var searchData=
[
  ['unmapmemobject_6586',['UnMapMemObject',['../classcl_1_1sycl_1_1detail_1_1UnMapMemObject.html',1,'cl::sycl::detail']]],
  ['updatehostrequirementcommand_6587',['UpdateHostRequirementCommand',['../classcl_1_1sycl_1_1detail_1_1UpdateHostRequirementCommand.html',1,'cl::sycl::detail']]],
  ['us_6588',['Us',['../unioncl_1_1sycl_1_1ONEAPI_1_1Us.html',1,'cl::sycl::ONEAPI']]],
  ['use_5fdefault_5fstream_6589',['use_default_stream',['../classcl_1_1sycl_1_1property_1_1queue_1_1cuda_1_1use__default__stream.html',1,'cl::sycl::property::queue::cuda']]],
  ['use_5fhost_5fptr_6590',['use_host_ptr',['../classcl_1_1sycl_1_1property_1_1image_1_1use__host__ptr.html',1,'cl::sycl::property::image::use_host_ptr'],['../classcl_1_1sycl_1_1property_1_1buffer_1_1use__host__ptr.html',1,'cl::sycl::property::buffer::use_host_ptr']]],
  ['use_5fmutex_6591',['use_mutex',['../classcl_1_1sycl_1_1property_1_1buffer_1_1use__mutex.html',1,'cl::sycl::property::buffer::use_mutex'],['../classcl_1_1sycl_1_1property_1_1image_1_1use__mutex.html',1,'cl::sycl::property::image::use_mutex']]],
  ['use_5fpinned_5fhost_5fmemory_6592',['use_pinned_host_memory',['../classcl_1_1sycl_1_1ext_1_1oneapi_1_1property_1_1buffer_1_1use__pinned__host__memory.html',1,'cl::sycl::ext::oneapi::property::buffer']]],
  ['use_5fprimary_5fcontext_6593',['use_primary_context',['../classcl_1_1sycl_1_1property_1_1context_1_1cuda_1_1use__primary__context.html',1,'cl::sycl::property::context::cuda']]],
  ['usm_5fallocator_6594',['usm_allocator',['../classcl_1_1sycl_1_1usm__allocator.html',1,'cl::sycl']]],
  ['usmallocationexception_6595',['UsmAllocationException',['../classUsmAllocationException.html',1,'']]],
  ['usmalloccontext_6596',['USMAllocContext',['../classUSMAllocContext.html',1,'']]],
  ['usmallocimpl_6597',['USMAllocImpl',['../classUSMAllocContext_1_1USMAllocImpl.html',1,'USMAllocContext']]],
  ['usmdevicememoryalloc_6598',['USMDeviceMemoryAlloc',['../classUSMDeviceMemoryAlloc.html',1,'']]],
  ['usmhostmemoryalloc_6599',['USMHostMemoryAlloc',['../classUSMHostMemoryAlloc.html',1,'']]],
  ['usmmemoryallocbase_6600',['USMMemoryAllocBase',['../classUSMMemoryAllocBase.html',1,'']]],
  ['usmsharedmemoryalloc_6601',['USMSharedMemoryAlloc',['../classUSMSharedMemoryAlloc.html',1,'']]],
  ['uu_6602',['Uu',['../unioncl_1_1sycl_1_1ONEAPI_1_1Uu.html',1,'cl::sycl::ONEAPI']]]
];
