var searchData=
[
  ['unmapmemobject_6333',['UnMapMemObject',['../classcl_1_1sycl_1_1detail_1_1UnMapMemObject.html',1,'cl::sycl::detail']]],
  ['updatehostrequirementcommand_6334',['UpdateHostRequirementCommand',['../classcl_1_1sycl_1_1detail_1_1UpdateHostRequirementCommand.html',1,'cl::sycl::detail']]],
  ['us_6335',['Us',['../unioncl_1_1sycl_1_1ONEAPI_1_1Us.html',1,'cl::sycl::ONEAPI']]],
  ['use_5fhost_5fptr_6336',['use_host_ptr',['../classcl_1_1sycl_1_1property_1_1buffer_1_1use__host__ptr.html',1,'cl::sycl::property::buffer::use_host_ptr'],['../classcl_1_1sycl_1_1property_1_1image_1_1use__host__ptr.html',1,'cl::sycl::property::image::use_host_ptr']]],
  ['use_5fmutex_6337',['use_mutex',['../classcl_1_1sycl_1_1property_1_1buffer_1_1use__mutex.html',1,'cl::sycl::property::buffer::use_mutex'],['../classcl_1_1sycl_1_1property_1_1image_1_1use__mutex.html',1,'cl::sycl::property::image::use_mutex']]],
  ['use_5fpinned_5fhost_5fmemory_6338',['use_pinned_host_memory',['../classcl_1_1sycl_1_1ext_1_1oneapi_1_1property_1_1buffer_1_1use__pinned__host__memory.html',1,'cl::sycl::ext::oneapi::property::buffer']]],
  ['use_5fprimary_5fcontext_6339',['use_primary_context',['../classcl_1_1sycl_1_1property_1_1context_1_1cuda_1_1use__primary__context.html',1,'cl::sycl::property::context::cuda']]],
  ['usm_5fallocator_6340',['usm_allocator',['../classcl_1_1sycl_1_1usm__allocator.html',1,'cl::sycl']]],
  ['usmallocationexception_6341',['UsmAllocationException',['../classUsmAllocationException.html',1,'']]],
  ['usmalloccontext_6342',['USMAllocContext',['../classUSMAllocContext.html',1,'']]],
  ['usmallocimpl_6343',['USMAllocImpl',['../classUSMAllocContext_1_1USMAllocImpl.html',1,'USMAllocContext']]],
  ['usmdevicememoryalloc_6344',['USMDeviceMemoryAlloc',['../classUSMDeviceMemoryAlloc.html',1,'']]],
  ['usmhostmemoryalloc_6345',['USMHostMemoryAlloc',['../classUSMHostMemoryAlloc.html',1,'']]],
  ['usmmemoryallocbase_6346',['USMMemoryAllocBase',['../classUSMMemoryAllocBase.html',1,'']]],
  ['usmsharedmemoryalloc_6347',['USMSharedMemoryAlloc',['../classUSMSharedMemoryAlloc.html',1,'']]],
  ['uu_6348',['Uu',['../unioncl_1_1sycl_1_1ONEAPI_1_1Uu.html',1,'cl::sycl::ONEAPI']]]
];
