clang: lib/Headers/__clang_cuda_math.h File Reference
__clang_cuda_math.h File Reference
Macros
#define __DEVICE__ static __device__ __forceinline__
#define __DEVICE_VOID__ __DEVICE__
#define __FAST_OR_SLOW(fast, slow) slow
Functions
__DEVICE__ int abs (int __a)
__DEVICE__ double fabs (double __a)
__DEVICE__ double acos (double __a)
__DEVICE__ float acosf (float __a)
__DEVICE__ double acosh (double __a)
__DEVICE__ float acoshf (float __a)
__DEVICE__ double asin (double __a)
__DEVICE__ float asinf (float __a)
__DEVICE__ double asinh (double __a)
__DEVICE__ float asinhf (float __a)
__DEVICE__ double atan (double __a)
__DEVICE__ double atan2 (double __a, double __b)
__DEVICE__ float atan2f (float __a, float __b)
__DEVICE__ float atanf (float __a)
__DEVICE__ double atanh (double __a)
__DEVICE__ float atanhf (float __a)
__DEVICE__ double cbrt (double __a)
__DEVICE__ float cbrtf (float __a)
__DEVICE__ double ceil (double __a)
__DEVICE__ float ceilf (float __a)
__DEVICE__ double copysign (double __a, double __b)
__DEVICE__ float copysignf (float __a, float __b)
__DEVICE__ double cos (double __a)
__DEVICE__ float cosf (float __a)
__DEVICE__ double cosh (double __a)
__DEVICE__ float coshf (float __a)
__DEVICE__ double cospi (double __a)
__DEVICE__ float cospif (float __a)
__DEVICE__ double cyl_bessel_i0 (double __a)
__DEVICE__ float cyl_bessel_i0f (float __a)
__DEVICE__ double cyl_bessel_i1 (double __a)
__DEVICE__ float cyl_bessel_i1f (float __a)
__DEVICE__ double erf (double __a)
__DEVICE__ double erfc (double __a)
__DEVICE__ float erfcf (float __a)
__DEVICE__ double erfcinv (double __a)
__DEVICE__ float erfcinvf (float __a)
__DEVICE__ double erfcx (double __a)
__DEVICE__ float erfcxf (float __a)
__DEVICE__ float erff (float __a)
__DEVICE__ double erfinv (double __a)
__DEVICE__ float erfinvf (float __a)
__DEVICE__ double exp (double __a)
__DEVICE__ double exp10 (double __a)
__DEVICE__ float exp10f (float __a)
__DEVICE__ double exp2 (double __a)
__DEVICE__ float exp2f (float __a)
__DEVICE__ float expf (float __a)
__DEVICE__ double expm1 (double __a)
__DEVICE__ float expm1f (float __a)
__DEVICE__ float fabsf (float __a)
__DEVICE__ double fdim (double __a, double __b)
__DEVICE__ float fdimf (float __a, float __b)
__DEVICE__ double fdivide (double __a, double __b)
__DEVICE__ float fdividef (float __a, float __b)
__DEVICE__ double floor (double __f)
__DEVICE__ float floorf (float __f)
__DEVICE__ double fma (double __a, double __b, double __c)
__DEVICE__ float fmaf (float __a, float __b, float __c)
__DEVICE__ double fmax (double __a, double __b)
__DEVICE__ float fmaxf (float __a, float __b)
__DEVICE__ double fmin (double __a, double __b)
__DEVICE__ float fminf (float __a, float __b)
__DEVICE__ double fmod (double __a, double __b)
__DEVICE__ float fmodf (float __a, float __b)
__DEVICE__ double frexp (double __a, int *__b)
__DEVICE__ float frexpf (float __a, int *__b)
__DEVICE__ double hypot (double __a, double __b)
__DEVICE__ float hypotf (float __a, float __b)
__DEVICE__ int ilogb (double __a)
__DEVICE__ int ilogbf (float __a)
__DEVICE__ double j0 (double __a)
__DEVICE__ float j0f (float __a)
__DEVICE__ double j1 (double __a)
__DEVICE__ float j1f (float __a)
__DEVICE__ double jn (int __n, double __a)
__DEVICE__ float jnf (int __n, float __a)
__DEVICE__ long labs (long __a)
__DEVICE__ double ldexp (double __a, int __b)
__DEVICE__ float ldexpf (float __a, int __b)
__DEVICE__ double lgamma (double __a)
__DEVICE__ float lgammaf (float __a)
__DEVICE__ long long llabs (long long __a)
__DEVICE__ long long llmax (long long __a, long long __b)
__DEVICE__ long long llmin (long long __a, long long __b)
__DEVICE__ long long llrint (double __a)
__DEVICE__ long long llrintf (float __a)
__DEVICE__ long long llround (double __a)
__DEVICE__ long long llroundf (float __a)
__DEVICE__ double round (double __a)
__DEVICE__ float roundf (float __a)
__DEVICE__ double log (double __a)
__DEVICE__ double log10 (double __a)
__DEVICE__ float log10f (float __a)
__DEVICE__ double log1p (double __a)
__DEVICE__ float log1pf (float __a)
__DEVICE__ double log2 (double __a)
__DEVICE__ float log2f (float __a)
__DEVICE__ double logb (double __a)
__DEVICE__ float logbf (float __a)
__DEVICE__ float logf (float __a)
__DEVICE__ long lrint (double __a)
__DEVICE__ long lrintf (float __a)
__DEVICE__ long lround (double __a)
__DEVICE__ long lroundf (float __a)
__DEVICE__ int max (int __a, int __b)
__DEVICE__ int min (int __a, int __b)
__DEVICE__ double modf (double __a, double *__b)
__DEVICE__ float modff (float __a, float *__b)
__DEVICE__ double nearbyint (double __a)
__DEVICE__ float nearbyintf (float __a)
__DEVICE__ double nextafter (double __a, double __b)
__DEVICE__ float nextafterf (float __a, float __b)
__DEVICE__ double norm (int __dim, const double *__t)
__DEVICE__ double norm3d (double __a, double __b, double __c)
__DEVICE__ float norm3df (float __a, float __b, float __c)
__DEVICE__ double norm4d (double __a, double __b, double __c, double __d)
__DEVICE__ float norm4df (float __a, float __b, float __c, float __d)
__DEVICE__ double normcdf (double __a)
__DEVICE__ float normcdff (float __a)
__DEVICE__ double normcdfinv (double __a)
__DEVICE__ float normcdfinvf (float __a)
__DEVICE__ float normf (int __dim, const float *__t)
__DEVICE__ double pow (double __a, double __b)
__DEVICE__ float powf (float __a, float __b)
__DEVICE__ double powi (double __a, int __b)
__DEVICE__ float powif (float __a, int __b)
__DEVICE__ double rcbrt (double __a)
__DEVICE__ float rcbrtf (float __a)
__DEVICE__ double remainder (double __a, double __b)
__DEVICE__ float remainderf (float __a, float __b)
__DEVICE__ double remquo (double __a, double __b, int *__c)
__DEVICE__ float remquof (float __a, float __b, int *__c)
__DEVICE__ double rhypot (double __a, double __b)
__DEVICE__ float rhypotf (float __a, float __b)
__DEVICE__ double rint (double __a)
__DEVICE__ float rintf (float __a)
__DEVICE__ double rnorm (int __a, const double *__b)
__DEVICE__ double rnorm3d (double __a, double __b, double __c)
__DEVICE__ float rnorm3df (float __a, float __b, float __c)
__DEVICE__ double rnorm4d (double __a, double __b, double __c, double __d)
__DEVICE__ float rnorm4df (float __a, float __b, float __c, float __d)
__DEVICE__ float rnormf (int __dim, const float *__t)
__DEVICE__ double rsqrt (double __a)
__DEVICE__ float rsqrtf (float __a)
__DEVICE__ double scalbn (double __a, int __b)
__DEVICE__ float scalbnf (float __a, int __b)
__DEVICE__ double scalbln (double __a, long __b)
__DEVICE__ float scalblnf (float __a, long __b)
__DEVICE__ double sin (double __a)
__DEVICE_VOID__ void sincos (double __a, double *__s, double *__c)
__DEVICE_VOID__ void sincosf (float __a, float *__s, float *__c)
__DEVICE_VOID__ void sincospi (double __a, double *__s, double *__c)
__DEVICE_VOID__ void sincospif (float __a, float *__s, float *__c)
__DEVICE__ float sinf (float __a)
__DEVICE__ double sinh (double __a)
__DEVICE__ float sinhf (float __a)
__DEVICE__ double sinpi (double __a)
__DEVICE__ float sinpif (float __a)
__DEVICE__ double sqrt (double __a)
__DEVICE__ float sqrtf (float __a)
__DEVICE__ double tan (double __a)
__DEVICE__ float tanf (float __a)
__DEVICE__ double tanh (double __a)
__DEVICE__ float tanhf (float __a)
__DEVICE__ double tgamma (double __a)
__DEVICE__ float tgammaf (float __a)
__DEVICE__ double trunc (double __a)
__DEVICE__ float truncf (float __a)
__DEVICE__ unsigned long long ullmax (unsigned long long __a, unsigned long long __b)
__DEVICE__ unsigned long long ullmin (unsigned long long __a, unsigned long long __b)
__DEVICE__ unsigned int umax (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int umin (unsigned int __a, unsigned int __b)
__DEVICE__ double y0 (double __a)
__DEVICE__ float y0f (float __a)
__DEVICE__ double y1 (double __a)
__DEVICE__ float y1f (float __a)
__DEVICE__ double yn (int __a, double __b)
__DEVICE__ float ynf (int __a, float __b)
Macro Definition Documentation
__DEVICE__
#define __DEVICE__ static __device__ __forceinline__
Definition at line 32 of file __clang_cuda_math.h.
__DEVICE_VOID__
#define __DEVICE_VOID__ __DEVICE__
Definition at line 42 of file __clang_cuda_math.h.
__FAST_OR_SLOW
#define __FAST_OR_SLOW (fast, slow) slow
Definition at line 53 of file __clang_cuda_math.h.
Function Documentation
abs()
__DEVICE__ int abs (int __a)
Definition at line 56 of file __clang_cuda_math.h.
References __a, and __nv_abs().
acos()
__DEVICE__ double acos (double __a)
Definition at line 58 of file __clang_cuda_math.h.
acosf()
__DEVICE__ float acosf (float __a)
Definition at line 59 of file __clang_cuda_math.h.
References __a, and __nv_acosf().
Referenced by __tg_acos(), and acos().
acosh()
__DEVICE__ double acosh (double __a)
Definition at line 60 of file __clang_cuda_math.h.
acoshf()
__DEVICE__ float acoshf (float __a)
Definition at line 61 of file __clang_cuda_math.h.
References __a, and __nv_acoshf().
Referenced by __tg_acosh().
asin()
__DEVICE__ double asin (double __a)
Definition at line 62 of file __clang_cuda_math.h.
asinf()
__DEVICE__ float asinf (float __a)
Definition at line 63 of file __clang_cuda_math.h.
References __a, and __nv_asinf().
Referenced by __tg_asin(), and asin().
asinh()
__DEVICE__ double asinh (double __a)
Definition at line 64 of file __clang_cuda_math.h.
asinhf()
__DEVICE__ float asinhf (float __a)
Definition at line 65 of file __clang_cuda_math.h.
References __a, and __nv_asinhf().
Referenced by __tg_asinh().
atan()
__DEVICE__ double atan (double __a)
Definition at line 66 of file __clang_cuda_math.h.
atan2()
__DEVICE__ double atan2 (double __a, double __b)
Definition at line 67 of file __clang_cuda_math.h.
atan2f()
__DEVICE__ float atan2f (float __a, float __b)
Definition at line 68 of file __clang_cuda_math.h.
References __a, __b, and __nv_atan2f().
Referenced by __tg_atan2(), __tg_carg(), std::arg(), and atan2().
atanf()
__DEVICE__ float atanf (float __a)
Definition at line 69 of file __clang_cuda_math.h.
References __a, and __nv_atanf().
Referenced by __tg_atan(), and atan().
atanh()
__DEVICE__ double atanh (double __a)
Definition at line 70 of file __clang_cuda_math.h.
atanhf()
__DEVICE__ float atanhf (float __a)
Definition at line 71 of file __clang_cuda_math.h.
References __a, and __nv_atanhf().
Referenced by __tg_atanh().
cbrt()
__DEVICE__ double cbrt (double __a)
Definition at line 72 of file __clang_cuda_math.h.
cbrtf()
__DEVICE__ float cbrtf (float __a)
Definition at line 73 of file __clang_cuda_math.h.
References __a, and __nv_cbrtf().
Referenced by __tg_cbrt().
ceil()
__DEVICE__ double ceil (double __a)
Definition at line 74 of file __clang_cuda_math.h.
ceilf()
__DEVICE__ float ceilf (float __a)
Definition at line 75 of file __clang_cuda_math.h.
References __a, and __nv_ceilf().
Referenced by __tg_ceil(), and ceil().
copysign()
__DEVICE__ double copysign (double __a, double __b)
Definition at line 76 of file __clang_cuda_math.h.
copysignf()
__DEVICE__ float copysignf (float __a, float __b)
Definition at line 79 of file __clang_cuda_math.h.
References __a, __b, and __nv_copysignf().
Referenced by __tg_copysign().
cos()
__DEVICE__ double cos (double __a)
Definition at line 82 of file __clang_cuda_math.h.
cosf()
__DEVICE__ float cosf (float __a)
Definition at line 83 of file __clang_cuda_math.h.
References __a, __FAST_OR_SLOW, __nv_cosf(), and __nv_fast_cosf().
Referenced by __tg_cos(), and cos().
cosh()
__DEVICE__ double cosh (double __a)
Definition at line 86 of file __clang_cuda_math.h.
coshf()
__DEVICE__ float coshf (float __a)
Definition at line 87 of file __clang_cuda_math.h.
References __a, and __nv_coshf().
Referenced by __tg_cosh(), and cosh().
cospi()
__DEVICE__ double cospi (double __a)
Definition at line 88 of file __clang_cuda_math.h.
References __a, and __nv_cospi().
cospif()
__DEVICE__ float cospif (float __a)
Definition at line 89 of file __clang_cuda_math.h.
References __a, and __nv_cospif().
cyl_bessel_i0()
__DEVICE__ double cyl_bessel_i0 (double __a)
Definition at line 90 of file __clang_cuda_math.h.
References __a, and __nv_cyl_bessel_i0().
cyl_bessel_i0f()
__DEVICE__ float cyl_bessel_i0f (float __a)
Definition at line 91 of file __clang_cuda_math.h.
References __a, and __nv_cyl_bessel_i0f().
cyl_bessel_i1()
__DEVICE__ double cyl_bessel_i1 (double __a)
Definition at line 92 of file __clang_cuda_math.h.
References __a, and __nv_cyl_bessel_i1().
cyl_bessel_i1f()
__DEVICE__ float cyl_bessel_i1f (float __a)
Definition at line 93 of file __clang_cuda_math.h.
References __a, and __nv_cyl_bessel_i1f().
erf()
__DEVICE__ double erf (double __a)
Definition at line 94 of file __clang_cuda_math.h.
erfc()
__DEVICE__ double erfc (double __a)
Definition at line 95 of file __clang_cuda_math.h.
erfcf()
__DEVICE__ float erfcf (float __a)
Definition at line 96 of file __clang_cuda_math.h.
References __a, and __nv_erfcf().
Referenced by __tg_erfc().
erfcinv()
__DEVICE__ double erfcinv (double __a)
Definition at line 97 of file __clang_cuda_math.h.
References __a, and __nv_erfcinv().
erfcinvf()
__DEVICE__ float erfcinvf (float __a)
Definition at line 98 of file __clang_cuda_math.h.
References __a, and __nv_erfcinvf().
erfcx()
__DEVICE__ double erfcx (double __a)
Definition at line 99 of file __clang_cuda_math.h.
References __a, and __nv_erfcx().
erfcxf()
__DEVICE__ float erfcxf (float __a)
Definition at line 100 of file __clang_cuda_math.h.
References __a, and __nv_erfcxf().
erff()
__DEVICE__ float erff (float __a)
Definition at line 101 of file __clang_cuda_math.h.
References __a, and __nv_erff().
Referenced by __tg_erf().
erfinv()
__DEVICE__ double erfinv (double __a)
Definition at line 102 of file __clang_cuda_math.h.
References __a, and __nv_erfinv().
erfinvf()
__DEVICE__ float erfinvf (float __a)
Definition at line 103 of file __clang_cuda_math.h.
References __a, and __nv_erfinvf().
exp()
__DEVICE__ double exp (double __a)
Definition at line 104 of file __clang_cuda_math.h.
exp10()
__DEVICE__ double exp10 (double __a)
Definition at line 105 of file __clang_cuda_math.h.
References __a, and __nv_exp10().
exp10f()
__DEVICE__ float exp10f (float __a)
Definition at line 106 of file __clang_cuda_math.h.
References __a, and __nv_exp10f().
exp2()
__DEVICE__ double exp2 (double __a)
Definition at line 107 of file __clang_cuda_math.h.
exp2f()
__DEVICE__ float exp2f (float __a)
Definition at line 108 of file __clang_cuda_math.h.
References __a, and __nv_exp2f().
Referenced by __tg_exp2().
expf()
__DEVICE__ float expf (float __a)
Definition at line 109 of file __clang_cuda_math.h.
References __a, and __nv_expf().
Referenced by __tg_exp(), and exp().
expm1()
__DEVICE__ double expm1 (double __a)
Definition at line 110 of file __clang_cuda_math.h.
expm1f()
__DEVICE__ float expm1f (float __a)
Definition at line 111 of file __clang_cuda_math.h.
References __a, and __nv_expm1f().
Referenced by __tg_expm1().
fabs()
__DEVICE__ double fabs (double __a)
Definition at line 57 of file __clang_cuda_math.h.
fabsf()
__DEVICE__ float fabsf (float __a)
Definition at line 112 of file __clang_cuda_math.h.
References __a, and __nv_fabsf().
Referenced by __tg_fabs(), abs(), and fabs().
fdim()
__DEVICE__ double fdim (double __a, double __b)
Definition at line 113 of file __clang_cuda_math.h.
fdimf()
__DEVICE__ float fdimf (float __a, float __b)
Definition at line 114 of file __clang_cuda_math.h.
References __a, __b, and __nv_fdimf().
Referenced by __tg_fdim().
fdivide()
__DEVICE__ double fdivide (double __a, double __b)
Definition at line 115 of file __clang_cuda_math.h.
References __a, and __b.
fdividef()
__DEVICE__ float fdividef (float __a, float __b)
Definition at line 116 of file __clang_cuda_math.h.
References __a, __b, and __nv_fast_fdividef().
floor()
__DEVICE__ double floor (double __f)
Definition at line 123 of file __clang_cuda_math.h.
floorf()
__DEVICE__ float floorf (float __f)
Definition at line 124 of file __clang_cuda_math.h.
References __nv_floorf().
Referenced by __tg_floor(), and floor().
fma()
__DEVICE__ double fma (double __a, double __b, double __c)
Definition at line 125 of file __clang_cuda_math.h.
fmaf()
__DEVICE__ float fmaf (float __a, float __b, float __c)
Definition at line 128 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_fmaf().
Referenced by __tg_fma().
fmax()
__DEVICE__ double fmax (double __a, double __b)
Definition at line 131 of file __clang_cuda_math.h.
fmaxf()
__DEVICE__ float fmaxf (float __a, float __b)
Definition at line 132 of file __clang_cuda_math.h.
References __a, __b, and __nv_fmaxf().
Referenced by __tg_fmax().
fmin()
__DEVICE__ double fmin (double __a, double __b)
Definition at line 133 of file __clang_cuda_math.h.
fminf()
__DEVICE__ float fminf (float __a, float __b)
Definition at line 134 of file __clang_cuda_math.h.
References __a, __b, and __nv_fminf().
Referenced by __tg_fmin().
fmod()
__DEVICE__ double fmod (double __a, double __b)
Definition at line 135 of file __clang_cuda_math.h.
fmodf()
__DEVICE__ float fmodf (float __a, float __b)
Definition at line 136 of file __clang_cuda_math.h.
References __a, __b, and __nv_fmodf().
Referenced by __tg_fmod(), and fmod().
frexp()
__DEVICE__ double frexp (double __a, int * __b)
Definition at line 137 of file __clang_cuda_math.h.
frexpf()
__DEVICE__ float frexpf (float __a, int * __b)
Definition at line 138 of file __clang_cuda_math.h.
References __a, __b, and __nv_frexpf().
Referenced by __tg_frexp(), and frexp().
hypot()
__DEVICE__ double hypot (double __a, double __b)
Definition at line 139 of file __clang_cuda_math.h.
hypotf()
__DEVICE__ float hypotf (float __a, float __b)
Definition at line 140 of file __clang_cuda_math.h.
References __a, __b, and __nv_hypotf().
Referenced by __tg_hypot().
ilogb()
__DEVICE__ int ilogb (double __a)
Definition at line 141 of file __clang_cuda_math.h.
ilogbf()
__DEVICE__ int ilogbf (float __a)
Definition at line 142 of file __clang_cuda_math.h.
References __a, and __nv_ilogbf().
Referenced by __tg_ilogb().
j0()
__DEVICE__ double j0 (double __a)
Definition at line 143 of file __clang_cuda_math.h.
References __a, and __nv_j0().
j0f()
__DEVICE__ float j0f (float __a)
Definition at line 144 of file __clang_cuda_math.h.
References __a, and __nv_j0f().
j1()
__DEVICE__ double j1 (double __a)
Definition at line 145 of file __clang_cuda_math.h.
References __a, and __nv_j1().
j1f()
__DEVICE__ float j1f (float __a)
Definition at line 146 of file __clang_cuda_math.h.
References __a, and __nv_j1f().
jn()
__DEVICE__ double jn (int __n, double __a)
Definition at line 147 of file __clang_cuda_math.h.
References __a, and __nv_jn().
jnf()
__DEVICE__ float jnf (int __n, float __a)
Definition at line 148 of file __clang_cuda_math.h.
References __a, and __nv_jnf().
labs()
__DEVICE__ long labs (long __a)
Definition at line 152 of file __clang_cuda_math.h.
References __a, and __nv_abs().
Referenced by abs().
ldexp()
__DEVICE__ double ldexp (double __a, int __b)
Definition at line 154 of file __clang_cuda_math.h.
ldexpf()
__DEVICE__ float ldexpf (float __a, int __b)
Definition at line 155 of file __clang_cuda_math.h.
References __a, __b, and __nv_ldexpf().
Referenced by __tg_ldexp(), and ldexp().
lgamma()
__DEVICE__ double lgamma (double __a)
Definition at line 156 of file __clang_cuda_math.h.
lgammaf()
__DEVICE__ float lgammaf (float __a)
Definition at line 157 of file __clang_cuda_math.h.
References __a, and __nv_lgammaf().
Referenced by __tg_lgamma().
llabs()
__DEVICE__ long long llabs (long long __a)
Definition at line 158 of file __clang_cuda_math.h.
References __a, and __nv_llabs().
Referenced by abs().
llmax()
__DEVICE__ long long llmax (long long __a, long long __b)
Definition at line 159 of file __clang_cuda_math.h.
References __a, __b, and __nv_llmax().
llmin()
__DEVICE__ long long llmin (long long __a, long long __b)
Definition at line 162 of file __clang_cuda_math.h.
References __a, __b, and __nv_llmin().
llrint()
__DEVICE__ long long llrint (double __a)
Definition at line 165 of file __clang_cuda_math.h.
llrintf()
__DEVICE__ long long llrintf (float __a)
Definition at line 166 of file __clang_cuda_math.h.
References __a, and __nv_llrintf().
Referenced by __tg_llrint().
llround()
__DEVICE__ long long llround (double __a)
Definition at line 167 of file __clang_cuda_math.h.
References __a, and __nv_llround().
llroundf()
__DEVICE__ long long llroundf (float __a)
Definition at line 168 of file __clang_cuda_math.h.
References __a, and __nv_llroundf().
Referenced by __tg_llround().
log()
__DEVICE__ double log (double __a)
Definition at line 171 of file __clang_cuda_math.h.
log10()
__DEVICE__ double log10 (double __a)
Definition at line 172 of file __clang_cuda_math.h.
log10f()
__DEVICE__ float log10f (float __a)
Definition at line 173 of file __clang_cuda_math.h.
References __a, and __nv_log10f().
Referenced by __tg_log10(), and log10().
log1p()
__DEVICE__ double log1p (double __a)
Definition at line 174 of file __clang_cuda_math.h.
log1pf()
__DEVICE__ float log1pf (float __a)
Definition at line 175 of file __clang_cuda_math.h.
References __a, and __nv_log1pf().
Referenced by __tg_log1p().
log2()
__DEVICE__ double log2 (double __a)
Definition at line 176 of file __clang_cuda_math.h.
log2f()
__DEVICE__ float log2f (float __a)
Definition at line 177 of file __clang_cuda_math.h.
References __a, __FAST_OR_SLOW, __nv_fast_log2f(), and __nv_log2f().
Referenced by __tg_log2().
logb()
__DEVICE__ double logb (double __a)
Definition at line 180 of file __clang_cuda_math.h.
logbf()
__DEVICE__ float logbf (float __a)
Definition at line 181 of file __clang_cuda_math.h.
References __a, and __nv_logbf().
Referenced by __tg_logb().
logf()
__DEVICE__ float logf (float __a)
Definition at line 182 of file __clang_cuda_math.h.
References __a, __FAST_OR_SLOW, __nv_fast_logf(), and __nv_logf().
Referenced by __tg_log(), and log().
lrint()
__DEVICE__ long lrint (double __a)
Definition at line 191 of file __clang_cuda_math.h.
lrintf()
__DEVICE__ long lrintf (float __a)
Definition at line 192 of file __clang_cuda_math.h.
References __a, and __float2int_rn().
Referenced by __tg_lrint().
lround()
__DEVICE__ long lround (double __a)
Definition at line 193 of file __clang_cuda_math.h.
lroundf()
__DEVICE__ long lroundf (float __a)
Definition at line 194 of file __clang_cuda_math.h.
References __a, and roundf().
Referenced by __tg_lround().
max()
__DEVICE__ int max (int __a, int __b)
Definition at line 196 of file __clang_cuda_math.h.
References __a, __b, and __nv_max().
Referenced by clang::Sema::ActOnNumericConstant(), clang::tooling::Replacements::add(), Append(), clang::ento::RangedConstraintManager::assumeSymInclusiveRange(), clang::ento::RangedConstraintManager::assumeSymRel(), clang::Sema::BuildVectorType(), checkOpenMPLoop(), clamp(), clang::DiagnosticsEngine::Clear(), combineAndSortRanges(), computeBlockInfo(), convertUnsignedAPIntToCharUnits(), clang::ast_matchers::dynamic::internal::VariadicOperatorMatcherDescriptor::create(), clang::FunctionDecl::DefaultedFunctionInfo::Create(), clang::interp::Program::createDescriptor(), clang::tooling::dependencies::DependencyScanningFilesystemSharedCache::DependencyScanningFilesystemSharedCache(), emit(), clang::CodeGen::CodeGenFunction::EmitBranchOnBoolExpr(), clang::CodeGen::CodeGenFunction::EmitCall(), EmitCheckedMixedSignMultiply(), clang::CodeGen::CodeGenFunction::EmitConditionalOperatorLValue(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), EmitNullBaseClassInitialization(), clang::BuiltinTypeLoc::expandBuiltinRange(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::Sema::FormatStringHasSArg(), clang::ASTContext::getAlignOfGlobalVar(), clang::TypoCorrectionConsumer::getBestEditDistance(), clang::CodeGen::CodeGenFunction::getBlockByrefInfo(), clang::SrcMgr::ContentCache::getBufferOrNone(), clang::format::BreakableBlockComment::getContentStartColumn(), clang::ASTContext::getDeclAlign(), getDeclAvailability(), clang::NumericLiteralParser::GetFixedPointValue(), clang::TypeLoc::getFullDataSizeForType(), clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, PointerLikeLocInfo >::getLocalDataAlignment(), clang::Decl::getMaxAlignment(), clang::DynamicAllocLValue::getMaxIndex(), clang::targets::MicrosoftARM64TargetInfo::getMinGlobalAlign(), clang::CodeGen::CodeGenModule::getMinimumClassObjectSize(), clang::TargetInfo::getNewAlign(), getNextAggregateIndexAfterDesignatedInit(), clang::DiagnosticsEngine::getNumOverloadCandidatesToShow(), clang::ASTContext::getObjCEncodingTypeSize(), clang::ASTContext::getPreferredTypeAlign(), getRangeForType(), clang::PrecompiledPreamble::getSize(), clang::Preprocessor::HandleEndOfFile(), clang::targets::X86TargetInfo::handleTargetFeatures(), clang::targets::MipsTargetInfo::handleTargetFeatures(), clang::VarDecl::hasDefinition(), clang::ast_matchers::dynamic::VariantValue::isConvertibleTo(), clang::DiagnosticsEngine::isDiagnosticInFlight(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), isSpecialMixedSignMultiply(), clang::sema::AnalysisBasedWarnings::IssueWarnings(), clang::MangleContext::mangleObjCMethodName(), clang::format::maxNestingDepth(), maybeAddRange(), ParseFrontendArgs(), clang::DarwinSDKInfo::RelatedTargetVersionMapping::parseJSON(), clang::format::CommaSeparatedList::precomputeFormattingInfos(), clang::ento::CheckerRegistryData::printCheckerWithDescList(), PrintDiagnosticCategories(), clang::Sema::RefersToMemberWithReducedAlignment(), clang::format::WhitespaceManager::replaceWhitespaceInToken(), clang::DiagnosticsEngine::Report(), clang::DiagnosticsEngine::Reset(), selectInterestingSourceRegion(), sumOffsets(), and TargetMVPriority().
min()
__DEVICE__ int min (int __a, int __b)
Definition at line 197 of file __clang_cuda_math.h.
References __a, __b, and __nv_min().
Referenced by clang::Sema::ActOnFinishSwitchStmt(), clang::Sema::CheckNonDependentConversions(), clamp(), clang::DeclarationName::compare(), clang::driver::tools::Clang::ConstructJob(), createHash(), clang::CodeGen::CodeGenFunction::EmitConditionalOperatorLValue(), clang::ento::CoreEngine::ExecuteWorkList(), clang::BuiltinTypeLoc::expandBuiltinRange(), FindDesignatorMismatch(), clang::CodeGen::swiftcall::SwiftAggLowering::finish(), clang::Sema::FormatStringHasSArg(), clang::ASTContext::getDeclAlign(), getDerivedToBaseAlignmentAndOffset(), clang::CodeGen::CodeGenModule::getDynamicOffsetAlignment(), GetExprRange(), clang::NumericLiteralParser::GetFloatValue(), clang::CodeGen::CodeGenModule::GetVCallVisibilityLevel(), llvm::yaml::MappingTraits< FormatStyle::SpacesInLineComment >::mapping(), maybeAddRange(), clang::format::CommaSeparatedList::precomputeFormattingInfos(), printWordWrapped(), profileIntValue(), clang::Sema::RefersToMemberWithReducedAlignment(), renderDebugOptions(), selectInterestingSourceRegion(), and TryPrintAsStringLiteral().
modf()
__DEVICE__ double modf (double __a, double * __b)
Definition at line 198 of file __clang_cuda_math.h.
modff()
__DEVICE__ float modff (float __a, float * __b)
Definition at line 199 of file __clang_cuda_math.h.
References __a, __b, and __nv_modff().
Referenced by modf().
nearbyint()
__DEVICE__ double nearbyint (double __a)
Definition at line 200 of file __clang_cuda_math.h.
nearbyintf()
__DEVICE__ float nearbyintf (float __a)
Definition at line 201 of file __clang_cuda_math.h.
References __a.
Referenced by __tg_nearbyint().
nextafter()
__DEVICE__ double nextafter (double __a, double __b)
Definition at line 202 of file __clang_cuda_math.h.
nextafterf()
__DEVICE__ float nextafterf (float __a, float __b)
Definition at line 205 of file __clang_cuda_math.h.
References __a, __b, and __nv_nextafterf().
Referenced by __tg_nextafter().
norm()
__DEVICE__ double norm (int __dim, const double * __t)
Definition at line 208 of file __clang_cuda_math.h.
References __nv_norm().
norm3d()
__DEVICE__ double norm3d (double __a, double __b, double __c)
Definition at line 211 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_norm3d().
norm3df()
__DEVICE__ float norm3df (float __a, float __b, float __c)
Definition at line 214 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_norm3df().
norm4d()
__DEVICE__ double norm4d (double __a, double __b, double __c, double __d)
Definition at line 217 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_norm4d().
norm4df()
__DEVICE__ float norm4df (float __a, float __b, float __c, float __d)
Definition at line 220 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_norm4df().
normcdf()
__DEVICE__ double normcdf (double __a)
Definition at line 223 of file __clang_cuda_math.h.
References __a, and __nv_normcdf().
normcdff()
__DEVICE__ float normcdff (float __a)
Definition at line 224 of file __clang_cuda_math.h.
References __a, and __nv_normcdff().
normcdfinv()
__DEVICE__ double normcdfinv (double __a)
Definition at line 225 of file __clang_cuda_math.h.
References __a, and __nv_normcdfinv().
normcdfinvf()
__DEVICE__ float normcdfinvf (float __a)
Definition at line 226 of file __clang_cuda_math.h.
References __a, and __nv_normcdfinvf().
normf()
__DEVICE__ float normf (int __dim, const float * __t)
Definition at line 227 of file __clang_cuda_math.h.
References __nv_normf().
pow()
__DEVICE__ double pow (double __a, double __b)
Definition at line 230 of file __clang_cuda_math.h.
powf()
__DEVICE__ float powf (float __a, float __b)
Definition at line 231 of file __clang_cuda_math.h.
References __a, __b, and __nv_powf().
Referenced by __tg_pow(), and pow().
powi()
__DEVICE__ double powi (double __a, int __b)
Definition at line 232 of file __clang_cuda_math.h.
References __a, __b, and __nv_powi().
Referenced by pow().
powif()
__DEVICE__ float powif (float __a, int __b)
Definition at line 233 of file __clang_cuda_math.h.
References __a, __b, and __nv_powif().
Referenced by pow().
rcbrt()
__DEVICE__ double rcbrt (double __a)
Definition at line 234 of file __clang_cuda_math.h.
References __a, and __nv_rcbrt().
rcbrtf()
__DEVICE__ float rcbrtf (float __a)
Definition at line 235 of file __clang_cuda_math.h.
References __a, and __nv_rcbrtf().
remainder()
__DEVICE__ double remainder (double __a, double __b)
Definition at line 236 of file __clang_cuda_math.h.
remainderf()
__DEVICE__ float remainderf (float __a, float __b)
Definition at line 239 of file __clang_cuda_math.h.
References __a, __b, and __nv_remainderf().
Referenced by __tg_remainder().
remquo()
__DEVICE__ double remquo (double __a, double __b, int * __c)
Definition at line 242 of file __clang_cuda_math.h.
remquof()
__DEVICE__ float remquof (float __a, float __b, int * __c)
Definition at line 245 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_remquof().
Referenced by __tg_remquo().
rhypot()
__DEVICE__ double rhypot (double __a, double __b)
Definition at line 248 of file __clang_cuda_math.h.
References __a, __b, and __nv_rhypot().
rhypotf()
__DEVICE__ float rhypotf (float __a, float __b)
Definition at line 251 of file __clang_cuda_math.h.
References __a, __b, and __nv_rhypotf().
rint()
__DEVICE__ double rint (double __a)
Definition at line 255 of file __clang_cuda_math.h.
Referenced by lrint().
rintf()
__DEVICE__ float rintf (float __a)
Definition at line 256 of file __clang_cuda_math.h.
References __a.
Referenced by __tg_rint().
rnorm()
__DEVICE__ double rnorm (int __a, const double * __b)
Definition at line 257 of file __clang_cuda_math.h.
References __a, __b, and __nv_rnorm().
rnorm3d()
__DEVICE__ double rnorm3d (double __a, double __b, double __c)
Definition at line 260 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_rnorm3d().
rnorm3df()
__DEVICE__ float rnorm3df (float __a, float __b, float __c)
Definition at line 263 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_rnorm3df().
rnorm4d()
__DEVICE__ double rnorm4d (double __a, double __b, double __c, double __d)
Definition at line 266 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_rnorm4d().
rnorm4df()
__DEVICE__ float rnorm4df (float __a, float __b, float __c, float __d)
Definition at line 269 of file __clang_cuda_math.h.
References __a, __b, __c, and __nv_rnorm4df().
rnormf()
__DEVICE__ float rnormf (int __dim, const float * __t)
Definition at line 272 of file __clang_cuda_math.h.
References __nv_rnormf().
round()
__DEVICE__ double round (double __a)
Definition at line 169 of file __clang_cuda_math.h.
Referenced by lround().
roundf()
__DEVICE__ float roundf (float __a)
Definition at line 170 of file __clang_cuda_math.h.
References __a, and __nv_roundf().
Referenced by __tg_round(), and lroundf().
rsqrt()
__DEVICE__ double rsqrt (double __a)
Definition at line 275 of file __clang_cuda_math.h.
References __a, and __nv_rsqrt().
rsqrtf()
__DEVICE__ float rsqrtf (float __a)
Definition at line 276 of file __clang_cuda_math.h.
References __a, and __nv_rsqrtf().
scalbln()
__DEVICE__ double scalbln (double __a, long __b)
Definition at line 279 of file __clang_cuda_math.h.
References __a, __b, HUGE_VAL, INT_MAX, INT_MIN, and scalbn().
scalblnf()
__DEVICE__ float scalblnf (float __a, long __b)
Definition at line 286 of file __clang_cuda_math.h.
References __a, __b, HUGE_VALF, INT_MAX, INT_MIN, and scalbnf().
Referenced by __tg_scalbln().
scalbn()
__DEVICE__ double scalbn (double __a, int __b)
Definition at line 277 of file __clang_cuda_math.h.
Referenced by scalbln().
scalbnf()
__DEVICE__ float scalbnf (float __a, int __b)
Definition at line 278 of file __clang_cuda_math.h.
References __a, __b, and __nv_scalbnf().
Referenced by __tg_scalbn(), and scalblnf().
sin()
__DEVICE__ double sin (double __a)
Definition at line 293 of file __clang_cuda_math.h.
sincos()
__DEVICE_VOID__ void sincos (double __a, double * __s, double * __c)
Definition at line 294 of file __clang_cuda_math.h.
References __a, __c, and __nv_sincos().
sincosf()
__DEVICE_VOID__ void sincosf (float __a, float * __s, float * __c)
Definition at line 297 of file __clang_cuda_math.h.
References __a, __c, __FAST_OR_SLOW, __nv_fast_sincosf(), and __nv_sincosf().
sincospi()
__DEVICE_VOID__ void sincospi (double __a, double * __s, double * __c)
Definition at line 300 of file __clang_cuda_math.h.
References __a, __c, and __nv_sincospi().
sincospif()
__DEVICE_VOID__ void sincospif (float __a, float * __s, float * __c)
Definition at line 303 of file __clang_cuda_math.h.
References __a, __c, and __nv_sincospif().
sinf()
__DEVICE__ float sinf (float __a)
Definition at line 306 of file __clang_cuda_math.h.
References __a, __FAST_OR_SLOW, __nv_fast_sinf(), and __nv_sinf().
Referenced by __tg_sin(), and sin().
sinh()
__DEVICE__ double sinh (double __a)
Definition at line 309 of file __clang_cuda_math.h.
sinhf()
__DEVICE__ float sinhf (float __a)
Definition at line 310 of file __clang_cuda_math.h.
References __a, and __nv_sinhf().
Referenced by __tg_sinh(), and sinh().
sinpi()
__DEVICE__ double sinpi (double __a)
Definition at line 311 of file __clang_cuda_math.h.
References __a, and __nv_sinpi().
sinpif()
__DEVICE__ float sinpif (float __a)
Definition at line 312 of file __clang_cuda_math.h.
References __a, and __nv_sinpif().
sqrt()
__DEVICE__ double sqrt (double __a)
Definition at line 313 of file __clang_cuda_math.h.
sqrtf()
__DEVICE__ float sqrtf (float __a)
Definition at line 314 of file __clang_cuda_math.h.
References __a, and __nv_sqrtf().
Referenced by __tg_sqrt(), and sqrt().
tan()
__DEVICE__ double tan (double __a)
Definition at line 315 of file __clang_cuda_math.h.
tanf()
__DEVICE__ float tanf (float __a)
Definition at line 316 of file __clang_cuda_math.h.
References __a, and __nv_tanf().
Referenced by __tg_tan(), and tan().
tanh()
__DEVICE__ double tanh (double __a)
Definition at line 317 of file __clang_cuda_math.h.
tanhf()
__DEVICE__ float tanhf (float __a)
Definition at line 318 of file __clang_cuda_math.h.
References __a, and __nv_tanhf().
Referenced by __tg_tanh(), and tanh().
tgamma()
__DEVICE__ double tgamma (double __a)
Definition at line 319 of file __clang_cuda_math.h.
tgammaf()
__DEVICE__ float tgammaf (float __a)
Definition at line 320 of file __clang_cuda_math.h.
References __a, and __nv_tgammaf().
Referenced by __tg_tgamma().
trunc()
__DEVICE__ double trunc (double __a)
Definition at line 321 of file __clang_cuda_math.h.
truncf()
__DEVICE__ float truncf (float __a)
Definition at line 322 of file __clang_cuda_math.h.
References __a, and __nv_truncf().
Referenced by __tg_trunc().
ullmax()
__DEVICE__ unsigned long long ullmax (unsigned long long __a, unsigned long long __b)
Definition at line 323 of file __clang_cuda_math.h.
References __a, __b, and __nv_ullmax().
ullmin()
__DEVICE__ unsigned long long ullmin (unsigned long long __a, unsigned long long __b)
Definition at line 327 of file __clang_cuda_math.h.
References __a, __b, and __nv_ullmin().
umax()
__DEVICE__ unsigned int umax (unsigned int __a, unsigned int __b)
Definition at line 331 of file __clang_cuda_math.h.
References __a, __b, and __nv_umax().
umin()
__DEVICE__ unsigned int umin (unsigned int __a, unsigned int __b)
Definition at line 334 of file __clang_cuda_math.h.
References __a, __b, and __nv_umin().
y0()
__DEVICE__ double y0 (double __a)
Definition at line 337 of file __clang_cuda_math.h.
References __a, and __nv_y0().
y0f()
__DEVICE__ float y0f (float __a)
Definition at line 338 of file __clang_cuda_math.h.
References __a, and __nv_y0f().
y1()
__DEVICE__ double y1 (double __a)
Definition at line 339 of file __clang_cuda_math.h.
References __a, and __nv_y1().
y1f()
__DEVICE__ float y1f (float __a)
Definition at line 340 of file __clang_cuda_math.h.
References __a, and __nv_y1f().
yn()
__DEVICE__ double yn (int __a, double __b)
Definition at line 341 of file __clang_cuda_math.h.
References __a, __b, and __nv_yn().
ynf()
__DEVICE__ float ynf (int __a, float __b)
Definition at line 342 of file __clang_cuda_math.h.
References __a, __b, and __nv_ynf().