clang: lib/Headers/__clang_cuda_device_functions.h File Reference
__clang_cuda_device_functions.h File Reference
Macros
#define __DEVICE__ static __device__ __forceinline__
#define __prof_trigger(__a) __asm__ __volatile__("pmevent \t%0;" ::"i"(__a))
Functions
__DEVICE__ int __all (int __a)
__DEVICE__ int __any (int __a)
__DEVICE__ unsigned int __ballot (int __a)
__DEVICE__ unsigned int __brev (unsigned int __a)
__DEVICE__ unsigned long long __brevll (unsigned long long __a)
__DEVICE__ void __attribute__ ((overloadable)) __brkpt(void)
__DEVICE__ unsigned int __byte_perm (unsigned int __a, unsigned int __b, unsigned int __c)
__DEVICE__ int __clz (int __a)
__DEVICE__ int __clzll (long long __a)
__DEVICE__ float __cosf (float __a)
__DEVICE__ double __dAtomicAdd (double *__p, double __v)
__DEVICE__ double __dAtomicAdd_block (double *__p, double __v)
__DEVICE__ double __dAtomicAdd_system (double *__p, double __v)
__DEVICE__ double __dadd_rd (double __a, double __b)
__DEVICE__ double __dadd_rn (double __a, double __b)
__DEVICE__ double __dadd_ru (double __a, double __b)
__DEVICE__ double __dadd_rz (double __a, double __b)
__DEVICE__ double __ddiv_rd (double __a, double __b)
__DEVICE__ double __ddiv_rn (double __a, double __b)
__DEVICE__ double __ddiv_ru (double __a, double __b)
__DEVICE__ double __ddiv_rz (double __a, double __b)
__DEVICE__ double __dmul_rd (double __a, double __b)
__DEVICE__ double __dmul_rn (double __a, double __b)
__DEVICE__ double __dmul_ru (double __a, double __b)
__DEVICE__ double __dmul_rz (double __a, double __b)
__DEVICE__ float __double2float_rd (double __a)
__DEVICE__ float __double2float_rn (double __a)
__DEVICE__ float __double2float_ru (double __a)
__DEVICE__ float __double2float_rz (double __a)
__DEVICE__ int __double2hiint (double __a)
__DEVICE__ int __double2int_rd (double __a)
__DEVICE__ int __double2int_rn (double __a)
__DEVICE__ int __double2int_ru (double __a)
__DEVICE__ int __double2int_rz (double __a)
__DEVICE__ long long __double2ll_rd (double __a)
__DEVICE__ long long __double2ll_rn (double __a)
__DEVICE__ long long __double2ll_ru (double __a)
__DEVICE__ long long __double2ll_rz (double __a)
__DEVICE__ int __double2loint (double __a)
__DEVICE__ unsigned int __double2uint_rd (double __a)
__DEVICE__ unsigned int __double2uint_rn (double __a)
__DEVICE__ unsigned int __double2uint_ru (double __a)
__DEVICE__ unsigned int __double2uint_rz (double __a)
__DEVICE__ unsigned long long __double2ull_rd (double __a)
__DEVICE__ unsigned long long __double2ull_rn (double __a)
__DEVICE__ unsigned long long __double2ull_ru (double __a)
__DEVICE__ unsigned long long __double2ull_rz (double __a)
__DEVICE__ long long __double_as_longlong (double __a)
__DEVICE__ double __drcp_rd (double __a)
__DEVICE__ double __drcp_rn (double __a)
__DEVICE__ double __drcp_ru (double __a)
__DEVICE__ double __drcp_rz (double __a)
__DEVICE__ double __dsqrt_rd (double __a)
__DEVICE__ double __dsqrt_rn (double __a)
__DEVICE__ double __dsqrt_ru (double __a)
__DEVICE__ double __dsqrt_rz (double __a)
__DEVICE__ double __dsub_rd (double __a, double __b)
__DEVICE__ double __dsub_rn (double __a, double __b)
__DEVICE__ double __dsub_ru (double __a, double __b)
__DEVICE__ double __dsub_rz (double __a, double __b)
__DEVICE__ float __exp10f (float __a)
__DEVICE__ float __expf (float __a)
__DEVICE__ float __fAtomicAdd (float *__p, float __v)
__DEVICE__ float __fAtomicAdd_block (float *__p, float __v)
__DEVICE__ float __fAtomicAdd_system (float *__p, float __v)
__DEVICE__ float __fAtomicExch (float *__p, float __v)
__DEVICE__ float __fAtomicExch_block (float *__p, float __v)
__DEVICE__ float __fAtomicExch_system (float *__p, float __v)
__DEVICE__ float __fadd_rd (float __a, float __b)
__DEVICE__ float __fadd_rn (float __a, float __b)
__DEVICE__ float __fadd_ru (float __a, float __b)
__DEVICE__ float __fadd_rz (float __a, float __b)
__DEVICE__ float __fdiv_rd (float __a, float __b)
__DEVICE__ float __fdiv_rn (float __a, float __b)
__DEVICE__ float __fdiv_ru (float __a, float __b)
__DEVICE__ float __fdiv_rz (float __a, float __b)
__DEVICE__ float __fdividef (float __a, float __b)
__DEVICE__ int __ffs (int __a)
__DEVICE__ int __ffsll (long long __a)
__DEVICE__ int __finite (double __a)
__DEVICE__ int __finitef (float __a)
__DEVICE__ int __float2int_rd (float __a)
__DEVICE__ int __float2int_rn (float __a)
__DEVICE__ int __float2int_ru (float __a)
__DEVICE__ int __float2int_rz (float __a)
__DEVICE__ long long __float2ll_rd (float __a)
__DEVICE__ long long __float2ll_rn (float __a)
__DEVICE__ long long __float2ll_ru (float __a)
__DEVICE__ long long __float2ll_rz (float __a)
__DEVICE__ unsigned int __float2uint_rd (float __a)
__DEVICE__ unsigned int __float2uint_rn (float __a)
__DEVICE__ unsigned int __float2uint_ru (float __a)
__DEVICE__ unsigned int __float2uint_rz (float __a)
__DEVICE__ unsigned long long __float2ull_rd (float __a)
__DEVICE__ unsigned long long __float2ull_rn (float __a)
__DEVICE__ unsigned long long __float2ull_ru (float __a)
__DEVICE__ unsigned long long __float2ull_rz (float __a)
__DEVICE__ int __float_as_int (float __a)
__DEVICE__ unsigned int __float_as_uint (float __a)
__DEVICE__ double __fma_rd (double __a, double __b, double __c)
__DEVICE__ double __fma_rn (double __a, double __b, double __c)
__DEVICE__ double __fma_ru (double __a, double __b, double __c)
__DEVICE__ double __fma_rz (double __a, double __b, double __c)
__DEVICE__ float __fmaf_ieee_rd (float __a, float __b, float __c)
__DEVICE__ float __fmaf_ieee_rn (float __a, float __b, float __c)
__DEVICE__ float __fmaf_ieee_ru (float __a, float __b, float __c)
__DEVICE__ float __fmaf_ieee_rz (float __a, float __b, float __c)
__DEVICE__ float __fmaf_rd (float __a, float __b, float __c)
__DEVICE__ float __fmaf_rn (float __a, float __b, float __c)
__DEVICE__ float __fmaf_ru (float __a, float __b, float __c)
__DEVICE__ float __fmaf_rz (float __a, float __b, float __c)
__DEVICE__ float __fmul_rd (float __a, float __b)
__DEVICE__ float __fmul_rn (float __a, float __b)
__DEVICE__ float __fmul_ru (float __a, float __b)
__DEVICE__ float __fmul_rz (float __a, float __b)
__DEVICE__ float __frcp_rd (float __a)
__DEVICE__ float __frcp_rn (float __a)
__DEVICE__ float __frcp_ru (float __a)
__DEVICE__ float __frcp_rz (float __a)
__DEVICE__ float __frsqrt_rn (float __a)
__DEVICE__ float __fsqrt_rd (float __a)
__DEVICE__ float __fsqrt_rn (float __a)
__DEVICE__ float __fsqrt_ru (float __a)
__DEVICE__ float __fsqrt_rz (float __a)
__DEVICE__ float __fsub_rd (float __a, float __b)
__DEVICE__ float __fsub_rn (float __a, float __b)
__DEVICE__ float __fsub_ru (float __a, float __b)
__DEVICE__ float __fsub_rz (float __a, float __b)
__DEVICE__ int __hadd (int __a, int __b)
__DEVICE__ double __hiloint2double (int __a, int __b)
__DEVICE__ int __iAtomicAdd (int *__p, int __v)
__DEVICE__ int __iAtomicAdd_block (int *__p, int __v)
__DEVICE__ int __iAtomicAdd_system (int *__p, int __v)
__DEVICE__ int __iAtomicAnd (int *__p, int __v)
__DEVICE__ int __iAtomicAnd_block (int *__p, int __v)
__DEVICE__ int __iAtomicAnd_system (int *__p, int __v)
__DEVICE__ int __iAtomicCAS (int *__p, int __cmp, int __v)
__DEVICE__ int __iAtomicCAS_block (int *__p, int __cmp, int __v)
__DEVICE__ int __iAtomicCAS_system (int *__p, int __cmp, int __v)
__DEVICE__ int __iAtomicExch (int *__p, int __v)
__DEVICE__ int __iAtomicExch_block (int *__p, int __v)
__DEVICE__ int __iAtomicExch_system (int *__p, int __v)
__DEVICE__ int __iAtomicMax (int *__p, int __v)
__DEVICE__ int __iAtomicMax_block (int *__p, int __v)
__DEVICE__ int __iAtomicMax_system (int *__p, int __v)
__DEVICE__ int __iAtomicMin (int *__p, int __v)
__DEVICE__ int __iAtomicMin_block (int *__p, int __v)
__DEVICE__ int __iAtomicMin_system (int *__p, int __v)
__DEVICE__ int __iAtomicOr (int *__p, int __v)
__DEVICE__ int __iAtomicOr_block (int *__p, int __v)
__DEVICE__ int __iAtomicOr_system (int *__p, int __v)
__DEVICE__ int __iAtomicXor (int *__p, int __v)
__DEVICE__ int __iAtomicXor_block (int *__p, int __v)
__DEVICE__ int __iAtomicXor_system (int *__p, int __v)
__DEVICE__ long long __illAtomicMax (long long *__p, long long __v)
__DEVICE__ long long __illAtomicMax_block (long long *__p, long long __v)
__DEVICE__ long long __illAtomicMax_system (long long *__p, long long __v)
__DEVICE__ long long __illAtomicMin (long long *__p, long long __v)
__DEVICE__ long long __illAtomicMin_block (long long *__p, long long __v)
__DEVICE__ long long __illAtomicMin_system (long long *__p, long long __v)
__DEVICE__ double __int2double_rn (int __a)
__DEVICE__ float __int2float_rd (int __a)
__DEVICE__ float __int2float_rn (int __a)
__DEVICE__ float __int2float_ru (int __a)
__DEVICE__ float __int2float_rz (int __a)
__DEVICE__ float __int_as_float (int __a)
__DEVICE__ int __isfinited (double __a)
__DEVICE__ int __isinf (double __a)
__DEVICE__ int __isinff (float __a)
__DEVICE__ int __isnan (double __a)
__DEVICE__ int __isnanf (float __a)
__DEVICE__ double __ll2double_rd (long long __a)
__DEVICE__ double __ll2double_rn (long long __a)
__DEVICE__ double __ll2double_ru (long long __a)
__DEVICE__ double __ll2double_rz (long long __a)
__DEVICE__ float __ll2float_rd (long long __a)
__DEVICE__ float __ll2float_rn (long long __a)
__DEVICE__ float __ll2float_ru (long long __a)
__DEVICE__ float __ll2float_rz (long long __a)
__DEVICE__ long long __llAtomicAnd (long long *__p, long long __v)
__DEVICE__ long long __llAtomicAnd_block (long long *__p, long long __v)
__DEVICE__ long long __llAtomicAnd_system (long long *__p, long long __v)
__DEVICE__ long long __llAtomicOr (long long *__p, long long __v)
__DEVICE__ long long __llAtomicOr_block (long long *__p, long long __v)
__DEVICE__ long long __llAtomicOr_system (long long *__p, long long __v)
__DEVICE__ long long __llAtomicXor (long long *__p, long long __v)
__DEVICE__ long long __llAtomicXor_block (long long *__p, long long __v)
__DEVICE__ long long __llAtomicXor_system (long long *__p, long long __v)
__DEVICE__ float __log10f (float __a)
__DEVICE__ float __log2f (float __a)
__DEVICE__ float __logf (float __a)
__DEVICE__ double __longlong_as_double (long long __a)
__DEVICE__ int __mul24 (int __a, int __b)
__DEVICE__ long long __mul64hi (long long __a, long long __b)
__DEVICE__ int __mulhi (int __a, int __b)
__DEVICE__ unsigned int __pm0 (void)
__DEVICE__ unsigned int __pm1 (void)
__DEVICE__ unsigned int __pm2 (void)
__DEVICE__ unsigned int __pm3 (void)
__DEVICE__ int __popc (unsigned int __a)
__DEVICE__ int __popcll (unsigned long long __a)
__DEVICE__ float __powf (float __a, float __b)
__DEVICE__ int __rhadd (int __a, int __b)
__DEVICE__ unsigned int __sad (int __a, int __b, unsigned int __c)
__DEVICE__ float __saturatef (float __a)
__DEVICE__ int __signbitd (double __a)
__DEVICE__ int __signbitf (float __a)
__DEVICE__ void __sincosf (float __a, float *__s, float *__c)
__DEVICE__ float __sinf (float __a)
__DEVICE__ int __syncthreads_and (int __a)
__DEVICE__ int __syncthreads_count (int __a)
__DEVICE__ int __syncthreads_or (int __a)
__DEVICE__ float __tanf (float __a)
__DEVICE__ void __threadfence (void)
__DEVICE__ void __threadfence_block (void)
__DEVICE__ void __threadfence_system (void)
__DEVICE__ void __trap (void)
__DEVICE__ unsigned int __uAtomicAdd (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicAdd_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicAdd_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicAnd (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicAnd_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicAnd_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicCAS (unsigned int *__p, unsigned int __cmp, unsigned int __v)
__DEVICE__ unsigned int __uAtomicCAS_block (unsigned int *__p, unsigned int __cmp, unsigned int __v)
__DEVICE__ unsigned int __uAtomicCAS_system (unsigned int *__p, unsigned int __cmp, unsigned int __v)
__DEVICE__ unsigned int __uAtomicDec (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicDec_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicDec_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicExch (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicExch_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicExch_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicInc (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicInc_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicInc_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicMax (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicMax_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicMax_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicMin (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicMin_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicMin_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicOr (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicOr_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicOr_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicXor (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicXor_block (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uAtomicXor_system (unsigned int *__p, unsigned int __v)
__DEVICE__ unsigned int __uhadd (unsigned int __a, unsigned int __b)
__DEVICE__ double __uint2double_rn (unsigned int __a)
__DEVICE__ float __uint2float_rd (unsigned int __a)
__DEVICE__ float __uint2float_rn (unsigned int __a)
__DEVICE__ float __uint2float_ru (unsigned int __a)
__DEVICE__ float __uint2float_rz (unsigned int __a)
__DEVICE__ float __uint_as_float (unsigned int __a)
__DEVICE__ double __ull2double_rd (unsigned long long __a)
__DEVICE__ double __ull2double_rn (unsigned long long __a)
__DEVICE__ double __ull2double_ru (unsigned long long __a)
__DEVICE__ double __ull2double_rz (unsigned long long __a)
__DEVICE__ float __ull2float_rd (unsigned long long __a)
__DEVICE__ float __ull2float_rn (unsigned long long __a)
__DEVICE__ float __ull2float_ru (unsigned long long __a)
__DEVICE__ float __ull2float_rz (unsigned long long __a)
__DEVICE__ unsigned long long __ullAtomicAdd (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicAdd_block (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicAdd_system (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicAnd (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicAnd_block (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicAnd_system (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicCAS (unsigned long long *__p, unsigned long long __cmp, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicCAS_block (unsigned long long *__p, unsigned long long __cmp, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicCAS_system (unsigned long long *__p, unsigned long long __cmp, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicExch (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicExch_block (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicExch_system (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicMax (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicMax_block (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicMax_system (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicMin (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicMin_block (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicMin_system (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicOr (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicOr_block (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicOr_system (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicXor (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicXor_block (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned long long __ullAtomicXor_system (unsigned long long *__p, unsigned long long __v)
__DEVICE__ unsigned int __umul24 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned long long __umul64hi (unsigned long long __a, unsigned long long __b)
__DEVICE__ unsigned int __umulhi (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __urhadd (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __usad (unsigned int __a, unsigned int __b, unsigned int __c)
__DEVICE__ unsigned int __bool2mask (unsigned int __a, int shift)
__DEVICE__ unsigned int __vabs2 (unsigned int __a)
__DEVICE__ unsigned int __vabs4 (unsigned int __a)
__DEVICE__ unsigned int __vabsdiffs2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vabsdiffs4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vabsdiffu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vabsdiffu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vabsss2 (unsigned int __a)
__DEVICE__ unsigned int __vabsss4 (unsigned int __a)
__DEVICE__ unsigned int __vadd2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vadd4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vaddss2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vaddss4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vaddus2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vaddus4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vavgs2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vavgs4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vavgu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vavgu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vseteq2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpeq2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vseteq4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpeq4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetges2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpges2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetges4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpges4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetgeu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpgeu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetgeu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpgeu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetgts2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpgts2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetgts4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpgts4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetgtu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpgtu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetgtu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpgtu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetles2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmples2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetles4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmples4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetleu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpleu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetleu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpleu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetlts2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmplts2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetlts4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmplts4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetltu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpltu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetltu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpltu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetne2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpne2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsetne4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vcmpne4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vhaddu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vhaddu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vmaxs2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vmaxs4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vmaxu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vmaxu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vmins2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vmins4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vminu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vminu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsads2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsads4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsadu2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsadu4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsub2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vneg2 (unsigned int __a)
__DEVICE__ unsigned int __vsub4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vneg4 (unsigned int __a)
__DEVICE__ unsigned int __vsubss2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vnegss2 (unsigned int __a)
__DEVICE__ unsigned int __vsubss4 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vnegss4 (unsigned int __a)
__DEVICE__ unsigned int __vsubus2 (unsigned int __a, unsigned int __b)
__DEVICE__ unsigned int __vsubus4 (unsigned int __a, unsigned int __b)
__DEVICE__ int clock ()
__DEVICE__ long long clock64 ()
__DEVICE__ void * memcpy (void *__a, const void *__b, size_t __c)
__DEVICE__ void * memset (void *__a, int __b, size_t __c)
Macro Definition Documentation
__DEVICE__
#define __DEVICE__ static __device__ __forceinline__
Definition at line 26 of file __clang_cuda_device_functions.h.
__prof_trigger
#define __prof_trigger (__a) __asm__ __volatile__("pmevent \t%0;" ::"i"(__a))
Definition at line 512 of file __clang_cuda_device_functions.h.
Function Documentation
__all()
__DEVICE__ int __all (int __a)
Definition at line 29 of file __clang_cuda_device_functions.h.
References __a.
__any()
__DEVICE__ int __any (int __a)
Definition at line 30 of file __clang_cuda_device_functions.h.
References __a.
__attribute__()
__DEVICE__ void __attribute__ ((overloadable))
Definition at line 40 of file __clang_cuda_device_functions.h.
__ballot()
__DEVICE__ unsigned int __ballot (int __a)
Definition at line 31 of file __clang_cuda_device_functions.h.
References __a.
__bool2mask()
__DEVICE__ unsigned int __bool2mask (unsigned int __a, int shift)
Definition at line 1051 of file __clang_cuda_device_functions.h.
References __a.
Referenced by __vcmpeq2(), __vcmpeq4(), __vcmpges2(), __vcmpges4(), __vcmpgeu2(), __vcmpgeu4(), __vcmpgts2(), __vcmpgts4(), __vcmpgtu2(), __vcmpgtu4(), __vcmples2(), __vcmples4(), __vcmpleu2(), __vcmpleu4(), __vcmplts2(), __vcmplts4(), __vcmpltu2(), __vcmpltu4(), __vcmpne2(), and __vcmpne4().
__brev()
__DEVICE__ unsigned int __brev (unsigned int __a)
Definition at line 32 of file __clang_cuda_device_functions.h.
References __a, and __nv_brev().
__brevll()
__DEVICE__ unsigned long long __brevll (unsigned long long __a)
Definition at line 33 of file __clang_cuda_device_functions.h.
References __a, and __nv_brevll().
__byte_perm()
__DEVICE__ unsigned int __byte_perm (unsigned int __a, unsigned int __b, unsigned int __c)
Definition at line 45 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_byte_perm().
__clz()
__DEVICE__ int __clz (int __a)
Definition at line 49 of file __clang_cuda_device_functions.h.
References __a, and __nv_clz().
__clzll()
__DEVICE__ int __clzll (long long __a)
Definition at line 50 of file __clang_cuda_device_functions.h.
References __a, and __nv_clzll().
__cosf()
__DEVICE__ float __cosf (float __a)
Definition at line 51 of file __clang_cuda_device_functions.h.
References __a, and __nv_fast_cosf().
__dadd_rd()
__DEVICE__ double __dadd_rd (double __a, double __b)
Definition at line 61 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dadd_rd().
__dadd_rn()
__DEVICE__ double __dadd_rn (double __a, double __b)
Definition at line 64 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dadd_rn().
__dadd_ru()
__DEVICE__ double __dadd_ru (double __a, double __b)
Definition at line 67 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dadd_ru().
__dadd_rz()
__DEVICE__ double __dadd_rz (double __a, double __b)
Definition at line 70 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dadd_rz().
__dAtomicAdd()
__DEVICE__ double __dAtomicAdd (double * __p, double __v)
Definition at line 52 of file __clang_cuda_device_functions.h.
References __p, and __v.
__dAtomicAdd_block()
__DEVICE__ double __dAtomicAdd_block (double * __p, double __v)
Definition at line 55 of file __clang_cuda_device_functions.h.
References __p, and __v.
__dAtomicAdd_system()
__DEVICE__ double __dAtomicAdd_system (double * __p, double __v)
Definition at line 58 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ddiv_rd()
__DEVICE__ double __ddiv_rd (double __a, double __b)
Definition at line 73 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_ddiv_rd().
__ddiv_rn()
__DEVICE__ double __ddiv_rn (double __a, double __b)
Definition at line 76 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_ddiv_rn().
__ddiv_ru()
__DEVICE__ double __ddiv_ru (double __a, double __b)
Definition at line 79 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_ddiv_ru().
__ddiv_rz()
__DEVICE__ double __ddiv_rz (double __a, double __b)
Definition at line 82 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_ddiv_rz().
__dmul_rd()
__DEVICE__ double __dmul_rd (double __a, double __b)
Definition at line 85 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dmul_rd().
__dmul_rn()
__DEVICE__ double __dmul_rn (double __a, double __b)
Definition at line 88 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dmul_rn().
__dmul_ru()
__DEVICE__ double __dmul_ru (double __a, double __b)
Definition at line 91 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dmul_ru().
__dmul_rz()
__DEVICE__ double __dmul_rz (double __a, double __b)
Definition at line 94 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dmul_rz().
__double2float_rd()
__DEVICE__ float __double2float_rd (double __a)
Definition at line 97 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2float_rd().
__double2float_rn()
__DEVICE__ float __double2float_rn (double __a)
Definition at line 100 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2float_rn().
__double2float_ru()
__DEVICE__ float __double2float_ru (double __a)
Definition at line 103 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2float_ru().
__double2float_rz()
__DEVICE__ float __double2float_rz (double __a)
Definition at line 106 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2float_rz().
__double2hiint()
__DEVICE__ int __double2hiint (double __a)
Definition at line 109 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2hiint().
__double2int_rd()
__DEVICE__ int __double2int_rd (double __a)
Definition at line 110 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2int_rd().
__double2int_rn()
__DEVICE__ int __double2int_rn (double __a)
Definition at line 111 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2int_rn().
__double2int_ru()
__DEVICE__ int __double2int_ru (double __a)
Definition at line 112 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2int_ru().
__double2int_rz()
__DEVICE__ int __double2int_rz (double __a)
Definition at line 113 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2int_rz().
__double2ll_rd()
__DEVICE__ long long __double2ll_rd (double __a)
Definition at line 114 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2ll_rd().
__double2ll_rn()
__DEVICE__ long long __double2ll_rn (double __a)
Definition at line 117 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2ll_rn().
__double2ll_ru()
__DEVICE__ long long __double2ll_ru (double __a)
Definition at line 120 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2ll_ru().
__double2ll_rz()
__DEVICE__ long long __double2ll_rz (double __a)
Definition at line 123 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2ll_rz().
__double2loint()
__DEVICE__ int __double2loint (double __a)
Definition at line 126 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2loint().
__double2uint_rd()
__DEVICE__ unsigned int __double2uint_rd (double __a)
Definition at line 127 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2uint_rd().
__double2uint_rn()
__DEVICE__ unsigned int __double2uint_rn (double __a)
Definition at line 130 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2uint_rn().
__double2uint_ru()
__DEVICE__ unsigned int __double2uint_ru (double __a)
Definition at line 133 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2uint_ru().
__double2uint_rz()
__DEVICE__ unsigned int __double2uint_rz (double __a)
Definition at line 136 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2uint_rz().
__double2ull_rd()
__DEVICE__ unsigned long long __double2ull_rd (double __a)
Definition at line 139 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2ull_rd().
__double2ull_rn()
__DEVICE__ unsigned long long __double2ull_rn (double __a)
Definition at line 142 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2ull_rn().
__double2ull_ru()
__DEVICE__ unsigned long long __double2ull_ru (double __a)
Definition at line 145 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2ull_ru().
__double2ull_rz()
__DEVICE__ unsigned long long __double2ull_rz (double __a)
Definition at line 148 of file __clang_cuda_device_functions.h.
References __a, and __nv_double2ull_rz().
__double_as_longlong()
__DEVICE__ long long __double_as_longlong (double __a)
Definition at line 151 of file __clang_cuda_device_functions.h.
References __a, and __nv_double_as_longlong().
__drcp_rd()
__DEVICE__ double __drcp_rd (double __a)
Definition at line 154 of file __clang_cuda_device_functions.h.
References __a, and __nv_drcp_rd().
__drcp_rn()
__DEVICE__ double __drcp_rn (double __a)
Definition at line 155 of file __clang_cuda_device_functions.h.
References __a, and __nv_drcp_rn().
__drcp_ru()
__DEVICE__ double __drcp_ru (double __a)
Definition at line 156 of file __clang_cuda_device_functions.h.
References __a, and __nv_drcp_ru().
__drcp_rz()
__DEVICE__ double __drcp_rz (double __a)
Definition at line 157 of file __clang_cuda_device_functions.h.
References __a, and __nv_drcp_rz().
__dsqrt_rd()
__DEVICE__ double __dsqrt_rd (double __a)
Definition at line 158 of file __clang_cuda_device_functions.h.
References __a, and __nv_dsqrt_rd().
__dsqrt_rn()
__DEVICE__ double __dsqrt_rn (double __a)
Definition at line 159 of file __clang_cuda_device_functions.h.
References __a, and __nv_dsqrt_rn().
__dsqrt_ru()
__DEVICE__ double __dsqrt_ru (double __a)
Definition at line 160 of file __clang_cuda_device_functions.h.
References __a, and __nv_dsqrt_ru().
__dsqrt_rz()
__DEVICE__ double __dsqrt_rz (double __a)
Definition at line 161 of file __clang_cuda_device_functions.h.
References __a, and __nv_dsqrt_rz().
__dsub_rd()
__DEVICE__ double __dsub_rd (double __a, double __b)
Definition at line 162 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dsub_rd().
__dsub_rn()
__DEVICE__ double __dsub_rn (double __a, double __b)
Definition at line 165 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dsub_rn().
__dsub_ru()
__DEVICE__ double __dsub_ru (double __a, double __b)
Definition at line 168 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dsub_ru().
__dsub_rz()
__DEVICE__ double __dsub_rz (double __a, double __b)
Definition at line 171 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_dsub_rz().
__exp10f()
__DEVICE__ float __exp10f (float __a)
Definition at line 174 of file __clang_cuda_device_functions.h.
References __a, and __nv_fast_exp10f().
__expf()
__DEVICE__ float __expf (float __a)
Definition at line 175 of file __clang_cuda_device_functions.h.
References __a, and __nv_fast_expf().
__fadd_rd()
__DEVICE__ float __fadd_rd (float __a, float __b)
Definition at line 197 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fadd_rd().
__fadd_rn()
__DEVICE__ float __fadd_rn (float __a, float __b)
Definition at line 200 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fadd_rn().
__fadd_ru()
__DEVICE__ float __fadd_ru (float __a, float __b)
Definition at line 203 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fadd_ru().
__fadd_rz()
__DEVICE__ float __fadd_rz (float __a, float __b)
Definition at line 206 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fadd_rz().
__fAtomicAdd()
__DEVICE__ float __fAtomicAdd (float * __p, float __v)
Definition at line 176 of file __clang_cuda_device_functions.h.
References __p, and __v.
__fAtomicAdd_block()
__DEVICE__ float __fAtomicAdd_block (float * __p, float __v)
Definition at line 179 of file __clang_cuda_device_functions.h.
References __p, and __v.
__fAtomicAdd_system()
__DEVICE__ float __fAtomicAdd_system (float * __p, float __v)
Definition at line 182 of file __clang_cuda_device_functions.h.
References __p, and __v.
__fAtomicExch()
__DEVICE__ float __fAtomicExch (float * __p, float __v)
Definition at line 185 of file __clang_cuda_device_functions.h.
References __nv_float_as_int(), __nv_int_as_float(), __p, and __v.
__fAtomicExch_block()
__DEVICE__ float __fAtomicExch_block (float * __p, float __v)
Definition at line 189 of file __clang_cuda_device_functions.h.
References __nv_float_as_int(), __nv_int_as_float(), __p, and __v.
__fAtomicExch_system()
__DEVICE__ float __fAtomicExch_system (float * __p, float __v)
Definition at line 193 of file __clang_cuda_device_functions.h.
References __nv_float_as_int(), __nv_int_as_float(), __p, and __v.
__fdiv_rd()
__DEVICE__ float __fdiv_rd (float __a, float __b)
Definition at line 209 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fdiv_rd().
__fdiv_rn()
__DEVICE__ float __fdiv_rn (float __a, float __b)
Definition at line 212 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fdiv_rn().
__fdiv_ru()
__DEVICE__ float __fdiv_ru (float __a, float __b)
Definition at line 215 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fdiv_ru().
__fdiv_rz()
__DEVICE__ float __fdiv_rz (float __a, float __b)
Definition at line 218 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fdiv_rz().
__fdividef()
__DEVICE__ float __fdividef (float __a, float __b)
Definition at line 221 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fast_fdividef().
__ffs()
__DEVICE__ int __ffs (int __a)
Definition at line 224 of file __clang_cuda_device_functions.h.
References __a, and __nv_ffs().
__ffsll()
__DEVICE__ int __ffsll (long long __a)
Definition at line 225 of file __clang_cuda_device_functions.h.
References __a, and __nv_ffsll().
__finite()
__DEVICE__ int __finite (double __a)
Definition at line 226 of file __clang_cuda_device_functions.h.
References __a, and __nv_isfinited().
__finitef()
__DEVICE__ int __finitef (float __a)
Definition at line 227 of file __clang_cuda_device_functions.h.
References __a, and __nv_finitef().
Referenced by isfinite().
__float2int_rd()
__DEVICE__ int __float2int_rd (float __a)
Definition at line 231 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2int_rd().
__float2int_rn()
__DEVICE__ int __float2int_rn (float __a)
Definition at line 232 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2int_rn().
Referenced by lrintf().
__float2int_ru()
__DEVICE__ int __float2int_ru (float __a)
Definition at line 233 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2int_ru().
__float2int_rz()
__DEVICE__ int __float2int_rz (float __a)
Definition at line 234 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2int_rz().
__float2ll_rd()
__DEVICE__ long long __float2ll_rd (float __a)
Definition at line 235 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2ll_rd().
__float2ll_rn()
__DEVICE__ long long __float2ll_rn (float __a)
Definition at line 236 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2ll_rn().
__float2ll_ru()
__DEVICE__ long long __float2ll_ru (float __a)
Definition at line 237 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2ll_ru().
__float2ll_rz()
__DEVICE__ long long __float2ll_rz (float __a)
Definition at line 238 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2ll_rz().
__float2uint_rd()
__DEVICE__ unsigned int __float2uint_rd (float __a)
Definition at line 239 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2uint_rd().
__float2uint_rn()
__DEVICE__ unsigned int __float2uint_rn (float __a)
Definition at line 242 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2uint_rn().
__float2uint_ru()
__DEVICE__ unsigned int __float2uint_ru (float __a)
Definition at line 245 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2uint_ru().
__float2uint_rz()
__DEVICE__ unsigned int __float2uint_rz (float __a)
Definition at line 248 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2uint_rz().
__float2ull_rd()
__DEVICE__ unsigned long long __float2ull_rd (float __a)
Definition at line 251 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2ull_rd().
__float2ull_rn()
__DEVICE__ unsigned long long __float2ull_rn (float __a)
Definition at line 254 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2ull_rn().
__float2ull_ru()
__DEVICE__ unsigned long long __float2ull_ru (float __a)
Definition at line 257 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2ull_ru().
__float2ull_rz()
__DEVICE__ unsigned long long __float2ull_rz (float __a)
Definition at line 260 of file __clang_cuda_device_functions.h.
References __a, and __nv_float2ull_rz().
__float_as_int()
__DEVICE__ int __float_as_int (float __a)
Definition at line 263 of file __clang_cuda_device_functions.h.
References __a, and __nv_float_as_int().
__float_as_uint()
__DEVICE__ unsigned int __float_as_uint (float __a)
Definition at line 264 of file __clang_cuda_device_functions.h.
References __a, and __nv_float_as_uint().
__fma_rd()
__DEVICE__ double __fma_rd (double __a, double __b, double __c)
Definition at line 267 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fma_rd().
__fma_rn()
__DEVICE__ double __fma_rn (double __a, double __b, double __c)
Definition at line 270 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fma_rn().
__fma_ru()
__DEVICE__ double __fma_ru (double __a, double __b, double __c)
Definition at line 273 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fma_ru().
__fma_rz()
__DEVICE__ double __fma_rz (double __a, double __b, double __c)
Definition at line 276 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fma_rz().
__fmaf_ieee_rd()
__DEVICE__ float __fmaf_ieee_rd (float __a, float __b, float __c)
Definition at line 279 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fmaf_ieee_rd().
__fmaf_ieee_rn()
__DEVICE__ float __fmaf_ieee_rn (float __a, float __b, float __c)
Definition at line 282 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fmaf_ieee_rn().
__fmaf_ieee_ru()
__DEVICE__ float __fmaf_ieee_ru (float __a, float __b, float __c)
Definition at line 285 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fmaf_ieee_ru().
__fmaf_ieee_rz()
__DEVICE__ float __fmaf_ieee_rz (float __a, float __b, float __c)
Definition at line 288 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fmaf_ieee_rz().
__fmaf_rd()
__DEVICE__ float __fmaf_rd (float __a, float __b, float __c)
Definition at line 291 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fmaf_rd().
__fmaf_rn()
__DEVICE__ float __fmaf_rn (float __a, float __b, float __c)
Definition at line 294 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fmaf_rn().
__fmaf_ru()
__DEVICE__ float __fmaf_ru (float __a, float __b, float __c)
Definition at line 297 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fmaf_ru().
__fmaf_rz()
__DEVICE__ float __fmaf_rz (float __a, float __b, float __c)
Definition at line 300 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_fmaf_rz().
__fmul_rd()
__DEVICE__ float __fmul_rd (float __a, float __b)
Definition at line 303 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fmul_rd().
__fmul_rn()
__DEVICE__ float __fmul_rn (float __a, float __b)
Definition at line 306 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fmul_rn().
__fmul_ru()
__DEVICE__ float __fmul_ru (float __a, float __b)
Definition at line 309 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fmul_ru().
__fmul_rz()
__DEVICE__ float __fmul_rz (float __a, float __b)
Definition at line 312 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fmul_rz().
__frcp_rd()
__DEVICE__ float __frcp_rd (float __a)
Definition at line 315 of file __clang_cuda_device_functions.h.
References __a, and __nv_frcp_rd().
__frcp_rn()
__DEVICE__ float __frcp_rn (float __a)
Definition at line 316 of file __clang_cuda_device_functions.h.
References __a, and __nv_frcp_rn().
__frcp_ru()
__DEVICE__ float __frcp_ru (float __a)
Definition at line 317 of file __clang_cuda_device_functions.h.
References __a, and __nv_frcp_ru().
__frcp_rz()
__DEVICE__ float __frcp_rz (float __a)
Definition at line 318 of file __clang_cuda_device_functions.h.
References __a, and __nv_frcp_rz().
__frsqrt_rn()
__DEVICE__ float __frsqrt_rn (float __a)
Definition at line 319 of file __clang_cuda_device_functions.h.
References __a, and __nv_frsqrt_rn().
__fsqrt_rd()
__DEVICE__ float __fsqrt_rd (float __a)
Definition at line 320 of file __clang_cuda_device_functions.h.
References __a, and __nv_fsqrt_rd().
__fsqrt_rn()
__DEVICE__ float __fsqrt_rn (float __a)
Definition at line 321 of file __clang_cuda_device_functions.h.
References __a, and __nv_fsqrt_rn().
__fsqrt_ru()
__DEVICE__ float __fsqrt_ru (float __a)
Definition at line 322 of file __clang_cuda_device_functions.h.
References __a, and __nv_fsqrt_ru().
__fsqrt_rz()
__DEVICE__ float __fsqrt_rz (float __a)
Definition at line 323 of file __clang_cuda_device_functions.h.
References __a, and __nv_fsqrt_rz().
__fsub_rd()
__DEVICE__ float __fsub_rd (float __a, float __b)
Definition at line 324 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fsub_rd().
__fsub_rn()
__DEVICE__ float __fsub_rn (float __a, float __b)
Definition at line 327 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fsub_rn().
__fsub_ru()
__DEVICE__ float __fsub_ru (float __a, float __b)
Definition at line 330 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fsub_ru().
__fsub_rz()
__DEVICE__ float __fsub_rz (float __a, float __b)
Definition at line 333 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fsub_rz().
__hadd()
__DEVICE__ int __hadd (int __a, int __b)
Definition at line 336 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_hadd().
__hiloint2double()
__DEVICE__ double __hiloint2double (int __a, int __b)
Definition at line 337 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_hiloint2double().
__iAtomicAdd()
__DEVICE__ int __iAtomicAdd (int * __p, int __v)
Definition at line 340 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicAdd_block()
__DEVICE__ int __iAtomicAdd_block (int * __p, int __v)
Definition at line 343 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicAdd_system()
__DEVICE__ int __iAtomicAdd_system (int * __p, int __v)
Definition at line 346 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicAnd()
__DEVICE__ int __iAtomicAnd (int * __p, int __v)
Definition at line 349 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicAnd_block()
__DEVICE__ int __iAtomicAnd_block (int * __p, int __v)
Definition at line 352 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicAnd_system()
__DEVICE__ int __iAtomicAnd_system (int * __p, int __v)
Definition at line 355 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicCAS()
__DEVICE__ int __iAtomicCAS (int * __p, int __cmp, int __v)
Definition at line 358 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicCAS_block()
__DEVICE__ int __iAtomicCAS_block (int * __p, int __cmp, int __v)
Definition at line 361 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicCAS_system()
__DEVICE__ int __iAtomicCAS_system (int * __p, int __cmp, int __v)
Definition at line 364 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicExch()
__DEVICE__ int __iAtomicExch (int * __p, int __v)
Definition at line 367 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicExch_block()
__DEVICE__ int __iAtomicExch_block (int * __p, int __v)
Definition at line 370 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicExch_system()
__DEVICE__ int __iAtomicExch_system (int * __p, int __v)
Definition at line 373 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicMax()
__DEVICE__ int __iAtomicMax (int * __p, int __v)
Definition at line 376 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicMax_block()
__DEVICE__ int __iAtomicMax_block (int * __p, int __v)
Definition at line 379 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicMax_system()
__DEVICE__ int __iAtomicMax_system (int * __p, int __v)
Definition at line 382 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicMin()
__DEVICE__ int __iAtomicMin (int * __p, int __v)
Definition at line 385 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicMin_block()
__DEVICE__ int __iAtomicMin_block (int * __p, int __v)
Definition at line 388 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicMin_system()
__DEVICE__ int __iAtomicMin_system (int * __p, int __v)
Definition at line 391 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicOr()
__DEVICE__ int __iAtomicOr (int * __p, int __v)
Definition at line 394 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicOr_block()
__DEVICE__ int __iAtomicOr_block (int * __p, int __v)
Definition at line 397 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicOr_system()
__DEVICE__ int __iAtomicOr_system (int * __p, int __v)
Definition at line 400 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicXor()
__DEVICE__ int __iAtomicXor (int * __p, int __v)
Definition at line 403 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicXor_block()
__DEVICE__ int __iAtomicXor_block (int * __p, int __v)
Definition at line 406 of file __clang_cuda_device_functions.h.
References __p, and __v.
__iAtomicXor_system()
__DEVICE__ int __iAtomicXor_system (int * __p, int __v)
Definition at line 409 of file __clang_cuda_device_functions.h.
References __p, and __v.
__illAtomicMax()
__DEVICE__ long long __illAtomicMax (long long * __p, long long __v)
Definition at line 412 of file __clang_cuda_device_functions.h.
References __p, and __v.
__illAtomicMax_block()
__DEVICE__ long long __illAtomicMax_block (long long * __p, long long __v)
Definition at line 415 of file __clang_cuda_device_functions.h.
References __p, and __v.
__illAtomicMax_system()
__DEVICE__ long long __illAtomicMax_system (long long * __p, long long __v)
Definition at line 418 of file __clang_cuda_device_functions.h.
References __p, and __v.
__illAtomicMin()
__DEVICE__ long long __illAtomicMin (long long * __p, long long __v)
Definition at line 421 of file __clang_cuda_device_functions.h.
References __p, and __v.
__illAtomicMin_block()
__DEVICE__ long long __illAtomicMin_block (long long * __p, long long __v)
Definition at line 424 of file __clang_cuda_device_functions.h.
References __p, and __v.
__illAtomicMin_system()
__DEVICE__ long long __illAtomicMin_system (long long * __p, long long __v)
Definition at line 427 of file __clang_cuda_device_functions.h.
References __p, and __v.
__int2double_rn()
__DEVICE__ double __int2double_rn (int __a)
Definition at line 430 of file __clang_cuda_device_functions.h.
References __a, and __nv_int2double_rn().
__int2float_rd()
__DEVICE__ float __int2float_rd (int __a)
Definition at line 431 of file __clang_cuda_device_functions.h.
References __a, and __nv_int2float_rd().
__int2float_rn()
__DEVICE__ float __int2float_rn (int __a)
Definition at line 432 of file __clang_cuda_device_functions.h.
References __a, and __nv_int2float_rn().
__int2float_ru()
__DEVICE__ float __int2float_ru (int __a)
Definition at line 433 of file __clang_cuda_device_functions.h.
References __a, and __nv_int2float_ru().
__int2float_rz()
__DEVICE__ float __int2float_rz (int __a)
Definition at line 434 of file __clang_cuda_device_functions.h.
References __a, and __nv_int2float_rz().
__int_as_float()
__DEVICE__ float __int_as_float (int __a)
Definition at line 435 of file __clang_cuda_device_functions.h.
References __a, and __nv_int_as_float().
__isfinited()
__DEVICE__ int __isfinited (double __a)
Definition at line 436 of file __clang_cuda_device_functions.h.
References __a, and __nv_isfinited().
Referenced by isfinite().
__isinf()
__DEVICE__ int __isinf (double __a)
Definition at line 437 of file __clang_cuda_device_functions.h.
References __a, and __nv_isinfd().
Referenced by isinf().
__isinff()
__DEVICE__ int __isinff (float __a)
Definition at line 438 of file __clang_cuda_device_functions.h.
References __a, and __nv_isinff().
Referenced by isinf().
__isnan()
__DEVICE__ int __isnan (double __a)
Definition at line 442 of file __clang_cuda_device_functions.h.
References __a, and __nv_isnand().
Referenced by isnan().
__isnanf()
__DEVICE__ int __isnanf (float __a)
Definition at line 443 of file __clang_cuda_device_functions.h.
References __a, and __nv_isnanf().
Referenced by isnan().
__ll2double_rd()
__DEVICE__ double __ll2double_rd (long long __a)
Definition at line 447 of file __clang_cuda_device_functions.h.
References __a, and __nv_ll2double_rd().
__ll2double_rn()
__DEVICE__ double __ll2double_rn (long long __a)
Definition at line 450 of file __clang_cuda_device_functions.h.
References __a, and __nv_ll2double_rn().
__ll2double_ru()
__DEVICE__ double __ll2double_ru (long long __a)
Definition at line 453 of file __clang_cuda_device_functions.h.
References __a, and __nv_ll2double_ru().
__ll2double_rz()
__DEVICE__ double __ll2double_rz (long long __a)
Definition at line 456 of file __clang_cuda_device_functions.h.
References __a, and __nv_ll2double_rz().
__ll2float_rd()
__DEVICE__ float __ll2float_rd (long long __a)
Definition at line 459 of file __clang_cuda_device_functions.h.
References __a, and __nv_ll2float_rd().
__ll2float_rn()
__DEVICE__ float __ll2float_rn (long long __a)
Definition at line 460 of file __clang_cuda_device_functions.h.
References __a, and __nv_ll2float_rn().
__ll2float_ru()
__DEVICE__ float __ll2float_ru (long long __a)
Definition at line 461 of file __clang_cuda_device_functions.h.
References __a, and __nv_ll2float_ru().
__ll2float_rz()
__DEVICE__ float __ll2float_rz (long long __a)
Definition at line 462 of file __clang_cuda_device_functions.h.
References __a, and __nv_ll2float_rz().
__llAtomicAnd()
__DEVICE__ long long __llAtomicAnd (long long * __p, long long __v)
Definition at line 463 of file __clang_cuda_device_functions.h.
References __p, and __v.
__llAtomicAnd_block()
__DEVICE__ long long __llAtomicAnd_block (long long * __p, long long __v)
Definition at line 466 of file __clang_cuda_device_functions.h.
References __p, and __v.
__llAtomicAnd_system()
__DEVICE__ long long __llAtomicAnd_system (long long * __p, long long __v)
Definition at line 469 of file __clang_cuda_device_functions.h.
References __p, and __v.
__llAtomicOr()
__DEVICE__ long long __llAtomicOr (long long * __p, long long __v)
Definition at line 472 of file __clang_cuda_device_functions.h.
References __p, and __v.
__llAtomicOr_block()
__DEVICE__ long long __llAtomicOr_block (long long * __p, long long __v)
Definition at line 475 of file __clang_cuda_device_functions.h.
References __p, and __v.
__llAtomicOr_system()
__DEVICE__ long long __llAtomicOr_system (long long * __p, long long __v)
Definition at line 478 of file __clang_cuda_device_functions.h.
References __p, and __v.
__llAtomicXor()
__DEVICE__ long long __llAtomicXor (long long * __p, long long __v)
Definition at line 481 of file __clang_cuda_device_functions.h.
References __p, and __v.
__llAtomicXor_block()
__DEVICE__ long long __llAtomicXor_block (long long * __p, long long __v)
Definition at line 484 of file __clang_cuda_device_functions.h.
References __p, and __v.
__llAtomicXor_system()
__DEVICE__ long long __llAtomicXor_system (long long * __p, long long __v)
Definition at line 487 of file __clang_cuda_device_functions.h.
References __p, and __v.
__log10f()
__DEVICE__ float __log10f (float __a)
Definition at line 490 of file __clang_cuda_device_functions.h.
References __a, and __nv_fast_log10f().
__log2f()
__DEVICE__ float __log2f (float __a)
Definition at line 491 of file __clang_cuda_device_functions.h.
References __a, and __nv_fast_log2f().
__logf()
__DEVICE__ float __logf (float __a)
Definition at line 492 of file __clang_cuda_device_functions.h.
References __a, and __nv_fast_logf().
__longlong_as_double()
__DEVICE__ double __longlong_as_double (long long __a)
Definition at line 493 of file __clang_cuda_device_functions.h.
References __a, and __nv_longlong_as_double().
__mul24()
__DEVICE__ int __mul24 (int __a, int __b)
Definition at line 496 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_mul24().
__mul64hi()
__DEVICE__ long long __mul64hi (long long __a, long long __b)
Definition at line 497 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_mul64hi().
__mulhi()
__DEVICE__ int __mulhi (int __a, int __b)
Definition at line 500 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_mulhi().
__pm0()
__DEVICE__ unsigned int __pm0 (void)
Definition at line 501 of file __clang_cuda_device_functions.h.
__pm1()
__DEVICE__ unsigned int __pm1 (void)
Definition at line 502 of file __clang_cuda_device_functions.h.
__pm2()
__DEVICE__ unsigned int __pm2 (void)
Definition at line 503 of file __clang_cuda_device_functions.h.
__pm3()
__DEVICE__ unsigned int __pm3 (void)
Definition at line 504 of file __clang_cuda_device_functions.h.
__popc()
__DEVICE__ int __popc (unsigned int __a)
Definition at line 505 of file __clang_cuda_device_functions.h.
References __a, and __nv_popc().
__popcll()
__DEVICE__ int __popcll (unsigned long long __a)
Definition at line 506 of file __clang_cuda_device_functions.h.
References __a, and __nv_popcll().
__powf()
__DEVICE__ float __powf (float __a, float __b)
Definition at line 507 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_fast_powf().
__rhadd()
__DEVICE__ int __rhadd (int __a, int __b)
Definition at line 513 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_rhadd().
__sad()
__DEVICE__ unsigned int __sad (int __a, int __b, unsigned int __c)
Definition at line 514 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_sad().
__saturatef()
__DEVICE__ float __saturatef (float __a)
Definition at line 517 of file __clang_cuda_device_functions.h.
References __a, and __nv_saturatef().
__signbitd()
__DEVICE__ int __signbitd (double __a)
Definition at line 518 of file __clang_cuda_device_functions.h.
References __a, and __nv_signbitd().
Referenced by signbit().
__signbitf()
__DEVICE__ int __signbitf (float __a)
Definition at line 519 of file __clang_cuda_device_functions.h.
References __a, and __nv_signbitf().
Referenced by signbit().
__sincosf()
__DEVICE__ void __sincosf (float __a, float * __s, float * __c)
Definition at line 520 of file __clang_cuda_device_functions.h.
References __a, __c, and __nv_fast_sincosf().
__sinf()
__DEVICE__ float __sinf (float __a)
Definition at line 523 of file __clang_cuda_device_functions.h.
References __a, and __nv_fast_sinf().
__syncthreads_and()
__DEVICE__ int __syncthreads_and (int __a)
Definition at line 524 of file __clang_cuda_device_functions.h.
References __a.
__syncthreads_count()
__DEVICE__ int __syncthreads_count (int __a)
Definition at line 525 of file __clang_cuda_device_functions.h.
References __a.
__syncthreads_or()
__DEVICE__ int __syncthreads_or (int __a)
Definition at line 526 of file __clang_cuda_device_functions.h.
References __a.
__tanf()
__DEVICE__ float __tanf (float __a)
Definition at line 527 of file __clang_cuda_device_functions.h.
References __a, and __nv_fast_tanf().
__threadfence()
__DEVICE__ void __threadfence (void)
Definition at line 528 of file __clang_cuda_device_functions.h.
__threadfence_block()
__DEVICE__ void __threadfence_block (void)
Definition at line 529 of file __clang_cuda_device_functions.h.
__threadfence_system()
__DEVICE__ void __threadfence_system (void)
Definition at line 530 of file __clang_cuda_device_functions.h.
__trap()
__DEVICE__ void __trap (void)
Definition at line 531 of file __clang_cuda_device_functions.h.
__uAtomicAdd()
__DEVICE__ unsigned int __uAtomicAdd (unsigned int * __p, unsigned int __v)
Definition at line 532 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicAdd_block()
__DEVICE__ unsigned int __uAtomicAdd_block (unsigned int * __p, unsigned int __v)
Definition at line 535 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicAdd_system()
__DEVICE__ unsigned int __uAtomicAdd_system (unsigned int * __p, unsigned int __v)
Definition at line 539 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicAnd()
__DEVICE__ unsigned int __uAtomicAnd (unsigned int * __p, unsigned int __v)
Definition at line 543 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicAnd_block()
__DEVICE__ unsigned int __uAtomicAnd_block (unsigned int * __p, unsigned int __v)
Definition at line 546 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicAnd_system()
__DEVICE__ unsigned int __uAtomicAnd_system (unsigned int * __p, unsigned int __v)
Definition at line 550 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicCAS()
__DEVICE__ unsigned int __uAtomicCAS (unsigned int * __p, unsigned int __cmp, unsigned int __v)
Definition at line 554 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicCAS_block()
__DEVICE__ unsigned int __uAtomicCAS_block (unsigned int * __p, unsigned int __cmp, unsigned int __v)
Definition at line 559 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicCAS_system()
__DEVICE__ unsigned int __uAtomicCAS_system (unsigned int * __p, unsigned int __cmp, unsigned int __v)
Definition at line 563 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicDec()
__DEVICE__ unsigned int __uAtomicDec (unsigned int * __p, unsigned int __v)
Definition at line 566 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicDec_block()
__DEVICE__ unsigned int __uAtomicDec_block (unsigned int * __p, unsigned int __v)
Definition at line 569 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicDec_system()
__DEVICE__ unsigned int __uAtomicDec_system (unsigned int * __p, unsigned int __v)
Definition at line 573 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicExch()
__DEVICE__ unsigned int __uAtomicExch (unsigned int * __p, unsigned int __v)
Definition at line 577 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicExch_block()
__DEVICE__ unsigned int __uAtomicExch_block (unsigned int * __p, unsigned int __v)
Definition at line 580 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicExch_system()
__DEVICE__ unsigned int __uAtomicExch_system (unsigned int * __p, unsigned int __v)
Definition at line 584 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicInc()
__DEVICE__ unsigned int __uAtomicInc (unsigned int * __p, unsigned int __v)
Definition at line 588 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicInc_block()
__DEVICE__ unsigned int __uAtomicInc_block (unsigned int * __p, unsigned int __v)
Definition at line 591 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicInc_system()
__DEVICE__ unsigned int __uAtomicInc_system (unsigned int * __p, unsigned int __v)
Definition at line 595 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicMax()
__DEVICE__ unsigned int __uAtomicMax (unsigned int * __p, unsigned int __v)
Definition at line 599 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicMax_block()
__DEVICE__ unsigned int __uAtomicMax_block (unsigned int * __p, unsigned int __v)
Definition at line 602 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicMax_system()
__DEVICE__ unsigned int __uAtomicMax_system (unsigned int * __p, unsigned int __v)
Definition at line 606 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicMin()
__DEVICE__ unsigned int __uAtomicMin (unsigned int * __p, unsigned int __v)
Definition at line 610 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicMin_block()
__DEVICE__ unsigned int __uAtomicMin_block (unsigned int * __p, unsigned int __v)
Definition at line 613 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicMin_system()
__DEVICE__ unsigned int __uAtomicMin_system (unsigned int * __p, unsigned int __v)
Definition at line 617 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicOr()
__DEVICE__ unsigned int __uAtomicOr (unsigned int * __p, unsigned int __v)
Definition at line 621 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicOr_block()
__DEVICE__ unsigned int __uAtomicOr_block (unsigned int * __p, unsigned int __v)
Definition at line 624 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicOr_system()
__DEVICE__ unsigned int __uAtomicOr_system (unsigned int * __p, unsigned int __v)
Definition at line 627 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicXor()
__DEVICE__ unsigned int __uAtomicXor (unsigned int * __p, unsigned int __v)
Definition at line 631 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicXor_block()
__DEVICE__ unsigned int __uAtomicXor_block (unsigned int * __p, unsigned int __v)
Definition at line 634 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uAtomicXor_system()
__DEVICE__ unsigned int __uAtomicXor_system (unsigned int * __p, unsigned int __v)
Definition at line 638 of file __clang_cuda_device_functions.h.
References __p, and __v.
__uhadd()
__DEVICE__ unsigned int __uhadd (unsigned int __a, unsigned int __b)
Definition at line 642 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_uhadd().
__uint2double_rn()
__DEVICE__ double __uint2double_rn (unsigned int __a)
Definition at line 645 of file __clang_cuda_device_functions.h.
References __a, and __nv_uint2double_rn().
__uint2float_rd()
__DEVICE__ float __uint2float_rd (unsigned int __a)
Definition at line 648 of file __clang_cuda_device_functions.h.
References __a, and __nv_uint2float_rd().
__uint2float_rn()
__DEVICE__ float __uint2float_rn (unsigned int __a)
Definition at line 651 of file __clang_cuda_device_functions.h.
References __a, and __nv_uint2float_rn().
__uint2float_ru()
__DEVICE__ float __uint2float_ru (unsigned int __a)
Definition at line 654 of file __clang_cuda_device_functions.h.
References __a, and __nv_uint2float_ru().
__uint2float_rz()
__DEVICE__ float __uint2float_rz (unsigned int __a)
Definition at line 657 of file __clang_cuda_device_functions.h.
References __a, and __nv_uint2float_rz().
__uint_as_float()
__DEVICE__ float __uint_as_float (unsigned int __a)
Definition at line 660 of file __clang_cuda_device_functions.h.
References __a, and __nv_uint_as_float().
__ull2double_rd()
__DEVICE__ double __ull2double_rd (unsigned long long __a)
Definition at line 663 of file __clang_cuda_device_functions.h.
References __a, and __nv_ull2double_rd().
__ull2double_rn()
__DEVICE__ double __ull2double_rn (unsigned long long __a)
Definition at line 666 of file __clang_cuda_device_functions.h.
References __a, and __nv_ull2double_rn().
__ull2double_ru()
__DEVICE__ double __ull2double_ru (unsigned long long __a)
Definition at line 669 of file __clang_cuda_device_functions.h.
References __a, and __nv_ull2double_ru().
__ull2double_rz()
__DEVICE__ double __ull2double_rz (unsigned long long __a)
Definition at line 672 of file __clang_cuda_device_functions.h.
References __a, and __nv_ull2double_rz().
__ull2float_rd()
__DEVICE__ float __ull2float_rd (unsigned long long __a)
Definition at line 675 of file __clang_cuda_device_functions.h.
References __a, and __nv_ull2float_rd().
__ull2float_rn()
__DEVICE__ float __ull2float_rn (unsigned long long __a)
Definition at line 678 of file __clang_cuda_device_functions.h.
References __a, and __nv_ull2float_rn().
__ull2float_ru()
__DEVICE__ float __ull2float_ru (unsigned long long __a)
Definition at line 681 of file __clang_cuda_device_functions.h.
References __a, and __nv_ull2float_ru().
__ull2float_rz()
__DEVICE__ float __ull2float_rz (unsigned long long __a)
Definition at line 684 of file __clang_cuda_device_functions.h.
References __a, and __nv_ull2float_rz().
__ullAtomicAdd()
__DEVICE__ unsigned long long __ullAtomicAdd (unsigned long long * __p, unsigned long long __v)
Definition at line 687 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicAdd_block()
__DEVICE__ unsigned long long __ullAtomicAdd_block (unsigned long long * __p, unsigned long long __v)
Definition at line 691 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicAdd_system()
__DEVICE__ unsigned long long __ullAtomicAdd_system (unsigned long long * __p, unsigned long long __v)
Definition at line 695 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicAnd()
__DEVICE__ unsigned long long __ullAtomicAnd (unsigned long long * __p, unsigned long long __v)
Definition at line 699 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicAnd_block()
__DEVICE__ unsigned long long __ullAtomicAnd_block (unsigned long long * __p, unsigned long long __v)
Definition at line 703 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicAnd_system()
__DEVICE__ unsigned long long __ullAtomicAnd_system (unsigned long long * __p, unsigned long long __v)
Definition at line 707 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicCAS()
__DEVICE__ unsigned long long __ullAtomicCAS (unsigned long long * __p, unsigned long long __cmp, unsigned long long __v)
Definition at line 711 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicCAS_block()
__DEVICE__ unsigned long long __ullAtomicCAS_block (unsigned long long * __p, unsigned long long __cmp, unsigned long long __v)
Definition at line 716 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicCAS_system()
__DEVICE__ unsigned long long __ullAtomicCAS_system (unsigned long long * __p, unsigned long long __cmp, unsigned long long __v)
Definition at line 721 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicExch()
__DEVICE__ unsigned long long __ullAtomicExch (unsigned long long * __p, unsigned long long __v)
Definition at line 726 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicExch_block()
__DEVICE__ unsigned long long __ullAtomicExch_block (unsigned long long * __p, unsigned long long __v)
Definition at line 730 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicExch_system()
__DEVICE__ unsigned long long __ullAtomicExch_system (unsigned long long * __p, unsigned long long __v)
Definition at line 734 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicMax()
__DEVICE__ unsigned long long __ullAtomicMax (unsigned long long * __p, unsigned long long __v)
Definition at line 738 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicMax_block()
__DEVICE__ unsigned long long __ullAtomicMax_block (unsigned long long * __p, unsigned long long __v)
Definition at line 742 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicMax_system()
__DEVICE__ unsigned long long __ullAtomicMax_system (unsigned long long * __p, unsigned long long __v)
Definition at line 746 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicMin()
__DEVICE__ unsigned long long __ullAtomicMin (unsigned long long * __p, unsigned long long __v)
Definition at line 750 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicMin_block()
__DEVICE__ unsigned long long __ullAtomicMin_block (unsigned long long * __p, unsigned long long __v)
Definition at line 754 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicMin_system()
__DEVICE__ unsigned long long __ullAtomicMin_system (unsigned long long * __p, unsigned long long __v)
Definition at line 758 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicOr()
__DEVICE__ unsigned long long __ullAtomicOr (unsigned long long * __p, unsigned long long __v)
Definition at line 762 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicOr_block()
__DEVICE__ unsigned long long __ullAtomicOr_block (unsigned long long * __p, unsigned long long __v)
Definition at line 766 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicOr_system()
__DEVICE__ unsigned long long __ullAtomicOr_system (unsigned long long * __p, unsigned long long __v)
Definition at line 770 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicXor()
__DEVICE__ unsigned long long __ullAtomicXor (unsigned long long * __p, unsigned long long __v)
Definition at line 774 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicXor_block()
__DEVICE__ unsigned long long __ullAtomicXor_block (unsigned long long * __p, unsigned long long __v)
Definition at line 778 of file __clang_cuda_device_functions.h.
References __p, and __v.
__ullAtomicXor_system()
__DEVICE__ unsigned long long __ullAtomicXor_system (unsigned long long * __p, unsigned long long __v)
Definition at line 782 of file __clang_cuda_device_functions.h.
References __p, and __v.
__umul24()
__DEVICE__ unsigned int __umul24 (unsigned int __a, unsigned int __b)
Definition at line 786 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_umul24().
__umul64hi()
__DEVICE__ unsigned long long __umul64hi (unsigned long long __a, unsigned long long __b)
Definition at line 789 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_umul64hi().
__umulhi()
__DEVICE__ unsigned int __umulhi (unsigned int __a, unsigned int __b)
Definition at line 793 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_umulhi().
__urhadd()
__DEVICE__ unsigned int __urhadd (unsigned int __a, unsigned int __b)
Definition at line 796 of file __clang_cuda_device_functions.h.
References __a, __b, and __nv_urhadd().
__usad()
__DEVICE__ unsigned int __usad (unsigned int __a, unsigned int __b, unsigned int __c)
Definition at line 799 of file __clang_cuda_device_functions.h.
References __a, __b, __c, and __nv_usad().
__vabs2()
__DEVICE__ unsigned int __vabs2 (unsigned int __a)
Definition at line 1054 of file __clang_cuda_device_functions.h.
References __a.
__vabs4()
__DEVICE__ unsigned int __vabs4 (unsigned int __a)
Definition at line 1061 of file __clang_cuda_device_functions.h.
References __a.
__vabsdiffs2()
__DEVICE__ unsigned int __vabsdiffs2 (unsigned int __a, unsigned int __b)
Definition at line 1068 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vabsdiffs4()
__DEVICE__ unsigned int __vabsdiffs4 (unsigned int __a, unsigned int __b)
Definition at line 1076 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vabsdiffu2()
__DEVICE__ unsigned int __vabsdiffu2 (unsigned int __a, unsigned int __b)
Definition at line 1083 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vabsdiffu4()
__DEVICE__ unsigned int __vabsdiffu4 (unsigned int __a, unsigned int __b)
Definition at line 1090 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vabsss2()
__DEVICE__ unsigned int __vabsss2 (unsigned int __a)
Definition at line 1097 of file __clang_cuda_device_functions.h.
References __a.
__vabsss4()
__DEVICE__ unsigned int __vabsss4 (unsigned int __a)
Definition at line 1104 of file __clang_cuda_device_functions.h.
References __a.
__vadd2()
__DEVICE__ unsigned int __vadd2 (unsigned int __a, unsigned int __b)
Definition at line 1111 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vadd4()
__DEVICE__ unsigned int __vadd4 (unsigned int __a, unsigned int __b)
Definition at line 1118 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vaddss2()
__DEVICE__ unsigned int __vaddss2 (unsigned int __a, unsigned int __b)
Definition at line 1125 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vaddss4()
__DEVICE__ unsigned int __vaddss4 (unsigned int __a, unsigned int __b)
Definition at line 1132 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vaddus2()
__DEVICE__ unsigned int __vaddus2 (unsigned int __a, unsigned int __b)
Definition at line 1139 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vaddus4()
__DEVICE__ unsigned int __vaddus4 (unsigned int __a, unsigned int __b)
Definition at line 1146 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vavgs2()
__DEVICE__ unsigned int __vavgs2 (unsigned int __a, unsigned int __b)
Definition at line 1153 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vavgs4()
__DEVICE__ unsigned int __vavgs4 (unsigned int __a, unsigned int __b)
Definition at line 1160 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vavgu2()
__DEVICE__ unsigned int __vavgu2 (unsigned int __a, unsigned int __b)
Definition at line 1167 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vavgu4()
__DEVICE__ unsigned int __vavgu4 (unsigned int __a, unsigned int __b)
Definition at line 1174 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vcmpeq2()
__DEVICE__ unsigned int __vcmpeq2 (unsigned int __a, unsigned int __b)
Definition at line 1188 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vseteq2().
__vcmpeq4()
__DEVICE__ unsigned int __vcmpeq4 (unsigned int __a, unsigned int __b)
Definition at line 1198 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vseteq4().
__vcmpges2()
__DEVICE__ unsigned int __vcmpges2 (unsigned int __a, unsigned int __b)
Definition at line 1208 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetges2().
__vcmpges4()
__DEVICE__ unsigned int __vcmpges4 (unsigned int __a, unsigned int __b)
Definition at line 1218 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetges4().
__vcmpgeu2()
__DEVICE__ unsigned int __vcmpgeu2 (unsigned int __a, unsigned int __b)
Definition at line 1228 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetgeu2().
__vcmpgeu4()
__DEVICE__ unsigned int __vcmpgeu4 (unsigned int __a, unsigned int __b)
Definition at line 1238 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetgeu4().
__vcmpgts2()
__DEVICE__ unsigned int __vcmpgts2 (unsigned int __a, unsigned int __b)
Definition at line 1248 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetgts2().
Referenced by __vmaxs2().
__vcmpgts4()
__DEVICE__ unsigned int __vcmpgts4 (unsigned int __a, unsigned int __b)
Definition at line 1258 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetgts4().
__vcmpgtu2()
__DEVICE__ unsigned int __vcmpgtu2 (unsigned int __a, unsigned int __b)
Definition at line 1268 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetgtu2().
__vcmpgtu4()
__DEVICE__ unsigned int __vcmpgtu4 (unsigned int __a, unsigned int __b)
Definition at line 1278 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetgtu4().
__vcmples2()
__DEVICE__ unsigned int __vcmples2 (unsigned int __a, unsigned int __b)
Definition at line 1288 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetles2().
__vcmples4()
__DEVICE__ unsigned int __vcmples4 (unsigned int __a, unsigned int __b)
Definition at line 1298 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetles4().
__vcmpleu2()
__DEVICE__ unsigned int __vcmpleu2 (unsigned int __a, unsigned int __b)
Definition at line 1308 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetleu2().
__vcmpleu4()
__DEVICE__ unsigned int __vcmpleu4 (unsigned int __a, unsigned int __b)
Definition at line 1318 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetleu4().
__vcmplts2()
__DEVICE__ unsigned int __vcmplts2 (unsigned int __a, unsigned int __b)
Definition at line 1328 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetlts2().
__vcmplts4()
__DEVICE__ unsigned int __vcmplts4 (unsigned int __a, unsigned int __b)
Definition at line 1338 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetlts4().
__vcmpltu2()
__DEVICE__ unsigned int __vcmpltu2 (unsigned int __a, unsigned int __b)
Definition at line 1348 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetltu2().
__vcmpltu4()
__DEVICE__ unsigned int __vcmpltu4 (unsigned int __a, unsigned int __b)
Definition at line 1358 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetltu4().
__vcmpne2()
__DEVICE__ unsigned int __vcmpne2 (unsigned int __a, unsigned int __b)
Definition at line 1368 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetne2().
__vcmpne4()
__DEVICE__ unsigned int __vcmpne4 (unsigned int __a, unsigned int __b)
Definition at line 1378 of file __clang_cuda_device_functions.h.
References __a, __b, __bool2mask(), and __vsetne4().
__vhaddu2()
__DEVICE__ unsigned int __vhaddu2 (unsigned int __a, unsigned int __b)
Definition at line 1387 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vhaddu4()
__DEVICE__ unsigned int __vhaddu4 (unsigned int __a, unsigned int __b)
Definition at line 1390 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vmaxs2()
__DEVICE__ unsigned int __vmaxs2 (unsigned int __a, unsigned int __b)
Definition at line 1394 of file __clang_cuda_device_functions.h.
References __a, __b, and __vcmpgts2().
__vmaxs4()
__DEVICE__ unsigned int __vmaxs4 (unsigned int __a, unsigned int __b)
Definition at line 1408 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vmaxu2()
__DEVICE__ unsigned int __vmaxu2 (unsigned int __a, unsigned int __b)
Definition at line 1415 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vmaxu4()
__DEVICE__ unsigned int __vmaxu4 (unsigned int __a, unsigned int __b)
Definition at line 1422 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vmins2()
__DEVICE__ unsigned int __vmins2 (unsigned int __a, unsigned int __b)
Definition at line 1429 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vmins4()
__DEVICE__ unsigned int __vmins4 (unsigned int __a, unsigned int __b)
Definition at line 1436 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vminu2()
__DEVICE__ unsigned int __vminu2 (unsigned int __a, unsigned int __b)
Definition at line 1443 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vminu4()
__DEVICE__ unsigned int __vminu4 (unsigned int __a, unsigned int __b)
Definition at line 1450 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vneg2()
__DEVICE__ unsigned int __vneg2 (unsigned int __a)
Definition at line 1493 of file __clang_cuda_device_functions.h.
References __a, and __vsub2().
__vneg4()
__DEVICE__ unsigned int __vneg4 (unsigned int __a)
Definition at line 1502 of file __clang_cuda_device_functions.h.
References __a, and __vsub4().
__vnegss2()
__DEVICE__ unsigned int __vnegss2 (unsigned int __a)
Definition at line 1510 of file __clang_cuda_device_functions.h.
References __a, and __vsubss2().
__vnegss4()
__DEVICE__ unsigned int __vnegss4 (unsigned int __a)
Definition at line 1520 of file __clang_cuda_device_functions.h.
References __a, and __vsubss4().
__vsads2()
__DEVICE__ unsigned int __vsads2 (unsigned int __a, unsigned int __b)
Definition at line 1457 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vsads4()
__DEVICE__ unsigned int __vsads4 (unsigned int __a, unsigned int __b)
Definition at line 1464 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vsadu2()
__DEVICE__ unsigned int __vsadu2 (unsigned int __a, unsigned int __b)
Definition at line 1471 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vsadu4()
__DEVICE__ unsigned int __vsadu4 (unsigned int __a, unsigned int __b)
Definition at line 1478 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vseteq2()
__DEVICE__ unsigned int __vseteq2 (unsigned int __a, unsigned int __b)
Definition at line 1181 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpeq2().
__vseteq4()
__DEVICE__ unsigned int __vseteq4 (unsigned int __a, unsigned int __b)
Definition at line 1191 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpeq4().
__vsetges2()
__DEVICE__ unsigned int __vsetges2 (unsigned int __a, unsigned int __b)
Definition at line 1201 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpges2().
__vsetges4()
__DEVICE__ unsigned int __vsetges4 (unsigned int __a, unsigned int __b)
Definition at line 1211 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpges4().
__vsetgeu2()
__DEVICE__ unsigned int __vsetgeu2 (unsigned int __a, unsigned int __b)
Definition at line 1221 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpgeu2().
__vsetgeu4()
__DEVICE__ unsigned int __vsetgeu4 (unsigned int __a, unsigned int __b)
Definition at line 1231 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpgeu4().
__vsetgts2()
__DEVICE__ unsigned int __vsetgts2 (unsigned int __a, unsigned int __b)
Definition at line 1241 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpgts2().
__vsetgts4()
__DEVICE__ unsigned int __vsetgts4 (unsigned int __a, unsigned int __b)
Definition at line 1251 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpgts4().
__vsetgtu2()
__DEVICE__ unsigned int __vsetgtu2 (unsigned int __a, unsigned int __b)
Definition at line 1261 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpgtu2().
__vsetgtu4()
__DEVICE__ unsigned int __vsetgtu4 (unsigned int __a, unsigned int __b)
Definition at line 1271 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpgtu4().
__vsetles2()
__DEVICE__ unsigned int __vsetles2 (unsigned int __a, unsigned int __b)
Definition at line 1281 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmples2().
__vsetles4()
__DEVICE__ unsigned int __vsetles4 (unsigned int __a, unsigned int __b)
Definition at line 1291 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmples4().
__vsetleu2()
__DEVICE__ unsigned int __vsetleu2 (unsigned int __a, unsigned int __b)
Definition at line 1301 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpleu2().
__vsetleu4()
__DEVICE__ unsigned int __vsetleu4 (unsigned int __a, unsigned int __b)
Definition at line 1311 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpleu4().
__vsetlts2()
__DEVICE__ unsigned int __vsetlts2 (unsigned int __a, unsigned int __b)
Definition at line 1321 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmplts2().
__vsetlts4()
__DEVICE__ unsigned int __vsetlts4 (unsigned int __a, unsigned int __b)
Definition at line 1331 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmplts4().
__vsetltu2()
__DEVICE__ unsigned int __vsetltu2 (unsigned int __a, unsigned int __b)
Definition at line 1341 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpltu2().
__vsetltu4()
__DEVICE__ unsigned int __vsetltu4 (unsigned int __a, unsigned int __b)
Definition at line 1351 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpltu4().
__vsetne2()
__DEVICE__ unsigned int __vsetne2 (unsigned int __a, unsigned int __b)
Definition at line 1361 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpne2().
__vsetne4()
__DEVICE__ unsigned int __vsetne4 (unsigned int __a, unsigned int __b)
Definition at line 1371 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vcmpne4().
__vsub2()
__DEVICE__ unsigned int __vsub2 (unsigned int __a, unsigned int __b)
Definition at line 1486 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vneg2().
__vsub4()
__DEVICE__ unsigned int __vsub4 (unsigned int __a, unsigned int __b)
Definition at line 1495 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vneg4().
__vsubss2()
__DEVICE__ unsigned int __vsubss2 (unsigned int __a, unsigned int __b)
Definition at line 1503 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vnegss2().
__vsubss4()
__DEVICE__ unsigned int __vsubss4 (unsigned int __a, unsigned int __b)
Definition at line 1513 of file __clang_cuda_device_functions.h.
References __a, and __b.
Referenced by __vnegss4().
__vsubus2()
__DEVICE__ unsigned int __vsubus2 (unsigned int __a, unsigned int __b)
Definition at line 1523 of file __clang_cuda_device_functions.h.
References __a, and __b.
__vsubus4()
__DEVICE__ unsigned int __vsubus4 (unsigned int __a, unsigned int __b)
Definition at line 1530 of file __clang_cuda_device_functions.h.
References __a, and __b.
clock()
__DEVICE__ int clock ()
Definition at line 1542 of file __clang_cuda_device_functions.h.
clock64()
__DEVICE__ long long clock64 ()
Definition at line 1544 of file __clang_cuda_device_functions.h.
memcpy()
__DEVICE__ void* memcpy (void * __a, const void * __b, size_t __c)
Definition at line 1549 of file __clang_cuda_device_functions.h.
References __a, __b, and __c.
Referenced by clang::ento::PathDiagnosticConsumer::FilesMade::addDiagnostic(), Append(), ASTAllocateString(), clang::CodeGenOptions::CodeGenOptions(), clang::AutoTypeLoc::copy(), clang::DependentNameTypeLoc::copy(), clang::DependentTemplateSpecializationTypeLoc::copy(), clang::ElaboratedTypeLoc::copy(), clang::TemplateSpecializationTypeLoc::copy(), clang::TypeLoc::copy(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal(), clang::extractapi::APISet::copyString(), clang::PragmaCommentDecl::Create(), createHash(), clang::interp::InterpState::deallocate(), clang::interp::Floating::deserialize(), clang::interp::IntegralAP< Signed >::deserialize(), getModuleContextHash(), clang::MSGuidDeclParts::getPart4And5AsUint64(), clang::ScratchBuffer::getToken(), clang::InclusionDirective::InclusionDirective(), clang::ObjCProtocolQualifiers< T >::initialize(), clang::comments::TextTokenRetokenizer::lexDelimitedSeq(), clang::Preprocessor::LexHeaderName(), clang::comments::TextTokenRetokenizer::lexWord(), LoadPointer(), LoadSourceLocation(), clang::sema::DelayedDiagnostic::makeAvailability(), clang::ObjCObjectType::ObjCObjectType(), clang::NestedNameSpecifierLocBuilder::operator=(), clang::CodeGen::EHScopeStack::pushCopyOfCleanup(), clang::threadSafety::til::SimpleArray< T >::reserve(), clang::CodeGenOptions::resetNonModularOptions(), clang::Sema::SaveNestedNameSpecifierAnnotation(), clang::interp::IntegralAP< Signed >::serialize(), clang::ObjCProtocolList::set(), clang::ObjCListBase::set(), clang::Sema::SetCtorInitializers(), clang::Sema::SetDelegatingInitializer(), clang::ShuffleVectorExpr::setExprs(), clang::ObjCImplementationDecl::setIvarInitializers(), clang::APValue::setLValue(), clang::MacroArgs::StringifyArgument(), and clang::ASTDeclReader::VisitPragmaCommentDecl().
memset()
__DEVICE__ void* memset (void * __a, int __b, size_t __c)
Definition at line 1552 of file __clang_cuda_device_functions.h.
References __a, __b, and __c.
Referenced by clang::DeclarationNameLoc::DeclarationNameLoc(), clang::interp::Block::invokeCtor(), clang::CodeGen::ObjCEntrypoints::ObjCEntrypoints(), clang::TokenConcatenation::TokenConcatenation(), clang::ReturnAdjustment::VirtualAdjustment::VirtualAdjustment(), and clang::ThisAdjustment::VirtualAdjustment::VirtualAdjustment().