clang: lib/Headers/__clang_hip_math.h File Reference
__clang_hip_math.h File Reference
#include <limits.h>
#include <stdint.h>
Macros
#define __DEVICE__ static __device__ inline __attribute__((always_inline))
#define __RETURN_TYPE int
#define __static_assert_type_size_equal(A, B) static_assert((A) == (B), "")
Functions
__DEVICE__ uint64_t __make_mantissa_base8 (const char *__tagp)
__DEVICE__ uint64_t __make_mantissa_base10 (const char *__tagp)
__DEVICE__ uint64_t __make_mantissa_base16 (const char *__tagp)
__DEVICE__ uint64_t __make_mantissa (const char *__tagp)
__DEVICE__ float acosf (float __x)
__DEVICE__ float acoshf (float __x)
__DEVICE__ float asinf (float __x)
__DEVICE__ float asinhf (float __x)
__DEVICE__ float atan2f (float __x, float __y)
__DEVICE__ float atanf (float __x)
__DEVICE__ float atanhf (float __x)
__DEVICE__ float cbrtf (float __x)
__DEVICE__ float ceilf (float __x)
__DEVICE__ float copysignf (float __x, float __y)
__DEVICE__ float cosf (float __x)
__DEVICE__ float coshf (float __x)
__DEVICE__ float cospif (float __x)
__DEVICE__ float cyl_bessel_i0f (float __x)
__DEVICE__ float cyl_bessel_i1f (float __x)
__DEVICE__ float erfcf (float __x)
__DEVICE__ float erfcinvf (float __x)
__DEVICE__ float erfcxf (float __x)
__DEVICE__ float erff (float __x)
__DEVICE__ float erfinvf (float __x)
__DEVICE__ float exp10f (float __x)
__DEVICE__ float exp2f (float __x)
__DEVICE__ float expf (float __x)
__DEVICE__ float expm1f (float __x)
__DEVICE__ float fabsf (float __x)
__DEVICE__ float fdimf (float __x, float __y)
__DEVICE__ float fdividef (float __x, float __y)
__DEVICE__ float floorf (float __x)
__DEVICE__ float fmaf (float __x, float __y, float __z)
__DEVICE__ float fmaxf (float __x, float __y)
__DEVICE__ float fminf (float __x, float __y)
__DEVICE__ float fmodf (float __x, float __y)
__DEVICE__ float frexpf (float __x, int *__nptr)
__DEVICE__ float hypotf (float __x, float __y)
__DEVICE__ int ilogbf (float __x)
__DEVICE__ __RETURN_TYPE __finitef (float __x)
__DEVICE__ __RETURN_TYPE __isinff (float __x)
__DEVICE__ __RETURN_TYPE __isnanf (float __x)
__DEVICE__ float j0f (float __x)
__DEVICE__ float j1f (float __x)
__DEVICE__ float jnf (int __n, float __x)
__DEVICE__ float ldexpf (float __x, int __e)
__DEVICE__ float lgammaf (float __x)
__DEVICE__ long long int llrintf (float __x)
__DEVICE__ long long int llroundf (float __x)
__DEVICE__ float log10f (float __x)
__DEVICE__ float log1pf (float __x)
__DEVICE__ float log2f (float __x)
__DEVICE__ float logbf (float __x)
__DEVICE__ float logf (float __x)
__DEVICE__ long int lrintf (float __x)
__DEVICE__ long int lroundf (float __x)
__DEVICE__ float modff (float __x, float *__iptr)
__DEVICE__ float nanf (const char *__tagp)
__DEVICE__ float nearbyintf (float __x)
__DEVICE__ float nextafterf (float __x, float __y)
__DEVICE__ float norm3df (float __x, float __y, float __z)
__DEVICE__ float norm4df (float __x, float __y, float __z, float __w)
__DEVICE__ float normcdff (float __x)
__DEVICE__ float normcdfinvf (float __x)
__DEVICE__ float normf (int __dim, const float *__a)
__DEVICE__ float powf (float __x, float __y)
__DEVICE__ float powif (float __x, int __y)
__DEVICE__ float rcbrtf (float __x)
__DEVICE__ float remainderf (float __x, float __y)
__DEVICE__ float remquof (float __x, float __y, int *__quo)
__DEVICE__ float rhypotf (float __x, float __y)
__DEVICE__ float rintf (float __x)
__DEVICE__ float rnorm3df (float __x, float __y, float __z)
__DEVICE__ float rnorm4df (float __x, float __y, float __z, float __w)
__DEVICE__ float rnormf (int __dim, const float *__a)
__DEVICE__ float roundf (float __x)
__DEVICE__ float rsqrtf (float __x)
__DEVICE__ float scalblnf (float __x, long int __n)
__DEVICE__ float scalbnf (float __x, int __n)
__DEVICE__ __RETURN_TYPE __signbitf (float __x)
__DEVICE__ void sincosf (float __x, float *__sinptr, float *__cosptr)
__DEVICE__ void sincospif (float __x, float *__sinptr, float *__cosptr)
__DEVICE__ float sinf (float __x)
__DEVICE__ float sinhf (float __x)
__DEVICE__ float sinpif (float __x)
__DEVICE__ float sqrtf (float __x)
__DEVICE__ float tanf (float __x)
__DEVICE__ float tanhf (float __x)
__DEVICE__ float tgammaf (float __x)
__DEVICE__ float truncf (float __x)
__DEVICE__ float y0f (float __x)
__DEVICE__ float y1f (float __x)
__DEVICE__ float ynf (int __n, float __x)
__DEVICE__ float __cosf (float __x)
__DEVICE__ float __exp10f (float __x)
__DEVICE__ float __expf (float __x)
__DEVICE__ float __fadd_rn (float __x, float __y)
__DEVICE__ float __fdiv_rn (float __x, float __y)
__DEVICE__ float __fdividef (float __x, float __y)
__DEVICE__ float __fmaf_rn (float __x, float __y, float __z)
__DEVICE__ float __fmul_rn (float __x, float __y)
__DEVICE__ float __frcp_rn (float __x)
__DEVICE__ float __frsqrt_rn (float __x)
__DEVICE__ float __fsqrt_rn (float __x)
__DEVICE__ float __fsub_rn (float __x, float __y)
__DEVICE__ float __log10f (float __x)
__DEVICE__ float __log2f (float __x)
__DEVICE__ float __logf (float __x)
__DEVICE__ float __powf (float __x, float __y)
__DEVICE__ float __saturatef (float __x)
__DEVICE__ void __sincosf (float __x, float *__sinptr, float *__cosptr)
__DEVICE__ float __sinf (float __x)
__DEVICE__ float __tanf (float __x)
__DEVICE__ double acos (double __x)
__DEVICE__ double acosh (double __x)
__DEVICE__ double asin (double __x)
__DEVICE__ double asinh (double __x)
__DEVICE__ double atan (double __x)
__DEVICE__ double atan2 (double __x, double __y)
__DEVICE__ double atanh (double __x)
__DEVICE__ double cbrt (double __x)
__DEVICE__ double ceil (double __x)
__DEVICE__ double copysign (double __x, double __y)
__DEVICE__ double cos (double __x)
__DEVICE__ double cosh (double __x)
__DEVICE__ double cospi (double __x)
__DEVICE__ double cyl_bessel_i0 (double __x)
__DEVICE__ double cyl_bessel_i1 (double __x)
__DEVICE__ double erf (double __x)
__DEVICE__ double erfc (double __x)
__DEVICE__ double erfcinv (double __x)
__DEVICE__ double erfcx (double __x)
__DEVICE__ double erfinv (double __x)
__DEVICE__ double exp (double __x)
__DEVICE__ double exp10 (double __x)
__DEVICE__ double exp2 (double __x)
__DEVICE__ double expm1 (double __x)
__DEVICE__ double fabs (double __x)
__DEVICE__ double fdim (double __x, double __y)
__DEVICE__ double floor (double __x)
__DEVICE__ double fma (double __x, double __y, double __z)
__DEVICE__ double fmax (double __x, double __y)
__DEVICE__ double fmin (double __x, double __y)
__DEVICE__ double fmod (double __x, double __y)
__DEVICE__ double frexp (double __x, int *__nptr)
__DEVICE__ double hypot (double __x, double __y)
__DEVICE__ int ilogb (double __x)
__DEVICE__ __RETURN_TYPE __finite (double __x)
__DEVICE__ __RETURN_TYPE __isinf (double __x)
__DEVICE__ __RETURN_TYPE __isnan (double __x)
__DEVICE__ double j0 (double __x)
__DEVICE__ double j1 (double __x)
__DEVICE__ double jn (int __n, double __x)
__DEVICE__ double ldexp (double __x, int __e)
__DEVICE__ double lgamma (double __x)
__DEVICE__ long long int llrint (double __x)
__DEVICE__ long long int llround (double __x)
__DEVICE__ double log (double __x)
__DEVICE__ double log10 (double __x)
__DEVICE__ double log1p (double __x)
__DEVICE__ double log2 (double __x)
__DEVICE__ double logb (double __x)
__DEVICE__ long int lrint (double __x)
__DEVICE__ long int lround (double __x)
__DEVICE__ double modf (double __x, double *__iptr)
__DEVICE__ double nan (const char *__tagp)
__DEVICE__ double nearbyint (double __x)
__DEVICE__ double nextafter (double __x, double __y)
__DEVICE__ double norm (int __dim, const double *__a)
__DEVICE__ double norm3d (double __x, double __y, double __z)
__DEVICE__ double norm4d (double __x, double __y, double __z, double __w)
__DEVICE__ double normcdf (double __x)
__DEVICE__ double normcdfinv (double __x)
__DEVICE__ double pow (double __x, double __y)
__DEVICE__ double powi (double __x, int __y)
__DEVICE__ double rcbrt (double __x)
__DEVICE__ double remainder (double __x, double __y)
__DEVICE__ double remquo (double __x, double __y, int *__quo)
__DEVICE__ double rhypot (double __x, double __y)
__DEVICE__ double rint (double __x)
__DEVICE__ double rnorm (int __dim, const double *__a)
__DEVICE__ double rnorm3d (double __x, double __y, double __z)
__DEVICE__ double rnorm4d (double __x, double __y, double __z, double __w)
__DEVICE__ double round (double __x)
__DEVICE__ double rsqrt (double __x)
__DEVICE__ double scalbln (double __x, long int __n)
__DEVICE__ double scalbn (double __x, int __n)
__DEVICE__ __RETURN_TYPE __signbit (double __x)
__DEVICE__ double sin (double __x)
__DEVICE__ void sincos (double __x, double *__sinptr, double *__cosptr)
__DEVICE__ void sincospi (double __x, double *__sinptr, double *__cosptr)
__DEVICE__ double sinh (double __x)
__DEVICE__ double sinpi (double __x)
__DEVICE__ double sqrt (double __x)
__DEVICE__ double tan (double __x)
__DEVICE__ double tanh (double __x)
__DEVICE__ double tgamma (double __x)
__DEVICE__ double trunc (double __x)
__DEVICE__ double y0 (double __x)
__DEVICE__ double y1 (double __x)
__DEVICE__ double yn (int __n, double __x)
__DEVICE__ double __dadd_rn (double __x, double __y)
__DEVICE__ double __ddiv_rn (double __x, double __y)
__DEVICE__ double __dmul_rn (double __x, double __y)
__DEVICE__ double __drcp_rn (double __x)
__DEVICE__ double __dsqrt_rn (double __x)
__DEVICE__ double __dsub_rn (double __x, double __y)
__DEVICE__ double __fma_rn (double __x, double __y, double __z)
Macro Definition Documentation
__DEVICE__
#define __DEVICE__ static __device__ inline __attribute__((always_inline))
Definition at line 32 of file __clang_hip_math.h.
__RETURN_TYPE
#define __RETURN_TYPE int
Definition at line 43 of file __clang_hip_math.h.
__static_assert_type_size_equal
#define __static_assert_type_size_equal (A, B) static_assert((A) == (B), "")
Definition at line 67 of file __clang_hip_math.h.
Function Documentation
__cosf()
__DEVICE__ float __cosf (float __x)
Definition at line 568 of file __clang_hip_math.h.
References __ocml_native_cos_f32(), and __x.
__dadd_rn()
__DEVICE__ double __dadd_rn (double __x, double __y)
Definition at line 1147 of file __clang_hip_math.h.
References __x, and __y.
__ddiv_rn()
__DEVICE__ double __ddiv_rn (double __x, double __y)
Definition at line 1169 of file __clang_hip_math.h.
References __x, and __y.
__dmul_rn()
__DEVICE__ double __dmul_rn (double __x, double __y)
Definition at line 1191 of file __clang_hip_math.h.
References __x, and __y.
__drcp_rn()
__DEVICE__ double __drcp_rn (double __x)
Definition at line 1205 of file __clang_hip_math.h.
References __x.
__dsqrt_rn()
__DEVICE__ double __dsqrt_rn (double __x)
Definition at line 1219 of file __clang_hip_math.h.
References __x.
__dsub_rn()
__DEVICE__ double __dsub_rn (double __x, double __y)
Definition at line 1241 of file __clang_hip_math.h.
References __x, and __y.
__exp10f()
__DEVICE__ float __exp10f (float __x)
Definition at line 571 of file __clang_hip_math.h.
References __x.
__expf()
__DEVICE__ float __expf (float __x)
Definition at line 574 of file __clang_hip_math.h.
References __x.
__fadd_rn()
__DEVICE__ float __fadd_rn (float __x, float __y)
Definition at line 587 of file __clang_hip_math.h.
References __x, and __y.
__fdiv_rn()
__DEVICE__ float __fdiv_rn (float __x, float __y)
Definition at line 601 of file __clang_hip_math.h.
References __x, and __y.
__fdividef()
__DEVICE__ float __fdividef (float __x, float __y)
Definition at line 605 of file __clang_hip_math.h.
References __x, and __y.
__finite()
__DEVICE__ __RETURN_TYPE __finite (double __x)
Definition at line 836 of file __clang_hip_math.h.
References __x.
__finitef()
__DEVICE__ __RETURN_TYPE __finitef (float __x)
Definition at line 281 of file __clang_hip_math.h.
References __x.
__fma_rn()
__DEVICE__ double __fma_rn (double __x, double __y, double __z)
Definition at line 1263 of file __clang_hip_math.h.
References __x, and __y.
__fmaf_rn()
__DEVICE__ float __fmaf_rn (float __x, float __y, float __z)
Definition at line 626 of file __clang_hip_math.h.
References __x, and __y.
__fmul_rn()
__DEVICE__ float __fmul_rn (float __x, float __y)
Definition at line 642 of file __clang_hip_math.h.
References __x, and __y.
__frcp_rn()
__DEVICE__ float __frcp_rn (float __x)
Definition at line 656 of file __clang_hip_math.h.
References __x.
__frsqrt_rn()
__DEVICE__ float __frsqrt_rn (float __x)
Definition at line 660 of file __clang_hip_math.h.
References __x.
__fsqrt_rn()
__DEVICE__ float __fsqrt_rn (float __x)
Definition at line 673 of file __clang_hip_math.h.
References __x.
__fsub_rn()
__DEVICE__ float __fsub_rn (float __x, float __y)
Definition at line 687 of file __clang_hip_math.h.
References __x, and __y.
__isinf()
__DEVICE__ __RETURN_TYPE __isinf (double __x)
Definition at line 839 of file __clang_hip_math.h.
References __x.
__isinff()
__DEVICE__ __RETURN_TYPE __isinff (float __x)
Definition at line 284 of file __clang_hip_math.h.
References __x.
__isnan()
__DEVICE__ __RETURN_TYPE __isnan (double __x)
Definition at line 842 of file __clang_hip_math.h.
References __x.
__isnanf()
__DEVICE__ __RETURN_TYPE __isnanf (float __x)
Definition at line 287 of file __clang_hip_math.h.
References __x.
__log10f()
__DEVICE__ float __log10f (float __x)
Definition at line 691 of file __clang_hip_math.h.
References __x.
__log2f()
__DEVICE__ float __log2f (float __x)
Definition at line 694 of file __clang_hip_math.h.
References __x.
__logf()
__DEVICE__ float __logf (float __x)
Definition at line 697 of file __clang_hip_math.h.
References __x.
__make_mantissa()
__DEVICE__ uint64_t __make_mantissa (const char * __tagp)
Definition at line 128 of file __clang_hip_math.h.
References __make_mantissa_base10(), __make_mantissa_base16(), and __make_mantissa_base8().
Referenced by nan(), and nanf().
__make_mantissa_base10()
__DEVICE__ uint64_t __make_mantissa_base10 (const char * __tagp)
Definition at line 90 of file __clang_hip_math.h.
Referenced by __make_mantissa().
__make_mantissa_base16()
__DEVICE__ uint64_t __make_mantissa_base16 (const char * __tagp)
Definition at line 107 of file __clang_hip_math.h.
Referenced by __make_mantissa().
__make_mantissa_base8()
__DEVICE__ uint64_t __make_mantissa_base8 (const char * __tagp)
Definition at line 73 of file __clang_hip_math.h.
Referenced by __make_mantissa().
__powf()
__DEVICE__ float __powf (float __x, float __y)
Definition at line 700 of file __clang_hip_math.h.
References __x, and __y.
__saturatef()
__DEVICE__ float __saturatef (float __x)
Definition at line 703 of file __clang_hip_math.h.
References __x.
__signbit()
__DEVICE__ __RETURN_TYPE __signbit (double __x)
Definition at line 1051 of file __clang_hip_math.h.
References __x.
__signbitf()
__DEVICE__ __RETURN_TYPE __signbitf (float __x)
Definition at line 489 of file __clang_hip_math.h.
References __x.
__sincosf()
__DEVICE__ void __sincosf (float __x, float * __sinptr, float * __cosptr)
Definition at line 706 of file __clang_hip_math.h.
References __ocml_native_cos_f32(), __ocml_native_sin_f32(), and __x.
__sinf()
__DEVICE__ float __sinf (float __x)
Definition at line 712 of file __clang_hip_math.h.
References __ocml_native_sin_f32(), and __x.
__tanf()
__DEVICE__ float __tanf (float __x)
Definition at line 715 of file __clang_hip_math.h.
References __ocml_tan_f32(), and __x.
acos()
__DEVICE__ double acos (double __x)
Definition at line 721 of file __clang_hip_math.h.
References __a, __nv_acos(), and __x.
acosf()
__DEVICE__ float acosf (float __x)
Definition at line 164 of file __clang_hip_math.h.
References __x.
acosh()
__DEVICE__ double acosh (double __x)
Definition at line 724 of file __clang_hip_math.h.
References __a, __nv_acosh(), and __x.
acoshf()
__DEVICE__ float acoshf (float __x)
Definition at line 167 of file __clang_hip_math.h.
References __x.
asin()
__DEVICE__ double asin (double __x)
Definition at line 727 of file __clang_hip_math.h.
References __a, __nv_asin(), and __x.
asinf()
__DEVICE__ float asinf (float __x)
Definition at line 170 of file __clang_hip_math.h.
References __x.
asinh()
__DEVICE__ double asinh (double __x)
Definition at line 730 of file __clang_hip_math.h.
References __a, __nv_asinh(), and __x.
asinhf()
__DEVICE__ float asinhf (float __x)
Definition at line 173 of file __clang_hip_math.h.
References __x.
atan()
__DEVICE__ double atan (double __x)
Definition at line 733 of file __clang_hip_math.h.
References __a, __nv_atan(), and __x.
atan2()
__DEVICE__ double atan2 (double __x, double __y)
Definition at line 736 of file __clang_hip_math.h.
References __a, __b, __nv_atan2(), __x, and __y.
atan2f()
__DEVICE__ float atan2f (float __x, float __y)
Definition at line 176 of file __clang_hip_math.h.
References __x, and __y.
atanf()
__DEVICE__ float atanf (float __x)
Definition at line 179 of file __clang_hip_math.h.
References __x.
atanh()
__DEVICE__ double atanh (double __x)
Definition at line 739 of file __clang_hip_math.h.
References __a, __nv_atanh(), and __x.
atanhf()
__DEVICE__ float atanhf (float __x)
Definition at line 182 of file __clang_hip_math.h.
References __x.
cbrt()
__DEVICE__ double cbrt (double __x)
Definition at line 742 of file __clang_hip_math.h.
References __a, __nv_cbrt(), and __x.
cbrtf()
__DEVICE__ float cbrtf (float __x)
Definition at line 185 of file __clang_hip_math.h.
References __x.
ceil()
__DEVICE__ double ceil (double __x)
Definition at line 745 of file __clang_hip_math.h.
References __a, __nv_ceil(), and __x.
ceilf()
__DEVICE__ float ceilf (float __x)
Definition at line 188 of file __clang_hip_math.h.
References __x.
copysign()
__DEVICE__ double copysign (double __x, double __y)
Definition at line 748 of file __clang_hip_math.h.
References __a, __b, __nv_copysign(), __x, and __y.
copysignf()
__DEVICE__ float copysignf (float __x, float __y)
Definition at line 191 of file __clang_hip_math.h.
References __x, and __y.
cos()
__DEVICE__ double cos (double __x)
Definition at line 753 of file __clang_hip_math.h.
References __a, __nv_cos(), __ocml_cos_f64(), and __x.
cosf()
__DEVICE__ float cosf (float __x)
Definition at line 194 of file __clang_hip_math.h.
References __ocml_cos_f32(), and __x.
cosh()
__DEVICE__ double cosh (double __x)
Definition at line 756 of file __clang_hip_math.h.
References __a, __nv_cosh(), and __x.
coshf()
__DEVICE__ float coshf (float __x)
Definition at line 197 of file __clang_hip_math.h.
References __x.
cospi()
__DEVICE__ double cospi (double __x)
Definition at line 759 of file __clang_hip_math.h.
References __ocml_cospi_f64(), and __x.
cospif()
__DEVICE__ float cospif (float __x)
Definition at line 200 of file __clang_hip_math.h.
References __ocml_cospi_f32(), and __x.
cyl_bessel_i0()
__DEVICE__ double cyl_bessel_i0 (double __x)
Definition at line 762 of file __clang_hip_math.h.
References __ocml_i0_f64(), and __x.
cyl_bessel_i0f()
__DEVICE__ float cyl_bessel_i0f (float __x)
Definition at line 203 of file __clang_hip_math.h.
References __ocml_i0_f32(), and __x.
cyl_bessel_i1()
__DEVICE__ double cyl_bessel_i1 (double __x)
Definition at line 765 of file __clang_hip_math.h.
References __ocml_i1_f64(), and __x.
cyl_bessel_i1f()
__DEVICE__ float cyl_bessel_i1f (float __x)
Definition at line 206 of file __clang_hip_math.h.
References __ocml_i1_f32(), and __x.
erf()
__DEVICE__ double erf (double __x)
Definition at line 768 of file __clang_hip_math.h.
References __a, __nv_erf(), and __x.
erfc()
__DEVICE__ double erfc (double __x)
Definition at line 771 of file __clang_hip_math.h.
References __a, __nv_erfc(), and __x.
erfcf()
__DEVICE__ float erfcf (float __x)
Definition at line 209 of file __clang_hip_math.h.
References __x.
erfcinv()
__DEVICE__ double erfcinv (double __x)
Definition at line 774 of file __clang_hip_math.h.
References __x.
erfcinvf()
__DEVICE__ float erfcinvf (float __x)
Definition at line 212 of file __clang_hip_math.h.
References __x.
erfcx()
__DEVICE__ double erfcx (double __x)
Definition at line 777 of file __clang_hip_math.h.
References __x.
erfcxf()
__DEVICE__ float erfcxf (float __x)
Definition at line 215 of file __clang_hip_math.h.
References __x.
erff()
__DEVICE__ float erff (float __x)
Definition at line 218 of file __clang_hip_math.h.
References __x.
erfinv()
__DEVICE__ double erfinv (double __x)
Definition at line 780 of file __clang_hip_math.h.
References __x.
erfinvf()
__DEVICE__ float erfinvf (float __x)
Definition at line 221 of file __clang_hip_math.h.
References __x.
exp()
__DEVICE__ double exp (double __x)
Definition at line 783 of file __clang_hip_math.h.
References __a, __nv_exp(), and __x.
exp10()
__DEVICE__ double exp10 (double __x)
Definition at line 786 of file __clang_hip_math.h.
References __x.
exp10f()
__DEVICE__ float exp10f (float __x)
Definition at line 224 of file __clang_hip_math.h.
References __x.
exp2()
__DEVICE__ double exp2 (double __x)
Definition at line 789 of file __clang_hip_math.h.
References __a, __nv_exp2(), and __x.
exp2f()
__DEVICE__ float exp2f (float __x)
Definition at line 227 of file __clang_hip_math.h.
References __x.
expf()
__DEVICE__ float expf (float __x)
Definition at line 230 of file __clang_hip_math.h.
References __x.
expm1()
__DEVICE__ double expm1 (double __x)
Definition at line 792 of file __clang_hip_math.h.
References __a, __nv_expm1(), and __x.
expm1f()
__DEVICE__ float expm1f (float __x)
Definition at line 233 of file __clang_hip_math.h.
References __x.
fabs()
__DEVICE__ double fabs (double __x)
Definition at line 795 of file __clang_hip_math.h.
References __a, __nv_fabs(), and __x.
fabsf()
__DEVICE__ float fabsf (float __x)
Definition at line 236 of file __clang_hip_math.h.
References __x.
fdim()
__DEVICE__ double fdim (double __x, double __y)
Definition at line 798 of file __clang_hip_math.h.
References __a, __b, __nv_fdim(), __x, and __y.
fdimf()
__DEVICE__ float fdimf (float __x, float __y)
Definition at line 239 of file __clang_hip_math.h.
References __x, and __y.
fdividef()
__DEVICE__ float fdividef (float __x, float __y)
Definition at line 242 of file __clang_hip_math.h.
References __x, and __y.
floor()
__DEVICE__ double floor (double __x)
Definition at line 801 of file __clang_hip_math.h.
References __nv_floor(), and __x.
floorf()
__DEVICE__ float floorf (float __x)
Definition at line 245 of file __clang_hip_math.h.
References __x.
fma()
__DEVICE__ double fma (double __x, double __y, double __z)
Definition at line 804 of file __clang_hip_math.h.
References __a, __b, __c, __nv_fma(), __x, and __y.
fmaf()
__DEVICE__ float fmaf (float __x, float __y, float __z)
Definition at line 248 of file __clang_hip_math.h.
References __x, and __y.
fmax()
__DEVICE__ double fmax (double __x, double __y)
Definition at line 809 of file __clang_hip_math.h.
References __a, __b, __nv_fmax(), __x, and __y.
fmaxf()
__DEVICE__ float fmaxf (float __x, float __y)
Definition at line 253 of file __clang_hip_math.h.
References __x, and __y.
fmin()
__DEVICE__ double fmin (double __x, double __y)
Definition at line 812 of file __clang_hip_math.h.
References __a, __b, __nv_fmin(), __x, and __y.
fminf()
__DEVICE__ float fminf (float __x, float __y)
Definition at line 256 of file __clang_hip_math.h.
References __x, and __y.
fmod()
__DEVICE__ double fmod (double __x, double __y)
Definition at line 815 of file __clang_hip_math.h.
References __a, __b, __nv_fmod(), __x, and __y.
fmodf()
__DEVICE__ float fmodf (float __x, float __y)
Definition at line 259 of file __clang_hip_math.h.
References __x, and __y.
frexp()
__DEVICE__ double frexp (double __x, int * __nptr)
Definition at line 818 of file __clang_hip_math.h.
References __a, __b, __nv_frexp(), __ocml_frexp_f64(), and __x.
frexpf()
__DEVICE__ float frexpf (float __x, int * __nptr)
Definition at line 262 of file __clang_hip_math.h.
References __ocml_frexp_f32(), and __x.
hypot()
__DEVICE__ double hypot (double __x, double __y)
Definition at line 830 of file __clang_hip_math.h.
References __a, __b, __nv_hypot(), __x, and __y.
hypotf()
__DEVICE__ float hypotf (float __x, float __y)
Definition at line 275 of file __clang_hip_math.h.
References __x, and __y.
ilogb()
__DEVICE__ int ilogb (double __x)
Definition at line 833 of file __clang_hip_math.h.
References __a, __nv_ilogb(), and __x.
ilogbf()
__DEVICE__ int ilogbf (float __x)
Definition at line 278 of file __clang_hip_math.h.
References __x.
j0()
__DEVICE__ double j0 (double __x)
Definition at line 845 of file __clang_hip_math.h.
References __ocml_j0_f64(), and __x.
Referenced by jn().
j0f()
__DEVICE__ float j0f (float __x)
Definition at line 290 of file __clang_hip_math.h.
References __ocml_j0_f32(), and __x.
Referenced by jnf().
j1()
__DEVICE__ double j1 (double __x)
Definition at line 848 of file __clang_hip_math.h.
References __ocml_j1_f64(), and __x.
Referenced by jn().
j1f()
__DEVICE__ float j1f (float __x)
Definition at line 293 of file __clang_hip_math.h.
References __ocml_j1_f32(), and __x.
Referenced by jnf().
jn()
__DEVICE__ double jn (int __n, double __x)
Definition at line 851 of file __clang_hip_math.h.
References __x, j0(), and j1().
jnf()
__DEVICE__ float jnf (int __n, float __x)
Definition at line 296 of file __clang_hip_math.h.
References __x, j0f(), and j1f().
ldexp()
__DEVICE__ double ldexp (double __x, int __e)
Definition at line 872 of file __clang_hip_math.h.
References __a, __b, __nv_ldexp(), and __x.
ldexpf()
__DEVICE__ float ldexpf (float __x, int __e)
Definition at line 317 of file __clang_hip_math.h.
References __x.
lgamma()
__DEVICE__ double lgamma (double __x)
Definition at line 875 of file __clang_hip_math.h.
References __a, __nv_lgamma(), __ocml_lgamma_f64(), and __x.
lgammaf()
__DEVICE__ float lgammaf (float __x)
Definition at line 320 of file __clang_hip_math.h.
References __ocml_lgamma_f32(), and __x.
llrint()
__DEVICE__ long long int llrint (double __x)
Definition at line 878 of file __clang_hip_math.h.
References __a, __nv_llrint(), and __x.
llrintf()
__DEVICE__ long long int llrintf (float __x)
Definition at line 323 of file __clang_hip_math.h.
References __x.
llround()
__DEVICE__ long long int llround (double __x)
Definition at line 881 of file __clang_hip_math.h.
References __x.
llroundf()
__DEVICE__ long long int llroundf (float __x)
Definition at line 326 of file __clang_hip_math.h.
References __x.
log()
__DEVICE__ double log (double __x)
Definition at line 884 of file __clang_hip_math.h.
References __a, __nv_log(), and __x.
log10()
__DEVICE__ double log10 (double __x)
Definition at line 887 of file __clang_hip_math.h.
References __a, __nv_log10(), and __x.
log10f()
__DEVICE__ float log10f (float __x)
Definition at line 329 of file __clang_hip_math.h.
References __x.
log1p()
__DEVICE__ double log1p (double __x)
Definition at line 890 of file __clang_hip_math.h.
References __a, __nv_log1p(), and __x.
log1pf()
__DEVICE__ float log1pf (float __x)
Definition at line 332 of file __clang_hip_math.h.
References __x.
log2()
__DEVICE__ double log2 (double __x)
Definition at line 893 of file __clang_hip_math.h.
References __a, __nv_log2(), and __x.
log2f()
__DEVICE__ float log2f (float __x)
Definition at line 335 of file __clang_hip_math.h.
References __x.
logb()
__DEVICE__ double logb (double __x)
Definition at line 896 of file __clang_hip_math.h.
References __a, __nv_logb(), and __x.
logbf()
__DEVICE__ float logbf (float __x)
Definition at line 338 of file __clang_hip_math.h.
References __x.
logf()
__DEVICE__ float logf (float __x)
Definition at line 341 of file __clang_hip_math.h.
References __x.
lrint()
__DEVICE__ long int lrint (double __x)
Definition at line 899 of file __clang_hip_math.h.
References __a, __x, and rint().
lrintf()
__DEVICE__ long int lrintf (float __x)
Definition at line 344 of file __clang_hip_math.h.
References __x.
lround()
__DEVICE__ long int lround (double __x)
Definition at line 902 of file __clang_hip_math.h.
References __a, __x, and round().
lroundf()
__DEVICE__ long int lroundf (float __x)
Definition at line 347 of file __clang_hip_math.h.
References __x.
modf()
__DEVICE__ double modf (double __x, double * __iptr)
Definition at line 905 of file __clang_hip_math.h.
References __a, __b, __nv_modf(), __ocml_modf_f64(), and __x.
modff()
__DEVICE__ float modff (float __x, float * __iptr)
Definition at line 350 of file __clang_hip_math.h.
References __ocml_modf_f32(), and __x.
nan()
__DEVICE__ double nan (const char * __tagp)
Definition at line 918 of file __clang_hip_math.h.
References __make_mantissa(), __static_assert_type_size_equal, and sign().
Referenced by mutateLongDoubleBuiltin().
nanf()
__DEVICE__ float nanf (const char * __tagp)
Definition at line 362 of file __clang_hip_math.h.
References __make_mantissa(), __static_assert_type_size_equal, and sign().
nearbyint()
__DEVICE__ double nearbyint (double __x)
Definition at line 946 of file __clang_hip_math.h.
References __a, and __x.
nearbyintf()
__DEVICE__ float nearbyintf (float __x)
Definition at line 383 of file __clang_hip_math.h.
References __x.
nextafter()
__DEVICE__ double nextafter (double __x, double __y)
Definition at line 949 of file __clang_hip_math.h.
References __a, __b, __nv_nextafter(), __x, and __y.
nextafterf()
__DEVICE__ float nextafterf (float __x, float __y)
Definition at line 386 of file __clang_hip_math.h.
References __x, and __y.
norm()
__DEVICE__ double norm (int __dim, const double * __a)
Definition at line 954 of file __clang_hip_math.h.
References __a.
norm3d()
__DEVICE__ double norm3d (double __x, double __y, double __z)
Definition at line 966 of file __clang_hip_math.h.
References __x, and __y.
norm3df()
__DEVICE__ float norm3df (float __x, float __y, float __z)
Definition at line 391 of file __clang_hip_math.h.
References __x, and __y.
norm4d()
__DEVICE__ double norm4d (double __x, double __y, double __z, double __w)
Definition at line 971 of file __clang_hip_math.h.
References __x, and __y.
norm4df()
__DEVICE__ float norm4df (float __x, float __y, float __z, float __w)
Definition at line 396 of file __clang_hip_math.h.
References __x, and __y.
normcdf()
__DEVICE__ double normcdf (double __x)
Definition at line 976 of file __clang_hip_math.h.
References __x.
normcdff()
__DEVICE__ float normcdff (float __x)
Definition at line 401 of file __clang_hip_math.h.
References __x.
normcdfinv()
__DEVICE__ double normcdfinv (double __x)
Definition at line 979 of file __clang_hip_math.h.
References __x.
normcdfinvf()
__DEVICE__ float normcdfinvf (float __x)
Definition at line 404 of file __clang_hip_math.h.
References __x.
normf()
__DEVICE__ float normf (int __dim, const float * __a)
Definition at line 407 of file __clang_hip_math.h.
References __a.
pow()
__DEVICE__ double pow (double __x, double __y)
Definition at line 982 of file __clang_hip_math.h.
References __a, __b, __nv_pow(), __x, and __y.
powf()
__DEVICE__ float powf (float __x, float __y)
Definition at line 419 of file __clang_hip_math.h.
References __x, and __y.
powi()
__DEVICE__ double powi (double __x, int __y)
Definition at line 985 of file __clang_hip_math.h.
References __x, and __y.
powif()
__DEVICE__ float powif (float __x, int __y)
Definition at line 422 of file __clang_hip_math.h.
References __x, and __y.
rcbrt()
__DEVICE__ double rcbrt (double __x)
Definition at line 988 of file __clang_hip_math.h.
References __x.
rcbrtf()
__DEVICE__ float rcbrtf (float __x)
Definition at line 425 of file __clang_hip_math.h.
References __x.
remainder()
__DEVICE__ double remainder (double __x, double __y)
Definition at line 991 of file __clang_hip_math.h.
References __a, __b, __nv_remainder(), __x, and __y.
remainderf()
__DEVICE__ float remainderf (float __x, float __y)
Definition at line 428 of file __clang_hip_math.h.
References __x, and __y.
remquo()
__DEVICE__ double remquo (double __x, double __y, int * __quo)
Definition at line 996 of file __clang_hip_math.h.
References __a, __b, __c, __nv_remquo(), __ocml_remquo_f64(), __x, and __y.
remquof()
__DEVICE__ float remquof (float __x, float __y, int * __quo)
Definition at line 433 of file __clang_hip_math.h.
References __ocml_remquo_f32(), __x, and __y.
rhypot()
__DEVICE__ double rhypot (double __x, double __y)
Definition at line 1009 of file __clang_hip_math.h.
References __x, and __y.
rhypotf()
__DEVICE__ float rhypotf (float __x, float __y)
Definition at line 446 of file __clang_hip_math.h.
References __x, and __y.
rint()
__DEVICE__ double rint (double __x)
Definition at line 1012 of file __clang_hip_math.h.
References __a, and __x.
rintf()
__DEVICE__ float rintf (float __x)
Definition at line 449 of file __clang_hip_math.h.
References __x.
rnorm()
__DEVICE__ double rnorm (int __dim, const double * __a)
Definition at line 1015 of file __clang_hip_math.h.
References __a.
rnorm3d()
__DEVICE__ double rnorm3d (double __x, double __y, double __z)
Definition at line 1027 of file __clang_hip_math.h.
References __x, and __y.
rnorm3df()
__DEVICE__ float rnorm3df (float __x, float __y, float __z)
Definition at line 452 of file __clang_hip_math.h.
References __x, and __y.
rnorm4d()
__DEVICE__ double rnorm4d (double __x, double __y, double __z, double __w)
Definition at line 1032 of file __clang_hip_math.h.
References __x, and __y.
rnorm4df()
__DEVICE__ float rnorm4df (float __x, float __y, float __z, float __w)
Definition at line 457 of file __clang_hip_math.h.
References __x, and __y.
rnormf()
__DEVICE__ float rnormf (int __dim, const float * __a)
Definition at line 462 of file __clang_hip_math.h.
References __a.
round()
__DEVICE__ double round (double __x)
Definition at line 1037 of file __clang_hip_math.h.
References __a, __nv_round(), and __x.
roundf()
__DEVICE__ float roundf (float __x)
Definition at line 474 of file __clang_hip_math.h.
References __x.
rsqrt()
__DEVICE__ double rsqrt (double __x)
Definition at line 1040 of file __clang_hip_math.h.
References __x.
rsqrtf()
__DEVICE__ float rsqrtf (float __x)
Definition at line 477 of file __clang_hip_math.h.
References __x.
scalbln()
__DEVICE__ double scalbln (double __x, long int __n)
Definition at line 1043 of file __clang_hip_math.h.
References __x, and INT_MAX.
scalblnf()
__DEVICE__ float scalblnf (float __x, long int __n)
Definition at line 480 of file __clang_hip_math.h.
References __x, and INT_MAX.
scalbn()
__DEVICE__ double scalbn (double __x, int __n)
Definition at line 1048 of file __clang_hip_math.h.
References __a, __b, __nv_scalbn(), and __x.
scalbnf()
__DEVICE__ float scalbnf (float __x, int __n)
Definition at line 486 of file __clang_hip_math.h.
References __x.
sin()
__DEVICE__ double sin (double __x)
Definition at line 1054 of file __clang_hip_math.h.
References __a, __nv_sin(), __ocml_sin_f64(), and __x.
sincos()
__DEVICE__ void sincos (double __x, double * __sinptr, double * __cosptr)
Definition at line 1057 of file __clang_hip_math.h.
References __ocml_sincos_f64(), and __x.
sincosf()
__DEVICE__ void sincosf (float __x, float * __sinptr, float * __cosptr)
Definition at line 492 of file __clang_hip_math.h.
References __ocml_sincos_f32(), and __x.
sincospi()
__DEVICE__ void sincospi (double __x, double * __sinptr, double * __cosptr)
Definition at line 1068 of file __clang_hip_math.h.
References __ocml_sincospi_f64(), and __x.
sincospif()
__DEVICE__ void sincospif (float __x, float * __sinptr, float * __cosptr)
Definition at line 503 of file __clang_hip_math.h.
References __ocml_sincospi_f32(), and __x.
sinf()
__DEVICE__ float sinf (float __x)
Definition at line 514 of file __clang_hip_math.h.
References __ocml_sin_f32(), and __x.
sinh()
__DEVICE__ double sinh (double __x)
Definition at line 1079 of file __clang_hip_math.h.
References __a, __nv_sinh(), and __x.
sinhf()
__DEVICE__ float sinhf (float __x)
Definition at line 517 of file __clang_hip_math.h.
References __x.
sinpi()
__DEVICE__ double sinpi (double __x)
Definition at line 1082 of file __clang_hip_math.h.
References __ocml_sinpi_f64(), and __x.
sinpif()
__DEVICE__ float sinpif (float __x)
Definition at line 520 of file __clang_hip_math.h.
References __ocml_sinpi_f32(), and __x.
sqrt()
__DEVICE__ double sqrt (double __x)
Definition at line 1085 of file __clang_hip_math.h.
References __a, __nv_sqrt(), and __x.
sqrtf()
__DEVICE__ float sqrtf (float __x)
Definition at line 523 of file __clang_hip_math.h.
References __x.
tan()
__DEVICE__ double tan (double __x)
Definition at line 1088 of file __clang_hip_math.h.
References __a, __nv_tan(), __ocml_tan_f64(), and __x.
tanf()
__DEVICE__ float tanf (float __x)
Definition at line 526 of file __clang_hip_math.h.
References __ocml_tan_f32(), and __x.
tanh()
__DEVICE__ double tanh (double __x)
Definition at line 1091 of file __clang_hip_math.h.
References __a, __nv_tanh(), and __x.
tanhf()
__DEVICE__ float tanhf (float __x)
Definition at line 529 of file __clang_hip_math.h.
References __x.
tgamma()
__DEVICE__ double tgamma (double __x)
Definition at line 1094 of file __clang_hip_math.h.
References __a, __nv_tgamma(), __ocml_tgamma_f64(), and __x.
tgammaf()
__DEVICE__ float tgammaf (float __x)
Definition at line 532 of file __clang_hip_math.h.
References __ocml_tgamma_f32(), and __x.
trunc()
__DEVICE__ double trunc (double __x)
Definition at line 1097 of file __clang_hip_math.h.
References __a, __nv_trunc(), and __x.
truncf()
__DEVICE__ float truncf (float __x)
Definition at line 535 of file __clang_hip_math.h.
References __x.
y0()
__DEVICE__ double y0 (double __x)
Definition at line 1100 of file __clang_hip_math.h.
References __ocml_y0_f64(), and __x.
Referenced by yn().
y0f()
__DEVICE__ float y0f (float __x)
Definition at line 538 of file __clang_hip_math.h.
References __ocml_y0_f32(), and __x.
Referenced by ynf().
y1()
__DEVICE__ double y1 (double __x)
Definition at line 1103 of file __clang_hip_math.h.
References __ocml_y1_f64(), and __x.
Referenced by yn().
y1f()
__DEVICE__ float y1f (float __x)
Definition at line 541 of file __clang_hip_math.h.
References __ocml_y1_f32(), and __x.
Referenced by ynf().
yn()
__DEVICE__ double yn (int __n, double __x)
Definition at line 1106 of file __clang_hip_math.h.
References __x, y0(), and y1().
ynf()
__DEVICE__ float ynf (int __n, float __x)
Definition at line 544 of file __clang_hip_math.h.
References __x, y0f(), and y1f().