clang: lib/Driver/ToolChains/AIX.cpp File Reference
AIX.cpp File Reference
#include "AIX.h"
#include "Arch/PPC.h"
#include "CommonArgs.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Option/ArgList.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/Path.h"
#include <set>
Typedefs
using AIX = clang::driver::toolchains::AIX
Functions
static bool hasExportListLinkerOpts (const ArgStringList &CmdArgs)
static void addTocDataOptions (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CC1Args, const Driver &D)
Typedef Documentation
AIX
using AIX = clang::driver::toolchains::AIX
Definition at line 22 of file AIX.cpp.
Function Documentation
addTocDataOptions()
static void addTocDataOptions (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CC1Args, const Driver & D) static
Definition at line 469 of file AIX.cpp.
References clang::driver::Driver::Diag().
Referenced by clang::driver::toolchains::AIX::addClangTargetOptions().
hasExportListLinkerOpts()
static bool hasExportListLinkerOpts (const ArgStringList & CmdArgs) static
Definition at line 89 of file AIX.cpp.
Referenced by clang::driver::tools::aix::Linker::ConstructJob().