clang: lib/Analysis/AnalysisDeclContext.cpp File Reference
AnalysisDeclContext.cpp File Reference
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/AST/LambdaCapture.h"
#include "clang/AST/ParentMap.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtCXX.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Analysis/Analyses/CFGReachabilityAnalysis.h"
#include "clang/Analysis/BodyFarm.h"
#include "clang/Analysis/CFG.h"
#include "clang/Analysis/CFGStmtMap.h"
#include "clang/Analysis/Support/BumpVector.h"
#include "clang/Basic/JsonSupport.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <memory>
Typedefs
using ManagedAnalysisMap = llvm::DenseMap< const void *, std::unique_ptr< ManagedAnalysis > >
using DeclVec = BumpVector< const VarDecl * >
Functions
static bool isSelfDecl (const VarDecl *VD)
Returns true if.
static void addParentsForSyntheticStmts (const CFG *TheCFG, ParentMap &PM)
Add each synthetic statement in the CFG to the parent map, using the source statement's parent.
static void printLocation (raw_ostream &Out, const SourceManager &SM, SourceLocation Loc)
static DeclVec * LazyInitializeReferencedDecls (const BlockDecl *BD, void *&Vec, llvm::BumpPtrAllocator &A)
Typedef Documentation
DeclVec
using DeclVec = BumpVector<const VarDecl *>
Definition at line 638 of file AnalysisDeclContext.cpp.
ManagedAnalysisMap
using ManagedAnalysisMap = llvm::DenseMap<const void *, std::unique_ptr<ManagedAnalysis> >
Definition at line 53 of file AnalysisDeclContext.cpp.
Function Documentation
addParentsForSyntheticStmts()
static void addParentsForSyntheticStmts (const CFG * TheCFG, ParentMap & PM) static
Add each synthetic statement in the CFG to the parent map, using the source statement's parent.
Definition at line 202 of file AnalysisDeclContext.cpp.
References clang::ParentMap::getParent(), clang::ParentMap::setParent(), clang::CFG::synthetic_stmt_begin(), and clang::CFG::synthetic_stmt_end().
Referenced by clang::AnalysisDeclContext::getCFG(), clang::AnalysisDeclContext::getParentMap(), and clang::AnalysisDeclContext::getUnoptimizedCFG().
isSelfDecl()
static bool isSelfDecl (const VarDecl * VD) static
Returns true if.
Parameters
VD is an Objective-C implicit 'self' parameter.
Definition at line 144 of file AnalysisDeclContext.cpp.
References clang::NamedDecl::getName().
Referenced by clang::AnalysisDeclContext::getSelfDecl().
LazyInitializeReferencedDecls()
static DeclVec* LazyInitializeReferencedDecls (const BlockDecl * BD, void *& Vec, llvm::BumpPtrAllocator & A) static
Definition at line 640 of file AnalysisDeclContext.cpp.
References clang::BlockDecl::captures(), clang::BlockDecl::getBody(), and clang::BumpVector< T >::push_back().
Referenced by clang::AnalysisDeclContext::getReferencedBlockVars().
printLocation()
static void printLocation (raw_ostream & Out, const SourceManager & SM, SourceLocation Loc) static
Definition at line 489 of file AnalysisDeclContext.cpp.
References clang::SourceLocation::isFileID(), clang::SourceLocation::print(), and SM.