clang: lib/APINotes/APINotesManager.cpp File Reference
APINotesManager.cpp File Reference
#include "clang/APINotes/APINotesManager.h"
#include "clang/APINotes/APINotesReader.h"
#include "clang/APINotes/APINotesYAMLCompiler.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/SourceMgrAdapter.h"
#include "clang/Basic/Version.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/PrettyStackTrace.h"
Macros
#define DEBUG_TYPE "API Notes"
Functions
STATISTIC (NumHeaderAPINotes, "non-framework API notes files loaded")
STATISTIC (NumPublicFrameworkAPINotes, "framework public API notes loaded")
STATISTIC (NumPrivateFrameworkAPINotes, "framework private API notes loaded")
STATISTIC (NumFrameworksSearched, "frameworks searched")
STATISTIC (NumDirectoriesSearched, "header directories searched")
STATISTIC (NumDirectoryCacheHits, "directory cache hits")
static void checkPrivateAPINotesName (DiagnosticsEngine &Diags, const FileEntry *File, const Module *M)
static bool hasPrivateSubmodules (const Module *M)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "API Notes"
Definition at line 31 of file APINotesManager.cpp.
Function Documentation
checkPrivateAPINotesName()
static void checkPrivateAPINotesName (DiagnosticsEngine & Diags, const FileEntry * File, const Module * M) static
Definition at line 193 of file APINotesManager.cpp.
References clang::File, clang::Module::IsSystem, clang::Module::Name, and clang::DiagnosticsEngine::Report().
Referenced by clang::api_notes::APINotesManager::getCurrentModuleAPINotes().
hasPrivateSubmodules()
static bool hasPrivateSubmodules (const Module * M) static
Returns
true if any of module's immediate submodules are defined in a private module map
Definition at line 213 of file APINotesManager.cpp.
References clang::Module::submodules().
Referenced by clang::api_notes::APINotesManager::getCurrentModuleAPINotes().
STATISTIC() [1/6]
STATISTIC (NumDirectoriesSearched , "header directories searched")
STATISTIC() [2/6]
STATISTIC (NumDirectoryCacheHits , "directory cache hits")
References clang::First.
STATISTIC() [3/6]
STATISTIC (NumFrameworksSearched , "frameworks searched")
STATISTIC() [4/6]
STATISTIC (NumHeaderAPINotes , "non-framework API notes files loaded")
STATISTIC() [5/6]
STATISTIC (NumPrivateFrameworkAPINotes , "framework private API notes loaded")
STATISTIC() [6/6]
STATISTIC (NumPublicFrameworkAPINotes , "framework public API notes loaded")