clang: lib/StaticAnalyzer/Checkers/ArrayBoundCheckerV2.cpp File Reference
ArrayBoundCheckerV2.cpp File Reference
#include "clang/AST/CharUnits.h"
#include "clang/AST/ParentMapContext.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Checkers/Taint.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/APSIntType.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicExtent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
Functions
static std::optional< std::pair< const SubRegion *, NonLoc > > computeOffset (ProgramStateRef State, SValBuilder &SVB, SVal Location)
For a given Location that can be represented as a symbolic expression ArrIdx, return the parent memory block Arr and the distance of Location from the beginning of Arr (expressed in a NonLoc that specifies the number of CharUnits).
static std::pair< NonLoc, nonloc::ConcreteInt > getSimplifiedOffsets (NonLoc offset, nonloc::ConcreteInt extent, SValBuilder &svalBuilder)
static bool isNegative (SValBuilder &SVB, ProgramStateRef State, NonLoc Value)
static bool isUnsigned (SValBuilder &SVB, NonLoc Value)
static std::pair< ProgramStateRef, ProgramStateRef > compareValueToThreshold (ProgramStateRef State, NonLoc Value, NonLoc Threshold, SValBuilder &SVB, bool CheckEquality=false)
static std::string getRegionName (const SubRegion *Region)
static std::optional< int64_t > getConcreteValue (NonLoc SV)
static std::optional< int64_t > getConcreteValue (std::optional< NonLoc > SV)
static Messages getPrecedesMsgs (const SubRegion *Region, NonLoc Offset)
static bool tryDividePair (std::optional< int64_t > &Val1, std::optional< int64_t > &Val2, int64_t Divisor)
Try to divide Val1 and Val2 (in place) by Divisor and return true if it can be performed (Divisor is nonzero and there is no remainder).
static Messages getExceedsMsgs (ASTContext &ACtx, const SubRegion *Region, NonLoc Offset, NonLoc Extent, SVal Location, bool AlsoMentionUnderflow)
static Messages getTaintMsgs (const SubRegion *Region, const char *OffsetName, bool AlsoMentionUnderflow)
Function Documentation
compareValueToThreshold()
static std::pair<ProgramStateRef, ProgramStateRef> compareValueToThreshold (ProgramStateRef State, NonLoc Value, NonLoc Threshold, SValBuilder & SVB, bool CheckEquality = false) static
Definition at line 291 of file ArrayBoundCheckerV2.cpp.
References clang::ento::SValBuilder::evalBinOpNN(), clang::ento::SVal::getAs(), clang::ento::SValBuilder::getConditionType(), getSimplifiedOffsets(), isNegative(), isUnsigned(), and State.
computeOffset()
static std::optional<std::pair<const SubRegion *, NonLoc> > computeOffset (ProgramStateRef State, SValBuilder & SVB, SVal Location) static
For a given Location that can be represented as a symbolic expression ArrIdx, return the parent memory block Arr and the distance of Location from the beginning of Arr (expressed in a NonLoc that specifies the number of CharUnits).
Returns nullopt when these cannot be determined.
Definition at line 171 of file ArrayBoundCheckerV2.cpp.
References clang::ento::SValBuilder::evalBinOpNN(), clang::ento::SValBuilder::getArrayIndexType(), clang::ento::SVal::getAs(), clang::ento::SVal::getAsRegion(), clang::ento::SValBuilder::makeZeroArrayIndex(), Offset, State, and clang::T.
getConcreteValue() [1/2]
static std::optional<int64_t> getConcreteValue (NonLoc SV) static
Definition at line 364 of file ArrayBoundCheckerV2.cpp.
References clang::ento::SVal::getAs().
Referenced by getConcreteValue(), and getExceedsMsgs().
getConcreteValue() [2/2]
static std::optional<int64_t> getConcreteValue (std::optional< NonLoc > SV) static
Definition at line 371 of file ArrayBoundCheckerV2.cpp.
References getConcreteValue().
getExceedsMsgs()
static Messages getExceedsMsgs (ASTContext & ACtx, const SubRegion * Region, NonLoc Offset, NonLoc Extent, SVal Location, bool AlsoMentionUnderflow) static
Definition at line 406 of file ArrayBoundCheckerV2.cpp.
References clang::ento::MemRegion::getAs(), clang::ento::SVal::getAsRegion(), clang::QualType::getAsString(), getConcreteValue(), clang::CharUnits::getQuantity(), getRegionName(), clang::ASTContext::getTypeSizeInChars(), Offset, and tryDividePair().
getPrecedesMsgs()
static Messages getPrecedesMsgs (const SubRegion * Region, NonLoc Offset) static
Definition at line 375 of file ArrayBoundCheckerV2.cpp.
References getRegionName(), and Offset.
getRegionName()
static std::string getRegionName (const SubRegion * Region) static
Definition at line 339 of file ArrayBoundCheckerV2.cpp.
References clang::ento::MemRegion::getAs(), and clang::ento::MemRegion::getDescriptiveName().
Referenced by getExceedsMsgs(), getPrecedesMsgs(), and getTaintMsgs().
getSimplifiedOffsets()
static std::pair<NonLoc, nonloc::ConcreteInt> getSimplifiedOffsets (NonLoc offset, nonloc::ConcreteInt extent, SValBuilder & svalBuilder) static
Definition at line 242 of file ArrayBoundCheckerV2.cpp.
References clang::ento::APSIntType::convert(), clang::ento::SVal::getAs(), clang::ento::nonloc::ConcreteInt::getValue(), and clang::ento::SValBuilder::makeIntVal().
Referenced by compareValueToThreshold().
getTaintMsgs()
static Messages getTaintMsgs (const SubRegion * Region, const char * OffsetName, bool AlsoMentionUnderflow) static
Definition at line 456 of file ArrayBoundCheckerV2.cpp.
References getRegionName().
isNegative()
static bool isNegative (SValBuilder & SVB, ProgramStateRef State, NonLoc Value) static
Definition at line 273 of file ArrayBoundCheckerV2.cpp.
References clang::ento::SValBuilder::getMaxValue(), and State.
Referenced by compareValueToThreshold().
isUnsigned()
static bool isUnsigned (SValBuilder & SVB, NonLoc Value) static
Definition at line 278 of file ArrayBoundCheckerV2.cpp.
References clang::ento::SValBuilder::getContext(), clang::Value::getType(), clang::Type::isUnsignedIntegerType(), and clang::T.
Referenced by CheckC23ConstexprInitStringLiteral(), compareValueToThreshold(), clang::ento::BasicValueFactory::getIntValue(), clang::ento::BasicValueFactory::getValue(), clang::DependentBitIntType::isSigned(), clang::ento::SValBuilder::makeIntVal(), clang::ASTContext::mergeTypes(), clang::BitIntType::Profile(), and clang::serialization::DataStreamBasicReader< Impl >::readAPSInt().
tryDividePair()
static bool tryDividePair (std::optional< int64_t > & Val1, std::optional< int64_t > & Val2, int64_t Divisor) static
Try to divide Val1 and Val2 (in place) by Divisor and return true if it can be performed (Divisor is nonzero and there is no remainder).
The values Val1 and Val2 may be nullopt and in that case the corresponding division is considered to be successful.
Definition at line 390 of file ArrayBoundCheckerV2.cpp.
Referenced by getExceedsMsgs().