clang: lib/Serialization/ASTWriterStmt.cpp File Reference
ASTWriterStmt.cpp File Reference
#include "clang/AST/ExprOpenMP.h"
#include "clang/Serialization/ASTRecordWriter.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Lex/Token.h"
#include "llvm/Bitstream/BitstreamWriter.h"
#include "clang/AST/StmtNodes.inc"
Classes
class clang::ASTStmtWriter
Namespaces
clang
Macros
#define STMT(Type, Base) void Visit##Type(Type *);
Functions
static void addConstraintSatisfaction (ASTRecordWriter &Record, const ASTConstraintSatisfaction &Satisfaction)
static void addSubstitutionDiagnostic (ASTRecordWriter &Record, const concepts::Requirement::SubstitutionDiagnostic *D)
Detailed Description
Implements serialization for Statements and Expressions.
Definition in file ASTWriterStmt.cpp.
Macro Definition Documentation
STMT
#define STMT (Type, Base) void Visit##Type(Type *);
Definition at line 56 of file ASTWriterStmt.cpp.
Function Documentation
addConstraintSatisfaction()
static void addConstraintSatisfaction (ASTRecordWriter & Record, const ASTConstraintSatisfaction & Satisfaction) static
Definition at line 399 of file ASTWriterStmt.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddStmt(), clang::ASTRecordWriter::AddString(), Diag(), clang::ASTConstraintSatisfaction::IsSatisfied, clang::ASTConstraintSatisfaction::NumRecords, and clang::ASTRecordWriter::push_back().
addSubstitutionDiagnostic()
static void addSubstitutionDiagnostic (ASTRecordWriter & Record, const concepts::Requirement::SubstitutionDiagnostic * D) static
Definition at line 421 of file ASTWriterStmt.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddString(), clang::concepts::Requirement::SubstitutionDiagnostic::DiagLoc, clang::concepts::Requirement::SubstitutionDiagnostic::DiagMessage, and clang::concepts::Requirement::SubstitutionDiagnostic::SubstitutedEntity.