clang: lib/Headers/avx512fp16intrin.h File Reference
avx512fp16intrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS512
#define __DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS128
#define _mm512_setr_ph(h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14, h15, h16, h17, h18, h19, h20, h21, h22, h23, h24, h25, h26, h27, h28, h29, h30, h31, h32)
#define _mm_comi_round_sh(A, B, P, R) __builtin_ia32_vcomish((__v8hf)A, (__v8hf)B, (int)(P), (int)(R))
#define _mm_comi_sh(A, B, pred) _mm_comi_round_sh((A), (B), (pred), _MM_FROUND_CUR_DIRECTION)
#define _mm512_add_round_ph(A, B, R)
#define _mm512_mask_add_round_ph(W, U, A, B, R)
#define _mm512_maskz_add_round_ph(U, A, B, R)
#define _mm512_sub_round_ph(A, B, R)
#define _mm512_mask_sub_round_ph(W, U, A, B, R)
#define _mm512_maskz_sub_round_ph(U, A, B, R)
#define _mm512_mul_round_ph(A, B, R)
#define _mm512_mask_mul_round_ph(W, U, A, B, R)
#define _mm512_maskz_mul_round_ph(U, A, B, R)
#define _mm512_div_round_ph(A, B, R)
#define _mm512_mask_div_round_ph(W, U, A, B, R)
#define _mm512_maskz_div_round_ph(U, A, B, R)
#define _mm512_min_round_ph(A, B, R)
#define _mm512_mask_min_round_ph(W, U, A, B, R)
#define _mm512_maskz_min_round_ph(U, A, B, R)
#define _mm512_max_round_ph(A, B, R)
#define _mm512_mask_max_round_ph(W, U, A, B, R)
#define _mm512_maskz_max_round_ph(U, A, B, R)
#define _mm_add_round_sh(A, B, R)
#define _mm_mask_add_round_sh(W, U, A, B, R)
#define _mm_maskz_add_round_sh(U, A, B, R)
#define _mm_sub_round_sh(A, B, R)
#define _mm_mask_sub_round_sh(W, U, A, B, R)
#define _mm_maskz_sub_round_sh(U, A, B, R)
#define _mm_mul_round_sh(A, B, R)
#define _mm_mask_mul_round_sh(W, U, A, B, R)
#define _mm_maskz_mul_round_sh(U, A, B, R)
#define _mm_div_round_sh(A, B, R)
#define _mm_mask_div_round_sh(W, U, A, B, R)
#define _mm_maskz_div_round_sh(U, A, B, R)
#define _mm_min_round_sh(A, B, R)
#define _mm_mask_min_round_sh(W, U, A, B, R)
#define _mm_maskz_min_round_sh(U, A, B, R)
#define _mm_max_round_sh(A, B, R)
#define _mm_mask_max_round_sh(W, U, A, B, R)
#define _mm_maskz_max_round_sh(U, A, B, R)
#define _mm512_cmp_round_ph_mask(A, B, P, R)
#define _mm512_mask_cmp_round_ph_mask(U, A, B, P, R)
#define _mm512_cmp_ph_mask(A, B, P) _mm512_cmp_round_ph_mask((A), (B), (P), _MM_FROUND_CUR_DIRECTION)
#define _mm512_mask_cmp_ph_mask(U, A, B, P) _mm512_mask_cmp_round_ph_mask((U), (A), (B), (P), _MM_FROUND_CUR_DIRECTION)
#define _mm_cmp_round_sh_mask(X, Y, P, R)
#define _mm_mask_cmp_round_sh_mask(M, X, Y, P, R)
#define _mm_cmp_sh_mask(X, Y, P)
#define _mm_mask_cmp_sh_mask(M, X, Y, P)
#define _mm512_getmant_ph(A, B, C)
#define _mm512_mask_getmant_ph(W, U, A, B, C)
#define _mm512_maskz_getmant_ph(U, A, B, C)
#define _mm512_getmant_round_ph(A, B, C, R)
#define _mm512_mask_getmant_round_ph(W, U, A, B, C, R)
#define _mm512_maskz_getmant_round_ph(U, A, B, C, R)
#define _mm512_getexp_round_ph(A, R)
#define _mm512_mask_getexp_round_ph(W, U, A, R)
#define _mm512_maskz_getexp_round_ph(U, A, R)
#define _mm512_scalef_round_ph(A, B, R)
#define _mm512_mask_scalef_round_ph(W, U, A, B, R)
#define _mm512_maskz_scalef_round_ph(U, A, B, R)
#define _mm512_roundscale_ph(A, B)
#define _mm512_mask_roundscale_ph(A, B, C, imm)
#define _mm512_maskz_roundscale_ph(A, B, imm)
#define _mm512_mask_roundscale_round_ph(A, B, C, imm, R)
#define _mm512_maskz_roundscale_round_ph(A, B, imm, R)
#define _mm512_roundscale_round_ph(A, imm, R)
#define _mm512_reduce_ph(A, imm)
#define _mm512_mask_reduce_ph(W, U, A, imm)
#define _mm512_maskz_reduce_ph(U, A, imm)
#define _mm512_mask_reduce_round_ph(W, U, A, imm, R)
#define _mm512_maskz_reduce_round_ph(U, A, imm, R)
#define _mm512_reduce_round_ph(A, imm, R)
#define _mm_getmant_round_sh(A, B, C, D, R)
#define _mm_getmant_sh(A, B, C, D)
#define _mm_mask_getmant_sh(W, U, A, B, C, D)
#define _mm_mask_getmant_round_sh(W, U, A, B, C, D, R)
#define _mm_maskz_getmant_sh(U, A, B, C, D)
#define _mm_maskz_getmant_round_sh(U, A, B, C, D, R)
#define _mm_getexp_round_sh(A, B, R)
#define _mm_mask_getexp_round_sh(W, U, A, B, R)
#define _mm_maskz_getexp_round_sh(U, A, B, R)
#define _mm_scalef_round_sh(A, B, R)
#define _mm_mask_scalef_round_sh(W, U, A, B, R)
#define _mm_maskz_scalef_round_sh(U, A, B, R)
#define _mm_roundscale_round_sh(A, B, imm, R)
#define _mm_roundscale_sh(A, B, imm)
#define _mm_mask_roundscale_sh(W, U, A, B, I)
#define _mm_mask_roundscale_round_sh(W, U, A, B, I, R)
#define _mm_maskz_roundscale_sh(U, A, B, I)
#define _mm_maskz_roundscale_round_sh(U, A, B, I, R)
#define _mm_reduce_sh(A, B, C)
#define _mm_mask_reduce_sh(W, U, A, B, C)
#define _mm_maskz_reduce_sh(U, A, B, C)
#define _mm_reduce_round_sh(A, B, C, R)
#define _mm_mask_reduce_round_sh(W, U, A, B, C, R)
#define _mm_maskz_reduce_round_sh(U, A, B, C, R)
#define _mm512_sqrt_round_ph(A, R) ((__m512h)__builtin_ia32_sqrtph512((__v32hf)(__m512h)(A), (int)(R)))
#define _mm512_mask_sqrt_round_ph(W, U, A, R)
#define _mm512_maskz_sqrt_round_ph(U, A, R)
#define _mm_sqrt_round_sh(A, B, R)
#define _mm_mask_sqrt_round_sh(W, U, A, B, R)
#define _mm_maskz_sqrt_round_sh(U, A, B, R)
#define _mm512_mask_fpclass_ph_mask(U, A, imm)
#define _mm512_fpclass_ph_mask(A, imm)
#define _mm_fpclass_sh_mask(A, imm)
#define _mm_mask_fpclass_sh_mask(U, A, imm)
#define _mm512_cvt_roundpd_ph(A, R)
#define _mm512_mask_cvt_roundpd_ph(W, U, A, R)
#define _mm512_maskz_cvt_roundpd_ph(U, A, R)
#define _mm512_cvt_roundph_pd(A, R)
#define _mm512_mask_cvt_roundph_pd(W, U, A, R)
#define _mm512_maskz_cvt_roundph_pd(U, A, R)
#define _mm_cvt_roundsh_ss(A, B, R)
#define _mm_mask_cvt_roundsh_ss(W, U, A, B, R)
#define _mm_maskz_cvt_roundsh_ss(U, A, B, R)
#define _mm_cvt_roundss_sh(A, B, R)
#define _mm_mask_cvt_roundss_sh(W, U, A, B, R)
#define _mm_maskz_cvt_roundss_sh(U, A, B, R)
#define _mm_cvt_roundsd_sh(A, B, R)
#define _mm_mask_cvt_roundsd_sh(W, U, A, B, R)
#define _mm_maskz_cvt_roundsd_sh(U, A, B, R)
#define _mm_cvt_roundsh_sd(A, B, R)
#define _mm_mask_cvt_roundsh_sd(W, U, A, B, R)
#define _mm_maskz_cvt_roundsh_sd(U, A, B, R)
#define _mm512_cvt_roundph_epi16(A, R)
#define _mm512_mask_cvt_roundph_epi16(W, U, A, R)
#define _mm512_maskz_cvt_roundph_epi16(U, A, R)
#define _mm512_cvtt_roundph_epi16(A, R)
#define _mm512_mask_cvtt_roundph_epi16(W, U, A, R)
#define _mm512_maskz_cvtt_roundph_epi16(U, A, R)
#define _mm512_cvt_roundepi16_ph(A, R)
#define _mm512_mask_cvt_roundepi16_ph(W, U, A, R)
#define _mm512_maskz_cvt_roundepi16_ph(U, A, R)
#define _mm512_cvt_roundph_epu16(A, R)
#define _mm512_mask_cvt_roundph_epu16(W, U, A, R)
#define _mm512_maskz_cvt_roundph_epu16(U, A, R)
#define _mm512_cvtt_roundph_epu16(A, R)
#define _mm512_mask_cvtt_roundph_epu16(W, U, A, R)
#define _mm512_maskz_cvtt_roundph_epu16(U, A, R)
#define _mm512_cvt_roundepu16_ph(A, R)
#define _mm512_mask_cvt_roundepu16_ph(W, U, A, R)
#define _mm512_maskz_cvt_roundepu16_ph(U, A, R)
#define _mm512_cvt_roundph_epi32(A, R)
#define _mm512_mask_cvt_roundph_epi32(W, U, A, R)
#define _mm512_maskz_cvt_roundph_epi32(U, A, R)
#define _mm512_cvt_roundph_epu32(A, R)
#define _mm512_mask_cvt_roundph_epu32(W, U, A, R)
#define _mm512_maskz_cvt_roundph_epu32(U, A, R)
#define _mm512_cvt_roundepi32_ph(A, R)
#define _mm512_mask_cvt_roundepi32_ph(W, U, A, R)
#define _mm512_maskz_cvt_roundepi32_ph(U, A, R)
#define _mm512_cvt_roundepu32_ph(A, R)
#define _mm512_mask_cvt_roundepu32_ph(W, U, A, R)
#define _mm512_maskz_cvt_roundepu32_ph(U, A, R)
#define _mm512_cvtt_roundph_epi32(A, R)
#define _mm512_mask_cvtt_roundph_epi32(W, U, A, R)
#define _mm512_maskz_cvtt_roundph_epi32(U, A, R)
#define _mm512_cvtt_roundph_epu32(A, R)
#define _mm512_mask_cvtt_roundph_epu32(W, U, A, R)
#define _mm512_maskz_cvtt_roundph_epu32(U, A, R)
#define _mm512_cvt_roundepi64_ph(A, R)
#define _mm512_mask_cvt_roundepi64_ph(W, U, A, R)
#define _mm512_maskz_cvt_roundepi64_ph(U, A, R)
#define _mm512_cvt_roundph_epi64(A, R)
#define _mm512_mask_cvt_roundph_epi64(W, U, A, R)
#define _mm512_maskz_cvt_roundph_epi64(U, A, R)
#define _mm512_cvt_roundepu64_ph(A, R)
#define _mm512_mask_cvt_roundepu64_ph(W, U, A, R)
#define _mm512_maskz_cvt_roundepu64_ph(U, A, R)
#define _mm512_cvt_roundph_epu64(A, R)
#define _mm512_mask_cvt_roundph_epu64(W, U, A, R)
#define _mm512_maskz_cvt_roundph_epu64(U, A, R)
#define _mm512_cvtt_roundph_epi64(A, R)
#define _mm512_mask_cvtt_roundph_epi64(W, U, A, R)
#define _mm512_maskz_cvtt_roundph_epi64(U, A, R)
#define _mm512_cvtt_roundph_epu64(A, R)
#define _mm512_mask_cvtt_roundph_epu64(W, U, A, R)
#define _mm512_maskz_cvtt_roundph_epu64(U, A, R)
#define _mm_cvt_roundsh_i32(A, R) ((int)__builtin_ia32_vcvtsh2si32((__v8hf)(A), (int)(R)))
#define _mm_cvt_roundsh_u32(A, R) ((unsigned int)__builtin_ia32_vcvtsh2usi32((__v8hf)(A), (int)(R)))
#define _mm_cvt_roundu32_sh(A, B, R) ((__m128h)__builtin_ia32_vcvtusi2sh((__v8hf)(A), (unsigned int)(B), (int)(R)))
#define _mm_cvt_roundi32_sh(A, B, R) ((__m128h)__builtin_ia32_vcvtsi2sh((__v8hf)(A), (int)(B), (int)(R)))
#define _mm_cvtt_roundsh_i32(A, R) ((int)__builtin_ia32_vcvttsh2si32((__v8hf)(A), (int)(R)))
#define _mm_cvtt_roundsh_u32(A, R) ((unsigned int)__builtin_ia32_vcvttsh2usi32((__v8hf)(A), (int)(R)))
#define _mm512_cvtx_roundph_ps(A, R)
#define _mm512_mask_cvtx_roundph_ps(W, U, A, R)
#define _mm512_maskz_cvtx_roundph_ps(U, A, R)
#define _mm512_cvtx_roundps_ph(A, R)
#define _mm512_mask_cvtx_roundps_ph(W, U, A, R)
#define _mm512_maskz_cvtx_roundps_ph(U, A, R)
#define _mm512_fmadd_round_ph(A, B, C, R)
#define _mm512_mask_fmadd_round_ph(A, U, B, C, R)
#define _mm512_mask3_fmadd_round_ph(A, B, C, U, R)
#define _mm512_maskz_fmadd_round_ph(U, A, B, C, R)
#define _mm512_fmsub_round_ph(A, B, C, R)
#define _mm512_mask_fmsub_round_ph(A, U, B, C, R)
#define _mm512_maskz_fmsub_round_ph(U, A, B, C, R)
#define _mm512_fnmadd_round_ph(A, B, C, R)
#define _mm512_mask3_fnmadd_round_ph(A, B, C, U, R)
#define _mm512_maskz_fnmadd_round_ph(U, A, B, C, R)
#define _mm512_fnmsub_round_ph(A, B, C, R)
#define _mm512_maskz_fnmsub_round_ph(U, A, B, C, R)
#define _mm512_fmaddsub_round_ph(A, B, C, R)
#define _mm512_mask_fmaddsub_round_ph(A, U, B, C, R)
#define _mm512_mask3_fmaddsub_round_ph(A, B, C, U, R)
#define _mm512_maskz_fmaddsub_round_ph(U, A, B, C, R)
#define _mm512_fmsubadd_round_ph(A, B, C, R)
#define _mm512_mask_fmsubadd_round_ph(A, U, B, C, R)
#define _mm512_maskz_fmsubadd_round_ph(U, A, B, C, R)
#define _mm512_mask3_fmsub_round_ph(A, B, C, U, R)
#define _mm512_mask3_fmsubadd_round_ph(A, B, C, U, R)
#define _mm512_mask_fnmadd_round_ph(A, U, B, C, R)
#define _mm512_mask_fnmsub_round_ph(A, U, B, C, R)
#define _mm512_mask3_fnmsub_round_ph(A, B, C, U, R)
#define _mm_fmadd_round_sh(A, B, C, R)
#define _mm_mask_fmadd_round_sh(W, U, A, B, R)
#define _mm_maskz_fmadd_round_sh(U, A, B, C, R)
#define _mm_mask3_fmadd_round_sh(W, X, Y, U, R)
#define _mm_fmsub_round_sh(A, B, C, R)
#define _mm_mask_fmsub_round_sh(W, U, A, B, R)
#define _mm_maskz_fmsub_round_sh(U, A, B, C, R)
#define _mm_mask3_fmsub_round_sh(W, X, Y, U, R)
#define _mm_fnmadd_round_sh(A, B, C, R)
#define _mm_mask_fnmadd_round_sh(W, U, A, B, R)
#define _mm_maskz_fnmadd_round_sh(U, A, B, C, R)
#define _mm_mask3_fnmadd_round_sh(W, X, Y, U, R)
#define _mm_fnmsub_round_sh(A, B, C, R)
#define _mm_mask_fnmsub_round_sh(W, U, A, B, R)
#define _mm_maskz_fnmsub_round_sh(U, A, B, C, R)
#define _mm_mask3_fnmsub_round_sh(W, X, Y, U, R)
#define _mm_fcmadd_round_sch(A, B, C, R)
#define _mm_mask_fcmadd_round_sch(A, U, B, C, R)
#define _mm_maskz_fcmadd_round_sch(U, A, B, C, R)
#define _mm_mask3_fcmadd_round_sch(A, B, C, U, R)
#define _mm_fmadd_round_sch(A, B, C, R)
#define _mm_mask_fmadd_round_sch(A, U, B, C, R)
#define _mm_maskz_fmadd_round_sch(U, A, B, C, R)
#define _mm_mask3_fmadd_round_sch(A, B, C, U, R)
#define _mm_fcmul_round_sch(A, B, R)
#define _mm_mask_fcmul_round_sch(W, U, A, B, R)
#define _mm_maskz_fcmul_round_sch(U, A, B, R)
#define _mm_fmul_round_sch(A, B, R)
#define _mm_mask_fmul_round_sch(W, U, A, B, R)
#define _mm_maskz_fmul_round_sch(U, A, B, R)
#define _mm512_fcmul_round_pch(A, B, R)
#define _mm512_mask_fcmul_round_pch(W, U, A, B, R)
#define _mm512_maskz_fcmul_round_pch(U, A, B, R)
#define _mm512_fmul_round_pch(A, B, R)
#define _mm512_mask_fmul_round_pch(W, U, A, B, R)
#define _mm512_maskz_fmul_round_pch(U, A, B, R)
#define _mm512_fcmadd_round_pch(A, B, C, R)
#define _mm512_mask_fcmadd_round_pch(A, U, B, C, R)
#define _mm512_mask3_fcmadd_round_pch(A, B, C, U, R)
#define _mm512_maskz_fcmadd_round_pch(U, A, B, C, R)
#define _mm512_fmadd_round_pch(A, B, C, R)
#define _mm512_mask_fmadd_round_pch(A, U, B, C, R)
#define _mm512_mask3_fmadd_round_pch(A, B, C, U, R)
#define _mm512_maskz_fmadd_round_pch(U, A, B, C, R)
#define _mm512_mul_pch(A, B) _mm512_fmul_pch(A, B)
#define _mm512_mask_mul_pch(W, U, A, B) _mm512_mask_fmul_pch(W, U, A, B)
#define _mm512_maskz_mul_pch(U, A, B) _mm512_maskz_fmul_pch(U, A, B)
#define _mm512_mul_round_pch(A, B, R) _mm512_fmul_round_pch(A, B, R)
#define _mm512_mask_mul_round_pch(W, U, A, B, R) _mm512_mask_fmul_round_pch(W, U, A, B, R)
#define _mm512_maskz_mul_round_pch(U, A, B, R) _mm512_maskz_fmul_round_pch(U, A, B, R)
#define _mm512_cmul_pch(A, B) _mm512_fcmul_pch(A, B)
#define _mm512_mask_cmul_pch(W, U, A, B) _mm512_mask_fcmul_pch(W, U, A, B)
#define _mm512_maskz_cmul_pch(U, A, B) _mm512_maskz_fcmul_pch(U, A, B)
#define _mm512_cmul_round_pch(A, B, R) _mm512_fcmul_round_pch(A, B, R)
#define _mm512_mask_cmul_round_pch(W, U, A, B, R) _mm512_mask_fcmul_round_pch(W, U, A, B, R)
#define _mm512_maskz_cmul_round_pch(U, A, B, R) _mm512_maskz_fcmul_round_pch(U, A, B, R)
#define _mm_mul_sch(A, B) _mm_fmul_sch(A, B)
#define _mm_mask_mul_sch(W, U, A, B) _mm_mask_fmul_sch(W, U, A, B)
#define _mm_maskz_mul_sch(U, A, B) _mm_maskz_fmul_sch(U, A, B)
#define _mm_mul_round_sch(A, B, R) _mm_fmul_round_sch(A, B, R)
#define _mm_mask_mul_round_sch(W, U, A, B, R) _mm_mask_fmul_round_sch(W, U, A, B, R)
#define _mm_maskz_mul_round_sch(U, A, B, R) _mm_maskz_fmul_round_sch(U, A, B, R)
#define _mm_cmul_sch(A, B) _mm_fcmul_sch(A, B)
#define _mm_mask_cmul_sch(W, U, A, B) _mm_mask_fcmul_sch(W, U, A, B)
#define _mm_maskz_cmul_sch(U, A, B) _mm_maskz_fcmul_sch(U, A, B)
#define _mm_cmul_round_sch(A, B, R) _mm_fcmul_round_sch(A, B, R)
#define _mm_mask_cmul_round_sch(W, U, A, B, R) _mm_mask_fcmul_round_sch(W, U, A, B, R)
#define _mm_maskz_cmul_round_sch(U, A, B, R) _mm_maskz_fcmul_round_sch(U, A, B, R)
Typedefs
typedef _Float16 __v32hf __attribute__((__vector_size__(64), __aligned__(64)))
Functions
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_cvtsh_h (__m512h __a)
static __inline __m128h __DEFAULT_FN_ATTRS128 _mm_setzero_ph (void)
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_setzero_ph (void)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_undefined_ph (void)
static __inline __m512h __DEFAULT_FN_ATTRS512 _mm512_setzero_ph (void)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_undefined_ph (void)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_undefined_ph (void)
static __inline __m512h __DEFAULT_FN_ATTRS512 _mm512_set1_ph (_Float16 __h)
static __inline __m512h __DEFAULT_FN_ATTRS512 _mm512_set_ph (_Float16 __h1, _Float16 __h2, _Float16 __h3, _Float16 __h4, _Float16 __h5, _Float16 __h6, _Float16 __h7, _Float16 __h8, _Float16 __h9, _Float16 __h10, _Float16 __h11, _Float16 __h12, _Float16 __h13, _Float16 __h14, _Float16 __h15, _Float16 __h16, _Float16 __h17, _Float16 __h18, _Float16 __h19, _Float16 __h20, _Float16 __h21, _Float16 __h22, _Float16 __h23, _Float16 __h24, _Float16 __h25, _Float16 __h26, _Float16 __h27, _Float16 __h28, _Float16 __h29, _Float16 __h30, _Float16 __h31, _Float16 __h32)
static __inline __m512h __DEFAULT_FN_ATTRS512 _mm512_set1_pch (_Float16 _Complex h)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_castph_ps (__m128h __a)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_castph_ps (__m256h __a)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_castph_ps (__m512h __a)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_castph_pd (__m128h __a)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_castph_pd (__m256h __a)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_castph_pd (__m512h __a)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_castph_si128 (__m128h __a)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_castph_si256 (__m256h __a)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_castph_si512 (__m512h __a)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_castps_ph (__m128 __a)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_castps_ph (__m256 __a)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castps_ph (__m512 __a)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_castpd_ph (__m128d __a)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_castpd_ph (__m256d __a)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castpd_ph (__m512d __a)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_castsi128_ph (__m128i __a)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_castsi256_ph (__m256i __a)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castsi512_ph (__m512i __a)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_castph256_ph128 (__m256h __a)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_castph512_ph128 (__m512h __a)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_castph512_ph256 (__m512h __a)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_castph128_ph256 (__m128h __a)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castph128_ph512 (__m128h __a)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castph256_ph512 (__m256h __a)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_zextph128_ph256 (__m128h __a)
Constructs a 256-bit floating-point vector of [16 x half] from a 128-bit floating-point vector of [8 x half].
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_zextph128_ph512 (__m128h __a)
Constructs a 512-bit floating-point vector of [32 x half] from a 128-bit floating-point vector of [8 x half].
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_zextph256_ph512 (__m256h __a)
Constructs a 512-bit floating-point vector of [32 x half] from a 256-bit floating-point vector of [16 x half].
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comieq_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comilt_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comile_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comigt_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comige_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comineq_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomieq_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomilt_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomile_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomigt_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomige_sh (__m128h A, __m128h B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomineq_sh (__m128h A, __m128h B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_add_ph (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_add_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_add_ph (__mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_sub_ph (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_sub_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_sub_ph (__mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mul_ph (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_mul_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_mul_ph (__mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_div_ph (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_div_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_div_ph (__mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_min_ph (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_min_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_min_ph (__mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_max_ph (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_max_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_max_ph (__mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_abs_ph (__m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_conj_pch (__m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_conj_pch (__m512h __W, __mmask16 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_conj_pch (__mmask16 __U, __m512h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_add_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_add_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_add_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_sub_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_sub_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_sub_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mul_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_mul_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_mul_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_div_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_div_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_div_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_min_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_min_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_min_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_max_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_max_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_max_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_load_sh (void const *__dp)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_load_sh (__m128h __W, __mmask8 __U, const void *__A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_load_sh (__mmask8 __U, const void *__A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_load_ph (void const *__p)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_load_ph (void const *__p)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_load_ph (void const *__p)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_loadu_ph (void const *__p)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_loadu_ph (void const *__p)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_loadu_ph (void const *__p)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_store_sh (void *__dp, __m128h __a)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_store_sh (void *__W, __mmask8 __U, __m128h __A)
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_store_ph (void *__P, __m512h __A)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_store_ph (void *__P, __m256h __A)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_store_ph (void *__P, __m128h __A)
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_storeu_ph (void *__P, __m512h __A)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_storeu_ph (void *__P, __m256h __A)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_storeu_ph (void *__P, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_move_sh (__m128h __a, __m128h __b)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_move_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_move_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtsi16_si128 (short __a)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_cvtsi128_si16 (__m128i __a)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_rcp_ph (__m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_rcp_ph (__m512h __W, __mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_rcp_ph (__mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_rsqrt_ph (__m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_rsqrt_ph (__m512h __W, __mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_rsqrt_ph (__mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_getexp_ph (__m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_getexp_ph (__m512h __W, __mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_getexp_ph (__mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_scalef_ph (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_scalef_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_scalef_ph (__mmask32 __U, __m512h __A, __m512h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_rcp_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_rcp_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_rcp_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_rsqrt_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_rsqrt_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_rsqrt_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_getexp_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_getexp_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_getexp_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_scalef_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_scalef_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_scalef_sh (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_sqrt_ph (__m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_sqrt_ph (__m512h __W, __mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_sqrt_ph (__mmask32 __U, __m512h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_sqrt_sh (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_sqrt_sh (__m128h __W, __mmask32 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_sqrt_sh (__mmask32 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_cvtpd_ph (__m512d __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtpd_ph (__m128h __W, __mmask8 __U, __m512d __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtpd_ph (__mmask8 __U, __m512d __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_cvtph_pd (__m128h __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_pd (__m512d __W, __mmask8 __U, __m128h __A)
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_pd (__mmask8 __U, __m128h __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_cvtsh_ss (__m128 __A, __m128h __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_cvtsh_ss (__m128 __W, __mmask8 __U, __m128 __A, __m128h __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_cvtsh_ss (__mmask8 __U, __m128 __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtss_sh (__m128h __A, __m128 __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtss_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128 __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtss_sh (__mmask8 __U, __m128h __A, __m128 __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtsd_sh (__m128h __A, __m128d __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtsd_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128d __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtsd_sh (__mmask8 __U, __m128h __A, __m128d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_cvtsh_sd (__m128d __A, __m128h __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_cvtsh_sd (__m128d __W, __mmask8 __U, __m128d __A, __m128h __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_cvtsh_sd (__mmask8 __U, __m128d __A, __m128h __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epi16 (__m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epi16 (__m512i __W, __mmask32 __U, __m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epi16 (__mmask32 __U, __m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epi16 (__m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epi16 (__m512i __W, __mmask32 __U, __m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epi16 (__mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_cvtepi16_ph (__m512i __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi16_ph (__m512h __W, __mmask32 __U, __m512i __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi16_ph (__mmask32 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epu16 (__m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epu16 (__m512i __W, __mmask32 __U, __m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epu16 (__mmask32 __U, __m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epu16 (__m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epu16 (__m512i __W, __mmask32 __U, __m512h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epu16 (__mmask32 __U, __m512h __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_cvtepu16_ph (__m512i __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu16_ph (__m512h __W, __mmask32 __U, __m512i __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu16_ph (__mmask32 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epi32 (__m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epi32 (__m512i __W, __mmask16 __U, __m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epi32 (__mmask16 __U, __m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epu32 (__m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epu32 (__m512i __W, __mmask16 __U, __m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epu32 (__mmask16 __U, __m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_cvtepi32_ph (__m512i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi32_ph (__m256h __W, __mmask16 __U, __m512i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi32_ph (__mmask16 __U, __m512i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_cvtepu32_ph (__m512i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu32_ph (__m256h __W, __mmask16 __U, __m512i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu32_ph (__mmask16 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epi32 (__m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epi32 (__m512i __W, __mmask16 __U, __m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epi32 (__mmask16 __U, __m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epu32 (__m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epu32 (__m512i __W, __mmask16 __U, __m256h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epu32 (__mmask16 __U, __m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_cvtepi64_ph (__m512i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi64_ph (__m128h __W, __mmask8 __U, __m512i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi64_ph (__mmask8 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epi64 (__m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epi64 (__m512i __W, __mmask8 __U, __m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epi64 (__mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_cvtepu64_ph (__m512i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu64_ph (__m128h __W, __mmask8 __U, __m512i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu64_ph (__mmask8 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epu64 (__m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epu64 (__m512i __W, __mmask8 __U, __m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epu64 (__mmask8 __U, __m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epi64 (__m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epi64 (__m512i __W, __mmask8 __U, __m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epi64 (__mmask8 __U, __m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epu64 (__m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epu64 (__m512i __W, __mmask8 __U, __m128h __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epu64 (__mmask8 __U, __m128h __A)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_cvtsh_i32 (__m128h __A)
static __inline__ unsigned int __DEFAULT_FN_ATTRS128 _mm_cvtsh_u32 (__m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtu32_sh (__m128h __A, unsigned int __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvti32_sh (__m128h __A, int __B)
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_cvttsh_i32 (__m128h __A)
static __inline__ unsigned int __DEFAULT_FN_ATTRS128 _mm_cvttsh_u32 (__m128h __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_cvtxph_ps (__m256h __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_cvtxph_ps (__m512 __W, __mmask16 __U, __m256h __A)
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtxph_ps (__mmask16 __U, __m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_cvtxps_ph (__m512 __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtxps_ph (__m256h __W, __mmask16 __U, __m512 __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtxps_ph (__mmask16 __U, __m512 __A)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmadd_ph (__m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmadd_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmadd_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmadd_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmsub_ph (__m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmsub_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmsub_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fnmadd_ph (__m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fnmadd_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fnmadd_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fnmsub_ph (__m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fnmsub_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmaddsub_ph (__m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmaddsub_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmaddsub_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmaddsub_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmsubadd_ph (__m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmsubadd_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmsubadd_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmsub_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmsubadd_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fnmadd_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fnmsub_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fnmsub_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmadd_sh (__m128h __W, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmadd_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmadd_sh (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmadd_sh (__m128h __W, __m128h __X, __m128h __Y, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmsub_sh (__m128h __W, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmsub_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmsub_sh (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmsub_sh (__m128h __W, __m128h __X, __m128h __Y, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fnmadd_sh (__m128h __W, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fnmadd_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fnmadd_sh (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fnmadd_sh (__m128h __W, __m128h __X, __m128h __Y, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fnmsub_sh (__m128h __W, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fnmsub_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fnmsub_sh (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fnmsub_sh (__m128h __W, __m128h __X, __m128h __Y, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fcmadd_sch (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fcmadd_sch (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fcmadd_sch (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fcmadd_sch (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmadd_sch (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmadd_sch (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmadd_sch (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmadd_sch (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fcmul_sch (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fcmul_sch (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fcmul_sch (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmul_sch (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmul_sch (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmul_sch (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fcmul_pch (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fcmul_pch (__m512h __W, __mmask16 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fcmul_pch (__mmask16 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmul_pch (__m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmul_pch (__m512h __W, __mmask16 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmul_pch (__mmask16 __U, __m512h __A, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fcmadd_pch (__m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fcmadd_pch (__m512h __A, __mmask16 __U, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fcmadd_pch (__m512h __A, __m512h __B, __m512h __C, __mmask16 __U)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fcmadd_pch (__mmask16 __U, __m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmadd_pch (__m512h __A, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmadd_pch (__m512h __A, __mmask16 __U, __m512h __B, __m512h __C)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmadd_pch (__m512h __A, __m512h __B, __m512h __C, __mmask16 __U)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmadd_pch (__mmask16 __U, __m512h __A, __m512h __B, __m512h __C)
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_reduce_add_ph (__m512h __W)
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_reduce_mul_ph (__m512h __W)
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_reduce_max_ph (__m512h __V)
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_reduce_min_ph (__m512h __V)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_blend_ph (__mmask32 __U, __m512h __A, __m512h __W)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_permutex2var_ph (__m512h __A, __m512i __I, __m512h __B)
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_permutexvar_ph (__m512i __A, __m512h __B)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128
Value:
  __attribute__((__always_inline__, __nodebug__, __target__("avx512fp16"),     \
                 __min_vector_width__(128)))
Definition at line 34 of file avx512fp16intrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256
Value:
  __attribute__((__always_inline__, __nodebug__, __target__("avx512fp16"),     \
                 __min_vector_width__(256)))
Definition at line 31 of file avx512fp16intrin.h.
__DEFAULT_FN_ATTRS512
#define __DEFAULT_FN_ATTRS512
Value:
  __attribute__((__always_inline__, __nodebug__, __target__("avx512fp16"),     \
                 __min_vector_width__(512)))
Definition at line 28 of file avx512fp16intrin.h.
_mm512_add_round_ph
#define _mm512_add_round_ph (A, B, R)
Value:
  ((__m512h)__builtin_ia32_addph512((__v32hf)(__m512h)(A),                     \
                                    (__v32hf)(__m512h)(B), (int)(R)))
Definition at line 373 of file avx512fp16intrin.h.
_mm512_cmp_ph_mask
#define _mm512_cmp_ph_mask (A, B, P) _mm512_cmp_round_ph_mask((A), (B), (P), _MM_FROUND_CUR_DIRECTION)
Definition at line 802 of file avx512fp16intrin.h.
_mm512_cmp_round_ph_mask
#define _mm512_cmp_round_ph_mask (A, B, P, R)
Value:
  ((__mmask32)__builtin_ia32_cmpph512_mask((__v32hf)(__m512h)(A),              \
                                           (__v32hf)(__m512h)(B), (int)(P),    \
                                           (__mmask32)-1, (int)(R)))
Definition at line 792 of file avx512fp16intrin.h.
_mm512_cmul_pch
#define _mm512_cmul_pch (A, B) _mm512_fcmul_pch(A, B)
Definition at line 3319 of file avx512fp16intrin.h.
_mm512_cmul_round_pch
#define _mm512_cmul_round_pch (A, B, R) _mm512_fcmul_round_pch(A, B, R)
Definition at line 3322 of file avx512fp16intrin.h.
_mm512_cvt_roundepi16_ph
#define _mm512_cvt_roundepi16_ph (A, R)
Value:
  ((__m512h)__builtin_ia32_vcvtw2ph512_mask((__v32hi)(A),                      \
                                            (__v32hf)_mm512_undefined_ph(),    \
                                            (__mmask32)(-1), (int)(R)))
Definition at line 1738 of file avx512fp16intrin.h.
_mm512_cvt_roundepi32_ph
#define _mm512_cvt_roundepi32_ph (A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtdq2ph512_mask((__v16si)(A),                     \
                                             (__v16hf)_mm256_undefined_ph(),   \
                                             (__mmask16)(-1), (int)(R)))
Definition at line 1940 of file avx512fp16intrin.h.
_mm512_cvt_roundepi64_ph
#define _mm512_cvt_roundepi64_ph (A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtqq2ph512_mask(                                  \
      (__v8di)(A), (__v8hf)_mm_undefined_ph(), (__mmask8)(-1), (int)(R)))
Definition at line 2074 of file avx512fp16intrin.h.
_mm512_cvt_roundepu16_ph
#define _mm512_cvt_roundepu16_ph (A, R)
Value:
  ((__m512h)__builtin_ia32_vcvtuw2ph512_mask((__v32hu)(A),                     \
                                             (__v32hf)_mm512_undefined_ph(),   \
                                             (__mmask32)(-1), (int)(R)))
Definition at line 1839 of file avx512fp16intrin.h.
_mm512_cvt_roundepu32_ph
#define _mm512_cvt_roundepu32_ph (A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtudq2ph512_mask((__v16su)(A),                    \
                                              (__v16hf)_mm256_undefined_ph(),  \
                                              (__mmask16)(-1), (int)(R)))
Definition at line 1973 of file avx512fp16intrin.h.
_mm512_cvt_roundepu64_ph
#define _mm512_cvt_roundepu64_ph (A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtuqq2ph512_mask(                                 \
      (__v8du)(A), (__v8hf)_mm_undefined_ph(), (__mmask8)(-1), (int)(R)))
Definition at line 2139 of file avx512fp16intrin.h.
_mm512_cvt_roundpd_ph
#define _mm512_cvt_roundpd_ph (A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtpd2ph512_mask(                                  \
      (__v8df)(A), (__v8hf)_mm_undefined_ph(), (__mmask8)(-1), (int)(R)))
Definition at line 1458 of file avx512fp16intrin.h.
_mm512_cvt_roundph_epi16
#define _mm512_cvt_roundph_epi16 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2w512_mask((__v32hf)(A),                      \
                                            (__v32hi)_mm512_undefined_epi32(), \
                                            (__mmask32)(-1), (int)(R)))
Definition at line 1670 of file avx512fp16intrin.h.
_mm512_cvt_roundph_epi32
#define _mm512_cvt_roundph_epi32 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2dq512_mask(                                  \
      (__v16hf)(A), (__v16si)_mm512_undefined_epi32(), (__mmask16)(-1),        \
      (int)(R)))
Definition at line 1872 of file avx512fp16intrin.h.
_mm512_cvt_roundph_epi64
#define _mm512_cvt_roundph_epi64 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2qq512_mask((__v8hf)(A),                      \
                                             (__v8di)_mm512_undefined_epi32(), \
                                             (__mmask8)(-1), (int)(R)))
Definition at line 2106 of file avx512fp16intrin.h.
_mm512_cvt_roundph_epu16
#define _mm512_cvt_roundph_epu16 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2uw512_mask(                                  \
      (__v32hf)(A), (__v32hu)_mm512_undefined_epi32(), (__mmask32)(-1),        \
      (int)(R)))
Definition at line 1771 of file avx512fp16intrin.h.
_mm512_cvt_roundph_epu32
#define _mm512_cvt_roundph_epu32 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2udq512_mask(                                 \
      (__v16hf)(A), (__v16su)_mm512_undefined_epi32(), (__mmask16)(-1),        \
      (int)(R)))
Definition at line 1906 of file avx512fp16intrin.h.
_mm512_cvt_roundph_epu64
#define _mm512_cvt_roundph_epu64 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2uqq512_mask(                                 \
      (__v8hf)(A), (__v8du)_mm512_undefined_epi32(), (__mmask8)(-1),           \
      (int)(R)))
Definition at line 2171 of file avx512fp16intrin.h.
_mm512_cvt_roundph_pd
#define _mm512_cvt_roundph_pd (A, R)
Value:
  ((__m512d)__builtin_ia32_vcvtph2pd512_mask(                                  \
      (__v8hf)(A), (__v8df)_mm512_undefined_pd(), (__mmask8)(-1), (int)(R)))
Definition at line 1489 of file avx512fp16intrin.h.
_mm512_cvtt_roundph_epi16
#define _mm512_cvtt_roundph_epi16 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2w512_mask(                                  \
      (__v32hf)(A), (__v32hi)_mm512_undefined_epi32(), (__mmask32)(-1),        \
      (int)(R)))
Definition at line 1704 of file avx512fp16intrin.h.
_mm512_cvtt_roundph_epi32
#define _mm512_cvtt_roundph_epi32 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2dq512_mask(                                 \
      (__v16hf)(A), (__v16si)_mm512_undefined_epi32(), (__mmask16)(-1),        \
      (int)(R)))
Definition at line 2006 of file avx512fp16intrin.h.
_mm512_cvtt_roundph_epi64
#define _mm512_cvtt_roundph_epi64 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2qq512_mask(                                 \
      (__v8hf)(A), (__v8di)_mm512_undefined_epi32(), (__mmask8)(-1),           \
      (int)(R)))
Definition at line 2204 of file avx512fp16intrin.h.
_mm512_cvtt_roundph_epu16
#define _mm512_cvtt_roundph_epu16 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2uw512_mask(                                 \
      (__v32hf)(A), (__v32hu)_mm512_undefined_epi32(), (__mmask32)(-1),        \
      (int)(R)))
Definition at line 1805 of file avx512fp16intrin.h.
_mm512_cvtt_roundph_epu32
#define _mm512_cvtt_roundph_epu32 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2udq512_mask(                                \
      (__v16hf)(A), (__v16su)_mm512_undefined_epi32(), (__mmask16)(-1),        \
      (int)(R)))
Definition at line 2040 of file avx512fp16intrin.h.
_mm512_cvtt_roundph_epu64
#define _mm512_cvtt_roundph_epu64 (A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2uqq512_mask(                                \
      (__v8hf)(A), (__v8du)_mm512_undefined_epi32(), (__mmask8)(-1),           \
      (int)(R)))
Definition at line 2237 of file avx512fp16intrin.h.
_mm512_cvtx_roundph_ps
#define _mm512_cvtx_roundph_ps (A, R)
Value:
  ((__m512)__builtin_ia32_vcvtph2psx512_mask((__v16hf)(A),                     \
                                             (__v16sf)_mm512_undefined_ps(),   \
                                             (__mmask16)(-1), (int)(R)))
Definition at line 2384 of file avx512fp16intrin.h.
_mm512_cvtx_roundps_ph
#define _mm512_cvtx_roundps_ph (A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtps2phx512_mask((__v16sf)(A),                    \
                                              (__v16hf)_mm256_undefined_ph(),  \
                                              (__mmask16)(-1), (int)(R)))
Definition at line 2416 of file avx512fp16intrin.h.
_mm512_div_round_ph
#define _mm512_div_round_ph (A, B, R)
Value:
  ((__m512h)__builtin_ia32_divph512((__v32hf)(__m512h)(A),                     \
                                    (__v32hf)(__m512h)(B), (int)(R)))
Definition at line 469 of file avx512fp16intrin.h.
_mm512_fcmadd_round_pch
#define _mm512_fcmadd_round_pch (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfcmaddcph512_mask3(                                \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(C),     \
      (__mmask16)-1, (int)(R)))
Definition at line 3203 of file avx512fp16intrin.h.
_mm512_fcmul_round_pch
#define _mm512_fcmul_round_pch (A, B, R)
Value:
  ((__m512h)__builtin_ia32_vfcmulcph512_mask(                                  \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B),                            \
      (__v16sf)(__m512h)_mm512_undefined_ph(), (__mmask16)-1, (int)(R)))
Definition at line 3123 of file avx512fp16intrin.h.
_mm512_fmadd_round_pch
#define _mm512_fmadd_round_pch (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddcph512_mask3(                                 \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(C),     \
      (__mmask16)-1, (int)(R)))
Definition at line 3252 of file avx512fp16intrin.h.
_mm512_fmadd_round_ph
#define _mm512_fmadd_round_ph (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask(                                   \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)-1, (int)(R)))
Definition at line 2448 of file avx512fp16intrin.h.
_mm512_fmaddsub_round_ph
#define _mm512_fmaddsub_round_ph (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddsubph512_mask(                                \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)-1, (int)(R)))
Definition at line 2596 of file avx512fp16intrin.h.
_mm512_fmsub_round_ph
#define _mm512_fmsub_round_ph (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask(                                   \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),    \
      (__mmask32)-1, (int)(R)))
Definition at line 2468 of file avx512fp16intrin.h.
_mm512_fmsubadd_round_ph
#define _mm512_fmsubadd_round_ph (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddsubph512_mask(                                \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),    \
      (__mmask32)-1, (int)(R)))
Definition at line 2616 of file avx512fp16intrin.h.
_mm512_fmul_round_pch
#define _mm512_fmul_round_pch (A, B, R)
Value:
  ((__m512h)__builtin_ia32_vfmulcph512_mask(                                   \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B),                            \
      (__v16sf)(__m512h)_mm512_undefined_ph(), (__mmask16)-1, (int)(R)))
Definition at line 3159 of file avx512fp16intrin.h.
_mm512_fnmadd_round_ph
#define _mm512_fnmadd_round_ph (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask(                                   \
      (__v32hf)(__m512h)(A), -(__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),    \
      (__mmask32)-1, (int)(R)))
Definition at line 2483 of file avx512fp16intrin.h.
_mm512_fnmsub_round_ph
#define _mm512_fnmsub_round_ph (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask(                                   \
      (__v32hf)(__m512h)(A), -(__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),   \
      (__mmask32)-1, (int)(R)))
Definition at line 2498 of file avx512fp16intrin.h.
_mm512_fpclass_ph_mask
#define _mm512_fpclass_ph_mask (A, imm)
Value:
  ((__mmask32)__builtin_ia32_fpclassph512_mask((__v32hf)(__m512h)(A),          \
                                               (int)(imm), (__mmask32)-1))
Definition at line 1446 of file avx512fp16intrin.h.
_mm512_getexp_round_ph
#define _mm512_getexp_round_ph (A, R)
Value:
  ((__m512h)__builtin_ia32_getexpph512_mask((__v32hf)(__m512h)(A),             \
                                            (__v32hf)_mm512_undefined_ph(),    \
                                            (__mmask32)-1, (int)(R)))
Definition at line 1056 of file avx512fp16intrin.h.
_mm512_getmant_ph
#define _mm512_getmant_ph (A, B, C)
Value:
  ((__m512h)__builtin_ia32_getmantph512_mask(                                  \
      (__v32hf)(__m512h)(A), (int)(((C) << 2) | (B)),                          \
      (__v32hf)_mm512_undefined_ph(), (__mmask32)-1,                           \
      _MM_FROUND_CUR_DIRECTION))
Definition at line 1006 of file avx512fp16intrin.h.
_mm512_getmant_round_ph
#define _mm512_getmant_round_ph (A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_getmantph512_mask(                                  \
      (__v32hf)(__m512h)(A), (int)(((C) << 2) | (B)),                          \
      (__v32hf)_mm512_undefined_ph(), (__mmask32)-1, (int)(R)))
Definition at line 1022 of file avx512fp16intrin.h.
_mm512_mask3_fcmadd_round_pch
#define _mm512_mask3_fcmadd_round_pch (A, B, C, U, R)
Value:
  ((__m512h)__builtin_ia32_vfcmaddcph512_mask3(                                \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(C),     \
      (__mmask16)(U), (int)(R)))
Definition at line 3213 of file avx512fp16intrin.h.
_mm512_mask3_fmadd_round_pch
#define _mm512_mask3_fmadd_round_pch (A, B, C, U, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddcph512_mask3(                                 \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(C),     \
      (__mmask16)(U), (int)(R)))
Definition at line 3262 of file avx512fp16intrin.h.
_mm512_mask3_fmadd_round_ph
#define _mm512_mask3_fmadd_round_ph (A, B, C, U, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask3(                                  \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)(U), (int)(R)))
Definition at line 2458 of file avx512fp16intrin.h.
_mm512_mask3_fmaddsub_round_ph
#define _mm512_mask3_fmaddsub_round_ph (A, B, C, U, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddsubph512_mask3(                               \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)(U), (int)(R)))
Definition at line 2606 of file avx512fp16intrin.h.
_mm512_mask3_fmsub_round_ph
#define _mm512_mask3_fmsub_round_ph (A, B, C, U, R)
Value:
  ((__m512h)__builtin_ia32_vfmsubph512_mask3(                                  \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)(U), (int)(R)))
Definition at line 2680 of file avx512fp16intrin.h.
_mm512_mask3_fmsubadd_round_ph
#define _mm512_mask3_fmsubadd_round_ph (A, B, C, U, R)
Value:
  ((__m512h)__builtin_ia32_vfmsubaddph512_mask3(                               \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)(U), (int)(R)))
Definition at line 2692 of file avx512fp16intrin.h.
_mm512_mask3_fnmadd_round_ph
#define _mm512_mask3_fnmadd_round_ph (A, B, C, U, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask3(                                  \
      -(__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),    \
      (__mmask32)(U), (int)(R)))
Definition at line 2488 of file avx512fp16intrin.h.
_mm512_mask3_fnmsub_round_ph
#define _mm512_mask3_fnmsub_round_ph (A, B, C, U, R)
Value:
  ((__m512h)__builtin_ia32_vfmsubph512_mask3(                                  \
      -(__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),    \
      (__mmask32)(U), (int)(R)))
Definition at line 2721 of file avx512fp16intrin.h.
_mm512_mask_add_round_ph
#define _mm512_mask_add_round_ph (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_add_round_ph((A), (B), (R)),             \
      (__v32hf)(__m512h)(W)))
Definition at line 377 of file avx512fp16intrin.h.
_mm512_mask_cmp_ph_mask
#define _mm512_mask_cmp_ph_mask (U, A, B, P) _mm512_mask_cmp_round_ph_mask((U), (A), (B), (P), _MM_FROUND_CUR_DIRECTION)
Definition at line 805 of file avx512fp16intrin.h.
_mm512_mask_cmp_round_ph_mask
#define _mm512_mask_cmp_round_ph_mask (U, A, B, P, R)
Value:
  ((__mmask32)__builtin_ia32_cmpph512_mask((__v32hf)(__m512h)(A),              \
                                           (__v32hf)(__m512h)(B), (int)(P),    \
                                           (__mmask32)(U), (int)(R)))
Definition at line 797 of file avx512fp16intrin.h.
_mm512_mask_cmul_pch
#define _mm512_mask_cmul_pch (W, U, A, B) _mm512_mask_fcmul_pch(W, U, A, B)
Definition at line 3320 of file avx512fp16intrin.h.
_mm512_mask_cmul_round_pch
#define _mm512_mask_cmul_round_pch (W, U, A, B, R) _mm512_mask_fcmul_round_pch(W, U, A, B, R)
Definition at line 3323 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundepi16_ph
#define _mm512_mask_cvt_roundepi16_ph (W, U, A, R)
Value:
  ((__m512h)__builtin_ia32_vcvtw2ph512_mask((__v32hi)(A), (__v32hf)(W),        \
                                            (__mmask32)(U), (int)(R)))
Definition at line 1743 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundepi32_ph
#define _mm512_mask_cvt_roundepi32_ph (W, U, A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtdq2ph512_mask((__v16si)(A), (__v16hf)(W),       \
                                             (__mmask16)(U), (int)(R)))
Definition at line 1945 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundepi64_ph
#define _mm512_mask_cvt_roundepi64_ph (W, U, A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtqq2ph512_mask((__v8di)(A), (__v8hf)(W),         \
                                             (__mmask8)(U), (int)(R)))
Definition at line 2078 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundepu16_ph
#define _mm512_mask_cvt_roundepu16_ph (W, U, A, R)
Value:
  ((__m512h)__builtin_ia32_vcvtuw2ph512_mask((__v32hu)(A), (__v32hf)(W),       \
                                             (__mmask32)(U), (int)(R)))
Definition at line 1844 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundepu32_ph
#define _mm512_mask_cvt_roundepu32_ph (W, U, A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtudq2ph512_mask((__v16su)(A), (__v16hf)(W),      \
                                              (__mmask16)(U), (int)(R)))
Definition at line 1978 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundepu64_ph
#define _mm512_mask_cvt_roundepu64_ph (W, U, A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtuqq2ph512_mask((__v8du)(A), (__v8hf)(W),        \
                                              (__mmask8)(U), (int)(R)))
Definition at line 2143 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundpd_ph
#define _mm512_mask_cvt_roundpd_ph (W, U, A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtpd2ph512_mask((__v8df)(A), (__v8hf)(W),         \
                                             (__mmask8)(U), (int)(R)))
Definition at line 1462 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundph_epi16
#define _mm512_mask_cvt_roundph_epi16 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2w512_mask((__v32hf)(A), (__v32hi)(W),        \
                                            (__mmask32)(U), (int)(R)))
Definition at line 1675 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundph_epi32
#define _mm512_mask_cvt_roundph_epi32 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2dq512_mask((__v16hf)(A), (__v16si)(W),       \
                                             (__mmask16)(U), (int)(R)))
Definition at line 1877 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundph_epi64
#define _mm512_mask_cvt_roundph_epi64 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2qq512_mask((__v8hf)(A), (__v8di)(W),         \
                                             (__mmask8)(U), (int)(R)))
Definition at line 2111 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundph_epu16
#define _mm512_mask_cvt_roundph_epu16 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2uw512_mask((__v32hf)(A), (__v32hu)(W),       \
                                             (__mmask32)(U), (int)(R)))
Definition at line 1776 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundph_epu32
#define _mm512_mask_cvt_roundph_epu32 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2udq512_mask((__v16hf)(A), (__v16su)(W),      \
                                              (__mmask16)(U), (int)(R)))
Definition at line 1911 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundph_epu64
#define _mm512_mask_cvt_roundph_epu64 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2uqq512_mask((__v8hf)(A), (__v8du)(W),        \
                                              (__mmask8)(U), (int)(R)))
Definition at line 2176 of file avx512fp16intrin.h.
_mm512_mask_cvt_roundph_pd
#define _mm512_mask_cvt_roundph_pd (W, U, A, R)
Value:
  ((__m512d)__builtin_ia32_vcvtph2pd512_mask((__v8hf)(A), (__v8df)(W),         \
                                             (__mmask8)(U), (int)(R)))
Definition at line 1493 of file avx512fp16intrin.h.
_mm512_mask_cvtt_roundph_epi16
#define _mm512_mask_cvtt_roundph_epi16 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2w512_mask((__v32hf)(A), (__v32hi)(W),       \
                                             (__mmask32)(U), (int)(R)))
Definition at line 1709 of file avx512fp16intrin.h.
_mm512_mask_cvtt_roundph_epi32
#define _mm512_mask_cvtt_roundph_epi32 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2dq512_mask((__v16hf)(A), (__v16si)(W),      \
                                              (__mmask16)(U), (int)(R)))
Definition at line 2011 of file avx512fp16intrin.h.
_mm512_mask_cvtt_roundph_epi64
#define _mm512_mask_cvtt_roundph_epi64 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2qq512_mask((__v8hf)(A), (__v8di)(W),        \
                                              (__mmask8)(U), (int)(R)))
Definition at line 2209 of file avx512fp16intrin.h.
_mm512_mask_cvtt_roundph_epu16
#define _mm512_mask_cvtt_roundph_epu16 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2uw512_mask((__v32hf)(A), (__v32hu)(W),      \
                                              (__mmask32)(U), (int)(R)))
Definition at line 1810 of file avx512fp16intrin.h.
_mm512_mask_cvtt_roundph_epu32
#define _mm512_mask_cvtt_roundph_epu32 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2udq512_mask((__v16hf)(A), (__v16su)(W),     \
                                               (__mmask16)(U), (int)(R)))
Definition at line 2045 of file avx512fp16intrin.h.
_mm512_mask_cvtt_roundph_epu64
#define _mm512_mask_cvtt_roundph_epu64 (W, U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2uqq512_mask((__v8hf)(A), (__v8du)(W),       \
                                               (__mmask8)(U), (int)(R)))
Definition at line 2242 of file avx512fp16intrin.h.
_mm512_mask_cvtx_roundph_ps
#define _mm512_mask_cvtx_roundph_ps (W, U, A, R)
Value:
  ((__m512)__builtin_ia32_vcvtph2psx512_mask((__v16hf)(A), (__v16sf)(W),       \
                                             (__mmask16)(U), (int)(R)))
Definition at line 2389 of file avx512fp16intrin.h.
_mm512_mask_cvtx_roundps_ph
#define _mm512_mask_cvtx_roundps_ph (W, U, A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtps2phx512_mask((__v16sf)(A), (__v16hf)(W),      \
                                              (__mmask16)(U), (int)(R)))
Definition at line 2421 of file avx512fp16intrin.h.
_mm512_mask_div_round_ph
#define _mm512_mask_div_round_ph (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_div_round_ph((A), (B), (R)),             \
      (__v32hf)(__m512h)(W)))
Definition at line 473 of file avx512fp16intrin.h.
_mm512_mask_fcmadd_round_pch
#define _mm512_mask_fcmadd_round_pch (A, U, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfcmaddcph512_mask(                                 \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(C),     \
      (__mmask16)(U), (int)(R)))
Definition at line 3208 of file avx512fp16intrin.h.
_mm512_mask_fcmul_round_pch
#define _mm512_mask_fcmul_round_pch (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_vfcmulcph512_mask(                                  \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(W),     \
      (__mmask16)(U), (int)(R)))
Definition at line 3128 of file avx512fp16intrin.h.
_mm512_mask_fmadd_round_pch
#define _mm512_mask_fmadd_round_pch (A, U, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddcph512_mask(                                  \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(C),     \
      (__mmask16)(U), (int)(R)))
Definition at line 3257 of file avx512fp16intrin.h.
_mm512_mask_fmadd_round_ph
#define _mm512_mask_fmadd_round_ph (A, U, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask(                                   \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)(U), (int)(R)))
Definition at line 2453 of file avx512fp16intrin.h.
_mm512_mask_fmaddsub_round_ph
#define _mm512_mask_fmaddsub_round_ph (A, U, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddsubph512_mask(                                \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)(U), (int)(R)))
Definition at line 2601 of file avx512fp16intrin.h.
_mm512_mask_fmsub_round_ph
#define _mm512_mask_fmsub_round_ph (A, U, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask(                                   \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),    \
      (__mmask32)(U), (int)(R)))
Definition at line 2473 of file avx512fp16intrin.h.
_mm512_mask_fmsubadd_round_ph
#define _mm512_mask_fmsubadd_round_ph (A, U, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddsubph512_mask(                                \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),    \
      (__mmask32)(U), (int)(R)))
Definition at line 2621 of file avx512fp16intrin.h.
_mm512_mask_fmul_round_pch
#define _mm512_mask_fmul_round_pch (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_vfmulcph512_mask(                                   \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(W),     \
      (__mmask16)(U), (int)(R)))
Definition at line 3164 of file avx512fp16intrin.h.
_mm512_mask_fnmadd_round_ph
#define _mm512_mask_fnmadd_round_ph (A, U, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask(                                   \
      (__v32hf)(__m512h)(A), -(__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),    \
      (__mmask32)(U), (int)(R)))
Definition at line 2704 of file avx512fp16intrin.h.
_mm512_mask_fnmsub_round_ph
#define _mm512_mask_fnmsub_round_ph (A, U, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_mask(                                   \
      (__v32hf)(__m512h)(A), -(__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),   \
      (__mmask32)(U), (int)(R)))
Definition at line 2716 of file avx512fp16intrin.h.
_mm512_mask_fpclass_ph_mask
#define _mm512_mask_fpclass_ph_mask (U, A, imm)
Value:
  ((__mmask32)__builtin_ia32_fpclassph512_mask((__v32hf)(__m512h)(A),          \
                                               (int)(imm), (__mmask32)(U)))
Definition at line 1442 of file avx512fp16intrin.h.
_mm512_mask_getexp_round_ph
#define _mm512_mask_getexp_round_ph (W, U, A, R)
Value:
  ((__m512h)__builtin_ia32_getexpph512_mask(                                   \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(W), (__mmask32)(U), (int)(R)))
Definition at line 1061 of file avx512fp16intrin.h.
_mm512_mask_getmant_ph
#define _mm512_mask_getmant_ph (W, U, A, B, C)
Value:
  ((__m512h)__builtin_ia32_getmantph512_mask(                                  \
      (__v32hf)(__m512h)(A), (int)(((C) << 2) | (B)), (__v32hf)(__m512h)(W),   \
      (__mmask32)(U), _MM_FROUND_CUR_DIRECTION))
Definition at line 1012 of file avx512fp16intrin.h.
_mm512_mask_getmant_round_ph
#define _mm512_mask_getmant_round_ph (W, U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_getmantph512_mask(                                  \
      (__v32hf)(__m512h)(A), (int)(((C) << 2) | (B)), (__v32hf)(__m512h)(W),   \
      (__mmask32)(U), (int)(R)))
Definition at line 1027 of file avx512fp16intrin.h.
_mm512_mask_max_round_ph
#define _mm512_mask_max_round_ph (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_max_round_ph((A), (B), (R)),             \
      (__v32hf)(__m512h)(W)))
Definition at line 539 of file avx512fp16intrin.h.
_mm512_mask_min_round_ph
#define _mm512_mask_min_round_ph (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_min_round_ph((A), (B), (R)),             \
      (__v32hf)(__m512h)(W)))
Definition at line 506 of file avx512fp16intrin.h.
_mm512_mask_mul_pch
#define _mm512_mask_mul_pch (W, U, A, B) _mm512_mask_fmul_pch(W, U, A, B)
Definition at line 3311 of file avx512fp16intrin.h.
_mm512_mask_mul_round_pch
#define _mm512_mask_mul_round_pch (W, U, A, B, R) _mm512_mask_fmul_round_pch(W, U, A, B, R)
Definition at line 3314 of file avx512fp16intrin.h.
_mm512_mask_mul_round_ph
#define _mm512_mask_mul_round_ph (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_mul_round_ph((A), (B), (R)),             \
      (__v32hf)(__m512h)(W)))
Definition at line 441 of file avx512fp16intrin.h.
_mm512_mask_reduce_ph
#define _mm512_mask_reduce_ph (W, U, A, imm)
Value:
  ((__m512h)__builtin_ia32_reduceph512_mask(                                   \
      (__v32hf)(__m512h)(A), (int)(imm), (__v32hf)(__m512h)(W),                \
      (__mmask32)(U), _MM_FROUND_CUR_DIRECTION))
Definition at line 1141 of file avx512fp16intrin.h.
_mm512_mask_reduce_round_ph
#define _mm512_mask_reduce_round_ph (W, U, A, imm, R)
Value:
  ((__m512h)__builtin_ia32_reduceph512_mask((__v32hf)(__m512h)(A), (int)(imm), \
                                            (__v32hf)(__m512h)(W),             \
                                            (__mmask32)(U), (int)(R)))
Definition at line 1151 of file avx512fp16intrin.h.
_mm512_mask_roundscale_ph
#define _mm512_mask_roundscale_ph (A, B, C, imm)
Value:
  ((__m512h)__builtin_ia32_rndscaleph_mask(                                    \
      (__v32hf)(__m512h)(C), (int)(imm), (__v32hf)(__m512h)(A),                \
      (__mmask32)(B), _MM_FROUND_CUR_DIRECTION))
Definition at line 1111 of file avx512fp16intrin.h.
_mm512_mask_roundscale_round_ph
#define _mm512_mask_roundscale_round_ph (A, B, C, imm, R)
Value:
  ((__m512h)__builtin_ia32_rndscaleph_mask((__v32hf)(__m512h)(C), (int)(imm),  \
                                           (__v32hf)(__m512h)(A),              \
                                           (__mmask32)(B), (int)(R)))
Definition at line 1121 of file avx512fp16intrin.h.
_mm512_mask_scalef_round_ph
#define _mm512_mask_scalef_round_ph (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_scalefph512_mask(                                   \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(W),     \
      (__mmask32)(U), (int)(R)))
Definition at line 1096 of file avx512fp16intrin.h.
_mm512_mask_sqrt_round_ph
#define _mm512_mask_sqrt_round_ph (W, U, A, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_sqrt_round_ph((A), (R)),                 \
      (__v32hf)(__m512h)(W)))
Definition at line 1372 of file avx512fp16intrin.h.
_mm512_mask_sub_round_ph
#define _mm512_mask_sub_round_ph (W, U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_sub_round_ph((A), (B), (R)),             \
      (__v32hf)(__m512h)(W)))
Definition at line 409 of file avx512fp16intrin.h.
_mm512_maskz_add_round_ph
#define _mm512_maskz_add_round_ph (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_add_round_ph((A), (B), (R)),             \
      (__v32hf)_mm512_setzero_ph()))
Definition at line 382 of file avx512fp16intrin.h.
_mm512_maskz_cmul_pch
#define _mm512_maskz_cmul_pch (U, A, B) _mm512_maskz_fcmul_pch(U, A, B)
Definition at line 3321 of file avx512fp16intrin.h.
_mm512_maskz_cmul_round_pch
#define _mm512_maskz_cmul_round_pch (U, A, B, R) _mm512_maskz_fcmul_round_pch(U, A, B, R)
Definition at line 3325 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundepi16_ph
#define _mm512_maskz_cvt_roundepi16_ph (U, A, R)
Value:
  ((__m512h)__builtin_ia32_vcvtw2ph512_mask(                                   \
      (__v32hi)(A), (__v32hf)_mm512_setzero_ph(), (__mmask32)(U), (int)(R)))
Definition at line 1747 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundepi32_ph
#define _mm512_maskz_cvt_roundepi32_ph (U, A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtdq2ph512_mask(                                  \
      (__v16si)(A), (__v16hf)_mm256_setzero_ph(), (__mmask16)(U), (int)(R)))
Definition at line 1949 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundepi64_ph
#define _mm512_maskz_cvt_roundepi64_ph (U, A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtqq2ph512_mask(                                  \
      (__v8di)(A), (__v8hf)_mm_setzero_ph(), (__mmask8)(U), (int)(R)))
Definition at line 2082 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundepu16_ph
#define _mm512_maskz_cvt_roundepu16_ph (U, A, R)
Value:
  ((__m512h)__builtin_ia32_vcvtuw2ph512_mask(                                  \
      (__v32hu)(A), (__v32hf)_mm512_setzero_ph(), (__mmask32)(U), (int)(R)))
Definition at line 1848 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundepu32_ph
#define _mm512_maskz_cvt_roundepu32_ph (U, A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtudq2ph512_mask(                                 \
      (__v16su)(A), (__v16hf)_mm256_setzero_ph(), (__mmask16)(U), (int)(R)))
Definition at line 1982 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundepu64_ph
#define _mm512_maskz_cvt_roundepu64_ph (U, A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtuqq2ph512_mask(                                 \
      (__v8du)(A), (__v8hf)_mm_setzero_ph(), (__mmask8)(U), (int)(R)))
Definition at line 2147 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundpd_ph
#define _mm512_maskz_cvt_roundpd_ph (U, A, R)
Value:
  ((__m128h)__builtin_ia32_vcvtpd2ph512_mask(                                  \
      (__v8df)(A), (__v8hf)_mm_setzero_ph(), (__mmask8)(U), (int)(R)))
Definition at line 1466 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundph_epi16
#define _mm512_maskz_cvt_roundph_epi16 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2w512_mask((__v32hf)(A),                      \
                                            (__v32hi)_mm512_setzero_epi32(),   \
                                            (__mmask32)(U), (int)(R)))
Definition at line 1679 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundph_epi32
#define _mm512_maskz_cvt_roundph_epi32 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2dq512_mask((__v16hf)(A),                     \
                                             (__v16si)_mm512_setzero_epi32(),  \
                                             (__mmask16)(U), (int)(R)))
Definition at line 1881 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundph_epi64
#define _mm512_maskz_cvt_roundph_epi64 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2qq512_mask(                                  \
      (__v8hf)(A), (__v8di)_mm512_setzero_epi32(), (__mmask8)(U), (int)(R)))
Definition at line 2115 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundph_epu16
#define _mm512_maskz_cvt_roundph_epu16 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2uw512_mask((__v32hf)(A),                     \
                                             (__v32hu)_mm512_setzero_epi32(),  \
                                             (__mmask32)(U), (int)(R)))
Definition at line 1780 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundph_epu32
#define _mm512_maskz_cvt_roundph_epu32 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2udq512_mask((__v16hf)(A),                    \
                                              (__v16su)_mm512_setzero_epi32(), \
                                              (__mmask16)(U), (int)(R)))
Definition at line 1915 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundph_epu64
#define _mm512_maskz_cvt_roundph_epu64 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvtph2uqq512_mask(                                 \
      (__v8hf)(A), (__v8du)_mm512_setzero_epi32(), (__mmask8)(U), (int)(R)))
Definition at line 2180 of file avx512fp16intrin.h.
_mm512_maskz_cvt_roundph_pd
#define _mm512_maskz_cvt_roundph_pd (U, A, R)
Value:
  ((__m512d)__builtin_ia32_vcvtph2pd512_mask(                                  \
      (__v8hf)(A), (__v8df)_mm512_setzero_pd(), (__mmask8)(U), (int)(R)))
Definition at line 1497 of file avx512fp16intrin.h.
_mm512_maskz_cvtt_roundph_epi16
#define _mm512_maskz_cvtt_roundph_epi16 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2w512_mask((__v32hf)(A),                     \
                                             (__v32hi)_mm512_setzero_epi32(),  \
                                             (__mmask32)(U), (int)(R)))
Definition at line 1713 of file avx512fp16intrin.h.
_mm512_maskz_cvtt_roundph_epi32
#define _mm512_maskz_cvtt_roundph_epi32 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2dq512_mask((__v16hf)(A),                    \
                                              (__v16si)_mm512_setzero_epi32(), \
                                              (__mmask16)(U), (int)(R)))
Definition at line 2015 of file avx512fp16intrin.h.
_mm512_maskz_cvtt_roundph_epi64
#define _mm512_maskz_cvtt_roundph_epi64 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2qq512_mask(                                 \
      (__v8hf)(A), (__v8di)_mm512_setzero_epi32(), (__mmask8)(U), (int)(R)))
Definition at line 2213 of file avx512fp16intrin.h.
_mm512_maskz_cvtt_roundph_epu16
#define _mm512_maskz_cvtt_roundph_epu16 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2uw512_mask((__v32hf)(A),                    \
                                              (__v32hu)_mm512_setzero_epi32(), \
                                              (__mmask32)(U), (int)(R)))
Definition at line 1814 of file avx512fp16intrin.h.
_mm512_maskz_cvtt_roundph_epu32
#define _mm512_maskz_cvtt_roundph_epu32 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2udq512_mask(                                \
      (__v16hf)(A), (__v16su)_mm512_setzero_epi32(), (__mmask16)(U),           \
      (int)(R)))
Definition at line 2049 of file avx512fp16intrin.h.
_mm512_maskz_cvtt_roundph_epu64
#define _mm512_maskz_cvtt_roundph_epu64 (U, A, R)
Value:
  ((__m512i)__builtin_ia32_vcvttph2uqq512_mask(                                \
      (__v8hf)(A), (__v8du)_mm512_setzero_epi32(), (__mmask8)(U), (int)(R)))
Definition at line 2246 of file avx512fp16intrin.h.
_mm512_maskz_cvtx_roundph_ps
#define _mm512_maskz_cvtx_roundph_ps (U, A, R)
Value:
  ((__m512)__builtin_ia32_vcvtph2psx512_mask(                                  \
      (__v16hf)(A), (__v16sf)_mm512_setzero_ps(), (__mmask16)(U), (int)(R)))
Definition at line 2393 of file avx512fp16intrin.h.
_mm512_maskz_cvtx_roundps_ph
#define _mm512_maskz_cvtx_roundps_ph (U, A, R)
Value:
  ((__m256h)__builtin_ia32_vcvtps2phx512_mask(                                 \
      (__v16sf)(A), (__v16hf)_mm256_setzero_ph(), (__mmask16)(U), (int)(R)))
Definition at line 2425 of file avx512fp16intrin.h.
_mm512_maskz_div_round_ph
#define _mm512_maskz_div_round_ph (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_div_round_ph((A), (B), (R)),             \
      (__v32hf)_mm512_setzero_ph()))
Definition at line 478 of file avx512fp16intrin.h.
_mm512_maskz_fcmadd_round_pch
#define _mm512_maskz_fcmadd_round_pch (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfcmaddcph512_maskz(                                \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(C),     \
      (__mmask16)(U), (int)(R)))
Definition at line 3218 of file avx512fp16intrin.h.
_mm512_maskz_fcmul_round_pch
#define _mm512_maskz_fcmul_round_pch (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_vfcmulcph512_mask(                                  \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B),                            \
      (__v16sf)(__m512h)_mm512_setzero_ph(), (__mmask16)(U), (int)(R)))
Definition at line 3133 of file avx512fp16intrin.h.
_mm512_maskz_fmadd_round_pch
#define _mm512_maskz_fmadd_round_pch (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddcph512_maskz(                                 \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B), (__v16sf)(__m512h)(C),     \
      (__mmask16)(U), (int)(R)))
Definition at line 3267 of file avx512fp16intrin.h.
_mm512_maskz_fmadd_round_ph
#define _mm512_maskz_fmadd_round_ph (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_maskz(                                  \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)(U), (int)(R)))
Definition at line 2463 of file avx512fp16intrin.h.
_mm512_maskz_fmaddsub_round_ph
#define _mm512_maskz_fmaddsub_round_ph (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddsubph512_maskz(                               \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),     \
      (__mmask32)(U), (int)(R)))
Definition at line 2611 of file avx512fp16intrin.h.
_mm512_maskz_fmsub_round_ph
#define _mm512_maskz_fmsub_round_ph (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_maskz(                                  \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),    \
      (__mmask32)(U), (int)(R)))
Definition at line 2478 of file avx512fp16intrin.h.
_mm512_maskz_fmsubadd_round_ph
#define _mm512_maskz_fmsubadd_round_ph (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddsubph512_maskz(                               \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),    \
      (__mmask32)(U), (int)(R)))
Definition at line 2626 of file avx512fp16intrin.h.
_mm512_maskz_fmul_round_pch
#define _mm512_maskz_fmul_round_pch (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_vfmulcph512_mask(                                   \
      (__v16sf)(__m512h)(A), (__v16sf)(__m512h)(B),                            \
      (__v16sf)(__m512h)_mm512_setzero_ph(), (__mmask16)(U), (int)(R)))
Definition at line 3169 of file avx512fp16intrin.h.
_mm512_maskz_fnmadd_round_ph
#define _mm512_maskz_fnmadd_round_ph (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_maskz(                                  \
      -(__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), (__v32hf)(__m512h)(C),    \
      (__mmask32)(U), (int)(R)))
Definition at line 2493 of file avx512fp16intrin.h.
_mm512_maskz_fnmsub_round_ph
#define _mm512_maskz_fnmsub_round_ph (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_vfmaddph512_maskz(                                  \
      -(__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B), -(__v32hf)(__m512h)(C),   \
      (__mmask32)(U), (int)(R)))
Definition at line 2503 of file avx512fp16intrin.h.
_mm512_maskz_getexp_round_ph
#define _mm512_maskz_getexp_round_ph (U, A, R)
Value:
  ((__m512h)__builtin_ia32_getexpph512_mask((__v32hf)(__m512h)(A),             \
                                            (__v32hf)_mm512_setzero_ph(),      \
                                            (__mmask32)(U), (int)(R)))
Definition at line 1065 of file avx512fp16intrin.h.
_mm512_maskz_getmant_ph
#define _mm512_maskz_getmant_ph (U, A, B, C)
Value:
  ((__m512h)__builtin_ia32_getmantph512_mask(                                  \
      (__v32hf)(__m512h)(A), (int)(((C) << 2) | (B)),                          \
      (__v32hf)_mm512_setzero_ph(), (__mmask32)(U), _MM_FROUND_CUR_DIRECTION))
Definition at line 1017 of file avx512fp16intrin.h.
_mm512_maskz_getmant_round_ph
#define _mm512_maskz_getmant_round_ph (U, A, B, C, R)
Value:
  ((__m512h)__builtin_ia32_getmantph512_mask(                                  \
      (__v32hf)(__m512h)(A), (int)(((C) << 2) | (B)),                          \
      (__v32hf)_mm512_setzero_ph(), (__mmask32)(U), (int)(R)))
Definition at line 1032 of file avx512fp16intrin.h.
_mm512_maskz_max_round_ph
#define _mm512_maskz_max_round_ph (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_max_round_ph((A), (B), (R)),             \
      (__v32hf)_mm512_setzero_ph()))
Definition at line 544 of file avx512fp16intrin.h.
_mm512_maskz_min_round_ph
#define _mm512_maskz_min_round_ph (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_min_round_ph((A), (B), (R)),             \
      (__v32hf)_mm512_setzero_ph()))
Definition at line 511 of file avx512fp16intrin.h.
_mm512_maskz_mul_pch
#define _mm512_maskz_mul_pch (U, A, B) _mm512_maskz_fmul_pch(U, A, B)
Definition at line 3312 of file avx512fp16intrin.h.
_mm512_maskz_mul_round_pch
#define _mm512_maskz_mul_round_pch (U, A, B, R) _mm512_maskz_fmul_round_pch(U, A, B, R)
Definition at line 3316 of file avx512fp16intrin.h.
_mm512_maskz_mul_round_ph
#define _mm512_maskz_mul_round_ph (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_mul_round_ph((A), (B), (R)),             \
      (__v32hf)_mm512_setzero_ph()))
Definition at line 446 of file avx512fp16intrin.h.
_mm512_maskz_reduce_ph
#define _mm512_maskz_reduce_ph (U, A, imm)
Value:
  ((__m512h)__builtin_ia32_reduceph512_mask(                                   \
      (__v32hf)(__m512h)(A), (int)(imm), (__v32hf)_mm512_setzero_ph(),         \
      (__mmask32)(U), _MM_FROUND_CUR_DIRECTION))
Definition at line 1146 of file avx512fp16intrin.h.
_mm512_maskz_reduce_round_ph
#define _mm512_maskz_reduce_round_ph (U, A, imm, R)
Value:
  ((__m512h)__builtin_ia32_reduceph512_mask((__v32hf)(__m512h)(A), (int)(imm), \
                                            (__v32hf)_mm512_setzero_ph(),      \
                                            (__mmask32)(U), (int)(R)))
Definition at line 1156 of file avx512fp16intrin.h.
_mm512_maskz_roundscale_ph
#define _mm512_maskz_roundscale_ph (A, B, imm)
Value:
  ((__m512h)__builtin_ia32_rndscaleph_mask(                                    \
      (__v32hf)(__m512h)(B), (int)(imm), (__v32hf)_mm512_setzero_ph(),         \
      (__mmask32)(A), _MM_FROUND_CUR_DIRECTION))
Definition at line 1116 of file avx512fp16intrin.h.
_mm512_maskz_roundscale_round_ph
#define _mm512_maskz_roundscale_round_ph (A, B, imm, R)
Value:
  ((__m512h)__builtin_ia32_rndscaleph_mask((__v32hf)(__m512h)(B), (int)(imm),  \
                                           (__v32hf)_mm512_setzero_ph(),       \
                                           (__mmask32)(A), (int)(R)))
Definition at line 1126 of file avx512fp16intrin.h.
_mm512_maskz_scalef_round_ph
#define _mm512_maskz_scalef_round_ph (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_scalefph512_mask(                                   \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B),                            \
      (__v32hf)_mm512_setzero_ph(), (__mmask32)(U), (int)(R)))
Definition at line 1101 of file avx512fp16intrin.h.
_mm512_maskz_sqrt_round_ph
#define _mm512_maskz_sqrt_round_ph (U, A, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_sqrt_round_ph((A), (R)),                 \
      (__v32hf)_mm512_setzero_ph()))
Definition at line 1377 of file avx512fp16intrin.h.
_mm512_maskz_sub_round_ph
#define _mm512_maskz_sub_round_ph (U, A, B, R)
Value:
  ((__m512h)__builtin_ia32_selectph_512(                                       \
      (__mmask32)(U), (__v32hf)_mm512_sub_round_ph((A), (B), (R)),             \
      (__v32hf)_mm512_setzero_ph()))
Definition at line 414 of file avx512fp16intrin.h.
_mm512_max_round_ph
#define _mm512_max_round_ph (A, B, R)
Value:
  ((__m512h)__builtin_ia32_maxph512((__v32hf)(__m512h)(A),                     \
                                    (__v32hf)(__m512h)(B), (int)(R)))
Definition at line 535 of file avx512fp16intrin.h.
_mm512_min_round_ph
#define _mm512_min_round_ph (A, B, R)
Value:
  ((__m512h)__builtin_ia32_minph512((__v32hf)(__m512h)(A),                     \
                                    (__v32hf)(__m512h)(B), (int)(R)))
Definition at line 502 of file avx512fp16intrin.h.
_mm512_mul_pch
#define _mm512_mul_pch (A, B) _mm512_fmul_pch(A, B)
Definition at line 3310 of file avx512fp16intrin.h.
_mm512_mul_round_pch
#define _mm512_mul_round_pch (A, B, R) _mm512_fmul_round_pch(A, B, R)
Definition at line 3313 of file avx512fp16intrin.h.
_mm512_mul_round_ph
#define _mm512_mul_round_ph (A, B, R)
Value:
  ((__m512h)__builtin_ia32_mulph512((__v32hf)(__m512h)(A),                     \
                                    (__v32hf)(__m512h)(B), (int)(R)))
Definition at line 437 of file avx512fp16intrin.h.
_mm512_reduce_ph
#define _mm512_reduce_ph (A, imm)
Value:
  ((__m512h)__builtin_ia32_reduceph512_mask(                                   \
      (__v32hf)(__m512h)(A), (int)(imm), (__v32hf)_mm512_undefined_ph(),       \
      (__mmask32)-1, _MM_FROUND_CUR_DIRECTION))
Definition at line 1136 of file avx512fp16intrin.h.
_mm512_reduce_round_ph
#define _mm512_reduce_round_ph (A, imm, R)
Value:
  ((__m512h)__builtin_ia32_reduceph512_mask((__v32hf)(__m512h)(A), (int)(imm), \
                                            (__v32hf)_mm512_undefined_ph(),    \
                                            (__mmask32)-1, (int)(R)))
Definition at line 1161 of file avx512fp16intrin.h.
_mm512_roundscale_ph
#define _mm512_roundscale_ph (A, B)
Value:
  ((__m512h)__builtin_ia32_rndscaleph_mask(                                    \
      (__v32hf)(__m512h)(A), (int)(B), (__v32hf)(__m512h)(A), (__mmask32)-1,   \
      _MM_FROUND_CUR_DIRECTION))
Definition at line 1106 of file avx512fp16intrin.h.
_mm512_roundscale_round_ph
#define _mm512_roundscale_round_ph (A, imm, R)
Value:
  ((__m512h)__builtin_ia32_rndscaleph_mask((__v32hf)(__m512h)(A), (int)(imm),  \
                                           (__v32hf)_mm512_undefined_ph(),     \
                                           (__mmask32)-1, (int)(R)))
Definition at line 1131 of file avx512fp16intrin.h.
_mm512_scalef_round_ph
#define _mm512_scalef_round_ph (A, B, R)
Value:
  ((__m512h)__builtin_ia32_scalefph512_mask(                                   \
      (__v32hf)(__m512h)(A), (__v32hf)(__m512h)(B),                            \
      (__v32hf)_mm512_undefined_ph(), (__mmask32)-1, (int)(R)))
Definition at line 1091 of file avx512fp16intrin.h.
_mm512_setr_ph
#define _mm512_setr_ph (h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14, h15, h16, h17, h18, h19, h20, h21, h22, h23, h24, h25, h26, h27, h28, h29, h30, h31, h32)
Value:
  _mm512_set_ph((h32), (h31), (h30), (h29), (h28), (h27), (h26), (h25), (h24), \
                (h23), (h22), (h21), (h20), (h19), (h18), (h17), (h16), (h15), \
                (h14), (h13), (h12), (h11), (h10), (h9), (h8), (h7), (h6),     \
                (h5), (h4), (h3), (h2), (h1))
Definition at line 92 of file avx512fp16intrin.h.
_mm512_sqrt_round_ph
#define _mm512_sqrt_round_ph (A, R) ((__m512h)__builtin_ia32_sqrtph512((__v32hf)(__m512h)(A), (int)(R)))
Definition at line 1369 of file avx512fp16intrin.h.
_mm512_sub_round_ph
#define _mm512_sub_round_ph (A, B, R)
Value:
  ((__m512h)__builtin_ia32_subph512((__v32hf)(__m512h)(A),                     \
                                    (__v32hf)(__m512h)(B), (int)(R)))
Definition at line 405 of file avx512fp16intrin.h.
_mm_add_round_sh
#define _mm_add_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_addsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 591 of file avx512fp16intrin.h.
_mm_cmp_round_sh_mask
#define _mm_cmp_round_sh_mask (X, Y, P, R)
Value:
  ((__mmask8)__builtin_ia32_cmpsh_mask((__v8hf)(__m128h)(X),                   \
                                       (__v8hf)(__m128h)(Y), (int)(P),         \
                                       (__mmask8)-1, (int)(R)))
Definition at line 808 of file avx512fp16intrin.h.
_mm_cmp_sh_mask
#define _mm_cmp_sh_mask (X, Y, P)
Value:
  ((__mmask8)__builtin_ia32_cmpsh_mask(                                        \
      (__v8hf)(__m128h)(X), (__v8hf)(__m128h)(Y), (int)(P), (__mmask8)-1,      \
      _MM_FROUND_CUR_DIRECTION))
Definition at line 818 of file avx512fp16intrin.h.
_mm_cmul_round_sch
#define _mm_cmul_round_sch (A, B, R) _mm_fcmul_round_sch(A, B, R)
Definition at line 3339 of file avx512fp16intrin.h.
_mm_cmul_sch
#define _mm_cmul_sch (A, B) _mm_fcmul_sch(A, B)
Definition at line 3336 of file avx512fp16intrin.h.
_mm_comi_round_sh
#define _mm_comi_round_sh (A, B, P, R) __builtin_ia32_vcomish((__v8hf)A, (__v8hf)B, (int)(P), (int)(R))
Definition at line 277 of file avx512fp16intrin.h.
_mm_comi_sh
#define _mm_comi_sh (A, B, pred) _mm_comi_round_sh((A), (B), (pred), _MM_FROUND_CUR_DIRECTION)
Definition at line 280 of file avx512fp16intrin.h.
_mm_cvt_roundi32_sh
#define _mm_cvt_roundi32_sh (A, B, R) ((__m128h)__builtin_ia32_vcvtsi2sh((__v8hf)(A), (int)(B), (int)(R)))
Definition at line 2326 of file avx512fp16intrin.h.
_mm_cvt_roundsd_sh
#define _mm_cvt_roundsd_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_vcvtsd2sh_round_mask((__v8hf)(A), (__v2df)(B),      \
                                                (__v8hf)_mm_undefined_ph(),    \
                                                (__mmask8)(-1), (int)(R)))
Definition at line 1596 of file avx512fp16intrin.h.
_mm_cvt_roundsh_i32
#define _mm_cvt_roundsh_i32 (A, R) ((int)__builtin_ia32_vcvtsh2si32((__v8hf)(A), (int)(R)))
Definition at line 2270 of file avx512fp16intrin.h.
_mm_cvt_roundsh_sd
#define _mm_cvt_roundsh_sd (A, B, R)
Value:
  ((__m128d)__builtin_ia32_vcvtsh2sd_round_mask((__v2df)(A), (__v8hf)(B),      \
                                                (__v2df)_mm_undefined_pd(),    \
                                                (__mmask8)(-1), (int)(R)))
Definition at line 1633 of file avx512fp16intrin.h.
_mm_cvt_roundsh_ss
#define _mm_cvt_roundsh_ss (A, B, R)
Value:
  ((__m128)__builtin_ia32_vcvtsh2ss_round_mask((__v4sf)(A), (__v8hf)(B),       \
                                               (__v4sf)_mm_undefined_ps(),     \
                                               (__mmask8)(-1), (int)(R)))
Definition at line 1520 of file avx512fp16intrin.h.
_mm_cvt_roundsh_u32
#define _mm_cvt_roundsh_u32 (A, R) ((unsigned int)__builtin_ia32_vcvtsh2usi32((__v8hf)(A), (int)(R)))
Definition at line 2277 of file avx512fp16intrin.h.
_mm_cvt_roundss_sh
#define _mm_cvt_roundss_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_vcvtss2sh_round_mask((__v8hf)(A), (__v4sf)(B),      \
                                                (__v8hf)_mm_undefined_ph(),    \
                                                (__mmask8)(-1), (int)(R)))
Definition at line 1558 of file avx512fp16intrin.h.
_mm_cvt_roundu32_sh
#define _mm_cvt_roundu32_sh (A, B, R) ((__m128h)__builtin_ia32_vcvtusi2sh((__v8hf)(A), (unsigned int)(B), (int)(R)))
Definition at line 2305 of file avx512fp16intrin.h.
_mm_cvtt_roundsh_i32
#define _mm_cvtt_roundsh_i32 (A, R) ((int)__builtin_ia32_vcvttsh2si32((__v8hf)(A), (int)(R)))
Definition at line 2346 of file avx512fp16intrin.h.
_mm_cvtt_roundsh_u32
#define _mm_cvtt_roundsh_u32 (A, R) ((unsigned int)__builtin_ia32_vcvttsh2usi32((__v8hf)(A), (int)(R)))
Definition at line 2364 of file avx512fp16intrin.h.
_mm_div_round_sh
#define _mm_div_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_divsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 699 of file avx512fp16intrin.h.
_mm_fcmadd_round_sch
#define _mm_fcmadd_round_sch (A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfcmaddcsh_mask(                                    \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(C),        \
      (__mmask8)-1, (int)(R)))
Definition at line 2961 of file avx512fp16intrin.h.
_mm_fcmul_round_sch
#define _mm_fcmul_round_sch (A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfcmulcsh_mask(                                     \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B),                              \
      (__v4sf)(__m128h)_mm_undefined_ph(), (__mmask8)-1, (int)(R)))
Definition at line 3049 of file avx512fp16intrin.h.
_mm_fmadd_round_sch
#define _mm_fmadd_round_sch (A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddcsh_mask(                                     \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(C),        \
      (__mmask8)-1, (int)(R)))
Definition at line 3008 of file avx512fp16intrin.h.
_mm_fmadd_round_sh
#define _mm_fmadd_round_sh (A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask(                                     \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(C),        \
      (__mmask8)-1, (int)(R)))
Definition at line 2755 of file avx512fp16intrin.h.
_mm_fmsub_round_sh
#define _mm_fmsub_round_sh (A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask(                                     \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), -(__v8hf)(__m128h)(C),       \
      (__mmask8)-1, (int)(R)))
Definition at line 2806 of file avx512fp16intrin.h.
_mm_fmul_round_sch
#define _mm_fmul_round_sch (A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfmulcsh_mask(                                      \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B),                              \
      (__v4sf)(__m128h)_mm_undefined_ph(), (__mmask8)-1, (int)(R)))
Definition at line 3087 of file avx512fp16intrin.h.
_mm_fnmadd_round_sh
#define _mm_fnmadd_round_sh (A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask(                                     \
      (__v8hf)(__m128h)(A), -(__v8hf)(__m128h)(B), (__v8hf)(__m128h)(C),       \
      (__mmask8)-1, (int)(R)))
Definition at line 2853 of file avx512fp16intrin.h.
_mm_fnmsub_round_sh
#define _mm_fnmsub_round_sh (A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask(                                     \
      (__v8hf)(__m128h)(A), -(__v8hf)(__m128h)(B), -(__v8hf)(__m128h)(C),      \
      (__mmask8)-1, (int)(R)))
Definition at line 2900 of file avx512fp16intrin.h.
_mm_fpclass_sh_mask
#define _mm_fpclass_sh_mask (A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclasssh_mask((__v8hf)(__m128h)(A), (int)(imm),   \
                                           (__mmask8)-1))
Definition at line 1450 of file avx512fp16intrin.h.
_mm_getexp_round_sh
#define _mm_getexp_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_getexpsh128_round_mask(                             \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 1237 of file avx512fp16intrin.h.
_mm_getmant_round_sh
#define _mm_getmant_round_sh (A, B, C, D, R)
Value:
  ((__m128h)__builtin_ia32_getmantsh_round_mask(                               \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (int)(((D) << 2) | (C)),     \
      (__v8hf)_mm_setzero_ph(), (__mmask8)-1, (int)(R)))
Definition at line 1207 of file avx512fp16intrin.h.
_mm_getmant_sh
#define _mm_getmant_sh (A, B, C, D)
Value:
  ((__m128h)__builtin_ia32_getmantsh_round_mask(                               \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (int)(((D) << 2) | (C)),     \
      (__v8hf)_mm_setzero_ph(), (__mmask8)-1, _MM_FROUND_CUR_DIRECTION))
Definition at line 1212 of file avx512fp16intrin.h.
_mm_mask3_fcmadd_round_sch
#define _mm_mask3_fcmadd_round_sch (A, B, C, U, R)
Value:
  ((__m128h)__builtin_ia32_vfcmaddcsh_round_mask3(                             \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(C),        \
      (__mmask8)(U), (int)(R)))
Definition at line 2976 of file avx512fp16intrin.h.
_mm_mask3_fmadd_round_sch
#define _mm_mask3_fmadd_round_sch (A, B, C, U, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddcsh_round_mask3(                              \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(C),        \
      (__mmask8)(U), (int)(R)))
Definition at line 3023 of file avx512fp16intrin.h.
_mm_mask3_fmadd_round_sh
#define _mm_mask3_fmadd_round_sh (W, X, Y, U, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask3(                                    \
      (__v8hf)(__m128h)(W), (__v8hf)(__m128h)(X), (__v8hf)(__m128h)(Y),        \
      (__mmask8)(U), (int)(R)))
Definition at line 2784 of file avx512fp16intrin.h.
_mm_mask3_fmsub_round_sh
#define _mm_mask3_fmsub_round_sh (W, X, Y, U, R)
Value:
  ((__m128h)__builtin_ia32_vfmsubsh3_mask3(                                    \
      (__v8hf)(__m128h)(W), (__v8hf)(__m128h)(X), (__v8hf)(__m128h)(Y),        \
      (__mmask8)(U), (int)(R)))
Definition at line 2835 of file avx512fp16intrin.h.
_mm_mask3_fnmadd_round_sh
#define _mm_mask3_fnmadd_round_sh (W, X, Y, U, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask3(                                    \
      (__v8hf)(__m128h)(W), -(__v8hf)(__m128h)(X), (__v8hf)(__m128h)(Y),       \
      (__mmask8)(U), (int)(R)))
Definition at line 2882 of file avx512fp16intrin.h.
_mm_mask3_fnmsub_round_sh
#define _mm_mask3_fnmsub_round_sh (W, X, Y, U, R)
Value:
  ((__m128h)__builtin_ia32_vfmsubsh3_mask3(                                    \
      (__v8hf)(__m128h)(W), -(__v8hf)(__m128h)(X), (__v8hf)(__m128h)(Y),       \
      (__mmask8)(U), (int)(R)))
Definition at line 2929 of file avx512fp16intrin.h.
_mm_mask_add_round_sh
#define _mm_mask_add_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_addsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 596 of file avx512fp16intrin.h.
_mm_mask_cmp_round_sh_mask
#define _mm_mask_cmp_round_sh_mask (M, X, Y, P, R)
Value:
  ((__mmask8)__builtin_ia32_cmpsh_mask((__v8hf)(__m128h)(X),                   \
                                       (__v8hf)(__m128h)(Y), (int)(P),         \
                                       (__mmask8)(M), (int)(R)))
Definition at line 813 of file avx512fp16intrin.h.
_mm_mask_cmp_sh_mask
#define _mm_mask_cmp_sh_mask (M, X, Y, P)
Value:
  ((__mmask8)__builtin_ia32_cmpsh_mask(                                        \
      (__v8hf)(__m128h)(X), (__v8hf)(__m128h)(Y), (int)(P), (__mmask8)(M),     \
      _MM_FROUND_CUR_DIRECTION))
Definition at line 823 of file avx512fp16intrin.h.
_mm_mask_cmul_round_sch
#define _mm_mask_cmul_round_sch (W, U, A, B, R) _mm_mask_fcmul_round_sch(W, U, A, B, R)
Definition at line 3340 of file avx512fp16intrin.h.
_mm_mask_cmul_sch
#define _mm_mask_cmul_sch (W, U, A, B) _mm_mask_fcmul_sch(W, U, A, B)
Definition at line 3337 of file avx512fp16intrin.h.
_mm_mask_cvt_roundsd_sh
#define _mm_mask_cvt_roundsd_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vcvtsd2sh_round_mask(                               \
      (__v8hf)(A), (__v2df)(B), (__v8hf)(W), (__mmask8)(U), (int)(R)))
Definition at line 1601 of file avx512fp16intrin.h.
_mm_mask_cvt_roundsh_sd
#define _mm_mask_cvt_roundsh_sd (W, U, A, B, R)
Value:
  ((__m128d)__builtin_ia32_vcvtsh2sd_round_mask(                               \
      (__v2df)(A), (__v8hf)(B), (__v2df)(W), (__mmask8)(U), (int)(R)))
Definition at line 1638 of file avx512fp16intrin.h.
_mm_mask_cvt_roundsh_ss
#define _mm_mask_cvt_roundsh_ss (W, U, A, B, R)
Value:
  ((__m128)__builtin_ia32_vcvtsh2ss_round_mask(                                \
      (__v4sf)(A), (__v8hf)(B), (__v4sf)(W), (__mmask8)(U), (int)(R)))
Definition at line 1525 of file avx512fp16intrin.h.
_mm_mask_cvt_roundss_sh
#define _mm_mask_cvt_roundss_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vcvtss2sh_round_mask(                               \
      (__v8hf)(A), (__v4sf)(B), (__v8hf)(W), (__mmask8)(U), (int)(R)))
Definition at line 1563 of file avx512fp16intrin.h.
_mm_mask_div_round_sh
#define _mm_mask_div_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_divsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 704 of file avx512fp16intrin.h.
_mm_mask_fcmadd_round_sch
#define _mm_mask_fcmadd_round_sch (A, U, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfcmaddcsh_round_mask(                              \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(C),        \
      (__mmask8)(U), (int)(R)))
Definition at line 2966 of file avx512fp16intrin.h.
_mm_mask_fcmul_round_sch
#define _mm_mask_fcmul_round_sch (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfcmulcsh_mask(                                     \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 3054 of file avx512fp16intrin.h.
_mm_mask_fmadd_round_sch
#define _mm_mask_fmadd_round_sch (A, U, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddcsh_round_mask(                               \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(C),        \
      (__mmask8)(U), (int)(R)))
Definition at line 3013 of file avx512fp16intrin.h.
_mm_mask_fmadd_round_sh
#define _mm_mask_fmadd_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask(                                     \
      (__v8hf)(__m128h)(W), (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B),        \
      (__mmask8)(U), (int)(R)))
Definition at line 2760 of file avx512fp16intrin.h.
_mm_mask_fmsub_round_sh
#define _mm_mask_fmsub_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask(                                     \
      (__v8hf)(__m128h)(W), (__v8hf)(__m128h)(A), -(__v8hf)(__m128h)(B),       \
      (__mmask8)(U), (int)(R)))
Definition at line 2811 of file avx512fp16intrin.h.
_mm_mask_fmul_round_sch
#define _mm_mask_fmul_round_sch (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfmulcsh_mask(                                      \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 3092 of file avx512fp16intrin.h.
_mm_mask_fnmadd_round_sh
#define _mm_mask_fnmadd_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask(                                     \
      (__v8hf)(__m128h)(W), -(__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B),       \
      (__mmask8)(U), (int)(R)))
Definition at line 2858 of file avx512fp16intrin.h.
_mm_mask_fnmsub_round_sh
#define _mm_mask_fnmsub_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_mask(                                     \
      (__v8hf)(__m128h)(W), -(__v8hf)(__m128h)(A), -(__v8hf)(__m128h)(B),      \
      (__mmask8)(U), (int)(R)))
Definition at line 2905 of file avx512fp16intrin.h.
_mm_mask_fpclass_sh_mask
#define _mm_mask_fpclass_sh_mask (U, A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclasssh_mask((__v8hf)(__m128h)(A), (int)(imm),   \
                                           (__mmask8)(U)))
Definition at line 1454 of file avx512fp16intrin.h.
_mm_mask_getexp_round_sh
#define _mm_mask_getexp_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_getexpsh128_round_mask(                             \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 1256 of file avx512fp16intrin.h.
_mm_mask_getmant_round_sh
#define _mm_mask_getmant_round_sh (W, U, A, B, C, D, R)
Value:
  ((__m128h)__builtin_ia32_getmantsh_round_mask(                               \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (int)(((D) << 2) | (C)),     \
      (__v8hf)(__m128h)(W), (__mmask8)(U), (int)(R)))
Definition at line 1222 of file avx512fp16intrin.h.
_mm_mask_getmant_sh
#define _mm_mask_getmant_sh (W, U, A, B, C, D)
Value:
  ((__m128h)__builtin_ia32_getmantsh_round_mask(                               \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (int)(((D) << 2) | (C)),     \
      (__v8hf)(__m128h)(W), (__mmask8)(U), _MM_FROUND_CUR_DIRECTION))
Definition at line 1217 of file avx512fp16intrin.h.
_mm_mask_max_round_sh
#define _mm_mask_max_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_maxsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 782 of file avx512fp16intrin.h.
_mm_mask_min_round_sh
#define _mm_mask_min_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_minsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 743 of file avx512fp16intrin.h.
_mm_mask_mul_round_sch
#define _mm_mask_mul_round_sch (W, U, A, B, R) _mm_mask_fmul_round_sch(W, U, A, B, R)
Definition at line 3332 of file avx512fp16intrin.h.
_mm_mask_mul_round_sh
#define _mm_mask_mul_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_mulsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 668 of file avx512fp16intrin.h.
_mm_mask_mul_sch
#define _mm_mask_mul_sch (W, U, A, B) _mm_mask_fmul_sch(W, U, A, B)
Definition at line 3329 of file avx512fp16intrin.h.
_mm_mask_reduce_round_sh
#define _mm_mask_reduce_round_sh (W, U, A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_reducesh_mask(                                      \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(C), (int)(R)))
Definition at line 1359 of file avx512fp16intrin.h.
_mm_mask_reduce_sh
#define _mm_mask_reduce_sh (W, U, A, B, C)
Value:
  ((__m128h)__builtin_ia32_reducesh_mask(                                      \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(C), _MM_FROUND_CUR_DIRECTION))
Definition at line 1344 of file avx512fp16intrin.h.
_mm_mask_roundscale_round_sh
#define _mm_mask_roundscale_round_sh (W, U, A, B, I, R)
Value:
  ((__m128h)__builtin_ia32_rndscalesh_round_mask(                              \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(I), (int)(R)))
Definition at line 1324 of file avx512fp16intrin.h.
_mm_mask_roundscale_sh
#define _mm_mask_roundscale_sh (W, U, A, B, I)
Value:
  ((__m128h)__builtin_ia32_rndscalesh_round_mask(                              \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(I), _MM_FROUND_CUR_DIRECTION))
Definition at line 1319 of file avx512fp16intrin.h.
_mm_mask_scalef_round_sh
#define _mm_mask_scalef_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_scalefsh_round_mask(                                \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 1292 of file avx512fp16intrin.h.
_mm_mask_sqrt_round_sh
#define _mm_mask_sqrt_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_sqrtsh_round_mask(                                  \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 1408 of file avx512fp16intrin.h.
_mm_mask_sub_round_sh
#define _mm_mask_sub_round_sh (W, U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_subsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(W),        \
      (__mmask8)(U), (int)(R)))
Definition at line 632 of file avx512fp16intrin.h.
_mm_maskz_add_round_sh
#define _mm_maskz_add_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_addsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 601 of file avx512fp16intrin.h.
_mm_maskz_cmul_round_sch
#define _mm_maskz_cmul_round_sch (U, A, B, R) _mm_maskz_fcmul_round_sch(U, A, B, R)
Definition at line 3342 of file avx512fp16intrin.h.
_mm_maskz_cmul_sch
#define _mm_maskz_cmul_sch (U, A, B) _mm_maskz_fcmul_sch(U, A, B)
Definition at line 3338 of file avx512fp16intrin.h.
_mm_maskz_cvt_roundsd_sh
#define _mm_maskz_cvt_roundsd_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vcvtsd2sh_round_mask((__v8hf)(A), (__v2df)(B),      \
                                                (__v8hf)_mm_setzero_ph(),      \
                                                (__mmask8)(U), (int)(R)))
Definition at line 1605 of file avx512fp16intrin.h.
_mm_maskz_cvt_roundsh_sd
#define _mm_maskz_cvt_roundsh_sd (U, A, B, R)
Value:
  ((__m128d)__builtin_ia32_vcvtsh2sd_round_mask((__v2df)(A), (__v8hf)(B),      \
                                                (__v2df)_mm_setzero_pd(),      \
                                                (__mmask8)(U), (int)(R)))
Definition at line 1642 of file avx512fp16intrin.h.
_mm_maskz_cvt_roundsh_ss
#define _mm_maskz_cvt_roundsh_ss (U, A, B, R)
Value:
  ((__m128)__builtin_ia32_vcvtsh2ss_round_mask((__v4sf)(A), (__v8hf)(B),       \
                                               (__v4sf)_mm_setzero_ps(),       \
                                               (__mmask8)(U), (int)(R)))
Definition at line 1529 of file avx512fp16intrin.h.
_mm_maskz_cvt_roundss_sh
#define _mm_maskz_cvt_roundss_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vcvtss2sh_round_mask((__v8hf)(A), (__v4sf)(B),      \
                                                (__v8hf)_mm_setzero_ph(),      \
                                                (__mmask8)(U), (int)(R)))
Definition at line 1567 of file avx512fp16intrin.h.
_mm_maskz_div_round_sh
#define _mm_maskz_div_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_divsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 709 of file avx512fp16intrin.h.
_mm_maskz_fcmadd_round_sch
#define _mm_maskz_fcmadd_round_sch (U, A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfcmaddcsh_maskz(                                   \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(C),        \
      (__mmask8)(U), (int)(R)))
Definition at line 2971 of file avx512fp16intrin.h.
_mm_maskz_fcmul_round_sch
#define _mm_maskz_fcmul_round_sch (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfcmulcsh_mask(                                     \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B),                              \
      (__v4sf)(__m128h)_mm_setzero_ph(), (__mmask8)(U), (int)(R)))
Definition at line 3059 of file avx512fp16intrin.h.
_mm_maskz_fmadd_round_sch
#define _mm_maskz_fmadd_round_sch (U, A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddcsh_maskz(                                    \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B), (__v4sf)(__m128h)(C),        \
      (__mmask8)(U), (int)(R)))
Definition at line 3018 of file avx512fp16intrin.h.
_mm_maskz_fmadd_round_sh
#define _mm_maskz_fmadd_round_sh (U, A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_maskz(                                    \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)(__m128h)(C),        \
      (__mmask8)(U), (int)(R)))
Definition at line 2772 of file avx512fp16intrin.h.
_mm_maskz_fmsub_round_sh
#define _mm_maskz_fmsub_round_sh (U, A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_maskz(                                    \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), -(__v8hf)(__m128h)(C),       \
      (__mmask8)(U), (int)R))
Definition at line 2823 of file avx512fp16intrin.h.
_mm_maskz_fmul_round_sch
#define _mm_maskz_fmul_round_sch (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_vfmulcsh_mask(                                      \
      (__v4sf)(__m128h)(A), (__v4sf)(__m128h)(B),                              \
      (__v4sf)(__m128h)_mm_setzero_ph(), (__mmask8)(U), (int)(R)))
Definition at line 3097 of file avx512fp16intrin.h.
_mm_maskz_fnmadd_round_sh
#define _mm_maskz_fnmadd_round_sh (U, A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_maskz(                                    \
      (__v8hf)(__m128h)(A), -(__v8hf)(__m128h)(B), (__v8hf)(__m128h)(C),       \
      (__mmask8)(U), (int)(R)))
Definition at line 2870 of file avx512fp16intrin.h.
_mm_maskz_fnmsub_round_sh
#define _mm_maskz_fnmsub_round_sh (U, A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_vfmaddsh3_maskz(                                    \
      (__v8hf)(__m128h)(A), -(__v8hf)(__m128h)(B), -(__v8hf)(__m128h)(C),      \
      (__mmask8)(U), (int)(R)))
Definition at line 2917 of file avx512fp16intrin.h.
_mm_maskz_getexp_round_sh
#define _mm_maskz_getexp_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_getexpsh128_round_mask(                             \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 1268 of file avx512fp16intrin.h.
_mm_maskz_getmant_round_sh
#define _mm_maskz_getmant_round_sh (U, A, B, C, D, R)
Value:
  ((__m128h)__builtin_ia32_getmantsh_round_mask(                               \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (int)(((D) << 2) | (C)),     \
      (__v8hf)_mm_setzero_ph(), (__mmask8)(U), (int)(R)))
Definition at line 1232 of file avx512fp16intrin.h.
_mm_maskz_getmant_sh
#define _mm_maskz_getmant_sh (U, A, B, C, D)
Value:
  ((__m128h)__builtin_ia32_getmantsh_round_mask(                               \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (int)(((D) << 2) | (C)),     \
      (__v8hf)_mm_setzero_ph(), (__mmask8)(U), _MM_FROUND_CUR_DIRECTION))
Definition at line 1227 of file avx512fp16intrin.h.
_mm_maskz_max_round_sh
#define _mm_maskz_max_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_maxsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 787 of file avx512fp16intrin.h.
_mm_maskz_min_round_sh
#define _mm_maskz_min_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_minsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 748 of file avx512fp16intrin.h.
_mm_maskz_mul_round_sch
#define _mm_maskz_mul_round_sch (U, A, B, R) _mm_maskz_fmul_round_sch(U, A, B, R)
Definition at line 3334 of file avx512fp16intrin.h.
_mm_maskz_mul_round_sh
#define _mm_maskz_mul_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_mulsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 673 of file avx512fp16intrin.h.
_mm_maskz_mul_sch
#define _mm_maskz_mul_sch (U, A, B) _mm_maskz_fmul_sch(U, A, B)
Definition at line 3330 of file avx512fp16intrin.h.
_mm_maskz_reduce_round_sh
#define _mm_maskz_reduce_round_sh (U, A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_reducesh_mask(                                      \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(C), (int)(R)))
Definition at line 1364 of file avx512fp16intrin.h.
_mm_maskz_reduce_sh
#define _mm_maskz_reduce_sh (U, A, B, C)
Value:
  ((__m128h)__builtin_ia32_reducesh_mask(                                      \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(C), _MM_FROUND_CUR_DIRECTION))
Definition at line 1349 of file avx512fp16intrin.h.
_mm_maskz_roundscale_round_sh
#define _mm_maskz_roundscale_round_sh (U, A, B, I, R)
Value:
  ((__m128h)__builtin_ia32_rndscalesh_round_mask(                              \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(I), (int)(R)))
Definition at line 1334 of file avx512fp16intrin.h.
_mm_maskz_roundscale_sh
#define _mm_maskz_roundscale_sh (U, A, B, I)
Value:
  ((__m128h)__builtin_ia32_rndscalesh_round_mask(                              \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(I), _MM_FROUND_CUR_DIRECTION))
Definition at line 1329 of file avx512fp16intrin.h.
_mm_maskz_scalef_round_sh
#define _mm_maskz_scalef_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_scalefsh_round_mask(                                \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 1304 of file avx512fp16intrin.h.
_mm_maskz_sqrt_round_sh
#define _mm_maskz_sqrt_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_sqrtsh_round_mask(                                  \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 1413 of file avx512fp16intrin.h.
_mm_maskz_sub_round_sh
#define _mm_maskz_sub_round_sh (U, A, B, R)
Value:
  ((__m128h)__builtin_ia32_subsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)(U), (int)(R)))
Definition at line 637 of file avx512fp16intrin.h.
_mm_max_round_sh
#define _mm_max_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_maxsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 777 of file avx512fp16intrin.h.
_mm_min_round_sh
#define _mm_min_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_minsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 738 of file avx512fp16intrin.h.
_mm_mul_round_sch
#define _mm_mul_round_sch (A, B, R) _mm_fmul_round_sch(A, B, R)
Definition at line 3331 of file avx512fp16intrin.h.
_mm_mul_round_sh
#define _mm_mul_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_mulsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 663 of file avx512fp16intrin.h.
_mm_mul_sch
#define _mm_mul_sch (A, B) _mm_fmul_sch(A, B)
Definition at line 3328 of file avx512fp16intrin.h.
_mm_reduce_round_sh
#define _mm_reduce_round_sh (A, B, C, R)
Value:
  ((__m128h)__builtin_ia32_reducesh_mask(                                      \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(C), (int)(R)))
Definition at line 1354 of file avx512fp16intrin.h.
_mm_reduce_sh
#define _mm_reduce_sh (A, B, C)
Value:
  ((__m128h)__builtin_ia32_reducesh_mask(                                      \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(C), _MM_FROUND_CUR_DIRECTION))
Definition at line 1339 of file avx512fp16intrin.h.
_mm_roundscale_round_sh
#define _mm_roundscale_round_sh (A, B, imm, R)
Value:
  ((__m128h)__builtin_ia32_rndscalesh_round_mask(                              \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(imm), (int)(R)))
Definition at line 1309 of file avx512fp16intrin.h.
_mm_roundscale_sh
#define _mm_roundscale_sh (A, B, imm)
Value:
  ((__m128h)__builtin_ia32_rndscalesh_round_mask(                              \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(imm), _MM_FROUND_CUR_DIRECTION))
Definition at line 1314 of file avx512fp16intrin.h.
_mm_scalef_round_sh
#define _mm_scalef_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_scalefsh_round_mask(                                \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 1273 of file avx512fp16intrin.h.
_mm_sqrt_round_sh
#define _mm_sqrt_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_sqrtsh_round_mask(                                  \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 1403 of file avx512fp16intrin.h.
_mm_sub_round_sh
#define _mm_sub_round_sh (A, B, R)
Value:
  ((__m128h)__builtin_ia32_subsh_round_mask(                                   \
      (__v8hf)(__m128h)(A), (__v8hf)(__m128h)(B), (__v8hf)_mm_setzero_ph(),    \
      (__mmask8)-1, (int)(R)))
Definition at line 627 of file avx512fp16intrin.h.
Typedef Documentation
__attribute__
typedef _Float16 __m256h_u __attribute__((__vector_size__(32), __aligned__(1)))
Definition at line 17 of file avx512fp16intrin.h.
Function Documentation
_mm256_castpd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_castpd_ph (__m256d __a) static
Definition at line 159 of file avx512fp16intrin.h.
References __a.
_mm256_castph128_ph256()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_castph128_ph256 (__m128h __a) static
Definition at line 198 of file avx512fp16intrin.h.
References __a.
_mm256_castph256_ph128()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_castph256_ph128 (__m256h __a) static
Definition at line 182 of file avx512fp16intrin.h.
References __a.
_mm256_castph_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_castph_pd (__m256h __a) static
Definition at line 121 of file avx512fp16intrin.h.
References __a.
_mm256_castph_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_castph_ps (__m256h __a) static
Definition at line 109 of file avx512fp16intrin.h.
References __a.
_mm256_castph_si256()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_castph_si256 (__m256h __a) static
Definition at line 134 of file avx512fp16intrin.h.
References __a.
_mm256_castps_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_castps_ph (__m256 __a) static
Definition at line 147 of file avx512fp16intrin.h.
References __a.
_mm256_castsi256_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_castsi256_ph (__m256i __a) static
Definition at line 172 of file avx512fp16intrin.h.
References __a.
_mm256_load_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_load_ph (void const * __p) static
Definition at line 856 of file avx512fp16intrin.h.
References __p.
_mm256_loadu_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_loadu_ph (void const * __p) static
Definition at line 873 of file avx512fp16intrin.h.
References __p, and __v.
_mm256_setzero_ph()
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_setzero_ph (void) static
Definition at line 46 of file avx512fp16intrin.h.
Referenced by _mm256_getexp_ph(), _mm256_maskz_add_ph(), _mm256_maskz_cvtepi16_ph(), _mm256_maskz_cvtepu16_ph(), _mm256_maskz_div_ph(), _mm256_maskz_fcmul_pch(), _mm256_maskz_fmadd_ph(), _mm256_maskz_fmaddsub_ph(), _mm256_maskz_fmsub_ph(), _mm256_maskz_fmsubadd_ph(), _mm256_maskz_fmul_pch(), _mm256_maskz_fnmadd_ph(), _mm256_maskz_fnmsub_ph(), _mm256_maskz_getexp_ph(), _mm256_maskz_max_ph(), _mm256_maskz_min_ph(), _mm256_maskz_mul_ph(), _mm256_maskz_rcp_ph(), _mm256_maskz_rsqrt_ph(), _mm256_maskz_scalef_ph(), _mm256_maskz_sqrt_ph(), _mm256_maskz_sub_ph(), _mm256_scalef_ph(), _mm512_cvtepi32_ph(), _mm512_cvtepu32_ph(), _mm512_cvtxps_ph(), _mm512_maskz_cvtepi32_ph(), _mm512_maskz_cvtepu32_ph(), _mm512_maskz_cvtxps_ph(), and _mm512_zextph256_ph512().
_mm256_store_ph()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_store_ph (void * __P, __m256h __A) static
Definition at line 907 of file avx512fp16intrin.h.
References __P.
_mm256_storeu_ph()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_storeu_ph (void * __P, __m256h __A) static
Definition at line 925 of file avx512fp16intrin.h.
References __P, and __v.
_mm256_undefined_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_undefined_ph (void) static
Definition at line 51 of file avx512fp16intrin.h.
Referenced by _mm256_fcmul_pch(), _mm256_fmul_pch(), _mm256_rcp_ph(), and _mm256_rsqrt_ph().
_mm256_zextph128_ph256()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_zextph128_ph256 (__m128h __a) static
Constructs a 256-bit floating-point vector of [16 x half] from a 128-bit floating-point vector of [8 x half].
The lower 128 bits contain the value of the source vector. The upper 384 bits are set to zero.
This intrinsic has no corresponding instruction.
Parameters
__a A 128-bit vector of [8 x half].
Returns
A 512-bit floating-point vector of [16 x half]. The lower 128 bits contain the value of the parameter. The upper 384 bits are set to zero.
Definition at line 231 of file avx512fp16intrin.h.
References __a, and _mm_setzero_ph().
_mm512_abs_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_abs_ph (__m512h __A) static
Definition at line 549 of file avx512fp16intrin.h.
References _mm512_and_epi32(), and _mm512_set1_epi32().
_mm512_add_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_add_ph (__m512h __A, __m512h __B) static
Definition at line 355 of file avx512fp16intrin.h.
Referenced by _mm512_mask_add_ph(), and _mm512_maskz_add_ph().
_mm512_castpd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castpd_ph (__m512d __a) static
Definition at line 163 of file avx512fp16intrin.h.
References __a.
_mm512_castph128_ph512()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castph128_ph512 (__m128h __a) static
Definition at line 204 of file avx512fp16intrin.h.
References __a.
_mm512_castph256_ph512()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castph256_ph512 (__m256h __a) static
Definition at line 211 of file avx512fp16intrin.h.
References __a.
_mm512_castph512_ph128()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_castph512_ph128 (__m512h __a) static
Definition at line 187 of file avx512fp16intrin.h.
References __a.
_mm512_castph512_ph256()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_castph512_ph256 (__m512h __a) static
Definition at line 192 of file avx512fp16intrin.h.
References __a.
_mm512_castph_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_castph_pd (__m512h __a) static
Definition at line 125 of file avx512fp16intrin.h.
References __a.
_mm512_castph_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_castph_ps (__m512h __a) static
Definition at line 113 of file avx512fp16intrin.h.
References __a.
_mm512_castph_si512()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_castph_si512 (__m512h __a) static
Definition at line 139 of file avx512fp16intrin.h.
References __a.
_mm512_castps_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castps_ph (__m512 __a) static
Definition at line 151 of file avx512fp16intrin.h.
References __a.
_mm512_castsi512_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_castsi512_ph (__m512i __a) static
Definition at line 177 of file avx512fp16intrin.h.
References __a.
_mm512_conj_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_conj_pch (__m512h __A) static
Definition at line 553 of file avx512fp16intrin.h.
References _mm512_set1_ps(), and _mm512_xor_ps().
Referenced by _mm512_mask_conj_pch(), and _mm512_maskz_conj_pch().
_mm512_cvtepi16_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_cvtepi16_ph (__m512i __A) static
Definition at line 1752 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtepi32_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_cvtepi32_ph (__m512i __A) static
Definition at line 1954 of file avx512fp16intrin.h.
References _mm256_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_cvtepi64_ph (__m512i __A) static
Definition at line 2087 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm512_cvtepu16_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_cvtepu16_ph (__m512i __A) static
Definition at line 1853 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtepu32_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_cvtepu32_ph (__m512i __A) static
Definition at line 1987 of file avx512fp16intrin.h.
References _mm256_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_cvtepu64_ph (__m512i __A) static
Definition at line 2152 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm512_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_cvtpd_ph (__m512d __A) static
Definition at line 1470 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm512_cvtph_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epi16 (__m512h __A) static
Definition at line 1685 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtph_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epi32 (__m256h __A) static
Definition at line 1887 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtph_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epi64 (__m128h __A) static
Definition at line 2120 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtph_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epu16 (__m512h __A) static
Definition at line 1786 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtph_epu32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epu32 (__m256h __A) static
Definition at line 1921 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtph_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtph_epu64 (__m128h __A) static
Definition at line 2185 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtph_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_cvtph_pd (__m128h __A) static
Definition at line 1501 of file avx512fp16intrin.h.
References _mm512_setzero_pd(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtsh_h()
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_cvtsh_h (__m512h __a) static
Definition at line 38 of file avx512fp16intrin.h.
References __a.
_mm512_cvttph_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epi16 (__m512h __A) static
Definition at line 1719 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttph_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epi32 (__m256h __A) static
Definition at line 2021 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttph_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epi64 (__m128h __A) static
Definition at line 2218 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttph_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epu16 (__m512h __A) static
Definition at line 1820 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttph_epu32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epu32 (__m256h __A) static
Definition at line 2055 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvttph_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvttph_epu64 (__m128h __A) static
Definition at line 2251 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtxph_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_cvtxph_ps (__m256h __A) static
Definition at line 2397 of file avx512fp16intrin.h.
References _mm512_setzero_ps(), and _MM_FROUND_CUR_DIRECTION.
_mm512_cvtxps_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_cvtxps_ph (__m512 __A) static
Definition at line 2429 of file avx512fp16intrin.h.
References _mm256_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_div_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_div_ph (__m512h __A, __m512h __B) static
Definition at line 451 of file avx512fp16intrin.h.
Referenced by _mm512_mask_div_ph(), and _mm512_maskz_div_ph().
_mm512_fcmadd_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fcmadd_pch (__m512h __A, __m512h __B, __m512h __C) static
Definition at line 3174 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_fcmul_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fcmul_pch (__m512h __A, __m512h __B) static
Definition at line 3102 of file avx512fp16intrin.h.
References _mm512_undefined_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_fmadd_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmadd_pch (__m512h __A, __m512h __B, __m512h __C) static
Definition at line 3223 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_fmadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmadd_ph (__m512h __A, __m512h __B, __m512h __C) static
Definition at line 2508 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_fmaddsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmaddsub_ph (__m512h __A, __m512h __B, __m512h __C) static
Definition at line 2632 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_fmsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmsub_ph (__m512h __A, __m512h __B, __m512h __C) static
Definition at line 2537 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_fmsubadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmsubadd_ph (__m512h __A, __m512h __B, __m512h __C) static
Definition at line 2660 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_fmul_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fmul_pch (__m512h __A, __m512h __B) static
Definition at line 3138 of file avx512fp16intrin.h.
References _mm512_undefined_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_fnmadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fnmadd_ph (__m512h __A, __m512h __B, __m512h __C) static
Definition at line 2559 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_fnmsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_fnmsub_ph (__m512h __A, __m512h __B, __m512h __C) static
Definition at line 2581 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_getexp_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_getexp_ph (__m512h __A) static
Definition at line 1037 of file avx512fp16intrin.h.
References _mm512_undefined_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_load_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_load_ph (void const * __p) static
Definition at line 851 of file avx512fp16intrin.h.
References __p.
_mm512_loadu_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_loadu_ph (void const * __p) static
Definition at line 865 of file avx512fp16intrin.h.
References __p, and __v.
_mm512_mask3_fcmadd_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fcmadd_pch (__m512h __A, __m512h __B, __m512h __C, __mmask16 __U) static
Definition at line 3190 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask3_fmadd_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmadd_pch (__m512h __A, __m512h __B, __m512h __C, __mmask16 __U) static
Definition at line 3239 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask3_fmadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmadd_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U) static
Definition at line 2524 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask3_fmaddsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmaddsub_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U) static
Definition at line 2646 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask3_fmsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmsub_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U) static
Definition at line 2686 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask3_fmsubadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fmsubadd_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U) static
Definition at line 2698 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask3_fnmadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fnmadd_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U) static
Definition at line 2568 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask3_fnmsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask3_fnmsub_ph (__m512h __A, __m512h __B, __m512h __C, __mmask32 __U) static
Definition at line 2734 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_add_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_add_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 361 of file avx512fp16intrin.h.
References _mm512_add_ph().
_mm512_mask_blend_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_blend_ph (__mmask32 __U, __m512h __A, __m512h __W) static
Definition at line 3293 of file avx512fp16intrin.h.
_mm512_mask_conj_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_conj_pch (__m512h __W, __mmask16 __U, __m512h __A) static
Definition at line 558 of file avx512fp16intrin.h.
References _mm512_conj_pch().
_mm512_mask_cvtepi16_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi16_ph (__m512h __W, __mmask32 __U, __m512i __A) static
Definition at line 1759 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtepi32_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi32_ph (__m256h __W, __mmask16 __U, __m512i __A) static
Definition at line 1961 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi64_ph (__m128h __W, __mmask8 __U, __m512i __A) static
Definition at line 2094 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtepu16_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu16_ph (__m512h __W, __mmask32 __U, __m512i __A) static
Definition at line 1860 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtepu32_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu32_ph (__m256h __W, __mmask16 __U, __m512i __A) static
Definition at line 1994 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu64_ph (__m128h __W, __mmask8 __U, __m512i __A) static
Definition at line 2159 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtpd_ph (__m128h __W, __mmask8 __U, __m512d __A) static
Definition at line 1477 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtph_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epi16 (__m512i __W, __mmask32 __U, __m512h __A) static
Definition at line 1692 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtph_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epi32 (__m512i __W, __mmask16 __U, __m256h __A) static
Definition at line 1894 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtph_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epi64 (__m512i __W, __mmask8 __U, __m128h __A) static
Definition at line 2127 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtph_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epu16 (__m512i __W, __mmask32 __U, __m512h __A) static
Definition at line 1793 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtph_epu32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epu32 (__m512i __W, __mmask16 __U, __m256h __A) static
Definition at line 1928 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtph_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_epu64 (__m512i __W, __mmask8 __U, __m128h __A) static
Definition at line 2192 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtph_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_mask_cvtph_pd (__m512d __W, __mmask8 __U, __m128h __A) static
Definition at line 1508 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttph_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epi16 (__m512i __W, __mmask32 __U, __m512h __A) static
Definition at line 1726 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttph_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epi32 (__m512i __W, __mmask16 __U, __m256h __A) static
Definition at line 2028 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttph_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epi64 (__m512i __W, __mmask8 __U, __m128h __A) static
Definition at line 2225 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttph_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epu16 (__m512i __W, __mmask32 __U, __m512h __A) static
Definition at line 1827 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttph_epu32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epu32 (__m512i __W, __mmask16 __U, __m256h __A) static
Definition at line 2062 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvttph_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvttph_epu64 (__m512i __W, __mmask8 __U, __m128h __A) static
Definition at line 2258 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtxph_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_mask_cvtxph_ps (__m512 __W, __mmask16 __U, __m256h __A) static
Definition at line 2404 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_cvtxps_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_mask_cvtxps_ph (__m256h __W, __mmask16 __U, __m512 __A) static
Definition at line 2436 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_div_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_div_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 457 of file avx512fp16intrin.h.
References _mm512_div_ph().
_mm512_mask_fcmadd_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fcmadd_pch (__m512h __A, __mmask16 __U, __m512h __B, __m512h __C) static
Definition at line 3183 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fcmul_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fcmul_pch (__m512h __W, __mmask16 __U, __m512h __A, __m512h __B) static
Definition at line 3110 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fmadd_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmadd_pch (__m512h __A, __mmask16 __U, __m512h __B, __m512h __C) static
Definition at line 3232 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fmadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmadd_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C) static
Definition at line 2517 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fmaddsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmaddsub_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C) static
Definition at line 2639 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fmsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmsub_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C) static
Definition at line 2546 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fmsubadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmsubadd_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C) static
Definition at line 2667 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fmul_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fmul_pch (__m512h __W, __mmask16 __U, __m512h __A, __m512h __B) static
Definition at line 3146 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fnmadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fnmadd_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C) static
Definition at line 2710 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_fnmsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_fnmsub_ph (__m512h __A, __mmask32 __U, __m512h __B, __m512h __C) static
Definition at line 2727 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_getexp_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_getexp_ph (__m512h __W, __mmask32 __U, __m512h __A) static
Definition at line 1044 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_max_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_max_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 523 of file avx512fp16intrin.h.
References _mm512_max_ph().
_mm512_mask_min_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_min_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 490 of file avx512fp16intrin.h.
References _mm512_min_ph().
_mm512_mask_mul_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_mul_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 425 of file avx512fp16intrin.h.
References _mm512_mul_ph().
_mm512_mask_rcp_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_rcp_ph (__m512h __W, __mmask32 __U, __m512h __A) static
Definition at line 978 of file avx512fp16intrin.h.
_mm512_mask_rsqrt_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_rsqrt_ph (__m512h __W, __mmask32 __U, __m512h __A) static
Definition at line 995 of file avx512fp16intrin.h.
_mm512_mask_scalef_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_scalef_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 1078 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_sqrt_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_sqrt_ph (__m512h __W, __mmask32 __U, __m512h __A) static
Definition at line 1388 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_mask_sub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mask_sub_ph (__m512h __W, __mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 393 of file avx512fp16intrin.h.
References _mm512_sub_ph().
_mm512_maskz_add_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_add_ph (__mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 367 of file avx512fp16intrin.h.
References _mm512_add_ph(), and _mm512_setzero_ph().
_mm512_maskz_conj_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_conj_pch (__mmask16 __U, __m512h __A) static
Definition at line 564 of file avx512fp16intrin.h.
References _mm512_conj_pch(), and _mm512_setzero_ps().
_mm512_maskz_cvtepi16_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi16_ph (__mmask32 __U, __m512i __A) static
Definition at line 1765 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtepi32_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi32_ph (__mmask16 __U, __m512i __A) static
Definition at line 1967 of file avx512fp16intrin.h.
References _mm256_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi64_ph (__mmask8 __U, __m512i __A) static
Definition at line 2100 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm512_maskz_cvtepu16_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu16_ph (__mmask32 __U, __m512i __A) static
Definition at line 1866 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtepu32_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu32_ph (__mmask16 __U, __m512i __A) static
Definition at line 2000 of file avx512fp16intrin.h.
References _mm256_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu64_ph (__mmask8 __U, __m512i __A) static
Definition at line 2165 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm512_maskz_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtpd_ph (__mmask8 __U, __m512d __A) static
Definition at line 1483 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm512_maskz_cvtph_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epi16 (__mmask32 __U, __m512h __A) static
Definition at line 1698 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtph_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epi32 (__mmask16 __U, __m256h __A) static
Definition at line 1900 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtph_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epi64 (__mmask8 __U, __m128h __A) static
Definition at line 2133 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtph_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epu16 (__mmask32 __U, __m512h __A) static
Definition at line 1799 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtph_epu32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epu32 (__mmask16 __U, __m256h __A) static
Definition at line 1934 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtph_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_epu64 (__mmask8 __U, __m128h __A) static
Definition at line 2198 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtph_pd()
static __inline__ __m512d __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtph_pd (__mmask8 __U, __m128h __A) static
Definition at line 1514 of file avx512fp16intrin.h.
References _mm512_setzero_pd(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttph_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epi16 (__mmask32 __U, __m512h __A) static
Definition at line 1732 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttph_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epi32 (__mmask16 __U, __m256h __A) static
Definition at line 2034 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttph_epi64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epi64 (__mmask8 __U, __m128h __A) static
Definition at line 2231 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttph_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epu16 (__mmask32 __U, __m512h __A) static
Definition at line 1833 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttph_epu32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epu32 (__mmask16 __U, __m256h __A) static
Definition at line 2068 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvttph_epu64()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvttph_epu64 (__mmask8 __U, __m128h __A) static
Definition at line 2264 of file avx512fp16intrin.h.
References _mm512_setzero_epi32, and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtxph_ps()
static __inline__ __m512 __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtxph_ps (__mmask16 __U, __m256h __A) static
Definition at line 2410 of file avx512fp16intrin.h.
References _mm512_setzero_ps(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_cvtxps_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtxps_ph (__mmask16 __U, __m512 __A) static
Definition at line 2442 of file avx512fp16intrin.h.
References _mm256_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_div_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_div_ph (__mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 463 of file avx512fp16intrin.h.
References _mm512_div_ph(), and _mm512_setzero_ph().
_mm512_maskz_fcmadd_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fcmadd_pch (__mmask16 __U, __m512h __A, __m512h __B, __m512h __C) static
Definition at line 3197 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fcmul_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fcmul_pch (__mmask16 __U, __m512h __A, __m512h __B) static
Definition at line 3117 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fmadd_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmadd_pch (__mmask16 __U, __m512h __A, __m512h __B, __m512h __C) static
Definition at line 3246 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fmadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmadd_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C) static
Definition at line 2531 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fmaddsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmaddsub_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C) static
Definition at line 2653 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fmsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmsub_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C) static
Definition at line 2553 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fmsubadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmsubadd_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C) static
Definition at line 2674 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fmul_pch()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fmul_pch (__mmask16 __U, __m512h __A, __m512h __B) static
Definition at line 3153 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fnmadd_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fnmadd_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C) static
Definition at line 2575 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_fnmsub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_fnmsub_ph (__mmask32 __U, __m512h __A, __m512h __B, __m512h __C) static
Definition at line 2590 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_getexp_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_getexp_ph (__mmask32 __U, __m512h __A) static
Definition at line 1050 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_max_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_max_ph (__mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 529 of file avx512fp16intrin.h.
References _mm512_max_ph(), and _mm512_setzero_ph().
_mm512_maskz_min_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_min_ph (__mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 496 of file avx512fp16intrin.h.
References _mm512_min_ph(), and _mm512_setzero_ph().
_mm512_maskz_mul_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_mul_ph (__mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 431 of file avx512fp16intrin.h.
References _mm512_mul_ph(), and _mm512_setzero_ph().
_mm512_maskz_rcp_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_rcp_ph (__mmask32 __U, __m512h __A) static
Definition at line 984 of file avx512fp16intrin.h.
References _mm512_setzero_ph().
_mm512_maskz_rsqrt_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_rsqrt_ph (__mmask32 __U, __m512h __A) static
Definition at line 1001 of file avx512fp16intrin.h.
References _mm512_setzero_ph().
_mm512_maskz_scalef_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_scalef_ph (__mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 1085 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_sqrt_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_sqrt_ph (__mmask32 __U, __m512h __A) static
Definition at line 1396 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_maskz_sub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_maskz_sub_ph (__mmask32 __U, __m512h __A, __m512h __B) static
Definition at line 399 of file avx512fp16intrin.h.
References _mm512_setzero_ph(), and _mm512_sub_ph().
_mm512_max_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_max_ph (__m512h __A, __m512h __B) static
Definition at line 516 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
Referenced by _mm512_mask_max_ph(), and _mm512_maskz_max_ph().
_mm512_min_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_min_ph (__m512h __A, __m512h __B) static
Definition at line 483 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
Referenced by _mm512_mask_min_ph(), and _mm512_maskz_min_ph().
_mm512_mul_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_mul_ph (__m512h __A, __m512h __B) static
Definition at line 419 of file avx512fp16intrin.h.
Referenced by _mm512_mask_mul_ph(), and _mm512_maskz_mul_ph().
_mm512_permutex2var_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_permutex2var_ph (__m512h __A, __m512i __I, __m512h __B) static
Definition at line 3299 of file avx512fp16intrin.h.
_mm512_permutexvar_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_permutexvar_ph (__m512i __A, __m512h __B) static
Definition at line 3305 of file avx512fp16intrin.h.
_mm512_rcp_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_rcp_ph (__m512h __A) static
Definition at line 972 of file avx512fp16intrin.h.
References _mm512_undefined_ph().
_mm512_reduce_add_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_reduce_add_ph (__m512h __W) static
Definition at line 3273 of file avx512fp16intrin.h.
_mm512_reduce_max_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_reduce_max_ph (__m512h __V) static
Definition at line 3283 of file avx512fp16intrin.h.
_mm512_reduce_min_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_reduce_min_ph (__m512h __V) static
Definition at line 3288 of file avx512fp16intrin.h.
_mm512_reduce_mul_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS512 _mm512_reduce_mul_ph (__m512h __W) static
Definition at line 3278 of file avx512fp16intrin.h.
_mm512_rsqrt_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_rsqrt_ph (__m512h __A) static
Definition at line 989 of file avx512fp16intrin.h.
References _mm512_undefined_ph().
_mm512_scalef_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_scalef_ph (__m512h __A, __m512h __B) static
Definition at line 1070 of file avx512fp16intrin.h.
References _mm512_undefined_ph(), and _MM_FROUND_CUR_DIRECTION.
_mm512_set1_pch()
static __inline __m512h __DEFAULT_FN_ATTRS512 _mm512_set1_pch (_Float16 _Complex h) static
Definition at line 101 of file avx512fp16intrin.h.
References _mm512_set1_ps().
_mm512_set1_ph()
static __inline __m512h __DEFAULT_FN_ATTRS512 _mm512_set1_ph (_Float16 __h) static
Definition at line 69 of file avx512fp16intrin.h.
_mm512_set_ph()
static __inline __m512h __DEFAULT_FN_ATTRS512 _mm512_set_ph (_Float16 __h1, _Float16 __h2, _Float16 __h3, _Float16 __h4, _Float16 __h5, _Float16 __h6, _Float16 __h7, _Float16 __h8, _Float16 __h9, _Float16 __h10, _Float16 __h11, _Float16 __h12, _Float16 __h13, _Float16 __h14, _Float16 __h15, _Float16 __h16, _Float16 __h17, _Float16 __h18, _Float16 __h19, _Float16 __h20, _Float16 __h21, _Float16 __h22, _Float16 __h23, _Float16 __h24, _Float16 __h25, _Float16 __h26, _Float16 __h27, _Float16 __h28, _Float16 __h29, _Float16 __h30, _Float16 __h31, _Float16 __h32) static
Definition at line 77 of file avx512fp16intrin.h.
_mm512_setzero_ph()
static __inline __m512h __DEFAULT_FN_ATTRS512 _mm512_setzero_ph (void) static
Definition at line 55 of file avx512fp16intrin.h.
Referenced by _mm512_cvtepi16_ph(), _mm512_cvtepu16_ph(), _mm512_maskz_add_ph(), _mm512_maskz_cvtepi16_ph(), _mm512_maskz_cvtepu16_ph(), _mm512_maskz_div_ph(), _mm512_maskz_fcmul_pch(), _mm512_maskz_fmul_pch(), _mm512_maskz_getexp_ph(), _mm512_maskz_max_ph(), _mm512_maskz_min_ph(), _mm512_maskz_mul_ph(), _mm512_maskz_rcp_ph(), _mm512_maskz_rsqrt_ph(), _mm512_maskz_scalef_ph(), _mm512_maskz_sqrt_ph(), and _mm512_maskz_sub_ph().
_mm512_sqrt_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_sqrt_ph (__m512h __A) static
Definition at line 1382 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm512_store_ph()
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_store_ph (void * __P, __m512h __A) static
Definition at line 902 of file avx512fp16intrin.h.
References __P.
_mm512_storeu_ph()
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_storeu_ph (void * __P, __m512h __A) static
Definition at line 917 of file avx512fp16intrin.h.
References __P, and __v.
_mm512_sub_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_sub_ph (__m512h __A, __m512h __B) static
Definition at line 387 of file avx512fp16intrin.h.
Referenced by _mm512_mask_sub_ph(), and _mm512_maskz_sub_ph().
_mm512_undefined_ph()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_undefined_ph (void) static
Definition at line 65 of file avx512fp16intrin.h.
Referenced by _mm512_fcmul_pch(), _mm512_fmul_pch(), _mm512_getexp_ph(), _mm512_rcp_ph(), _mm512_rsqrt_ph(), and _mm512_scalef_ph().
_mm512_zextph128_ph512()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_zextph128_ph512 (__m128h __a) static
Constructs a 512-bit floating-point vector of [32 x half] from a 128-bit floating-point vector of [8 x half].
The lower 128 bits contain the value of the source vector. The upper 384 bits are set to zero.
This intrinsic has no corresponding instruction.
Parameters
__a A 128-bit vector of [8 x half].
Returns
A 512-bit floating-point vector of [32 x half]. The lower 128 bits contain the value of the parameter. The upper 384 bits are set to zero.
Definition at line 250 of file avx512fp16intrin.h.
References __a, and _mm_setzero_ph().
_mm512_zextph256_ph512()
static __inline__ __m512h __DEFAULT_FN_ATTRS512 _mm512_zextph256_ph512 (__m256h __a) static
Constructs a 512-bit floating-point vector of [32 x half] from a 256-bit floating-point vector of [16 x half].
The lower 256 bits contain the value of the source vector. The upper 256 bits are set to zero.
This intrinsic has no corresponding instruction.
Parameters
__a A 256-bit vector of [16 x half].
Returns
A 512-bit floating-point vector of [32 x half]. The lower 256 bits contain the value of the parameter. The upper 256 bits are set to zero.
Definition at line 270 of file avx512fp16intrin.h.
References __a, and _mm256_setzero_ph().
_mm_add_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_add_sh (__m128h __A, __m128h __B) static
Definition at line 570 of file avx512fp16intrin.h.
Referenced by _mm_mask_add_sh(), and _mm_maskz_add_sh().
_mm_castpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_castpd_ph (__m128d __a) static
Definition at line 155 of file avx512fp16intrin.h.
References __a.
_mm_castph_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_castph_pd (__m128h __a) static
Definition at line 117 of file avx512fp16intrin.h.
References __a.
_mm_castph_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_castph_ps (__m128h __a) static
Definition at line 105 of file avx512fp16intrin.h.
References __a.
_mm_castph_si128()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_castph_si128 (__m128h __a) static
Definition at line 129 of file avx512fp16intrin.h.
References __a.
_mm_castps_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_castps_ph (__m128 __a) static
Definition at line 143 of file avx512fp16intrin.h.
References __a.
_mm_castsi128_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_castsi128_ph (__m128i __a) static
Definition at line 167 of file avx512fp16intrin.h.
References __a.
_mm_comieq_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comieq_sh (__m128h A, __m128h B) static
Definition at line 283 of file avx512fp16intrin.h.
References _CMP_EQ_OS, and _MM_FROUND_CUR_DIRECTION.
_mm_comige_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comige_sh (__m128h A, __m128h B) static
Definition at line 307 of file avx512fp16intrin.h.
References _CMP_GE_OS, and _MM_FROUND_CUR_DIRECTION.
_mm_comigt_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comigt_sh (__m128h A, __m128h B) static
Definition at line 301 of file avx512fp16intrin.h.
References _CMP_GT_OS, and _MM_FROUND_CUR_DIRECTION.
_mm_comile_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comile_sh (__m128h A, __m128h B) static
Definition at line 295 of file avx512fp16intrin.h.
References _CMP_LE_OS, and _MM_FROUND_CUR_DIRECTION.
_mm_comilt_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comilt_sh (__m128h A, __m128h B) static
Definition at line 289 of file avx512fp16intrin.h.
References _CMP_LT_OS, and _MM_FROUND_CUR_DIRECTION.
_mm_comineq_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_comineq_sh (__m128h A, __m128h B) static
Definition at line 313 of file avx512fp16intrin.h.
References _CMP_NEQ_US, and _MM_FROUND_CUR_DIRECTION.
_mm_cvti32_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvti32_sh (__m128h __A, int __B) static
Definition at line 2329 of file avx512fp16intrin.h.
_mm_cvtsd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtsd_sh (__m128h __A, __m128d __B) static
Definition at line 1610 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_undefined_ph().
_mm_cvtsh_i32()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_cvtsh_i32 (__m128h __A) static
Definition at line 2273 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_cvtsh_sd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_cvtsh_sd (__m128d __A, __m128h __B) static
Definition at line 1647 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_undefined_pd().
_mm_cvtsh_ss()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_cvtsh_ss (__m128 __A, __m128h __B) static
Definition at line 1534 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_undefined_ps().
_mm_cvtsh_u32()
static __inline__ unsigned int __DEFAULT_FN_ATTRS128 _mm_cvtsh_u32 (__m128h __A) static
Definition at line 2281 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_cvtsi128_si16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_cvtsi128_si16 (__m128i __a) static
Definition at line 967 of file avx512fp16intrin.h.
References __a, and __b.
_mm_cvtsi16_si128()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtsi16_si128 (short __a) static
Definition at line 963 of file avx512fp16intrin.h.
References __a.
_mm_cvtss_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtss_sh (__m128h __A, __m128 __B) static
Definition at line 1572 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_undefined_ph().
_mm_cvttsh_i32()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_cvttsh_i32 (__m128h __A) static
Definition at line 2349 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_cvttsh_u32()
static __inline__ unsigned int __DEFAULT_FN_ATTRS128 _mm_cvttsh_u32 (__m128h __A) static
Definition at line 2368 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_cvtu32_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtu32_sh (__m128h __A, unsigned int __B) static
Definition at line 2309 of file avx512fp16intrin.h.
_mm_div_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_div_sh (__m128h __A, __m128h __B) static
Definition at line 678 of file avx512fp16intrin.h.
Referenced by _mm_mask_div_sh(), and _mm_maskz_div_sh().
_mm_fcmadd_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fcmadd_sch (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 2934 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_fcmul_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fcmul_sch (__m128h __A, __m128h __B) static
Definition at line 3028 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_undefined_ph().
_mm_fmadd_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmadd_sch (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 2981 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_fmadd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmadd_sh (__m128h __W, __m128h __A, __m128h __B) static
Definition at line 2740 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_fmsub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmsub_sh (__m128h __W, __m128h __A, __m128h __B) static
Definition at line 2789 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_fmul_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmul_sch (__m128h __A, __m128h __B) static
Definition at line 3064 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_undefined_ph().
_mm_fnmadd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fnmadd_sh (__m128h __W, __m128h __A, __m128h __B) static
Definition at line 2840 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_fnmsub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fnmsub_sh (__m128h __W, __m128h __A, __m128h __B) static
Definition at line 2887 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_getexp_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_getexp_sh (__m128h __A, __m128h __B) static
Definition at line 1242 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_load_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_load_ph (void const * __p) static
Definition at line 860 of file avx512fp16intrin.h.
References __p.
_mm_load_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_load_sh (void const * __dp) static
Definition at line 828 of file avx512fp16intrin.h.
References _Float16.
_mm_loadu_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_loadu_ph (void const * __p) static
Definition at line 880 of file avx512fp16intrin.h.
References __p, and __v.
_mm_mask3_fcmadd_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fcmadd_sch (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 2956 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask3_fmadd_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmadd_sch (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 3003 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask3_fmadd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmadd_sh (__m128h __W, __m128h __X, __m128h __Y, __mmask8 __U) static
Definition at line 2778 of file avx512fp16intrin.h.
References __Y, and _MM_FROUND_CUR_DIRECTION.
_mm_mask3_fmsub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmsub_sh (__m128h __W, __m128h __X, __m128h __Y, __mmask8 __U) static
Definition at line 2829 of file avx512fp16intrin.h.
References __Y, and _MM_FROUND_CUR_DIRECTION.
_mm_mask3_fnmadd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fnmadd_sh (__m128h __W, __m128h __X, __m128h __Y, __mmask8 __U) static
Definition at line 2876 of file avx512fp16intrin.h.
References __Y, and _MM_FROUND_CUR_DIRECTION.
_mm_mask3_fnmsub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fnmsub_sh (__m128h __W, __m128h __X, __m128h __Y, __mmask8 __U) static
Definition at line 2923 of file avx512fp16intrin.h.
References __Y, and _MM_FROUND_CUR_DIRECTION.
_mm_mask_add_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_add_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 576 of file avx512fp16intrin.h.
References _mm_add_sh().
_mm_mask_cvtsd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtsd_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128d __B) static
Definition at line 1617 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_cvtsh_sd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_cvtsh_sd (__m128d __W, __mmask8 __U, __m128d __A, __m128h __B) static
Definition at line 1654 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_cvtsh_ss()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_cvtsh_ss (__m128 __W, __mmask8 __U, __m128 __A, __m128h __B) static
Definition at line 1541 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_cvtss_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtss_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128 __B) static
Definition at line 1579 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_div_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_div_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 684 of file avx512fp16intrin.h.
References _mm_div_sh().
_mm_mask_fcmadd_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fcmadd_sch (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 2943 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_fcmul_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fcmul_sch (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 3036 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_fmadd_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmadd_sch (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 2990 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_fmadd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmadd_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 2747 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_fmsub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmsub_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 2797 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_fmul_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmul_sch (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 3071 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_fnmadd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fnmadd_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 2848 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_fnmsub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fnmsub_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 2895 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_getexp_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_getexp_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1250 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_load_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_load_sh (__m128h __W, __mmask8 __U, const void * __A) static
Definition at line 837 of file avx512fp16intrin.h.
References _mm_setzero_ph().
_mm_mask_max_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_max_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 760 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_min_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_min_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 721 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_move_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_move_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 948 of file avx512fp16intrin.h.
References _mm_move_sh().
_mm_mask_mul_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_mul_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 648 of file avx512fp16intrin.h.
References _mm_mul_sh().
_mm_mask_rcp_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_rcp_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1172 of file avx512fp16intrin.h.
_mm_mask_rsqrt_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_rsqrt_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1193 of file avx512fp16intrin.h.
_mm_mask_scalef_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_scalef_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1286 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_sqrt_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_sqrt_sh (__m128h __W, __mmask32 __U, __m128h __A, __m128h __B) static
Definition at line 1425 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_mask_store_sh()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_store_sh (void * __W, __mmask8 __U, __m128h __A) static
Definition at line 896 of file avx512fp16intrin.h.
_mm_mask_sub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_sub_sh (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 612 of file avx512fp16intrin.h.
References _mm_sub_sh().
_mm_maskz_add_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_add_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 584 of file avx512fp16intrin.h.
References _mm_add_sh(), and _mm_setzero_ph().
_mm_maskz_cvtsd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtsd_sh (__mmask8 __U, __m128h __A, __m128d __B) static
Definition at line 1627 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_cvtsh_sd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_cvtsh_sd (__mmask8 __U, __m128d __A, __m128h __B) static
Definition at line 1664 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_pd().
_mm_maskz_cvtsh_ss()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_cvtsh_ss (__mmask8 __U, __m128 __A, __m128h __B) static
Definition at line 1550 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ps().
_mm_maskz_cvtss_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtss_sh (__mmask8 __U, __m128h __A, __m128 __B) static
Definition at line 1588 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_div_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_div_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 692 of file avx512fp16intrin.h.
References _mm_div_sh(), and _mm_setzero_ph().
_mm_maskz_fcmadd_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fcmadd_sch (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 2949 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_maskz_fcmul_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fcmul_sch (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 3043 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_fmadd_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmadd_sch (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 2996 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_maskz_fmadd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmadd_sh (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 2766 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_maskz_fmsub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmsub_sh (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 2817 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_maskz_fmul_sch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmul_sch (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 3081 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_fnmadd_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fnmadd_sh (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 2864 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_maskz_fnmsub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fnmsub_sh (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 2911 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION.
_mm_maskz_getexp_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_getexp_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1262 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_load_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_load_sh (__mmask8 __U, const void * __A) static
Definition at line 845 of file avx512fp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_max_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_max_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 769 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_min_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_min_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 730 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_move_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_move_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 955 of file avx512fp16intrin.h.
References _mm_move_sh(), and _mm_setzero_ph().
_mm_maskz_mul_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_mul_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 656 of file avx512fp16intrin.h.
References _mm_mul_sh(), and _mm_setzero_ph().
_mm_maskz_rcp_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_rcp_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1180 of file avx512fp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_rsqrt_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_rsqrt_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1202 of file avx512fp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_scalef_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_scalef_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1298 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_sqrt_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_sqrt_sh (__mmask32 __U, __m128h __A, __m128h __B) static
Definition at line 1434 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_maskz_sub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_sub_sh (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 620 of file avx512fp16intrin.h.
References _mm_setzero_ph(), and _mm_sub_sh().
_mm_max_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_max_sh (__m128h __A, __m128h __B) static
Definition at line 753 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_min_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_min_sh (__m128h __A, __m128h __B) static
Definition at line 714 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_move_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_move_sh (__m128h __a, __m128h __b) static
Definition at line 942 of file avx512fp16intrin.h.
References __a, and __b.
Referenced by _mm_mask_move_sh(), and _mm_maskz_move_sh().
_mm_mul_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mul_sh (__m128h __A, __m128h __B) static
Definition at line 642 of file avx512fp16intrin.h.
Referenced by _mm_mask_mul_sh(), and _mm_maskz_mul_sh().
_mm_rcp_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_rcp_sh (__m128h __A, __m128h __B) static
Definition at line 1166 of file avx512fp16intrin.h.
References _mm_setzero_ph().
_mm_rsqrt_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_rsqrt_sh (__m128h __A, __m128h __B) static
Definition at line 1187 of file avx512fp16intrin.h.
References _mm_setzero_ph().
_mm_scalef_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_scalef_sh (__m128h __A, __m128h __B) static
Definition at line 1278 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_setzero_ph()
static __inline __m128h __DEFAULT_FN_ATTRS128 _mm_setzero_ph (void) static
Definition at line 42 of file avx512fp16intrin.h.
Referenced by _mm256_maskz_cvtepi32_ph(), _mm256_maskz_cvtepi64_ph(), _mm256_maskz_cvtepu32_ph(), _mm256_maskz_cvtepu64_ph(), _mm256_maskz_cvtpd_ph(), _mm256_maskz_cvtxps_ph(), _mm256_zextph128_ph256(), _mm512_cvtepi64_ph(), _mm512_cvtepu64_ph(), _mm512_cvtpd_ph(), _mm512_maskz_cvtepi64_ph(), _mm512_maskz_cvtepu64_ph(), _mm512_maskz_cvtpd_ph(), _mm512_zextph128_ph512(), _mm_getexp_ph(), _mm_getexp_sh(), _mm_mask_load_sh(), _mm_maskz_add_ph(), _mm_maskz_add_sh(), _mm_maskz_cvtepi16_ph(), _mm_maskz_cvtepi32_ph(), _mm_maskz_cvtepi64_ph(), _mm_maskz_cvtepu16_ph(), _mm_maskz_cvtepu32_ph(), _mm_maskz_cvtepu64_ph(), _mm_maskz_cvtpd_ph(), _mm_maskz_cvtsd_sh(), _mm_maskz_cvtss_sh(), _mm_maskz_cvtxps_ph(), _mm_maskz_div_ph(), _mm_maskz_div_sh(), _mm_maskz_fcmul_pch(), _mm_maskz_fcmul_sch(), _mm_maskz_fmadd_ph(), _mm_maskz_fmaddsub_ph(), _mm_maskz_fmsub_ph(), _mm_maskz_fmsubadd_ph(), _mm_maskz_fmul_pch(), _mm_maskz_fmul_sch(), _mm_maskz_fnmadd_ph(), _mm_maskz_fnmsub_ph(), _mm_maskz_getexp_ph(), _mm_maskz_getexp_sh(), _mm_maskz_load_sh(), _mm_maskz_max_ph(), _mm_maskz_max_sh(), _mm_maskz_min_ph(), _mm_maskz_min_sh(), _mm_maskz_move_sh(), _mm_maskz_mul_ph(), _mm_maskz_mul_sh(), _mm_maskz_rcp_ph(), _mm_maskz_rcp_sh(), _mm_maskz_rsqrt_ph(), _mm_maskz_rsqrt_sh(), _mm_maskz_scalef_ph(), _mm_maskz_scalef_sh(), _mm_maskz_sqrt_ph(), _mm_maskz_sqrt_sh(), _mm_maskz_sub_ph(), _mm_maskz_sub_sh(), _mm_max_sh(), _mm_min_sh(), _mm_rcp_sh(), _mm_rsqrt_sh(), _mm_scalef_ph(), _mm_scalef_sh(), and _mm_sqrt_sh().
_mm_sqrt_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_sqrt_sh (__m128h __A, __m128h __B) static
Definition at line 1418 of file avx512fp16intrin.h.
References _MM_FROUND_CUR_DIRECTION, and _mm_setzero_ph().
_mm_store_ph()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_store_ph (void * __P, __m128h __A) static
Definition at line 912 of file avx512fp16intrin.h.
References __P.
_mm_store_sh()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_store_sh (void * __dp, __m128h __a) static
Definition at line 888 of file avx512fp16intrin.h.
References __a, and _Float16.
_mm_storeu_ph()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_storeu_ph (void * __P, __m128h __A) static
Definition at line 933 of file avx512fp16intrin.h.
References __P, and __v.
_mm_sub_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_sub_sh (__m128h __A, __m128h __B) static
Definition at line 606 of file avx512fp16intrin.h.
Referenced by _mm_mask_sub_sh(), and _mm_maskz_sub_sh().
_mm_ucomieq_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomieq_sh (__m128h A, __m128h B) static
Definition at line 319 of file avx512fp16intrin.h.
References _CMP_EQ_OQ, and _MM_FROUND_CUR_DIRECTION.
_mm_ucomige_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomige_sh (__m128h A, __m128h B) static
Definition at line 343 of file avx512fp16intrin.h.
References _CMP_GE_OQ, and _MM_FROUND_CUR_DIRECTION.
_mm_ucomigt_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomigt_sh (__m128h A, __m128h B) static
Definition at line 337 of file avx512fp16intrin.h.
References _CMP_GT_OQ, and _MM_FROUND_CUR_DIRECTION.
_mm_ucomile_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomile_sh (__m128h A, __m128h B) static
Definition at line 331 of file avx512fp16intrin.h.
References _CMP_LE_OQ, and _MM_FROUND_CUR_DIRECTION.
_mm_ucomilt_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomilt_sh (__m128h A, __m128h B) static
Definition at line 325 of file avx512fp16intrin.h.
References _CMP_LT_OQ, and _MM_FROUND_CUR_DIRECTION.
_mm_ucomineq_sh()
static __inline__ int __DEFAULT_FN_ATTRS128 _mm_ucomineq_sh (__m128h A, __m128h B) static
Definition at line 349 of file avx512fp16intrin.h.
References _CMP_NEQ_UQ, and _MM_FROUND_CUR_DIRECTION.
_mm_undefined_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_undefined_ph (void) static
Definition at line 61 of file avx512fp16intrin.h.
Referenced by _mm256_cvtepi64_ph(), _mm256_cvtepu64_ph(), _mm256_cvtpd_ph(), _mm256_cvtxps_ph(), _mm_cvtepi32_ph(), _mm_cvtepi64_ph(), _mm_cvtepu32_ph(), _mm_cvtepu64_ph(), _mm_cvtpd_ph(), _mm_cvtsd_sh(), _mm_cvtss_sh(), _mm_cvtxps_ph(), _mm_fcmul_pch(), _mm_fcmul_sch(), _mm_fmul_pch(), _mm_fmul_sch(), _mm_rcp_ph(), and _mm_rsqrt_ph().