clang: lib/Headers/avx512vlfp16intrin.h File Reference
avx512vlfp16intrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS128
#define _mm_setr_ph(h1, h2, h3, h4, h5, h6, h7, h8) _mm_set_ph((h8), (h7), (h6), (h5), (h4), (h3), (h2), (h1))
#define _mm256_setr_ph(h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14, h15, h16)
#define _mm256_cmp_ph_mask(a, b, p)
#define _mm256_mask_cmp_ph_mask(m, a, b, p)
#define _mm_cmp_ph_mask(a, b, p)
#define _mm_mask_cmp_ph_mask(m, a, b, p)
#define _mm_getmant_ph(A, B, C)
#define _mm_mask_getmant_ph(W, U, A, B, C)
#define _mm_maskz_getmant_ph(U, A, B, C)
#define _mm256_getmant_ph(A, B, C)
#define _mm256_mask_getmant_ph(W, U, A, B, C)
#define _mm256_maskz_getmant_ph(U, A, B, C)
#define _mm_roundscale_ph(A, imm)
#define _mm_mask_roundscale_ph(W, U, A, imm)
#define _mm_maskz_roundscale_ph(U, A, imm)
#define _mm256_roundscale_ph(A, imm)
#define _mm256_mask_roundscale_ph(W, U, A, imm)
#define _mm256_maskz_roundscale_ph(U, A, imm)
#define _mm_reduce_ph(A, imm)
#define _mm_mask_reduce_ph(W, U, A, imm)
#define _mm_maskz_reduce_ph(U, A, imm)
#define _mm256_reduce_ph(A, imm)
#define _mm256_mask_reduce_ph(W, U, A, imm)
#define _mm256_maskz_reduce_ph(U, A, imm)
#define _mm_mask_fpclass_ph_mask(U, A, imm)
#define _mm_fpclass_ph_mask(A, imm)
#define _mm256_mask_fpclass_ph_mask(U, A, imm)
#define _mm256_fpclass_ph_mask(A, imm)
#define _mm_mul_pch(A, B) _mm_fmul_pch(A, B)
#define _mm_mask_mul_pch(W, U, A, B) _mm_mask_fmul_pch(W, U, A, B)
#define _mm_maskz_mul_pch(U, A, B) _mm_maskz_fmul_pch(U, A, B)
#define _mm256_mul_pch(A, B) _mm256_fmul_pch(A, B)
#define _mm256_mask_mul_pch(W, U, A, B) _mm256_mask_fmul_pch(W, U, A, B)
#define _mm256_maskz_mul_pch(U, A, B) _mm256_maskz_fmul_pch(U, A, B)
#define _mm_cmul_pch(A, B) _mm_fcmul_pch(A, B)
#define _mm_mask_cmul_pch(W, U, A, B) _mm_mask_fcmul_pch(W, U, A, B)
#define _mm_maskz_cmul_pch(U, A, B) _mm_maskz_fcmul_pch(U, A, B)
#define _mm256_cmul_pch(A, B) _mm256_fcmul_pch(A, B)
#define _mm256_mask_cmul_pch(W, U, A, B) _mm256_mask_fcmul_pch(W, U, A, B)
#define _mm256_maskz_cmul_pch(U, A, B) _mm256_maskz_fcmul_pch(U, A, B)
Functions
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_cvtsh_h (__m128h __a)
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_cvtsh_h (__m256h __a)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_set_sh (_Float16 __h)
static __inline __m128h __DEFAULT_FN_ATTRS128 _mm_set1_ph (_Float16 __h)
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_set1_ph (_Float16 __h)
static __inline __m128h __DEFAULT_FN_ATTRS128 _mm_set_ph (_Float16 __h1, _Float16 __h2, _Float16 __h3, _Float16 __h4, _Float16 __h5, _Float16 __h6, _Float16 __h7, _Float16 __h8)
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_set1_pch (_Float16 _Complex h)
static __inline __m128h __DEFAULT_FN_ATTRS128 _mm_set1_pch (_Float16 _Complex h)
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_set_ph (_Float16 __h1, _Float16 __h2, _Float16 __h3, _Float16 __h4, _Float16 __h5, _Float16 __h6, _Float16 __h7, _Float16 __h8, _Float16 __h9, _Float16 __h10, _Float16 __h11, _Float16 __h12, _Float16 __h13, _Float16 __h14, _Float16 __h15, _Float16 __h16)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_add_ph (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_add_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_add_ph (__mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_add_ph (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_add_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_add_ph (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_sub_ph (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_sub_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_sub_ph (__mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_sub_ph (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_sub_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_sub_ph (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mul_ph (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_mul_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_mul_ph (__mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mul_ph (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_mul_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_mul_ph (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_div_ph (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_div_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_div_ph (__mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_div_ph (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_div_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_div_ph (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_min_ph (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_min_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_min_ph (__mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_min_ph (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_min_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_min_ph (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_max_ph (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_max_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_max_ph (__mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_max_ph (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_max_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_max_ph (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_abs_ph (__m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_abs_ph (__m128h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_conj_pch (__m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_conj_pch (__m256h __W, __mmask8 __U, __m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_conj_pch (__mmask8 __U, __m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_conj_pch (__m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_conj_pch (__m128h __W, __mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_conj_pch (__mmask8 __U, __m128h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_rcp_ph (__m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_rcp_ph (__m256h __W, __mmask16 __U, __m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_rcp_ph (__mmask16 __U, __m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_rcp_ph (__m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_rcp_ph (__m128h __W, __mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_rcp_ph (__mmask8 __U, __m128h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_rsqrt_ph (__m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_rsqrt_ph (__m256h __W, __mmask16 __U, __m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_rsqrt_ph (__mmask16 __U, __m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_rsqrt_ph (__m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_rsqrt_ph (__m128h __W, __mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_rsqrt_ph (__mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_getexp_ph (__m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_getexp_ph (__m128h __W, __mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_getexp_ph (__mmask8 __U, __m128h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_getexp_ph (__m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_getexp_ph (__m256h __W, __mmask16 __U, __m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_getexp_ph (__mmask16 __U, __m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_scalef_ph (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_scalef_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_scalef_ph (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_scalef_ph (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_scalef_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_scalef_ph (__mmask16 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_sqrt_ph (__m128h __a)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_sqrt_ph (__m128h __W, __mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_sqrt_ph (__mmask8 __U, __m128h __A)
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_sqrt_ph (__m256h __a)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_sqrt_ph (__m256h __W, __mmask16 __U, __m256h __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_sqrt_ph (__mmask16 __U, __m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtpd_ph (__m128d __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtpd_ph (__m128h __W, __mmask8 __U, __m128d __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtpd_ph (__mmask8 __U, __m128d __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtpd_ph (__m256d __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtpd_ph (__m128h __W, __mmask8 __U, __m256d __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtpd_ph (__mmask8 __U, __m256d __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_cvtph_pd (__m128h __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_pd (__m128d __W, __mmask8 __U, __m128h __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_pd (__mmask8 __U, __m128h __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_cvtph_pd (__m128h __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_pd (__m256d __W, __mmask8 __U, __m128h __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_pd (__mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epi16 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epi16 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epi16 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epi16 (__m256h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epi16 (__m256i __W, __mmask16 __U, __m256h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epi16 (__mmask16 __U, __m256h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epi16 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epi16 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epi16 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epi16 (__m256h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epi16 (__m256i __W, __mmask16 __U, __m256h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epi16 (__mmask16 __U, __m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepi16_ph (__m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi16_ph (__m128h __W, __mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi16_ph (__mmask8 __U, __m128i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_cvtepi16_ph (__m256i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi16_ph (__m256h __W, __mmask16 __U, __m256i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi16_ph (__mmask16 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epu16 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epu16 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epu16 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epu16 (__m256h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epu16 (__m256i __W, __mmask16 __U, __m256h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epu16 (__mmask16 __U, __m256h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epu16 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epu16 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epu16 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epu16 (__m256h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epu16 (__m256i __W, __mmask16 __U, __m256h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epu16 (__mmask16 __U, __m256h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepu16_ph (__m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu16_ph (__m128h __W, __mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu16_ph (__mmask8 __U, __m128i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_cvtepu16_ph (__m256i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu16_ph (__m256h __W, __mmask16 __U, __m256i __A)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu16_ph (__mmask16 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epi32 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epi32 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epi32 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epi32 (__m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epi32 (__m256i __W, __mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epi32 (__mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epu32 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epu32 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epu32 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epu32 (__m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epu32 (__m256i __W, __mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epu32 (__mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepi32_ph (__m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi32_ph (__m128h __W, __mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi32_ph (__mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtepi32_ph (__m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi32_ph (__m128h __W, __mmask8 __U, __m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi32_ph (__mmask8 __U, __m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepu32_ph (__m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu32_ph (__m128h __W, __mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu32_ph (__mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtepu32_ph (__m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu32_ph (__m128h __W, __mmask8 __U, __m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu32_ph (__mmask8 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epi32 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epi32 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epi32 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epi32 (__m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epi32 (__m256i __W, __mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epi32 (__mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epu32 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epu32 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epu32 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epu32 (__m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epu32 (__m256i __W, __mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epu32 (__mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepi64_ph (__m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi64_ph (__m128h __W, __mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi64_ph (__mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtepi64_ph (__m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi64_ph (__m128h __W, __mmask8 __U, __m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi64_ph (__mmask8 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epi64 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epi64 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epi64 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epi64 (__m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epi64 (__m256i __W, __mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epi64 (__mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepu64_ph (__m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu64_ph (__m128h __W, __mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu64_ph (__mmask8 __U, __m128i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtepu64_ph (__m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu64_ph (__m128h __W, __mmask8 __U, __m256i __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu64_ph (__mmask8 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epu64 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epu64 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epu64 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epu64 (__m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epu64 (__m256i __W, __mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epu64 (__mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epi64 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epi64 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epi64 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epi64 (__m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epi64 (__m256i __W, __mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epi64 (__mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epu64 (__m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epu64 (__m128i __W, __mmask8 __U, __m128h __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epu64 (__mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epu64 (__m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epu64 (__m256i __W, __mmask8 __U, __m128h __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epu64 (__mmask8 __U, __m128h __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_cvtxph_ps (__m128h __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_cvtxph_ps (__m128 __W, __mmask8 __U, __m128h __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_cvtxph_ps (__mmask8 __U, __m128h __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_cvtxph_ps (__m128h __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_cvtxph_ps (__m256 __W, __mmask8 __U, __m128h __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtxph_ps (__mmask8 __U, __m128h __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtxps_ph (__m128 __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtxps_ph (__m128h __W, __mmask8 __U, __m128 __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtxps_ph (__mmask8 __U, __m128 __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtxps_ph (__m256 __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtxps_ph (__m128h __W, __mmask8 __U, __m256 __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtxps_ph (__mmask8 __U, __m256 __A)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmadd_ph (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmadd_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmadd_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmadd_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmsub_ph (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmsub_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmsub_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fnmadd_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fnmadd_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fnmsub_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmadd_ph (__m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmadd_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmadd_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmadd_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmsub_ph (__m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmsub_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmsub_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fnmadd_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fnmadd_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fnmsub_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmaddsub_ph (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmaddsub_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmaddsub_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmaddsub_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmsubadd_ph (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmsubadd_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmsubadd_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmaddsub_ph (__m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmaddsub_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmaddsub_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmaddsub_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmsubadd_ph (__m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmsubadd_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmsubadd_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmsub_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmsub_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmsubadd_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmsubadd_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fnmadd_ph (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fnmadd_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fnmadd_ph (__m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fnmadd_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fnmsub_ph (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fnmsub_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fnmsub_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fnmsub_ph (__m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fnmsub_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fnmsub_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fcmul_pch (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fcmul_pch (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fcmul_pch (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS128 _mm256_fcmul_pch (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fcmul_pch (__m256h __W, __mmask8 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fcmul_pch (__mmask8 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fcmadd_pch (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fcmadd_pch (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fcmadd_pch (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fcmadd_pch (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fcmadd_pch (__m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fcmadd_pch (__m256h __A, __mmask8 __U, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fcmadd_pch (__m256h __A, __m256h __B, __m256h __C, __mmask8 __U)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fcmadd_pch (__mmask8 __U, __m256h __A, __m256h __B, __m256h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmul_pch (__m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmul_pch (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmul_pch (__mmask8 __U, __m128h __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmul_pch (__m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmul_pch (__m256h __W, __mmask8 __U, __m256h __A, __m256h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmul_pch (__mmask8 __U, __m256h __A, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmadd_pch (__m128h __A, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmadd_pch (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmadd_pch (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmadd_pch (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmadd_pch (__m256h __A, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmadd_pch (__m256h __A, __mmask8 __U, __m256h __B, __m256h __C)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmadd_pch (__m256h __A, __m256h __B, __m256h __C, __mmask8 __U)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmadd_pch (__mmask8 __U, __m256h __A, __m256h __B, __m256h __C)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_blend_ph (__mmask8 __U, __m128h __A, __m128h __W)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_blend_ph (__mmask16 __U, __m256h __A, __m256h __W)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_permutex2var_ph (__m128h __A, __m128i __I, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_permutex2var_ph (__m256h __A, __m256i __I, __m256h __B)
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_permutexvar_ph (__m128i __A, __m128h __B)
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_permutexvar_ph (__m256i __A, __m256h __B)
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_reduce_add_ph (__m256h __W)
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_reduce_mul_ph (__m256h __W)
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_reduce_max_ph (__m256h __V)
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_reduce_min_ph (__m256h __V)
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_reduce_add_ph (__m128h __W)
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_reduce_mul_ph (__m128h __W)
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_reduce_max_ph (__m128h __V)
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_reduce_min_ph (__m128h __V)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128
Value:
  __attribute__((__always_inline__, __nodebug__,                               \
                 __target__("avx512fp16, avx512vl"),                           \
                 __min_vector_width__(128)))
Definition at line 22 of file avx512vlfp16intrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256
Value:
  __attribute__((__always_inline__, __nodebug__,                               \
                 __target__("avx512fp16, avx512vl"),                           \
                 __min_vector_width__(256)))
Definition at line 18 of file avx512vlfp16intrin.h.
_mm256_cmp_ph_mask
#define _mm256_cmp_ph_mask (a, b, p)
Value:
  ((__mmask16)__builtin_ia32_cmpph256_mask(                                    \
      (__v16hf)(__m256h)(a), (__v16hf)(__m256h)(b), (int)(p), (__mmask16)-1))
Definition at line 357 of file avx512vlfp16intrin.h.
_mm256_cmul_pch
#define _mm256_cmul_pch (A, B) _mm256_fcmul_pch(A, B)
Definition at line 2061 of file avx512vlfp16intrin.h.
_mm256_fpclass_ph_mask
#define _mm256_fpclass_ph_mask (A, imm)
Value:
  ((__mmask16)__builtin_ia32_fpclassph256_mask((__v16hf)(__m256h)(A),          \
                                               (int)(imm), (__mmask16)-1))
Definition at line 647 of file avx512vlfp16intrin.h.
_mm256_getmant_ph
#define _mm256_getmant_ph (A, B, C)
Value:
  ((__m256h)__builtin_ia32_getmantph256_mask(                                  \
      (__v16hf)(__m256h)(A), (int)(((C) << 2) | (B)),                          \
      (__v16hf)_mm256_setzero_ph(), (__mmask16)-1))
Definition at line 492 of file avx512vlfp16intrin.h.
_mm256_mask_cmp_ph_mask
#define _mm256_mask_cmp_ph_mask (m, a, b, p)
Value:
  ((__mmask16)__builtin_ia32_cmpph256_mask(                                    \
      (__v16hf)(__m256h)(a), (__v16hf)(__m256h)(b), (int)(p), (__mmask16)(m)))
Definition at line 361 of file avx512vlfp16intrin.h.
_mm256_mask_cmul_pch
#define _mm256_mask_cmul_pch (W, U, A, B) _mm256_mask_fcmul_pch(W, U, A, B)
Definition at line 2062 of file avx512vlfp16intrin.h.
_mm256_mask_fpclass_ph_mask
#define _mm256_mask_fpclass_ph_mask (U, A, imm)
Value:
  ((__mmask16)__builtin_ia32_fpclassph256_mask((__v16hf)(__m256h)(A),          \
                                               (int)(imm), (__mmask16)(U)))
Definition at line 643 of file avx512vlfp16intrin.h.
_mm256_mask_getmant_ph
#define _mm256_mask_getmant_ph (W, U, A, B, C)
Value:
  ((__m256h)__builtin_ia32_getmantph256_mask(                                  \
      (__v16hf)(__m256h)(A), (int)(((C) << 2) | (B)), (__v16hf)(__m256h)(W),   \
      (__mmask16)(U)))
Definition at line 497 of file avx512vlfp16intrin.h.
_mm256_mask_mul_pch
#define _mm256_mask_mul_pch (W, U, A, B) _mm256_mask_fmul_pch(W, U, A, B)
Definition at line 2055 of file avx512vlfp16intrin.h.
_mm256_mask_reduce_ph
#define _mm256_mask_reduce_ph (W, U, A, imm)
Value:
  ((__m256h)__builtin_ia32_reduceph256_mask((__v16hf)(__m256h)(A), (int)(imm), \
                                            (__v16hf)(__m256h)(W),             \
                                            (__mmask16)(U)))
Definition at line 591 of file avx512vlfp16intrin.h.
_mm256_mask_roundscale_ph
#define _mm256_mask_roundscale_ph (W, U, A, imm)
Value:
  ((__m256h)__builtin_ia32_rndscaleph_256_mask(                                \
      (__v16hf)(__m256h)(A), (int)(imm), (__v16hf)(__m256h)(W),                \
      (__mmask16)(U)))
Definition at line 562 of file avx512vlfp16intrin.h.
_mm256_maskz_cmul_pch
#define _mm256_maskz_cmul_pch (U, A, B) _mm256_maskz_fcmul_pch(U, A, B)
Definition at line 2063 of file avx512vlfp16intrin.h.
_mm256_maskz_getmant_ph
#define _mm256_maskz_getmant_ph (U, A, B, C)
Value:
  ((__m256h)__builtin_ia32_getmantph256_mask(                                  \
      (__v16hf)(__m256h)(A), (int)(((C) << 2) | (B)),                          \
      (__v16hf)_mm256_setzero_ph(), (__mmask16)(U)))
Definition at line 502 of file avx512vlfp16intrin.h.
_mm256_maskz_mul_pch
#define _mm256_maskz_mul_pch (U, A, B) _mm256_maskz_fmul_pch(U, A, B)
Definition at line 2056 of file avx512vlfp16intrin.h.
_mm256_maskz_reduce_ph
#define _mm256_maskz_reduce_ph (U, A, imm)
Value:
  ((__m256h)__builtin_ia32_reduceph256_mask((__v16hf)(__m256h)(A), (int)(imm), \
                                            (__v16hf)_mm256_setzero_ph(),      \
                                            (__mmask16)(U)))
Definition at line 596 of file avx512vlfp16intrin.h.
_mm256_maskz_roundscale_ph
#define _mm256_maskz_roundscale_ph (U, A, imm)
Value:
  ((__m256h)__builtin_ia32_rndscaleph_256_mask(                                \
      (__v16hf)(__m256h)(A), (int)(imm), (__v16hf)_mm256_setzero_ph(),         \
      (__mmask16)(U)))
Definition at line 567 of file avx512vlfp16intrin.h.
_mm256_mul_pch
#define _mm256_mul_pch (A, B) _mm256_fmul_pch(A, B)
Definition at line 2054 of file avx512vlfp16intrin.h.
_mm256_reduce_ph
#define _mm256_reduce_ph (A, imm)
Value:
  ((__m256h)__builtin_ia32_reduceph256_mask((__v16hf)(__m256h)(A), (int)(imm), \
                                            (__v16hf)_mm256_setzero_ph(),      \
                                            (__mmask16)-1))
Definition at line 586 of file avx512vlfp16intrin.h.
_mm256_roundscale_ph
#define _mm256_roundscale_ph (A, imm)
Value:
  ((__m256h)__builtin_ia32_rndscaleph_256_mask(                                \
      (__v16hf)(__m256h)(A), (int)(imm), (__v16hf)_mm256_setzero_ph(),         \
      (__mmask16)-1))
Definition at line 557 of file avx512vlfp16intrin.h.
_mm256_setr_ph
#define _mm256_setr_ph (h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14, h15, h16)
Value:
  _mm256_set_ph((h16), (h15), (h14), (h13), (h12), (h11), (h10), (h9), (h8),   \
                (h7), (h6), (h5), (h4), (h3), (h2), (h1))
Definition at line 77 of file avx512vlfp16intrin.h.
_mm_cmp_ph_mask
#define _mm_cmp_ph_mask (a, b, p)
Value:
  ((__mmask8)__builtin_ia32_cmpph128_mask(                                     \
      (__v8hf)(__m128h)(a), (__v8hf)(__m128h)(b), (int)(p), (__mmask8)-1))
Definition at line 365 of file avx512vlfp16intrin.h.
_mm_cmul_pch
#define _mm_cmul_pch (A, B) _mm_fcmul_pch(A, B)
Definition at line 2058 of file avx512vlfp16intrin.h.
_mm_fpclass_ph_mask
#define _mm_fpclass_ph_mask (A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclassph128_mask((__v8hf)(__m128h)(A),            \
                                              (int)(imm), (__mmask8)-1))
Definition at line 639 of file avx512vlfp16intrin.h.
_mm_getmant_ph
#define _mm_getmant_ph (A, B, C)
Value:
  ((__m128h)__builtin_ia32_getmantph128_mask(                                  \
      (__v8hf)(__m128h)(A), (int)(((C) << 2) | (B)), (__v8hf)_mm_setzero_ph(), \
      (__mmask8)-1))
Definition at line 477 of file avx512vlfp16intrin.h.
_mm_mask_cmp_ph_mask
#define _mm_mask_cmp_ph_mask (m, a, b, p)
Value:
  ((__mmask8)__builtin_ia32_cmpph128_mask(                                     \
      (__v8hf)(__m128h)(a), (__v8hf)(__m128h)(b), (int)(p), (__mmask8)(m)))
Definition at line 369 of file avx512vlfp16intrin.h.
_mm_mask_cmul_pch
#define _mm_mask_cmul_pch (W, U, A, B) _mm_mask_fcmul_pch(W, U, A, B)
Definition at line 2059 of file avx512vlfp16intrin.h.
_mm_mask_fpclass_ph_mask
#define _mm_mask_fpclass_ph_mask (U, A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclassph128_mask((__v8hf)(__m128h)(A),            \
                                              (int)(imm), (__mmask8)(U)))
Definition at line 635 of file avx512vlfp16intrin.h.
_mm_mask_getmant_ph
#define _mm_mask_getmant_ph (W, U, A, B, C)
Value:
  ((__m128h)__builtin_ia32_getmantph128_mask(                                  \
      (__v8hf)(__m128h)(A), (int)(((C) << 2) | (B)), (__v8hf)(__m128h)(W),     \
      (__mmask8)(U)))
Definition at line 482 of file avx512vlfp16intrin.h.
_mm_mask_mul_pch
#define _mm_mask_mul_pch (W, U, A, B) _mm_mask_fmul_pch(W, U, A, B)
Definition at line 2052 of file avx512vlfp16intrin.h.
_mm_mask_reduce_ph
#define _mm_mask_reduce_ph (W, U, A, imm)
Value:
  ((__m128h)__builtin_ia32_reduceph128_mask(                                   \
      (__v8hf)(__m128h)(A), (int)(imm), (__v8hf)(__m128h)(W), (__mmask8)(U)))
Definition at line 577 of file avx512vlfp16intrin.h.
_mm_mask_roundscale_ph
#define _mm_mask_roundscale_ph (W, U, A, imm)
Value:
  ((__m128h)__builtin_ia32_rndscaleph_128_mask(                                \
      (__v8hf)(__m128h)(A), (int)(imm), (__v8hf)(__m128h)(W), (__mmask8)(U)))
Definition at line 548 of file avx512vlfp16intrin.h.
_mm_maskz_cmul_pch
#define _mm_maskz_cmul_pch (U, A, B) _mm_maskz_fcmul_pch(U, A, B)
Definition at line 2060 of file avx512vlfp16intrin.h.
_mm_maskz_getmant_ph
#define _mm_maskz_getmant_ph (U, A, B, C)
Value:
  ((__m128h)__builtin_ia32_getmantph128_mask(                                  \
      (__v8hf)(__m128h)(A), (int)(((C) << 2) | (B)), (__v8hf)_mm_setzero_ph(), \
      (__mmask8)(U)))
Definition at line 487 of file avx512vlfp16intrin.h.
_mm_maskz_mul_pch
#define _mm_maskz_mul_pch (U, A, B) _mm_maskz_fmul_pch(U, A, B)
Definition at line 2053 of file avx512vlfp16intrin.h.
_mm_maskz_reduce_ph
#define _mm_maskz_reduce_ph (U, A, imm)
Value:
  ((__m128h)__builtin_ia32_reduceph128_mask((__v8hf)(__m128h)(A), (int)(imm),  \
                                            (__v8hf)_mm_setzero_ph(),          \
                                            (__mmask8)(U)))
Definition at line 581 of file avx512vlfp16intrin.h.
_mm_maskz_roundscale_ph
#define _mm_maskz_roundscale_ph (U, A, imm)
Value:
  ((__m128h)__builtin_ia32_rndscaleph_128_mask(                                \
      (__v8hf)(__m128h)(A), (int)(imm), (__v8hf)_mm_setzero_ph(),              \
      (__mmask8)(U)))
Definition at line 552 of file avx512vlfp16intrin.h.
_mm_mul_pch
#define _mm_mul_pch (A, B) _mm_fmul_pch(A, B)
Definition at line 2051 of file avx512vlfp16intrin.h.
_mm_reduce_ph
#define _mm_reduce_ph (A, imm)
Value:
  ((__m128h)__builtin_ia32_reduceph128_mask((__v8hf)(__m128h)(A), (int)(imm),  \
                                            (__v8hf)_mm_setzero_ph(),          \
                                            (__mmask8)-1))
Definition at line 572 of file avx512vlfp16intrin.h.
_mm_roundscale_ph
#define _mm_roundscale_ph (A, imm)
Value:
  ((__m128h)__builtin_ia32_rndscaleph_128_mask(                                \
      (__v8hf)(__m128h)(A), (int)(imm), (__v8hf)_mm_setzero_ph(),              \
      (__mmask8)-1))
Definition at line 543 of file avx512vlfp16intrin.h.
_mm_setr_ph
#define _mm_setr_ph (h1, h2, h3, h4, h5, h6, h7, h8) _mm_set_ph((h8), (h7), (h6), (h5), (h4), (h3), (h2), (h1))
Definition at line 74 of file avx512vlfp16intrin.h.
Function Documentation
_mm256_abs_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_abs_ph (__m256h __A) static
Definition at line 316 of file avx512vlfp16intrin.h.
References _mm256_and_epi32(), and _mm256_set1_epi32().
_mm256_add_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_add_ph (__m256h __A, __m256h __B) static
Definition at line 82 of file avx512vlfp16intrin.h.
Referenced by _mm256_mask_add_ph(), and _mm256_maskz_add_ph().
_mm256_conj_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_conj_pch (__m256h __A) static
Definition at line 324 of file avx512vlfp16intrin.h.
References _mm256_set1_ps(), and _mm256_xor_ps().
Referenced by _mm256_mask_conj_pch(), and _mm256_maskz_conj_pch().
_mm256_cvtepi16_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_cvtepi16_ph (__m256i __A) static
Definition at line 808 of file avx512vlfp16intrin.h.
Referenced by _mm256_mask_cvtepi16_ph(), and _mm256_maskz_cvtepi16_ph().
_mm256_cvtepi32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtepi32_ph (__m256i __A) static
Definition at line 1017 of file avx512vlfp16intrin.h.
Referenced by _mm256_mask_cvtepi32_ph(), and _mm256_maskz_cvtepi32_ph().
_mm256_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtepi64_ph (__m256i __A) static
Definition at line 1155 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm256_cvtepu16_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_cvtepu16_ph (__m256i __A) static
Definition at line 912 of file avx512vlfp16intrin.h.
Referenced by _mm256_mask_cvtepu16_ph(), and _mm256_maskz_cvtepu16_ph().
_mm256_cvtepu32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtepu32_ph (__m256i __A) static
Definition at line 1051 of file avx512vlfp16intrin.h.
Referenced by _mm256_mask_cvtepu32_ph(), and _mm256_maskz_cvtepu32_ph().
_mm256_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtepu64_ph (__m256i __A) static
Definition at line 1225 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm256_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtpd_ph (__m256d __A) static
Definition at line 669 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm256_cvtph_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epi16 (__m256h __A) static
Definition at line 739 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvtph_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epi32 (__m128h __A) static
Definition at line 947 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvtph_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epi64 (__m128h __A) static
Definition at line 1190 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvtph_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epu16 (__m256h __A) static
Definition at line 843 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvtph_epu32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epu32 (__m128h __A) static
Definition at line 982 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvtph_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtph_epu64 (__m128h __A) static
Definition at line 1260 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvtph_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_cvtph_pd (__m128h __A) static
Definition at line 704 of file avx512vlfp16intrin.h.
References _mm256_undefined_pd().
_mm256_cvtsh_h()
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_cvtsh_h (__m256h __a) static
Definition at line 31 of file avx512vlfp16intrin.h.
References __a.
_mm256_cvttph_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epi16 (__m256h __A) static
Definition at line 774 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvttph_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epi32 (__m128h __A) static
Definition at line 1085 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvttph_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epi64 (__m128h __A) static
Definition at line 1295 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvttph_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epu16 (__m256h __A) static
Definition at line 878 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvttph_epu32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epu32 (__m128h __A) static
Definition at line 1120 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvttph_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttph_epu64 (__m128h __A) static
Definition at line 1330 of file avx512vlfp16intrin.h.
References _mm256_undefined_si256().
_mm256_cvtxph_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_cvtxph_ps (__m128h __A) static
Definition at line 1365 of file avx512vlfp16intrin.h.
References _mm256_undefined_ps().
_mm256_cvtxps_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_cvtxps_ph (__m256 __A) static
Definition at line 1400 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm256_div_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_div_ph (__m256h __A, __m256h __B) static
Definition at line 193 of file avx512vlfp16intrin.h.
Referenced by _mm256_mask_div_ph(), and _mm256_maskz_div_ph().
_mm256_fcmadd_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fcmadd_pch (__m256h __A, __m256h __B, __m256h __C) static
Definition at line 1853 of file avx512vlfp16intrin.h.
_mm256_fcmul_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS128 _mm256_fcmul_pch (__m256h __A, __m256h __B) static
Definition at line 1807 of file avx512vlfp16intrin.h.
References _mm256_undefined_ph().
_mm256_fmadd_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmadd_pch (__m256h __A, __m256h __B, __m256h __C) static
Definition at line 1947 of file avx512vlfp16intrin.h.
_mm256_fmadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmadd_ph (__m256h __A, __m256h __B, __m256h __C) static
Definition at line 1497 of file avx512vlfp16intrin.h.
_mm256_fmaddsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmaddsub_ph (__m256h __A, __m256h __B, __m256h __C) static
Definition at line 1630 of file avx512vlfp16intrin.h.
_mm256_fmsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmsub_ph (__m256h __A, __m256h __B, __m256h __C) static
Definition at line 1528 of file avx512vlfp16intrin.h.
_mm256_fmsubadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmsubadd_ph (__m256h __A, __m256h __B, __m256h __C) static
Definition at line 1660 of file avx512vlfp16intrin.h.
_mm256_fmul_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fmul_pch (__m256h __A, __m256h __B) static
Definition at line 1901 of file avx512vlfp16intrin.h.
References _mm256_undefined_ph().
_mm256_fnmadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fnmadd_ph (__m256h __A, __m256h __B, __m256h __C) static
Definition at line 1728 of file avx512vlfp16intrin.h.
_mm256_fnmsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_fnmsub_ph (__m256h __A, __m256h __B, __m256h __C) static
Definition at line 1766 of file avx512vlfp16intrin.h.
_mm256_getexp_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_getexp_ph (__m256h __A) static
Definition at line 460 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_mask3_fcmadd_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fcmadd_pch (__m256h __A, __m256h __B, __m256h __C, __mmask8 __U) static
Definition at line 1870 of file avx512vlfp16intrin.h.
_mm256_mask3_fmadd_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmadd_pch (__m256h __A, __m256h __B, __m256h __C, __mmask8 __U) static
Definition at line 1964 of file avx512vlfp16intrin.h.
_mm256_mask3_fmadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmadd_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U) static
Definition at line 1513 of file avx512vlfp16intrin.h.
_mm256_mask3_fmaddsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmaddsub_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U) static
Definition at line 1644 of file avx512vlfp16intrin.h.
_mm256_mask3_fmsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmsub_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U) static
Definition at line 1690 of file avx512vlfp16intrin.h.
_mm256_mask3_fmsubadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fmsubadd_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U) static
Definition at line 1706 of file avx512vlfp16intrin.h.
_mm256_mask3_fnmadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fnmadd_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U) static
Definition at line 1552 of file avx512vlfp16intrin.h.
_mm256_mask3_fnmsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask3_fnmsub_ph (__m256h __A, __m256h __B, __m256h __C, __mmask16 __U) static
Definition at line 1782 of file avx512vlfp16intrin.h.
_mm256_mask_add_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_add_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 88 of file avx512vlfp16intrin.h.
References _mm256_add_ph().
_mm256_mask_blend_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_blend_ph (__mmask16 __U, __m256h __A, __m256h __W) static
Definition at line 1983 of file avx512vlfp16intrin.h.
_mm256_mask_conj_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_conj_pch (__m256h __W, __mmask8 __U, __m256h __A) static
Definition at line 329 of file avx512vlfp16intrin.h.
References _mm256_conj_pch().
_mm256_mask_cvtepi16_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi16_ph (__m256h __W, __mmask16 __U, __m256i __A) static
Definition at line 813 of file avx512vlfp16intrin.h.
References _mm256_cvtepi16_ph().
_mm256_mask_cvtepi32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi32_ph (__m128h __W, __mmask8 __U, __m256i __A) static
Definition at line 1022 of file avx512vlfp16intrin.h.
References _mm256_cvtepi32_ph().
_mm256_mask_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi64_ph (__m128h __W, __mmask8 __U, __m256i __A) static
Definition at line 1161 of file avx512vlfp16intrin.h.
_mm256_mask_cvtepu16_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu16_ph (__m256h __W, __mmask16 __U, __m256i __A) static
Definition at line 917 of file avx512vlfp16intrin.h.
References _mm256_cvtepu16_ph().
_mm256_mask_cvtepu32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu32_ph (__m128h __W, __mmask8 __U, __m256i __A) static
Definition at line 1056 of file avx512vlfp16intrin.h.
References _mm256_cvtepu32_ph().
_mm256_mask_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu64_ph (__m128h __W, __mmask8 __U, __m256i __A) static
Definition at line 1231 of file avx512vlfp16intrin.h.
_mm256_mask_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtpd_ph (__m128h __W, __mmask8 __U, __m256d __A) static
Definition at line 675 of file avx512vlfp16intrin.h.
_mm256_mask_cvtph_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epi16 (__m256i __W, __mmask16 __U, __m256h __A) static
Definition at line 745 of file avx512vlfp16intrin.h.
_mm256_mask_cvtph_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epi32 (__m256i __W, __mmask8 __U, __m128h __A) static
Definition at line 953 of file avx512vlfp16intrin.h.
_mm256_mask_cvtph_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epi64 (__m256i __W, __mmask8 __U, __m128h __A) static
Definition at line 1196 of file avx512vlfp16intrin.h.
_mm256_mask_cvtph_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epu16 (__m256i __W, __mmask16 __U, __m256h __A) static
Definition at line 849 of file avx512vlfp16intrin.h.
_mm256_mask_cvtph_epu32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epu32 (__m256i __W, __mmask8 __U, __m128h __A) static
Definition at line 988 of file avx512vlfp16intrin.h.
_mm256_mask_cvtph_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_epu64 (__m256i __W, __mmask8 __U, __m128h __A) static
Definition at line 1266 of file avx512vlfp16intrin.h.
_mm256_mask_cvtph_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_cvtph_pd (__m256d __W, __mmask8 __U, __m128h __A) static
Definition at line 710 of file avx512vlfp16intrin.h.
_mm256_mask_cvttph_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epi16 (__m256i __W, __mmask16 __U, __m256h __A) static
Definition at line 780 of file avx512vlfp16intrin.h.
_mm256_mask_cvttph_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epi32 (__m256i __W, __mmask8 __U, __m128h __A) static
Definition at line 1091 of file avx512vlfp16intrin.h.
_mm256_mask_cvttph_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epi64 (__m256i __W, __mmask8 __U, __m128h __A) static
Definition at line 1301 of file avx512vlfp16intrin.h.
_mm256_mask_cvttph_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epu16 (__m256i __W, __mmask16 __U, __m256h __A) static
Definition at line 884 of file avx512vlfp16intrin.h.
_mm256_mask_cvttph_epu32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epu32 (__m256i __W, __mmask8 __U, __m128h __A) static
Definition at line 1126 of file avx512vlfp16intrin.h.
_mm256_mask_cvttph_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttph_epu64 (__m256i __W, __mmask8 __U, __m128h __A) static
Definition at line 1336 of file avx512vlfp16intrin.h.
_mm256_mask_cvtxph_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_cvtxph_ps (__m256 __W, __mmask8 __U, __m128h __A) static
Definition at line 1371 of file avx512vlfp16intrin.h.
_mm256_mask_cvtxps_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_mask_cvtxps_ph (__m128h __W, __mmask8 __U, __m256 __A) static
Definition at line 1406 of file avx512vlfp16intrin.h.
_mm256_mask_div_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_div_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 199 of file avx512vlfp16intrin.h.
References _mm256_div_ph().
_mm256_mask_fcmadd_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fcmadd_pch (__m256h __A, __mmask8 __U, __m256h __B, __m256h __C) static
Definition at line 1861 of file avx512vlfp16intrin.h.
_mm256_mask_fcmul_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fcmul_pch (__m256h __W, __mmask8 __U, __m256h __A, __m256h __B) static
Definition at line 1814 of file avx512vlfp16intrin.h.
_mm256_mask_fmadd_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmadd_pch (__m256h __A, __mmask8 __U, __m256h __B, __m256h __C) static
Definition at line 1955 of file avx512vlfp16intrin.h.
_mm256_mask_fmadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmadd_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C) static
Definition at line 1505 of file avx512vlfp16intrin.h.
_mm256_mask_fmaddsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmaddsub_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C) static
Definition at line 1636 of file avx512vlfp16intrin.h.
_mm256_mask_fmsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmsub_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C) static
Definition at line 1536 of file avx512vlfp16intrin.h.
_mm256_mask_fmsubadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmsubadd_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C) static
Definition at line 1666 of file avx512vlfp16intrin.h.
_mm256_mask_fmul_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fmul_pch (__m256h __W, __mmask8 __U, __m256h __A, __m256h __B) static
Definition at line 1908 of file avx512vlfp16intrin.h.
_mm256_mask_fnmadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fnmadd_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C) static
Definition at line 1736 of file avx512vlfp16intrin.h.
_mm256_mask_fnmsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_fnmsub_ph (__m256h __A, __mmask16 __U, __m256h __B, __m256h __C) static
Definition at line 1774 of file avx512vlfp16intrin.h.
_mm256_mask_getexp_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_getexp_ph (__m256h __W, __mmask16 __U, __m256h __A) static
Definition at line 466 of file avx512vlfp16intrin.h.
_mm256_mask_max_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_max_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 279 of file avx512vlfp16intrin.h.
_mm256_mask_min_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_min_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 236 of file avx512vlfp16intrin.h.
_mm256_mask_mul_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_mul_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 162 of file avx512vlfp16intrin.h.
References _mm256_mul_ph().
_mm256_mask_rcp_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_rcp_ph (__m256h __W, __mmask16 __U, __m256h __A) static
Definition at line 379 of file avx512vlfp16intrin.h.
_mm256_mask_rsqrt_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_rsqrt_ph (__m256h __W, __mmask16 __U, __m256h __A) static
Definition at line 414 of file avx512vlfp16intrin.h.
_mm256_mask_scalef_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_scalef_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 532 of file avx512vlfp16intrin.h.
_mm256_mask_sqrt_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_sqrt_ph (__m256h __W, __mmask16 __U, __m256h __A) static
Definition at line 623 of file avx512vlfp16intrin.h.
References _mm256_sqrt_ph().
_mm256_mask_sub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mask_sub_ph (__m256h __W, __mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 125 of file avx512vlfp16intrin.h.
References _mm256_sub_ph().
_mm256_maskz_add_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_add_ph (__mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 94 of file avx512vlfp16intrin.h.
References _mm256_add_ph(), and _mm256_setzero_ph().
_mm256_maskz_conj_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_conj_pch (__mmask8 __U, __m256h __A) static
Definition at line 335 of file avx512vlfp16intrin.h.
References _mm256_conj_pch(), and _mm256_setzero_ps().
_mm256_maskz_cvtepi16_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi16_ph (__mmask16 __U, __m256i __A) static
Definition at line 819 of file avx512vlfp16intrin.h.
References _mm256_cvtepi16_ph(), and _mm256_setzero_ph().
_mm256_maskz_cvtepi32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi32_ph (__mmask8 __U, __m256i __A) static
Definition at line 1028 of file avx512vlfp16intrin.h.
References _mm256_cvtepi32_ph(), and _mm_setzero_ph().
_mm256_maskz_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi64_ph (__mmask8 __U, __m256i __A) static
Definition at line 1167 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm256_maskz_cvtepu16_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu16_ph (__mmask16 __U, __m256i __A) static
Definition at line 923 of file avx512vlfp16intrin.h.
References _mm256_cvtepu16_ph(), and _mm256_setzero_ph().
_mm256_maskz_cvtepu32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu32_ph (__mmask8 __U, __m256i __A) static
Definition at line 1062 of file avx512vlfp16intrin.h.
References _mm256_cvtepu32_ph(), and _mm_setzero_ph().
_mm256_maskz_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu64_ph (__mmask8 __U, __m256i __A) static
Definition at line 1237 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm256_maskz_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtpd_ph (__mmask8 __U, __m256d __A) static
Definition at line 681 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm256_maskz_cvtph_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epi16 (__mmask16 __U, __m256h __A) static
Definition at line 751 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtph_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epi32 (__mmask8 __U, __m128h __A) static
Definition at line 959 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtph_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epi64 (__mmask8 __U, __m128h __A) static
Definition at line 1202 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtph_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epu16 (__mmask16 __U, __m256h __A) static
Definition at line 855 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtph_epu32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epu32 (__mmask8 __U, __m128h __A) static
Definition at line 994 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtph_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_epu64 (__mmask8 __U, __m128h __A) static
Definition at line 1272 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtph_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtph_pd (__mmask8 __U, __m128h __A) static
Definition at line 716 of file avx512vlfp16intrin.h.
References _mm256_setzero_pd().
_mm256_maskz_cvttph_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epi16 (__mmask16 __U, __m256h __A) static
Definition at line 786 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttph_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epi32 (__mmask8 __U, __m128h __A) static
Definition at line 1097 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttph_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epi64 (__mmask8 __U, __m128h __A) static
Definition at line 1307 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttph_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epu16 (__mmask16 __U, __m256h __A) static
Definition at line 890 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttph_epu32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epu32 (__mmask8 __U, __m128h __A) static
Definition at line 1132 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttph_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttph_epu64 (__mmask8 __U, __m128h __A) static
Definition at line 1342 of file avx512vlfp16intrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtxph_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtxph_ps (__mmask8 __U, __m128h __A) static
Definition at line 1377 of file avx512vlfp16intrin.h.
References _mm256_setzero_ps().
_mm256_maskz_cvtxps_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtxps_ph (__mmask8 __U, __m256 __A) static
Definition at line 1412 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm256_maskz_div_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_div_ph (__mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 205 of file avx512vlfp16intrin.h.
References _mm256_div_ph(), and _mm256_setzero_ph().
_mm256_maskz_fcmadd_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fcmadd_pch (__mmask8 __U, __m256h __A, __m256h __B, __m256h __C) static
Definition at line 1876 of file avx512vlfp16intrin.h.
_mm256_maskz_fcmul_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fcmul_pch (__mmask8 __U, __m256h __A, __m256h __B) static
Definition at line 1820 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_fmadd_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmadd_pch (__mmask8 __U, __m256h __A, __m256h __B, __m256h __C) static
Definition at line 1970 of file avx512vlfp16intrin.h.
_mm256_maskz_fmadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmadd_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C) static
Definition at line 1521 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_fmaddsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmaddsub_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C) static
Definition at line 1652 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_fmsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmsub_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C) static
Definition at line 1544 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_fmsubadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmsubadd_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C) static
Definition at line 1674 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_fmul_pch()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fmul_pch (__mmask8 __U, __m256h __A, __m256h __B) static
Definition at line 1914 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_fnmadd_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fnmadd_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C) static
Definition at line 1560 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_fnmsub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_fnmsub_ph (__mmask16 __U, __m256h __A, __m256h __B, __m256h __C) static
Definition at line 1568 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_getexp_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_getexp_ph (__mmask16 __U, __m256h __A) static
Definition at line 472 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_max_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_max_ph (__mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 287 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_min_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_min_ph (__mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 244 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_mul_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_mul_ph (__mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 168 of file avx512vlfp16intrin.h.
References _mm256_mul_ph(), and _mm256_setzero_ph().
_mm256_maskz_rcp_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_rcp_ph (__mmask16 __U, __m256h __A) static
Definition at line 385 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_rsqrt_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_rsqrt_ph (__mmask16 __U, __m256h __A) static
Definition at line 420 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_scalef_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_scalef_ph (__mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 538 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_maskz_sqrt_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_sqrt_ph (__mmask16 __U, __m256h __A) static
Definition at line 629 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph(), and _mm256_sqrt_ph().
_mm256_maskz_sub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_maskz_sub_ph (__mmask16 __U, __m256h __A, __m256h __B) static
Definition at line 131 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph(), and _mm256_sub_ph().
_mm256_max_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_max_ph (__m256h __A, __m256h __B) static
Definition at line 273 of file avx512vlfp16intrin.h.
_mm256_min_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_min_ph (__m256h __A, __m256h __B) static
Definition at line 230 of file avx512vlfp16intrin.h.
_mm256_mul_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_mul_ph (__m256h __A, __m256h __B) static
Definition at line 156 of file avx512vlfp16intrin.h.
Referenced by _mm256_mask_mul_ph(), and _mm256_maskz_mul_ph().
_mm256_permutex2var_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_permutex2var_ph (__m256h __A, __m256i __I, __m256h __B) static
Definition at line 1995 of file avx512vlfp16intrin.h.
_mm256_permutexvar_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_permutexvar_ph (__m256i __A, __m256h __B) static
Definition at line 2006 of file avx512vlfp16intrin.h.
_mm256_rcp_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_rcp_ph (__m256h __A) static
Definition at line 373 of file avx512vlfp16intrin.h.
References _mm256_undefined_ph().
_mm256_reduce_add_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_reduce_add_ph (__m256h __W) static
Definition at line 2011 of file avx512vlfp16intrin.h.
_mm256_reduce_max_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_reduce_max_ph (__m256h __V) static
Definition at line 2021 of file avx512vlfp16intrin.h.
_mm256_reduce_min_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_reduce_min_ph (__m256h __V) static
Definition at line 2026 of file avx512vlfp16intrin.h.
_mm256_reduce_mul_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS256 _mm256_reduce_mul_ph (__m256h __W) static
Definition at line 2016 of file avx512vlfp16intrin.h.
_mm256_rsqrt_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_rsqrt_ph (__m256h __A) static
Definition at line 408 of file avx512vlfp16intrin.h.
References _mm256_undefined_ph().
_mm256_scalef_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_scalef_ph (__m256h __A, __m256h __B) static
Definition at line 525 of file avx512vlfp16intrin.h.
References _mm256_setzero_ph().
_mm256_set1_pch()
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_set1_pch (_Float16 _Complex h) static
Definition at line 55 of file avx512vlfp16intrin.h.
References _mm256_set1_ps().
_mm256_set1_ph()
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_set1_ph (_Float16 __h) static
Definition at line 43 of file avx512vlfp16intrin.h.
_mm256_set_ph()
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_set_ph (_Float16 __h1, _Float16 __h2, _Float16 __h3, _Float16 __h4, _Float16 __h5, _Float16 __h6, _Float16 __h7, _Float16 __h8, _Float16 __h9, _Float16 __h10, _Float16 __h11, _Float16 __h12, _Float16 __h13, _Float16 __h14, _Float16 __h15, _Float16 __h16) static
Definition at line 65 of file avx512vlfp16intrin.h.
_mm256_sqrt_ph()
static __inline __m256h __DEFAULT_FN_ATTRS256 _mm256_sqrt_ph (__m256h __a) static
Definition at line 618 of file avx512vlfp16intrin.h.
References __a.
Referenced by _mm256_mask_sqrt_ph(), and _mm256_maskz_sqrt_ph().
_mm256_sub_ph()
static __inline__ __m256h __DEFAULT_FN_ATTRS256 _mm256_sub_ph (__m256h __A, __m256h __B) static
Definition at line 119 of file avx512vlfp16intrin.h.
Referenced by _mm256_mask_sub_ph(), and _mm256_maskz_sub_ph().
_mm_abs_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_abs_ph (__m128h __A) static
Definition at line 320 of file avx512vlfp16intrin.h.
References _mm_and_epi32(), and _mm_set1_epi32().
_mm_add_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_add_ph (__m128h __A, __m128h __B) static
Definition at line 99 of file avx512vlfp16intrin.h.
Referenced by _mm_mask_add_ph(), and _mm_maskz_add_ph().
_mm_conj_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_conj_pch (__m128h __A) static
Definition at line 340 of file avx512vlfp16intrin.h.
References _mm_set1_ps(), and _mm_xor_ps().
Referenced by _mm_mask_conj_pch(), and _mm_maskz_conj_pch().
_mm_cvtepi16_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepi16_ph (__m128i __A) static
Definition at line 791 of file avx512vlfp16intrin.h.
Referenced by _mm_mask_cvtepi16_ph(), and _mm_maskz_cvtepi16_ph().
_mm_cvtepi32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepi32_ph (__m128i __A) static
Definition at line 999 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepi64_ph (__m128i __A) static
Definition at line 1137 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_cvtepu16_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepu16_ph (__m128i __A) static
Definition at line 895 of file avx512vlfp16intrin.h.
Referenced by _mm_mask_cvtepu16_ph(), and _mm_maskz_cvtepu16_ph().
_mm_cvtepu32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepu32_ph (__m128i __A) static
Definition at line 1033 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtepu64_ph (__m128i __A) static
Definition at line 1207 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtpd_ph (__m128d __A) static
Definition at line 651 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_cvtph_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epi16 (__m128h __A) static
Definition at line 721 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvtph_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epi32 (__m128h __A) static
Definition at line 929 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvtph_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epi64 (__m128h __A) static
Definition at line 1172 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvtph_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epu16 (__m128h __A) static
Definition at line 825 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvtph_epu32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epu32 (__m128h __A) static
Definition at line 964 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvtph_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtph_epu64 (__m128h __A) static
Definition at line 1242 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvtph_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_cvtph_pd (__m128h __A) static
Definition at line 686 of file avx512vlfp16intrin.h.
References _mm_undefined_pd().
_mm_cvtsh_h()
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_cvtsh_h (__m128h __a) static
Definition at line 27 of file avx512vlfp16intrin.h.
References __a.
_mm_cvttph_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epi16 (__m128h __A) static
Definition at line 756 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvttph_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epi32 (__m128h __A) static
Definition at line 1067 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvttph_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epi64 (__m128h __A) static
Definition at line 1277 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvttph_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epu16 (__m128h __A) static
Definition at line 860 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvttph_epu32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epu32 (__m128h __A) static
Definition at line 1102 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvttph_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttph_epu64 (__m128h __A) static
Definition at line 1312 of file avx512vlfp16intrin.h.
References _mm_undefined_si128().
_mm_cvtxph_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_cvtxph_ps (__m128h __A) static
Definition at line 1347 of file avx512vlfp16intrin.h.
References _mm_undefined_ps().
_mm_cvtxps_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_cvtxps_ph (__m128 __A) static
Definition at line 1382 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_div_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_div_ph (__m128h __A, __m128h __B) static
Definition at line 210 of file avx512vlfp16intrin.h.
Referenced by _mm_mask_div_ph(), and _mm_maskz_div_ph().
_mm_fcmadd_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fcmadd_pch (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 1825 of file avx512vlfp16intrin.h.
_mm_fcmul_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fcmul_pch (__m128h __A, __m128h __B) static
Definition at line 1789 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_fmadd_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmadd_pch (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 1919 of file avx512vlfp16intrin.h.
_mm_fmadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmadd_ph (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 1417 of file avx512vlfp16intrin.h.
_mm_fmaddsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmaddsub_ph (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 1575 of file avx512vlfp16intrin.h.
_mm_fmsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmsub_ph (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 1450 of file avx512vlfp16intrin.h.
Referenced by _mm_mask_fmsub_ph(), and _mm_maskz_fmsub_ph().
_mm_fmsubadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmsubadd_ph (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 1606 of file avx512vlfp16intrin.h.
_mm_fmul_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fmul_pch (__m128h __A, __m128h __B) static
Definition at line 1881 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_fnmadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fnmadd_ph (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 1713 of file avx512vlfp16intrin.h.
_mm_fnmsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_fnmsub_ph (__m128h __A, __m128h __B, __m128h __C) static
Definition at line 1743 of file avx512vlfp16intrin.h.
_mm_getexp_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_getexp_ph (__m128h __A) static
Definition at line 443 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_mask3_fcmadd_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fcmadd_pch (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 1842 of file avx512vlfp16intrin.h.
_mm_mask3_fmadd_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmadd_pch (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 1936 of file avx512vlfp16intrin.h.
_mm_mask3_fmadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmadd_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 1435 of file avx512vlfp16intrin.h.
_mm_mask3_fmaddsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmaddsub_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 1591 of file avx512vlfp16intrin.h.
_mm_mask3_fmsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmsub_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 1682 of file avx512vlfp16intrin.h.
_mm_mask3_fmsubadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fmsubadd_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 1698 of file avx512vlfp16intrin.h.
_mm_mask3_fnmadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fnmadd_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 1474 of file avx512vlfp16intrin.h.
_mm_mask3_fnmsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask3_fnmsub_ph (__m128h __A, __m128h __B, __m128h __C, __mmask8 __U) static
Definition at line 1759 of file avx512vlfp16intrin.h.
_mm_mask_add_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_add_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 104 of file avx512vlfp16intrin.h.
References _mm_add_ph().
_mm_mask_blend_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_blend_ph (__mmask8 __U, __m128h __A, __m128h __W) static
Definition at line 1975 of file avx512vlfp16intrin.h.
_mm_mask_conj_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_conj_pch (__m128h __W, __mmask8 __U, __m128h __A) static
Definition at line 344 of file avx512vlfp16intrin.h.
References _mm_conj_pch().
_mm_mask_cvtepi16_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi16_ph (__m128h __W, __mmask8 __U, __m128i __A) static
Definition at line 796 of file avx512vlfp16intrin.h.
References _mm_cvtepi16_ph().
_mm_mask_cvtepi32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi32_ph (__m128h __W, __mmask8 __U, __m128i __A) static
Definition at line 1005 of file avx512vlfp16intrin.h.
_mm_mask_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi64_ph (__m128h __W, __mmask8 __U, __m128i __A) static
Definition at line 1143 of file avx512vlfp16intrin.h.
_mm_mask_cvtepu16_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu16_ph (__m128h __W, __mmask8 __U, __m128i __A) static
Definition at line 900 of file avx512vlfp16intrin.h.
References _mm_cvtepu16_ph().
_mm_mask_cvtepu32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu32_ph (__m128h __W, __mmask8 __U, __m128i __A) static
Definition at line 1039 of file avx512vlfp16intrin.h.
_mm_mask_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu64_ph (__m128h __W, __mmask8 __U, __m128i __A) static
Definition at line 1213 of file avx512vlfp16intrin.h.
_mm_mask_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtpd_ph (__m128h __W, __mmask8 __U, __m128d __A) static
Definition at line 656 of file avx512vlfp16intrin.h.
_mm_mask_cvtph_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epi16 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 727 of file avx512vlfp16intrin.h.
_mm_mask_cvtph_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epi32 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 935 of file avx512vlfp16intrin.h.
_mm_mask_cvtph_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epi64 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 1178 of file avx512vlfp16intrin.h.
_mm_mask_cvtph_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epu16 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 831 of file avx512vlfp16intrin.h.
_mm_mask_cvtph_epu32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epu32 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 970 of file avx512vlfp16intrin.h.
_mm_mask_cvtph_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_epu64 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 1248 of file avx512vlfp16intrin.h.
_mm_mask_cvtph_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_cvtph_pd (__m128d __W, __mmask8 __U, __m128h __A) static
Definition at line 691 of file avx512vlfp16intrin.h.
_mm_mask_cvttph_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epi16 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 762 of file avx512vlfp16intrin.h.
_mm_mask_cvttph_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epi32 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 1073 of file avx512vlfp16intrin.h.
_mm_mask_cvttph_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epi64 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 1283 of file avx512vlfp16intrin.h.
_mm_mask_cvttph_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epu16 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 866 of file avx512vlfp16intrin.h.
_mm_mask_cvttph_epu32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epu32 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 1108 of file avx512vlfp16intrin.h.
_mm_mask_cvttph_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttph_epu64 (__m128i __W, __mmask8 __U, __m128h __A) static
Definition at line 1318 of file avx512vlfp16intrin.h.
_mm_mask_cvtxph_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_cvtxph_ps (__m128 __W, __mmask8 __U, __m128h __A) static
Definition at line 1352 of file avx512vlfp16intrin.h.
_mm_mask_cvtxps_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_cvtxps_ph (__m128h __W, __mmask8 __U, __m128 __A) static
Definition at line 1387 of file avx512vlfp16intrin.h.
_mm_mask_div_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_div_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 215 of file avx512vlfp16intrin.h.
References _mm_div_ph().
_mm_mask_fcmadd_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fcmadd_pch (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 1833 of file avx512vlfp16intrin.h.
_mm_mask_fcmul_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fcmul_pch (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1796 of file avx512vlfp16intrin.h.
_mm_mask_fmadd_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmadd_pch (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 1927 of file avx512vlfp16intrin.h.
_mm_mask_fmadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmadd_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 1424 of file avx512vlfp16intrin.h.
_mm_mask_fmaddsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmaddsub_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 1583 of file avx512vlfp16intrin.h.
_mm_mask_fmsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmsub_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 1457 of file avx512vlfp16intrin.h.
References _mm_fmsub_ph().
_mm_mask_fmsubadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmsubadd_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 1614 of file avx512vlfp16intrin.h.
_mm_mask_fmul_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fmul_pch (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1887 of file avx512vlfp16intrin.h.
_mm_mask_fnmadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fnmadd_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 1721 of file avx512vlfp16intrin.h.
_mm_mask_fnmsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_fnmsub_ph (__m128h __A, __mmask8 __U, __m128h __B, __m128h __C) static
Definition at line 1751 of file avx512vlfp16intrin.h.
_mm_mask_getexp_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_getexp_ph (__m128h __W, __mmask8 __U, __m128h __A) static
Definition at line 449 of file avx512vlfp16intrin.h.
_mm_mask_max_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_max_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 299 of file avx512vlfp16intrin.h.
_mm_mask_min_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_min_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 256 of file avx512vlfp16intrin.h.
_mm_mask_mul_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_mul_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 178 of file avx512vlfp16intrin.h.
References _mm_mul_ph().
_mm_mask_rcp_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_rcp_ph (__m128h __W, __mmask8 __U, __m128h __A) static
Definition at line 395 of file avx512vlfp16intrin.h.
_mm_mask_rsqrt_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_rsqrt_ph (__m128h __W, __mmask8 __U, __m128h __A) static
Definition at line 430 of file avx512vlfp16intrin.h.
_mm_mask_scalef_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_scalef_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 514 of file avx512vlfp16intrin.h.
_mm_mask_sqrt_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_sqrt_ph (__m128h __W, __mmask8 __U, __m128h __A) static
Definition at line 605 of file avx512vlfp16intrin.h.
References _mm_sqrt_ph().
_mm_mask_sub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mask_sub_ph (__m128h __W, __mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 141 of file avx512vlfp16intrin.h.
References _mm_sub_ph().
_mm_maskz_add_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_add_ph (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 112 of file avx512vlfp16intrin.h.
References _mm_add_ph(), and _mm_setzero_ph().
_mm_maskz_conj_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_conj_pch (__mmask8 __U, __m128h __A) static
Definition at line 352 of file avx512vlfp16intrin.h.
References _mm_conj_pch(), and _mm_setzero_ps().
_mm_maskz_cvtepi16_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi16_ph (__mmask8 __U, __m128i __A) static
Definition at line 802 of file avx512vlfp16intrin.h.
References _mm_cvtepi16_ph(), and _mm_setzero_ph().
_mm_maskz_cvtepi32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi32_ph (__mmask8 __U, __m128i __A) static
Definition at line 1011 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_cvtepi64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi64_ph (__mmask8 __U, __m128i __A) static
Definition at line 1149 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_cvtepu16_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu16_ph (__mmask8 __U, __m128i __A) static
Definition at line 906 of file avx512vlfp16intrin.h.
References _mm_cvtepu16_ph(), and _mm_setzero_ph().
_mm_maskz_cvtepu32_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu32_ph (__mmask8 __U, __m128i __A) static
Definition at line 1045 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_cvtepu64_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu64_ph (__mmask8 __U, __m128i __A) static
Definition at line 1219 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_cvtpd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtpd_ph (__mmask8 __U, __m128d __A) static
Definition at line 664 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_cvtph_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epi16 (__mmask8 __U, __m128h __A) static
Definition at line 733 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtph_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epi32 (__mmask8 __U, __m128h __A) static
Definition at line 941 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtph_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epi64 (__mmask8 __U, __m128h __A) static
Definition at line 1184 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtph_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epu16 (__mmask8 __U, __m128h __A) static
Definition at line 837 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtph_epu32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epu32 (__mmask8 __U, __m128h __A) static
Definition at line 976 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtph_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_epu64 (__mmask8 __U, __m128h __A) static
Definition at line 1254 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtph_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_cvtph_pd (__mmask8 __U, __m128h __A) static
Definition at line 699 of file avx512vlfp16intrin.h.
References _mm_setzero_pd().
_mm_maskz_cvttph_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epi16 (__mmask8 __U, __m128h __A) static
Definition at line 768 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttph_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epi32 (__mmask8 __U, __m128h __A) static
Definition at line 1079 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttph_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epi64 (__mmask8 __U, __m128h __A) static
Definition at line 1289 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttph_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epu16 (__mmask8 __U, __m128h __A) static
Definition at line 872 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttph_epu32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epu32 (__mmask8 __U, __m128h __A) static
Definition at line 1114 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttph_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttph_epu64 (__mmask8 __U, __m128h __A) static
Definition at line 1324 of file avx512vlfp16intrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtxph_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_cvtxph_ps (__mmask8 __U, __m128h __A) static
Definition at line 1360 of file avx512vlfp16intrin.h.
References _mm_setzero_ps().
_mm_maskz_cvtxps_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_cvtxps_ph (__mmask8 __U, __m128 __A) static
Definition at line 1395 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_div_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_div_ph (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 223 of file avx512vlfp16intrin.h.
References _mm_div_ph(), and _mm_setzero_ph().
_mm_maskz_fcmadd_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fcmadd_pch (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 1848 of file avx512vlfp16intrin.h.
_mm_maskz_fcmul_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fcmul_pch (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1802 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_fmadd_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmadd_pch (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 1942 of file avx512vlfp16intrin.h.
_mm_maskz_fmadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmadd_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 1443 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_fmaddsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmaddsub_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 1599 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_fmsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmsub_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 1467 of file avx512vlfp16intrin.h.
References _mm_fmsub_ph(), and _mm_setzero_ph().
_mm_maskz_fmsubadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmsubadd_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 1622 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_fmul_pch()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fmul_pch (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 1896 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_fnmadd_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fnmadd_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 1482 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_fnmsub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_fnmsub_ph (__mmask8 __U, __m128h __A, __m128h __B, __m128h __C) static
Definition at line 1490 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_getexp_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_getexp_ph (__mmask8 __U, __m128h __A) static
Definition at line 455 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_max_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_max_ph (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 308 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_min_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_min_ph (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 265 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_mul_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_mul_ph (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 186 of file avx512vlfp16intrin.h.
References _mm_mul_ph(), and _mm_setzero_ph().
_mm_maskz_rcp_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_rcp_ph (__mmask8 __U, __m128h __A) static
Definition at line 402 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_rsqrt_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_rsqrt_ph (__mmask8 __U, __m128h __A) static
Definition at line 438 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_scalef_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_scalef_ph (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 520 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_maskz_sqrt_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_sqrt_ph (__mmask8 __U, __m128h __A) static
Definition at line 612 of file avx512vlfp16intrin.h.
References _mm_setzero_ph(), and _mm_sqrt_ph().
_mm_maskz_sub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_maskz_sub_ph (__mmask8 __U, __m128h __A, __m128h __B) static
Definition at line 149 of file avx512vlfp16intrin.h.
References _mm_setzero_ph(), and _mm_sub_ph().
_mm_max_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_max_ph (__m128h __A, __m128h __B) static
Definition at line 294 of file avx512vlfp16intrin.h.
_mm_min_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_min_ph (__m128h __A, __m128h __B) static
Definition at line 251 of file avx512vlfp16intrin.h.
_mm_mul_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_mul_ph (__m128h __A, __m128h __B) static
Definition at line 173 of file avx512vlfp16intrin.h.
Referenced by _mm_mask_mul_ph(), and _mm_maskz_mul_ph().
_mm_permutex2var_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_permutex2var_ph (__m128h __A, __m128i __I, __m128h __B) static
Definition at line 1989 of file avx512vlfp16intrin.h.
_mm_permutexvar_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_permutexvar_ph (__m128i __A, __m128h __B) static
Definition at line 2001 of file avx512vlfp16intrin.h.
_mm_rcp_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_rcp_ph (__m128h __A) static
Definition at line 390 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_reduce_add_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_reduce_add_ph (__m128h __W) static
Definition at line 2031 of file avx512vlfp16intrin.h.
_mm_reduce_max_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_reduce_max_ph (__m128h __V) static
Definition at line 2041 of file avx512vlfp16intrin.h.
_mm_reduce_min_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_reduce_min_ph (__m128h __V) static
Definition at line 2046 of file avx512vlfp16intrin.h.
_mm_reduce_mul_ph()
static __inline__ _Float16 __DEFAULT_FN_ATTRS128 _mm_reduce_mul_ph (__m128h __W) static
Definition at line 2036 of file avx512vlfp16intrin.h.
_mm_rsqrt_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_rsqrt_ph (__m128h __A) static
Definition at line 425 of file avx512vlfp16intrin.h.
References _mm_undefined_ph().
_mm_scalef_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_scalef_ph (__m128h __A, __m128h __B) static
Definition at line 507 of file avx512vlfp16intrin.h.
References _mm_setzero_ph().
_mm_set1_pch()
static __inline __m128h __DEFAULT_FN_ATTRS128 _mm_set1_pch (_Float16 _Complex h) static
Definition at line 60 of file avx512vlfp16intrin.h.
References _mm_set1_ps().
_mm_set1_ph()
static __inline __m128h __DEFAULT_FN_ATTRS128 _mm_set1_ph (_Float16 __h) static
Definition at line 39 of file avx512vlfp16intrin.h.
_mm_set_ph()
static __inline __m128h __DEFAULT_FN_ATTRS128 _mm_set_ph (_Float16 __h1, _Float16 __h2, _Float16 __h3, _Float16 __h4, _Float16 __h5, _Float16 __h6, _Float16 __h7, _Float16 __h8) static
Definition at line 49 of file avx512vlfp16intrin.h.
_mm_set_sh()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_set_sh (_Float16 __h) static
Definition at line 35 of file avx512vlfp16intrin.h.
_mm_sqrt_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_sqrt_ph (__m128h __a) static
Definition at line 601 of file avx512vlfp16intrin.h.
References __a.
Referenced by _mm_mask_sqrt_ph(), and _mm_maskz_sqrt_ph().
_mm_sub_ph()
static __inline__ __m128h __DEFAULT_FN_ATTRS128 _mm_sub_ph (__m128h __A, __m128h __B) static
Definition at line 136 of file avx512vlfp16intrin.h.
Referenced by _mm_mask_sub_ph(), and _mm_maskz_sub_ph().