clang: lib/Headers/avx512vlbwintrin.h File Reference
avx512vlbwintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS256
#define _mm_cmp_epi8_mask(a, b, p)
#define _mm_mask_cmp_epi8_mask(m, a, b, p)
#define _mm_cmp_epu8_mask(a, b, p)
#define _mm_mask_cmp_epu8_mask(m, a, b, p)
#define _mm256_cmp_epi8_mask(a, b, p)
#define _mm256_mask_cmp_epi8_mask(m, a, b, p)
#define _mm256_cmp_epu8_mask(a, b, p)
#define _mm256_mask_cmp_epu8_mask(m, a, b, p)
#define _mm_cmp_epi16_mask(a, b, p)
#define _mm_mask_cmp_epi16_mask(m, a, b, p)
#define _mm_cmp_epu16_mask(a, b, p)
#define _mm_mask_cmp_epu16_mask(m, a, b, p)
#define _mm256_cmp_epi16_mask(a, b, p)
#define _mm256_mask_cmp_epi16_mask(m, a, b, p)
#define _mm256_cmp_epu16_mask(a, b, p)
#define _mm256_mask_cmp_epu16_mask(m, a, b, p)
#define _mm_cmpeq_epi8_mask(A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_EQ)
#define _mm_mask_cmpeq_epi8_mask(k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm_cmpge_epi8_mask(A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_GE)
#define _mm_mask_cmpge_epi8_mask(k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm_cmpgt_epi8_mask(A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_GT)
#define _mm_mask_cmpgt_epi8_mask(k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm_cmple_epi8_mask(A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_LE)
#define _mm_mask_cmple_epi8_mask(k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm_cmplt_epi8_mask(A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_LT)
#define _mm_mask_cmplt_epi8_mask(k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm_cmpneq_epi8_mask(A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_NE)
#define _mm_mask_cmpneq_epi8_mask(k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm256_cmpeq_epi8_mask(A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_EQ)
#define _mm256_mask_cmpeq_epi8_mask(k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm256_cmpge_epi8_mask(A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_GE)
#define _mm256_mask_cmpge_epi8_mask(k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm256_cmpgt_epi8_mask(A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_GT)
#define _mm256_mask_cmpgt_epi8_mask(k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm256_cmple_epi8_mask(A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_LE)
#define _mm256_mask_cmple_epi8_mask(k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm256_cmplt_epi8_mask(A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_LT)
#define _mm256_mask_cmplt_epi8_mask(k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm256_cmpneq_epi8_mask(A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_NE)
#define _mm256_mask_cmpneq_epi8_mask(k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm_cmpeq_epu8_mask(A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_EQ)
#define _mm_mask_cmpeq_epu8_mask(k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm_cmpge_epu8_mask(A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_GE)
#define _mm_mask_cmpge_epu8_mask(k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm_cmpgt_epu8_mask(A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_GT)
#define _mm_mask_cmpgt_epu8_mask(k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm_cmple_epu8_mask(A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_LE)
#define _mm_mask_cmple_epu8_mask(k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm_cmplt_epu8_mask(A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_LT)
#define _mm_mask_cmplt_epu8_mask(k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm_cmpneq_epu8_mask(A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_NE)
#define _mm_mask_cmpneq_epu8_mask(k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm256_cmpeq_epu8_mask(A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_EQ)
#define _mm256_mask_cmpeq_epu8_mask(k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm256_cmpge_epu8_mask(A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_GE)
#define _mm256_mask_cmpge_epu8_mask(k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm256_cmpgt_epu8_mask(A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_GT)
#define _mm256_mask_cmpgt_epu8_mask(k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm256_cmple_epu8_mask(A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_LE)
#define _mm256_mask_cmple_epu8_mask(k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm256_cmplt_epu8_mask(A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_LT)
#define _mm256_mask_cmplt_epu8_mask(k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm256_cmpneq_epu8_mask(A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_NE)
#define _mm256_mask_cmpneq_epu8_mask(k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm_cmpeq_epi16_mask(A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_EQ)
#define _mm_mask_cmpeq_epi16_mask(k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm_cmpge_epi16_mask(A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_GE)
#define _mm_mask_cmpge_epi16_mask(k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm_cmpgt_epi16_mask(A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_GT)
#define _mm_mask_cmpgt_epi16_mask(k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm_cmple_epi16_mask(A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_LE)
#define _mm_mask_cmple_epi16_mask(k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm_cmplt_epi16_mask(A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_LT)
#define _mm_mask_cmplt_epi16_mask(k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm_cmpneq_epi16_mask(A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_NE)
#define _mm_mask_cmpneq_epi16_mask(k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm256_cmpeq_epi16_mask(A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_EQ)
#define _mm256_mask_cmpeq_epi16_mask(k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm256_cmpge_epi16_mask(A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_GE)
#define _mm256_mask_cmpge_epi16_mask(k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm256_cmpgt_epi16_mask(A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_GT)
#define _mm256_mask_cmpgt_epi16_mask(k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm256_cmple_epi16_mask(A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_LE)
#define _mm256_mask_cmple_epi16_mask(k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm256_cmplt_epi16_mask(A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_LT)
#define _mm256_mask_cmplt_epi16_mask(k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm256_cmpneq_epi16_mask(A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_NE)
#define _mm256_mask_cmpneq_epi16_mask(k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm_cmpeq_epu16_mask(A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_EQ)
#define _mm_mask_cmpeq_epu16_mask(k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm_cmpge_epu16_mask(A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_GE)
#define _mm_mask_cmpge_epu16_mask(k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm_cmpgt_epu16_mask(A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_GT)
#define _mm_mask_cmpgt_epu16_mask(k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm_cmple_epu16_mask(A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_LE)
#define _mm_mask_cmple_epu16_mask(k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm_cmplt_epu16_mask(A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_LT)
#define _mm_mask_cmplt_epu16_mask(k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm_cmpneq_epu16_mask(A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_NE)
#define _mm_mask_cmpneq_epu16_mask(k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm256_cmpeq_epu16_mask(A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_EQ)
#define _mm256_mask_cmpeq_epu16_mask(k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm256_cmpge_epu16_mask(A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_GE)
#define _mm256_mask_cmpge_epu16_mask(k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm256_cmpgt_epu16_mask(A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_GT)
#define _mm256_mask_cmpgt_epu16_mask(k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm256_cmple_epu16_mask(A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_LE)
#define _mm256_mask_cmple_epu16_mask(k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm256_cmplt_epu16_mask(A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_LT)
#define _mm256_mask_cmplt_epu16_mask(k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm256_cmpneq_epu16_mask(A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_NE)
#define _mm256_mask_cmpneq_epu16_mask(k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm_mask_shufflehi_epi16(W, U, A, imm)
#define _mm_maskz_shufflehi_epi16(U, A, imm)
#define _mm256_mask_shufflehi_epi16(W, U, A, imm)
#define _mm256_maskz_shufflehi_epi16(U, A, imm)
#define _mm_mask_shufflelo_epi16(W, U, A, imm)
#define _mm_maskz_shufflelo_epi16(U, A, imm)
#define _mm256_mask_shufflelo_epi16(W, U, A, imm)
#define _mm256_maskz_shufflelo_epi16(U, A, imm)
#define _mm_mask_alignr_epi8(W, U, A, B, N)
#define _mm_maskz_alignr_epi8(U, A, B, N)
#define _mm256_mask_alignr_epi8(W, U, A, B, N)
#define _mm256_maskz_alignr_epi8(U, A, B, N)
#define _mm_dbsad_epu8(A, B, imm)
#define _mm_mask_dbsad_epu8(W, U, A, B, imm)
#define _mm_maskz_dbsad_epu8(U, A, B, imm)
#define _mm256_dbsad_epu8(A, B, imm)
#define _mm256_mask_dbsad_epu8(W, U, A, B, imm)
#define _mm256_maskz_dbsad_epu8(U, A, B, imm)
Functions
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_add_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_add_epi8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_add_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_add_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sub_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sub_epi8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sub_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sub_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_add_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_add_epi8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_add_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_add_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sub_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sub_epi8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sub_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sub_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mullo_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mullo_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mullo_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mullo_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_blend_epi8 (__mmask16 __U, __m128i __A, __m128i __W)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_blend_epi8 (__mmask32 __U, __m256i __A, __m256i __W)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_blend_epi16 (__mmask8 __U, __m128i __A, __m128i __W)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_blend_epi16 (__mmask16 __U, __m256i __A, __m256i __W)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_abs_epi8 (__m128i __W, __mmask16 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_abs_epi8 (__mmask16 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_abs_epi8 (__m256i __W, __mmask32 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_abs_epi8 (__mmask32 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_abs_epi16 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_abs_epi16 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_abs_epi16 (__m256i __W, __mmask16 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_abs_epi16 (__mmask16 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_packs_epi32 (__mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_packs_epi32 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_packs_epi32 (__mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_packs_epi32 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_packs_epi16 (__mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_packs_epi16 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_packs_epi16 (__mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_packs_epi16 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_packus_epi32 (__mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_packus_epi32 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_packus_epi32 (__mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_packus_epi32 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_packus_epi16 (__mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_packus_epi16 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_packus_epi16 (__mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_packus_epi16 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_adds_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_adds_epi8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_adds_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_adds_epi8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_adds_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_adds_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_adds_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_adds_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_adds_epu8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_adds_epu8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_adds_epu8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_adds_epu8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_adds_epu16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_adds_epu16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_adds_epu16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_adds_epu16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_avg_epu8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_avg_epu8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_avg_epu8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_avg_epu8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_avg_epu16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_avg_epu16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_avg_epu16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_avg_epu16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_max_epi8 (__mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_max_epi8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_max_epi8 (__mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_max_epi8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_max_epi16 (__mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_max_epi16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_max_epi16 (__mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_max_epi16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_max_epu8 (__mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_max_epu8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_max_epu8 (__mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_max_epu8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_max_epu16 (__mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_max_epu16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_max_epu16 (__mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_max_epu16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_min_epi8 (__mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_min_epi8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_min_epi8 (__mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_min_epi8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_min_epi16 (__mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_min_epi16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_min_epi16 (__mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_min_epi16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_min_epu8 (__mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_min_epu8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_min_epu8 (__mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_min_epu8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_min_epu16 (__mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_min_epu16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_min_epu16 (__mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_min_epu16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shuffle_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shuffle_epi8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shuffle_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shuffle_epi8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_subs_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_subs_epi8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_subs_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_subs_epi8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_subs_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_subs_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_subs_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_subs_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_subs_epu8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_subs_epu8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_subs_epu8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_subs_epu8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_subs_epu16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_subs_epu16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_subs_epu16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_subs_epu16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_permutex2var_epi16 (__m128i __A, __m128i __I, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_permutex2var_epi16 (__m128i __A, __mmask8 __U, __m128i __I, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask2_permutex2var_epi16 (__m128i __A, __m128i __I, __mmask8 __U, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_permutex2var_epi16 (__mmask8 __U, __m128i __A, __m128i __I, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_permutex2var_epi16 (__m256i __A, __m256i __I, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_permutex2var_epi16 (__m256i __A, __mmask16 __U, __m256i __I, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask2_permutex2var_epi16 (__m256i __A, __m256i __I, __mmask16 __U, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_permutex2var_epi16 (__mmask16 __U, __m256i __A, __m256i __I, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_maddubs_epi16 (__m128i __W, __mmask8 __U, __m128i __X, __m128i __Y)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_maddubs_epi16 (__mmask8 __U, __m128i __X, __m128i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_maddubs_epi16 (__m256i __W, __mmask16 __U, __m256i __X, __m256i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_maddubs_epi16 (__mmask16 __U, __m256i __X, __m256i __Y)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_madd_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_madd_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_madd_epi16 (__m256i __W, __mmask8 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_madd_epi16 (__mmask8 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtsepi16_epi8 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtsepi16_epi8 (__m128i __O, __mmask8 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtsepi16_epi8 (__mmask8 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_cvtsepi16_epi8 (__m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtsepi16_epi8 (__m128i __O, __mmask16 __M, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtsepi16_epi8 (__mmask16 __M, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtusepi16_epi8 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtusepi16_epi8 (__m128i __O, __mmask8 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtusepi16_epi8 (__mmask8 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_cvtusepi16_epi8 (__m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtusepi16_epi8 (__m128i __O, __mmask16 __M, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtusepi16_epi8 (__mmask16 __M, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtepi16_epi8 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi16_epi8 (__m128i __O, __mmask8 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi16_epi8 (__mmask8 __M, __m128i __A)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi16_storeu_epi8 (void *__P, __mmask8 __M, __m128i __A)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_cvtsepi16_storeu_epi8 (void *__P, __mmask8 __M, __m128i __A)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_cvtusepi16_storeu_epi8 (void *__P, __mmask8 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_cvtepi16_epi8 (__m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi16_epi8 (__m128i __O, __mmask16 __M, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi16_epi8 (__mmask16 __M, __m256i __A)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi16_storeu_epi8 (void *__P, __mmask16 __M, __m256i __A)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_cvtsepi16_storeu_epi8 (void *__P, __mmask16 __M, __m256i __A)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_cvtusepi16_storeu_epi8 (void *__P, __mmask16 __M, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mulhrs_epi16 (__m128i __W, __mmask8 __U, __m128i __X, __m128i __Y)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mulhrs_epi16 (__mmask8 __U, __m128i __X, __m128i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mulhrs_epi16 (__m256i __W, __mmask16 __U, __m256i __X, __m256i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mulhrs_epi16 (__mmask16 __U, __m256i __X, __m256i __Y)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mulhi_epu16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mulhi_epu16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mulhi_epu16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mulhi_epu16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mulhi_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mulhi_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mulhi_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mulhi_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_unpackhi_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_unpackhi_epi8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_unpackhi_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_unpackhi_epi8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_unpackhi_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_unpackhi_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_unpackhi_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_unpackhi_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_unpacklo_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_unpacklo_epi8 (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_unpacklo_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_unpacklo_epi8 (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_unpacklo_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_unpacklo_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_unpacklo_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_unpacklo_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi8_epi16 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi8_epi16 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi8_epi16 (__m256i __W, __mmask16 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi8_epi16 (__mmask16 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu8_epi16 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu8_epi16 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu8_epi16 (__m256i __W, __mmask16 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu8_epi16 (__mmask16 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_sllv_epi16 (__m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sllv_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sllv_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_sllv_epi16 (__m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sllv_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sllv_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sll_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sll_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sll_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sll_epi16 (__mmask16 __U, __m256i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_slli_epi16 (__m128i __W, __mmask8 __U, __m128i __A, unsigned int __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_slli_epi16 (__mmask8 __U, __m128i __A, unsigned int __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_slli_epi16 (__m256i __W, __mmask16 __U, __m256i __A, unsigned int __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_slli_epi16 (__mmask16 __U, __m256i __A, unsigned int __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_srlv_epi16 (__m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srlv_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srlv_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_srlv_epi16 (__m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srlv_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srlv_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_srav_epi16 (__m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srav_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srav_epi16 (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_srav_epi16 (__m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srav_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srav_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sra_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sra_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sra_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sra_epi16 (__mmask16 __U, __m256i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srai_epi16 (__m128i __W, __mmask8 __U, __m128i __A, unsigned int __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srai_epi16 (__mmask8 __U, __m128i __A, unsigned int __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srai_epi16 (__m256i __W, __mmask16 __U, __m256i __A, unsigned int __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srai_epi16 (__mmask16 __U, __m256i __A, unsigned int __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srl_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srl_epi16 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srl_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srl_epi16 (__mmask16 __U, __m256i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srli_epi16 (__m128i __W, __mmask8 __U, __m128i __A, int __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srli_epi16 (__mmask8 __U, __m128i __A, int __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srli_epi16 (__m256i __W, __mmask16 __U, __m256i __A, int __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srli_epi16 (__mmask16 __U, __m256i __A, int __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mov_epi16 (__m128i __W, __mmask8 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mov_epi16 (__mmask8 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mov_epi16 (__m256i __W, __mmask16 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mov_epi16 (__mmask16 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mov_epi8 (__m128i __W, __mmask16 __U, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mov_epi8 (__mmask16 __U, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mov_epi8 (__m256i __W, __mmask32 __U, __m256i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mov_epi8 (__mmask32 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_set1_epi8 (__m128i __O, __mmask16 __M, char __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_set1_epi8 (__mmask16 __M, char __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_set1_epi8 (__m256i __O, __mmask32 __M, char __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_set1_epi8 (__mmask32 __M, char __A)
static __inline __m128i __DEFAULT_FN_ATTRS128 _mm_loadu_epi16 (void const *__P)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_loadu_epi16 (__m128i __W, __mmask8 __U, void const *__P)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_loadu_epi16 (__mmask8 __U, void const *__P)
static __inline __m256i __DEFAULT_FN_ATTRS256 _mm256_loadu_epi16 (void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_loadu_epi16 (__m256i __W, __mmask16 __U, void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_loadu_epi16 (__mmask16 __U, void const *__P)
static __inline __m128i __DEFAULT_FN_ATTRS128 _mm_loadu_epi8 (void const *__P)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_loadu_epi8 (__m128i __W, __mmask16 __U, void const *__P)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_loadu_epi8 (__mmask16 __U, void const *__P)
static __inline __m256i __DEFAULT_FN_ATTRS256 _mm256_loadu_epi8 (void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_loadu_epi8 (__m256i __W, __mmask32 __U, void const *__P)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_loadu_epi8 (__mmask32 __U, void const *__P)
static __inline void __DEFAULT_FN_ATTRS128 _mm_storeu_epi16 (void *__P, __m128i __A)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_storeu_epi16 (void *__P, __mmask8 __U, __m128i __A)
static __inline void __DEFAULT_FN_ATTRS256 _mm256_storeu_epi16 (void *__P, __m256i __A)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_storeu_epi16 (void *__P, __mmask16 __U, __m256i __A)
static __inline void __DEFAULT_FN_ATTRS128 _mm_storeu_epi8 (void *__P, __m128i __A)
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_storeu_epi8 (void *__P, __mmask16 __U, __m128i __A)
static __inline void __DEFAULT_FN_ATTRS256 _mm256_storeu_epi8 (void *__P, __m256i __A)
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_storeu_epi8 (void *__P, __mmask32 __U, __m256i __A)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_test_epi8_mask (__m128i __A, __m128i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_mask_test_epi8_mask (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_test_epi8_mask (__m256i __A, __m256i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_mask_test_epi8_mask (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_test_epi16_mask (__m128i __A, __m128i __B)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_mask_test_epi16_mask (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_test_epi16_mask (__m256i __A, __m256i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_mask_test_epi16_mask (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_testn_epi8_mask (__m128i __A, __m128i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_mask_testn_epi8_mask (__mmask16 __U, __m128i __A, __m128i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_testn_epi8_mask (__m256i __A, __m256i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_mask_testn_epi8_mask (__mmask32 __U, __m256i __A, __m256i __B)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_testn_epi16_mask (__m128i __A, __m128i __B)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_mask_testn_epi16_mask (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_testn_epi16_mask (__m256i __A, __m256i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_mask_testn_epi16_mask (__mmask16 __U, __m256i __A, __m256i __B)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_movepi8_mask (__m128i __A)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_movepi8_mask (__m256i __A)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_movepi16_mask (__m128i __A)
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_movepi16_mask (__m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_movm_epi8 (__mmask16 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_movm_epi8 (__mmask32 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_movm_epi16 (__mmask8 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_movm_epi16 (__mmask16 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_broadcastb_epi8 (__m128i __O, __mmask16 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_broadcastb_epi8 (__mmask16 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_broadcastb_epi8 (__m256i __O, __mmask32 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcastb_epi8 (__mmask32 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_broadcastw_epi16 (__m128i __O, __mmask8 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_broadcastw_epi16 (__mmask8 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_broadcastw_epi16 (__m256i __O, __mmask16 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcastw_epi16 (__mmask16 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_set1_epi16 (__m256i __O, __mmask16 __M, short __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_set1_epi16 (__mmask16 __M, short __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_set1_epi16 (__m128i __O, __mmask8 __M, short __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_set1_epi16 (__mmask8 __M, short __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_permutexvar_epi16 (__m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_permutexvar_epi16 (__mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_permutexvar_epi16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_permutexvar_epi16 (__m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_permutexvar_epi16 (__mmask16 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_permutexvar_epi16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_add_epi16 (__m128i __W)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_mul_epi16 (__m128i __W)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_and_epi16 (__m128i __W)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_or_epi16 (__m128i __W)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_add_epi16 (__mmask8 __M, __m128i __W)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_mul_epi16 (__mmask8 __M, __m128i __W)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_and_epi16 (__mmask8 __M, __m128i __W)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_or_epi16 (__mmask8 __M, __m128i __W)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_max_epi16 (__m128i __V)
static __inline__ unsigned short __DEFAULT_FN_ATTRS128 _mm_reduce_max_epu16 (__m128i __V)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_min_epi16 (__m128i __V)
static __inline__ unsigned short __DEFAULT_FN_ATTRS128 _mm_reduce_min_epu16 (__m128i __V)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_max_epi16 (__mmask16 __M, __m128i __V)
static __inline__ unsigned short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_max_epu16 (__mmask16 __M, __m128i __V)
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_min_epi16 (__mmask16 __M, __m128i __V)
static __inline__ unsigned short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_min_epu16 (__mmask16 __M, __m128i __V)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_add_epi16 (__m256i __W)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_mul_epi16 (__m256i __W)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_and_epi16 (__m256i __W)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_or_epi16 (__m256i __W)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_add_epi16 (__mmask16 __M, __m256i __W)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_mul_epi16 (__mmask16 __M, __m256i __W)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_and_epi16 (__mmask16 __M, __m256i __W)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_or_epi16 (__mmask16 __M, __m256i __W)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_max_epi16 (__m256i __V)
static __inline__ unsigned short __DEFAULT_FN_ATTRS256 _mm256_reduce_max_epu16 (__m256i __V)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_min_epi16 (__m256i __V)
static __inline__ unsigned short __DEFAULT_FN_ATTRS256 _mm256_reduce_min_epu16 (__m256i __V)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_max_epi16 (__mmask16 __M, __m256i __V)
static __inline__ unsigned short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_max_epu16 (__mmask16 __M, __m256i __V)
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_min_epi16 (__mmask16 __M, __m256i __V)
static __inline__ unsigned short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_min_epu16 (__mmask16 __M, __m256i __V)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_add_epi8 (__m128i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_mul_epi8 (__m128i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_and_epi8 (__m128i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_or_epi8 (__m128i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_add_epi8 (__mmask16 __M, __m128i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_mul_epi8 (__mmask16 __M, __m128i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_and_epi8 (__mmask16 __M, __m128i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_or_epi8 (__mmask16 __M, __m128i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_max_epi8 (__m128i __V)
static __inline__ unsigned char __DEFAULT_FN_ATTRS128 _mm_reduce_max_epu8 (__m128i __V)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_min_epi8 (__m128i __V)
static __inline__ unsigned char __DEFAULT_FN_ATTRS128 _mm_reduce_min_epu8 (__m128i __V)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_max_epi8 (__mmask16 __M, __m128i __V)
static __inline__ unsigned char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_max_epu8 (__mmask16 __M, __m128i __V)
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_min_epi8 (__mmask16 __M, __m128i __V)
static __inline__ unsigned char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_min_epu8 (__mmask16 __M, __m128i __V)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_add_epi8 (__m256i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_mul_epi8 (__m256i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_and_epi8 (__m256i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_or_epi8 (__m256i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_add_epi8 (__mmask32 __M, __m256i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_mul_epi8 (__mmask32 __M, __m256i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_and_epi8 (__mmask32 __M, __m256i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_or_epi8 (__mmask32 __M, __m256i __W)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_max_epi8 (__m256i __V)
static __inline__ unsigned char __DEFAULT_FN_ATTRS256 _mm256_reduce_max_epu8 (__m256i __V)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_min_epi8 (__m256i __V)
static __inline__ unsigned char __DEFAULT_FN_ATTRS256 _mm256_reduce_min_epu8 (__m256i __V)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_max_epi8 (__mmask32 __M, __m256i __V)
static __inline__ unsigned char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_max_epu8 (__mmask32 __M, __m256i __V)
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_min_epi8 (__mmask32 __M, __m256i __V)
static __inline__ unsigned char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_min_epu8 (__mmask32 __M, __m256i __V)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128
Value:
  __attribute__((__always_inline__, __nodebug__,                               \
                 __target__("avx512vl,avx512bw,no-evex512"),                   \
                 __min_vector_width__(128)))
Definition at line 18 of file avx512vlbwintrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256
Value:
  __attribute__((__always_inline__, __nodebug__,                               \
                 __target__("avx512vl,avx512bw,no-evex512"),                   \
                 __min_vector_width__(256)))
Definition at line 22 of file avx512vlbwintrin.h.
_mm256_cmp_epi16_mask
#define _mm256_cmp_epi16_mask (a, b, p)
Value:
  ((__mmask16)__builtin_ia32_cmpw256_mask((__v16hi)(__m256i)(a), \
                                          (__v16hi)(__m256i)(b), (int)(p), \
                                          (__mmask16)-1))
Definition at line 89 of file avx512vlbwintrin.h.
_mm256_cmp_epi8_mask
#define _mm256_cmp_epi8_mask (a, b, p)
Value:
  ((__mmask32)__builtin_ia32_cmpb256_mask((__v32qi)(__m256i)(a), \
                                          (__v32qi)(__m256i)(b), (int)(p), \
                                          (__mmask32)-1))
Definition at line 49 of file avx512vlbwintrin.h.
_mm256_cmp_epu16_mask
#define _mm256_cmp_epu16_mask (a, b, p)
Value:
  ((__mmask16)__builtin_ia32_ucmpw256_mask((__v16hi)(__m256i)(a), \
                                           (__v16hi)(__m256i)(b), (int)(p), \
                                           (__mmask16)-1))
Definition at line 99 of file avx512vlbwintrin.h.
_mm256_cmp_epu8_mask
#define _mm256_cmp_epu8_mask (a, b, p)
Value:
  ((__mmask32)__builtin_ia32_ucmpb256_mask((__v32qi)(__m256i)(a), \
                                           (__v32qi)(__m256i)(b), (int)(p), \
                                           (__mmask32)-1))
Definition at line 59 of file avx512vlbwintrin.h.
_mm256_cmpeq_epi16_mask
#define _mm256_cmpeq_epi16_mask (A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 234 of file avx512vlbwintrin.h.
_mm256_cmpeq_epi8_mask
#define _mm256_cmpeq_epi8_mask (A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 134 of file avx512vlbwintrin.h.
_mm256_cmpeq_epu16_mask
#define _mm256_cmpeq_epu16_mask (A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 284 of file avx512vlbwintrin.h.
_mm256_cmpeq_epu8_mask
#define _mm256_cmpeq_epu8_mask (A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 184 of file avx512vlbwintrin.h.
_mm256_cmpge_epi16_mask
#define _mm256_cmpge_epi16_mask (A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_GE)
Definition at line 238 of file avx512vlbwintrin.h.
_mm256_cmpge_epi8_mask
#define _mm256_cmpge_epi8_mask (A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_GE)
Definition at line 138 of file avx512vlbwintrin.h.
_mm256_cmpge_epu16_mask
#define _mm256_cmpge_epu16_mask (A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_GE)
Definition at line 288 of file avx512vlbwintrin.h.
_mm256_cmpge_epu8_mask
#define _mm256_cmpge_epu8_mask (A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_GE)
Definition at line 188 of file avx512vlbwintrin.h.
_mm256_cmpgt_epi16_mask
#define _mm256_cmpgt_epi16_mask (A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_GT)
Definition at line 242 of file avx512vlbwintrin.h.
_mm256_cmpgt_epi8_mask
#define _mm256_cmpgt_epi8_mask (A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_GT)
Definition at line 142 of file avx512vlbwintrin.h.
_mm256_cmpgt_epu16_mask
#define _mm256_cmpgt_epu16_mask (A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_GT)
Definition at line 292 of file avx512vlbwintrin.h.
_mm256_cmpgt_epu8_mask
#define _mm256_cmpgt_epu8_mask (A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_GT)
Definition at line 192 of file avx512vlbwintrin.h.
_mm256_cmple_epi16_mask
#define _mm256_cmple_epi16_mask (A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_LE)
Definition at line 246 of file avx512vlbwintrin.h.
_mm256_cmple_epi8_mask
#define _mm256_cmple_epi8_mask (A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_LE)
Definition at line 146 of file avx512vlbwintrin.h.
_mm256_cmple_epu16_mask
#define _mm256_cmple_epu16_mask (A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_LE)
Definition at line 296 of file avx512vlbwintrin.h.
_mm256_cmple_epu8_mask
#define _mm256_cmple_epu8_mask (A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_LE)
Definition at line 196 of file avx512vlbwintrin.h.
_mm256_cmplt_epi16_mask
#define _mm256_cmplt_epi16_mask (A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_LT)
Definition at line 250 of file avx512vlbwintrin.h.
_mm256_cmplt_epi8_mask
#define _mm256_cmplt_epi8_mask (A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_LT)
Definition at line 150 of file avx512vlbwintrin.h.
_mm256_cmplt_epu16_mask
#define _mm256_cmplt_epu16_mask (A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_LT)
Definition at line 300 of file avx512vlbwintrin.h.
_mm256_cmplt_epu8_mask
#define _mm256_cmplt_epu8_mask (A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_LT)
Definition at line 200 of file avx512vlbwintrin.h.
_mm256_cmpneq_epi16_mask
#define _mm256_cmpneq_epi16_mask (A, B) _mm256_cmp_epi16_mask((A), (B), _MM_CMPINT_NE)
Definition at line 254 of file avx512vlbwintrin.h.
_mm256_cmpneq_epi8_mask
#define _mm256_cmpneq_epi8_mask (A, B) _mm256_cmp_epi8_mask((A), (B), _MM_CMPINT_NE)
Definition at line 154 of file avx512vlbwintrin.h.
_mm256_cmpneq_epu16_mask
#define _mm256_cmpneq_epu16_mask (A, B) _mm256_cmp_epu16_mask((A), (B), _MM_CMPINT_NE)
Definition at line 304 of file avx512vlbwintrin.h.
_mm256_cmpneq_epu8_mask
#define _mm256_cmpneq_epu8_mask (A, B) _mm256_cmp_epu8_mask((A), (B), _MM_CMPINT_NE)
Definition at line 204 of file avx512vlbwintrin.h.
_mm256_dbsad_epu8
#define _mm256_dbsad_epu8 (A, B, imm)
Value:
  ((__m256i)__builtin_ia32_dbpsadbw256((__v32qi)(__m256i)(A), \
                                       (__v32qi)(__m256i)(B), (int)(imm)))
Definition at line 2798 of file avx512vlbwintrin.h.
_mm256_mask_alignr_epi8
#define _mm256_mask_alignr_epi8 (W, U, A, B, N)
Value:
  ((__m256i)__builtin_ia32_selectb_256((__mmask32)(U), \
                              (__v32qi)_mm256_alignr_epi8((A), (B), (int)(N)), \
                              (__v32qi)(__m256i)(W)))
Definition at line 2774 of file avx512vlbwintrin.h.
_mm256_mask_cmp_epi16_mask
#define _mm256_mask_cmp_epi16_mask (m, a, b, p)
Value:
  ((__mmask16)__builtin_ia32_cmpw256_mask((__v16hi)(__m256i)(a), \
                                          (__v16hi)(__m256i)(b), (int)(p), \
                                          (__mmask16)(m)))
Definition at line 94 of file avx512vlbwintrin.h.
_mm256_mask_cmp_epi8_mask
#define _mm256_mask_cmp_epi8_mask (m, a, b, p)
Value:
  ((__mmask32)__builtin_ia32_cmpb256_mask((__v32qi)(__m256i)(a), \
                                          (__v32qi)(__m256i)(b), (int)(p), \
                                          (__mmask32)(m)))
Definition at line 54 of file avx512vlbwintrin.h.
_mm256_mask_cmp_epu16_mask
#define _mm256_mask_cmp_epu16_mask (m, a, b, p)
Value:
  ((__mmask16)__builtin_ia32_ucmpw256_mask((__v16hi)(__m256i)(a), \
                                           (__v16hi)(__m256i)(b), (int)(p), \
                                           (__mmask16)(m)))
Definition at line 104 of file avx512vlbwintrin.h.
_mm256_mask_cmp_epu8_mask
#define _mm256_mask_cmp_epu8_mask (m, a, b, p)
Value:
  ((__mmask32)__builtin_ia32_ucmpb256_mask((__v32qi)(__m256i)(a), \
                                           (__v32qi)(__m256i)(b), (int)(p), \
                                           (__mmask32)(m)))
Definition at line 64 of file avx512vlbwintrin.h.
_mm256_mask_cmpeq_epi16_mask
#define _mm256_mask_cmpeq_epi16_mask (k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 236 of file avx512vlbwintrin.h.
_mm256_mask_cmpeq_epi8_mask
#define _mm256_mask_cmpeq_epi8_mask (k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 136 of file avx512vlbwintrin.h.
_mm256_mask_cmpeq_epu16_mask
#define _mm256_mask_cmpeq_epu16_mask (k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 286 of file avx512vlbwintrin.h.
_mm256_mask_cmpeq_epu8_mask
#define _mm256_mask_cmpeq_epu8_mask (k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 186 of file avx512vlbwintrin.h.
_mm256_mask_cmpge_epi16_mask
#define _mm256_mask_cmpge_epi16_mask (k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 240 of file avx512vlbwintrin.h.
_mm256_mask_cmpge_epi8_mask
#define _mm256_mask_cmpge_epi8_mask (k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 140 of file avx512vlbwintrin.h.
_mm256_mask_cmpge_epu16_mask
#define _mm256_mask_cmpge_epu16_mask (k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 290 of file avx512vlbwintrin.h.
_mm256_mask_cmpge_epu8_mask
#define _mm256_mask_cmpge_epu8_mask (k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 190 of file avx512vlbwintrin.h.
_mm256_mask_cmpgt_epi16_mask
#define _mm256_mask_cmpgt_epi16_mask (k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 244 of file avx512vlbwintrin.h.
_mm256_mask_cmpgt_epi8_mask
#define _mm256_mask_cmpgt_epi8_mask (k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 144 of file avx512vlbwintrin.h.
_mm256_mask_cmpgt_epu16_mask
#define _mm256_mask_cmpgt_epu16_mask (k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 294 of file avx512vlbwintrin.h.
_mm256_mask_cmpgt_epu8_mask
#define _mm256_mask_cmpgt_epu8_mask (k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 194 of file avx512vlbwintrin.h.
_mm256_mask_cmple_epi16_mask
#define _mm256_mask_cmple_epi16_mask (k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 248 of file avx512vlbwintrin.h.
_mm256_mask_cmple_epi8_mask
#define _mm256_mask_cmple_epi8_mask (k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 148 of file avx512vlbwintrin.h.
_mm256_mask_cmple_epu16_mask
#define _mm256_mask_cmple_epu16_mask (k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 298 of file avx512vlbwintrin.h.
_mm256_mask_cmple_epu8_mask
#define _mm256_mask_cmple_epu8_mask (k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 198 of file avx512vlbwintrin.h.
_mm256_mask_cmplt_epi16_mask
#define _mm256_mask_cmplt_epi16_mask (k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 252 of file avx512vlbwintrin.h.
_mm256_mask_cmplt_epi8_mask
#define _mm256_mask_cmplt_epi8_mask (k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 152 of file avx512vlbwintrin.h.
_mm256_mask_cmplt_epu16_mask
#define _mm256_mask_cmplt_epu16_mask (k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 302 of file avx512vlbwintrin.h.
_mm256_mask_cmplt_epu8_mask
#define _mm256_mask_cmplt_epu8_mask (k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 202 of file avx512vlbwintrin.h.
_mm256_mask_cmpneq_epi16_mask
#define _mm256_mask_cmpneq_epi16_mask (k, A, B) _mm256_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 256 of file avx512vlbwintrin.h.
_mm256_mask_cmpneq_epi8_mask
#define _mm256_mask_cmpneq_epi8_mask (k, A, B) _mm256_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 156 of file avx512vlbwintrin.h.
_mm256_mask_cmpneq_epu16_mask
#define _mm256_mask_cmpneq_epu16_mask (k, A, B) _mm256_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 306 of file avx512vlbwintrin.h.
_mm256_mask_cmpneq_epu8_mask
#define _mm256_mask_cmpneq_epu8_mask (k, A, B) _mm256_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 206 of file avx512vlbwintrin.h.
_mm256_mask_dbsad_epu8
#define _mm256_mask_dbsad_epu8 (W, U, A, B, imm)
Value:
  ((__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                  (__v16hi)_mm256_dbsad_epu8((A), (B), (imm)), \
                                  (__v16hi)(__m256i)(W)))
Definition at line 2802 of file avx512vlbwintrin.h.
_mm256_mask_shufflehi_epi16
#define _mm256_mask_shufflehi_epi16 (W, U, A, imm)
Value:
  ((__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                       (__v16hi)_mm256_shufflehi_epi16((A), (imm)), \
                                       (__v16hi)(__m256i)(W)))
Definition at line 1839 of file avx512vlbwintrin.h.
_mm256_mask_shufflelo_epi16
#define _mm256_mask_shufflelo_epi16 (W, U, A, imm)
Value:
  ((__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                       (__v16hi)_mm256_shufflelo_epi16((A), \
                                                                       (imm)), \
                                       (__v16hi)(__m256i)(W)))
Definition at line 1859 of file avx512vlbwintrin.h.
_mm256_maskz_alignr_epi8
#define _mm256_maskz_alignr_epi8 (U, A, B, N)
Value:
  ((__m256i)__builtin_ia32_selectb_256((__mmask32)(U), \
                              (__v32qi)_mm256_alignr_epi8((A), (B), (int)(N)), \
                              (__v32qi)_mm256_setzero_si256()))
Definition at line 2779 of file avx512vlbwintrin.h.
_mm256_maskz_dbsad_epu8
#define _mm256_maskz_dbsad_epu8 (U, A, B, imm)
Value:
  ((__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                  (__v16hi)_mm256_dbsad_epu8((A), (B), (imm)), \
                                  (__v16hi)_mm256_setzero_si256()))
Definition at line 2807 of file avx512vlbwintrin.h.
_mm256_maskz_shufflehi_epi16
#define _mm256_maskz_shufflehi_epi16 (U, A, imm)
Value:
  ((__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                       (__v16hi)_mm256_shufflehi_epi16((A), (imm)), \
                                       (__v16hi)_mm256_setzero_si256()))
Definition at line 1844 of file avx512vlbwintrin.h.
_mm256_maskz_shufflelo_epi16
#define _mm256_maskz_shufflelo_epi16 (U, A, imm)
Value:
  ((__m256i)__builtin_ia32_selectw_256((__mmask16)(U), \
                                       (__v16hi)_mm256_shufflelo_epi16((A), \
                                                                       (imm)), \
                                       (__v16hi)_mm256_setzero_si256()))
Definition at line 1865 of file avx512vlbwintrin.h.
_mm_cmp_epi16_mask
#define _mm_cmp_epi16_mask (a, b, p)
Value:
  ((__mmask8)__builtin_ia32_cmpw128_mask((__v8hi)(__m128i)(a), \
                                         (__v8hi)(__m128i)(b), (int)(p), \
                                         (__mmask8)-1))
Definition at line 69 of file avx512vlbwintrin.h.
_mm_cmp_epi8_mask
#define _mm_cmp_epi8_mask (a, b, p)
Value:
  ((__mmask16)__builtin_ia32_cmpb128_mask((__v16qi)(__m128i)(a), \
                                          (__v16qi)(__m128i)(b), (int)(p), \
                                          (__mmask16)-1))
Definition at line 29 of file avx512vlbwintrin.h.
_mm_cmp_epu16_mask
#define _mm_cmp_epu16_mask (a, b, p)
Value:
  ((__mmask8)__builtin_ia32_ucmpw128_mask((__v8hi)(__m128i)(a), \
                                          (__v8hi)(__m128i)(b), (int)(p), \
                                          (__mmask8)-1))
Definition at line 79 of file avx512vlbwintrin.h.
_mm_cmp_epu8_mask
#define _mm_cmp_epu8_mask (a, b, p)
Value:
  ((__mmask16)__builtin_ia32_ucmpb128_mask((__v16qi)(__m128i)(a), \
                                           (__v16qi)(__m128i)(b), (int)(p), \
                                           (__mmask16)-1))
Definition at line 39 of file avx512vlbwintrin.h.
_mm_cmpeq_epi16_mask
#define _mm_cmpeq_epi16_mask (A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 209 of file avx512vlbwintrin.h.
_mm_cmpeq_epi8_mask
#define _mm_cmpeq_epi8_mask (A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 109 of file avx512vlbwintrin.h.
_mm_cmpeq_epu16_mask
#define _mm_cmpeq_epu16_mask (A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 259 of file avx512vlbwintrin.h.
_mm_cmpeq_epu8_mask
#define _mm_cmpeq_epu8_mask (A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 159 of file avx512vlbwintrin.h.
_mm_cmpge_epi16_mask
#define _mm_cmpge_epi16_mask (A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_GE)
Definition at line 213 of file avx512vlbwintrin.h.
_mm_cmpge_epi8_mask
#define _mm_cmpge_epi8_mask (A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_GE)
Definition at line 113 of file avx512vlbwintrin.h.
_mm_cmpge_epu16_mask
#define _mm_cmpge_epu16_mask (A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_GE)
Definition at line 263 of file avx512vlbwintrin.h.
_mm_cmpge_epu8_mask
#define _mm_cmpge_epu8_mask (A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_GE)
Definition at line 163 of file avx512vlbwintrin.h.
_mm_cmpgt_epi16_mask
#define _mm_cmpgt_epi16_mask (A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_GT)
Definition at line 217 of file avx512vlbwintrin.h.
_mm_cmpgt_epi8_mask
#define _mm_cmpgt_epi8_mask (A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_GT)
Definition at line 117 of file avx512vlbwintrin.h.
_mm_cmpgt_epu16_mask
#define _mm_cmpgt_epu16_mask (A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_GT)
Definition at line 267 of file avx512vlbwintrin.h.
_mm_cmpgt_epu8_mask
#define _mm_cmpgt_epu8_mask (A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_GT)
Definition at line 167 of file avx512vlbwintrin.h.
_mm_cmple_epi16_mask
#define _mm_cmple_epi16_mask (A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_LE)
Definition at line 221 of file avx512vlbwintrin.h.
_mm_cmple_epi8_mask
#define _mm_cmple_epi8_mask (A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_LE)
Definition at line 121 of file avx512vlbwintrin.h.
_mm_cmple_epu16_mask
#define _mm_cmple_epu16_mask (A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_LE)
Definition at line 271 of file avx512vlbwintrin.h.
_mm_cmple_epu8_mask
#define _mm_cmple_epu8_mask (A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_LE)
Definition at line 171 of file avx512vlbwintrin.h.
_mm_cmplt_epi16_mask
#define _mm_cmplt_epi16_mask (A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_LT)
Definition at line 225 of file avx512vlbwintrin.h.
_mm_cmplt_epi8_mask
#define _mm_cmplt_epi8_mask (A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_LT)
Definition at line 125 of file avx512vlbwintrin.h.
_mm_cmplt_epu16_mask
#define _mm_cmplt_epu16_mask (A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_LT)
Definition at line 275 of file avx512vlbwintrin.h.
_mm_cmplt_epu8_mask
#define _mm_cmplt_epu8_mask (A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_LT)
Definition at line 175 of file avx512vlbwintrin.h.
_mm_cmpneq_epi16_mask
#define _mm_cmpneq_epi16_mask (A, B) _mm_cmp_epi16_mask((A), (B), _MM_CMPINT_NE)
Definition at line 229 of file avx512vlbwintrin.h.
_mm_cmpneq_epi8_mask
#define _mm_cmpneq_epi8_mask (A, B) _mm_cmp_epi8_mask((A), (B), _MM_CMPINT_NE)
Definition at line 129 of file avx512vlbwintrin.h.
_mm_cmpneq_epu16_mask
#define _mm_cmpneq_epu16_mask (A, B) _mm_cmp_epu16_mask((A), (B), _MM_CMPINT_NE)
Definition at line 279 of file avx512vlbwintrin.h.
_mm_cmpneq_epu8_mask
#define _mm_cmpneq_epu8_mask (A, B) _mm_cmp_epu8_mask((A), (B), _MM_CMPINT_NE)
Definition at line 179 of file avx512vlbwintrin.h.
_mm_dbsad_epu8
#define _mm_dbsad_epu8 (A, B, imm)
Value:
  ((__m128i)__builtin_ia32_dbpsadbw128((__v16qi)(__m128i)(A), \
                                       (__v16qi)(__m128i)(B), (int)(imm)))
Definition at line 2784 of file avx512vlbwintrin.h.
_mm_mask_alignr_epi8
#define _mm_mask_alignr_epi8 (W, U, A, B, N)
Value:
  ((__m128i)__builtin_ia32_selectb_128((__mmask16)(U), \
                                 (__v16qi)_mm_alignr_epi8((A), (B), (int)(N)), \
                                 (__v16qi)(__m128i)(W)))
Definition at line 2764 of file avx512vlbwintrin.h.
_mm_mask_cmp_epi16_mask
#define _mm_mask_cmp_epi16_mask (m, a, b, p)
Value:
  ((__mmask8)__builtin_ia32_cmpw128_mask((__v8hi)(__m128i)(a), \
                                         (__v8hi)(__m128i)(b), (int)(p), \
                                         (__mmask8)(m)))
Definition at line 74 of file avx512vlbwintrin.h.
_mm_mask_cmp_epi8_mask
#define _mm_mask_cmp_epi8_mask (m, a, b, p)
Value:
  ((__mmask16)__builtin_ia32_cmpb128_mask((__v16qi)(__m128i)(a), \
                                          (__v16qi)(__m128i)(b), (int)(p), \
                                          (__mmask16)(m)))
Definition at line 34 of file avx512vlbwintrin.h.
_mm_mask_cmp_epu16_mask
#define _mm_mask_cmp_epu16_mask (m, a, b, p)
Value:
  ((__mmask8)__builtin_ia32_ucmpw128_mask((__v8hi)(__m128i)(a), \
                                          (__v8hi)(__m128i)(b), (int)(p), \
                                          (__mmask8)(m)))
Definition at line 84 of file avx512vlbwintrin.h.
_mm_mask_cmp_epu8_mask
#define _mm_mask_cmp_epu8_mask (m, a, b, p)
Value:
  ((__mmask16)__builtin_ia32_ucmpb128_mask((__v16qi)(__m128i)(a), \
                                           (__v16qi)(__m128i)(b), (int)(p), \
                                           (__mmask16)(m)))
Definition at line 44 of file avx512vlbwintrin.h.
_mm_mask_cmpeq_epi16_mask
#define _mm_mask_cmpeq_epi16_mask (k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 211 of file avx512vlbwintrin.h.
_mm_mask_cmpeq_epi8_mask
#define _mm_mask_cmpeq_epi8_mask (k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 111 of file avx512vlbwintrin.h.
_mm_mask_cmpeq_epu16_mask
#define _mm_mask_cmpeq_epu16_mask (k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 261 of file avx512vlbwintrin.h.
_mm_mask_cmpeq_epu8_mask
#define _mm_mask_cmpeq_epu8_mask (k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 161 of file avx512vlbwintrin.h.
_mm_mask_cmpge_epi16_mask
#define _mm_mask_cmpge_epi16_mask (k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 215 of file avx512vlbwintrin.h.
_mm_mask_cmpge_epi8_mask
#define _mm_mask_cmpge_epi8_mask (k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 115 of file avx512vlbwintrin.h.
_mm_mask_cmpge_epu16_mask
#define _mm_mask_cmpge_epu16_mask (k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 265 of file avx512vlbwintrin.h.
_mm_mask_cmpge_epu8_mask
#define _mm_mask_cmpge_epu8_mask (k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 165 of file avx512vlbwintrin.h.
_mm_mask_cmpgt_epi16_mask
#define _mm_mask_cmpgt_epi16_mask (k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 219 of file avx512vlbwintrin.h.
_mm_mask_cmpgt_epi8_mask
#define _mm_mask_cmpgt_epi8_mask (k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 119 of file avx512vlbwintrin.h.
_mm_mask_cmpgt_epu16_mask
#define _mm_mask_cmpgt_epu16_mask (k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 269 of file avx512vlbwintrin.h.
_mm_mask_cmpgt_epu8_mask
#define _mm_mask_cmpgt_epu8_mask (k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 169 of file avx512vlbwintrin.h.
_mm_mask_cmple_epi16_mask
#define _mm_mask_cmple_epi16_mask (k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 223 of file avx512vlbwintrin.h.
_mm_mask_cmple_epi8_mask
#define _mm_mask_cmple_epi8_mask (k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 123 of file avx512vlbwintrin.h.
_mm_mask_cmple_epu16_mask
#define _mm_mask_cmple_epu16_mask (k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 273 of file avx512vlbwintrin.h.
_mm_mask_cmple_epu8_mask
#define _mm_mask_cmple_epu8_mask (k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 173 of file avx512vlbwintrin.h.
_mm_mask_cmplt_epi16_mask
#define _mm_mask_cmplt_epi16_mask (k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 227 of file avx512vlbwintrin.h.
_mm_mask_cmplt_epi8_mask
#define _mm_mask_cmplt_epi8_mask (k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 127 of file avx512vlbwintrin.h.
_mm_mask_cmplt_epu16_mask
#define _mm_mask_cmplt_epu16_mask (k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 277 of file avx512vlbwintrin.h.
_mm_mask_cmplt_epu8_mask
#define _mm_mask_cmplt_epu8_mask (k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 177 of file avx512vlbwintrin.h.
_mm_mask_cmpneq_epi16_mask
#define _mm_mask_cmpneq_epi16_mask (k, A, B) _mm_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 231 of file avx512vlbwintrin.h.
_mm_mask_cmpneq_epi8_mask
#define _mm_mask_cmpneq_epi8_mask (k, A, B) _mm_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 131 of file avx512vlbwintrin.h.
_mm_mask_cmpneq_epu16_mask
#define _mm_mask_cmpneq_epu16_mask (k, A, B) _mm_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 281 of file avx512vlbwintrin.h.
_mm_mask_cmpneq_epu8_mask
#define _mm_mask_cmpneq_epu8_mask (k, A, B) _mm_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 181 of file avx512vlbwintrin.h.
_mm_mask_dbsad_epu8
#define _mm_mask_dbsad_epu8 (W, U, A, B, imm)
Value:
  ((__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                      (__v8hi)_mm_dbsad_epu8((A), (B), (imm)), \
                                      (__v8hi)(__m128i)(W)))
Definition at line 2788 of file avx512vlbwintrin.h.
_mm_mask_shufflehi_epi16
#define _mm_mask_shufflehi_epi16 (W, U, A, imm)
Value:
  ((__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                       (__v8hi)_mm_shufflehi_epi16((A), (imm)), \
                                       (__v8hi)(__m128i)(W)))
Definition at line 1829 of file avx512vlbwintrin.h.
_mm_mask_shufflelo_epi16
#define _mm_mask_shufflelo_epi16 (W, U, A, imm)
Value:
  ((__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                       (__v8hi)_mm_shufflelo_epi16((A), (imm)), \
                                       (__v8hi)(__m128i)(W)))
Definition at line 1849 of file avx512vlbwintrin.h.
_mm_maskz_alignr_epi8
#define _mm_maskz_alignr_epi8 (U, A, B, N)
Value:
  ((__m128i)__builtin_ia32_selectb_128((__mmask16)(U), \
                                 (__v16qi)_mm_alignr_epi8((A), (B), (int)(N)), \
                                 (__v16qi)_mm_setzero_si128()))
Definition at line 2769 of file avx512vlbwintrin.h.
_mm_maskz_dbsad_epu8
#define _mm_maskz_dbsad_epu8 (U, A, B, imm)
Value:
  ((__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                      (__v8hi)_mm_dbsad_epu8((A), (B), (imm)), \
                                      (__v8hi)_mm_setzero_si128()))
Definition at line 2793 of file avx512vlbwintrin.h.
_mm_maskz_shufflehi_epi16
#define _mm_maskz_shufflehi_epi16 (U, A, imm)
Value:
  ((__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                       (__v8hi)_mm_shufflehi_epi16((A), (imm)), \
                                       (__v8hi)_mm_setzero_si128()))
Definition at line 1834 of file avx512vlbwintrin.h.
_mm_maskz_shufflelo_epi16
#define _mm_maskz_shufflelo_epi16 (U, A, imm)
Value:
  ((__m128i)__builtin_ia32_selectw_128((__mmask8)(U), \
                                       (__v8hi)_mm_shufflelo_epi16((A), (imm)), \
                                       (__v8hi)_mm_setzero_si128()))
Definition at line 1854 of file avx512vlbwintrin.h.
Function Documentation
_mm256_cvtepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_cvtepi16_epi8 (__m256i __A) static
Definition at line 1531 of file avx512vlbwintrin.h.
Referenced by _mm256_mask_cvtepi16_epi8(), and _mm256_maskz_cvtepi16_epi8().
_mm256_cvtsepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_cvtsepi16_epi8 (__m256i __A) static
Definition at line 1427 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm256_cvtusepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_cvtusepi16_epi8 (__m256i __A) static
Definition at line 1469 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm256_loadu_epi16()
static __inline __m256i __DEFAULT_FN_ATTRS256 _mm256_loadu_epi16 (void const * __P) static
Definition at line 2321 of file avx512vlbwintrin.h.
References __P, and __v.
_mm256_loadu_epi8()
static __inline __m256i __DEFAULT_FN_ATTRS256 _mm256_loadu_epi8 (void const * __P) static
Definition at line 2373 of file avx512vlbwintrin.h.
References __P, and __v.
_mm256_mask2_permutex2var_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask2_permutex2var_epi16 (__m256i __A, __m256i __I, __mmask16 __U, __m256i __B) static
Definition at line 1331 of file avx512vlbwintrin.h.
References _mm256_permutex2var_epi16().
_mm256_mask_abs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_abs_epi16 (__m256i __W, __mmask16 __U, __m256i __A) static
Definition at line 530 of file avx512vlbwintrin.h.
References _mm256_abs_epi16().
_mm256_mask_abs_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_abs_epi8 (__m256i __W, __mmask32 __U, __m256i __A) static
Definition at line 498 of file avx512vlbwintrin.h.
References _mm256_abs_epi8().
_mm256_mask_add_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_add_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 324 of file avx512vlbwintrin.h.
References _mm256_add_epi16().
_mm256_mask_add_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_add_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 310 of file avx512vlbwintrin.h.
References _mm256_add_epi8().
_mm256_mask_adds_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_adds_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 721 of file avx512vlbwintrin.h.
References _mm256_adds_epi16().
_mm256_mask_adds_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_adds_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 689 of file avx512vlbwintrin.h.
References _mm256_adds_epi8().
_mm256_mask_adds_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_adds_epu16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 785 of file avx512vlbwintrin.h.
References _mm256_adds_epu16().
_mm256_mask_adds_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_adds_epu8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 753 of file avx512vlbwintrin.h.
References _mm256_adds_epu8().
_mm256_mask_avg_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_avg_epu16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 849 of file avx512vlbwintrin.h.
References _mm256_avg_epu16().
_mm256_mask_avg_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_avg_epu8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 817 of file avx512vlbwintrin.h.
References _mm256_avg_epu8().
_mm256_mask_blend_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_blend_epi16 (__mmask16 __U, __m256i __A, __m256i __W) static
Definition at line 474 of file avx512vlbwintrin.h.
_mm256_mask_blend_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_blend_epi8 (__mmask32 __U, __m256i __A, __m256i __W) static
Definition at line 458 of file avx512vlbwintrin.h.
_mm256_mask_broadcastb_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_broadcastb_epi8 (__m256i __O, __mmask32 __M, __m128i __A) static
Definition at line 2638 of file avx512vlbwintrin.h.
References _mm256_broadcastb_epi8().
_mm256_mask_broadcastw_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_broadcastw_epi16 (__m256i __O, __mmask16 __M, __m128i __A) static
Definition at line 2670 of file avx512vlbwintrin.h.
References _mm256_broadcastw_epi16().
_mm256_mask_cvtepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi16_epi8 (__m128i __O, __mmask16 __M, __m256i __A) static
Definition at line 1536 of file avx512vlbwintrin.h.
References _mm256_cvtepi16_epi8().
_mm256_mask_cvtepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi16_storeu_epi8 (void * __P, __mmask16 __M, __m256i __A) static
Definition at line 1550 of file avx512vlbwintrin.h.
References __P.
_mm256_mask_cvtepi8_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi8_epi16 (__m256i __W, __mmask16 __U, __m128i __A) static
Definition at line 1780 of file avx512vlbwintrin.h.
References _mm256_cvtepi8_epi16().
_mm256_mask_cvtepu8_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu8_epi16 (__m256i __W, __mmask16 __U, __m128i __A) static
Definition at line 1813 of file avx512vlbwintrin.h.
References _mm256_cvtepu8_epi16().
_mm256_mask_cvtsepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtsepi16_epi8 (__m128i __O, __mmask16 __M, __m256i __A) static
Definition at line 1434 of file avx512vlbwintrin.h.
_mm256_mask_cvtsepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_cvtsepi16_storeu_epi8 (void * __P, __mmask16 __M, __m256i __A) static
Definition at line 1556 of file avx512vlbwintrin.h.
References __P.
_mm256_mask_cvtusepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtusepi16_epi8 (__m128i __O, __mmask16 __M, __m256i __A) static
Definition at line 1476 of file avx512vlbwintrin.h.
_mm256_mask_cvtusepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_cvtusepi16_storeu_epi8 (void * __P, __mmask16 __M, __m256i __A) static
Definition at line 1562 of file avx512vlbwintrin.h.
References __P.
_mm256_mask_loadu_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_loadu_epi16 (__m256i __W, __mmask16 __U, void const * __P) static
Definition at line 2330 of file avx512vlbwintrin.h.
References __P.
_mm256_mask_loadu_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_loadu_epi8 (__m256i __W, __mmask32 __U, void const * __P) static
Definition at line 2382 of file avx512vlbwintrin.h.
References __P.
_mm256_mask_madd_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_madd_epi16 (__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) static
Definition at line 1392 of file avx512vlbwintrin.h.
References _mm256_madd_epi16().
_mm256_mask_maddubs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_maddubs_epi16 (__m256i __W, __mmask16 __U, __m256i __X, __m256i __Y) static
Definition at line 1363 of file avx512vlbwintrin.h.
References __Y, and _mm256_maddubs_epi16().
_mm256_mask_max_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_max_epi16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 921 of file avx512vlbwintrin.h.
References _mm256_max_epi16().
_mm256_mask_max_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_max_epi8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 889 of file avx512vlbwintrin.h.
References _mm256_max_epi8().
_mm256_mask_max_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_max_epu16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 985 of file avx512vlbwintrin.h.
References _mm256_max_epu16().
_mm256_mask_max_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_max_epu8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 953 of file avx512vlbwintrin.h.
References _mm256_max_epu8().
_mm256_mask_min_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_min_epi16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 1049 of file avx512vlbwintrin.h.
References _mm256_min_epi16().
_mm256_mask_min_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_min_epi8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 1017 of file avx512vlbwintrin.h.
References _mm256_min_epi8().
_mm256_mask_min_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_min_epu16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 1113 of file avx512vlbwintrin.h.
References _mm256_min_epu16().
_mm256_mask_min_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_min_epu8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 1081 of file avx512vlbwintrin.h.
References _mm256_min_epu8().
_mm256_mask_mov_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mov_epi16 (__m256i __W, __mmask16 __U, __m256i __A) static
Definition at line 2214 of file avx512vlbwintrin.h.
Referenced by _mm256_mask_reduce_and_epi16(), _mm256_mask_reduce_max_epi16(), _mm256_mask_reduce_min_epi16(), _mm256_mask_reduce_min_epu16(), and _mm256_mask_reduce_mul_epi16().
_mm256_mask_mov_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mov_epi8 (__m256i __W, __mmask32 __U, __m256i __A) static
Definition at line 2246 of file avx512vlbwintrin.h.
Referenced by _mm256_mask_reduce_and_epi8(), _mm256_mask_reduce_max_epi8(), _mm256_mask_reduce_min_epi8(), _mm256_mask_reduce_min_epu8(), and _mm256_mask_reduce_mul_epi8().
_mm256_mask_mulhi_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mulhi_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1638 of file avx512vlbwintrin.h.
References _mm256_mulhi_epi16().
_mm256_mask_mulhi_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mulhi_epu16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1610 of file avx512vlbwintrin.h.
References _mm256_mulhi_epu16().
_mm256_mask_mulhrs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mulhrs_epi16 (__m256i __W, __mmask16 __U, __m256i __X, __m256i __Y) static
Definition at line 1582 of file avx512vlbwintrin.h.
References __Y, and _mm256_mulhrs_epi16().
_mm256_mask_mullo_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mullo_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 422 of file avx512vlbwintrin.h.
References _mm256_mullo_epi16().
_mm256_mask_packs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_packs_epi16 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 601 of file avx512vlbwintrin.h.
References _mm256_packs_epi16().
_mm256_mask_packs_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_packs_epi32 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 569 of file avx512vlbwintrin.h.
References _mm256_packs_epi32().
_mm256_mask_packus_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_packus_epi16 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 665 of file avx512vlbwintrin.h.
References _mm256_packus_epi16().
_mm256_mask_packus_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_packus_epi32 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 633 of file avx512vlbwintrin.h.
References _mm256_packus_epi32().
_mm256_mask_permutex2var_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_permutex2var_epi16 (__m256i __A, __mmask16 __U, __m256i __I, __m256i __B) static
Definition at line 1322 of file avx512vlbwintrin.h.
References _mm256_permutex2var_epi16().
_mm256_mask_permutexvar_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_permutexvar_epi16 (__m256i __W, __mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 2756 of file avx512vlbwintrin.h.
References _mm256_permutexvar_epi16().
_mm256_mask_reduce_add_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_add_epi16 (__mmask16 __M, __m256i __W) static
Definition at line 2921 of file avx512vlbwintrin.h.
References _mm256_maskz_mov_epi16().
_mm256_mask_reduce_add_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_add_epi8 (__mmask32 __M, __m256i __W) static
Definition at line 3097 of file avx512vlbwintrin.h.
References _mm256_maskz_mov_epi8().
_mm256_mask_reduce_and_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_and_epi16 (__mmask16 __M, __m256i __W) static
Definition at line 2933 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi16(), and _mm256_set1_epi16().
_mm256_mask_reduce_and_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_and_epi8 (__mmask32 __M, __m256i __W) static
Definition at line 3109 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi8(), and _mm256_set1_epi8().
_mm256_mask_reduce_max_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_max_epi16 (__mmask16 __M, __m256i __V) static
Definition at line 2965 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi16(), and _mm256_set1_epi16().
_mm256_mask_reduce_max_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_max_epi8 (__mmask32 __M, __m256i __V) static
Definition at line 3141 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi8(), and _mm256_set1_epi8().
_mm256_mask_reduce_max_epu16()
static __inline__ unsigned short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_max_epu16 (__mmask16 __M, __m256i __V) static
Definition at line 2971 of file avx512vlbwintrin.h.
References _mm256_maskz_mov_epi16().
_mm256_mask_reduce_max_epu8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_max_epu8 (__mmask32 __M, __m256i __V) static
Definition at line 3147 of file avx512vlbwintrin.h.
References _mm256_maskz_mov_epi8().
_mm256_mask_reduce_min_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_min_epi16 (__mmask16 __M, __m256i __V) static
Definition at line 2977 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi16(), and _mm256_set1_epi16().
_mm256_mask_reduce_min_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_min_epi8 (__mmask32 __M, __m256i __V) static
Definition at line 3153 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi8(), and _mm256_set1_epi8().
_mm256_mask_reduce_min_epu16()
static __inline__ unsigned short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_min_epu16 (__mmask16 __M, __m256i __V) static
Definition at line 2983 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi16(), and _mm256_set1_epi16().
_mm256_mask_reduce_min_epu8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_min_epu8 (__mmask32 __M, __m256i __V) static
Definition at line 3159 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi8(), and _mm256_set1_epi8().
_mm256_mask_reduce_mul_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_mul_epi16 (__mmask16 __M, __m256i __W) static
Definition at line 2927 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi16(), and _mm256_set1_epi16().
_mm256_mask_reduce_mul_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_mul_epi8 (__mmask32 __M, __m256i __W) static
Definition at line 3103 of file avx512vlbwintrin.h.
References _mm256_mask_mov_epi8(), and _mm256_set1_epi8().
_mm256_mask_reduce_or_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_or_epi16 (__mmask16 __M, __m256i __W) static
Definition at line 2939 of file avx512vlbwintrin.h.
References _mm256_maskz_mov_epi16().
_mm256_mask_reduce_or_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_mask_reduce_or_epi8 (__mmask32 __M, __m256i __W) static
Definition at line 3115 of file avx512vlbwintrin.h.
References _mm256_maskz_mov_epi8().
_mm256_mask_set1_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_set1_epi16 (__m256i __O, __mmask16 __M, short __A) static
Definition at line 2686 of file avx512vlbwintrin.h.
References _mm256_set1_epi16().
_mm256_mask_set1_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_set1_epi8 (__m256i __O, __mmask32 __M, char __A) static
Definition at line 2279 of file avx512vlbwintrin.h.
References _mm256_set1_epi8().
_mm256_mask_shuffle_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_shuffle_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1137 of file avx512vlbwintrin.h.
References _mm256_shuffle_epi8().
_mm256_mask_sll_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sll_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m128i __B) static
Definition at line 1932 of file avx512vlbwintrin.h.
References _mm256_sll_epi16().
_mm256_mask_slli_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_slli_epi16 (__m256i __W, __mmask16 __U, __m256i __A, unsigned int __B) static
Definition at line 1964 of file avx512vlbwintrin.h.
References _mm256_slli_epi16().
_mm256_mask_sllv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sllv_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1878 of file avx512vlbwintrin.h.
References _mm256_sllv_epi16().
_mm256_mask_sra_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sra_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m128i __B) static
Definition at line 2085 of file avx512vlbwintrin.h.
References _mm256_sra_epi16().
_mm256_mask_srai_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srai_epi16 (__m256i __W, __mmask16 __U, __m256i __A, unsigned int __B) static
Definition at line 2117 of file avx512vlbwintrin.h.
References _mm256_srai_epi16().
_mm256_mask_srav_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srav_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 2031 of file avx512vlbwintrin.h.
References _mm256_srav_epi16().
_mm256_mask_srl_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srl_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m128i __B) static
Definition at line 2150 of file avx512vlbwintrin.h.
References _mm256_srl_epi16().
_mm256_mask_srli_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srli_epi16 (__m256i __W, __mmask16 __U, __m256i __A, int __B) static
Definition at line 2182 of file avx512vlbwintrin.h.
References _mm256_srli_epi16().
_mm256_mask_srlv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_srlv_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1987 of file avx512vlbwintrin.h.
References _mm256_srlv_epi16().
_mm256_mask_storeu_epi16()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_storeu_epi16 (void * __P, __mmask16 __U, __m256i __A) static
Definition at line 2425 of file avx512vlbwintrin.h.
References __P.
_mm256_mask_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS256 _mm256_mask_storeu_epi8 (void * __P, __mmask32 __U, __m256i __A) static
Definition at line 2459 of file avx512vlbwintrin.h.
References __P.
_mm256_mask_sub_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sub_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 352 of file avx512vlbwintrin.h.
References _mm256_sub_epi16().
_mm256_mask_sub_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_sub_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 338 of file avx512vlbwintrin.h.
References _mm256_sub_epi8().
_mm256_mask_subs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_subs_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1201 of file avx512vlbwintrin.h.
References _mm256_subs_epi16().
_mm256_mask_subs_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_subs_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1169 of file avx512vlbwintrin.h.
References _mm256_subs_epi8().
_mm256_mask_subs_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_subs_epu16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1265 of file avx512vlbwintrin.h.
References _mm256_subs_epu16().
_mm256_mask_subs_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_subs_epu8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1233 of file avx512vlbwintrin.h.
References _mm256_subs_epu8().
_mm256_mask_test_epi16_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_mask_test_epi16_mask (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 2514 of file avx512vlbwintrin.h.
References _mm256_and_si256(), _mm256_mask_cmpneq_epi16_mask, and _mm256_setzero_si256().
_mm256_mask_test_epi8_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_mask_test_epi8_mask (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 2487 of file avx512vlbwintrin.h.
References _mm256_and_si256(), _mm256_mask_cmpneq_epi8_mask, and _mm256_setzero_si256().
_mm256_mask_testn_epi16_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_mask_testn_epi16_mask (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 2567 of file avx512vlbwintrin.h.
References _mm256_and_si256(), _mm256_mask_cmpeq_epi16_mask, and _mm256_setzero_si256().
_mm256_mask_testn_epi8_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_mask_testn_epi8_mask (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 2541 of file avx512vlbwintrin.h.
References _mm256_and_si256(), _mm256_mask_cmpeq_epi8_mask, and _mm256_setzero_si256().
_mm256_mask_unpackhi_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_unpackhi_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1694 of file avx512vlbwintrin.h.
References _mm256_unpackhi_epi16().
_mm256_mask_unpackhi_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_unpackhi_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1666 of file avx512vlbwintrin.h.
References _mm256_unpackhi_epi8().
_mm256_mask_unpacklo_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_unpacklo_epi16 (__m256i __W, __mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1750 of file avx512vlbwintrin.h.
References _mm256_unpacklo_epi16().
_mm256_mask_unpacklo_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_unpacklo_epi8 (__m256i __W, __mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1722 of file avx512vlbwintrin.h.
References _mm256_unpacklo_epi8().
_mm256_maskz_abs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_abs_epi16 (__mmask16 __U, __m256i __A) static
Definition at line 538 of file avx512vlbwintrin.h.
References _mm256_abs_epi16(), and _mm256_setzero_si256().
_mm256_maskz_abs_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_abs_epi8 (__mmask32 __U, __m256i __A) static
Definition at line 506 of file avx512vlbwintrin.h.
References _mm256_abs_epi8(), and _mm256_setzero_si256().
_mm256_maskz_add_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_add_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 331 of file avx512vlbwintrin.h.
References _mm256_add_epi16(), and _mm256_setzero_si256().
_mm256_maskz_add_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_add_epi8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 317 of file avx512vlbwintrin.h.
References _mm256_add_epi8(), and _mm256_setzero_si256().
_mm256_maskz_adds_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_adds_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 729 of file avx512vlbwintrin.h.
References _mm256_adds_epi16(), and _mm256_setzero_si256().
_mm256_maskz_adds_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_adds_epi8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 697 of file avx512vlbwintrin.h.
References _mm256_adds_epi8(), and _mm256_setzero_si256().
_mm256_maskz_adds_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_adds_epu16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 793 of file avx512vlbwintrin.h.
References _mm256_adds_epu16(), and _mm256_setzero_si256().
_mm256_maskz_adds_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_adds_epu8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 761 of file avx512vlbwintrin.h.
References _mm256_adds_epu8(), and _mm256_setzero_si256().
_mm256_maskz_avg_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_avg_epu16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 857 of file avx512vlbwintrin.h.
References _mm256_avg_epu16(), and _mm256_setzero_si256().
_mm256_maskz_avg_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_avg_epu8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 825 of file avx512vlbwintrin.h.
References _mm256_avg_epu8(), and _mm256_setzero_si256().
_mm256_maskz_broadcastb_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcastb_epi8 (__mmask32 __M, __m128i __A) static
Definition at line 2646 of file avx512vlbwintrin.h.
References _mm256_broadcastb_epi8(), and _mm256_setzero_si256().
_mm256_maskz_broadcastw_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcastw_epi16 (__mmask16 __M, __m128i __A) static
Definition at line 2678 of file avx512vlbwintrin.h.
References _mm256_broadcastw_epi16(), and _mm256_setzero_si256().
_mm256_maskz_cvtepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi16_epi8 (__mmask16 __M, __m256i __A) static
Definition at line 1543 of file avx512vlbwintrin.h.
References _mm256_cvtepi16_epi8(), and _mm_setzero_si128().
_mm256_maskz_cvtepi8_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi8_epi16 (__mmask16 __U, __m128i __A) static
Definition at line 1788 of file avx512vlbwintrin.h.
References _mm256_cvtepi8_epi16(), and _mm256_setzero_si256().
_mm256_maskz_cvtepu8_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu8_epi16 (__mmask16 __U, __m128i __A) static
Definition at line 1821 of file avx512vlbwintrin.h.
References _mm256_cvtepu8_epi16(), and _mm256_setzero_si256().
_mm256_maskz_cvtsepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtsepi16_epi8 (__mmask16 __M, __m256i __A) static
Definition at line 1441 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm256_maskz_cvtusepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtusepi16_epi8 (__mmask16 __M, __m256i __A) static
Definition at line 1483 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm256_maskz_loadu_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_loadu_epi16 (__mmask16 __U, void const * __P) static
Definition at line 2338 of file avx512vlbwintrin.h.
References __P, and _mm256_setzero_si256().
_mm256_maskz_loadu_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_loadu_epi8 (__mmask32 __U, void const * __P) static
Definition at line 2390 of file avx512vlbwintrin.h.
References __P, and _mm256_setzero_si256().
_mm256_maskz_madd_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_madd_epi16 (__mmask8 __U, __m256i __A, __m256i __B) static
Definition at line 1399 of file avx512vlbwintrin.h.
References _mm256_madd_epi16(), and _mm256_setzero_si256().
_mm256_maskz_maddubs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_maddubs_epi16 (__mmask16 __U, __m256i __X, __m256i __Y) static
Definition at line 1371 of file avx512vlbwintrin.h.
References __Y, _mm256_maddubs_epi16(), and _mm256_setzero_si256().
_mm256_maskz_max_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_max_epi16 (__mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 913 of file avx512vlbwintrin.h.
References _mm256_max_epi16(), and _mm256_setzero_si256().
_mm256_maskz_max_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_max_epi8 (__mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 881 of file avx512vlbwintrin.h.
References _mm256_max_epi8(), and _mm256_setzero_si256().
_mm256_maskz_max_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_max_epu16 (__mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 977 of file avx512vlbwintrin.h.
References _mm256_max_epu16(), and _mm256_setzero_si256().
_mm256_maskz_max_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_max_epu8 (__mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 945 of file avx512vlbwintrin.h.
References _mm256_max_epu8(), and _mm256_setzero_si256().
_mm256_maskz_min_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_min_epi16 (__mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 1041 of file avx512vlbwintrin.h.
References _mm256_min_epi16(), and _mm256_setzero_si256().
_mm256_maskz_min_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_min_epi8 (__mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 1009 of file avx512vlbwintrin.h.
References _mm256_min_epi8(), and _mm256_setzero_si256().
_mm256_maskz_min_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_min_epu16 (__mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 1105 of file avx512vlbwintrin.h.
References _mm256_min_epu16(), and _mm256_setzero_si256().
_mm256_maskz_min_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_min_epu8 (__mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 1073 of file avx512vlbwintrin.h.
References _mm256_min_epu8(), and _mm256_setzero_si256().
_mm256_maskz_mov_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mov_epi16 (__mmask16 __U, __m256i __A) static
Definition at line 2222 of file avx512vlbwintrin.h.
References _mm256_setzero_si256().
Referenced by _mm256_mask_reduce_add_epi16(), _mm256_mask_reduce_max_epu16(), and _mm256_mask_reduce_or_epi16().
_mm256_maskz_mov_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mov_epi8 (__mmask32 __U, __m256i __A) static
Definition at line 2254 of file avx512vlbwintrin.h.
References _mm256_setzero_si256().
Referenced by _mm256_mask_reduce_add_epi8(), _mm256_mask_reduce_max_epu8(), and _mm256_mask_reduce_or_epi8().
_mm256_maskz_mulhi_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mulhi_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1645 of file avx512vlbwintrin.h.
References _mm256_mulhi_epi16(), and _mm256_setzero_si256().
_mm256_maskz_mulhi_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mulhi_epu16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1617 of file avx512vlbwintrin.h.
References _mm256_mulhi_epu16(), and _mm256_setzero_si256().
_mm256_maskz_mulhrs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mulhrs_epi16 (__mmask16 __U, __m256i __X, __m256i __Y) static
Definition at line 1589 of file avx512vlbwintrin.h.
References __Y, _mm256_mulhrs_epi16(), and _mm256_setzero_si256().
_mm256_maskz_mullo_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mullo_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 429 of file avx512vlbwintrin.h.
References _mm256_mullo_epi16(), and _mm256_setzero_si256().
_mm256_maskz_packs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_packs_epi16 (__mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 593 of file avx512vlbwintrin.h.
References _mm256_packs_epi16(), and _mm256_setzero_si256().
_mm256_maskz_packs_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_packs_epi32 (__mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 561 of file avx512vlbwintrin.h.
References _mm256_packs_epi32(), and _mm256_setzero_si256().
_mm256_maskz_packus_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_packus_epi16 (__mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 657 of file avx512vlbwintrin.h.
References _mm256_packus_epi16(), and _mm256_setzero_si256().
_mm256_maskz_packus_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_packus_epi32 (__mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 625 of file avx512vlbwintrin.h.
References _mm256_packus_epi32(), and _mm256_setzero_si256().
_mm256_maskz_permutex2var_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_permutex2var_epi16 (__mmask16 __U, __m256i __A, __m256i __I, __m256i __B) static
Definition at line 1340 of file avx512vlbwintrin.h.
References _mm256_permutex2var_epi16(), and _mm256_setzero_si256().
_mm256_maskz_permutexvar_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_permutexvar_epi16 (__mmask16 __M, __m256i __A, __m256i __B) static
Definition at line 2747 of file avx512vlbwintrin.h.
References _mm256_permutexvar_epi16(), and _mm256_setzero_si256().
_mm256_maskz_set1_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_set1_epi16 (__mmask16 __M, short __A) static
Definition at line 2694 of file avx512vlbwintrin.h.
References _mm256_set1_epi16(), and _mm256_setzero_si256().
_mm256_maskz_set1_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_set1_epi8 (__mmask32 __M, char __A) static
Definition at line 2287 of file avx512vlbwintrin.h.
References _mm256_set1_epi8(), and _mm256_setzero_si256().
_mm256_maskz_shuffle_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_shuffle_epi8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1145 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_shuffle_epi8().
_mm256_maskz_sll_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sll_epi16 (__mmask16 __U, __m256i __A, __m128i __B) static
Definition at line 1940 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_sll_epi16().
_mm256_maskz_slli_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_slli_epi16 (__mmask16 __U, __m256i __A, unsigned int __B) static
Definition at line 1973 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_slli_epi16().
_mm256_maskz_sllv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sllv_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1886 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_sllv_epi16().
_mm256_maskz_sra_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sra_epi16 (__mmask16 __U, __m256i __A, __m128i __B) static
Definition at line 2093 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_sra_epi16().
_mm256_maskz_srai_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srai_epi16 (__mmask16 __U, __m256i __A, unsigned int __B) static
Definition at line 2126 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_srai_epi16().
_mm256_maskz_srav_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srav_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 2039 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_srav_epi16().
_mm256_maskz_srl_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srl_epi16 (__mmask16 __U, __m256i __A, __m128i __B) static
Definition at line 2158 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_srl_epi16().
_mm256_maskz_srli_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srli_epi16 (__mmask16 __U, __m256i __A, int __B) static
Definition at line 2190 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_srli_epi16().
_mm256_maskz_srlv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_srlv_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1995 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_srlv_epi16().
_mm256_maskz_sub_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sub_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 359 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_sub_epi16().
_mm256_maskz_sub_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_sub_epi8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 345 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_sub_epi8().
_mm256_maskz_subs_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_subs_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1209 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_subs_epi16().
_mm256_maskz_subs_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_subs_epi8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1177 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_subs_epi8().
_mm256_maskz_subs_epu16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_subs_epu16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1273 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_subs_epu16().
_mm256_maskz_subs_epu8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_subs_epu8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1241 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_subs_epu8().
_mm256_maskz_unpackhi_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_unpackhi_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1701 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_unpackhi_epi16().
_mm256_maskz_unpackhi_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_unpackhi_epi8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1673 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_unpackhi_epi8().
_mm256_maskz_unpacklo_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_unpacklo_epi16 (__mmask16 __U, __m256i __A, __m256i __B) static
Definition at line 1757 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_unpacklo_epi16().
_mm256_maskz_unpacklo_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_unpacklo_epi8 (__mmask32 __U, __m256i __A, __m256i __B) static
Definition at line 1729 of file avx512vlbwintrin.h.
References _mm256_setzero_si256(), and _mm256_unpacklo_epi8().
_mm256_movepi16_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_movepi16_mask (__m256i __A) static
Definition at line 2592 of file avx512vlbwintrin.h.
_mm256_movepi8_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_movepi8_mask (__m256i __A) static
Definition at line 2580 of file avx512vlbwintrin.h.
_mm256_movm_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_movm_epi16 (__mmask16 __A) static
Definition at line 2616 of file avx512vlbwintrin.h.
_mm256_movm_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_movm_epi8 (__mmask32 __A) static
Definition at line 2604 of file avx512vlbwintrin.h.
_mm256_permutex2var_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_permutex2var_epi16 (__m256i __A, __m256i __I, __m256i __B) static
Definition at line 1315 of file avx512vlbwintrin.h.
Referenced by _mm256_mask2_permutex2var_epi16(), _mm256_mask_permutex2var_epi16(), and _mm256_maskz_permutex2var_epi16().
_mm256_permutexvar_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_permutexvar_epi16 (__m256i __A, __m256i __B) static
Definition at line 2741 of file avx512vlbwintrin.h.
Referenced by _mm256_mask_permutexvar_epi16(), and _mm256_maskz_permutexvar_epi16().
_mm256_reduce_add_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_add_epi16 (__m256i __W) static
Definition at line 2901 of file avx512vlbwintrin.h.
_mm256_reduce_add_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_add_epi8 (__m256i __W) static
Definition at line 3077 of file avx512vlbwintrin.h.
_mm256_reduce_and_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_and_epi16 (__m256i __W) static
Definition at line 2911 of file avx512vlbwintrin.h.
_mm256_reduce_and_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_and_epi8 (__m256i __W) static
Definition at line 3087 of file avx512vlbwintrin.h.
_mm256_reduce_max_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_max_epi16 (__m256i __V) static
Definition at line 2945 of file avx512vlbwintrin.h.
_mm256_reduce_max_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_max_epi8 (__m256i __V) static
Definition at line 3121 of file avx512vlbwintrin.h.
_mm256_reduce_max_epu16()
static __inline__ unsigned short __DEFAULT_FN_ATTRS256 _mm256_reduce_max_epu16 (__m256i __V) static
Definition at line 2950 of file avx512vlbwintrin.h.
_mm256_reduce_max_epu8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS256 _mm256_reduce_max_epu8 (__m256i __V) static
Definition at line 3126 of file avx512vlbwintrin.h.
_mm256_reduce_min_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_min_epi16 (__m256i __V) static
Definition at line 2955 of file avx512vlbwintrin.h.
_mm256_reduce_min_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_min_epi8 (__m256i __V) static
Definition at line 3131 of file avx512vlbwintrin.h.
_mm256_reduce_min_epu16()
static __inline__ unsigned short __DEFAULT_FN_ATTRS256 _mm256_reduce_min_epu16 (__m256i __V) static
Definition at line 2960 of file avx512vlbwintrin.h.
_mm256_reduce_min_epu8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS256 _mm256_reduce_min_epu8 (__m256i __V) static
Definition at line 3136 of file avx512vlbwintrin.h.
_mm256_reduce_mul_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_mul_epi16 (__m256i __W) static
Definition at line 2906 of file avx512vlbwintrin.h.
_mm256_reduce_mul_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_mul_epi8 (__m256i __W) static
Definition at line 3082 of file avx512vlbwintrin.h.
_mm256_reduce_or_epi16()
static __inline__ short __DEFAULT_FN_ATTRS256 _mm256_reduce_or_epi16 (__m256i __W) static
Definition at line 2916 of file avx512vlbwintrin.h.
_mm256_reduce_or_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS256 _mm256_reduce_or_epi8 (__m256i __W) static
Definition at line 3092 of file avx512vlbwintrin.h.
_mm256_sllv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_sllv_epi16 (__m256i __A, __m256i __B) static
Definition at line 1872 of file avx512vlbwintrin.h.
Referenced by _mm256_mask_sllv_epi16(), and _mm256_maskz_sllv_epi16().
_mm256_srav_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_srav_epi16 (__m256i __A, __m256i __B) static
Definition at line 2025 of file avx512vlbwintrin.h.
Referenced by _mm256_mask_srav_epi16(), and _mm256_maskz_srav_epi16().
_mm256_srlv_epi16()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_srlv_epi16 (__m256i __A, __m256i __B) static
Definition at line 1981 of file avx512vlbwintrin.h.
Referenced by _mm256_mask_srlv_epi16(), and _mm256_maskz_srlv_epi16().
_mm256_storeu_epi16()
static __inline void __DEFAULT_FN_ATTRS256 _mm256_storeu_epi16 (void * __P, __m256i __A) static
Definition at line 2416 of file avx512vlbwintrin.h.
References __P, and __v.
_mm256_storeu_epi8()
static __inline void __DEFAULT_FN_ATTRS256 _mm256_storeu_epi8 (void * __P, __m256i __A) static
Definition at line 2450 of file avx512vlbwintrin.h.
References __P, and __v.
_mm256_test_epi16_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_test_epi16_mask (__m256i __A, __m256i __B) static
Definition at line 2507 of file avx512vlbwintrin.h.
References _mm256_and_si256(), _mm256_cmpneq_epi16_mask, and _mm256_setzero_si256().
_mm256_test_epi8_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_test_epi8_mask (__m256i __A, __m256i __B) static
Definition at line 2480 of file avx512vlbwintrin.h.
References _mm256_and_si256(), _mm256_cmpneq_epi8_mask, and _mm256_setzero_si256().
_mm256_testn_epi16_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS256 _mm256_testn_epi16_mask (__m256i __A, __m256i __B) static
Definition at line 2560 of file avx512vlbwintrin.h.
References _mm256_and_si256(), _mm256_cmpeq_epi16_mask, and _mm256_setzero_si256().
_mm256_testn_epi8_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS256 _mm256_testn_epi8_mask (__m256i __A, __m256i __B) static
Definition at line 2534 of file avx512vlbwintrin.h.
References _mm256_and_si256(), _mm256_cmpeq_epi8_mask, and _mm256_setzero_si256().
_mm_cvtepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtepi16_epi8 (__m128i __A) static
Definition at line 1490 of file avx512vlbwintrin.h.
_mm_cvtsepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtsepi16_epi8 (__m128i __A) static
Definition at line 1406 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm_cvtusepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtusepi16_epi8 (__m128i __A) static
Definition at line 1448 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm_loadu_epi16()
static __inline __m128i __DEFAULT_FN_ATTRS128 _mm_loadu_epi16 (void const * __P) static
Definition at line 2295 of file avx512vlbwintrin.h.
References __P, and __v.
_mm_loadu_epi8()
static __inline __m128i __DEFAULT_FN_ATTRS128 _mm_loadu_epi8 (void const * __P) static
Definition at line 2347 of file avx512vlbwintrin.h.
References __P, and __v.
_mm_mask2_permutex2var_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask2_permutex2var_epi16 (__m128i __A, __m128i __I, __mmask8 __U, __m128i __B) static
Definition at line 1297 of file avx512vlbwintrin.h.
References _mm_permutex2var_epi16().
_mm_mask_abs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_abs_epi16 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 514 of file avx512vlbwintrin.h.
References _mm_abs_epi16().
_mm_mask_abs_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_abs_epi8 (__m128i __W, __mmask16 __U, __m128i __A) static
Definition at line 482 of file avx512vlbwintrin.h.
References _mm_abs_epi8().
_mm_mask_add_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_add_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 380 of file avx512vlbwintrin.h.
References _mm_add_epi16().
_mm_mask_add_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_add_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 366 of file avx512vlbwintrin.h.
References _mm_add_epi8().
_mm_mask_adds_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_adds_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 705 of file avx512vlbwintrin.h.
References _mm_adds_epi16().
_mm_mask_adds_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_adds_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 673 of file avx512vlbwintrin.h.
References _mm_adds_epi8().
_mm_mask_adds_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_adds_epu16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 769 of file avx512vlbwintrin.h.
References _mm_adds_epu16().
_mm_mask_adds_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_adds_epu8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 737 of file avx512vlbwintrin.h.
References _mm_adds_epu8().
_mm_mask_avg_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_avg_epu16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 833 of file avx512vlbwintrin.h.
References _mm_avg_epu16().
_mm_mask_avg_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_avg_epu8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 801 of file avx512vlbwintrin.h.
References _mm_avg_epu8().
_mm_mask_blend_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_blend_epi16 (__mmask8 __U, __m128i __A, __m128i __W) static
Definition at line 466 of file avx512vlbwintrin.h.
_mm_mask_blend_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_blend_epi8 (__mmask16 __U, __m128i __A, __m128i __W) static
Definition at line 450 of file avx512vlbwintrin.h.
_mm_mask_broadcastb_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_broadcastb_epi8 (__m128i __O, __mmask16 __M, __m128i __A) static
Definition at line 2622 of file avx512vlbwintrin.h.
References _mm_broadcastb_epi8().
_mm_mask_broadcastw_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_broadcastw_epi16 (__m128i __O, __mmask8 __M, __m128i __A) static
Definition at line 2654 of file avx512vlbwintrin.h.
References _mm_broadcastw_epi16().
_mm_mask_cvtepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi16_epi8 (__m128i __O, __mmask8 __M, __m128i __A) static
Definition at line 1498 of file avx512vlbwintrin.h.
_mm_mask_cvtepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi16_storeu_epi8 (void * __P, __mmask8 __M, __m128i __A) static
Definition at line 1512 of file avx512vlbwintrin.h.
References __P.
_mm_mask_cvtepi8_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi8_epi16 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 1764 of file avx512vlbwintrin.h.
References _mm_cvtepi8_epi16().
_mm_mask_cvtepu8_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu8_epi16 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 1797 of file avx512vlbwintrin.h.
References _mm_cvtepu8_epi16().
_mm_mask_cvtsepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtsepi16_epi8 (__m128i __O, __mmask8 __M, __m128i __A) static
Definition at line 1413 of file avx512vlbwintrin.h.
_mm_mask_cvtsepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_cvtsepi16_storeu_epi8 (void * __P, __mmask8 __M, __m128i __A) static
Definition at line 1519 of file avx512vlbwintrin.h.
References __P.
_mm_mask_cvtusepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtusepi16_epi8 (__m128i __O, __mmask8 __M, __m128i __A) static
Definition at line 1455 of file avx512vlbwintrin.h.
_mm_mask_cvtusepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_cvtusepi16_storeu_epi8 (void * __P, __mmask8 __M, __m128i __A) static
Definition at line 1525 of file avx512vlbwintrin.h.
References __P.
_mm_mask_loadu_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_loadu_epi16 (__m128i __W, __mmask8 __U, void const * __P) static
Definition at line 2304 of file avx512vlbwintrin.h.
References __P.
_mm_mask_loadu_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_loadu_epi8 (__m128i __W, __mmask16 __U, void const * __P) static
Definition at line 2356 of file avx512vlbwintrin.h.
References __P.
_mm_mask_madd_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_madd_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1378 of file avx512vlbwintrin.h.
References _mm_madd_epi16().
_mm_mask_maddubs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_maddubs_epi16 (__m128i __W, __mmask8 __U, __m128i __X, __m128i __Y) static
Definition at line 1349 of file avx512vlbwintrin.h.
References __Y, and _mm_maddubs_epi16().
_mm_mask_max_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_max_epi16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 905 of file avx512vlbwintrin.h.
References _mm_max_epi16().
_mm_mask_max_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_max_epi8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 873 of file avx512vlbwintrin.h.
References _mm_max_epi8().
_mm_mask_max_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_max_epu16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 969 of file avx512vlbwintrin.h.
References _mm_max_epu16().
_mm_mask_max_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_max_epu8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 937 of file avx512vlbwintrin.h.
References _mm_max_epu8().
_mm_mask_min_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_min_epi16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 1033 of file avx512vlbwintrin.h.
References _mm_min_epi16().
_mm_mask_min_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_min_epi8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 1001 of file avx512vlbwintrin.h.
References _mm_min_epi8().
_mm_mask_min_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_min_epu16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 1097 of file avx512vlbwintrin.h.
References _mm_min_epu16().
_mm_mask_min_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_min_epu8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 1065 of file avx512vlbwintrin.h.
References _mm_min_epu8().
_mm_mask_mov_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mov_epi16 (__m128i __W, __mmask8 __U, __m128i __A) static
Definition at line 2198 of file avx512vlbwintrin.h.
Referenced by _mm_mask_reduce_and_epi16(), _mm_mask_reduce_max_epi16(), _mm_mask_reduce_min_epi16(), _mm_mask_reduce_min_epu16(), and _mm_mask_reduce_mul_epi16().
_mm_mask_mov_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mov_epi8 (__m128i __W, __mmask16 __U, __m128i __A) static
Definition at line 2230 of file avx512vlbwintrin.h.
Referenced by _mm_mask_reduce_and_epi8(), _mm_mask_reduce_max_epi8(), _mm_mask_reduce_min_epi8(), _mm_mask_reduce_min_epu8(), and _mm_mask_reduce_mul_epi8().
_mm_mask_mulhi_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mulhi_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1624 of file avx512vlbwintrin.h.
References _mm_mulhi_epi16().
_mm_mask_mulhi_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mulhi_epu16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1596 of file avx512vlbwintrin.h.
References _mm_mulhi_epu16().
_mm_mask_mulhrs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mulhrs_epi16 (__m128i __W, __mmask8 __U, __m128i __X, __m128i __Y) static
Definition at line 1568 of file avx512vlbwintrin.h.
References __Y, and _mm_mulhrs_epi16().
_mm_mask_mullo_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mullo_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 436 of file avx512vlbwintrin.h.
References _mm_mullo_epi16().
_mm_mask_packs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_packs_epi16 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 585 of file avx512vlbwintrin.h.
References _mm_packs_epi16().
_mm_mask_packs_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_packs_epi32 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 553 of file avx512vlbwintrin.h.
References _mm_packs_epi32().
_mm_mask_packus_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_packus_epi16 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 649 of file avx512vlbwintrin.h.
References _mm_packus_epi16().
_mm_mask_packus_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_packus_epi32 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 617 of file avx512vlbwintrin.h.
References _mm_packus_epi32().
_mm_mask_permutex2var_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_permutex2var_epi16 (__m128i __A, __mmask8 __U, __m128i __I, __m128i __B) static
Definition at line 1288 of file avx512vlbwintrin.h.
References _mm_permutex2var_epi16().
_mm_mask_permutexvar_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_permutexvar_epi16 (__m128i __W, __mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 2732 of file avx512vlbwintrin.h.
References _mm_permutexvar_epi16().
_mm_mask_reduce_add_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_add_epi16 (__mmask8 __M, __m128i __W) static
Definition at line 2833 of file avx512vlbwintrin.h.
References _mm_maskz_mov_epi16().
_mm_mask_reduce_add_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_add_epi8 (__mmask16 __M, __m128i __W) static
Definition at line 3009 of file avx512vlbwintrin.h.
References _mm_maskz_mov_epi8().
_mm_mask_reduce_and_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_and_epi16 (__mmask8 __M, __m128i __W) static
Definition at line 2845 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi16(), and _mm_set1_epi16().
_mm_mask_reduce_and_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_and_epi8 (__mmask16 __M, __m128i __W) static
Definition at line 3021 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi8(), and _mm_set1_epi8().
_mm_mask_reduce_max_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_max_epi16 (__mmask16 __M, __m128i __V) static
Definition at line 2877 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi16(), and _mm_set1_epi16().
_mm_mask_reduce_max_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_max_epi8 (__mmask16 __M, __m128i __V) static
Definition at line 3053 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi8(), and _mm_set1_epi8().
_mm_mask_reduce_max_epu16()
static __inline__ unsigned short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_max_epu16 (__mmask16 __M, __m128i __V) static
Definition at line 2883 of file avx512vlbwintrin.h.
References _mm_maskz_mov_epi16().
_mm_mask_reduce_max_epu8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_max_epu8 (__mmask16 __M, __m128i __V) static
Definition at line 3059 of file avx512vlbwintrin.h.
References _mm_maskz_mov_epi8().
_mm_mask_reduce_min_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_min_epi16 (__mmask16 __M, __m128i __V) static
Definition at line 2889 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi16(), and _mm_set1_epi16().
_mm_mask_reduce_min_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_min_epi8 (__mmask16 __M, __m128i __V) static
Definition at line 3065 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi8(), and _mm_set1_epi8().
_mm_mask_reduce_min_epu16()
static __inline__ unsigned short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_min_epu16 (__mmask16 __M, __m128i __V) static
Definition at line 2895 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi16(), and _mm_set1_epi16().
_mm_mask_reduce_min_epu8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_min_epu8 (__mmask16 __M, __m128i __V) static
Definition at line 3071 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi8(), and _mm_set1_epi8().
_mm_mask_reduce_mul_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_mul_epi16 (__mmask8 __M, __m128i __W) static
Definition at line 2839 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi16(), and _mm_set1_epi16().
_mm_mask_reduce_mul_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_mul_epi8 (__mmask16 __M, __m128i __W) static
Definition at line 3015 of file avx512vlbwintrin.h.
References _mm_mask_mov_epi8(), and _mm_set1_epi8().
_mm_mask_reduce_or_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_mask_reduce_or_epi16 (__mmask8 __M, __m128i __W) static
Definition at line 2851 of file avx512vlbwintrin.h.
References _mm_maskz_mov_epi16().
_mm_mask_reduce_or_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_mask_reduce_or_epi8 (__mmask16 __M, __m128i __W) static
Definition at line 3027 of file avx512vlbwintrin.h.
References _mm_maskz_mov_epi8().
_mm_mask_set1_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_set1_epi16 (__m128i __O, __mmask8 __M, short __A) static
Definition at line 2702 of file avx512vlbwintrin.h.
References _mm_set1_epi16().
_mm_mask_set1_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_set1_epi8 (__m128i __O, __mmask16 __M, char __A) static
Definition at line 2263 of file avx512vlbwintrin.h.
References _mm_set1_epi8().
_mm_mask_shuffle_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_shuffle_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1121 of file avx512vlbwintrin.h.
References _mm_shuffle_epi8().
_mm_mask_sll_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sll_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1916 of file avx512vlbwintrin.h.
References _mm_sll_epi16().
_mm_mask_slli_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_slli_epi16 (__m128i __W, __mmask8 __U, __m128i __A, unsigned int __B) static
Definition at line 1948 of file avx512vlbwintrin.h.
References _mm_slli_epi16().
_mm_mask_sllv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sllv_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1900 of file avx512vlbwintrin.h.
References _mm_sllv_epi16().
_mm_mask_sra_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sra_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2069 of file avx512vlbwintrin.h.
References _mm_sra_epi16().
_mm_mask_srai_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srai_epi16 (__m128i __W, __mmask8 __U, __m128i __A, unsigned int __B) static
Definition at line 2101 of file avx512vlbwintrin.h.
References _mm_srai_epi16().
_mm_mask_srav_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srav_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2053 of file avx512vlbwintrin.h.
References _mm_srav_epi16().
_mm_mask_srl_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srl_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2134 of file avx512vlbwintrin.h.
References _mm_srl_epi16().
_mm_mask_srli_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srli_epi16 (__m128i __W, __mmask8 __U, __m128i __A, int __B) static
Definition at line 2166 of file avx512vlbwintrin.h.
References _mm_srli_epi16().
_mm_mask_srlv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_srlv_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2009 of file avx512vlbwintrin.h.
References _mm_srlv_epi16().
_mm_mask_storeu_epi16()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_storeu_epi16 (void * __P, __mmask8 __U, __m128i __A) static
Definition at line 2408 of file avx512vlbwintrin.h.
References __P.
_mm_mask_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS128 _mm_mask_storeu_epi8 (void * __P, __mmask16 __U, __m128i __A) static
Definition at line 2442 of file avx512vlbwintrin.h.
References __P.
_mm_mask_sub_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sub_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 408 of file avx512vlbwintrin.h.
References _mm_sub_epi16().
_mm_mask_sub_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_sub_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 394 of file avx512vlbwintrin.h.
References _mm_sub_epi8().
_mm_mask_subs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_subs_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1185 of file avx512vlbwintrin.h.
References _mm_subs_epi16().
_mm_mask_subs_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_subs_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1153 of file avx512vlbwintrin.h.
References _mm_subs_epi8().
_mm_mask_subs_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_subs_epu16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1249 of file avx512vlbwintrin.h.
References _mm_subs_epu16().
_mm_mask_subs_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_subs_epu8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1217 of file avx512vlbwintrin.h.
References _mm_subs_epu8().
_mm_mask_test_epi16_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_mask_test_epi16_mask (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2500 of file avx512vlbwintrin.h.
References _mm_and_si128(), _mm_mask_cmpneq_epi16_mask, and _mm_setzero_si128().
_mm_mask_test_epi8_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_mask_test_epi8_mask (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 2473 of file avx512vlbwintrin.h.
References _mm_and_si128(), _mm_mask_cmpneq_epi8_mask, and _mm_setzero_si128().
_mm_mask_testn_epi16_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_mask_testn_epi16_mask (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2554 of file avx512vlbwintrin.h.
References _mm_and_si128(), _mm_mask_cmpeq_epi16_mask, and _mm_setzero_si128().
_mm_mask_testn_epi8_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_mask_testn_epi8_mask (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 2527 of file avx512vlbwintrin.h.
References _mm_and_si128(), _mm_mask_cmpeq_epi8_mask, and _mm_setzero_si128().
_mm_mask_unpackhi_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_unpackhi_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1680 of file avx512vlbwintrin.h.
References _mm_unpackhi_epi16().
_mm_mask_unpackhi_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_unpackhi_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1652 of file avx512vlbwintrin.h.
References _mm_unpackhi_epi8().
_mm_mask_unpacklo_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_unpacklo_epi16 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1736 of file avx512vlbwintrin.h.
References _mm_unpacklo_epi16().
_mm_mask_unpacklo_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_unpacklo_epi8 (__m128i __W, __mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1708 of file avx512vlbwintrin.h.
References _mm_unpacklo_epi8().
_mm_maskz_abs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_abs_epi16 (__mmask8 __U, __m128i __A) static
Definition at line 522 of file avx512vlbwintrin.h.
References _mm_abs_epi16(), and _mm_setzero_si128().
_mm_maskz_abs_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_abs_epi8 (__mmask16 __U, __m128i __A) static
Definition at line 490 of file avx512vlbwintrin.h.
References _mm_abs_epi8(), and _mm_setzero_si128().
_mm_maskz_add_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_add_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 387 of file avx512vlbwintrin.h.
References _mm_add_epi16(), and _mm_setzero_si128().
_mm_maskz_add_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_add_epi8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 373 of file avx512vlbwintrin.h.
References _mm_add_epi8(), and _mm_setzero_si128().
_mm_maskz_adds_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_adds_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 713 of file avx512vlbwintrin.h.
References _mm_adds_epi16(), and _mm_setzero_si128().
_mm_maskz_adds_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_adds_epi8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 681 of file avx512vlbwintrin.h.
References _mm_adds_epi8(), and _mm_setzero_si128().
_mm_maskz_adds_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_adds_epu16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 777 of file avx512vlbwintrin.h.
References _mm_adds_epu16(), and _mm_setzero_si128().
_mm_maskz_adds_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_adds_epu8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 745 of file avx512vlbwintrin.h.
References _mm_adds_epu8(), and _mm_setzero_si128().
_mm_maskz_avg_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_avg_epu16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 841 of file avx512vlbwintrin.h.
References _mm_avg_epu16(), and _mm_setzero_si128().
_mm_maskz_avg_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_avg_epu8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 809 of file avx512vlbwintrin.h.
References _mm_avg_epu8(), and _mm_setzero_si128().
_mm_maskz_broadcastb_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_broadcastb_epi8 (__mmask16 __M, __m128i __A) static
Definition at line 2630 of file avx512vlbwintrin.h.
References _mm_broadcastb_epi8(), and _mm_setzero_si128().
_mm_maskz_broadcastw_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_broadcastw_epi16 (__mmask8 __M, __m128i __A) static
Definition at line 2662 of file avx512vlbwintrin.h.
References _mm_broadcastw_epi16(), and _mm_setzero_si128().
_mm_maskz_cvtepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi16_epi8 (__mmask8 __M, __m128i __A) static
Definition at line 1505 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtepi8_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi8_epi16 (__mmask8 __U, __m128i __A) static
Definition at line 1772 of file avx512vlbwintrin.h.
References _mm_cvtepi8_epi16(), and _mm_setzero_si128().
_mm_maskz_cvtepu8_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu8_epi16 (__mmask8 __U, __m128i __A) static
Definition at line 1805 of file avx512vlbwintrin.h.
References _mm_cvtepu8_epi16(), and _mm_setzero_si128().
_mm_maskz_cvtsepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtsepi16_epi8 (__mmask8 __M, __m128i __A) static
Definition at line 1420 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtusepi16_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtusepi16_epi8 (__mmask8 __M, __m128i __A) static
Definition at line 1462 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
_mm_maskz_loadu_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_loadu_epi16 (__mmask8 __U, void const * __P) static
Definition at line 2312 of file avx512vlbwintrin.h.
References __P, and _mm_setzero_si128().
_mm_maskz_loadu_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_loadu_epi8 (__mmask16 __U, void const * __P) static
Definition at line 2364 of file avx512vlbwintrin.h.
References __P, and _mm_setzero_si128().
_mm_maskz_madd_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_madd_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1385 of file avx512vlbwintrin.h.
References _mm_madd_epi16(), and _mm_setzero_si128().
_mm_maskz_maddubs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_maddubs_epi16 (__mmask8 __U, __m128i __X, __m128i __Y) static
Definition at line 1356 of file avx512vlbwintrin.h.
References __Y, _mm_maddubs_epi16(), and _mm_setzero_si128().
_mm_maskz_max_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_max_epi16 (__mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 897 of file avx512vlbwintrin.h.
References _mm_max_epi16(), and _mm_setzero_si128().
_mm_maskz_max_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_max_epi8 (__mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 865 of file avx512vlbwintrin.h.
References _mm_max_epi8(), and _mm_setzero_si128().
_mm_maskz_max_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_max_epu16 (__mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 961 of file avx512vlbwintrin.h.
References _mm_max_epu16(), and _mm_setzero_si128().
_mm_maskz_max_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_max_epu8 (__mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 929 of file avx512vlbwintrin.h.
References _mm_max_epu8(), and _mm_setzero_si128().
_mm_maskz_min_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_min_epi16 (__mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 1025 of file avx512vlbwintrin.h.
References _mm_min_epi16(), and _mm_setzero_si128().
_mm_maskz_min_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_min_epi8 (__mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 993 of file avx512vlbwintrin.h.
References _mm_min_epi8(), and _mm_setzero_si128().
_mm_maskz_min_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_min_epu16 (__mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 1089 of file avx512vlbwintrin.h.
References _mm_min_epu16(), and _mm_setzero_si128().
_mm_maskz_min_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_min_epu8 (__mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 1057 of file avx512vlbwintrin.h.
References _mm_min_epu8(), and _mm_setzero_si128().
_mm_maskz_mov_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mov_epi16 (__mmask8 __U, __m128i __A) static
Definition at line 2206 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
Referenced by _mm_mask_reduce_add_epi16(), _mm_mask_reduce_max_epu16(), and _mm_mask_reduce_or_epi16().
_mm_maskz_mov_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mov_epi8 (__mmask16 __U, __m128i __A) static
Definition at line 2238 of file avx512vlbwintrin.h.
References _mm_setzero_si128().
Referenced by _mm_mask_reduce_add_epi8(), _mm_mask_reduce_max_epu8(), and _mm_mask_reduce_or_epi8().
_mm_maskz_mulhi_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mulhi_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1631 of file avx512vlbwintrin.h.
References _mm_mulhi_epi16(), and _mm_setzero_si128().
_mm_maskz_mulhi_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mulhi_epu16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1603 of file avx512vlbwintrin.h.
References _mm_mulhi_epu16(), and _mm_setzero_si128().
_mm_maskz_mulhrs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mulhrs_epi16 (__mmask8 __U, __m128i __X, __m128i __Y) static
Definition at line 1575 of file avx512vlbwintrin.h.
References __Y, _mm_mulhrs_epi16(), and _mm_setzero_si128().
_mm_maskz_mullo_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mullo_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 443 of file avx512vlbwintrin.h.
References _mm_mullo_epi16(), and _mm_setzero_si128().
_mm_maskz_packs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_packs_epi16 (__mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 577 of file avx512vlbwintrin.h.
References _mm_packs_epi16(), and _mm_setzero_si128().
_mm_maskz_packs_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_packs_epi32 (__mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 546 of file avx512vlbwintrin.h.
References _mm_packs_epi32(), and _mm_setzero_si128().
_mm_maskz_packus_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_packus_epi16 (__mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 641 of file avx512vlbwintrin.h.
References _mm_packus_epi16(), and _mm_setzero_si128().
_mm_maskz_packus_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_packus_epi32 (__mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 609 of file avx512vlbwintrin.h.
References _mm_packus_epi32(), and _mm_setzero_si128().
_mm_maskz_permutex2var_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_permutex2var_epi16 (__mmask8 __U, __m128i __A, __m128i __I, __m128i __B) static
Definition at line 1306 of file avx512vlbwintrin.h.
References _mm_permutex2var_epi16(), and _mm_setzero_si128().
_mm_maskz_permutexvar_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_permutexvar_epi16 (__mmask8 __M, __m128i __A, __m128i __B) static
Definition at line 2724 of file avx512vlbwintrin.h.
References _mm_permutexvar_epi16(), and _mm_setzero_si128().
_mm_maskz_set1_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_set1_epi16 (__mmask8 __M, short __A) static
Definition at line 2710 of file avx512vlbwintrin.h.
References _mm_set1_epi16(), and _mm_setzero_si128().
_mm_maskz_set1_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_set1_epi8 (__mmask16 __M, char __A) static
Definition at line 2271 of file avx512vlbwintrin.h.
References _mm_set1_epi8(), and _mm_setzero_si128().
_mm_maskz_shuffle_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_shuffle_epi8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1129 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_shuffle_epi8().
_mm_maskz_sll_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sll_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1924 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_sll_epi16().
_mm_maskz_slli_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_slli_epi16 (__mmask8 __U, __m128i __A, unsigned int __B) static
Definition at line 1956 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_slli_epi16().
_mm_maskz_sllv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sllv_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1908 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_sllv_epi16().
_mm_maskz_sra_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sra_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2077 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_sra_epi16().
_mm_maskz_srai_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srai_epi16 (__mmask8 __U, __m128i __A, unsigned int __B) static
Definition at line 2109 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_srai_epi16().
_mm_maskz_srav_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srav_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2061 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_srav_epi16().
_mm_maskz_srl_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srl_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2142 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_srl_epi16().
_mm_maskz_srli_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srli_epi16 (__mmask8 __U, __m128i __A, int __B) static
Definition at line 2174 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_srli_epi16().
_mm_maskz_srlv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_srlv_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 2017 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_srlv_epi16().
_mm_maskz_sub_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sub_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 415 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_sub_epi16().
_mm_maskz_sub_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_sub_epi8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 401 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_sub_epi8().
_mm_maskz_subs_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_subs_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1193 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_subs_epi16().
_mm_maskz_subs_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_subs_epi8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1161 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_subs_epi8().
_mm_maskz_subs_epu16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_subs_epu16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1257 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_subs_epu16().
_mm_maskz_subs_epu8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_subs_epu8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1225 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_subs_epu8().
_mm_maskz_unpackhi_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_unpackhi_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1687 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_unpackhi_epi16().
_mm_maskz_unpackhi_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_unpackhi_epi8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1659 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_unpackhi_epi8().
_mm_maskz_unpacklo_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_unpacklo_epi16 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 1743 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_unpacklo_epi16().
_mm_maskz_unpacklo_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_unpacklo_epi8 (__mmask16 __U, __m128i __A, __m128i __B) static
Definition at line 1715 of file avx512vlbwintrin.h.
References _mm_setzero_si128(), and _mm_unpacklo_epi8().
_mm_movepi16_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_movepi16_mask (__m128i __A) static
Definition at line 2586 of file avx512vlbwintrin.h.
_mm_movepi8_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_movepi8_mask (__m128i __A) static
Definition at line 2574 of file avx512vlbwintrin.h.
_mm_movm_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_movm_epi16 (__mmask8 __A) static
Definition at line 2610 of file avx512vlbwintrin.h.
_mm_movm_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_movm_epi8 (__mmask16 __A) static
Definition at line 2598 of file avx512vlbwintrin.h.
_mm_permutex2var_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_permutex2var_epi16 (__m128i __A, __m128i __I, __m128i __B) static
Definition at line 1281 of file avx512vlbwintrin.h.
Referenced by _mm_mask2_permutex2var_epi16(), _mm_mask_permutex2var_epi16(), and _mm_maskz_permutex2var_epi16().
_mm_permutexvar_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_permutexvar_epi16 (__m128i __A, __m128i __B) static
Definition at line 2718 of file avx512vlbwintrin.h.
Referenced by _mm_mask_permutexvar_epi16(), and _mm_maskz_permutexvar_epi16().
_mm_reduce_add_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_add_epi16 (__m128i __W) static
Definition at line 2813 of file avx512vlbwintrin.h.
_mm_reduce_add_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_add_epi8 (__m128i __W) static
Definition at line 2989 of file avx512vlbwintrin.h.
_mm_reduce_and_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_and_epi16 (__m128i __W) static
Definition at line 2823 of file avx512vlbwintrin.h.
_mm_reduce_and_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_and_epi8 (__m128i __W) static
Definition at line 2999 of file avx512vlbwintrin.h.
_mm_reduce_max_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_max_epi16 (__m128i __V) static
Definition at line 2857 of file avx512vlbwintrin.h.
_mm_reduce_max_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_max_epi8 (__m128i __V) static
Definition at line 3033 of file avx512vlbwintrin.h.
_mm_reduce_max_epu16()
static __inline__ unsigned short __DEFAULT_FN_ATTRS128 _mm_reduce_max_epu16 (__m128i __V) static
Definition at line 2862 of file avx512vlbwintrin.h.
_mm_reduce_max_epu8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS128 _mm_reduce_max_epu8 (__m128i __V) static
Definition at line 3038 of file avx512vlbwintrin.h.
_mm_reduce_min_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_min_epi16 (__m128i __V) static
Definition at line 2867 of file avx512vlbwintrin.h.
_mm_reduce_min_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_min_epi8 (__m128i __V) static
Definition at line 3043 of file avx512vlbwintrin.h.
_mm_reduce_min_epu16()
static __inline__ unsigned short __DEFAULT_FN_ATTRS128 _mm_reduce_min_epu16 (__m128i __V) static
Definition at line 2872 of file avx512vlbwintrin.h.
_mm_reduce_min_epu8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS128 _mm_reduce_min_epu8 (__m128i __V) static
Definition at line 3048 of file avx512vlbwintrin.h.
_mm_reduce_mul_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_mul_epi16 (__m128i __W) static
Definition at line 2818 of file avx512vlbwintrin.h.
_mm_reduce_mul_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_mul_epi8 (__m128i __W) static
Definition at line 2994 of file avx512vlbwintrin.h.
_mm_reduce_or_epi16()
static __inline__ short __DEFAULT_FN_ATTRS128 _mm_reduce_or_epi16 (__m128i __W) static
Definition at line 2828 of file avx512vlbwintrin.h.
_mm_reduce_or_epi8()
static __inline__ signed char __DEFAULT_FN_ATTRS128 _mm_reduce_or_epi8 (__m128i __W) static
Definition at line 3004 of file avx512vlbwintrin.h.
_mm_sllv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_sllv_epi16 (__m128i __A, __m128i __B) static
Definition at line 1894 of file avx512vlbwintrin.h.
Referenced by _mm_mask_sllv_epi16(), and _mm_maskz_sllv_epi16().
_mm_srav_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_srav_epi16 (__m128i __A, __m128i __B) static
Definition at line 2047 of file avx512vlbwintrin.h.
Referenced by _mm_mask_srav_epi16(), and _mm_maskz_srav_epi16().
_mm_srlv_epi16()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_srlv_epi16 (__m128i __A, __m128i __B) static
Definition at line 2003 of file avx512vlbwintrin.h.
Referenced by _mm_mask_srlv_epi16(), and _mm_maskz_srlv_epi16().
_mm_storeu_epi16()
static __inline void __DEFAULT_FN_ATTRS128 _mm_storeu_epi16 (void * __P, __m128i __A) static
Definition at line 2399 of file avx512vlbwintrin.h.
References __P, and __v.
_mm_storeu_epi8()
static __inline void __DEFAULT_FN_ATTRS128 _mm_storeu_epi8 (void * __P, __m128i __A) static
Definition at line 2433 of file avx512vlbwintrin.h.
References __P, and __v.
_mm_test_epi16_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_test_epi16_mask (__m128i __A, __m128i __B) static
Definition at line 2494 of file avx512vlbwintrin.h.
References _mm_and_si128(), _mm_cmpneq_epi16_mask, and _mm_setzero_si128().
_mm_test_epi8_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_test_epi8_mask (__m128i __A, __m128i __B) static
Definition at line 2467 of file avx512vlbwintrin.h.
References _mm_and_si128(), _mm_cmpneq_epi8_mask, and _mm_setzero_si128().
_mm_testn_epi16_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_testn_epi16_mask (__m128i __A, __m128i __B) static
Definition at line 2548 of file avx512vlbwintrin.h.
References _mm_and_si128(), _mm_cmpeq_epi16_mask, and _mm_setzero_si128().
_mm_testn_epi8_mask()
static __inline__ __mmask16 __DEFAULT_FN_ATTRS128 _mm_testn_epi8_mask (__m128i __A, __m128i __B) static
Definition at line 2521 of file avx512vlbwintrin.h.
References _mm_and_si128(), _mm_cmpeq_epi8_mask, and _mm_setzero_si128().