clang: lib/Headers/avx512vbmiintrin.h File Reference
avx512vbmiintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512vbmi"), __min_vector_width__(512)))
Functions
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_permutex2var_epi8 (__m512i __A, __m512i __I, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_permutex2var_epi8 (__m512i __A, __mmask64 __U, __m512i __I, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask2_permutex2var_epi8 (__m512i __A, __m512i __I, __mmask64 __U, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_permutex2var_epi8 (__mmask64 __U, __m512i __A, __m512i __I, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_permutexvar_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_permutexvar_epi8 (__mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_permutexvar_epi8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_multishift_epi64_epi8 (__m512i __X, __m512i __Y)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_multishift_epi64_epi8 (__m512i __W, __mmask64 __M, __m512i __X, __m512i __Y)
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_multishift_epi64_epi8 (__mmask64 __M, __m512i __X, __m512i __Y)
Macro Definition Documentation
__DEFAULT_FN_ATTRS
#define __DEFAULT_FN_ATTRS __attribute__((__always_inline__, __nodebug__, __target__("avx512vbmi"), __min_vector_width__(512)))
Definition at line 18 of file avx512vbmiintrin.h.
Function Documentation
_mm512_mask2_permutex2var_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask2_permutex2var_epi8 (__m512i __A, __m512i __I, __mmask64 __U, __m512i __B) static
Definition at line 38 of file avx512vbmiintrin.h.
References _mm512_permutex2var_epi8().
_mm512_mask_multishift_epi64_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_multishift_epi64_epi8 (__m512i __W, __mmask64 __M, __m512i __X, __m512i __Y) static
Definition at line 86 of file avx512vbmiintrin.h.
References __Y, and _mm512_multishift_epi64_epi8().
_mm512_mask_permutex2var_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_permutex2var_epi8 (__m512i __A, __mmask64 __U, __m512i __I, __m512i __B) static
Definition at line 29 of file avx512vbmiintrin.h.
References _mm512_permutex2var_epi8().
_mm512_mask_permutexvar_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_mask_permutexvar_epi8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 71 of file avx512vbmiintrin.h.
References _mm512_permutexvar_epi8().
_mm512_maskz_multishift_epi64_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_multishift_epi64_epi8 (__mmask64 __M, __m512i __X, __m512i __Y) static
Definition at line 95 of file avx512vbmiintrin.h.
References __Y, _mm512_multishift_epi64_epi8(), and _mm512_setzero_si512().
_mm512_maskz_permutex2var_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_permutex2var_epi8 (__mmask64 __U, __m512i __A, __m512i __I, __m512i __B) static
Definition at line 47 of file avx512vbmiintrin.h.
References _mm512_permutex2var_epi8(), and _mm512_setzero_si512().
_mm512_maskz_permutexvar_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_maskz_permutexvar_epi8 (__mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 62 of file avx512vbmiintrin.h.
References _mm512_permutexvar_epi8(), and _mm512_setzero_si512().
_mm512_multishift_epi64_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_multishift_epi64_epi8 (__m512i __X, __m512i __Y) static
Definition at line 80 of file avx512vbmiintrin.h.
References __Y.
Referenced by _mm512_mask_multishift_epi64_epi8(), and _mm512_maskz_multishift_epi64_epi8().
_mm512_permutex2var_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_permutex2var_epi8 (__m512i __A, __m512i __I, __m512i __B) static
Definition at line 22 of file avx512vbmiintrin.h.
Referenced by _mm512_mask2_permutex2var_epi8(), _mm512_mask_permutex2var_epi8(), and _mm512_maskz_permutex2var_epi8().
_mm512_permutexvar_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS _mm512_permutexvar_epi8 (__m512i __A, __m512i __B) static
Definition at line 56 of file avx512vbmiintrin.h.
Referenced by _mm512_mask_permutexvar_epi8(), and _mm512_maskz_permutexvar_epi8().