clang: lib/Headers/avx512bwintrin.h File Reference
avx512bwintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS512
#define __DEFAULT_FN_ATTRS
#define _kshiftli_mask32(A, I) ((__mmask32)__builtin_ia32_kshiftlisi((__mmask32)(A), (unsigned int)(I)))
#define _kshiftri_mask32(A, I) ((__mmask32)__builtin_ia32_kshiftrisi((__mmask32)(A), (unsigned int)(I)))
#define _kshiftli_mask64(A, I) ((__mmask64)__builtin_ia32_kshiftlidi((__mmask64)(A), (unsigned int)(I)))
#define _kshiftri_mask64(A, I) ((__mmask64)__builtin_ia32_kshiftridi((__mmask64)(A), (unsigned int)(I)))
#define _mm512_cmp_epi8_mask(a, b, p)
#define _mm512_mask_cmp_epi8_mask(m, a, b, p)
#define _mm512_cmp_epu8_mask(a, b, p)
#define _mm512_mask_cmp_epu8_mask(m, a, b, p)
#define _mm512_cmp_epi16_mask(a, b, p)
#define _mm512_mask_cmp_epi16_mask(m, a, b, p)
#define _mm512_cmp_epu16_mask(a, b, p)
#define _mm512_mask_cmp_epu16_mask(m, a, b, p)
#define _mm512_cmpeq_epi8_mask(A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_EQ)
#define _mm512_mask_cmpeq_epi8_mask(k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm512_cmpge_epi8_mask(A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_GE)
#define _mm512_mask_cmpge_epi8_mask(k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm512_cmpgt_epi8_mask(A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_GT)
#define _mm512_mask_cmpgt_epi8_mask(k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm512_cmple_epi8_mask(A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_LE)
#define _mm512_mask_cmple_epi8_mask(k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm512_cmplt_epi8_mask(A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_LT)
#define _mm512_mask_cmplt_epi8_mask(k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm512_cmpneq_epi8_mask(A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_NE)
#define _mm512_mask_cmpneq_epi8_mask(k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm512_cmpeq_epu8_mask(A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_EQ)
#define _mm512_mask_cmpeq_epu8_mask(k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm512_cmpge_epu8_mask(A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_GE)
#define _mm512_mask_cmpge_epu8_mask(k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm512_cmpgt_epu8_mask(A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_GT)
#define _mm512_mask_cmpgt_epu8_mask(k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm512_cmple_epu8_mask(A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_LE)
#define _mm512_mask_cmple_epu8_mask(k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm512_cmplt_epu8_mask(A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_LT)
#define _mm512_mask_cmplt_epu8_mask(k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm512_cmpneq_epu8_mask(A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_NE)
#define _mm512_mask_cmpneq_epu8_mask(k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm512_cmpeq_epi16_mask(A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_EQ)
#define _mm512_mask_cmpeq_epi16_mask(k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm512_cmpge_epi16_mask(A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_GE)
#define _mm512_mask_cmpge_epi16_mask(k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm512_cmpgt_epi16_mask(A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_GT)
#define _mm512_mask_cmpgt_epi16_mask(k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm512_cmple_epi16_mask(A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_LE)
#define _mm512_mask_cmple_epi16_mask(k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm512_cmplt_epi16_mask(A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_LT)
#define _mm512_mask_cmplt_epi16_mask(k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm512_cmpneq_epi16_mask(A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_NE)
#define _mm512_mask_cmpneq_epi16_mask(k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm512_cmpeq_epu16_mask(A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_EQ)
#define _mm512_mask_cmpeq_epu16_mask(k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_EQ)
#define _mm512_cmpge_epu16_mask(A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_GE)
#define _mm512_mask_cmpge_epu16_mask(k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GE)
#define _mm512_cmpgt_epu16_mask(A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_GT)
#define _mm512_mask_cmpgt_epu16_mask(k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GT)
#define _mm512_cmple_epu16_mask(A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_LE)
#define _mm512_mask_cmple_epu16_mask(k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LE)
#define _mm512_cmplt_epu16_mask(A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_LT)
#define _mm512_mask_cmplt_epu16_mask(k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LT)
#define _mm512_cmpneq_epu16_mask(A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_NE)
#define _mm512_mask_cmpneq_epu16_mask(k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_NE)
#define _mm512_shufflehi_epi16(A, imm) ((__m512i)__builtin_ia32_pshufhw512((__v32hi)(__m512i)(A), (int)(imm)))
#define _mm512_mask_shufflehi_epi16(W, U, A, imm)
#define _mm512_maskz_shufflehi_epi16(U, A, imm)
#define _mm512_shufflelo_epi16(A, imm) ((__m512i)__builtin_ia32_pshuflw512((__v32hi)(__m512i)(A), (int)(imm)))
#define _mm512_mask_shufflelo_epi16(W, U, A, imm)
#define _mm512_maskz_shufflelo_epi16(U, A, imm)
#define _mm512_bslli_epi128(a, imm) ((__m512i)__builtin_ia32_pslldqi512_byteshift((__v8di)(__m512i)(a), (int)(imm)))
#define _mm512_bsrli_epi128(a, imm) ((__m512i)__builtin_ia32_psrldqi512_byteshift((__v8di)(__m512i)(a), (int)(imm)))
#define _mm512_alignr_epi8(A, B, N)
#define _mm512_mask_alignr_epi8(W, U, A, B, N)
#define _mm512_maskz_alignr_epi8(U, A, B, N)
#define _mm512_dbsad_epu8(A, B, imm)
#define _mm512_mask_dbsad_epu8(W, U, A, B, imm)
#define _mm512_maskz_dbsad_epu8(U, A, B, imm)
Typedefs
typedef unsigned int __mmask32
typedef unsigned long long __mmask64
Functions
static __inline __mmask32 __DEFAULT_FN_ATTRS _knot_mask32 (__mmask32 __M)
static __inline __mmask64 __DEFAULT_FN_ATTRS _knot_mask64 (__mmask64 __M)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kand_mask32 (__mmask32 __A, __mmask32 __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kand_mask64 (__mmask64 __A, __mmask64 __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kandn_mask32 (__mmask32 __A, __mmask32 __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kandn_mask64 (__mmask64 __A, __mmask64 __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kor_mask32 (__mmask32 __A, __mmask32 __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kor_mask64 (__mmask64 __A, __mmask64 __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kxnor_mask32 (__mmask32 __A, __mmask32 __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kxnor_mask64 (__mmask64 __A, __mmask64 __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kxor_mask32 (__mmask32 __A, __mmask32 __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kxor_mask64 (__mmask64 __A, __mmask64 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestc_mask32_u8 (__mmask32 __A, __mmask32 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestz_mask32_u8 (__mmask32 __A, __mmask32 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortest_mask32_u8 (__mmask32 __A, __mmask32 __B, unsigned char *__C)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestc_mask64_u8 (__mmask64 __A, __mmask64 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestz_mask64_u8 (__mmask64 __A, __mmask64 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortest_mask64_u8 (__mmask64 __A, __mmask64 __B, unsigned char *__C)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestc_mask32_u8 (__mmask32 __A, __mmask32 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestz_mask32_u8 (__mmask32 __A, __mmask32 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktest_mask32_u8 (__mmask32 __A, __mmask32 __B, unsigned char *__C)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestc_mask64_u8 (__mmask64 __A, __mmask64 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestz_mask64_u8 (__mmask64 __A, __mmask64 __B)
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktest_mask64_u8 (__mmask64 __A, __mmask64 __B, unsigned char *__C)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kadd_mask32 (__mmask32 __A, __mmask32 __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kadd_mask64 (__mmask64 __A, __mmask64 __B)
static __inline__ unsigned int __DEFAULT_FN_ATTRS _cvtmask32_u32 (__mmask32 __A)
static __inline__ unsigned long long __DEFAULT_FN_ATTRS _cvtmask64_u64 (__mmask64 __A)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _cvtu32_mask32 (unsigned int __A)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _cvtu64_mask64 (unsigned long long __A)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _load_mask32 (__mmask32 *__A)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _load_mask64 (__mmask64 *__A)
static __inline__ void __DEFAULT_FN_ATTRS _store_mask32 (__mmask32 *__A, __mmask32 __B)
static __inline__ void __DEFAULT_FN_ATTRS _store_mask64 (__mmask64 *__A, __mmask64 __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_add_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_add_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_add_epi8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sub_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sub_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sub_epi8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_add_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_add_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_add_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sub_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sub_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sub_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mullo_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mullo_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mullo_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_blend_epi8 (__mmask64 __U, __m512i __A, __m512i __W)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_blend_epi16 (__mmask32 __U, __m512i __A, __m512i __W)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_abs_epi8 (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_abs_epi8 (__m512i __W, __mmask64 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_abs_epi8 (__mmask64 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_abs_epi16 (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_abs_epi16 (__m512i __W, __mmask32 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_abs_epi16 (__mmask32 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_packs_epi32 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_packs_epi32 (__mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_packs_epi32 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_packs_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_packs_epi16 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_packs_epi16 (__mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_packus_epi32 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_packus_epi32 (__mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_packus_epi32 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_packus_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_packus_epi16 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_packus_epi16 (__mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_adds_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_adds_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_adds_epi8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_adds_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_adds_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_adds_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_adds_epu8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_adds_epu8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_adds_epu8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_adds_epu16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_adds_epu16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_adds_epu16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_avg_epu8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_avg_epu8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_avg_epu8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_avg_epu16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_avg_epu16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_avg_epu16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_max_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_max_epi8 (__mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_max_epi8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_max_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_max_epi16 (__mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_max_epi16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_max_epu8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_max_epu8 (__mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_max_epu8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_max_epu16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_max_epu16 (__mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_max_epu16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_min_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_min_epi8 (__mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_min_epi8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_min_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_min_epi16 (__mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_min_epi16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_min_epu8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_min_epu8 (__mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_min_epu8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_min_epu16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_min_epu16 (__mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_min_epu16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_shuffle_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_shuffle_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_shuffle_epi8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_subs_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_subs_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_subs_epi8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_subs_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_subs_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_subs_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_subs_epu8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_subs_epu8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_subs_epu8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_subs_epu16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_subs_epu16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_subs_epu16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_permutex2var_epi16 (__m512i __A, __m512i __I, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_permutex2var_epi16 (__m512i __A, __mmask32 __U, __m512i __I, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask2_permutex2var_epi16 (__m512i __A, __m512i __I, __mmask32 __U, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_permutex2var_epi16 (__mmask32 __U, __m512i __A, __m512i __I, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mulhrs_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mulhrs_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mulhrs_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mulhi_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mulhi_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mulhi_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mulhi_epu16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mulhi_epu16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mulhi_epu16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maddubs_epi16 (__m512i __X, __m512i __Y)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_maddubs_epi16 (__m512i __W, __mmask32 __U, __m512i __X, __m512i __Y)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_maddubs_epi16 (__mmask32 __U, __m512i __X, __m512i __Y)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_madd_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_madd_epi16 (__m512i __W, __mmask16 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_madd_epi16 (__mmask16 __U, __m512i __A, __m512i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_cvtsepi16_epi8 (__m512i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtsepi16_epi8 (__m256i __O, __mmask32 __M, __m512i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtsepi16_epi8 (__mmask32 __M, __m512i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_cvtusepi16_epi8 (__m512i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtusepi16_epi8 (__m256i __O, __mmask32 __M, __m512i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtusepi16_epi8 (__mmask32 __M, __m512i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_cvtepi16_epi8 (__m512i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi16_epi8 (__m256i __O, __mmask32 __M, __m512i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi16_epi8 (__mmask32 __M, __m512i __A)
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi16_storeu_epi8 (void *__P, __mmask32 __M, __m512i __A)
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_cvtsepi16_storeu_epi8 (void *__P, __mmask32 __M, __m512i __A)
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_cvtusepi16_storeu_epi8 (void *__P, __mmask32 __M, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_unpackhi_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_unpackhi_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_unpackhi_epi8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_unpackhi_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_unpackhi_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_unpackhi_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_unpacklo_epi8 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_unpacklo_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_unpacklo_epi8 (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_unpacklo_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_unpacklo_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_unpacklo_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtepi8_epi16 (__m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi8_epi16 (__m512i __W, __mmask32 __U, __m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi8_epi16 (__mmask32 __U, __m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtepu8_epi16 (__m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu8_epi16 (__m512i __W, __mmask32 __U, __m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu8_epi16 (__mmask32 __U, __m256i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sllv_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sllv_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sllv_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sll_epi16 (__m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sll_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sll_epi16 (__mmask32 __U, __m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_slli_epi16 (__m512i __A, unsigned int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_slli_epi16 (__m512i __W, __mmask32 __U, __m512i __A, unsigned int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_slli_epi16 (__mmask32 __U, __m512i __A, unsigned int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srlv_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srlv_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srlv_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srav_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srav_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srav_epi16 (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sra_epi16 (__m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sra_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sra_epi16 (__mmask32 __U, __m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srai_epi16 (__m512i __A, unsigned int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srai_epi16 (__m512i __W, __mmask32 __U, __m512i __A, unsigned int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srai_epi16 (__mmask32 __U, __m512i __A, unsigned int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srl_epi16 (__m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srl_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srl_epi16 (__mmask32 __U, __m512i __A, __m128i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srli_epi16 (__m512i __A, unsigned int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srli_epi16 (__m512i __W, __mmask32 __U, __m512i __A, unsigned int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srli_epi16 (__mmask32 __U, __m512i __A, int __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mov_epi16 (__m512i __W, __mmask32 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mov_epi16 (__mmask32 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mov_epi8 (__m512i __W, __mmask64 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mov_epi8 (__mmask64 __U, __m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_set1_epi8 (__m512i __O, __mmask64 __M, char __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_set1_epi8 (__mmask64 __M, char __A)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _mm512_kunpackd (__mmask64 __A, __mmask64 __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _mm512_kunpackw (__mmask32 __A, __mmask32 __B)
static __inline __m512i __DEFAULT_FN_ATTRS512 _mm512_loadu_epi16 (void const *__P)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_loadu_epi16 (__m512i __W, __mmask32 __U, void const *__P)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_loadu_epi16 (__mmask32 __U, void const *__P)
static __inline __m512i __DEFAULT_FN_ATTRS512 _mm512_loadu_epi8 (void const *__P)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_loadu_epi8 (__m512i __W, __mmask64 __U, void const *__P)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_loadu_epi8 (__mmask64 __U, void const *__P)
static __inline void __DEFAULT_FN_ATTRS512 _mm512_storeu_epi16 (void *__P, __m512i __A)
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_storeu_epi16 (void *__P, __mmask32 __U, __m512i __A)
static __inline void __DEFAULT_FN_ATTRS512 _mm512_storeu_epi8 (void *__P, __m512i __A)
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_storeu_epi8 (void *__P, __mmask64 __U, __m512i __A)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_test_epi8_mask (__m512i __A, __m512i __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_mask_test_epi8_mask (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_test_epi16_mask (__m512i __A, __m512i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_mask_test_epi16_mask (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_testn_epi8_mask (__m512i __A, __m512i __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_mask_testn_epi8_mask (__mmask64 __U, __m512i __A, __m512i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_testn_epi16_mask (__m512i __A, __m512i __B)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_mask_testn_epi16_mask (__mmask32 __U, __m512i __A, __m512i __B)
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_movepi8_mask (__m512i __A)
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_movepi16_mask (__m512i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_movm_epi8 (__mmask64 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_movm_epi16 (__mmask32 __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcastb_epi8 (__m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcastb_epi8 (__m512i __O, __mmask64 __M, __m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcastb_epi8 (__mmask64 __M, __m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_set1_epi16 (__m512i __O, __mmask32 __M, short __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_set1_epi16 (__mmask32 __M, short __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcastw_epi16 (__m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcastw_epi16 (__m512i __O, __mmask32 __M, __m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcastw_epi16 (__mmask32 __M, __m128i __A)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_permutexvar_epi16 (__m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_permutexvar_epi16 (__mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_permutexvar_epi16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B)
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sad_epu8 (__m512i __A, __m512i __B)
Macro Definition Documentation
__DEFAULT_FN_ATTRS
#define __DEFAULT_FN_ATTRS
Value:
  __attribute__((__always_inline__, __nodebug__,                               \
                 __target__("avx512bw,no-evex512")))
Definition at line 24 of file avx512bwintrin.h.
__DEFAULT_FN_ATTRS512
#define __DEFAULT_FN_ATTRS512
Value:
  __attribute__((__always_inline__, __nodebug__,                               \
                 __target__("avx512bw,evex512"), __min_vector_width__(512)))
Definition at line 21 of file avx512bwintrin.h.
_kshiftli_mask32
#define _kshiftli_mask32 (A, I) ((__mmask32)__builtin_ia32_kshiftlisi((__mmask32)(A), (unsigned int)(I)))
Definition at line 172 of file avx512bwintrin.h.
_kshiftli_mask64
#define _kshiftli_mask64 (A, I) ((__mmask64)__builtin_ia32_kshiftlidi((__mmask64)(A), (unsigned int)(I)))
Definition at line 178 of file avx512bwintrin.h.
_kshiftri_mask32
#define _kshiftri_mask32 (A, I) ((__mmask32)__builtin_ia32_kshiftrisi((__mmask32)(A), (unsigned int)(I)))
Definition at line 175 of file avx512bwintrin.h.
_kshiftri_mask64
#define _kshiftri_mask64 (A, I) ((__mmask64)__builtin_ia32_kshiftridi((__mmask64)(A), (unsigned int)(I)))
Definition at line 181 of file avx512bwintrin.h.
_mm512_alignr_epi8
#define _mm512_alignr_epi8 (A, B, N)
Value:
  ((__m512i)__builtin_ia32_palignr512((__v64qi)(__m512i)(A), \
                                      (__v64qi)(__m512i)(B), (int)(N)))
Definition at line 1976 of file avx512bwintrin.h.
_mm512_bslli_epi128
#define _mm512_bslli_epi128 (a, imm) ((__m512i)__builtin_ia32_pslldqi512_byteshift((__v8di)(__m512i)(a), (int)(imm)))
Definition at line 1520 of file avx512bwintrin.h.
_mm512_bsrli_epi128
#define _mm512_bsrli_epi128 (a, imm) ((__m512i)__builtin_ia32_psrldqi512_byteshift((__v8di)(__m512i)(a), (int)(imm)))
Definition at line 1657 of file avx512bwintrin.h.
_mm512_cmp_epi16_mask
#define _mm512_cmp_epi16_mask (a, b, p)
Value:
  ((__mmask32)__builtin_ia32_cmpw512_mask((__v32hi)(__m512i)(a), \
                                          (__v32hi)(__m512i)(b), (int)(p), \
                                          (__mmask32)-1))
Definition at line 245 of file avx512bwintrin.h.
_mm512_cmp_epi8_mask
#define _mm512_cmp_epi8_mask (a, b, p)
Value:
  ((__mmask64)__builtin_ia32_cmpb512_mask((__v64qi)(__m512i)(a), \
                                          (__v64qi)(__m512i)(b), (int)(p), \
                                          (__mmask64)-1))
Definition at line 225 of file avx512bwintrin.h.
_mm512_cmp_epu16_mask
#define _mm512_cmp_epu16_mask (a, b, p)
Value:
  ((__mmask32)__builtin_ia32_ucmpw512_mask((__v32hi)(__m512i)(a), \
                                           (__v32hi)(__m512i)(b), (int)(p), \
                                           (__mmask32)-1))
Definition at line 255 of file avx512bwintrin.h.
_mm512_cmp_epu8_mask
#define _mm512_cmp_epu8_mask (a, b, p)
Value:
  ((__mmask64)__builtin_ia32_ucmpb512_mask((__v64qi)(__m512i)(a), \
                                           (__v64qi)(__m512i)(b), (int)(p), \
                                           (__mmask64)-1))
Definition at line 235 of file avx512bwintrin.h.
_mm512_cmpeq_epi16_mask
#define _mm512_cmpeq_epi16_mask (A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 315 of file avx512bwintrin.h.
_mm512_cmpeq_epi8_mask
#define _mm512_cmpeq_epi8_mask (A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 265 of file avx512bwintrin.h.
_mm512_cmpeq_epu16_mask
#define _mm512_cmpeq_epu16_mask (A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 340 of file avx512bwintrin.h.
_mm512_cmpeq_epu8_mask
#define _mm512_cmpeq_epu8_mask (A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_EQ)
Definition at line 290 of file avx512bwintrin.h.
_mm512_cmpge_epi16_mask
#define _mm512_cmpge_epi16_mask (A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_GE)
Definition at line 319 of file avx512bwintrin.h.
_mm512_cmpge_epi8_mask
#define _mm512_cmpge_epi8_mask (A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_GE)
Definition at line 269 of file avx512bwintrin.h.
_mm512_cmpge_epu16_mask
#define _mm512_cmpge_epu16_mask (A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_GE)
Definition at line 344 of file avx512bwintrin.h.
_mm512_cmpge_epu8_mask
#define _mm512_cmpge_epu8_mask (A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_GE)
Definition at line 294 of file avx512bwintrin.h.
_mm512_cmpgt_epi16_mask
#define _mm512_cmpgt_epi16_mask (A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_GT)
Definition at line 323 of file avx512bwintrin.h.
_mm512_cmpgt_epi8_mask
#define _mm512_cmpgt_epi8_mask (A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_GT)
Definition at line 273 of file avx512bwintrin.h.
_mm512_cmpgt_epu16_mask
#define _mm512_cmpgt_epu16_mask (A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_GT)
Definition at line 348 of file avx512bwintrin.h.
_mm512_cmpgt_epu8_mask
#define _mm512_cmpgt_epu8_mask (A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_GT)
Definition at line 298 of file avx512bwintrin.h.
_mm512_cmple_epi16_mask
#define _mm512_cmple_epi16_mask (A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_LE)
Definition at line 327 of file avx512bwintrin.h.
_mm512_cmple_epi8_mask
#define _mm512_cmple_epi8_mask (A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_LE)
Definition at line 277 of file avx512bwintrin.h.
_mm512_cmple_epu16_mask
#define _mm512_cmple_epu16_mask (A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_LE)
Definition at line 352 of file avx512bwintrin.h.
_mm512_cmple_epu8_mask
#define _mm512_cmple_epu8_mask (A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_LE)
Definition at line 302 of file avx512bwintrin.h.
_mm512_cmplt_epi16_mask
#define _mm512_cmplt_epi16_mask (A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_LT)
Definition at line 331 of file avx512bwintrin.h.
_mm512_cmplt_epi8_mask
#define _mm512_cmplt_epi8_mask (A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_LT)
Definition at line 281 of file avx512bwintrin.h.
_mm512_cmplt_epu16_mask
#define _mm512_cmplt_epu16_mask (A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_LT)
Definition at line 356 of file avx512bwintrin.h.
_mm512_cmplt_epu8_mask
#define _mm512_cmplt_epu8_mask (A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_LT)
Definition at line 306 of file avx512bwintrin.h.
_mm512_cmpneq_epi16_mask
#define _mm512_cmpneq_epi16_mask (A, B) _mm512_cmp_epi16_mask((A), (B), _MM_CMPINT_NE)
Definition at line 335 of file avx512bwintrin.h.
_mm512_cmpneq_epi8_mask
#define _mm512_cmpneq_epi8_mask (A, B) _mm512_cmp_epi8_mask((A), (B), _MM_CMPINT_NE)
Definition at line 285 of file avx512bwintrin.h.
_mm512_cmpneq_epu16_mask
#define _mm512_cmpneq_epu16_mask (A, B) _mm512_cmp_epu16_mask((A), (B), _MM_CMPINT_NE)
Definition at line 360 of file avx512bwintrin.h.
_mm512_cmpneq_epu8_mask
#define _mm512_cmpneq_epu8_mask (A, B) _mm512_cmp_epu8_mask((A), (B), _MM_CMPINT_NE)
Definition at line 310 of file avx512bwintrin.h.
_mm512_dbsad_epu8
#define _mm512_dbsad_epu8 (A, B, imm)
Value:
  ((__m512i)__builtin_ia32_dbpsadbw512((__v64qi)(__m512i)(A), \
                                       (__v64qi)(__m512i)(B), (int)(imm)))
Definition at line 1990 of file avx512bwintrin.h.
_mm512_mask_alignr_epi8
#define _mm512_mask_alignr_epi8 (W, U, A, B, N)
Value:
  ((__m512i)__builtin_ia32_selectb_512((__mmask64)(U), \
                              (__v64qi)_mm512_alignr_epi8((A), (B), (int)(N)), \
                              (__v64qi)(__m512i)(W)))
Definition at line 1980 of file avx512bwintrin.h.
_mm512_mask_cmp_epi16_mask
#define _mm512_mask_cmp_epi16_mask (m, a, b, p)
Value:
  ((__mmask32)__builtin_ia32_cmpw512_mask((__v32hi)(__m512i)(a), \
                                          (__v32hi)(__m512i)(b), (int)(p), \
                                          (__mmask32)(m)))
Definition at line 250 of file avx512bwintrin.h.
_mm512_mask_cmp_epi8_mask
#define _mm512_mask_cmp_epi8_mask (m, a, b, p)
Value:
  ((__mmask64)__builtin_ia32_cmpb512_mask((__v64qi)(__m512i)(a), \
                                          (__v64qi)(__m512i)(b), (int)(p), \
                                          (__mmask64)(m)))
Definition at line 230 of file avx512bwintrin.h.
_mm512_mask_cmp_epu16_mask
#define _mm512_mask_cmp_epu16_mask (m, a, b, p)
Value:
  ((__mmask32)__builtin_ia32_ucmpw512_mask((__v32hi)(__m512i)(a), \
                                           (__v32hi)(__m512i)(b), (int)(p), \
                                           (__mmask32)(m)))
Definition at line 260 of file avx512bwintrin.h.
_mm512_mask_cmp_epu8_mask
#define _mm512_mask_cmp_epu8_mask (m, a, b, p)
Value:
  ((__mmask64)__builtin_ia32_ucmpb512_mask((__v64qi)(__m512i)(a), \
                                           (__v64qi)(__m512i)(b), (int)(p), \
                                           (__mmask64)(m)))
Definition at line 240 of file avx512bwintrin.h.
_mm512_mask_cmpeq_epi16_mask
#define _mm512_mask_cmpeq_epi16_mask (k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 317 of file avx512bwintrin.h.
_mm512_mask_cmpeq_epi8_mask
#define _mm512_mask_cmpeq_epi8_mask (k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 267 of file avx512bwintrin.h.
_mm512_mask_cmpeq_epu16_mask
#define _mm512_mask_cmpeq_epu16_mask (k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 342 of file avx512bwintrin.h.
_mm512_mask_cmpeq_epu8_mask
#define _mm512_mask_cmpeq_epu8_mask (k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_EQ)
Definition at line 292 of file avx512bwintrin.h.
_mm512_mask_cmpge_epi16_mask
#define _mm512_mask_cmpge_epi16_mask (k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 321 of file avx512bwintrin.h.
_mm512_mask_cmpge_epi8_mask
#define _mm512_mask_cmpge_epi8_mask (k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 271 of file avx512bwintrin.h.
_mm512_mask_cmpge_epu16_mask
#define _mm512_mask_cmpge_epu16_mask (k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 346 of file avx512bwintrin.h.
_mm512_mask_cmpge_epu8_mask
#define _mm512_mask_cmpge_epu8_mask (k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GE)
Definition at line 296 of file avx512bwintrin.h.
_mm512_mask_cmpgt_epi16_mask
#define _mm512_mask_cmpgt_epi16_mask (k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 325 of file avx512bwintrin.h.
_mm512_mask_cmpgt_epi8_mask
#define _mm512_mask_cmpgt_epi8_mask (k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 275 of file avx512bwintrin.h.
_mm512_mask_cmpgt_epu16_mask
#define _mm512_mask_cmpgt_epu16_mask (k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 350 of file avx512bwintrin.h.
_mm512_mask_cmpgt_epu8_mask
#define _mm512_mask_cmpgt_epu8_mask (k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_GT)
Definition at line 300 of file avx512bwintrin.h.
_mm512_mask_cmple_epi16_mask
#define _mm512_mask_cmple_epi16_mask (k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 329 of file avx512bwintrin.h.
_mm512_mask_cmple_epi8_mask
#define _mm512_mask_cmple_epi8_mask (k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 279 of file avx512bwintrin.h.
_mm512_mask_cmple_epu16_mask
#define _mm512_mask_cmple_epu16_mask (k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 354 of file avx512bwintrin.h.
_mm512_mask_cmple_epu8_mask
#define _mm512_mask_cmple_epu8_mask (k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LE)
Definition at line 304 of file avx512bwintrin.h.
_mm512_mask_cmplt_epi16_mask
#define _mm512_mask_cmplt_epi16_mask (k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 333 of file avx512bwintrin.h.
_mm512_mask_cmplt_epi8_mask
#define _mm512_mask_cmplt_epi8_mask (k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 283 of file avx512bwintrin.h.
_mm512_mask_cmplt_epu16_mask
#define _mm512_mask_cmplt_epu16_mask (k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 358 of file avx512bwintrin.h.
_mm512_mask_cmplt_epu8_mask
#define _mm512_mask_cmplt_epu8_mask (k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_LT)
Definition at line 308 of file avx512bwintrin.h.
_mm512_mask_cmpneq_epi16_mask
#define _mm512_mask_cmpneq_epi16_mask (k, A, B) _mm512_mask_cmp_epi16_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 337 of file avx512bwintrin.h.
_mm512_mask_cmpneq_epi8_mask
#define _mm512_mask_cmpneq_epi8_mask (k, A, B) _mm512_mask_cmp_epi8_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 287 of file avx512bwintrin.h.
_mm512_mask_cmpneq_epu16_mask
#define _mm512_mask_cmpneq_epu16_mask (k, A, B) _mm512_mask_cmp_epu16_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 362 of file avx512bwintrin.h.
_mm512_mask_cmpneq_epu8_mask
#define _mm512_mask_cmpneq_epu8_mask (k, A, B) _mm512_mask_cmp_epu8_mask((k), (A), (B), _MM_CMPINT_NE)
Definition at line 312 of file avx512bwintrin.h.
_mm512_mask_dbsad_epu8
#define _mm512_mask_dbsad_epu8 (W, U, A, B, imm)
Value:
  ((__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                  (__v32hi)_mm512_dbsad_epu8((A), (B), (imm)), \
                                  (__v32hi)(__m512i)(W)))
Definition at line 1994 of file avx512bwintrin.h.
_mm512_mask_shufflehi_epi16
#define _mm512_mask_shufflehi_epi16 (W, U, A, imm)
Value:
  ((__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                       (__v32hi)_mm512_shufflehi_epi16((A), \
                                                                       (imm)), \
                                       (__v32hi)(__m512i)(W)))
Definition at line 1424 of file avx512bwintrin.h.
_mm512_mask_shufflelo_epi16
#define _mm512_mask_shufflelo_epi16 (W, U, A, imm)
Value:
  ((__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                       (__v32hi)_mm512_shufflelo_epi16((A), \
                                                                       (imm)), \
                                       (__v32hi)(__m512i)(W)))
Definition at line 1440 of file avx512bwintrin.h.
_mm512_maskz_alignr_epi8
#define _mm512_maskz_alignr_epi8 (U, A, B, N)
Value:
  ((__m512i)__builtin_ia32_selectb_512((__mmask64)(U), \
                              (__v64qi)_mm512_alignr_epi8((A), (B), (int)(N)), \
                              (__v64qi)(__m512i)_mm512_setzero_si512()))
Definition at line 1985 of file avx512bwintrin.h.
_mm512_maskz_dbsad_epu8
#define _mm512_maskz_dbsad_epu8 (U, A, B, imm)
Value:
  ((__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                  (__v32hi)_mm512_dbsad_epu8((A), (B), (imm)), \
                                  (__v32hi)_mm512_setzero_si512()))
Definition at line 1999 of file avx512bwintrin.h.
_mm512_maskz_shufflehi_epi16
#define _mm512_maskz_shufflehi_epi16 (U, A, imm)
Value:
  ((__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                       (__v32hi)_mm512_shufflehi_epi16((A), \
                                                                       (imm)), \
                                       (__v32hi)_mm512_setzero_si512()))
Definition at line 1430 of file avx512bwintrin.h.
_mm512_maskz_shufflelo_epi16
#define _mm512_maskz_shufflelo_epi16 (U, A, imm)
Value:
  ((__m512i)__builtin_ia32_selectw_512((__mmask32)(U), \
                                       (__v32hi)_mm512_shufflelo_epi16((A), \
                                                                       (imm)), \
                                       (__v32hi)_mm512_setzero_si512()))
Definition at line 1447 of file avx512bwintrin.h.
_mm512_shufflehi_epi16
#define _mm512_shufflehi_epi16 (A, imm) ((__m512i)__builtin_ia32_pshufhw512((__v32hi)(__m512i)(A), (int)(imm)))
Definition at line 1421 of file avx512bwintrin.h.
_mm512_shufflelo_epi16
#define _mm512_shufflelo_epi16 (A, imm) ((__m512i)__builtin_ia32_pshuflw512((__v32hi)(__m512i)(A), (int)(imm)))
Definition at line 1436 of file avx512bwintrin.h.
Typedef Documentation
__mmask32
typedef unsigned int __mmask32
Definition at line 17 of file avx512bwintrin.h.
__mmask64
typedef unsigned long long __mmask64
Definition at line 18 of file avx512bwintrin.h.
Function Documentation
_cvtmask32_u32()
static __inline__ unsigned int __DEFAULT_FN_ATTRS _cvtmask32_u32 (__mmask32 __A) static
Definition at line 185 of file avx512bwintrin.h.
_cvtmask64_u64()
static __inline__ unsigned long long __DEFAULT_FN_ATTRS _cvtmask64_u64 (__mmask64 __A) static
Definition at line 190 of file avx512bwintrin.h.
_cvtu32_mask32()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _cvtu32_mask32 (unsigned int __A) static
Definition at line 195 of file avx512bwintrin.h.
_cvtu64_mask64()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _cvtu64_mask64 (unsigned long long __A) static
Definition at line 200 of file avx512bwintrin.h.
_kadd_mask32()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kadd_mask32 (__mmask32 __A, __mmask32 __B) static
Definition at line 162 of file avx512bwintrin.h.
_kadd_mask64()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kadd_mask64 (__mmask64 __A, __mmask64 __B) static
Definition at line 167 of file avx512bwintrin.h.
_kand_mask32()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kand_mask32 (__mmask32 __A, __mmask32 __B) static
Definition at line 39 of file avx512bwintrin.h.
_kand_mask64()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kand_mask64 (__mmask64 __A, __mmask64 __B) static
Definition at line 44 of file avx512bwintrin.h.
_kandn_mask32()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kandn_mask32 (__mmask32 __A, __mmask32 __B) static
Definition at line 50 of file avx512bwintrin.h.
_kandn_mask64()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kandn_mask64 (__mmask64 __A, __mmask64 __B) static
Definition at line 55 of file avx512bwintrin.h.
_knot_mask32()
static __inline __mmask32 __DEFAULT_FN_ATTRS _knot_mask32 (__mmask32 __M) static
Definition at line 29 of file avx512bwintrin.h.
_knot_mask64()
static __inline __mmask64 __DEFAULT_FN_ATTRS _knot_mask64 (__mmask64 __M) static
Definition at line 34 of file avx512bwintrin.h.
_kor_mask32()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kor_mask32 (__mmask32 __A, __mmask32 __B) static
Definition at line 61 of file avx512bwintrin.h.
_kor_mask64()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kor_mask64 (__mmask64 __A, __mmask64 __B) static
Definition at line 66 of file avx512bwintrin.h.
_kortest_mask32_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortest_mask32_u8 (__mmask32 __A, __mmask32 __B, unsigned char * __C) static
Definition at line 106 of file avx512bwintrin.h.
_kortest_mask64_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortest_mask64_u8 (__mmask64 __A, __mmask64 __B, unsigned char * __C) static
Definition at line 122 of file avx512bwintrin.h.
_kortestc_mask32_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestc_mask32_u8 (__mmask32 __A, __mmask32 __B) static
Definition at line 94 of file avx512bwintrin.h.
_kortestc_mask64_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestc_mask64_u8 (__mmask64 __A, __mmask64 __B) static
Definition at line 112 of file avx512bwintrin.h.
_kortestz_mask32_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestz_mask32_u8 (__mmask32 __A, __mmask32 __B) static
Definition at line 100 of file avx512bwintrin.h.
_kortestz_mask64_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _kortestz_mask64_u8 (__mmask64 __A, __mmask64 __B) static
Definition at line 117 of file avx512bwintrin.h.
_ktest_mask32_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktest_mask32_u8 (__mmask32 __A, __mmask32 __B, unsigned char * __C) static
Definition at line 140 of file avx512bwintrin.h.
_ktest_mask64_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktest_mask64_u8 (__mmask64 __A, __mmask64 __B, unsigned char * __C) static
Definition at line 156 of file avx512bwintrin.h.
_ktestc_mask32_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestc_mask32_u8 (__mmask32 __A, __mmask32 __B) static
Definition at line 128 of file avx512bwintrin.h.
_ktestc_mask64_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestc_mask64_u8 (__mmask64 __A, __mmask64 __B) static
Definition at line 146 of file avx512bwintrin.h.
_ktestz_mask32_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestz_mask32_u8 (__mmask32 __A, __mmask32 __B) static
Definition at line 134 of file avx512bwintrin.h.
_ktestz_mask64_u8()
static __inline__ unsigned char __DEFAULT_FN_ATTRS _ktestz_mask64_u8 (__mmask64 __A, __mmask64 __B) static
Definition at line 151 of file avx512bwintrin.h.
_kxnor_mask32()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kxnor_mask32 (__mmask32 __A, __mmask32 __B) static
Definition at line 72 of file avx512bwintrin.h.
_kxnor_mask64()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kxnor_mask64 (__mmask64 __A, __mmask64 __B) static
Definition at line 77 of file avx512bwintrin.h.
_kxor_mask32()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _kxor_mask32 (__mmask32 __A, __mmask32 __B) static
Definition at line 83 of file avx512bwintrin.h.
_kxor_mask64()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _kxor_mask64 (__mmask64 __A, __mmask64 __B) static
Definition at line 88 of file avx512bwintrin.h.
_load_mask32()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _load_mask32 (__mmask32 * __A) static
Definition at line 205 of file avx512bwintrin.h.
_load_mask64()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _load_mask64 (__mmask64 * __A) static
Definition at line 209 of file avx512bwintrin.h.
_mm512_abs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_abs_epi16 (__m512i __A) static
Definition at line 499 of file avx512bwintrin.h.
Referenced by _mm512_mask_abs_epi16(), and _mm512_maskz_abs_epi16().
_mm512_abs_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_abs_epi8 (__m512i __A) static
Definition at line 477 of file avx512bwintrin.h.
Referenced by _mm512_mask_abs_epi8(), and _mm512_maskz_abs_epi8().
_mm512_add_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_add_epi16 (__m512i __A, __m512i __B) static
Definition at line 404 of file avx512bwintrin.h.
Referenced by _mm512_mask_add_epi16(), and _mm512_maskz_add_epi16().
_mm512_add_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_add_epi8 (__m512i __A, __m512i __B) static
Definition at line 366 of file avx512bwintrin.h.
Referenced by _mm512_mask_add_epi8(), and _mm512_maskz_add_epi8().
_mm512_adds_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_adds_epi16 (__m512i __A, __m512i __B) static
Definition at line 631 of file avx512bwintrin.h.
Referenced by _mm512_mask_adds_epi16(), and _mm512_maskz_adds_epi16().
_mm512_adds_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_adds_epi8 (__m512i __A, __m512i __B) static
Definition at line 609 of file avx512bwintrin.h.
Referenced by _mm512_mask_adds_epi8(), and _mm512_maskz_adds_epi8().
_mm512_adds_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_adds_epu16 (__m512i __A, __m512i __B) static
Definition at line 675 of file avx512bwintrin.h.
Referenced by _mm512_mask_adds_epu16(), and _mm512_maskz_adds_epu16().
_mm512_adds_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_adds_epu8 (__m512i __A, __m512i __B) static
Definition at line 653 of file avx512bwintrin.h.
Referenced by _mm512_mask_adds_epu8(), and _mm512_maskz_adds_epu8().
_mm512_avg_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_avg_epu16 (__m512i __A, __m512i __B) static
Definition at line 720 of file avx512bwintrin.h.
Referenced by _mm512_mask_avg_epu16(), and _mm512_maskz_avg_epu16().
_mm512_avg_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_avg_epu8 (__m512i __A, __m512i __B) static
Definition at line 697 of file avx512bwintrin.h.
Referenced by _mm512_mask_avg_epu8(), and _mm512_maskz_avg_epu8().
_mm512_broadcastb_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcastb_epi8 (__m128i __A) static
Definition at line 1887 of file avx512bwintrin.h.
Referenced by _mm512_mask_broadcastb_epi8(), and _mm512_maskz_broadcastb_epi8().
_mm512_broadcastw_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_broadcastw_epi16 (__m128i __A) static
Definition at line 1929 of file avx512bwintrin.h.
Referenced by _mm512_mask_broadcastw_epi16(), and _mm512_maskz_broadcastw_epi16().
_mm512_cvtepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_cvtepi16_epi8 (__m512i __A) static
Definition at line 1212 of file avx512bwintrin.h.
References _mm256_undefined_si256().
_mm512_cvtepi8_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtepi8_epi16 (__m256i __A) static
Definition at line 1375 of file avx512bwintrin.h.
Referenced by _mm512_mask_cvtepi8_epi16(), and _mm512_maskz_cvtepi8_epi16().
_mm512_cvtepu8_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_cvtepu8_epi16 (__m256i __A) static
Definition at line 1399 of file avx512bwintrin.h.
Referenced by _mm512_mask_cvtepu8_epi16(), and _mm512_maskz_cvtepu8_epi16().
_mm512_cvtsepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_cvtsepi16_epi8 (__m512i __A) static
Definition at line 1170 of file avx512bwintrin.h.
References _mm256_setzero_si256().
_mm512_cvtusepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_cvtusepi16_epi8 (__m512i __A) static
Definition at line 1191 of file avx512bwintrin.h.
References _mm256_setzero_si256().
_mm512_kunpackd()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS _mm512_kunpackd (__mmask64 __A, __mmask64 __B) static
Definition at line 1708 of file avx512bwintrin.h.
_mm512_kunpackw()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS _mm512_kunpackw (__mmask32 __A, __mmask32 __B) static
Definition at line 1715 of file avx512bwintrin.h.
_mm512_loadu_epi16()
static __inline __m512i __DEFAULT_FN_ATTRS512 _mm512_loadu_epi16 (void const * __P) static
Definition at line 1722 of file avx512bwintrin.h.
References __P, and __v.
_mm512_loadu_epi8()
static __inline __m512i __DEFAULT_FN_ATTRS512 _mm512_loadu_epi8 (void const * __P) static
Definition at line 1748 of file avx512bwintrin.h.
References __P, and __v.
_mm512_madd_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_madd_epi16 (__m512i __A, __m512i __B) static
Definition at line 1151 of file avx512bwintrin.h.
Referenced by _mm512_mask_madd_epi16(), and _mm512_maskz_madd_epi16().
_mm512_maddubs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maddubs_epi16 (__m512i __X, __m512i __Y) static
Definition at line 1131 of file avx512bwintrin.h.
References __Y.
Referenced by _mm512_mask_maddubs_epi16(), and _mm512_maskz_maddubs_epi16().
_mm512_mask2_permutex2var_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask2_permutex2var_epi16 (__m512i __A, __m512i __I, __mmask32 __U, __m512i __B) static
Definition at line 1046 of file avx512bwintrin.h.
References _mm512_permutex2var_epi16().
_mm512_mask_abs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_abs_epi16 (__m512i __W, __mmask32 __U, __m512i __A) static
Definition at line 505 of file avx512bwintrin.h.
References _mm512_abs_epi16().
_mm512_mask_abs_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_abs_epi8 (__m512i __W, __mmask64 __U, __m512i __A) static
Definition at line 483 of file avx512bwintrin.h.
References _mm512_abs_epi8().
_mm512_mask_add_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_add_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 409 of file avx512bwintrin.h.
References _mm512_add_epi16().
_mm512_mask_add_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_add_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 371 of file avx512bwintrin.h.
References _mm512_add_epi8().
_mm512_mask_adds_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_adds_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 637 of file avx512bwintrin.h.
References _mm512_adds_epi16().
_mm512_mask_adds_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_adds_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 615 of file avx512bwintrin.h.
References _mm512_adds_epi8().
_mm512_mask_adds_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_adds_epu16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 681 of file avx512bwintrin.h.
References _mm512_adds_epu16().
_mm512_mask_adds_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_adds_epu8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 659 of file avx512bwintrin.h.
References _mm512_adds_epu8().
_mm512_mask_avg_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_avg_epu16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 726 of file avx512bwintrin.h.
References _mm512_avg_epu16().
_mm512_mask_avg_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_avg_epu8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 703 of file avx512bwintrin.h.
References _mm512_avg_epu8().
_mm512_mask_blend_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_blend_epi16 (__mmask32 __U, __m512i __A, __m512i __W) static
Definition at line 469 of file avx512bwintrin.h.
_mm512_mask_blend_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_blend_epi8 (__mmask64 __U, __m512i __A, __m512i __W) static
Definition at line 461 of file avx512bwintrin.h.
_mm512_mask_broadcastb_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcastb_epi8 (__m512i __O, __mmask64 __M, __m128i __A) static
Definition at line 1897 of file avx512bwintrin.h.
References _mm512_broadcastb_epi8().
_mm512_mask_broadcastw_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_broadcastw_epi16 (__m512i __O, __mmask32 __M, __m128i __A) static
Definition at line 1937 of file avx512bwintrin.h.
References _mm512_broadcastw_epi16().
_mm512_mask_cvtepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi16_epi8 (__m256i __O, __mmask32 __M, __m512i __A) static
Definition at line 1219 of file avx512bwintrin.h.
_mm512_mask_cvtepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi16_storeu_epi8 (void * __P, __mmask32 __M, __m512i __A) static
Definition at line 1233 of file avx512bwintrin.h.
References __P.
_mm512_mask_cvtepi8_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepi8_epi16 (__m512i __W, __mmask32 __U, __m256i __A) static
Definition at line 1383 of file avx512bwintrin.h.
References _mm512_cvtepi8_epi16().
_mm512_mask_cvtepu8_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtepu8_epi16 (__m512i __W, __mmask32 __U, __m256i __A) static
Definition at line 1405 of file avx512bwintrin.h.
References _mm512_cvtepu8_epi16().
_mm512_mask_cvtsepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtsepi16_epi8 (__m256i __O, __mmask32 __M, __m512i __A) static
Definition at line 1177 of file avx512bwintrin.h.
_mm512_mask_cvtsepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_cvtsepi16_storeu_epi8 (void * __P, __mmask32 __M, __m512i __A) static
Definition at line 1239 of file avx512bwintrin.h.
References __P.
_mm512_mask_cvtusepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_mask_cvtusepi16_epi8 (__m256i __O, __mmask32 __M, __m512i __A) static
Definition at line 1198 of file avx512bwintrin.h.
_mm512_mask_cvtusepi16_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_cvtusepi16_storeu_epi8 (void * __P, __mmask32 __M, __m512i __A) static
Definition at line 1245 of file avx512bwintrin.h.
References __P.
_mm512_mask_loadu_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_loadu_epi16 (__m512i __W, __mmask32 __U, void const * __P) static
Definition at line 1731 of file avx512bwintrin.h.
References __P.
_mm512_mask_loadu_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_loadu_epi8 (__m512i __W, __mmask64 __U, void const * __P) static
Definition at line 1757 of file avx512bwintrin.h.
References __P.
_mm512_mask_madd_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_madd_epi16 (__m512i __W, __mmask16 __U, __m512i __A, __m512i __B) static
Definition at line 1156 of file avx512bwintrin.h.
References _mm512_madd_epi16().
_mm512_mask_maddubs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_maddubs_epi16 (__m512i __W, __mmask32 __U, __m512i __X, __m512i __Y) static
Definition at line 1136 of file avx512bwintrin.h.
References __Y, and _mm512_maddubs_epi16().
_mm512_mask_max_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_max_epi16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 779 of file avx512bwintrin.h.
References _mm512_max_epi16().
_mm512_mask_max_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_max_epi8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 757 of file avx512bwintrin.h.
References _mm512_max_epi8().
_mm512_mask_max_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_max_epu16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 824 of file avx512bwintrin.h.
References _mm512_max_epu16().
_mm512_mask_max_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_max_epu8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 802 of file avx512bwintrin.h.
References _mm512_max_epu8().
_mm512_mask_min_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_min_epi16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 868 of file avx512bwintrin.h.
References _mm512_min_epi16().
_mm512_mask_min_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_min_epi8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 846 of file avx512bwintrin.h.
References _mm512_min_epi8().
_mm512_mask_min_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_min_epu16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 912 of file avx512bwintrin.h.
References _mm512_min_epu16().
_mm512_mask_min_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_min_epu8 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 890 of file avx512bwintrin.h.
References _mm512_min_epu8().
_mm512_mask_mov_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mov_epi16 (__m512i __W, __mmask32 __U, __m512i __A) static
Definition at line 1661 of file avx512bwintrin.h.
_mm512_mask_mov_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mov_epi8 (__m512i __W, __mmask64 __U, __m512i __A) static
Definition at line 1677 of file avx512bwintrin.h.
_mm512_mask_mulhi_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mulhi_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1092 of file avx512bwintrin.h.
References _mm512_mulhi_epi16().
_mm512_mask_mulhi_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mulhi_epu16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1115 of file avx512bwintrin.h.
References _mm512_mulhi_epu16().
_mm512_mask_mulhrs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mulhrs_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1070 of file avx512bwintrin.h.
References _mm512_mulhrs_epi16().
_mm512_mask_mullo_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_mullo_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 447 of file avx512bwintrin.h.
References _mm512_mullo_epi16().
_mm512_mask_packs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_packs_epi16 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 549 of file avx512bwintrin.h.
References _mm512_packs_epi16().
_mm512_mask_packs_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_packs_epi32 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 535 of file avx512bwintrin.h.
References _mm512_packs_epi32().
_mm512_mask_packus_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_packus_epi16 (__m512i __W, __mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 593 of file avx512bwintrin.h.
References _mm512_packus_epi16().
_mm512_mask_packus_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_packus_epi32 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 579 of file avx512bwintrin.h.
References _mm512_packus_epi32().
_mm512_mask_permutex2var_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_permutex2var_epi16 (__m512i __A, __mmask32 __U, __m512i __I, __m512i __B) static
Definition at line 1037 of file avx512bwintrin.h.
References _mm512_permutex2var_epi16().
_mm512_mask_permutexvar_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_permutexvar_epi16 (__m512i __W, __mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 1968 of file avx512bwintrin.h.
References _mm512_permutexvar_epi16().
_mm512_mask_set1_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_set1_epi16 (__m512i __O, __mmask32 __M, short __A) static
Definition at line 1913 of file avx512bwintrin.h.
References _mm512_set1_epi16().
_mm512_mask_set1_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_set1_epi8 (__m512i __O, __mmask64 __M, char __A) static
Definition at line 1693 of file avx512bwintrin.h.
References _mm512_set1_epi8().
_mm512_mask_shuffle_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_shuffle_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 926 of file avx512bwintrin.h.
References _mm512_shuffle_epi8().
_mm512_mask_sll_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sll_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m128i __B) static
Definition at line 1482 of file avx512bwintrin.h.
References _mm512_sll_epi16().
_mm512_mask_slli_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_slli_epi16 (__m512i __W, __mmask32 __U, __m512i __A, unsigned int __B) static
Definition at line 1504 of file avx512bwintrin.h.
References _mm512_slli_epi16().
_mm512_mask_sllv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sllv_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1460 of file avx512bwintrin.h.
References _mm512_sllv_epi16().
_mm512_mask_sra_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sra_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m128i __B) static
Definition at line 1574 of file avx512bwintrin.h.
References _mm512_sra_epi16().
_mm512_mask_srai_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srai_epi16 (__m512i __W, __mmask32 __U, __m512i __A, unsigned int __B) static
Definition at line 1596 of file avx512bwintrin.h.
References _mm512_srai_epi16().
_mm512_mask_srav_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srav_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1552 of file avx512bwintrin.h.
References _mm512_srav_epi16().
_mm512_mask_srl_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srl_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m128i __B) static
Definition at line 1619 of file avx512bwintrin.h.
References _mm512_srl_epi16().
_mm512_mask_srli_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srli_epi16 (__m512i __W, __mmask32 __U, __m512i __A, unsigned int __B) static
Definition at line 1641 of file avx512bwintrin.h.
References _mm512_srli_epi16().
_mm512_mask_srlv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_srlv_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1530 of file avx512bwintrin.h.
References _mm512_srlv_epi16().
_mm512_mask_storeu_epi16()
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_storeu_epi16 (void * __P, __mmask32 __U, __m512i __A) static
Definition at line 1783 of file avx512bwintrin.h.
References __P.
_mm512_mask_storeu_epi8()
static __inline__ void __DEFAULT_FN_ATTRS512 _mm512_mask_storeu_epi8 (void * __P, __mmask64 __U, __m512i __A) static
Definition at line 1800 of file avx512bwintrin.h.
References __P.
_mm512_mask_sub_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sub_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 428 of file avx512bwintrin.h.
References _mm512_sub_epi16().
_mm512_mask_sub_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_sub_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 390 of file avx512bwintrin.h.
References _mm512_sub_epi8().
_mm512_mask_subs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_subs_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 970 of file avx512bwintrin.h.
References _mm512_subs_epi16().
_mm512_mask_subs_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_subs_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 948 of file avx512bwintrin.h.
References _mm512_subs_epi8().
_mm512_mask_subs_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_subs_epu16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1014 of file avx512bwintrin.h.
References _mm512_subs_epu16().
_mm512_mask_subs_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_subs_epu8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 992 of file avx512bwintrin.h.
References _mm512_subs_epu8().
_mm512_mask_test_epi16_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_mask_test_epi16_mask (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1829 of file avx512bwintrin.h.
References _mm512_and_epi32(), _mm512_mask_cmpneq_epi16_mask, and _mm512_setzero_si512().
_mm512_mask_test_epi8_mask()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_mask_test_epi8_mask (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 1815 of file avx512bwintrin.h.
References _mm512_and_epi32(), _mm512_mask_cmpneq_epi8_mask, and _mm512_setzero_si512().
_mm512_mask_testn_epi16_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_mask_testn_epi16_mask (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1856 of file avx512bwintrin.h.
References _mm512_and_epi32(), _mm512_mask_cmpeq_epi16_mask, and _mm512_setzero_si512().
_mm512_mask_testn_epi8_mask()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_mask_testn_epi8_mask (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 1842 of file avx512bwintrin.h.
References _mm512_and_epi32(), _mm512_mask_cmpeq_epi8_mask, and _mm512_setzero_si512().
_mm512_mask_unpackhi_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_unpackhi_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1299 of file avx512bwintrin.h.
References _mm512_unpackhi_epi16().
_mm512_mask_unpackhi_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_unpackhi_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 1272 of file avx512bwintrin.h.
References _mm512_unpackhi_epi8().
_mm512_mask_unpacklo_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_unpacklo_epi16 (__m512i __W, __mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1361 of file avx512bwintrin.h.
References _mm512_unpacklo_epi16().
_mm512_mask_unpacklo_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mask_unpacklo_epi8 (__m512i __W, __mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 1334 of file avx512bwintrin.h.
References _mm512_unpacklo_epi8().
_mm512_maskz_abs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_abs_epi16 (__mmask32 __U, __m512i __A) static
Definition at line 513 of file avx512bwintrin.h.
References _mm512_abs_epi16(), and _mm512_setzero_si512().
_mm512_maskz_abs_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_abs_epi8 (__mmask64 __U, __m512i __A) static
Definition at line 491 of file avx512bwintrin.h.
References _mm512_abs_epi8(), and _mm512_setzero_si512().
_mm512_maskz_add_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_add_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 416 of file avx512bwintrin.h.
References _mm512_add_epi16(), and _mm512_setzero_si512().
_mm512_maskz_add_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_add_epi8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 378 of file avx512bwintrin.h.
References _mm512_add_epi8(), and _mm512_setzero_si512().
_mm512_maskz_adds_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_adds_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 645 of file avx512bwintrin.h.
References _mm512_adds_epi16(), and _mm512_setzero_si512().
_mm512_maskz_adds_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_adds_epi8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 623 of file avx512bwintrin.h.
References _mm512_adds_epi8(), and _mm512_setzero_si512().
_mm512_maskz_adds_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_adds_epu16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 689 of file avx512bwintrin.h.
References _mm512_adds_epu16(), and _mm512_setzero_si512().
_mm512_maskz_adds_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_adds_epu8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 667 of file avx512bwintrin.h.
References _mm512_adds_epu8(), and _mm512_setzero_si512().
_mm512_maskz_avg_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_avg_epu16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 735 of file avx512bwintrin.h.
References _mm512_avg_epu16(), and _mm512_setzero_si512().
_mm512_maskz_avg_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_avg_epu8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 712 of file avx512bwintrin.h.
References _mm512_avg_epu8(), and _mm512_setzero_si512().
_mm512_maskz_broadcastb_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcastb_epi8 (__mmask64 __M, __m128i __A) static
Definition at line 1905 of file avx512bwintrin.h.
References _mm512_broadcastb_epi8(), and _mm512_setzero_si512().
_mm512_maskz_broadcastw_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_broadcastw_epi16 (__mmask32 __M, __m128i __A) static
Definition at line 1945 of file avx512bwintrin.h.
References _mm512_broadcastw_epi16(), and _mm512_setzero_si512().
_mm512_maskz_cvtepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi16_epi8 (__mmask32 __M, __m512i __A) static
Definition at line 1226 of file avx512bwintrin.h.
References _mm256_setzero_si256().
_mm512_maskz_cvtepi8_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepi8_epi16 (__mmask32 __U, __m256i __A) static
Definition at line 1391 of file avx512bwintrin.h.
References _mm512_cvtepi8_epi16(), and _mm512_setzero_si512().
_mm512_maskz_cvtepu8_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtepu8_epi16 (__mmask32 __U, __m256i __A) static
Definition at line 1413 of file avx512bwintrin.h.
References _mm512_cvtepu8_epi16(), and _mm512_setzero_si512().
_mm512_maskz_cvtsepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtsepi16_epi8 (__mmask32 __M, __m512i __A) static
Definition at line 1184 of file avx512bwintrin.h.
References _mm256_setzero_si256().
_mm512_maskz_cvtusepi16_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS512 _mm512_maskz_cvtusepi16_epi8 (__mmask32 __M, __m512i __A) static
Definition at line 1205 of file avx512bwintrin.h.
References _mm256_setzero_si256().
_mm512_maskz_loadu_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_loadu_epi16 (__mmask32 __U, void const * __P) static
Definition at line 1739 of file avx512bwintrin.h.
References __P, and _mm512_setzero_si512().
_mm512_maskz_loadu_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_loadu_epi8 (__mmask64 __U, void const * __P) static
Definition at line 1765 of file avx512bwintrin.h.
References __P, and _mm512_setzero_si512().
_mm512_maskz_madd_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_madd_epi16 (__mmask16 __U, __m512i __A, __m512i __B) static
Definition at line 1163 of file avx512bwintrin.h.
References _mm512_madd_epi16(), and _mm512_setzero_si512().
_mm512_maskz_maddubs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_maddubs_epi16 (__mmask32 __U, __m512i __X, __m512i __Y) static
Definition at line 1144 of file avx512bwintrin.h.
References __Y, _mm512_maddubs_epi16(), and _mm512_setzero_si512().
_mm512_maskz_max_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_max_epi16 (__mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 771 of file avx512bwintrin.h.
References _mm512_max_epi16(), and _mm512_setzero_si512().
_mm512_maskz_max_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_max_epi8 (__mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 749 of file avx512bwintrin.h.
References _mm512_max_epi8(), and _mm512_setzero_si512().
_mm512_maskz_max_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_max_epu16 (__mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 816 of file avx512bwintrin.h.
References _mm512_max_epu16(), and _mm512_setzero_si512().
_mm512_maskz_max_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_max_epu8 (__mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 794 of file avx512bwintrin.h.
References _mm512_max_epu8(), and _mm512_setzero_si512().
_mm512_maskz_min_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_min_epi16 (__mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 860 of file avx512bwintrin.h.
References _mm512_min_epi16(), and _mm512_setzero_si512().
_mm512_maskz_min_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_min_epi8 (__mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 838 of file avx512bwintrin.h.
References _mm512_min_epi8(), and _mm512_setzero_si512().
_mm512_maskz_min_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_min_epu16 (__mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 904 of file avx512bwintrin.h.
References _mm512_min_epu16(), and _mm512_setzero_si512().
_mm512_maskz_min_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_min_epu8 (__mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 882 of file avx512bwintrin.h.
References _mm512_min_epu8(), and _mm512_setzero_si512().
_mm512_maskz_mov_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mov_epi16 (__mmask32 __U, __m512i __A) static
Definition at line 1669 of file avx512bwintrin.h.
References _mm512_setzero_si512().
_mm512_maskz_mov_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mov_epi8 (__mmask64 __U, __m512i __A) static
Definition at line 1685 of file avx512bwintrin.h.
References _mm512_setzero_si512().
_mm512_maskz_mulhi_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mulhi_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1101 of file avx512bwintrin.h.
References _mm512_mulhi_epi16(), and _mm512_setzero_si512().
_mm512_maskz_mulhi_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mulhi_epu16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1123 of file avx512bwintrin.h.
References _mm512_mulhi_epu16(), and _mm512_setzero_si512().
_mm512_maskz_mulhrs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mulhrs_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1078 of file avx512bwintrin.h.
References _mm512_mulhrs_epi16(), and _mm512_setzero_si512().
_mm512_maskz_mullo_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_mullo_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 454 of file avx512bwintrin.h.
References _mm512_mullo_epi16(), and _mm512_setzero_si512().
_mm512_maskz_packs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_packs_epi16 (__mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 557 of file avx512bwintrin.h.
References _mm512_packs_epi16(), and _mm512_setzero_si512().
_mm512_maskz_packs_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_packs_epi32 (__mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 527 of file avx512bwintrin.h.
References _mm512_packs_epi32(), and _mm512_setzero_si512().
_mm512_maskz_packus_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_packus_epi16 (__mmask64 __M, __m512i __A, __m512i __B) static
Definition at line 601 of file avx512bwintrin.h.
References _mm512_packus_epi16(), and _mm512_setzero_si512().
_mm512_maskz_packus_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_packus_epi32 (__mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 571 of file avx512bwintrin.h.
References _mm512_packus_epi32(), and _mm512_setzero_si512().
_mm512_maskz_permutex2var_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_permutex2var_epi16 (__mmask32 __U, __m512i __A, __m512i __I, __m512i __B) static
Definition at line 1055 of file avx512bwintrin.h.
References _mm512_permutex2var_epi16(), and _mm512_setzero_si512().
_mm512_maskz_permutexvar_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_permutexvar_epi16 (__mmask32 __M, __m512i __A, __m512i __B) static
Definition at line 1959 of file avx512bwintrin.h.
References _mm512_permutexvar_epi16(), and _mm512_setzero_si512().
_mm512_maskz_set1_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_set1_epi16 (__mmask32 __M, short __A) static
Definition at line 1921 of file avx512bwintrin.h.
References _mm512_set1_epi16(), and _mm512_setzero_si512().
_mm512_maskz_set1_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_set1_epi8 (__mmask64 __M, char __A) static
Definition at line 1701 of file avx512bwintrin.h.
References _mm512_set1_epi8(), and _mm512_setzero_si512().
_mm512_maskz_shuffle_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_shuffle_epi8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 934 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_shuffle_epi8().
_mm512_maskz_sll_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sll_epi16 (__mmask32 __U, __m512i __A, __m128i __B) static
Definition at line 1490 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_sll_epi16().
_mm512_maskz_slli_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_slli_epi16 (__mmask32 __U, __m512i __A, unsigned int __B) static
Definition at line 1513 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_slli_epi16().
_mm512_maskz_sllv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sllv_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1468 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_sllv_epi16().
_mm512_maskz_sra_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sra_epi16 (__mmask32 __U, __m512i __A, __m128i __B) static
Definition at line 1582 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_sra_epi16().
_mm512_maskz_srai_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srai_epi16 (__mmask32 __U, __m512i __A, unsigned int __B) static
Definition at line 1605 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_srai_epi16().
_mm512_maskz_srav_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srav_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1560 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_srav_epi16().
_mm512_maskz_srl_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srl_epi16 (__mmask32 __U, __m512i __A, __m128i __B) static
Definition at line 1627 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_srl_epi16().
_mm512_maskz_srli_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srli_epi16 (__mmask32 __U, __m512i __A, int __B) static
Definition at line 1650 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_srli_epi16().
_mm512_maskz_srlv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_srlv_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1538 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_srlv_epi16().
_mm512_maskz_sub_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sub_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 435 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_sub_epi16().
_mm512_maskz_sub_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_sub_epi8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 397 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_sub_epi8().
_mm512_maskz_subs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_subs_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 978 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_subs_epi16().
_mm512_maskz_subs_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_subs_epi8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 956 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_subs_epi8().
_mm512_maskz_subs_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_subs_epu16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1022 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_subs_epu16().
_mm512_maskz_subs_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_subs_epu8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 1000 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_subs_epu8().
_mm512_maskz_unpackhi_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_unpackhi_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1306 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_unpackhi_epi16().
_mm512_maskz_unpackhi_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_unpackhi_epi8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 1279 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_unpackhi_epi8().
_mm512_maskz_unpacklo_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_unpacklo_epi16 (__mmask32 __U, __m512i __A, __m512i __B) static
Definition at line 1368 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_unpacklo_epi16().
_mm512_maskz_unpacklo_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_maskz_unpacklo_epi8 (__mmask64 __U, __m512i __A, __m512i __B) static
Definition at line 1341 of file avx512bwintrin.h.
References _mm512_setzero_si512(), and _mm512_unpacklo_epi8().
_mm512_max_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_max_epi16 (__m512i __A, __m512i __B) static
Definition at line 765 of file avx512bwintrin.h.
Referenced by _mm512_mask_max_epi16(), and _mm512_maskz_max_epi16().
_mm512_max_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_max_epi8 (__m512i __A, __m512i __B) static
Definition at line 743 of file avx512bwintrin.h.
Referenced by _mm512_mask_max_epi8(), and _mm512_maskz_max_epi8().
_mm512_max_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_max_epu16 (__m512i __A, __m512i __B) static
Definition at line 810 of file avx512bwintrin.h.
Referenced by _mm512_mask_max_epu16(), and _mm512_maskz_max_epu16().
_mm512_max_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_max_epu8 (__m512i __A, __m512i __B) static
Definition at line 788 of file avx512bwintrin.h.
Referenced by _mm512_mask_max_epu8(), and _mm512_maskz_max_epu8().
_mm512_min_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_min_epi16 (__m512i __A, __m512i __B) static
Definition at line 854 of file avx512bwintrin.h.
Referenced by _mm512_mask_min_epi16(), and _mm512_maskz_min_epi16().
_mm512_min_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_min_epi8 (__m512i __A, __m512i __B) static
Definition at line 832 of file avx512bwintrin.h.
Referenced by _mm512_mask_min_epi8(), and _mm512_maskz_min_epi8().
_mm512_min_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_min_epu16 (__m512i __A, __m512i __B) static
Definition at line 898 of file avx512bwintrin.h.
Referenced by _mm512_mask_min_epu16(), and _mm512_maskz_min_epu16().
_mm512_min_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_min_epu8 (__m512i __A, __m512i __B) static
Definition at line 876 of file avx512bwintrin.h.
Referenced by _mm512_mask_min_epu8(), and _mm512_maskz_min_epu8().
_mm512_movepi16_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_movepi16_mask (__m512i __A) static
Definition at line 1869 of file avx512bwintrin.h.
_mm512_movepi8_mask()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_movepi8_mask (__m512i __A) static
Definition at line 1863 of file avx512bwintrin.h.
_mm512_movm_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_movm_epi16 (__mmask32 __A) static
Definition at line 1881 of file avx512bwintrin.h.
_mm512_movm_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_movm_epi8 (__mmask64 __A) static
Definition at line 1875 of file avx512bwintrin.h.
_mm512_mulhi_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mulhi_epi16 (__m512i __A, __m512i __B) static
Definition at line 1086 of file avx512bwintrin.h.
Referenced by _mm512_mask_mulhi_epi16(), and _mm512_maskz_mulhi_epi16().
_mm512_mulhi_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mulhi_epu16 (__m512i __A, __m512i __B) static
Definition at line 1109 of file avx512bwintrin.h.
Referenced by _mm512_mask_mulhi_epu16(), and _mm512_maskz_mulhi_epu16().
_mm512_mulhrs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mulhrs_epi16 (__m512i __A, __m512i __B) static
Definition at line 1064 of file avx512bwintrin.h.
Referenced by _mm512_mask_mulhrs_epi16(), and _mm512_maskz_mulhrs_epi16().
_mm512_mullo_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_mullo_epi16 (__m512i __A, __m512i __B) static
Definition at line 442 of file avx512bwintrin.h.
Referenced by _mm512_mask_mullo_epi16(), and _mm512_maskz_mullo_epi16().
_mm512_packs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_packs_epi16 (__m512i __A, __m512i __B) static
Definition at line 543 of file avx512bwintrin.h.
Referenced by _mm512_mask_packs_epi16(), and _mm512_maskz_packs_epi16().
_mm512_packs_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_packs_epi32 (__m512i __A, __m512i __B) static
Definition at line 521 of file avx512bwintrin.h.
Referenced by _mm512_mask_packs_epi32(), and _mm512_maskz_packs_epi32().
_mm512_packus_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_packus_epi16 (__m512i __A, __m512i __B) static
Definition at line 587 of file avx512bwintrin.h.
Referenced by _mm512_mask_packus_epi16(), and _mm512_maskz_packus_epi16().
_mm512_packus_epi32()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_packus_epi32 (__m512i __A, __m512i __B) static
Definition at line 565 of file avx512bwintrin.h.
Referenced by _mm512_mask_packus_epi32(), and _mm512_maskz_packus_epi32().
_mm512_permutex2var_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_permutex2var_epi16 (__m512i __A, __m512i __I, __m512i __B) static
Definition at line 1030 of file avx512bwintrin.h.
Referenced by _mm512_mask2_permutex2var_epi16(), _mm512_mask_permutex2var_epi16(), and _mm512_maskz_permutex2var_epi16().
_mm512_permutexvar_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_permutexvar_epi16 (__m512i __A, __m512i __B) static
Definition at line 1953 of file avx512bwintrin.h.
Referenced by _mm512_mask_permutexvar_epi16(), and _mm512_maskz_permutexvar_epi16().
_mm512_sad_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sad_epu8 (__m512i __A, __m512i __B) static
Definition at line 2005 of file avx512bwintrin.h.
_mm512_shuffle_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_shuffle_epi8 (__m512i __A, __m512i __B) static
Definition at line 920 of file avx512bwintrin.h.
Referenced by _mm512_mask_shuffle_epi8(), and _mm512_maskz_shuffle_epi8().
_mm512_sll_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sll_epi16 (__m512i __A, __m128i __B) static
Definition at line 1476 of file avx512bwintrin.h.
Referenced by _mm512_mask_sll_epi16(), and _mm512_maskz_sll_epi16().
_mm512_slli_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_slli_epi16 (__m512i __A, unsigned int __B) static
Definition at line 1498 of file avx512bwintrin.h.
Referenced by _mm512_mask_slli_epi16(), and _mm512_maskz_slli_epi16().
_mm512_sllv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sllv_epi16 (__m512i __A, __m512i __B) static
Definition at line 1454 of file avx512bwintrin.h.
Referenced by _mm512_mask_sllv_epi16(), and _mm512_maskz_sllv_epi16().
_mm512_sra_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sra_epi16 (__m512i __A, __m128i __B) static
Definition at line 1568 of file avx512bwintrin.h.
Referenced by _mm512_mask_sra_epi16(), and _mm512_maskz_sra_epi16().
_mm512_srai_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srai_epi16 (__m512i __A, unsigned int __B) static
Definition at line 1590 of file avx512bwintrin.h.
Referenced by _mm512_mask_srai_epi16(), and _mm512_maskz_srai_epi16().
_mm512_srav_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srav_epi16 (__m512i __A, __m512i __B) static
Definition at line 1546 of file avx512bwintrin.h.
Referenced by _mm512_mask_srav_epi16(), and _mm512_maskz_srav_epi16().
_mm512_srl_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srl_epi16 (__m512i __A, __m128i __B) static
Definition at line 1613 of file avx512bwintrin.h.
Referenced by _mm512_mask_srl_epi16(), and _mm512_maskz_srl_epi16().
_mm512_srli_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srli_epi16 (__m512i __A, unsigned int __B) static
Definition at line 1635 of file avx512bwintrin.h.
Referenced by _mm512_mask_srli_epi16(), and _mm512_maskz_srli_epi16().
_mm512_srlv_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_srlv_epi16 (__m512i __A, __m512i __B) static
Definition at line 1524 of file avx512bwintrin.h.
Referenced by _mm512_mask_srlv_epi16(), and _mm512_maskz_srlv_epi16().
_mm512_storeu_epi16()
static __inline void __DEFAULT_FN_ATTRS512 _mm512_storeu_epi16 (void * __P, __m512i __A) static
Definition at line 1774 of file avx512bwintrin.h.
References __P, and __v.
_mm512_storeu_epi8()
static __inline void __DEFAULT_FN_ATTRS512 _mm512_storeu_epi8 (void * __P, __m512i __A) static
Definition at line 1791 of file avx512bwintrin.h.
References __P, and __v.
_mm512_sub_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sub_epi16 (__m512i __A, __m512i __B) static
Definition at line 423 of file avx512bwintrin.h.
Referenced by _mm512_mask_sub_epi16(), and _mm512_maskz_sub_epi16().
_mm512_sub_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_sub_epi8 (__m512i __A, __m512i __B) static
Definition at line 385 of file avx512bwintrin.h.
Referenced by _mm512_mask_sub_epi8(), and _mm512_maskz_sub_epi8().
_mm512_subs_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_subs_epi16 (__m512i __A, __m512i __B) static
Definition at line 964 of file avx512bwintrin.h.
Referenced by _mm512_mask_subs_epi16(), and _mm512_maskz_subs_epi16().
_mm512_subs_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_subs_epi8 (__m512i __A, __m512i __B) static
Definition at line 942 of file avx512bwintrin.h.
Referenced by _mm512_mask_subs_epi8(), and _mm512_maskz_subs_epi8().
_mm512_subs_epu16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_subs_epu16 (__m512i __A, __m512i __B) static
Definition at line 1008 of file avx512bwintrin.h.
Referenced by _mm512_mask_subs_epu16(), and _mm512_maskz_subs_epu16().
_mm512_subs_epu8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_subs_epu8 (__m512i __A, __m512i __B) static
Definition at line 986 of file avx512bwintrin.h.
Referenced by _mm512_mask_subs_epu8(), and _mm512_maskz_subs_epu8().
_mm512_test_epi16_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_test_epi16_mask (__m512i __A, __m512i __B) static
Definition at line 1822 of file avx512bwintrin.h.
References _mm512_and_epi32(), _mm512_cmpneq_epi16_mask, and _mm512_setzero_si512().
_mm512_test_epi8_mask()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_test_epi8_mask (__m512i __A, __m512i __B) static
Definition at line 1808 of file avx512bwintrin.h.
References _mm512_and_epi32(), _mm512_cmpneq_epi8_mask, and _mm512_setzero_si512().
_mm512_testn_epi16_mask()
static __inline__ __mmask32 __DEFAULT_FN_ATTRS512 _mm512_testn_epi16_mask (__m512i __A, __m512i __B) static
Definition at line 1849 of file avx512bwintrin.h.
References _mm512_and_epi32(), _mm512_cmpeq_epi16_mask, and _mm512_setzero_si512().
_mm512_testn_epi8_mask()
static __inline__ __mmask64 __DEFAULT_FN_ATTRS512 _mm512_testn_epi8_mask (__m512i __A, __m512i __B) static
Definition at line 1836 of file avx512bwintrin.h.
References _mm512_and_epi32(), _mm512_cmpeq_epi8_mask, and _mm512_setzero_si512().
_mm512_unpackhi_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_unpackhi_epi16 (__m512i __A, __m512i __B) static
Definition at line 1286 of file avx512bwintrin.h.
Referenced by _mm512_mask_unpackhi_epi16(), and _mm512_maskz_unpackhi_epi16().
_mm512_unpackhi_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_unpackhi_epi8 (__m512i __A, __m512i __B) static
Definition at line 1251 of file avx512bwintrin.h.
Referenced by _mm512_mask_unpackhi_epi8(), and _mm512_maskz_unpackhi_epi8().
_mm512_unpacklo_epi16()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_unpacklo_epi16 (__m512i __A, __m512i __B) static
Definition at line 1348 of file avx512bwintrin.h.
Referenced by _mm512_mask_unpacklo_epi16(), and _mm512_maskz_unpacklo_epi16().
_mm512_unpacklo_epi8()
static __inline__ __m512i __DEFAULT_FN_ATTRS512 _mm512_unpacklo_epi8 (__m512i __A, __m512i __B) static
Definition at line 1313 of file avx512bwintrin.h.
Referenced by _mm512_mask_unpacklo_epi8(), and _mm512_maskz_unpacklo_epi8().
_store_mask32()
static __inline__ void __DEFAULT_FN_ATTRS _store_mask32 (__mmask32 * __A, __mmask32 __B) static
Definition at line 214 of file avx512bwintrin.h.
_store_mask64()
static __inline__ void __DEFAULT_FN_ATTRS _store_mask64 (__mmask64 * __A, __mmask64 __B) static
Definition at line 218 of file avx512bwintrin.h.