clang: lib/Headers/avx512vlvnniintrin.h File Reference
avx512vlvnniintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512vnni"), __min_vector_width__(128)))
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512vnni"), __min_vector_width__(256)))
#define _mm256_dpbusd_epi32(S, A, B) ((__m256i)__builtin_ia32_vpdpbusd256((__v8si)(S), (__v8si)(A), (__v8si)(B)))
Multiply groups of 4 adjacent pairs of unsigned 8-bit integers in A with corresponding signed 8-bit integers in B, producing 4 intermediate signed 16-bit results.
#define _mm256_dpbusds_epi32(S, A, B) ((__m256i)__builtin_ia32_vpdpbusds256((__v8si)(S), (__v8si)(A), (__v8si)(B)))
Multiply groups of 4 adjacent pairs of unsigned 8-bit integers in A with corresponding signed 8-bit integers in B, producing 4 intermediate signed 16-bit results.
#define _mm256_dpwssd_epi32(S, A, B) ((__m256i)__builtin_ia32_vpdpwssd256((__v8si)(S), (__v8si)(A), (__v8si)(B)))
Multiply groups of 2 adjacent pairs of signed 16-bit integers in A with corresponding 16-bit integers in B, producing 2 intermediate signed 32-bit results.
#define _mm256_dpwssds_epi32(S, A, B) ((__m256i)__builtin_ia32_vpdpwssds256((__v8si)(S), (__v8si)(A), (__v8si)(B)))
Multiply groups of 2 adjacent pairs of signed 16-bit integers in A with corresponding 16-bit integers in B, producing 2 intermediate signed 32-bit results.
#define _mm_dpbusd_epi32(S, A, B) ((__m128i)__builtin_ia32_vpdpbusd128((__v4si)(S), (__v4si)(A), (__v4si)(B)))
Multiply groups of 4 adjacent pairs of unsigned 8-bit integers in A with corresponding signed 8-bit integers in B, producing 4 intermediate signed 16-bit results.
#define _mm_dpbusds_epi32(S, A, B) ((__m128i)__builtin_ia32_vpdpbusds128((__v4si)(S), (__v4si)(A), (__v4si)(B)))
Multiply groups of 4 adjacent pairs of unsigned 8-bit integers in A with corresponding signed 8-bit integers in B, producing 4 intermediate signed 16-bit results.
#define _mm_dpwssd_epi32(S, A, B) ((__m128i)__builtin_ia32_vpdpwssd128((__v4si)(S), (__v4si)(A), (__v4si)(B)))
Multiply groups of 2 adjacent pairs of signed 16-bit integers in A with corresponding 16-bit integers in B, producing 2 intermediate signed 32-bit results.
#define _mm_dpwssds_epi32(S, A, B) ((__m128i)__builtin_ia32_vpdpwssds128((__v4si)(S), (__v4si)(A), (__v4si)(B)))
Multiply groups of 2 adjacent pairs of signed 16-bit integers in A with corresponding 16-bit integers in B, producing 2 intermediate signed 32-bit results.
Functions
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_dpbusd_epi32 (__m256i __S, __mmask8 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_dpbusd_epi32 (__mmask8 __U, __m256i __S, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_dpbusds_epi32 (__m256i __S, __mmask8 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_dpbusds_epi32 (__mmask8 __U, __m256i __S, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_dpwssd_epi32 (__m256i __S, __mmask8 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_dpwssd_epi32 (__mmask8 __U, __m256i __S, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_dpwssds_epi32 (__m256i __S, __mmask8 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_dpwssds_epi32 (__mmask8 __U, __m256i __S, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_dpbusd_epi32 (__m128i __S, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_dpbusd_epi32 (__mmask8 __U, __m128i __S, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_dpbusds_epi32 (__m128i __S, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_dpbusds_epi32 (__mmask8 __U, __m128i __S, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_dpwssd_epi32 (__m128i __S, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_dpwssd_epi32 (__mmask8 __U, __m128i __S, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_dpwssds_epi32 (__m128i __S, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_dpwssds_epi32 (__mmask8 __U, __m128i __S, __m128i __A, __m128i __B)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512vnni"), __min_vector_width__(128)))
Definition at line 18 of file avx512vlvnniintrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512vnni"), __min_vector_width__(256)))
Definition at line 19 of file avx512vlvnniintrin.h.
_mm256_dpbusd_epi32
#define _mm256_dpbusd_epi32 (S, A, B) ((__m256i)__builtin_ia32_vpdpbusd256((__v8si)(S), (__v8si)(A), (__v8si)(B)))
Multiply groups of 4 adjacent pairs of unsigned 8-bit integers in A with corresponding signed 8-bit integers in B, producing 4 intermediate signed 16-bit results.
Sum these 4 results with the corresponding 32-bit integer in S, and store the packed 32-bit results in DST.
This intrinsic corresponds to the VPDPBUSD instructions.
\operation FOR j := 0 to 7 tmp1.word := Signed(ZeroExtend16(A.byte[4*j]) * SignExtend16(B.byte[4*j])) tmp2.word := Signed(ZeroExtend16(A.byte[4*j+1]) * SignExtend16(B.byte[4*j+1])) tmp3.word := Signed(ZeroExtend16(A.byte[4*j+2]) * SignExtend16(B.byte[4*j+2])) tmp4.word := Signed(ZeroExtend16(A.byte[4*j+3]) * SignExtend16(B.byte[4*j+3])) DST.dword[j] := S.dword[j] + tmp1 + tmp2 + tmp3 + tmp4 ENDFOR DST[MAX:256] := 0 \endoperation
Definition at line 38 of file avx512vlvnniintrin.h.
_mm256_dpbusds_epi32
#define _mm256_dpbusds_epi32 (S, A, B) ((__m256i)__builtin_ia32_vpdpbusds256((__v8si)(S), (__v8si)(A), (__v8si)(B)))
Multiply groups of 4 adjacent pairs of unsigned 8-bit integers in A with corresponding signed 8-bit integers in B, producing 4 intermediate signed 16-bit results.
Sum these 4 results with the corresponding 32-bit integer in S using signed saturation, and store the packed 32-bit results in DST.
This intrinsic corresponds to the VPDPBUSDS instructions.
\operation FOR j := 0 to 7 tmp1.word := Signed(ZeroExtend16(A.byte[4*j]) * SignExtend16(B.byte[4*j])) tmp2.word := Signed(ZeroExtend16(A.byte[4*j+1]) * SignExtend16(B.byte[4*j+1])) tmp3.word := Signed(ZeroExtend16(A.byte[4*j+2]) * SignExtend16(B.byte[4*j+2])) tmp4.word := Signed(ZeroExtend16(A.byte[4*j+3]) * SignExtend16(B.byte[4*j+3])) DST.dword[j] := Saturate32(S.dword[j] + tmp1 + tmp2 + tmp3 + tmp4) ENDFOR DST[MAX:256] := 0 \endoperation
Definition at line 58 of file avx512vlvnniintrin.h.
_mm256_dpwssd_epi32
#define _mm256_dpwssd_epi32 (S, A, B) ((__m256i)__builtin_ia32_vpdpwssd256((__v8si)(S), (__v8si)(A), (__v8si)(B)))
Multiply groups of 2 adjacent pairs of signed 16-bit integers in A with corresponding 16-bit integers in B, producing 2 intermediate signed 32-bit results.
Sum these 2 results with the corresponding 32-bit integer in S, and store the packed 32-bit results in DST.
This intrinsic corresponds to the VPDPWSSD instructions.
\operation FOR j := 0 to 7 tmp1.dword := SignExtend32(A.word[2*j]) * SignExtend32(B.word[2*j]) tmp2.dword := SignExtend32(A.word[2*j+1]) * SignExtend32(B.word[2*j+1]) DST.dword[j] := S.dword[j] + tmp1 + tmp2 ENDFOR DST[MAX:256] := 0 \endoperation
Definition at line 76 of file avx512vlvnniintrin.h.
_mm256_dpwssds_epi32
#define _mm256_dpwssds_epi32 (S, A, B) ((__m256i)__builtin_ia32_vpdpwssds256((__v8si)(S), (__v8si)(A), (__v8si)(B)))
Multiply groups of 2 adjacent pairs of signed 16-bit integers in A with corresponding 16-bit integers in B, producing 2 intermediate signed 32-bit results.
Sum these 2 results with the corresponding 32-bit integer in S using signed saturation, and store the packed 32-bit results in DST.
This intrinsic corresponds to the VPDPWSSDS instructions.
\operation FOR j := 0 to 7 tmp1.dword := SignExtend32(A.word[2*j]) * SignExtend32(B.word[2*j]) tmp2.dword := SignExtend32(A.word[2*j+1]) * SignExtend32(B.word[2*j+1]) DST.dword[j] := Saturate32(S.dword[j] + tmp1 + tmp2) ENDFOR DST[MAX:256] := 0 \endoperation
Definition at line 94 of file avx512vlvnniintrin.h.
_mm_dpbusd_epi32
#define _mm_dpbusd_epi32 (S, A, B) ((__m128i)__builtin_ia32_vpdpbusd128((__v4si)(S), (__v4si)(A), (__v4si)(B)))
Multiply groups of 4 adjacent pairs of unsigned 8-bit integers in A with corresponding signed 8-bit integers in B, producing 4 intermediate signed 16-bit results.
Sum these 4 results with the corresponding 32-bit integer in S, and store the packed 32-bit results in DST.
This intrinsic corresponds to the VPDPBUSD instructions.
\operation FOR j := 0 to 3 tmp1.word := Signed(ZeroExtend16(A.byte[4*j]) * SignExtend16(B.byte[4*j])) tmp2.word := Signed(ZeroExtend16(A.byte[4*j+1]) * SignExtend16(B.byte[4*j+1])) tmp3.word := Signed(ZeroExtend16(A.byte[4*j+2]) * SignExtend16(B.byte[4*j+2])) tmp4.word := Signed(ZeroExtend16(A.byte[4*j+3]) * SignExtend16(B.byte[4*j+3])) DST.dword[j] := S.dword[j] + tmp1 + tmp2 + tmp3 + tmp4 ENDFOR DST[MAX:128] := 0 \endoperation
Definition at line 114 of file avx512vlvnniintrin.h.
_mm_dpbusds_epi32
#define _mm_dpbusds_epi32 (S, A, B) ((__m128i)__builtin_ia32_vpdpbusds128((__v4si)(S), (__v4si)(A), (__v4si)(B)))
Multiply groups of 4 adjacent pairs of unsigned 8-bit integers in A with corresponding signed 8-bit integers in B, producing 4 intermediate signed 16-bit results.
Sum these 4 results with the corresponding 32-bit integer in S using signed saturation, and store the packed 32-bit results in DST.
This intrinsic corresponds to the VPDPBUSDS instructions.
\operation FOR j := 0 to 3 tmp1.word := Signed(ZeroExtend16(A.byte[4*j]) * SignExtend16(B.byte[4*j])) tmp2.word := Signed(ZeroExtend16(A.byte[4*j+1]) * SignExtend16(B.byte[4*j+1])) tmp3.word := Signed(ZeroExtend16(A.byte[4*j+2]) * SignExtend16(B.byte[4*j+2])) tmp4.word := Signed(ZeroExtend16(A.byte[4*j+3]) * SignExtend16(B.byte[4*j+3])) DST.dword[j] := Saturate32(S.dword[j] + tmp1 + tmp2 + tmp3 + tmp4) ENDFOR DST[MAX:128] := 0 \endoperation
Definition at line 134 of file avx512vlvnniintrin.h.
_mm_dpwssd_epi32
#define _mm_dpwssd_epi32 (S, A, B) ((__m128i)__builtin_ia32_vpdpwssd128((__v4si)(S), (__v4si)(A), (__v4si)(B)))
Multiply groups of 2 adjacent pairs of signed 16-bit integers in A with corresponding 16-bit integers in B, producing 2 intermediate signed 32-bit results.
Sum these 2 results with the corresponding 32-bit integer in S, and store the packed 32-bit results in DST.
This intrinsic corresponds to the VPDPWSSD instructions.
\operation FOR j := 0 to 3 tmp1.dword := SignExtend32(A.word[2*j]) * SignExtend32(B.word[2*j]) tmp2.dword := SignExtend32(A.word[2*j+1]) * SignExtend32(B.word[2*j+1]) DST.dword[j] := S.dword[j] + tmp1 + tmp2 ENDFOR DST[MAX:128] := 0 \endoperation
Definition at line 152 of file avx512vlvnniintrin.h.
_mm_dpwssds_epi32
#define _mm_dpwssds_epi32 (S, A, B) ((__m128i)__builtin_ia32_vpdpwssds128((__v4si)(S), (__v4si)(A), (__v4si)(B)))
Multiply groups of 2 adjacent pairs of signed 16-bit integers in A with corresponding 16-bit integers in B, producing 2 intermediate signed 32-bit results.
Sum these 2 results with the corresponding 32-bit integer in S using signed saturation, and store the packed 32-bit results in DST.
This intrinsic corresponds to the VPDPWSSDS instructions.
\operation FOR j := 0 to 3 tmp1.dword := SignExtend32(A.word[2*j]) * SignExtend32(B.word[2*j]) tmp2.dword := SignExtend32(A.word[2*j+1]) * SignExtend32(B.word[2*j+1]) DST.dword[j] := Saturate32(S.dword[j] + tmp1 + tmp2) ENDFOR DST[MAX:128] := 0 \endoperation
Definition at line 170 of file avx512vlvnniintrin.h.
Function Documentation
_mm256_mask_dpbusd_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_dpbusd_epi32 (__m256i __S, __mmask8 __U, __m256i __A, __m256i __B) static
Definition at line 174 of file avx512vlvnniintrin.h.
References _mm256_dpbusd_epi32.
_mm256_mask_dpbusds_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_dpbusds_epi32 (__m256i __S, __mmask8 __U, __m256i __A, __m256i __B) static
Definition at line 190 of file avx512vlvnniintrin.h.
References _mm256_dpbusds_epi32.
_mm256_mask_dpwssd_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_dpwssd_epi32 (__m256i __S, __mmask8 __U, __m256i __A, __m256i __B) static
Definition at line 206 of file avx512vlvnniintrin.h.
References _mm256_dpwssd_epi32.
_mm256_mask_dpwssds_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_dpwssds_epi32 (__m256i __S, __mmask8 __U, __m256i __A, __m256i __B) static
Definition at line 222 of file avx512vlvnniintrin.h.
References _mm256_dpwssds_epi32.
_mm256_maskz_dpbusd_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_dpbusd_epi32 (__mmask8 __U, __m256i __S, __m256i __A, __m256i __B) static
Definition at line 182 of file avx512vlvnniintrin.h.
References _mm256_dpbusd_epi32, and _mm256_setzero_si256().
_mm256_maskz_dpbusds_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_dpbusds_epi32 (__mmask8 __U, __m256i __S, __m256i __A, __m256i __B) static
Definition at line 198 of file avx512vlvnniintrin.h.
References _mm256_dpbusds_epi32, and _mm256_setzero_si256().
_mm256_maskz_dpwssd_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_dpwssd_epi32 (__mmask8 __U, __m256i __S, __m256i __A, __m256i __B) static
Definition at line 214 of file avx512vlvnniintrin.h.
References _mm256_dpwssd_epi32, and _mm256_setzero_si256().
_mm256_maskz_dpwssds_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_dpwssds_epi32 (__mmask8 __U, __m256i __S, __m256i __A, __m256i __B) static
Definition at line 230 of file avx512vlvnniintrin.h.
References _mm256_dpwssds_epi32, and _mm256_setzero_si256().
_mm_mask_dpbusd_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_dpbusd_epi32 (__m128i __S, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 238 of file avx512vlvnniintrin.h.
References _mm_dpbusd_epi32.
_mm_mask_dpbusds_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_dpbusds_epi32 (__m128i __S, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 254 of file avx512vlvnniintrin.h.
References _mm_dpbusds_epi32.
_mm_mask_dpwssd_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_dpwssd_epi32 (__m128i __S, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 270 of file avx512vlvnniintrin.h.
References _mm_dpwssd_epi32.
_mm_mask_dpwssds_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_dpwssds_epi32 (__m128i __S, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 286 of file avx512vlvnniintrin.h.
References _mm_dpwssds_epi32.
_mm_maskz_dpbusd_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_dpbusd_epi32 (__mmask8 __U, __m128i __S, __m128i __A, __m128i __B) static
Definition at line 246 of file avx512vlvnniintrin.h.
References _mm_dpbusd_epi32, and _mm_setzero_si128().
_mm_maskz_dpbusds_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_dpbusds_epi32 (__mmask8 __U, __m128i __S, __m128i __A, __m128i __B) static
Definition at line 262 of file avx512vlvnniintrin.h.
References _mm_dpbusds_epi32, and _mm_setzero_si128().
_mm_maskz_dpwssd_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_dpwssd_epi32 (__mmask8 __U, __m128i __S, __m128i __A, __m128i __B) static
Definition at line 278 of file avx512vlvnniintrin.h.
References _mm_dpwssd_epi32, and _mm_setzero_si128().
_mm_maskz_dpwssds_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_dpwssds_epi32 (__mmask8 __U, __m128i __S, __m128i __A, __m128i __B) static
Definition at line 294 of file avx512vlvnniintrin.h.
References _mm_dpwssds_epi32, and _mm_setzero_si128().