clang: lib/Headers/avx512vldqintrin.h File Reference
avx512vldqintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512dq"), __min_vector_width__(128)))
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512dq"), __min_vector_width__(256)))
#define _mm_range_pd(A, B, C)
#define _mm_mask_range_pd(W, U, A, B, C)
#define _mm_maskz_range_pd(U, A, B, C)
#define _mm256_range_pd(A, B, C)
#define _mm256_mask_range_pd(W, U, A, B, C)
#define _mm256_maskz_range_pd(U, A, B, C)
#define _mm_range_ps(A, B, C)
#define _mm_mask_range_ps(W, U, A, B, C)
#define _mm_maskz_range_ps(U, A, B, C)
#define _mm256_range_ps(A, B, C)
#define _mm256_mask_range_ps(W, U, A, B, C)
#define _mm256_maskz_range_ps(U, A, B, C)
#define _mm_reduce_pd(A, B)
#define _mm_mask_reduce_pd(W, U, A, B)
#define _mm_maskz_reduce_pd(U, A, B)
#define _mm256_reduce_pd(A, B)
#define _mm256_mask_reduce_pd(W, U, A, B)
#define _mm256_maskz_reduce_pd(U, A, B)
#define _mm_reduce_ps(A, B)
#define _mm_mask_reduce_ps(W, U, A, B)
#define _mm_maskz_reduce_ps(U, A, B)
#define _mm256_reduce_ps(A, B)
#define _mm256_mask_reduce_ps(W, U, A, B)
#define _mm256_maskz_reduce_ps(U, A, B)
#define _mm256_extractf64x2_pd(A, imm)
#define _mm256_mask_extractf64x2_pd(W, U, A, imm)
#define _mm256_maskz_extractf64x2_pd(U, A, imm)
#define _mm256_extracti64x2_epi64(A, imm)
#define _mm256_mask_extracti64x2_epi64(W, U, A, imm)
#define _mm256_maskz_extracti64x2_epi64(U, A, imm)
#define _mm256_insertf64x2(A, B, imm)
#define _mm256_mask_insertf64x2(W, U, A, B, imm)
#define _mm256_maskz_insertf64x2(U, A, B, imm)
#define _mm256_inserti64x2(A, B, imm)
#define _mm256_mask_inserti64x2(W, U, A, B, imm)
#define _mm256_maskz_inserti64x2(U, A, B, imm)
#define _mm_mask_fpclass_pd_mask(U, A, imm)
#define _mm_fpclass_pd_mask(A, imm)
#define _mm256_mask_fpclass_pd_mask(U, A, imm)
#define _mm256_fpclass_pd_mask(A, imm)
#define _mm_mask_fpclass_ps_mask(U, A, imm)
#define _mm_fpclass_ps_mask(A, imm)
#define _mm256_mask_fpclass_ps_mask(U, A, imm)
#define _mm256_fpclass_ps_mask(A, imm)
Functions
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mullo_epi64 (__m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mullo_epi64 (__m256i __W, __mmask8 __U, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mullo_epi64 (__mmask8 __U, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mullo_epi64 (__m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mullo_epi64 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mullo_epi64 (__mmask8 __U, __m128i __A, __m128i __B)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_andnot_pd (__m256d __W, __mmask8 __U, __m256d __A, __m256d __B)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_andnot_pd (__mmask8 __U, __m256d __A, __m256d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_andnot_pd (__m128d __W, __mmask8 __U, __m128d __A, __m128d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_andnot_pd (__mmask8 __U, __m128d __A, __m128d __B)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_andnot_ps (__m256 __W, __mmask8 __U, __m256 __A, __m256 __B)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_andnot_ps (__mmask8 __U, __m256 __A, __m256 __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_andnot_ps (__m128 __W, __mmask8 __U, __m128 __A, __m128 __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_andnot_ps (__mmask8 __U, __m128 __A, __m128 __B)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_and_pd (__m256d __W, __mmask8 __U, __m256d __A, __m256d __B)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_and_pd (__mmask8 __U, __m256d __A, __m256d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_and_pd (__m128d __W, __mmask8 __U, __m128d __A, __m128d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_and_pd (__mmask8 __U, __m128d __A, __m128d __B)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_and_ps (__m256 __W, __mmask8 __U, __m256 __A, __m256 __B)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_and_ps (__mmask8 __U, __m256 __A, __m256 __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_and_ps (__m128 __W, __mmask8 __U, __m128 __A, __m128 __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_and_ps (__mmask8 __U, __m128 __A, __m128 __B)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_xor_pd (__m256d __W, __mmask8 __U, __m256d __A, __m256d __B)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_xor_pd (__mmask8 __U, __m256d __A, __m256d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_xor_pd (__m128d __W, __mmask8 __U, __m128d __A, __m128d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_xor_pd (__mmask8 __U, __m128d __A, __m128d __B)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_xor_ps (__m256 __W, __mmask8 __U, __m256 __A, __m256 __B)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_xor_ps (__mmask8 __U, __m256 __A, __m256 __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_xor_ps (__m128 __W, __mmask8 __U, __m128 __A, __m128 __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_xor_ps (__mmask8 __U, __m128 __A, __m128 __B)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_or_pd (__m256d __W, __mmask8 __U, __m256d __A, __m256d __B)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_or_pd (__mmask8 __U, __m256d __A, __m256d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_or_pd (__m128d __W, __mmask8 __U, __m128d __A, __m128d __B)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_or_pd (__mmask8 __U, __m128d __A, __m128d __B)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_or_ps (__m256 __W, __mmask8 __U, __m256 __A, __m256 __B)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_or_ps (__mmask8 __U, __m256 __A, __m256 __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_or_ps (__m128 __W, __mmask8 __U, __m128 __A, __m128 __B)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_or_ps (__mmask8 __U, __m128 __A, __m128 __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtpd_epi64 (__m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtpd_epi64 (__m128i __W, __mmask8 __U, __m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtpd_epi64 (__mmask8 __U, __m128d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtpd_epi64 (__m256d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtpd_epi64 (__m256i __W, __mmask8 __U, __m256d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtpd_epi64 (__mmask8 __U, __m256d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtpd_epu64 (__m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtpd_epu64 (__m128i __W, __mmask8 __U, __m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtpd_epu64 (__mmask8 __U, __m128d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtpd_epu64 (__m256d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtpd_epu64 (__m256i __W, __mmask8 __U, __m256d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtpd_epu64 (__mmask8 __U, __m256d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtps_epi64 (__m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtps_epi64 (__m128i __W, __mmask8 __U, __m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtps_epi64 (__mmask8 __U, __m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtps_epi64 (__m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtps_epi64 (__m256i __W, __mmask8 __U, __m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtps_epi64 (__mmask8 __U, __m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtps_epu64 (__m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtps_epu64 (__m128i __W, __mmask8 __U, __m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtps_epu64 (__mmask8 __U, __m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtps_epu64 (__m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtps_epu64 (__m256i __W, __mmask8 __U, __m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtps_epu64 (__mmask8 __U, __m128 __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_cvtepi64_pd (__m128i __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi64_pd (__m128d __W, __mmask8 __U, __m128i __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi64_pd (__mmask8 __U, __m128i __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_cvtepi64_pd (__m256i __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi64_pd (__m256d __W, __mmask8 __U, __m256i __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi64_pd (__mmask8 __U, __m256i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_cvtepi64_ps (__m128i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi64_ps (__m128 __W, __mmask8 __U, __m128i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi64_ps (__mmask8 __U, __m128i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_cvtepi64_ps (__m256i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi64_ps (__m128 __W, __mmask8 __U, __m256i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi64_ps (__mmask8 __U, __m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttpd_epi64 (__m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttpd_epi64 (__m128i __W, __mmask8 __U, __m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttpd_epi64 (__mmask8 __U, __m128d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttpd_epi64 (__m256d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttpd_epi64 (__m256i __W, __mmask8 __U, __m256d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttpd_epi64 (__mmask8 __U, __m256d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttpd_epu64 (__m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttpd_epu64 (__m128i __W, __mmask8 __U, __m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttpd_epu64 (__mmask8 __U, __m128d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttpd_epu64 (__m256d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttpd_epu64 (__m256i __W, __mmask8 __U, __m256d __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttpd_epu64 (__mmask8 __U, __m256d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttps_epi64 (__m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttps_epi64 (__m128i __W, __mmask8 __U, __m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttps_epi64 (__mmask8 __U, __m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttps_epi64 (__m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttps_epi64 (__m256i __W, __mmask8 __U, __m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttps_epi64 (__mmask8 __U, __m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttps_epu64 (__m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttps_epu64 (__m128i __W, __mmask8 __U, __m128 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttps_epu64 (__mmask8 __U, __m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttps_epu64 (__m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttps_epu64 (__m256i __W, __mmask8 __U, __m128 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttps_epu64 (__mmask8 __U, __m128 __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_cvtepu64_pd (__m128i __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu64_pd (__m128d __W, __mmask8 __U, __m128i __A)
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu64_pd (__mmask8 __U, __m128i __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_cvtepu64_pd (__m256i __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu64_pd (__m256d __W, __mmask8 __U, __m256i __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu64_pd (__mmask8 __U, __m256i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_cvtepu64_ps (__m128i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu64_ps (__m128 __W, __mmask8 __U, __m128i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu64_ps (__mmask8 __U, __m128i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_cvtepu64_ps (__m256i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu64_ps (__m128 __W, __mmask8 __U, __m256i __A)
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu64_ps (__mmask8 __U, __m256i __A)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_movepi32_mask (__m128i __A)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS256 _mm256_movepi32_mask (__m256i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_movm_epi32 (__mmask8 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_movm_epi32 (__mmask8 __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_movm_epi64 (__mmask8 __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_movm_epi64 (__mmask8 __A)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_movepi64_mask (__m128i __A)
static __inline__ __mmask8 __DEFAULT_FN_ATTRS256 _mm256_movepi64_mask (__m256i __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_broadcast_f32x2 (__m128 __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_broadcast_f32x2 (__m256 __O, __mmask8 __M, __m128 __A)
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcast_f32x2 (__mmask8 __M, __m128 __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_broadcast_f64x2 (__m128d __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_broadcast_f64x2 (__m256d __O, __mmask8 __M, __m128d __A)
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcast_f64x2 (__mmask8 __M, __m128d __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_broadcast_i32x2 (__m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_broadcast_i32x2 (__m128i __O, __mmask8 __M, __m128i __A)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_broadcast_i32x2 (__mmask8 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_broadcast_i32x2 (__m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_broadcast_i32x2 (__m256i __O, __mmask8 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcast_i32x2 (__mmask8 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_broadcast_i64x2 (__m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_broadcast_i64x2 (__m256i __O, __mmask8 __M, __m128i __A)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcast_i64x2 (__mmask8 __M, __m128i __A)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512dq"), __min_vector_width__(128)))
Definition at line 18 of file avx512vldqintrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vl,avx512dq"), __min_vector_width__(256)))
Definition at line 19 of file avx512vldqintrin.h.
_mm256_extractf64x2_pd
#define _mm256_extractf64x2_pd (A, imm)
Value:
  ((__m128d)__builtin_ia32_extractf64x2_256_mask((__v4df)(__m256d)(A), \
                                                 (int)(imm), \
                                                 (__v2df)_mm_undefined_pd(), \
                                                 (__mmask8)-1))
Definition at line 1068 of file avx512vldqintrin.h.
_mm256_extracti64x2_epi64
#define _mm256_extracti64x2_epi64 (A, imm)
Value:
  ((__m128i)__builtin_ia32_extracti64x2_256_mask((__v4di)(__m256i)(A), \
                                                (int)(imm), \
                                                (__v2di)_mm_undefined_si128(), \
                                                (__mmask8)-1))
Definition at line 1086 of file avx512vldqintrin.h.
_mm256_fpclass_pd_mask
#define _mm256_fpclass_pd_mask (A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclasspd256_mask((__v4df)(__m256d)(A), (int)(imm), \
                                              (__mmask8)-1))
Definition at line 1144 of file avx512vldqintrin.h.
_mm256_fpclass_ps_mask
#define _mm256_fpclass_ps_mask (A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclassps256_mask((__v8sf)(__m256)(A), (int)(imm), \
                                              (__mmask8)-1))
Definition at line 1160 of file avx512vldqintrin.h.
_mm256_insertf64x2
#define _mm256_insertf64x2 (A, B, imm)
Value:
  ((__m256d)__builtin_ia32_insertf64x2_256((__v4df)(__m256d)(A), \
                                           (__v2df)(__m128d)(B), (int)(imm)))
Definition at line 1104 of file avx512vldqintrin.h.
_mm256_inserti64x2
#define _mm256_inserti64x2 (A, B, imm)
Value:
  ((__m256i)__builtin_ia32_inserti64x2_256((__v4di)(__m256i)(A), \
                                           (__v2di)(__m128i)(B), (int)(imm)))
Definition at line 1118 of file avx512vldqintrin.h.
_mm256_mask_extractf64x2_pd
#define _mm256_mask_extractf64x2_pd (W, U, A, imm)
Value:
  ((__m128d)__builtin_ia32_extractf64x2_256_mask((__v4df)(__m256d)(A), \
                                                 (int)(imm), \
                                                 (__v2df)(__m128d)(W), \
                                                 (__mmask8)(U)))
Definition at line 1074 of file avx512vldqintrin.h.
_mm256_mask_extracti64x2_epi64
#define _mm256_mask_extracti64x2_epi64 (W, U, A, imm)
Value:
  ((__m128i)__builtin_ia32_extracti64x2_256_mask((__v4di)(__m256i)(A), \
                                                 (int)(imm), \
                                                 (__v2di)(__m128i)(W), \
                                                 (__mmask8)(U)))
Definition at line 1092 of file avx512vldqintrin.h.
_mm256_mask_fpclass_pd_mask
#define _mm256_mask_fpclass_pd_mask (U, A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclasspd256_mask((__v4df)(__m256d)(A), (int)(imm), \
                                              (__mmask8)(U)))
Definition at line 1140 of file avx512vldqintrin.h.
_mm256_mask_fpclass_ps_mask
#define _mm256_mask_fpclass_ps_mask (U, A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclassps256_mask((__v8sf)(__m256)(A), (int)(imm), \
                                              (__mmask8)(U)))
Definition at line 1156 of file avx512vldqintrin.h.
_mm256_mask_insertf64x2
#define _mm256_mask_insertf64x2 (W, U, A, B, imm)
Value:
  ((__m256d)__builtin_ia32_selectpd_256((__mmask8)(U), \
                                  (__v4df)_mm256_insertf64x2((A), (B), (imm)), \
                                  (__v4df)(__m256d)(W)))
Definition at line 1108 of file avx512vldqintrin.h.
_mm256_mask_inserti64x2
#define _mm256_mask_inserti64x2 (W, U, A, B, imm)
Value:
  ((__m256i)__builtin_ia32_selectq_256((__mmask8)(U), \
                                   (__v4di)_mm256_inserti64x2((A), (B), (imm)), \
                                   (__v4di)(__m256i)(W)))
Definition at line 1122 of file avx512vldqintrin.h.
_mm256_mask_range_pd
#define _mm256_mask_range_pd (W, U, A, B, C)
Value:
  ((__m256d)__builtin_ia32_rangepd256_mask((__v4df)(__m256d)(A), \
                                           (__v4df)(__m256d)(B), (int)(C), \
                                           (__v4df)(__m256d)(W), \
                                           (__mmask8)(U)))
Definition at line 799 of file avx512vldqintrin.h.
_mm256_mask_range_ps
#define _mm256_mask_range_ps (W, U, A, B, C)
Value:
  ((__m256)__builtin_ia32_rangeps256_mask((__v8sf)(__m256)(A), \
                                          (__v8sf)(__m256)(B), (int)(C), \
                                          (__v8sf)(__m256)(W), (__mmask8)(U)))
Definition at line 834 of file avx512vldqintrin.h.
_mm256_mask_reduce_pd
#define _mm256_mask_reduce_pd (W, U, A, B)
Value:
  ((__m256d)__builtin_ia32_reducepd256_mask((__v4df)(__m256d)(A), (int)(B), \
                                            (__v4df)(__m256d)(W), \
                                            (__mmask8)(U)))
Definition at line 865 of file avx512vldqintrin.h.
_mm256_mask_reduce_ps
#define _mm256_mask_reduce_ps (W, U, A, B)
Value:
  ((__m256)__builtin_ia32_reduceps256_mask((__v8sf)(__m256)(A), (int)(B), \
                                           (__v8sf)(__m256)(W), \
                                           (__mmask8)(U)))
Definition at line 895 of file avx512vldqintrin.h.
_mm256_maskz_extractf64x2_pd
#define _mm256_maskz_extractf64x2_pd (U, A, imm)
Value:
  ((__m128d)__builtin_ia32_extractf64x2_256_mask((__v4df)(__m256d)(A), \
                                                 (int)(imm), \
                                                 (__v2df)_mm_setzero_pd(), \
                                                 (__mmask8)(U)))
Definition at line 1080 of file avx512vldqintrin.h.
_mm256_maskz_extracti64x2_epi64
#define _mm256_maskz_extracti64x2_epi64 (U, A, imm)
Value:
  ((__m128i)__builtin_ia32_extracti64x2_256_mask((__v4di)(__m256i)(A), \
                                                 (int)(imm), \
                                                 (__v2di)_mm_setzero_si128(), \
                                                 (__mmask8)(U)))
Definition at line 1098 of file avx512vldqintrin.h.
_mm256_maskz_insertf64x2
#define _mm256_maskz_insertf64x2 (U, A, B, imm)
Value:
  ((__m256d)__builtin_ia32_selectpd_256((__mmask8)(U), \
                                  (__v4df)_mm256_insertf64x2((A), (B), (imm)), \
                                  (__v4df)_mm256_setzero_pd()))
Definition at line 1113 of file avx512vldqintrin.h.
_mm256_maskz_inserti64x2
#define _mm256_maskz_inserti64x2 (U, A, B, imm)
Value:
  ((__m256i)__builtin_ia32_selectq_256((__mmask8)(U), \
                                   (__v4di)_mm256_inserti64x2((A), (B), (imm)), \
                                   (__v4di)_mm256_setzero_si256()))
Definition at line 1127 of file avx512vldqintrin.h.
_mm256_maskz_range_pd
#define _mm256_maskz_range_pd (U, A, B, C)
Value:
  ((__m256d)__builtin_ia32_rangepd256_mask((__v4df)(__m256d)(A), \
                                           (__v4df)(__m256d)(B), (int)(C), \
                                           (__v4df)_mm256_setzero_pd(), \
                                           (__mmask8)(U)))
Definition at line 805 of file avx512vldqintrin.h.
_mm256_maskz_range_ps
#define _mm256_maskz_range_ps (U, A, B, C)
Value:
  ((__m256)__builtin_ia32_rangeps256_mask((__v8sf)(__m256)(A), \
                                          (__v8sf)(__m256)(B), (int)(C), \
                                          (__v8sf)_mm256_setzero_ps(), \
                                          (__mmask8)(U)))
Definition at line 839 of file avx512vldqintrin.h.
_mm256_maskz_reduce_pd
#define _mm256_maskz_reduce_pd (U, A, B)
Value:
  ((__m256d)__builtin_ia32_reducepd256_mask((__v4df)(__m256d)(A), (int)(B), \
                                            (__v4df)_mm256_setzero_pd(), \
                                            (__mmask8)(U)))
Definition at line 870 of file avx512vldqintrin.h.
_mm256_maskz_reduce_ps
#define _mm256_maskz_reduce_ps (U, A, B)
Value:
  ((__m256)__builtin_ia32_reduceps256_mask((__v8sf)(__m256)(A), (int)(B), \
                                           (__v8sf)_mm256_setzero_ps(), \
                                           (__mmask8)(U)))
Definition at line 900 of file avx512vldqintrin.h.
_mm256_range_pd
#define _mm256_range_pd (A, B, C)
Value:
  ((__m256d)__builtin_ia32_rangepd256_mask((__v4df)(__m256d)(A), \
                                           (__v4df)(__m256d)(B), (int)(C), \
                                           (__v4df)_mm256_setzero_pd(), \
                                           (__mmask8)-1))
Definition at line 793 of file avx512vldqintrin.h.
_mm256_range_ps
#define _mm256_range_ps (A, B, C)
Value:
  ((__m256)__builtin_ia32_rangeps256_mask((__v8sf)(__m256)(A), \
                                          (__v8sf)(__m256)(B), (int)(C), \
                                          (__v8sf)_mm256_setzero_ps(), \
                                          (__mmask8)-1))
Definition at line 828 of file avx512vldqintrin.h.
_mm256_reduce_pd
#define _mm256_reduce_pd (A, B)
Value:
  ((__m256d)__builtin_ia32_reducepd256_mask((__v4df)(__m256d)(A), (int)(B), \
                                            (__v4df)_mm256_setzero_pd(), \
                                            (__mmask8)-1))
Definition at line 860 of file avx512vldqintrin.h.
_mm256_reduce_ps
#define _mm256_reduce_ps (A, B)
Value:
  ((__m256)__builtin_ia32_reduceps256_mask((__v8sf)(__m256)(A), (int)(B), \
                                           (__v8sf)_mm256_setzero_ps(), \
                                           (__mmask8)-1))
Definition at line 890 of file avx512vldqintrin.h.
_mm_fpclass_pd_mask
#define _mm_fpclass_pd_mask (A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclasspd128_mask((__v2df)(__m128d)(A), (int)(imm), \
                                              (__mmask8)-1))
Definition at line 1136 of file avx512vldqintrin.h.
_mm_fpclass_ps_mask
#define _mm_fpclass_ps_mask (A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclassps128_mask((__v4sf)(__m128)(A), (int)(imm), \
                                              (__mmask8)-1))
Definition at line 1152 of file avx512vldqintrin.h.
_mm_mask_fpclass_pd_mask
#define _mm_mask_fpclass_pd_mask (U, A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclasspd128_mask((__v2df)(__m128d)(A), (int)(imm), \
                                              (__mmask8)(U)))
Definition at line 1132 of file avx512vldqintrin.h.
_mm_mask_fpclass_ps_mask
#define _mm_mask_fpclass_ps_mask (U, A, imm)
Value:
  ((__mmask8)__builtin_ia32_fpclassps128_mask((__v4sf)(__m128)(A), (int)(imm), \
                                              (__mmask8)(U)))
Definition at line 1148 of file avx512vldqintrin.h.
_mm_mask_range_pd
#define _mm_mask_range_pd (W, U, A, B, C)
Value:
  ((__m128d)__builtin_ia32_rangepd128_mask((__v2df)(__m128d)(A), \
                                           (__v2df)(__m128d)(B), (int)(C), \
                                           (__v2df)(__m128d)(W), \
                                           (__mmask8)(U)))
Definition at line 781 of file avx512vldqintrin.h.
_mm_mask_range_ps
#define _mm_mask_range_ps (W, U, A, B, C)
Value:
  ((__m128)__builtin_ia32_rangeps128_mask((__v4sf)(__m128)(A), \
                                          (__v4sf)(__m128)(B), (int)(C), \
                                          (__v4sf)(__m128)(W), (__mmask8)(U)))
Definition at line 817 of file avx512vldqintrin.h.
_mm_mask_reduce_pd
#define _mm_mask_reduce_pd (W, U, A, B)
Value:
  ((__m128d)__builtin_ia32_reducepd128_mask((__v2df)(__m128d)(A), (int)(B), \
                                            (__v2df)(__m128d)(W), \
                                            (__mmask8)(U)))
Definition at line 850 of file avx512vldqintrin.h.
_mm_mask_reduce_ps
#define _mm_mask_reduce_ps (W, U, A, B)
Value:
  ((__m128)__builtin_ia32_reduceps128_mask((__v4sf)(__m128)(A), (int)(B), \
                                           (__v4sf)(__m128)(W), \
                                           (__mmask8)(U)))
Definition at line 880 of file avx512vldqintrin.h.
_mm_maskz_range_pd
#define _mm_maskz_range_pd (U, A, B, C)
Value:
  ((__m128d)__builtin_ia32_rangepd128_mask((__v2df)(__m128d)(A), \
                                           (__v2df)(__m128d)(B), (int)(C), \
                                           (__v2df)_mm_setzero_pd(), \
                                           (__mmask8)(U)))
Definition at line 787 of file avx512vldqintrin.h.
_mm_maskz_range_ps
#define _mm_maskz_range_ps (U, A, B, C)
Value:
  ((__m128)__builtin_ia32_rangeps128_mask((__v4sf)(__m128)(A), \
                                          (__v4sf)(__m128)(B), (int)(C), \
                                          (__v4sf)_mm_setzero_ps(), \
                                          (__mmask8)(U)))
Definition at line 822 of file avx512vldqintrin.h.
_mm_maskz_reduce_pd
#define _mm_maskz_reduce_pd (U, A, B)
Value:
  ((__m128d)__builtin_ia32_reducepd128_mask((__v2df)(__m128d)(A), (int)(B), \
                                            (__v2df)_mm_setzero_pd(), \
                                            (__mmask8)(U)))
Definition at line 855 of file avx512vldqintrin.h.
_mm_maskz_reduce_ps
#define _mm_maskz_reduce_ps (U, A, B)
Value:
  ((__m128)__builtin_ia32_reduceps128_mask((__v4sf)(__m128)(A), (int)(B), \
                                           (__v4sf)_mm_setzero_ps(), \
                                           (__mmask8)(U)))
Definition at line 885 of file avx512vldqintrin.h.
_mm_range_pd
#define _mm_range_pd (A, B, C)
Value:
  ((__m128d)__builtin_ia32_rangepd128_mask((__v2df)(__m128d)(A), \
                                           (__v2df)(__m128d)(B), (int)(C), \
                                           (__v2df)_mm_setzero_pd(), \
                                           (__mmask8)-1))
Definition at line 775 of file avx512vldqintrin.h.
_mm_range_ps
#define _mm_range_ps (A, B, C)
Value:
  ((__m128)__builtin_ia32_rangeps128_mask((__v4sf)(__m128)(A), \
                                          (__v4sf)(__m128)(B), (int)(C), \
                                          (__v4sf)_mm_setzero_ps(), \
                                          (__mmask8)-1))
Definition at line 811 of file avx512vldqintrin.h.
_mm_reduce_pd
#define _mm_reduce_pd (A, B)
Value:
  ((__m128d)__builtin_ia32_reducepd128_mask((__v2df)(__m128d)(A), (int)(B), \
                                            (__v2df)_mm_setzero_pd(), \
                                            (__mmask8)-1))
Definition at line 845 of file avx512vldqintrin.h.
_mm_reduce_ps
#define _mm_reduce_ps (A, B)
Value:
  ((__m128)__builtin_ia32_reduceps128_mask((__v4sf)(__m128)(A), (int)(B), \
                                           (__v4sf)_mm_setzero_ps(), \
                                           (__mmask8)-1))
Definition at line 875 of file avx512vldqintrin.h.
Function Documentation
_mm256_broadcast_f32x2()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_broadcast_f32x2 (__m128 __A) static
Definition at line 954 of file avx512vldqintrin.h.
Referenced by _mm256_mask_broadcast_f32x2(), and _mm256_maskz_broadcast_f32x2().
_mm256_broadcast_f64x2()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_broadcast_f64x2 (__m128d __A) static
Definition at line 977 of file avx512vldqintrin.h.
Referenced by _mm256_mask_broadcast_f64x2(), and _mm256_maskz_broadcast_f64x2().
_mm256_broadcast_i32x2()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_broadcast_i32x2 (__m128i __A) static
Definition at line 1023 of file avx512vldqintrin.h.
Referenced by _mm256_mask_broadcast_i32x2(), and _mm256_maskz_broadcast_i32x2().
_mm256_broadcast_i64x2()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_broadcast_i64x2 (__m128i __A) static
Definition at line 1046 of file avx512vldqintrin.h.
Referenced by _mm256_mask_broadcast_i64x2(), and _mm256_maskz_broadcast_i64x2().
_mm256_cvtepi64_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_cvtepi64_pd (__m256i __A) static
Definition at line 471 of file avx512vldqintrin.h.
Referenced by _mm256_mask_cvtepi64_pd(), and _mm256_maskz_cvtepi64_pd().
_mm256_cvtepi64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_cvtepi64_ps (__m256i __A) static
Definition at line 511 of file avx512vldqintrin.h.
Referenced by _mm256_mask_cvtepi64_ps(), and _mm256_maskz_cvtepi64_ps().
_mm256_cvtepu64_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_cvtepu64_pd (__m256i __A) static
Definition at line 717 of file avx512vldqintrin.h.
Referenced by _mm256_mask_cvtepu64_pd(), and _mm256_maskz_cvtepu64_pd().
_mm256_cvtepu64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_cvtepu64_ps (__m256i __A) static
Definition at line 757 of file avx512vldqintrin.h.
Referenced by _mm256_mask_cvtepu64_ps(), and _mm256_maskz_cvtepu64_ps().
_mm256_cvtpd_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtpd_epi64 (__m256d __A) static
Definition at line 305 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_cvtpd_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtpd_epu64 (__m256d __A) static
Definition at line 347 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_cvtps_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtps_epi64 (__m128 __A) static
Definition at line 389 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_cvtps_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvtps_epu64 (__m128 __A) static
Definition at line 431 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_cvttpd_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttpd_epi64 (__m256d __A) static
Definition at line 551 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_cvttpd_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttpd_epu64 (__m256d __A) static
Definition at line 593 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_cvttps_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttps_epi64 (__m128 __A) static
Definition at line 635 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_cvttps_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_cvttps_epu64 (__m128 __A) static
Definition at line 677 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_mask_and_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_and_pd (__m256d __W, __mmask8 __U, __m256d __A, __m256d __B) static
Definition at line 116 of file avx512vldqintrin.h.
References _mm256_and_pd().
_mm256_mask_and_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_and_ps (__m256 __W, __mmask8 __U, __m256 __A, __m256 __B) static
Definition at line 144 of file avx512vldqintrin.h.
References _mm256_and_ps().
_mm256_mask_andnot_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_andnot_pd (__m256d __W, __mmask8 __U, __m256d __A, __m256d __B) static
Definition at line 60 of file avx512vldqintrin.h.
References _mm256_andnot_pd().
_mm256_mask_andnot_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_andnot_ps (__m256 __W, __mmask8 __U, __m256 __A, __m256 __B) static
Definition at line 88 of file avx512vldqintrin.h.
References _mm256_andnot_ps().
_mm256_mask_broadcast_f32x2()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_broadcast_f32x2 (__m256 __O, __mmask8 __M, __m128 __A) static
Definition at line 961 of file avx512vldqintrin.h.
References _mm256_broadcast_f32x2().
_mm256_mask_broadcast_f64x2()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_broadcast_f64x2 (__m256d __O, __mmask8 __M, __m128d __A) static
Definition at line 984 of file avx512vldqintrin.h.
References _mm256_broadcast_f64x2().
_mm256_mask_broadcast_i32x2()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_broadcast_i32x2 (__m256i __O, __mmask8 __M, __m128i __A) static
Definition at line 1030 of file avx512vldqintrin.h.
References _mm256_broadcast_i32x2().
_mm256_mask_broadcast_i64x2()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_broadcast_i64x2 (__m256i __O, __mmask8 __M, __m128i __A) static
Definition at line 1053 of file avx512vldqintrin.h.
References _mm256_broadcast_i64x2().
_mm256_mask_cvtepi64_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi64_pd (__m256d __W, __mmask8 __U, __m256i __A) static
Definition at line 476 of file avx512vldqintrin.h.
References _mm256_cvtepi64_pd().
_mm256_mask_cvtepi64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepi64_ps (__m128 __W, __mmask8 __U, __m256i __A) static
Definition at line 516 of file avx512vldqintrin.h.
References _mm256_cvtepi64_ps().
_mm256_mask_cvtepu64_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu64_pd (__m256d __W, __mmask8 __U, __m256i __A) static
Definition at line 722 of file avx512vldqintrin.h.
References _mm256_cvtepu64_pd().
_mm256_mask_cvtepu64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_mask_cvtepu64_ps (__m128 __W, __mmask8 __U, __m256i __A) static
Definition at line 762 of file avx512vldqintrin.h.
References _mm256_cvtepu64_ps().
_mm256_mask_cvtpd_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtpd_epi64 (__m256i __W, __mmask8 __U, __m256d __A) static
Definition at line 312 of file avx512vldqintrin.h.
_mm256_mask_cvtpd_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtpd_epu64 (__m256i __W, __mmask8 __U, __m256d __A) static
Definition at line 354 of file avx512vldqintrin.h.
_mm256_mask_cvtps_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtps_epi64 (__m256i __W, __mmask8 __U, __m128 __A) static
Definition at line 396 of file avx512vldqintrin.h.
_mm256_mask_cvtps_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvtps_epu64 (__m256i __W, __mmask8 __U, __m128 __A) static
Definition at line 438 of file avx512vldqintrin.h.
_mm256_mask_cvttpd_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttpd_epi64 (__m256i __W, __mmask8 __U, __m256d __A) static
Definition at line 558 of file avx512vldqintrin.h.
_mm256_mask_cvttpd_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttpd_epu64 (__m256i __W, __mmask8 __U, __m256d __A) static
Definition at line 600 of file avx512vldqintrin.h.
_mm256_mask_cvttps_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttps_epi64 (__m256i __W, __mmask8 __U, __m128 __A) static
Definition at line 642 of file avx512vldqintrin.h.
_mm256_mask_cvttps_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_cvttps_epu64 (__m256i __W, __mmask8 __U, __m128 __A) static
Definition at line 684 of file avx512vldqintrin.h.
_mm256_mask_mullo_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_mullo_epi64 (__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) static
Definition at line 27 of file avx512vldqintrin.h.
References _mm256_mullo_epi64().
_mm256_mask_or_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_or_pd (__m256d __W, __mmask8 __U, __m256d __A, __m256d __B) static
Definition at line 228 of file avx512vldqintrin.h.
References _mm256_or_pd().
_mm256_mask_or_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_or_ps (__m256 __W, __mmask8 __U, __m256 __A, __m256 __B) static
Definition at line 256 of file avx512vldqintrin.h.
References _mm256_or_ps().
_mm256_mask_xor_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_mask_xor_pd (__m256d __W, __mmask8 __U, __m256d __A, __m256d __B) static
Definition at line 172 of file avx512vldqintrin.h.
References _mm256_xor_pd().
_mm256_mask_xor_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_mask_xor_ps (__m256 __W, __mmask8 __U, __m256 __A, __m256 __B) static
Definition at line 200 of file avx512vldqintrin.h.
References _mm256_xor_ps().
_mm256_maskz_and_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_and_pd (__mmask8 __U, __m256d __A, __m256d __B) static
Definition at line 123 of file avx512vldqintrin.h.
References _mm256_and_pd(), and _mm256_setzero_pd().
_mm256_maskz_and_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_and_ps (__mmask8 __U, __m256 __A, __m256 __B) static
Definition at line 151 of file avx512vldqintrin.h.
References _mm256_and_ps(), and _mm256_setzero_ps().
_mm256_maskz_andnot_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_andnot_pd (__mmask8 __U, __m256d __A, __m256d __B) static
Definition at line 67 of file avx512vldqintrin.h.
References _mm256_andnot_pd(), and _mm256_setzero_pd().
_mm256_maskz_andnot_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_andnot_ps (__mmask8 __U, __m256 __A, __m256 __B) static
Definition at line 95 of file avx512vldqintrin.h.
References _mm256_andnot_ps(), and _mm256_setzero_ps().
_mm256_maskz_broadcast_f32x2()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcast_f32x2 (__mmask8 __M, __m128 __A) static
Definition at line 969 of file avx512vldqintrin.h.
References _mm256_broadcast_f32x2(), and _mm256_setzero_ps().
_mm256_maskz_broadcast_f64x2()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcast_f64x2 (__mmask8 __M, __m128d __A) static
Definition at line 992 of file avx512vldqintrin.h.
References _mm256_broadcast_f64x2(), and _mm256_setzero_pd().
_mm256_maskz_broadcast_i32x2()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcast_i32x2 (__mmask8 __M, __m128i __A) static
Definition at line 1038 of file avx512vldqintrin.h.
References _mm256_broadcast_i32x2(), and _mm256_setzero_si256().
_mm256_maskz_broadcast_i64x2()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_broadcast_i64x2 (__mmask8 __M, __m128i __A) static
Definition at line 1061 of file avx512vldqintrin.h.
References _mm256_broadcast_i64x2(), and _mm256_setzero_si256().
_mm256_maskz_cvtepi64_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi64_pd (__mmask8 __U, __m256i __A) static
Definition at line 483 of file avx512vldqintrin.h.
References _mm256_cvtepi64_pd(), and _mm256_setzero_pd().
_mm256_maskz_cvtepi64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepi64_ps (__mmask8 __U, __m256i __A) static
Definition at line 523 of file avx512vldqintrin.h.
References _mm256_cvtepi64_ps(), and _mm_setzero_ps().
_mm256_maskz_cvtepu64_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu64_pd (__mmask8 __U, __m256i __A) static
Definition at line 729 of file avx512vldqintrin.h.
References _mm256_cvtepu64_pd(), and _mm256_setzero_pd().
_mm256_maskz_cvtepu64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtepu64_ps (__mmask8 __U, __m256i __A) static
Definition at line 769 of file avx512vldqintrin.h.
References _mm256_cvtepu64_ps(), and _mm_setzero_ps().
_mm256_maskz_cvtpd_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtpd_epi64 (__mmask8 __U, __m256d __A) static
Definition at line 319 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtpd_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtpd_epu64 (__mmask8 __U, __m256d __A) static
Definition at line 361 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtps_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtps_epi64 (__mmask8 __U, __m128 __A) static
Definition at line 403 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvtps_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvtps_epu64 (__mmask8 __U, __m128 __A) static
Definition at line 445 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttpd_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttpd_epi64 (__mmask8 __U, __m256d __A) static
Definition at line 565 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttpd_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttpd_epu64 (__mmask8 __U, __m256d __A) static
Definition at line 607 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttps_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttps_epi64 (__mmask8 __U, __m128 __A) static
Definition at line 649 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_maskz_cvttps_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_cvttps_epu64 (__mmask8 __U, __m128 __A) static
Definition at line 691 of file avx512vldqintrin.h.
References _mm256_setzero_si256().
_mm256_maskz_mullo_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_mullo_epi64 (__mmask8 __U, __m256i __A, __m256i __B) static
Definition at line 34 of file avx512vldqintrin.h.
References _mm256_mullo_epi64(), and _mm256_setzero_si256().
_mm256_maskz_or_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_or_pd (__mmask8 __U, __m256d __A, __m256d __B) static
Definition at line 235 of file avx512vldqintrin.h.
References _mm256_or_pd(), and _mm256_setzero_pd().
_mm256_maskz_or_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_or_ps (__mmask8 __U, __m256 __A, __m256 __B) static
Definition at line 263 of file avx512vldqintrin.h.
References _mm256_or_ps(), and _mm256_setzero_ps().
_mm256_maskz_xor_pd()
static __inline__ __m256d __DEFAULT_FN_ATTRS256 _mm256_maskz_xor_pd (__mmask8 __U, __m256d __A, __m256d __B) static
Definition at line 179 of file avx512vldqintrin.h.
References _mm256_setzero_pd(), and _mm256_xor_pd().
_mm256_maskz_xor_ps()
static __inline__ __m256 __DEFAULT_FN_ATTRS256 _mm256_maskz_xor_ps (__mmask8 __U, __m256 __A, __m256 __B) static
Definition at line 207 of file avx512vldqintrin.h.
References _mm256_setzero_ps(), and _mm256_xor_ps().
_mm256_movepi32_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS256 _mm256_movepi32_mask (__m256i __A) static
Definition at line 912 of file avx512vldqintrin.h.
_mm256_movepi64_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS256 _mm256_movepi64_mask (__m256i __A) static
Definition at line 948 of file avx512vldqintrin.h.
_mm256_movm_epi32()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_movm_epi32 (__mmask8 __A) static
Definition at line 924 of file avx512vldqintrin.h.
_mm256_movm_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_movm_epi64 (__mmask8 __A) static
Definition at line 936 of file avx512vldqintrin.h.
_mm256_mullo_epi64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mullo_epi64 (__m256i __A, __m256i __B) static
Definition at line 22 of file avx512vldqintrin.h.
Referenced by _mm256_mask_mullo_epi64(), and _mm256_maskz_mullo_epi64().
_mm_broadcast_i32x2()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_broadcast_i32x2 (__m128i __A) static
Definition at line 1000 of file avx512vldqintrin.h.
Referenced by _mm_mask_broadcast_i32x2(), and _mm_maskz_broadcast_i32x2().
_mm_cvtepi64_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_cvtepi64_pd (__m128i __A) static
Definition at line 452 of file avx512vldqintrin.h.
Referenced by _mm_mask_cvtepi64_pd(), and _mm_maskz_cvtepi64_pd().
_mm_cvtepi64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_cvtepi64_ps (__m128i __A) static
Definition at line 490 of file avx512vldqintrin.h.
References _mm_setzero_ps().
_mm_cvtepu64_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_cvtepu64_pd (__m128i __A) static
Definition at line 698 of file avx512vldqintrin.h.
Referenced by _mm_mask_cvtepu64_pd(), and _mm_maskz_cvtepu64_pd().
_mm_cvtepu64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_cvtepu64_ps (__m128i __A) static
Definition at line 736 of file avx512vldqintrin.h.
References _mm_setzero_ps().
_mm_cvtpd_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtpd_epi64 (__m128d __A) static
Definition at line 284 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_cvtpd_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtpd_epu64 (__m128d __A) static
Definition at line 326 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_cvtps_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtps_epi64 (__m128 __A) static
Definition at line 368 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_cvtps_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvtps_epu64 (__m128 __A) static
Definition at line 410 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_cvttpd_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttpd_epi64 (__m128d __A) static
Definition at line 530 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_cvttpd_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttpd_epu64 (__m128d __A) static
Definition at line 572 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_cvttps_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttps_epi64 (__m128 __A) static
Definition at line 614 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_cvttps_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_cvttps_epu64 (__m128 __A) static
Definition at line 656 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_mask_and_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_and_pd (__m128d __W, __mmask8 __U, __m128d __A, __m128d __B) static
Definition at line 130 of file avx512vldqintrin.h.
References _mm_and_pd().
_mm_mask_and_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_and_ps (__m128 __W, __mmask8 __U, __m128 __A, __m128 __B) static
Definition at line 158 of file avx512vldqintrin.h.
References _mm_and_ps().
_mm_mask_andnot_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_andnot_pd (__m128d __W, __mmask8 __U, __m128d __A, __m128d __B) static
Definition at line 74 of file avx512vldqintrin.h.
References _mm_andnot_pd().
_mm_mask_andnot_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_andnot_ps (__m128 __W, __mmask8 __U, __m128 __A, __m128 __B) static
Definition at line 102 of file avx512vldqintrin.h.
References _mm_andnot_ps().
_mm_mask_broadcast_i32x2()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_broadcast_i32x2 (__m128i __O, __mmask8 __M, __m128i __A) static
Definition at line 1007 of file avx512vldqintrin.h.
References _mm_broadcast_i32x2().
_mm_mask_cvtepi64_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi64_pd (__m128d __W, __mmask8 __U, __m128i __A) static
Definition at line 457 of file avx512vldqintrin.h.
References _mm_cvtepi64_pd().
_mm_mask_cvtepi64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_cvtepi64_ps (__m128 __W, __mmask8 __U, __m128i __A) static
Definition at line 497 of file avx512vldqintrin.h.
_mm_mask_cvtepu64_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu64_pd (__m128d __W, __mmask8 __U, __m128i __A) static
Definition at line 703 of file avx512vldqintrin.h.
References _mm_cvtepu64_pd().
_mm_mask_cvtepu64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_cvtepu64_ps (__m128 __W, __mmask8 __U, __m128i __A) static
Definition at line 743 of file avx512vldqintrin.h.
_mm_mask_cvtpd_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtpd_epi64 (__m128i __W, __mmask8 __U, __m128d __A) static
Definition at line 291 of file avx512vldqintrin.h.
_mm_mask_cvtpd_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtpd_epu64 (__m128i __W, __mmask8 __U, __m128d __A) static
Definition at line 333 of file avx512vldqintrin.h.
_mm_mask_cvtps_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtps_epi64 (__m128i __W, __mmask8 __U, __m128 __A) static
Definition at line 375 of file avx512vldqintrin.h.
_mm_mask_cvtps_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvtps_epu64 (__m128i __W, __mmask8 __U, __m128 __A) static
Definition at line 417 of file avx512vldqintrin.h.
_mm_mask_cvttpd_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttpd_epi64 (__m128i __W, __mmask8 __U, __m128d __A) static
Definition at line 537 of file avx512vldqintrin.h.
_mm_mask_cvttpd_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttpd_epu64 (__m128i __W, __mmask8 __U, __m128d __A) static
Definition at line 579 of file avx512vldqintrin.h.
_mm_mask_cvttps_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttps_epi64 (__m128i __W, __mmask8 __U, __m128 __A) static
Definition at line 621 of file avx512vldqintrin.h.
_mm_mask_cvttps_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_cvttps_epu64 (__m128i __W, __mmask8 __U, __m128 __A) static
Definition at line 663 of file avx512vldqintrin.h.
_mm_mask_mullo_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_mullo_epi64 (__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 46 of file avx512vldqintrin.h.
References _mm_mullo_epi64().
_mm_mask_or_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_or_pd (__m128d __W, __mmask8 __U, __m128d __A, __m128d __B) static
Definition at line 242 of file avx512vldqintrin.h.
References _mm_or_pd().
_mm_mask_or_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_or_ps (__m128 __W, __mmask8 __U, __m128 __A, __m128 __B) static
Definition at line 270 of file avx512vldqintrin.h.
References _mm_or_ps().
_mm_mask_xor_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_mask_xor_pd (__m128d __W, __mmask8 __U, __m128d __A, __m128d __B) static
Definition at line 186 of file avx512vldqintrin.h.
References _mm_xor_pd().
_mm_mask_xor_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_mask_xor_ps (__m128 __W, __mmask8 __U, __m128 __A, __m128 __B) static
Definition at line 214 of file avx512vldqintrin.h.
References _mm_xor_ps().
_mm_maskz_and_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_and_pd (__mmask8 __U, __m128d __A, __m128d __B) static
Definition at line 137 of file avx512vldqintrin.h.
References _mm_and_pd(), and _mm_setzero_pd().
_mm_maskz_and_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_and_ps (__mmask8 __U, __m128 __A, __m128 __B) static
Definition at line 165 of file avx512vldqintrin.h.
References _mm_and_ps(), and _mm_setzero_ps().
_mm_maskz_andnot_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_andnot_pd (__mmask8 __U, __m128d __A, __m128d __B) static
Definition at line 81 of file avx512vldqintrin.h.
References _mm_andnot_pd(), and _mm_setzero_pd().
_mm_maskz_andnot_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_andnot_ps (__mmask8 __U, __m128 __A, __m128 __B) static
Definition at line 109 of file avx512vldqintrin.h.
References _mm_andnot_ps(), and _mm_setzero_ps().
_mm_maskz_broadcast_i32x2()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_broadcast_i32x2 (__mmask8 __M, __m128i __A) static
Definition at line 1015 of file avx512vldqintrin.h.
References _mm_broadcast_i32x2(), and _mm_setzero_si128().
_mm_maskz_cvtepi64_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi64_pd (__mmask8 __U, __m128i __A) static
Definition at line 464 of file avx512vldqintrin.h.
References _mm_cvtepi64_pd(), and _mm_setzero_pd().
_mm_maskz_cvtepi64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepi64_ps (__mmask8 __U, __m128i __A) static
Definition at line 504 of file avx512vldqintrin.h.
References _mm_setzero_ps().
_mm_maskz_cvtepu64_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu64_pd (__mmask8 __U, __m128i __A) static
Definition at line 710 of file avx512vldqintrin.h.
References _mm_cvtepu64_pd(), and _mm_setzero_pd().
_mm_maskz_cvtepu64_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_cvtepu64_ps (__mmask8 __U, __m128i __A) static
Definition at line 750 of file avx512vldqintrin.h.
References _mm_setzero_ps().
_mm_maskz_cvtpd_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtpd_epi64 (__mmask8 __U, __m128d __A) static
Definition at line 298 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtpd_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtpd_epu64 (__mmask8 __U, __m128d __A) static
Definition at line 340 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtps_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtps_epi64 (__mmask8 __U, __m128 __A) static
Definition at line 382 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvtps_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvtps_epu64 (__mmask8 __U, __m128 __A) static
Definition at line 424 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttpd_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttpd_epi64 (__mmask8 __U, __m128d __A) static
Definition at line 544 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttpd_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttpd_epu64 (__mmask8 __U, __m128d __A) static
Definition at line 586 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttps_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttps_epi64 (__mmask8 __U, __m128 __A) static
Definition at line 628 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_maskz_cvttps_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_cvttps_epu64 (__mmask8 __U, __m128 __A) static
Definition at line 670 of file avx512vldqintrin.h.
References _mm_setzero_si128().
_mm_maskz_mullo_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_mullo_epi64 (__mmask8 __U, __m128i __A, __m128i __B) static
Definition at line 53 of file avx512vldqintrin.h.
References _mm_mullo_epi64(), and _mm_setzero_si128().
_mm_maskz_or_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_or_pd (__mmask8 __U, __m128d __A, __m128d __B) static
Definition at line 249 of file avx512vldqintrin.h.
References _mm_or_pd(), and _mm_setzero_pd().
_mm_maskz_or_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_or_ps (__mmask8 __U, __m128 __A, __m128 __B) static
Definition at line 277 of file avx512vldqintrin.h.
References _mm_or_ps(), and _mm_setzero_ps().
_mm_maskz_xor_pd()
static __inline__ __m128d __DEFAULT_FN_ATTRS128 _mm_maskz_xor_pd (__mmask8 __U, __m128d __A, __m128d __B) static
Definition at line 193 of file avx512vldqintrin.h.
References _mm_setzero_pd(), and _mm_xor_pd().
_mm_maskz_xor_ps()
static __inline__ __m128 __DEFAULT_FN_ATTRS128 _mm_maskz_xor_ps (__mmask8 __U, __m128 __A, __m128 __B) static
Definition at line 221 of file avx512vldqintrin.h.
References _mm_setzero_ps(), and _mm_xor_ps().
_mm_movepi32_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_movepi32_mask (__m128i __A) static
Definition at line 906 of file avx512vldqintrin.h.
_mm_movepi64_mask()
static __inline__ __mmask8 __DEFAULT_FN_ATTRS128 _mm_movepi64_mask (__m128i __A) static
Definition at line 942 of file avx512vldqintrin.h.
_mm_movm_epi32()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_movm_epi32 (__mmask8 __A) static
Definition at line 918 of file avx512vldqintrin.h.
_mm_movm_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_movm_epi64 (__mmask8 __A) static
Definition at line 930 of file avx512vldqintrin.h.
_mm_mullo_epi64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mullo_epi64 (__m128i __A, __m128i __B) static
Definition at line 41 of file avx512vldqintrin.h.
Referenced by _mm_mask_mullo_epi64(), and _mm_maskz_mullo_epi64().