clang: lib/Headers/avx512vbmivlintrin.h File Reference
avx512vbmivlintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vbmi,avx512vl"), __min_vector_width__(128)))
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vbmi,avx512vl"), __min_vector_width__(256)))
Functions
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_permutex2var_epi8 (__m128i __A, __m128i __I, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_permutex2var_epi8 (__m128i __A, __mmask16 __U, __m128i __I, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask2_permutex2var_epi8 (__m128i __A, __m128i __I, __mmask16 __U, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_permutex2var_epi8 (__mmask16 __U, __m128i __A, __m128i __I, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_permutex2var_epi8 (__m256i __A, __m256i __I, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_permutex2var_epi8 (__m256i __A, __mmask32 __U, __m256i __I, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask2_permutex2var_epi8 (__m256i __A, __m256i __I, __mmask32 __U, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_permutex2var_epi8 (__mmask32 __U, __m256i __A, __m256i __I, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_permutexvar_epi8 (__m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_permutexvar_epi8 (__mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_permutexvar_epi8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_permutexvar_epi8 (__m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_permutexvar_epi8 (__mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_permutexvar_epi8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_multishift_epi64_epi8 (__m128i __X, __m128i __Y)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_multishift_epi64_epi8 (__m128i __W, __mmask16 __M, __m128i __X, __m128i __Y)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_multishift_epi64_epi8 (__mmask16 __M, __m128i __X, __m128i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_multishift_epi64_epi8 (__m256i __X, __m256i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_multishift_epi64_epi8 (__m256i __W, __mmask32 __M, __m256i __X, __m256i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_multishift_epi64_epi8 (__mmask32 __M, __m256i __X, __m256i __Y)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512vbmi,avx512vl"), __min_vector_width__(128)))
Definition at line 18 of file avx512vbmivlintrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512vbmi,avx512vl"), __min_vector_width__(256)))
Definition at line 19 of file avx512vbmivlintrin.h.
Function Documentation
_mm256_mask2_permutex2var_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask2_permutex2var_epi8 (__m256i __A, __m256i __I, __mmask32 __U, __m256i __B) static
Definition at line 74 of file avx512vbmivlintrin.h.
References _mm256_permutex2var_epi8().
_mm256_mask_multishift_epi64_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_multishift_epi64_epi8 (__m256i __W, __mmask32 __M, __m256i __X, __m256i __Y) static
Definition at line 168 of file avx512vbmivlintrin.h.
References __Y, and _mm256_multishift_epi64_epi8().
_mm256_mask_permutex2var_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_permutex2var_epi8 (__m256i __A, __mmask32 __U, __m256i __I, __m256i __B) static
Definition at line 65 of file avx512vbmivlintrin.h.
References _mm256_permutex2var_epi8().
_mm256_mask_permutexvar_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_permutexvar_epi8 (__m256i __W, __mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 130 of file avx512vbmivlintrin.h.
References _mm256_permutexvar_epi8().
_mm256_maskz_multishift_epi64_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_multishift_epi64_epi8 (__mmask32 __M, __m256i __X, __m256i __Y) static
Definition at line 177 of file avx512vbmivlintrin.h.
References __Y, _mm256_multishift_epi64_epi8(), and _mm256_setzero_si256().
_mm256_maskz_permutex2var_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_permutex2var_epi8 (__mmask32 __U, __m256i __A, __m256i __I, __m256i __B) static
Definition at line 83 of file avx512vbmivlintrin.h.
References _mm256_permutex2var_epi8(), and _mm256_setzero_si256().
_mm256_maskz_permutexvar_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_permutexvar_epi8 (__mmask32 __M, __m256i __A, __m256i __B) static
Definition at line 121 of file avx512vbmivlintrin.h.
References _mm256_permutexvar_epi8(), and _mm256_setzero_si256().
_mm256_multishift_epi64_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_multishift_epi64_epi8 (__m256i __X, __m256i __Y) static
Definition at line 162 of file avx512vbmivlintrin.h.
References __Y.
Referenced by _mm256_mask_multishift_epi64_epi8(), and _mm256_maskz_multishift_epi64_epi8().
_mm256_permutex2var_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_permutex2var_epi8 (__m256i __A, __m256i __I, __m256i __B) static
Definition at line 58 of file avx512vbmivlintrin.h.
Referenced by _mm256_mask2_permutex2var_epi8(), _mm256_mask_permutex2var_epi8(), and _mm256_maskz_permutex2var_epi8().
_mm256_permutexvar_epi8()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_permutexvar_epi8 (__m256i __A, __m256i __B) static
Definition at line 115 of file avx512vbmivlintrin.h.
Referenced by _mm256_mask_permutexvar_epi8(), and _mm256_maskz_permutexvar_epi8().
_mm_mask2_permutex2var_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask2_permutex2var_epi8 (__m128i __A, __m128i __I, __mmask16 __U, __m128i __B) static
Definition at line 40 of file avx512vbmivlintrin.h.
References _mm_permutex2var_epi8().
_mm_mask_multishift_epi64_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_multishift_epi64_epi8 (__m128i __W, __mmask16 __M, __m128i __X, __m128i __Y) static
Definition at line 145 of file avx512vbmivlintrin.h.
References __Y, and _mm_multishift_epi64_epi8().
_mm_mask_permutex2var_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_permutex2var_epi8 (__m128i __A, __mmask16 __U, __m128i __I, __m128i __B) static
Definition at line 31 of file avx512vbmivlintrin.h.
References _mm_permutex2var_epi8().
_mm_mask_permutexvar_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_permutexvar_epi8 (__m128i __W, __mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 106 of file avx512vbmivlintrin.h.
References _mm_permutexvar_epi8().
_mm_maskz_multishift_epi64_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_multishift_epi64_epi8 (__mmask16 __M, __m128i __X, __m128i __Y) static
Definition at line 154 of file avx512vbmivlintrin.h.
References __Y, _mm_multishift_epi64_epi8(), and _mm_setzero_si128().
_mm_maskz_permutex2var_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_permutex2var_epi8 (__mmask16 __U, __m128i __A, __m128i __I, __m128i __B) static
Definition at line 49 of file avx512vbmivlintrin.h.
References _mm_permutex2var_epi8(), and _mm_setzero_si128().
_mm_maskz_permutexvar_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_permutexvar_epi8 (__mmask16 __M, __m128i __A, __m128i __B) static
Definition at line 98 of file avx512vbmivlintrin.h.
References _mm_permutexvar_epi8(), and _mm_setzero_si128().
_mm_multishift_epi64_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_multishift_epi64_epi8 (__m128i __X, __m128i __Y) static
Definition at line 139 of file avx512vbmivlintrin.h.
References __Y.
Referenced by _mm_mask_multishift_epi64_epi8(), and _mm_maskz_multishift_epi64_epi8().
_mm_permutex2var_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_permutex2var_epi8 (__m128i __A, __m128i __I, __m128i __B) static
Definition at line 23 of file avx512vbmivlintrin.h.
Referenced by _mm_mask2_permutex2var_epi8(), _mm_mask_permutex2var_epi8(), and _mm_maskz_permutex2var_epi8().
_mm_permutexvar_epi8()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_permutexvar_epi8 (__m128i __A, __m128i __B) static
Definition at line 92 of file avx512vbmivlintrin.h.
Referenced by _mm_mask_permutexvar_epi8(), and _mm_maskz_permutexvar_epi8().