clang: lib/Headers/avx512ifmavlintrin.h File Reference
avx512ifmavlintrin.h File Reference
Macros
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512ifma,avx512vl"), __min_vector_width__(128)))
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512ifma,avx512vl"), __min_vector_width__(256)))
Functions
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_madd52hi_epu64 (__m128i __X, __m128i __Y, __m128i __Z)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_madd52hi_epu64 (__m128i __W, __mmask8 __M, __m128i __X, __m128i __Y)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_madd52hi_epu64 (__mmask8 __M, __m128i __X, __m128i __Y, __m128i __Z)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_madd52hi_epu64 (__m256i __X, __m256i __Y, __m256i __Z)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_madd52hi_epu64 (__m256i __W, __mmask8 __M, __m256i __X, __m256i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_madd52hi_epu64 (__mmask8 __M, __m256i __X, __m256i __Y, __m256i __Z)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_madd52lo_epu64 (__m128i __X, __m128i __Y, __m128i __Z)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_madd52lo_epu64 (__m128i __W, __mmask8 __M, __m128i __X, __m128i __Y)
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_madd52lo_epu64 (__mmask8 __M, __m128i __X, __m128i __Y, __m128i __Z)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_madd52lo_epu64 (__m256i __X, __m256i __Y, __m256i __Z)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_madd52lo_epu64 (__m256i __W, __mmask8 __M, __m256i __X, __m256i __Y)
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_madd52lo_epu64 (__mmask8 __M, __m256i __X, __m256i __Y, __m256i __Z)
Macro Definition Documentation
__DEFAULT_FN_ATTRS128
#define __DEFAULT_FN_ATTRS128 __attribute__((__always_inline__, __nodebug__, __target__("avx512ifma,avx512vl"), __min_vector_width__(128)))
Definition at line 18 of file avx512ifmavlintrin.h.
__DEFAULT_FN_ATTRS256
#define __DEFAULT_FN_ATTRS256 __attribute__((__always_inline__, __nodebug__, __target__("avx512ifma,avx512vl"), __min_vector_width__(256)))
Definition at line 19 of file avx512ifmavlintrin.h.
Function Documentation
_mm256_madd52hi_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_madd52hi_epu64 (__m256i __X, __m256i __Y, __m256i __Z) static
Definition at line 47 of file avx512ifmavlintrin.h.
References __Y.
Referenced by _mm256_mask_madd52hi_epu64(), and _mm256_maskz_madd52hi_epu64().
_mm256_madd52lo_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_madd52lo_epu64 (__m256i __X, __m256i __Y, __m256i __Z) static
Definition at line 93 of file avx512ifmavlintrin.h.
References __Y.
Referenced by _mm256_mask_madd52lo_epu64(), and _mm256_maskz_madd52lo_epu64().
_mm256_mask_madd52hi_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_madd52hi_epu64 (__m256i __W, __mmask8 __M, __m256i __X, __m256i __Y) static
Definition at line 54 of file avx512ifmavlintrin.h.
References __Y, and _mm256_madd52hi_epu64().
_mm256_mask_madd52lo_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_mask_madd52lo_epu64 (__m256i __W, __mmask8 __M, __m256i __X, __m256i __Y) static
Definition at line 100 of file avx512ifmavlintrin.h.
References __Y, and _mm256_madd52lo_epu64().
_mm256_maskz_madd52hi_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_madd52hi_epu64 (__mmask8 __M, __m256i __X, __m256i __Y, __m256i __Z) static
Definition at line 62 of file avx512ifmavlintrin.h.
References __Y, _mm256_madd52hi_epu64(), and _mm256_setzero_si256().
_mm256_maskz_madd52lo_epu64()
static __inline__ __m256i __DEFAULT_FN_ATTRS256 _mm256_maskz_madd52lo_epu64 (__mmask8 __M, __m256i __X, __m256i __Y, __m256i __Z) static
Definition at line 108 of file avx512ifmavlintrin.h.
References __Y, _mm256_madd52lo_epu64(), and _mm256_setzero_si256().
_mm_madd52hi_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_madd52hi_epu64 (__m128i __X, __m128i __Y, __m128i __Z) static
Definition at line 24 of file avx512ifmavlintrin.h.
References __Y.
Referenced by _mm_mask_madd52hi_epu64(), and _mm_maskz_madd52hi_epu64().
_mm_madd52lo_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_madd52lo_epu64 (__m128i __X, __m128i __Y, __m128i __Z) static
Definition at line 70 of file avx512ifmavlintrin.h.
References __Y.
Referenced by _mm_mask_madd52lo_epu64(), and _mm_maskz_madd52lo_epu64().
_mm_mask_madd52hi_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_madd52hi_epu64 (__m128i __W, __mmask8 __M, __m128i __X, __m128i __Y) static
Definition at line 31 of file avx512ifmavlintrin.h.
References __Y, and _mm_madd52hi_epu64().
_mm_mask_madd52lo_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_mask_madd52lo_epu64 (__m128i __W, __mmask8 __M, __m128i __X, __m128i __Y) static
Definition at line 77 of file avx512ifmavlintrin.h.
References __Y, and _mm_madd52lo_epu64().
_mm_maskz_madd52hi_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_madd52hi_epu64 (__mmask8 __M, __m128i __X, __m128i __Y, __m128i __Z) static
Definition at line 39 of file avx512ifmavlintrin.h.
References __Y, _mm_madd52hi_epu64(), and _mm_setzero_si128().
_mm_maskz_madd52lo_epu64()
static __inline__ __m128i __DEFAULT_FN_ATTRS128 _mm_maskz_madd52lo_epu64 (__mmask8 __M, __m128i __X, __m128i __Y, __m128i __Z) static
Definition at line 85 of file avx512ifmavlintrin.h.
References __Y, _mm_madd52lo_epu64(), and _mm_setzero_si128().