clang: lib/CodeGen/BackendUtil.cpp File Reference
BackendUtil.cpp File Reference
#include "clang/CodeGen/BackendUtil.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/TargetOptions.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "clang/Frontend/Utils.h"
#include "clang/Lex/HeaderSearchOptions.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/StackSafetyAnalysis.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/Bitcode/BitcodeWriterPass.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/CodeGen/SchedulerRegistry.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/LTO/LTOBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Passes/PassPlugin.h"
#include "llvm/Passes/StandardInstrumentations.h"
#include "llvm/SYCLLowerIR/ESIMD/ESIMDVerifier.h"
#include "llvm/SYCLLowerIR/LowerWGLocalMemory.h"
#include "llvm/SYCLLowerIR/MutatePrintfAddrspace.h"
#include "llvm/Support/BuryPointer.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/Coroutines.h"
#include "llvm/Transforms/Coroutines/CoroCleanup.h"
#include "llvm/Transforms/Coroutines/CoroEarly.h"
#include "llvm/Transforms/Coroutines/CoroElide.h"
#include "llvm/Transforms/Coroutines/CoroSplit.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/AlwaysInliner.h"
#include "llvm/Transforms/IPO/LowerTypeTests.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/IPO/ThinLTOBitcodeWriter.h"
#include "llvm/Transforms/InstCombine/InstCombine.h"
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/Transforms/Instrumentation/AddressSanitizer.h"
#include "llvm/Transforms/Instrumentation/AddressSanitizerOptions.h"
#include "llvm/Transforms/Instrumentation/BoundsChecking.h"
#include "llvm/Transforms/Instrumentation/DataFlowSanitizer.h"
#include "llvm/Transforms/Instrumentation/GCOVProfiler.h"
#include "llvm/Transforms/Instrumentation/HWAddressSanitizer.h"
#include "llvm/Transforms/Instrumentation/InstrProfiling.h"
#include "llvm/Transforms/Instrumentation/MemProfiler.h"
#include "llvm/Transforms/Instrumentation/MemorySanitizer.h"
#include "llvm/Transforms/Instrumentation/SPIRITTAnnotations.h"
#include "llvm/Transforms/Instrumentation/SanitizerCoverage.h"
#include "llvm/Transforms/Instrumentation/ThreadSanitizer.h"
#include "llvm/Transforms/ObjCARC.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/EarlyCSE.h"
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/Transforms/Scalar/LowerMatrixIntrinsics.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/CanonicalizeAliases.h"
#include "llvm/Transforms/Utils/Debugify.h"
#include "llvm/Transforms/Utils/EntryExitInstrumenter.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include "llvm/Transforms/Utils/NameAnonGlobals.h"
#include "llvm/Transforms/Utils/SymbolRewriter.h"
#include <memory>
#include "llvm/Support/Extension.def"
Namespaces
llvm
YAML serialization mapping.
Macros
#define HANDLE_EXTENSION(Ext) llvm::PassPluginLibraryInfo get##Ext##PluginInfo();
#define HANDLE_EXTENSION(Ext) get##Ext##PluginInfo().RegisterPassBuilderCallbacks(PB);
Functions
static void addObjCARCAPElimPass (const PassManagerBuilder &Builder, PassManagerBase &PM)
static void addObjCARCExpandPass (const PassManagerBuilder &Builder, PassManagerBase &PM)
static void addObjCARCOptPass (const PassManagerBuilder &Builder, PassManagerBase &PM)
static void addAddDiscriminatorsPass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addBoundsCheckingPass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static SanitizerCoverageOptions getSancovOptsFromCGOpts (const CodeGenOptions &CGOpts)
static void addSanitizerCoveragePass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static bool asanUseGlobalsGC (const Triple &T, const CodeGenOptions &CGOpts)
static void addMemProfilerPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addAddressSanitizerPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addKernelAddressSanitizerPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addHWAddressSanitizerPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addKernelHWAddressSanitizerPasses (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addGeneralOptsForMemorySanitizer (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM, bool CompileKernel)
static void addMemorySanitizerPass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addKernelMemorySanitizerPass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addThreadSanitizerPass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addDataFlowSanitizerPass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addEntryExitInstrumentationPass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static void addPostInlineEntryExitInstrumentationPass (const PassManagerBuilder &Builder, legacy::PassManagerBase &PM)
static TargetLibraryInfoImpl * createTLII (llvm::Triple &TargetTriple, const CodeGenOptions &CodeGenOpts)
static void addSymbolRewriterPass (const CodeGenOptions &Opts, legacy::PassManager *MPM)
static CodeGenOpt::Level getCGOptLevel (const CodeGenOptions &CodeGenOpts)
static Optional< llvm::CodeModel::Model > getCodeModel (const CodeGenOptions &CodeGenOpts)
static CodeGenFileType getCodeGenFileType (BackendAction Action)
static bool actionRequiresCodeGen (BackendAction Action)
static bool initTargetOptions (DiagnosticsEngine &Diags, llvm::TargetOptions &Options, const CodeGenOptions &CodeGenOpts, const clang::TargetOptions &TargetOpts, const LangOptions &LangOpts, const HeaderSearchOptions &HSOpts)
static Optional< GCOVOptions > getGCOVOptions (const CodeGenOptions &CodeGenOpts, const LangOptions &LangOpts)
static Optional< InstrProfOptions > getInstrProfOptions (const CodeGenOptions &CodeGenOpts, const LangOptions &LangOpts)
static void setCommandLineOpts (const CodeGenOptions &CodeGenOpts)
static OptimizationLevel mapToLevel (const CodeGenOptions &Opts)
static void addSanitizers (const Triple &TargetTriple, const CodeGenOptions &CodeGenOpts, const LangOptions &LangOpts, PassBuilder &PB)
static void runThinLTOBackend (DiagnosticsEngine &Diags, ModuleSummaryIndex *CombinedIndex, Module *M, const HeaderSearchOptions &HeaderOpts, const CodeGenOptions &CGOpts, const clang::TargetOptions &TOpts, const LangOptions &LOpts, std::unique_ptr< raw_pwrite_stream > OS, std::string SampleProfile, std::string ProfileRemapping, BackendAction Action)
Variables
cl::opt< bool > llvm::DebugInfoCorrelate
Macro Definition Documentation
HANDLE_EXTENSION [1/2]
#define HANDLE_EXTENSION (Ext) llvm::PassPluginLibraryInfo get##Ext##PluginInfo();
Definition at line 98 of file BackendUtil.cpp.
HANDLE_EXTENSION [2/2]
#define HANDLE_EXTENSION (Ext) get##Ext##PluginInfo().RegisterPassBuilderCallbacks(PB);
Definition at line 98 of file BackendUtil.cpp.
Function Documentation
actionRequiresCodeGen()
static bool actionRequiresCodeGen (BackendAction Action) static
Definition at line 503 of file BackendUtil.cpp.
References clang::Backend_EmitBC, clang::Backend_EmitLL, and clang::Backend_EmitNothing.
addAddDiscriminatorsPass()
static void addAddDiscriminatorsPass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 232 of file BackendUtil.cpp.
addAddressSanitizerPasses()
static void addAddressSanitizerPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 306 of file BackendUtil.cpp.
addBoundsCheckingPass()
static void addBoundsCheckingPass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 237 of file BackendUtil.cpp.
addDataFlowSanitizerPass()
static void addDataFlowSanitizerPass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 397 of file BackendUtil.cpp.
addEntryExitInstrumentationPass()
static void addEntryExitInstrumentationPass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 405 of file BackendUtil.cpp.
addGeneralOptsForMemorySanitizer()
static void addGeneralOptsForMemorySanitizer (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM, bool CompileKernel) static
Definition at line 357 of file BackendUtil.cpp.
addHWAddressSanitizerPasses()
static void addHWAddressSanitizerPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 336 of file BackendUtil.cpp.
addKernelAddressSanitizerPasses()
static void addKernelAddressSanitizerPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 326 of file BackendUtil.cpp.
addKernelHWAddressSanitizerPasses()
static void addKernelHWAddressSanitizerPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 347 of file BackendUtil.cpp.
addKernelMemorySanitizerPass()
static void addKernelMemorySanitizerPass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 387 of file BackendUtil.cpp.
addMemorySanitizerPass()
static void addMemorySanitizerPass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 382 of file BackendUtil.cpp.
addMemProfilerPasses()
static void addMemProfilerPasses (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 300 of file BackendUtil.cpp.
addObjCARCAPElimPass()
static void addObjCARCAPElimPass (const PassManagerBuilder & Builder, PassManagerBase & PM) static
Definition at line 217 of file BackendUtil.cpp.
addObjCARCExpandPass()
static void addObjCARCExpandPass (const PassManagerBuilder & Builder, PassManagerBase & PM) static
Definition at line 222 of file BackendUtil.cpp.
addObjCARCOptPass()
static void addObjCARCOptPass (const PassManagerBuilder & Builder, PassManagerBase & PM) static
Definition at line 227 of file BackendUtil.cpp.
addPostInlineEntryExitInstrumentationPass()
static void addPostInlineEntryExitInstrumentationPass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 411 of file BackendUtil.cpp.
addSanitizerCoveragePass()
static void addSanitizerCoveragePass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 265 of file BackendUtil.cpp.
addSanitizers()
static void addSanitizers (const Triple & TargetTriple, const CodeGenOptions & CodeGenOpts, const LangOptions & LangOpts, PassBuilder & PB) static
Definition at line 1188 of file BackendUtil.cpp.
References asanUseGlobalsGC(), clang::SanitizerSet::has(), clang::CodeGenOptions::hasSanitizeCoverage(), clang::LangOptions::NoSanitizeFiles, clang::LangOptions::Sanitize, and clang::CodeGenOptions::SanitizeRecover.
addSymbolRewriterPass()
static void addSymbolRewriterPass (const CodeGenOptions & Opts, legacy::PassManager * MPM) static
Definition at line 450 of file BackendUtil.cpp.
References clang::CodeGenOptions::RewriteMapFiles.
addThreadSanitizerPass()
static void addThreadSanitizerPass (const PassManagerBuilder & Builder, legacy::PassManagerBase & PM) static
Definition at line 392 of file BackendUtil.cpp.
asanUseGlobalsGC()
static bool asanUseGlobalsGC (const Triple & T, const CodeGenOptions & CGOpts) static
Definition at line 280 of file BackendUtil.cpp.
Referenced by addSanitizers().
createTLII()
static TargetLibraryInfoImpl* createTLII (llvm::Triple & TargetTriple, const CodeGenOptions & CodeGenOpts) static
Definition at line 416 of file BackendUtil.cpp.
References clang::CodeGenOptions::Accelerate, clang::CodeGenOptions::Darwin_libsystem_m, clang::CodeGenOptions::LIBMVEC, clang::CodeGenOptions::MASSV, and clang::CodeGenOptions::SVML.
getCGOptLevel()
static CodeGenOpt::Level getCGOptLevel (const CodeGenOptions & CodeGenOpts) static
Definition at line 461 of file BackendUtil.cpp.
References clang::XRayInstrKind::None.
Referenced by runThinLTOBackend().
getCodeGenFileType()
static CodeGenFileType getCodeGenFileType (BackendAction Action) static
Definition at line 492 of file BackendUtil.cpp.
References clang::Backend_EmitAssembly, clang::Backend_EmitMCNull, and clang::Backend_EmitObj.
Referenced by runThinLTOBackend().
getCodeModel()
static Optional<llvm::CodeModel::Model> getCodeModel (const CodeGenOptions & CodeGenOpts) static
Definition at line 477 of file BackendUtil.cpp.
References clang::CodeGenOptions::CodeModel.
Referenced by runThinLTOBackend().
getGCOVOptions()
static Optional<GCOVOptions> getGCOVOptions (const CodeGenOptions & CodeGenOpts, const LangOptions & LangOpts) static
Definition at line 661 of file BackendUtil.cpp.
getInstrProfOptions()
static Optional<InstrProfOptions> getInstrProfOptions (const CodeGenOptions & CodeGenOpts, const LangOptions & LangOpts) static
Definition at line 679 of file BackendUtil.cpp.
References clang::CodeGenOptions::hasProfileClangInstr().
getSancovOptsFromCGOpts()
static SanitizerCoverageOptions getSancovOptsFromCGOpts (const CodeGenOptions & CGOpts) static
Definition at line 243 of file BackendUtil.cpp.
References Type.
initTargetOptions()
static bool initTargetOptions (DiagnosticsEngine & Diags, llvm::TargetOptions & Options, const CodeGenOptions & CodeGenOpts, const clang::TargetOptions & TargetOpts, const LangOptions & LangOpts, const HeaderSearchOptions & HSOpts) static
Definition at line 508 of file BackendUtil.cpp.
Referenced by runThinLTOBackend().
mapToLevel()
static OptimizationLevel mapToLevel (const CodeGenOptions & Opts) static
Definition at line 1157 of file BackendUtil.cpp.
runThinLTOBackend()
static void runThinLTOBackend (DiagnosticsEngine & Diags, ModuleSummaryIndex * CombinedIndex, Module * M, const HeaderSearchOptions & HeaderOpts, const CodeGenOptions & CGOpts, const clang::TargetOptions & TOpts, const LangOptions & LOpts, std::unique_ptr< raw_pwrite_stream > OS, std::string SampleProfile, std::string ProfileRemapping, BackendAction Action) static
Definition at line 1638 of file BackendUtil.cpp.
References clang::Backend_EmitBC, clang::Backend_EmitLL, clang::Backend_EmitNothing, clang::CodeGenOptions::CmdArgs, clang::TargetOptions::CPU, clang::TargetOptions::Features, getCGOptLevel(), getCodeGenFileType(), getCodeModel(), clang::CodeGenOptions::hasProfileCSIRInstr(), clang::CodeGenOptions::hasProfileCSIRUse(), initTargetOptions(), clang::CodeGenOptions::InstrProfileOutput, clang::CodeGenOptions::ObjectFilenameForDebug, clang::CodeGenOptions::OptRecordFile, clang::CodeGenOptions::OptRecordFormat, clang::CodeGenOptions::OptRecordPasses, clang::Module::print(), clang::CodeGenOptions::ProfileInstrumentUsePath, clang::CodeGenOptions::RelocationModel, clang::CodeGenOptions::SaveTempsFilePrefix, setCommandLineOpts(), clang::CodeGenOptions::SplitDwarfFile, and clang::CodeGenOptions::SplitDwarfOutput.
setCommandLineOpts()
static void setCommandLineOpts (const CodeGenOptions & CodeGenOpts) static
Definition at line 920 of file BackendUtil.cpp.
References clang::CodeGenOptions::DebugPass, and clang::CodeGenOptions::LimitFloatPrecision.
Referenced by runThinLTOBackend().