clang: lib/StaticAnalyzer/Checkers/BlockInCriticalSectionChecker.cpp File Reference
BlockInCriticalSectionChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallDescription.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramStateTrait.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState_Fwd.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include <iterator>
#include <utility>
#include <variant>
Classes
struct std::iterator_traits< typename llvm::ImmutableList< CritSectionMarker >::iterator >
Namespaces
std
Functions
static const MemRegion * getRegion (const CallEvent &Call, const MutexDescriptor &Descriptor, bool IsLock)
Function Documentation
getRegion()
static const MemRegion* getRegion (const CallEvent & Call, const MutexDescriptor & Descriptor, bool IsLock) static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 238 of file BlockInCriticalSectionChecker.cpp.
Referenced by annotateStartParameter(), clang::ento::nonloc::LazyCompoundVal::getRegion(), isArrayIndexOutOfBounds(), and clang::ento::ExprEngine::ProcessAutomaticObjDtor().