clang: lib/AST/Interp/ByteCodeExprGen.cpp File Reference
ByteCodeExprGen.cpp File Reference
#include "ByteCodeExprGen.h"
#include "ByteCodeEmitter.h"
#include "ByteCodeStmtGen.h"
#include "Context.h"
#include "Floating.h"
#include "Function.h"
#include "InterpShared.h"
#include "PrimType.h"
#include "Program.h"
#include "clang/AST/Attr.h"
Classes
class clang::interp::DeclScope< Emitter >
Scope used to handle temporaries in toplevel variable declarations.
class clang::interp::OptionScope< Emitter >
Scope used to handle initialization methods.
Namespaces
clang
The JSON file list parser is used to communicate input to InstallAPI.
clang::interp
Typedefs
using APSInt = llvm::APSInt
Functions
static CharUnits AlignOfType (QualType T, const ASTContext &ASTCtx, UnaryExprOrTypeTrait Kind)
Typedef Documentation
APSInt
using APSInt = llvm::APSInt
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 23 of file ByteCodeExprGen.cpp.
Function Documentation
AlignOfType()
static CharUnits AlignOfType (QualType T, const ASTContext & ASTCtx, UnaryExprOrTypeTrait Kind) static
Definition at line 1219 of file ByteCodeExprGen.cpp.
References clang::Type::getAs(), clang::ASTContext::getLangOpts(), clang::Type::getPointeeType(), clang::ASTContext::getPreferredTypeAlign(), clang::ASTContext::getTypeAlignInChars(), clang::CharUnits::One(), clang::T, clang::ASTContext::toCharUnitsFromBits(), and clang::LangOptionsBase::Ver7.
Referenced by clang::interp::ByteCodeExprGen< Emitter >::VisitUnaryExprOrTypeTraitExpr().