clang: lib/CodeGen/CGCleanup.cpp File Reference
CGCleanup.cpp File Reference
#include "CGCleanup.h"
#include "CodeGenFunction.h"
#include "llvm/Support/SaveAndRestore.h"
Enumerations
enum ForActivation_t { ForActivation , ForDeactivation }
Functions
static void createStoreInstBefore (llvm::Value *value, Address addr, llvm::Instruction *beforeInst, CodeGenFunction &CGF)
static llvm::LoadInst * createLoadInstBefore (Address addr, const Twine &name, llvm::Instruction *beforeInst, CodeGenFunction &CGF)
static void ResolveAllBranchFixups (CodeGenFunction &CGF, llvm::SwitchInst *Switch, llvm::BasicBlock *CleanupEntry)
All the branch fixups on the EH stack have propagated out past the outermost normal cleanup; resolve them all by adding cases to the given switch instruction.
static llvm::SwitchInst * TransitionToCleanupSwitch (CodeGenFunction &CGF, llvm::BasicBlock *Block)
Transitions the terminator of the given exit-block of a cleanup to be a cleanup switch.
static llvm::BasicBlock * CreateNormalEntry (CodeGenFunction &CGF, EHCleanupScope &Scope)
static llvm::BasicBlock * SimplifyCleanupEntry (CodeGenFunction &CGF, llvm::BasicBlock *Entry)
Attempts to reduce a cleanup's entry block to a fallthrough.
static void EmitCleanup (CodeGenFunction &CGF, EHScopeStack::Cleanup *Fn, EHScopeStack::Cleanup::Flags flags, Address ActiveFlag)
static void ForwardPrebranchedFallthrough (llvm::BasicBlock *Exit, llvm::BasicBlock *From, llvm::BasicBlock *To)
static void destroyOptimisticNormalEntry (CodeGenFunction &CGF, EHCleanupScope &scope)
We don't need a normal entry block for the given cleanup.
static bool IsUsedAsNormalCleanup (EHScopeStack &EHStack, EHScopeStack::stable_iterator C)
static bool IsUsedAsEHCleanup (EHScopeStack &EHStack, EHScopeStack::stable_iterator cleanup)
static void SetupCleanupBlockActivation (CodeGenFunction &CGF, EHScopeStack::stable_iterator C, ForActivation_t kind, llvm::Instruction *dominatingIP)
The given cleanup block is changing activation state.
static void EmitSehScope (CodeGenFunction &CGF, llvm::FunctionCallee &SehCppScope)
Enumeration Type Documentation
ForActivation_t
enum ForActivation_t
Enumerator
ForActivation
ForDeactivation
Definition at line 1186 of file CGCleanup.cpp.
Function Documentation
createLoadInstBefore()
static llvm::LoadInst* createLoadInstBefore (Address addr, const Twine & name, llvm::Instruction * beforeInst, CodeGenFunction & CGF) static
Definition at line 302 of file CGCleanup.cpp.
References clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), clang::CodeGen::Address::getElementType(), and clang::transformer::name().
Referenced by TransitionToCleanupSwitch().
CreateNormalEntry()
static llvm::BasicBlock* CreateNormalEntry (CodeGenFunction & CGF, EHCleanupScope & Scope) static
Definition at line 498 of file CGCleanup.cpp.
References clang::CodeGen::CodeGenFunction::createBasicBlock().
createStoreInstBefore()
static void createStoreInstBefore (llvm::Value * value, Address addr, llvm::Instruction * beforeInst, CodeGenFunction & CGF) static
Definition at line 295 of file CGCleanup.cpp.
References clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), and clang::CharUnits::getAsAlign().
Referenced by ResolveAllBranchFixups(), and SetupCleanupBlockActivation().
destroyOptimisticNormalEntry()
static void destroyOptimisticNormalEntry (CodeGenFunction & CGF, EHCleanupScope & scope) static
We don't need a normal entry block for the given cleanup.
Optimistic fixup branches can cause these blocks to come into existence anyway; if so, destroy it.
The validity of this transformation is very much specific to the exact ways in which we form branches to cleanup entries.
Definition at line 597 of file CGCleanup.cpp.
References clang::CodeGen::EHCleanupScope::getNormalBlock(), clang::CodeGen::RawAddress::getPointer(), clang::CodeGen::CodeGenFunction::getUnreachableBlock(), and clang::CodeGen::CodeGenFunction::NormalCleanupDest.
EmitCleanup()
static void EmitCleanup (CodeGenFunction & CGF, EHScopeStack::Cleanup * Fn, EHScopeStack::Cleanup::Flags flags, Address ActiveFlag) static
Definition at line 548 of file CGCleanup.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::EHScopeStack::Cleanup::Emit(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::HaveInsertPoint(), and clang::CodeGen::Address::isValid().
EmitSehScope()
static void EmitSehScope (CodeGenFunction & CGF, llvm::FunctionCallee & SehCppScope) static
Definition at line 1313 of file CGCleanup.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CodeGenFunction::CurrentFuncletPad, clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::getBundlesForFunclet(), and clang::CodeGen::CodeGenFunction::getInvokeDest().
Referenced by clang::CodeGen::CodeGenFunction::EmitSehCppScopeBegin(), clang::CodeGen::CodeGenFunction::EmitSehCppScopeEnd(), clang::CodeGen::CodeGenFunction::EmitSehTryScopeBegin(), and clang::CodeGen::CodeGenFunction::EmitSehTryScopeEnd().
ForwardPrebranchedFallthrough()
static void ForwardPrebranchedFallthrough (llvm::BasicBlock * Exit, llvm::BasicBlock * From, llvm::BasicBlock * To) static
Definition at line 573 of file CGCleanup.cpp.
References clang::Switch.
IsUsedAsEHCleanup()
static bool IsUsedAsEHCleanup (EHScopeStack & EHStack, EHScopeStack::stable_iterator cleanup) static
Definition at line 1165 of file CGCleanup.cpp.
References clang::format::cleanup(), clang::CodeGen::EHScopeStack::find(), clang::CodeGen::EHScope::getEnclosingEHScope(), clang::CodeGen::EHScopeStack::getInnermostEHScope(), and clang::CodeGen::EHScope::hasEHBranches().
Referenced by SetupCleanupBlockActivation().
IsUsedAsNormalCleanup()
static bool IsUsedAsNormalCleanup (EHScopeStack & EHStack, EHScopeStack::stable_iterator C) static
Definition at line 1146 of file CGCleanup.cpp.
References clang::CodeGen::EHScopeStack::find(), and clang::CodeGen::EHScopeStack::getInnermostNormalCleanup().
Referenced by SetupCleanupBlockActivation().
ResolveAllBranchFixups()
static void ResolveAllBranchFixups (CodeGenFunction & CGF, llvm::SwitchInst * Switch, llvm::BasicBlock * CleanupEntry) static
All the branch fixups on the EH stack have propagated out past the outermost normal cleanup; resolve them all by adding cases to the given switch instruction.
Definition at line 313 of file CGCleanup.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::EHScopeStack::clearFixups(), createStoreInstBefore(), clang::CodeGen::BranchFixup::Destination, clang::CodeGen::BranchFixup::DestinationIndex, clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::EHScopeStack::getBranchFixup(), clang::CodeGen::CodeGenFunction::getNormalCleanupDestSlot(), clang::CodeGen::EHScopeStack::getNumBranchFixups(), clang::CodeGen::BranchFixup::InitialBranch, clang::CodeGen::BranchFixup::OptimisticBranchBlock, and clang::Switch.
SetupCleanupBlockActivation()
static void SetupCleanupBlockActivation (CodeGenFunction & CGF, EHScopeStack::stable_iterator C, ForActivation_t kind, llvm::Instruction * dominatingIP) static
The given cleanup block is changing activation state.
Configure a cleanup variable if necessary.
It would be good if we had some way of determining if there were extra uses after the change-over point.
Definition at line 1196 of file CGCleanup.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateStore(), createStoreInstBefore(), clang::CodeGen::CodeGenFunction::CreateTempAlloca(), clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::EHScopeStack::find(), ForActivation, ForDeactivation, clang::CodeGen::CodeGenFunction::isInConditionalBranch(), IsUsedAsEHCleanup(), IsUsedAsNormalCleanup(), clang::CharUnits::One(), clang::CodeGen::CodeGenFunction::setBeforeOutermostConditional(), and clang::dataflow::var().
Referenced by clang::CodeGen::CodeGenFunction::ActivateCleanupBlock().
SimplifyCleanupEntry()
static llvm::BasicBlock* SimplifyCleanupEntry (CodeGenFunction & CGF, llvm::BasicBlock * Entry) static
Attempts to reduce a cleanup's entry block to a fallthrough.
This is basically llvm::MergeBlockIntoPredecessor, except simplified/optimized for the tighter constraints on cleanup blocks.
Returns the new block, whatever it is.
Definition at line 514 of file CGCleanup.cpp.
References clang::CodeGen::CodeGenFunction::Builder.
TransitionToCleanupSwitch()
static llvm::SwitchInst* TransitionToCleanupSwitch (CodeGenFunction & CGF, llvm::BasicBlock * Block) static
Transitions the terminator of the given exit-block of a cleanup to be a cleanup switch.
Definition at line 351 of file CGCleanup.cpp.
References Block, createLoadInstBefore(), clang::CodeGen::CodeGenFunction::getNormalCleanupDestSlot(), clang::CFGBlock::getTerminator(), clang::interp::Load(), and clang::Switch.
Referenced by clang::CodeGen::CodeGenFunction::ResolveBranchFixups().