clang: lib/CodeGen/CGCoroutine.cpp File Reference
CGCoroutine.cpp File Reference
#include "CGCleanup.h"
#include "CodeGenFunction.h"
#include "llvm/ADT/ScopeExit.h"
#include "clang/AST/StmtCXX.h"
#include "clang/AST/StmtVisitor.h"
Classes
struct clang::CodeGen::CGCoroData
Functions
static void createCoroData (CodeGenFunction &CGF, CodeGenFunction::CGCoroInfo &CurCoro, llvm::CallInst *CoroId, CallExpr const *CoroIdExpr=nullptr)
static SmallString< 32 > buildSuspendPrefixStr (CGCoroData &Coro, AwaitKind Kind)
static bool FunctionCanThrow (const FunctionDecl *D)
static bool StmtCanThrow (const Stmt *S)
static LValueOrRValue emitSuspendExpression (CodeGenFunction &CGF, CGCoroData &Coro, CoroutineSuspendExpr const &S, AwaitKind Kind, AggValueSlot aggSlot, bool ignoreResult, bool forLValue)
static QualType getCoroutineSuspendExprReturnType (const ASTContext &Ctx, const CoroutineSuspendExpr *E)
static SmallVector< llvm::OperandBundleDef, 1 > getBundlesForCoroEnd (CodeGenFunction &CGF)
static void emitBodyAndFallthrough (CodeGenFunction &CGF, const CoroutineBodyStmt &S, Stmt *Body)
Function Documentation
buildSuspendPrefixStr()
static SmallString<32> buildSuspendPrefixStr (CGCoroData & Coro, AwaitKind Kind) static
Definition at line 112 of file CGCoroutine.cpp.
References clang::CodeGen::CGCoroData::AwaitNum, clang::interp::Init(), clang::No, and clang::CodeGen::CGCoroData::YieldNum.
createCoroData()
static void createCoroData (CodeGenFunction & CGF, CodeGenFunction::CGCoroInfo & CurCoro, llvm::CallInst * CoroId, CallExpr const * CoroIdExpr = nullptr) static
Definition at line 89 of file CGCoroutine.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CurCoro, clang::CodeGen::CodeGenFunction::CGCoroInfo::Data, and clang::CodeGen::CodeGenModule::Error().
emitBodyAndFallthrough()
static void emitBodyAndFallthrough (CodeGenFunction & CGF, const CoroutineBodyStmt & S, Stmt * Body) static
Definition at line 766 of file CGCoroutine.cpp.
emitSuspendExpression()
static LValueOrRValue emitSuspendExpression (CodeGenFunction & CGF, CGCoroData & Coro, CoroutineSuspendExpr const & S, AwaitKind Kind, AggValueSlot aggSlot, bool ignoreResult, bool forLValue) static
Definition at line 222 of file CGCoroutine.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitCoawaitExpr(), clang::CodeGen::CodeGenFunction::EmitCoawaitLValue(), clang::CodeGen::CodeGenFunction::EmitCoyieldExpr(), and clang::CodeGen::CodeGenFunction::EmitCoyieldLValue().
FunctionCanThrow()
static bool FunctionCanThrow (const FunctionDecl * D) static
Definition at line 134 of file CGCoroutine.cpp.
References clang::CT_Cannot, clang::Type::getAs(), clang::ValueDecl::getType(), and clang::isNoexceptExceptionSpec().
getBundlesForCoroEnd()
static SmallVector<llvm::OperandBundleDef, 1> getBundlesForCoroEnd (CodeGenFunction & CGF) static
Definition at line 556 of file CGCoroutine.cpp.
References clang::CodeGen::CodeGenFunction::CurrentFuncletPad.
getCoroutineSuspendExprReturnType()
static QualType getCoroutineSuspendExprReturnType (const ASTContext & Ctx, const CoroutineSuspendExpr * E) static
Definition at line 402 of file CGCoroutine.cpp.
References clang::CoroutineSuspendExpr::getResumeExpr().
Referenced by clang::CodeGen::CodeGenFunction::EmitCoawaitLValue(), and clang::CodeGen::CodeGenFunction::EmitCoyieldLValue().
StmtCanThrow()
static bool StmtCanThrow (const Stmt * S) static
Definition at line 144 of file CGCoroutine.cpp.