clang: lib/CodeGen/CGCUDANV.cpp File Reference
CGCUDANV.cpp File Reference
#include "CGCUDARuntime.h"
#include "CGCXXABI.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "clang/AST/Decl.h"
#include "clang/Basic/Cuda.h"
#include "clang/CodeGen/CodeGenABITypes.h"
#include "clang/CodeGen/ConstantInitBuilder.h"
#include "llvm/Frontend/Offloading/Utility.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/ReplaceConstant.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/VirtualFileSystem.h"
Functions
static std::unique_ptr< MangleContext > InitDeviceMC (CodeGenModule &CGM)
static void replaceManagedVar (llvm::GlobalVariable *Var, llvm::GlobalVariable *ManagedVar)
Function Documentation
InitDeviceMC()
static std::unique_ptr<MangleContext> InitDeviceMC (CodeGenModule & CGM) static
Definition at line 209 of file CGCUDANV.cpp.
References clang::ASTContext::createDeviceMangleContext(), clang::ASTContext::createMangleContext(), clang::ASTContext::getAuxTargetInfo(), clang::CodeGen::CodeGenModule::getContext(), clang::TargetInfo::getCXXABI(), clang::ASTContext::getTargetInfo(), clang::TargetCXXABI::isItaniumFamily(), and clang::TargetCXXABI::isMicrosoft().
replaceManagedVar()
static void replaceManagedVar (llvm::GlobalVariable * Var, llvm::GlobalVariable * ManagedVar) static
Definition at line 470 of file CGCUDANV.cpp.