clang: lib/CodeGen/CGCXX.cpp File Reference
CGCXX.cpp File Reference
#include "CGCXXABI.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/StmtCXX.h"
#include "clang/Basic/CodeGenOptions.h"
#include "llvm/ADT/StringExtras.h"
Functions
static CGCallee BuildAppleKextVirtualCall (CodeGenFunction &CGF, GlobalDecl GD, llvm::Type *Ty, const CXXRecordDecl *RD)
Function Documentation
BuildAppleKextVirtualCall()
static CGCallee BuildAppleKextVirtualCall (CodeGenFunction & CGF, GlobalDecl GD, llvm::Type * Ty, const CXXRecordDecl * RD) static
Definition at line 247 of file CGCXX.cpp.
References clang::VTableLayout::AddressPointLocation::AddressPointIndex, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::VTableLayout::getAddressPoint(), clang::CodeGen::CGCXXABI::getAddrOfVTable(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::TargetInfo::getCXXABI(), clang::CodeGen::CodeGenModule::getItaniumVTableContext(), clang::ItaniumVTableContext::getMethodVTableIndex(), clang::CodeGen::CodeGenModule::getTarget(), clang::ItaniumVTableContext::getVTableLayout(), clang::VTableLayout::getVTableOffset(), clang::TargetCXXABI::isMicrosoft(), clang::CodeGen::CodeGenTypeCache::PointerAlignInBytes, clang::VTableLayout::AddressPointLocation::VTableIndex, and clang::CharUnits::Zero().
Referenced by clang::CodeGen::CodeGenFunction::BuildAppleKextVirtualCall(), and clang::CodeGen::CodeGenFunction::BuildAppleKextVirtualDestructorCall().