clang: lib/CodeGen/CGDebugInfo.cpp File Reference
CGDebugInfo.cpp File Reference
#include "CGDebugInfo.h"
#include "CGBlocks.h"
#include "CGCXXABI.h"
#include "CGObjCRuntime.h"
#include "CGRecordLayout.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Expr.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/VTableBuilder.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Version.h"
#include "clang/Frontend/FrontendOptions.h"
#include "clang/Lex/HeaderSearchOptions.h"
#include "clang/Lex/ModuleMap.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SHA1.h"
#include "llvm/Support/SHA256.h"
#include "llvm/Support/TimeProfiler.h"
#include <optional>
#include "clang/AST/BuiltinTypes.def"
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/OpenCLExtensionTypes.def"
#include "clang/Basic/AArch64SVEACLETypes.def"
#include "clang/Basic/PPCTypes.def"
#include "clang/Basic/RISCVVTypes.def"
#include "clang/Basic/WebAssemblyReferenceTypes.def"
#include "clang/AST/TypeNodes.inc"
Macros
#define BUILTIN_TYPE(Id, SingletonId)
#define PLACEHOLDER_TYPE(Id, SingletonId) case BuiltinType::Id:
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define IMAGE_WRITE_TYPE(Type, Id, Ext)
#define IMAGE_READ_WRITE_TYPE(Type, Id, Ext)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
#define SVE_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define PPC_VECTOR_TYPE(Name, Id, size) case BuiltinType::Id:
#define RVV_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define WASM_REF_TYPE(Name, MangledName, Id, SingletonId, AS)
#define TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base) case Type::Class:
Functions
static uint32_t getTypeAlignIfRequired (const Type *Ty, const ASTContext &Ctx)
static uint32_t getTypeAlignIfRequired (QualType Ty, const ASTContext &Ctx)
static uint32_t getDeclAlignIfRequired (const Decl *D, const ASTContext &Ctx)
FileID ComputeValidFileID (SourceManager &SM, StringRef FileName)
static void stripUnusedQualifiers (Qualifiers &Q)
static llvm::dwarf::Tag getNextQualifier (Qualifiers &Q)
static bool hasCXXMangling (const TagDecl *TD, llvm::DICompileUnit *TheCU)
static bool needsTypeIdentifier (const TagDecl *TD, CodeGenModule &CGM, llvm::DICompileUnit *TheCU)
static SmallString< 256 > getTypeIdentifier (const TagType *Ty, CodeGenModule &CGM, llvm::DICompileUnit *TheCU)
static llvm::dwarf::Tag getTagForRecord (const RecordDecl *RD)
static llvm::SmallVector< TemplateArgument > GetTemplateArgs (const TemplateDecl *TD, const TemplateSpecializationType *Ty)
static llvm::DINode::DIFlags getAccessFlag (AccessSpecifier Access, const RecordDecl *RD)
Convert an AccessSpecifier into the corresponding DINode flag.
static unsigned getDwarfCC (CallingConv CC)
static llvm::DINode::DIFlags getRefFlags (const FunctionProtoType *Func)
static bool isFunctionLocalClass (const CXXRecordDecl *RD)
isFunctionLocalClass - Return true if CXXRecordDecl is defined inside a function.
static bool isClassOrMethodDLLImport (const CXXRecordDecl *RD)
Return true if the class or any of its methods are marked dllimport.
static bool isDefinedInClangModule (const RecordDecl *RD)
Does a type definition exist in an imported clang module?
static bool hasExplicitMemberDefinition (CXXRecordDecl::method_iterator I, CXXRecordDecl::method_iterator End)
static bool canUseCtorHoming (const CXXRecordDecl *RD)
static bool shouldOmitDefinition (llvm::codegenoptions::DebugInfoKind DebugKind, bool DebugTypeExtRefs, const RecordDecl *RD, const LangOptions &LangOpts)
static bool hasDefaultGetterName (const ObjCPropertyDecl *PD, const ObjCMethodDecl *Getter)
static bool hasDefaultSetterName (const ObjCPropertyDecl *PD, const ObjCMethodDecl *Setter)
static QualType UnwrapTypeForDebugInfo (QualType T, const ASTContext &C)
static bool ReferencesAnonymousEntity (ArrayRef< TemplateArgument > Args)
static bool ReferencesAnonymousEntity (RecordType *RT)
static bool IsReconstitutableType (QualType QT)
Macro Definition Documentation
ABSTRACT_TYPE
#define ABSTRACT_TYPE (Class, Base)
BUILTIN_TYPE
#define BUILTIN_TYPE (Id, SingletonId)
DEPENDENT_TYPE
#define DEPENDENT_TYPE (Class, Base) case Type::Class:
EXT_OPAQUE_TYPE
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
  case BuiltinType::Id: \
    return getOrCreateStructPtrType("opencl_" #ExtType, Id##Ty);
IMAGE_READ_WRITE_TYPE
#define IMAGE_READ_WRITE_TYPE (Type, Id, Ext)
IMAGE_TYPE [1/2]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Id:                                                        \
    return getOrCreateStructPtrType("opencl_" #ImgType "_" #Suffix "_t",       \
                                    SingletonId);
IMAGE_TYPE [2/2]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Sampled##Id:                                               \
    return getOrCreateStructPtrType(                                           \
        "spirv_sampled_" #ImgType "_" #Suffix "_t", Sampled##SingletonId);
IMAGE_WRITE_TYPE
#define IMAGE_WRITE_TYPE (Type, Id, Ext)
NON_CANONICAL_TYPE
#define NON_CANONICAL_TYPE (Class, Base)
PLACEHOLDER_TYPE
#define PLACEHOLDER_TYPE (Id, SingletonId) case BuiltinType::Id:
PPC_VECTOR_TYPE
#define PPC_VECTOR_TYPE (Name, Id, size) case BuiltinType::Id:
RVV_TYPE
#define RVV_TYPE (Name, Id, SingletonId) case BuiltinType::Id:
SVE_TYPE
#define SVE_TYPE (Name, Id, SingletonId) case BuiltinType::Id:
TYPE
#define TYPE (Class, Base)
WASM_REF_TYPE
#define WASM_REF_TYPE (Name, MangledName, Id, SingletonId, AS)
Value:
  case BuiltinType::Id: {                                                      \
    if (!SingletonId)                                                          \
      SingletonId =                                                            \
          DBuilder.createForwardDecl(llvm::dwarf::DW_TAG_structure_type,       \
                                     MangledName, TheCU, TheCU->getFile(), 0); \
    return SingletonId;                                                        \
  }
Function Documentation
canUseCtorHoming()
static bool canUseCtorHoming (const CXXRecordDecl * RD) static
Definition at line 2709 of file CGDebugInfo.cpp.
References clang::CXXRecordDecl::ctors(), clang::CXXRecordDecl::hasConstexprNonCopyMoveConstructor(), clang::CXXRecordDecl::hasTrivialDefaultConstructor(), clang::CXXRecordDecl::isAggregate(), isClassOrMethodDLLImport(), and clang::CXXRecordDecl::isLambda().
ComputeValidFileID()
FileID ComputeValidFileID (SourceManager & SM, StringRef FileName)
Definition at line 391 of file CGDebugInfo.cpp.
References clang::SrcMgr::C_User, clang::FileName, and SM.
getAccessFlag()
static llvm::DINode::DIFlags getAccessFlag (AccessSpecifier Access, const RecordDecl * RD) static
Convert an AccessSpecifier into the corresponding DINode flag.
As an optimization, return 0 if the access specifier equals the default for the containing type.
Definition at line 1470 of file CGDebugInfo.cpp.
References clang::AS_none, clang::AS_private, clang::AS_protected, clang::AS_public, clang::Default, clang::TagDecl::isClass(), clang::TagDecl::isStruct(), and clang::TagDecl::isUnion().
getDeclAlignIfRequired()
static uint32_t getDeclAlignIfRequired (const Decl * D, const ASTContext & Ctx) static
Definition at line 68 of file CGDebugInfo.cpp.
References clang::Decl::getMaxAlignment(), and clang::Decl::hasAttr().
Referenced by clang::CodeGen::CGDebugInfo::EmitExternalVariable(), and clang::CodeGen::CGDebugInfo::EmitGlobalVariable().
getDwarfCC()
static unsigned getDwarfCC (CallingConv CC) static
Definition at line 1522 of file CGDebugInfo.cpp.
References clang::CC_AAPCS, clang::CC_AAPCS_VFP, clang::CC_AArch64SVEPCS, clang::CC_AArch64VectorCall, clang::CC_AMDGPUKernelCall, clang::CC_C, clang::CC_IntelOclBicc, clang::CC_M68kRTD, clang::CC_OpenCLKernel, clang::CC_PreserveAll, clang::CC_PreserveMost, clang::CC_PreserveNone, clang::CC_RISCVVectorCall, clang::CC_SpirFunction, clang::CC_Swift, clang::CC_SwiftAsync, clang::CC_Win64, clang::CC_X86_64SysV, clang::CC_X86FastCall, clang::CC_X86Pascal, clang::CC_X86RegCall, clang::CC_X86StdCall, clang::CC_X86ThisCall, and clang::CC_X86VectorCall.
getNextQualifier()
static llvm::dwarf::Tag getNextQualifier (Qualifiers & Q) static
Definition at line 1025 of file CGDebugInfo.cpp.
References clang::Qualifiers::hasConst(), clang::Qualifiers::hasRestrict(), clang::Qualifiers::hasVolatile(), clang::Qualifiers::removeConst(), clang::Qualifiers::removeRestrict(), and clang::Qualifiers::removeVolatile().
getRefFlags()
static llvm::DINode::DIFlags getRefFlags (const FunctionProtoType * Func) static
Definition at line 1575 of file CGDebugInfo.cpp.
References clang::Func, clang::RQ_LValue, and clang::RQ_RValue.
getTagForRecord()
static llvm::dwarf::Tag getTagForRecord (const RecordDecl * RD) static
Returns
the appropriate DWARF tag for a composite type.
Definition at line 1180 of file CGDebugInfo.cpp.
References clang::TagDecl::isClass(), clang::TagDecl::isInterface(), clang::TagDecl::isStruct(), and clang::TagDecl::isUnion().
GetTemplateArgs()
static llvm::SmallVector<TemplateArgument> GetTemplateArgs (const TemplateDecl * TD, const TemplateSpecializationType * Ty) static
Definition at line 1370 of file CGDebugInfo.cpp.
References clang::TemplateParameterList::asArray(), clang::TemplateDecl::getTemplateParameters(), clang::TemplateSpecializationType::isTypeAlias(), and clang::TemplateSpecializationType::template_arguments().
getTypeAlignIfRequired() [1/2]
static uint32_t getTypeAlignIfRequired (const Type * Ty, const ASTContext & Ctx) static
Definition at line 59 of file CGDebugInfo.cpp.
References clang::ASTContext::getTypeInfo(), and clang::TypeInfo::isAlignRequired().
Referenced by getTypeAlignIfRequired().
getTypeAlignIfRequired() [2/2]
static uint32_t getTypeAlignIfRequired (QualType Ty, const ASTContext & Ctx) static
Definition at line 64 of file CGDebugInfo.cpp.
References getTypeAlignIfRequired(), and clang::QualType::getTypePtr().
getTypeIdentifier()
static SmallString<256> getTypeIdentifier (const TagType * Ty, CodeGenModule & CGM, llvm::DICompileUnit * TheCU) static
Definition at line 1159 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCXXABI(), clang::TagType::getDecl(), clang::RecordDecl::getDefinition(), clang::CodeGen::CGCXXABI::getMangleContext(), clang::CodeGen::CodeGenModule::getVTableLinkage(), Identifier, clang::MangleContext::mangleCXXRTTIName(), and needsTypeIdentifier().
hasCXXMangling()
static bool hasCXXMangling (const TagDecl * TD, llvm::DICompileUnit * TheCU) static
Returns
whether a C++ mangling exists for the type defined by TD.
Definition at line 1107 of file CGDebugInfo.cpp.
Referenced by needsTypeIdentifier().
hasDefaultGetterName()
static bool hasDefaultGetterName (const ObjCPropertyDecl * PD, const ObjCMethodDecl * Getter) static
Returns
true if Getter has the default name for the property PD.
Definition at line 2914 of file CGDebugInfo.cpp.
References clang::NamedDecl::getDeclName(), clang::NamedDecl::getName(), clang::Selector::getNameForSlot(), clang::DeclarationName::getObjCSelector(), and clang::DeclarationName::isObjCZeroArgSelector().
hasDefaultSetterName()
static bool hasDefaultSetterName (const ObjCPropertyDecl * PD, const ObjCMethodDecl * Setter) static
Returns
true if Setter has the default name for the property PD.
Definition at line 2926 of file CGDebugInfo.cpp.
References clang::SelectorTable::constructSetterName(), clang::NamedDecl::getDeclName(), clang::NamedDecl::getName(), clang::Selector::getNameForSlot(), clang::DeclarationName::getObjCSelector(), and clang::DeclarationName::isObjCOneArgSelector().
hasExplicitMemberDefinition()
static bool hasExplicitMemberDefinition (CXXRecordDecl::method_iterator I, CXXRecordDecl::method_iterator End) static
Definition at line 2699 of file CGDebugInfo.cpp.
References End, and clang::FunctionDecl::getInstantiatedFromMemberFunction().
isClassOrMethodDLLImport()
static bool isClassOrMethodDLLImport (const CXXRecordDecl * RD) static
Return true if the class or any of its methods are marked dllimport.
Definition at line 2627 of file CGDebugInfo.cpp.
References clang::Decl::hasAttr(), and clang::CXXRecordDecl::methods().
Referenced by canUseCtorHoming(), and clang::CodeGen::CGDebugInfo::completeClassData().
isDefinedInClangModule()
static bool isDefinedInClangModule (const RecordDecl * RD) static
Does a type definition exist in an imported clang module?
Definition at line 2637 of file CGDebugInfo.cpp.
References clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::DeclContext::getEnclosingNamespaceContext(), clang::NamedDecl::getName(), clang::CXXRecordDecl::getTemplateSpecializationKind(), clang::TagDecl::isCompleteDefinition(), clang::NamedDecl::isExternallyVisible(), clang::Decl::isFromASTFile(), clang::TSK_ExplicitInstantiationDeclaration, and clang::TSK_Undeclared.
Referenced by clang::CodeGen::CGDebugInfo::completeClassData().
isFunctionLocalClass()
static bool isFunctionLocalClass (const CXXRecordDecl * RD) static
isFunctionLocalClass - Return true if CXXRecordDecl is defined inside a function.
Definition at line 2004 of file CGDebugInfo.cpp.
References clang::Decl::getDeclContext().
IsReconstitutableType()
static bool IsReconstitutableType (QualType QT) static
Definition at line 5477 of file CGDebugInfo.cpp.
References clang::T.
needsTypeIdentifier()
static bool needsTypeIdentifier (const TagDecl * TD, CodeGenModule & CGM, llvm::DICompileUnit * TheCU) static
Definition at line 1141 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), hasCXXMangling(), and clang::NamedDecl::isExternallyVisible().
Referenced by getTypeIdentifier().
ReferencesAnonymousEntity() [1/2]
static bool ReferencesAnonymousEntity (ArrayRef< TemplateArgument > Args) static
Definition at line 5396 of file CGDebugInfo.cpp.
References clang::TemplateArgument::getKind().
Referenced by ReferencesAnonymousEntity().
ReferencesAnonymousEntity() [2/2]
static bool ReferencesAnonymousEntity (RecordType * RT) static
Definition at line 5380 of file CGDebugInfo.cpp.
References clang::RecordType::getDecl(), clang::NamedDecl::getIdentifier(), and ReferencesAnonymousEntity().
shouldOmitDefinition()
static bool shouldOmitDefinition (llvm::codegenoptions::DebugInfoKind DebugKind, bool DebugTypeExtRefs, const RecordDecl * RD, const LangOptions & LangOpts) static
Definition at line 2735 of file CGDebugInfo.cpp.
Referenced by clang::CodeGen::CGDebugInfo::completeRequiredType().
stripUnusedQualifiers()
static void stripUnusedQualifiers (Qualifiers & Q) static
Definition at line 1017 of file CGDebugInfo.cpp.
References clang::Qualifiers::removeAddressSpace(), clang::Qualifiers::removeObjCGCAttr(), clang::Qualifiers::removeObjCLifetime(), and clang::Qualifiers::removeUnaligned().
UnwrapTypeForDebugInfo()
static QualType UnwrapTypeForDebugInfo (QualType T, const ASTContext & C) static
Definition at line 3546 of file CGDebugInfo.cpp.
References clang::FunctionProtoType::desugar(), clang::Type::getTypeClass(), clang::QualType::isNull(), Paren, clang::Qualifiers::removeCommonQualifiers(), and clang::T.