clang: lib/CodeGen/CGExpr.cpp File Reference
CGExpr.cpp File Reference
#include "CGCUDARuntime.h"
#include "CGCXXABI.h"
#include "CGCall.h"
#include "CGCleanup.h"
#include "CGDebugInfo.h"
#include "CGObjCRuntime.h"
#include "CGOpenMPRuntime.h"
#include "CGRecordLayout.h"
#include "CGSYCLRuntime.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/NSAPI.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/MatrixBuilder.h"
#include "llvm/Passes/OptimizationLevel.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/xxhash.h"
#include "llvm/Transforms/Utils/SanitizerStats.h"
#include <optional>
#include <string>
Macros
#define SANITIZER_CHECK(Enum, Name, Version) {#Name, Version},
Typedefs
using RecIndicesTy = SmallVector< std::pair< const RecordDecl *, llvm::Value * >, 8 >
Enumerations
enum ConstantEmissionKind { CEK_None , CEK_AsReferenceOnly , CEK_AsValueOrReference , CEK_AsValueOnly }
Can we constant-emit a load of a reference to a variable of the given type? This is different from predicates like Decl::mightBeUsableInConstantExpressions because we do want it to apply in situations that don't necessarily satisfy the language's rules for this (e.g.
Functions
static llvm::cl::opt< bool > ClSanitizeDebugDeoptimization ("ubsan-unique-traps", llvm::cl::Optional, llvm::cl::desc("Deoptimize traps for UBSAN so there is 1 trap per check."))
static llvm::cl::opt< bool > ClSanitizeGuardChecks ("ubsan-guard-checks", llvm::cl::Optional, llvm::cl::desc("Guard UBSAN checks with `llvm.allow.ubsan.check()`."))
static void pushTemporaryCleanup (CodeGenFunction &CGF, const MaterializeTemporaryExpr *M, const Expr *E, Address ReferenceTemporary)
static RawAddress createReferenceTemporary (CodeGenFunction &CGF, const MaterializeTemporaryExpr *M, const Expr *Inner, RawAddress *Alloca=nullptr)
static bool isAAPCS (const TargetInfo &TargetInfo)
Helper method to check if the underlying ABI is AAPCS.
static llvm::Value * emitHash16Bytes (CGBuilderTy &Builder, llvm::Value *Low, llvm::Value *High)
Emit the hash_16_bytes function from include/llvm/ADT/Hashing.h.
static llvm::Value * getArrayIndexingBound (CodeGenFunction &CGF, const Expr *Base, QualType &IndexedType, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel)
If Base is known to point to the start of an array, return the length of that array.
static bool getGEPIndicesToField (CodeGenFunction &CGF, const RecordDecl *RD, const FieldDecl *FD, RecIndicesTy &Indices)
static Address EmitPointerWithAlignment (const Expr *E, LValueBaseInfo *BaseInfo, TBAAAccessInfo *TBAAInfo, KnownNonNull_t IsKnownNonNull, CodeGenFunction &CGF)
static QualType getConstantExprReferredType (const FullExpr *E, const ASTContext &Ctx)
static bool isConstantEmittableObjectType (QualType type)
Given an object of the given canonical type, can we safely copy a value out of it based on its initializer?
static ConstantEmissionKind checkVarTypeForConstantEmission (QualType type)
static DeclRefExpr * tryToConvertMemberExprToDeclRefExpr (CodeGenFunction &CGF, const MemberExpr *ME)
static bool hasBooleanRepresentation (QualType Ty)
static bool getRangeForType (CodeGenFunction &CGF, QualType Ty, llvm::APInt &Min, llvm::APInt &End, bool StrictEnums, bool IsBool)
static RawAddress MaybeConvertMatrixAddress (RawAddress Addr, CodeGenFunction &CGF, bool IsVector=true)
static void EmitStoreOfMatrixScalar (llvm::Value *value, LValue lvalue, bool isInit, CodeGenFunction &CGF)
static RValue EmitLoadOfMatrixLValue (LValue LV, SourceLocation Loc, CodeGenFunction &CGF)
static void setObjCGCLValueClass (const ASTContext &Ctx, const Expr *E, LValue &LV, bool IsMemberAccess=false)
static LValue EmitThreadPrivateVarDeclLValue (CodeGenFunction &CGF, const VarDecl *VD, QualType T, Address Addr, llvm::Type *RealVarTy, SourceLocation Loc)
static Address emitDeclTargetVarDeclLValue (CodeGenFunction &CGF, const VarDecl *VD, QualType T)
static LValue EmitGlobalVarDeclLValue (CodeGenFunction &CGF, const Expr *E, const VarDecl *VD)
static llvm::Constant * EmitFunctionDeclPointer (CodeGenModule &CGM, GlobalDecl GD)
static LValue EmitFunctionDeclLValue (CodeGenFunction &CGF, const Expr *E, GlobalDecl GD)
static LValue EmitCapturedFieldLValue (CodeGenFunction &CGF, const FieldDecl *FD, llvm::Value *ThisValue)
static LValue EmitGlobalNamedRegister (const VarDecl *VD, CodeGenModule &CGM)
Named Registers are named metadata pointing to the register name which will be read from/written to as an argument to the intrinsic @llvm.read/write_register.
static bool canEmitSpuriousReferenceToVariable (CodeGenFunction &CGF, const DeclRefExpr *E, const VarDecl *VD)
Determine whether we can emit a reference to VD from the current context, despite not necessarily having seen an odr-use of the variable in this context.
static CheckRecoverableKind getRecoverableKind (SanitizerMask Kind)
static void emitCheckHandlerCall (CodeGenFunction &CGF, llvm::FunctionType *FnType, ArrayRef< llvm::Value * > FnArgs, SanitizerHandler CheckHandler, CheckRecoverableKind RecoverKind, bool IsFatal, llvm::BasicBlock *ContBB)
static const Expr * isSimpleArrayDecayOperand (const Expr *E)
isSimpleArrayDecayOperand - If the specified expr is a simple decay from an array to pointer, return the array subexpression.
static llvm::Value * emitArraySubscriptGEP (CodeGenFunction &CGF, llvm::Type *elemType, llvm::Value *ptr, ArrayRef< llvm::Value * > indices, bool inbounds, bool signedIndices, SourceLocation loc, const llvm::Twine &name="arrayidx")
static Address emitArraySubscriptGEP (CodeGenFunction &CGF, Address addr, ArrayRef< llvm::Value * > indices, llvm::Type *elementType, bool inbounds, bool signedIndices, SourceLocation loc, CharUnits align, const llvm::Twine &name="arrayidx")
static CharUnits getArrayElementAlign (CharUnits arrayAlign, llvm::Value *idx, CharUnits eltSize)
static QualType getFixedSizeElementType (const ASTContext &ctx, const VariableArrayType *vla)
static void AddIVDepMetadata (CodeGenFunction &CGF, const ValueDecl *ArrayDecl, llvm::Value *EltPtr)
static bool hasBPFPreserveStaticOffset (const RecordDecl *D)
static bool hasBPFPreserveStaticOffset (const Expr *E)
static Address wrapWithBPFPreserveStaticOffset (CodeGenFunction &CGF, Address &Addr)
static bool IsPreserveAIArrayBase (CodeGenFunction &CGF, const Expr *ArrayBase)
Given an array base, check whether its member access belongs to a record with preserve_access_index attribute or not.
static Address emitArraySubscriptGEP (CodeGenFunction &CGF, Address addr, ArrayRef< llvm::Value * > indices, QualType eltType, bool inbounds, bool signedIndices, SourceLocation loc, QualType *arrayType=nullptr, const Expr *Base=nullptr, const llvm::Twine &name="arrayidx", const ValueDecl *arrayDecl=nullptr)
static bool getFieldOffsetInBits (CodeGenFunction &CGF, const RecordDecl *RD, const FieldDecl *FD, int64_t &Offset)
The offset of a field from the beginning of the record.
static std::optional< int64_t > getOffsetDifferenceInBits (CodeGenFunction &CGF, const FieldDecl *FD1, const FieldDecl *FD2)
Returns the relative offset difference between FD1 and FD2.
static Address emitOMPArraySectionBase (CodeGenFunction &CGF, const Expr *Base, LValueBaseInfo &BaseInfo, TBAAAccessInfo &TBAAInfo, QualType BaseTy, QualType ElTy, bool IsLowerBound)
static Address emitAddrOfZeroSizeField (CodeGenFunction &CGF, Address Base, const FieldDecl *Field)
Get the address of a zero-sized field within a record.
static Address emitAddrOfFieldStorage (CodeGenFunction &CGF, Address base, const FieldDecl *field)
Drill down to the storage of a field without walking into reference types.
static Address emitPreserveStructAccess (CodeGenFunction &CGF, LValue base, Address addr, const FieldDecl *field)
static bool hasAnyVptr (const QualType Type, const ASTContext &Context)
static std::optional< LValue > EmitLValueOrThrowExpression (CodeGenFunction &CGF, const Expr *Operand)
Emit the operand of a glvalue conditional operator.
static bool OnlyHasInlineBuiltinDeclaration (const FunctionDecl *FD)
static CGCallee EmitDirectCallee (CodeGenFunction &CGF, GlobalDecl GD)
static LValueOrRValue emitPseudoObjectExpr (CodeGenFunction &CGF, const PseudoObjectExpr *E, bool forLValue, AggValueSlot slot)
Variables
const SanitizerHandlerInfo SanitizerHandlers []
Macro Definition Documentation
SANITIZER_CHECK
#define SANITIZER_CHECK (Enum, Name, Version) {#Name, Version},
Typedef Documentation
RecIndicesTy
using RecIndicesTy = SmallVector<std::pair<const RecordDecl *, llvm::Value *>, 8>
Definition at line 1067 of file CGExpr.cpp.
Enumeration Type Documentation
ConstantEmissionKind
enum ConstantEmissionKind
Can we constant-emit a load of a reference to a variable of the given type? This is different from predicates like Decl::mightBeUsableInConstantExpressions because we do want it to apply in situations that don't necessarily satisfy the language's rules for this (e.g.
C++'s ODR-use rules). For example, we want to able to do this with const float variables even if those variables aren't marked 'constexpr'.
Enumerator
CEK_None
CEK_AsReferenceOnly
CEK_AsValueOrReference
CEK_AsValueOnly
Definition at line 1696 of file CGExpr.cpp.
Function Documentation
AddIVDepMetadata()
static void AddIVDepMetadata (CodeGenFunction & CGF, const ValueDecl * ArrayDecl, llvm::Value * EltPtr) static
Definition at line 3987 of file CGExpr.cpp.
References clang::CodeGen::LoopInfoStack::addIVDepMetadata(), and clang::CodeGen::CodeGenFunction::LoopStack.
Referenced by emitArraySubscriptGEP().
canEmitSpuriousReferenceToVariable()
static bool canEmitSpuriousReferenceToVariable (CodeGenFunction & CGF, const DeclRefExpr * E, const VarDecl * VD) static
Determine whether we can emit a reference to VD from the current context, despite not necessarily having seen an odr-use of the variable in this context.
Definition at line 2906 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CurCodeDecl, clang::CodeGen::CodeGenFunction::getContext(), clang::Decl::getDeclContext(), clang::VarDecl::getDefinition(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMLinkageVarDefinition(), clang::VarDecl::hasLocalStorage(), and clang::DeclRefExpr::refersToEnclosingVariableOrCapture().
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue().
checkVarTypeForConstantEmission()
static ConstantEmissionKind checkVarTypeForConstantEmission (QualType type) static
Definition at line 1702 of file CGExpr.cpp.
References CEK_AsReferenceOnly, CEK_AsValueOnly, CEK_AsValueOrReference, CEK_None, isConstantEmittableObjectType(), and clang::ast_matchers::type.
Referenced by clang::CodeGen::CodeGenFunction::tryEmitAsConstant().
ClSanitizeDebugDeoptimization()
static llvm::cl::opt<bool> ClSanitizeDebugDeoptimization ("ubsan-unique-traps" , llvm::cl::Optional , llvm::cl::desc("Deoptimize traps for UBSAN so there is 1 trap per check.")) static
Referenced by clang::CodeGen::CodeGenFunction::EmitTrapCheck().
ClSanitizeGuardChecks()
static llvm::cl::opt<bool> ClSanitizeGuardChecks ("ubsan-guard-checks" , llvm::cl::Optional , llvm::cl::desc("Guard UBSAN checks with `llvm.allow.ubsan.check()`.")) static
Referenced by clang::CodeGen::CodeGenFunction::EmitCheck().
createReferenceTemporary()
static RawAddress createReferenceTemporary (CodeGenFunction & CGF, const MaterializeTemporaryExpr * M, const Expr * Inner, RawAddress * Alloca = nullptr) static
Definition at line 395 of file CGExpr.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr().
emitAddrOfFieldStorage()
static Address emitAddrOfFieldStorage (CodeGenFunction & CGF, Address base, const FieldDecl * field) static
Drill down to the storage of a field without walking into reference types.
The resulting address doesn't necessarily have the right type.
Definition at line 4767 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateStructGEP(), emitAddrOfZeroSizeField(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), clang::NamedDecl::getName(), clang::FieldDecl::getParent(), clang::CodeGen::CodeGenModule::getTypes(), and clang::FieldDecl::isZeroSize().
Referenced by clang::CodeGen::CodeGenFunction::EmitLValueForField(), and clang::CodeGen::CodeGenFunction::EmitLValueForFieldInitialization().
emitAddrOfZeroSizeField()
static Address emitAddrOfZeroSizeField (CodeGenFunction & CGF, Address Base, const FieldDecl * Field) static
Get the address of a zero-sized field within a record.
The resulting address doesn't necessarily have the right type.
Definition at line 4753 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTContext::getFieldOffset(), clang::CodeGen::CodeGenTypeCache::Int8Ty, Offset, and clang::ASTContext::toCharUnitsFromBits().
Referenced by emitAddrOfFieldStorage().
emitArraySubscriptGEP() [1/3]
static Address emitArraySubscriptGEP (CodeGenFunction & CGF, Address addr, ArrayRef< llvm::Value * > indices, llvm::Type * elementType, bool inbounds, bool signedIndices, SourceLocation loc, CharUnits align, const llvm::Twine & name = "arrayidx") static
Definition at line 3948 of file CGExpr.cpp.
References clang::interp::align(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateGEP(), clang::CodeGen::CodeGenFunction::EmitCheckedInBoundsGEP(), clang::transformer::name(), and clang::CodeGen::CodeGenFunction::NotSubtraction.
emitArraySubscriptGEP() [2/3]
static Address emitArraySubscriptGEP (CodeGenFunction & CGF, Address addr, ArrayRef< llvm::Value * > indices, QualType eltType, bool inbounds, bool signedIndices, SourceLocation loc, QualType * arrayType = nullptr, const Expr * Base = nullptr, const llvm::Twine & name = "arrayidx", const ValueDecl * arrayDecl = nullptr) static
Definition at line 4060 of file CGExpr.cpp.
References AddIVDepMetadata(), clang::ast_matchers::arrayType, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), emitArraySubscriptGEP(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), getArrayElementAlign(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getDebugInfo(), clang::CodeGen::Address::getElementType(), getFixedSizeElementType(), clang::CodeGen::CGDebugInfo::getOrCreateStandaloneType(), clang::ASTContext::getTypeSizeInChars(), hasBPFPreserveStaticOffset(), clang::CodeGen::CodeGenFunction::IsInPreservedAIRegion, IsPreserveAIArrayBase(), clang::transformer::name(), and wrapWithBPFPreserveStaticOffset().
emitArraySubscriptGEP() [3/3]
static llvm::Value* emitArraySubscriptGEP (CodeGenFunction & CGF, llvm::Type * elemType, llvm::Value * ptr, ArrayRef< llvm::Value * > indices, bool inbounds, bool signedIndices, SourceLocation loc, const llvm::Twine & name = "arrayidx") static
Definition at line 3931 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGBuilderTy::CreateGEP(), clang::CodeGen::CodeGenFunction::EmitCheckedInBoundsGEP(), clang::transformer::name(), and clang::CodeGen::CodeGenFunction::NotSubtraction.
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), emitArraySubscriptGEP(), and clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr().
EmitCapturedFieldLValue()
static LValue EmitCapturedFieldLValue (CodeGenFunction & CGF, const FieldDecl * FD, llvm::Value * ThisValue) static
Definition at line 2869 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::EmitLValueForLambdaField().
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue().
emitCheckHandlerCall()
static void emitCheckHandlerCall (CodeGenFunction & CGF, llvm::FunctionType * FnType, ArrayRef< llvm::Value * > FnArgs, SanitizerHandler CheckHandler, CheckRecoverableKind RecoverKind, bool IsFatal, llvm::BasicBlock * ContBB) static
Definition at line 3467 of file CGExpr.cpp.
References AlwaysRecoverable, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenFunction::getLLVMContext(), SanitizerHandlers, and Unrecoverable.
Referenced by clang::CodeGen::CodeGenFunction::EmitCheck().
emitDeclTargetVarDeclLValue()
static Address emitDeclTargetVarDeclLValue (CodeGenFunction & CGF, const VarDecl * VD, QualType T) static
Definition at line 2749 of file CGExpr.cpp.
References clang::Type::castAs(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitLoadOfPointer(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::ASTContext::getPointerType(), clang::ValueDecl::getType(), clang::CodeGen::CGOpenMPRuntime::hasRequiresUnifiedSharedMemory(), and clang::CodeGen::Address::invalid().
Referenced by EmitGlobalVarDeclLValue().
EmitDirectCallee()
static CGCallee EmitDirectCallee (CodeGenFunction & CGF, GlobalDecl GD) static
Definition at line 5510 of file CGExpr.cpp.
References clang::ASTContext::BuiltinInfo, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CurFn, EmitFunctionDeclPointer(), clang::CodeGen::CGCallee::forBuiltin(), clang::CodeGen::CGCallee::forDirect(), clang::FunctionDecl::getBuiltinID(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getCUDARuntime(), clang::GlobalDecl::getDecl(), clang::CodeGen::CGCUDARuntime::getKernelStub(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getMangledName(), clang::NamedDecl::getName(), clang::Decl::hasAttr(), clang::Builtin::Context::isPredefinedLibFunction(), and OnlyHasInlineBuiltinDeclaration().
Referenced by clang::CodeGen::CodeGenFunction::EmitCallee().
EmitFunctionDeclLValue()
static LValue EmitFunctionDeclLValue (CodeGenFunction & CGF, const Expr * E, GlobalDecl GD) static
Definition at line 2860 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::Decl, EmitFunctionDeclPointer(), clang::CodeGen::CodeGenFunction::getContext(), clang::GlobalDecl::getDecl(), clang::ASTContext::getDeclAlign(), clang::Expr::getType(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), and V.
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), and clang::CodeGen::CodeGenFunction::EmitMemberExpr().
EmitFunctionDeclPointer()
static llvm::Constant* EmitFunctionDeclPointer (CodeGenModule & CGM, GlobalDecl GD) static
Definition at line 2848 of file CGExpr.cpp.
References clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::GlobalDecl::getDecl(), clang::CodeGen::ConstantAddress::getPointer(), clang::CodeGen::CodeGenModule::GetWeakRefReference(), clang::Decl::hasAttr(), and V.
Referenced by EmitDirectCallee(), and EmitFunctionDeclLValue().
EmitGlobalNamedRegister()
static LValue EmitGlobalNamedRegister (const VarDecl * VD, CodeGenModule & CGM) static
Named Registers are named metadata pointing to the register name which will be read from/written to as an argument to the intrinsic @llvm.read/write_register.
So far, only the name is being passed down, but other options such as register type, allocation type or even optimization options could be passed down via the metadata node.
Definition at line 2881 of file CGExpr.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue().
EmitGlobalVarDeclLValue()
static LValue EmitGlobalVarDeclLValue (CodeGenFunction & CGF, const Expr * E, const VarDecl * VD) static
Definition at line 2809 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::Decl, emitDeclTargetVarDeclLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfReferenceLValue(), clang::CodeGen::CGCXXABI::EmitThreadLocalVarDeclLValue(), EmitThreadPrivateVarDeclLValue(), clang::CodeGen::CodeGenModule::GetAddrOfGlobalVar(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::ASTContext::getDeclAlign(), clang::Expr::getExprLoc(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::VarDecl::getTLSKind(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::CodeGen::CodeGenFunction::getTypes(), clang::Decl::hasAttr(), clang::Type::isReferenceType(), clang::CodeGen::Address::isValid(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), setObjCGCLValueClass(), clang::T, clang::VarDecl::TLS_Dynamic, clang::VarDecl::TLS_None, clang::CodeGen::CGCXXABI::usesThreadWrapperFunction(), and V.
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue().
emitHash16Bytes()
static llvm::Value* emitHash16Bytes (CGBuilderTy & Builder, llvm::Value * Low, llvm::Value * High) static
Emit the hash_16_bytes function from include/llvm/ADT/Hashing.h.
Definition at line 649 of file CGExpr.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitTypeCheck().
EmitLoadOfMatrixLValue()
static RValue EmitLoadOfMatrixLValue (LValue LV, SourceLocation Loc, CodeGenFunction & CGF) static
Definition at line 2151 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getType(), clang::Type::isConstantMatrixType(), MaybeConvertMatrixAddress(), and clang::CodeGen::LValue::setAddress().
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfLValue().
EmitLValueOrThrowExpression()
static std::optional<LValue> EmitLValueOrThrowExpression (CodeGenFunction & CGF, const Expr * Operand) static
Emit the operand of a glvalue conditional operator.
This is either a glvalue or a (possibly-parenthesized) throw-expression. If this is a throw, no LValue is returned and the current block has been terminated.
Definition at line 5056 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::EmitCXXThrowExpr(), and clang::CodeGen::CodeGenFunction::EmitLValue().
Referenced by clang::CodeGen::CodeGenFunction::EmitConditionalOperatorLValue().
emitOMPArraySectionBase()
static Address emitOMPArraySectionBase (CodeGenFunction & CGF, const Expr * Base, LValueBaseInfo & BaseInfo, TBAAAccessInfo & TBAAInfo, QualType BaseTy, QualType ElTy, bool IsLowerBound) static
Definition at line 4396 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getBaseInfo(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::Type::isArrayType(), clang::Type::isVariableArrayType(), clang::CodeGen::LValueBaseInfo::mergeForCast(), clang::CodeGen::CodeGenModule::mergeTBAAInfoForCast(), and clang::CodeGen::Address::withElementType().
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr().
EmitPointerWithAlignment()
static Address EmitPointerWithAlignment (const Expr * E, LValueBaseInfo * BaseInfo, TBAAAccessInfo * TBAAInfo, KnownNonNull_t IsKnownNonNull, CodeGenFunction & CGF) static
Definition at line 1250 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CFITCK_UnrelatedCast, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateAddrSpaceCast(), clang::CodeGen::Decl, clang::CodeGen::CodeGenFunction::EmitArrayToPointerDecay(), clang::CodeGen::CodeGenModule::EmitExplicitCastExprType(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheckForCast(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenFunction::GetAddressOfBaseClass(), clang::CodeGen::LValueBaseInfo::getAlignmentSource(), clang::Type::getAs(), clang::CodeGen::LValue::getBaseInfo(), clang::CodeGen::CodeGenModule::getNaturalPointeeTypeAlignment(), clang::Type::getPointeeType(), clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), clang::CodeGen::LValue::getTBAAInfo(), clang::Expr::getType(), clang::CodeGen::Address::getType(), clang::SanitizerSet::has(), clang::Expr::IgnoreParens(), clang::Type::isObjCObjectPointerType(), clang::Type::isPointerType(), clang::CodeGen::CodeGenFunction::makeNaturalAddressForPointer(), clang::CodeGen::LValueBaseInfo::mergeForCast(), clang::CodeGen::CodeGenModule::mergeTBAAInfoForCast(), clang::CodeGen::CodeGenFunction::SanOpts, clang::CodeGen::Address::setAlignment(), clang::CodeGen::CodeGenFunction::ShouldNullCheckClassCastValue(), and clang::CodeGen::Address::withElementType().
Referenced by clang::CodeGen::CodeGenFunction::EmitAMDGPUBuiltinExpr(), clang::CodeGen::CodeGenFunction::emitBuiltinOSLogFormat(), clang::CodeGen::CodeGenFunction::EmitHexagonBuiltinExpr(), and clang::CodeGen::CodeGenFunction::EmitMSVCBuiltinExpr().
emitPreserveStructAccess()
static Address emitPreserveStructAccess (CodeGenFunction & CGF, LValue base, Address addr, const FieldDecl * field) static
Definition at line 4780 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreatePreserveStructAccessIndex(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CodeGenFunction::getDebugInfo(), clang::CodeGen::CodeGenFunction::getDebugInfoFIndex(), clang::FieldDecl::getFieldIndex(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), clang::Decl::getLocation(), clang::CodeGen::CGDebugInfo::getOrCreateStandaloneType(), clang::FieldDecl::getParent(), clang::CodeGen::LValue::getType(), and clang::CodeGen::CodeGenModule::getTypes().
Referenced by clang::CodeGen::CodeGenFunction::EmitLValueForField().
emitPseudoObjectExpr()
static LValueOrRValue emitPseudoObjectExpr (CodeGenFunction & CGF, const PseudoObjectExpr * E, bool forLValue, AggValueSlot slot) static
Definition at line 6154 of file CGExpr.cpp.
References clang::CodeGen::AggValueSlot::asRValue(), clang::CodeGen::Decl, clang::CodeGen::CodeGenFunction::EmitAggExpr(), clang::CodeGen::CodeGenFunction::EmitAnyExpr(), clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::AggValueSlot::getAddress(), clang::PseudoObjectExpr::getResultExpr(), clang::CodeGen::Address::getType(), clang::CodeGen::CodeGenFunction::hasAggregateEvaluationKind(), clang::Expr::isPRValue(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::PseudoObjectExpr::semantics_begin(), and clang::PseudoObjectExpr::semantics_end().
Referenced by clang::CodeGen::CodeGenFunction::EmitPseudoObjectLValue(), and clang::CodeGen::CodeGenFunction::EmitPseudoObjectRValue().
EmitStoreOfMatrixScalar()
static void EmitStoreOfMatrixScalar (llvm::Value * value, LValue lvalue, bool isInit, CodeGenFunction & CGF) static
Definition at line 2072 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getBaseInfo(), clang::CodeGen::LValue::getTBAAInfo(), clang::CodeGen::LValue::getType(), clang::CodeGen::LValue::isNontemporal(), clang::CodeGen::LValue::isVolatile(), and MaybeConvertMatrixAddress().
Referenced by clang::CodeGen::CodeGenFunction::EmitStoreOfScalar().
EmitThreadPrivateVarDeclLValue()
static LValue EmitThreadPrivateVarDeclLValue (CodeGenFunction & CGF, const VarDecl * VD, QualType T, Address Addr, llvm::Type * RealVarTy, SourceLocation Loc) static
Definition at line 2735 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::Decl, clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::T, and clang::CodeGen::Address::withElementType().
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), and EmitGlobalVarDeclLValue().
getArrayElementAlign()
static CharUnits getArrayElementAlign (CharUnits arrayAlign, llvm::Value * idx, CharUnits eltSize) static
Definition at line 3963 of file CGExpr.cpp.
References clang::CharUnits::alignmentAtOffset(), and clang::CharUnits::alignmentOfArrayElement().
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), and emitArraySubscriptGEP().
getArrayIndexingBound()
static llvm::Value* getArrayIndexingBound (CodeGenFunction & CGF, const Expr * Base, QualType & IndexedType, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel) static
If Base is known to point to the start of an array, return the length of that array.
Return 0 if the length cannot be determined.
Definition at line 921 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::Type::castAsArrayTypeUnsafe(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenFunction::getVLASize(), clang::CodeGen::CodeGenFunction::LoadPassedObjectSize(), and clang::CodeGen::CodeGenFunction::VlaSizePair::NumElts.
getConstantExprReferredType()
static QualType getConstantExprReferredType (const FullExpr * E, const ASTContext & Ctx) static
Definition at line 1505 of file CGExpr.cpp.
References clang::Type::getPointeeType(), clang::FullExpr::getSubExpr(), clang::Expr::getType(), and clang::Expr::IgnoreImplicit().
getFieldOffsetInBits()
static bool getFieldOffsetInBits (CodeGenFunction & CGF, const RecordDecl * RD, const FieldDecl * FD, int64_t & Offset) static
The offset of a field from the beginning of the record.
Definition at line 4113 of file CGExpr.cpp.
References clang::DeclContext::decls(), clang::ASTContext::getASTRecordLayout(), clang::CodeGen::CodeGenFunction::getContext(), clang::ASTRecordLayout::getFieldOffset(), and Offset.
Referenced by getOffsetDifferenceInBits().
getFixedSizeElementType()
static QualType getFixedSizeElementType (const ASTContext & ctx, const VariableArrayType * vla) static
Definition at line 3978 of file CGExpr.cpp.
References clang::ASTContext::getAsVariableArrayType(), and clang::ArrayType::getElementType().
Referenced by emitArraySubscriptGEP().
getGEPIndicesToField()
static bool getGEPIndicesToField (CodeGenFunction & CGF, const RecordDecl * RD, const FieldDecl * FD, RecIndicesTy & Indices) static
Definition at line 1070 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::DeclContext::decls(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), clang::CodeGen::CodeGenModule::getTypes(), and clang::TagDecl::isUnion().
Referenced by clang::CodeGen::CodeGenFunction::EmitCountedByFieldExpr().
getOffsetDifferenceInBits()
static std::optional<int64_t> getOffsetDifferenceInBits (CodeGenFunction & CGF, const FieldDecl * FD1, const FieldDecl * FD2) static
Returns the relative offset difference between FD1 and FD2.
offsetof(struct foo, FD1) - offsetof(struct foo, FD2)
Both fields must be within the same struct.
Definition at line 4144 of file CGExpr.cpp.
References getFieldOffsetInBits(), clang::DeclContext::getOuterLexicalRecordContext(), and clang::FieldDecl::getParent().
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr().
getRangeForType()
static bool getRangeForType (CodeGenFunction & CGF, QualType Ty, llvm::APInt & Min, llvm::APInt & End, bool StrictEnums, bool IsBool) static
Definition at line 1855 of file CGExpr.cpp.
References End, clang::Type::getAs(), clang::CodeGen::CodeGenFunction::getContext(), clang::EnumType::getDecl(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::ASTContext::getTypeSize(), clang::EnumDecl::getValueRange(), clang::EnumDecl::isFixed(), and clang::Min.
Referenced by clang::CodeGen::CodeGenFunction::EmitScalarRangeCheck().
getRecoverableKind()
static CheckRecoverableKind getRecoverableKind (SanitizerMask Kind) static
Definition at line 3444 of file CGExpr.cpp.
References AlwaysRecoverable, and Unrecoverable.
Referenced by clang::CodeGen::CodeGenFunction::EmitCheck().
hasAnyVptr()
static bool hasAnyVptr (const QualType Type, const ASTContext & Context) static
Definition at line 4793 of file CGExpr.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitLValueForField().
hasBooleanRepresentation()
static bool hasBooleanRepresentation (QualType Ty) static
Definition at line 1842 of file CGExpr.cpp.
References clang::Type::getAs(), and clang::Type::isBooleanType().
Referenced by clang::CodeGen::CodeGenFunction::EmitFromMemory(), clang::CodeGen::CodeGenFunction::EmitScalarRangeCheck(), clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue(), and clang::CodeGen::CodeGenFunction::EmitToMemory().
hasBPFPreserveStaticOffset() [1/2]
static bool hasBPFPreserveStaticOffset (const Expr * E) static
Definition at line 4001 of file CGExpr.cpp.
References clang::Type::getAsRecordDecl(), clang::Type::getPointeeType(), clang::Expr::getType(), hasBPFPreserveStaticOffset(), and clang::QualType::isNull().
hasBPFPreserveStaticOffset() [2/2]
static bool hasBPFPreserveStaticOffset (const RecordDecl * D) static
Definition at line 3997 of file CGExpr.cpp.
References clang::Decl::hasAttr().
Referenced by emitArraySubscriptGEP(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), and hasBPFPreserveStaticOffset().
isAAPCS()
static bool isAAPCS (const TargetInfo & TargetInfo) static
Helper method to check if the underlying ABI is AAPCS.
Definition at line 442 of file CGExpr.cpp.
References clang::TargetInfo::getABI().
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue().
isConstantEmittableObjectType()
static bool isConstantEmittableObjectType (QualType type) static
Given an object of the given canonical type, can we safely copy a value out of it based on its initializer?
Definition at line 1671 of file CGExpr.cpp.
References clang::Qualifiers::hasConst(), clang::Qualifiers::hasVolatile(), and clang::ast_matchers::type.
Referenced by checkVarTypeForConstantEmission().
IsPreserveAIArrayBase()
static bool IsPreserveAIArrayBase (CodeGenFunction & CGF, const Expr * ArrayBase) static
Given an array base, check whether its member access belongs to a record with preserve_access_index attribute or not.
Definition at line 4026 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::getDebugInfo(), clang::PointerType::getPointeeType(), clang::Type::getUnqualifiedDesugaredType(), clang::Type::hasAttr(), and clang::Expr::IgnoreImpCasts().
Referenced by emitArraySubscriptGEP().
isSimpleArrayDecayOperand()
static const Expr* isSimpleArrayDecayOperand (const Expr * E) static
isSimpleArrayDecayOperand - If the specified expr is a simple decay from an array to pointer, return the array subexpression.
Definition at line 3917 of file CGExpr.cpp.
References clang::FullExpr::getSubExpr(), clang::Expr::getType(), and clang::Type::isVariableArrayType().
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), and clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr().
MaybeConvertMatrixAddress()
static RawAddress MaybeConvertMatrixAddress (RawAddress Addr, CodeGenFunction & CGF, bool IsVector = true) static
Definition at line 2047 of file CGExpr.cpp.
References clang::CodeGen::RawAddress::getElementType(), and clang::CodeGen::RawAddress::withElementType().
Referenced by EmitLoadOfMatrixLValue(), clang::CodeGen::CodeGenFunction::EmitMatrixSubscriptExpr(), and EmitStoreOfMatrixScalar().
OnlyHasInlineBuiltinDeclaration()
static bool OnlyHasInlineBuiltinDeclaration (const FunctionDecl * FD) static
Definition at line 5503 of file CGExpr.cpp.
References clang::Redeclarable< decl_type >::getPreviousDecl().
Referenced by EmitDirectCallee().
pushTemporaryCleanup()
static void pushTemporaryCleanup (CodeGenFunction & CGF, const MaterializeTemporaryExpr * M, const Expr * E, Address ReferenceTemporary) static
Definition at line 279 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::interp::Destroy(), clang::CodeGen::CodeGenFunction::destroyARCStrongImprecise, clang::CodeGen::CodeGenFunction::destroyARCStrongPrecise, clang::CodeGen::CodeGenFunction::destroyARCWeak, clang::CodeGen::CodeGenFunction::destroyCXXObject, clang::Dtor_Complete, clang::CodeGen::EHCleanup, clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::CodeGenFunction::generateDestroyHelper(), clang::CodeGen::CodeGenModule::getAddrAndTypeOfCXXStructor(), clang::CodeGen::CodeGenFunction::getARCCleanupKind(), clang::Type::getAs(), clang::Type::getBaseElementTypeUnsafe(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::MaterializeTemporaryExpr::getExtendingDecl(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::QualType::getObjCLifetime(), clang::MaterializeTemporaryExpr::getStorageDuration(), clang::Expr::getType(), clang::Decl::hasAttr(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::Type::isArrayType(), clang::CodeGen::NormalAndEHCleanup, clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, clang::CodeGen::CodeGenFunction::pushDestroy(), clang::CodeGen::CodeGenFunction::pushLifetimeExtendedDestroy(), clang::CodeGen::CGCXXABI::registerGlobalDtor(), clang::SD_Automatic, clang::SD_Dynamic, clang::SD_FullExpression, clang::SD_Static, and clang::SD_Thread.
Referenced by clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr().
setObjCGCLValueClass()
static void setObjCGCLValueClass (const ASTContext & Ctx, const Expr * E, LValue & LV, bool IsMemberAccess = false) static
Definition at line 2638 of file CGExpr.cpp.
References clang::Type::castAs(), clang::ASTContext::getLangOpts(), clang::Expr::getType(), clang::Type::isArrayType(), clang::CodeGen::LValue::isGlobalObjCRef(), clang::CodeGen::LValue::isObjCArray(), clang::CodeGen::LValue::isObjCIvar(), clang::Type::isPointerType(), clang::Type::isRecordType(), clang::LangOptionsBase::NonGC, clang::CodeGen::LValue::setBaseIvarExp(), clang::CodeGen::LValue::setGlobalObjCRef(), clang::CodeGen::LValue::setObjCArray(), clang::CodeGen::LValue::setObjCIvar(), clang::CodeGen::LValue::setThreadLocalRef(), and clang::VarDecl::TLS_None.
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), EmitGlobalVarDeclLValue(), clang::CodeGen::CodeGenFunction::EmitMemberExpr(), and clang::CodeGen::CodeGenFunction::EmitObjCIvarRefLValue().
tryToConvertMemberExprToDeclRefExpr()
static DeclRefExpr* tryToConvertMemberExprToDeclRefExpr (CodeGenFunction & CGF, const MemberExpr * ME) static
Definition at line 1806 of file CGExpr.cpp.
References clang::DeclRefExpr::Create(), clang::CodeGen::CodeGenFunction::getContext(), clang::MemberExpr::getExprLoc(), clang::MemberExpr::getMemberDecl(), clang::Expr::getType(), clang::Expr::getValueKind(), and clang::MemberExpr::isNonOdrUse().
Referenced by clang::CodeGen::CodeGenFunction::EmitMemberExpr(), and clang::CodeGen::CodeGenFunction::tryEmitAsConstant().
wrapWithBPFPreserveStaticOffset()
static Address wrapWithBPFPreserveStaticOffset (CodeGenFunction & CGF, Address & Addr) static
Definition at line 4013 of file CGExpr.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenFunction::getTarget(), and clang::TargetInfo::getTriple().
Referenced by emitArraySubscriptGEP(), and clang::CodeGen::CodeGenFunction::EmitLValueForField().
Variable Documentation
SanitizerHandlers
const SanitizerHandlerInfo SanitizerHandlers[]
Initial value:
= {
#define SANITIZER_CHECK(Enum, Name, Version)
    LIST_SANITIZER_CHECKS
}
Definition at line 3461 of file CGExpr.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitCheck(), and emitCheckHandlerCall().