clang: lib/CodeGen/CGExprCXX.cpp File Reference
CGExprCXX.cpp File Reference
#include "CGCUDARuntime.h"
#include "CGCXXABI.h"
#include "CGDebugInfo.h"
#include "CGObjCRuntime.h"
#include "CodeGenFunction.h"
#include "ConstantEmitter.h"
#include "TargetInfo.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/CodeGen/CGFunctionInfo.h"
#include "llvm/IR/Intrinsics.h"
Functions
static MemberCallInfo commonEmitCXXMemberOrOperatorCall (CodeGenFunction &CGF, const CXXMethodDecl *MD, llvm::Value *This, llvm::Value *ImplicitParam, QualType ImplicitParamTy, const CallExpr *CE, CallArgList &Args, CallArgList *RtlArgs)
static CXXRecordDecl * getCXXRecord (const Expr *E)
static void EmitNullBaseClassInitialization (CodeGenFunction &CGF, Address DestPtr, const CXXRecordDecl *Base)
static CharUnits CalculateCookiePadding (CodeGenFunction &CGF, const CXXNewExpr *E)
static llvm::Value * EmitCXXNewAllocSize (CodeGenFunction &CGF, const CXXNewExpr *e, unsigned minElements, llvm::Value *&numElements, llvm::Value *&sizeWithoutCookie)
static void StoreAnyExprIntoOneUnit (CodeGenFunction &CGF, const Expr *Init, QualType AllocType, Address NewPtr, AggValueSlot::Overlap_t MayOverlap)
static void EmitNewInitializer (CodeGenFunction &CGF, const CXXNewExpr *E, QualType ElementType, llvm::Type *ElementTy, Address NewPtr, llvm::Value *NumElements, llvm::Value *AllocSizeWithoutCookie)
static RValue EmitNewDeleteCall (CodeGenFunction &CGF, const FunctionDecl *CalleeDecl, const FunctionProtoType *CalleeType, const CallArgList &Args)
Emit a call to an operator new or operator delete function, as implicitly created by new-expressions and delete-expressions.
static UsualDeleteParams getUsualDeleteParams (const FunctionDecl *FD)
static void EnterNewDeleteCleanup (CodeGenFunction &CGF, const CXXNewExpr *E, Address NewPtr, llvm::Value *AllocSize, CharUnits AllocAlign, const CallArgList &NewArgs)
Enter a cleanup to call 'operator delete' if the initializer in a new-expression throws.
static void EmitDestroyingObjectDelete (CodeGenFunction &CGF, const CXXDeleteExpr *DE, Address Ptr, QualType ElementType)
Emit the code for deleting a single object with a destroying operator delete.
static bool EmitObjectDelete (CodeGenFunction &CGF, const CXXDeleteExpr *DE, Address Ptr, QualType ElementType, llvm::BasicBlock *UnconditionalDeleteBlock)
Emit the code for deleting a single object.
static void EmitArrayDelete (CodeGenFunction &CGF, const CXXDeleteExpr *E, Address deletedPtr, QualType elementType)
Emit the code for deleting an array of objects.
static bool isGLValueFromPointerDeref (const Expr *E)
static llvm::Value * EmitTypeidFromVTable (CodeGenFunction &CGF, const Expr *E, llvm::Type *StdTypeInfoPtrTy)
static llvm::Value * EmitDynamicCastToNull (CodeGenFunction &CGF, QualType DestTy)
Function Documentation
CalculateCookiePadding()
static CharUnits CalculateCookiePadding (CodeGenFunction & CGF, const CXXNewExpr * E) static
Definition at line 682 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGCXXABI::GetArrayCookieSize(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CXXNewExpr::getOperatorNew(), clang::CXXNewExpr::isArray(), clang::FunctionDecl::isReservedGlobalPlacementOperator(), and clang::CharUnits::Zero().
Referenced by EmitCXXNewAllocSize(), and clang::CodeGen::CodeGenFunction::EmitCXXNewExpr().
commonEmitCXXMemberOrOperatorCall()
static MemberCallInfo commonEmitCXXMemberOrOperatorCall (CodeGenFunction & CGF, const CXXMethodDecl * MD, llvm::Value * This, llvm::Value * ImplicitParam, QualType ImplicitParamTy, const CallExpr * CE, CallArgList & Args, CallArgList * RtlArgs) static
Definition at line 36 of file CGExprCXX.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CallArgList::addFrom(), clang::CallExpr::arguments(), clang::Type::castAs(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenTypes::DeriveThisType(), clang::CodeGen::CodeGenFunction::EmitCallArgs(), clang::CodeGen::RequiredArgs::forPrototypePlus(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CallExpr::getDirectCallee(), clang::FunctionProtoType::getNumParams(), clang::CodeGen::CGCXXABI::getThisArgumentTypeForMethod(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenFunction::getTypes(), clang::CXXMethodDecl::isInstance(), and clang::interp::This().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXDestructorCall(), and clang::CodeGen::CodeGenFunction::EmitCXXMemberOrOperatorCall().
EmitArrayDelete()
static void EmitArrayDelete (CodeGenFunction & CGF, const CXXDeleteExpr * E, Address deletedPtr, QualType elementType) static
Emit the code for deleting an array of objects.
Definition at line 2012 of file CGExprCXX.cpp.
References clang::CharUnits::alignmentOfArrayElement(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::CodeGenFunction::emitArrayDestroy(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::CodeGenFunction::getDestroyer(), clang::CodeGen::Address::getElementType(), clang::CXXDeleteExpr::getOperatorDelete(), clang::CodeGen::Address::getPointer(), clang::ASTContext::getTypeSizeInChars(), clang::CodeGen::CodeGenFunction::needsEHCleanup(), clang::CodeGen::NormalAndEHCleanup, clang::CodeGen::CodeGenFunction::PopCleanupBlock(), and clang::CodeGen::CGCXXABI::ReadArrayCookie().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXDeleteExpr().
EmitCXXNewAllocSize()
static llvm::Value* EmitCXXNewAllocSize (CodeGenFunction & CGF, const CXXNewExpr * e, unsigned minElements, llvm::Value *& numElements, llvm::Value *& sizeWithoutCookie) static
Definition at line 695 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenFunction::Builder, CalculateCookiePadding(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CXXNewExpr::getAllocatedType(), clang::CXXNewExpr::getArraySize(), clang::ASTContext::getAsConstantArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CharUnits::getQuantity(), clang::Expr::getType(), clang::ASTContext::getTypeSizeInChars(), clang::CXXNewExpr::isArray(), clang::CharUnits::isOne(), clang::CodeGen::CodeGenTypeCache::SizeTy, and clang::CodeGen::ConstantEmitter::tryEmitAbstract().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXNewExpr().
EmitDestroyingObjectDelete()
static void EmitDestroyingObjectDelete (CodeGenFunction & CGF, const CXXDeleteExpr * DE, Address Ptr, QualType ElementType) static
Emit the code for deleting a single object with a destroying operator delete.
If the element type has a non-virtual destructor, Ptr has already been converted to the type of the parameter of 'operator delete'. Otherwise Ptr points to an object of the static type.
Definition at line 1876 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitDeleteCall(), clang::CodeGen::CGCXXABI::emitVirtualObjectDelete(), clang::Type::getAsCXXRecordDecl(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CXXRecordDecl::getDestructor(), clang::CXXDeleteExpr::getOperatorDelete(), and clang::CodeGen::Address::getPointer().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXDeleteExpr().
EmitDynamicCastToNull()
static llvm::Value* EmitDynamicCastToNull (CodeGenFunction & CGF, QualType DestTy) static
C++ [expr.dynamic.cast]p9: A failed cast to reference type throws std::bad_cast
Definition at line 2217 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGCXXABI::EmitBadCastCall(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenModule::getCXXABI(), and clang::Type::isPointerType().
Referenced by clang::CodeGen::CodeGenFunction::EmitDynamicCast().
EmitNewDeleteCall()
static RValue EmitNewDeleteCall (CodeGenFunction & CGF, const FunctionDecl * CalleeDecl, const FunctionProtoType * CalleeType, const CallArgList & Args) static
Emit a call to an operator new or operator delete function, as implicitly created by new-expressions and delete-expressions.
C++1y [expr.new]p10: [In a new-expression,] an implementation is allowed to omit a call to a replaceable global allocation function.
We model such elidable calls with the 'builtin' attribute.
Definition at line 1305 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenTypes::arrangeFreeFunctionCall(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::CodeGen::CodeGenModule::getTypes(), and clang::FunctionDecl::isReplaceableGlobalAllocationFunction().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), and clang::CodeGen::CodeGenFunction::EmitDeleteCall().
EmitNewInitializer()
static void EmitNewInitializer (CodeGenFunction & CGF, const CXXNewExpr * E, QualType ElementType, llvm::Type * ElementTy, Address NewPtr, llvm::Value * NumElements, llvm::Value * AllocSizeWithoutCookie) static
Definition at line 1290 of file CGExprCXX.cpp.
References clang::CodeGen::AggValueSlot::DoesNotOverlap, clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), clang::CXXNewExpr::getAllocatedType(), clang::CXXNewExpr::getInitializer(), clang::CXXNewExpr::isArray(), and StoreAnyExprIntoOneUnit().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXNewExpr().
EmitNullBaseClassInitialization()
static void EmitNullBaseClassInitialization (CodeGenFunction & CGF, Address DestPtr, const CXXRecordDecl * Base) static
Definition at line 496 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), clang::CodeGen::CGBuilderTy::CreateMemSet(), clang::CodeGen::CodeGenFunction::EmitCastToVoidPtr(), clang::CodeGen::CodeGenModule::EmitNullConstantForBase(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), clang::ASTContext::getASTRecordLayout(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::CodeGenModule::getModule(), clang::ASTRecordLayout::getNonVirtualAlignment(), clang::ASTRecordLayout::getNonVirtualSize(), clang::CodeGen::CodeGenTypeCache::getPointerSize(), clang::CodeGen::CodeGenModule::getSize(), clang::CodeGen::CGCXXABI::getVBPtrOffsets(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CharUnits::isNegative(), clang::CharUnits::isZero(), max(), and clang::CharUnits::Zero().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructExpr().
EmitObjectDelete()
static bool EmitObjectDelete (CodeGenFunction & CGF, const CXXDeleteExpr * DE, Address Ptr, QualType ElementType, llvm::BasicBlock * UnconditionalDeleteBlock) static
Emit the code for deleting a single object.
Returns
true if we started emitting UnconditionalDeleteBlock, false if not.
Definition at line 1890 of file CGExprCXX.cpp.
References clang::CodeGen::ARCPreciseLifetime, clang::CodeGen::CodeGenFunction::CGM, clang::declaresSameEntity(), clang::Dtor_Complete, clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::CodeGenFunction::EmitARCDestroyStrong(), clang::CodeGen::CodeGenFunction::EmitARCDestroyWeak(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitCXXDestructorCall(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), clang::CodeGen::CGCXXABI::emitVirtualObjectDelete(), clang::CXXDeleteExpr::getArgument(), clang::Type::getAs(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getCXXABI(), getCXXRecord(), clang::CXXRecordDecl::getDestructor(), clang::CXXMethodDecl::getDevirtualizedMethod(), clang::Expr::getExprLoc(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::QualType::getObjCLifetime(), clang::CXXDeleteExpr::getOperatorDelete(), clang::DeclContext::getParent(), clang::CodeGen::Address::getPointer(), clang::CXXRecordDecl::hasDefinition(), clang::CXXRecordDecl::hasTrivialDestructor(), clang::FunctionDecl::isDestroyingOperatorDelete(), clang::CXXMethodDecl::isVirtual(), clang::CodeGen::NormalAndEHCleanup, clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, clang::CodeGen::CodeGenFunction::PopCleanupBlock(), and clang::CodeGen::CodeGenFunction::TCK_MemberCall.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXDeleteExpr().
EmitTypeidFromVTable()
static llvm::Value* EmitTypeidFromVTable (CodeGenFunction & CGF, const Expr * E, llvm::Type * StdTypeInfoPtrTy) static
Definition at line 2152 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGCXXABI::EmitBadTypeidCall(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), clang::CodeGen::CGCXXABI::EmitTypeid(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::Expr::getExprLoc(), clang::CodeGen::Address::getPointer(), clang::Expr::getType(), isGLValueFromPointerDeref(), clang::CodeGen::CGCXXABI::shouldTypeidBeNullChecked(), and clang::CodeGen::CodeGenFunction::TCK_DynamicOperation.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXTypeidExpr().
EnterNewDeleteCleanup()
static void EnterNewDeleteCleanup (CodeGenFunction & CGF, const CXXNewExpr * E, Address NewPtr, llvm::Value * AllocSize, CharUnits AllocAlign, const CallArgList & NewArgs) static
Enter a cleanup to call 'operator delete' if the initializer in a new-expression throws.
Definition at line 1484 of file CGExprCXX.cpp.
References clang::CodeGen::EHCleanup, clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::RValue::get(), clang::CXXNewExpr::getNumPlacementArgs(), clang::CXXNewExpr::getOperatorDelete(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenFunction::initFullExprCleanup(), clang::CodeGen::CodeGenFunction::isInConditionalBranch(), clang::CXXNewExpr::passAlignment(), clang::CodeGen::EHScopeStack::pushCleanupWithExtra(), clang::CodeGen::InvariantValue< T >::save(), and V.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXNewExpr().
getCXXRecord()
static CXXRecordDecl* getCXXRecord (const Expr * E) static
Definition at line 171 of file CGExprCXX.cpp.
References clang::Type::castAs(), clang::Type::getAs(), clang::RecordType::getDecl(), clang::Type::getPointeeType(), and clang::Expr::getType().
Referenced by EmitObjectDelete().
getUsualDeleteParams()
static UsualDeleteParams getUsualDeleteParams (const FunctionDecl * FD) static
Definition at line 1357 of file CGExprCXX.cpp.
References clang::Type::castAs(), clang::ValueDecl::getType(), clang::Type::isAlignValT(), clang::FunctionDecl::isDestroyingOperatorDelete(), clang::Type::isIntegerType(), clang::FunctionProtoType::param_type_begin(), and clang::FunctionProtoType::param_type_end().
Referenced by clang::CodeGen::CodeGenFunction::EmitDeleteCall().
isGLValueFromPointerDeref()
static bool isGLValueFromPointerDeref (const Expr * E) static
Definition at line 2120 of file CGExprCXX.cpp.
References clang::Expr::IgnoreParens().
Referenced by EmitTypeidFromVTable().
StoreAnyExprIntoOneUnit()
static void StoreAnyExprIntoOneUnit (CodeGenFunction & CGF, const Expr * Init, QualType AllocType, Address NewPtr, AggValueSlot::Overlap_t MayOverlap) static
Definition at line 957 of file CGExprCXX.cpp.
References clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::CodeGenFunction::EmitAggExpr(), clang::CodeGen::CodeGenFunction::EmitComplexExprIntoLValue(), clang::CodeGen::CodeGenFunction::EmitScalarInit(), clang::CodeGen::AggValueSlot::forAddr(), clang::CodeGen::CodeGenFunction::getEvaluationKind(), clang::QualType::getQualifiers(), clang::CodeGen::AggValueSlot::IsDestructed, clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::AggValueSlot::IsNotZeroed, clang::CodeGen::AggValueSlot::IsSanitizerChecked, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
Referenced by clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), and EmitNewInitializer().