clang: lib/CodeGen/CGExprComplex.cpp File Reference
CGExprComplex.cpp File Reference
#include "CGOpenMPRuntime.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "clang/AST/StmtVisitor.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include <algorithm>
Namespaces
llvm
Diagnostic wrappers for TextAPI types for error reporting.
Macros
#define HANDLEBINOP(OP)
#define HANDLE_BINOP(OP)
Typedefs
typedef CodeGenFunction::ComplexPairTy ComplexPairTy
typedef ComplexPairTy(ComplexExprEmitter::* CompoundFunc) (const ComplexExprEmitter::BinOpInfo &)
Functions
static const ComplexType * getComplexType (QualType type)
Return the complex type that we are meant to emit.
static StringRef getComplexMultiplyLibCallName (llvm::Type *Ty)
Lookup the libcall name for a given floating point type complex multiply.
static llvm::Value * EmitllvmFAbs (CodeGenFunction &CGF, llvm::Value *Value)
static CompoundFunc getComplexOp (BinaryOperatorKind Op)
Macro Definition Documentation
HANDLE_BINOP
#define HANDLE_BINOP (OP)
Value:
  case BO_##OP:                                                                \
    return EmitBin##OP(EmitBinOps(BO, PromotionType));
HANDLEBINOP
#define HANDLEBINOP (OP)
Value:
  ComplexPairTy VisitBin##OP(const BinaryOperator *E) {                        \
    QualType promotionTy = getPromotionType(                                   \
        E->getType(),                                                          \
        (E->getOpcode() == BinaryOperatorKind::BO_Div) ? true : false);        \
    ComplexPairTy result = EmitBin##OP(EmitBinOps(E, promotionTy));            \
    if (!promotionTy.isNull())                                                 \
      result = CGF.EmitUnPromotedValue(result, E->getType());                  \
    return result;                                                             \
  }
Definition at line 347 of file CGExprComplex.cpp.
Typedef Documentation
ComplexPairTy
typedef CodeGenFunction::ComplexPairTy ComplexPairTy
Definition at line 35 of file CGExprComplex.cpp.
CompoundFunc
typedef ComplexPairTy(ComplexExprEmitter::* CompoundFunc) (const ComplexExprEmitter::BinOpInfo &)
Definition at line 1512 of file CGExprComplex.cpp.
Function Documentation
EmitllvmFAbs()
static llvm::Value* EmitllvmFAbs (CodeGenFunction & CGF, llvm::Value * Value) static
Definition at line 940 of file CGExprComplex.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, fabs, clang::Func, clang::CodeGen::CodeGenModule::getIntrinsic(), and clang::Value::getType().
getComplexMultiplyLibCallName()
static StringRef getComplexMultiplyLibCallName (llvm::Type * Ty) static
Lookup the libcall name for a given floating point type complex multiply.
Definition at line 788 of file CGExprComplex.cpp.
getComplexOp()
static CompoundFunc getComplexOp (BinaryOperatorKind Op) static
Definition at line 1515 of file CGExprComplex.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitComplexCompoundAssignmentLValue(), and clang::CodeGen::CodeGenFunction::EmitScalarCompoundAssignWithComplex().
getComplexType()
static const ComplexType* getComplexType (QualType type) static
Return the complex type that we are meant to emit.
Definition at line 38 of file CGExprComplex.cpp.
References clang::ast_matchers::type.
Referenced by clang::CodeGen::CodeGenFunction::EmitComplexExpr(), and clang::CodeGen::CodeGenFunction::EmitComplexExprIntoLValue().