clang: lib/CodeGen/CGExprScalar.cpp File Reference
CGExprScalar.cpp File Reference
#include "CGCXXABI.h"
#include "CGCleanup.h"
#include "CGDebugInfo.h"
#include "CGObjCRuntime.h"
#include "CGOpenMPRuntime.h"
#include "CGRecordLayout.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Expr.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/APFixedPoint.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/FixedPointBuilder.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsPowerPC.h"
#include "llvm/IR/MatrixBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/TypeSize.h"
#include <cstdarg>
#include <optional>
Classes
struct GEPOffsetAndOverflow
Namespaces
llvm
Diagnostic wrappers for TextAPI types for error reporting.
Macros
#define HANDLEBINOP(OP)
#define VISITCOMP(CODE, UI, SI, FP, SIG)
#define HANDLE_BINOP(OP)
#define COMPOUND_OP(Op)
Enumerations
enum IntrinsicType { VCMPEQ , VCMPGT }
Functions
static std::pair< ScalarExprEmitter::ImplicitConversionCheckKind, std::pair< llvm::Value *, SanitizerMask > > EmitIntegerTruncationCheckHelper (Value *Src, QualType SrcType, Value *Dst, QualType DstType, CGBuilderTy &Builder)
static bool PromotionIsPotentiallyEligibleForImplicitIntegerConversionCheck (QualType SrcType, QualType DstType)
static llvm::Value * EmitIsNegativeTestHelper (Value *V, QualType VType, const char *Name, CGBuilderTy &Builder)
static std::pair< ScalarExprEmitter::ImplicitConversionCheckKind, std::pair< llvm::Value *, SanitizerMask > > EmitIntegerSignChangeCheckHelper (Value *Src, QualType SrcType, Value *Dst, QualType DstType, CGBuilderTy &Builder)
static std::pair< ScalarExprEmitter::ImplicitConversionCheckKind, std::pair< llvm::Value *, SanitizerMask > > EmitBitfieldTruncationCheckHelper (Value *Src, QualType SrcType, Value *Dst, QualType DstType, CGBuilderTy &Builder)
static std::pair< ScalarExprEmitter::ImplicitConversionCheckKind, std::pair< llvm::Value *, SanitizerMask > > EmitBitfieldSignChangeCheckHelper (Value *Src, QualType SrcType, Value *Dst, QualType DstType, CGBuilderTy &Builder)
static int getMaskElt (llvm::ShuffleVectorInst *SVI, unsigned Idx, unsigned Off)
static int getAsInt32 (llvm::ConstantInt *C, llvm::Type *I32Ty)
static BinOpInfo createBinOpInfoFromIncDec (const UnaryOperator *E, llvm::Value *InVal, bool IsInc, FPOptions FPFeatures)
static Value * emitPointerArithmetic (CodeGenFunction &CGF, const BinOpInfo &op, bool isSubtraction)
Emit pointer + index arithmetic.
static Value * buildFMulAdd (llvm::Instruction *MulOp, Value *Addend, const CodeGenFunction &CGF, CGBuilderTy &Builder, bool negMul, bool negAdd)
static Value * tryEmitFMulAdd (const BinOpInfo &op, const CodeGenFunction &CGF, CGBuilderTy &Builder, bool isSub=false)
static llvm::Intrinsic::ID GetIntrinsic (IntrinsicType IT, BuiltinType::Kind ElemKind)
static bool isCheapEnoughToEvaluateUnconditionally (const Expr *E, CodeGenFunction &CGF)
isCheapEnoughToEvaluateUnconditionally - Return true if the specified expression is cheap enough and side-effect-free enough to evaluate unconditionally instead of conditionally.
static Value * ConvertVec3AndVec4 (CGBuilderTy &Builder, CodeGenFunction &CGF, Value *Src, unsigned NumElementsDst)
static Value * createCastsForTypeOfSameSize (CGBuilderTy &Builder, const llvm::DataLayout &DL, Value *Src, llvm::Type *DstTy, StringRef Name="")
static GEPOffsetAndOverflow EmitGEPOffsetInBytes (Value *BasePtr, Value *GEPVal, llvm::LLVMContext &VMContext, CodeGenModule &CGM, CGBuilderTy &Builder)
Evaluate given GEPVal, which is either an inbounds GEP, or a constant, and compute the total offset it applies from it's base pointer BasePtr.
Macro Definition Documentation
COMPOUND_OP
#define COMPOUND_OP (Op)
Value:
    case BO_##Op##Assign:                                                     \
      return Scalar.EmitCompoundAssignLValue(E, &ScalarExprEmitter::Emit##Op, \
                                             Result)
HANDLE_BINOP
#define HANDLE_BINOP (OP)
Value:
  case BO_##OP:                                                                \
    return Emit##OP(EmitBinOps(BO, PromotionType));
HANDLEBINOP
#define HANDLEBINOP (OP)
Value:
  Value *VisitBin##OP(const BinaryOperator *E) {                               \
    QualType promotionTy = getPromotionType(E->getType());                     \
    auto result = Emit##OP(EmitBinOps(E, promotionTy));                        \
    if (result && !promotionTy.isNull())                                       \
      result = EmitUnPromotedValue(result, E->getType());                      \
    return result;                                                             \
  }                                                                            \
  Value *VisitBin##OP##Assign(const CompoundAssignOperator *E) {               \
    return EmitCompoundAssign(E, &ScalarExprEmitter::Emit##OP);                \
  }
Definition at line 854 of file CGExprScalar.cpp.
VISITCOMP
#define VISITCOMP (CODE, UI, SI, FP, SIG)
Value:
    Value *VisitBin##CODE(const BinaryOperator *E) { \
      return EmitCompare(E, llvm::ICmpInst::UI, llvm::ICmpInst::SI, \
                         llvm::FCmpInst::FP, SIG); }
Definition at line 881 of file CGExprScalar.cpp.
Enumeration Type Documentation
IntrinsicType
enum IntrinsicType
Enumerator
VCMPEQ
VCMPGT
Definition at line 4525 of file CGExprScalar.cpp.
Function Documentation
buildFMulAdd()
static Value* buildFMulAdd (llvm::Instruction * MulOp, Value * Addend, const CodeGenFunction & CGF, CGBuilderTy & Builder, bool negMul, bool negAdd) static
Definition at line 4001 of file CGExprScalar.cpp.
ConvertVec3AndVec4()
static Value* ConvertVec3AndVec4 (CGBuilderTy & Builder, CodeGenFunction & CGF, Value * Src, unsigned NumElementsDst) static
Definition at line 5383 of file CGExprScalar.cpp.
createBinOpInfoFromIncDec()
static BinOpInfo createBinOpInfoFromIncDec (const UnaryOperator * E, llvm::Value * InVal, bool IsInc, FPOptions FPFeatures) static
Definition at line 2727 of file CGExprScalar.cpp.
References clang::Expr::getType().
createCastsForTypeOfSameSize()
static Value* createCastsForTypeOfSameSize (CGBuilderTy & Builder, const llvm::DataLayout & DL, Value * Src, llvm::Type * DstTy, StringRef Name = "") static
Definition at line 5405 of file CGExprScalar.cpp.
EmitBitfieldSignChangeCheckHelper()
static std::pair<ScalarExprEmitter::ImplicitConversionCheckKind, std::pair<llvm::Value *, SanitizerMask> > EmitBitfieldSignChangeCheckHelper (Value * Src, QualType SrcType, Value * Dst, QualType DstType, CGBuilderTy & Builder) static
Definition at line 1290 of file CGExprScalar.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitBitfieldConversionCheck().
EmitBitfieldTruncationCheckHelper()
static std::pair<ScalarExprEmitter::ImplicitConversionCheckKind, std::pair<llvm::Value *, SanitizerMask> > EmitBitfieldTruncationCheckHelper (Value * Src, QualType SrcType, Value * Dst, QualType DstType, CGBuilderTy & Builder) static
Definition at line 1264 of file CGExprScalar.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitBitfieldConversionCheck().
EmitGEPOffsetInBytes()
static GEPOffsetAndOverflow EmitGEPOffsetInBytes (Value * BasePtr, Value * GEPVal, llvm::LLVMContext & VMContext, CodeGenModule & CGM, CGBuilderTy & Builder) static
Evaluate given GEPVal, which is either an inbounds GEP, or a constant, and compute the total offset it applies from it's base pointer BasePtr.
Returns offset in bytes and a boolean flag whether an overflow happened during evaluation.
Return the result of the given binary operation.
Definition at line 5620 of file CGExprScalar.cpp.
EmitIntegerSignChangeCheckHelper()
static std::pair<ScalarExprEmitter::ImplicitConversionCheckKind, std::pair<llvm::Value *, SanitizerMask> > EmitIntegerSignChangeCheckHelper (Value * Src, QualType SrcType, Value * Dst, QualType DstType, CGBuilderTy & Builder) static
Definition at line 1139 of file CGExprScalar.cpp.
EmitIntegerTruncationCheckHelper()
static std::pair<ScalarExprEmitter::ImplicitConversionCheckKind, std::pair<llvm::Value *, SanitizerMask> > EmitIntegerTruncationCheckHelper (Value * Src, QualType SrcType, Value * Dst, QualType DstType, CGBuilderTy & Builder) static
Definition at line 1028 of file CGExprScalar.cpp.
EmitIsNegativeTestHelper()
static llvm::Value* EmitIsNegativeTestHelper (Value * V, QualType VType, const char * Name, CGBuilderTy & Builder) static
Definition at line 1120 of file CGExprScalar.cpp.
emitPointerArithmetic()
static Value* emitPointerArithmetic (CodeGenFunction & CGF, const BinOpInfo & op, bool isSubtraction) static
Emit pointer + index arithmetic.
Definition at line 3878 of file CGExprScalar.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::Type::castAs(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateGEP(), clang::CodeGen::CodeGenFunction::EmitBoundsCheck(), clang::CodeGen::CodeGenFunction::EmitCheckedInBoundsGEP(), clang::ast_matchers::expr, clang::Type::getAs(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::CodeGen::CodeGenModule::getSize(), clang::Expr::getType(), clang::Value::getType(), clang::ASTContext::getTypeSizeInChars(), clang::CodeGen::CodeGenFunction::getVLASize(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::Type::isFunctionType(), clang::BinaryOperator::isNullPointerArithmeticExtension(), clang::Type::isSignedIntegerOrEnumerationType(), clang::LangOptions::isSignedOverflowDefined(), clang::Type::isVoidType(), clang::CodeGen::CodeGenFunction::VlaSizePair::NumElts, clang::ast_matchers::pointerType, and clang::CodeGen::CodeGenFunction::SanOpts.
getAsInt32()
static int getAsInt32 (llvm::ConstantInt * C, llvm::Type * I32Ty) static
Definition at line 2015 of file CGExprScalar.cpp.
GetIntrinsic()
static llvm::Intrinsic::ID GetIntrinsic (IntrinsicType IT, BuiltinType::Kind ElemKind) static
Definition at line 4527 of file CGExprScalar.cpp.
References clang::RISCV::Float, and VCMPEQ.
getMaskElt()
static int getMaskElt (llvm::ShuffleVectorInst * SVI, unsigned Idx, unsigned Off) static
Definition at line 2007 of file CGExprScalar.cpp.
isCheapEnoughToEvaluateUnconditionally()
static bool isCheapEnoughToEvaluateUnconditionally (const Expr * E, CodeGenFunction & CGF) static
isCheapEnoughToEvaluateUnconditionally - Return true if the specified expression is cheap enough and side-effect-free enough to evaluate unconditionally instead of conditionally.
This is used to convert control flow into selects in some cases.
Definition at line 5138 of file CGExprScalar.cpp.
References clang::CodeGen::CodeGenFunction::getContext(), clang::Expr::IgnoreParens(), and clang::Expr::isEvaluatable().
PromotionIsPotentiallyEligibleForImplicitIntegerConversionCheck()
static bool PromotionIsPotentiallyEligibleForImplicitIntegerConversionCheck (QualType SrcType, QualType DstType) static
Definition at line 1064 of file CGExprScalar.cpp.
References clang::Type::isIntegerType().
Referenced by clang::CodeGen::CodeGenFunction::EmitBitfieldConversionCheck().
tryEmitFMulAdd()
static Value* tryEmitFMulAdd (const BinOpInfo & op, const CodeGenFunction & CGF, CGBuilderTy & Builder, bool isSub = false) static
Definition at line 4036 of file CGExprScalar.cpp.