clang: lib/CodeGen/CGNonTrivialStruct.cpp File Reference
CGNonTrivialStruct.cpp File Reference
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "clang/AST/NonTrivialTypeVisitor.h"
#include "clang/CodeGen/CodeGenABITypes.h"
#include "llvm/Support/ScopedPrinter.h"
#include <array>
Functions
static uint64_t getFieldSize (const FieldDecl *FD, QualType FT, ASTContext &Ctx)
template<class G , size_t N>
static void callSpecialFunction (G &&Gen, StringRef FuncName, QualType QT, bool IsVolatile, CodeGenFunction &CGF, std::array< Address, N > Addrs)
template<class G , size_t N>
static llvm::Function * getSpecialFunction (G &&Gen, StringRef FuncName, QualType QT, bool IsVolatile, std::array< CharUnits, N > Alignments, CodeGenModule &CGM)
Function Documentation
callSpecialFunction()
template<class G , size_t N> static void callSpecialFunction (G && Gen, StringRef FuncName, QualType QT, bool IsVolatile, CodeGenFunction & CGF, std::array< Address, N > Addrs) static
Definition at line 829 of file CGNonTrivialStruct.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and clang::QualType::withVolatile().
Referenced by clang::CodeGen::CodeGenFunction::callCStructCopyAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructCopyConstructor(), clang::CodeGen::CodeGenFunction::callCStructDefaultConstructor(), clang::CodeGen::CodeGenFunction::callCStructDestructor(), clang::CodeGen::CodeGenFunction::callCStructMoveAssignmentOperator(), and clang::CodeGen::CodeGenFunction::callCStructMoveConstructor().
getFieldSize()
static uint64_t getFieldSize (const FieldDecl * FD, QualType FT, ASTContext & Ctx) static
Definition at line 25 of file CGNonTrivialStruct.cpp.
References clang::FieldDecl::getBitWidthValue(), clang::ASTContext::getTypeSize(), and clang::FieldDecl::isBitField().
getSpecialFunction()
template<class G , size_t N> static llvm::Function* getSpecialFunction (G && Gen, StringRef FuncName, QualType QT, bool IsVolatile, std::array< CharUnits, N > Alignments, CodeGenModule & CGM) static
Definition at line 841 of file CGNonTrivialStruct.cpp.
References clang::QualType::withVolatile().
Referenced by clang::CodeGen::getNonTrivialCStructCopyAssignmentOperator(), clang::CodeGen::getNonTrivialCStructCopyConstructor(), clang::CodeGen::getNonTrivialCStructDefaultConstructor(), clang::CodeGen::getNonTrivialCStructDestructor(), clang::CodeGen::getNonTrivialCStructMoveAssignmentOperator(), and clang::CodeGen::getNonTrivialCStructMoveConstructor().