clang: lib/CodeGen/CGObjC.cpp File Reference
CGObjC.cpp File Reference
#include "CGDebugInfo.h"
#include "CGObjCRuntime.h"
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "ConstantEmitter.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/StmtObjC.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/CodeGen/CGFunctionInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/ObjCARCUtil.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/InlineAsm.h"
Typedefs
typedef llvm::PointerIntPair< llvm::Value *, 1, bool > TryEmitResult
typedef llvm::function_ref< llvm::Value *(CodeGenFunction &CGF, llvm::Value *value)> ValueTransform
Functions
static TryEmitResult tryEmitARCRetainScalarExpr (CodeGenFunction &CGF, const Expr *e)
static RValue AdjustObjCObjectType (CodeGenFunction &CGF, QualType ExpT, RValue Result)
Adjust the type of an Objective-C object that doesn't match up due to type erasure at various points, e.g., related result types or the use of parameterized classes.
static llvm::Constant * getNullForVariable (Address addr)
Given the address of a variable of pointer type, find the correct null to store into it.
static bool shouldExtendReceiverForInnerPointerMessage (const ObjCMessageExpr *message)
Decide whether to extend the lifetime of the receiver of a returns-inner-pointer message.
static const Expr * findWeakLValue (const Expr *E)
Given an expression of ObjC pointer type, check whether it was immediately loaded from an ARC __weak l-value.
static Optional< llvm::Value * > tryGenerateSpecializedMessageSend (CodeGenFunction &CGF, QualType ResultType, llvm::Value *Receiver, const CallArgList &Args, Selector Sel, const ObjCMethodDecl *method, bool isClassMessage)
The ObjC runtime may provide entrypoints that are likely to be faster than an ordinary message send of the appropriate selector.
static void AppendFirstImpliedRuntimeProtocols (const ObjCProtocolDecl *PD, llvm::UniqueVector< const ObjCProtocolDecl * > &PDs)
static Optional< llvm::Value * > tryEmitSpecializedAllocInit (CodeGenFunction &CGF, const ObjCMessageExpr *OME)
Instead of '[[MyClass alloc] init]', try to generate 'objc_alloc_init(MyClass)'.
static llvm::Value * emitARCRetainLoadOfScalar (CodeGenFunction &CGF, LValue lvalue, QualType type)
static void emitStructGetterCall (CodeGenFunction &CGF, ObjCIvarDecl *ivar, bool isAtomic, bool hasStrong)
emitStructGetterCall - Call the runtime function to load a property into the return value slot.
static bool hasUnalignedAtomics (llvm::Triple::ArchType arch)
Determine whether the given architecture supports unaligned atomic accesses.
static CharUnits getMaxAtomicAccessSize (CodeGenModule &CGM, llvm::Triple::ArchType arch)
Return the maximum size that permits atomic accesses for the given architecture.
static bool hasTrivialGetExpr (const ObjCPropertyImplDecl *propImpl)
static void emitCPPObjectAtomicGetterCall (CodeGenFunction &CGF, llvm::Value *returnAddr, ObjCIvarDecl *ivar, llvm::Constant *AtomicHelperFn)
emitCPPObjectAtomicGetterCall - Call the runtime function to copy the ivar into the resturn slot.
static void emitStructSetterCall (CodeGenFunction &CGF, ObjCMethodDecl *OMD, ObjCIvarDecl *ivar)
emitStructSetterCall - Call the runtime function to store the value from the first formal parameter into the given ivar.
static void emitCPPObjectAtomicSetterCall (CodeGenFunction &CGF, ObjCMethodDecl *OMD, ObjCIvarDecl *ivar, llvm::Constant *AtomicHelperFn)
emitCPPObjectAtomicSetterCall - Call the runtime function to store the value from the first formal parameter into the given ivar, using the Cpp API for atomic Cpp objects with non-trivial copy assignment.
static bool hasTrivialSetExpr (const ObjCPropertyImplDecl *PID)
static bool UseOptimizedSetter (CodeGenModule &CGM)
static void destroyARCStrongWithStore (CodeGenFunction &CGF, Address addr, QualType type)
Like CodeGenFunction::destroyARCStrong, but do it with a call.
static void emitCXXDestructMethod (CodeGenFunction &CGF, ObjCImplementationDecl *impl)
static void setARCRuntimeFunctionLinkage (CodeGenModule &CGM, llvm::Value *RTF)
static void setARCRuntimeFunctionLinkage (CodeGenModule &CGM, llvm::FunctionCallee RTF)
static llvm::Value * emitARCValueOperation (CodeGenFunction &CGF, llvm::Value *value, llvm::Type *returnType, llvm::Function *&fn, llvm::Intrinsic::ID IntID, llvm::CallInst::TailCallKind tailKind=llvm::CallInst::TCK_None)
Perform an operation having the signature i8* (i8*) where a null input causes a no-op and returns null.
static llvm::Value * emitARCLoadOperation (CodeGenFunction &CGF, Address addr, llvm::Function *&fn, llvm::Intrinsic::ID IntID)
Perform an operation having the following signature: i8* (i8**)
static llvm::Value * emitARCStoreOperation (CodeGenFunction &CGF, Address addr, llvm::Value *value, llvm::Function *&fn, llvm::Intrinsic::ID IntID, bool ignored)
Perform an operation having the following signature: i8* (i8**, i8*)
static void emitARCCopyOperation (CodeGenFunction &CGF, Address dst, Address src, llvm::Function *&fn, llvm::Intrinsic::ID IntID)
Perform an operation having the following signature: void (i8**, i8**)
static llvm::Value * emitObjCValueOperation (CodeGenFunction &CGF, llvm::Value *value, llvm::Type *returnType, llvm::FunctionCallee &fn, StringRef fnName)
Perform an operation having the signature i8* (i8*) where a null input causes a no-op and returns null.
static void emitAutoreleasedReturnValueMarker (CodeGenFunction &CGF)
static llvm::Value * emitOptimizedARCReturnCall (llvm::Value *value, bool IsRetainRV, CodeGenFunction &CGF)
static bool shouldRetainObjCLifetime (Qualifiers::ObjCLifetime lifetime)
static TryEmitResult tryEmitARCRetainLoadOfScalar (CodeGenFunction &CGF, LValue lvalue, QualType type)
static TryEmitResult tryEmitARCRetainLoadOfScalar (CodeGenFunction &CGF, const Expr *e)
static llvm::Value * emitARCOperationAfterCall (CodeGenFunction &CGF, llvm::Value *value, ValueTransform doAfterCall, ValueTransform doFallback)
Insert code immediately after a call.
static llvm::Value * emitARCRetainCallResult (CodeGenFunction &CGF, const Expr *e)
Given that the given expression is some sort of call (which does not return retained), emit a retain following it.
static llvm::Value * emitARCUnsafeClaimCallResult (CodeGenFunction &CGF, const Expr *e)
Given that the given expression is some sort of call (which does not return retained), perform an unsafeClaim following it.
static bool shouldEmitSeparateBlockRetain (const Expr *e)
Determine whether it might be important to emit a separate objc_retain_block on the result of the given expression, or whether it's okay to just emit it in a +1 context.
static llvm::Value * emitARCUnsafeUnretainedScalarExpr (CodeGenFunction &CGF, const Expr *e)
static unsigned getBaseMachOPlatformID (const llvm::Triple &TT)
static llvm::Value * emitIsPlatformVersionAtLeast (CodeGenFunction &CGF, const VersionTuple &Version)
static bool isFoundationNeededForDarwinAvailabilityCheck (const llvm::Triple &TT, const VersionTuple &TargetVersion)
Typedef Documentation
TryEmitResult
typedef llvm::PointerIntPair<llvm::Value*,1,bool> TryEmitResult
Definition at line 33 of file CGObjC.cpp.
ValueTransform
typedef llvm::function_ref<llvm::Value *(CodeGenFunction &CGF, llvm::Value *value)> ValueTransform
Definition at line 2931 of file CGObjC.cpp.
Function Documentation
AdjustObjCObjectType()
static RValue AdjustObjCObjectType (CodeGenFunction & CGF, QualType ET, RValue Result) static
Adjust the type of an Objective-C object that doesn't match up due to type erasure at various points, e.g., related result types or the use of parameterized classes.
Definition at line 269 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::RValue::get(), and clang::Type::isObjCRetainableType().
Referenced by clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr().
AppendFirstImpliedRuntimeProtocols()
static void AppendFirstImpliedRuntimeProtocols (const ObjCProtocolDecl * PD, llvm::UniqueVector< const ObjCProtocolDecl * > & PDs) static
Definition at line 450 of file CGObjC.cpp.
References clang::ObjCProtocolDecl::getCanonicalDecl(), clang::ObjCProtocolDecl::isNonRuntimeProtocol(), and clang::ObjCProtocolDecl::protocols().
Referenced by clang::CodeGen::CGObjCRuntime::GetRuntimeProtocolList().
destroyARCStrongWithStore()
static void destroyARCStrongWithStore (CodeGenFunction & CGF, Address addr, QualType type) static
Like CodeGenFunction::destroyARCStrong, but do it with a call.
Definition at line 1612 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::EmitARCStoreStrongCall(), and getNullForVariable().
Referenced by emitCXXDestructMethod().
emitARCCopyOperation()
static void emitARCCopyOperation (CodeGenFunction & CGF, Address dst, Address src, llvm::Function *& fn, llvm::Intrinsic::ID IntID) static
Perform an operation having the following signature: void (i8**, i8**)
Definition at line 2189 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::Address::getPointer(), clang::CodeGen::Address::getType(), clang::CodeGen::CodeGenTypeCache::Int8PtrPtrTy, and setARCRuntimeFunctionLinkage().
Referenced by clang::CodeGen::CodeGenFunction::EmitARCCopyWeak(), and clang::CodeGen::CodeGenFunction::EmitARCMoveWeak().
emitARCLoadOperation()
static llvm::Value* emitARCLoadOperation (CodeGenFunction & CGF, Address addr, llvm::Function *& fn, llvm::Intrinsic::ID IntID) static
Perform an operation having the following signature: i8* (i8**)
Definition at line 2138 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::Int8PtrPtrTy, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and setARCRuntimeFunctionLinkage().
Referenced by clang::CodeGen::CodeGenFunction::EmitARCLoadWeak(), and clang::CodeGen::CodeGenFunction::EmitARCLoadWeakRetained().
emitARCOperationAfterCall()
static llvm::Value* emitARCOperationAfterCall (CodeGenFunction & CGF, llvm::Value * value, ValueTransform doAfterCall, ValueTransform doFallback) static
Insert code immediately after a call.
Definition at line 2937 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder.
Referenced by emitARCRetainCallResult(), and emitARCUnsafeClaimCallResult().
emitARCRetainCallResult()
static llvm::Value* emitARCRetainCallResult (CodeGenFunction & CGF, const Expr * e) static
Given that the given expression is some sort of call (which does not return retained), emit a retain following it.
Definition at line 2993 of file CGObjC.cpp.
References emitARCOperationAfterCall(), clang::CodeGen::CodeGenFunction::EmitARCRetainAutoreleasedReturnValue(), clang::CodeGen::CodeGenFunction::EmitARCRetainNonBlock(), and clang::CodeGen::CodeGenFunction::EmitScalarExpr().
Referenced by clang::CodeGen::CodeGenFunction::EmitARCReclaimReturnedObject().
emitARCRetainLoadOfScalar()
static llvm::Value * emitARCRetainLoadOfScalar (CodeGenFunction & CGF, LValue lvalue, QualType type) static
Definition at line 3408 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::EmitARCRetain(), and tryEmitARCRetainLoadOfScalar().
Referenced by clang::CodeGen::CodeGenFunction::generateObjCGetterBody().
emitARCStoreOperation()
static llvm::Value* emitARCStoreOperation (CodeGenFunction & CGF, Address addr, llvm::Value * value, llvm::Function *& fn, llvm::Intrinsic::ID IntID, bool ignored) static
Perform an operation having the following signature: i8* (i8**, i8*)
Definition at line 2162 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenTypeCache::Int8PtrPtrTy, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and setARCRuntimeFunctionLinkage().
Referenced by clang::CodeGen::CodeGenFunction::EmitARCInitWeak(), and clang::CodeGen::CodeGenFunction::EmitARCStoreWeak().
emitARCUnsafeClaimCallResult()
static llvm::Value* emitARCUnsafeClaimCallResult (CodeGenFunction & CGF, const Expr * e) static
Given that the given expression is some sort of call (which does not return retained), perform an unsafeClaim following it.
Definition at line 3007 of file CGObjC.cpp.
References emitARCOperationAfterCall(), clang::CodeGen::CodeGenFunction::EmitARCUnsafeClaimAutoreleasedReturnValue(), and clang::CodeGen::CodeGenFunction::EmitScalarExpr().
Referenced by clang::CodeGen::CodeGenFunction::EmitARCReclaimReturnedObject().
emitARCUnsafeUnretainedScalarExpr()
static llvm::Value* emitARCUnsafeUnretainedScalarExpr (CodeGenFunction & CGF, const Expr * e) static
Definition at line 3538 of file CGObjC.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitARCUnsafeUnretainedScalarExpr().
emitARCValueOperation()
static llvm::Value* emitARCValueOperation (CodeGenFunction & CGF, llvm::Value * value, llvm::Type * returnType, llvm::Function *& fn, llvm::Intrinsic::ID IntID, llvm::CallInst::TailCallKind tailKind = llvm::CallInst::TCK_None) static
Perform an operation having the signature i8* (i8*) where a null input causes a no-op and returns null.
Definition at line 2112 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and setARCRuntimeFunctionLinkage().
Referenced by clang::CodeGen::CodeGenFunction::EmitARCAutorelease(), clang::CodeGen::CodeGenFunction::EmitARCAutoreleaseReturnValue(), clang::CodeGen::CodeGenFunction::EmitARCRetainAutoreleaseNonBlock(), clang::CodeGen::CodeGenFunction::EmitARCRetainAutoreleaseReturnValue(), clang::CodeGen::CodeGenFunction::EmitARCRetainBlock(), clang::CodeGen::CodeGenFunction::EmitARCRetainNonBlock(), and emitOptimizedARCReturnCall().
emitAutoreleasedReturnValueMarker()
static void emitAutoreleasedReturnValueMarker (CodeGenFunction & CGF) static
Definition at line 2293 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::TargetCodeGenInfo::getARCRetainAutoreleasedReturnValueMarker(), clang::CodeGen::CodeGenFunction::getBundlesForFunclet(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenFunction::getLLVMContext(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::CodeGen::ObjCEntrypoints::retainAutoreleasedReturnValueMarker, and clang::CodeGen::CodeGenTypeCache::VoidTy.
Referenced by emitOptimizedARCReturnCall().
emitCPPObjectAtomicGetterCall()
static void emitCPPObjectAtomicGetterCall (CodeGenFunction & CGF, llvm::Value * returnAddr, ObjCIvarDecl * ivar, llvm::Constant * AtomicHelperFn) static
emitCPPObjectAtomicGetterCall - Call the runtime function to copy the ivar into the resturn slot.
Definition at line 1081 of file CGObjC.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionCall(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitLValueForIvar(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CGObjCRuntime::GetCppAtomicObjectGetFunction(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::LValue::getPointer(), clang::CodeGen::CodeGenFunction::getTypes(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenFunction::LoadObjCSelf(), clang::CodeGen::CodeGenFunction::TypeOfSelfObject(), clang::ASTContext::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by clang::CodeGen::CodeGenFunction::generateObjCGetterBody().
emitCPPObjectAtomicSetterCall()
static void emitCPPObjectAtomicSetterCall (CodeGenFunction & CGF, ObjCMethodDecl * OMD, ObjCIvarDecl * ivar, llvm::Constant * AtomicHelperFn) static
emitCPPObjectAtomicSetterCall - Call the runtime function to store the value from the first formal parameter into the given ivar, using the Cpp API for atomic Cpp objects with non-trivial copy assignment.
Definition at line 1333 of file CGObjC.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionCall(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForIvar(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CGObjCRuntime::GetCppAtomicObjectSetFunction(), clang::QualType::getNonReferenceType(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::LValue::getPointer(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenFunction::getTypes(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenFunction::LoadObjCSelf(), clang::ObjCMethodDecl::param_begin(), clang::CodeGen::CodeGenFunction::TypeOfSelfObject(), clang::VK_LValue, clang::ASTContext::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by clang::CodeGen::CodeGenFunction::generateObjCSetterBody().
emitCXXDestructMethod()
static void emitCXXDestructMethod (CodeGenFunction & CGF, ObjCImplementationDecl * impl) static
Definition at line 1619 of file CGObjC.cpp.
References clang::ObjCInterfaceDecl::all_declared_ivar_begin(), destroyARCStrongWithStore(), clang::QualType::DK_objc_strong_lifetime, clang::CodeGen::EHCleanup, clang::CodeGen::CodeGenFunction::EHStack, clang::ObjCImplDecl::getClassInterface(), clang::CodeGen::CodeGenFunction::getCleanupKind(), clang::CodeGen::CodeGenFunction::getDestroyer(), clang::ObjCIvarDecl::getNextIvar(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenFunction::LoadObjCSelf(), and clang::CodeGen::CodeGenFunction::RunCleanupsScope::requiresCleanups().
emitIsPlatformVersionAtLeast()
static llvm::Value* emitIsPlatformVersionAtLeast (CodeGenFunction & CGF, const VersionTuple & Version) static
Definition at line 3905 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall(), getBaseMachOPlatformID(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTriple(), clang::CodeGen::CodeGenTypeCache::Int32Ty, and clang::CodeGen::CodeGenModule::IsPlatformVersionAtLeastFn.
Referenced by clang::CodeGen::CodeGenFunction::EmitBuiltinAvailable().
emitObjCValueOperation()
static llvm::Value* emitObjCValueOperation (CodeGenFunction & CGF, llvm::Value * value, llvm::Type * returnType, llvm::FunctionCallee & fn, StringRef fnName) static
Perform an operation having the signature i8* (i8*) where a null input causes a no-op and returns null.
Definition at line 2209 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CodeGenFunction::EmitCallOrInvoke(), and clang::CodeGen::CodeGenTypeCache::Int8PtrTy.
Referenced by clang::CodeGen::CodeGenFunction::EmitObjCAlloc(), clang::CodeGen::CodeGenFunction::EmitObjCAllocInit(), clang::CodeGen::CodeGenFunction::EmitObjCAllocWithZone(), clang::CodeGen::CodeGenFunction::EmitObjCAutorelease(), and clang::CodeGen::CodeGenFunction::EmitObjCRetainNonBlock().
emitOptimizedARCReturnCall()
static llvm::Value* emitOptimizedARCReturnCall (llvm::Value * value, bool IsRetainRV, CodeGenFunction & CGF) static
Definition at line 2332 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::EmitARCNoopIntrinsicUse(), emitARCValueOperation(), emitAutoreleasedReturnValueMarker(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), clang::CodeGen::CodeGenModule::getTarget(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::TargetInfo::getTriple(), clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::TargetCodeGenInfo::markARCOptimizedReturnCallsAsNoTail(), clang::CodeGen::ObjCEntrypoints::objc_retainAutoreleasedReturnValue, and clang::CodeGen::ObjCEntrypoints::objc_unsafeClaimAutoreleasedReturnValue.
Referenced by clang::CodeGen::CodeGenFunction::EmitARCRetainAutoreleasedReturnValue(), and clang::CodeGen::CodeGenFunction::EmitARCUnsafeClaimAutoreleasedReturnValue().
emitStructGetterCall()
static void emitStructGetterCall (CodeGenFunction & CGF, ObjCIvarDecl * ivar, bool isAtomic, bool hasStrong) static
emitStructGetterCall - Call the runtime function to load a property into the return value slot.
Definition at line 815 of file CGObjC.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionCall(), clang::ASTContext::BoolTy, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitLValueForIvar(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::CGObjCRuntime::GetGetStructFunction(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::Address::getPointer(), clang::CodeGen::CodeGenModule::getSize(), clang::ASTContext::getSizeType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenFunction::getTypes(), clang::ASTContext::getTypeSizeInChars(), clang::CodeGen::CodeGenFunction::LoadObjCSelf(), clang::CodeGen::CodeGenFunction::ReturnValue, clang::CodeGen::CodeGenFunction::TypeOfSelfObject(), clang::CodeGen::CodeGenTypeCache::VoidPtrTy, clang::ASTContext::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by clang::CodeGen::CodeGenFunction::generateObjCGetterBody().
emitStructSetterCall()
static void emitStructSetterCall (CodeGenFunction & CGF, ObjCMethodDecl * OMD, ObjCIvarDecl * ivar) static
emitStructSetterCall - Call the runtime function to store the value from the first formal parameter into the given ivar.
Definition at line 1289 of file CGObjC.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionCall(), clang::ASTContext::BoolTy, clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateBitCast(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForIvar(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenFunction::getContext(), clang::QualType::getNonReferenceType(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::LValue::getPointer(), clang::CodeGen::CGObjCRuntime::GetSetStructFunction(), clang::CodeGen::CodeGenModule::getSize(), clang::ASTContext::getSizeType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenFunction::getTypes(), clang::ASTContext::getTypeSizeInChars(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenFunction::LoadObjCSelf(), clang::ObjCMethodDecl::param_begin(), clang::CodeGen::CodeGenFunction::TypeOfSelfObject(), clang::VK_LValue, clang::ASTContext::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by clang::CodeGen::CodeGenFunction::generateObjCSetterBody().
findWeakLValue()
static const Expr* findWeakLValue (const Expr * E) static
Given an expression of ObjC pointer type, check whether it was immediately loaded from an ARC __weak l-value.
Definition at line 346 of file CGObjC.cpp.
References clang::Expr::getType(), clang::Expr::IgnoreParens(), clang::Type::isObjCRetainableType(), and clang::Qualifiers::OCL_Weak.
Referenced by clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr().
getBaseMachOPlatformID()
static unsigned getBaseMachOPlatformID (const llvm::Triple & TT) static
Definition at line 3889 of file CGObjC.cpp.
Referenced by emitIsPlatformVersionAtLeast().
getMaxAtomicAccessSize()
static CharUnits getMaxAtomicAccessSize (CodeGenModule & CGM, llvm::Triple::ArchType arch) static
Return the maximum size that permits atomic accesses for the given architecture.
Definition at line 855 of file CGObjC.cpp.
References clang::CharUnits::fromQuantity(), and clang::CodeGen::CodeGenTypeCache::PointerSizeInBytes.
getNullForVariable()
static llvm::Constant* getNullForVariable (Address addr) static
Given the address of a variable of pointer type, find the correct null to store into it.
Definition at line 42 of file CGObjC.cpp.
References clang::CodeGen::Address::getElementType().
Referenced by destroyARCStrongWithStore(), clang::CodeGen::CodeGenFunction::EmitARCDestroyStrong(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), and tryEmitARCRetainLoadOfScalar().
hasTrivialGetExpr()
static bool hasTrivialGetExpr (const ObjCPropertyImplDecl * propImpl) static
Definition at line 1056 of file CGObjC.cpp.
References clang::ObjCPropertyImplDecl::getGetterCXXConstructor(), and clang::Expr::isGLValue().
Referenced by clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), and clang::CodeGen::CodeGenFunction::generateObjCGetterBody().
hasTrivialSetExpr()
static bool hasTrivialSetExpr (const ObjCPropertyImplDecl * PID) static
Definition at line 1369 of file CGObjC.cpp.
References clang::ObjCPropertyImplDecl::getSetterCXXAssignment().
Referenced by clang::CodeGen::CodeGenFunction::GenerateObjCAtomicSetterCopyHelperFunction(), and clang::CodeGen::CodeGenFunction::generateObjCSetterBody().
hasUnalignedAtomics()
static bool hasUnalignedAtomics (llvm::Triple::ArchType arch) static
Determine whether the given architecture supports unaligned atomic accesses.
They don't have to be fast, just faster than a function call and a mutex.
Definition at line 847 of file CGObjC.cpp.
isFoundationNeededForDarwinAvailabilityCheck()
static bool isFoundationNeededForDarwinAvailabilityCheck (const llvm::Triple & TT, const VersionTuple & TargetVersion) static
Definition at line 3965 of file CGObjC.cpp.
setARCRuntimeFunctionLinkage() [1/2]
static void setARCRuntimeFunctionLinkage (CodeGenModule & CGM, llvm::FunctionCallee RTF) static
Definition at line 2104 of file CGObjC.cpp.
References setARCRuntimeFunctionLinkage().
setARCRuntimeFunctionLinkage() [2/2]
static void setARCRuntimeFunctionLinkage (CodeGenModule & CGM, llvm::Value * RTF) static
Definition at line 2092 of file CGObjC.cpp.
References clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getTriple(), clang::ObjCRuntime::hasNativeARC(), and clang::LangOptions::ObjCRuntime.
Referenced by emitARCCopyOperation(), clang::CodeGen::CodeGenFunction::EmitARCDestroyWeak(), emitARCLoadOperation(), clang::CodeGen::CodeGenFunction::EmitARCRelease(), emitARCStoreOperation(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrongCall(), emitARCValueOperation(), clang::CodeGen::CodeGenFunction::EmitObjCAutoreleasePoolPop(), clang::CodeGen::CodeGenFunction::EmitObjCAutoreleasePoolPush(), clang::CodeGen::CodeGenFunction::EmitObjCRelease(), and setARCRuntimeFunctionLinkage().
shouldEmitSeparateBlockRetain()
static bool shouldEmitSeparateBlockRetain (const Expr * e) static
Determine whether it might be important to emit a separate objc_retain_block on the result of the given expression, or whether it's okay to just emit it in a +1 context.
Definition at line 3033 of file CGObjC.cpp.
References clang::cast(), clang::Expr::getType(), clang::Expr::IgnoreParens(), and clang::Type::isBlockPointerType().
Referenced by clang::CodeGen::CodeGenFunction::EmitARCExtendBlockObject().
shouldExtendReceiverForInnerPointerMessage()
static bool shouldExtendReceiverForInnerPointerMessage (const ObjCMessageExpr * message) static
Decide whether to extend the lifetime of the receiver of a returns-inner-pointer message.
Definition at line 287 of file CGObjC.cpp.
References clang::ObjCMessageExpr::Class, clang::CastExpr::getCastKind(), clang::DeclRefExpr::getDecl(), clang::ObjCMessageExpr::getInstanceReceiver(), clang::QualType::getObjCLifetime(), clang::ObjCMessageExpr::getReceiverKind(), clang::CastExpr::getSubExpr(), clang::Expr::getType(), clang::Decl::hasAttr(), clang::VarDecl::hasLocalStorage(), clang::Expr::IgnoreParens(), clang::ObjCMessageExpr::Instance, clang::Qualifiers::OCL_Strong, clang::ObjCMessageExpr::SuperClass, and clang::ObjCMessageExpr::SuperInstance.
Referenced by clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr().
shouldRetainObjCLifetime()
static bool shouldRetainObjCLifetime (Qualifiers::ObjCLifetime lifetime) static
Definition at line 2853 of file CGObjC.cpp.
References clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, and clang::Qualifiers::OCL_Weak.
Referenced by tryEmitARCRetainLoadOfScalar().
tryEmitARCRetainLoadOfScalar() [1/2]
static TryEmitResult tryEmitARCRetainLoadOfScalar (CodeGenFunction & CGF, const Expr * e) static
Definition at line 2882 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::CodeGenFunction::emitScalarConstant(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenFunction::getLangOpts(), getNullForVariable(), clang::CodeGen::RValue::getScalarVal(), clang::Expr::getType(), clang::Expr::IgnoreParens(), clang::Expr::isXValue(), clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, shouldRetainObjCLifetime(), tryEmitARCRetainLoadOfScalar(), and clang::CodeGen::CodeGenFunction::tryEmitAsConstant().
tryEmitARCRetainLoadOfScalar() [2/2]
static TryEmitResult tryEmitARCRetainLoadOfScalar (CodeGenFunction & CGF, LValue lvalue, QualType type) static
Definition at line 2868 of file CGObjC.cpp.
References clang::CodeGen::CodeGenFunction::EmitARCLoadWeakRetained(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::RValue::getScalarVal(), clang::Qualifiers::OCL_Weak, and shouldRetainObjCLifetime().
Referenced by emitARCRetainLoadOfScalar(), and tryEmitARCRetainLoadOfScalar().
tryEmitARCRetainScalarExpr()
static TryEmitResult tryEmitARCRetainScalarExpr (CodeGenFunction & CGF, const Expr * e) static
Definition at line 3404 of file CGObjC.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitARCExtendBlockObject(), clang::CodeGen::CodeGenFunction::EmitARCRetainAutoreleaseScalarExpr(), clang::CodeGen::CodeGenFunction::EmitARCRetainScalarExpr(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrong(), and clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr().
tryEmitSpecializedAllocInit()
static Optional<llvm::Value *> tryEmitSpecializedAllocInit (CodeGenFunction & CGF, const ObjCMessageExpr * OME) static
Instead of '[[MyClass alloc] init]', try to generate 'objc_alloc_init(MyClass)'.
This provides a code size improvement on the caller side, as well as the optimized objc_alloc.
Definition at line 523 of file CGObjC.cpp.
References clang::Type::castAs(), clang::CodeGen::CodeGenFunction::CGM, clang::ObjCMessageExpr::Class, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::EmitObjCAllocInit(), clang::CodeGen::CodeGenFunction::EmitScalarExpr(), clang::CodeGen::CGObjCRuntime::GetClass(), clang::ObjCMessageExpr::getInstanceReceiver(), clang::ObjCObjectType::getInterface(), clang::CodeGen::CodeGenFunction::getLangOpts(), clang::Selector::getNameForSlot(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::ObjCMessageExpr::getReceiverKind(), clang::ObjCMessageExpr::getSelector(), clang::Expr::getType(), clang::Expr::IgnoreParenCasts(), clang::ObjCMessageExpr::Instance, clang::Type::isObjCObjectPointerType(), clang::Selector::isUnarySelector(), clang::LangOptions::ObjCRuntime, clang::ObjCMessageExpr::SuperClass, and clang::ObjCMessageExpr::SuperInstance.
Referenced by clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr().
tryGenerateSpecializedMessageSend()
static Optional<llvm::Value *> tryGenerateSpecializedMessageSend (CodeGenFunction & CGF, QualType ResultType, llvm::Value * Receiver, const CallArgList & Args, Selector Sel, const ObjCMethodDecl * method, bool isClassMessage) static
The ObjC runtime may provide entrypoints that are likely to be faster than an ordinary message send of the appropriate selector.
The entrypoints are guaranteed to be equivalent to just sending the corresponding message. If the entrypoint is implemented naively as just a message send, using it is a trade-off: it sacrifices a few cycles of overhead to save a small amount of code. However, it's possible for runtimes to detect and special-case classes that use "standard" behavior; if that's dynamically a large proportion of all objects, using the entrypoint will also be faster than using a message send.
If the runtime does support a required entrypoint, then this method will generate a call and return the resulting value. Otherwise it will return None and the caller can generate a msgSend instead.
Definition at line 374 of file CGObjC.cpp.
References clang::CodeGen::ARCPreciseLifetime, std::arg(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertType(), clang::CodeGen::CodeGenFunction::EmitObjCAlloc(), clang::CodeGen::CodeGenFunction::EmitObjCAllocWithZone(), clang::CodeGen::CodeGenFunction::EmitObjCAutorelease(), clang::CodeGen::CodeGenFunction::EmitObjCRelease(), clang::CodeGen::CodeGenFunction::EmitObjCRetainNonBlock(), clang::Selector::getMethodFamily(), clang::Selector::getNameForSlot(), clang::Selector::getNumArgs(), clang::Selector::isKeywordSelector(), clang::Type::isObjCObjectPointerType(), clang::Selector::isUnarySelector(), clang::Type::isVoidType(), clang::LangOptions::NonGC, clang::OMF_alloc, clang::OMF_autorelease, clang::OMF_release, and clang::OMF_retain.
Referenced by clang::CodeGen::CGObjCRuntime::GeneratePossiblySpecializedMessageSend().
UseOptimizedSetter()
static bool UseOptimizedSetter (CodeGenModule & CGM) static
Definition at line 1393 of file CGObjC.cpp.
References clang::CodeGen::CodeGenModule::getLangOpts(), clang::ObjCRuntime::hasOptimizedSetter(), clang::LangOptions::NonGC, and clang::LangOptions::ObjCRuntime.
Referenced by clang::CodeGen::CodeGenFunction::generateObjCSetterBody().