clang: lib/CodeGen/CGOpenCLRuntime.cpp File Reference
CGOpenCLRuntime.cpp File Reference
#include "CGOpenCLRuntime.h"
#include "CodeGenFunction.h"
#include "TargetInfo.h"
#include "clang/CodeGen/ConstantInitBuilder.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalValue.h"
#include <assert.h>
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/OpenCLExtensionTypes.def"
Macros
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define IMAGE_WRITE_TYPE(Type, Id, Ext)
#define IMAGE_READ_WRITE_TYPE(Type, Id, Ext)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix)
#define IMAGE_WRITE_TYPE(Type, Id, Ext)
#define IMAGE_READ_WRITE_TYPE(Type, Id, Ext)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext)
Functions
static const BlockExpr * getBlockExpr (const Expr *E)
Macro Definition Documentation
EXT_OPAQUE_TYPE
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext)
Value:
  case BuiltinType::Id: \
    return llvm::PointerType::get( \
        llvm::StructType::create(Ctx, "opencl." #ExtType), AddrSpc);
IMAGE_READ_WRITE_TYPE [1/2]
#define IMAGE_READ_WRITE_TYPE (Type, Id, Ext)
IMAGE_READ_WRITE_TYPE [2/2]
#define IMAGE_READ_WRITE_TYPE (Type, Id, Ext)
IMAGE_TYPE [1/4]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Id:                                                        \
    return llvm::IntegerType::getInt64Ty(CGM.getLLVMContext());
IMAGE_TYPE [2/4]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Sampled##Id:                                               \
    return llvm::StructType::get(                                              \
        llvm::IntegerType::getInt64Ty(CGM.getLLVMContext()),                   \
        llvm::IntegerType::getInt32Ty(CGM.getLLVMContext()));
IMAGE_TYPE [3/4]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Id: \
    return llvm::PointerType::get( \
        llvm::StructType::create(Ctx, "opencl." #ImgType "_" #Suffix "_t"), \
        AddrSpc);
IMAGE_TYPE [4/4]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix)
Value:
  case BuiltinType::Sampled##Id:                                               \
    return llvm::PointerType::get(                                             \
        llvm::StructType::create(Ctx, "spirv.SampledImage." #ImgType           \
                                      "_" #Suffix "_t"),                       \
        AddrSpc);
IMAGE_WRITE_TYPE [1/2]
#define IMAGE_WRITE_TYPE (Type, Id, Ext)
IMAGE_WRITE_TYPE [2/2]
#define IMAGE_WRITE_TYPE (Type, Id, Ext)
Function Documentation
getBlockExpr()
static const BlockExpr* getBlockExpr (const Expr * E) static
Definition at line 161 of file CGOpenCLRuntime.cpp.
References clang::Expr::IgnoreCasts().
Referenced by clang::CodeGen::CGOpenCLRuntime::emitOpenCLEnqueuedBlock(), and clang::CodeGen::CGOpenCLRuntime::getInvokeFunction().