clang: lib/CodeGen/CGPointerAuth.cpp File Reference
CGPointerAuth.cpp File Reference
#include "CodeGenFunction.h"
#include "CodeGenModule.h"
#include "clang/CodeGen/CodeGenABITypes.h"
#include "clang/CodeGen/ConstantInitBuilder.h"
#include "llvm/Support/SipHash.h"
Functions
static CGPointerAuthInfo getPointerAuthInfoForPointeeType (CodeGenModule &CGM, QualType PointeeType)
Return the natural pointer authentication for values of the given pointee type.
static CGPointerAuthInfo getPointerAuthInfoForType (CodeGenModule &CGM, QualType PointerType)
Return the natural pointer authentication for values of the given pointer type.
Function Documentation
getPointerAuthInfoForPointeeType()
static CGPointerAuthInfo getPointerAuthInfoForPointeeType (CodeGenModule & CGM, QualType PointeeType) static
Return the natural pointer authentication for values of the given pointee type.
Definition at line 130 of file CGPointerAuth.cpp.
References clang::CodeGen::CodeGenModule::getFunctionPointerAuthInfo(), clang::Type::isFunctionType(), and clang::QualType::isNull().
Referenced by clang::CodeGen::CodeGenModule::getPointerAuthInfoForPointeeType(), and getPointerAuthInfoForType().
getPointerAuthInfoForType()
static CGPointerAuthInfo getPointerAuthInfoForType (CodeGenModule & CGM, QualType PointerType) static
Return the natural pointer authentication for values of the given pointer type.
Definition at line 148 of file CGPointerAuth.cpp.
References clang::PointerType::getPointeeType(), getPointerAuthInfoForPointeeType(), clang::Type::isBlockPointerType(), and clang::Type::isSignableType().
Referenced by clang::CodeGen::CodeGenModule::getPointerAuthInfoForType().