clang: lib/StaticAnalyzer/Checkers/CheckObjCDealloc.cpp File Reference
CheckObjCDealloc.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/Analysis/PathDiagnostic.h"
#include "clang/AST/Attr.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprObjC.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramStateTrait.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
#include "llvm/Support/raw_ostream.h"
Enumerations
enum ReleaseRequirement { ReleaseRequirement::MustRelease, ReleaseRequirement::MustNotReleaseDirectly, ReleaseRequirement::Unknown }
Indicates whether an instance variable is required to be released in -dealloc.
Functions
static bool isSynthesizedRetainableProperty (const ObjCPropertyImplDecl *I, const ObjCIvarDecl **ID, const ObjCPropertyDecl **PD)
Returns true if the property implementation is synthesized and the type of the property is retainable.
Enumeration Type Documentation
ReleaseRequirement
enum ReleaseRequirement strong
Indicates whether an instance variable is required to be released in -dealloc.
Enumerator
MustRelease
The instance variable must be released, either by calling -release on it directly or by nilling it out with a property setter.
MustNotReleaseDirectly
The instance variable must not be directly released with -release.
Unknown
The requirement for the instance variable could not be determined.
Definition at line 54 of file CheckObjCDealloc.cpp.
Function Documentation
isSynthesizedRetainableProperty()
static bool isSynthesizedRetainableProperty (const ObjCPropertyImplDecl * I, const ObjCIvarDecl ** ID, const ObjCPropertyDecl ** PD) static
Returns true if the property implementation is synthesized and the type of the property is retainable.
Definition at line 68 of file CheckObjCDealloc.cpp.
References clang::ObjCPropertyImplDecl::getPropertyDecl(), clang::ObjCPropertyImplDecl::getPropertyImplementation(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), clang::Type::isObjCRetainableType(), and clang::ObjCPropertyImplDecl::Synthesize.