clang: lib/StaticAnalyzer/Core/CheckerContext.cpp File Reference
CheckerContext.cpp File Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/Basic/Builtins.h"
#include "clang/Lex/Lexer.h"
#include "llvm/ADT/StringExtras.h"
Functions
static bool evalComparison (SVal LHSVal, BinaryOperatorKind ComparisonOp, SVal RHSVal, ProgramStateRef State)
Evaluate comparison and return true if it's known that condition is true.
Function Documentation
evalComparison()
static bool evalComparison (SVal LHSVal, BinaryOperatorKind ComparisonOp, SVal RHSVal, ProgramStateRef State) static
Evaluate comparison and return true if it's known that condition is true.
Definition at line 140 of file CheckerContext.cpp.
References clang::ento::SVal::castAs(), clang::ento::SValBuilder::evalBinOp(), clang::ento::StoreManager::getBinding(), clang::ento::SValBuilder::getConditionType(), clang::ento::ProgramStateManager::getStoreManager(), clang::ento::ProgramStateManager::getSValBuilder(), clang::ento::SVal::isUnknownOrUndef(), and State.
Referenced by clang::ento::CheckerContext::isGreaterOrEqual(), and clang::ento::CheckerContext::isNegative().