clang: lib/Tooling/DumpTool/ClangSrcLocDump.cpp File Reference
ClangSrcLocDump.cpp File Reference
#include "clang/Basic/Diagnostic.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/Job.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/Tool.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/TextDiagnosticPrinter.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "clang/Tooling/Tooling.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/JSON.h"
#include "ASTSrcLocProcessor.h"
Classes
class ASTSrcLocGenerationAction
Functions
static cl::list< std::string > IncludeDirectories ("I", cl::desc("Include directories to use while compiling"), cl::value_desc("directory"), cl::Required, cl::OneOrMore, cl::Prefix)
static cl::opt< bool > SkipProcessing ("skip-processing", cl::desc("Avoid processing the AST header file"), cl::Required, cl::value_desc("bool"))
static cl::opt< std::string > JsonOutputPath ("json-output-path", cl::desc("json output path"), cl::Required, cl::value_desc("path"))
int main (int argc, const char **argv)
Variables
static const char Filename [] = "ASTTU.cpp"
Function Documentation
IncludeDirectories()
static cl::list<std::string> IncludeDirectories ("I" , cl::desc("Include directories to use while compiling") , cl::value_desc("directory") , cl::Required , cl::OneOrMore , cl::Prefix) static
Referenced by main().
JsonOutputPath()
static cl::opt<std::string> JsonOutputPath ("json-output-path" , cl::desc("json output path") , cl::Required , cl::value_desc("path")) static
Referenced by main().
main()
int main (int argc, const char ** argv)
Definition at line 68 of file ClangSrcLocDump.cpp.
References Cmd, clang::CompilerInstance::createDiagnostics(), clang::CompilerInvocation::CreateFromArgs(), clang::CompilerInstance::createSourceManager(), clang::CompilerInstance::ExecuteAction(), Filename, clang::CompilerInstance::getDiagnosticOpts(), clang::driver::getDriverOptTable(), clang::CompilerInstance::hasDiagnostics(), IncludeDirectories(), JsonOutputPath(), clang::ParseDiagnosticArgs(), clang::CompilerInstance::setFileManager(), clang::CompilerInstance::setInvocation(), SkipProcessing(), and string().
SkipProcessing()
static cl::opt<bool> SkipProcessing ("skip-processing" , cl::desc("Avoid processing the AST header file") , cl::Required , cl::value_desc("bool")) static
Referenced by main().
Variable Documentation
Filename
const char Filename[] = "ASTTU.cpp" static
Definition at line 66 of file ClangSrcLocDump.cpp.
Referenced by main().