clang: lib/Driver/ToolChains/Clang.cpp File Reference
Clang.cpp File Reference
#include "Clang.h"
#include "AMDGPU.h"
#include "Arch/AArch64.h"
#include "Arch/ARM.h"
#include "Arch/M68k.h"
#include "Arch/Mips.h"
#include "Arch/PPC.h"
#include "Arch/RISCV.h"
#include "Arch/Sparc.h"
#include "Arch/SystemZ.h"
#include "Arch/VE.h"
#include "Arch/X86.h"
#include "CommonArgs.h"
#include "Hexagon.h"
#include "MSP430.h"
#include "PS4CPU.h"
#include "SYCL.h"
#include "clang/Basic/CLWarnings.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/LangStandard.h"
#include "clang/Basic/ObjCRuntime.h"
#include "clang/Basic/Version.h"
#include "clang/Driver/Action.h"
#include "clang/Driver/Distro.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "clang/Driver/Types.h"
#include "clang/Driver/XRayArgs.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/TargetParser.h"
#include "llvm/Support/YAMLParser.h"
Enumerations
enum DwarfFissionKind { DwarfFissionKind::None, DwarfFissionKind::Split, DwarfFissionKind::Single }
Functions
static void CheckPreprocessingOptions (const Driver &D, const ArgList &Args)
static void CheckCodeGenerationOptions (const Driver &D, const ArgList &Args)
static void EscapeSpacesAndBackslashes (const char *Arg, SmallVectorImpl< char > &Res)
static void QuoteTarget (StringRef Target, SmallVectorImpl< char > &Res)
static void forAllAssociatedToolChains (Compilation &C, const JobAction &JA, const ToolChain &RegularToolChain, llvm::function_ref< void(const ToolChain &)> Work)
Apply Work on the current tool chain RegularToolChain and any other offloading tool chain that is associated with the current action JA.
static bool getRefinementStep (StringRef In, const Driver &D, const Arg &A, size_t &Position)
This is a helper function for validating the optional refinement step parameter in reciprocal argument strings.
static void ParseMRecip (const Driver &D, const ArgList &Args, ArgStringList &OutStrings)
The -mrecip flag requires processing of many optional parameters.
static void ParseMPreferVectorWidth (const Driver &D, const ArgList &Args, ArgStringList &CmdArgs)
The -mprefer-vector-width option accepts either a positive integer or the string "none".
static void getWebAssemblyTargetFeatures (const ArgList &Args, std::vector< StringRef > &Features)
static void getTargetFeatures (const Driver &D, const llvm::Triple &Triple, const ArgList &Args, ArgStringList &CmdArgs, bool ForAS, bool IsAux=false)
static bool shouldUseExceptionTablesForObjCExceptions (const ObjCRuntime &runtime, const llvm::Triple &Triple)
static bool addExceptionArgs (const ArgList &Args, types::ID InputType, const ToolChain &TC, bool KernelOrKext, const ObjCRuntime &objcRuntime, ArgStringList &CmdArgs)
Adds exception related arguments to the driver command arguments.
static bool ShouldEnableAutolink (const ArgList &Args, const ToolChain &TC, const JobAction &JA)
static codegenoptions::DebugInfoKind DebugLevelToInfoKind (const Arg &A)
static bool mustUseNonLeafFramePointerForTarget (const llvm::Triple &Triple)
static bool useFramePointerForTargetByDefault (const ArgList &Args, const llvm::Triple &Triple)
static CodeGenOptions::FramePointerKind getFramePointerKind (const ArgList &Args, const llvm::Triple &Triple)
static const char * addDebugCompDirArg (const ArgList &Args, ArgStringList &CmdArgs, const llvm::vfs::FileSystem &VFS)
Add a CC1 option to specify the debug compilation directory.
static void addDebugObjectName (const ArgList &Args, ArgStringList &CmdArgs, const char *DebugCompilationDir, const char *OutputFileName)
static void addDebugPrefixMapArg (const Driver &D, const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs)
Add a CC1 and CC1AS option to specify the debug file path prefix map.
static void addMacroPrefixMapArg (const Driver &D, const ArgList &Args, ArgStringList &CmdArgs)
Add a CC1 and CC1AS option to specify the macro file path prefix map.
static void addCoveragePrefixMapArg (const Driver &D, const ArgList &Args, ArgStringList &CmdArgs)
Add a CC1 and CC1AS option to specify the coverage file path prefix map.
static bool isSYCLOptimizationO2orHigher (const ArgList &Args)
Simple check to see if the optimization level is at -O2 or higher.
static bool shouldEnableVectorizerAtOLevel (const ArgList &Args, bool isSlpVec)
Vectorize at all optimization levels greater than 1 except for -Oz.
static void addDashXForInput (const ArgList &Args, const InputInfo &Input, ArgStringList &CmdArgs)
Add -x lang to CmdArgs for Input.
static void addPGOAndCoverageFlags (const ToolChain &TC, Compilation &C, const Driver &D, const InputInfo &Output, const ArgList &Args, SanitizerArgs &SanArgs, ArgStringList &CmdArgs)
static bool ContainsCompileAction (const Action *A)
Check whether the given input tree contains any compilation actions.
static bool UseRelaxAll (Compilation &C, const ArgList &Args)
Check if -relax-all should be passed to the internal assembler.
static unsigned DwarfVersionNum (StringRef ArgValue)
static const Arg * getDwarfNArg (const ArgList &Args)
static void RenderDebugEnablingArgs (const ArgList &Args, ArgStringList &CmdArgs, codegenoptions::DebugInfoKind DebugInfoKind, unsigned DwarfVersion, llvm::DebuggerKind DebuggerTuning)
static bool checkDebugInfoOption (const Arg *A, const ArgList &Args, const Driver &D, const ToolChain &TC)
static void RenderDebugInfoCompressionArgs (const ArgList &Args, ArgStringList &CmdArgs, const Driver &D, const ToolChain &TC)
static const char * RelocationModelName (llvm::Reloc::Model Model)
static void handleAMDGPUCodeObjectVersionOptions (const Driver &D, const ArgList &Args, ArgStringList &CmdArgs, bool IsCC1As=false)
static bool ContainsAppendFooterAction (const Action *A)
Check whether the given input tree contains any append footer actions.
static bool isSignedCharDefault (const llvm::Triple &Triple)
static bool hasMultipleInvocations (const llvm::Triple &Triple, const ArgList &Args)
static bool checkRemarksOptions (const Driver &D, const ArgList &Args, const llvm::Triple &Triple)
static void renderRemarksOptions (const ArgList &Args, ArgStringList &CmdArgs, const llvm::Triple &Triple, const InputInfo &Input, const InputInfo &Output, const JobAction &JA)
void AddAAPCSVolatileBitfieldArgs (const ArgList &Args, ArgStringList &CmdArgs)
static void CollectARMPACBTIOptions (const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs, bool isAArch64)
static void SetRISCVSmallDataLimit (const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs)
static bool CheckARMImplicitITArg (StringRef Value)
static void AddARMImplicitITArgs (const ArgList &Args, ArgStringList &CmdArgs, StringRef Value)
static void CollectArgsForIntegratedAssembler (Compilation &C, const ArgList &Args, ArgStringList &CmdArgs, const Driver &D)
static void RenderFloatingPointOptions (const ToolChain &TC, const Driver &D, bool OFastEnabled, const ArgList &Args, ArgStringList &CmdArgs, const JobAction &JA)
static void RenderAnalyzerOptions (const ArgList &Args, ArgStringList &CmdArgs, const llvm::Triple &Triple, const InputInfo &Input)
static void RenderSSPOptions (const Driver &D, const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs, bool KernelOrKext)
static void RenderSCPOptions (const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs)
static void RenderTrivialAutoVarInitOptions (const Driver &D, const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs)
static void RenderOpenCLOptions (const ArgList &Args, ArgStringList &CmdArgs, types::ID InputType)
static void RenderARCMigrateToolOptions (const Driver &D, const ArgList &Args, ArgStringList &CmdArgs)
static void RenderBuiltinOptions (const ToolChain &TC, const llvm::Triple &T, const ArgList &Args, ArgStringList &CmdArgs)
static void RenderModulesOptions (Compilation &C, const Driver &D, const ArgList &Args, const InputInfo &Input, const InputInfo &Output, ArgStringList &CmdArgs, bool &HaveModules)
static void RenderCharacterOptions (const ArgList &Args, const llvm::Triple &T, ArgStringList &CmdArgs)
static void RenderObjCOptions (const ToolChain &TC, const Driver &D, const llvm::Triple &T, const ArgList &Args, ObjCRuntime &Runtime, bool InferCovariantReturns, const InputInfo &Input, ArgStringList &CmdArgs)
static void RenderDiagnosticsOptions (const Driver &D, const ArgList &Args, ArgStringList &CmdArgs)
static DwarfFissionKind getDebugFissionKind (const Driver &D, const ArgList &Args, Arg *&Arg)
static void renderDwarfFormat (const Driver &D, const llvm::Triple &T, const ArgList &Args, ArgStringList &CmdArgs, unsigned DwarfVersion)
static void renderDebugOptions (const ToolChain &TC, const Driver &D, const llvm::Triple &T, const ArgList &Args, bool EmitCodeView, bool IRInput, ArgStringList &CmdArgs, codegenoptions::DebugInfoKind &DebugInfoKind, DwarfFissionKind &DwarfFission)
static bool ContainsWrapperAction (const Action *A)
Check whether the given input tree contains any wrapper actions.
static bool maybeConsumeDash (const std::string &EH, size_t &I)
static EHFlags parseClangCLEHFlags (const Driver &D, const ArgList &Args)
/EH controls whether to run destructor cleanups when exceptions are thrown.
static void addArgs (ArgStringList &DstArgs, const llvm::opt::ArgList &Alloc, ArrayRef< StringRef > SrcArgs)
static std::string getSYCLPostLinkOptimizationLevel (const ArgList &Args)
Enumeration Type Documentation
DwarfFissionKind
enum DwarfFissionKind strong
Enumerator
None
Split
Single
Definition at line 4103 of file Clang.cpp.
Function Documentation
AddAAPCSVolatileBitfieldArgs()
void AddAAPCSVolatileBitfieldArgs (const ArgList & Args, ArgStringList & CmdArgs)
Definition at line 1730 of file Clang.cpp.
addArgs()
static void addArgs (ArgStringList & DstArgs, const llvm::opt::ArgList & Alloc, ArrayRef< StringRef > SrcArgs) static
Definition at line 9302 of file Clang.cpp.
Referenced by clang::driver::tools::SYCLPostLink::ConstructJob(), clang::driver::tools::FileTableTform::ConstructJob(), clang::driver::tools::AppendFooter::ConstructJob(), and clang::driver::tools::SpirvToIrWrapper::ConstructJob().
AddARMImplicitITArgs()
static void AddARMImplicitITArgs (const ArgList & Args, ArgStringList & CmdArgs, StringRef Value) static
Definition at line 2591 of file Clang.cpp.
addCoveragePrefixMapArg()
static void addCoveragePrefixMapArg (const Driver & D, const ArgList & Args, ArgStringList & CmdArgs) static
Add a CC1 and CC1AS option to specify the coverage file path prefix map.
Definition at line 723 of file Clang.cpp.
References clang::driver::Driver::Diag().
addDashXForInput()
static void addDashXForInput (const ArgList & Args, const InputInfo & Input, ArgStringList & CmdArgs) static
Add -x lang to CmdArgs for Input.
Definition at line 794 of file Clang.cpp.
References clang::driver::InputInfo::getType(), and clang::driver::types::getTypeName().
Referenced by clang::driver::tools::Clang::ConstructJob().
addDebugCompDirArg()
static const char* addDebugCompDirArg (const ArgList & Args, ArgStringList & CmdArgs, const llvm::vfs::FileSystem & VFS) static
Add a CC1 option to specify the debug compilation directory.
Definition at line 645 of file Clang.cpp.
Referenced by clang::driver::tools::Clang::ConstructJob().
addDebugObjectName()
static void addDebugObjectName (const ArgList & Args, ArgStringList & CmdArgs, const char * DebugCompilationDir, const char * OutputFileName) static
Definition at line 663 of file Clang.cpp.
addDebugPrefixMapArg()
static void addDebugPrefixMapArg (const Driver & D, const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs) static
Add a CC1 and CC1AS option to specify the debug file path prefix map.
Definition at line 687 of file Clang.cpp.
Referenced by clang::driver::tools::Clang::ConstructJob().
addExceptionArgs()
static bool addExceptionArgs (const ArgList & Args, types::ID InputType, const ToolChain & TC, bool KernelOrKext, const ObjCRuntime & objcRuntime, ArgStringList & CmdArgs) static
Adds exception related arguments to the driver command arguments.
There's a main flag, -fexceptions and also language specific flags to enable/disable C++ and Objective-C exceptions. This makes it possible to for example disable C++ exceptions but enable Objective-C exceptions.
Definition at line 426 of file Clang.cpp.
References clang::driver::ToolChain::getTriple(), clang::driver::types::isCXX(), clang::driver::types::isObjC(), and shouldUseExceptionTablesForObjCExceptions().
addMacroPrefixMapArg()
static void addMacroPrefixMapArg (const Driver & D, const ArgList & Args, ArgStringList & CmdArgs) static
Add a CC1 and CC1AS option to specify the macro file path prefix map.
Definition at line 708 of file Clang.cpp.
References clang::driver::Driver::Diag().
addPGOAndCoverageFlags()
static void addPGOAndCoverageFlags (const ToolChain & TC, Compilation & C, const Driver & D, const InputInfo & Output, const ArgList & Args, SanitizerArgs & SanArgs, ArgStringList & CmdArgs) static
Definition at line 824 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::driver::InputInfo::getBaseInput(), clang::driver::ToolChain::getCompilerRTBasename(), clang::driver::tools::getLastProfileSampleUseArg(), clang::driver::tools::getLastProfileUseArg(), clang::driver::ToolChain::getTriple(), clang::driver::Driver::getVFS(), clang::driver::InputInfo::isFilename(), clang::driver::ToolChain::needsGCovInstrumentation(), clang::driver::SanitizerArgs::needsTsanRt(), and v.
Referenced by clang::driver::tools::Clang::ConstructJob().
CheckARMImplicitITArg()
static bool CheckARMImplicitITArg (StringRef Value) static
Definition at line 2586 of file Clang.cpp.
Referenced by CollectArgsForIntegratedAssembler().
CheckCodeGenerationOptions()
static void CheckCodeGenerationOptions (const Driver & D, const ArgList & Args) static
Definition at line 74 of file Clang.cpp.
References clang::driver::Driver::Diag().
Referenced by clang::driver::tools::Clang::ConstructJob().
checkDebugInfoOption()
static bool checkDebugInfoOption (const Arg * A, const ArgList & Args, const Driver & D, const ToolChain & TC) static
Definition at line 1144 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getTripleString(), and clang::driver::ToolChain::supportsDebugInfoOption().
Referenced by RenderDebugInfoCompressionArgs(), and renderDebugOptions().
CheckPreprocessingOptions()
static void CheckPreprocessingOptions (const Driver & D, const ArgList & Args) static
Definition at line 61 of file Clang.cpp.
References clang::driver::Driver::CCCIsCPP(), clang::driver::Driver::Diag(), and clang::driver::Driver::IsCLMode().
checkRemarksOptions()
static bool checkRemarksOptions (const Driver & D, const ArgList & Args, const llvm::Triple & Triple) static
Definition at line 1631 of file Clang.cpp.
References clang::driver::Driver::Diag(), and hasMultipleInvocations().
CollectArgsForIntegratedAssembler()
static void CollectArgsForIntegratedAssembler (Compilation & C, const ArgList & Args, ArgStringList & CmdArgs, const Driver & D) static
Definition at line 2597 of file Clang.cpp.
References CheckARMImplicitITArg(), clang::codegenoptions::DebugInfoConstructor, clang::driver::Driver::Diag(), DwarfVersionNum(), RenderDebugEnablingArgs(), and UseRelaxAll().
Referenced by clang::driver::tools::Clang::ConstructJob().
CollectARMPACBTIOptions()
static void CollectARMPACBTIOptions (const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs, bool isAArch64) static
Definition at line 1768 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getEffectiveTriple(), and clang::Scope::Scope().
ContainsAppendFooterAction()
static bool ContainsAppendFooterAction (const Action * A) static
Check whether the given input tree contains any append footer actions.
Definition at line 1220 of file Clang.cpp.
References clang::driver::Action::inputs().
ContainsCompileAction()
static bool ContainsCompileAction (const Action * A) static
Check whether the given input tree contains any compilation actions.
Definition at line 1048 of file Clang.cpp.
References clang::driver::Action::inputs().
Referenced by UseRelaxAll().
ContainsWrapperAction()
static bool ContainsWrapperAction (const Action * A) static
Check whether the given input tree contains any wrapper actions.
Definition at line 4479 of file Clang.cpp.
References clang::driver::Action::inputs().
Referenced by clang::driver::tools::Clang::ConstructJob().
DebugLevelToInfoKind()
static codegenoptions::DebugInfoKind DebugLevelToInfoKind (const Arg & A) static
Definition at line 514 of file Clang.cpp.
References clang::codegenoptions::DebugDirectivesOnly, clang::codegenoptions::DebugInfoConstructor, clang::codegenoptions::DebugLineTablesOnly, and clang::codegenoptions::NoDebugInfo.
Referenced by renderDebugOptions().
DwarfVersionNum()
static unsigned DwarfVersionNum (StringRef ArgValue) static
Definition at line 1080 of file Clang.cpp.
Referenced by CollectArgsForIntegratedAssembler(), and renderDebugOptions().
EscapeSpacesAndBackslashes()
static void EscapeSpacesAndBackslashes (const char * Arg, SmallVectorImpl< char > & Res) static
Definition at line 86 of file Clang.cpp.
forAllAssociatedToolChains()
static void forAllAssociatedToolChains (Compilation & C, const JobAction & JA, const ToolChain & RegularToolChain, llvm::function_ref< void(const ToolChain &)> Work) static
Apply Work on the current tool chain RegularToolChain and any other offloading tool chain that is associated with the current action JA.
Definition at line 132 of file Clang.cpp.
References clang::driver::Action::isDeviceOffloading(), clang::driver::Action::isHostOffloading(), clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_HIP, clang::driver::Action::OFK_Host, clang::driver::Action::OFK_OpenMP, and clang::driver::Action::OFK_SYCL.
getDebugFissionKind()
static DwarfFissionKind getDebugFissionKind (const Driver & D, const ArgList & Args, Arg *& Arg) static
Definition at line 4105 of file Clang.cpp.
References clang::driver::Driver::Diag(), None, Single, and Split.
Referenced by renderDebugOptions().
getDwarfNArg()
static const Arg* getDwarfNArg (const ArgList & Args) static
Definition at line 1091 of file Clang.cpp.
Referenced by renderDebugOptions().
getFramePointerKind()
static CodeGenOptions::FramePointerKind getFramePointerKind (const ArgList & Args, const llvm::Triple & Triple) static
Definition at line 615 of file Clang.cpp.
References clang::CodeGenOptions::All, mustUseNonLeafFramePointerForTarget(), clang::CodeGenOptions::None, clang::CodeGenOptions::NonLeaf, and useFramePointerForTargetByDefault().
Referenced by clang::driver::tools::Clang::ConstructJob().
getRefinementStep()
static bool getRefinementStep (StringRef In, const Driver & D, const Arg & A, size_t & Position) static
This is a helper function for validating the optional refinement step parameter in reciprocal argument strings.
Return false if there is an error parsing the refinement step. Otherwise, return true and set the Position of the refinement step in the input string.
Definition at line 172 of file Clang.cpp.
Referenced by ParseMRecip().
getSYCLPostLinkOptimizationLevel()
static std::string getSYCLPostLinkOptimizationLevel (const ArgList & Args) static
Definition at line 9310 of file Clang.cpp.
Referenced by clang::driver::tools::SYCLPostLink::ConstructJob().
getTargetFeatures()
static void getTargetFeatures (const Driver & D, const llvm::Triple & Triple, const ArgList & Args, ArgStringList & CmdArgs, bool ForAS, bool IsAux = false) static
Definition at line 325 of file Clang.cpp.
References clang::driver::tools::aarch64::getAArch64TargetFeatures(), clang::driver::tools::amdgpu::getAMDGPUTargetFeatures(), clang::driver::tools::arm::getARMTargetFeatures(), clang::driver::tools::hexagon::getHexagonTargetFeatures(), clang::driver::tools::m68k::getM68kTargetFeatures(), clang::driver::tools::mips::getMIPSTargetFeatures(), clang::driver::tools::msp430::getMSP430TargetFeatures(), clang::driver::tools::NVPTX::getNVPTXTargetFeatures(), clang::driver::tools::ppc::getPPCTargetFeatures(), clang::driver::tools::riscv::getRISCVTargetFeatures(), clang::driver::tools::sparc::getSparcTargetFeatures(), clang::driver::tools::systemz::getSystemZTargetFeatures(), clang::driver::tools::ve::getVETargetFeatures(), getWebAssemblyTargetFeatures(), clang::driver::tools::x86::getX86TargetFeatures(), and clang::driver::tools::unifyTargetFeatures().
Referenced by clang::driver::tools::Clang::ConstructJob(), and clang::driver::tools::ClangAs::ConstructJob().
getWebAssemblyTargetFeatures()
static void getWebAssemblyTargetFeatures (const ArgList & Args, std::vector< StringRef > & Features) static
Definition at line 320 of file Clang.cpp.
References clang::driver::tools::handleTargetFeaturesGroup().
Referenced by getTargetFeatures().
handleAMDGPUCodeObjectVersionOptions()
static void handleAMDGPUCodeObjectVersionOptions (const Driver & D, const ArgList & Args, ArgStringList & CmdArgs, bool IsCC1As = false) static
Definition at line 1196 of file Clang.cpp.
References clang::driver::tools::getAMDGPUCodeObjectVersion(), and clang::driver::tools::haveAMDGPUCodeObjectVersionArgument().
hasMultipleInvocations()
static bool hasMultipleInvocations (const llvm::Triple & Triple, const ArgList & Args) static
Definition at line 1620 of file Clang.cpp.
Referenced by checkRemarksOptions().
isSignedCharDefault()
static bool isSignedCharDefault (const llvm::Triple & Triple) static
Definition at line 1587 of file Clang.cpp.
Referenced by RenderCharacterOptions().
isSYCLOptimizationO2orHigher()
static bool isSYCLOptimizationO2orHigher (const ArgList & Args) static
Simple check to see if the optimization level is at -O2 or higher.
For -fsycl (DPC++) -O2 is the default.
Definition at line 739 of file Clang.cpp.
Referenced by clang::driver::tools::Clang::ConstructJob(), and clang::driver::tools::SYCLPostLink::ConstructJob().
maybeConsumeDash()
static bool maybeConsumeDash (const std::string & EH, size_t & I) static
Definition at line 7930 of file Clang.cpp.
Referenced by parseClangCLEHFlags().
mustUseNonLeafFramePointerForTarget()
static bool mustUseNonLeafFramePointerForTarget (const llvm::Triple & Triple) static
Definition at line 528 of file Clang.cpp.
Referenced by getFramePointerKind().
parseClangCLEHFlags()
static EHFlags parseClangCLEHFlags (const Driver & D, const ArgList & Args) static
/EH controls whether to run destructor cleanups when exceptions are thrown.
There are three modifiers:
s: Cleanup after "synchronous" exceptions, aka C++ exceptions.
a: Cleanup after "asynchronous" exceptions, aka structured exceptions. The 'a' modifier is unimplemented and fundamentally hard in LLVM IR.
c: Assume that extern "C" functions are implicitly nounwind. The default is /EHs-c-, meaning cleanups are disabled.
Definition at line 7951 of file Clang.cpp.
References clang::driver::Driver::Diag(), and maybeConsumeDash().
ParseMPreferVectorWidth()
static void ParseMPreferVectorWidth (const Driver & D, const ArgList & Args, ArgStringList & CmdArgs) static
The -mprefer-vector-width option accepts either a positive integer or the string "none".
Definition at line 301 of file Clang.cpp.
References clang::driver::Driver::Diag().
ParseMRecip()
static void ParseMRecip (const Driver & D, const ArgList & Args, ArgStringList & OutStrings) static
The -mrecip flag requires processing of many optional parameters.
Definition at line 200 of file Clang.cpp.
References clang::driver::Driver::Diag(), and getRefinementStep().
Referenced by RenderFloatingPointOptions().
QuoteTarget()
static void QuoteTarget (StringRef Target, SmallVectorImpl< char > & Res) static
Definition at line 103 of file Clang.cpp.
References clang::Target.
RelocationModelName()
static const char* RelocationModelName (llvm::Reloc::Model Model) static
Definition at line 1179 of file Clang.cpp.
Referenced by clang::driver::tools::Clang::ConstructJob().
RenderAnalyzerOptions()
static void RenderAnalyzerOptions (const ArgList & Args, ArgStringList & CmdArgs, const llvm::Triple & Triple, const InputInfo & Input) static
Definition at line 3249 of file Clang.cpp.
References clang::driver::InputInfo::getType(), and clang::driver::types::isCXX().
Referenced by clang::driver::tools::Clang::ConstructJob().
RenderARCMigrateToolOptions()
static void RenderARCMigrateToolOptions (const Driver & D, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 3568 of file Clang.cpp.
References clang::driver::Driver::Diag().
Referenced by clang::driver::tools::Clang::ConstructJob().
RenderBuiltinOptions()
static void RenderBuiltinOptions (const ToolChain & TC, const llvm::Triple & T, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 3640 of file Clang.cpp.
References clang::driver::ToolChain::getArch().
RenderCharacterOptions()
static void RenderCharacterOptions (const ArgList & Args, const llvm::Triple & T, ArgStringList & CmdArgs) static
Definition at line 3860 of file Clang.cpp.
References isSignedCharDefault().
RenderDebugEnablingArgs()
static void RenderDebugEnablingArgs (const ArgList & Args, ArgStringList & CmdArgs, codegenoptions::DebugInfoKind DebugInfoKind, unsigned DwarfVersion, llvm::DebuggerKind DebuggerTuning) static
Definition at line 1097 of file Clang.cpp.
References clang::codegenoptions::DebugDirectivesOnly, clang::codegenoptions::DebugInfoConstructor, clang::codegenoptions::DebugLineTablesOnly, clang::codegenoptions::FullDebugInfo, clang::codegenoptions::LimitedDebugInfo, and clang::codegenoptions::UnusedTypeInfo.
Referenced by CollectArgsForIntegratedAssembler(), and renderDebugOptions().
RenderDebugInfoCompressionArgs()
static void RenderDebugInfoCompressionArgs (const ArgList & Args, ArgStringList & CmdArgs, const Driver & D, const ToolChain & TC) static
Definition at line 1154 of file Clang.cpp.
References checkDebugInfoOption(), and clang::driver::Driver::Diag().
Referenced by renderDebugOptions().
renderDebugOptions()
static void renderDebugOptions (const ToolChain & TC, const Driver & D, const llvm::Triple & T, const ArgList & Args, bool EmitCodeView, bool IRInput, ArgStringList & CmdArgs, codegenoptions::DebugInfoKind & DebugInfoKind, DwarfFissionKind & DwarfFission) static
Definition at line 4149 of file Clang.cpp.
References clang::driver::ToolChain::adjustDebugInfoKind(), checkDebugInfoOption(), clang::codegenoptions::DebugDirectivesOnly, clang::codegenoptions::DebugInfoConstructor, DebugLevelToInfoKind(), clang::codegenoptions::DebugLineTablesOnly, clang::driver::Driver::Diag(), clang::codegenoptions::DIF_CodeView, clang::codegenoptions::DIF_DWARF, DwarfVersionNum(), clang::codegenoptions::FullDebugInfo, getDebugFissionKind(), clang::driver::ToolChain::getDefaultDebugFormat(), clang::driver::ToolChain::getDefaultDebuggerTuning(), clang::driver::ToolChain::GetDefaultDwarfVersion(), clang::driver::ToolChain::GetDefaultStandaloneDebug(), getDwarfNArg(), clang::driver::ToolChain::getMaxDwarfVersion(), clang::driver::ToolChain::getTripleString(), clang::codegenoptions::LimitedDebugInfo, min(), clang::codegenoptions::NoDebugInfo, None, clang::driver::tools::ParseDebugDefaultVersion(), RenderDebugEnablingArgs(), RenderDebugInfoCompressionArgs(), renderDwarfFormat(), clang::codegenoptions::UnusedTypeInfo, clang::driver::ToolChain::useIntegratedAs(), and clang::driver::willEmitRemarks().
Referenced by clang::driver::tools::Clang::ConstructJob().
RenderDiagnosticsOptions()
static void RenderDiagnosticsOptions (const Driver & D, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 3988 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::DiagnosticsEngine::getDiagnosticOptions(), clang::driver::Driver::getDiags(), and string().
renderDwarfFormat()
static void renderDwarfFormat (const Driver & D, const llvm::Triple & T, const ArgList & Args, ArgStringList & CmdArgs, unsigned DwarfVersion) static
Definition at line 4126 of file Clang.cpp.
References clang::driver::Driver::Diag().
Referenced by renderDebugOptions().
RenderFloatingPointOptions()
static void RenderFloatingPointOptions (const ToolChain & TC, const Driver & D, bool OFastEnabled, const ArgList & Args, ArgStringList & CmdArgs, const JobAction & JA) static
Definition at line 2819 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDefaultDenormalModeForType(), clang::driver::Action::isDeviceOffloading(), clang::driver::ToolChain::IsMathErrnoDefault(), clang::driver::Action::isOffloading(), clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_HIP, and ParseMRecip().
Referenced by clang::driver::tools::Clang::ConstructJob().
RenderModulesOptions()
static void RenderModulesOptions (Compilation & C, const Driver & D, const ArgList & Args, const InputInfo & Input, const InputInfo & Output, ArgStringList & CmdArgs, bool & HaveModules) static
Definition at line 3686 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::driver::Driver::getDefaultModuleCachePath(), clang::driver::InputInfo::getFilename(), clang::driver::InputInfo::getType(), clang::driver::types::isCXX(), clang::driver::Driver::ResourceDir, and string().
RenderObjCOptions()
static void RenderObjCOptions (const ToolChain & TC, const Driver & D, const llvm::Triple & T, const ArgList & Args, ObjCRuntime & Runtime, bool InferCovariantReturns, const InputInfo & Input, ArgStringList & CmdArgs) static
Definition at line 3895 of file Clang.cpp.
References clang::ObjCRuntime::allowsWeak(), clang::driver::ToolChain::CheckObjCARC(), clang::driver::ToolChain::CST_Libcxx, clang::driver::Driver::Diag(), clang::ObjCRuntime::FragileMacOSX, clang::driver::ToolChain::getArch(), clang::driver::ToolChain::GetCXXStdlibType(), clang::ObjCRuntime::getKind(), clang::driver::InputInfo::getType(), clang::driver::types::isCXX(), clang::ObjCRuntime::isLegacyDispatchDefaultForArch(), clang::ObjCRuntime::isNeXTFamily(), clang::ObjCRuntime::isNonFragile(), clang::driver::types::isObjC(), clang::driver::tools::isObjCAutoRefCount(), and clang::driver::ToolChain::UseObjCMixedDispatch().
RenderOpenCLOptions()
static void RenderOpenCLOptions (const ArgList & Args, ArgStringList & CmdArgs, types::ID InputType) static
Definition at line 3532 of file Clang.cpp.
References clang::driver::types::isOpenCL(), clang::driver::types::isSrcFile(), and string().
renderRemarksOptions()
static void renderRemarksOptions (const ArgList & Args, ArgStringList & CmdArgs, const llvm::Triple & Triple, const InputInfo & Input, const InputInfo & Output, const JobAction & JA) static
Definition at line 1647 of file Clang.cpp.
References clang::driver::InputInfo::getBaseInput(), clang::driver::InputInfo::getFilename(), clang::driver::Action::getOffloadingArch(), clang::driver::Action::getOffloadingDeviceKind(), clang::driver::Action::GetOffloadingFileNamePrefix(), clang::driver::Action::isDeviceOffloading(), clang::driver::InputInfo::isFilename(), clang::driver::Action::OFK_Host, and clang::driver::Action::OFK_None.
RenderSCPOptions()
static void RenderSCPOptions (const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 3457 of file Clang.cpp.
References clang::driver::ToolChain::getEffectiveTriple().
RenderSSPOptions()
static void RenderSSPOptions (const Driver & D, const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs, bool KernelOrKext) static
Definition at line 3324 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::GetDefaultStackProtectorLevel(), clang::driver::ToolChain::getEffectiveTriple(), clang::driver::tools::arm::isHardTPSupported(), Offset, clang::LangOptions::SSPOff, clang::LangOptions::SSPOn, clang::LangOptions::SSPReq, clang::LangOptions::SSPStrong, and string().
RenderTrivialAutoVarInitOptions()
static void RenderTrivialAutoVarInitOptions (const Driver & D, const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 3473 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::GetDefaultTrivialAutoVarInit(), clang::LangOptions::Pattern, clang::LangOptions::Uninitialized, and clang::LangOptions::Zero.
SetRISCVSmallDataLimit()
static void SetRISCVSmallDataLimit (const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 2248 of file Clang.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), and clang::driver::ToolChain::getTriple().
ShouldEnableAutolink()
static bool ShouldEnableAutolink (const ArgList & Args, const ToolChain & TC, const JobAction & JA) static
Definition at line 496 of file Clang.cpp.
References clang::Default, clang::driver::ToolChain::getTriple(), clang::driver::Action::isDeviceOffloading(), clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_HIP, and clang::driver::ToolChain::useIntegratedAs().
Referenced by clang::driver::tools::Clang::ConstructJob().
shouldEnableVectorizerAtOLevel()
static bool shouldEnableVectorizerAtOLevel (const ArgList & Args, bool isSlpVec) static
Vectorize at all optimization levels greater than 1 except for -Oz.
For -Oz the loop vectorizer is disabled, while the slp vectorizer is enabled.
Definition at line 763 of file Clang.cpp.
shouldUseExceptionTablesForObjCExceptions()
static bool shouldUseExceptionTablesForObjCExceptions (const ObjCRuntime & runtime, const llvm::Triple & Triple) static
Definition at line 406 of file Clang.cpp.
References clang::ObjCRuntime::isNonFragile().
Referenced by addExceptionArgs().
useFramePointerForTargetByDefault()
static bool useFramePointerForTargetByDefault (const ArgList & Args, const llvm::Triple & Triple) static
Definition at line 540 of file Clang.cpp.
References clang::driver::tools::areOptimizationsEnabled().
Referenced by getFramePointerKind().
UseRelaxAll()
static bool UseRelaxAll (Compilation & C, const ArgList & Args) static
Check if -relax-all should be passed to the internal assembler.
This is done by default when compiling non-assembler source with -O0.
Definition at line 1057 of file Clang.cpp.
References ContainsCompileAction().
Referenced by CollectArgsForIntegratedAssembler().