clang: clang::ento::ScanReachableSymbols Class Reference
clang::ento::ScanReachableSymbols Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
Public Member Functions
ScanReachableSymbols (ProgramStateRef st, SymbolVisitor &v)
bool scan (nonloc::LazyCompoundVal val)
bool scan (nonloc::CompoundVal val)
bool scan (SVal val)
bool scan (const MemRegion *R)
bool scan (const SymExpr *sym)
Detailed Description
A utility class that visits the reachable symbols using a custom SymbolVisitor. Terminates recursive traversal when the visitor function returns false.
Definition at line 863 of file ProgramState.h.
Constructor & Destructor Documentation
ScanReachableSymbols()
clang::ento::ScanReachableSymbols::ScanReachableSymbols (ProgramStateRef st, SymbolVisitor & v) inline
Definition at line 870 of file ProgramState.h.
References state.
Member Function Documentation
scan() [1/5]
bool ScanReachableSymbols::scan (const MemRegion * R)
Definition at line 587 of file ProgramState.cpp.
References clang::ento::BlockDataRegion::referenced_vars_iterator::getCapturedRegion(), scan(), clang::ento::StoreManager::scanReachableSymbols(), clang::ento::SymbolVisitor::VisitMemRegion(), and clang::ento::SymbolVisitor::VisitSymbol().
scan() [2/5]
bool ScanReachableSymbols::scan (const SymExpr * sym)
Definition at line 552 of file ProgramState.cpp.
References clang::if(), clang::ento::SymExpr::symbol_begin(), clang::ento::SymExpr::symbol_end(), and clang::ento::SymbolVisitor::VisitSymbol().
scan() [3/5]
bool ScanReachableSymbols::scan (nonloc::CompoundVal val)
Definition at line 544 of file ProgramState.cpp.
References clang::ento::nonloc::CompoundVal::begin(), clang::ento::nonloc::CompoundVal::end(), and scan().
scan() [4/5]
bool ScanReachableSymbols::scan (nonloc::LazyCompoundVal val)
Definition at line 531 of file ProgramState.cpp.
References clang::ento::MemRegion::getBaseRegion(), clang::ento::nonloc::LazyCompoundVal::getCVData(), clang::ento::nonloc::LazyCompoundVal::getRegion(), clang::ento::nonloc::LazyCompoundVal::getStore(), and clang::ento::StoreManager::scanReachableSymbols().
Referenced by clang::ento::EnvironmentManager::removeDeadBindings(), and scan().
scan() [5/5]
bool ScanReachableSymbols::scan (SVal val)
Definition at line 567 of file ProgramState.cpp.
References clang::ento::SVal::getAs(), clang::ento::SVal::getAsSymbol(), scan(), and clang::tooling::X().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h
lib/StaticAnalyzer/Core/ProgramState.cpp