clang: clang::threadSafety::til::Alloc Class Reference
clang::threadSafety::til::Alloc Class Reference
Allocate memory for a new value on the heap or stack.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Types
enum AllocKind { AK_Stack , AK_Heap }
Public Member Functions
Alloc (SExpr *D, AllocKind K)
Alloc (const Alloc &A, SExpr *Dt)
AllocKind kind () const
SExpr * dataType ()
const SExpr * dataType () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Alloc *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
SExpr & operator= (const SExpr &)=delete
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Allocate memory for a new value on the heap or stack.
Definition at line 1004 of file ThreadSafetyTIL.h.
Member Enumeration Documentation
AllocKind
enum clang::threadSafety::til::Alloc::AllocKind
Enumerator
AK_Stack
AK_Heap
Definition at line 1006 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Alloc() [1/2]
clang::threadSafety::til::Alloc::Alloc (SExpr * D, AllocKind K) inline
Definition at line 1011 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Alloc() [2/2]
clang::threadSafety::til::Alloc::Alloc (const Alloc & A, SExpr * Dt) inline
Definition at line 1012 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags, and kind().
Member Function Documentation
classof()
static bool clang::threadSafety::til::Alloc::classof (const SExpr * E) inline static
Definition at line 1014 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Alloc::compare (const Alloc * E, C & Cmp) const inline
Definition at line 1028 of file ThreadSafetyTIL.h.
dataType() [1/2]
SExpr* clang::threadSafety::til::Alloc::dataType () inline
Definition at line 1018 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printAlloc().
dataType() [2/2]
const SExpr* clang::threadSafety::til::Alloc::dataType () const inline
Definition at line 1019 of file ThreadSafetyTIL.h.
kind()
AllocKind clang::threadSafety::til::Alloc::kind () const inline
Definition at line 1016 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Referenced by Alloc().
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Alloc::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1022 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h