clang: clang::InputKind Class Reference
clang::InputKind Class Reference
The kind of a file that we've been handed as an input.
#include "clang/Frontend/FrontendOptions.h"
Public Types
enum Format { Source , ModuleMap , Precompiled }
The input file format.
enum HeaderUnitKind { HeaderUnit_None , HeaderUnit_User , HeaderUnit_System , HeaderUnit_Abs }
Public Member Functions
constexpr InputKind (Language L=Language::Unknown, Format F=Source, bool PP=false, HeaderUnitKind HU=HeaderUnit_None, bool HD=false)
Language getLanguage () const
Format getFormat () const
HeaderUnitKind getHeaderUnitKind () const
bool isPreprocessed () const
bool isHeader () const
bool isHeaderUnit () const
bool isUnknown () const
Is the input kind fully-unknown?
bool isObjectiveC () const
Is the language of the input some dialect of Objective-C?
InputKind getPreprocessed () const
InputKind getHeader () const
InputKind withHeaderUnit (HeaderUnitKind HU) const
InputKind withFormat (Format F) const
Detailed Description
The kind of a file that we've been handed as an input.
Definition at line 154 of file FrontendOptions.h.
Member Enumeration Documentation
Format
enum clang::InputKind::Format
The input file format.
Enumerator
Source
ModuleMap
Precompiled
Definition at line 157 of file FrontendOptions.h.
HeaderUnitKind
enum clang::InputKind::HeaderUnitKind
Enumerator
HeaderUnit_None
HeaderUnit_User
HeaderUnit_System
HeaderUnit_Abs
Definition at line 166 of file FrontendOptions.h.
Constructor & Destructor Documentation
InputKind()
constexpr clang::InputKind::InputKind (Language L = Language::Unknown, Format F = Source, bool PP = false, HeaderUnitKind HU = HeaderUnit_None, bool HD = false) inline constexpr
Definition at line 185 of file FrontendOptions.h.
Referenced by getHeader(), getPreprocessed(), withFormat(), and withHeaderUnit().
Member Function Documentation
getFormat()
Format clang::InputKind::getFormat () const inline
Definition at line 191 of file FrontendOptions.h.
Referenced by clang::FrontendAction::BeginSourceFile(), GenerateFrontendArgs(), getHeader(), getPreprocessed(), clang::CompilerInstance::InitializeSourceManager(), ParseFrontendArgs(), and withHeaderUnit().
getHeader()
InputKind clang::InputKind::getHeader () const inline
Definition at line 212 of file FrontendOptions.h.
References getFormat(), getHeaderUnitKind(), getLanguage(), InputKind(), and isPreprocessed().
Referenced by ParseFrontendArgs().
getHeaderUnitKind()
HeaderUnitKind clang::InputKind::getHeaderUnitKind () const inline
Definition at line 192 of file FrontendOptions.h.
Referenced by GenerateFrontendArgs(), getHeader(), getPreprocessed(), ParseFrontendArgs(), and withFormat().
getLanguage()
Language clang::InputKind::getLanguage () const inline
Definition at line 190 of file FrontendOptions.h.
Referenced by clang::FrontendAction::BeginSourceFile(), GenerateFrontendArgs(), getHeader(), GetInputKindName(), getOptimizationLevel(), getPreprocessed(), needsModules(), withFormat(), and withHeaderUnit().
getPreprocessed()
InputKind clang::InputKind::getPreprocessed () const inline
Definition at line 207 of file FrontendOptions.h.
References getFormat(), getHeaderUnitKind(), getLanguage(), InputKind(), and isHeader().
Referenced by ParseFrontendArgs().
isHeader()
bool clang::InputKind::isHeader () const inline
Definition at line 196 of file FrontendOptions.h.
Referenced by getPreprocessed(), withFormat(), and withHeaderUnit().
isHeaderUnit()
bool clang::InputKind::isHeaderUnit () const inline
Definition at line 197 of file FrontendOptions.h.
References HeaderUnit_None.
isObjectiveC()
bool clang::InputKind::isObjectiveC () const inline
Is the language of the input some dialect of Objective-C?
Definition at line 203 of file FrontendOptions.h.
References clang::ObjC, and clang::ObjCXX.
isPreprocessed()
bool clang::InputKind::isPreprocessed () const inline
Definition at line 195 of file FrontendOptions.h.
Referenced by GenerateFrontendArgs(), getHeader(), withFormat(), and withHeaderUnit().
isUnknown()
bool clang::InputKind::isUnknown () const inline
Is the input kind fully-unknown?
Definition at line 200 of file FrontendOptions.h.
References Source, and clang::Unknown.
Referenced by ParseFrontendArgs().
withFormat()
InputKind clang::InputKind::withFormat (Format F) const inline
Definition at line 222 of file FrontendOptions.h.
References getHeaderUnitKind(), getLanguage(), InputKind(), isHeader(), and isPreprocessed().
Referenced by ParseFrontendArgs().
withHeaderUnit()
InputKind clang::InputKind::withHeaderUnit (HeaderUnitKind HU) const inline
Definition at line 217 of file FrontendOptions.h.
References getFormat(), getLanguage(), InputKind(), isHeader(), and isPreprocessed().
Referenced by ParseFrontendArgs().
The documentation for this class was generated from the following file:
include/clang/Frontend/FrontendOptions.h