clang: clang::threadSafety::til::Cast Class Reference
clang::threadSafety::til::Cast Class Reference
Cast expressions.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Cast (TIL_CastOpcode Op, SExpr *E)
Cast (const Cast &C, SExpr *E)
TIL_CastOpcode castOpcode () const
SExpr * expr ()
const SExpr * expr () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Cast *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
SExpr & operator= (const SExpr &)=delete
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Cast expressions.
Cast expressions are essentially unary operations, but we treat them as a distinct AST node because they only change the type of the result.
Definition at line 1264 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Cast() [1/2]
clang::threadSafety::til::Cast::Cast (TIL_CastOpcode Op, SExpr * E) inline
Definition at line 1266 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Cast() [2/2]
clang::threadSafety::til::Cast::Cast (const Cast & C, SExpr * E) inline
Definition at line 1267 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Member Function Documentation
castOpcode()
TIL_CastOpcode clang::threadSafety::til::Cast::castOpcode () const inline
Definition at line 1271 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCast().
classof()
static bool clang::threadSafety::til::Cast::classof (const SExpr * E) inline static
Definition at line 1269 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Cast::compare (const Cast * E, C & Cmp) const inline
Definition at line 1285 of file ThreadSafetyTIL.h.
expr() [1/2]
SExpr* clang::threadSafety::til::Cast::expr () inline
Definition at line 1275 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCast().
expr() [2/2]
const SExpr* clang::threadSafety::til::Cast::expr () const inline
Definition at line 1276 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Cast::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1279 of file ThreadSafetyTIL.h.
References clang::ast_matchers::Ne.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h