clang: clang::extractapi::Template Class Reference
clang::extractapi::Template Class Reference
#include "clang/ExtractAPI/API.h"
Public Member Functions
Template ()=default
Template (const TemplateDecl *Decl)
Template (const ClassTemplatePartialSpecializationDecl *Decl)
Template (const VarTemplatePartialSpecializationDecl *Decl)
const llvm::SmallVector< TemplateParameter > & getParameters () const
const llvm::SmallVector< TemplateConstraint > & getConstraints () const
void addTemplateParameter (std::string Type, std::string Name, unsigned int Index, unsigned int Depth, bool IsParameterPack)
bool empty () const
Detailed Description
Definition at line 47 of file API.h.
Constructor & Destructor Documentation
Template() [1/4]
clang::extractapi::Template::Template () default
Template() [2/4]
clang::extractapi::Template::Template (const TemplateDecl * Decl) inline
Definition at line 74 of file API.h.
References addTemplateParameter(), and clang::Parameter.
Template() [3/4]
clang::extractapi::Template::Template (const ClassTemplatePartialSpecializationDecl * Decl) inline
Definition at line 92 of file API.h.
References addTemplateParameter(), and clang::Parameter.
Template() [4/4]
clang::extractapi::Template::Template (const VarTemplatePartialSpecializationDecl * Decl) inline
Definition at line 110 of file API.h.
References addTemplateParameter(), and clang::Parameter.
Member Function Documentation
addTemplateParameter()
void clang::extractapi::Template::addTemplateParameter (std::string Type, std::string Name, unsigned int Index, unsigned int Depth, bool IsParameterPack) inline
Definition at line 136 of file API.h.
Referenced by Template().
empty()
bool clang::extractapi::Template::empty () const inline
Definition at line 142 of file API.h.
getConstraints()
const llvm::SmallVector<TemplateConstraint>& clang::extractapi::Template::getConstraints () const inline
Definition at line 132 of file API.h.
getParameters()
const llvm::SmallVector<TemplateParameter>& clang::extractapi::Template::getParameters () const inline
Definition at line 128 of file API.h.
The documentation for this class was generated from the following file:
include/clang/ExtractAPI/API.h