clang: clang::ento::NodeBuilderContext Class Reference
clang::ento::NodeBuilderContext Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h"
Public Member Functions
NodeBuilderContext (const CoreEngine &E, const CFGBlock *B, const LocationContext *L)
NodeBuilderContext (const CoreEngine &E, const CFGBlock *B, ExplodedNode *N)
const CoreEngine & getEngine () const
Return the CoreEngine associated with this builder.
const CFGBlock * getBlock () const
Return the CFGBlock associated with this builder.
const LocationContext * getLocationContext () const
Return the location context associated with this builder.
unsigned blockCount () const
Returns the number of times the current basic block has been visited on the exploded graph path.
Detailed Description
Definition at line 196 of file CoreEngine.h.
Constructor & Destructor Documentation
NodeBuilderContext() [1/2]
clang::ento::NodeBuilderContext::NodeBuilderContext (const CoreEngine & E, const CFGBlock * B, const LocationContext * L) inline
Definition at line 202 of file CoreEngine.h.
References Block.
NodeBuilderContext() [2/2]
clang::ento::NodeBuilderContext::NodeBuilderContext (const CoreEngine & E, const CFGBlock * B, ExplodedNode * N) inline
Definition at line 208 of file CoreEngine.h.
Member Function Documentation
blockCount()
unsigned clang::ento::NodeBuilderContext::blockCount () const inline
Returns the number of times the current basic block has been visited on the exploded graph path.
Definition at line 222 of file CoreEngine.h.
References Block, and clang::LocationContext::getStackFrame().
Referenced by clang::ento::ExprEngine::bindReturnValue(), clang::ento::CheckerContext::blockCount(), clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::VisitAtomicExpr(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitBlockExpr(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCXXCatchStmt(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ento::ExprEngine::VisitGuardedExpr(), and clang::ento::ExprEngine::VisitIncrementDecrementOperator().
getBlock()
const CFGBlock* clang::ento::NodeBuilderContext::getBlock () const inline
Return the CFGBlock associated with this builder.
Definition at line 215 of file CoreEngine.h.
References Block.
Referenced by clang::ento::BranchNodeBuilder::generateNode(), clang::ento::CheckerContext::getBlockID(), clang::ento::ExprEngine::getCFGElementRef(), clang::ento::ExprEngine::getCurrentCFGElement(), clang::ento::ExprEngine::processBranch(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::ProcessImplicitDtor(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::ProcessNewAllocator(), and clang::ento::ExprEngine::ProcessStmt().
getEngine()
const CoreEngine& clang::ento::NodeBuilderContext::getEngine () const inline
Return the CoreEngine associated with this builder.
Definition at line 212 of file CoreEngine.h.
Referenced by clang::ento::NodeBuilder::generateNodeImpl().
getLocationContext()
const LocationContext* clang::ento::NodeBuilderContext::getLocationContext () const inline
Return the location context associated with this builder.
Definition at line 218 of file CoreEngine.h.
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h