clang: clang::analyze_printf::PrintfSpecifier Class Reference
clang::analyze_printf::PrintfSpecifier Class Reference
#include "clang/AST/FormatString.h"
Public Member Functions
PrintfSpecifier ()
void setConversionSpecifier (const PrintfConversionSpecifier &cs)
void setHasThousandsGrouping (const char *position)
void setIsLeftJustified (const char *position)
void setHasPlusPrefix (const char *position)
void setHasSpacePrefix (const char *position)
void setHasAlternativeForm (const char *position)
void setHasLeadingZeros (const char *position)
void setHasObjCTechnicalTerm (const char *position)
void setIsPrivate (const char *position)
void setIsPublic (const char *position)
void setIsSensitive (const char *position)
void setUsesPositionalArg ()
const PrintfConversionSpecifier & getConversionSpecifier () const
void setPrecision (const OptionalAmount &Amt)
const OptionalAmount & getPrecision () const
bool consumesDataArgument () const
ArgType getArgType (ASTContext &Ctx, bool IsObjCLiteral) const
Returns the builtin type that a data argument paired with this format specifier should have.
const OptionalFlag & hasThousandsGrouping () const
const OptionalFlag & isLeftJustified () const
const OptionalFlag & hasPlusPrefix () const
const OptionalFlag & hasAlternativeForm () const
const OptionalFlag & hasLeadingZeros () const
const OptionalFlag & hasSpacePrefix () const
const OptionalFlag & hasObjCTechnicalTerm () const
const OptionalFlag & isPrivate () const
const OptionalFlag & isPublic () const
const OptionalFlag & isSensitive () const
bool usesPositionalArg () const
StringRef getMaskType () const
void setMaskType (StringRef S)
bool fixType (QualType QT, const LangOptions &LangOpt, ASTContext &Ctx, bool IsObjCLiteral)
Changes the specifier and length according to a QualType, retaining any flags or options.
void toString (raw_ostream &os) const
bool hasValidPlusPrefix () const
bool hasValidAlternativeForm () const
bool hasValidLeadingZeros () const
bool hasValidSpacePrefix () const
bool hasValidLeftJustified () const
bool hasValidThousandsGroupingPrefix () const
bool hasValidPrecision () const
bool hasValidFieldWidth () const
Public Member Functions inherited from clang::analyze_format_string::FormatSpecifier
FormatSpecifier (bool isPrintf)
void setLengthModifier (LengthModifier lm)
void setUsesPositionalArg ()
void setArgIndex (unsigned i)
unsigned getArgIndex () const
unsigned getPositionalArgIndex () const
const LengthModifier & getLengthModifier () const
const OptionalAmount & getFieldWidth () const
void setVectorNumElts (const OptionalAmount &Amt)
const OptionalAmount & getVectorNumElts () const
void setFieldWidth (const OptionalAmount &Amt)
bool usesPositionalArg () const
bool hasValidLengthModifier (const TargetInfo &Target, const LangOptions &LO) const
bool hasStandardLengthModifier () const
std::optional< LengthModifier > getCorrectedLengthModifier () const
bool hasStandardConversionSpecifier (const LangOptions &LangOpt) const
bool hasStandardLengthConversionCombination () const
Static Public Member Functions
static PrintfSpecifier Parse (const char *beg, const char *end)
Static Public Member Functions inherited from clang::analyze_format_string::FormatSpecifier
static bool namedTypeToLengthModifier (QualType QT, LengthModifier &LM)
For a TypedefType QT, if it is a named integer type such as size_t, assign the appropriate value to LM and return true.
Additional Inherited Members
Protected Attributes inherited from clang::analyze_format_string::FormatSpecifier
LengthModifier LM
OptionalAmount FieldWidth
ConversionSpecifier CS
OptionalAmount VectorNumElts
bool UsesPositionalArg
Positional arguments, an IEEE extension: IEEE Std 1003.1, 2004 Edition http://www.opengroup.org/onlinepubs/009695399/functions/printf.html.
unsigned argIndex
Detailed Description
Definition at line 524 of file FormatString.h.
Constructor & Destructor Documentation
PrintfSpecifier()
clang::analyze_printf::PrintfSpecifier::PrintfSpecifier () inline
Definition at line 541 of file FormatString.h.
Member Function Documentation
consumesDataArgument()
bool clang::analyze_printf::PrintfSpecifier::consumesDataArgument () const inline
Definition at line 597 of file FormatString.h.
References clang::analyze_format_string::ConversionSpecifier::consumesDataArgument(), and getConversionSpecifier().
fixType()
bool PrintfSpecifier::fixType (QualType QT, const LangOptions & LangOpt, ASTContext & Ctx, bool IsObjCLiteral)
Changes the specifier and length according to a QualType, retaining any flags or options.
Returns true on success, or false when a conversion was not successful.
Definition at line 747 of file PrintfFormatString.cpp.
References clang::analyze_format_string::LengthModifier::AsChar, clang::analyze_format_string::LengthModifier::AsLong, clang::analyze_format_string::LengthModifier::AsLongDouble, clang::analyze_format_string::LengthModifier::AsLongLong, clang::analyze_format_string::LengthModifier::AsShort, clang::analyze_format_string::LengthModifier::AsShortLong, clang::analyze_format_string::LengthModifier::AsWideChar, clang::analyze_format_string::ConversionSpecifier::cArg, clang::analyze_format_string::ConversionSpecifier::dArg, clang::analyze_format_string::ConversionSpecifier::DArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::RISCV::Float, clang::Type::getAs(), clang::VectorType::getElementType(), clang::BuiltinType::getKind(), clang::VectorType::getNumElements(), clang::Type::getPointeeType(), clang::ASTContext::getTargetInfo(), clang::analyze_format_string::ConversionSpecifier::iArg, clang::Type::isAnyCharacterType(), clang::Type::isCharType(), clang::Type::isObjCRetainableType(), clang::Type::isPointerType(), clang::Type::isRealFloatingType(), clang::Type::isSignedIntegerType(), clang::Type::isUnsignedIntegerType(), clang::analyze_format_string::ArgType::isValid(), clang::Type::isWideCharType(), clang::analyze_format_string::ArgType::matchesType(), clang::analyze_format_string::ConversionSpecifier::nArg, clang::analyze_format_string::LengthModifier::None, clang::analyze_format_string::OptionalAmount::NotSpecified, clang::analyze_format_string::ConversionSpecifier::ObjCObjArg, clang::analyze_format_string::ConversionSpecifier::sArg, clang::analyze_format_string::ConversionSpecifier::uArg, and clang::analyze_format_string::ConversionSpecifier::UArg.
getArgType()
ArgType PrintfSpecifier::getArgType (ASTContext & Ctx, bool IsObjCLiteral) const
Returns the builtin type that a data argument paired with this format specifier should have.
This method will return null if the format specifier does not have a matching data argument or the matching argument matches more than one type.
Definition at line 733 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::consumesDataArgument(), clang::analyze_format_string::ArgType::Invalid(), clang::analyze_format_string::ArgType::isValid(), and clang::analyze_format_string::ArgType::makeVectorType().
getConversionSpecifier()
const PrintfConversionSpecifier& clang::analyze_printf::PrintfSpecifier::getConversionSpecifier () const inline
Definition at line 584 of file FormatString.h.
References clang::analyze_format_string::FormatSpecifier::CS.
Referenced by consumesDataArgument().
getMaskType()
StringRef clang::analyze_printf::PrintfSpecifier::getMaskType () const inline
Definition at line 622 of file FormatString.h.
getPrecision()
const OptionalAmount& clang::analyze_printf::PrintfSpecifier::getPrecision () const inline
Definition at line 593 of file FormatString.h.
hasAlternativeForm()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::hasAlternativeForm () const inline
Definition at line 613 of file FormatString.h.
hasLeadingZeros()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::hasLeadingZeros () const inline
Definition at line 614 of file FormatString.h.
hasObjCTechnicalTerm()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::hasObjCTechnicalTerm () const inline
Definition at line 616 of file FormatString.h.
hasPlusPrefix()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::hasPlusPrefix () const inline
Definition at line 612 of file FormatString.h.
hasSpacePrefix()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::hasSpacePrefix () const inline
Definition at line 615 of file FormatString.h.
hasThousandsGrouping()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::hasThousandsGrouping () const inline
Definition at line 608 of file FormatString.h.
hasValidAlternativeForm()
bool PrintfSpecifier::hasValidAlternativeForm () const
Definition at line 1035 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::aArg, clang::analyze_format_string::ConversionSpecifier::AArg, clang::analyze_format_string::ConversionSpecifier::bArg, clang::analyze_format_string::ConversionSpecifier::BArg, clang::analyze_format_string::ConversionSpecifier::eArg, clang::analyze_format_string::ConversionSpecifier::EArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::analyze_format_string::ConversionSpecifier::FArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDrArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDyArg, clang::analyze_format_string::ConversionSpecifier::gArg, clang::analyze_format_string::ConversionSpecifier::GArg, clang::analyze_format_string::ConversionSpecifier::kArg, clang::analyze_format_string::ConversionSpecifier::KArg, clang::analyze_format_string::ConversionSpecifier::oArg, clang::analyze_format_string::ConversionSpecifier::OArg, clang::analyze_format_string::ConversionSpecifier::rArg, clang::analyze_format_string::ConversionSpecifier::RArg, clang::analyze_format_string::ConversionSpecifier::xArg, and clang::analyze_format_string::ConversionSpecifier::XArg.
hasValidFieldWidth()
bool PrintfSpecifier::hasValidFieldWidth () const
Definition at line 1207 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::nArg, and clang::analyze_format_string::OptionalAmount::NotSpecified.
hasValidLeadingZeros()
bool PrintfSpecifier::hasValidLeadingZeros () const
Definition at line 1068 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::aArg, clang::analyze_format_string::ConversionSpecifier::AArg, clang::analyze_format_string::ConversionSpecifier::bArg, clang::analyze_format_string::ConversionSpecifier::BArg, clang::analyze_format_string::ConversionSpecifier::dArg, clang::analyze_format_string::ConversionSpecifier::DArg, clang::analyze_format_string::ConversionSpecifier::eArg, clang::analyze_format_string::ConversionSpecifier::EArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::analyze_format_string::ConversionSpecifier::FArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDrArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDyArg, clang::analyze_format_string::ConversionSpecifier::gArg, clang::analyze_format_string::ConversionSpecifier::GArg, clang::analyze_format_string::ConversionSpecifier::iArg, clang::analyze_format_string::ConversionSpecifier::kArg, clang::analyze_format_string::ConversionSpecifier::KArg, clang::analyze_format_string::ConversionSpecifier::oArg, clang::analyze_format_string::ConversionSpecifier::OArg, clang::analyze_format_string::ConversionSpecifier::rArg, clang::analyze_format_string::ConversionSpecifier::RArg, clang::analyze_format_string::ConversionSpecifier::uArg, clang::analyze_format_string::ConversionSpecifier::UArg, clang::analyze_format_string::ConversionSpecifier::xArg, and clang::analyze_format_string::ConversionSpecifier::XArg.
hasValidLeftJustified()
bool PrintfSpecifier::hasValidLeftJustified () const
Definition at line 1134 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::nArg.
hasValidPlusPrefix()
bool PrintfSpecifier::hasValidPlusPrefix () const
Definition at line 1007 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::aArg, clang::analyze_format_string::ConversionSpecifier::AArg, clang::analyze_format_string::ConversionSpecifier::dArg, clang::analyze_format_string::ConversionSpecifier::DArg, clang::analyze_format_string::ConversionSpecifier::eArg, clang::analyze_format_string::ConversionSpecifier::EArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::analyze_format_string::ConversionSpecifier::FArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDrArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDyArg, clang::analyze_format_string::ConversionSpecifier::gArg, clang::analyze_format_string::ConversionSpecifier::GArg, clang::analyze_format_string::ConversionSpecifier::iArg, clang::analyze_format_string::ConversionSpecifier::kArg, and clang::analyze_format_string::ConversionSpecifier::rArg.
hasValidPrecision()
bool PrintfSpecifier::hasValidPrecision () const
Definition at line 1168 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::aArg, clang::analyze_format_string::ConversionSpecifier::AArg, clang::analyze_format_string::ConversionSpecifier::bArg, clang::analyze_format_string::ConversionSpecifier::BArg, clang::analyze_format_string::ConversionSpecifier::dArg, clang::analyze_format_string::ConversionSpecifier::DArg, clang::analyze_format_string::ConversionSpecifier::eArg, clang::analyze_format_string::ConversionSpecifier::EArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::analyze_format_string::ConversionSpecifier::FArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDrArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDyArg, clang::analyze_format_string::ConversionSpecifier::gArg, clang::analyze_format_string::ConversionSpecifier::GArg, clang::analyze_format_string::ConversionSpecifier::iArg, clang::analyze_format_string::ConversionSpecifier::kArg, clang::analyze_format_string::ConversionSpecifier::KArg, clang::analyze_format_string::OptionalAmount::NotSpecified, clang::analyze_format_string::ConversionSpecifier::oArg, clang::analyze_format_string::ConversionSpecifier::OArg, clang::analyze_format_string::ConversionSpecifier::PArg, clang::analyze_format_string::ConversionSpecifier::rArg, clang::analyze_format_string::ConversionSpecifier::RArg, clang::analyze_format_string::ConversionSpecifier::sArg, clang::analyze_format_string::ConversionSpecifier::uArg, clang::analyze_format_string::ConversionSpecifier::UArg, clang::analyze_format_string::ConversionSpecifier::xArg, and clang::analyze_format_string::ConversionSpecifier::XArg.
hasValidSpacePrefix()
bool PrintfSpecifier::hasValidSpacePrefix () const
Definition at line 1106 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::aArg, clang::analyze_format_string::ConversionSpecifier::AArg, clang::analyze_format_string::ConversionSpecifier::dArg, clang::analyze_format_string::ConversionSpecifier::DArg, clang::analyze_format_string::ConversionSpecifier::eArg, clang::analyze_format_string::ConversionSpecifier::EArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::analyze_format_string::ConversionSpecifier::FArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDrArg, clang::analyze_format_string::ConversionSpecifier::FreeBSDyArg, clang::analyze_format_string::ConversionSpecifier::gArg, clang::analyze_format_string::ConversionSpecifier::GArg, clang::analyze_format_string::ConversionSpecifier::iArg, clang::analyze_format_string::ConversionSpecifier::kArg, and clang::analyze_format_string::ConversionSpecifier::rArg.
hasValidThousandsGroupingPrefix()
bool PrintfSpecifier::hasValidThousandsGroupingPrefix () const
Definition at line 1148 of file PrintfFormatString.cpp.
References clang::analyze_format_string::ConversionSpecifier::dArg, clang::analyze_format_string::ConversionSpecifier::DArg, clang::analyze_format_string::ConversionSpecifier::fArg, clang::analyze_format_string::ConversionSpecifier::FArg, clang::analyze_format_string::ConversionSpecifier::gArg, clang::analyze_format_string::ConversionSpecifier::GArg, clang::analyze_format_string::ConversionSpecifier::iArg, clang::analyze_format_string::ConversionSpecifier::uArg, and clang::analyze_format_string::ConversionSpecifier::UArg.
isLeftJustified()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::isLeftJustified () const inline
Definition at line 611 of file FormatString.h.
isPrivate()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::isPrivate () const inline
Definition at line 617 of file FormatString.h.
isPublic()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::isPublic () const inline
Definition at line 618 of file FormatString.h.
isSensitive()
const OptionalFlag& clang::analyze_printf::PrintfSpecifier::isSensitive () const inline
Definition at line 619 of file FormatString.h.
Parse()
static PrintfSpecifier clang::analyze_printf::PrintfSpecifier::Parse (const char * beg, const char * end) static
setConversionSpecifier()
void clang::analyze_printf::PrintfSpecifier::setConversionSpecifier (const PrintfConversionSpecifier & cs) inline
Definition at line 551 of file FormatString.h.
References clang::analyze_format_string::FormatSpecifier::CS.
setHasAlternativeForm()
void clang::analyze_printf::PrintfSpecifier::setHasAlternativeForm (const char * position) inline
Definition at line 566 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setHasLeadingZeros()
void clang::analyze_printf::PrintfSpecifier::setHasLeadingZeros (const char * position) inline
Definition at line 569 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setHasObjCTechnicalTerm()
void clang::analyze_printf::PrintfSpecifier::setHasObjCTechnicalTerm (const char * position) inline
Definition at line 572 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setHasPlusPrefix()
void clang::analyze_printf::PrintfSpecifier::setHasPlusPrefix (const char * position) inline
Definition at line 560 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setHasSpacePrefix()
void clang::analyze_printf::PrintfSpecifier::setHasSpacePrefix (const char * position) inline
Definition at line 563 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setHasThousandsGrouping()
void clang::analyze_printf::PrintfSpecifier::setHasThousandsGrouping (const char * position) inline
Definition at line 554 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setIsLeftJustified()
void clang::analyze_printf::PrintfSpecifier::setIsLeftJustified (const char * position) inline
Definition at line 557 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setIsPrivate()
void clang::analyze_printf::PrintfSpecifier::setIsPrivate (const char * position) inline
Definition at line 575 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setIsPublic()
void clang::analyze_printf::PrintfSpecifier::setIsPublic (const char * position) inline
Definition at line 576 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setIsSensitive()
void clang::analyze_printf::PrintfSpecifier::setIsSensitive (const char * position) inline
Definition at line 577 of file FormatString.h.
References clang::analyze_format_string::OptionalFlag::setPosition().
setMaskType()
void clang::analyze_printf::PrintfSpecifier::setMaskType (StringRef S) inline
Definition at line 623 of file FormatString.h.
setPrecision()
void clang::analyze_printf::PrintfSpecifier::setPrecision (const OptionalAmount & Amt) inline
Definition at line 588 of file FormatString.h.
References clang::analyze_format_string::OptionalAmount::setUsesDotPrefix().
setUsesPositionalArg()
void clang::analyze_printf::PrintfSpecifier::setUsesPositionalArg () inline
Definition at line 580 of file FormatString.h.
References clang::analyze_format_string::FormatSpecifier::UsesPositionalArg.
toString()
void PrintfSpecifier::toString (raw_ostream & os) const
Definition at line 975 of file PrintfFormatString.cpp.
usesPositionalArg()
bool clang::analyze_printf::PrintfSpecifier::usesPositionalArg () const inline
Definition at line 620 of file FormatString.h.
References clang::analyze_format_string::FormatSpecifier::UsesPositionalArg.
The documentation for this class was generated from the following files:
include/clang/AST/FormatString.h
lib/AST/PrintfFormatString.cpp