clang: clang::FixItRewriter Class Reference
clang::FixItRewriter Class Reference
#include "clang/Rewrite/Frontend/FixItRewriter.h"
Public Types
using iterator = Rewriter::buffer_iterator
Public Member Functions
FixItRewriter (DiagnosticsEngine &Diags, SourceManager &SourceMgr, const LangOptions &LangOpts, FixItOptions *FixItOpts)
Initialize a new fix-it rewriter.
~FixItRewriter () override
Destroy the fix-it rewriter.
bool IsModified (FileID ID) const
Check whether there are modifications for a given file.
iterator buffer_begin ()
iterator buffer_end ()
bool WriteFixedFile (FileID ID, raw_ostream &OS)
Write a single modified source file.
bool WriteFixedFiles (std::vector< std::pair< std::string, std::string >> *RewrittenFiles=nullptr)
Write the modified source files.
bool IncludeInDiagnosticCounts () const override
IncludeInDiagnosticCounts - This method (whose default implementation returns true) indicates whether the diagnostics handled by this DiagnosticConsumer should be included in the number of diagnostics reported by DiagnosticsEngine.
void HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const Diagnostic &Info) override
HandleDiagnostic - Handle this diagnostic, reporting it to the user or capturing it to a log as needed.
void Diag (SourceLocation Loc, unsigned DiagID)
Emit a diagnostic via the adapted diagnostic client.
Public Member Functions inherited from clang::DiagnosticConsumer
DiagnosticConsumer ()=default
virtual ~DiagnosticConsumer ()
unsigned getNumErrors () const
unsigned getNumWarnings () const
virtual void clear ()
virtual void BeginSourceFile (const LangOptions &LangOpts, const Preprocessor *PP=nullptr)
Callback to inform the diagnostic client that processing of a source file is beginning.
virtual void EndSourceFile ()
Callback to inform the diagnostic client that processing of a source file has ended.
virtual void finish ()
Callback to inform the diagnostic client that processing of all source files has ended.
Additional Inherited Members
Protected Attributes inherited from clang::DiagnosticConsumer
unsigned NumWarnings = 0
Number of warnings reported.
unsigned NumErrors = 0
Number of errors reported.
Detailed Description
Definition at line 62 of file FixItRewriter.h.
Member Typedef Documentation
iterator
using clang::FixItRewriter::iterator = Rewriter::buffer_iterator
Definition at line 100 of file FixItRewriter.h.
Constructor & Destructor Documentation
FixItRewriter()
FixItRewriter::FixItRewriter (DiagnosticsEngine & Diags, SourceManager & SourceMgr, const LangOptions & LangOpts, FixItOptions * FixItOpts)
Initialize a new fix-it rewriter.
Definition at line 37 of file FixItRewriter.cpp.
References clang::DiagnosticsEngine::getClient(), clang::Rewrite, clang::DiagnosticsEngine::setClient(), and clang::DiagnosticsEngine::takeClient().
~FixItRewriter()
FixItRewriter::~FixItRewriter () override
Destroy the fix-it rewriter.
Definition at line 47 of file FixItRewriter.cpp.
References clang::DiagnosticsEngine::setClient().
Member Function Documentation
buffer_begin()
iterator clang::FixItRewriter::buffer_begin () inline
Definition at line 103 of file FixItRewriter.h.
References clang::Rewrite.
Referenced by WriteFixedFiles().
buffer_end()
iterator clang::FixItRewriter::buffer_end () inline
Definition at line 104 of file FixItRewriter.h.
References clang::Rewrite.
Referenced by WriteFixedFiles().
Diag()
void FixItRewriter::Diag (SourceLocation Loc, unsigned DiagID)
Emit a diagnostic via the adapted diagnostic client.
Definition at line 199 of file FixItRewriter.cpp.
References clang::DiagnosticsEngine::Clear(), clang::DiagnosticsEngine::Report(), and clang::DiagnosticsEngine::setClient().
Referenced by HandleDiagnostic(), and WriteFixedFiles().
HandleDiagnostic()
void FixItRewriter::HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const Diagnostic & Info) override virtual
HandleDiagnostic - Handle this diagnostic, reporting it to the user or capturing it to a log as needed.
Reimplemented from clang::DiagnosticConsumer.
Definition at line 128 of file FixItRewriter.cpp.
References clang::FixItHint::BeforePreviousInsertions, clang::FixItHint::CodeToInsert, clang::edit::EditedSource::commit(), Diag(), clang::DiagnosticsEngine::Error, clang::FixItOptions::FixOnlyWarnings, clang::CharSourceRange::getBegin(), clang::CharSourceRange::getEnd(), clang::Diagnostic::getFixItHint(), clang::Diagnostic::getLocation(), clang::Diagnostic::getNumFixItHints(), clang::DiagnosticConsumer::HandleDiagnostic(), clang::edit::Commit::insert(), clang::FixItHint::InsertFromRange, clang::edit::Commit::insertFromRange(), clang::edit::Commit::isCommitable(), clang::CharSourceRange::isTokenRange(), clang::CharSourceRange::isValid(), clang::Last, clang::DiagnosticsEngine::Note, clang::edit::Commit::remove(), clang::FixItHint::RemoveRange, clang::edit::Commit::replace(), and clang::FixItOptions::Silent.
IncludeInDiagnosticCounts()
bool FixItRewriter::IncludeInDiagnosticCounts () const override virtual
IncludeInDiagnosticCounts - This method (whose default implementation returns true) indicates whether the diagnostics handled by this DiagnosticConsumer should be included in the number of diagnostics reported by DiagnosticsEngine.
Reimplemented from clang::DiagnosticConsumer.
Definition at line 124 of file FixItRewriter.cpp.
References clang::DiagnosticConsumer::IncludeInDiagnosticCounts().
IsModified()
bool clang::FixItRewriter::IsModified (FileID ID) const inline
Check whether there are modifications for a given file.
Definition at line 96 of file FixItRewriter.h.
References clang::Rewrite.
WriteFixedFile()
bool FixItRewriter::WriteFixedFile (FileID ID, raw_ostream & OS)
Write a single modified source file.
Returns
true if there was an error, false otherwise.
Definition at line 51 of file FixItRewriter.cpp.
References clang::Rewriter::getRewriteBufferFor(), and clang::RewriteBuffer::write().
WriteFixedFiles()
bool FixItRewriter::WriteFixedFiles (std::vector< std::pair< std::string, std::string >> * RewrittenFiles = nullptr)
Write the modified source files.
Returns
true if there was an error, false otherwise.
Definition at line 78 of file FixItRewriter.cpp.
References clang::edit::EditedSource::applyRewrites(), buffer_begin(), buffer_end(), Diag(), Filename, clang::FixItOptions::FixWhatYouCan, clang::FileEntry::getName(), clang::FixItOptions::InPlace, clang::DiagnosticsEngine::Report(), clang::Rewrite, clang::FixItOptions::RewriteFilename(), string(), and clang::RewriteBuffer::write().
The documentation for this class was generated from the following files:
include/clang/Rewrite/Frontend/FixItRewriter.h
lib/Frontend/Rewrite/FixItRewriter.cpp