clang: clang::BalancedDelimiterTracker Class Reference
clang::BalancedDelimiterTracker Class Reference
RAII class that helps handle the parsing of an open/close delimiter pair, such as braces { ...
#include "clang/Parse/RAIIObjectsForParser.h"
Public Member Functions
BalancedDelimiterTracker (Parser &p, tok::TokenKind k, tok::TokenKind FinalToken=tok::semi)
SourceLocation getOpenLocation () const
SourceLocation getCloseLocation () const
SourceRange getRange () const
bool consumeOpen ()
bool expectAndConsume (unsigned DiagID=diag::err_expected, const char *Msg="", tok::TokenKind SkipToTok=tok::unknown)
bool consumeClose ()
void skipToEnd ()
Public Member Functions inherited from clang::GreaterThanIsOperatorScope
GreaterThanIsOperatorScope (bool &GTIO, bool Val)
~GreaterThanIsOperatorScope ()
Detailed Description
RAII class that helps handle the parsing of an open/close delimiter pair, such as braces { ...
} or parentheses (...).
Definition at line 385 of file RAIIObjectsForParser.h.
Constructor & Destructor Documentation
BalancedDelimiterTracker()
clang::BalancedDelimiterTracker::BalancedDelimiterTracker (Parser & p, tok::TokenKind k, tok::TokenKind FinalToken = tok::semi) inline
Definition at line 404 of file RAIIObjectsForParser.h.
References P.
Member Function Documentation
consumeClose()
bool clang::BalancedDelimiterTracker::consumeClose () inline
Definition at line 446 of file RAIIObjectsForParser.h.
References clang::FixItHint::CreateRemoval(), and P.
Referenced by clang::Parser::parseMapperModifier(), clang::Parser::ParseOpenMPParensExpr(), parseOpenMPSimpleClause(), clang::Parser::ParseOpenMPVarList(), and skipToEnd().
consumeOpen()
bool clang::BalancedDelimiterTracker::consumeOpen () inline
Definition at line 431 of file RAIIObjectsForParser.h.
References P.
Referenced by clang::Parser::ParseOpenMPVarList().
expectAndConsume()
bool BalancedDelimiterTracker::expectAndConsume (unsigned DiagID = diag::err_expected, const char * Msg = "", tok::TokenKind SkipToTok = tok::unknown)
Definition at line 2608 of file Parser.cpp.
References clang::Parser::getLangOpts(), clang::Token::getLocation(), clang::Parser::SkipUntil(), and clang::Parser::StopAtSemi.
Referenced by clang::Parser::parseMapperModifier(), clang::Parser::ParseOpenMPParensExpr(), parseOpenMPSimpleClause(), and clang::Parser::ParseOpenMPVarList().
getCloseLocation()
SourceLocation clang::BalancedDelimiterTracker::getCloseLocation () const inline
Definition at line 428 of file RAIIObjectsForParser.h.
Referenced by clang::Parser::ParseOpenMPParensExpr(), parseOpenMPSimpleClause(), and clang::Parser::ParseOpenMPVarList().
getOpenLocation()
SourceLocation clang::BalancedDelimiterTracker::getOpenLocation () const inline
Definition at line 427 of file RAIIObjectsForParser.h.
Referenced by clang::Parser::ParseOpenMPVarList().
getRange()
SourceRange clang::BalancedDelimiterTracker::getRange () const inline
Definition at line 429 of file RAIIObjectsForParser.h.
skipToEnd()
void BalancedDelimiterTracker::skipToEnd ()
Definition at line 2644 of file Parser.cpp.
References consumeClose(), clang::Parser::SkipUntil(), and clang::Parser::StopBeforeMatch.
The documentation for this class was generated from the following files:
include/clang/Parse/RAIIObjectsForParser.h
lib/Parse/Parser.cpp