clang: clang::JSONNodeDumper Class Reference
clang::JSONNodeDumper Class Reference
#include "clang/AST/JSONNodeDumper.h"
Public Member Functions
JSONNodeDumper (raw_ostream &OS, const SourceManager &SrcMgr, ASTContext &Ctx, const PrintingPolicy &PrintPolicy, const comments::CommandTraits *Traits)
void Visit (const Attr *A)
void Visit (const Stmt *Node)
void Visit (const Type *T)
void Visit (QualType T)
void Visit (const Decl *D)
void Visit (TypeLoc TL)
void Visit (const comments::Comment *C, const comments::FullComment *FC)
void Visit (const TemplateArgument &TA, SourceRange R={}, const Decl *From=nullptr, StringRef Label={})
void Visit (const CXXCtorInitializer *Init)
void Visit (const OpenACCClause *C)
void Visit (const OMPClause *C)
void Visit (const BlockDecl::Capture &C)
void Visit (const GenericSelectionExpr::ConstAssociation &A)
void Visit (const concepts::Requirement *R)
void Visit (const APValue &Value, QualType Ty)
void Visit (const ConceptReference *)
void VisitAliasAttr (const AliasAttr *AA)
void VisitCleanupAttr (const CleanupAttr *CA)
void VisitDeprecatedAttr (const DeprecatedAttr *DA)
void VisitUnavailableAttr (const UnavailableAttr *UA)
void VisitSectionAttr (const SectionAttr *SA)
void VisitVisibilityAttr (const VisibilityAttr *VA)
void VisitTLSModelAttr (const TLSModelAttr *TA)
void VisitTypedefType (const TypedefType *TT)
void VisitUsingType (const UsingType *TT)
void VisitFunctionType (const FunctionType *T)
void VisitFunctionProtoType (const FunctionProtoType *T)
void VisitRValueReferenceType (const ReferenceType *RT)
void VisitArrayType (const ArrayType *AT)
void VisitConstantArrayType (const ConstantArrayType *CAT)
void VisitDependentSizedExtVectorType (const DependentSizedExtVectorType *VT)
void VisitVectorType (const VectorType *VT)
void VisitUnresolvedUsingType (const UnresolvedUsingType *UUT)
void VisitUnaryTransformType (const UnaryTransformType *UTT)
void VisitTagType (const TagType *TT)
void VisitTemplateTypeParmType (const TemplateTypeParmType *TTPT)
void VisitSubstTemplateTypeParmType (const SubstTemplateTypeParmType *STTPT)
void VisitSubstTemplateTypeParmPackType (const SubstTemplateTypeParmPackType *T)
void VisitAutoType (const AutoType *AT)
void VisitTemplateSpecializationType (const TemplateSpecializationType *TST)
void VisitInjectedClassNameType (const InjectedClassNameType *ICNT)
void VisitObjCInterfaceType (const ObjCInterfaceType *OIT)
void VisitPackExpansionType (const PackExpansionType *PET)
void VisitElaboratedType (const ElaboratedType *ET)
void VisitMacroQualifiedType (const MacroQualifiedType *MQT)
void VisitMemberPointerType (const MemberPointerType *MPT)
void VisitNamedDecl (const NamedDecl *ND)
void VisitTypedefDecl (const TypedefDecl *TD)
void VisitTypeAliasDecl (const TypeAliasDecl *TAD)
void VisitNamespaceDecl (const NamespaceDecl *ND)
void VisitUsingDirectiveDecl (const UsingDirectiveDecl *UDD)
void VisitNamespaceAliasDecl (const NamespaceAliasDecl *NAD)
void VisitUsingDecl (const UsingDecl *UD)
void VisitUsingEnumDecl (const UsingEnumDecl *UED)
void VisitUsingShadowDecl (const UsingShadowDecl *USD)
void VisitVarDecl (const VarDecl *VD)
void VisitFieldDecl (const FieldDecl *FD)
void VisitFunctionDecl (const FunctionDecl *FD)
void VisitEnumDecl (const EnumDecl *ED)
void VisitEnumConstantDecl (const EnumConstantDecl *ECD)
void VisitRecordDecl (const RecordDecl *RD)
void VisitCXXRecordDecl (const CXXRecordDecl *RD)
void VisitHLSLBufferDecl (const HLSLBufferDecl *D)
void VisitTemplateTypeParmDecl (const TemplateTypeParmDecl *D)
void VisitNonTypeTemplateParmDecl (const NonTypeTemplateParmDecl *D)
void VisitTemplateTemplateParmDecl (const TemplateTemplateParmDecl *D)
void VisitLinkageSpecDecl (const LinkageSpecDecl *LSD)
void VisitAccessSpecDecl (const AccessSpecDecl *ASD)
void VisitFriendDecl (const FriendDecl *FD)
void VisitObjCIvarDecl (const ObjCIvarDecl *D)
void VisitObjCMethodDecl (const ObjCMethodDecl *D)
void VisitObjCTypeParamDecl (const ObjCTypeParamDecl *D)
void VisitObjCCategoryDecl (const ObjCCategoryDecl *D)
void VisitObjCCategoryImplDecl (const ObjCCategoryImplDecl *D)
void VisitObjCProtocolDecl (const ObjCProtocolDecl *D)
void VisitObjCInterfaceDecl (const ObjCInterfaceDecl *D)
void VisitObjCImplementationDecl (const ObjCImplementationDecl *D)
void VisitObjCCompatibleAliasDecl (const ObjCCompatibleAliasDecl *D)
void VisitObjCPropertyDecl (const ObjCPropertyDecl *D)
void VisitObjCPropertyImplDecl (const ObjCPropertyImplDecl *D)
void VisitBlockDecl (const BlockDecl *D)
void VisitDeclRefExpr (const DeclRefExpr *DRE)
void VisitSYCLUniqueStableNameExpr (const SYCLUniqueStableNameExpr *E)
void VisitSYCLUniqueStableIdExpr (const SYCLUniqueStableIdExpr *E)
void VisitPredefinedExpr (const PredefinedExpr *PE)
void VisitUnaryOperator (const UnaryOperator *UO)
void VisitBinaryOperator (const BinaryOperator *BO)
void VisitCompoundAssignOperator (const CompoundAssignOperator *CAO)
void VisitMemberExpr (const MemberExpr *ME)
void VisitAtomicExpr (const AtomicExpr *AE)
void VisitCXXNewExpr (const CXXNewExpr *NE)
void VisitCXXDeleteExpr (const CXXDeleteExpr *DE)
void VisitCXXThisExpr (const CXXThisExpr *TE)
void VisitCastExpr (const CastExpr *CE)
void VisitImplicitCastExpr (const ImplicitCastExpr *ICE)
void VisitCallExpr (const CallExpr *CE)
void VisitUnaryExprOrTypeTraitExpr (const UnaryExprOrTypeTraitExpr *TTE)
void VisitSizeOfPackExpr (const SizeOfPackExpr *SOPE)
void VisitUnresolvedLookupExpr (const UnresolvedLookupExpr *ULE)
void VisitAddrLabelExpr (const AddrLabelExpr *ALE)
void VisitCXXTypeidExpr (const CXXTypeidExpr *CTE)
void VisitConstantExpr (const ConstantExpr *CE)
void VisitInitListExpr (const InitListExpr *ILE)
void VisitGenericSelectionExpr (const GenericSelectionExpr *GSE)
void VisitCXXUnresolvedConstructExpr (const CXXUnresolvedConstructExpr *UCE)
void VisitCXXConstructExpr (const CXXConstructExpr *CE)
void VisitExprWithCleanups (const ExprWithCleanups *EWC)
void VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr *BTE)
void VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr *MTE)
void VisitCXXDependentScopeMemberExpr (const CXXDependentScopeMemberExpr *ME)
void VisitRequiresExpr (const RequiresExpr *RE)
void VisitCXXDefaultArgExpr (const CXXDefaultArgExpr *Node)
void VisitCXXDefaultInitExpr (const CXXDefaultInitExpr *Node)
void VisitObjCEncodeExpr (const ObjCEncodeExpr *OEE)
void VisitObjCMessageExpr (const ObjCMessageExpr *OME)
void VisitObjCBoxedExpr (const ObjCBoxedExpr *OBE)
void VisitObjCSelectorExpr (const ObjCSelectorExpr *OSE)
void VisitObjCProtocolExpr (const ObjCProtocolExpr *OPE)
void VisitObjCPropertyRefExpr (const ObjCPropertyRefExpr *OPRE)
void VisitObjCSubscriptRefExpr (const ObjCSubscriptRefExpr *OSRE)
void VisitObjCIvarRefExpr (const ObjCIvarRefExpr *OIRE)
void VisitObjCBoolLiteralExpr (const ObjCBoolLiteralExpr *OBLE)
void VisitIntegerLiteral (const IntegerLiteral *IL)
void VisitCharacterLiteral (const CharacterLiteral *CL)
void VisitFixedPointLiteral (const FixedPointLiteral *FPL)
void VisitFloatingLiteral (const FloatingLiteral *FL)
void VisitStringLiteral (const StringLiteral *SL)
void VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr *BLE)
void VisitIfStmt (const IfStmt *IS)
void VisitSwitchStmt (const SwitchStmt *SS)
void VisitCaseStmt (const CaseStmt *CS)
void VisitLabelStmt (const LabelStmt *LS)
void VisitGotoStmt (const GotoStmt *GS)
void VisitWhileStmt (const WhileStmt *WS)
void VisitObjCAtCatchStmt (const ObjCAtCatchStmt *OACS)
void VisitCompoundStmt (const CompoundStmt *IS)
void VisitNullTemplateArgument (const TemplateArgument &TA)
void VisitTypeTemplateArgument (const TemplateArgument &TA)
void VisitDeclarationTemplateArgument (const TemplateArgument &TA)
void VisitNullPtrTemplateArgument (const TemplateArgument &TA)
void VisitIntegralTemplateArgument (const TemplateArgument &TA)
void VisitTemplateTemplateArgument (const TemplateArgument &TA)
void VisitTemplateExpansionTemplateArgument (const TemplateArgument &TA)
void VisitExpressionTemplateArgument (const TemplateArgument &TA)
void VisitPackTemplateArgument (const TemplateArgument &TA)
void visitTextComment (const comments::TextComment *C, const comments::FullComment *)
void visitInlineCommandComment (const comments::InlineCommandComment *C, const comments::FullComment *)
void visitHTMLStartTagComment (const comments::HTMLStartTagComment *C, const comments::FullComment *)
void visitHTMLEndTagComment (const comments::HTMLEndTagComment *C, const comments::FullComment *)
void visitBlockCommandComment (const comments::BlockCommandComment *C, const comments::FullComment *)
void visitParamCommandComment (const comments::ParamCommandComment *C, const comments::FullComment *FC)
void visitTParamCommandComment (const comments::TParamCommandComment *C, const comments::FullComment *FC)
void visitVerbatimBlockComment (const comments::VerbatimBlockComment *C, const comments::FullComment *)
void visitVerbatimBlockLineComment (const comments::VerbatimBlockLineComment *C, const comments::FullComment *)
void visitVerbatimLineComment (const comments::VerbatimLineComment *C, const comments::FullComment *)
Public Member Functions inherited from clang::attrvisitor::Base< Ptr, ImplClass, RetTy, ParamTys >
RetTy Visit (PTR(Attr) A)
RetTy VisitAttr (PTR(Attr))
Public Member Functions inherited from clang::comments::CommentVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
RetTy visit (PTR(Comment) C, ParamTys... P)
RetTy visitComment (PTR(Comment) C, ParamTys... P)
Public Member Functions inherited from clang::templateargumentvisitor::Base< Ref, ImplClass, RetTy, ParamTys >
RetTy Visit (REF(TemplateArgument) TA, ParamTys... P)
VISIT_METHOD (Null)
VISIT_METHOD (Type)
VISIT_METHOD (Declaration)
VISIT_METHOD (NullPtr)
VISIT_METHOD (Integral)
VISIT_METHOD (StructuralValue)
VISIT_METHOD (Template)
VISIT_METHOD (TemplateExpansion)
VISIT_METHOD (Expression)
VISIT_METHOD (Pack)
RetTy VisitTemplateArgument (REF(TemplateArgument), ParamTys...)
Public Member Functions inherited from clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
RetTy Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) RetTy VisitStmt(PTR(Stmt) Node
Public Member Functions inherited from clang::TypeVisitor< JSONNodeDumper >
void Visit (const Type *T)
Performs the operation associated with this visitor object.
void VisitType (const Type *)
Method called if ImpClass doesn't provide specific handler for some type class.
Public Member Functions inherited from clang::declvisitor::Base< Ptr, ImplClass, RetTy >
RetTy Visit (PTR(Decl) D)
RetTy VisitDecl (PTR(Decl) D)
Public Member Functions inherited from clang::NodeStreamer
template<typename Fn >
void AddChild (Fn DoAddChild)
Add a child of the current node. Calls DoAddChild without arguments.
template<typename Fn >
void AddChild (StringRef Label, Fn DoAddChild)
Add a child of the current node with an optional label.
NodeStreamer (raw_ostream &OS)
Friends
class JSONDumper
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
ParamTys P { return RetTy()
Protected Attributes inherited from clang::NodeStreamer
llvm::json::OStream JOS
Detailed Description
Definition at line 116 of file JSONNodeDumper.h.
Constructor & Destructor Documentation
JSONNodeDumper()
clang::JSONNodeDumper::JSONNodeDumper (raw_ostream & OS, const SourceManager & SrcMgr, ASTContext & Ctx, const PrintingPolicy & PrintPolicy, const comments::CommandTraits * Traits) inline
Definition at line 188 of file JSONNodeDumper.h.
Member Function Documentation
Visit() [1/16]
void JSONNodeDumper::Visit (const APValue & Value, QualType Ty)
Definition at line 236 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
Visit() [2/16]
void JSONNodeDumper::Visit (const Attr * A)
Definition at line 24 of file JSONNodeDumper.cpp.
References clang::Attr::getKind(), clang::AttributeCommonInfo::getRange(), clang::Attr::isImplicit(), clang::Attr::isInherited(), clang::NodeStreamer::JOS, and clang::attrvisitor::Base< Ptr, ImplClass, RetTy, ParamTys >::Visit().
Referenced by VisitConstantExpr(), VisitNonTypeTemplateParmDecl(), VisitTemplateTemplateParmDecl(), and VisitTemplateTypeParmDecl().
Visit() [3/16]
void JSONNodeDumper::Visit (const BlockDecl::Capture & C)
Definition at line 194 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
Visit() [4/16]
void JSONNodeDumper::Visit (const comments::Comment * C, const comments::FullComment * FC)
Definition at line 149 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS, and clang::comments::CommentVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::visit().
Visit() [5/16]
void JSONNodeDumper::Visit (const ConceptReference * CR)
Definition at line 243 of file JSONNodeDumper.cpp.
References clang::ConceptReference::getLocation(), clang::ConceptReference::getNamedConcept(), clang::ConceptReference::getSourceRange(), clang::ConceptReference::getTemplateArgsAsWritten(), and clang::NodeStreamer::JOS.
Visit() [6/16]
void JSONNodeDumper::Visit (const concepts::Requirement * R)
Definition at line 207 of file JSONNodeDumper.cpp.
References clang::concepts::Requirement::containsUnexpandedParameterPack(), clang::concepts::Requirement::getKind(), clang::concepts::Requirement::isDependent(), clang::concepts::Requirement::isSatisfied(), clang::NodeStreamer::JOS, clang::concepts::Requirement::RK_Compound, clang::concepts::Requirement::RK_Nested, clang::concepts::Requirement::RK_Simple, and clang::concepts::Requirement::RK_Type.
Visit() [7/16]
void JSONNodeDumper::Visit (const CXXCtorInitializer * Init)
Definition at line 176 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
Visit() [8/16]
void JSONNodeDumper::Visit (const Decl * D)
Definition at line 114 of file JSONNodeDumper.cpp.
References clang::Decl::getDeclContext(), clang::Decl::getDeclKindName(), clang::Decl::getLexicalDeclContext(), clang::Decl::getLocation(), clang::Decl::getSourceRange(), clang::Decl::isImplicit(), clang::Decl::isInvalidDecl(), clang::Decl::isThisDeclarationReferenced(), clang::Decl::isUsed(), clang::NodeStreamer::JOS, and clang::declvisitor::Base< Ptr, ImplClass, RetTy >::Visit().
Visit() [9/16]
void JSONNodeDumper::Visit (const GenericSelectionExpr::ConstAssociation & A)
Definition at line 202 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
Visit() [10/16]
void JSONNodeDumper::Visit (const OMPClause * C)
Definition at line 192 of file JSONNodeDumper.cpp.
Visit() [11/16]
void JSONNodeDumper::Visit (const OpenACCClause * C)
Definition at line 190 of file JSONNodeDumper.cpp.
Visit() [12/16]
void JSONNodeDumper::Visit (const Stmt * Node)
Definition at line 49 of file JSONNodeDumper.cpp.
Visit() [13/16]
void JSONNodeDumper::Visit (const TemplateArgument & TA, SourceRange R = {}, const Decl * From = nullptr, StringRef Label = {})
Definition at line 164 of file JSONNodeDumper.cpp.
References clang::SourceRange::isValid(), clang::NodeStreamer::JOS, Label, and clang::templateargumentvisitor::Base< Ref, ImplClass, RetTy, ParamTys >::Visit().
Visit() [14/16]
void JSONNodeDumper::Visit (const Type * T)
Definition at line 73 of file JSONNodeDumper.cpp.
References clang::Type::containsErrors(), clang::Type::containsUnexpandedParameterPack(), clang::Type::getTypeClassName(), clang::Type::isDependentType(), clang::Type::isFromAST(), clang::Type::isInstantiationDependentType(), clang::Type::isVariablyModifiedType(), clang::NodeStreamer::JOS, clang::T, and clang::TypeVisitor< JSONNodeDumper >::Visit().
Visit() [15/16]
void JSONNodeDumper::Visit (QualType T)
Definition at line 92 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS, and clang::T.
Visit() [16/16]
void JSONNodeDumper::Visit (TypeLoc TL)
Definition at line 99 of file JSONNodeDumper.cpp.
References clang::TypeLoc::getSourceRange(), clang::TypeLoc::getType(), clang::Type::getTypeClassName(), clang::TypeLoc::getTypeLocClass(), clang::TypeLoc::getTypePtr(), clang::TypeLoc::isNull(), clang::NodeStreamer::JOS, and clang::TypeLoc::Qualified.
VisitAccessSpecDecl()
void JSONNodeDumper::VisitAccessSpecDecl (const AccessSpecDecl * ASD)
Definition at line 1084 of file JSONNodeDumper.cpp.
References clang::Decl::getAccess(), and clang::NodeStreamer::JOS.
VisitAddrLabelExpr()
void JSONNodeDumper::VisitAddrLabelExpr (const AddrLabelExpr * ALE)
Definition at line 1468 of file JSONNodeDumper.cpp.
References clang::AddrLabelExpr::getLabel(), clang::NamedDecl::getName(), and clang::NodeStreamer::JOS.
VisitAliasAttr()
void JSONNodeDumper::VisitAliasAttr (const AliasAttr * AA)
Definition at line 570 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitArrayType()
void JSONNodeDumper::VisitArrayType (const ArrayType * AT)
Definition at line 680 of file JSONNodeDumper.cpp.
References clang::Qualifiers::getAsString(), clang::ArrayType::getIndexTypeQualifiers(), clang::ArrayType::getSizeModifier(), clang::NodeStreamer::JOS, clang::Normal, clang::Star, and clang::Static.
Referenced by VisitConstantArrayType().
VisitAtomicExpr()
void JSONNodeDumper::VisitAtomicExpr (const AtomicExpr * AE)
Definition at line 1236 of file JSONNodeDumper.cpp.
References clang::AtomicExpr::getOpAsString(), and clang::NodeStreamer::JOS.
VisitAutoType()
void JSONNodeDumper::VisitAutoType (const AutoType * AT)
Definition at line 783 of file JSONNodeDumper.cpp.
References clang::Auto, clang::DecltypeAuto, clang::AutoType::getKeyword(), clang::GNUAutoType, clang::DeducedType::isDeduced(), and clang::NodeStreamer::JOS.
VisitBinaryOperator()
void JSONNodeDumper::VisitBinaryOperator (const BinaryOperator * BO)
Definition at line 1368 of file JSONNodeDumper.cpp.
References clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getOpcodeStr(), and clang::NodeStreamer::JOS.
Referenced by VisitCompoundAssignOperator().
visitBlockCommandComment()
void JSONNodeDumper::visitBlockCommandComment (const comments::BlockCommandComment * C, const comments::FullComment *)
Definition at line 1781 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitBlockDecl()
void JSONNodeDumper::VisitBlockDecl (const BlockDecl * D)
Definition at line 1231 of file JSONNodeDumper.cpp.
References clang::BlockDecl::capturesCXXThis(), and clang::BlockDecl::isVariadic().
VisitCallExpr()
void JSONNodeDumper::VisitCallExpr (const CallExpr * CE)
Definition at line 1442 of file JSONNodeDumper.cpp.
References clang::CallExpr::usesADL().
VisitCaseStmt()
void JSONNodeDumper::VisitCaseStmt (const CaseStmt * CS)
Definition at line 1659 of file JSONNodeDumper.cpp.
References clang::CaseStmt::caseStmtIsGNURange().
VisitCastExpr()
void JSONNodeDumper::VisitCastExpr (const CastExpr * CE)
Definition at line 1426 of file JSONNodeDumper.cpp.
References clang::CastExpr::getCastKindName(), clang::CastExpr::getConversionFunction(), and clang::NodeStreamer::JOS.
Referenced by VisitImplicitCastExpr().
VisitCharacterLiteral()
void JSONNodeDumper::VisitCharacterLiteral (const CharacterLiteral * CL)
Definition at line 1621 of file JSONNodeDumper.cpp.
References clang::CharacterLiteral::getValue(), and clang::NodeStreamer::JOS.
VisitCleanupAttr()
void JSONNodeDumper::VisitCleanupAttr (const CleanupAttr * CA)
Definition at line 574 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitCompoundAssignOperator()
void JSONNodeDumper::VisitCompoundAssignOperator (const CompoundAssignOperator * CAO)
Definition at line 1372 of file JSONNodeDumper.cpp.
References clang::CompoundAssignOperator::getComputationLHSType(), clang::CompoundAssignOperator::getComputationResultType(), clang::NodeStreamer::JOS, and VisitBinaryOperator().
VisitCompoundStmt()
void JSONNodeDumper::VisitCompoundStmt (const CompoundStmt * IS)
Definition at line 1857 of file JSONNodeDumper.cpp.
VisitConstantArrayType()
void JSONNodeDumper::VisitConstantArrayType (const ConstantArrayType * CAT)
Definition at line 697 of file JSONNodeDumper.cpp.
References clang::ConstantArrayType::getSExtSize(), clang::NodeStreamer::JOS, and VisitArrayType().
VisitConstantExpr()
void JSONNodeDumper::VisitConstantExpr (const ConstantExpr * CE)
Definition at line 1483 of file JSONNodeDumper.cpp.
References clang::ConstantExpr::getAPValueResult(), clang::ConstantExpr::getResultAPValueKind(), clang::Expr::getType(), clang::APValue::None, and Visit().
VisitCXXBindTemporaryExpr()
void JSONNodeDumper::VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr * BTE)
Definition at line 1551 of file JSONNodeDumper.cpp.
References clang::CXXTemporary::getDestructor(), clang::CXXBindTemporaryExpr::getTemporary(), and clang::NodeStreamer::JOS.
VisitCXXBoolLiteralExpr()
void JSONNodeDumper::VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr * BLE)
Definition at line 1642 of file JSONNodeDumper.cpp.
References clang::CXXBoolLiteralExpr::getValue(), and clang::NodeStreamer::JOS.
VisitCXXConstructExpr()
void JSONNodeDumper::VisitCXXConstructExpr (const CXXConstructExpr * CE)
Definition at line 1505 of file JSONNodeDumper.cpp.
References clang::Complete, clang::Delegating, clang::CXXConstructExpr::getConstructionKind(), clang::CXXConstructExpr::getConstructor(), clang::ValueDecl::getType(), clang::CXXConstructExpr::hadMultipleCandidates(), clang::CXXConstructExpr::isElidable(), clang::CXXConstructExpr::isImmediateEscalating(), clang::CXXConstructExpr::isListInitialization(), clang::CXXConstructExpr::isStdInitListInitialization(), clang::NodeStreamer::JOS, clang::NonVirtualBase, clang::CXXConstructExpr::requiresZeroInitialization(), and clang::VirtualBase.
VisitCXXDefaultArgExpr()
void JSONNodeDumper::VisitCXXDefaultArgExpr (const CXXDefaultArgExpr * Node)
Definition at line 1585 of file JSONNodeDumper.cpp.
References Node.
VisitCXXDefaultInitExpr()
void JSONNodeDumper::VisitCXXDefaultInitExpr (const CXXDefaultInitExpr * Node)
Definition at line 1589 of file JSONNodeDumper.cpp.
References Node.
VisitCXXDeleteExpr()
void JSONNodeDumper::VisitCXXDeleteExpr (const CXXDeleteExpr * DE)
Definition at line 1414 of file JSONNodeDumper.cpp.
References clang::CXXDeleteExpr::getOperatorDelete(), clang::CXXDeleteExpr::isArrayForm(), clang::CXXDeleteExpr::isArrayFormAsWritten(), clang::CXXDeleteExpr::isGlobalDelete(), and clang::NodeStreamer::JOS.
VisitCXXDependentScopeMemberExpr()
void JSONNodeDumper::VisitCXXDependentScopeMemberExpr (const CXXDependentScopeMemberExpr * ME)
Definition at line 1593 of file JSONNodeDumper.cpp.
References clang::DeclarationName::getAsString(), clang::CXXDependentScopeMemberExpr::getMember(), clang::CXXDependentScopeMemberExpr::getNumTemplateArgs(), clang::CXXDependentScopeMemberExpr::hasExplicitTemplateArgs(), clang::CXXDependentScopeMemberExpr::hasTemplateKeyword(), clang::CXXDependentScopeMemberExpr::isArrow(), clang::NodeStreamer::JOS, and clang::CXXDependentScopeMemberExpr::template_arguments().
VisitCXXNewExpr()
void JSONNodeDumper::VisitCXXNewExpr (const CXXNewExpr * NE)
Definition at line 1395 of file JSONNodeDumper.cpp.
References clang::Braces, clang::NodeStreamer::JOS, clang::interp::NE(), clang::None, and clang::Parens.
VisitCXXRecordDecl()
void JSONNodeDumper::VisitCXXRecordDecl (const CXXRecordDecl * RD)
Definition at line 1001 of file JSONNodeDumper.cpp.
References clang::CXXRecordDecl::bases(), clang::CXXRecordDecl::getNumBases(), clang::TagDecl::isCompleteDefinition(), clang::NodeStreamer::JOS, and VisitRecordDecl().
VisitCXXThisExpr()
void JSONNodeDumper::VisitCXXThisExpr (const CXXThisExpr * TE)
Definition at line 1422 of file JSONNodeDumper.cpp.
References clang::CXXThisExpr::isImplicit().
VisitCXXTypeidExpr()
void JSONNodeDumper::VisitCXXTypeidExpr (const CXXTypeidExpr * CTE)
Definition at line 1473 of file JSONNodeDumper.cpp.
References clang::TypeSourceInfo::getType(), clang::CXXTypeidExpr::getTypeOperand(), clang::CXXTypeidExpr::getTypeOperandSourceInfo(), clang::CXXTypeidExpr::isTypeOperand(), and clang::NodeStreamer::JOS.
VisitCXXUnresolvedConstructExpr()
void JSONNodeDumper::VisitCXXUnresolvedConstructExpr (const CXXUnresolvedConstructExpr * UCE)
Definition at line 1498 of file JSONNodeDumper.cpp.
References clang::Expr::getType(), clang::CXXUnresolvedConstructExpr::getTypeAsWritten(), clang::CXXUnresolvedConstructExpr::isListInitialization(), and clang::NodeStreamer::JOS.
VisitDeclarationTemplateArgument()
void JSONNodeDumper::VisitDeclarationTemplateArgument (const TemplateArgument & TA)
Definition at line 1690 of file JSONNodeDumper.cpp.
References clang::TemplateArgument::getAsDecl(), and clang::NodeStreamer::JOS.
VisitDeclRefExpr()
void JSONNodeDumper::VisitDeclRefExpr (const DeclRefExpr * DRE)
Definition at line 1334 of file JSONNodeDumper.cpp.
References clang::DeclRefExpr::getDecl(), clang::DeclRefExpr::getFoundDecl(), clang::DeclRefExpr::isImmediateEscalating(), clang::DeclRefExpr::isNonOdrUse(), clang::NodeStreamer::JOS, clang::NOUR_Constant, clang::NOUR_Discarded, clang::NOUR_None, and clang::NOUR_Unevaluated.
VisitDependentSizedExtVectorType()
void JSONNodeDumper::VisitDependentSizedExtVectorType (const DependentSizedExtVectorType * VT)
Definition at line 704 of file JSONNodeDumper.cpp.
References clang::DependentSizedExtVectorType::getAttributeLoc(), and clang::NodeStreamer::JOS.
VisitDeprecatedAttr()
void JSONNodeDumper::VisitDeprecatedAttr (const DeprecatedAttr * DA)
Definition at line 578 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitElaboratedType()
void JSONNodeDumper::VisitElaboratedType (const ElaboratedType * ET)
Definition at line 822 of file JSONNodeDumper.cpp.
References clang::ElaboratedType::getOwnedTagDecl(), clang::ElaboratedType::getQualifier(), and clang::NodeStreamer::JOS.
VisitEnumConstantDecl()
void JSONNodeDumper::VisitEnumConstantDecl (const EnumConstantDecl * ECD)
Definition at line 991 of file JSONNodeDumper.cpp.
References clang::ValueDecl::getType(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitEnumDecl()
void JSONNodeDumper::VisitEnumDecl (const EnumDecl * ED)
Definition at line 983 of file JSONNodeDumper.cpp.
References clang::EnumDecl::getIntegerType(), clang::EnumDecl::isFixed(), clang::EnumDecl::isScoped(), clang::EnumDecl::isScopedUsingClassTag(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitExpressionTemplateArgument()
void JSONNodeDumper::VisitExpressionTemplateArgument (const TemplateArgument & TA)
Definition at line 1709 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitExprWithCleanups()
void JSONNodeDumper::VisitExprWithCleanups (const ExprWithCleanups * EWC)
Definition at line 1531 of file JSONNodeDumper.cpp.
References clang::ExprWithCleanups::cleanupsHaveSideEffects(), clang::ExprWithCleanups::getNumObjects(), clang::ExprWithCleanups::getObjects(), clang::if(), and clang::NodeStreamer::JOS.
VisitFieldDecl()
void JSONNodeDumper::VisitFieldDecl (const FieldDecl * FD)
Definition at line 952 of file JSONNodeDumper.cpp.
References clang::ValueDecl::getType(), clang::FieldDecl::hasInClassInitializer(), clang::FieldDecl::isBitField(), clang::NamedDecl::isModulePrivate(), clang::FieldDecl::isMutable(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitFixedPointLiteral()
void JSONNodeDumper::VisitFixedPointLiteral (const FixedPointLiteral * FPL)
Definition at line 1628 of file JSONNodeDumper.cpp.
References clang::FixedPointLiteral::getValueAsString(), and clang::NodeStreamer::JOS.
VisitFloatingLiteral()
void JSONNodeDumper::VisitFloatingLiteral (const FloatingLiteral * FL)
Definition at line 1631 of file JSONNodeDumper.cpp.
References clang::FloatingLiteral::getValue(), and clang::NodeStreamer::JOS.
VisitFriendDecl()
void JSONNodeDumper::VisitFriendDecl (const FriendDecl * FD)
Definition at line 1088 of file JSONNodeDumper.cpp.
References clang::FriendDecl::getFriendType(), clang::NodeStreamer::JOS, and clang::T.
VisitFunctionDecl()
void JSONNodeDumper::VisitFunctionDecl (const FunctionDecl * FD)
Definition at line 961 of file JSONNodeDumper.cpp.
References clang::FunctionDecl::getDeletedMessage(), clang::FunctionDecl::getStorageClass(), clang::VarDecl::getStorageClassSpecifierString(), clang::ValueDecl::getType(), clang::FunctionDecl::isConstexpr(), clang::FunctionDecl::isDefaulted(), clang::FunctionDecl::isDeleted(), clang::FunctionDecl::isDeletedAsWritten(), clang::FunctionDecl::isImmediateFunction(), clang::FunctionDecl::isInlineSpecified(), clang::FunctionDecl::isPureVirtual(), clang::FunctionDecl::isVariadic(), clang::FunctionDecl::isVirtualAsWritten(), clang::NodeStreamer::JOS, clang::SC_None, and VisitNamedDecl().
VisitFunctionProtoType()
void JSONNodeDumper::VisitFunctionProtoType (const FunctionProtoType * T)
Definition at line 624 of file JSONNodeDumper.cpp.
References clang::EST_Dynamic, clang::EST_DynamicNone, clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, clang::FunctionProtoType::getExtProtoInfo(), clang::FunctionProtoType::ExtProtoInfo::HasTrailingReturn, clang::FunctionType::isConst(), clang::FunctionType::isRestrict(), clang::FunctionType::isVolatile(), clang::NodeStreamer::JOS, clang::FunctionProtoType::ExtProtoInfo::RefQualifier, clang::RQ_LValue, clang::RQ_None, clang::RQ_RValue, clang::T, clang::FunctionProtoType::ExceptionSpecInfo::Type, and clang::FunctionProtoType::ExtProtoInfo::Variadic.
VisitFunctionType()
void JSONNodeDumper::VisitFunctionType (const FunctionType * T)
Definition at line 615 of file JSONNodeDumper.cpp.
References clang::FunctionType::ExtInfo::getCC(), clang::FunctionType::getExtInfo(), clang::FunctionType::ExtInfo::getHasRegParm(), clang::FunctionType::getNameForCallConv(), clang::FunctionType::ExtInfo::getNoReturn(), clang::FunctionType::ExtInfo::getProducesResult(), clang::FunctionType::ExtInfo::getRegParm(), clang::NodeStreamer::JOS, and clang::T.
VisitGenericSelectionExpr()
void JSONNodeDumper::VisitGenericSelectionExpr (const GenericSelectionExpr * GSE)
Definition at line 1493 of file JSONNodeDumper.cpp.
References clang::GenericSelectionExpr::isResultDependent().
VisitGotoStmt()
void JSONNodeDumper::VisitGotoStmt (const GotoStmt * GS)
Definition at line 1668 of file JSONNodeDumper.cpp.
References clang::GotoStmt::getLabel(), and clang::NodeStreamer::JOS.
VisitHLSLBufferDecl()
void JSONNodeDumper::VisitHLSLBufferDecl (const HLSLBufferDecl * D)
Definition at line 1017 of file JSONNodeDumper.cpp.
References clang::HLSLBufferDecl::isCBuffer(), clang::NodeStreamer::JOS, and VisitNamedDecl().
visitHTMLEndTagComment()
void JSONNodeDumper::visitHTMLEndTagComment (const comments::HTMLEndTagComment * C, const comments::FullComment *)
Definition at line 1776 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
visitHTMLStartTagComment()
void JSONNodeDumper::visitHTMLStartTagComment (const comments::HTMLStartTagComment * C, const comments::FullComment *)
Definition at line 1761 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitIfStmt()
void JSONNodeDumper::VisitIfStmt (const IfStmt * IS)
Definition at line 1646 of file JSONNodeDumper.cpp.
References clang::IfStmt::hasElseStorage(), clang::IfStmt::hasInitStorage(), clang::IfStmt::hasVarStorage(), clang::IfStmt::isConsteval(), clang::IfStmt::isConstexpr(), and clang::IfStmt::isNegatedConsteval().
VisitImplicitCastExpr()
void JSONNodeDumper::VisitImplicitCastExpr (const ImplicitCastExpr * ICE)
Definition at line 1437 of file JSONNodeDumper.cpp.
References clang::ImplicitCastExpr::isPartOfExplicitCast(), and VisitCastExpr().
VisitInitListExpr()
void JSONNodeDumper::VisitInitListExpr (const InitListExpr * ILE)
Definition at line 1488 of file JSONNodeDumper.cpp.
References clang::InitListExpr::getInitializedFieldInUnion(), and clang::NodeStreamer::JOS.
VisitInjectedClassNameType()
void JSONNodeDumper::VisitInjectedClassNameType (const InjectedClassNameType * ICNT)
Definition at line 808 of file JSONNodeDumper.cpp.
References clang::InjectedClassNameType::getDecl(), and clang::NodeStreamer::JOS.
visitInlineCommandComment()
void JSONNodeDumper::visitInlineCommandComment (const comments::InlineCommandComment * C, const comments::FullComment *)
Definition at line 1731 of file JSONNodeDumper.cpp.
References clang::comments::Anchor, clang::comments::Bold, clang::comments::Emphasized, clang::NodeStreamer::JOS, clang::comments::Monospaced, and clang::comments::Normal.
VisitIntegerLiteral()
void JSONNodeDumper::VisitIntegerLiteral (const IntegerLiteral * IL)
Definition at line 1615 of file JSONNodeDumper.cpp.
References clang::Expr::getType(), clang::APIntStorage::getValue(), clang::Type::isSignedIntegerType(), and clang::NodeStreamer::JOS.
VisitIntegralTemplateArgument()
void JSONNodeDumper::VisitIntegralTemplateArgument (const TemplateArgument & TA)
Definition at line 1697 of file JSONNodeDumper.cpp.
References clang::TemplateArgument::getAsIntegral(), and clang::NodeStreamer::JOS.
VisitLabelStmt()
void JSONNodeDumper::VisitLabelStmt (const LabelStmt * LS)
Definition at line 1663 of file JSONNodeDumper.cpp.
References clang::LabelStmt::getDecl(), clang::LabelStmt::getName(), clang::LabelStmt::isSideEntry(), and clang::NodeStreamer::JOS.
VisitLinkageSpecDecl()
void JSONNodeDumper::VisitLinkageSpecDecl (const LinkageSpecDecl * LSD)
Definition at line 1070 of file JSONNodeDumper.cpp.
References clang::C, clang::CXX, clang::LinkageSpecDecl::getLanguage(), clang::LinkageSpecDecl::hasBraces(), and clang::NodeStreamer::JOS.
VisitMacroQualifiedType()
void JSONNodeDumper::VisitMacroQualifiedType (const MacroQualifiedType * MQT)
Definition at line 833 of file JSONNodeDumper.cpp.
References clang::MacroQualifiedType::getMacroIdentifier(), clang::IdentifierInfo::getName(), and clang::NodeStreamer::JOS.
VisitMaterializeTemporaryExpr()
void JSONNodeDumper::VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr * MTE)
Definition at line 1559 of file JSONNodeDumper.cpp.
References clang::MaterializeTemporaryExpr::getExtendingDecl(), clang::MaterializeTemporaryExpr::getStorageDuration(), clang::MaterializeTemporaryExpr::isBoundToLvalueReference(), clang::NodeStreamer::JOS, clang::SD_Automatic, clang::SD_Dynamic, clang::SD_FullExpression, clang::SD_Static, and clang::SD_Thread.
VisitMemberExpr()
void JSONNodeDumper::VisitMemberExpr (const MemberExpr * ME)
Definition at line 1380 of file JSONNodeDumper.cpp.
References clang::NamedDecl::getDeclName(), clang::MemberExpr::getMemberDecl(), clang::NamedDecl::getNameAsString(), clang::MemberExpr::isArrow(), clang::MemberExpr::isNonOdrUse(), clang::NodeStreamer::JOS, clang::NOUR_Constant, clang::NOUR_Discarded, clang::NOUR_None, and clang::NOUR_Unevaluated.
VisitMemberPointerType()
void JSONNodeDumper::VisitMemberPointerType (const MemberPointerType * MPT)
Definition at line 837 of file JSONNodeDumper.cpp.
References clang::MemberPointerType::isMemberDataPointer(), and clang::MemberPointerType::isMemberFunctionPointer().
VisitNamedDecl()
void JSONNodeDumper::VisitNamedDecl (const NamedDecl * ND)
Definition at line 842 of file JSONNodeDumper.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ASTNameGenerator::getName(), clang::NamedDecl::getNameAsString(), clang::Decl::isTemplated(), and clang::NodeStreamer::JOS.
Referenced by VisitEnumConstantDecl(), VisitEnumDecl(), VisitFieldDecl(), VisitFunctionDecl(), VisitHLSLBufferDecl(), VisitNamespaceAliasDecl(), VisitNamespaceDecl(), VisitNonTypeTemplateParmDecl(), VisitObjCCategoryDecl(), VisitObjCCategoryImplDecl(), VisitObjCCompatibleAliasDecl(), VisitObjCImplementationDecl(), VisitObjCInterfaceDecl(), VisitObjCIvarDecl(), VisitObjCMethodDecl(), VisitObjCPropertyDecl(), VisitObjCPropertyImplDecl(), VisitObjCProtocolDecl(), VisitObjCTypeParamDecl(), VisitRecordDecl(), VisitSizeOfPackExpr(), VisitTemplateTemplateParmDecl(), VisitTemplateTypeParmDecl(), VisitTypeAliasDecl(), VisitTypedefDecl(), and VisitVarDecl().
VisitNamespaceAliasDecl()
void JSONNodeDumper::VisitNamespaceAliasDecl (const NamespaceAliasDecl * NAD)
Definition at line 896 of file JSONNodeDumper.cpp.
References clang::NamespaceAliasDecl::getAliasedNamespace(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitNamespaceDecl()
void JSONNodeDumper::VisitNamespaceDecl (const NamespaceDecl * ND)
Definition at line 882 of file JSONNodeDumper.cpp.
References clang::NamespaceDecl::getOriginalNamespace(), clang::NamespaceDecl::isInline(), clang::NamespaceDecl::isNested(), clang::NamespaceDecl::isOriginalNamespace(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitNonTypeTemplateParmDecl()
void JSONNodeDumper::VisitNonTypeTemplateParmDecl (const NonTypeTemplateParmDecl * D)
Definition at line 1037 of file JSONNodeDumper.cpp.
References clang::NonTypeTemplateParmDecl::defaultArgumentWasInherited(), clang::NonTypeTemplateParmDecl::getDefaultArgStorage(), clang::NonTypeTemplateParmDecl::getDefaultArgument(), clang::NonTypeTemplateParmDecl::getDepth(), clang::NonTypeTemplateParmDecl::getIndex(), clang::DefaultArgStorage< ParmDecl, ArgType >::getInheritedFrom(), clang::ValueDecl::getType(), clang::NonTypeTemplateParmDecl::hasDefaultArgument(), clang::NonTypeTemplateParmDecl::isParameterPack(), clang::NodeStreamer::JOS, Visit(), and VisitNamedDecl().
VisitNullPtrTemplateArgument()
void JSONNodeDumper::VisitNullPtrTemplateArgument (const TemplateArgument & TA)
Definition at line 1694 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitNullTemplateArgument()
void JSONNodeDumper::VisitNullTemplateArgument (const TemplateArgument & TA)
Definition at line 1684 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitObjCAtCatchStmt()
void JSONNodeDumper::VisitObjCAtCatchStmt (const ObjCAtCatchStmt * OACS)
Definition at line 1677 of file JSONNodeDumper.cpp.
References clang::ObjCAtCatchStmt::getCatchParamDecl().
VisitObjCBoolLiteralExpr()
void JSONNodeDumper::VisitObjCBoolLiteralExpr (const ObjCBoolLiteralExpr * OBLE)
Definition at line 1330 of file JSONNodeDumper.cpp.
References clang::ObjCBoolLiteralExpr::getValue(), and clang::NodeStreamer::JOS.
VisitObjCBoxedExpr()
void JSONNodeDumper::VisitObjCBoxedExpr (const ObjCBoxedExpr * OBE)
Definition at line 1274 of file JSONNodeDumper.cpp.
References clang::ObjCBoxedExpr::getBoxingMethod(), and clang::NodeStreamer::JOS.
VisitObjCCategoryDecl()
void JSONNodeDumper::VisitObjCCategoryDecl (const ObjCCategoryDecl * D)
Definition at line 1129 of file JSONNodeDumper.cpp.
References clang::ObjCCategoryDecl::getClassInterface(), clang::ObjCCategoryDecl::getImplementation(), clang::NodeStreamer::JOS, clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::P, clang::ObjCCategoryDecl::protocols(), and VisitNamedDecl().
VisitObjCCategoryImplDecl()
void JSONNodeDumper::VisitObjCCategoryImplDecl (const ObjCCategoryImplDecl * D)
Definition at line 1141 of file JSONNodeDumper.cpp.
References clang::ObjCCategoryImplDecl::getCategoryDecl(), clang::ObjCImplDecl::getClassInterface(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitObjCCompatibleAliasDecl()
void JSONNodeDumper::VisitObjCCompatibleAliasDecl (const ObjCCompatibleAliasDecl * D)
Definition at line 1176 of file JSONNodeDumper.cpp.
References clang::ObjCCompatibleAliasDecl::getClassInterface(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitObjCEncodeExpr()
void JSONNodeDumper::VisitObjCEncodeExpr (const ObjCEncodeExpr * OEE)
Definition at line 1240 of file JSONNodeDumper.cpp.
References clang::ObjCEncodeExpr::getEncodedType(), and clang::NodeStreamer::JOS.
VisitObjCImplementationDecl()
void JSONNodeDumper::VisitObjCImplementationDecl (const ObjCImplementationDecl * D)
Definition at line 1169 of file JSONNodeDumper.cpp.
References clang::ObjCImplDecl::getClassInterface(), clang::ObjCImplementationDecl::getSuperClass(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitObjCInterfaceDecl()
void JSONNodeDumper::VisitObjCInterfaceDecl (const ObjCInterfaceDecl * D)
Definition at line 1157 of file JSONNodeDumper.cpp.
References clang::ObjCInterfaceDecl::getImplementation(), clang::ObjCInterfaceDecl::getSuperClass(), clang::NodeStreamer::JOS, clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::P, clang::ObjCInterfaceDecl::protocols(), and VisitNamedDecl().
VisitObjCInterfaceType()
void JSONNodeDumper::VisitObjCInterfaceType (const ObjCInterfaceType * OIT)
Definition at line 813 of file JSONNodeDumper.cpp.
References clang::ObjCInterfaceType::getDecl(), and clang::NodeStreamer::JOS.
VisitObjCIvarDecl()
void JSONNodeDumper::VisitObjCIvarDecl (const ObjCIvarDecl * D)
Definition at line 1093 of file JSONNodeDumper.cpp.
References clang::ObjCIvarDecl::getAccessControl(), clang::ObjCIvarDecl::getSynthesize(), clang::ValueDecl::getType(), clang::NodeStreamer::JOS, clang::ObjCIvarDecl::None, clang::ObjCIvarDecl::Package, clang::ObjCIvarDecl::Private, clang::ObjCIvarDecl::Protected, clang::ObjCIvarDecl::Public, and VisitNamedDecl().
VisitObjCIvarRefExpr()
void JSONNodeDumper::VisitObjCIvarRefExpr (const ObjCIvarRefExpr * OIRE)
Definition at line 1324 of file JSONNodeDumper.cpp.
References clang::ObjCIvarRefExpr::getDecl(), clang::ObjCIvarRefExpr::isArrow(), clang::ObjCIvarRefExpr::isFreeIvar(), and clang::NodeStreamer::JOS.
VisitObjCMessageExpr()
void JSONNodeDumper::VisitObjCMessageExpr (const ObjCMessageExpr * OME)
Definition at line 1244 of file JSONNodeDumper.cpp.
References clang::ObjCMessageExpr::Class, clang::ObjCMessageExpr::getCallReturnType(), clang::ObjCMessageExpr::getClassReceiver(), clang::ObjCMessageExpr::getReceiverKind(), clang::ObjCMessageExpr::getSelector(), clang::ObjCMessageExpr::getSuperType(), clang::Expr::getType(), clang::ObjCMessageExpr::Instance, clang::NodeStreamer::JOS, clang::Selector::print(), clang::ObjCMessageExpr::SuperClass, and clang::ObjCMessageExpr::SuperInstance.
VisitObjCMethodDecl()
void JSONNodeDumper::VisitObjCMethodDecl (const ObjCMethodDecl * D)
Definition at line 1106 of file JSONNodeDumper.cpp.
References clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::isInstanceMethod(), clang::ObjCMethodDecl::isVariadic(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitObjCPropertyDecl()
void JSONNodeDumper::VisitObjCPropertyDecl (const ObjCPropertyDecl * D)
Definition at line 1182 of file JSONNodeDumper.cpp.
References clang::ObjCPropertyDecl::getGetterMethodDecl(), clang::ObjCPropertyDecl::getPropertyAttributes(), clang::ObjCPropertyDecl::getPropertyImplementation(), clang::ObjCPropertyDecl::getSetterMethodDecl(), clang::ObjCPropertyDecl::getType(), clang::NodeStreamer::JOS, clang::ObjCPropertyAttribute::kind_assign, clang::ObjCPropertyAttribute::kind_atomic, clang::ObjCPropertyAttribute::kind_class, clang::ObjCPropertyAttribute::kind_copy, clang::ObjCPropertyAttribute::kind_direct, clang::ObjCPropertyAttribute::kind_getter, clang::ObjCPropertyAttribute::kind_noattr, clang::ObjCPropertyAttribute::kind_nonatomic, clang::ObjCPropertyAttribute::kind_null_resettable, clang::ObjCPropertyAttribute::kind_nullability, clang::ObjCPropertyAttribute::kind_readonly, clang::ObjCPropertyAttribute::kind_readwrite, clang::ObjCPropertyAttribute::kind_retain, clang::ObjCPropertyAttribute::kind_setter, clang::ObjCPropertyAttribute::kind_strong, clang::ObjCPropertyAttribute::kind_unsafe_unretained, clang::ObjCPropertyAttribute::kind_weak, clang::ObjCPropertyDecl::None, clang::ObjCPropertyDecl::Optional, clang::ObjCPropertyDecl::Required, and VisitNamedDecl().
VisitObjCPropertyImplDecl()
void JSONNodeDumper::VisitObjCPropertyImplDecl (const ObjCPropertyImplDecl * D)
Definition at line 1221 of file JSONNodeDumper.cpp.
References clang::ObjCPropertyImplDecl::getPropertyDecl(), clang::ObjCPropertyImplDecl::getPropertyImplementation(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), clang::NodeStreamer::JOS, clang::ObjCPropertyImplDecl::Synthesize, and VisitNamedDecl().
VisitObjCPropertyRefExpr()
void JSONNodeDumper::VisitObjCPropertyRefExpr (const ObjCPropertyRefExpr * OPRE)
Definition at line 1296 of file JSONNodeDumper.cpp.
References clang::ObjCPropertyRefExpr::getExplicitProperty(), clang::ObjCPropertyRefExpr::getImplicitPropertyGetter(), clang::ObjCPropertyRefExpr::getImplicitPropertySetter(), clang::ObjCPropertyRefExpr::isImplicitProperty(), clang::ObjCPropertyRefExpr::isMessagingGetter(), clang::ObjCPropertyRefExpr::isMessagingSetter(), clang::ObjCPropertyRefExpr::isSuperReceiver(), and clang::NodeStreamer::JOS.
VisitObjCProtocolDecl()
void JSONNodeDumper::VisitObjCProtocolDecl (const ObjCProtocolDecl * D)
Definition at line 1147 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS, clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::P, clang::ObjCProtocolDecl::protocols(), and VisitNamedDecl().
VisitObjCProtocolExpr()
void JSONNodeDumper::VisitObjCProtocolExpr (const ObjCProtocolExpr * OPE)
Definition at line 1292 of file JSONNodeDumper.cpp.
References clang::ObjCProtocolExpr::getProtocol(), and clang::NodeStreamer::JOS.
VisitObjCSelectorExpr()
void JSONNodeDumper::VisitObjCSelectorExpr (const ObjCSelectorExpr * OSE)
Definition at line 1284 of file JSONNodeDumper.cpp.
References clang::ObjCSelectorExpr::getSelector(), clang::NodeStreamer::JOS, and clang::Selector::print().
VisitObjCSubscriptRefExpr()
void JSONNodeDumper::VisitObjCSubscriptRefExpr (const ObjCSubscriptRefExpr * OSRE)
Definition at line 1313 of file JSONNodeDumper.cpp.
References clang::ObjCSubscriptRefExpr::getAtIndexMethodDecl(), clang::ObjCSubscriptRefExpr::isArraySubscriptRefExpr(), clang::NodeStreamer::JOS, and clang::ObjCSubscriptRefExpr::setAtIndexMethodDecl().
VisitObjCTypeParamDecl()
void JSONNodeDumper::VisitObjCTypeParamDecl (const ObjCTypeParamDecl * D)
Definition at line 1113 of file JSONNodeDumper.cpp.
References clang::Contravariant, clang::Covariant, clang::TypedefNameDecl::getUnderlyingType(), clang::ObjCTypeParamDecl::getVariance(), clang::ObjCTypeParamDecl::hasExplicitBound(), clang::Invariant, clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitPackExpansionType()
void JSONNodeDumper::VisitPackExpansionType (const PackExpansionType * PET)
Definition at line 817 of file JSONNodeDumper.cpp.
References clang::PackExpansionType::getNumExpansions(), and clang::NodeStreamer::JOS.
VisitPackTemplateArgument()
void JSONNodeDumper::VisitPackTemplateArgument (const TemplateArgument & TA)
Definition at line 1713 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
visitParamCommandComment()
void JSONNodeDumper::visitParamCommandComment (const comments::ParamCommandComment * C, const comments::FullComment * FC)
Definition at line 1793 of file JSONNodeDumper.cpp.
References clang::comments::In, clang::comments::InOut, clang::NodeStreamer::JOS, and clang::comments::Out.
VisitPredefinedExpr()
void JSONNodeDumper::VisitPredefinedExpr (const PredefinedExpr * PE)
Definition at line 1357 of file JSONNodeDumper.cpp.
References clang::PredefinedExpr::getIdentKind(), clang::PredefinedExpr::getIdentKindName(), and clang::NodeStreamer::JOS.
VisitRecordDecl()
void JSONNodeDumper::VisitRecordDecl (const RecordDecl * RD)
Definition at line 996 of file JSONNodeDumper.cpp.
References clang::TagDecl::getKindName(), clang::TagDecl::isCompleteDefinition(), clang::NodeStreamer::JOS, and VisitNamedDecl().
Referenced by VisitCXXRecordDecl().
VisitRequiresExpr()
void JSONNodeDumper::VisitRequiresExpr (const RequiresExpr * RE)
Definition at line 1610 of file JSONNodeDumper.cpp.
References clang::RequiresExpr::isSatisfied(), clang::Expr::isValueDependent(), and clang::NodeStreamer::JOS.
VisitRValueReferenceType()
void JSONNodeDumper::VisitRValueReferenceType (const ReferenceType * RT)
Definition at line 676 of file JSONNodeDumper.cpp.
References clang::ReferenceType::isSpelledAsLValue().
VisitSectionAttr()
void JSONNodeDumper::VisitSectionAttr (const SectionAttr * SA)
Definition at line 590 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitSizeOfPackExpr()
void JSONNodeDumper::VisitSizeOfPackExpr (const SizeOfPackExpr * SOPE)
Definition at line 1453 of file JSONNodeDumper.cpp.
References clang::SizeOfPackExpr::getPack(), and VisitNamedDecl().
VisitStringLiteral()
void JSONNodeDumper::VisitStringLiteral (const StringLiteral * SL)
Definition at line 1636 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS, and clang::StringLiteral::outputString().
VisitSubstTemplateTypeParmPackType()
void JSONNodeDumper::VisitSubstTemplateTypeParmPackType (const SubstTemplateTypeParmPackType * T)
Definition at line 778 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS, and clang::T.
VisitSubstTemplateTypeParmType()
void JSONNodeDumper::VisitSubstTemplateTypeParmType (const SubstTemplateTypeParmType * STTPT)
Definition at line 771 of file JSONNodeDumper.cpp.
References clang::SubstTemplateTypeParmType::getIndex(), clang::SubstTemplateTypeParmType::getPackIndex(), and clang::NodeStreamer::JOS.
VisitSwitchStmt()
void JSONNodeDumper::VisitSwitchStmt (const SwitchStmt * SS)
Definition at line 1655 of file JSONNodeDumper.cpp.
References clang::SwitchStmt::hasInitStorage(), and clang::SwitchStmt::hasVarStorage().
VisitSYCLUniqueStableIdExpr()
void JSONNodeDumper::VisitSYCLUniqueStableIdExpr (const SYCLUniqueStableIdExpr * E)
Definition at line 1354 of file JSONNodeDumper.cpp.
VisitSYCLUniqueStableNameExpr()
void JSONNodeDumper::VisitSYCLUniqueStableNameExpr (const SYCLUniqueStableNameExpr * E)
Definition at line 1348 of file JSONNodeDumper.cpp.
References clang::TypeSourceInfo::getType(), clang::SYCLUniqueStableNameExpr::getTypeSourceInfo(), and clang::NodeStreamer::JOS.
VisitTagType()
void JSONNodeDumper::VisitTagType (const TagType * TT)
Definition at line 759 of file JSONNodeDumper.cpp.
References clang::TagType::getDecl(), and clang::NodeStreamer::JOS.
VisitTemplateExpansionTemplateArgument()
void JSONNodeDumper::VisitTemplateExpansionTemplateArgument (const TemplateArgument & TA)
Definition at line 1704 of file JSONNodeDumper.cpp.
VisitTemplateSpecializationType()
void JSONNodeDumper::VisitTemplateSpecializationType (const TemplateSpecializationType * TST)
Definition at line 798 of file JSONNodeDumper.cpp.
References clang::TemplateSpecializationType::getTemplateName(), clang::TemplateSpecializationType::isTypeAlias(), clang::NodeStreamer::JOS, and clang::TemplateName::print().
VisitTemplateTemplateArgument()
void JSONNodeDumper::VisitTemplateTemplateArgument (const TemplateArgument & TA)
Definition at line 1700 of file JSONNodeDumper.cpp.
VisitTemplateTemplateParmDecl()
void JSONNodeDumper::VisitTemplateTemplateParmDecl (const TemplateTemplateParmDecl * D)
Definition at line 1053 of file JSONNodeDumper.cpp.
References clang::TemplateTemplateParmDecl::defaultArgumentWasInherited(), clang::TemplateArgumentLoc::getArgument(), clang::TemplateTemplateParmDecl::getDefaultArgStorage(), clang::TemplateTemplateParmDecl::getDefaultArgument(), clang::TemplateTemplateParmDecl::getDepth(), clang::TemplateTemplateParmDecl::getIndex(), clang::TemplateTemplateParmDecl::hasDefaultArgument(), clang::TemplateTemplateParmDecl::isParameterPack(), clang::NodeStreamer::JOS, Visit(), and VisitNamedDecl().
VisitTemplateTypeParmDecl()
void JSONNodeDumper::VisitTemplateTypeParmDecl (const TemplateTypeParmDecl * D)
Definition at line 1022 of file JSONNodeDumper.cpp.
References clang::TemplateTypeParmDecl::defaultArgumentWasInherited(), clang::TemplateTypeParmDecl::getDefaultArgStorage(), clang::TemplateTypeParmDecl::getDefaultArgument(), clang::TemplateTypeParmDecl::getDepth(), clang::TemplateTypeParmDecl::getIndex(), clang::DefaultArgStorage< ParmDecl, ArgType >::getInheritedFrom(), clang::TemplateTypeParmDecl::hasDefaultArgument(), clang::TemplateTypeParmDecl::isParameterPack(), clang::NodeStreamer::JOS, Visit(), VisitNamedDecl(), and clang::TemplateTypeParmDecl::wasDeclaredWithTypename().
VisitTemplateTypeParmType()
void JSONNodeDumper::VisitTemplateTypeParmType (const TemplateTypeParmType * TTPT)
Definition at line 763 of file JSONNodeDumper.cpp.
References clang::TemplateTypeParmType::getDecl(), clang::TemplateTypeParmType::getDepth(), clang::TemplateTypeParmType::getIndex(), clang::TemplateTypeParmType::isParameterPack(), and clang::NodeStreamer::JOS.
visitTextComment()
void JSONNodeDumper::visitTextComment (const comments::TextComment * C, const comments::FullComment *)
Definition at line 1726 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitTLSModelAttr()
void JSONNodeDumper::VisitTLSModelAttr (const TLSModelAttr * TA)
Definition at line 599 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
visitTParamCommandComment()
void JSONNodeDumper::visitTParamCommandComment (const comments::TParamCommandComment * C, const comments::FullComment * FC)
Definition at line 1816 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitTypeAliasDecl()
void JSONNodeDumper::VisitTypeAliasDecl (const TypeAliasDecl * TAD)
Definition at line 877 of file JSONNodeDumper.cpp.
References clang::TypedefNameDecl::getUnderlyingType(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitTypedefDecl()
void JSONNodeDumper::VisitTypedefDecl (const TypedefDecl * TD)
Definition at line 872 of file JSONNodeDumper.cpp.
References clang::TypedefNameDecl::getUnderlyingType(), clang::NodeStreamer::JOS, and VisitNamedDecl().
VisitTypedefType()
void JSONNodeDumper::VisitTypedefType (const TypedefType * TT)
Definition at line 603 of file JSONNodeDumper.cpp.
References clang::TypedefType::desugar(), clang::TypedefType::getDecl(), clang::NodeStreamer::JOS, and clang::TypedefType::typeMatchesDecl().
VisitTypeTemplateArgument()
void JSONNodeDumper::VisitTypeTemplateArgument (const TemplateArgument & TA)
Definition at line 1687 of file JSONNodeDumper.cpp.
References clang::TemplateArgument::getAsType(), and clang::NodeStreamer::JOS.
VisitUnaryExprOrTypeTraitExpr()
void JSONNodeDumper::VisitUnaryExprOrTypeTraitExpr (const UnaryExprOrTypeTraitExpr * TTE)
Definition at line 1446 of file JSONNodeDumper.cpp.
References clang::UnaryExprOrTypeTraitExpr::getArgumentType(), clang::UnaryExprOrTypeTraitExpr::getKind(), clang::getTraitSpelling(), clang::UnaryExprOrTypeTraitExpr::isArgumentType(), and clang::NodeStreamer::JOS.
VisitUnaryOperator()
void JSONNodeDumper::VisitUnaryOperator (const UnaryOperator * UO)
Definition at line 1361 of file JSONNodeDumper.cpp.
References clang::UnaryOperator::canOverflow(), clang::UnaryOperator::getOpcode(), clang::UnaryOperator::getOpcodeStr(), clang::UnaryOperator::isPostfix(), and clang::NodeStreamer::JOS.
VisitUnaryTransformType()
void JSONNodeDumper::VisitUnaryTransformType (const UnaryTransformType * UTT)
Definition at line 749 of file JSONNodeDumper.cpp.
References clang::UnaryTransformType::getUTTKind().
VisitUnavailableAttr()
void JSONNodeDumper::VisitUnavailableAttr (const UnavailableAttr * UA)
Definition at line 585 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitUnresolvedLookupExpr()
void JSONNodeDumper::VisitUnresolvedLookupExpr (const UnresolvedLookupExpr * ULE)
Definition at line 1457 of file JSONNodeDumper.cpp.
References clang::OverloadExpr::decls(), clang::DeclarationName::getAsString(), clang::OverloadExpr::getName(), clang::NodeStreamer::JOS, and clang::UnresolvedLookupExpr::requiresADL().
VisitUnresolvedUsingType()
void JSONNodeDumper::VisitUnresolvedUsingType (const UnresolvedUsingType * UUT)
Definition at line 745 of file JSONNodeDumper.cpp.
References clang::UnresolvedUsingType::getDecl(), and clang::NodeStreamer::JOS.
VisitUsingDecl()
void JSONNodeDumper::VisitUsingDecl (const UsingDecl * UD)
Definition at line 902 of file JSONNodeDumper.cpp.
VisitUsingDirectiveDecl()
void JSONNodeDumper::VisitUsingDirectiveDecl (const UsingDirectiveDecl * UDD)
Definition at line 891 of file JSONNodeDumper.cpp.
References clang::UsingDirectiveDecl::getNominatedNamespace(), and clang::NodeStreamer::JOS.
VisitUsingEnumDecl()
void JSONNodeDumper::VisitUsingEnumDecl (const UsingEnumDecl * UED)
Definition at line 912 of file JSONNodeDumper.cpp.
References clang::UsingEnumDecl::getEnumDecl(), and clang::NodeStreamer::JOS.
VisitUsingShadowDecl()
void JSONNodeDumper::VisitUsingShadowDecl (const UsingShadowDecl * USD)
Definition at line 916 of file JSONNodeDumper.cpp.
References clang::UsingShadowDecl::getTargetDecl(), and clang::NodeStreamer::JOS.
VisitUsingType()
void JSONNodeDumper::VisitUsingType (const UsingType * TT)
Definition at line 609 of file JSONNodeDumper.cpp.
References clang::UsingType::desugar(), clang::UsingType::getFoundDecl(), clang::NodeStreamer::JOS, and clang::UsingType::typeMatchesDecl().
VisitVarDecl()
void JSONNodeDumper::VisitVarDecl (const VarDecl * VD)
Definition at line 920 of file JSONNodeDumper.cpp.
References clang::VarDecl::CallInit, clang::VarDecl::CInit, clang::VarDecl::getInitStyle(), clang::VarDecl::getStorageClass(), clang::VarDecl::getStorageClassSpecifierString(), clang::VarDecl::getTLSKind(), clang::ValueDecl::getType(), clang::VarDecl::hasInit(), clang::VarDecl::isConstexpr(), clang::VarDecl::isInline(), clang::NamedDecl::isModulePrivate(), clang::VarDecl::isNRVOVariable(), clang::VarDecl::isParameterPack(), clang::NodeStreamer::JOS, clang::VarDecl::ListInit, clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::P, clang::VarDecl::ParenListInit, clang::SC_None, clang::VarDecl::TLS_Dynamic, clang::VarDecl::TLS_None, clang::VarDecl::TLS_Static, and VisitNamedDecl().
VisitVectorType()
void JSONNodeDumper::VisitVectorType (const VectorType * VT)
Definition at line 710 of file JSONNodeDumper.cpp.
References clang::AltiVecBool, clang::AltiVecPixel, clang::AltiVecVector, clang::Generic, clang::VectorType::getNumElements(), clang::VectorType::getVectorKind(), clang::NodeStreamer::JOS, clang::Neon, clang::NeonPoly, clang::RVVFixedLengthData, clang::RVVFixedLengthMask, clang::SveFixedLengthData, and clang::SveFixedLengthPredicate.
visitVerbatimBlockComment()
void JSONNodeDumper::visitVerbatimBlockComment (const comments::VerbatimBlockComment * C, const comments::FullComment *)
Definition at line 1831 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
visitVerbatimBlockLineComment()
void JSONNodeDumper::visitVerbatimBlockLineComment (const comments::VerbatimBlockLineComment * C, const comments::FullComment *)
Definition at line 1837 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
visitVerbatimLineComment()
void JSONNodeDumper::visitVerbatimLineComment (const comments::VerbatimLineComment * C, const comments::FullComment *)
Definition at line 1843 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitVisibilityAttr()
void JSONNodeDumper::VisitVisibilityAttr (const VisibilityAttr * VA)
Definition at line 594 of file JSONNodeDumper.cpp.
References clang::NodeStreamer::JOS.
VisitWhileStmt()
void JSONNodeDumper::VisitWhileStmt (const WhileStmt * WS)
Definition at line 1673 of file JSONNodeDumper.cpp.
References clang::WhileStmt::hasVarStorage().
Friends And Related Function Documentation
JSONDumper
friend class JSONDumper friend
Definition at line 125 of file JSONNodeDumper.h.
The documentation for this class was generated from the following files:
include/clang/AST/JSONNodeDumper.h
lib/AST/JSONNodeDumper.cpp