clang: clang::EmbedExpr::ChildElementIter< Const > Class Template Reference
clang::EmbedExpr::ChildElementIter< Const > Class Template Reference
#include "clang/AST/Expr.h"
Public Member Functions
ChildElementIter ()
BaseTy::reference operator* () const
BaseTy::pointer operator-> () const
ChildElementIter & operator++ ()
bool operator== (ChildElementIter Other) const
Friends
class EmbedExpr
Detailed Description
template<bool Const>
class clang::EmbedExpr::ChildElementIter< Const >
Definition at line 4928 of file Expr.h.
Constructor & Destructor Documentation
ChildElementIter()
template<bool Const> clang::EmbedExpr::ChildElementIter< Const >::ChildElementIter () inline
Definition at line 4945 of file Expr.h.
Member Function Documentation
operator*()
template<bool Const> BaseTy::reference clang::EmbedExpr::ChildElementIter< Const >::operator* () const inline
Definition at line 4946 of file Expr.h.
References clang::EmbedDataStorage::BinaryData, clang::StringLiteral::getBytes(), clang::Expr::getType(), clang::APIntStorage::getValue(), clang::Type::isSignedIntegerType(), and clang::APIntStorage::setValue().
operator++()
template<bool Const> ChildElementIter& clang::EmbedExpr::ChildElementIter< Const >::operator++ () inline
Definition at line 4960 of file Expr.h.
References clang::EmbedExpr::getDataElementCount(), and clang::EmbedExpr::getStartingElementPos().
operator->()
template<bool Const> BaseTy::pointer clang::EmbedExpr::ChildElementIter< Const >::operator-> () const inline
Definition at line 4958 of file Expr.h.
operator==()
template<bool Const> bool clang::EmbedExpr::ChildElementIter< Const >::operator== (ChildElementIter< Const > Other) const inline
Definition at line 4971 of file Expr.h.
References clang::Other.
Friends And Related Function Documentation
EmbedExpr
template<bool Const> friend class EmbedExpr friend
Definition at line 4933 of file Expr.h.
The documentation for this class was generated from the following file:
include/clang/AST/Expr.h