clang: clang::OpenACCClauseWithIntExprs Class Reference
clang::OpenACCClauseWithIntExprs Class Reference
Represents a clause that has one or more IntExprs.
#include "clang/AST/OpenACCClause.h"
Public Member Functions
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClauseWithParams
SourceLocation getLParenLoc () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClause
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Protected Member Functions
OpenACCClauseWithIntExprs (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
void setIntExprs (MutableArrayRef< Expr * > NewIntExprs)
Used only for initialization, the leaf class can initialize this to trailing storage.
llvm::ArrayRef< Expr * > getIntExprs () const
Gets the entire list of integer expressions, but leave it to the individual clauses to expose this how they'd like.
Protected Member Functions inherited from clang::OpenACCClauseWithParams
OpenACCClauseWithParams (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClause
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Additional Inherited Members
Public Types inherited from clang::OpenACCClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Static Public Member Functions inherited from clang::OpenACCClause
static bool classof (const OpenACCClause *)
Detailed Description
Represents a clause that has one or more IntExprs.
It does not own the IntExprs, but provides 'children' and other accessors.
Definition at line 161 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCClauseWithIntExprs()
clang::OpenACCClauseWithIntExprs::OpenACCClauseWithIntExprs (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline protected
Definition at line 165 of file OpenACCClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OpenACCClauseWithIntExprs::children () inline
Definition at line 181 of file OpenACCClause.h.
Referenced by children().
children() [2/2]
const_child_range clang::OpenACCClauseWithIntExprs::children () const inline
Definition at line 186 of file OpenACCClause.h.
References children().
getIntExprs()
llvm::ArrayRef<Expr *> clang::OpenACCClauseWithIntExprs::getIntExprs () const inline protected
Gets the entire list of integer expressions, but leave it to the individual clauses to expose this how they'd like.
Definition at line 178 of file OpenACCClause.h.
Referenced by clang::OpenACCClauseWithSingleIntExpr::getIntExpr(), clang::OpenACCNumGangsClause::getIntExprs(), and clang::OpenACCClauseWithSingleIntExpr::hasIntExpr().
setIntExprs()
void clang::OpenACCClauseWithIntExprs::setIntExprs (MutableArrayRef< Expr * > NewIntExprs) inline protected
Used only for initialization, the leaf class can initialize this to trailing storage.
Definition at line 171 of file OpenACCClause.h.
Referenced by clang::OpenACCClauseWithSingleIntExpr::OpenACCClauseWithSingleIntExpr().
The documentation for this class was generated from the following file:
include/clang/AST/OpenACCClause.h