clang: clang::serialization::DeclOffset Class Reference
clang::serialization::DeclOffset Class Reference
Source location and bit offset of a declaration.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
DeclOffset ()=default
DeclOffset (RawLocEncoding RawLoc, uint64_t BitOffset, uint64_t DeclTypesBlockStartOffset)
void setRawLoc (RawLocEncoding Loc)
RawLocEncoding getRawLoc () const
void setBitOffset (uint64_t Offset, const uint64_t DeclTypesBlockStartOffset)
uint64_t getBitOffset (const uint64_t DeclTypesBlockStartOffset) const
Detailed Description
Source location and bit offset of a declaration.
Keep structure alignment 32-bit since the blob is assumed as 32-bit aligned.
Definition at line 252 of file ASTBitCodes.h.
Constructor & Destructor Documentation
DeclOffset() [1/2]
clang::serialization::DeclOffset::DeclOffset () default
DeclOffset() [2/2]
clang::serialization::DeclOffset::DeclOffset (RawLocEncoding RawLoc, uint64_t BitOffset, uint64_t DeclTypesBlockStartOffset) inline
Definition at line 263 of file ASTBitCodes.h.
References setBitOffset().
Member Function Documentation
getBitOffset()
uint64_t clang::serialization::DeclOffset::getBitOffset (const uint64_t DeclTypesBlockStartOffset) const inline
Definition at line 277 of file ASTBitCodes.h.
References clang::serialization::UnalignedUInt64::get().
getRawLoc()
RawLocEncoding clang::serialization::DeclOffset::getRawLoc () const inline
Definition at line 271 of file ASTBitCodes.h.
References clang::serialization::UnalignedUInt64::get().
setBitOffset()
void clang::serialization::DeclOffset::setBitOffset (uint64_t Offset, const uint64_t DeclTypesBlockStartOffset) inline
Definition at line 273 of file ASTBitCodes.h.
References Offset, and clang::serialization::UnalignedUInt64::set().
Referenced by DeclOffset().
setRawLoc()
void clang::serialization::DeclOffset::setRawLoc (RawLocEncoding Loc) inline
Definition at line 269 of file ASTBitCodes.h.
References Loc.
The documentation for this class was generated from the following file:
include/clang/Serialization/ASTBitCodes.h