clang: clang::CFG Class Reference
clang::CFG Class Reference
Represents a source-level, intra-procedural CFG that represents the control-flow of a Stmt.
#include "clang/Analysis/CFG.h"
Classes
class BuildOptions
Public Types
using CFGBlockListTy = BumpVector< CFGBlock * >
using iterator = CFGBlockListTy::iterator
using const_iterator = CFGBlockListTy::const_iterator
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using try_block_iterator = std::vector< const CFGBlock * >::const_iterator
using try_block_range = llvm::iterator_range< try_block_iterator >
using synthetic_stmt_iterator = llvm::DenseMap< const DeclStmt *, const DeclStmt * >::const_iterator
using synthetic_stmt_range = llvm::iterator_range< synthetic_stmt_iterator >
Public Member Functions
CFGBlock * createBlock ()
Create a new block in the CFG.
void setEntry (CFGBlock *B)
Set the entry block of the CFG.
void setIndirectGotoBlock (CFGBlock *B)
Set the block used for indirect goto jumps.
CFGBlock & front ()
CFGBlock & back ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator nodes_begin ()
iterator nodes_end ()
llvm::iterator_range< iterator > nodes ()
llvm::iterator_range< const_iterator > const_nodes () const
const_iterator nodes_begin () const
const_iterator nodes_end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
llvm::iterator_range< reverse_iterator > reverse_nodes ()
llvm::iterator_range< const_reverse_iterator > const_reverse_nodes () const
CFGBlock & getEntry ()
const CFGBlock & getEntry () const
CFGBlock & getExit ()
const CFGBlock & getExit () const
CFGBlock * getIndirectGotoBlock ()
const CFGBlock * getIndirectGotoBlock () const
try_block_iterator try_blocks_begin () const
try_block_iterator try_blocks_end () const
try_block_range try_blocks () const
void addTryDispatchBlock (const CFGBlock *block)
void addSyntheticDeclStmt (const DeclStmt *Synthetic, const DeclStmt *Source)
Records a synthetic DeclStmt and the DeclStmt it was constructed from.
synthetic_stmt_iterator synthetic_stmt_begin () const
Iterates over synthetic DeclStmts in the CFG.
synthetic_stmt_iterator synthetic_stmt_end () const
synthetic_stmt_range synthetic_stmts () const
template<typename Callback >
void VisitBlockStmts (Callback &O) const
unsigned getNumBlockIDs () const
Returns the total number of BlockIDs allocated (which start at 0).
unsigned size () const
Return the total number of CFGBlocks within the CFG This is simply a renaming of the getNumBlockIDs().
bool isLinear () const
Returns true if the CFG has no branches.
void viewCFG (const LangOptions &LO) const
void print (raw_ostream &OS, const LangOptions &LO, bool ShowColors) const
print - A simple pretty printer of a CFG that outputs to an ostream.
void dump (const LangOptions &LO, bool ShowColors) const
dump - A simple pretty printer of a CFG that outputs to stderr.
CFG ()
llvm::BumpPtrAllocator & getAllocator ()
BumpVectorContext & getBumpVectorContext ()
Static Public Member Functions
static std::unique_ptr< CFG > buildCFG (const Decl *D, Stmt *AST, ASTContext *C, const BuildOptions &BO)
Builds a CFG from an AST.
Detailed Description
Represents a source-level, intra-procedural CFG that represents the control-flow of a Stmt.
The Stmt can represent an entire function body, or a single expression. A CFG will always contain one empty block that represents the Exit point of the CFG. A CFG will also contain a designated Entry block. The CFG solely represents control-flow; it consists of CFGBlocks which are simply containers of Stmt*'s in the AST the CFG was constructed from.
Definition at line 1225 of file CFG.h.
Member Typedef Documentation
CFGBlockListTy
using clang::CFG::CFGBlockListTy = BumpVector<CFGBlock *>
Definition at line 1294 of file CFG.h.
const_iterator
using clang::CFG::const_iterator = CFGBlockListTy::const_iterator
Definition at line 1296 of file CFG.h.
const_reverse_iterator
using clang::CFG::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 1298 of file CFG.h.
iterator
using clang::CFG::iterator = CFGBlockListTy::iterator
Definition at line 1295 of file CFG.h.
reverse_iterator
using clang::CFG::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 1297 of file CFG.h.
synthetic_stmt_iterator
using clang::CFG::synthetic_stmt_iterator = llvm::DenseMap<const DeclStmt *, const DeclStmt *>::const_iterator
Definition at line 1371 of file CFG.h.
synthetic_stmt_range
using clang::CFG::synthetic_stmt_range = llvm::iterator_range<synthetic_stmt_iterator>
Definition at line 1372 of file CFG.h.
try_block_iterator
using clang::CFG::try_block_iterator = std::vector<const CFGBlock *>::const_iterator
Definition at line 1339 of file CFG.h.
try_block_range
using clang::CFG::try_block_range = llvm::iterator_range<try_block_iterator>
Definition at line 1340 of file CFG.h.
Constructor & Destructor Documentation
CFG()
clang::CFG::CFG () inline
Definition at line 1436 of file CFG.h.
Member Function Documentation
addSyntheticDeclStmt()
void clang::CFG::addSyntheticDeclStmt (const DeclStmt * Synthetic, const DeclStmt * Source) inline
Records a synthetic DeclStmt and the DeclStmt it was constructed from.
The CFG uses synthetic DeclStmts when a single AST DeclStmt contains multiple decls.
Definition at line 1362 of file CFG.h.
References clang::DeclStmt::isSingleDecl().
addTryDispatchBlock()
void clang::CFG::addTryDispatchBlock (const CFGBlock * block) inline
Definition at line 1354 of file CFG.h.
back()
CFGBlock& clang::CFG::back () inline
Definition at line 1301 of file CFG.h.
References clang::BumpVector< T >::back().
Referenced by createBlock().
begin() [1/2]
iterator clang::CFG::begin () inline
Definition at line 1303 of file CFG.h.
References clang::BumpVector< T >::begin().
Referenced by const_nodes(), createBlock(), clang::CFGDominatorTreeImpl< true >::dump(), clang::CFGBlock::getIndexInCFG(), nodes(), and clang::LiveVariables::runOnAllBlocks().
begin() [2/2]
const_iterator clang::CFG::begin () const inline
Definition at line 1305 of file CFG.h.
References clang::BumpVector< T >::begin().
buildCFG()
std::unique_ptr< CFG > CFG::buildCFG (const Decl * D, Stmt * AST, ASTContext * C, const BuildOptions & BO) static
Builds a CFG from an AST.
buildCFG - Constructs a CFG from an AST.
Definition at line 5058 of file CFG.cpp.
Referenced by clang::AnalysisDeclContext::getCFG(), and clang::AnalysisDeclContext::getUnoptimizedCFG().
const_nodes()
llvm::iterator_range<const_iterator> clang::CFG::const_nodes () const inline
Definition at line 1312 of file CFG.h.
References begin(), and end().
const_reverse_nodes()
llvm::iterator_range<const_reverse_iterator> clang::CFG::const_reverse_nodes () const inline
Definition at line 1327 of file CFG.h.
References rbegin(), and rend().
createBlock()
CFGBlock * CFG::createBlock ()
Create a new block in the CFG.
createBlock - Constructs and adds a new CFGBlock to the CFG.
The CFG owns the block; the caller should not directly free it.
The block has no successors or predecessors. If this is the first block created in the CFG, it is automatically set to be the Entry and Exit of the CFG.
Definition at line 5041 of file CFG.cpp.
References back(), begin(), end(), getAllocator(), and clang::BumpVector< T >::push_back().
dump()
void CFG::dump (const LangOptions & LO, bool ShowColors) const
dump - A simple pretty printer of a CFG that outputs to stderr.
Definition at line 5903 of file CFG.cpp.
References clang::CFGBlock::print().
Referenced by clang::AnalysisDeclContext::dumpCFG().
end() [1/2]
iterator clang::CFG::end () inline
Definition at line 1304 of file CFG.h.
References clang::BumpVector< T >::end().
Referenced by const_nodes(), createBlock(), clang::CFGDominatorTreeImpl< true >::dump(), nodes(), and clang::LiveVariables::runOnAllBlocks().
end() [2/2]
const_iterator clang::CFG::end () const inline
Definition at line 1306 of file CFG.h.
References clang::BumpVector< T >::end().
front()
CFGBlock& clang::CFG::front () inline
Definition at line 1300 of file CFG.h.
References clang::BumpVector< T >::front().
getAllocator()
llvm::BumpPtrAllocator& clang::CFG::getAllocator () inline
Definition at line 1438 of file CFG.h.
References clang::BumpVectorContext::getAllocator().
Referenced by createBlock().
getBumpVectorContext()
BumpVectorContext& clang::CFG::getBumpVectorContext () inline
Definition at line 1442 of file CFG.h.
getEntry() [1/2]
CFGBlock& clang::CFG::getEntry () inline
Definition at line 1331 of file CFG.h.
Referenced by annotateStartParameter(), CheckFallThrough(), checkForRecursiveFunctionCall(), clang::ento::CoreEngine::ExecuteWorkList(), clang::reachable_code::FindUnreachableCode(), clang::CallEnter::getEntry(), llvm::GraphTraits< ::clang::CFG * >::getEntryNode(), clang::sema::AnalysisBasedWarnings::IssueWarnings(), print_block(), clang::dataflow::runTypeErasedDataflowAnalysis(), clang::runUninitializedVariablesAnalysis(), visitReachableThrows(), and clang::threadSafety::CFGWalker::walk().
getEntry() [2/2]
const CFGBlock& clang::CFG::getEntry () const inline
Definition at line 1332 of file CFG.h.
getExit() [1/2]
CFGBlock& clang::CFG::getExit () inline
Definition at line 1333 of file CFG.h.
Referenced by checkForRecursiveFunctionCall(), clang::FunctionExitPoint::getBlock(), llvm::GraphTraits< Inverse< ::clang::CFG * > >::getEntryNode(), clang::CFGBlock::isInevitablySinking(), print_block(), clang::consumed::ConsumedAnalyzer::run(), and clang::threadSafety::CFGWalker::walk().
getExit() [2/2]
const CFGBlock& clang::CFG::getExit () const inline
Definition at line 1334 of file CFG.h.
getIndirectGotoBlock() [1/2]
CFGBlock* clang::CFG::getIndirectGotoBlock () inline
Definition at line 1336 of file CFG.h.
Referenced by print_block().
getIndirectGotoBlock() [2/2]
const CFGBlock* clang::CFG::getIndirectGotoBlock () const inline
Definition at line 1337 of file CFG.h.
getNumBlockIDs()
unsigned clang::CFG::getNumBlockIDs () const inline
Returns the total number of BlockIDs allocated (which start at 0).
Definition at line 1411 of file CFG.h.
Referenced by CheckFallThrough(), clang::LiveVariables::computeLiveness(), clang::ento::CoreEngine::ExecuteWorkList(), clang::reachable_code::FindUnreachableCode(), clang::PostOrderCFGView::PostOrderCFGView(), clang::consumed::ConsumedAnalyzer::run(), clang::runUninitializedVariablesAnalysis(), and visitReachableThrows().
isLinear()
bool CFG::isLinear () const
Returns true if the CFG has no branches.
Usually it boils down to the CFG having exactly three blocks (entry, the actual code, exit), but sometimes more blocks appear due to having control flow that can be fully resolved in compile time.
Definition at line 5064 of file CFG.cpp.
References size(), and clang::CFGBlock::succs().
Referenced by clang::ento::NoStateChangeFuncVisitor::VisitNode().
nodes()
llvm::iterator_range<iterator> clang::CFG::nodes () inline
Definition at line 1311 of file CFG.h.
References begin(), and end().
Referenced by clang::LiveVariables::computeLiveness().
nodes_begin() [1/2]
iterator clang::CFG::nodes_begin () inline
Definition at line 1308 of file CFG.h.
References clang::BumpVector< T >::begin().
Referenced by llvm::GraphTraits< ::clang::CFG * >::nodes_begin(), and llvm::GraphTraits< Inverse< ::clang::CFG * > >::nodes_begin().
nodes_begin() [2/2]
const_iterator clang::CFG::nodes_begin () const inline
Definition at line 1316 of file CFG.h.
References clang::BumpVector< T >::begin().
nodes_end() [1/2]
iterator clang::CFG::nodes_end () inline
Definition at line 1309 of file CFG.h.
References clang::BumpVector< T >::end().
Referenced by llvm::GraphTraits< ::clang::CFG * >::nodes_end(), and llvm::GraphTraits< Inverse< ::clang::CFG * > >::nodes_end().
nodes_end() [2/2]
const_iterator clang::CFG::nodes_end () const inline
Definition at line 1317 of file CFG.h.
References clang::BumpVector< T >::end().
print()
void CFG::print (raw_ostream & OS, const LangOptions & LO, bool ShowColors) const
print - A simple pretty printer of a CFG that outputs to an ostream.
Definition at line 5908 of file CFG.cpp.
References print_block().
rbegin() [1/2]
reverse_iterator clang::CFG::rbegin () inline
Definition at line 1319 of file CFG.h.
References clang::BumpVector< T >::rbegin().
Referenced by const_reverse_nodes(), and reverse_nodes().
rbegin() [2/2]
const_reverse_iterator clang::CFG::rbegin () const inline
Definition at line 1321 of file CFG.h.
References clang::BumpVector< T >::rbegin().
rend() [1/2]
reverse_iterator clang::CFG::rend () inline
Definition at line 1320 of file CFG.h.
References clang::BumpVector< T >::rend().
Referenced by const_reverse_nodes(), and reverse_nodes().
rend() [2/2]
const_reverse_iterator clang::CFG::rend () const inline
Definition at line 1322 of file CFG.h.
References clang::BumpVector< T >::rend().
reverse_nodes()
llvm::iterator_range<reverse_iterator> clang::CFG::reverse_nodes () inline
Definition at line 1324 of file CFG.h.
References rbegin(), and rend().
setEntry()
void clang::CFG::setEntry (CFGBlock * B) inline
Set the entry block of the CFG.
This is typically used only during CFG construction. Most CFG clients expect that the entry block has no predecessors and contains no statements.
Definition at line 1284 of file CFG.h.
setIndirectGotoBlock()
void clang::CFG::setIndirectGotoBlock (CFGBlock * B) inline
Set the block used for indirect goto jumps.
This is typically used only during CFG construction.
Definition at line 1288 of file CFG.h.
size()
unsigned clang::CFG::size () const inline
Return the total number of CFGBlocks within the CFG This is simply a renaming of the getNumBlockIDs().
This is necessary because the dominator implementation needs such an interface.
Definition at line 1416 of file CFG.h.
Referenced by isLinear(), clang::dataflow::runTypeErasedDataflowAnalysis(), and llvm::GraphTraits< ::clang::CFG * >::size().
synthetic_stmt_begin()
synthetic_stmt_iterator clang::CFG::synthetic_stmt_begin () const inline
Iterates over synthetic DeclStmts in the CFG.
Each element is a (synthetic statement, source statement) pair.
See also
addSyntheticDeclStmt
Definition at line 1379 of file CFG.h.
Referenced by addParentsForSyntheticStmts(), and synthetic_stmts().
synthetic_stmt_end()
synthetic_stmt_iterator clang::CFG::synthetic_stmt_end () const inline
See also
synthetic_stmt_begin
Definition at line 1384 of file CFG.h.
Referenced by addParentsForSyntheticStmts(), and synthetic_stmts().
synthetic_stmts()
synthetic_stmt_range clang::CFG::synthetic_stmts () const inline
See also
synthetic_stmt_begin
Definition at line 1389 of file CFG.h.
References synthetic_stmt_begin(), and synthetic_stmt_end().
try_blocks()
try_block_range clang::CFG::try_blocks () const inline
Definition at line 1350 of file CFG.h.
References try_blocks_begin(), and try_blocks_end().
Referenced by clang::reachable_code::FindUnreachableCode().
try_blocks_begin()
try_block_iterator clang::CFG::try_blocks_begin () const inline
Definition at line 1342 of file CFG.h.
Referenced by try_blocks().
try_blocks_end()
try_block_iterator clang::CFG::try_blocks_end () const inline
Definition at line 1346 of file CFG.h.
Referenced by try_blocks().
viewCFG()
void CFG::viewCFG (const LangOptions & LO) const
Definition at line 6136 of file CFG.cpp.
References GraphHelper.
VisitBlockStmts()
template<typename Callback > void clang::CFG::VisitBlockStmts (Callback & O) const inline
Definition at line 1397 of file CFG.h.
Referenced by clang::runUninitializedVariablesAnalysis().
The documentation for this class was generated from the following files:
include/clang/Analysis/CFG.h
lib/Analysis/CFG.cpp