clang: clang::driver::toolchains::BareMetal Class Reference
clang::driver::toolchains::BareMetal Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/BareMetal.h"
Public Member Functions
BareMetal (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
~BareMetal () override=default
void findMultilibs (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
bool useIntegratedAs () const override
Check if the toolchain should use the integrated assembler.
bool isBareMetal () const override
isBareMetal - Is this a bare metal target.
bool isCrossCompiling () const override
Returns true if the toolchain is targeting a non-native architecture.
bool HasNativeLLVMSupport () const override
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
bool isPICDefault () const override
Test whether this toolchain defaults to PIC.
bool isPIEDefault (const llvm::opt::ArgList &Args) const override
Test whether this toolchain defaults to PIE.
bool isPICDefaultForced () const override
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
bool SupportsProfiling () const override
SupportsProfiling - Does this tool chain support -pg.
StringRef getOSLibName () const override
RuntimeLibType GetDefaultRuntimeLibType () const override
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
CXXStdlibType GetDefaultCXXStdlibType () const override
const char * getDefaultLinker () const override
GetDefaultLinker - Get the default linker to use.
void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add the clang cc1 arguments for system include paths.
void addClangTargetOptions (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, Action::OffloadKind DeviceOffloadKind) const override
Add options that need to be passed to cc1 for this target.
void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
void AddCXXStdlibLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
void AddLinkRuntimeLib (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
std::string computeSysRoot () const override
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
SanitizerMask getSupportedSanitizers () const override
Return sanitizers which are available in this toolchain.
Public Member Functions inherited from clang::driver::ToolChain
virtual ~ToolChain ()
const Driver & getDriver () const
llvm::vfs::FileSystem & getVFS () const
const llvm::Triple & getTriple () const
virtual const llvm::Triple * getAuxTriple () const
Get the toolchain's aux triple, if it has one.
virtual std::string getInputFilename (const InputInfo &Input) const
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
llvm::Triple::ArchType getArch () const
StringRef getArchName () const
StringRef getPlatform () const
StringRef getOS () const
StringRef getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
std::string getTripleString () const
const llvm::Triple & getEffectiveTriple () const
Get the toolchain's effective clang triple.
bool hasEffectiveTriple () const
path_list & getLibraryPaths ()
const path_list & getLibraryPaths () const
path_list & getFilePaths ()
const path_list & getFilePaths () const
path_list & getProgramPaths ()
const path_list & getProgramPaths () const
const MultilibSet & getMultilibs () const
const llvm::SmallVector< Multilib > & getSelectedMultilibs () const
Multilib::flags_list getMultilibFlags (const llvm::opt::ArgList &) const
Get flags suitable for multilib selection, based on the provided clang command line arguments.
SanitizerArgs getSanitizerArgs (const llvm::opt::ArgList &JobArgs) const
const XRayArgs & getXRayArgs () const
const llvm::opt::Arg * getRTTIArg () const
RTTIMode getRTTIMode () const
ExceptionsMode getExceptionsMode () const
virtual llvm::opt::DerivedArgList * TranslateArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
virtual llvm::opt::DerivedArgList * TranslateOffloadTargetArgs (const llvm::opt::DerivedArgList &Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > &AllocatedArgs, Action::OffloadKind DeviceOffloadKind) const
TranslateOffloadTargetArgs - Create a new derived argument list for that contains the Offload target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val Also handles -Xsycl-target OR -Xsycl-target=<triple>
virtual void TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, llvm::opt::Arg *&A, llvm::opt::DerivedArgList *DAL, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs=nullptr) const
Append the argument following A to DAL assuming A is an Xarch argument.
virtual llvm::opt::DerivedArgList * TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs) const
Translate -Xarch_ arguments.
virtual Tool * SelectTool (const JobAction &JA) const
Choose a tool to use to handle the action JA.
std::string GetFilePath (const char *Name) const
std::string GetProgramPath (const char *Name) const
std::string GetLinkerPath (bool *LinkerIsLLD=nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
std::string GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
virtual void printVerboseInfo (raw_ostream &OS) const
Dispatch to the specific toolchain for verbose printing.
virtual types::ID LookupTypeForExtension (StringRef Ext) const
LookupTypeForExtension - Return the default language type to use for the given extension.
virtual bool IsBlocksDefault () const
IsBlocksDefault - Does this tool chain enable -fblocks by default.
virtual bool IsIntegratedAssemblerDefault () const
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
virtual bool IsIntegratedBackendDefault () const
IsIntegratedBackendDefault - Does this tool chain enable -fintegrated-objemitter by default.
virtual bool IsIntegratedBackendSupported () const
IsIntegratedBackendSupported - Does this tool chain support -fintegrated-objemitter.
virtual bool IsNonIntegratedBackendSupported () const
IsNonIntegratedBackendSupported - Does this tool chain support -fno-integrated-objemitter.
virtual bool useIntegratedBackend () const
Check if the toolchain should use the integrated backend.
virtual bool parseInlineAsmUsingAsmParser () const
Check if the toolchain should use AsmParser to parse inlineAsm when integrated assembler is not default.
virtual bool IsMathErrnoDefault () const
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
virtual bool IsEncodeExtendedBlockSignatureDefault () const
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
virtual bool IsObjCNonFragileABIDefault () const
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
virtual bool UseObjCMixedDispatch () const
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
virtual bool useRelaxRelocations () const
Check whether to enable x86 relax relocations by default.
bool defaultToIEEELongDouble () const
Check whether use IEEE binary128 as long double format by default.
virtual LangOptions::StackProtectorMode GetDefaultStackProtectorLevel (bool KernelOrKext) const
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
virtual LangOptions::TrivialAutoVarInitKind GetDefaultTrivialAutoVarInit () const
Get the default trivial automatic variable initialization.
virtual UnwindLibType GetDefaultUnwindLibType () const
virtual std::string getCompilerRTPath () const
virtual std::string getCompilerRT (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
const char * getCompilerRTArgString (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::string getCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::optional< std::string > getRuntimePath () const
std::optional< std::string > getStdlibPath () const
virtual path_list getArchSpecificLibPaths () const
virtual UnwindTableLevel getDefaultUnwindTableLevel (const llvm::opt::ArgList &Args) const
How detailed should the unwind tables be by default.
virtual bool IsAArch64OutlineAtomicsDefault (const llvm::opt::ArgList &Args) const
Test whether this toolchain supports outline atomics by default.
virtual void CheckObjCARC () const
Complain if this tool chain doesn't support Objective-C ARC.
virtual llvm::codegenoptions::DebugInfoFormat getDefaultDebugFormat () const
Get the default debug info format. Typically, this is DWARF.
virtual bool UseDwarfDebugFlags () const
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
virtual std::string GetGlobalDebugPathRemapping () const
Add an additional -fdebug-prefix-map entry.
virtual unsigned GetDefaultDwarfVersion () const
virtual unsigned getMaxDwarfVersion () const
virtual bool GetDefaultStandaloneDebug () const
virtual llvm::DebuggerKind getDefaultDebuggerTuning () const
virtual bool supportsDebugInfoOption (const llvm::opt::Arg *) const
Does this toolchain supports given debug info option or not.
virtual void adjustDebugInfoKind (llvm::codegenoptions::DebugInfoKind &DebugInfoKind, const llvm::opt::ArgList &Args) const
Adjust debug information kind considering all passed options.
virtual llvm::ExceptionHandling GetExceptionModel (const llvm::opt::ArgList &Args) const
GetExceptionModel - Return the tool chain exception model.
virtual bool SupportsEmbeddedBitcode () const
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
virtual std::string getThreadModel () const
getThreadModel() - Which thread model does this target use?
virtual bool isThreadModelSupported (const StringRef Model) const
isThreadModelSupported() - Does this target support a thread model?
virtual std::string getMultiarchTriple (const Driver &D, const llvm::Triple &TargetTriple, StringRef SysRoot) const
virtual std::string ComputeLLVMTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
virtual std::string ComputeEffectiveClangTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
virtual ObjCRuntime getDefaultObjCRuntime (bool isNonFragile) const
getDefaultObjCRuntime - Return the default Objective-C runtime for this platform.
virtual bool hasBlocksRuntime () const
hasBlocksRuntime - Given that the user is compiling with -fblocks, does this tool chain guarantee the existence of a blocks runtime?
virtual void addClangCC1ASTargetOptions (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CC1ASArgs) const
Add options that need to be passed to cc1as for this target.
virtual void addClangWarningOptions (llvm::opt::ArgStringList &CC1Args) const
Add warning options that need to be passed to cc1 for this target.
virtual RuntimeLibType GetRuntimeLibType (const llvm::opt::ArgList &Args) const
virtual CXXStdlibType GetCXXStdlibType (const llvm::opt::ArgList &Args) const
virtual UnwindLibType GetUnwindLibType (const llvm::opt::ArgList &Args) const
virtual std::string detectLibcxxVersion (StringRef IncludePath) const
void AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
bool ShouldLinkCXXStdlib (const llvm::opt::ArgList &Args) const
Returns if the C++ standard library should be linked in.
void AddFilePathLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
virtual void AddCCKextLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
virtual bool isFastMathRuntimeAvailable (const llvm::opt::ArgList &Args, std::string &Path) const
If a runtime library exists that sets global flags for unsafe floating point math, return true.
bool addFastMathRuntimeIfAvailable (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
virtual Expected< SmallVector< std::string > > getSystemGPUArchs (const llvm::opt::ArgList &Args) const
getSystemGPUArchs - Use a tool to detect the user's availible GPUs.
virtual void addProfileRTLibs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
addProfileRTLibs - When -fprofile-instr-profile is specified, try to pass a suitable profile runtime library to the linker.
virtual void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific CUDA includes.
virtual void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific HIP includes.
virtual void AddIAMCUIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use MCU GCC toolchain includes.
virtual VersionTuple computeMSVCVersion (const Driver *D, const llvm::opt::ArgList &Args) const
On Windows, returns the MSVC compatibility version.
virtual llvm::SmallVector< BitCodeLibraryInfo, 12 > getDeviceLibs (const llvm::opt::ArgList &Args, const Action::OffloadKind DeviceOffloadingKind) const
Get paths for device libraries.
virtual void AddHIPRuntimeLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
Add the system specific linker arguments to use for the given HIP runtime library type.
virtual SanitizerMask getDefaultSanitizers () const
Return sanitizers which are enabled by default.
virtual bool canSplitThinLTOUnit () const
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
virtual llvm::DenormalMode getDefaultDenormalModeForType (const llvm::opt::ArgList &DriverArgs, const JobAction &JA, const llvm::fltSemantics *FPType=nullptr) const
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
Static Public Member Functions
static bool handlesTarget (const llvm::Triple &Triple)
Static Public Member Functions inherited from clang::driver::ToolChain
static ParsedClangName getTargetAndModeFromProgramName (StringRef ProgName)
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
static bool needsProfileRT (const llvm::opt::ArgList &Args)
needsProfileRT - returns true if instrumentation profile is on.
static bool needsGCovInstrumentation (const llvm::opt::ArgList &Args)
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
static llvm::Triple getOpenMPTriple (StringRef TripleStr)
Protected Member Functions
Tool * buildLinker () const override
Tool * buildStaticLibTool () const override
Protected Member Functions inherited from clang::driver::ToolChain
ToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > executeToolChainProgram (StringRef Executable) const
Executes the given Executable and returns the stdout.
void setTripleEnvironment (llvm::Triple::EnvironmentType Env)
virtual Tool * buildAssembler () const
virtual Tool * buildBackendCompiler () const
virtual Tool * getTool (Action::ActionClass AC) const
virtual std::string buildCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type, bool AddArch) const
std::optional< std::string > getTargetSubDirPath (StringRef BaseDir) const
Find the target-specific subdirectory for the current target triple under BaseDir, doing fallback triple searches as necessary.
Additional Inherited Members
Public Types inherited from clang::driver::ToolChain
enum CXXStdlibType { CST_Libcxx , CST_Libstdcxx }
enum RuntimeLibType { RLT_CompilerRT , RLT_Libgcc }
enum UnwindLibType { UNW_None , UNW_CompilerRT , UNW_Libgcc }
enum class UnwindTableLevel { None , Synchronous , Asynchronous }
enum RTTIMode { RM_Enabled , RM_Disabled }
enum ExceptionsMode { EM_Enabled , EM_Disabled }
enum FileType { FT_Object , FT_Static , FT_Shared }
using path_list = SmallVector< std::string, 16 >
Static Protected Member Functions inherited from clang::driver::ToolChain
static void addSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory to CC1 arguments.
static void addExternCSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
static void addExternCSystemIncludeIfExists (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
static void addSystemIncludes (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, ArrayRef< StringRef > Paths)
Utility function to add a list of system include directories to CC1.
static std::string concat (StringRef Path, const Twine &A, const Twine &B="", const Twine &C="", const Twine &D="")
Protected Attributes inherited from clang::driver::ToolChain
MultilibSet Multilibs
llvm::SmallVector< Multilib > SelectedMultilibs
Detailed Description
Definition at line 22 of file BareMetal.h.
Constructor & Destructor Documentation
BareMetal()
BareMetal::BareMetal (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args)
Definition at line 100 of file BareMetal.cpp.
References computeSysRoot(), findMultilibs(), clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getFilePaths(), clang::driver::ToolChain::getLibraryPaths(), and clang::driver::ToolChain::getProgramPaths().
~BareMetal()
clang::driver::toolchains::BareMetal::~BareMetal () override default
Member Function Documentation
AddClangCXXStdlibIncludeArgs()
void BareMetal::AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
Reimplemented from clang::driver::ToolChain.
Definition at line 292 of file BareMetal.cpp.
References clang::driver::ToolChain::addSystemInclude(), computeSysRoot(), clang::driver::ToolChain::CST_Libcxx, clang::driver::ToolChain::CST_Libstdcxx, clang::driver::ToolChain::GetCXXStdlibType(), clang::driver::ToolChain::getDriver(), clang::driver::Driver::getVFS(), clang::interp::LE(), clang::driver::toolchains::Generic_GCC::GCCVersion::Major, clang::driver::toolchains::Generic_GCC::GCCVersion::Parse(), and clang::driver::toolchains::Generic_GCC::GCCVersion::Text.
AddClangSystemIncludeArgs()
void BareMetal::AddClangSystemIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add the clang cc1 arguments for system include paths.
This routine is responsible for adding the necessary cc1 arguments to include headers from standard system header directories.
Reimplemented from clang::driver::ToolChain.
Definition at line 262 of file BareMetal.cpp.
References clang::driver::ToolChain::addSystemInclude(), computeSysRoot(), and clang::driver::ToolChain::getDriver().
addClangTargetOptions()
void BareMetal::addClangTargetOptions (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, Action::OffloadKind DeviceOffloadKind) const override virtual
Add options that need to be passed to cc1 for this target.
Reimplemented from clang::driver::ToolChain.
Definition at line 286 of file BareMetal.cpp.
AddCXXStdlibLibArgs()
void BareMetal::AddCXXStdlibLibArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const override virtual
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
Reimplemented from clang::driver::ToolChain.
Definition at line 347 of file BareMetal.cpp.
References clang::driver::ToolChain::CST_Libcxx, clang::driver::ToolChain::CST_Libstdcxx, and clang::driver::ToolChain::GetCXXStdlibType().
AddLinkRuntimeLib()
void BareMetal::AddLinkRuntimeLib (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const
Definition at line 364 of file BareMetal.cpp.
References clang::driver::ToolChain::getCompilerRTArgString(), clang::driver::ToolChain::GetRuntimeLibType(), clang::driver::ToolChain::RLT_CompilerRT, and clang::driver::ToolChain::RLT_Libgcc.
buildLinker()
Tool * BareMetal::buildLinker () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 240 of file BareMetal.cpp.
buildStaticLibTool()
Tool * BareMetal::buildStaticLibTool () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 244 of file BareMetal.cpp.
computeSysRoot()
std::string BareMetal::computeSysRoot () const override virtual
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
Reimplemented from clang::driver::ToolChain.
Definition at line 248 of file BareMetal.cpp.
References computeBaseSysRoot(), clang::driver::ToolChain::getDriver(), and clang::driver::ToolChain::getTriple().
Referenced by AddClangCXXStdlibIncludeArgs(), AddClangSystemIncludeArgs(), and BareMetal().
findMultilibs()
void BareMetal::findMultilibs (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args)
Definition at line 218 of file BareMetal.cpp.
References computeBaseSysRoot(), findMultilibsFromYAML(), findRISCVMultilibs(), isRISCVBareMetal(), MultilibFilename, clang::driver::ToolChain::Multilibs, and clang::driver::ToolChain::SelectedMultilibs.
Referenced by BareMetal().
GetDefaultCXXStdlibType()
CXXStdlibType clang::driver::toolchains::BareMetal::GetDefaultCXXStdlibType () const inline override virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 54 of file BareMetal.h.
References clang::driver::ToolChain::CST_Libcxx.
getDefaultLinker()
const char* clang::driver::toolchains::BareMetal::getDefaultLinker () const inline override virtual
GetDefaultLinker - Get the default linker to use.
Reimplemented from clang::driver::ToolChain.
Definition at line 58 of file BareMetal.h.
GetDefaultRuntimeLibType()
RuntimeLibType clang::driver::toolchains::BareMetal::GetDefaultRuntimeLibType () const inline override virtual
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
Reimplemented from clang::driver::ToolChain.
Definition at line 51 of file BareMetal.h.
References clang::driver::ToolChain::RLT_CompilerRT.
getOSLibName()
StringRef clang::driver::toolchains::BareMetal::getOSLibName () const inline override virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 49 of file BareMetal.h.
getSupportedSanitizers()
SanitizerMask BareMetal::getSupportedSanitizers () const override virtual
Return sanitizers which are available in this toolchain.
Reimplemented from clang::driver::ToolChain.
Definition at line 489 of file BareMetal.cpp.
References clang::driver::ToolChain::getSupportedSanitizers(), and clang::driver::ToolChain::getTriple().
handlesTarget()
bool BareMetal::handlesTarget (const llvm::Triple & Triple) static
Definition at line 235 of file BareMetal.cpp.
References isAArch64BareMetal(), isARMBareMetal(), isPPCBareMetal(), and isRISCVBareMetal().
HasNativeLLVMSupport()
bool clang::driver::toolchains::BareMetal::HasNativeLLVMSupport () const inline override virtual
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
Reimplemented from clang::driver::ToolChain.
Definition at line 41 of file BareMetal.h.
isBareMetal()
bool clang::driver::toolchains::BareMetal::isBareMetal () const inline override virtual
isBareMetal - Is this a bare metal target.
Reimplemented from clang::driver::ToolChain.
Definition at line 39 of file BareMetal.h.
isCrossCompiling()
bool clang::driver::toolchains::BareMetal::isCrossCompiling () const inline override virtual
Returns true if the toolchain is targeting a non-native architecture.
Reimplemented from clang::driver::ToolChain.
Definition at line 40 of file BareMetal.h.
isPICDefault()
bool clang::driver::toolchains::BareMetal::isPICDefault () const inline override virtual
Test whether this toolchain defaults to PIC.
Implements clang::driver::ToolChain.
Definition at line 42 of file BareMetal.h.
isPICDefaultForced()
bool clang::driver::toolchains::BareMetal::isPICDefaultForced () const inline override virtual
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
If this returns true, any PIC related flags should be ignored and instead the results of isPICDefault() and isPIEDefault(const llvm::opt::ArgList &Args) are used exclusively.
Implements clang::driver::ToolChain.
Definition at line 46 of file BareMetal.h.
isPIEDefault()
bool clang::driver::toolchains::BareMetal::isPIEDefault (const llvm::opt::ArgList & Args) const inline override virtual
Test whether this toolchain defaults to PIE.
Implements clang::driver::ToolChain.
Definition at line 43 of file BareMetal.h.
SupportsProfiling()
bool clang::driver::toolchains::BareMetal::SupportsProfiling () const inline override virtual
SupportsProfiling - Does this tool chain support -pg.
Reimplemented from clang::driver::ToolChain.
Definition at line 47 of file BareMetal.h.
useIntegratedAs()
bool clang::driver::toolchains::BareMetal::useIntegratedAs () const inline override virtual
Check if the toolchain should use the integrated assembler.
Reimplemented from clang::driver::ToolChain.
Definition at line 38 of file BareMetal.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/BareMetal.h
lib/Driver/ToolChains/BareMetal.cpp