clang: clang::comments::Lexer Class Reference
clang::comments::Lexer Class Reference
Comment lexer.
#include "clang/AST/CommentLexer.h"
Public Member Functions
Lexer (llvm::BumpPtrAllocator &Allocator, DiagnosticsEngine &Diags, const CommandTraits &Traits, SourceLocation FileLoc, const char *BufferStart, const char *BufferEnd, bool ParseCommands=true)
void lex (Token &T)
StringRef getSpelling (const Token &Tok, const SourceManager &SourceMgr) const
Detailed Description
Comment lexer.
Definition at line 220 of file CommentLexer.h.
Constructor & Destructor Documentation
Lexer()
clang::comments::Lexer::Lexer (llvm::BumpPtrAllocator & Allocator, DiagnosticsEngine & Diags, const CommandTraits & Traits, SourceLocation FileLoc, const char * BufferStart, const char * BufferEnd, bool ParseCommands = true)
Definition at line 737 of file CommentLexer.cpp.
Member Function Documentation
getSpelling()
StringRef clang::comments::Lexer::getSpelling (const Token & Tok, const SourceManager & SourceMgr) const
Definition at line 847 of file CommentLexer.cpp.
References Begin, clang::File, clang::SourceManager::getBufferData(), clang::SourceManager::getDecomposedLoc(), clang::comments::Token::getLength(), and clang::comments::Token::getLocation().
Referenced by clang::comments::Token::dump().
lex()
void clang::comments::Lexer::lex (Token & T)
Definition at line 745 of file CommentLexer.cpp.
References clang::comments::tok::eof, and clang::comments::tok::newline.
The documentation for this class was generated from the following files:
include/clang/AST/CommentLexer.h
lib/AST/CommentLexer.cpp