clang: clang::CodeGen::AddressImpl< T, true > Class Template Reference
clang::CodeGen::AddressImpl< T, true > Class Template Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/Address.h"
Public Member Functions
AddressImpl (llvm::Value *Pointer, llvm::Type *ElementType, CharUnits Alignment)
llvm::Value * getPointer () const
llvm::Type * getElementType () const
CharUnits getAlignment () const
Detailed Description
template<typename T>
class clang::CodeGen::AddressImpl< T, true >
Definition at line 44 of file Address.h.
Constructor & Destructor Documentation
AddressImpl()
template<typename T > clang::CodeGen::AddressImpl< T, true >::AddressImpl (llvm::Value * Pointer, llvm::Type * ElementType, CharUnits Alignment) inline
Definition at line 51 of file Address.h.
References clang::CharUnits::getQuantity(), clang::CharUnits::isPowerOfTwo(), and clang::CharUnits::isZero().
Member Function Documentation
getAlignment()
template<typename T > CharUnits clang::CodeGen::AddressImpl< T, true >::getAlignment () const inline
Definition at line 67 of file Address.h.
References clang::CharUnits::fromQuantity().
getElementType()
template<typename T > llvm::Type* clang::CodeGen::AddressImpl< T, true >::getElementType () const inline
Definition at line 66 of file Address.h.
getPointer()
template<typename T > llvm::Value* clang::CodeGen::AddressImpl< T, true >::getPointer () const inline
Definition at line 65 of file Address.h.
The documentation for this class was generated from the following file:
lib/CodeGen/Address.h