clang: clang::threadSafety::til::UnaryOp Class Reference
clang::threadSafety::til::UnaryOp Class Reference
Simple arithmetic unary operations, e.g.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
UnaryOp (TIL_UnaryOpcode Op, SExpr *E)
UnaryOp (const UnaryOp &U, SExpr *E)
TIL_UnaryOpcode unaryOpcode () const
SExpr * expr ()
const SExpr * expr () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const UnaryOp *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const unsigned char Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Simple arithmetic unary operations, e.g.
negate and not. These operations have no side-effects.
Definition at line 1166 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
UnaryOp() [1/2]
clang::threadSafety::til::UnaryOp::UnaryOp (TIL_UnaryOpcode Op, SExpr * E) inline
Definition at line 1168 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
UnaryOp() [2/2]
clang::threadSafety::til::UnaryOp::UnaryOp (const UnaryOp & U, SExpr * E) inline
Definition at line 1172 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Member Function Documentation
classof()
static bool clang::threadSafety::til::UnaryOp::classof (const SExpr * E) inline static
Definition at line 1174 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::UnaryOp::compare (const UnaryOp * E, C & Cmp) const inline
Definition at line 1190 of file ThreadSafetyTIL.h.
expr() [1/2]
SExpr* clang::threadSafety::til::UnaryOp::expr () inline
Definition at line 1180 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printUnaryOp().
expr() [2/2]
const SExpr* clang::threadSafety::til::UnaryOp::expr () const inline
Definition at line 1181 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::UnaryOp::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1184 of file ThreadSafetyTIL.h.
References clang::ast_matchers::Ne.
unaryOpcode()
TIL_UnaryOpcode clang::threadSafety::til::UnaryOp::unaryOpcode () const inline
Definition at line 1176 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printUnaryOp().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h