clang: clang::ento::CompoundValData Class Reference
clang::ento::CompoundValData Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h"
Public Types
using iterator = llvm::ImmutableList< SVal >::iterator
Public Member Functions
CompoundValData (QualType t, llvm::ImmutableList< SVal > l)
iterator begin () const
iterator end () const
QualType getType () const
void Profile (llvm::FoldingSetNodeID &ID)
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, QualType T, llvm::ImmutableList< SVal > L)
Detailed Description
Definition at line 40 of file BasicValueFactory.h.
Member Typedef Documentation
iterator
using clang::ento::CompoundValData::iterator = llvm::ImmutableList<SVal>::iterator
Definition at line 49 of file BasicValueFactory.h.
Constructor & Destructor Documentation
CompoundValData()
clang::ento::CompoundValData::CompoundValData (QualType t, llvm::ImmutableList< SVal > l) inline
Definition at line 45 of file BasicValueFactory.h.
References clang::ento::NonLoc::isCompoundType(), and clang::T.
Member Function Documentation
begin()
iterator clang::ento::CompoundValData::begin () const inline
Definition at line 51 of file BasicValueFactory.h.
end()
iterator clang::ento::CompoundValData::end () const inline
Definition at line 52 of file BasicValueFactory.h.
getType()
QualType clang::ento::CompoundValData::getType () const inline
Definition at line 54 of file BasicValueFactory.h.
References clang::T.
Profile() [1/2]
void clang::ento::CompoundValData::Profile (llvm::FoldingSetNodeID & ID) inline
Definition at line 59 of file BasicValueFactory.h.
References ID, Profile(), and clang::T.
Referenced by Profile().
Profile() [2/2]
void CompoundValData::Profile (llvm::FoldingSetNodeID & ID, QualType T, llvm::ImmutableList< SVal > L) static
Definition at line 32 of file BasicValueFactory.cpp.
References ID, clang::FunctionProtoType::Profile(), and clang::T.
Referenced by clang::ento::BasicValueFactory::getCompoundValData().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h
lib/StaticAnalyzer/Core/BasicValueFactory.cpp