clang: clang::OMPClauseWithPostUpdate Class Reference
clang::OMPClauseWithPostUpdate Class Reference
Class that handles post-update expression for some clauses, like 'lastprivate', 'reduction' etc.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
const Expr * getPostUpdateExpr () const
Get post-update expression for the clause.
Expr * getPostUpdateExpr ()
Get post-update expression for the clause.
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static OMPClauseWithPostUpdate * get (OMPClause *C)
static const OMPClauseWithPostUpdate * get (const OMPClause *C)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Protected Member Functions
OMPClauseWithPostUpdate (const OMPClause *This)
void setPostUpdateExpr (Expr *S)
Set pre-initialization statement for the clause.
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Friends
class OMPClauseReader
Detailed Description
Class that handles post-update expression for some clauses, like 'lastprivate', 'reduction' etc.
Definition at line 233 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPClauseWithPostUpdate()
clang::OMPClauseWithPostUpdate::OMPClauseWithPostUpdate (const OMPClause * This) inline protected
Definition at line 240 of file OpenMPClause.h.
References get(), and clang::interp::This().
Member Function Documentation
get() [1/2]
const OMPClauseWithPostUpdate * OMPClauseWithPostUpdate::get (const OMPClause * C) static
Definition at line 188 of file OpenMPClause.cpp.
get() [2/2]
OMPClauseWithPostUpdate * OMPClauseWithPostUpdate::get (OMPClause * C) static
Definition at line 183 of file OpenMPClause.cpp.
Referenced by OMPClauseWithPostUpdate().
getPostUpdateExpr() [1/2]
Expr* clang::OMPClauseWithPostUpdate::getPostUpdateExpr () inline
Get post-update expression for the clause.
Definition at line 252 of file OpenMPClause.h.
getPostUpdateExpr() [2/2]
const Expr* clang::OMPClauseWithPostUpdate::getPostUpdateExpr () const inline
Get post-update expression for the clause.
Definition at line 249 of file OpenMPClause.h.
setPostUpdateExpr()
void clang::OMPClauseWithPostUpdate::setPostUpdateExpr (Expr * S) inline protected
Set pre-initialization statement for the clause.
Definition at line 245 of file OpenMPClause.h.
Referenced by clang::OMPLinearClause::Create(), clang::OMPInReductionClause::Create(), clang::OMPTaskReductionClause::Create(), and clang::OMPLastprivateClause::Create().
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 234 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp