clang: clang::Parser::MultiParseScope Class Reference
clang::Parser::MultiParseScope Class Reference
Introduces zero or more scopes for parsing.
#include "clang/Parse/Parser.h"
Public Member Functions
MultiParseScope (Parser &Self)
void Enter (unsigned ScopeFlags)
void Exit ()
~MultiParseScope ()
Detailed Description
Introduces zero or more scopes for parsing.
The scopes will all be exited when the object is destroyed.
Definition at line 1124 of file Parser.h.
Constructor & Destructor Documentation
MultiParseScope()
clang::Parser::MultiParseScope::MultiParseScope (Parser & Self) inline
Definition at line 1131 of file Parser.h.
~MultiParseScope()
clang::Parser::MultiParseScope::~MultiParseScope () inline
Definition at line 1142 of file Parser.h.
References Exit().
Member Function Documentation
Enter()
void clang::Parser::MultiParseScope::Enter (unsigned ScopeFlags) inline
Definition at line 1132 of file Parser.h.
References clang::Parser::EnterScope().
Referenced by clang::Parser::ReenterClassScopeRAII::ReenterClassScopeRAII().
Exit()
void clang::Parser::MultiParseScope::Exit () inline
Definition at line 1136 of file Parser.h.
References clang::Parser::ExitScope().
Referenced by ~MultiParseScope().
The documentation for this class was generated from the following file:
include/clang/Parse/Parser.h