clang: clang::comments::Token Class Reference
clang::comments::Token Class Reference
Comment token.
#include "clang/AST/CommentLexer.h"
Public Member Functions
SourceLocation getLocation () const LLVM_READONLY
void setLocation (SourceLocation SL)
SourceLocation getEndLocation () const LLVM_READONLY
tok::TokenKind getKind () const LLVM_READONLY
void setKind (tok::TokenKind K)
bool is (tok::TokenKind K) const LLVM_READONLY
bool isNot (tok::TokenKind K) const LLVM_READONLY
unsigned getLength () const LLVM_READONLY
void setLength (unsigned L)
StringRef getText () const LLVM_READONLY
void setText (StringRef Text)
StringRef getUnknownCommandName () const LLVM_READONLY
void setUnknownCommandName (StringRef Name)
unsigned getCommandID () const LLVM_READONLY
void setCommandID (unsigned ID)
unsigned getVerbatimBlockID () const LLVM_READONLY
void setVerbatimBlockID (unsigned ID)
StringRef getVerbatimBlockText () const LLVM_READONLY
void setVerbatimBlockText (StringRef Text)
unsigned getVerbatimLineID () const LLVM_READONLY
void setVerbatimLineID (unsigned ID)
StringRef getVerbatimLineText () const LLVM_READONLY
void setVerbatimLineText (StringRef Text)
StringRef getHTMLTagStartName () const LLVM_READONLY
void setHTMLTagStartName (StringRef Name)
StringRef getHTMLIdent () const LLVM_READONLY
void setHTMLIdent (StringRef Name)
StringRef getHTMLQuotedString () const LLVM_READONLY
void setHTMLQuotedString (StringRef Str)
StringRef getHTMLTagEndName () const LLVM_READONLY
void setHTMLTagEndName (StringRef Name)
void dump (const Lexer &L, const SourceManager &SM) const
Friends
class Lexer
class TextTokenRetokenizer
Detailed Description
Comment token.
Definition at line 55 of file CommentLexer.h.
Member Function Documentation
dump()
void clang::comments::Token::dump (const Lexer & L, const SourceManager & SM) const
Definition at line 21 of file CommentLexer.cpp.
References clang::comments::Lexer::getSpelling(), clang::SourceLocation::print(), and SM.
getCommandID()
unsigned clang::comments::Token::getCommandID () const inline
Definition at line 120 of file CommentLexer.h.
References clang::comments::tok::at_command, clang::comments::tok::backslash_command, and is().
Referenced by clang::comments::BriefParser::Parse(), clang::comments::Parser::parseBlockCommand(), clang::comments::Parser::parseInlineCommand(), and clang::comments::Parser::parseParagraphOrBlockCommand().
getEndLocation()
SourceLocation clang::comments::Token::getEndLocation () const inline
Definition at line 83 of file CommentLexer.h.
References clang::SourceLocation::getLocWithOffset().
Referenced by clang::comments::Parser::parseBlockCommand(), clang::comments::Parser::parseCommandArgs(), clang::comments::Parser::parseHTMLStartTag(), clang::comments::Parser::parseInlineCommand(), clang::comments::Parser::parseParagraphOrBlockCommand(), clang::comments::Parser::parseParamCommandArgs(), clang::comments::Parser::parseTParamCommandArgs(), and clang::comments::Parser::parseVerbatimLine().
getHTMLIdent()
StringRef clang::comments::Token::getHTMLIdent () const inline
Definition at line 183 of file CommentLexer.h.
References clang::comments::tok::html_ident, and is().
Referenced by clang::comments::Parser::parseHTMLStartTag().
getHTMLQuotedString()
StringRef clang::comments::Token::getHTMLQuotedString () const inline
Definition at line 194 of file CommentLexer.h.
References clang::comments::tok::html_quoted_string, and is().
Referenced by clang::comments::Parser::parseHTMLStartTag().
getHTMLTagEndName()
StringRef clang::comments::Token::getHTMLTagEndName () const inline
Definition at line 205 of file CommentLexer.h.
References clang::comments::tok::html_end_tag, and is().
Referenced by clang::comments::Parser::parseHTMLEndTag().
getHTMLTagStartName()
StringRef clang::comments::Token::getHTMLTagStartName () const inline
Definition at line 172 of file CommentLexer.h.
References clang::comments::tok::html_start_tag, and is().
Referenced by clang::comments::Parser::parseHTMLStartTag().
getKind()
tok::TokenKind clang::comments::Token::getKind () const inline
Definition at line 89 of file CommentLexer.h.
Referenced by clang::comments::Parser::parseBlockContent(), clang::comments::Parser::parseHTMLStartTag(), and clang::comments::Parser::parseParagraphOrBlockCommand().
getLength()
unsigned clang::comments::Token::getLength () const inline
Definition at line 95 of file CommentLexer.h.
Referenced by clang::comments::Lexer::getSpelling().
getLocation()
SourceLocation clang::comments::Token::getLocation () const inline
Definition at line 80 of file CommentLexer.h.
Referenced by clang::comments::Lexer::getSpelling(), clang::comments::Parser::parseBlockCommand(), clang::comments::Parser::parseCommandArgs(), clang::comments::Parser::parseHTMLEndTag(), clang::comments::Parser::parseHTMLStartTag(), clang::comments::Parser::parseInlineCommand(), clang::comments::Parser::parseParagraphOrBlockCommand(), clang::comments::Parser::parseParamCommandArgs(), clang::comments::Parser::parseTParamCommandArgs(), clang::comments::Parser::parseVerbatimBlock(), and clang::comments::Parser::parseVerbatimLine().
getText()
StringRef clang::comments::Token::getText () const inline
Definition at line 98 of file CommentLexer.h.
References is(), and clang::comments::tok::text.
Referenced by clang::comments::BriefParser::Parse(), clang::comments::Parser::parseCommandArgs(), clang::comments::Parser::parseParagraphOrBlockCommand(), clang::comments::Parser::parseParamCommandArgs(), and clang::comments::Parser::parseTParamCommandArgs().
getUnknownCommandName()
StringRef clang::comments::Token::getUnknownCommandName () const inline
Definition at line 109 of file CommentLexer.h.
References is(), and clang::comments::tok::unknown_command.
Referenced by clang::comments::Parser::parseParagraphOrBlockCommand().
getVerbatimBlockID()
unsigned clang::comments::Token::getVerbatimBlockID () const inline
Definition at line 130 of file CommentLexer.h.
References is(), clang::comments::tok::verbatim_block_begin, and clang::comments::tok::verbatim_block_end.
Referenced by clang::comments::Parser::parseVerbatimBlock().
getVerbatimBlockText()
StringRef clang::comments::Token::getVerbatimBlockText () const inline
Definition at line 140 of file CommentLexer.h.
References is(), and clang::comments::tok::verbatim_block_line.
Referenced by clang::comments::Parser::parseVerbatimBlock().
getVerbatimLineID()
unsigned clang::comments::Token::getVerbatimLineID () const inline
Definition at line 151 of file CommentLexer.h.
References is(), and clang::comments::tok::verbatim_line_name.
Referenced by clang::comments::Parser::parseVerbatimLine().
getVerbatimLineText()
StringRef clang::comments::Token::getVerbatimLineText () const inline
Definition at line 161 of file CommentLexer.h.
References is(), and clang::comments::tok::verbatim_line_text.
Referenced by clang::comments::Parser::parseVerbatimLine().
is()
bool clang::comments::Token::is (tok::TokenKind K) const inline
Definition at line 92 of file CommentLexer.h.
Referenced by getCommandID(), getHTMLIdent(), getHTMLQuotedString(), getHTMLTagEndName(), getHTMLTagStartName(), getText(), getUnknownCommandName(), getVerbatimBlockID(), getVerbatimBlockText(), getVerbatimLineID(), getVerbatimLineText(), clang::comments::BriefParser::Parse(), clang::comments::Parser::parseBlockCommand(), clang::comments::Parser::parseFullComment(), clang::comments::Parser::parseHTMLEndTag(), clang::comments::Parser::parseHTMLStartTag(), clang::comments::Parser::parseInlineCommand(), clang::comments::Parser::parseParagraphOrBlockCommand(), clang::comments::Parser::parseVerbatimBlock(), clang::comments::Parser::parseVerbatimLine(), setCommandID(), setHTMLQuotedString(), setText(), setVerbatimBlockID(), setVerbatimBlockText(), setVerbatimLineID(), and setVerbatimLineText().
isNot()
bool clang::comments::Token::isNot (tok::TokenKind K) const inline
Definition at line 93 of file CommentLexer.h.
Referenced by clang::comments::BriefParser::Parse(), clang::comments::Parser::parseFullComment(), and clang::comments::Parser::parseHTMLStartTag().
setCommandID()
void clang::comments::Token::setCommandID (unsigned ID) inline
Definition at line 125 of file CommentLexer.h.
References clang::comments::tok::at_command, clang::comments::tok::backslash_command, ID, and is().
setHTMLIdent()
void clang::comments::Token::setHTMLIdent (StringRef Name) inline
Definition at line 188 of file CommentLexer.h.
setHTMLQuotedString()
void clang::comments::Token::setHTMLQuotedString (StringRef Str) inline
Definition at line 199 of file CommentLexer.h.
References clang::comments::tok::html_quoted_string, and is().
setHTMLTagEndName()
void clang::comments::Token::setHTMLTagEndName (StringRef Name) inline
Definition at line 210 of file CommentLexer.h.
setHTMLTagStartName()
void clang::comments::Token::setHTMLTagStartName (StringRef Name) inline
Definition at line 177 of file CommentLexer.h.
setKind()
void clang::comments::Token::setKind (tok::TokenKind K) inline
Definition at line 90 of file CommentLexer.h.
setLength()
void clang::comments::Token::setLength (unsigned L) inline
Definition at line 96 of file CommentLexer.h.
setLocation()
void clang::comments::Token::setLocation (SourceLocation SL) inline
Definition at line 81 of file CommentLexer.h.
setText()
void clang::comments::Token::setText (StringRef Text) inline
Definition at line 103 of file CommentLexer.h.
References is(), clang::comments::tok::text, and Text.
setUnknownCommandName()
void clang::comments::Token::setUnknownCommandName (StringRef Name) inline
Definition at line 114 of file CommentLexer.h.
setVerbatimBlockID()
void clang::comments::Token::setVerbatimBlockID (unsigned ID) inline
Definition at line 135 of file CommentLexer.h.
References ID, is(), clang::comments::tok::verbatim_block_begin, and clang::comments::tok::verbatim_block_end.
setVerbatimBlockText()
void clang::comments::Token::setVerbatimBlockText (StringRef Text) inline
Definition at line 145 of file CommentLexer.h.
References is(), Text, and clang::comments::tok::verbatim_block_line.
setVerbatimLineID()
void clang::comments::Token::setVerbatimLineID (unsigned ID) inline
Definition at line 156 of file CommentLexer.h.
References ID, is(), and clang::comments::tok::verbatim_line_name.
setVerbatimLineText()
void clang::comments::Token::setVerbatimLineText (StringRef Text) inline
Definition at line 166 of file CommentLexer.h.
References is(), Text, and clang::comments::tok::verbatim_line_text.
Friends And Related Function Documentation
Lexer
friend class Lexer friend
Definition at line 56 of file CommentLexer.h.
TextTokenRetokenizer
friend class TextTokenRetokenizer friend
Definition at line 57 of file CommentLexer.h.
The documentation for this class was generated from the following files:
include/clang/AST/CommentLexer.h
lib/AST/CommentLexer.cpp