clang: clang::OMPFullClause Class Reference
clang::OMPFullClause Class Reference final
Representation of the 'full' clause of the '#pragma omp unroll' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPFullClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation EndLoc)
Build an AST node for a 'full' clause.
static OMPFullClause * CreateEmpty (const ASTContext &C)
Build an empty 'full' AST node for deserialization.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
Representation of the 'full' clause of the '#pragma omp unroll' directive.
#pragma omp unroll full
for (int i = 0; i < 64; ++i)
Definition at line 973 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPFullClause::children () inline
Definition at line 993 of file OpenMPClause.h.
children() [2/2]
const_child_range clang::OMPFullClause::children () const inline
Definition at line 994 of file OpenMPClause.h.
classof()
static bool clang::OMPFullClause::classof (const OMPClause * T) inline static
Definition at line 1005 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
Create()
OMPFullClause * OMPFullClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation EndLoc) static
Build an AST node for a 'full' clause.
Parameters
C Context of the AST.
StartLoc Starting location of the clause.
EndLoc Ending location of the clause.
Definition at line 958 of file OpenMPClause.cpp.
References clang::OMPClause::setLocEnd(), and clang::OMPClause::setLocStart().
Referenced by clang::Sema::ActOnOpenMPFullClause().
CreateEmpty()
OMPFullClause * OMPFullClause::CreateEmpty (const ASTContext & C) static
Build an empty 'full' AST node for deserialization.
Parameters
C Context of the AST.
Definition at line 967 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
used_children() [1/2]
child_range clang::OMPFullClause::used_children () inline
Definition at line 998 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPFullClause::used_children () const inline
Definition at line 1001 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 974 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp