clang: clang::arcmt::trans::BodyContext Class Reference
clang::arcmt::trans::BodyContext Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/ARCMigrate/Transforms.h"
Public Member Functions
BodyContext (MigrationContext &MigrateCtx, Stmt *S)
MigrationContext & getMigrationContext ()
ParentMap & getParentMap ()
Stmt * getTopStmt ()
Detailed Description
Definition at line 45 of file Transforms.h.
Constructor & Destructor Documentation
BodyContext()
clang::arcmt::trans::BodyContext::BodyContext (MigrationContext & MigrateCtx, Stmt * S) inline
Definition at line 51 of file Transforms.h.
Member Function Documentation
getMigrationContext()
MigrationContext& clang::arcmt::trans::BodyContext::getMigrationContext () inline
Definition at line 54 of file Transforms.h.
Referenced by clang::arcmt::trans::BlockObjCVariableTraverser::traverseBody(), and clang::arcmt::trans::GCCollectableCallsTraverser::traverseBody().
getParentMap()
ParentMap& clang::arcmt::trans::BodyContext::getParentMap () inline
Definition at line 55 of file Transforms.h.
getTopStmt()
Stmt* clang::arcmt::trans::BodyContext::getTopStmt () inline
Definition at line 56 of file Transforms.h.
Referenced by clang::arcmt::trans::BlockObjCVariableTraverser::traverseBody(), and clang::arcmt::trans::GCCollectableCallsTraverser::traverseBody().
The documentation for this class was generated from the following file:
lib/ARCMigrate/Transforms.h