clang: clang::driver::OffloadDepsJobAction Class Reference
clang::driver::OffloadDepsJobAction Class Reference final
#include "clang/Driver/Action.h"
Classes
struct DependentActionInfo
Type that provides information about the actions that depend on this offload deps action.
Public Member Functions
OffloadDepsJobAction (const OffloadAction::HostDependence &HDep, types::ID Type)
void registerDependentActionInfo (const ToolChain *TC, StringRef BoundArch, OffloadKind Kind)
Register information about a dependent action.
ArrayRef< DependentActionInfo > getDependentActionsInfo () const
Return the information about all depending actions.
const ToolChain * getHostTC () const
Public Member Functions inherited from clang::driver::Action
virtual ~Action ()
const char * getClassName () const
ActionClass getKind () const
types::ID getType () const
ActionList & getInputs ()
const ActionList & getInputs () const
size_type size () const
input_iterator input_begin ()
input_iterator input_end ()
input_range inputs ()
input_const_iterator input_begin () const
input_const_iterator input_end () const
input_const_range inputs () const
void setCannotBeCollapsedWithNextDependentAction ()
Mark this action as not legal to collapse.
bool isCollapsingWithNextDependentActionLegal () const
Return true if this function can be collapsed with others.
std::string getOffloadingKindPrefix () const
Return a string containing the offload kind of the action.
void propagateDeviceOffloadInfo (OffloadKind OKind, const char *OArch)
Set the device offload info of this action and propagate it to its dependences.
void propagateHostOffloadInfo (unsigned OKinds, const char *OArch)
Append the host offload info of this action and propagate it to its dependences.
void setHostOffloadInfo (unsigned OKinds, const char *OArch)
void propagateOffloadInfo (const Action *A)
Set the offload info of this action to be the same as the provided action, and propagate it to its dependences.
unsigned getOffloadingHostActiveKinds () const
OffloadKind getOffloadingDeviceKind () const
const char * getOffloadingArch () const
bool isHostOffloading (OffloadKind OKind) const
Check if this action have any offload kinds.
bool isDeviceOffloading (OffloadKind OKind) const
bool isOffloading (OffloadKind OKind) const
Static Public Member Functions
static bool classof (const Action *A)
Static Public Member Functions inherited from clang::driver::JobAction
static bool classof (const Action *A)
Static Public Member Functions inherited from clang::driver::Action
static const char * getClassName (ActionClass AC)
static std::string GetOffloadingFileNamePrefix (OffloadKind Kind, StringRef NormalizedTriple, bool CreatePrefixForHost=false)
Return a string that can be used as prefix in order to generate unique files for each offloading kind.
static StringRef GetOffloadKindName (OffloadKind Kind)
Return a string containing a offload kind name.
Additional Inherited Members
Public Types inherited from clang::driver::Action
enum ActionClass {
InputClass = 0, BindArchClass, OffloadClass, ForEachWrappingClass,
PreprocessJobClass, PrecompileJobClass, HeaderModulePrecompileJobClass, ExtractAPIJobClass,
AnalyzeJobClass, MigrateJobClass, CompileJobClass, BackendJobClass,
AssembleJobClass, LinkJobClass, IfsMergeJobClass, LipoJobClass,
DsymutilJobClass, VerifyDebugInfoJobClass, VerifyPCHJobClass, OffloadBundlingJobClass,
OffloadUnbundlingJobClass, OffloadWrapperJobClass, OffloadDepsJobClass, SPIRVTranslatorJobClass,
SPIRCheckJobClass, SYCLPostLinkJobClass, BackendCompileJobClass, FileTableTformJobClass,
AppendFooterJobClass, SpirvToIrWrapperJobClass, LinkerWrapperJobClass, StaticLibJobClass,
JobClassFirst = PreprocessJobClass, JobClassLast = StaticLibJobClass
}
enum OffloadKind {
OFK_None = 0x00, OFK_Host = 0x01, OFK_Cuda = 0x02, OFK_OpenMP = 0x04,
OFK_HIP = 0x08, OFK_SYCL = 0x10
}
using size_type = ActionList::size_type
using input_iterator = ActionList::iterator
using input_const_iterator = ActionList::const_iterator
using input_range = llvm::iterator_range< input_iterator >
using input_const_range = llvm::iterator_range< input_const_iterator >
Protected Member Functions inherited from clang::driver::JobAction
JobAction (ActionClass Kind, Action *Input, types::ID Type)
JobAction (ActionClass Kind, const ActionList &Inputs, types::ID Type)
Protected Member Functions inherited from clang::driver::Action
Action (ActionClass Kind, types::ID Type)
Action (ActionClass Kind, Action *Input, types::ID Type)
Action (ActionClass Kind, Action *Input)
Action (ActionClass Kind, const ActionList &Inputs, types::ID Type)
Protected Attributes inherited from clang::driver::Action
unsigned ActiveOffloadKindMask = 0u
Offload information.
OffloadKind OffloadingDeviceKind = OFK_None
Offloading kind of the device.
const char * OffloadingArch = nullptr
The Offloading architecture associated with this action.
Detailed Description
Definition at line 679 of file Action.h.
Constructor & Destructor Documentation
OffloadDepsJobAction()
OffloadDepsJobAction::OffloadDepsJobAction (const OffloadAction::HostDependence & HDep, types::ID Type)
Definition at line 471 of file Action.cpp.
References clang::driver::Action::ActiveOffloadKindMask, clang::driver::OffloadAction::HostDependence::getAction(), clang::driver::OffloadAction::HostDependence::getBoundArch(), clang::driver::OffloadAction::HostDependence::getOffloadKinds(), clang::driver::Action::OffloadingArch, and clang::driver::Action::propagateHostOffloadInfo().
Member Function Documentation
classof()
static bool clang::driver::OffloadDepsJobAction::classof (const Action * A) inline static
Definition at line 728 of file Action.h.
References clang::driver::Action::getKind(), and clang::driver::Action::OffloadDepsJobClass.
getDependentActionsInfo()
ArrayRef<DependentActionInfo> clang::driver::OffloadDepsJobAction::getDependentActionsInfo () const inline
Return the information about all depending actions.
Definition at line 722 of file Action.h.
getHostTC()
const ToolChain* clang::driver::OffloadDepsJobAction::getHostTC () const inline
Definition at line 726 of file Action.h.
registerDependentActionInfo()
void clang::driver::OffloadDepsJobAction::registerDependentActionInfo (const ToolChain * TC, StringRef BoundArch, OffloadKind Kind) inline
Register information about a dependent action.
Definition at line 716 of file Action.h.
The documentation for this class was generated from the following files:
include/clang/Driver/Action.h
lib/Driver/Action.cpp