clang: clang::ento::ProgramStateManager Class Reference
clang::ento::ProgramStateManager Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
Public Member Functions
ProgramStateManager (ASTContext &Ctx, StoreManagerCreator CreateStoreManager, ConstraintManagerCreator CreateConstraintManager, llvm::BumpPtrAllocator &alloc, ExprEngine *expreng)
~ProgramStateManager ()
ProgramStateRef getInitialState (const LocationContext *InitLoc)
ASTContext & getContext ()
const ASTContext & getContext () const
BasicValueFactory & getBasicVals ()
SValBuilder & getSValBuilder ()
const SValBuilder & getSValBuilder () const
SymbolManager & getSymbolManager ()
const SymbolManager & getSymbolManager () const
llvm::BumpPtrAllocator & getAllocator ()
MemRegionManager & getRegionManager ()
const MemRegionManager & getRegionManager () const
CallEventManager & getCallEventManager ()
StoreManager & getStoreManager ()
ConstraintManager & getConstraintManager ()
ExprEngine & getOwningEngine ()
ProgramStateRef removeDeadBindingsFromEnvironmentAndStore (ProgramStateRef St, const StackFrameContext *LCtx, SymbolReaper &SymReaper)
SVal ArrayToPointer (Loc Array, QualType ElementTy)
ProgramStateRef addGDM (ProgramStateRef St, void *Key, void *Data)
ProgramStateRef removeGDM (ProgramStateRef state, void *Key)
void iterBindings (ProgramStateRef state, StoreManager::BindingsHandler &F)
ProgramStateRef getPersistentState (ProgramState &Impl)
ProgramStateRef getPersistentStateWithGDM (ProgramStateRef FromState, ProgramStateRef GDMState)
bool haveEqualConstraints (ProgramStateRef S1, ProgramStateRef S2) const
bool haveEqualEnvironments (ProgramStateRef S1, ProgramStateRef S2) const
bool haveEqualStores (ProgramStateRef S1, ProgramStateRef S2) const
template<typename T >
ProgramStateRef set (ProgramStateRef st, typename ProgramStateTrait< T >::data_type D)
template<typename T >
ProgramStateRef set (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::value_type V, typename ProgramStateTrait< T >::context_type C)
template<typename T >
ProgramStateRef add (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::context_type C)
template<typename T >
ProgramStateRef remove (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::context_type C)
template<typename T >
ProgramStateRef remove (ProgramStateRef st)
void * FindGDMContext (void *index, void *(*CreateContext)(llvm::BumpPtrAllocator &), void(*DeleteContext)(void *))
template<typename T >
ProgramStateTrait< T >::context_type get_context ()
Friends
class ProgramState
void ProgramStateRelease (const ProgramState *state)
Decrement the number of times this state is referenced.
Detailed Description
Definition at line 461 of file ProgramState.h.
Constructor & Destructor Documentation
ProgramStateManager()
ProgramStateManager::ProgramStateManager (ASTContext & Ctx, StoreManagerCreator CreateStoreManager, ConstraintManagerCreator CreateConstraintManager, llvm::BumpPtrAllocator & alloc, ExprEngine * expreng)
Definition at line 71 of file ProgramState.cpp.
~ProgramStateManager()
ProgramStateManager::~ProgramStateManager ()
Definition at line 84 of file ProgramState.cpp.
Member Function Documentation
add()
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::add (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::context_type C) inline
Definition at line 614 of file ProgramState.h.
References addGDM(), and AttributeLangSupport::C.
Referenced by clang::ento::ProgramState::add().
addGDM()
ProgramStateRef ProgramStateManager::addGDM (ProgramStateRef St, void * Key, void * Data)
Definition at line 507 of file ProgramState.cpp.
References getPersistentState().
Referenced by add(), remove(), and set().
ArrayToPointer()
SVal clang::ento::ProgramStateManager::ArrayToPointer (Loc Array, QualType ElementTy) inline
Definition at line 548 of file ProgramState.h.
References Array.
Referenced by clang::ento::SValBuilder::evalCastSubKind().
FindGDMContext()
void * ProgramStateManager::FindGDMContext (void * index, void *(*)(llvm::BumpPtrAllocator &) CreateContext, void(*)(void *) DeleteContext)
Definition at line 494 of file ProgramState.cpp.
Referenced by get_context().
get_context()
template<typename T > ProgramStateTrait<T>::context_type clang::ento::ProgramStateManager::get_context () inline
Definition at line 640 of file ProgramState.h.
References FindGDMContext().
Referenced by clang::ento::ProgramState::get_context().
getAllocator()
llvm::BumpPtrAllocator& clang::ento::ProgramStateManager::getAllocator () inline
Definition at line 526 of file ProgramState.h.
getBasicVals()
BasicValueFactory& clang::ento::ProgramStateManager::getBasicVals () inline
Definition at line 507 of file ProgramState.h.
Referenced by clang::ento::ProgramState::getBasicVals(), and clang::ento::ExprEngine::getBasicVals().
getCallEventManager()
CallEventManager& clang::ento::ProgramStateManager::getCallEventManager () inline
Definition at line 535 of file ProgramState.h.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::VisitCallExpr(), clang::ento::ExprEngine::VisitCXXDeleteExpr(), clang::ento::ExprEngine::VisitCXXNewAllocatorCall(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::UndefOrNullArgVisitor::VisitNode(), clang::ento::NoStateChangeFuncVisitor::VisitNode(), and clang::ento::ExprEngine::VisitObjCMessage().
getConstraintManager()
ConstraintManager& clang::ento::ProgramStateManager::getConstraintManager () inline
Definition at line 538 of file ProgramState.h.
Referenced by clang::ento::ProgramState::getConstraintManager(), clang::ento::ExprEngine::getConstraintManager(), and clang::ento::ProgramState::printJson().
getContext() [1/2]
ASTContext& clang::ento::ProgramStateManager::getContext () inline
Definition at line 504 of file ProgramState.h.
Referenced by clang::ento::StoreManager::castRegion(), and clang::ento::ProgramState::printJson().
getContext() [2/2]
const ASTContext& clang::ento::ProgramStateManager::getContext () const inline
Definition at line 505 of file ProgramState.h.
getInitialState()
ProgramStateRef ProgramStateManager::getInitialState (const LocationContext * InitLoc)
Definition at line 387 of file ProgramState.cpp.
References clang::ento::EnvironmentManager::getInitialEnvironment(), getPersistentState(), and State.
Referenced by clang::ento::ExprEngine::getInitialState().
getOwningEngine()
ExprEngine& clang::ento::ProgramStateManager::getOwningEngine () inline
Definition at line 539 of file ProgramState.h.
Referenced by clang::ento::ProgramState::bindDefaultInitial(), clang::ento::ProgramState::bindDefaultZero(), clang::ento::SValBuilder::evalCastSubKind(), clang::ento::ProgramState::getAnalysisManager(), and clang::ento::ProgramState::printJson().
getPersistentState()
ProgramStateRef ProgramStateManager::getPersistentState (ProgramState & Impl)
Definition at line 404 of file ProgramState.cpp.
References ProgramState, and State.
Referenced by addGDM(), getInitialState(), getPersistentStateWithGDM(), removeDeadBindingsFromEnvironmentAndStore(), and removeGDM().
getPersistentStateWithGDM()
ProgramStateRef ProgramStateManager::getPersistentStateWithGDM (ProgramStateRef FromState, ProgramStateRef GDMState)
Definition at line 396 of file ProgramState.cpp.
References getPersistentState().
getRegionManager() [1/2]
MemRegionManager& clang::ento::ProgramStateManager::getRegionManager () inline
Definition at line 528 of file ProgramState.h.
Referenced by clang::ento::ProgramState::getRegion().
getRegionManager() [2/2]
const MemRegionManager& clang::ento::ProgramStateManager::getRegionManager () const inline
Definition at line 531 of file ProgramState.h.
getStoreManager()
StoreManager& clang::ento::ProgramStateManager::getStoreManager () inline
Definition at line 537 of file ProgramState.h.
Referenced by clang::ento::SValBuilder::getCastedMemRegionVal(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::ExprEngine::getStoreManager(), clang::ento::ProgramState::printJson(), clang::ento::ProgramState::ProgramState(), clang::ento::ExprEngine::VisitCast(), and clang::ento::ProgramState::~ProgramState().
getSValBuilder() [1/2]
SValBuilder& clang::ento::ProgramStateManager::getSValBuilder () inline
Definition at line 511 of file ProgramState.h.
Referenced by clang::ento::ProgramState::areEqual(), clang::ento::CreateRangeConstraintManager(), clang::ento::CreateZ3ConstraintManager(), getBVF(), and clang::ento::CXXInstanceCall::getInitialStackFrameContents().
getSValBuilder() [2/2]
const SValBuilder& clang::ento::ProgramStateManager::getSValBuilder () const inline
Definition at line 515 of file ProgramState.h.
getSymbolManager() [1/2]
SymbolManager& clang::ento::ProgramStateManager::getSymbolManager () inline
Definition at line 519 of file ProgramState.h.
Referenced by clang::ento::ProgramState::getSymbolManager().
getSymbolManager() [2/2]
const SymbolManager& clang::ento::ProgramStateManager::getSymbolManager () const inline
Definition at line 522 of file ProgramState.h.
haveEqualConstraints()
bool clang::ento::ProgramStateManager::haveEqualConstraints (ProgramStateRef S1, ProgramStateRef S2) const inline
Definition at line 566 of file ProgramState.h.
Referenced by clang::ento::ConditionBRVisitor::VisitTrueTest().
haveEqualEnvironments()
bool clang::ento::ProgramStateManager::haveEqualEnvironments (ProgramStateRef S1, ProgramStateRef S2) const inline
Definition at line 570 of file ProgramState.h.
haveEqualStores()
bool clang::ento::ProgramStateManager::haveEqualStores (ProgramStateRef S1, ProgramStateRef S2) const inline
Definition at line 574 of file ProgramState.h.
iterBindings()
void clang::ento::ProgramStateManager::iterBindings (ProgramStateRef state, StoreManager::BindingsHandler & F) inline
Definition at line 558 of file ProgramState.h.
References state.
Referenced by GetAllocationSite(), and getAllVarBindingsForSymbol().
remove() [1/2]
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::remove (ProgramStateRef st) inline
Definition at line 631 of file ProgramState.h.
References removeGDM().
remove() [2/2]
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::remove (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::context_type C) inline
Definition at line 622 of file ProgramState.h.
References addGDM(), and AttributeLangSupport::C.
Referenced by clang::ento::ProgramState::remove().
removeDeadBindingsFromEnvironmentAndStore()
ProgramStateRef ProgramStateManager::removeDeadBindingsFromEnvironmentAndStore (ProgramStateRef St, const StackFrameContext * LCtx, SymbolReaper & SymReaper)
Definition at line 90 of file ProgramState.cpp.
References getPersistentState(), clang::ento::ProgramState::getStore(), clang::ento::EnvironmentManager::removeDeadBindings(), clang::ento::SymbolReaper::setReapedStore(), and state.
removeGDM()
ProgramStateRef ProgramStateManager::removeGDM (ProgramStateRef state, void * Key)
Definition at line 519 of file ProgramState.cpp.
References getPersistentState(), and state.
Referenced by remove().
set() [1/2]
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::set (ProgramStateRef st, typename ProgramStateTrait< T >::data_type D) inline
Definition at line 598 of file ProgramState.h.
References addGDM().
Referenced by clang::ento::ProgramState::set().
set() [2/2]
template<typename T > ProgramStateRef clang::ento::ProgramStateManager::set (ProgramStateRef st, typename ProgramStateTrait< T >::key_type K, typename ProgramStateTrait< T >::value_type V, typename ProgramStateTrait< T >::context_type C) inline
Definition at line 604 of file ProgramState.h.
References addGDM(), AttributeLangSupport::C, and V.
Friends And Related Function Documentation
ProgramState
friend class ProgramState friend
Definition at line 462 of file ProgramState.h.
Referenced by getPersistentState().
ProgramStateRelease
void ProgramStateRelease (const ProgramState * state) friend
Decrement the number of times this state is referenced.
Definition at line 34 of file ProgramState.cpp.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h
lib/StaticAnalyzer/Core/ProgramState.cpp