clang: clang::DiagnosticNoteRenderer Class Reference
clang::DiagnosticNoteRenderer Class Reference abstract
Subclass of DiagnosticRender that turns all subdiagostics into explicit notes.
#include "clang/Frontend/DiagnosticRenderer.h"
Public Member Functions
DiagnosticNoteRenderer (const LangOptions &LangOpts, DiagnosticOptions *DiagOpts)
~DiagnosticNoteRenderer () override
void emitIncludeLocation (FullSourceLoc Loc, PresumedLoc PLoc) override
void emitImportLocation (FullSourceLoc Loc, PresumedLoc PLoc, StringRef ModuleName) override
void emitBuildingModuleLocation (FullSourceLoc Loc, PresumedLoc PLoc, StringRef ModuleName) override
virtual void emitNote (FullSourceLoc Loc, StringRef Message)=0
Public Member Functions inherited from clang::DiagnosticRenderer
void emitDiagnostic (FullSourceLoc Loc, DiagnosticsEngine::Level Level, StringRef Message, ArrayRef< CharSourceRange > Ranges, ArrayRef< FixItHint > FixItHints, DiagOrStoredDiag D=(Diagnostic *) nullptr)
Emit a diagnostic.
void emitStoredDiagnostic (StoredDiagnostic &Diag)
Additional Inherited Members
Protected Member Functions inherited from clang::DiagnosticRenderer
DiagnosticRenderer (const LangOptions &LangOpts, DiagnosticOptions *DiagOpts)
virtual ~DiagnosticRenderer ()
virtual void emitDiagnosticMessage (FullSourceLoc Loc, PresumedLoc PLoc, DiagnosticsEngine::Level Level, StringRef Message, ArrayRef< CharSourceRange > Ranges, DiagOrStoredDiag Info)=0
virtual void emitDiagnosticLoc (FullSourceLoc Loc, PresumedLoc PLoc, DiagnosticsEngine::Level Level, ArrayRef< CharSourceRange > Ranges)=0
virtual void emitCodeContext (FullSourceLoc Loc, DiagnosticsEngine::Level Level, SmallVectorImpl< CharSourceRange > &Ranges, ArrayRef< FixItHint > Hints)=0
virtual void beginDiagnostic (DiagOrStoredDiag D, DiagnosticsEngine::Level Level)
virtual void endDiagnostic (DiagOrStoredDiag D, DiagnosticsEngine::Level Level)
Protected Attributes inherited from clang::DiagnosticRenderer
const LangOptions & LangOpts
IntrusiveRefCntPtr< DiagnosticOptions > DiagOpts
SourceLocation LastLoc
The location of the previous diagnostic if known.
SourceLocation LastIncludeLoc
The location of the last include whose stack was printed if known.
DiagnosticsEngine::Level LastLevel = DiagnosticsEngine::Ignored
The level of the last diagnostic emitted.
Detailed Description
Subclass of DiagnosticRender that turns all subdiagostics into explicit notes.
It is up to subclasses to further define the behavior.
Definition at line 142 of file DiagnosticRenderer.h.
Constructor & Destructor Documentation
DiagnosticNoteRenderer()
clang::DiagnosticNoteRenderer::DiagnosticNoteRenderer (const LangOptions & LangOpts, DiagnosticOptions * DiagOpts) inline
Definition at line 144 of file DiagnosticRenderer.h.
~DiagnosticNoteRenderer()
DiagnosticNoteRenderer::~DiagnosticNoteRenderer () override default
Member Function Documentation
emitBuildingModuleLocation()
void DiagnosticNoteRenderer::emitBuildingModuleLocation (FullSourceLoc Loc, PresumedLoc PLoc, StringRef ModuleName) override virtual
Implements clang::DiagnosticRenderer.
Definition at line 620 of file DiagnosticRenderer.cpp.
References emitNote(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), and clang::PresumedLoc::isValid().
emitImportLocation()
void DiagnosticNoteRenderer::emitImportLocation (FullSourceLoc Loc, PresumedLoc PLoc, StringRef ModuleName) override virtual
Implements clang::DiagnosticRenderer.
Definition at line 606 of file DiagnosticRenderer.cpp.
References emitNote(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), and clang::PresumedLoc::isValid().
emitIncludeLocation()
void DiagnosticNoteRenderer::emitIncludeLocation (FullSourceLoc Loc, PresumedLoc PLoc) override virtual
Implements clang::DiagnosticRenderer.
Definition at line 596 of file DiagnosticRenderer.cpp.
References emitNote(), clang::PresumedLoc::getFilename(), and clang::PresumedLoc::getLine().
emitNote()
virtual void clang::DiagnosticNoteRenderer::emitNote (FullSourceLoc Loc, StringRef Message) pure virtual
Referenced by emitBuildingModuleLocation(), emitImportLocation(), and emitIncludeLocation().
The documentation for this class was generated from the following files:
include/clang/Frontend/DiagnosticRenderer.h
lib/Frontend/DiagnosticRenderer.cpp