clang: clang::CodeGen::CallArgList Class Reference
clang::CodeGen::CallArgList Class Reference
CallArgList - Type for representing both the value and type of arguments in a call.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCall.h"
Classes
struct CallArgCleanup
struct Writeback
Public Types
typedef llvm::iterator_range< SmallVectorImpl< Writeback >::const_iterator > writeback_const_range
Public Member Functions
CallArgList ()=default
void add (RValue rvalue, QualType type)
void addUncopiedAggregate (LValue LV, QualType type)
void addFrom (const CallArgList &other)
Add all the arguments from another CallArgList to this one.
void addWriteback (LValue srcLV, Address temporary, llvm::Value *toUse)
bool hasWritebacks () const
writeback_const_range writebacks () const
void addArgCleanupDeactivation (EHScopeStack::stable_iterator Cleanup, llvm::Instruction *IsActiveIP)
ArrayRef< CallArgCleanup > getCleanupsToDeactivate () const
void allocateArgumentMemory (CodeGenFunction &CGF)
llvm::Instruction * getStackBase () const
void freeArgumentMemory (CodeGenFunction &CGF) const
bool isUsingInAlloca () const
Returns if we're using an inalloca struct to pass arguments in memory.
Detailed Description
CallArgList - Type for representing both the value and type of arguments in a call.
Definition at line 257 of file CGCall.h.
Member Typedef Documentation
writeback_const_range
typedef llvm::iterator_range<SmallVectorImpl<Writeback>::const_iterator> clang::CodeGen::CallArgList::writeback_const_range
Definition at line 310 of file CGCall.h.
Constructor & Destructor Documentation
CallArgList()
clang::CodeGen::CallArgList::CallArgList () default
Member Function Documentation
add()
void clang::CodeGen::CallArgList::add (RValue rvalue, QualType type) inline
Definition at line 281 of file CGCall.h.
References clang::ast_matchers::type.
Referenced by clang::CodeGen::CGCXXABI::addImplicitConstructorArgs(), commonEmitCXXMemberOrOperatorCall(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), clang::CodeGen::CodeGenFunction::EmitBlockCallExpr(), clang::CodeGen::CodeGenFunction::emitBuiltinOSLogFormat(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::EmitCallArg(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), clang::CodeGen::CodeGenFunction::EmitCXXMemberPointerCallExpr(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitDelegateCallArg(), clang::CodeGen::CodeGenFunction::EmitDelegateCXXConstructorCall(), clang::CodeGen::CodeGenFunction::EmitLambdaBlockInvokeBody(), clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaCallOpBody(), clang::CodeGen::CodeGenFunction::EmitLambdaStaticInvokeBody(), clang::CodeGen::CodeGenFunction::EmitObjCBoxedExpr(), emitStructSetterCall(), emitWritebackArg(), clang::CodeGen::CodeGenFunction::generateObjCGetterBody(), and clang::CodeGen::CodeGenFunction::generateObjCSetterBody().
addArgCleanupDeactivation()
void clang::CodeGen::CallArgList::addArgCleanupDeactivation (EHScopeStack::stable_iterator Cleanup, llvm::Instruction * IsActiveIP) inline
Definition at line 316 of file CGCall.h.
References clang::CodeGen::CallArgList::CallArgCleanup::Cleanup, and clang::CodeGen::CallArgList::CallArgCleanup::IsActiveIP.
Referenced by clang::CodeGen::CodeGenFunction::EmitCallArg(), and clang::CodeGen::CodeGenFunction::EmitDelegateCallArg().
addFrom()
void clang::CodeGen::CallArgList::addFrom (const CallArgList & other) inline
Add all the arguments from another CallArgList to this one.
After doing this, the old CallArgList retains its list of arguments, but must not be used to emit a call.
Definition at line 290 of file CGCall.h.
Referenced by commonEmitCXXMemberOrOperatorCall().
addUncopiedAggregate()
void clang::CodeGen::CallArgList::addUncopiedAggregate (LValue LV, QualType type) inline
Definition at line 283 of file CGCall.h.
References clang::ast_matchers::type.
Referenced by clang::CodeGen::CodeGenFunction::EmitCallArg().
addWriteback()
void clang::CodeGen::CallArgList::addWriteback (LValue srcLV, Address temporary, llvm::Value * toUse) inline
Definition at line 302 of file CGCall.h.
Referenced by emitWritebackArg().
allocateArgumentMemory()
void CallArgList::allocateArgumentMemory (CodeGenFunction & CGF)
Definition at line 4431 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder.
freeArgumentMemory()
void CallArgList::freeArgumentMemory (CodeGenFunction & CGF) const
Definition at line 4438 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::Builder.
Referenced by clang::CodeGen::CodeGenFunction::EmitCall().
getCleanupsToDeactivate()
ArrayRef<CallArgCleanup> clang::CodeGen::CallArgList::getCleanupsToDeactivate () const inline
Definition at line 324 of file CGCall.h.
Referenced by deactivateArgCleanupsBeforeCall(), and clang::CodeGen::CodeGenFunction::EmitCall().
getStackBase()
llvm::Instruction* clang::CodeGen::CallArgList::getStackBase () const inline
Definition at line 329 of file CGCall.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCall().
hasWritebacks()
bool clang::CodeGen::CallArgList::hasWritebacks () const inline
Definition at line 307 of file CGCall.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCall().
isUsingInAlloca()
bool clang::CodeGen::CallArgList::isUsingInAlloca () const inline
Returns if we're using an inalloca struct to pass arguments in memory.
Definition at line 334 of file CGCall.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCallArg().
writebacks()
writeback_const_range clang::CodeGen::CallArgList::writebacks () const inline
Definition at line 312 of file CGCall.h.
Referenced by emitWritebacks().
The documentation for this class was generated from the following files:
lib/CodeGen/CGCall.h
lib/CodeGen/CGCall.cpp