clang: clang::RISCV::RVVType Class Reference
clang::RISCV::RVVType Class Reference
#include "clang/Support/RISCVVIntrinsicUtils.h"
Public Member Functions
const std::string & getBuiltinStr () const
const std::string & getClangBuiltinStr () const
const std::string & getTypeStr () const
const std::string & getShortStr ()
bool isValid () const
bool isScalar () const
bool isVector () const
bool isVector (unsigned Width) const
bool isFloat () const
bool isBFloat () const
bool isSignedInteger () const
bool isFloatVector (unsigned Width) const
bool isFloat (unsigned Width) const
bool isConstant () const
bool isPointer () const
bool isTuple () const
unsigned getElementBitwidth () const
ScalarTypeKind getScalarType () const
VScaleVal getScale () const
unsigned getNF () const
Friends
class RVVTypeCache
Detailed Description
Definition at line 251 of file RISCVVIntrinsicUtils.h.
Member Function Documentation
getBuiltinStr()
const std::string& clang::RISCV::RVVType::getBuiltinStr () const inline
Definition at line 280 of file RISCVVIntrinsicUtils.h.
getClangBuiltinStr()
const std::string& clang::RISCV::RVVType::getClangBuiltinStr () const inline
Definition at line 284 of file RISCVVIntrinsicUtils.h.
getElementBitwidth()
unsigned clang::RISCV::RVVType::getElementBitwidth () const inline
Definition at line 319 of file RISCVVIntrinsicUtils.h.
getNF()
unsigned clang::RISCV::RVVType::getNF () const inline
Definition at line 323 of file RISCVVIntrinsicUtils.h.
getScalarType()
ScalarTypeKind clang::RISCV::RVVType::getScalarType () const inline
Definition at line 321 of file RISCVVIntrinsicUtils.h.
getScale()
VScaleVal clang::RISCV::RVVType::getScale () const inline
Definition at line 322 of file RISCVVIntrinsicUtils.h.
getShortStr()
const std::string& clang::RISCV::RVVType::getShortStr () inline
Definition at line 291 of file RISCVVIntrinsicUtils.h.
getTypeStr()
const std::string& clang::RISCV::RVVType::getTypeStr () const inline
Definition at line 288 of file RISCVVIntrinsicUtils.h.
isBFloat()
bool clang::RISCV::RVVType::isBFloat () const inline
Definition at line 306 of file RISCVVIntrinsicUtils.h.
References clang::RISCV::BFloat.
isConstant()
bool clang::RISCV::RVVType::isConstant () const inline
Definition at line 316 of file RISCVVIntrinsicUtils.h.
isFloat() [1/2]
bool clang::RISCV::RVVType::isFloat () const inline
Definition at line 305 of file RISCVVIntrinsicUtils.h.
References clang::RISCV::Float.
Referenced by isFloat(), and isFloatVector().
isFloat() [2/2]
bool clang::RISCV::RVVType::isFloat (unsigned Width) const inline
Definition at line 313 of file RISCVVIntrinsicUtils.h.
References isFloat().
isFloatVector()
bool clang::RISCV::RVVType::isFloatVector (unsigned Width) const inline
Definition at line 310 of file RISCVVIntrinsicUtils.h.
References isFloat(), and isVector().
isPointer()
bool clang::RISCV::RVVType::isPointer () const inline
Definition at line 317 of file RISCVVIntrinsicUtils.h.
isScalar()
bool clang::RISCV::RVVType::isScalar () const inline
Definition at line 300 of file RISCVVIntrinsicUtils.h.
isSignedInteger()
bool clang::RISCV::RVVType::isSignedInteger () const inline
Definition at line 307 of file RISCVVIntrinsicUtils.h.
References clang::RISCV::SignedInteger.
isTuple()
bool clang::RISCV::RVVType::isTuple () const inline
Definition at line 318 of file RISCVVIntrinsicUtils.h.
isValid()
bool clang::RISCV::RVVType::isValid () const inline
Definition at line 299 of file RISCVVIntrinsicUtils.h.
isVector() [1/2]
bool clang::RISCV::RVVType::isVector () const inline
Definition at line 301 of file RISCVVIntrinsicUtils.h.
Referenced by isFloatVector(), and isVector().
isVector() [2/2]
bool clang::RISCV::RVVType::isVector (unsigned Width) const inline
Definition at line 302 of file RISCVVIntrinsicUtils.h.
References isVector().
Friends And Related Function Documentation
RVVTypeCache
friend class RVVTypeCache friend
Definition at line 252 of file RISCVVIntrinsicUtils.h.
The documentation for this class was generated from the following files:
include/clang/Support/RISCVVIntrinsicUtils.h
lib/Support/RISCVVIntrinsicUtils.cpp