clang: clang::MemberPointerTypeLoc Class Reference
clang::MemberPointerTypeLoc Class Reference
Wrapper for source info for member pointers.
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getStarLoc () const
void setStarLoc (SourceLocation Loc)
const Type * getClass () const
TypeSourceInfo * getClassTInfo () const
void setClassTInfo (TypeSourceInfo *TI)
void initializeLocal (ASTContext &Context, SourceLocation Loc)
SourceRange getLocalSourceRange () const
Public Member Functions inherited from clang::PointerLikeTypeLoc< MemberPointerTypeLoc, MemberPointerType, MemberPointerLocInfo >
SourceLocation getSigilLoc () const
void setSigilLoc (SourceLocation Loc)
TypeLoc getPointeeLoc () const
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
QualType getInnerType () const
Public Member Functions inherited from clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (Derived other)
TypeLoc getNextTypeLoc () const
const TypeClass * getTypePtr () const
Additional Inherited Members
Protected Member Functions inherited from clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
LocalData * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Detailed Description
Wrapper for source info for member pointers.
Definition at line 1330 of file TypeLoc.h.
Member Function Documentation
getClass()
const Type* clang::MemberPointerTypeLoc::getClass () const inline
Definition at line 1342 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr().
getClassTInfo()
TypeSourceInfo* clang::MemberPointerTypeLoc::getClassTInfo () const inline
Definition at line 1346 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalData().
Referenced by getLocalSourceRange(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitMemberPointerTypeLoc().
getLocalSourceRange()
SourceRange clang::MemberPointerTypeLoc::getLocalSourceRange () const inline
Definition at line 1359 of file TypeLoc.h.
References getClassTInfo(), and getStarLoc().
getStarLoc()
SourceLocation clang::MemberPointerTypeLoc::getStarLoc () const inline
Definition at line 1334 of file TypeLoc.h.
References clang::PointerLikeTypeLoc< MemberPointerTypeLoc, MemberPointerType, MemberPointerLocInfo >::getSigilLoc().
Referenced by getLocalSourceRange().
initializeLocal()
void clang::MemberPointerTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc) inline
Definition at line 1354 of file TypeLoc.h.
setClassTInfo()
void clang::MemberPointerTypeLoc::setClassTInfo (TypeSourceInfo * TI) inline
Definition at line 1350 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalData().
setStarLoc()
void clang::MemberPointerTypeLoc::setStarLoc (SourceLocation Loc) inline
Definition at line 1338 of file TypeLoc.h.
References clang::PointerLikeTypeLoc< MemberPointerTypeLoc, MemberPointerType, MemberPointerLocInfo >::setSigilLoc().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h