clang: clang::PrettyStackTraceDecl Class Reference
clang::PrettyStackTraceDecl Class Reference
PrettyStackTraceDecl - If a crash occurs, indicate that it happened when doing something to a specific decl.
#include "clang/AST/DeclBase.h"
Public Member Functions
PrettyStackTraceDecl (const Decl *theDecl, SourceLocation L, SourceManager &sm, const char *Msg)
void print (raw_ostream &OS) const override
Detailed Description
PrettyStackTraceDecl - If a crash occurs, indicate that it happened when doing something to a specific decl.
Definition at line 1289 of file DeclBase.h.
Constructor & Destructor Documentation
PrettyStackTraceDecl()
clang::PrettyStackTraceDecl::PrettyStackTraceDecl (const Decl * theDecl, SourceLocation L, SourceManager & sm, const char * Msg) inline
Definition at line 1296 of file DeclBase.h.
References SM.
Member Function Documentation
print()
void PrettyStackTraceDecl::print (raw_ostream & OS) const override
Definition at line 309 of file DeclBase.cpp.
References clang::Decl::getLocation(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isValid(), and clang::SourceLocation::print().
The documentation for this class was generated from the following files:
include/clang/AST/DeclBase.h
lib/AST/DeclBase.cpp