clang: clang::FunctionEffectSet Class Reference
clang::FunctionEffectSet Class Reference
A mutable set of FunctionEffects and possibly conditions attached to them.
#include "clang/AST/Type.h"
Classes
struct Conflict
Public Types
using iterator = FunctionEffectIterator< FunctionEffectSet >
using Conflicts = SmallVector< Conflict >
Public Member Functions
FunctionEffectSet ()=default
FunctionEffectSet (const FunctionEffectsRef &FX)
bool empty () const
size_t size () const
iterator begin () const
iterator end () const
operator FunctionEffectsRef () const
void dump (llvm::raw_ostream &OS) const
bool insert (const FunctionEffectWithCondition &NewEC, Conflicts &Errs)
bool insert (const FunctionEffectsRef &Set, Conflicts &Errs)
Static Public Member Functions
static FunctionEffectSet getUnion (FunctionEffectsRef LHS, FunctionEffectsRef RHS, Conflicts &Errs)
static FunctionEffectSet getIntersection (FunctionEffectsRef LHS, FunctionEffectsRef RHS)
Public Attributes
friend iterator
Detailed Description
A mutable set of FunctionEffects and possibly conditions attached to them.
Used to compare and merge effects on declarations.
Has the same invariants as FunctionEffectsRef.
Definition at line 4920 of file Type.h.
Member Typedef Documentation
Conflicts
using clang::FunctionEffectSet::Conflicts = SmallVector<Conflict>
Definition at line 4952 of file Type.h.
iterator
using clang::FunctionEffectSet::iterator = FunctionEffectIterator<FunctionEffectSet>
Definition at line 4933 of file Type.h.
Constructor & Destructor Documentation
FunctionEffectSet() [1/2]
clang::FunctionEffectSet::FunctionEffectSet () default
Referenced by getUnion().
FunctionEffectSet() [2/2]
clang::FunctionEffectSet::FunctionEffectSet (const FunctionEffectsRef & FX) inline explicit
Definition at line 4927 of file Type.h.
Member Function Documentation
begin()
iterator clang::FunctionEffectSet::begin () const inline
Definition at line 4935 of file Type.h.
dump()
LLVM_DUMP_METHOD void FunctionEffectSet::dump (llvm::raw_ostream & OS) const
Definition at line 5321 of file Type.cpp.
References clang::FunctionEffectsRef::dump().
empty()
bool clang::FunctionEffectSet::empty () const inline
Definition at line 4930 of file Type.h.
end()
iterator clang::FunctionEffectSet::end () const inline
Definition at line 4936 of file Type.h.
getIntersection()
FunctionEffectSet FunctionEffectSet::getIntersection (FunctionEffectsRef LHS, FunctionEffectsRef RHS) static
Definition at line 5253 of file Type.cpp.
References clang::FunctionEffectsRef::begin(), and clang::FunctionEffectsRef::end().
Referenced by clang::ASTContext::mergeFunctionTypes().
getUnion()
FunctionEffectSet FunctionEffectSet::getUnion (FunctionEffectsRef LHS, FunctionEffectsRef RHS, Conflicts & Errs) static
Definition at line 5291 of file Type.cpp.
References clang::FunctionEffectsRef::empty(), FunctionEffectSet(), and insert().
Referenced by clang::ASTContext::mergeFunctionTypes().
insert() [1/2]
bool FunctionEffectSet::insert (const FunctionEffectsRef & Set, Conflicts & Errs)
Definition at line 5247 of file Type.cpp.
References insert(), and clang::Set.
insert() [2/2]
bool FunctionEffectSet::insert (const FunctionEffectWithCondition & NewEC, Conflicts & Errs)
Definition at line 5204 of file Type.cpp.
References clang::FunctionEffectWithCondition::Cond, clang::FunctionEffectWithCondition::Effect, clang::EffectConditionExpr::getCondition(), clang::FunctionEffect::kind(), and clang::FunctionEffect::oppositeKind().
Referenced by clang::Sema::CheckOverridingFunctionAttributes(), getUnion(), and insert().
operator FunctionEffectsRef()
clang::FunctionEffectSet::operator FunctionEffectsRef () const inline
Definition at line 4938 of file Type.h.
size()
size_t clang::FunctionEffectSet::size () const inline
Definition at line 4931 of file Type.h.
Member Data Documentation
iterator
friend clang::FunctionEffectSet::iterator
Definition at line 4934 of file Type.h.
The documentation for this class was generated from the following files:
include/clang/AST/Type.h
lib/AST/Type.cpp