clang: SYCLFwdDeclEmitter Class Reference
SYCLFwdDeclEmitter Class Reference
Public Member Functions
SYCLFwdDeclEmitter (raw_ostream &OS, const LangOptions &LO)
void Visit (QualType T)
void VisitReferenceType (const ReferenceType *RT)
void Visit (const TemplateArgument &TA)
void VisitPointerType (const PointerType *T)
void VisitTagType (const TagType *T)
void VisitTypeTemplateArgument (const TemplateArgument &TA)
void VisitIntegralTemplateArgument (const TemplateArgument &TA)
void VisitTemplateTemplateArgument (const TemplateArgument &TA)
void VisitPackTemplateArgument (const TemplateArgument &TA)
Public Member Functions inherited from clang::TypeVisitor< SYCLFwdDeclEmitter >
void Visit (const Type *T)
Performs the operation associated with this visitor object.
void VisitType (const Type *)
Method called if ImpClass doesn't provide specific handler for some type class.
Public Member Functions inherited from clang::templateargumentvisitor::Base< Ref, ImplClass, RetTy, ParamTys >
RetTy Visit (REF(TemplateArgument) TA, ParamTys... P)
VISIT_METHOD (Null)
VISIT_METHOD (Type)
VISIT_METHOD (Declaration)
VISIT_METHOD (NullPtr)
VISIT_METHOD (Integral)
VISIT_METHOD (StructuralValue)
VISIT_METHOD (Template)
VISIT_METHOD (TemplateExpansion)
VISIT_METHOD (Expression)
VISIT_METHOD (Pack)
RetTy VisitTemplateArgument (REF(TemplateArgument), ParamTys...)
Detailed Description
Definition at line 4838 of file SemaSYCL.cpp.
Constructor & Destructor Documentation
SYCLFwdDeclEmitter()
SYCLFwdDeclEmitter::SYCLFwdDeclEmitter (raw_ostream & OS, const LangOptions & LO) inline
Definition at line 4917 of file SemaSYCL.cpp.
References clang::PrintingPolicy::adjustForCPlusPlusFwdDecl(), clang::PrintingPolicy::PrintCanonicalTypes, clang::PrintingPolicy::SkipCanonicalizationOfTemplateTypeParms, clang::PrintingPolicy::SuppressFinalSpecifier, clang::PrintingPolicy::SuppressTypedefs, and clang::PrintingPolicy::SuppressUnwrittenScope.
Member Function Documentation
Visit() [1/2]
void SYCLFwdDeclEmitter::Visit (const TemplateArgument & TA) inline
Definition at line 4939 of file SemaSYCL.cpp.
References clang::TemplateArgument::isNull().
Visit() [2/2]
void SYCLFwdDeclEmitter::Visit (QualType T) inline
Definition at line 4927 of file SemaSYCL.cpp.
References clang::T.
Referenced by clang::SYCLIntegrationHeader::emit().
VisitIntegralTemplateArgument()
void SYCLFwdDeclEmitter::VisitIntegralTemplateArgument (const TemplateArgument & TA) inline
Definition at line 4976 of file SemaSYCL.cpp.
References clang::Type::getAs(), clang::TemplateArgument::getIntegralType(), and clang::T.
VisitPackTemplateArgument()
void SYCLFwdDeclEmitter::VisitPackTemplateArgument (const TemplateArgument & TA) inline
Definition at line 5030 of file SemaSYCL.cpp.
References clang::TemplateArgument::getPackAsArray().
VisitPointerType()
void SYCLFwdDeclEmitter::VisitPointerType (const PointerType * T) inline
Definition at line 4945 of file SemaSYCL.cpp.
References clang::Type::getPointeeType(), clang::Type::isPointerType(), and clang::T.
VisitReferenceType()
void SYCLFwdDeclEmitter::VisitReferenceType (const ReferenceType * RT) inline
Definition at line 4933 of file SemaSYCL.cpp.
References clang::ReferenceType::getPointeeType().
VisitTagType()
void SYCLFwdDeclEmitter::VisitTagType (const TagType * T) inline
Definition at line 4953 of file SemaSYCL.cpp.
References clang::T.
VisitTemplateTemplateArgument()
void SYCLFwdDeclEmitter::VisitTemplateTemplateArgument (const TemplateArgument & TA) inline
Definition at line 4982 of file SemaSYCL.cpp.
References clang::TemplateArgument::getAsTemplate(), clang::TemplateName::getAsTemplateDecl(), clang::TemplateDecl::getTemplateParameters(), P, and clang::TemplateParam.
VisitTypeTemplateArgument()
void SYCLFwdDeclEmitter::VisitTypeTemplateArgument (const TemplateArgument & TA) inline
Definition at line 4971 of file SemaSYCL.cpp.
References clang::TemplateArgument::getAsType(), and clang::T.
The documentation for this class was generated from the following file:
lib/Sema/SemaSYCL.cpp