clang: clang::LazyASTUnresolvedSet Class Reference
clang::LazyASTUnresolvedSet Class Reference
An UnresolvedSet-like class that might not have been loaded from the external AST source yet.
#include "clang/AST/ASTUnresolvedSet.h"
Public Member Functions
ASTUnresolvedSet & get (ASTContext &C) const
void reserve (ASTContext &C, unsigned N)
void addLazyDecl (ASTContext &C, uintptr_t ID, AccessSpecifier AS)
Detailed Description
An UnresolvedSet-like class that might not have been loaded from the external AST source yet.
Definition at line 93 of file ASTUnresolvedSet.h.
Member Function Documentation
addLazyDecl()
void clang::LazyASTUnresolvedSet::addLazyDecl (ASTContext & C, uintptr_t ID, AccessSpecifier AS) inline
Definition at line 107 of file ASTUnresolvedSet.h.
References clang::ASTUnresolvedSet::addDecl(), and clang::ASTUnresolvedSet::empty().
Referenced by clang::ASTRecordReader::readUnresolvedSet().
get()
ASTUnresolvedSet& clang::LazyASTUnresolvedSet::get (ASTContext & C) const inline
Definition at line 99 of file ASTUnresolvedSet.h.
reserve()
void clang::LazyASTUnresolvedSet::reserve (ASTContext & C, unsigned N) inline
Definition at line 105 of file ASTUnresolvedSet.h.
References clang::ASTUnresolvedSet::reserve().
Referenced by clang::ASTRecordReader::readUnresolvedSet().
The documentation for this class was generated from the following files:
include/clang/AST/ASTUnresolvedSet.h
lib/AST/DeclCXX.cpp