clang: clang::TemplateName Class Reference
clang::TemplateName Class Reference
Represents a C++ template name within the type system.
#include "clang/AST/TemplateName.h"
Public Types
enum NameKind {
Template, OverloadedTemplate, AssumedTemplate, QualifiedTemplate,
DependentTemplate, SubstTemplateTemplateParm, SubstTemplateTemplateParmPack
}
enum Qualified { Qualified::None, Qualified::AsWritten, Qualified::Fully }
Public Member Functions
TemplateName ()=default
TemplateName (TemplateDecl *Template)
TemplateName (OverloadedTemplateStorage *Storage)
TemplateName (AssumedTemplateStorage *Storage)
TemplateName (SubstTemplateTemplateParmStorage *Storage)
TemplateName (SubstTemplateTemplateParmPackStorage *Storage)
TemplateName (QualifiedTemplateName *Qual)
TemplateName (DependentTemplateName *Dep)
bool isNull () const
Determine whether this template name is NULL.
NameKind getKind () const
TemplateDecl * getAsTemplateDecl () const
Retrieve the underlying template declaration that this template name refers to, if known.
OverloadedTemplateStorage * getAsOverloadedTemplate () const
Retrieve the underlying, overloaded function template declarations that this template name refers to, if known.
AssumedTemplateStorage * getAsAssumedTemplateName () const
Retrieve information on a name that has been assumed to be a template-name in order to permit a call via ADL.
SubstTemplateTemplateParmStorage * getAsSubstTemplateTemplateParm () const
Retrieve the substituted template template parameter, if known.
SubstTemplateTemplateParmPackStorage * getAsSubstTemplateTemplateParmPack () const
Retrieve the substituted template template parameter pack, if known.
QualifiedTemplateName * getAsQualifiedTemplateName () const
Retrieve the underlying qualified template name structure, if any.
DependentTemplateName * getAsDependentTemplateName () const
Retrieve the underlying dependent template name structure, if any.
TemplateName getUnderlying () const
TemplateName getNameToSubstitute () const
Get the template name to substitute when this template name is used as a template template argument.
TemplateNameDependence getDependence () const
bool isDependent () const
Determines whether this is a dependent template name.
bool isInstantiationDependent () const
Determines whether this is a template name that somehow depends on a template parameter.
bool containsUnexpandedParameterPack () const
Determines whether this template name contains an unexpanded parameter pack (for C++0x variadic templates).
void print (raw_ostream &OS, const PrintingPolicy &Policy, Qualified Qual=Qualified::AsWritten) const
Print the template name.
void dump (raw_ostream &OS) const
Debugging aid that dumps the template name.
void dump () const
Debugging aid that dumps the template name to standard error.
void Profile (llvm::FoldingSetNodeID &ID)
void * getAsVoidPointer () const
Retrieve the template name as a void pointer.
Static Public Member Functions
static TemplateName getFromVoidPointer (void *Ptr)
Build a template name from a void pointer.
Detailed Description
Represents a C++ template name within the type system.
A C++ template name refers to a template within the C++ type system. In most cases, a template name is simply a reference to a class template, e.g.
template<typename T> class X { };
X<int> xi;
Here, the 'X' in X<int> is a template name that refers to the declaration of the class template X, above. Template names can also refer to function templates, C++0x template aliases, etc.
Some template names are dependent. For example, consider:
template<typename MetaFun, typename T1, typename T2> struct apply2 {
  typedef typename MetaFun::template apply<T1, T2>::type type;
};
Here, "apply" is treated as a template name within the typename specifier in the typedef. "apply" is a nested template, and can only be understood in the context of
Definition at line 190 of file TemplateName.h.
Member Enumeration Documentation
NameKind
enum clang::TemplateName::NameKind
Enumerator
Template
A single template declaration.
OverloadedTemplate
A set of overloaded template declarations.
AssumedTemplate
An unqualified-id that has been assumed to name a function template that will be found by ADL.
QualifiedTemplate
A qualified template name, where the qualification is kept to describe the source code as written.
DependentTemplate
A dependent template name that has not been resolved to a template (or set of templates).
SubstTemplateTemplateParm
A template template parameter that has been substituted for some other template name.
SubstTemplateTemplateParmPack
A template template parameter pack that has been substituted for a template template argument pack, but has not yet been expanded into individual arguments.
Definition at line 201 of file TemplateName.h.
Qualified
enum clang::TemplateName::Qualified strong
Enumerator
None
AsWritten
Fully
Definition at line 310 of file TemplateName.h.
Constructor & Destructor Documentation
TemplateName() [1/8]
clang::TemplateName::TemplateName () default
Referenced by getFromVoidPointer(), and getNameToSubstitute().
TemplateName() [2/8]
TemplateName::TemplateName (TemplateDecl * Template) explicit
Definition at line 68 of file TemplateName.cpp.
TemplateName() [3/8]
TemplateName::TemplateName (OverloadedTemplateStorage * Storage) explicit
Definition at line 69 of file TemplateName.cpp.
TemplateName() [4/8]
TemplateName::TemplateName (AssumedTemplateStorage * Storage) explicit
Definition at line 71 of file TemplateName.cpp.
TemplateName() [5/8]
TemplateName::TemplateName (SubstTemplateTemplateParmStorage * Storage) explicit
Definition at line 73 of file TemplateName.cpp.
TemplateName() [6/8]
TemplateName::TemplateName (SubstTemplateTemplateParmPackStorage * Storage) explicit
Definition at line 75 of file TemplateName.cpp.
TemplateName() [7/8]
TemplateName::TemplateName (QualifiedTemplateName * Qual) explicit
Definition at line 77 of file TemplateName.cpp.
TemplateName() [8/8]
TemplateName::TemplateName (DependentTemplateName * Dep) explicit
Definition at line 78 of file TemplateName.cpp.
Member Function Documentation
containsUnexpandedParameterPack()
bool TemplateName::containsUnexpandedParameterPack () const
Determines whether this template name contains an unexpanded parameter pack (for C++0x variadic templates).
Definition at line 219 of file TemplateName.cpp.
References getDependence().
Referenced by clang::Sema::ActOnPackExpansion(), and clang::Sema::DiagnoseUnexpandedParameterPack().
dump() [1/2]
LLVM_DUMP_METHOD void TemplateName::dump () const
Debugging aid that dumps the template name to standard error.
Definition at line 291 of file TemplateName.cpp.
dump() [2/2]
void TemplateName::dump (raw_ostream & OS) const
Debugging aid that dumps the template name.
Definition at line 284 of file TemplateName.cpp.
References print().
Referenced by clang::TextNodeDumper::VisitTemplateExpansionTemplateArgument(), clang::TextNodeDumper::VisitTemplateSpecializationType(), and clang::TextNodeDumper::VisitTemplateTemplateArgument().
getAsAssumedTemplateName()
AssumedTemplateStorage * TemplateName::getAsAssumedTemplateName () const
Retrieve information on a name that has been assumed to be a template-name in order to permit a call via ADL.
Definition at line 122 of file TemplateName.cpp.
References clang::UncommonTemplateNameStorage::getAsAssumedTemplateName().
Referenced by clang::ASTImporter::Import(), IsStructurallyEquivalent(), and print().
getAsDependentTemplateName()
DependentTemplateName * TemplateName::getAsDependentTemplateName () const
Retrieve the underlying dependent template name structure, if any.
Definition at line 152 of file TemplateName.cpp.
Referenced by clang::Sema::ActOnTagTemplateIdType(), clang::Sema::CheckTemplateArgument(), clang::ASTContext::getCanonicalTemplateSpecializationType(), getDependence(), clang::ASTContext::getTemplateSpecializationType(), clang::ASTImporter::Import(), IsStructurallyEquivalent(), print(), clang::TreeTransform< KernelBodyTransform >::TransformDependentTemplateSpecializationType(), and clang::RecursiveASTVisitor< CallGraph >::TraverseTemplateName().
getAsOverloadedTemplate()
OverloadedTemplateStorage * TemplateName::getAsOverloadedTemplate () const
Retrieve the underlying, overloaded function template declarations that this template name refers to, if known.
Returns
The set of overloaded function templates that this template name refers to, if known. If the template name does not refer to a specific set of function templates because it is a dependent name or refers to a single template, returns NULL.
Definition at line 114 of file TemplateName.cpp.
References clang::UncommonTemplateNameStorage::getAsOverloadedStorage().
Referenced by clang::ASTImporter::Import(), IsStructurallyEquivalent(), and print().
getAsQualifiedTemplateName()
QualifiedTemplateName * TemplateName::getAsQualifiedTemplateName () const
Retrieve the underlying qualified template name structure, if any.
Definition at line 148 of file TemplateName.cpp.
Referenced by getAsTemplateDecl(), clang::ASTContext::getCanonicalTemplateSpecializationType(), getDependence(), clang::TypeName::getFullyQualifiedTemplateName(), clang::ASTContext::getTemplateSpecializationType(), clang::ASTImporter::Import(), print(), and clang::RecursiveASTVisitor< CallGraph >::TraverseTemplateName().
getAsSubstTemplateTemplateParm()
SubstTemplateTemplateParmStorage * TemplateName::getAsSubstTemplateTemplateParm () const
Retrieve the substituted template template parameter, if known.
Returns
The storage for the substituted template template parameter, if known. Otherwise, returns NULL.
Definition at line 131 of file TemplateName.cpp.
References clang::UncommonTemplateNameStorage::getAsSubstTemplateTemplateParm().
Referenced by getAsTemplateDecl(), getUnderlying(), clang::ASTImporter::Import(), and print().
getAsSubstTemplateTemplateParmPack()
SubstTemplateTemplateParmPackStorage * TemplateName::getAsSubstTemplateTemplateParmPack () const
Retrieve the substituted template template parameter pack, if known.
Returns
The storage for the substituted template template parameter pack, if known. Otherwise, returns NULL.
Definition at line 140 of file TemplateName.cpp.
References clang::UncommonTemplateNameStorage::getAsSubstTemplateTemplateParmPack().
Referenced by clang::Sema::getFullyPackExpandedSize(), clang::ASTImporter::Import(), IsStructurallyEquivalent(), and print().
getAsTemplateDecl()
TemplateDecl * TemplateName::getAsTemplateDecl () const
Retrieve the underlying template declaration that this template name refers to, if known.
Returns
The template declaration that this template name refers to, if any. If the template name does not refer to a specific declaration because it is a dependent name, or if it refers to a set of function templates, returns NULL.
Definition at line 101 of file TemplateName.cpp.
References getAsQualifiedTemplateName(), getAsSubstTemplateTemplateParm(), and Template.
Referenced by clang::Sema::ActOnTagTemplateIdType(), addAssociatedClassesAndNamespaces(), clang::Sema::BuildTypeConstraint(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), GetDeclSpecTypeForDeclarator(), getDependence(), clang::TypeName::getFullyQualifiedTemplateName(), getNameToSubstitute(), clang::ASTContext::getTemplateSpecializationType(), clang::ASTImporter::Import(), isEnableIf(), IsSmallVector(), IsStdVector(), IsStructurallyEquivalent(), SYCLKernelNameTypeVisitor::VisitTemplateTemplateArgument(), SYCLFwdDeclEmitter::VisitTemplateTemplateArgument(), and SYCLKernelNameTypePrinter::VisitTemplateTemplateArgument().
getAsVoidPointer()
void* clang::TemplateName::getAsVoidPointer () const inline
Retrieve the template name as a void pointer.
Definition at line 334 of file TemplateName.h.
Referenced by llvm::PointerLikeTypeTraits< clang::TemplateName >::getAsVoidPointer(), clang::ASTContext::hasSameTemplateName(), isSameTemplateArg(), and clang::SubstTemplateTemplateParmStorage::Profile().
getDependence()
TemplateNameDependence TemplateName::getDependence () const
Definition at line 173 of file TemplateName.cpp.
References getAsDependentTemplateName(), getAsQualifiedTemplateName(), getAsTemplateDecl(), getKind(), clang::XRayInstrKind::None, Template, and clang::toTemplateNameDependence().
Referenced by containsUnexpandedParameterPack(), isDependent(), isInstantiationDependent(), and print().
getFromVoidPointer()
static TemplateName clang::TemplateName::getFromVoidPointer (void * Ptr) inline static
Build a template name from a void pointer.
Definition at line 337 of file TemplateName.h.
References TemplateName().
Referenced by clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), and llvm::PointerLikeTypeTraits< clang::TemplateName >::getFromVoidPointer().
getKind()
TemplateName::NameKind TemplateName::getKind () const
Definition at line 82 of file TemplateName.cpp.
References AssumedTemplate, DependentTemplate, clang::UncommonTemplateNameStorage::getAsAssumedTemplateName(), clang::UncommonTemplateNameStorage::getAsOverloadedStorage(), clang::UncommonTemplateNameStorage::getAsSubstTemplateTemplateParm(), OverloadedTemplate, QualifiedTemplate, SubstTemplateTemplateParm, SubstTemplateTemplateParmPack, and Template.
Referenced by clang::Sema::CheckDeductionGuideDeclarator(), getDependence(), clang::ASTImporter::Import(), and IsStructurallyEquivalent().
getNameToSubstitute()
TemplateName TemplateName::getNameToSubstitute () const
Get the template name to substitute when this template name is used as a template template argument.
This refers to the most recent declaration of the template, including any default template arguments.
Definition at line 156 of file TemplateName.cpp.
References getAsTemplateDecl(), clang::Decl::getFriendObjectKind(), clang::Decl::getMostRecentDecl(), clang::Decl::getPreviousDecl(), and TemplateName().
getUnderlying()
TemplateName clang::TemplateName::getUnderlying () const inline
Definition at line 372 of file TemplateName.h.
References getAsSubstTemplateTemplateParm(), and getUnderlying().
Referenced by getUnderlying().
isDependent()
bool TemplateName::isDependent () const
Determines whether this is a dependent template name.
Definition at line 211 of file TemplateName.cpp.
References getDependence().
Referenced by clang::Sema::DeduceTemplateSpecializationFromInitializer(), and clang::DeducedTemplateSpecializationType::Profile().
isInstantiationDependent()
bool TemplateName::isInstantiationDependent () const
Determines whether this is a template name that somehow depends on a template parameter.
Definition at line 215 of file TemplateName.cpp.
References getDependence().
isNull()
bool TemplateName::isNull () const
Determine whether this template name is NULL.
Definition at line 80 of file TemplateName.cpp.
Referenced by clang::Sema::DiagnoseUnexpandedParameterPack(), clang::Sema::SubstDefaultTemplateArgumentIfAvailable(), clang::TreeTransform< KernelBodyTransform >::TransformTemplateArgument(), and clang::TreeTransform< KernelBodyTransform >::TransformTemplateSpecializationType().
print()
void TemplateName::print (raw_ostream & OS, const PrintingPolicy & Policy, Qualified Qual = Qualified::AsWritten) const
Print the template name.
Parameters
OS the output stream to which the template name will be printed.
Qual print the (Qualified::None) simple name, (Qualified::AsWritten) any written (possibly partial) qualifier, or (Qualified::Fully) the fully qualified name.
Definition at line 223 of file TemplateName.cpp.
References AsWritten, clang::OverloadedTemplateStorage::begin(), clang::PrintingPolicy::CleanUglifiedParameters, Fully, getAsAssumedTemplateName(), getAsDependentTemplateName(), getAsOverloadedTemplate(), getAsQualifiedTemplateName(), getAsSubstTemplateTemplateParm(), getAsSubstTemplateTemplateParmPack(), getDependence(), clang::getOperatorSpelling(), and Template.
Referenced by dump(), clang::operator<<(), clang::TemplateArgument::print(), and clang::JSONNodeDumper::VisitTemplateSpecializationType().
Profile()
void clang::TemplateName::Profile (llvm::FoldingSetNodeID & ID) inline
Definition at line 329 of file TemplateName.h.
Referenced by clang::DeducedTemplateSpecializationType::Profile(), and clang::TemplateSpecializationType::Profile().
The documentation for this class was generated from the following files:
include/clang/AST/TemplateName.h
lib/AST/TemplateName.cpp