clang: clang::NoSanitizeList Class Reference
clang::NoSanitizeList Class Reference
#include "clang/Basic/NoSanitizeList.h"
Public Member Functions
NoSanitizeList (const std::vector< std::string > &NoSanitizeListPaths, SourceManager &SM)
~NoSanitizeList ()
bool containsGlobal (SanitizerMask Mask, StringRef GlobalName, StringRef Category=StringRef()) const
bool containsType (SanitizerMask Mask, StringRef MangledTypeName, StringRef Category=StringRef()) const
bool containsFunction (SanitizerMask Mask, StringRef FunctionName) const
bool containsFile (SanitizerMask Mask, StringRef FileName, StringRef Category=StringRef()) const
bool containsLocation (SanitizerMask Mask, SourceLocation Loc, StringRef Category=StringRef()) const
Detailed Description
Definition at line 29 of file NoSanitizeList.h.
Constructor & Destructor Documentation
NoSanitizeList()
NoSanitizeList::NoSanitizeList (const std::vector< std::string > & NoSanitizeListPaths, SourceManager & SM)
Definition at line 22 of file NoSanitizeList.cpp.
~NoSanitizeList()
NoSanitizeList::~NoSanitizeList () default
Member Function Documentation
containsFile()
bool NoSanitizeList::containsFile (SanitizerMask Mask, StringRef FileName, StringRef Category = StringRef()) const
Definition at line 45 of file NoSanitizeList.cpp.
References Category.
Referenced by containsLocation().
containsFunction()
bool NoSanitizeList::containsFunction (SanitizerMask Mask, StringRef FunctionName) const
Definition at line 40 of file NoSanitizeList.cpp.
containsGlobal()
bool NoSanitizeList::containsGlobal (SanitizerMask Mask, StringRef GlobalName, StringRef Category = StringRef()) const
Definition at line 30 of file NoSanitizeList.cpp.
References Category.
containsLocation()
bool NoSanitizeList::containsLocation (SanitizerMask Mask, SourceLocation Loc, StringRef Category = StringRef()) const
Definition at line 50 of file NoSanitizeList.cpp.
References Category, containsFile(), clang::SourceManager::getFileLoc(), clang::SourceManager::getFilename(), and clang::SourceLocation::isValid().
Referenced by clang::CodeGen::CodeGenModule::isInNoSanitizeList().
containsType()
bool NoSanitizeList::containsType (SanitizerMask Mask, StringRef MangledTypeName, StringRef Category = StringRef()) const
Definition at line 35 of file NoSanitizeList.cpp.
References Category.
Referenced by clang::CodeGen::CodeGenFunction::EmitTypeCheck(), and clang::CodeGen::CodeGenFunction::ShouldEmitVTableTypeCheckedLoad().
The documentation for this class was generated from the following files:
include/clang/Basic/NoSanitizeList.h
lib/Basic/NoSanitizeList.cpp