clang: clang::OMPPriorityClause Class Reference
clang::OMPPriorityClause Class Reference
This represents 'priority' clause in the '#pragma omp ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
OMPPriorityClause (Expr *Priority, Stmt *HelperPriority, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build 'priority' clause.
OMPPriorityClause ()
Build an empty clause.
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Expr * getPriority ()
Return Priority number.
Expr * getPriority () const
Return Priority number.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents 'priority' clause in the '#pragma omp ...' directive.
#pragma omp task priority(n)
In this example directive '#pragma omp teams' has clause 'priority' with single expression 'n'.
Definition at line 6287 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPPriorityClause() [1/2]
clang::OMPPriorityClause::OMPPriorityClause (Expr * Priority, Stmt * HelperPriority, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build 'priority' clause.
Parameters
Priority Expression associated with this clause.
HelperPriority Helper priority for the construct.
CaptureRegion Innermost OpenMP region where expressions in this clause must be captured.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Definition at line 6311 of file OpenMPClause.h.
References clang::OMPClauseWithPreInit::setPreInitStmt().
OMPPriorityClause() [2/2]
clang::OMPPriorityClause::OMPPriorityClause () inline
Build an empty clause.
Definition at line 6320 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPPriorityClause::children () inline
Definition at line 6336 of file OpenMPClause.h.
References Priority.
children() [2/2]
const_child_range clang::OMPPriorityClause::children () const inline
Definition at line 6338 of file OpenMPClause.h.
References Priority.
classof()
static bool clang::OMPPriorityClause::classof (const OMPClause * T) inline static
Definition at line 6348 of file OpenMPClause.h.
References clang::T.
getLParenLoc()
SourceLocation clang::OMPPriorityClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 6328 of file OpenMPClause.h.
getPriority() [1/2]
Expr* clang::OMPPriorityClause::getPriority () inline
Return Priority number.
Definition at line 6331 of file OpenMPClause.h.
References Priority.
getPriority() [2/2]
Expr* clang::OMPPriorityClause::getPriority () const inline
Return Priority number.
Definition at line 6334 of file OpenMPClause.h.
References Priority.
setLParenLoc()
void clang::OMPPriorityClause::setLParenLoc (SourceLocation Loc) inline
Sets the location of '('.
Definition at line 6325 of file OpenMPClause.h.
used_children() [1/2]
OMPClause::child_range OMPPriorityClause::used_children ()
Definition at line 325 of file OpenMPClause.cpp.
References getAddrOfExprAsWritten(), and Priority.
Referenced by used_children().
used_children() [2/2]
const_child_range clang::OMPPriorityClause::used_children () const inline
Definition at line 6343 of file OpenMPClause.h.
References used_children().
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 6288 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp