clang: clang::serialization::GlobalDeclID Class Reference
clang::serialization::GlobalDeclID Class Reference
Wrapper class for DeclID.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
GlobalDeclID ()
GlobalDeclID (DeclID ID)
DeclID get () const
operator DeclID () const
Friends
bool operator== (const GlobalDeclID &LHS, const GlobalDeclID &RHS)
bool operator!= (const GlobalDeclID &LHS, const GlobalDeclID &RHS)
bool operator< (const GlobalDeclID &LHS, const GlobalDeclID &RHS)
bool operator> (const GlobalDeclID &LHS, const GlobalDeclID &RHS)
bool operator<= (const GlobalDeclID &LHS, const GlobalDeclID &RHS)
bool operator>= (const GlobalDeclID &LHS, const GlobalDeclID &RHS)
Detailed Description
Wrapper class for DeclID.
This is helpful to not mix the use of LocalDeclID and GlobalDeclID to improve the type safety.
Definition at line 84 of file ASTBitCodes.h.
Constructor & Destructor Documentation
GlobalDeclID() [1/2]
clang::serialization::GlobalDeclID::GlobalDeclID () inline
Definition at line 86 of file ASTBitCodes.h.
GlobalDeclID() [2/2]
clang::serialization::GlobalDeclID::GlobalDeclID (DeclID ID) inline explicit
Definition at line 87 of file ASTBitCodes.h.
Member Function Documentation
get()
DeclID clang::serialization::GlobalDeclID::get () const inline
Definition at line 89 of file ASTBitCodes.h.
Referenced by llvm::DenseMapInfo< clang::serialization::GlobalDeclID >::getHashValue(), clang::ASTReader::mapGlobalIDToModuleFileGlobalID(), and clang::ASTDeclReader::VisitCXXRecordDeclImpl().
operator DeclID()
clang::serialization::GlobalDeclID::operator DeclID () const inline explicit
Definition at line 91 of file ASTBitCodes.h.
Friends And Related Function Documentation
operator!=
bool operator!= (const GlobalDeclID & LHS, const GlobalDeclID & RHS) friend
Definition at line 96 of file ASTBitCodes.h.
operator<
bool operator< (const GlobalDeclID & LHS, const GlobalDeclID & RHS) friend
Definition at line 100 of file ASTBitCodes.h.
operator<=
bool operator<= (const GlobalDeclID & LHS, const GlobalDeclID & RHS) friend
Definition at line 106 of file ASTBitCodes.h.
operator==
bool operator== (const GlobalDeclID & LHS, const GlobalDeclID & RHS) friend
Definition at line 93 of file ASTBitCodes.h.
operator>
bool operator> (const GlobalDeclID & LHS, const GlobalDeclID & RHS) friend
Definition at line 103 of file ASTBitCodes.h.
operator>=
bool operator>= (const GlobalDeclID & LHS, const GlobalDeclID & RHS) friend
Definition at line 109 of file ASTBitCodes.h.
The documentation for this class was generated from the following file:
include/clang/Serialization/ASTBitCodes.h