clang: clang::BitsUnpacker Class Reference
clang::BitsUnpacker Class Reference
A simple helper class to unpack an integer to bits and consuming the bits in order.
#include "clang/Serialization/ASTReader.h"
Public Member Functions
BitsUnpacker (uint32_t V)
BitsUnpacker (const BitsUnpacker &)=delete
BitsUnpacker (BitsUnpacker &&)=delete
BitsUnpacker operator= (const BitsUnpacker &)=delete
BitsUnpacker operator= (BitsUnpacker &&)=delete
~BitsUnpacker ()=default
void updateValue (uint32_t V)
void advance (uint32_t BitsWidth)
bool getNextBit ()
uint32_t getNextBits (uint32_t Width)
bool canGetNextNBits (uint32_t Width) const
Detailed Description
A simple helper class to unpack an integer to bits and consuming the bits in order.
Definition at line 2441 of file ASTReader.h.
Constructor & Destructor Documentation
BitsUnpacker() [1/3]
clang::BitsUnpacker::BitsUnpacker (uint32_t V) inline
Definition at line 2445 of file ASTReader.h.
References updateValue(), and V.
BitsUnpacker() [2/3]
clang::BitsUnpacker::BitsUnpacker (const BitsUnpacker &) delete
BitsUnpacker() [3/3]
clang::BitsUnpacker::BitsUnpacker (BitsUnpacker &&) delete
~BitsUnpacker()
clang::BitsUnpacker::~BitsUnpacker () default
Member Function Documentation
advance()
void clang::BitsUnpacker::advance (uint32_t BitsWidth) inline
Definition at line 2457 of file ASTReader.h.
canGetNextNBits()
bool clang::BitsUnpacker::canGetNextNBits (uint32_t Width) const inline
Definition at line 2472 of file ASTReader.h.
getNextBit()
bool clang::BitsUnpacker::getNextBit () inline
Definition at line 2459 of file ASTReader.h.
Referenced by clang::ASTDeclReader::VisitDecl(), clang::ASTDeclReader::VisitEnumDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTDeclReader::VisitNamespaceDecl(), clang::ASTDeclReader::VisitParmVarDecl(), clang::ASTDeclReader::VisitRecordDeclImpl(), clang::ASTDeclReader::VisitTagDecl(), and clang::ASTDeclReader::VisitVarDeclImpl().
getNextBits()
uint32_t clang::BitsUnpacker::getNextBits (uint32_t Width) inline
Definition at line 2464 of file ASTReader.h.
References clang::interp::Ret().
Referenced by clang::ASTDeclReader::VisitDecl(), clang::ASTDeclReader::VisitEnumDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTDeclReader::VisitParmVarDecl(), clang::ASTDeclReader::VisitRecordDeclImpl(), clang::ASTDeclReader::VisitTagDecl(), and clang::ASTDeclReader::VisitVarDeclImpl().
operator=() [1/2]
BitsUnpacker clang::BitsUnpacker::operator= (BitsUnpacker &&) delete
operator=() [2/2]
BitsUnpacker clang::BitsUnpacker::operator= (const BitsUnpacker &) delete
updateValue()
void clang::BitsUnpacker::updateValue (uint32_t V) inline
Definition at line 2452 of file ASTReader.h.
References V.
Referenced by BitsUnpacker().
The documentation for this class was generated from the following file:
include/clang/Serialization/ASTReader.h