clang: clang::interp::Function Class Reference
clang::interp::Function Class Reference final
Bytecode function.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Function.h"
Public Types
using ParamDescriptor = std::pair< PrimType, Descriptor * >
using arg_reverse_iterator = SmallVectorImpl< PrimType >::const_reverse_iterator
Range over argument types.
Public Member Functions
unsigned getFrameSize () const
Returns the size of the function's local stack.
unsigned getArgSize () const
Returns the size of the argument stack.
CodePtr getCodeBegin () const
Returns a pointer to the start of the code.
CodePtr getCodeEnd () const
Returns a pointer to the end of the code.
const FunctionDecl * getDecl () const
Returns the original FunctionDecl.
const std::string getName () const
Returns the name of the function decl this code was generated for.
SourceLocation getLoc () const
Returns the location.
ParamDescriptor getParamDescriptor (unsigned Offset) const
Returns a parameter descriptor.
bool hasRVO () const
Checks if the first argument is a RVO pointer.
bool hasNonNullAttr () const
llvm::iterator_range< llvm::SmallVector< Scope, 2 >::const_iterator > scopes () const
Range over the scope blocks.
llvm::iterator_range< arg_reverse_iterator > args_reverse () const
Scope & getScope (unsigned Idx)
Returns a specific scope.
const Scope & getScope (unsigned Idx) const
SourceInfo getSource (CodePtr PC) const
Returns the source information at a given PC.
bool isConstexpr () const
Checks if the function is valid to call in constexpr.
bool isVirtual () const
Checks if the function is virtual.
bool isConstructor () const
Checks if the function is a constructor.
bool isDestructor () const
Checks if the function is a destructor.
const CXXRecordDecl * getParentDecl () const
Returns the parent record decl, if any.
bool isLambdaStaticInvoker () const
Returns whether this function is a lambda static invoker, which we generate custom byte code for.
bool isLambdaCallOperator () const
Returns whether this function is the call operator of a lambda record decl.
bool isFullyCompiled () const
Checks if the function is fully done compiling.
bool hasThisPointer () const
bool hasBody () const
Checks if the function already has a body attached.
bool isDefined () const
Checks if the function is defined.
bool isVariadic () const
unsigned getBuiltinID () const
bool isBuiltin () const
bool isUnevaluatedBuiltin () const
unsigned getNumParams () const
unsigned getNumWrittenParams () const
Returns the number of parameter this function takes when it's called, i.e excluding the instance pointer and the RVO pointer.
unsigned getWrittenArgSize () const
unsigned getParamOffset (unsigned ParamIndex) const
void dump () const
Dumps the disassembled bytecode to llvm::errs().
void dump (llvm::raw_ostream &OS) const
Friends
class Program
class ByteCodeEmitter
Detailed Description
Bytecode function.
Contains links to the bytecode of the function, as well as metadata describing all arguments and stack-local variables.
Calling Convention
When calling a function, all argument values must be on the stack.
If the function has a This pointer (i.e. hasThisPointer() returns true, the argument values need to be preceeded by a Pointer for the This object.
If the function uses Return Value Optimization, the arguments (and potentially the This pointer) need to be preceeded by a Pointer pointing to the location to construct the returned value.
After the function has been called, it will remove all arguments, including RVO and This pointer, from the stack.
Definition at line 77 of file Function.h.
Member Typedef Documentation
arg_reverse_iterator
using clang::interp::Function::arg_reverse_iterator = SmallVectorImpl<PrimType>::const_reverse_iterator
Range over argument types.
Definition at line 121 of file Function.h.
ParamDescriptor
using clang::interp::Function::ParamDescriptor = std::pair<PrimType, Descriptor *>
Definition at line 79 of file Function.h.
Member Function Documentation
args_reverse()
llvm::iterator_range<arg_reverse_iterator> clang::interp::Function::args_reverse () const inline
Definition at line 123 of file Function.h.
Referenced by clang::interp::InterpFrame::popArgs().
dump() [1/2]
LLVM_DUMP_METHOD void Function::dump () const
Dumps the disassembled bytecode to llvm::errs().
Definition at line 60 of file Disasm.cpp.
dump() [2/2]
LLVM_DUMP_METHOD void Function::dump (llvm::raw_ostream & OS) const
Definition at line 62 of file Disasm.cpp.
References getArgSize(), getFrameSize(), getName(), hasRVO(), and hasThisPointer().
getArgSize()
unsigned clang::interp::Function::getArgSize () const inline
Returns the size of the argument stack.
Definition at line 84 of file Function.h.
Referenced by dump().
getBuiltinID()
unsigned clang::interp::Function::getBuiltinID () const inline
Definition at line 181 of file Function.h.
References clang::FunctionDecl::getBuiltinID().
getCodeBegin()
CodePtr clang::interp::Function::getCodeBegin () const inline
Returns a pointer to the start of the code.
Definition at line 87 of file Function.h.
Referenced by clang::interp::InterpFrame::getPC(), and getSource().
getCodeEnd()
CodePtr clang::interp::Function::getCodeEnd () const inline
Returns a pointer to the end of the code.
Definition at line 89 of file Function.h.
Referenced by getSource().
getDecl()
const FunctionDecl* clang::interp::Function::getDecl () const inline
Returns the original FunctionDecl.
Definition at line 92 of file Function.h.
Referenced by clang::interp::InterpFrame::getCallee(), clang::interp::InterpFrame::getExpr(), clang::interp::InterpFrame::getLocation(), clang::interp::InterpFrame::getRange(), clang::interp::InterpFrame::getSource(), and hasNonNullAttr().
getFrameSize()
unsigned clang::interp::Function::getFrameSize () const inline
Returns the size of the function's local stack.
Definition at line 82 of file Function.h.
Referenced by dump().
getLoc()
SourceLocation clang::interp::Function::getLoc () const inline
Returns the location.
Definition at line 104 of file Function.h.
getName()
const std::string clang::interp::Function::getName () const inline
Returns the name of the function decl this code was generated for.
Definition at line 96 of file Function.h.
References clang::NamedDecl::getQualifiedNameAsString().
Referenced by dump().
getNumParams()
unsigned clang::interp::Function::getNumParams () const inline
Definition at line 187 of file Function.h.
Referenced by getNumWrittenParams().
getNumWrittenParams()
unsigned clang::interp::Function::getNumWrittenParams () const inline
Returns the number of parameter this function takes when it's called, i.e excluding the instance pointer and the RVO pointer.
Definition at line 191 of file Function.h.
References getNumParams(), hasRVO(), and hasThisPointer().
getParamDescriptor()
Function::ParamDescriptor Function::getParamDescriptor (unsigned Offset) const
Returns a parameter descriptor.
Definition at line 30 of file Function.cpp.
References Offset.
Referenced by clang::interp::InterpFrame::getParamPointer().
getParamOffset()
unsigned clang::interp::Function::getParamOffset (unsigned ParamIndex) const inline
Definition at line 199 of file Function.h.
getParentDecl()
const CXXRecordDecl* clang::interp::Function::getParentDecl () const inline
Returns the parent record decl, if any.
Definition at line 146 of file Function.h.
References clang::DeclContext::getParent().
getScope() [1/2]
Scope& clang::interp::Function::getScope (unsigned Idx) inline
Returns a specific scope.
Definition at line 128 of file Function.h.
Referenced by clang::interp::InterpFrame::destroy().
getScope() [2/2]
const Scope& clang::interp::Function::getScope (unsigned Idx) const inline
Definition at line 129 of file Function.h.
getSource()
SourceInfo Function::getSource (CodePtr PC) const
Returns the source information at a given PC.
Definition at line 36 of file Function.cpp.
References getCodeBegin(), getCodeEnd(), hasBody(), and Offset.
Referenced by clang::interp::EvalEmitter::getSource(), and clang::interp::InterpState::getSource().
getWrittenArgSize()
unsigned clang::interp::Function::getWrittenArgSize () const inline
Definition at line 195 of file Function.h.
References clang::interp::align(), hasRVO(), hasThisPointer(), clang::interp::primSize(), and clang::interp::PT_Ptr.
hasBody()
bool clang::interp::Function::hasBody () const inline
Checks if the function already has a body attached.
Definition at line 174 of file Function.h.
Referenced by clang::interp::InterpFrame::getExpr(), clang::interp::InterpFrame::getLocation(), clang::interp::InterpFrame::getRange(), getSource(), clang::interp::InterpFrame::getSource(), and clang::interp::EvalEmitter::getSource().
hasNonNullAttr()
bool clang::interp::Function::hasNonNullAttr () const inline
Definition at line 112 of file Function.h.
References getDecl(), and clang::Decl::hasAttr().
hasRVO()
bool clang::interp::Function::hasRVO () const inline
Checks if the first argument is a RVO pointer.
Definition at line 110 of file Function.h.
Referenced by clang::interp::InterpFrame::describe(), dump(), getNumWrittenParams(), getWrittenArgSize(), and clang::interp::ByteCodeExprGen< Emitter >::VisitCXXInheritedCtorInitExpr().
hasThisPointer()
bool clang::interp::Function::hasThisPointer () const inline
Definition at line 171 of file Function.h.
Referenced by clang::interp::InterpFrame::describe(), dump(), getNumWrittenParams(), getWrittenArgSize(), and clang::interp::ByteCodeExprGen< Emitter >::VisitCXXInheritedCtorInitExpr().
isBuiltin()
bool clang::interp::Function::isBuiltin () const inline
Definition at line 183 of file Function.h.
References clang::FunctionDecl::getBuiltinID().
Referenced by clang::interp::InterpFrame::describe().
isConstexpr()
bool clang::interp::Function::isConstexpr () const inline
Checks if the function is valid to call in constexpr.
Definition at line 135 of file Function.h.
References isLambdaStaticInvoker().
isConstructor()
bool clang::interp::Function::isConstructor () const inline
Checks if the function is a constructor.
Definition at line 141 of file Function.h.
isDefined()
bool clang::interp::Function::isDefined () const inline
Checks if the function is defined.
Definition at line 177 of file Function.h.
isDestructor()
bool clang::interp::Function::isDestructor () const inline
Checks if the function is a destructor.
Definition at line 143 of file Function.h.
isFullyCompiled()
bool clang::interp::Function::isFullyCompiled () const inline
Checks if the function is fully done compiling.
Definition at line 169 of file Function.h.
isLambdaCallOperator()
bool clang::interp::Function::isLambdaCallOperator () const inline
Returns whether this function is the call operator of a lambda record decl.
Definition at line 162 of file Function.h.
References clang::isLambdaCallOperator().
isLambdaStaticInvoker()
bool clang::interp::Function::isLambdaStaticInvoker () const inline
Returns whether this function is a lambda static invoker, which we generate custom byte code for.
Definition at line 154 of file Function.h.
Referenced by isConstexpr().
isUnevaluatedBuiltin()
bool clang::interp::Function::isUnevaluatedBuiltin () const inline
Definition at line 185 of file Function.h.
isVariadic()
bool clang::interp::Function::isVariadic () const inline
Definition at line 179 of file Function.h.
isVirtual()
bool Function::isVirtual () const
Checks if the function is virtual.
Definition at line 47 of file Function.cpp.
scopes()
llvm::iterator_range<llvm::SmallVector<Scope, 2>::const_iterator> clang::interp::Function::scopes () const inline
Range over the scope blocks.
Definition at line 116 of file Function.h.
Referenced by clang::interp::InterpFrame::~InterpFrame().
Friends And Related Function Documentation
ByteCodeEmitter
friend class ByteCodeEmitter friend
Definition at line 228 of file Function.h.
Program
friend class Program friend
Definition at line 227 of file Function.h.
The documentation for this class was generated from the following files:
lib/AST/Interp/Function.h
lib/AST/Interp/Disasm.cpp
lib/AST/Interp/Function.cpp