clang: clang::ento::CXXDestructorCall Class Reference
clang::ento::CXXDestructorCall Class Reference
Represents an implicit call to a C++ destructor.
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
Public Member Functions
SourceRange getSourceRange () const override
Returns a source range for the entire call, suitable for outputting in diagnostics.
unsigned getNumArgs () const override
Returns the number of arguments (explicit and implicit).
RuntimeDefinition getRuntimeDefinition () const override
Returns the definition of the function or method that will be called.
SVal getCXXThisVal () const override
Returns the value of the implicit 'this' object.
bool isBaseDestructor () const
Returns true if this is a call to a base class destructor.
Kind getKind () const override
Returns the kind of call this is.
StringRef getKindAsString () const override
Public Member Functions inherited from clang::ento::CXXInstanceCall
virtual const Expr * getCXXThisExpr () const
Returns the expression representing the implicit 'this' object.
const FunctionDecl * getDecl () const override
Returns the declaration of the function or method that will be called.
void getInitialStackFrameContents (const StackFrameContext *CalleeCtx, BindingsTy &Bindings) const override
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
Public Member Functions inherited from clang::ento::AnyFunctionCall
bool argumentsMayEscape () const override
Returns true if any of the arguments are known to escape to long- term storage, even if this method will not modify them.
ArrayRef< ParmVarDecl * > parameters () const override
Return call's formal parameters.
Public Member Functions inherited from clang::ento::CallEvent
CallEvent & operator= (const CallEvent &)=delete
virtual ~CallEvent ()=default
const ProgramStateRef & getState () const
The state in which the call is being evaluated.
const LocationContext * getLocationContext () const
The context in which the call is being evaluated.
virtual const Expr * getOriginExpr () const
Returns the expression whose value will be the result of this call.
bool isInSystemHeader () const
Returns true if the callee is known to be from a system header.
virtual SVal getArgSVal (unsigned Index) const
Returns the value of a given argument at the time of the call.
virtual const Expr * getArgExpr (unsigned Index) const
Returns the expression associated with a given argument.
virtual SourceRange getArgSourceRange (unsigned Index) const
Returns the source range for errors associated with this argument.
QualType getResultType () const
Returns the result type, adjusted for references.
SVal getReturnValue () const
Returns the return value of the call.
bool hasNonNullArgumentsWithType (bool(*Condition)(QualType)) const
Returns true if the type of any of the non-null arguments satisfies the condition.
bool hasNonZeroCallbackArg () const
Returns true if any of the arguments appear to represent callbacks.
bool hasVoidPointerToNonConstArg () const
Returns true if any of the arguments is void*.
bool isGlobalCFunction (StringRef SpecificName=StringRef()) const
Returns true if the callee is an externally-visible function in the top-level namespace, such as malloc.
const IdentifierInfo * getCalleeIdentifier () const
Returns the name of the callee, if its name is a simple identifier.
ProgramPoint getProgramPoint (bool IsPreVisit=false, const ProgramPointTag *Tag=nullptr) const
Returns an appropriate ProgramPoint for this call.
ProgramStateRef invalidateRegions (unsigned BlockCount, ProgramStateRef Orig=nullptr) const
Returns a new state with all argument regions invalidated.
template<typename T >
CallEventRef< T > cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
CallEventRef cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
AnalysisDeclContext * getCalleeAnalysisDeclContext () const
Returns AnalysisDeclContext for the callee stack frame.
const StackFrameContext * getCalleeStackFrame (unsigned BlockCount) const
Returns the callee stack frame.
const ParamVarRegion * getParameterLocation (unsigned Index, unsigned BlockCount) const
Returns memory location for a parameter variable within the callee stack frame.
bool isArgumentConstructedDirectly (unsigned Index) const
Returns true if on the current path, the argument was constructed by calling a C++ constructor over it.
virtual Optional< unsigned > getAdjustedParameterIndex (unsigned ASTArgumentIndex) const
Some calls have parameter numbering mismatched from argument numbering.
virtual unsigned getASTArgumentIndex (unsigned CallArgumentIndex) const
Some call event sub-classes conveniently adjust mismatching AST indices to match parameter indices.
const ConstructionContext * getConstructionContext () const
Returns the construction context of the call, if it is a C++ constructor call or a call of a function returning a C++ class instance.
Optional< SVal > getReturnValueUnderConstruction () const
If the call returns a C++ record type then the region of its return value can be retrieved from its construction context.
param_type_iterator param_type_begin () const
Returns an iterator over the types of the call's formal parameters.
param_type_iterator param_type_end () const
void dump (raw_ostream &Out) const
void dump () const
Static Public Member Functions
static bool classof (const CallEvent *CA)
Static Public Member Functions inherited from clang::ento::CXXInstanceCall
static bool classof (const CallEvent *CA)
Static Public Member Functions inherited from clang::ento::AnyFunctionCall
static bool classof (const CallEvent *CA)
Static Public Member Functions inherited from clang::ento::CallEvent
static bool isCallStmt (const Stmt *S)
Returns true if this is a statement is a function or method call of some kind.
static QualType getDeclaredResultType (const Decl *D)
Returns the result type of a function or method declaration.
static bool isVariadic (const Decl *D)
Returns true if the given decl is known to be variadic.
Protected Types
using DtorDataTy = llvm::PointerIntPair< const MemRegion *, 1, bool >
Protected Types inherited from clang::ento::CallEvent
using ValueList = SmallVectorImpl< SVal >
Protected Member Functions
CXXDestructorCall (const CXXDestructorDecl *DD, const Stmt *Trigger, const MemRegion *Target, bool IsBaseDestructor, ProgramStateRef St, const LocationContext *LCtx)
Creates an implicit destructor.
CXXDestructorCall (const CXXDestructorCall &Other)=default
void cloneTo (void *Dest) const override
Copies this CallEvent, with vtable intact, into a new block of memory.
Protected Member Functions inherited from clang::ento::CXXInstanceCall
CXXInstanceCall (const CallExpr *CE, ProgramStateRef St, const LocationContext *LCtx)
CXXInstanceCall (const FunctionDecl *D, ProgramStateRef St, const LocationContext *LCtx)
CXXInstanceCall (const CXXInstanceCall &Other)=default
void getExtraInvalidatedValues (ValueList &Values, RegionAndSymbolInvalidationTraits *ETraits) const override
Used to specify non-argument regions that will be invalidated as a result of this call.
Protected Member Functions inherited from clang::ento::AnyFunctionCall
AnyFunctionCall (const Expr *E, ProgramStateRef St, const LocationContext *LCtx)
AnyFunctionCall (const Decl *D, ProgramStateRef St, const LocationContext *LCtx)
AnyFunctionCall (const AnyFunctionCall &Other)=default
Protected Member Functions inherited from clang::ento::CallEvent
CallEvent (const Expr *E, ProgramStateRef state, const LocationContext *lctx)
CallEvent (const Decl *D, ProgramStateRef state, const LocationContext *lctx)
CallEvent (const CallEvent &Original)
SVal getSVal (const Stmt *S) const
Get the value of arbitrary expressions at this point in the path.
Friends
class CallEventManager
Additional Inherited Members
Public Types inherited from clang::ento::CallEvent
using Kind = CallEventKind
using FrameBindingTy = std::pair< SVal, SVal >
using BindingsTy = SmallVectorImpl< FrameBindingTy >
using param_type_iterator = llvm::mapped_iterator< ArrayRef< ParmVarDecl * >::iterator, GetTypeFn >
Protected Attributes inherited from clang::ento::CallEvent
const void * Data
SourceLocation Location
Detailed Description
Represents an implicit call to a C++ destructor.
This can occur at the end of a scope (for automatic objects), at the end of a full-expression (for temporaries), or as part of a delete.
Definition at line 782 of file CallEvent.h.
Member Typedef Documentation
DtorDataTy
using clang::ento::CXXDestructorCall::DtorDataTy = llvm::PointerIntPair<const MemRegion *, 1, bool> protected
Definition at line 786 of file CallEvent.h.
Constructor & Destructor Documentation
CXXDestructorCall() [1/2]
clang::ento::CXXDestructorCall::CXXDestructorCall (const CXXDestructorDecl * DD, const Stmt * Trigger, const MemRegion * Target, bool IsBaseDestructor, ProgramStateRef St, const LocationContext * LCtx) inline protected
Creates an implicit destructor.
Parameters
DD The destructor that will be called.
Trigger The statement whose completion causes this destructor call.
Target The object region to be destructed.
St The path-sensitive state at this point in the program.
LCtx The location context at this point in the program.
Definition at line 795 of file CallEvent.h.
References clang::ento::CallEvent::Data, clang::Stmt::getEndLoc(), clang::ento::CallEvent::Location, and clang::Target.
Referenced by cloneTo().
CXXDestructorCall() [2/2]
clang::ento::CXXDestructorCall::CXXDestructorCall (const CXXDestructorCall & Other) protected default
Member Function Documentation
classof()
static bool clang::ento::CXXDestructorCall::classof (const CallEvent * CA) inline static
Definition at line 824 of file CallEvent.h.
References clang::ento::CE_CXXDestructor, and clang::ento::CallEvent::getKind().
cloneTo()
void clang::ento::CXXDestructorCall::cloneTo (void * Dest) const inline override protected virtual
Copies this CallEvent, with vtable intact, into a new block of memory.
Implements clang::ento::CallEvent.
Definition at line 805 of file CallEvent.h.
References CXXDestructorCall().
getCXXThisVal()
SVal CXXDestructorCall::getCXXThisVal () const override virtual
Returns the value of the implicit 'this' object.
Reimplemented from clang::ento::CXXInstanceCall.
Definition at line 885 of file CallEvent.cpp.
References clang::ento::CallEvent::Data.
getKind()
Kind clang::ento::CXXDestructorCall::getKind () const inline override virtual
Returns the kind of call this is.
Implements clang::ento::CallEvent.
Definition at line 821 of file CallEvent.h.
References clang::ento::CE_CXXDestructor.
getKindAsString()
StringRef clang::ento::CXXDestructorCall::getKindAsString () const inline override virtual
Implements clang::ento::CallEvent.
Definition at line 822 of file CallEvent.h.
getNumArgs()
unsigned clang::ento::CXXDestructorCall::getNumArgs () const inline override virtual
Returns the number of arguments (explicit and implicit).
Note that this may be greater than the number of parameters in the callee's declaration, and that it may include arguments not written in the source.
Implements clang::ento::CallEvent.
Definition at line 809 of file CallEvent.h.
getRuntimeDefinition()
RuntimeDefinition CXXDestructorCall::getRuntimeDefinition () const override virtual
Returns the definition of the function or method that will be called.
Reimplemented from clang::ento::CXXInstanceCall.
Definition at line 891 of file CallEvent.cpp.
References clang::ento::AnyFunctionCall::getRuntimeDefinition(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), and isBaseDestructor().
getSourceRange()
SourceRange clang::ento::CXXDestructorCall::getSourceRange () const inline override virtual
Returns a source range for the entire call, suitable for outputting in diagnostics.
Reimplemented from clang::ento::CallEvent.
Definition at line 808 of file CallEvent.h.
References clang::ento::CallEvent::Location.
isBaseDestructor()
bool clang::ento::CXXDestructorCall::isBaseDestructor () const inline
Returns true if this is a call to a base class destructor.
Definition at line 817 of file CallEvent.h.
References clang::ento::CallEvent::Data.
Referenced by getRuntimeDefinition().
Friends And Related Function Documentation
CallEventManager
friend class CallEventManager friend
Definition at line 783 of file CallEvent.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h
lib/StaticAnalyzer/Core/CallEvent.cpp