clang: clang::SemaOpenCL Class Reference
clang::SemaOpenCL Class Reference
#include "clang/Sema/SemaOpenCL.h"
Public Member Functions
SemaOpenCL (Sema &S)
void handleNoSVMAttr (Decl *D, const ParsedAttr &AL)
void handleAccessAttr (Decl *D, const ParsedAttr &AL)
bool checkBuiltinRWPipe (CallExpr *Call)
bool checkBuiltinReserveRWPipe (CallExpr *Call)
bool checkSubgroupExt (CallExpr *Call)
bool checkBuiltinCommitRWPipe (CallExpr *Call)
bool checkBuiltinPipePackets (CallExpr *Call)
bool checkBuiltinToAddr (unsigned BuiltinID, CallExpr *Call)
bool checkBuiltinEnqueueKernel (CallExpr *TheCall)
OpenCL C v2.0, s6.13.17 - Enqueue kernel function contains four different overload formats specified in Table 6.13.17.1.
bool checkBuiltinKernelWorkGroupSize (CallExpr *TheCall)
OpenCL C v2.0, s6.13.17.6 - Check the argument to the get_kernel_work_group_size and get_kernel_preferred_work_group_size_multiple builtin functions.
bool checkBuiltinNDRangeAndBlock (CallExpr *TheCall)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 22 of file SemaOpenCL.h.
Constructor & Destructor Documentation
SemaOpenCL()
clang::SemaOpenCL::SemaOpenCL (Sema & S)
Definition at line 21 of file SemaOpenCL.cpp.
Member Function Documentation
checkBuiltinCommitRWPipe()
bool clang::SemaOpenCL::checkBuiltinCommitRWPipe (CallExpr * Call)
Definition at line 487 of file SemaOpenCL.cpp.
References clang::Sema::checkArgCount(), clang::checkPipeArg(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::ASTContext::OCLReserveIDTy, and clang::SemaBase::SemaRef.
checkBuiltinEnqueueKernel()
bool clang::SemaOpenCL::checkBuiltinEnqueueKernel (CallExpr * TheCall)
OpenCL C v2.0, s6.13.17 - Enqueue kernel function contains four different overload formats specified in Table 6.13.17.1.
int enqueue_kernel(queue_t queue, kernel_enqueue_flags_t flags, const ndrange_t ndrange, void (^block)(void)) int enqueue_kernel(queue_t queue, kernel_enqueue_flags_t flags, const ndrange_t ndrange, uint num_events_in_wait_list, clk_event_t event_wait_list, clk_event_t *event_ret, void (^block)(void)) int enqueue_kernel(queue_t queue, kernel_enqueue_flags_t flags, const ndrange_t ndrange, void (^block)(local void, ...), uint size0, ...) int enqueue_kernel(queue_t queue, kernel_enqueue_flags_t flags, const ndrange_t ndrange, uint num_events_in_wait_list, clk_event_t event_wait_list, clk_event_t *event_ret, void (^block)(local void, ...), uint size0, ...)
Definition at line 219 of file SemaOpenCL.cpp.
checkBuiltinKernelWorkGroupSize()
bool clang::SemaOpenCL::checkBuiltinKernelWorkGroupSize (CallExpr * TheCall)
OpenCL C v2.0, s6.13.17.6 - Check the argument to the get_kernel_work_group_size and get_kernel_preferred_work_group_size_multiple builtin functions.
Definition at line 158 of file SemaOpenCL.cpp.
References clang::Sema::checkArgCount(), clang::checkBlockArgs(), clang::SemaBase::Diag(), clang::CallExpr::getArg(), clang::Stmt::getBeginLoc(), clang::CallExpr::getDirectCallee(), clang::isBlockPointer(), and clang::SemaBase::SemaRef.
checkBuiltinNDRangeAndBlock()
bool clang::SemaOpenCL::checkBuiltinNDRangeAndBlock (CallExpr * TheCall)
Definition at line 134 of file SemaOpenCL.cpp.
References clang::Sema::checkArgCount(), clang::checkBlockArgs(), checkSubgroupExt(), clang::SemaBase::Diag(), clang::CallExpr::getArg(), clang::QualType::getAsString(), clang::Stmt::getBeginLoc(), clang::CallExpr::getDirectCallee(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), clang::isBlockPointer(), and clang::SemaBase::SemaRef.
checkBuiltinPipePackets()
bool clang::SemaOpenCL::checkBuiltinPipePackets (CallExpr * Call)
Definition at line 505 of file SemaOpenCL.cpp.
References clang::Sema::checkArgCount(), clang::SemaBase::Diag(), and clang::SemaBase::SemaRef.
checkBuiltinReserveRWPipe()
bool clang::SemaOpenCL::checkBuiltinReserveRWPipe (CallExpr * Call)
Definition at line 463 of file SemaOpenCL.cpp.
References clang::Sema::checkArgCount(), clang::checkPipeArg(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::SemaBase::SemaRef, and clang::ASTContext::UnsignedIntTy.
checkBuiltinRWPipe()
bool clang::SemaOpenCL::checkBuiltinRWPipe (CallExpr * Call)
Definition at line 413 of file SemaOpenCL.cpp.
References clang::checkPipeArg(), clang::checkPipePacketType(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Type::isIntegerType(), clang::Type::isUnsignedIntegerType(), clang::ASTContext::OCLReserveIDTy, clang::SemaBase::SemaRef, and clang::ASTContext::UnsignedIntTy.
checkBuiltinToAddr()
bool clang::SemaOpenCL::checkBuiltinToAddr (unsigned BuiltinID, CallExpr * Call)
Definition at line 518 of file SemaOpenCL.cpp.
References clang::Sema::checkArgCount(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::opencl_constant, clang::opencl_generic, clang::opencl_global, clang::opencl_local, clang::opencl_private, and clang::SemaBase::SemaRef.
checkSubgroupExt()
bool clang::SemaOpenCL::checkSubgroupExt (CallExpr * Call)
Definition at line 118 of file SemaOpenCL.cpp.
References clang::SemaBase::Diag(), clang::SemaBase::getLangOpts(), clang::Sema::getOpenCLOptions(), clang::OpenCLOptions::isSupported(), and clang::SemaBase::SemaRef.
Referenced by checkBuiltinNDRangeAndBlock().
handleAccessAttr()
void clang::SemaOpenCL::handleAccessAttr (Decl * D, const ParsedAttr & AL)
Definition at line 32 of file SemaOpenCL.cpp.
References D, clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::AttributeCommonInfo::getAttrName(), clang::SemaBase::getLangOpts(), clang::AttributeCommonInfo::getLoc(), clang::IdentifierInfo::getName(), clang::LangOptions::getOpenCLCompatibleVersion(), clang::Sema::getOpenCLOptions(), clang::AttributeCommonInfo::getRange(), clang::ParsedAttr::getSemanticSpelling(), clang::OpenCLOptions::isSupported(), and clang::SemaBase::SemaRef.
handleNoSVMAttr()
void clang::SemaOpenCL::handleNoSVMAttr (Decl * D, const ParsedAttr & AL)
Definition at line 23 of file SemaOpenCL.cpp.
References clang::SemaBase::Diag(), clang::SemaBase::getLangOpts(), clang::AttributeCommonInfo::getLoc(), and clang::LangOptions::getOpenCLVersionString().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaOpenCL.h
lib/Sema/SemaOpenCL.cpp