clang: clang::ento::AllocaRegion Class Reference
clang::ento::AllocaRegion Class Reference
AllocaRegion - A region that represents an untyped blob of bytes created by a call to 'alloca'.
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
const Expr * getExpr () const
bool isBoundable () const override
void Profile (llvm::FoldingSetNodeID &ID) const override
void dumpToStream (raw_ostream &os) const override
Public Member Functions inherited from clang::ento::SubRegion
const MemRegion * getSuperRegion () const
MemRegionManager & getMemRegionManager () const override
bool isSubRegionOf (const MemRegion *R) const override
Check if the region is a subregion of the given region.
Public Member Functions inherited from clang::ento::MemRegion
ASTContext & getContext () const
const MemSpaceRegion * getMemorySpace () const
const MemRegion * getBaseRegion () const
const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasGlobalsOrParametersStorage () const
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
virtual bool canPrintPrettyAsExpr () const
Returns true if this region's textual representation can be used as part of a larger expression.
virtual void printPrettyAsExpr (raw_ostream &os) const
Print the region as expression.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
const RegionTy * castAs () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Static Public Member Functions
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::SubRegion
static bool classof (const MemRegion *R)
Friends
class MemRegionManager
Additional Inherited Members
Public Types inherited from clang::ento::MemRegion
enum Kind
Protected Member Functions inherited from clang::ento::SubRegion
SubRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::MemRegion
MemRegion (Kind k)
virtual ~MemRegion ()
Protected Attributes inherited from clang::ento::SubRegion
const MemRegion * superRegion
Detailed Description
AllocaRegion - A region that represents an untyped blob of bytes created by a call to 'alloca'.
Definition at line 466 of file MemRegion.h.
Member Function Documentation
classof()
static bool clang::ento::AllocaRegion::classof (const MemRegion * R) inline static
Definition at line 492 of file MemRegion.h.
References clang::ento::MemRegion::getKind().
dumpToStream()
void AllocaRegion::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::MemRegion.
Definition at line 454 of file MemRegion.cpp.
References clang::ento::MemRegion::getContext(), and clang::Stmt::getID().
getExpr()
const Expr* clang::ento::AllocaRegion::getExpr () const inline
Definition at line 484 of file MemRegion.h.
Referenced by clang::ento::SValExplainer::VisitAllocaRegion().
isBoundable()
bool clang::ento::AllocaRegion::isBoundable () const inline override virtual
Reimplemented from clang::ento::MemRegion.
Definition at line 486 of file MemRegion.h.
Profile()
void AllocaRegion::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Implements clang::ento::MemRegion.
Definition at line 251 of file MemRegion.cpp.
References clang::ento::SubRegion::superRegion.
Friends And Related Function Documentation
MemRegionManager
friend class MemRegionManager friend
Definition at line 467 of file MemRegion.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp