clang: clang::TestModuleFileExtension Class Reference
clang::TestModuleFileExtension Class Reference
A module file extension used for testing purposes.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Frontend/TestModuleFileExtension.h"
Public Member Functions
TestModuleFileExtension (StringRef BlockName, unsigned MajorVersion, unsigned MinorVersion, bool Hashed, StringRef UserInfo)
~TestModuleFileExtension () override
ModuleFileExtensionMetadata getExtensionMetadata () const override
void hashExtension (ExtensionHashBuilder &HBuilder) const override
std::unique_ptr< ModuleFileExtensionWriter > createExtensionWriter (ASTWriter &Writer) override
std::unique_ptr< ModuleFileExtensionReader > createExtensionReader (const ModuleFileExtensionMetadata &Metadata, ASTReader &Reader, serialization::ModuleFile &Mod, const llvm::BitstreamCursor &Stream) override
std::string str () const
Static Public Attributes
static char ID = 0
Detailed Description
A module file extension used for testing purposes.
Definition at line 20 of file TestModuleFileExtension.h.
Constructor & Destructor Documentation
TestModuleFileExtension()
clang::TestModuleFileExtension::TestModuleFileExtension (StringRef BlockName, unsigned MajorVersion, unsigned MinorVersion, bool Hashed, StringRef UserInfo) inline
Definition at line 49 of file TestModuleFileExtension.h.
~TestModuleFileExtension()
TestModuleFileExtension::~TestModuleFileExtension () override
Definition at line 89 of file TestModuleFileExtension.cpp.
Member Function Documentation
createExtensionReader()
std::unique_ptr< ModuleFileExtensionReader > TestModuleFileExtension::createExtensionReader (const ModuleFileExtensionMetadata & Metadata, ASTReader & Reader, serialization::ModuleFile & Mod, const llvm::BitstreamCursor & Stream) override
Definition at line 112 of file TestModuleFileExtension.cpp.
References clang::ModuleFileExtensionMetadata::BlockName, clang::ASTReader::getDiags(), clang::serialization::ModuleFile::ImportLoc, clang::ModuleFileExtensionMetadata::MajorVersion, clang::ModuleFileExtensionMetadata::MinorVersion, and clang::DiagnosticsEngine::Report().
createExtensionWriter()
std::unique_ptr< ModuleFileExtensionWriter > TestModuleFileExtension::createExtensionWriter (ASTWriter & Writer) override
Definition at line 107 of file TestModuleFileExtension.cpp.
getExtensionMetadata()
ModuleFileExtensionMetadata TestModuleFileExtension::getExtensionMetadata () const override
Definition at line 92 of file TestModuleFileExtension.cpp.
hashExtension()
void TestModuleFileExtension::hashExtension (ExtensionHashBuilder & HBuilder) const override
Definition at line 96 of file TestModuleFileExtension.cpp.
str()
std::string TestModuleFileExtension::str () const
Definition at line 131 of file TestModuleFileExtension.cpp.
References string().
Member Data Documentation
ID
char TestModuleFileExtension::ID = 0 static
Definition at line 47 of file TestModuleFileExtension.h.
The documentation for this class was generated from the following files:
lib/Frontend/TestModuleFileExtension.h
lib/Frontend/TestModuleFileExtension.cpp