clang: clang::ento::BugSuppression Class Reference
clang::ento::BugSuppression Class Reference
#include "clang/StaticAnalyzer/Core/BugReporter/BugSuppression.h"
Public Types
using DiagnosticIdentifierList = llvm::ArrayRef< llvm::StringRef >
Public Member Functions
BugSuppression (const ASTContext &ACtx)
bool isSuppressed (const BugReport &)
Return true if the given bug report was explicitly suppressed by the user.
bool isSuppressed (const PathDiagnosticLocation &Location, const Decl *DeclWithIssue, DiagnosticIdentifierList DiagnosticIdentification)
Return true if the bug reported at the given location was explicitly suppressed by the user.
Detailed Description
Definition at line 29 of file BugSuppression.h.
Member Typedef Documentation
DiagnosticIdentifierList
using clang::ento::BugSuppression::DiagnosticIdentifierList = llvm::ArrayRef<llvm::StringRef>
Definition at line 33 of file BugSuppression.h.
Constructor & Destructor Documentation
BugSuppression()
clang::ento::BugSuppression::BugSuppression (const ASTContext & ACtx) inline explicit
Definition at line 31 of file BugSuppression.h.
Member Function Documentation
isSuppressed() [1/2]
bool BugSuppression::isSuppressed (const BugReport & R)
Return true if the given bug report was explicitly suppressed by the user.
Definition at line 129 of file BugSuppression.cpp.
References clang::ento::BugReport::getDeclWithIssue(), clang::ento::BugReport::getLocation(), and clang::ento::BugReport::getUniqueingLocation().
Referenced by clang::ento::BugReporter::emitReport().
isSuppressed() [2/2]
bool BugSuppression::isSuppressed (const PathDiagnosticLocation & Location, const Decl * DeclWithIssue, DiagnosticIdentifierList DiagnosticIdentification)
Return true if the bug reported at the given location was explicitly suppressed by the user.
Definition at line 138 of file BugSuppression.cpp.
References clang::ento::PathDiagnosticLocation::asRange(), clang::Decl::getLexicalDeclContext(), clang::ento::PathDiagnosticLocation::getManager(), clang::ASTContext::getTranslationUnitDecl(), clang::initialize(), clang::ento::PathDiagnosticLocation::isValid(), Parent, and SM.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugSuppression.h
lib/StaticAnalyzer/Core/BugSuppression.cpp