clang: clang::OMPAlignedClause Class Reference
clang::OMPAlignedClause Class Reference final
This represents clause 'aligned' in the '#pragma omp ...' directives.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
void setColonLoc (SourceLocation Loc)
Sets the location of ':'.
SourceLocation getColonLoc () const
Returns the location of ':'.
Expr * getAlignment ()
Returns alignment.
const Expr * getAlignment () const
Returns alignment.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPVarListClause< OMPAlignedClause >
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_const_iterator varlist_begin () const
varlist_iterator varlist_end ()
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPAlignedClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, ArrayRef< Expr * > VL, Expr *A)
Creates clause with a list of variables VL and alignment A.
static OMPAlignedClause * CreateEmpty (const ASTContext &C, unsigned NumVars)
Creates an empty clause with the place for NumVars variables.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPVarListClause< OMPAlignedClause >
using varlist_iterator = MutableArrayRef< Expr * >::iterator
using varlist_const_iterator = ArrayRef< const Expr * >::iterator
using varlist_range = llvm::iterator_range< varlist_iterator >
using varlist_const_range = llvm::iterator_range< varlist_const_iterator >
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPVarListClause< OMPAlignedClause >
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents clause 'aligned' in the '#pragma omp ...' directives.
#pragma omp simd aligned(a,b : 8)
In this example directive '#pragma omp simd' has clause 'aligned' with variables 'a', 'b' and alignment '8'.
Definition at line 4317 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPAlignedClause::children () inline
Definition at line 4386 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPAlignedClause >::varlist_begin(), and clang::OMPVarListClause< OMPAlignedClause >::varlist_end().
Referenced by children().
children() [2/2]
const_child_range clang::OMPAlignedClause::children () const inline
Definition at line 4391 of file OpenMPClause.h.
References children().
classof()
static bool clang::OMPAlignedClause::classof (const OMPClause * T) inline static
Definition at line 4403 of file OpenMPClause.h.
References clang::T.
Create()
OMPAlignedClause * OMPAlignedClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, ArrayRef< Expr * > VL, Expr * A) static
Creates clause with a list of variables VL and alignment A.
Parameters
C AST Context.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
ColonLoc Location of ':'.
EndLoc Ending location of the clause.
VL List of references to the variables.
A Alignment.
Definition at line 633 of file OpenMPClause.cpp.
References clang::OMPVarListClause< T >::setVarRefs().
Referenced by clang::SemaOpenMP::ActOnOpenMPAlignedClause().
CreateEmpty()
OMPAlignedClause * OMPAlignedClause::CreateEmpty (const ASTContext & C, unsigned NumVars) static
Creates an empty clause with the place for NumVars variables.
Parameters
C AST context.
NumVars Number of variables.
Definition at line 644 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
getAlignment() [1/2]
Expr* clang::OMPAlignedClause::getAlignment () inline
Returns alignment.
Definition at line 4381 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPAlignedClause >::varlist_end().
getAlignment() [2/2]
const Expr* clang::OMPAlignedClause::getAlignment () const inline
Returns alignment.
Definition at line 4384 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPAlignedClause >::varlist_end().
getColonLoc()
SourceLocation clang::OMPAlignedClause::getColonLoc () const inline
Returns the location of ':'.
Definition at line 4378 of file OpenMPClause.h.
setColonLoc()
void clang::OMPAlignedClause::setColonLoc (SourceLocation Loc) inline
Sets the location of ':'.
Definition at line 4375 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPAlignedClause::used_children () inline
Definition at line 4396 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPAlignedClause::used_children () const inline
Definition at line 4399 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 4320 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp