clang: clang::OMPSizesClause Class Reference
clang::OMPSizesClause Class Reference final
This represents the 'sizes' clause in the '#pragma omp tile' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
unsigned getNumSizes () const
Returns the number of list items.
MutableArrayRef< Expr * > getSizesRefs ()
Returns the tile size expressions.
ArrayRef< Expr * > getSizesRefs () const
void setSizesRefs (ArrayRef< Expr * > VL)
Sets the tile size expressions.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPSizesClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< Expr * > Sizes)
Build a 'sizes' AST node.
static OMPSizesClause * CreateEmpty (const ASTContext &C, unsigned NumSizes)
Build an empty 'sizes' AST node for deserialization.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
class llvm::TrailingObjects< OMPSizesClause, Expr * >
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents the 'sizes' clause in the '#pragma omp tile' directive.
#pragma omp tile sizes(5,5)
for (int i = 0; i < 64; ++i)
  for (int j = 0; j < 64; ++j)
Definition at line 880 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPSizesClause::children () inline
Definition at line 944 of file OpenMPClause.h.
References getSizesRefs().
children() [2/2]
const_child_range clang::OMPSizesClause::children () const inline
Definition at line 949 of file OpenMPClause.h.
References getSizesRefs().
classof()
static bool clang::OMPSizesClause::classof (const OMPClause * T) inline static
Definition at line 962 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
Create()
OMPSizesClause * OMPSizesClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< Expr * > Sizes) static
Build a 'sizes' AST node.
Parameters
C Context of the AST.
StartLoc Location of the 'sizes' identifier.
LParenLoc Location of '('.
EndLoc Location of ')'.
Sizes Content of the clause.
Definition at line 939 of file OpenMPClause.cpp.
References clang::OMPClause::setLocEnd(), clang::OMPClause::setLocStart(), setLParenLoc(), and setSizesRefs().
Referenced by clang::Sema::ActOnOpenMPSizesClause().
CreateEmpty()
OMPSizesClause * OMPSizesClause::CreateEmpty (const ASTContext & C, unsigned NumSizes) static
Build an empty 'sizes' AST node for deserialization.
Parameters
C Context of the AST.
NumSizes Number of items in the clause.
Definition at line 952 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
getLParenLoc()
SourceLocation clang::OMPSizesClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 919 of file OpenMPClause.h.
getNumSizes()
unsigned clang::OMPSizesClause::getNumSizes () const inline
Returns the number of list items.
Definition at line 922 of file OpenMPClause.h.
Referenced by clang::Sema::ActOnOpenMPTileDirective().
getSizesRefs() [1/2]
MutableArrayRef<Expr *> clang::OMPSizesClause::getSizesRefs () inline
Returns the tile size expressions.
Definition at line 925 of file OpenMPClause.h.
Referenced by children().
getSizesRefs() [2/2]
ArrayRef<Expr *> clang::OMPSizesClause::getSizesRefs () const inline
Definition at line 930 of file OpenMPClause.h.
setLParenLoc()
void clang::OMPSizesClause::setLParenLoc (SourceLocation Loc) inline
Sets the location of '('.
Definition at line 916 of file OpenMPClause.h.
Referenced by Create().
setSizesRefs()
void clang::OMPSizesClause::setSizesRefs (ArrayRef< Expr * > VL) inline
Sets the tile size expressions.
Definition at line 937 of file OpenMPClause.h.
Referenced by Create().
used_children() [1/2]
child_range clang::OMPSizesClause::used_children () inline
Definition at line 955 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPSizesClause::used_children () const inline
Definition at line 958 of file OpenMPClause.h.
Friends And Related Function Documentation
llvm::TrailingObjects< OMPSizesClause, Expr * >
friend class llvm::TrailingObjects< OMPSizesClause, Expr * > friend
Definition at line 884 of file OpenMPClause.h.
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 883 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp