clang: clang::NSAPI Class Reference
clang::NSAPI Class Reference
#include "clang/AST/NSAPI.h"
Public Types
enum NSClassIdKindKind {
ClassId_NSObject, ClassId_NSString, ClassId_NSArray, ClassId_NSMutableArray,
ClassId_NSDictionary, ClassId_NSMutableDictionary, ClassId_NSNumber, ClassId_NSMutableSet,
ClassId_NSMutableOrderedSet, ClassId_NSValue
}
enum NSStringMethodKind {
NSStr_stringWithString, NSStr_stringWithUTF8String, NSStr_stringWithCStringEncoding, NSStr_stringWithCString,
NSStr_initWithString, NSStr_initWithUTF8String
}
enum NSArrayMethodKind {
NSArr_array, NSArr_arrayWithArray, NSArr_arrayWithObject, NSArr_arrayWithObjects,
NSArr_arrayWithObjectsCount, NSArr_initWithArray, NSArr_initWithObjects, NSArr_objectAtIndex,
NSMutableArr_replaceObjectAtIndex, NSMutableArr_addObject, NSMutableArr_insertObjectAtIndex, NSMutableArr_setObjectAtIndexedSubscript
}
Enumerates the NSArray/NSMutableArray methods used to generate literals and to apply some checks.
enum NSDictionaryMethodKind {
NSDict_dictionary, NSDict_dictionaryWithDictionary, NSDict_dictionaryWithObjectForKey, NSDict_dictionaryWithObjectsForKeys,
NSDict_dictionaryWithObjectsForKeysCount, NSDict_dictionaryWithObjectsAndKeys, NSDict_initWithDictionary, NSDict_initWithObjectsAndKeys,
NSDict_initWithObjectsForKeys, NSDict_objectForKey, NSMutableDict_setObjectForKey, NSMutableDict_setObjectForKeyedSubscript,
NSMutableDict_setValueForKey
}
Enumerates the NSDictionary/NSMutableDictionary methods used to generate literals and to apply some checks.
enum NSSetMethodKind {
NSMutableSet_addObject, NSOrderedSet_insertObjectAtIndex, NSOrderedSet_setObjectAtIndex, NSOrderedSet_setObjectAtIndexedSubscript,
NSOrderedSet_replaceObjectAtIndexWithObject
}
Enumerates the NSMutableSet/NSOrderedSet methods used to apply some checks.
enum NSNumberLiteralMethodKind {
NSNumberWithChar, NSNumberWithUnsignedChar, NSNumberWithShort, NSNumberWithUnsignedShort,
NSNumberWithInt, NSNumberWithUnsignedInt, NSNumberWithLong, NSNumberWithUnsignedLong,
NSNumberWithLongLong, NSNumberWithUnsignedLongLong, NSNumberWithFloat, NSNumberWithDouble,
NSNumberWithBool, NSNumberWithInteger, NSNumberWithUnsignedInteger
}
Enumerates the NSNumber methods used to generate literals.
Public Member Functions
NSAPI (ASTContext &Ctx)
ASTContext & getASTContext () const
IdentifierInfo * getNSClassId (NSClassIdKindKind K) const
Selector getNSStringSelector (NSStringMethodKind MK) const
The Objective-C NSString selectors.
bool isNSUTF8StringEncodingConstant (const Expr *E) const
Returns true if the expression.
bool isNSASCIIStringEncodingConstant (const Expr *E) const
Returns true if the expression.
Selector getNSArraySelector (NSArrayMethodKind MK) const
The Objective-C NSArray selectors.
Optional< NSArrayMethodKind > getNSArrayMethodKind (Selector Sel)
Return NSArrayMethodKind if Sel is such a selector.
Selector getNSDictionarySelector (NSDictionaryMethodKind MK) const
The Objective-C NSDictionary selectors.
Optional< NSDictionaryMethodKind > getNSDictionaryMethodKind (Selector Sel)
Return NSDictionaryMethodKind if Sel is such a selector.
Selector getNSSetSelector (NSSetMethodKind MK) const
The Objective-C NSSet selectors.
Optional< NSSetMethodKind > getNSSetMethodKind (Selector Sel)
Return NSSetMethodKind if Sel is such a selector.
Selector getObjectForKeyedSubscriptSelector () const
Returns selector for "objectForKeyedSubscript:".
Selector getObjectAtIndexedSubscriptSelector () const
Returns selector for "objectAtIndexedSubscript:".
Selector getSetObjectForKeyedSubscriptSelector () const
Returns selector for "setObject:forKeyedSubscript".
Selector getSetObjectAtIndexedSubscriptSelector () const
Returns selector for "setObject:atIndexedSubscript".
Selector getIsEqualSelector () const
Returns selector for "isEqual:".
Selector getNewSelector () const
Selector getInitSelector () const
Selector getNSNumberLiteralSelector (NSNumberLiteralMethodKind MK, bool Instance) const
The Objective-C NSNumber selectors used to create NSNumber literals.
bool isNSNumberLiteralSelector (NSNumberLiteralMethodKind MK, Selector Sel) const
Optional< NSNumberLiteralMethodKind > getNSNumberLiteralMethodKind (Selector Sel) const
Return NSNumberLiteralMethodKind if Sel is such a selector.
Optional< NSNumberLiteralMethodKind > getNSNumberFactoryMethodKind (QualType T) const
Determine the appropriate NSNumber factory method kind for a literal of the given type.
bool isObjCBOOLType (QualType T) const
Returns true if.
bool isObjCNSIntegerType (QualType T) const
Returns true if.
bool isObjCNSUIntegerType (QualType T) const
Returns true if.
StringRef GetNSIntegralKind (QualType T) const
Returns one of NSIntegral typedef names if.
bool isMacroDefined (StringRef Id) const
Returns true if Id is currently defined as a macro.
bool isSubclassOfNSClass (ObjCInterfaceDecl *InterfaceDecl, NSClassIdKindKind NSClassKind) const
Returns true if InterfaceDecl is subclass of NSClassKind.
Static Public Attributes
static const unsigned NumClassIds = 10
static const unsigned NumNSStringMethods = 6
static const unsigned NumNSArrayMethods = 12
static const unsigned NumNSDictionaryMethods = 13
static const unsigned NumNSSetMethods = 5
static const unsigned NumNSNumberLiteralMethods = 15
Detailed Description
Definition at line 23 of file NSAPI.h.
Member Enumeration Documentation
NSArrayMethodKind
enum clang::NSAPI::NSArrayMethodKind
Enumerates the NSArray/NSMutableArray methods used to generate literals and to apply some checks.
Enumerator
NSArr_array
NSArr_arrayWithArray
NSArr_arrayWithObject
NSArr_arrayWithObjects
NSArr_arrayWithObjectsCount
NSArr_initWithArray
NSArr_initWithObjects
NSArr_objectAtIndex
NSMutableArr_replaceObjectAtIndex
NSMutableArr_addObject
NSMutableArr_insertObjectAtIndex
NSMutableArr_setObjectAtIndexedSubscript
Definition at line 72 of file NSAPI.h.
NSClassIdKindKind
enum clang::NSAPI::NSClassIdKindKind
Enumerator
ClassId_NSObject
ClassId_NSString
ClassId_NSArray
ClassId_NSMutableArray
ClassId_NSDictionary
ClassId_NSMutableDictionary
ClassId_NSNumber
ClassId_NSMutableSet
ClassId_NSMutableOrderedSet
ClassId_NSValue
Definition at line 29 of file NSAPI.h.
NSDictionaryMethodKind
enum clang::NSAPI::NSDictionaryMethodKind
Enumerates the NSDictionary/NSMutableDictionary methods used to generate literals and to apply some checks.
Enumerator
NSDict_dictionary
NSDict_dictionaryWithDictionary
NSDict_dictionaryWithObjectForKey
NSDict_dictionaryWithObjectsForKeys
NSDict_dictionaryWithObjectsForKeysCount
NSDict_dictionaryWithObjectsAndKeys
NSDict_initWithDictionary
NSDict_initWithObjectsAndKeys
NSDict_initWithObjectsForKeys
NSDict_objectForKey
NSMutableDict_setObjectForKey
NSMutableDict_setObjectForKeyedSubscript
NSMutableDict_setValueForKey
Definition at line 96 of file NSAPI.h.
NSNumberLiteralMethodKind
enum clang::NSAPI::NSNumberLiteralMethodKind
Enumerates the NSNumber methods used to generate literals.
Enumerator
NSNumberWithChar
NSNumberWithUnsignedChar
NSNumberWithShort
NSNumberWithUnsignedShort
NSNumberWithInt
NSNumberWithUnsignedInt
NSNumberWithLong
NSNumberWithUnsignedLong
NSNumberWithLongLong
NSNumberWithUnsignedLongLong
NSNumberWithFloat
NSNumberWithDouble
NSNumberWithBool
NSNumberWithInteger
NSNumberWithUnsignedInteger
Definition at line 174 of file NSAPI.h.
NSSetMethodKind
enum clang::NSAPI::NSSetMethodKind
Enumerates the NSMutableSet/NSOrderedSet methods used to apply some checks.
Enumerator
NSMutableSet_addObject
NSOrderedSet_insertObjectAtIndex
NSOrderedSet_setObjectAtIndex
NSOrderedSet_setObjectAtIndexedSubscript
NSOrderedSet_replaceObjectAtIndexWithObject
Definition at line 121 of file NSAPI.h.
NSStringMethodKind
enum clang::NSAPI::NSStringMethodKind
Enumerator
NSStr_stringWithString
NSStr_stringWithUTF8String
NSStr_stringWithCStringEncoding
NSStr_stringWithCString
NSStr_initWithString
NSStr_initWithUTF8String
Definition at line 43 of file NSAPI.h.
Constructor & Destructor Documentation
NSAPI()
NSAPI::NSAPI (ASTContext & Ctx) explicit
Definition at line 17 of file NSAPI.cpp.
Member Function Documentation
getASTContext()
ASTContext& clang::NSAPI::getASTContext () const inline
Definition at line 27 of file NSAPI.h.
Referenced by doRewriteToUTF8StringBoxedExpressionHelper(), getNSArrayObjects(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToArrayLiteral(), rewriteToArraySubscriptGet(), rewriteToArraySubscriptSet(), rewriteToDictionaryLiteral(), rewriteToDictionarySubscriptGet(), rewriteToDictionarySubscriptSet(), rewriteToNSEnumDecl(), rewriteToNumberLiteral(), rewriteToNumericBoxedExpression(), clang::edit::rewriteToObjCLiteralSyntax(), rewriteToObjCProperty(), clang::edit::rewriteToObjCSubscriptSyntax(), and shouldNotRewriteImmediateMessageArgs().
getInitSelector()
Selector clang::NSAPI::getInitSelector () const inline
Definition at line 169 of file NSAPI.h.
getIsEqualSelector()
Selector clang::NSAPI::getIsEqualSelector () const inline
Returns selector for "isEqual:".
Definition at line 161 of file NSAPI.h.
getNewSelector()
Selector clang::NSAPI::getNewSelector () const inline
Definition at line 165 of file NSAPI.h.
getNSArrayMethodKind()
Optional< NSAPI::NSArrayMethodKind > NSAPI::getNSArrayMethodKind (Selector Sel)
Return NSArrayMethodKind if Sel is such a selector.
Definition at line 145 of file NSAPI.cpp.
References getNSArraySelector(), and NumNSArrayMethods.
getNSArraySelector()
Selector NSAPI::getNSArraySelector (NSArrayMethodKind MK) const
The Objective-C NSArray selectors.
Definition at line 78 of file NSAPI.cpp.
References clang::IdentifierTable::get(), clang::SelectorTable::getNullarySelector(), clang::SelectorTable::getSelector(), clang::SelectorTable::getUnarySelector(), clang::ASTContext::Idents, NSArr_array, NSArr_arrayWithArray, NSArr_arrayWithObject, NSArr_arrayWithObjects, NSArr_arrayWithObjectsCount, NSArr_initWithArray, NSArr_initWithObjects, NSArr_objectAtIndex, NSMutableArr_addObject, NSMutableArr_insertObjectAtIndex, NSMutableArr_replaceObjectAtIndex, NSMutableArr_setObjectAtIndexedSubscript, and clang::ASTContext::Selectors.
Referenced by getNSArrayMethodKind(), getNSArrayObjects(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToArrayLiteral(), and clang::edit::rewriteToObjCSubscriptSyntax().
getNSClassId()
IdentifierInfo * NSAPI::getNSClassId (NSClassIdKindKind K) const
Definition at line 22 of file NSAPI.cpp.
References clang::IdentifierTable::get(), clang::ASTContext::Idents, and NumClassIds.
Referenced by getNSArrayObjects(), isSubclassOfNSClass(), clang::edit::rewriteObjCRedundantCallWithLiteral(), clang::edit::rewriteToObjCLiteralSyntax(), and shouldNotRewriteImmediateMessageArgs().
getNSDictionaryMethodKind()
Optional< NSAPI::NSDictionaryMethodKind > NSAPI::getNSDictionaryMethodKind (Selector Sel)
Return NSDictionaryMethodKind if Sel is such a selector.
Definition at line 247 of file NSAPI.cpp.
References getNSDictionarySelector(), and NumNSDictionaryMethods.
getNSDictionarySelector()
Selector NSAPI::getNSDictionarySelector (NSDictionaryMethodKind MK) const
The Objective-C NSDictionary selectors.
Definition at line 155 of file NSAPI.cpp.
References clang::IdentifierTable::get(), clang::SelectorTable::getNullarySelector(), clang::SelectorTable::getSelector(), clang::SelectorTable::getUnarySelector(), clang::ASTContext::Idents, NSDict_dictionary, NSDict_dictionaryWithDictionary, NSDict_dictionaryWithObjectForKey, NSDict_dictionaryWithObjectsAndKeys, NSDict_dictionaryWithObjectsForKeys, NSDict_dictionaryWithObjectsForKeysCount, NSDict_initWithDictionary, NSDict_initWithObjectsAndKeys, NSDict_initWithObjectsForKeys, NSDict_objectForKey, NSMutableDict_setObjectForKey, NSMutableDict_setObjectForKeyedSubscript, NSMutableDict_setValueForKey, and clang::ASTContext::Selectors.
Referenced by getNSDictionaryMethodKind(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToDictionaryLiteral(), clang::edit::rewriteToObjCSubscriptSyntax(), and shouldNotRewriteImmediateMessageArgs().
GetNSIntegralKind()
StringRef NSAPI::GetNSIntegralKind (QualType T) const
Returns one of NSIntegral typedef names if.
Parameters
T is a typedef of that name in objective-c.
Definition at line 520 of file NSAPI.cpp.
References clang::Type::getAs(), clang::ASTContext::getLangOpts(), and clang::QualType::isNull().
getNSNumberFactoryMethodKind()
Optional< NSAPI::NSNumberLiteralMethodKind > NSAPI::getNSNumberFactoryMethodKind (QualType T) const
Determine the appropriate NSNumber factory method kind for a literal of the given type.
Definition at line 378 of file NSAPI.cpp.
References clang::Type::getAs(), clang::BuiltinType::getKind(), isObjCBOOLType(), isObjCNSIntegerType(), isObjCNSUIntegerType(), NSNumberWithBool, NSNumberWithChar, NSNumberWithDouble, NSNumberWithFloat, NSNumberWithInt, NSNumberWithInteger, NSNumberWithLong, NSNumberWithLongLong, NSNumberWithShort, NSNumberWithUnsignedChar, NSNumberWithUnsignedInt, NSNumberWithUnsignedInteger, NSNumberWithUnsignedLong, NSNumberWithUnsignedLongLong, and NSNumberWithUnsignedShort.
getNSNumberLiteralMethodKind()
Optional< NSAPI::NSNumberLiteralMethodKind > NSAPI::getNSNumberLiteralMethodKind (Selector Sel) const
Return NSNumberLiteralMethodKind if Sel is such a selector.
Definition at line 367 of file NSAPI.cpp.
References isNSNumberLiteralSelector(), and NumNSNumberLiteralMethods.
Referenced by rewriteToNumberLiteral(), and rewriteToNumericBoxedExpression().
getNSNumberLiteralSelector()
Selector NSAPI::getNSNumberLiteralSelector (NSNumberLiteralMethodKind MK, bool Instance) const
The Objective-C NSNumber selectors used to create NSNumber literals.
Parameters
Instance if true it will return the selector for the init* method otherwise it will return the selector for the number* method.
Definition at line 314 of file NSAPI.cpp.
References clang::IdentifierTable::get(), clang::SelectorTable::getUnarySelector(), clang::ASTContext::Idents, NumNSNumberLiteralMethods, and clang::ASTContext::Selectors.
Referenced by isNSNumberLiteralSelector().
getNSSetMethodKind()
Optional< NSAPI::NSSetMethodKind > NSAPI::getNSSetMethodKind (Selector Sel)
Return NSSetMethodKind if Sel is such a selector.
Definition at line 304 of file NSAPI.cpp.
References getNSSetSelector(), and NumNSSetMethods.
getNSSetSelector()
Selector NSAPI::getNSSetSelector (NSSetMethodKind MK) const
The Objective-C NSSet selectors.
Definition at line 257 of file NSAPI.cpp.
References clang::IdentifierTable::get(), clang::SelectorTable::getSelector(), clang::SelectorTable::getUnarySelector(), clang::ASTContext::Idents, NSMutableSet_addObject, NSOrderedSet_insertObjectAtIndex, NSOrderedSet_replaceObjectAtIndexWithObject, NSOrderedSet_setObjectAtIndex, NSOrderedSet_setObjectAtIndexedSubscript, and clang::ASTContext::Selectors.
Referenced by getNSSetMethodKind().
getNSStringSelector()
Selector NSAPI::getNSStringSelector (NSStringMethodKind MK) const
The Objective-C NSString selectors.
Definition at line 42 of file NSAPI.cpp.
References clang::IdentifierTable::get(), clang::SelectorTable::getSelector(), clang::SelectorTable::getUnarySelector(), clang::ASTContext::Idents, NSStr_initWithString, NSStr_initWithUTF8String, NSStr_stringWithCString, NSStr_stringWithCStringEncoding, NSStr_stringWithString, NSStr_stringWithUTF8String, and clang::ASTContext::Selectors.
Referenced by clang::edit::rewriteObjCRedundantCallWithLiteral(), and rewriteToStringBoxedExpression().
getObjectAtIndexedSubscriptSelector()
Selector clang::NSAPI::getObjectAtIndexedSubscriptSelector () const inline
Returns selector for "objectAtIndexedSubscript:".
Definition at line 143 of file NSAPI.h.
Referenced by rewriteToArraySubscriptGet().
getObjectForKeyedSubscriptSelector()
Selector clang::NSAPI::getObjectForKeyedSubscriptSelector () const inline
Returns selector for "objectForKeyedSubscript:".
Definition at line 137 of file NSAPI.h.
Referenced by rewriteToDictionarySubscriptGet().
getSetObjectAtIndexedSubscriptSelector()
Selector clang::NSAPI::getSetObjectAtIndexedSubscriptSelector () const inline
Returns selector for "setObject:atIndexedSubscript".
Definition at line 155 of file NSAPI.h.
Referenced by rewriteToArraySubscriptSet().
getSetObjectForKeyedSubscriptSelector()
Selector clang::NSAPI::getSetObjectForKeyedSubscriptSelector () const inline
Returns selector for "setObject:forKeyedSubscript".
Definition at line 149 of file NSAPI.h.
Referenced by rewriteToDictionarySubscriptSet().
isMacroDefined()
bool NSAPI::isMacroDefined (StringRef Id) const
Returns true if Id is currently defined as a macro.
Definition at line 546 of file NSAPI.cpp.
References clang::IdentifierTable::get(), clang::IdentifierInfo::hasMacroDefinition(), Id, and clang::ASTContext::Idents.
Referenced by rewriteToObjCProperty().
isNSASCIIStringEncodingConstant()
bool clang::NSAPI::isNSASCIIStringEncodingConstant (const Expr * E) const inline
Returns true if the expression.
Parameters
E is a reference of "NSASCIIStringEncoding" enum constant.
Definition at line 66 of file NSAPI.h.
Referenced by rewriteToStringBoxedExpression().
isNSNumberLiteralSelector()
bool clang::NSAPI::isNSNumberLiteralSelector (NSNumberLiteralMethodKind MK, Selector Sel) const inline
Definition at line 199 of file NSAPI.h.
References getNSNumberLiteralSelector().
Referenced by getNSNumberLiteralMethodKind(), rewriteToBoolLiteral(), and rewriteToCharLiteral().
isNSUTF8StringEncodingConstant()
bool clang::NSAPI::isNSUTF8StringEncodingConstant (const Expr * E) const inline
Returns true if the expression.
Parameters
E is a reference of "NSUTF8StringEncoding" enum constant.
Definition at line 60 of file NSAPI.h.
Referenced by rewriteToStringBoxedExpression().
isObjCBOOLType()
bool NSAPI::isObjCBOOLType (QualType T) const
Returns true if.
Parameters
T is a typedef of "BOOL" in objective-c.
Definition at line 508 of file NSAPI.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitScalarRangeCheck(), and getNSNumberFactoryMethodKind().
isObjCNSIntegerType()
bool NSAPI::isObjCNSIntegerType (QualType T) const
Returns true if.
Parameters
T is a typedef of "NSInteger" in objective-c.
Definition at line 512 of file NSAPI.cpp.
Referenced by getNSNumberFactoryMethodKind().
isObjCNSUIntegerType()
bool NSAPI::isObjCNSUIntegerType (QualType T) const
Returns true if.
Parameters
T is a typedef of "NSUInteger" in objective-c.
Definition at line 516 of file NSAPI.cpp.
Referenced by getNSNumberFactoryMethodKind().
isSubclassOfNSClass()
bool NSAPI::isSubclassOfNSClass (ObjCInterfaceDecl * InterfaceDecl, NSClassIdKindKind NSClassKind) const
Returns true if InterfaceDecl is subclass of NSClassKind.
Definition at line 551 of file NSAPI.cpp.
References clang::NamedDecl::getIdentifier(), getNSClassId(), and clang::ObjCInterfaceDecl::getSuperClass().
Member Data Documentation
NumClassIds
const unsigned clang::NSAPI::NumClassIds = 10 static
Definition at line 41 of file NSAPI.h.
Referenced by getNSClassId().
NumNSArrayMethods
const unsigned clang::NSAPI::NumNSArrayMethods = 12 static
Definition at line 86 of file NSAPI.h.
Referenced by getNSArrayMethodKind().
NumNSDictionaryMethods
const unsigned clang::NSAPI::NumNSDictionaryMethods = 13 static
Definition at line 111 of file NSAPI.h.
Referenced by getNSDictionaryMethodKind().
NumNSNumberLiteralMethods
const unsigned clang::NSAPI::NumNSNumberLiteralMethods = 15 static
Definition at line 191 of file NSAPI.h.
Referenced by getNSNumberLiteralMethodKind(), getNSNumberLiteralSelector(), and clang::Sema::Sema().
NumNSSetMethods
const unsigned clang::NSAPI::NumNSSetMethods = 5 static
Definition at line 128 of file NSAPI.h.
Referenced by getNSSetMethodKind().
NumNSStringMethods
const unsigned clang::NSAPI::NumNSStringMethods = 6 static
Definition at line 51 of file NSAPI.h.
The documentation for this class was generated from the following files:
include/clang/AST/NSAPI.h
lib/AST/NSAPI.cpp