clang: clang::CodeGen::CodeGenTypes Class Reference
clang::CodeGen::CodeGenTypes Class Reference
This class organizes the cross-module state that is used while lowering AST types to LLVM types.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenTypes.h"
Public Member Functions
CodeGenTypes (CodeGenModule &cgm)
~CodeGenTypes ()
const llvm::DataLayout & getDataLayout () const
CodeGenModule & getCGM () const
ASTContext & getContext () const
const ABIInfo & getABIInfo () const
const TargetInfo & getTarget () const
CGCXXABI & getCXXABI () const
llvm::LLVMContext & getLLVMContext ()
const CodeGenOptions & getCodeGenOpts () const
unsigned ClangCallConvToLLVMCallConv (CallingConv CC)
Convert clang calling convention to LLVM callilng convention.
CanQualType DeriveThisType (const CXXRecordDecl *RD, const CXXMethodDecl *MD)
Derives the 'this' type for codegen purposes, i.e.
llvm::Type * ConvertType (QualType T)
ConvertType - Convert type T into a llvm::Type.
llvm::Type * ConvertTypeForMem (QualType T, bool ForBitField=false)
ConvertTypeForMem - Convert type T into a llvm::Type.
llvm::Type * ConvertSYCLJointMatrixINTELType (RecordDecl *RD)
ConvertSYCLJointMatrixINTELType - Convert SYCL joint_matrix type which is represented as a pointer to a structure to LLVM extension type with the parameters that follow SPIR-V JointMatrixINTEL type.
llvm::FunctionType * GetFunctionType (const CGFunctionInfo &Info)
GetFunctionType - Get the LLVM function type for.
llvm::FunctionType * GetFunctionType (GlobalDecl GD)
bool isFuncTypeConvertible (const FunctionType *FT)
isFuncTypeConvertible - Utility to check whether a function type can be converted to an LLVM type (i.e.
bool isFuncParamTypeConvertible (QualType Ty)
isFuncParamTypeConvertible - Return true if the specified type in a function parameter or result position can be converted to an IR type at this point.
bool inheritingCtorHasParams (const InheritedConstructor &Inherited, CXXCtorType Type)
Determine if a C++ inheriting constructor should have parameters matching those of its inherited constructor.
llvm::Type * GetFunctionTypeForVTable (GlobalDecl GD)
GetFunctionTypeForVTable - Get the LLVM function type for use in a vtable, given a CXXMethodDecl.
const CGRecordLayout & getCGRecordLayout (const RecordDecl *)
getCGRecordLayout - Return record layout info for the given record decl.
void UpdateCompletedType (const TagDecl *TD)
UpdateCompletedType - When we find the full definition for a TagDecl, replace the 'opaque' type we previously made for it if applicable.
void RefreshTypeCacheForClass (const CXXRecordDecl *RD)
Remove stale types from the type cache when an inheritance model gets assigned to a class.
const CGFunctionInfo & arrangeGlobalDeclaration (GlobalDecl GD)
const CGFunctionInfo & arrangeCall (const CGFunctionInfo &declFI, const CallArgList &args)
Given a function info for a declaration, return the function info for a call with the given arguments.
const CGFunctionInfo & arrangeFunctionDeclaration (const FunctionDecl *FD)
Free functions are functions that are compatible with an ordinary C function pointer type.
const CGFunctionInfo & arrangeFreeFunctionCall (const CallArgList &Args, const FunctionType *Ty, bool ChainCall)
Figure out the rules for calling a function with the given formal type using the given arguments.
const CGFunctionInfo & arrangeFreeFunctionType (CanQual< FunctionProtoType > Ty)
Arrange the argument and result information for a value of the given freestanding function type.
const CGFunctionInfo & arrangeFreeFunctionType (CanQual< FunctionNoProtoType > Ty)
Arrange the argument and result information for a value of the given unprototyped freestanding function type.
const CGFunctionInfo & arrangeNullaryFunction ()
A nullary function is a freestanding function of type 'void ()'.
const CGFunctionInfo & arrangeBuiltinFunctionDeclaration (QualType resultType, const FunctionArgList &args)
A builtin function is a freestanding function using the default C conventions.
const CGFunctionInfo & arrangeBuiltinFunctionDeclaration (CanQualType resultType, ArrayRef< CanQualType > argTypes)
const CGFunctionInfo & arrangeBuiltinFunctionCall (QualType resultType, const CallArgList &args)
const CGFunctionInfo & arrangeObjCMethodDeclaration (const ObjCMethodDecl *MD)
Objective-C methods are C functions with some implicit parameters.
const CGFunctionInfo & arrangeObjCMessageSendSignature (const ObjCMethodDecl *MD, QualType receiverType)
Arrange the argument and result information for the function type through which to perform a send to the given Objective-C method, using the given receiver type.
const CGFunctionInfo & arrangeUnprototypedObjCMessageSend (QualType returnType, const CallArgList &args)
const CGFunctionInfo & arrangeBlockFunctionDeclaration (const FunctionProtoType *type, const FunctionArgList &args)
Block invocation functions are C functions with an implicit parameter.
const CGFunctionInfo & arrangeBlockFunctionCall (const CallArgList &args, const FunctionType *type)
A block function is essentially a free function with an extra implicit argument.
const CGFunctionInfo & arrangeCXXMethodDeclaration (const CXXMethodDecl *MD)
C++ methods have some special rules and also have implicit parameters.
const CGFunctionInfo & arrangeCXXStructorDeclaration (GlobalDecl GD)
const CGFunctionInfo & arrangeCXXConstructorCall (const CallArgList &Args, const CXXConstructorDecl *D, CXXCtorType CtorKind, unsigned ExtraPrefixArgs, unsigned ExtraSuffixArgs, bool PassProtoArgs=true)
Arrange a call to a C++ method, passing the given arguments.
const CGFunctionInfo & arrangeCXXMethodCall (const CallArgList &args, const FunctionProtoType *type, RequiredArgs required, unsigned numPrefixArgs)
Arrange a call to a C++ method, passing the given arguments.
const CGFunctionInfo & arrangeUnprototypedMustTailThunk (const CXXMethodDecl *MD)
Arrange a thunk that takes 'this' as the first parameter followed by varargs.
const CGFunctionInfo & arrangeMSCtorClosure (const CXXConstructorDecl *CD, CXXCtorType CT)
const CGFunctionInfo & arrangeCXXMethodType (const CXXRecordDecl *RD, const FunctionProtoType *FTP, const CXXMethodDecl *MD)
Arrange the argument and result information for a call to an unknown C++ non-static member function of the given abstract type.
const CGFunctionInfo & arrangeLLVMFunctionInfo (CanQualType returnType, FnInfoOpts opts, ArrayRef< CanQualType > argTypes, FunctionType::ExtInfo info, ArrayRef< FunctionProtoType::ExtParameterInfo > paramInfos, RequiredArgs args)
"Arrange" the LLVM information for a call or type with the given signature.
std::unique_ptr< CGRecordLayout > ComputeRecordLayout (const RecordDecl *D, llvm::StructType *Ty)
Compute a new LLVM record layout object for the given record.
void addRecordTypeName (const RecordDecl *RD, llvm::StructType *Ty, StringRef suffix)
addRecordTypeName - Compute a name from the given record decl with an optional suffix and name the given LLVM type using it.
llvm::StructType * ConvertRecordDeclType (const RecordDecl *TD)
ConvertRecordDeclType - Lay out a tagged decl type like struct or union.
void getExpandedTypes (QualType Ty, SmallVectorImpl< llvm::Type * >::iterator &TI)
getExpandedTypes - Expand the type
bool isZeroInitializable (QualType T)
IsZeroInitializable - Return whether a type can be zero-initialized (in the C++ sense) with an LLVM zeroinitializer.
bool isPointerZeroInitializable (QualType T)
Check if the pointer type can be zero-initialized (in the C++ sense) with an LLVM zeroinitializer.
bool isZeroInitializable (const RecordDecl *RD)
IsZeroInitializable - Return whether a record type can be zero-initialized (in the C++ sense) with an LLVM zeroinitializer.
bool isLongDoubleReferenced () const
bool isRecordLayoutComplete (const Type *Ty) const
isRecordLayoutComplete - Return true if the specified type is already completely laid out.
unsigned getTargetAddressSpace (QualType T) const
Detailed Description
This class organizes the cross-module state that is used while lowering AST types to LLVM types.
Definition at line 54 of file CodeGenTypes.h.
Constructor & Destructor Documentation
CodeGenTypes()
CodeGenTypes::CodeGenTypes (CodeGenModule & cgm)
Definition at line 32 of file CodeGenTypes.cpp.
~CodeGenTypes()
CodeGenTypes::~CodeGenTypes ()
Definition at line 40 of file CodeGenTypes.cpp.
Member Function Documentation
addRecordTypeName()
void CodeGenTypes::addRecordTypeName (const RecordDecl * RD, llvm::StructType * Ty, StringRef suffix)
addRecordTypeName - Compute a name from the given record decl with an optional suffix and name the given LLVM type using it.
Definition at line 50 of file CodeGenTypes.cpp.
References clang::Decl::getASTContext(), clang::Decl::getDeclContext(), clang::NamedDecl::getIdentifier(), clang::TagDecl::getKindName(), clang::ASTContext::getPrintingPolicy(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::TagDecl::printName(), clang::NamedDecl::printQualifiedName(), clang::PrintingPolicy::SuppressInlineNamespace, and clang::TypeName.
Referenced by ConvertRecordDeclType().
arrangeBlockFunctionCall()
const CGFunctionInfo & CodeGenTypes::arrangeBlockFunctionCall (const CallArgList & args, const FunctionType * type)
A block function is essentially a free function with an extra implicit argument.
Definition at line 651 of file CGCall.cpp.
References arrangeFreeFunctionLikeCall().
Referenced by clang::CodeGen::CodeGenFunction::EmitBlockCallExpr().
arrangeBlockFunctionDeclaration()
const CGFunctionInfo & CodeGenTypes::arrangeBlockFunctionDeclaration (const FunctionProtoType * type, const FunctionArgList & args)
Block invocation functions are C functions with an implicit parameter.
Definition at line 658 of file CGCall.cpp.
References arrangeLLVMFunctionInfo(), clang::CodeGen::RequiredArgs::forPrototypePlus(), getArgTypesForDeclaration(), clang::FunctionType::getExtInfo(), getExtParameterInfosForCall(), clang::FunctionType::getReturnType(), GetReturnType(), and clang::CodeGen::None.
Referenced by clang::CodeGen::CodeGenFunction::GenerateBlockFunction().
arrangeBuiltinFunctionCall()
const CGFunctionInfo & CodeGenTypes::arrangeBuiltinFunctionCall (QualType resultType, const CallArgList & args)
Definition at line 670 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, arrangeLLVMFunctionInfo(), clang::ASTContext::getCanonicalParamType(), GetReturnType(), and clang::CodeGen::None.
Referenced by emitAtomicLibcall(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), and emitStructSetterCall().
arrangeBuiltinFunctionDeclaration() [1/2]
const CGFunctionInfo & CodeGenTypes::arrangeBuiltinFunctionDeclaration (CanQualType resultType, ArrayRef< CanQualType > argTypes)
Definition at line 692 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, arrangeLLVMFunctionInfo(), and clang::CodeGen::None.
arrangeBuiltinFunctionDeclaration() [2/2]
const CGFunctionInfo & CodeGenTypes::arrangeBuiltinFunctionDeclaration (QualType resultType, const FunctionArgList & args)
A builtin function is a freestanding function using the default C conventions.
Definition at line 682 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, arrangeLLVMFunctionInfo(), getArgTypesForDeclaration(), GetReturnType(), and clang::CodeGen::None.
Referenced by clang::CodeGen::CodeGenFunction::EmitCfiCheckFail(), clang::CodeGen::CodeGenFunction::EmitCfiCheckStub(), emitCombinerOrInitializer(), emitCopyprivateCopyFunction(), emitDestructorsFunction(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), emitOutlinedFunctionPrologue(), emitProxyTaskFunction(), emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), emitShuffleAndReduceFunction(), emitTaskDupFunction(), emitTaskPrivateMappingFunction(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::generateDestroyHelper(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicSetterCopyHelperFunction(), and getClangCallTerminateFn().
arrangeCall()
const CGFunctionInfo & CodeGenTypes::arrangeCall (const CGFunctionInfo & declFI, const CallArgList & args)
Given a function info for a declaration, return the function info for a call with the given arguments.
Often this will be able to simply return the declaration info.
Definition at line 731 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::allowsOptionalArgs(), clang::CodeGen::CGFunctionInfo::arg_size(), arrangeLLVMFunctionInfo(), getArgTypesForCall(), clang::CodeGen::CGFunctionInfo::getExtInfo(), clang::CodeGen::CGFunctionInfo::getExtParameterInfos(), clang::CodeGen::CGFunctionInfo::getRequiredArgs(), clang::CodeGen::CGFunctionInfo::getReturnType(), clang::CodeGen::CGFunctionInfo::isChainCall(), clang::CodeGen::IsChainCall, clang::CodeGen::CGFunctionInfo::isDelegateCall(), clang::CodeGen::IsDelegateCall, clang::CodeGen::CGFunctionInfo::isInstanceMethod(), clang::CodeGen::IsInstanceMethod, and clang::CodeGen::None.
Referenced by clang::CodeGen::CGObjCRuntime::getMessageSendInfo().
arrangeCXXConstructorCall()
const CGFunctionInfo & CodeGenTypes::arrangeCXXConstructorCall (const CallArgList & args, const CXXConstructorDecl * D, CXXCtorType CtorKind, unsigned ExtraPrefixArgs, unsigned ExtraSuffixArgs, bool PassProtoArgs = true)
Arrange a call to a C++ method, passing the given arguments.
ExtraPrefixArgs is the number of ABI-specific args passed after the this parameter. ExtraSuffixArgs is the number of ABI-specific args passed at the end of args. PassProtoArgs indicates whether args has args for the parameters in the given CXXConstructorDecl.
Definition at line 421 of file CGCall.cpp.
References addExtParameterInfosForCall(), clang::CodeGen::RequiredArgs::All, arrangeLLVMFunctionInfo(), clang::CodeGen::RequiredArgs::forPrototypePlus(), clang::ASTContext::getCanonicalParamType(), clang::CodeGen::CodeGenModule::getContext(), GetFormalType(), clang::CanQual< T >::getTypePtr(), clang::CodeGen::CGCXXABI::hasMostDerivedReturn(), clang::CodeGen::CGCXXABI::HasThisReturn(), clang::CodeGen::IsInstanceMethod, clang::Required, clang::ASTContext::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by canEmitDelegateCallArgs(), and clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall().
arrangeCXXMethodCall()
const CGFunctionInfo & CodeGenTypes::arrangeCXXMethodCall (const CallArgList & args, const FunctionProtoType * proto, RequiredArgs required, unsigned numPrefixArgs)
Arrange a call to a C++ method, passing the given arguments.
numPrefixArgs is the number of ABI-specific prefix arguments we have. It does not count this.
Definition at line 704 of file CGCall.cpp.
References arrangeLLVMFunctionInfo(), getArgTypesForCall(), clang::FunctionType::getExtInfo(), getExtParameterInfosForCall(), clang::FunctionType::getReturnType(), GetReturnType(), and clang::CodeGen::IsInstanceMethod.
Referenced by clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::EmitCXXMemberOrOperatorCall(), and clang::CodeGen::CodeGenFunction::EmitCXXMemberPointerCallExpr().
arrangeCXXMethodDeclaration()
const CGFunctionInfo & CodeGenTypes::arrangeCXXMethodDeclaration (const CXXMethodDecl * MD)
C++ methods have some special rules and also have implicit parameters.
Arrange the argument and result information for a declaration or definition of the given C++ non-static member function.
The member function must be an ordinary function, i.e. not a constructor or destructor.
Definition at line 309 of file CGCall.cpp.
References arrangeCXXMethodType(), arrangeFreeFunctionType(), clang::CanQual< T >::getAs(), GetFormalType(), clang::CodeGen::CGCXXABI::getThisArgumentTypeForMethod(), clang::CXXMethodDecl::isImplicitObjectMemberFunction(), and setCUDAKernelCallingConvention().
Referenced by arrangeFunctionDeclaration(), clang::CodeGen::CodeGenFunction::EmitForwardingCallToLambda(), and clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaImplFn().
arrangeCXXMethodType()
const CGFunctionInfo & CodeGenTypes::arrangeCXXMethodType (const CXXRecordDecl * RD, const FunctionProtoType * FTP, const CXXMethodDecl * MD)
Arrange the argument and result information for a call to an unknown C++ non-static member function of the given abstract type.
(A null RD means we don't have any meaningful "this" argument type, so fall back to a generic pointer type). The member function must be an ordinary function, i.e. not a constructor or destructor.
Definition at line 281 of file CGCall.cpp.
References arrangeLLVMFunctionInfo(), DeriveThisType(), clang::CanQual< T >::getAs(), and clang::Type::getCanonicalTypeUnqualified().
Referenced by arrangeCXXMethodDeclaration(), and clang::CodeGen::arrangeCXXMethodType().
arrangeCXXStructorDeclaration()
const CGFunctionInfo & CodeGenTypes::arrangeCXXStructorDeclaration (GlobalDecl GD)
Definition at line 336 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, appendParameterTypes(), arrangeLLVMFunctionInfo(), clang::CodeGen::CGCXXABI::buildStructorSignature(), DeriveThisType(), clang::CodeGen::CodeGenModule::getContext(), clang::GlobalDecl::getCtorType(), clang::GlobalDecl::getDecl(), GetFormalType(), clang::CodeGen::CGCXXABI::getThisArgumentTypeForMethod(), clang::CodeGen::CGCXXABI::hasMostDerivedReturn(), clang::CodeGen::CGCXXABI::HasThisReturn(), inheritingCtorHasParams(), clang::CodeGen::IsInstanceMethod, clang::CodeGen::CGCXXABI::AddedStructorArgCounts::Prefix, clang::CodeGen::CGCXXABI::AddedStructorArgCounts::Suffix, clang::ASTContext::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by arrangeGlobalDeclaration(), clang::CodeGen::CodeGenFunction::BuildAppleKextVirtualDestructorCall(), clang::CodeGen::CodeGenModule::codegenCXXStructor(), clang::CodeGen::CodeGenFunction::EmitCXXDestructorCall(), and clang::CodeGen::CodeGenModule::getAddrAndTypeOfCXXStructor().
arrangeFreeFunctionCall()
const CGFunctionInfo & CodeGenTypes::arrangeFreeFunctionCall (const CallArgList & args, const FunctionType * fnType, bool chainCall)
Figure out the rules for calling a function with the given formal type using the given arguments.
The arguments are necessary because the function might be unprototyped, in which case it's target-dependent in crazy ways.
Definition at line 641 of file CGCall.cpp.
References arrangeFreeFunctionLikeCall().
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), and EmitNewDeleteCall().
arrangeFreeFunctionType() [1/2]
const CGFunctionInfo & CodeGenTypes::arrangeFreeFunctionType (CanQual< FunctionNoProtoType > Ty)
Arrange the argument and result information for a value of the given unprototyped freestanding function type.
Definition at line 119 of file CGCall.cpp.
References arrangeLLVMFunctionInfo(), clang::CanQual< T >::getUnqualifiedType(), and clang::CodeGen::None.
arrangeFreeFunctionType() [2/2]
const CGFunctionInfo & CodeGenTypes::arrangeFreeFunctionType (CanQual< FunctionProtoType > Ty)
Arrange the argument and result information for a value of the given freestanding function type.
Definition at line 208 of file CGCall.cpp.
References arrangeLLVMFunctionInfo().
Referenced by arrangeCXXMethodDeclaration(), clang::CodeGen::arrangeFreeFunctionType(), and arrangeFunctionDeclaration().
arrangeFunctionDeclaration()
const CGFunctionInfo & CodeGenTypes::arrangeFunctionDeclaration (const FunctionDecl * FD)
Free functions are functions that are compatible with an ordinary C function pointer type.
Arrange the argument and result information for the declaration or definition of the given function.
Definition at line 465 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, arrangeCXXMethodDeclaration(), arrangeFreeFunctionType(), arrangeLLVMFunctionInfo(), clang::CanQual< T >::castAs(), clang::CanQual< T >::getAs(), clang::Type::getCanonicalTypeUnqualified(), clang::ValueDecl::getType(), clang::CodeGen::None, and setCUDAKernelCallingConvention().
Referenced by arrangeGlobalDeclaration(), and clang::CodeGen::CodeGenFunction::EmitAutoVarCleanups().
arrangeGlobalDeclaration()
const CGFunctionInfo & CodeGenTypes::arrangeGlobalDeclaration (GlobalDecl GD)
Definition at line 545 of file CGCall.cpp.
References arrangeCXXStructorDeclaration(), arrangeFunctionDeclaration(), and clang::GlobalDecl::getDecl().
Referenced by clang::CodeGen::CodeGenModule::EmitGlobal(), and GetFunctionType().
arrangeLLVMFunctionInfo()
const CGFunctionInfo & CodeGenTypes::arrangeLLVMFunctionInfo (CanQualType resultType, FnInfoOpts opts, ArrayRef< CanQualType > argTypes, FunctionType::ExtInfo info, ArrayRef< FunctionProtoType::ExtParameterInfo > paramInfos, RequiredArgs required)
"Arrange" the LLVM information for a call or type with the given signature.
Arrange the argument and result information for an abstract value of a given function type.
This is largely an internal method; other clients should use one of the above routines, which ultimately defer to this.
Parameters
argTypes - must all actually be canonical as params
This is the method which all of the above functions ultimately defer to.
Definition at line 768 of file CGCall.cpp.
References clang::CodeGen::CGFunctionInfo::arguments(), AttributeLangSupport::C, clang::CodeGen::ABIArgInfo::canHaveCoerceToType(), clang::CC_Swift, clang::CC_SwiftAsync, ClangCallConvToLLVMCallConv(), clang::CodeGen::swiftcall::computeABIInfo(), clang::CodeGen::ABIInfo::computeInfo(), clang::CodeGen::computeSPIRKernelABIInfo(), ConvertType(), clang::CodeGen::CGFunctionInfo::create(), getABIInfo(), clang::FunctionType::ExtInfo::getCC(), clang::CodeGen::ABIArgInfo::getCoerceToType(), getContext(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), clang::CodeGen::CGFunctionInfo::getReturnType(), clang::CodeGen::CodeGenModule::getTriple(), ID, clang::CodeGen::IsChainCall, clang::CodeGen::IsDelegateCall, clang::CodeGen::IsInstanceMethod, isInstanceMethod(), clang::CodeGen::CGFunctionInfo::Profile(), clang::CodeGen::ABIArgInfo::setCoerceToType(), and clang::T.
Referenced by arrangeBlockFunctionDeclaration(), arrangeBuiltinFunctionCall(), arrangeBuiltinFunctionDeclaration(), arrangeCall(), arrangeCXXConstructorCall(), arrangeCXXMethodCall(), arrangeCXXStructorDeclaration(), clang::CodeGen::arrangeFreeFunctionCall(), arrangeFreeFunctionLikeCall(), arrangeFreeFunctionType(), arrangeFunctionDeclaration(), arrangeLLVMFunctionInfo(), arrangeMSCtorClosure(), arrangeNullaryFunction(), arrangeObjCMessageSendSignature(), arrangeUnprototypedMustTailThunk(), arrangeUnprototypedObjCMessageSend(), clang::CodeGen::CodeGenFunction::createTLSAtExitStub(), and clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaImplFn().
arrangeMSCtorClosure()
const CGFunctionInfo & CodeGenTypes::arrangeMSCtorClosure (const CXXConstructorDecl * CD, CXXCtorType CT)
Definition at line 571 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, arrangeLLVMFunctionInfo(), clang::Ctor_CopyingClosure, clang::Ctor_DefaultClosure, DeriveThisType(), clang::ASTContext::getDefaultCallingConvention(), GetFormalType(), clang::CXXRecordDecl::getNumVBases(), clang::CXXMethodDecl::getParent(), clang::ASTContext::IntTy, clang::CodeGen::IsInstanceMethod, and clang::ASTContext::VoidTy.
arrangeNullaryFunction()
const CGFunctionInfo & CodeGenTypes::arrangeNullaryFunction ()
A nullary function is a freestanding function of type 'void ()'.
This method works for both calls and declarations.
Definition at line 724 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, arrangeLLVMFunctionInfo(), getContext(), and clang::CodeGen::None.
Referenced by clang::CodeGen::CodeGenFunction::createAtExitStub(), and createGlobalInitOrCleanupFn().
arrangeObjCMessageSendSignature()
const CGFunctionInfo & CodeGenTypes::arrangeObjCMessageSendSignature (const ObjCMethodDecl * MD, QualType receiverType)
Arrange the argument and result information for the function type through which to perform a send to the given Objective-C method, using the given receiver type.
The receiver type is not always the 'self' type of the method or even an Objective-C pointer type. This is not the right method for actually performing such a message send, due to the possibility of optional arguments.
Definition at line 502 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, arrangeLLVMFunctionInfo(), getCallingConventionForDecl(), clang::ASTContext::getCanonicalParamType(), getContext(), clang::ASTContext::getObjCSelType(), clang::ObjCMethodDecl::getReturnType(), GetReturnType(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::Decl::hasAttr(), clang::ObjCMethodDecl::isDirectMethod(), clang::ObjCMethodDecl::isVariadic(), clang::CodeGen::None, clang::ObjCMethodDecl::parameters(), clang::FunctionType::ExtInfo::withCallingConv(), clang::FunctionType::ExtParameterInfo::withIsNoEscape(), and clang::FunctionType::ExtInfo::withProducesResult().
Referenced by clang::CodeGen::arrangeObjCMessageSendSignature(), arrangeObjCMethodDeclaration(), and clang::CodeGen::CGObjCRuntime::getMessageSendInfo().
arrangeObjCMethodDeclaration()
const CGFunctionInfo & CodeGenTypes::arrangeObjCMethodDeclaration (const ObjCMethodDecl * MD)
Objective-C methods are C functions with some implicit parameters.
Arrange the argument and result information for the declaration or definition of an Objective-C method.
Definition at line 489 of file CGCall.cpp.
References arrangeObjCMessageSendSignature(), clang::ObjCMethodDecl::getSelfDecl(), and clang::ValueDecl::getType().
Referenced by clang::CodeGen::CodeGenFunction::StartObjCMethod().
arrangeUnprototypedMustTailThunk()
const CGFunctionInfo & CodeGenTypes::arrangeUnprototypedMustTailThunk (const CXXMethodDecl * MD)
Arrange a thunk that takes 'this' as the first parameter followed by varargs.
Return a void pointer, regardless of the actual return type. The body of the thunk will end in a musttail call to a function of the correct type, and the caller will bitcast the function to the correct prototype.
Definition at line 562 of file CGCall.cpp.
References arrangeLLVMFunctionInfo(), DeriveThisType(), GetFormalType(), clang::CXXMethodDecl::getParent(), clang::CXXMethodDecl::isVirtual(), clang::CodeGen::None, and clang::ASTContext::VoidTy.
arrangeUnprototypedObjCMessageSend()
const CGFunctionInfo & CodeGenTypes::arrangeUnprototypedObjCMessageSend (QualType returnType, const CallArgList & args)
Definition at line 535 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::All, arrangeLLVMFunctionInfo(), getArgTypesForCall(), GetReturnType(), and clang::CodeGen::None.
Referenced by clang::CodeGen::CGObjCRuntime::getMessageSendInfo().
ClangCallConvToLLVMCallConv()
unsigned CodeGenTypes::ClangCallConvToLLVMCallConv (CallingConv CC)
Convert clang calling convention to LLVM callilng convention.
Definition at line 52 of file CGCall.cpp.
References AttributeLangSupport::C, clang::CC_AAPCS, clang::CC_AAPCS_VFP, clang::CC_AArch64SVEPCS, clang::CC_AArch64VectorCall, clang::CC_AMDGPUKernelCall, clang::CC_IntelOclBicc, clang::CC_M68kRTD, clang::CC_OpenCLKernel, clang::CC_PreserveAll, clang::CC_PreserveMost, clang::CC_PreserveNone, clang::CC_RISCVVectorCall, clang::CC_SpirFunction, clang::CC_Swift, clang::CC_SwiftAsync, clang::CC_Win64, clang::CC_X86_64SysV, clang::CC_X86FastCall, clang::CC_X86Pascal, clang::CC_X86RegCall, clang::CC_X86StdCall, clang::CC_X86ThisCall, clang::CC_X86VectorCall, clang::CodeGen::TargetCodeGenInfo::getOpenCLKernelCallingConv(), and clang::CodeGen::CodeGenModule::getTargetCodeGenInfo().
Referenced by arrangeLLVMFunctionInfo().
ComputeRecordLayout()
std::unique_ptr< CGRecordLayout > CodeGenTypes::ComputeRecordLayout (const RecordDecl * D, llvm::StructType * Ty)
Compute a new LLVM record layout object for the given record.
Definition at line 1088 of file CGRecordLayoutBuilder.cpp.
Referenced by ConvertRecordDeclType().
ConvertRecordDeclType()
llvm::StructType * CodeGenTypes::ConvertRecordDeclType (const RecordDecl * TD)
ConvertRecordDeclType - Lay out a tagged decl type like struct or union.
Definition at line 834 of file CodeGenTypes.cpp.
References addRecordTypeName(), clang::CodeGen::CodeGenModule::addTypeWithAspects(), ComputeRecordLayout(), clang::serialized_diags::create(), clang::RecordType::getDecl(), clang::RecordDecl::getDefinition(), getLLVMContext(), clang::ASTContext::getTagDeclType(), clang::QualType::getTypePtr(), clang::Decl::hasAttr(), and clang::TagDecl::isCompleteDefinition().
Referenced by ConvertType(), getCGRecordLayout(), and UpdateCompletedType().
ConvertSYCLJointMatrixINTELType()
llvm::Type * CodeGenTypes::ConvertSYCLJointMatrixINTELType (RecordDecl * RD)
ConvertSYCLJointMatrixINTELType - Convert SYCL joint_matrix type which is represented as a pointer to a structure to LLVM extension type with the parameters that follow SPIR-V JointMatrixINTEL type.
The expected representation is: target("spirv.JointMatrixINTEL", element_type, rows%, cols%, scope%, use%, (optional) element_type_interpretation%)
Definition at line 329 of file CodeGenTypes.cpp.
References ConvertType(), getJointMatrixINTELExtType(), getKind(), getLLVMContext(), and clang::TemplateArgument::Type.
Referenced by ConvertType().
ConvertType()
llvm::Type * CodeGenTypes::ConvertType (QualType T)
ConvertType - Convert type T into a llvm::Type.
ConvertType - Convert the specified type to its LLVM form.
Definition at line 367 of file CodeGenTypes.cpp.
References clang::CodeGen::CGCXXABI::ConvertMemberPointerType(), clang::CodeGen::CGOpenCLRuntime::convertOpenCLSpecificType(), ConvertRecordDeclType(), ConvertSYCLJointMatrixINTELType(), ConvertTypeForMem(), clang::serialized_diags::create(), clang::ASTContext::BuiltinVectorTypeInfo::EC, clang::ASTContext::BuiltinVectorTypeInfo::ElementType, clang::RISCV::Float, clang::QualType::getAddressSpace(), clang::Type::getAsCXXRecordDecl(), clang::ASTContext::getBuiltinVectorTypeInfo(), clang::ASTContext::getCanonicalType(), clang::CodeGen::TargetCodeGenInfo::getCUDADeviceBuiltinSurfaceDeviceType(), clang::CodeGen::TargetCodeGenInfo::getCUDADeviceBuiltinTextureDeviceType(), getCXXABI(), clang::ArrayType::getElementType(), clang::MatrixType::getElementType(), clang::ASTContext::getFloatTypeSemantics(), clang::ArrayType::getIndexTypeCVRQualifiers(), clang::EnumDecl::getIntegerType(), getKind(), clang::ASTContext::getLangOpts(), getLLVMContext(), clang::ConstantMatrixType::getNumColumns(), clang::ConstantMatrixType::getNumRows(), clang::CodeGen::CodeGenModule::getOpenCLRuntime(), clang::CodeGen::CGOpenCLRuntime::getPipeType(), clang::Type::getPointeeType(), clang::PointerType::getPointeeType(), clang::ReferenceType::getPointeeType(), clang::NamedDecl::getQualifiedNameAsString(), clang::ASTContext::getTargetAddressSpace(), getTargetAddressSpace(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::ASTContext::getTargetInfo(), clang::CodeGen::CodeGenModule::getTriple(), clang::Type::getTypeClass(), getTypeForFormat(), clang::QualType::getTypePtrOrNull(), clang::ASTContext::getTypeSize(), clang::ConstantArrayType::getZExtSize(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::TagDecl::isCompleteDefinition(), clang::Type::isCUDADeviceBuiltinSurfaceType(), clang::Type::isCUDADeviceBuiltinTextureType(), clang::EnumDecl::isFixed(), clang::Type::isStructureOrClassType(), clang::ASTContext::BuiltinVectorTypeInfo::NumVectors, clang::T, and clang::TargetInfo::useFP16ConversionIntrinsics().
Referenced by clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), addX86InterruptAttrs(), arrangeLLVMFunctionInfo(), buildBlockDescriptor(), buildGlobalBlock(), computeBlockInfo(), clang::CodeGen::convertFreeFunctionType(), clang::CodeGen::CGCXXABI::ConvertMemberPointerType(), ConvertSYCLJointMatrixINTELType(), clang::CodeGen::CodeGenFunction::ConvertType(), ConvertTypeForMem(), clang::CodeGen::CodeGenFunction::EmitCXXDestructorCall(), clang::CodeGen::CodeGenFunction::EmitDeleteCall(), clang::CodeGen::CodeGenFunction::EmitExtVectorElementLValue(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::CGOpenMPRuntime::emitKmpRoutineEntryT(), clang::CodeGen::CodeGenFunction::EmitLoadOfGlobalRegLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughGlobalRegLValue(), clang::CodeGen::CodeGenFunction::EmitSynthesizedCXXCopyCtorCall(), clang::CodeGen::CodeGenModule::getBlockDescriptorType(), clang::CodeGen::CGCXXABI::GetBogusMemberPointer(), getExpandedTypes(), getGuardAcquireFn(), clang::CodeGen::CodeGenModule::GetNonVirtualBaseClassOffset(), clang::CodeGen::ConstantEmitter::tryEmitPrivate(), and UpdateCompletedType().
ConvertTypeForMem()
llvm::Type * CodeGenTypes::ConvertTypeForMem (QualType T, bool ForBitField = false)
ConvertTypeForMem - Convert type T into a llvm::Type.
This differs from ConvertType in that it is used to convert to the memory representation for a type. For example, the scalar representation for _Bool is i1, but the memory representation is usually i8 or i32, depending on the target.
Definition at line 92 of file CodeGenTypes.cpp.
References ConvertType(), clang::ASTContext::getCanonicalType(), clang::MatrixType::getElementType(), getLLVMContext(), clang::ConstantMatrixType::getNumColumns(), clang::ConstantMatrixType::getNumRows(), clang::CanQual< T >::getTypePtr(), clang::ASTContext::getTypeSize(), clang::Type::isBitIntType(), clang::Type::isConstantMatrixType(), clang::Type::isExtVectorBoolType(), and clang::T.
Referenced by computeBlockInfo(), ConvertType(), clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::convertTypeForMemory(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::ConstantEmitter::emitForMemory(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), EmitGlobalVarDeclLValue(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenModule::EmitOMPAllocateDecl(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), and clang::CodeGen::CodeGenModule::GetWeakRefReference().
DeriveThisType()
CanQualType CodeGenTypes::DeriveThisType (const CXXRecordDecl * RD, const CXXMethodDecl * MD)
Derives the 'this' type for codegen purposes, i.e.
ignoring method CVR qualification.
ignoring method CVR qualification. Either or both of RD and MD may be null. A null RD indicates that there is no meaningful 'this' type, and a null MD can occur when calling a method pointer.
Definition at line 89 of file CGCall.cpp.
References clang::CanQual< Type >::CreateUnsafe(), clang::Qualifiers::getAddressSpace(), clang::ASTContext::getAddrSpaceQualType(), clang::Type::getCanonicalTypeInternal(), clang::CXXMethodDecl::getMethodQualifiers(), clang::ASTContext::getPointerType(), clang::ASTContext::getTagDeclType(), and clang::ASTContext::VoidTy.
Referenced by arrangeCXXMethodType(), arrangeCXXStructorDeclaration(), arrangeMSCtorClosure(), arrangeUnprototypedMustTailThunk(), and commonEmitCXXMemberOrOperatorCall().
getABIInfo()
const ABIInfo& clang::CodeGen::CodeGenTypes::getABIInfo () const inline
Definition at line 109 of file CodeGenTypes.h.
Referenced by arrangeLLVMFunctionInfo(), clang::CodeGen::CodeGenFunction::EmitVAArg(), and isTrivialForMSVC().
getCGM()
CodeGenModule& clang::CodeGen::CodeGenTypes::getCGM () const inline
Definition at line 107 of file CodeGenTypes.h.
getCGRecordLayout()
const CGRecordLayout & CodeGenTypes::getCGRecordLayout (const RecordDecl * RD)
getCGRecordLayout - Return record layout info for the given record decl.
Definition at line 879 of file CodeGenTypes.cpp.
References ConvertRecordDeclType(), clang::ASTContext::getTagDeclType(), and clang::QualType::getTypePtr().
Referenced by emitAddrOfFieldStorage(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), EmitNullConstant(), EmitNullConstantForBase(), emitPreserveStructAccess(), getGEPIndicesToField(), clang::CodeGen::getLLVMFieldNumber(), and isZeroInitializable().
getCodeGenOpts()
const CodeGenOptions & CodeGenTypes::getCodeGenOpts () const
Definition at line 46 of file CodeGenTypes.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts().
Referenced by emitGlobalDtorWithCXAAtExit(), and clang::CodeGen::ABIInfo::getCodeGenOpts().
getContext()
ASTContext& clang::CodeGen::CodeGenTypes::getContext () const inline
Definition at line 108 of file CodeGenTypes.h.
Referenced by appendParameterTypes(), arrangeFreeFunctionLikeCall(), arrangeLLVMFunctionInfo(), arrangeNullaryFunction(), arrangeObjCMessageSendSignature(), clang::CodeGen::ABIInfo::getContext(), GetFunctionType(), and getTargetAddressSpace().
getCXXABI()
CGCXXABI& clang::CodeGen::CodeGenTypes::getCXXABI () const inline
Definition at line 111 of file CodeGenTypes.h.
Referenced by ConvertType(), clang::CodeGen::ABIInfo::getCXXABI(), isFuncParamTypeConvertible(), and isZeroInitializable().
getDataLayout()
const llvm::DataLayout& clang::CodeGen::CodeGenTypes::getDataLayout () const inline
Definition at line 104 of file CodeGenTypes.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfGlobalRegLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughGlobalRegLValue(), clang::CodeGen::ABIInfo::getDataLayout(), and getTargetAddressSpace().
getExpandedTypes()
void CodeGenTypes::getExpandedTypes (QualType Ty, SmallVectorImpl< llvm::Type * >::iterator & TI)
getExpandedTypes - Expand the type
Ty into the LLVM argument types it would be passed as. See ABIArgInfo::Expand.
Definition at line 1023 of file CGCall.cpp.
References ConvertType(), and getTypeExpansion().
Referenced by GetFunctionType().
GetFunctionType() [1/2]
llvm::FunctionType * CodeGenTypes::GetFunctionType (const CGFunctionInfo & Info)
GetFunctionType - Get the LLVM function type for.
Info.
Definition at line 1636 of file CGCall.cpp.
References clang::CodeGen::CGFunctionInfo::arg_begin(), clang::CodeGen::ABIArgInfo::CoerceAndExpand, clang::CodeGen::ABIArgInfo::Direct, clang::CodeGen::ABIArgInfo::Expand, clang::CodeGen::ABIArgInfo::Extend, clang::CodeGen::ABIArgInfo::getCanBeFlattened(), clang::CodeGen::ABIArgInfo::getCoerceAndExpandTypeSequence(), clang::CodeGen::ABIArgInfo::getCoerceToType(), getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), getExpandedTypes(), clang::CodeGen::ABIArgInfo::getInAllocaSRet(), clang::CodeGen::ABIArgInfo::getIndirectAddrSpace(), clang::CodeGen::ABIArgInfo::getKind(), getLLVMContext(), clang::CodeGen::CGFunctionInfo::getNumRequiredArgs(), clang::CodeGen::ABIArgInfo::getPaddingType(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), clang::CodeGen::CGFunctionInfo::getReturnType(), getTargetAddressSpace(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::ABIArgInfo::getUnpaddedCoerceAndExpandType(), clang::CodeGen::ABIArgInfo::Ignore, clang::CodeGen::ABIArgInfo::InAlloca, clang::CodeGen::ABIArgInfo::Indirect, clang::CodeGen::ABIArgInfo::IndirectAliased, clang::CodeGen::CGFunctionInfoArgInfo::info, clang::CodeGen::ABIArgInfo::isDirect(), clang::CodeGen::CGFunctionInfo::isVariadic(), clang::interp::Ret(), and clang::CodeGen::CGFunctionInfoArgInfo::type.
Referenced by clang::CodeGen::CodeGenFunction::BuildAppleKextVirtualDestructorCall(), emitAtomicLibcall(), clang::CodeGen::CodeGenFunction::EmitCall(), emitCombinerOrInitializer(), emitDestructorsFunction(), clang::CodeGen::CodeGenFunction::EmitForwardingCallToLambda(), clang::CodeGen::CodeGenModule::EmitGlobal(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaImplFn(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), emitOutlinedFunctionPrologue(), emitProxyTaskFunction(), emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), emitShuffleAndReduceFunction(), emitTaskDupFunction(), emitTaskPrivateMappingFunction(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), clang::CodeGen::CodeGenFunction::GenerateBlockFunction(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::generateDestroyHelper(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicSetterCopyHelperFunction(), clang::CodeGen::CodeGenFunction::generateThunk(), clang::CodeGen::CodeGenFunction::GenerateVarArgsThunk(), clang::CodeGen::CodeGenModule::getAddrAndTypeOfCXXStructor(), getClangCallTerminateFn(), GetFunctionType(), GetFunctionTypeForVTable(), and clang::CodeGen::CodeGenModule::TryEmitBaseDestructorAsAlias().
GetFunctionType() [2/2]
llvm::FunctionType * CodeGenTypes::GetFunctionType (GlobalDecl GD)
Definition at line 1630 of file CGCall.cpp.
References arrangeGlobalDeclaration(), and GetFunctionType().
GetFunctionTypeForVTable()
llvm::Type * CodeGenTypes::GetFunctionTypeForVTable (GlobalDecl GD)
GetFunctionTypeForVTable - Get the LLVM function type for use in a vtable, given a CXXMethodDecl.
If the method to has an incomplete return type, and/or incomplete argument types, this will return the opaque type.
Definition at line 1763 of file CGCall.cpp.
References clang::Type::castAs(), clang::GlobalDecl::getDecl(), GetFunctionType(), getLLVMContext(), clang::ValueDecl::getType(), and isFuncTypeConvertible().
getLLVMContext()
llvm::LLVMContext& clang::CodeGen::CodeGenTypes::getLLVMContext () inline
Definition at line 112 of file CodeGenTypes.h.
Referenced by ConvertRecordDeclType(), ConvertSYCLJointMatrixINTELType(), ConvertType(), ConvertTypeForMem(), GetFunctionType(), GetFunctionTypeForVTable(), and clang::CodeGen::ABIInfo::getVMContext().
getTarget()
const TargetInfo& clang::CodeGen::CodeGenTypes::getTarget () const inline
Definition at line 110 of file CodeGenTypes.h.
Referenced by clang::CodeGen::ABIInfo::appendAttributeMangling(), clang::CodeGen::ABIInfo::getTarget(), and clang::CodeGen::SwiftABIInfo::occupiesMoreThan().
getTargetAddressSpace()
unsigned CodeGenTypes::getTargetAddressSpace (QualType T) const
Definition at line 933 of file CodeGenTypes.cpp.
References getContext(), getDataLayout(), clang::ASTContext::getTargetAddressSpace(), clang::Type::isFunctionType(), and clang::T.
Referenced by ConvertType(), clang::CodeGen::CodeGenFunction::EmitCXXGlobalVarDeclInit(), GetFunctionType(), and clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress().
inheritingCtorHasParams()
bool CodeGenTypes::inheritingCtorHasParams (const InheritedConstructor & Inherited, CXXCtorType Type)
Determine if a C++ inheriting constructor should have parameters matching those of its inherited constructor.
Definition at line 326 of file CGCall.cpp.
References clang::ConstructorUsingShadowDecl::constructsVirtualBase(), clang::Ctor_Complete, and clang::InheritedConstructor::getShadowDecl().
Referenced by arrangeCXXStructorDeclaration(), clang::CodeGen::CodeGenFunction::BuildFunctionArgList(), and clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall().
isFuncParamTypeConvertible()
bool CodeGenTypes::isFuncParamTypeConvertible (QualType Ty)
isFuncParamTypeConvertible - Return true if the specified type in a function parameter or result position can be converted to an IR type at this point.
This boils down to being whether it is complete.
Definition at line 133 of file CodeGenTypes.cpp.
References clang::Type::getAs(), getCXXABI(), clang::Type::isIncompleteType(), and clang::CodeGen::CGCXXABI::isMemberPointerConvertible().
Referenced by isFuncTypeConvertible().
isFuncTypeConvertible()
bool CodeGenTypes::isFuncTypeConvertible (const FunctionType * FT)
isFuncTypeConvertible - Utility to check whether a function type can be converted to an LLVM type (i.e.
Code to verify a given function type is complete, i.e.
doesn't depend on an incomplete tag type).
the return type and all of the parameter types are complete. Also check to see if we are in a RS_StructPointer context, and if so whether any struct types have been pended. If so, we don't want to ask the ABI lowering code to handle a type that cannot be converted to an IR type.
Definition at line 154 of file CodeGenTypes.cpp.
References clang::FunctionType::getReturnType(), and isFuncParamTypeConvertible().
Referenced by GetFunctionTypeForVTable().
isLongDoubleReferenced()
bool clang::CodeGen::CodeGenTypes::isLongDoubleReferenced () const inline
Definition at line 303 of file CodeGenTypes.h.
isPointerZeroInitializable()
bool CodeGenTypes::isPointerZeroInitializable (QualType T)
Check if the pointer type can be zero-initialized (in the C++ sense) with an LLVM zeroinitializer.
Definition at line 896 of file CodeGenTypes.cpp.
References clang::Type::isAnyPointerType(), clang::Type::isBlockPointerType(), isZeroInitializable(), and clang::T.
Referenced by isSimpleZero().
isRecordLayoutComplete()
bool CodeGenTypes::isRecordLayoutComplete (const Type * Ty) const
isRecordLayoutComplete - Return true if the specified type is already completely laid out.
Definition at line 123 of file CodeGenTypes.cpp.
isZeroInitializable() [1/2]
bool CodeGenTypes::isZeroInitializable (const RecordDecl * RD)
IsZeroInitializable - Return whether a record type can be zero-initialized (in the C++ sense) with an LLVM zeroinitializer.
Definition at line 929 of file CodeGenTypes.cpp.
References getCGRecordLayout(), and clang::CodeGen::CGRecordLayout::isZeroInitializable().
isZeroInitializable() [2/2]
bool CodeGenTypes::isZeroInitializable (QualType T)
IsZeroInitializable - Return whether a type can be zero-initialized (in the C++ sense) with an LLVM zeroinitializer.
Definition at line 901 of file CodeGenTypes.cpp.
References clang::Type::getAs(), clang::ASTContext::getAsArrayType(), clang::ASTContext::getBaseElementType(), clang::ASTContext::getConstantArrayElementCount(), getCXXABI(), clang::ASTContext::getTargetNullPointerValue(), clang::CodeGen::CGCXXABI::isZeroInitializable(), and clang::T.
Referenced by clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), GetNumNonZeroBytesInInit(), isPointerZeroInitializable(), and isSimpleZero().
RefreshTypeCacheForClass()
void CodeGenTypes::RefreshTypeCacheForClass (const CXXRecordDecl * RD)
Remove stale types from the type cache when an inheritance model gets assigned to a class.
Definition at line 208 of file CodeGenTypes.cpp.
References clang::ASTContext::getCanonicalType(), clang::ASTContext::getRecordType(), and clang::T.
Referenced by clang::CodeGen::CodeGenModule::RefreshTypeCacheForClass().
UpdateCompletedType()
void CodeGenTypes::UpdateCompletedType (const TagDecl * TD)
UpdateCompletedType - When we find the full definition for a TagDecl, replace the 'opaque' type we previously made for it if applicable.
Definition at line 168 of file CodeGenTypes.cpp.
References ConvertRecordDeclType(), ConvertType(), clang::CodeGen::CodeGenModule::getModuleDebugInfo(), clang::ASTContext::getTagDeclType(), clang::QualType::getTypePtr(), clang::TagDecl::isDependentType(), and clang::CodeGen::CodeGenModule::setAspectsEnumDecl().
Referenced by clang::CodeGen::CodeGenModule::UpdateCompletedType().
The documentation for this class was generated from the following files:
lib/CodeGen/CodeGenTypes.h
lib/CodeGen/CGCall.cpp
lib/CodeGen/CGRecordLayoutBuilder.cpp
lib/CodeGen/CodeGenTypes.cpp