clang: clang::CodeGen::CGFunctionInfo Class Reference
clang::CodeGen::CGFunctionInfo Class Reference final
CGFunctionInfo - Class to encapsulate the information about a function definition.
#include "clang/CodeGen/CGFunctionInfo.h"
Public Types
typedef const ArgInfo * const_arg_iterator
typedef ArgInfo * arg_iterator
Public Member Functions
void operator delete (void *p)
size_t numTrailingObjects (OverloadToken< ArgInfo >) const
size_t numTrailingObjects (OverloadToken< ExtParameterInfo >) const
MutableArrayRef< ArgInfo > arguments ()
ArrayRef< ArgInfo > arguments () const
const_arg_iterator arg_begin () const
const_arg_iterator arg_end () const
arg_iterator arg_begin ()
arg_iterator arg_end ()
unsigned arg_size () const
bool isVariadic () const
RequiredArgs getRequiredArgs () const
unsigned getNumRequiredArgs () const
bool isInstanceMethod () const
bool isChainCall () const
bool isDelegateCall () const
bool isCmseNSCall () const
bool isNoReturn () const
bool isReturnsRetained () const
In ARC, whether this function retains its return value.
bool isNoCallerSavedRegs () const
Whether this function no longer saves caller registers.
bool isNoCfCheck () const
Whether this function has nocf_check attribute.
CallingConv getASTCallingConvention () const
getASTCallingConvention() - Return the AST-specified calling convention.
unsigned getCallingConvention () const
getCallingConvention - Return the user specified calling convention, which has been translated into an LLVM CC.
unsigned getEffectiveCallingConvention () const
getEffectiveCallingConvention - Return the actual calling convention to use, which may depend on the ABI.
void setEffectiveCallingConvention (unsigned Value)
bool getHasRegParm () const
unsigned getRegParm () const
FunctionType::ExtInfo getExtInfo () const
CanQualType getReturnType () const
ABIArgInfo & getReturnInfo ()
const ABIArgInfo & getReturnInfo () const
ArrayRef< ExtParameterInfo > getExtParameterInfos () const
ExtParameterInfo getExtParameterInfo (unsigned argIndex) const
bool usesInAlloca () const
Return true if this function uses inalloca arguments.
llvm::StructType * getArgStruct () const
Get the struct type used to represent all the arguments in memory.
CharUnits getArgStructAlignment () const
void setArgStruct (llvm::StructType *Ty, CharUnits Align)
unsigned getMaxVectorWidth () const
Return the maximum vector width in the arguments.
void setMaxVectorWidth (unsigned Width)
Set the maximum vector width in the arguments.
void Profile (llvm::FoldingSetNodeID &ID)
Static Public Member Functions
static CGFunctionInfo * create (unsigned llvmCC, bool instanceMethod, bool chainCall, bool delegateCall, const FunctionType::ExtInfo &extInfo, ArrayRef< ExtParameterInfo > paramInfos, CanQualType resultType, ArrayRef< CanQualType > argTypes, RequiredArgs required)
static void Profile (llvm::FoldingSetNodeID &ID, bool InstanceMethod, bool ChainCall, bool IsDelegateCall, const FunctionType::ExtInfo &info, ArrayRef< ExtParameterInfo > paramInfos, RequiredArgs required, CanQualType resultType, ArrayRef< CanQualType > argTypes)
Friends
class TrailingObjects
Detailed Description
CGFunctionInfo - Class to encapsulate the information about a function definition.
Definition at line 551 of file CGFunctionInfo.h.
Member Typedef Documentation
arg_iterator
typedef ArgInfo* clang::CodeGen::CGFunctionInfo::arg_iterator
Definition at line 657 of file CGFunctionInfo.h.
const_arg_iterator
typedef const ArgInfo* clang::CodeGen::CGFunctionInfo::const_arg_iterator
Definition at line 656 of file CGFunctionInfo.h.
Member Function Documentation
arg_begin() [1/2]
arg_iterator clang::CodeGen::CGFunctionInfo::arg_begin () inline
Definition at line 668 of file CGFunctionInfo.h.
arg_begin() [2/2]
const_arg_iterator clang::CodeGen::CGFunctionInfo::arg_begin () const inline
Definition at line 666 of file CGFunctionInfo.h.
Referenced by arguments(), clang::CodeGen::swiftcall::computeABIInfo(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaImplFn(), clang::CodeGen::CodeGenFunction::EmitMustTailThunk(), and clang::CodeGen::CodeGenTypes::GetFunctionType().
arg_end() [1/2]
arg_iterator clang::CodeGen::CGFunctionInfo::arg_end () inline
Definition at line 669 of file CGFunctionInfo.h.
arg_end() [2/2]
const_arg_iterator clang::CodeGen::CGFunctionInfo::arg_end () const inline
Definition at line 667 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaImplFn().
arg_size()
unsigned clang::CodeGen::CGFunctionInfo::arg_size () const inline
Definition at line 671 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall(), clang::CodeGen::swiftcall::computeABIInfo(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), and getNumRequiredArgs().
arguments() [1/2]
MutableArrayRef<ArgInfo> clang::CodeGen::CGFunctionInfo::arguments () inline
Definition at line 659 of file CGFunctionInfo.h.
References arg_begin().
Referenced by clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), clang::CodeGen::DefaultABIInfo::computeInfo(), PNaClABIInfo::computeInfo(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), and Profile().
arguments() [2/2]
ArrayRef<ArgInfo> clang::CodeGen::CGFunctionInfo::arguments () const inline
Definition at line 662 of file CGFunctionInfo.h.
References arg_begin().
create()
CGFunctionInfo * CGFunctionInfo::create (unsigned llvmCC, bool instanceMethod, bool chainCall, bool delegateCall, const FunctionType::ExtInfo & extInfo, ArrayRef< ExtParameterInfo > paramInfos, CanQualType resultType, ArrayRef< CanQualType > argTypes, RequiredArgs required) static
Definition at line 838 of file CGCall.cpp.
References clang::CodeGen::RequiredArgs::allowsOptionalArgs(), clang::FunctionType::ExtInfo::getCC(), clang::FunctionType::ExtInfo::getCmseNSCall(), clang::FunctionType::ExtInfo::getHasRegParm(), clang::FunctionType::ExtInfo::getNoCallerSavedRegs(), clang::FunctionType::ExtInfo::getNoCfCheck(), clang::FunctionType::ExtInfo::getNoReturn(), clang::CodeGen::RequiredArgs::getNumRequiredArgs(), clang::FunctionType::ExtInfo::getProducesResult(), clang::FunctionType::ExtInfo::getRegParm(), and clang::CodeGen::CGFunctionInfoArgInfo::type.
Referenced by clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo().
getArgStruct()
llvm::StructType* clang::CodeGen::CGFunctionInfo::getArgStruct () const inline
Get the struct type used to represent all the arguments in memory.
Definition at line 747 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), and clang::CodeGen::CodeGenFunction::StartFunction().
getArgStructAlignment()
CharUnits clang::CodeGen::CGFunctionInfo::getArgStructAlignment () const inline
Definition at line 748 of file CGFunctionInfo.h.
References clang::CharUnits::fromQuantity().
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), and clang::CodeGen::CodeGenFunction::EmitFunctionProlog().
getASTCallingConvention()
CallingConv clang::CodeGen::CGFunctionInfo::getASTCallingConvention () const inline
getASTCallingConvention() - Return the AST-specified calling convention.
Definition at line 701 of file CGFunctionInfo.h.
Referenced by getExtInfo(), and Profile().
getCallingConvention()
unsigned clang::CodeGen::CGFunctionInfo::getCallingConvention () const inline
getCallingConvention - Return the user specified calling convention, which has been translated into an LLVM CC.
Definition at line 707 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk().
getEffectiveCallingConvention()
unsigned clang::CodeGen::CGFunctionInfo::getEffectiveCallingConvention () const inline
getEffectiveCallingConvention - Return the actual calling convention to use, which may depend on the ABI.
Definition at line 711 of file CGFunctionInfo.h.
getExtInfo()
FunctionType::ExtInfo clang::CodeGen::CGFunctionInfo::getExtInfo () const inline
Definition at line 721 of file CGFunctionInfo.h.
References getASTCallingConvention(), getHasRegParm(), getRegParm(), isCmseNSCall(), isNoCallerSavedRegs(), isNoCfCheck(), isNoReturn(), and isReturnsRetained().
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall(), and clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaImplFn().
getExtParameterInfo()
ExtParameterInfo clang::CodeGen::CGFunctionInfo::getExtParameterInfo (unsigned argIndex) const inline
Definition at line 737 of file CGFunctionInfo.h.
References getExtParameterInfos().
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), and clang::CodeGen::CodeGenFunction::EmitFunctionProlog().
getExtParameterInfos()
ArrayRef<ExtParameterInfo> clang::CodeGen::CGFunctionInfo::getExtParameterInfos () const inline
Definition at line 733 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall(), getExtParameterInfo(), and Profile().
getHasRegParm()
bool clang::CodeGen::CGFunctionInfo::getHasRegParm () const inline
Definition at line 718 of file CGFunctionInfo.h.
Referenced by getExtInfo().
getMaxVectorWidth()
unsigned clang::CodeGen::CGFunctionInfo::getMaxVectorWidth () const inline
Return the maximum vector width in the arguments.
Definition at line 757 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenFunction::FinishFunction().
getNumRequiredArgs()
unsigned clang::CodeGen::CGFunctionInfo::getNumRequiredArgs () const inline
Definition at line 675 of file CGFunctionInfo.h.
References arg_size(), clang::CodeGen::RequiredArgs::getNumRequiredArgs(), getRequiredArgs(), and isVariadic().
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), and clang::CodeGen::CodeGenTypes::GetFunctionType().
getRegParm()
unsigned clang::CodeGen::CGFunctionInfo::getRegParm () const inline
Definition at line 719 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), and getExtInfo().
getRequiredArgs()
RequiredArgs clang::CodeGen::CGFunctionInfo::getRequiredArgs () const inline
Definition at line 674 of file CGFunctionInfo.h.
References clang::Required.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall(), clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaImplFn(), and getNumRequiredArgs().
getReturnInfo() [1/2]
ABIArgInfo& clang::CodeGen::CGFunctionInfo::getReturnInfo () inline
Definition at line 730 of file CGFunctionInfo.h.
References clang::CodeGen::CGFunctionInfoArgInfo::info.
Referenced by clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), clang::CodeGen::classifyReturnType(), clang::CodeGen::swiftcall::computeABIInfo(), clang::CodeGen::DefaultABIInfo::computeInfo(), PNaClABIInfo::computeInfo(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::EmitForwardingCallToLambda(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitMustTailThunk(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::ReturnTypeUsesSRet(), and clang::CodeGen::CodeGenFunction::StartFunction().
getReturnInfo() [2/2]
const ABIArgInfo& clang::CodeGen::CGFunctionInfo::getReturnInfo () const inline
Definition at line 731 of file CGFunctionInfo.h.
References clang::CodeGen::CGFunctionInfoArgInfo::info.
getReturnType()
CanQualType clang::CodeGen::CGFunctionInfo::getReturnType () const inline
Definition at line 728 of file CGFunctionInfo.h.
References clang::CodeGen::CGFunctionInfoArgInfo::type.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall(), clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), clang::CodeGen::classifyReturnType(), clang::CodeGen::swiftcall::computeABIInfo(), clang::CodeGen::DefaultABIInfo::computeInfo(), PNaClABIInfo::computeInfo(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::EmitForwardingCallToLambda(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaImplFn(), clang::CodeGen::CodeGenTypes::GetFunctionType(), Profile(), and clang::CodeGen::CodeGenFunction::StartFunction().
isChainCall()
bool clang::CodeGen::CGFunctionInfo::isChainCall () const inline
Definition at line 681 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall().
isCmseNSCall()
bool clang::CodeGen::CGFunctionInfo::isCmseNSCall () const inline
Definition at line 685 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), and getExtInfo().
isDelegateCall()
bool clang::CodeGen::CGFunctionInfo::isDelegateCall () const inline
Definition at line 683 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall(), and clang::CodeGen::CodeGenFunction::GenerateCode().
isInstanceMethod()
bool clang::CodeGen::CGFunctionInfo::isInstanceMethod () const inline
Definition at line 679 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall().
isNoCallerSavedRegs()
bool clang::CodeGen::CGFunctionInfo::isNoCallerSavedRegs () const inline
Whether this function no longer saves caller registers.
Definition at line 694 of file CGFunctionInfo.h.
Referenced by getExtInfo().
isNoCfCheck()
bool clang::CodeGen::CGFunctionInfo::isNoCfCheck () const inline
Whether this function has nocf_check attribute.
Definition at line 697 of file CGFunctionInfo.h.
Referenced by getExtInfo().
isNoReturn()
bool clang::CodeGen::CGFunctionInfo::isNoReturn () const inline
Definition at line 687 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), and getExtInfo().
isReturnsRetained()
bool clang::CodeGen::CGFunctionInfo::isReturnsRetained () const inline
In ARC, whether this function retains its return value.
This is not always reliable for call sites.
Definition at line 691 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), getExtInfo(), and clang::CodeGen::CodeGenFunction::StartFunction().
isVariadic()
bool clang::CodeGen::CGFunctionInfo::isVariadic () const inline
Definition at line 673 of file CGFunctionInfo.h.
References clang::Required.
Referenced by clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::GenerateVarArgsThunk(), clang::CodeGen::CodeGenTypes::GetFunctionType(), and getNumRequiredArgs().
numTrailingObjects() [1/2]
size_t clang::CodeGen::CGFunctionInfo::numTrailingObjects (OverloadToken< ArgInfo >) const inline
Definition at line 649 of file CGFunctionInfo.h.
numTrailingObjects() [2/2]
size_t clang::CodeGen::CGFunctionInfo::numTrailingObjects (OverloadToken< ExtParameterInfo >) const inline
Definition at line 652 of file CGFunctionInfo.h.
operator delete()
void clang::CodeGen::CGFunctionInfo::operator delete (void * p) inline
Definition at line 644 of file CGFunctionInfo.h.
Profile() [1/2]
void clang::CodeGen::CGFunctionInfo::Profile (llvm::FoldingSetNodeID & ID) inline
Definition at line 767 of file CGFunctionInfo.h.
References arguments(), getASTCallingConvention(), getExtParameterInfos(), getReturnType(), ID, clang::CanQual< T >::Profile(), and clang::Required.
Referenced by clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo().
Profile() [2/2]
static void clang::CodeGen::CGFunctionInfo::Profile (llvm::FoldingSetNodeID & ID, bool InstanceMethod, bool ChainCall, bool IsDelegateCall, const FunctionType::ExtInfo & info, ArrayRef< ExtParameterInfo > paramInfos, RequiredArgs required, CanQualType resultType, ArrayRef< CanQualType > argTypes) inline static
Definition at line 789 of file CGFunctionInfo.h.
References clang::FunctionType::ExtInfo::getCC(), clang::FunctionType::ExtInfo::getCmseNSCall(), clang::FunctionType::ExtInfo::getHasRegParm(), clang::FunctionType::ExtInfo::getNoCallerSavedRegs(), clang::FunctionType::ExtInfo::getNoCfCheck(), clang::FunctionType::ExtInfo::getNoReturn(), clang::CodeGen::RequiredArgs::getOpaqueData(), clang::FunctionType::ExtInfo::getProducesResult(), clang::FunctionType::ExtInfo::getRegParm(), ID, clang::CodeGen::IsDelegateCall, and clang::CanQual< T >::Profile().
setArgStruct()
void clang::CodeGen::CGFunctionInfo::setArgStruct (llvm::StructType * Ty, CharUnits Align) inline
Definition at line 751 of file CGFunctionInfo.h.
References clang::CharUnits::getQuantity().
setEffectiveCallingConvention()
void clang::CodeGen::CGFunctionInfo::setEffectiveCallingConvention (unsigned Value) inline
Definition at line 714 of file CGFunctionInfo.h.
setMaxVectorWidth()
void clang::CodeGen::CGFunctionInfo::setMaxVectorWidth (unsigned Width) inline
Set the maximum vector width in the arguments.
Definition at line 762 of file CGFunctionInfo.h.
usesInAlloca()
bool clang::CodeGen::CGFunctionInfo::usesInAlloca () const inline
Return true if this function uses inalloca arguments.
Definition at line 744 of file CGFunctionInfo.h.
Referenced by canEmitDelegateCallArgs(), and clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk().
Friends And Related Function Documentation
TrailingObjects
friend class TrailingObjects friend
Definition at line 648 of file CGFunctionInfo.h.
The documentation for this class was generated from the following files:
include/clang/CodeGen/CGFunctionInfo.h
lib/CodeGen/CGCall.cpp