clang: clang::CodeGen::ApplyInlineDebugLocation Class Reference
clang::CodeGen::ApplyInlineDebugLocation Class Reference
A scoped helper to set the current debug location to an inlined location.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGDebugInfo.h"
Public Member Functions
ApplyInlineDebugLocation (CodeGenFunction &CGF, GlobalDecl InlinedFn)
Set up the CodeGenFunction's DebugInfo to produce inline locations for the function InlinedFn.
~ApplyInlineDebugLocation ()
Restore everything back to the original state.
Detailed Description
A scoped helper to set the current debug location to an inlined location.
Definition at line 892 of file CGDebugInfo.h.
Constructor & Destructor Documentation
ApplyInlineDebugLocation()
ApplyInlineDebugLocation::ApplyInlineDebugLocation (CodeGenFunction & CGF, GlobalDecl InlinedFn)
Set up the CodeGenFunction's DebugInfo to produce inline locations for the function InlinedFn.
The current debug location becomes the inlined call site of the inlined function.
Definition at line 150 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CodeGenFunction::getDebugInfo().
~ApplyInlineDebugLocation()
ApplyInlineDebugLocation::~ApplyInlineDebugLocation ()
Restore everything back to the original state.
Definition at line 166 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CGDebugInfo::EmitInlineFunctionEnd(), and clang::CodeGen::CodeGenFunction::getDebugInfo().
The documentation for this class was generated from the following files:
lib/CodeGen/CGDebugInfo.h
lib/CodeGen/CGDebugInfo.cpp