clang: clang::LinkageInfo Class Reference
clang::LinkageInfo Class Reference
#include "clang/Basic/Visibility.h"
Public Member Functions
LinkageInfo ()
LinkageInfo (Linkage L, Visibility V, bool E)
Linkage getLinkage () const
Visibility getVisibility () const
bool isVisibilityExplicit () const
void setLinkage (Linkage L)
void mergeLinkage (Linkage L)
void mergeLinkage (LinkageInfo other)
void mergeExternalVisibility (Linkage L)
void mergeExternalVisibility (LinkageInfo Other)
void mergeVisibility (Visibility newVis, bool newExplicit)
Merge in the visibility 'newVis'.
void mergeVisibility (LinkageInfo other)
void merge (LinkageInfo other)
Merge both linkage and visibility.
void mergeMaybeWithVisibility (LinkageInfo other, bool withVis)
Merge linkage and conditionally merge visibility.
Static Public Member Functions
static LinkageInfo external ()
static LinkageInfo internal ()
static LinkageInfo uniqueExternal ()
static LinkageInfo none ()
static LinkageInfo visible_none ()
Detailed Description
Definition at line 53 of file Visibility.h.
Constructor & Destructor Documentation
LinkageInfo() [1/2]
clang::LinkageInfo::LinkageInfo () inline
Definition at line 63 of file Visibility.h.
References clang::External.
Referenced by external(), internal(), none(), uniqueExternal(), and visible_none().
LinkageInfo() [2/2]
clang::LinkageInfo::LinkageInfo (Linkage L, Visibility V, bool E) inline
Definition at line 66 of file Visibility.h.
References getLinkage(), getVisibility(), isVisibilityExplicit(), and V.
Member Function Documentation
external()
static LinkageInfo clang::LinkageInfo::external () inline static
Definition at line 72 of file Visibility.h.
References LinkageInfo().
Referenced by clang::LinkageComputer::computeTypeLinkageInfo(), and getExternalLinkageFor().
getLinkage()
Linkage clang::LinkageInfo::getLinkage () const inline
Definition at line 88 of file Visibility.h.
Referenced by clang::NamedDecl::getLinkageInternal(), clang::LinkageComputer::getLVForDecl(), clang::LinkageComputer::getTypeLinkageAndVisibility(), clang::CodeGen::CodeGenModule::GetVCallVisibilityLevel(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), clang::NamedDecl::isLinkageValid(), clang::Type::isLinkageValid(), LinkageInfo(), mergeExternalVisibility(), mergeLinkage(), and setLinkageForGV().
getVisibility()
Visibility clang::LinkageInfo::getVisibility () const inline
Definition at line 89 of file Visibility.h.
Referenced by clang::NamedDecl::getVisibility(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), LinkageInfo(), mergeVisibility(), clang::CodeGen::CodeGenModule::setGlobalVisibility(), and clang::CodeGen::CodeGenModule::shouldMapVisibilityToDLLExport().
internal()
static LinkageInfo clang::LinkageInfo::internal () inline static
Definition at line 75 of file Visibility.h.
References clang::DefaultVisibility, clang::Internal, and LinkageInfo().
Referenced by clang::LinkageComputer::computeLVForDecl(), and clang::LinkageComputer::getLVForDecl().
isVisibilityExplicit()
bool clang::LinkageInfo::isVisibilityExplicit () const inline
Definition at line 90 of file Visibility.h.
Referenced by LinkageInfo(), mergeVisibility(), clang::CodeGen::CodeGenModule::setGlobalVisibility(), and clang::CodeGen::CodeGenModule::shouldMapVisibilityToDLLExport().
merge()
void clang::LinkageInfo::merge (LinkageInfo other) inline
Merge both linkage and visibility.
Definition at line 137 of file Visibility.h.
References mergeLinkage(), and mergeVisibility().
Referenced by clang::LinkageComputer::computeLVForDecl(), and clang::LinkageComputer::computeTypeLinkageInfo().
mergeExternalVisibility() [1/2]
void clang::LinkageInfo::mergeExternalVisibility (Linkage L) inline
Definition at line 101 of file Visibility.h.
References clang::External, getLinkage(), clang::isExternallyVisible(), clang::None, setLinkage(), clang::UniqueExternal, and clang::VisibleNone.
Referenced by mergeExternalVisibility().
mergeExternalVisibility() [2/2]
void clang::LinkageInfo::mergeExternalVisibility (LinkageInfo Other) inline
Definition at line 111 of file Visibility.h.
References mergeExternalVisibility(), and clang::Other.
mergeLinkage() [1/2]
void clang::LinkageInfo::mergeLinkage (Linkage L) inline
Definition at line 94 of file Visibility.h.
References getLinkage(), clang::minLinkage(), and setLinkage().
Referenced by merge(), mergeLinkage(), and mergeMaybeWithVisibility().
mergeLinkage() [2/2]
void clang::LinkageInfo::mergeLinkage (LinkageInfo other) inline
Definition at line 97 of file Visibility.h.
References getLinkage(), and mergeLinkage().
mergeMaybeWithVisibility()
void clang::LinkageInfo::mergeMaybeWithVisibility (LinkageInfo other, bool withVis) inline
Merge linkage and conditionally merge visibility.
Definition at line 143 of file Visibility.h.
References mergeLinkage(), and mergeVisibility().
mergeVisibility() [1/2]
void clang::LinkageInfo::mergeVisibility (LinkageInfo other) inline
Definition at line 132 of file Visibility.h.
References getVisibility(), isVisibilityExplicit(), and mergeVisibility().
mergeVisibility() [2/2]
void clang::LinkageInfo::mergeVisibility (Visibility newVis, bool newExplicit) inline
Merge in the visibility 'newVis'.
Definition at line 116 of file Visibility.h.
References getVisibility().
Referenced by merge(), mergeMaybeWithVisibility(), and mergeVisibility().
none()
static LinkageInfo clang::LinkageInfo::none () inline static
Definition at line 81 of file Visibility.h.
References clang::DefaultVisibility, LinkageInfo(), and clang::None.
Referenced by clang::LinkageComputer::computeLVForDecl().
setLinkage()
void clang::LinkageInfo::setLinkage (Linkage L) inline
Definition at line 92 of file Visibility.h.
Referenced by mergeExternalVisibility(), mergeLinkage(), and setLinkageForGV().
uniqueExternal()
static LinkageInfo clang::LinkageInfo::uniqueExternal () inline static
Definition at line 78 of file Visibility.h.
References clang::DefaultVisibility, LinkageInfo(), and clang::UniqueExternal.
visible_none()
static LinkageInfo clang::LinkageInfo::visible_none () inline static
Definition at line 84 of file Visibility.h.
References clang::DefaultVisibility, LinkageInfo(), and clang::VisibleNone.
Referenced by clang::LinkageComputer::computeLVForDecl().
The documentation for this class was generated from the following file:
include/clang/Basic/Visibility.h