clang: clang::extractapi::DeclarationFragmentsBuilder Class Reference
clang::extractapi::DeclarationFragmentsBuilder Class Reference
A factory class to build DeclarationFragments for different kinds of Decl.
#include "clang/ExtractAPI/DeclarationFragments.h"
Static Public Member Functions
template<typename FunctionT >
static FunctionSignature getFunctionSignature (const FunctionT *Function)
Build FunctionSignature for a function-like declaration FunctionT like FunctionDecl, ObjCMethodDecl, or CXXMethodDecl.
static AccessControl getAccessControl (const Decl *Decl)
static DeclarationFragments getFragmentsForNamespace (const NamespaceDecl *Decl)
static DeclarationFragments getFragmentsForVar (const VarDecl *)
Build DeclarationFragments for a variable declaration VarDecl.
static DeclarationFragments getFragmentsForVarTemplate (const VarDecl *)
static DeclarationFragments getFragmentsForFunction (const FunctionDecl *)
Build DeclarationFragments for a function declaration FunctionDecl.
static DeclarationFragments getFragmentsForEnumConstant (const EnumConstantDecl *)
Build DeclarationFragments for an enum constant declaration EnumConstantDecl.
static DeclarationFragments getFragmentsForEnum (const EnumDecl *)
Build DeclarationFragments for an enum declaration EnumDecl.
static DeclarationFragments getFragmentsForField (const FieldDecl *)
Build DeclarationFragments for a field declaration FieldDecl.
static DeclarationFragments getFragmentsForRecordDecl (const RecordDecl *)
Build DeclarationFragments for a struct/union record declaration RecordDecl.
static DeclarationFragments getFragmentsForCXXClass (const CXXRecordDecl *)
static DeclarationFragments getFragmentsForSpecialCXXMethod (const CXXMethodDecl *)
static DeclarationFragments getFragmentsForCXXMethod (const CXXMethodDecl *)
static DeclarationFragments getFragmentsForConversionFunction (const CXXConversionDecl *)
static DeclarationFragments getFragmentsForOverloadedOperator (const CXXMethodDecl *)
static DeclarationFragments getFragmentsForTemplateParameters (ArrayRef< NamedDecl * >)
static DeclarationFragments getFragmentsForTemplateArguments (const ArrayRef< TemplateArgument >, ASTContext &, const std::optional< ArrayRef< TemplateArgumentLoc >>)
static DeclarationFragments getFragmentsForConcept (const ConceptDecl *)
static DeclarationFragments getFragmentsForRedeclarableTemplate (const RedeclarableTemplateDecl *)
static DeclarationFragments getFragmentsForClassTemplateSpecialization (const ClassTemplateSpecializationDecl *)
static DeclarationFragments getFragmentsForClassTemplatePartialSpecialization (const ClassTemplatePartialSpecializationDecl *)
static DeclarationFragments getFragmentsForVarTemplateSpecialization (const VarTemplateSpecializationDecl *)
static DeclarationFragments getFragmentsForVarTemplatePartialSpecialization (const VarTemplatePartialSpecializationDecl *)
static DeclarationFragments getFragmentsForFunctionTemplate (const FunctionTemplateDecl *Decl)
static DeclarationFragments getFragmentsForFunctionTemplateSpecialization (const FunctionDecl *Decl)
static DeclarationFragments getFragmentsForObjCCategory (const ObjCCategoryDecl *)
Build DeclarationFragments for an Objective-C category declaration ObjCCategoryDecl.
static DeclarationFragments getFragmentsForObjCInterface (const ObjCInterfaceDecl *)
Build DeclarationFragments for an Objective-C interface declaration ObjCInterfaceDecl.
static DeclarationFragments getFragmentsForObjCMethod (const ObjCMethodDecl *)
Build DeclarationFragments for an Objective-C method declaration ObjCMethodDecl.
static DeclarationFragments getFragmentsForObjCProperty (const ObjCPropertyDecl *)
Build DeclarationFragments for an Objective-C property declaration ObjCPropertyDecl.
static DeclarationFragments getFragmentsForObjCProtocol (const ObjCProtocolDecl *)
Build DeclarationFragments for an Objective-C protocol declaration ObjCProtocolDecl.
static DeclarationFragments getFragmentsForMacro (StringRef Name, const MacroDirective *MD)
Build DeclarationFragments for a macro.
static DeclarationFragments getFragmentsForTypedef (const TypedefNameDecl *Decl)
Build DeclarationFragments for a typedef TypedefNameDecl.
static DeclarationFragments getSubHeading (const NamedDecl *)
Build sub-heading fragments for a NamedDecl.
static DeclarationFragments getSubHeading (const ObjCMethodDecl *)
Build sub-heading fragments for an Objective-C method.
static DeclarationFragments getSubHeadingForMacro (StringRef Name)
Build a sub-heading for macro Name.
Detailed Description
A factory class to build DeclarationFragments for different kinds of Decl.
Definition at line 294 of file DeclarationFragments.h.
Member Function Documentation
getAccessControl()
static AccessControl clang::extractapi::DeclarationFragmentsBuilder::getAccessControl (const Decl * Decl) inline static
Definition at line 305 of file DeclarationFragments.h.
References clang::AS_none, clang::AS_private, clang::AS_protected, clang::AS_public, and clang::Decl::getAccess().
getFragmentsForClassTemplatePartialSpecialization()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForClassTemplatePartialSpecialization (const ClassTemplatePartialSpecializationDecl * Decl) static
Definition at line 1075 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), getFragmentsForCXXClass(), clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::pop_back(), and clang::extractapi::DeclarationFragments::Text.
getFragmentsForClassTemplateSpecialization()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForClassTemplateSpecialization (const ClassTemplateSpecializationDecl * Decl) static
Definition at line 1055 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), getFragmentsForCXXClass(), clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::pop_back(), and clang::extractapi::DeclarationFragments::Text.
getFragmentsForConcept()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForConcept (const ConceptDecl * Concept) static
Definition at line 1017 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForConversionFunction()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForConversionFunction (const CXXConversionDecl * ConversionFunction) static
Definition at line 883 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::Text, and clang::extractapi::DeclarationFragments::TypeIdentifier.
getFragmentsForCXXClass()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForCXXClass (const CXXRecordDecl * Record) static
Definition at line 797 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::extractapi::DeclarationFragments::getStructureTypeFragment(), and clang::extractapi::DeclarationFragments::Identifier.
Referenced by getFragmentsForClassTemplatePartialSpecialization(), and getFragmentsForClassTemplateSpecialization().
getFragmentsForCXXMethod()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForCXXMethod (const CXXMethodDecl * Method) static
Definition at line 842 of file DeclarationFragments.cpp.
getFragmentsForEnum()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForEnum (const EnumDecl * EnumDecl) static
Build DeclarationFragments for an enum declaration EnumDecl.
Definition at line 734 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), clang::EnumDecl::getIntegerType(), clang::NamedDecl::getName(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::extractapi::DeclarationFragments::Identifier, clang::QualType::isNull(), clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForEnumConstant()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForEnumConstant (const EnumConstantDecl * EnumConstDecl) static
Build DeclarationFragments for an enum constant declaration EnumConstantDecl.
Definition at line 726 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::NamedDecl::getName(), and clang::extractapi::DeclarationFragments::Identifier.
getFragmentsForField()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForField (const FieldDecl * Field) static
Build DeclarationFragments for a field declaration FieldDecl.
Definition at line 761 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::extractapi::DeclarationFragments::Identifier, and clang::extractapi::DeclarationFragments::Keyword.
getFragmentsForFunction()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForFunction (const FunctionDecl * Func) static
Build DeclarationFragments for a function declaration FunctionDecl.
Definition at line 651 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Func, clang::extractapi::DeclarationFragments::getExceptionSpecificationString(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, clang::SC_Auto, clang::SC_Extern, clang::SC_None, clang::SC_PrivateExtern, clang::SC_Register, clang::SC_Static, and clang::extractapi::DeclarationFragments::Text.
Referenced by getFragmentsForFunctionTemplate(), and getFragmentsForFunctionTemplateSpecialization().
getFragmentsForFunctionTemplate()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForFunctionTemplate (const FunctionTemplateDecl * Decl) static
Definition at line 1138 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getAsFunction(), getFragmentsForFunction(), clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForFunctionTemplateSpecialization()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForFunctionTemplateSpecialization (const FunctionDecl * Decl) static
Definition at line 1154 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), getFragmentsForFunction(), clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForMacro()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForMacro (StringRef Name, const MacroDirective * MD) static
Build DeclarationFragments for a macro.
Parameters
Name name of the macro.
MD the associated MacroDirective.
Definition at line 1165 of file DeclarationFragments.cpp.
getFragmentsForNamespace()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForNamespace (const NamespaceDecl * Decl) static
Definition at line 484 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::extractapi::DeclarationFragments::Identifier, and clang::extractapi::DeclarationFragments::Keyword.
getFragmentsForObjCCategory()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCCategory (const ObjCCategoryDecl * Category) static
Build DeclarationFragments for an Objective-C category declaration ObjCCategoryDecl.
Definition at line 1195 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), Category, clang::index::generateUSRForDecl(), clang::extractapi::DeclarationFragments::Identifier, clang::Interface, clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::Text, and clang::extractapi::DeclarationFragments::TypeIdentifier.
getFragmentsForObjCInterface()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCInterface (const ObjCInterfaceDecl * Interface) static
Build DeclarationFragments for an Objective-C interface declaration ObjCInterfaceDecl.
Definition at line 1216 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::index::generateUSRForDecl(), clang::extractapi::DeclarationFragments::Identifier, clang::Interface, clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::Text, and clang::extractapi::DeclarationFragments::TypeIdentifier.
getFragmentsForObjCMethod()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCMethod (const ObjCMethodDecl * Method) static
Build DeclarationFragments for an Objective-C method declaration ObjCMethodDecl.
Definition at line 1238 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), clang::Selector::getNameForSlot(), clang::Selector::getNumArgs(), clang::ObjCMethodDecl::getParamDecl(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), clang::extractapi::DeclarationFragments::Identifier, clang::ObjCMethodDecl::isClassMethod(), clang::ObjCMethodDecl::isInstanceMethod(), clang::ObjCMethodDecl::param_size(), and clang::extractapi::DeclarationFragments::Text.
getFragmentsForObjCProperty()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCProperty (const ObjCPropertyDecl * Property) static
Build DeclarationFragments for an Objective-C property declaration ObjCPropertyDecl.
Definition at line 1282 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::First, clang::getNullabilitySpelling(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, clang::ObjCPropertyAttribute::kind_assign, clang::ObjCPropertyAttribute::kind_atomic, clang::ObjCPropertyAttribute::kind_class, clang::ObjCPropertyAttribute::kind_copy, clang::ObjCPropertyAttribute::kind_direct, clang::ObjCPropertyAttribute::kind_getter, clang::ObjCPropertyAttribute::kind_noattr, clang::ObjCPropertyAttribute::kind_nonatomic, clang::ObjCPropertyAttribute::kind_null_resettable, clang::ObjCPropertyAttribute::kind_nullability, clang::ObjCPropertyAttribute::kind_readonly, clang::ObjCPropertyAttribute::kind_readwrite, clang::ObjCPropertyAttribute::kind_retain, clang::ObjCPropertyAttribute::kind_setter, clang::ObjCPropertyAttribute::kind_strong, clang::ObjCPropertyAttribute::kind_unsafe_unretained, clang::ObjCPropertyAttribute::kind_weak, clang::Property, clang::AttributedType::stripOuterNullability(), clang::extractapi::DeclarationFragments::Text, and clang::Unspecified.
getFragmentsForObjCProtocol()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForObjCProtocol (const ObjCProtocolDecl * Protocol) static
Build DeclarationFragments for an Objective-C protocol declaration ObjCProtocolDecl.
Definition at line 1383 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::index::generateUSRForDecl(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::Text, and clang::extractapi::DeclarationFragments::TypeIdentifier.
getFragmentsForOverloadedOperator()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForOverloadedOperator (const CXXMethodDecl * Method) static
Definition at line 914 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), clang::extractapi::DeclarationFragments::getExceptionSpecificationString(), clang::FunctionDecl::getExceptionSpecType(), clang::NamedDecl::getNameAsString(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::FunctionDecl::getReturnType(), clang::extractapi::DeclarationFragments::Identifier, clang::CXXMethodDecl::isConst(), clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForRecordDecl()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForRecordDecl (const RecordDecl * Record) static
Build DeclarationFragments for a struct/union record declaration RecordDecl.
Definition at line 776 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForRedeclarableTemplate()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForRedeclarableTemplate (const RedeclarableTemplateDecl * RedeclarableTemplate) static
Definition at line 1034 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::TemplateParameterList::asArray(), clang::NamedDecl::getName(), clang::TemplateDecl::getTemplateParameters(), clang::extractapi::DeclarationFragments::Identifier, clang::extractapi::DeclarationFragments::Keyword, and clang::extractapi::DeclarationFragments::Text.
getFragmentsForSpecialCXXMethod()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForSpecialCXXMethod (const CXXMethodDecl * Method) static
Definition at line 813 of file DeclarationFragments.cpp.
getFragmentsForTemplateArguments()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForTemplateArguments (const ArrayRef< TemplateArgument > TemplateArguments, ASTContext & Context, const std::optional< ArrayRef< TemplateArgumentLoc >> TemplateArgumentLocs) static
Definition at line 987 of file DeclarationFragments.cpp.
getFragmentsForTemplateParameters()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForTemplateParameters (ArrayRef< NamedDecl * > ParameterArray) static
Definition at line 947 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSpace(), clang::extractapi::DeclarationFragments::GenericParameter, clang::extractapi::DeclarationFragments::Keyword, clang::TemplateParam, clang::extractapi::DeclarationFragments::Text, and clang::extractapi::DeclarationFragments::TypeIdentifier.
getFragmentsForTypedef()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForTypedef (const TypedefNameDecl * Decl) static
Build DeclarationFragments for a typedef TypedefNameDecl.
Definition at line 1413 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), clang::extractapi::DeclarationFragments::Identifier, and clang::extractapi::DeclarationFragments::Keyword.
getFragmentsForVar()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForVar (const VarDecl * Var) static
Build DeclarationFragments for a variable declaration VarDecl.
Definition at line 495 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), clang::NamedDecl::getName(), clang::VarDecl::getStorageClass(), clang::VarDecl::getStorageClassSpecifierString(), clang::ValueDecl::getType(), clang::TypeSourceInfo::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::ASTContext::getUnqualifiedObjCPointerType(), clang::extractapi::DeclarationFragments::Identifier, clang::VarDecl::isConstexpr(), clang::extractapi::DeclarationFragments::Keyword, clang::SC_None, and clang::T.
getFragmentsForVarTemplate()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForVarTemplate (const VarDecl * Var) static
Definition at line 537 of file DeclarationFragments.cpp.
References clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::extractapi::DeclarationFragments::begin(), clang::Decl::getASTContext(), clang::NamedDecl::getName(), clang::ValueDecl::getType(), clang::TypeSourceInfo::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::ASTContext::getUnqualifiedObjCPointerType(), clang::extractapi::DeclarationFragments::Identifier, clang::VarDecl::isConstexpr(), clang::VarDecl::isStaticDataMember(), clang::extractapi::DeclarationFragments::Keyword, and clang::T.
Referenced by getFragmentsForVarTemplatePartialSpecialization(), and getFragmentsForVarTemplateSpecialization().
getFragmentsForVarTemplatePartialSpecialization()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForVarTemplatePartialSpecialization (const VarTemplatePartialSpecializationDecl * Decl) static
Definition at line 1116 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), getFragmentsForVarTemplate(), clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::pop_back(), and clang::extractapi::DeclarationFragments::Text.
getFragmentsForVarTemplateSpecialization()
DeclarationFragments DeclarationFragmentsBuilder::getFragmentsForVarTemplateSpecialization (const VarTemplateSpecializationDecl * Decl) static
Definition at line 1097 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::appendSemicolon(), clang::extractapi::DeclarationFragments::appendSpace(), clang::Decl::getASTContext(), getFragmentsForVarTemplate(), clang::extractapi::DeclarationFragments::Keyword, clang::extractapi::DeclarationFragments::pop_back(), and clang::extractapi::DeclarationFragments::Text.
getFunctionSignature()
template<typename FunctionT > template FunctionSignature DeclarationFragmentsBuilder::getFunctionSignature (const FunctionT * Function) static
Build FunctionSignature for a function-like declaration FunctionT like FunctionDecl, ObjCMethodDecl, or CXXMethodDecl.
The logic and implementation of building a signature for a FunctionDecl, CXXMethodDecl, and ObjCMethodDecl are exactly the same, but they do not share a common base. This template helps reuse the code.
Definition at line 462 of file DeclarationFragments.h.
References clang::extractapi::FunctionSignature::addParameter(), clang::frontend::After, clang::extractapi::DeclarationFragments::append(), clang::extractapi::DeclarationFragments::begin(), clang::Function, and clang::extractapi::FunctionSignature::setReturnType().
getSubHeading() [1/2]
DeclarationFragments DeclarationFragmentsBuilder::getSubHeading (const NamedDecl * Decl) static
Build sub-heading fragments for a NamedDecl.
Definition at line 1437 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::getAsString(), clang::Decl::getDeclContext(), and clang::extractapi::DeclarationFragments::Identifier.
getSubHeading() [2/2]
DeclarationFragments DeclarationFragmentsBuilder::getSubHeading (const ObjCMethodDecl * Method) static
Build sub-heading fragments for an Objective-C method.
Definition at line 1459 of file DeclarationFragments.cpp.
References clang::extractapi::DeclarationFragments::append(), clang::NamedDecl::getNameAsString(), clang::extractapi::DeclarationFragments::Identifier, clang::ObjCMethodDecl::isClassMethod(), clang::ObjCMethodDecl::isInstanceMethod(), and clang::extractapi::DeclarationFragments::Text.
getSubHeadingForMacro()
DeclarationFragments DeclarationFragmentsBuilder::getSubHeadingForMacro (StringRef Name) static
Build a sub-heading for macro Name.
Definition at line 1472 of file DeclarationFragments.cpp.
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/DeclarationFragments.h
lib/ExtractAPI/DeclarationFragments.cpp