clang: clang::ento::ArgEffect Class Reference
clang::ento::ArgEffect Class Reference
An ArgEffect summarizes the retain count behavior on an argument or receiver to a function or method.
#include "clang/Analysis/RetainSummaryManager.h"
Public Member Functions
ArgEffect (ArgEffectKind K=DoNothing, ObjKind O=ObjKind::AnyObj)
ArgEffectKind getKind () const
ObjKind getObjKind () const
ArgEffect withKind (ArgEffectKind NewK)
bool operator== (const ArgEffect &Other) const
Detailed Description
An ArgEffect summarizes the retain count behavior on an argument or receiver to a function or method.
Definition at line 119 of file RetainSummaryManager.h.
Constructor & Destructor Documentation
ArgEffect()
clang::ento::ArgEffect::ArgEffect (ArgEffectKind K = DoNothing, ObjKind O = ObjKind::AnyObj) inline explicit
Definition at line 123 of file RetainSummaryManager.h.
Referenced by withKind().
Member Function Documentation
getKind()
ArgEffectKind clang::ento::ArgEffect::getKind () const inline
Definition at line 126 of file RetainSummaryManager.h.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), clang::ento::retaincountchecker::RetainCountChecker::checkSummary(), getStopTrackingHardEquivalent(), clang::ento::RetainSummary::isNoop(), clang::ento::retaincountchecker::RetainCountChecker::processSummaryOfInlined(), updateOutParameters(), and clang::ento::retaincountchecker::RetainCountChecker::updateSymbol().
getObjKind()
ObjKind clang::ento::ArgEffect::getObjKind () const inline
Definition at line 127 of file RetainSummaryManager.h.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), updateOutParameters(), and clang::ento::retaincountchecker::RetainCountChecker::updateSymbol().
operator==()
bool clang::ento::ArgEffect::operator== (const ArgEffect & Other) const inline
Definition at line 133 of file RetainSummaryManager.h.
References clang::Other.
withKind()
ArgEffect clang::ento::ArgEffect::withKind (ArgEffectKind NewK) inline
Definition at line 129 of file RetainSummaryManager.h.
References ArgEffect().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), getStopTrackingHardEquivalent(), and clang::ento::retaincountchecker::RetainCountChecker::updateSymbol().
The documentation for this class was generated from the following file:
include/clang/Analysis/RetainSummaryManager.h