clang: clang::CodeCompletionHandler Class Reference
clang::CodeCompletionHandler Class Reference
Callback handler that receives notifications when performing code completion within the preprocessor.
#include "clang/Lex/CodeCompletionHandler.h"
Public Member Functions
virtual ~CodeCompletionHandler ()
virtual void CodeCompleteDirective (bool InConditional)
Callback invoked when performing code completion for a preprocessor directive.
virtual void CodeCompleteInConditionalExclusion ()
Callback invoked when performing code completion within a block of code that was excluded due to preprocessor conditionals.
virtual void CodeCompleteMacroName (bool IsDefinition)
Callback invoked when performing code completion in a context where the name of a macro is expected.
virtual void CodeCompletePreprocessorExpression ()
Callback invoked when performing code completion in a preprocessor expression, such as the condition of an #if or #elif directive.
virtual void CodeCompleteMacroArgument (IdentifierInfo *Macro, MacroInfo *MacroInfo, unsigned ArgumentIndex)
Callback invoked when performing code completion inside a function-like macro argument.
virtual void CodeCompleteIncludedFile (llvm::StringRef Dir, bool IsAngled)
Callback invoked when performing code completion inside the filename part of an include directive.
virtual void CodeCompleteNaturalLanguage ()
Callback invoked when performing code completion in a part of the file where we expect natural language, e.g., a comment, string, or #error directive.
Detailed Description
Callback handler that receives notifications when performing code completion within the preprocessor.
Definition at line 25 of file CodeCompletionHandler.h.
Constructor & Destructor Documentation
~CodeCompletionHandler()
CodeCompletionHandler::~CodeCompletionHandler () virtual default
Member Function Documentation
CodeCompleteDirective()
virtual void clang::CodeCompletionHandler::CodeCompleteDirective (bool InConditional) inline virtual
Callback invoked when performing code completion for a preprocessor directive.
This callback will be invoked when the preprocessor processes a '#' at the start of a line, followed by the code-completion token.
Parameters
InConditional Whether we're inside a preprocessor conditional already.
Definition at line 37 of file CodeCompletionHandler.h.
Referenced by clang::Preprocessor::HandleDirective().
CodeCompleteIncludedFile()
virtual void clang::CodeCompletionHandler::CodeCompleteIncludedFile (llvm::StringRef Dir, bool IsAngled) inline virtual
Callback invoked when performing code completion inside the filename part of an include directive.
(Also #import, #include_next, etc). Dir is the directory relative to the include path.
Definition at line 67 of file CodeCompletionHandler.h.
Referenced by clang::Preprocessor::CodeCompleteIncludedFile().
CodeCompleteInConditionalExclusion()
virtual void clang::CodeCompletionHandler::CodeCompleteInConditionalExclusion () inline virtual
Callback invoked when performing code completion within a block of code that was excluded due to preprocessor conditionals.
Definition at line 41 of file CodeCompletionHandler.h.
CodeCompleteMacroArgument()
virtual void clang::CodeCompletionHandler::CodeCompleteMacroArgument (IdentifierInfo * Macro, MacroInfo * MacroInfo, unsigned ArgumentIndex) inline virtual
Callback invoked when performing code completion inside a function-like macro argument.
There will be another callback invocation after the macro arguments are parsed, so this callback should generally be used to note that the next callback is invoked inside a macro argument.
Definition at line 60 of file CodeCompletionHandler.h.
CodeCompleteMacroName()
virtual void clang::CodeCompletionHandler::CodeCompleteMacroName (bool IsDefinition) inline virtual
Callback invoked when performing code completion in a context where the name of a macro is expected.
Parameters
IsDefinition Whether this is the definition of a macro, e.g., in a #define.
Definition at line 48 of file CodeCompletionHandler.h.
Referenced by EvaluateDefined().
CodeCompleteNaturalLanguage()
virtual void clang::CodeCompletionHandler::CodeCompleteNaturalLanguage () inline virtual
Callback invoked when performing code completion in a part of the file where we expect natural language, e.g., a comment, string, or #error directive.
Definition at line 72 of file CodeCompletionHandler.h.
Referenced by clang::Preprocessor::CodeCompleteNaturalLanguage().
CodeCompletePreprocessorExpression()
virtual void clang::CodeCompletionHandler::CodeCompletePreprocessorExpression () inline virtual
Callback invoked when performing code completion in a preprocessor expression, such as the condition of an #if or #elif directive.
Definition at line 52 of file CodeCompletionHandler.h.
Referenced by EvaluateValue().
The documentation for this class was generated from the following files:
include/clang/Lex/CodeCompletionHandler.h
lib/Lex/Preprocessor.cpp