clang: clang::arcmt::trans::MigrationContext Class Reference
clang::arcmt::trans::MigrationContext Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/ARCMigrate/Transforms.h"
Classes
struct GCAttrOccurrence
Public Types
typedef std::vector< ASTTraverser * >::iterator traverser_iterator
Public Member Functions
MigrationContext (MigrationPass &pass)
~MigrationContext ()
traverser_iterator traversers_begin ()
traverser_iterator traversers_end ()
void addTraverser (ASTTraverser *traverser)
bool isGCOwnedNonObjC (QualType T)
bool removePropertyAttribute (StringRef fromAttr, SourceLocation atLoc)
bool rewritePropertyAttribute (StringRef fromAttr, StringRef toAttr, SourceLocation atLoc)
bool addPropertyAttribute (StringRef attr, SourceLocation atLoc)
void traverse (TranslationUnitDecl *TU)
void dumpGCAttrs ()
Public Attributes
MigrationPass & Pass
std::vector< GCAttrOccurrence > GCAttrs
llvm::DenseSet< SourceLocation > AttrSet
llvm::DenseSet< SourceLocation > RemovedAttrSet
llvm::DenseSet< SourceLocation > AtPropsWeak
Set of raw '@' locations for 'assign' properties group that contain GC __weak.
Detailed Description
Definition at line 80 of file Transforms.h.
Member Typedef Documentation
traverser_iterator
typedef std::vector<ASTTraverser *>::iterator clang::arcmt::trans::MigrationContext::traverser_iterator
Definition at line 106 of file Transforms.h.
Constructor & Destructor Documentation
MigrationContext()
clang::arcmt::trans::MigrationContext::MigrationContext (MigrationPass & pass) inline explicit
Definition at line 103 of file Transforms.h.
~MigrationContext()
MigrationContext::~MigrationContext ()
Definition at line 352 of file Transforms.cpp.
References traversers_begin(), and traversers_end().
Member Function Documentation
addPropertyAttribute()
bool MigrationContext::addPropertyAttribute (StringRef attr, SourceLocation atLoc)
Definition at line 460 of file Transforms.cpp.
References clang::ast_matchers::attr, clang::arcmt::MigrationPass::Ctx, clang::ASTContext::getLangOpts(), clang::Token::getLocation(), clang::Token::getRawIdentifier(), clang::ASTContext::getSourceManager(), clang::arcmt::TransformActions::insert(), clang::Token::is(), clang::SourceLocation::isMacroID(), clang::Token::isNot(), clang::Lexer::LexFromRawLexer(), Pass, SM, string(), and clang::arcmt::MigrationPass::TA.
Referenced by checkAllAtProps().
addTraverser()
void clang::arcmt::trans::MigrationContext::addTraverser (ASTTraverser * traverser) inline
Definition at line 110 of file Transforms.h.
Referenced by traverseAST().
dumpGCAttrs()
void MigrationContext::dumpGCAttrs ()
Definition at line 330 of file TransGCAttrs.cpp.
References clang::arcmt::MigrationPass::Ctx, GCAttrs, clang::ASTContext::getSourceManager(), Pass, and clang::arcmt::trans::MigrationContext::GCAttrOccurrence::Strong.
isGCOwnedNonObjC()
bool MigrationContext::isGCOwnedNonObjC (QualType T)
Definition at line 358 of file Transforms.cpp.
References clang::arcmt::MigrationPass::Ctx, clang::Type::getAs(), clang::ASTContext::getBaseElementType(), clang::Type::getPointeeType(), clang::Type::isArrayType(), clang::QualType::isNull(), and Pass.
removePropertyAttribute()
bool clang::arcmt::trans::MigrationContext::removePropertyAttribute (StringRef fromAttr, SourceLocation atLoc) inline
Definition at line 115 of file Transforms.h.
References rewritePropertyAttribute().
rewritePropertyAttribute()
bool MigrationContext::rewritePropertyAttribute (StringRef fromAttr, StringRef toAttr, SourceLocation atLoc)
Definition at line 378 of file Transforms.cpp.
References clang::arcmt::MigrationPass::Ctx, clang::ASTContext::getLangOpts(), clang::Token::getLocation(), clang::Token::getRawIdentifier(), clang::ASTContext::getSourceManager(), clang::Token::is(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isMacroID(), clang::Token::isNot(), clang::SourceLocation::isValid(), clang::Lexer::LexFromRawLexer(), Pass, clang::arcmt::TransformActions::remove(), clang::arcmt::TransformActions::replaceText(), SM, clang::Token::startToken(), and clang::arcmt::MigrationPass::TA.
Referenced by checkAllAtProps(), and removePropertyAttribute().
traverse()
void MigrationContext::traverse (TranslationUnitDecl * TU)
Definition at line 508 of file Transforms.cpp.
References traversers_begin(), and traversers_end().
Referenced by traverseAST().
traversers_begin()
traverser_iterator clang::arcmt::trans::MigrationContext::traversers_begin () inline
Definition at line 107 of file Transforms.h.
Referenced by traverse(), and ~MigrationContext().
traversers_end()
traverser_iterator clang::arcmt::trans::MigrationContext::traversers_end () inline
Definition at line 108 of file Transforms.h.
Referenced by traverse(), and ~MigrationContext().
Member Data Documentation
AtPropsWeak
llvm::DenseSet<SourceLocation> clang::arcmt::trans::MigrationContext::AtPropsWeak
Set of raw '@' locations for 'assign' properties group that contain GC __weak.
Definition at line 101 of file Transforms.h.
Referenced by checkAllAtProps().
AttrSet
llvm::DenseSet<SourceLocation> clang::arcmt::trans::MigrationContext::AttrSet
Definition at line 96 of file Transforms.h.
GCAttrs
std::vector<GCAttrOccurrence> clang::arcmt::trans::MigrationContext::GCAttrs
Definition at line 95 of file Transforms.h.
Referenced by checkWeakGCAttrs(), dumpGCAttrs(), and errorForGCAttrsOnNonObjC().
Pass
MigrationPass& clang::arcmt::trans::MigrationContext::Pass
Definition at line 84 of file Transforms.h.
Referenced by addPropertyAttribute(), checkAllAtProps(), checkWeakGCAttrs(), dumpGCAttrs(), errorForGCAttrsOnNonObjC(), isGCOwnedNonObjC(), rewritePropertyAttribute(), clang::arcmt::trans::BlockObjCVariableTraverser::traverseBody(), and clang::arcmt::trans::GCAttrsTraverser::traverseTU().
RemovedAttrSet
llvm::DenseSet<SourceLocation> clang::arcmt::trans::MigrationContext::RemovedAttrSet
Definition at line 97 of file Transforms.h.
Referenced by checkAllAtProps(), and checkWeakGCAttrs().
The documentation for this class was generated from the following files:
lib/ARCMigrate/Transforms.h
lib/ARCMigrate/Transforms.cpp
lib/ARCMigrate/TransGCAttrs.cpp