clang: clang::api_notes::ObjCMethodInfo Class Reference
clang::api_notes::ObjCMethodInfo Class Reference
Describes API notes data for an Objective-C method.
#include "clang/APINotes/Types.h"
Public Member Functions
ObjCMethodInfo ()
ObjCMethodInfo & operator|= (const ObjCContextInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS)
Public Member Functions inherited from clang::api_notes::FunctionInfo
FunctionInfo ()
void addTypeInfo (unsigned index, NullabilityKind kind)
void addReturnTypeInfo (NullabilityKind kind)
Adds the return type info.
void addParamTypeInfo (unsigned index, NullabilityKind kind)
Adds the parameter type info.
NullabilityKind getParamTypeInfo (unsigned index) const
NullabilityKind getReturnTypeInfo () const
std::optional< RetainCountConventionKind > getRetainCountConvention () const
void setRetainCountConvention (std::optional< RetainCountConventionKind > Value)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::CommonEntityInfo
CommonEntityInfo ()
std::optional< bool > isSwiftPrivate () const
void setSwiftPrivate (std::optional< bool > Private)
CommonEntityInfo & operator|= (const CommonEntityInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Attributes
unsigned DesignatedInit: 1
Whether this is a designated initializer of its class.
unsigned RequiredInit: 1
Whether this is a required initializer.
Public Attributes inherited from clang::api_notes::FunctionInfo
unsigned NullabilityAudited: 1
Whether the signature has been audited with respect to nullability.
unsigned NumAdjustedNullable: 8
Number of types whose nullability is encoded with the NullabilityPayload.
unsigned RawRetainCountConvention: 3
A biased RetainCountConventionKind, where 0 means "unspecified".
uint64_t NullabilityPayload = 0
Stores the nullability of the return type and the parameters.
std::string ResultType
The result type of this function, as a C type.
std::vector< ParamInfo > Params
The function parameters.
Public Attributes inherited from clang::api_notes::CommonEntityInfo
std::string UnavailableMsg
Message to use when this entity is unavailable.
unsigned Unavailable: 1
Whether this entity is marked unavailable.
unsigned UnavailableInSwift: 1
Whether this entity is marked unavailable in Swift.
std::string SwiftName
Swift name of this entity.
Friends
bool operator== (const ObjCMethodInfo &, const ObjCMethodInfo &)
Additional Inherited Members
Static Public Member Functions inherited from clang::api_notes::FunctionInfo
static unsigned getMaxNullabilityIndex ()
Detailed Description
Describes API notes data for an Objective-C method.
Definition at line 615 of file Types.h.
Constructor & Destructor Documentation
ObjCMethodInfo()
clang::api_notes::ObjCMethodInfo::ObjCMethodInfo () inline
Definition at line 625 of file Types.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::api_notes::ObjCMethodInfo::dump (llvm::raw_ostream & OS)
Definition at line 84 of file APINotesTypes.cpp.
References DesignatedInit, clang::api_notes::FunctionInfo::dump(), and RequiredInit.
operator|=()
ObjCMethodInfo& clang::api_notes::ObjCMethodInfo::operator|= (const ObjCContextInfo & RHS) inline
Definition at line 629 of file Types.h.
References clang::api_notes::FunctionInfo::addTypeInfo(), clang::api_notes::ObjCContextInfo::getDefaultNullability(), clang::api_notes::FunctionInfo::NullabilityAudited, and clang::Nullable.
Friends And Related Function Documentation
operator==
bool operator== (const ObjCMethodInfo & LHS, const ObjCMethodInfo & RHS) friend
Definition at line 643 of file Types.h.
Member Data Documentation
DesignatedInit
unsigned clang::api_notes::ObjCMethodInfo::DesignatedInit
Whether this is a designated initializer of its class.
Definition at line 619 of file Types.h.
Referenced by clang::api_notes::APINotesWriter::addObjCMethod(), and dump().
RequiredInit
unsigned clang::api_notes::ObjCMethodInfo::RequiredInit
Whether this is a required initializer.
Definition at line 623 of file Types.h.
Referenced by dump().
The documentation for this class was generated from the following files:
include/clang/APINotes/Types.h
lib/APINotes/APINotesTypes.cpp