clang: clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo Class Reference
clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo Class Reference
Base class of the entries info.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGOpenMPRuntime.h"
Public Types
enum OffloadingEntryInfoKinds : unsigned { OffloadingEntryInfoTargetRegion = 0, OffloadingEntryInfoDeviceGlobalVar = 1, OffloadingEntryInfoInvalid = ~0u }
Kind of a given entry.
Public Member Functions
bool isValid () const
unsigned getOrder () const
OffloadingEntryInfoKinds getKind () const
uint32_t getFlags () const
void setFlags (uint32_t NewFlags)
llvm::Constant * getAddress () const
void setAddress (llvm::Constant *V)
Static Public Member Functions
static bool classof (const OffloadEntryInfo *Info)
Protected Member Functions
OffloadEntryInfo ()=delete
OffloadEntryInfo (OffloadingEntryInfoKinds Kind)
OffloadEntryInfo (OffloadingEntryInfoKinds Kind, unsigned Order, uint32_t Flags)
~OffloadEntryInfo ()=default
Detailed Description
Base class of the entries info.
Definition at line 540 of file CGOpenMPRuntime.h.
Member Enumeration Documentation
OffloadingEntryInfoKinds
enum clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::OffloadingEntryInfoKinds : unsigned
Kind of a given entry.
Enumerator
OffloadingEntryInfoTargetRegion
Entry is a target region.
OffloadingEntryInfoDeviceGlobalVar
Entry is a declare target variable.
OffloadingEntryInfoInvalid
Invalid entry info.
Definition at line 543 of file CGOpenMPRuntime.h.
Constructor & Destructor Documentation
OffloadEntryInfo() [1/3]
clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::OffloadEntryInfo () protected delete
OffloadEntryInfo() [2/3]
clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::OffloadEntryInfo (OffloadingEntryInfoKinds Kind) inline explicit protected
Definition at line 554 of file CGOpenMPRuntime.h.
OffloadEntryInfo() [3/3]
clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::OffloadEntryInfo (OffloadingEntryInfoKinds Kind, unsigned Order, uint32_t Flags) inline explicit protected
Definition at line 555 of file CGOpenMPRuntime.h.
~OffloadEntryInfo()
clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::~OffloadEntryInfo () protected default
Member Function Documentation
classof()
static bool clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::classof (const OffloadEntryInfo * Info) inline static
Definition at line 573 of file CGOpenMPRuntime.h.
getAddress()
llvm::Constant* clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::getAddress () const inline
Definition at line 566 of file CGOpenMPRuntime.h.
getFlags()
uint32_t clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::getFlags () const inline
Definition at line 564 of file CGOpenMPRuntime.h.
getKind()
OffloadingEntryInfoKinds clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::getKind () const inline
Definition at line 563 of file CGOpenMPRuntime.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfoTargetRegion::classof(), and clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfoDeviceGlobalVar::classof().
getOrder()
unsigned clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::getOrder () const inline
Definition at line 562 of file CGOpenMPRuntime.h.
isValid()
bool clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::isValid () const inline
Definition at line 561 of file CGOpenMPRuntime.h.
setAddress()
void clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::setAddress (llvm::Constant * V) inline
Definition at line 569 of file CGOpenMPRuntime.h.
References V.
Referenced by clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfoDeviceGlobalVar::OffloadEntryInfoDeviceGlobalVar(), and clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfoTargetRegion::OffloadEntryInfoTargetRegion().
setFlags()
void clang::CodeGen::CGOpenMPRuntime::OffloadEntriesInfoManagerTy::OffloadEntryInfo::setFlags (uint32_t NewFlags) inline
Definition at line 565 of file CGOpenMPRuntime.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CGOpenMPRuntime.h