clang: clang::driver::tools::solaris::Linker Class Reference
clang::driver::tools::solaris::Linker Class Reference final
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/Solaris.h"
Public Member Functions
Linker (const ToolChain &TC)
bool hasIntegratedCPP () const override
bool isLinkJob () const override
std::string getLinkerPath (const llvm::opt::ArgList &Args) const
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Definition at line 36 of file Solaris.h.
Constructor & Destructor Documentation
Linker()
clang::driver::tools::solaris::Linker::Linker (const ToolChain & TC) inline
Definition at line 38 of file Solaris.h.
Member Function Documentation
ConstructJob()
void solaris::Linker::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 82 of file Solaris.cpp.
References clang::driver::tools::addAsNeededOption(), clang::driver::ToolChain::AddCXXStdlibLibArgs(), clang::driver::ToolChain::addFastMathRuntimeIfAvailable(), clang::driver::ToolChain::AddFilePathLibArgs(), clang::driver::tools::addFortranRuntimeLibraryPath(), clang::driver::tools::addFortranRuntimeLibs(), clang::driver::tools::AddLinkerInputs(), clang::driver::tools::addOpenMPRuntime(), clang::driver::ToolChain::addProfileRTLibs(), clang::driver::tools::addSanitizerRuntimes(), clang::C, clang::driver::Driver::CCCIsCXX(), clang::driver::ToolChain::getArch(), clang::driver::ToolChain::getDriver(), clang::driver::InputInfo::getFilename(), clang::driver::ToolChain::GetFilePath(), clang::LangStandard::getLangStandardForName(), clang::LangStandard::getLanguage(), getPIE(), clang::driver::ToolChain::getSanitizerArgs(), clang::driver::ToolChain::getTriple(), clang::LangStandard::isC99(), clang::driver::InputInfo::isFilename(), clang::driver::Driver::IsFlangMode(), clang::LangStandard::isGNUMode(), clang::driver::tools::solaris::isLinkerGnuLd(), clang::driver::InputInfo::isNothing(), clang::driver::tools::linkSanitizerRuntimeDeps(), clang::driver::SanitizerArgs::needsAsanRt(), clang::driver::SanitizerArgs::needsSharedRt(), clang::driver::SanitizerArgs::needsStatsRt(), clang::driver::SanitizerArgs::needsUbsanRt(), clang::driver::ResponseFileSupport::None(), clang::driver::SanitizerArgs::requiresMinimalRuntime(), clang::driver::ToolChain::ShouldLinkCXXStdlib(), and Std.
getLinkerPath()
std::string solaris::Linker::getLinkerPath (const llvm::opt::ArgList & Args) const
Definition at line 57 of file Solaris.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDefaultLinker(), and clang::driver::ToolChain::getDriver().
hasIntegratedCPP()
bool clang::driver::tools::solaris::Linker::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 40 of file Solaris.h.
isLinkJob()
bool clang::driver::tools::solaris::Linker::isLinkJob () const inline override virtual
Reimplemented from clang::driver::Tool.
Definition at line 41 of file Solaris.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Solaris.h
lib/Driver/ToolChains/Solaris.cpp