clang: clang::NeonTypeFlags Class Reference
clang::NeonTypeFlags Class Reference
Flags to identify the types for overloaded Neon builtins.
#include "clang/Basic/TargetBuiltins.h"
Public Types
enum EltType {
Int8, Int16, Int32, Int64,
Poly8, Poly16, Poly64, Poly128,
Float16, Float32, Float64, BFloat16
}
Public Member Functions
NeonTypeFlags (unsigned F)
NeonTypeFlags (EltType ET, bool IsUnsigned, bool IsQuad)
EltType getEltType () const
bool isPoly () const
bool isUnsigned () const
bool isQuad () const
Detailed Description
Flags to identify the types for overloaded Neon builtins.
These must be kept in sync with the flags in utils/TableGen/NeonEmitter.h.
Definition at line 156 of file TargetBuiltins.h.
Member Enumeration Documentation
EltType
enum clang::NeonTypeFlags::EltType
Enumerator
Int8
Int16
Int32
Int64
Poly8
Poly16
Poly64
Poly128
Float16
Float32
Float64
BFloat16
Definition at line 165 of file TargetBuiltins.h.
Constructor & Destructor Documentation
NeonTypeFlags() [1/2]
clang::NeonTypeFlags::NeonTypeFlags (unsigned F) inline
Definition at line 180 of file TargetBuiltins.h.
NeonTypeFlags() [2/2]
clang::NeonTypeFlags::NeonTypeFlags (EltType ET, bool IsUnsigned, bool IsQuad) inline
Definition at line 181 of file TargetBuiltins.h.
Member Function Documentation
getEltType()
EltType clang::NeonTypeFlags::getEltType () const inline
Definition at line 188 of file TargetBuiltins.h.
Referenced by GetFloatNeonType(), getNeonEltType(), GetNeonType(), and isPoly().
isPoly()
bool clang::NeonTypeFlags::isPoly () const inline
Definition at line 189 of file TargetBuiltins.h.
References getEltType(), Poly16, Poly64, and Poly8.
isQuad()
bool clang::NeonTypeFlags::isQuad () const inline
Definition at line 194 of file TargetBuiltins.h.
Referenced by GetFloatNeonType(), and GetNeonType().
isUnsigned()
bool clang::NeonTypeFlags::isUnsigned () const inline
Definition at line 193 of file TargetBuiltins.h.
Referenced by getNeonEltType().
The documentation for this class was generated from the following file:
include/clang/Basic/TargetBuiltins.h