clang: clang::FileEntryRef Class Reference
clang::FileEntryRef Class Reference
A reference to a FileEntry that includes the name of the file as it was accessed by the FileManager's client.
#include "clang/Basic/FileEntry.h"
Classes
struct MapValue
Type stored in the StringMap.
Public Types
using MapEntry = llvm::StringMapEntry< llvm::ErrorOr< MapValue > >
Type used in the StringMap.
Public Member Functions
StringRef getName () const
The name of this FileEntry.
StringRef getNameAsRequested () const
The name of this FileEntry, as originally requested without applying any remappings for VFS 'use-external-name'.
const FileEntry & getFileEntry () const
DirectoryEntryRef getDir () const
off_t getSize () const
unsigned getUID () const
const llvm::sys::fs::UniqueID & getUniqueID () const
time_t getModificationTime () const
bool isNamedPipe () const
void closeFile () const
bool isSameRef (const FileEntryRef &RHS) const
Check if RHS referenced the file in exactly the same way.
operator const FileEntry * () const
Allow FileEntryRef to degrade into 'const FileEntry*' to facilitate incremental adoption.
FileEntryRef ()=delete
FileEntryRef (const MapEntry &ME)
const clang::FileEntryRef::MapEntry & getMapEntry () const
Expose the underlying MapEntry to simplify packing in a PointerIntPair or PointerUnion and allow construction in Optional.
const MapEntry & getBaseMapEntry () const
Retrieve the base MapEntry after redirects.
Friends
class FileMgr::MapEntryOptionalStorage< FileEntryRef >
struct llvm::DenseMapInfo< FileEntryRef >
bool operator== (const FileEntryRef &LHS, const FileEntryRef &RHS)
Check if the underlying FileEntry is the same, intentially ignoring whether the file was referenced with the same spelling of the filename.
bool operator== (const FileEntry *LHS, const FileEntryRef &RHS)
bool operator== (const FileEntryRef &LHS, const FileEntry *RHS)
bool operator!= (const FileEntryRef &LHS, const FileEntryRef &RHS)
bool operator!= (const FileEntry *LHS, const FileEntryRef &RHS)
bool operator!= (const FileEntryRef &LHS, const FileEntry *RHS)
llvm::hash_code hash_value (FileEntryRef Ref)
Hash code is based on the FileEntry, not the specific named reference, just like operator==.
Detailed Description
A reference to a FileEntry that includes the name of the file as it was accessed by the FileManager's client.
Definition at line 57 of file FileEntry.h.
Member Typedef Documentation
MapEntry
using clang::FileEntryRef::MapEntry = llvm::StringMapEntry<llvm::ErrorOr<MapValue> >
Type used in the StringMap.
Definition at line 112 of file FileEntry.h.
Constructor & Destructor Documentation
FileEntryRef() [1/2]
clang::FileEntryRef::FileEntryRef () delete
FileEntryRef() [2/2]
clang::FileEntryRef::FileEntryRef (const MapEntry & ME) inline explicit
Definition at line 154 of file FileEntry.h.
Member Function Documentation
closeFile()
void clang::FileEntryRef::closeFile () const inline
Definition at line 354 of file FileEntry.h.
References clang::FileEntry::closeFile(), and getFileEntry().
getBaseMapEntry()
const MapEntry& clang::FileEntryRef::getBaseMapEntry () const inline
Retrieve the base MapEntry after redirects.
Definition at line 164 of file FileEntry.h.
getDir()
DirectoryEntryRef clang::FileEntryRef::getDir () const inline
Definition at line 73 of file FileEntry.h.
Referenced by clang::ModuleMap::isHeaderUnavailableInModule(), clang::Preprocessor::LookupFile(), and clang::ModuleMap::setUmbrellaHeaderAsWritten().
getFileEntry()
const FileEntry& clang::FileEntryRef::getFileEntry () const inline
Definition at line 70 of file FileEntry.h.
Referenced by closeFile(), clang::FileManager::getBufferForFile(), getFileName(), getModificationTime(), getSize(), clang::FileManager::getSTDIN(), getUID(), getUniqueID(), clang::FileManager::getVirtualFile(), isNamedPipe(), clang::Preprocessor::LookupFile(), clang::operator==(), clang::SourceManager::translateFile(), and clang::VerifyDiagnosticConsumer::UpdateParsedFileStatus().
getMapEntry()
const clang::FileEntryRef::MapEntry& clang::FileEntryRef::getMapEntry () const inline
Expose the underlying MapEntry to simplify packing in a PointerIntPair or PointerUnion and allow construction in Optional.
Definition at line 161 of file FileEntry.h.
getModificationTime()
time_t clang::FileEntryRef::getModificationTime () const inline
Definition at line 348 of file FileEntry.h.
References getFileEntry(), and clang::FileEntry::getModificationTime().
Referenced by clang::arcmt::FileRemapper::flushToFile(), clang::serialization::reader::HeaderFileInfoTrait::GetInternalKey(), and clang::Preprocessor::HandlePragmaDependency().
getName()
StringRef clang::FileEntryRef::getName () const inline
The name of this FileEntry.
If a VFS uses 'use-external-name', this is the redirected name. See getRequestedName().
Definition at line 61 of file FileEntry.h.
Referenced by clang::ModuleMap::addHeader(), clang::arcmt::MigrationProcess::applyTransform(), clang::tooling::AtomicChange::AtomicChange(), clang::FrontendAction::BeginSourceFile(), checkMSVCHeaderSearch(), compareCrossTUSourceLocs(), compileModule(), clang::SourceManager::createFileID(), diagnoseFrameworkInclude(), clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile(), clang::arcmt::FileRemapper::flushToFile(), clang::FileManager::getBufferForFile(), clang::SrcMgr::ContentCache::getBufferOrNone(), getFileName(), clang::serialization::reader::HeaderFileInfoTrait::GetInternalKey(), clang::FileManager::GetUniqueIDMapping(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), clang::HeaderSearch::LookupSubframeworkHeader(), clang::Rewriter::overwriteChangedFiles(), clang::arcmt::FileRemapper::overwriteOriginal(), printLoc(), clang::index::SerializablePathCollection::tryStoreFilePath(), and clang::FixItRewriter::WriteFixedFiles().
getNameAsRequested()
StringRef clang::FileEntryRef::getNameAsRequested () const inline
The name of this FileEntry, as originally requested without applying any remappings for VFS 'use-external-name'.
FIXME: this should be the semantics of getName(). See comment in FileManager::getFileRef().
Definition at line 68 of file FileEntry.h.
Referenced by compileModule().
getSize()
off_t clang::FileEntryRef::getSize () const inline
Definition at line 340 of file FileEntry.h.
References getFileEntry(), and clang::FileEntry::getSize().
Referenced by clang::HeaderMap::Create(), clang::SrcMgr::ContentCache::getBufferOrNone(), clang::serialization::reader::HeaderFileInfoTrait::GetInternalKey(), clang::SrcMgr::ContentCache::getSize(), InitializeFileRemapping(), and clang::SourceManager::overrideFileContents().
getUID()
unsigned clang::FileEntryRef::getUID () const inline
Definition at line 342 of file FileEntry.h.
References getFileEntry(), and clang::FileEntry::getUID().
Referenced by clang::HeaderSearch::getExistingFileInfo(), clang::HeaderSearch::getExistingLocalFileInfo(), clang::HeaderSearch::getFileInfo(), and clang::FileManager::GetUniqueIDMapping().
getUniqueID()
const llvm::sys::fs::UniqueID & clang::FileEntryRef::getUniqueID () const inline
Definition at line 344 of file FileEntry.h.
References getFileEntry(), and clang::FileEntry::getUniqueID().
isNamedPipe()
bool clang::FileEntryRef::isNamedPipe () const inline
Definition at line 352 of file FileEntry.h.
References getFileEntry(), and clang::FileEntry::isNamedPipe().
Referenced by clang::SourceManager::createFileID(), and clang::SrcMgr::ContentCache::getBufferOrNone().
isSameRef()
bool clang::FileEntryRef::isSameRef (const FileEntryRef & RHS) const inline
Check if RHS referenced the file in exactly the same way.
Definition at line 132 of file FileEntry.h.
Referenced by llvm::DenseMapInfo< clang::FileEntryRef >::isEqual().
operator const FileEntry *()
clang::FileEntryRef::operator const FileEntry * () const inline
Allow FileEntryRef to degrade into 'const FileEntry*' to facilitate incremental adoption.
The goal is to avoid code churn due to dances like the following:
// Old code.
lvalue = rvalue;
// Temporary code from an incremental patch.
lvalue = &rvalue.getFileEntry();
// Final code.
lvalue = rvalue;
FIXME: Once FileEntryRef is "everywhere" and FileEntry::LastRef and FileEntry::getName have been deleted, delete this implicit conversion.
Definition at line 151 of file FileEntry.h.
Friends And Related Function Documentation
FileMgr::MapEntryOptionalStorage< FileEntryRef >
friend class FileMgr::MapEntryOptionalStorage< FileEntryRef > friend
Definition at line 164 of file FileEntry.h.
hash_value
llvm::hash_code hash_value (FileEntryRef Ref) friend
Hash code is based on the FileEntry, not the specific named reference, just like operator==.
Definition at line 105 of file FileEntry.h.
llvm::DenseMapInfo< FileEntryRef >
friend struct llvm::DenseMapInfo< FileEntryRef > friend
Definition at line 177 of file FileEntry.h.
operator!= [1/3]
bool operator!= (const FileEntry * LHS, const FileEntryRef & RHS) friend
Definition at line 96 of file FileEntry.h.
operator!= [2/3]
bool operator!= (const FileEntryRef & LHS, const FileEntry * RHS) friend
Definition at line 99 of file FileEntry.h.
operator!= [3/3]
bool operator!= (const FileEntryRef & LHS, const FileEntryRef & RHS) friend
Definition at line 93 of file FileEntry.h.
operator== [1/3]
bool operator== (const FileEntry * LHS, const FileEntryRef & RHS) friend
Definition at line 87 of file FileEntry.h.
operator== [2/3]
bool operator== (const FileEntryRef & LHS, const FileEntry * RHS) friend
Definition at line 90 of file FileEntry.h.
operator== [3/3]
bool operator== (const FileEntryRef & LHS, const FileEntryRef & RHS) friend
Check if the underlying FileEntry is the same, intentially ignoring whether the file was referenced with the same spelling of the filename.
Definition at line 84 of file FileEntry.h.
The documentation for this class was generated from the following file:
include/clang/Basic/FileEntry.h