clang: clang::CFGStmt Class Reference
clang::CFGStmt Class Reference
#include "clang/Analysis/CFG.h"
Public Member Functions
CFGStmt (Stmt *S, Kind K=Statement)
const Stmt * getStmt () const
Public Member Functions inherited from clang::CFGElement
template<typename T >
T castAs () const
Convert to the specified CFGElement type, asserting that this CFGElement is of the desired type.
template<typename T >
Optional< T > getAs () const
Convert to the specified CFGElement type, returning None if this CFGElement is not of the desired type.
Kind getKind () const
void dumpToStream (llvm::raw_ostream &OS) const
void dump () const
Protected Member Functions
CFGStmt ()=default
Protected Member Functions inherited from clang::CFGElement
CFGElement (Kind kind, const void *Ptr1, const void *Ptr2=nullptr)
CFGElement ()=default
Friends
class CFGElement
Additional Inherited Members
Public Types inherited from clang::CFGElement
enum Kind {
Initializer, ScopeBegin, ScopeEnd, NewAllocator,
LifetimeEnds, LoopExit, Statement, Constructor,
CXXRecordTypedCall, STMT_BEGIN = Statement, STMT_END = CXXRecordTypedCall, AutomaticObjectDtor,
DeleteDtor, BaseDtor, MemberDtor, TemporaryDtor,
DTOR_BEGIN = AutomaticObjectDtor, DTOR_END = TemporaryDtor
}
Protected Attributes inherited from clang::CFGElement
llvm::PointerIntPair< void *, 2 > Data1
llvm::PointerIntPair< void *, 2 > Data2
Detailed Description
Definition at line 132 of file CFG.h.
Constructor & Destructor Documentation
CFGStmt() [1/2]
clang::CFGStmt::CFGStmt (Stmt * S, Kind K = Statement) inline explicit
Definition at line 134 of file CFG.h.
CFGStmt() [2/2]
clang::CFGStmt::CFGStmt () protected default
Member Function Documentation
getStmt()
const Stmt* clang::CFGStmt::getStmt () const inline
Definition at line 138 of file CFG.h.
References clang::CFGElement::Data1.
Referenced by clang::ento::CoreEngine::enqueueStmtNode(), getLocationForCaller(), hasRecursiveCallInPath(), clang::ento::ExprEngine::processCFGElement(), clang::consumed::ConsumedAnalyzer::run(), clang::ento::ExprEngine::VisitLogicalExpr(), and clang::threadSafety::CFGWalker::walk().
Friends And Related Function Documentation
CFGElement
friend class CFGElement friend
Definition at line 143 of file CFG.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/CFG.h