clang: clang::threadSafety::SExprBuilder Class Reference
clang::threadSafety::SExprBuilder Class Reference
#include "clang/Analysis/Analyses/ThreadSafetyCommon.h"
Classes
struct CallingContext
Encapsulates the lexical context of a function call.
Public Member Functions
SExprBuilder (til::MemRegionRef A)
CapabilityExpr translateAttrExpr (const Expr *AttrExp, const NamedDecl *D, const Expr *DeclExp, til::SExpr *Self=nullptr)
Translate a clang expression in an attribute to a til::SExpr.
CapabilityExpr translateAttrExpr (const Expr *AttrExp, CallingContext *Ctx)
Translate a clang expression in an attribute to a til::SExpr.
til::LiteralPtr * createVariable (const VarDecl *VD)
std::pair< til::LiteralPtr *, StringRef > createThisPlaceholder (const Expr *Exp)
til::SExpr * translate (const Stmt *S, CallingContext *Ctx)
til::SCFG * buildCFG (CFGWalker &Walker)
til::SExpr * lookupStmt (const Stmt *S)
til::BasicBlock * lookupBlock (const CFGBlock *B)
const til::SCFG * getCFG () const
til::SCFG * getCFG ()
Friends
class CFGWalker
Detailed Description
Definition at line 339 of file ThreadSafetyCommon.h.
Constructor & Destructor Documentation
SExprBuilder()
clang::threadSafety::SExprBuilder::SExprBuilder (til::MemRegionRef A) inline
Definition at line 373 of file ThreadSafetyCommon.h.
References clang::threadSafety::til::Variable::setKind(), and clang::threadSafety::til::Variable::VK_SFun.
Member Function Documentation
buildCFG()
til::SCFG * SExprBuilder::buildCFG (CFGWalker & Walker)
Definition at line 74 of file ThreadSafetyCommon.cpp.
References clang::threadSafety::CFGWalker::walk().
createThisPlaceholder()
std::pair< til::LiteralPtr *, StringRef > SExprBuilder::createThisPlaceholder (const Expr * Exp)
Definition at line 226 of file ThreadSafetyCommon.cpp.
References ClassifyDiagnostic(), and clang::Expr::getType().
createVariable()
til::LiteralPtr * SExprBuilder::createVariable (const VarDecl * VD)
Definition at line 221 of file ThreadSafetyCommon.cpp.
getCFG() [1/2]
til::SCFG* clang::threadSafety::SExprBuilder::getCFG () inline
Definition at line 407 of file ThreadSafetyCommon.h.
getCFG() [2/2]
const til::SCFG* clang::threadSafety::SExprBuilder::getCFG () const inline
Definition at line 406 of file ThreadSafetyCommon.h.
lookupBlock()
til::BasicBlock* clang::threadSafety::SExprBuilder::lookupBlock (const CFGBlock * B) inline
Definition at line 402 of file ThreadSafetyCommon.h.
References clang::CFGBlock::getBlockID().
lookupStmt()
til::SExpr * SExprBuilder::lookupStmt (const Stmt * S)
Definition at line 72 of file ThreadSafetyCommon.cpp.
translate()
til::SExpr * SExprBuilder::translate (const Stmt * S, CallingContext * Ctx)
Definition at line 234 of file ThreadSafetyCommon.cpp.
Referenced by translateAttrExpr().
translateAttrExpr() [1/2]
CapabilityExpr SExprBuilder::translateAttrExpr (const Expr * AttrExp, CallingContext * Ctx)
Translate a clang expression in an attribute to a til::SExpr.
Definition at line 174 of file ThreadSafetyCommon.cpp.
References clang::threadSafety::til::CAST_objToPtr, ClassifyDiagnostic(), clang::Expr::getType(), clang::interp::Neg(), and translate().
translateAttrExpr() [2/2]
CapabilityExpr SExprBuilder::translateAttrExpr (const Expr * AttrExp, const NamedDecl * D, const Expr * DeclExp, til::SExpr * Self = nullptr)
Translate a clang expression in an attribute to a til::SExpr.
Constructs the context from D, DeclExp, and SelfDecl.
Parameters
AttrExp The expression to translate.
D The declaration to which the attribute is attached.
DeclExp An expression involving the Decl to which the attribute is attached. E.g. the call to a function.
Self S-expression to substitute for a CXXThisExpr in a call, or argument to a cleanup function.
Definition at line 115 of file ThreadSafetyCommon.cpp.
References ClassifyDiagnostic(), clang::threadSafety::SExprBuilder::CallingContext::FunArgs, isCalleeArrow(), clang::threadSafety::SExprBuilder::CallingContext::NumArgs, clang::threadSafety::SExprBuilder::CallingContext::SelfArg, and clang::threadSafety::SExprBuilder::CallingContext::SelfArrow.
Friends And Related Function Documentation
CFGWalker
friend class CFGWalker friend
Definition at line 411 of file ThreadSafetyCommon.h.
The documentation for this class was generated from the following files:
include/clang/Analysis/Analyses/ThreadSafetyCommon.h
lib/Analysis/ThreadSafetyCommon.cpp