clang: clang::OMPFinalClause Class Reference
clang::OMPFinalClause Class Reference
This represents 'final' clause in the '#pragma omp ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
OMPFinalClause (Expr *Cond, Stmt *HelperCond, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build 'final' clause with condition Cond.
OMPFinalClause ()
Build an empty clause.
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Expr * getCondition () const
Returns condition.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents 'final' clause in the '#pragma omp ...' directive.
#pragma omp task final(a > 5)
In this example directive '#pragma omp task' has simple 'final' clause with condition 'a > 5'.
Definition at line 606 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPFinalClause() [1/2]
clang::OMPFinalClause::OMPFinalClause (Expr * Cond, Stmt * HelperCond, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build 'final' clause with condition Cond.
Parameters
Cond Condition of the clause.
HelperCond Helper condition for the construct.
CaptureRegion Innermost OpenMP region where expressions in this clause must be captured.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Definition at line 628 of file OpenMPClause.h.
References clang::Condition, and clang::OMPClauseWithPreInit::setPreInitStmt().
OMPFinalClause() [2/2]
clang::OMPFinalClause::OMPFinalClause () inline
Build an empty clause.
Definition at line 637 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPFinalClause::children () inline
Definition at line 650 of file OpenMPClause.h.
References clang::Condition.
children() [2/2]
const_child_range clang::OMPFinalClause::children () const inline
Definition at line 652 of file OpenMPClause.h.
References clang::Condition.
classof()
static bool clang::OMPFinalClause::classof (const OMPClause * T) inline static
Definition at line 662 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
getCondition()
Expr* clang::OMPFinalClause::getCondition () const inline
Returns condition.
Definition at line 648 of file OpenMPClause.h.
References clang::Condition.
getLParenLoc()
SourceLocation clang::OMPFinalClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 645 of file OpenMPClause.h.
setLParenLoc()
void clang::OMPFinalClause::setLParenLoc (SourceLocation Loc) inline
Sets the location of '('.
Definition at line 642 of file OpenMPClause.h.
used_children() [1/2]
OMPClause::child_range OMPFinalClause::used_children ()
Definition at line 305 of file OpenMPClause.cpp.
References clang::Condition, and getAddrOfExprAsWritten().
Referenced by used_children().
used_children() [2/2]
const_child_range clang::OMPFinalClause::used_children () const inline
Definition at line 657 of file OpenMPClause.h.
References used_children().
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 607 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp