clang: clang::CodeGen::CGSYCLRuntime Class Reference
clang::CodeGen::CGSYCLRuntime Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGSYCLRuntime.h"
Public Member Functions
CGSYCLRuntime (CodeGenModule &CGM)
bool actOnFunctionStart (const FunctionDecl &FD, llvm::Function &F)
void emitWorkGroupLocalVarDecl (CodeGenFunction &CGF, const VarDecl &D)
bool actOnAutoVarEmit (CodeGenFunction &CGF, const VarDecl &D, llvm::Value *Addr)
bool actOnGlobalVarEmit (CodeGenModule &CGM, const VarDecl &D, llvm::Value *Addr)
Protected Attributes
CodeGenModule & CGM
Detailed Description
Definition at line 39 of file CGSYCLRuntime.h.
Constructor & Destructor Documentation
CGSYCLRuntime()
clang::CodeGen::CGSYCLRuntime::CGSYCLRuntime (CodeGenModule & CGM) inline
Definition at line 44 of file CGSYCLRuntime.h.
Member Function Documentation
actOnAutoVarEmit()
bool CGSYCLRuntime::actOnAutoVarEmit (CodeGenFunction & CGF, const VarDecl & D, llvm::Value * Addr)
Definition at line 106 of file CGSYCLRuntime.cpp.
References clang::Decl::getAttr().
Referenced by clang::CodeGen::CodeGenFunction::EmitAutoVarDecl().
actOnFunctionStart()
bool CGSYCLRuntime::actOnFunctionStart (const FunctionDecl & FD, llvm::Function & F)
Definition at line 63 of file CGSYCLRuntime.cpp.
References clang::Decl::getAttr(), and clang::Decl::hasAttr().
Referenced by clang::CodeGen::CodeGenFunction::StartFunction().
actOnGlobalVarEmit()
bool CGSYCLRuntime::actOnGlobalVarEmit (CodeGenModule & CGM, const VarDecl & D, llvm::Value * Addr)
Definition at line 118 of file CGSYCLRuntime.cpp.
References clang::Decl::getAttr().
emitWorkGroupLocalVarDecl()
void CGSYCLRuntime::emitWorkGroupLocalVarDecl (CodeGenFunction & CGF, const VarDecl & D)
Definition at line 95 of file CGSYCLRuntime.cpp.
References clang::CodeGen::CodeGenFunction::EmitStaticVarDecl(), and clang::Decl::getAttr().
Referenced by clang::CodeGen::CodeGenFunction::EmitVarDecl().
Member Data Documentation
CGM
CodeGenModule& clang::CodeGen::CGSYCLRuntime::CGM protected
Definition at line 41 of file CGSYCLRuntime.h.
The documentation for this class was generated from the following files:
lib/CodeGen/CGSYCLRuntime.h
lib/CodeGen/CGSYCLRuntime.cpp