clang: clang::LazyIdentifierInfoPtr Class Reference
clang::LazyIdentifierInfoPtr Class Reference
#include "clang/Lex/ExternalPreprocessorSource.h"
Public Member Functions
LazyIdentifierInfoPtr ()=default
LazyIdentifierInfoPtr (const IdentifierInfo *Ptr)
LazyIdentifierInfoPtr (uint64_t ID)
LazyIdentifierInfoPtr & operator= (const IdentifierInfo *Ptr)
LazyIdentifierInfoPtr & operator= (uint64_t ID)
bool isValid () const
Whether this pointer is non-NULL.
bool isID () const
Whether this pointer is currently stored as ID.
IdentifierInfo * getPtr () const
uint64_t getID () const
Detailed Description
Definition at line 50 of file ExternalPreprocessorSource.h.
Constructor & Destructor Documentation
LazyIdentifierInfoPtr() [1/3]
clang::LazyIdentifierInfoPtr::LazyIdentifierInfoPtr () default
LazyIdentifierInfoPtr() [2/3]
clang::LazyIdentifierInfoPtr::LazyIdentifierInfoPtr (const IdentifierInfo * Ptr) inline explicit
Definition at line 58 of file ExternalPreprocessorSource.h.
LazyIdentifierInfoPtr() [3/3]
clang::LazyIdentifierInfoPtr::LazyIdentifierInfoPtr (uint64_t ID) inline explicit
Definition at line 61 of file ExternalPreprocessorSource.h.
References ID.
Member Function Documentation
getID()
uint64_t clang::LazyIdentifierInfoPtr::getID () const inline
Definition at line 95 of file ExternalPreprocessorSource.h.
References isID().
Referenced by clang::HeaderFileInfo::getControllingMacro().
getPtr()
IdentifierInfo* clang::LazyIdentifierInfoPtr::getPtr () const inline
Definition at line 90 of file ExternalPreprocessorSource.h.
References isID().
Referenced by clang::HeaderFileInfo::getControllingMacro().
isID()
bool clang::LazyIdentifierInfoPtr::isID () const inline
Whether this pointer is currently stored as ID.
Definition at line 88 of file ExternalPreprocessorSource.h.
Referenced by clang::HeaderFileInfo::getControllingMacro(), getID(), and getPtr().
isValid()
bool clang::LazyIdentifierInfoPtr::isValid () const inline
Whether this pointer is non-NULL.
This operation does not require the AST node to be deserialized.
Definition at line 85 of file ExternalPreprocessorSource.h.
Referenced by mergeHeaderFileInfo().
operator=() [1/2]
LazyIdentifierInfoPtr& clang::LazyIdentifierInfoPtr::operator= (const IdentifierInfo * Ptr) inline
Definition at line 67 of file ExternalPreprocessorSource.h.
operator=() [2/2]
LazyIdentifierInfoPtr& clang::LazyIdentifierInfoPtr::operator= (uint64_t ID) inline
Definition at line 72 of file ExternalPreprocessorSource.h.
References ID.
The documentation for this class was generated from the following file:
include/clang/Lex/ExternalPreprocessorSource.h