clang: clang::interp::Context Class Reference
clang::interp::Context Class Reference final
Holds all information required to evaluate constexpr code in a module.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Context.h"
Public Member Functions
Context (ASTContext &Ctx)
Initialises the constexpr VM.
~Context ()
Cleans up the constexpr VM.
bool isPotentialConstantExpr (State &Parent, const FunctionDecl *FnDecl)
Checks if a function is a potential constant expression.
bool evaluateAsRValue (State &Parent, const Expr *E, APValue &Result)
Evaluates a toplevel expression as an rvalue.
bool evaluate (State &Parent, const Expr *E, APValue &Result)
Like evaluateAsRvalue(), but does no implicit lvalue-to-rvalue conversion.
bool evaluateAsInitializer (State &Parent, const VarDecl *VD, APValue &Result)
Evaluates a toplevel initializer.
ASTContext & getASTContext () const
Returns the AST context.
const LangOptions & getLangOpts () const
Returns the language options.
InterpStack & getStack ()
Returns the interpreter stack.
unsigned getCharBit () const
Returns CHAR_BIT.
const llvm::fltSemantics & getFloatSemantics (QualType T) const
Return the floating-point semantics for T.
uint32_t getBitWidth (QualType T) const
Return the size of T in bits.
std::optional< PrimType > classify (QualType T) const
Classifies a type.
std::optional< PrimType > classify (const Expr *E) const
Classifies an expression.
const CXXMethodDecl * getOverridingFunction (const CXXRecordDecl *DynamicDecl, const CXXRecordDecl *StaticDecl, const CXXMethodDecl *InitialFunction) const
const Function * getOrCreateFunction (const FunctionDecl *FD)
Program & getProgram () const
Returns the program. This is only needed for unittests.
Static Public Member Functions
static bool shouldBeGloballyIndexed (const ValueDecl *VD)
Returns whether we should create a global variable for the given ValueDecl.
Detailed Description
Holds all information required to evaluate constexpr code in a module.
Definition at line 40 of file Context.h.
Constructor & Destructor Documentation
Context()
Context::Context (ASTContext & Ctx)
Initialises the constexpr VM.
Definition at line 25 of file Context.cpp.
~Context()
Context::~Context ()
Cleans up the constexpr VM.
Definition at line 27 of file Context.cpp.
Member Function Documentation
classify() [1/2]
std::optional<PrimType> clang::interp::Context::classify (const Expr * E) const inline
Classifies an expression.
Definition at line 77 of file Context.h.
References classify(), clang::Expr::getType(), clang::Type::isFunctionType(), clang::Expr::isGLValue(), clang::interp::PT_FnPtr, and clang::interp::PT_Ptr.
classify() [2/2]
std::optional< PrimType > Context::classify (QualType T) const
Classifies a type.
Definition at line 119 of file Context.cpp.
References clang::Type::getAs(), clang::ASTContext::getIntWidth(), clang::Type::isAnyComplexType(), clang::Type::isBooleanType(), clang::Type::isFloatingType(), clang::Type::isFunctionPointerType(), clang::Type::isFunctionReferenceType(), clang::Type::isFunctionType(), clang::Type::isNullPtrType(), clang::Type::isPointerType(), clang::Type::isReferenceType(), clang::Type::isSignedIntegerOrEnumerationType(), clang::Type::isSpecificBuiltinType(), clang::Type::isUnsignedIntegerOrEnumerationType(), clang::Type::isVectorType(), clang::interp::PT_Bool, clang::interp::PT_Float, clang::interp::PT_FnPtr, clang::interp::PT_IntAP, clang::interp::PT_IntAPS, clang::interp::PT_Ptr, clang::interp::PT_Sint16, clang::interp::PT_Sint32, clang::interp::PT_Sint64, clang::interp::PT_Sint8, clang::interp::PT_Uint16, clang::interp::PT_Uint32, clang::interp::PT_Uint64, clang::interp::PT_Uint8, and clang::T.
Referenced by clang::interp::ByteCodeExprGen< Emitter >::classify(), classify(), clang::interp::ByteCodeEmitter::compileFunc(), clang::interp::Program::createDescriptor(), clang::interp::InterpFrame::describe(), clang::interp::Program::getOrCreateRecord(), and clang::interp::Pointer::toRValue().
evaluate()
bool Context::evaluate (State & Parent, const Expr * E, APValue & Result)
Like evaluateAsRvalue(), but does no implicit lvalue-to-rvalue conversion.
Definition at line 67 of file Context.cpp.
References clang::interp::InterpStack::clear(), clang::interp::InterpStack::empty(), and Parent.
evaluateAsInitializer()
bool Context::evaluateAsInitializer (State & Parent, const VarDecl * VD, APValue & Result)
Evaluates a toplevel initializer.
Definition at line 90 of file Context.cpp.
References clang::interp::CheckGlobalInitialized(), clang::interp::InterpStack::clear(), clang::interp::InterpStack::empty(), clang::ValueDecl::getType(), clang::Type::isArrayType(), clang::Type::isRecordType(), Parent, and shouldBeGloballyIndexed().
evaluateAsRValue()
bool Context::evaluateAsRValue (State & Parent, const Expr * E, APValue & Result)
Evaluates a toplevel expression as an rvalue.
Definition at line 42 of file Context.cpp.
References clang::interp::InterpStack::clear(), clang::interp::InterpStack::empty(), clang::Expr::isGLValue(), and Parent.
getASTContext()
ASTContext& clang::interp::Context::getASTContext () const inline
Returns the AST context.
Definition at line 61 of file Context.h.
Referenced by clang::interp::EvaluationResult::dump(), and clang::interp::Pointer::toRValue().
getBitWidth()
uint32_t clang::interp::Context::getBitWidth (QualType T) const inline
Return the size of T in bits.
Definition at line 71 of file Context.h.
References clang::ASTContext::getIntWidth(), and clang::T.
getCharBit()
unsigned Context::getCharBit () const
Returns CHAR_BIT.
Definition at line 182 of file Context.cpp.
References clang::TargetInfo::getCharWidth(), and clang::ASTContext::getTargetInfo().
getFloatSemantics()
const llvm::fltSemantics & Context::getFloatSemantics (QualType T) const
Return the floating-point semantics for T.
Simple wrapper around getFloatTypeSemantics() to make code a little shorter.
Definition at line 188 of file Context.cpp.
References clang::ASTContext::getFloatTypeSemantics(), and clang::T.
getLangOpts()
const LangOptions & Context::getLangOpts () const
Returns the language options.
Definition at line 117 of file Context.cpp.
References clang::ASTContext::getLangOpts().
getOrCreateFunction()
const Function * Context::getOrCreateFunction (const FunctionDecl * FD)
Definition at line 249 of file Context.cpp.
References clang::Func.
getOverridingFunction()
const CXXMethodDecl * Context::getOverridingFunction (const CXXRecordDecl * DynamicDecl, const CXXRecordDecl * StaticDecl, const CXXMethodDecl * InitialFunction) const
Definition at line 213 of file Context.cpp.
References clang::CXXRecordDecl::bases(), clang::CXXRecordDecl::bases_begin(), clang::Type::getAsCXXRecordDecl(), clang::CXXMethodDecl::getCorrespondingMethodDeclaredInClass(), clang::CXXRecordDecl::getNumBases(), and clang::CXXBaseSpecifier::getType().
getProgram()
Program& clang::interp::Context::getProgram () const inline
Returns the program. This is only needed for unittests.
Definition at line 105 of file Context.h.
getStack()
InterpStack& clang::interp::Context::getStack () inline
Returns the interpreter stack.
Definition at line 65 of file Context.h.
isPotentialConstantExpr()
bool Context::isPotentialConstantExpr (State & Parent, const FunctionDecl * FnDecl)
Checks if a function is a potential constant expression.
Definition at line 29 of file Context.cpp.
References clang::interp::InterpStack::empty(), clang::Func, and Parent.
shouldBeGloballyIndexed()
static bool clang::interp::Context::shouldBeGloballyIndexed (const ValueDecl * VD) inline static
Returns whether we should create a global variable for the given ValueDecl.
Definition at line 97 of file Context.h.
References V.
Referenced by clang::interp::Program::createGlobal(), clang::interp::DeclScope< Emitter >::DeclScope(), evaluateAsInitializer(), and clang::interp::ByteCodeExprGen< Emitter >::visitVarDecl().
The documentation for this class was generated from the following files:
lib/AST/Interp/Context.h
lib/AST/Interp/Context.cpp