clang: clang::OMPLastprivateClause Class Reference
clang::OMPLastprivateClause Class Reference final
This represents clause 'lastprivate' in the '#pragma omp ...' directives.
#include "clang/AST/OpenMPClause.h"
Public Types
using helper_expr_iterator = MutableArrayRef< Expr * >::iterator
using helper_expr_const_iterator = ArrayRef< const Expr * >::iterator
using helper_expr_range = llvm::iterator_range< helper_expr_iterator >
using helper_expr_const_range = llvm::iterator_range< helper_expr_const_iterator >
Public Types inherited from clang::OMPVarListClause< OMPLastprivateClause >
using varlist_iterator = MutableArrayRef< Expr * >::iterator
using varlist_const_iterator = ArrayRef< const Expr * >::iterator
using varlist_range = llvm::iterator_range< varlist_iterator >
using varlist_const_range = llvm::iterator_range< varlist_const_iterator >
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
OpenMPLastprivateModifier getKind () const
Lastprivate kind.
SourceLocation getKindLoc () const
Returns the location of the lastprivate kind.
SourceLocation getColonLoc () const
Returns the location of the ':' symbol, if any.
void setPrivateCopies (ArrayRef< Expr * > PrivateCopies)
Set list of helper expressions, required for generation of private copies of original lastprivate variables.
helper_expr_const_range private_copies () const
helper_expr_range private_copies ()
helper_expr_const_range source_exprs () const
helper_expr_range source_exprs ()
helper_expr_const_range destination_exprs () const
helper_expr_range destination_exprs ()
helper_expr_const_range assignment_ops () const
helper_expr_range assignment_ops ()
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPVarListClause< OMPLastprivateClause >
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_const_iterator varlist_begin () const
varlist_iterator varlist_end ()
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPostUpdate
const Expr * getPostUpdateExpr () const
Get post-update expression for the clause.
Expr * getPostUpdateExpr ()
Get post-update expression for the clause.
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static OMPLastprivateClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< Expr * > VL, ArrayRef< Expr * > SrcExprs, ArrayRef< Expr * > DstExprs, ArrayRef< Expr * > AssignmentOps, OpenMPLastprivateModifier LPKind, SourceLocation LPKindLoc, SourceLocation ColonLoc, Stmt *PreInit, Expr *PostUpdate)
Creates clause with a list of variables VL.
static OMPLastprivateClause * CreateEmpty (const ASTContext &C, unsigned N)
Creates an empty clause with the place for N variables.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPostUpdate
static OMPClauseWithPostUpdate * get (OMPClause *C)
static const OMPClauseWithPostUpdate * get (const OMPClause *C)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Friends
class OMPClauseReader
Additional Inherited Members
Protected Member Functions inherited from clang::OMPVarListClause< OMPLastprivateClause >
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPostUpdate
OMPClauseWithPostUpdate (const OMPClause *This)
void setPostUpdateExpr (Expr *S)
Set pre-initialization statement for the clause.
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents clause 'lastprivate' in the '#pragma omp ...' directives.
#pragma omp simd lastprivate(a,b)
In this example directive '#pragma omp simd' has clause 'lastprivate' with the variables 'a' and 'b'.
Definition at line 2893 of file OpenMPClause.h.
Member Typedef Documentation
helper_expr_const_iterator
using clang::OMPLastprivateClause::helper_expr_const_iterator = ArrayRef<const Expr *>::iterator
Definition at line 3054 of file OpenMPClause.h.
helper_expr_const_range
using clang::OMPLastprivateClause::helper_expr_const_range = llvm::iterator_range<helper_expr_const_iterator>
Definition at line 3056 of file OpenMPClause.h.
helper_expr_iterator
using clang::OMPLastprivateClause::helper_expr_iterator = MutableArrayRef<Expr *>::iterator
Definition at line 3053 of file OpenMPClause.h.
helper_expr_range
using clang::OMPLastprivateClause::helper_expr_range = llvm::iterator_range<helper_expr_iterator>
Definition at line 3055 of file OpenMPClause.h.
Member Function Documentation
assignment_ops() [1/2]
helper_expr_range clang::OMPLastprivateClause::assignment_ops () inline
Definition at line 3097 of file OpenMPClause.h.
assignment_ops() [2/2]
helper_expr_const_range clang::OMPLastprivateClause::assignment_ops () const inline
Definition at line 3092 of file OpenMPClause.h.
children() [1/2]
child_range clang::OMPLastprivateClause::children () inline
Definition at line 3102 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPLastprivateClause >::varlist_begin(), and clang::OMPVarListClause< OMPLastprivateClause >::varlist_end().
Referenced by children().
children() [2/2]
const_child_range clang::OMPLastprivateClause::children () const inline
Definition at line 3107 of file OpenMPClause.h.
References children().
classof()
static bool clang::OMPLastprivateClause::classof (const OMPClause * T) inline static
Definition at line 3119 of file OpenMPClause.h.
References clang::T.
Create()
OMPLastprivateClause * OMPLastprivateClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< Expr * > VL, ArrayRef< Expr * > SrcExprs, ArrayRef< Expr * > DstExprs, ArrayRef< Expr * > AssignmentOps, OpenMPLastprivateModifier LPKind, SourceLocation LPKindLoc, SourceLocation ColonLoc, Stmt * PreInit, Expr * PostUpdate) static
Creates clause with a list of variables VL.
Parameters
C AST context.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
VL List of references to the variables.
SrcExprs List of helper expressions for proper generation of assignment operation required for lastprivate clause. This list represents private variables (for arrays, single array element).
DstExprs List of helper expressions for proper generation of assignment operation required for lastprivate clause. This list represents original variables (for arrays, single array element).
AssignmentOps List of helper expressions that represents assignment operation:
DstExprs = SrcExprs;
Required for proper codegen of final assignment performed by the lastprivate clause.
LPKind Lastprivate kind, e.g. 'conditional'.
LPKindLoc Location of the lastprivate kind.
ColonLoc Location of the ':' symbol if lastprivate kind is used.
PreInit Statement that must be executed before entering the OpenMP region with this clause.
PostUpdate Expression that must be executed after exit from the OpenMP region with this clause.
Definition at line 513 of file OpenMPClause.cpp.
References clang::OMPClauseWithPostUpdate::setPostUpdateExpr(), clang::OMPClauseWithPreInit::setPreInitStmt(), and clang::OMPVarListClause< T >::setVarRefs().
Referenced by clang::SemaOpenMP::ActOnOpenMPLastprivateClause().
CreateEmpty()
OMPLastprivateClause * OMPLastprivateClause::CreateEmpty (const ASTContext & C, unsigned N) static
Creates an empty clause with the place for N variables.
Parameters
C AST context.
N The number of variables.
Definition at line 531 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
destination_exprs() [1/2]
helper_expr_range clang::OMPLastprivateClause::destination_exprs () inline
Definition at line 3087 of file OpenMPClause.h.
destination_exprs() [2/2]
helper_expr_const_range clang::OMPLastprivateClause::destination_exprs () const inline
Definition at line 3082 of file OpenMPClause.h.
getColonLoc()
SourceLocation clang::OMPLastprivateClause::getColonLoc () const inline
Returns the location of the ':' symbol, if any.
Definition at line 3051 of file OpenMPClause.h.
getKind()
OpenMPLastprivateModifier clang::OMPLastprivateClause::getKind () const inline
Lastprivate kind.
Definition at line 3047 of file OpenMPClause.h.
getKindLoc()
SourceLocation clang::OMPLastprivateClause::getKindLoc () const inline
Returns the location of the lastprivate kind.
Definition at line 3049 of file OpenMPClause.h.
private_copies() [1/2]
helper_expr_range clang::OMPLastprivateClause::private_copies () inline
Definition at line 3068 of file OpenMPClause.h.
private_copies() [2/2]
helper_expr_const_range clang::OMPLastprivateClause::private_copies () const inline
Definition at line 3063 of file OpenMPClause.h.
setPrivateCopies()
void OMPLastprivateClause::setPrivateCopies (ArrayRef< Expr * > PrivateCopies)
Set list of helper expressions, required for generation of private copies of original lastprivate variables.
Definition at line 485 of file OpenMPClause.cpp.
source_exprs() [1/2]
helper_expr_range clang::OMPLastprivateClause::source_exprs () inline
Definition at line 3078 of file OpenMPClause.h.
source_exprs() [2/2]
helper_expr_const_range clang::OMPLastprivateClause::source_exprs () const inline
Definition at line 3073 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPLastprivateClause::used_children () inline
Definition at line 3112 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPLastprivateClause::used_children () const inline
Definition at line 3115 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 2913 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp