clang: clang::TypeOfExprTypeLoc Class Reference
clang::TypeOfExprTypeLoc Class Reference
#include "clang/AST/TypeLoc.h"
Public Member Functions
Expr * getUnderlyingExpr () const
SourceRange getLocalSourceRange () const
Public Member Functions inherited from clang::TypeofLikeTypeLoc< TypeOfExprTypeLoc, TypeOfExprType, TypeOfExprTypeLocInfo >
SourceLocation getTypeofLoc () const
void setTypeofLoc (SourceLocation Loc)
SourceLocation getLParenLoc () const
void setLParenLoc (SourceLocation Loc)
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation Loc)
SourceRange getParensRange () const
void setParensRange (SourceRange range)
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
Public Member Functions inherited from clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (Derived other)
TypeLoc getNextTypeLoc () const
const TypeClass * getTypePtr () const
Additional Inherited Members
Protected Member Functions inherited from clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
LocalData * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Detailed Description
Definition at line 2036 of file TypeLoc.h.
Member Function Documentation
getLocalSourceRange()
SourceRange TypeOfExprTypeLoc::getLocalSourceRange () const
Definition at line 323 of file TypeLoc.cpp.
References clang::TypeofLikeTypeLoc< TypeOfExprTypeLoc, TypeOfExprType, TypeOfExprTypeLocInfo >::getRParenLoc(), clang::tooling::fixit::internal::getSourceRange(), clang::TypeofLikeTypeLoc< TypeOfExprTypeLoc, TypeOfExprType, TypeOfExprTypeLocInfo >::getTypeofLoc(), and getUnderlyingExpr().
getUnderlyingExpr()
Expr* clang::TypeOfExprTypeLoc::getUnderlyingExpr () const inline
Definition at line 2040 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr().
Referenced by getLocalSourceRange(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeOfExprTypeLoc().
The documentation for this class was generated from the following files:
include/clang/AST/TypeLoc.h
lib/AST/TypeLoc.cpp