clang: clang::APValue::LValueBase Class Reference
clang::APValue::LValueBase Class Reference
#include "clang/AST/APValue.h"
Public Member Functions
LValueBase ()
LValueBase (const ValueDecl *P, unsigned I=0, unsigned V=0)
LValueBase (const Expr *P, unsigned I=0, unsigned V=0)
void Profile (llvm::FoldingSetNodeID &ID) const
template<class T >
bool is () const
template<class T >
T get () const
template<class T >
T dyn_cast () const
void * getOpaqueValue () const
bool isNull () const
operator bool () const
unsigned getCallIndex () const
unsigned getVersion () const
QualType getTypeInfoType () const
QualType getDynamicAllocType () const
QualType getType () const
Static Public Member Functions
static LValueBase getDynamicAlloc (DynamicAllocLValue LV, QualType Type)
static LValueBase getTypeInfo (TypeInfoLValue LV, QualType TypeInfo)
Friends
struct llvm::DenseMapInfo< LValueBase >
bool operator== (const LValueBase &LHS, const LValueBase &RHS)
bool operator!= (const LValueBase &LHS, const LValueBase &RHS)
llvm::hash_code hash_value (const LValueBase &Base)
Detailed Description
Definition at line 146 of file APValue.h.
Constructor & Destructor Documentation
LValueBase() [1/3]
clang::APValue::LValueBase::LValueBase () inline
Definition at line 152 of file APValue.h.
LValueBase() [2/3]
APValue::LValueBase::LValueBase (const ValueDecl * P, unsigned I = 0, unsigned V = 0)
Definition at line 42 of file APValue.cpp.
LValueBase() [3/3]
APValue::LValueBase::LValueBase (const Expr * P, unsigned I = 0, unsigned V = 0)
Definition at line 44 of file APValue.cpp.
Member Function Documentation
dyn_cast()
template<class T > T clang::APValue::LValueBase::dyn_cast () const inline
Definition at line 167 of file APValue.h.
References clang::T.
Referenced by getObjectType(), clang::ASTNodeImporter::ImportAPValue(), IsGlobalLValue(), and clang::CodeGen::CodeGenFunction::tryEmitAsConstant().
get()
template<class T > T clang::APValue::LValueBase::get () const inline
Definition at line 164 of file APValue.h.
References clang::T.
Referenced by clang::ASTNodeImporter::ImportAPValue(), and IsGlobalLValue().
getCallIndex()
unsigned APValue::LValueBase::getCallIndex () const
Definition at line 108 of file APValue.cpp.
Referenced by clang::ASTNodeImporter::ImportAPValue().
getDynamicAlloc()
APValue::LValueBase APValue::LValueBase::getDynamicAlloc (DynamicAllocLValue LV, QualType Type) static
Definition at line 47 of file APValue.cpp.
getDynamicAllocType()
QualType APValue::LValueBase::getDynamicAllocType () const
Definition at line 122 of file APValue.cpp.
References clang::QualType::getFromOpaquePtr().
Referenced by getObjectType().
getOpaqueValue()
void * APValue::LValueBase::getOpaqueValue () const
Definition at line 175 of file APValue.cpp.
getType()
QualType APValue::LValueBase::getType () const
Definition at line 63 of file APValue.cpp.
References clang::Type::isIncompleteArrayType(), and clang::T.
Referenced by getLValueType().
getTypeInfo()
APValue::LValueBase APValue::LValueBase::getTypeInfo (TypeInfoLValue LV, QualType TypeInfo) static
Definition at line 55 of file APValue.cpp.
Referenced by clang::ASTNodeImporter::ImportAPValue().
getTypeInfoType()
QualType APValue::LValueBase::getTypeInfoType () const
Definition at line 117 of file APValue.cpp.
References clang::QualType::getFromOpaquePtr().
Referenced by getObjectType(), and clang::ASTNodeImporter::ImportAPValue().
getVersion()
unsigned APValue::LValueBase::getVersion () const
Definition at line 113 of file APValue.cpp.
Referenced by clang::ASTNodeImporter::ImportAPValue().
is()
template<class T > bool clang::APValue::LValueBase::is () const inline
Definition at line 161 of file APValue.h.
References clang::T.
Referenced by getObjectType(), clang::ASTNodeImporter::ImportAPValue(), and IsGlobalLValue().
isNull()
bool APValue::LValueBase::isNull () const
Definition at line 179 of file APValue.cpp.
operator bool()
APValue::LValueBase::operator bool () const explicit
Definition at line 183 of file APValue.cpp.
Profile()
void APValue::LValueBase::Profile (llvm::FoldingSetNodeID & ID) const
Definition at line 127 of file APValue.cpp.
References ID.
Referenced by clang::APValue::Profile().
Friends And Related Function Documentation
hash_value
llvm::hash_code hash_value (const LValueBase & Base) friend
Definition at line 202 of file APValue.cpp.
llvm::DenseMapInfo< LValueBase >
friend struct llvm::DenseMapInfo< LValueBase > friend
Definition at line 186 of file APValue.h.
operator!=
bool operator!= (const LValueBase & LHS, const LValueBase & RHS) friend
Definition at line 183 of file APValue.h.
operator==
bool operator== (const LValueBase & LHS, const LValueBase & RHS) friend
Definition at line 136 of file APValue.cpp.
Member Data Documentation
DynamicAllocType
void* clang::APValue::LValueBase::DynamicAllocType
The QualType, if this is a DynamicAllocLValue.
Definition at line 199 of file APValue.h.
Local
LocalState clang::APValue::LValueBase::Local
Definition at line 195 of file APValue.h.
TypeInfoType
void* clang::APValue::LValueBase::TypeInfoType
The type std::type_info, if this is a TypeInfoLValue.
Definition at line 197 of file APValue.h.
The documentation for this class was generated from the following files:
include/clang/AST/APValue.h
lib/AST/APValue.cpp