clang: clang::CodeGen::RequiredArgs Class Reference
clang::CodeGen::RequiredArgs Class Reference
A class for recording the number of arguments that a function signature requires.
#include "clang/CodeGen/CGFunctionInfo.h"
Public Types
enum All_t { All }
Public Member Functions
RequiredArgs (All_t _)
RequiredArgs (unsigned n)
bool allowsOptionalArgs () const
unsigned getNumRequiredArgs () const
unsigned getOpaqueData () const
Static Public Member Functions
static RequiredArgs forPrototypePlus (const FunctionProtoType *prototype, unsigned additional)
Compute the arguments required by the given formal prototype, given that there may be some additional, non-formal arguments in play.
static RequiredArgs forPrototypePlus (CanQual< FunctionProtoType > prototype, unsigned additional)
static RequiredArgs forPrototype (const FunctionProtoType *prototype)
static RequiredArgs forPrototype (CanQual< FunctionProtoType > prototype)
static RequiredArgs getFromOpaqueData (unsigned value)
Detailed Description
A class for recording the number of arguments that a function signature requires.
Definition at line 480 of file CGFunctionInfo.h.
Member Enumeration Documentation
All_t
enum clang::CodeGen::RequiredArgs::All_t
Enumerator
All
Definition at line 485 of file CGFunctionInfo.h.
Constructor & Destructor Documentation
RequiredArgs() [1/2]
clang::CodeGen::RequiredArgs::RequiredArgs (All_t _) inline
Definition at line 487 of file CGFunctionInfo.h.
Referenced by forPrototypePlus(), and getFromOpaqueData().
RequiredArgs() [2/2]
clang::CodeGen::RequiredArgs::RequiredArgs (unsigned n) inline explicit
Definition at line 488 of file CGFunctionInfo.h.
Member Function Documentation
allowsOptionalArgs()
bool clang::CodeGen::RequiredArgs::allowsOptionalArgs () const inline
Definition at line 524 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CodeGenTypes::arrangeCall(), clang::CodeGen::CGFunctionInfo::create(), getNumRequiredArgs(), and clang::CodeGen::CGFunctionInfo::isVariadic().
forPrototype() [1/2]
static RequiredArgs clang::CodeGen::RequiredArgs::forPrototype (CanQual< FunctionProtoType > prototype) inline static
Definition at line 520 of file CGFunctionInfo.h.
References forPrototypePlus(), and clang::CanQual< T >::getTypePtr().
forPrototype() [2/2]
static RequiredArgs clang::CodeGen::RequiredArgs::forPrototype (const FunctionProtoType * prototype) inline static
Definition at line 516 of file CGFunctionInfo.h.
References forPrototypePlus().
forPrototypePlus() [1/2]
static RequiredArgs clang::CodeGen::RequiredArgs::forPrototypePlus (CanQual< FunctionProtoType > prototype, unsigned additional) inline static
Definition at line 511 of file CGFunctionInfo.h.
References forPrototypePlus(), and clang::CanQual< T >::getTypePtr().
forPrototypePlus() [2/2]
static RequiredArgs clang::CodeGen::RequiredArgs::forPrototypePlus (const FunctionProtoType * prototype, unsigned additional) inline static
Compute the arguments required by the given formal prototype, given that there may be some additional, non-formal arguments in play.
If FD is not null, this will consider pass_object_size params in FD.
Definition at line 497 of file CGFunctionInfo.h.
References All, clang::FunctionProtoType::getExtParameterInfos(), clang::FunctionProtoType::getNumParams(), clang::FunctionProtoType::hasExtParameterInfos(), clang::FunctionProtoType::isVariadic(), and RequiredArgs().
Referenced by clang::CodeGen::CodeGenTypes::arrangeBlockFunctionDeclaration(), clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), arrangeFreeFunctionLikeCall(), arrangeLLVMFunctionInfo(), commonEmitCXXMemberOrOperatorCall(), clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::EmitCXXMemberPointerCallExpr(), forPrototype(), and forPrototypePlus().
getFromOpaqueData()
static RequiredArgs clang::CodeGen::RequiredArgs::getFromOpaqueData (unsigned value) inline static
Definition at line 531 of file CGFunctionInfo.h.
References All, and RequiredArgs().
getNumRequiredArgs()
unsigned clang::CodeGen::RequiredArgs::getNumRequiredArgs () const inline
Definition at line 525 of file CGFunctionInfo.h.
References allowsOptionalArgs().
Referenced by clang::CodeGen::CGFunctionInfo::create(), and clang::CodeGen::CGFunctionInfo::getNumRequiredArgs().
getOpaqueData()
unsigned clang::CodeGen::RequiredArgs::getOpaqueData () const inline
Definition at line 530 of file CGFunctionInfo.h.
Referenced by clang::CodeGen::CGFunctionInfo::Profile().
The documentation for this class was generated from the following file:
include/clang/CodeGen/CGFunctionInfo.h