clang: clang::threadSafety::til::Goto Class Reference
clang::threadSafety::til::Goto Class Reference
Jump to another basic block.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Goto (BasicBlock *B, unsigned I)
Goto (const Goto &G, BasicBlock *B, unsigned I)
const BasicBlock * targetBlock () const
BasicBlock * targetBlock ()
unsigned index () const
Returns the index into the.
ArrayRef< BasicBlock * > successors ()
Return the list of basic blocks that this terminator can branch to.
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Goto *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::Terminator
ArrayRef< BasicBlock * > successors ()
Return the list of basic blocks that this terminator can branch to.
ArrayRef< BasicBlock * > successors () const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Static Public Member Functions inherited from clang::threadSafety::til::Terminator
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::Terminator
Terminator (TIL_Opcode Op)
Terminator (const SExpr &E)
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
SExpr & operator= (const SExpr &)=delete
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Jump to another basic block.
A goto instruction is essentially a tail-recursive call into another block. In addition to the block pointer, it specifies an index into the phi nodes of that block. The index can be used to retrieve the "arguments" of the call.
Definition at line 1378 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Goto() [1/2]
clang::threadSafety::til::Goto::Goto (BasicBlock * B, unsigned I) inline
Definition at line 1380 of file ThreadSafetyTIL.h.
Goto() [2/2]
clang::threadSafety::til::Goto::Goto (const Goto & G, BasicBlock * B, unsigned I) inline
Definition at line 1382 of file ThreadSafetyTIL.h.
Member Function Documentation
classof()
static bool clang::threadSafety::til::Goto::classof (const SExpr * E) inline static
Definition at line 1385 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Goto::compare (const Goto * E, C & Cmp) const inline
Definition at line 1403 of file ThreadSafetyTIL.h.
index()
unsigned clang::threadSafety::til::Goto::index () const inline
Returns the index into the.
Definition at line 1391 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printGoto().
successors()
ArrayRef<BasicBlock *> clang::threadSafety::til::Goto::successors () inline
Return the list of basic blocks that this terminator can branch to.
Definition at line 1394 of file ThreadSafetyTIL.h.
targetBlock() [1/2]
BasicBlock* clang::threadSafety::til::Goto::targetBlock () inline
Definition at line 1388 of file ThreadSafetyTIL.h.
targetBlock() [2/2]
const BasicBlock* clang::threadSafety::til::Goto::targetBlock () const inline
Definition at line 1387 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printGoto().
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Goto::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1397 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h