clang: clang::ento::AnyCXXConstructorCall Class Reference
clang::ento::AnyCXXConstructorCall Class Reference
Represents any constructor invocation.
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
Public Member Functions
SVal getCXXThisVal () const
Returns the value of the implicit 'this' object.
Public Member Functions inherited from clang::ento::AnyFunctionCall
const FunctionDecl * getDecl () const override
Returns the declaration of the function or method that will be called.
RuntimeDefinition getRuntimeDefinition () const override
Returns the definition of the function or method that will be called.
bool argumentsMayEscape () const override
Returns true if any of the arguments are known to escape to long- term storage, even if this method will not modify them.
ArrayRef< ParmVarDecl * > parameters () const override
Return call's formal parameters.
Public Member Functions inherited from clang::ento::CallEvent
CallEvent & operator= (const CallEvent &)=delete
virtual ~CallEvent ()=default
virtual Kind getKind () const =0
Returns the kind of call this is.
virtual StringRef getKindAsString () const =0
const ProgramStateRef & getState () const
The state in which the call is being evaluated.
const LocationContext * getLocationContext () const
The context in which the call is being evaluated.
virtual const Expr * getOriginExpr () const
Returns the expression whose value will be the result of this call.
virtual unsigned getNumArgs () const =0
Returns the number of arguments (explicit and implicit).
bool isInSystemHeader () const
Returns true if the callee is known to be from a system header.
virtual SourceRange getSourceRange () const
Returns a source range for the entire call, suitable for outputting in diagnostics.
virtual SVal getArgSVal (unsigned Index) const
Returns the value of a given argument at the time of the call.
virtual const Expr * getArgExpr (unsigned Index) const
Returns the expression associated with a given argument.
virtual SourceRange getArgSourceRange (unsigned Index) const
Returns the source range for errors associated with this argument.
QualType getResultType () const
Returns the result type, adjusted for references.
SVal getReturnValue () const
Returns the return value of the call.
bool hasNonNullArgumentsWithType (bool(*Condition)(QualType)) const
Returns true if the type of any of the non-null arguments satisfies the condition.
bool hasNonZeroCallbackArg () const
Returns true if any of the arguments appear to represent callbacks.
bool hasVoidPointerToNonConstArg () const
Returns true if any of the arguments is void*.
bool isGlobalCFunction (StringRef SpecificName=StringRef()) const
Returns true if the callee is an externally-visible function in the top-level namespace, such as malloc.
const IdentifierInfo * getCalleeIdentifier () const
Returns the name of the callee, if its name is a simple identifier.
ProgramPoint getProgramPoint (bool IsPreVisit=false, const ProgramPointTag *Tag=nullptr) const
Returns an appropriate ProgramPoint for this call.
ProgramStateRef invalidateRegions (unsigned BlockCount, ProgramStateRef Orig=nullptr) const
Returns a new state with all argument regions invalidated.
template<typename T >
CallEventRef< T > cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
CallEventRef cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
AnalysisDeclContext * getCalleeAnalysisDeclContext () const
Returns AnalysisDeclContext for the callee stack frame.
const StackFrameContext * getCalleeStackFrame (unsigned BlockCount) const
Returns the callee stack frame.
const ParamVarRegion * getParameterLocation (unsigned Index, unsigned BlockCount) const
Returns memory location for a parameter variable within the callee stack frame.
bool isArgumentConstructedDirectly (unsigned Index) const
Returns true if on the current path, the argument was constructed by calling a C++ constructor over it.
virtual Optional< unsigned > getAdjustedParameterIndex (unsigned ASTArgumentIndex) const
Some calls have parameter numbering mismatched from argument numbering.
virtual unsigned getASTArgumentIndex (unsigned CallArgumentIndex) const
Some call event sub-classes conveniently adjust mismatching AST indices to match parameter indices.
const ConstructionContext * getConstructionContext () const
Returns the construction context of the call, if it is a C++ constructor call or a call of a function returning a C++ class instance.
Optional< SVal > getReturnValueUnderConstruction () const
If the call returns a C++ record type then the region of its return value can be retrieved from its construction context.
param_type_iterator param_type_begin () const
Returns an iterator over the types of the call's formal parameters.
param_type_iterator param_type_end () const
void dump (raw_ostream &Out) const
void dump () const
Static Public Member Functions
static bool classof (const CallEvent *Call)
Static Public Member Functions inherited from clang::ento::AnyFunctionCall
static bool classof (const CallEvent *CA)
Static Public Member Functions inherited from clang::ento::CallEvent
static bool isCallStmt (const Stmt *S)
Returns true if this is a statement is a function or method call of some kind.
static QualType getDeclaredResultType (const Decl *D)
Returns the result type of a function or method declaration.
static bool isVariadic (const Decl *D)
Returns true if the given decl is known to be variadic.
Protected Member Functions
AnyCXXConstructorCall (const Expr *E, const MemRegion *Target, ProgramStateRef St, const LocationContext *LCtx)
void getExtraInvalidatedValues (ValueList &Values, RegionAndSymbolInvalidationTraits *ETraits) const override
Used to specify non-argument regions that will be invalidated as a result of this call.
void getInitialStackFrameContents (const StackFrameContext *CalleeCtx, BindingsTy &Bindings) const override
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
Protected Member Functions inherited from clang::ento::AnyFunctionCall
AnyFunctionCall (const Expr *E, ProgramStateRef St, const LocationContext *LCtx)
AnyFunctionCall (const Decl *D, ProgramStateRef St, const LocationContext *LCtx)
AnyFunctionCall (const AnyFunctionCall &Other)=default
Protected Member Functions inherited from clang::ento::CallEvent
CallEvent (const Expr *E, ProgramStateRef state, const LocationContext *lctx)
CallEvent (const Decl *D, ProgramStateRef state, const LocationContext *lctx)
CallEvent (const CallEvent &Original)
virtual void cloneTo (void *Dest) const =0
Copies this CallEvent, with vtable intact, into a new block of memory.
SVal getSVal (const Stmt *S) const
Get the value of arbitrary expressions at this point in the path.
Additional Inherited Members
Public Types inherited from clang::ento::CallEvent
using Kind = CallEventKind
using FrameBindingTy = std::pair< SVal, SVal >
using BindingsTy = SmallVectorImpl< FrameBindingTy >
using param_type_iterator = llvm::mapped_iterator< ArrayRef< ParmVarDecl * >::iterator, GetTypeFn >
Protected Types inherited from clang::ento::CallEvent
using ValueList = SmallVectorImpl< SVal >
Protected Attributes inherited from clang::ento::CallEvent
const void * Data
SourceLocation Location
Detailed Description
Represents any constructor invocation.
This includes regular constructors and inherited constructors.
Definition at line 831 of file CallEvent.h.
Constructor & Destructor Documentation
AnyCXXConstructorCall()
clang::ento::AnyCXXConstructorCall::AnyCXXConstructorCall (const Expr * E, const MemRegion * Target, ProgramStateRef St, const LocationContext * LCtx) inline protected
Definition at line 833 of file CallEvent.h.
References clang::ento::CallEvent::Data, and clang::Target.
Member Function Documentation
classof()
static bool clang::ento::AnyCXXConstructorCall::classof (const CallEvent * Call) inline static
Definition at line 851 of file CallEvent.h.
References clang::ento::CE_BEG_CXX_CONSTRUCTOR_CALLS, and clang::ento::CE_END_CXX_CONSTRUCTOR_CALLS.
getCXXThisVal()
SVal AnyCXXConstructorCall::getCXXThisVal () const
Returns the value of the implicit 'this' object.
Definition at line 848 of file CallEvent.cpp.
References clang::ento::CallEvent::Data.
Referenced by getExtraInvalidatedValues(), and getInitialStackFrameContents().
getExtraInvalidatedValues()
void AnyCXXConstructorCall::getExtraInvalidatedValues (ValueList & Values, RegionAndSymbolInvalidationTraits * ETraits) const override protected virtual
Used to specify non-argument regions that will be invalidated as a result of this call.
Reimplemented from clang::ento::CallEvent.
Definition at line 854 of file CallEvent.cpp.
References getCXXThisVal(), clang::ento::RegionAndSymbolInvalidationTraits::setTrait(), clang::ento::RegionAndSymbolInvalidationTraits::TK_SuppressEscape, and V.
getInitialStackFrameContents()
void AnyCXXConstructorCall::getInitialStackFrameContents (const StackFrameContext * CalleeCtx, BindingsTy & Bindings) const override protected virtual
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
Reimplemented from clang::ento::AnyFunctionCall.
Definition at line 863 of file CallEvent.cpp.
References clang::ento::SValBuilder::getCXXThis(), getCXXThisVal(), clang::LocationContext::getDecl(), clang::ento::AnyFunctionCall::getInitialStackFrameContents(), clang::ento::CallEvent::getState(), and clang::ento::SVal::isUnknown().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h
lib/StaticAnalyzer/Core/CallEvent.cpp