clang: clang::TextDiagnosticPrinter Class Reference
clang::TextDiagnosticPrinter Class Reference
#include "clang/Frontend/TextDiagnosticPrinter.h"
Public Member Functions
TextDiagnosticPrinter (raw_ostream &os, DiagnosticOptions *diags, bool OwnsOutputStream=false)
~TextDiagnosticPrinter () override
void setPrefix (std::string Value)
setPrefix - Set the diagnostic printer prefix string, which will be printed at the start of any diagnostics.
void BeginSourceFile (const LangOptions &LO, const Preprocessor *PP) override
Callback to inform the diagnostic client that processing of a source file is beginning.
void EndSourceFile () override
Callback to inform the diagnostic client that processing of a source file has ended.
void HandleDiagnostic (DiagnosticsEngine::Level Level, const Diagnostic &Info) override
Handle this diagnostic, reporting it to the user or capturing it to a log as needed.
Public Member Functions inherited from clang::DiagnosticConsumer
DiagnosticConsumer ()=default
virtual ~DiagnosticConsumer ()
unsigned getNumErrors () const
unsigned getNumWarnings () const
virtual void clear ()
virtual void finish ()
Callback to inform the diagnostic client that processing of all source files has ended.
virtual bool IncludeInDiagnosticCounts () const
Indicates whether the diagnostics handled by this DiagnosticConsumer should be included in the number of diagnostics reported by DiagnosticsEngine.
Additional Inherited Members
Protected Attributes inherited from clang::DiagnosticConsumer
unsigned NumWarnings = 0
Number of warnings reported.
unsigned NumErrors = 0
Number of errors reported.
Detailed Description
Definition at line 27 of file TextDiagnosticPrinter.h.
Constructor & Destructor Documentation
TextDiagnosticPrinter()
TextDiagnosticPrinter::TextDiagnosticPrinter (raw_ostream & os, DiagnosticOptions * diags, bool OwnsOutputStream = false)
Definition at line 24 of file TextDiagnosticPrinter.cpp.
~TextDiagnosticPrinter()
TextDiagnosticPrinter::~TextDiagnosticPrinter () override
Definition at line 31 of file TextDiagnosticPrinter.cpp.
Member Function Documentation
BeginSourceFile()
void TextDiagnosticPrinter::BeginSourceFile (const LangOptions & LangOpts, const Preprocessor * PP) override virtual
Callback to inform the diagnostic client that processing of a source file is beginning.
Note that diagnostics may be emitted outside the processing of a source file, for example during the parsing of command line options. However, diagnostics with source range information are required to only be emitted in between BeginSourceFile() and EndSourceFile().
Parameters
LangOpts The language options for the source file being processed.
PP The preprocessor object being used for the source; this is optional, e.g., it may not be present when processing AST source files.
Reimplemented from clang::DiagnosticConsumer.
Definition at line 36 of file TextDiagnosticPrinter.cpp.
Referenced by emitPremigrationErrors().
EndSourceFile()
void TextDiagnosticPrinter::EndSourceFile () override virtual
Callback to inform the diagnostic client that processing of a source file has ended.
The diagnostic client should assume that any objects made available via BeginSourceFile() are inaccessible.
Reimplemented from clang::DiagnosticConsumer.
Definition at line 42 of file TextDiagnosticPrinter.cpp.
Referenced by emitPremigrationErrors().
HandleDiagnostic()
void TextDiagnosticPrinter::HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const Diagnostic & Info) override virtual
Handle this diagnostic, reporting it to the user or capturing it to a log as needed.
The default implementation just keeps track of the total number of warnings and errors.
Reimplemented from clang::DiagnosticConsumer.
Definition at line 109 of file TextDiagnosticPrinter.cpp.
References clang::Diagnostic::FormatDiagnostic(), clang::Diagnostic::getFixItHints(), clang::Diagnostic::getLocation(), clang::Diagnostic::getRanges(), clang::Diagnostic::getSourceManager(), clang::DiagnosticConsumer::HandleDiagnostic(), clang::Diagnostic::hasSourceManager(), clang::SourceLocation::isValid(), clang::DiagnosticsEngine::Note, clang::TextDiagnostic::printDiagnosticLevel(), clang::TextDiagnostic::printDiagnosticMessage(), and printDiagnosticOptions().
setPrefix()
void clang::TextDiagnosticPrinter::setPrefix (std::string Value) inline
setPrefix - Set the diagnostic printer prefix string, which will be printed at the start of any diagnostics.
If empty, no prefix string is used.
Definition at line 48 of file TextDiagnosticPrinter.h.
The documentation for this class was generated from the following files:
include/clang/Frontend/TextDiagnosticPrinter.h
lib/Frontend/TextDiagnosticPrinter.cpp