clang: clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor Class Reference
clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/ASTMatchers/Dynamic/Marshallers.h"
Public Member Functions
MapAnyOfMatcherDescriptor (ASTNodeKind CladeNodeKind, std::vector< ASTNodeKind > NodeKinds)
VariantMatcher create (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics *Error) const override
bool isVariadic () const override
Returns whether the matcher is variadic.
unsigned getNumArgs () const override
Returns the number of arguments accepted by the matcher if not variadic.
void getArgKinds (ASTNodeKind ThisKind, unsigned, std::vector< ArgKind > &Kinds) const override
Given that the matcher is being converted to type ThisKind, append the set of argument types accepted for argument ArgNo to ArgKinds.
bool isConvertibleTo (ASTNodeKind Kind, unsigned *Specificity, ASTNodeKind *LeastDerivedKind) const override
Returns whether this matcher is convertible to the given type.
Public Member Functions inherited from clang::ast_matchers::dynamic::internal::MatcherDescriptor
virtual ~MatcherDescriptor ()=default
virtual ASTNodeKind nodeMatcherType () const
virtual bool isBuilderMatcher () const
virtual std::unique_ptr< MatcherDescriptor > buildMatcherCtor (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics *Error) const
virtual bool isPolymorphic () const
Returns whether the matcher will, given a matcher of any type T, yield a matcher of type T.
Detailed Description
Definition at line 933 of file Marshallers.h.
Constructor & Destructor Documentation
MapAnyOfMatcherDescriptor()
clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor::MapAnyOfMatcherDescriptor (ASTNodeKind CladeNodeKind, std::vector< ASTNodeKind > NodeKinds) inline
Definition at line 938 of file Marshallers.h.
Member Function Documentation
create()
VariantMatcher clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor::create (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics * Error) const inline override virtual
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 942 of file Marshallers.h.
References clang::ast_matchers::dynamic::VariantMatcher::getTypedMatcher(), clang::ast_matchers::dynamic::VariantMatcher::hasTypedMatcher(), and clang::ast_matchers::dynamic::VariantMatcher::SingleMatcher().
getArgKinds()
void clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor::getArgKinds (ASTNodeKind ThisKind, unsigned ArgNo, std::vector< ArgKind > & ArgKinds) const inline override virtual
Given that the matcher is being converted to type ThisKind, append the set of argument types accepted for argument ArgNo to ArgKinds.
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 982 of file Marshallers.h.
References clang::ast_matchers::dynamic::ArgKind::MakeMatcherArg().
getNumArgs()
unsigned clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor::getNumArgs () const inline override virtual
Returns the number of arguments accepted by the matcher if not variadic.
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 980 of file Marshallers.h.
isConvertibleTo()
bool clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor::isConvertibleTo (ASTNodeKind Kind, unsigned * Specificity, ASTNodeKind * LeastDerivedKind) const inline override virtual
Returns whether this matcher is convertible to the given type.
If it is so convertible, store in *Specificity a value corresponding to the "specificity" of the converted matcher to the given context, and in *LeastDerivedKind the least derived matcher kind which would result in the same matcher overload. Zero specificity indicates that this conversion would produce a trivial matcher that will either always or never match. Such matchers are excluded from code completion results.
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 987 of file Marshallers.h.
isVariadic()
bool clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor::isVariadic () const inline override virtual
Returns whether the matcher is variadic.
Variadic matchers can take any number of arguments, but they must be of the same type.
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 979 of file Marshallers.h.
The documentation for this class was generated from the following file:
lib/ASTMatchers/Dynamic/Marshallers.h