clang: clang::APFloatStorage Class Reference
clang::APFloatStorage Class Reference
#include "clang/AST/APNumericStorage.h"
Public Member Functions
llvm::APFloat getValue (const llvm::fltSemantics &Semantics) const
void setValue (const ASTContext &C, const llvm::APFloat &Val)
Detailed Description
Definition at line 59 of file APNumericStorage.h.
Member Function Documentation
getValue()
llvm::APFloat clang::APFloatStorage::getValue (const llvm::fltSemantics & Semantics) const inline
Definition at line 61 of file APNumericStorage.h.
References clang::APNumericStorage::getIntValue().
Referenced by clang::FloatingLiteral::getValue().
setValue()
void clang::APFloatStorage::setValue (const ASTContext & C, const llvm::APFloat & Val) inline
Definition at line 64 of file APNumericStorage.h.
References clang::APNumericStorage::setIntValue().
Referenced by clang::FloatingLiteral::setValue().
The documentation for this class was generated from the following file:
include/clang/AST/APNumericStorage.h