clang: clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType > Class Template Reference
clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType > Class Template Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/ASTMatchers/Dynamic/Marshallers.h"
Public Member Functions
RegexMatcherDescriptor (ReturnType(*WithFlags)(StringRef, llvm::Regex::RegexFlags), ReturnType(*NoFlags)(StringRef), ArrayRef< ASTNodeKind > RetKinds)
bool isVariadic () const override
Returns whether the matcher is variadic.
unsigned getNumArgs () const override
Returns the number of arguments accepted by the matcher if not variadic.
void getArgKinds (ASTNodeKind ThisKind, unsigned ArgNo, std::vector< ArgKind > &Kinds) const override
Given that the matcher is being converted to type ThisKind, append the set of argument types accepted for argument ArgNo to ArgKinds.
bool isConvertibleTo (ASTNodeKind Kind, unsigned *Specificity, ASTNodeKind *LeastDerivedKind) const override
Returns whether this matcher is convertible to the given type.
VariantMatcher create (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics *Error) const override
Public Member Functions inherited from clang::ast_matchers::dynamic::internal::MatcherDescriptor
virtual ~MatcherDescriptor ()=default
virtual ASTNodeKind nodeMatcherType () const
virtual bool isBuilderMatcher () const
virtual std::unique_ptr< MatcherDescriptor > buildMatcherCtor (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics *Error) const
virtual bool isPolymorphic () const
Returns whether the matcher will, given a matcher of any type T, yield a matcher of type T.
Detailed Description
template<typename ReturnType>
class clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >
Definition at line 799 of file Marshallers.h.
Constructor & Destructor Documentation
RegexMatcherDescriptor()
template<typename ReturnType > clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >::RegexMatcherDescriptor (ReturnType(*)(StringRef, llvm::Regex::RegexFlags) WithFlags, ReturnType(*)(StringRef) NoFlags, ArrayRef< ASTNodeKind > RetKinds) inline
Definition at line 801 of file Marshallers.h.
Member Function Documentation
create()
template<typename ReturnType > VariantMatcher clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >::create (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics * Error) const inline override virtual
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 822 of file Marshallers.h.
References clang::ast_matchers::dynamic::Diagnostics::ET_RegistryWrongArgCount, getKind(), and clang::ast_matchers::dynamic::internal::outvalueToVariantMatcher().
getArgKinds()
template<typename ReturnType > void clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >::getArgKinds (ASTNodeKind ThisKind, unsigned ArgNo, std::vector< ArgKind > & ArgKinds) const inline override virtual
Given that the matcher is being converted to type ThisKind, append the set of argument types accepted for argument ArgNo to ArgKinds.
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 810 of file Marshallers.h.
References clang::ast_matchers::dynamic::ArgKind::AK_String.
getNumArgs()
template<typename ReturnType > unsigned clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >::getNumArgs () const inline override virtual
Returns the number of arguments accepted by the matcher if not variadic.
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 808 of file Marshallers.h.
isConvertibleTo()
template<typename ReturnType > bool clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >::isConvertibleTo (ASTNodeKind Kind, unsigned * Specificity, ASTNodeKind * LeastDerivedKind) const inline override virtual
Returns whether this matcher is convertible to the given type.
If it is so convertible, store in *Specificity a value corresponding to the "specificity" of the converted matcher to the given context, and in *LeastDerivedKind the least derived matcher kind which would result in the same matcher overload. Zero specificity indicates that this conversion would produce a trivial matcher that will either always or never match. Such matchers are excluded from code completion results.
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 816 of file Marshallers.h.
References clang::ast_matchers::dynamic::internal::isRetKindConvertibleTo().
isVariadic()
template<typename ReturnType > bool clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >::isVariadic () const inline override virtual
Returns whether the matcher is variadic.
Variadic matchers can take any number of arguments, but they must be of the same type.
Implements clang::ast_matchers::dynamic::internal::MatcherDescriptor.
Definition at line 807 of file Marshallers.h.
The documentation for this class was generated from the following file:
lib/ASTMatchers/Dynamic/Marshallers.h