clang: clang::Declarator Class Reference
clang::Declarator Class Reference
Information about one declarator, including the parsed type information and the identifier.
#include "clang/Sema/DeclSpec.h"
Public Types
typedef SmallVectorImpl< DeclaratorChunk >::const_iterator type_object_iterator
typedef llvm::iterator_range< type_object_iterator > type_object_range
Public Member Functions
Declarator (const DeclSpec &DS, const ParsedAttributesView &DeclarationAttrs, DeclaratorContext C)
DS and DeclarationAttrs must outlive the Declarator.
~Declarator ()
const DeclSpec & getDeclSpec () const
getDeclSpec - Return the declaration-specifier that this declarator was declared with.
DeclSpec & getMutableDeclSpec ()
getMutableDeclSpec - Return a non-const version of the DeclSpec.
AttributePool & getAttributePool () const
const CXXScopeSpec & getCXXScopeSpec () const
getCXXScopeSpec - Return the C++ scope specifier (global scope or nested-name-specifier) that is part of the declarator-id.
CXXScopeSpec & getCXXScopeSpec ()
UnqualifiedId & getName ()
Retrieve the name specified by this declarator.
const DecompositionDeclarator & getDecompositionDeclarator () const
DeclaratorContext getContext () const
bool isPrototypeContext () const
SourceRange getSourceRange () const LLVM_READONLY
Get the source range that spans this declarator.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void SetSourceRange (SourceRange R)
void SetRangeBegin (SourceLocation Loc)
SetRangeBegin - Set the start of the source range to Loc, unless it's invalid.
void SetRangeEnd (SourceLocation Loc)
SetRangeEnd - Set the end of the source range to Loc, unless it's invalid.
void ExtendWithDeclSpec (const DeclSpec &DS)
ExtendWithDeclSpec - Extend the declarator source range to include the given declspec, unless its location is invalid.
void clear ()
Reset the contents of this Declarator.
bool mayOmitIdentifier () const
mayOmitIdentifier - Return true if the identifier is either optional or not allowed.
bool mayHaveIdentifier () const
mayHaveIdentifier - Return true if the identifier is either optional or required.
bool mayHaveDecompositionDeclarator () const
Return true if the context permits a C++17 decomposition declarator.
bool mayBeFollowedByCXXDirectInit () const
mayBeFollowedByCXXDirectInit - Return true if the declarator can be followed by a C++ direct initializer, e.g.
bool isPastIdentifier () const
isPastIdentifier - Return true if we have parsed beyond the point where the name would appear.
bool hasName () const
hasName - Whether this declarator has a name, which might be an identifier (accessible via getIdentifier()) or some kind of special C++ name (constructor, destructor, etc.), or a structured binding (which is not exactly a name, but occupies the same position).
bool isDecompositionDeclarator () const
Return whether this declarator is a decomposition declarator.
const IdentifierInfo * getIdentifier () const
SourceLocation getIdentifierLoc () const
void SetIdentifier (const IdentifierInfo *Id, SourceLocation IdLoc)
Set the name of this declarator to be the given identifier.
void setDecompositionBindings (SourceLocation LSquareLoc, ArrayRef< DecompositionDeclarator::Binding > Bindings, SourceLocation RSquareLoc)
Set the decomposition bindings for this declarator.
void AddTypeInfo (const DeclaratorChunk &TI, ParsedAttributes &&attrs, SourceLocation EndLoc)
AddTypeInfo - Add a chunk to this declarator.
void AddTypeInfo (const DeclaratorChunk &TI, AttributePool &OtherPool, SourceLocation EndLoc)
AddTypeInfo - Add a chunk to this declarator.
void AddTypeInfo (const DeclaratorChunk &TI, SourceLocation EndLoc)
AddTypeInfo - Add a chunk to this declarator.
void AddInnermostTypeInfo (const DeclaratorChunk &TI)
Add a new innermost chunk to this declarator.
unsigned getNumTypeObjects () const
Return the number of types applied to this declarator.
const DeclaratorChunk & getTypeObject (unsigned i) const
Return the specified TypeInfo from this declarator.
DeclaratorChunk & getTypeObject (unsigned i)
type_object_range type_objects () const
Returns the range of type objects, from the identifier outwards.
void DropFirstTypeObject ()
const DeclaratorChunk * getInnermostNonParenChunk () const
Return the innermost (closest to the declarator) chunk of this declarator that is not a parens chunk, or null if there are no non-parens chunks.
const DeclaratorChunk * getOutermostNonParenChunk () const
Return the outermost (furthest from the declarator) chunk of this declarator that is not a parens chunk, or null if there are no non-parens chunks.
bool isArrayOfUnknownBound () const
isArrayOfUnknownBound - This method returns true if the declarator is a declarator for an array of unknown bound (looking through parentheses).
bool isFunctionDeclarator (unsigned &idx) const
isFunctionDeclarator - This method returns true if the declarator is a function declarator (looking through parentheses).
bool isFunctionDeclarator () const
isFunctionDeclarator - Once this declarator is fully parsed and formed, this method returns true if the identifier is a function declarator (looking through parentheses).
DeclaratorChunk::FunctionTypeInfo & getFunctionTypeInfo ()
getFunctionTypeInfo - Retrieves the function type info object (looking through parentheses).
const DeclaratorChunk::FunctionTypeInfo & getFunctionTypeInfo () const
getFunctionTypeInfo - Retrieves the function type info object (looking through parentheses).
bool isDeclarationOfFunction () const
Determine whether the declaration that will be produced from this declaration will be a function.
bool isFunctionDeclarationContext () const
Return true if this declaration appears in a context where a function declarator would be a function declaration.
bool isExpressionContext () const
Determine whether this declaration appears in a context where an expression could appear.
bool isFunctionDeclaratorAFunctionDeclaration () const
Return true if a function declarator at this position would be a function declaration.
bool hasTrailingReturnType () const
Determine whether a trailing return type was written (at any level) within this declarator.
ParsedType getTrailingReturnType () const
Get the trailing return type appearing (at any level) within this declarator.
void setTrailingRequiresClause (Expr *TRC)
Sets a trailing requires clause for this declarator.
Expr * getTrailingRequiresClause ()
Sets a trailing requires clause for this declarator.
bool hasTrailingRequiresClause () const
Determine whether a trailing requires clause was written in this declarator.
void setTemplateParameterLists (ArrayRef< TemplateParameterList * > TPLs)
Sets the template parameter lists that preceded the declarator.
ArrayRef< TemplateParameterList * > getTemplateParameterLists () const
The template parameter lists that preceded the declarator.
void setInventedTemplateParameterList (TemplateParameterList *Invented)
Sets the template parameter list generated from the explicit template parameters along with any invented template parameters from placeholder-typed parameters.
TemplateParameterList * getInventedTemplateParameterList () const
The template parameter list generated from the explicit template parameters along with any invented template parameters from placeholder-typed parameters, if there were any such parameters.
void takeAttributes (ParsedAttributes &attrs)
takeAttributes - Takes attributes from the given parsed-attributes set and add them to this declarator.
const ParsedAttributes & getAttributes () const
ParsedAttributes & getAttributes ()
const ParsedAttributesView & getDeclarationAttributes () const
bool hasAttributes () const
hasAttributes - do we contain any attributes?
void setAsmLabel (Expr *E)
Expr * getAsmLabel () const
void setExtension (bool Val=true)
bool getExtension () const
void setObjCIvar (bool Val=true)
bool isObjCIvar () const
void setObjCWeakProperty (bool Val=true)
bool isObjCWeakProperty () const
void setInvalidType (bool Val=true)
bool isInvalidType () const
void setGroupingParens (bool flag)
bool hasGroupingParens () const
bool isFirstDeclarator () const
SourceLocation getCommaLoc () const
void setCommaLoc (SourceLocation CL)
bool hasEllipsis () const
SourceLocation getEllipsisLoc () const
void setEllipsisLoc (SourceLocation EL)
bool hasPackIndexing () const
Expr * getPackIndexingExpr () const
void setPackIndexingExpr (Expr *PI)
void setFunctionDefinitionKind (FunctionDefinitionKind Val)
bool isFunctionDefinition () const
FunctionDefinitionKind getFunctionDefinitionKind () const
void setHasInitializer (bool Val=true)
bool hasInitializer () const
bool isFirstDeclarationOfMember ()
Returns true if this declares a real member and not a friend.
bool isStaticMember ()
Returns true if this declares a static member.
bool isExplicitObjectMemberFunction ()
bool isCtorOrDtor ()
Returns true if this declares a constructor or a destructor.
void setRedeclaration (bool Val)
bool isRedeclaration () const
Friends
struct DeclaratorChunk
Detailed Description
Information about one declarator, including the parsed type information and the identifier.
When the declarator is fully formed, this is turned into the appropriate Decl object.
Declarators come in two types: normal declarators and abstract declarators. Abstract declarators are used when parsing types, and don't have an identifier. Normal declarators do have ID's.
Instances of this class should be a transient object that lives on the stack, not objects that are allocated in large quantities on the heap.
Definition at line 1898 of file DeclSpec.h.
Member Typedef Documentation
type_object_iterator
typedef SmallVectorImpl<DeclaratorChunk>::const_iterator clang::Declarator::type_object_iterator
Definition at line 2405 of file DeclSpec.h.
type_object_range
typedef llvm::iterator_range<type_object_iterator> clang::Declarator::type_object_range
Definition at line 2406 of file DeclSpec.h.
Constructor & Destructor Documentation
Declarator()
clang::Declarator::Declarator (const DeclSpec & DS, const ParsedAttributesView & DeclarationAttrs, DeclaratorContext C) inline
DS and DeclarationAttrs must outlive the Declarator.
In particular, take care not to pass temporary objects for these parameters.
DeclarationAttrs contains [[]] attributes from the attribute-specifier-seq at the beginning of a declaration, which appertain to the declared entity itself. Attributes with other syntax (e.g. GNU) should not be placed in this attribute list; if they occur at the beginning of a declaration, they apply to the DeclSpec and should be attached to that instead.
Here is an example of an attribute associated with a declaration:
[[deprecated]] int x, y;
This attribute appertains to all of the entities declared in the declaration, i.e. x and y in this case.
Definition at line 2020 of file DeclSpec.h.
~Declarator()
clang::Declarator::~Declarator () inline
Definition at line 2040 of file DeclSpec.h.
References clear().
Member Function Documentation
AddInnermostTypeInfo()
void clang::Declarator::AddInnermostTypeInfo (const DeclaratorChunk & TI) inline
Add a new innermost chunk to this declarator.
Definition at line 2387 of file DeclSpec.h.
Referenced by maybeSynthesizeBlockSignature().
AddTypeInfo() [1/3]
void clang::Declarator::AddTypeInfo (const DeclaratorChunk & TI, AttributePool & OtherPool, SourceLocation EndLoc) inline
AddTypeInfo - Add a chunk to this declarator.
Also extend the range to EndLoc, which should be the last token of the chunk. This overload is for copying a 'chunk' from another declarator, so it takes the pool that the other Declarator owns so that it can 'take' the attributes from it.
Definition at line 2365 of file DeclSpec.h.
References getAttributePool(), clang::SourceLocation::isInvalid(), SetRangeEnd(), and clang::AttributePool::takeFrom().
AddTypeInfo() [2/3]
void clang::Declarator::AddTypeInfo (const DeclaratorChunk & TI, ParsedAttributes && attrs, SourceLocation EndLoc) inline
AddTypeInfo - Add a chunk to this declarator.
Also extend the range to EndLoc, which should be the last token of the chunk. This function takes attrs by R-Value reference because it takes ownership of those attributes from the parameter.
Definition at line 2351 of file DeclSpec.h.
References getAttributePool(), clang::SourceLocation::isInvalid(), SetRangeEnd(), and clang::AttributePool::takeAllFrom().
AddTypeInfo() [3/3]
void clang::Declarator::AddTypeInfo (const DeclaratorChunk & TI, SourceLocation EndLoc) inline
AddTypeInfo - Add a chunk to this declarator.
Also extend the range to EndLoc, which should be the last token of the chunk.
Definition at line 2376 of file DeclSpec.h.
References clang::DeclaratorChunk::AttrList, clang::ParsedAttributesView::empty(), clang::SourceLocation::isInvalid(), and SetRangeEnd().
clear()
void clang::Declarator::clear () inline
Reset the contents of this Declarator.
Definition at line 2108 of file DeclSpec.h.
References clang::CXXScopeSpec::clear().
Referenced by clang::ParsingDeclarator::clear(), and ~Declarator().
DropFirstTypeObject()
void clang::Declarator::DropFirstTypeObject () inline
Definition at line 2413 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew().
ExtendWithDeclSpec()
void clang::Declarator::ExtendWithDeclSpec (const DeclSpec & DS) inline
ExtendWithDeclSpec - Extend the declarator source range to include the given declspec, unless its location is invalid.
Adopts the range start if the current range start is invalid.
Definition at line 2099 of file DeclSpec.h.
References clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::DeclSpec::getSourceRange(), and clang::SourceLocation::isInvalid().
getAsmLabel()
Expr* clang::Declarator::getAsmLabel () const inline
Definition at line 2700 of file DeclSpec.h.
getAttributePool()
AttributePool& clang::Declarator::getAttributePool () const inline
Definition at line 2054 of file DeclSpec.h.
References clang::ParsedAttributes::getPool().
Referenced by addContextSensitiveTypeNullability(), AddTypeInfo(), and takeDeclAttributes().
getAttributes() [1/2]
ParsedAttributes& clang::Declarator::getAttributes () inline
Definition at line 2682 of file DeclSpec.h.
getAttributes() [2/2]
const ParsedAttributes& clang::Declarator::getAttributes () const inline
Definition at line 2681 of file DeclSpec.h.
Referenced by distributeFunctionTypeAttrFromDeclarator(), distributeObjCPointerTypeAttrFromDeclarator(), GetDeclSpecTypeForDeclarator(), hasAttributes(), and takeDeclAttributes().
getBeginLoc()
SourceLocation clang::Declarator::getBeginLoc () const inline
Definition at line 2081 of file DeclSpec.h.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnStartFunctionDeclarationDeclarator(), clang::Sema::isDeclaratorFunctionLike(), clang::Sema::isLibstdcxxEagerExceptionSpecHack(), and maybeSynthesizeBlockSignature().
getCommaLoc()
SourceLocation clang::Declarator::getCommaLoc () const inline
Definition at line 2720 of file DeclSpec.h.
getContext()
DeclaratorContext clang::Declarator::getContext () const inline
Definition at line 2070 of file DeclSpec.h.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnTypeName(), GetDeclSpecTypeForDeclarator(), isFirstDeclarationOfMember(), isOmittedBlockReturnType(), and isStaticMember().
getCXXScopeSpec() [1/2]
CXXScopeSpec& clang::Declarator::getCXXScopeSpec () inline
Definition at line 2061 of file DeclSpec.h.
getCXXScopeSpec() [2/2]
const CXXScopeSpec& clang::Declarator::getCXXScopeSpec () const inline
getCXXScopeSpec - Return the C++ scope specifier (global scope or nested-name-specifier) that is part of the declarator-id.
Definition at line 2060 of file DeclSpec.h.
Referenced by clang::Sema::ActOnStartFunctionDeclarationDeclarator(), and clang::Sema::isDeclaratorFunctionLike().
getDeclarationAttributes()
const ParsedAttributesView& clang::Declarator::getDeclarationAttributes () const inline
Definition at line 2684 of file DeclSpec.h.
Referenced by hasAttributes(), and takeDeclAttributes().
getDeclSpec()
const DeclSpec& clang::Declarator::getDeclSpec () const inline
getDeclSpec - Return the declaration-specifier that this declarator was declared with.
Definition at line 2045 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::canDelayFunctionBody(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckDestructorDeclarator(), clang::Sema::containsUnexpandedParameterPacks(), clang::ParsingDeclarator::getDeclSpec(), clang::ParsingFieldDeclarator::getDeclSpec(), GetDeclSpecTypeForDeclarator(), getFunctionStorageClass(), hasAttributes(), clang::Sema::isDeclaratorFunctionLike(), isFirstDeclarationOfMember(), isFunctionDeclarationContext(), isOmittedBlockReturnType(), isStaticMember(), mayBeFollowedByCXXDirectInit(), and takeDeclAttributes().
getDecompositionDeclarator()
const DecompositionDeclarator& clang::Declarator::getDecompositionDeclarator () const inline
Definition at line 2066 of file DeclSpec.h.
getEllipsisLoc()
SourceLocation clang::Declarator::getEllipsisLoc () const inline
Definition at line 2724 of file DeclSpec.h.
getEndLoc()
SourceLocation clang::Declarator::getEndLoc () const inline
Definition at line 2082 of file DeclSpec.h.
getExtension()
bool clang::Declarator::getExtension () const inline
Definition at line 2703 of file DeclSpec.h.
getFunctionDefinitionKind()
FunctionDefinitionKind clang::Declarator::getFunctionDefinitionKind () const inline
Definition at line 2739 of file DeclSpec.h.
Referenced by isFunctionDefinition().
getFunctionTypeInfo() [1/2]
DeclaratorChunk::FunctionTypeInfo& clang::Declarator::getFunctionTypeInfo () inline
getFunctionTypeInfo - Retrieves the function type info object (looking through parentheses).
Definition at line 2485 of file DeclSpec.h.
References isFunctionDeclarator().
Referenced by clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), getFunctionTypeInfo(), isExplicitObjectMemberFunction(), and maybeSynthesizeBlockSignature().
getFunctionTypeInfo() [2/2]
const DeclaratorChunk::FunctionTypeInfo& clang::Declarator::getFunctionTypeInfo () const inline
getFunctionTypeInfo - Retrieves the function type info object (looking through parentheses).
Definition at line 2494 of file DeclSpec.h.
References getFunctionTypeInfo().
getIdentifier()
const IdentifierInfo* clang::Declarator::getIdentifier () const inline
Definition at line 2328 of file DeclSpec.h.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnTypeName(), clang::Sema::isDeclaratorFunctionLike(), and clang::Sema::isLibstdcxxEagerExceptionSpecHack().
getIdentifierLoc()
SourceLocation clang::Declarator::getIdentifierLoc () const inline
Definition at line 2334 of file DeclSpec.h.
Referenced by clang::Sema::ActOnStartFunctionDeclarationDeclarator(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), and clang::Sema::CheckDestructorDeclarator().
getInnermostNonParenChunk()
const DeclaratorChunk* clang::Declarator::getInnermostNonParenChunk () const inline
Return the innermost (closest to the declarator) chunk of this declarator that is not a parens chunk, or null if there are no non-parens chunks.
Definition at line 2422 of file DeclSpec.h.
Referenced by isArrayOfUnknownBound().
getInventedTemplateParameterList()
TemplateParameterList* clang::Declarator::getInventedTemplateParameterList () const inline
The template parameter list generated from the explicit template parameters along with any invented template parameters from placeholder-typed parameters, if there were any such parameters.
Definition at line 2661 of file DeclSpec.h.
getMutableDeclSpec()
DeclSpec& clang::Declarator::getMutableDeclSpec () inline
getMutableDeclSpec - Return a non-const version of the DeclSpec.
This should be used with extreme care: declspecs can often be shared between multiple declarators, so mutating the DeclSpec affects all of the Declarators. This should only be done when the declspec is known to not be shared or when in error recovery etc.
Definition at line 2052 of file DeclSpec.h.
Referenced by addContextSensitiveTypeNullability(), clang::Sema::CheckDeductionGuideDeclarator(), distributeObjCPointerTypeAttrFromDeclarator(), GetDeclSpecTypeForDeclarator(), getFunctionStorageClass(), and takeDeclAttributes().
getName()
UnqualifiedId& clang::Declarator::getName () inline
Retrieve the name specified by this declarator.
Definition at line 2064 of file DeclSpec.h.
Referenced by clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckDestructorDeclarator(), GetDeclSpecTypeForDeclarator(), getMissingDeclaratorIdLoc(), clang::Sema::GetNameForDeclarator(), isCtorOrDtor(), and isStaticMember().
getNumTypeObjects()
unsigned clang::Declarator::getNumTypeObjects () const inline
Return the number of types applied to this declarator.
Definition at line 2392 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::ActOnStartOfLambdaDefinition(), addContextSensitiveTypeNullability(), clang::Sema::canDelayFunctionBody(), clang::Sema::CheckExtraCXXDefaultArguments(), clang::Sema::containsUnexpandedParameterPacks(), distributeFunctionTypeAttrToInnermost(), distributeObjCPointerTypeAttrFromDeclarator(), GetDeclSpecTypeForDeclarator(), handleObjCOwnershipTypeAttr(), hasAttributes(), isFunctionDeclaratorAFunctionDeclaration(), isOmittedBlockReturnType(), isPipeDeclarator(), maybeMovePastReturnType(), maybeSynthesizeBlockSignature(), and takeDeclAttributes().
getOutermostNonParenChunk()
const DeclaratorChunk* clang::Declarator::getOutermostNonParenChunk () const inline
Return the outermost (furthest from the declarator) chunk of this declarator that is not a parens chunk, or null if there are no non-parens chunks.
Definition at line 2433 of file DeclSpec.h.
getPackIndexingExpr()
Expr* clang::Declarator::getPackIndexingExpr () const inline
Definition at line 2728 of file DeclSpec.h.
getSourceRange()
SourceRange clang::Declarator::getSourceRange () const inline
Get the source range that spans this declarator.
Definition at line 2080 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), and clang::Sema::CheckDeductionGuideDeclarator().
getTemplateParameterLists()
ArrayRef<TemplateParameterList *> clang::Declarator::getTemplateParameterLists () const inline
The template parameter lists that preceded the declarator.
Definition at line 2647 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFinishFunctionDeclarationDeclarator(), and clang::Sema::ActOnStartFunctionDeclarationDeclarator().
getTrailingRequiresClause()
Expr* clang::Declarator::getTrailingRequiresClause () inline
Sets a trailing requires clause for this declarator.
Definition at line 2631 of file DeclSpec.h.
Referenced by clang::Sema::containsUnexpandedParameterPacks().
getTrailingReturnType()
ParsedType clang::Declarator::getTrailingReturnType () const inline
Get the trailing return type appearing (at any level) within this declarator.
Definition at line 2615 of file DeclSpec.h.
References clang::DeclaratorChunk::Function, and type_objects().
Referenced by GetDeclSpecTypeForDeclarator().
getTypeObject() [1/2]
DeclaratorChunk& clang::Declarator::getTypeObject (unsigned i) inline
Definition at line 2400 of file DeclSpec.h.
getTypeObject() [2/2]
const DeclaratorChunk& clang::Declarator::getTypeObject (unsigned i) const inline
Return the specified TypeInfo from this declarator.
TypeInfo #0 is closest to the identifier.
Definition at line 2396 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), addContextSensitiveTypeNullability(), clang::Sema::canDelayFunctionBody(), clang::Sema::CheckExtraCXXDefaultArguments(), clang::Sema::containsUnexpandedParameterPacks(), distributeFunctionTypeAttr(), distributeFunctionTypeAttrToInnermost(), distributeNullabilityTypeAttr(), distributeObjCPointerTypeAttr(), distributeObjCPointerTypeAttrFromDeclarator(), hasAttributes(), hasOuterPointerLikeChunk(), isFunctionDeclaratorAFunctionDeclaration(), isOmittedBlockReturnType(), isPipeDeclarator(), maybeMovePastReturnType(), and takeDeclAttributes().
hasAttributes()
bool clang::Declarator::hasAttributes () const inline
hasAttributes - do we contain any attributes?
Definition at line 2689 of file DeclSpec.h.
References getAttributes(), getDeclarationAttributes(), getDeclSpec(), getNumTypeObjects(), and getTypeObject().
hasEllipsis()
bool clang::Declarator::hasEllipsis () const inline
Definition at line 2723 of file DeclSpec.h.
References clang::SourceLocation::isValid().
hasGroupingParens()
bool clang::Declarator::hasGroupingParens () const inline
Definition at line 2717 of file DeclSpec.h.
Referenced by mayBeFollowedByCXXDirectInit().
hasInitializer()
bool clang::Declarator::hasInitializer () const inline
Definition at line 2744 of file DeclSpec.h.
hasName()
bool clang::Declarator::hasName () const inline
hasName - Whether this declarator has a name, which might be an identifier (accessible via getIdentifier()) or some kind of special C++ name (constructor, destructor, etc.), or a structured binding (which is not exactly a name, but occupies the same position).
Definition at line 2318 of file DeclSpec.h.
Referenced by setDecompositionBindings().
hasPackIndexing()
bool clang::Declarator::hasPackIndexing () const inline
Definition at line 2727 of file DeclSpec.h.
hasTrailingRequiresClause()
bool clang::Declarator::hasTrailingRequiresClause () const inline
Determine whether a trailing requires clause was written in this declarator.
Definition at line 2637 of file DeclSpec.h.
hasTrailingReturnType()
bool clang::Declarator::hasTrailingReturnType () const inline
Determine whether a trailing return type was written (at any level) within this declarator.
Definition at line 2606 of file DeclSpec.h.
References clang::DeclaratorChunk::Function, and type_objects().
Referenced by GetDeclSpecTypeForDeclarator().
isArrayOfUnknownBound()
bool clang::Declarator::isArrayOfUnknownBound () const inline
isArrayOfUnknownBound - This method returns true if the declarator is a declarator for an array of unknown bound (looking through parentheses).
Definition at line 2444 of file DeclSpec.h.
References clang::DeclaratorChunk::Arr, clang::DeclaratorChunk::Array, getInnermostNonParenChunk(), clang::DeclaratorChunk::Kind, and clang::DeclaratorChunk::ArrayTypeInfo::NumElts.
isCtorOrDtor()
bool Declarator::isCtorOrDtor ()
Returns true if this declares a constructor or a destructor.
Definition at line 436 of file DeclSpec.cpp.
References clang::UnqualifiedId::getKind(), getKind(), getName(), clang::IK_ConstructorName, and clang::IK_DestructorName.
isDeclarationOfFunction()
bool Declarator::isDeclarationOfFunction () const
Determine whether the declaration that will be produced from this declaration will be a function.
A declaration can declare a function even if the declarator itself isn't a function declarator, if the type specifier refers to a function type. This routine checks for both cases.
Definition at line 325 of file DeclSpec.cpp.
References clang::DeclaratorChunk::Array, clang::DeclaratorChunk::BlockPointer, clang::DeclaratorChunk::Function, clang::OpaquePtr< PtrTy >::get(), clang::DeclSpec::getRepAsExpr(), clang::DeclSpec::getRepAsType(), clang::DeclSpec::getTypeSpecType(), clang::Type::isFunctionType(), clang::QualType::isNull(), clang::DeclaratorChunk::MemberPointer, clang::DeclaratorChunk::Paren, clang::DeclaratorChunk::Pipe, clang::DeclaratorChunk::Pointer, clang::DeclaratorChunk::Reference, clang::TST_Accum, clang::TST_atomic, clang::TST_auto, clang::TST_auto_type, clang::TST_BFloat16, clang::TST_bitint, clang::TST_bool, clang::TST_char, clang::TST_char16, clang::TST_char32, clang::TST_char8, clang::TST_class, clang::TST_decimal128, clang::TST_decimal32, clang::TST_decimal64, clang::TST_decltype, clang::TST_decltype_auto, clang::TST_double, clang::TST_enum, clang::TST_error, clang::TST_float, clang::TST_float128, clang::TST_Float16, clang::TST_Fract, clang::TST_half, clang::TST_ibm128, clang::TST_int, clang::TST_int128, clang::TST_interface, clang::TST_struct, clang::TST_typename, clang::TST_typename_pack_indexing, clang::TST_typeof_unqualExpr, clang::TST_typeof_unqualType, clang::TST_typeofExpr, clang::TST_typeofType, clang::TST_union, clang::TST_unknown_anytype, clang::TST_unspecified, clang::TST_void, and clang::TST_wchar.
isDecompositionDeclarator()
bool clang::Declarator::isDecompositionDeclarator () const inline
Return whether this declarator is a decomposition declarator.
Definition at line 2324 of file DeclSpec.h.
References clang::DecompositionDeclarator::isSet().
isExplicitObjectMemberFunction()
bool Declarator::isExplicitObjectMemberFunction ()
Definition at line 424 of file DeclSpec.cpp.
References getFunctionTypeInfo(), isFunctionDeclarator(), clang::DeclaratorChunk::FunctionTypeInfo::NumParams, P, clang::DeclaratorChunk::ParamInfo::Param, and clang::DeclaratorChunk::FunctionTypeInfo::Params.
isExpressionContext()
bool clang::Declarator::isExpressionContext () const inline
Determine whether this declaration appears in a context where an expression could appear.
Definition at line 2550 of file DeclSpec.h.
isFirstDeclarationOfMember()
bool clang::Declarator::isFirstDeclarationOfMember () inline
Returns true if this declares a real member and not a friend.
Definition at line 2747 of file DeclSpec.h.
References getContext(), getDeclSpec(), clang::DeclSpec::isFriendSpecified(), and clang::Member.
isFirstDeclarator()
bool clang::Declarator::isFirstDeclarator () const inline
Definition at line 2719 of file DeclSpec.h.
References clang::SourceLocation::isValid().
isFunctionDeclarationContext()
bool clang::Declarator::isFunctionDeclarationContext () const inline
Return true if this declaration appears in a context where a function declarator would be a function declaration.
Definition at line 2508 of file DeclSpec.h.
References getDeclSpec(), and clang::DeclSpec::SCS_typedef.
Referenced by clang::Sema::CheckExtraCXXDefaultArguments(), and isFunctionDeclaratorAFunctionDeclaration().
isFunctionDeclarator() [1/2]
bool clang::Declarator::isFunctionDeclarator () const inline
isFunctionDeclarator - Once this declarator is fully parsed and formed, this method returns true if the identifier is a function declarator (looking through parentheses).
Definition at line 2478 of file DeclSpec.h.
Referenced by getFunctionTypeInfo(), and isExplicitObjectMemberFunction().
isFunctionDeclarator() [2/2]
bool clang::Declarator::isFunctionDeclarator (unsigned & idx) const inline
isFunctionDeclarator - This method returns true if the declarator is a function declarator (looking through parentheses).
If true is returned, then the reference type parameter idx is assigned with the index of the declaration chunk.
Definition at line 2454 of file DeclSpec.h.
References clang::DeclaratorChunk::Array, clang::DeclaratorChunk::BlockPointer, clang::DeclaratorChunk::Function, clang::DeclaratorChunk::MemberPointer, clang::DeclaratorChunk::Paren, clang::DeclaratorChunk::Pipe, clang::DeclaratorChunk::Pointer, and clang::DeclaratorChunk::Reference.
Referenced by clang::Sema::ActOnStartOfFunctionDef(), GetDeclSpecTypeForDeclarator(), and maybeSynthesizeBlockSignature().
isFunctionDeclaratorAFunctionDeclaration()
bool clang::Declarator::isFunctionDeclaratorAFunctionDeclaration () const inline
Return true if a function declarator at this position would be a function declaration.
Definition at line 2593 of file DeclSpec.h.
References getNumTypeObjects(), getTypeObject(), isFunctionDeclarationContext(), and clang::DeclaratorChunk::Paren.
isFunctionDefinition()
bool clang::Declarator::isFunctionDefinition () const inline
Definition at line 2735 of file DeclSpec.h.
References clang::Declaration, and getFunctionDefinitionKind().
Referenced by clang::Sema::CheckDeductionGuideDeclarator().
isInvalidType()
bool clang::Declarator::isInvalidType () const inline
Definition at line 2712 of file DeclSpec.h.
References clang::DeclSpec::getTypeSpecType(), and clang::DeclSpec::TST_error.
Referenced by clang::Sema::ActOnBuiltinBitCastExpr(), clang::Sema::ActOnCXXNamedCast(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnTypeName(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckDestructorDeclarator(), and GetDeclSpecTypeForDeclarator().
isObjCIvar()
bool clang::Declarator::isObjCIvar () const inline
Definition at line 2706 of file DeclSpec.h.
isObjCWeakProperty()
bool clang::Declarator::isObjCWeakProperty () const inline
Definition at line 2709 of file DeclSpec.h.
isPastIdentifier()
bool clang::Declarator::isPastIdentifier () const inline
isPastIdentifier - Return true if we have parsed beyond the point where the name would appear.
(This may happen even if we haven't actually parsed a name, perhaps because this context doesn't require one.)
Definition at line 2312 of file DeclSpec.h.
isPrototypeContext()
bool clang::Declarator::isPrototypeContext () const inline
Definition at line 2072 of file DeclSpec.h.
Referenced by clang::Sema::GetTypeForDeclarator().
isRedeclaration()
bool clang::Declarator::isRedeclaration () const inline
Definition at line 2763 of file DeclSpec.h.
isStaticMember()
bool Declarator::isStaticMember ()
Returns true if this declares a static member.
This cannot be called on a declarator outside of a MemberContext because we won't know until redeclaration time if the decl is static.
Definition at line 416 of file DeclSpec.cpp.
References getContext(), getDeclSpec(), clang::UnqualifiedId::getKind(), getName(), clang::DeclSpec::getStorageClassSpec(), clang::IK_OperatorFunctionId, clang::CXXMethodDecl::isStaticOverloadedOperator(), clang::Member, and clang::DeclSpec::SCS_static.
mayBeFollowedByCXXDirectInit()
bool clang::Declarator::mayBeFollowedByCXXDirectInit () const inline
mayBeFollowedByCXXDirectInit - Return true if the declarator can be followed by a C++ direct initializer, e.g.
"int x(1);".
Definition at line 2254 of file DeclSpec.h.
References getDeclSpec(), hasGroupingParens(), clang::DeclSpec::SCS_extern, and clang::DeclSpec::SCS_typedef.
mayHaveDecompositionDeclarator()
bool clang::Declarator::mayHaveDecompositionDeclarator () const inline
Return true if the context permits a C++17 decomposition declarator.
Definition at line 2209 of file DeclSpec.h.
mayHaveIdentifier()
bool clang::Declarator::mayHaveIdentifier () const inline
mayHaveIdentifier - Return true if the identifier is either optional or required.
This is true for normal declarators and prototypes, but not typenames.
Definition at line 2171 of file DeclSpec.h.
mayOmitIdentifier()
bool clang::Declarator::mayOmitIdentifier () const inline
mayOmitIdentifier - Return true if the identifier is either optional or not allowed.
This is true for typenames, prototypes, and template parameter lists.
Definition at line 2131 of file DeclSpec.h.
setAsmLabel()
void clang::Declarator::setAsmLabel (Expr * E) inline
Definition at line 2699 of file DeclSpec.h.
setCommaLoc()
void clang::Declarator::setCommaLoc (SourceLocation CL) inline
Definition at line 2721 of file DeclSpec.h.
setDecompositionBindings()
void Declarator::setDecompositionBindings (SourceLocation LSquareLoc, ArrayRef< DecompositionDeclarator::Binding > Bindings, SourceLocation RSquareLoc)
Set the decomposition bindings for this declarator.
Definition at line 294 of file DeclSpec.cpp.
References clang::UnqualifiedId::EndLocation, hasName(), InlineBindings, clang::SourceRange::setEnd(), and SetIdentifier().
setEllipsisLoc()
void clang::Declarator::setEllipsisLoc (SourceLocation EL) inline
Definition at line 2725 of file DeclSpec.h.
setExtension()
void clang::Declarator::setExtension (bool Val = true) inline
Definition at line 2702 of file DeclSpec.h.
setFunctionDefinitionKind()
void clang::Declarator::setFunctionDefinitionKind (FunctionDefinitionKind Val) inline
Definition at line 2731 of file DeclSpec.h.
setGroupingParens()
void clang::Declarator::setGroupingParens (bool flag) inline
Definition at line 2716 of file DeclSpec.h.
setHasInitializer()
void clang::Declarator::setHasInitializer (bool Val = true) inline
Definition at line 2743 of file DeclSpec.h.
SetIdentifier()
void clang::Declarator::SetIdentifier (const IdentifierInfo * Id, SourceLocation IdLoc) inline
Set the name of this declarator to be the given identifier.
Definition at line 2337 of file DeclSpec.h.
Referenced by setDecompositionBindings().
setInvalidType()
void clang::Declarator::setInvalidType (bool Val = true) inline
Definition at line 2711 of file DeclSpec.h.
Referenced by clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDestructorDeclarator(), GetDeclSpecTypeForDeclarator(), and getFunctionStorageClass().
setInventedTemplateParameterList()
void clang::Declarator::setInventedTemplateParameterList (TemplateParameterList * Invented) inline
Sets the template parameter list generated from the explicit template parameters along with any invented template parameters from placeholder-typed parameters.
Definition at line 2654 of file DeclSpec.h.
Referenced by clang::Sema::ActOnFinishFunctionDeclarationDeclarator().
setObjCIvar()
void clang::Declarator::setObjCIvar (bool Val = true) inline
Definition at line 2705 of file DeclSpec.h.
setObjCWeakProperty()
void clang::Declarator::setObjCWeakProperty (bool Val = true) inline
Definition at line 2708 of file DeclSpec.h.
setPackIndexingExpr()
void clang::Declarator::setPackIndexingExpr (Expr * PI) inline
Definition at line 2729 of file DeclSpec.h.
SetRangeBegin()
void clang::Declarator::SetRangeBegin (SourceLocation Loc) inline
SetRangeBegin - Set the start of the source range to Loc, unless it's invalid.
Definition at line 2087 of file DeclSpec.h.
References clang::SourceLocation::isInvalid().
SetRangeEnd()
void clang::Declarator::SetRangeEnd (SourceLocation Loc) inline
SetRangeEnd - Set the end of the source range to Loc, unless it's invalid.
Definition at line 2092 of file DeclSpec.h.
References clang::SourceLocation::isInvalid().
Referenced by AddTypeInfo(), setTrailingRequiresClause(), and takeAttributes().
setRedeclaration()
void clang::Declarator::setRedeclaration (bool Val) inline
Definition at line 2762 of file DeclSpec.h.
SetSourceRange()
void clang::Declarator::SetSourceRange (SourceRange R) inline
Definition at line 2084 of file DeclSpec.h.
setTemplateParameterLists()
void clang::Declarator::setTemplateParameterLists (ArrayRef< TemplateParameterList * > TPLs) inline
Sets the template parameter lists that preceded the declarator.
Definition at line 2642 of file DeclSpec.h.
setTrailingRequiresClause()
void clang::Declarator::setTrailingRequiresClause (Expr * TRC) inline
Sets a trailing requires clause for this declarator.
Definition at line 2624 of file DeclSpec.h.
References clang::Stmt::getEndLoc(), and SetRangeEnd().
takeAttributes()
void clang::Declarator::takeAttributes (ParsedAttributes & attrs) inline
takeAttributes - Takes attributes from the given parsed-attributes set and add them to this declarator.
These examples both add 3 attributes to "var": short int var attribute((aligned(16),common,deprecated)); short int x, attribute((aligned(16)) var attribute((common,deprecated));
Also extends the range of the declarator.
Definition at line 2674 of file DeclSpec.h.
References clang::SourceRange::getEnd(), clang::SourceLocation::isValid(), clang::ParsedAttributesView::Range, SetRangeEnd(), and clang::ParsedAttributes::takeAllFrom().
type_objects()
type_object_range clang::Declarator::type_objects () const inline
Returns the range of type objects, from the identifier outwards.
Definition at line 2409 of file DeclSpec.h.
Referenced by clang::Sema::CheckConversionDeclarator(), clang::Sema::CheckDeductionGuideDeclarator(), getTrailingReturnType(), and hasTrailingReturnType().
Friends And Related Function Documentation
DeclaratorChunk
friend struct DeclaratorChunk friend
Definition at line 2001 of file DeclSpec.h.
Member Data Documentation
InlineBindings
DecompositionDeclarator::Binding clang::Declarator::InlineBindings[16]
Definition at line 1986 of file DeclSpec.h.
Referenced by setDecompositionBindings().
InlineParams
DeclaratorChunk::ParamInfo clang::Declarator::InlineParams[16]
InlineParams - This is a local array used for the first function decl chunk to avoid going to the heap for the common case when we have one function chunk in the declarator.
Definition at line 1985 of file DeclSpec.h.
Referenced by clang::DeclaratorChunk::getFunction().
The documentation for this class was generated from the following files:
include/clang/Sema/DeclSpec.h
lib/Sema/DeclSpec.cpp