clang: clang::ento::retaincountchecker::RefLeakReportVisitor Class Reference
clang::ento::retaincountchecker::RefLeakReportVisitor Class Reference
Public Member Functions
RefLeakReportVisitor (SymbolRef Sym, const MemRegion *LastBinding)
PathDiagnosticPieceRef getEndPath (BugReporterContext &BRC, const ExplodedNode *N, PathSensitiveBugReport &BR) override
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
Public Member Functions inherited from clang::ento::retaincountchecker::RefCountReportVisitor
RefCountReportVisitor (SymbolRef sym)
void Profile (llvm::FoldingSetNodeID &ID) const override
PathDiagnosticPieceRef VisitNode (const ExplodedNode *N, BugReporterContext &BRC, PathSensitiveBugReport &BR) override
Return a diagnostic piece which should be associated with the given node.
Public Member Functions inherited from clang::ento::BugReporterVisitor
BugReporterVisitor ()=default
BugReporterVisitor (const BugReporterVisitor &)=default
BugReporterVisitor (BugReporterVisitor &&)
BugReporterVisitor & operator= (const BugReporterVisitor &)=delete
BugReporterVisitor & operator= (BugReporterVisitor &&)=delete
virtual ~BugReporterVisitor ()
virtual void finalizeVisitor (BugReporterContext &BRC, const ExplodedNode *EndPathNode, PathSensitiveBugReport &BR)
Last function called on the visitor, no further calls to VisitNode would follow.
Additional Inherited Members
Static Public Member Functions inherited from clang::ento::BugReporterVisitor
static PathDiagnosticPieceRef getDefaultEndPath (const BugReporterContext &BRC, const ExplodedNode *N, const PathSensitiveBugReport &BR)
Generates the default final diagnostic piece.
Protected Attributes inherited from clang::ento::retaincountchecker::RefCountReportVisitor
SymbolRef Sym
Detailed Description
Definition at line 334 of file RetainCountDiagnostics.cpp.
Constructor & Destructor Documentation
RefLeakReportVisitor()
clang::ento::retaincountchecker::RefLeakReportVisitor::RefLeakReportVisitor (SymbolRef Sym, const MemRegion * LastBinding) inline
Definition at line 336 of file RetainCountDiagnostics.cpp.
Member Function Documentation
getEndPath()
PathDiagnosticPieceRef RefLeakReportVisitor::getEndPath (BugReporterContext & BRC, const ExplodedNode * N, PathSensitiveBugReport & BR) override virtual
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
NOTE that this function can be implemented on at most one used visitor, and otherwise it crahes at runtime.
Reimplemented from clang::ento::retaincountchecker::RefCountReportVisitor.
Definition at line 761 of file RetainCountDiagnostics.cpp.
References clang::ento::CF, describeRegion(), clang::ento::retaincountchecker::RefVal::ErrorLeakReturned, clang::ento::BugReporterContext::getASTContext(), clang::ento::ExplodedNode::getCodeDecl(), clang::ento::retaincountchecker::RefVal::getCount(), clang::ento::retaincountchecker::RefVal::getKind(), clang::ASTContext::getLangOpts(), clang::NamedDecl::getNameAsString(), clang::ento::retaincountchecker::RefVal::getObjKind(), getPrettyTypeName(), clang::ento::retaincountchecker::getRefBinding(), clang::ento::ExplodedNode::getState(), clang::ento::SymExpr::getType(), clang::Decl::hasAttr(), clang::ento::PathSensitiveBugReport::markInteresting(), clang::ento::ObjC, clang::ento::OS, and clang::ento::retaincountchecker::RefCountReportVisitor::Sym.
The documentation for this class was generated from the following file:
lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountDiagnostics.cpp