clang: clang::threadSafety::til::Branch Class Reference
clang::threadSafety::til::Branch Class Reference
A conditional branch to two other blocks.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Branch (SExpr *C, BasicBlock *T, BasicBlock *E)
Branch (const Branch &Br, SExpr *C, BasicBlock *T, BasicBlock *E)
const SExpr * condition () const
SExpr * condition ()
const BasicBlock * thenBlock () const
BasicBlock * thenBlock ()
const BasicBlock * elseBlock () const
BasicBlock * elseBlock ()
ArrayRef< BasicBlock * > successors ()
Return the list of basic blocks that this terminator can branch to.
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Branch *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::Terminator
ArrayRef< BasicBlock * > successors ()
Return the list of basic blocks that this terminator can branch to.
ArrayRef< BasicBlock * > successors () const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Static Public Member Functions inherited from clang::threadSafety::til::Terminator
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::Terminator
Terminator (TIL_Opcode Op)
Terminator (const SExpr &E)
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const unsigned char Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
A conditional branch to two other blocks.
Note that unlike Goto, Branch does not have an index. The target blocks must be child-blocks, and cannot have Phi nodes.
Definition at line 1407 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Branch() [1/2]
clang::threadSafety::til::Branch::Branch (SExpr * C, BasicBlock * T, BasicBlock * E) inline
Definition at line 1409 of file ThreadSafetyTIL.h.
Branch() [2/2]
clang::threadSafety::til::Branch::Branch (const Branch & Br, SExpr * C, BasicBlock * T, BasicBlock * E) inline
Definition at line 1415 of file ThreadSafetyTIL.h.
Member Function Documentation
classof()
static bool clang::threadSafety::til::Branch::classof (const SExpr * E) inline static
Definition at line 1421 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Branch::compare (const Branch * E, C & Cmp) const inline
Definition at line 1446 of file ThreadSafetyTIL.h.
condition() [1/2]
SExpr* clang::threadSafety::til::Branch::condition () inline
Definition at line 1424 of file ThreadSafetyTIL.h.
condition() [2/2]
const SExpr* clang::threadSafety::til::Branch::condition () const inline
Definition at line 1423 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printBranch().
elseBlock() [1/2]
BasicBlock* clang::threadSafety::til::Branch::elseBlock () inline
Definition at line 1430 of file ThreadSafetyTIL.h.
elseBlock() [2/2]
const BasicBlock* clang::threadSafety::til::Branch::elseBlock () const inline
Definition at line 1429 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printBranch().
successors()
ArrayRef<BasicBlock*> clang::threadSafety::til::Branch::successors () inline
Return the list of basic blocks that this terminator can branch to.
Definition at line 1433 of file ThreadSafetyTIL.h.
thenBlock() [1/2]
BasicBlock* clang::threadSafety::til::Branch::thenBlock () inline
Definition at line 1427 of file ThreadSafetyTIL.h.
thenBlock() [2/2]
const BasicBlock* clang::threadSafety::til::Branch::thenBlock () const inline
Definition at line 1426 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printBranch().
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Branch::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1438 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h