clang: clang::OMPPartialClause Class Reference
clang::OMPPartialClause Class Reference final
Representation of the 'partial' clause of the '#pragma omp unroll' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
SourceLocation getLParenLoc () const
Returns the location of '('.
Expr * getFactor () const
Returns the argument of the clause or nullptr if not set.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPPartialClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, Expr *Factor)
Build an AST node for a 'partial' clause.
static OMPPartialClause * CreateEmpty (const ASTContext &C)
Build an empty 'partial' AST node for deserialization.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
Representation of the 'partial' clause of the '#pragma omp unroll' directive.
#pragma omp unroll partial(4)
for (int i = start; i < end; ++i)
Definition at line 907 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPPartialClause::children () inline
Definition at line 948 of file OpenMPClause.h.
children() [2/2]
const_child_range clang::OMPPartialClause::children () const inline
Definition at line 949 of file OpenMPClause.h.
classof()
static bool clang::OMPPartialClause::classof (const OMPClause * T) inline static
Definition at line 960 of file OpenMPClause.h.
References clang::T.
Create()
OMPPartialClause * OMPPartialClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, Expr * Factor) static
Build an AST node for a 'partial' clause.
Parameters
C Context of the AST.
StartLoc Location of the 'partial' identifier.
LParenLoc Location of '('.
EndLoc Location of ')'.
Factor Clause argument.
Definition at line 987 of file OpenMPClause.cpp.
References clang::OMPClause::setLocEnd(), and clang::OMPClause::setLocStart().
Referenced by clang::SemaOpenMP::ActOnOpenMPPartialClause().
CreateEmpty()
OMPPartialClause * OMPPartialClause::CreateEmpty (const ASTContext & C) static
Build an empty 'partial' AST node for deserialization.
Parameters
C Context of the AST.
Definition at line 1000 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
getFactor()
Expr* clang::OMPPartialClause::getFactor () const inline
Returns the argument of the clause or nullptr if not set.
Definition at line 946 of file OpenMPClause.h.
getLParenLoc()
SourceLocation clang::OMPPartialClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 943 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPPartialClause::used_children () inline
Definition at line 953 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPPartialClause::used_children () const inline
Definition at line 956 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 908 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp