clang: clang::ParsedAttributesView Class Reference
clang::ParsedAttributesView Class Reference
#include "clang/Sema/ParsedAttr.h"
Classes
struct const_iterator
struct iterator
Public Member Functions
bool empty () const
SizeType size () const
ParsedAttr & operator[] (SizeType pos)
const ParsedAttr & operator[] (SizeType pos) const
void addAtEnd (ParsedAttr *newAttr)
void remove (ParsedAttr *ToBeRemoved)
void clearListOnly ()
void addAll (iterator B, iterator E)
void addAll (const_iterator B, const_iterator E)
void addAllAtEnd (iterator B, iterator E)
void addAllAtEnd (const_iterator B, const_iterator E)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
ParsedAttr & front ()
const ParsedAttr & front () const
ParsedAttr & back ()
const ParsedAttr & back () const
bool hasAttribute (ParsedAttr::Kind K) const
Public Attributes
SourceRange Range
Detailed Description
Definition at line 909 of file ParsedAttr.h.
Member Function Documentation
addAll() [1/2]
void clang::ParsedAttributesView::addAll (const_iterator B, const_iterator E) inline
Definition at line 956 of file ParsedAttr.h.
addAll() [2/2]
void clang::ParsedAttributesView::addAll (iterator B, iterator E) inline
Definition at line 952 of file ParsedAttr.h.
Referenced by clang::DeclSpec::addAttributes(), and clang::ParsedAttributes::takeAllFrom().
addAllAtEnd() [1/2]
void clang::ParsedAttributesView::addAllAtEnd (const_iterator B, const_iterator E) inline
Definition at line 964 of file ParsedAttr.h.
addAllAtEnd() [2/2]
void clang::ParsedAttributesView::addAllAtEnd (iterator B, iterator E) inline
Definition at line 960 of file ParsedAttr.h.
addAtEnd()
void clang::ParsedAttributesView::addAtEnd (ParsedAttr * newAttr) inline
Definition at line 920 of file ParsedAttr.h.
Referenced by addContextSensitiveTypeNullability(), clang::ParsedAttributes::addNew(), clang::ParsedAttributes::addNewPropertyAttr(), clang::ParsedAttributes::addNewTypeAttr(), clang::ParsedAttributes::addNewTypeTagForDatatype(), moveAttrFromListToList(), takeDeclAttributes(), and clang::ParsedAttributes::takeOneFrom().
back() [1/2]
ParsedAttr& clang::ParsedAttributesView::back () inline
Definition at line 981 of file ParsedAttr.h.
References empty().
back() [2/2]
const ParsedAttr& clang::ParsedAttributesView::back () const inline
Definition at line 985 of file ParsedAttr.h.
References empty().
begin() [1/2]
iterator clang::ParsedAttributesView::begin () inline
Definition at line 968 of file ParsedAttr.h.
Referenced by clang::DeclSpec::addAttributes(), and clang::ParsedAttributes::takeAllFrom().
begin() [2/2]
const_iterator clang::ParsedAttributesView::begin () const inline
Definition at line 969 of file ParsedAttr.h.
clearListOnly()
void clang::ParsedAttributesView::clearListOnly () inline
Definition at line 931 of file ParsedAttr.h.
Referenced by clang::ParsedAttributes::clear(), and clang::ParsedAttributes::takeAllFrom().
empty()
bool clang::ParsedAttributesView::empty () const inline
Definition at line 915 of file ParsedAttr.h.
Referenced by back(), front(), GetDeclSpecTypeForDeclarator(), clang::DeclSpec::hasAttributes(), and processTypeAttrs().
end() [1/2]
iterator clang::ParsedAttributesView::end () inline
Definition at line 970 of file ParsedAttr.h.
Referenced by clang::DeclSpec::addAttributes(), getMSPropertyAttr(), and clang::ParsedAttributes::takeAllFrom().
end() [2/2]
const_iterator clang::ParsedAttributesView::end () const inline
Definition at line 971 of file ParsedAttr.h.
front() [1/2]
ParsedAttr& clang::ParsedAttributesView::front () inline
Definition at line 973 of file ParsedAttr.h.
References empty().
front() [2/2]
const ParsedAttr& clang::ParsedAttributesView::front () const inline
Definition at line 977 of file ParsedAttr.h.
References empty().
hasAttribute()
bool clang::ParsedAttributesView::hasAttribute (ParsedAttr::Kind K) const inline
Definition at line 990 of file ParsedAttr.h.
References clang::AttributeCommonInfo::getParsedKind().
operator[]() [1/2]
ParsedAttr& clang::ParsedAttributesView::operator[] (SizeType pos) inline
Definition at line 917 of file ParsedAttr.h.
operator[]() [2/2]
const ParsedAttr& clang::ParsedAttributesView::operator[] (SizeType pos) const inline
Definition at line 918 of file ParsedAttr.h.
remove()
void clang::ParsedAttributesView::remove (ParsedAttr * ToBeRemoved) inline
Definition at line 925 of file ParsedAttr.h.
Referenced by distributeFunctionTypeAttrFromDeclarator(), distributeObjCPointerTypeAttrFromDeclarator(), moveAttrFromListToList(), takeDeclAttributes(), and clang::ParsedAttributes::takeOneFrom().
size()
SizeType clang::ParsedAttributesView::size () const inline
Definition at line 916 of file ParsedAttr.h.
Referenced by clang::DeclaratorChunk::getFunction(), and clang::DeclaratorChunk::FunctionTypeInfo::hasMethodTypeQualifiers().
Member Data Documentation
Range
SourceRange clang::ParsedAttributesView::Range
Definition at line 914 of file ParsedAttr.h.
Referenced by clang::Sema::ActOnAttributedStmt(), clang::ParsedAttributes::clear(), and clang::Declarator::takeAttributes().
The documentation for this class was generated from the following file:
include/clang/Sema/ParsedAttr.h