clang: clang::serialization::reader::ASTIdentifierLookupTraitBase Class Reference
clang::serialization::reader::ASTIdentifierLookupTraitBase Class Reference
Base class for the trait describing the on-disk hash table for the identifiers in an AST file.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Serialization/ASTReaderInternals.h"
Public Types
using external_key_type = StringRef
using internal_key_type = StringRef
using hash_value_type = unsigned
using offset_type = unsigned
Static Public Member Functions
static bool EqualKey (const internal_key_type &a, const internal_key_type &b)
static hash_value_type ComputeHash (const internal_key_type &a)
static std::pair< unsigned, unsigned > ReadKeyDataLength (const unsigned char *&d)
static const internal_key_type & GetInternalKey (const external_key_type &x)
static const external_key_type & GetExternalKey (const internal_key_type &x)
static internal_key_type ReadKey (const unsigned char *d, unsigned n)
Detailed Description
Base class for the trait describing the on-disk hash table for the identifiers in an AST file.
This class is not useful by itself; rather, it provides common functionality for accessing the on-disk hash table of identifiers in an AST file. Different subclasses customize that functionality based on what information they are interested in. Those subclasses must provide the data_type type and the ReadData operation, only.
Definition at line 130 of file ASTReaderInternals.h.
Member Typedef Documentation
external_key_type
using clang::serialization::reader::ASTIdentifierLookupTraitBase::external_key_type = StringRef
Definition at line 132 of file ASTReaderInternals.h.
hash_value_type
using clang::serialization::reader::ASTIdentifierLookupTraitBase::hash_value_type = unsigned
Definition at line 134 of file ASTReaderInternals.h.
internal_key_type
using clang::serialization::reader::ASTIdentifierLookupTraitBase::internal_key_type = StringRef
Definition at line 133 of file ASTReaderInternals.h.
offset_type
using clang::serialization::reader::ASTIdentifierLookupTraitBase::offset_type = unsigned
Definition at line 135 of file ASTReaderInternals.h.
Member Function Documentation
ComputeHash()
unsigned ASTIdentifierLookupTraitBase::ComputeHash (const internal_key_type & a) static
Definition at line 973 of file ASTReader.cpp.
EqualKey()
static bool clang::serialization::reader::ASTIdentifierLookupTraitBase::EqualKey (const internal_key_type & a, const internal_key_type & b) inline static
Definition at line 137 of file ASTReaderInternals.h.
References b.
GetExternalKey()
static const external_key_type& clang::serialization::reader::ASTIdentifierLookupTraitBase::GetExternalKey (const internal_key_type & x) inline static
Definition at line 152 of file ASTReaderInternals.h.
GetInternalKey()
static const internal_key_type& clang::serialization::reader::ASTIdentifierLookupTraitBase::GetInternalKey (const external_key_type & x) inline static
Definition at line 148 of file ASTReaderInternals.h.
ReadKey()
ASTIdentifierLookupTraitBase::internal_key_type ASTIdentifierLookupTraitBase::ReadKey (const unsigned char * d, unsigned n) static
Definition at line 983 of file ASTReader.cpp.
Referenced by clang::ASTReader::ReadAST().
ReadKeyDataLength()
std::pair< unsigned, unsigned > ASTIdentifierLookupTraitBase::ReadKeyDataLength (const unsigned char *& d) static
Definition at line 978 of file ASTReader.cpp.
References readULEBKeyDataLength().
Referenced by clang::ASTReader::ReadAST().
The documentation for this class was generated from the following files:
lib/Serialization/ASTReaderInternals.h
lib/Serialization/ASTReader.cpp