clang: PNaClABIInfo Class Reference
PNaClABIInfo Class Reference
Public Member Functions
PNaClABIInfo (CodeGen::CodeGenTypes &CGT)
ABIArgInfo classifyReturnType (QualType RetTy) const
ABIArgInfo classifyArgumentType (QualType RetTy) const
Classify argument of given type Ty.
void computeInfo (CGFunctionInfo &FI) const override
Address EmitVAArg (CodeGenFunction &CGF, Address VAListAddr, QualType Ty) const override
EmitVAArg - Emit the target dependent code to load a value of.
Public Member Functions inherited from clang::CodeGen::ABIInfo
ABIInfo (CodeGen::CodeGenTypes &cgt)
virtual ~ABIInfo ()
virtual bool allowBFloatArgsAndRet () const
CodeGen::CGCXXABI & getCXXABI () const
ASTContext & getContext () const
llvm::LLVMContext & getVMContext () const
const llvm::DataLayout & getDataLayout () const
const TargetInfo & getTarget () const
const CodeGenOptions & getCodeGenOpts () const
llvm::CallingConv::ID getRuntimeCC () const
Return the calling convention to use for system runtime functions.
bool isAndroid () const
bool isOHOSFamily () const
virtual CodeGen::Address EmitMSVAArg (CodeGen::CodeGenFunction &CGF, CodeGen::Address VAListAddr, QualType Ty) const
Emit the target dependent code to load a value of.
virtual bool isHomogeneousAggregateBaseType (QualType Ty) const
virtual bool isHomogeneousAggregateSmallEnough (const Type *Base, uint64_t Members) const
virtual bool isZeroLengthBitfieldPermittedInHomogeneousAggregate () const
bool isHomogeneousAggregate (QualType Ty, const Type *&Base, uint64_t &Members) const
isHomogeneousAggregate - Return true if a type is an ELFv2 homogeneous aggregate.
bool isPromotableIntegerTypeForABI (QualType Ty) const
CodeGen::ABIArgInfo getNaturalAlignIndirect (QualType Ty, bool ByVal=true, bool Realign=false, llvm::Type *Padding=nullptr) const
A convenience method to return an indirect ABIArgInfo with an expected alignment equal to the ABI alignment of the given type.
CodeGen::ABIArgInfo getNaturalAlignIndirectInReg (QualType Ty, bool Realign=false) const
virtual void appendAttributeMangling (TargetAttr *Attr, raw_ostream &Out) const
virtual void appendAttributeMangling (TargetVersionAttr *Attr, raw_ostream &Out) const
virtual void appendAttributeMangling (TargetClonesAttr *Attr, unsigned Index, raw_ostream &Out) const
virtual void appendAttributeMangling (StringRef AttrStr, raw_ostream &Out) const
Additional Inherited Members
Protected Attributes inherited from clang::CodeGen::ABIInfo
CodeGen::CodeGenTypes & CGT
llvm::CallingConv::ID RuntimeCC
Detailed Description
Definition at line 22 of file PNaCl.cpp.
Constructor & Destructor Documentation
PNaClABIInfo()
PNaClABIInfo::PNaClABIInfo (CodeGen::CodeGenTypes & CGT) inline
Definition at line 24 of file PNaCl.cpp.
Member Function Documentation
classifyArgumentType()
ABIArgInfo PNaClABIInfo::classifyArgumentType (QualType RetTy) const
Classify argument of given type Ty.
Definition at line 60 of file PNaCl.cpp.
References clang::Type::getAs(), clang::CodeGen::ABIArgInfo::getDirect(), clang::CodeGen::ABIArgInfo::getExtend(), clang::CodeGen::getRecordArgABI(), clang::CodeGen::isAggregateTypeForABI(), clang::Type::isFloatingType(), and clang::CodeGen::CGCXXABI::RAA_DirectInMemory.
classifyReturnType()
ABIArgInfo PNaClABIInfo::classifyReturnType (QualType RetTy) const
Definition at line 83 of file PNaCl.cpp.
References clang::Type::getAs(), clang::CodeGen::ABIArgInfo::getDirect(), clang::CodeGen::ABIArgInfo::getExtend(), clang::CodeGen::ABIArgInfo::getIgnore(), clang::CodeGen::isAggregateTypeForABI(), and clang::Type::isVoidType().
computeInfo()
void PNaClABIInfo::computeInfo (CGFunctionInfo & FI) const override virtual
Implements clang::CodeGen::ABIInfo.
Definition at line 40 of file PNaCl.cpp.
References clang::CodeGen::CGFunctionInfo::arguments(), clang::CodeGen::swiftcall::classifyArgumentType(), clang::CodeGen::classifyReturnType(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), and clang::CodeGen::CGFunctionInfo::getReturnType().
EmitVAArg()
Address PNaClABIInfo::EmitVAArg (CodeGenFunction & CGF, Address VAListAddr, QualType Ty) const override virtual
EmitVAArg - Emit the target dependent code to load a value of.
Ty from the va_list pointed to by
VAListAddr.
Implements clang::CodeGen::ABIInfo.
Definition at line 48 of file PNaCl.cpp.
References clang::CodeGen::EmitVAArgInstr(), and clang::CodeGen::ABIArgInfo::getDirect().
The documentation for this class was generated from the following file:
lib/CodeGen/Targets/PNaCl.cpp