clang: clang::SemaHLSL Class Reference
clang::SemaHLSL Class Reference
#include "clang/Sema/SemaHLSL.h"
Public Member Functions
SemaHLSL (Sema &S)
Decl * ActOnStartBuffer (Scope *BufferScope, bool CBuffer, SourceLocation KwLoc, IdentifierInfo *Ident, SourceLocation IdentLoc, SourceLocation LBrace)
void ActOnFinishBuffer (Decl *Dcl, SourceLocation RBrace)
HLSLNumThreadsAttr * mergeNumThreadsAttr (Decl *D, const AttributeCommonInfo &AL, int X, int Y, int Z)
HLSLShaderAttr * mergeShaderAttr (Decl *D, const AttributeCommonInfo &AL, llvm::Triple::EnvironmentType ShaderType)
HLSLParamModifierAttr * mergeParamModifierAttr (Decl *D, const AttributeCommonInfo &AL, HLSLParamModifierAttr::Spelling Spelling)
void ActOnTopLevelFunction (FunctionDecl *FD)
void CheckEntryPoint (FunctionDecl *FD)
void CheckSemanticAnnotation (FunctionDecl *EntryPoint, const Decl *Param, const HLSLAnnotationAttr *AnnotationAttr)
void DiagnoseAttrStageMismatch (const Attr *A, llvm::Triple::EnvironmentType Stage, std::initializer_list< llvm::Triple::EnvironmentType > AllowedStages)
void DiagnoseAvailabilityViolations (TranslationUnitDecl *TU)
void handleNumThreadsAttr (Decl *D, const ParsedAttr &AL)
void handleSV_DispatchThreadIDAttr (Decl *D, const ParsedAttr &AL)
void handlePackOffsetAttr (Decl *D, const ParsedAttr &AL)
void handleShaderAttr (Decl *D, const ParsedAttr &AL)
void handleResourceClassAttr (Decl *D, const ParsedAttr &AL)
void handleResourceBindingAttr (Decl *D, const ParsedAttr &AL)
void handleParamModifierAttr (Decl *D, const ParsedAttr &AL)
bool CheckBuiltinFunctionCall (unsigned BuiltinID, CallExpr *TheCall)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 30 of file SemaHLSL.h.
Constructor & Destructor Documentation
SemaHLSL()
SemaHLSL::SemaHLSL (Sema & S)
Definition at line 30 of file SemaHLSL.cpp.
Member Function Documentation
ActOnFinishBuffer()
void SemaHLSL::ActOnFinishBuffer (Decl * Dcl, SourceLocation RBrace)
Definition at line 82 of file SemaHLSL.cpp.
References clang::SemaBase::Diag().
ActOnStartBuffer()
Decl * SemaHLSL::ActOnStartBuffer (Scope * BufferScope, bool CBuffer, SourceLocation KwLoc, IdentifierInfo * Ident, SourceLocation IdentLoc, SourceLocation LBrace)
Definition at line 32 of file SemaHLSL.cpp.
References clang::HLSLBufferDecl::Create(), clang::SemaBase::getASTContext(), clang::Sema::getCurLexicalContext(), clang::Sema::PushDeclContext(), clang::Sema::PushOnScopeChains(), and clang::SemaBase::SemaRef.
ActOnTopLevelFunction()
void SemaHLSL::ActOnTopLevelFunction (FunctionDecl * FD)
Definition at line 181 of file SemaHLSL.cpp.
References clang::Decl::addAttr(), clang::SemaBase::Diag(), Env, clang::SemaBase::getASTContext(), clang::Decl::getAttr(), clang::DeclaratorDecl::getBeginLoc(), clang::NamedDecl::getName(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTargetOpts(), clang::TargetInfo::getTriple(), clang::TargetOptions::HLSLEntry, and clang::Decl::setInvalidDecl().
CheckBuiltinFunctionCall()
bool SemaHLSL::CheckBuiltinFunctionCall (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 1015 of file SemaHLSL.cpp.
References clang::Sema::BuiltinElementwiseTernaryMath(), clang::Sema::BuiltinVectorToScalarMath(), CheckAllArgsHaveFloatRepresentation(), clang::Sema::checkArgCount(), CheckFloatOrHalfRepresentations(), CheckNoDoubleVectors(), CheckUnsignedIntRepresentation(), CheckVectorElementCallArgs(), clang::CallExpr::getArg(), clang::SemaBase::getASTContext(), clang::Expr::getType(), clang::Type::hasFloatingRepresentation(), clang::Sema::PrepareBuiltinElementwiseMathOneArgCall(), clang::SemaBase::SemaRef, and SetElementTypeAsReturnType().
CheckEntryPoint()
void SemaHLSL::CheckEntryPoint (FunctionDecl * FD)
Definition at line 214 of file SemaHLSL.cpp.
References CheckSemanticAnnotation(), clang::SemaBase::Diag(), DiagnoseAttrStageMismatch(), clang::Decl::getAttr(), clang::Decl::getLocation(), clang::Decl::hasAttr(), clang::FunctionDecl::parameters(), and clang::Decl::setInvalidDecl().
CheckSemanticAnnotation()
void SemaHLSL::CheckSemanticAnnotation (FunctionDecl * EntryPoint, const Decl * Param, const HLSLAnnotationAttr * AnnotationAttr)
Definition at line 267 of file SemaHLSL.cpp.
References DiagnoseAttrStageMismatch(), clang::Decl::getAttr(), and clang::Attr::getKind().
Referenced by CheckEntryPoint().
DiagnoseAttrStageMismatch()
void SemaHLSL::DiagnoseAttrStageMismatch (const Attr * A, llvm::Triple::EnvironmentType Stage, std::initializer_list< llvm::Triple::EnvironmentType > AllowedStages)
Definition at line 286 of file SemaHLSL.cpp.
References clang::SemaBase::Diag(), and clang::AttributeCommonInfo::getLoc().
Referenced by CheckEntryPoint(), and CheckSemanticAnnotation().
DiagnoseAvailabilityViolations()
void SemaHLSL::DiagnoseAvailabilityViolations (TranslationUnitDecl * TU)
Definition at line 884 of file SemaHLSL.cpp.
References clang::Sema::getASTContext(), clang::Sema::getLangOpts(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), and clang::SemaBase::SemaRef.
handleNumThreadsAttr()
void SemaHLSL::handleNumThreadsAttr (Decl * D, const ParsedAttr & AL)
Definition at line 300 of file SemaHLSL.cpp.
References clang::Decl::addAttr(), clang::Sema::checkUInt32Argument(), D, clang::SemaBase::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::SemaBase::getASTContext(), clang::Expr::getExprLoc(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), mergeNumThreadsAttr(), clang::SemaBase::SemaRef, and X.
handlePackOffsetAttr()
void SemaHLSL::handlePackOffsetAttr (Decl * D, const ParsedAttr & AL)
Definition at line 371 of file SemaHLSL.cpp.
References clang::Decl::addAttr(), clang::Sema::checkUInt32Argument(), D, clang::SemaBase::Diag(), clang::ParsedAttr::getArgAsExpr(), clang::Type::getAs(), clang::SemaBase::getASTContext(), clang::Decl::getDeclContext(), clang::AttributeCommonInfo::getLoc(), clang::ASTContext::getTypeAlign(), clang::ASTContext::getTypeSize(), clang::Type::isArrayType(), clang::Type::isStructureType(), clang::SemaBase::SemaRef, and clang::T.
handleParamModifierAttr()
void SemaHLSL::handleParamModifierAttr (Decl * D, const ParsedAttr & AL)
Definition at line 533 of file SemaHLSL.cpp.
References clang::Decl::addAttr(), D, clang::ParsedAttr::getSemanticSpelling(), and mergeParamModifierAttr().
handleResourceBindingAttr()
void SemaHLSL::handleResourceBindingAttr (Decl * D, const ParsedAttr & AL)
Definition at line 462 of file SemaHLSL.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), D, clang::SemaBase::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::SemaBase::getASTContext(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::ParsedAttr::isArgIdent(), and Loc.
handleResourceClassAttr()
void SemaHLSL::handleResourceClassAttr (Decl * D, const ParsedAttr & AL)
Definition at line 440 of file SemaHLSL.cpp.
References clang::AANT_ArgumentIdentifier, clang::Decl::addAttr(), D, clang::SemaBase::Diag(), clang::ParsedAttr::getArgAsIdent(), clang::SemaBase::getASTContext(), clang::AttributeCommonInfo::getLoc(), Identifier, clang::ParsedAttr::isArgIdent(), and Loc.
handleShaderAttr()
void SemaHLSL::handleShaderAttr (Decl * D, const ParsedAttr & AL)
Definition at line 420 of file SemaHLSL.cpp.
References clang::Decl::addAttr(), clang::Sema::checkStringLiteralArgumentAttr(), D, clang::SemaBase::Diag(), clang::AttributeCommonInfo::getLoc(), mergeShaderAttr(), and clang::SemaBase::SemaRef.
handleSV_DispatchThreadIDAttr()
void SemaHLSL::handleSV_DispatchThreadIDAttr (Decl * D, const ParsedAttr & AL)
Definition at line 359 of file SemaHLSL.cpp.
References clang::Decl::addAttr(), D, clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::AttributeCommonInfo::getLoc(), and isLegalTypeForHLSLSV_DispatchThreadID().
mergeNumThreadsAttr()
HLSLNumThreadsAttr * SemaHLSL::mergeNumThreadsAttr (Decl * D, const AttributeCommonInfo & AL, int X, int Y, int Z)
Definition at line 133 of file SemaHLSL.cpp.
References D, clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::Decl::getAttr(), clang::AttributeCommonInfo::getLoc(), and X.
Referenced by handleNumThreadsAttr().
mergeParamModifierAttr()
HLSLParamModifierAttr * SemaHLSL::mergeParamModifierAttr (Decl * D, const AttributeCommonInfo & AL, HLSLParamModifierAttr::Spelling Spelling)
Definition at line 161 of file SemaHLSL.cpp.
References D, clang::SemaBase::Diag(), clang::Decl::dropAttr(), clang::SemaBase::getASTContext(), clang::Decl::getAttr(), clang::SourceRange::getEnd(), clang::AttributeCommonInfo::getLoc(), and clang::AttributeCommonInfo::getRange().
Referenced by handleParamModifierAttr().
mergeShaderAttr()
HLSLShaderAttr * SemaHLSL::mergeShaderAttr (Decl * D, const AttributeCommonInfo & AL, llvm::Triple::EnvironmentType ShaderType)
Definition at line 148 of file SemaHLSL.cpp.
References D, clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::Decl::getAttr(), and clang::AttributeCommonInfo::getLoc().
Referenced by handleShaderAttr().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaHLSL.h
lib/Sema/SemaHLSL.cpp