clang: clang::CodeGen::EHScopeStack::iterator Class Reference
clang::CodeGen::EHScopeStack::iterator Class Reference
A non-stable pointer into the scope stack.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCleanup.h"
Public Member Functions
iterator ()
EHScope * get () const
EHScope * operator-> () const
EHScope & operator* () const
iterator & operator++ ()
iterator next ()
iterator operator++ (int)
bool encloses (iterator other) const
bool strictlyEncloses (iterator other) const
bool operator== (iterator other) const
bool operator!= (iterator other) const
Friends
class EHScopeStack
Detailed Description
A non-stable pointer into the scope stack.
Definition at line 500 of file CGCleanup.h.
Constructor & Destructor Documentation
iterator()
clang::CodeGen::EHScopeStack::iterator::iterator () inline
Definition at line 507 of file CGCleanup.h.
Member Function Documentation
encloses()
bool clang::CodeGen::EHScopeStack::iterator::encloses (iterator other) const inline
Definition at line 553 of file CGCleanup.h.
get()
EHScope* clang::CodeGen::EHScopeStack::iterator::get () const inline
Definition at line 509 of file CGCleanup.h.
Referenced by operator*(), operator++(), and operator->().
next()
iterator clang::CodeGen::EHScopeStack::iterator::next () inline
Definition at line 541 of file CGCleanup.h.
operator!=()
bool clang::CodeGen::EHScopeStack::iterator::operator!= (iterator other) const inline
Definition at line 557 of file CGCleanup.h.
operator*()
EHScope& clang::CodeGen::EHScopeStack::iterator::operator* () const inline
Definition at line 514 of file CGCleanup.h.
References get().
operator++() [1/2]
iterator& clang::CodeGen::EHScopeStack::iterator::operator++ () inline
Definition at line 516 of file CGCleanup.h.
References clang::CodeGen::EHScope::Catch, clang::CodeGen::EHScope::Cleanup, clang::CodeGen::EHScope::Filter, get(), getKind(), clang::CodeGen::EHTerminateScope::getSize(), clang::CodeGen::EHFilterScope::getSizeForNumFilters(), clang::CodeGen::EHCatchScope::getSizeForNumHandlers(), clang::CodeGen::EHScopeStack::ScopeStackAlignment, and clang::CodeGen::EHScope::Terminate.
Referenced by operator++().
operator++() [2/2]
iterator clang::CodeGen::EHScopeStack::iterator::operator++ (int) inline
Definition at line 547 of file CGCleanup.h.
References operator++().
operator->()
EHScope* clang::CodeGen::EHScopeStack::iterator::operator-> () const inline
Definition at line 513 of file CGCleanup.h.
References get().
operator==()
bool clang::CodeGen::EHScopeStack::iterator::operator== (iterator other) const inline
Definition at line 556 of file CGCleanup.h.
strictlyEncloses()
bool clang::CodeGen::EHScopeStack::iterator::strictlyEncloses (iterator other) const inline
Definition at line 554 of file CGCleanup.h.
Friends And Related Function Documentation
EHScopeStack
friend class EHScopeStack friend
Definition at line 503 of file CGCleanup.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CGCleanup.h