clang: clang::tooling::stdlib::Recognizer Class Reference
clang::tooling::stdlib::Recognizer Class Reference
#include "clang/Tooling/Inclusions/StandardLibrary.h"
Public Member Functions
Recognizer ()
llvm::Optional< Symbol > operator() (const Decl *D)
Detailed Description
Definition at line 91 of file StandardLibrary.h.
Constructor & Destructor Documentation
Recognizer()
clang::tooling::stdlib::Recognizer::Recognizer ()
Definition at line 104 of file StandardLibrary.cpp.
References clang::tooling::stdlib::ensureInitialized().
Member Function Documentation
operator()()
llvm::Optional< Symbol > clang::tooling::stdlib::Recognizer::operator() (const Decl * D)
Definition at line 126 of file StandardLibrary.cpp.
References clang::NamedDecl::classofKind(), clang::Decl::getDeclContext(), clang::DeclContext::getDeclKind(), clang::DeclContext::getParent(), and clang::DeclContext::isNamespace().
The documentation for this class was generated from the following files:
include/clang/Tooling/Inclusions/StandardLibrary.h
lib/Tooling/Inclusions/StandardLibrary.cpp