clang: clang::driver::toolchains::Darwin Class Reference
clang::driver::toolchains::Darwin Class Reference
Darwin - The base Darwin tool chain.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/Darwin.h"
Public Types
enum DarwinPlatformKind {
MacOS , IPhoneOS , TvOS , WatchOS ,
DriverKit , XROS , LastDarwinPlatform = XROS
}
enum DarwinEnvironmentKind { NativeEnvironment , Simulator , MacCatalyst }
Public Types inherited from clang::driver::toolchains::MachO
enum RuntimeLinkOptions : unsigned { RLO_AlwaysLink = 1 << 0 , RLO_IsEmbedded = 1 << 1 , RLO_AddRPath = 1 << 2 }
Options to control how a runtime library is linked.
Public Types inherited from clang::driver::ToolChain
enum CXXStdlibType { CST_Libcxx , CST_Libstdcxx }
enum RuntimeLibType { RLT_CompilerRT , RLT_Libgcc }
enum UnwindLibType { UNW_None , UNW_CompilerRT , UNW_Libgcc }
enum class UnwindTableLevel { None , Synchronous , Asynchronous }
enum RTTIMode { RM_Enabled , RM_Disabled }
enum ExceptionsMode { EM_Enabled , EM_Disabled }
enum FileType { FT_Object , FT_Static , FT_Shared }
using path_list = SmallVector< std::string, 16 >
Public Member Functions
Darwin (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
Darwin - Darwin tool chain for i386 and x86_64.
~Darwin () override
std::string ComputeEffectiveClangTriple (const llvm::opt::ArgList &Args, types::ID InputType) const override
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
Apple Specific Toolchain Implementation
{
void addMinVersionArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
void addPlatformVersionArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
void addStartObjectFileArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
bool isKernelStatic () const override
On some iOS platforms, kernel and kernel modules were built statically.
void addProfileRTLibs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
Add any profiling runtime libraries that are needed.
ToolChain Implementation
}
{
bool isCrossCompiling () const override
Returns true if the toolchain is targeting a non-native architecture.
llvm::opt::DerivedArgList * TranslateArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
CXXStdlibType GetDefaultCXXStdlibType () const override
ObjCRuntime getDefaultObjCRuntime (bool isNonFragile) const override
Darwin provides an ARC runtime starting in MacOS X 10.7 and iOS 5.0.
bool hasBlocksRuntime () const override
Darwin provides a blocks runtime starting in MacOS X 10.6 and iOS 3.2.
void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use system-specific CUDA includes.
void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use system-specific HIP includes.
bool UseObjCMixedDispatch () const override
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
LangOptions::StackProtectorMode GetDefaultStackProtectorLevel (bool KernelOrKext) const override
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
void CheckObjCARC () const override
Complain if this tool chain doesn't support Objective-C ARC.
llvm::ExceptionHandling GetExceptionModel (const llvm::opt::ArgList &Args) const override
GetExceptionModel - Return the tool chain exception model.
bool SupportsEmbeddedBitcode () const override
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
SanitizerMask getSupportedSanitizers () const override
Return sanitizers which are available in this toolchain.
void printVerboseInfo (raw_ostream &OS) const override
Dispatch to the specific toolchain for verbose printing.
Public Member Functions inherited from clang::driver::toolchains::MachO
MachO (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
~MachO () override
types::ID LookupTypeForExtension (StringRef Ext) const override
LookupTypeForExtension - Return the default language type to use for the given extension.
bool HasNativeLLVMSupport () const override
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
bool IsBlocksDefault () const override
IsBlocksDefault - Does this tool chain enable -fblocks by default.
bool IsMathErrnoDefault () const override
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
bool IsEncodeExtendedBlockSignatureDefault () const override
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
bool IsObjCNonFragileABIDefault () const override
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
UnwindTableLevel getDefaultUnwindTableLevel (const llvm::opt::ArgList &Args) const override
How detailed should the unwind tables be by default.
RuntimeLibType GetDefaultRuntimeLibType () const override
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
bool isPICDefault () const override
Test whether this toolchain defaults to PIC.
bool isPIEDefault (const llvm::opt::ArgList &Args) const override
Test whether this toolchain defaults to PIE.
bool isPICDefaultForced () const override
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
bool SupportsProfiling () const override
SupportsProfiling - Does this tool chain support -pg.
bool UseDwarfDebugFlags () const override
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
std::string GetGlobalDebugPathRemapping () const override
Add an additional -fdebug-prefix-map entry.
bool canSplitThinLTOUnit () const override
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
StringRef getMachOArchName (const llvm::opt::ArgList &Args) const
Get the "MachO" arch name for a particular compiler invocation.
VersionTuple getLinkerVersion (const llvm::opt::ArgList &Args) const
Get the version of the linker known to be available for a particular compiler invocation (via the -mlinker-version= arg).
virtual void AddLinkARCArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
Add the linker arguments to link the ARC runtime library.
virtual void AddLinkRuntimeLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, bool ForceLinkBuiltinRT=false) const
Add the linker arguments to link the compiler runtime library.
bool isTargetIOSBased () const
Is the target either iOS or an iOS simulator?
void AddLinkRuntimeLib (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, StringRef Component, RuntimeLinkOptions Opts=RuntimeLinkOptions(), bool IsShared=false) const
Add a runtime library to the list of items to link.
Public Member Functions inherited from clang::driver::ToolChain
virtual ~ToolChain ()
const Driver & getDriver () const
llvm::vfs::FileSystem & getVFS () const
const llvm::Triple & getTriple () const
virtual const llvm::Triple * getAuxTriple () const
Get the toolchain's aux triple, if it has one.
virtual std::string getInputFilename (const InputInfo &Input) const
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
llvm::Triple::ArchType getArch () const
StringRef getArchName () const
StringRef getPlatform () const
StringRef getOS () const
StringRef getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
std::string getTripleString () const
const llvm::Triple & getEffectiveTriple () const
Get the toolchain's effective clang triple.
bool hasEffectiveTriple () const
path_list & getLibraryPaths ()
const path_list & getLibraryPaths () const
path_list & getFilePaths ()
const path_list & getFilePaths () const
path_list & getProgramPaths ()
const path_list & getProgramPaths () const
const MultilibSet & getMultilibs () const
const llvm::SmallVector< Multilib > & getSelectedMultilibs () const
Multilib::flags_list getMultilibFlags (const llvm::opt::ArgList &) const
Get flags suitable for multilib selection, based on the provided clang command line arguments.
SanitizerArgs getSanitizerArgs (const llvm::opt::ArgList &JobArgs) const
const XRayArgs & getXRayArgs () const
const llvm::opt::Arg * getRTTIArg () const
RTTIMode getRTTIMode () const
ExceptionsMode getExceptionsMode () const
virtual llvm::opt::DerivedArgList * TranslateOffloadTargetArgs (const llvm::opt::DerivedArgList &Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > &AllocatedArgs, Action::OffloadKind DeviceOffloadKind) const
TranslateOffloadTargetArgs - Create a new derived argument list for that contains the Offload target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val Also handles -Xsycl-target OR -Xsycl-target=<triple>
virtual void TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, llvm::opt::Arg *&A, llvm::opt::DerivedArgList *DAL, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs=nullptr) const
Append the argument following A to DAL assuming A is an Xarch argument.
virtual llvm::opt::DerivedArgList * TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs) const
Translate -Xarch_ arguments.
virtual Tool * SelectTool (const JobAction &JA) const
Choose a tool to use to handle the action JA.
std::string GetFilePath (const char *Name) const
std::string GetProgramPath (const char *Name) const
std::string GetLinkerPath (bool *LinkerIsLLD=nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
std::string GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
virtual bool IsIntegratedAssemblerDefault () const
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
virtual bool IsIntegratedBackendDefault () const
IsIntegratedBackendDefault - Does this tool chain enable -fintegrated-objemitter by default.
virtual bool IsIntegratedBackendSupported () const
IsIntegratedBackendSupported - Does this tool chain support -fintegrated-objemitter.
virtual bool IsNonIntegratedBackendSupported () const
IsNonIntegratedBackendSupported - Does this tool chain support -fno-integrated-objemitter.
virtual bool useIntegratedAs () const
Check if the toolchain should use the integrated assembler.
virtual bool useIntegratedBackend () const
Check if the toolchain should use the integrated backend.
virtual bool parseInlineAsmUsingAsmParser () const
Check if the toolchain should use AsmParser to parse inlineAsm when integrated assembler is not default.
virtual bool useRelaxRelocations () const
Check whether to enable x86 relax relocations by default.
bool defaultToIEEELongDouble () const
Check whether use IEEE binary128 as long double format by default.
virtual LangOptions::TrivialAutoVarInitKind GetDefaultTrivialAutoVarInit () const
Get the default trivial automatic variable initialization.
virtual const char * getDefaultLinker () const
GetDefaultLinker - Get the default linker to use.
virtual UnwindLibType GetDefaultUnwindLibType () const
virtual std::string getCompilerRTPath () const
virtual std::string getCompilerRT (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
const char * getCompilerRTArgString (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::string getCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::optional< std::string > getRuntimePath () const
std::optional< std::string > getStdlibPath () const
virtual path_list getArchSpecificLibPaths () const
virtual StringRef getOSLibName () const
virtual bool IsAArch64OutlineAtomicsDefault (const llvm::opt::ArgList &Args) const
Test whether this toolchain supports outline atomics by default.
virtual llvm::codegenoptions::DebugInfoFormat getDefaultDebugFormat () const
Get the default debug info format. Typically, this is DWARF.
virtual unsigned GetDefaultDwarfVersion () const
virtual unsigned getMaxDwarfVersion () const
virtual bool GetDefaultStandaloneDebug () const
virtual llvm::DebuggerKind getDefaultDebuggerTuning () const
virtual bool supportsDebugInfoOption (const llvm::opt::Arg *) const
Does this toolchain supports given debug info option or not.
virtual void adjustDebugInfoKind (llvm::codegenoptions::DebugInfoKind &DebugInfoKind, const llvm::opt::ArgList &Args) const
Adjust debug information kind considering all passed options.
virtual std::string getThreadModel () const
getThreadModel() - Which thread model does this target use?
virtual bool isThreadModelSupported (const StringRef Model) const
isThreadModelSupported() - Does this target support a thread model?
virtual bool isBareMetal () const
isBareMetal - Is this a bare metal target.
virtual std::string getMultiarchTriple (const Driver &D, const llvm::Triple &TargetTriple, StringRef SysRoot) const
virtual std::string ComputeLLVMTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
virtual std::string computeSysRoot () const
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
virtual void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add the clang cc1 arguments for system include paths.
virtual void addClangWarningOptions (llvm::opt::ArgStringList &CC1Args) const
Add warning options that need to be passed to cc1 for this target.
virtual RuntimeLibType GetRuntimeLibType (const llvm::opt::ArgList &Args) const
virtual CXXStdlibType GetCXXStdlibType (const llvm::opt::ArgList &Args) const
virtual UnwindLibType GetUnwindLibType (const llvm::opt::ArgList &Args) const
virtual std::string detectLibcxxVersion (StringRef IncludePath) const
virtual void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
void AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
bool ShouldLinkCXXStdlib (const llvm::opt::ArgList &Args) const
Returns if the C++ standard library should be linked in.
virtual void AddCXXStdlibLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
void AddFilePathLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
virtual void AddCCKextLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
virtual bool isFastMathRuntimeAvailable (const llvm::opt::ArgList &Args, std::string &Path) const
If a runtime library exists that sets global flags for unsafe floating point math, return true.
bool addFastMathRuntimeIfAvailable (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
virtual Expected< SmallVector< std::string > > getSystemGPUArchs (const llvm::opt::ArgList &Args) const
getSystemGPUArchs - Use a tool to detect the user's availible GPUs.
virtual void AddIAMCUIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use MCU GCC toolchain includes.
virtual VersionTuple computeMSVCVersion (const Driver *D, const llvm::opt::ArgList &Args) const
On Windows, returns the MSVC compatibility version.
virtual llvm::SmallVector< BitCodeLibraryInfo, 12 > getDeviceLibs (const llvm::opt::ArgList &Args, const Action::OffloadKind DeviceOffloadingKind) const
Get paths for device libraries.
virtual void AddHIPRuntimeLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
Add the system specific linker arguments to use for the given HIP runtime library type.
virtual SanitizerMask getDefaultSanitizers () const
Return sanitizers which are enabled by default.
virtual llvm::DenormalMode getDefaultDenormalModeForType (const llvm::opt::ArgList &DriverArgs, const JobAction &JA, const llvm::fltSemantics *FPType=nullptr) const
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
Public Attributes
bool TargetInitialized
Whether the information on the target has been initialized.
DarwinPlatformKind TargetPlatform
DarwinEnvironmentKind TargetEnvironment
VersionTuple TargetVersion
The native OS version we are targeting.
VersionTuple OSTargetVersion
The OS version we are targeting as specified in the triple.
std::optional< DarwinSDKInfo > SDKInfo
The information about the darwin SDK that was used.
std::optional< llvm::Triple > TargetVariantTriple
The target variant triple that was specified (if any).
LazyDetector< CudaInstallationDetector > CudaInstallation
LazyDetector< RocmInstallationDetector > RocmInstallation
Darwin specific Toolchain functions
}
{
bool isTargetIPhoneOS () const
bool isTargetIOSSimulator () const
bool isTargetIOSBased () const
bool isTargetXROSDevice () const
bool isTargetXROSSimulator () const
bool isTargetXROS () const
bool isTargetTvOS () const
bool isTargetTvOSSimulator () const
bool isTargetTvOSBased () const
bool isTargetWatchOS () const
bool isTargetWatchOSSimulator () const
bool isTargetWatchOSBased () const
bool isTargetDriverKit () const
bool isTargetMacCatalyst () const
bool isTargetMacOS () const
bool isTargetMacOSBased () const
bool isTargetAppleSiliconMac () const
bool isTargetInitialized () const
VersionTuple getTripleTargetVersion () const
The version of the OS that's used by the OS specified in the target triple.
bool isIPhoneOSVersionLT (unsigned V0, unsigned V1=0, unsigned V2=0) const
bool isMacosxVersionLT (unsigned V0, unsigned V1=0, unsigned V2=0) const
Returns true if the minimum supported macOS version for the slice that's being built is less than the specified version.
void setTarget (DarwinPlatformKind Platform, DarwinEnvironmentKind Environment, unsigned Major, unsigned Minor, unsigned Micro, VersionTuple NativeTargetVersion) const
bool isAlignedAllocationUnavailable () const
Return true if c++17 aligned allocation/deallocation functions are not implemented in the c++ standard library of the deployment target we are targeting.
void addClangTargetOptions (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, Action::OffloadKind DeviceOffloadKind) const override
Add options that need to be passed to cc1 for this target.
void addClangCC1ASTargetOptions (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CC1ASArgs) const override
Add options that need to be passed to cc1as for this target.
StringRef getPlatformFamily () const
StringRef getOSLibraryNameSuffix (bool IgnoreSim=false) const override
static StringRef getSDKName (StringRef isysroot)
Additional Inherited Members
Static Public Member Functions inherited from clang::driver::ToolChain
static ParsedClangName getTargetAndModeFromProgramName (StringRef ProgName)
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
static bool needsProfileRT (const llvm::opt::ArgList &Args)
needsProfileRT - returns true if instrumentation profile is on.
static bool needsGCovInstrumentation (const llvm::opt::ArgList &Args)
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
static llvm::Triple getOpenMPTriple (StringRef TripleStr)
Protected Member Functions inherited from clang::driver::toolchains::MachO
Tool * buildAssembler () const override
Tool * buildLinker () const override
Tool * buildStaticLibTool () const override
Tool * getTool (Action::ActionClass AC) const override
Protected Member Functions inherited from clang::driver::ToolChain
ToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > executeToolChainProgram (StringRef Executable) const
Executes the given Executable and returns the stdout.
void setTripleEnvironment (llvm::Triple::EnvironmentType Env)
virtual Tool * buildBackendCompiler () const
virtual std::string buildCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type, bool AddArch) const
std::optional< std::string > getTargetSubDirPath (StringRef BaseDir) const
Find the target-specific subdirectory for the current target triple under BaseDir, doing fallback triple searches as necessary.
Static Protected Member Functions inherited from clang::driver::ToolChain
static void addSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory to CC1 arguments.
static void addExternCSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
static void addExternCSystemIncludeIfExists (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
static void addSystemIncludes (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, ArrayRef< StringRef > Paths)
Utility function to add a list of system include directories to CC1.
static std::string concat (StringRef Path, const Twine &A, const Twine &B="", const Twine &C="", const Twine &D="")
Protected Attributes inherited from clang::driver::ToolChain
MultilibSet Multilibs
llvm::SmallVector< Multilib > SelectedMultilibs
Detailed Description
Darwin - The base Darwin tool chain.
Definition at line 287 of file Darwin.h.
Member Enumeration Documentation
DarwinEnvironmentKind
enum clang::driver::toolchains::Darwin::DarwinEnvironmentKind
Enumerator
NativeEnvironment
Simulator
MacCatalyst
Definition at line 305 of file Darwin.h.
DarwinPlatformKind
enum clang::driver::toolchains::Darwin::DarwinPlatformKind
Enumerator
MacOS
IPhoneOS
TvOS
WatchOS
DriverKit
XROS
LastDarwinPlatform
Definition at line 296 of file Darwin.h.
Constructor & Destructor Documentation
Darwin()
Darwin::Darwin (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args)
Darwin - Darwin tool chain for i386 and x86_64.
Definition at line 932 of file Darwin.cpp.
~Darwin()
Darwin::~Darwin () override
Definition at line 1082 of file Darwin.cpp.
Member Function Documentation
addClangCC1ASTargetOptions()
void Darwin::addClangCC1ASTargetOptions (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CC1ASArgs) const override protected virtual
Add options that need to be passed to cc1as for this target.
Pass the SDK version to the compiler when the SDK information is available.
Pass the target variant SDK version to the compiler when the SDK information is available and is required for target variant.
Reimplemented from clang::driver::ToolChain.
Definition at line 2957 of file Darwin.cpp.
References isTargetMacCatalyst(), clang::DarwinSDKInfo::OSEnvPair::macOStoMacCatalystPair(), minimumMacCatalystDeploymentTarget(), SDKInfo, TargetVariantTriple, and V.
Referenced by addClangTargetOptions().
addClangTargetOptions()
void Darwin::addClangTargetOptions (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, Action::OffloadKind DeviceOffloadKind) const override protected virtual
Add options that need to be passed to cc1 for this target.
Reimplemented from clang::driver::ToolChain.
Definition at line 2915 of file Darwin.cpp.
References addClangCC1ASTargetOptions(), isAlignedAllocationUnavailable(), SDKInfo, sdkSupportsBuiltinModules(), and TargetPlatform.
AddCudaIncludeArgs()
void Darwin::AddCudaIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add arguments to use system-specific CUDA includes.
Reimplemented from clang::driver::ToolChain.
Definition at line 983 of file Darwin.cpp.
References CudaInstallation.
AddHIPIncludeArgs()
void Darwin::AddHIPIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add arguments to use system-specific HIP includes.
Reimplemented from clang::driver::ToolChain.
Definition at line 988 of file Darwin.cpp.
References RocmInstallation.
addMinVersionArgs()
void Darwin::addMinVersionArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const override virtual
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 3122 of file Darwin.cpp.
References clang::driver::ToolChain::getEffectiveTriple(), getTripleTargetVersion(), isTargetDriverKit(), isTargetIOSBased(), isTargetIOSSimulator(), isTargetMacCatalyst(), isTargetMacOS(), isTargetMacOSBased(), isTargetTvOS(), isTargetTvOSSimulator(), isTargetWatchOS(), isTargetWatchOSSimulator(), isTargetXROS(), TargetVariantTriple, and TargetVersion.
addPlatformVersionArgs()
void Darwin::addPlatformVersionArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const override virtual
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 3195 of file Darwin.cpp.
References clang::driver::ToolChain::getArchName(), clang::getAsString(), clang::driver::ToolChain::getEffectiveTriple(), getPlatformName(), clang::driver::ToolChain::getTriple(), getTripleTargetVersion(), IPhoneOS, MacCatalyst, MacOS, clang::DarwinSDKInfo::OSEnvPair::macOStoMacCatalystPair(), minimumMacCatalystDeploymentTarget(), NativeEnvironment, SDKInfo, Simulator, TargetEnvironment, TargetPlatform, TargetVariantTriple, TargetVersion, and TvOS.
addProfileRTLibs()
void Darwin::addProfileRTLibs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const override virtual
Add any profiling runtime libraries that are needed.
This is essentially a MachO specific version of addProfileRT in Tools.cpp.
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 1401 of file Darwin.cpp.
References addExportedSymbol(), clang::driver::toolchains::MachO::AddLinkRuntimeLib(), addSectalignToPage(), hasExportSymbolDirective(), clang::driver::ToolChain::needsGCovInstrumentation(), clang::driver::ToolChain::needsProfileRT(), and clang::driver::toolchains::MachO::RLO_AlwaysLink.
addStartObjectFileArgs()
void Darwin::addStartObjectFileArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const override virtual
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 3361 of file Darwin.cpp.
References addBundleLinkArgs(), addDefaultCRTLinkArgs(), addDynamicLibLinkArgs(), addPgProfilingLinkArgs(), clang::driver::ToolChain::GetFilePath(), isMacosxVersionLT(), isTargetMacOS(), and clang::driver::toolchains::MachO::SupportsProfiling().
CheckObjCARC()
void Darwin::CheckObjCARC () const override virtual
Complain if this tool chain doesn't support Objective-C ARC.
Reimplemented from clang::driver::ToolChain.
Definition at line 3384 of file Darwin.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), isMacosxVersionLT(), isTargetIOSBased(), isTargetMacOSBased(), isTargetWatchOSBased(), and isTargetXROS().
ComputeEffectiveClangTriple()
std::string Darwin::ComputeEffectiveClangTriple (const llvm::opt::ArgList & Args, types::ID InputType) const override virtual
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
For example, on Darwin the -mmacosx-version-min= command line argument (which sets the deployment target) determines the version in the triple passed to Clang.
Reimplemented from clang::driver::ToolChain.
Definition at line 1086 of file Darwin.cpp.
References clang::driver::ToolChain::ComputeLLVMTriple(), getTripleTargetVersion(), isTargetDriverKit(), isTargetInitialized(), isTargetIOSBased(), isTargetMacCatalyst(), isTargetTvOSBased(), isTargetWatchOSBased(), and isTargetXROS().
GetDefaultCXXStdlibType()
ToolChain::CXXStdlibType Darwin::GetDefaultCXXStdlibType () const override virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 948 of file Darwin.cpp.
References clang::driver::ToolChain::CST_Libcxx.
getDefaultObjCRuntime()
ObjCRuntime Darwin::getDefaultObjCRuntime (bool isNonFragile) const override virtual
Darwin provides an ARC runtime starting in MacOS X 10.7 and iOS 5.0.
Reimplemented from clang::driver::ToolChain.
Definition at line 954 of file Darwin.cpp.
References clang::ObjCRuntime::FragileMacOSX, clang::ObjCRuntime::iOS, isTargetIOSBased(), isTargetWatchOSBased(), isTargetXROS(), clang::ObjCRuntime::MacOSX, clang::T, TargetVersion, and clang::ObjCRuntime::WatchOS.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs().
GetDefaultStackProtectorLevel()
LangOptions::StackProtectorMode clang::driver::toolchains::Darwin::GetDefaultStackProtectorLevel (bool KernelOrKext) const inline override virtual
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
Reimplemented from clang::driver::ToolChain.
Definition at line 558 of file Darwin.h.
References clang::LangOptionsBase::SSPOff, and clang::LangOptionsBase::SSPOn.
GetExceptionModel()
llvm::ExceptionHandling Darwin::GetExceptionModel (const llvm::opt::ArgList & Args) const override virtual
GetExceptionModel - Return the tool chain exception model.
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 3087 of file Darwin.cpp.
References clang::driver::ToolChain::ComputeLLVMTriple(), clang::driver::ToolChain::getArch(), clang::driver::ToolChain::getTriple(), and clang::XRayInstrKind::None.
getOSLibraryNameSuffix()
StringRef Darwin::getOSLibraryNameSuffix (bool IgnoreSim = false) const override protected virtual
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 1343 of file Darwin.cpp.
References MacCatalyst, NativeEnvironment, TargetEnvironment, and TargetPlatform.
getPlatformFamily()
StringRef Darwin::getPlatformFamily () const protected
Definition at line 1311 of file Darwin.cpp.
References MacCatalyst, TargetEnvironment, and TargetPlatform.
getSDKName()
StringRef Darwin::getSDKName (StringRef isysroot) static
Definition at line 1331 of file Darwin.cpp.
getSupportedSanitizers()
SanitizerMask Darwin::getSupportedSanitizers () const override virtual
Return sanitizers which are available in this toolchain.
Reimplemented from clang::driver::ToolChain.
Definition at line 3391 of file Darwin.cpp.
References clang::driver::ToolChain::getSupportedSanitizers(), clang::driver::ToolChain::getTriple(), isIPhoneOSVersionLT(), isMacosxVersionLT(), isTargetIOSSimulator(), isTargetIPhoneOS(), isTargetMacOSBased(), isTargetTvOSSimulator(), and isTargetWatchOSSimulator().
getTripleTargetVersion()
VersionTuple clang::driver::toolchains::Darwin::getTripleTargetVersion () const inline
The version of the OS that's used by the OS specified in the target triple.
It might be different from the actual target OS on which the program will run, e.g. MacCatalyst code runs on a macOS target, but its target triple is iOS.
Definition at line 479 of file Darwin.h.
References clang::TargetVersion.
Referenced by addMinVersionArgs(), addPlatformVersionArgs(), and ComputeEffectiveClangTriple().
hasBlocksRuntime()
bool Darwin::hasBlocksRuntime () const override virtual
Darwin provides a blocks runtime starting in MacOS X 10.6 and iOS 3.2.
Reimplemented from clang::driver::ToolChain.
Definition at line 972 of file Darwin.cpp.
References isIPhoneOSVersionLT(), isMacosxVersionLT(), isTargetDriverKit(), isTargetIOSBased(), isTargetMacOSBased(), isTargetWatchOSBased(), and isTargetXROS().
isAlignedAllocationUnavailable()
bool Darwin::isAlignedAllocationUnavailable () const protected
Return true if c++17 aligned allocation/deallocation functions are not implemented in the c++ standard library of the deployment target we are targeting.
Definition at line 2867 of file Darwin.cpp.
References clang::alignedAllocMinVersion(), DriverKit, IPhoneOS, isTargetMacCatalyst(), MacOS, TargetPlatform, TargetVersion, TvOS, WatchOS, and XROS.
Referenced by addClangTargetOptions().
isCrossCompiling()
bool clang::driver::toolchains::Darwin::isCrossCompiling () const inline override virtual
Returns true if the toolchain is targeting a non-native architecture.
Reimplemented from clang::driver::ToolChain.
Definition at line 535 of file Darwin.h.
isIPhoneOSVersionLT()
bool clang::driver::toolchains::Darwin::isIPhoneOSVersionLT (unsigned V0, unsigned V1 = 0, unsigned V2 = 0) const inline
Definition at line 484 of file Darwin.h.
References clang::TargetVersion.
Referenced by addBundleLinkArgs(), addDefaultCRTLinkArgs(), addDynamicLibLinkArgs(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), clang::driver::toolchains::DarwinClang::GetDefaultDwarfVersion(), getSupportedSanitizers(), hasBlocksRuntime(), SupportsEmbeddedBitcode(), and TranslateArgs().
isKernelStatic()
bool clang::driver::toolchains::Darwin::isKernelStatic () const inline override virtual
On some iOS platforms, kernel and kernel modules were built statically.
Is this such a target?
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 351 of file Darwin.h.
isMacosxVersionLT()
bool clang::driver::toolchains::Darwin::isMacosxVersionLT (unsigned V0, unsigned V1 = 0, unsigned V2 = 0) const inline
Returns true if the minimum supported macOS version for the slice that's being built is less than the specified version.
If there's no minimum supported macOS version, the deployment target version is compared to the specifed version instead.
Definition at line 494 of file Darwin.h.
References clang::TargetVersion.
Referenced by addBundleLinkArgs(), addDefaultCRTLinkArgs(), addDynamicLibLinkArgs(), addPgProfilingLinkArgs(), addStartObjectFileArgs(), CheckObjCARC(), clang::driver::toolchains::DarwinClang::GetDefaultDwarfVersion(), getSupportedSanitizers(), and hasBlocksRuntime().
isTargetAppleSiliconMac()
bool clang::driver::toolchains::Darwin::isTargetAppleSiliconMac () const inline
Definition at line 468 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs().
isTargetDriverKit()
bool clang::driver::toolchains::Darwin::isTargetDriverKit () const inline
Definition at line 449 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddCCKextLibArgs(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), addMinVersionArgs(), ComputeEffectiveClangTriple(), hasBlocksRuntime(), and TranslateArgs().
isTargetInitialized()
bool clang::driver::toolchains::Darwin::isTargetInitialized () const inline
Definition at line 473 of file Darwin.h.
Referenced by ComputeEffectiveClangTriple().
isTargetIOSBased()
bool clang::driver::toolchains::Darwin::isTargetIOSBased () const inline
Definition at line 404 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), addMinVersionArgs(), CheckObjCARC(), ComputeEffectiveClangTriple(), clang::driver::toolchains::DarwinClang::GetDefaultDwarfVersion(), getDefaultObjCRuntime(), hasBlocksRuntime(), and TranslateArgs().
isTargetIOSSimulator()
bool clang::driver::toolchains::Darwin::isTargetIOSSimulator () const inline
Definition at line 398 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), addMinVersionArgs(), and getSupportedSanitizers().
isTargetIPhoneOS()
bool clang::driver::toolchains::Darwin::isTargetIPhoneOS () const inline
Definition at line 392 of file Darwin.h.
Referenced by addBundleLinkArgs(), clang::driver::toolchains::DarwinClang::AddCCKextLibArgs(), addDefaultCRTLinkArgs(), addDynamicLibLinkArgs(), clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), getSupportedSanitizers(), and SupportsEmbeddedBitcode().
isTargetMacCatalyst()
bool clang::driver::toolchains::Darwin::isTargetMacCatalyst () const inline
Definition at line 454 of file Darwin.h.
Referenced by addClangCC1ASTargetOptions(), addMinVersionArgs(), ComputeEffectiveClangTriple(), and isAlignedAllocationUnavailable().
isTargetMacOS()
bool clang::driver::toolchains::Darwin::isTargetMacOS () const inline
Definition at line 458 of file Darwin.h.
Referenced by addBundleLinkArgs(), clang::driver::toolchains::DarwinClang::addClangWarningOptions(), addDefaultCRTLinkArgs(), addDynamicLibLinkArgs(), addMinVersionArgs(), addPgProfilingLinkArgs(), and addStartObjectFileArgs().
isTargetMacOSBased()
bool clang::driver::toolchains::Darwin::isTargetMacOSBased () const inline
Definition at line 463 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), addMinVersionArgs(), addPgProfilingLinkArgs(), CheckObjCARC(), clang::driver::toolchains::DarwinClang::GetDefaultDwarfVersion(), getSupportedSanitizers(), and hasBlocksRuntime().
isTargetTvOS()
bool clang::driver::toolchains::Darwin::isTargetTvOS () const inline
Definition at line 419 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddCCKextLibArgs(), clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), and addMinVersionArgs().
isTargetTvOSBased()
bool clang::driver::toolchains::Darwin::isTargetTvOSBased () const inline
Definition at line 429 of file Darwin.h.
Referenced by ComputeEffectiveClangTriple().
isTargetTvOSSimulator()
bool clang::driver::toolchains::Darwin::isTargetTvOSSimulator () const inline
Definition at line 424 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), addMinVersionArgs(), and getSupportedSanitizers().
isTargetWatchOS()
bool clang::driver::toolchains::Darwin::isTargetWatchOS () const inline
Definition at line 434 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddCCKextLibArgs(), clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), and addMinVersionArgs().
isTargetWatchOSBased()
bool clang::driver::toolchains::Darwin::isTargetWatchOSBased () const inline
Definition at line 444 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::addClangWarningOptions(), CheckObjCARC(), ComputeEffectiveClangTriple(), getDefaultObjCRuntime(), hasBlocksRuntime(), and TranslateArgs().
isTargetWatchOSSimulator()
bool clang::driver::toolchains::Darwin::isTargetWatchOSSimulator () const inline
Definition at line 439 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), addMinVersionArgs(), and getSupportedSanitizers().
isTargetXROS()
bool clang::driver::toolchains::Darwin::isTargetXROS () const inline
Definition at line 417 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), addMinVersionArgs(), CheckObjCARC(), ComputeEffectiveClangTriple(), getDefaultObjCRuntime(), hasBlocksRuntime(), and TranslateArgs().
isTargetXROSDevice()
bool clang::driver::toolchains::Darwin::isTargetXROSDevice () const inline
Definition at line 409 of file Darwin.h.
Referenced by clang::driver::toolchains::DarwinClang::AddCCKextLibArgs().
isTargetXROSSimulator()
bool clang::driver::toolchains::Darwin::isTargetXROSSimulator () const inline
Definition at line 413 of file Darwin.h.
printVerboseInfo()
void Darwin::printVerboseInfo (raw_ostream & OS) const override virtual
Dispatch to the specific toolchain for verbose printing.
This is used when handling the verbose option to print detailed, toolchain-specific information useful for understanding the behavior of the driver on a specific platform.
Reimplemented from clang::driver::ToolChain.
Definition at line 3418 of file Darwin.cpp.
References CudaInstallation, and RocmInstallation.
setTarget()
void clang::driver::toolchains::Darwin::setTarget (DarwinPlatformKind Platform, DarwinEnvironmentKind Environment, unsigned Major, unsigned Minor, unsigned Micro, VersionTuple NativeTargetVersion) const inline protected
Definition at line 366 of file Darwin.h.
References clang::TargetVersion.
SupportsEmbeddedBitcode()
bool Darwin::SupportsEmbeddedBitcode () const override virtual
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
Reimplemented from clang::driver::ToolChain.
Definition at line 3101 of file Darwin.cpp.
References isIPhoneOSVersionLT(), isTargetIPhoneOS(), and TargetInitialized.
TranslateArgs()
DerivedArgList * Darwin::TranslateArgs (const llvm::opt::DerivedArgList & Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override virtual
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
If DeviceOffloadKind is specified the translation specific for that offload kind is performed.
Parameters
BoundArch - The bound architecture name, or 0.
DeviceOffloadKind - The device offload kind used for the translation.
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 3013 of file Darwin.cpp.
References clang::driver::Driver::Diag(), clang::driver::tools::darwin::getArchTypeForMachOArchName(), clang::driver::ToolChain::getDriver(), isIPhoneOSVersionLT(), isTargetDriverKit(), isTargetIOSBased(), isTargetWatchOSBased(), isTargetXROS(), and clang::driver::toolchains::MachO::TranslateArgs().
UseObjCMixedDispatch()
bool clang::driver::toolchains::Darwin::UseObjCMixedDispatch () const inline override virtual
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
Reimplemented from clang::driver::toolchains::MachO.
Definition at line 550 of file Darwin.h.
Member Data Documentation
CudaInstallation
LazyDetector<CudaInstallationDetector> clang::driver::toolchains::Darwin::CudaInstallation
Definition at line 325 of file Darwin.h.
Referenced by AddCudaIncludeArgs(), and printVerboseInfo().
OSTargetVersion
VersionTuple clang::driver::toolchains::Darwin::OSTargetVersion mutable
The OS version we are targeting as specified in the triple.
Definition at line 317 of file Darwin.h.
RocmInstallation
LazyDetector<RocmInstallationDetector> clang::driver::toolchains::Darwin::RocmInstallation
Definition at line 326 of file Darwin.h.
Referenced by AddHIPIncludeArgs(), and printVerboseInfo().
SDKInfo
std::optional<DarwinSDKInfo> clang::driver::toolchains::Darwin::SDKInfo mutable
The information about the darwin SDK that was used.
Definition at line 320 of file Darwin.h.
Referenced by addClangCC1ASTargetOptions(), addClangTargetOptions(), and addPlatformVersionArgs().
TargetEnvironment
DarwinEnvironmentKind clang::driver::toolchains::Darwin::TargetEnvironment mutable
Definition at line 312 of file Darwin.h.
Referenced by addPlatformVersionArgs(), getOSLibraryNameSuffix(), and getPlatformFamily().
TargetInitialized
bool clang::driver::toolchains::Darwin::TargetInitialized mutable
Whether the information on the target has been initialized.
Definition at line 294 of file Darwin.h.
Referenced by SupportsEmbeddedBitcode().
TargetPlatform
DarwinPlatformKind clang::driver::toolchains::Darwin::TargetPlatform mutable
Definition at line 311 of file Darwin.h.
Referenced by addClangTargetOptions(), addPlatformVersionArgs(), getOSLibraryNameSuffix(), getPlatformFamily(), and isAlignedAllocationUnavailable().
TargetVariantTriple
std::optional<llvm::Triple> clang::driver::toolchains::Darwin::TargetVariantTriple mutable
The target variant triple that was specified (if any).
Definition at line 323 of file Darwin.h.
Referenced by addClangCC1ASTargetOptions(), addMinVersionArgs(), and addPlatformVersionArgs().
TargetVersion
VersionTuple clang::driver::toolchains::Darwin::TargetVersion mutable
The native OS version we are targeting.
Definition at line 315 of file Darwin.h.
Referenced by addMinVersionArgs(), addPlatformVersionArgs(), getDefaultObjCRuntime(), and isAlignedAllocationUnavailable().
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Darwin.h
lib/Driver/ToolChains/Darwin.cpp