clang: clang::SemaBPF Class Reference
clang::SemaBPF Class Reference
#include "clang/Sema/SemaBPF.h"
Public Member Functions
SemaBPF (Sema &S)
bool CheckBPFBuiltinFunctionCall (unsigned BuiltinID, CallExpr *TheCall)
void handlePreserveAIRecord (RecordDecl *RD)
void handlePreserveAccessIndexAttr (Decl *D, const ParsedAttr &AL)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 24 of file SemaBPF.h.
Constructor & Destructor Documentation
SemaBPF()
clang::SemaBPF::SemaBPF (Sema & S)
Definition at line 25 of file SemaBPF.cpp.
Member Function Documentation
CheckBPFBuiltinFunctionCall()
bool clang::SemaBPF::CheckBPFBuiltinFunctionCall (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 111 of file SemaBPF.cpp.
handlePreserveAccessIndexAttr()
void clang::SemaBPF::handlePreserveAccessIndexAttr (Decl * D, const ParsedAttr & AL)
Definition at line 187 of file SemaBPF.cpp.
References D, clang::SemaBase::getASTContext(), and handlePreserveAIRecord().
handlePreserveAIRecord()
void clang::SemaBPF::handlePreserveAIRecord (RecordDecl * RD)
Definition at line 175 of file SemaBPF.cpp.
References D, clang::DeclContext::decls(), and clang::SemaBase::getASTContext().
Referenced by handlePreserveAccessIndexAttr().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaBPF.h
lib/Sema/SemaBPF.cpp