clang: clang::OpenACCDefaultClause Class Reference
clang::OpenACCDefaultClause Class Reference
A 'default' clause, has the optional 'none' or 'present' argument.
#include "clang/AST/OpenACCClause.h"
Public Member Functions
OpenACCDefaultClauseKind getDefaultClauseKind () const
Public Member Functions inherited from clang::OpenACCClauseWithParams
SourceLocation getLParenLoc () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClause
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Static Public Member Functions
static OpenACCDefaultClause * Create (const ASTContext &C, OpenACCDefaultClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Static Public Member Functions inherited from clang::OpenACCClause
static bool classof (const OpenACCClause *)
Protected Member Functions
OpenACCDefaultClause (OpenACCDefaultClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClauseWithParams
OpenACCClauseWithParams (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClause
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Friends
class ASTReaderStmt
class ASTWriterStmt
Additional Inherited Members
Public Types inherited from clang::OpenACCClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Detailed Description
A 'default' clause, has the optional 'none' or 'present' argument.
Definition at line 74 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCDefaultClause()
clang::OpenACCDefaultClause::OpenACCDefaultClause (OpenACCDefaultClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline protected
Definition at line 81 of file OpenACCClause.h.
References clang::Default, clang::None, and clang::Present.
Referenced by Create().
Member Function Documentation
Create()
OpenACCDefaultClause * OpenACCDefaultClause::Create (const ASTContext & C, OpenACCDefaultClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc) static
Definition at line 20 of file OpenACCClause.cpp.
References OpenACCDefaultClause().
Referenced by clang::SemaOpenACC::ActOnClause(), and clang::ASTRecordReader::readOpenACCClause().
getDefaultClauseKind()
OpenACCDefaultClauseKind clang::OpenACCDefaultClause::getDefaultClauseKind () const inline
Definition at line 92 of file OpenACCClause.h.
Friends And Related Function Documentation
ASTReaderStmt
friend class ASTReaderStmt friend
Definition at line 75 of file OpenACCClause.h.
ASTWriterStmt
friend class ASTWriterStmt friend
Definition at line 76 of file OpenACCClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenACCClause.h
lib/AST/OpenACCClause.cpp