clang: clang::comments::CommentVisitorBase< Ptr, ImplClass, RetTy, ParamTys > Class Template Reference
clang::comments::CommentVisitorBase< Ptr, ImplClass, RetTy, ParamTys > Class Template Reference
#include "clang/AST/CommentVisitor.h"
Public Member Functions
RetTy visit (PTR(Comment) C, ParamTys... P)
RetTy visitComment (PTR(Comment) C, ParamTys... P)
Detailed Description
template<template< typename > class Ptr, typename ImplClass, typename RetTy = void, class... ParamTys>
class clang::comments::CommentVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
Definition at line 20 of file CommentVisitor.h.
Member Function Documentation
visit()
template<template< typename > class Ptr, typename ImplClass , typename RetTy = void, class... ParamTys> RetTy clang::comments::CommentVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::visit (PTR(Comment) C, ParamTys... P) inline
Definition at line 27 of file CommentVisitor.h.
Referenced by clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), clang::JSONNodeDumper::Visit(), and clang::TextNodeDumper::Visit().
visitComment()
template<template< typename > class Ptr, typename ImplClass , typename RetTy = void, class... ParamTys> RetTy clang::comments::CommentVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::visitComment (PTR(Comment) C, ParamTys... P) inline
Definition at line 52 of file CommentVisitor.h.
The documentation for this class was generated from the following file:
include/clang/AST/CommentVisitor.h