clang: clang::CodeGen::LValueBaseInfo Class Reference
clang::CodeGen::LValueBaseInfo Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGValue.h"
Public Member Functions
LValueBaseInfo (AlignmentSource Source=AlignmentSource::Type)
AlignmentSource getAlignmentSource () const
void setAlignmentSource (AlignmentSource Source)
void mergeForCast (const LValueBaseInfo &Info)
Detailed Description
Definition at line 154 of file CGValue.h.
Constructor & Destructor Documentation
LValueBaseInfo()
clang::CodeGen::LValueBaseInfo::LValueBaseInfo (AlignmentSource Source = AlignmentSource::Type) inline explicit
Definition at line 158 of file CGValue.h.
Member Function Documentation
getAlignmentSource()
AlignmentSource clang::CodeGen::LValueBaseInfo::getAlignmentSource () const inline
Definition at line 160 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitLValueForFieldInitialization(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), and mergeForCast().
mergeForCast()
void clang::CodeGen::LValueBaseInfo::mergeForCast (const LValueBaseInfo & Info) inline
Definition at line 163 of file CGValue.h.
References getAlignmentSource(), and setAlignmentSource().
Referenced by emitOMPArraySectionBase(), and clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment().
setAlignmentSource()
void clang::CodeGen::LValueBaseInfo::setAlignmentSource (AlignmentSource Source) inline
Definition at line 161 of file CGValue.h.
Referenced by mergeForCast().
The documentation for this class was generated from the following file:
lib/CodeGen/CGValue.h