clang: clang::NestedNameSpecifierLoc Class Reference
clang::NestedNameSpecifierLoc Class Reference
A C++ nested-name-specifier augmented with source location information.
#include "clang/AST/NestedNameSpecifier.h"
Public Member Functions
NestedNameSpecifierLoc ()=default
Construct an empty nested-name-specifier.
NestedNameSpecifierLoc (NestedNameSpecifier *Qualifier, void *Data)
Construct a nested-name-specifier with source location information from.
operator bool () const
Evaluates true when this nested-name-specifier location is non-empty.
bool hasQualifier () const
Evaluates true when this nested-name-specifier location is empty.
NestedNameSpecifier * getNestedNameSpecifier () const
Retrieve the nested-name-specifier to which this instance refers.
void * getOpaqueData () const
Retrieve the opaque pointer that refers to source-location data.
SourceRange getSourceRange () const LLVM_READONLY
Retrieve the source range covering the entirety of this nested-name-specifier.
SourceRange getLocalSourceRange () const
Retrieve the source range covering just the last part of this nested-name-specifier, not including the prefix.
SourceLocation getBeginLoc () const
Retrieve the location of the beginning of this nested-name-specifier.
SourceLocation getEndLoc () const
Retrieve the location of the end of this nested-name-specifier.
SourceLocation getLocalBeginLoc () const
Retrieve the location of the beginning of this component of the nested-name-specifier.
SourceLocation getLocalEndLoc () const
Retrieve the location of the end of this component of the nested-name-specifier.
NestedNameSpecifierLoc getPrefix () const
Return the prefix of this nested-name-specifier.
TypeLoc getTypeLoc () const
For a nested-name-specifier that refers to a type, retrieve the type with source-location information.
unsigned getDataLength () const
Determines the data length for the entire nested-name-specifier.
Friends
bool operator== (NestedNameSpecifierLoc X, NestedNameSpecifierLoc Y)
bool operator!= (NestedNameSpecifierLoc X, NestedNameSpecifierLoc Y)
Detailed Description
A C++ nested-name-specifier augmented with source location information.
Definition at line 243 of file NestedNameSpecifier.h.
Constructor & Destructor Documentation
NestedNameSpecifierLoc() [1/2]
clang::NestedNameSpecifierLoc::NestedNameSpecifierLoc () default
Construct an empty nested-name-specifier.
Referenced by getPrefix().
NestedNameSpecifierLoc() [2/2]
clang::NestedNameSpecifierLoc::NestedNameSpecifierLoc (NestedNameSpecifier * Qualifier, void * Data) inline
Construct a nested-name-specifier with source location information from.
Definition at line 261 of file NestedNameSpecifier.h.
References Data.
Member Function Documentation
getBeginLoc()
SourceLocation clang::NestedNameSpecifierLoc::getBeginLoc () const inline
Retrieve the location of the beginning of this nested-name-specifier.
Definition at line 299 of file NestedNameSpecifier.h.
References clang::SourceRange::getBegin(), and getSourceRange().
Referenced by clang::MSPropertyRefExpr::getBeginLoc(), clang::DeclRefExpr::getBeginLoc(), clang::MemberExpr::getBeginLoc(), clang::DependentScopeDeclRefExpr::getBeginLoc(), clang::CXXDependentScopeMemberExpr::getBeginLoc(), clang::AutoTypeLoc::getLocalSourceRange(), clang::UsingDecl::getSourceRange(), clang::UnresolvedUsingValueDecl::getSourceRange(), clang::Sema::SubstNestedNameSpecifierLoc(), and clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc().
getDataLength()
unsigned clang::NestedNameSpecifierLoc::getDataLength () const inline
Determines the data length for the entire nested-name-specifier.
Definition at line 340 of file NestedNameSpecifier.h.
References getDataLength().
Referenced by getDataLength(), getLocalSourceRange(), and getTypeLoc().
getEndLoc()
SourceLocation clang::NestedNameSpecifierLoc::getEndLoc () const inline
Retrieve the location of the end of this nested-name-specifier.
Definition at line 305 of file NestedNameSpecifier.h.
References clang::SourceRange::getEnd(), and getSourceRange().
Referenced by clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc().
getLocalBeginLoc()
SourceLocation clang::NestedNameSpecifierLoc::getLocalBeginLoc () const inline
Retrieve the location of the beginning of this component of the nested-name-specifier.
Definition at line 311 of file NestedNameSpecifier.h.
References clang::SourceRange::getBegin(), and getLocalSourceRange().
Referenced by clang::CXXScopeSpec::getLastQualifierNameLoc(), clang::index::IndexingContext::indexNestedNameSpecifierLoc(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), and clang::tooling::RecursiveSymbolVisitor< T >::TraverseNestedNameSpecifierLoc().
getLocalEndLoc()
SourceLocation clang::NestedNameSpecifierLoc::getLocalEndLoc () const inline
Retrieve the location of the end of this component of the nested-name-specifier.
Definition at line 317 of file NestedNameSpecifier.h.
References clang::SourceRange::getEnd(), and getLocalSourceRange().
Referenced by clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), and clang::tooling::RecursiveSymbolVisitor< T >::TraverseNestedNameSpecifierLoc().
getLocalSourceRange()
SourceRange NestedNameSpecifierLoc::getLocalSourceRange () const
Retrieve the source range covering just the last part of this nested-name-specifier, not including the prefix.
For example, if this instance refers to a nested-name-specifier ::std::vector<int>::, the returned source range would cover from "vector" to the last '::'.
Definition at line 422 of file NestedNameSpecifier.cpp.
References clang::TypeLoc::getBeginLoc(), getDataLength(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, LoadPointer(), LoadSourceLocation(), clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, Offset, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
Referenced by clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), getLocalBeginLoc(), getLocalEndLoc(), and getSourceRange().
getNestedNameSpecifier()
NestedNameSpecifier* clang::NestedNameSpecifierLoc::getNestedNameSpecifier () const inline
Retrieve the nested-name-specifier to which this instance refers.
Definition at line 274 of file NestedNameSpecifier.h.
Referenced by clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::Sema::CheckTypenameType(), llvm::DenseMapInfo< clang::NestedNameSpecifierLoc >::getHashValue(), clang::TagDecl::getQualifier(), clang::UsingDirectiveDecl::getQualifier(), clang::NamespaceAliasDecl::getQualifier(), clang::UsingDecl::getQualifier(), clang::UsingEnumDecl::getQualifier(), clang::UnresolvedUsingValueDecl::getQualifier(), clang::UnresolvedUsingTypenameDecl::getQualifier(), clang::DeclRefExpr::getQualifier(), clang::MemberExpr::getQualifier(), clang::CXXPseudoDestructorExpr::getQualifier(), clang::OverloadExpr::getQualifier(), clang::DependentScopeDeclRefExpr::getQualifier(), clang::CXXDependentScopeMemberExpr::getQualifier(), clang::index::IndexingContext::indexNestedNameSpecifierLoc(), isEnableIf(), clang::ConceptReference::print(), clang::TreeTransform< Derived >::RebuildDependentNameType(), clang::TreeTransform< Derived >::RebuildElaboratedType(), clang::ElaboratedTypeLoc::setQualifierLoc(), clang::DependentNameTypeLoc::setQualifierLoc(), clang::DependentTemplateSpecializationTypeLoc::setQualifierLoc(), clang::TemplateArgumentLocInfo::TemplateArgumentLocInfo(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), clang::RecursiveASTVisitor< Derived >::TraverseNestedNameSpecifierLoc(), and clang::tooling::RecursiveSymbolVisitor< T >::TraverseNestedNameSpecifierLoc().
getOpaqueData()
void* clang::NestedNameSpecifierLoc::getOpaqueData () const inline
Retrieve the opaque pointer that refers to source-location data.
Definition at line 279 of file NestedNameSpecifier.h.
References Data.
Referenced by llvm::DenseMapInfo< clang::NestedNameSpecifierLoc >::getHashValue(), clang::ElaboratedTypeLoc::setQualifierLoc(), clang::DependentNameTypeLoc::setQualifierLoc(), clang::DependentTemplateSpecializationTypeLoc::setQualifierLoc(), clang::TemplateArgumentLocInfo::TemplateArgumentLocInfo(), and clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc().
getPrefix()
NestedNameSpecifierLoc clang::NestedNameSpecifierLoc::getPrefix () const inline
Return the prefix of this nested-name-specifier.
For example, if this instance refers to a nested-name-specifier ::std::vector<int>::, the prefix is ::std::. Note that the returned prefix may be empty, if this is the first component of the nested-name-specifier.
Definition at line 327 of file NestedNameSpecifier.h.
References Data, and NestedNameSpecifierLoc().
Referenced by clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTImporter::Import(), clang::index::IndexingContext::indexNestedNameSpecifierLoc(), and clang::RecursiveASTVisitor< Derived >::TraverseNestedNameSpecifierLoc().
getSourceRange()
SourceRange NestedNameSpecifierLoc::getSourceRange () const
Retrieve the source range covering the entirety of this nested-name-specifier.
For example, if this instance refers to a nested-name-specifier ::std::vector<int>::, the returned source range would cover from the initial '::' to the last '::'.
Definition at line 410 of file NestedNameSpecifier.cpp.
References clang::First, and getLocalSourceRange().
Referenced by getBeginLoc(), getEndLoc(), clang::ElaboratedTypeLoc::getLocalSourceRange(), clang::NestedNameSpecifierLocBuilder::getSourceRange(), clang::TreeTransform< Derived >::RebuildDependentNameType(), and clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization().
getTypeLoc()
TypeLoc NestedNameSpecifierLoc::getTypeLoc () const
For a nested-name-specifier that refers to a type, retrieve the type with source-location information.
Definition at line 453 of file NestedNameSpecifier.cpp.
References getDataLength(), LoadPointer(), Offset, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
Referenced by clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::index::IndexingContext::indexNestedNameSpecifierLoc(), isEnableIf(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), and clang::RecursiveASTVisitor< Derived >::TraverseNestedNameSpecifierLoc().
hasQualifier()
bool clang::NestedNameSpecifierLoc::hasQualifier () const inline
Evaluates true when this nested-name-specifier location is empty.
Definition at line 270 of file NestedNameSpecifier.h.
Referenced by clang::CXXPseudoDestructorExpr::hasQualifier(), clang::ElaboratedTypeLoc::setQualifierLoc(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
operator bool()
clang::NestedNameSpecifierLoc::operator bool () const inline explicit
Evaluates true when this nested-name-specifier location is non-empty.
Definition at line 266 of file NestedNameSpecifier.h.
Friends And Related Function Documentation
operator!=
bool operator!= (NestedNameSpecifierLoc X, NestedNameSpecifierLoc Y) friend
Definition at line 347 of file NestedNameSpecifier.h.
operator==
bool operator== (NestedNameSpecifierLoc X, NestedNameSpecifierLoc Y) friend
Definition at line 342 of file NestedNameSpecifier.h.
The documentation for this class was generated from the following files:
include/clang/AST/NestedNameSpecifier.h
lib/AST/NestedNameSpecifier.cpp