clang: clang::GCCAsmStmt::AsmStringPiece Class Reference
clang::GCCAsmStmt::AsmStringPiece Class Reference
AsmStringPiece - this is part of a decomposed asm string specification (for use with the AnalyzeAsmString function below).
#include "clang/AST/Stmt.h"
Public Types
enum Kind { String, Operand }
Public Member Functions
AsmStringPiece (const std::string &S)
AsmStringPiece (unsigned OpNo, const std::string &S, SourceLocation Begin, SourceLocation End)
bool isString () const
bool isOperand () const
const std::string & getString () const
unsigned getOperandNo () const
CharSourceRange getRange () const
char getModifier () const
getModifier - Get the modifier for this operand, if present.
Detailed Description
AsmStringPiece - this is part of a decomposed asm string specification (for use with the AnalyzeAsmString function below).
An asm string is considered to be a concatenation of these parts.
Definition at line 3042 of file Stmt.h.
Member Enumeration Documentation
Kind
enum clang::GCCAsmStmt::AsmStringPiece::Kind
Enumerator
String
Operand
Definition at line 3044 of file Stmt.h.
Constructor & Destructor Documentation
AsmStringPiece() [1/2]
clang::GCCAsmStmt::AsmStringPiece::AsmStringPiece (const std::string & S) inline
Definition at line 3058 of file Stmt.h.
AsmStringPiece() [2/2]
clang::GCCAsmStmt::AsmStringPiece::AsmStringPiece (unsigned OpNo, const std::string & S, SourceLocation Begin, SourceLocation End) inline
Definition at line 3059 of file Stmt.h.
Member Function Documentation
getModifier()
char GCCAsmStmt::AsmStringPiece::getModifier () const
getModifier - Get the modifier for this operand, if present.
This returns '\0' if there was no modifier.
Definition at line 491 of file Stmt.cpp.
References clang::isLetter(), and isOperand().
Referenced by clang::Sema::ActOnGCCAsmStmt().
getOperandNo()
unsigned clang::GCCAsmStmt::AsmStringPiece::getOperandNo () const inline
Definition at line 3069 of file Stmt.h.
References isOperand().
Referenced by clang::Sema::ActOnGCCAsmStmt(), and isOperandMentioned().
getRange()
CharSourceRange clang::GCCAsmStmt::AsmStringPiece::getRange () const inline
Definition at line 3074 of file Stmt.h.
References isOperand().
Referenced by clang::Sema::ActOnGCCAsmStmt().
getString()
const std::string& clang::GCCAsmStmt::AsmStringPiece::getString () const inline
Definition at line 3067 of file Stmt.h.
Referenced by clang::Sema::ActOnGCCAsmStmt().
isOperand()
bool clang::GCCAsmStmt::AsmStringPiece::isOperand () const inline
Definition at line 3065 of file Stmt.h.
References Operand.
Referenced by clang::Sema::ActOnGCCAsmStmt(), getModifier(), getOperandNo(), getRange(), and isOperandMentioned().
isString()
bool clang::GCCAsmStmt::AsmStringPiece::isString () const inline
Definition at line 3064 of file Stmt.h.
References String.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp