clang: clang::api_notes::CommonEntityInfo Class Reference
clang::api_notes::CommonEntityInfo Class Reference
Describes API notes data for any entity.
#include "clang/APINotes/Types.h"
Public Member Functions
CommonEntityInfo ()
llvm::Optional< bool > isSwiftPrivate () const
void setSwiftPrivate (llvm::Optional< bool > Private)
CommonEntityInfo & operator|= (const CommonEntityInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Attributes
std::string UnavailableMsg
Message to use when this entity is unavailable.
unsigned Unavailable: 1
Whether this entity is marked unavailable.
unsigned UnavailableInSwift: 1
Whether this entity is marked unavailable in Swift.
std::string SwiftName
Swift name of this entity.
Friends
bool operator== (const CommonEntityInfo &, const CommonEntityInfo &)
Detailed Description
Describes API notes data for any entity.
This is used as the base of all API notes.
Definition at line 47 of file Types.h.
Constructor & Destructor Documentation
CommonEntityInfo()
clang::api_notes::CommonEntityInfo::CommonEntityInfo () inline
Definition at line 69 of file Types.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::api_notes::CommonEntityInfo::dump (llvm::raw_ostream & OS) const
Definition at line 14 of file APINotesTypes.cpp.
References SwiftName, Unavailable, UnavailableInSwift, and UnavailableMsg.
Referenced by clang::api_notes::CommonTypeInfo::dump(), clang::api_notes::VariableInfo::dump(), and clang::api_notes::FunctionInfo::dump().
isSwiftPrivate()
llvm::Optional<bool> clang::api_notes::CommonEntityInfo::isSwiftPrivate () const inline
Definition at line 73 of file Types.h.
Referenced by operator|=().
operator|=()
CommonEntityInfo& clang::api_notes::CommonEntityInfo::operator|= (const CommonEntityInfo & RHS) inline
Definition at line 85 of file Types.h.
References isSwiftPrivate(), setSwiftPrivate(), SwiftName, Unavailable, UnavailableInSwift, and UnavailableMsg.
setSwiftPrivate()
void clang::api_notes::CommonEntityInfo::setSwiftPrivate (llvm::Optional< bool > Private) inline
Definition at line 78 of file Types.h.
Referenced by operator|=().
Friends And Related Function Documentation
operator==
bool operator== (const CommonEntityInfo & LHS, const CommonEntityInfo & RHS) friend
Definition at line 111 of file Types.h.
Member Data Documentation
SwiftName
std::string clang::api_notes::CommonEntityInfo::SwiftName
Swift name of this entity.
Definition at line 67 of file Types.h.
Referenced by dump(), clang::api_notes::operator==(), and operator|=().
Unavailable
unsigned clang::api_notes::CommonEntityInfo::Unavailable
Whether this entity is marked unavailable.
Definition at line 53 of file Types.h.
Referenced by dump(), clang::api_notes::operator==(), and operator|=().
UnavailableInSwift
unsigned clang::api_notes::CommonEntityInfo::UnavailableInSwift
Whether this entity is marked unavailable in Swift.
Definition at line 56 of file Types.h.
Referenced by dump(), clang::api_notes::operator==(), and operator|=().
UnavailableMsg
std::string clang::api_notes::CommonEntityInfo::UnavailableMsg
Message to use when this entity is unavailable.
Definition at line 50 of file Types.h.
Referenced by dump(), clang::api_notes::operator==(), and operator|=().
The documentation for this class was generated from the following files:
include/clang/APINotes/Types.h
lib/APINotes/APINotesTypes.cpp