clang: clang::SemaObjC::GlobalMethodPool Class Reference
clang::SemaObjC::GlobalMethodPool Class Reference
#include "clang/Sema/SemaObjC.h"
Public Types
using Lists = std::pair< ObjCMethodList, ObjCMethodList >
using iterator = llvm::DenseMap< Selector, Lists >::iterator
Public Member Functions
iterator begin ()
iterator end ()
iterator find (Selector Sel)
std::pair< iterator, bool > insert (std::pair< Selector, Lists > &&Val)
int count (Selector Sel) const
bool empty () const
Detailed Description
Definition at line 209 of file SemaObjC.h.
Member Typedef Documentation
iterator
using clang::SemaObjC::GlobalMethodPool::iterator = llvm::DenseMap<Selector, Lists>::iterator
Definition at line 212 of file SemaObjC.h.
Lists
using clang::SemaObjC::GlobalMethodPool::Lists = std::pair<ObjCMethodList, ObjCMethodList>
Definition at line 211 of file SemaObjC.h.
Member Function Documentation
begin()
iterator clang::SemaObjC::GlobalMethodPool::begin () inline
Definition at line 213 of file SemaObjC.h.
Referenced by clang::SemaObjC::SelectorsForTypoCorrection().
count()
int clang::SemaObjC::GlobalMethodPool::count (Selector Sel) const inline
Definition at line 219 of file SemaObjC.h.
empty()
bool clang::SemaObjC::GlobalMethodPool::empty () const inline
Definition at line 220 of file SemaObjC.h.
end()
iterator clang::SemaObjC::GlobalMethodPool::end () inline
Definition at line 214 of file SemaObjC.h.
Referenced by clang::SemaObjC::AreMultipleMethodsInGlobalPool(), clang::SemaObjC::CollectMultipleMethodsInGlobalPool(), clang::SemaObjC::LookupImplementedMethodInGlobalPool(), and clang::SemaObjC::SelectorsForTypoCorrection().
find()
iterator clang::SemaObjC::GlobalMethodPool::find (Selector Sel) inline
Definition at line 215 of file SemaObjC.h.
Referenced by clang::SemaObjC::AreMultipleMethodsInGlobalPool(), clang::SemaObjC::CollectMultipleMethodsInGlobalPool(), and clang::SemaObjC::LookupImplementedMethodInGlobalPool().
insert()
std::pair<iterator, bool> clang::SemaObjC::GlobalMethodPool::insert (std::pair< Selector, Lists > && Val) inline
Definition at line 216 of file SemaObjC.h.
The documentation for this class was generated from the following file:
include/clang/Sema/SemaObjC.h