clang: clang::CodeGen::CGDebugInfo Class Reference
clang::CodeGen::CGDebugInfo Class Reference
This class gathers all debug information during compilation and is responsible for emitting to llvm globals or pass directly to the backend.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGDebugInfo.h"
Public Member Functions
CGDebugInfo (CodeGenModule &CGM)
~CGDebugInfo ()
void finalize ()
std::string remapDIPath (StringRef) const
Remap a given path with the current debug prefix map.
void registerVLASizeExpression (QualType Ty, llvm::Metadata *SizeExpr)
Register VLA size expression debug node with the qualified type.
void setLocation (SourceLocation Loc)
Update the current source location.
SourceLocation getLocation () const
Return the current source location.
void setInlinedAt (llvm::MDNode *InlinedAt)
Update the current inline scope.
llvm::MDNode * getInlinedAt () const
llvm::DebugLoc SourceLocToDebugLoc (SourceLocation Loc)
void EmitLocation (CGBuilderTy &Builder, SourceLocation Loc)
Emit metadata to indicate a change in line/column information in the source file.
QualType getFunctionType (const FunctionDecl *FD, QualType RetTy, const SmallVectorImpl< const VarDecl * > &Args)
void emitFunctionStart (GlobalDecl GD, SourceLocation Loc, SourceLocation ScopeLoc, QualType FnType, llvm::Function *Fn, bool CurFnIsThunk)
Emit a call to llvm.dbg.function.start to indicate start of a new function.
void EmitInlineFunctionStart (CGBuilderTy &Builder, GlobalDecl GD)
Start a new scope for an inlined function.
void EmitInlineFunctionEnd (CGBuilderTy &Builder)
End an inlined function scope.
void EmitFunctionDecl (GlobalDecl GD, SourceLocation Loc, QualType FnType, llvm::Function *Fn=nullptr)
Emit debug info for a function declaration.
void EmitFuncDeclForCallSite (llvm::CallBase *CallOrInvoke, QualType CalleeType, const FunctionDecl *CalleeDecl)
Emit debug info for an extern function being called.
void EmitFunctionEnd (CGBuilderTy &Builder, llvm::Function *Fn)
Constructs the debug code for exiting a function.
void EmitLexicalBlockStart (CGBuilderTy &Builder, SourceLocation Loc)
Emit metadata to indicate the beginning of a new lexical block and push the block onto the stack.
void EmitLexicalBlockEnd (CGBuilderTy &Builder, SourceLocation Loc)
Emit metadata to indicate the end of a new lexical block and pop the current block.
llvm::DILocalVariable * EmitDeclareOfAutoVariable (const VarDecl *Decl, llvm::Value *AI, CGBuilderTy &Builder, const bool UsePointerValue=false)
Emit call to llvm.dbg.declare for an automatic variable declaration.
void EmitLabel (const LabelDecl *D, CGBuilderTy &Builder)
Emit call to llvm.dbg.label for an label.
void EmitDeclareOfBlockDeclRefVariable (const VarDecl *variable, llvm::Value *storage, CGBuilderTy &Builder, const CGBlockInfo &blockInfo, llvm::Instruction *InsertPoint=nullptr)
Emit call to llvm.dbg.declare for an imported variable declaration in a block.
llvm::DILocalVariable * EmitDeclareOfArgVariable (const VarDecl *Decl, llvm::Value *AI, unsigned ArgNo, CGBuilderTy &Builder)
Emit call to llvm.dbg.declare for an argument variable declaration.
void EmitDeclareOfBlockLiteralArgVariable (const CGBlockInfo &block, StringRef Name, unsigned ArgNo, llvm::AllocaInst *LocalAddr, CGBuilderTy &Builder)
Emit call to llvm.dbg.declare for the block-literal argument to a block invocation function.
void EmitGlobalVariable (llvm::GlobalVariable *GV, const VarDecl *Decl)
Emit information about a global variable.
void EmitGlobalVariable (const ValueDecl *VD, const APValue &Init)
Emit a constant global variable's debug info.
void EmitExternalVariable (llvm::GlobalVariable *GV, const VarDecl *Decl)
Emit information about an external variable.
void EmitUsingDirective (const UsingDirectiveDecl &UD)
Emit C++ using directive.
void EmitExplicitCastType (QualType Ty)
Emit the type explicitly casted to.
void EmitAndRetainType (QualType Ty)
Emit the type even if it might not be used.
void EmitUsingShadowDecl (const UsingShadowDecl &USD)
Emit a shadow decl brought in by a using or using-enum.
void EmitUsingDecl (const UsingDecl &UD)
Emit C++ using declaration.
void EmitUsingEnumDecl (const UsingEnumDecl &UD)
Emit C++ using-enum declaration.
void EmitImportDecl (const ImportDecl &ID)
Emit an @import declaration.
llvm::DIImportedEntity * EmitNamespaceAlias (const NamespaceAliasDecl &NA)
Emit C++ namespace alias.
llvm::DIType * getOrCreateRecordType (QualType Ty, SourceLocation L)
Emit record type's standalone debug info.
llvm::DIType * getOrCreateInterfaceType (QualType Ty, SourceLocation Loc)
Emit an Objective-C interface type standalone debug info.
llvm::DIType * getOrCreateStandaloneType (QualType Ty, SourceLocation Loc)
Emit standalone debug info for a type.
void addHeapAllocSiteMetadata (llvm::CallBase *CallSite, QualType AllocatedTy, SourceLocation Loc)
Add heapallocsite metadata for MSAllocator calls.
void completeType (const EnumDecl *ED)
void completeType (const RecordDecl *RD)
void completeRequiredType (const RecordDecl *RD)
void completeClassData (const RecordDecl *RD)
void completeClass (const RecordDecl *RD)
void completeTemplateDefinition (const ClassTemplateSpecializationDecl &SD)
void completeUnusedClass (const CXXRecordDecl &D)
llvm::DIMacro * CreateMacro (llvm::DIMacroFile *Parent, unsigned MType, SourceLocation LineLoc, StringRef Name, StringRef Value)
Create debug info for a macro defined by a #define directive or a macro undefined by a #undef directive.
llvm::DIMacroFile * CreateTempMacroFile (llvm::DIMacroFile *Parent, SourceLocation LineLoc, SourceLocation FileLoc)
Create debug info for a file referenced by an include directive.
Param2DILocTy & getParamDbgMappings ()
ParamDecl2StmtTy & getCoroutineParameterMappings ()
void setDwoId (uint64_t Signature)
Module debugging: Support for building PCMs.
void setModuleMap (ModuleMap &MMap)
When generating debug information for a clang module or precompiled header, this module map will be used to determine the module of origin of each Decl.
void setPCHDescriptor (ASTSourceDescriptor PCH)
When generating debug information for a clang module or precompiled header, this module map will be used to determine the module of origin of each Decl.
Friends
class ApplyDebugLocation
class SaveAndRestoreLocation
Detailed Description
This class gathers all debug information during compilation and is responsible for emitting to llvm globals or pass directly to the backend.
Definition at line 55 of file CGDebugInfo.h.
Constructor & Destructor Documentation
CGDebugInfo()
CGDebugInfo::CGDebugInfo (CodeGenModule & CGM)
Definition at line 67 of file CGDebugInfo.cpp.
References clang::CodeGenOptions::DebugPrefixMap, and clang::CodeGen::CodeGenModule::getCodeGenOpts().
~CGDebugInfo()
CGDebugInfo::~CGDebugInfo ()
Definition at line 76 of file CGDebugInfo.cpp.
Member Function Documentation
addHeapAllocSiteMetadata()
void CGDebugInfo::addHeapAllocSiteMetadata (llvm::CallBase * CallSite, QualType AllocatedTy, SourceLocation Loc)
Add heapallocsite metadata for MSAllocator calls.
Definition at line 2344 of file CGDebugInfo.cpp.
References clang::codegenoptions::DebugLineTablesOnly, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::Type::isVoidType(), and clang::transformer::node().
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), and clang::CodeGen::CodeGenFunction::EmitCXXNewExpr().
completeClass()
void CGDebugInfo::completeClass (const RecordDecl * RD)
Definition at line 2434 of file CGDebugInfo.cpp.
References clang::Type::castAs(), clang::codegenoptions::DebugLineTablesOnly, clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getContext(), and clang::ASTContext::getRecordType().
Referenced by completeClassData().
completeClassData()
void CGDebugInfo::completeClassData (const RecordDecl * RD)
Definition at line 2420 of file CGDebugInfo.cpp.
References completeClass(), clang::RecordDecl::getDefinition(), clang::CodeGen::CodeGenModule::getVTableLinkage(), isClassOrMethodDLLImport(), and isDefinedInClangModule().
Referenced by completeRequiredType(), and completeUnusedClass().
completeRequiredType()
void CGDebugInfo::completeRequiredType (const RecordDecl * RD)
Definition at line 2533 of file CGDebugInfo.cpp.
References completeClassData(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::ASTContext::getRecordType(), and shouldOmitDefinition().
Referenced by completeType().
completeTemplateDefinition()
void CGDebugInfo::completeTemplateDefinition (const ClassTemplateSpecializationDecl & SD)
Definition at line 3341 of file CGDebugInfo.cpp.
References completeUnusedClass().
completeType() [1/2]
void CGDebugInfo::completeType (const EnumDecl * ED)
Definition at line 2359 of file CGDebugInfo.cpp.
References clang::Type::castAs(), clang::codegenoptions::DebugLineTablesOnly, clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getContext(), and clang::ASTContext::getEnumType().
completeType() [2/2]
void CGDebugInfo::completeType (const RecordDecl * RD)
Definition at line 2372 of file CGDebugInfo.cpp.
References completeRequiredType(), clang::CodeGen::CodeGenModule::getLangOpts(), and clang::codegenoptions::LimitedDebugInfo.
completeUnusedClass()
void CGDebugInfo::completeUnusedClass (const CXXRecordDecl & D)
Definition at line 3346 of file CGDebugInfo.cpp.
References completeClassData(), clang::codegenoptions::DebugLineTablesOnly, clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getContext(), and clang::ASTContext::getRecordType().
Referenced by completeTemplateDefinition().
CreateMacro()
llvm::DIMacro * CGDebugInfo::CreateMacro (llvm::DIMacroFile * Parent, unsigned MType, SourceLocation LineLoc, StringRef Name, StringRef Value)
Create debug info for a macro defined by a #define directive or a macro undefined by a #undef directive.
Definition at line 3243 of file CGDebugInfo.cpp.
Referenced by clang::MacroPPCallbacks::MacroUndefined().
CreateTempMacroFile()
llvm::DIMacroFile * CGDebugInfo::CreateTempMacroFile (llvm::DIMacroFile * Parent, SourceLocation LineLoc, SourceLocation FileLoc)
Create debug info for a file referenced by an include directive.
Definition at line 3250 of file CGDebugInfo.cpp.
References clang::SourceLocation::isInvalid(), Line, and Parent.
EmitAndRetainType()
void CGDebugInfo::EmitAndRetainType (QualType Ty)
Emit the type even if it might not be used.
Definition at line 5612 of file CGDebugInfo.cpp.
EmitDeclareOfArgVariable()
llvm::DILocalVariable * CGDebugInfo::EmitDeclareOfArgVariable (const VarDecl * Decl, llvm::Value * AI, unsigned ArgNo, CGBuilderTy & Builder)
Emit call to llvm.dbg.declare for an argument variable declaration.
Definition at line 4780 of file CGDebugInfo.cpp.
EmitDeclareOfAutoVariable()
llvm::DILocalVariable * CGDebugInfo::EmitDeclareOfAutoVariable (const VarDecl * Decl, llvm::Value * AI, CGBuilderTy & Builder, const bool UsePointerValue = false)
Emit call to llvm.dbg.declare for an automatic variable declaration.
Returns a pointer to the DILocalVariable associated with the llvm.dbg.declare, or nullptr otherwise.
Definition at line 4658 of file CGDebugInfo.cpp.
EmitDeclareOfBlockDeclRefVariable()
void CGDebugInfo::EmitDeclareOfBlockDeclRefVariable (const VarDecl * variable, llvm::Value * storage, CGBuilderTy & Builder, const CGBlockInfo & blockInfo, llvm::Instruction * InsertPoint = nullptr)
Emit call to llvm.dbg.declare for an imported variable declaration in a block.
Definition at line 4707 of file CGDebugInfo.cpp.
EmitDeclareOfBlockLiteralArgVariable()
void CGDebugInfo::EmitDeclareOfBlockLiteralArgVariable (const CGBlockInfo & block, StringRef Name, unsigned ArgNo, llvm::AllocaInst * LocalAddr, CGBuilderTy & Builder)
Emit call to llvm.dbg.declare for the block-literal argument to a block invocation function.
Definition at line 4834 of file CGDebugInfo.cpp.
EmitExplicitCastType()
void CGDebugInfo::EmitExplicitCastType (QualType Ty)
Emit the type explicitly casted to.
Definition at line 5606 of file CGDebugInfo.cpp.
EmitExternalVariable()
void CGDebugInfo::EmitExternalVariable (llvm::GlobalVariable * GV, const VarDecl * Decl)
Emit information about an external variable.
Definition at line 5382 of file CGDebugInfo.cpp.
References getDeclAlignIfRequired(), clang::Decl::getLocation(), and clang::Decl::hasAttr().
EmitFuncDeclForCallSite()
void CGDebugInfo::EmitFuncDeclForCallSite (llvm::CallBase * CallOrInvoke, QualType CalleeType, const FunctionDecl * CalleeDecl)
Emit debug info for an extern function being called.
This is needed for call site debug info.
Definition at line 4188 of file CGDebugInfo.cpp.
References EmitFunctionDecl(), clang::FunctionDecl::getBuiltinID(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::Decl::getLocation(), clang::Decl::hasAttr(), clang::FunctionDecl::isInlined(), clang::NamedDecl::isReserved(), clang::FunctionDecl::isStatic(), and clang::NotReserved.
EmitFunctionDecl()
void CGDebugInfo::EmitFunctionDecl (GlobalDecl GD, SourceLocation Loc, QualType FnType, llvm::Function * Fn = nullptr)
Emit debug info for a function declaration.
Fn is set only when a declaration for a debug call site gets created.
Definition at line 4132 of file CGDebugInfo.cpp.
Referenced by EmitFuncDeclForCallSite().
EmitFunctionEnd()
void CGDebugInfo::EmitFunctionEnd (CGBuilderTy & Builder, llvm::Function * Fn)
Constructs the debug code for exiting a function.
Definition at line 4304 of file CGDebugInfo.cpp.
emitFunctionStart()
void CGDebugInfo::emitFunctionStart (GlobalDecl GD, SourceLocation Loc, SourceLocation ScopeLoc, QualType FnType, llvm::Function * Fn, bool CurFnIsThunk)
Emit a call to llvm.dbg.function.start to indicate start of a new function.
Parameters
Loc The location of the function header.
ScopeLoc The location of the function body.
Definition at line 4027 of file CGDebugInfo.cpp.
EmitGlobalVariable() [1/2]
void CGDebugInfo::EmitGlobalVariable (const ValueDecl * VD, const APValue & Init)
Emit a constant global variable's debug info.
Definition at line 5297 of file CGDebugInfo.cpp.
References getDeclAlignIfRequired(), clang::Decl::getLocation(), and clang::Decl::hasAttr().
EmitGlobalVariable() [2/2]
void CGDebugInfo::EmitGlobalVariable (llvm::GlobalVariable * GV, const VarDecl * Decl)
Emit information about a global variable.
Definition at line 5230 of file CGDebugInfo.cpp.
References clang::Type::castAs(), clang::cuda_constant, clang::cuda_shared, clang::VarDecl::getCanonicalDecl(), getDeclAlignIfRequired(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::RecordDecl::isAnonymousStructOrUnion(), and clang::Type::isUnionType().
Referenced by clang::CodeGen::CodeGenFunction::EmitStaticVarDecl().
EmitImportDecl()
void CGDebugInfo::EmitImportDecl (const ImportDecl & ID)
Emit an @import declaration.
Definition at line 5469 of file CGDebugInfo.cpp.
EmitInlineFunctionEnd()
void CGDebugInfo::EmitInlineFunctionEnd (CGBuilderTy & Builder)
End an inlined function scope.
Definition at line 4233 of file CGDebugInfo.cpp.
Referenced by clang::CodeGen::ApplyInlineDebugLocation::~ApplyInlineDebugLocation().
EmitInlineFunctionStart()
void CGDebugInfo::EmitInlineFunctionStart (CGBuilderTy & Builder, GlobalDecl GD)
Start a new scope for an inlined function.
Definition at line 4218 of file CGDebugInfo.cpp.
EmitLabel()
void CGDebugInfo::EmitLabel (const LabelDecl * D, CGBuilderTy & Builder)
Emit call to llvm.dbg.label for an label.
Definition at line 4672 of file CGDebugInfo.cpp.
EmitLexicalBlockEnd()
void CGDebugInfo::EmitLexicalBlockEnd (CGBuilderTy & Builder, SourceLocation Loc)
Emit metadata to indicate the end of a new lexical block and pop the current block.
Definition at line 4291 of file CGDebugInfo.cpp.
EmitLexicalBlockStart()
void CGDebugInfo::EmitLexicalBlockStart (CGBuilderTy & Builder, SourceLocation Loc)
Emit metadata to indicate the beginning of a new lexical block and push the block onto the stack.
Definition at line 4274 of file CGDebugInfo.cpp.
EmitLocation()
void CGDebugInfo::EmitLocation (CGBuilderTy & Builder, SourceLocation Loc)
Emit metadata to indicate a change in line/column information in the source file.
If the location is invalid, the previous location will be reused.
Definition at line 4239 of file CGDebugInfo.cpp.
EmitNamespaceAlias()
llvm::DIImportedEntity * CGDebugInfo::EmitNamespaceAlias (const NamespaceAliasDecl & NA)
Emit C++ namespace alias.
Definition at line 5483 of file CGDebugInfo.cpp.
References clang::NamespaceAliasDecl::getAliasedNamespace(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), and clang::NamedDecl::getName().
EmitUsingDecl()
void CGDebugInfo::EmitUsingDecl (const UsingDecl & UD)
Emit C++ using declaration.
Definition at line 5433 of file CGDebugInfo.cpp.
References clang::Type::getContainedAutoType(), clang::BaseUsingDecl::shadow_size(), and clang::BaseUsingDecl::shadows().
EmitUsingDirective()
void CGDebugInfo::EmitUsingDirective (const UsingDirectiveDecl & UD)
Emit C++ using directive.
Definition at line 5408 of file CGDebugInfo.cpp.
References clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::UsingDirectiveDecl::getNominatedNamespace(), clang::NamespaceDecl::isAnonymousNamespace(), and clang::SourceLocation::isValid().
EmitUsingEnumDecl()
void CGDebugInfo::EmitUsingEnumDecl (const UsingEnumDecl & UD)
Emit C++ using-enum declaration.
Definition at line 5458 of file CGDebugInfo.cpp.
References clang::BaseUsingDecl::shadow_size(), and clang::BaseUsingDecl::shadows().
EmitUsingShadowDecl()
void CGDebugInfo::EmitUsingShadowDecl (const UsingShadowDecl & USD)
Emit a shadow decl brought in by a using or using-enum.
Definition at line 5423 of file CGDebugInfo.cpp.
References clang::Decl::getDeclContext(), clang::Decl::getLocation(), clang::NamedDecl::getUnderlyingDecl(), and clang::Target.
finalize()
void CGDebugInfo::finalize ()
Definition at line 5529 of file CGDebugInfo.cpp.
References clang::QualType::getAsOpaquePtr(), and P.
getCoroutineParameterMappings()
ParamDecl2StmtTy& clang::CodeGen::CGDebugInfo::getCoroutineParameterMappings () inline
Definition at line 573 of file CGDebugInfo.h.
getFunctionType()
QualType CGDebugInfo::getFunctionType (const FunctionDecl * FD, QualType RetTy, const SmallVectorImpl< const VarDecl * > & Args)
Definition at line 4014 of file CGDebugInfo.cpp.
References clang::CC_C, clang::Type::getAs(), clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::getFunctionType(), and clang::ValueDecl::getType().
getInlinedAt()
llvm::MDNode* clang::CodeGen::CGDebugInfo::getInlinedAt () const inline
Returns
the current inline scope.
Definition at line 426 of file CGDebugInfo.h.
getLocation()
SourceLocation clang::CodeGen::CGDebugInfo::getLocation () const inline
Return the current source location.
This does not necessarily correspond to the IRBuilder's current DebugLoc.
Definition at line 419 of file CGDebugInfo.h.
getOrCreateInterfaceType()
llvm::DIType * CGDebugInfo::getOrCreateInterfaceType (QualType Ty, SourceLocation Loc)
Emit an Objective-C interface type standalone debug info.
Definition at line 2328 of file CGDebugInfo.cpp.
References getOrCreateStandaloneType().
getOrCreateRecordType()
llvm::DIType * CGDebugInfo::getOrCreateRecordType (QualType Ty, SourceLocation L)
Emit record type's standalone debug info.
Definition at line 2321 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGenOptions::hasReducedDebugInfo().
Referenced by clang::CodeGen::CodeGenFunction::EmitLValueForField().
getOrCreateStandaloneType()
llvm::DIType * CGDebugInfo::getOrCreateStandaloneType (QualType Ty, SourceLocation Loc)
Emit standalone debug info for a type.
Definition at line 2333 of file CGDebugInfo.cpp.
References clang::QualType::getAsOpaquePtr(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGenOptions::hasReducedDebugInfo(), and clang::QualType::isNull().
Referenced by emitArraySubscriptGEP(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), emitPreserveStructAccess(), and getOrCreateInterfaceType().
getParamDbgMappings()
Param2DILocTy& clang::CodeGen::CGDebugInfo::getParamDbgMappings () inline
Definition at line 572 of file CGDebugInfo.h.
registerVLASizeExpression()
void clang::CodeGen::CGDebugInfo::registerVLASizeExpression (QualType Ty, llvm::Metadata * SizeExpr) inline
Register VLA size expression debug node with the qualified type.
Definition at line 393 of file CGDebugInfo.h.
remapDIPath()
std::string CGDebugInfo::remapDIPath (StringRef Path) const
Remap a given path with the current debug prefix map.
Definition at line 456 of file CGDebugInfo.cpp.
References P.
setDwoId()
void CGDebugInfo::setDwoId (uint64_t Signature)
Module debugging: Support for building PCMs.
Set the main CU's DwoId field to Signature.
Definition at line 5524 of file CGDebugInfo.cpp.
setInlinedAt()
void clang::CodeGen::CGDebugInfo::setInlinedAt (llvm::MDNode * InlinedAt) inline
Update the current inline scope.
All subsequent calls to EmitLocation will create a location with this inlinedAt field.
Definition at line 423 of file CGDebugInfo.h.
setLocation()
void CGDebugInfo::setLocation (SourceLocation Loc)
Update the current source location.
If
loc is invalid it is ignored.
Definition at line 171 of file CGDebugInfo.cpp.
References clang::CodeGen::CodeGenModule::getContext(), clang::SourceManager::getExpansionLoc(), clang::ASTContext::getSourceManager(), clang::SourceLocation::isInvalid(), clang::PresumedLoc::isInvalid(), and SM.
Referenced by clang::CodeGen::CodeGenFunction::EmitStaticVarDecl().
setModuleMap()
void clang::CodeGen::CGDebugInfo::setModuleMap (ModuleMap & MMap) inline
When generating debug information for a clang module or precompiled header, this module map will be used to determine the module of origin of each Decl.
Definition at line 405 of file CGDebugInfo.h.
setPCHDescriptor()
void clang::CodeGen::CGDebugInfo::setPCHDescriptor (ASTSourceDescriptor PCH) inline
When generating debug information for a clang module or precompiled header, this module map will be used to determine the module of origin of each Decl.
Definition at line 410 of file CGDebugInfo.h.
References clang::PCH.
SourceLocToDebugLoc()
llvm::DebugLoc CGDebugInfo::SourceLocToDebugLoc (SourceLocation Loc)
Definition at line 5618 of file CGDebugInfo.cpp.
Friends And Related Function Documentation
ApplyDebugLocation
friend class ApplyDebugLocation friend
Definition at line 56 of file CGDebugInfo.h.
SaveAndRestoreLocation
friend class SaveAndRestoreLocation friend
Definition at line 57 of file CGDebugInfo.h.
The documentation for this class was generated from the following files:
lib/CodeGen/CGDebugInfo.h
lib/CodeGen/CGDebugInfo.cpp