clang: clang::interp::Floating Class Reference
clang::interp::Floating Class Reference final
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Floating.h"
Public Member Functions
Floating ()
Zero-initializes a Floating.
Floating (const APFloat &F)
const APFloat & getAPFloat () const
bool operator< (Floating RHS) const
bool operator> (Floating RHS) const
bool operator<= (Floating RHS) const
bool operator>= (Floating RHS) const
bool operator== (Floating RHS) const
bool operator!= (Floating RHS) const
Floating operator- () const
APFloat::opStatus convertToInteger (APSInt &Result) const
Floating toSemantics (const llvm::fltSemantics *Sem, llvm::RoundingMode RM) const
Floating toSemantics (const Floating &Other, llvm::RoundingMode RM) const
Convert this Floating to one with the same semantics as \Other.
APSInt toAPSInt (unsigned NumBits=0) const
APValue toAPValue () const
void print (llvm::raw_ostream &OS) const
std::string toDiagnosticString (const ASTContext &Ctx) const
unsigned bitWidth () const
bool isSigned () const
bool isNegative () const
bool isPositive () const
bool isZero () const
bool isNonZero () const
bool isMin () const
bool isMinusOne () const
bool isNan () const
bool isSignaling () const
bool isInf () const
bool isFinite () const
bool isNormal () const
bool isDenormal () const
llvm::FPClassTest classify () const
APFloat::fltCategory getCategory () const
ComparisonCategoryResult compare (const Floating &RHS) const
size_t bytesToSerialize () const
void serialize (std::byte *Buff) const
Static Public Member Functions
static Floating getInf (const llvm::fltSemantics &Sem)
static APFloat::opStatus fromIntegral (APSInt Val, const llvm::fltSemantics &Sem, llvm::RoundingMode RM, Floating &Result)
static Floating bitcastFromMemory (const std::byte *Buff, const llvm::fltSemantics &Sem)
static Floating deserialize (const std::byte *Buff)
static Floating abs (const Floating &F)
static APFloat::opStatus add (const Floating &A, const Floating &B, llvm::RoundingMode RM, Floating *R)
static APFloat::opStatus increment (const Floating &A, llvm::RoundingMode RM, Floating *R)
static APFloat::opStatus sub (const Floating &A, const Floating &B, llvm::RoundingMode RM, Floating *R)
static APFloat::opStatus decrement (const Floating &A, llvm::RoundingMode RM, Floating *R)
static APFloat::opStatus mul (const Floating &A, const Floating &B, llvm::RoundingMode RM, Floating *R)
static APFloat::opStatus div (const Floating &A, const Floating &B, llvm::RoundingMode RM, Floating *R)
static bool neg (const Floating &A, Floating *R)
Detailed Description
Definition at line 26 of file Floating.h.
Constructor & Destructor Documentation
Floating() [1/2]
clang::interp::Floating::Floating () inline
Zero-initializes a Floating.
Definition at line 33 of file Floating.h.
Referenced by abs(), add(), bitcastFromMemory(), decrement(), div(), getInf(), increment(), mul(), operator-(), sub(), and toSemantics().
Floating() [2/2]
clang::interp::Floating::Floating (const APFloat & F) inline
Definition at line 34 of file Floating.h.
Member Function Documentation
abs()
static Floating clang::interp::Floating::abs (const Floating & F) inline static
Definition at line 159 of file Floating.h.
References Floating(), and V.
add()
static APFloat::opStatus clang::interp::Floating::add (const Floating & A, const Floating & B, llvm::RoundingMode RM, Floating * R) inline static
Definition at line 168 of file Floating.h.
References Floating().
bitcastFromMemory()
static Floating clang::interp::Floating::bitcastFromMemory (const std::byte * Buff, const llvm::fltSemantics & Sem) inline static
Definition at line 129 of file Floating.h.
References Floating().
Referenced by deserialize().
bitWidth()
unsigned clang::interp::Floating::bitWidth () const inline
Definition at line 86 of file Floating.h.
Referenced by serialize().
bytesToSerialize()
size_t clang::interp::Floating::bytesToSerialize () const inline
Definition at line 139 of file Floating.h.
Referenced by ReadArg< Floating >().
classify()
llvm::FPClassTest clang::interp::Floating::classify () const inline
Definition at line 101 of file Floating.h.
compare()
ComparisonCategoryResult clang::interp::Floating::compare (const Floating & RHS) const inline
Definition at line 104 of file Floating.h.
References clang::Equal, clang::Greater, clang::Less, and clang::Unordered.
convertToInteger()
APFloat::opStatus clang::interp::Floating::convertToInteger (APSInt & Result) const inline
Definition at line 50 of file Floating.h.
decrement()
static APFloat::opStatus clang::interp::Floating::decrement (const Floating & A, llvm::RoundingMode RM, Floating * R) inline static
Definition at line 187 of file Floating.h.
References Floating().
deserialize()
static Floating clang::interp::Floating::deserialize (const std::byte * Buff) inline static
Definition at line 153 of file Floating.h.
References bitcastFromMemory(), and memcpy().
Referenced by ReadArg< Floating >().
div()
static APFloat::opStatus clang::interp::Floating::div (const Floating & A, const Floating & B, llvm::RoundingMode RM, Floating * R) inline static
Definition at line 200 of file Floating.h.
References Floating().
fromIntegral()
static APFloat::opStatus clang::interp::Floating::fromIntegral (APSInt Val, const llvm::fltSemantics & Sem, llvm::RoundingMode RM, Floating & Result) inline static
Definition at line 119 of file Floating.h.
getAPFloat()
const APFloat& clang::interp::Floating::getAPFloat () const inline
Definition at line 40 of file Floating.h.
Referenced by clang::interp::Pointer::toRValue().
getCategory()
APFloat::fltCategory clang::interp::Floating::getCategory () const inline
Definition at line 102 of file Floating.h.
getInf()
static Floating clang::interp::Floating::getInf (const llvm::fltSemantics & Sem) inline static
Definition at line 37 of file Floating.h.
References Floating().
increment()
static APFloat::opStatus clang::interp::Floating::increment (const Floating & A, llvm::RoundingMode RM, Floating * R) inline static
Definition at line 174 of file Floating.h.
References Floating().
isDenormal()
bool clang::interp::Floating::isDenormal () const inline
Definition at line 100 of file Floating.h.
isFinite()
bool clang::interp::Floating::isFinite () const inline
Definition at line 98 of file Floating.h.
isInf()
bool clang::interp::Floating::isInf () const inline
Definition at line 97 of file Floating.h.
isMin()
bool clang::interp::Floating::isMin () const inline
Definition at line 93 of file Floating.h.
isMinusOne()
bool clang::interp::Floating::isMinusOne () const inline
Definition at line 94 of file Floating.h.
isNan()
bool clang::interp::Floating::isNan () const inline
Definition at line 95 of file Floating.h.
isNegative()
bool clang::interp::Floating::isNegative () const inline
Definition at line 89 of file Floating.h.
isNonZero()
bool clang::interp::Floating::isNonZero () const inline
Definition at line 92 of file Floating.h.
isNormal()
bool clang::interp::Floating::isNormal () const inline
Definition at line 99 of file Floating.h.
isPositive()
bool clang::interp::Floating::isPositive () const inline
Definition at line 90 of file Floating.h.
isSignaling()
bool clang::interp::Floating::isSignaling () const inline
Definition at line 96 of file Floating.h.
isSigned()
bool clang::interp::Floating::isSigned () const inline
Definition at line 88 of file Floating.h.
isZero()
bool clang::interp::Floating::isZero () const inline
Definition at line 91 of file Floating.h.
mul()
static APFloat::opStatus clang::interp::Floating::mul (const Floating & A, const Floating & B, llvm::RoundingMode RM, Floating * R) inline static
Definition at line 194 of file Floating.h.
References Floating().
neg()
static bool clang::interp::Floating::neg (const Floating & A, Floating * R) inline static
Definition at line 206 of file Floating.h.
operator!=()
bool clang::interp::Floating::operator!= (Floating RHS) const inline
Definition at line 47 of file Floating.h.
operator-()
Floating clang::interp::Floating::operator- () const inline
Definition at line 48 of file Floating.h.
References Floating().
operator<()
bool clang::interp::Floating::operator< (Floating RHS) const inline
Definition at line 42 of file Floating.h.
operator<=()
bool clang::interp::Floating::operator<= (Floating RHS) const inline
Definition at line 44 of file Floating.h.
operator==()
bool clang::interp::Floating::operator== (Floating RHS) const inline
Definition at line 46 of file Floating.h.
operator>()
bool clang::interp::Floating::operator> (Floating RHS) const inline
Definition at line 43 of file Floating.h.
operator>=()
bool clang::interp::Floating::operator>= (Floating RHS) const inline
Definition at line 45 of file Floating.h.
print()
void clang::interp::Floating::print (llvm::raw_ostream & OS) const inline
Definition at line 73 of file Floating.h.
Referenced by clang::interp::operator<<(), and toDiagnosticString().
serialize()
void clang::interp::Floating::serialize (std::byte * Buff) const inline
Definition at line 144 of file Floating.h.
References bitWidth().
sub()
static APFloat::opStatus clang::interp::Floating::sub (const Floating & A, const Floating & B, llvm::RoundingMode RM, Floating * R) inline static
Definition at line 181 of file Floating.h.
References Floating().
toAPSInt()
APSInt clang::interp::Floating::toAPSInt (unsigned NumBits = 0) const inline
Definition at line 69 of file Floating.h.
toAPValue()
APValue clang::interp::Floating::toAPValue () const inline
Definition at line 72 of file Floating.h.
toDiagnosticString()
std::string clang::interp::Floating::toDiagnosticString (const ASTContext & Ctx) const inline
Definition at line 79 of file Floating.h.
References print().
toSemantics() [1/2]
Floating clang::interp::Floating::toSemantics (const Floating & Other, llvm::RoundingMode RM) const inline
Convert this Floating to one with the same semantics as \Other.
Definition at line 65 of file Floating.h.
References clang::Other, and toSemantics().
toSemantics() [2/2]
Floating clang::interp::Floating::toSemantics (const llvm::fltSemantics * Sem, llvm::RoundingMode RM) const inline
Definition at line 55 of file Floating.h.
References clang::Copy, and Floating().
Referenced by toSemantics().
The documentation for this class was generated from the following file:
lib/AST/Interp/Floating.h