clang: clang::DiagnosticMapping Class Reference
clang::DiagnosticMapping Class Reference
#include "clang/Basic/DiagnosticIDs.h"
Public Member Functions
diag::Severity getSeverity () const
void setSeverity (diag::Severity Value)
bool isUser () const
bool isPragma () const
bool isErrorOrFatal () const
bool hasNoWarningAsError () const
void setNoWarningAsError (bool Value)
bool hasNoErrorAsFatal () const
void setNoErrorAsFatal (bool Value)
bool wasUpgradedFromWarning () const
Whether this mapping attempted to map the diagnostic to a warning, but was overruled because the diagnostic was already mapped to an error or fatal error.
void setUpgradedFromWarning (bool Value)
unsigned serialize () const
Serialize this mapping as a raw integer.
Static Public Member Functions
static DiagnosticMapping Make (diag::Severity Severity, bool IsUser, bool IsPragma)
static DiagnosticMapping deserialize (unsigned Bits)
Deserialize a mapping.
Detailed Description
Definition at line 101 of file DiagnosticIDs.h.
Member Function Documentation
deserialize()
static DiagnosticMapping clang::DiagnosticMapping::deserialize (unsigned Bits) inline static
Deserialize a mapping.
Definition at line 151 of file DiagnosticIDs.h.
Referenced by clang::ASTReader::ReadPragmaDiagnosticMappings().
getSeverity()
diag::Severity clang::DiagnosticMapping::getSeverity () const inline
Definition at line 122 of file DiagnosticIDs.h.
Referenced by GetDefaultDiagMapping(), clang::DiagnosticIDs::isBuiltinExtensionDiag(), clang::DiagnosticIDs::isDefaultMappingAsError(), isErrorOrFatal(), clang::DiagnosticsEngine::setDiagnosticGroupErrorAsFatal(), clang::DiagnosticsEngine::setDiagnosticGroupWarningAsError(), and clang::DiagnosticsEngine::setSeverity().
hasNoErrorAsFatal()
bool clang::DiagnosticMapping::hasNoErrorAsFatal () const inline
Definition at line 136 of file DiagnosticIDs.h.
hasNoWarningAsError()
bool clang::DiagnosticMapping::hasNoWarningAsError () const inline
Definition at line 133 of file DiagnosticIDs.h.
Referenced by clang::DiagnosticsEngine::setSeverity().
isErrorOrFatal()
bool clang::DiagnosticMapping::isErrorOrFatal () const inline
Definition at line 128 of file DiagnosticIDs.h.
References clang::diag::Error, clang::diag::Fatal, and getSeverity().
Referenced by clang::ASTReader::ReadPragmaDiagnosticMappings().
isPragma()
bool clang::DiagnosticMapping::isPragma () const inline
Definition at line 126 of file DiagnosticIDs.h.
Referenced by clang::ASTReader::ReadPragmaDiagnosticMappings().
isUser()
bool clang::DiagnosticMapping::isUser () const inline
Definition at line 125 of file DiagnosticIDs.h.
Make()
static DiagnosticMapping clang::DiagnosticMapping::Make (diag::Severity Severity, bool IsUser, bool IsPragma) inline static
Definition at line 110 of file DiagnosticIDs.h.
Referenced by GetDefaultDiagMapping().
serialize()
unsigned clang::DiagnosticMapping::serialize () const inline
Serialize this mapping as a raw integer.
Definition at line 146 of file DiagnosticIDs.h.
setNoErrorAsFatal()
void clang::DiagnosticMapping::setNoErrorAsFatal (bool Value) inline
Definition at line 137 of file DiagnosticIDs.h.
Referenced by clang::DiagnosticsEngine::setDiagnosticGroupErrorAsFatal().
setNoWarningAsError()
void clang::DiagnosticMapping::setNoWarningAsError (bool Value) inline
Definition at line 134 of file DiagnosticIDs.h.
Referenced by GetDefaultDiagMapping(), clang::DiagnosticsEngine::setDiagnosticGroupWarningAsError(), and clang::DiagnosticsEngine::setSeverity().
setSeverity()
void clang::DiagnosticMapping::setSeverity (diag::Severity Value) inline
Definition at line 123 of file DiagnosticIDs.h.
Referenced by GetDefaultDiagMapping(), clang::ASTReader::ReadPragmaDiagnosticMappings(), clang::DiagnosticsEngine::setDiagnosticGroupErrorAsFatal(), and clang::DiagnosticsEngine::setDiagnosticGroupWarningAsError().
setUpgradedFromWarning()
void clang::DiagnosticMapping::setUpgradedFromWarning (bool Value) inline
Definition at line 143 of file DiagnosticIDs.h.
Referenced by clang::ASTReader::ReadPragmaDiagnosticMappings(), and clang::DiagnosticsEngine::setSeverity().
wasUpgradedFromWarning()
bool clang::DiagnosticMapping::wasUpgradedFromWarning () const inline
Whether this mapping attempted to map the diagnostic to a warning, but was overruled because the diagnostic was already mapped to an error or fatal error.
Definition at line 142 of file DiagnosticIDs.h.
Referenced by clang::ASTReader::ReadPragmaDiagnosticMappings().
The documentation for this class was generated from the following file:
include/clang/Basic/DiagnosticIDs.h