clang: clang::OpenACCIfClause Class Reference
clang::OpenACCIfClause Class Reference
An 'if' clause, which has a required condition expression.
#include "clang/AST/OpenACCClause.h"
Static Public Member Functions
static OpenACCIfClause * Create (const ASTContext &C, SourceLocation BeginLoc, SourceLocation LParenLoc, Expr *ConditionExpr, SourceLocation EndLoc)
Static Public Member Functions inherited from clang::OpenACCClause
static bool classof (const OpenACCClause *)
Protected Member Functions
OpenACCIfClause (SourceLocation BeginLoc, SourceLocation LParenLoc, Expr *ConditionExpr, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClauseWithCondition
OpenACCClauseWithCondition (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, Expr *ConditionExpr, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClauseWithParams
OpenACCClauseWithParams (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClause
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Additional Inherited Members
Public Types inherited from clang::OpenACCClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions inherited from clang::OpenACCClauseWithCondition
bool hasConditionExpr () const
const Expr * getConditionExpr () const
Expr * getConditionExpr ()
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClauseWithParams
SourceLocation getLParenLoc () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClause
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Detailed Description
An 'if' clause, which has a required condition expression.
Definition at line 137 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCIfClause()
OpenACCIfClause::OpenACCIfClause (SourceLocation BeginLoc, SourceLocation LParenLoc, Expr * ConditionExpr, SourceLocation EndLoc) protected
Definition at line 40 of file OpenACCClause.cpp.
References clang::Expr::getType(), clang::If, clang::Expr::isInstantiationDependent(), and clang::Type::isScalarType().
Referenced by Create().
Member Function Documentation
Create()
OpenACCIfClause * OpenACCIfClause::Create (const ASTContext & C, SourceLocation BeginLoc, SourceLocation LParenLoc, Expr * ConditionExpr, SourceLocation EndLoc) static
Definition at line 31 of file OpenACCClause.cpp.
References OpenACCIfClause().
Referenced by clang::SemaOpenACC::ActOnClause(), and clang::ASTRecordReader::readOpenACCClause().
The documentation for this class was generated from the following files:
include/clang/AST/OpenACCClause.h
lib/AST/OpenACCClause.cpp