clang: clang::ento::SValBuilder Class Reference
clang::ento::SValBuilder Class Reference abstract
#include "clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h"
Public Member Functions
SValBuilder (llvm::BumpPtrAllocator &alloc, ASTContext &context, ProgramStateManager &stateMgr)
virtual ~SValBuilder ()=default
SVal evalCast (SVal V, QualType CastTy, QualType OriginalTy)
Cast a given SVal to another SVal using given QualType's.
SVal evalIntegralCast (ProgramStateRef state, SVal val, QualType castTy, QualType originalType)
virtual SVal evalMinus (NonLoc val)=0
virtual SVal evalComplement (NonLoc val)=0
virtual SVal evalBinOpNN (ProgramStateRef state, BinaryOperator::Opcode op, NonLoc lhs, NonLoc rhs, QualType resultTy)=0
Create a new value which represents a binary expression with two non- location operands.
virtual SVal evalBinOpLL (ProgramStateRef state, BinaryOperator::Opcode op, Loc lhs, Loc rhs, QualType resultTy)=0
Create a new value which represents a binary expression with two memory location operands.
virtual SVal evalBinOpLN (ProgramStateRef state, BinaryOperator::Opcode op, Loc lhs, NonLoc rhs, QualType resultTy)=0
Create a new value which represents a binary expression with a memory location and non-location operands.
virtual const llvm::APSInt * getKnownValue (ProgramStateRef state, SVal val)=0
Evaluates a given SVal.
virtual SVal simplifySVal (ProgramStateRef State, SVal Val)=0
Simplify symbolic expressions within a given SVal.
SVal makeSymExprValNN (BinaryOperator::Opcode op, NonLoc lhs, NonLoc rhs, QualType resultTy)
Constructs a symbolic expression for two non-location values.
SVal evalBinOp (ProgramStateRef state, BinaryOperator::Opcode op, SVal lhs, SVal rhs, QualType type)
ConditionTruthVal areEqual (ProgramStateRef state, SVal lhs, SVal rhs)
SVal evalEQ (ProgramStateRef state, SVal lhs, SVal rhs)
DefinedOrUnknownSVal evalEQ (ProgramStateRef state, DefinedOrUnknownSVal lhs, DefinedOrUnknownSVal rhs)
ASTContext & getContext ()
const ASTContext & getContext () const
ProgramStateManager & getStateManager ()
QualType getConditionType () const
QualType getArrayIndexType () const
BasicValueFactory & getBasicValueFactory ()
const BasicValueFactory & getBasicValueFactory () const
SymbolManager & getSymbolManager ()
const SymbolManager & getSymbolManager () const
MemRegionManager & getRegionManager ()
const MemRegionManager & getRegionManager () const
const AnalyzerOptions & getAnalyzerOptions () const
const SymbolConjured * conjureSymbol (const Stmt *stmt, const LocationContext *LCtx, QualType type, unsigned visitCount, const void *symbolTag=nullptr)
const SymbolConjured * conjureSymbol (const Expr *expr, const LocationContext *LCtx, unsigned visitCount, const void *symbolTag=nullptr)
DefinedOrUnknownSVal makeZeroVal (QualType type)
Construct an SVal representing '0' for the specified type.
DefinedOrUnknownSVal getRegionValueSymbolVal (const TypedValueRegion *region)
Make a unique symbol for value of region.
DefinedOrUnknownSVal conjureSymbolVal (const void *symbolTag, const Expr *expr, const LocationContext *LCtx, unsigned count)
Create a new symbol with a unique 'name'.
DefinedOrUnknownSVal conjureSymbolVal (const void *symbolTag, const Expr *expr, const LocationContext *LCtx, QualType type, unsigned count)
DefinedOrUnknownSVal conjureSymbolVal (const Stmt *stmt, const LocationContext *LCtx, QualType type, unsigned visitCount)
DefinedOrUnknownSVal getConjuredHeapSymbolVal (const Expr *E, const LocationContext *LCtx, unsigned Count)
Conjure a symbol representing heap allocated memory region.
DefinedOrUnknownSVal getConjuredHeapSymbolVal (const Expr *E, const LocationContext *LCtx, QualType type, unsigned Count)
Conjure a symbol representing heap allocated memory region.
DefinedOrUnknownSVal getDerivedRegionValueSymbolVal (SymbolRef parentSymbol, const TypedValueRegion *region)
DefinedSVal getMetadataSymbolVal (const void *symbolTag, const MemRegion *region, const Expr *expr, QualType type, const LocationContext *LCtx, unsigned count)
DefinedSVal getMemberPointer (const NamedDecl *ND)
DefinedSVal getFunctionPointer (const FunctionDecl *func)
DefinedSVal getBlockPointer (const BlockDecl *block, CanQualType locTy, const LocationContext *locContext, unsigned blockCount)
Optional< SVal > getConstantVal (const Expr *E)
Returns the value of E, if it can be determined in a non-path-sensitive manner.
NonLoc makeCompoundVal (QualType type, llvm::ImmutableList< SVal > vals)
NonLoc makeLazyCompoundVal (const StoreRef &store, const TypedValueRegion *region)
NonLoc makePointerToMember (const DeclaratorDecl *DD)
NonLoc makePointerToMember (const PointerToMemberData *PTMD)
NonLoc makeZeroArrayIndex ()
NonLoc makeArrayIndex (uint64_t idx)
SVal convertToArrayIndex (SVal val)
nonloc::ConcreteInt makeIntVal (const IntegerLiteral *integer)
nonloc::ConcreteInt makeBoolVal (const ObjCBoolLiteralExpr *boolean)
nonloc::ConcreteInt makeBoolVal (const CXXBoolLiteralExpr *boolean)
nonloc::ConcreteInt makeIntVal (const llvm::APSInt &integer)
loc::ConcreteInt makeIntLocVal (const llvm::APSInt &integer)
NonLoc makeIntVal (const llvm::APInt &integer, bool isUnsigned)
DefinedSVal makeIntVal (uint64_t integer, QualType type)
NonLoc makeIntVal (uint64_t integer, bool isUnsigned)
NonLoc makeIntValWithWidth (QualType ptrType, uint64_t integer)
NonLoc makeLocAsInteger (Loc loc, unsigned bits)
NonLoc makeNonLoc (const SymExpr *lhs, BinaryOperator::Opcode op, const llvm::APSInt &rhs, QualType type)
NonLoc makeNonLoc (const llvm::APSInt &rhs, BinaryOperator::Opcode op, const SymExpr *lhs, QualType type)
NonLoc makeNonLoc (const SymExpr *lhs, BinaryOperator::Opcode op, const SymExpr *rhs, QualType type)
NonLoc makeNonLoc (const SymExpr *operand, QualType fromTy, QualType toTy)
Create a NonLoc value for cast.
nonloc::ConcreteInt makeTruthVal (bool b, QualType type)
nonloc::ConcreteInt makeTruthVal (bool b)
Loc makeNullWithType (QualType type)
Create NULL pointer, with proper pointer bit-width for given address space.
Loc makeLoc (SymbolRef sym)
Loc makeLoc (const MemRegion *region)
Loc makeLoc (const AddrLabelExpr *expr)
Loc makeLoc (const llvm::APSInt &integer)
Optional< loc::MemRegionVal > getCastedMemRegionVal (const MemRegion *region, QualType type)
Return MemRegionVal on success cast, otherwise return None.
SVal makeSymbolVal (SymbolRef Sym)
Make an SVal that represents the given symbol.
loc::MemRegionVal getCXXThis (const CXXMethodDecl *D, const StackFrameContext *SFC)
Return a memory region for the 'this' object reference.
loc::MemRegionVal getCXXThis (const CXXRecordDecl *D, const StackFrameContext *SFC)
Return a memory region for the 'this' object reference.
Protected Member Functions
SVal evalCastKind (UndefinedVal V, QualType CastTy, QualType OriginalTy)
SVal evalCastKind (UnknownVal V, QualType CastTy, QualType OriginalTy)
SVal evalCastKind (Loc V, QualType CastTy, QualType OriginalTy)
SVal evalCastKind (NonLoc V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (loc::ConcreteInt V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (loc::GotoLabel V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (loc::MemRegionVal V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (nonloc::CompoundVal V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (nonloc::ConcreteInt V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (nonloc::LazyCompoundVal V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (nonloc::LocAsInteger V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (nonloc::SymbolVal V, QualType CastTy, QualType OriginalTy)
SVal evalCastSubKind (nonloc::PointerToMember V, QualType CastTy, QualType OriginalTy)
SVal simplifySymbolCast (nonloc::SymbolVal V, QualType CastTy)
Reduce cast expression by removing redundant intermediate casts.
Protected Attributes
ASTContext & Context
BasicValueFactory BasicVals
Manager of APSInt values.
SymbolManager SymMgr
Manages the creation of symbols.
MemRegionManager MemMgr
Manages the creation of memory regions.
ProgramStateManager & StateMgr
const AnalyzerOptions & AnOpts
const QualType ArrayIndexTy
The scalar type to use for array indices.
const unsigned ArrayIndexWidth
The width of the scalar type used for array indices.
Detailed Description
Definition at line 53 of file SValBuilder.h.
Constructor & Destructor Documentation
SValBuilder()
SValBuilder::SValBuilder (llvm::BumpPtrAllocator & alloc, ASTContext & context, ProgramStateManager & stateMgr)
Definition at line 52 of file SValBuilder.cpp.
~SValBuilder()
virtual clang::ento::SValBuilder::~SValBuilder () virtual default
Member Function Documentation
areEqual()
ConditionTruthVal SValBuilder::areEqual (ProgramStateRef state, SVal lhs, SVal rhs)
Returns
Whether values in lhs and rhs are equal at state.
Definition at line 485 of file SValBuilder.cpp.
References evalEQ(), and state.
Referenced by clang::ento::ProgramState::areEqual().
conjureSymbol() [1/2]
const SymbolConjured* clang::ento::SValBuilder::conjureSymbol (const Expr * expr, const LocationContext * LCtx, unsigned visitCount, const void * symbolTag = nullptr) inline
Definition at line 201 of file SValBuilder.h.
References clang::ento::SymbolManager::conjureSymbol(), clang::ast_matchers::expr, and SymMgr.
conjureSymbol() [2/2]
const SymbolConjured* clang::ento::SValBuilder::conjureSymbol (const Stmt * stmt, const LocationContext * LCtx, QualType type, unsigned visitCount, const void * symbolTag = nullptr) inline
Definition at line 193 of file SValBuilder.h.
References clang::ento::SymbolManager::conjureSymbol(), clang::ast_matchers::stmt, and SymMgr.
conjureSymbolVal() [1/3]
DefinedOrUnknownSVal SValBuilder::conjureSymbolVal (const Stmt * stmt, const LocationContext * LCtx, QualType type, unsigned visitCount)
Definition at line 182 of file SValBuilder.cpp.
References clang::ento::SymbolManager::canSymbolicate(), clang::ento::SymbolManager::conjureSymbol(), clang::ento::MemRegionManager::getSymbolicRegion(), clang::ento::Loc::isLocType(), makeZeroVal(), MemMgr, clang::ast_matchers::stmt, and SymMgr.
conjureSymbolVal() [2/3]
DefinedOrUnknownSVal SValBuilder::conjureSymbolVal (const void * symbolTag, const Expr * expr, const LocationContext * LCtx, QualType type, unsigned count)
Definition at line 163 of file SValBuilder.cpp.
References clang::ento::SymbolManager::canSymbolicate(), clang::ento::SymbolManager::conjureSymbol(), clang::ast_matchers::expr, clang::ento::MemRegionManager::getSymbolicRegion(), clang::ento::Loc::isLocType(), makeZeroVal(), MemMgr, and SymMgr.
conjureSymbolVal() [3/3]
DefinedOrUnknownSVal clang::ento::SValBuilder::conjureSymbolVal (const void * symbolTag, const Expr * expr, const LocationContext * LCtx, unsigned count)
Create a new symbol with a unique 'name'.
We resort to conjured symbols when we cannot construct a derived symbol. The advantage of symbols derived/built from other symbols is that we preserve the relation between related(or even equivalent) expressions, so conjured symbols should be used sparingly.
Referenced by clang::ento::ExprEngine::bindReturnValue(), clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::retaincountchecker::RetainCountChecker::evalCall(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::VisitBinaryOperator(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCXXCatchStmt(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::ExprEngine::VisitDeclStmt(), and clang::ento::ExprEngine::VisitGuardedExpr().
convertToArrayIndex()
SVal SValBuilder::convertToArrayIndex (SVal val)
Definition at line 109 of file SValBuilder.cpp.
References ArrayIndexTy, ArrayIndexWidth, evalCast(), clang::ento::SVal::getAs(), and clang::ento::SVal::isUnknownOrUndef().
evalBinOp()
SVal SValBuilder::evalBinOp (ProgramStateRef state, BinaryOperator::Opcode op, SVal lhs, SVal rhs, QualType type)
Definition at line 434 of file SValBuilder.cpp.
References clang::ento::SVal::castAs(), evalBinOpLL(), evalBinOpLN(), evalBinOpNN(), clang::ento::SVal::getAs(), clang::ento::SVal::isUndef(), clang::ento::SVal::isUnknown(), makeIntVal(), and state.
Referenced by clang::ento::ExprEngine::bindReturnValue(), clang::ento::ExprEngine::evalBinOp(), and evalEQ().
evalBinOpLL()
virtual SVal clang::ento::SValBuilder::evalBinOpLL (ProgramStateRef state, BinaryOperator::Opcode op, Loc lhs, Loc rhs, QualType resultTy) pure virtual
Create a new value which represents a binary expression with two memory location operands.
Referenced by evalBinOp().
evalBinOpLN()
virtual SVal clang::ento::SValBuilder::evalBinOpLN (ProgramStateRef state, BinaryOperator::Opcode op, Loc lhs, NonLoc rhs, QualType resultTy) pure virtual
Create a new value which represents a binary expression with a memory location and non-location operands.
For example, this would be used to evaluate a pointer arithmetic operation.
Referenced by evalBinOp().
evalBinOpNN()
virtual SVal clang::ento::SValBuilder::evalBinOpNN (ProgramStateRef state, BinaryOperator::Opcode op, NonLoc lhs, NonLoc rhs, QualType resultTy) pure virtual
Create a new value which represents a binary expression with two non- location operands.
Referenced by clang::ento::ProgramState::assumeInBound(), clang::ento::iterator::assumeNoOverflow(), evalBinOp(), clang::ento::ExprEngine::evalBinOp(), and evalIntegralCast().
evalCast()
SVal SValBuilder::evalCast (SVal V, QualType CastTy, QualType OriginalTy)
Cast a given SVal to another SVal using given QualType's.
Parameters
V – SVal that should be casted.
CastTy – QualType that V should be casted according to.
OriginalTy – QualType which is associated to V. It provides additional information about what type the cast performs from.
Returns
the most appropriate casted SVal. Note: Many cases don't use an exact OriginalTy. It can be extracted from SVal or the cast can performs unconditionaly. Always pass OriginalTy! It can be crucial in certain cases and generates different results. FIXME: If OriginalTy.isNull() is true, then cast performs based on CastTy only. This behavior is uncertain and should be improved.
Definition at line 589 of file SValBuilder.cpp.
References Context, evalCastKind(), clang::ASTContext::getCanonicalType(), clang::ASTContext::getPointerType(), clang::QualType::isNull(), clang::Type::isVariableArrayType(), shouldBeModeledWithNoOp(), and V.
Referenced by clang::ento::SimpleConstraintManager::assume(), convertToArrayIndex(), evalIntegralCast(), getConstantVal(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::ExprEngine::handleLValueBitCast(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCXXNewExpr(), and clang::ento::ExprEngine::VisitLogicalExpr().
evalCastKind() [1/4]
SVal SValBuilder::evalCastKind (Loc V, QualType CastTy, QualType OriginalTy) protected
Definition at line 636 of file SValBuilder.cpp.
References evalCastSubKind(), and V.
evalCastKind() [2/4]
SVal SValBuilder::evalCastKind (NonLoc V, QualType CastTy, QualType OriginalTy) protected
Definition at line 649 of file SValBuilder.cpp.
References evalCastSubKind(), and V.
evalCastKind() [3/4]
SVal SValBuilder::evalCastKind (UndefinedVal V, QualType CastTy, QualType OriginalTy) protected
Definition at line 626 of file SValBuilder.cpp.
References V.
Referenced by evalCast(), and evalCastSubKind().
evalCastKind() [4/4]
SVal SValBuilder::evalCastKind (UnknownVal V, QualType CastTy, QualType OriginalTy) protected
Definition at line 631 of file SValBuilder.cpp.
References V.
evalCastSubKind() [1/9]
SVal SValBuilder::evalCastSubKind (loc::ConcreteInt V, QualType CastTy, QualType OriginalTy) protected
Definition at line 671 of file SValBuilder.cpp.
References clang::ento::APSIntType::apply(), BasicVals, clang::ento::BasicValueFactory::getAPSIntType(), clang::Type::isBooleanType(), clang::Type::isIntegralOrEnumerationType(), clang::ento::Loc::isLocType(), makeIntVal(), makeTruthVal(), and V.
Referenced by evalCastKind(), and evalCastSubKind().
evalCastSubKind() [2/9]
SVal SValBuilder::evalCastSubKind (loc::GotoLabel V, QualType CastTy, QualType OriginalTy) protected
Definition at line 692 of file SValBuilder.cpp.
References Context, clang::ASTContext::getIntWidth(), clang::Type::isBooleanType(), clang::Type::isIntegralOrEnumerationType(), clang::ento::Loc::isLocType(), clang::QualType::isNull(), clang::Type::isPointerType(), clang::Type::isReferenceType(), makeLocAsInteger(), makeTruthVal(), and V.
evalCastSubKind() [3/9]
SVal SValBuilder::evalCastSubKind (loc::MemRegionVal V, QualType CastTy, QualType OriginalTy) protected
Definition at line 726 of file SValBuilder.cpp.
References clang::ento::ProgramStateManager::ArrayToPointer(), BasicVals, clang::ento::SVal::castAs(), Context, clang::QualType::getCanonicalType(), getCastedMemRegionVal(), clang::ento::SymbolManager::getExtentSymbol(), clang::ASTContext::getIntWidth(), clang::ento::MemRegion::getSymbolicBase(), clang::ento::SymExpr::getType(), clang::ento::BasicValueFactory::getZeroWithTypeSize(), hasSameUnqualifiedPointeeType(), clang::Type::isBlockPointerType(), clang::Type::isBooleanType(), clang::Type::isFunctionPointerType(), clang::Type::isFunctionType(), clang::Type::isIntegralOrEnumerationType(), clang::ento::Loc::isLocType(), clang::QualType::isNull(), clang::Type::isPointerType(), clang::Type::isReferenceType(), clang::Type::isVoidPointerType(), makeLocAsInteger(), makeNonLoc(), makeTruthVal(), StateMgr, SymMgr, and V.
evalCastSubKind() [4/9]
SVal SValBuilder::evalCastSubKind (nonloc::CompoundVal V, QualType CastTy, QualType OriginalTy) protected
Definition at line 864 of file SValBuilder.cpp.
evalCastSubKind() [5/9]
SVal SValBuilder::evalCastSubKind (nonloc::ConcreteInt V, QualType CastTy, QualType OriginalTy) protected
Definition at line 870 of file SValBuilder.cpp.
References clang::ento::APSIntType::apply(), BasicVals, clang::ento::BasicValueFactory::getAPSIntType(), clang::ento::Loc::isLocType(), makeIntLocVal(), makeIntVal(), makeTruthVal(), and V.
evalCastSubKind() [6/9]
SVal SValBuilder::evalCastSubKind (nonloc::LazyCompoundVal V, QualType CastTy, QualType OriginalTy) protected
Definition at line 894 of file SValBuilder.cpp.
evalCastSubKind() [7/9]
SVal SValBuilder::evalCastSubKind (nonloc::LocAsInteger V, QualType CastTy, QualType OriginalTy) protected
Definition at line 900 of file SValBuilder.cpp.
References Context, evalCastKind(), evalCastSubKind(), clang::ento::SVal::getAsRegion(), getCastedMemRegionVal(), clang::ASTContext::getIntWidth(), clang::ento::SymExpr::getType(), clang::Type::isBooleanType(), clang::Type::isFloatingType(), clang::Type::isFunctionType(), clang::Type::isIntegralOrEnumerationType(), clang::ento::Loc::isLocType(), clang::QualType::isNull(), clang::Type::isReferenceType(), makeLocAsInteger(), clang::ento::MemRegion::StripCasts(), and V.
evalCastSubKind() [8/9]
SVal SValBuilder::evalCastSubKind (nonloc::PointerToMember V, QualType CastTy, QualType OriginalTy) protected
Definition at line 1003 of file SValBuilder.cpp.
References V.
evalCastSubKind() [9/9]
SVal SValBuilder::evalCastSubKind (nonloc::SymbolVal V, QualType CastTy, QualType OriginalTy) protected
Definition at line 963 of file SValBuilder.cpp.
References Context, clang::ento::ExprEngine::getAnalysisManager(), clang::ento::AnalysisManager::getAnalyzerOptions(), getBasicValueFactory(), clang::ASTContext::getCanonicalType(), clang::ento::ProgramStateManager::getOwningEngine(), clang::ento::SymExpr::getType(), clang::Type::isBooleanType(), clang::Type::isFloatingType(), clang::Type::isIntegralOrEnumerationType(), clang::ento::Loc::isLocType(), clang::Type::isMemberPointerType(), clang::QualType::isNull(), makeNonLoc(), simplifySymbolCast(), StateMgr, and V.
evalComplement()
virtual SVal clang::ento::SValBuilder::evalComplement (NonLoc val) pure virtual
Referenced by clang::ento::ExprEngine::evalComplement().
evalEQ() [1/2]
DefinedOrUnknownSVal SValBuilder::evalEQ (ProgramStateRef state, DefinedOrUnknownSVal lhs, DefinedOrUnknownSVal rhs)
Definition at line 494 of file SValBuilder.cpp.
References clang::ento::SVal::castAs(), evalEQ(), and state.
evalEQ() [2/2]
SVal SValBuilder::evalEQ (ProgramStateRef state, SVal lhs, SVal rhs)
Definition at line 490 of file SValBuilder.cpp.
References evalBinOp(), getConditionType(), and state.
Referenced by areEqual(), and evalEQ().
evalIntegralCast()
SVal SValBuilder::evalIntegralCast (ProgramStateRef state, SVal val, QualType castTy, QualType originalType)
Definition at line 537 of file SValBuilder.cpp.
References clang::ento::SVal::castAs(), evalBinOpNN(), evalCast(), clang::ento::SVal::getAsSymbol(), getConditionType(), getContext(), clang::ento::APSIntType::getMaxValue(), clang::Type::isUnsignedIntegerType(), makeIntVal(), makeNonLoc(), and state.
Referenced by clang::ento::ExprEngine::VisitCast().
evalMinus()
virtual SVal clang::ento::SValBuilder::evalMinus (NonLoc val) pure virtual
Referenced by clang::ento::ExprEngine::evalMinus().
getAnalyzerOptions()
const AnalyzerOptions& clang::ento::SValBuilder::getAnalyzerOptions () const inline
Definition at line 189 of file SValBuilder.h.
References AnOpts.
Referenced by clang::ento::MemRegionManager::getStaticSize().
getArrayIndexType()
QualType clang::ento::SValBuilder::getArrayIndexType () const inline
Definition at line 176 of file SValBuilder.h.
References ArrayIndexTy.
Referenced by clang::ento::ProgramState::assumeInBound(), clang::ento::ExprEngine::bindReturnValue(), and clang::ento::MemRegionManager::getStaticSize().
getBasicValueFactory() [1/2]
BasicValueFactory& clang::ento::SValBuilder::getBasicValueFactory () inline
Definition at line 180 of file SValBuilder.h.
References BasicVals.
Referenced by clang::ento::ProgramState::assumeInBound(), clang::ento::iterator::assumeNoOverflow(), clang::ento::nonloc::ConcreteInt::evalBinOp(), evalCastSubKind(), clang::ento::SimpleConstraintManager::getBasicVals(), and getBVF().
getBasicValueFactory() [2/2]
const BasicValueFactory& clang::ento::SValBuilder::getBasicValueFactory () const inline
Definition at line 181 of file SValBuilder.h.
References BasicVals.
getBlockPointer()
DefinedSVal SValBuilder::getBlockPointer (const BlockDecl * block, CanQualType locTy, const LocationContext * locContext, unsigned blockCount)
Definition at line 276 of file SValBuilder.cpp.
References clang::LocationContext::getAnalysisDeclContext(), clang::ento::MemRegionManager::getBlockCodeRegion(), clang::ento::MemRegionManager::getBlockDataRegion(), and MemMgr.
Referenced by clang::ento::ExprEngine::VisitBlockExpr().
getCastedMemRegionVal()
Optional< loc::MemRegionVal > SValBuilder::getCastedMemRegionVal (const MemRegion * region, QualType type)
Return MemRegionVal on success cast, otherwise return None.
Definition at line 288 of file SValBuilder.cpp.
References clang::ento::StoreManager::castRegion(), clang::ento::ProgramStateManager::getStoreManager(), and StateMgr.
Referenced by evalCastSubKind().
getConditionType()
QualType clang::ento::SValBuilder::getConditionType () const inline
Definition at line 172 of file SValBuilder.h.
References clang::ASTContext::BoolTy, Context, clang::ASTContext::getLangOpts(), and clang::ASTContext::IntTy.
Referenced by clang::ento::iterator::assumeNoOverflow(), evalEQ(), evalIntegralCast(), and clang::ento::ExprEngine::getInitialState().
getConjuredHeapSymbolVal() [1/2]
DefinedOrUnknownSVal clang::ento::SValBuilder::getConjuredHeapSymbolVal (const Expr * E, const LocationContext * LCtx, QualType type, unsigned Count)
Conjure a symbol representing heap allocated memory region.
Note, now, the expression doesn't need to represent a location. But the type need to!
getConjuredHeapSymbolVal() [2/2]
DefinedOrUnknownSVal clang::ento::SValBuilder::getConjuredHeapSymbolVal (const Expr * E, const LocationContext * LCtx, unsigned Count)
Conjure a symbol representing heap allocated memory region.
Note, the expression should represent a location.
Referenced by clang::ento::ExprEngine::bindReturnValue(), and clang::ento::ExprEngine::VisitCXXNewExpr().
getConstantVal()
Optional< SVal > SValBuilder::getConstantVal (const Expr * E)
Returns the value of E, if it can be determined in a non-path-sensitive manner.
If E is not a constant or cannot be modeled, returns None.
Definition at line 309 of file SValBuilder.cpp.
References evalCast(), clang::Expr::EvaluateAsInt(), getContext(), getRegionManager(), clang::Stmt::getStmtClass(), clang::Expr::getType(), clang::Expr::IgnoreParens(), clang::Expr::isGLValue(), clang::ento::Loc::isLocType(), clang::Expr::isNullPointerConstant(), makeBoolVal(), makeIntVal(), makeLoc(), makeNullWithType(), makeTruthVal(), makeZeroVal(), and clang::Expr::NPC_ValueDependentIsNotNull.
getContext() [1/2]
ASTContext& clang::ento::SValBuilder::getContext () inline
Definition at line 167 of file SValBuilder.h.
References Context.
Referenced by clang::ento::SimpleConstraintManager::assume(), clang::ento::ProgramState::assumeInBound(), clang::ento::ExprEngine::computeObjectUnderConstruction(), evalIntegralCast(), getConstantVal(), getCXXThis(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), and clang::ento::StoreManager::MakeElementRegion().
getContext() [2/2]
const ASTContext& clang::ento::SValBuilder::getContext () const inline
Definition at line 168 of file SValBuilder.h.
References Context.
getCXXThis() [1/2]
loc::MemRegionVal SValBuilder::getCXXThis (const CXXMethodDecl * D, const StackFrameContext * SFC)
Return a memory region for the 'this' object reference.
Definition at line 295 of file SValBuilder.cpp.
References getRegionManager(), and clang::CXXMethodDecl::getThisType().
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), clang::ento::CallEventManager::getCaller(), clang::ento::BlockCall::getInitialStackFrameContents(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::AnyCXXConstructorCall::getInitialStackFrameContents(), clang::ento::ExprEngine::getInitialState(), clang::ento::ExprEngine::ProcessBaseDtor(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::ProcessMemberDtor(), and clang::ento::ExprEngine::VisitCommonDeclRefExpr().
getCXXThis() [2/2]
loc::MemRegionVal SValBuilder::getCXXThis (const CXXRecordDecl * D, const StackFrameContext * SFC)
Return a memory region for the 'this' object reference.
Definition at line 302 of file SValBuilder.cpp.
References getContext(), clang::ASTContext::getPointerType(), getRegionManager(), and clang::TypeDecl::getTypeForDecl().
getDerivedRegionValueSymbolVal()
DefinedOrUnknownSVal SValBuilder::getDerivedRegionValueSymbolVal (SymbolRef parentSymbol, const TypedValueRegion * region)
Definition at line 238 of file SValBuilder.cpp.
References clang::ento::SymbolManager::canSymbolicate(), clang::ento::SymbolManager::getDerivedSymbol(), clang::ento::MemRegionManager::getSymbolicRegion(), clang::ento::TypedValueRegion::getValueType(), clang::ento::Loc::isLocType(), clang::Type::isNullPtrType(), makeZeroVal(), MemMgr, and SymMgr.
getFunctionPointer()
DefinedSVal SValBuilder::getFunctionPointer (const FunctionDecl * func)
Definition at line 272 of file SValBuilder.cpp.
References clang::ento::MemRegionManager::getFunctionCodeRegion(), and MemMgr.
Referenced by getMemberPointer(), clang::ento::ExprEngine::VisitCommonDeclRefExpr(), and clang::ento::ExprEngine::VisitMemberExpr().
getKnownValue()
virtual const llvm::APSInt* clang::ento::SValBuilder::getKnownValue (ProgramStateRef state, SVal val) pure virtual
Evaluates a given SVal.
If the SVal has only one possible (integer) value, that value is returned. Otherwise, returns NULL.
getMemberPointer()
DefinedSVal SValBuilder::getMemberPointer (const NamedDecl * ND)
Definition at line 256 of file SValBuilder.cpp.
References getFunctionPointer(), and clang::prec::PointerToMember.
Referenced by clang::ento::ExprEngine::VisitCast(), and clang::ento::ExprEngine::VisitUnaryOperator().
getMetadataSymbolVal()
DefinedSVal SValBuilder::getMetadataSymbolVal (const void * symbolTag, const MemRegion * region, const Expr * expr, QualType type, const LocationContext * LCtx, unsigned count)
Definition at line 221 of file SValBuilder.cpp.
References clang::ento::SymbolManager::canSymbolicate(), clang::ast_matchers::expr, clang::ento::SymbolManager::getMetadataSymbol(), clang::ento::MemRegionManager::getSymbolicRegion(), clang::ento::Loc::isLocType(), MemMgr, and SymMgr.
getRegionManager() [1/2]
MemRegionManager& clang::ento::SValBuilder::getRegionManager () inline
Definition at line 186 of file SValBuilder.h.
References MemMgr.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), getConstantVal(), getCXXThis(), clang::ento::ObjCMethodCall::getInitialStackFrameContents(), clang::ento::ExprEngine::VisitCXXThisExpr(), and clang::ento::ExprEngine::VisitLambdaExpr().
getRegionManager() [2/2]
const MemRegionManager& clang::ento::SValBuilder::getRegionManager () const inline
Definition at line 187 of file SValBuilder.h.
References MemMgr.
getRegionValueSymbolVal()
DefinedOrUnknownSVal SValBuilder::getRegionValueSymbolVal (const TypedValueRegion * region)
Make a unique symbol for value of region.
Definition at line 128 of file SValBuilder.cpp.
References clang::ento::SymbolManager::canSymbolicate(), clang::ento::SymbolManager::getRegionValueSymbol(), clang::ento::MemRegionManager::getSymbolicRegion(), clang::ento::TypedValueRegion::getValueType(), clang::ento::Loc::isLocType(), clang::Type::isNullPtrType(), makeZeroVal(), MemMgr, and SymMgr.
getStateManager()
ProgramStateManager& clang::ento::SValBuilder::getStateManager () inline
Definition at line 170 of file SValBuilder.h.
References StateMgr.
getSymbolManager() [1/2]
SymbolManager& clang::ento::SValBuilder::getSymbolManager () inline
Definition at line 183 of file SValBuilder.h.
References SymMgr.
Referenced by clang::ento::MemRegionManager::getStaticSize(), clang::ento::SimpleConstraintManager::getSymbolManager(), and clang::ento::CheckerContext::getSymbolManager().
getSymbolManager() [2/2]
const SymbolManager& clang::ento::SValBuilder::getSymbolManager () const inline
Definition at line 184 of file SValBuilder.h.
References SymMgr.
makeArrayIndex()
NonLoc clang::ento::SValBuilder::makeArrayIndex (uint64_t idx) inline
Definition at line 294 of file SValBuilder.h.
References ArrayIndexTy, and BasicVals.
Referenced by clang::ento::StoreManager::MakeElementRegion().
makeBoolVal() [1/2]
nonloc::ConcreteInt SValBuilder::makeBoolVal (const CXXBoolLiteralExpr * boolean)
Definition at line 123 of file SValBuilder.cpp.
References clang::CXXBoolLiteralExpr::getValue(), and makeTruthVal().
makeBoolVal() [2/2]
nonloc::ConcreteInt clang::ento::SValBuilder::makeBoolVal (const ObjCBoolLiteralExpr * boolean) inline
Definition at line 306 of file SValBuilder.h.
References clang::Expr::getType(), clang::ObjCBoolLiteralExpr::getValue(), and makeTruthVal().
Referenced by getConstantVal().
makeCompoundVal()
NonLoc clang::ento::SValBuilder::makeCompoundVal (QualType type, llvm::ImmutableList< SVal > vals) inline
Definition at line 272 of file SValBuilder.h.
References BasicVals, and clang::ento::BasicValueFactory::getCompoundValData().
Referenced by makeZeroVal(), and clang::ento::ExprEngine::VisitInitListExpr().
makeIntLocVal()
loc::ConcreteInt clang::ento::SValBuilder::makeIntLocVal (const llvm::APSInt & integer) inline
Definition at line 316 of file SValBuilder.h.
References BasicVals.
Referenced by evalCastSubKind().
makeIntVal() [1/5]
nonloc::ConcreteInt clang::ento::SValBuilder::makeIntVal (const IntegerLiteral * integer) inline
Definition at line 300 of file SValBuilder.h.
References BasicVals, clang::Expr::getType(), clang::APIntStorage::getValue(), and clang::Type::isUnsignedIntegerOrEnumerationType().
Referenced by clang::ento::ExprEngine::bindReturnValue(), evalBinOp(), evalCastSubKind(), clang::ento::nonloc::ConcreteInt::evalComplement(), clang::ento::ExprEngine::evalEagerlyAssumeBinOpBifurcation(), evalIntegralCast(), clang::ento::nonloc::ConcreteInt::evalMinus(), getConstantVal(), clang::ento::MemRegionManager::getStaticSize(), clang::ento::CheckerContext::isGreaterOrEqual(), clang::ento::CheckerContext::isNegative(), makeZeroVal(), clang::ento::ExprEngine::VisitCommonDeclRefExpr(), clang::ento::ExprEngine::VisitLogicalExpr(), and clang::ento::ExprEngine::VisitUnaryExprOrTypeTraitExpr().
makeIntVal() [2/5]
NonLoc clang::ento::SValBuilder::makeIntVal (const llvm::APInt & integer, bool isUnsigned) inline
Definition at line 320 of file SValBuilder.h.
References BasicVals.
makeIntVal() [3/5]
nonloc::ConcreteInt clang::ento::SValBuilder::makeIntVal (const llvm::APSInt & integer) inline
Definition at line 312 of file SValBuilder.h.
References BasicVals.
makeIntVal() [4/5]
NonLoc clang::ento::SValBuilder::makeIntVal (uint64_t integer, bool isUnsigned) inline
Definition at line 331 of file SValBuilder.h.
References BasicVals, and clang::ento::BasicValueFactory::getIntValue().
makeIntVal() [5/5]
DefinedSVal clang::ento::SValBuilder::makeIntVal (uint64_t integer, QualType type) inline
Definition at line 324 of file SValBuilder.h.
References BasicVals, and clang::ento::Loc::isLocType().
makeIntValWithWidth()
NonLoc clang::ento::SValBuilder::makeIntValWithWidth (QualType ptrType, uint64_t integer) inline
Definition at line 335 of file SValBuilder.h.
References BasicVals.
makeLazyCompoundVal()
NonLoc clang::ento::SValBuilder::makeLazyCompoundVal (const StoreRef & store, const TypedValueRegion * region) inline
Definition at line 276 of file SValBuilder.h.
References BasicVals, and clang::ento::BasicValueFactory::getLazyCompoundValData().
makeLoc() [1/4]
Loc clang::ento::SValBuilder::makeLoc (const AddrLabelExpr * expr) inline
Definition at line 390 of file SValBuilder.h.
References clang::ast_matchers::expr.
makeLoc() [2/4]
Loc clang::ento::SValBuilder::makeLoc (const llvm::APSInt & integer) inline
Definition at line 394 of file SValBuilder.h.
References BasicVals.
makeLoc() [3/4]
Loc clang::ento::SValBuilder::makeLoc (const MemRegion * region) inline
Definition at line 386 of file SValBuilder.h.
makeLoc() [4/4]
Loc clang::ento::SValBuilder::makeLoc (SymbolRef sym) inline
Definition at line 382 of file SValBuilder.h.
References clang::ento::MemRegionManager::getSymbolicRegion(), and MemMgr.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction(), getConstantVal(), clang::ento::ObjCMethodCall::getInitialStackFrameContents(), clang::ento::StoreManager::getLValueVar(), and makeSymbolVal().
makeLocAsInteger()
NonLoc clang::ento::SValBuilder::makeLocAsInteger (Loc loc, unsigned bits) inline
Definition at line 339 of file SValBuilder.h.
References BasicVals, and clang::ento::BasicValueFactory::getPersistentSValWithData().
Referenced by evalCastSubKind().
makeNonLoc() [1/4]
NonLoc clang::ento::SValBuilder::makeNonLoc (const llvm::APSInt & rhs, BinaryOperator::Opcode op, const SymExpr * lhs, QualType type)
makeNonLoc() [2/4]
NonLoc SValBuilder::makeNonLoc (const SymExpr * lhs, BinaryOperator::Opcode op, const llvm::APSInt & rhs, QualType type)
Definition at line 77 of file SValBuilder.cpp.
References clang::ento::SymbolManager::getSymIntExpr(), clang::ento::Loc::isLocType(), and SymMgr.
Referenced by evalCastSubKind(), evalIntegralCast(), and makeSymExprValNN().
makeNonLoc() [3/4]
NonLoc SValBuilder::makeNonLoc (const SymExpr * lhs, BinaryOperator::Opcode op, const SymExpr * rhs, QualType type)
Definition at line 95 of file SValBuilder.cpp.
References clang::ento::SymbolManager::getSymSymExpr(), clang::ento::Loc::isLocType(), and SymMgr.
makeNonLoc() [4/4]
NonLoc SValBuilder::makeNonLoc (const SymExpr * operand, QualType fromTy, QualType toTy)
Create a NonLoc value for cast.
Definition at line 102 of file SValBuilder.cpp.
References clang::ento::SymbolManager::getCastSymbol(), clang::ento::Loc::isLocType(), and SymMgr.
makeNullWithType()
Loc clang::ento::SValBuilder::makeNullWithType (QualType type) inline
Create NULL pointer, with proper pointer bit-width for given address space.
Parameters
type pointer type.
Definition at line 366 of file SValBuilder.h.
References BasicVals, Context, clang::ASTContext::getPointerType(), clang::ento::BasicValueFactory::getZeroWithTypeSize(), and clang::ast_matchers::type.
Referenced by getConstantVal(), makeZeroVal(), and clang::ento::ExprEngine::VisitCast().
makePointerToMember() [1/2]
NonLoc clang::ento::SValBuilder::makePointerToMember (const DeclaratorDecl * DD) inline
Definition at line 282 of file SValBuilder.h.
References clang::prec::PointerToMember.
Referenced by clang::ento::ExprEngine::VisitCast().
makePointerToMember() [2/2]
NonLoc clang::ento::SValBuilder::makePointerToMember (const PointerToMemberData * PTMD) inline
Definition at line 286 of file SValBuilder.h.
References clang::prec::PointerToMember.
makeSymbolVal()
SVal clang::ento::SValBuilder::makeSymbolVal (SymbolRef Sym) inline
Make an SVal that represents the given symbol.
This follows the convention of representing Loc-type symbols (symbolic pointers and references) as Loc values wrapping the symbol rather than as plain symbol values.
Definition at line 405 of file SValBuilder.h.
References clang::ento::SymExpr::getType(), clang::ento::Loc::isLocType(), and makeLoc().
Referenced by clang::ento::SMTConstraintManager::canReasonAbout(), and clang::ento::simplifyToSVal().
makeSymExprValNN()
SVal SValBuilder::makeSymExprValNN (BinaryOperator::Opcode op, NonLoc lhs, NonLoc rhs, QualType resultTy)
Constructs a symbolic expression for two non-location values.
Definition at line 409 of file SValBuilder.cpp.
References AnOpts, clang::ento::SymExpr::computeComplexity(), clang::ento::SVal::getAs(), clang::ento::SVal::getAsSymbol(), and makeNonLoc().
makeTruthVal() [1/2]
nonloc::ConcreteInt clang::ento::SValBuilder::makeTruthVal (bool b) inline
Definition at line 359 of file SValBuilder.h.
References b, BasicVals, and clang::ento::BasicValueFactory::getTruthValue().
makeTruthVal() [2/2]
nonloc::ConcreteInt clang::ento::SValBuilder::makeTruthVal (bool b, QualType type) inline
Definition at line 355 of file SValBuilder.h.
References b, BasicVals, and clang::ento::BasicValueFactory::getTruthValue().
Referenced by evalCastSubKind(), getConstantVal(), makeBoolVal(), and clang::ento::ExprEngine::VisitCast().
makeZeroArrayIndex()
NonLoc clang::ento::SValBuilder::makeZeroArrayIndex () inline
Definition at line 290 of file SValBuilder.h.
References ArrayIndexTy, and BasicVals.
Referenced by clang::ento::StoreManager::GetElementZeroRegion().
makeZeroVal()
DefinedOrUnknownSVal SValBuilder::makeZeroVal (QualType type)
Construct an SVal representing '0' for the specified type.
Definition at line 62 of file SValBuilder.cpp.
References BasicVals, clang::ento::BasicValueFactory::getEmptySValList(), clang::ento::Loc::isLocType(), makeCompoundVal(), makeIntVal(), and makeNullWithType().
Referenced by conjureSymbolVal(), getConstantVal(), getDerivedRegionValueSymbolVal(), clang::ento::ExprEngine::getInitialState(), getRegionValueSymbolVal(), and clang::ento::ExprEngine::VisitUnaryOperator().
simplifySVal()
virtual SVal clang::ento::SValBuilder::simplifySVal (ProgramStateRef State, SVal Val) pure virtual
Simplify symbolic expressions within a given SVal.
Return an SVal that represents the same value, but is hopefully easier to work with than the original SVal.
Referenced by clang::ento::simplifyToSVal().
simplifySymbolCast()
SVal clang::ento::SValBuilder::simplifySymbolCast (nonloc::SymbolVal V, QualType CastTy) protected
Reduce cast expression by removing redundant intermediate casts.
E.g.
(char)(short)(int x) -> (char)(int x)
(int)(int x) -> int x
Parameters
V – SymbolVal, which pressumably contains SymbolCast or any symbol that is applicable for cast operation.
CastTy – QualType, which V shall be cast to.
Returns
SVal with simplified cast expression.
Note
: Currently only support integral casts.
Definition at line 1009 of file SValBuilder.cpp.
References clang::ento::BasicValueFactory::getAPSIntType(), clang::ento::APSIntType::getBitWidth(), clang::QualType::getCanonicalType(), clang::ASTContext::getCanonicalType(), clang::ento::SymExpr::getType(), clang::ento::APSIntType::isUnsigned(), and V.
Referenced by evalCastSubKind().
Member Data Documentation
AnOpts
const AnalyzerOptions& clang::ento::SValBuilder::AnOpts protected
Definition at line 70 of file SValBuilder.h.
Referenced by getAnalyzerOptions(), and makeSymExprValNN().
ArrayIndexTy
const QualType clang::ento::SValBuilder::ArrayIndexTy protected
The scalar type to use for array indices.
Definition at line 73 of file SValBuilder.h.
Referenced by convertToArrayIndex(), getArrayIndexType(), makeArrayIndex(), and makeZeroArrayIndex().
ArrayIndexWidth
const unsigned clang::ento::SValBuilder::ArrayIndexWidth protected
The width of the scalar type used for array indices.
Definition at line 76 of file SValBuilder.h.
Referenced by convertToArrayIndex().
BasicVals
BasicValueFactory clang::ento::SValBuilder::BasicVals protected
Manager of APSInt values.
Definition at line 60 of file SValBuilder.h.
Referenced by evalCastSubKind(), getBasicValueFactory(), makeArrayIndex(), makeCompoundVal(), makeIntLocVal(), makeIntVal(), makeIntValWithWidth(), makeLazyCompoundVal(), makeLoc(), makeLocAsInteger(), makeNullWithType(), makeTruthVal(), makeZeroArrayIndex(), and makeZeroVal().
Context
ASTContext& clang::ento::SValBuilder::Context protected
Definition at line 57 of file SValBuilder.h.
Referenced by evalCast(), evalCastSubKind(), getConditionType(), getContext(), and makeNullWithType().
MemMgr
MemRegionManager clang::ento::SValBuilder::MemMgr protected
Manages the creation of memory regions.
Definition at line 66 of file SValBuilder.h.
Referenced by conjureSymbolVal(), getBlockPointer(), getDerivedRegionValueSymbolVal(), getFunctionPointer(), getMetadataSymbolVal(), getRegionManager(), getRegionValueSymbolVal(), and makeLoc().
StateMgr
ProgramStateManager& clang::ento::SValBuilder::StateMgr protected
Definition at line 68 of file SValBuilder.h.
Referenced by evalCastSubKind(), getCastedMemRegionVal(), and getStateManager().
SymMgr
SymbolManager clang::ento::SValBuilder::SymMgr protected
Manages the creation of symbols.
Definition at line 63 of file SValBuilder.h.
Referenced by conjureSymbol(), conjureSymbolVal(), evalCastSubKind(), getDerivedRegionValueSymbolVal(), getMetadataSymbolVal(), getRegionValueSymbolVal(), getSymbolManager(), and makeNonLoc().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h
lib/StaticAnalyzer/Core/SValBuilder.cpp