clang: clang::threadSafety::til::PrettyPrinter< Self, StreamType > Class Template Reference
clang::threadSafety::til::PrettyPrinter< Self, StreamType > Class Template Reference
#include "clang/Analysis/Analyses/ThreadSafetyTraverse.h"
Public Member Functions
PrettyPrinter (bool V=false, bool C=true, bool CS=true)
Static Public Member Functions
static void print (const SExpr *E, StreamType &SS)
Protected Member Functions
Self * self ()
void newline (StreamType &SS)
unsigned precedence (const SExpr *E)
void printBlockLabel (StreamType &SS, const BasicBlock *BB, int index)
void printSExpr (const SExpr *E, StreamType &SS, unsigned P, bool Sub=true)
void printNull (StreamType &SS)
void printFuture (const Future *E, StreamType &SS)
void printUndefined (const Undefined *E, StreamType &SS)
void printWildcard (const Wildcard *E, StreamType &SS)
template<class T >
void printLiteralT (const LiteralT< T > *E, StreamType &SS)
void printLiteralT (const LiteralT< uint8_t > *E, StreamType &SS)
void printLiteral (const Literal *E, StreamType &SS)
void printLiteralPtr (const LiteralPtr *E, StreamType &SS)
void printVariable (const Variable *V, StreamType &SS, bool IsVarDecl=false)
void printFunction (const Function *E, StreamType &SS, unsigned sugared=0)
void printSFunction (const SFunction *E, StreamType &SS)
void printCode (const Code *E, StreamType &SS)
void printField (const Field *E, StreamType &SS)
void printApply (const Apply *E, StreamType &SS, bool sugared=false)
void printSApply (const SApply *E, StreamType &SS)
void printProject (const Project *E, StreamType &SS)
void printCall (const Call *E, StreamType &SS)
void printAlloc (const Alloc *E, StreamType &SS)
void printLoad (const Load *E, StreamType &SS)
void printStore (const Store *E, StreamType &SS)
void printArrayIndex (const ArrayIndex *E, StreamType &SS)
void printArrayAdd (const ArrayAdd *E, StreamType &SS)
void printUnaryOp (const UnaryOp *E, StreamType &SS)
void printBinaryOp (const BinaryOp *E, StreamType &SS)
void printCast (const Cast *E, StreamType &SS)
void printSCFG (const SCFG *E, StreamType &SS)
void printBBInstr (const SExpr *E, StreamType &SS)
void printBasicBlock (const BasicBlock *E, StreamType &SS)
void printPhi (const Phi *E, StreamType &SS)
void printGoto (const Goto *E, StreamType &SS)
void printBranch (const Branch *E, StreamType &SS)
void printReturn (const Return *E, StreamType &SS)
void printIdentifier (const Identifier *E, StreamType &SS)
void printIfThenElse (const IfThenElse *E, StreamType &SS)
void printLet (const Let *E, StreamType &SS)
Static Protected Attributes
static const unsigned Prec_Atom = 0
static const unsigned Prec_Postfix = 1
static const unsigned Prec_Unary = 2
static const unsigned Prec_Binary = 3
static const unsigned Prec_Other = 4
static const unsigned Prec_Decl = 5
static const unsigned Prec_MAX = 6
Detailed Description
template<typename Self, typename StreamType>
class clang::threadSafety::til::PrettyPrinter< Self, StreamType >
Definition at line 405 of file ThreadSafetyTraverse.h.
Constructor & Destructor Documentation
PrettyPrinter()
template<typename Self , typename StreamType > clang::threadSafety::til::PrettyPrinter< Self, StreamType >::PrettyPrinter (bool V = false, bool C = true, bool CS = true) inline
Definition at line 417 of file ThreadSafetyTraverse.h.
Member Function Documentation
newline()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::newline (StreamType & SS) inline protected
Definition at line 428 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBasicBlock(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBBInstr(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSCFG().
precedence()
template<typename Self , typename StreamType > unsigned clang::threadSafety::til::PrettyPrinter< Self, StreamType >::precedence (const SExpr * E) inline protected
Definition at line 442 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::SExpr::opcode(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Atom, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Binary, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Decl, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Other, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Unary.
print()
template<typename Self , typename StreamType > static void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::print (const SExpr * E, StreamType & SS) inline static
Definition at line 420 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX.
printAlloc()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printAlloc (const Alloc * E, StreamType & SS) inline protected
Definition at line 746 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Alloc::dataType(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Other, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
printApply()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printApply (const Apply * E, StreamType & SS, bool sugared = false) inline protected
Definition at line 685 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Apply::arg(), clang::threadSafety::til::Apply::fun(), clang::threadSafety::til::SExpr::opcode(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCall().
printArrayAdd()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayAdd (const ArrayAdd * E, StreamType & SS) inline protected
Definition at line 770 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::ArrayAdd::array(), clang::threadSafety::til::ArrayAdd::index(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Atom, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
printArrayIndex()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayIndex (const ArrayIndex * E, StreamType & SS) inline protected
Definition at line 763 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::ArrayIndex::array(), clang::threadSafety::til::ArrayIndex::index(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
printBasicBlock()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBasicBlock (const BasicBlock * E, StreamType & SS) inline protected
Definition at line 842 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::BasicBlock::arguments(), clang::threadSafety::til::BasicBlock::blockID(), clang::threadSafety::til::BasicBlock::instructions(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::newline(), clang::threadSafety::til::BasicBlock::parent(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBBInstr(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), clang::T, and clang::threadSafety::til::BasicBlock::terminator().
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSCFG().
printBBInstr()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBBInstr (const SExpr * E, StreamType & SS) inline protected
Definition at line 826 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::SExpr::id(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::newline(), clang::threadSafety::til::SExpr::opcode(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and V.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBasicBlock().
printBinaryOp()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBinaryOp (const BinaryOp * E, StreamType & SS) inline protected
Definition at line 781 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::BinaryOp::binaryOpcode(), clang::threadSafety::til::BinaryOp::expr0(), clang::threadSafety::til::BinaryOp::expr1(), clang::threadSafety::til::getBinaryOpcodeString(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Binary, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
printBlockLabel()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBlockLabel (StreamType & SS, const BasicBlock * BB, int index) inline protected
Definition at line 485 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::BasicBlock::blockID().
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBranch(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printGoto().
printBranch()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBranch (const Branch * E, StreamType & SS) inline protected
Definition at line 883 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Branch::condition(), clang::threadSafety::til::Branch::elseBlock(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBlockLabel(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and clang::threadSafety::til::Branch::thenBlock().
printCall()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCall (const Call * E, StreamType & SS) inline protected
Definition at line 734 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printApply(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), clang::T, and clang::threadSafety::til::Call::target().
printCast()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCast (const Cast * E, StreamType & SS) inline protected
Definition at line 787 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::CAST_extendNum, clang::threadSafety::til::CAST_none, clang::threadSafety::til::CAST_objToPtr, clang::threadSafety::til::CAST_toFloat, clang::threadSafety::til::CAST_toInt, clang::threadSafety::til::CAST_truncNum, clang::threadSafety::til::Cast::castOpcode(), clang::threadSafety::til::Cast::expr(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Unary, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
printCode()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCode (const Code * E, StreamType & SS) inline protected
Definition at line 671 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Code::body(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Decl, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and clang::threadSafety::til::Code::returnType().
printField()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printField (const Field * E, StreamType & SS) inline protected
Definition at line 678 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Field::body(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Decl, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and clang::threadSafety::til::Field::range().
printFunction()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printFunction (const Function * E, StreamType & SS, unsigned sugared = 0) inline protected
Definition at line 639 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Function::body(), clang::threadSafety::til::Variable::definition(), clang::threadSafety::til::SExpr::opcode(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Decl, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printVariable(), and clang::threadSafety::til::Function::variableDecl().
printFuture()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printFuture (const Future * E, StreamType & SS) inline protected
Definition at line 529 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Future::maybeGetResult(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Atom, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
printGoto()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printGoto (const Goto * E, StreamType & SS) inline protected
Definition at line 878 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Goto::index(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBlockLabel(), and clang::threadSafety::til::Goto::targetBlock().
printIdentifier()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printIdentifier (const Identifier * E, StreamType & SS) inline protected
Definition at line 897 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Identifier::name().
printIfThenElse()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printIfThenElse (const IfThenElse * E, StreamType & SS) inline protected
Definition at line 901 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::IfThenElse::condition(), clang::threadSafety::til::IfThenElse::elseExpr(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Other, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Unary, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and clang::threadSafety::til::IfThenElse::thenExpr().
printLet()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLet (const Let * E, StreamType & SS) inline protected
Definition at line 918 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Let::body(), clang::threadSafety::til::Variable::definition(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Decl, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printVariable(), and clang::threadSafety::til::Let::variableDecl().
printLiteral()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLiteral (const Literal * E, StreamType & SS) inline protected
Definition at line 550 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Literal::as(), clang::threadSafety::til::ValueType::Base, clang::threadSafety::til::ValueType::BT_Bool, clang::threadSafety::til::ValueType::BT_Float, clang::threadSafety::til::ValueType::BT_Int, clang::threadSafety::til::ValueType::BT_Pointer, clang::threadSafety::til::ValueType::BT_String, clang::threadSafety::til::ValueType::BT_ValueRef, clang::threadSafety::til::ValueType::BT_Void, clang::threadSafety::til::Literal::clangExpr(), clang::threadSafety::getSourceLiteralString(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLiteralT(), clang::threadSafety::til::ValueType::Signed, clang::threadSafety::til::ValueType::Size, clang::threadSafety::til::ValueType::ST_16, clang::threadSafety::til::ValueType::ST_32, clang::threadSafety::til::ValueType::ST_64, clang::threadSafety::til::ValueType::ST_8, and clang::threadSafety::til::Literal::valueType().
printLiteralPtr()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLiteralPtr (const LiteralPtr * E, StreamType & SS) inline protected
Definition at line 625 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::LiteralPtr::clangDecl().
printLiteralT() [1/2]
template<typename Self , typename StreamType > template<class T > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLiteralT (const LiteralT< T > * E, StreamType & SS) inline protected
Definition at line 542 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::LiteralT< T >::value().
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLiteral().
printLiteralT() [2/2]
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLiteralT (const LiteralT< uint8_t > * E, StreamType & SS) inline protected
Definition at line 546 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::LiteralT< T >::value().
printLoad()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLoad (const Load * E, StreamType & SS) inline protected
Definition at line 751 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Load::pointer(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
printNull()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printNull (StreamType & SS) inline protected
Definition at line 525 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
printPhi()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printPhi (const Phi * E, StreamType & SS) inline protected
Definition at line 863 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Phi::PH_SingleVal, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), clang::threadSafety::til::Phi::status(), V, and clang::threadSafety::til::Phi::values().
printProject()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printProject (const Project * E, StreamType & SS) inline protected
Definition at line 708 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Project::clangDecl(), clang::NamedDecl::getQualifiedNameAsString(), clang::threadSafety::til::Project::isArrow(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), clang::threadSafety::til::Project::record(), clang::threadSafety::til::Project::slotName(), V, and clang::threadSafety::til::Variable::VK_SFun.
printReturn()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printReturn (const Return * E, StreamType & SS) inline protected
Definition at line 892 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Other, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and clang::threadSafety::til::Return::returnValue().
printSApply()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSApply (const SApply * E, StreamType & SS) inline protected
Definition at line 699 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::SApply::arg(), clang::threadSafety::til::SApply::isDelegation(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and clang::threadSafety::til::SApply::sfun().
printSCFG()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSCFG (const SCFG * E, StreamType & SS) inline protected
Definition at line 818 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::PrettyPrinter< Self, StreamType >::newline(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBasicBlock().
printSExpr()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr (const SExpr * E, StreamType & SS, unsigned P, bool Sub = true) inline protected
Definition at line 498 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::SExpr::block(), clang::threadSafety::til::SExpr::id(), clang::threadSafety::til::SExpr::opcode(), P, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX, and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printNull().
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printAlloc(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printApply(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayAdd(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayIndex(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBasicBlock(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBBInstr(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBinaryOp(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBranch(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCall(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCast(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCode(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printField(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printFunction(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printFuture(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printIfThenElse(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLet(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLoad(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printPhi(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printProject(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printReturn(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSApply(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSFunction(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printStore(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printUnaryOp().
printSFunction()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSFunction (const SFunction * E, StreamType & SS) inline protected
Definition at line 664 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::SFunction::body(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Decl, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printVariable(), and clang::threadSafety::til::SFunction::variableDecl().
printStore()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printStore (const Store * E, StreamType & SS) inline protected
Definition at line 757 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Store::destination(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Other, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and clang::threadSafety::til::Store::source().
printUnaryOp()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printUnaryOp (const UnaryOp * E, StreamType & SS) inline protected
Definition at line 776 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::UnaryOp::expr(), clang::threadSafety::til::getUnaryOpcodeString(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Unary, clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr(), and clang::threadSafety::til::UnaryOp::unaryOpcode().
printUndefined()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printUndefined (const Undefined * E, StreamType & SS) inline protected
Definition at line 533 of file ThreadSafetyTraverse.h.
printVariable()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printVariable (const Variable * V, StreamType & SS, bool IsVarDecl = false) inline protected
Definition at line 632 of file ThreadSafetyTraverse.h.
References V, and clang::threadSafety::til::Variable::VK_SFun.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printFunction(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLet(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSFunction().
printWildcard()
template<typename Self , typename StreamType > void clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printWildcard (const Wildcard * E, StreamType & SS) inline protected
Definition at line 537 of file ThreadSafetyTraverse.h.
self()
template<typename Self , typename StreamType > Self* clang::threadSafety::til::PrettyPrinter< Self, StreamType >::self () inline protected
Definition at line 426 of file ThreadSafetyTraverse.h.
Member Data Documentation
Prec_Atom
template<typename Self , typename StreamType > const unsigned clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Atom = 0 static protected
Definition at line 433 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::precedence(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayAdd(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printFuture().
Prec_Binary
template<typename Self , typename StreamType > const unsigned clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Binary = 3 static protected
Definition at line 436 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::precedence(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBinaryOp().
Prec_Decl
template<typename Self , typename StreamType > const unsigned clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Decl = 5 static protected
Definition at line 438 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::precedence(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCode(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printField(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printFunction(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLet(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSFunction().
Prec_MAX
template<typename Self , typename StreamType > const unsigned clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_MAX = 6 static protected
Definition at line 439 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::precedence(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::print(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printApply(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayIndex(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBasicBlock(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBBInstr(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printBranch(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printFunction(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printIfThenElse(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printPhi(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSApply(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSExpr().
Prec_Other
template<typename Self , typename StreamType > const unsigned clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Other = 4 static protected
Definition at line 437 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::precedence(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printAlloc(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printIfThenElse(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printReturn(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printStore().
Prec_Postfix
template<typename Self , typename StreamType > const unsigned clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Postfix = 1 static protected
Definition at line 434 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::precedence(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printApply(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayAdd(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayIndex(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCall(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printLoad(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printProject(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printSApply().
Prec_Unary
template<typename Self , typename StreamType > const unsigned clang::threadSafety::til::PrettyPrinter< Self, StreamType >::Prec_Unary = 2 static protected
Definition at line 435 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::precedence(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printCast(), clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printIfThenElse(), and clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printUnaryOp().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTraverse.h