clang: clang::dataflow::TopBoolValue Class Reference
clang::dataflow::TopBoolValue Class Reference final
A TopBoolValue represents a boolean that is explicitly unconstrained.
#include "clang/Analysis/FlowSensitive/Value.h"
Public Member Functions
TopBoolValue (const Formula &F)
Atom getAtom () const
Public Member Functions inherited from clang::dataflow::BoolValue
BoolValue (Kind ValueKind, const Formula &F)
const Formula & formula () const
Public Member Functions inherited from clang::dataflow::Value
Value (Kind ValKind)
Value (const Value &)=delete
Value & operator= (const Value &)=delete
virtual ~Value ()=default
Kind getKind () const
Value * getProperty (llvm::StringRef Name) const
Returns the value of the synthetic property with the given Name or null if the property isn't assigned a value.
void setProperty (llvm::StringRef Name, Value &Val)
Assigns Val as the value of the synthetic property with the given Name.
llvm::iterator_range< llvm::StringMap< Value * >::const_iterator > properties () const
Static Public Member Functions
static bool classof (const Value *Val)
Static Public Member Functions inherited from clang::dataflow::BoolValue
static bool classof (const Value *Val)
Additional Inherited Members
Public Types inherited from clang::dataflow::Value
enum class Kind {
Integer , Pointer , TopBool , AtomicBool ,
FormulaBool
}
Detailed Description
A TopBoolValue represents a boolean that is explicitly unconstrained.
This is equivalent to an AtomicBoolValue that does not appear anywhere else in a system of formula. Knowing the value is unconstrained is useful when e.g. reasoning about convergence.
Definition at line 116 of file Value.h.
Constructor & Destructor Documentation
TopBoolValue()
clang::dataflow::TopBoolValue::TopBoolValue (const Formula & F) inline
Definition at line 118 of file Value.h.
References clang::dataflow::Formula::AtomRef, and clang::dataflow::Formula::kind().
Member Function Documentation
classof()
static bool clang::dataflow::TopBoolValue::classof (const Value * Val) inline static
Definition at line 122 of file Value.h.
References clang::dataflow::Value::getKind(), and clang::dataflow::Value::TopBool.
getAtom()
Atom clang::dataflow::TopBoolValue::getAtom () const inline
Definition at line 126 of file Value.h.
References clang::dataflow::BoolValue::formula(), and clang::dataflow::Formula::getAtom().
The documentation for this class was generated from the following file:
include/clang/Analysis/FlowSensitive/Value.h