clang: clang::OMPOrderedClause Class Reference
clang::OMPOrderedClause Class Reference final
This represents 'ordered' clause in the '#pragma omp ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Expr * getNumForLoops () const
Return the number of associated for-loops.
void setLoopNumIterations (unsigned NumLoop, Expr *NumIterations)
Set number of iterations for the specified loop.
ArrayRef< Expr * > getLoopNumIterations () const
Get number of iterations for all the loops.
void setLoopCounter (unsigned NumLoop, Expr *Counter)
Set loop counter for the specified loop.
Expr * getLoopCounter (unsigned NumLoop)
Get loops counter for the specified loop.
const Expr * getLoopCounter (unsigned NumLoop) const
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPOrderedClause * Create (const ASTContext &C, Expr *Num, unsigned NumLoops, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build 'ordered' clause.
static OMPOrderedClause * CreateEmpty (const ASTContext &C, unsigned NumLoops)
Build an empty clause.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents 'ordered' clause in the '#pragma omp ...' directive.
#pragma omp for ordered (2)
In this example directive '#pragma omp for' has 'ordered' clause with parameter 2.
Definition at line 1830 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPOrderedClause::children () inline
Definition at line 1901 of file OpenMPClause.h.
children() [2/2]
const_child_range clang::OMPOrderedClause::children () const inline
Definition at line 1903 of file OpenMPClause.h.
classof()
static bool clang::OMPOrderedClause::classof (const OMPClause * T) inline static
Definition at line 1914 of file OpenMPClause.h.
References clang::T.
Create()
OMPOrderedClause * OMPOrderedClause::Create (const ASTContext & C, Expr * Num, unsigned NumLoops, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) static
Build 'ordered' clause.
Parameters
Num Expression, possibly associated with this clause.
NumLoops Number of loops, associated with this clause.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Definition at line 343 of file OpenMPClause.cpp.
References setLoopNumIterations().
Referenced by clang::SemaOpenMP::ActOnOpenMPOrderedClause().
CreateEmpty()
OMPOrderedClause * OMPOrderedClause::CreateEmpty (const ASTContext & C, unsigned NumLoops) static
Build an empty clause.
Definition at line 358 of file OpenMPClause.cpp.
References setLoopNumIterations().
Referenced by clang::OMPClauseReader::readClause().
getLoopCounter() [1/2]
Expr * OMPOrderedClause::getLoopCounter (unsigned NumLoop)
Get loops counter for the specified loop.
Definition at line 384 of file OpenMPClause.cpp.
getLoopCounter() [2/2]
const Expr * OMPOrderedClause::getLoopCounter (unsigned NumLoop) const
Definition at line 389 of file OpenMPClause.cpp.
getLoopNumIterations()
ArrayRef< Expr * > OMPOrderedClause::getLoopNumIterations () const
Get number of iterations for all the loops.
Definition at line 375 of file OpenMPClause.cpp.
getLParenLoc()
SourceLocation clang::OMPOrderedClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 1885 of file OpenMPClause.h.
getNumForLoops()
Expr* clang::OMPOrderedClause::getNumForLoops () const inline
Return the number of associated for-loops.
Definition at line 1888 of file OpenMPClause.h.
setLoopCounter()
void OMPOrderedClause::setLoopCounter (unsigned NumLoop, Expr * Counter)
Set loop counter for the specified loop.
Definition at line 379 of file OpenMPClause.cpp.
setLoopNumIterations()
void OMPOrderedClause::setLoopNumIterations (unsigned NumLoop, Expr * NumIterations)
Set number of iterations for the specified loop.
Definition at line 369 of file OpenMPClause.cpp.
Referenced by Create(), and CreateEmpty().
setLParenLoc()
void clang::OMPOrderedClause::setLParenLoc (SourceLocation Loc) inline
Sets the location of '('.
Definition at line 1882 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPOrderedClause::used_children () inline
Definition at line 1907 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPOrderedClause::used_children () const inline
Definition at line 1910 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 1833 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp