clang: clang::syntax::MutationsImpl Class Reference
clang::syntax::MutationsImpl Class Reference
Static Public Member Functions
static void addAfter (syntax::Node *Anchor, syntax::Node *New, NodeRole Role)
Add a new node with a specified role.
static void replace (syntax::Node *Old, syntax::Node *New)
Replace the node, keeping the role.
static void remove (syntax::Node *N)
Completely remove the node from its parent.
Detailed Description
Definition at line 27 of file Mutations.cpp.
Member Function Documentation
addAfter()
static void clang::syntax::MutationsImpl::addAfter (syntax::Node * Anchor, syntax::Node * New, NodeRole Role) inline static
Add a new node with a specified role.
Definition at line 30 of file Mutations.cpp.
References clang::syntax::Detached, clang::syntax::Node::isDetached(), and P.
remove()
static void clang::syntax::MutationsImpl::remove (syntax::Node * N) inline static
Completely remove the node from its parent.
Definition at line 65 of file Mutations.cpp.
References clang::syntax::Node::assertInvariants(), clang::syntax::Node::canModify(), clang::syntax::Node::getNextSibling(), clang::syntax::Node::getParent(), and P.
replace()
static void clang::syntax::MutationsImpl::replace (syntax::Node * Old, syntax::Node * New) inline static
Replace the node, keeping the role.
Definition at line 48 of file Mutations.cpp.
References clang::syntax::Node::canModify(), clang::syntax::Node::getNextSibling(), clang::syntax::Node::getParent(), clang::syntax::Node::isDetached(), and P.
The documentation for this class was generated from the following file:
lib/Tooling/Syntax/Mutations.cpp