clang: clang::SemaObjC Class Reference
clang::SemaObjC Class Reference
#include "clang/Sema/SemaObjC.h"
Classes
class GlobalMethodPool
struct ObjCArgInfo
Public Types
enum ObjCSubscriptKind { OS_Array , OS_Dictionary , OS_Error }
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Member Functions
SemaObjC (Sema &S)
ExprResult CheckObjCForCollectionOperand (SourceLocation forLoc, Expr *collection)
StmtResult ActOnObjCForCollectionStmt (SourceLocation ForColLoc, Stmt *First, Expr *collection, SourceLocation RParenLoc)
StmtResult FinishObjCForCollectionStmt (Stmt *ForCollection, Stmt *Body)
FinishObjCForCollectionStmt - Attach the body to a objective-C foreach statement.
StmtResult ActOnObjCAtCatchStmt (SourceLocation AtLoc, SourceLocation RParen, Decl *Parm, Stmt *Body)
StmtResult ActOnObjCAtFinallyStmt (SourceLocation AtLoc, Stmt *Body)
StmtResult ActOnObjCAtTryStmt (SourceLocation AtLoc, Stmt *Try, MultiStmtArg Catch, Stmt *Finally)
StmtResult BuildObjCAtThrowStmt (SourceLocation AtLoc, Expr *Throw)
StmtResult ActOnObjCAtThrowStmt (SourceLocation AtLoc, Expr *Throw, Scope *CurScope)
ExprResult ActOnObjCAtSynchronizedOperand (SourceLocation atLoc, Expr *operand)
StmtResult ActOnObjCAtSynchronizedStmt (SourceLocation AtLoc, Expr *SynchExpr, Stmt *SynchBody)
StmtResult ActOnObjCAutoreleasePoolStmt (SourceLocation AtLoc, Stmt *Body)
TypeResult actOnObjCProtocolQualifierType (SourceLocation lAngleLoc, ArrayRef< Decl * > protocols, ArrayRef< SourceLocation > protocolLocs, SourceLocation rAngleLoc)
Build a an Objective-C protocol-qualified 'id' type where no base type was specified.
TypeResult actOnObjCTypeArgsAndProtocolQualifiers (Scope *S, SourceLocation Loc, ParsedType BaseType, SourceLocation TypeArgsLAngleLoc, ArrayRef< ParsedType > TypeArgs, SourceLocation TypeArgsRAngleLoc, SourceLocation ProtocolLAngleLoc, ArrayRef< Decl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc)
Build a specialized and/or protocol-qualified Objective-C type.
QualType BuildObjCTypeParamType (const ObjCTypeParamDecl *Decl, SourceLocation ProtocolLAngleLoc, ArrayRef< ObjCProtocolDecl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc, bool FailOnError=false)
Build an Objective-C type parameter type.
QualType BuildObjCObjectType (QualType BaseType, SourceLocation Loc, SourceLocation TypeArgsLAngleLoc, ArrayRef< TypeSourceInfo * > TypeArgs, SourceLocation TypeArgsRAngleLoc, SourceLocation ProtocolLAngleLoc, ArrayRef< ObjCProtocolDecl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc, bool FailOnError, bool Rebuilding)
Build an Objective-C object pointer type.
ParsedType ActOnObjCInstanceType (SourceLocation Loc)
The parser has parsed the context-sensitive type 'instancetype' in an Objective-C message declaration.
void checkRetainCycles (ObjCMessageExpr *msg)
checkRetainCycles - Check whether an Objective-C message send might create an obvious retain cycle.
void checkRetainCycles (Expr *receiver, Expr *argument)
Check a property assign to see if it's likely to cause a retain cycle.
void checkRetainCycles (VarDecl *Var, Expr *Init)
bool CheckObjCString (Expr *Arg)
CheckObjCString - Checks that the argument to the builtin CFString constructor is correct Note: It might also make sense to do the UTF-16 conversion here (would simplify the backend).
bool CheckObjCMethodCall (ObjCMethodDecl *Method, SourceLocation loc, ArrayRef< const Expr * > Args)
void CheckObjCCircularContainer (ObjCMessageExpr *Message)
Check whether receiver is mutable ObjC container which attempts to add itself into the container.
void ActOnObjCContainerStartDefinition (ObjCContainerDecl *IDecl)
void ActOnObjCContainerFinishDefinition ()
void ActOnObjCTemporaryExitContainerContext (ObjCContainerDecl *ObjCCtx)
Invoked when we must temporarily exit the objective-c container scope for parsing/looking-up C constructs.
void ActOnObjCReenterContainerContext (ObjCContainerDecl *ObjCCtx)
const DeclContext * getCurObjCLexicalContext () const
ObjCProtocolDecl * LookupProtocol (IdentifierInfo *II, SourceLocation IdLoc, RedeclarationKind Redecl=RedeclarationKind::NotForRedeclaration)
Find the protocol with the given name, if any.
bool isObjCWritebackConversion (QualType FromType, QualType ToType, QualType &ConvertedType)
Determine whether this is an Objective-C writeback conversion, used for parameter passing when performing automatic reference counting.
ObjCSubscriptKind CheckSubscriptingKind (Expr *FromE)
CheckSubscriptingKind - This routine decide what type of indexing represented by "FromE" is being done.
void AddCFAuditedAttribute (Decl *D)
AddCFAuditedAttribute - Check whether we're currently within '#pragma clang arc_cf_code_audited' and, if so, consider adding the appropriate attribute.
bool isCFError (RecordDecl *D)
IdentifierInfo * getNSErrorIdent ()
Retrieve the identifier "NSError".
ObjC @property and @synthesize
Implementations are in SemaObjCProperty.cpp
void CheckObjCPropertyAttributes (Decl *PropertyPtrTy, SourceLocation Loc, unsigned &Attributes, bool propertyInPrimaryClass)
Ensure attributes are consistent with type.
void ProcessPropertyDecl (ObjCPropertyDecl *property)
Process the specified property declaration and create decls for the setters and getters as needed.
Decl * ActOnProperty (Scope *S, SourceLocation AtLoc, SourceLocation LParenLoc, FieldDeclarator &FD, ObjCDeclSpec &ODS, Selector GetterSel, Selector SetterSel, tok::ObjCKeywordKind MethodImplKind, DeclContext *lexicalDC=nullptr)
Decl * ActOnPropertyImplDecl (Scope *S, SourceLocation AtLoc, SourceLocation PropertyLoc, bool ImplKind, IdentifierInfo *PropertyId, IdentifierInfo *PropertyIvar, SourceLocation PropertyIvarLoc, ObjCPropertyQueryKind QueryKind)
ActOnPropertyImplDecl - This routine performs semantic checks and builds the AST node for a property implementation declaration; declared as @synthesize or @dynamic.
ObjCPropertyDecl * HandlePropertyInClassExtension (Scope *S, SourceLocation AtLoc, SourceLocation LParenLoc, FieldDeclarator &FD, Selector GetterSel, SourceLocation GetterNameLoc, Selector SetterSel, SourceLocation SetterNameLoc, const bool isReadWrite, unsigned &Attributes, const unsigned AttributesAsWritten, QualType T, TypeSourceInfo *TSI, tok::ObjCKeywordKind MethodImplKind)
Called by ActOnProperty to handle @property declarations in class extensions.
ObjCPropertyDecl * CreatePropertyDecl (Scope *S, ObjCContainerDecl *CDecl, SourceLocation AtLoc, SourceLocation LParenLoc, FieldDeclarator &FD, Selector GetterSel, SourceLocation GetterNameLoc, Selector SetterSel, SourceLocation SetterNameLoc, const bool isReadWrite, const unsigned Attributes, const unsigned AttributesAsWritten, QualType T, TypeSourceInfo *TSI, tok::ObjCKeywordKind MethodImplKind, DeclContext *lexicalDC=nullptr)
Called by ActOnProperty and HandlePropertyInClassExtension to handle creating the ObjcPropertyDecl for a category or @interface.
void DiagnosePropertyMismatch (ObjCPropertyDecl *Property, ObjCPropertyDecl *SuperProperty, const IdentifierInfo *Name, bool OverridingProtocolProperty)
DiagnosePropertyMismatch - Compares two properties for their attributes and types and warns on a variety of inconsistencies.
bool DiagnosePropertyAccessorMismatch (ObjCPropertyDecl *PD, ObjCMethodDecl *Getter, SourceLocation Loc)
void DiagnoseUnimplementedProperties (Scope *S, ObjCImplDecl *IMPDecl, ObjCContainerDecl *CDecl, bool SynthesizeProperties)
DiagnoseUnimplementedProperties - This routine warns on those properties which must be implemented by this implementation.
void diagnoseNullResettableSynthesizedSetters (const ObjCImplDecl *impDecl)
Diagnose any null-resettable synthesized setters.
void DefaultSynthesizeProperties (Scope *S, ObjCImplDecl *IMPDecl, ObjCInterfaceDecl *IDecl, SourceLocation AtEnd)
DefaultSynthesizeProperties - This routine default synthesizes all properties which must be synthesized in the class's @implementation.
void DefaultSynthesizeProperties (Scope *S, Decl *D, SourceLocation AtEnd)
bool IvarBacksCurrentMethodAccessor (ObjCInterfaceDecl *IFace, ObjCMethodDecl *Method, ObjCIvarDecl *IV)
IvarBacksCurrentMethodAccessor - This routine returns 'true' if 'IV' is an ivar synthesized for 'Method' and 'Method' is a property accessor declared in class 'IFace'.
void DiagnoseOwningPropertyGetterSynthesis (const ObjCImplementationDecl *D)
void DiagnoseMissingDesignatedInitOverrides (const ObjCImplementationDecl *ImplD, const ObjCInterfaceDecl *IFD)
void AtomicPropertySetterGetterRules (ObjCImplDecl *IMPDecl, ObjCInterfaceDecl *IDecl)
AtomicPropertySetterGetterRules - This routine enforces the rule (via warning) when atomic property has one but not the other user-declared setter or getter.
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
Public Attributes
RecordDecl * CFError = nullptr
The struct behind the CFErrorRef pointer.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
ObjC Declarations
Implementations are in SemaDeclObjC.cpp
enum ObjCSpecialMethodKind {
OSMK_None , OSMK_Alloc , OSMK_New , OSMK_Copy ,
OSMK_RetainingInit , OSMK_NonRetainingInit
}
enum MethodMatchStrategy { MMS_loose , MMS_strict }
enum ObjCContainerKind {
OCK_None = -1 , OCK_Interface = 0 , OCK_Protocol , OCK_Category ,
OCK_ClassExtension , OCK_Implementation , OCK_CategoryImplementation
}
enum ResultTypeCompatibilityKind { RTC_Compatible , RTC_Incompatible , RTC_Unknown }
Describes the compatibility of a result type with its method.
typedef llvm::SmallPtrSet< Selector, 8 > SelectorSet
using DeclGroupPtrTy = OpaquePtr< DeclGroupRef >
llvm::MapVector< Selector, SourceLocation > ReferencedSelectors
Method selectors used in a @selector expression.
GlobalMethodPool MethodPool
Method Pool - allows efficient lookup when typechecking messages to "id".
ObjCContainerKind getObjCContainerKind () const
DeclResult actOnObjCTypeParam (Scope *S, ObjCTypeParamVariance variance, SourceLocation varianceLoc, unsigned index, IdentifierInfo *paramName, SourceLocation paramLoc, SourceLocation colonLoc, ParsedType typeBound)
ObjCTypeParamList * actOnObjCTypeParamList (Scope *S, SourceLocation lAngleLoc, ArrayRef< Decl * > typeParams, SourceLocation rAngleLoc)
void popObjCTypeParamList (Scope *S, ObjCTypeParamList *typeParamList)
ObjCInterfaceDecl * ActOnStartClassInterface (Scope *S, SourceLocation AtInterfaceLoc, IdentifierInfo *ClassName, SourceLocation ClassLoc, ObjCTypeParamList *typeParamList, IdentifierInfo *SuperName, SourceLocation SuperLoc, ArrayRef< ParsedType > SuperTypeArgs, SourceRange SuperTypeArgsRange, Decl *const *ProtoRefs, unsigned NumProtoRefs, const SourceLocation *ProtoLocs, SourceLocation EndProtoLoc, const ParsedAttributesView &AttrList, SkipBodyInfo *SkipBody)
void ActOnSuperClassOfClassInterface (Scope *S, SourceLocation AtInterfaceLoc, ObjCInterfaceDecl *IDecl, IdentifierInfo *ClassName, SourceLocation ClassLoc, IdentifierInfo *SuperName, SourceLocation SuperLoc, ArrayRef< ParsedType > SuperTypeArgs, SourceRange SuperTypeArgsRange)
void ActOnTypedefedProtocols (SmallVectorImpl< Decl * > &ProtocolRefs, SmallVectorImpl< SourceLocation > &ProtocolLocs, IdentifierInfo *SuperName, SourceLocation SuperLoc)
ActOnTypedefedProtocols - this action finds protocol list as part of the typedef'ed use for a qualified super class and adds them to the list of the protocols.
Decl * ActOnCompatibilityAlias (SourceLocation AtCompatibilityAliasLoc, IdentifierInfo *AliasName, SourceLocation AliasLocation, IdentifierInfo *ClassName, SourceLocation ClassLocation)
ActOnCompatibilityAlias - this action is called after complete parsing of a @compatibility_alias declaration.
bool CheckForwardProtocolDeclarationForCircularDependency (IdentifierInfo *PName, SourceLocation &PLoc, SourceLocation PrevLoc, const ObjCList< ObjCProtocolDecl > &PList)
ObjCProtocolDecl * ActOnStartProtocolInterface (SourceLocation AtProtoInterfaceLoc, IdentifierInfo *ProtocolName, SourceLocation ProtocolLoc, Decl *const *ProtoRefNames, unsigned NumProtoRefs, const SourceLocation *ProtoLocs, SourceLocation EndProtoLoc, const ParsedAttributesView &AttrList, SkipBodyInfo *SkipBody)
ObjCCategoryDecl * ActOnStartCategoryInterface (SourceLocation AtInterfaceLoc, const IdentifierInfo *ClassName, SourceLocation ClassLoc, ObjCTypeParamList *typeParamList, const IdentifierInfo *CategoryName, SourceLocation CategoryLoc, Decl *const *ProtoRefs, unsigned NumProtoRefs, const SourceLocation *ProtoLocs, SourceLocation EndProtoLoc, const ParsedAttributesView &AttrList)
ObjCImplementationDecl * ActOnStartClassImplementation (SourceLocation AtClassImplLoc, const IdentifierInfo *ClassName, SourceLocation ClassLoc, const IdentifierInfo *SuperClassname, SourceLocation SuperClassLoc, const ParsedAttributesView &AttrList)
ObjCCategoryImplDecl * ActOnStartCategoryImplementation (SourceLocation AtCatImplLoc, const IdentifierInfo *ClassName, SourceLocation ClassLoc, const IdentifierInfo *CatName, SourceLocation CatLoc, const ParsedAttributesView &AttrList)
ActOnStartCategoryImplementation - Perform semantic checks on the category implementation declaration and build an ObjCCategoryImplDecl object.
DeclGroupPtrTy ActOnFinishObjCImplementation (Decl *ObjCImpDecl, ArrayRef< Decl * > Decls)
DeclGroupPtrTy ActOnForwardProtocolDeclaration (SourceLocation AtProtoclLoc, ArrayRef< IdentifierLocPair > IdentList, const ParsedAttributesView &attrList)
ActOnForwardProtocolDeclaration - Handle @protocol foo;.
void FindProtocolDeclaration (bool WarnOnDeclarations, bool ForObjCContainer, ArrayRef< IdentifierLocPair > ProtocolId, SmallVectorImpl< Decl * > &Protocols)
FindProtocolDeclaration - This routine looks up protocols and issues an error if they are not declared.
void DiagnoseTypeArgsAndProtocols (IdentifierInfo *ProtocolId, SourceLocation ProtocolLoc, IdentifierInfo *TypeArgId, SourceLocation TypeArgLoc, bool SelectProtocolFirst=false)
void actOnObjCTypeArgsOrProtocolQualifiers (Scope *S, ParsedType baseType, SourceLocation lAngleLoc, ArrayRef< IdentifierInfo * > identifiers, ArrayRef< SourceLocation > identifierLocs, SourceLocation rAngleLoc, SourceLocation &typeArgsLAngleLoc, SmallVectorImpl< ParsedType > &typeArgs, SourceLocation &typeArgsRAngleLoc, SourceLocation &protocolLAngleLoc, SmallVectorImpl< Decl * > &protocols, SourceLocation &protocolRAngleLoc, bool warnOnIncompleteProtocols)
Given a list of identifiers (and their locations), resolve the names to either Objective-C protocol qualifiers or type arguments, as appropriate.
void DiagnoseClassExtensionDupMethods (ObjCCategoryDecl *CAT, ObjCInterfaceDecl *ID)
DiagnoseClassExtensionDupMethods - Check for duplicate declaration of a class method in its extension.
Decl * ActOnAtEnd (Scope *S, SourceRange AtEnd, ArrayRef< Decl * > allMethods=std::nullopt, ArrayRef< DeclGroupPtrTy > allTUVars=std::nullopt)
Decl * ActOnMethodDeclaration (Scope *S, SourceLocation BeginLoc, SourceLocation EndLoc, tok::TokenKind MethodType, ObjCDeclSpec &ReturnQT, ParsedType ReturnType, ArrayRef< SourceLocation > SelectorLocs, Selector Sel, ObjCArgInfo *ArgInfo, DeclaratorChunk::ParamInfo *CParamInfo, unsigned CNumArgs, const ParsedAttributesView &AttrList, tok::ObjCKeywordKind MethodImplKind, bool isVariadic, bool MethodDefinition)
bool CheckARCMethodDecl (ObjCMethodDecl *method)
Check a method declaration for compatibility with the Objective-C ARC conventions.
bool checkInitMethod (ObjCMethodDecl *method, QualType receiverTypeIfCall)
Check whether the given method, which must be in the 'init' family, is a valid member of that family.
void CheckObjCMethodOverride (ObjCMethodDecl *NewMethod, const ObjCMethodDecl *Overridden)
Check whether the given new method is a valid override of the given overridden method, and set any properties that should be inherited.
void CheckObjCMethodDirectOverrides (ObjCMethodDecl *method, ObjCMethodDecl *overridden)
void CheckObjCMethodOverrides (ObjCMethodDecl *ObjCMethod, ObjCInterfaceDecl *CurrentClass, ResultTypeCompatibilityKind RTC)
void AddAnyMethodToGlobalPool (Decl *D)
AddAnyMethodToGlobalPool - Add any method, instance or factory to global pool.
void ActOnStartOfObjCMethodDef (Scope *S, Decl *D)
ActOnStartOfObjCMethodDef - This routine sets up parameters; invisible and user declared, in the method definition's AST.
bool isObjCMethodDecl (Decl *D)
void CheckImplementationIvars (ObjCImplementationDecl *ImpDecl, ObjCIvarDecl **Fields, unsigned nIvars, SourceLocation Loc)
CheckImplementationIvars - This routine checks if the instance variables listed in the implelementation match those listed in the interface.
void WarnConflictingTypedMethods (ObjCMethodDecl *Method, ObjCMethodDecl *MethodDecl, bool IsProtocolMethodDecl)
void CheckConflictingOverridingMethod (ObjCMethodDecl *Method, ObjCMethodDecl *Overridden, bool IsProtocolMethodDecl)
void WarnExactTypedMethods (ObjCMethodDecl *Method, ObjCMethodDecl *MethodDecl, bool IsProtocolMethodDecl)
WarnExactTypedMethods - This routine issues a warning if method implementation declaration matches exactly that of its declaration.
void MatchAllMethodDeclarations (const SelectorSet &InsMap, const SelectorSet &ClsMap, SelectorSet &InsMapSeen, SelectorSet &ClsMapSeen, ObjCImplDecl *IMPDecl, ObjCContainerDecl *IDecl, bool &IncompleteImpl, bool ImmediateClass, bool WarnCategoryMethodImpl=false)
MatchAllMethodDeclarations - Check methods declaraed in interface or or protocol against those declared in their implementations.
void CheckCategoryVsClassMethodMatches (ObjCCategoryImplDecl *CatIMP)
CheckCategoryVsClassMethodMatches - Checks that methods implemented in category matches with those implemented in its primary class and warns each time an exact match is found.
void ImplMethodsVsClassMethods (Scope *S, ObjCImplDecl *IMPDecl, ObjCContainerDecl *IDecl, bool IncompleteImpl=false)
ImplMethodsVsClassMethods - This is main routine to warn if any method remains unimplemented in the class or category @implementation.
DeclGroupPtrTy ActOnForwardClassDeclaration (SourceLocation Loc, IdentifierInfo **IdentList, SourceLocation *IdentLocs, ArrayRef< ObjCTypeParamList * > TypeParamLists, unsigned NumElts)
bool MatchTwoMethodDeclarations (const ObjCMethodDecl *Method, const ObjCMethodDecl *PrevMethod, MethodMatchStrategy strategy=MMS_strict)
MatchTwoMethodDeclarations - Checks if two methods' type match and returns true, or false, accordingly.
void addMethodToGlobalList (ObjCMethodList *List, ObjCMethodDecl *Method)
Add the given method to the list of globally-known methods.
void ReadMethodPool (Selector Sel)
Read the contents of the method pool for a given selector from external storage.
void updateOutOfDateSelector (Selector Sel)
bool CollectMultipleMethodsInGlobalPool (Selector Sel, SmallVectorImpl< ObjCMethodDecl * > &Methods, bool InstanceFirst, bool CheckTheOther, const ObjCObjectType *TypeBound=nullptr)
We first select the type of the method: Instance or Factory, then collect all methods with that type.
bool AreMultipleMethodsInGlobalPool (Selector Sel, ObjCMethodDecl *BestMethod, SourceRange R, bool receiverIdOrClass, SmallVectorImpl< ObjCMethodDecl * > &Methods)
void DiagnoseMultipleMethodInGlobalPool (SmallVectorImpl< ObjCMethodDecl * > &Methods, Selector Sel, SourceRange R, bool receiverIdOrClass)
const ObjCMethodDecl * SelectorsForTypoCorrection (Selector Sel, QualType ObjectType=QualType())
ObjCMethodDecl * LookupImplementedMethodInGlobalPool (Selector Sel)
LookupImplementedMethodInGlobalPool - Returns the method which has an implementation.
void DiagnoseDuplicateIvars (ObjCInterfaceDecl *ID, ObjCInterfaceDecl *SID)
DiagnoseDuplicateIvars - Check for duplicate ivars in the entire class at the start of @implementation.
bool CheckObjCDeclScope (Decl *D)
Checks that the Objective-C declaration is declared in the global scope.
void ActOnDefs (Scope *S, Decl *TagD, SourceLocation DeclStart, const IdentifierInfo *ClassName, SmallVectorImpl< Decl * > &Decls)
Called whenever @defs(ClassName) is encountered in the source.
VarDecl * BuildObjCExceptionDecl (TypeSourceInfo *TInfo, QualType ExceptionType, SourceLocation StartLoc, SourceLocation IdLoc, const IdentifierInfo *Id, bool Invalid=false)
Build a type-check a new Objective-C exception variable declaration.
Decl * ActOnObjCExceptionDecl (Scope *S, Declarator &D)
void CollectIvarsToConstructOrDestruct (ObjCInterfaceDecl *OI, SmallVectorImpl< ObjCIvarDecl * > &Ivars)
CollectIvarsToConstructOrDestruct - Collect those ivars which require initialization.
void DiagnoseUseOfUnimplementedSelectors ()
void DiagnoseUnusedBackingIvarInAccessor (Scope *S, const ObjCImplementationDecl *ImplD)
DiagnoseUnusedBackingIvarInAccessor - Issue an 'unused' warning if ivar which backs the property is not used in the property's accessor.
ObjCIvarDecl * GetIvarBackingPropertyAccessor (const ObjCMethodDecl *Method, const ObjCPropertyDecl *&PDecl) const
GetIvarBackingPropertyAccessor - If method is a property setter/getter and it property has a backing ivar, returns this ivar; otherwise, returns NULL.
void AddInstanceMethodToGlobalPool (ObjCMethodDecl *Method, bool impl=false)
AddInstanceMethodToGlobalPool - All instance methods in a translation unit are added to a global pool.
void AddFactoryMethodToGlobalPool (ObjCMethodDecl *Method, bool impl=false)
AddFactoryMethodToGlobalPool - Same as above, but for factory methods.
QualType AdjustParameterTypeForObjCAutoRefCount (QualType T, SourceLocation NameLoc, TypeSourceInfo *TSInfo)
ObjCInterfaceDecl * getObjCInterfaceDecl (const IdentifierInfo *&Id, SourceLocation IdLoc, bool TypoCorrection=false)
Look for an Objective-C class in the translation unit.
bool inferObjCARCLifetime (ValueDecl *decl)
void SetIvarInitializers (ObjCImplementationDecl *ObjCImplementation)
SetIvarInitializers - This routine builds initialization ASTs for the Objective-C implementation whose ivars need be initialized.
Decl * ActOnIvar (Scope *S, SourceLocation DeclStart, Declarator &D, Expr *BitWidth, tok::ObjCKeywordKind visibility)
ActOnIvar - Each ivar field of an objective-c class is passed into this in order to create an IvarDecl object for it.
ObjCContainerDecl * getObjCDeclContext () const
ObjC Expressions
Implementations are in SemaExprObjC.cpp
enum ObjCMessageKind { ObjCSuperMessage , ObjCInstanceMessage , ObjCClassMessage }
Describes the kind of message expression indicated by a message send that starts with an identifier.
enum ARCConversionResult { ACR_okay , ACR_unbridged , ACR_error }
enum ObjCLiteralKind {
LK_Array , LK_Dictionary , LK_Numeric , LK_Boxed ,
LK_String , LK_Block , LK_None
}
std::unique_ptr< NSAPI > NSAPIObj
Caches identifiers/selectors for NSFoundation APIs.
ObjCInterfaceDecl * NSNumberDecl
The declaration of the Objective-C NSNumber class.
ObjCInterfaceDecl * NSValueDecl
The declaration of the Objective-C NSValue class.
QualType NSNumberPointer
Pointer to NSNumber type (NSNumber *).
QualType NSValuePointer
Pointer to NSValue type (NSValue *).
ObjCMethodDecl * NSNumberLiteralMethods [NSAPI::NumNSNumberLiteralMethods]
The Objective-C NSNumber methods used to create NSNumber literals.
ObjCInterfaceDecl * NSStringDecl
The declaration of the Objective-C NSString class.
QualType NSStringPointer
Pointer to NSString type (NSString *).
ObjCMethodDecl * StringWithUTF8StringMethod
The declaration of the stringWithUTF8String: method.
ObjCMethodDecl * ValueWithBytesObjCTypeMethod
The declaration of the valueWithBytes:objCType: method.
ObjCInterfaceDecl * NSArrayDecl
The declaration of the Objective-C NSArray class.
ObjCMethodDecl * ArrayWithObjectsMethod
The declaration of the arrayWithObjects:count: method.
ObjCInterfaceDecl * NSDictionaryDecl
The declaration of the Objective-C NSDictionary class.
ObjCMethodDecl * DictionaryWithObjectsMethod
The declaration of the dictionaryWithObjects:forKeys:count: method.
QualType QIDNSCopying
id<NSCopying> type.
Selector RespondsToSelectorSel
will hold 'respondsToSelector:'
ExprResult HandleExprPropertyRefExpr (const ObjCObjectPointerType *OPT, Expr *BaseExpr, SourceLocation OpLoc, DeclarationName MemberName, SourceLocation MemberLoc, SourceLocation SuperLoc, QualType SuperType, bool Super)
HandleExprPropertyRefExpr - Handle foo.bar where foo is a pointer to an objective C interface.
ExprResult ActOnClassPropertyRefExpr (const IdentifierInfo &receiverName, const IdentifierInfo &propertyName, SourceLocation receiverNameLoc, SourceLocation propertyNameLoc)
ExprResult ParseObjCStringLiteral (SourceLocation *AtLocs, ArrayRef< Expr * > Strings)
ExprResult BuildObjCStringLiteral (SourceLocation AtLoc, StringLiteral *S)
ExprResult BuildObjCNumericLiteral (SourceLocation AtLoc, Expr *Number)
BuildObjCNumericLiteral - builds an ObjCBoxedExpr AST node for the numeric literal expression.
ExprResult ActOnObjCBoolLiteral (SourceLocation AtLoc, SourceLocation ValueLoc, bool Value)
ExprResult BuildObjCArrayLiteral (SourceRange SR, MultiExprArg Elements)
ExprResult BuildObjCBoxedExpr (SourceRange SR, Expr *ValueExpr)
BuildObjCBoxedExpr - builds an ObjCBoxedExpr AST node for the '@' prefixed parenthesized expression.
ExprResult BuildObjCSubscriptExpression (SourceLocation RB, Expr *BaseExpr, Expr *IndexExpr, ObjCMethodDecl *getterMethod, ObjCMethodDecl *setterMethod)
Build an ObjC subscript pseudo-object expression, given that that's supported by the runtime.
ExprResult BuildObjCDictionaryLiteral (SourceRange SR, MutableArrayRef< ObjCDictionaryElement > Elements)
ExprResult BuildObjCEncodeExpression (SourceLocation AtLoc, TypeSourceInfo *EncodedTypeInfo, SourceLocation RParenLoc)
ExprResult ParseObjCEncodeExpression (SourceLocation AtLoc, SourceLocation EncodeLoc, SourceLocation LParenLoc, ParsedType Ty, SourceLocation RParenLoc)
ExprResult ParseObjCSelectorExpression (Selector Sel, SourceLocation AtLoc, SourceLocation SelLoc, SourceLocation LParenLoc, SourceLocation RParenLoc, bool WarnMultipleSelectors)
ParseObjCSelectorExpression - Build selector expression for @selector.
ExprResult ParseObjCProtocolExpression (IdentifierInfo *ProtocolName, SourceLocation AtLoc, SourceLocation ProtoLoc, SourceLocation LParenLoc, SourceLocation ProtoIdLoc, SourceLocation RParenLoc)
ParseObjCProtocolExpression - Build protocol expression for @protocol.
ObjCMethodDecl * tryCaptureObjCSelf (SourceLocation Loc)
Try to capture an implicit reference to 'self'.
ObjCMessageKind getObjCMessageKind (Scope *S, IdentifierInfo *Name, SourceLocation NameLoc, bool IsSuper, bool HasTrailingDot, ParsedType &ReceiverType)
ExprResult ActOnSuperMessage (Scope *S, SourceLocation SuperLoc, Selector Sel, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg Args)
ExprResult BuildClassMessage (TypeSourceInfo *ReceiverTypeInfo, QualType ReceiverType, SourceLocation SuperLoc, Selector Sel, ObjCMethodDecl *Method, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg Args, bool isImplicit=false)
Build an Objective-C class message expression.
ExprResult BuildClassMessageImplicit (QualType ReceiverType, bool isSuperReceiver, SourceLocation Loc, Selector Sel, ObjCMethodDecl *Method, MultiExprArg Args)
ExprResult ActOnClassMessage (Scope *S, ParsedType Receiver, Selector Sel, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg Args)
ExprResult BuildInstanceMessage (Expr *Receiver, QualType ReceiverType, SourceLocation SuperLoc, Selector Sel, ObjCMethodDecl *Method, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg Args, bool isImplicit=false)
Build an Objective-C instance message expression.
ExprResult BuildInstanceMessageImplicit (Expr *Receiver, QualType ReceiverType, SourceLocation Loc, Selector Sel, ObjCMethodDecl *Method, MultiExprArg Args)
ExprResult ActOnInstanceMessage (Scope *S, Expr *Receiver, Selector Sel, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg Args)
ExprResult BuildObjCBridgedCast (SourceLocation LParenLoc, ObjCBridgeCastKind Kind, SourceLocation BridgeKeywordLoc, TypeSourceInfo *TSInfo, Expr *SubExpr)
ExprResult ActOnObjCBridgedCast (Scope *S, SourceLocation LParenLoc, ObjCBridgeCastKind Kind, SourceLocation BridgeKeywordLoc, ParsedType Type, SourceLocation RParenLoc, Expr *SubExpr)
void CheckTollFreeBridgeCast (QualType castType, Expr *castExpr)
void CheckObjCBridgeRelatedCast (QualType castType, Expr *castExpr)
bool CheckTollFreeBridgeStaticCast (QualType castType, Expr *castExpr, CastKind &Kind)
bool checkObjCBridgeRelatedComponents (SourceLocation Loc, QualType DestType, QualType SrcType, ObjCInterfaceDecl *&RelatedClass, ObjCMethodDecl *&ClassMethod, ObjCMethodDecl *&InstanceMethod, TypedefNameDecl *&TDNDecl, bool CfToNs, bool Diagnose=true)
bool CheckObjCBridgeRelatedConversions (SourceLocation Loc, QualType DestType, QualType SrcType, Expr *&SrcExpr, bool Diagnose=true)
bool isSelfExpr (Expr *RExpr)
Private Helper predicate to check for 'self'.
bool isSelfExpr (Expr *RExpr, const ObjCMethodDecl *Method)
ObjCMethodDecl * LookupMethodInQualifiedType (Selector Sel, const ObjCObjectPointerType *OPT, bool IsInstance)
LookupMethodInQualifiedType - Lookups up a method in protocol qualifier list of a qualified objective pointer type.
ObjCMethodDecl * LookupMethodInObjectType (Selector Sel, QualType Ty, bool IsInstance)
LookupMethodInType - Look up a method in an ObjCObjectType.
bool isKnownName (StringRef name)
ARCConversionResult CheckObjCConversion (SourceRange castRange, QualType castType, Expr *&op, CheckedConversionKind CCK, bool Diagnose=true, bool DiagnoseCFAudited=false, BinaryOperatorKind Opc=BO_PtrMemD)
Checks for invalid conversions and casts between retainable pointers and other pointer kinds for ARC and Weak.
Expr * stripARCUnbridgedCast (Expr *e)
stripARCUnbridgedCast - Given an expression of ARCUnbridgedCast type, remove the placeholder cast.
void diagnoseARCUnbridgedCast (Expr *e)
Given that we saw an expression with the ARCUnbridgedCastTy placeholder type, complain bitterly.
bool CheckObjCARCUnavailableWeakConversion (QualType castType, QualType ExprType)
bool CheckMessageArgumentTypes (const Expr *Receiver, QualType ReceiverType, MultiExprArg Args, Selector Sel, ArrayRef< SourceLocation > SelectorLocs, ObjCMethodDecl *Method, bool isClassMessage, bool isSuperMessage, SourceLocation lbrac, SourceLocation rbrac, SourceRange RecRange, QualType &ReturnType, ExprValueKind &VK)
CheckMessageArgumentTypes - Check types in an Obj-C message send.
QualType getMessageSendResultType (const Expr *Receiver, QualType ReceiverType, ObjCMethodDecl *Method, bool isClassMessage, bool isSuperMessage)
Determine the result of a message send expression based on the type of the receiver, the method expected to receive the message, and the form of the message send.
void EmitRelatedResultTypeNote (const Expr *E)
If the given expression involves a message send to a method with a related result type, emit a note describing what happened.
void EmitRelatedResultTypeNoteForReturn (QualType destType)
Given that we had incompatible pointer types in a return statement, check whether we're in a method with a related result type, and if so, emit a note describing what happened.
ObjCMethodDecl * LookupInstanceMethodInGlobalPool (Selector Sel, SourceRange R, bool receiverIdOrClass=false)
LookupInstanceMethodInGlobalPool - Returns the method and warns if there are multiple signatures.
ObjCMethodDecl * LookupFactoryMethodInGlobalPool (Selector Sel, SourceRange R, bool receiverIdOrClass=false)
LookupFactoryMethodInGlobalPool - Returns the method and warns if there are multiple signatures.
DeclResult LookupIvarInObjCMethod (LookupResult &Lookup, Scope *S, IdentifierInfo *II)
The parser has read a name in, and Sema has detected that we're currently inside an ObjC method.
ExprResult LookupInObjCMethod (LookupResult &LookUp, Scope *S, IdentifierInfo *II, bool AllowBuiltinCreation=false)
The parser has read a name in, and Sema has detected that we're currently inside an ObjC method.
ExprResult BuildIvarRefExpr (Scope *S, SourceLocation Loc, ObjCIvarDecl *IV)
QualType FindCompositeObjCPointerType (ExprResult &LHS, ExprResult &RHS, SourceLocation QuestionLoc)
FindCompositeObjCPointerType - Helper method to find composite type of two objective-c pointer types of the two input expressions.
bool CheckConversionToObjCLiteral (QualType DstType, Expr *&SrcExpr, bool Diagnose=true)
ExprResult ActOnObjCBoolLiteral (SourceLocation OpLoc, tok::TokenKind Kind)
ActOnObjCBoolLiteral - Parse {__objc_yes,__objc_no} literals.
ExprResult ActOnObjCAvailabilityCheckExpr (llvm::ArrayRef< AvailabilitySpec > AvailSpecs, SourceLocation AtLoc, SourceLocation RParen)
CastKind PrepareCastToObjCObjectPointer (ExprResult &E)
Prepare a conversion of the given expression to an ObjC object pointer type.
ObjCLiteralKind CheckLiteralKind (Expr *FromE)
Detailed Description
Definition at line 50 of file SemaObjC.h.
Member Typedef Documentation
DeclGroupPtrTy
using clang::SemaObjC::DeclGroupPtrTy = OpaquePtr<DeclGroupRef>
Definition at line 294 of file SemaObjC.h.
SelectorSet
typedef llvm::SmallPtrSet<Selector, 8> clang::SemaObjC::SelectorSet
Definition at line 213 of file SemaObjC.h.
Member Enumeration Documentation
ARCConversionResult
enum clang::SemaObjC::ARCConversionResult
Enumerator
ACR_okay
ACR_unbridged
ACR_error
Definition at line 793 of file SemaObjC.h.
MethodMatchStrategy
enum clang::SemaObjC::MethodMatchStrategy
Enumerator
MMS_loose
MMS_strict
Definition at line 215 of file SemaObjC.h.
ObjCContainerKind
enum clang::SemaObjC::ObjCContainerKind
Enumerator
OCK_None
OCK_Interface
OCK_Protocol
OCK_Category
OCK_ClassExtension
OCK_Implementation
OCK_CategoryImplementation
Definition at line 217 of file SemaObjC.h.
ObjCLiteralKind
enum clang::SemaObjC::ObjCLiteralKind
Enumerator
LK_Array
LK_Dictionary
LK_Numeric
LK_Boxed
LK_String
LK_Block
LK_None
Definition at line 896 of file SemaObjC.h.
ObjCMessageKind
enum clang::SemaObjC::ObjCMessageKind
Describes the kind of message expression indicated by a message send that starts with an identifier.
Enumerator
ObjCSuperMessage
The message is sent to 'super'.
ObjCInstanceMessage
The message is an instance message.
ObjCClassMessage
The message is a class message, and the identifier is a type name.
Definition at line 695 of file SemaObjC.h.
ObjCSpecialMethodKind
enum clang::SemaObjC::ObjCSpecialMethodKind
Enumerator
OSMK_None
OSMK_Alloc
OSMK_New
OSMK_Copy
OSMK_RetainingInit
OSMK_NonRetainingInit
Definition at line 175 of file SemaObjC.h.
ObjCSubscriptKind
enum clang::SemaObjC::ObjCSubscriptKind
Enumerator
OS_Array
OS_Dictionary
OS_Error
Definition at line 147 of file SemaObjC.h.
ResultTypeCompatibilityKind
enum clang::SemaObjC::ResultTypeCompatibilityKind
Describes the compatibility of a result type with its method.
Enumerator
RTC_Compatible
RTC_Incompatible
RTC_Unknown
Definition at line 368 of file SemaObjC.h.
Constructor & Destructor Documentation
SemaObjC()
clang::SemaObjC::SemaObjC (Sema & S)
Definition at line 25 of file SemaObjC.cpp.
Member Function Documentation
ActOnAtEnd()
Decl * SemaObjC::ActOnAtEnd (Scope * S, SourceRange AtEnd, ArrayRef< Decl * > allMethods = std::nullopt, ArrayRef< DeclGroupPtrTy > allTUVars = std::nullopt)
Check for instance method of the same name with incompatible types
The following allows us to typecheck messages to "id".
Check for class method of the same name with incompatible types
Definition at line 3986 of file SemaDeclObjC.cpp.
ActOnClassMessage()
ExprResult SemaObjC::ActOnClassMessage (Scope * S, ParsedType Receiver, Selector Sel, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg Args)
Definition at line 2766 of file SemaExprObjC.cpp.
ActOnClassPropertyRefExpr()
ExprResult SemaObjC::ActOnClassPropertyRefExpr (const IdentifierInfo & receiverName, const IdentifierInfo & propertyName, SourceLocation receiverNameLoc, SourceLocation propertyNameLoc)
Definition at line 2170 of file SemaExprObjC.cpp.
ActOnCompatibilityAlias()
Decl * SemaObjC::ActOnCompatibilityAlias (SourceLocation AtLoc, IdentifierInfo * AliasName, SourceLocation AliasLocation, IdentifierInfo * ClassName, SourceLocation ClassLocation)
ActOnCompatibilityAlias - this action is called after complete parsing of a @compatibility_alias declaration.
It sets up the alias relationships.
Definition at line 1143 of file SemaDeclObjC.cpp.
ActOnDefs()
void SemaObjC::ActOnDefs (Scope * S, Decl * TagD, SourceLocation DeclStart, const IdentifierInfo * ClassName, SmallVectorImpl< Decl * > & Decls)
Called whenever @defs(ClassName) is encountered in the source.
Inserts the instance variables of ClassName into Decls.
Definition at line 5116 of file SemaDeclObjC.cpp.
ActOnFinishObjCImplementation()
SemaObjC::DeclGroupPtrTy SemaObjC::ActOnFinishObjCImplementation (Decl * ObjCImpDecl, ArrayRef< Decl * > Decls)
Definition at line 2120 of file SemaDeclObjC.cpp.
References clang::Sema::BuildDeclaratorGroup(), clang::Decl::getDeclContext(), clang::DeclContext::isFileContext(), clang::SemaBase::SemaRef, and clang::Decl::setTopLevelDeclInObjCContainer().
ActOnForwardClassDeclaration()
SemaObjC::DeclGroupPtrTy SemaObjC::ActOnForwardClassDeclaration (SourceLocation Loc, IdentifierInfo ** IdentList, SourceLocation * IdentLocs, ArrayRef< ObjCTypeParamList * > TypeParamLists, unsigned NumElts)
Definition at line 3063 of file SemaDeclObjC.cpp.
ActOnForwardProtocolDeclaration()
SemaObjC::DeclGroupPtrTy SemaObjC::ActOnForwardProtocolDeclaration (SourceLocation AtProtoclLoc, ArrayRef< IdentifierLocPair > IdentList, const ParsedAttributesView & attrList)
ActOnForwardProtocolDeclaration - Handle @protocol foo;.
Definition at line 1788 of file SemaDeclObjC.cpp.
ActOnInstanceMessage()
ExprResult SemaObjC::ActOnInstanceMessage (Scope * S, Expr * Receiver, Selector Sel, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg Args)
Definition at line 3423 of file SemaExprObjC.cpp.
ActOnIvar()
Decl * SemaObjC::ActOnIvar (Scope * S, SourceLocation DeclStart, Declarator & D, Expr * BitWidth, tok::ObjCKeywordKind visibility)
ActOnIvar - Each ivar field of an objective-c class is passed into this in order to create an IvarDecl object for it.
Definition at line 5577 of file SemaDeclObjC.cpp.
ActOnMethodDeclaration()
Decl * SemaObjC::ActOnMethodDeclaration (Scope * S, SourceLocation BeginLoc, SourceLocation EndLoc, tok::TokenKind MethodType, ObjCDeclSpec & ReturnQT, ParsedType ReturnType, ArrayRef< SourceLocation > SelectorLocs, Selector Sel, ObjCArgInfo * ArgInfo, DeclaratorChunk::ParamInfo * CParamInfo, unsigned CNumArgs, const ParsedAttributesView & AttrList, tok::ObjCKeywordKind MethodImplKind, bool isVariadic, bool MethodDefinition)
Definition at line 4731 of file SemaDeclObjC.cpp.
ActOnObjCAtCatchStmt()
StmtResult clang::SemaObjC::ActOnObjCAtCatchStmt (SourceLocation AtLoc, SourceLocation RParen, Decl * Parm, Stmt * Body)
Definition at line 203 of file SemaObjC.cpp.
ActOnObjCAtFinallyStmt()
StmtResult clang::SemaObjC::ActOnObjCAtFinallyStmt (SourceLocation AtLoc, Stmt * Body)
Definition at line 214 of file SemaObjC.cpp.
ActOnObjCAtSynchronizedOperand()
ExprResult clang::SemaObjC::ActOnObjCAtSynchronizedOperand (SourceLocation atLoc, Expr * operand)
Definition at line 283 of file SemaObjC.cpp.
References clang::Sema::ActOnFinishFullExpr(), clang::Sema::DefaultLvalueConversion(), clang::SemaBase::Diag(), clang::ExprError(), clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getLangOpts(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::ActionResult< PtrTy, Compress >::isUsable(), clang::Sema::PerformContextuallyConvertToObjCPointer(), clang::ast_matchers::pointerType, clang::Sema::RequireCompleteType(), clang::SemaBase::SemaRef, and clang::ast_matchers::type.
ActOnObjCAtSynchronizedStmt()
StmtResult clang::SemaObjC::ActOnObjCAtSynchronizedStmt (SourceLocation AtLoc, Expr * SynchExpr, Stmt * SynchBody)
Definition at line 321 of file SemaObjC.cpp.
ActOnObjCAtThrowStmt()
StmtResult clang::SemaObjC::ActOnObjCAtThrowStmt (SourceLocation AtLoc, Expr * Throw, Scope * CurScope)
Definition at line 266 of file SemaObjC.cpp.
References BuildObjCAtThrowStmt(), clang::SemaBase::Diag(), clang::SemaBase::getLangOpts(), clang::Scope::getParent(), clang::Scope::isAtCatchScope(), and clang::StmtError().
ActOnObjCAtTryStmt()
StmtResult clang::SemaObjC::ActOnObjCAtTryStmt (SourceLocation AtLoc, Stmt * Try, MultiStmtArg Catch, Stmt * Finally)
Definition at line 219 of file SemaObjC.cpp.
ActOnObjCAutoreleasePoolStmt()
StmtResult clang::SemaObjC::ActOnObjCAutoreleasePoolStmt (SourceLocation AtLoc, Stmt * Body)
Definition at line 330 of file SemaObjC.cpp.
ActOnObjCAvailabilityCheckExpr()
ExprResult SemaObjC::ActOnObjCAvailabilityCheckExpr (llvm::ArrayRef< AvailabilitySpec > AvailSpecs, SourceLocation AtLoc, SourceLocation RParen)
Definition at line 5158 of file SemaExprObjC.cpp.
ActOnObjCBoolLiteral() [1/2]
ExprResult SemaObjC::ActOnObjCBoolLiteral (SourceLocation AtLoc, SourceLocation ValueLoc, bool Value)
Definition at line 373 of file SemaExprObjC.cpp.
ActOnObjCBoolLiteral() [2/2]
ExprResult SemaObjC::ActOnObjCBoolLiteral (SourceLocation OpLoc, tok::TokenKind Kind)
ActOnObjCBoolLiteral - Parse {__objc_yes,__objc_no} literals.
Definition at line 5136 of file SemaExprObjC.cpp.
ActOnObjCBridgedCast()
ExprResult SemaObjC::ActOnObjCBridgedCast (Scope * S, SourceLocation LParenLoc, ObjCBridgeCastKind Kind, SourceLocation BridgeKeywordLoc, ParsedType Type, SourceLocation RParenLoc, Expr * SubExpr)
Definition at line 4763 of file SemaExprObjC.cpp.
ActOnObjCContainerFinishDefinition()
void clang::SemaObjC::ActOnObjCContainerFinishDefinition ()
Definition at line 1279 of file SemaObjC.cpp.
References clang::Sema::PopDeclContext(), and clang::SemaBase::SemaRef.
Referenced by ActOnObjCTemporaryExitContainerContext().
ActOnObjCContainerStartDefinition()
void clang::SemaObjC::ActOnObjCContainerStartDefinition (ObjCContainerDecl * IDecl)
Definition at line 1272 of file SemaObjC.cpp.
References clang::Sema::CurContext, clang::DeclContext::getLexicalParent(), and clang::SemaBase::SemaRef.
Referenced by ActOnObjCReenterContainerContext().
ActOnObjCExceptionDecl()
Decl * SemaObjC::ActOnObjCExceptionDecl (Scope * S, Declarator & D)
Definition at line 5205 of file SemaDeclObjC.cpp.
ActOnObjCForCollectionStmt()
StmtResult clang::SemaObjC::ActOnObjCForCollectionStmt (SourceLocation ForColLoc, Stmt * First, Expr * collection, SourceLocation RParenLoc)
Definition at line 32 of file SemaObjC.cpp.
ActOnObjCInstanceType()
ParsedType clang::SemaObjC::ActOnObjCInstanceType (SourceLocation Loc)
The parser has parsed the context-sensitive type 'instancetype' in an Objective-C message declaration.
Return the appropriate type.
Definition at line 741 of file SemaObjC.cpp.
actOnObjCProtocolQualifierType()
TypeResult clang::SemaObjC::actOnObjCProtocolQualifierType (SourceLocation lAngleLoc, ArrayRef< Decl * > protocols, ArrayRef< SourceLocation > protocolLocs, SourceLocation rAngleLoc)
Build a an Objective-C protocol-qualified 'id' type where no base type was specified.
Definition at line 337 of file SemaObjC.cpp.
ActOnObjCReenterContainerContext()
void clang::SemaObjC::ActOnObjCReenterContainerContext (ObjCContainerDecl * ObjCCtx)
Definition at line 1291 of file SemaObjC.cpp.
References ActOnObjCContainerStartDefinition(), clang::Sema::OriginalLexicalContext, and clang::SemaBase::SemaRef.
ActOnObjCTemporaryExitContainerContext()
void clang::SemaObjC::ActOnObjCTemporaryExitContainerContext (ObjCContainerDecl * ObjCCtx)
Invoked when we must temporarily exit the objective-c container scope for parsing/looking-up C constructs.
Must be followed by a call to
See also
ActOnObjCReenterContainerContext
Definition at line 1284 of file SemaObjC.cpp.
References ActOnObjCContainerFinishDefinition(), clang::Sema::CurContext, clang::Sema::OriginalLexicalContext, and clang::SemaBase::SemaRef.
actOnObjCTypeArgsAndProtocolQualifiers()
TypeResult clang::SemaObjC::actOnObjCTypeArgsAndProtocolQualifiers (Scope * S, SourceLocation Loc, ParsedType BaseType, SourceLocation TypeArgsLAngleLoc, ArrayRef< ParsedType > TypeArgs, SourceLocation TypeArgsRAngleLoc, SourceLocation ProtocolLAngleLoc, ArrayRef< Decl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc)
Build a specialized and/or protocol-qualified Objective-C type.
Definition at line 374 of file SemaObjC.cpp.
actOnObjCTypeArgsOrProtocolQualifiers()
void SemaObjC::actOnObjCTypeArgsOrProtocolQualifiers (Scope * S, ParsedType baseType, SourceLocation lAngleLoc, ArrayRef< IdentifierInfo * > identifiers, ArrayRef< SourceLocation > identifierLocs, SourceLocation rAngleLoc, SourceLocation & typeArgsLAngleLoc, SmallVectorImpl< ParsedType > & typeArgs, SourceLocation & typeArgsRAngleLoc, SourceLocation & protocolLAngleLoc, SmallVectorImpl< Decl * > & protocols, SourceLocation & protocolRAngleLoc, bool warnOnIncompleteProtocols)
Given a list of identifiers (and their locations), resolve the names to either Objective-C protocol qualifiers or type arguments, as appropriate.
Definition at line 1427 of file SemaDeclObjC.cpp.
actOnObjCTypeParam()
DeclResult SemaObjC::actOnObjCTypeParam (Scope * S, ObjCTypeParamVariance variance, SourceLocation varianceLoc, unsigned index, IdentifierInfo * paramName, SourceLocation paramLoc, SourceLocation colonLoc, ParsedType typeBound)
Definition at line 667 of file SemaDeclObjC.cpp.
actOnObjCTypeParamList()
ObjCTypeParamList * SemaObjC::actOnObjCTypeParamList (Scope * S, SourceLocation lAngleLoc, ArrayRef< Decl * > typeParams, SourceLocation rAngleLoc)
Definition at line 770 of file SemaDeclObjC.cpp.
ActOnProperty()
Decl * SemaObjC::ActOnProperty (Scope * S, SourceLocation AtLoc, SourceLocation LParenLoc, FieldDeclarator & FD, ObjCDeclSpec & ODS, Selector GetterSel, Selector SetterSel, tok::ObjCKeywordKind MethodImplKind, DeclContext * lexicalDC = nullptr)
Definition at line 174 of file SemaObjCProperty.cpp.
ActOnPropertyImplDecl()
Decl * SemaObjC::ActOnPropertyImplDecl (Scope * S, SourceLocation AtLoc, SourceLocation PropertyLoc, bool ImplKind, IdentifierInfo * PropertyId, IdentifierInfo * PropertyIvar, SourceLocation PropertyIvarLoc, ObjCPropertyQueryKind QueryKind)
ActOnPropertyImplDecl - This routine performs semantic checks and builds the AST node for a property implementation declaration; declared as @synthesize or @dynamic.
Definition at line 1062 of file SemaObjCProperty.cpp.
ActOnStartCategoryImplementation()
ObjCCategoryImplDecl * SemaObjC::ActOnStartCategoryImplementation (SourceLocation AtCatImplLoc, const IdentifierInfo * ClassName, SourceLocation ClassLoc, const IdentifierInfo * CatName, SourceLocation CatLoc, const ParsedAttributesView & AttrList)
ActOnStartCategoryImplementation - Perform semantic checks on the category implementation declaration and build an ObjCCategoryImplDecl object.
Check that class of this category is already completely declared.
Check that CatName, category name, is not used in another implementation.
Definition at line 1915 of file SemaDeclObjC.cpp.
ActOnStartCategoryInterface()
ObjCCategoryDecl * SemaObjC::ActOnStartCategoryInterface (SourceLocation AtInterfaceLoc, const IdentifierInfo * ClassName, SourceLocation ClassLoc, ObjCTypeParamList * typeParamList, const IdentifierInfo * CategoryName, SourceLocation CategoryLoc, Decl *const * ProtoRefs, unsigned NumProtoRefs, const SourceLocation * ProtoLocs, SourceLocation EndProtoLoc, const ParsedAttributesView & AttrList)
Check that class of this category is already completely declared.
Check for duplicate interface declaration for this category
Definition at line 1816 of file SemaDeclObjC.cpp.
ActOnStartClassImplementation()
ObjCImplementationDecl * SemaObjC::ActOnStartClassImplementation (SourceLocation AtClassImplLoc, const IdentifierInfo * ClassName, SourceLocation ClassLoc, const IdentifierInfo * SuperClassname, SourceLocation SuperClassLoc, const ParsedAttributesView & AttrList)
Definition at line 1983 of file SemaDeclObjC.cpp.
ActOnStartClassInterface()
ObjCInterfaceDecl * SemaObjC::ActOnStartClassInterface (Scope * S, SourceLocation AtInterfaceLoc, IdentifierInfo * ClassName, SourceLocation ClassLoc, ObjCTypeParamList * typeParamList, IdentifierInfo * SuperName, SourceLocation SuperLoc, ArrayRef< ParsedType > SuperTypeArgs, SourceRange SuperTypeArgsRange, Decl *const * ProtoRefs, unsigned NumProtoRefs, const SourceLocation * ProtoLocs, SourceLocation EndProtoLoc, const ParsedAttributesView & AttrList, SkipBodyInfo * SkipBody)
Definition at line 975 of file SemaDeclObjC.cpp.
ActOnStartOfObjCMethodDef()
void SemaObjC::ActOnStartOfObjCMethodDef (Scope * S, Decl * D)
ActOnStartOfObjCMethodDef - This routine sets up parameters; invisible and user declared, in the method definition's AST.
Definition at line 369 of file SemaDeclObjC.cpp.
ActOnStartProtocolInterface()
ObjCProtocolDecl * SemaObjC::ActOnStartProtocolInterface (SourceLocation AtProtoInterfaceLoc, IdentifierInfo * ProtocolName, SourceLocation ProtocolLoc, Decl *const * ProtoRefNames, unsigned NumProtoRefs, const SourceLocation * ProtoLocs, SourceLocation EndProtoLoc, const ParsedAttributesView & AttrList, SkipBodyInfo * SkipBody)
Check then save referenced protocols.
Definition at line 1217 of file SemaDeclObjC.cpp.
ActOnSuperClassOfClassInterface()
void SemaObjC::ActOnSuperClassOfClassInterface (Scope * S, SourceLocation AtInterfaceLoc, ObjCInterfaceDecl * IDecl, IdentifierInfo * ClassName, SourceLocation ClassLoc, IdentifierInfo * SuperName, SourceLocation SuperLoc, ArrayRef< ParsedType > SuperTypeArgs, SourceRange SuperTypeArgsRange)
Definition at line 553 of file SemaDeclObjC.cpp.
ActOnSuperMessage()
ExprResult SemaObjC::ActOnSuperMessage (Scope * S, SourceLocation SuperLoc, Selector Sel, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg Args)
Definition at line 2392 of file SemaExprObjC.cpp.
ActOnTypedefedProtocols()
void SemaObjC::ActOnTypedefedProtocols (SmallVectorImpl< Decl * > & ProtocolRefs, SmallVectorImpl< SourceLocation > & ProtocolLocs, IdentifierInfo * SuperName, SourceLocation SuperLoc)
ActOnTypedefedProtocols - this action finds protocol list as part of the typedef'ed use for a qualified super class and adds them to the list of the protocols.
Definition at line 1116 of file SemaDeclObjC.cpp.
References clang::Type::getAs(), clang::Type::isObjCObjectType(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupSingleName(), clang::SemaBase::SemaRef, clang::T, and clang::Sema::TUScope.
AddAnyMethodToGlobalPool()
void SemaObjC::AddAnyMethodToGlobalPool (Decl * D)
AddAnyMethodToGlobalPool - Add any method, instance or factory to global pool.
Definition at line 336 of file SemaDeclObjC.cpp.
References AddFactoryMethodToGlobalPool(), AddInstanceMethodToGlobalPool(), and clang::ObjCMethodDecl::isInstanceMethod().
AddCFAuditedAttribute()
void clang::SemaObjC::AddCFAuditedAttribute (Decl * D)
AddCFAuditedAttribute - Check whether we're currently within '#pragma clang arc_cf_code_audited' and, if so, consider adding the appropriate attribute.
Definition at line 1443 of file SemaObjC.cpp.
AddFactoryMethodToGlobalPool()
void clang::SemaObjC::AddFactoryMethodToGlobalPool (ObjCMethodDecl * Method, bool impl = false) inline
AddFactoryMethodToGlobalPool - Same as above, but for factory methods.
Definition at line 517 of file SemaObjC.h.
Referenced by AddAnyMethodToGlobalPool().
AddInstanceMethodToGlobalPool()
void clang::SemaObjC::AddInstanceMethodToGlobalPool (ObjCMethodDecl * Method, bool impl = false) inline
AddInstanceMethodToGlobalPool - All instance methods in a translation unit are added to a global pool.
This allows us to efficiently associate a selector with a method declaraation for purposes of typechecking messages sent to "id" (where the class of the object is unknown).
Definition at line 511 of file SemaObjC.h.
Referenced by AddAnyMethodToGlobalPool().
addMethodToGlobalList()
void SemaObjC::addMethodToGlobalList (ObjCMethodList * List, ObjCMethodDecl * Method)
Add the given method to the list of globally-known methods.
Definition at line 3322 of file SemaDeclObjC.cpp.
AdjustParameterTypeForObjCAutoRefCount()
QualType SemaObjC::AdjustParameterTypeForObjCAutoRefCount (QualType T, SourceLocation NameLoc, TypeSourceInfo * TSInfo)
Definition at line 5395 of file SemaDeclObjC.cpp.
AreMultipleMethodsInGlobalPool()
bool SemaObjC::AreMultipleMethodsInGlobalPool (Selector Sel, ObjCMethodDecl * BestMethod, SourceRange R, bool receiverIdOrClass, SmallVectorImpl< ObjCMethodDecl * > & Methods)
Definition at line 3555 of file SemaDeclObjC.cpp.
References DiagnoseMultipleMethodInGlobalPool(), clang::SemaObjC::GlobalMethodPool::end(), clang::SemaObjC::GlobalMethodPool::find(), clang::Decl::hasAttr(), clang::ObjCMethodList::hasMoreThanOneDecl(), clang::ObjCMethodDecl::isInstanceMethod(), and MethodPool.
AtomicPropertySetterGetterRules()
void SemaObjC::AtomicPropertySetterGetterRules (ObjCImplDecl * IMPDecl, ObjCInterfaceDecl * IDecl)
AtomicPropertySetterGetterRules - This routine enforces the rule (via warning) when atomic property has one but not the other user-declared setter or getter.
Definition at line 2144 of file SemaObjCProperty.cpp.
References clang::FixItHint::CreateInsertion(), clang::SemaBase::Diag(), clang::ObjCPropertyImplDecl::Dynamic, clang::ObjCImplDecl::FindPropertyImplDecl(), clang::ObjCContainerDecl::getClassMethod(), clang::ObjCContainerDecl::getInstanceMethod(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::Sema::getLocForEndOfToken(), clang::ObjCMethodDecl::isSynthesizedAccessorStub(), clang::ObjCPropertyAttribute::kind_atomic, clang::ObjCPropertyAttribute::kind_nonatomic, clang::ObjCPropertyAttribute::kind_readwrite, clang::ObjCInterfaceDecl::known_extensions(), clang::LangOptionsBase::NonGC, clang::ObjCContainerDecl::properties(), clang::Property, and clang::SemaBase::SemaRef.
BuildClassMessage()
ExprResult SemaObjC::BuildClassMessage (TypeSourceInfo * ReceiverTypeInfo, QualType ReceiverType, SourceLocation SuperLoc, Selector Sel, ObjCMethodDecl * Method, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg ArgsIn, bool isImplicit = false)
Build an Objective-C class message expression.
This routine takes care of both normal class messages and class messages to the superclass.
Parameters
ReceiverTypeInfo Type source information that describes the receiver of this message. This may be NULL, in which case we are sending to the superclass and SuperLoc must be a valid source location.
ReceiverType The type of the object receiving the message. When ReceiverTypeInfo is non-NULL, this is the same type as that refers to. For a superclass send, this is the type of the superclass.
SuperLoc The location of the "super" keyword in a superclass message.
Sel The selector to which the message is being sent.
Method The method that this class message is invoking, if already known.
LBracLoc The location of the opening square bracket ']'.
RBracLoc The location of the closing square bracket ']'.
ArgsIn The message arguments.
Definition at line 2618 of file SemaExprObjC.cpp.
Referenced by clang::TreeTransform< Derived >::RebuildObjCMessageExpr().
BuildClassMessageImplicit()
ExprResult SemaObjC::BuildClassMessageImplicit (QualType ReceiverType, bool isSuperReceiver, SourceLocation Loc, Selector Sel, ObjCMethodDecl * Method, MultiExprArg Args)
Definition at line 2442 of file SemaExprObjC.cpp.
BuildInstanceMessage()
ExprResult SemaObjC::BuildInstanceMessage (Expr * Receiver, QualType ReceiverType, SourceLocation SuperLoc, Selector Sel, ObjCMethodDecl * Method, SourceLocation LBracLoc, ArrayRef< SourceLocation > SelectorLocs, SourceLocation RBracLoc, MultiExprArg ArgsIn, bool isImplicit = false)
Build an Objective-C instance message expression.
This routine takes care of both normal instance messages and instance messages to the superclass instance.
Parameters
Receiver The expression that computes the object that will receive this message. This may be empty, in which case we are sending to the superclass instance and SuperLoc must be a valid source location.
ReceiverType The (static) type of the object receiving the message. When a Receiver expression is provided, this is the same type as that expression. For a superclass instance send, this is a pointer to the type of the superclass.
SuperLoc The location of the "super" keyword in a superclass instance message.
Sel The selector to which the message is being sent.
Method The method that this instance message is invoking, if already known.
LBracLoc The location of the opening square bracket ']'.
RBracLoc The location of the closing square bracket ']'.
ArgsIn The message arguments.
Definition at line 2843 of file SemaExprObjC.cpp.
References clang::SourceLocation::isValid().
Referenced by BuildInstanceMessageImplicit(), and clang::TreeTransform< Derived >::RebuildObjCMessageExpr().
BuildInstanceMessageImplicit()
ExprResult SemaObjC::BuildInstanceMessageImplicit (Expr * Receiver, QualType ReceiverType, SourceLocation Loc, Selector Sel, ObjCMethodDecl * Method, MultiExprArg Args)
Definition at line 2787 of file SemaExprObjC.cpp.
References BuildInstanceMessage(), and Loc.
BuildIvarRefExpr()
ExprResult SemaObjC::BuildIvarRefExpr (Scope * S, SourceLocation Loc, ObjCIvarDecl * IV)
Definition at line 4871 of file SemaExprObjC.cpp.
BuildObjCArrayLiteral()
ExprResult SemaObjC::BuildObjCArrayLiteral (SourceRange SR, MultiExprArg Elements)
Definition at line 800 of file SemaExprObjC.cpp.
BuildObjCAtThrowStmt()
StmtResult clang::SemaObjC::BuildObjCAtThrowStmt (SourceLocation AtLoc, Expr * Throw)
Definition at line 239 of file SemaObjC.cpp.
Referenced by ActOnObjCAtThrowStmt().
BuildObjCBoxedExpr()
ExprResult SemaObjC::BuildObjCBoxedExpr (SourceRange SR, Expr * ValueExpr)
BuildObjCBoxedExpr - builds an ObjCBoxedExpr AST node for the '@' prefixed parenthesized expression.
The type of the expression will either be "NSNumber *", "NSString *" or "NSValue *" depending on the type of ValueType, which is allowed to be a built-in numeric type, "char *", "const char *" or C structure with attribute 'objc_boxable'.
Definition at line 509 of file SemaExprObjC.cpp.
BuildObjCBridgedCast()
ExprResult SemaObjC::BuildObjCBridgedCast (SourceLocation LParenLoc, ObjCBridgeCastKind Kind, SourceLocation BridgeKeywordLoc, TypeSourceInfo * TSInfo, Expr * SubExpr)
Definition at line 4651 of file SemaExprObjC.cpp.
BuildObjCDictionaryLiteral()
ExprResult SemaObjC::BuildObjCDictionaryLiteral (SourceRange SR, MutableArrayRef< ObjCDictionaryElement > Elements)
Definition at line 960 of file SemaExprObjC.cpp.
BuildObjCEncodeExpression()
ExprResult SemaObjC::BuildObjCEncodeExpression (SourceLocation AtLoc, TypeSourceInfo * EncodedTypeInfo, SourceLocation RParenLoc)
Definition at line 1135 of file SemaExprObjC.cpp.
Referenced by clang::TreeTransform< Derived >::RebuildObjCEncodeExpr().
BuildObjCExceptionDecl()
VarDecl * SemaObjC::BuildObjCExceptionDecl (TypeSourceInfo * TInfo, QualType ExceptionType, SourceLocation StartLoc, SourceLocation IdLoc, const IdentifierInfo * Id, bool Invalid = false)
Build a type-check a new Objective-C exception variable declaration.
Definition at line 5158 of file SemaDeclObjC.cpp.
BuildObjCNumericLiteral()
ExprResult SemaObjC::BuildObjCNumericLiteral (SourceLocation AtLoc, Expr * Number)
BuildObjCNumericLiteral - builds an ObjCBoxedExpr AST node for the numeric literal expression.
Type of the expression will be "NSNumber *" or "id" if NSNumber is unavailable.
Type of the expression will be "NSNumber *".
Definition at line 322 of file SemaExprObjC.cpp.
Referenced by CheckConversionToObjCLiteral().
BuildObjCObjectType()
QualType clang::SemaObjC::BuildObjCObjectType (QualType BaseType, SourceLocation Loc, SourceLocation TypeArgsLAngleLoc, ArrayRef< TypeSourceInfo * > TypeArgs, SourceLocation TypeArgsRAngleLoc, SourceLocation ProtocolLAngleLoc, ArrayRef< ObjCProtocolDecl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc, bool FailOnError, bool Rebuilding)
Build an Objective-C object pointer type.
Definition at line 708 of file SemaObjC.cpp.
Referenced by clang::TreeTransform< Derived >::RebuildObjCObjectType().
BuildObjCStringLiteral()
ExprResult SemaObjC::BuildObjCStringLiteral (SourceLocation AtLoc, StringLiteral * S)
Definition at line 85 of file SemaExprObjC.cpp.
Referenced by CheckConversionToObjCLiteral().
BuildObjCSubscriptExpression()
ExprResult SemaObjC::BuildObjCSubscriptExpression (SourceLocation RB, Expr * BaseExpr, Expr * IndexExpr, ObjCMethodDecl * getterMethod, ObjCMethodDecl * setterMethod)
Build an ObjC subscript pseudo-object expression, given that that's supported by the runtime.
Definition at line 770 of file SemaExprObjC.cpp.
BuildObjCTypeParamType()
QualType clang::SemaObjC::BuildObjCTypeParamType (const ObjCTypeParamDecl * Decl, SourceLocation ProtocolLAngleLoc, ArrayRef< ObjCProtocolDecl * > Protocols, ArrayRef< SourceLocation > ProtocolLocs, SourceLocation ProtocolRAngleLoc, bool FailOnError = false)
Build an Objective-C type parameter type.
Definition at line 481 of file SemaObjC.cpp.
Referenced by clang::TreeTransform< Derived >::RebuildObjCTypeParamType().
CheckARCMethodDecl()
bool SemaObjC::CheckARCMethodDecl (ObjCMethodDecl * method)
Check a method declaration for compatibility with the Objective-C ARC conventions.
Definition at line 231 of file SemaDeclObjC.cpp.
CheckCategoryVsClassMethodMatches()
void SemaObjC::CheckCategoryVsClassMethodMatches (ObjCCategoryImplDecl * CatIMP)
CheckCategoryVsClassMethodMatches - Checks that methods implemented in category matches with those implemented in its primary class and warns each time an exact match is found.
Definition at line 2946 of file SemaDeclObjC.cpp.
References clang::ObjCContainerDecl::class_methods(), clang::ObjCCategoryImplDecl::getCategoryDecl(), clang::ObjCCategoryDecl::getClassInterface(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ObjCContainerDecl::instance_methods(), clang::ObjCInterfaceDecl::lookupMethod(), and MatchAllMethodDeclarations().
CheckConflictingOverridingMethod()
void SemaObjC::CheckConflictingOverridingMethod (ObjCMethodDecl * Method, ObjCMethodDecl * Overridden, bool IsProtocolMethodDecl)
Definition at line 2614 of file SemaDeclObjC.cpp.
References CheckMethodOverrideParam(), CheckMethodOverrideReturn(), clang::SemaBase::Diag(), clang::Decl::getLocation(), clang::ObjCMethodDecl::isVariadic(), clang::ObjCMethodDecl::param_begin(), clang::ObjCMethodDecl::param_end(), and clang::SemaBase::SemaRef.
CheckConversionToObjCLiteral()
bool SemaObjC::CheckConversionToObjCLiteral (QualType DstType, Expr *& SrcExpr, bool Diagnose = true)
Definition at line 5081 of file SemaExprObjC.cpp.
References BuildObjCNumericLiteral(), BuildObjCStringLiteral(), clang::FixItHint::CreateInsertion(), clang::SemaBase::Diag(), clang::ActionResult< PtrTy, Compress >::get(), clang::Type::getAs(), clang::SemaBase::getASTContext(), clang::Stmt::getBeginLoc(), clang::ObjCObjectPointerType::getInterfaceDecl(), clang::SemaBase::getLangOpts(), ID, clang::Expr::IgnoreParenImpCasts(), clang::Expr::isNullPointerConstant(), clang::ObjCObjectPointerType::isObjCIdType(), and clang::Expr::NPC_NeverValueDependent.
CheckForwardProtocolDeclarationForCircularDependency()
bool SemaObjC::CheckForwardProtocolDeclarationForCircularDependency (IdentifierInfo * PName, SourceLocation & PLoc, SourceLocation PrevLoc, const ObjCList< ObjCProtocolDecl > & PList)
Definition at line 1192 of file SemaDeclObjC.cpp.
References clang::ObjCList< T >::begin(), clang::SemaBase::Diag(), clang::ObjCList< T >::end(), and LookupProtocol().
CheckImplementationIvars()
void SemaObjC::CheckImplementationIvars (ObjCImplementationDecl * ImpDecl, ObjCIvarDecl ** Fields, unsigned nIvars, SourceLocation Loc)
CheckImplementationIvars - This routine checks if the instance variables listed in the implelementation match those listed in the interface.
Check case of non-existing @interface decl. (legacy objective-c @implementation decl without an @interface decl). Add implementations's ivar to the synthesize class's ivar list.
Definition at line 2139 of file SemaDeclObjC.cpp.
checkInitMethod()
bool SemaObjC::checkInitMethod (ObjCMethodDecl * method, QualType receiverTypeIfCall)
Check whether the given method, which must be in the 'init' family, is a valid member of that family.
Parameters
receiverTypeIfCall - if null, check this as if declaring it; if non-null, check this as if making a call to it with the given receiver type
Returns
true to indicate that there was an error and appropriate actions were taken
Definition at line 45 of file SemaDeclObjC.cpp.
CheckLiteralKind()
SemaObjC::ObjCLiteralKind SemaObjC::CheckLiteralKind (Expr * FromE)
Definition at line 5208 of file SemaExprObjC.cpp.
References clang::Stmt::getStmtClass(), clang::Expr::IgnoreParenImpCasts(), LK_Array, LK_Block, LK_Dictionary, and LK_String.
CheckMessageArgumentTypes()
bool SemaObjC::CheckMessageArgumentTypes (const Expr * Receiver, QualType ReceiverType, MultiExprArg Args, Selector Sel, ArrayRef< SourceLocation > SelectorLocs, ObjCMethodDecl * Method, bool isClassMessage, bool isSuperMessage, SourceLocation lbrac, SourceLocation rbrac, SourceRange RecRange, QualType & ReturnType, ExprValueKind & VK)
CheckMessageArgumentTypes - Check types in an Obj-C message send.
Parameters
Method - May be null.
[out] ReturnType - The return type of the send.
Returns
true iff there were any incompatible types.
Definition at line 1725 of file SemaExprObjC.cpp.
CheckObjCARCUnavailableWeakConversion()
bool SemaObjC::CheckObjCARCUnavailableWeakConversion (QualType castType, QualType ExprType)
Definition at line 4596 of file SemaExprObjC.cpp.
CheckObjCBridgeRelatedCast()
void SemaObjC::CheckObjCBridgeRelatedCast (QualType castType, Expr * castExpr)
Definition at line 4193 of file SemaExprObjC.cpp.
References ACTC_coreFoundation, ACTC_retainable, clang::ast_matchers::castExpr, CheckObjCBridgeRelatedConversions(), and classifyTypeForARCConversion().
checkObjCBridgeRelatedComponents()
bool SemaObjC::checkObjCBridgeRelatedComponents (SourceLocation Loc, QualType DestType, QualType SrcType, ObjCInterfaceDecl *& RelatedClass, ObjCMethodDecl *& ClassMethod, ObjCMethodDecl *& InstanceMethod, TypedefNameDecl *& TDNDecl, bool CfToNs, bool Diagnose = true)
Definition at line 4231 of file SemaExprObjC.cpp.
CheckObjCBridgeRelatedConversions()
bool SemaObjC::CheckObjCBridgeRelatedConversions (SourceLocation Loc, QualType DestType, QualType SrcType, Expr *& SrcExpr, bool Diagnose = true)
Definition at line 4303 of file SemaExprObjC.cpp.
Referenced by CheckObjCBridgeRelatedCast().
CheckObjCCircularContainer()
void clang::SemaObjC::CheckObjCCircularContainer (ObjCMessageExpr * Message)
Check whether receiver is mutable ObjC container which attempts to add itself into the container.
Definition at line 1091 of file SemaObjC.cpp.
References clang::SemaBase::Diag(), clang::Decl::getLocation(), clang::GetNSMutableArrayArgumentIndex(), clang::GetNSMutableDictionaryArgumentIndex(), clang::GetNSSetArgumentIndex(), clang::Expr::IgnoreImpCasts(), and clang::ObjCMessageExpr::SuperInstance.
CheckObjCConversion()
SemaObjC::ARCConversionResult SemaObjC::CheckObjCConversion (SourceRange castRange, QualType castType, Expr *& op, CheckedConversionKind CCK, bool Diagnose = true, bool DiagnoseCFAudited = false, BinaryOperatorKind Opc = BO_PtrMemD)
Checks for invalid conversions and casts between retainable pointers and other pointer kinds for ARC and Weak.
Definition at line 4399 of file SemaExprObjC.cpp.
Referenced by clang::Sema::PerformImplicitConversion().
CheckObjCDeclScope()
bool SemaObjC::CheckObjCDeclScope (Decl * D)
Checks that the Objective-C declaration is declared in the global scope.
Emits an error and marks the declaration as invalid if it's not declared in the global scope.
Definition at line 5096 of file SemaDeclObjC.cpp.
References clang::Sema::CurContext, clang::SemaBase::Diag(), clang::Sema::getCurLexicalContext(), clang::Decl::getLocation(), clang::DeclContext::getRedeclContext(), clang::SemaBase::SemaRef, and clang::Decl::setInvalidDecl().
CheckObjCForCollectionOperand()
ExprResult clang::SemaObjC::CheckObjCForCollectionOperand (SourceLocation forLoc, Expr * collection)
Definition at line 117 of file SemaObjC.cpp.
CheckObjCMethodCall()
bool clang::SemaObjC::CheckObjCMethodCall (ObjCMethodDecl * Method, SourceLocation loc, ArrayRef< const Expr * > Args)
Definition at line 1242 of file SemaObjC.cpp.
References clang::Sema::checkCall(), clang::Sema::CheckTCBEnforcement(), clang::ObjCMethodDecl::getSourceRange(), clang::ObjCMethodDecl::isVariadic(), clang::SemaBase::SemaRef, clang::Sema::VariadicDoesNotApply, and clang::Sema::VariadicMethod.
CheckObjCMethodDirectOverrides()
void SemaObjC::CheckObjCMethodDirectOverrides (ObjCMethodDecl * method, ObjCMethodDecl * overridden)
Definition at line 4433 of file SemaDeclObjC.cpp.
References clang::ast_matchers::attr, clang::SemaBase::Diag(), clang::Decl::getAttr(), clang::Decl::getDeclContext(), clang::Decl::getLocation(), and clang::ObjCMethodDecl::isDirectMethod().
CheckObjCMethodOverride()
void SemaObjC::CheckObjCMethodOverride (ObjCMethodDecl * NewMethod, const ObjCMethodDecl * Overridden)
Check whether the given new method is a valid override of the given overridden method, and set any properties that should be inherited.
Definition at line 141 of file SemaDeclObjC.cpp.
CheckObjCMethodOverrides()
void SemaObjC::CheckObjCMethodOverrides (ObjCMethodDecl * ObjCMethod, ObjCInterfaceDecl * CurrentClass, ResultTypeCompatibilityKind RTC)
Definition at line 4447 of file SemaDeclObjC.cpp.
CheckObjCPropertyAttributes()
void SemaObjC::CheckObjCPropertyAttributes (Decl * PropertyPtrTy, SourceLocation Loc, unsigned & Attributes, bool propertyInPrimaryClass)
Ensure attributes are consistent with type.
Parameters
[in,out] Attributes The attributes to check; they will be modified to be consistent with PropertyTy.
Definition at line 2619 of file SemaObjCProperty.cpp.
References clang::SemaBase::Diag(), clang::LangOptionsBase::GCOnly, clang::SemaBase::getLangOpts(), clang::Type::getNullability(), getOwnershipRule(), clang::ObjCPropertyDecl::getType(), clang::Decl::hasAttr(), clang::Type::isBlockPointerType(), clang::Decl::isInvalidDecl(), clang::Type::isObjCARCImplicitlyUnretainedType(), clang::Type::isObjCClassType(), clang::Type::isObjCObjectPointerType(), clang::Type::isObjCQualifiedClassType(), clang::Type::isObjCRetainableType(), clang::ObjCPropertyAttribute::kind_assign, clang::ObjCPropertyAttribute::kind_atomic, clang::ObjCPropertyAttribute::kind_copy, clang::ObjCPropertyAttribute::kind_nonatomic, clang::ObjCPropertyAttribute::kind_readonly, clang::ObjCPropertyAttribute::kind_readwrite, clang::ObjCPropertyAttribute::kind_retain, clang::ObjCPropertyAttribute::kind_setter, clang::ObjCPropertyAttribute::kind_strong, clang::ObjCPropertyAttribute::kind_unsafe_unretained, clang::ObjCPropertyAttribute::kind_weak, Loc, clang::LangOptionsBase::NonGC, clang::NonNull, clang::Decl::setInvalidDecl(), and clang::ObjCPropertyDecl::setPropertyAttributes().
CheckObjCString()
bool clang::SemaObjC::CheckObjCString (Expr * Arg)
CheckObjCString - Checks that the argument to the builtin CFString constructor is correct Note: It might also make sense to do the UTF-16 conversion here (would simplify the backend).
Definition at line 1214 of file SemaObjC.cpp.
References clang::SemaBase::Diag(), clang::Stmt::getBeginLoc(), clang::Stmt::getSourceRange(), and clang::Expr::IgnoreParenCasts().
checkRetainCycles() [1/3]
void clang::SemaObjC::checkRetainCycles (Expr * receiver, Expr * argument)
Check a property assign to see if it's likely to cause a retain cycle.
Definition at line 1187 of file SemaObjC.cpp.
References clang::diagnoseRetainCycle(), clang::findCapturingExpr(), clang::findRetainCycleOwner(), and clang::SemaBase::SemaRef.
checkRetainCycles() [2/3]
void clang::SemaObjC::checkRetainCycles (ObjCMessageExpr * msg)
checkRetainCycles - Check whether an Objective-C message send might create an obvious retain cycle.
Check a message send to see if it's likely to cause a retain cycle.
Definition at line 1157 of file SemaObjC.cpp.
References clang::diagnoseRetainCycle(), clang::findCapturingExpr(), clang::findRetainCycleOwner(), clang::ObjCMessageExpr::getArg(), clang::Sema::getCurMethodDecl(), clang::ObjCMessageExpr::getInstanceReceiver(), clang::ObjCMessageExpr::getMethodDecl(), clang::ObjCMessageExpr::getNumArgs(), clang::ObjCMessageExpr::getReceiverKind(), clang::ObjCMessageExpr::getSelector(), clang::ObjCMethodDecl::getSelfDecl(), clang::ObjCMessageExpr::getSuperLoc(), clang::ObjCMessageExpr::Instance, clang::ObjCMessageExpr::isInstanceMessage(), clang::isSetterLikeSelector(), clang::ObjCMethodDecl::parameters(), clang::SemaBase::SemaRef, and clang::ObjCMessageExpr::SuperInstance.
checkRetainCycles() [3/3]
void clang::SemaObjC::checkRetainCycles (VarDecl * Var, Expr * Init)
Definition at line 1196 of file SemaObjC.cpp.
References Capturer, clang::considerVariable(), clang::diagnoseRetainCycle(), clang::findCapturingExpr(), clang::Decl::getLocation(), clang::VarDecl::getSourceRange(), and clang::SemaBase::SemaRef.
CheckSubscriptingKind()
SemaObjC::ObjCSubscriptKind clang::SemaObjC::CheckSubscriptingKind (Expr * FromE)
CheckSubscriptingKind - This routine decide what type of indexing represented by "FromE" is being done.
Definition at line 1375 of file SemaObjC.cpp.
References clang::FixItHint::CreateInsertion(), clang::SemaBase::Diag(), clang::Type::getAs(), clang::RecordType::getDecl(), clang::Expr::getExprLoc(), clang::SemaBase::getLangOpts(), clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isBlockPointerType(), clang::Type::isIncompleteType(), clang::Type::isIntegralOrEnumerationType(), clang::Type::isObjCIdType(), clang::Type::isObjCObjectPointerType(), clang::Type::isVoidPointerType(), OS_Array, OS_Dictionary, OS_Error, clang::Sema::RequireCompleteType(), clang::SemaBase::SemaRef, and clang::T.
CheckTollFreeBridgeCast()
void SemaObjC::CheckTollFreeBridgeCast (QualType castType, Expr * castExpr)
Definition at line 4145 of file SemaExprObjC.cpp.
References ACTC_coreFoundation, ACTC_retainable, clang::ast_matchers::castExpr, classifyTypeForARCConversion(), clang::SemaBase::getLangOpts(), and clang::SemaBase::SemaRef.
Referenced by CheckTollFreeBridgeStaticCast().
CheckTollFreeBridgeStaticCast()
bool SemaObjC::CheckTollFreeBridgeStaticCast (QualType castType, Expr * castExpr, CastKind & Kind)
Definition at line 4214 of file SemaExprObjC.cpp.
References ACTC_coreFoundation, ACTC_retainable, clang::ast_matchers::castExpr, CheckTollFreeBridgeCast(), classifyTypeForARCConversion(), and clang::SemaBase::getLangOpts().
CollectIvarsToConstructOrDestruct()
void SemaObjC::CollectIvarsToConstructOrDestruct (ObjCInterfaceDecl * OI, SmallVectorImpl< ObjCIvarDecl * > & Ivars)
CollectIvarsToConstructOrDestruct - Collect those ivars which require initialization.
Definition at line 5263 of file SemaDeclObjC.cpp.
CollectMultipleMethodsInGlobalPool()
bool SemaObjC::CollectMultipleMethodsInGlobalPool (Selector Sel, SmallVectorImpl< ObjCMethodDecl * > & Methods, bool InstanceFirst, bool CheckTheOther, const ObjCObjectType * TypeBound = nullptr)
We first select the type of the method: Instance or Factory, then collect all methods with that type.
Returns instance or factory methods in global method pool for given selector. It checks the desired kind first, if none is found, and parameter checkTheOther is set, it then checks the other kind. If no such method or only one method is found, function returns false; otherwise, it returns true.
Definition at line 3517 of file SemaDeclObjC.cpp.
References clang::SemaObjC::GlobalMethodPool::end(), clang::Sema::ExternalSource, FilterMethodsByTypeBound(), clang::SemaObjC::GlobalMethodPool::find(), clang::ObjCMethodList::getNext(), MethodPool, ReadMethodPool(), and clang::SemaBase::SemaRef.
CreatePropertyDecl()
ObjCPropertyDecl * SemaObjC::CreatePropertyDecl (Scope * S, ObjCContainerDecl * CDecl, SourceLocation AtLoc, SourceLocation LParenLoc, FieldDeclarator & FD, Selector GetterSel, SourceLocation GetterNameLoc, Selector SetterSel, SourceLocation SetterNameLoc, const bool isReadWrite, const unsigned Attributes, const unsigned AttributesAsWritten, QualType T, TypeSourceInfo * TSI, tok::ObjCKeywordKind MethodImplKind, DeclContext * lexicalDC = nullptr)
Called by ActOnProperty and HandlePropertyInClassExtension to handle creating the ObjcPropertyDecl for a category or @interface.
Definition at line 550 of file SemaObjCProperty.cpp.
DefaultSynthesizeProperties() [1/2]
void SemaObjC::DefaultSynthesizeProperties (Scope * S, Decl * D, SourceLocation AtEnd)
Definition at line 1961 of file SemaObjCProperty.cpp.
DefaultSynthesizeProperties() [2/2]
void SemaObjC::DefaultSynthesizeProperties (Scope * S, ObjCImplDecl * IMPDecl, ObjCInterfaceDecl * IDecl, SourceLocation AtEnd)
DefaultSynthesizeProperties - This routine default synthesizes all properties which must be synthesized in the class's @implementation.
Default synthesizes all properties which must be synthesized in class's @implementation.
Definition at line 1866 of file SemaObjCProperty.cpp.
diagnoseARCUnbridgedCast()
void SemaObjC::diagnoseARCUnbridgedCast (Expr * e)
Given that we saw an expression with the ARCUnbridgedCastTy placeholder type, complain bitterly.
Definition at line 4522 of file SemaExprObjC.cpp.
References ACTC_retainable, clang::cast(), clang::ast_matchers::castExpr, classifyTypeForARCConversion(), clang::CStyleCast, diagnoseObjCARCConversion(), clang::QualType::getNonReferenceType(), clang::CastExpr::getSubExpr(), clang::Expr::hasPlaceholderType(), clang::Expr::IgnoreParens(), clang::OtherCast, and clang::SemaBase::SemaRef.
DiagnoseClassExtensionDupMethods()
void SemaObjC::DiagnoseClassExtensionDupMethods (ObjCCategoryDecl * CAT, ObjCInterfaceDecl * ID)
DiagnoseClassExtensionDupMethods - Check for duplicate declaration of a class method in its extension.
Definition at line 1764 of file SemaDeclObjC.cpp.
References clang::SemaBase::Diag(), clang::Decl::getLocation(), ID, clang::ObjCMethodDecl::isInstanceMethod(), MatchTwoMethodDeclarations(), and clang::ObjCContainerDecl::methods().
DiagnoseDuplicateIvars()
void SemaObjC::DiagnoseDuplicateIvars (ObjCInterfaceDecl * ID, ObjCInterfaceDecl * SID)
DiagnoseDuplicateIvars - Check for duplicate ivars in the entire class at the start of @implementation.
This becomes necessary because class extension can add ivars to a class in random order which will not be known until class's @implementation is seen.
Definition at line 3773 of file SemaDeclObjC.cpp.
References clang::SemaBase::Diag(), clang::Decl::getLocation(), ID, and clang::ObjCInterfaceDecl::lookupInstanceVariable().
DiagnoseMissingDesignatedInitOverrides()
void SemaObjC::DiagnoseMissingDesignatedInitOverrides (const ObjCImplementationDecl * ImplD, const ObjCInterfaceDecl * IFD)
Definition at line 2298 of file SemaObjCProperty.cpp.
References clang::SemaBase::Diag(), clang::ObjCInterfaceDecl::getDesignatedInitializers(), clang::ObjCContainerDecl::getInstanceMethod(), clang::Decl::getLocation(), clang::ObjCMethodDecl::getSelector(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ObjCInterfaceDecl::hasDesignatedInitializers(), clang::ObjCContainerDecl::instance_methods(), clang::Decl::isUnavailable(), clang::OMF_init, and clang::ObjCInterfaceDecl::visible_extensions().
DiagnoseMultipleMethodInGlobalPool()
void SemaObjC::DiagnoseMultipleMethodInGlobalPool (SmallVectorImpl< ObjCMethodDecl * > & Methods, Selector Sel, SourceRange R, bool receiverIdOrClass)
Definition at line 3600 of file SemaDeclObjC.cpp.
References clang::SemaBase::Diag(), clang::SourceRange::getBegin(), clang::SemaBase::getDiagnostics(), clang::SemaBase::getLangOpts(), isAcceptableMethodMismatch(), clang::DiagnosticsEngine::isIgnored(), MatchTwoMethodDeclarations(), MMS_loose, and MMS_strict.
Referenced by AreMultipleMethodsInGlobalPool().
diagnoseNullResettableSynthesizedSetters()
void SemaObjC::diagnoseNullResettableSynthesizedSetters (const ObjCImplDecl * impDecl)
Diagnose any null-resettable synthesized setters.
Definition at line 2118 of file SemaObjCProperty.cpp.
References clang::SemaBase::Diag(), clang::Decl::getBeginLoc(), clang::SourceLocation::isInvalid(), clang::ObjCPropertyAttribute::kind_null_resettable, clang::ObjCImplDecl::property_impls(), and clang::ObjCPropertyImplDecl::Synthesize.
DiagnoseOwningPropertyGetterSynthesis()
void SemaObjC::DiagnoseOwningPropertyGetterSynthesis (const ObjCImplementationDecl * D)
Definition at line 2238 of file SemaObjCProperty.cpp.
References clang::FixItHint::CreateInsertion(), clang::SemaBase::Diag(), clang::LangOptionsBase::GCOnly, clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ObjCPropertyDecl::getGetterMethodDecl(), clang::Preprocessor::getIdentifierInfo(), clang::SemaBase::getLangOpts(), clang::Preprocessor::getLastMacroWithSpelling(), clang::Decl::getLocation(), clang::ObjCMethodDecl::getMethodFamily(), clang::Sema::getPreprocessor(), clang::Decl::hasAttr(), clang::ObjCPropertyDecl::isClassProperty(), clang::ObjCMethodDecl::isSynthesizedAccessorStub(), clang::SourceLocation::isValid(), clang::OMF_alloc, clang::OMF_copy, clang::OMF_mutableCopy, clang::OMF_new, clang::ObjCImplDecl::property_impls(), clang::Decl::redecls(), and clang::SemaBase::SemaRef.
DiagnosePropertyAccessorMismatch()
bool SemaObjC::DiagnosePropertyAccessorMismatch (ObjCPropertyDecl * PD, ObjCMethodDecl * Getter, SourceLocation Loc)
Definition at line 1687 of file SemaObjCProperty.cpp.
DiagnosePropertyMismatch()
void SemaObjC::DiagnosePropertyMismatch (ObjCPropertyDecl * Property, ObjCPropertyDecl * SuperProperty, const IdentifierInfo * Name, bool OverridingProtocolProperty)
DiagnosePropertyMismatch - Compares two properties for their attributes and types and warns on a variety of inconsistencies.
Definition at line 1612 of file SemaObjCProperty.cpp.
DiagnoseTypeArgsAndProtocols()
void SemaObjC::DiagnoseTypeArgsAndProtocols (IdentifierInfo * ProtocolId, SourceLocation ProtocolLoc, IdentifierInfo * TypeArgId, SourceLocation TypeArgLoc, bool SelectProtocolFirst = false)
Definition at line 1417 of file SemaDeclObjC.cpp.
References clang::SemaBase::Diag().
DiagnoseUnimplementedProperties()
void SemaObjC::DiagnoseUnimplementedProperties (Scope * S, ObjCImplDecl * IMPDecl, ObjCContainerDecl * CDecl, bool SynthesizeProperties)
DiagnoseUnimplementedProperties - This routine warns on those properties which must be implemented by this implementation.
Definition at line 2011 of file SemaObjCProperty.cpp.
DiagnoseUnusedBackingIvarInAccessor()
void SemaObjC::DiagnoseUnusedBackingIvarInAccessor (Scope * S, const ObjCImplementationDecl * ImplD)
DiagnoseUnusedBackingIvarInAccessor - Issue an 'unused' warning if ivar which backs the property is not used in the property's accessor.
Definition at line 5360 of file SemaDeclObjC.cpp.
DiagnoseUseOfUnimplementedSelectors()
void SemaObjC::DiagnoseUseOfUnimplementedSelectors ()
Definition at line 5274 of file SemaDeclObjC.cpp.
Referenced by clang::Sema::ActOnEndOfTranslationUnit().
EmitRelatedResultTypeNote()
void SemaObjC::EmitRelatedResultTypeNote (const Expr * E)
If the given expression involves a message send to a method with a related result type, emit a note describing what happened.
Definition at line 1698 of file SemaExprObjC.cpp.
Referenced by clang::Sema::PerformImplicitConversion().
EmitRelatedResultTypeNoteForReturn()
void SemaObjC::EmitRelatedResultTypeNoteForReturn (QualType destType)
Given that we had incompatible pointer types in a return statement, check whether we're in a method with a related result type, and if so, emit a note describing what happened.
Definition at line 1668 of file SemaExprObjC.cpp.
FindCompositeObjCPointerType()
QualType SemaObjC::FindCompositeObjCPointerType (ExprResult & LHS, ExprResult & RHS, SourceLocation QuestionLoc)
FindCompositeObjCPointerType - Helper method to find composite type of two objective-c pointer types of the two input expressions.
Definition at line 4931 of file SemaExprObjC.cpp.
Referenced by clang::Sema::CXXCheckConditionalOperands().
FindProtocolDeclaration()
void SemaObjC::FindProtocolDeclaration (bool WarnOnDeclarations, bool ForObjCContainer, ArrayRef< IdentifierLocPair > ProtocolId, SmallVectorImpl< Decl * > & Protocols)
FindProtocolDeclaration - This routine looks up protocols and issues an error if they are not declared.
It returns list of protocol declarations in its 'Protocols' argument.
Definition at line 1312 of file SemaDeclObjC.cpp.
References clang::Sema::CorrectTypo(), clang::Sema::CTK_ErrorRecovery, clang::SemaBase::Diag(), clang::Sema::diagnoseTypo(), clang::Sema::DiagnoseUseOfDecl(), clang::TypoCorrection::getCorrectionDeclAs(), clang::ObjCProtocolDecl::getDefinition(), clang::Decl::getLocation(), clang::ObjCProtocolDecl::isThisDeclarationADefinition(), clang::Sema::LookupObjCProtocolName, LookupProtocol(), NestedProtocolHasNoDefinition(), clang::Sema::PDiag(), clang::SemaBase::SemaRef, and clang::Sema::TUScope.
FinishObjCForCollectionStmt()
StmtResult clang::SemaObjC::FinishObjCForCollectionStmt (Stmt * ForCollection, Stmt * Body)
FinishObjCForCollectionStmt - Attach the body to a objective-C foreach statement.
Definition at line 194 of file SemaObjC.cpp.
getCurObjCLexicalContext()
const DeclContext * clang::SemaObjC::getCurObjCLexicalContext () const
Definition at line 1256 of file SemaObjC.cpp.
References clang::Sema::getCurLexicalContext(), and clang::SemaBase::SemaRef.
GetIvarBackingPropertyAccessor()
ObjCIvarDecl * SemaObjC::GetIvarBackingPropertyAccessor (const ObjCMethodDecl * Method, const ObjCPropertyDecl *& PDecl) const
GetIvarBackingPropertyAccessor - If method is a property setter/getter and it property has a backing ivar, returns this ivar; otherwise, returns NULL.
It also returns ivar's property on success.
Definition at line 5299 of file SemaDeclObjC.cpp.
References clang::ObjCMethodDecl::findPropertyDecl(), clang::ObjCMethodDecl::getClassInterface(), clang::ObjCPropertyDecl::getPropertyIvarDecl(), clang::ObjCMethodDecl::getSelector(), clang::ObjCMethodDecl::isClassMethod(), clang::ObjCMethodDecl::isPropertyAccessor(), and clang::ObjCInterfaceDecl::lookupMethod().
getMessageSendResultType()
QualType SemaObjC::getMessageSendResultType (const Expr * Receiver, QualType ReceiverType, ObjCMethodDecl * Method, bool isClassMessage, bool isSuperMessage)
Determine the result of a message send expression based on the type of the receiver, the method expected to receive the message, and the form of the message send.
Definition at line 1531 of file SemaExprObjC.cpp.
getNSErrorIdent()
IdentifierInfo * clang::SemaObjC::getNSErrorIdent ()
Retrieve the identifier "NSError".
Definition at line 1265 of file SemaObjC.cpp.
References clang::Preprocessor::getIdentifierInfo(), clang::Sema::PP, and clang::SemaBase::SemaRef.
Referenced by isCFError().
getObjCContainerKind()
SemaObjC::ObjCContainerKind SemaObjC::getObjCContainerKind () const
Definition at line 3826 of file SemaDeclObjC.cpp.
References clang::Sema::CurContext, clang::DeclContext::getDeclKind(), OCK_Category, OCK_CategoryImplementation, OCK_ClassExtension, OCK_Implementation, OCK_Interface, OCK_None, OCK_Protocol, and clang::SemaBase::SemaRef.
getObjCDeclContext()
ObjCContainerDecl * SemaObjC::getObjCDeclContext () const
Definition at line 5499 of file SemaDeclObjC.cpp.
References clang::Sema::CurContext, and clang::SemaBase::SemaRef.
Referenced by clang::Parser::getObjCDeclContext().
getObjCInterfaceDecl()
ObjCInterfaceDecl * SemaObjC::getObjCInterfaceDecl (const IdentifierInfo *& Id, SourceLocation IdLoc, bool TypoCorrection = false)
Look for an Objective-C class in the translation unit.
Parameters
Id The name of the Objective-C class we're looking for. If typo-correction fixes this name, the Id will be updated to the fixed name.
IdLoc The location of the name in the translation unit.
DoTypoCorrection If true, this routine will attempt typo correction if there is no class with the given name.
Returns
The declaration of the named Objective-C class, or NULL if the class could not be found.
Definition at line 5427 of file SemaDeclObjC.cpp.
References clang::Sema::CorrectTypo(), clang::Sema::CTK_ErrorRecovery, clang::Sema::diagnoseTypo(), clang::ObjCInterfaceDecl::getDefinition(), clang::NamedDecl::getIdentifier(), Id, clang::Sema::LookupOrdinaryName, clang::Sema::LookupSingleName(), clang::Sema::PDiag(), clang::SemaBase::SemaRef, and clang::Sema::TUScope.
getObjCMessageKind()
SemaObjC::ObjCMessageKind SemaObjC::getObjCMessageKind (Scope * S, IdentifierInfo * Name, SourceLocation NameLoc, bool IsSuper, bool HasTrailingDot, ParsedType & ReceiverType)
Definition at line 2296 of file SemaExprObjC.cpp.
HandleExprPropertyRefExpr()
ExprResult SemaObjC::HandleExprPropertyRefExpr (const ObjCObjectPointerType * OPT, Expr * BaseExpr, SourceLocation OpLoc, DeclarationName MemberName, SourceLocation MemberLoc, SourceLocation SuperLoc, QualType SuperType, bool Super)
HandleExprPropertyRefExpr - Handle foo.bar where foo is a pointer to an objective C interface.
This is a property reference expression.
Definition at line 1989 of file SemaExprObjC.cpp.
HandlePropertyInClassExtension()
ObjCPropertyDecl * SemaObjC::HandlePropertyInClassExtension (Scope * S, SourceLocation AtLoc, SourceLocation LParenLoc, FieldDeclarator & FD, Selector GetterSel, SourceLocation GetterNameLoc, Selector SetterSel, SourceLocation SetterNameLoc, const bool isReadWrite, unsigned & Attributes, const unsigned AttributesAsWritten, QualType T, TypeSourceInfo * TSI, tok::ObjCKeywordKind MethodImplKind)
Called by ActOnProperty to handle @property declarations in class extensions.
Definition at line 404 of file SemaObjCProperty.cpp.
ImplMethodsVsClassMethods()
void SemaObjC::ImplMethodsVsClassMethods (Scope * S, ObjCImplDecl * IMPDecl, ObjCContainerDecl * IDecl, bool IncompleteImpl = false)
ImplMethodsVsClassMethods - This is main routine to warn if any method remains unimplemented in the class or category @implementation.
Definition at line 2985 of file SemaDeclObjC.cpp.
inferObjCARCLifetime()
bool SemaObjC::inferObjCARCLifetime (ValueDecl * decl)
Definition at line 5455 of file SemaDeclObjC.cpp.
Referenced by FinishForRangeVarDecl().
isCFError()
bool clang::SemaObjC::isCFError (RecordDecl * D)
Definition at line 1461 of file SemaObjC.cpp.
References CFError, clang::Decl::getAttr(), getNSErrorIdent(), clang::TagDecl::getTagKind(), and clang::Struct.
isKnownName()
bool SemaObjC::isKnownName (StringRef name)
Definition at line 3749 of file SemaExprObjC.cpp.
isObjCMethodDecl()
bool clang::SemaObjC::isObjCMethodDecl (Decl * D) inline
Definition at line 386 of file SemaObjC.h.
isObjCWritebackConversion()
bool clang::SemaObjC::isObjCWritebackConversion (QualType FromType, QualType ToType, QualType & ConvertedType)
Determine whether this is an Objective-C writeback conversion, used for parameter passing when performing automatic reference counting.
Parameters
FromType The type we're converting form.
ToType The type we're converting to.
ConvertedType The type that will be produced after applying this conversion.
Construct the type we're converting to, which is a pointer to __autoreleasing pointee.
Definition at line 1314 of file SemaObjC.cpp.
isSelfExpr() [1/2]
bool SemaObjC::isSelfExpr (Expr * RExpr)
Private Helper predicate to check for 'self'.
Definition at line 1934 of file SemaExprObjC.cpp.
References clang::Sema::CurContext, clang::DeclContext::getNonClosureAncestor(), and clang::SemaBase::SemaRef.
isSelfExpr() [2/2]
bool SemaObjC::isSelfExpr (Expr * RExpr, const ObjCMethodDecl * Method)
Definition at line 1941 of file SemaExprObjC.cpp.
References clang::ObjCMethodDecl::getSelfDecl(), and clang::Expr::IgnoreParenLValueCasts().
IvarBacksCurrentMethodAccessor()
bool SemaObjC::IvarBacksCurrentMethodAccessor (ObjCInterfaceDecl * IFace, ObjCMethodDecl * Method, ObjCIvarDecl * IV)
IvarBacksCurrentMethodAccessor - This routine returns 'true' if 'IV' is an ivar synthesized for 'Method' and 'Method' is a property accessor declared in class 'IFace'.
Definition at line 1814 of file SemaObjCProperty.cpp.
References clang::ObjCMethodDecl::getSelector(), clang::ObjCIvarDecl::getSynthesize(), clang::ObjCContainerDecl::instance_properties(), clang::ObjCMethodDecl::isInstanceMethod(), clang::ObjCMethodDecl::isPropertyAccessor(), clang::ObjCInterfaceDecl::known_extensions(), clang::ObjCInterfaceDecl::lookupMethod(), and clang::Property.
LookupFactoryMethodInGlobalPool()
ObjCMethodDecl* clang::SemaObjC::LookupFactoryMethodInGlobalPool (Selector Sel, SourceRange R, bool receiverIdOrClass = false) inline
LookupFactoryMethodInGlobalPool - Returns the method and warns if there are multiple signatures.
Definition at line 850 of file SemaObjC.h.
LookupImplementedMethodInGlobalPool()
ObjCMethodDecl * SemaObjC::LookupImplementedMethodInGlobalPool (Selector Sel)
LookupImplementedMethodInGlobalPool - Returns the method which has an implementation.
Definition at line 3655 of file SemaDeclObjC.cpp.
References clang::SemaObjC::GlobalMethodPool::end(), clang::SemaObjC::GlobalMethodPool::find(), clang::ObjCMethodDecl::isDefined(), clang::ObjCMethodDecl::isPropertyAccessor(), and MethodPool.
LookupInObjCMethod()
ExprResult SemaObjC::LookupInObjCMethod (LookupResult & LookUp, Scope * S, IdentifierInfo * II, bool AllowBuiltinCreation = false)
The parser has read a name in, and Sema has detected that we're currently inside an ObjC method.
Perform some additional checks and determine if we should form a reference to an ivar. If so, build an expression referencing that ivar.
Definition at line 4853 of file SemaExprObjC.cpp.
Referenced by attemptRecovery().
LookupInstanceMethodInGlobalPool()
ObjCMethodDecl* clang::SemaObjC::LookupInstanceMethodInGlobalPool (Selector Sel, SourceRange R, bool receiverIdOrClass = false) inline
LookupInstanceMethodInGlobalPool - Returns the method and warns if there are multiple signatures.
Definition at line 841 of file SemaObjC.h.
LookupIvarInObjCMethod()
DeclResult SemaObjC::LookupIvarInObjCMethod (LookupResult & Lookup, Scope * S, IdentifierInfo * II)
The parser has read a name in, and Sema has detected that we're currently inside an ObjC method.
Perform some additional checks and determine if we should form a reference to an ivar.
Ideally, most of this would be done by lookup, but there's actually quite a lot of extra work involved.
Definition at line 4780 of file SemaExprObjC.cpp.
LookupMethodInObjectType()
ObjCMethodDecl * SemaObjC::LookupMethodInObjectType (Selector Sel, QualType Ty, bool IsInstance)
LookupMethodInType - Look up a method in an ObjCObjectType.
Definition at line 1952 of file SemaExprObjC.cpp.
References clang::ObjCObjectType::getInterface(), clang::ObjCProtocolQualifiers< T >::quals(), and clang::ast_matchers::type.
LookupMethodInQualifiedType()
ObjCMethodDecl * SemaObjC::LookupMethodInQualifiedType (Selector Sel, const ObjCObjectPointerType * OPT, bool IsInstance)
LookupMethodInQualifiedType - Lookups up a method in protocol qualifier list of a qualified objective pointer type.
Definition at line 1976 of file SemaExprObjC.cpp.
References clang::ObjCObjectPointerType::quals().
LookupProtocol()
ObjCProtocolDecl * clang::SemaObjC::LookupProtocol (IdentifierInfo * II, SourceLocation IdLoc, RedeclarationKind Redecl = RedeclarationKind::NotForRedeclaration)
Find the protocol with the given name, if any.
Definition at line 1297 of file SemaObjC.cpp.
References clang::Sema::LookupObjCProtocolName, clang::Sema::LookupSingleName(), clang::SemaBase::SemaRef, and clang::Sema::TUScope.
Referenced by CheckForwardProtocolDeclarationForCircularDependency(), and FindProtocolDeclaration().
MatchAllMethodDeclarations()
void SemaObjC::MatchAllMethodDeclarations (const SelectorSet & InsMap, const SelectorSet & ClsMap, SelectorSet & InsMapSeen, SelectorSet & ClsMapSeen, ObjCImplDecl * IMPDecl, ObjCContainerDecl * IDecl, bool & IncompleteImpl, bool ImmediateClass, bool WarnCategoryMethodImpl = false)
MatchAllMethodDeclarations - Check methods declaraed in interface or or protocol against those declared in their implementations.
MatchAllMethodDeclarations - Check methods declared in interface or protocol against those declared in their implementations.
Definition at line 2837 of file SemaDeclObjC.cpp.
References clang::ObjCContainerDecl::class_methods(), clang::ObjCContainerDecl::getClassMethod(), clang::ObjCContainerDecl::getInstanceMethod(), clang::ObjCContainerDecl::instance_methods(), clang::ObjCMethodDecl::isSynthesizedAccessorStub(), clang::SemaBase::SemaRef, WarnConflictingTypedMethods(), WarnExactTypedMethods(), and WarnUndefinedMethod().
Referenced by CheckCategoryVsClassMethodMatches().
MatchTwoMethodDeclarations()
bool SemaObjC::MatchTwoMethodDeclarations (const ObjCMethodDecl * left, const ObjCMethodDecl * right, MethodMatchStrategy strategy = MMS_strict)
MatchTwoMethodDeclarations - Checks if two methods' type match and returns true, or false, accordingly.
MatchTwoMethodDeclarations - Checks that two methods have matching type and returns true, or false, accordingly.
TODO: Handle protocol list; such as id<p1,p2> in type comparisons
Definition at line 3262 of file SemaDeclObjC.cpp.
Referenced by DiagnoseClassExtensionDupMethods(), and DiagnoseMultipleMethodInGlobalPool().
ParseObjCEncodeExpression()
ExprResult SemaObjC::ParseObjCEncodeExpression (SourceLocation AtLoc, SourceLocation EncodeLoc, SourceLocation LParenLoc, ParsedType Ty, SourceLocation RParenLoc)
Definition at line 1166 of file SemaExprObjC.cpp.
ParseObjCProtocolExpression()
ExprResult SemaObjC::ParseObjCProtocolExpression (IdentifierInfo * ProtocolName, SourceLocation AtLoc, SourceLocation ProtoLoc, SourceLocation LParenLoc, SourceLocation ProtoIdLoc, SourceLocation RParenLoc)
ParseObjCProtocolExpression - Build protocol expression for @protocol.
Definition at line 1397 of file SemaExprObjC.cpp.
ParseObjCSelectorExpression()
ExprResult SemaObjC::ParseObjCSelectorExpression (Selector Sel, SourceLocation AtLoc, SourceLocation SelLoc, SourceLocation LParenLoc, SourceLocation RParenLoc, bool WarnMultipleSelectors)
ParseObjCSelectorExpression - Build selector expression for @selector.
Definition at line 1301 of file SemaExprObjC.cpp.
ParseObjCStringLiteral()
ExprResult SemaObjC::ParseObjCStringLiteral (SourceLocation * AtLocs, ArrayRef< Expr * > Strings)
Definition at line 38 of file SemaExprObjC.cpp.
popObjCTypeParamList()
void SemaObjC::popObjCTypeParamList (Scope * S, ObjCTypeParamList * typeParamList)
Definition at line 805 of file SemaDeclObjC.cpp.
Referenced by clang::Parser::ObjCTypeParamListScope::leave().
PrepareCastToObjCObjectPointer()
CastKind SemaObjC::PrepareCastToObjCObjectPointer (ExprResult & E)
Prepare a conversion of the given expression to an ObjC object pointer type.
Definition at line 5195 of file SemaExprObjC.cpp.
References clang::ActionResult< PtrTy, Compress >::get(), clang::Expr::getType(), clang::Sema::maybeExtendBlockObject(), clang::SemaBase::SemaRef, and clang::ast_matchers::type.
Referenced by clang::Sema::PerformImplicitConversion().
ProcessPropertyDecl()
void SemaObjC::ProcessPropertyDecl (ObjCPropertyDecl * property)
Process the specified property declaration and create decls for the setters and getters as needed.
ProcessPropertyDecl - Make sure that any user-defined setter/getter methods have the property type and issue diagnostics if they don't.
Parameters
property The property declaration being processed
Also synthesize a getter/setter method if none exist (and update the appropriate lookup tables.
Definition at line 2356 of file SemaObjCProperty.cpp.
ReadMethodPool()
void SemaObjC::ReadMethodPool (Selector Sel)
Read the contents of the method pool for a given selector from external storage.
Definition at line 3427 of file SemaDeclObjC.cpp.
References clang::Sema::ExternalSource, and clang::SemaBase::SemaRef.
Referenced by CollectMultipleMethodsInGlobalPool().
SelectorsForTypoCorrection()
const ObjCMethodDecl * SemaObjC::SelectorsForTypoCorrection (Selector Sel, QualType ObjectType = QualType())
Definition at line 3712 of file SemaDeclObjC.cpp.
References b, clang::SemaObjC::GlobalMethodPool::begin(), clang::SemaObjC::GlobalMethodPool::end(), clang::Type::getAsObjCInterfacePointerType(), clang::Selector::getAsString(), clang::Selector::getNumArgs(), HelperIsMethodInObjCType(), HelperSelectorsForTypoCorrection(), clang::QualType::isNull(), clang::Type::isObjCClassType(), clang::Type::isObjCIdType(), clang::Type::isObjCObjectPointerType(), clang::Type::isObjCQualifiedClassType(), clang::Type::isObjCQualifiedIdType(), MethodPool, and clang::SemaBase::SemaRef.
SetIvarInitializers()
void SemaObjC::SetIvarInitializers (ObjCImplementationDecl * ObjCImplementation)
SetIvarInitializers - This routine builds initialization ASTs for the Objective-C implementation whose ivars need be initialized.
Definition at line 5503 of file SemaDeclObjC.cpp.
References clang::CPlusPlus, clang::ObjCImplDecl::getClassInterface(), and clang::SemaBase::getLangOpts().
stripARCUnbridgedCast()
Expr * SemaObjC::stripARCUnbridgedCast (Expr * e)
stripARCUnbridgedCast - Given an expression of ARCUnbridgedCast type, remove the placeholder cast.
Definition at line 4555 of file SemaExprObjC.cpp.
References clang::Expr::hasPlaceholderType().
Referenced by clang::Sema::SelectBestMethod().
tryCaptureObjCSelf()
ObjCMethodDecl * SemaObjC::tryCaptureObjCSelf (SourceLocation Loc)
Try to capture an implicit reference to 'self'.
Definition at line 1427 of file SemaExprObjC.cpp.
References clang::Sema::getFunctionLevelDeclContext(), clang::ObjCMethodDecl::getSelfDecl(), Loc, clang::SemaBase::SemaRef, and clang::Sema::tryCaptureVariable().
updateOutOfDateSelector()
void SemaObjC::updateOutOfDateSelector (Selector Sel)
Definition at line 3432 of file SemaDeclObjC.cpp.
References clang::Sema::ExternalSource, and clang::SemaBase::SemaRef.
WarnConflictingTypedMethods()
void SemaObjC::WarnConflictingTypedMethods (ObjCMethodDecl * Method, ObjCMethodDecl * MethodDecl, bool IsProtocolMethodDecl)
Definition at line 2589 of file SemaDeclObjC.cpp.
References checkMethodFamilyMismatch(), CheckMethodOverrideParam(), CheckMethodOverrideReturn(), clang::SemaBase::Diag(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::ObjCMethodDecl::isVariadic(), clang::ObjCMethodDecl::param_begin(), clang::ObjCMethodDecl::param_end(), and clang::SemaBase::SemaRef.
Referenced by MatchAllMethodDeclarations().
WarnExactTypedMethods()
void SemaObjC::WarnExactTypedMethods (ObjCMethodDecl * Method, ObjCMethodDecl * MethodDecl, bool IsProtocolMethodDecl)
WarnExactTypedMethods - This routine issues a warning if method implementation declaration matches exactly that of its declaration.
Definition at line 2638 of file SemaDeclObjC.cpp.
Referenced by MatchAllMethodDeclarations().
Member Data Documentation
ArrayWithObjectsMethod
ObjCMethodDecl* clang::SemaObjC::ArrayWithObjectsMethod
The declaration of the arrayWithObjects:count: method.
Definition at line 611 of file SemaObjC.h.
CFError
RecordDecl* clang::SemaObjC::CFError = nullptr
The struct behind the CFErrorRef pointer.
Definition at line 156 of file SemaObjC.h.
Referenced by isCFError().
DictionaryWithObjectsMethod
ObjCMethodDecl* clang::SemaObjC::DictionaryWithObjectsMethod
The declaration of the dictionaryWithObjects:forKeys:count: method.
Definition at line 617 of file SemaObjC.h.
MethodPool
GlobalMethodPool clang::SemaObjC::MethodPool
Method Pool - allows efficient lookup when typechecking messages to "id".
We need to maintain a list, since selectors can have differing signatures across classes. In Cocoa, this happens to be extremely uncommon (only 1% of selectors are "overloaded"). At the head of the list it is recorded whether there were 0, 1, or >= 2 methods inside categories with a particular selector.
Definition at line 211 of file SemaObjC.h.
Referenced by AreMultipleMethodsInGlobalPool(), CollectMultipleMethodsInGlobalPool(), LookupImplementedMethodInGlobalPool(), and SelectorsForTypoCorrection().
NSAPIObj
std::unique_ptr<NSAPI> clang::SemaObjC::NSAPIObj
Caches identifiers/selectors for NSFoundation APIs.
Definition at line 578 of file SemaObjC.h.
NSArrayDecl
ObjCInterfaceDecl* clang::SemaObjC::NSArrayDecl
The declaration of the Objective-C NSArray class.
Definition at line 608 of file SemaObjC.h.
NSDictionaryDecl
ObjCInterfaceDecl* clang::SemaObjC::NSDictionaryDecl
The declaration of the Objective-C NSDictionary class.
Definition at line 614 of file SemaObjC.h.
NSNumberDecl
ObjCInterfaceDecl* clang::SemaObjC::NSNumberDecl
The declaration of the Objective-C NSNumber class.
Definition at line 581 of file SemaObjC.h.
NSNumberLiteralMethods
ObjCMethodDecl* clang::SemaObjC::NSNumberLiteralMethods[NSAPI::NumNSNumberLiteralMethods]
The Objective-C NSNumber methods used to create NSNumber literals.
Definition at line 593 of file SemaObjC.h.
NSNumberPointer
QualType clang::SemaObjC::NSNumberPointer
Pointer to NSNumber type (NSNumber *).
Definition at line 587 of file SemaObjC.h.
NSStringDecl
ObjCInterfaceDecl* clang::SemaObjC::NSStringDecl
The declaration of the Objective-C NSString class.
Definition at line 596 of file SemaObjC.h.
NSStringPointer
QualType clang::SemaObjC::NSStringPointer
Pointer to NSString type (NSString *).
Definition at line 599 of file SemaObjC.h.
NSValueDecl
ObjCInterfaceDecl* clang::SemaObjC::NSValueDecl
The declaration of the Objective-C NSValue class.
Definition at line 584 of file SemaObjC.h.
NSValuePointer
QualType clang::SemaObjC::NSValuePointer
Pointer to NSValue type (NSValue *).
Definition at line 590 of file SemaObjC.h.
QIDNSCopying
QualType clang::SemaObjC::QIDNSCopying
id<NSCopying> type.
Definition at line 620 of file SemaObjC.h.
ReferencedSelectors
llvm::MapVector<Selector, SourceLocation> clang::SemaObjC::ReferencedSelectors
Method selectors used in a @selector expression.
Used for implementation of -Wselector.
Definition at line 186 of file SemaObjC.h.
RespondsToSelectorSel
Selector clang::SemaObjC::RespondsToSelectorSel
will hold 'respondsToSelector:'
Definition at line 623 of file SemaObjC.h.
StringWithUTF8StringMethod
ObjCMethodDecl* clang::SemaObjC::StringWithUTF8StringMethod
The declaration of the stringWithUTF8String: method.
Definition at line 602 of file SemaObjC.h.
ValueWithBytesObjCTypeMethod
ObjCMethodDecl* clang::SemaObjC::ValueWithBytesObjCTypeMethod
The declaration of the valueWithBytes:objCType: method.
Definition at line 605 of file SemaObjC.h.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaObjC.h
lib/Sema/SemaDeclObjC.cpp
lib/Sema/SemaExprObjC.cpp
lib/Sema/SemaObjC.cpp
lib/Sema/SemaObjCProperty.cpp