clang: clang::interp::Block Class Reference
clang::interp::Block Class Reference final
A memory block, either on the stack or in the heap.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/InterpBlock.h"
Public Member Functions
Block (const std::optional< unsigned > &DeclID, const Descriptor *Desc, bool IsStatic=false, bool IsExtern=false)
Creates a new block.
Block (const Descriptor *Desc, bool IsStatic=false, bool IsExtern=false)
const Descriptor * getDescriptor () const
Returns the block's descriptor.
bool hasPointers () const
Checks if the block has any live pointers.
bool isExtern () const
Checks if the block is extern.
bool isStatic () const
Checks if the block has static storage duration.
bool isTemporary () const
Checks if the block is temporary.
unsigned getSize () const
Returns the size of the block.
std::optional< unsigned > getDeclID () const
Returns the declaration ID.
bool isInitialized () const
std::byte * data ()
Returns a pointer to the stored data.
const std::byte * data () const
std::byte * rawData ()
Returns a pointer to the raw data, including metadata.
const std::byte * rawData () const
template<typename T >
T & deref ()
Returns a view over the data.
template<typename T >
const T & deref () const
void invokeCtor ()
Invokes the constructor.
void invokeDtor ()
Invokes the Destructor.
void dump () const
void dump (llvm::raw_ostream &OS) const
Protected Member Functions
Block (const Descriptor *Desc, bool IsExtern, bool IsStatic, bool IsDead)
void cleanup ()
Deletes a dead block at the end of its lifetime.
void addPointer (Pointer *P)
Pointer chain management.
void removePointer (Pointer *P)
void replacePointer (Pointer *Old, Pointer *New)
bool hasPointer (const Pointer *P) const
Protected Attributes
Pointer * Pointers = nullptr
Start of the chain of pointers.
std::optional< unsigned > DeclID
Unique identifier of the declaration.
bool IsStatic = false
Flag indicating if the block has static storage duration.
bool IsExtern = false
Flag indicating if the block is an extern.
bool IsDead = false
Flag indicating if the pointer is dead.
bool IsInitialized = false
Flag indicating if the block contents have been initialized via invokeCtor.
const Descriptor * Desc
Pointer to the stack slot descriptor.
Friends
class Pointer
class DeadBlock
class InterpState
Detailed Description
A memory block, either on the stack or in the heap.
The storage described by the block is immediately followed by optional metadata, which is followed by the actual data.
Block* rawData() data() │ │ │ │ │ │ ▼ ▼ ▼ ┌───────────────┬─────────────────────────┬─────────────────┐ │ Block │ Metadata │ Data │ │ sizeof(Block) │ Desc->getMetadataSize() │ Desc->getSize() │ └───────────────┴─────────────────────────┴─────────────────┘
Desc->getAllocSize() describes the size after the Block, i.e. the data size and the metadata size.
Definition at line 49 of file InterpBlock.h.
Constructor & Destructor Documentation
Block() [1/3]
clang::interp::Block::Block (const std::optional< unsigned > & DeclID, const Descriptor * Desc, bool IsStatic = false, bool IsExtern = false) inline
Creates a new block.
Definition at line 52 of file InterpBlock.h.
Block() [2/3]
clang::interp::Block::Block (const Descriptor * Desc, bool IsStatic = false, bool IsExtern = false) inline
Definition at line 56 of file InterpBlock.h.
Block() [3/3]
clang::interp::Block::Block (const Descriptor * Desc, bool IsExtern, bool IsStatic, bool IsDead) inline protected
Definition at line 129 of file InterpBlock.h.
Member Function Documentation
addPointer()
void Block::addPointer (Pointer * P) protected
Pointer chain management.
Definition at line 19 of file InterpBlock.cpp.
References hasPointer(), IsStatic, P, and Pointers.
Referenced by replacePointer().
cleanup()
void Block::cleanup () protected
Deletes a dead block at the end of its lifetime.
Definition at line 56 of file InterpBlock.cpp.
References IsDead, and Pointers.
Referenced by clang::interp::Pointer::operator=().
data() [1/2]
std::byte* clang::interp::Block::data () inline
Returns a pointer to the stored data.
You are allowed to read Desc->getSize() bytes from this address.
Definition at line 78 of file InterpBlock.h.
References Desc, clang::interp::Descriptor::getMetadataSize(), and rawData().
Referenced by clang::interp::DeadBlock::data(), clang::interp::InterpState::deallocate(), deref(), clang::interp::Pointer::elem(), invokeCtor(), and invokeDtor().
data() [2/2]
const std::byte* clang::interp::Block::data () const inline
Definition at line 83 of file InterpBlock.h.
References Desc, clang::interp::Descriptor::getMetadataSize(), and rawData().
deref() [1/2]
template<typename T > T& clang::interp::Block::deref () inline
Returns a view over the data.
Definition at line 100 of file InterpBlock.h.
References data(), and clang::T.
deref() [2/2]
template<typename T > const T& clang::interp::Block::deref () const inline
Definition at line 101 of file InterpBlock.h.
References data(), and clang::T.
dump() [1/2]
void clang::interp::Block::dump () const inline
Definition at line 121 of file InterpBlock.h.
References dump().
Referenced by dump().
dump() [2/2]
LLVM_DUMP_METHOD void Block::dump (llvm::raw_ostream & OS) const
Definition at line 268 of file Disasm.cpp.
References IsDead, IsExtern, IsInitialized, IsStatic, P, and Pointers.
getDeclID()
std::optional<unsigned> clang::interp::Block::getDeclID () const inline
Returns the declaration ID.
Definition at line 73 of file InterpBlock.h.
References DeclID.
Referenced by clang::interp::Pointer::getDeclID().
getDescriptor()
const Descriptor* clang::interp::Block::getDescriptor () const inline
Returns the block's descriptor.
Definition at line 61 of file InterpBlock.h.
References Desc.
Referenced by clang::interp::InterpState::deallocate().
getSize()
unsigned clang::interp::Block::getSize () const inline
Returns the size of the block.
Definition at line 71 of file InterpBlock.h.
References Desc, and clang::interp::Descriptor::getAllocSize().
Referenced by clang::interp::InterpState::deallocate().
hasPointer()
bool Block::hasPointer (const Pointer * P) const protected
Definition at line 85 of file InterpBlock.cpp.
References P, and Pointers.
Referenced by addPointer(), removePointer(), and replacePointer().
hasPointers()
bool clang::interp::Block::hasPointers () const inline
Checks if the block has any live pointers.
Definition at line 63 of file InterpBlock.h.
References Pointers.
Referenced by clang::interp::InterpState::deallocate().
invokeCtor()
void clang::interp::Block::invokeCtor () inline
Invokes the constructor.
Definition at line 106 of file InterpBlock.h.
References clang::interp::Descriptor::CtorFn, data(), Desc, clang::interp::Descriptor::getAllocSize(), clang::interp::Descriptor::IsConst, IsInitialized, clang::interp::Descriptor::IsMutable, memset(), and rawData().
Referenced by clang::interp::EvalEmitter::createLocal().
invokeDtor()
void clang::interp::Block::invokeDtor () inline
Invokes the Destructor.
Definition at line 115 of file InterpBlock.h.
References data(), Desc, clang::interp::Descriptor::DtorFn, and IsInitialized.
Referenced by clang::interp::InterpState::deallocate(), clang::interp::EvalEmitter::~EvalEmitter(), and clang::interp::InterpFrame::~InterpFrame().
isExtern()
bool clang::interp::Block::isExtern () const inline
Checks if the block is extern.
Definition at line 65 of file InterpBlock.h.
References IsExtern.
Referenced by clang::interp::Pointer::isExtern().
isInitialized()
bool clang::interp::Block::isInitialized () const inline
Definition at line 74 of file InterpBlock.h.
References IsInitialized.
Referenced by clang::interp::EvalEmitter::~EvalEmitter(), and clang::interp::InterpFrame::~InterpFrame().
isStatic()
bool clang::interp::Block::isStatic () const inline
Checks if the block has static storage duration.
Definition at line 67 of file InterpBlock.h.
References IsStatic.
Referenced by clang::interp::Pointer::isStatic().
isTemporary()
bool clang::interp::Block::isTemporary () const inline
Checks if the block is temporary.
Definition at line 69 of file InterpBlock.h.
References Desc, and clang::interp::Descriptor::IsTemporary.
Referenced by clang::interp::Pointer::isTemporary().
rawData() [1/2]
std::byte* clang::interp::Block::rawData () inline
Returns a pointer to the raw data, including metadata.
You are allowed to read Desc->getAllocSize() bytes from this address.
Definition at line 91 of file InterpBlock.h.
Referenced by data(), clang::interp::InterpState::deallocate(), clang::interp::Pointer::deref(), invokeCtor(), and clang::interp::DeadBlock::rawData().
rawData() [2/2]
const std::byte* clang::interp::Block::rawData () const inline
Definition at line 94 of file InterpBlock.h.
removePointer()
void Block::removePointer (Pointer * P) protected
Definition at line 36 of file InterpBlock.cpp.
References hasPointer(), IsStatic, P, and Pointers.
Referenced by replacePointer().
replacePointer()
void Block::replacePointer (Pointer * Old, Pointer * New) protected
Definition at line 61 of file InterpBlock.cpp.
References addPointer(), clang::interp::Pointer::BS, hasPointer(), IsStatic, clang::interp::BlockPointer::Pointee, Pointers, and removePointer().
Friends And Related Function Documentation
DeadBlock
friend class DeadBlock friend
Definition at line 126 of file InterpBlock.h.
InterpState
friend class InterpState friend
Definition at line 127 of file InterpBlock.h.
Pointer
friend class Pointer friend
Definition at line 125 of file InterpBlock.h.
Member Data Documentation
DeclID
std::optional<unsigned> clang::interp::Block::DeclID protected
Unique identifier of the declaration.
Definition at line 146 of file InterpBlock.h.
Referenced by getDeclID().
Desc
const Descriptor* clang::interp::Block::Desc protected
Pointer to the stack slot descriptor.
Definition at line 158 of file InterpBlock.h.
Referenced by ctorRecord(), data(), clang::interp::Pointer::getDeclDesc(), getDescriptor(), getSize(), invokeCtor(), invokeDtor(), and isTemporary().
IsDead
bool clang::interp::Block::IsDead = false protected
Flag indicating if the pointer is dead.
This is only ever set once, when converting the Block to a DeadBlock.
Definition at line 153 of file InterpBlock.h.
Referenced by cleanup(), dump(), and clang::interp::Pointer::isLive().
IsExtern
bool clang::interp::Block::IsExtern = false protected
Flag indicating if the block is an extern.
Definition at line 150 of file InterpBlock.h.
Referenced by dump(), and isExtern().
IsInitialized
bool clang::interp::Block::IsInitialized = false protected
Flag indicating if the block contents have been initialized via invokeCtor.
Definition at line 156 of file InterpBlock.h.
Referenced by clang::interp::InterpState::deallocate(), dump(), invokeCtor(), invokeDtor(), and isInitialized().
IsStatic
bool clang::interp::Block::IsStatic = false protected
Flag indicating if the block has static storage duration.
Definition at line 148 of file InterpBlock.h.
Referenced by addPointer(), dump(), isStatic(), removePointer(), and replacePointer().
Pointers
Pointer* clang::interp::Block::Pointers = nullptr protected
Start of the chain of pointers.
Definition at line 144 of file InterpBlock.h.
Referenced by addPointer(), cleanup(), clang::interp::DeadBlock::DeadBlock(), dump(), hasPointer(), hasPointers(), removePointer(), and replacePointer().
The documentation for this class was generated from the following files:
lib/AST/Interp/InterpBlock.h
lib/AST/Interp/Disasm.cpp
lib/AST/Interp/InterpBlock.cpp