clang: clang::FileID Class Reference
clang::FileID Class Reference
An opaque identifier used by SourceManager which refers to a source file (MemoryBuffer) along with its #include path and #line data.
#include "clang/Basic/SourceLocation.h"
Public Member Functions
bool isValid () const
bool isInvalid () const
bool operator== (const FileID &RHS) const
bool operator< (const FileID &RHS) const
bool operator<= (const FileID &RHS) const
bool operator!= (const FileID &RHS) const
bool operator> (const FileID &RHS) const
bool operator>= (const FileID &RHS) const
unsigned getHashValue () const
Static Public Member Functions
static FileID getSentinel ()
Friends
class ASTWriter
class ASTReader
class SourceManager
class SourceManagerTestHelper
Detailed Description
An opaque identifier used by SourceManager which refers to a source file (MemoryBuffer) along with its #include path and #line data.
Definition at line 39 of file SourceLocation.h.
Member Function Documentation
getHashValue()
unsigned clang::FileID::getHashValue () const inline
Definition at line 56 of file SourceLocation.h.
Referenced by clang::html::AddLineNumbers(), and clang::syntax::operator<<().
getSentinel()
static FileID clang::FileID::getSentinel () inline static
Definition at line 55 of file SourceLocation.h.
Referenced by llvm::DenseMapInfo< clang::FileID, void >::getTombstoneKey().
isInvalid()
bool clang::FileID::isInvalid () const inline
Definition at line 46 of file SourceLocation.h.
Referenced by clang::ASTUnit::addFileLevelDecl(), checkConfigMacro(), clang::SourceManager::getDecomposedIncludedLoc(), clang::ASTUnit::getEndOfPreambleFileID(), clang::SourceManager::getLineNumber(), clang::SourceManager::getMacroArgExpandedLocation(), clang::ASTUnit::getStartOfMainFileID(), clang::ento::PathDiagnosticConsumer::HandlePathDiagnostic(), clang::ASTImporter::Import(), clang::index::IndexingContext::importedModule(), clang::SourceManager::initializeForReplay(), clang::SourceManager::isAtEndOfImmediateMacroExpansion(), clang::SourceManager::isAtStartOfImmediateMacroExpansion(), clang::PreprocessingRecord::isEntityInFileID(), clang::ASTUnit::isInMainFileID(), clang::ASTUnit::isInPreambleFileID(), clang::edit::FileOffset::isInvalid(), clang::ASTUnit::mapLocationFromPreamble(), clang::ASTUnit::mapLocationToPreamble(), clang::SourceManager::setPreambleFileID(), clang::SourceManager::translateLineCol(), and clang::VerifyDiagnosticConsumer::UpdateParsedFileStatus().
isValid()
bool clang::FileID::isValid () const inline
Definition at line 45 of file SourceLocation.h.
Referenced by compileModule(), clang::Preprocessor::creatingPCHWithThroughHeader(), clang::TextDiagnostic::emitDiagnosticLoc(), clang::Preprocessor::EnterMainSourceFile(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::Preprocessor::HandleEndOfFile(), clang::ASTImporter::Import(), clang::CompilerInstance::InitializeSourceManager(), clang::InBeforeInTUCacheEntry::isCacheValid(), clang::SourceManager::isMainFile(), clang::Preprocessor::isPCHThroughHeader(), isPreprocessedEntityIfInFileID(), clang::ASTReader::ReadAST(), clang::ASTReader::ReadPragmaDiagnosticMappings(), updateExecutedLinesWithDiagnosticPieces(), and clang::Preprocessor::usingPCHWithThroughHeader().
operator!=()
bool clang::FileID::operator!= (const FileID & RHS) const inline
Definition at line 51 of file SourceLocation.h.
operator<()
bool clang::FileID::operator< (const FileID & RHS) const inline
Definition at line 49 of file SourceLocation.h.
operator<=()
bool clang::FileID::operator<= (const FileID & RHS) const inline
Definition at line 50 of file SourceLocation.h.
operator==()
bool clang::FileID::operator== (const FileID & RHS) const inline
Definition at line 48 of file SourceLocation.h.
operator>()
bool clang::FileID::operator> (const FileID & RHS) const inline
Definition at line 52 of file SourceLocation.h.
operator>=()
bool clang::FileID::operator>= (const FileID & RHS) const inline
Definition at line 53 of file SourceLocation.h.
Friends And Related Function Documentation
ASTReader
friend class ASTReader friend
Definition at line 60 of file SourceLocation.h.
ASTWriter
friend class ASTWriter friend
Definition at line 59 of file SourceLocation.h.
SourceManager
friend class SourceManager friend
Definition at line 61 of file SourceLocation.h.
SourceManagerTestHelper
friend class SourceManagerTestHelper friend
Definition at line 62 of file SourceLocation.h.
The documentation for this class was generated from the following file:
include/clang/Basic/SourceLocation.h