clang: clang::declvisitor::Base< Ptr, ImplClass, RetTy > Class Template Reference
clang::declvisitor::Base< Ptr, ImplClass, RetTy > Class Template Reference
A simple visitor class that helps create declaration visitors.
#include "clang/AST/DeclVisitor.h"
Public Member Functions
RetTy Visit (PTR(Decl) D)
RetTy VisitDecl (PTR(Decl) D)
Detailed Description
template<template< typename > class Ptr, typename ImplClass, typename RetTy = void>
class clang::declvisitor::Base< Ptr, ImplClass, RetTy >
A simple visitor class that helps create declaration visitors.
Definition at line 31 of file DeclVisitor.h.
Member Function Documentation
Visit()
template<template< typename > class Ptr, typename ImplClass , typename RetTy = void> RetTy clang::declvisitor::Base< Ptr, ImplClass, RetTy >::Visit (PTR(Decl) D) inline
Definition at line 37 of file DeclVisitor.h.
References clang::Decl::getKind().
Referenced by clang::TemplateDeclInstantiator::SubstTemplateParams(), and clang::JSONNodeDumper::Visit().
VisitDecl()
template<template< typename > class Ptr, typename ImplClass , typename RetTy = void> RetTy clang::declvisitor::Base< Ptr, ImplClass, RetTy >::VisitDecl (PTR(Decl) D) inline
Definition at line 53 of file DeclVisitor.h.
The documentation for this class was generated from the following file:
include/clang/AST/DeclVisitor.h