clang: clang::FPOptionsOverride Class Reference
clang::FPOptionsOverride Class Reference
Represents difference between two FPOptions values.
#include "clang/Basic/LangOptions.h"
Public Types
using RoundingMode = llvm::RoundingMode
using storage_type = uint64_t
The type suitable for storing values of FPOptionsOverride.
Public Member Functions
FPOptionsOverride ()
FPOptionsOverride (const LangOptions &LO)
FPOptionsOverride (FPOptions FPO)
FPOptionsOverride (FPOptions FPO, FPOptions::storage_type Mask)
bool requiresTrailingStorage () const
void setAllowFPContractWithinStatement ()
void setAllowFPContractAcrossStatement ()
void setDisallowFPContract ()
void setFPPreciseEnabled (bool Value)
void setDisallowOptimizations ()
storage_type getAsOpaqueInt () const
FPOptions applyOverrides (FPOptions Base)
FPOptions applyOverrides (const LangOptions &LO)
bool operator== (FPOptionsOverride other) const
bool operator!= (FPOptionsOverride other) const
LLVM_DUMP_METHOD void dump ()
Static Public Member Functions
static FPOptionsOverride getFromOpaqueInt (storage_type I)
Static Public Attributes
static constexpr storage_type OverrideMaskBits
Bit mask selecting bits of OverrideMask in serialized representation of FPOptionsOverride.
Detailed Description
Represents difference between two FPOptions values.
The effect of language constructs changing the set of floating point options is usually a change of some FP properties while leaving others intact. This class describes such changes by keeping information about what FP options are overridden.
The integral set of FP options, described by the class FPOptions, may be represented as a default FP option set, defined by language standard and command line options, with the overrides introduced by pragmas.
The is implemented as a value of the new FPOptions plus a mask showing which fields are actually set in it.
Definition at line 949 of file LangOptions.h.
Member Typedef Documentation
RoundingMode
using clang::FPOptionsOverride::RoundingMode = llvm::RoundingMode
Definition at line 954 of file LangOptions.h.
storage_type
using clang::FPOptionsOverride::storage_type = uint64_t
The type suitable for storing values of FPOptionsOverride.
Must be twice as wide as bit size of FPOption.
Definition at line 958 of file LangOptions.h.
Constructor & Destructor Documentation
FPOptionsOverride() [1/4]
clang::FPOptionsOverride::FPOptionsOverride () inline
Definition at line 967 of file LangOptions.h.
FPOptionsOverride() [2/4]
clang::FPOptionsOverride::FPOptionsOverride (const LangOptions & LO) inline
Definition at line 968 of file LangOptions.h.
FPOptionsOverride() [3/4]
clang::FPOptionsOverride::FPOptionsOverride (FPOptions FPO) inline
Definition at line 970 of file LangOptions.h.
FPOptionsOverride() [4/4]
clang::FPOptionsOverride::FPOptionsOverride (FPOptions FPO, FPOptions::storage_type Mask) inline
Definition at line 972 of file LangOptions.h.
Member Function Documentation
applyOverrides() [1/2]
FPOptions clang::FPOptionsOverride::applyOverrides (const LangOptions & LO) inline
Definition at line 1029 of file LangOptions.h.
References applyOverrides().
applyOverrides() [2/2]
FPOptions clang::FPOptionsOverride::applyOverrides (FPOptions Base) inline
Definition at line 1022 of file LangOptions.h.
References clang::FPOptions::getFromOpaqueInt().
Referenced by clang::Sema::ActOnPragmaCXLimitedRange(), clang::Sema::ActOnPragmaFEnvAccess(), clang::Sema::ActOnPragmaFEnvRound(), clang::Sema::ActOnPragmaFloatControl(), clang::Sema::ActOnPragmaFPContract(), clang::Sema::ActOnPragmaFPEvalMethod(), clang::Sema::ActOnPragmaFPValueChangingOption(), clang::FPOptions::applyChanges(), applyOverrides(), clang::UnaryOperator::getFPFeaturesInEffect(), clang::CallExpr::getFPFeaturesInEffect(), clang::CastExpr::getFPFeaturesInEffect(), clang::BinaryOperator::getFPFeaturesInEffect(), and clang::Sema::setExceptionMode().
dump()
LLVM_DUMP_METHOD void FPOptionsOverride::dump ()
Definition at line 232 of file LangOptions.cpp.
getAsOpaqueInt()
storage_type clang::FPOptionsOverride::getAsOpaqueInt () const inline
Definition at line 1010 of file LangOptions.h.
References clang::FPOptions::StorageBitSize.
getFromOpaqueInt()
static FPOptionsOverride clang::FPOptionsOverride::getFromOpaqueInt (storage_type I) inline static
Definition at line 1015 of file LangOptions.h.
References clang::FPOptions::getFromOpaqueInt(), OverrideMaskBits, and clang::FPOptions::StorageBitSize.
operator!=()
bool clang::FPOptionsOverride::operator!= (FPOptionsOverride other) const inline
Definition at line 1036 of file LangOptions.h.
operator==()
bool clang::FPOptionsOverride::operator== (FPOptionsOverride other) const inline
Definition at line 1033 of file LangOptions.h.
requiresTrailingStorage()
bool clang::FPOptionsOverride::requiresTrailingStorage () const inline
Definition at line 975 of file LangOptions.h.
Referenced by clang::BinaryOperator::BinaryOperator(), clang::CallExpr::CallExpr(), clang::CompoundStmt::Create(), clang::UnaryOperator::Create(), clang::BinaryOperator::Create(), clang::CompoundAssignOperator::Create(), clang::ImplicitCastExpr::Create(), clang::CStyleCastExpr::Create(), clang::CXXStaticCastExpr::Create(), clang::CXXFunctionalCastExpr::Create(), clang::UserDefinedLiteral::Create(), clang::CXXMemberCallExpr::Create(), clang::CallExpr::Create(), clang::CUDAKernelCallExpr::Create(), clang::CXXOperatorCallExpr::Create(), and clang::UnaryOperator::UnaryOperator().
setAllowFPContractAcrossStatement()
void clang::FPOptionsOverride::setAllowFPContractAcrossStatement () inline
Definition at line 981 of file LangOptions.h.
References clang::LangOptionsBase::FPM_Fast.
Referenced by clang::Sema::ActOnPragmaFPContract(), and setFPPreciseEnabled().
setAllowFPContractWithinStatement()
void clang::FPOptionsOverride::setAllowFPContractWithinStatement () inline
Definition at line 977 of file LangOptions.h.
References clang::LangOptionsBase::FPM_On.
Referenced by clang::Sema::ActOnPragmaFPContract(), and setFPPreciseEnabled().
setDisallowFPContract()
void clang::FPOptionsOverride::setDisallowFPContract () inline
Definition at line 985 of file LangOptions.h.
References clang::LangOptionsBase::FPM_Off.
Referenced by clang::Sema::ActOnPragmaFPContract(), and setDisallowOptimizations().
setDisallowOptimizations()
void clang::FPOptionsOverride::setDisallowOptimizations () inline
Definition at line 1005 of file LangOptions.h.
References setDisallowFPContract(), and setFPPreciseEnabled().
Referenced by clang::Sema::applyFunctionAttributesBeforeParsingBody().
setFPPreciseEnabled()
void clang::FPOptionsOverride::setFPPreciseEnabled (bool Value) inline
Definition at line 989 of file LangOptions.h.
References setAllowFPContractAcrossStatement(), and setAllowFPContractWithinStatement().
Referenced by clang::Sema::ActOnPragmaFloatControl(), and setDisallowOptimizations().
Member Data Documentation
OverrideMaskBits
constexpr storage_type clang::FPOptionsOverride::OverrideMaskBits static constexpr
Initial value:
=
      (static_cast<storage_type>(1) << FPOptions::StorageBitSize) - 1
Bit mask selecting bits of OverrideMask in serialized representation of FPOptionsOverride.
Definition at line 964 of file LangOptions.h.
Referenced by getFromOpaqueInt().
The documentation for this class was generated from the following files:
include/clang/Basic/LangOptions.h
lib/Basic/LangOptions.cpp