clang: clang::ento::ExplodedNode Class Reference
clang::ento::ExplodedNode Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/ExplodedGraph.h"
Public Types
using succ_iterator = ExplodedNode *const *
using succ_range = llvm::iterator_range< succ_iterator >
using const_succ_iterator = const ExplodedNode *const *
using const_succ_range = llvm::iterator_range< const_succ_iterator >
using pred_iterator = ExplodedNode *const *
using pred_range = llvm::iterator_range< pred_iterator >
using const_pred_iterator = const ExplodedNode *const *
using const_pred_range = llvm::iterator_range< const_pred_iterator >
Public Member Functions
ExplodedNode (const ProgramPoint &loc, ProgramStateRef state, int64_t Id, bool IsSink)
ProgramPoint getLocation () const
getLocation - Returns the edge associated with the given node.
const LocationContext * getLocationContext () const
const StackFrameContext * getStackFrame () const
const Decl & getCodeDecl () const
CFG & getCFG () const
const CFGBlock * getCFGBlock () const
const ParentMap & getParentMap () const
template<typename T >
T & getAnalysis () const
const ProgramStateRef & getState () const
template<typename T >
std::optional< T > getLocationAs () const &
SVal getSVal (const Stmt *S) const
Get the value of an arbitrary expression at this node.
void Profile (llvm::FoldingSetNodeID &ID) const
void addPredecessor (ExplodedNode *V, ExplodedGraph &G)
addPredeccessor - Adds a predecessor to the current node, and in tandem add this node as a successor of the other node.
unsigned succ_size () const
unsigned pred_size () const
bool succ_empty () const
bool pred_empty () const
bool isSink () const
bool hasSinglePred () const
ExplodedNode * getFirstPred ()
const ExplodedNode * getFirstPred () const
ExplodedNode * getFirstSucc ()
const ExplodedNode * getFirstSucc () const
pred_iterator pred_begin ()
pred_iterator pred_end ()
pred_range preds ()
const_pred_iterator pred_begin () const
const_pred_iterator pred_end () const
const_pred_range preds () const
succ_iterator succ_begin ()
succ_iterator succ_end ()
succ_range succs ()
const_succ_iterator succ_begin () const
const_succ_iterator succ_end () const
const_succ_range succs () const
int64_t getID () const
bool isTrivial () const
The node is trivial if it has only one successor, only one predecessor, it's predecessor has only one successor, and its program state is the same as the program state of the previous node.
const Stmt * getStmtForDiagnostics () const
If the node's program point corresponds to a statement, retrieve that statement.
const Stmt * getNextStmtForDiagnostics () const
Find the next statement that was executed on this node's execution path.
const Stmt * getPreviousStmtForDiagnostics () const
Find the statement that was executed immediately before this node.
const Stmt * getCurrentOrPreviousStmtForDiagnostics () const
Find the statement that was executed at or immediately before this node.
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, const ProgramPoint &Loc, const ProgramStateRef &state, bool IsSink)
Friends
class BranchNodeBuilder
class CoreEngine
class EndOfFunctionNodeBuilder
class ExplodedGraph
class IndirectGotoNodeBuilder
class NodeBuilder
class SwitchNodeBuilder
Detailed Description
Definition at line 66 of file ExplodedGraph.h.
Member Typedef Documentation
const_pred_iterator
using clang::ento::ExplodedNode::const_pred_iterator = const ExplodedNode * const *
Definition at line 235 of file ExplodedGraph.h.
const_pred_range
using clang::ento::ExplodedNode::const_pred_range = llvm::iterator_range<const_pred_iterator>
Definition at line 236 of file ExplodedGraph.h.
const_succ_iterator
using clang::ento::ExplodedNode::const_succ_iterator = const ExplodedNode * const *
Definition at line 229 of file ExplodedGraph.h.
const_succ_range
using clang::ento::ExplodedNode::const_succ_range = llvm::iterator_range<const_succ_iterator>
Definition at line 230 of file ExplodedGraph.h.
pred_iterator
using clang::ento::ExplodedNode::pred_iterator = ExplodedNode * const *
Definition at line 232 of file ExplodedGraph.h.
pred_range
using clang::ento::ExplodedNode::pred_range = llvm::iterator_range<pred_iterator>
Definition at line 233 of file ExplodedGraph.h.
succ_iterator
using clang::ento::ExplodedNode::succ_iterator = ExplodedNode * const *
Definition at line 226 of file ExplodedGraph.h.
succ_range
using clang::ento::ExplodedNode::succ_range = llvm::iterator_range<succ_iterator>
Definition at line 227 of file ExplodedGraph.h.
Constructor & Destructor Documentation
ExplodedNode()
clang::ento::ExplodedNode::ExplodedNode (const ProgramPoint & loc, ProgramStateRef state, int64_t Id, bool IsSink) inline explicit
Definition at line 138 of file ExplodedGraph.h.
References Id, and isSink().
Member Function Documentation
addPredecessor()
void ExplodedNode::addPredecessor (ExplodedNode * V, ExplodedGraph & G)
addPredeccessor - Adds a predecessor to the current node, and in tandem add this node as a successor of the other node.
Definition at line 204 of file ExplodedGraph.cpp.
References V.
Referenced by clang::ento::CoreEngine::enqueueStmtNode(), clang::ento::SwitchNodeBuilder::generateCaseStmtNode(), clang::ento::SwitchNodeBuilder::generateDefaultCaseNode(), clang::ento::IndirectGotoNodeBuilder::generateNode(), clang::ento::NodeBuilder::generateNodeImpl(), clang::ento::ExprEngine::processCallExit(), and clang::ento::ExplodedGraph::trim().
getAnalysis()
template<typename T > T& clang::ento::ExplodedNode::getAnalysis () const inline
Definition at line 165 of file ExplodedGraph.h.
References clang::LocationContext::getAnalysis(), getLocationContext(), and clang::T.
getCFG()
CFG& clang::ento::ExplodedNode::getCFG () const inline
Definition at line 157 of file ExplodedGraph.h.
References clang::LocationContext::getCFG(), and getLocationContext().
getCFGBlock()
const CFGBlock * ExplodedNode::getCFGBlock () const
Definition at line 289 of file ExplodedGraph.cpp.
References getLocation(), and P.
getCodeDecl()
const Decl& clang::ento::ExplodedNode::getCodeDecl () const inline
Definition at line 155 of file ExplodedGraph.h.
References clang::LocationContext::getDecl(), and getLocationContext().
Referenced by clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath().
getCurrentOrPreviousStmtForDiagnostics()
const Stmt * ExplodedNode::getCurrentOrPreviousStmtForDiagnostics () const
Find the statement that was executed at or immediately before this node.
Useful when any nearby statement will do. If the statement belongs to a body-farmed definition, retrieve the call site for that definition.
Definition at line 385 of file ExplodedGraph.cpp.
Referenced by clang::ento::PathSensitiveBugReport::Profile().
getFirstPred() [1/2]
ExplodedNode* clang::ento::ExplodedNode::getFirstPred () inline
Definition at line 209 of file ExplodedGraph.h.
References pred_begin(), and pred_empty().
Referenced by annotateStartParameter(), clang::ento::CoreEngine::dispatchWorkItem(), findExecutedLines(), generateVisitorsDiagnostics(), getAcquireSite(), GetAllocationSite(), getCalleeNode(), getFirstPred(), getMatchingCallExitEnd(), getPreviousStmtForDiagnostics(), isTrivial(), peelOffOuterExpr(), clang::ento::TrackConstraintBRVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode(), clang::ento::ConditionBRVisitor::VisitNodeImpl(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
getFirstPred() [2/2]
const ExplodedNode* clang::ento::ExplodedNode::getFirstPred () const inline
Definition at line 213 of file ExplodedGraph.h.
References getFirstPred().
getFirstSucc() [1/2]
ExplodedNode* clang::ento::ExplodedNode::getFirstSucc () inline
Definition at line 217 of file ExplodedGraph.h.
References succ_begin(), and succ_empty().
Referenced by llvm::GraphTraits< clang::ento::ExplodedGraph * >::child_end(), getFirstSucc(), getMatchingCallExitEnd(), getNextStmtForDiagnostics(), llvm::GraphTraits< clang::ento::ExplodedGraph * >::predecessorOfTrivial(), and llvm::DOTGraphTraits< ExplodedGraph * >::traverseHiddenNodes().
getFirstSucc() [2/2]
const ExplodedNode* clang::ento::ExplodedNode::getFirstSucc () const inline
Definition at line 221 of file ExplodedGraph.h.
References getFirstSucc().
getID()
int64_t clang::ento::ExplodedNode::getID () const inline
Definition at line 262 of file ExplodedGraph.h.
References Id.
Referenced by clang::ento::ExplodedGraph::trim().
getLocation()
ProgramPoint clang::ento::ExplodedNode::getLocation () const inline
getLocation - Returns the edge associated with the given node.
Definition at line 145 of file ExplodedGraph.h.
Referenced by alreadyExecutedAtLeastOneLoopIteration(), clang::ento::bugreporter::StoreHandler::constructNote(), clang::ento::CoreEngine::dispatchWorkItem(), clang::ento::WorkList::enqueue(), clang::ento::CoreEngine::enqueueStmtNode(), clang::ento::ExprEngine::evalEagerlyAssumeBinOpBifurcation(), GetAllocationSite(), getCFGBlock(), getLocationContext(), clang::ento::CheckerContext::getLocationRegionIfPostStore(), clang::ento::StackHintGeneratorForSymbol::getMessage(), getStackFrame(), clang::ento::PathSensitiveBugReport::getStmt(), getStmtBeforeCond(), getStmtForDiagnostics(), llvm::DOTGraphTraits< ExplodedGraph * >::nodeHasBugReport(), peelOffOuterExpr(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::processEndOfFunction(), clang::ento::ExplodedGraph::trim(), clang::ento::ExprEngine::VisitLogicalExpr(), clang::ento::TrackConstraintBRVisitor::VisitNode(), clang::ento::UndefOrNullArgVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::TagVisitor::VisitNode(), clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode(), clang::ento::ConditionBRVisitor::VisitNodeImpl(), and clang::ento::ExprEngine::VisitObjCMessage().
getLocationAs()
template<typename T > std::optional<T> clang::ento::ExplodedNode::getLocationAs () const & inline
Definition at line 171 of file ExplodedGraph.h.
References clang::T.
Referenced by annotateStartParameter(), findExecutedLines(), getMatchingCallExitEnd(), isInitializationOfVar(), showBRDiagnostics(), clang::ento::NoStateChangeFuncVisitor::VisitNode(), clang::ento::NilReceiverBRVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), and wasRegionOfInterestModifiedAt().
getLocationContext()
const LocationContext* clang::ento::ExplodedNode::getLocationContext () const inline
Definition at line 147 of file ExplodedGraph.h.
References getLocation(), and clang::ProgramPoint::getLocationContext().
Referenced by assumeCondition(), clang::ento::retaincountchecker::RetainCountChecker::checkEndFunction(), constructDebugPieceForTrackedCondition(), clang::ento::ExprEngine::CreateCXXTemporaryObject(), clang::ento::CoreEngine::enqueueStmtNode(), clang::ento::ExprEngine::evalEagerlyAssumeBinOpBifurcation(), clang::ento::FalsePositiveRefutationBRVisitor::finalizeVisitor(), findExecutedLines(), clang::ento::SwitchNodeBuilder::generateCaseStmtNode(), clang::ento::SwitchNodeBuilder::generateDefaultCaseNode(), clang::ento::IndirectGotoNodeBuilder::generateNode(), clang::ento::BranchNodeBuilder::generateNode(), GetAllocationSite(), getAnalysis(), getArgumentValueString(), getCFG(), getCodeDecl(), clang::ento::CheckerContext::getCurrentAnalysisDeclContext(), clang::ento::PathSensitiveBugReport::getDeclWithIssue(), clang::ento::CheckerContext::getLocationContext(), clang::ento::IndirectGotoNodeBuilder::getLocationContext(), clang::ento::SwitchNodeBuilder::getLocationContext(), getLocationRegionIfReference(), getParentMap(), getStmtForDiagnostics(), getSValForVar(), clang::ento::ExprEngine::handleUOExtension(), clang::ento::isCapturedByReference(), isInitializationOfVar(), clang::ento::ConditionBRVisitor::patternMatch(), clang::ento::ExprEngine::ProcessAutomaticObjDtor(), clang::ento::ExprEngine::ProcessBaseDtor(), clang::ento::ExprEngine::processBranch(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::processCFGElement(), clang::ento::ExprEngine::processCleanupTemporaryBranch(), clang::ento::ExprEngine::ProcessDeleteDtor(), clang::ento::ExprEngine::processEndOfFunction(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::ProcessMemberDtor(), clang::ento::ExprEngine::ProcessNewAllocator(), clang::ento::retaincountchecker::RetainCountChecker::processObjCLiterals(), clang::ento::ExprEngine::ProcessStmt(), clang::ento::ExprEngine::ProcessTemporaryDtor(), REGISTER_TRAIT_WITH_PROGRAMSTATE(), clang::ento::ExprEngine::removeDeadOnEndOfFunction(), clang::ento::CheckerManager::runCheckersForEndFunction(), clang::ento::updateLoopStack(), clang::ento::ExprEngine::VisitBlockExpr(), clang::ento::ExprEngine::VisitCallExpr(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCommonDeclRefExpr(), clang::ento::ExprEngine::VisitCompoundLiteralExpr(), clang::ento::ConditionBRVisitor::VisitConditionVariable(), clang::ento::ExprEngine::VisitCXXCatchStmt(), clang::ento::ExprEngine::VisitCXXDeleteExpr(), clang::ento::ExprEngine::VisitCXXNewAllocatorCall(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::ExprEngine::VisitCXXThisExpr(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ento::ExprEngine::VisitGCCAsmStmt(), clang::ento::ExprEngine::VisitGuardedExpr(), clang::ento::ExprEngine::VisitIncrementDecrementOperator(), clang::ento::ExprEngine::VisitInitListExpr(), clang::ento::ExprEngine::VisitLambdaExpr(), clang::ento::ExprEngine::VisitLogicalExpr(), clang::ento::ExprEngine::VisitLvalObjCIvarRefExpr(), clang::ento::NoStateChangeFuncVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode(), clang::ento::ExprEngine::VisitObjCMessage(), clang::ento::ExprEngine::VisitOffsetOfExpr(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
getNextStmtForDiagnostics()
const Stmt * ExplodedNode::getNextStmtForDiagnostics () const
Find the next statement that was executed on this node's execution path.
Useful for explaining control flow that follows the current node. If the statement belongs to a body-farmed definition, retrieve the call site for that definition.
Definition at line 350 of file ExplodedGraph.cpp.
References getFirstSucc().
getParentMap()
const ParentMap& clang::ento::ExplodedNode::getParentMap () const inline
Definition at line 161 of file ExplodedGraph.h.
References getLocationContext(), and clang::LocationContext::getParentMap().
getPreviousStmtForDiagnostics()
const Stmt * ExplodedNode::getPreviousStmtForDiagnostics () const
Find the statement that was executed immediately before this node.
Useful when the node corresponds to a CFG block entrance. If the statement belongs to a body-farmed definition, retrieve the call site for that definition.
Definition at line 377 of file ExplodedGraph.cpp.
References getFirstPred().
getStackFrame()
const StackFrameContext* clang::ento::ExplodedNode::getStackFrame () const inline
Definition at line 151 of file ExplodedGraph.h.
References getLocation(), and clang::ProgramPoint::getStackFrame().
Referenced by annotateConsumedSummaryMismatch(), getCalleeNode(), getMatchingCallExitEnd(), clang::ento::CheckerContext::getStackFrame(), isVarAnInterestingCondition(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::processEndOfFunction(), and clang::ento::NoStateChangeFuncVisitor::VisitNode().
getState()
const ProgramStateRef& clang::ento::ExplodedNode::getState () const inline
Definition at line 169 of file ExplodedGraph.h.
Referenced by clang::ento::FalsePositiveRefutationBRVisitor::addConstraints(), annotateConsumedSummaryMismatch(), annotateStartParameter(), assumeCondition(), clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), clang::ento::retaincountchecker::RetainCountChecker::checkEndFunction(), clang::ento::CheckerContext::CheckerContext(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::ento::ExprEngine::CreateCXXTemporaryObject(), clang::ento::ExprEngine::defaultEvalCall(), clang::ento::CoreEngine::enqueueStmtNode(), clang::ento::ExprEngine::evalEagerlyAssumeBinOpBifurcation(), getAcquireSite(), GetAllocationSite(), getArgumentValueString(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), getLocationRegionIfReference(), clang::ento::StackHintGeneratorForSymbol::getMessage(), clang::ento::CheckerContext::getState(), getSValForVar(), clang::ento::ExprEngine::handleUOExtension(), hasVisibleUpdate(), isTrivial(), llvm::DOTGraphTraits< ExplodedGraph * >::nodeHasBugReport(), clang::ento::PathSensitiveBugReport::PathSensitiveBugReport(), clang::ento::ConditionBRVisitor::patternMatch(), clang::ento::ExprEngine::ProcessAutomaticObjDtor(), clang::ento::ExprEngine::ProcessBaseDtor(), clang::ento::ExprEngine::processBranch(), clang::ento::ExprEngine::processCallEnter(), clang::ento::ExprEngine::processCallExit(), clang::ento::ExprEngine::processCFGBlockEntrance(), clang::ento::ExprEngine::processCleanupTemporaryBranch(), clang::ento::ExprEngine::ProcessDeleteDtor(), clang::ento::ExprEngine::processEndOfFunction(), clang::ento::ExprEngine::ProcessInitializer(), clang::ento::ExprEngine::ProcessMemberDtor(), clang::ento::ExprEngine::ProcessNewAllocator(), clang::ento::ExprEngine::ProcessTemporaryDtor(), REGISTER_TRAIT_WITH_PROGRAMSTATE(), clang::ento::ExprEngine::removeDead(), clang::ento::updateLoopStack(), clang::ento::ExprEngine::VisitBlockExpr(), clang::ento::ExprEngine::VisitCallExpr(), clang::ento::ExprEngine::VisitCast(), clang::ento::ExprEngine::VisitCommonDeclRefExpr(), clang::ento::ExprEngine::VisitCompoundLiteralExpr(), clang::ento::ExprEngine::VisitCXXCatchStmt(), clang::ento::ExprEngine::VisitCXXDeleteExpr(), clang::ento::ExprEngine::VisitCXXNewAllocatorCall(), clang::ento::ExprEngine::VisitCXXNewExpr(), clang::ento::ExprEngine::VisitCXXThisExpr(), clang::ento::ExprEngine::VisitDeclStmt(), clang::ento::ExprEngine::VisitGCCAsmStmt(), clang::ento::ExprEngine::VisitGuardedExpr(), clang::ento::ExprEngine::VisitIncrementDecrementOperator(), clang::ento::ExprEngine::VisitInitListExpr(), clang::ento::ExprEngine::VisitLambdaExpr(), clang::ento::ExprEngine::VisitLogicalExpr(), clang::ento::ExprEngine::VisitLvalObjCIvarRefExpr(), clang::ento::ExprEngine::VisitMSAsmStmt(), clang::ento::NoStateChangeFuncVisitor::VisitNode(), clang::ento::UndefOrNullArgVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::SuppressInlineDefensiveChecksVisitor::VisitNode(), clang::ento::ExprEngine::VisitObjCMessage(), clang::ento::ExprEngine::VisitOffsetOfExpr(), clang::ento::ConditionBRVisitor::VisitTrueTest(), and wasRegionOfInterestModifiedAt().
getStmtForDiagnostics()
const Stmt * ExplodedNode::getStmtForDiagnostics () const
If the node's program point corresponds to a statement, retrieve that statement.
Useful for figuring out where to put a warning or a note. If the statement belongs to a body-farmed definition, retrieve the call site for that definition.
Definition at line 319 of file ExplodedGraph.cpp.
References findTopAutosynthesizedParentContext(), clang::LocationContext::getAnalysisDeclContext(), getLocation(), getLocationContext(), clang::AnalysisDeclContext::isBodyAutosynthesized(), and P.
getSVal()
SVal clang::ento::ExplodedNode::getSVal (const Stmt * S) const inline
Get the value of an arbitrary expression at this node.
Definition at line 176 of file ExplodedGraph.h.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::ento::CheckerContext::getCalleeDecl(), clang::ento::StackHintGeneratorForSymbol::getMessage(), clang::ento::retaincountchecker::RetainCountChecker::processObjCLiterals(), and wasRegionOfInterestModifiedAt().
hasSinglePred()
bool clang::ento::ExplodedNode::hasSinglePred () const inline
Definition at line 205 of file ExplodedGraph.h.
References pred_size().
Referenced by clang::ento::CoreEngine::dispatchWorkItem().
isSink()
bool clang::ento::ExplodedNode::isSink () const inline
Definition at line 203 of file ExplodedGraph.h.
Referenced by checkInvariantViolation(), clang::ento::CoreEngine::enqueueStmtNode(), ExplodedNode(), clang::ento::NodeBuilderWithSinks::generateSink(), Profile(), and clang::ento::ExplodedGraph::trim().
isTrivial()
bool ExplodedNode::isTrivial () const
The node is trivial if it has only one successor, only one predecessor, it's predecessor has only one successor, and its program state is the same as the program state of the previous node.
Trivial nodes may be skipped while printing exploded graph.
Definition at line 283 of file ExplodedGraph.cpp.
References getFirstPred(), getState(), pred_size(), and succ_size().
Referenced by llvm::DOTGraphTraits< ExplodedGraph * >::isNodeHidden(), and llvm::GraphTraits< clang::ento::ExplodedGraph * >::predecessorOfTrivial().
pred_begin() [1/2]
pred_iterator clang::ento::ExplodedNode::pred_begin () inline
Definition at line 238 of file ExplodedGraph.h.
Referenced by getFirstPred(), pred_begin(), clang::ento::ExprEngine::VisitGuardedExpr(), and clang::ento::ExprEngine::VisitLogicalExpr().
pred_begin() [2/2]
const_pred_iterator clang::ento::ExplodedNode::pred_begin () const inline
Definition at line 242 of file ExplodedGraph.h.
References pred_begin().
pred_empty()
bool clang::ento::ExplodedNode::pred_empty () const inline
Definition at line 201 of file ExplodedGraph.h.
Referenced by getFirstPred(), and clang::ento::isPossiblyEscaped().
pred_end() [1/2]
pred_iterator clang::ento::ExplodedNode::pred_end () inline
Definition at line 239 of file ExplodedGraph.h.
Referenced by pred_end().
pred_end() [2/2]
const_pred_iterator clang::ento::ExplodedNode::pred_end () const inline
Definition at line 245 of file ExplodedGraph.h.
References pred_end().
pred_size()
unsigned clang::ento::ExplodedNode::pred_size () const inline
Definition at line 199 of file ExplodedGraph.h.
Referenced by hasSinglePred(), isTrivial(), and clang::ento::ExprEngine::VisitLogicalExpr().
preds() [1/2]
pred_range clang::ento::ExplodedNode::preds () inline
Definition at line 240 of file ExplodedGraph.h.
Referenced by alreadyExecutedAtLeastOneLoopIteration().
preds() [2/2]
const_pred_range clang::ento::ExplodedNode::preds () const inline
Definition at line 248 of file ExplodedGraph.h.
Profile() [1/2]
void clang::ento::ExplodedNode::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 189 of file ExplodedGraph.h.
References ID, isSink(), and Profile().
Profile() [2/2]
static void clang::ento::ExplodedNode::Profile (llvm::FoldingSetNodeID & ID, const ProgramPoint & Loc, const ProgramStateRef & state, bool IsSink) inline static
Definition at line 180 of file ExplodedGraph.h.
References ID.
Referenced by clang::ento::ExplodedGraph::getNode(), and Profile().
succ_begin() [1/2]
succ_iterator clang::ento::ExplodedNode::succ_begin () inline
Definition at line 250 of file ExplodedGraph.h.
Referenced by llvm::GraphTraits< clang::ento::ExplodedGraph * >::child_begin(), getFirstSucc(), and succ_begin().
succ_begin() [2/2]
const_succ_iterator clang::ento::ExplodedNode::succ_begin () const inline
Definition at line 254 of file ExplodedGraph.h.
References succ_begin().
succ_empty()
bool clang::ento::ExplodedNode::succ_empty () const inline
Definition at line 200 of file ExplodedGraph.h.
Referenced by getFirstSucc().
succ_end() [1/2]
succ_iterator clang::ento::ExplodedNode::succ_end () inline
Definition at line 251 of file ExplodedGraph.h.
Referenced by llvm::GraphTraits< clang::ento::ExplodedGraph * >::child_end(), and succ_end().
succ_end() [2/2]
const_succ_iterator clang::ento::ExplodedNode::succ_end () const inline
Definition at line 257 of file ExplodedGraph.h.
References succ_end().
succ_size()
unsigned clang::ento::ExplodedNode::succ_size () const inline
Definition at line 198 of file ExplodedGraph.h.
Referenced by getMatchingCallExitEnd(), isTrivial(), llvm::GraphTraits< clang::ento::ExplodedGraph * >::predecessorOfTrivial(), and llvm::DOTGraphTraits< ExplodedGraph * >::traverseHiddenNodes().
succs() [1/2]
succ_range clang::ento::ExplodedNode::succs () inline
Definition at line 252 of file ExplodedGraph.h.
succs() [2/2]
const_succ_range clang::ento::ExplodedNode::succs () const inline
Definition at line 260 of file ExplodedGraph.h.
Friends And Related Function Documentation
BranchNodeBuilder
friend class BranchNodeBuilder friend
Definition at line 67 of file ExplodedGraph.h.
CoreEngine
friend class CoreEngine friend
Definition at line 68 of file ExplodedGraph.h.
EndOfFunctionNodeBuilder
friend class EndOfFunctionNodeBuilder friend
Definition at line 69 of file ExplodedGraph.h.
ExplodedGraph
friend class ExplodedGraph friend
Definition at line 70 of file ExplodedGraph.h.
IndirectGotoNodeBuilder
friend class IndirectGotoNodeBuilder friend
Definition at line 71 of file ExplodedGraph.h.
NodeBuilder
friend class NodeBuilder friend
Definition at line 72 of file ExplodedGraph.h.
SwitchNodeBuilder
friend class SwitchNodeBuilder friend
Definition at line 73 of file ExplodedGraph.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/ExplodedGraph.h
lib/StaticAnalyzer/Core/ExplodedGraph.cpp