clang: clang::PresumedLoc Class Reference
clang::PresumedLoc Class Reference
Represents an unpacked "presumed" location which can be presented to the user.
#include "clang/Basic/SourceLocation.h"
Public Member Functions
PresumedLoc ()=default
PresumedLoc (const char *FN, FileID FID, unsigned Ln, unsigned Co, SourceLocation IL)
bool isInvalid () const
Return true if this object is invalid or uninitialized.
bool isValid () const
const char * getFilename () const
Return the presumed filename of this location.
FileID getFileID () const
unsigned getLine () const
Return the presumed line number of this location.
unsigned getColumn () const
Return the presumed column number of this location.
SourceLocation getIncludeLoc () const
Return the presumed include location of this location.
Detailed Description
Represents an unpacked "presumed" location which can be presented to the user.
A 'presumed' location can be modified by #line and GNU line marker directives and is always the expansion point of a normal location.
You can get a PresumedLoc from a SourceLocation with SourceManager.
Definition at line 304 of file SourceLocation.h.
Constructor & Destructor Documentation
PresumedLoc() [1/2]
clang::PresumedLoc::PresumedLoc () default
PresumedLoc() [2/2]
clang::PresumedLoc::PresumedLoc (const char * FN, FileID FID, unsigned Ln, unsigned Co, SourceLocation IL) inline
Definition at line 312 of file SourceLocation.h.
References Filename.
Member Function Documentation
getColumn()
unsigned clang::PresumedLoc::getColumn () const inline
Return the presumed column number of this location.
This cannot be affected by #line, but is packaged here for convenience.
Definition at line 347 of file SourceLocation.h.
References isValid().
Referenced by clang::TextNodeDumper::dumpLocation(), clang::SYCLIntegrationHeader::emit(), clang::CodeGen::CodeGenFunction::EmitCheckSourceLocation(), clang::TextDiagnostic::emitDiagnosticLoc(), emitMappingInformation(), clang::CodeGen::CGOpenMPRuntime::emitUpdateLocation(), clang::AnalysisDeclContext::getFunctionName(), getIdentStringFromSourceLocation(), clang::SourceManager::getPresumedColumnNumber(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::index::FileIndexRecord::print(), clang::SourceLocation::print(), and clang::printSourceLocationAsJson().
getFileID()
FileID clang::PresumedLoc::getFileID () const inline
Definition at line 331 of file SourceLocation.h.
References isValid().
getFilename()
const char* clang::PresumedLoc::getFilename () const inline
Return the presumed filename of this location.
This can be affected by #line etc.
Definition at line 326 of file SourceLocation.h.
References Filename, and isValid().
Referenced by clang::DoPrintPreprocessedInput(), clang::TextNodeDumper::dumpLocation(), clang::SYCLIntegrationHeader::emit(), clang::CodeGen::CodeGenModule::EmitAnnotationUnit(), clang::DiagnosticNoteRenderer::emitBuildingModuleLocation(), clang::TextDiagnostic::emitBuildingModuleLocation(), clang::CodeGen::CodeGenFunction::EmitCheckSourceLocation(), clang::TextDiagnostic::emitDiagnosticLoc(), clang::DiagnosticNoteRenderer::emitImportLocation(), clang::TextDiagnostic::emitImportLocation(), clang::DiagnosticNoteRenderer::emitIncludeLocation(), clang::TextDiagnostic::emitIncludeLocation(), emitMappingInformation(), emitTargetTeamsLoopCodegenStatus(), clang::CodeGen::CGOpenMPRuntime::emitUpdateLocation(), getEntryInfoFromPresumedLoc(), getIdentStringFromSourceLocation(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::Preprocessor::HandlePragmaSystemHeader(), clang::SourceManager::isWrittenInBuiltinFile(), clang::SourceManager::isWrittenInCommandLineFile(), clang::SourceManager::isWrittenInScratchSpace(), clang::index::FileIndexRecord::print(), clang::SourceLocation::print(), clang::printSourceLocationAsJson(), and clang::extractapi::SymbolGraphSerializer::serializeSingleSymbolSGF().
getIncludeLoc()
SourceLocation clang::PresumedLoc::getIncludeLoc () const inline
Return the presumed include location of this location.
This can be affected by GNU linemarker directives.
Definition at line 355 of file SourceLocation.h.
References isValid().
Referenced by ReadLineMarkerFlags().
getLine()
unsigned clang::PresumedLoc::getLine () const inline
Return the presumed line number of this location.
This can be affected by #line etc.
Definition at line 339 of file SourceLocation.h.
References isValid().
Referenced by clang::TextNodeDumper::dumpLocation(), clang::SYCLIntegrationHeader::emit(), clang::CodeGen::CodeGenModule::EmitAnnotationLineNo(), clang::DiagnosticNoteRenderer::emitBuildingModuleLocation(), clang::TextDiagnostic::emitBuildingModuleLocation(), clang::CodeGen::CodeGenFunction::EmitCheckSourceLocation(), clang::TextDiagnostic::emitDiagnosticLoc(), clang::DiagnosticNoteRenderer::emitImportLocation(), clang::TextDiagnostic::emitImportLocation(), clang::DiagnosticNoteRenderer::emitIncludeLocation(), clang::TextDiagnostic::emitIncludeLocation(), emitMappingInformation(), emitTargetTeamsLoopCodegenStatus(), clang::CodeGen::CGOpenMPRuntime::emitUpdateLocation(), getEntryInfoFromPresumedLoc(), clang::AnalysisDeclContext::getFunctionName(), getIdentStringFromSourceLocation(), clang::SourceManager::getPresumedLineNumber(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::Preprocessor::HandlePragmaSystemHeader(), clang::index::FileIndexRecord::print(), clang::SourceLocation::print(), and clang::printSourceLocationAsJson().
isInvalid()
bool clang::PresumedLoc::isInvalid () const inline
Return true if this object is invalid or uninitialized.
This occurs when created with invalid source locations or when walking off the top of a #include stack.
Definition at line 320 of file SourceLocation.h.
References Filename.
Referenced by clang::DoPrintPreprocessedInput(), clang::TextNodeDumper::dumpLocation(), clang::TextDiagnostic::emitDiagnosticLoc(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::Preprocessor::HandlePragmaSystemHeader(), clang::SourceManager::isWrittenInBuiltinFile(), clang::SourceManager::isWrittenInCommandLineFile(), clang::SourceManager::isWrittenInScratchSpace(), clang::SourceLocation::print(), clang::printSourceLocationAsJson(), ReadLineMarkerFlags(), and clang::CodeGen::CGDebugInfo::setLocation().
isValid()
bool clang::PresumedLoc::isValid () const inline
Definition at line 321 of file SourceLocation.h.
References Filename.
Referenced by clang::CodeGen::CodeGenModule::EmitAnnotationLineNo(), clang::CodeGen::CodeGenModule::EmitAnnotationUnit(), clang::DiagnosticNoteRenderer::emitBuildingModuleLocation(), clang::TextDiagnostic::emitBuildingModuleLocation(), clang::CodeGen::CodeGenFunction::EmitCheckSourceLocation(), clang::DiagnosticNoteRenderer::emitImportLocation(), clang::TextDiagnostic::emitImportLocation(), clang::TextDiagnostic::emitIncludeLocation(), emitTargetTeamsLoopCodegenStatus(), getColumn(), getFileID(), getFilename(), clang::AnalysisDeclContext::getFunctionName(), getIncludeLoc(), and getLine().
The documentation for this class was generated from the following file:
include/clang/Basic/SourceLocation.h