clang: clang::driver::tools::visualstudio::Linker Class Reference
clang::driver::tools::visualstudio::Linker Class Reference final
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/MSVC.h"
Public Member Functions
Linker (const ToolChain &TC)
bool hasIntegratedCPP () const override
bool isLinkJob () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Definition at line 27 of file MSVC.h.
Constructor & Destructor Documentation
Linker()
clang::driver::tools::visualstudio::Linker::Linker (const ToolChain & TC) inline
Definition at line 29 of file MSVC.h.
Member Function Documentation
ConstructJob()
void visualstudio::Linker::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 103 of file MSVC.cpp.
References clang::driver::tools::addFortranRuntimeLibraryPath(), clang::driver::tools::addFortranRuntimeLibs(), clang::driver::tools::addHIPRuntimeLibArgs(), clang::driver::tools::AddRunTimeLibs(), clang::driver::ResponseFileSupport::AtFileUTF16(), canExecute(), clang::FileName, FindVisualStudioExecutable(), clang::driver::InputInfo::getFilename(), clang::driver::Action::getType(), clang::driver::tools::isDependentLibAdded(), clang::driver::InputInfo::isFilename(), clang::driver::InputInfo::isNothing(), clang::driver::Driver::OMPRT_GOMP, clang::driver::Driver::OMPRT_IOMP5, clang::driver::Driver::OMPRT_OMP, and clang::driver::Driver::OMPRT_Unknown.
hasIntegratedCPP()
bool clang::driver::tools::visualstudio::Linker::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 31 of file MSVC.h.
isLinkJob()
bool clang::driver::tools::visualstudio::Linker::isLinkJob () const inline override virtual
Reimplemented from clang::driver::Tool.
Definition at line 32 of file MSVC.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/MSVC.h
lib/Driver/ToolChains/MSVC.cpp