clang: clang::ento::PathDiagnosticPiece Class Reference
clang::ento::PathDiagnosticPiece Class Reference abstract
#include "clang/Analysis/PathDiagnostic.h"
Public Types
enum Kind {
ControlFlow , Event , Macro , Call ,
Note , PopUp
}
enum DisplayHint { Above , Below }
Public Member Functions
PathDiagnosticPiece ()=delete
PathDiagnosticPiece (const PathDiagnosticPiece &)=delete
PathDiagnosticPiece & operator= (const PathDiagnosticPiece &)=delete
virtual ~PathDiagnosticPiece ()
StringRef getString () const
void setTag (const char *tag)
Tag this PathDiagnosticPiece with the given C-string.
const void * getTag () const
Return the opaque tag (if any) on the PathDiagnosticPiece.
StringRef getTagStr () const
Return the string representation of the tag.
DisplayHint getDisplayHint () const
getDisplayHint - Return a hint indicating where the diagnostic should be displayed by the PathDiagnosticConsumer.
virtual PathDiagnosticLocation getLocation () const =0
virtual void flattenLocations ()=0
Kind getKind () const
void addRange (SourceRange R)
void addRange (SourceLocation B, SourceLocation E)
void addFixit (FixItHint F)
ArrayRef< SourceRange > getRanges () const
Return the SourceRanges associated with this PathDiagnosticPiece.
ArrayRef< FixItHint > getFixits () const
Return the fix-it hints associated with this PathDiagnosticPiece.
virtual void Profile (llvm::FoldingSetNodeID &ID) const
void setAsLastInMainSourceFile ()
bool isLastInMainSourceFile () const
virtual void dump () const =0
Protected Member Functions
PathDiagnosticPiece (StringRef s, Kind k, DisplayHint hint=Below)
PathDiagnosticPiece (Kind k, DisplayHint hint=Below)
Detailed Description
Definition at line 403 of file PathDiagnostic.h.
Member Enumeration Documentation
DisplayHint
enum clang::ento::PathDiagnosticPiece::DisplayHint
Enumerator
Above
Below
Definition at line 406 of file PathDiagnostic.h.
Kind
enum clang::ento::PathDiagnosticPiece::Kind
Enumerator
ControlFlow
Event
Macro
Call
Note
PopUp
Definition at line 405 of file PathDiagnostic.h.
Constructor & Destructor Documentation
PathDiagnosticPiece() [1/4]
PathDiagnosticPiece::PathDiagnosticPiece (StringRef s, Kind k, DisplayHint hint = Below) protected
Definition at line 55 of file PathDiagnostic.cpp.
PathDiagnosticPiece() [2/4]
PathDiagnosticPiece::PathDiagnosticPiece (Kind k, DisplayHint hint = Below) protected
Definition at line 59 of file PathDiagnostic.cpp.
PathDiagnosticPiece() [3/4]
clang::ento::PathDiagnosticPiece::PathDiagnosticPiece () delete
PathDiagnosticPiece() [4/4]
clang::ento::PathDiagnosticPiece::PathDiagnosticPiece (const PathDiagnosticPiece &) delete
~PathDiagnosticPiece()
PathDiagnosticPiece::~PathDiagnosticPiece () virtual default
Member Function Documentation
addFixit()
void clang::ento::PathDiagnosticPiece::addFixit (FixItHint F) inline
Definition at line 469 of file PathDiagnostic.h.
addRange() [1/2]
void clang::ento::PathDiagnosticPiece::addRange (SourceLocation B, SourceLocation E) inline
Definition at line 463 of file PathDiagnostic.h.
References clang::SourceLocation::isValid().
addRange() [2/2]
void clang::ento::PathDiagnosticPiece::addRange (SourceRange R) inline
Definition at line 457 of file PathDiagnostic.h.
References clang::SourceRange::isValid().
Referenced by clang::ento::PathDiagnosticSpotPiece::PathDiagnosticSpotPiece().
dump()
virtual void clang::ento::PathDiagnosticPiece::dump () const pure virtual
Implemented in clang::ento::PathDiagnosticPopUpPiece, clang::ento::PathDiagnosticNotePiece, clang::ento::PathDiagnosticMacroPiece, clang::ento::PathDiagnosticControlFlowPiece, clang::ento::PathDiagnosticCallPiece, and clang::ento::PathDiagnosticEventPiece.
flattenLocations()
virtual void clang::ento::PathDiagnosticPiece::flattenLocations () pure virtual
Implemented in clang::ento::PathDiagnosticMacroPiece, clang::ento::PathDiagnosticControlFlowPiece, clang::ento::PathDiagnosticCallPiece, and clang::ento::PathDiagnosticSpotPiece.
getDisplayHint()
DisplayHint clang::ento::PathDiagnosticPiece::getDisplayHint () const inline
getDisplayHint - Return a hint indicating where the diagnostic should be displayed by the PathDiagnosticConsumer.
Definition at line 450 of file PathDiagnostic.h.
getFixits()
ArrayRef<FixItHint> clang::ento::PathDiagnosticPiece::getFixits () const inline
Return the fix-it hints associated with this PathDiagnosticPiece.
Definition at line 477 of file PathDiagnostic.h.
getKind()
Kind clang::ento::PathDiagnosticPiece::getKind () const inline
Definition at line 455 of file PathDiagnostic.h.
Referenced by calculateImportance(), and comparePiece().
getLocation()
virtual PathDiagnosticLocation clang::ento::PathDiagnosticPiece::getLocation () const pure virtual
Implemented in clang::ento::PathDiagnosticControlFlowPiece, clang::ento::PathDiagnosticCallPiece, and clang::ento::PathDiagnosticSpotPiece.
Referenced by comparePiece(), clang::ento::PathDiagnosticConsumer::HandlePathDiagnostic(), and resetDiagnosticLocationToMainFile().
getRanges()
ArrayRef<SourceRange> clang::ento::PathDiagnosticPiece::getRanges () const inline
Return the SourceRanges associated with this PathDiagnosticPiece.
Definition at line 474 of file PathDiagnostic.h.
Referenced by comparePiece(), and clang::ento::PathDiagnosticConsumer::HandlePathDiagnostic().
getString()
StringRef clang::ento::PathDiagnosticPiece::getString () const inline
Definition at line 436 of file PathDiagnostic.h.
Referenced by comparePiece(), and clang::ento::ConditionBRVisitor::isPieceMessageGeneric().
getTag()
const void* clang::ento::PathDiagnosticPiece::getTag () const inline
Return the opaque tag (if any) on the PathDiagnosticPiece.
Definition at line 442 of file PathDiagnostic.h.
Referenced by eventsDescribeSameCondition().
getTagStr()
StringRef clang::ento::PathDiagnosticPiece::getTagStr () const inline
Return the string representation of the tag.
This is useful for debugging.
Definition at line 446 of file PathDiagnostic.h.
Referenced by calculateImportance().
isLastInMainSourceFile()
bool clang::ento::PathDiagnosticPiece::isLastInMainSourceFile () const inline
Definition at line 485 of file PathDiagnostic.h.
operator=()
PathDiagnosticPiece& clang::ento::PathDiagnosticPiece::operator= (const PathDiagnosticPiece &) delete
Profile()
void PathDiagnosticPiece::Profile (llvm::FoldingSetNodeID & ID) const virtual
Reimplemented in clang::ento::PathDiagnosticPopUpPiece, clang::ento::PathDiagnosticNotePiece, clang::ento::PathDiagnosticMacroPiece, clang::ento::PathDiagnosticControlFlowPiece, clang::ento::PathDiagnosticCallPiece, and clang::ento::PathDiagnosticSpotPiece.
Definition at line 1093 of file PathDiagnostic.cpp.
References getKind(), and ID.
Referenced by clang::ento::PathDiagnosticSpotPiece::Profile(), clang::ento::PathDiagnosticCallPiece::Profile(), and clang::ento::PathDiagnosticControlFlowPiece::Profile().
setAsLastInMainSourceFile()
void clang::ento::PathDiagnosticPiece::setAsLastInMainSourceFile () inline
Definition at line 481 of file PathDiagnostic.h.
Referenced by resetDiagnosticLocationToMainFile().
setTag()
void clang::ento::PathDiagnosticPiece::setTag (const char * tag) inline
Tag this PathDiagnosticPiece with the given C-string.
Definition at line 439 of file PathDiagnostic.h.
The documentation for this class was generated from the following files:
include/clang/Analysis/PathDiagnostic.h
lib/Analysis/PathDiagnostic.cpp