clang: DiagDeviceFunction Class Reference
DiagDeviceFunction Class Reference
Public Member Functions
DiagDeviceFunction (SemaSYCL &S, const llvm::SmallPtrSetImpl< const FunctionDecl * > &RecursiveFuncs)
void CheckBody (Stmt *ToBeDiagnosed)
bool VisitCallExpr (CallExpr *e)
bool VisitCXXTypeidExpr (CXXTypeidExpr *E)
bool VisitCXXDynamicCastExpr (const CXXDynamicCastExpr *E)
bool TraverseVarDecl (VarDecl *VD)
bool TraverseTemplateArgumentLoc (const TemplateArgumentLoc &ArgLoc)
bool TraverseStaticAssertDecl (StaticAssertDecl *D)
bool TraverseCaseStmt (CaseStmt *S)
bool TraverseConstantArrayTypeLoc (const ConstantArrayTypeLoc &ArrLoc)
bool TraverseIfStmt (IfStmt *S)
Public Member Functions inherited from clang::RecursiveASTVisitor< DiagDeviceFunction >
DiagDeviceFunction & getDerived ()
Return a reference to the derived class.
bool shouldVisitTemplateInstantiations () const
Return whether this visitor should recurse into template instantiations.
bool shouldWalkTypesOfTypeLocs () const
Return whether this visitor should recurse into the types of TypeLocs.
bool shouldVisitImplicitCode () const
Return whether this visitor should recurse into implicit code, e.g., implicit constructors and destructors.
bool shouldVisitLambdaBody () const
Return whether this visitor should recurse into lambda body.
bool shouldTraversePostOrder () const
Return whether this visitor should traverse post-order.
bool TraverseAST (ASTContext &AST)
Recursively visits an entire AST, starting from the TranslationUnitDecl.
bool TraverseStmt (Stmt *S, DataRecursionQueue *Queue=nullptr)
Recursively visit a statement or expression, by dispatching to Traverse*() based on the argument's dynamic type.
bool dataTraverseStmtPre (Stmt *S)
Invoked before visiting a statement or expression via data recursion.
bool dataTraverseStmtPost (Stmt *S)
Invoked after visiting a statement or expression via data recursion.
bool TraverseType (QualType T)
Recursively visit a type, by dispatching to Traverse*Type() based on the argument's getTypeClass() property.
bool TraverseTypeLoc (TypeLoc TL)
Recursively visit a type with location, by dispatching to Traverse*TypeLoc() based on the argument type's getTypeClass() property.
bool TraverseAttr (Attr *At)
Recursively visit an attribute, by dispatching to Traverse*Attr() based on the argument's dynamic type.
bool TraverseDecl (Decl *D)
Recursively visit a declaration, by dispatching to Traverse*Decl() based on the argument's dynamic type.
bool TraverseNestedNameSpecifier (NestedNameSpecifier *NNS)
Recursively visit a C++ nested-name-specifier.
bool TraverseNestedNameSpecifierLoc (NestedNameSpecifierLoc NNS)
Recursively visit a C++ nested-name-specifier with location information.
bool TraverseDeclarationNameInfo (DeclarationNameInfo NameInfo)
Recursively visit a name with its location information.
bool TraverseTemplateName (TemplateName Template)
Recursively visit a template name and dispatch to the appropriate method.
bool TraverseTemplateArgument (const TemplateArgument &Arg)
Recursively visit a template argument and dispatch to the appropriate method for the argument type.
bool TraverseTemplateArgumentLoc (const TemplateArgumentLoc &ArgLoc)
Recursively visit a template argument location and dispatch to the appropriate method for the argument type.
bool TraverseTemplateArguments (ArrayRef< TemplateArgument > Args)
Recursively visit a set of template arguments.
bool TraverseCXXBaseSpecifier (const CXXBaseSpecifier &Base)
Recursively visit a base specifier.
bool TraverseConstructorInitializer (CXXCtorInitializer *Init)
Recursively visit a constructor initializer.
bool TraverseLambdaCapture (LambdaExpr *LE, const LambdaCapture *C, Expr *Init)
Recursively visit a lambda capture.
bool TraverseSynOrSemInitListExpr (InitListExpr *S, DataRecursionQueue *Queue=nullptr)
Recursively visit the syntactic or semantic form of an initialization list.
bool TraverseObjCProtocolLoc (ObjCProtocolLoc ProtocolLoc)
Recursively visit an Objective-C protocol reference with location information.
bool TraverseConceptReference (ConceptReference *CR)
Recursively visit concept reference with location information.
bool VisitConceptReference (ConceptReference *CR)
bool VisitAttr (Attr *A)
Stmt::child_range getStmtChildren (Stmt *S)
bool WalkUpFromStmt (Stmt *S)
bool VisitStmt (Stmt *S)
bool WalkUpFromType (Type *T)
bool VisitType (Type *T)
bool WalkUpFromTypeLoc (TypeLoc TL)
bool VisitTypeLoc (TypeLoc TL)
bool WalkUpFromQualifiedTypeLoc (QualifiedTypeLoc TL)
bool VisitQualifiedTypeLoc (QualifiedTypeLoc TL)
bool WalkUpFromUnqualTypeLoc (UnqualTypeLoc TL)
bool VisitUnqualTypeLoc (UnqualTypeLoc TL)
bool WalkUpFromDecl (Decl *D)
bool VisitDecl (Decl *D)
bool canIgnoreChildDeclWhileTraversingDeclContext (const Decl *Child)
bool TraverseTypeConstraint (const TypeConstraint *C)
bool TraverseConceptRequirement (concepts::Requirement *R)
bool TraverseConceptTypeRequirement (concepts::TypeRequirement *R)
bool TraverseConceptExprRequirement (concepts::ExprRequirement *R)
bool TraverseConceptNestedRequirement (concepts::NestedRequirement *R)
bool dataTraverseNode (Stmt *S, DataRecursionQueue *Queue)
Additional Inherited Members
Public Types inherited from clang::RecursiveASTVisitor< DiagDeviceFunction >
typedef SmallVectorImpl< llvm::PointerIntPair< Stmt *, 1, bool > > DataRecursionQueue
A queue used for performing data recursion over statements.
Detailed Description
Definition at line 568 of file SemaSYCL.cpp.
Constructor & Destructor Documentation
DiagDeviceFunction()
DiagDeviceFunction::DiagDeviceFunction (SemaSYCL & S, const llvm::SmallPtrSetImpl< const FunctionDecl * > & RecursiveFuncs) inline
Definition at line 573 of file SemaSYCL.cpp.
Member Function Documentation
CheckBody()
void DiagDeviceFunction::CheckBody (Stmt * ToBeDiagnosed) inline
Definition at line 578 of file SemaSYCL.cpp.
TraverseCaseStmt()
bool DiagDeviceFunction::TraverseCaseStmt (CaseStmt * S) inline
Definition at line 670 of file SemaSYCL.cpp.
TraverseConstantArrayTypeLoc()
bool DiagDeviceFunction::TraverseConstantArrayTypeLoc (const ConstantArrayTypeLoc & ArrLoc) inline
Definition at line 676 of file SemaSYCL.cpp.
TraverseIfStmt()
bool DiagDeviceFunction::TraverseIfStmt (IfStmt * S) inline
Definition at line 680 of file SemaSYCL.cpp.
TraverseStaticAssertDecl()
bool DiagDeviceFunction::TraverseStaticAssertDecl (StaticAssertDecl * D) inline
Definition at line 666 of file SemaSYCL.cpp.
TraverseTemplateArgumentLoc()
bool DiagDeviceFunction::TraverseTemplateArgumentLoc (const TemplateArgumentLoc & ArgLoc) inline
Definition at line 660 of file SemaSYCL.cpp.
TraverseVarDecl()
bool DiagDeviceFunction::TraverseVarDecl (VarDecl * VD) inline
Definition at line 652 of file SemaSYCL.cpp.
References clang::VarDecl::isConstexpr().
VisitCallExpr()
bool DiagDeviceFunction::VisitCallExpr (CallExpr * e) inline
Definition at line 580 of file SemaSYCL.cpp.
References clang::SemaBase::Diag(), clang::CallExpr::getDirectCallee(), clang::Expr::getExprLoc(), clang::SemaBase::getLangOpts(), IsSyclMathFunc(), clang::SemaSYCL::KernelCallDllimportFunction, clang::SemaSYCL::KernelCallRecursiveFunction, and clang::SemaSYCL::KernelCallVirtualFunction.
VisitCXXDynamicCastExpr()
bool DiagDeviceFunction::VisitCXXDynamicCastExpr (const CXXDynamicCastExpr * E) inline
Definition at line 645 of file SemaSYCL.cpp.
References clang::SemaBase::Diag(), clang::Expr::getExprLoc(), and clang::SemaSYCL::KernelRTTI.
VisitCXXTypeidExpr()
bool DiagDeviceFunction::VisitCXXTypeidExpr (CXXTypeidExpr * E) inline
Definition at line 639 of file SemaSYCL.cpp.
References clang::SemaBase::Diag(), clang::Expr::getExprLoc(), and clang::SemaSYCL::KernelRTTI.
The documentation for this class was generated from the following file:
lib/Sema/SemaSYCL.cpp