clang: clang::LocalDeclID Class Reference
clang::LocalDeclID Class Reference
#include "clang/AST/DeclID.h"
Public Member Functions
LocalDeclID ()
LocalDeclID & operator++ ()
LocalDeclID operator++ (int)
Public Member Functions inherited from clang::DeclIDBase
DeclID getRawValue () const
operator DeclID () const
operator PredefinedDeclIDs () const
bool isValid () const
bool isInvalid () const
unsigned getModuleFileIndex () const
unsigned getLocalDeclIndex () const
Static Public Member Functions
static LocalDeclID get (ASTReader &Reader, serialization::ModuleFile &MF, DeclID ID)
static LocalDeclID get (ASTReader &Reader, serialization::ModuleFile &MF, unsigned ModuleFileIndex, unsigned LocalDeclID)
Friends
class ASTWriter
class GlobalDeclID
Additional Inherited Members
Public Types inherited from clang::DeclIDBase
using DeclID = uint64_t
An ID number that refers to a declaration in an AST file.
Protected Member Functions inherited from clang::DeclIDBase
DeclIDBase ()
DeclIDBase (DeclID ID)
Protected Attributes inherited from clang::DeclIDBase
DeclID ID
Detailed Description
Definition at line 185 of file DeclID.h.
Constructor & Destructor Documentation
LocalDeclID()
clang::LocalDeclID::LocalDeclID () inline
Definition at line 196 of file DeclID.h.
Member Function Documentation
get() [1/2]
LocalDeclID LocalDeclID::get (ASTReader & Reader, serialization::ModuleFile & MF, DeclID ID) static
Definition at line 911 of file ASTReader.cpp.
References ID, clang::serialization::ModuleFile::LocalNumDecls, clang::serialization::ModuleFile::ModuleOffsetMap, clang::NUM_PREDEF_DECL_IDS, and clang::serialization::ModuleFile::TransitiveImports.
Referenced by clang::ASTReader::FindExternalLexicalDecls(), clang::ASTReader::FindFileRegionDecls(), get(), clang::ASTReader::mapGlobalIDToModuleFileGlobalID(), clang::ASTReader::ModuleDeclIterator::operator*(), clang::serialization::reader::ASTIdentifierLookupTrait::ReadData(), clang::serialization::reader::ASTSelectorLookupTrait::ReadData(), clang::serialization::reader::ASTDeclContextNameLookupTrait::ReadDataInto(), and clang::ASTReader::ReadDeclID().
get() [2/2]
LocalDeclID LocalDeclID::get (ASTReader & Reader, serialization::ModuleFile & MF, unsigned ModuleFileIndex, unsigned LocalDeclID) static
Definition at line 938 of file ASTReader.cpp.
References get().
operator++() [1/2]
LocalDeclID& clang::LocalDeclID::operator++ () inline
Definition at line 203 of file DeclID.h.
References clang::DeclIDBase::ID.
operator++() [2/2]
LocalDeclID clang::LocalDeclID::operator++ (int) inline
Definition at line 208 of file DeclID.h.
References clang::interp::Ret().
Friends And Related Function Documentation
ASTWriter
friend class ASTWriter friend
Definition at line 192 of file DeclID.h.
GlobalDeclID
friend class GlobalDeclID friend
Definition at line 193 of file DeclID.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclID.h
lib/Serialization/ASTReader.cpp