clang: DerefSimplePtrArithFixableGadget Class Reference
DerefSimplePtrArithFixableGadget Class Reference
Public Member Functions
DerefSimplePtrArithFixableGadget (const MatchFinder::MatchResult &Result)
virtual std::optional< FixItList > getFixits (const FixitStrategy &s) const final
virtual const Stmt * getBaseStmt () const final
virtual DeclUseList getClaimedVarUseSites () const final
Static Public Member Functions
static Matcher matcher ()
Detailed Description
Definition at line 1277 of file UnsafeBufferUsage.cpp.
Constructor & Destructor Documentation
DerefSimplePtrArithFixableGadget()
DerefSimplePtrArithFixableGadget::DerefSimplePtrArithFixableGadget (const MatchFinder::MatchResult & Result) inline
Definition at line 1289 of file UnsafeBufferUsage.cpp.
Member Function Documentation
getBaseStmt()
virtual const Stmt* DerefSimplePtrArithFixableGadget::getBaseStmt () const inline final virtual
Definition at line 1320 of file UnsafeBufferUsage.cpp.
getClaimedVarUseSites()
virtual DeclUseList DerefSimplePtrArithFixableGadget::getClaimedVarUseSites () const inline final virtual
Definition at line 1322 of file UnsafeBufferUsage.cpp.
getFixits()
std::optional< FixItList > DerefSimplePtrArithFixableGadget::getFixits (const FixitStrategy & s) const final virtual
Definition at line 1897 of file UnsafeBufferUsage.cpp.
References clang::Decl::getASTContext(), clang::DeclRefExpr::getDecl(), clang::ASTContext::getSourceManager(), Offset, s, and SM.
matcher()
static Matcher DerefSimplePtrArithFixableGadget::matcher () inline static
Definition at line 1297 of file UnsafeBufferUsage.cpp.
The documentation for this class was generated from the following file:
lib/Analysis/UnsafeBufferUsage.cpp