clang: clang::OMPDistScheduleClause Class Reference
clang::OMPDistScheduleClause Class Reference
This represents 'dist_schedule' clause in the '#pragma omp ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
OMPDistScheduleClause (SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation KLoc, SourceLocation CommaLoc, SourceLocation EndLoc, OpenMPDistScheduleClauseKind Kind, Expr *ChunkSize, Stmt *HelperChunkSize)
Build 'dist_schedule' clause with schedule kind Kind and chunk size expression ChunkSize.
OMPDistScheduleClause ()
Build an empty clause.
OpenMPDistScheduleClauseKind getDistScheduleKind () const
Get kind of the clause.
SourceLocation getLParenLoc ()
Get location of '('.
SourceLocation getDistScheduleKindLoc ()
Get kind location.
SourceLocation getCommaLoc ()
Get location of ','.
Expr * getChunkSize ()
Get chunk size.
const Expr * getChunkSize () const
Get chunk size.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents 'dist_schedule' clause in the '#pragma omp ...' directive.
#pragma omp distribute dist_schedule(static, 3)
In this example directive '#pragma omp distribute' has 'dist_schedule' clause with arguments 'static' and '3'.
Definition at line 6420 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPDistScheduleClause() [1/2]
clang::OMPDistScheduleClause::OMPDistScheduleClause (SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation KLoc, SourceLocation CommaLoc, SourceLocation EndLoc, OpenMPDistScheduleClauseKind Kind, Expr * ChunkSize, Stmt * HelperChunkSize) inline
Build 'dist_schedule' clause with schedule kind Kind and chunk size expression ChunkSize.
Parameters
StartLoc Starting location of the clause.
LParenLoc Location of '('.
KLoc Starting location of the argument.
CommaLoc Location of ','.
EndLoc Ending location of the clause.
Kind DistSchedule kind.
ChunkSize Chunk size.
HelperChunkSize Helper chunk size for combined directives.
Definition at line 6475 of file OpenMPClause.h.
References clang::OMPClauseWithPreInit::setPreInitStmt().
OMPDistScheduleClause() [2/2]
clang::OMPDistScheduleClause::OMPDistScheduleClause () inline explicit
Build an empty clause.
Definition at line 6487 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPDistScheduleClause::children () inline
Definition at line 6510 of file OpenMPClause.h.
Referenced by children().
children() [2/2]
const_child_range clang::OMPDistScheduleClause::children () const inline
Definition at line 6515 of file OpenMPClause.h.
References children().
classof()
static bool clang::OMPDistScheduleClause::classof (const OMPClause * T) inline static
Definition at line 6527 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
getChunkSize() [1/2]
Expr* clang::OMPDistScheduleClause::getChunkSize () inline
Get chunk size.
Definition at line 6505 of file OpenMPClause.h.
getChunkSize() [2/2]
const Expr* clang::OMPDistScheduleClause::getChunkSize () const inline
Get chunk size.
Definition at line 6508 of file OpenMPClause.h.
getCommaLoc()
SourceLocation clang::OMPDistScheduleClause::getCommaLoc () inline
Get location of ','.
Definition at line 6502 of file OpenMPClause.h.
getDistScheduleKind()
OpenMPDistScheduleClauseKind clang::OMPDistScheduleClause::getDistScheduleKind () const inline
Get kind of the clause.
Definition at line 6493 of file OpenMPClause.h.
getDistScheduleKindLoc()
SourceLocation clang::OMPDistScheduleClause::getDistScheduleKindLoc () inline
Get kind location.
Definition at line 6499 of file OpenMPClause.h.
getLParenLoc()
SourceLocation clang::OMPDistScheduleClause::getLParenLoc () inline
Get location of '('.
Definition at line 6496 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPDistScheduleClause::used_children () inline
Definition at line 6520 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPDistScheduleClause::used_children () const inline
Definition at line 6523 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 6421 of file OpenMPClause.h.
The documentation for this class was generated from the following file:
include/clang/AST/OpenMPClause.h