clang: clang::CompoundStmt Class Reference
clang::CompoundStmt Class Reference final
CompoundStmt - This represents a group of statements like { stmt stmt }.
#include "clang/AST/Stmt.h"
Public Types
using body_iterator = Stmt **
using body_range = llvm::iterator_range< body_iterator >
using const_body_iterator = Stmt *const *
using body_const_range = llvm::iterator_range< const_body_iterator >
using reverse_body_iterator = std::reverse_iterator< body_iterator >
using const_reverse_body_iterator = std::reverse_iterator< const_body_iterator >
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
CompoundStmt (SourceLocation Loc)
CompoundStmt (SourceLocation Loc, SourceLocation EndLoc)
bool body_empty () const
unsigned size () const
bool hasStoredFPFeatures () const
FPOptionsOverride getStoredFPFeatures () const
Get FPOptionsOverride from trailing storage.
body_range body ()
body_iterator body_begin ()
body_iterator body_end ()
Stmt * body_front ()
Stmt * body_back ()
body_const_range body () const
const_body_iterator body_begin () const
const_body_iterator body_end () const
const Stmt * body_front () const
const Stmt * body_back () const
reverse_body_iterator body_rbegin ()
reverse_body_iterator body_rend ()
const_reverse_body_iterator body_rbegin () const
const_reverse_body_iterator body_rend () const
Stmt * getStmtExprResult ()
const Stmt * getStmtExprResult () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
SourceLocation getLBracLoc () const
SourceLocation getRBracLoc () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical, bool ProfileLambdaExpr=false) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static CompoundStmt * Create (const ASTContext &C, ArrayRef< Stmt * > Stmts, FPOptionsOverride FPFeatures, SourceLocation LB, SourceLocation RB)
static CompoundStmt * CreateEmpty (const ASTContext &C, unsigned NumStmts, bool HasFPFeatures)
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Friends
class ASTStmtReader
Additional Inherited Members
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator< T, const T *const, const Stmt *const >
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator< Expr >
using ConstExprIterator = ConstCastIterator< Expr >
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
CompoundStmt - This represents a group of statements like { stmt stmt }.
Definition at line 1604 of file Stmt.h.
Member Typedef Documentation
body_const_range
using clang::CompoundStmt::body_const_range = llvm::iterator_range<const_body_iterator>
Definition at line 1674 of file Stmt.h.
body_iterator
using clang::CompoundStmt::body_iterator = Stmt **
Definition at line 1661 of file Stmt.h.
body_range
using clang::CompoundStmt::body_range = llvm::iterator_range<body_iterator>
Definition at line 1662 of file Stmt.h.
const_body_iterator
using clang::CompoundStmt::const_body_iterator = Stmt *const *
Definition at line 1673 of file Stmt.h.
const_reverse_body_iterator
using clang::CompoundStmt::const_reverse_body_iterator = std::reverse_iterator<const_body_iterator>
Definition at line 1704 of file Stmt.h.
reverse_body_iterator
using clang::CompoundStmt::reverse_body_iterator = std::reverse_iterator<body_iterator>
Definition at line 1694 of file Stmt.h.
Constructor & Destructor Documentation
CompoundStmt() [1/2]
clang::CompoundStmt::CompoundStmt (SourceLocation Loc) inline explicit
Definition at line 1638 of file Stmt.h.
CompoundStmt() [2/2]
clang::CompoundStmt::CompoundStmt (SourceLocation Loc, SourceLocation EndLoc) inline
Definition at line 1640 of file Stmt.h.
References clang::Stmt::CompoundStmtBits.
Member Function Documentation
body() [1/2]
body_range clang::CompoundStmt::body () inline
Definition at line 1664 of file Stmt.h.
References body_begin(), and body_end().
Referenced by clang::CodeGen::CodeGenFunction::emitImplicitAssignmentOperatorBody(), getStmtExprResult(), isBodyEmpty(), and isCapturedBy().
body() [2/2]
body_const_range clang::CompoundStmt::body () const inline
Definition at line 1676 of file Stmt.h.
References body_begin(), and body_end().
body_back() [1/2]
Stmt* clang::CompoundStmt::body_back () inline
Definition at line 1669 of file Stmt.h.
References body_begin(), body_empty(), and size().
Referenced by getStmtExprResult(), and clang::Expr::isUnusedResultAWarning().
body_back() [2/2]
const Stmt* clang::CompoundStmt::body_back () const inline
Definition at line 1690 of file Stmt.h.
References body_begin(), body_empty(), and size().
body_begin() [1/2]
body_iterator clang::CompoundStmt::body_begin () inline
Definition at line 1665 of file Stmt.h.
Referenced by body(), body_back(), body_end(), body_front(), body_rend(), children(), and isIdenticalStmt().
body_begin() [2/2]
const_body_iterator clang::CompoundStmt::body_begin () const inline
Definition at line 1680 of file Stmt.h.
body_empty()
bool clang::CompoundStmt::body_empty () const inline
Definition at line 1650 of file Stmt.h.
References clang::Stmt::CompoundStmtBits.
Referenced by body_back(), body_front(), clang::Sema::BuildStmtExpr(), and clang::Expr::isUnusedResultAWarning().
body_end() [1/2]
body_iterator clang::CompoundStmt::body_end () inline
Definition at line 1666 of file Stmt.h.
References body_begin(), and size().
Referenced by body(), body_rbegin(), children(), and isIdenticalStmt().
body_end() [2/2]
const_body_iterator clang::CompoundStmt::body_end () const inline
Definition at line 1684 of file Stmt.h.
References body_begin(), and size().
body_front() [1/2]
Stmt* clang::CompoundStmt::body_front () inline
Definition at line 1667 of file Stmt.h.
References body_begin(), and body_empty().
body_front() [2/2]
const Stmt* clang::CompoundStmt::body_front () const inline
Definition at line 1686 of file Stmt.h.
References body_begin(), and body_empty().
body_rbegin() [1/2]
reverse_body_iterator clang::CompoundStmt::body_rbegin () inline
Definition at line 1696 of file Stmt.h.
References body_end().
body_rbegin() [2/2]
const_reverse_body_iterator clang::CompoundStmt::body_rbegin () const inline
Definition at line 1707 of file Stmt.h.
References body_end().
body_rend() [1/2]
reverse_body_iterator clang::CompoundStmt::body_rend () inline
Definition at line 1700 of file Stmt.h.
References body_begin().
body_rend() [2/2]
const_reverse_body_iterator clang::CompoundStmt::body_rend () const inline
Definition at line 1711 of file Stmt.h.
References body_begin().
children() [1/2]
child_range clang::CompoundStmt::children () inline
Definition at line 1746 of file Stmt.h.
References body_begin(), and body_end().
children() [2/2]
const_child_range clang::CompoundStmt::children () const inline
Definition at line 1748 of file Stmt.h.
References body_begin(), and body_end().
classof()
static bool clang::CompoundStmt::classof (const Stmt * T) inline static
Definition at line 1741 of file Stmt.h.
References clang::T.
Create()
CompoundStmt * CompoundStmt::Create (const ASTContext & C, ArrayRef< Stmt * > Stmts, FPOptionsOverride FPFeatures, SourceLocation LB, SourceLocation RB) static
Definition at line 383 of file Stmt.cpp.
References clang::FPOptionsOverride::requiresTrailingStorage().
Referenced by clang::Sema::ActOnCompoundStmt(), clang::Sema::DefineImplicitLambdaToBlockPointerConversion(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), and clang::Sema::MaybeCreateStmtWithCleanups().
CreateEmpty()
CompoundStmt * CompoundStmt::CreateEmpty (const ASTContext & C, unsigned NumStmts, bool HasFPFeatures) static
Definition at line 393 of file Stmt.cpp.
References clang::Stmt::CompoundStmtBits.
getBeginLoc()
SourceLocation clang::CompoundStmt::getBeginLoc () const inline
Definition at line 1735 of file Stmt.h.
Referenced by clang::CoroutineBodyStmt::getBeginLoc().
getEndLoc()
SourceLocation clang::CompoundStmt::getEndLoc () const inline
Definition at line 1736 of file Stmt.h.
Referenced by clang::SEHExceptStmt::getEndLoc(), clang::CoroutineBodyStmt::getEndLoc(), and clang::ObjCAtSynchronizedStmt::getEndLoc().
getLBracLoc()
SourceLocation clang::CompoundStmt::getLBracLoc () const inline
Definition at line 1738 of file Stmt.h.
Referenced by clang::ento::PathDiagnosticLocation::createBeginBrace().
getRBracLoc()
SourceLocation clang::CompoundStmt::getRBracLoc () const inline
Definition at line 1739 of file Stmt.h.
Referenced by clang::ento::PathDiagnosticLocation::createEndBrace().
getStmtExprResult() [1/2]
Stmt* clang::CompoundStmt::getStmtExprResult () inline
Definition at line 1723 of file Stmt.h.
References body(), and body_back().
Referenced by clang::Sema::BuildStmtExpr(), clang::computeDependence(), and getStmtExprResult().
getStmtExprResult() [2/2]
const Stmt* clang::CompoundStmt::getStmtExprResult () const inline
Definition at line 1731 of file Stmt.h.
References getStmtExprResult().
getStoredFPFeatures()
FPOptionsOverride clang::CompoundStmt::getStoredFPFeatures () const inline
Get FPOptionsOverride from trailing storage.
Definition at line 1656 of file Stmt.h.
References hasStoredFPFeatures().
hasStoredFPFeatures()
bool clang::CompoundStmt::hasStoredFPFeatures () const inline
Definition at line 1653 of file Stmt.h.
References clang::Stmt::CompoundStmtBits.
Referenced by getStoredFPFeatures().
size()
unsigned clang::CompoundStmt::size () const inline
Definition at line 1651 of file Stmt.h.
References clang::Stmt::CompoundStmtBits.
Referenced by body_back(), body_end(), and isIdenticalStmt().
Friends And Related Function Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 1607 of file Stmt.h.
The documentation for this class was generated from the following files:
include/clang/AST/Stmt.h
lib/AST/Stmt.cpp