clang: clang::analyze_os_log::OSLogBufferLayout Class Reference
clang::analyze_os_log::OSLogBufferLayout Class Reference
#include "clang/AST/OSLog.h"
Public Types
enum Flags { HasPrivateItems = 1, HasNonScalarItems = 1 << 1 }
Public Member Functions
CharUnits size () const
bool hasPrivateItems () const
bool hasNonScalarOrMask () const
unsigned char getSummaryByte () const
unsigned char getNumArgsByte () const
Public Attributes
SmallVector< OSLogBufferItem, 4 > Items
Detailed Description
Definition at line 111 of file OSLog.h.
Member Enumeration Documentation
Flags
enum clang::analyze_os_log::OSLogBufferLayout::Flags
Enumerator
HasPrivateItems
HasNonScalarItems
Definition at line 115 of file OSLog.h.
Member Function Documentation
getNumArgsByte()
unsigned char clang::analyze_os_log::OSLogBufferLayout::getNumArgsByte () const inline
Definition at line 148 of file OSLog.h.
References Items.
getSummaryByte()
unsigned char clang::analyze_os_log::OSLogBufferLayout::getSummaryByte () const inline
Definition at line 139 of file OSLog.h.
References HasNonScalarItems, hasNonScalarOrMask(), HasPrivateItems, and hasPrivateItems().
hasNonScalarOrMask()
bool clang::analyze_os_log::OSLogBufferLayout::hasNonScalarOrMask () const inline
Definition at line 132 of file OSLog.h.
References clang::analyze_os_log::OSLogBufferItem::getKind(), clang::analyze_os_log::OSLogBufferItem::getMaskType(), Items, and clang::analyze_os_log::OSLogBufferItem::ScalarKind.
Referenced by getSummaryByte().
hasPrivateItems()
bool clang::analyze_os_log::OSLogBufferLayout::hasPrivateItems () const inline
Definition at line 127 of file OSLog.h.
References clang::analyze_os_log::OSLogBufferItem::getIsPrivate(), and Items.
Referenced by getSummaryByte().
size()
CharUnits clang::analyze_os_log::OSLogBufferLayout::size () const inline
Definition at line 117 of file OSLog.h.
References clang::CharUnits::fromQuantity(), and Items.
Member Data Documentation
Items
SmallVector<OSLogBufferItem, 4> clang::analyze_os_log::OSLogBufferLayout::Items
Definition at line 113 of file OSLog.h.
Referenced by clang::CodeGen::CodeGenFunction::emitBuiltinOSLogFormat(), getNumArgsByte(), hasNonScalarOrMask(), hasPrivateItems(), and size().
The documentation for this class was generated from the following file:
include/clang/AST/OSLog.h