clang: clang::CodeGen::ConstantEmitter Class Reference
clang::CodeGen::ConstantEmitter Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/ConstantEmitter.h"
Public Member Functions
ConstantEmitter (CodeGenModule &CGM, CodeGenFunction *CGF=nullptr)
ConstantEmitter (CodeGenFunction &CGF)
Initialize this emission in the context of the given function.
ConstantEmitter (const ConstantEmitter &other)=delete
ConstantEmitter & operator= (const ConstantEmitter &other)=delete
~ConstantEmitter ()
bool isAbstract () const
Is the current emission context abstract?
bool isInConstantContext () const
void setInConstantContext (bool var)
llvm::Constant * tryEmitForInitializer (const VarDecl &D)
Try to emit the initiaizer of the given declaration as an abstract constant.
llvm::Constant * tryEmitForInitializer (const Expr *E, LangAS destAddrSpace, QualType destType)
llvm::Constant * emitForInitializer (const APValue &value, LangAS destAddrSpace, QualType destType)
void finalize (llvm::GlobalVariable *global)
llvm::Constant * tryEmitAbstractForInitializer (const VarDecl &D)
Try to emit the initializer of the given declaration as an abstract constant.
llvm::Constant * emitAbstract (const Expr *E, QualType T)
Emit the result of the given expression as an abstract constant, asserting that it succeeded.
llvm::Constant * emitAbstract (SourceLocation loc, const APValue &value, QualType T)
llvm::Constant * tryEmitAbstract (const Expr *E, QualType T)
Try to emit the result of the given expression as an abstract constant.
llvm::Constant * tryEmitAbstractForMemory (const Expr *E, QualType T)
llvm::Constant * tryEmitAbstract (const APValue &value, QualType T)
llvm::Constant * tryEmitAbstractForMemory (const APValue &value, QualType T)
llvm::Constant * tryEmitConstantExpr (const ConstantExpr *CE)
llvm::Constant * emitNullForMemory (QualType T)
llvm::Constant * emitForMemory (llvm::Constant *C, QualType T)
llvm::Constant * tryEmitPrivateForVarInit (const VarDecl &D)
llvm::Constant * tryEmitPrivate (const Expr *E, QualType T)
llvm::Constant * tryEmitPrivateForMemory (const Expr *E, QualType T)
llvm::Constant * tryEmitPrivate (const APValue &value, QualType T)
llvm::Constant * tryEmitPrivateForMemory (const APValue &value, QualType T)
llvm::GlobalValue * getCurrentAddrPrivate ()
Get the address of the current location.
void registerCurrentAddrPrivate (llvm::Constant *signal, llvm::GlobalValue *placeholder)
Register a 'signal' value with the emitter to inform it where to resolve a placeholder.
Static Public Member Functions
static llvm::Constant * emitNullForMemory (CodeGenModule &CGM, QualType T)
static llvm::Constant * emitForMemory (CodeGenModule &CGM, llvm::Constant *C, QualType T)
Public Attributes
CodeGenModule & CGM
CodeGenFunction *const CGF
Detailed Description
Definition at line 23 of file ConstantEmitter.h.
Constructor & Destructor Documentation
ConstantEmitter() [1/3]
clang::CodeGen::ConstantEmitter::ConstantEmitter (CodeGenModule & CGM, CodeGenFunction * CGF = nullptr) inline
Definition at line 51 of file ConstantEmitter.h.
ConstantEmitter() [2/3]
clang::CodeGen::ConstantEmitter::ConstantEmitter (CodeGenFunction & CGF) inline
Initialize this emission in the context of the given function.
Use this if the expression might contain contextual references like block addresses or PredefinedExprs.
Definition at line 57 of file ConstantEmitter.h.
ConstantEmitter() [3/3]
clang::CodeGen::ConstantEmitter::ConstantEmitter (const ConstantEmitter & other) delete
~ConstantEmitter()
ConstantEmitter::~ConstantEmitter ()
Definition at line 1669 of file CGExprConstant.cpp.
Member Function Documentation
emitAbstract() [1/2]
llvm::Constant * ConstantEmitter::emitAbstract (const Expr * E, QualType T)
Emit the result of the given expression as an abstract constant, asserting that it succeeded.
This is only safe to do when the expression is known to be a constant expression with either a fairly simple type or a known simple form.
Definition at line 1456 of file CGExprConstant.cpp.
References CGM, clang::CodeGen::CodeGenModule::EmitNullConstant(), clang::CodeGen::CodeGenModule::Error(), clang::Expr::getExprLoc(), and tryEmitPrivate().
Referenced by clang::CodeGen::CodeGenModule::createOpenCLIntToSamplerConversion(), clang::CodeGen::CodeGenModule::EmitAnnotationArgs(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::tryEmitAsConstant(), and tryEmitConstantExpr().
emitAbstract() [2/2]
llvm::Constant * ConstantEmitter::emitAbstract (SourceLocation loc, const APValue & value, QualType T)
Definition at line 1469 of file CGExprConstant.cpp.
References CGM, clang::CodeGen::CodeGenModule::EmitNullConstant(), clang::CodeGen::CodeGenModule::Error(), and tryEmitPrivate().
emitForInitializer()
llvm::Constant * ConstantEmitter::emitForInitializer (const APValue & value, LangAS destAddrSpace, QualType destType)
Definition at line 1494 of file CGExprConstant.cpp.
References tryEmitPrivateForMemory().
emitForMemory() [1/2]
llvm::Constant * ConstantEmitter::emitForMemory (CodeGenModule & CGM, llvm::Constant * C, QualType T) static
Definition at line 1746 of file CGExprConstant.cpp.
References CGM, clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), emitForMemory(), clang::Type::getAs(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::CodeGenModule::getTypes(), clang::ASTContext::getTypeSize(), clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::Type::isBitIntType().
emitForMemory() [2/2]
llvm::Constant* clang::CodeGen::ConstantEmitter::emitForMemory (llvm::Constant * C, QualType T) inline
Definition at line 121 of file ConstantEmitter.h.
References CGM, and clang::T.
Referenced by emitForMemory(), emitNullForMemory(), tryEmitAbstractForMemory(), tryEmitPrivateForMemory(), and tryEmitPrivateForVarInit().
emitNullForMemory() [1/2]
llvm::Constant * ConstantEmitter::emitNullForMemory (CodeGenModule & CGM, QualType T) static
Definition at line 2369 of file CGExprConstant.cpp.
References CGM, emitForMemory(), clang::CodeGen::CodeGenModule::EmitNullConstant(), and clang::T.
emitNullForMemory() [2/2]
llvm::Constant* clang::CodeGen::ConstantEmitter::emitNullForMemory (QualType T) inline
Definition at line 118 of file ConstantEmitter.h.
References CGM, and clang::T.
finalize()
void ConstantEmitter::finalize (llvm::GlobalVariable * global)
Definition at line 1653 of file CGExprConstant.cpp.
References CGM.
Referenced by clang::CodeGen::CodeGenFunction::AddInitializerToStaticVarDecl().
getCurrentAddrPrivate()
llvm::GlobalValue * ConstantEmitter::getCurrentAddrPrivate ()
Get the address of the current location.
This is a constant that will resolve, after finalization, to the address of the 'signal' value that is registered with the emitter later.
Definition at line 1503 of file CGExprConstant.cpp.
References CGM, clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getModule(), clang::ASTContext::getTargetAddressSpace(), and clang::CodeGen::CodeGenTypeCache::Int8Ty.
isAbstract()
bool clang::CodeGen::ConstantEmitter::isAbstract () const inline
Is the current emission context abstract?
Definition at line 66 of file ConstantEmitter.h.
isInConstantContext()
bool clang::CodeGen::ConstantEmitter::isInConstantContext () const inline
Definition at line 70 of file ConstantEmitter.h.
operator=()
ConstantEmitter& clang::CodeGen::ConstantEmitter::operator= (const ConstantEmitter & other) delete
registerCurrentAddrPrivate()
void ConstantEmitter::registerCurrentAddrPrivate (llvm::Constant * signal, llvm::GlobalValue * placeholder)
Register a 'signal' value with the emitter to inform it where to resolve a placeholder.
The signal value must be unique in the initializer; it might, for example, be the address of a global that refers to the current-address value in its own initializer.
Uses of the placeholder must be properly anchored before finalizing the emitter, e.g. by being installed as the initializer of a global variable. That is, it must be possible to replaceAllUsesWith the placeholder with the proper address of the signal.
Definition at line 1523 of file CGExprConstant.cpp.
setInConstantContext()
void clang::CodeGen::ConstantEmitter::setInConstantContext (bool var) inline
Definition at line 71 of file ConstantEmitter.h.
References clang::dataflow::var().
tryEmitAbstract() [1/2]
llvm::Constant * ConstantEmitter::tryEmitAbstract (const APValue & value, QualType T)
Definition at line 1438 of file CGExprConstant.cpp.
References tryEmitPrivate().
tryEmitAbstract() [2/2]
llvm::Constant * ConstantEmitter::tryEmitAbstract (const Expr * E, QualType T)
Try to emit the result of the given expression as an abstract constant.
Definition at line 1431 of file CGExprConstant.cpp.
References tryEmitPrivate().
Referenced by EmitCXXNewAllocSize(), clang::CodeGen::CodeGenFunction::EmitObjCBoxedExpr(), and tryEmitAbstractForMemory().
tryEmitAbstractForInitializer()
llvm::Constant * ConstantEmitter::tryEmitAbstractForInitializer (const VarDecl & D)
Try to emit the initializer of the given declaration as an abstract constant.
Definition at line 1424 of file CGExprConstant.cpp.
References tryEmitPrivateForVarInit().
Referenced by clang::CodeGen::CodeGenFunction::EmitAutoVarInit(), and tryCaptureAsConstant().
tryEmitAbstractForMemory() [1/2]
llvm::Constant * ConstantEmitter::tryEmitAbstractForMemory (const APValue & value, QualType T)
Definition at line 1725 of file CGExprConstant.cpp.
References CGM, emitForMemory(), getNonMemoryType(), and tryEmitAbstract().
tryEmitAbstractForMemory() [2/2]
llvm::Constant * ConstantEmitter::tryEmitAbstractForMemory (const Expr * E, QualType T)
Definition at line 1718 of file CGExprConstant.cpp.
References CGM, emitForMemory(), getNonMemoryType(), and tryEmitAbstract().
Referenced by tryEmitPrivate().
tryEmitConstantExpr()
llvm::Constant * ConstantEmitter::tryEmitConstantExpr (const ConstantExpr * CE)
Definition at line 1444 of file CGExprConstant.cpp.
References CGM, emitAbstract(), clang::ConstantExpr::getAPValueResult(), clang::ConstantExpr::getBeginLoc(), clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::getLValueReferenceType(), clang::Expr::getType(), clang::ConstantExpr::hasAPValueResult(), and clang::Expr::isGLValue().
tryEmitForInitializer() [1/2]
llvm::Constant * ConstantEmitter::tryEmitForInitializer (const Expr * E, LangAS destAddrSpace, QualType destType)
Definition at line 1487 of file CGExprConstant.cpp.
References tryEmitPrivateForMemory().
tryEmitForInitializer() [2/2]
llvm::Constant * ConstantEmitter::tryEmitForInitializer (const VarDecl & D)
Try to emit the initiaizer of the given declaration as an abstract constant.
If this succeeds, the emission must be finalized.
Definition at line 1482 of file CGExprConstant.cpp.
References clang::QualType::getAddressSpace(), clang::ValueDecl::getType(), and tryEmitPrivateForVarInit().
Referenced by clang::CodeGen::CodeGenFunction::AddInitializerToStaticVarDecl().
tryEmitPrivate() [1/2]
llvm::Constant * ConstantEmitter::tryEmitPrivate (const APValue & value, QualType T)
Definition at line 2093 of file CGExprConstant.cpp.
References clang::APValue::AddrLabelDiff, clang::APValue::Array, clang::Type::castAs(), CGM, Complex, clang::APValue::ComplexFloat, clang::APValue::ComplexInt, clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CGCXXABI::EmitMemberPointer(), clang::APValue::FixedPoint, clang::APValue::Float, clang::ASTContext::getAsArrayType(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::ArrayType::getElementType(), clang::VectorType::getElementType(), clang::APValue::getFloat(), clang::APValue::getInt(), clang::Value::getKind(), clang::ASTContext::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::ASTContext::getTargetInfo(), clang::Expr::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::APValue::Indeterminate, clang::APValue::Int, clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::APValue::isFloat(), clang::Type::isIncompleteArrayType(), clang::APValue::isIndeterminate(), clang::APValue::isInt(), clang::APValue::LValue, clang::APValue::MemberPointer, clang::APValue::None, clang::APValue::Struct, tryEmitAbstractForMemory(), tryEmitPrivate(), tryEmitPrivateForMemory(), clang::APValue::Union, clang::TargetInfo::useFP16ConversionIntrinsics(), and clang::APValue::Vector.
tryEmitPrivate() [2/2]
llvm::Constant * ConstantEmitter::tryEmitPrivate (const Expr * E, QualType T)
Definition at line 1780 of file CGExprConstant.cpp.
References CGM, clang::Expr::EvaluateAsLValue(), clang::Expr::EvaluateAsRValue(), clang::CodeGen::CodeGenModule::getContext(), clang::Type::isReferenceType(), and clang::Type::isVoidType().
Referenced by emitAbstract(), tryEmitAbstract(), tryEmitPrivate(), and tryEmitPrivateForMemory().
tryEmitPrivateForMemory() [1/2]
llvm::Constant * ConstantEmitter::tryEmitPrivateForMemory (const APValue & value, QualType T)
Definition at line 1739 of file CGExprConstant.cpp.
References CGM, emitForMemory(), getNonMemoryType(), and tryEmitPrivate().
tryEmitPrivateForMemory() [2/2]
llvm::Constant * ConstantEmitter::tryEmitPrivateForMemory (const Expr * E, QualType T)
Definition at line 1732 of file CGExprConstant.cpp.
References CGM, emitForMemory(), getNonMemoryType(), and tryEmitPrivate().
Referenced by emitForInitializer(), tryEmitForInitializer(), tryEmitPrivate(), and tryEmitPrivateForVarInit().
tryEmitPrivateForVarInit()
llvm::Constant * ConstantEmitter::tryEmitPrivateForVarInit (const VarDecl & D)
Definition at line 1683 of file CGExprConstant.cpp.
References CGM, emitForMemory(), clang::CodeGen::CodeGenModule::EmitNullConstant(), clang::VarDecl::evaluateValue(), clang::ASTContext::getBaseElementType(), clang::CodeGen::CodeGenModule::getContext(), clang::VarDecl::getInit(), getNonMemoryType(), clang::ValueDecl::getType(), clang::VarDecl::hasConstantInitialization(), clang::VarDecl::hasLocalStorage(), clang::CXXConstructorDecl::isDefaultConstructor(), clang::Type::isRecordType(), clang::Type::isReferenceType(), clang::FunctionDecl::isTrivial(), and tryEmitPrivateForMemory().
Referenced by tryEmitAbstractForInitializer(), and tryEmitForInitializer().
Member Data Documentation
CGF
CodeGenFunction* const clang::CodeGen::ConstantEmitter::CGF
Definition at line 26 of file ConstantEmitter.h.
CGM
CodeGenModule& clang::CodeGen::ConstantEmitter::CGM
Definition at line 25 of file ConstantEmitter.h.
Referenced by emitAbstract(), emitForMemory(), emitNullForMemory(), finalize(), getCurrentAddrPrivate(), tryEmitAbstractForMemory(), tryEmitConstantExpr(), tryEmitPrivate(), tryEmitPrivateForMemory(), and tryEmitPrivateForVarInit().
The documentation for this class was generated from the following files:
lib/CodeGen/ConstantEmitter.h
lib/CodeGen/CGExprConstant.cpp