clang: clang::ExtractAPIAction Class Reference
clang::ExtractAPIAction Class Reference
ExtractAPIAction sets up the output file and creates the ExtractAPIVisitor.
#include "clang/ExtractAPI/FrontendActions.h"
Public Member Functions
bool PrepareToExecuteAction (CompilerInstance &CI) override
Prepare to execute the action on the given CompilerInstance.
Public Member Functions inherited from clang::ASTFrontendAction
ASTFrontendAction ()
bool usesPreprocessorOnly () const override
Does this action only use the preprocessor?
Public Member Functions inherited from clang::FrontendAction
FrontendAction ()
virtual ~FrontendAction ()
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
virtual TranslationUnitKind getTranslationUnitKind ()
For AST-based actions, the kind of translation unit we're handling.
virtual bool hasPCHSupport () const
Does this action support use with PCH?
virtual bool hasASTFileSupport () const
Does this action support use with AST files?
virtual bool hasIRSupport () const
Does this action support use with IR files?
virtual bool hasCodeCompletionSupport () const
Does this action support use with code completion?
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
virtual void EndSourceFile ()
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Static Public Member Functions
static std::unique_ptr< llvm::raw_pwrite_stream > CreateOutputFile (CompilerInstance &CI, StringRef InFile)
static StringRef getInputBufferName ()
Protected Member Functions
std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile) override
Create the AST consumer object for this action, if supported.
Protected Member Functions inherited from clang::ASTFrontendAction
void ExecuteAction () override
Implement the ExecuteAction interface by running Sema on the already-initialized AST consumer.
Protected Member Functions inherited from clang::FrontendAction
virtual bool BeginInvocation (CompilerInstance &CI)
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
virtual bool BeginSourceFileAction (CompilerInstance &CI)
Callback at the start of processing a single input.
virtual void EndSourceFileAction ()
Callback at the end of processing a single input.
virtual bool shouldEraseOutputFiles ()
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Detailed Description
ExtractAPIAction sets up the output file and creates the ExtractAPIVisitor.
Definition at line 22 of file FrontendActions.h.
Member Function Documentation
CreateASTConsumer()
std::unique_ptr< ASTConsumer > ExtractAPIAction::CreateASTConsumer (CompilerInstance & CI, StringRef InFile) override protected virtual
Create the AST consumer object for this action, if supported.
This routine is called as part of BeginSourceFile(), which will fail if the AST consumer cannot be created. This will not be called if the action has indicated that it only uses the preprocessor.
Parameters
CI - The current compiler instance, provided as a convenience, see getCompilerInstance().
InFile - The current input file, provided as a convenience, see getCurrentFile().
Returns
The new AST consumer, or null on failure.
Implements clang::FrontendAction.
Definition at line 336 of file ExtractAPIConsumer.cpp.
References clang::CompilerInstance::getASTContext(), clang::CompilerInvocationValueBase::getFrontendOpts(), clang::CompilerInstance::getInvocation(), and clang::FrontendOptions::ProductName.
CreateOutputFile()
std::unique_ptr< raw_pwrite_stream > ExtractAPIAction::CreateOutputFile (CompilerInstance & CI, StringRef InFile) static
Definition at line 375 of file ExtractAPIConsumer.cpp.
References clang::CompilerInstance::createDefaultOutputFile().
getInputBufferName()
static StringRef clang::ExtractAPIAction::getInputBufferName () inline static
Definition at line 42 of file FrontendActions.h.
PrepareToExecuteAction()
bool ExtractAPIAction::PrepareToExecuteAction (CompilerInstance & CI) override virtual
Prepare to execute the action on the given CompilerInstance.
This is called before executing the action on any inputs. This generates a single header that includes all of CI's inputs and replaces CI's input list with it before actually executing the action.
Reimplemented from clang::FrontendAction.
Definition at line 345 of file ExtractAPIConsumer.cpp.
References clang::CompilerInstance::getFrontendOpts(), and clang::FrontendOptions::Inputs.
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/FrontendActions.h
lib/ExtractAPI/ExtractAPIConsumer.cpp