clang: clang::driver::JobList Class Reference
clang::driver::JobList Class Reference
JobList - A sequence of jobs to perform.
#include "clang/Driver/Job.h"
Public Types
using list_type = SmallVector< std::unique_ptr< Command >, 4 >
using size_type = list_type::size_type
using iterator = llvm::pointee_iterator< list_type::iterator >
using const_iterator = llvm::pointee_iterator< list_type::const_iterator >
Public Member Functions
void Print (llvm::raw_ostream &OS, const char *Terminator, bool Quote, CrashReportInfo *CrashInfo=nullptr) const
void addJob (std::unique_ptr< Command > J)
Add a job to the list (taking ownership).
void clear ()
Clear the job list.
list_type & getJobsForOverride ()
Return a mutable list of Jobs for llvm-foreach wrapping.
const list_type & getJobs () const
bool empty () const
size_type size () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Detailed Description
JobList - A sequence of jobs to perform.
Definition at line 307 of file Job.h.
Member Typedef Documentation
const_iterator
using clang::driver::JobList::const_iterator = llvm::pointee_iterator<list_type::const_iterator>
Definition at line 312 of file Job.h.
iterator
using clang::driver::JobList::iterator = llvm::pointee_iterator<list_type::iterator>
Definition at line 311 of file Job.h.
list_type
using clang::driver::JobList::list_type = SmallVector<std::unique_ptr<Command>, 4>
Definition at line 309 of file Job.h.
size_type
using clang::driver::JobList::size_type = list_type::size_type
Definition at line 310 of file Job.h.
Member Function Documentation
addJob()
void clang::driver::JobList::addJob (std::unique_ptr< Command > J) inline
Add a job to the list (taking ownership).
Definition at line 322 of file Job.h.
Referenced by clang::driver::Compilation::addCommand().
begin() [1/2]
iterator clang::driver::JobList::begin () inline
Definition at line 333 of file Job.h.
begin() [2/2]
const_iterator clang::driver::JobList::begin () const inline
Definition at line 334 of file Job.h.
clear()
void JobList::clear ()
Clear the job list.
Definition at line 472 of file Job.cpp.
Referenced by clang::driver::Compilation::initCompilationForDiagnostics().
empty()
bool clang::driver::JobList::empty () const inline
Definition at line 331 of file Job.h.
end() [1/2]
iterator clang::driver::JobList::end () inline
Definition at line 335 of file Job.h.
Referenced by clang::createInvocationFromCommandLine().
end() [2/2]
const_iterator clang::driver::JobList::end () const inline
Definition at line 336 of file Job.h.
getJobs()
const list_type& clang::driver::JobList::getJobs () const inline
Definition at line 329 of file Job.h.
Referenced by stripPositionalArgs().
getJobsForOverride()
list_type& clang::driver::JobList::getJobsForOverride () inline
Return a mutable list of Jobs for llvm-foreach wrapping.
Definition at line 328 of file Job.h.
Print()
void JobList::Print (llvm::raw_ostream & OS, const char * Terminator, bool Quote, CrashReportInfo * CrashInfo = nullptr) const
Definition at line 466 of file Job.cpp.
Referenced by clang::createInvocationFromCommandLine().
size()
size_type clang::driver::JobList::size () const inline
Definition at line 332 of file Job.h.
Referenced by clang::createInvocationFromCommandLine().
The documentation for this class was generated from the following files:
include/clang/Driver/Job.h
lib/Driver/Job.cpp