clang: clang::threadSafety::til::MatchComparator Class Reference
clang::threadSafety::til::MatchComparator Class Reference
#include "clang/Analysis/Analyses/ThreadSafetyTraverse.h"
Public Types
using CType = bool
Public Member Functions
CType trueResult ()
bool notTrue (CType ct)
bool compareIntegers (unsigned i, unsigned j)
bool compareStrings (StringRef s, StringRef r)
bool comparePointers (const void *P, const void *Q)
bool compare (const SExpr *E1, const SExpr *E2)
void enterScope (const Variable *V1, const Variable *V2)
void leaveScope ()
bool compareVariableRefs (const Variable *V1, const Variable *V2)
Public Member Functions inherited from clang::threadSafety::til::Comparator< MatchComparator >
bool compareByCase (const SExpr *E1, const SExpr *E2)
Static Public Member Functions
static bool compareExprs (const SExpr *E1, const SExpr *E2)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::Comparator< MatchComparator >
MatchComparator * self ()
Detailed Description
Definition at line 361 of file ThreadSafetyTraverse.h.
Member Typedef Documentation
CType
using clang::threadSafety::til::MatchComparator::CType = bool
Definition at line 366 of file ThreadSafetyTraverse.h.
Member Function Documentation
compare()
bool clang::threadSafety::til::MatchComparator::compare (const SExpr * E1, const SExpr * E2) inline
Definition at line 375 of file ThreadSafetyTraverse.h.
References clang::threadSafety::til::Comparator< MatchComparator >::compareByCase(), and clang::threadSafety::til::SExpr::opcode().
compareExprs()
static bool clang::threadSafety::til::MatchComparator::compareExprs (const SExpr * E1, const SExpr * E2) inline static
Definition at line 393 of file ThreadSafetyTraverse.h.
Referenced by clang::threadSafety::sx::matches().
compareIntegers()
bool clang::threadSafety::til::MatchComparator::compareIntegers (unsigned i, unsigned j) inline
Definition at line 371 of file ThreadSafetyTraverse.h.
comparePointers()
bool clang::threadSafety::til::MatchComparator::comparePointers (const void * P, const void * Q) inline
Definition at line 373 of file ThreadSafetyTraverse.h.
References P.
compareStrings()
bool clang::threadSafety::til::MatchComparator::compareStrings (StringRef s, StringRef r) inline
Definition at line 372 of file ThreadSafetyTraverse.h.
References s.
compareVariableRefs()
bool clang::threadSafety::til::MatchComparator::compareVariableRefs (const Variable * V1, const Variable * V2) inline
Definition at line 389 of file ThreadSafetyTraverse.h.
enterScope()
void clang::threadSafety::til::MatchComparator::enterScope (const Variable * V1, const Variable * V2) inline
Definition at line 386 of file ThreadSafetyTraverse.h.
leaveScope()
void clang::threadSafety::til::MatchComparator::leaveScope () inline
Definition at line 387 of file ThreadSafetyTraverse.h.
notTrue()
bool clang::threadSafety::til::MatchComparator::notTrue (CType ct) inline
Definition at line 369 of file ThreadSafetyTraverse.h.
trueResult()
CType clang::threadSafety::til::MatchComparator::trueResult () inline
Definition at line 368 of file ThreadSafetyTraverse.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTraverse.h