clang: clang::FunctionDecl Class Reference
clang::FunctionDecl Class Reference
Represents a function declaration or definition.
#include "clang/AST/Decl.h"
Classes
class DefaultedOrDeletedFunctionInfo
Stashed information about a defaulted/deleted function body.
Public Types
enum TemplatedKind {
TK_NonTemplate , TK_FunctionTemplate , TK_MemberSpecialization , TK_FunctionTemplateSpecialization ,
TK_DependentFunctionTemplateSpecialization , TK_DependentNonTemplate
}
The kind of templated function a FunctionDecl can be.
using redecl_range = redeclarable_base::redecl_range
using redecl_iterator = redeclarable_base::redecl_iterator
using param_iterator = MutableArrayRef< ParmVarDecl * >::iterator
using param_const_iterator = ArrayRef< ParmVarDecl * >::const_iterator
Public Types inherited from clang::NamedDecl
enum ExplicitVisibilityKind { VisibilityForType , VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned char {
Unowned , Visible , VisibleWhenImported , ReachableWhenImported ,
ModulePrivate
}
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using DeclID = uint32_t
An ID number that refers to a declaration in an AST file.
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range< attr_iterator >
using redecl_range = llvm::iterator_range< redecl_iterator >
Public Types inherited from clang::DeclContext
using decl_range = llvm::iterator_range< decl_iterator >
using lookup_result = DeclContextLookupResult
using lookup_iterator = lookup_result::iterator
using lookups_range = llvm::iterator_range< all_lookups_iterator >
using udir_iterator_base = llvm::iterator_adaptor_base< udir_iterator, lookup_iterator, typename lookup_iterator::iterator_category, UsingDirectiveDecl * >
using udir_range = llvm::iterator_range< udir_iterator >
using ddiag_range = llvm::iterator_range< DeclContext::ddiag_iterator >
Public Types inherited from clang::Redeclarable< FunctionDecl >
using redecl_range = llvm::iterator_range< redecl_iterator >
Public Member Functions
DeclarationNameInfo getNameInfo () const
void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const override
Appends a human-readable name for this declaration into the given stream.
void setRangeEnd (SourceLocation E)
SourceLocation getEllipsisLoc () const
Returns the location of the ellipsis of a variadic function.
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
bool hasBody (const FunctionDecl *&Definition) const
Returns true if the function has a body.
bool hasBody () const override
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
bool hasTrivialBody () const
Returns whether the function has a trivial body that does not require any specific codegen.
bool isDefined (const FunctionDecl *&Definition, bool CheckForPendingFriendDefinition=false) const
Returns true if the function has a definition that does not need to be instantiated.
bool isDefined () const
FunctionDecl * getDefinition ()
Get the definition for this declaration.
const FunctionDecl * getDefinition () const
Stmt * getBody (const FunctionDecl *&Definition) const
Retrieve the body (definition) of the function.
Stmt * getBody () const override
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
bool isThisDeclarationADefinition () const
Returns whether this specific declaration of the function is also a definition that does not contain uninstantiated body.
bool isThisDeclarationInstantiatedFromAFriendDefinition () const
Determine whether this specific declaration of the function is a friend declaration that was instantiated from a function definition.
bool doesThisDeclarationHaveABody () const
Returns whether this specific declaration of the function has a body.
void setBody (Stmt *B)
void setLazyBody (uint64_t Offset)
void setDefaultedOrDeletedInfo (DefaultedOrDeletedFunctionInfo *Info)
DefaultedOrDeletedFunctionInfo * getDefalutedOrDeletedInfo () const
bool isVariadic () const
Whether this function is variadic.
bool isVirtualAsWritten () const
Whether this function is marked as virtual explicitly.
void setVirtualAsWritten (bool V)
State that this function is marked as virtual explicitly.
bool isPureVirtual () const
Whether this virtual function is pure, i.e.
void setIsPureVirtual (bool P=true)
bool isLateTemplateParsed () const
Whether this templated function will be late parsed.
void setLateTemplateParsed (bool ILT=true)
State that this templated function will be late parsed.
bool isTrivial () const
Whether this function is "trivial" in some specialized C++ senses.
void setTrivial (bool IT)
bool isTrivialForCall () const
void setTrivialForCall (bool IT)
bool isDefaulted () const
Whether this function is defaulted.
void setDefaulted (bool D=true)
bool isExplicitlyDefaulted () const
Whether this function is explicitly defaulted.
void setExplicitlyDefaulted (bool ED=true)
State that this function is explicitly defaulted.
SourceLocation getDefaultLoc () const
void setDefaultLoc (SourceLocation NewLoc)
bool isUserProvided () const
True if this method is user-declared and was not deleted or defaulted on its first declaration.
bool isIneligibleOrNotSelected () const
void setIneligibleOrNotSelected (bool II)
bool hasImplicitReturnZero () const
Whether falling off this function implicitly returns null/zero.
void setHasImplicitReturnZero (bool IRZ)
State that falling off this function implicitly returns null/zero.
bool hasPrototype () const
Whether this function has a prototype, either because one was explicitly written or because it was "inherited" by merging a declaration without a prototype with a declaration that has a prototype.
bool hasWrittenPrototype () const
Whether this function has a written prototype.
void setHasWrittenPrototype (bool P=true)
State that this function has a written prototype.
bool hasInheritedPrototype () const
Whether this function inherited its prototype from a previous declaration.
void setHasInheritedPrototype (bool P=true)
State that this function inherited its prototype from a previous declaration.
bool isConstexpr () const
Whether this is a (C++11) constexpr function or constexpr constructor.
void setConstexprKind (ConstexprSpecKind CSK)
ConstexprSpecKind getConstexprKind () const
bool isConstexprSpecified () const
bool isConsteval () const
void setBodyContainsImmediateEscalatingExpressions (bool Set)
bool BodyContainsImmediateEscalatingExpressions () const
bool isImmediateEscalating () const
bool isImmediateFunction () const
bool instantiationIsPending () const
Whether the instantiation of this function is pending.
void setInstantiationIsPending (bool IC)
State that the instantiation of this function is pending.
bool usesSEHTry () const
Indicates the function uses __try.
void setUsesSEHTry (bool UST)
bool isDeleted () const
Whether this function has been deleted.
bool isDeletedAsWritten () const
void setDeletedAsWritten (bool D=true, StringLiteral *Message=nullptr)
bool isMain () const
Determines whether this function is "main", which is the entry point into an executable program.
bool isMSVCRTEntryPoint () const
Determines whether this function is a MSVCRT user defined entry point.
bool isReservedGlobalPlacementOperator () const
Determines whether this operator new or delete is one of the reserved global placement operators: void *operator new(size_t, void *); void *operator new[](size_t, void *); void operator delete(void *, void *); void operator delete[](void *, void *); These functions have special behavior under [new.delete.placement]: These functions are reserved, a C++ program may not define functions that displace the versions in the Standard C++ library.
bool isReplaceableGlobalAllocationFunction (std::optional< unsigned > *AlignmentParam=nullptr, bool *IsNothrow=nullptr) const
Determines whether this function is one of the replaceable global allocation functions: void *operator new(size_t); void *operator new(size_t, const std::nothrow_t &) noexcept; void *operator new[](size_t); void *operator new[](size_t, const std::nothrow_t &) noexcept; void operator delete(void *) noexcept; void operator delete(void *, std::size_t) noexcept; [C++1y] void operator delete(void *, const std::nothrow_t &) noexcept; void operator delete[](void *) noexcept; void operator delete[](void *, std::size_t) noexcept; [C++1y] void operator delete[](void *, const std::nothrow_t &) noexcept; These functions have special behavior under C++1y [expr.new]: An implementation is allowed to omit a call to a replaceable global allocation function.
bool isInlineBuiltinDeclaration () const
Determine if this function provides an inline implementation of a builtin.
bool isDestroyingOperatorDelete () const
Determine whether this is a destroying operator delete.
LanguageLinkage getLanguageLinkage () const
Compute the language linkage.
bool isExternC () const
Determines whether this function is a function with external, C linkage.
bool isInExternCContext () const
Determines whether this function's context is, or is nested within, a C++ extern "C" linkage spec.
bool isInExternCXXContext () const
Determines whether this function's context is, or is nested within, a C++ extern "C++" linkage spec.
bool isGlobal () const
Determines whether this is a global function.
bool isNoReturn () const
Determines whether this function is known to be 'noreturn', through an attribute on its declaration or its type.
bool hasSkippedBody () const
True if the function was a definition but its body was skipped.
void setHasSkippedBody (bool Skipped=true)
bool willHaveBody () const
True if this function will eventually have a body, once it's fully parsed.
void setWillHaveBody (bool V=true)
bool isMultiVersion () const
True if this function is considered a multiversioned function.
void setIsMultiVersion (bool V=true)
Sets the multiversion state for this declaration and all of its redeclarations.
void setFriendConstraintRefersToEnclosingTemplate (bool V=true)
bool FriendConstraintRefersToEnclosingTemplate () const
bool isMemberLikeConstrainedFriend () const
Determine whether a function is a friend function that cannot be redeclared outside of its class, per C++ [temp.friend]p9.
MultiVersionKind getMultiVersionKind () const
Gets the kind of multiversioning attribute this declaration has.
bool isCPUDispatchMultiVersion () const
True if this function is a multiversioned dispatch function as a part of the cpu_specific/cpu_dispatch functionality.
bool isCPUSpecificMultiVersion () const
True if this function is a multiversioned processor specific function as a part of the cpu_specific/cpu_dispatch functionality.
bool isTargetMultiVersion () const
True if this function is a multiversioned dispatch function as a part of the target functionality.
bool isTargetMultiVersionDefault () const
True if this function is the default version of a multiversioned dispatch function as a part of the target functionality.
bool isTargetClonesMultiVersion () const
True if this function is a multiversioned dispatch function as a part of the target-clones functionality.
bool isTargetVersionMultiVersion () const
True if this function is a multiversioned dispatch function as a part of the target-version functionality.
void getAssociatedConstraints (SmallVectorImpl< const Expr * > &AC) const
Get the associated-constraints of this function declaration.
StringLiteral * getDeletedMessage () const
Get the message that indicates why this function was deleted.
void setPreviousDeclaration (FunctionDecl *PrevDecl)
FunctionDecl * getCanonicalDecl () override
Retrieves the "canonical" declaration of the given declaration.
const FunctionDecl * getCanonicalDecl () const
unsigned getBuiltinID (bool ConsiderWrapperFunctions=false) const
Returns a value indicating whether this function corresponds to a builtin function.
ArrayRef< ParmVarDecl * > parameters () const
MutableArrayRef< ParmVarDecl * > parameters ()
bool param_empty () const
param_iterator param_begin ()
param_iterator param_end ()
param_const_iterator param_begin () const
param_const_iterator param_end () const
size_t param_size () const
unsigned getNumParams () const
Return the number of parameters this function must have based on its FunctionType.
const ParmVarDecl * getParamDecl (unsigned i) const
ParmVarDecl * getParamDecl (unsigned i)
void setParams (ArrayRef< ParmVarDecl * > NewParamInfo)
unsigned getMinRequiredArguments () const
Returns the minimum number of arguments needed to call this function.
unsigned getMinRequiredExplicitArguments () const
Returns the minimum number of non-object arguments needed to call this function.
bool hasCXXExplicitFunctionObjectParameter () const
unsigned getNumNonObjectParams () const
const ParmVarDecl * getNonObjectParameter (unsigned I) const
ParmVarDecl * getNonObjectParameter (unsigned I)
bool hasOneParamOrDefaultArgs () const
Determine whether this function has a single parameter, or multiple parameters where all but the first have default arguments.
FunctionTypeLoc getFunctionTypeLoc () const
Find the source location information for how the type of this function was written.
QualType getReturnType () const
SourceRange getReturnTypeSourceRange () const
Attempt to compute an informative source range covering the function return type.
SourceRange getParametersSourceRange () const
Attempt to compute an informative source range covering the function parameters, including the ellipsis of a variadic function.
QualType getDeclaredReturnType () const
Get the declared return type, which may differ from the actual return type if the return type is deduced.
ExceptionSpecificationType getExceptionSpecType () const
Gets the ExceptionSpecificationType as declared.
SourceRange getExceptionSpecSourceRange () const
Attempt to compute an informative source range covering the function exception specification, if any.
QualType getCallResultType () const
Determine the type of an expression that calls this function.
StorageClass getStorageClass () const
Returns the storage class as written in the source.
void setStorageClass (StorageClass SClass)
Sets the storage class as written in the source.
bool isInlineSpecified () const
Determine whether the "inline" keyword was specified for this function.
void setInlineSpecified (bool I)
Set whether the "inline" keyword was specified for this function.
bool UsesFPIntrin () const
Determine whether the function was declared in source context that requires constrained FP intrinsics.
void setUsesFPIntrin (bool I)
Set whether the function was declared in source context that requires constrained FP intrinsics.
void setImplicitlyInline (bool I=true)
Flag that this function is implicitly inline.
bool isInlined () const
Determine whether this function should be inlined, because it is either marked "inline" or "constexpr" or is a member function of a class that was defined in the class body.
bool isInlineDefinitionExternallyVisible () const
For an inline function definition in C, or for a gnu_inline function in C++, determine whether the definition will be externally visible.
bool isMSExternInline () const
The combination of the extern and inline keywords under MSVC forces the function to be required.
bool doesDeclarationForceExternallyVisibleDefinition () const
For a function declaration in C or C++, determine whether this declaration causes the definition to be externally visible.
bool isStatic () const
bool isOverloadedOperator () const
Whether this function declaration represents an C++ overloaded operator, e.g., "operator+".
OverloadedOperatorKind getOverloadedOperator () const
getOverloadedOperator - Which C++ overloaded operator this function represents, if any.
const IdentifierInfo * getLiteralIdentifier () const
getLiteralIdentifier - The literal suffix identifier this function represents, if any.
FunctionDecl * getInstantiatedFromMemberFunction () const
If this function is an instantiation of a member function of a class template specialization, retrieves the function from which it was instantiated.
TemplatedKind getTemplatedKind () const
What kind of templated function this is.
MemberSpecializationInfo * getMemberSpecializationInfo () const
If this function is an instantiation of a member function of a class template specialization, retrieves the member specialization information.
void setInstantiationOfMemberFunction (FunctionDecl *FD, TemplateSpecializationKind TSK)
Specify that this record is an instantiation of the member function FD.
void setInstantiatedFromDecl (FunctionDecl *FD)
Specify that this function declaration was instantiated from a FunctionDecl FD.
FunctionDecl * getInstantiatedFromDecl () const
FunctionTemplateDecl * getDescribedFunctionTemplate () const
Retrieves the function template that is described by this function declaration.
void setDescribedFunctionTemplate (FunctionTemplateDecl *Template)
bool isFunctionTemplateSpecialization () const
Determine whether this function is a function template specialization.
FunctionTemplateSpecializationInfo * getTemplateSpecializationInfo () const
If this function is actually a function template specialization, retrieve information about this function template specialization.
bool isImplicitlyInstantiable () const
Determines whether this function is a function template specialization or a member of a class template specialization that can be implicitly instantiated.
bool isTemplateInstantiation () const
Determines if the given function was instantiated from a function template.
FunctionDecl * getTemplateInstantiationPattern (bool ForDefinition=true) const
Retrieve the function declaration from which this function could be instantiated, if it is an instantiation (rather than a non-template or a specialization, for example).
FunctionTemplateDecl * getPrimaryTemplate () const
Retrieve the primary template that this function template specialization either specializes or was instantiated from.
const TemplateArgumentList * getTemplateSpecializationArgs () const
Retrieve the template arguments used to produce this function template specialization from the primary template.
const ASTTemplateArgumentListInfo * getTemplateSpecializationArgsAsWritten () const
Retrieve the template argument list as written in the sources, if any.
void setFunctionTemplateSpecialization (FunctionTemplateDecl *Template, const TemplateArgumentList *TemplateArgs, void *InsertPos, TemplateSpecializationKind TSK=TSK_ImplicitInstantiation, const TemplateArgumentListInfo *TemplateArgsAsWritten=nullptr, SourceLocation PointOfInstantiation=SourceLocation())
Specify that this function declaration is actually a function template specialization.
void setDependentTemplateSpecialization (ASTContext &Context, const UnresolvedSetImpl &Templates, const TemplateArgumentListInfo *TemplateArgs)
Specifies that this function declaration is actually a dependent function template specialization.
DependentFunctionTemplateSpecializationInfo * getDependentSpecializationInfo () const
TemplateSpecializationKind getTemplateSpecializationKind () const
Determine what kind of template instantiation this function represents.
TemplateSpecializationKind getTemplateSpecializationKindForInstantiation () const
Determine the kind of template specialization this function represents for the purpose of template instantiation.
void setTemplateSpecializationKind (TemplateSpecializationKind TSK, SourceLocation PointOfInstantiation=SourceLocation())
Determine what kind of template instantiation this function represents.
SourceLocation getPointOfInstantiation () const
Retrieve the (first) point of instantiation of a function template specialization or a member of a class template specialization.
bool isOutOfLine () const override
Determine whether this is or was instantiated from an out-of-line definition of a member function.
unsigned getMemoryFunctionKind () const
Identify a memory copying or setting function.
unsigned getODRHash ()
Returns ODRHash of the function.
unsigned getODRHash () const
Returns cached ODRHash of the function.
Public Member Functions inherited from clang::DeclaratorDecl
TypeSourceInfo * getTypeSourceInfo () const
void setTypeSourceInfo (TypeSourceInfo *TI)
SourceLocation getInnerLocStart () const
Return start of source range ignoring outer template declarations.
void setInnerLocStart (SourceLocation L)
SourceLocation getOuterLocStart () const
Return start of source range taking into account any outer template declarations.
SourceLocation getBeginLoc () const LLVM_READONLY
NestedNameSpecifier * getQualifier () const
Retrieve the nested-name-specifier that qualifies the name of this declaration, if it was present in the source.
NestedNameSpecifierLoc getQualifierLoc () const
Retrieve the nested-name-specifier (with source-location information) that qualifies the name of this declaration, if it was present in the source.
void setQualifierInfo (NestedNameSpecifierLoc QualifierLoc)
Expr * getTrailingRequiresClause ()
Get the constraint-expression introduced by the trailing requires-clause in the function/member declaration, or null if no requires-clause was provided.
const Expr * getTrailingRequiresClause () const
void setTrailingRequiresClause (Expr *TrailingRequiresClause)
unsigned getNumTemplateParameterLists () const
TemplateParameterList * getTemplateParameterList (unsigned index) const
void setTemplateParameterListsInfo (ASTContext &Context, ArrayRef< TemplateParameterList * > TPLists)
SourceLocation getTypeSpecStartLoc () const
SourceLocation getTypeSpecEndLoc () const
Public Member Functions inherited from clang::ValueDecl
QualType getType () const
void setType (QualType newType)
bool isWeak () const
Determine whether this symbol is weakly-imported, or declared with the weak or weak-ref attr.
bool isInitCapture () const
Whether this variable is the implicit variable for a lambda init-capture.
VarDecl * getPotentiallyDecomposedVarDecl ()
const VarDecl * getPotentiallyDecomposedVarDecl () const
Public Member Functions inherited from clang::NamedDecl
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
virtual void printName (raw_ostream &OS, const PrintingPolicy &Policy) const
Pretty-print the unqualified name of this declaration.
void printName (raw_ostream &OS) const
Calls printName() with the ASTContext printing policy from the decl.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy, bool WithGlobalNsPrefix=false) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy, bool WithGlobalNsPrefix=false) const
std::string getQualifiedNameAsString (bool WithGlobalNsPrefix=false) const
bool declarationReplaces (const NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
ReservedIdentifierStatus isReserved (const LangOptions &LangOpts) const
Determine if the declaration obeys the reserved identifier rules of the given language.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
std::optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
bool isPlaceholderVar (const LangOptions &LangOpts) const
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
DeclContext * getNonTransparentDeclContext ()
Return the non transparent context.
const DeclContext * getNonTransparentDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
bool isFileContextDecl () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename... Ts>
void dropAttrs ()
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool isInExportDeclContext () const
Whether this declaration was exported in a lexical context.
bool isInvisibleOutsideTheOwningModule () const
bool isInAnotherModuleUnit () const
Whether this declaration comes from another module unit.
bool isFromExplicitGlobalModule () const
Whether this declaration comes from explicit global module.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
DeclID getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
bool isReachable () const
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod (bool LexicalParent=false) const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod (bool LexicalParent=false)
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl () const
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
void clearIdentifierNamespace ()
Clears the namespace of this declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
bool isFunctionPointerType () const
Public Member Functions inherited from clang::DeclContext
~DeclContext ()
bool hasValidDeclKind () const
Decl::Kind getDeclKind () const
const char * getDeclKindName () const
DeclContext * getParent ()
getParent - Returns the containing DeclContext.
const DeclContext * getParent () const
DeclContext * getLexicalParent ()
getLexicalParent - Returns the containing lexical DeclContext.
const DeclContext * getLexicalParent () const
DeclContext * getLookupParent ()
Find the parent context of this context that will be used for unqualified name lookup.
const DeclContext * getLookupParent () const
ASTContext & getParentASTContext () const
bool isClosure () const
const BlockDecl * getInnermostBlockDecl () const
Return this DeclContext if it is a BlockDecl.
bool isObjCContainer () const
bool isFunctionOrMethod () const
bool isLookupContext () const
Test whether the context supports looking up names.
bool isFileContext () const
bool isTranslationUnit () const
bool isRecord () const
bool isNamespace () const
bool isStdNamespace () const
bool isInlineNamespace () const
bool isDependentContext () const
Determines whether this context is dependent on a template parameter.
bool isTransparentContext () const
isTransparentContext - Determines whether this context is a "transparent" context, meaning that the members declared in this context are semantically declared in the nearest enclosing non-transparent (opaque) context but are lexically declared in this context.
bool isExternCContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C linkage.
const LinkageSpecDecl * getExternCContext () const
Retrieve the nearest enclosing C linkage specification context.
bool isExternCXXContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C++ linkage.
bool Equals (const DeclContext *DC) const
Determine whether this declaration context is equivalent to the declaration context DC.
bool Encloses (const DeclContext *DC) const
Determine whether this declaration context encloses the declaration context DC.
Decl * getNonClosureAncestor ()
Find the nearest non-closure ancestor of this context, i.e.
const Decl * getNonClosureAncestor () const
DeclContext * getNonTransparentContext ()
const DeclContext * getNonTransparentContext () const
DeclContext * getPrimaryContext ()
getPrimaryContext - There may be many different declarations of the same entity (including forward declarations of classes, multiple definitions of namespaces, etc.), each with a different set of declarations.
const DeclContext * getPrimaryContext () const
DeclContext * getRedeclContext ()
getRedeclContext - Retrieve the context in which an entity conflicts with other entities of the same name, or where it is a redeclaration if the two entities are compatible.
const DeclContext * getRedeclContext () const
DeclContext * getEnclosingNamespaceContext ()
Retrieve the nearest enclosing namespace context.
const DeclContext * getEnclosingNamespaceContext () const
RecordDecl * getOuterLexicalRecordContext ()
Retrieve the outermost lexically enclosing record context.
const RecordDecl * getOuterLexicalRecordContext () const
bool InEnclosingNamespaceSetOf (const DeclContext *NS) const
Test if this context is part of the enclosing namespace set of the context NS, as defined in C++0x [namespace.def]p9.
void collectAllContexts (SmallVectorImpl< DeclContext * > &Contexts)
Collects all of the declaration contexts that are semantically connected to this declaration context.
decl_range decls () const
decls_begin/decls_end - Iterate over the declarations stored in this context.
decl_iterator decls_begin () const
decl_iterator decls_end () const
bool decls_empty () const
decl_range noload_decls () const
noload_decls_begin/end - Iterate over the declarations stored in this context that are currently loaded; don't attempt to retrieve anything from an external source.
decl_iterator noload_decls_begin () const
decl_iterator noload_decls_end () const
void addDecl (Decl *D)
Add the declaration D into this context.
void addDeclInternal (Decl *D)
Add the declaration D into this context, but suppress searches for external declarations with the same name.
void addHiddenDecl (Decl *D)
Add the declaration D to this context without modifying any lookup tables.
void removeDecl (Decl *D)
Removes a declaration from this context.
bool containsDecl (Decl *D) const
Checks whether a declaration is in this context.
bool containsDeclAndLoad (Decl *D) const
Checks whether a declaration is in this context.
lookup_result lookup (DeclarationName Name) const
lookup - Find the declarations (if any) with the given Name in this context.
lookup_result noload_lookup (DeclarationName Name)
Find the declarations with the given name that are visible within this context; don't attempt to retrieve anything from an external source.
void localUncachedLookup (DeclarationName Name, SmallVectorImpl< NamedDecl * > &Results)
A simplistic name lookup mechanism that performs name lookup into this declaration context without consulting the external source.
void makeDeclVisibleInContext (NamedDecl *D)
Makes a declaration visible within this context.
lookups_range lookups () const
lookups_range noload_lookups (bool PreserveInternalState) const
all_lookups_iterator lookups_begin () const
Iterators over all possible lookups within this context.
all_lookups_iterator lookups_end () const
all_lookups_iterator noload_lookups_begin () const
Iterators over all possible lookups within this context that are currently loaded; don't attempt to retrieve anything from an external source.
all_lookups_iterator noload_lookups_end () const
udir_range using_directives () const
Returns iterator range [First, Last) of UsingDirectiveDecls stored within this context.
ddiag_range ddiags () const
void setMustBuildLookupTable ()
Mark that there are external lexical declarations that we need to include in our lookup table (and that are not available as external visible lookups).
StoredDeclsMap * getLookupPtr () const
Retrieve the internal representation of the lookup structure.
StoredDeclsMap * buildLookup ()
Ensure the lookup structure is fully-built and return it.
bool hasExternalLexicalStorage () const
Whether this DeclContext has external storage containing additional declarations that are lexically in this context.
void setHasExternalLexicalStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations lexically in this context.
bool hasExternalVisibleStorage () const
Whether this DeclContext has external storage containing additional declarations that are visible in this context.
void setHasExternalVisibleStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations visible in this context.
bool isDeclInLexicalTraversal (const Decl *D) const
Determine whether the given declaration is stored in the list of declarations lexically within this context.
void setUseQualifiedLookup (bool use=true) const
bool shouldUseQualifiedLookup () const
void dumpAsDecl () const
void dumpAsDecl (const ASTContext *Ctx) const
void dumpDeclContext () const
void dumpLookups () const
void dumpLookups (llvm::raw_ostream &OS, bool DumpDecls=false, bool Deserialize=false) const
Public Member Functions inherited from clang::Redeclarable< FunctionDecl >
Redeclarable (const ASTContext &Ctx)
FunctionDecl * getPreviousDecl ()
Return the previous declaration of this declaration or NULL if this is the first declaration.
const FunctionDecl * getPreviousDecl () const
FunctionDecl * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const FunctionDecl * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
FunctionDecl * getMostRecentDecl ()
Returns the most recent (re)declaration of this declaration.
const FunctionDecl * getMostRecentDecl () const
Returns the most recent (re)declaration of this declaration.
void setPreviousDecl (FunctionDecl *PrevDecl)
Set the previous declaration.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Static Public Member Functions
static FunctionDecl * Create (ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation NLoc, DeclarationName N, QualType T, TypeSourceInfo *TInfo, StorageClass SC, bool UsesFPIntrin=false, bool isInlineSpecified=false, bool hasWrittenPrototype=true, ConstexprSpecKind ConstexprKind=ConstexprSpecKind::Unspecified, Expr *TrailingRequiresClause=nullptr)
static FunctionDecl * Create (ASTContext &C, DeclContext *DC, SourceLocation StartLoc, const DeclarationNameInfo &NameInfo, QualType T, TypeSourceInfo *TInfo, StorageClass SC, bool UsesFPIntrin, bool isInlineSpecified, bool hasWrittenPrototype, ConstexprSpecKind ConstexprKind, Expr *TrailingRequiresClause)
static FunctionDecl * CreateDeserialized (ASTContext &C, DeclID ID)
static bool classof (const Decl *D)
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const FunctionDecl *D)
static FunctionDecl * castFromDeclContext (const DeclContext *DC)
Static Public Member Functions inherited from clang::DeclaratorDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::ValueDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::NamedDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static bool isFlexibleArrayMemberLike (ASTContext &Context, const Decl *D, QualType Ty, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel, bool IgnoreTemplateOrMacroSubstitution)
Whether it resembles a flexible array member.
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Static Public Member Functions inherited from clang::DeclContext
static bool classof (const Decl *D)
static bool classof (const DeclContext *D)
Protected Types
using redeclarable_base = Redeclarable< FunctionDecl >
Protected Member Functions
FunctionDecl (Kind DK, ASTContext &C, DeclContext *DC, SourceLocation StartLoc, const DeclarationNameInfo &NameInfo, QualType T, TypeSourceInfo *TInfo, StorageClass S, bool UsesFPIntrin, bool isInlineSpecified, ConstexprSpecKind ConstexprKind, Expr *TrailingRequiresClause=nullptr)
FunctionDecl * getNextRedeclarationImpl () override
Returns the next redeclaration or itself if this is the only decl.
FunctionDecl * getPreviousDeclImpl () override
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
FunctionDecl * getMostRecentDeclImpl () override
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
Protected Member Functions inherited from clang::DeclaratorDecl
DeclaratorDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N, QualType T, TypeSourceInfo *TInfo, SourceLocation StartL)
Protected Member Functions inherited from clang::ValueDecl
ValueDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N, QualType T)
Protected Member Functions inherited from clang::NamedDecl
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclID ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
ASTMutationListener * getASTMutationListener () const
Protected Member Functions inherited from clang::DeclContext
DeclContext (Decl::Kind K)
Protected Member Functions inherited from clang::Redeclarable< FunctionDecl >
FunctionDecl * getNextRedeclaration () const
Friends
class ASTDeclReader
class ASTDeclWriter
Additional Inherited Members
Static Protected Member Functions inherited from clang::DeclContext
static std::pair< Decl *, Decl * > BuildDeclChain (ArrayRef< Decl * > Decls, bool FieldsAlreadyLoaded)
Build up a chain of declarations.
Static Protected Member Functions inherited from clang::Redeclarable< FunctionDecl >
static DeclLink PreviousDeclLink (FunctionDecl *D)
static DeclLink LatestDeclLink (const ASTContext &Ctx)
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 3, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Protected Attributes inherited from clang::DeclContext
union {
DeclContextBitfields DeclContextBits
TagDeclBitfields TagDeclBits
EnumDeclBitfields EnumDeclBits
RecordDeclBitfields RecordDeclBits
OMPDeclareReductionDeclBitfields OMPDeclareReductionDeclBits
FunctionDeclBitfields FunctionDeclBits
CXXConstructorDeclBitfields CXXConstructorDeclBits
ObjCMethodDeclBitfields ObjCMethodDeclBits
ObjCContainerDeclBitfields ObjCContainerDeclBits
LinkageSpecDeclBitfields LinkageSpecDeclBits
BlockDeclBitfields BlockDeclBits
};
This anonymous union stores the bits belonging to DeclContext and classes deriving from it.
Decl * FirstDecl = nullptr
FirstDecl - The first declaration stored within this declaration context.
Decl * LastDecl = nullptr
LastDecl - The last declaration stored within this declaration context.
Protected Attributes inherited from clang::Redeclarable< FunctionDecl >
DeclLink RedeclLink
Points to the next redeclaration in the chain.
FunctionDecl * First
Detailed Description
Represents a function declaration or definition.
Since a given function can be declared several times in a program, there may be several FunctionDecls that correspond to that function. Only one of those FunctionDecls will be found when traversing the list of declarations in the context of the FunctionDecl (e.g., the translation unit); this FunctionDecl contains all of the information known about the function. Other, previous declarations of the function are available via the getPreviousDecl() chain.
Definition at line 1970 of file Decl.h.
Member Typedef Documentation
param_const_iterator
using clang::FunctionDecl::param_const_iterator = ArrayRef<ParmVarDecl *>::const_iterator
Definition at line 2694 of file Decl.h.
param_iterator
using clang::FunctionDecl::param_iterator = MutableArrayRef<ParmVarDecl *>::iterator
Definition at line 2693 of file Decl.h.
redecl_iterator
using clang::FunctionDecl::redecl_iterator = redeclarable_base::redecl_iterator
Definition at line 2152 of file Decl.h.
redecl_range
using clang::FunctionDecl::redecl_range = redeclarable_base::redecl_range
Definition at line 2151 of file Decl.h.
redeclarable_base
using clang::FunctionDecl::redeclarable_base = Redeclarable<FunctionDecl> protected
Definition at line 2133 of file Decl.h.
Member Enumeration Documentation
TemplatedKind
enum clang::FunctionDecl::TemplatedKind
The kind of templated function a FunctionDecl can be.
Enumerator
TK_NonTemplate
TK_FunctionTemplate
TK_MemberSpecialization
TK_FunctionTemplateSpecialization
TK_DependentFunctionTemplateSpecialization
TK_DependentNonTemplate
Definition at line 1977 of file Decl.h.
Constructor & Destructor Documentation
FunctionDecl()
FunctionDecl::FunctionDecl (Kind DK, ASTContext & C, DeclContext * DC, SourceLocation StartLoc, const DeclarationNameInfo & NameInfo, QualType T, TypeSourceInfo * TInfo, StorageClass S, bool UsesFPIntrin, bool isInlineSpecified, ConstexprSpecKind ConstexprKind, Expr * TrailingRequiresClause = nullptr) protected
Definition at line 3041 of file Decl.cpp.
Referenced by Create(), and CreateDeserialized().
Member Function Documentation
BodyContainsImmediateEscalatingExpressions()
bool clang::FunctionDecl::BodyContainsImmediateEscalatingExpressions () const inline
Definition at line 2454 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by isImmediateFunction().
castFromDeclContext()
static FunctionDecl* clang::FunctionDecl::castFromDeclContext (const DeclContext * DC) inline static
Definition at line 3053 of file Decl.h.
castToDeclContext()
static DeclContext* clang::FunctionDecl::castToDeclContext (const FunctionDecl * D) inline static
Definition at line 3050 of file Decl.h.
classof()
static bool clang::FunctionDecl::classof (const Decl * D) inline static
Definition at line 3046 of file Decl.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::FunctionDecl::classofKind (Kind K) inline static
Definition at line 3047 of file Decl.h.
Referenced by classof().
Create() [1/2]
FunctionDecl * FunctionDecl::Create (ASTContext & C, DeclContext * DC, SourceLocation StartLoc, const DeclarationNameInfo & NameInfo, QualType T, TypeSourceInfo * TInfo, StorageClass SC, bool UsesFPIntrin, bool isInlineSpecified, bool hasWrittenPrototype, ConstexprSpecKind ConstexprKind, Expr * TrailingRequiresClause) static
Definition at line 5402 of file Decl.cpp.
References AttributeLangSupport::C, clang::Function, FunctionDecl(), hasWrittenPrototype(), isInlineSpecified(), setHasWrittenPrototype(), clang::T, and UsesFPIntrin().
Create() [2/2]
static FunctionDecl* clang::FunctionDecl::Create (ASTContext & C, DeclContext * DC, SourceLocation StartLoc, SourceLocation NLoc, DeclarationName N, QualType T, TypeSourceInfo * TInfo, StorageClass SC, bool UsesFPIntrin = false, bool isInlineSpecified = false, bool hasWrittenPrototype = true, ConstexprSpecKind ConstexprKind = ConstexprSpecKind::Unspecified, Expr * TrailingRequiresClause = nullptr) inline static
Definition at line 2162 of file Decl.h.
References AttributeLangSupport::C, hasWrittenPrototype(), isInlineSpecified(), clang::T, and UsesFPIntrin().
Referenced by emitOutlinedFunctionPrologue(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicSetterCopyHelperFunction(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
CreateDeserialized()
FunctionDecl * FunctionDecl::CreateDeserialized (ASTContext & C, Decl::DeclID ID) static
Definition at line 5415 of file Decl.cpp.
References AttributeLangSupport::C, clang::Function, FunctionDecl(), ID, clang::SC_None, and clang::Unspecified.
doesDeclarationForceExternallyVisibleDefinition()
bool FunctionDecl::doesDeclarationForceExternallyVisibleDefinition () const
For a function declaration in C or C++, determine whether this declaration causes the definition to be externally visible.
For instance, this determines if adding the current declaration to the set of redeclarations of the given functions causes isInlineDefinitionExternallyVisible to change from false to true.
Definition at line 3811 of file Decl.cpp.
References doesThisDeclarationHaveABody().
Referenced by clang::CodeGen::CodeGenModule::EmitGlobal().
doesThisDeclarationHaveABody()
bool clang::FunctionDecl::doesThisDeclarationHaveABody () const inline
Returns whether this specific declaration of the function has a body.
Definition at line 2297 of file Decl.h.
References Body, clang::DeclContext::FunctionDeclBits, and isLateTemplateParsed().
Referenced by clang::ASTRecordWriter::AddFunctionDefinition(), CheckAbstractClassUsage(), clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), doesDeclarationForceExternallyVisibleDefinition(), clang::CodeGen::CodeGenModule::EmitGlobal(), clang::dataflow::DataflowAnalysisContext::getAdornedCFG(), clang::CXXMethodDecl::hasInlineBody(), IsDisallowedCopyOrAssign(), isInlineDefinitionExternallyVisible(), isThisDeclarationADefinition(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl().
FriendConstraintRefersToEnclosingTemplate()
bool clang::FunctionDecl::FriendConstraintRefersToEnclosingTemplate () const inline
Definition at line 2619 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and getCanonicalDecl().
Referenced by isMemberLikeConstrainedFriend(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getAssociatedConstraints()
void clang::FunctionDecl::getAssociatedConstraints (SmallVectorImpl< const Expr * > & AC) const inline
Get the associated-constraints of this function declaration.
Currently, this will either be a vector of size 1 containing the trailing-requires-clause or an empty vector.
Use this instead of getTrailingRequiresClause for concepts APIs that accept an ArrayRef of constraint expressions.
Definition at line 2663 of file Decl.h.
Referenced by clang::Sema::resolveAddressOfSingleOverloadCandidate().
getBody() [1/2]
Stmt* clang::FunctionDecl::getBody () const inline override virtual
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
Otherwise this method returns null.
Reimplemented from clang::Decl.
Definition at line 2271 of file Decl.h.
getBody() [2/2]
Stmt * FunctionDecl::getBody (const FunctionDecl *& Definition) const
Retrieve the body (definition) of the function.
The function body might be in any of the (re-)declarations of this function. The variant that accepts a FunctionDecl pointer will set that function declaration to the actual declaration containing the body (if there is one). NOTE: For checking if there is a body, use hasBody() instead, to avoid unnecessary AST de-serialization of the body.
Definition at line 3240 of file Decl.cpp.
References clang::Decl::getASTContext(), and hasBody().
Referenced by clang::ASTRecordWriter::AddFunctionDefinition(), clang::Sema::CheckConstexprFunctionDefinition(), clang::CodeGen::CodeGenFunction::EmitConstructorBody(), clang::CodeGen::CodeGenFunction::EmitDestructorBody(), clang::CodeGen::CodeGenFunction::emitImplicitAssignmentOperatorBody(), endsWithReturn(), clang::CodeGen::CodeGenFunction::GenerateCode(), getMethodBody(), clang::dataflow::getReferencedDecls(), HandleDestructionImpl(), clang::ASTNodeImporter::ImportFunctionDeclBody(), clang::Sema::InstantiateFunctionDefinition(), clang::CodeGen::CodeGenFunction::StartFunction(), clang::interp::ByteCodeStmtGen< Emitter >::visitFunc(), and clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl().
getBuiltinID()
unsigned FunctionDecl::getBuiltinID (bool ConsiderWrapperFunctions = false) const
Returns a value indicating whether this function corresponds to a builtin function.
The function corresponds to a built-in function if it is declared at translation scope or within an extern "C" block and its name matches with the name of a builtin. The returned value will be 0 for functions that do not correspond to a builtin, a value of type Builtin::ID if in the target-independent range [1,Builtin::First), or a target-specific builtin value.
Parameters
ConsiderWrapperFunctions If true, we should consider wrapper functions as their wrapped builtins. This shouldn't be done in general, but it's useful in Sema to diagnose calls to wrappers based on their semantics.
Definition at line 3636 of file Decl.cpp.
Referenced by clang::Sema::AddKnownFunctionAttributes(), clang::Sema::BuildCallExpr(), clang::Sema::BuildResolvedCallExpr(), clang::ASTContext::canBuiltinBeRedeclared(), clang::Sema::CheckEquivalentExceptionSpec(), clang::CodeGen::CodeGenFunction::checkTargetFeatures(), clang::interp::ByteCodeEmitter::compileFunc(), clang::Sema::ConvertArgumentsForCall(), clang::CodeGen::CodeGenFunction::EmitBranchOnBoolExpr(), EmitDirectCallee(), clang::Sema::FixOverloadedFunctionReference(), getAbsoluteValueFunctionKind(), clang::interp::Function::getBuiltinID(), getMemoryFunctionKind(), clang::interp::Function::isBuiltin(), and isInlineBuiltinDeclaration().
getCallResultType()
QualType clang::FunctionDecl::getCallResultType () const inline
Determine the type of an expression that calls this function.
Definition at line 2792 of file Decl.h.
References clang::Type::castAs(), clang::Decl::getASTContext(), and clang::ValueDecl::getType().
Referenced by clang::Sema::BuildResolvedCallExpr().
getCanonicalDecl() [1/2]
const FunctionDecl* clang::FunctionDecl::getCanonicalDecl () const inline
Definition at line 2678 of file Decl.h.
References getCanonicalDecl().
getCanonicalDecl() [2/2]
FunctionDecl * FunctionDecl::getCanonicalDecl () override virtual
Retrieves the "canonical" declaration of the given declaration.
Reimplemented from clang::Decl.
Reimplemented in clang::CXXConversionDecl, clang::CXXDestructorDecl, clang::CXXConstructorDecl, and clang::CXXMethodDecl.
Definition at line 3621 of file Decl.cpp.
References clang::Redeclarable< FunctionDecl >::getFirstDecl().
Referenced by clang::Sema::CheckImmediateEscalatingFunctionDefinition(), clang::interp::Program::createFunction(), clang::CodeGen::CGOpenMPRuntime::emitDeclareTargetFunction(), FriendConstraintRefersToEnclosingTemplate(), getCanonicalDecl(), clang::CXXMethodDecl::getCanonicalDecl(), clang::CXXConstructorDecl::getCanonicalDecl(), clang::CXXDestructorDecl::getCanonicalDecl(), clang::CXXConversionDecl::getCanonicalDecl(), clang::interp::Program::getFunction(), isDeleted(), isGlobal(), isInstantiationOf(), isMultiVersion(), clang::Sema::SetDeclDefaulted(), clang::Sema::SetDeclDeleted(), setFriendConstraintRefersToEnclosingTemplate(), setIsMultiVersion(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getConstexprKind()
ConstexprSpecKind clang::FunctionDecl::getConstexprKind () const inline
Definition at line 2440 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by CheckConstexprDestructorSubobjects(), isConsteval(), isConstexpr(), isConstexprSpecified(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getDeclaredReturnType()
QualType clang::FunctionDecl::getDeclaredReturnType () const inline
Get the declared return type, which may differ from the actual return type if the return type is deduced.
Definition at line 2773 of file Decl.h.
References clang::Type::castAs(), getReturnType(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), and clang::T.
Referenced by IsOverloadOrOverrideImpl().
getDefalutedOrDeletedInfo()
FunctionDecl::DefaultedOrDeletedFunctionInfo * FunctionDecl::getDefalutedOrDeletedInfo () const
Definition at line 3155 of file Decl.cpp.
References DefaultedOrDeletedInfo, and clang::DeclContext::FunctionDeclBits.
Referenced by clang::TemplateDeclInstantiator::SubstDefaultedFunction(), and clang::ASTDeclWriter::VisitFunctionDecl().
getDefaultLoc()
SourceLocation clang::FunctionDecl::getDefaultLoc () const inline
Definition at line 2362 of file Decl.h.
References isExplicitlyDefaulted().
Referenced by clang::ASTDeclWriter::VisitFunctionDecl().
getDefinition() [1/2]
FunctionDecl* clang::FunctionDecl::getDefinition () inline
Get the definition for this declaration.
Definition at line 2253 of file Decl.h.
References isDefined().
Referenced by clang::ento::RetainSummaryManager::canEval(), clang::dataflow::DataflowAnalysisContext::getAdornedCFG(), clang::CallGraphNode::getDefinition(), getDefinition(), getMethodBody(), clang::ASTNodeImporter::hasReturnTypeDeclaredInside(), clang::Sema::InstantiateFunctionDefinition(), and DeviceFunctionTracker::~DeviceFunctionTracker().
getDefinition() [2/2]
const FunctionDecl* clang::FunctionDecl::getDefinition () const inline
Definition at line 2259 of file Decl.h.
References getDefinition().
getDeletedMessage()
StringLiteral* clang::FunctionDecl::getDeletedMessage () const inline
Get the message that indicates why this function was deleted.
Definition at line 2669 of file Decl.h.
References DefaultedOrDeletedInfo, clang::DeclContext::FunctionDeclBits, and clang::FunctionDecl::DefaultedOrDeletedFunctionInfo::getDeletedMessage().
Referenced by clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::JSONNodeDumper::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getDependentSpecializationInfo()
DependentFunctionTemplateSpecializationInfo * FunctionDecl::getDependentSpecializationInfo () const
Definition at line 4243 of file Decl.cpp.
Referenced by clang::ASTNodeImporter::ImportTemplateInformation(), clang::ASTDeclWriter::VisitCXXMethodDecl(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getDescribedFunctionTemplate()
FunctionTemplateDecl * FunctionDecl::getDescribedFunctionTemplate () const
Retrieves the function template that is described by this function declaration.
Every function template is represented as a FunctionTemplateDecl and a FunctionDecl (or something derived from FunctionDecl). The former contains template properties (such as the template parameter lists) while the latter contains the actual description of the template's contents. FunctionTemplateDecl::getTemplatedDecl() retrieves the FunctionDecl that describes the function template, getDescribedFunctionTemplate() retrieves the FunctionTemplateDecl from a FunctionDecl.
Definition at line 4046 of file Decl.cpp.
Referenced by clang::Sema::ActOnConversionDeclarator(), clang::Sema::BuildLambdaExpr(), clang::SemaCUDA::CheckCall(), clang::Sema::CheckCXXDefaultArguments(), clang::Sema::CheckIfFunctionSpecializationIsImmediate(), clang::Sema::CheckLiteralOperatorDeclaration(), CheckOperatorNewDeleteTypes(), clang::interp::ByteCodeEmitter::compileFunc(), clang::Sema::CompleteLambdaCallOperator(), clang::Sema::DeclareAggregateDeductionGuideFromInitList(), clang::Sema::DeduceReturnType(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), clang::CodeGen::CodeGenFunction::EmitLambdaDelegatingInvokeBody(), clang::Sema::FriendConstraintsDependOnEnclosingTemplate(), FunctionsCorrespond(), clang::CXXRecordDecl::getGenericLambdaTemplateParameterList(), clang::CXXMethodDecl::isCopyAssignmentOperator(), clang::CXXConstructorDecl::isCopyOrMoveConstructor(), isMemberLikeConstrainedFriend(), clang::CXXMethodDecl::isMoveAssignmentOperator(), IsOverloadOrOverrideImpl(), clang::CXXConstructorDecl::isSpecializationCopyingObject(), isThisDeclarationInstantiatedFromAFriendDefinition(), clang::SemaCUDA::maybeAddHostDeviceAttrs(), setPreviousDeclaration(), ShouldWarnAboutMissingPrototype(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
getEllipsisLoc()
SourceLocation clang::FunctionDecl::getEllipsisLoc () const inline
Returns the location of the ellipsis of a variadic function.
Definition at line 2194 of file Decl.h.
References clang::Type::getAs(), clang::FunctionProtoType::getEllipsisLoc(), and clang::ValueDecl::getType().
Referenced by getParametersSourceRange().
getExceptionSpecSourceRange()
SourceRange FunctionDecl::getExceptionSpecSourceRange () const
Attempt to compute an informative source range covering the function exception specification, if any.
Definition at line 3909 of file Decl.cpp.
References clang::FunctionTypeLoc::getExceptionSpecRange(), and getFunctionTypeLoc().
Referenced by clang::CodeGen::CodeGenFunction::EmitStartEHSpec().
getExceptionSpecType()
ExceptionSpecificationType clang::FunctionDecl::getExceptionSpecType () const inline
Gets the ExceptionSpecificationType as declared.
Definition at line 2780 of file Decl.h.
References clang::EST_None, clang::Type::getAs(), clang::FunctionProtoType::getExceptionSpecType(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSourceInfo(), and clang::T.
Referenced by clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForOverloadedOperator().
getFunctionTypeLoc()
FunctionTypeLoc FunctionDecl::getFunctionTypeLoc () const
Find the source location information for how the type of this function was written.
May be absent (for example if the function was declared via a typedef) and may contain a different type from that of the function (for example if the function type was adjusted by an attribute).
Definition at line 3871 of file Decl.cpp.
References clang::TypeLoc::getAs(), clang::TypeSourceInfo::getTypeLoc(), clang::DeclaratorDecl::getTypeSourceInfo(), and clang::TypeLoc::IgnoreParens().
Referenced by getExceptionSpecSourceRange(), and getReturnTypeSourceRange().
getInstantiatedFromDecl()
FunctionDecl * FunctionDecl::getInstantiatedFromDecl () const
Definition at line 4070 of file Decl.cpp.
Referenced by getPatternFunctionDecl(), clang::ASTNodeImporter::ImportTemplateInformation(), and clang::ASTDeclWriter::VisitFunctionDecl().
getInstantiatedFromMemberFunction()
FunctionDecl * FunctionDecl::getInstantiatedFromMemberFunction () const
If this function is an instantiation of a member function of a class template specialization, retrieves the function from which it was instantiated.
This routine will return non-NULL for (non-templated) member functions of class templates and for instantiations of function templates. For example, given:
template<typename T>
struct X {
  void f(T);
};
The declaration for X<int>::f is a (non-templated) FunctionDecl whose parent is the class template specialization X<int>. For this declaration, getInstantiatedFromFunction() will return the FunctionDecl X<T>::A. When a complete definition of X<int>::A is required, it will be instantiated from the declaration returned by getInstantiatedFromMemberFunction().
Definition at line 4018 of file Decl.cpp.
References getMemberSpecializationInfo().
Referenced by adjustDeclToTemplate(), clang::Sema::CheckForFunctionRedefinition(), getExplicitVisibilityAux(), getODRHash(), getPatternFunctionDecl(), hasExplicitMemberDefinition(), clang::ASTNodeImporter::ImportTemplateInformation(), isOutOfLine(), isThisDeclarationInstantiatedFromAFriendDefinition(), clang::Sema::resolveAddressOfSingleOverloadCandidate(), and clang::TextNodeDumper::VisitFunctionDecl().
getLanguageLinkage()
LanguageLinkage FunctionDecl::getLanguageLinkage () const
Compute the language linkage.
Definition at line 3492 of file Decl.cpp.
References getDeclLanguageLinkage().
getLiteralIdentifier()
const IdentifierInfo * FunctionDecl::getLiteralIdentifier () const
getLiteralIdentifier - The literal suffix identifier this function represents, if any.
Definition at line 3991 of file Decl.cpp.
References clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::getCXXLiteralIdentifier(), and clang::NamedDecl::getDeclName().
getMemberSpecializationInfo()
MemberSpecializationInfo * FunctionDecl::getMemberSpecializationInfo () const
If this function is an instantiation of a member function of a class template specialization, retrieves the member specialization information.
Definition at line 4025 of file Decl.cpp.
Referenced by getInstantiatedFromMemberFunction(), getTemplateInstantiationPattern(), clang::ASTNodeImporter::ImportTemplateInformation(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
getMemoryFunctionKind()
unsigned FunctionDecl::getMemoryFunctionKind () const
Identify a memory copying or setting function.
If the given function is a memory copy or setting function, returns the corresponding Builtin ID. If the function is not a memory function, returns 0.
Definition at line 4405 of file Decl.cpp.
References getBuiltinID(), clang::NamedDecl::getIdentifier(), isExternC(), clang::Decl::isInStdNamespace(), and clang::IdentifierInfo::isStr().
Referenced by getStrlenExprArg().
getMinRequiredArguments()
unsigned FunctionDecl::getMinRequiredArguments () const
Returns the minimum number of arguments needed to call this function.
getMinRequiredArguments - Returns the minimum number of arguments needed to call this function.
This may be fewer than the number of function parameters, if some of the parameters have default arguments (in C++).
This may be fewer than the number of function parameters, if some of the parameters have default arguments (in C++) or are parameter packs (C++11).
Definition at line 3717 of file Decl.cpp.
References clang::CPlusPlus, clang::Decl::getASTContext(), clang::Decl::getLangOpts(), getNumParams(), and parameters().
Referenced by compareOverloads(), clang::Sema::ConvertArgumentsForCall(), getMinRequiredExplicitArguments(), clang::CXXConstructorDecl::isConvertingConstructor(), clang::CXXConstructorDecl::isDefaultConstructor(), clang::Sema::SpecialMemberIsTrivial(), and clang::FunctionCallFilterCCC::ValidateCandidate().
getMinRequiredExplicitArguments()
unsigned FunctionDecl::getMinRequiredExplicitArguments () const
Returns the minimum number of non-object arguments needed to call this function.
This produces the same value as getMinRequiredArguments except it does not count the explicit object argument, if any.
Definition at line 3744 of file Decl.cpp.
References getMinRequiredArguments(), and hasCXXExplicitFunctionObjectParameter().
getMostRecentDeclImpl()
FunctionDecl* clang::FunctionDecl::getMostRecentDeclImpl () inline override protected virtual
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
Reimplemented from clang::Decl.
Definition at line 2143 of file Decl.h.
References clang::Redeclarable< FunctionDecl >::getMostRecentDecl().
getMultiVersionKind()
MultiVersionKind FunctionDecl::getMultiVersionKind () const
Gets the kind of multiversioning attribute this declaration has.
Note that this can return a value even if the function is not multiversion, such as the case of 'target'.
Definition at line 3562 of file Decl.cpp.
References clang::CPUDispatch, clang::CPUSpecific, clang::None, clang::Target, clang::TargetClones, and clang::TargetVersion.
Referenced by MultiVersionTypesCompatible(), patchDefaultTargetVersion(), and PreviousDeclsHaveMultiVersionAttribute().
getNameForDiagnostic()
void FunctionDecl::getNameForDiagnostic (raw_ostream & OS, const PrintingPolicy & Policy, bool Qualified) const override virtual
Appends a human-readable name for this declaration into the given stream.
This is the method invoked by Sema when displaying a NamedDecl in a diagnostic. It does not necessarily produce the same result as printName(); for example, class template specializations are printed with their template arguments.
Reimplemented from clang::NamedDecl.
Definition at line 3085 of file Decl.cpp.
References clang::TemplateArgumentList::asArray(), clang::NamedDecl::getNameForDiagnostic(), getTemplateSpecializationArgs(), and clang::printTemplateArgumentList().
getNameInfo()
DeclarationNameInfo clang::FunctionDecl::getNameInfo () const inline
Definition at line 2184 of file Decl.h.
References clang::NamedDecl::getDeclName(), and clang::Decl::getLocation().
Referenced by CheckConstexprFunctionBody(), getReturnTypeSourceRange(), clang::Sema::RebuildLambdaScopeInfo(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getNextRedeclarationImpl()
FunctionDecl* clang::FunctionDecl::getNextRedeclarationImpl () inline override protected virtual
Returns the next redeclaration or itself if this is the only decl.
Decl subclasses that can be redeclared should override this method so that Decl::redecl_iterator can iterate over them.
Reimplemented from clang::Decl.
Definition at line 2135 of file Decl.h.
References clang::Redeclarable< FunctionDecl >::getNextRedeclaration().
getNonObjectParameter() [1/2]
ParmVarDecl* clang::FunctionDecl::getNonObjectParameter (unsigned I) inline
Definition at line 2738 of file Decl.h.
References getParamDecl(), and hasCXXExplicitFunctionObjectParameter().
getNonObjectParameter() [2/2]
const ParmVarDecl* clang::FunctionDecl::getNonObjectParameter (unsigned I) const inline
Definition at line 2734 of file Decl.h.
References getParamDecl(), and hasCXXExplicitFunctionObjectParameter().
Referenced by clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::CXXMethodDecl::isCopyAssignmentOperator(), clang::CXXMethodDecl::isMoveAssignmentOperator(), and clang::Sema::SpecialMemberIsTrivial().
getNumNonObjectParams()
unsigned FunctionDecl::getNumNonObjectParams () const
Definition at line 3739 of file Decl.cpp.
References getNumParams(), and hasCXXExplicitFunctionObjectParameter().
Referenced by clang::Sema::FunctionNonObjectParamTypesAreEqual().
getNumParams()
unsigned FunctionDecl::getNumParams () const
Return the number of parameters this function must have based on its FunctionType.
getNumParams - Return the number of parameters this function must have based on its FunctionType.
This is the length of the ParamInfo array after it has been created.
Definition at line 3696 of file Decl.cpp.
References clang::Type::getAs(), clang::FunctionProtoType::getNumParams(), and clang::ValueDecl::getType().
Referenced by clang::SemaOpenMP::ActOnOpenMPDeclareVariantDirective(), addX86InterruptAttrs(), allowAmbiguity(), castArgToParamTypeIfNeeded(), clang::Sema::CheckCXXDefaultArguments(), CheckOperatorNewDeleteTypes(), clang::Sema::CheckOverloadedOperatorDeclaration(), compareOverloads(), clang::interp::InterpFrame::describe(), clang::CodeGen::CodeGenFunction::EmitInheritedCXXConstructorCall(), evaluateCDTSize(), FunctionsCorrespond(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForOverloadedOperator(), getMinRequiredArguments(), getNDSWDS(), clang::ento::CXXDeallocatorCall::getNumArgs(), clang::CXXMethodDecl::getNumExplicitParams(), getNumNonObjectParams(), clang::OverloadCandidate::getNumParams(), getParamDecl(), getParametersSourceRange(), GetSYCLKernelObjectType(), hasCopyOrMoveCtorParam(), hasCXXExplicitFunctionObjectParameter(), hasIdenticalPassObjectSizeAttrs(), hasOneParamOrDefaultArgs(), clang::Sema::InstantiateDefaultCtorDefaultArgs(), clang::CXXConstructorDecl::isConvertingConstructor(), isDestroyingOperatorDelete(), clang::SemaCUDA::isEmptyConstructor(), clang::Sema::isUsualDeallocationFunction(), clang::CXXMethodDecl::isUsualDeallocationFunction(), parameters(), shouldTrackFirstArgument(), clang::Sema::SpecialMemberIsTrivial(), clang::FunctionCallFilterCCC::ValidateCandidate(), and clang::TextNodeDumper::VisitFunctionDecl().
getODRHash() [1/2]
unsigned FunctionDecl::getODRHash ()
Returns ODRHash of the function.
This value is calculated and stored on first call, then the stored value returned on the other calls.
Definition at line 4530 of file Decl.cpp.
References clang::ODRHash::AddFunctionDecl(), clang::ODRHash::CalculateHash(), and getInstantiatedFromMemberFunction().
Referenced by clang::ODRDiagsEmitter::diagnoseMismatch(), and clang::ASTDeclWriter::VisitFunctionDecl().
getODRHash() [2/2]
unsigned FunctionDecl::getODRHash () const
Returns cached ODRHash of the function.
This must have been previously computed and stored.
Definition at line 4525 of file Decl.cpp.
getOverloadedOperator()
OverloadedOperatorKind FunctionDecl::getOverloadedOperator () const
getOverloadedOperator - Which C++ overloaded operator this function represents, if any.
Definition at line 3983 of file Decl.cpp.
References clang::DeclarationName::CXXOperatorName, clang::DeclarationName::getCXXOverloadedOperator(), clang::NamedDecl::getDeclName(), and clang::OO_None.
Referenced by clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::CodeGen::CodeGenFunction::EmitDeleteCall(), findImplicitlyDeclaredEqualityComparisons(), hasReservedReturnType(), clang::CXXMethodDecl::isCopyAssignmentOperator(), isDestroyingOperatorDelete(), clang::isLambdaCallOperator(), clang::CXXMethodDecl::isMoveAssignmentOperator(), isOverloadedOperator(), isStandardNewDelete(), isStdOstreamOperatorCall(), isSYCLKernelBodyFunction(), clang::CXXMethodDecl::isUsualDeallocationFunction(), and clang::CodeGen::CodeGenFunction::StartFunction().
getParamDecl() [1/2]
ParmVarDecl* clang::FunctionDecl::getParamDecl (unsigned i) inline
Definition at line 2712 of file Decl.h.
References getNumParams().
getParamDecl() [2/2]
const ParmVarDecl* clang::FunctionDecl::getParamDecl (unsigned i) const inline
Definition at line 2708 of file Decl.h.
References getNumParams().
Referenced by clang::SemaOpenMP::ActOnOpenMPDeclareVariantDirective(), addX86InterruptAttrs(), allowAmbiguity(), clang::Sema::BuildLiteralOperatorCall(), castArgToParamTypeIfNeeded(), CheckConstexprParameterTypes(), clang::Sema::CheckCXXDefaultArguments(), clang::Sema::CheckExplicitObjectOverride(), clang::Sema::CheckLiteralOperatorDeclaration(), CheckOperatorNewDeclaration(), CheckOperatorNewDeleteTypes(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckOverridingFunctionAttributes(), clang::SemaSYCL::CheckSYCLKernelCall(), clang::Sema::ConvertArgumentsForCall(), create_call_once(), create_dispatch_once(), create_dispatch_sync(), create_OSAtomicCompareAndSwap(), create_std_move_forward(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::DeduceTemplateArguments(), clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::interp::InterpFrame::describe(), diagnoseInstanceReference(), clang::Sema::DiagnoseInvalidExplicitObjectParameterInLambda(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), clang::CodeGen::CGHLSLRuntime::emitEntryFunction(), evaluateCDTSize(), FunctionsCorrespond(), clang::Sema::GatherArgumentsForCall(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForOverloadedOperator(), getNDSWDS(), getNonObjectParameter(), GetSYCLKernelObjectType(), HandleFunctionCall(), HandleLambdaCapture(), hasCopyOrMoveCtorParam(), hasCXXExplicitFunctionObjectParameter(), clang::Sema::InstantiateDefaultCtorDefaultArgs(), clang::CXXConstructorDecl::isCopyConstructor(), clang::CXXConstructorDecl::isCopyOrMoveConstructor(), isDestroyingOperatorDelete(), clang::Sema::isInitListConstructor(), clang::CXXConstructorDecl::isMoveConstructor(), clang::CXXConstructorDecl::isSpecializationCopyingObject(), clang::Sema::PerformImplicitConversion(), clang::Sema::RebuildLambdaScopeInfo(), shouldTrackFirstArgument(), and clang::Sema::SpecialMemberIsTrivial().
getParametersSourceRange()
SourceRange FunctionDecl::getParametersSourceRange () const
Attempt to compute an informative source range covering the function parameters, including the ellipsis of a variadic function.
The source range excludes the parentheses, and is invalid if there are no parameters and no ellipsis.
Definition at line 3893 of file Decl.cpp.
References Begin, End, clang::SourceRange::getBegin(), getEllipsisLoc(), clang::SourceRange::getEnd(), getNumParams(), clang::ParmVarDecl::getSourceRange(), clang::SourceLocation::isInvalid(), and clang::SourceLocation::isValid().
Referenced by clang::Sema::ConvertArgumentsForCall().
getPointOfInstantiation()
SourceLocation FunctionDecl::getPointOfInstantiation () const
Retrieve the (first) point of instantiation of a function template specialization or a member of a class template specialization.
Returns
the first point of instantiation, if this function was instantiated from a template; otherwise, returns an invalid source location.
Definition at line 4366 of file Decl.cpp.
getPreviousDeclImpl()
FunctionDecl* clang::FunctionDecl::getPreviousDeclImpl () inline override protected virtual
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
Reimplemented from clang::Decl.
Definition at line 2139 of file Decl.h.
References clang::Redeclarable< FunctionDecl >::getPreviousDecl().
getPrimaryTemplate()
FunctionTemplateDecl * FunctionDecl::getPrimaryTemplate () const
Retrieve the primary template that this function template specialization either specializes or was instantiated from.
If this function declaration is not a function template specialization, returns NULL.
Definition at line 4166 of file Decl.cpp.
Referenced by allowAmbiguity(), clang::Sema::CheckLiteralOperatorDeclaration(), getPatternFunctionDecl(), getTemplateInstantiationPattern(), clang::CXXMethodDecl::isCopyAssignmentOperator(), clang::CXXConstructorDecl::isCopyOrMoveConstructor(), clang::CXXMethodDecl::isMoveAssignmentOperator(), isOutOfLine(), isTemplate(), clang::CXXMethodDecl::isUsualDeallocationFunction(), and clang::Sema::SubstDefaultArgument().
getReturnType()
QualType clang::FunctionDecl::getReturnType () const inline
Definition at line 2756 of file Decl.h.
References clang::Type::castAs(), and clang::ValueDecl::getType().
Referenced by clang::CodeGen::CodeGenFunction::BuildFunctionArgList(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildReturnStmt(), clang::Sema::BuildSynthesizedThreeWayComparison(), CheckConstexprFunctionBody(), CheckConstexprReturnType(), clang::Sema::CheckCoroutineWrapper(), clang::interp::ByteCodeEmitter::compileFunc(), create_OSAtomicCompareAndSwap(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::DeduceReturnType(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), DiagnoseForRangeReferenceVariableCopies(), clang::ODRDiagsEmitter::diagnoseMismatch(), dumpMicrosoftThunkAdjustment(), evaluateCDTSize(), clang::comments::DeclInfo::fill(), clang::CodeGen::CodeGenFunction::GenerateCode(), getCallableReturnType(), clang::CXXConversionDecl::getConversionType(), getDeclaredReturnType(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForOverloadedOperator(), clang::Sema::getMoreSpecializedTemplate(), getNDSWDS(), HandleVirtualDispatch(), implicitObjectParamIsLifetimeBound(), clang::isReturnValueRefCounted(), clang::Sema::RebuildLambdaScopeInfo(), shouldTrackFirstArgument(), and clang::interp::ByteCodeStmtGen< Emitter >::visitFunc().
getReturnTypeSourceRange()
SourceRange FunctionDecl::getReturnTypeSourceRange () const
Attempt to compute an informative source range covering the function return type.
This may omit qualifiers and other information with limited representation in the AST.
Definition at line 3877 of file Decl.cpp.
References clang::Decl::getASTContext(), clang::DeclarationNameInfo::getBeginLoc(), clang::SourceRange::getEnd(), getFunctionTypeLoc(), getNameInfo(), clang::FunctionTypeLoc::getReturnLoc(), clang::ASTContext::getSourceManager(), clang::TypeLoc::getSourceRange(), clang::SourceLocation::isInvalid(), clang::SourceRange::isInvalid(), and SM.
Referenced by clang::Sema::CheckOverridingFunctionReturnType(), and clang::ODRDiagsEmitter::diagnoseMismatch().
getSourceRange()
SourceRange FunctionDecl::getSourceRange () const override virtual
Source range that this declaration covers.
Reimplemented from clang::DeclaratorDecl.
Definition at line 4401 of file Decl.cpp.
References clang::DeclaratorDecl::getOuterLocStart().
Referenced by clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckExplicitObjectOverride(), clang::ODRDiagsEmitter::diagnoseMismatch(), patchDefaultTargetVersion(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getStorageClass()
StorageClass clang::FunctionDecl::getStorageClass () const inline
Returns the storage class as written in the source.
For the computed linkage of symbol, see getLinkage.
Definition at line 2799 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::CheckMain(), CheckOperatorNewDeleteDeclarationScope(), clang::Sema::CheckOverridingFunctionAttributes(), createDefaultTargetVersionFrom(), clang::ODRDiagsEmitter::diagnoseMismatch(), getFunctionSourceLocation(), isGlobal(), isStatic(), clang::CXXMethodDecl::isStatic(), RedeclForcesDefC99(), redeclForcesDefMSVC(), clang::TextNodeDumper::VisitFunctionDecl(), clang::JSONNodeDumper::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getTemplatedKind()
FunctionDecl::TemplatedKind FunctionDecl::getTemplatedKind () const
What kind of templated function this is.
Definition at line 3997 of file Decl.cpp.
References TK_DependentFunctionTemplateSpecialization, TK_DependentNonTemplate, TK_FunctionTemplate, TK_FunctionTemplateSpecialization, TK_MemberSpecialization, and TK_NonTemplate.
Referenced by clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckFunctionConstraints(), getPatternFunctionDecl(), clang::ASTNodeImporter::ImportFunctionTemplateWithTemplateArgsFromSpecialization(), clang::ASTNodeImporter::ImportTemplateInformation(), clang::Sema::IsAtLeastAsConstrained(), clang::Sema::IsInsideALocalClassWithinATemplateFunction(), clang::ASTDeclWriter::VisitCXXMethodDecl(), clang::installapi::InstallAPIVisitor::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
getTemplateInstantiationPattern()
FunctionDecl * FunctionDecl::getTemplateInstantiationPattern (bool ForDefinition = true) const
Retrieve the function declaration from which this function could be instantiated, if it is an instantiation (rather than a non-template or a specialization, for example).
If ForDefinition is false, explicit specializations will be treated as if they were implicit instantiations. This will then find the pattern corresponding to non-definition portions of the declaration, such as default arguments and the exception specification.
Definition at line 4117 of file Decl.cpp.
References clang::CodeGen::ForDefinition, getDefinitionOrSelf(), clang::MemberSpecializationInfo::getInstantiatedFrom(), getMemberSpecializationInfo(), getPrimaryTemplate(), getTemplateSpecializationKind(), clang::MemberSpecializationInfo::getTemplateSpecializationKind(), isDefined(), clang::isGenericLambdaCallOperatorSpecialization(), and clang::isTemplateInstantiation().
Referenced by clang::Sema::CheckIfFunctionSpecializationIsImmediate(), clang::Sema::DeduceReturnType(), clang::CodeGen::CodeGenFunction::GenerateCode(), GetSignature(), clang::CXXMethodDecl::hasInlineBody(), isImplicitlyInstantiable(), isUserProvided(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), and clang::Sema::SubstDefaultArgument().
getTemplateSpecializationArgs()
const TemplateArgumentList * FunctionDecl::getTemplateSpecializationArgs () const
Retrieve the template arguments used to produce this function template specialization from the primary template.
If this function declaration is not a function template specialization, returns NULL.
Definition at line 4182 of file Decl.cpp.
Referenced by addInstanceOfTransition(), calculateKernelNameType(), clang::Sema::CheckIfFunctionSpecializationIsImmediate(), clang::Sema::DeduceReturnType(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::CodeGen::CodeGenFunction::EmitIntelSYCLAllocaBuiltin(), clang::CodeGen::CodeGenFunction::EmitLambdaDelegatingInvokeBody(), getNameForDiagnostic(), and isTemplate().
getTemplateSpecializationArgsAsWritten()
const ASTTemplateArgumentListInfo * FunctionDecl::getTemplateSpecializationArgsAsWritten () const
Retrieve the template argument list as written in the sources, if any.
If this function declaration is not a function template specialization or if it had no explicit template argument list, returns NULL. Note that it an explicit template argument list may be written empty, e.g., template<> void foo<>(char* s);
Definition at line 4192 of file Decl.cpp.
Referenced by clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getTemplateSpecializationInfo()
FunctionTemplateSpecializationInfo * FunctionDecl::getTemplateSpecializationInfo () const
If this function is actually a function template specialization, retrieve information about this function template specialization.
Otherwise, returns NULL.
Definition at line 4176 of file Decl.cpp.
Referenced by getExplicitVisibilityAux(), clang::ASTNodeImporter::ImportFunctionTemplateWithTemplateArgsFromSpecialization(), clang::ASTNodeImporter::ImportTemplateInformation(), clang::ASTDeclWriter::VisitCXXMethodDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl(), clang::installapi::InstallAPIVisitor::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
getTemplateSpecializationKind()
TemplateSpecializationKind FunctionDecl::getTemplateSpecializationKind () const
Determine what kind of template instantiation this function represents.
Definition at line 4272 of file Decl.cpp.
References clang::Decl::FOK_None, clang::Decl::getFriendObjectKind(), clang::TSK_ExplicitSpecialization, and clang::TSK_Undeclared.
Referenced by clang::Sema::ActOnConversionDeclarator(), clang::Sema::CheckCXXDefaultArguments(), clang::Sema::DefineUsedVTables(), getTemplateInstantiationPattern(), clang::installapi::getVTableLinkage(), clang::CodeGen::CodeGenModule::getVTableLinkage(), clang::installapi::hasVTable(), clang::ASTNodeImporter::ImportTemplateInformation(), isTemplateInstantiation(), and clang::TextNodeDumper::VisitFunctionDecl().
getTemplateSpecializationKindForInstantiation()
TemplateSpecializationKind FunctionDecl::getTemplateSpecializationKindForInstantiation () const
Determine the kind of template specialization this function represents for the purpose of template instantiation.
Definition at line 4295 of file Decl.cpp.
References clang::Decl::FOK_None, clang::Decl::getFriendObjectKind(), clang::TSK_ExplicitSpecialization, and clang::TSK_Undeclared.
Referenced by isImplicitlyInstantiable().
hasBody() [1/2]
bool clang::FunctionDecl::hasBody () const inline override virtual
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
Note that hasBody can also return true if any redeclaration of this Decl represents a declaration for a body of code.
Reimplemented from clang::Decl.
Definition at line 2224 of file Decl.h.
Referenced by getBody(), and isInlineBuiltinDeclaration().
hasBody() [2/2]
bool FunctionDecl::hasBody (const FunctionDecl *& Definition) const
Returns true if the function has a body.
The function body might be in any of the (re-)declarations of this function. The variant that accepts a FunctionDecl pointer will set that function declaration to the actual declaration containing the body (if there is one).
Definition at line 3160 of file Decl.cpp.
References clang::Redeclarable< FunctionDecl >::redecls().
Referenced by clang::Sema::BuildResolvedCallExpr(), clang::Sema::DefineUsedVTables(), clang::Sema::DiagnoseImmediateEscalatingReason(), clang::CodeGen::CodeGenModule::getVTableLinkage(), clang::cross_tu::hasBodyOrInit(), isImplicitlyInstantiable(), isOutOfLine(), and clang::CodeGen::CodeGenVTables::isVTableExternal().
hasCXXExplicitFunctionObjectParameter()
bool FunctionDecl::hasCXXExplicitFunctionObjectParameter () const
Definition at line 3735 of file Decl.cpp.
References getNumParams(), getParamDecl(), and clang::ParmVarDecl::isExplicitObjectParameter().
Referenced by clang::Sema::CheckFunctionCall(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckOverridingFunctionExceptionSpec(), clang::Sema::ConvertArgumentsForCall(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), clang::Sema::FunctionNonObjectParamTypesAreEqual(), getMinRequiredExplicitArguments(), getNonObjectParameter(), getNumNonObjectParams(), clang::CXXMethodDecl::isExplicitObjectMemberFunction(), and clang::CXXMethodDecl::isImplicitObjectMemberFunction().
hasImplicitReturnZero()
bool clang::FunctionDecl::hasImplicitReturnZero () const inline
Whether falling off this function implicitly returns null/zero.
If a more specific implicit return value is required, front-ends should synthesize the appropriate return statements.
Definition at line 2392 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::CodeGen::CodeGenFunction::GenerateCode(), and clang::ASTDeclWriter::VisitFunctionDecl().
hasInheritedPrototype()
bool clang::FunctionDecl::hasInheritedPrototype () const inline
Whether this function inherited its prototype from a previous declaration.
Definition at line 2423 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by hasPrototype(), and clang::ASTDeclWriter::VisitFunctionDecl().
hasOneParamOrDefaultArgs()
bool FunctionDecl::hasOneParamOrDefaultArgs () const
Determine whether this function has a single parameter, or multiple parameters where all but the first have default arguments.
This notion is used in the definition of copy/move constructors and initializer list constructors. Note that, unlike getMinRequiredArguments, parameter packs are not treated specially here.
Definition at line 3749 of file Decl.cpp.
References getNumParams(), P, and parameters().
Referenced by clang::CXXConstructorDecl::isCopyOrMoveConstructor(), clang::Sema::isInitListConstructor(), and clang::CXXConstructorDecl::isSpecializationCopyingObject().
hasPrototype()
bool clang::FunctionDecl::hasPrototype () const inline
Whether this function has a prototype, either because one was explicitly written or because it was "inherited" by merging a declaration without a prototype with a declaration that has a prototype.
Definition at line 2407 of file Decl.h.
References hasInheritedPrototype(), and hasWrittenPrototype().
Referenced by clang::Sema::BuildResolvedCallExpr(), and castArgToParamTypeIfNeeded().
hasSkippedBody()
bool clang::FunctionDecl::hasSkippedBody () const inline
True if the function was a definition but its body was skipped.
Definition at line 2591 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by isThisDeclarationADefinition(), and clang::ASTDeclWriter::VisitFunctionDecl().
hasTrivialBody()
bool FunctionDecl::hasTrivialBody () const
Returns whether the function has a trivial body that does not require any specific codegen.
Definition at line 3171 of file Decl.cpp.
Referenced by CanSkipVTablePointerInitialization(), clang::SemaCUDA::isEmptyConstructor(), clang::SemaCUDA::isEmptyDestructor(), and clang::CodeGen::CodeGenModule::TryEmitBaseDestructorAsAlias().
hasWrittenPrototype()
bool clang::FunctionDecl::hasWrittenPrototype () const inline
Whether this function has a written prototype.
Definition at line 2412 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by Create(), hasPrototype(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
instantiationIsPending()
bool clang::FunctionDecl::instantiationIsPending () const inline
Whether the instantiation of this function is pending.
This bit is set when the decision to instantiate this function is made and unset if and when the function body is created. That leaves out cases where instantiation did not happen because the template definition was not seen in this TU. This bit remains set in those cases, under the assumption that the instantiation will happen in some other TU.
Definition at line 2471 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
isConsteval()
bool clang::FunctionDecl::isConsteval () const inline
Definition at line 2446 of file Decl.h.
References clang::Consteval, and getConstexprKind().
Referenced by clang::Sema::ActOnStartOfFunctionDef(), CheckConstexprDeclStmt(), CheckConstexprFunctionBody(), CheckConstexprParameterTypes(), CheckConstexprReturnType(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckImmediateEscalatingFunctionDefinition(), clang::Sema::CheckMain(), clang::Sema::DiagnoseImmediateEscalatingReason(), EvaluateAndDiagnoseImmediateInvocation(), isImmediateEscalating(), isImmediateFunction(), and IsOverloadOrOverrideImpl().
isConstexpr()
bool clang::FunctionDecl::isConstexpr () const inline
Whether this is a (C++11) constexpr function or constexpr constructor.
Definition at line 2434 of file Decl.h.
References getConstexprKind(), and clang::Unspecified.
Referenced by CheckConstexprFunction(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::CheckMain(), CheckTrivialDefaultConstructor(), clang::interp::ByteCodeEmitter::compileFunc(), clang::CodeGen::CodeGenModule::EmitGlobal(), IsOverloadOrOverrideImpl(), clang::Sema::MarkVirtualMembersReferenced(), clang::SemaCUDA::maybeAddHostDeviceAttrs(), and clang::JSONNodeDumper::VisitFunctionDecl().
isConstexprSpecified()
bool clang::FunctionDecl::isConstexprSpecified () const inline
Definition at line 2443 of file Decl.h.
References clang::Constexpr, and getConstexprKind().
isCPUDispatchMultiVersion()
bool FunctionDecl::isCPUDispatchMultiVersion () const
True if this function is a multiversioned dispatch function as a part of the cpu_specific/cpu_dispatch functionality.
Definition at line 3576 of file Decl.cpp.
References isMultiVersion().
Referenced by IsCPUDispatchCPUSpecificMultiVersion(), and clang::Sema::resolveAndFixAddressOfSingleOverloadCandidate().
isCPUSpecificMultiVersion()
bool FunctionDecl::isCPUSpecificMultiVersion () const
True if this function is a multiversioned processor specific function as a part of the cpu_specific/cpu_dispatch functionality.
Definition at line 3580 of file Decl.cpp.
References isMultiVersion().
Referenced by IsCPUDispatchCPUSpecificMultiVersion(), and clang::Sema::resolveAndFixAddressOfSingleOverloadCandidate().
isDefaulted()
bool clang::FunctionDecl::isDefaulted () const inline
Whether this function is defaulted.
Valid for e.g. special member functions, defaulted comparisions (not methods!).
Definition at line 2349 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::DiagnoseDeletedDefaultedFunction(), clang::Sema::diagnoseZeroToNullptrConversion(), clang::CodeGen::CodeGenFunction::GenerateCode(), HandleFunctionCall(), isDeletedAsWritten(), isImmediateEscalating(), clang::Sema::isImplicitlyDeleted(), isMemcpyEquivalentSpecialMember(), isThisDeclarationADefinition(), clang::Sema::SetDeclDefaulted(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::JSONNodeDumper::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
isDefined() [1/2]
bool clang::FunctionDecl::isDefined () const inline
Definition at line 2247 of file Decl.h.
Referenced by getDefinition(), and getTemplateInstantiationPattern().
isDefined() [2/2]
bool FunctionDecl::isDefined (const FunctionDecl *& Definition, bool CheckForPendingFriendDefinition = false) const
Returns true if the function has a definition that does not need to be instantiated.
The variant that accepts a FunctionDecl pointer will set that function declaration to the declaration that is a definition (if there is one).
Parameters
CheckForPendingFriendDefinition If true, also check for friend declarations that were instantiated from function definitions. Such a declaration behaves as if it is a definition for the purpose of redefinition checking, but isn't actually a "real" definition until its body is instantiated.
Definition at line 3207 of file Decl.cpp.
References clang::Redeclarable< FunctionDecl >::redecls().
Referenced by clang::Sema::CheckForFunctionRedefinition(), clang::interp::ByteCodeEmitter::compileFunc(), clang::CodeGen::CodeGenFunction::GenerateVarArgsThunk(), getMethodBody(), clang::CXXMethodDecl::hasInlineBody(), clang::TemplateDeclInstantiator::InitFunctionInstantiation(), clang::SemaCUDA::isEmptyConstructor(), clang::SemaCUDA::isEmptyDestructor(), clang::Sema::isUnavailableAlignedAllocationFunction(), and clang::Sema::MarkVTableUsed().
isDeleted()
bool clang::FunctionDecl::isDeleted () const inline
Whether this function has been deleted.
A function that is "deleted" (via the C++0x "= delete" syntax) acts like a normal function, except that it cannot actually be called or have its address taken. Deleted functions are typically used in C++ overload resolution to attract arguments whose type or lvalue/rvalue-ness would permit the use of a different overload that would behave incorrectly. For example, one might use deleted functions to ban implicit conversion from a floating-point number to an Integer type:
struct Integer {
  Integer(long); // construct from a long
  Integer(double) = delete; // no construction from float or double
  Integer(long double) = delete; // no construction from long double
};
Definition at line 2504 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and getCanonicalDecl().
Referenced by clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::DiagnoseDeletedDefaultedFunction(), clang::CXXRecordDecl::finishedDefaultedOrDeletedMember(), clang::Sema::isImplicitlyDeleted(), clang::Sema::LookupSpecialMember(), clang::Sema::MarkVTableUsed(), ShouldWarnAboutMissingPrototype(), clang::TextNodeDumper::VisitFunctionDecl(), clang::JSONNodeDumper::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
isDeletedAsWritten()
bool clang::FunctionDecl::isDeletedAsWritten () const inline
Definition at line 2508 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and isDefaulted().
Referenced by clang::ODRDiagsEmitter::diagnoseMismatch(), isThisDeclarationADefinition(), setDeletedAsWritten(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::JSONNodeDumper::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
isDestroyingOperatorDelete()
bool FunctionDecl::isDestroyingOperatorDelete () const
Determine whether this is a destroying operator delete.
Definition at line 3478 of file Decl.cpp.
References clang::Type::getAsCXXRecordDecl(), getNumParams(), getOverloadedOperator(), getParamDecl(), clang::ValueDecl::getType(), and clang::Decl::isInStdNamespace().
Referenced by CheckOperatorDeleteDeclaration(), clang::CodeGen::CodeGenFunction::EmitCXXDeleteExpr(), EmitObjectDelete(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), getUsualDeleteParams(), and clang::CXXMethodDecl::isUsualDeallocationFunction().
isExplicitlyDefaulted()
bool clang::FunctionDecl::isExplicitlyDefaulted () const inline
Whether this function is explicitly defaulted.
Definition at line 2353 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::ODRDiagsEmitter::diagnoseMismatch(), findImplicitlyDeclaredEqualityComparisons(), getDefaultLoc(), setDefaultLoc(), clang::ASTDeclWriter::VisitCXXMethodDecl(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
isExternC()
bool FunctionDecl::isExternC () const
Determines whether this function is a function with external, C linkage.
Definition at line 3496 of file Decl.cpp.
References isDeclExternC().
Referenced by clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::CheckLiteralOperatorDeclaration(), clang::Sema::GatherArgumentsForCall(), getFunctionSourceLocation(), and getMemoryFunctionKind().
isFunctionTemplateSpecialization()
bool FunctionDecl::isFunctionTemplateSpecialization () const
Determine whether this function is a function template specialization.
Definition at line 4058 of file Decl.cpp.
Referenced by clang::Sema::DeclareImplicitDeductionGuides(), clang::CodeGen::CodeGenFunction::EmitLambdaDelegatingInvokeBody(), clang::Sema::getTopMostPointOfInstantiation(), clang::isGenericLambdaCallOperatorSpecialization(), clang::SemaCUDA::maybeAddHostDeviceAttrs(), and ShouldWarnAboutMissingPrototype().
isGlobal()
bool FunctionDecl::isGlobal () const
Determines whether this is a global function.
Definition at line 3510 of file Decl.cpp.
References getCanonicalDecl(), clang::Decl::getDeclContext(), clang::DeclContext::getParent(), getStorageClass(), clang::DeclContext::isNamespace(), and clang::SC_Static.
Referenced by ShouldWarnAboutMissingPrototype(), and clang::CallGraph::VisitFunctionDecl().
isImmediateEscalating()
bool FunctionDecl::isImmediateEscalating () const
Definition at line 3272 of file Decl.cpp.
References isConsteval(), isDefaulted(), and clang::isLambdaCallOperator().
Referenced by clang::Sema::ActOnStartOfFunctionDef(), clang::Sema::CheckIfFunctionSpecializationIsImmediate(), clang::Sema::CheckImmediateEscalatingFunctionDefinition(), clang::Sema::DiagnoseImmediateEscalatingReason(), and isImmediateFunction().
isImmediateFunction()
bool FunctionDecl::isImmediateFunction () const
Definition at line 3292 of file Decl.cpp.
References BodyContainsImmediateEscalatingExpressions(), isConsteval(), and isImmediateEscalating().
Referenced by clang::Sema::BuildCXXDefaultArgExpr(), clang::Sema::CheckCXXDefaultArgExpr(), clang::Sema::CheckImmediateEscalatingFunctionDefinition(), clang::CodeGen::CodeGenModule::EmitTopLevelDecl(), EvaluateAndDiagnoseImmediateInvocation(), clang::VTableContextBase::hasVtableSlot(), and clang::JSONNodeDumper::VisitFunctionDecl().
isImplicitlyInstantiable()
bool FunctionDecl::isImplicitlyInstantiable () const
Determines whether this function is a function template specialization or a member of a class template specialization that can be implicitly instantiated.
Definition at line 4075 of file Decl.cpp.
References getTemplateInstantiationPattern(), getTemplateSpecializationKindForInstantiation(), hasBody(), isInlined(), clang::Decl::isInvalidDecl(), clang::TSK_ExplicitInstantiationDeclaration, clang::TSK_ExplicitInstantiationDefinition, clang::TSK_ExplicitSpecialization, clang::TSK_ImplicitInstantiation, and clang::TSK_Undeclared.
isIneligibleOrNotSelected()
bool clang::FunctionDecl::isIneligibleOrNotSelected () const inline
Definition at line 2382 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::CXXRecordDecl::finishedDefaultedOrDeletedMember(), clang::TextNodeDumper::VisitFunctionDecl(), and clang::ASTDeclWriter::VisitFunctionDecl().
isInExternCContext()
bool FunctionDecl::isInExternCContext () const
Determines whether this function's context is, or is nested within, a C++ extern "C" linkage spec.
Definition at line 3500 of file Decl.cpp.
References clang::Decl::getLexicalDeclContext(), and clang::DeclContext::isExternCContext().
isInExternCXXContext()
bool FunctionDecl::isInExternCXXContext () const
Determines whether this function's context is, or is nested within, a C++ extern "C++" linkage spec.
Definition at line 3506 of file Decl.cpp.
References clang::Decl::getLexicalDeclContext(), and clang::DeclContext::isExternCXXContext().
isInlineBuiltinDeclaration()
bool FunctionDecl::isInlineBuiltinDeclaration () const
Determine if this function provides an inline implementation of a builtin.
Definition at line 3453 of file Decl.cpp.
References getBuiltinID(), and hasBody().
Referenced by clang::CodeGen::CodeGenFunction::GenerateCode().
isInlined()
bool clang::FunctionDecl::isInlined () const inline
Determine whether this function should be inlined, because it is either marked "inline" or "constexpr" or is a member function of a class that was defined in the class body.
Definition at line 2832 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::checkClassLevelDLLAttribute(), clang::SemaSYCL::ConstructOpenCLKernel(), clang::Sema::DefineUsedVTables(), clang::CodeGen::CGDebugInfo::EmitFuncDeclForCallSite(), clang::CodeGen::CodeGenModule::getVTableLinkage(), isImplicitlyInstantiable(), isInlineDefinitionExternallyVisible(), isMSExternInline(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), setPreviousDeclaration(), ShouldWarnAboutMissingPrototype(), useInlineVisibilityHidden(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
isInlineDefinitionExternallyVisible()
bool FunctionDecl::isInlineDefinitionExternallyVisible () const
For an inline function definition in C, or for a gnu_inline function in C++, determine whether the definition will be externally visible.
Inline function definitions are always available for inlining optimizations. However, depending on the language dialect, declaration specifiers, and attributes, the definition of an inline function may or may not be "externally" visible to other translation units in the program.
In C99, inline definitions are not externally visible by default. However, if even one of the global-scope declarations is marked "extern inline", the inline definition becomes externally visible (C99 6.7.4p6).
In GNU89 mode, or if the gnu_inline attribute is attached to the function definition, we use the GNU semantics for inline, which are nearly the opposite of C99 semantics. In particular, "inline" by itself will create an externally visible symbol, but "extern inline" will not create an externally visible symbol.
Definition at line 3931 of file Decl.cpp.
References doesThisDeclarationHaveABody(), isInlined(), and willHaveBody().
isInlineSpecified()
bool clang::FunctionDecl::isInlineSpecified () const inline
Determine whether the "inline" keyword was specified for this function.
Definition at line 2810 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::CheckMain(), Create(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::CodeGen::CodeGenVTables::isVTableExternal(), RedeclForcesDefC99(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::JSONNodeDumper::VisitFunctionDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
isLateTemplateParsed()
bool clang::FunctionDecl::isLateTemplateParsed () const inline
Whether this templated function will be late parsed.
Definition at line 2328 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by doesThisDeclarationHaveABody(), clang::Sema::InstantiateFunctionDefinition(), and clang::ASTDeclWriter::VisitFunctionDecl().
isMain()
bool FunctionDecl::isMain () const
Determines whether this function is "main", which is the entry point into an executable program.
Definition at line 3310 of file Decl.cpp.
References clang::TranslationUnitDecl::getASTContext(), clang::Decl::getDeclContext(), clang::ASTContext::getLangOpts(), clang::DeclContext::getRedeclContext(), and isNamed().
Referenced by clang::Sema::BuildReturnStmt(), getFunctionSourceLocation(), IsOverloadOrOverrideImpl(), clang::Sema::SetDeclDeleted(), and clang::CodeGen::CodeGenFunction::StartFunction().
isMemberLikeConstrainedFriend()
bool FunctionDecl::isMemberLikeConstrainedFriend () const
Determine whether a function is a friend function that cannot be redeclared outside of its class, per C++ [temp.friend]p9.
Definition at line 3540 of file Decl.cpp.
References FriendConstraintRefersToEnclosingTemplate(), getDescribedFunctionTemplate(), clang::Decl::getFriendObjectKind(), and clang::DeclaratorDecl::getTrailingRequiresClause().
Referenced by IsOverloadOrOverrideImpl().
isMSExternInline()
bool FunctionDecl::isMSExternInline () const
The combination of the extern and inline keywords under MSVC forces the function to be required.
Note: This function assumes that we will only get called when isInlined() would return true for this FunctionDecl.
Definition at line 3761 of file Decl.cpp.
References isInlined().
isMSVCRTEntryPoint()
bool FunctionDecl::isMSVCRTEntryPoint () const
Determines whether this function is a MSVCRT user defined entry point.
Definition at line 3318 of file Decl.cpp.
References clang::TranslationUnitDecl::getASTContext(), clang::Decl::getDeclContext(), clang::NamedDecl::getIdentifier(), clang::NamedDecl::getName(), clang::DeclContext::getRedeclContext(), clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().
Referenced by IsOverloadOrOverrideImpl(), and clang::CodeGen::CodeGenFunction::StartFunction().
isMultiVersion()
bool clang::FunctionDecl::isMultiVersion () const inline
True if this function is considered a multiversioned function.
Definition at line 2601 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and getCanonicalDecl().
Referenced by clang::CodeGen::CodeGenFunction::checkTargetFeatures(), clang::CodeGen::CodeGenModule::EmitGlobal(), clang::ASTContext::forEachMultiversionedFunctionVersion(), clang::CodeGen::CodeGenModule::getLLVMLinkageForDeclarator(), isBetterMultiversionCandidate(), isCPUDispatchMultiVersion(), isCPUSpecificMultiVersion(), isNonViableMultiVersionOverload(), isTargetClonesMultiVersion(), isTargetMultiVersion(), isTargetMultiVersionDefault(), isTargetVersionMultiVersion(), clang::Sema::NoteOverloadCandidate(), and clang::ASTDeclWriter::VisitFunctionDecl().
isNoReturn()
bool FunctionDecl::isNoReturn () const
Determines whether this function is known to be 'noreturn', through an attribute on its declaration or its type.
Definition at line 3529 of file Decl.cpp.
References clang::ValueDecl::getType().
Referenced by clang::Sema::BuildReturnStmt().
isOutOfLine()
bool FunctionDecl::isOutOfLine () const override virtual
Determine whether this is or was instantiated from an out-of-line definition of a member function.
Reimplemented from clang::Decl.
Definition at line 4378 of file Decl.cpp.
References getInstantiatedFromMemberFunction(), getPrimaryTemplate(), hasBody(), and clang::Decl::isOutOfLine().
Referenced by clang::CXXMethodDecl::hasInlineBody(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
isOverloadedOperator()
bool clang::FunctionDecl::isOverloadedOperator () const inline
Whether this function declaration represents an C++ overloaded operator, e.g., "operator+".
Definition at line 2844 of file Decl.h.
References getOverloadedOperator(), and clang::OO_None.
Referenced by clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), isStdOstreamOperatorCall(), and printMemFnName().
isPureVirtual()
bool clang::FunctionDecl::isPureVirtual () const inline
Whether this virtual function is pure, i.e.
makes the containing class abstract.
Definition at line 2324 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::ODRDiagsEmitter::diagnoseMismatch(), clang::CXXMethodDecl::getDevirtualizedMethod(), clang::CXXMethodDecl::isVirtual(), clang::Sema::MarkVirtualMembersReferenced(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::TextNodeDumper::VisitFunctionDecl(), clang::JSONNodeDumper::VisitFunctionDecl(), and clang::ASTDeclWriter::VisitFunctionDecl().
isReplaceableGlobalAllocationFunction()
bool FunctionDecl::isReplaceableGlobalAllocationFunction (std::optional< unsigned > * AlignmentParam = nullptr, bool * IsNothrow = nullptr) const
Determines whether this function is one of the replaceable global allocation functions: void *operator new(size_t); void *operator new(size_t, const std::nothrow_t &) noexcept; void *operator new[](size_t); void *operator new[](size_t, const std::nothrow_t &) noexcept; void operator delete(void *) noexcept; void operator delete(void *, std::size_t) noexcept; [C++1y] void operator delete(void *, const std::nothrow_t &) noexcept; void operator delete[](void *) noexcept; void operator delete[](void *, std::size_t) noexcept; [C++1y] void operator delete[](void *, const std::nothrow_t &) noexcept; These functions have special behavior under C++1y [expr.new]: An implementation is allowed to omit a call to a replaceable global allocation function.
[...]
If this function is an aligned allocation/deallocation function, return the parameter number of the requested alignment through AlignmentParam.
If this function is an allocation/deallocation function that takes the std::nothrow_t tag, return true through IsNothrow,
Definition at line 3370 of file Decl.cpp.
References clang::Type::castAs(), clang::Qualifiers::Const, clang::DeclarationName::CXXOperatorName, clang::Type::getAs(), clang::Decl::getASTContext(), clang::QualType::getCVRQualifiers(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::ASTContext::getLangOpts(), clang::Type::getPointeeType(), clang::DeclContext::getRedeclContext(), clang::ASTContext::getSizeType(), clang::ValueDecl::getType(), clang::ASTContext::hasSameType(), clang::Type::isAlignValT(), clang::Type::isEnumeralType(), clang::Type::isNothrowT(), clang::QualType::isNull(), clang::Type::isReferenceType(), clang::IdentifierInfo::isStr(), clang::DeclContext::isTranslationUnit(), and clang::T.
Referenced by clang::Sema::AddKnownFunctionAttributesForReplaceableGlobalAllocationFunction(), clang::Sema::CheckEquivalentExceptionSpec(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), EmitNewDeleteCall(), clang::Sema::isUnavailableAlignedAllocationFunction(), and clang::ento::ExprEngine::VisitCXXNewExpr().
isReservedGlobalPlacementOperator()
bool FunctionDecl::isReservedGlobalPlacementOperator () const
Determines whether this operator new or delete is one of the reserved global placement operators: void *operator new(size_t, void *); void *operator new[](size_t, void *); void operator delete(void *, void *); void operator delete[](void *, void *); These functions have special behavior under [new.delete.placement]: These functions are reserved, a C++ program may not define functions that displace the versions in the Standard C++ library.
The provisions of [basic.stc.dynamic] do not apply to these reserved placement forms of operator new and operator delete.
This function must be an allocation or deallocation function.
Definition at line 3345 of file Decl.cpp.
References clang::Type::castAs(), clang::DeclarationName::CXXOperatorName, clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::DeclContext::getRedeclContext(), clang::ValueDecl::getType(), and clang::DeclContext::isTranslationUnit().
Referenced by CalculateCookiePadding(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CXXNewExpr::shouldNullCheckAllocation(), and clang::ento::ExprEngine::VisitCXXNewExpr().
isStatic()
bool clang::FunctionDecl::isStatic () const inline
Definition at line 2840 of file Decl.h.
References getStorageClass(), and clang::SC_Static.
Referenced by clang::Sema::CanBeGetReturnTypeOnAllocFailure(), clang::Sema::CheckFunctionCall(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), and clang::CodeGen::CGDebugInfo::EmitFuncDeclForCallSite().
isTargetClonesMultiVersion()
bool FunctionDecl::isTargetClonesMultiVersion () const
True if this function is a multiversioned dispatch function as a part of the target-clones functionality.
Definition at line 3598 of file Decl.cpp.
References isMultiVersion().
isTargetMultiVersion()
bool FunctionDecl::isTargetMultiVersion () const
True if this function is a multiversioned dispatch function as a part of the target functionality.
Definition at line 3584 of file Decl.cpp.
References isMultiVersion().
Referenced by isNonViableMultiVersionOverload().
isTargetMultiVersionDefault()
bool FunctionDecl::isTargetMultiVersionDefault () const
True if this function is the default version of a multiversioned dispatch function as a part of the target functionality.
Definition at line 3589 of file Decl.cpp.
References isMultiVersion().
Referenced by isNonViableMultiVersionOverload().
isTargetVersionMultiVersion()
bool FunctionDecl::isTargetVersionMultiVersion () const
True if this function is a multiversioned dispatch function as a part of the target-version functionality.
Definition at line 3602 of file Decl.cpp.
References isMultiVersion().
isTemplateInstantiation()
bool FunctionDecl::isTemplateInstantiation () const
Determines if the given function was instantiated from a function template.
Definition at line 4110 of file Decl.cpp.
References getTemplateSpecializationKind(), and clang::isTemplateInstantiation().
Referenced by clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::SemaCUDA::isEmptyConstructor(), and clang::SemaCUDA::isEmptyDestructor().
isThisDeclarationADefinition()
bool clang::FunctionDecl::isThisDeclarationADefinition () const inline
Returns whether this specific declaration of the function is also a definition that does not contain uninstantiated body.
This does not determine whether the function has been defined (e.g., in a previous definition); for that information, use isDefined.
Note: the function declaration does not become a definition until the parser reaches the definition, if called before, this function will return false.
Definition at line 2285 of file Decl.h.
References doesThisDeclarationHaveABody(), clang::Decl::hasDefiningAttr(), hasSkippedBody(), isDefaulted(), isDeletedAsWritten(), and willHaveBody().
Referenced by clang::Sema::InstantiateFunctionDefinition(), clang::FunctionTemplateDecl::isThisDeclarationADefinition(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), and clang::CallGraph::VisitFunctionDecl().
isThisDeclarationInstantiatedFromAFriendDefinition()
bool FunctionDecl::isThisDeclarationInstantiatedFromAFriendDefinition () const
Determine whether this specific declaration of the function is a friend declaration that was instantiated from a function definition.
Such declarations behave like definitions in some contexts.
Definition at line 3184 of file Decl.cpp.
References getDescribedFunctionTemplate(), clang::Decl::getFriendObjectKind(), getInstantiatedFromMemberFunction(), and clang::FunctionTemplateDecl::getInstantiatedFromMemberTemplate().
Referenced by clang::Sema::InstantiateFunctionDefinition().
isTrivial()
bool clang::FunctionDecl::isTrivial () const inline
Whether this function is "trivial" in some specialized C++ senses.
Can only be true for default constructors, copy constructors, copy assignment operators, and destructors. Not meaningful until the class has been fully built by Sema.
Definition at line 2341 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::CXXRecordDecl::addedEligibleSpecialMemberFunction(), clang::Sema::checkClassLevelDLLAttribute(), CheckTrivialDefaultConstructor(), clang::CodeGen::CodeGenFunction::EmitCXXConstructExpr(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), clang::CXXRecordDecl::finishedDefaultedOrDeletedMember(), HandleDestructionImpl(), HandleFunctionCall(), clang::Expr::isConstantInitializer(), clang::SemaCUDA::isEmptyConstructor(), clang::SemaCUDA::isEmptyDestructor(), isMemcpyEquivalentSpecialMember(), isTrivialObjectAssignment(), clang::CodeGen::ConstantEmitter::tryEmitPrivateForVarInit(), clang::interp::ByteCodeExprGen< Emitter >::VisitCXXConstructExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitCXXInheritedCtorInitExpr(), clang::TextNodeDumper::VisitFunctionDecl(), and clang::ASTDeclWriter::VisitFunctionDecl().
isTrivialForCall()
bool clang::FunctionDecl::isTrivialForCall () const inline
Definition at line 2344 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::CXXRecordDecl::addedEligibleSpecialMemberFunction(), clang::CXXRecordDecl::setTrivialForCallFlags(), and clang::ASTDeclWriter::VisitFunctionDecl().
isUserProvided()
bool clang::FunctionDecl::isUserProvided () const inline
True if this method is user-declared and was not deleted or defaulted on its first declaration.
Definition at line 2374 of file Decl.h.
References getTemplateInstantiationPattern().
Referenced by clang::CXXRecordDecl::addedEligibleSpecialMemberFunction(), clang::CXXRecordDecl::finishedDefaultedOrDeletedMember(), clang::SemaCUDA::IdentifyTarget(), clang::Sema::RequireLiteralType(), and clang::Sema::SpecialMemberIsTrivial().
isVariadic()
bool FunctionDecl::isVariadic () const
Whether this function is variadic.
Definition at line 3093 of file Decl.cpp.
References clang::ValueDecl::getType().
Referenced by canEmitDelegateCallArgs(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), compareOverloads(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitLambdaBlockInvokeBody(), clang::CodeGen::CodeGenFunction::EmitLambdaInAllocaCallOpBody(), clang::CodeGen::CodeGenFunction::EmitLambdaStaticInvokeBody(), clang::comments::DeclInfo::fill(), clang::CXXConstructorDecl::isConvertingConstructor(), clang::SemaCUDA::maybeAddHostDeviceAttrs(), clang::Sema::SpecialMemberIsTrivial(), and clang::JSONNodeDumper::VisitFunctionDecl().
isVirtualAsWritten()
bool clang::FunctionDecl::isVirtualAsWritten () const inline
Whether this function is marked as virtual explicitly.
Definition at line 2315 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::CheckConstexprFunctionDefinition(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::TemplateDeclInstantiator::InitMethodInstantiation(), clang::CXXMethodDecl::isVirtual(), clang::TextNodeDumper::VisitFunctionDecl(), clang::JSONNodeDumper::VisitFunctionDecl(), and clang::ASTDeclWriter::VisitFunctionDecl().
param_begin() [1/2]
param_iterator clang::FunctionDecl::param_begin () inline
Definition at line 2697 of file Decl.h.
References parameters().
Referenced by clang::Sema::CheckLiteralOperatorDeclaration(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), hasIdenticalPassObjectSizeAttrs(), clang::CodeGen::CodeGenFunction::StartThunk(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl(), and clang::TextNodeDumper::VisitFunctionDecl().
param_begin() [2/2]
param_const_iterator clang::FunctionDecl::param_begin () const inline
Definition at line 2699 of file Decl.h.
References parameters().
param_empty()
bool clang::FunctionDecl::param_empty () const inline
Definition at line 2696 of file Decl.h.
References parameters().
Referenced by clang::TextNodeDumper::VisitFunctionDecl().
param_end() [1/2]
param_iterator clang::FunctionDecl::param_end () inline
Definition at line 2698 of file Decl.h.
References parameters().
Referenced by clang::CodeCompletionResult::createCodeCompletionStringForDecl(), getSyclKernelHandlerArg(), hasIdenticalPassObjectSizeAttrs(), and clang::CodeGen::CodeGenFunction::StartThunk().
param_end() [2/2]
param_const_iterator clang::FunctionDecl::param_end () const inline
Definition at line 2700 of file Decl.h.
References parameters().
param_size()
size_t clang::FunctionDecl::param_size () const inline
Definition at line 2701 of file Decl.h.
References parameters().
Referenced by clang::Sema::BuildResolvedCallExpr(), clang::ento::RetainSummaryManager::canEval(), clang::Sema::CheckLiteralOperatorDeclaration(), create_call_once(), create_dispatch_once(), create_dispatch_sync(), create_OSAtomicCompareAndSwap(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::Sema::getMoreSpecializedTemplate(), and clang::ASTDeclWriter::VisitFunctionDecl().
parameters() [1/2]
MutableArrayRef<ParmVarDecl *> clang::FunctionDecl::parameters () inline
Definition at line 2688 of file Decl.h.
References getNumParams().
parameters() [2/2]
ArrayRef<ParmVarDecl *> clang::FunctionDecl::parameters () const inline
Definition at line 2685 of file Decl.h.
References getNumParams().
Referenced by clang::CodeGen::CodeGenFunction::BuildFunctionArgList(), canEmitDelegateCallArgs(), clang::SemaHLSL::CheckEntryPoint(), clang::Sema::CheckLiteralOperatorDeclaration(), clang::Sema::CheckOverloadedOperatorDeclaration(), compareOverloads(), clang::interp::ByteCodeEmitter::compileFunc(), clang::Sema::CompleteLambdaCallOperator(), clang::Sema::DeclareImplicitDeductionGuides(), clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), clang::CodeGen::CodeGenFunction::EmitLambdaDelegatingInvokeBody(), clang::comments::DeclInfo::fill(), functionDeclHasDefaultArgument(), functionHasPassObjectSizeParams(), clang::CodeGen::CodeGenFunction::GenerateCode(), clang::CXXMethodDecl::getFunctionObjectParameterReferenceType(), getMinRequiredArguments(), clang::Sema::getMoreSpecializedTemplate(), getSyclKernelHandlerArg(), hasNonTrivialConstructorCall(), hasOneParamOrDefaultArgs(), isOSObjectRelated(), param_begin(), param_empty(), param_end(), param_size(), clang::ento::AnyFunctionCall::parameters(), clang::TemplateDeclInstantiator::SubstFunctionType(), clang::interp::ByteCodeExprGen< Emitter >::VisitCXXInheritedCtorInitExpr(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl(), and clang::ASTDeclWriter::VisitFunctionDecl().
setBody()
void FunctionDecl::setBody (Stmt * B)
Definition at line 3252 of file Decl.cpp.
References Body, clang::DeclContext::FunctionDeclBits, and clang::Stmt::getEndLoc().
Referenced by clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitLambdaToBlockPointerConversion(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), clang::Sema::DefineImplicitMoveAssignment(), and clang::ASTNodeImporter::ImportFunctionDeclBody().
setBodyContainsImmediateEscalatingExpressions()
void clang::FunctionDecl::setBodyContainsImmediateEscalatingExpressions (bool Set) inline
Definition at line 2450 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and clang::Set.
Referenced by clang::Sema::CheckImmediateEscalatingFunctionDefinition().
setConstexprKind()
void clang::FunctionDecl::setConstexprKind (ConstexprSpecKind CSK) inline
Definition at line 2437 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckMain(), clang::Sema::CompleteLambdaCallOperator(), and clang::ASTDeclReader::VisitFunctionDecl().
setDefaulted()
void clang::FunctionDecl::setDefaulted (bool D = true) inline
Definition at line 2350 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
setDefaultedOrDeletedInfo()
void FunctionDecl::setDefaultedOrDeletedInfo (DefaultedOrDeletedFunctionInfo * Info)
Definition at line 3121 of file Decl.cpp.
References Body, DefaultedOrDeletedInfo, and clang::DeclContext::FunctionDeclBits.
Referenced by setDeletedAsWritten(), clang::TemplateDeclInstantiator::SubstDefaultedFunction(), and clang::ASTDeclReader::VisitFunctionDecl().
setDefaultLoc()
void clang::FunctionDecl::setDefaultLoc (SourceLocation NewLoc) inline
Definition at line 2366 of file Decl.h.
References isExplicitlyDefaulted(), and clang::SourceLocation::isInvalid().
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
setDeletedAsWritten()
void FunctionDecl::setDeletedAsWritten (bool D = true, StringLiteral * Message = nullptr)
Definition at line 3130 of file Decl.cpp.
References clang::FunctionDecl::DefaultedOrDeletedFunctionInfo::Create(), DefaultedOrDeletedInfo, clang::DeclContext::FunctionDeclBits, clang::Decl::getASTContext(), isDeletedAsWritten(), setDefaultedOrDeletedInfo(), and clang::FunctionDecl::DefaultedOrDeletedFunctionInfo::setDeletedMessage().
Referenced by clang::Sema::SetDeclDeleted(), and clang::ASTDeclReader::VisitFunctionDecl().
setDependentTemplateSpecialization()
void FunctionDecl::setDependentTemplateSpecialization (ASTContext & Context, const UnresolvedSetImpl & Templates, const TemplateArgumentListInfo * TemplateArgs)
Specifies that this function declaration is actually a dependent function template specialization.
Definition at line 4232 of file Decl.cpp.
Referenced by clang::Sema::CheckDependentFunctionTemplateSpecialization(), clang::ASTNodeImporter::ImportTemplateInformation(), and clang::ASTDeclReader::VisitFunctionDecl().
setDescribedFunctionTemplate()
void FunctionDecl::setDescribedFunctionTemplate (FunctionTemplateDecl * Template)
Definition at line 4051 of file Decl.cpp.
Referenced by clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
setExplicitlyDefaulted()
void clang::FunctionDecl::setExplicitlyDefaulted (bool ED = true) inline
State that this function is explicitly defaulted.
Definition at line 2358 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
setFriendConstraintRefersToEnclosingTemplate()
void clang::FunctionDecl::setFriendConstraintRefersToEnclosingTemplate (bool V = true) inline
Definition at line 2613 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, getCanonicalDecl(), and V.
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
setFunctionTemplateSpecialization()
void clang::FunctionDecl::setFunctionTemplateSpecialization (FunctionTemplateDecl * Template, const TemplateArgumentList * TemplateArgs, void * InsertPos, TemplateSpecializationKind TSK = TSK_ImplicitInstantiation, const TemplateArgumentListInfo * TemplateArgsAsWritten = nullptr, SourceLocation PointOfInstantiation = SourceLocation()) inline
Specify that this function declaration is actually a function template specialization.
Parameters
Template the function template that this function template specialization specializes.
TemplateArgs the template arguments that produced this function template specialization from the template.
InsertPos If non-NULL, the position in the function template specialization set where the function template specialization data will be inserted.
TSK the kind of template specialization this is.
TemplateArgsAsWritten location info of template arguments.
PointOfInstantiation point at which the function template specialization was first instantiated.
Definition at line 2985 of file Decl.h.
References clang::Decl::getASTContext().
Referenced by clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
setHasImplicitReturnZero()
void clang::FunctionDecl::setHasImplicitReturnZero (bool IRZ) inline
State that falling off this function implicitly returns null/zero.
If a more specific implicit return value is required, front-ends should synthesize the appropriate return statements.
Definition at line 2399 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::CheckMSVCRTEntryPoint(), and clang::ASTDeclReader::VisitFunctionDecl().
setHasInheritedPrototype()
void clang::FunctionDecl::setHasInheritedPrototype (bool P = true) inline
State that this function inherited its prototype from a previous declaration.
Definition at line 2429 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and P.
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
setHasSkippedBody()
void clang::FunctionDecl::setHasSkippedBody (bool Skipped = true) inline
Definition at line 2592 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::ActOnSkippedFunctionBody(), and clang::ASTDeclReader::VisitFunctionDecl().
setHasWrittenPrototype()
void clang::FunctionDecl::setHasWrittenPrototype (bool P = true) inline
State that this function has a written prototype.
Definition at line 2417 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and P.
Referenced by Create(), and clang::ASTDeclReader::VisitFunctionDecl().
setImplicitlyInline()
void clang::FunctionDecl::setImplicitlyInline (bool I = true) inline
Flag that this function is implicitly inline.
Definition at line 2827 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::SetDeclDeleted(), setPreviousDeclaration(), clang::ASTDeclReader::UpdateDecl(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
setIneligibleOrNotSelected()
void clang::FunctionDecl::setIneligibleOrNotSelected (bool II) inline
Definition at line 2385 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::CXXRecordDecl::addedSelectedDestructor(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::ASTDeclReader::VisitFunctionDecl().
setInlineSpecified()
void clang::FunctionDecl::setInlineSpecified (bool I) inline
Set whether the "inline" keyword was specified for this function.
Definition at line 2813 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
setInstantiatedFromDecl()
void FunctionDecl::setInstantiatedFromDecl (FunctionDecl * FD)
Specify that this function declaration was instantiated from a FunctionDecl FD.
This is only used if this is a function declaration declared locally inside of a function template.
Definition at line 4064 of file Decl.cpp.
Referenced by clang::ASTNodeImporter::ImportTemplateInformation(), and clang::ASTDeclReader::VisitFunctionDecl().
setInstantiationIsPending()
void clang::FunctionDecl::setInstantiationIsPending (bool IC) inline
State that the instantiation of this function is pending.
(see instantiationIsPending)
Definition at line 2477 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
setInstantiationOfMemberFunction()
void clang::FunctionDecl::setInstantiationOfMemberFunction (FunctionDecl * FD, TemplateSpecializationKind TSK) inline
Specify that this record is an instantiation of the member function FD.
Definition at line 2885 of file Decl.h.
References clang::Decl::getASTContext().
Referenced by clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
setIsMultiVersion()
void clang::FunctionDecl::setIsMultiVersion (bool V = true) inline
Sets the multiversion state for this declaration and all of its redeclarations.
Definition at line 2607 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, getCanonicalDecl(), and V.
Referenced by patchDefaultTargetVersion(), and clang::ASTDeclReader::VisitFunctionDecl().
setIsPureVirtual()
void FunctionDecl::setIsPureVirtual (bool P = true)
Definition at line 3259 of file Decl.cpp.
References clang::DeclContext::FunctionDeclBits, clang::Decl::getDeclContext(), P, and Parent.
Referenced by clang::Sema::CheckPureMethod(), and clang::ASTDeclReader::VisitFunctionDecl().
setLateTemplateParsed()
void clang::FunctionDecl::setLateTemplateParsed (bool ILT = true) inline
State that this templated function will be late parsed.
Definition at line 2333 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::MarkAsLateParsedTemplate(), clang::Sema::UnmarkAsLateParsedTemplate(), and clang::ASTDeclReader::VisitFunctionDecl().
setLazyBody()
void clang::FunctionDecl::setLazyBody (uint64_t Offset) inline
Definition at line 2303 of file Decl.h.
References Body, clang::DeclContext::FunctionDeclBits, and Offset.
setParams()
void clang::FunctionDecl::setParams (ArrayRef< ParmVarDecl * > NewParamInfo) inline
Definition at line 2716 of file Decl.h.
References clang::Decl::getASTContext().
Referenced by clang::Sema::CompleteLambdaCallOperator(), and clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
setPreviousDeclaration()
void FunctionDecl::setPreviousDeclaration (FunctionDecl * PrevDecl)
Definition at line 3607 of file Decl.cpp.
References getDescribedFunctionTemplate(), isInlined(), setImplicitlyInline(), and clang::Redeclarable< FunctionDecl >::setPreviousDecl().
setRangeEnd()
void clang::FunctionDecl::setRangeEnd (SourceLocation E) inline
Definition at line 2191 of file Decl.h.
Referenced by clang::Sema::CheckPureMethod(), clang::CXXMethodDecl::CXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
setStorageClass()
void clang::FunctionDecl::setStorageClass (StorageClass SClass) inline
Sets the storage class as written in the source.
Definition at line 2804 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::CompleteLambdaCallOperator(), and clang::ASTDeclReader::VisitFunctionDecl().
setTemplateSpecializationKind()
void FunctionDecl::setTemplateSpecializationKind (TemplateSpecializationKind TSK, SourceLocation PointOfInstantiation = SourceLocation())
Determine what kind of template instantiation this function represents.
Definition at line 4339 of file Decl.cpp.
References clang::Decl::getASTContext(), clang::Decl::getASTMutationListener(), clang::SourceLocation::isValid(), and clang::TSK_ExplicitSpecialization.
setTrivial()
void clang::FunctionDecl::setTrivial (bool IT) inline
Definition at line 2342 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
setTrivialForCall()
void clang::FunctionDecl::setTrivialForCall (bool IT) inline
Definition at line 2345 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::ASTDeclReader::VisitFunctionDecl().
setUsesFPIntrin()
void clang::FunctionDecl::setUsesFPIntrin (bool I) inline
Set whether the function was declared in source context that requires constrained FP intrinsics.
Definition at line 2824 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
setUsesSEHTry()
void clang::FunctionDecl::setUsesSEHTry (bool UST) inline
Definition at line 2483 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::ActOnSEHTryBlock(), and clang::ASTDeclReader::VisitFunctionDecl().
setVirtualAsWritten()
void clang::FunctionDecl::setVirtualAsWritten (bool V) inline
State that this function is marked as virtual explicitly.
Definition at line 2320 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and V.
Referenced by clang::TemplateDeclInstantiator::InitMethodInstantiation(), and clang::ASTDeclReader::VisitFunctionDecl().
setWillHaveBody()
void clang::FunctionDecl::setWillHaveBody (bool V = true) inline
Definition at line 2598 of file Decl.h.
References clang::DeclContext::FunctionDeclBits, and V.
Referenced by clang::Sema::SetDeclDeleted().
UsesFPIntrin()
bool clang::FunctionDecl::UsesFPIntrin () const inline
Determine whether the function was declared in source context that requires constrained FP intrinsics.
Definition at line 2820 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::CXXDestructorDecl::Create(), clang::CXXConversionDecl::Create(), clang::CXXConstructorDecl::Create(), clang::CXXMethodDecl::Create(), Create(), clang::CodeGen::CodeGenFunction::StartFunction(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
usesSEHTry()
bool clang::FunctionDecl::usesSEHTry () const inline
Indicates the function uses __try.
Definition at line 2482 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::CodeGen::EHPersonality::get(), clang::CodeGen::CodeGenFunction::StartFunction(), and clang::ASTDeclWriter::VisitFunctionDecl().
willHaveBody()
bool clang::FunctionDecl::willHaveBody () const inline
True if this function will eventually have a body, once it's fully parsed.
Definition at line 2597 of file Decl.h.
References clang::DeclContext::FunctionDeclBits.
Referenced by clang::Sema::DefineDefaultedComparison(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::CXXMethodDecl::hasInlineBody(), clang::Sema::InstantiateFunctionDefinition(), isInlineDefinitionExternallyVisible(), and isThisDeclarationADefinition().
Friends And Related Function Documentation
ASTDeclReader
friend class ASTDeclReader friend
Definition at line 2148 of file Decl.h.
ASTDeclWriter
friend class ASTDeclWriter friend
Definition at line 2149 of file Decl.h.
Member Data Documentation
Body
LazyDeclStmtPtr clang::FunctionDecl::Body
The body of the function.
Definition at line 2038 of file Decl.h.
Referenced by doesThisDeclarationHaveABody(), setBody(), setDefaultedOrDeletedInfo(), and setLazyBody().
DefaultedOrDeletedInfo
DefaultedOrDeletedFunctionInfo* clang::FunctionDecl::DefaultedOrDeletedInfo
Information about a future defaulted function definition.
Definition at line 2040 of file Decl.h.
Referenced by getDefalutedOrDeletedInfo(), getDeletedMessage(), setDefaultedOrDeletedInfo(), and setDeletedAsWritten().
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp