clang: clang::Scope Class Reference
clang::Scope Class Reference
Scope - A scope is a transient data structure that is used while parsing the program.
#include "clang/Sema/Scope.h"
Public Types
enum ScopeFlags {
NoScope = 0 , FnScope = 0x01 , BreakScope = 0x02 , ContinueScope = 0x04 ,
DeclScope = 0x08 , ControlScope = 0x10 , ClassScope = 0x20 , BlockScope = 0x40 ,
TemplateParamScope = 0x80 , FunctionPrototypeScope = 0x100 , FunctionDeclarationScope = 0x200 , AtCatchScope = 0x400 ,
ObjCMethodScope = 0x800 , SwitchScope = 0x1000 , TryScope = 0x2000 , FnTryCatchScope = 0x4000 ,
OpenMPDirectiveScope = 0x8000 , OpenMPLoopDirectiveScope = 0x10000 , OpenMPSimdDirectiveScope = 0x20000 , EnumScope = 0x40000 ,
SEHTryScope = 0x80000 , SEHExceptScope = 0x100000 , SEHFilterScope = 0x200000 , CompoundStmtScope = 0x400000 ,
ClassInheritanceScope = 0x800000 , CatchScope = 0x1000000 , ConditionVarScope = 0x2000000 , OpenMPOrderClauseScope = 0x4000000 ,
LambdaScope = 0x8000000 , OpenACCComputeConstructScope = 0x10000000 , TypeAliasScope = 0x20000000
}
ScopeFlags - These are bitfields that are or'd together when creating a scope, which defines the sorts of things the scope contains.
using decl_range = llvm::iterator_range< DeclSetTy::iterator >
using using_directives_range = llvm::iterator_range< UsingDirectivesTy::iterator >
Public Member Functions
Scope (Scope *Parent, unsigned ScopeFlags, DiagnosticsEngine &Diag)
unsigned getFlags () const
getFlags - Return the flags for this scope.
void setFlags (unsigned F)
bool isBlockScope () const
isBlockScope - Return true if this scope correspond to a closure.
const Scope * getParent () const
getParent - Return the scope that this is nested in.
Scope * getParent ()
const Scope * getFnParent () const
getFnParent - Return the closest scope that is a function body.
Scope * getFnParent ()
const Scope * getMSLastManglingParent () const
Scope * getMSLastManglingParent ()
Scope * getContinueParent ()
getContinueParent - Return the closest scope that a continue statement would be affected by.
const Scope * getContinueParent () const
void setIsConditionVarScope (bool InConditionVarScope)
bool isConditionVarScope () const
Scope * getBreakParent ()
getBreakParent - Return the closest scope that a break statement would be affected by.
const Scope * getBreakParent () const
Scope * getBlockParent ()
const Scope * getBlockParent () const
Scope * getTemplateParamParent ()
const Scope * getTemplateParamParent () const
Scope * getDeclParent ()
const Scope * getDeclParent () const
unsigned getDepth () const
Returns the depth of this scope. The translation-unit has scope depth 0.
unsigned getFunctionPrototypeDepth () const
Returns the number of function prototype scopes in this scope chain.
unsigned getNextFunctionPrototypeIndex ()
Return the number of parameters declared in this function prototype, increasing it by one for the next call.
decl_range decls () const
bool decl_empty () const
void AddDecl (Decl *D)
void RemoveDecl (Decl *D)
void incrementMSManglingNumber ()
void decrementMSManglingNumber ()
unsigned getMSLastManglingNumber () const
unsigned getMSCurManglingNumber () const
bool isDeclScope (const Decl *D) const
isDeclScope - Return true if this is the scope that the specified decl is declared in.
DeclContext * getEntity () const
Get the entity corresponding to this scope.
DeclContext * getLookupEntity () const
Get the DeclContext in which to continue unqualified lookup after a lookup in this scope.
void setEntity (DeclContext *E)
void setLookupEntity (DeclContext *E)
bool hasUnrecoverableErrorOccurred () const
Determine whether any unrecoverable errors have occurred within this scope.
bool isFunctionScope () const
isFunctionScope() - Return true if this scope is a function scope.
bool isClassScope () const
isClassScope - Return true if this scope is a class/struct/union scope.
bool isClassInheritanceScope () const
Determines whether this scope is between inheritance colon and the real class/struct definition.
bool isInCXXInlineMethodScope () const
isInCXXInlineMethodScope - Return true if this scope is a C++ inline method scope or is inside one.
bool isInObjcMethodScope () const
isInObjcMethodScope - Return true if this scope is, or is contained in, an Objective-C method body.
bool isInObjcMethodOuterScope () const
isInObjcMethodOuterScope - Return true if this scope is an Objective-C method outer most body.
bool isTemplateParamScope () const
isTemplateParamScope - Return true if this scope is a C++ template parameter scope.
bool isFunctionPrototypeScope () const
isFunctionPrototypeScope - Return true if this scope is a function prototype scope.
bool isFunctionDeclarationScope () const
isFunctionDeclarationScope - Return true if this scope is a function prototype scope.
bool isAtCatchScope () const
isAtCatchScope - Return true if this scope is @catch.
bool isCatchScope () const
isCatchScope - Return true if this scope is a C++ catch statement.
bool isSwitchScope () const
isSwitchScope - Return true if this scope is a switch scope.
bool isLoopScope () const
Return true if this scope is a loop.
bool isOpenMPDirectiveScope () const
Determines whether this scope is the OpenMP directive scope.
bool isOpenMPLoopDirectiveScope () const
Determine whether this scope is some OpenMP loop directive scope (for example, 'omp for', 'omp simd').
bool isOpenMPSimdDirectiveScope () const
Determine whether this scope is (or is nested into) some OpenMP loop simd directive scope (for example, 'omp simd', 'omp for simd').
bool isOpenMPLoopScope () const
Determine whether this scope is a loop having OpenMP loop directive attached.
bool isOpenMPOrderClauseScope () const
Determine whether this scope is some OpenMP directive with order clause which specifies concurrent scope.
bool isOpenACCComputeConstructScope () const
Determine whether this scope is the statement associated with an OpenACC Compute construct directive.
bool isInOpenACCComputeConstructScope (ScopeFlags Flags=NoScope) const
Determine if this scope (or its parents) are a compute construct.
bool isContinueScope () const
Determine whether this scope is a while/do/for statement, which can have continue statements embedded into it.
bool isTryScope () const
Determine whether this scope is a C++ 'try' block.
bool isFnTryCatchScope () const
Determine whether this scope is a function-level C++ try or catch scope.
bool isSEHTryScope () const
Determine whether this scope is a SEH '__try' block.
bool isSEHExceptScope () const
Determine whether this scope is a SEH '__except' block.
bool isCompoundStmtScope () const
Determine whether this scope is a compound statement scope.
bool isControlScope () const
Determine whether this scope is a controlling scope in a if/switch/while/for statement.
bool isTypeAliasScope () const
Determine whether this scope is a type alias scope.
bool Contains (const Scope &rhs) const
Returns if rhs has a higher scope depth than this.
bool containedInPrototypeScope () const
containedInPrototypeScope - Return true if this or a parent scope is a FunctionPrototypeScope.
void PushUsingDirective (UsingDirectiveDecl *UDir)
using_directives_range using_directives ()
void updateNRVOCandidate (VarDecl *VD)
void applyNRVO ()
void Init (Scope *parent, unsigned flags)
Init - This is used by the parser to implement scope caching.
void AddFlags (unsigned Flags)
Sets up the specified scope flags and adjusts the scope state variables accordingly.
void dumpImpl (raw_ostream &OS) const
void dump () const
Detailed Description
Scope - A scope is a transient data structure that is used while parsing the program.
It assists with resolving identifiers to the appropriate declaration.
Definition at line 41 of file Scope.h.
Member Typedef Documentation
decl_range
using clang::Scope::decl_range = llvm::iterator_range<DeclSetTy::iterator>
Definition at line 334 of file Scope.h.
using_directives_range
using clang::Scope::using_directives_range = llvm::iterator_range<UsingDirectivesTy::iterator>
Definition at line 603 of file Scope.h.
Member Enumeration Documentation
ScopeFlags
enum clang::Scope::ScopeFlags
ScopeFlags - These are bitfields that are or'd together when creating a scope, which defines the sorts of things the scope contains.
Enumerator
NoScope
FnScope
This indicates that the scope corresponds to a function, which means that labels are set here.
BreakScope
This is a while, do, switch, for, etc that can have break statements embedded into it.
ContinueScope
This is a while, do, for, which can have continue statements embedded into it.
DeclScope
This is a scope that can contain a declaration.
Some scopes just contain loop constructs but don't contain decls.
ControlScope
The controlling scope in a if/switch/while/for statement.
ClassScope
The scope of a struct/union/class definition.
BlockScope
This is a scope that corresponds to a block/closure object.
Blocks serve as top-level scopes for some objects like labels, they also prevent things like break and continue. BlockScopes always have the FnScope and DeclScope flags set as well.
TemplateParamScope
This is a scope that corresponds to the template parameters of a C++ template.
Template parameter scope starts at the 'template' keyword and ends when the template declaration ends.
FunctionPrototypeScope
This is a scope that corresponds to the parameters within a function prototype.
FunctionDeclarationScope
This is a scope that corresponds to the parameters within a function prototype for a function declaration (as opposed to any other kind of function declarator).
Always has FunctionPrototypeScope set as well.
AtCatchScope
This is a scope that corresponds to the Objective-C @catch statement.
ObjCMethodScope
This scope corresponds to an Objective-C method body.
It always has FnScope and DeclScope set as well.
SwitchScope
This is a scope that corresponds to a switch statement.
TryScope
This is the scope of a C++ try statement.
FnTryCatchScope
This is the scope for a function-level C++ try or catch scope.
OpenMPDirectiveScope
This is the scope of OpenMP executable directive.
OpenMPLoopDirectiveScope
This is the scope of some OpenMP loop directive.
OpenMPSimdDirectiveScope
This is the scope of some OpenMP simd directive.
For example, it is used for 'omp simd', 'omp for simd'. This flag is propagated to children scopes.
EnumScope
This scope corresponds to an enum.
SEHTryScope
This scope corresponds to an SEH try.
SEHExceptScope
This scope corresponds to an SEH except.
SEHFilterScope
We are currently in the filter expression of an SEH except block.
CompoundStmtScope
This is a compound statement scope.
ClassInheritanceScope
We are between inheritance colon and the real class/struct definition scope.
CatchScope
This is the scope of a C++ catch statement.
ConditionVarScope
This is a scope in which a condition variable is currently being parsed.
If such a scope is a ContinueScope, it's invalid to jump to the continue block from here.
OpenMPOrderClauseScope
This is a scope of some OpenMP directive with order clause which specifies concurrent.
LambdaScope
This is the scope for a lambda, after the lambda introducer.
Lambdas need two FunctionPrototypeScope scopes (because there is a template scope in between), the outer scope does not increase the depth of recursion.
OpenACCComputeConstructScope
This is the scope of an OpenACC Compute Construct, which restricts jumping into/out of it.
TypeAliasScope
This is a scope of type alias declaration.
Definition at line 45 of file Scope.h.
Constructor & Destructor Documentation
Scope()
clang::Scope::Scope (Scope * Parent, unsigned ScopeFlags, DiagnosticsEngine & Diag) inline
Definition at line 253 of file Scope.h.
References Init(), and Parent.
Referenced by CollectARMPACBTIOptions().
Member Function Documentation
AddDecl()
void clang::Scope::AddDecl (Decl * D) inline
Definition at line 342 of file Scope.h.
Referenced by clang::Sema::ActOnReenterTemplateScope().
AddFlags()
void Scope::AddFlags (unsigned Flags)
Sets up the specified scope flags and adjusts the scope state variables accordingly.
Definition at line 115 of file Scope.cpp.
References BreakScope, and ContinueScope.
applyNRVO()
void Scope::applyNRVO ()
Definition at line 165 of file Scope.cpp.
References getEntity(), getParent(), and isDeclScope().
containedInPrototypeScope()
bool Scope::containedInPrototypeScope () const
containedInPrototypeScope - Return true if this or a parent scope is a FunctionPrototypeScope.
Definition at line 105 of file Scope.cpp.
Contains()
bool clang::Scope::Contains (const Scope & rhs) const inline
Returns if rhs has a higher scope depth than this.
The caller is responsible for calling this only if one of the two scopes is an ancestor of the other.
Definition at line 593 of file Scope.h.
decl_empty()
bool clang::Scope::decl_empty () const inline
Definition at line 340 of file Scope.h.
decls()
decl_range clang::Scope::decls () const inline
Definition at line 336 of file Scope.h.
decrementMSManglingNumber()
void clang::Scope::decrementMSManglingNumber () inline
Definition at line 359 of file Scope.h.
References getMSLastManglingParent().
dump()
LLVM_DUMP_METHOD void Scope::dump () const
Definition at line 196 of file Scope.cpp.
References dumpImpl().
dumpImpl()
void Scope::dumpImpl (raw_ostream & OS) const
Definition at line 198 of file Scope.cpp.
References AtCatchScope, BlockScope, BreakScope, CatchScope, ClassInheritanceScope, ClassScope, CompoundStmtScope, ContinueScope, ControlScope, DeclScope, EnumScope, FnScope, FnTryCatchScope, FunctionDeclarationScope, FunctionPrototypeScope, getEntity(), getFlags(), getMSCurManglingNumber(), getMSLastManglingNumber(), getParent(), ObjCMethodScope, OpenACCComputeConstructScope, OpenMPDirectiveScope, OpenMPLoopDirectiveScope, OpenMPSimdDirectiveScope, Parent, SEHExceptScope, SEHFilterScope, SEHTryScope, SwitchScope, TemplateParamScope, and TryScope.
Referenced by dump().
getBlockParent() [1/2]
Scope* clang::Scope::getBlockParent () inline
Definition at line 309 of file Scope.h.
getBlockParent() [2/2]
const Scope* clang::Scope::getBlockParent () const inline
Definition at line 310 of file Scope.h.
getBreakParent() [1/2]
Scope* clang::Scope::getBreakParent () inline
getBreakParent - Return the closest scope that a break statement would be affected by.
Definition at line 302 of file Scope.h.
Referenced by getBreakParent().
getBreakParent() [2/2]
const Scope* clang::Scope::getBreakParent () const inline
Definition at line 305 of file Scope.h.
References getBreakParent().
getContinueParent() [1/2]
Scope* clang::Scope::getContinueParent () inline
getContinueParent - Return the closest scope that a continue statement would be affected by.
Definition at line 281 of file Scope.h.
Referenced by getContinueParent().
getContinueParent() [2/2]
const Scope* clang::Scope::getContinueParent () const inline
Definition at line 285 of file Scope.h.
References getContinueParent().
getDeclParent() [1/2]
Scope* clang::Scope::getDeclParent () inline
Definition at line 315 of file Scope.h.
getDeclParent() [2/2]
const Scope* clang::Scope::getDeclParent () const inline
Definition at line 316 of file Scope.h.
getDepth()
unsigned clang::Scope::getDepth () const inline
Returns the depth of this scope. The translation-unit has scope depth 0.
Definition at line 319 of file Scope.h.
getEntity()
DeclContext* clang::Scope::getEntity () const inline
Get the entity corresponding to this scope.
Definition at line 381 of file Scope.h.
References isTemplateParamScope().
Referenced by applyNRVO(), and dumpImpl().
getFlags()
unsigned clang::Scope::getFlags () const inline
getFlags - Return the flags for this scope.
Definition at line 259 of file Scope.h.
Referenced by clang::Sema::DiagnoseCommaOperator(), dumpImpl(), isAtCatchScope(), isCatchScope(), isClassInheritanceScope(), isClassScope(), isCompoundStmtScope(), isContinueScope(), isControlScope(), isFnTryCatchScope(), isFunctionDeclarationScope(), isFunctionPrototypeScope(), isFunctionScope(), isLoopScope(), isOpenACCComputeConstructScope(), isOpenMPDirectiveScope(), isOpenMPLoopDirectiveScope(), isOpenMPOrderClauseScope(), isOpenMPSimdDirectiveScope(), isSEHExceptScope(), isSEHTryScope(), isTemplateParamScope(), isTryScope(), and isTypeAliasScope().
getFnParent() [1/2]
Scope* clang::Scope::getFnParent () inline
Definition at line 272 of file Scope.h.
getFnParent() [2/2]
const Scope* clang::Scope::getFnParent () const inline
getFnParent - Return the closest scope that is a function body.
Definition at line 271 of file Scope.h.
Referenced by clang::Sema::ActOnReturnStmt(), and isInCXXInlineMethodScope().
getFunctionPrototypeDepth()
unsigned clang::Scope::getFunctionPrototypeDepth () const inline
Returns the number of function prototype scopes in this scope chain.
Definition at line 323 of file Scope.h.
getLookupEntity()
DeclContext* clang::Scope::getLookupEntity () const inline
Get the DeclContext in which to continue unqualified lookup after a lookup in this scope.
Definition at line 387 of file Scope.h.
getMSCurManglingNumber()
unsigned clang::Scope::getMSCurManglingNumber () const inline
Definition at line 372 of file Scope.h.
Referenced by dumpImpl().
getMSLastManglingNumber()
unsigned clang::Scope::getMSLastManglingNumber () const inline
Definition at line 366 of file Scope.h.
References getMSLastManglingParent().
Referenced by dumpImpl().
getMSLastManglingParent() [1/2]
Scope* clang::Scope::getMSLastManglingParent () inline
Definition at line 277 of file Scope.h.
getMSLastManglingParent() [2/2]
const Scope* clang::Scope::getMSLastManglingParent () const inline
Definition at line 274 of file Scope.h.
Referenced by decrementMSManglingNumber(), getMSLastManglingNumber(), and incrementMSManglingNumber().
getNextFunctionPrototypeIndex()
unsigned clang::Scope::getNextFunctionPrototypeIndex () inline
Return the number of parameters declared in this function prototype, increasing it by one for the next call.
Definition at line 329 of file Scope.h.
References isFunctionPrototypeScope().
getParent() [1/2]
Scope* clang::Scope::getParent () inline
Definition at line 268 of file Scope.h.
getParent() [2/2]
const Scope* clang::Scope::getParent () const inline
getParent - Return the scope that this is nested in.
Definition at line 267 of file Scope.h.
Referenced by clang::Sema::ActOnLambdaExpressionAfterIntroducer(), clang::Sema::ActOnObjCAtThrowStmt(), clang::Sema::ActOnSEHLeaveStmt(), clang::Sema::ActOnStartNamespaceDef(), clang::Sema::ActOnStartOfFunctionDef(), applyNRVO(), dumpImpl(), clang::Parser::ExitScope(), isOpenMPLoopScope(), and setFlags().
getTemplateParamParent() [1/2]
Scope* clang::Scope::getTemplateParamParent () inline
Definition at line 312 of file Scope.h.
Referenced by clang::Sema::ActOnLambdaExpressionAfterIntroducer().
getTemplateParamParent() [2/2]
const Scope* clang::Scope::getTemplateParamParent () const inline
Definition at line 313 of file Scope.h.
hasUnrecoverableErrorOccurred()
bool clang::Scope::hasUnrecoverableErrorOccurred () const inline
Determine whether any unrecoverable errors have occurred within this scope.
Note that this may return false even if the scope contains invalid declarations or statements, if the errors for those invalid constructs were suppressed because some prior invalid construct was referenced.
Definition at line 400 of file Scope.h.
References clang::DiagnosticErrorTrap::hasUnrecoverableErrorOccurred().
incrementMSManglingNumber()
void clang::Scope::incrementMSManglingNumber () inline
Definition at line 352 of file Scope.h.
References getMSLastManglingParent().
Referenced by clang::Sema::incrementMSManglingNumber().
Init()
void Scope::Init (Scope * parent, unsigned flags)
Init - This is used by the parser to implement scope caching.
Definition at line 95 of file Scope.cpp.
References clang::DiagnosticErrorTrap::reset().
Referenced by clang::Parser::EnterScope(), and Scope().
isAtCatchScope()
bool clang::Scope::isAtCatchScope () const inline
isAtCatchScope - Return true if this scope is @catch.
Definition at line 467 of file Scope.h.
References AtCatchScope, and getFlags().
Referenced by clang::Sema::ActOnObjCAtThrowStmt().
isBlockScope()
bool clang::Scope::isBlockScope () const inline
isBlockScope - Return true if this scope correspond to a closure.
Definition at line 264 of file Scope.h.
References BlockScope.
isCatchScope()
bool clang::Scope::isCatchScope () const inline
isCatchScope - Return true if this scope is a C++ catch statement.
Definition at line 472 of file Scope.h.
References CatchScope, and getFlags().
isClassInheritanceScope()
bool clang::Scope::isClassInheritanceScope () const inline
Determines whether this scope is between inheritance colon and the real class/struct definition.
Definition at line 412 of file Scope.h.
References ClassInheritanceScope, and getFlags().
isClassScope()
bool clang::Scope::isClassScope () const inline
isClassScope - Return true if this scope is a class/struct/union scope.
Definition at line 408 of file Scope.h.
References ClassScope, and getFlags().
isCompoundStmtScope()
bool clang::Scope::isCompoundStmtScope () const inline
Determine whether this scope is a compound statement scope.
Definition at line 578 of file Scope.h.
References CompoundStmtScope, and getFlags().
isConditionVarScope()
bool clang::Scope::isConditionVarScope () const inline
Definition at line 296 of file Scope.h.
References ConditionVarScope.
isContinueScope()
bool clang::Scope::isContinueScope () const inline
Determine whether this scope is a while/do/for statement, which can have continue statements embedded into it.
Definition at line 559 of file Scope.h.
References getFlags().
isControlScope()
bool clang::Scope::isControlScope () const inline
Determine whether this scope is a controlling scope in a if/switch/while/for statement.
Definition at line 584 of file Scope.h.
References ControlScope, and getFlags().
isDeclScope()
bool clang::Scope::isDeclScope (const Decl * D) const inline
isDeclScope - Return true if this is the scope that the specified decl is declared in.
Definition at line 378 of file Scope.h.
Referenced by applyNRVO().
isFnTryCatchScope()
bool clang::Scope::isFnTryCatchScope () const inline
Determine whether this scope is a function-level C++ try or catch scope.
Definition at line 567 of file Scope.h.
References getFlags().
isFunctionDeclarationScope()
bool clang::Scope::isFunctionDeclarationScope () const inline
isFunctionDeclarationScope - Return true if this scope is a function prototype scope.
Definition at line 462 of file Scope.h.
References FunctionDeclarationScope, and getFlags().
Referenced by GetDeclSpecTypeForDeclarator().
isFunctionPrototypeScope()
bool clang::Scope::isFunctionPrototypeScope () const inline
isFunctionPrototypeScope - Return true if this scope is a function prototype scope.
Definition at line 456 of file Scope.h.
References FunctionPrototypeScope, and getFlags().
Referenced by getNextFunctionPrototypeIndex().
isFunctionScope()
bool clang::Scope::isFunctionScope () const inline
isFunctionScope() - Return true if this scope is a function scope.
Definition at line 405 of file Scope.h.
References FnScope, and getFlags().
isInCXXInlineMethodScope()
bool clang::Scope::isInCXXInlineMethodScope () const inline
isInCXXInlineMethodScope - Return true if this scope is a C++ inline method scope or is inside one.
Definition at line 418 of file Scope.h.
References getFnParent().
isInObjcMethodOuterScope()
bool clang::Scope::isInObjcMethodOuterScope () const inline
isInObjcMethodOuterScope - Return true if this scope is an Objective-C method outer most body.
Definition at line 439 of file Scope.h.
isInObjcMethodScope()
bool clang::Scope::isInObjcMethodScope () const inline
isInObjcMethodScope - Return true if this scope is, or is contained in, an Objective-C method body.
Note that this method is not constant time.
Definition at line 428 of file Scope.h.
isInOpenACCComputeConstructScope()
bool clang::Scope::isInOpenACCComputeConstructScope (ScopeFlags Flags = NoScope) const inline
Determine if this scope (or its parents) are a compute construct.
If the argument is provided, the search will stop at any of the specified scopes. Otherwise, it will stop only at the normal 'no longer search' scopes.
Definition at line 540 of file Scope.h.
isLoopScope()
bool clang::Scope::isLoopScope () const inline
Return true if this scope is a loop.
Definition at line 489 of file Scope.h.
References BreakScope, getFlags(), and SwitchScope.
isOpenACCComputeConstructScope()
bool clang::Scope::isOpenACCComputeConstructScope () const inline
Determine whether this scope is the statement associated with an OpenACC Compute construct directive.
Definition at line 533 of file Scope.h.
References getFlags(), and OpenACCComputeConstructScope.
isOpenMPDirectiveScope()
bool clang::Scope::isOpenMPDirectiveScope () const inline
Determines whether this scope is the OpenMP directive scope.
Definition at line 497 of file Scope.h.
References getFlags(), and OpenMPDirectiveScope.
Referenced by isOpenMPLoopDirectiveScope().
isOpenMPLoopDirectiveScope()
bool clang::Scope::isOpenMPLoopDirectiveScope () const inline
Determine whether this scope is some OpenMP loop directive scope (for example, 'omp for', 'omp simd').
Definition at line 503 of file Scope.h.
References getFlags(), isOpenMPDirectiveScope(), and OpenMPLoopDirectiveScope.
isOpenMPLoopScope()
bool clang::Scope::isOpenMPLoopScope () const inline
Determine whether this scope is a loop having OpenMP loop directive attached.
Definition at line 520 of file Scope.h.
References getParent(), and P.
isOpenMPOrderClauseScope()
bool clang::Scope::isOpenMPOrderClauseScope () const inline
Determine whether this scope is some OpenMP directive with order clause which specifies concurrent scope.
Definition at line 527 of file Scope.h.
References getFlags(), and OpenMPOrderClauseScope.
Referenced by clang::SemaOpenMP::ActOnOpenMPCall().
isOpenMPSimdDirectiveScope()
bool clang::Scope::isOpenMPSimdDirectiveScope () const inline
Determine whether this scope is (or is nested into) some OpenMP loop simd directive scope (for example, 'omp simd', 'omp for simd').
Definition at line 514 of file Scope.h.
References getFlags(), and OpenMPSimdDirectiveScope.
isSEHExceptScope()
bool clang::Scope::isSEHExceptScope () const inline
Determine whether this scope is a SEH '__except' block.
Definition at line 575 of file Scope.h.
References getFlags(), and SEHExceptScope.
isSEHTryScope()
bool clang::Scope::isSEHTryScope () const inline
Determine whether this scope is a SEH '__try' block.
Definition at line 572 of file Scope.h.
References getFlags(), and SEHTryScope.
Referenced by clang::Sema::ActOnSEHLeaveStmt().
isSwitchScope()
bool clang::Scope::isSwitchScope () const inline
isSwitchScope - Return true if this scope is a switch scope.
Definition at line 475 of file Scope.h.
isTemplateParamScope()
bool clang::Scope::isTemplateParamScope () const inline
isTemplateParamScope - Return true if this scope is a C++ template parameter scope.
Definition at line 450 of file Scope.h.
References getFlags(), and TemplateParamScope.
Referenced by getEntity(), and setEntity().
isTryScope()
bool clang::Scope::isTryScope () const inline
Determine whether this scope is a C++ 'try' block.
Definition at line 564 of file Scope.h.
References getFlags(), and TryScope.
isTypeAliasScope()
bool clang::Scope::isTypeAliasScope () const inline
Determine whether this scope is a type alias scope.
Definition at line 587 of file Scope.h.
References getFlags(), and TypeAliasScope.
PushUsingDirective()
void clang::Scope::PushUsingDirective (UsingDirectiveDecl * UDir) inline
Definition at line 599 of file Scope.h.
RemoveDecl()
void clang::Scope::RemoveDecl (Decl * D) inline
Definition at line 350 of file Scope.h.
setEntity()
void clang::Scope::setEntity (DeclContext * E) inline
Definition at line 389 of file Scope.h.
References isTemplateParamScope().
setFlags()
void clang::Scope::setFlags (unsigned F) inline
Definition at line 261 of file Scope.h.
References getParent(), and setFlags().
Referenced by setFlags().
setIsConditionVarScope()
void clang::Scope::setIsConditionVarScope (bool InConditionVarScope) inline
Definition at line 291 of file Scope.h.
References ConditionVarScope.
setLookupEntity()
void clang::Scope::setLookupEntity (DeclContext * E) inline
Definition at line 394 of file Scope.h.
updateNRVOCandidate()
void Scope::updateNRVOCandidate (VarDecl * VD)
Definition at line 136 of file Scope.cpp.
Referenced by clang::Sema::ActOnReturnStmt().
using_directives()
using_directives_range clang::Scope::using_directives () inline
Definition at line 606 of file Scope.h.
The documentation for this class was generated from the following files:
include/clang/Sema/Scope.h
lib/Sema/Scope.cpp