clang: clang::ento::nonloc::LazyCompoundVal Class Reference
clang::ento::nonloc::LazyCompoundVal Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
Public Member Functions
LLVM_ATTRIBUTE_RETURNS_NONNULL const LazyCompoundValData * getCVData () const
const void * getStore () const
It might return null.
LLVM_ATTRIBUTE_RETURNS_NONNULL const TypedValueRegion * getRegion () const
Public Member Functions inherited from clang::ento::NonLoc
void dumpToStream (raw_ostream &Out) const
Public Member Functions inherited from clang::ento::DefinedSVal
bool isUnknown () const =delete
bool isUnknownOrUndef () const =delete
bool isValid () const =delete
Public Member Functions inherited from clang::ento::DefinedOrUnknownSVal
bool isUndef () const =delete
bool isValid () const =delete
Public Member Functions inherited from clang::ento::SVal
SVal ()=default
template<typename T >
T castAs () const
Convert to the specified SVal type, asserting that this SVal is of the desired type.
template<typename T >
std::optional< T > getAs () const
Convert to the specified SVal type, returning std::nullopt if this SVal is not of the desired type.
SValKind getKind () const
void Profile (llvm::FoldingSetNodeID &ID) const
bool operator== (SVal R) const
bool operator!= (SVal R) const
bool isUnknown () const
bool isUndef () const
bool isUnknownOrUndef () const
bool isValid () const
bool isConstant () const
bool isConstant (int I) const
bool isZeroConstant () const
const FunctionDecl * getAsFunctionDecl () const
getAsFunctionDecl - If this SVal is a MemRegionVal and wraps a CodeTextRegion wrapping a FunctionDecl, return that FunctionDecl.
SymbolRef getAsLocSymbol (bool IncludeBaseRegions=false) const
If this SVal is a location and wraps a symbol, return that SymbolRef.
SymbolRef getLocSymbolInBase () const
Get the symbol in the SVal or its base region.
SymbolRef getAsSymbol (bool IncludeBaseRegions=false) const
If this SVal wraps a symbol return that SymbolRef.
const llvm::APSInt * getAsInteger () const
If this SVal is loc::ConcreteInt or nonloc::ConcreteInt, return a pointer to APSInt which is held in it.
const MemRegion * getAsRegion () const
void printJson (raw_ostream &Out, bool AddQuotes) const
printJson - Pretty-prints in JSON format.
void dumpToStream (raw_ostream &OS) const
void dump () const
llvm::iterator_range< SymExpr::symbol_iterator > symbols () const
QualType getType (const ASTContext &) const
Try to get a reasonable type for the given value.
Static Public Member Functions
static bool classof (SVal V)
Static Public Member Functions inherited from clang::ento::NonLoc
static bool isCompoundType (QualType T)
static bool classof (SVal V)
Static Public Member Functions inherited from clang::ento::DefinedSVal
static bool classof (SVal V)
Static Public Member Functions inherited from clang::ento::DefinedOrUnknownSVal
static bool classof (SVal V)
Friends
class ento::SValBuilder
Additional Inherited Members
Public Types inherited from clang::ento::SVal
enum SValKind : unsigned char
Protected Member Functions inherited from clang::ento::NonLoc
NonLoc (SValKind Kind, const void *Data)
Protected Member Functions inherited from clang::ento::DefinedSVal
DefinedSVal (SValKind Kind, const void *Data)
Protected Member Functions inherited from clang::ento::DefinedOrUnknownSVal
DefinedOrUnknownSVal (SValKind Kind, const void *Data=nullptr)
Protected Member Functions inherited from clang::ento::SVal
SVal (SValKind Kind, const void *Data=nullptr)
template<typename T >
const T * castDataAs () const
Protected Attributes inherited from clang::ento::SVal
const void * Data = nullptr
SValKind Kind = UndefinedValKind
Detailed Description
Definition at line 349 of file SVals.h.
Member Function Documentation
classof()
static bool clang::ento::nonloc::LazyCompoundVal::classof (SVal V) inline static
Definition at line 369 of file SVals.h.
References V.
getCVData()
LLVM_ATTRIBUTE_RETURNS_NONNULL const LazyCompoundValData* clang::ento::nonloc::LazyCompoundVal::getCVData () const inline
Definition at line 359 of file SVals.h.
Referenced by clang::ento::ScanReachableSymbols::scan().
getRegion()
const TypedValueRegion * nonloc::LazyCompoundVal::getRegion () const
Definition at line 194 of file SVals.cpp.
References Data, and getRegion().
Referenced by clang::ento::StoreManager::getDefaultBinding(), hasVisibleUpdate(), and clang::ento::ScanReachableSymbols::scan().
getStore()
const void * nonloc::LazyCompoundVal::getStore () const
It might return null.
Definition at line 190 of file SVals.cpp.
References Data.
Referenced by clang::ento::StoreManager::getDefaultBinding(), and clang::ento::ScanReachableSymbols::scan().
Friends And Related Function Documentation
ento::SValBuilder
friend class ento::SValBuilder friend
Definition at line 350 of file SVals.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SVals.h
lib/StaticAnalyzer/Core/SVals.cpp