clang: clang::format::AnnotatedLine Class Reference
clang::format::AnnotatedLine Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Format/TokenAnnotator.h"
Public Member Functions
AnnotatedLine (const UnwrappedLine &Line)
void addChildren (const UnwrappedLineNode &Node, FormatToken *Current)
size_t size () const
~AnnotatedLine ()
bool isComment () const
template<typename... Ts>
bool startsWith (Ts... Tokens) const
true if this line starts with the given tokens in order, ignoring comments.
template<typename... Ts>
bool endsWith (Ts... Tokens) const
true if this line ends with the given tokens in reversed order, ignoring comments.
bool mightBeFunctionDefinition () const
true if this line looks like a function definition instead of a function declaration.
bool startsWithNamespace () const
true if this line starts a namespace definition.
FormatToken * getFirstNonComment () const
FormatToken * getLastNonComment () const
Public Attributes
FormatToken * First
FormatToken * Last
SmallVector< AnnotatedLine *, 0 > Children
LineType Type
unsigned Level
unsigned PPLevel
size_t MatchingOpeningBlockLineIndex
size_t MatchingClosingBlockLineIndex
bool InPPDirective
bool InPragmaDirective
bool InMacroBody
bool MustBeDeclaration
bool MightBeFunctionDecl
bool IsMultiVariableDeclStmt
bool ContainsMacroCall = false
True if this line contains a macro call for which an expansion exists.
bool Affected
True if this line should be formatted, i.e.
bool LeadingEmptyLinesAffected
True if the leading empty lines of this line intersect with one of the input ranges.
bool ChildrenAffected
True if one of this line's children intersects with an input range.
bool ReturnTypeWrapped
True if breaking after last attribute group in function return type.
bool IsContinuation
True if this line should be indented by ContinuationIndent in addition to the normal indention level.
unsigned FirstStartColumn
Detailed Description
Definition at line 45 of file TokenAnnotator.h.
Constructor & Destructor Documentation
AnnotatedLine()
clang::format::AnnotatedLine::AnnotatedLine (const UnwrappedLine & Line) inline
Definition at line 47 of file TokenAnnotator.h.
~AnnotatedLine()
clang::format::AnnotatedLine::~AnnotatedLine () inline
Definition at line 100 of file TokenAnnotator.h.
References Children.
Member Function Documentation
addChildren()
void clang::format::AnnotatedLine::addChildren (const UnwrappedLineNode & Node, FormatToken * Current) inline
Definition at line 83 of file TokenAnnotator.h.
endsWith()
template<typename... Ts> bool clang::format::AnnotatedLine::endsWith (Ts... Tokens) const inline
true if this line ends with the given tokens in reversed order, ignoring comments.
For example, given tokens [T1, T2, T3, ...], the function returns true if this line is like "... T3 T2 T1".
Definition at line 125 of file TokenAnnotator.h.
Referenced by mightBeFunctionDefinition().
getFirstNonComment()
FormatToken* clang::format::AnnotatedLine::getFirstNonComment () const inline
Definition at line 153 of file TokenAnnotator.h.
References First, clang::format::FormatToken::getNextNonComment(), and clang::format::FormatToken::is().
Referenced by clang::format::getFunctionName().
getLastNonComment()
FormatToken* clang::format::AnnotatedLine::getLastNonComment () const inline
Definition at line 158 of file TokenAnnotator.h.
References clang::format::FormatToken::getPreviousNonComment(), clang::format::FormatToken::is(), and Last.
isComment()
bool clang::format::AnnotatedLine::isComment () const inline
Definition at line 111 of file TokenAnnotator.h.
References First, clang::format::FormatToken::getNextNonComment(), and clang::format::FormatToken::is().
mightBeFunctionDefinition()
bool clang::format::AnnotatedLine::mightBeFunctionDefinition () const inline
true if this line looks like a function definition instead of a function declaration.
Asserts MightBeFunctionDecl.
Definition at line 131 of file TokenAnnotator.h.
References endsWith(), and MightBeFunctionDecl.
size()
size_t clang::format::AnnotatedLine::size () const inline
Definition at line 93 of file TokenAnnotator.h.
References Children.
Referenced by clang::format::isGoogScope().
startsWith()
template<typename... Ts> bool clang::format::AnnotatedLine::startsWith (Ts... Tokens) const inline
true if this line starts with the given tokens in order, ignoring comments.
Definition at line 117 of file TokenAnnotator.h.
Referenced by startsWithNamespace().
startsWithNamespace()
bool clang::format::AnnotatedLine::startsWithNamespace () const inline
true if this line starts a namespace definition.
Definition at line 147 of file TokenAnnotator.h.
References startsWith().
Member Data Documentation
Affected
bool clang::format::AnnotatedLine::Affected
True if this line should be formatted, i.e.
intersects directly or indirectly with one of the input ranges.
Definition at line 185 of file TokenAnnotator.h.
Children
SmallVector<AnnotatedLine *, 0> clang::format::AnnotatedLine::Children
Definition at line 166 of file TokenAnnotator.h.
Referenced by size(), and ~AnnotatedLine().
ChildrenAffected
bool clang::format::AnnotatedLine::ChildrenAffected
True if one of this line's children intersects with an input range.
Definition at line 192 of file TokenAnnotator.h.
ContainsMacroCall
bool clang::format::AnnotatedLine::ContainsMacroCall = false
True if this line contains a macro call for which an expansion exists.
Definition at line 181 of file TokenAnnotator.h.
First
FormatToken* clang::format::AnnotatedLine::First
Definition at line 163 of file TokenAnnotator.h.
Referenced by getFirstNonComment(), isComment(), clang::format::maxNestingDepth(), and clang::format::TokenAnnotator::setCommentLineLevels().
FirstStartColumn
unsigned clang::format::AnnotatedLine::FirstStartColumn
Definition at line 201 of file TokenAnnotator.h.
InMacroBody
bool clang::format::AnnotatedLine::InMacroBody
Definition at line 175 of file TokenAnnotator.h.
InPPDirective
bool clang::format::AnnotatedLine::InPPDirective
Definition at line 173 of file TokenAnnotator.h.
InPragmaDirective
bool clang::format::AnnotatedLine::InPragmaDirective
Definition at line 174 of file TokenAnnotator.h.
IsContinuation
bool clang::format::AnnotatedLine::IsContinuation
True if this line should be indented by ContinuationIndent in addition to the normal indention level.
Definition at line 199 of file TokenAnnotator.h.
IsMultiVariableDeclStmt
bool clang::format::AnnotatedLine::IsMultiVariableDeclStmt
Definition at line 178 of file TokenAnnotator.h.
Last
FormatToken* clang::format::AnnotatedLine::Last
Definition at line 164 of file TokenAnnotator.h.
Referenced by getLastNonComment().
LeadingEmptyLinesAffected
bool clang::format::AnnotatedLine::LeadingEmptyLinesAffected
True if the leading empty lines of this line intersect with one of the input ranges.
Definition at line 189 of file TokenAnnotator.h.
Level
unsigned clang::format::AnnotatedLine::Level
Definition at line 169 of file TokenAnnotator.h.
Referenced by clang::format::forEachToken(), and clang::format::TokenAnnotator::setCommentLineLevels().
MatchingClosingBlockLineIndex
size_t clang::format::AnnotatedLine::MatchingClosingBlockLineIndex
Definition at line 172 of file TokenAnnotator.h.
MatchingOpeningBlockLineIndex
size_t clang::format::AnnotatedLine::MatchingOpeningBlockLineIndex
Definition at line 171 of file TokenAnnotator.h.
MightBeFunctionDecl
bool clang::format::AnnotatedLine::MightBeFunctionDecl
Definition at line 177 of file TokenAnnotator.h.
Referenced by mightBeFunctionDefinition().
MustBeDeclaration
bool clang::format::AnnotatedLine::MustBeDeclaration
Definition at line 176 of file TokenAnnotator.h.
PPLevel
unsigned clang::format::AnnotatedLine::PPLevel
Definition at line 170 of file TokenAnnotator.h.
ReturnTypeWrapped
bool clang::format::AnnotatedLine::ReturnTypeWrapped
True if breaking after last attribute group in function return type.
Definition at line 195 of file TokenAnnotator.h.
Type
LineType clang::format::AnnotatedLine::Type
Definition at line 168 of file TokenAnnotator.h.
Referenced by clang::format::TokenAnnotator::setCommentLineLevels().
The documentation for this class was generated from the following file:
lib/Format/TokenAnnotator.h