clang: clang::DesignatedInitExpr::Designator Class Reference
clang::DesignatedInitExpr::Designator Class Reference
Represents a single C99 designator.
#include "clang/AST/Expr.h"
Public Member Functions
Designator ()
bool isFieldDesignator () const
bool isArrayDesignator () const
bool isArrayRangeDesignator () const
const IdentifierInfo * getFieldName () const
FieldDecl * getFieldDecl () const
void setFieldDecl (FieldDecl *FD)
SourceLocation getDotLoc () const
SourceLocation getFieldLoc () const
unsigned getArrayIndex () const
SourceLocation getLBracketLoc () const
SourceLocation getEllipsisLoc () const
SourceLocation getRBracketLoc () const
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceRange getSourceRange () const LLVM_READONLY
Static Public Member Functions
static Designator CreateFieldDesignator (const IdentifierInfo *FieldName, SourceLocation DotLoc, SourceLocation FieldLoc)
Creates a field designator.
static Designator CreateArrayDesignator (unsigned Index, SourceLocation LBracketLoc, SourceLocation RBracketLoc)
Creates an array designator.
static Designator CreateArrayRangeDesignator (unsigned Index, SourceLocation LBracketLoc, SourceLocation EllipsisLoc, SourceLocation RBracketLoc)
Creates a GNU array-range designator.
Detailed Description
Represents a single C99 designator.
Todo:
This class is infuriatingly similar to clang::Designator, but minor differences (storing indices vs. storing pointers) keep us from reusing it. Try harder, later, to rectify these differences.
Definition at line 5176 of file Expr.h.
Constructor & Destructor Documentation
Designator()
clang::DesignatedInitExpr::Designator::Designator () inline
Definition at line 5247 of file Expr.h.
Member Function Documentation
CreateArrayDesignator()
static Designator clang::DesignatedInitExpr::Designator::CreateArrayDesignator (unsigned Index, SourceLocation LBracketLoc, SourceLocation RBracketLoc) inline static
Creates an array designator.
Definition at line 5293 of file Expr.h.
Referenced by clang::ASTNodeImporter::import().
CreateArrayRangeDesignator()
static Designator clang::DesignatedInitExpr::Designator::CreateArrayRangeDesignator (unsigned Index, SourceLocation LBracketLoc, SourceLocation EllipsisLoc, SourceLocation RBracketLoc) inline static
Creates a GNU array-range designator.
Definition at line 5303 of file Expr.h.
Referenced by clang::ASTNodeImporter::import().
CreateFieldDesignator()
static Designator clang::DesignatedInitExpr::Designator::CreateFieldDesignator (const IdentifierInfo * FieldName, SourceLocation DotLoc, SourceLocation FieldLoc) inline static
Creates a field designator.
Definition at line 5257 of file Expr.h.
References FieldInfo.
Referenced by clang::ASTNodeImporter::import().
getArrayIndex()
unsigned clang::DesignatedInitExpr::Designator::getArrayIndex () const inline
Definition at line 5314 of file Expr.h.
References ArrayOrRangeInfo, isArrayDesignator(), and isArrayRangeDesignator().
Referenced by clang::DesignatedInitExpr::getArrayIndex(), clang::DesignatedInitExpr::getArrayRangeEnd(), clang::DesignatedInitExpr::getArrayRangeStart(), and clang::ASTNodeImporter::import().
getBeginLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getBeginLoc () const inline
Definition at line 5338 of file Expr.h.
References getDotLoc(), getFieldLoc(), getLBracketLoc(), isFieldDesignator(), and clang::SourceLocation::isInvalid().
Referenced by clang::DesignatedInitExpr::getDesignatorsSourceRange(), and getSourceRange().
getDotLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getDotLoc () const inline
Definition at line 5279 of file Expr.h.
References FieldInfo, and isFieldDesignator().
Referenced by ExpandAnonymousFieldDesignator(), getBeginLoc(), clang::DesignatedInitExpr::getBeginLoc(), and clang::ASTNodeImporter::import().
getEllipsisLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getEllipsisLoc () const inline
Definition at line 5326 of file Expr.h.
References ArrayOrRangeInfo, and isArrayRangeDesignator().
Referenced by clang::ASTNodeImporter::import().
getEndLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getEndLoc () const inline
Definition at line 5344 of file Expr.h.
References getFieldLoc(), getRBracketLoc(), and isFieldDesignator().
Referenced by getSourceRange().
getFieldDecl()
FieldDecl* clang::DesignatedInitExpr::Designator::getFieldDecl () const inline
Definition at line 5267 of file Expr.h.
References FieldInfo, and isFieldDesignator().
Referenced by getFieldName().
getFieldLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getFieldLoc () const inline
Definition at line 5284 of file Expr.h.
References FieldInfo, and isFieldDesignator().
Referenced by ExpandAnonymousFieldDesignator(), getBeginLoc(), clang::DesignatedInitExpr::getBeginLoc(), getEndLoc(), and clang::ASTNodeImporter::import().
getFieldName()
const IdentifierInfo * DesignatedInitExpr::Designator::getFieldName () const
Definition at line 4597 of file Expr.cpp.
References FieldInfo, getFieldDecl(), clang::NamedDecl::getIdentifier(), and isFieldDesignator().
Referenced by clang::ASTNodeImporter::import().
getLBracketLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getLBracketLoc () const inline
Definition at line 5320 of file Expr.h.
References ArrayOrRangeInfo, isArrayDesignator(), and isArrayRangeDesignator().
Referenced by getBeginLoc(), and clang::ASTNodeImporter::import().
getRBracketLoc()
SourceLocation clang::DesignatedInitExpr::Designator::getRBracketLoc () const inline
Definition at line 5332 of file Expr.h.
References ArrayOrRangeInfo, isArrayDesignator(), and isArrayRangeDesignator().
Referenced by getEndLoc(), and clang::ASTNodeImporter::import().
getSourceRange()
SourceRange clang::DesignatedInitExpr::Designator::getSourceRange () const inline
Definition at line 5348 of file Expr.h.
References getBeginLoc(), and getEndLoc().
Referenced by clang::DesignatedInitExpr::getDesignatorsSourceRange().
isArrayDesignator()
bool clang::DesignatedInitExpr::Designator::isArrayDesignator () const inline
Definition at line 5250 of file Expr.h.
Referenced by getArrayIndex(), clang::DesignatedInitExpr::getArrayIndex(), getLBracketLoc(), getRBracketLoc(), and clang::ASTNodeImporter::import().
isArrayRangeDesignator()
bool clang::DesignatedInitExpr::Designator::isArrayRangeDesignator () const inline
Definition at line 5251 of file Expr.h.
Referenced by getArrayIndex(), clang::DesignatedInitExpr::getArrayRangeEnd(), clang::DesignatedInitExpr::getArrayRangeStart(), getEllipsisLoc(), getLBracketLoc(), getRBracketLoc(), and clang::ASTNodeImporter::import().
isFieldDesignator()
bool clang::DesignatedInitExpr::Designator::isFieldDesignator () const inline
Definition at line 5249 of file Expr.h.
Referenced by getBeginLoc(), getDotLoc(), getEndLoc(), getFieldDecl(), getFieldLoc(), getFieldName(), clang::ASTNodeImporter::import(), and setFieldDecl().
setFieldDecl()
void clang::DesignatedInitExpr::Designator::setFieldDecl (FieldDecl * FD) inline
Definition at line 5274 of file Expr.h.
References FieldInfo, and isFieldDesignator().
Member Data Documentation
ArrayOrRangeInfo
struct ArrayOrRangeDesignatorInfo clang::DesignatedInitExpr::Designator::ArrayOrRangeInfo
An array or GNU array-range designator, e.g., "[9]" or "[10..15]".
Definition at line 5219 of file Expr.h.
Referenced by getArrayIndex(), getEllipsisLoc(), getLBracketLoc(), and getRBracketLoc().
FieldInfo
struct FieldDesignatorInfo clang::DesignatedInitExpr::Designator::FieldInfo
A field designator, e.g., ".x".
Definition at line 5219 of file Expr.h.
Referenced by CreateFieldDesignator(), getDotLoc(), getFieldDecl(), getFieldLoc(), getFieldName(), and setFieldDecl().
The documentation for this class was generated from the following files:
include/clang/AST/Expr.h
lib/AST/Expr.cpp