clang: clang::OverridingMethods Class Reference
clang::OverridingMethods Class Reference
The set of methods that override a given virtual method in each subobject where it occurs.
#include "clang/AST/CXXInheritance.h"
Public Types
using iterator = MapType::iterator
using const_iterator = MapType::const_iterator
using overriding_iterator = SmallVectorImpl< UniqueVirtualMethod >::iterator
using overriding_const_iterator = SmallVectorImpl< UniqueVirtualMethod >::const_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
unsigned size () const
void add (unsigned OverriddenSubobject, UniqueVirtualMethod Overriding)
void add (const OverridingMethods &Other)
void replaceAll (UniqueVirtualMethod Overriding)
Detailed Description
The set of methods that override a given virtual method in each subobject where it occurs.
The first part of the pair is the subobject in which the overridden virtual function occurs, while the second part of the pair is the virtual method that overrides it (including the subobject in which that virtual function occurs).
Definition at line 269 of file CXXInheritance.h.
Member Typedef Documentation
const_iterator
using clang::OverridingMethods::const_iterator = MapType::const_iterator
Definition at line 278 of file CXXInheritance.h.
iterator
using clang::OverridingMethods::iterator = MapType::iterator
Definition at line 277 of file CXXInheritance.h.
overriding_const_iterator
using clang::OverridingMethods::overriding_const_iterator = SmallVectorImpl<UniqueVirtualMethod>::const_iterator
Definition at line 290 of file CXXInheritance.h.
overriding_iterator
using clang::OverridingMethods::overriding_iterator = SmallVectorImpl<UniqueVirtualMethod>::iterator
Definition at line 288 of file CXXInheritance.h.
Member Function Documentation
add() [1/2]
void OverridingMethods::add (const OverridingMethods & Other)
Definition at line 472 of file CXXInheritance.cpp.
References add(), and clang::Other.
add() [2/2]
void OverridingMethods::add (unsigned OverriddenSubobject, UniqueVirtualMethod Overriding)
Definition at line 464 of file CXXInheritance.cpp.
Referenced by add().
begin() [1/2]
iterator clang::OverridingMethods::begin () inline
Definition at line 280 of file CXXInheritance.h.
Referenced by replaceAll().
begin() [2/2]
const_iterator clang::OverridingMethods::begin () const inline
Definition at line 281 of file CXXInheritance.h.
end() [1/2]
iterator clang::OverridingMethods::end () inline
Definition at line 282 of file CXXInheritance.h.
Referenced by replaceAll().
end() [2/2]
const_iterator clang::OverridingMethods::end () const inline
Definition at line 283 of file CXXInheritance.h.
replaceAll()
void OverridingMethods::replaceAll (UniqueVirtualMethod Overriding)
Definition at line 482 of file CXXInheritance.cpp.
References begin(), and end().
size()
unsigned clang::OverridingMethods::size () const inline
Definition at line 284 of file CXXInheritance.h.
The documentation for this class was generated from the following files:
include/clang/AST/CXXInheritance.h
lib/AST/CXXInheritance.cpp