clang: clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData > Class Template Reference
clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData > Class Template Reference
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getTypeofLoc () const
void setTypeofLoc (SourceLocation Loc)
SourceLocation getLParenLoc () const
void setLParenLoc (SourceLocation Loc)
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation Loc)
SourceRange getParensRange () const
void setParensRange (SourceRange range)
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, TypeofLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (Derived other)
TypeLoc getNextTypeLoc () const
const TypeClass * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
SourceLocation getTemplateKeywordLoc () const
Get the SourceLocation of the template keyword (if any).
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
void dump () const
void dump (llvm::raw_ostream &, const ASTContext &) const
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, TypeofLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
TypeofLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
template<class Derived, class TypeClass, class LocalData = TypeofLocInfo>
class clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >
Definition at line 1989 of file TypeLoc.h.
Member Function Documentation
getLocalSourceRange()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> SourceRange clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getLocalSourceRange () const inline
Definition at line 2025 of file TypeLoc.h.
References clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getRParenLoc(), and clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getTypeofLoc().
getLParenLoc()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> SourceLocation clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getLParenLoc () const inline
Definition at line 2000 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, TypeofLocInfo >::getLocalData(), and clang::TypeofLocInfo::LParenLoc.
Referenced by clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getParensRange().
getParensRange()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> SourceRange clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getParensRange () const inline
Definition at line 2016 of file TypeLoc.h.
References clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getLParenLoc(), and clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getRParenLoc().
getRParenLoc()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> SourceLocation clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getRParenLoc () const inline
Definition at line 2008 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, TypeofLocInfo >::getLocalData(), and clang::TypeofLocInfo::RParenLoc.
Referenced by clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getLocalSourceRange(), and clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getParensRange().
getTypeofLoc()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> SourceLocation clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getTypeofLoc () const inline
Definition at line 1992 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, TypeofLocInfo >::getLocalData(), and clang::TypeofLocInfo::TypeofLoc.
Referenced by clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::getLocalSourceRange().
initializeLocal()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> void clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::initializeLocal (ASTContext & Context, SourceLocation Loc) inline
Definition at line 2029 of file TypeLoc.h.
setLParenLoc()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> void clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::setLParenLoc (SourceLocation Loc) inline
Definition at line 2004 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, TypeofLocInfo >::getLocalData(), and clang::TypeofLocInfo::LParenLoc.
Referenced by clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::setParensRange().
setParensRange()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> void clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::setParensRange (SourceRange range) inline
Definition at line 2020 of file TypeLoc.h.
References clang::transformer::range(), clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::setLParenLoc(), and clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::setRParenLoc().
setRParenLoc()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> void clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::setRParenLoc (SourceLocation Loc) inline
Definition at line 2012 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, TypeofLocInfo >::getLocalData(), and clang::TypeofLocInfo::RParenLoc.
Referenced by clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::setParensRange().
setTypeofLoc()
template<class Derived , class TypeClass , class LocalData = TypeofLocInfo> void clang::TypeofLikeTypeLoc< Derived, TypeClass, LocalData >::setTypeofLoc (SourceLocation Loc) inline
Definition at line 1996 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, Derived, TypeClass, TypeofLocInfo >::getLocalData(), and clang::TypeofLocInfo::TypeofLoc.
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h