clang: clang::ModuleMapParser Class Reference
clang::ModuleMapParser Class Reference
Public Member Functions
ModuleMapParser (Lexer &L, SourceManager &SourceMgr, const TargetInfo *Target, DiagnosticsEngine &Diags, ModuleMap &Map, const FileEntry *ModuleMapFile, const DirectoryEntry *Directory, bool IsSystem)
bool parseModuleMapFile ()
Parse a module map file.
bool terminatedByDirective ()
SourceLocation getLocation ()
Detailed Description
Definition at line 1438 of file ModuleMap.cpp.
Constructor & Destructor Documentation
ModuleMapParser()
clang::ModuleMapParser::ModuleMapParser (Lexer & L, SourceManager & SourceMgr, const TargetInfo * Target, DiagnosticsEngine & Diags, ModuleMap & Map, const FileEntry * ModuleMapFile, const DirectoryEntry * Directory, bool IsSystem) inline explicit
Definition at line 1520 of file ModuleMap.cpp.
References clang::MMToken::clear(), and clang::Target.
Member Function Documentation
getLocation()
SourceLocation clang::ModuleMapParser::getLocation () inline
Definition at line 1534 of file ModuleMap.cpp.
References clang::MMToken::getLocation().
parseModuleMapFile()
bool ModuleMapParser::parseModuleMapFile ()
Parse a module map file.
module-map-file: module-declaration*
Definition at line 2977 of file ModuleMap.cpp.
References clang::MMToken::Comma, clang::MMToken::ConfigMacros, clang::MMToken::Conflict, clang::MMToken::EndOfFile, clang::MMToken::Exclaim, clang::MMToken::ExcludeKeyword, clang::MMToken::ExplicitKeyword, clang::MMToken::ExportAsKeyword, clang::MMToken::ExportKeyword, clang::MMToken::ExternKeyword, clang::MMToken::FrameworkKeyword, clang::MMToken::getLocation(), clang::MMToken::HeaderKeyword, clang::MMToken::Identifier, clang::MMToken::IntegerLiteral, clang::MMToken::Kind, clang::MMToken::LBrace, clang::MMToken::LinkKeyword, clang::MMToken::LSquare, clang::MMToken::ModuleKeyword, clang::MMToken::Period, clang::MMToken::PrivateKeyword, clang::MMToken::RBrace, clang::DiagnosticsEngine::Report(), clang::MMToken::RequiresKeyword, clang::MMToken::RSquare, clang::MMToken::Star, clang::MMToken::StringLiteral, clang::MMToken::TextualKeyword, clang::MMToken::UmbrellaKeyword, and clang::MMToken::UseKeyword.
terminatedByDirective()
bool clang::ModuleMapParser::terminatedByDirective () inline
Definition at line 1533 of file ModuleMap.cpp.
The documentation for this class was generated from the following file:
lib/Lex/ModuleMap.cpp