clang: clang::Sema::AlignPackInfo Class Reference
clang::Sema::AlignPackInfo Class Reference
#include "clang/Sema/Sema.h"
Public Types
enum Mode : unsigned char { Native, Natural, Packed, Mac68k }
Public Member Functions
AlignPackInfo (AlignPackInfo::Mode M, unsigned Num, bool IsXL)
AlignPackInfo (AlignPackInfo::Mode M, bool IsXL)
AlignPackInfo (bool IsXL)
AlignPackInfo ()
bool IsPackAttr () const
bool IsAlignAttr () const
Mode getAlignMode () const
unsigned getPackNumber () const
bool IsPackSet () const
bool IsXLStack () const
bool operator== (const AlignPackInfo &Info) const
bool operator!= (const AlignPackInfo &Info) const
Static Public Member Functions
static uint32_t getRawEncoding (const AlignPackInfo &Info)
static AlignPackInfo getFromRawEncoding (unsigned Encoding)
Detailed Description
Definition at line 665 of file Sema.h.
Member Enumeration Documentation
Mode
enum clang::Sema::AlignPackInfo::Mode : unsigned char
Enumerator
Native
Natural
Packed
Mac68k
Definition at line 669 of file Sema.h.
Constructor & Destructor Documentation
AlignPackInfo() [1/4]
clang::Sema::AlignPackInfo::AlignPackInfo (AlignPackInfo::Mode M, unsigned Num, bool IsXL) inline
Definition at line 672 of file Sema.h.
AlignPackInfo() [2/4]
clang::Sema::AlignPackInfo::AlignPackInfo (AlignPackInfo::Mode M, bool IsXL) inline
Definition at line 678 of file Sema.h.
AlignPackInfo() [3/4]
clang::Sema::AlignPackInfo::AlignPackInfo (bool IsXL) inline explicit
Definition at line 682 of file Sema.h.
AlignPackInfo() [4/4]
clang::Sema::AlignPackInfo::AlignPackInfo () inline
Definition at line 684 of file Sema.h.
Referenced by getFromRawEncoding().
Member Function Documentation
getAlignMode()
Mode clang::Sema::AlignPackInfo::getAlignMode () const inline
Definition at line 720 of file Sema.h.
Referenced by clang::Sema::ActOnPragmaPack(), clang::Sema::AddAlignmentAttributesForRecord(), and getRawEncoding().
getFromRawEncoding()
static AlignPackInfo clang::Sema::AlignPackInfo::getFromRawEncoding (unsigned Encoding) inline static
Definition at line 704 of file Sema.h.
References AlignPackInfo().
Referenced by clang::ASTReader::ReadAlignPackInfo().
getPackNumber()
unsigned clang::Sema::AlignPackInfo::getPackNumber () const inline
Definition at line 722 of file Sema.h.
Referenced by clang::Sema::ActOnPragmaPack(), clang::Sema::AddAlignmentAttributesForRecord(), and getRawEncoding().
getRawEncoding()
static uint32_t clang::Sema::AlignPackInfo::getRawEncoding (const AlignPackInfo & Info) inline static
Definition at line 689 of file Sema.h.
References getAlignMode(), getPackNumber(), IsPackAttr(), and IsXLStack().
Referenced by clang::ASTWriter::AddAlignPackInfo().
IsAlignAttr()
bool clang::Sema::AlignPackInfo::IsAlignAttr () const inline
Definition at line 718 of file Sema.h.
Referenced by clang::Sema::ActOnPragmaPack(), and clang::Sema::AddAlignmentAttributesForRecord().
IsPackAttr()
bool clang::Sema::AlignPackInfo::IsPackAttr () const inline
Definition at line 716 of file Sema.h.
Referenced by getRawEncoding().
IsPackSet()
bool clang::Sema::AlignPackInfo::IsPackSet () const inline
Definition at line 724 of file Sema.h.
Referenced by clang::Sema::ActOnPragmaPack(), and clang::Sema::AddAlignmentAttributesForRecord().
IsXLStack()
bool clang::Sema::AlignPackInfo::IsXLStack () const inline
Definition at line 730 of file Sema.h.
Referenced by getRawEncoding().
operator!=()
bool clang::Sema::AlignPackInfo::operator!= (const AlignPackInfo & Info) const inline
Definition at line 738 of file Sema.h.
operator==()
bool clang::Sema::AlignPackInfo::operator== (const AlignPackInfo & Info) const inline
Definition at line 732 of file Sema.h.
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h