clang: clang::OMPInclusiveClause Class Reference
clang::OMPInclusiveClause Class Reference final
This represents clause 'inclusive' in the '#pragma omp scan' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPVarListClause< OMPInclusiveClause >
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_const_iterator varlist_begin () const
varlist_iterator varlist_end ()
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPInclusiveClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< Expr * > VL)
Creates clause with a list of variables VL.
static OMPInclusiveClause * CreateEmpty (const ASTContext &C, unsigned N)
Creates an empty clause with the place for N variables.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPVarListClause< OMPInclusiveClause >
using varlist_iterator = MutableArrayRef< Expr * >::iterator
using varlist_const_iterator = ArrayRef< const Expr * >::iterator
using varlist_range = llvm::iterator_range< varlist_iterator >
using varlist_const_range = llvm::iterator_range< varlist_const_iterator >
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPVarListClause< OMPInclusiveClause >
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents clause 'inclusive' in the '#pragma omp scan' directive.
#pragma omp scan inclusive(a,b)
In this example directive '#pragma omp scan' has clause 'inclusive' with the variables 'a' and 'b'.
Definition at line 8087 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPInclusiveClause::children () inline
Definition at line 8132 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPInclusiveClause >::varlist_begin(), and clang::OMPVarListClause< OMPInclusiveClause >::varlist_end().
Referenced by children().
children() [2/2]
const_child_range clang::OMPInclusiveClause::children () const inline
Definition at line 8137 of file OpenMPClause.h.
References children().
classof()
static bool clang::OMPInclusiveClause::classof (const OMPClause * T) inline static
Definition at line 8149 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
Create()
OMPInclusiveClause * OMPInclusiveClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< Expr * > VL) static
Creates clause with a list of variables VL.
Parameters
C AST context.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
VL List of references to the original variables.
Definition at line 1460 of file OpenMPClause.cpp.
References clang::OMPVarListClause< T >::setVarRefs().
Referenced by clang::Sema::ActOnOpenMPInclusiveClause().
CreateEmpty()
OMPInclusiveClause * OMPInclusiveClause::CreateEmpty (const ASTContext & C, unsigned N) static
Creates an empty clause with the place for N variables.
Parameters
C AST context.
N The number of variables.
Definition at line 1472 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
used_children() [1/2]
child_range clang::OMPInclusiveClause::used_children () inline
Definition at line 8142 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPInclusiveClause::used_children () const inline
Definition at line 8145 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 8090 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp