clang: clang::ExtractAPIActionBase Class Reference
clang::ExtractAPIActionBase Class Reference
Base class to be used by front end actions to generate ExtarctAPI info.
#include "clang/ExtractAPI/ExtractAPIActionBase.h"
Protected Member Functions
void ImplEndSourceFileAction (CompilerInstance &CI)
Implements EndSourceFileAction for Symbol-Graph generation.
Protected Attributes
std::unique_ptr< extractapi::APISet > API
A representation of the APIs this action extracts.
std::unique_ptr< llvm::raw_pwrite_stream > OS
A stream to the main output file of this action.
std::string ProductName
The product this action is extracting API information for.
std::unique_ptr< llvm::MemoryBuffer > Buffer
The synthesized input buffer that contains all the provided input header files.
extractapi::APIIgnoresList IgnoresList
The list of symbols to ignore during serialization.
Detailed Description
Base class to be used by front end actions to generate ExtarctAPI info.
Deriving from this class equips an action with all the necessary tools to generate ExractAPI information in form of symbol-graphs
Definition at line 29 of file ExtractAPIActionBase.h.
Member Function Documentation
ImplEndSourceFileAction()
void ExtractAPIActionBase::ImplEndSourceFileAction (CompilerInstance & CI) protected
Implements EndSourceFileAction for Symbol-Graph generation.
Use the serializer to generate output symbol graph files from the information gathered during the execution of Action.
Definition at line 392 of file ExtractAPIConsumer.cpp.
References clang::extractapi::SymbolGraphSerializerOption::Compact, clang::FrontendOptions::EmitExtensionSymbolGraphs, clang::FrontendOptions::EmitPrettySymbolGraphs, clang::FrontendOptions::EmitSymbolGraphSymbolLabelsForTesting, clang::extractapi::SymbolGraphSerializerOption::EmitSymbolLabelsForTesting, clang::CompilerInstance::getFrontendOpts(), clang::extractapi::SymbolGraphSerializer::serializeMainSymbolGraph(), and clang::extractapi::SymbolGraphSerializer::serializeWithExtensionGraphs().
Member Data Documentation
API
std::unique_ptr<extractapi::APISet> clang::ExtractAPIActionBase::API protected
A representation of the APIs this action extracts.
Definition at line 32 of file ExtractAPIActionBase.h.
Buffer
std::unique_ptr<llvm::MemoryBuffer> clang::ExtractAPIActionBase::Buffer protected
The synthesized input buffer that contains all the provided input header files.
Definition at line 42 of file ExtractAPIActionBase.h.
IgnoresList
extractapi::APIIgnoresList clang::ExtractAPIActionBase::IgnoresList protected
The list of symbols to ignore during serialization.
Definition at line 45 of file ExtractAPIActionBase.h.
OS
std::unique_ptr<llvm::raw_pwrite_stream> clang::ExtractAPIActionBase::OS protected
A stream to the main output file of this action.
Definition at line 35 of file ExtractAPIActionBase.h.
ProductName
std::string clang::ExtractAPIActionBase::ProductName protected
The product this action is extracting API information for.
Definition at line 38 of file ExtractAPIActionBase.h.
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/ExtractAPIActionBase.h
lib/ExtractAPI/ExtractAPIConsumer.cpp