clang: clang::TypeLocReader Class Reference
clang::TypeLocReader Class Reference
Public Member Functions
TypeLocReader (ASTRecordReader &Reader, LocSeq *Seq)
void VisitFunctionTypeLoc (FunctionTypeLoc)
void VisitArrayTypeLoc (ArrayTypeLoc)
Public Member Functions inherited from clang::TypeLocVisitor< TypeLocReader >
void Visit (TypeLoc TyLoc)
void Visit (UnqualTypeLoc TyLoc)
void VisitTypeLoc (TypeLoc TyLoc)
Detailed Description
Definition at line 6754 of file ASTReader.cpp.
Constructor & Destructor Documentation
TypeLocReader()
clang::TypeLocReader::TypeLocReader (ASTRecordReader & Reader, LocSeq * Seq) inline
Definition at line 6776 of file ASTReader.cpp.
References clang::Seq.
Member Function Documentation
VisitArrayTypeLoc()
void TypeLocReader::VisitArrayTypeLoc (ArrayTypeLoc TL)
Definition at line 6848 of file ASTReader.cpp.
References clang::ArrayTypeLoc::setLBracketLoc(), clang::ArrayTypeLoc::setRBracketLoc(), and clang::ArrayTypeLoc::setSizeExpr().
VisitFunctionTypeLoc()
void TypeLocReader::VisitFunctionTypeLoc (FunctionTypeLoc TL)
Definition at line 6915 of file ASTReader.cpp.
References clang::FunctionTypeLoc::getNumParams(), clang::FunctionTypeLoc::setExceptionSpecRange(), clang::FunctionTypeLoc::setLocalRangeBegin(), clang::FunctionTypeLoc::setLocalRangeEnd(), clang::FunctionTypeLoc::setLParenLoc(), clang::FunctionTypeLoc::setParam(), and clang::FunctionTypeLoc::setRParenLoc().
The documentation for this class was generated from the following file:
lib/Serialization/ASTReader.cpp