clang: clang::APIntStorage Class Reference
clang::APIntStorage Class Reference
#include "clang/AST/APNumericStorage.h"
Public Member Functions
llvm::APInt getValue () const
void setValue (const ASTContext &C, const llvm::APInt &Val)
Detailed Description
Definition at line 51 of file APNumericStorage.h.
Member Function Documentation
getValue()
llvm::APInt clang::APIntStorage::getValue () const inline
Definition at line 53 of file APNumericStorage.h.
References clang::APNumericStorage::getIntValue().
Referenced by FindTypeTagExpr(), clang::EnumConstantDecl::getInitVal(), isIdenticalStmt(), clang::Expr::isNullPointerConstant(), clang::ento::SValBuilder::makeIntVal(), ValidDuplicateEnum(), clang::ASTNodeImporter::VisitFixedPointLiteral(), clang::JSONNodeDumper::VisitIntegerLiteral(), and clang::ASTNodeImporter::VisitIntegerLiteral().
setValue()
void clang::APIntStorage::setValue (const ASTContext & C, const llvm::APInt & Val) inline
Definition at line 54 of file APNumericStorage.h.
References clang::APNumericStorage::setIntValue().
Referenced by clang::FixedPointLiteral::FixedPointLiteral(), clang::IntegerLiteral::IntegerLiteral(), and clang::EnumConstantDecl::setInitVal().
The documentation for this class was generated from the following file:
include/clang/AST/APNumericStorage.h