clang: clang::Sema::FullExprArg Class Reference
clang::Sema::FullExprArg Class Reference
#include "clang/Sema/Sema.h"
Public Member Functions
FullExprArg ()
FullExprArg (Sema &actions)
ExprResult release ()
Expr * get () const
Expr * operator-> ()
Friends
class Sema
Detailed Description
Definition at line 5989 of file Sema.h.
Constructor & Destructor Documentation
FullExprArg() [1/2]
clang::Sema::FullExprArg::FullExprArg () inline
Definition at line 5991 of file Sema.h.
FullExprArg() [2/2]
clang::Sema::FullExprArg::FullExprArg (Sema & actions) inline
Definition at line 5992 of file Sema.h.
Member Function Documentation
get()
Expr* clang::Sema::FullExprArg::get () const inline
Definition at line 5996 of file Sema.h.
Referenced by clang::Sema::ActOnForStmt(), clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPDistScheduleClause(), clang::SemaOpenMP::ActOnOpenMPFilterClause(), clang::SemaOpenMP::ActOnOpenMPFinalClause(), clang::SemaOpenMP::ActOnOpenMPIfClause(), clang::SemaOpenMP::ActOnOpenMPNocontextClause(), clang::SemaOpenMP::ActOnOpenMPNovariantsClause(), clang::SemaOpenMP::ActOnOpenMPNumTeamsClause(), clang::SemaOpenMP::ActOnOpenMPNumThreadsClause(), clang::SemaOpenMP::ActOnOpenMPScheduleClause(), clang::SemaOpenMP::ActOnOpenMPThreadLimitClause(), clang::SemaOpenMP::ActOnOpenMPXDynCGroupMemClause(), and isNonNegativeIntegerValue().
operator->()
Expr* clang::Sema::FullExprArg::operator-> () inline
Definition at line 5998 of file Sema.h.
release()
ExprResult clang::Sema::FullExprArg::release () inline
Definition at line 5994 of file Sema.h.
Referenced by clang::Sema::ActOnForStmt().
Friends And Related Function Documentation
Sema
friend class Sema friend
Definition at line 6003 of file Sema.h.
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h