clang: clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys > Class Template Reference
clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys > Class Template Reference
StmtVisitorBase - This class implements a simple visitor for Stmt subclasses.
#include "clang/AST/StmtVisitor.h"
Public Member Functions
RetTy Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) RetTy VisitStmt(PTR(Stmt) Node
Public Attributes
ParamTys P { return RetTy()
Detailed Description
template<template< typename > class Ptr, typename ImplClass, typename RetTy = void, class... ParamTys>
class clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
StmtVisitorBase - This class implements a simple visitor for Stmt subclasses.
Since Expr derives from Stmt, this also includes support for visiting Exprs.
Definition at line 37 of file StmtVisitor.h.
Member Function Documentation
BINOP_FALLBACK()
template<template< typename > class Ptr, typename ImplClass , typename RetTy = void, class... ParamTys> clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::BINOP_FALLBACK (PtrMemD)
Visit()
template<template< typename > class Ptr, typename ImplClass , typename RetTy = void, class... ParamTys> RetTy clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::Visit (PTR(Stmt) S, ParamTys... P) inline
Definition at line 44 of file StmtVisitor.h.
Referenced by clang::TrivialFunctionAnalysisVisitor::checkArguments(), clang::TrivialFunctionAnalysisVisitor::IsFunctionTrivial(), clang::TrivialFunctionAnalysisVisitor::VisitBinaryOperator(), clang::TrivialFunctionAnalysisVisitor::VisitCXXBindTemporaryExpr(), clang::TrivialFunctionAnalysisVisitor::VisitCXXConstructExpr(), clang::TrivialFunctionAnalysisVisitor::VisitCXXDefaultArgExpr(), clang::TrivialFunctionAnalysisVisitor::VisitCXXMemberCallExpr(), clang::TrivialFunctionAnalysisVisitor::VisitExplicitCastExpr(), clang::TrivialFunctionAnalysisVisitor::VisitExprWithCleanups(), clang::TrivialFunctionAnalysisVisitor::VisitImplicitCastExpr(), clang::TrivialFunctionAnalysisVisitor::VisitInitListExpr(), clang::TrivialFunctionAnalysisVisitor::VisitMaterializeTemporaryExpr(), clang::TrivialFunctionAnalysisVisitor::VisitMemberExpr(), clang::TrivialFunctionAnalysisVisitor::VisitParenExpr(), clang::TrivialFunctionAnalysisVisitor::VisitReturnStmt(), and clang::TrivialFunctionAnalysisVisitor::VisitUnaryOperator().
Member Data Documentation
P
template<template< typename > class Ptr, typename ImplClass , typename RetTy = void, class... ParamTys> ParamTys clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >::P { return RetTy()
Definition at line 172 of file StmtVisitor.h.
Referenced by clang::TextNodeDumper::dumpBareTemplateName(), clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLambdaExpr(), clang::JSONNodeDumper::VisitObjCCategoryDecl(), clang::TextNodeDumper::VisitObjCCategoryDecl(), clang::JSONNodeDumper::VisitObjCInterfaceDecl(), clang::JSONNodeDumper::VisitObjCProtocolDecl(), clang::TextNodeDumper::VisitVarDecl(), and clang::JSONNodeDumper::VisitVarDecl().
The documentation for this class was generated from the following file:
include/clang/AST/StmtVisitor.h