clang: clang::ast_matchers::dynamic::internal::MatcherDescriptor Class Reference
clang::ast_matchers::dynamic::internal::MatcherDescriptor Class Reference abstract
Matcher descriptor interface.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/ASTMatchers/Dynamic/Marshallers.h"
Public Member Functions
virtual ~MatcherDescriptor ()=default
virtual VariantMatcher create (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics *Error) const =0
virtual ASTNodeKind nodeMatcherType () const
virtual bool isBuilderMatcher () const
virtual std::unique_ptr< MatcherDescriptor > buildMatcherCtor (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics *Error) const
virtual bool isVariadic () const =0
Returns whether the matcher is variadic.
virtual unsigned getNumArgs () const =0
Returns the number of arguments accepted by the matcher if not variadic.
virtual void getArgKinds (ASTNodeKind ThisKind, unsigned ArgNo, std::vector< ArgKind > &ArgKinds) const =0
Given that the matcher is being converted to type ThisKind, append the set of argument types accepted for argument ArgNo to ArgKinds.
virtual bool isConvertibleTo (ASTNodeKind Kind, unsigned *Specificity=nullptr, ASTNodeKind *LeastDerivedKind=nullptr) const =0
Returns whether this matcher is convertible to the given type.
virtual bool isPolymorphic () const
Returns whether the matcher will, given a matcher of any type T, yield a matcher of type T.
Detailed Description
Matcher descriptor interface.
Provides a create() method that constructs the matcher from the provided arguments, and various other methods for type introspection.
Definition at line 304 of file Marshallers.h.
Constructor & Destructor Documentation
~MatcherDescriptor()
virtual clang::ast_matchers::dynamic::internal::MatcherDescriptor::~MatcherDescriptor () virtual default
Member Function Documentation
buildMatcherCtor()
virtual std::unique_ptr<MatcherDescriptor> clang::ast_matchers::dynamic::internal::MatcherDescriptor::buildMatcherCtor (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics * Error) const inline virtual
Reimplemented in clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor.
Definition at line 317 of file Marshallers.h.
Referenced by clang::ast_matchers::dynamic::Registry::buildMatcherCtor().
create()
virtual VariantMatcher clang::ast_matchers::dynamic::internal::MatcherDescriptor::create (SourceRange NameRange, ArrayRef< ParserValue > Args, Diagnostics * Error) const pure virtual
Implemented in clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor, clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicOperatorMatcherDescriptor, clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >, clang::ast_matchers::dynamic::internal::OverloadedMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicFuncMatcherDescriptor, and clang::ast_matchers::dynamic::internal::FixedArgCountMatcherDescriptor.
Referenced by clang::ast_matchers::dynamic::Registry::constructMatcher().
getArgKinds()
virtual void clang::ast_matchers::dynamic::internal::MatcherDescriptor::getArgKinds (ASTNodeKind ThisKind, unsigned ArgNo, std::vector< ArgKind > & ArgKinds) const pure virtual
Given that the matcher is being converted to type ThisKind, append the set of argument types accepted for argument ArgNo to ArgKinds.
Implemented in clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor, clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor, clang::ast_matchers::dynamic::internal::VariadicOperatorMatcherDescriptor, clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >, clang::ast_matchers::dynamic::internal::OverloadedMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicFuncMatcherDescriptor, and clang::ast_matchers::dynamic::internal::FixedArgCountMatcherDescriptor.
getNumArgs()
virtual unsigned clang::ast_matchers::dynamic::internal::MatcherDescriptor::getNumArgs () const pure virtual
Returns the number of arguments accepted by the matcher if not variadic.
Implemented in clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor, clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicOperatorMatcherDescriptor, clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >, clang::ast_matchers::dynamic::internal::OverloadedMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicFuncMatcherDescriptor, and clang::ast_matchers::dynamic::internal::FixedArgCountMatcherDescriptor.
isBuilderMatcher()
virtual bool clang::ast_matchers::dynamic::internal::MatcherDescriptor::isBuilderMatcher () const inline virtual
Reimplemented in clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor.
Definition at line 314 of file Marshallers.h.
Referenced by clang::ast_matchers::dynamic::Registry::isBuilderMatcher().
isConvertibleTo()
virtual bool clang::ast_matchers::dynamic::internal::MatcherDescriptor::isConvertibleTo (ASTNodeKind Kind, unsigned * Specificity = nullptr, ASTNodeKind * LeastDerivedKind = nullptr) const pure virtual
Returns whether this matcher is convertible to the given type.
If it is so convertible, store in *Specificity a value corresponding to the "specificity" of the converted matcher to the given context, and in *LeastDerivedKind the least derived matcher kind which would result in the same matcher overload. Zero specificity indicates that this conversion would produce a trivial matcher that will either always or never match. Such matchers are excluded from code completion results.
Implemented in clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor, clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicOperatorMatcherDescriptor, clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >, clang::ast_matchers::dynamic::internal::OverloadedMatcherDescriptor, clang::ast_matchers::dynamic::internal::DynCastAllOfMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicFuncMatcherDescriptor, and clang::ast_matchers::dynamic::internal::FixedArgCountMatcherDescriptor.
isPolymorphic()
virtual bool clang::ast_matchers::dynamic::internal::MatcherDescriptor::isPolymorphic () const inline virtual
Returns whether the matcher will, given a matcher of any type T, yield a matcher of type T.
Reimplemented in clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor, and clang::ast_matchers::dynamic::internal::VariadicOperatorMatcherDescriptor.
Definition at line 349 of file Marshallers.h.
isVariadic()
virtual bool clang::ast_matchers::dynamic::internal::MatcherDescriptor::isVariadic () const pure virtual
Returns whether the matcher is variadic.
Variadic matchers can take any number of arguments, but they must be of the same type.
Implemented in clang::ast_matchers::dynamic::internal::MapAnyOfBuilderDescriptor, clang::ast_matchers::dynamic::internal::MapAnyOfMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicOperatorMatcherDescriptor, clang::ast_matchers::dynamic::internal::RegexMatcherDescriptor< ReturnType >, clang::ast_matchers::dynamic::internal::OverloadedMatcherDescriptor, clang::ast_matchers::dynamic::internal::VariadicFuncMatcherDescriptor, and clang::ast_matchers::dynamic::internal::FixedArgCountMatcherDescriptor.
nodeMatcherType()
virtual ASTNodeKind clang::ast_matchers::dynamic::internal::MatcherDescriptor::nodeMatcherType () const inline virtual
Reimplemented in clang::ast_matchers::dynamic::internal::DynCastAllOfMatcherDescriptor, and clang::ast_matchers::dynamic::internal::VariadicFuncMatcherDescriptor.
Definition at line 312 of file Marshallers.h.
Referenced by clang::ast_matchers::dynamic::Registry::nodeMatcherType().
The documentation for this class was generated from the following file:
lib/ASTMatchers/Dynamic/Marshallers.h