clang: clang::ento::loc::ConcreteInt Class Reference
clang::ento::loc::ConcreteInt Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
Public Member Functions
ConcreteInt (const llvm::APSInt &V)
const llvm::APSInt & getValue () const
SVal evalBinOp (BasicValueFactory &BasicVals, BinaryOperator::Opcode Op, const ConcreteInt &R) const
Public Member Functions inherited from clang::ento::Loc
void dumpToStream (raw_ostream &Out) const
Public Member Functions inherited from clang::ento::DefinedSVal
bool isUnknown () const =delete
bool isUnknownOrUndef () const =delete
bool isValid () const =delete
Public Member Functions inherited from clang::ento::DefinedOrUnknownSVal
bool isUndef () const =delete
bool isValid () const =delete
Public Member Functions inherited from clang::ento::SVal
SVal ()=default
template<typename T >
T castAs () const
Convert to the specified SVal type, asserting that this SVal is of the desired type.
template<typename T >
Optional< T > getAs () const
Convert to the specified SVal type, returning None if this SVal is not of the desired type.
unsigned getRawKind () const
BaseKind getBaseKind () const
unsigned getSubKind () const
void Profile (llvm::FoldingSetNodeID &ID) const
bool operator== (const SVal &R) const
bool operator!= (const SVal &R) const
bool isUnknown () const
bool isUndef () const
bool isUnknownOrUndef () const
bool isValid () const
bool isConstant () const
bool isConstant (int I) const
bool isZeroConstant () const
bool hasConjuredSymbol () const
hasConjuredSymbol - If this SVal wraps a conjured symbol, return true;
const FunctionDecl * getAsFunctionDecl () const
getAsFunctionDecl - If this SVal is a MemRegionVal and wraps a CodeTextRegion wrapping a FunctionDecl, return that FunctionDecl.
SymbolRef getAsLocSymbol (bool IncludeBaseRegions=false) const
If this SVal is a location and wraps a symbol, return that SymbolRef.
SymbolRef getLocSymbolInBase () const
Get the symbol in the SVal or its base region.
SymbolRef getAsSymbol (bool IncludeBaseRegions=false) const
If this SVal wraps a symbol return that SymbolRef.
const MemRegion * getAsRegion () const
void printJson (raw_ostream &Out, bool AddQuotes) const
printJson - Pretty-prints in JSON format.
void dumpToStream (raw_ostream &OS) const
void dump () const
SymExpr::symbol_iterator symbol_begin () const
SymExpr::symbol_iterator symbol_end () const
QualType getType (const ASTContext &) const
Try to get a reasonable type for the given value.
Friends
class SVal
Additional Inherited Members
Public Types inherited from clang::ento::SVal
enum BaseKind
enum { BaseBits = 2, BaseMask = 0b11 }
Static Public Member Functions inherited from clang::ento::Loc
static bool isLocType (QualType T)
Protected Member Functions inherited from clang::ento::Loc
Loc ()=default
Loc (unsigned SubKind, const void *D)
Protected Member Functions inherited from clang::ento::DefinedSVal
DefinedSVal ()=default
DefinedSVal (const void *d, bool isLoc, unsigned ValKind)
Protected Member Functions inherited from clang::ento::DefinedOrUnknownSVal
DefinedOrUnknownSVal ()=default
DefinedOrUnknownSVal (const void *d, bool isLoc, unsigned ValKind)
DefinedOrUnknownSVal (BaseKind k, void *D=nullptr)
Protected Member Functions inherited from clang::ento::SVal
SVal (const void *d, bool isLoc, unsigned ValKind)
SVal (BaseKind k, const void *D=nullptr)
Protected Attributes inherited from clang::ento::SVal
const void * Data = nullptr
unsigned Kind = 0
The lowest 2 bits are a BaseKind (0 – 3).
Detailed Description
Definition at line 647 of file SVals.h.
Constructor & Destructor Documentation
ConcreteInt()
clang::ento::loc::ConcreteInt::ConcreteInt (const llvm::APSInt & V) inline explicit
Definition at line 649 of file SVals.h.
Member Function Documentation
evalBinOp()
SVal loc::ConcreteInt::evalBinOp (BasicValueFactory & BasicVals, BinaryOperator::Opcode Op, const ConcreteInt & R) const
Definition at line 305 of file SVals.cpp.
References clang::ento::BasicValueFactory::evalAPSInt(), getValue(), getValue(), clang::BinaryOperator::isComparisonOp(), and clang::tooling::X().
getValue()
const llvm::APSInt& clang::ento::loc::ConcreteInt::getValue () const inline
Definition at line 651 of file SVals.h.
References clang::ento::SVal::Data.
Referenced by evalBinOp().
Friends And Related Function Documentation
SVal
friend class SVal friend
Definition at line 660 of file SVals.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SVals.h
lib/StaticAnalyzer/Core/SVals.cpp