clang: clang::ento::BasicValueFactory Class Reference
clang::ento::BasicValueFactory Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h"
Public Member Functions
BasicValueFactory (ASTContext &ctx, llvm::BumpPtrAllocator &Alloc)
~BasicValueFactory ()
ASTContext & getContext () const
const llvm::APSInt & getValue (const llvm::APSInt &X)
const llvm::APSInt & getValue (const llvm::APInt &X, bool isUnsigned)
const llvm::APSInt & getValue (uint64_t X, QualType T)
APSIntType getAPSIntType (QualType T) const
Returns the type of the APSInt used to store values of the given QualType.
const llvm::APSInt & Convert (const llvm::APSInt &To, const llvm::APSInt &From)
Convert - Create a new persistent APSInt with the same value as 'From' but with the bitwidth and signedness of 'To'.
const llvm::APSInt & Convert (QualType T, const llvm::APSInt &From)
const llvm::APSInt & Convert (APSIntType TargetType, const llvm::APSInt &From)
const llvm::APSInt & getIntValue (uint64_t X, bool isUnsigned)
const llvm::APSInt & getMaxValue (const llvm::APSInt &v)
const llvm::APSInt & getMinValue (const llvm::APSInt &v)
const llvm::APSInt & getMaxValue (QualType T)
const llvm::APSInt & getMinValue (QualType T)
const llvm::APSInt & getMaxValue (APSIntType T)
const llvm::APSInt & getMinValue (APSIntType T)
const llvm::APSInt & Add1 (const llvm::APSInt &V)
const llvm::APSInt & Sub1 (const llvm::APSInt &V)
const llvm::APSInt & getZeroWithTypeSize (QualType T)
const llvm::APSInt & getTruthValue (bool b, QualType T)
const llvm::APSInt & getTruthValue (bool b)
const CompoundValData * getCompoundValData (QualType T, llvm::ImmutableList< SVal > Vals)
const LazyCompoundValData * getLazyCompoundValData (const StoreRef &store, const TypedValueRegion *region)
const PointerToMemberData * getPointerToMemberData (const NamedDecl *ND, llvm::ImmutableList< const CXXBaseSpecifier * > L)
llvm::ImmutableList< SVal > getEmptySValList ()
llvm::ImmutableList< SVal > prependSVal (SVal X, llvm::ImmutableList< SVal > L)
llvm::ImmutableList< const CXXBaseSpecifier * > getEmptyCXXBaseList ()
llvm::ImmutableList< const CXXBaseSpecifier * > prependCXXBase (const CXXBaseSpecifier *CBS, llvm::ImmutableList< const CXXBaseSpecifier * > L)
const PointerToMemberData * accumCXXBase (llvm::iterator_range< CastExpr::path_const_iterator > PathRange, const nonloc::PointerToMember &PTM, const clang::CastKind &kind)
const llvm::APSInt * evalAPSInt (BinaryOperator::Opcode Op, const llvm::APSInt &V1, const llvm::APSInt &V2)
const std::pair< SVal, uintptr_t > & getPersistentSValWithData (const SVal &V, uintptr_t Data)
const std::pair< SVal, SVal > & getPersistentSValPair (const SVal &V1, const SVal &V2)
const SVal * getPersistentSVal (SVal X)
Detailed Description
Definition at line 107 of file BasicValueFactory.h.
Constructor & Destructor Documentation
BasicValueFactory()
clang::ento::BasicValueFactory::BasicValueFactory (ASTContext & ctx, llvm::BumpPtrAllocator & Alloc) inline
Definition at line 129 of file BasicValueFactory.h.
~BasicValueFactory()
BasicValueFactory::~BasicValueFactory ()
Definition at line 79 of file BasicValueFactory.cpp.
Member Function Documentation
accumCXXBase()
const PointerToMemberData * BasicValueFactory::accumCXXBase (llvm::iterator_range< CastExpr::path_const_iterator > PathRange, const nonloc::PointerToMember & PTM, const clang::CastKind & kind)
Definition at line 192 of file BasicValueFactory.cpp.
References clang::ento::PointerToMemberData::getCXXBaseList(), clang::ento::PointerToMemberData::getDeclaratorDecl(), getPointerToMemberData(), clang::ento::nonloc::PointerToMember::getPTMData(), hasNoRepeatedElements(), and prependCXXBase().
Add1()
const llvm::APSInt& clang::ento::BasicValueFactory::Add1 (const llvm::APSInt & V) inline
Definition at line 206 of file BasicValueFactory.h.
References V, and clang::tooling::X().
Convert() [1/3]
const llvm::APSInt& clang::ento::BasicValueFactory::Convert (APSIntType TargetType, const llvm::APSInt & From) inline
Definition at line 170 of file BasicValueFactory.h.
References clang::ento::APSIntType::convert().
Convert() [2/3]
const llvm::APSInt& clang::ento::BasicValueFactory::Convert (const llvm::APSInt & To, const llvm::APSInt & From) inline
Convert - Create a new persistent APSInt with the same value as 'From' but with the bitwidth and signedness of 'To'.
Definition at line 156 of file BasicValueFactory.h.
References clang::ento::APSIntType::convert().
Referenced by Convert(), and clang::ento::SMTConstraintManager::getSymVal().
Convert() [3/3]
const llvm::APSInt& clang::ento::BasicValueFactory::Convert (QualType T, const llvm::APSInt & From) inline
Definition at line 165 of file BasicValueFactory.h.
References Convert(), and getAPSIntType().
evalAPSInt()
const llvm::APSInt * BasicValueFactory::evalAPSInt (BinaryOperator::Opcode Op, const llvm::APSInt & V1, const llvm::APSInt & V2)
Definition at line 250 of file BasicValueFactory.cpp.
References clang::ASTContext::getLangOpts(), and getTruthValue().
Referenced by clang::ento::nonloc::ConcreteInt::evalBinOp(), clang::ento::loc::ConcreteInt::evalBinOp(), and clang::ento::SMTConstraintManager::getSymVal().
getAPSIntType()
APSIntType clang::ento::BasicValueFactory::getAPSIntType (QualType T) const inline
Returns the type of the APSInt used to store values of the given QualType.
Definition at line 142 of file BasicValueFactory.h.
References clang::Type::getAs(), clang::ASTContext::getIntWidth(), clang::Type::isIntegralOrEnumerationType(), clang::ento::Loc::isLocType(), and clang::Type::isSignedIntegerOrEnumerationType().
Referenced by clang::ento::iterator::assumeNoOverflow(), clang::ento::RangedConstraintManager::assumeSymInclusiveRange(), clang::ento::RangedConstraintManager::assumeSymRel(), Convert(), clang::ento::SValBuilder::evalCastSubKind(), getMaxValue(), getMinValue(), getValue(), and clang::ento::SValBuilder::simplifySymbolCast().
getCompoundValData()
const CompoundValData * BasicValueFactory::getCompoundValData (QualType T, llvm::ImmutableList< SVal > Vals)
Definition at line 126 of file BasicValueFactory.cpp.
References clang::ento::CompoundValData::Profile().
Referenced by clang::ento::SValBuilder::makeCompoundVal().
getContext()
ASTContext& clang::ento::BasicValueFactory::getContext () const inline
Definition at line 135 of file BasicValueFactory.h.
Referenced by clang::ento::SMTConstraintManager::assumeSym(), clang::ento::SMTConstraintManager::assumeSymInclusiveRange(), clang::ento::SMTConstraintManager::canReasonAbout(), clang::ento::SMTConstraintManager::checkNull(), and clang::ento::SMTConstraintManager::getSymVal().
getEmptyCXXBaseList()
llvm::ImmutableList<const CXXBaseSpecifier *> clang::ento::BasicValueFactory::getEmptyCXXBaseList () inline
Definition at line 250 of file BasicValueFactory.h.
getEmptySValList()
llvm::ImmutableList<SVal> clang::ento::BasicValueFactory::getEmptySValList () inline
Definition at line 242 of file BasicValueFactory.h.
Referenced by clang::ento::SValBuilder::makeZeroVal(), and clang::ento::ExprEngine::VisitInitListExpr().
getIntValue()
const llvm::APSInt& clang::ento::BasicValueFactory::getIntValue (uint64_t X, bool isUnsigned) inline
Definition at line 177 of file BasicValueFactory.h.
References clang::ASTContext::IntTy, clang::ASTContext::UnsignedIntTy, and clang::tooling::X().
Referenced by clang::ento::SValBuilder::makeIntVal().
getLazyCompoundValData()
const LazyCompoundValData * BasicValueFactory::getLazyCompoundValData (const StoreRef & store, const TypedValueRegion * region)
Definition at line 144 of file BasicValueFactory.cpp.
References clang::ento::LazyCompoundValData::Profile().
Referenced by clang::ento::SValBuilder::makeLazyCompoundVal().
getMaxValue() [1/3]
const llvm::APSInt& clang::ento::BasicValueFactory::getMaxValue (APSIntType T) inline
Definition at line 198 of file BasicValueFactory.h.
References clang::ento::APSIntType::getMaxValue().
getMaxValue() [2/3]
const llvm::APSInt& clang::ento::BasicValueFactory::getMaxValue (const llvm::APSInt & v) inline
Definition at line 182 of file BasicValueFactory.h.
References v.
Referenced by getMaxValue().
getMaxValue() [3/3]
const llvm::APSInt& clang::ento::BasicValueFactory::getMaxValue (QualType T) inline
Definition at line 190 of file BasicValueFactory.h.
References getAPSIntType(), and getMaxValue().
getMinValue() [1/3]
const llvm::APSInt& clang::ento::BasicValueFactory::getMinValue (APSIntType T) inline
Definition at line 202 of file BasicValueFactory.h.
References clang::ento::APSIntType::getMinValue().
getMinValue() [2/3]
const llvm::APSInt& clang::ento::BasicValueFactory::getMinValue (const llvm::APSInt & v) inline
Definition at line 186 of file BasicValueFactory.h.
References v.
Referenced by clang::ento::ProgramState::assumeInBound(), and getMinValue().
getMinValue() [3/3]
const llvm::APSInt& clang::ento::BasicValueFactory::getMinValue (QualType T) inline
Definition at line 194 of file BasicValueFactory.h.
References getAPSIntType(), and getMinValue().
getPersistentSVal()
const SVal * BasicValueFactory::getPersistentSVal (SVal X)
Definition at line 394 of file BasicValueFactory.cpp.
References getPersistentSValWithData(), and clang::tooling::X().
getPersistentSValPair()
const std::pair< SVal, SVal > & BasicValueFactory::getPersistentSValPair (const SVal & V1, const SVal & V2)
Definition at line 370 of file BasicValueFactory.cpp.
References P, and clang::ento::SVal::Profile().
getPersistentSValWithData()
const std::pair< SVal, uintptr_t > & BasicValueFactory::getPersistentSValWithData (const SVal & V, uintptr_t Data)
Definition at line 345 of file BasicValueFactory.cpp.
References P, and V.
Referenced by getPersistentSVal(), and clang::ento::SValBuilder::makeLocAsInteger().
getPointerToMemberData()
const PointerToMemberData * BasicValueFactory::getPointerToMemberData (const NamedDecl * ND, llvm::ImmutableList< const CXXBaseSpecifier * > L)
Definition at line 162 of file BasicValueFactory.cpp.
References clang::ento::PointerToMemberData::Profile().
Referenced by accumCXXBase().
getTruthValue() [1/2]
const llvm::APSInt& clang::ento::BasicValueFactory::getTruthValue (bool b) inline
Definition at line 228 of file BasicValueFactory.h.
References b, clang::ASTContext::getLogicalOperationType(), and getTruthValue().
getTruthValue() [2/2]
const llvm::APSInt& clang::ento::BasicValueFactory::getTruthValue (bool b, QualType T) inline
Definition at line 223 of file BasicValueFactory.h.
References b, clang::ASTContext::getIntWidth(), and clang::Type::isUnsignedIntegerOrEnumerationType().
Referenced by evalAPSInt(), getTruthValue(), and clang::ento::SValBuilder::makeTruthVal().
getValue() [1/3]
const llvm::APSInt & BasicValueFactory::getValue (const llvm::APInt & X, bool isUnsigned)
Definition at line 108 of file BasicValueFactory.cpp.
References V, and clang::tooling::X().
getValue() [2/3]
const llvm::APSInt & BasicValueFactory::getValue (const llvm::APSInt & X)
Definition at line 90 of file BasicValueFactory.cpp.
References P, and clang::tooling::X().
getValue() [3/3]
const llvm::APSInt & BasicValueFactory::getValue (uint64_t X, QualType T)
Definition at line 121 of file BasicValueFactory.cpp.
References getAPSIntType(), and clang::tooling::X().
getZeroWithTypeSize()
const llvm::APSInt& clang::ento::BasicValueFactory::getZeroWithTypeSize (QualType T) inline
Definition at line 218 of file BasicValueFactory.h.
References clang::ASTContext::getTypeSize(), and clang::Type::isScalarType().
Referenced by clang::ento::SValBuilder::evalCastSubKind(), and clang::ento::SValBuilder::makeNullWithType().
prependCXXBase()
llvm::ImmutableList<const CXXBaseSpecifier *> clang::ento::BasicValueFactory::prependCXXBase (const CXXBaseSpecifier * CBS, llvm::ImmutableList< const CXXBaseSpecifier * > L) inline
Definition at line 254 of file BasicValueFactory.h.
Referenced by accumCXXBase().
prependSVal()
llvm::ImmutableList<SVal> clang::ento::BasicValueFactory::prependSVal (SVal X, llvm::ImmutableList< SVal > L) inline
Definition at line 246 of file BasicValueFactory.h.
References clang::tooling::X().
Sub1()
const llvm::APSInt& clang::ento::BasicValueFactory::Sub1 (const llvm::APSInt & V) inline
Definition at line 212 of file BasicValueFactory.h.
References V, and clang::tooling::X().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h
lib/StaticAnalyzer/Core/BasicValueFactory.cpp