clang: clang::CodeGen::ReturnValueSlot Class Reference
clang::CodeGen::ReturnValueSlot Class Reference
ReturnValueSlot - Contains the address where the return value of a function can be stored, and whether the address is volatile or not.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCall.h"
Public Member Functions
ReturnValueSlot ()
ReturnValueSlot (Address Addr, bool IsVolatile, bool IsUnused=false, bool IsExternallyDestructed=false)
bool isNull () const
bool isVolatile () const
Address getValue () const
bool isUnused () const
bool isExternallyDestructed () const
Address getAddress () const
Detailed Description
ReturnValueSlot - Contains the address where the return value of a function can be stored, and whether the address is volatile or not.
Definition at line 355 of file CGCall.h.
Constructor & Destructor Documentation
ReturnValueSlot() [1/2]
clang::CodeGen::ReturnValueSlot::ReturnValueSlot () inline
Definition at line 367 of file CGCall.h.
ReturnValueSlot() [2/2]
clang::CodeGen::ReturnValueSlot::ReturnValueSlot (Address Addr, bool IsVolatile, bool IsUnused = false, bool IsExternallyDestructed = false) inline
Definition at line 369 of file CGCall.h.
Member Function Documentation
getAddress()
Address clang::CodeGen::ReturnValueSlot::getAddress () const inline
Definition at line 379 of file CGCall.h.
getValue()
Address clang::CodeGen::ReturnValueSlot::getValue () const inline
Definition at line 376 of file CGCall.h.
isExternallyDestructed()
bool clang::CodeGen::ReturnValueSlot::isExternallyDestructed () const inline
Definition at line 378 of file CGCall.h.
isNull()
bool clang::CodeGen::ReturnValueSlot::isNull () const inline
Definition at line 374 of file CGCall.h.
References clang::CodeGen::Address::isValid().
Referenced by clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), and clang::CodeGen::CodeGenFunction::EmitForwardingCallToLambda().
isUnused()
bool clang::CodeGen::ReturnValueSlot::isUnused () const inline
Definition at line 377 of file CGCall.h.
isVolatile()
bool clang::CodeGen::ReturnValueSlot::isVolatile () const inline
Definition at line 375 of file CGCall.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CGCall.h