clang: clang::interp::InterpState Class Reference
clang::interp::InterpState Class Reference final
Interpreter context.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/InterpState.h"
Public Member Functions
InterpState (State &Parent, Program &P, InterpStack &Stk, Context &Ctx, SourceMapper *M=nullptr)
~InterpState ()
InterpState (const InterpState &)=delete
InterpState & operator= (const InterpState &)=delete
Frame * getSplitFrame ()
Frame * getCurrentFrame () override
unsigned getCallStackDepth () override
const Frame * getBottomFrame () const override
Expr::EvalStatus & getEvalStatus () const override
ASTContext & getCtx () const override
bool checkingForUndefinedBehavior () const override
bool keepEvaluatingAfterFailure () const override
bool checkingPotentialConstantExpression () const override
bool noteUndefinedBehavior () override
bool inConstantContext () const
bool hasActiveDiagnostic () override
void setActiveDiagnostic (bool Flag) override
void setFoldFailureDiagnostic (bool Flag) override
bool hasPriorDiagnostic () override
bool reportOverflow (const Expr *E, const llvm::APSInt &Value)
Reports overflow and return true if evaluation should continue.
void deallocate (Block *B)
Deallocates a pointer.
SourceInfo getSource (const Function *F, CodePtr PC) const override
Delegates source mapping to the mapper.
Context & getContext () const
Public Member Functions inherited from clang::interp::State
virtual ~State ()
State ()=default
OptionalDiagnostic FFDiag (SourceLocation Loc, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
Diagnose that the evaluation could not be folded (FF => FoldFailure)
OptionalDiagnostic FFDiag (const Expr *E, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic FFDiag (const SourceInfo &SI, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic CCEDiag (SourceLocation Loc, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
Diagnose that the evaluation does not produce a C++11 core constant expression.
OptionalDiagnostic CCEDiag (const Expr *E, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic CCEDiag (const SourceInfo &SI, diag::kind DiagId=diag::note_invalid_subexpr_in_const_expr, unsigned ExtraNotes=0)
OptionalDiagnostic Note (SourceLocation Loc, diag::kind DiagId)
Add a note to a prior diagnostic.
void addNotes (ArrayRef< PartialDiagnosticAt > Diags)
Add a stack of notes to a prior diagnostic.
DiagnosticBuilder report (SourceLocation Loc, diag::kind DiagId)
Directly reports a diagnostic message.
const LangOptions & getLangOpts () const
Public Member Functions inherited from clang::interp::SourceMapper
virtual ~SourceMapper ()
const Expr * getExpr (const Function *F, CodePtr PC) const
Returns the expression if an opcode belongs to one, null otherwise.
SourceLocation getLocation (const Function *F, CodePtr PC) const
Returns the location from which an opcode originates.
SourceRange getRange (const Function *F, CodePtr PC) const
Public Attributes
Program & P
Reference to the module containing all bytecode.
InterpStack & Stk
Temporary stack.
Context & Ctx
Interpreter Context.
InterpFrame * Current = nullptr
The current frame.
Public Attributes inherited from clang::interp::State
bool InConstantContext = false
Whether or not we're in a context where the front end requires a constant value.
Detailed Description
Interpreter context.
Definition at line 35 of file InterpState.h.
Constructor & Destructor Documentation
InterpState() [1/2]
InterpState::InterpState (State & Parent, Program & P, InterpStack & Stk, Context & Ctx, SourceMapper * M = nullptr)
Definition at line 18 of file InterpState.cpp.
~InterpState()
InterpState::~InterpState ()
Definition at line 22 of file InterpState.cpp.
References Current.
InterpState() [2/2]
clang::interp::InterpState::InterpState (const InterpState &) delete
Member Function Documentation
checkingForUndefinedBehavior()
bool clang::interp::InterpState::checkingForUndefinedBehavior () const inline override virtual
Implements clang::interp::State.
Definition at line 62 of file InterpState.h.
References Parent.
checkingPotentialConstantExpression()
bool clang::interp::InterpState::checkingPotentialConstantExpression () const inline override virtual
Implements clang::interp::State.
Definition at line 68 of file InterpState.h.
References Parent.
deallocate()
void InterpState::deallocate (Block * B)
Deallocates a pointer.
Definition at line 48 of file InterpState.cpp.
References clang::interp::Block::data(), clang::interp::Block::getDescriptor(), clang::interp::Descriptor::getMetadataSize(), clang::interp::Block::getSize(), clang::interp::Block::hasPointers(), clang::interp::Block::invokeDtor(), clang::interp::Block::IsInitialized, memcpy(), clang::interp::Descriptor::MoveFn, and clang::interp::Block::rawData().
Referenced by clang::interp::InterpFrame::destroy(), and clang::interp::InterpFrame::~InterpFrame().
getBottomFrame()
const Frame* clang::interp::InterpState::getBottomFrame () const inline override virtual
Implements clang::interp::State.
Definition at line 51 of file InterpState.h.
References Parent.
getCallStackDepth()
unsigned clang::interp::InterpState::getCallStackDepth () inline override virtual
Implements clang::interp::State.
Definition at line 48 of file InterpState.h.
References Current, and clang::interp::InterpFrame::getDepth().
getContext()
Context& clang::interp::InterpState::getContext () const inline
Definition at line 99 of file InterpState.h.
References Ctx.
getCtx()
ASTContext& clang::interp::InterpState::getCtx () const inline override virtual
Implements clang::interp::State.
Definition at line 59 of file InterpState.h.
References Parent.
Referenced by clang::interp::InterpFrame::describe().
getCurrentFrame()
Frame * InterpState::getCurrentFrame () override virtual
Implements clang::interp::State.
Definition at line 36 of file InterpState.cpp.
References clang::interp::InterpFrame::Caller, Current, and clang::interp::State::getCurrentFrame().
getEvalStatus()
Expr::EvalStatus& clang::interp::InterpState::getEvalStatus () const inline override virtual
Implements clang::interp::State.
Definition at line 56 of file InterpState.h.
References Parent.
getSource()
SourceInfo clang::interp::InterpState::getSource (const Function * F, CodePtr PC) const inline override virtual
Delegates source mapping to the mapper.
Implements clang::interp::SourceMapper.
Definition at line 91 of file InterpState.h.
References clang::interp::Function::getSource(), and clang::interp::SourceMapper::getSource().
Referenced by clang::interp::InterpFrame::getSource().
getSplitFrame()
Frame* clang::interp::InterpState::getSplitFrame () inline
Definition at line 46 of file InterpState.h.
References Parent.
Referenced by clang::interp::InterpFrame::getCaller().
hasActiveDiagnostic()
bool clang::interp::InterpState::hasActiveDiagnostic () inline override virtual
Implements clang::interp::State.
Definition at line 75 of file InterpState.h.
References Parent.
hasPriorDiagnostic()
bool clang::interp::InterpState::hasPriorDiagnostic () inline override virtual
Implements clang::interp::State.
Definition at line 82 of file InterpState.h.
References Parent.
inConstantContext()
bool clang::interp::InterpState::inConstantContext () const inline
Definition at line 74 of file InterpState.h.
References Parent.
keepEvaluatingAfterFailure()
bool clang::interp::InterpState::keepEvaluatingAfterFailure () const inline override virtual
Implements clang::interp::State.
Definition at line 65 of file InterpState.h.
References Parent.
noteUndefinedBehavior()
bool clang::interp::InterpState::noteUndefinedBehavior () inline override virtual
Implements clang::interp::State.
Definition at line 71 of file InterpState.h.
References Parent.
Referenced by reportOverflow().
operator=()
InterpState& clang::interp::InterpState::operator= (const InterpState &) delete
reportOverflow()
bool InterpState::reportOverflow (const Expr * E, const llvm::APSInt & Value)
Reports overflow and return true if evaluation should continue.
Definition at line 42 of file InterpState.cpp.
References clang::interp::State::CCEDiag(), clang::Expr::getType(), and noteUndefinedBehavior().
setActiveDiagnostic()
void clang::interp::InterpState::setActiveDiagnostic (bool Flag) inline override virtual
Implements clang::interp::State.
Definition at line 76 of file InterpState.h.
References Parent.
setFoldFailureDiagnostic()
void clang::interp::InterpState::setFoldFailureDiagnostic (bool Flag) inline override virtual
Implements clang::interp::State.
Definition at line 79 of file InterpState.h.
References Parent.
Member Data Documentation
Ctx
Context& clang::interp::InterpState::Ctx
Interpreter Context.
Definition at line 115 of file InterpState.h.
Referenced by clang::interp::InterpFrame::describe(), and getContext().
Current
InterpFrame* clang::interp::InterpState::Current = nullptr
The current frame.
Definition at line 117 of file InterpState.h.
Referenced by getCallStackDepth(), getCurrentFrame(), and ~InterpState().
P
Program& clang::interp::InterpState::P
Reference to the module containing all bytecode.
Definition at line 111 of file InterpState.h.
Stk
InterpStack& clang::interp::InterpState::Stk
Temporary stack.
Definition at line 113 of file InterpState.h.
Referenced by clang::interp::EvalEmitter::jumpFalse(), clang::interp::EvalEmitter::jumpTrue(), and clang::interp::InterpFrame::popArgs().
The documentation for this class was generated from the following files:
lib/AST/Interp/InterpState.h
lib/AST/Interp/InterpState.cpp