clang: clang::PrettyDeclStackTraceEntry Class Reference
clang::PrettyDeclStackTraceEntry Class Reference
PrettyDeclStackTraceEntry - If a crash occurs in the parser while parsing something related to a declaration, include that declaration in the stack trace.
#include "clang/AST/PrettyDeclStackTrace.h"
Public Member Functions
PrettyDeclStackTraceEntry (ASTContext &Ctx, Decl *D, SourceLocation Loc, const char *Msg)
void print (raw_ostream &OS) const override
Detailed Description
PrettyDeclStackTraceEntry - If a crash occurs in the parser while parsing something related to a declaration, include that declaration in the stack trace.
Definition at line 29 of file PrettyDeclStackTrace.h.
Constructor & Destructor Documentation
PrettyDeclStackTraceEntry()
clang::PrettyDeclStackTraceEntry::PrettyDeclStackTraceEntry (ASTContext & Ctx, Decl * D, SourceLocation Loc, const char * Msg) inline
Definition at line 36 of file PrettyDeclStackTrace.h.
Member Function Documentation
print()
void PrettyDeclStackTraceEntry::print (raw_ostream & OS) const override
Definition at line 80 of file Decl.cpp.
References clang::Decl::getLocation(), clang::ASTContext::getPrintingPolicy(), clang::ASTContext::getSourceManager(), clang::SourceLocation::isValid(), and clang::SourceLocation::print().
The documentation for this class was generated from the following files:
include/clang/AST/PrettyDeclStackTrace.h
lib/AST/Decl.cpp