clang: clang::XRayFunctionFilter Class Reference
clang::XRayFunctionFilter Class Reference
#include "clang/Basic/XRayLists.h"
Public Types
enum class ImbueAttribute { NONE , ALWAYS , NEVER , ALWAYS_ARG1 }
Public Member Functions
XRayFunctionFilter (ArrayRef< std::string > AlwaysInstrumentPaths, ArrayRef< std::string > NeverInstrumentPaths, ArrayRef< std::string > AttrListPaths, SourceManager &SM)
~XRayFunctionFilter ()
ImbueAttribute shouldImbueFunction (StringRef FunctionName) const
ImbueAttribute shouldImbueFunctionsInFile (StringRef Filename, StringRef Category=StringRef()) const
ImbueAttribute shouldImbueLocation (SourceLocation Loc, StringRef Category=StringRef()) const
Detailed Description
Definition at line 29 of file XRayLists.h.
Member Enumeration Documentation
ImbueAttribute
enum clang::XRayFunctionFilter::ImbueAttribute strong
Enumerator
NONE
ALWAYS
NEVER
ALWAYS_ARG1
Definition at line 41 of file XRayLists.h.
Constructor & Destructor Documentation
XRayFunctionFilter()
XRayFunctionFilter::XRayFunctionFilter (ArrayRef< std::string > AlwaysInstrumentPaths, ArrayRef< std::string > NeverInstrumentPaths, ArrayRef< std::string > AttrListPaths, SourceManager & SM)
Definition at line 20 of file XRayLists.cpp.
~XRayFunctionFilter()
XRayFunctionFilter::~XRayFunctionFilter () default
Member Function Documentation
shouldImbueFunction()
XRayFunctionFilter::ImbueAttribute XRayFunctionFilter::shouldImbueFunction (StringRef FunctionName) const
Definition at line 35 of file XRayLists.cpp.
References ALWAYS, ALWAYS_ARG1, NEVER, and NONE.
shouldImbueFunctionsInFile()
XRayFunctionFilter::ImbueAttribute XRayFunctionFilter::shouldImbueFunctionsInFile (StringRef Filename, StringRef Category = StringRef()) const
Definition at line 57 of file XRayLists.cpp.
References ALWAYS, Category, Filename, NEVER, and NONE.
Referenced by shouldImbueLocation().
shouldImbueLocation()
XRayFunctionFilter::ImbueAttribute XRayFunctionFilter::shouldImbueLocation (SourceLocation Loc, StringRef Category = StringRef()) const
Definition at line 71 of file XRayLists.cpp.
References Category, clang::SourceManager::getFileLoc(), clang::SourceManager::getFilename(), clang::SourceLocation::isValid(), NONE, and shouldImbueFunctionsInFile().
The documentation for this class was generated from the following files:
include/clang/Basic/XRayLists.h
lib/Basic/XRayLists.cpp