clang: clang::analyze_format_string::LengthModifier Class Reference
clang::analyze_format_string::LengthModifier Class Reference
Represents the length modifier in a format string in scanf/printf.
#include "clang/AST/FormatString.h"
Public Types
enum Kind {
None, AsChar, AsShort, AsShortLong,
AsLong, AsLongLong, AsQuad, AsIntMax,
AsSizeT, AsPtrDiff, AsInt32, AsInt3264,
AsInt64, AsLongDouble, AsAllocate, AsMAllocate,
AsWide, AsWideChar = AsLong
}
Public Member Functions
LengthModifier ()
LengthModifier (const char *pos, Kind k)
const char * getStart () const
unsigned getLength () const
Kind getKind () const
void setKind (Kind k)
const char * toString () const
Detailed Description
Represents the length modifier in a format string in scanf/printf.
Definition at line 64 of file FormatString.h.
Member Enumeration Documentation
Kind
enum clang::analyze_format_string::LengthModifier::Kind
Enumerator
None
AsChar
AsShort
AsShortLong
AsLong
AsLongLong
AsQuad
AsIntMax
AsSizeT
AsPtrDiff
AsInt32
AsInt3264
AsInt64
AsLongDouble
AsAllocate
AsMAllocate
AsWide
AsWideChar
Definition at line 66 of file FormatString.h.
Constructor & Destructor Documentation
LengthModifier() [1/2]
clang::analyze_format_string::LengthModifier::LengthModifier () inline
Definition at line 87 of file FormatString.h.
LengthModifier() [2/2]
clang::analyze_format_string::LengthModifier::LengthModifier (const char * pos, Kind k) inline
Definition at line 89 of file FormatString.h.
Member Function Documentation
getKind()
Kind clang::analyze_format_string::LengthModifier::getKind () const inline
Definition at line 111 of file FormatString.h.
Referenced by clang::analyze_format_string::FormatSpecifier::getCorrectedLengthModifier(), clang::analyze_format_string::FormatSpecifier::hasStandardLengthConversionCombination(), clang::analyze_format_string::FormatSpecifier::hasStandardLengthModifier(), and clang::analyze_format_string::FormatSpecifier::hasValidLengthModifier().
getLength()
unsigned clang::analyze_format_string::LengthModifier::getLength () const inline
Definition at line 96 of file FormatString.h.
References AsChar, AsInt32, AsInt64, AsLongLong, and None.
getStart()
const char* clang::analyze_format_string::LengthModifier::getStart () const inline
Definition at line 92 of file FormatString.h.
setKind()
void clang::analyze_format_string::LengthModifier::setKind (Kind k) inline
Definition at line 112 of file FormatString.h.
Referenced by clang::analyze_format_string::FormatSpecifier::getCorrectedLengthModifier(), and clang::analyze_format_string::FormatSpecifier::namedTypeToLengthModifier().
toString()
const char * analyze_format_string::LengthModifier::toString () const
Definition at line 575 of file FormatString.cpp.
The documentation for this class was generated from the following files:
include/clang/AST/FormatString.h
lib/AST/FormatString.cpp