clang: clang::ento::BlockCounter Class Reference
clang::ento::BlockCounter Class Reference
An abstract data type used to count the number of times a given block has been visited along a path analyzed by CoreEngine.
#include "clang/StaticAnalyzer/Core/PathSensitive/BlockCounter.h"
Classes
class Factory
Public Member Functions
BlockCounter ()
unsigned getNumVisited (const StackFrameContext *CallSite, unsigned BlockID) const
Friends
class Factory
Detailed Description
An abstract data type used to count the number of times a given block has been visited along a path analyzed by CoreEngine.
Definition at line 29 of file BlockCounter.h.
Constructor & Destructor Documentation
BlockCounter()
clang::ento::BlockCounter::BlockCounter () inline
Definition at line 35 of file BlockCounter.h.
References Data.
Referenced by clang::ento::BlockCounter::Factory::GetEmptyCounter(), and clang::ento::BlockCounter::Factory::IncrementCount().
Member Function Documentation
getNumVisited()
unsigned BlockCounter::getNumVisited (const StackFrameContext * CallSite, unsigned BlockID) const
Definition at line 57 of file BlockCounter.cpp.
References GetMap(), and clang::T.
Referenced by clang::ento::BlockCounter::Factory::IncrementCount().
Friends And Related Function Documentation
Factory
friend class Factory friend
Definition at line 52 of file BlockCounter.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/BlockCounter.h
lib/StaticAnalyzer/Core/BlockCounter.cpp