clang: clang::ASTStmtWriter Class Reference
clang::ASTStmtWriter Class Reference
Public Member Functions
ASTStmtWriter (ASTWriter &Writer, ASTWriter::RecordData &Record)
ASTStmtWriter (const ASTStmtWriter &)=delete
uint64_t Emit ()
void AddTemplateKWAndArgsInfo (const ASTTemplateKWAndArgsInfo &ArgInfo, const TemplateArgumentLoc *Args)
void VisitStmt (Stmt *S)
Public Member Functions inherited from clang::StmtVisitorBase< std::add_pointer, ASTStmtWriter, void, ParamTys... >
void Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) void VisitStmt(PTR(Stmt) Node
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< std::add_pointer, ASTStmtWriter, void, ParamTys... >
ParamTys P
Detailed Description
Definition at line 32 of file ASTWriterStmt.cpp.
Constructor & Destructor Documentation
ASTStmtWriter() [1/2]
clang::ASTStmtWriter::ASTStmtWriter (ASTWriter & Writer, ASTWriter::RecordData & Record) inline
Definition at line 40 of file ASTWriterStmt.cpp.
ASTStmtWriter() [2/2]
clang::ASTStmtWriter::ASTStmtWriter (const ASTStmtWriter &) delete
Member Function Documentation
AddTemplateKWAndArgsInfo()
void ASTStmtWriter::AddTemplateKWAndArgsInfo (const ASTTemplateKWAndArgsInfo & ArgInfo, const TemplateArgumentLoc * Args)
Definition at line 62 of file ASTWriterStmt.cpp.
References clang::ASTRecordWriter::AddSourceLocation(), clang::ASTRecordWriter::AddTemplateArgumentLoc(), clang::ASTTemplateKWAndArgsInfo::LAngleLoc, clang::ASTTemplateKWAndArgsInfo::NumTemplateArgs, clang::ASTTemplateKWAndArgsInfo::RAngleLoc, and clang::ASTTemplateKWAndArgsInfo::TemplateKWLoc.
Emit()
uint64_t clang::ASTStmtWriter::Emit () inline
Definition at line 46 of file ASTWriterStmt.cpp.
References clang::ASTRecordWriter::EmitStmt(), and clang::serialization::STMT_NULL_PTR.
VisitStmt()
void ASTStmtWriter::VisitStmt (Stmt * S)
Definition at line 71 of file ASTWriterStmt.cpp.
The documentation for this class was generated from the following file:
lib/Serialization/ASTWriterStmt.cpp