clang: clang::RewriteBuffer Class Reference
clang::RewriteBuffer Class Reference
RewriteBuffer - As code is rewritten, SourceBuffer's from the original input with modifications get a new RewriteBuffer associated with them.
#include "clang/Rewrite/Core/RewriteBuffer.h"
Public Types
using iterator = RewriteRope::const_iterator
Public Member Functions
iterator begin () const
iterator end () const
unsigned size () const
void Initialize (const char *BufStart, const char *BufEnd)
Initialize - Start this rewrite buffer out with a copy of the unmodified input buffer.
void Initialize (StringRef Input)
raw_ostream & write (raw_ostream &Stream) const
Write to Stream the result of applying all changes to the original buffer.
void RemoveText (unsigned OrigOffset, unsigned Size, bool removeLineIfEmpty=false)
RemoveText - Remove the specified text.
void InsertText (unsigned OrigOffset, StringRef Str, bool InsertAfter=true)
InsertText - Insert some text at the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
void InsertTextBefore (unsigned OrigOffset, StringRef Str)
InsertTextBefore - Insert some text before the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
void InsertTextAfter (unsigned OrigOffset, StringRef Str)
InsertTextAfter - Insert some text at the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
void ReplaceText (unsigned OrigOffset, unsigned OrigLength, StringRef NewStr)
ReplaceText - This method replaces a range of characters in the input buffer with a new string.
Friends
class Rewriter
Detailed Description
RewriteBuffer - As code is rewritten, SourceBuffer's from the original input with modifications get a new RewriteBuffer associated with them.
The RewriteBuffer captures the modified text itself as well as information used to map between SourceLocation's in the original input and offsets in the RewriteBuffer. For example, if text is inserted into the buffer, any locations after the insertion point have to be mapped.
Definition at line 25 of file RewriteBuffer.h.
Member Typedef Documentation
iterator
using clang::RewriteBuffer::iterator = RewriteRope::const_iterator
Definition at line 35 of file RewriteBuffer.h.
Member Function Documentation
begin()
iterator clang::RewriteBuffer::begin () const inline
Definition at line 37 of file RewriteBuffer.h.
References clang::RewriteRope::begin().
Referenced by clang::Rewriter::getRewrittenText(), RemoveText(), and write().
end()
iterator clang::RewriteBuffer::end () const inline
Definition at line 38 of file RewriteBuffer.h.
References clang::RewriteRope::end().
Referenced by clang::Rewriter::getRewriteBufferFor(), RemoveText(), and write().
Initialize() [1/2]
void clang::RewriteBuffer::Initialize (const char * BufStart, const char * BufEnd) inline
Initialize - Start this rewrite buffer out with a copy of the unmodified input buffer.
Definition at line 43 of file RewriteBuffer.h.
References clang::RewriteRope::assign().
Referenced by Initialize().
Initialize() [2/2]
void clang::RewriteBuffer::Initialize (StringRef Input) inline
Definition at line 46 of file RewriteBuffer.h.
References Initialize().
InsertText()
void RewriteBuffer::InsertText (unsigned OrigOffset, StringRef Str, bool InsertAfter = true)
InsertText - Insert some text at the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
The text is inserted after the specified location.
Definition at line 111 of file Rewriter.cpp.
References clang::RewriteRope::insert().
Referenced by InsertTextAfter(), clang::Rewriter::InsertTextAfterToken(), and InsertTextBefore().
InsertTextAfter()
void clang::RewriteBuffer::InsertTextAfter (unsigned OrigOffset, StringRef Str) inline
InsertTextAfter - Insert some text at the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
The text is inserted after the specified location.
Definition at line 81 of file RewriteBuffer.h.
References InsertText().
Referenced by clang::html::AddLineNumbers(), clang::html::HighlightRange(), and clang::RewriteMacrosInInput().
InsertTextBefore()
void clang::RewriteBuffer::InsertTextBefore (unsigned OrigOffset, StringRef Str) inline
InsertTextBefore - Insert some text before the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
The text is inserted before the specified location. This is method is the same as InsertText with "InsertAfter == false".
Definition at line 74 of file RewriteBuffer.h.
References InsertText().
Referenced by AddLineNumber(), clang::html::AddLineNumbers(), clang::html::HighlightRange(), and clang::RewriteMacrosInInput().
RemoveText()
void RewriteBuffer::RemoveText (unsigned OrigOffset, unsigned Size, bool removeLineIfEmpty = false)
RemoveText - Remove the specified text.
Definition at line 57 of file Rewriter.cpp.
References begin(), end(), clang::RewriteRope::erase(), isWhitespaceExceptNL(), and clang::RewriteRope::size().
Referenced by clang::Rewriter::RemoveText().
ReplaceText()
void RewriteBuffer::ReplaceText (unsigned OrigOffset, unsigned OrigLength, StringRef NewStr)
ReplaceText - This method replaces a range of characters in the input buffer with a new string.
This is effectively a combined "remove/insert" operation.
This is effectively a combined "remove+insert" operation.
Definition at line 126 of file Rewriter.cpp.
References clang::RewriteRope::erase(), and clang::RewriteRope::insert().
Referenced by clang::html::EscapeText(), and clang::Rewriter::ReplaceText().
size()
unsigned clang::RewriteBuffer::size () const inline
Definition at line 39 of file RewriteBuffer.h.
References clang::RewriteRope::size().
write()
raw_ostream & RewriteBuffer::write (raw_ostream & Stream) const
Write to Stream the result of applying all changes to the original buffer.
Note that it isn't safe to use this function to overwrite memory mapped files in-place (PR17960). Consider using a higher-level utility such as Rewriter::overwriteChangedFiles() instead.
The original buffer is not actually changed.
Definition at line 33 of file Rewriter.cpp.
References begin(), end(), and clang::RopePieceBTreeIterator::MoveToNextPiece().
Referenced by clang::arcmt::MigrationProcess::applyTransform(), clang::FixItRewriter::WriteFixedFile(), and clang::FixItRewriter::WriteFixedFiles().
Friends And Related Function Documentation
Rewriter
friend class Rewriter friend
Definition at line 26 of file RewriteBuffer.h.
The documentation for this class was generated from the following files:
include/clang/Rewrite/Core/RewriteBuffer.h
lib/Rewrite/Rewriter.cpp