clang: clang::TypeConstraint Class Reference
clang::TypeConstraint Class Reference
Models the abbreviated syntax to constrain a template type parameter: template <convertible_to<string> T> void print(T object); ~~~~~~~~~~~~~~~~~~~~~~ Semantically, this adds an "immediately-declared constraint" with extra arg: requires convertible_to<T, string>
#include "clang/AST/ASTConcept.h"
Public Member Functions
TypeConstraint (ConceptReference *ConceptRef, Expr *ImmediatelyDeclaredConstraint)
Expr * getImmediatelyDeclaredConstraint () const
Get the immediately-declared constraint expression introduced by this type-constraint, that is - the constraint expression that is added to the associated constraints of the enclosing declaration in practice.
ConceptReference * getConceptReference () const
ConceptDecl * getNamedConcept () const
SourceLocation getConceptNameLoc () const
bool hasExplicitTemplateArgs () const
const ASTTemplateArgumentListInfo * getTemplateArgsAsWritten () const
SourceLocation getTemplateKWLoc () const
NamedDecl * getFoundDecl () const
const NestedNameSpecifierLoc & getNestedNameSpecifierLoc () const
const DeclarationNameInfo & getConceptNameInfo () const
void print (llvm::raw_ostream &OS, const PrintingPolicy &Policy) const
Detailed Description
Models the abbreviated syntax to constrain a template type parameter: template <convertible_to<string> T> void print(T object); ~~~~~~~~~~~~~~~~~~~~~~ Semantically, this adds an "immediately-declared constraint" with extra arg: requires convertible_to<T, string>
In the C++ grammar, a type-constraint is also used for auto types: convertible_to<string> auto X = ...; We do not model these as TypeConstraints, but AutoType(Loc) directly.
Definition at line 231 of file ASTConcept.h.
Constructor & Destructor Documentation
TypeConstraint()
clang::TypeConstraint::TypeConstraint (ConceptReference * ConceptRef, Expr * ImmediatelyDeclaredConstraint) inline
Definition at line 238 of file ASTConcept.h.
Member Function Documentation
getConceptNameInfo()
const DeclarationNameInfo& clang::TypeConstraint::getConceptNameInfo () const inline
Definition at line 278 of file ASTConcept.h.
References clang::ConceptReference::getConceptNameInfo().
Referenced by clang::Sema::SubstTypeConstraint().
getConceptNameLoc()
SourceLocation clang::TypeConstraint::getConceptNameLoc () const inline
Definition at line 256 of file ASTConcept.h.
References clang::ConceptReference::getConceptNameLoc().
getConceptReference()
ConceptReference* clang::TypeConstraint::getConceptReference () const inline
Definition at line 250 of file ASTConcept.h.
Referenced by clang::ASTContext::isSameTypeConstraint(), clang::Sema::SubstTypeConstraint(), and clang::ASTDeclWriter::VisitTemplateTypeParmDecl().
getFoundDecl()
NamedDecl* clang::TypeConstraint::getFoundDecl () const inline
Definition at line 272 of file ASTConcept.h.
References clang::ConceptReference::getFoundDecl().
getImmediatelyDeclaredConstraint()
Expr* clang::TypeConstraint::getImmediatelyDeclaredConstraint () const inline
Get the immediately-declared constraint expression introduced by this type-constraint, that is - the constraint expression that is added to the associated constraints of the enclosing declaration in practice.
Definition at line 246 of file ASTConcept.h.
Referenced by clang::ASTContext::isSameTypeConstraint(), clang::concepts::ExprRequirement::ReturnTypeRequirement::ReturnTypeRequirement(), clang::Sema::SubstTypeConstraint(), and clang::ASTDeclWriter::VisitTemplateTypeParmDecl().
getNamedConcept()
ConceptDecl* clang::TypeConstraint::getNamedConcept () const inline
Definition at line 254 of file ASTConcept.h.
References clang::ConceptReference::getNamedConcept().
Referenced by clang::ASTContext::isSameTypeConstraint(), and clang::Sema::SubstTypeConstraint().
getNestedNameSpecifierLoc()
const NestedNameSpecifierLoc& clang::TypeConstraint::getNestedNameSpecifierLoc () const inline
Definition at line 274 of file ASTConcept.h.
References clang::ConceptReference::getNestedNameSpecifierLoc().
Referenced by clang::Sema::SubstTypeConstraint().
getTemplateArgsAsWritten()
const ASTTemplateArgumentListInfo* clang::TypeConstraint::getTemplateArgsAsWritten () const inline
Definition at line 264 of file ASTConcept.h.
References clang::ConceptReference::getTemplateArgsAsWritten().
Referenced by clang::Sema::SubstTypeConstraint().
getTemplateKWLoc()
SourceLocation clang::TypeConstraint::getTemplateKWLoc () const inline
Definition at line 268 of file ASTConcept.h.
References clang::ConceptReference::getTemplateKWLoc().
hasExplicitTemplateArgs()
bool clang::TypeConstraint::hasExplicitTemplateArgs () const inline
Definition at line 260 of file ASTConcept.h.
References clang::ConceptReference::hasExplicitTemplateArgs().
print()
void clang::TypeConstraint::print (llvm::raw_ostream & OS, const PrintingPolicy & Policy) const inline
Definition at line 282 of file ASTConcept.h.
References clang::ConceptReference::print().
The documentation for this class was generated from the following file:
include/clang/AST/ASTConcept.h