clang: clang::ProfileList Class Reference
clang::ProfileList Class Reference
#include "clang/Basic/ProfileList.h"
Public Types
enum ExclusionType { Allow , Skip , Forbid }
Represents if an how something should be excluded from profiling.
Public Member Functions
ProfileList (ArrayRef< std::string > Paths, SourceManager &SM)
~ProfileList ()
bool isEmpty () const
ExclusionType getDefault (CodeGenOptions::ProfileInstrKind Kind) const
std::optional< ExclusionType > isFunctionExcluded (StringRef FunctionName, CodeGenOptions::ProfileInstrKind Kind) const
std::optional< ExclusionType > isLocationExcluded (SourceLocation Loc, CodeGenOptions::ProfileInstrKind Kind) const
std::optional< ExclusionType > isFileExcluded (StringRef FileName, CodeGenOptions::ProfileInstrKind Kind) const
Detailed Description
Definition at line 28 of file ProfileList.h.
Member Enumeration Documentation
ExclusionType
enum clang::ProfileList::ExclusionType
Represents if an how something should be excluded from profiling.
Enumerator
Allow
Profiling is allowed.
Skip
Profiling is skipped using the skipprofile attribute.
Forbid
Profiling is forbidden using the noprofile attribute.
Definition at line 31 of file ProfileList.h.
Constructor & Destructor Documentation
ProfileList()
ProfileList::ProfileList (ArrayRef< std::string > Paths, SourceManager & SM)
Definition at line 67 of file ProfileList.cpp.
~ProfileList()
ProfileList::~ProfileList () default
Member Function Documentation
getDefault()
ProfileList::ExclusionType ProfileList::getDefault (CodeGenOptions::ProfileInstrKind Kind) const
Definition at line 89 of file ProfileList.cpp.
References Allow, Forbid, getSectionName(), and Skip.
Referenced by clang::CodeGen::CodeGenModule::isFunctionBlockedByProfileList().
isEmpty()
bool clang::ProfileList::isEmpty () const inline
Definition at line 51 of file ProfileList.h.
Referenced by clang::CodeGen::CodeGenModule::isFunctionBlockedByProfileList().
isFileExcluded()
std::optional< ProfileList::ExclusionType > ProfileList::isFileExcluded (StringRef FileName, CodeGenOptions::ProfileInstrKind Kind) const
Definition at line 139 of file ProfileList.cpp.
References Allow, clang::FileName, Forbid, getSectionName(), and V.
Referenced by clang::CodeGen::CodeGenModule::isFunctionBlockedByProfileList(), and isLocationExcluded().
isFunctionExcluded()
std::optional< ProfileList::ExclusionType > ProfileList::isFunctionExcluded (StringRef FunctionName, CodeGenOptions::ProfileInstrKind Kind) const
Definition at line 119 of file ProfileList.cpp.
References Allow, Forbid, getSectionName(), and V.
Referenced by clang::CodeGen::CodeGenModule::isFunctionBlockedByProfileList().
isLocationExcluded()
std::optional< ProfileList::ExclusionType > ProfileList::isLocationExcluded (SourceLocation Loc, CodeGenOptions::ProfileInstrKind Kind) const
Definition at line 133 of file ProfileList.cpp.
References clang::SourceManager::getFileLoc(), clang::SourceManager::getFilename(), and isFileExcluded().
Referenced by clang::CodeGen::CodeGenModule::isFunctionBlockedByProfileList().
The documentation for this class was generated from the following files:
include/clang/Basic/ProfileList.h
lib/Basic/ProfileList.cpp