clang: clang::syntax::Arena Class Reference
clang::syntax::Arena Class Reference
A memory arena for syntax trees.
#include "clang/Tooling/Syntax/Tree.h"
Public Member Functions
Arena (SourceManager &SourceMgr, const LangOptions &LangOpts, const TokenBuffer &Tokens)
const SourceManager & getSourceManager () const
const LangOptions & getLangOptions () const
const TokenBuffer & getTokenBuffer () const
llvm::BumpPtrAllocator & getAllocator ()
Friends
class FactoryImpl
Detailed Description
A memory arena for syntax trees.
Also tracks the underlying token buffers, source manager, etc.
Definition at line 41 of file Tree.h.
Constructor & Destructor Documentation
Arena()
syntax::Arena::Arena (SourceManager & SourceMgr, const LangOptions & LangOpts, const TokenBuffer & Tokens)
Definition at line 36 of file Tree.cpp.
Member Function Documentation
getAllocator()
llvm::BumpPtrAllocator& clang::syntax::Arena::getAllocator () inline
Definition at line 50 of file Tree.h.
Referenced by clang::syntax::TreeBuilder::allocator().
getLangOptions()
const LangOptions& clang::syntax::Arena::getLangOptions () const inline
Definition at line 47 of file Tree.h.
getSourceManager()
const SourceManager& clang::syntax::Arena::getSourceManager () const inline
Definition at line 46 of file Tree.h.
Referenced by clang::syntax::computeReplacements(), clang::syntax::deepCopyExpandingMacros(), clang::syntax::TreeBuilder::getRange(), and clang::syntax::TreeBuilder::sourceManager().
getTokenBuffer()
const syntax::TokenBuffer & syntax::Arena::getTokenBuffer () const
Definition at line 40 of file Tree.cpp.
Referenced by clang::syntax::computeReplacements(), and clang::syntax::TreeBuilder::TreeBuilder().
Friends And Related Function Documentation
FactoryImpl
friend class FactoryImpl friend
Definition at line 58 of file Tree.h.
The documentation for this class was generated from the following files:
include/clang/Tooling/Syntax/Tree.h
lib/Tooling/Syntax/Tree.cpp