clang: clang::format::IndexedTokenSource Class Reference
clang::format::IndexedTokenSource Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Format/FormatTokenSource.h"
Public Member Functions
IndexedTokenSource (ArrayRef< FormatToken * > Tokens)
FormatToken * getNextToken () override
FormatToken * getPreviousToken () override
FormatToken * peekNextToken (bool SkipComment=false) override
bool isEOF () override
unsigned getPosition () override
FormatToken * setPosition (unsigned P) override
FormatToken * insertTokens (ArrayRef< FormatToken * > New) override
void reset ()
Public Member Functions inherited from clang::format::FormatTokenSource
virtual ~FormatTokenSource ()
FormatToken * getNextNonComment ()
Detailed Description
Definition at line 86 of file FormatTokenSource.h.
Constructor & Destructor Documentation
IndexedTokenSource()
clang::format::IndexedTokenSource::IndexedTokenSource (ArrayRef< FormatToken * > Tokens) inline
Definition at line 88 of file FormatTokenSource.h.
Member Function Documentation
getNextToken()
FormatToken* clang::format::IndexedTokenSource::getNextToken () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 91 of file FormatTokenSource.h.
References isEOF().
getPosition()
unsigned clang::format::IndexedTokenSource::getPosition () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 130 of file FormatTokenSource.h.
getPreviousToken()
FormatToken* clang::format::IndexedTokenSource::getPreviousToken () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 107 of file FormatTokenSource.h.
References clang::comments::tok::eof.
insertTokens()
FormatToken* clang::format::IndexedTokenSource::insertTokens (ArrayRef< FormatToken * > New) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 142 of file FormatTokenSource.h.
References clang::comments::tok::eof.
isEOF()
bool clang::format::IndexedTokenSource::isEOF () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 126 of file FormatTokenSource.h.
References clang::comments::tok::eof, and false.
Referenced by getNextToken(), and peekNextToken().
peekNextToken()
FormatToken* clang::format::IndexedTokenSource::peekNextToken (bool SkipComment = false) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 112 of file FormatTokenSource.h.
References isEOF().
reset()
void clang::format::IndexedTokenSource::reset () inline
Definition at line 163 of file FormatTokenSource.h.
Referenced by clang::format::UnwrappedLineParser::parse().
setPosition()
FormatToken* clang::format::IndexedTokenSource::setPosition (unsigned P) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 136 of file FormatTokenSource.h.
References P.
The documentation for this class was generated from the following file:
lib/Format/FormatTokenSource.h