clang: clang::InitializedEntity Class Reference
clang::InitializedEntity Class Reference
Describes an entity that is being initialized.
#include "clang/Sema/Initialization.h"
Public Types
enum EntityKind {
EK_Variable, EK_Parameter, EK_TemplateParameter, EK_Result,
EK_StmtExprResult, EK_Exception, EK_Member, EK_ArrayElement,
EK_New, EK_Temporary, EK_Base, EK_Delegating,
EK_VectorElement, EK_BlockElement, EK_LambdaToBlockConversionBlockElement, EK_ComplexElement,
EK_LambdaCapture, EK_CompoundLiteralInit, EK_RelatedResult, EK_Parameter_CF_Audited,
EK_Binding
}
Specifies the kind of entity being initialized.
Public Member Functions
EntityKind getKind () const
Determine the kind of initialization.
const InitializedEntity * getParent () const
Retrieve the parent of the entity being initialized, when the initialization itself is occurring within the context of a larger initialization.
QualType getType () const
Retrieve type being initialized.
TypeSourceInfo * getTypeSourceInfo () const
Retrieve complete type-source information for the object being constructed, if known.
DeclarationName getName () const
Retrieve the name of the entity being initialized.
ValueDecl * getDecl () const
Retrieve the variable, parameter, or field being initialized.
ObjCMethodDecl * getMethodDecl () const
Retrieve the ObjectiveC method being initialized.
bool allowsNRVO () const
Determine whether this initialization allows the named return value optimization, which also applies to thrown objects.
bool isParameterKind () const
bool isParamOrTemplateParamKind () const
bool isParameterConsumed () const
Determine whether this initialization consumes the parameter.
const CXXBaseSpecifier * getBaseSpecifier () const
Retrieve the base specifier.
bool isInheritedVirtualBase () const
Return whether the base is an inherited virtual base.
bool isVariableLengthArrayNew () const
Determine whether this is an array new with an unknown bound.
bool isImplicitMemberInitializer () const
Is this the implicit initialization of a member of a class from a defaulted constructor?
bool isDefaultMemberInitializer () const
Is this the default member initializer of a member (specified inside the class definition)?
SourceLocation getReturnLoc () const
Determine the location of the 'return' keyword when initializing the result of a function call.
SourceLocation getThrowLoc () const
Determine the location of the 'throw' keyword when initializing an exception object.
unsigned getElementIndex () const
If this is an array, vector, or complex number element, get the element's index.
void setElementIndex (unsigned Index)
If this is already the initializer for an array or vector element, sets the element index.
StringRef getCapturedVarName () const
For a lambda capture, return the capture's name.
SourceLocation getCaptureLoc () const
Determine the location of the capture when initializing field from a captured variable in a lambda.
void setParameterCFAudited ()
unsigned allocateManglingNumber () const
void dump () const
Dump a representation of the initialized entity to standard error, for debugging purposes.
Static Public Member Functions
static InitializedEntity InitializeVariable (VarDecl *Var)
Create the initialization entity for a variable.
static InitializedEntity InitializeParameter (ASTContext &Context, ParmVarDecl *Parm)
Create the initialization entity for a parameter.
static InitializedEntity InitializeParameter (ASTContext &Context, ParmVarDecl *Parm, QualType Type)
Create the initialization entity for a parameter, but use another type.
static InitializedEntity InitializeParameter (ASTContext &Context, QualType Type, bool Consumed)
Create the initialization entity for a parameter that is only known by its type.
static InitializedEntity InitializeTemplateParameter (QualType T, NonTypeTemplateParmDecl *Param)
Create the initialization entity for a template parameter.
static InitializedEntity InitializeResult (SourceLocation ReturnLoc, QualType Type)
Create the initialization entity for the result of a function.
static InitializedEntity InitializeStmtExprResult (SourceLocation ReturnLoc, QualType Type)
static InitializedEntity InitializeBlock (SourceLocation BlockVarLoc, QualType Type)
static InitializedEntity InitializeLambdaToBlock (SourceLocation BlockVarLoc, QualType Type)
static InitializedEntity InitializeException (SourceLocation ThrowLoc, QualType Type)
Create the initialization entity for an exception object.
static InitializedEntity InitializeNew (SourceLocation NewLoc, QualType Type)
Create the initialization entity for an object allocated via new.
static InitializedEntity InitializeTemporary (QualType Type)
Create the initialization entity for a temporary.
static InitializedEntity InitializeTemporary (ASTContext &Context, TypeSourceInfo *TypeInfo)
Create the initialization entity for a temporary.
static InitializedEntity InitializeTemporary (TypeSourceInfo *TypeInfo, QualType Type)
Create the initialization entity for a temporary.
static InitializedEntity InitializeRelatedResult (ObjCMethodDecl *MD, QualType Type)
Create the initialization entity for a related result.
static InitializedEntity InitializeBase (ASTContext &Context, const CXXBaseSpecifier *Base, bool IsInheritedVirtualBase, const InitializedEntity *Parent=nullptr)
Create the initialization entity for a base class subobject.
static InitializedEntity InitializeDelegation (QualType Type)
Create the initialization entity for a delegated constructor.
static InitializedEntity InitializeMember (FieldDecl *Member, const InitializedEntity *Parent=nullptr, bool Implicit=false)
Create the initialization entity for a member subobject.
static InitializedEntity InitializeMember (IndirectFieldDecl *Member, const InitializedEntity *Parent=nullptr, bool Implicit=false)
Create the initialization entity for a member subobject.
static InitializedEntity InitializeMemberFromDefaultMemberInitializer (FieldDecl *Member)
Create the initialization entity for a default member initializer.
static InitializedEntity InitializeElement (ASTContext &Context, unsigned Index, const InitializedEntity &Parent)
Create the initialization entity for an array element.
static InitializedEntity InitializeBinding (VarDecl *Binding)
Create the initialization entity for a structured binding.
static InitializedEntity InitializeLambdaCapture (IdentifierInfo *VarID, QualType FieldType, SourceLocation Loc)
Create the initialization entity for a lambda capture.
static InitializedEntity InitializeCompoundLiteralInit (TypeSourceInfo *TSI)
Create the entity for a compound literal initializer.
Detailed Description
Describes an entity that is being initialized.
Definition at line 47 of file Initialization.h.
Member Enumeration Documentation
EntityKind
enum clang::InitializedEntity::EntityKind
Specifies the kind of entity being initialized.
Enumerator
EK_Variable
The entity being initialized is a variable.
EK_Parameter
The entity being initialized is a function parameter.
EK_TemplateParameter
The entity being initialized is a non-type template parameter.
EK_Result
The entity being initialized is the result of a function call.
EK_StmtExprResult
The entity being initialized is the result of a statement expression.
EK_Exception
The entity being initialized is an exception object that is being thrown.
EK_Member
The entity being initialized is a non-static data member subobject.
EK_ArrayElement
The entity being initialized is an element of an array.
EK_New
The entity being initialized is an object (or array of objects) allocated via new.
EK_Temporary
The entity being initialized is a temporary object.
EK_Base
The entity being initialized is a base member subobject.
EK_Delegating
The initialization is being done by a delegating constructor.
EK_VectorElement
The entity being initialized is an element of a vector.
or vector.
EK_BlockElement
The entity being initialized is a field of block descriptor for the copied-in c++ object.
EK_LambdaToBlockConversionBlockElement
The entity being initialized is a field of block descriptor for the copied-in lambda object that's used in the lambda to block conversion.
EK_ComplexElement
The entity being initialized is the real or imaginary part of a complex number.
EK_LambdaCapture
The entity being initialized is the field that captures a variable in a lambda.
EK_CompoundLiteralInit
The entity being initialized is the initializer for a compound literal.
EK_RelatedResult
The entity being implicitly initialized back to the formal result type.
EK_Parameter_CF_Audited
The entity being initialized is a function parameter; function is member of group of audited CF APIs.
EK_Binding
The entity being initialized is a structured binding of a decomposition declaration.
Definition at line 50 of file Initialization.h.
Member Function Documentation
allocateManglingNumber()
unsigned clang::InitializedEntity::allocateManglingNumber () const inline
Definition at line 553 of file Initialization.h.
Referenced by clang::Sema::checkInitializerLifetime().
allowsNRVO()
bool InitializedEntity::allowsNRVO () const
Determine whether this initialization allows the named return value optimization, which also applies to thrown objects.
Definition at line 3372 of file SemaInit.cpp.
References EK_ArrayElement, EK_Base, EK_Binding, EK_BlockElement, EK_ComplexElement, EK_CompoundLiteralInit, EK_Delegating, EK_Exception, EK_LambdaCapture, EK_LambdaToBlockConversionBlockElement, EK_Member, EK_New, EK_Parameter, EK_Parameter_CF_Audited, EK_RelatedResult, EK_Result, EK_StmtExprResult, EK_TemplateParameter, EK_Temporary, EK_Variable, EK_VectorElement, getKind(), and LocAndNRVO.
dump()
LLVM_DUMP_METHOD void InitializedEntity::dump () const
Dump a representation of the initialized entity to standard error, for debugging purposes.
Definition at line 3449 of file SemaInit.cpp.
getBaseSpecifier()
const CXXBaseSpecifier* clang::InitializedEntity::getBaseSpecifier () const inline
Retrieve the base specifier.
Definition at line 477 of file Initialization.h.
References EK_Base, and getKind().
Referenced by clang::Sema::CheckConstructorAccess().
getCapturedVarName()
StringRef clang::InitializedEntity::getCapturedVarName () const inline
For a lambda capture, return the capture's name.
Definition at line 537 of file Initialization.h.
References EK_LambdaCapture, and getKind().
Referenced by clang::Sema::CheckConstructorAccess().
getCaptureLoc()
SourceLocation clang::InitializedEntity::getCaptureLoc () const inline
Determine the location of the capture when initializing field from a captured variable in a lambda.
Definition at line 544 of file Initialization.h.
References EK_LambdaCapture, and getKind().
Referenced by getInitializationLoc().
getDecl()
ValueDecl * InitializedEntity::getDecl () const
Retrieve the variable, parameter, or field being initialized.
Definition at line 3339 of file SemaInit.cpp.
References EK_ArrayElement, EK_Base, EK_Binding, EK_BlockElement, EK_ComplexElement, EK_CompoundLiteralInit, EK_Delegating, EK_Exception, EK_LambdaCapture, EK_LambdaToBlockConversionBlockElement, EK_Member, EK_New, EK_Parameter, EK_Parameter_CF_Audited, EK_RelatedResult, EK_Result, EK_StmtExprResult, EK_TemplateParameter, EK_Temporary, EK_Variable, EK_VectorElement, getKind(), Parameter, and Variable.
Referenced by canPerformArrayCopy(), clang::Sema::CheckConstructorAccess(), clang::Sema::checkInitializerLifetime(), getAssignmentAction(), and getInitializationLoc().
getElementIndex()
unsigned clang::InitializedEntity::getElementIndex () const inline
If this is an array, vector, or complex number element, get the element's index.
Definition at line 522 of file Initialization.h.
References EK_ArrayElement, EK_ComplexElement, EK_VectorElement, getKind(), and Index.
getKind()
EntityKind clang::InitializedEntity::getKind () const inline
Determine the kind of initialization.
Definition at line 427 of file Initialization.h.
Referenced by allowsNRVO(), canPerformArrayCopy(), clang::Sema::CheckConstructorAccess(), getAssignmentAction(), getBaseSpecifier(), getCapturedVarName(), getCaptureLoc(), getDecl(), getElementIndex(), getEntityLifetime(), getInitializationLoc(), getName(), getReturnLoc(), getThrowLoc(), isDefaultMemberInitializer(), isExplicitTemporary(), isIdiomaticBraceElisionEntity(), isImplicitMemberInitializer(), isInheritedVirtualBase(), isParameterKind(), isParamOrTemplateParamKind(), isVariableLengthArrayNew(), setElementIndex(), shouldBindAsTemporary(), and shouldDestroyEntity().
getMethodDecl()
ObjCMethodDecl* clang::InitializedEntity::getMethodDecl () const inline
Retrieve the ObjectiveC method being initialized.
Definition at line 454 of file Initialization.h.
References MethodDecl.
getName()
DeclarationName InitializedEntity::getName () const
Retrieve the name of the entity being initialized.
Definition at line 3302 of file SemaInit.cpp.
References EK_ArrayElement, EK_Base, EK_Binding, EK_BlockElement, EK_ComplexElement, EK_CompoundLiteralInit, EK_Delegating, EK_Exception, EK_LambdaCapture, EK_LambdaToBlockConversionBlockElement, EK_Member, EK_New, EK_Parameter, EK_Parameter_CF_Audited, EK_RelatedResult, EK_Result, EK_StmtExprResult, EK_TemplateParameter, EK_Temporary, EK_Variable, EK_VectorElement, clang::NamedDecl::getDeclName(), getKind(), Parameter, and Variable.
getParent()
const InitializedEntity* clang::InitializedEntity::getParent () const inline
Retrieve the parent of the entity being initialized, when the initialization itself is occurring within the context of a larger initialization.
Definition at line 432 of file Initialization.h.
References Parent.
Referenced by canPerformArrayCopy(), clang::Sema::CheckConstructorAccess(), clang::Sema::checkInitializerLifetime(), getEntityLifetime(), and isIdiomaticBraceElisionEntity().
getReturnLoc()
SourceLocation clang::InitializedEntity::getReturnLoc () const inline
Determine the location of the 'return' keyword when initializing the result of a function call.
Definition at line 508 of file Initialization.h.
References EK_Result, getKind(), and LocAndNRVO.
Referenced by getInitializationLoc().
getThrowLoc()
SourceLocation clang::InitializedEntity::getThrowLoc () const inline
Determine the location of the 'throw' keyword when initializing an exception object.
Definition at line 515 of file Initialization.h.
References EK_Exception, getKind(), and LocAndNRVO.
Referenced by getInitializationLoc().
getType()
QualType clang::InitializedEntity::getType () const inline
Retrieve type being initialized.
Definition at line 435 of file Initialization.h.
References Type.
Referenced by clang::Sema::CanPerformAggregateInitializationForOverloadResolution(), clang::Sema::CheckConstructorAccess(), clang::Sema::checkInitializerLifetime(), isIdiomaticBraceElisionEntity(), isVariableLengthArrayNew(), and clang::Sema::PerformCopyInitialization().
getTypeSourceInfo()
TypeSourceInfo* clang::InitializedEntity::getTypeSourceInfo () const inline
Retrieve complete type-source information for the object being constructed, if known.
Definition at line 439 of file Initialization.h.
References EK_CompoundLiteralInit, EK_Temporary, and TypeInfo.
InitializeBase()
InitializedEntity InitializedEntity::InitializeBase (ASTContext & Context, const CXXBaseSpecifier * Base, bool IsInheritedVirtualBase, const InitializedEntity * Parent = nullptr) static
Create the initialization entity for a base class subobject.
Definition at line 3290 of file SemaInit.cpp.
References Base, EK_Base, and Parent.
Referenced by clang::Sema::BuildBaseInitializer(), and BuildImplicitBaseInitializer().
InitializeBinding()
static InitializedEntity clang::InitializedEntity::InitializeBinding (VarDecl * Binding) inline static
Create the initialization entity for a structured binding.
Definition at line 405 of file Initialization.h.
References EK_Binding.
InitializeBlock()
static InitializedEntity clang::InitializedEntity::InitializeBlock (SourceLocation BlockVarLoc, QualType Type) inline static
Definition at line 309 of file Initialization.h.
References EK_BlockElement.
Referenced by clang::Sema::ActOnBlockStmtExpr().
InitializeCompoundLiteralInit()
static InitializedEntity clang::InitializedEntity::InitializeCompoundLiteralInit (TypeSourceInfo * TSI) inline static
Create the entity for a compound literal initializer.
Definition at line 419 of file Initialization.h.
Referenced by clang::Sema::BuildCompoundLiteralExpr().
InitializeDelegation()
static InitializedEntity clang::InitializedEntity::InitializeDelegation (QualType Type) inline static
Create the initialization entity for a delegated constructor.
Definition at line 371 of file Initialization.h.
References EK_Delegating.
Referenced by clang::Sema::BuildDelegatingInitializer().
InitializeElement()
static InitializedEntity clang::InitializedEntity::InitializeElement (ASTContext & Context, unsigned Index, const InitializedEntity & Parent) inline static
Create the initialization entity for an array element.
Definition at line 398 of file Initialization.h.
InitializeException()
static InitializedEntity clang::InitializedEntity::InitializeException (SourceLocation ThrowLoc, QualType Type) inline static
Create the initialization entity for an exception object.
Definition at line 321 of file Initialization.h.
References EK_Exception.
Referenced by clang::Sema::BuildCXXThrow().
InitializeLambdaCapture()
static InitializedEntity clang::InitializedEntity::InitializeLambdaCapture (IdentifierInfo * VarID, QualType FieldType, SourceLocation Loc) inline static
Create the initialization entity for a lambda capture.
VarID The name of the entity being captured, or nullptr for 'this'.
Definition at line 412 of file Initialization.h.
Referenced by clang::Sema::buildLambdaInitCaptureInitialization().
InitializeLambdaToBlock()
static InitializedEntity clang::InitializedEntity::InitializeLambdaToBlock (SourceLocation BlockVarLoc, QualType Type) inline static
Definition at line 314 of file Initialization.h.
References EK_LambdaToBlockConversionBlockElement.
Referenced by clang::Sema::BuildBlockForLambdaConversion().
InitializeMember() [1/2]
static InitializedEntity clang::InitializedEntity::InitializeMember (FieldDecl * Member, const InitializedEntity * Parent = nullptr, bool Implicit = false) inline static
Create the initialization entity for a member subobject.
Definition at line 377 of file Initialization.h.
References clang::Member, and Parent.
Referenced by BuildImplicitMemberInitializer(), clang::Sema::BuildMemberInitializer(), CollectFieldInitializer(), and clang::Sema::SetIvarInitializers().
InitializeMember() [2/2]
static InitializedEntity clang::InitializedEntity::InitializeMember (IndirectFieldDecl * Member, const InitializedEntity * Parent = nullptr, bool Implicit = false) inline static
Create the initialization entity for a member subobject.
Definition at line 385 of file Initialization.h.
References clang::Member, and Parent.
InitializeMemberFromDefaultMemberInitializer()
static InitializedEntity clang::InitializedEntity::InitializeMemberFromDefaultMemberInitializer (FieldDecl * Member) inline static
Create the initialization entity for a default member initializer.
Definition at line 393 of file Initialization.h.
References clang::Member.
Referenced by clang::Sema::ActOnFinishCXXInClassMemberInitializer().
InitializeNew()
static InitializedEntity clang::InitializedEntity::InitializeNew (SourceLocation NewLoc, QualType Type) inline static
Create the initialization entity for an object allocated via new.
Definition at line 327 of file Initialization.h.
References EK_New.
InitializeParameter() [1/3]
static InitializedEntity clang::InitializedEntity::InitializeParameter (ASTContext & Context, ParmVarDecl * Parm) inline static
Create the initialization entity for a parameter.
Definition at line 253 of file Initialization.h.
Referenced by clang::Sema::BuildAtomicExpr(), clang::Sema::BuildLiteralOperatorCall(), clang::Sema::BuildObjCBoxedExpr(), clang::Sema::BuildObjCNumericLiteral(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuildVAArgExpr(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::checkUnknownAnyArg(), clang::Sema::ConvertParamDefaultArgument(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::GatherArgumentsForCall(), and clang::Sema::InstantiateDefaultArgument().
InitializeParameter() [2/3]
static InitializedEntity clang::InitializedEntity::InitializeParameter (ASTContext & Context, ParmVarDecl * Parm, QualType Type) inline static
Create the initialization entity for a parameter, but use another type.
Definition at line 261 of file Initialization.h.
InitializeParameter() [3/3]
static InitializedEntity clang::InitializedEntity::InitializeParameter (ASTContext & Context, QualType Type, bool Consumed) inline static
Create the initialization entity for a parameter that is only known by its type.
Definition at line 276 of file Initialization.h.
InitializeRelatedResult()
static InitializedEntity clang::InitializedEntity::InitializeRelatedResult (ObjCMethodDecl * MD, QualType Type) inline static
Create the initialization entity for a related result.
Definition at line 357 of file Initialization.h.
Referenced by clang::Sema::BuildReturnStmt().
InitializeResult()
static InitializedEntity clang::InitializedEntity::InitializeResult (SourceLocation ReturnLoc, QualType Type) inline static
Create the initialization entity for the result of a function.
Definition at line 299 of file Initialization.h.
References EK_Result.
Referenced by clang::Sema::ActOnCapScopeReturnStmt(), and clang::Sema::BuildReturnStmt().
InitializeStmtExprResult()
static InitializedEntity clang::InitializedEntity::InitializeStmtExprResult (SourceLocation ReturnLoc, QualType Type) inline static
Definition at line 304 of file Initialization.h.
References EK_StmtExprResult.
Referenced by clang::Sema::ActOnStmtExprResult().
InitializeTemplateParameter()
static InitializedEntity clang::InitializedEntity::InitializeTemplateParameter (QualType T, NonTypeTemplateParmDecl * Param) inline static
Create the initialization entity for a template parameter.
Definition at line 289 of file Initialization.h.
References EK_TemplateParameter, and Variable.
Referenced by clang::Sema::CheckTemplateArgument().
InitializeTemporary() [1/3]
static InitializedEntity clang::InitializedEntity::InitializeTemporary (ASTContext & Context, TypeSourceInfo * TypeInfo) inline static
Create the initialization entity for a temporary.
Definition at line 337 of file Initialization.h.
InitializeTemporary() [2/3]
static InitializedEntity clang::InitializedEntity::InitializeTemporary (QualType Type) inline static
Create the initialization entity for a temporary.
Definition at line 332 of file Initialization.h.
Referenced by clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildObjCBoxedExpr(), ConvertForConditional(), clang::Sema::CreateBuiltinBinOp(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DefaultArgumentPromotion(), EvaluateBinaryTypeTrait(), TryClassUnification(), clang::Sema::tryConvertExprToType(), and TryStaticImplicitCast().
InitializeTemporary() [3/3]
static InitializedEntity clang::InitializedEntity::InitializeTemporary (TypeSourceInfo * TypeInfo, QualType Type) inline static
Create the initialization entity for a temporary.
Definition at line 349 of file Initialization.h.
InitializeVariable()
static InitializedEntity clang::InitializedEntity::InitializeVariable (VarDecl * Var) inline static
Create the initialization entity for a variable.
Definition at line 248 of file Initialization.h.
Referenced by clang::Sema::ActOnOpenMPFirstprivateClause(), clang::Sema::ActOnUninitializedDecl(), clang::Sema::AddInitializerToDecl(), and clang::Sema::buildCoroutinePromise().
isDefaultMemberInitializer()
bool clang::InitializedEntity::isDefaultMemberInitializer () const inline
Is this the default member initializer of a member (specified inside the class definition)?
Definition at line 502 of file Initialization.h.
References EK_Member, getKind(), and Variable.
Referenced by getEntityLifetime().
isImplicitMemberInitializer()
bool clang::InitializedEntity::isImplicitMemberInitializer () const inline
Is this the implicit initialization of a member of a class from a defaulted constructor?
Definition at line 496 of file Initialization.h.
References EK_Member, getKind(), and Variable.
Referenced by canPerformArrayCopy().
isInheritedVirtualBase()
bool clang::InitializedEntity::isInheritedVirtualBase () const inline
Return whether the base is an inherited virtual base.
Definition at line 483 of file Initialization.h.
References EK_Base, and getKind().
Referenced by clang::Sema::CheckConstructorAccess().
isParameterConsumed()
bool clang::InitializedEntity::isParameterConsumed () const inline
Determine whether this initialization consumes the parameter.
Definition at line 471 of file Initialization.h.
References isParameterKind(), and Parameter.
isParameterKind()
bool clang::InitializedEntity::isParameterKind () const inline
Definition at line 460 of file Initialization.h.
References EK_Parameter, EK_Parameter_CF_Audited, and getKind().
Referenced by isParameterConsumed(), isParamOrTemplateParamKind(), and clang::Sema::PerformCopyInitialization().
isParamOrTemplateParamKind()
bool clang::InitializedEntity::isParamOrTemplateParamKind () const inline
Definition at line 465 of file Initialization.h.
References EK_TemplateParameter, getKind(), and isParameterKind().
isVariableLengthArrayNew()
bool clang::InitializedEntity::isVariableLengthArrayNew () const inline
Determine whether this is an array new with an unknown bound.
Definition at line 489 of file Initialization.h.
References EK_New, getKind(), and getType().
setElementIndex()
void clang::InitializedEntity::setElementIndex (unsigned Index) inline
If this is already the initializer for an array or vector element, sets the element index.
Definition at line 530 of file Initialization.h.
References EK_ArrayElement, EK_ComplexElement, EK_VectorElement, getKind(), and Index.
setParameterCFAudited()
void clang::InitializedEntity::setParameterCFAudited () inline
Definition at line 549 of file Initialization.h.
References EK_Parameter_CF_Audited.
Referenced by clang::Sema::GatherArgumentsForCall().
Member Data Documentation
Base
llvm::PointerIntPair<const CXXBaseSpecifier *, 1> clang::InitializedEntity::Base
When Kind == EK_Base, the base specifier that provides the base class.
The integer specifies whether the base is an inherited virtual base.
Definition at line 201 of file Initialization.h.
Referenced by InitializeBase().
Capture
struct C clang::InitializedEntity::Capture
Definition at line 208 of file Initialization.h.
Index
unsigned clang::InitializedEntity::Index
When Kind == EK_ArrayElement, EK_VectorElement, or EK_ComplexElement, the index of the array or vector element being initialized.
Definition at line 206 of file Initialization.h.
Referenced by getElementIndex(), and setElementIndex().
LocAndNRVO
struct LN clang::InitializedEntity::LocAndNRVO
Definition at line 196 of file Initialization.h.
Referenced by allowsNRVO(), getReturnLoc(), and getThrowLoc().
MethodDecl
ObjCMethodDecl* clang::InitializedEntity::MethodDecl
When Kind == EK_RelatedResult, the ObjectiveC method where result type was implicitly changed to accommodate ARC semantics.
Definition at line 186 of file Initialization.h.
Referenced by getMethodDecl().
Parameter
llvm::PointerIntPair<ParmVarDecl *, 1> clang::InitializedEntity::Parameter
When Kind == EK_Parameter, the ParmVarDecl, with the integer indicating whether the parameter is "consumed".
Definition at line 190 of file Initialization.h.
Referenced by getDecl(), getName(), and isParameterConsumed().
TypeInfo
TypeSourceInfo* clang::InitializedEntity::TypeInfo
When Kind == EK_Temporary or EK_CompoundLiteralInit, the type source information for the temporary.
Definition at line 194 of file Initialization.h.
Referenced by getTypeSourceInfo().
Variable
VD clang::InitializedEntity::Variable
When Kind == EK_Variable, EK_Member, EK_Binding, or EK_TemplateParameter, the variable, binding, or template parameter.
Definition at line 182 of file Initialization.h.
Referenced by getDecl(), getName(), InitializeTemplateParameter(), isDefaultMemberInitializer(), and isImplicitMemberInitializer().
The documentation for this class was generated from the following files:
include/clang/Sema/Initialization.h
lib/Sema/SemaInit.cpp