clang: clang::tooling::FrontendActionFactory Class Reference
clang::tooling::FrontendActionFactory Class Reference abstract
Interface to generate clang::FrontendActions.
#include "clang/Tooling/Tooling.h"
Public Member Functions
~FrontendActionFactory () override
bool runInvocation (std::shared_ptr< CompilerInvocation > Invocation, FileManager *Files, std::shared_ptr< PCHContainerOperations > PCHContainerOps, DiagnosticConsumer *DiagConsumer) override
Invokes the compiler with a FrontendAction created by create().
virtual std::unique_ptr< FrontendAction > create ()=0
Returns a new clang::FrontendAction.
Public Member Functions inherited from clang::tooling::ToolAction
virtual ~ToolAction ()
Detailed Description
Interface to generate clang::FrontendActions.
Having a factory interface allows, for example, a new FrontendAction to be created for each translation unit processed by ClangTool. This class is also a ToolAction which uses the FrontendActions created by create() to process each translation unit.
Definition at line 98 of file Tooling.h.
Constructor & Destructor Documentation
~FrontendActionFactory()
FrontendActionFactory::~FrontendActionFactory () override default
Member Function Documentation
create()
virtual std::unique_ptr<FrontendAction> clang::tooling::FrontendActionFactory::create () pure virtual
Returns a new clang::FrontendAction.
Referenced by runInvocation().
runInvocation()
bool FrontendActionFactory::runInvocation (std::shared_ptr< CompilerInvocation > Invocation, FileManager * Files, std::shared_ptr< PCHContainerOperations > PCHContainerOps, DiagnosticConsumer * DiagConsumer) override virtual
Invokes the compiler with a FrontendAction created by create().
Implements clang::tooling::ToolAction.
Definition at line 402 of file Tooling.cpp.
References clang::FileManager::clearStatCache(), create(), clang::CompilerInstance::createDiagnostics(), clang::CompilerInstance::createSourceManager(), clang::CompilerInstance::ExecuteAction(), clang::CompilerInstance::hasDiagnostics(), clang::CompilerInstance::setFileManager(), and clang::CompilerInstance::setInvocation().
The documentation for this class was generated from the following files:
include/clang/Tooling/Tooling.h
lib/Tooling/Tooling.cpp