clang: clang::BaseSubobject Class Reference
clang::BaseSubobject Class Reference
#include "clang/AST/BaseSubobject.h"
Public Member Functions
BaseSubobject ()=default
BaseSubobject (const CXXRecordDecl *Base, CharUnits BaseOffset)
const CXXRecordDecl * getBase () const
getBase - Returns the base class declaration.
CharUnits getBaseOffset () const
getBaseOffset - Returns the base class offset.
Friends
bool operator== (const BaseSubobject &LHS, const BaseSubobject &RHS)
Detailed Description
Definition at line 30 of file BaseSubobject.h.
Constructor & Destructor Documentation
BaseSubobject() [1/2]
clang::BaseSubobject::BaseSubobject () default
BaseSubobject() [2/2]
clang::BaseSubobject::BaseSubobject (const CXXRecordDecl * Base, CharUnits BaseOffset) inline
Definition at line 39 of file BaseSubobject.h.
Member Function Documentation
getBase()
const CXXRecordDecl* clang::BaseSubobject::getBase () const inline
getBase - Returns the base class declaration.
Definition at line 43 of file BaseSubobject.h.
Referenced by selectBestPath().
getBaseOffset()
CharUnits clang::BaseSubobject::getBaseOffset () const inline
getBaseOffset - Returns the base class offset.
Definition at line 46 of file BaseSubobject.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitVTableAssumptionLoad(), and clang::CodeGen::CodeGenFunction::InitializeVTablePointer().
Friends And Related Function Documentation
operator==
bool operator== (const BaseSubobject & LHS, const BaseSubobject & RHS) friend
Definition at line 48 of file BaseSubobject.h.
The documentation for this class was generated from the following file:
include/clang/AST/BaseSubobject.h