clang: clang::FunctionDecl::DefaultedOrDeletedFunctionInfo Class Reference
clang::FunctionDecl::DefaultedOrDeletedFunctionInfo Class Reference final
Stashed information about a defaulted/deleted function body.
#include "clang/AST/Decl.h"
Public Member Functions
ArrayRef< DeclAccessPair > getUnqualifiedLookups () const
Get the unqualified lookup results that should be used in this defaulted function definition.
StringLiteral * getDeletedMessage () const
void setDeletedMessage (StringLiteral *Message)
Static Public Member Functions
static DefaultedOrDeletedFunctionInfo * Create (ASTContext &Context, ArrayRef< DeclAccessPair > Lookups, StringLiteral *DeletedMessage=nullptr)
Detailed Description
Stashed information about a defaulted/deleted function body.
Definition at line 1998 of file Decl.h.
Member Function Documentation
Create()
FunctionDecl::DefaultedOrDeletedFunctionInfo * FunctionDecl::DefaultedOrDeletedFunctionInfo::Create (ASTContext & Context, ArrayRef< DeclAccessPair > Lookups, StringLiteral * DeletedMessage = nullptr) static
Definition at line 3100 of file Decl.cpp.
Referenced by clang::FunctionDecl::setDeletedAsWritten(), clang::TemplateDeclInstantiator::SubstDefaultedFunction(), and clang::ASTDeclReader::VisitFunctionDecl().
getDeletedMessage()
StringLiteral* clang::FunctionDecl::DefaultedOrDeletedFunctionInfo::getDeletedMessage () const inline
Definition at line 2020 of file Decl.h.
Referenced by clang::FunctionDecl::getDeletedMessage().
getUnqualifiedLookups()
ArrayRef<DeclAccessPair> clang::FunctionDecl::DefaultedOrDeletedFunctionInfo::getUnqualifiedLookups () const inline
Get the unqualified lookup results that should be used in this defaulted function definition.
Definition at line 2016 of file Decl.h.
setDeletedMessage()
void FunctionDecl::DefaultedOrDeletedFunctionInfo::setDeletedMessage (StringLiteral * Message)
Definition at line 3143 of file Decl.cpp.
Referenced by clang::FunctionDecl::setDeletedAsWritten().
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp