clang: clang::ento::FunctionCodeRegion Class Reference
clang::ento::FunctionCodeRegion Class Reference
FunctionCodeRegion - A region that represents code texts of function.
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
QualType getLocationType () const override
const NamedDecl * getDecl () const
void dumpToStream (raw_ostream &os) const override
void Profile (llvm::FoldingSetNodeID &ID) const override
Public Member Functions inherited from clang::ento::CodeTextRegion
bool isBoundable () const override
Public Member Functions inherited from clang::ento::TypedRegion
QualType getDesugaredLocationType (ASTContext &Context) const
Public Member Functions inherited from clang::ento::SubRegion
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getSuperRegion () const
MemRegionManager & getMemRegionManager () const override
bool isSubRegionOf (const MemRegion *R) const override
Check if the region is a subregion of the given region.
Public Member Functions inherited from clang::ento::MemRegion
ASTContext & getContext () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemSpaceRegion * getMemorySpace () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getBaseRegion () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
virtual bool canPrintPrettyAsExpr () const
Returns true if this region's textual representation can be used as part of a larger expression.
virtual void printPrettyAsExpr (raw_ostream &os) const
Print the region as expression.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
LLVM_ATTRIBUTE_RETURNS_NONNULL const RegionTy * castAs () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Static Public Member Functions
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::CodeTextRegion
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::TypedRegion
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::SubRegion
static bool classof (const MemRegion *R)
Friends
class MemRegionManager
Additional Inherited Members
Public Types inherited from clang::ento::MemRegion
enum Kind
Protected Member Functions inherited from clang::ento::CodeTextRegion
CodeTextRegion (const MemSpaceRegion *sreg, Kind k)
Protected Member Functions inherited from clang::ento::TypedRegion
TypedRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::SubRegion
SubRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::MemRegion
MemRegion (Kind k)
virtual ~MemRegion ()
Protected Attributes inherited from clang::ento::SubRegion
const MemRegion * superRegion
Detailed Description
FunctionCodeRegion - A region that represents code texts of function.
Definition at line 579 of file MemRegion.h.
Member Function Documentation
classof()
static bool clang::ento::FunctionCodeRegion::classof (const MemRegion * R) inline static
Definition at line 615 of file MemRegion.h.
References clang::ento::MemRegion::getKind().
dumpToStream()
void FunctionCodeRegion::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::MemRegion.
Definition at line 484 of file MemRegion.cpp.
References clang::DeclarationName::getAsString(), getDecl(), and clang::NamedDecl::getDeclName().
getDecl()
const NamedDecl* clang::ento::FunctionCodeRegion::getDecl () const inline
Definition at line 607 of file MemRegion.h.
Referenced by dumpToStream().
getLocationType()
QualType clang::ento::FunctionCodeRegion::getLocationType () const inline override virtual
Implements clang::ento::TypedRegion.
Definition at line 593 of file MemRegion.h.
References clang::ento::MemRegion::getContext(), and clang::ASTContext::getPointerType().
Profile()
void FunctionCodeRegion::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Implements clang::ento::MemRegion.
Definition at line 362 of file MemRegion.cpp.
References ID, and clang::ento::SubRegion::superRegion.
Friends And Related Function Documentation
MemRegionManager
friend class MemRegionManager friend
Definition at line 580 of file MemRegion.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp