clang: clang::DependencyFileGenerator Class Reference
clang::DependencyFileGenerator Class Reference
Builds a dependency file when attached to a Preprocessor (for includes) and ASTReader (for module imports), and writes it out at the end of processing a source file.
#include "clang/Frontend/Utils.h"
Public Member Functions
DependencyFileGenerator (const DependencyOutputOptions &Opts)
void attachToPreprocessor (Preprocessor &PP) override
void finishedMainFile (DiagnosticsEngine &Diags) override
Called when the end of the main file is reached.
bool needSystemDependencies () final override
Return true if system files should be passed to sawDependency().
bool sawDependency (StringRef Filename, bool FromModule, bool IsSystem, bool IsModuleFile, bool IsMissing) final override
Called when a new file is seen.
Public Member Functions inherited from clang::DependencyCollector
virtual ~DependencyCollector ()
virtual void attachToASTReader (ASTReader &R)
ArrayRef< std::string > getDependencies () const
virtual void maybeAddDependency (StringRef Filename, bool FromModule, bool IsSystem, bool IsModuleFile, bool IsMissing)
Add a dependency Filename if it has not been seen before and sawDependency() returns true.
Protected Member Functions
void outputDependencyFile (llvm::raw_ostream &OS)
Protected Member Functions inherited from clang::DependencyCollector
bool addDependency (StringRef Filename)
Return true if the filename was added to the list of dependencies, false otherwise.
Detailed Description
Builds a dependency file when attached to a Preprocessor (for includes) and ASTReader (for module imports), and writes it out at the end of processing a source file.
Users should attach to the ast reader whenever a module is loaded.
Definition at line 103 of file Utils.h.
Constructor & Destructor Documentation
DependencyFileGenerator()
DependencyFileGenerator::DependencyFileGenerator (const DependencyOutputOptions & Opts)
Definition at line 187 of file DependencyFile.cpp.
References clang::DependencyCollector::addDependency(), and clang::DependencyOutputOptions::ExtraDeps.
Member Function Documentation
attachToPreprocessor()
void DependencyFileGenerator::attachToPreprocessor (Preprocessor & PP) override virtual
Reimplemented from clang::DependencyCollector.
Definition at line 202 of file DependencyFile.cpp.
References clang::DependencyCollector::attachToPreprocessor(), and clang::Preprocessor::SetSuppressIncludeNotFoundError().
finishedMainFile()
void DependencyFileGenerator::finishedMainFile (DiagnosticsEngine & Diags) override virtual
Called when the end of the main file is reached.
Reimplemented from clang::DependencyCollector.
Definition at line 238 of file DependencyFile.cpp.
References outputDependencyFile().
needSystemDependencies()
bool clang::DependencyFileGenerator::needSystemDependencies () inline final override virtual
Return true if system files should be passed to sawDependency().
Reimplemented from clang::DependencyCollector.
Definition at line 111 of file Utils.h.
outputDependencyFile()
void DependencyFileGenerator::outputDependencyFile (llvm::raw_ostream & OS) protected
Definition at line 337 of file DependencyFile.cpp.
References clang::File, clang::DependencyCollector::getDependencies(), PrintFilename(), and clang::Target.
Referenced by finishedMainFile().
sawDependency()
bool DependencyFileGenerator::sawDependency (StringRef Filename, bool FromModule, bool IsSystem, bool IsModuleFile, bool IsMissing) final override virtual
Called when a new file is seen.
Return true if Filename should be added to the list of dependencies.
The default implementation ignores <built-in> and system files.
Reimplemented from clang::DependencyCollector.
Definition at line 210 of file DependencyFile.cpp.
References Filename, and isSpecialFilename().
The documentation for this class was generated from the following files:
include/clang/Frontend/Utils.h
lib/Frontend/DependencyFile.cpp