clang: clang::edit::FileOffset Class Reference
clang::edit::FileOffset Class Reference
#include "clang/Edit/FileOffset.h"
Public Member Functions
FileOffset ()=default
FileOffset (FileID fid, unsigned offs)
bool isInvalid () const
FileID getFID () const
unsigned getOffset () const
FileOffset getWithOffset (unsigned offset) const
Friends
bool operator== (FileOffset LHS, FileOffset RHS)
bool operator!= (FileOffset LHS, FileOffset RHS)
bool operator< (FileOffset LHS, FileOffset RHS)
bool operator> (FileOffset LHS, FileOffset RHS)
bool operator>= (FileOffset LHS, FileOffset RHS)
bool operator<= (FileOffset LHS, FileOffset RHS)
Detailed Description
Definition at line 18 of file FileOffset.h.
Constructor & Destructor Documentation
FileOffset() [1/2]
clang::edit::FileOffset::FileOffset () default
FileOffset() [2/2]
clang::edit::FileOffset::FileOffset (FileID fid, unsigned offs) inline
Definition at line 24 of file FileOffset.h.
Member Function Documentation
getFID()
FileID clang::edit::FileOffset::getFID () const inline
Definition at line 28 of file FileOffset.h.
Referenced by adjustRemoval(), applyRewrite(), clang::edit::Commit::Edit::getFileLocation(), and clang::edit::Commit::replaceWithInner().
getOffset()
unsigned clang::edit::FileOffset::getOffset () const inline
Definition at line 29 of file FileOffset.h.
Referenced by adjustRemoval(), applyRewrite(), clang::edit::Commit::Edit::getFileLocation(), and clang::edit::Commit::replaceWithInner().
getWithOffset()
FileOffset clang::edit::FileOffset::getWithOffset (unsigned offset) const inline
Definition at line 31 of file FileOffset.h.
Referenced by clang::edit::EditedSource::applyRewrites(), and clang::edit::Commit::replaceWithInner().
isInvalid()
bool clang::edit::FileOffset::isInvalid () const inline
Definition at line 26 of file FileOffset.h.
References clang::FileID::isInvalid().
Friends And Related Function Documentation
operator!=
bool operator!= (FileOffset LHS, FileOffset RHS) friend
Definition at line 41 of file FileOffset.h.
operator<
bool operator< (FileOffset LHS, FileOffset RHS) friend
Definition at line 45 of file FileOffset.h.
operator<=
bool operator<= (FileOffset LHS, FileOffset RHS) friend
Definition at line 57 of file FileOffset.h.
operator==
bool operator== (FileOffset LHS, FileOffset RHS) friend
Definition at line 37 of file FileOffset.h.
operator>
bool operator> (FileOffset LHS, FileOffset RHS) friend
Definition at line 49 of file FileOffset.h.
operator>=
bool operator>= (FileOffset LHS, FileOffset RHS) friend
Definition at line 53 of file FileOffset.h.
The documentation for this class was generated from the following file:
include/clang/Edit/FileOffset.h