clang: clang::ObjCMessageExpr Class Reference
clang::ObjCMessageExpr Class Reference final
An expression that sends a message to the given Objective-C object or class.
#include "clang/AST/ExprObjC.h"
Public Types
enum ReceiverKind { Class = 0 , Instance , SuperClass , SuperInstance }
The kind of receiver this message is sending to.
using arg_iterator = ExprIterator
using const_arg_iterator = ConstExprIterator
Public Types inherited from clang::Expr
enum LValueClassification {
LV_Valid , LV_NotObjectType , LV_IncompleteVoidType , LV_DuplicateVectorComponents ,
LV_InvalidExpression , LV_InvalidMessageExpression , LV_MemberFunction , LV_SubObjCPropertySetting ,
LV_ClassTemporary , LV_ArrayTemporary
}
enum isModifiableLvalueResult {
MLV_Valid , MLV_NotObjectType , MLV_IncompleteVoidType , MLV_DuplicateVectorComponents ,
MLV_InvalidExpression , MLV_LValueCast , MLV_IncompleteType , MLV_ConstQualified ,
MLV_ConstQualifiedField , MLV_ConstAddrSpace , MLV_ArrayType , MLV_NoSetterProperty ,
MLV_MemberFunction , MLV_SubObjCPropertySetting , MLV_InvalidMessageExpression , MLV_ClassTemporary ,
MLV_ArrayTemporary
}
enum SideEffectsKind { SE_NoSideEffects , SE_AllowUndefinedBehavior , SE_AllowSideEffects }
enum class ConstantExprKind { Normal , NonClassTemplateArgument , ClassTemplateArgument , ImmediateInvocation }
enum NullPointerConstantKind {
NPCK_NotNull = 0 , NPCK_ZeroExpression , NPCK_ZeroLiteral , NPCK_CXX11_nullptr ,
NPCK_GNUNull
}
Enumeration used to describe the kind of Null pointer constant returned from isNullPointerConstant().
enum NullPointerConstantValueDependence { NPC_NeverValueDependent = 0 , NPC_ValueDependentIsNull , NPC_ValueDependentIsNotNull }
Enumeration used to describe how isNullPointerConstant() should cope with value-dependent expressions.
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
bool isImplicit () const
Indicates whether the message send was implicitly generated by the implementation.
ReceiverKind getReceiverKind () const
Determine the kind of receiver that this message is being sent to.
QualType getCallReturnType (ASTContext &Ctx) const
SourceRange getReceiverRange () const
Source range of the receiver.
bool isInstanceMessage () const
Determine whether this is an instance message to either a computed object or to super.
bool isClassMessage () const
Determine whether this is an class message to either a specified class or to super.
Expr * getInstanceReceiver ()
Returns the object expression (receiver) for an instance message, or null for a message that is not an instance message.
const Expr * getInstanceReceiver () const
void setInstanceReceiver (Expr *rec)
Turn this message send into an instance message that computes the receiver object with the given expression.
QualType getClassReceiver () const
Returns the type of a class message send, or NULL if the message is not a class message.
TypeSourceInfo * getClassReceiverTypeInfo () const
Returns a type-source information of a class message send, or nullptr if the message is not a class message.
void setClassReceiver (TypeSourceInfo *TSInfo)
SourceLocation getSuperLoc () const
Retrieve the location of the 'super' keyword for a class or instance message to 'super', otherwise an invalid source location.
QualType getReceiverType () const
Retrieve the receiver type to which this message is being directed.
ObjCInterfaceDecl * getReceiverInterface () const
Retrieve the Objective-C interface to which this message is being directed, if known.
QualType getSuperType () const
Retrieve the type referred to by 'super'.
void setSuper (SourceLocation Loc, QualType T, bool IsInstanceSuper)
Selector getSelector () const
void setSelector (Selector S)
const ObjCMethodDecl * getMethodDecl () const
ObjCMethodDecl * getMethodDecl ()
void setMethodDecl (ObjCMethodDecl *MD)
ObjCMethodFamily getMethodFamily () const
unsigned getNumArgs () const
Return the number of actual arguments in this message, not counting the receiver.
Expr ** getArgs ()
Retrieve the arguments to this message, not including the receiver.
const Expr *const * getArgs () const
Expr * getArg (unsigned Arg)
getArg - Return the specified argument.
const Expr * getArg (unsigned Arg) const
void setArg (unsigned Arg, Expr *ArgExpr)
setArg - Set the specified argument.
bool isDelegateInitCall () const
isDelegateInitCall - Answers whether this message send has been tagged as a "delegate init call", i.e.
void setDelegateInitCall (bool isDelegate)
SourceLocation getLeftLoc () const
SourceLocation getRightLoc () const
SourceLocation getSelectorStartLoc () const
SourceLocation getSelectorLoc (unsigned Index) const
void getSelectorLocs (SmallVectorImpl< SourceLocation > &SelLocs) const
unsigned getNumSelectorLocs () const
void setSourceRange (SourceRange R)
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
llvm::iterator_range< arg_iterator > arguments ()
llvm::iterator_range< const_arg_iterator > arguments () const
arg_iterator arg_begin ()
arg_iterator arg_end ()
const_arg_iterator arg_begin () const
const_arg_iterator arg_end () const
Public Member Functions inherited from clang::Expr
Expr ()=delete
Expr (const Expr &)=delete
Expr (Expr &&)=delete
Expr & operator= (const Expr &)=delete
Expr & operator= (Expr &&)=delete
QualType getType () const
void setType (QualType t)
QualType getEnumCoercedType (const ASTContext &Ctx) const
If this expression is an enumeration constant, return the enumeration type under which said constant was declared.
ExprDependence getDependence () const
bool isValueDependent () const
Determines whether the value of this expression depends on.
bool isTypeDependent () const
Determines whether the type of this expression depends on.
bool isInstantiationDependent () const
Whether this expression is instantiation-dependent, meaning that it depends in some way on.
bool containsUnexpandedParameterPack () const
Whether this expression contains an unexpanded parameter pack (for C++11 variadic templates).
bool containsErrors () const
Whether this expression contains subexpressions which had errors, e.g.
SourceLocation getExprLoc () const LLVM_READONLY
getExprLoc - Return the preferred location for the arrow when diagnosing a problem with a generic expression.
bool isReadIfDiscardedInCPlusPlus11 () const
Determine whether an lvalue-to-rvalue conversion should implicitly be applied to this expression if it appears as a discarded-value expression in C++11 onwards.
bool isUnusedResultAWarning (const Expr *&WarnExpr, SourceLocation &Loc, SourceRange &R1, SourceRange &R2, ASTContext &Ctx) const
isUnusedResultAWarning - Return true if this immediate expression should be warned about if the result is unused.
bool isLValue () const
isLValue - True if this expression is an "l-value" according to the rules of the current language.
bool isPRValue () const
bool isXValue () const
bool isGLValue () const
LValueClassification ClassifyLValue (ASTContext &Ctx) const
Reasons why an expression might not be an l-value.
isModifiableLvalueResult isModifiableLvalue (ASTContext &Ctx, SourceLocation *Loc=nullptr) const
isModifiableLvalue - C99 6.3.2.1: an lvalue that does not have array type, does not have an incomplete type, does not have a const-qualified type, and if it is a structure or union, does not have any member (including, recursively, any member or element of all contained aggregates or unions) with a const-qualified type.
Classification Classify (ASTContext &Ctx) const
Classify - Classify this expression according to the C++11 expression taxonomy.
Classification ClassifyModifiable (ASTContext &Ctx, SourceLocation &Loc) const
ClassifyModifiable - Classify this expression according to the C++11 expression taxonomy, and see if it is valid on the left side of an assignment.
FPOptions getFPFeaturesInEffect (const LangOptions &LO) const
Returns the set of floating point options that apply to this expression.
ExprValueKind getValueKind () const
getValueKind - The value kind that this expression produces.
ExprObjectKind getObjectKind () const
getObjectKind - The object kind that this expression produces.
bool isOrdinaryOrBitFieldObject () const
void setValueKind (ExprValueKind Cat)
setValueKind - Set the value kind produced by this expression.
void setObjectKind (ExprObjectKind Cat)
setObjectKind - Set the object kind produced by this expression.
bool refersToBitField () const
Returns true if this expression is a gl-value that potentially refers to a bit-field.
FieldDecl * getSourceBitField ()
If this expression refers to a bit-field, retrieve the declaration of that bit-field.
EnumConstantDecl * getEnumConstantDecl ()
If this expression refers to an enum constant, retrieve its declaration.
const EnumConstantDecl * getEnumConstantDecl () const
const FieldDecl * getSourceBitField () const
Decl * getReferencedDeclOfCallee ()
const Decl * getReferencedDeclOfCallee () const
const ObjCPropertyRefExpr * getObjCProperty () const
If this expression is an l-value for an Objective C property, find the underlying property reference expression.
bool isObjCSelfExpr () const
Check if this expression is the ObjC 'self' implicit parameter.
bool refersToVectorElement () const
Returns whether this expression refers to a vector element.
bool refersToMatrixElement () const
Returns whether this expression refers to a matrix element.
bool refersToGlobalRegisterVar () const
Returns whether this expression refers to a global register variable.
bool hasPlaceholderType () const
Returns whether this expression has a placeholder type.
bool hasPlaceholderType (BuiltinType::Kind K) const
Returns whether this expression has a specific placeholder type.
bool isKnownToHaveBooleanValue (bool Semantic=true) const
isKnownToHaveBooleanValue - Return true if this is an integer expression that is known to return 0 or 1.
bool isFlexibleArrayMemberLike (ASTContext &Context, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel, bool IgnoreTemplateOrMacroSubstitution=false) const
Check whether this array fits the idiom of a flexible array member, depending on the value of -fstrict-flex-array.
std::optional< llvm::APSInt > getIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr) const
isIntegerConstantExpr - Return the value if this expression is a valid integer constant expression.
bool isIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr) const
bool isCXX98IntegralConstantExpr (const ASTContext &Ctx) const
isCXX98IntegralConstantExpr - Return true if this expression is an integral constant expression in C++98.
bool isCXX11ConstantExpr (const ASTContext &Ctx, APValue *Result=nullptr, SourceLocation *Loc=nullptr) const
isCXX11ConstantExpr - Return true if this expression is a constant expression in C++11.
bool isConstantInitializer (ASTContext &Ctx, bool ForRef, const Expr **Culprit=nullptr) const
isConstantInitializer - Returns true if this expression can be emitted to IR as a constant, and thus can be used as a constant initializer in C.
const ValueDecl * getAsBuiltinConstantDeclRef (const ASTContext &Context) const
If this expression is an unambiguous reference to a single declaration, in the style of __builtin_function_start, return that declaration.
bool EvaluateAsRValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsRValue - Return true if this is a constant which we can fold to an rvalue using any crazy technique (that has nothing to do with language standards) that we want to, even if the expression has side-effects.
bool EvaluateAsBooleanCondition (bool &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsBooleanCondition - Return true if this is a constant which we can fold and convert to a boolean condition using any crazy technique that we want to, even if the expression has side-effects.
bool EvaluateAsInt (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsInt - Return true if this is a constant which we can fold and convert to an integer, using any crazy technique that we want to.
bool EvaluateAsFloat (llvm::APFloat &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a floating point value, using any crazy technique that we want to.
bool EvaluateAsFixedPoint (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFixedPoint - Return true if this is a constant which we can fold and convert to a fixed point value.
bool isEvaluatable (const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects) const
isEvaluatable - Call EvaluateAsRValue to see if this expression can be constant folded without side-effects, but discard the result.
bool HasSideEffects (const ASTContext &Ctx, bool IncludePossibleEffects=true) const
HasSideEffects - This routine returns true for all those expressions which have any effect other than producing a value.
bool hasNonTrivialCall (const ASTContext &Ctx) const
Determine whether this expression involves a call to any function that is not trivial.
llvm::APSInt EvaluateKnownConstInt (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
EvaluateKnownConstInt - Call EvaluateAsRValue and return the folded integer.
llvm::APSInt EvaluateKnownConstIntCheckOverflow (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
void EvaluateForOverflow (const ASTContext &Ctx) const
bool EvaluateAsLValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsLValue - Evaluate an expression to see if we can fold it to an lvalue with link time known address, with no side-effects.
bool EvaluateAsInitializer (APValue &Result, const ASTContext &Ctx, const VarDecl *VD, SmallVectorImpl< PartialDiagnosticAt > &Notes, bool IsConstantInitializer) const
EvaluateAsInitializer - Evaluate an expression as if it were the initializer of the given declaration.
bool EvaluateWithSubstitution (APValue &Value, ASTContext &Ctx, const FunctionDecl *Callee, ArrayRef< const Expr * > Args, const Expr *This=nullptr) const
EvaluateWithSubstitution - Evaluate an expression as if from the context of a call to the given function with the given arguments, inside an unevaluated context.
bool EvaluateAsConstantExpr (EvalResult &Result, const ASTContext &Ctx, ConstantExprKind Kind=ConstantExprKind::Normal) const
Evaluate an expression that is required to be a constant expression.
bool tryEvaluateObjectSize (uint64_t &Result, ASTContext &Ctx, unsigned Type) const
If the current Expr is a pointer, this will try to statically determine the number of bytes available where the pointer is pointing.
bool tryEvaluateStrLen (uint64_t &Result, ASTContext &Ctx) const
If the current Expr is a pointer, this will try to statically determine the strlen of the string pointed to.
bool EvaluateCharRangeAsString (std::string &Result, const Expr *SizeExpression, const Expr *PtrExpression, ASTContext &Ctx, EvalResult &Status) const
NullPointerConstantKind isNullPointerConstant (ASTContext &Ctx, NullPointerConstantValueDependence NPC) const
isNullPointerConstant - C99 6.3.2.3p3 - Test if this reduces down to a Null pointer constant.
bool isOBJCGCCandidate (ASTContext &Ctx) const
isOBJCGCCandidate - Return true if this expression may be used in a read/ write barrier.
bool isBoundMemberFunction (ASTContext &Ctx) const
Returns true if this expression is a bound member function.
Expr * IgnoreUnlessSpelledInSource ()
Skip past any invisible AST nodes which might surround this statement, such as ExprWithCleanups or ImplicitCastExpr nodes, but also injected CXXMemberExpr and CXXConstructExpr which represent implicit conversions.
const Expr * IgnoreUnlessSpelledInSource () const
Expr * IgnoreImpCasts () LLVM_READONLY
Skip past any implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreImpCasts () const
Expr * IgnoreCasts () LLVM_READONLY
Skip past any casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreCasts () const
Expr * IgnoreImplicit () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicit () const
Expr * IgnoreImplicitAsWritten () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicitAsWritten () const
Expr * IgnoreParens () LLVM_READONLY
Skip past any parentheses which might surround this expression until reaching a fixed point.
const Expr * IgnoreParens () const
Expr * IgnoreParenImpCasts () LLVM_READONLY
Skip past any parentheses and implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenImpCasts () const
Expr * IgnoreParenCasts () LLVM_READONLY
Skip past any parentheses and casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenCasts () const
Expr * IgnoreConversionOperatorSingleStep () LLVM_READONLY
Skip conversion operators.
const Expr * IgnoreConversionOperatorSingleStep () const
Expr * IgnoreParenLValueCasts () LLVM_READONLY
Skip past any parentheses and lvalue casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenLValueCasts () const
Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) LLVM_READONLY
Skip past any parentheses and casts which do not change the value (including ptr->int casts of the same size) until reaching a fixed point.
const Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) const
Expr * IgnoreParenBaseCasts () LLVM_READONLY
Skip past any parentheses and derived-to-base casts until reaching a fixed point.
const Expr * IgnoreParenBaseCasts () const
bool isDefaultArgument () const
Determine whether this expression is a default function argument.
bool isTemporaryObject (ASTContext &Ctx, const CXXRecordDecl *TempTy) const
Determine whether the result of this expression is a temporary object of the given class type.
bool isImplicitCXXThis () const
Whether this expression is an implicit reference to 'this' in C++.
const CXXRecordDecl * getBestDynamicClassType () const
For an expression of class type or pointer to class type, return the most derived class decl the expression is known to refer to.
const Expr * getBestDynamicClassTypeExpr () const
Get the inner expression that determines the best dynamic class.
const Expr * skipRValueSubobjectAdjustments (SmallVectorImpl< const Expr * > &CommaLHS, SmallVectorImpl< SubobjectAdjustment > &Adjustments) const
Walk outwards from an expression we want to bind a reference to and find the expression whose lifetime needs to be extended.
const Expr * skipRValueSubobjectAdjustments () const
Public Member Functions inherited from clang::ValueStmt
const Expr * getExprStmt () const
Expr * getExprStmt ()
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical, bool ProfileLambdaExpr=false) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static ObjCMessageExpr * Create (const ASTContext &Context, QualType T, ExprValueKind VK, SourceLocation LBracLoc, SourceLocation SuperLoc, bool IsInstanceSuper, QualType SuperType, Selector Sel, ArrayRef< SourceLocation > SelLocs, ObjCMethodDecl *Method, ArrayRef< Expr * > Args, SourceLocation RBracLoc, bool isImplicit)
Create a message send to super.
static ObjCMessageExpr * Create (const ASTContext &Context, QualType T, ExprValueKind VK, SourceLocation LBracLoc, TypeSourceInfo *Receiver, Selector Sel, ArrayRef< SourceLocation > SelLocs, ObjCMethodDecl *Method, ArrayRef< Expr * > Args, SourceLocation RBracLoc, bool isImplicit)
Create a class message send.
static ObjCMessageExpr * Create (const ASTContext &Context, QualType T, ExprValueKind VK, SourceLocation LBracLoc, Expr *Receiver, Selector Sel, ArrayRef< SourceLocation > SeLocs, ObjCMethodDecl *Method, ArrayRef< Expr * > Args, SourceLocation RBracLoc, bool isImplicit)
Create an instance message send.
static ObjCMessageExpr * CreateEmpty (const ASTContext &Context, unsigned NumArgs, unsigned NumStoredSelLocs)
Create an empty Objective-C message expression, to be filled in by subsequent calls.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Expr
static ExprValueKind getValueKindForType (QualType T)
getValueKindForType - Given a formal return or parameter type, give its value kind.
static bool isPotentialConstantExpr (const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExpr - Return true if this function's definition might be usable in a constant expression in C++11, if it were marked constexpr.
static bool isPotentialConstantExprUnevaluated (Expr *E, const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExprUnevaluated - Return true if this expression might be usable in a constant expression in C++11 in an unevaluated context, if it were in function FD marked constexpr.
static QualType findBoundMemberType (const Expr *expr)
Given an expression of bound-member type, find the type of the member.
static bool hasAnyTypeDependentArguments (ArrayRef< Expr * > Exprs)
hasAnyTypeDependentArguments - Determines if any of the expressions in Exprs is type-dependent.
static bool isSameComparisonOperand (const Expr *E1, const Expr *E2)
Checks that the two Expr's will refer to the same value as a comparison operand.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::ValueStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Public Attributes
friend TrailingObjects
Friends
class ASTStmtReader
class ASTStmtWriter
Additional Inherited Members
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator< T, const T *const, const Stmt *const >
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator< Expr >
using ConstExprIterator = ConstCastIterator< Expr >
Protected Member Functions inherited from clang::Expr
Expr (StmtClass SC, QualType T, ExprValueKind VK, ExprObjectKind OK)
Expr (StmtClass SC, EmptyShell)
Construct an empty expression.
void setDependence (ExprDependence Deps)
Each concrete expr subclass is expected to compute its dependence and call this in the constructor.
Protected Member Functions inherited from clang::ValueStmt
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt (StmtClass SC)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
An expression that sends a message to the given Objective-C object or class.
The following contains two message send expressions:
[[NSString alloc] initWithString:@"Hello"]
The innermost message send invokes the "alloc" class method on the NSString class, while the outermost message send invokes the "initWithString" instance method on the object returned from NSString's "alloc". In all, an Objective-C message send can take on four different (although related) forms:
Send to an object instance.
Send to a class.
Send to the superclass instance of the current class.
Send to the superclass of the current class.
All four kinds of message sends are modeled by the ObjCMessageExpr class, and can be distinguished via getReceiverKind(). Example:
The "void *" trailing objects are actually ONE void * (the receiver pointer), and NumArgs Expr *. But due to the implementation of children(), these must be together contiguously.
Definition at line 943 of file ExprObjC.h.
Member Typedef Documentation
arg_iterator
using clang::ObjCMessageExpr::arg_iterator = ExprIterator
Definition at line 1459 of file ExprObjC.h.
const_arg_iterator
using clang::ObjCMessageExpr::const_arg_iterator = ConstExprIterator
Definition at line 1460 of file ExprObjC.h.
Member Enumeration Documentation
ReceiverKind
enum clang::ObjCMessageExpr::ReceiverKind
The kind of receiver this message is sending to.
Enumerator
Class
The receiver is a class.
Instance
The receiver is an object instance.
SuperClass
The receiver is a superclass.
SuperInstance
The receiver is the instance of the superclass object.
Definition at line 948 of file ExprObjC.h.
Member Function Documentation
arg_begin() [1/2]
arg_iterator clang::ObjCMessageExpr::arg_begin () inline
Definition at line 1470 of file ExprObjC.h.
References getArgs().
Referenced by arguments().
arg_begin() [2/2]
const_arg_iterator clang::ObjCMessageExpr::arg_begin () const inline
Definition at line 1476 of file ExprObjC.h.
References getArgs().
arg_end() [1/2]
arg_iterator clang::ObjCMessageExpr::arg_end () inline
Definition at line 1472 of file ExprObjC.h.
References getArgs().
Referenced by arguments().
arg_end() [2/2]
const_arg_iterator clang::ObjCMessageExpr::arg_end () const inline
Definition at line 1480 of file ExprObjC.h.
References getArgs().
arguments() [1/2]
llvm::iterator_range<arg_iterator> clang::ObjCMessageExpr::arguments () inline
Definition at line 1462 of file ExprObjC.h.
References arg_begin(), and arg_end().
Referenced by clang::computeDependence(), and clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr().
arguments() [2/2]
llvm::iterator_range<const_arg_iterator> clang::ObjCMessageExpr::arguments () const inline
Definition at line 1466 of file ExprObjC.h.
References arg_begin(), and arg_end().
children() [1/2]
Stmt::child_range ObjCMessageExpr::children ()
Definition at line 326 of file ExprObjC.cpp.
References getArgs(), getNumArgs(), getReceiverKind(), and Instance.
Referenced by children().
children() [2/2]
Stmt::const_child_range ObjCMessageExpr::children () const
Definition at line 336 of file ExprObjC.cpp.
References children().
classof()
static bool clang::ObjCMessageExpr::classof (const Stmt * T) inline static
Definition at line 1484 of file ExprObjC.h.
References clang::T.
Create() [1/3]
ObjCMessageExpr * ObjCMessageExpr::Create (const ASTContext & Context, QualType T, ExprValueKind VK, SourceLocation LBracLoc, Expr * Receiver, Selector Sel, ArrayRef< SourceLocation > SeLocs, ObjCMethodDecl * Method, ArrayRef< Expr * > Args, SourceLocation RBracLoc, bool isImplicit) static
Create an instance message send.
Parameters
Context The ASTContext in which this expression will be created.
T The result type of this message.
VK The value kind of this message. A message returning a l-value or r-value reference will be an l-value or x-value, respectively.
LBracLoc The location of the open square bracket '['.
Receiver The expression used to produce the object that will receive this message.
Sel The selector used to determine which method gets called.
Method The Objective-C method against which this message send was type-checked. May be nullptr.
Args The message send arguments.
RBracLoc The location of the closing square bracket ']'.
Definition at line 214 of file ExprObjC.cpp.
Create() [2/3]
ObjCMessageExpr * ObjCMessageExpr::Create (const ASTContext & Context, QualType T, ExprValueKind VK, SourceLocation LBracLoc, SourceLocation SuperLoc, bool IsInstanceSuper, QualType SuperType, Selector Sel, ArrayRef< SourceLocation > SelLocs, ObjCMethodDecl * Method, ArrayRef< Expr * > Args, SourceLocation RBracLoc, bool isImplicit) static
Create a message send to super.
Parameters
Context The ASTContext in which this expression will be created.
T The result type of this message.
VK The value kind of this message. A message returning a l-value or r-value reference will be an l-value or x-value, respectively.
LBracLoc The location of the open square bracket '['.
SuperLoc The location of the "super" keyword.
IsInstanceSuper Whether this is an instance "super" message (otherwise, it's a class "super" message).
Sel The selector used to determine which method gets called.
Method The Objective-C method against which this message send was type-checked. May be nullptr.
Args The message send arguments.
RBracLoc The location of the closing square bracket ']'.
Definition at line 175 of file ExprObjC.cpp.
Referenced by clang::Sema::BuildClassMessage(), and clang::Sema::BuildInstanceMessage().
Create() [3/3]
ObjCMessageExpr * ObjCMessageExpr::Create (const ASTContext & Context, QualType T, ExprValueKind VK, SourceLocation LBracLoc, TypeSourceInfo * Receiver, Selector Sel, ArrayRef< SourceLocation > SelLocs, ObjCMethodDecl * Method, ArrayRef< Expr * > Args, SourceLocation RBracLoc, bool isImplicit) static
Create a class message send.
Parameters
Context The ASTContext in which this expression will be created.
T The result type of this message.
VK The value kind of this message. A message returning a l-value or r-value reference will be an l-value or x-value, respectively.
LBracLoc The location of the open square bracket '['.
Receiver The type of the receiver, including source-location information.
Sel The selector used to determine which method gets called.
Method The Objective-C method against which this message send was type-checked. May be nullptr.
Args The message send arguments.
RBracLoc The location of the closing square bracket ']'.
Definition at line 195 of file ExprObjC.cpp.
CreateEmpty()
ObjCMessageExpr * ObjCMessageExpr::CreateEmpty (const ASTContext & Context, unsigned NumArgs, unsigned NumStoredSelLocs) static
Create an empty Objective-C message expression, to be filled in by subsequent calls.
Parameters
Context The context in which the message send will be created.
NumArgs The number of message arguments, not including the receiver.
Definition at line 232 of file ExprObjC.cpp.
getArg() [1/2]
Expr* clang::ObjCMessageExpr::getArg (unsigned Arg) inline
getArg - Return the specified argument.
Definition at line 1395 of file ExprObjC.h.
References getArgs().
Referenced by clang::Sema::checkRetainCycles(), doRewriteToUTF8StringBoxedExpressionHelper(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToArrayLiteral(), rewriteToArraySubscriptSet(), rewriteToDictionaryLiteral(), rewriteToDictionarySubscriptSet(), rewriteToNumberLiteral(), rewriteToNumericBoxedExpression(), rewriteToStringBoxedExpression(), rewriteToSubscriptGetCommon(), and shouldNotRewriteImmediateMessageArgs().
getArg() [2/2]
const Expr* clang::ObjCMessageExpr::getArg (unsigned Arg) const inline
Definition at line 1399 of file ExprObjC.h.
References getArgs().
getArgs() [1/2]
Expr** clang::ObjCMessageExpr::getArgs () inline
Retrieve the arguments to this message, not including the receiver.
Definition at line 1386 of file ExprObjC.h.
Referenced by arg_begin(), arg_end(), children(), getArg(), and setArg().
getArgs() [2/2]
const Expr* const* clang::ObjCMessageExpr::getArgs () const inline
Definition at line 1389 of file ExprObjC.h.
getBeginLoc()
SourceLocation clang::ObjCMessageExpr::getBeginLoc () const inline
Definition at line 1451 of file ExprObjC.h.
Referenced by getSelectorStartLoc().
getCallReturnType()
QualType ObjCMessageExpr::getCallReturnType (ASTContext & Ctx) const
Returns
the return type of the message being sent. This is not always the type of the message expression itself because of references (the expression would not have a reference type). It is also not always the declared return type of the method because of instancetype (in that case it's an expression type).
Definition at line 265 of file ExprObjC.cpp.
References getMethodDecl(), clang::ASTContext::getObjCInstanceType(), clang::ASTContext::getReferenceQualifiedType(), and clang::Expr::getType().
Referenced by clang::JSONNodeDumper::VisitObjCMessageExpr().
getClassReceiver()
QualType clang::ObjCMessageExpr::getClassReceiver () const inline
Returns the type of a class message send, or NULL if the message is not a class message.
Definition at line 1279 of file ExprObjC.h.
References getClassReceiverTypeInfo().
Referenced by clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), getReceiverType(), maybeAdjustInterfaceForSubscriptingCheck(), and clang::JSONNodeDumper::VisitObjCMessageExpr().
getClassReceiverTypeInfo()
TypeSourceInfo* clang::ObjCMessageExpr::getClassReceiverTypeInfo () const inline
Returns a type-source information of a class message send, or nullptr if the message is not a class message.
Definition at line 1288 of file ExprObjC.h.
References Class, and getReceiverKind().
Referenced by getClassReceiver(), and getReceiverRange().
getEndLoc()
SourceLocation clang::ObjCMessageExpr::getEndLoc () const inline
Definition at line 1452 of file ExprObjC.h.
getInstanceReceiver() [1/2]
Expr* clang::ObjCMessageExpr::getInstanceReceiver () inline
Returns the object expression (receiver) for an instance message, or null for a message that is not an instance message.
Definition at line 1260 of file ExprObjC.h.
References getReceiverKind(), and Instance.
Referenced by canRewriteToSubscriptSyntax(), clang::Sema::checkRetainCycles(), clang::computeDependence(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), getInstanceReceiver(), getReceiverRange(), getReceiverType(), clang::arcmt::trans::hasSideEffects(), clang::sema::FunctionScopeInfo::recordUseOfWeak(), rewriteToArraySubscriptSet(), rewriteToDictionarySubscriptSet(), rewriteToSubscriptGetCommon(), shouldExtendReceiverForInnerPointerMessage(), and tryEmitSpecializedAllocInit().
getInstanceReceiver() [2/2]
const Expr* clang::ObjCMessageExpr::getInstanceReceiver () const inline
Definition at line 1266 of file ExprObjC.h.
References getInstanceReceiver().
getLeftLoc()
SourceLocation clang::ObjCMessageExpr::getLeftLoc () const inline
Definition at line 1416 of file ExprObjC.h.
getMethodDecl() [1/2]
ObjCMethodDecl* clang::ObjCMessageExpr::getMethodDecl () inline
Definition at line 1363 of file ExprObjC.h.
getMethodDecl() [2/2]
const ObjCMethodDecl* clang::ObjCMessageExpr::getMethodDecl () const inline
Definition at line 1356 of file ExprObjC.h.
Referenced by clang::Sema::checkRetainCycles(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExprLValue(), clang::Sema::EmitRelatedResultTypeNote(), findMethodDecl(), getCallReturnType(), clang::ento::ObjCMethodCall::getDecl(), getMethodFamily(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), clang::Expr::isUnusedResultAWarning(), and clang::edit::rewriteToObjCSubscriptSyntax().
getMethodFamily()
ObjCMethodFamily clang::ObjCMessageExpr::getMethodFamily () const inline
Definition at line 1375 of file ExprObjC.h.
References getMethodDecl(), clang::ObjCMethodDecl::getMethodFamily(), clang::Selector::getMethodFamily(), and getSelector().
Referenced by clang::ento::ObjCMethodCall::getMethodFamily(), clang::arcmt::trans::hasSideEffects(), and clang::Expr::isUnusedResultAWarning().
getNumArgs()
unsigned clang::ObjCMessageExpr::getNumArgs () const inline
Return the number of actual arguments in this message, not counting the receiver.
Definition at line 1382 of file ExprObjC.h.
Referenced by clang::Sema::checkRetainCycles(), children(), clang::ento::ObjCMethodCall::getNumArgs(), clang::sema::FunctionScopeInfo::recordUseOfWeak(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToArrayLiteral(), rewriteToArraySubscriptSet(), rewriteToDictionaryLiteral(), rewriteToDictionarySubscriptSet(), rewriteToNumberLiteral(), rewriteToNumericBoxedExpression(), clang::edit::rewriteToObjCSubscriptSyntax(), rewriteToStringBoxedExpression(), rewriteToSubscriptGetCommon(), and shouldNotRewriteImmediateMessageArgs().
getNumSelectorLocs()
unsigned clang::ObjCMessageExpr::getNumSelectorLocs () const inline
Definition at line 1437 of file ExprObjC.h.
References clang::Selector::getNumArgs(), getSelector(), isImplicit(), and clang::Selector::isUnarySelector().
Referenced by getSelectorLocs().
getReceiverInterface()
ObjCInterfaceDecl * ObjCMessageExpr::getReceiverInterface () const
Retrieve the Objective-C interface to which this message is being directed, if known.
This routine cross-cuts all of the different kinds of message sends to determine what the underlying (statically known) type of the receiver will be; use getReceiverKind() to determine whether the message is a class or an instance method, whether it is a send to super or not, etc.
Returns
The Objective-C interface if known, otherwise nullptr.
Definition at line 314 of file ExprObjC.cpp.
References clang::Type::getAs(), getReceiverType(), and clang::T.
Referenced by clang::ento::ObjCMethodCall::getReceiverInterface(), and clang::ento::ObjCMethodCall::getRuntimeDefinition().
getReceiverKind()
ReceiverKind clang::ObjCMessageExpr::getReceiverKind () const inline
Determine the kind of receiver that this message is being sent to.
Definition at line 1234 of file ExprObjC.h.
Referenced by clang::Sema::checkRetainCycles(), children(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), findMethodDecl(), getClassReceiverTypeInfo(), getInstanceReceiver(), getReceiverRange(), getReceiverType(), getSuperLoc(), getSuperType(), clang::arcmt::trans::hasSideEffects(), isClassMessage(), isInstanceMessage(), maybeAdjustInterfaceForSubscriptingCheck(), clang::edit::rewriteToObjCSubscriptSyntax(), shouldExtendReceiverForInnerPointerMessage(), tryEmitSpecializedAllocInit(), and clang::JSONNodeDumper::VisitObjCMessageExpr().
getReceiverRange()
SourceRange ObjCMessageExpr::getReceiverRange () const
Source range of the receiver.
Definition at line 277 of file ExprObjC.cpp.
References Class, getClassReceiverTypeInfo(), getInstanceReceiver(), getReceiverKind(), clang::Stmt::getSourceRange(), clang::TypeLoc::getSourceRange(), getSuperLoc(), clang::TypeSourceInfo::getTypeLoc(), Instance, SuperClass, and SuperInstance.
getReceiverType()
QualType ObjCMessageExpr::getReceiverType () const
Retrieve the receiver type to which this message is being directed.
This routine cross-cuts all of the different kinds of message sends to determine what the underlying (statically known) type of the receiver will be; use getReceiverKind() to determine whether the message is a class or an instance method, whether it is a send to super or not, etc.
Returns
The type of the receiver.
Definition at line 300 of file ExprObjC.cpp.
References Class, getClassReceiver(), getInstanceReceiver(), getReceiverKind(), getSuperType(), clang::Expr::getType(), Instance, SuperClass, and SuperInstance.
Referenced by findMethodDecl(), and getReceiverInterface().
getRightLoc()
SourceLocation clang::ObjCMessageExpr::getRightLoc () const inline
Definition at line 1417 of file ExprObjC.h.
getSelector()
Selector ObjCMessageExpr::getSelector () const
Definition at line 293 of file ExprObjC.cpp.
Referenced by clang::Sema::checkRetainCycles(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), findMethodDecl(), getMethodFamily(), getNumSelectorLocs(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), clang::ento::ObjCMethodCall::getSelector(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToArrayLiteral(), rewriteToBoolLiteral(), rewriteToCharLiteral(), rewriteToDictionaryLiteral(), rewriteToNumberLiteral(), rewriteToNumericBoxedExpression(), clang::edit::rewriteToObjCSubscriptSyntax(), rewriteToStringBoxedExpression(), shouldNotRewriteImmediateMessageArgs(), tryEmitSpecializedAllocInit(), and clang::JSONNodeDumper::VisitObjCMessageExpr().
getSelectorLoc()
SourceLocation clang::ObjCMessageExpr::getSelectorLoc (unsigned Index) const inline
Definition at line 1425 of file ExprObjC.h.
Referenced by getSelectorLocs(), and getSelectorStartLoc().
getSelectorLocs()
void ObjCMessageExpr::getSelectorLocs (SmallVectorImpl< SourceLocation > & SelLocs) const
Definition at line 258 of file ExprObjC.cpp.
References getNumSelectorLocs(), and getSelectorLoc().
getSelectorStartLoc()
SourceLocation clang::ObjCMessageExpr::getSelectorStartLoc () const inline
Definition at line 1419 of file ExprObjC.h.
References getBeginLoc(), getSelectorLoc(), and isImplicit().
getSuperLoc()
SourceLocation clang::ObjCMessageExpr::getSuperLoc () const inline
Retrieve the location of the 'super' keyword for a class or instance message to 'super', otherwise an invalid source location.
Definition at line 1301 of file ExprObjC.h.
References getReceiverKind(), SuperClass, and SuperInstance.
Referenced by clang::Sema::checkRetainCycles(), and getReceiverRange().
getSuperType()
QualType clang::ObjCMessageExpr::getSuperType () const inline
Retrieve the type referred to by 'super'.
The returned type will either be an ObjCInterfaceType (for an class message to super) or an ObjCObjectPointerType that refers to a class (for an instance message to super);
Definition at line 1336 of file ExprObjC.h.
References clang::QualType::getFromOpaquePtr(), getReceiverKind(), SuperClass, and SuperInstance.
Referenced by clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), getReceiverType(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), maybeAdjustInterfaceForSubscriptingCheck(), and clang::JSONNodeDumper::VisitObjCMessageExpr().
isClassMessage()
bool clang::ObjCMessageExpr::isClassMessage () const inline
Determine whether this is an class message to either a specified class or to super.
Definition at line 1254 of file ExprObjC.h.
References Class, getReceiverKind(), and SuperClass.
isDelegateInitCall()
bool clang::ObjCMessageExpr::isDelegateInitCall () const inline
isDelegateInitCall - Answers whether this message send has been tagged as a "delegate init call", i.e.
a call to a method in the -init family on self from within an -init method implementation.
Definition at line 1413 of file ExprObjC.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr().
isImplicit()
bool clang::ObjCMessageExpr::isImplicit () const inline
Indicates whether the message send was implicitly generated by the implementation.
If false, it was written explicitly in the source code.
Definition at line 1230 of file ExprObjC.h.
Referenced by getNumSelectorLocs(), getSelectorStartLoc(), and clang::edit::rewriteToObjCSubscriptSyntax().
isInstanceMessage()
bool clang::ObjCMessageExpr::isInstanceMessage () const inline
Determine whether this is an instance message to either a computed object or to super.
Definition at line 1248 of file ExprObjC.h.
References getReceiverKind(), Instance, and SuperInstance.
Referenced by clang::Sema::checkRetainCycles(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), clang::ento::ObjCMethodCall::isInstanceMessage(), and clang::Expr::isUnusedResultAWarning().
setArg()
void clang::ObjCMessageExpr::setArg (unsigned Arg, Expr * ArgExpr) inline
setArg - Set the specified argument.
Definition at line 1405 of file ExprObjC.h.
References getArgs().
setClassReceiver()
void clang::ObjCMessageExpr::setClassReceiver (TypeSourceInfo * TSInfo) inline
Definition at line 1294 of file ExprObjC.h.
References Class.
setDelegateInitCall()
void clang::ObjCMessageExpr::setDelegateInitCall (bool isDelegate) inline
Definition at line 1414 of file ExprObjC.h.
setInstanceReceiver()
void clang::ObjCMessageExpr::setInstanceReceiver (Expr * rec) inline
Turn this message send into an instance message that computes the receiver object with the given expression.
Definition at line 1272 of file ExprObjC.h.
References Instance.
setMethodDecl()
void clang::ObjCMessageExpr::setMethodDecl (ObjCMethodDecl * MD) inline
Definition at line 1370 of file ExprObjC.h.
setSelector()
void clang::ObjCMessageExpr::setSelector (Selector S) inline
Definition at line 1351 of file ExprObjC.h.
setSourceRange()
void clang::ObjCMessageExpr::setSourceRange (SourceRange R) inline
Definition at line 1446 of file ExprObjC.h.
References clang::SourceRange::getBegin(), and clang::SourceRange::getEnd().
setSuper()
void clang::ObjCMessageExpr::setSuper (SourceLocation Loc, QualType T, bool IsInstanceSuper) inline
Definition at line 1343 of file ExprObjC.h.
References SuperClass, SuperInstance, and clang::T.
Friends And Related Function Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 1106 of file ExprObjC.h.
ASTStmtWriter
friend class ASTStmtWriter friend
Definition at line 1107 of file ExprObjC.h.
Member Data Documentation
TrailingObjects
friend clang::ObjCMessageExpr::TrailingObjects
Definition at line 1108 of file ExprObjC.h.
The documentation for this class was generated from the following files:
include/clang/AST/ExprObjC.h
lib/AST/ExprObjC.cpp