clang: clang::APValue::LValuePathEntry Class Reference
clang::APValue::LValuePathEntry Class Reference
A non-discriminated union of a base, field, or array index.
#include "clang/AST/APValue.h"
Public Member Functions
LValuePathEntry ()
LValuePathEntry (BaseOrMemberType BaseOrMember)
BaseOrMemberType getAsBaseOrMember () const
uint64_t getAsArrayIndex () const
void Profile (llvm::FoldingSetNodeID &ID) const
Static Public Member Functions
static LValuePathEntry ArrayIndex (uint64_t Index)
Friends
bool operator== (LValuePathEntry A, LValuePathEntry B)
bool operator!= (LValuePathEntry A, LValuePathEntry B)
llvm::hash_code hash_value (LValuePathEntry A)
Detailed Description
A non-discriminated union of a base, field, or array index.
Definition at line 208 of file APValue.h.
Constructor & Destructor Documentation
LValuePathEntry() [1/2]
clang::APValue::LValuePathEntry::LValuePathEntry () inline
Definition at line 214 of file APValue.h.
LValuePathEntry() [2/2]
APValue::LValuePathEntry::LValuePathEntry (BaseOrMemberType BaseOrMember)
Definition at line 147 of file APValue.cpp.
Member Function Documentation
ArrayIndex()
static LValuePathEntry clang::APValue::LValuePathEntry::ArrayIndex (uint64_t Index) inline static
Definition at line 216 of file APValue.h.
Referenced by clang::ASTNodeImporter::ImportAPValue(), clang::serialization::DataStreamBasicReader< Impl >::readLValuePathSerializationHelper(), and clang::interp::Pointer::toAPValue().
getAsArrayIndex()
uint64_t clang::APValue::LValuePathEntry::getAsArrayIndex () const inline
Definition at line 226 of file APValue.h.
getAsBaseOrMember()
BaseOrMemberType clang::APValue::LValuePathEntry::getAsBaseOrMember () const inline
Definition at line 222 of file APValue.h.
Profile()
void APValue::LValuePathEntry::Profile (llvm::FoldingSetNodeID & ID) const
Definition at line 153 of file APValue.cpp.
References ID.
Friends And Related Function Documentation
hash_value
llvm::hash_code hash_value (LValuePathEntry A) friend
Definition at line 236 of file APValue.h.
operator!=
bool operator!= (LValuePathEntry A, LValuePathEntry B) friend
Definition at line 233 of file APValue.h.
operator==
bool operator== (LValuePathEntry A, LValuePathEntry B) friend
Definition at line 230 of file APValue.h.
The documentation for this class was generated from the following files:
include/clang/AST/APValue.h
lib/AST/APValue.cpp