clang: clang::GenerateModuleInterfaceAction Class Reference
clang::GenerateModuleInterfaceAction Class Reference
Generates full BMI (which contains full information to generate the object files) for C++20 Named Modules.
#include "clang/Frontend/FrontendActions.h"
Protected Member Functions
bool BeginSourceFileAction (CompilerInstance &CI) override
Callback at the start of processing a single input.
std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile) override
Create the AST consumer object for this action, if supported.
TranslationUnitKind getTranslationUnitKind () override
For AST-based actions, the kind of translation unit we're handling.
std::unique_ptr< raw_pwrite_stream > CreateOutputFile (CompilerInstance &CI, StringRef InFile) override
Protected Member Functions inherited from clang::GenerateModuleAction
std::vector< std::unique_ptr< ASTConsumer > > CreateMultiplexConsumer (CompilerInstance &CI, StringRef InFile)
bool hasASTFileSupport () const override
Does this action support use with AST files?
bool shouldEraseOutputFiles () override
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Protected Member Functions inherited from clang::ASTFrontendAction
void ExecuteAction () override
Implement the ExecuteAction interface by running Sema on the already-initialized AST consumer.
Protected Member Functions inherited from clang::FrontendAction
virtual bool PrepareToExecuteAction (CompilerInstance &CI)
Prepare to execute the action on the given CompilerInstance.
virtual bool BeginInvocation (CompilerInstance &CI)
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
virtual void EndSourceFileAction ()
Callback at the end of processing a single input.
Additional Inherited Members
Public Member Functions inherited from clang::ASTFrontendAction
ASTFrontendAction ()
bool usesPreprocessorOnly () const override
Does this action only use the preprocessor?
Public Member Functions inherited from clang::FrontendAction
FrontendAction ()
virtual ~FrontendAction ()
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
virtual bool hasPCHSupport () const
Does this action support use with PCH?
virtual bool hasIRSupport () const
Does this action support use with IR files?
virtual bool hasCodeCompletionSupport () const
Does this action support use with code completion?
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
virtual void EndSourceFile ()
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Detailed Description
Generates full BMI (which contains full information to generate the object files) for C++20 Named Modules.
Definition at line 157 of file FrontendActions.h.
Member Function Documentation
BeginSourceFileAction()
bool GenerateModuleInterfaceAction::BeginSourceFileAction (CompilerInstance & CI) override protected virtual
Callback at the start of processing a single input.
Returns
True on success; on failure ExecutionAction() and EndSourceFileAction() will not be called.
Reimplemented from clang::FrontendAction.
Definition at line 265 of file FrontendActions.cpp.
References clang::FrontendAction::BeginSourceFileAction(), clang::LangOptionsBase::CMK_ModuleInterface, and clang::CompilerInstance::getLangOpts().
CreateASTConsumer()
std::unique_ptr< ASTConsumer > GenerateModuleInterfaceAction::CreateASTConsumer (CompilerInstance & CI, StringRef InFile) override protected virtual
Create the AST consumer object for this action, if supported.
This routine is called as part of BeginSourceFile(), which will fail if the AST consumer cannot be created. This will not be called if the action has indicated that it only uses the preprocessor.
Parameters
CI - The current compiler instance, provided as a convenience, see getCompilerInstance().
InFile - The current input file, provided as a convenience, see getCurrentFile().
Returns
The new AST consumer, or null on failure.
Reimplemented from clang::GenerateModuleAction.
Definition at line 273 of file FrontendActions.cpp.
References clang::GenerateModuleAction::CreateMultiplexConsumer(), clang::FrontendOptions::GenReducedBMI, clang::CompilerInstance::getFrontendOpts(), clang::CompilerInstance::getHeaderSearchOpts(), clang::CompilerInstance::getModuleCache(), clang::CompilerInstance::getPreprocessor(), clang::FrontendOptions::ModuleOutputPath, clang::HeaderSearchOptions::ModulesSkipDiagnosticOptions, clang::HeaderSearchOptions::ModulesSkipHeaderSearchPaths, and clang::HeaderSearchOptions::ModulesSkipPragmaDiagnosticMappings.
CreateOutputFile()
std::unique_ptr< raw_pwrite_stream > GenerateModuleInterfaceAction::CreateOutputFile (CompilerInstance & CI, StringRef InFile) override protected virtual
Implements clang::GenerateModuleAction.
Definition at line 295 of file FrontendActions.cpp.
References clang::CompilerInstance::createDefaultOutputFile().
getTranslationUnitKind()
TranslationUnitKind clang::GenerateModuleInterfaceAction::getTranslationUnitKind () inline override protected virtual
For AST-based actions, the kind of translation unit we're handling.
Reimplemented from clang::GenerateModuleAction.
Definition at line 164 of file FrontendActions.h.
References clang::TU_Complete.
The documentation for this class was generated from the following files:
include/clang/Frontend/FrontendActions.h
lib/Frontend/FrontendActions.cpp