clang: clang::ento::NoteTag Class Reference
clang::ento::NoteTag Class Reference
The tag upon which the TagVisitor reacts.
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
Public Types
using Callback = std::function< std::string(BugReporterContext &, PathSensitiveBugReport &)>
Public Member Functions
Optional< std::string > generateMessage (BugReporterContext &BRC, PathSensitiveBugReport &R) const
StringRef getTagDescription () const override
bool isPrunable () const
Public Member Functions inherited from clang::ProgramPointTag
ProgramPointTag (void *tagKind=nullptr)
virtual ~ProgramPointTag ()
const void * getTagKind () const
Used to implement 'isKind' in subclasses.
Static Public Member Functions
static bool classof (const ProgramPointTag *T)
Friends
class Factory
class TagVisitor
Additional Inherited Members
Protected Member Functions inherited from clang::ento::DataTag
DataTag (void *TagKind)
Detailed Description
The tag upon which the TagVisitor reacts.
Add these in order to display additional PathDiagnosticEventPieces along the path.
Definition at line 763 of file BugReporter.h.
Member Typedef Documentation
Callback
using clang::ento::NoteTag::Callback = std::function<std::string(BugReporterContext &, PathSensitiveBugReport &)>
Definition at line 766 of file BugReporter.h.
Member Function Documentation
classof()
static bool clang::ento::NoteTag::classof (const ProgramPointTag * T) inline static
Definition at line 778 of file BugReporter.h.
References clang::ProgramPointTag::getTagKind().
generateMessage()
Optional<std::string> clang::ento::NoteTag::generateMessage (BugReporterContext & BRC, PathSensitiveBugReport & R) const inline
Definition at line 782 of file BugReporter.h.
References string().
Referenced by clang::ento::TagVisitor::VisitNode().
getTagDescription()
StringRef clang::ento::NoteTag::getTagDescription () const inline override virtual
Reimplemented from clang::ento::DataTag.
Definition at line 791 of file BugReporter.h.
isPrunable()
bool clang::ento::NoteTag::isPrunable () const inline
Definition at line 798 of file BugReporter.h.
Referenced by clang::ento::TagVisitor::VisitNode().
Friends And Related Function Documentation
Factory
friend class Factory friend
Definition at line 800 of file BugReporter.h.
TagVisitor
friend class TagVisitor friend
Definition at line 801 of file BugReporter.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp