clang: clang::syntax::TokenBufferTokenManager Class Reference
clang::syntax::TokenBufferTokenManager Class Reference
A TokenBuffer-powered token manager.
#include "clang/Tooling/Syntax/TokenBufferTokenManager.h"
Public Member Functions
TokenBufferTokenManager (const TokenBuffer &Tokens, const LangOptions &LangOpts, SourceManager &SourceMgr)
llvm::StringLiteral kind () const override
Describes what the exact class kind of the TokenManager is.
llvm::StringRef getText (Key I) const override
const syntax::Token * getToken (Key I) const
SourceManager & sourceManager ()
const SourceManager & sourceManager () const
const TokenBuffer & tokenBuffer () const
Public Member Functions inherited from clang::syntax::TokenManager
virtual ~TokenManager ()=default
Static Public Member Functions
static bool classof (const TokenManager *N)
Friends
class FactoryImpl
Additional Inherited Members
Public Types inherited from clang::syntax::TokenManager
using Key = uintptr_t
A key to identify a specific token.
Detailed Description
A TokenBuffer-powered token manager.
It tracks the underlying token buffers, source manager, etc.
Definition at line 20 of file TokenBufferTokenManager.h.
Constructor & Destructor Documentation
TokenBufferTokenManager()
clang::syntax::TokenBufferTokenManager::TokenBufferTokenManager (const TokenBuffer & Tokens, const LangOptions & LangOpts, SourceManager & SourceMgr) inline
Definition at line 22 of file TokenBufferTokenManager.h.
Member Function Documentation
classof()
static bool clang::syntax::TokenBufferTokenManager::classof (const TokenManager * N) inline static
Definition at line 26 of file TokenBufferTokenManager.h.
References clang::syntax::TokenManager::kind().
getText()
llvm::StringRef clang::syntax::TokenBufferTokenManager::getText (Key I) const inline override virtual
Implements clang::syntax::TokenManager.
Definition at line 29 of file TokenBufferTokenManager.h.
References clang::comments::tok::eof, getToken(), clang::syntax::Token::kind(), and clang::syntax::Token::text().
Referenced by clang::syntax::deepCopyExpandingMacros().
getToken()
const syntax::Token* clang::syntax::TokenBufferTokenManager::getToken (Key I) const inline
Definition at line 40 of file TokenBufferTokenManager.h.
Referenced by clang::syntax::deepCopyExpandingMacros(), and getText().
kind()
llvm::StringLiteral clang::syntax::TokenBufferTokenManager::kind () const inline override virtual
Describes what the exact class kind of the TokenManager is.
Implements clang::syntax::TokenManager.
Definition at line 27 of file TokenBufferTokenManager.h.
sourceManager() [1/2]
SourceManager& clang::syntax::TokenBufferTokenManager::sourceManager () inline
Definition at line 43 of file TokenBufferTokenManager.h.
Referenced by clang::syntax::computeReplacements().
sourceManager() [2/2]
const SourceManager& clang::syntax::TokenBufferTokenManager::sourceManager () const inline
Definition at line 44 of file TokenBufferTokenManager.h.
tokenBuffer()
const TokenBuffer& clang::syntax::TokenBufferTokenManager::tokenBuffer () const inline
Definition at line 45 of file TokenBufferTokenManager.h.
Referenced by clang::syntax::computeReplacements(), and clang::syntax::TreeBuilder::TreeBuilder().
Friends And Related Function Documentation
FactoryImpl
friend class FactoryImpl friend
Definition at line 56 of file TokenBufferTokenManager.h.
The documentation for this class was generated from the following files:
include/clang/Tooling/Syntax/TokenBufferTokenManager.h
lib/Tooling/Syntax/TokenBufferTokenManager.cpp