clang: clang::CodeGen::CGBuilderTy Class Reference
clang::CodeGen::CGBuilderTy Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGBuilder.h"
Public Member Functions
CGBuilderTy (const CodeGenTypeCache &TypeCache, llvm::LLVMContext &C)
CGBuilderTy (const CodeGenTypeCache &TypeCache, llvm::LLVMContext &C, const llvm::ConstantFolder &F, const CGBuilderInserterTy &Inserter)
CGBuilderTy (const CodeGenTypeCache &TypeCache, llvm::Instruction *I)
CGBuilderTy (const CodeGenTypeCache &TypeCache, llvm::BasicBlock *BB)
llvm::ConstantInt * getSize (CharUnits N)
llvm::ConstantInt * getSize (uint64_t N)
llvm::LoadInst * CreateLoad (Address Addr, const llvm::Twine &Name="")
llvm::LoadInst * CreateLoad (Address Addr, const char *Name)
llvm::LoadInst * CreateLoad (Address Addr, bool IsVolatile, const llvm::Twine &Name="")
llvm::LoadInst * CreateAlignedLoad (llvm::Type *Ty, llvm::Value *Addr, CharUnits Align, const llvm::Twine &Name="")
llvm::StoreInst * CreateStore (llvm::Value *Val, Address Addr, bool IsVolatile=false)
llvm::StoreInst * CreateAlignedStore (llvm::Value *Val, llvm::Value *Addr, CharUnits Align, bool IsVolatile=false)
llvm::StoreInst * CreateDefaultAlignedStore (llvm::Value *Val, llvm::Value *Addr, bool IsVolatile=false)
llvm::LoadInst * CreateFlagLoad (llvm::Value *Addr, const llvm::Twine &Name="")
Emit a load from an i1 flag variable.
llvm::StoreInst * CreateFlagStore (bool Value, llvm::Value *Addr)
Emit a store to an i1 flag variable.
llvm::AtomicCmpXchgInst * CreateAtomicCmpXchg (llvm::Value *Ptr, llvm::Value *Cmp, llvm::Value *New, llvm::AtomicOrdering SuccessOrdering, llvm::AtomicOrdering FailureOrdering, llvm::SyncScope::ID SSID=llvm::SyncScope::System)
llvm::AtomicRMWInst * CreateAtomicRMW (llvm::AtomicRMWInst::BinOp Op, llvm::Value *Ptr, llvm::Value *Val, llvm::AtomicOrdering Ordering, llvm::SyncScope::ID SSID=llvm::SyncScope::System)
Address CreateBitCast (Address Addr, llvm::Type *Ty, const llvm::Twine &Name="")
Address CreateAddrSpaceCast (Address Addr, llvm::Type *Ty, const llvm::Twine &Name="")
Address CreateElementBitCast (Address Addr, llvm::Type *Ty, const llvm::Twine &Name="")
Cast the element type of the given address to a different type, preserving information like the alignment and address space.
Address CreatePointerBitCastOrAddrSpaceCast (Address Addr, llvm::Type *Ty, const llvm::Twine &Name="")
Address CreateStructGEP (Address Addr, unsigned Index, const llvm::Twine &Name="")
Address CreateConstArrayGEP (Address Addr, uint64_t Index, const llvm::Twine &Name="")
Given addr = [n x T]* ...
Address CreateConstInBoundsGEP (Address Addr, uint64_t Index, const llvm::Twine &Name="")
Given addr = T* ...
Address CreateConstGEP (Address Addr, uint64_t Index, const llvm::Twine &Name="")
Given addr = T* ...
Address CreateConstInBoundsByteGEP (Address Addr, CharUnits Offset, const llvm::Twine &Name="")
Given a pointer to i8, adjust it by a given constant offset.
Address CreateConstByteGEP (Address Addr, CharUnits Offset, const llvm::Twine &Name="")
Address CreateConstInBoundsGEP2_32 (Address Addr, unsigned Idx0, unsigned Idx1, const llvm::Twine &Name="")
llvm::CallInst * CreateMemCpy (Address Dest, Address Src, llvm::Value *Size, bool IsVolatile=false)
llvm::CallInst * CreateMemCpy (Address Dest, Address Src, uint64_t Size, bool IsVolatile=false)
llvm::CallInst * CreateMemCpyInline (Address Dest, Address Src, uint64_t Size)
llvm::CallInst * CreateMemMove (Address Dest, Address Src, llvm::Value *Size, bool IsVolatile=false)
llvm::CallInst * CreateMemSet (Address Dest, llvm::Value *Value, llvm::Value *Size, bool IsVolatile=false)
Address CreatePreserveStructAccessIndex (Address Addr, unsigned Index, unsigned FieldIndex, llvm::MDNode *DbgInfo)
Detailed Description
Definition at line 43 of file CGBuilder.h.
Constructor & Destructor Documentation
CGBuilderTy() [1/4]
clang::CodeGen::CGBuilderTy::CGBuilderTy (const CodeGenTypeCache & TypeCache, llvm::LLVMContext & C) inline
Definition at line 48 of file CGBuilder.h.
CGBuilderTy() [2/4]
clang::CodeGen::CGBuilderTy::CGBuilderTy (const CodeGenTypeCache & TypeCache, llvm::LLVMContext & C, const llvm::ConstantFolder & F, const CGBuilderInserterTy & Inserter) inline
Definition at line 50 of file CGBuilder.h.
CGBuilderTy() [3/4]
clang::CodeGen::CGBuilderTy::CGBuilderTy (const CodeGenTypeCache & TypeCache, llvm::Instruction * I) inline
Definition at line 54 of file CGBuilder.h.
CGBuilderTy() [4/4]
clang::CodeGen::CGBuilderTy::CGBuilderTy (const CodeGenTypeCache & TypeCache, llvm::BasicBlock * BB) inline
Definition at line 56 of file CGBuilder.h.
Member Function Documentation
CreateAddrSpaceCast()
Address clang::CodeGen::CGBuilderTy::CreateAddrSpaceCast (Address Addr, llvm::Type * Ty, const llvm::Twine & Name = "") inline
Definition at line 158 of file CGBuilder.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), and clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment().
CreateAlignedLoad()
llvm::LoadInst* clang::CodeGen::CGBuilderTy::CreateAlignedLoad (llvm::Type * Ty, llvm::Value * Addr, CharUnits Align, const llvm::Twine & Name = "") inline
Definition at line 86 of file CGBuilder.h.
Referenced by BuildAppleKextVirtualCall(), createPlaceholderSlot(), clang::CodeGen::CodeGenFunction::EmitBlockCallExpr(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), EmitISOVolatileLoad(), clang::CodeGen::CodeGenFunction::EmitSEHExceptionCodeSave(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), performTypeAdjustment(), clang::CodeGen::DominatingLLVMValue::restore(), and clang::CodeGen::CodeGenFunction::StartFunction().
CreateAlignedStore()
llvm::StoreInst* clang::CodeGen::CGBuilderTy::CreateAlignedStore (llvm::Value * Val, llvm::Value * Addr, CharUnits Align, bool IsVolatile = false) inline
Definition at line 102 of file CGBuilder.h.
References clang::CharUnits::getAsAlign().
Referenced by CreateFlagStore(), CreateStore(), EmitISOVolatileStore(), clang::CodeGen::CodeGenFunction::EmitNVPTXDevicePrintfCallExpr(), and clang::CodeGen::CodeGenFunction::FinallyInfo::exit().
CreateAtomicCmpXchg()
llvm::AtomicCmpXchgInst* clang::CodeGen::CGBuilderTy::CreateAtomicCmpXchg (llvm::Value * Ptr, llvm::Value * Cmp, llvm::Value * New, llvm::AtomicOrdering SuccessOrdering, llvm::AtomicOrdering FailureOrdering, llvm::SyncScope::ID SSID = llvm::SyncScope::System) inline
Definition at line 131 of file CGBuilder.h.
Referenced by emitAtomicCmpXchg(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicCmpXchgForMSIntrin(), and MakeAtomicCmpXchgValue().
CreateAtomicRMW()
llvm::AtomicRMWInst* clang::CodeGen::CGBuilderTy::CreateAtomicRMW (llvm::AtomicRMWInst::BinOp Op, llvm::Value * Ptr, llvm::Value * Val, llvm::AtomicOrdering Ordering, llvm::SyncScope::ID SSID = llvm::SyncScope::System) inline
Definition at line 143 of file CGBuilder.h.
Referenced by EmitAtomicDecrementValue(), EmitAtomicIncrementValue(), EmitAtomicOp(), EmitBinaryAtomicPost(), EmitBitTestIntrinsic(), emitOMPAtomicRMW(), and MakeBinaryAtomicValue().
CreateBitCast()
Address clang::CodeGen::CGBuilderTy::CreateBitCast (Address Addr, llvm::Type * Ty, const llvm::Twine & Name = "") inline
Definition at line 151 of file CGBuilder.h.
Referenced by AddDirectArgument(), AdjustObjCObjectType(), ApplyNonVirtualAndVirtualOffset(), BuildAppleKextVirtualCall(), clang::CodeGen::CodeGenFunction::BuildBlockRelease(), callSpecialFunction(), castValueToType(), CoerceIntOrPtrToIntOrPtr(), CreateCoercedLoad(), clang::CodeGen::CodeGenFunction::defaultInitNonTrivialCStructVar(), clang::CodeGen::CodeGenFunction::EmitAnnotationCall(), clang::CodeGen::CodeGenFunction::EmitAnyExprToExn(), emitARCCopyOperation(), clang::CodeGen::CodeGenFunction::EmitARCDestroyWeak(), emitARCLoadOperation(), clang::CodeGen::CodeGenFunction::EmitARCRelease(), clang::CodeGen::CodeGenFunction::EmitARCRetainAutorelease(), emitARCStoreOperation(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrongCall(), emitARCValueOperation(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), EmitAtomicCmpXchg128ForMSIntrin(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), clang::CodeGen::CodeGenFunction::EmitAutoVarInit(), EmitBinaryAtomicPost(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitCastToVoidPtr(), emitCatchDispatchBlock(), clang::CodeGen::CodeGenFunction::EmitCfiSlowPathCheck(), clang::CodeGen::CodeGenFunction::EmitCheck(), clang::CodeGen::CodeGenFunction::EmitCheckValue(), EmitCommonNeonSISDBuiltinExpr(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitCXXTypeidExpr(), clang::CodeGen::CodeGenFunction::EmitDeleteCall(), clang::CodeGen::CodeGenFunction::EmitExtendGCLifetime(), clang::CodeGen::CodeGenFunction::EmitFieldAnnotations(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::CodeGenFunction::EmitIntelFPGAFieldAnnotations(), EmitISOVolatileLoad(), EmitISOVolatileStore(), clang::CodeGen::CodeGenFunction::EmitLifetimeEnd(), clang::CodeGen::CodeGenFunction::EmitLifetimeStart(), clang::CodeGen::CodeGenFunction::EmitMustTailThunk(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), EmitNontemporalStore(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), clang::CodeGen::CodeGenFunction::EmitObjCBoxedExpr(), clang::CodeGen::CodeGenFunction::EmitObjCCollectionLiteral(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), clang::CodeGen::CodeGenFunction::EmitObjCRelease(), emitObjCValueOperation(), clang::CodeGen::CodeGenFunction::EmitOMPUseDevicePtrClause(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), emitPointerArithmetic(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::EmitSEHExceptionCodeSave(), EmitSignBit(), emitStructGetterCall(), emitStructSetterCall(), clang::CodeGen::CodeGenFunction::EmitSynthesizedCXXCopyCtorCall(), clang::CodeGen::CGOpenMPRuntime::emitTeamsCall(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), clang::CodeGen::CodeGenFunction::EmitTypeMetadataCodeForVCall(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), clang::CodeGen::CodeGenFunction::EmitVarAnnotations(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheck(), clang::CodeGen::CodeGenFunction::EmitVTableTypeCheckedLoad(), emitWriteback(), emitWritebackArg(), EmitX86_64VAArgFromMemory(), EmitX86CompressStore(), EmitX86CvtBF16ToFloatExpr(), EmitX86CvtF16ToFloatExpr(), EmitX86ExpandLoad(), EmitX86MaskedLoad(), EmitX86MaskedStore(), EmitX86MaskLogic(), EmitX86Muldq(), EmitX86ScalarSelect(), generateByrefCopyHelper(), generateByrefDisposeHelper(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), clang::CodeGen::CodeGenFunction::generateObjCGetterBody(), clang::CodeGen::CodeGenFunction::generateObjCSetterBody(), clang::CodeGen::CodeGenFunction::GenerateVarArgsThunk(), clang::CodeGen::CodeGenFunction::GetAddressOfBaseClass(), clang::CodeGen::CodeGenFunction::GetAddressOfDerivedClass(), clang::CodeGen::CodeGenFunction::GetAddrOfBlockDecl(), getMaskVecValue(), InitCatchParam(), MakeAtomicCmpXchgValue(), MakeBinaryAtomicValue(), performTypeAdjustment(), clang::CodeGen::CodeGenFunction::recoverAddrOfEscapedLocal(), tryEmitFusedAutoreleaseOfResult(), and tryRemoveRetainOfSelf().
CreateConstArrayGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstArrayGEP (Address Addr, uint64_t Index, const llvm::Twine & Name = "") inline
Given addr = [n x T]* ...
produce name = getelementptr inbounds addr, i64 0, i64 index where i64 is actually the target word size.
This API assumes that drilling into an array like this is always an inbounds operation.
Definition at line 208 of file CGBuilder.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitArrayToPointerDecay(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossOrdered(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), emitNonContiguousDescriptor(), clang::CodeGen::CodeGenFunction::EmitObjCCollectionLiteral(), emitOMPArraySectionBase(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), and clang::CodeGen::CGOpenMPRuntime::emitSingleRegion().
CreateConstByteGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstByteGEP (Address Addr, CharUnits Offset, const llvm::Twine & Name = "") inline
Definition at line 261 of file CGBuilder.h.
CreateConstGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstGEP (Address Addr, uint64_t Index, const llvm::Twine & Name = "") inline
Given addr = T* ...
produce name = getelementptr inbounds addr, i64 index where i64 is actually the target word size.
Definition at line 242 of file CGBuilder.h.
Referenced by shuffleAndStore().
CreateConstInBoundsByteGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP (Address Addr, CharUnits Offset, const llvm::Twine & Name = "") inline
Given a pointer to i8, adjust it by a given constant offset.
Definition at line 254 of file CGBuilder.h.
Referenced by emitAddressAtOffset(), EmitNullBaseClassInitialization(), emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenFunction::GetAddressOfDirectBaseInCompleteClass(), performTypeAdjustment(), and clang::CodeGen::CGCXXABI::ReadArrayCookie().
CreateConstInBoundsGEP()
Address clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP (Address Addr, uint64_t Index, const llvm::Twine & Name = "") inline
Given addr = T* ...
produce name = getelementptr inbounds addr, i64 index where i64 is actually the target word size.
Definition at line 226 of file CGBuilder.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitExtVectorElementLValue(), and clang::CodeGen::CodeGenFunction::EmitLValueForField().
CreateConstInBoundsGEP2_32()
Address clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP2_32 (Address Addr, unsigned Idx0, unsigned Idx1, const llvm::Twine & Name = "") inline
Definition at line 269 of file CGBuilder.h.
Referenced by emitNonContiguousDescriptor().
CreateDefaultAlignedStore()
llvm::StoreInst* clang::CodeGen::CGBuilderTy::CreateDefaultAlignedStore (llvm::Value * Val, llvm::Value * Addr, bool IsVolatile = false) inline
Definition at line 109 of file CGBuilder.h.
CreateElementBitCast()
Address clang::CodeGen::CGBuilderTy::CreateElementBitCast (Address Addr, llvm::Type * Ty, const llvm::Twine & Name = "") inline
Cast the element type of the given address to a different type, preserving information like the alignment and address space.
Definition at line 166 of file CGBuilder.h.
Referenced by CheckAggExprForMemSetUse(), CreateCoercedStore(), emitAddressAtOffset(), clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::emitArrayLength(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitArrayToPointerDecay(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::ReductionCodeGen::emitCleanups(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitCXXUuidofExpr(), clang::CodeGen::CodeGenFunction::EmitExtVectorElementLValue(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::ReductionCodeGen::emitInitialization(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitLValueForFieldInitialization(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), emitNonZeroVLAInit(), EmitNullBaseClassInitialization(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), clang::CodeGen::CodeGenFunction::EmitObjCIsaExpr(), EmitOMPAggregateInit(), emitOMPArraySectionBase(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), EmitThreadPrivateVarDeclLValue(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenFunction::generateObjCSetterBody(), clang::CodeGen::CodeGenFunction::GetAddressOfDirectBaseInCompleteClass(), clang::CodeGen::CodeGenFunction::GetVTablePtr(), loadToBegin(), MaybeConvertMatrixAddress(), performTypeAdjustment(), clang::CodeGen::CGCXXABI::ReadArrayCookie(), and tryEmitARCCopyWeakInit().
CreateFlagLoad()
llvm::LoadInst* clang::CodeGen::CGBuilderTy::CreateFlagLoad (llvm::Value * Addr, const llvm::Twine & Name = "") inline
Emit a load from an i1 flag variable.
Definition at line 116 of file CGBuilder.h.
CreateFlagStore()
llvm::StoreInst* clang::CodeGen::CGBuilderTy::CreateFlagStore (bool Value, llvm::Value * Addr) inline
Emit a store to an i1 flag variable.
Definition at line 123 of file CGBuilder.h.
References CreateAlignedStore(), and clang::CharUnits::One().
Referenced by clang::CodeGen::CodeGenFunction::FinallyInfo::enter(), and clang::CodeGen::CodeGenFunction::FinallyInfo::exit().
CreateLoad() [1/3]
llvm::LoadInst* clang::CodeGen::CGBuilderTy::CreateLoad (Address Addr, bool IsVolatile, const llvm::Twine & Name = "") inline
Definition at line 78 of file CGBuilder.h.
CreateLoad() [2/3]
llvm::LoadInst* clang::CodeGen::CGBuilderTy::CreateLoad (Address Addr, const char * Name) inline
Definition at line 72 of file CGBuilder.h.
CreateLoad() [3/3]
llvm::LoadInst* clang::CodeGen::CGBuilderTy::CreateLoad (Address Addr, const llvm::Twine & Name = "") inline
Definition at line 68 of file CGBuilder.h.
Referenced by CreateCoercedLoad(), clang::CodeGen::CodeGenFunction::DecodeAddrUsedInPrologue(), clang::CodeGen::CodeGenFunction::EmitARCDestroyStrong(), emitAtomicCmpXchg(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicOp(), EmitBitTestIntrinsic(), clang::CodeGen::CodeGenFunction::emitBlockByrefAddress(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCfiCheckFail(), EmitCleanup(), clang::CodeGen::CodeGenFunction::EmitCXXPseudoDestructorExpr(), clang::CodeGen::CodeGenFunction::EmitDelegateCallArg(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::CodeGenFunction::EmitLoadOfBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfExtVectorElementLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfPointer(), clang::CodeGen::CodeGenFunction::EmitLoadOfReference(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), EmitMemberInitializer(), emitOMPArraySectionBase(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::CodeGenFunction::EmitReturnValueCheck(), clang::CodeGen::CodeGenFunction::EmitSEHExceptionCode(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughExtVectorComponentLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), emitVoidPtrDirectVAArg(), emitVoidPtrVAArg(), emitWriteback(), EmitX86_64VAArgFromMemory(), clang::CodeGen::CodeGenFunction::GenerateBlockFunction(), generateByrefCopyHelper(), generateByrefDisposeHelper(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateCXXGlobalInitFunc(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), clang::CodeGen::CodeGenFunction::generateObjCGetterBody(), clang::CodeGen::CodeGenFunction::generateObjCSetterBody(), clang::CodeGen::CodeGenFunction::GetAddrOfBlockDecl(), clang::CodeGen::CodeGenFunction::getExceptionFromSlot(), clang::CodeGen::CodeGenFunction::getSelectorFromSlot(), clang::CodeGen::CodeGenFunction::GetVTablePtr(), clang::CodeGen::CGCXXABI::loadIncomingCXXThis(), and performTypeAdjustment().
CreateMemCpy() [1/2]
llvm::CallInst* clang::CodeGen::CGBuilderTy::CreateMemCpy (Address Dest, Address Src, llvm::Value * Size, bool IsVolatile = false) inline
Definition at line 285 of file CGBuilder.h.
References clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by CreateCoercedLoad(), CreateCoercedStore(), CreateMemCpy(), clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::EmitCall(), emitDepobjElements(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), emitNonZeroVLAInit(), EmitNullBaseClassInitialization(), and clang::CodeGen::CodeGenFunction::EmitNullInitialization().
CreateMemCpy() [2/2]
llvm::CallInst* clang::CodeGen::CGBuilderTy::CreateMemCpy (Address Dest, Address Src, uint64_t Size, bool IsVolatile = false) inline
Definition at line 291 of file CGBuilder.h.
References CreateMemCpy(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
CreateMemCpyInline()
llvm::CallInst* clang::CodeGen::CGBuilderTy::CreateMemCpyInline (Address Dest, Address Src, uint64_t Size) inline
Definition at line 299 of file CGBuilder.h.
References clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
CreateMemMove()
llvm::CallInst* clang::CodeGen::CGBuilderTy::CreateMemMove (Address Dest, Address Src, llvm::Value * Size, bool IsVolatile = false) inline
Definition at line 306 of file CGBuilder.h.
References clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
CreateMemSet()
llvm::CallInst* clang::CodeGen::CGBuilderTy::CreateMemSet (Address Dest, llvm::Value * Value, llvm::Value * Size, bool IsVolatile = false) inline
Definition at line 314 of file CGBuilder.h.
References clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by CheckAggExprForMemSetUse(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), EmitNullBaseClassInitialization(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), and initializeAlloca().
CreatePointerBitCastOrAddrSpaceCast()
Address clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast (Address Addr, llvm::Type * Ty, const llvm::Twine & Name = "") inline
Definition at line 173 of file CGBuilder.h.
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), castToBase(), castValueToType(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), CreateCoercedStore(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), emitDepobjElements(), emitDepobjElementsSizes(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), emitNonContiguousDescriptor(), clang::CodeGen::CodeGenFunction::EmitOMPUseDeviceAddrClause(), clang::CodeGen::CGOpenMPRuntimeGPU::emitOutlinedFunctionCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), emitPrivatesInit(), emitShuffleAndReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), clang::CodeGen::CGOpenMPRuntime::getTaskReductionItem(), clang::CodeGen::CodeGenFunction::InitializeVTablePointer(), clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), shuffleAndStore(), and clang::CodeGen::CodeGenFunction::StartFunction().
CreatePreserveStructAccessIndex()
Address clang::CodeGen::CGBuilderTy::CreatePreserveStructAccessIndex (Address Addr, unsigned Index, unsigned FieldIndex, llvm::MDNode * DbgInfo) inline
Definition at line 321 of file CGBuilder.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLValueForField(), and emitPreserveStructAccess().
CreateStore()
llvm::StoreInst* clang::CodeGen::CGBuilderTy::CreateStore (llvm::Value * Val, Address Addr, bool IsVolatile = false) inline
Definition at line 95 of file CGBuilder.h.
References CreateAlignedStore(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), and clang::CodeGen::Address::getPointer().
Referenced by castToBase(), clang::CodeGen::CodeGenFunction::createCleanupActiveFlag(), CreateCoercedStore(), clang::CodeGen::CodeGenFunction::EmitAggregateStore(), clang::CodeGen::CodeGenFunction::EmitARCInitWeak(), EmitAtomicCmpXchg128ForMSIntrin(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), EmitAtomicOp(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), EmitBitTestIntrinsic(), clang::CodeGen::CodeGenFunction::emitByrefStructureInit(), clang::CodeGen::CodeGenFunction::EmitCall(), EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), clang::CodeGen::CodeGenFunction::EmitCheckValue(), clang::CodeGen::CodeGenFunction::EmitDelegateCallArg(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), emitGlobalToListReduceFunction(), clang::CodeGen::CGObjCRuntime::EmitInitOfCatchParam(), clang::CodeGen::CodeGenFunction::EmitLandingPad(), emitListToGlobalReduceFunction(), clang::CodeGen::CodeGenFunction::EmitMustTailThunk(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), emitNonContiguousDescriptor(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), clang::CodeGen::CodeGenFunction::EmitSEHExceptionCodeSave(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughExtVectorComponentLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), EmitSystemZIntrinsicWithCC(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups(), emitVoidPtrDirectVAArg(), emitWasmCatchPadBlock(), emitWritebackArg(), EmitX86_64VAArgFromMemory(), clang::CodeGen::CodeGenFunction::GenerateBlockFunction(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateCXXGlobalInitFunc(), clang::CodeGen::CodeGenFunction::generateObjCGetterBody(), clang::CodeGen::CodeGenFunction::generateObjCSetterBody(), clang::CodeGen::CodeGenFunction::GenerateSEHFilterFunction(), InitCatchParam(), clang::CodeGen::CodeGenFunction::InitializeVTablePointer(), clang::CodeGen::CodeGenFunction::PopCleanupBlocks(), clang::CodeGen::DominatingLLVMValue::save(), clang::CodeGen::CodeGenFunction::setBlockContextParameter(), SetupCleanupBlockActivation(), clang::CodeGen::CodeGenFunction::OMPMapVars::setVarAddr(), and clang::CodeGen::CodeGenFunction::StartFunction().
CreateStructGEP()
Address clang::CodeGen::CGBuilderTy::CreateStructGEP (Address Addr, unsigned Index, const llvm::Twine & Name = "") inline
Definition at line 188 of file CGBuilder.h.
Referenced by emitAddrOfFieldStorage(), clang::CodeGen::CodeGenFunction::emitAddrOfImagComponent(), clang::CodeGen::CodeGenFunction::emitAddrOfRealComponent(), clang::CodeGen::CodeGenFunction::EmitAggregateStore(), clang::CodeGen::CodeGenFunction::emitBlockByrefAddress(), clang::CodeGen::CodeGenFunction::EmitBlockCallExpr(), clang::CodeGen::CodeGenFunction::emitByrefStructureInit(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitNVPTXDevicePrintfCallExpr(), clang::CodeGen::CodeGenFunction::EmitSEHExceptionCodeSave(), EmitX86_64VAArgFromMemory(), EnterStructPointerForCoercedAccess(), clang::CodeGen::CodeGenFunction::GenerateBlockFunction(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfBlockDecl(), and clang::CodeGen::CodeGenFunction::StartFunction().
getSize() [1/2]
llvm::ConstantInt* clang::CodeGen::CGBuilderTy::getSize (CharUnits N) inline
Definition at line 59 of file CGBuilder.h.
References clang::CharUnits::getQuantity(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer().
getSize() [2/2]
llvm::ConstantInt* clang::CodeGen::CGBuilderTy::getSize (uint64_t N) inline
Definition at line 62 of file CGBuilder.h.
References clang::CodeGen::CodeGenTypeCache::SizeTy.
The documentation for this class was generated from the following file:
lib/CodeGen/CGBuilder.h