clang: clang::ento::RetainSummaryManager Class Reference
clang::ento::RetainSummaryManager Class Reference
#include "clang/Analysis/RetainSummaryManager.h"
Public Types
enum BehaviorSummary { BehaviorSummary::NoOp, BehaviorSummary::Identity, BehaviorSummary::IdentityThis, BehaviorSummary::IdentityOrZero }
Public Member Functions
RetainSummaryManager (ASTContext &ctx, bool trackObjCAndCFObjects, bool trackOSObjects)
Optional< BehaviorSummary > canEval (const CallExpr *CE, const FunctionDecl *FD, bool &hasTrustedImplementationAnnotation)
bool isTrustedReferenceCountImplementation (const Decl *FD)
const RetainSummary * getSummary (AnyCall C, bool HasNonZeroCallbackArg=false, bool IsReceiverUnconsumedSelf=false, QualType ReceiverType={})
RetEffect getObjAllocRetEffect () const
Static Public Member Functions
static bool isKnownSmartPointer (QualType QT)
Friends
class RetainSummaryTemplate
Detailed Description
Definition at line 449 of file RetainSummaryManager.h.
Member Enumeration Documentation
BehaviorSummary
enum clang::ento::RetainSummaryManager::BehaviorSummary strong
Enumerator
NoOp
Identity
IdentityThis
IdentityOrZero
Definition at line 637 of file RetainSummaryManager.h.
Constructor & Destructor Documentation
RetainSummaryManager()
clang::ento::RetainSummaryManager::RetainSummaryManager (ASTContext & ctx, bool trackObjCAndCFObjects, bool trackOSObjects) inline
Definition at line 624 of file RetainSummaryManager.h.
Member Function Documentation
canEval()
Optional< RetainSummaryManager::BehaviorSummary > RetainSummaryManager::canEval (const CallExpr * CE, const FunctionDecl * FD, bool & hasTrustedImplementationAnnotation)
Definition at line 722 of file RetainSummaryManager.cpp.
References clang::CallExpr::getCallReturnType(), clang::FunctionDecl::getDefinition(), clang::NamedDecl::getIdentifier(), clang::IdentifierInfo::getName(), clang::CallExpr::getNumArgs(), Identity, IdentityOrZero, IdentityThis, isAutorelease(), isMakeCollectable(), clang::Type::isObjCIdType(), isOSObjectDynamicCast(), isOSObjectRequiredCast(), isOSObjectSubclass(), isOSObjectThisCast(), clang::Type::isPointerType(), clang::ento::cocoa::isRefType(), isRetain(), clang::IdentifierInfo::isStr(), isTrustedReferenceCountImplementation(), NoOp, clang::FunctionDecl::param_size(), and Parent.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::evalCall().
getObjAllocRetEffect()
RetEffect clang::ento::RetainSummaryManager::getObjAllocRetEffect () const inline
Definition at line 665 of file RetainSummaryManager.h.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkSummary().
getSummary()
const RetainSummary * RetainSummaryManager::getSummary (AnyCall C, bool HasNonZeroCallbackArg = false, bool IsReceiverUnconsumedSelf = false, QualType ReceiverType = {})
Definition at line 665 of file RetainSummaryManager.cpp.
References clang::AnyCall::Allocator, clang::AnyCall::Block, clang::AnyCall::Constructor, clang::AnyCall::Deallocator, clang::AnyCall::Destructor, clang::AnyCall::Function, clang::AnyCall::InheritedConstructor, and clang::AnyCall::ObjCMethod.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), and getSummary().
isKnownSmartPointer()
bool RetainSummaryManager::isKnownSmartPointer (QualType QT) static
Returns
Whether the type corresponds to a known smart pointer implementation (that is, everything about it is inlineable).
Definition at line 228 of file RetainSummaryManager.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::QualType::getCanonicalType(), and clang::IdentifierInfo::getName().
Referenced by isSmartPtrField().
isTrustedReferenceCountImplementation()
bool RetainSummaryManager::isTrustedReferenceCountImplementation (const Decl * FD)
Definition at line 716 of file RetainSummaryManager.cpp.
References hasRCAnnotation().
Referenced by canEval(), and clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction().
Friends And Related Function Documentation
RetainSummaryTemplate
friend class RetainSummaryTemplate friend
Definition at line 731 of file RetainSummaryManager.h.
The documentation for this class was generated from the following files:
include/clang/Analysis/RetainSummaryManager.h
lib/Analysis/RetainSummaryManager.cpp