clang: clang::OMPReductionClause Class Reference
clang::OMPReductionClause Class Reference final
This represents clause 'reduction' in the '#pragma omp ...' directives.
#include "clang/AST/OpenMPClause.h"
Public Types
using helper_expr_iterator = MutableArrayRef< Expr * >::iterator
using helper_expr_const_iterator = ArrayRef< const Expr * >::iterator
using helper_expr_range = llvm::iterator_range< helper_expr_iterator >
using helper_expr_const_range = llvm::iterator_range< helper_expr_const_iterator >
Public Types inherited from clang::OMPVarListClause< OMPReductionClause >
using varlist_iterator = MutableArrayRef< Expr * >::iterator
using varlist_const_iterator = ArrayRef< const Expr * >::iterator
using varlist_range = llvm::iterator_range< varlist_iterator >
using varlist_const_range = llvm::iterator_range< varlist_const_iterator >
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
OpenMPReductionClauseModifier getModifier () const
Returns modifier.
SourceLocation getModifierLoc () const
Returns modifier location.
SourceLocation getColonLoc () const
Gets location of ':' symbol in clause.
const DeclarationNameInfo & getNameInfo () const
Gets the name info for specified reduction identifier.
NestedNameSpecifierLoc getQualifierLoc () const
Gets the nested name specifier.
helper_expr_const_range privates () const
helper_expr_range privates ()
helper_expr_const_range lhs_exprs () const
helper_expr_range lhs_exprs ()
helper_expr_const_range rhs_exprs () const
helper_expr_range rhs_exprs ()
helper_expr_const_range reduction_ops () const
helper_expr_range reduction_ops ()
helper_expr_const_range copy_ops () const
helper_expr_range copy_ops ()
helper_expr_const_range copy_array_temps () const
helper_expr_range copy_array_temps ()
helper_expr_const_range copy_array_elems () const
helper_expr_range copy_array_elems ()
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPVarListClause< OMPReductionClause >
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_const_iterator varlist_begin () const
varlist_iterator varlist_end ()
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPostUpdate
const Expr * getPostUpdateExpr () const
Get post-update expression for the clause.
Expr * getPostUpdateExpr ()
Get post-update expression for the clause.
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static OMPReductionClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc, OpenMPReductionClauseModifier Modifier, ArrayRef< Expr * > VL, NestedNameSpecifierLoc QualifierLoc, const DeclarationNameInfo &NameInfo, ArrayRef< Expr * > Privates, ArrayRef< Expr * > LHSExprs, ArrayRef< Expr * > RHSExprs, ArrayRef< Expr * > ReductionOps, ArrayRef< Expr * > CopyOps, ArrayRef< Expr * > CopyArrayTemps, ArrayRef< Expr * > CopyArrayElems, Stmt *PreInit, Expr *PostUpdate)
Creates clause with a list of variables VL.
static OMPReductionClause * CreateEmpty (const ASTContext &C, unsigned N, OpenMPReductionClauseModifier Modifier)
Creates an empty clause with the place for N variables.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPostUpdate
static OMPClauseWithPostUpdate * get (OMPClause *C)
static const OMPClauseWithPostUpdate * get (const OMPClause *C)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Friends
class OMPClauseReader
Additional Inherited Members
Protected Member Functions inherited from clang::OMPVarListClause< OMPReductionClause >
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPostUpdate
OMPClauseWithPostUpdate (const OMPClause *This)
void setPostUpdateExpr (Expr *S)
Set pre-initialization statement for the clause.
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents clause 'reduction' in the '#pragma omp ...' directives.
#pragma omp parallel reduction(+:a,b)
In this example directive '#pragma omp parallel' has clause 'reduction' with operator '+' and the variables 'a' and 'b'.
Definition at line 3039 of file OpenMPClause.h.
Member Typedef Documentation
helper_expr_const_iterator
using clang::OMPReductionClause::helper_expr_const_iterator = ArrayRef<const Expr *>::iterator
Definition at line 3274 of file OpenMPClause.h.
helper_expr_const_range
using clang::OMPReductionClause::helper_expr_const_range = llvm::iterator_range<helper_expr_const_iterator>
Definition at line 3277 of file OpenMPClause.h.
helper_expr_iterator
using clang::OMPReductionClause::helper_expr_iterator = MutableArrayRef<Expr *>::iterator
Definition at line 3273 of file OpenMPClause.h.
helper_expr_range
using clang::OMPReductionClause::helper_expr_range = llvm::iterator_range<helper_expr_iterator>
Definition at line 3275 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPReductionClause::children () inline
Definition at line 3343 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPReductionClause >::varlist_begin(), and clang::OMPVarListClause< OMPReductionClause >::varlist_end().
Referenced by children().
children() [2/2]
const_child_range clang::OMPReductionClause::children () const inline
Definition at line 3348 of file OpenMPClause.h.
References children().
classof()
static bool clang::OMPReductionClause::classof (const OMPClause * T) inline static
Definition at line 3362 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
copy_array_elems() [1/2]
helper_expr_range clang::OMPReductionClause::copy_array_elems () inline
Definition at line 3338 of file OpenMPClause.h.
copy_array_elems() [2/2]
helper_expr_const_range clang::OMPReductionClause::copy_array_elems () const inline
Definition at line 3333 of file OpenMPClause.h.
copy_array_temps() [1/2]
helper_expr_range clang::OMPReductionClause::copy_array_temps () inline
Definition at line 3328 of file OpenMPClause.h.
copy_array_temps() [2/2]
helper_expr_const_range clang::OMPReductionClause::copy_array_temps () const inline
Definition at line 3323 of file OpenMPClause.h.
copy_ops() [1/2]
helper_expr_range clang::OMPReductionClause::copy_ops () inline
Definition at line 3318 of file OpenMPClause.h.
copy_ops() [2/2]
helper_expr_const_range clang::OMPReductionClause::copy_ops () const inline
Definition at line 3313 of file OpenMPClause.h.
Create()
OMPReductionClause * OMPReductionClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc, OpenMPReductionClauseModifier Modifier, ArrayRef< Expr * > VL, NestedNameSpecifierLoc QualifierLoc, const DeclarationNameInfo & NameInfo, ArrayRef< Expr * > Privates, ArrayRef< Expr * > LHSExprs, ArrayRef< Expr * > RHSExprs, ArrayRef< Expr * > ReductionOps, ArrayRef< Expr * > CopyOps, ArrayRef< Expr * > CopyArrayTemps, ArrayRef< Expr * > CopyArrayElems, Stmt * PreInit, Expr * PostUpdate) static
Creates clause with a list of variables VL.
Parameters
StartLoc Starting location of the clause.
LParenLoc Location of '('.
ModifierLoc Modifier location.
ColonLoc Location of ':'.
EndLoc Ending location of the clause.
VL The variables in the clause.
QualifierLoc The nested-name qualifier with location information
NameInfo The full name info for reduction identifier.
Privates List of helper expressions for proper generation of private copies.
LHSExprs List of helper expressions for proper generation of assignment operation required for copyprivate clause. This list represents LHSs of the reduction expressions.
RHSExprs List of helper expressions for proper generation of assignment operation required for copyprivate clause. This list represents RHSs of the reduction expressions. Also, variables in these expressions are used for proper initialization of reduction copies.
ReductionOps List of helper expressions that represents reduction expressions:
LHSExprs binop RHSExprs;
operator binop(LHSExpr, RHSExpr);
<CutomReduction>(LHSExpr, RHSExpr);
Required for proper codegen of final reduction operation performed by the reduction clause.
CopyOps List of copy operations for inscan reductions:
TempExprs = LHSExprs;
CopyArrayTemps Temp arrays for prefix sums.
CopyArrayElems Temp arrays for prefix sums.
PreInit Statement that must be executed before entering the OpenMP region with this clause.
PostUpdate Expression that must be executed after exit from the OpenMP region with this clause.
Definition at line 777 of file OpenMPClause.cpp.
References clang::OMPVarListClause< T >::setVarRefs().
Referenced by clang::Sema::ActOnOpenMPReductionClause().
CreateEmpty()
OMPReductionClause * OMPReductionClause::CreateEmpty (const ASTContext & C, unsigned N, OpenMPReductionClauseModifier Modifier) static
Creates an empty clause with the place for N variables.
Parameters
C AST context.
N The number of variables.
Modifier Reduction modifier.
Definition at line 814 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
getColonLoc()
SourceLocation clang::OMPReductionClause::getColonLoc () const inline
Gets location of ':' symbol in clause.
Definition at line 3265 of file OpenMPClause.h.
getModifier()
OpenMPReductionClauseModifier clang::OMPReductionClause::getModifier () const inline
Returns modifier.
Definition at line 3259 of file OpenMPClause.h.
getModifierLoc()
SourceLocation clang::OMPReductionClause::getModifierLoc () const inline
Returns modifier location.
Definition at line 3262 of file OpenMPClause.h.
getNameInfo()
const DeclarationNameInfo& clang::OMPReductionClause::getNameInfo () const inline
Gets the name info for specified reduction identifier.
Definition at line 3268 of file OpenMPClause.h.
getQualifierLoc()
NestedNameSpecifierLoc clang::OMPReductionClause::getQualifierLoc () const inline
Gets the nested name specifier.
Definition at line 3271 of file OpenMPClause.h.
lhs_exprs() [1/2]
helper_expr_range clang::OMPReductionClause::lhs_exprs () inline
Definition at line 3291 of file OpenMPClause.h.
lhs_exprs() [2/2]
helper_expr_const_range clang::OMPReductionClause::lhs_exprs () const inline
Definition at line 3287 of file OpenMPClause.h.
privates() [1/2]
helper_expr_range clang::OMPReductionClause::privates () inline
Definition at line 3283 of file OpenMPClause.h.
privates() [2/2]
helper_expr_const_range clang::OMPReductionClause::privates () const inline
Definition at line 3279 of file OpenMPClause.h.
reduction_ops() [1/2]
helper_expr_range clang::OMPReductionClause::reduction_ops () inline
Definition at line 3308 of file OpenMPClause.h.
reduction_ops() [2/2]
helper_expr_const_range clang::OMPReductionClause::reduction_ops () const inline
Definition at line 3303 of file OpenMPClause.h.
rhs_exprs() [1/2]
helper_expr_range clang::OMPReductionClause::rhs_exprs () inline
Definition at line 3299 of file OpenMPClause.h.
rhs_exprs() [2/2]
helper_expr_const_range clang::OMPReductionClause::rhs_exprs () const inline
Definition at line 3295 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPReductionClause::used_children () inline
Definition at line 3353 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPReductionClause >::varlist_begin(), and clang::OMPVarListClause< OMPReductionClause >::varlist_end().
Referenced by used_children().
used_children() [2/2]
const_child_range clang::OMPReductionClause::used_children () const inline
Definition at line 3357 of file OpenMPClause.h.
References used_children().
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 3043 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp