clang: clang::PseudoDestructorTypeStorage Class Reference
clang::PseudoDestructorTypeStorage Class Reference
Stores the type being destroyed by a pseudo-destructor expression.
#include "clang/AST/ExprCXX.h"
Public Member Functions
PseudoDestructorTypeStorage ()=default
PseudoDestructorTypeStorage (IdentifierInfo *II, SourceLocation Loc)
PseudoDestructorTypeStorage (TypeSourceInfo *Info)
TypeSourceInfo * getTypeSourceInfo () const
IdentifierInfo * getIdentifier () const
SourceLocation getLocation () const
Detailed Description
Stores the type being destroyed by a pseudo-destructor expression.
Definition at line 2483 of file ExprCXX.h.
Constructor & Destructor Documentation
PseudoDestructorTypeStorage() [1/3]
clang::PseudoDestructorTypeStorage::PseudoDestructorTypeStorage () default
PseudoDestructorTypeStorage() [2/3]
clang::PseudoDestructorTypeStorage::PseudoDestructorTypeStorage (IdentifierInfo * II, SourceLocation Loc) inline
Definition at line 2494 of file ExprCXX.h.
PseudoDestructorTypeStorage() [3/3]
PseudoDestructorTypeStorage::PseudoDestructorTypeStorage (TypeSourceInfo * Info)
Definition at line 315 of file ExprCXX.cpp.
References clang::SourceRange::getBegin(), clang::TypeLoc::getLocalSourceRange(), and clang::TypeSourceInfo::getTypeLoc().
Member Function Documentation
getIdentifier()
IdentifierInfo* clang::PseudoDestructorTypeStorage::getIdentifier () const inline
Definition at line 2503 of file ExprCXX.h.
Referenced by clang::CXXPseudoDestructorExpr::getDestroyedTypeIdentifier(), and clang::TreeTransform< KernelBodyTransform >::RebuildCXXPseudoDestructorExpr().
getLocation()
SourceLocation clang::PseudoDestructorTypeStorage::getLocation () const inline
Definition at line 2507 of file ExprCXX.h.
Referenced by clang::CXXPseudoDestructorExpr::getDestroyedTypeLoc(), and clang::CXXPseudoDestructorExpr::getEndLoc().
getTypeSourceInfo()
TypeSourceInfo* clang::PseudoDestructorTypeStorage::getTypeSourceInfo () const inline
Definition at line 2499 of file ExprCXX.h.
Referenced by clang::Sema::BuildPseudoDestructorExpr(), clang::CXXPseudoDestructorExpr::getDestroyedType(), clang::CXXPseudoDestructorExpr::getDestroyedTypeInfo(), clang::CXXPseudoDestructorExpr::getEndLoc(), and clang::TreeTransform< KernelBodyTransform >::RebuildCXXPseudoDestructorExpr().
The documentation for this class was generated from the following files:
include/clang/AST/ExprCXX.h
lib/AST/ExprCXX.cpp