clang: clang::Parser::ObjCTypeParamListScope Class Reference
clang::Parser::ObjCTypeParamListScope Class Reference
Class to handle popping type parameters when leaving the scope.
Public Member Functions
ObjCTypeParamListScope (Sema &Actions, Scope *S)
~ObjCTypeParamListScope ()
void enter (ObjCTypeParamList *P)
void leave ()
Detailed Description
Class to handle popping type parameters when leaving the scope.
Definition at line 98 of file ParseObjc.cpp.
Constructor & Destructor Documentation
ObjCTypeParamListScope()
clang::Parser::ObjCTypeParamListScope::ObjCTypeParamListScope (Sema & Actions, Scope * S) inline
Definition at line 104 of file ParseObjc.cpp.
~ObjCTypeParamListScope()
clang::Parser::ObjCTypeParamListScope::~ObjCTypeParamListScope () inline
Definition at line 107 of file ParseObjc.cpp.
References clang::Parser::ObjCTypeParamListScope::leave().
Member Function Documentation
enter()
void clang::Parser::ObjCTypeParamListScope::enter (ObjCTypeParamList * P) inline
Definition at line 111 of file ParseObjc.cpp.
References P.
leave()
void clang::Parser::ObjCTypeParamListScope::leave () inline
Definition at line 116 of file ParseObjc.cpp.
References clang::Sema::popObjCTypeParamList().
Referenced by clang::Parser::ObjCTypeParamListScope::~ObjCTypeParamListScope().
The documentation for this class was generated from the following file:
lib/Parse/ParseObjc.cpp