clang: clang::SemaOpenACC Class Reference
clang::SemaOpenACC Class Reference
#include "clang/Sema/SemaOpenACC.h"
Classes
class OpenACCParsedClause
A type to represent all the data for an OpenACC Clause that has been parsed, but not yet created/semantically analyzed.
Public Member Functions
SemaOpenACC (Sema &S)
OpenACCClause * ActOnClause (ArrayRef< const OpenACCClause * > ExistingClauses, OpenACCParsedClause &Clause)
Called after parsing an OpenACC Clause so that it can be checked.
void ActOnConstruct (OpenACCDirectiveKind K, SourceLocation StartLoc)
Called after the construct has been parsed, but clauses haven't been parsed.
bool ActOnStartStmtDirective (OpenACCDirectiveKind K, SourceLocation StartLoc)
Called after the directive, including its clauses, have been parsed and parsing has consumed the 'annot_pragma_openacc_end' token.
bool ActOnStartDeclDirective (OpenACCDirectiveKind K, SourceLocation StartLoc)
Called after the directive, including its clauses, have been parsed and parsing has consumed the 'annot_pragma_openacc_end' token.
StmtResult ActOnAssociatedStmt (OpenACCDirectiveKind K, StmtResult AssocStmt)
Called when we encounter an associated statement for our construct, this should check legality of the statement as it appertains to this Construct.
StmtResult ActOnEndStmtDirective (OpenACCDirectiveKind K, SourceLocation StartLoc, SourceLocation EndLoc, ArrayRef< OpenACCClause * > Clauses, StmtResult AssocStmt)
Called after the directive has been completely parsed, including the declaration group or associated statement.
DeclGroupRef ActOnEndDeclDirective ()
Called after the directive has been completely parsed, including the declaration group or associated statement.
ExprResult ActOnIntExpr (OpenACCDirectiveKind DK, OpenACCClauseKind CK, SourceLocation Loc, Expr *IntExpr)
Called when encountering an 'int-expr' for OpenACC, and manages conversions and diagnostics to 'int'.
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 27 of file SemaOpenACC.h.
Constructor & Destructor Documentation
SemaOpenACC()
SemaOpenACC::SemaOpenACC (Sema & S)
Definition at line 130 of file SemaOpenACC.cpp.
Member Function Documentation
ActOnAssociatedStmt()
StmtResult SemaOpenACC::ActOnAssociatedStmt (OpenACCDirectiveKind K, StmtResult AssocStmt)
Called when we encounter an associated statement for our construct, this should check legality of the statement as it appertains to this Construct.
Definition at line 452 of file SemaOpenACC.cpp.
References clang::Kernels, clang::Parallel, and clang::Serial.
ActOnClause()
OpenACCClause * SemaOpenACC::ActOnClause (ArrayRef< const OpenACCClause * > ExistingClauses, OpenACCParsedClause & Clause)
Called after parsing an OpenACC Clause so that it can be checked.
Definition at line 133 of file SemaOpenACC.cpp.
References clang::OpenACCDefaultClause::Create(), clang::OpenACCNumGangsClause::Create(), clang::OpenACCIfClause::Create(), clang::OpenACCSelfClause::Create(), clang::OpenACCNumWorkersClause::Create(), clang::OpenACCVectorLengthClause::Create(), clang::Default, clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::SemaOpenACC::OpenACCParsedClause::getBeginLoc(), clang::SemaOpenACC::OpenACCParsedClause::getClauseKind(), clang::SemaOpenACC::OpenACCParsedClause::getConditionExpr(), clang::SemaOpenACC::OpenACCParsedClause::getDefaultClauseKind(), clang::SemaOpenACC::OpenACCParsedClause::getDirectiveKind(), clang::SemaOpenACC::OpenACCParsedClause::getEndLoc(), clang::SemaOpenACC::OpenACCParsedClause::getIntExprs(), clang::SemaOpenACC::OpenACCParsedClause::getLParenLoc(), clang::If, clang::Invalid, clang::isOpenACCComputeDirectiveKind(), clang::NumGangs, clang::NumWorkers, clang::Parallel, clang::ParallelLoop, clang::Self, and clang::VectorLength.
ActOnConstruct()
void SemaOpenACC::ActOnConstruct (OpenACCDirectiveKind K, SourceLocation StartLoc)
Called after the construct has been parsed, but clauses haven't been parsed.
This allows us to diagnose not-implemented, as well as set up any state required for parsing the clauses.
Definition at line 315 of file SemaOpenACC.cpp.
References clang::SemaBase::Diag(), clang::Invalid, clang::Kernels, clang::Parallel, and clang::Serial.
ActOnEndDeclDirective()
DeclGroupRef SemaOpenACC::ActOnEndDeclDirective ()
Called after the directive has been completely parsed, including the declaration group or associated statement.
Definition at line 479 of file SemaOpenACC.cpp.
ActOnEndStmtDirective()
StmtResult SemaOpenACC::ActOnEndStmtDirective (OpenACCDirectiveKind K, SourceLocation StartLoc, SourceLocation EndLoc, ArrayRef< OpenACCClause * > Clauses, StmtResult AssocStmt)
Called after the directive has been completely parsed, including the declaration group or associated statement.
Definition at line 431 of file SemaOpenACC.cpp.
References clang::OpenACCComputeConstruct::Create(), clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::Invalid, clang::ActionResult< PtrTy, Compress >::isUsable(), clang::Kernels, clang::Parallel, clang::Serial, clang::StmtEmpty(), and clang::StmtError().
ActOnIntExpr()
ExprResult SemaOpenACC::ActOnIntExpr (OpenACCDirectiveKind DK, OpenACCClauseKind CK, SourceLocation Loc, Expr * IntExpr)
Called when encountering an 'int-expr' for OpenACC, and manages conversions and diagnostics to 'int'.
Definition at line 336 of file SemaOpenACC.cpp.
References clang::Invalid, clang::Type::isIntegerType(), clang::ast_matchers::match(), and clang::T.
ActOnStartDeclDirective()
bool SemaOpenACC::ActOnStartDeclDirective (OpenACCDirectiveKind K, SourceLocation StartLoc)
Called after the directive, including its clauses, have been parsed and parsing has consumed the 'annot_pragma_openacc_end' token.
This DOES happen before any associated declarations or statements have been parsed. This function is only called when we are parsing a 'Decl' context.
Definition at line 474 of file SemaOpenACC.cpp.
ActOnStartStmtDirective()
bool SemaOpenACC::ActOnStartStmtDirective (OpenACCDirectiveKind K, SourceLocation StartLoc)
Called after the directive, including its clauses, have been parsed and parsing has consumed the 'annot_pragma_openacc_end' token.
This DOES happen before any associated declarations or statements have been parsed. This function is only called when we are parsing a 'statement' context.
Definition at line 426 of file SemaOpenACC.cpp.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaOpenACC.h
lib/Sema/SemaOpenACC.cpp