clang: clang::driver::Command Class Reference
clang::driver::Command Class Reference
Command - An executable path/name and argument vector to execute.
#include "clang/Driver/Job.h"
Public Types
using ErrorCodeDiagMapTy = llvm::DenseMap< int, std::string >
using ErrorCodeExitMapTy = llvm::DenseMap< int, bool >
Public Member Functions
Command (const Action &Source, const Tool &Creator, ResponseFileSupport ResponseSupport, const char *Executable, const llvm::opt::ArgStringList &Arguments, ArrayRef< InputInfo > Inputs, ArrayRef< InputInfo > Outputs=std::nullopt, const char *PrependArg=nullptr)
Command (const Command &)=default
virtual ~Command ()=default
virtual void Print (llvm::raw_ostream &OS, const char *Terminator, bool Quote, CrashReportInfo *CrashInfo=nullptr) const
virtual int Execute (ArrayRef< std::optional< StringRef >> Redirects, std::string *ErrMsg, bool *ExecutionFailed) const
void addDiagForErrorCode (int ErrorCode, StringRef CustomDiag)
Store a custom driver diagnostic message upon a particular error code returned by the command.
void addExitForErrorCode (int ErrorCode, bool Exit)
Store if the compilation should exit upon a particular error code returned by the command.
StringRef getDiagForErrorCode (int ErrorCode) const
Get the custom driver diagnostic message for a particular error code if such was stored.
bool getWillExitForErrorCode (int ErrorCode) const
Will the tool exit when a particular error code is encountered.
const Action & getSource () const
getSource - Return the Action which caused the creation of this job.
const Tool & getCreator () const
getCreator - Return the Tool which caused the creation of this job.
const ResponseFileSupport & getResponseFileSupport ()
Returns the kind of response file supported by the current invocation.
void setResponseFile (const char *FileName)
Set to pass arguments via a response file when launching the command.
void setInputFileList (llvm::opt::ArgStringList List)
Set an input file list, necessary if you specified an RF_FileList response file support.
virtual void setEnvironment (llvm::ArrayRef< const char * > NewEnvironment)
Sets the environment to be used by the new process.
void setRedirectFiles (const std::vector< std::optional< std::string >> &Redirects)
void replaceArguments (llvm::opt::ArgStringList List)
void replaceExecutable (const char *Exe)
const char * getExecutable () const
const llvm::opt::ArgStringList & getArguments () const
const std::vector< InputInfo > & getInputInfos () const
const std::vector< std::string > & getOutputFilenames () const
std::optional< llvm::sys::ProcessStatistics > getProcessStatistics () const
Public Attributes
bool PrintInputFilenames = false
Whether to print the input filenames when executing.
bool InProcess = false
Whether the command will be executed in this process or not.
Protected Member Functions
void PrintFileNames () const
Optionally print the filenames to be compiled.
Detailed Description
Command - An executable path/name and argument vector to execute.
Definition at line 107 of file Job.h.
Member Typedef Documentation
ErrorCodeDiagMapTy
using clang::driver::Command::ErrorCodeDiagMapTy = llvm::DenseMap<int, std::string>
Definition at line 109 of file Job.h.
ErrorCodeExitMapTy
using clang::driver::Command::ErrorCodeExitMapTy = llvm::DenseMap<int, bool>
Definition at line 110 of file Job.h.
Constructor & Destructor Documentation
Command() [1/2]
Command::Command (const Action & Source, const Tool & Creator, ResponseFileSupport ResponseSupport, const char * Executable, const llvm::opt::ArgStringList & Arguments, ArrayRef< InputInfo > Inputs, ArrayRef< InputInfo > Outputs = std::nullopt, const char * PrependArg = nullptr)
Definition at line 39 of file Job.cpp.
Command() [2/2]
clang::driver::Command::Command (const Command &) default
~Command()
virtual clang::driver::Command::~Command () virtual default
Member Function Documentation
addDiagForErrorCode()
void Command::addDiagForErrorCode (int ErrorCode, StringRef CustomDiag)
Store a custom driver diagnostic message upon a particular error code returned by the command.
Definition at line 167 of file Job.cpp.
addExitForErrorCode()
void Command::addExitForErrorCode (int ErrorCode, bool Exit)
Store if the compilation should exit upon a particular error code returned by the command.
Definition at line 171 of file Job.cpp.
Execute()
int Command::Execute (ArrayRef< std::optional< StringRef >> Redirects, std::string * ErrMsg, bool * ExecutionFailed) const virtual
Reimplemented in clang::driver::CC1Command.
Definition at line 348 of file Job.cpp.
References Env.
Referenced by clang::driver::CC1Command::Execute(), and clang::driver::Driver::generateCompilationDiagnostics().
getArguments()
const llvm::opt::ArgStringList& clang::driver::Command::getArguments () const inline
Definition at line 265 of file Job.h.
Referenced by clang::driver::CC1Command::Execute(), and clang::driver::Driver::generateCompilationDiagnostics().
getCreator()
const Tool& clang::driver::Command::getCreator () const inline
getCreator - Return the Tool which caused the creation of this job.
Definition at line 232 of file Job.h.
Referenced by clang::driver::CC1Command::Execute(), clang::driver::Driver::ExecuteCompilation(), and clang::driver::Driver::generateCompilationDiagnostics().
getDiagForErrorCode()
StringRef Command::getDiagForErrorCode (int ErrorCode) const
Get the custom driver diagnostic message for a particular error code if such was stored.
Returns an empty string if no diagnostic message was found for the given error code.
Definition at line 175 of file Job.cpp.
Referenced by clang::driver::Driver::ExecuteCompilation().
getExecutable()
const char* clang::driver::Command::getExecutable () const inline
Definition at line 263 of file Job.h.
Referenced by clang::driver::CC1Command::Execute().
getInputInfos()
const std::vector<InputInfo>& clang::driver::Command::getInputInfos () const inline
Definition at line 267 of file Job.h.
getOutputFilenames()
const std::vector<std::string>& clang::driver::Command::getOutputFilenames () const inline
Definition at line 269 of file Job.h.
getProcessStatistics()
std::optional<llvm::sys::ProcessStatistics> clang::driver::Command::getProcessStatistics () const inline
Definition at line 273 of file Job.h.
getResponseFileSupport()
const ResponseFileSupport& clang::driver::Command::getResponseFileSupport () inline
Returns the kind of response file supported by the current invocation.
Definition at line 235 of file Job.h.
getSource()
const Action& clang::driver::Command::getSource () const inline
getSource - Return the Action which caused the creation of this job.
Definition at line 229 of file Job.h.
Referenced by clang::driver::Driver::ExecuteCompilation().
getWillExitForErrorCode()
bool Command::getWillExitForErrorCode (int ErrorCode) const
Will the tool exit when a particular error code is encountered.
Returns true if not set (always exit)
Definition at line 182 of file Job.cpp.
Referenced by clang::driver::Compilation::ExecuteJobs().
Print()
void Command::Print (llvm::raw_ostream & OS, const char * Terminator, bool Quote, CrashReportInfo * CrashInfo = nullptr) const virtual
Reimplemented in clang::driver::CC1Command.
Definition at line 229 of file Job.cpp.
References clang::driver::CrashReportInfo::Filename, clang::driver::InputInfo::getFilename(), rewriteIncludes(), clang::driver::ResponseFileSupport::RF_FileList, skipArgs(), and clang::driver::CrashReportInfo::VFSPath.
Referenced by clang::driver::CC1Command::Print().
PrintFileNames()
void Command::PrintFileNames () const protected
Optionally print the filenames to be compiled.
Definition at line 340 of file Job.cpp.
Referenced by clang::driver::CC1Command::Execute().
replaceArguments()
void clang::driver::Command::replaceArguments (llvm::opt::ArgStringList List) inline
Definition at line 257 of file Job.h.
Referenced by clang::driver::Driver::generateCompilationDiagnostics().
replaceExecutable()
void clang::driver::Command::replaceExecutable (const char * Exe) inline
Definition at line 261 of file Job.h.
setEnvironment()
void Command::setEnvironment (llvm::ArrayRef< const char * > NewEnvironment) virtual
Sets the environment to be used by the new process.
Parameters
NewEnvironment An array of environment variables.
Remarks
If the environment remains unset, then the environment from the parent process will be used.
Reimplemented in clang::driver::CC1Command.
Definition at line 329 of file Job.cpp.
setInputFileList()
void clang::driver::Command::setInputFileList (llvm::opt::ArgStringList List) inline
Set an input file list, necessary if you specified an RF_FileList response file support.
Definition at line 244 of file Job.h.
setRedirectFiles()
void Command::setRedirectFiles (const std::vector< std::optional< std::string >> & Redirects)
Definition at line 335 of file Job.cpp.
setResponseFile()
void Command::setResponseFile (const char * FileName)
Set to pass arguments via a response file when launching the command.
Definition at line 323 of file Job.cpp.
References clang::FileName.
Member Data Documentation
InProcess
bool clang::driver::Command::InProcess = false
Whether the command will be executed in this process or not.
Definition at line 193 of file Job.h.
Referenced by clang::driver::CC1Command::CC1Command(), clang::driver::CC1Command::Execute(), and clang::driver::CC1Command::Print().
PrintInputFilenames
bool clang::driver::Command::PrintInputFilenames = false
Whether to print the input filenames when executing.
Definition at line 190 of file Job.h.
The documentation for this class was generated from the following files:
include/clang/Driver/Job.h
lib/Driver/Job.cpp