clang: clang::RewriteRope Class Reference
clang::RewriteRope Class Reference
RewriteRope - A powerful string class.
#include "clang/Rewrite/Core/RewriteRope.h"
Public Types
using iterator = RopePieceBTree::iterator
using const_iterator = RopePieceBTree::iterator
Public Member Functions
RewriteRope ()=default
RewriteRope (const RewriteRope &RHS)
iterator begin () const
iterator end () const
unsigned size () const
void clear ()
void assign (const char *Start, const char *End)
void insert (unsigned Offset, const char *Start, const char *End)
void erase (unsigned Offset, unsigned NumBytes)
Detailed Description
RewriteRope - A powerful string class.
This class supports extremely efficient insertions and deletions into the middle of it, even for ridiculously long strings.
Definition at line 171 of file RewriteRope.h.
Member Typedef Documentation
const_iterator
using clang::RewriteRope::const_iterator = RopePieceBTree::iterator
Definition at line 185 of file RewriteRope.h.
iterator
using clang::RewriteRope::iterator = RopePieceBTree::iterator
Definition at line 184 of file RewriteRope.h.
Constructor & Destructor Documentation
RewriteRope() [1/2]
clang::RewriteRope::RewriteRope () default
RewriteRope() [2/2]
clang::RewriteRope::RewriteRope (const RewriteRope & RHS) inline
Definition at line 182 of file RewriteRope.h.
Member Function Documentation
assign()
void clang::RewriteRope::assign (const char * Start, const char * End) inline
Definition at line 195 of file RewriteRope.h.
References clear(), End, and clang::RopePieceBTree::insert().
Referenced by clang::RewriteBuffer::Initialize().
begin()
iterator clang::RewriteRope::begin () const inline
Definition at line 187 of file RewriteRope.h.
References clang::RopePieceBTree::begin().
Referenced by clang::RewriteBuffer::begin().
clear()
void clang::RewriteRope::clear () inline
Definition at line 191 of file RewriteRope.h.
References clang::RopePieceBTree::clear().
Referenced by assign().
end()
iterator clang::RewriteRope::end () const inline
Definition at line 188 of file RewriteRope.h.
References clang::RopePieceBTree::end().
Referenced by clang::RewriteBuffer::end().
erase()
void clang::RewriteRope::erase (unsigned Offset, unsigned NumBytes) inline
Definition at line 207 of file RewriteRope.h.
References clang::RopePieceBTree::erase(), Offset, and size().
Referenced by clang::RewriteBuffer::RemoveText(), and clang::RewriteBuffer::ReplaceText().
insert()
void clang::RewriteRope::insert (unsigned Offset, const char * Start, const char * End) inline
Definition at line 201 of file RewriteRope.h.
References End, clang::RopePieceBTree::insert(), Offset, and size().
Referenced by clang::RewriteBuffer::InsertText(), and clang::RewriteBuffer::ReplaceText().
size()
unsigned clang::RewriteRope::size () const inline
Definition at line 189 of file RewriteRope.h.
References clang::RopePieceBTree::size().
Referenced by erase(), insert(), clang::RewriteBuffer::RemoveText(), and clang::RewriteBuffer::size().
The documentation for this class was generated from the following files:
include/clang/Rewrite/Core/RewriteRope.h
lib/Rewrite/RewriteRope.cpp