clang: clang::interp::Pointer Class Reference
clang::interp::Pointer Class Reference
A pointer to a memory block, live or dead.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Pointer.h"
Public Member Functions
Pointer ()
Pointer (Block *B)
Pointer (Block *B, uint64_t BaseAndOffset)
Pointer (const Pointer &P)
Pointer (Pointer &&P)
Pointer (uint64_t Address, const Descriptor *Desc, uint64_t Offset=0)
~Pointer ()
void operator= (const Pointer &P)
void operator= (Pointer &&P)
bool operator== (const Pointer &P) const
Equality operators are just for tests.
bool operator!= (const Pointer &P) const
APValue toAPValue () const
Converts the pointer to an APValue.
std::string toDiagnosticString (const ASTContext &Ctx) const
Converts the pointer to a string usable in diagnostics.
uint64_t getIntegerRepresentation () const
std::optional< APValue > toRValue (const Context &Ctx, QualType ResultType) const
Converts the pointer to an APValue that is an rvalue.
Pointer atIndex (uint64_t Idx) const
Offsets a pointer inside an array.
Pointer atField (unsigned Off) const
Creates a pointer to a field.
Pointer atFieldSub (unsigned Off) const
Subtract the given offset from the current Base and Offset of the pointer.
Pointer narrow () const
Restricts the scope of an array element pointer.
Pointer expand () const
Expands a pointer to the containing array, undoing narrowing.
bool isZero () const
Checks if the pointer is null.
bool isLive () const
Checks if the pointer is live.
bool isField () const
Checks if the item is a field in an object.
const Descriptor * getDeclDesc () const
Accessor for information about the declaration site.
SourceLocation getDeclLoc () const
DeclTy getSource () const
Returns the expression or declaration the pointer has been created for.
Pointer getBase () const
Returns a pointer to the object of which this pointer is a field.
Pointer getArray () const
Returns the parent array.
const Descriptor * getFieldDesc () const
Accessors for information about the innermost field.
QualType getType () const
Returns the type of the innermost field.
Pointer getDeclPtr () const
size_t elemSize () const
Returns the element size of the innermost field.
size_t getSize () const
Returns the total size of the innermost field.
unsigned getOffset () const
Returns the offset into an array.
bool isArrayRoot () const
Whether this array refers to an array, but not to the first element.
bool inArray () const
Checks if the innermost field is an array.
bool inPrimitiveArray () const
Checks if the structure is a primitive array.
bool isUnknownSizeArray () const
Checks if the structure is an array of unknown size.
bool isArrayElement () const
Checks if the pointer points to an array.
bool isRoot () const
Pointer points directly to a block.
bool canBeInitialized () const
If this pointer has an InlineDescriptor we can use to initialize.
const BlockPointer & asBlockPointer () const
const IntPointer & asIntPointer () const
bool isBlockPointer () const
bool isIntegralPointer () const
const Record * getRecord () const
Returns the record descriptor of a class.
const Record * getElemRecord () const
Returns the element record type, if this is a non-primive array.
const FieldDecl * getField () const
Returns the field information.
bool isUnion () const
Checks if the object is a union.
bool isExtern () const
Checks if the storage is extern.
bool isStatic () const
Checks if the storage is static.
bool isTemporary () const
Checks if the storage is temporary.
bool isStaticTemporary () const
Checks if the storage is a static temporary.
bool isMutable () const
Checks if the field is mutable.
bool isWeak () const
bool isInitialized () const
Checks if an object was initialized.
bool isActive () const
Checks if the object is active.
bool isBaseClass () const
Checks if a structure is a base class.
bool isDummy () const
Checks if the pointer points to a dummy value.
bool isConst () const
Checks if an object or a subfield is mutable.
std::optional< unsigned > getDeclID () const
Returns the declaration ID.
unsigned getByteOffset () const
Returns the byte offset from the start.
unsigned getNumElems () const
Returns the number of elements.
const Block * block () const
int64_t getIndex () const
Returns the index into an array.
bool isOnePastEnd () const
Checks if the index is one past end.
bool isPastEnd () const
Checks if the pointer points past the end of the object.
bool isElementPastEnd () const
Checks if the pointer is an out-of-bounds element pointer.
bool isZeroSizeArray () const
Checks if the pointer is pointing to a zero-size array.
template<typename T >
T & deref () const
Dereferences the pointer, if it's live.
template<typename T >
T & elem (unsigned I) const
Dereferences a primitive element.
bool isDereferencable () const
Whether this block can be read from at all.
void initialize () const
Initializes a field.
void activate () const
Activats a field.
void deactivate () const
Deactivates an entire strurcutre.
ComparisonCategoryResult compare (const Pointer &Other) const
Compare two pointers.
void print (llvm::raw_ostream &OS) const
Prints the pointer.
Static Public Member Functions
static bool hasSameBase (const Pointer &A, const Pointer &B)
Checks if two pointers are comparable.
static bool hasSameArray (const Pointer &A, const Pointer &B)
Checks if two pointers can be subtracted.
Friends
class Block
class DeadBlock
class MemberPointer
class InterpState
struct InitMap
class DynamicAllocator
Detailed Description
A pointer to a memory block, live or dead.
This object can be allocated into interpreter stack frames. If pointing to a live block, it is a link in the chain of pointers pointing to the block.
In the simplest form, a Pointer has a Block* (the pointee) and both Base and Offset are 0, which means it will point to raw data.
The Base field is used to access metadata about the data. For primitive arrays, the Base is followed by an InitMap. In a variety of cases, the Base is preceded by an InlineDescriptor, which is used to track the initialization state, among other things.
The Offset field is used to access the actual data. In other words, the data the pointer decribes can be found at Pointee->rawData() + Pointer.Offset.
Pointee Offset │ │ │ │ ▼ ▼ ┌───────┬────────────┬─────────┬────────────────────────────┐ │ Block │ InlineDesc │ InitMap │ Actual Data │ └───────┴────────────┴─────────┴────────────────────────────┘ ▲ │ │ Base
Definition at line 79 of file Pointer.h.
Constructor & Destructor Documentation
Pointer() [1/6]
clang::interp::Pointer::Pointer () inline
Definition at line 85 of file Pointer.h.
References clang::interp::Int.
Referenced by atField(), atFieldSub(), atIndex(), expand(), getArray(), getBase(), getDeclPtr(), and narrow().
Pointer() [2/6]
Pointer::Pointer (Block * B)
Definition at line 23 of file Pointer.cpp.
Pointer() [3/6]
Pointer::Pointer (Block * B, uint64_t BaseAndOffset)
Definition at line 27 of file Pointer.cpp.
Pointer() [4/6]
Pointer::Pointer (const Pointer & P)
Definition at line 30 of file Pointer.cpp.
References isBlockPointer().
Pointer() [5/6]
Pointer::Pointer (Pointer && P)
Definition at line 48 of file Pointer.cpp.
References clang::interp::Block, and P.
Pointer() [6/6]
clang::interp::Pointer::Pointer (uint64_t Address, const Descriptor * Desc, uint64_t Offset = 0) inline
Definition at line 94 of file Pointer.h.
~Pointer()
Pointer::~Pointer ()
Definition at line 56 of file Pointer.cpp.
References isIntegralPointer().
Member Function Documentation
activate()
void Pointer::activate () const
Activats a field.
Definition at line 310 of file Pointer.cpp.
References clang::interp::InlineDescriptor::IsActive, and isRoot().
asBlockPointer()
const BlockPointer& clang::interp::Pointer::asBlockPointer () const inline
Definition at line 416 of file Pointer.h.
References isBlockPointer().
Referenced by atField(), atFieldSub(), atIndex(), block(), canBeInitialized(), deref(), elem(), elemSize(), expand(), getArray(), getBase(), getDeclDesc(), getDeclID(), getDeclPtr(), getIndex(), getIntegerRepresentation(), getOffset(), getType(), hasSameBase(), initialize(), isArrayElement(), isArrayRoot(), isDummy(), isExtern(), isInitialized(), isLive(), isOnePastEnd(), isRoot(), isStatic(), isTemporary(), isZero(), narrow(), and operator==().
asIntPointer()
const IntPointer& clang::interp::Pointer::asIntPointer () const inline
Definition at line 420 of file Pointer.h.
References isIntegralPointer().
Referenced by atField(), atIndex(), elemSize(), getByteOffset(), getDeclDesc(), getFieldDesc(), getIntegerRepresentation(), getSource(), isZero(), operator==(), toAPValue(), and toDiagnosticString().
atField()
Pointer clang::interp::Pointer::atField (unsigned Off) const inline
Creates a pointer to a field.
Definition at line 154 of file Pointer.h.
References asBlockPointer(), asIntPointer(), isIntegralPointer(), and Pointer().
Referenced by clang::interp::collectBlocks(), clang::interp::MemberPointer::toPointer(), and toRValue().
atFieldSub()
Pointer clang::interp::Pointer::atFieldSub (unsigned Off) const inline
Subtract the given offset from the current Base and Offset of the pointer.
Definition at line 163 of file Pointer.h.
References asBlockPointer(), and Pointer().
atIndex()
Pointer clang::interp::Pointer::atIndex (uint64_t Idx) const inline
Offsets a pointer inside an array.
Definition at line 137 of file Pointer.h.
References asBlockPointer(), asIntPointer(), elemSize(), getDeclDesc(), getFieldDesc(), getSize(), isIntegralPointer(), and Pointer().
Referenced by clang::interp::collectBlocks(), and toRValue().
block()
const Block* clang::interp::Pointer::block () const inline
Definition at line 533 of file Pointer.h.
References asBlockPointer(), and clang::interp::BlockPointer::Pointee.
Referenced by clang::interp::collectBlocks(), isInitialized(), and clang::interp::MemberPointer::toPointer().
canBeInitialized()
bool clang::interp::Pointer::canBeInitialized () const inline
If this pointer has an InlineDescriptor we can use to initialize.
Definition at line 409 of file Pointer.h.
References asBlockPointer(), clang::interp::BlockPointer::Base, isBlockPointer(), and clang::interp::BlockPointer::Pointee.
compare()
ComparisonCategoryResult clang::interp::Pointer::compare (const Pointer & Other) const inline
Compare two pointers.
Definition at line 626 of file Pointer.h.
References clang::Equal, clang::Greater, hasSameBase(), clang::Less, clang::Other, and clang::Unordered.
deactivate()
void Pointer::deactivate () const
Deactivates an entire strurcutre.
Definition at line 321 of file Pointer.cpp.
deref()
template<typename T > T& clang::interp::Pointer::deref () const inline
Dereferences the pointer, if it's live.
Definition at line 583 of file Pointer.h.
References asBlockPointer(), clang::interp::BlockPointer::Base, isArrayRoot(), isBlockPointer(), isDereferencable(), isLive(), clang::interp::BlockPointer::Pointee, clang::interp::Block::rawData(), and clang::T.
Referenced by clang::interp::assignInteger(), clang::interp::collectBlocks(), clang::interp::InterpFrame::getParam(), clang::interp::InterpFrame::setParam(), and toRValue().
elem()
template<typename T > T& clang::interp::Pointer::elem (unsigned I) const inline
Dereferences a primitive element.
Definition at line 599 of file Pointer.h.
References asBlockPointer(), clang::interp::Block::data(), getNumElems(), isBlockPointer(), clang::interp::BlockPointer::Pointee, and clang::T.
elemSize()
size_t clang::interp::Pointer::elemSize () const inline
Returns the element size of the innermost field.
Definition at line 337 of file Pointer.h.
References asBlockPointer(), asIntPointer(), clang::interp::IntPointer::Desc, getDeclDesc(), clang::interp::Descriptor::getElemSize(), getFieldDesc(), clang::interp::Descriptor::getSize(), and isIntegralPointer().
Referenced by atIndex(), getIndex(), getIntegerRepresentation(), and getNumElems().
expand()
Pointer clang::interp::Pointer::expand () const inline
Expands a pointer to the containing array, undoing narrowing.
Definition at line 212 of file Pointer.h.
References asBlockPointer(), clang::interp::BlockPointer::Base, clang::interp::InlineDescriptor::Desc, getDeclDesc(), clang::interp::Block::getDescriptor(), clang::interp::Descriptor::getMetadataSize(), getSize(), inPrimitiveArray(), clang::interp::Descriptor::IsArray, isBlockPointer(), isElementPastEnd(), isRoot(), clang::interp::InlineDescriptor::Offset, clang::interp::BlockPointer::Pointee, and Pointer().
getArray()
Pointer clang::interp::Pointer::getArray () const inline
Returns the parent array.
Definition at line 297 of file Pointer.h.
References asBlockPointer(), and Pointer().
Referenced by toAPValue().
getBase()
Pointer clang::interp::Pointer::getBase () const inline
Returns a pointer to the object of which this pointer is a field.
Definition at line 288 of file Pointer.h.
References asBlockPointer(), clang::interp::BlockPointer::Base, clang::interp::InlineDescriptor::Offset, and Pointer().
Referenced by toAPValue().
getByteOffset()
unsigned clang::interp::Pointer::getByteOffset () const inline
Returns the byte offset from the start.
Definition at line 518 of file Pointer.h.
References asIntPointer(), isIntegralPointer(), isOnePastEnd(), and clang::interp::IntPointer::Value.
getDeclDesc()
const Descriptor* clang::interp::Pointer::getDeclDesc () const inline
Accessor for information about the declaration site.
Definition at line 268 of file Pointer.h.
References asBlockPointer(), asIntPointer(), clang::interp::IntPointer::Desc, isBlockPointer(), isIntegralPointer(), and clang::interp::BlockPointer::Pointee.
Referenced by atIndex(), elemSize(), expand(), getDeclLoc(), getFieldDesc(), getSource(), isConst(), isDummy(), isWeak(), and toAPValue().
getDeclID()
std::optional<unsigned> clang::interp::Pointer::getDeclID () const inline
Returns the declaration ID.
Definition at line 509 of file Pointer.h.
References asBlockPointer(), clang::interp::Block::getDeclID(), isBlockPointer(), and clang::interp::BlockPointer::Pointee.
getDeclLoc()
SourceLocation clang::interp::Pointer::getDeclLoc () const inline
Definition at line 276 of file Pointer.h.
References getDeclDesc(), and clang::interp::Descriptor::getLocation().
getDeclPtr()
Pointer clang::interp::Pointer::getDeclPtr () const inline
Definition at line 332 of file Pointer.h.
References asBlockPointer(), and Pointer().
getElemRecord()
const Record* clang::interp::Pointer::getElemRecord () const inline
Returns the element record type, if this is a non-primive array.
Definition at line 430 of file Pointer.h.
References clang::interp::Descriptor::ElemDesc, clang::interp::Descriptor::ElemRecord, and getFieldDesc().
getField()
const FieldDecl* clang::interp::Pointer::getField () const inline
Returns the field information.
Definition at line 435 of file Pointer.h.
References clang::interp::Descriptor::asFieldDecl(), and getFieldDesc().
getFieldDesc()
const Descriptor* clang::interp::Pointer::getFieldDesc () const inline
Accessors for information about the innermost field.
Definition at line 308 of file Pointer.h.
References asIntPointer(), clang::interp::InlineDescriptor::Desc, clang::interp::IntPointer::Desc, getDeclDesc(), isIntegralPointer(), and isRoot().
Referenced by atIndex(), clang::interp::collectBlocks(), elemSize(), getElemRecord(), getField(), getOffset(), getRecord(), getSize(), getType(), hasSameArray(), inArray(), initialize(), inPrimitiveArray(), isField(), isInitialized(), isUnknownSizeArray(), isZeroSizeArray(), narrow(), toAPValue(), and toRValue().
getIndex()
int64_t clang::interp::Pointer::getIndex () const inline
Returns the index into an array.
Definition at line 536 of file Pointer.h.
References asBlockPointer(), elemSize(), getOffset(), isBlockPointer(), and isZero().
Referenced by initialize(), isInitialized(), and toAPValue().
getIntegerRepresentation()
uint64_t clang::interp::Pointer::getIntegerRepresentation () const inline
Definition at line 126 of file Pointer.h.
References asBlockPointer(), asIntPointer(), elemSize(), isIntegralPointer(), clang::interp::BlockPointer::Pointee, and clang::interp::IntPointer::Value.
getNumElems()
unsigned clang::interp::Pointer::getNumElems () const inline
Returns the number of elements.
Definition at line 527 of file Pointer.h.
References elemSize(), getSize(), and isIntegralPointer().
Referenced by elem(), and toAPValue().
getOffset()
unsigned clang::interp::Pointer::getOffset () const inline
Returns the offset into an array.
Definition at line 355 of file Pointer.h.
References asBlockPointer(), clang::interp::BlockPointer::Base, and getFieldDesc().
Referenced by getIndex(), and isOnePastEnd().
getRecord()
const Record* clang::interp::Pointer::getRecord () const inline
Returns the record descriptor of a class.
Definition at line 428 of file Pointer.h.
References clang::interp::Descriptor::ElemRecord, and getFieldDesc().
Referenced by clang::interp::MemberPointer::toPointer().
getSize()
size_t clang::interp::Pointer::getSize () const inline
Returns the total size of the innermost field.
Definition at line 349 of file Pointer.h.
References getFieldDesc(), clang::interp::Descriptor::getSize(), and isBlockPointer().
Referenced by atIndex(), expand(), getNumElems(), and isOnePastEnd().
getSource()
DeclTy clang::interp::Pointer::getSource () const inline
Returns the expression or declaration the pointer has been created for.
Definition at line 279 of file Pointer.h.
References asIntPointer(), clang::interp::IntPointer::Desc, getDeclDesc(), clang::interp::Descriptor::getSource(), isBlockPointer(), and isIntegralPointer().
Referenced by hasSameBase().
getType()
QualType clang::interp::Pointer::getType () const inline
Returns the type of the innermost field.
Definition at line 318 of file Pointer.h.
References asBlockPointer(), getFieldDesc(), clang::interp::Descriptor::getType(), and inPrimitiveArray().
Referenced by toDiagnosticString(), and toRValue().
hasSameArray()
bool Pointer::hasSameArray (const Pointer & A, const Pointer & B) static
Checks if two pointers can be subtracted.
Definition at line 339 of file Pointer.cpp.
References clang::interp::BlockPointer::Base, BS, getFieldDesc(), hasSameBase(), and clang::interp::Descriptor::IsArray.
hasSameBase()
bool Pointer::hasSameBase (const Pointer & A, const Pointer & B) static
Checks if two pointers are comparable.
Definition at line 325 of file Pointer.cpp.
References asBlockPointer(), getSource(), isIntegralPointer(), isZero(), and clang::interp::BlockPointer::Pointee.
Referenced by compare(), and hasSameArray().
inArray()
bool clang::interp::Pointer::inArray () const inline
Checks if the innermost field is an array.
Definition at line 377 of file Pointer.h.
References getFieldDesc(), clang::interp::Descriptor::IsArray, and isBlockPointer().
Referenced by isArrayElement(), and isArrayRoot().
initialize()
void Pointer::initialize () const
Initializes a field.
Definition at line 262 of file Pointer.cpp.
References asBlockPointer(), getFieldDesc(), getIndex(), clang::interp::Descriptor::getNumElems(), clang::interp::Initialized, clang::interp::GlobalInlineDescriptor::InitState, clang::interp::InlineDescriptor::IsInitialized, isIntegralPointer(), clang::interp::Descriptor::isPrimitiveArray(), isRoot(), isStatic(), clang::interp::BlockPointer::Pointee, and clang::interp::Block::rawData().
inPrimitiveArray()
bool clang::interp::Pointer::inPrimitiveArray () const inline
Checks if the structure is a primitive array.
Definition at line 383 of file Pointer.h.
References getFieldDesc(), isBlockPointer(), and clang::interp::Descriptor::isPrimitiveArray().
Referenced by expand(), getType(), and narrow().
isActive()
bool clang::interp::Pointer::isActive () const inline
Checks if the object is active.
Definition at line 483 of file Pointer.h.
References clang::interp::InlineDescriptor::IsActive, isBlockPointer(), and isRoot().
Referenced by toRValue().
isArrayElement()
bool clang::interp::Pointer::isArrayElement () const inline
Checks if the pointer points to an array.
Definition at line 395 of file Pointer.h.
References asBlockPointer(), clang::interp::BlockPointer::Base, inArray(), and isBlockPointer().
Referenced by toAPValue().
isArrayRoot()
bool clang::interp::Pointer::isArrayRoot () const inline
Whether this array refers to an array, but not to the first element.
Definition at line 372 of file Pointer.h.
References asBlockPointer(), clang::interp::BlockPointer::Base, and inArray().
Referenced by deref(), and toAPValue().
isBaseClass()
bool clang::interp::Pointer::isBaseClass () const inline
Checks if a structure is a base class.
Definition at line 489 of file Pointer.h.
References clang::interp::InlineDescriptor::IsBase, and isField().
isBlockPointer()
bool clang::interp::Pointer::isBlockPointer () const inline
Definition at line 424 of file Pointer.h.
References clang::interp::Block.
Referenced by asBlockPointer(), canBeInitialized(), deref(), elem(), expand(), getDeclDesc(), getDeclID(), getIndex(), getSize(), getSource(), inArray(), inPrimitiveArray(), isActive(), isArrayElement(), isDereferencable(), isDummy(), isExtern(), isMutable(), isTemporary(), isUnknownSizeArray(), isWeak(), isZero(), narrow(), operator=(), operator==(), Pointer(), and print().
isConst()
bool clang::interp::Pointer::isConst () const inline
Checks if an object or a subfield is mutable.
Definition at line 502 of file Pointer.h.
References getDeclDesc(), clang::interp::InlineDescriptor::IsConst, clang::interp::Descriptor::IsConst, isIntegralPointer(), and isRoot().
isDereferencable()
bool clang::interp::Pointer::isDereferencable () const inline
Whether this block can be read from at all.
This is only true for block pointers that point to a valid location inside that block.
Definition at line 609 of file Pointer.h.
References isBlockPointer(), and isPastEnd().
Referenced by deref().
isDummy()
bool clang::interp::Pointer::isDummy () const inline
Checks if the pointer points to a dummy value.
Definition at line 491 of file Pointer.h.
References asBlockPointer(), getDeclDesc(), isBlockPointer(), and clang::interp::Descriptor::isDummy().
Referenced by toAPValue(), and toRValue().
isElementPastEnd()
bool clang::interp::Pointer::isElementPastEnd () const inline
Checks if the pointer is an out-of-bounds element pointer.
Definition at line 577 of file Pointer.h.
Referenced by expand(), isOnePastEnd(), and print().
isExtern()
bool clang::interp::Pointer::isExtern () const inline
Checks if the storage is extern.
Definition at line 441 of file Pointer.h.
References asBlockPointer(), isBlockPointer(), clang::interp::Block::isExtern(), and clang::interp::BlockPointer::Pointee.
isField()
bool clang::interp::Pointer::isField () const inline
Checks if the item is a field in an object.
Definition at line 260 of file Pointer.h.
References clang::interp::Descriptor::asDecl(), getFieldDesc(), isIntegralPointer(), and isRoot().
Referenced by isBaseClass(), and toAPValue().
isInitialized()
bool Pointer::isInitialized () const
Checks if an object was initialized.
Definition at line 226 of file Pointer.cpp.
References asBlockPointer(), block(), getFieldDesc(), getIndex(), clang::interp::Initialized, clang::interp::GlobalInlineDescriptor::InitState, clang::interp::InlineDescriptor::IsInitialized, isIntegralPointer(), clang::interp::Descriptor::isPrimitiveArray(), isRoot(), isStatic(), and clang::interp::Block::rawData().
Referenced by clang::interp::Program::dump().
isIntegralPointer()
bool clang::interp::Pointer::isIntegralPointer () const inline
Definition at line 425 of file Pointer.h.
References clang::interp::Int.
Referenced by asIntPointer(), atField(), atIndex(), elemSize(), getByteOffset(), getDeclDesc(), getFieldDesc(), getIntegerRepresentation(), getNumElems(), getSource(), hasSameBase(), initialize(), isConst(), isField(), isInitialized(), isLive(), isOnePastEnd(), isPastEnd(), isRoot(), isStatic(), isWeak(), isZero(), operator==(), toAPValue(), toDiagnosticString(), toRValue(), and ~Pointer().
isLive()
bool clang::interp::Pointer::isLive () const inline
Checks if the pointer is live.
Definition at line 254 of file Pointer.h.
References asBlockPointer(), isIntegralPointer(), and clang::interp::BlockPointer::Pointee.
Referenced by deref(), and toRValue().
isMutable()
bool clang::interp::Pointer::isMutable () const inline
Checks if the field is mutable.
Definition at line 465 of file Pointer.h.
References isBlockPointer(), clang::interp::InlineDescriptor::IsFieldMutable, and isRoot().
isOnePastEnd()
bool clang::interp::Pointer::isOnePastEnd () const inline
Checks if the index is one past end.
Definition at line 554 of file Pointer.h.
References asBlockPointer(), getOffset(), getSize(), isElementPastEnd(), isIntegralPointer(), isPastEnd(), isUnknownSizeArray(), and isZeroSizeArray().
Referenced by getByteOffset(), narrow(), and toAPValue().
isPastEnd()
bool clang::interp::Pointer::isPastEnd () const inline
Checks if the pointer points past the end of the object.
Definition at line 569 of file Pointer.h.
References isIntegralPointer(), and isZero().
Referenced by isDereferencable(), isOnePastEnd(), and toRValue().
isRoot()
bool clang::interp::Pointer::isRoot () const inline
Pointer points directly to a block.
Definition at line 401 of file Pointer.h.
References asBlockPointer(), isIntegralPointer(), and isZero().
Referenced by activate(), expand(), getFieldDesc(), initialize(), isActive(), isConst(), isField(), isInitialized(), isMutable(), and print().
isStatic()
bool clang::interp::Pointer::isStatic () const inline
Checks if the storage is static.
Definition at line 447 of file Pointer.h.
References asBlockPointer(), isIntegralPointer(), clang::interp::Block::isStatic(), and clang::interp::BlockPointer::Pointee.
Referenced by initialize(), isInitialized(), and isStaticTemporary().
isStaticTemporary()
bool clang::interp::Pointer::isStaticTemporary () const inline
Checks if the storage is a static temporary.
Definition at line 462 of file Pointer.h.
References isStatic(), and isTemporary().
isTemporary()
bool clang::interp::Pointer::isTemporary () const inline
Checks if the storage is temporary.
Definition at line 454 of file Pointer.h.
References asBlockPointer(), isBlockPointer(), clang::interp::Block::isTemporary(), and clang::interp::BlockPointer::Pointee.
Referenced by isStaticTemporary().
isUnion()
bool clang::interp::Pointer::isUnion () const
Checks if the object is a union.
isUnknownSizeArray()
bool clang::interp::Pointer::isUnknownSizeArray () const inline
Checks if the structure is an array of unknown size.
Definition at line 389 of file Pointer.h.
References getFieldDesc(), isBlockPointer(), and clang::interp::Descriptor::isUnknownSizeArray().
Referenced by isOnePastEnd(), narrow(), and toAPValue().
isWeak()
bool clang::interp::Pointer::isWeak () const inline
Definition at line 471 of file Pointer.h.
References getDeclDesc(), isBlockPointer(), and isIntegralPointer().
isZero()
bool clang::interp::Pointer::isZero () const inline
Checks if the pointer is null.
Definition at line 247 of file Pointer.h.
References asBlockPointer(), asIntPointer(), isBlockPointer(), isIntegralPointer(), clang::interp::BlockPointer::Pointee, and clang::interp::IntPointer::Value.
Referenced by getIndex(), hasSameBase(), isPastEnd(), isRoot(), narrow(), clang::interp::MemberPointer::takeInstance(), toAPValue(), toDiagnosticString(), and toRValue().
isZeroSizeArray()
bool clang::interp::Pointer::isZeroSizeArray () const inline
Checks if the pointer is pointing to a zero-size array.
Definition at line 580 of file Pointer.h.
References getFieldDesc(), and clang::interp::Descriptor::isZeroSizeArray().
Referenced by isOnePastEnd().
narrow()
Pointer clang::interp::Pointer::narrow () const inline
Restricts the scope of an array element pointer.
Definition at line 170 of file Pointer.h.
References asBlockPointer(), clang::interp::BlockPointer::Base, getFieldDesc(), inPrimitiveArray(), isBlockPointer(), isOnePastEnd(), isUnknownSizeArray(), isZero(), and Pointer().
Referenced by clang::interp::collectBlocks(), and toRValue().
operator!=()
bool clang::interp::Pointer::operator!= (const Pointer & P) const inline
Definition at line 118 of file Pointer.h.
References P.
operator=() [1/2]
void Pointer::operator= (const Pointer & P)
Definition at line 66 of file Pointer.cpp.
References clang::interp::Block, isBlockPointer(), and P.
operator=() [2/2]
void Pointer::operator= (Pointer && P)
Definition at line 94 of file Pointer.cpp.
References clang::interp::Block, isBlockPointer(), and P.
operator==()
bool clang::interp::Pointer::operator== (const Pointer & P) const inline
Equality operators are just for tests.
Definition at line 105 of file Pointer.h.
References asBlockPointer(), asIntPointer(), clang::interp::BlockPointer::Base, isBlockPointer(), isIntegralPointer(), P, clang::interp::BlockPointer::Pointee, and clang::interp::IntPointer::Value.
print()
void Pointer::print (llvm::raw_ostream & OS) const
Prints the pointer.
Definition at line 189 of file Pointer.cpp.
References clang::interp::Block::getSize(), isBlockPointer(), isElementPastEnd(), and isRoot().
toAPValue()
APValue Pointer::toAPValue () const
Converts the pointer to an APValue.
Definition at line 122 of file Pointer.cpp.
References clang::APValue::LValuePathEntry::ArrayIndex(), clang::interp::Descriptor::asDecl(), clang::interp::Descriptor::asExpr(), asIntPointer(), clang::interp::Descriptor::asValueDecl(), E, clang::CharUnits::fromQuantity(), getArray(), getBase(), getDeclDesc(), getFieldDesc(), getIndex(), getNumElems(), isArrayElement(), isArrayRoot(), isDummy(), isField(), isIntegralPointer(), isOnePastEnd(), isUnknownSizeArray(), isZero(), Path, and clang::CharUnits::Zero().
Referenced by toDiagnosticString(), and toRValue().
toDiagnosticString()
std::string Pointer::toDiagnosticString (const ASTContext & Ctx) const
Converts the pointer to a string usable in diagnostics.
Definition at line 216 of file Pointer.cpp.
References asIntPointer(), clang::APValue::getAsString(), getType(), isIntegralPointer(), isZero(), and toAPValue().
toRValue()
std::optional< APValue > Pointer::toRValue (const Context & Ctx, QualType ResultType) const
Converts the pointer to an APValue that is an rvalue.
Definition at line 345 of file Pointer.cpp.
References clang::interp::Descriptor::asFieldDecl(), atField(), atIndex(), bool, clang::interp::Context::classify(), deref(), clang::interp::Record::fields(), clang::interp::Floating::getAPFloat(), clang::APValue::getArrayInitializedElt(), clang::interp::Context::getASTContext(), clang::interp::Record::getBase(), clang::interp::Record::getField(), getFieldDesc(), clang::interp::Record::getNumBases(), clang::interp::Record::getNumFields(), clang::interp::Record::getNumVirtualBases(), clang::ASTContext::getRecordType(), getType(), clang::interp::Record::getVirtualBase(), INT_TYPE_SWITCH, isActive(), isDummy(), clang::Type::isFloatingType(), clang::Type::isIntegerType(), isIntegralPointer(), isLive(), clang::QualType::isNull(), isPastEnd(), isZero(), narrow(), clang::T, toAPValue(), and TYPE_SWITCH.
Friends And Related Function Documentation
Block
friend class Block friend
Definition at line 647 of file Pointer.h.
DeadBlock
friend class DeadBlock friend
Definition at line 648 of file Pointer.h.
DynamicAllocator
friend class DynamicAllocator friend
Definition at line 652 of file Pointer.h.
InitMap
friend struct InitMap friend
Definition at line 651 of file Pointer.h.
InterpState
friend class InterpState friend
Definition at line 650 of file Pointer.h.
MemberPointer
friend class MemberPointer friend
Definition at line 649 of file Pointer.h.
Member Data Documentation
BS
BlockPointer clang::interp::Pointer::BS
Definition at line 690 of file Pointer.h.
Referenced by hasSameArray().
Int
IntPointer clang::interp::Pointer::Int
Definition at line 691 of file Pointer.h.
The documentation for this class was generated from the following files:
lib/AST/Interp/Pointer.h
lib/AST/Interp/Pointer.cpp