clang: clang::serialization::reader::ASTDeclContextNameLookupTrait Class Reference
clang::serialization::reader::ASTDeclContextNameLookupTrait Class Reference
Class that performs name lookup into a DeclContext stored in an AST file.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Serialization/ASTReaderInternals.h"
Classes
struct data_type_builder
Public Types
using data_type = SmallVector< GlobalDeclID, 4 >
The lookup result is a list of global declaration IDs.
using hash_value_type = unsigned
using offset_type = unsigned
using file_type = ModuleFile *
using external_key_type = DeclarationName
using internal_key_type = DeclarationNameKey
Public Member Functions
ASTDeclContextNameLookupTrait (ASTReader &Reader, ModuleFile &F)
internal_key_type ReadKey (const unsigned char *d, unsigned)
void ReadDataInto (internal_key_type, const unsigned char *d, unsigned DataLen, data_type_builder &Val)
file_type ReadFileRef (const unsigned char *&d)
Static Public Member Functions
static bool EqualKey (const internal_key_type &a, const internal_key_type &b)
static hash_value_type ComputeHash (const internal_key_type &Key)
static internal_key_type GetInternalKey (const external_key_type &Name)
static std::pair< unsigned, unsigned > ReadKeyDataLength (const unsigned char *&d)
static void MergeDataInto (const data_type &From, data_type_builder &To)
Static Public Attributes
static const int MaxTables = 4
Detailed Description
Class that performs name lookup into a DeclContext stored in an AST file.
Definition at line 43 of file ASTReaderInternals.h.
Member Typedef Documentation
data_type
using clang::serialization::reader::ASTDeclContextNameLookupTrait::data_type = SmallVector<GlobalDeclID, 4>
The lookup result is a list of global declaration IDs.
Definition at line 52 of file ASTReaderInternals.h.
external_key_type
using clang::serialization::reader::ASTDeclContextNameLookupTrait::external_key_type = DeclarationName
Definition at line 83 of file ASTReaderInternals.h.
file_type
using clang::serialization::reader::ASTDeclContextNameLookupTrait::file_type = ModuleFile *
Definition at line 81 of file ASTReaderInternals.h.
hash_value_type
using clang::serialization::reader::ASTDeclContextNameLookupTrait::hash_value_type = unsigned
Definition at line 79 of file ASTReaderInternals.h.
internal_key_type
using clang::serialization::reader::ASTDeclContextNameLookupTrait::internal_key_type = DeclarationNameKey
Definition at line 84 of file ASTReaderInternals.h.
offset_type
using clang::serialization::reader::ASTDeclContextNameLookupTrait::offset_type = unsigned
Definition at line 80 of file ASTReaderInternals.h.
Constructor & Destructor Documentation
ASTDeclContextNameLookupTrait()
clang::serialization::reader::ASTDeclContextNameLookupTrait::ASTDeclContextNameLookupTrait (ASTReader & Reader, ModuleFile & F) inline explicit
Definition at line 86 of file ASTReaderInternals.h.
Member Function Documentation
ComputeHash()
static hash_value_type clang::serialization::reader::ASTDeclContextNameLookupTrait::ComputeHash (const internal_key_type & Key) inline static
Definition at line 93 of file ASTReaderInternals.h.
References clang::serialization::DeclarationNameKey::getHash().
EqualKey()
static bool clang::serialization::reader::ASTDeclContextNameLookupTrait::EqualKey (const internal_key_type & a, const internal_key_type & b) inline static
Definition at line 89 of file ASTReaderInternals.h.
References b.
GetInternalKey()
static internal_key_type clang::serialization::reader::ASTDeclContextNameLookupTrait::GetInternalKey (const external_key_type & Name) inline static
Definition at line 97 of file ASTReaderInternals.h.
MergeDataInto()
static void clang::serialization::reader::ASTDeclContextNameLookupTrait::MergeDataInto (const data_type & From, data_type_builder & To) inline static
Definition at line 109 of file ASTReaderInternals.h.
References clang::serialization::reader::ASTDeclContextNameLookupTrait::data_type_builder::Data, ID, and clang::serialization::reader::ASTDeclContextNameLookupTrait::data_type_builder::insert().
ReadDataInto()
void ASTDeclContextNameLookupTrait::ReadDataInto (internal_key_type , const unsigned char * d, unsigned DataLen, data_type_builder & Val)
Definition at line 1211 of file ASTReader.cpp.
References clang::serialization::reader::ASTDeclContextNameLookupTrait::data_type_builder::insert().
ReadFileRef()
ModuleFile * ASTDeclContextNameLookupTrait::ReadFileRef (const unsigned char *& d)
Definition at line 1163 of file ASTReader.cpp.
ReadKey()
ASTDeclContextNameLookupTrait::internal_key_type ASTDeclContextNameLookupTrait::ReadKey (const unsigned char * d, unsigned)
Definition at line 1177 of file ASTReader.cpp.
References clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, Data, clang::DeclarationName::Identifier, clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, and clang::DeclarationName::ObjCZeroArgSelector.
ReadKeyDataLength()
std::pair< unsigned, unsigned > ASTDeclContextNameLookupTrait::ReadKeyDataLength (const unsigned char *& d) static
Definition at line 1172 of file ASTReader.cpp.
References readULEBKeyDataLength().
Member Data Documentation
MaxTables
const int clang::serialization::reader::ASTDeclContextNameLookupTrait::MaxTables = 4 static
Definition at line 49 of file ASTReaderInternals.h.
The documentation for this class was generated from the following files:
lib/Serialization/ASTReaderInternals.h
lib/Serialization/ASTReader.cpp