clang: clang::ObjCTypeParamList Class Reference
clang::ObjCTypeParamList Class Reference final
Stores a list of Objective-C type parameters for a parameterized class or a category/extension thereof.
#include "clang/AST/DeclObjC.h"
Public Types
using iterator = ObjCTypeParamDecl **
Iterate through the type parameters in the list.
using const_iterator = ObjCTypeParamDecl *const *
Public Member Functions
iterator begin ()
iterator end ()
unsigned size () const
Determine the number of type parameters in this list.
const_iterator begin () const
const_iterator end () const
ObjCTypeParamDecl * front () const
ObjCTypeParamDecl * back () const
SourceLocation getLAngleLoc () const
SourceLocation getRAngleLoc () const
SourceRange getSourceRange () const
void gatherDefaultTypeArgs (SmallVectorImpl< QualType > &typeArgs) const
Gather the default set of type arguments to be substituted for these type parameters when dealing with an unspecialized type.
Static Public Member Functions
static ObjCTypeParamList * create (ASTContext &ctx, SourceLocation lAngleLoc, ArrayRef< ObjCTypeParamDecl * > typeParams, SourceLocation rAngleLoc)
Create a new Objective-C type parameter list.
Public Attributes
friend TrailingObjects
Detailed Description
Stores a list of Objective-C type parameters for a parameterized class or a category/extension thereof.
@interface NSArray<T> // stores the <T>
@end
Definition at line 657 of file DeclObjC.h.
Member Typedef Documentation
const_iterator
using clang::ObjCTypeParamList::const_iterator = ObjCTypeParamDecl * const *
Definition at line 688 of file DeclObjC.h.
iterator
using clang::ObjCTypeParamList::iterator = ObjCTypeParamDecl **
Iterate through the type parameters in the list.
Definition at line 678 of file DeclObjC.h.
Member Function Documentation
back()
ObjCTypeParamDecl* clang::ObjCTypeParamList::back () const inline
Definition at line 703 of file DeclObjC.h.
References end(), and size().
begin() [1/2]
iterator clang::ObjCTypeParamList::begin () inline
Definition at line 680 of file DeclObjC.h.
Referenced by end(), front(), and sameObjCTypeArgs().
begin() [2/2]
const_iterator clang::ObjCTypeParamList::begin () const inline
Definition at line 690 of file DeclObjC.h.
create()
ObjCTypeParamList * ObjCTypeParamList::create (ASTContext & ctx, SourceLocation lAngleLoc, ArrayRef< ObjCTypeParamDecl * > typeParams, SourceLocation rAngleLoc) static
Create a new Objective-C type parameter list.
Definition at line 1519 of file DeclObjC.cpp.
References clang::ASTContext::Allocate().
Referenced by clang::ASTNodeImporter::ImportObjCTypeParamList(), and clang::ASTDeclReader::ReadObjCTypeParamList().
end() [1/2]
iterator clang::ObjCTypeParamList::end () inline
Definition at line 682 of file DeclObjC.h.
References begin(), and size().
Referenced by back().
end() [2/2]
const_iterator clang::ObjCTypeParamList::end () const inline
Definition at line 694 of file DeclObjC.h.
References begin(), and size().
front()
ObjCTypeParamDecl* clang::ObjCTypeParamList::front () const inline
Definition at line 698 of file DeclObjC.h.
References begin(), and size().
gatherDefaultTypeArgs()
void ObjCTypeParamList::gatherDefaultTypeArgs (SmallVectorImpl< QualType > & typeArgs) const
Gather the default set of type arguments to be substituted for these type parameters when dealing with an unspecialized type.
Definition at line 1530 of file DeclObjC.cpp.
References size().
getLAngleLoc()
SourceLocation clang::ObjCTypeParamList::getLAngleLoc () const inline
Definition at line 708 of file DeclObjC.h.
Referenced by clang::Sema::ActOnStartCategoryInterface(), clang::ASTDeclWriter::AddObjCTypeParamList(), and clang::ASTNodeImporter::ImportObjCTypeParamList().
getRAngleLoc()
SourceLocation clang::ObjCTypeParamList::getRAngleLoc () const inline
Definition at line 709 of file DeclObjC.h.
Referenced by clang::ASTDeclWriter::AddObjCTypeParamList(), and clang::ASTNodeImporter::ImportObjCTypeParamList().
getSourceRange()
SourceRange clang::ObjCTypeParamList::getSourceRange () const inline
Definition at line 710 of file DeclObjC.h.
Referenced by clang::Sema::ActOnForwardClassDeclaration(), and clang::Sema::ActOnStartCategoryInterface().
size()
unsigned clang::ObjCTypeParamList::size () const inline
Determine the number of type parameters in this list.
Definition at line 685 of file DeclObjC.h.
Referenced by clang::ASTDeclWriter::AddObjCTypeParamList(), back(), clang::ObjCObjectType::computeSuperClassTypeSlow(), end(), front(), and gatherDefaultTypeArgs().
Member Data Documentation
TrailingObjects
friend clang::ObjCTypeParamList::TrailingObjects
Definition at line 669 of file DeclObjC.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclObjC.h
lib/AST/DeclObjC.cpp