clang: clang::ento::ConditionTruthVal Class Reference
clang::ento::ConditionTruthVal Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/ConstraintManager.h"
Public Member Functions
ConditionTruthVal (bool constraint)
Construct a ConditionTruthVal indicating the constraint is constrained to either true or false, depending on the boolean value provided.
ConditionTruthVal ()=default
Construct a ConstraintVal indicating the constraint is underconstrained.
bool getValue () const
bool isConstrainedTrue () const
Return true if the constraint is perfectly constrained to 'true'.
bool isConstrainedFalse () const
Return true if the constraint is perfectly constrained to 'false'.
bool isConstrained () const
Return true if the constrained is perfectly constrained.
bool isUnderconstrained () const
Return true if the constrained is underconstrained and we do not know if the constraint is true of value.
Detailed Description
Definition at line 38 of file ConstraintManager.h.
Constructor & Destructor Documentation
ConditionTruthVal() [1/2]
clang::ento::ConditionTruthVal::ConditionTruthVal (bool constraint) inline
Construct a ConditionTruthVal indicating the constraint is constrained to either true or false, depending on the boolean value provided.
Definition at line 44 of file ConstraintManager.h.
ConditionTruthVal() [2/2]
clang::ento::ConditionTruthVal::ConditionTruthVal () default
Construct a ConstraintVal indicating the constraint is underconstrained.
Member Function Documentation
getValue()
bool clang::ento::ConditionTruthVal::getValue () const inline
Returns
Stored value, assuming that the value is known. Crashes otherwise.
Definition at line 51 of file ConstraintManager.h.
Referenced by clang::ento::ProgramState::isNonNull().
isConstrained()
bool clang::ento::ConditionTruthVal::isConstrained () const inline
Return true if the constrained is perfectly constrained.
Definition at line 66 of file ConstraintManager.h.
isConstrainedFalse()
bool clang::ento::ConditionTruthVal::isConstrainedFalse () const inline
Return true if the constraint is perfectly constrained to 'false'.
Definition at line 61 of file ConstraintManager.h.
Referenced by clang::ento::SMTConstraintManager::checkNull().
isConstrainedTrue()
bool clang::ento::ConditionTruthVal::isConstrainedTrue () const inline
Return true if the constraint is perfectly constrained to 'true'.
Definition at line 56 of file ConstraintManager.h.
Referenced by clang::ento::SMTConstraintManager::checkNull(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), and clang::ento::retaincountchecker::RetainCountChecker::evalAssume().
isUnderconstrained()
bool clang::ento::ConditionTruthVal::isUnderconstrained () const inline
Return true if the constrained is underconstrained and we do not know if the constraint is true of value.
Definition at line 72 of file ConstraintManager.h.
Referenced by clang::ento::ProgramState::isNonNull().
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/ConstraintManager.h