clang: clang::FrontendInputFile Class Reference
clang::FrontendInputFile Class Reference
An input file for the front end.
#include "clang/Frontend/FrontendOptions.h"
Public Member Functions
FrontendInputFile ()=default
FrontendInputFile (StringRef File, InputKind Kind, bool IsSystem=false)
FrontendInputFile (llvm::MemoryBufferRef Buffer, InputKind Kind, bool IsSystem=false)
InputKind getKind () const
bool isSystem () const
bool isEmpty () const
bool isFile () const
bool isBuffer () const
bool isPreprocessed () const
bool isHeader () const
InputKind::HeaderUnitKind getHeaderUnitKind () const
StringRef getFile () const
llvm::MemoryBufferRef getBuffer () const
Detailed Description
An input file for the front end.
Definition at line 229 of file FrontendOptions.h.
Constructor & Destructor Documentation
FrontendInputFile() [1/3]
clang::FrontendInputFile::FrontendInputFile () default
FrontendInputFile() [2/3]
clang::FrontendInputFile::FrontendInputFile (StringRef File, InputKind Kind, bool IsSystem = false) inline
Definition at line 246 of file FrontendOptions.h.
References clang::File.
FrontendInputFile() [3/3]
clang::FrontendInputFile::FrontendInputFile (llvm::MemoryBufferRef Buffer, InputKind Kind, bool IsSystem = false) inline
Definition at line 248 of file FrontendOptions.h.
Member Function Documentation
getBuffer()
llvm::MemoryBufferRef clang::FrontendInputFile::getBuffer () const inline
Definition at line 269 of file FrontendOptions.h.
References isBuffer().
Referenced by clang::FrontendAction::getCurrentFileOrBufferName(), clang::ASTUnit::getMainFileName(), and clang::CompilerInstance::InitializeSourceManager().
getFile()
StringRef clang::FrontendInputFile::getFile () const inline
Definition at line 264 of file FrontendOptions.h.
References clang::File, and isFile().
Referenced by clang::FrontendAction::BeginSourceFile(), clang::FrontendAction::getCurrentFile(), clang::FrontendAction::getCurrentFileOrBufferName(), clang::ASTUnit::getMainFileName(), and clang::CompilerInstance::InitializeSourceManager().
getHeaderUnitKind()
InputKind::HeaderUnitKind clang::FrontendInputFile::getHeaderUnitKind () const inline
Definition at line 260 of file FrontendOptions.h.
getKind()
InputKind clang::FrontendInputFile::getKind () const inline
Definition at line 252 of file FrontendOptions.h.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::FrontendAction::getCurrentFileKind(), clang::CompilerInstance::InitializeSourceManager(), and needsModules().
isBuffer()
bool clang::FrontendInputFile::isBuffer () const inline
Definition at line 257 of file FrontendOptions.h.
Referenced by getBuffer(), clang::CompilerInstance::InitializeSourceManager(), and isFile().
isEmpty()
bool clang::FrontendInputFile::isEmpty () const inline
Definition at line 255 of file FrontendOptions.h.
References clang::File.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::FrontendAction::getCurrentFile(), clang::FrontendAction::getCurrentFileKind(), clang::FrontendAction::getCurrentFileOrBufferName(), and clang::FrontendAction::isCurrentFileAST().
isFile()
bool clang::FrontendInputFile::isFile () const inline
Definition at line 256 of file FrontendOptions.h.
References isBuffer().
Referenced by clang::FrontendAction::getCurrentFileOrBufferName(), getFile(), and clang::ASTUnit::getMainFileName().
isHeader()
bool clang::FrontendInputFile::isHeader () const inline
Definition at line 259 of file FrontendOptions.h.
isPreprocessed()
bool clang::FrontendInputFile::isPreprocessed () const inline
Definition at line 258 of file FrontendOptions.h.
isSystem()
bool clang::FrontendInputFile::isSystem () const inline
Definition at line 253 of file FrontendOptions.h.
Referenced by clang::CompilerInstance::InitializeSourceManager().
The documentation for this class was generated from the following file:
include/clang/Frontend/FrontendOptions.h