clang: clang::ento::SwitchNodeBuilder::iterator Class Reference
clang::ento::SwitchNodeBuilder::iterator Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h"
Public Member Functions
iterator & operator++ ()
bool operator!= (const iterator &X) const
bool operator== (const iterator &X) const
const CaseStmt * getCase () const
const CFGBlock * getBlock () const
Friends
class SwitchNodeBuilder
Detailed Description
Definition at line 537 of file CoreEngine.h.
Member Function Documentation
getBlock()
const CFGBlock* clang::ento::SwitchNodeBuilder::iterator::getBlock () const inline
Definition at line 553 of file CoreEngine.h.
Referenced by clang::ento::SwitchNodeBuilder::generateCaseStmtNode().
getCase()
const CaseStmt* clang::ento::SwitchNodeBuilder::iterator::getCase () const inline
Definition at line 549 of file CoreEngine.h.
operator!=()
bool clang::ento::SwitchNodeBuilder::iterator::operator!= (const iterator & X) const inline
Definition at line 546 of file CoreEngine.h.
References clang::tooling::X().
operator++()
iterator& clang::ento::SwitchNodeBuilder::iterator::operator++ () inline
Definition at line 545 of file CoreEngine.h.
operator==()
bool clang::ento::SwitchNodeBuilder::iterator::operator== (const iterator & X) const inline
Definition at line 547 of file CoreEngine.h.
References clang::tooling::X().
Friends And Related Function Documentation
SwitchNodeBuilder
friend class SwitchNodeBuilder friend
Definition at line 538 of file CoreEngine.h.
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h