clang: clang::driver::tools::SPIRCheck Class Reference
clang::driver::tools::SPIRCheck Class Reference final
SPIR Checking tool.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/Clang.h"
Public Member Functions
SPIRCheck (const ToolChain &TC)
bool hasIntegratedCPP () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isLinkJob () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
SPIR Checking tool.
Definition at line 215 of file Clang.h.
Constructor & Destructor Documentation
SPIRCheck()
clang::driver::tools::SPIRCheck::SPIRCheck (const ToolChain & TC) inline
Definition at line 217 of file Clang.h.
Member Function Documentation
ConstructJob()
void SPIRCheck::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 9263 of file Clang.cpp.
References Cmd, clang::driver::InputInfo::getBaseInput(), clang::driver::InputInfo::getFilename(), clang::driver::Tool::getShortName(), clang::driver::Tool::getToolChain(), and clang::driver::ResponseFileSupport::None().
hasIntegratedCPP()
bool clang::driver::tools::SPIRCheck::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 220 of file Clang.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Clang.h
lib/Driver/ToolChains/Clang.cpp