clang: clang::OpenACCAutoClause Class Reference
clang::OpenACCAutoClause Class Reference
#include "clang/AST/OpenACCClause.h"
Public Member Functions
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClause
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Static Public Member Functions
static bool classof (const OpenACCClause *C)
static OpenACCAutoClause * Create (const ASTContext &Ctx, SourceLocation BeginLoc, SourceLocation EndLoc)
Static Public Member Functions inherited from clang::OpenACCClause
static bool classof (const OpenACCClause *)
Protected Member Functions
OpenACCAutoClause (SourceLocation BeginLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClause
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Additional Inherited Members
Public Types inherited from clang::OpenACCClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Detailed Description
Definition at line 58 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCAutoClause()
clang::OpenACCAutoClause::OpenACCAutoClause (SourceLocation BeginLoc, SourceLocation EndLoc) inline protected
Definition at line 60 of file OpenACCClause.h.
References clang::Auto.
Referenced by Create().
Member Function Documentation
children() [1/2]
child_range clang::OpenACCAutoClause::children () inline
Definition at line 71 of file OpenACCClause.h.
children() [2/2]
const_child_range clang::OpenACCAutoClause::children () const inline
Definition at line 74 of file OpenACCClause.h.
classof()
static bool clang::OpenACCAutoClause::classof (const OpenACCClause * C) inline static
Definition at line 64 of file OpenACCClause.h.
References clang::Auto.
Create()
OpenACCAutoClause * OpenACCAutoClause::Create (const ASTContext & Ctx, SourceLocation BeginLoc, SourceLocation EndLoc) static
Definition at line 323 of file OpenACCClause.cpp.
References OpenACCAutoClause().
Referenced by clang::ASTRecordReader::readOpenACCClause().
The documentation for this class was generated from the following files:
include/clang/AST/OpenACCClause.h
lib/AST/OpenACCClause.cpp