clang: clang::CodeGen::CodeGenFunction::RunCleanupsScope Class Reference
clang::CodeGen::CodeGenFunction::RunCleanupsScope Class Reference
Enters a new scope for capturing cleanups, all of which will be executed once the scope is exited.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
RunCleanupsScope (CodeGenFunction &CGF)
Enter a new cleanup scope.
~RunCleanupsScope ()
Exit this cleanup scope, emitting any accumulated cleanups.
bool requiresCleanups () const
Determine whether this scope requires any cleanups.
void ForceCleanup (std::initializer_list< llvm::Value ** > ValuesToReload={})
Force the emission of cleanups now, instead of waiting until this object is destroyed.
Protected Attributes
bool PerformCleanup
CodeGenFunction & CGF
Detailed Description
Enters a new scope for capturing cleanups, all of which will be executed once the scope is exited.
Definition at line 872 of file CodeGenFunction.h.
Constructor & Destructor Documentation
RunCleanupsScope()
clang::CodeGen::CodeGenFunction::RunCleanupsScope::RunCleanupsScope (CodeGenFunction & CGF) inline explicit
Enter a new cleanup scope.
Definition at line 888 of file CodeGenFunction.h.
References CGF, clang::CodeGen::CodeGenFunction::CurrentCleanupScopeDepth, clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupStack, and clang::CodeGen::EHScopeStack::stable_begin().
~RunCleanupsScope()
clang::CodeGen::CodeGenFunction::RunCleanupsScope::~RunCleanupsScope () inline
Exit this cleanup scope, emitting any accumulated cleanups.
Definition at line 901 of file CodeGenFunction.h.
References ForceCleanup(), and PerformCleanup.
Member Function Documentation
ForceCleanup()
void clang::CodeGen::CodeGenFunction::RunCleanupsScope::ForceCleanup (std::initializer_list< llvm::Value ** > ValuesToReload = {}) inline
Force the emission of cleanups now, instead of waiting until this object is destroyed.
Parameters
ValuesToReload - A list of values that need to be available at the insertion point after cleanup emission. If cleanup emission created a shared cleanup block, these value pointers will be rewritten. Otherwise, they not will be modified.
Definition at line 917 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitConstructorBody(), clang::CodeGen::CodeGenFunction::EmitDestructorBody(), clang::CodeGen::CodeGenFunction::LexicalScope::ForceCleanup(), clang::CodeGen::CodeGenFunction::OMPPrivateScope::ForceCleanup(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), and ~RunCleanupsScope().
requiresCleanups()
bool clang::CodeGen::CodeGenFunction::RunCleanupsScope::requiresCleanups () const inline
Determine whether this scope requires any cleanups.
Definition at line 907 of file CodeGenFunction.h.
References CGF, clang::CodeGen::CodeGenFunction::EHStack, and clang::CodeGen::EHScopeStack::stable_begin().
Referenced by emitCXXDestructMethod().
Member Data Documentation
CGF
CodeGenFunction& clang::CodeGen::CodeGenFunction::RunCleanupsScope::CGF protected
Definition at line 884 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), clang::CodeGen::CodeGenFunction::LexicalScope::ForceCleanup(), clang::CodeGen::CodeGenFunction::OMPPrivateScope::ForceCleanup(), clang::CodeGen::CodeGenFunction::OMPPrivateScope::isGlobalVarCaptured(), clang::CodeGen::CodeGenFunction::LexicalScope::LexicalScope(), clang::CodeGen::CodeGenFunction::OMPPrivateScope::Privatize(), requiresCleanups(), clang::CodeGen::CodeGenFunction::LexicalScope::rescopeLabels(), RunCleanupsScope(), and clang::CodeGen::CodeGenFunction::LexicalScope::~LexicalScope().
PerformCleanup
bool clang::CodeGen::CodeGenFunction::RunCleanupsScope::PerformCleanup protected
Definition at line 877 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::LexicalScope::addLabel(), clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), clang::CodeGen::CodeGenFunction::LexicalScope::~LexicalScope(), clang::CodeGen::CodeGenFunction::OMPPrivateScope::~OMPPrivateScope(), and ~RunCleanupsScope().
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h