clang: clang::BlockDecl::Capture Class Reference
clang::BlockDecl::Capture Class Reference
A class which contains all the information about a particular captured value.
#include "clang/AST/Decl.h"
Public Member Functions
Capture (VarDecl *variable, bool byRef, bool nested, Expr *copy)
VarDecl * getVariable () const
The variable being captured.
bool isByRef () const
Whether this is a "by ref" capture, i.e.
bool isEscapingByref () const
bool isNonEscapingByref () const
bool isNested () const
Whether this is a nested capture, i.e.
bool hasCopyExpr () const
Expr * getCopyExpr () const
void setCopyExpr (Expr *e)
Detailed Description
A class which contains all the information about a particular captured value.
Definition at line 4185 of file Decl.h.
Constructor & Destructor Documentation
Capture()
clang::BlockDecl::Capture::Capture (VarDecl * variable, bool byRef, bool nested, Expr * copy) inline
Definition at line 4200 of file Decl.h.
Member Function Documentation
getCopyExpr()
Expr* clang::BlockDecl::Capture::getCopyExpr () const inline
Definition at line 4225 of file Decl.h.
Referenced by computeCopyInfoForBlockCapture(), and clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction().
getVariable()
VarDecl* clang::BlockDecl::Capture::getVariable () const inline
The variable being captured.
Definition at line 4206 of file Decl.h.
Referenced by computeBlockInfo(), clang::CodeGen::CodeGenFunction::GenerateBlockFunction(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), getBlockCaptureStr(), getCaptureFieldType(), isEscapingByref(), and isNonEscapingByref().
hasCopyExpr()
bool clang::BlockDecl::Capture::hasCopyExpr () const inline
Definition at line 4224 of file Decl.h.
Referenced by computeBlockInfo().
isByRef()
bool clang::BlockDecl::Capture::isByRef () const inline
Whether this is a "by ref" capture, i.e.
a capture of a __block variable.
Definition at line 4210 of file Decl.h.
Referenced by computeCopyInfoForBlockCapture(), and clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction().
isEscapingByref()
bool clang::BlockDecl::Capture::isEscapingByref () const inline
Definition at line 4212 of file Decl.h.
References getVariable(), and clang::VarDecl::isEscapingByref().
Referenced by computeBlockInfo(), computeCopyInfoForBlockCapture(), and computeDestroyInfoForBlockCapture().
isNested()
bool clang::BlockDecl::Capture::isNested () const inline
Whether this is a nested capture, i.e.
the variable captured is not from outside the immediately enclosing function/block.
Definition at line 4222 of file Decl.h.
Referenced by getCaptureFieldType().
isNonEscapingByref()
bool clang::BlockDecl::Capture::isNonEscapingByref () const inline
Definition at line 4216 of file Decl.h.
References getVariable(), and clang::VarDecl::isNonEscapingByref().
setCopyExpr()
void clang::BlockDecl::Capture::setCopyExpr (Expr * e) inline
Definition at line 4226 of file Decl.h.
The documentation for this class was generated from the following file:
include/clang/AST/Decl.h