clang: clang::CodeGen::ABIInfo Class Reference
clang::CodeGen::ABIInfo Class Reference abstract
ABIInfo - Target specific hooks for defining how a type should be passed or returned from functions.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/ABIInfo.h"
Public Member Functions
ABIInfo (CodeGen::CodeGenTypes &cgt)
virtual ~ABIInfo ()
virtual bool allowBFloatArgsAndRet () const
CodeGen::CGCXXABI & getCXXABI () const
ASTContext & getContext () const
llvm::LLVMContext & getVMContext () const
const llvm::DataLayout & getDataLayout () const
const TargetInfo & getTarget () const
const CodeGenOptions & getCodeGenOpts () const
llvm::CallingConv::ID getRuntimeCC () const
Return the calling convention to use for system runtime functions.
virtual void computeInfo (CodeGen::CGFunctionInfo &FI) const =0
virtual CodeGen::Address EmitVAArg (CodeGen::CodeGenFunction &CGF, CodeGen::Address VAListAddr, QualType Ty) const =0
EmitVAArg - Emit the target dependent code to load a value of.
bool isAndroid () const
bool isOHOSFamily () const
virtual CodeGen::Address EmitMSVAArg (CodeGen::CodeGenFunction &CGF, CodeGen::Address VAListAddr, QualType Ty) const
Emit the target dependent code to load a value of.
virtual bool isHomogeneousAggregateBaseType (QualType Ty) const
virtual bool isHomogeneousAggregateSmallEnough (const Type *Base, uint64_t Members) const
virtual bool isZeroLengthBitfieldPermittedInHomogeneousAggregate () const
bool isHomogeneousAggregate (QualType Ty, const Type *&Base, uint64_t &Members) const
isHomogeneousAggregate - Return true if a type is an ELFv2 homogeneous aggregate.
bool isPromotableIntegerTypeForABI (QualType Ty) const
CodeGen::ABIArgInfo getNaturalAlignIndirect (QualType Ty, bool ByVal=true, bool Realign=false, llvm::Type *Padding=nullptr) const
A convenience method to return an indirect ABIArgInfo with an expected alignment equal to the ABI alignment of the given type.
CodeGen::ABIArgInfo getNaturalAlignIndirectInReg (QualType Ty, bool Realign=false) const
virtual void appendAttributeMangling (TargetAttr *Attr, raw_ostream &Out) const
virtual void appendAttributeMangling (TargetVersionAttr *Attr, raw_ostream &Out) const
virtual void appendAttributeMangling (TargetClonesAttr *Attr, unsigned Index, raw_ostream &Out) const
virtual void appendAttributeMangling (StringRef AttrStr, raw_ostream &Out) const
Protected Attributes
CodeGen::CodeGenTypes & CGT
llvm::CallingConv::ID RuntimeCC
Detailed Description
ABIInfo - Target specific hooks for defining how a type should be passed or returned from functions.
Definition at line 45 of file ABIInfo.h.
Constructor & Destructor Documentation
ABIInfo()
clang::CodeGen::ABIInfo::ABIInfo (CodeGen::CodeGenTypes & cgt) inline
Definition at line 51 of file ABIInfo.h.
~ABIInfo()
ABIInfo::~ABIInfo () virtual default
Member Function Documentation
allowBFloatArgsAndRet()
virtual bool clang::CodeGen::ABIInfo::allowBFloatArgsAndRet () const inline virtual
Definition at line 56 of file ABIInfo.h.
appendAttributeMangling() [1/4]
void ABIInfo::appendAttributeMangling (StringRef AttrStr, raw_ostream & Out) const virtual
Definition at line 205 of file ABIInfo.cpp.
References CGT, clang::ParsedTargetAttr::CPU, clang::ParsedTargetAttr::Features, clang::CodeGen::CodeGenTypes::getTarget(), and clang::TargetInfo::parseTargetAttr().
appendAttributeMangling() [2/4]
void ABIInfo::appendAttributeMangling (TargetAttr * Attr, raw_ostream & Out) const virtual
Definition at line 187 of file ABIInfo.cpp.
Referenced by appendAttributeMangling().
appendAttributeMangling() [3/4]
void ABIInfo::appendAttributeMangling (TargetClonesAttr * Attr, unsigned Index, raw_ostream & Out) const virtual
Definition at line 199 of file ABIInfo.cpp.
appendAttributeMangling() [4/4]
void ABIInfo::appendAttributeMangling (TargetVersionAttr * Attr, raw_ostream & Out) const virtual
Definition at line 194 of file ABIInfo.cpp.
References appendAttributeMangling().
computeInfo()
virtual void clang::CodeGen::ABIInfo::computeInfo (CodeGen::CGFunctionInfo & FI) const pure virtual
Implemented in PNaClABIInfo, and clang::CodeGen::DefaultABIInfo.
Referenced by clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo().
EmitMSVAArg()
Address ABIInfo::EmitMSVAArg (CodeGen::CodeGenFunction & CGF, CodeGen::Address VAListAddr, QualType Ty) const virtual
Emit the target dependent code to load a value of.
Ty from the __builtin_ms_va_list pointed to by
VAListAddr.
Definition at line 42 of file ABIInfo.cpp.
References clang::CodeGen::Address::invalid().
Referenced by clang::CodeGen::CodeGenFunction::EmitVAArg().
EmitVAArg()
virtual CodeGen::Address clang::CodeGen::ABIInfo::EmitVAArg (CodeGen::CodeGenFunction & CGF, CodeGen::Address VAListAddr, QualType Ty) const pure virtual
EmitVAArg - Emit the target dependent code to load a value of.
Ty from the va_list pointed to by
VAListAddr.
Implemented in PNaClABIInfo, and clang::CodeGen::DefaultABIInfo.
Referenced by clang::CodeGen::CodeGenFunction::EmitVAArg().
getCodeGenOpts()
const CodeGenOptions & ABIInfo::getCodeGenOpts () const
Definition at line 32 of file ABIInfo.cpp.
References CGT, and clang::CodeGen::CodeGenTypes::getCodeGenOpts().
getContext()
ASTContext & ABIInfo::getContext () const
Definition at line 20 of file ABIInfo.cpp.
References CGT, and clang::CodeGen::CodeGenTypes::getContext().
Referenced by clang::CodeGen::DefaultABIInfo::classifyReturnType(), getNaturalAlignIndirect(), getNaturalAlignIndirectInReg(), isHomogeneousAggregate(), isPromotableIntegerTypeForABI(), and isZeroLengthBitfieldPermittedInHomogeneousAggregate().
getCXXABI()
CGCXXABI & ABIInfo::getCXXABI () const
Definition at line 18 of file ABIInfo.cpp.
References CGT, and clang::CodeGen::CodeGenTypes::getCXXABI().
Referenced by clang::CodeGen::DefaultABIInfo::classifyArgumentType(), clang::CodeGen::DefaultABIInfo::computeInfo(), and isHomogeneousAggregate().
getDataLayout()
const llvm::DataLayout & ABIInfo::getDataLayout () const
Definition at line 26 of file ABIInfo.cpp.
References CGT, and clang::CodeGen::CodeGenTypes::getDataLayout().
getNaturalAlignIndirect()
ABIArgInfo ABIInfo::getNaturalAlignIndirect (QualType Ty, bool ByVal = true, bool Realign = false, llvm::Type * Padding = nullptr) const
A convenience method to return an indirect ABIArgInfo with an expected alignment equal to the ABI alignment of the given type.
Definition at line 174 of file ABIInfo.cpp.
References getContext(), and clang::CodeGen::ABIArgInfo::getIndirect().
Referenced by clang::CodeGen::DefaultABIInfo::classifyArgumentType(), clang::CodeGen::classifyReturnType(), and clang::CodeGen::DefaultABIInfo::classifyReturnType().
getNaturalAlignIndirectInReg()
ABIArgInfo ABIInfo::getNaturalAlignIndirectInReg (QualType Ty, bool Realign = false) const
Definition at line 181 of file ABIInfo.cpp.
References getContext(), and clang::CodeGen::ABIArgInfo::getIndirectInReg().
getRuntimeCC()
llvm::CallingConv::ID clang::CodeGen::ABIInfo::getRuntimeCC () const inline
Return the calling convention to use for system runtime functions.
Definition at line 67 of file ABIInfo.h.
References RuntimeCC.
getTarget()
const TargetInfo & ABIInfo::getTarget () const
Definition at line 30 of file ABIInfo.cpp.
References CGT, and clang::CodeGen::CodeGenTypes::getTarget().
Referenced by isAndroid(), and isOHOSFamily().
getVMContext()
llvm::LLVMContext & ABIInfo::getVMContext () const
Definition at line 22 of file ABIInfo.cpp.
References CGT, and clang::CodeGen::CodeGenTypes::getLLVMContext().
isAndroid()
bool ABIInfo::isAndroid () const
Definition at line 36 of file ABIInfo.cpp.
References getTarget(), and clang::TargetInfo::getTriple().
isHomogeneousAggregate()
bool ABIInfo::isHomogeneousAggregate (QualType Ty, const Type *& Base, uint64_t & Members) const
isHomogeneousAggregate - Return true if a type is an ELFv2 homogeneous aggregate.
Base is set to the base element type, and Members is set to the number of base elements.
Definition at line 61 of file ABIInfo.cpp.
References clang::RecordDecl::fields(), clang::Type::getAs(), getContext(), getCXXABI(), clang::QualType::getTypePtr(), clang::ASTContext::getTypeSize(), clang::ASTContext::getVectorType(), clang::RecordDecl::hasFlexibleArrayMember(), clang::CodeGen::isEmptyRecord(), isHomogeneousAggregateBaseType(), isHomogeneousAggregateSmallEnough(), clang::TagDecl::isUnion(), clang::Type::isVectorType(), isZeroLengthBitfieldPermittedInHomogeneousAggregate(), and max().
Referenced by isTrivialForMSVC().
isHomogeneousAggregateBaseType()
bool ABIInfo::isHomogeneousAggregateBaseType (QualType Ty) const virtual
Definition at line 47 of file ABIInfo.cpp.
Referenced by isHomogeneousAggregate().
isHomogeneousAggregateSmallEnough()
bool ABIInfo::isHomogeneousAggregateSmallEnough (const Type * Base, uint64_t Members) const virtual
Definition at line 51 of file ABIInfo.cpp.
Referenced by isHomogeneousAggregate().
isOHOSFamily()
bool ABIInfo::isOHOSFamily () const
Definition at line 38 of file ABIInfo.cpp.
References getTarget(), and clang::TargetInfo::getTriple().
isPromotableIntegerTypeForABI()
bool ABIInfo::isPromotableIntegerTypeForABI (QualType Ty) const
Definition at line 163 of file ABIInfo.cpp.
References clang::Type::getAs(), and getContext().
Referenced by clang::CodeGen::DefaultABIInfo::classifyReturnType().
isZeroLengthBitfieldPermittedInHomogeneousAggregate()
bool ABIInfo::isZeroLengthBitfieldPermittedInHomogeneousAggregate () const virtual
Definition at line 56 of file ABIInfo.cpp.
References getContext(), and clang::ASTContext::getLangOpts().
Referenced by isHomogeneousAggregate().
Member Data Documentation
CGT
CodeGen::CodeGenTypes& clang::CodeGen::ABIInfo::CGT protected
Definition at line 47 of file ABIInfo.h.
Referenced by appendAttributeMangling(), getCodeGenOpts(), getContext(), getCXXABI(), getDataLayout(), getTarget(), and getVMContext().
RuntimeCC
llvm::CallingConv::ID clang::CodeGen::ABIInfo::RuntimeCC protected
Definition at line 48 of file ABIInfo.h.
Referenced by getRuntimeCC().
The documentation for this class was generated from the following files:
lib/CodeGen/ABIInfo.h
lib/CodeGen/ABIInfo.cpp