clang: clang::PrecompiledPreamble::PCHStorage Class Reference
clang::PrecompiledPreamble::PCHStorage Class Reference
Public Types
enum class Kind
Public Member Functions
Kind getKind () const
llvm::StringRef filePath () const
llvm::StringRef memoryContents () const
void shrink ()
Static Public Member Functions
static std::unique_ptr< PCHStorage > file (std::unique_ptr< TempPCHFile > File)
static std::unique_ptr< PCHStorage > inMemory (std::shared_ptr< PCHBuffer > Buf)
Detailed Description
Definition at line 358 of file PrecompiledPreamble.cpp.
Member Enumeration Documentation
Kind
enum PrecompiledPreamble::PCHStorage::Kind strong
Definition at line 372 of file PrecompiledPreamble.cpp.
Member Function Documentation
file()
static std::unique_ptr<PCHStorage> clang::PrecompiledPreamble::PCHStorage::file (std::unique_ptr< TempPCHFile > File) inline static
Definition at line 360 of file PrecompiledPreamble.cpp.
References clang::File.
Referenced by clang::PrecompiledPreamble::Build().
filePath()
llvm::StringRef clang::PrecompiledPreamble::PCHStorage::filePath () const inline
Definition at line 380 of file PrecompiledPreamble.cpp.
References clang::File, and clang::PrecompiledPreamble::PCHStorage::getKind().
getKind()
Kind clang::PrecompiledPreamble::PCHStorage::getKind () const inline
Definition at line 373 of file PrecompiledPreamble.cpp.
References clang::File.
Referenced by clang::PrecompiledPreamble::PCHStorage::filePath(), and clang::PrecompiledPreamble::PCHStorage::memoryContents().
inMemory()
static std::unique_ptr<PCHStorage> clang::PrecompiledPreamble::PCHStorage::inMemory (std::shared_ptr< PCHBuffer > Buf) inline static
Definition at line 366 of file PrecompiledPreamble.cpp.
Referenced by clang::PrecompiledPreamble::Build().
memoryContents()
llvm::StringRef clang::PrecompiledPreamble::PCHStorage::memoryContents () const inline
Definition at line 384 of file PrecompiledPreamble.cpp.
References clang::PrecompiledPreamble::PCHStorage::getKind().
shrink()
void clang::PrecompiledPreamble::PCHStorage::shrink () inline
Definition at line 392 of file PrecompiledPreamble.cpp.
The documentation for this class was generated from the following file:
lib/Frontend/PrecompiledPreamble.cpp