clang: clang::IncrementalCUDADeviceParser Class Reference
clang::IncrementalCUDADeviceParser Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Interpreter/DeviceOffload.h"
Public Member Functions
IncrementalCUDADeviceParser (Interpreter &Interp, std::unique_ptr< CompilerInstance > Instance, IncrementalParser &HostParser, llvm::LLVMContext &LLVMCtx, llvm::IntrusiveRefCntPtr< llvm::vfs::InMemoryFileSystem > VFS, llvm::Error &Err)
llvm::Expected< PartialTranslationUnit & > Parse (llvm::StringRef Input) override
Parses incremental input by creating an in-memory file.
llvm::Expected< llvm::StringRef > GeneratePTX ()
llvm::Error GenerateFatbinary ()
~IncrementalCUDADeviceParser ()
Public Member Functions inherited from clang::IncrementalParser
IncrementalParser (Interpreter &Interp, std::unique_ptr< CompilerInstance > Instance, llvm::LLVMContext &LLVMCtx, llvm::Error &Err)
virtual ~IncrementalParser ()
CompilerInstance * getCI ()
CodeGenerator * getCodeGen () const
llvm::StringRef GetMangledName (GlobalDecl GD) const
Uses the CodeGenModule mangled name cache and avoids recomputing.
void CleanUpPTU (PartialTranslationUnit &PTU)
std::list< PartialTranslationUnit > & getPTUs ()
std::unique_ptr< llvm::Module > GenModule ()
Protected Attributes
IncrementalParser & HostParser
int SMVersion
llvm::SmallString< 1024 > PTXCode
llvm::SmallVector< char, 1024 > FatbinContent
llvm::IntrusiveRefCntPtr< llvm::vfs::InMemoryFileSystem > VFS
Protected Attributes inherited from clang::IncrementalParser
std::unique_ptr< IncrementalAction > Act
Long-lived, incremental parsing action.
std::unique_ptr< CompilerInstance > CI
Compiler instance performing the incremental compilation.
std::unique_ptr< Parser > P
Parser.
ASTConsumer * Consumer = nullptr
Consumer to process the produced top level decls. Owned by Act.
unsigned InputCount = 0
Counts the number of direct user input lines that have been parsed.
std::list< PartialTranslationUnit > PTUs
List containing every information about every incrementally parsed piece of code.
std::unique_ptr< llvm::Module > CachedInCodeGenModule
When CodeGen is created the first llvm::Module gets cached in many places and we must keep it alive.
Additional Inherited Members
Protected Member Functions inherited from clang::IncrementalParser
IncrementalParser ()
Detailed Description
Definition at line 22 of file DeviceOffload.h.
Constructor & Destructor Documentation
IncrementalCUDADeviceParser()
clang::IncrementalCUDADeviceParser::IncrementalCUDADeviceParser (Interpreter & Interp, std::unique_ptr< CompilerInstance > Instance, IncrementalParser & HostParser, llvm::LLVMContext & LLVMCtx, llvm::IntrusiveRefCntPtr< llvm::vfs::InMemoryFileSystem > VFS, llvm::Error & Err)
Definition at line 25 of file DeviceOffload.cpp.
~IncrementalCUDADeviceParser()
clang::IncrementalCUDADeviceParser::~IncrementalCUDADeviceParser ()
Definition at line 174 of file DeviceOffload.cpp.
Member Function Documentation
GenerateFatbinary()
llvm::Error clang::IncrementalCUDADeviceParser::GenerateFatbinary ()
Definition at line 107 of file DeviceOffload.cpp.
References FatbinContent, PTXCode, and SMVersion.
Referenced by Parse().
GeneratePTX()
llvm::Expected< llvm::StringRef > clang::IncrementalCUDADeviceParser::GeneratePTX ()
Definition at line 71 of file DeviceOffload.cpp.
References clang::IncrementalParser::getCI(), clang::IncrementalParser::PTUs, and PTXCode.
Referenced by Parse().
Parse()
llvm::Expected< PartialTranslationUnit & > clang::IncrementalCUDADeviceParser::Parse (llvm::StringRef Input) override virtual
Parses incremental input by creating an in-memory file.
Returns
a PartialTranslationUnit which holds information about the TranslationUnitDecl and llvm::Module corresponding to the input.
Reimplemented from clang::IncrementalParser.
Definition at line 44 of file DeviceOffload.cpp.
References clang::CodeGenOptions::CudaGpuBinaryFileName, FatbinContent, GenerateFatbinary(), GeneratePTX(), clang::IncrementalParser::getCI(), clang::CompilerInstance::getCodeGenOpts(), HostParser, clang::IncrementalParser::Parse(), clang::IncrementalParser::PTUs, and VFS.
Member Data Documentation
FatbinContent
llvm::SmallVector<char, 1024> clang::IncrementalCUDADeviceParser::FatbinContent protected
Definition at line 45 of file DeviceOffload.h.
Referenced by GenerateFatbinary(), and Parse().
HostParser
IncrementalParser& clang::IncrementalCUDADeviceParser::HostParser protected
Definition at line 42 of file DeviceOffload.h.
Referenced by Parse().
PTXCode
llvm::SmallString<1024> clang::IncrementalCUDADeviceParser::PTXCode protected
Definition at line 44 of file DeviceOffload.h.
Referenced by GenerateFatbinary(), and GeneratePTX().
SMVersion
int clang::IncrementalCUDADeviceParser::SMVersion protected
Definition at line 43 of file DeviceOffload.h.
Referenced by GenerateFatbinary().
VFS
llvm::IntrusiveRefCntPtr<llvm::vfs::InMemoryFileSystem> clang::IncrementalCUDADeviceParser::VFS protected
Definition at line 46 of file DeviceOffload.h.
Referenced by Parse().
The documentation for this class was generated from the following files:
lib/Interpreter/DeviceOffload.h
lib/Interpreter/DeviceOffload.cpp