clang: clang::threadSafety::til::SFunction Class Reference
clang::threadSafety::til::SFunction Class Reference
A self-applicable function.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
SFunction (Variable *Vd, SExpr *B)
SFunction (const SFunction &F, Variable *Vd, SExpr *B)
Variable * variableDecl ()
const Variable * variableDecl () const
SExpr * body ()
const SExpr * body () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const SFunction *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const unsigned char Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
A self-applicable function.
A self-applicable function can be applied to itself. It's useful for implementing objects and late binding.
Definition at line 715 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
SFunction() [1/2]
clang::threadSafety::til::SFunction::SFunction (Variable * Vd, SExpr * B) inline
Definition at line 717 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::Variable::setKind(), and clang::threadSafety::til::Variable::VK_SFun.
SFunction() [2/2]
clang::threadSafety::til::SFunction::SFunction (const SFunction & F, Variable * Vd, SExpr * B) inline
Definition at line 724 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::Variable::setKind(), and clang::threadSafety::til::Variable::VK_SFun.
Member Function Documentation
body() [1/2]
SExpr* clang::threadSafety::til::SFunction::body () inline
Definition at line 736 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printSFunction().
body() [2/2]
const SExpr* clang::threadSafety::til::SFunction::body () const inline
Definition at line 737 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::SFunction::classof (const SExpr * E) inline static
Definition at line 731 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::SFunction::compare (const SFunction * E, C & Cmp) const inline
Definition at line 752 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::SFunction::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 740 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::Variable::traverse().
variableDecl() [1/2]
Variable* clang::threadSafety::til::SFunction::variableDecl () inline
Definition at line 733 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printSFunction().
variableDecl() [2/2]
const Variable* clang::threadSafety::til::SFunction::variableDecl () const inline
Definition at line 734 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h