clang: clang::SemaAVR Class Reference
clang::SemaAVR Class Reference
#include "clang/Sema/SemaAVR.h"
Public Member Functions
SemaAVR (Sema &S)
void handleInterruptAttr (Decl *D, const ParsedAttr &AL)
void handleSignalAttr (Decl *D, const ParsedAttr &AL)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 22 of file SemaAVR.h.
Constructor & Destructor Documentation
SemaAVR()
clang::SemaAVR::SemaAVR (Sema & S)
Definition at line 21 of file SemaAVR.cpp.
Member Function Documentation
handleInterruptAttr()
void clang::SemaAVR::handleInterruptAttr (Decl * D, const ParsedAttr & AL)
Definition at line 23 of file SemaAVR.cpp.
References clang::ParsedAttr::checkExactlyNumArgs(), D, clang::SemaBase::Diag(), clang::ExpectedFunction, clang::isFuncOrMethodForAttrSubject(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::SemaBase::SemaRef.
handleSignalAttr()
void clang::SemaAVR::handleSignalAttr (Decl * D, const ParsedAttr & AL)
Definition at line 36 of file SemaAVR.cpp.
References clang::ParsedAttr::checkExactlyNumArgs(), D, clang::SemaBase::Diag(), clang::ExpectedFunction, clang::isFuncOrMethodForAttrSubject(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and clang::SemaBase::SemaRef.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaAVR.h
lib/Sema/SemaAVR.cpp