clang: clang::CodeGen::RawAddress Class Reference
clang::CodeGen::RawAddress Class Reference
An abstract representation of an aligned address.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/Address.h"
Public Member Functions
RawAddress (llvm::Value *Pointer, llvm::Type *ElementType, CharUnits Alignment, KnownNonNull_t IsKnownNonNull=NotKnownNonNull)
RawAddress (Address Addr)
bool isValid () const
llvm::Value * getPointer () const
llvm::PointerType * getType () const
Return the type of the pointer value.
llvm::Type * getElementType () const
Return the type of the values stored in this address.
unsigned getAddressSpace () const
Return the address space that this address resides in.
llvm::StringRef getName () const
Return the IR name of the pointer value.
CharUnits getAlignment () const
Return the alignment of this pointer.
RawAddress withElementType (llvm::Type *ElemTy) const
Return address with different element type, but same pointer and alignment.
KnownNonNull_t isKnownNonNull () const
Static Public Member Functions
static RawAddress invalid ()
Protected Member Functions
RawAddress (std::nullptr_t)
Detailed Description
An abstract representation of an aligned address.
This is designed to be an IR-level abstraction, carrying just the information necessary to perform IR operations on an address like loads and stores. In particular, it doesn't carry C type information or allow the representation of things like bit-fields; clients working at that level should generally be using LValue. The pointer contained in this class is known to be unsigned.
Definition at line 41 of file Address.h.
Constructor & Destructor Documentation
RawAddress() [1/3]
clang::CodeGen::RawAddress::RawAddress (std::nullptr_t) inline protected
Definition at line 47 of file Address.h.
Referenced by invalid(), and withElementType().
RawAddress() [2/3]
clang::CodeGen::RawAddress::RawAddress (llvm::Value * Pointer, llvm::Type * ElementType, CharUnits Alignment, KnownNonNull_t IsKnownNonNull = NotKnownNonNull) inline
Definition at line 50 of file Address.h.
RawAddress() [3/3]
clang::CodeGen::RawAddress::RawAddress (Address Addr) inline
Definition at line 251 of file Address.h.
Member Function Documentation
getAddressSpace()
unsigned clang::CodeGen::RawAddress::getAddressSpace () const inline
Return the address space that this address resides in.
Definition at line 82 of file Address.h.
References getType().
getAlignment()
CharUnits clang::CodeGen::RawAddress::getAlignment () const inline
Return the alignment of this pointer.
Definition at line 92 of file Address.h.
References isValid().
Referenced by clang::CodeGen::ConstantAddress::castImpl(), CreateCoercedLoad(), CreateCoercedStore(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::EHCleanupScope::setActiveFlag(), withElementType(), and clang::CodeGen::ConstantAddress::withElementType().
getElementType()
llvm::Type* clang::CodeGen::RawAddress::getElementType () const inline
Return the type of the values stored in this address.
Definition at line 76 of file Address.h.
References isValid().
Referenced by clang::CodeGen::ConstantAddress::castImpl(), castToBase(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), and MaybeConvertMatrixAddress().
getName()
llvm::StringRef clang::CodeGen::RawAddress::getName () const inline
Return the IR name of the pointer value.
Definition at line 87 of file Address.h.
References getPointer().
getPointer()
llvm::Value* clang::CodeGen::RawAddress::getPointer () const inline
Definition at line 65 of file Address.h.
References isValid().
Referenced by clang::CodeGen::ConstantAddress::castImpl(), castToBase(), CreateCoercedLoad(), CreateCoercedStore(), destroyOptimisticNormalEntry(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::EmitAutoVarDecl(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCheckValue(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), emitListToGlobalReduceFunction(), clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CodeGenFunction::FinishFunction(), getName(), clang::CodeGen::ConstantAddress::getPointer(), getType(), clang::CodeGen::ConstantAddress::isaImpl(), clang::CodeGen::CodeGenFunction::setBlockContextParameter(), and withElementType().
getType()
llvm::PointerType* clang::CodeGen::RawAddress::getType () const inline
Return the type of the pointer value.
Definition at line 71 of file Address.h.
References getPointer().
Referenced by getAddressSpace().
invalid()
static RawAddress clang::CodeGen::RawAddress::invalid () inline static
Definition at line 60 of file Address.h.
References RawAddress().
Referenced by castToBase(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::emitBuiltinOSLogFormat(), clang::CodeGen::CodeGenFunction::EmitCall(), and clang::CodeGen::CodeGenFunction::pushCleanupAfterFullExpr().
isKnownNonNull()
KnownNonNull_t clang::CodeGen::RawAddress::isKnownNonNull () const inline
Definition at line 103 of file Address.h.
References isValid().
Referenced by withElementType().
isValid()
bool clang::CodeGen::RawAddress::isValid () const inline
Definition at line 61 of file Address.h.
Referenced by castToBase(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GenerateCXXGlobalInitFunc(), getAlignment(), getElementType(), getPointer(), isKnownNonNull(), and clang::CodeGen::CodeGenFunction::pushCleanupAfterFullExprWithActiveFlag().
withElementType()
RawAddress clang::CodeGen::RawAddress::withElementType (llvm::Type * ElemTy) const inline
Return address with different element type, but same pointer and alignment.
Definition at line 99 of file Address.h.
References getAlignment(), getPointer(), isKnownNonNull(), and RawAddress().
Referenced by MaybeConvertMatrixAddress().
The documentation for this class was generated from the following file:
lib/CodeGen/Address.h