clang: clang::concepts::NestedRequirement Class Reference
clang::concepts::NestedRequirement Class Reference
A requires-expression requirement which is satisfied when a general constraint expression is satisfied ('nested' requirements).
#include "clang/AST/ExprConcepts.h"
Public Member Functions
NestedRequirement (Expr *Constraint)
NestedRequirement (ASTContext &C, Expr *Constraint, const ConstraintSatisfaction &Satisfaction)
NestedRequirement (StringRef InvalidConstraintEntity, const ASTConstraintSatisfaction *Satisfaction)
NestedRequirement (ASTContext &C, StringRef InvalidConstraintEntity, const ConstraintSatisfaction &Satisfaction)
bool hasInvalidConstraint () const
StringRef getInvalidConstraintEntity ()
Expr * getConstraintExpr () const
const ASTConstraintSatisfaction & getConstraintSatisfaction () const
Public Member Functions inherited from clang::concepts::Requirement
Requirement (RequirementKind Kind, bool IsDependent, bool ContainsUnexpandedParameterPack, bool IsSatisfied=true)
RequirementKind getKind () const
bool isSatisfied () const
void setSatisfied (bool IsSatisfied)
void setDependent (bool IsDependent)
bool isDependent () const
void setContainsUnexpandedParameterPack (bool Contains)
bool containsUnexpandedParameterPack () const
Static Public Member Functions
static bool classof (const Requirement *R)
Public Attributes
friend ASTStmtReader
friend ASTStmtWriter
Additional Inherited Members
Public Types inherited from clang::concepts::Requirement
enum RequirementKind { RK_Type , RK_Simple , RK_Compound , RK_Nested }
Detailed Description
A requires-expression requirement which is satisfied when a general constraint expression is satisfied ('nested' requirements).
Definition at line 429 of file ExprConcepts.h.
Constructor & Destructor Documentation
NestedRequirement() [1/4]
clang::concepts::NestedRequirement::NestedRequirement (Expr * Constraint) inline
Definition at line 439 of file ExprConcepts.h.
References clang::Expr::isInstantiationDependent().
NestedRequirement() [2/4]
clang::concepts::NestedRequirement::NestedRequirement (ASTContext & C, Expr * Constraint, const ConstraintSatisfaction & Satisfaction) inline
Definition at line 448 of file ExprConcepts.h.
References clang::Create.
NestedRequirement() [3/4]
clang::concepts::NestedRequirement::NestedRequirement (StringRef InvalidConstraintEntity, const ASTConstraintSatisfaction * Satisfaction) inline
Definition at line 456 of file ExprConcepts.h.
NestedRequirement() [4/4]
clang::concepts::NestedRequirement::NestedRequirement (ASTContext & C, StringRef InvalidConstraintEntity, const ConstraintSatisfaction & Satisfaction) inline
Definition at line 465 of file ExprConcepts.h.
References clang::Create.
Member Function Documentation
classof()
static bool clang::concepts::NestedRequirement::classof (const Requirement * R) inline static
Definition at line 488 of file ExprConcepts.h.
References clang::concepts::Requirement::getKind(), and clang::concepts::Requirement::RK_Nested.
getConstraintExpr()
Expr* clang::concepts::NestedRequirement::getConstraintExpr () const inline
Definition at line 477 of file ExprConcepts.h.
References hasInvalidConstraint().
Referenced by clang::TreeTransform< Derived >::TransformNestedRequirement(), and clang::RecursiveASTVisitor< Derived >::TraverseConceptNestedRequirement().
getConstraintSatisfaction()
const ASTConstraintSatisfaction& clang::concepts::NestedRequirement::getConstraintSatisfaction () const inline
Definition at line 484 of file ExprConcepts.h.
Referenced by clang::TreeTransform< Derived >::TransformNestedRequirement().
getInvalidConstraintEntity()
StringRef clang::concepts::NestedRequirement::getInvalidConstraintEntity () inline
Definition at line 472 of file ExprConcepts.h.
References hasInvalidConstraint().
Referenced by clang::TreeTransform< Derived >::TransformNestedRequirement().
hasInvalidConstraint()
bool clang::concepts::NestedRequirement::hasInvalidConstraint () const inline
Definition at line 470 of file ExprConcepts.h.
Referenced by getConstraintExpr(), getInvalidConstraintEntity(), clang::TreeTransform< Derived >::TransformNestedRequirement(), and clang::RecursiveASTVisitor< Derived >::TraverseConceptNestedRequirement().
Member Data Documentation
ASTStmtReader
friend clang::concepts::NestedRequirement::ASTStmtReader
Definition at line 436 of file ExprConcepts.h.
ASTStmtWriter
friend clang::concepts::NestedRequirement::ASTStmtWriter
Definition at line 437 of file ExprConcepts.h.
The documentation for this class was generated from the following file:
include/clang/AST/ExprConcepts.h