clang: clang::InMemoryModuleCache Class Reference
clang::InMemoryModuleCache Class Reference
In-memory cache for modules.
#include "clang/Serialization/InMemoryModuleCache.h"
Public Types
enum State { Unknown , Tentative , ToBuild , Final }
There are four states for a PCM.
Public Member Functions
State getPCMState (llvm::StringRef Filename) const
Get the state of the PCM.
llvm::MemoryBuffer & addPCM (llvm::StringRef Filename, std::unique_ptr< llvm::MemoryBuffer > Buffer)
Store the PCM under the Filename.
llvm::MemoryBuffer & addBuiltPCM (llvm::StringRef Filename, std::unique_ptr< llvm::MemoryBuffer > Buffer)
Store a just-built PCM under the Filename.
bool tryToDropPCM (llvm::StringRef Filename)
Try to remove a buffer from the cache.
void finalizePCM (llvm::StringRef Filename)
Mark a PCM as final.
llvm::MemoryBuffer * lookupPCM (llvm::StringRef Filename) const
Get a pointer to the pCM if it exists; else nullptr.
bool isPCMFinal (llvm::StringRef Filename) const
Check whether the PCM is final and has been shown to work.
bool shouldBuildPCM (llvm::StringRef Filename) const
Check whether the PCM is waiting to be built.
Detailed Description
In-memory cache for modules.
This is a cache for modules for use across a compilation, sharing state between the CompilerInstances in an implicit modules build. It must be shared by each CompilerInstance, ASTReader, ASTWriter, and ModuleManager that are coordinating.
Critically, it ensures that a single process has a consistent view of each PCM. This is used by CompilerInstance when building PCMs to ensure that each ModuleManager sees the same files.
Definition at line 29 of file InMemoryModuleCache.h.
Member Enumeration Documentation
State
enum clang::InMemoryModuleCache::State
There are four states for a PCM.
It must monotonically increase.
Unknown: the PCM has neither been read from disk nor built.
Tentative: the PCM has been read from disk but not yet imported or built. It might work.
ToBuild: the PCM read from disk did not work but a new one has not been built yet.
Final: indicating that the current PCM was either built in this process or has been successfully imported.
Enumerator
Unknown
Tentative
ToBuild
Final
Definition at line 56 of file InMemoryModuleCache.h.
Member Function Documentation
addBuiltPCM()
llvm::MemoryBuffer & InMemoryModuleCache::addBuiltPCM (llvm::StringRef Filename, std::unique_ptr< llvm::MemoryBuffer > Buffer)
Store a just-built PCM under the Filename.
Precondition
state is Unknown or ToBuild.
state is not Tentative.
Returns
a reference to the buffer as a convenience.
Definition at line 33 of file InMemoryModuleCache.cpp.
References Filename.
Referenced by clang::ASTWriter::WriteAST().
addPCM()
llvm::MemoryBuffer & InMemoryModuleCache::addPCM (llvm::StringRef Filename, std::unique_ptr< llvm::MemoryBuffer > Buffer)
Store the PCM under the Filename.
Precondition
state is Unknown
Postcondition
state is Tentative
Returns
a reference to the buffer as a convenience.
Definition at line 25 of file InMemoryModuleCache.cpp.
References Filename.
finalizePCM()
void InMemoryModuleCache::finalizePCM (llvm::StringRef Filename)
Mark a PCM as final.
Precondition
state is Tentative or Final.
Postcondition
state is Final.
Definition at line 73 of file InMemoryModuleCache.cpp.
References Filename.
getPCMState()
InMemoryModuleCache::State InMemoryModuleCache::getPCMState (llvm::StringRef Filename) const
Get the state of the PCM.
Definition at line 15 of file InMemoryModuleCache.cpp.
References Filename, Final, Tentative, ToBuild, and Unknown.
Referenced by isPCMFinal(), and shouldBuildPCM().
isPCMFinal()
bool InMemoryModuleCache::isPCMFinal (llvm::StringRef Filename) const
Check whether the PCM is final and has been shown to work.
Returns
true iff state is Final.
Definition at line 51 of file InMemoryModuleCache.cpp.
References Filename, Final, and getPCMState().
lookupPCM()
llvm::MemoryBuffer * InMemoryModuleCache::lookupPCM (llvm::StringRef Filename) const
Get a pointer to the pCM if it exists; else nullptr.
Definition at line 44 of file InMemoryModuleCache.cpp.
References Filename.
Referenced by clang::ASTReader::readASTFileControlBlock().
shouldBuildPCM()
bool InMemoryModuleCache::shouldBuildPCM (llvm::StringRef Filename) const
Check whether the PCM is waiting to be built.
Returns
true iff state is ToBuild.
Definition at line 55 of file InMemoryModuleCache.cpp.
References Filename, getPCMState(), and ToBuild.
tryToDropPCM()
bool InMemoryModuleCache::tryToDropPCM (llvm::StringRef Filename)
Try to remove a buffer from the cache.
No effect if state is Final.
Precondition
state is Tentative/Final.
Postcondition
Tentative => ToBuild or Final => Final.
Returns
false on success, i.e. if Tentative => ToBuild.
Definition at line 59 of file InMemoryModuleCache.cpp.
References Filename.
The documentation for this class was generated from the following files:
include/clang/Serialization/InMemoryModuleCache.h
lib/Serialization/InMemoryModuleCache.cpp