clang: clang::SemaBase Class Reference
clang::SemaBase Class Reference
#include "clang/Sema/SemaBase.h"
Classes
class DeviceDeferredDiagnostic
class ImmediateDiagBuilder
Helper class that creates diagnostics with optional template instantiation stacks.
class SemaDiagnosticBuilder
A generic diagnostic builder for errors which may or may not be deferred.
Public Types
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Member Functions
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Public Attributes
Sema & SemaRef
Detailed Description
Definition at line 36 of file SemaBase.h.
Member Enumeration Documentation
DeviceDiagnosticReason
enum clang::SemaBase::DeviceDiagnosticReason strong
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
This permits multiple offload systems to coexist in the same translation unit.
Enumerator
None
Diagnostic doesn't apply to anything.
Included for completeness, but should make this a no-op.
OmpDevice
OpenMP specific diagnostic.
OmpHost
OmpAll
CudaDevice
CUDA specific diagnostics.
CudaHost
CudaAll
Sycl
SYCL specific diagnostic.
Esimd
ESIMD specific diagnostic.
All
A flag representing 'all'.
This can be used to avoid the check all-together and make this behave as it did before the DiagnosticReason was added (that is, unconditionally emit). Note: This needs to be updated if any flags above are added.
Definition at line 99 of file SemaBase.h.
Constructor & Destructor Documentation
SemaBase()
clang::SemaBase::SemaBase (Sema & S)
Definition at line 7 of file SemaBase.cpp.
Member Function Documentation
addFDToReachableFromSyclDevice()
void clang::SemaBase::addFDToReachableFromSyclDevice (const FunctionDecl * Callee, const FunctionDecl * Caller) inline
Definition at line 133 of file SemaBase.h.
Diag() [1/2]
Sema::SemaDiagnosticBuilder clang::SemaBase::Diag (SourceLocation Loc, const PartialDiagnostic & PD, bool DeferHint = false)
Emit a partial diagnostic.
Definition at line 86 of file SemaBase.cpp.
References Diag(), clang::PartialDiagnostic::getDiagID(), and Loc.
Diag() [2/2]
Sema::SemaDiagnosticBuilder clang::SemaBase::Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint = false)
Emit a diagnostic.
Definition at line 61 of file SemaBase.cpp.
References All, clang::Sema::CUDA(), clang::Sema::DeferDiags, clang::SemaCUDA::DiagIfDeviceCode(), clang::SemaCUDA::DiagIfHostCode(), clang::Sema::getCurFunctionDecl(), clang::DiagnosticsEngine::getDiagnosticIDs(), getDiagnostics(), getLangOpts(), clang::DiagnosticIDs::isDeferrable(), clang::SemaBase::SemaDiagnosticBuilder::isImmediate(), clang::Sema::IsLastErrorImmediate, clang::SemaBase::SemaDiagnosticBuilder::K_Immediate, Loc, and SemaRef.
Referenced by clang::SemaOpenACC::ActOnAssociatedStmt(), clang::Sema::ActOnBaseSpecifier(), clang::SemaOpenACC::ActOnConstruct(), clang::Sema::ActOnConversionDeclarator(), clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), clang::Sema::ActOnCXXNew(), clang::Sema::ActOnEffectExpression(), clang::Sema::ActOnEndOfTranslationUnit(), clang::SemaHLSL::ActOnFinishBuffer(), clang::Sema::ActOnMemInitializers(), clang::SemaObjC::ActOnObjCAtSynchronizedOperand(), clang::SemaObjC::ActOnObjCAtThrowStmt(), clang::SemaOpenMP::ActOnOpenMPAffinityClause(), clang::SemaOpenMP::ActOnOpenMPAlignedClause(), clang::SemaOpenMP::ActOnOpenMPAssumesDirective(), clang::SemaOpenMP::ActOnOpenMPAtClause(), clang::SemaOpenMP::ActOnOpenMPAtomicDefaultMemOrderClause(), clang::SemaOpenMP::ActOnOpenMPBindClause(), clang::SemaOpenMP::ActOnOpenMPCall(), clang::SemaOpenMP::ActOnOpenMPCancelDirective(), clang::SemaOpenMP::ActOnOpenMPCancellationPointDirective(), clang::SemaOpenMP::ActOnOpenMPCopyinClause(), clang::SemaOpenMP::ActOnOpenMPCopyprivateClause(), clang::SemaOpenMP::ActOnOpenMPCriticalDirective(), clang::SemaOpenMP::ActOnOpenMPDeclareMapperType(), clang::SemaOpenMP::ActOnOpenMPDeclareReductionType(), clang::SemaOpenMP::ActOnOpenMPDeclareSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDeclareTargetName(), clang::SemaOpenMP::ActOnOpenMPDeclareVariantDirective(), clang::SemaOpenMP::ActOnOpenMPDefaultClause(), clang::SemaOpenMP::ActOnOpenMPDefaultmapClause(), clang::SemaOpenMP::ActOnOpenMPDependClause(), clang::SemaOpenMP::ActOnOpenMPDepobjClause(), clang::SemaOpenMP::ActOnOpenMPDepobjDirective(), clang::SemaOpenMP::ActOnOpenMPDestroyClause(), clang::SemaOpenMP::ActOnOpenMPDetachClause(), clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPDistScheduleClause(), clang::SemaOpenMP::ActOnOpenMPDoacrossClause(), clang::SemaOpenMP::ActOnOpenMPErrorDirective(), clang::SemaOpenMP::ActOnOpenMPExclusiveClause(), clang::SemaOpenMP::ActOnOpenMPExecutableDirective(), clang::SemaOpenMP::ActOnOpenMPFailClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPFlushDirective(), clang::SemaOpenMP::ActOnOpenMPFromClause(), clang::SemaOpenMP::ActOnOpenMPGrainsizeClause(), clang::SemaOpenMP::ActOnOpenMPHasDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPInclusiveClause(), clang::SemaOpenMP::ActOnOpenMPInitClause(), clang::SemaOpenMP::ActOnOpenMPInteropDirective(), clang::SemaOpenMP::ActOnOpenMPIsDevicePtrClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPLoopInitialization(), clang::SemaOpenMP::ActOnOpenMPMapClause(), clang::SemaOpenMP::ActOnOpenMPMessageClause(), clang::SemaOpenMP::ActOnOpenMPNontemporalClause(), clang::SemaOpenMP::ActOnOpenMPNumTasksClause(), clang::SemaOpenMP::ActOnOpenMPOrderClause(), clang::SemaOpenMP::ActOnOpenMPOrderedDirective(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPProcBindClause(), clang::SemaOpenMP::ActOnOpenMPReductionClause(), clang::SemaOpenMP::ActOnOpenMPRequiresDirective(), clang::SemaOpenMP::ActOnOpenMPScanDirective(), clang::SemaOpenMP::ActOnOpenMPScheduleClause(), clang::SemaOpenMP::ActOnOpenMPSeverityClause(), clang::SemaOpenMP::ActOnOpenMPSharedClause(), clang::SemaOpenMP::ActOnOpenMPSingleDirective(), clang::SemaOpenMP::ActOnOpenMPTargetDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetEnterDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetExitDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPTargetUpdateDirective(), clang::SemaOpenMP::ActOnOpenMPTaskwaitDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPToClause(), clang::SemaOpenMP::ActOnOpenMPUpdateClause(), clang::SemaOpenMP::ActOnOpenMPUseDevicePtrClause(), clang::Sema::ActOnPackExpansion(), clang::Sema::ActOnPackIndexingType(), clang::Sema::ActOnParamDefaultArgument(), clang::Sema::ActOnPragmaAttributeAttribute(), clang::Sema::ActOnPragmaAttributePop(), clang::Sema::ActOnPragmaClangSection(), clang::Sema::ActOnPragmaFEnvAccess(), clang::Sema::ActOnPragmaFloatControl(), clang::Sema::ActOnPragmaFPEvalMethod(), clang::Sema::ActOnPragmaFPValueChangingOption(), clang::Sema::ActOnPragmaMSAllocText(), clang::Sema::ActOnPragmaMSFunction(), clang::Sema::ActOnPragmaMSOptimize(), clang::Sema::ActOnPragmaMSStrictGuardStackCheck(), clang::Sema::ActOnPragmaMSVtorDisp(), clang::Sema::ActOnPragmaOptionsAlign(), clang::Sema::ActOnPragmaPack(), clang::Sema::ActOnPragmaVisibility(), clang::Sema::ActOnPureSpecifier(), clang::Sema::ActOnStartNamespaceDef(), clang::SemaOpenMP::ActOnStartOpenMPDeclareTargetContext(), clang::Sema::ActOnStartRequiresExpr(), clang::Sema::ActOnSuperScopeSpecifier(), clang::SemaHLSL::ActOnTopLevelFunction(), clang::SemaOpenACC::ActOnVar(), clang::Sema::adjustMemberFunctionCC(), clang::SemaObjC::AtomicPropertySetterGetterRules(), clang::Sema::AttachBaseSpecifiers(), clang::Sema::BuildAddressSpaceAttr(), clang::Sema::BuildArrayType(), clang::Sema::BuildAtomicType(), clang::Sema::BuildBaseInitializer(), clang::Sema::BuildBitIntType(), clang::Sema::BuildBlockPointerType(), clang::Sema::BuildCXXNamedCast(), clang::Sema::BuildCXXNoexceptExpr(), clang::Sema::BuildCXXTypeConstructExpr(), clang::Sema::BuildDecltypeType(), clang::Sema::BuildDelegatingInitializer(), clang::Sema::BuildEmptyCXXFoldExpr(), clang::Sema::BuildExtVectorType(), clang::Sema::BuildFunctionType(), BuildImplicitMemberInitializer(), buildLambdaCaptureFixit(), buildLambdaThisCaptureFixit(), clang::Sema::BuildMatrixType(), clang::Sema::BuildMemberPointerType(), BuildNonArrayForRange(), clang::Sema::BuildPointerType(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildQualifiedType(), clang::Sema::BuildReferenceType(), clang::Sema::BuildStaticAssertDeclaration(), clang::Sema::BuildTypeofExprType(), clang::SemaSYCL::BuildUniqueStableIdExpr(), clang::Sema::BuildVectorType(), clang::SemaARM::BuiltinARMSpecialReg(), clang::Sema::BuiltinChangeSignedness(), clang::Sema::BuiltinEnumUnderlyingType(), clang::SemaPPC::BuiltinVSX(), clang::SemaWasm::BuiltinWasmTableCopy(), clang::SemaWasm::BuiltinWasmTableFill(), clang::SemaWasm::BuiltinWasmTableGrow(), clang::SemaPPC::checkAIXMemberAlignment(), clang::Sema::CheckAllocatedType(), clang::SemaCUDA::checkAllowedInitializer(), clang::Sema::CheckAltivecInitFromScalar(), clang::SemaAMDGPU::CheckAMDGCNBuiltinFunctionCall(), clang::Sema::checkArrayElementAlignment(), clang::Sema::CheckBaseSpecifier(), clang::SemaOpenCL::checkBuiltinCommitRWPipe(), clang::SemaX86::CheckBuiltinFunctionCall(), clang::SemaX86::CheckBuiltinGatherScatterScale(), clang::SemaOpenCL::checkBuiltinKernelWorkGroupSize(), clang::SemaOpenCL::checkBuiltinNDRangeAndBlock(), clang::SemaOpenCL::checkBuiltinPipePackets(), clang::SemaOpenCL::checkBuiltinReserveRWPipe(), clang::SemaX86::CheckBuiltinRoundingOrSAE(), clang::SemaOpenCL::checkBuiltinRWPipe(), clang::SemaX86::CheckBuiltinTileDuplicate(), clang::SemaOpenCL::checkBuiltinToAddr(), CheckC23ConstexprInitStringLiteral(), CheckC23ConstexprVarType(), checkCancelRegion(), clang::Sema::checkClassLevelDLLAttribute(), clang::Sema::CheckComparisonCategoryType(), clang::Sema::CheckCompatibleReinterpretCast(), clang::Sema::CheckCompleteDecompositionDeclaration(), clang::Sema::CheckConditionVariable(), clang::SemaObjC::CheckConflictingOverridingMethod(), CheckConstexprCtorInitializer(), CheckConstexprDeclStmt(), CheckConstexprDestructorSubobjects(), CheckConstexprFunctionBody(), clang::Sema::CheckConstexprFunctionDefinition(), CheckConstexprMissingReturn(), clang::Sema::CheckConstructor(), clang::Sema::CheckConstructorDeclarator(), clang::Sema::CheckConversionDeclarator(), clang::SemaObjC::CheckConversionToObjCLiteral(), clang::Sema::CheckCXXDefaultArguments(), clang::Sema::CheckCXXThisCapture(), clang::Sema::CheckCXXThisType(), checkDeclInTargetContext(), clang::SemaOpenMP::checkDeclIsAllowedInOpenMPTarget(), clang::Sema::CheckDeductionGuideDeclarator(), clang::Sema::CheckDestructor(), clang::Sema::CheckDestructorDeclarator(), clang::SemaHLSL::CheckEntryPoint(), clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::CheckExceptionSpecSubset(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckExplicitObjectOverride(), clang::sema::checkExprLifetimeImpl(), clang::Sema::CheckExtraCXXDefaultArguments(), CheckForReference(), clang::SemaObjC::CheckForwardProtocolDeclarationForCircularDependency(), clang::Sema::checkFunctionOrMethodParameterIndex(), clang::Sema::CheckFunctionReturnType(), CheckIdentityFieldAssignment(), clang::Sema::CheckIfOverriddenFunctionIsMarkedFinal(), clang::Sema::checkIllFormedTrivialABIStruct(), clang::Sema::CheckImmediateEscalatingFunctionDefinition(), clang::Sema::checkIncorrectVTablePointerAuthenticationAttribute(), clang::Sema::CheckInheritingConstructorUsingDecl(), clang::Sema::CheckLiteralOperatorDeclaration(), checkLiteralOperatorTemplateParameterList(), checkMapClauseExpressionBase(), checkMapConflicts(), checkMappableExpressionList(), clang::SemaMIPS::CheckMipsBuiltinCpu(), clang::SemaARM::CheckNeonBuiltinFunctionCall(), clang::SemaObjC::checkNSReturnsRetainedReturnType(), clang::SemaObjC::CheckObjCCircularContainer(), clang::SemaObjC::CheckObjCDeclScope(), clang::SemaObjC::CheckObjCMethodDirectOverrides(), checkObjCMethodX86VectorTypes(), clang::SemaObjC::CheckObjCPropertyAttributes(), clang::SemaObjC::CheckObjCString(), clang::SemaOpenMP::CheckOMPRequiresDecl(), clang::SemaOpenMP::CheckOpenMPLinearDecl(), clang::SemaOpenMP::CheckOpenMPLinearModifier(), checkOpenMPLoop(), CheckOperatorDeleteDeclaration(), CheckOperatorNewDeclaration(), CheckOperatorNewDeleteDeclarationScope(), CheckOperatorNewDeleteTypes(), clang::Sema::CheckOverloadedOperatorDeclaration(), clang::Sema::CheckOverrideControl(), clang::Sema::CheckOverridingFunctionAttributes(), clang::Sema::CheckOverridingFunctionReturnType(), clang::Sema::CheckPackExpansion(), clang::Sema::CheckPointerToMemberOperands(), clang::Sema::CheckPureMethod(), clang::Sema::CheckQualifiedFunctionForTypeId(), clang::SemaOpenACC::CheckReductionVar(), clang::Sema::CheckSizelessVectorConditionalTypes(), clang::SemaARM::CheckSMEBuiltinFunctionCall(), clang::Sema::CheckSpecifiedExceptionType(), CheckStmtInlineAttr(), clang::SemaOpenCL::checkSubgroupExt(), clang::SemaObjC::CheckSubscriptingKind(), clang::SemaSYCL::CheckSYCLKernelCall(), clang::SemaSystemZ::CheckSystemZBuiltinFunctionCall(), clang::SemaCUDA::checkTargetOverload(), clang::Sema::CheckTypeTraitArity(), clang::Sema::checkUInt32Argument(), clang::Sema::CheckUsingDeclQualifier(), clang::Sema::CheckUsingDeclRedeclaration(), clang::Sema::CheckUsingShadowDecl(), clang::SemaOpenACC::CheckVarIsPointerType(), clang::Sema::CheckVectorConditionalTypes(), clang::Sema::CheckVirtualDtorCall(), clang::Sema::ConstantFoldAttrArgs(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CXXCheckConditionalOperands(), clang::Sema::DeduceAutoType(), clang::Sema::DeduceReturnType(), clang::Sema::DeduceTemplateSpecializationFromInitializer(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitLambdaToBlockPointerConversion(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::DefineUsedVTables(), Diag(), clang::Sema::DiagnoseAbsenceOfOverrideControl(), clang::Sema::DiagnoseAbstractType(), clang::SemaHLSL::DiagnoseAttrStageMismatch(), clang::Sema::DiagnoseAutoDeductionFailure(), DiagnoseBaseOrMemInitializerOrder(), clang::SemaObjC::DiagnoseClassExtensionDupMethods(), clang::SemaObjC::DiagnoseCStringFormatDirectiveInCFAPI(), clang::SemaObjC::DiagnoseDuplicateIvars(), clang::Sema::diagnoseEquivalentInternalLinkageDeclarations(), DiagnoseForRangeConstVariableCopies(), DiagnoseForRangeReferenceVariableCopies(), clang::Sema::diagnoseFunctionEffectConversion(), clang::Sema::DiagnoseHiddenVirtualMethods(), clang::Sema::DiagnoseImmediateEscalatingReason(), diagnoseInstanceReference(), DiagnoseMismatchedNewDelete(), clang::SemaObjC::DiagnoseMissingDesignatedInitOverrides(), clang::Sema::diagnoseMissingImport(), clang::SemaObjC::DiagnoseMultipleMethodInGlobalPool(), clang::Sema::DiagnoseMultipleUserDefinedConversion(), clang::Sema::DiagnoseNonDefaultPragmaAlignPack(), clang::Sema::diagnoseNullableToNonnullConversion(), clang::SemaObjC::diagnoseNullResettableSynthesizedSetters(), diagnoseOpenCLTypes(), clang::SemaObjC::DiagnoseOwningPropertyGetterSynthesis(), DiagnoseQualifiedMemberReference(), clang::Sema::DiagnoseStaticAssertDetails(), DiagnoseTwoPhaseLookup(), clang::SemaObjC::DiagnoseTypeArgsAndProtocols(), clang::Sema::diagnoseTypo(), clang::Sema::diagnoseUnavailableAlignedAllocation(), clang::SemaOpenMP::DiagnoseUnterminatedOpenMPDeclareTarget(), clang::Sema::DiagnoseUnterminatedPragmaAlignPack(), clang::Sema::DiagnoseUnterminatedPragmaAttribute(), clang::Sema::diagnoseZeroToNullptrConversion(), clang::Sema::DiagPlaceholderVariableDefinition(), clang::Sema::emitAndClearUnusedLocalTypedefWarnings(), clang::Sema::EmitCurrentDiagnostic(), clang::SemaOpenMP::EndOpenMPDSABlock(), EvaluateAndDiagnoseImmediateInvocation(), clang::Sema::EvaluateConvertedConstantExpression(), clang::Sema::EvaluateStaticAssertMessageAsString(), clang::SemaOpenMP::finalizeOpenMPDelayedAnalysis(), clang::SemaSYCL::finalizeSYCLDelayedAnalysis(), clang::Sema::FinalizeVarWithDestructor(), clang::Sema::FindAllocationFunctions(), clang::Sema::FindInstantiatedDecl(), clang::SemaObjC::FindProtocolDeclaration(), FinishForRangeVarDecl(), flushDiagnostics(), GetDeclSpecTypeForDeclarator(), getFunctionStorageClass(), clang::Sema::getMostSpecialized(), clang::SemaOpenCL::handleAccessAttr(), clang::SemaSwift::handleAsyncAttr(), clang::SemaSwift::handleAsyncError(), clang::SemaObjC::handleBlocksAttr(), clang::SemaSwift::handleBridge(), clang::SemaObjC::handleBridgeAttr(), clang::SemaObjC::handleBridgeMutableAttr(), clang::SemaObjC::handleBridgeRelatedAttr(), clang::SemaARM::handleCmseNSEntryAttr(), clang::SemaObjC::handleDesignatedInitializer(), clang::SemaObjC::handleDirectAttr(), clang::SemaObjC::handleDirectMembersAttr(), clang::SemaObjC::handleExternallyRetainedAttr(), clang::SemaX86::handleForceAlignArgPointerAttr(), clang::SemaObjC::handleIndependentClass(), clang::SemaARM::handleInterruptAttr(), clang::SemaAVR::handleInterruptAttr(), clang::SemaM68k::handleInterruptAttr(), clang::SemaMIPS::handleInterruptAttr(), clang::SemaMSP430::handleInterruptAttr(), clang::SemaSYCL::handleKernelAttr(), clang::SemaObjC::handleMethodFamilyAttr(), clang::SemaARM::handleNewAttr(), clang::SemaSwift::handleNewType(), clang::SemaOpenCL::handleNoSVMAttr(), clang::SemaObjC::handleNSErrorDomain(), clang::SemaObjC::handleNSObject(), clang::SemaHLSL::handleNumThreadsAttr(), clang::SemaObjC::handleOwnershipAttr(), clang::SemaHLSL::handlePackOffsetAttr(), clang::SemaObjC::handlePreciseLifetimeAttr(), clang::SemaObjC::handleRequiresSuperAttr(), clang::SemaHLSL::handleResourceBindingAttr(), clang::SemaHLSL::handleResourceClassAttr(), clang::SemaObjC::handleReturnsInnerPointerAttr(), clang::SemaHLSL::handleShaderAttr(), clang::SemaAVR::handleSignalAttr(), clang::SemaObjC::handleSuppresProtocolAttr(), clang::SemaHLSL::handleSV_DispatchThreadIDAttr(), clang::SemaWasm::handleWebAssemblyImportModuleAttr(), clang::SemaWasm::handleWebAssemblyImportNameAttr(), clang::SemaObjC::handleXReturnsXRetainedAttr(), clang::Sema::ImpCastExprToType(), clang::SemaCUDA::inferTargetForImplicitSpecialMember(), clang::TemplateDeclInstantiator::InstantiateClassTemplatePartialSpecialization(), clang::Sema::InstantiateExceptionSpec(), clang::Sema::InstantiateFunctionDefinition(), clang::Sema::InstantiateInClassInitializer(), clang::Sema::InstantiateVariableDefinition(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), isNonNegativeIntegerValue(), IsOverloadOrOverrideImpl(), isValidInteropVariable(), clang::Sema::lookupCoroutineTraits(), clang::SemaOpenMP::lookupOpenMPDeclareTargetName(), clang::SemaCUDA::maybeAddHostDeviceAttrs(), clang::Sema::MaybeEmitAmbiguousAtomicConstraintsDiagnostic(), clang::SemaWasm::mergeImportModuleAttr(), clang::SemaWasm::mergeImportNameAttr(), clang::SemaHLSL::mergeNumThreadsAttr(), clang::SemaHLSL::mergeParamModifierAttr(), clang::SemaHLSL::mergeShaderAttr(), clang::Sema::NoteHiddenVirtualMethods(), clang::Sema::NoteOverloadCandidate(), clang::SemaARM::ParseSVEImmChecks(), clang::Sema::PerformContextuallyConvertToBool(), clang::Sema::PerformImplicitConversion(), clang::Sema::PopPragmaVisibility(), clang::Sema::propagateDLLAttrToBaseClassTemplate(), clang::TreeTransform< Derived >::RebuildCXXForRangeStmt(), clang::TreeTransform< Derived >::RebuildDependentNameType(), clang::TreeTransform< Derived >::RebuildQualifiedType(), clang::Sema::RequireCompleteEnumDecl(), clang::Sema::RequireLiteralType(), clang::Sema::ResolveAndFixSingleFunctionTemplateSpecialization(), clang::Sema::ResolveExceptionSpec(), clang::Sema::ResolveSingleFunctionTemplateSpecialization(), clang::Sema::SetCtorInitializers(), clang::Sema::SetDeclDefaulted(), clang::Sema::SetDeclDeleted(), clang::Sema::ShouldDeleteSpecialMember(), clang::Sema::SpecialMemberIsTrivial(), clang::Sema::SubstDefaultArgument(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformAttributedType(), clang::TreeTransform< Derived >::TransformNestedNameSpecifierLoc(), clang::Sema::tryToRecoverWithCall(), clang::Sema::UnifySection(), DiagDeviceFunction::VisitCallExpr(), DiagDeviceFunction::VisitCXXDynamicCastExpr(), DiagDeviceFunction::VisitCXXTypeidExpr(), clang::SemaObjC::WarnConflictingTypedMethods(), and clang::Sema::warnStackExhausted().
getASTContext()
ASTContext & clang::SemaBase::getASTContext () const
Definition at line 9 of file SemaBase.cpp.
References clang::Sema::Context, and SemaRef.
Referenced by clang::SemaOpenACC::ActOnEndStmtDirective(), clang::SemaOpenMP::ActOnFinishedFunctionDefinitionInOpenMPDeclareVariantScope(), clang::SemaOpenMP::ActOnOpenMPAcqRelClause(), clang::SemaOpenMP::ActOnOpenMPAcquireClause(), clang::SemaOpenMP::ActOnOpenMPAffinityClause(), clang::SemaOpenMP::ActOnOpenMPAlignClause(), clang::SemaOpenMP::ActOnOpenMPAlignedClause(), clang::SemaOpenMP::ActOnOpenMPAssumesDirective(), clang::SemaOpenMP::ActOnOpenMPAtClause(), clang::SemaOpenMP::ActOnOpenMPAtomicDefaultMemOrderClause(), clang::SemaOpenMP::ActOnOpenMPBarrierDirective(), clang::SemaOpenMP::ActOnOpenMPBindClause(), clang::SemaOpenMP::ActOnOpenMPCancelDirective(), clang::SemaOpenMP::ActOnOpenMPCancellationPointDirective(), clang::SemaOpenMP::ActOnOpenMPCanonicalLoop(), clang::SemaOpenMP::ActOnOpenMPCaptureClause(), clang::SemaOpenMP::ActOnOpenMPCollapseClause(), clang::SemaOpenMP::ActOnOpenMPCompareClause(), clang::SemaOpenMP::ActOnOpenMPCopyinClause(), clang::SemaOpenMP::ActOnOpenMPCopyprivateClause(), clang::SemaOpenMP::ActOnOpenMPCriticalDirective(), clang::SemaOpenMP::ActOnOpenMPDeclareSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDeclareTargetName(), clang::SemaOpenMP::ActOnOpenMPDeclareVariantDirective(), clang::SemaOpenMP::ActOnOpenMPDefaultClause(), clang::SemaOpenMP::ActOnOpenMPDefaultmapClause(), clang::SemaOpenMP::ActOnOpenMPDependClause(), clang::SemaOpenMP::ActOnOpenMPDepobjClause(), clang::SemaOpenMP::ActOnOpenMPDepobjDirective(), clang::SemaOpenMP::ActOnOpenMPDestroyClause(), clang::SemaOpenMP::ActOnOpenMPDetachClause(), clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistScheduleClause(), clang::SemaOpenMP::ActOnOpenMPDoacrossClause(), clang::SemaOpenMP::ActOnOpenMPDynamicAllocatorsClause(), clang::SemaOpenMP::ActOnOpenMPErrorDirective(), clang::SemaOpenMP::ActOnOpenMPExclusiveClause(), clang::SemaOpenMP::ActOnOpenMPFailClause(), clang::SemaOpenMP::ActOnOpenMPFilterClause(), clang::SemaOpenMP::ActOnOpenMPFinalClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPFlushClause(), clang::SemaOpenMP::ActOnOpenMPFlushDirective(), clang::SemaOpenMP::ActOnOpenMPForDirective(), clang::SemaOpenMP::ActOnOpenMPForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPFromClause(), clang::SemaOpenMP::ActOnOpenMPFullClause(), clang::SemaOpenMP::ActOnOpenMPGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPGrainsizeClause(), clang::SemaOpenMP::ActOnOpenMPHasDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPHintClause(), clang::SemaOpenMP::ActOnOpenMPIfClause(), clang::SemaOpenMP::ActOnOpenMPInclusiveClause(), clang::SemaOpenMP::ActOnOpenMPInitClause(), clang::SemaOpenMP::ActOnOpenMPInReductionClause(), clang::SemaOpenMP::ActOnOpenMPInteropDirective(), clang::SemaOpenMP::ActOnOpenMPIsDevicePtrClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPLoopInitialization(), clang::SemaOpenMP::ActOnOpenMPMapClause(), clang::SemaOpenMP::ActOnOpenMPMaskedDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMasterDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMergeableClause(), clang::SemaOpenMP::ActOnOpenMPMessageClause(), clang::SemaOpenMP::ActOnOpenMPNocontextClause(), clang::SemaOpenMP::ActOnOpenMPNogroupClause(), clang::SemaOpenMP::ActOnOpenMPNontemporalClause(), clang::SemaOpenMP::ActOnOpenMPNovariantsClause(), clang::SemaOpenMP::ActOnOpenMPNowaitClause(), clang::SemaOpenMP::ActOnOpenMPNumTasksClause(), clang::SemaOpenMP::ActOnOpenMPNumTeamsClause(), clang::SemaOpenMP::ActOnOpenMPNumThreadsClause(), clang::SemaOpenMP::ActOnOpenMPOrderClause(), clang::SemaOpenMP::ActOnOpenMPOrderedClause(), clang::SemaOpenMP::ActOnOpenMPOrderedDirective(), clang::SemaOpenMP::ActOnOpenMPParallelDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelSectionsDirective(), clang::SemaOpenMP::ActOnOpenMPPartialClause(), clang::SemaOpenMP::ActOnOpenMPPriorityClause(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPProcBindClause(), clang::SemaOpenMP::ActOnOpenMPReadClause(), clang::SemaOpenMP::ActOnOpenMPReductionClause(), clang::SemaOpenMP::ActOnOpenMPRelaxedClause(), clang::SemaOpenMP::ActOnOpenMPReleaseClause(), clang::SemaOpenMP::ActOnOpenMPReverseOffloadClause(), clang::SemaOpenMP::ActOnOpenMPSafelenClause(), clang::SemaOpenMP::ActOnOpenMPScheduleClause(), clang::SemaOpenMP::ActOnOpenMPScopeDirective(), clang::SemaOpenMP::ActOnOpenMPSectionDirective(), clang::SemaOpenMP::ActOnOpenMPSectionsDirective(), clang::SemaOpenMP::ActOnOpenMPSeqCstClause(), clang::SemaOpenMP::ActOnOpenMPSeverityClause(), clang::SemaOpenMP::ActOnOpenMPSharedClause(), clang::SemaOpenMP::ActOnOpenMPSIMDClause(), clang::SemaOpenMP::ActOnOpenMPSimdDirective(), clang::SemaOpenMP::ActOnOpenMPSimdlenClause(), clang::SemaOpenMP::ActOnOpenMPSingleDirective(), clang::SemaOpenMP::ActOnOpenMPSizesClause(), clang::SemaOpenMP::ActOnOpenMPTargetDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetEnterDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetExitDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetUpdateDirective(), clang::SemaOpenMP::ActOnOpenMPTaskDirective(), clang::SemaOpenMP::ActOnOpenMPTaskgroupDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTaskReductionClause(), clang::SemaOpenMP::ActOnOpenMPTaskwaitDirective(), clang::SemaOpenMP::ActOnOpenMPTaskyieldDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPThreadLimitClause(), clang::SemaOpenMP::ActOnOpenMPThreadsClause(), clang::SemaOpenMP::ActOnOpenMPToClause(), clang::SemaOpenMP::ActOnOpenMPUnifiedAddressClause(), clang::SemaOpenMP::ActOnOpenMPUnifiedSharedMemoryClause(), clang::SemaOpenMP::ActOnOpenMPUntiedClause(), clang::SemaOpenMP::ActOnOpenMPUpdateClause(), clang::SemaOpenMP::ActOnOpenMPUseClause(), clang::SemaOpenMP::ActOnOpenMPUseDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPUseDevicePtrClause(), clang::SemaOpenMP::ActOnOpenMPWeakClause(), clang::SemaOpenMP::ActOnOpenMPWriteClause(), clang::SemaOpenMP::ActOnOpenMPXAttributeClause(), clang::SemaOpenMP::ActOnOpenMPXBareClause(), clang::SemaOpenMP::ActOnOpenMPXDynCGroupMemClause(), clang::SemaHLSL::ActOnStartBuffer(), clang::SemaHLSL::ActOnTopLevelFunction(), clang::SemaSYCL::ActOnUniqueStableNameExpr(), clang::SemaSYCL::BuildUniqueStableIdExpr(), clang::SemaSYCL::BuildUniqueStableNameExpr(), clang::SemaPPC::BuiltinVSX(), clang::SemaWasm::BuiltinWasmRefNullExtern(), clang::SemaWasm::BuiltinWasmTableCopy(), clang::SemaWasm::BuiltinWasmTableFill(), clang::SemaWasm::BuiltinWasmTableGrow(), clang::SemaWasm::BuiltinWasmTableSet(), clang::SemaPPC::checkAIXMemberAlignment(), clang::SemaSYCL::checkAllowedSYCLInitializer(), clang::SemaAMDGPU::CheckAMDGCNBuiltinFunctionCall(), clang::SemaOpenCL::checkBuiltinCommitRWPipe(), clang::SemaHLSL::CheckBuiltinFunctionCall(), clang::SemaOpenCL::checkBuiltinReserveRWPipe(), clang::SemaOpenCL::checkBuiltinRWPipe(), clang::SemaOpenCL::checkBuiltinToAddr(), clang::SemaCUDA::CheckCall(), clang::SemaObjC::CheckConversionToObjCLiteral(), clang::SemaOpenMP::checkDeclIsAllowedInOpenMPTarget(), clang::SemaARM::CheckNeonBuiltinFunctionCall(), clang::SemaOpenMP::CheckOMPRequiresDecl(), clang::SemaOpenMP::CheckOpenMPLinearDecl(), clang::SemaOpenACC::CheckReductionVar(), clang::SemaSYCL::CheckSYCLKernelCall(), clang::SemaSystemZ::CheckSystemZBuiltinFunctionCall(), clang::SemaSYCL::ConstructOpenCLKernel(), clang::SemaCUDA::getConfigureFuncName(), getFreeFunctionRangeDim(), clang::SemaOpenCL::handleAccessAttr(), clang::SemaAMDGPU::handleAMDGPUNumSGPRAttr(), clang::SemaAMDGPU::handleAMDGPUNumVGPRAttr(), clang::SemaSwift::handleAsyncAttr(), clang::SemaSwift::handleAsyncError(), clang::SemaSwift::handleAttrAttr(), clang::SemaObjC::handleBlocksAttr(), clang::SemaObjC::handleBoxable(), clang::SemaSwift::handleBridge(), clang::SemaObjC::handleBridgeAttr(), clang::SemaObjC::handleBridgeMutableAttr(), clang::SemaObjC::handleBridgeRelatedAttr(), clang::SemaARM::handleCmseNSEntryAttr(), clang::SemaObjC::handleDesignatedInitializer(), clang::SemaX86::handleForceAlignArgPointerAttr(), clang::SemaObjC::handleIBOutlet(), clang::SemaObjC::handleIndependentClass(), clang::SemaARM::handleInterruptAttr(), clang::SemaM68k::handleInterruptAttr(), clang::SemaMIPS::handleInterruptAttr(), clang::SemaMSP430::handleInterruptAttr(), clang::SemaObjC::handleMethodFamilyAttr(), clang::SemaSwift::handleNewType(), clang::SemaObjC::handleNSErrorDomain(), clang::SemaObjC::handleNSObject(), clang::SemaHLSL::handleNumThreadsAttr(), clang::SemaOpenMP::handleOMPAssumeAttr(), clang::SemaHLSL::handlePackOffsetAttr(), clang::SemaObjC::handlePreciseLifetimeAttr(), clang::SemaBPF::handlePreserveAccessIndexAttr(), clang::SemaBPF::handlePreserveAIRecord(), clang::SemaObjC::handleRequiresSuperAttr(), clang::SemaHLSL::handleResourceBindingAttr(), clang::SemaHLSL::handleResourceClassAttr(), clang::SemaObjC::handleReturnsInnerPointerAttr(), clang::SemaObjC::handleRuntimeName(), clang::SemaObjC::handleSuppresProtocolAttr(), clang::SemaHLSL::handleSV_DispatchThreadIDAttr(), clang::SemaWasm::handleWebAssemblyImportModuleAttr(), clang::SemaWasm::handleWebAssemblyImportNameAttr(), clang::SemaCUDA::inferTargetForImplicitSpecialMember(), clang::SemaObjC::isCFStringType(), isFreeFunction(), clang::SemaObjC::isNSStringType(), clang::SemaOpenMP::isOpenMPDeclareMapperVarDeclAllowed(), clang::SemaCUDA::MaybeAddConstantAttr(), clang::SemaCUDA::maybeAddHostDeviceAttrs(), clang::SemaWasm::mergeImportModuleAttr(), clang::SemaWasm::mergeImportNameAttr(), clang::SemaHLSL::mergeNumThreadsAttr(), clang::SemaHLSL::mergeParamModifierAttr(), clang::SemaHLSL::mergeShaderAttr(), clang::SemaCUDA::RecordImplicitHostDeviceFuncUsedByDevice(), clang::SemaCUDA::SetLambdaAttrs(), clang::SemaSYCL::SetSYCLKernelNames(), clang::SemaARM::SmeAliasValid(), clang::SemaARM::SveAliasValid(), and clang::SemaOpenMP::tryCaptureOpenMPLambdas().
getDiagnostics()
DiagnosticsEngine & clang::SemaBase::getDiagnostics () const
Definition at line 10 of file SemaBase.cpp.
References clang::Sema::Diags, and SemaRef.
Referenced by Diag(), clang::SemaCUDA::DiagIfDeviceCode(), clang::SemaCUDA::DiagIfHostCode(), clang::SemaObjC::DiagnoseMultipleMethodInGlobalPool(), clang::Sema::PushBlockScope(), clang::Sema::PushFunctionScope(), and clang::Sema::PushLambdaScope().
getLangOpts()
const LangOptions & clang::SemaBase::getLangOpts () const
Definition at line 11 of file SemaBase.cpp.
References clang::Sema::LangOpts, and SemaRef.
Referenced by clang::SemaObjC::ActOnObjCAtSynchronizedOperand(), clang::SemaObjC::ActOnObjCAtThrowStmt(), clang::SemaOpenMP::ActOnOpenMPAlignedClause(), clang::SemaOpenMP::ActOnOpenMPCall(), clang::SemaOpenMP::ActOnOpenMPDeclareSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDeclareTargetName(), clang::SemaOpenMP::ActOnOpenMPDefaultmapClause(), clang::SemaOpenMP::ActOnOpenMPDependClause(), clang::SemaOpenMP::ActOnOpenMPDestroyClause(), clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPDistScheduleClause(), clang::SemaOpenMP::ActOnOpenMPExecutableDirective(), clang::SemaOpenMP::ActOnOpenMPFilterClause(), clang::SemaOpenMP::ActOnOpenMPFinalClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPGrainsizeClause(), clang::SemaOpenMP::ActOnOpenMPIfClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPLoopInitialization(), clang::SemaOpenMP::ActOnOpenMPNocontextClause(), clang::SemaOpenMP::ActOnOpenMPNovariantsClause(), clang::SemaOpenMP::ActOnOpenMPNumTasksClause(), clang::SemaOpenMP::ActOnOpenMPNumTeamsClause(), clang::SemaOpenMP::ActOnOpenMPNumThreadsClause(), clang::SemaOpenMP::ActOnOpenMPOrderClause(), clang::SemaOpenMP::ActOnOpenMPOrderedDirective(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPProcBindClause(), clang::SemaOpenMP::ActOnOpenMPScheduleClause(), clang::SemaOpenMP::ActOnOpenMPTargetDataDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPThreadLimitClause(), clang::SemaOpenMP::ActOnOpenMPUpdateClause(), clang::SemaOpenMP::ActOnOpenMPXDynCGroupMemClause(), clang::SemaOpenMP::ActOnStartOpenMPDeclareTargetContext(), clang::SemaSYCL::addSyclVarDecl(), clang::SemaObjC::AddXConsumedAttr(), clang::SemaObjC::AtomicPropertySetterGetterRules(), clang::SemaSYCL::checkAllowedSYCLInitializer(), clang::SemaCUDA::CheckCall(), clang::SemaObjC::CheckConversionToObjCLiteral(), clang::SemaOpenMP::checkDeclIsAllowedInOpenMPTarget(), clang::SemaCUDA::CheckLambdaCapture(), clang::SemaObjC::CheckObjCPropertyAttributes(), clang::SemaOpenMP::CheckOpenMPLinearModifier(), clang::SemaOpenCL::checkSubgroupExt(), clang::SemaObjC::CheckSubscriptingKind(), clang::SemaSYCL::checkSYCLDeviceVarDecl(), clang::SemaCUDA::checkTargetOverload(), clang::SemaObjC::CheckTollFreeBridgeCast(), clang::SemaObjC::CheckTollFreeBridgeStaticCast(), clang::SemaSYCL::ConstructOpenCLKernel(), clang::SemaSYCL::deepTypeCheckForDevice(), Diag(), clang::SemaCUDA::DiagIfDeviceCode(), clang::SemaSYCL::DiagIfDeviceCode(), clang::SemaCUDA::DiagIfHostCode(), clang::SemaObjC::DiagnoseMultipleMethodInGlobalPool(), clang::SemaObjC::DiagnoseOwningPropertyGetterSynthesis(), clang::SemaOpenMP::finalizeOpenMPDelayedAnalysis(), clang::SemaSYCL::finalizeSYCLDelayedAnalysis(), clang::SemaCUDA::getConfigureFuncName(), clang::SemaOpenMP::getOpenMPCapturedExpr(), clang::SemaOpenMP::getOpenMPDeclareMapperVarName(), clang::SemaOpenCL::handleAccessAttr(), clang::SemaARM::handleCmseNSEntryAttr(), clang::SemaObjC::handleDirectAttr(), clang::SemaObjC::handleDirectMembersAttr(), clang::SemaOpenCL::handleNoSVMAttr(), clang::SemaObjC::handleXReturnsXRetainedAttr(), clang::SemaCUDA::IdentifyPreference(), clang::SemaOpenMP::isOpenMPDeclareMapperVarDeclAllowed(), clang::SemaOpenMP::isOpenMPGlobalCapturedDecl(), clang::SemaOpenMP::isOpenMPTargetCapturedDecl(), clang::SemaObjC::isSignedCharBool(), clang::SemaSYCL::isSYCLEsimdPrivateGlobal(), clang::SemaCUDA::MaybeAddConstantAttr(), clang::SemaCUDA::maybeAddHostDeviceAttrs(), clang::SemaCUDA::PopForceHostDevice(), clang::SemaCUDA::PushForceHostDevice(), clang::SemaObjC::SetIvarInitializers(), clang::SemaCUDA::SetLambdaAttrs(), and clang::SemaObjC::WarnConflictingTypedMethods().
isFDReachableFromSyclDevice()
bool clang::SemaBase::isFDReachableFromSyclDevice (const FunctionDecl * Callee, const FunctionDecl * Caller) inline
Definition at line 139 of file SemaBase.h.
References P.
Referenced by clang::SemaSYCL::finalizeSYCLDelayedAnalysis().
PDiag()
PartialDiagnostic clang::SemaBase::PDiag (unsigned DiagID = 0)
Build a partial diagnostic.
Definition at line 32 of file SemaBase.cpp.
References clang::Sema::Context, clang::ASTContext::getDiagAllocator(), and SemaRef.
Referenced by clang::Sema::ActOnDecltypeExpression(), clang::Sema::BuildLiteralOperatorCall(), BuildNonArrayForRange(), checkDestructorReference(), clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::CheckExceptionSpecCompatibility(), clang::Sema::CheckOverridingFunctionExceptionSpec(), clang::Sema::CheckParamExceptionSpec(), clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::Sema::CreateOverloadedUnaryOp(), clang::Sema::diagnoseTypo(), clang::Sema::FinalizeVarWithDestructor(), clang::SemaObjC::FindProtocolDeclaration(), clang::SemaObjC::getObjCInterfaceDecl(), clang::Sema::isMemberAccessibleForDeletion(), clang::SemaOpenMP::lookupOpenMPDeclareTargetName(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), clang::Sema::MarkVirtualBaseDestructorsReferenced(), clang::Sema::MaybeBindToTemporary(), clang::Sema::NoteHiddenVirtualMethods(), clang::Sema::NoteOverloadCandidate(), and clang::Sema::PerformImplicitConversion().
Member Data Documentation
SemaRef
Sema& clang::SemaBase::SemaRef
Definition at line 40 of file SemaBase.h.
Referenced by clang::SemaOpenMP::ActOnFinishedFunctionDefinitionInOpenMPAssumeScope(), clang::SemaOpenMP::ActOnFinishedFunctionDefinitionInOpenMPDeclareVariantScope(), clang::SemaObjC::ActOnFinishObjCImplementation(), clang::SemaObjC::ActOnObjCAtSynchronizedOperand(), clang::SemaObjC::ActOnObjCContainerFinishDefinition(), clang::SemaObjC::ActOnObjCContainerStartDefinition(), clang::SemaObjC::ActOnObjCReenterContainerContext(), clang::SemaObjC::ActOnObjCTemporaryExitContainerContext(), clang::SemaOpenMP::ActOnOpenMPAffinityClause(), clang::SemaOpenMP::ActOnOpenMPAlignedClause(), clang::SemaOpenMP::ActOnOpenMPAllocatorClause(), clang::SemaOpenMP::ActOnOpenMPAssumesDirective(), clang::SemaOpenMP::ActOnOpenMPCanonicalLoop(), clang::SemaOpenMP::ActOnOpenMPCopyinClause(), clang::SemaOpenMP::ActOnOpenMPCopyprivateClause(), clang::SemaOpenMP::ActOnOpenMPCriticalDirective(), clang::SemaOpenMP::ActOnOpenMPDeclareMapperType(), clang::SemaOpenMP::ActOnOpenMPDeclareReductionCombinerEnd(), clang::SemaOpenMP::ActOnOpenMPDeclareReductionInitializerEnd(), clang::SemaOpenMP::ActOnOpenMPDeclareReductionType(), clang::SemaOpenMP::ActOnOpenMPDeclareSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDependClause(), clang::SemaOpenMP::ActOnOpenMPDepobjClause(), clang::SemaOpenMP::ActOnOpenMPDestroyClause(), clang::SemaOpenMP::ActOnOpenMPDetachClause(), clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistScheduleClause(), clang::SemaOpenMP::ActOnOpenMPDoacrossClause(), clang::SemaOpenMP::ActOnOpenMPExclusiveClause(), clang::SemaOpenMP::ActOnOpenMPExecutableDirective(), clang::SemaOpenMP::ActOnOpenMPFilterClause(), clang::SemaOpenMP::ActOnOpenMPFinalClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPForDirective(), clang::SemaOpenMP::ActOnOpenMPForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPFromClause(), clang::SemaOpenMP::ActOnOpenMPGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPGrainsizeClause(), clang::SemaOpenMP::ActOnOpenMPHasDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPIfClause(), clang::SemaOpenMP::ActOnOpenMPInclusiveClause(), clang::SemaOpenMP::ActOnOpenMPInitClause(), clang::SemaOpenMP::ActOnOpenMPInReductionClause(), clang::SemaOpenMP::ActOnOpenMPInteropDirective(), clang::SemaOpenMP::ActOnOpenMPIsDevicePtrClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPLoopInitialization(), clang::SemaOpenMP::ActOnOpenMPMapClause(), clang::SemaOpenMP::ActOnOpenMPMaskedDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMasterDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPNocontextClause(), clang::SemaOpenMP::ActOnOpenMPNontemporalClause(), clang::SemaOpenMP::ActOnOpenMPNovariantsClause(), clang::SemaOpenMP::ActOnOpenMPNumTasksClause(), clang::SemaOpenMP::ActOnOpenMPNumTeamsClause(), clang::SemaOpenMP::ActOnOpenMPNumThreadsClause(), clang::SemaOpenMP::ActOnOpenMPOrderedDirective(), clang::SemaOpenMP::ActOnOpenMPParallelDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelSectionsDirective(), clang::SemaOpenMP::ActOnOpenMPPriorityClause(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPReductionClause(), clang::SemaOpenMP::ActOnOpenMPRegionStart(), clang::SemaOpenMP::ActOnOpenMPRequiresDirective(), clang::SemaOpenMP::ActOnOpenMPScheduleClause(), clang::SemaOpenMP::ActOnOpenMPScopeDirective(), clang::SemaOpenMP::ActOnOpenMPSectionDirective(), clang::SemaOpenMP::ActOnOpenMPSectionsDirective(), clang::SemaOpenMP::ActOnOpenMPSharedClause(), clang::SemaOpenMP::ActOnOpenMPSimdDirective(), clang::SemaOpenMP::ActOnOpenMPSingleDirective(), clang::SemaOpenMP::ActOnOpenMPSizesClause(), clang::SemaOpenMP::ActOnOpenMPTargetDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetDirective(), clang::SemaOpenMP::ActOnOpenMPTargetEnterDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetExitDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetUpdateDirective(), clang::SemaOpenMP::ActOnOpenMPTaskDirective(), clang::SemaOpenMP::ActOnOpenMPTaskgroupDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTaskReductionClause(), clang::SemaOpenMP::ActOnOpenMPTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPThreadLimitClause(), clang::SemaOpenMP::ActOnOpenMPThreadprivateDirective(), clang::SemaOpenMP::ActOnOpenMPToClause(), clang::SemaOpenMP::ActOnOpenMPUseClause(), clang::SemaOpenMP::ActOnOpenMPUseDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPUseDevicePtrClause(), clang::SemaOpenMP::ActOnOpenMPXDynCGroupMemClause(), clang::SemaHLSL::ActOnStartBuffer(), clang::SemaOpenMP::ActOnStartOpenMPDeclareTargetContext(), clang::SemaObjC::ActOnTypedefedProtocols(), clang::SemaSYCL::ActOnUniqueStableNameExpr(), clang::SemaObjC::AtomicPropertySetterGetterRules(), attemptRecovery(), BuildImplicitBaseInitializer(), BuildImplicitMemberInitializer(), clang::SemaARM::BuiltinARMSpecialReg(), clang::SemaPPC::BuiltinVSX(), clang::SemaWasm::BuiltinWasmTableCopy(), clang::SemaWasm::BuiltinWasmTableFill(), clang::SemaWasm::BuiltinWasmTableGet(), clang::SemaWasm::BuiltinWasmTableGrow(), clang::SemaWasm::BuiltinWasmTableSet(), clang::SemaWasm::BuiltinWasmTableSize(), canRecoverDotPseudoDestructorCallsOnPointerObjects(), CastForMoving(), clang::SemaARM::CheckAArch64BuiltinFunctionCall(), clang::SemaAMDGPU::CheckAMDGCNBuiltinFunctionCall(), clang::SemaARM::CheckARMBuiltinFunctionCall(), clang::SemaObjC::checkArrayLiteral(), clang::SemaOpenCL::checkBuiltinCommitRWPipe(), clang::SemaX86::CheckBuiltinFunctionCall(), clang::SemaHLSL::CheckBuiltinFunctionCall(), clang::SemaX86::CheckBuiltinGatherScatterScale(), clang::SemaOpenCL::checkBuiltinKernelWorkGroupSize(), clang::SemaOpenCL::checkBuiltinNDRangeAndBlock(), clang::SemaOpenCL::checkBuiltinPipePackets(), clang::SemaOpenCL::checkBuiltinReserveRWPipe(), clang::SemaX86::CheckBuiltinRoundingOrSAE(), clang::SemaOpenCL::checkBuiltinRWPipe(), clang::SemaX86::CheckBuiltinTileArgumentsRange(), clang::SemaX86::CheckBuiltinTileDuplicate(), clang::SemaOpenCL::checkBuiltinToAddr(), clang::SemaCUDA::CheckCall(), clang::SemaObjC::CheckConflictingOverridingMethod(), CheckConstexprCtorInitializer(), CheckConstexprDeclStmt(), CheckConstexprDestructorSubobjects(), CheckConstexprFunctionBody(), CheckConstexprMissingReturn(), CheckConstexprParameterTypes(), CheckConstexprReturnType(), clang::SemaOpenMP::checkDeclIsAllowedInOpenMPTarget(), clang::SemaHexagon::CheckHexagonBuiltinArgument(), clang::SemaCUDA::CheckLambdaCapture(), checkLiteralOperatorTemplateParameterList(), CheckLiteralType(), clang::SemaLoongArch::CheckLoongArchBuiltinFunctionCall(), clang::SemaMIPS::CheckMipsBuiltinArgument(), clang::SemaARM::CheckNeonBuiltinFunctionCall(), clang::SemaNVPTX::CheckNVPTXBuiltinFunctionCall(), clang::SemaObjC::CheckObjCDeclScope(), clang::SemaObjC::CheckObjCMethodCall(), clang::SemaOpenMP::CheckOMPRequiresDecl(), clang::SemaOpenMP::CheckOpenMPLinearDecl(), CheckOperatorDeleteDeclaration(), CheckOperatorNewDeclaration(), CheckOperatorNewDeleteDeclarationScope(), CheckOperatorNewDeleteTypes(), clang::SemaObjC::checkRetainCycles(), clang::SemaARM::CheckSMEBuiltinFunctionCall(), clang::SemaOpenCL::checkSubgroupExt(), clang::SemaObjC::CheckSubscriptingKind(), clang::SemaARM::CheckSVEBuiltinFunctionCall(), clang::SemaSYCL::CheckSYCLKernelCall(), clang::SemaSystemZ::CheckSystemZBuiltinFunctionCall(), clang::SemaCUDA::checkTargetOverload(), clang::SemaObjC::CheckTollFreeBridgeCast(), clang::Sema::InstantiatingTemplate::Clear(), CollectFieldInitializer(), clang::SemaObjC::CollectMultipleMethodsInGlobalPool(), clang::Sema::CorrectDelayedTyposInExpr(), clang::SemaCUDA::CurrentTarget(), Diag(), clang::SemaCUDA::DiagIfDeviceCode(), clang::SemaSYCL::DiagIfDeviceCode(), clang::SemaCUDA::DiagIfHostCode(), diagnoseAmbiguousConversion(), clang::SemaObjC::diagnoseARCUnbridgedCast(), clang::SemaHLSL::DiagnoseAvailabilityViolations(), DiagnoseBaseOrMemInitializerOrder(), clang::SemaObjC::DiagnoseCStringFormatDirectiveInCFAPI(), clang::Sema::DiagnoseImmediateEscalatingReason(), DiagnoseMismatchedNewDelete(), diagnoseNoViableConversion(), clang::SemaObjC::DiagnoseOwningPropertyGetterSynthesis(), DiagnoseTwoPhaseLookup(), DiagnoseTwoPhaseOperatorLookup(), clang::SemaOpenMP::EndOpenMPClause(), clang::SemaOpenMP::EndOpenMPDSABlock(), clang::SemaSYCL::finalizeSYCLDelayedAnalysis(), FindBaseInitializer(), clang::SemaObjC::FindProtocolDeclaration(), finishContextualImplicitConversion(), getASTContext(), clang::SemaObjC::getCurObjCLexicalContext(), getDiagnostics(), clang::SemaObjC::GetFormatNSStringIdx(), getLangOpts(), clang::SemaObjC::getNSErrorIdent(), clang::SemaObjC::getObjCContainerKind(), clang::SemaObjC::getObjCDeclContext(), clang::SemaObjC::getObjCInterfaceDecl(), clang::SemaOpenMP::getOpenMPCapturedExpr(), clang::SemaOpenCL::handleAccessAttr(), clang::SemaAMDGPU::handleAMDGPUNumSGPRAttr(), clang::SemaAMDGPU::handleAMDGPUNumVGPRAttr(), clang::SemaAMDGPU::handleAMDGPUWavesPerEUAttr(), clang::SemaSwift::handleAsyncAttr(), clang::SemaSwift::handleAsyncError(), clang::SemaSwift::handleAttrAttr(), clang::SemaObjC::handleBoxable(), clang::SemaSwift::handleBridge(), clang::SemaObjC::handleExternallyRetainedAttr(), clang::SemaObjC::handleIBOutlet(), clang::SemaARM::handleInterruptAttr(), clang::SemaAVR::handleInterruptAttr(), clang::SemaM68k::handleInterruptAttr(), clang::SemaMIPS::handleInterruptAttr(), clang::SemaMSP430::handleInterruptAttr(), clang::SemaSwift::handleNewType(), clang::SemaObjC::handleNSErrorDomain(), clang::SemaHLSL::handleNumThreadsAttr(), clang::SemaOpenMP::handleOMPAssumeAttr(), clang::SemaHLSL::handlePackOffsetAttr(), clang::SemaObjC::handleRuntimeName(), clang::SemaHLSL::handleShaderAttr(), clang::SemaAVR::handleSignalAttr(), clang::SemaWasm::handleWebAssemblyImportModuleAttr(), clang::SemaWasm::handleWebAssemblyImportNameAttr(), clang::Sema::SFINAETrap::hasErrorOccurred(), clang::SemaCUDA::inferTargetForImplicitSpecialMember(), clang::SemaCUDA::inheritTargetAttrs(), clang::Sema::InstantiateVariableDefinition(), clang::SemaCUDA::isEmptyConstructor(), clang::SemaCUDA::isEmptyDestructor(), clang::SemaObjC::isSelfExpr(), clang::Sema::LambdaScopeForCallOperatorInstantiationRAII::LambdaScopeForCallOperatorInstantiationRAII(), clang::SemaOpenMP::lookupOpenMPDeclareTargetName(), clang::SemaObjC::LookupProtocol(), clang::SemaSYCL::MarkDevices(), clang::SemaObjC::MatchAllMethodDeclarations(), clang::SemaCUDA::maybeAddHostDeviceAttrs(), clang::SemaARM::ParseSVEImmChecks(), PDiag(), clang::SemaObjC::PrepareCastToObjCObjectPointer(), clang::SemaObjC::ReadMethodPool(), recordConversion(), clang::SemaCUDA::RecordImplicitHostDeviceFuncUsedByDevice(), RemoveAddressSpaceFromPtr(), clang::SemaObjC::SelectorsForTypoCorrection(), clang::Sema::SFINAETrap::SFINAETrap(), clang::SemaOpenMP::StartOpenMPDSABlock(), clang::Sema::TentativeAnalysisScope::TentativeAnalysisScope(), clang::SemaObjC::tryCaptureObjCSelf(), clang::SemaOpenMP::tryCaptureOpenMPLambdas(), clang::SemaObjC::updateOutOfDateSelector(), clang::SemaObjC::WarnConflictingTypedMethods(), clang::SemaOpenACC::AssociatedStmtRAII::~AssociatedStmtRAII(), clang::Sema::SatisfactionStackResetRAII::~SatisfactionStackResetRAII(), clang::Sema::SFINAETrap::~SFINAETrap(), and clang::Sema::TentativeAnalysisScope::~TentativeAnalysisScope().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaBase.h
lib/Sema/SemaBase.cpp