clang: clang::UncommonTemplateNameStorage Class Reference
clang::UncommonTemplateNameStorage Class Reference
Implementation class used to describe either a set of overloaded template names or an already-substituted template template parameter pack.
#include "clang/AST/TemplateName.h"
Classes
struct BitsTag
Public Member Functions
OverloadedTemplateStorage * getAsOverloadedStorage ()
AssumedTemplateStorage * getAsAssumedTemplateName ()
SubstTemplateTemplateParmStorage * getAsSubstTemplateTemplateParm ()
SubstTemplateTemplateParmPackStorage * getAsSubstTemplateTemplateParmPack ()
Protected Types
enum Kind { Overloaded , Assumed , SubstTemplateTemplateParm , SubstTemplateTemplateParmPack }
Protected Member Functions
UncommonTemplateNameStorage (Kind Kind, unsigned Index, unsigned Data)
Protected Attributes
union {
struct BitsTag Bits
void * PointerAlignment
};
Detailed Description
Implementation class used to describe either a set of overloaded template names or an already-substituted template template parameter pack.
Definition at line 48 of file TemplateName.h.
Member Enumeration Documentation
Kind
enum clang::UncommonTemplateNameStorage::Kind protected
Enumerator
Overloaded
Assumed
SubstTemplateTemplateParm
SubstTemplateTemplateParmPack
Definition at line 50 of file TemplateName.h.
Constructor & Destructor Documentation
UncommonTemplateNameStorage()
clang::UncommonTemplateNameStorage::UncommonTemplateNameStorage (Kind Kind, unsigned Index, unsigned Data) inline protected
Definition at line 74 of file TemplateName.h.
References Bits, clang::UncommonTemplateNameStorage::BitsTag::Data, clang::UncommonTemplateNameStorage::BitsTag::Index, and clang::UncommonTemplateNameStorage::BitsTag::Kind.
Member Function Documentation
getAsAssumedTemplateName()
AssumedTemplateStorage* clang::UncommonTemplateNameStorage::getAsAssumedTemplateName () inline
Definition at line 87 of file TemplateName.h.
References Assumed, Bits, and clang::UncommonTemplateNameStorage::BitsTag::Kind.
Referenced by clang::TemplateName::getAsAssumedTemplateName(), and clang::TemplateName::getKind().
getAsOverloadedStorage()
OverloadedTemplateStorage* clang::UncommonTemplateNameStorage::getAsOverloadedStorage () inline
Definition at line 81 of file TemplateName.h.
References Bits, clang::UncommonTemplateNameStorage::BitsTag::Kind, and Overloaded.
Referenced by clang::TemplateName::getAsOverloadedTemplate(), and clang::TemplateName::getKind().
getAsSubstTemplateTemplateParm()
SubstTemplateTemplateParmStorage* clang::UncommonTemplateNameStorage::getAsSubstTemplateTemplateParm () inline
Definition at line 93 of file TemplateName.h.
References Bits, clang::UncommonTemplateNameStorage::BitsTag::Kind, and SubstTemplateTemplateParm.
Referenced by clang::TemplateName::getAsSubstTemplateTemplateParm(), clang::TemplateName::getKind(), and clang::TemplateName::getUnderlying().
getAsSubstTemplateTemplateParmPack()
SubstTemplateTemplateParmPackStorage* clang::UncommonTemplateNameStorage::getAsSubstTemplateTemplateParmPack () inline
Definition at line 99 of file TemplateName.h.
References Bits, clang::UncommonTemplateNameStorage::BitsTag::Kind, and SubstTemplateTemplateParmPack.
Referenced by clang::TemplateName::getAsSubstTemplateTemplateParmPack().
Member Data Documentation
union { ... }
Bits
struct BitsTag clang::UncommonTemplateNameStorage::Bits
Definition at line 66 of file TemplateName.h.
Referenced by clang::OverloadedTemplateStorage::end(), clang::SubstTemplateTemplateParmPackStorage::getArgumentPack(), getAsAssumedTemplateName(), getAsOverloadedStorage(), getAsSubstTemplateTemplateParm(), getAsSubstTemplateTemplateParmPack(), clang::SubstTemplateTemplateParmPackStorage::getIndex(), clang::SubstTemplateTemplateParmStorage::getIndex(), clang::SubstTemplateTemplateParmStorage::getPackIndex(), clang::SubstTemplateTemplateParmStorage::getParameter(), clang::SubstTemplateTemplateParmPackStorage::getParameterPack(), clang::OverloadedTemplateStorage::size(), and UncommonTemplateNameStorage().
PointerAlignment
void* clang::UncommonTemplateNameStorage::PointerAlignment
Definition at line 71 of file TemplateName.h.
The documentation for this class was generated from the following file:
include/clang/AST/TemplateName.h