clang: clang::CleanupInfo Class Reference
clang::CleanupInfo Class Reference
#include "clang/Sema/CleanupInfo.h"
Public Member Functions
bool exprNeedsCleanups () const
bool cleanupsHaveSideEffects () const
void setExprNeedsCleanups (bool SideEffects)
void reset ()
void mergeFrom (CleanupInfo Rhs)
Detailed Description
Definition at line 19 of file CleanupInfo.h.
Member Function Documentation
cleanupsHaveSideEffects()
bool clang::CleanupInfo::cleanupsHaveSideEffects () const inline
Definition at line 26 of file CleanupInfo.h.
Referenced by clang::Sema::MaybeCreateExprWithCleanups().
exprNeedsCleanups()
bool clang::CleanupInfo::exprNeedsCleanups () const inline
Definition at line 24 of file CleanupInfo.h.
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::Sema::BuildStmtExpr(), clang::Sema::MaybeCreateExprWithCleanups(), and clang::Sema::MaybeCreateStmtWithCleanups().
mergeFrom()
void clang::CleanupInfo::mergeFrom (CleanupInfo Rhs) inline
Definition at line 38 of file CleanupInfo.h.
Referenced by clang::Sema::PopExpressionEvaluationContext().
reset()
void clang::CleanupInfo::reset () inline
Definition at line 33 of file CleanupInfo.h.
Referenced by clang::Sema::DiscardCleanupsInEvaluationContext(), and clang::Sema::PushExpressionEvaluationContext().
setExprNeedsCleanups()
void clang::CleanupInfo::setExprNeedsCleanups (bool SideEffects) inline
Definition at line 28 of file CleanupInfo.h.
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::Sema::BuildCompoundLiteralExpr(), clang::Sema::BuildObjCBridgedCast(), clang::Sema::CheckCXXDefaultArgExpr(), clang::Sema::CheckObjCConversion(), clang::Sema::CreateMaterializeTemporaryExpr(), clang::Sema::MaybeBindToTemporary(), and clang::Sema::maybeExtendBlockObject().
The documentation for this class was generated from the following file:
include/clang/Sema/CleanupInfo.h