clang: clang::CallGraphNode Class Reference
clang::CallGraphNode Class Reference
#include "clang/Analysis/CallGraph.h"
Classes
struct CallRecord
Public Types
using iterator = SmallVectorImpl< CallRecord >::iterator
using const_iterator = SmallVectorImpl< CallRecord >::const_iterator
Public Member Functions
CallGraphNode (Decl *D)
iterator begin ()
Iterators through all the callees/children of the node.
iterator end ()
const_iterator begin () const
const_iterator end () const
llvm::iterator_range< iterator > callees ()
Iterator access to callees/children of the node.
llvm::iterator_range< const_iterator > callees () const
bool empty () const
unsigned size () const
void addCallee (CallRecord Call)
Decl * getDecl () const
FunctionDecl * getDefinition () const
void print (raw_ostream &os) const
void dump () const
Detailed Description
Definition at line 163 of file CallGraph.h.
Member Typedef Documentation
const_iterator
using clang::CallGraphNode::const_iterator = SmallVectorImpl<CallRecord>::const_iterator
Definition at line 190 of file CallGraph.h.
iterator
using clang::CallGraphNode::iterator = SmallVectorImpl<CallRecord>::iterator
Definition at line 189 of file CallGraph.h.
Constructor & Destructor Documentation
CallGraphNode()
clang::CallGraphNode::CallGraphNode (Decl * D) inline
Definition at line 187 of file CallGraph.h.
Member Function Documentation
addCallee()
void clang::CallGraphNode::addCallee (CallRecord Call) inline
Definition at line 209 of file CallGraph.h.
Referenced by clang::CallGraph::getOrInsertNode().
begin() [1/2]
iterator clang::CallGraphNode::begin () inline
Iterators through all the callees/children of the node.
Definition at line 193 of file CallGraph.h.
Referenced by callees(), llvm::GraphTraits< clang::CallGraphNode * >::child_begin(), llvm::GraphTraits< const clang::CallGraphNode * >::child_begin(), and clang::CallGraph::print().
begin() [2/2]
const_iterator clang::CallGraphNode::begin () const inline
Definition at line 195 of file CallGraph.h.
callees() [1/2]
llvm::iterator_range<iterator> clang::CallGraphNode::callees () inline
Iterator access to callees/children of the node.
Definition at line 199 of file CallGraph.h.
References begin(), and end().
callees() [2/2]
llvm::iterator_range<const_iterator> clang::CallGraphNode::callees () const inline
Definition at line 202 of file CallGraph.h.
References begin(), and end().
dump()
LLVM_DUMP_METHOD void CallGraphNode::dump () const
Definition at line 282 of file CallGraph.cpp.
References print().
empty()
bool clang::CallGraphNode::empty () const inline
Definition at line 206 of file CallGraph.h.
end() [1/2]
iterator clang::CallGraphNode::end () inline
Definition at line 194 of file CallGraph.h.
Referenced by callees(), llvm::GraphTraits< clang::CallGraphNode * >::child_end(), llvm::GraphTraits< const clang::CallGraphNode * >::child_end(), and clang::CallGraph::print().
end() [2/2]
const_iterator clang::CallGraphNode::end () const inline
Definition at line 196 of file CallGraph.h.
getDecl()
Decl* clang::CallGraphNode::getDecl () const inline
Definition at line 211 of file CallGraph.h.
Referenced by getDefinition().
getDefinition()
FunctionDecl* clang::CallGraphNode::getDefinition () const inline
Definition at line 213 of file CallGraph.h.
References clang::Decl::getAsFunction(), getDecl(), and clang::FunctionDecl::getDefinition().
print()
void CallGraphNode::print (raw_ostream & os) const
Definition at line 276 of file CallGraph.cpp.
Referenced by dump(), and clang::CallGraph::print().
size()
unsigned clang::CallGraphNode::size () const inline
Definition at line 207 of file CallGraph.h.
The documentation for this class was generated from the following files:
include/clang/Analysis/CallGraph.h
lib/Analysis/CallGraph.cpp