clang: clang::interp::SourceMapper Class Reference
clang::interp::SourceMapper Class Reference abstract
Interface for classes which map locations to sources.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Source.h"
Public Member Functions
virtual ~SourceMapper ()
virtual SourceInfo getSource (const Function *F, CodePtr PC) const =0
Returns source information for a given PC in a function.
const Expr * getExpr (const Function *F, CodePtr PC) const
Returns the expression if an opcode belongs to one, null otherwise.
SourceLocation getLocation (const Function *F, CodePtr PC) const
Returns the location from which an opcode originates.
SourceRange getRange (const Function *F, CodePtr PC) const
Detailed Description
Interface for classes which map locations to sources.
Definition at line 94 of file Source.h.
Constructor & Destructor Documentation
~SourceMapper()
virtual clang::interp::SourceMapper::~SourceMapper () inline virtual
Definition at line 96 of file Source.h.
Member Function Documentation
getExpr()
const Expr * SourceMapper::getExpr (const Function * F, CodePtr PC) const
Returns the expression if an opcode belongs to one, null otherwise.
Definition at line 41 of file Source.cpp.
References getSource().
Referenced by clang::interp::InterpFrame::getExpr().
getLocation()
SourceLocation SourceMapper::getLocation (const Function * F, CodePtr PC) const
Returns the location from which an opcode originates.
Definition at line 47 of file Source.cpp.
References clang::interp::SourceInfo::getLoc(), and getSource().
Referenced by clang::interp::InterpFrame::getLocation().
getRange()
SourceRange SourceMapper::getRange (const Function * F, CodePtr PC) const
Definition at line 51 of file Source.cpp.
References clang::interp::SourceInfo::getRange(), and getSource().
Referenced by clang::interp::InterpFrame::getCallRange(), and clang::interp::InterpFrame::getRange().
getSource()
virtual SourceInfo clang::interp::SourceMapper::getSource (const Function * F, CodePtr PC) const pure virtual
Returns source information for a given PC in a function.
Implemented in clang::interp::InterpState, and clang::interp::EvalEmitter.
Referenced by getExpr(), getLocation(), getRange(), and clang::interp::InterpState::getSource().
The documentation for this class was generated from the following files:
lib/AST/Interp/Source.h
lib/AST/Interp/Source.cpp