clang: clang::FileManager Class Reference
clang::FileManager Class Reference
Implements support for file system lookup, file system caching, and directory search management.
#include "clang/Basic/FileManager.h"
Public Member Functions
FileManager (const FileSystemOptions &FileSystemOpts, IntrusiveRefCntPtr< llvm::vfs::FileSystem > FS=nullptr)
Construct a file manager, optionally with a custom VFS.
~FileManager ()
void setStatCache (std::unique_ptr< FileSystemStatCache > statCache)
Installs the provided FileSystemStatCache object within the FileManager.
void clearStatCache ()
Removes the FileSystemStatCache object from the manager.
size_t getNumUniqueRealFiles () const
Returns the number of unique real file entries cached by the file manager.
llvm::Expected< DirectoryEntryRef > getDirectoryRef (StringRef DirName, bool CacheFailure=true)
Lookup, cache, and verify the specified directory (real or virtual).
OptionalDirectoryEntryRef getOptionalDirectoryRef (StringRef DirName, bool CacheFailure=true)
Get a DirectoryEntryRef if it exists, without doing anything on error.
llvm::ErrorOr< const DirectoryEntry * > getDirectory (StringRef DirName, bool CacheFailure=true)
Lookup, cache, and verify the specified directory (real or virtual).
llvm::ErrorOr< const FileEntry * > getFile (StringRef Filename, bool OpenFile=false, bool CacheFailure=true)
Lookup, cache, and verify the specified file (real or virtual).
llvm::Expected< FileEntryRef > getFileRef (StringRef Filename, bool OpenFile=false, bool CacheFailure=true)
Lookup, cache, and verify the specified file (real or virtual).
llvm::Expected< FileEntryRef > getSTDIN ()
Get the FileEntryRef for stdin, returning an error if stdin cannot be read.
OptionalFileEntryRef getOptionalFileRef (StringRef Filename, bool OpenFile=false, bool CacheFailure=true)
Get a FileEntryRef if it exists, without doing anything on error.
FileSystemOptions & getFileSystemOpts ()
Returns the current file system options.
const FileSystemOptions & getFileSystemOpts () const
llvm::vfs::FileSystem & getVirtualFileSystem () const
llvm::IntrusiveRefCntPtr< llvm::vfs::FileSystem > getVirtualFileSystemPtr () const
void trackVFSUsage (bool Active)
Enable or disable tracking of VFS usage.
void setVirtualFileSystem (IntrusiveRefCntPtr< llvm::vfs::FileSystem > FS)
FileEntryRef getVirtualFileRef (StringRef Filename, off_t Size, time_t ModificationTime)
Retrieve a file entry for a "virtual" file that acts as if there were a file with the given name on disk.
const FileEntry * getVirtualFile (StringRef Filename, off_t Size, time_t ModificationTime)
OptionalFileEntryRef getBypassFile (FileEntryRef VFE)
Retrieve a FileEntry that bypasses VFE, which is expected to be a virtual file entry, to access the real file.
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > getBufferForFile (FileEntryRef Entry, bool isVolatile=false, bool RequiresNullTerminator=true)
Open the specified file as a MemoryBuffer, returning a new MemoryBuffer if successful, otherwise returning null.
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > getBufferForFile (StringRef Filename, bool isVolatile=false, bool RequiresNullTerminator=true) const
std::error_code getNoncachedStatValue (StringRef Path, llvm::vfs::Status &Result)
Get the 'stat' information for the given Path.
bool FixupRelativePath (SmallVectorImpl< char > &path) const
If path is not absolute and FileSystemOptions set the working directory, the path is modified to be relative to the given working directory.
bool makeAbsolutePath (SmallVectorImpl< char > &Path) const
Makes Path absolute taking into account FileSystemOptions and the working directory option.
void GetUniqueIDMapping (SmallVectorImpl< OptionalFileEntryRef > &UIDToFiles) const
Produce an array mapping from the unique IDs assigned to each file to the corresponding FileEntryRef.
StringRef getCanonicalName (DirectoryEntryRef Dir)
Retrieve the canonical name for a given directory.
StringRef getCanonicalName (FileEntryRef File)
Retrieve the canonical name for a given file.
void PrintStats () const
Detailed Description
Implements support for file system lookup, file system caching, and directory search management.
This also handles more advanced properties, such as uniquing files based on "inode", so that a file with two names (e.g. symlinked) will be treated as a single file.
Definition at line 53 of file FileManager.h.
Constructor & Destructor Documentation
FileManager()
FileManager::FileManager (const FileSystemOptions & FileSystemOpts, IntrusiveRefCntPtr< llvm::vfs::FileSystem > FS = nullptr)
Construct a file manager, optionally with a custom VFS.
Parameters
FS if non-null, the VFS to use. Otherwise uses llvm::vfs::getRealFileSystem().
Definition at line 52 of file FileManager.cpp.
~FileManager()
FileManager::~FileManager () default
Member Function Documentation
clearStatCache()
void FileManager::clearStatCache ()
Removes the FileSystemStatCache object from the manager.
Definition at line 69 of file FileManager.cpp.
Referenced by clang::tooling::FrontendActionFactory::runInvocation().
FixupRelativePath()
bool FileManager::FixupRelativePath (SmallVectorImpl< char > & path) const
If path is not absolute and FileSystemOptions set the working directory, the path is modified to be relative to the given working directory.
Returns
true if path changed.
Definition at line 484 of file FileManager.cpp.
References clang::FileSystemOptions::WorkingDir.
Referenced by makeAbsolutePath().
getBufferForFile() [1/2]
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > FileManager::getBufferForFile (FileEntryRef Entry, bool isVolatile = false, bool RequiresNullTerminator = true)
Open the specified file as a MemoryBuffer, returning a new MemoryBuffer if successful, otherwise returning null.
Definition at line 520 of file FileManager.cpp.
References clang::FileEntry::closeFile(), Filename, clang::FileEntryRef::getFileEntry(), clang::FileEntryRef::getName(), clang::FileEntry::getSize(), and clang::FileEntry::isNamedPipe().
Referenced by clang::extractapi::APIIgnoresList::create(), clang::HeaderMap::Create(), clang::DumpModuleInfoAction::ExecuteAction(), clang::PrintPreambleAction::ExecuteAction(), clang::SrcMgr::ContentCache::getBufferOrNone(), clang::ASTReader::getOriginalSourceFile(), clang::ASTReader::readASTFileControlBlock(), clang::serialized_diags::SerializedDiagnosticReader::readDiagnostics(), and clang::BackendConsumer::ReloadModules().
getBufferForFile() [2/2]
llvm::ErrorOr<std::unique_ptr<llvm::MemoryBuffer> > clang::FileManager::getBufferForFile (StringRef Filename, bool isVolatile = false, bool RequiresNullTerminator = true) const inline
Definition at line 285 of file FileManager.h.
References Filename.
getBypassFile()
OptionalFileEntryRef FileManager::getBypassFile (FileEntryRef VFE)
Retrieve a FileEntry that bypasses VFE, which is expected to be a virtual file entry, to access the real file.
The returned FileEntry will have the same filename as FE but a different identity and its own stat.
This should be used only for rare error recovery paths because it bypasses all mapping and uniquing, blindly creating a new FileEntry. There is no attempt to deduplicate these; if you bypass the same file twice, you get two new file entries.
Definition at line 455 of file FileManager.cpp.
Referenced by clang::SourceManager::bypassFileContentsOverride().
getCanonicalName() [1/2]
StringRef FileManager::getCanonicalName (DirectoryEntryRef Dir)
Retrieve the canonical name for a given directory.
This is a very expensive operation, despite its results being cached, and should only be used when the physical layout of the file system is required, which is (almost) never.
Definition at line 613 of file FileManager.cpp.
References clang::DirectoryEntryRef::getName().
Referenced by clang::ModuleMap::canonicalizeModuleMapPath(), getCanonicalName(), and getTopFrameworkDir().
getCanonicalName() [2/2]
StringRef FileManager::getCanonicalName (FileEntryRef File)
Retrieve the canonical name for a given file.
This is a very expensive operation, despite its results being cached, and should only be used when the physical layout of the file system is required, which is (almost) never.
Definition at line 617 of file FileManager.cpp.
References clang::File, and getCanonicalName().
getDirectory()
llvm::ErrorOr< const DirectoryEntry * > FileManager::getDirectory (StringRef DirName, bool CacheFailure = true)
Lookup, cache, and verify the specified directory (real or virtual).
This function is deprecated and will be removed at some point in the future, new clients should use getDirectoryRef.
This returns a std::error_code if there was an error reading the directory. If there is no error, the DirectoryEntry is guaranteed to be non-NULL.
Parameters
CacheFailure If true and the file does not exist, we'll cache the failure to find this file.
Definition at line 188 of file FileManager.cpp.
References getDirectoryRef().
Referenced by computeRelativePath().
getDirectoryRef()
llvm::Expected< DirectoryEntryRef > FileManager::getDirectoryRef (StringRef DirName, bool CacheFailure = true)
Lookup, cache, and verify the specified directory (real or virtual).
This returns a std::error_code if there was an error reading the directory. On success, returns the reference to the directory entry together with the exact path that was used to access a file by a particular call to getDirectoryRef.
Parameters
CacheFailure If true and the file does not exist, we'll cache the failure to find this file.
Definition at line 118 of file FileManager.cpp.
Referenced by clang::ModuleMap::canonicalizeModuleMapPath(), getDirectory(), getDirectoryFromFile(), and getOptionalDirectoryRef().
getFile()
llvm::ErrorOr< const FileEntry * > FileManager::getFile (StringRef Filename, bool OpenFile = false, bool CacheFailure = true)
Lookup, cache, and verify the specified file (real or virtual).
This function is deprecated and will be removed at some point in the future, new clients should use getFileRef.
This returns a std::error_code if there was an error loading the file. If there is no error, the FileEntry is guaranteed to be non-NULL.
Parameters
OpenFile if true and the file exists, it will be opened.
CacheFailure If true and the file does not exist, we'll cache the failure to find this file.
Definition at line 196 of file FileManager.cpp.
References Filename, and getFileRef().
Referenced by clang::BackendConsumer::getBestLocationFromDebugLoc(), clang::tooling::groupReplacementsByFile(), and clang::RewriteIncludesAction::RewriteImportsListener::visitModuleFile().
getFileRef()
llvm::Expected< FileEntryRef > FileManager::getFileRef (StringRef Filename, bool OpenFile = false, bool CacheFailure = true)
Lookup, cache, and verify the specified file (real or virtual).
Return the reference to the file entry together with the exact path that was used to access a file by a particular call to getFileRef. If the underlying VFS is a redirecting VFS that uses external file names, the returned FileEntryRef will use the external name instead of the filename that was passed to this method.
This returns a std::error_code if there was an error loading the file, or a FileEntryRef otherwise.
Parameters
OpenFile if true and the file exists, it will be opened.
CacheFailure If true and the file does not exist, we'll cache the failure to find this file.
Definition at line 204 of file FileManager.cpp.
References Filename, and getDirectoryFromFile().
Referenced by getFile(), getOptionalFileRef(), and clang::CompilerInstance::InitializeSourceManager().
getFileSystemOpts() [1/2]
FileSystemOptions& clang::FileManager::getFileSystemOpts () inline
Returns the current file system options.
Definition at line 242 of file FileManager.h.
Referenced by clang::ASTUnit::LoadFromCompilerInvocation(), and clang::tooling::ToolInvocation::run().
getFileSystemOpts() [2/2]
const FileSystemOptions& clang::FileManager::getFileSystemOpts () const inline
Definition at line 243 of file FileManager.h.
getNoncachedStatValue()
std::error_code FileManager::getNoncachedStatValue (StringRef Path, llvm::vfs::Status & Result)
Get the 'stat' information for the given Path.
If the path is relative, it will be resolved against the WorkingDir of the FileManager's FileSystemOptions.
Returns
a std::error_code describing an error, if there was one
Definition at line 583 of file FileManager.cpp.
getNumUniqueRealFiles()
size_t clang::FileManager::getNumUniqueRealFiles () const inline
Returns the number of unique real file entries cached by the file manager.
Definition at line 153 of file FileManager.h.
getOptionalDirectoryRef()
OptionalDirectoryEntryRef clang::FileManager::getOptionalDirectoryRef (StringRef DirName, bool CacheFailure = true) inline
Get a DirectoryEntryRef if it exists, without doing anything on error.
Definition at line 169 of file FileManager.h.
References getDirectoryRef().
Referenced by clang::ApplyHeaderSearchOptions(), clang::FrontendAction::BeginSourceFile(), collectIncludePCH(), clang::api_notes::APINotesManager::getCurrentModuleAPINotes(), getTopFrameworkDir(), clang::HeaderSearch::hasModuleMap(), clang::HeaderSearch::loadModuleMapFile(), loadModuleMapForModuleBuild(), clang::Preprocessor::LookupFile(), and clang::HeaderSearch::LookupSubframeworkHeader().
getOptionalFileRef()
OptionalFileEntryRef clang::FileManager::getOptionalFileRef (StringRef Filename, bool OpenFile = false, bool CacheFailure = true) inline
Get a FileEntryRef if it exists, without doing anything on error.
Definition at line 234 of file FileManager.h.
References Filename, and getFileRef().
Referenced by clang::tooling::applyAllReplacements(), clang::FrontendAction::BeginSourceFile(), clang::PrecompiledPreamble::Build(), EnableCodeCompletion(), clang::installapi::findLibrary(), getPrivateModuleMap(), getPublicModuleMap(), clang::Module::getTopHeaders(), clang::ASTImporter::Import(), InitializeFileRemapping(), clang::DirectoryLookup::LookupFile(), clang::serialization::ModuleManager::lookupModuleFile(), clang::HeaderSearch::lookupModuleMapFile(), clang::HeaderSearch::LookupSubframeworkHeader(), prepareToBuildModule(), and clang::serialization::reader::HeaderFileInfoTrait::ReadData().
getSTDIN()
llvm::Expected< FileEntryRef > FileManager::getSTDIN ()
Get the FileEntryRef for stdin, returning an error if stdin cannot be read.
This reads and caches stdin before returning. Subsequent calls return the same file entry, and a reference to the cached input is returned by calls to getBufferForFile.
Definition at line 347 of file FileManager.cpp.
References clang::FileEntryRef::getFileEntry(), and getVirtualFileRef().
Referenced by clang::CompilerInstance::InitializeSourceManager(), and clang::serialization::ModuleManager::lookupModuleFile().
GetUniqueIDMapping()
void FileManager::GetUniqueIDMapping (SmallVectorImpl< OptionalFileEntryRef > & UIDToFiles) const
Produce an array mapping from the unique IDs assigned to each file to the corresponding FileEntryRef.
Definition at line 595 of file FileManager.cpp.
References clang::FileEntryRef::getName(), and clang::FileEntryRef::getUID().
getVirtualFile()
const FileEntry * FileManager::getVirtualFile (StringRef Filename, off_t Size, time_t ModificationTime)
Definition at line 373 of file FileManager.cpp.
References Filename, clang::FileEntryRef::getFileEntry(), and getVirtualFileRef().
Referenced by clang::serialization::ModuleManager::addInMemoryBuffer(), and InitializeFileRemapping().
getVirtualFileRef()
FileEntryRef FileManager::getVirtualFileRef (StringRef Filename, off_t Size, time_t ModificationTime)
Retrieve a file entry for a "virtual" file that acts as if there were a file with the given name on disk.
The file itself is not accessed.
Definition at line 378 of file FileManager.cpp.
References Filename, and getDirectoryFromFile().
Referenced by getSTDIN(), getVirtualFile(), InitializeFileRemapping(), and clang::HeaderSearch::loadModuleMapFile().
getVirtualFileSystem()
llvm::vfs::FileSystem& clang::FileManager::getVirtualFileSystem () const inline
Definition at line 245 of file FileManager.h.
Referenced by clang::HeaderSearch::collectVFSUsageAndClear(), clang::CompilerInstance::getVirtualFileSystem(), and clang::tooling::ToolInvocation::run().
getVirtualFileSystemPtr()
llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem> clang::FileManager::getVirtualFileSystemPtr () const inline
Definition at line 247 of file FileManager.h.
Referenced by clang::CodeGenAction::ExecuteAction().
makeAbsolutePath()
bool FileManager::makeAbsolutePath (SmallVectorImpl< char > & Path) const
Makes Path absolute taking into account FileSystemOptions and the working directory option.
Returns
true if Path changed to absolute.
Definition at line 497 of file FileManager.cpp.
References FixupRelativePath().
Referenced by cleanPathForOutput(), makeAbsoluteAndPreferred(), and clang::Rewriter::overwriteChangedFiles().
PrintStats()
void FileManager::PrintStats () const
Definition at line 659 of file FileManager.cpp.
setStatCache()
void FileManager::setStatCache (std::unique_ptr< FileSystemStatCache > statCache)
Installs the provided FileSystemStatCache object within the FileManager.
Ownership of this object is transferred to the FileManager.
Parameters
statCache the new stat cache to install. Ownership of this object is transferred to the FileManager.
Definition at line 64 of file FileManager.cpp.
setVirtualFileSystem()
void clang::FileManager::setVirtualFileSystem (IntrusiveRefCntPtr< llvm::vfs::FileSystem > FS) inline
Definition at line 255 of file FileManager.h.
trackVFSUsage()
void FileManager::trackVFSUsage (bool Active)
Enable or disable tracking of VFS usage.
Used to not track full header search and implicit modulemap lookup.
Definition at line 366 of file FileManager.cpp.
The documentation for this class was generated from the following files:
include/clang/Basic/FileManager.h
lib/Basic/FileManager.cpp