clang: SYCLKernelNameTypePrinter Class Reference
SYCLKernelNameTypePrinter Class Reference
Public Member Functions
SYCLKernelNameTypePrinter (raw_ostream &OS, PrintingPolicy &Policy)
void Visit (QualType T)
void VisitType (const Type *T)
void Visit (const TemplateArgument &TA)
void VisitTagType (const TagType *T)
void VisitTemplateArgument (const TemplateArgument &TA)
void VisitTypeTemplateArgument (const TemplateArgument &TA)
void VisitIntegralTemplateArgument (const TemplateArgument &TA)
void VisitTemplateTemplateArgument (const TemplateArgument &TA)
void VisitPackTemplateArgument (const TemplateArgument &TA)
Public Member Functions inherited from clang::TypeVisitor< SYCLKernelNameTypePrinter >
void Visit (const Type *T)
Performs the operation associated with this visitor object.
void VisitType (const Type *)
Method called if ImpClass doesn't provide specific handler for some type class.
Public Member Functions inherited from clang::templateargumentvisitor::Base< Ref, ImplClass, RetTy, ParamTys >
RetTy Visit (REF(TemplateArgument) TA, ParamTys... P)
VISIT_METHOD (Null)
VISIT_METHOD (Type)
VISIT_METHOD (Declaration)
VISIT_METHOD (NullPtr)
VISIT_METHOD (Integral)
VISIT_METHOD (StructuralValue)
VISIT_METHOD (Template)
VISIT_METHOD (TemplateExpansion)
VISIT_METHOD (Expression)
VISIT_METHOD (Pack)
RetTy VisitTemplateArgument (REF(TemplateArgument), ParamTys...)
Detailed Description
Definition at line 5035 of file SemaSYCL.cpp.
Constructor & Destructor Documentation
SYCLKernelNameTypePrinter()
SYCLKernelNameTypePrinter::SYCLKernelNameTypePrinter (raw_ostream & OS, PrintingPolicy & Policy) inline
Definition at line 5076 of file SemaSYCL.cpp.
Member Function Documentation
Visit() [1/2]
void SYCLKernelNameTypePrinter::Visit (const TemplateArgument & TA) inline
Definition at line 5093 of file SemaSYCL.cpp.
References clang::TemplateArgument::isNull().
Visit() [2/2]
void SYCLKernelNameTypePrinter::Visit (QualType T) inline
Definition at line 5079 of file SemaSYCL.cpp.
References clang::QualType::getQualifiers(), clang::QualType::getTypePtr(), and clang::T.
Referenced by clang::SYCLIntegrationHeader::emit().
VisitIntegralTemplateArgument()
void SYCLKernelNameTypePrinter::VisitIntegralTemplateArgument (const TemplateArgument & TA) inline
Definition at line 5141 of file SemaSYCL.cpp.
References clang::Type::getAs(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getIntegralType(), clang::TemplateArgument::print(), and clang::T.
VisitPackTemplateArgument()
void SYCLKernelNameTypePrinter::VisitPackTemplateArgument (const TemplateArgument & TA) inline
Definition at line 5159 of file SemaSYCL.cpp.
References clang::TemplateArgument::getPackAsArray(), and printTemplateArgs().
VisitTagType()
void SYCLKernelNameTypePrinter::VisitTagType (const TagType * T) inline
Definition at line 5099 of file SemaSYCL.cpp.
References clang::Decl::getDeclContext(), clang::NamespaceDecl::isAnonymousNamespace(), clang::TagDecl::printName(), clang::NamedDecl::printQualifiedName(), printTemplateArgs(), and clang::T.
VisitTemplateArgument()
void SYCLKernelNameTypePrinter::VisitTemplateArgument (const TemplateArgument & TA) inline
Definition at line 5130 of file SemaSYCL.cpp.
References clang::TemplateArgument::print().
VisitTemplateTemplateArgument()
void SYCLKernelNameTypePrinter::VisitTemplateTemplateArgument (const TemplateArgument & TA) inline
Definition at line 5154 of file SemaSYCL.cpp.
References clang::TemplateArgument::getAsTemplate(), clang::TemplateName::getAsTemplateDecl(), and clang::NamedDecl::printQualifiedName().
VisitType()
void SYCLKernelNameTypePrinter::VisitType (const Type * T) inline
Definition at line 5089 of file SemaSYCL.cpp.
References clang::QualType::getAsString(), and clang::T.
VisitTypeTemplateArgument()
void SYCLKernelNameTypePrinter::VisitTypeTemplateArgument (const TemplateArgument & TA) inline
Definition at line 5134 of file SemaSYCL.cpp.
References clang::TemplateArgument::getAsType(), clang::PrintingPolicy::SuppressTagKeyword, and clang::T.
The documentation for this class was generated from the following file:
lib/Sema/SemaSYCL.cpp