clang: clang::SemaSYCL Class Reference
clang::SemaSYCL Class Reference
#include "clang/Sema/SemaSYCL.h"
Public Types
enum SYCLRestrictKind {
KernelGlobalVariable , KernelRTTI , KernelNonConstStaticDataVariable , KernelCallVirtualFunction ,
KernelUseExceptions , KernelCallRecursiveFunction , KernelCallFunctionPointer , KernelAllocateStorage ,
KernelUseAssembly , KernelCallDllimportFunction , KernelCallVariadicFunction , KernelCallUndefinedFunction ,
KernelConstStaticVariable
}
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Member Functions
SemaSYCL (Sema &S)
void CheckSYCLKernelCall (FunctionDecl *CallerFunc, ArrayRef< const Expr * > Args)
SemaDiagnosticBuilder DiagIfDeviceCode (SourceLocation Loc, unsigned DiagID, DeviceDiagnosticReason Reason=DeviceDiagnosticReason::Sycl|DeviceDiagnosticReason::Esimd)
Creates a SemaDiagnosticBuilder that emits the diagnostic if the current context is "used as device code".
void deepTypeCheckForDevice (SourceLocation UsedAt, llvm::DenseSet< QualType > Visited, ValueDecl *DeclToCheck)
void addSyclOpenCLKernel (const FunctionDecl *SyclKernel, FunctionDecl *OpenCLKernel)
void addSyclDeviceDecl (Decl *d)
llvm::SetVector< Decl * > & syclDeviceDecls ()
SYCLIntegrationHeader & getSyclIntegrationHeader ()
Lazily creates and returns SYCL integration header instance.
SYCLIntegrationFooter & getSyclIntegrationFooter ()
void addSyclVarDecl (VarDecl *VD)
bool hasSyclIntegrationHeader ()
bool hasSyclIntegrationFooter ()
bool isDeclAllowedInSYCLDeviceCode (const Decl *D)
void checkSYCLDeviceVarDecl (VarDecl *Var)
void copySYCLKernelAttrs (CXXMethodDecl *CallOperator)
void ConstructOpenCLKernel (FunctionDecl *KernelCallerFunc, MangleContext &MC)
void SetSYCLKernelNames ()
void MarkDevices ()
ExprResult ActOnSYCLBuiltinNumFieldsExpr (ParsedType PT)
Get the number of fields or captures within the parsed type.
ExprResult BuildSYCLBuiltinNumFieldsExpr (SourceLocation Loc, QualType SourceTy)
ExprResult ActOnSYCLBuiltinFieldTypeExpr (ParsedType PT, Expr *Idx)
Get a value based on the type of the given field number so that callers can wrap it in a decltype() to get the actual type of the field.
ExprResult BuildSYCLBuiltinFieldTypeExpr (SourceLocation Loc, QualType SourceTy, Expr *Idx)
ExprResult ActOnSYCLBuiltinNumBasesExpr (ParsedType PT)
Get the number of base classes within the parsed type.
ExprResult BuildSYCLBuiltinNumBasesExpr (SourceLocation Loc, QualType SourceTy)
ExprResult ActOnSYCLBuiltinBaseTypeExpr (ParsedType PT, Expr *Idx)
Get a value based on the type of the given base number so that callers can wrap it in a decltype() to get the actual type of the base class.
ExprResult BuildSYCLBuiltinBaseTypeExpr (SourceLocation Loc, QualType SourceTy, Expr *Idx)
bool checkAllowedSYCLInitializer (VarDecl *VD)
void finalizeSYCLDelayedAnalysis (const FunctionDecl *Caller, const FunctionDecl *Callee, SourceLocation Loc, DeviceDiagnosticReason Reason)
Finishes analysis of the deferred functions calls that may be not properly declared for device compilation.
bool isSYCLEsimdPrivateGlobal (VarDecl *VDecl)
Tells whether given variable is a SYCL explicit SIMD extension's "private global" variable - global variable in the private address space.
ExprResult BuildUniqueStableIdExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, Expr *E)
ExprResult ActOnUniqueStableIdExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, Expr *E)
ExprResult BuildUniqueStableNameExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, TypeSourceInfo *TSI)
ExprResult ActOnUniqueStableNameExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, ParsedType ParsedTy)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
Static Public Member Functions
template<typename AttrTy >
static bool isTypeDecoratedWithDeclAttribute (QualType Ty)
static bool isSyclType (QualType Ty, SYCLTypeAttr::SYCLType TypeName)
Check whether Ty corresponds to a SYCL type of name TypeName.
Additional Inherited Members
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 216 of file SemaSYCL.h.
Member Enumeration Documentation
SYCLRestrictKind
enum clang::SemaSYCL::SYCLRestrictKind
Enumerator
KernelGlobalVariable
KernelRTTI
KernelNonConstStaticDataVariable
KernelCallVirtualFunction
KernelUseExceptions
KernelCallRecursiveFunction
KernelCallFunctionPointer
KernelAllocateStorage
KernelUseAssembly
KernelCallDllimportFunction
KernelCallVariadicFunction
KernelCallUndefinedFunction
KernelConstStaticVariable
Definition at line 299 of file SemaSYCL.h.
Constructor & Destructor Documentation
SemaSYCL()
SemaSYCL::SemaSYCL (Sema & S)
Definition at line 401 of file SemaSYCL.cpp.
Member Function Documentation
ActOnSYCLBuiltinBaseTypeExpr()
ExprResult SemaSYCL::ActOnSYCLBuiltinBaseTypeExpr (ParsedType PT, Expr * Idx)
Get a value based on the type of the given base number so that callers can wrap it in a decltype() to get the actual type of the base class.
Definition at line 246 of file SemaSYCL.cpp.
References clang::TypeLoc::getBeginLoc(), and clang::TypeSourceInfo::getTypeLoc().
ActOnSYCLBuiltinFieldTypeExpr()
ExprResult SemaSYCL::ActOnSYCLBuiltinFieldTypeExpr (ParsedType PT, Expr * Idx)
Get a value based on the type of the given field number so that callers can wrap it in a decltype() to get the actual type of the field.
Definition at line 140 of file SemaSYCL.cpp.
References clang::TypeLoc::getBeginLoc(), clang::Sema::GetTypeFromParser(), and clang::TypeSourceInfo::getTypeLoc().
ActOnSYCLBuiltinNumBasesExpr()
ExprResult SemaSYCL::ActOnSYCLBuiltinNumBasesExpr (ParsedType PT)
Get the number of base classes within the parsed type.
Definition at line 219 of file SemaSYCL.cpp.
References clang::TypeLoc::getBeginLoc(), clang::Sema::GetTypeFromParser(), and clang::TypeSourceInfo::getTypeLoc().
ActOnSYCLBuiltinNumFieldsExpr()
ExprResult SemaSYCL::ActOnSYCLBuiltinNumFieldsExpr (ParsedType PT)
Get the number of fields or captures within the parsed type.
Definition at line 113 of file SemaSYCL.cpp.
References clang::TypeLoc::getBeginLoc(), clang::Sema::GetTypeFromParser(), and clang::TypeSourceInfo::getTypeLoc().
ActOnUniqueStableIdExpr()
ExprResult SemaSYCL::ActOnUniqueStableIdExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, Expr * E)
Definition at line 5839 of file SemaSYCL.cpp.
References BuildUniqueStableIdExpr().
ActOnUniqueStableNameExpr()
ExprResult SemaSYCL::ActOnUniqueStableNameExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, ParsedType ParsedTy)
Definition at line 5853 of file SemaSYCL.cpp.
References BuildUniqueStableNameExpr(), clang::ExprError(), clang::SemaBase::getASTContext(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::Sema::GetTypeFromParser(), clang::QualType::isNull(), and clang::SemaBase::SemaRef.
addSyclDeviceDecl()
void clang::SemaSYCL::addSyclDeviceDecl (Decl * d) inline
Definition at line 275 of file SemaSYCL.h.
addSyclOpenCLKernel()
void clang::SemaSYCL::addSyclOpenCLKernel (const FunctionDecl * SyclKernel, FunctionDecl * OpenCLKernel) inline
Definition at line 270 of file SemaSYCL.h.
addSyclVarDecl()
void clang::SemaSYCL::addSyclVarDecl (VarDecl * VD) inline
Definition at line 291 of file SemaSYCL.h.
References clang::SYCLIntegrationFooter::addVarDecl(), clang::SemaBase::getLangOpts(), and getSyclIntegrationFooter().
Referenced by clang::Sema::BuildVarTemplateInstantiation().
BuildSYCLBuiltinBaseTypeExpr()
ExprResult SemaSYCL::BuildSYCLBuiltinBaseTypeExpr (SourceLocation Loc, QualType SourceTy, Expr * Idx)
Definition at line 255 of file SemaSYCL.cpp.
References Diag(), clang::ExprError(), clang::Type::getAsCXXRecordDecl(), clang::Expr::getIntegerConstantExpr(), clang::Type::isDependentType(), clang::Type::isRecordType(), and clang::Expr::isValueDependent().
BuildSYCLBuiltinFieldTypeExpr()
ExprResult SemaSYCL::BuildSYCLBuiltinFieldTypeExpr (SourceLocation Loc, QualType SourceTy, Expr * Idx)
Definition at line 149 of file SemaSYCL.cpp.
References Diag(), clang::ExprError(), clang::Type::getAsRecordDecl(), clang::Expr::getIntegerConstantExpr(), clang::Type::isDependentType(), clang::Type::isRecordType(), clang::Expr::isValueDependent(), and clang::VK_PRValue.
BuildSYCLBuiltinNumBasesExpr()
ExprResult SemaSYCL::BuildSYCLBuiltinNumBasesExpr (SourceLocation Loc, QualType SourceTy)
Definition at line 228 of file SemaSYCL.cpp.
References Diag(), clang::ExprError(), clang::Type::isDependentType(), and clang::Type::isRecordType().
BuildSYCLBuiltinNumFieldsExpr()
ExprResult SemaSYCL::BuildSYCLBuiltinNumFieldsExpr (SourceLocation Loc, QualType SourceTy)
Definition at line 122 of file SemaSYCL.cpp.
References Diag(), clang::ExprError(), clang::Type::isDependentType(), and clang::Type::isRecordType().
BuildUniqueStableIdExpr()
ExprResult SemaSYCL::BuildUniqueStableIdExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, Expr * E)
Definition at line 5807 of file SemaSYCL.cpp.
References clang::SYCLUniqueStableIdExpr::Create(), clang::SemaBase::Diag(), clang::ExprError(), clang::SemaBase::getASTContext(), clang::Expr::getExprLoc(), clang::Expr::IgnoreUnlessSpelledInSource(), and clang::Expr::isInstantiationDependent().
Referenced by ActOnUniqueStableIdExpr().
BuildUniqueStableNameExpr()
ExprResult SemaSYCL::BuildUniqueStableNameExpr (SourceLocation OpLoc, SourceLocation LParen, SourceLocation RParen, TypeSourceInfo * TSI)
Definition at line 5845 of file SemaSYCL.cpp.
References clang::SYCLUniqueStableNameExpr::Create(), and clang::SemaBase::getASTContext().
Referenced by ActOnUniqueStableNameExpr().
checkAllowedSYCLInitializer()
bool SemaSYCL::checkAllowedSYCLInitializer (VarDecl * VD)
Definition at line 4762 of file SemaSYCL.cpp.
References clang::SemaBase::getASTContext(), clang::VarDecl::getInit(), clang::SemaBase::getLangOpts(), clang::VarDecl::hasGlobalStorage(), clang::VarDecl::hasInit(), clang::VarDecl::isConstexpr(), and clang::Decl::isInvalidDecl().
checkSYCLDeviceVarDecl()
void SemaSYCL::checkSYCLDeviceVarDecl (VarDecl * Var)
Definition at line 478 of file SemaSYCL.cpp.
References checkSYCLType(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::ValueDecl::getType(), and Visited.
CheckSYCLKernelCall()
void SemaSYCL::CheckSYCLKernelCall (FunctionDecl * CallerFunc, ArrayRef< const Expr * > Args)
Definition at line 4080 of file SemaSYCL.cpp.
References calculateKernelNameType(), clang::CXXRecordDecl::captures(), clang::SemaBase::Diag(), clang::Type::getAsCXXRecordDecl(), clang::SemaBase::getASTContext(), clang::QualType::getCanonicalType(), clang::Decl::getLocation(), clang::FunctionDecl::getParamDecl(), GetSYCLKernelObjectType(), clang::ValueDecl::getType(), clang::CXXRecordDecl::hasDefinition(), clang::Decl::isInvalidDecl(), clang::CXXRecordDecl::isLambda(), clang::Type::isReferenceType(), SYCLKernelNameTypeVisitor::isValid(), clang::Sema::LangOpts, clang::SemaBase::SemaRef, clang::Decl::setInvalidDecl(), clang::LangOptionsBase::SYCL_2017, clang::LangOptionsBase::SYCL_2020, and SYCLKernelNameTypeVisitor::Visit().
ConstructOpenCLKernel()
void SemaSYCL::ConstructOpenCLKernel (FunctionDecl * KernelCallerFunc, MangleContext & MC)
Definition at line 4243 of file SemaSYCL.cpp.
References calculateKernelNameType(), constructKernelName(), copySYCLKernelAttrs(), clang::Type::getAsCXXRecordDecl(), clang::SemaBase::getASTContext(), clang::CXXRecordDecl::getLambdaCallOperator(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), getSyclIntegrationFooter(), getSyclIntegrationHeader(), getSyclKernelHandlerArg(), GetSYCLKernelObjectType(), clang::ValueDecl::getType(), clang::FunctionDecl::isInlined(), clang::Decl::isInvalidDecl(), and clang::CXXRecordDecl::isLambda().
copySYCLKernelAttrs()
void SemaSYCL::copySYCLKernelAttrs (CXXMethodDecl * CallOperator)
Definition at line 4149 of file SemaSYCL.cpp.
References clang::Decl::addAttr(), clang::CallGraph::addToCallGraph(), collectSYCLAttributes(), clang::CallGraph::getNode(), isSYCLKernelBodyFunction(), and Visited.
Referenced by ConstructOpenCLKernel().
deepTypeCheckForDevice()
void SemaSYCL::deepTypeCheckForDevice (SourceLocation UsedAt, llvm::DenseSet< QualType > Visited, ValueDecl * DeclToCheck)
Definition at line 4637 of file SemaSYCL.cpp.
References DiagIfDeviceCode(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::Type::isPointerType(), and isZeroSizedArray().
DiagIfDeviceCode()
Sema::SemaDiagnosticBuilder SemaSYCL::DiagIfDeviceCode (SourceLocation Loc, unsigned DiagID, DeviceDiagnosticReason Reason = DeviceDiagnosticReason::Sycl | DeviceDiagnosticReason::Esimd)
Creates a SemaDiagnosticBuilder that emits the diagnostic if the current context is "used as device code".
If CurLexicalContext is a kernel function or it is known that the function will be emitted for the device, emits the diagnostics immediately.
If CurLexicalContext is a function and we are compiling for the device, but we don't know that this function will be codegen'ed for device yet, creates a diagnostic which is emitted if and when we realize that the function will be codegen'ed.
Example usage:
Diagnose __float128 type usage only from SYCL device code if the current target doesn't support it if (!S.Context.getTargetInfo().hasFloat128Type() && S.getLangOpts().SYCLIsDevice) DiagIfDeviceCode(Loc, diag::err_type_unsupported) << "__float128";
Definition at line 4613 of file SemaSYCL.cpp.
References clang::Sema::Emitted, clang::Sema::getCurLexicalContext(), clang::Sema::getEmissionReason(), clang::Sema::getEmissionStatus(), clang::SemaBase::getLangOpts(), clang::SemaBase::SemaDiagnosticBuilder::K_Deferred, clang::SemaBase::SemaDiagnosticBuilder::K_ImmediateWithCallStack, clang::SemaBase::SemaDiagnosticBuilder::K_Nop, clang::SemaBase::None, and clang::SemaBase::SemaRef.
Referenced by deepTypeCheckForDevice().
finalizeSYCLDelayedAnalysis()
void SemaSYCL::finalizeSYCLDelayedAnalysis (const FunctionDecl * Caller, const FunctionDecl * Callee, SourceLocation Loc, DeviceDiagnosticReason Reason)
Finishes analysis of the deferred functions calls that may be not properly declared for device compilation.
Definition at line 4729 of file SemaSYCL.cpp.
References clang::CUDA, clang::SemaBase::Diag(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::Sema::getSourceManager(), clang::SemaBase::isFDReachableFromSyclDevice(), isSYCLUndefinedAllowed(), KernelCallUndefinedFunction, clang::SemaBase::None, clang::SemaBase::SemaRef, and clang::SemaBase::Sycl.
getSyclIntegrationFooter()
SYCLIntegrationFooter& clang::SemaSYCL::getSyclIntegrationFooter () inline
Definition at line 285 of file SemaSYCL.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnitFragment(), addSyclVarDecl(), and ConstructOpenCLKernel().
getSyclIntegrationHeader()
SYCLIntegrationHeader& clang::SemaSYCL::getSyclIntegrationHeader () inline
Lazily creates and returns SYCL integration header instance.
Definition at line 279 of file SemaSYCL.h.
Referenced by clang::Sema::ActOnEndOfTranslationUnitFragment(), ConstructOpenCLKernel(), and SetSYCLKernelNames().
hasSyclIntegrationFooter()
bool clang::SemaSYCL::hasSyclIntegrationFooter () inline
Definition at line 297 of file SemaSYCL.h.
hasSyclIntegrationHeader()
bool clang::SemaSYCL::hasSyclIntegrationHeader () inline
Definition at line 296 of file SemaSYCL.h.
isDeclAllowedInSYCLDeviceCode()
bool SemaSYCL::isDeclAllowedInSYCLDeviceCode (const Decl * D)
Definition at line 375 of file SemaSYCL.cpp.
References clang::CXXLanguageLinkage, clang::DeclContext::getEnclosingNamespaceContext(), clang::IdentifierInfo::isStr(), and clang::DeclContext::isTranslationUnit().
isSYCLEsimdPrivateGlobal()
bool clang::SemaSYCL::isSYCLEsimdPrivateGlobal (VarDecl * VDecl) inline
Tells whether given variable is a SYCL explicit SIMD extension's "private global" variable - global variable in the private address space.
Definition at line 355 of file SemaSYCL.h.
References clang::QualType::getAddressSpace(), clang::SemaBase::getLangOpts(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::VarDecl::hasGlobalStorage(), and clang::sycl_private.
isSyclType()
bool SemaSYCL::isSyclType (QualType Ty, SYCLTypeAttr::SYCLType TypeName) static
Check whether Ty corresponds to a SYCL type of name TypeName.
Definition at line 73 of file SemaSYCL.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::Decl::getAttr(), clang::TemplateDecl::getTemplatedDecl(), and clang::TypeName.
Referenced by clang::SYCLIntegrationFooter::addVarDecl(), getAccessTarget(), getSyclKernelHandlerArg(), isSyclAccessorType(), isSYCLPrivateMemoryVar(), and MarkWIScopeFnVisitor::VisitCXXMemberCallExpr().
isTypeDecoratedWithDeclAttribute()
template<typename AttrTy > static bool clang::SemaSYCL::isTypeDecoratedWithDeclAttribute (QualType Ty) inline static
Definition at line 362 of file SemaSYCL.h.
References clang::Type::getAsCXXRecordDecl(), clang::ClassTemplateDecl::getTemplatedDecl(), and clang::Decl::hasAttr().
MarkDevices()
void SemaSYCL::MarkDevices ()
Definition at line 4585 of file SemaSYCL.cpp.
References CheckSYCL2020Attributes(), clang::Sema::CheckSYCLAddIRAttributesFunctionAttrConflicts(), PropagateAndDiagnoseDeviceAttr(), clang::SemaBase::SemaRef, syclDeviceDecls(), and clang::T.
Referenced by clang::Sema::ActOnEndOfTranslationUnitFragment().
SetSYCLKernelNames()
void SemaSYCL::SetSYCLKernelNames ()
Definition at line 4197 of file SemaSYCL.cpp.
References constructKernelName(), clang::SemaBase::getASTContext(), getSyclIntegrationHeader(), and clang::SYCLIntegrationHeader::updateKernelNames().
Referenced by clang::Sema::ActOnEndOfTranslationUnitFragment().
syclDeviceDecls()
llvm::SetVector<Decl *>& clang::SemaSYCL::syclDeviceDecls () inline
Definition at line 276 of file SemaSYCL.h.
Referenced by MarkDevices().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaSYCL.h
lib/Sema/SemaSYCL.cpp