clang: clang::ASTReader Class Reference
clang::ASTReader Class Reference
Reads an AST files chain containing the contents of a translation unit.
#include "clang/Serialization/ASTReader.h"
Classes
class ListenerScope
RAII object to temporarily add an AST callback listener.
class ModuleDeclIterator
Public Types
enum ASTReadResult {
Success , Failure , Missing , OutOfDate ,
VersionMismatch , ConfigurationMismatch , HadErrors
}
The result of reading the control block of an AST file, which can fail for various reasons.
using RecordData = SmallVector< uint64_t, 64 >
using RecordDataImpl = SmallVectorImpl< uint64_t >
using ModuleFile = serialization::ModuleFile
using ModuleKind = serialization::ModuleKind
using ModuleManager = serialization::ModuleManager
using ModuleIterator = ModuleManager::ModuleIterator
using ModuleConstIterator = ModuleManager::ModuleConstIterator
using ModuleReverseIterator = ModuleManager::ModuleReverseIterator
Public Types inherited from clang::ExternalASTSource
enum ExtKind { EK_Always , EK_Never , EK_ReplyHazy }
Friends
class ASTDeclReader
Types of AST files.
class ASTIdentifierIterator
class ASTRecordReader
class ASTUnit
class ASTWriter
class PCHValidator
class serialization::reader::ASTIdentifierLookupTrait
class serialization::ReadMethodPoolVisitor
class TypeLocReader
Sema-relevant special data
Fields containing data that is used for semantic analysis
enum LoadFailureCapabilities {
ARR_None = 0 , ARR_Missing = 0x1 , ARR_OutOfDate = 0x2 , ARR_VersionMismatch = 0x4 ,
ARR_ConfigurationMismatch = 0x8 , ARR_TreatModuleWithErrorsAsOutOfDate = 0x10
}
Flags that indicate what kind of AST loading failures the client of the AST reader can directly handle.
SmallVector< serialization::GlobalDeclID, 16 > PreloadedDeclIDs
SmallVector< std::pair< llvm::BitstreamCursor, serialization::ModuleFile * >, 8 > CommentsCursors
Cursors for comments blocks.
void ResolveImportedPath (ModuleFile &M, std::string &Filename)
If we are loading a relocatable PCH or module file, and the filename is not an absolute path, add the system or module root to the beginning of the file name.
Decl * getKeyDeclaration (Decl *D)
Returns the first key declaration for the given declaration.
const Decl * getKeyDeclaration (const Decl *D)
template<typename Fn >
void forEachImportedKeyDecl (const Decl *D, Fn Visit)
Run a callback on each imported key declaration of D.
const serialization::reader::DeclContextLookupTable * getLoadedLookupTables (DeclContext *Primary) const
Get the loaded lookup tables for Primary, if any.
llvm::iterator_range< ModuleDeclIterator > getModuleFileLevelDecls (ModuleFile &Mod)
ASTReader (Preprocessor &PP, InMemoryModuleCache &ModuleCache, ASTContext *Context, const PCHContainerReader &PCHContainerRdr, ArrayRef< std::shared_ptr< ModuleFileExtension >> Extensions, StringRef isysroot="", DisableValidationForModuleKind DisableValidationKind=DisableValidationForModuleKind::None, bool AllowASTWithCompilerErrors=false, bool AllowConfigurationMismatch=false, bool ValidateSystemInputs=false, bool ValidateASTInputFilesContent=false, bool UseGlobalIndex=true, std::unique_ptr< llvm::Timer > ReadTimer={})
Load the AST file and validate its contents against the given Preprocessor.
ASTReader (const ASTReader &)=delete
ASTReader & operator= (const ASTReader &)=delete
~ASTReader () override
SourceManager & getSourceManager () const
FileManager & getFileManager () const
DiagnosticsEngine & getDiags () const
ASTReadResult ReadAST (StringRef FileName, ModuleKind Type, SourceLocation ImportLoc, unsigned ClientLoadCapabilities, ModuleFile **NewLoadedModuleFile=nullptr)
Load the AST file designated by the given file name.
void makeModuleVisible (Module *Mod, Module::NameVisibilityKind NameVisibility, SourceLocation ImportLoc)
Make the entities in the given module and any of its (non-explicit) submodules visible to name lookup.
void makeNamesVisible (const HiddenNames &Names, Module *Owner)
Make the names within this set of hidden names visible.
void mergeDefinitionVisibility (NamedDecl *Def, NamedDecl *MergedDef)
Note that MergedDef is a redefinition of the canonical definition Def, so Def should be visible whenever MergedDef is.
std::unique_ptr< ASTReaderListener > takeListener ()
Take the AST callbacks listener.
void setListener (std::unique_ptr< ASTReaderListener > Listener)
Set the AST callbacks listener.
void addListener (std::unique_ptr< ASTReaderListener > L)
Add an AST callback listener.
void setDeserializationListener (ASTDeserializationListener *Listener, bool TakeOwnership=false)
Set the AST deserialization listener.
ASTDeserializationListener * getDeserializationListener ()
Get the AST deserialization listener.
bool hasGlobalIndex () const
Determine whether this AST reader has a global index.
GlobalModuleIndex * getGlobalIndex ()
Return global module index.
void resetForReload ()
Reset reader for a reload try.
bool loadGlobalIndex ()
Attempts to load the global index.
bool isGlobalIndexUnavailable () const
Determine whether we tried to load the global index, but failed, e.g., because it is out-of-date or does not exist.
void InitializeContext ()
Initializes the ASTContext.
void UpdateSema ()
Update the state of Sema after loading some additional modules.
void addInMemoryBuffer (StringRef &FileName, std::unique_ptr< llvm::MemoryBuffer > Buffer)
Add in-memory (virtual file) buffer.
void finalizeForWriting ()
Finalizes the AST reader's state before writing an AST file to disk.
ModuleManager & getModuleManager ()
Retrieve the module manager.
Preprocessor & getPreprocessor () const
Retrieve the preprocessor.
StringRef getOriginalSourceFile ()
Retrieve the name of the original source file name for the primary module file.
const std::string & getSuggestedPredefines ()
Returns the suggested contents of the predefines buffer, which contains a (typically-empty) subset of the predefines build prior to including the precompiled header.
PreprocessedEntity * ReadPreprocessedEntity (unsigned Index) override
Read a preallocated preprocessed entity from the external source.
std::pair< unsigned, unsigned > findPreprocessedEntitiesInRange (SourceRange Range) override
Returns a pair of [Begin, End) indices of preallocated preprocessed entities that Range encompasses.
std::optional< bool > isPreprocessedEntityInFileID (unsigned Index, FileID FID) override
Optionally returns true or false if the preallocated preprocessed entity with index Index came from file FID.
SourceRange ReadSkippedRange (unsigned Index) override
Read a preallocated skipped range from the external source.
HeaderFileInfo GetHeaderFileInfo (FileEntryRef FE) override
Read the header file information for the given file entry.
void ReadPragmaDiagnosticMappings (DiagnosticsEngine &Diag)
unsigned getTotalNumSLocs () const
Returns the number of source locations found in the chain.
unsigned getTotalNumIdentifiers () const
Returns the number of identifiers found in the chain.
unsigned getTotalNumMacros () const
Returns the number of macros found in the chain.
unsigned getTotalNumTypes () const
Returns the number of types found in the chain.
unsigned getTotalNumDecls () const
Returns the number of declarations found in the chain.
unsigned getTotalNumSubmodules () const
Returns the number of submodules known.
unsigned getTotalNumSelectors () const
Returns the number of selectors found in the chain.
unsigned getTotalNumPreprocessedEntities () const
Returns the number of preprocessed entities known to the AST reader.
QualType GetType (serialization::TypeID ID)
Resolve a type ID into a type, potentially building a new type.
QualType getLocalType (ModuleFile &F, unsigned LocalID)
Resolve a local type ID within a given AST file into a type.
serialization::TypeID getGlobalTypeID (ModuleFile &F, unsigned LocalID) const
Map a local type ID within a given AST file into a global type ID.
QualType readType (ModuleFile &F, const RecordData &Record, unsigned &Idx)
Read a type from the current position in the given record, which was read from the given AST file.
serialization::GlobalDeclID getGlobalDeclID (ModuleFile &F, serialization::LocalDeclID LocalID) const
Map from a local declaration ID within a given module to a global declaration ID.
bool isDeclIDFromModule (serialization::GlobalDeclID ID, ModuleFile &M) const
Returns true if global DeclID ID originated from module M.
ModuleFile * getOwningModuleFile (const Decl *D)
Retrieve the module file that owns the given declaration, or NULL if the declaration is not from a module file.
SourceLocation getSourceLocationForDeclID (serialization::GlobalDeclID ID)
Returns the source location for the decl ID.
Decl * GetDecl (serialization::GlobalDeclID ID)
Resolve a declaration ID into a declaration, potentially building a new declaration.
Decl * GetExternalDecl (Decl::DeclID ID) override
Resolve a declaration ID into a declaration, potentially building a new declaration.
Decl * GetExistingDecl (serialization::GlobalDeclID ID)
Resolve a declaration ID into a declaration.
Decl * GetLocalDecl (ModuleFile &F, serialization::LocalDeclID LocalID)
Reads a declaration with the given local ID in the given module.
template<typename T >
T * GetLocalDeclAs (ModuleFile &F, serialization::LocalDeclID LocalID)
Reads a declaration with the given local ID in the given module.
serialization::DeclID mapGlobalIDToModuleFileGlobalID (ModuleFile &M, serialization::GlobalDeclID GlobalID)
Map a global declaration ID into the declaration ID used to refer to this declaration within the given module fule.
serialization::GlobalDeclID ReadDeclID (ModuleFile &F, const RecordData &Record, unsigned &Idx)
Reads a declaration ID from the given position in a record in the given module.
Decl * ReadDecl (ModuleFile &F, const RecordData &R, unsigned &I)
Reads a declaration from the given position in a record in the given module.
template<typename T >
T * ReadDeclAs (ModuleFile &F, const RecordData &R, unsigned &I)
Reads a declaration from the given position in a record in the given module.
void CompleteRedeclChain (const Decl *D) override
If any redeclarations of D have been imported since it was last checked, this digs out those redeclarations and adds them to the redeclaration chain for D.
CXXBaseSpecifier * GetExternalCXXBaseSpecifiers (uint64_t Offset) override
Resolve the offset of a set of C++ base specifiers in the decl stream into an array of specifiers.
Stmt * GetExternalDeclStmt (uint64_t Offset) override
Resolve the offset of a statement into a statement.
bool FindExternalVisibleDeclsByName (const DeclContext *DC, DeclarationName Name) override
Finds all the visible declarations with a given name.
void FindExternalLexicalDecls (const DeclContext *DC, llvm::function_ref< bool(Decl::Kind)> IsKindWeWant, SmallVectorImpl< Decl * > &Decls) override
Read all of the declarations lexically stored in a declaration context.
void FindFileRegionDecls (FileID File, unsigned Offset, unsigned Length, SmallVectorImpl< Decl * > &Decls) override
Get the decls that are contained in a file in the Offset/Length range.
void StartedDeserializing () override
Notify ASTReader that we started deserialization of a decl or type so until FinishedDeserializing is called there may be decls that are initializing.
void FinishedDeserializing () override
Notify ASTReader that we finished the deserialization of a decl or type.
void StartTranslationUnit (ASTConsumer *Consumer) override
Function that will be invoked when we begin parsing a new translation unit involving this external AST source.
void PrintStats () override
Print some statistics about AST usage.
void dump ()
Dump information about the AST reader to standard error.
void getMemoryBufferSizes (MemoryBufferSizes &sizes) const override
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
void InitializeSema (Sema &S) override
Initialize the semantic source with the Sema instance being used to perform semantic analysis on the abstract syntax tree.
void ForgetSema () override
Inform the semantic consumer that Sema is no longer available.
IdentifierInfo * get (StringRef Name) override
Retrieve the IdentifierInfo for the named identifier.
IdentifierIterator * getIdentifiers () override
Retrieve an iterator into the set of all identifiers in all loaded AST files.
void ReadMethodPool (Selector Sel) override
Load the contents of the global method pool for a given selector.
void updateOutOfDateSelector (Selector Sel) override
Load the contents of the global method pool for a given selector if necessary.
void ReadKnownNamespaces (SmallVectorImpl< NamespaceDecl * > &Namespaces) override
Load the set of namespaces that are known to the external source, which will be used during typo correction.
void ReadUndefinedButUsed (llvm::MapVector< NamedDecl *, SourceLocation > &Undefined) override
Load the set of used but not defined functions or variables with internal linkage, or used but not defined internal functions.
void ReadMismatchingDeleteExpressions (llvm::MapVector< FieldDecl *, llvm::SmallVector< std::pair< SourceLocation, bool >, 4 >> &Exprs) override
void ReadTentativeDefinitions (SmallVectorImpl< VarDecl * > &TentativeDefs) override
Read the set of tentative definitions known to the external Sema source.
void ReadUnusedFileScopedDecls (SmallVectorImpl< const DeclaratorDecl * > &Decls) override
Read the set of unused file-scope declarations known to the external Sema source.
void ReadDelegatingConstructors (SmallVectorImpl< CXXConstructorDecl * > &Decls) override
Read the set of delegating constructors known to the external Sema source.
void ReadExtVectorDecls (SmallVectorImpl< TypedefNameDecl * > &Decls) override
Read the set of ext_vector type declarations known to the external Sema source.
void ReadUnusedLocalTypedefNameCandidates (llvm::SmallSetVector< const TypedefNameDecl *, 4 > &Decls) override
Read the set of potentially unused typedefs known to the source.
void ReadDeclsToCheckForDeferredDiags (llvm::SmallSetVector< Decl *, 4 > &Decls) override
Read the set of decls to be checked for deferred diags.
void ReadReferencedSelectors (SmallVectorImpl< std::pair< Selector, SourceLocation >> &Sels) override
void ReadWeakUndeclaredIdentifiers (SmallVectorImpl< std::pair< IdentifierInfo *, WeakInfo >> &WeakIDs) override
void ReadUsedVTables (SmallVectorImpl< ExternalVTableUse > &VTables) override
Read the set of used vtables known to the external Sema source.
void ReadPendingInstantiations (SmallVectorImpl< std::pair< ValueDecl *, SourceLocation >> &Pending) override
void ReadLateParsedTemplates (llvm::MapVector< const FunctionDecl *, std::unique_ptr< LateParsedTemplate >> &LPTMap) override
Read the set of late parsed template functions for this source.
void AssignedLambdaNumbering (const CXXRecordDecl *Lambda) override
Notify the external source that a lambda was assigned a mangling number.
void LoadSelector (Selector Sel)
Load a selector from disk, registering its ID if it exists.
void SetIdentifierInfo (unsigned ID, IdentifierInfo *II)
void SetGloballyVisibleDecls (IdentifierInfo *II, const SmallVectorImpl< serialization::GlobalDeclID > &DeclIDs, SmallVectorImpl< Decl * > *Decls=nullptr)
Set the globally-visible declarations associated with the given identifier.
DiagnosticBuilder Diag (unsigned DiagID) const
Report a diagnostic.
DiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID) const
Report a diagnostic.
IdentifierInfo * DecodeIdentifierInfo (serialization::IdentifierID ID)
IdentifierInfo * readIdentifier (ModuleFile &M, const RecordData &Record, unsigned &Idx)
IdentifierInfo * GetIdentifier (serialization::IdentifierID ID) override
IdentifierInfo * getLocalIdentifier (ModuleFile &M, unsigned LocalID)
serialization::IdentifierID getGlobalIdentifierID (ModuleFile &M, unsigned LocalID)
void resolvePendingMacro (IdentifierInfo *II, const PendingMacroInfo &PMInfo)
MacroInfo * getMacro (serialization::MacroID ID)
Retrieve the macro with the given ID.
serialization::MacroID getGlobalMacroID (ModuleFile &M, unsigned LocalID)
Retrieve the global macro ID corresponding to the given local ID within the given module file.
bool ReadSLocEntry (int ID) override
Read the source location entry with index ID.
int getSLocEntryID (SourceLocation::UIntTy SLocOffset) override
Get the index ID for the loaded SourceLocation offset.
llvm::Expected< SourceLocation::UIntTy > readSLocOffset (ModuleFile *F, unsigned Index)
Try to read the offset of the SLocEntry at the given index in the given module file.
std::pair< SourceLocation, StringRef > getModuleImportLoc (int ID) override
Retrieve the module import location and module name for the given source manager entry ID.
serialization::SubmoduleID getGlobalSubmoduleID (ModuleFile &M, unsigned LocalID)
Retrieve the global submodule ID given a module and its local ID number.
Module * getSubmodule (serialization::SubmoduleID GlobalID)
Retrieve the submodule that corresponds to a global submodule ID.
Module * getModule (unsigned ID) override
Retrieve the module that corresponds to the given module ID.
ModuleFile * getLocalModuleFile (ModuleFile &M, unsigned ID)
Retrieve the module file with a given local ID within the specified ModuleFile.
unsigned getModuleFileID (ModuleFile *M)
Get an ID for the given module file.
std::optional< ASTSourceDescriptor > getSourceDescriptor (unsigned ID) override
Return a descriptor for the corresponding module.
ExtKind hasExternalDefinitions (const Decl *D) override
Selector getLocalSelector (ModuleFile &M, unsigned LocalID)
Retrieve a selector from the given module with its local ID number.
Selector DecodeSelector (serialization::SelectorID Idx)
Selector GetExternalSelector (serialization::SelectorID ID) override
Resolve a selector ID into a selector.
uint32_t GetNumExternalSelectors () override
Returns the number of selectors known to the external AST source.
Selector ReadSelector (ModuleFile &M, const RecordData &Record, unsigned &Idx)
serialization::SelectorID getGlobalSelectorID (ModuleFile &M, unsigned LocalID) const
Retrieve the global selector ID that corresponds to this the local selector ID in a given module.
CXXCtorInitializer ** GetExternalCXXCtorInitializers (uint64_t Offset) override
Read the contents of a CXXCtorInitializer array.
Sema::AlignPackInfo ReadAlignPackInfo (uint32_t Raw) const
Read a AlignPackInfo from raw form.
SourceLocation ReadUntranslatedSourceLocation (SourceLocation::UIntTy Raw, LocSeq *Seq=nullptr) const
Read a source location from raw form and return it in its originating module file's source location space.
SourceLocation ReadSourceLocation (ModuleFile &ModuleFile, SourceLocation::UIntTy Raw, LocSeq *Seq=nullptr) const
Read a source location from raw form.
SourceLocation TranslateSourceLocation (ModuleFile &ModuleFile, SourceLocation Loc) const
Translate a source location from another module file's source location space into ours.
SourceLocation ReadSourceLocation (ModuleFile &ModuleFile, const RecordDataImpl &Record, unsigned &Idx, LocSeq *Seq=nullptr)
Read a source location.
FileID ReadFileID (ModuleFile &F, const RecordDataImpl &Record, unsigned &Idx) const
Read a FileID.
FileID TranslateFileID (ModuleFile &F, FileID FID) const
Translate a FileID from another module file's FileID space into ours.
SourceRange ReadSourceRange (ModuleFile &F, const RecordData &Record, unsigned &Idx, LocSeq *Seq=nullptr)
Read a source range.
std::string ReadPath (ModuleFile &F, const RecordData &Record, unsigned &Idx)
std::string ReadPath (StringRef BaseDirectory, const RecordData &Record, unsigned &Idx)
CXXTemporary * ReadCXXTemporary (ModuleFile &F, const RecordData &Record, unsigned &Idx)
Stmt * ReadStmt (ModuleFile &F)
Reads a statement.
Expr * ReadExpr (ModuleFile &F)
Reads an expression.
Stmt * ReadSubStmt ()
Reads a sub-statement operand during statement reading.
Expr * ReadSubExpr ()
Reads a sub-expression operand during statement reading.
Token ReadToken (ModuleFile &M, const RecordDataImpl &Record, unsigned &Idx)
Reads a token out of a record.
MacroInfo * ReadMacroRecord (ModuleFile &F, uint64_t Offset)
Reads the macro record located at the given offset.
serialization::PreprocessedEntityID getGlobalPreprocessedEntityID (ModuleFile &M, unsigned LocalID) const
Determine the global preprocessed entity ID that corresponds to the given local ID within the given module.
void addPendingMacro (IdentifierInfo *II, ModuleFile *M, uint32_t MacroDirectivesOffset)
Add a macro to deserialize its macro directive history.
void ReadDefinedMacros () override
Read the set of macros defined by this external macro source.
void updateOutOfDateIdentifier (const IdentifierInfo &II) override
Update an out-of-date identifier.
void markIdentifierUpToDate (const IdentifierInfo *II)
Note that this identifier is up-to-date.
void completeVisibleDeclsMap (const DeclContext *DC) override
Load all external visible decls in the given DeclContext.
ASTContext & getContext ()
Retrieve the AST context that this AST reader supplements.
Sema * getSema ()
Retrieve the semantic analysis object used to analyze the translation unit in which the precompiled header is being imported.
IdentifierResolver & getIdResolver ()
Get the identifier resolver used for name lookup / updates in the translation unit scope.
IdentifierTable & getIdentifierTable ()
Retrieve the identifier table associated with the preprocessor.
void RecordSwitchCaseID (SwitchCase *SC, unsigned ID)
Record that the given ID maps to the given switch-case statement.
SwitchCase * getSwitchCaseWithID (unsigned ID)
Retrieve the switch-case statement with the given ID.
void ClearSwitchCaseIDs ()
void ReadComments () override
Loads comments ranges.
void visitInputFileInfos (serialization::ModuleFile &MF, bool IncludeSystem, llvm::function_ref< void(const serialization::InputFileInfo &IFI, bool IsSystem)> Visitor)
Visit all the input file infos of the given module file.
void visitInputFiles (serialization::ModuleFile &MF, bool IncludeSystem, bool Complain, llvm::function_ref< void(const serialization::InputFile &IF, bool isSystem)> Visitor)
Visit all the input files of the given module file.
void visitTopLevelModuleMaps (serialization::ModuleFile &MF, llvm::function_ref< void(FileEntryRef)> Visitor)
Visit all the top-level module maps loaded when building the given module file.
bool isProcessingUpdateRecords ()
static void ResolveImportedPath (std::string &Filename, StringRef Prefix)
static std::string getOriginalSourceFile (const std::string &ASTFileName, FileManager &FileMgr, const PCHContainerReader &PCHContainerRdr, DiagnosticsEngine &Diags)
Retrieve the name of the original source file name directly from the AST file, without actually loading the AST file.
static bool readASTFileControlBlock (StringRef Filename, FileManager &FileMgr, const InMemoryModuleCache &ModuleCache, const PCHContainerReader &PCHContainerRdr, bool FindModuleFileExtensions, ASTReaderListener &Listener, bool ValidateDiagnosticOptions, unsigned ClientLoadCapabilities=ARR_ConfigurationMismatch|ARR_OutOfDate)
Read the control block for the named AST file.
static bool isAcceptableASTFile (StringRef Filename, FileManager &FileMgr, const InMemoryModuleCache &ModuleCache, const PCHContainerReader &PCHContainerRdr, const LangOptions &LangOpts, const TargetOptions &TargetOpts, const PreprocessorOptions &PPOpts, StringRef ExistingModuleCachePath, bool RequireStrictOptionMatches=false)
Determine whether the given AST file is acceptable to load into a translation unit with the given language and target options.
static llvm::Error ReadBlockAbbrevs (llvm::BitstreamCursor &Cursor, unsigned BlockID, uint64_t *StartOfBlockOffset=nullptr)
ReadBlockAbbrevs - Enter a subblock of the specified BlockID with the specified cursor.
static llvm::BitVector ReadBitVector (const RecordData &Record, const StringRef Blob)
static std::string ReadString (const RecordDataImpl &Record, unsigned &Idx)
static void SkipString (const RecordData &Record, unsigned &Idx)
static void SkipPath (const RecordData &Record, unsigned &Idx)
static VersionTuple ReadVersionTuple (const RecordData &Record, unsigned &Idx)
Read a version tuple.
Additional Inherited Members
Public Member Functions inherited from clang::ExternalPreprocessorSource
virtual ~ExternalPreprocessorSource ()
virtual IdentifierInfo * GetIdentifier (unsigned ID)=0
Return the identifier associated with the given ID number.
Public Member Functions inherited from clang::ExternalPreprocessingRecordSource
virtual ~ExternalPreprocessingRecordSource ()
Public Member Functions inherited from clang::ExternalHeaderFileInfoSource
virtual ~ExternalHeaderFileInfoSource ()
Public Member Functions inherited from clang::ExternalSemaSource
ExternalSemaSource ()=default
~ExternalSemaSource () override
virtual bool LookupUnqualified (LookupResult &R, Scope *S)
Do last resort, unqualified lookup on a LookupResult that Sema cannot find.
virtual void ReadReferencedSelectors (SmallVectorImpl< std::pair< Selector, SourceLocation > > &Sels)
Read the set of referenced selectors known to the external Sema source.
virtual void ReadWeakUndeclaredIdentifiers (SmallVectorImpl< std::pair< IdentifierInfo *, WeakInfo > > &WI)
Read the set of weak, undeclared identifiers known to the external Sema source.
virtual void ReadPendingInstantiations (SmallVectorImpl< std::pair< ValueDecl *, SourceLocation > > &Pending)
Read the set of pending instantiations known to the external Sema source.
virtual TypoCorrection CorrectTypo (const DeclarationNameInfo &Typo, int LookupKind, Scope *S, CXXScopeSpec *SS, CorrectionCandidateCallback &CCC, DeclContext *MemberContext, bool EnteringContext, const ObjCObjectPointerType *OPT)
Try to "correct" a typo in the source code by finding visible declarations whose names are similar to the name that was present in the source code.
virtual bool MaybeDiagnoseMissingCompleteType (SourceLocation Loc, QualType T)
Produces a diagnostic note if the external source contains a complete definition for T.
bool isA (const void *ClassID) const override
LLVM-style RTTI.
Public Member Functions inherited from clang::ExternalASTSource
ExternalASTSource ()=default
virtual ~ExternalASTSource ()
uint32_t getGeneration () const
Get the current generation of this AST source.
void FindExternalLexicalDecls (const DeclContext *DC, SmallVectorImpl< Decl * > &Result)
Finds all declarations lexically contained within the given DeclContext.
virtual void CompleteType (TagDecl *Tag)
Gives the external AST source an opportunity to complete an incomplete type.
virtual void CompleteType (ObjCInterfaceDecl *Class)
Gives the external AST source an opportunity to complete an incomplete Objective-C class.
virtual bool layoutRecordType (const RecordDecl *Record, uint64_t &Size, uint64_t &Alignment, llvm::DenseMap< const FieldDecl *, uint64_t > &FieldOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > &BaseOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > &VirtualBaseOffsets)
Perform layout on the given record.
MemoryBufferSizes getMemoryBufferSizes () const
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
Public Member Functions inherited from clang::IdentifierInfoLookup
virtual ~IdentifierInfoLookup ()
Public Member Functions inherited from clang::ExternalSLocEntrySource
virtual ~ExternalSLocEntrySource ()
Static Public Member Functions inherited from clang::ExternalSemaSource
static bool classof (const ExternalASTSource *S)
Static Public Member Functions inherited from clang::ExternalASTSource
static bool classof (const ExternalASTSource *S)
Protected Member Functions inherited from clang::ExternalASTSource
uint32_t incrementGeneration (ASTContext &C)
Increment the current generation.
Static Protected Member Functions inherited from clang::ExternalASTSource
static DeclContextLookupResult SetExternalVisibleDeclsForName (const DeclContext *DC, DeclarationName Name, ArrayRef< NamedDecl * > Decls)
static DeclContextLookupResult SetNoExternalVisibleDeclsForName (const DeclContext *DC, DeclarationName Name)
Detailed Description
Reads an AST files chain containing the contents of a translation unit.
The ASTReader class reads bitstreams (produced by the ASTWriter class) containing the serialized representation of a given abstract syntax tree and its supporting data structures. An instance of the ASTReader can be attached to an ASTContext object, which will provide access to the contents of the AST files.
The AST reader provides lazy de-serialization of declarations, as required when traversing the AST. Only those AST nodes that are actually required will be de-serialized.
Definition at line 359 of file ASTReader.h.
Member Typedef Documentation
ModuleConstIterator
using clang::ASTReader::ModuleConstIterator = ModuleManager::ModuleConstIterator
Definition at line 414 of file ASTReader.h.
ModuleFile
using clang::ASTReader::ModuleFile = serialization::ModuleFile
Definition at line 410 of file ASTReader.h.
ModuleIterator
using clang::ASTReader::ModuleIterator = ModuleManager::ModuleIterator
Definition at line 413 of file ASTReader.h.
ModuleKind
using clang::ASTReader::ModuleKind = serialization::ModuleKind
Definition at line 411 of file ASTReader.h.
ModuleManager
using clang::ASTReader::ModuleManager = serialization::ModuleManager
Definition at line 412 of file ASTReader.h.
ModuleReverseIterator
using clang::ASTReader::ModuleReverseIterator = ModuleManager::ModuleReverseIterator
Definition at line 415 of file ASTReader.h.
RecordData
using clang::ASTReader::RecordData = SmallVector<uint64_t, 64>
Definition at line 379 of file ASTReader.h.
RecordDataImpl
using clang::ASTReader::RecordDataImpl = SmallVectorImpl<uint64_t>
Definition at line 380 of file ASTReader.h.
Member Enumeration Documentation
ASTReadResult
enum clang::ASTReader::ASTReadResult
The result of reading the control block of an AST file, which can fail for various reasons.
Enumerator
Success
The control block was read successfully.
Aside from failures, the AST file is safe to read into the current context.
Failure
The AST file itself appears corrupted.
Missing
The AST file was missing.
OutOfDate
The AST file is out-of-date relative to its input files, and needs to be regenerated.
VersionMismatch
The AST file was written by a different version of Clang.
ConfigurationMismatch
The AST file was written with a different language/target configuration.
HadErrors
The AST file has errors.
Definition at line 384 of file ASTReader.h.
LoadFailureCapabilities
enum clang::ASTReader::LoadFailureCapabilities
Flags that indicate what kind of AST loading failures the client of the AST reader can directly handle.
When a client states that it can handle a particular kind of failure, the AST reader will not emit errors when producing that kind of failure.
Enumerator
ARR_None
The client can't handle any AST loading failures.
ARR_Missing
The client can handle an AST file that cannot load because it is missing.
ARR_OutOfDate
The client can handle an AST file that cannot load because it is out-of-date relative to its input files.
ARR_VersionMismatch
The client can handle an AST file that cannot load because it was built with a different version of Clang.
ARR_ConfigurationMismatch
The client can handle an AST file that cannot load because it's compiled configuration doesn't match that of the context it was loaded into.
ARR_TreatModuleWithErrorsAsOutOfDate
If a module file is marked with errors treat it as out-of-date so the caller can rebuild it.
Definition at line 1621 of file ASTReader.h.
Constructor & Destructor Documentation
ASTReader() [1/2]
ASTReader::ASTReader (Preprocessor & PP, InMemoryModuleCache & ModuleCache, ASTContext * Context, const PCHContainerReader & PCHContainerRdr, ArrayRef< std::shared_ptr< ModuleFileExtension >> Extensions, StringRef isysroot = "", DisableValidationForModuleKind DisableValidationKind = DisableValidationForModuleKind::None, bool AllowASTWithCompilerErrors = false, bool AllowConfigurationMismatch = false, bool ValidateSystemInputs = false, bool ValidateASTInputFilesContent = false, bool UseGlobalIndex = true, std::unique_ptr< llvm::Timer > ReadTimer = {})
Load the AST file and validate its contents against the given Preprocessor.
Parameters
PP the preprocessor associated with the context in which this precompiled header will be loaded.
Context the AST context that this precompiled header will be loaded into, if any.
PCHContainerRdr the PCHContainerOperations to use for loading and creating modules.
Extensions the list of module file extensions that can be loaded from the AST files.
isysroot If non-NULL, the system include path specified by the user. This is only used with relocatable PCH files. If non-NULL, a relocatable PCH file will use the default path "/".
DisableValidationKind If set, the AST reader will suppress most of its regular consistency checking, allowing the use of precompiled headers and module files that cannot be determined to be compatible.
AllowASTWithCompilerErrors If true, the AST reader will accept an AST file the was created out of an AST with compiler errors, otherwise it will reject it.
AllowConfigurationMismatch If true, the AST reader will not check for configuration differences between the AST file and the invocation.
ValidateSystemInputs If true, the AST reader will validate system input files in addition to user input files. This is only meaningful if DisableValidation is false.
UseGlobalIndex If true, the AST reader will try to load and use the global module index.
ReadTimer If non-null, a timer used to track the time spent deserializing.
Definition at line 10220 of file ASTReader.cpp.
ASTReader() [2/2]
clang::ASTReader::ASTReader (const ASTReader &) delete
~ASTReader()
ASTReader::~ASTReader () override
Definition at line 10259 of file ASTReader.cpp.
Member Function Documentation
addInMemoryBuffer()
void clang::ASTReader::addInMemoryBuffer (StringRef & FileName, std::unique_ptr< llvm::MemoryBuffer > Buffer) inline
Add in-memory (virtual file) buffer.
Definition at line 1772 of file ASTReader.h.
References clang::serialization::ModuleManager::addInMemoryBuffer(), and clang::FileName.
addListener()
void clang::ASTReader::addListener (std::unique_ptr< ASTReaderListener > L) inline
Add an AST callback listener.
Takes ownership of L.
Definition at line 1706 of file ASTReader.h.
Referenced by clang::DependencyCollector::attachToASTReader(), and clang::ModuleDependencyCollector::attachToASTReader().
addPendingMacro()
void ASTReader::addPendingMacro (IdentifierInfo * II, ModuleFile * M, uint32_t MacroDirectivesOffset)
Add a macro to deserialize its macro directive history.
Parameters
II The name of the macro.
M The module file.
MacroDirectivesOffset Offset of the serialized macro directive history.
Definition at line 2098 of file ASTReader.cpp.
AssignedLambdaNumbering()
void ASTReader::AssignedLambdaNumbering (const CXXRecordDecl * Lambda) override virtual
Notify the external source that a lambda was assigned a mangling number.
This enables the external source to track the correspondence between lambdas and mangling numbers if necessary.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8812 of file ASTReader.cpp.
References getCanonicalDecl(), clang::CXXRecordDecl::getLambdaContextDecl(), and clang::CXXRecordDecl::getLambdaIndexInContext().
ClearSwitchCaseIDs()
void ASTReader::ClearSwitchCaseIDs ()
Definition at line 9444 of file ASTReader.cpp.
CompleteRedeclChain()
void ASTReader::CompleteRedeclChain (const Decl * D) override virtual
If any redeclarations of D have been imported since it was last checked, this digs out those redeclarations and adds them to the redeclaration chain for D.
Reimplemented from clang::ExternalASTSource.
Definition at line 7531 of file ASTReader.cpp.
References clang::Decl::getDeclContext(), and clang::DeclContext::getRedeclContext().
completeVisibleDeclsMap()
void ASTReader::completeVisibleDeclsMap (const DeclContext * DC) override virtual
Load all external visible decls in the given DeclContext.
Reimplemented from clang::ExternalASTSource.
Definition at line 8015 of file ASTReader.cpp.
References clang::NamedDecl::getDeclName(), clang::DeclContext::hasExternalVisibleStorage(), and ID.
DecodeIdentifierInfo()
IdentifierInfo * ASTReader::DecodeIdentifierInfo (serialization::IdentifierID ID)
Definition at line 8884 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), and clang::ContinuousRangeMap< Int, V, InitialCapacity >::find().
Referenced by GetIdentifier(), getLocalIdentifier(), readIdentifier(), and ReadWeakUndeclaredIdentifiers().
DecodeSelector()
Selector ASTReader::DecodeSelector (serialization::SelectorID Idx)
Definition at line 9068 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseSelectorID, clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::NUM_PREDEF_SELECTOR_IDS, clang::serialization::reader::ASTSelectorLookupTrait::ReadKey(), clang::serialization::ModuleFile::SelectorLookupTableData, clang::serialization::ModuleFile::SelectorOffsets, and clang::ASTDeserializationListener::SelectorRead().
Referenced by GetExternalSelector(), getLocalSelector(), and ReadReferencedSelectors().
Diag() [1/2]
DiagnosticBuilder ASTReader::Diag (SourceLocation Loc, unsigned DiagID) const
Report a diagnostic.
Definition at line 9420 of file ASTReader.cpp.
References clang::DiagnosticsEngine::Report().
Diag() [2/2]
DiagnosticBuilder ASTReader::Diag (unsigned DiagID) const
Report a diagnostic.
Definition at line 9416 of file ASTReader.cpp.
dump()
LLVM_DUMP_METHOD void ASTReader::dump ()
Dump information about the AST reader to standard error.
Definition at line 8185 of file ASTReader.cpp.
References clang::serialization::ModuleFile::dump(), and dumpModuleIDMap().
finalizeForWriting()
void ASTReader::finalizeForWriting ()
Finalizes the AST reader's state before writing an AST file to disk.
This operation may undo temporary state in the AST that should not be emitted.
Definition at line 5241 of file ASTReader.cpp.
FindExternalLexicalDecls()
void ASTReader::FindExternalLexicalDecls (const DeclContext * DC, llvm::function_ref< bool(Decl::Kind)> IsKindWeWant, SmallVectorImpl< Decl * > & Decls) override virtual
Read all of the declarations lexically stored in a declaration context.
Parameters
DC The declaration context whose declarations will be read.
IsKindWeWant A predicate indicating which declaration kinds we are interested in.
Decls Vector that will contain the declarations loaded from the external source. The caller is responsible for merging these declarations with any declarations already stored in the declaration context.
Reimplemented from clang::ExternalASTSource.
Definition at line 7870 of file ASTReader.cpp.
References ID, clang::DeclContext::isDeclInLexicalTraversal(), and clang::serialization::NUM_PREDEF_DECL_IDS.
FindExternalVisibleDeclsByName()
bool ASTReader::FindExternalVisibleDeclsByName (const DeclContext * DC, DeclarationName Name) override virtual
Finds all the visible declarations with a given name.
The current implementation of this method just loads the entire lookup table as unmaterialized references.
Reimplemented from clang::ExternalASTSource.
Definition at line 7988 of file ASTReader.cpp.
FindFileRegionDecls()
void ASTReader::FindFileRegionDecls (FileID File, unsigned Offset, unsigned Length, SmallVectorImpl< Decl * > & Decls) override virtual
Get the decls that are contained in a file in the Offset/Length range.
Length can be 0 to indicate a point at Offset instead of a range.
Reimplemented from clang::ExternalASTSource.
Definition at line 7946 of file ASTReader.cpp.
References clang::File, clang::SourceLocation::getLocWithOffset(), Offset, and SM.
findPreprocessedEntitiesInRange()
std::pair< unsigned, unsigned > ASTReader::findPreprocessedEntitiesInRange (SourceRange Range) override virtual
Returns a pair of [Begin, End) indices of preallocated preprocessed entities that Range encompasses.
Returns a pair of [Begin, End) indices of preallocated preprocessed entities that.
Range encompasses.
Implements clang::ExternalPreprocessingRecordSource.
Definition at line 6470 of file ASTReader.cpp.
FinishedDeserializing()
void ASTReader::FinishedDeserializing () override virtual
Notify ASTReader that we finished the deserialization of a decl or type.
Must be paired with StartedDeserializing.
Reimplemented from clang::ExternalASTSource.
Definition at line 10136 of file ASTReader.cpp.
References clang::ASTContext::adjustDeducedFunctionResultType(), clang::ASTContext::adjustExceptionSpec(), clang::FunctionProtoType::ExtProtoInfo::ExceptionSpec, clang::ASTContext::getASTMutationListener(), getContext(), and clang::FunctionProtoType::getExtProtoInfo().
forEachImportedKeyDecl()
template<typename Fn > void clang::ASTReader::forEachImportedKeyDecl (const Decl * D, Fn Visit) inline
Run a callback on each imported key declaration of D.
Definition at line 1357 of file ASTReader.h.
References clang::Decl::getCanonicalDecl(), GetExistingDecl(), and clang::Decl::isFromASTFile().
ForgetSema()
void clang::ASTReader::ForgetSema () inline override virtual
Inform the semantic consumer that Sema is no longer available.
Reimplemented from clang::ExternalSemaSource.
Definition at line 2069 of file ASTReader.h.
get()
IdentifierInfo * ASTReader::get (StringRef Name) override virtual
Retrieve the IdentifierInfo for the named identifier.
This routine builds a new IdentifierInfo for the given identifier. If any declarations with this name are visible from translation unit scope, their declarations will be deserialized and introduced into the declaration chain of the identifier.
Implements clang::IdentifierInfoLookup.
Definition at line 8352 of file ASTReader.cpp.
getContext()
ASTContext& clang::ASTReader::getContext () inline
Retrieve the AST context that this AST reader supplements.
Definition at line 2379 of file ASTReader.h.
Referenced by clang::ASTDeclReader::attachPreviousDecl(), FinishedDeserializing(), clang::ASTRecordReader::getContext(), clang::index::indexModuleFile(), ReadCXXTemporary(), and clang::ASTDeclReader::UpdateDecl().
GetDecl()
Decl * ASTReader::GetDecl (serialization::GlobalDeclID ID)
Resolve a declaration ID into a declaration, potentially building a new declaration.
Definition at line 7800 of file ASTReader.cpp.
References ID, and clang::serialization::NUM_PREDEF_DECL_IDS.
Referenced by GetLocalDecl(), clang::ASTReader::ModuleDeclIterator::operator*(), ReadDecl(), ReadDeclAs(), ReadDeclsToCheckForDeferredDiags(), ReadDelegatingConstructors(), ReadExtVectorDecls(), ReadKnownNamespaces(), ReadMismatchingDeleteExpressions(), ReadPendingInstantiations(), ReadTentativeDefinitions(), ReadUndefinedButUsed(), ReadUnusedFileScopedDecls(), ReadUnusedLocalTypedefNameCandidates(), ReadUsedVTables(), and SetGloballyVisibleDecls().
getDeserializationListener()
ASTDeserializationListener* clang::ASTReader::getDeserializationListener () inline
Get the AST deserialization listener.
Definition at line 1743 of file ASTReader.h.
getDiags()
DiagnosticsEngine& clang::ASTReader::getDiags () const inline
Definition at line 1614 of file ASTReader.h.
Referenced by clang::TestModuleFileExtension::createExtensionReader().
GetExistingDecl()
Decl * ASTReader::GetExistingDecl (serialization::GlobalDeclID ID)
Resolve a declaration ID into a declaration.
Return 0 if it's not been loaded yet.
Definition at line 7775 of file ASTReader.cpp.
References clang::Decl::getCanonicalDecl(), getPredefinedDecl(), ID, and clang::serialization::NUM_PREDEF_DECL_IDS.
Referenced by forEachImportedKeyDecl(), and getKeyDeclaration().
GetExternalCXXBaseSpecifiers()
CXXBaseSpecifier * ASTReader::GetExternalCXXBaseSpecifiers (uint64_t Offset) override virtual
Resolve the offset of a set of C++ base specifiers in the decl stream into an array of specifiers.
The default implementation of this method is a no-op.
Reimplemented from clang::ExternalASTSource.
Definition at line 7620 of file ASTReader.cpp.
GetExternalCXXCtorInitializers()
CXXCtorInitializer ** ASTReader::GetExternalCXXCtorInitializers (uint64_t Offset) override virtual
Read the contents of a CXXCtorInitializer array.
Reimplemented from clang::ExternalASTSource.
Definition at line 7588 of file ASTReader.cpp.
References clang::serialization::DECL_CXX_CTOR_INITIALIZERS, and Offset.
GetExternalDecl()
Decl * ASTReader::GetExternalDecl (Decl::DeclID ID) override virtual
Resolve a declaration ID into a declaration, potentially building a new declaration.
This method only needs to be implemented if the AST source ever passes back decl sets as VisibleDeclaration objects.
The default implementation of this method is a no-op.
Reimplemented from clang::ExternalASTSource.
Definition at line 7527 of file ASTReader.cpp.
References ID.
GetExternalDeclStmt()
Stmt * ASTReader::GetExternalDeclStmt (uint64_t Offset) override virtual
Resolve the offset of a statement into a statement.
This operation will read a new statement from the external source each time it is called, and is meant to be used via a LazyOffsetPtr (which is used by Decls for the body of functions, etc).
Reimplemented from clang::ExternalASTSource.
Definition at line 7854 of file ASTReader.cpp.
References Offset.
GetExternalSelector()
Selector ASTReader::GetExternalSelector (serialization::SelectorID ID) override virtual
Resolve a selector ID into a selector.
This operation only needs to be implemented if the AST source returns non-zero for GetNumKnownSelectors().
The default implementation of this method is a no-op.
Reimplemented from clang::ExternalASTSource.
Definition at line 9093 of file ASTReader.cpp.
References DecodeSelector().
getFileManager()
FileManager& clang::ASTReader::getFileManager () const inline
Definition at line 1613 of file ASTReader.h.
Referenced by clang::DependencyCollector::attachToASTReader(), and clang::ModuleDependencyCollector::attachToASTReader().
getGlobalDeclID()
GlobalDeclID ASTReader::getGlobalDeclID (ModuleFile & F, serialization::LocalDeclID LocalID) const
Map from a local declaration ID within a given module to a global declaration ID.
Definition at line 7662 of file ASTReader.cpp.
References clang::serialization::ModuleFile::DeclRemap, clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::LocalDeclID::get(), ID, clang::serialization::ModuleFile::ModuleOffsetMap, and clang::serialization::NUM_PREDEF_DECL_IDS.
Referenced by GetLocalDecl(), and clang::ASTReader::ModuleDeclIterator::operator*().
getGlobalIdentifierID()
IdentifierID ASTReader::getGlobalIdentifierID (ModuleFile & M, unsigned LocalID)
Definition at line 8919 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::IdentifierRemap, clang::serialization::ModuleFile::ModuleOffsetMap, and clang::serialization::NUM_PREDEF_IDENT_IDS.
Referenced by getLocalIdentifier(), and readIdentifier().
getGlobalIndex()
GlobalModuleIndex* clang::ASTReader::getGlobalIndex () inline
Return global module index.
Definition at line 1751 of file ASTReader.h.
getGlobalMacroID()
MacroID ASTReader::getGlobalMacroID (ModuleFile & M, unsigned LocalID)
Retrieve the global macro ID corresponding to the given local ID within the given module file.
Definition at line 8961 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::MacroRemap, clang::serialization::ModuleFile::ModuleOffsetMap, and clang::serialization::NUM_PREDEF_MACRO_IDS.
getGlobalPreprocessedEntityID()
PreprocessedEntityID ASTReader::getGlobalPreprocessedEntityID (ModuleFile & M, unsigned LocalID) const
Determine the global preprocessed entity ID that corresponds to the given local ID within the given module.
Definition at line 1963 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, clang::serialization::NUM_PREDEF_PP_ENTITY_IDS, and clang::serialization::ModuleFile::PreprocessedEntityRemap.
getGlobalSelectorID()
serialization::SelectorID ASTReader::getGlobalSelectorID (ModuleFile & M, unsigned LocalID) const
Retrieve the global selector ID that corresponds to this the local selector ID in a given module.
Definition at line 9103 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, clang::serialization::NUM_PREDEF_SELECTOR_IDS, and clang::serialization::ModuleFile::SelectorRemap.
Referenced by getLocalSelector().
getGlobalSubmoduleID()
serialization::SubmoduleID ASTReader::getGlobalSubmoduleID (ModuleFile & M, unsigned LocalID)
Retrieve the global submodule ID given a module and its local ID number.
Definition at line 8976 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, clang::serialization::NUM_PREDEF_SUBMODULE_IDS, and clang::serialization::ModuleFile::SubmoduleRemap.
Referenced by clang::ASTRecordReader::getGlobalSubmoduleID(), and getLocalModuleFile().
getGlobalTypeID()
serialization::TypeID ASTReader::getGlobalTypeID (ModuleFile & F, unsigned LocalID) const
Map a local type ID within a given AST file into a global type ID.
Definition at line 7450 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::Qualifiers::FastMask, clang::Qualifiers::FastWidth, clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::serialization::ModuleFile::ModuleOffsetMap, clang::serialization::NUM_PREDEF_TYPE_IDS, and clang::serialization::ModuleFile::TypeRemap.
Referenced by clang::ASTRecordReader::getGlobalTypeID().
GetHeaderFileInfo()
HeaderFileInfo ASTReader::GetHeaderFileInfo (FileEntryRef FE) override virtual
Read the header file information for the given file entry.
Implements clang::ExternalHeaderFileInfoSource.
Definition at line 6533 of file ASTReader.cpp.
GetIdentifier()
IdentifierInfo* clang::ASTReader::GetIdentifier (serialization::IdentifierID ID) inline override
Definition at line 2160 of file ASTReader.h.
References DecodeIdentifierInfo().
getIdentifiers()
IdentifierIterator * ASTReader::getIdentifiers () override virtual
Retrieve an iterator into the set of all identifiers in all loaded AST files.
Reimplemented from clang::IdentifierInfoLookup.
Definition at line 8477 of file ASTReader.cpp.
References ASTIdentifierIterator, and loadGlobalIndex().
getIdentifierTable()
IdentifierTable & ASTReader::getIdentifierTable ()
Retrieve the identifier table associated with the preprocessor.
Definition at line 9426 of file ASTReader.cpp.
References clang::Preprocessor::getIdentifierTable().
getIdResolver()
IdentifierResolver & ASTReader::getIdResolver ()
Get the identifier resolver used for name lookup / updates in the translation unit scope.
We have one of these even if we don't have a Sema object.
Definition at line 10264 of file ASTReader.cpp.
References clang::Sema::IdResolver.
getKeyDeclaration() [1/2]
const Decl* clang::ASTReader::getKeyDeclaration (const Decl * D) inline
Definition at line 1351 of file ASTReader.h.
References getKeyDeclaration().
getKeyDeclaration() [2/2]
Decl* clang::ASTReader::getKeyDeclaration (Decl * D) inline
Returns the first key declaration for the given declaration.
This is one that is formerly-canonical (or still canonical) and whose module did not import any other key declaration of the entity.
Definition at line 1341 of file ASTReader.h.
References clang::Decl::getCanonicalDecl(), GetExistingDecl(), and clang::Decl::isFromASTFile().
Referenced by getKeyDeclaration().
getLoadedLookupTables()
const serialization::reader::DeclContextLookupTable * ASTReader::getLoadedLookupTables (DeclContext * Primary) const
Get the loaded lookup tables for Primary, if any.
Definition at line 8039 of file ASTReader.cpp.
GetLocalDecl()
Decl* clang::ASTReader::GetLocalDecl (ModuleFile & F, serialization::LocalDeclID LocalID) inline
Reads a declaration with the given local ID in the given module.
Definition at line 1942 of file ASTReader.h.
References GetDecl(), and getGlobalDeclID().
Referenced by GetLocalDeclAs(), clang::ASTRecordReader::GetLocalDeclAs(), and ReadLateParsedTemplates().
GetLocalDeclAs()
template<typename T > T* clang::ASTReader::GetLocalDeclAs (ModuleFile & F, serialization::LocalDeclID LocalID) inline
Reads a declaration with the given local ID in the given module.
Returns
The requested declaration, casted to the given return type.
Definition at line 1950 of file ASTReader.h.
References GetLocalDecl().
getLocalIdentifier()
IdentifierInfo * ASTReader::getLocalIdentifier (ModuleFile & M, unsigned LocalID)
Definition at line 8915 of file ASTReader.cpp.
References DecodeIdentifierInfo(), and getGlobalIdentifierID().
getLocalModuleFile()
ModuleFile * ASTReader::getLocalModuleFile (ModuleFile & M, unsigned ID)
Retrieve the module file with a given local ID within the specified ModuleFile.
Definition at line 9009 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), getGlobalSubmoduleID(), getModuleManager(), and clang::serialization::ModuleManager::pch_modules().
getLocalSelector()
Selector ASTReader::getLocalSelector (ModuleFile & M, unsigned LocalID)
Retrieve a selector from the given module with its local ID number.
Definition at line 9064 of file ASTReader.cpp.
References DecodeSelector(), and getGlobalSelectorID().
Referenced by ReadSelector().
getLocalType()
QualType ASTReader::getLocalType (ModuleFile & F, unsigned LocalID)
Resolve a local type ID within a given AST file into a type.
Definition at line 7445 of file ASTReader.cpp.
Referenced by readType().
getMacro()
MacroInfo * ASTReader::getMacro (serialization::MacroID ID)
Retrieve the macro with the given ID.
Definition at line 8934 of file ASTReader.cpp.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), and clang::serialization::NUM_PREDEF_MACRO_IDS.
getMemoryBufferSizes()
void ASTReader::getMemoryBufferSizes (MemoryBufferSizes & sizes) const override virtual
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
Reimplemented from clang::ExternalASTSource.
Definition at line 8205 of file ASTReader.cpp.
References bytes(), clang::ExternalASTSource::MemoryBufferSizes::malloc_bytes, and clang::ExternalASTSource::MemoryBufferSizes::mmap_bytes.
getModule()
Module * ASTReader::getModule (unsigned ID) override virtual
Retrieve the module that corresponds to the given module ID.
Note: overrides method in ExternalASTSource
Implements clang::ExternalPreprocessorSource.
Definition at line 9005 of file ASTReader.cpp.
References getSubmodule().
getModuleFileID()
unsigned ASTReader::getModuleFileID (ModuleFile * M)
Get an ID for the given module file.
Definition at line 9022 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseSubmoduleID, getModuleManager(), clang::serialization::ModuleFile::isModule(), clang::serialization::NUM_PREDEF_SUBMODULE_IDS, and clang::serialization::ModuleManager::pch_modules().
getModuleFileLevelDecls()
llvm::iterator_range< ASTReader::ModuleDeclIterator > ASTReader::getModuleFileLevelDecls (ModuleFile & Mod)
Definition at line 6243 of file ASTReader.cpp.
References clang::serialization::ModuleFile::FileSortedDecls, and clang::serialization::ModuleFile::NumFileSortedDecls.
Referenced by clang::index::indexModuleFile().
getModuleImportLoc()
std::pair< SourceLocation, StringRef > ASTReader::getModuleImportLoc (int ID) override virtual
Retrieve the module import location and module name for the given source manager entry ID.
Implements clang::ExternalSLocEntrySource.
Definition at line 1716 of file ASTReader.cpp.
References ID, clang::serialization::ModuleFile::ImportLoc, clang::serialization::ModuleFile::isModule(), and clang::serialization::ModuleFile::ModuleName.
getModuleManager()
ModuleManager& clang::ASTReader::getModuleManager () inline
Retrieve the module manager.
Definition at line 1785 of file ASTReader.h.
Referenced by clang::FrontendAction::BeginSourceFile(), clang::DumpModuleInfoAction::ExecuteAction(), getLocalModuleFile(), and getModuleFileID().
GetNumExternalSelectors()
uint32_t ASTReader::GetNumExternalSelectors () override virtual
Returns the number of selectors known to the external AST source.
The default implementation of this method is a no-op.
Reimplemented from clang::ExternalASTSource.
Definition at line 9097 of file ASTReader.cpp.
References getTotalNumSelectors().
getOriginalSourceFile() [1/2]
StringRef clang::ASTReader::getOriginalSourceFile () inline
Retrieve the name of the original source file name for the primary module file.
Definition at line 1792 of file ASTReader.h.
References clang::serialization::ModuleManager::getPrimaryModule(), and clang::serialization::ModuleFile::OriginalSourceFileName.
Referenced by createInvocationForMigration().
getOriginalSourceFile() [2/2]
std::string ASTReader::getOriginalSourceFile (const std::string & ASTFileName, FileManager & FileMgr, const PCHContainerReader & PCHContainerRdr, DiagnosticsEngine & Diags) static
Retrieve the name of the original source file name directly from the AST file, without actually loading the AST file.
Definition at line 5294 of file ASTReader.cpp.
References clang::serialization::CONTROL_BLOCK_ID, doesntStartWithASTFileMagic(), clang::PCHContainerReader::ExtractPCH(), clang::FileManager::getBufferForFile(), clang::serialization::ORIGINAL_FILE, clang::DiagnosticsEngine::Report(), and SkipCursorToBlock().
getOwningModuleFile()
ModuleFile * ASTReader::getOwningModuleFile (const Decl * D)
Retrieve the module file that owns the given declaration, or NULL if the declaration is not from a module file.
Definition at line 7688 of file ASTReader.cpp.
References clang::Decl::getGlobalID(), and clang::Decl::isFromASTFile().
Referenced by clang::ASTDeclWriter::AddFirstDeclFromEachModule(), and ReadLateParsedTemplates().
getPreprocessor()
Preprocessor& clang::ASTReader::getPreprocessor () const inline
Retrieve the preprocessor.
Definition at line 1788 of file ASTReader.h.
Referenced by clang::index::indexModuleFile(), isInterestingIdentifier(), and markIdentifierFromAST().
getSema()
Sema* clang::ASTReader::getSema () inline
Retrieve the semantic analysis object used to analyze the translation unit in which the precompiled header is being imported.
Definition at line 2391 of file ASTReader.h.
Referenced by ReadMethodPool().
getSLocEntryID()
int ASTReader::getSLocEntryID (SourceLocation::UIntTy SLocOffset) override virtual
Get the index ID for the loaded SourceLocation offset.
Implements clang::ExternalSLocEntrySource.
Definition at line 1494 of file ASTReader.cpp.
References clang::serialization::ModuleFile::LocalNumSLocEntries, and Offset.
getSourceDescriptor()
std::optional< ASTSourceDescriptor > ASTReader::getSourceDescriptor (unsigned ID) override virtual
Return a descriptor for the corresponding module.
Reimplemented from clang::ExternalASTSource.
Definition at line 9039 of file ASTReader.cpp.
References distance(), clang::FileName, clang::serialization::ModuleFile::FileName, clang::serialization::ModuleManager::getPrimaryModule(), getSubmodule(), clang::serialization::ModuleFile::OriginalSourceFileName, clang::serialization::ModuleManager::pch_modules(), and clang::serialization::ModuleFile::Signature.
getSourceLocationForDeclID()
SourceLocation ASTReader::getSourceLocationForDeclID (serialization::GlobalDeclID ID)
Returns the source location for the decl ID.
Definition at line 7697 of file ASTReader.cpp.
References ID, and clang::serialization::NUM_PREDEF_DECL_IDS.
getSourceManager()
SourceManager& clang::ASTReader::getSourceManager () const inline
Definition at line 1612 of file ASTReader.h.
getSubmodule()
Module * ASTReader::getSubmodule (serialization::SubmoduleID GlobalID)
Retrieve the submodule that corresponds to a global submodule ID.
Definition at line 8991 of file ASTReader.cpp.
References clang::serialization::NUM_PREDEF_SUBMODULE_IDS.
Referenced by getModule(), getSourceDescriptor(), and clang::ASTRecordReader::getSubmodule().
getSuggestedPredefines()
const std::string& clang::ASTReader::getSuggestedPredefines () inline
Returns the suggested contents of the predefines buffer, which contains a (typically-empty) subset of the predefines build prior to including the precompiled header.
Definition at line 1828 of file ASTReader.h.
getSwitchCaseWithID()
SwitchCase * ASTReader::getSwitchCaseWithID (unsigned ID)
Retrieve the switch-case statement with the given ID.
Definition at line 9439 of file ASTReader.cpp.
Referenced by clang::ASTRecordReader::getSwitchCaseWithID().
getTotalNumDecls()
unsigned clang::ASTReader::getTotalNumDecls () const inline
Returns the number of declarations found in the chain.
Definition at line 1875 of file ASTReader.h.
getTotalNumIdentifiers()
unsigned clang::ASTReader::getTotalNumIdentifiers () const inline
Returns the number of identifiers found in the chain.
Definition at line 1860 of file ASTReader.h.
getTotalNumMacros()
unsigned clang::ASTReader::getTotalNumMacros () const inline
Returns the number of macros found in the chain.
Definition at line 1865 of file ASTReader.h.
getTotalNumPreprocessedEntities()
unsigned clang::ASTReader::getTotalNumPreprocessedEntities () const inline
Returns the number of preprocessed entities known to the AST reader.
Definition at line 1891 of file ASTReader.h.
getTotalNumSelectors()
unsigned clang::ASTReader::getTotalNumSelectors () const inline
Returns the number of selectors found in the chain.
Definition at line 1885 of file ASTReader.h.
Referenced by GetNumExternalSelectors().
getTotalNumSLocs()
unsigned clang::ASTReader::getTotalNumSLocs () const inline
Returns the number of source locations found in the chain.
Definition at line 1855 of file ASTReader.h.
getTotalNumSubmodules()
unsigned clang::ASTReader::getTotalNumSubmodules () const inline
Returns the number of submodules known.
Definition at line 1880 of file ASTReader.h.
Referenced by clang::DumpModuleInfoAction::ExecuteAction().
getTotalNumTypes()
unsigned clang::ASTReader::getTotalNumTypes () const inline
Returns the number of types found in the chain.
Definition at line 1870 of file ASTReader.h.
GetType()
QualType ASTReader::GetType (serialization::TypeID ID)
Resolve a type ID into a type, potentially building a new type.
Definition at line 7149 of file ASTReader.cpp.
hasExternalDefinitions()
ExternalASTSource::ExtKind ASTReader::hasExternalDefinitions (const Decl * D) override virtual
Reimplemented from clang::ExternalASTSource.
Definition at line 9057 of file ASTReader.cpp.
References clang::ExternalASTSource::EK_Always, clang::ExternalASTSource::EK_Never, and clang::ExternalASTSource::EK_ReplyHazy.
hasGlobalIndex()
bool clang::ASTReader::hasGlobalIndex () const inline
Determine whether this AST reader has a global index.
Definition at line 1748 of file ASTReader.h.
InitializeContext()
void ASTReader::InitializeContext ()
Initializes the ASTContext.
Definition at line 5098 of file ASTReader.cpp.
InitializeSema()
void ASTReader::InitializeSema (Sema & S) override virtual
Initialize the semantic source with the Sema instance being used to perform semantic analysis on the abstract syntax tree.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8221 of file ASTReader.cpp.
isAcceptableASTFile()
bool ASTReader::isAcceptableASTFile (StringRef Filename, FileManager & FileMgr, const InMemoryModuleCache & ModuleCache, const PCHContainerReader & PCHContainerRdr, const LangOptions & LangOpts, const TargetOptions & TargetOpts, const PreprocessorOptions & PPOpts, StringRef ExistingModuleCachePath, bool RequireStrictOptionMatches = false) static
Determine whether the given AST file is acceptable to load into a translation unit with the given language and target options.
Definition at line 5703 of file ASTReader.cpp.
isDeclIDFromModule()
bool ASTReader::isDeclIDFromModule (serialization::GlobalDeclID ID, ModuleFile & M) const
Returns true if global DeclID ID originated from module M.
Definition at line 7678 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseDeclID, ID, clang::serialization::ModuleFile::LocalNumDecls, and clang::serialization::NUM_PREDEF_DECL_IDS.
isGlobalIndexUnavailable()
bool ASTReader::isGlobalIndexUnavailable () const
Determine whether we tried to load the global index, but failed, e.g., because it is out-of-date or does not exist.
Definition at line 4377 of file ASTReader.cpp.
isPreprocessedEntityInFileID()
std::optional< bool > ASTReader::isPreprocessedEntityInFileID (unsigned Index, FileID FID) override virtual
Optionally returns true or false if the preallocated preprocessed entity with index Index came from file FID.
Optionally returns true or false if the preallocated preprocessed entity with index.
Index came from file
FID.
Reimplemented from clang::ExternalPreprocessingRecordSource.
Definition at line 6483 of file ASTReader.cpp.
isProcessingUpdateRecords()
bool clang::ASTReader::isProcessingUpdateRecords () inline
Definition at line 2436 of file ASTReader.h.
loadGlobalIndex()
bool ASTReader::loadGlobalIndex ()
Attempts to load the global index.
Returns
true if loading the global index has failed for any reason.
Definition at line 4352 of file ASTReader.cpp.
References clang::GlobalModuleIndex::readIndex().
Referenced by getIdentifiers().
LoadSelector()
void ASTReader::LoadSelector (Selector Sel)
Load a selector from disk, registering its ID if it exists.
Definition at line 8823 of file ASTReader.cpp.
References ReadMethodPool().
makeModuleVisible()
void ASTReader::makeModuleVisible (Module * Mod, Module::NameVisibilityKind NameVisibility, SourceLocation ImportLoc)
Make the entities in the given module and any of its (non-explicit) submodules visible to name lookup.
Parameters
Mod The module whose names should be made visible.
NameVisibility The level of visibility to give the names in the module. Visibility can only be increased over time.
ImportLoc The location at which the import occurs.
Definition at line 4288 of file ASTReader.cpp.
References Visited.
makeNamesVisible()
void ASTReader::makeNamesVisible (const HiddenNames & Names, Module * Owner)
Make the names within this set of hidden names visible.
Definition at line 4274 of file ASTReader.cpp.
References clang::Module::Hidden, moveMethodToBackOfGlobalList(), and clang::Module::NameVisibility.
mapGlobalIDToModuleFileGlobalID()
DeclID ASTReader::mapGlobalIDToModuleFileGlobalID (ModuleFile & M, serialization::GlobalDeclID GlobalID)
Map a global declaration ID into the declaration ID used to refer to this declaration within the given module fule.
Returns
the global ID of the given declaration as known in the given module file.
Definition at line 7821 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseDeclID, clang::serialization::GlobalDeclID::get(), clang::serialization::ModuleFile::GlobalToLocalDeclIDs, ID, and clang::serialization::NUM_PREDEF_DECL_IDS.
markIdentifierUpToDate()
void ASTReader::markIdentifierUpToDate (const IdentifierInfo * II)
Note that this identifier is up-to-date.
Definition at line 2247 of file ASTReader.cpp.
mergeDefinitionVisibility()
void ASTReader::mergeDefinitionVisibility (NamedDecl * Def, NamedDecl * MergedDef)
Note that MergedDef is a redefinition of the canonical definition Def, so Def should be visible whenever MergedDef is.
We've merged the definition MergedDef into the existing definition Def.
Ensure that Def is made visible whenever MergedDef is made visible.
Definition at line 4337 of file ASTReader.cpp.
References clang::Decl::getImportedOwningModule(), clang::Decl::isUnconditionallyVisible(), and clang::Decl::setVisibleDespiteOwningModule().
Referenced by clang::ASTDeclReader::attachPreviousDeclImpl().
operator=()
ASTReader& clang::ASTReader::operator= (const ASTReader &) delete
PrintStats()
void ASTReader::PrintStats () override virtual
Print some statistics about AST usage.
Reimplemented from clang::ExternalASTSource.
Definition at line 8075 of file ASTReader.cpp.
References dump().
ReadAlignPackInfo()
Sema::AlignPackInfo clang::ASTReader::ReadAlignPackInfo (uint32_t Raw) const inline
Read a AlignPackInfo from raw form.
Definition at line 2242 of file ASTReader.h.
References clang::Sema::AlignPackInfo::getFromRawEncoding().
ReadAST()
ASTReader::ASTReadResult ASTReader::ReadAST (StringRef FileName, ModuleKind Type, SourceLocation ImportLoc, unsigned ClientLoadCapabilities, ModuleFile ** NewLoadedModuleFile = nullptr)
Load the AST file designated by the given file name.
Parameters
FileName The name of the AST file to load.
Type The kind of AST being loaded, e.g., PCH, module, main file, or preamble.
ImportLoc the location where the module file will be considered as imported from. For non-module AST types it should be invalid.
ClientLoadCapabilities The set of client load-failure capabilities, represented as a bitset of the enumerators of LoadFailureCapabilities.
LoadedModuleFile The optional out-parameter refers to the new loaded modules. In case the module specified by FileName is already loaded, the module file pointer referred by NewLoadedModuleFile wouldn't change. Otherwise if the AST file get loaded successfully, NewLoadedModuleFile would refer to the address of the new loaded top level module. The state of NewLoadedModuleFile is unspecified if the AST file isn't loaded successfully.
Definition at line 4443 of file ASTReader.cpp.
References clang::HeaderSearchOptions::BuildSessionTimestamp, Data, clang::serialization::ModuleFile::DidReadTopLevelSubmodule, clang::serialization::ModuleFile::DirectImportLoc, clang::serialization::EXTENSION_BLOCK_ID, clang::FileName, clang::serialization::ModuleFile::FileName, clang::serialization::ModuleFile::GlobalBitOffset, ID, Id, clang::serialization::ModuleFile::IdentifierTableData, clang::serialization::ModuleFile::ImportLoc, clang::serialization::ModuleFile::isModule(), clang::FileID::isValid(), markIdentifierFromAST(), clang::Module::Conflict::Message, clang::serialization::MK_ImplicitModule, clang::serialization::MK_MainFile, clang::serialization::MK_PCH, clang::serialization::MK_Preamble, clang::serialization::ModuleFile::ModuleName, clang::HeaderSearchOptions::ModulesValidateOncePerBuildSession, Offset, clang::serialization::ModuleFile::OriginalSourceFileID, clang::Module::Conflict::Other, clang::serialization::ModuleFile::PreloadIdentifierOffsets, clang::serialization::reader::ASTIdentifierLookupTrait::ReadIdentifierID(), clang::serialization::reader::ASTIdentifierLookupTraitBase::ReadKey(), clang::serialization::reader::ASTIdentifierLookupTraitBase::ReadKeyDataLength(), clang::IdentifierInfo::setOutOfDate(), clang::serialization::ModuleFile::SizeInBits, SkipCursorToBlock(), clang::serialization::ModuleFile::Stream, clang::Unresolved, and updateModuleTimestamp().
readASTFileControlBlock()
bool ASTReader::readASTFileControlBlock (StringRef Filename, FileManager & FileMgr, const InMemoryModuleCache & ModuleCache, const PCHContainerReader & PCHContainerRdr, bool FindModuleFileExtensions, ASTReaderListener & Listener, bool ValidateDiagnosticOptions, unsigned ClientLoadCapabilities = ARR_ConfigurationMismatch | ARR_OutOfDate) static
Read the control block for the named AST file.
Returns
true if an error occurred, false otherwise.
Definition at line 5409 of file ASTReader.cpp.
References clang::serialization::CONTROL_BLOCK_ID, doesntStartWithASTFileMagic(), clang::serialized_diags::Error, clang::serialization::EXTENSION_BLOCK_ID, clang::serialization::EXTENSION_METADATA, clang::PCHContainerReader::ExtractPCH(), Filename, clang::FileManager::getBufferForFile(), clang::serialization::IMPORTS, clang::serialization::INPUT_FILE, clang::serialization::INPUT_FILE_HASH, clang::serialization::INPUT_FILE_OFFSETS, clang::serialization::INPUT_FILES_BLOCK_ID, clang::InMemoryModuleCache::lookupPCM(), clang::serialization::METADATA, clang::serialization::MODULE_DIRECTORY, clang::serialization::MODULE_MAP_FILE, clang::serialization::MODULE_NAME, clang::ASTReaderListener::needsImportVisitation(), clang::ASTReaderListener::needsInputFileVisitation(), clang::ASTReaderListener::needsSystemInputFileVisitation(), clang::serialization::OPTIONS_BLOCK_ID, parseModuleFileExtensionMetadata(), clang::ASTReaderListener::ReadFullVersionInformation(), clang::ASTReaderListener::readModuleFileExtension(), clang::ASTReaderListener::ReadModuleMapFile(), clang::ASTReaderListener::ReadModuleName(), clang::ASTFileSignature::size, SkipCursorToBlock(), clang::serialization::VERSION_MAJOR, clang::ASTReaderListener::visitImport(), and clang::ASTReaderListener::visitInputFile().
ReadBitVector()
llvm::BitVector ASTReader::ReadBitVector (const RecordData & Record, const StringRef Blob) static
Definition at line 9357 of file ASTReader.cpp.
References clang::interp::Ret().
ReadBlockAbbrevs()
llvm::Error ASTReader::ReadBlockAbbrevs (llvm::BitstreamCursor & Cursor, unsigned BlockID, uint64_t * StartOfBlockOffset = nullptr) static
ReadBlockAbbrevs - Enter a subblock of the specified BlockID with the specified cursor.
Enter a subblock of the specified BlockID with the specified cursor.
Read the abbreviations that are at the top of the block and then leave the cursor pointing into the block.
Definition at line 1753 of file ASTReader.cpp.
References Offset.
ReadComments()
void ASTReader::ReadComments () override virtual
Loads comments ranges.
Reimplemented from clang::ExternalASTSource.
Definition at line 9448 of file ASTReader.cpp.
ReadCXXTemporary()
CXXTemporary * ASTReader::ReadCXXTemporary (ModuleFile & F, const RecordData & Record, unsigned & Idx)
Definition at line 9409 of file ASTReader.cpp.
References clang::CXXTemporary::Create(), and getContext().
Referenced by clang::ASTRecordReader::readCXXTemporary().
ReadDecl()
Decl* clang::ASTReader::ReadDecl (ModuleFile & F, const RecordData & R, unsigned & I) inline
Reads a declaration from the given position in a record in the given module.
Definition at line 1972 of file ASTReader.h.
References GetDecl(), and ReadDeclID().
Referenced by clang::ASTRecordReader::readDecl().
ReadDeclAs()
template<typename T > T* clang::ASTReader::ReadDeclAs (ModuleFile & F, const RecordData & R, unsigned & I) inline
Reads a declaration from the given position in a record in the given module.
Returns
The declaration read from this location, casted to the given result type.
Definition at line 1982 of file ASTReader.h.
References GetDecl(), and ReadDeclID().
Referenced by clang::ASTRecordReader::readDeclAs().
ReadDeclID()
GlobalDeclID ASTReader::ReadDeclID (ModuleFile & F, const RecordData & Record, unsigned & Idx)
Reads a declaration ID from the given position in a record in the given module.
Returns
The declaration ID read from the record, adjusted to a global ID.
Definition at line 7839 of file ASTReader.cpp.
Referenced by ReadDecl(), ReadDeclAs(), and clang::ASTRecordReader::readDeclID().
ReadDeclsToCheckForDeferredDiags()
void ASTReader::ReadDeclsToCheckForDeferredDiags (llvm::SmallSetVector< Decl *, 4 > & Decls) override virtual
Read the set of decls to be checked for deferred diags.
The external source should append its own potentially emitted function and variable decls which may cause deferred diags. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8711 of file ASTReader.cpp.
References GetDecl().
ReadDefinedMacros()
void ASTReader::ReadDefinedMacros () override virtual
Read the set of macros defined by this external macro source.
Implements clang::ExternalPreprocessorSource.
Definition at line 2104 of file ASTReader.cpp.
References clang::serialized_diags::Error, clang::IdentifierInfo::isOutOfDate(), clang::serialization::PP_MACRO_FUNCTION_LIKE, clang::serialization::PP_MACRO_OBJECT_LIKE, and clang::serialization::PP_TOKEN.
ReadDelegatingConstructors()
void ASTReader::ReadDelegatingConstructors (SmallVectorImpl< CXXConstructorDecl * > & Decls) override virtual
Read the set of delegating constructors known to the external Sema source.
The external source should append its own delegating constructors to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8678 of file ASTReader.cpp.
References GetDecl().
ReadExpr()
Expr * ASTReader::ReadExpr (ModuleFile & F)
Reads an expression.
Definition at line 2855 of file ASTReaderStmt.cpp.
Referenced by clang::ASTRecordReader::readExpr().
ReadExtVectorDecls()
void ASTReader::ReadExtVectorDecls (SmallVectorImpl< TypedefNameDecl * > & Decls) override virtual
Read the set of ext_vector type declarations known to the external Sema source.
The external source should append its own ext_vector type declarations to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8689 of file ASTReader.cpp.
References GetDecl().
ReadFileID()
FileID clang::ASTReader::ReadFileID (ModuleFile & F, const RecordDataImpl & Record, unsigned & Idx) const inline
Read a FileID.
Definition at line 2283 of file ASTReader.h.
References TranslateFileID().
readIdentifier()
IdentifierInfo* clang::ASTReader::readIdentifier (ModuleFile & M, const RecordData & Record, unsigned & Idx) inline
Definition at line 2155 of file ASTReader.h.
References DecodeIdentifierInfo(), and getGlobalIdentifierID().
Referenced by clang::ASTRecordReader::readIdentifier().
ReadKnownNamespaces()
void ASTReader::ReadKnownNamespaces (SmallVectorImpl< NamespaceDecl * > & Namespaces) override virtual
Load the set of namespaces that are known to the external source, which will be used during typo correction.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8619 of file ASTReader.cpp.
References GetDecl().
ReadLateParsedTemplates()
void ASTReader::ReadLateParsedTemplates (llvm::MapVector< const FunctionDecl *, std::unique_ptr< LateParsedTemplate >> & LPTMap) override virtual
Read the set of late parsed template functions for this source.
The external source should insert its own late parsed template functions into the map. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same map entries repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8782 of file ASTReader.cpp.
References clang::FPOptions::getFromOpaqueInt(), GetLocalDecl(), getOwningModuleFile(), LT, ReadToken(), and clang::T.
ReadMacroRecord()
MacroInfo * ASTReader::ReadMacroRecord (ModuleFile & F, uint64_t Offset)
Reads the macro record located at the given offset.
Definition at line 1832 of file ASTReader.cpp.
References clang::serialized_diags::Error, clang::serialization::ModuleFile::MacroCursor, Offset, clang::serialization::PP_MACRO_DIRECTIVE_HISTORY, clang::serialization::PP_MACRO_FUNCTION_LIKE, clang::serialization::PP_MACRO_OBJECT_LIKE, and clang::serialization::PP_MODULE_MACRO.
ReadMethodPool()
void ASTReader::ReadMethodPool (Selector Sel) override virtual
Load the contents of the global method pool for a given selector.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8576 of file ASTReader.cpp.
References clang::serialization::ReadMethodPoolVisitor::getFactoryMethods(), clang::ExternalASTSource::getGeneration(), clang::serialization::ReadMethodPoolVisitor::getInstanceMethods(), getSema(), and clang::serialization::ModuleManager::visit().
Referenced by LoadSelector(), and updateOutOfDateSelector().
ReadMismatchingDeleteExpressions()
void ASTReader::ReadMismatchingDeleteExpressions (llvm::MapVector< FieldDecl *, llvm::SmallVector< std::pair< SourceLocation, bool >, 4 >> & Exprs) override virtual
Reimplemented from clang::ExternalSemaSource.
Definition at line 8641 of file ASTReader.cpp.
References GetDecl(), and clang::SourceLocation::getFromRawEncoding().
ReadPath() [1/2]
std::string ASTReader::ReadPath (ModuleFile & F, const RecordData & Record, unsigned & Idx)
Definition at line 9382 of file ASTReader.cpp.
References Filename, ReadString(), and ResolveImportedPath().
Referenced by clang::ASTRecordReader::readPath().
ReadPath() [2/2]
std::string ASTReader::ReadPath (StringRef BaseDirectory, const RecordData & Record, unsigned & Idx)
Definition at line 9389 of file ASTReader.cpp.
References Filename, ReadString(), and ResolveImportedPath().
ReadPendingInstantiations()
void ASTReader::ReadPendingInstantiations (SmallVectorImpl< std::pair< ValueDecl *, SourceLocation >> & Pending) override
Definition at line 8770 of file ASTReader.cpp.
References GetDecl(), and clang::SourceLocation::getFromRawEncoding().
ReadPragmaDiagnosticMappings()
void ASTReader::ReadPragmaDiagnosticMappings (DiagnosticsEngine & Diag)
Definition at line 6542 of file ASTReader.cpp.
References clang::DiagnosticMapping::deserialize(), Diag(), clang::DiagnosticMapping::isErrorOrFatal(), clang::serialization::ModuleFile::isModule(), clang::DiagnosticMapping::isPragma(), clang::FileID::isValid(), clang::serialization::ModuleFile::Kind, clang::serialization::MK_ImplicitModule, Offset, clang::serialization::ModuleFile::OriginalSourceFileID, clang::serialization::ModuleFile::PragmaDiagMappings, clang::DiagnosticMapping::setSeverity(), clang::DiagnosticMapping::setUpgradedFromWarning(), State, clang::T, clang::diag::Warning, and clang::DiagnosticMapping::wasUpgradedFromWarning().
ReadPreprocessedEntity()
PreprocessedEntity * ASTReader::ReadPreprocessedEntity (unsigned Index) override virtual
Read a preallocated preprocessed entity from the external source.
Returns
null if an error occurred that prevented the preprocessed entity from being loaded.
Implements clang::ExternalPreprocessingRecordSource.
Definition at line 6264 of file ASTReader.cpp.
ReadReferencedSelectors()
void ASTReader::ReadReferencedSelectors (SmallVectorImpl< std::pair< Selector, SourceLocation >> & Sels) override
Definition at line 8721 of file ASTReader.cpp.
References DecodeSelector(), and clang::SourceLocation::getFromRawEncoding().
ReadSelector()
Selector clang::ASTReader::ReadSelector (ModuleFile & M, const RecordData & Record, unsigned & Idx) inline
Definition at line 2229 of file ASTReader.h.
References getLocalSelector().
Referenced by clang::ASTRecordReader::readSelector().
ReadSkippedRange()
SourceRange ASTReader::ReadSkippedRange (unsigned Index) override virtual
Read a preallocated skipped range from the external source.
Implements clang::ExternalPreprocessingRecordSource.
Definition at line 6250 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BasePreprocessedSkippedRangeID, clang::serialization::PPSkippedRange::getBegin(), clang::serialization::PPSkippedRange::getEnd(), and clang::serialization::ModuleFile::PreprocessedSkippedRangeOffsets.
ReadSLocEntry()
bool ASTReader::ReadSLocEntry (int ID) override virtual
Read the source location entry with index ID.
Implements clang::ExternalSLocEntrySource.
Definition at line 1531 of file ASTReader.cpp.
References ID.
readSLocOffset()
llvm::Expected< SourceLocation::UIntTy > ASTReader::readSLocOffset (ModuleFile * F, unsigned Index)
Try to read the offset of the SLocEntry at the given index in the given module file.
Definition at line 1459 of file ASTReader.cpp.
ReadSourceLocation() [1/2]
SourceLocation clang::ASTReader::ReadSourceLocation (ModuleFile & ModuleFile, const RecordDataImpl & Record, unsigned & Idx, LocSeq * Seq = nullptr) inline
Read a source location.
Definition at line 2276 of file ASTReader.h.
References ReadSourceLocation(), and clang::Seq.
ReadSourceLocation() [2/2]
SourceLocation clang::ASTReader::ReadSourceLocation (ModuleFile & ModuleFile, SourceLocation::UIntTy Raw, LocSeq * Seq = nullptr) const inline
Read a source location from raw form.
Definition at line 2254 of file ASTReader.h.
References ReadUntranslatedSourceLocation(), clang::Seq, and TranslateSourceLocation().
Referenced by clang::ASTRecordReader::readSourceLocation(), ReadSourceLocation(), and ReadSourceRange().
ReadSourceRange()
SourceRange ASTReader::ReadSourceRange (ModuleFile & F, const RecordData & Record, unsigned & Idx, LocSeq * Seq = nullptr)
Read a source range.
Definition at line 9350 of file ASTReader.cpp.
References ReadSourceLocation(), and clang::Seq.
Referenced by clang::ASTRecordReader::readSourceRange().
ReadStmt()
Stmt * ASTReader::ReadStmt (ModuleFile & F)
Reads a statement.
Definition at line 2841 of file ASTReaderStmt.cpp.
Referenced by clang::ASTRecordReader::readStmt().
ReadString()
std::string ASTReader::ReadString (const RecordDataImpl & Record, unsigned & Idx) static
Definition at line 9375 of file ASTReader.cpp.
Referenced by ReadPath(), and clang::ASTRecordReader::readString().
ReadSubExpr()
Expr * ASTReader::ReadSubExpr ()
Reads a sub-expression operand during statement reading.
Definition at line 2859 of file ASTReaderStmt.cpp.
Referenced by clang::ASTRecordReader::readSubExpr().
ReadSubStmt()
Stmt* clang::ASTReader::ReadSubStmt () inline
Reads a sub-statement operand during statement reading.
Definition at line 2334 of file ASTReader.h.
Referenced by clang::ASTRecordReader::readSubStmt().
ReadTentativeDefinitions()
void ASTReader::ReadTentativeDefinitions (SmallVectorImpl< VarDecl * > & TentativeDefs) override virtual
Read the set of tentative definitions known to the external Sema source.
The external source should append its own tentative definitions to the given vector of tentative definitions. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8657 of file ASTReader.cpp.
References GetDecl().
ReadToken()
Token ASTReader::ReadToken (ModuleFile & M, const RecordDataImpl & Record, unsigned & Idx)
Reads a token out of a record.
Definition at line 1780 of file ASTReader.cpp.
References clang::Sema::PragmaPackInfo::Action, clang::Token::getKind(), clang::Token::isAnnotation(), clang::PragmaLoopHintInfo::PragmaName, clang::Token::setAnnotationEndLoc(), clang::Token::setAnnotationValue(), clang::Token::setFlag(), clang::Token::setIdentifierInfo(), clang::Token::setKind(), clang::Token::setLength(), clang::Token::setLocation(), and clang::Token::startToken().
Referenced by ReadLateParsedTemplates(), and clang::ASTRecordReader::readToken().
readType()
QualType clang::ASTReader::readType (ModuleFile & F, const RecordData & Record, unsigned & Idx) inline
Read a type from the current position in the given record, which was read from the given AST file.
Definition at line 1910 of file ASTReader.h.
References getLocalType().
Referenced by clang::ASTRecordReader::readType().
ReadUndefinedButUsed()
void ASTReader::ReadUndefinedButUsed (llvm::MapVector< NamedDecl *, SourceLocation > & Undefined) override virtual
Load the set of used but not defined functions or variables with internal linkage, or used but not defined internal functions.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8630 of file ASTReader.cpp.
References GetDecl(), clang::SourceLocation::getFromRawEncoding(), and clang::RISCV::Undefined.
ReadUntranslatedSourceLocation()
SourceLocation clang::ASTReader::ReadUntranslatedSourceLocation (SourceLocation::UIntTy Raw, LocSeq * Seq = nullptr) const inline
Read a source location from raw form and return it in its originating module file's source location space.
Definition at line 2248 of file ASTReader.h.
References clang::SourceLocationEncoding::decode(), and clang::Seq.
Referenced by ReadSourceLocation().
ReadUnusedFileScopedDecls()
void ASTReader::ReadUnusedFileScopedDecls (SmallVectorImpl< const DeclaratorDecl * > & Decls) override virtual
Read the set of unused file-scope declarations known to the external Sema source.
The external source should append its own unused, filed-scope to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8667 of file ASTReader.cpp.
References GetDecl().
ReadUnusedLocalTypedefNameCandidates()
void ASTReader::ReadUnusedLocalTypedefNameCandidates (llvm::SmallSetVector< const TypedefNameDecl *, 4 > & Decls) override virtual
Read the set of potentially unused typedefs known to the source.
The external source should append its own potentially unused local typedefs to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8699 of file ASTReader.cpp.
References GetDecl().
ReadUsedVTables()
void ASTReader::ReadUsedVTables (SmallVectorImpl< ExternalVTableUse > & VTables) override virtual
Read the set of used vtables known to the external Sema source.
The external source should append its own used vtables to the given vector. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same vtables repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8757 of file ASTReader.cpp.
References clang::ExternalVTableUse::DefinitionRequired, GetDecl(), clang::SourceLocation::getFromRawEncoding(), clang::ExternalVTableUse::Location, and clang::ExternalVTableUse::Record.
ReadVersionTuple()
VersionTuple ASTReader::ReadVersionTuple (const RecordData & Record, unsigned & Idx) static
Read a version tuple.
Definition at line 9397 of file ASTReader.cpp.
Referenced by clang::ASTRecordReader::readVersionTuple().
ReadWeakUndeclaredIdentifiers()
void ASTReader::ReadWeakUndeclaredIdentifiers (SmallVectorImpl< std::pair< IdentifierInfo *, WeakInfo >> & WeakIDs) override
Definition at line 8739 of file ASTReader.cpp.
References DecodeIdentifierInfo(), and clang::SourceLocation::getFromRawEncoding().
RecordSwitchCaseID()
void ASTReader::RecordSwitchCaseID (SwitchCase * SC, unsigned ID)
Record that the given ID maps to the given switch-case statement.
Definition at line 9432 of file ASTReader.cpp.
Referenced by clang::ASTRecordReader::recordSwitchCaseID().
resetForReload()
void clang::ASTReader::resetForReload () inline
Reset reader for a reload try.
Definition at line 1754 of file ASTReader.h.
ResolveImportedPath() [1/2]
void ASTReader::ResolveImportedPath (ModuleFile & M, std::string & Filename)
If we are loading a relocatable PCH or module file, and the filename is not an absolute path, add the system or module root to the beginning of the file name.
Definition at line 2677 of file ASTReader.cpp.
References clang::serialization::ModuleFile::BaseDirectory, and Filename.
Referenced by ReadPath().
ResolveImportedPath() [2/2]
void ASTReader::ResolveImportedPath (std::string & Filename, StringRef Prefix) static
Definition at line 2683 of file ASTReader.cpp.
References Filename.
resolvePendingMacro()
void ASTReader::resolvePendingMacro (IdentifierInfo * II, const PendingMacroInfo & PMInfo)
Definition at line 2258 of file ASTReader.cpp.
References clang::serialization::ModuleFile::isModule(), clang::serialization::ModuleFile::MacroCursor, clang::serialization::ModuleFile::MacroOffsetsBase, clang::MacroDirective::MD_Define, clang::MacroDirective::MD_Undefine, clang::MacroDirective::MD_Visibility, clang::serialization::PP_MACRO_DIRECTIVE_HISTORY, clang::serialization::PP_MODULE_MACRO, and clang::MacroDirective::setPrevious().
setDeserializationListener()
void ASTReader::setDeserializationListener (ASTDeserializationListener * Listener, bool TakeOwnership = false)
Set the AST deserialization listener.
Definition at line 897 of file ASTReader.cpp.
SetGloballyVisibleDecls()
void ASTReader::SetGloballyVisibleDecls (IdentifierInfo * II, const SmallVectorImpl< serialization::GlobalDeclID > & DeclIDs, SmallVectorImpl< Decl * > * Decls = nullptr)
Set the globally-visible declarations associated with the given identifier.
If the AST reader is currently in a state where the given declaration IDs cannot safely be resolved, they are queued until it is safe to resolve them.
Parameters
II an IdentifierInfo that refers to one or more globally-visible declarations.
DeclIDs the set of declaration IDs with the name II that are visible at global scope.
Decls if non-null, this vector will be populated with the set of deserialized declarations. These declarations will not be pushed into scope.
Definition at line 8852 of file ASTReader.cpp.
References GetDecl(), and PreloadedDeclIDs.
SetIdentifierInfo()
void ASTReader::SetIdentifierInfo (unsigned ID, IdentifierInfo * II)
Definition at line 8828 of file ASTReader.cpp.
References clang::ASTDeserializationListener::IdentifierRead().
setListener()
void clang::ASTReader::setListener (std::unique_ptr< ASTReaderListener > Listener) inline
Set the AST callbacks listener.
Definition at line 1699 of file ASTReader.h.
Referenced by clang::ASTReader::ListenerScope::ListenerScope(), and clang::ASTReader::ListenerScope::~ListenerScope().
SkipPath()
static void clang::ASTReader::SkipPath (const RecordData & Record, unsigned & Idx) inline static
Definition at line 2317 of file ASTReader.h.
References SkipString().
SkipString()
static void clang::ASTReader::SkipString (const RecordData & Record, unsigned & Idx) inline static
Definition at line 2305 of file ASTReader.h.
Referenced by SkipPath().
StartedDeserializing()
void ASTReader::StartedDeserializing () override virtual
Notify ASTReader that we started deserialization of a decl or type so until FinishedDeserializing is called there may be decls that are initializing.
Must be paired with FinishedDeserializing.
Reimplemented from clang::ExternalASTSource.
Definition at line 10131 of file ASTReader.cpp.
StartTranslationUnit()
void ASTReader::StartTranslationUnit (ASTConsumer * Consumer) override virtual
Function that will be invoked when we begin parsing a new translation unit involving this external AST source.
This function will provide all of the external definitions to the ASTConsumer.
Reimplemented from clang::ExternalASTSource.
Definition at line 8065 of file ASTReader.cpp.
takeListener()
std::unique_ptr<ASTReaderListener> clang::ASTReader::takeListener () inline
Take the AST callbacks listener.
Definition at line 1694 of file ASTReader.h.
Referenced by clang::ASTReader::ListenerScope::ListenerScope(), and clang::ASTReader::ListenerScope::~ListenerScope().
TranslateFileID()
FileID clang::ASTReader::TranslateFileID (ModuleFile & F, FileID FID) const inline
Translate a FileID from another module file's FileID space into ours.
Definition at line 2289 of file ASTReader.h.
References clang::serialization::ModuleFile::SLocEntryBaseID.
Referenced by ReadFileID().
TranslateSourceLocation()
SourceLocation clang::ASTReader::TranslateSourceLocation (ModuleFile & ModuleFile, SourceLocation Loc) const inline
Translate a source location from another module file's source location space into ours.
Definition at line 2263 of file ASTReader.h.
References clang::ContinuousRangeMap< Int, V, InitialCapacity >::end(), clang::ContinuousRangeMap< Int, V, InitialCapacity >::find(), clang::SourceLocation::getLocWithOffset(), clang::serialization::ModuleFile::ModuleOffsetMap, and clang::serialization::ModuleFile::SLocRemap.
Referenced by ReadSourceLocation().
updateOutOfDateIdentifier()
void ASTReader::updateOutOfDateIdentifier (const IdentifierInfo & II) override virtual
Update an out-of-date identifier.
Implements clang::ExternalPreprocessorSource.
Definition at line 2222 of file ASTReader.cpp.
References clang::IdentifierInfo::getName().
updateOutOfDateSelector()
void ASTReader::updateOutOfDateSelector (Selector Sel) override virtual
Load the contents of the global method pool for a given selector if necessary.
Reimplemented from clang::ExternalSemaSource.
Definition at line 8614 of file ASTReader.cpp.
References ReadMethodPool().
UpdateSema()
void ASTReader::UpdateSema ()
Update the state of Sema after loading some additional modules.
Definition at line 8247 of file ASTReader.cpp.
visitInputFileInfos()
void ASTReader::visitInputFileInfos (serialization::ModuleFile & MF, bool IncludeSystem, llvm::function_ref< void(const serialization::InputFileInfo &IFI, bool IsSystem)> Visitor)
Visit all the input file infos of the given module file.
Definition at line 9520 of file ASTReader.cpp.
References clang::serialization::ModuleFile::InputFilesLoaded, and clang::serialization::ModuleFile::NumUserInputFiles.
visitInputFiles()
void ASTReader::visitInputFiles (serialization::ModuleFile & MF, bool IncludeSystem, bool Complain, llvm::function_ref< void(const serialization::InputFile &IF, bool isSystem)> Visitor)
Visit all the input files of the given module file.
Definition at line 9536 of file ASTReader.cpp.
References clang::serialization::ModuleFile::InputFilesLoaded, and clang::serialization::ModuleFile::NumUserInputFiles.
visitTopLevelModuleMaps()
void ASTReader::visitTopLevelModuleMaps (serialization::ModuleFile & MF, llvm::function_ref< void(FileEntryRef)> Visitor)
Visit all the top-level module maps loaded when building the given module file.
Definition at line 9551 of file ASTReader.cpp.
References clang::serialization::ModuleFile::InputFilesLoaded, clang::serialization::InputFileInfo::ModuleMap, and clang::serialization::InputFileInfo::TopLevel.
Referenced by clang::FrontendAction::BeginSourceFile().
Friends And Related Function Documentation
ASTDeclReader
friend class ASTDeclReader friend
Types of AST files.
Definition at line 369 of file ASTReader.h.
ASTIdentifierIterator
friend class ASTIdentifierIterator friend
Definition at line 370 of file ASTReader.h.
Referenced by getIdentifiers().
ASTRecordReader
friend class ASTRecordReader friend
Definition at line 371 of file ASTReader.h.
ASTUnit
friend class ASTUnit friend
Definition at line 372 of file ASTReader.h.
ASTWriter
friend class ASTWriter friend
Definition at line 373 of file ASTReader.h.
PCHValidator
friend class PCHValidator friend
Definition at line 374 of file ASTReader.h.
serialization::reader::ASTIdentifierLookupTrait
friend class serialization::reader::ASTIdentifierLookupTrait friend
Definition at line 375 of file ASTReader.h.
serialization::ReadMethodPoolVisitor
friend class serialization::ReadMethodPoolVisitor friend
Definition at line 376 of file ASTReader.h.
TypeLocReader
friend class TypeLocReader friend
Definition at line 377 of file ASTReader.h.
Member Data Documentation
CommentsCursors
SmallVector<std::pair<llvm::BitstreamCursor, serialization::ModuleFile *>, 8> clang::ASTReader::CommentsCursors
Cursors for comments blocks.
Definition at line 2413 of file ASTReader.h.
PreloadedDeclIDs
SmallVector<serialization::GlobalDeclID, 16> clang::ASTReader::PreloadedDeclIDs
Definition at line 2386 of file ASTReader.h.
Referenced by SetGloballyVisibleDecls().
The documentation for this class was generated from the following files:
include/clang/Serialization/ASTReader.h
lib/Serialization/ASTReader.cpp
lib/Serialization/ASTReaderDecl.cpp
lib/Serialization/ASTReaderStmt.cpp