clang: clang::interp::InterpFrame Class Reference
clang::interp::InterpFrame Class Reference final
Frame storing local variables.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/InterpFrame.h"
Public Member Functions
InterpFrame (InterpState &S, const Function *Func, InterpFrame *Caller, CodePtr RetPC, unsigned ArgSize)
Creates a new frame for a method call.
InterpFrame (InterpState &S, const Function *Func, CodePtr RetPC, unsigned VarArgSize=0)
Creates a new frame with the values that make sense.
~InterpFrame ()
Destroys the frame, killing all live pointers to stack slots.
void destroy (unsigned Idx)
Invokes the destructors for a scope.
void popArgs ()
Pops the arguments off the stack.
void describe (llvm::raw_ostream &OS) const override
Describes the frame with arguments for diagnostic purposes.
Frame * getCaller () const override
Returns the parent frame object.
SourceRange getCallRange () const override
Returns the location of the call to the frame.
const FunctionDecl * getCallee () const override
Returns the caller.
const Function * getFunction () const
Returns the current function.
size_t getFrameOffset () const
Returns the offset on the stack at which the frame starts.
template<typename T >
const T & getLocal (unsigned Offset) const
Returns the value of a local variable.
template<typename T >
void setLocal (unsigned Offset, const T &Value)
Mutates a local variable.
Pointer getLocalPointer (unsigned Offset) const
Returns a pointer to a local variables.
template<typename T >
const T & getParam (unsigned Offset) const
Returns the value of an argument.
template<typename T >
void setParam (unsigned Offset, const T &Value)
Mutates a local copy of a parameter.
Pointer getParamPointer (unsigned Offset)
Returns a pointer to an argument - lazily creates a block.
const Pointer & getThis () const
Returns the 'this' pointer.
const Pointer & getRVOPtr () const
Returns the RVO pointer, if the Function has one.
bool isRoot () const
Checks if the frame is a root frame - return should quit the interpreter.
CodePtr getPC () const
Returns the PC of the frame's code start.
CodePtr getRetPC () const
Returns the return address of the frame.
virtual SourceInfo getSource (CodePtr PC) const
Map a location to a source.
const Expr * getExpr (CodePtr PC) const
SourceLocation getLocation (CodePtr PC) const
SourceRange getRange (CodePtr PC) const
unsigned getDepth () const
void dump () const
void dump (llvm::raw_ostream &OS, unsigned Indent=0) const
Public Member Functions inherited from clang::interp::Frame
virtual ~Frame ()
Public Attributes
InterpFrame * Caller
The frame of the previous function.
Detailed Description
Frame storing local variables.
Definition at line 28 of file InterpFrame.h.
Constructor & Destructor Documentation
InterpFrame() [1/2]
InterpFrame::InterpFrame (InterpState & S, const Function * Func, InterpFrame * Caller, CodePtr RetPC, unsigned ArgSize)
Creates a new frame for a method call.
Definition at line 24 of file InterpFrame.cpp.
InterpFrame() [2/2]
InterpFrame::InterpFrame (InterpState & S, const Function * Func, CodePtr RetPC, unsigned VarArgSize = 0)
Creates a new frame with the values that make sense.
I.e., the caller is the current frame of S, the This() pointer is the current Pointer on the top of S's stack, and the RVO pointer is before that.
Definition at line 46 of file InterpFrame.cpp.
~InterpFrame()
InterpFrame::~InterpFrame ()
Destroys the frame, killing all live pointers to stack slots.
Definition at line 66 of file InterpFrame.cpp.
References clang::interp::InterpState::deallocate(), clang::interp::Block::invokeDtor(), clang::interp::Block::isInitialized(), clang::interp::Scope::locals(), and clang::interp::Function::scopes().
Member Function Documentation
describe()
void InterpFrame::describe (llvm::raw_ostream & OS) const override virtual
Describes the frame with arguments for diagnostic purposes.
Implements clang::interp::Frame.
Definition at line 154 of file InterpFrame.cpp.
References clang::interp::align(), clang::interp::Context::classify(), clang::interp::InterpState::Ctx, getCallee(), clang::interp::InterpState::getCtx(), getFunction(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::ASTContext::getRecordType(), clang::ValueDecl::getType(), clang::interp::Function::hasRVO(), clang::interp::Function::hasThisPointer(), clang::interp::Function::isBuiltin(), clang::interp::primSize(), print(), clang::interp::PT_Ptr, and TYPE_SWITCH.
Referenced by dump().
destroy()
void InterpFrame::destroy (unsigned Idx)
Invokes the destructors for a scope.
Definition at line 84 of file InterpFrame.cpp.
References clang::interp::InterpState::deallocate(), clang::interp::Function::getScope(), and clang::interp::Scope::locals().
dump() [1/2]
void clang::interp::InterpFrame::dump () const inline
Definition at line 126 of file InterpFrame.h.
References dump().
Referenced by dump().
dump() [2/2]
LLVM_DUMP_METHOD void InterpFrame::dump (llvm::raw_ostream & OS, unsigned Indent = 0) const
Definition at line 211 of file Disasm.cpp.
References Caller, describe(), getCallee(), getDepth(), getFunction(), getRVOPtr(), getThis(), and clang::Indent().
getCallee()
const FunctionDecl * InterpFrame::getCallee () const override virtual
Returns the caller.
Implements clang::interp::Frame.
Definition at line 199 of file InterpFrame.cpp.
References clang::interp::Function::getDecl().
Referenced by describe(), and dump().
getCaller()
Frame * InterpFrame::getCaller () const override virtual
Returns the parent frame object.
Implements clang::interp::Frame.
Definition at line 187 of file InterpFrame.cpp.
References Caller, and clang::interp::InterpState::getSplitFrame().
getCallRange()
SourceRange InterpFrame::getCallRange () const override virtual
Returns the location of the call to the frame.
Implements clang::interp::Frame.
Definition at line 193 of file InterpFrame.cpp.
References Caller, and clang::interp::SourceMapper::getRange().
getDepth()
unsigned clang::interp::InterpFrame::getDepth () const inline
Definition at line 124 of file InterpFrame.h.
Referenced by dump(), and clang::interp::InterpState::getCallStackDepth().
getExpr()
const Expr * InterpFrame::getExpr (CodePtr PC) const
Definition at line 240 of file InterpFrame.cpp.
References Caller, clang::interp::Function::getDecl(), getExpr(), clang::interp::SourceMapper::getExpr(), clang::interp::Function::hasBody(), and clang::Decl::isImplicit().
Referenced by getExpr().
getFrameOffset()
size_t clang::interp::InterpFrame::getFrameOffset () const inline
Returns the offset on the stack at which the frame starts.
Definition at line 69 of file InterpFrame.h.
getFunction()
const Function* clang::interp::InterpFrame::getFunction () const inline
Returns the current function.
Definition at line 66 of file InterpFrame.h.
Referenced by describe(), and dump().
getLocal()
template<typename T > const T& clang::interp::InterpFrame::getLocal (unsigned Offset) const inline
Returns the value of a local variable.
Definition at line 72 of file InterpFrame.h.
References Offset.
getLocalPointer()
Pointer InterpFrame::getLocalPointer (unsigned Offset) const
Returns a pointer to a local variables.
Definition at line 205 of file InterpFrame.cpp.
References Offset.
getLocation()
SourceLocation InterpFrame::getLocation (CodePtr PC) const
Definition at line 247 of file InterpFrame.cpp.
References Caller, clang::interp::Function::getDecl(), getLocation(), clang::interp::SourceMapper::getLocation(), clang::interp::Function::hasBody(), and clang::Decl::isImplicit().
Referenced by getLocation().
getParam()
template<typename T > const T& clang::interp::InterpFrame::getParam (unsigned Offset) const inline
Returns the value of an argument.
Definition at line 86 of file InterpFrame.h.
References clang::interp::Pointer::deref(), Offset, and clang::T.
getParamPointer()
Pointer InterpFrame::getParamPointer (unsigned Offset)
Returns a pointer to an argument - lazily creates a block.
Definition at line 210 of file InterpFrame.cpp.
References clang::interp::Function::getParamDescriptor(), clang::T, and TYPE_SWITCH.
Referenced by setParam().
getPC()
CodePtr clang::interp::InterpFrame::getPC () const inline
Returns the PC of the frame's code start.
Definition at line 113 of file InterpFrame.h.
References clang::interp::Function::getCodeBegin().
getRange()
SourceRange InterpFrame::getRange (CodePtr PC) const
Definition at line 254 of file InterpFrame.cpp.
References Caller, clang::interp::Function::getDecl(), getRange(), clang::interp::SourceMapper::getRange(), clang::interp::Function::hasBody(), and clang::Decl::isImplicit().
Referenced by getRange().
getRetPC()
CodePtr clang::interp::InterpFrame::getRetPC () const inline
Returns the return address of the frame.
Definition at line 116 of file InterpFrame.h.
getRVOPtr()
const Pointer& clang::interp::InterpFrame::getRVOPtr () const inline
Returns the RVO pointer, if the Function has one.
Definition at line 107 of file InterpFrame.h.
Referenced by dump().
getSource()
SourceInfo InterpFrame::getSource (CodePtr PC) const virtual
Map a location to a source.
Definition at line 231 of file InterpFrame.cpp.
References Caller, clang::interp::Function::getDecl(), getSource(), clang::interp::InterpState::getSource(), clang::interp::Function::hasBody(), and clang::Decl::isImplicit().
Referenced by getSource().
getThis()
const Pointer& clang::interp::InterpFrame::getThis () const inline
Returns the 'this' pointer.
Definition at line 104 of file InterpFrame.h.
Referenced by dump().
isRoot()
bool clang::interp::InterpFrame::isRoot () const inline
Checks if the frame is a root frame - return should quit the interpreter.
Definition at line 110 of file InterpFrame.h.
popArgs()
void InterpFrame::popArgs ()
Pops the arguments off the stack.
Definition at line 90 of file InterpFrame.cpp.
References clang::interp::Function::args_reverse(), clang::interp::InterpStack::discard(), clang::interp::InterpState::Stk, clang::T, and TYPE_SWITCH.
setLocal()
template<typename T > void clang::interp::InterpFrame::setLocal (unsigned Offset, const T & Value) inline
Mutates a local variable.
Definition at line 77 of file InterpFrame.h.
References clang::interp::InlineDescriptor::IsInitialized, and Offset.
setParam()
template<typename T > void clang::interp::InterpFrame::setParam (unsigned Offset, const T & Value) inline
Mutates a local copy of a parameter.
Definition at line 96 of file InterpFrame.h.
References clang::interp::Pointer::deref(), getParamPointer(), Offset, and clang::T.
Member Data Documentation
Caller
InterpFrame* clang::interp::InterpFrame::Caller
The frame of the previous function.
Definition at line 31 of file InterpFrame.h.
Referenced by dump(), getCaller(), getCallRange(), clang::interp::InterpState::getCurrentFrame(), getExpr(), getLocation(), getRange(), and getSource().
The documentation for this class was generated from the following files:
lib/AST/Interp/InterpFrame.h
lib/AST/Interp/Disasm.cpp
lib/AST/Interp/InterpFrame.cpp