clang: clang::CXXScopeSpec Class Reference
clang::CXXScopeSpec Class Reference
Represents a C++ nested-name-specifier or a global scope specifier.
#include "clang/Sema/DeclSpec.h"
Public Member Functions
SourceRange getRange () const
void setRange (SourceRange R)
void setBeginLoc (SourceLocation Loc)
void setEndLoc (SourceLocation Loc)
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
NestedNameSpecifier * getScopeRep () const
Retrieve the representation of the nested-name-specifier.
void Extend (ASTContext &Context, SourceLocation TemplateKWLoc, TypeLoc TL, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'type::'.
void Extend (ASTContext &Context, IdentifierInfo *Identifier, SourceLocation IdentifierLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'identifier::'.
void Extend (ASTContext &Context, NamespaceDecl *Namespace, SourceLocation NamespaceLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'namespace::'.
void Extend (ASTContext &Context, NamespaceAliasDecl *Alias, SourceLocation AliasLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'namespace-alias::'.
void MakeGlobal (ASTContext &Context, SourceLocation ColonColonLoc)
Turn this (empty) nested-name-specifier into the global nested-name-specifier '::'.
void MakeSuper (ASTContext &Context, CXXRecordDecl *RD, SourceLocation SuperLoc, SourceLocation ColonColonLoc)
Turns this (empty) nested-name-specifier into '__super' nested-name-specifier.
void MakeTrivial (ASTContext &Context, NestedNameSpecifier *Qualifier, SourceRange R)
Make a new nested-name-specifier from incomplete source-location information.
void Adopt (NestedNameSpecifierLoc Other)
Adopt an existing nested-name-specifier (with source-range information).
NestedNameSpecifierLoc getWithLocInContext (ASTContext &Context) const
Retrieve a nested-name-specifier with location information, copied into the given AST context.
SourceLocation getLastQualifierNameLoc () const
Retrieve the location of the name in the last qualifier in this nested name specifier.
bool isEmpty () const
No scope specifier.
bool isNotEmpty () const
A scope specifier is present, but may be valid or invalid.
bool isInvalid () const
An error occurred during parsing of the scope specifier.
bool isValid () const
A scope specifier is present, and it refers to a real scope.
void SetInvalid (SourceRange R)
Indicate that this nested-name-specifier is invalid.
bool isSet () const
Deprecated.
void clear ()
char * location_data () const
Retrieve the data associated with the source-location information.
unsigned location_size () const
Retrieve the size of the data associated with source-location information.
Detailed Description
Represents a C++ nested-name-specifier or a global scope specifier.
These can be in 3 states: 1) Not present, identified by isEmpty() 2) Present, identified by isNotEmpty() 2.a) Valid, identified by isValid() 2.b) Invalid, identified by isInvalid().
isSet() is deprecated because it mostly corresponded to "valid" but was often used as if it meant "present".
The actual scope is described by getScopeRep().
Definition at line 64 of file DeclSpec.h.
Member Function Documentation
Adopt()
void CXXScopeSpec::Adopt (NestedNameSpecifierLoc Other)
Adopt an existing nested-name-specifier (with source-range information).
Definition at line 131 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::Adopt(), clang::NestedNameSpecifierLocBuilder::Clear(), clang::NestedNameSpecifierLoc::getSourceRange(), and clang::NestedNameSpecifierLocBuilder::getSourceRange().
Referenced by clang::Sema::ActOnTemplateTypeArgument(), clang::Sema::CheckTemplateArgument(), clang::Sema::CheckTypenameType(), clang::TreeTransform< KernelBodyTransform >::RebuildCXXDependentScopeMemberExpr(), clang::TreeTransform< KernelBodyTransform >::RebuildDeclRefExpr(), clang::TreeTransform< KernelBodyTransform >::RebuildDependentNameType(), clang::TreeTransform< KernelBodyTransform >::RebuildDependentScopeDeclRefExpr(), clang::Sema::RebuildNestedNameSpecifierInCurrentInstantiation(), clang::TreeTransform< KernelBodyTransform >::RebuildUnresolvedMemberExpr(), clang::Sema::RestoreNestedNameSpecifierAnnotation(), clang::transformOMPMappableExprListClause(), clang::TreeTransform< KernelBodyTransform >::TransformTemplateArgument(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
clear()
void clang::CXXScopeSpec::clear () inline
Definition at line 212 of file DeclSpec.h.
Referenced by clang::Declarator::clear(), and clang::Parser::ParseUnqualifiedId().
Extend() [1/4]
void CXXScopeSpec::Extend (ASTContext & Context, IdentifierInfo * Identifier, SourceLocation IdentifierLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'identifier::'.
Parameters
Context The AST context in which this nested-name-specifier resides.
Identifier The identifier.
IdentifierLoc The location of the identifier.
ColonColonLoc The location of the trailing '::'.
Definition at line 64 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::Extend(), clang::SourceRange::getBegin(), clang::NestedNameSpecifierLocBuilder::getSourceRange(), Identifier, clang::SourceLocation::isInvalid(), clang::SourceRange::setBegin(), and clang::SourceRange::setEnd().
Extend() [2/4]
void CXXScopeSpec::Extend (ASTContext & Context, NamespaceAliasDecl * Alias, SourceLocation AliasLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'namespace-alias::'.
Parameters
Context The AST context in which this nested-name-specifier resides.
Alias The namespace alias.
AliasLoc The location of the namespace alias name.
ColonColonLoc The location of the trailing '::'.
Definition at line 90 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::Extend(), clang::SourceRange::getBegin(), clang::NestedNameSpecifierLocBuilder::getSourceRange(), clang::SourceLocation::isInvalid(), clang::SourceRange::setBegin(), and clang::SourceRange::setEnd().
Extend() [3/4]
void CXXScopeSpec::Extend (ASTContext & Context, NamespaceDecl * Namespace, SourceLocation NamespaceLoc, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'namespace::'.
Parameters
Context The AST context in which this nested-name-specifier resides.
Namespace The namespace.
NamespaceLoc The location of the namespace name.
ColonColonLoc The location of the trailing '::'.
Definition at line 77 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::Extend(), clang::SourceRange::getBegin(), clang::NestedNameSpecifierLocBuilder::getSourceRange(), clang::SourceLocation::isInvalid(), clang::SourceRange::setBegin(), and clang::SourceRange::setEnd().
Extend() [4/4]
void CXXScopeSpec::Extend (ASTContext & Context, SourceLocation TemplateKWLoc, TypeLoc TL, SourceLocation ColonColonLoc)
Extend the current nested-name-specifier by another nested-name-specifier component of the form 'type::'.
Parameters
Context The AST context in which this nested-name-specifier resides.
TemplateKWLoc The location of the 'template' keyword, if present.
TL The TypeLoc that describes the type preceding the '::'.
ColonColonLoc The location of the trailing '::'.
Definition at line 53 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::Extend(), clang::SourceRange::getBegin(), clang::TypeLoc::getBeginLoc(), clang::NestedNameSpecifierLocBuilder::getSourceRange(), clang::SourceLocation::isInvalid(), clang::SourceRange::setBegin(), and clang::SourceRange::setEnd().
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), and clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc().
getBeginLoc()
SourceLocation clang::CXXScopeSpec::getBeginLoc () const inline
Definition at line 73 of file DeclSpec.h.
Referenced by clang::Sema::ActOnPackExpansion(), clang::Sema::CheckUsingDeclQualifier(), clang::DeclaratorChunk::getMemberPointer(), clang::TypoCorrection::setCorrectionRange(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
getEndLoc()
SourceLocation clang::CXXScopeSpec::getEndLoc () const inline
Definition at line 74 of file DeclSpec.h.
getLastQualifierNameLoc()
SourceLocation CXXScopeSpec::getLastQualifierNameLoc () const
Retrieve the location of the name in the last qualifier in this nested name specifier.
For example, the location of bar in
///   \::foo::bar<0>::
///           ^~~
///
Definition at line 144 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLoc::getLocalBeginLoc(), clang::NestedNameSpecifierLocBuilder::getRepresentation(), and clang::NestedNameSpecifierLocBuilder::getTemporary().
Referenced by clang::Sema::computeDeclContext(), and clang::Sema::RequireCompleteDeclContext().
getRange()
SourceRange clang::CXXScopeSpec::getRange () const inline
Definition at line 69 of file DeclSpec.h.
Referenced by clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildQualifiedTemplateIdExpr(), clang::Sema::CheckUsingDeclQualifier(), clang::Sema::CheckUsingDeclRedeclaration(), diagnoseInstanceReference(), DiagnoseQualifiedMemberReference(), clang::Sema::DiagnoseUnexpandedParameterPack(), LookupMemberExprInRecord(), clang::Sema::RebuildNestedNameSpecifierInCurrentInstantiation(), clang::Sema::RequireCompleteDeclContext(), clang::Sema::RequireCompleteEnumDecl(), clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc(), and clang::Parser::TryAnnotateTypeOrScopeToken().
getScopeRep()
NestedNameSpecifier* clang::CXXScopeSpec::getScopeRep () const inline
Retrieve the representation of the nested-name-specifier.
Definition at line 77 of file DeclSpec.h.
Referenced by clang::Sema::ActOnDependentIdExpression(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::BuildQualifiedTemplateIdExpr(), clang::Sema::CheckUsingDeclQualifier(), clang::Sema::CheckUsingDeclRedeclaration(), clang::Sema::computeDeclContext(), clang::Sema::containsUnexpandedParameterPacks(), clang::Sema::DiagnoseUnexpandedParameterPack(), clang::Sema::getElaboratedType(), getRangeOfTypeInNestedNameSpecifier(), clang::Sema::isDependentScopeSpecifier(), isEmpty(), isInvalid(), isSet(), isValid(), clang::Sema::LookupQualifiedName(), clang::Sema::MatchTemplateParametersToScopeSpecifier(), clang::TreeTransform< KernelBodyTransform >::RebuildTemplateName(), clang::Sema::SaveNestedNameSpecifierAnnotation(), ScopeSpecifierHasTemplateId(), and clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc().
getWithLocInContext()
NestedNameSpecifierLoc CXXScopeSpec::getWithLocInContext (ASTContext & Context) const
Retrieve a nested-name-specifier with location information, copied into the given AST context.
Parameters
Context The context into which this nested-name-specifier will be copied.
Definition at line 151 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::getRepresentation(), and clang::NestedNameSpecifierLocBuilder::getWithLocInContext().
Referenced by clang::Sema::ActOnDependentIdExpression(), clang::Sema::ActOnDependentMemberExpr(), clang::Sema::ActOnOpenMPFromClause(), clang::Sema::ActOnOpenMPInReductionClause(), clang::Sema::ActOnOpenMPMapClause(), clang::Sema::ActOnOpenMPReductionClause(), clang::Sema::ActOnOpenMPTaskReductionClause(), clang::Sema::ActOnOpenMPToClause(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::ActOnTypeRequirement(), clang::Sema::BuildDeclarationNameExpr(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildDependentDeclRefExpr(), clang::Sema::BuildPseudoDestructorExpr(), clang::Sema::BuildTemplateIdExpr(), clang::Sema::BuildTypeConstraint(), clang::Sema::CheckTemplateArgument(), clang::Sema::RebuildNestedNameSpecifierInCurrentInstantiation(), clang::TreeTransform< KernelBodyTransform >::TransformDependentTemplateSpecializationType(), clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc(), clang::transformOMPMappableExprListClause(), and translateTemplateArgument().
isEmpty()
bool clang::CXXScopeSpec::isEmpty () const inline
No scope specifier.
Definition at line 190 of file DeclSpec.h.
References getScopeRep().
Referenced by attemptRecovery(), diagnoseInstanceReference(), DiagnoseTwoPhaseLookup(), isNotEmpty(), ParseReductionId(), clang::Parser::ParseUnqualifiedId(), clang::Sema::SaveNestedNameSpecifierAnnotation(), clang::TypoCorrection::setCorrectionRange(), clang::Parser::TryAnnotateCXXScopeToken(), clang::Parser::TryAnnotateTypeOrScopeToken(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
isInvalid()
bool clang::CXXScopeSpec::isInvalid () const inline
An error occurred during parsing of the scope specifier.
Definition at line 195 of file DeclSpec.h.
References getScopeRep().
Referenced by clang::Sema::ActOnCXXNestedNameSpecifierDecltype(), clang::Sema::ActOnTagTemplateIdType(), clang::Sema::computeDeclContext(), clang::Sema::getCurrentClass(), clang::Sema::isCurrentClassNameTypo(), clang::Sema::isDependentScopeSpecifier(), clang::Sema::RebuildNestedNameSpecifierInCurrentInstantiation(), and clang::Sema::SaveNestedNameSpecifierAnnotation().
isNotEmpty()
bool clang::CXXScopeSpec::isNotEmpty () const inline
A scope specifier is present, but may be valid or invalid.
Definition at line 192 of file DeclSpec.h.
References isEmpty().
Referenced by clang::Sema::getCurrentClass(), clang::Parser::ParseUnqualifiedId(), and clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec().
isSet()
bool clang::CXXScopeSpec::isSet () const inline
Deprecated.
Some call sites intend isNotEmpty() while others intend isValid().
Definition at line 210 of file DeclSpec.h.
References getScopeRep().
Referenced by clang::Sema::BuildTypeConstraint(), clang::Sema::computeDeclContext(), diagnoseInstanceReference(), clang::Sema::isCurrentClassNameTypo(), clang::Sema::isDependentScopeSpecifier(), LookupMemberExprInRecord(), clang::Parser::ParseUnqualifiedId(), ScopeSpecifierHasTemplateId(), and clang::Sema::UseArgumentDependentLookup().
isValid()
bool clang::CXXScopeSpec::isValid () const inline
A scope specifier is present, and it refers to a real scope.
Definition at line 197 of file DeclSpec.h.
References getScopeRep().
Referenced by clang::Sema::ActOnPackExpansion(), and clang::Sema::getElaboratedType().
location_data()
char* clang::CXXScopeSpec::location_data () const inline
Retrieve the data associated with the source-location information.
Definition at line 218 of file DeclSpec.h.
Referenced by getRangeOfTypeInNestedNameSpecifier(), clang::Sema::SaveNestedNameSpecifierAnnotation(), and clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc().
location_size()
unsigned clang::CXXScopeSpec::location_size () const inline
Retrieve the size of the data associated with source-location information.
Definition at line 222 of file DeclSpec.h.
Referenced by clang::Sema::SaveNestedNameSpecifierAnnotation(), and clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc().
MakeGlobal()
void CXXScopeSpec::MakeGlobal (ASTContext & Context, SourceLocation ColonColonLoc)
Turn this (empty) nested-name-specifier into the global nested-name-specifier '::'.
Definition at line 103 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::getSourceRange(), and clang::NestedNameSpecifierLocBuilder::MakeGlobal().
Referenced by clang::Sema::ActOnCXXGlobalScopeSpecifier(), and clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc().
MakeSuper()
void CXXScopeSpec::MakeSuper (ASTContext & Context, CXXRecordDecl * RD, SourceLocation SuperLoc, SourceLocation ColonColonLoc)
Turns this (empty) nested-name-specifier into '__super' nested-name-specifier.
Parameters
Context The AST context in which this nested-name-specifier resides.
RD The declaration of the class in which nested-name-specifier appeared.
SuperLoc The location of the '__super' keyword. name.
ColonColonLoc The location of the trailing '::'.
Definition at line 113 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::getSourceRange(), clang::NestedNameSpecifierLocBuilder::MakeSuper(), clang::SourceRange::setBegin(), and clang::SourceRange::setEnd().
Referenced by clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc().
MakeTrivial()
void CXXScopeSpec::MakeTrivial (ASTContext & Context, NestedNameSpecifier * Qualifier, SourceRange R)
Make a new nested-name-specifier from incomplete source-location information.
FIXME: This routine should be used very, very rarely, in cases where we need to synthesize a nested-name-specifier. Most code should instead use Adopt() with a proper NestedNameSpecifierLoc.
Definition at line 125 of file DeclSpec.cpp.
References clang::NestedNameSpecifierLocBuilder::MakeTrivial().
Referenced by attemptRecovery(), and clang::Sema::BuildExpressionFromDeclTemplateArgument().
setBeginLoc()
void clang::CXXScopeSpec::setBeginLoc (SourceLocation Loc) inline
Definition at line 71 of file DeclSpec.h.
setEndLoc()
void clang::CXXScopeSpec::setEndLoc (SourceLocation Loc) inline
Definition at line 72 of file DeclSpec.h.
SetInvalid()
void clang::CXXScopeSpec::SetInvalid (SourceRange R) inline
Indicate that this nested-name-specifier is invalid.
Definition at line 200 of file DeclSpec.h.
References clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), and clang::SourceRange::isValid().
Referenced by clang::Sema::RequireCompleteDeclContext(), clang::Sema::RequireCompleteEnumDecl(), and clang::Sema::RestoreNestedNameSpecifierAnnotation().
setRange()
void clang::CXXScopeSpec::setRange (SourceRange R) inline
Definition at line 70 of file DeclSpec.h.
The documentation for this class was generated from the following files:
include/clang/Sema/DeclSpec.h
lib/Sema/DeclSpec.cpp