clang: clang::VariableConstructionContext Class Reference
clang::VariableConstructionContext Class Reference
An abstract base class for local variable constructors.
#include "clang/Analysis/ConstructionContext.h"
Public Member Functions
const DeclStmt * getDeclStmt () const
const ArrayInitLoopExpr * getArrayInitLoop () const override
Public Member Functions inherited from clang::ConstructionContext
Kind getKind () const
virtual ~ConstructionContext ()=default
Static Public Member Functions
static bool classof (const ConstructionContext *CC)
Static Public Member Functions inherited from clang::ConstructionContext
static const ConstructionContext * createFromLayers (BumpVectorContext &C, const ConstructionContextLayer *TopLayer)
Consume the construction context layer, together with its parent layers, and wrap it up into a complete construction context.
Protected Member Functions
VariableConstructionContext (ConstructionContext::Kind K, const DeclStmt *DS)
Protected Member Functions inherited from clang::ConstructionContext
ConstructionContext (Kind K)
Additional Inherited Members
Public Types inherited from clang::ConstructionContext
enum Kind {
SimpleVariableKind , CXX17ElidedCopyVariableKind , VARIABLE_BEGIN = SimpleVariableKind , VARIABLE_END = CXX17ElidedCopyVariableKind ,
SimpleConstructorInitializerKind , CXX17ElidedCopyConstructorInitializerKind , INITIALIZER_BEGIN = SimpleConstructorInitializerKind , INITIALIZER_END = CXX17ElidedCopyConstructorInitializerKind ,
NewAllocatedObjectKind , SimpleTemporaryObjectKind , ElidedTemporaryObjectKind , TEMPORARY_BEGIN = SimpleTemporaryObjectKind ,
TEMPORARY_END = ElidedTemporaryObjectKind , SimpleReturnedValueKind , CXX17ElidedCopyReturnedValueKind , RETURNED_VALUE_BEGIN = SimpleReturnedValueKind ,
RETURNED_VALUE_END = CXX17ElidedCopyReturnedValueKind , ArgumentKind , LambdaCaptureKind
}
Protected Attributes inherited from clang::ConstructionContext
Kind K
Detailed Description
An abstract base class for local variable constructors.
Definition at line 316 of file ConstructionContext.h.
Constructor & Destructor Documentation
VariableConstructionContext()
clang::VariableConstructionContext::VariableConstructionContext (ConstructionContext::Kind K, const DeclStmt * DS) inline protected
Definition at line 320 of file ConstructionContext.h.
References classof().
Member Function Documentation
classof()
static bool clang::VariableConstructionContext::classof (const ConstructionContext * CC) inline static
Definition at line 335 of file ConstructionContext.h.
References clang::ConstructionContext::getKind(), clang::ConstructionContext::VARIABLE_BEGIN, and clang::ConstructionContext::VARIABLE_END.
Referenced by VariableConstructionContext().
getArrayInitLoop()
const ArrayInitLoopExpr* clang::VariableConstructionContext::getArrayInitLoop () const inline override virtual
Reimplemented from clang::ConstructionContext.
Definition at line 329 of file ConstructionContext.h.
References clang::DeclStmt::getSingleDecl().
getDeclStmt()
const DeclStmt* clang::VariableConstructionContext::getDeclStmt () const inline
Definition at line 327 of file ConstructionContext.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/ConstructionContext.h