clang: clang::SemaOpenACC::OpenACCParsedClause Class Reference
clang::SemaOpenACC::OpenACCParsedClause Class Reference
A type to represent all the data for an OpenACC Clause that has been parsed, but not yet created/semantically analyzed.
#include "clang/Sema/SemaOpenACC.h"
Public Member Functions
OpenACCParsedClause (OpenACCDirectiveKind DirKind, OpenACCClauseKind ClauseKind, SourceLocation BeginLoc)
OpenACCDirectiveKind getDirectiveKind () const
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getLParenLoc () const
SourceLocation getEndLoc () const
OpenACCDefaultClauseKind getDefaultClauseKind () const
const Expr * getConditionExpr () const
Expr * getConditionExpr ()
unsigned getNumIntExprs () const
SourceLocation getQueuesLoc () const
Expr * getDevNumExpr () const
ArrayRef< Expr * > getQueueIdExprs () const
ArrayRef< Expr * > getIntExprs ()
ArrayRef< Expr * > getIntExprs () const
OpenACCReductionOperator getReductionOp () const
ArrayRef< Expr * > getVarList ()
ArrayRef< Expr * > getVarList () const
bool isReadOnly () const
bool isZero () const
ArrayRef< DeviceTypeArgument > getDeviceTypeArchitectures () const
void setLParenLoc (SourceLocation EndLoc)
void setEndLoc (SourceLocation EndLoc)
void setDefaultDetails (OpenACCDefaultClauseKind DefKind)
void setConditionDetails (Expr *ConditionExpr)
void setIntExprDetails (ArrayRef< Expr * > IntExprs)
void setIntExprDetails (llvm::SmallVector< Expr * > &&IntExprs)
void setVarListDetails (ArrayRef< Expr * > VarList, bool IsReadOnly, bool IsZero)
void setVarListDetails (llvm::SmallVector< Expr * > &&VarList, bool IsReadOnly, bool IsZero)
void setReductionDetails (OpenACCReductionOperator Op, llvm::SmallVector< Expr * > &&VarList)
void setWaitDetails (Expr *DevNum, SourceLocation QueuesLoc, llvm::SmallVector< Expr * > &&IntExprs)
void setDeviceTypeDetails (llvm::SmallVector< DeviceTypeArgument > &&Archs)
Detailed Description
A type to represent all the data for an OpenACC Clause that has been parsed, but not yet created/semantically analyzed.
This is effectively a discriminated union on the 'Clause Kind', with all of the individual clause details stored in a std::variant.
Definition at line 46 of file SemaOpenACC.h.
Constructor & Destructor Documentation
OpenACCParsedClause()
clang::SemaOpenACC::OpenACCParsedClause::OpenACCParsedClause (OpenACCDirectiveKind DirKind, OpenACCClauseKind ClauseKind, SourceLocation BeginLoc) inline
Definition at line 90 of file SemaOpenACC.h.
Member Function Documentation
getBeginLoc()
SourceLocation clang::SemaOpenACC::OpenACCParsedClause::getBeginLoc () const inline
Definition at line 98 of file SemaOpenACC.h.
References clang::SourceRange::getBegin().
getClauseKind()
OpenACCClauseKind clang::SemaOpenACC::OpenACCParsedClause::getClauseKind () const inline
Definition at line 96 of file SemaOpenACC.h.
getConditionExpr() [1/2]
Expr* clang::SemaOpenACC::OpenACCParsedClause::getConditionExpr () inline
Definition at line 114 of file SemaOpenACC.h.
References clang::If, clang::Self, and clang::Update.
getConditionExpr() [2/2]
const Expr* clang::SemaOpenACC::OpenACCParsedClause::getConditionExpr () const inline
Definition at line 110 of file SemaOpenACC.h.
getDefaultClauseKind()
OpenACCDefaultClauseKind clang::SemaOpenACC::OpenACCParsedClause::getDefaultClauseKind () const inline
Definition at line 104 of file SemaOpenACC.h.
References clang::Default.
getDeviceTypeArchitectures()
ArrayRef<DeviceTypeArgument> clang::SemaOpenACC::OpenACCParsedClause::getDeviceTypeArchitectures () const inline
Definition at line 243 of file SemaOpenACC.h.
References clang::DeviceType, and clang::DType.
getDevNumExpr()
Expr* clang::SemaOpenACC::OpenACCParsedClause::getDevNumExpr () const inline
Definition at line 154 of file SemaOpenACC.h.
References clang::Wait.
getDirectiveKind()
OpenACCDirectiveKind clang::SemaOpenACC::OpenACCParsedClause::getDirectiveKind () const inline
Definition at line 94 of file SemaOpenACC.h.
getEndLoc()
SourceLocation clang::SemaOpenACC::OpenACCParsedClause::getEndLoc () const inline
Definition at line 102 of file SemaOpenACC.h.
References clang::SourceRange::getEnd().
getIntExprs() [1/2]
ArrayRef<Expr *> clang::SemaOpenACC::OpenACCParsedClause::getIntExprs () inline
Definition at line 174 of file SemaOpenACC.h.
References clang::Async, clang::NumGangs, clang::NumWorkers, and clang::VectorLength.
Referenced by getIntExprs().
getIntExprs() [2/2]
ArrayRef<Expr *> clang::SemaOpenACC::OpenACCParsedClause::getIntExprs () const inline
Definition at line 184 of file SemaOpenACC.h.
References getIntExprs().
getLParenLoc()
SourceLocation clang::SemaOpenACC::OpenACCParsedClause::getLParenLoc () const inline
Definition at line 100 of file SemaOpenACC.h.
getNumIntExprs()
unsigned clang::SemaOpenACC::OpenACCParsedClause::getNumIntExprs () const inline
Definition at line 129 of file SemaOpenACC.h.
References clang::Async, clang::NumGangs, clang::NumWorkers, clang::VectorLength, and clang::Wait.
getQueueIdExprs()
ArrayRef<Expr *> clang::SemaOpenACC::OpenACCParsedClause::getQueueIdExprs () const inline
Definition at line 164 of file SemaOpenACC.h.
References clang::Wait.
getQueuesLoc()
SourceLocation clang::SemaOpenACC::OpenACCParsedClause::getQueuesLoc () const inline
Definition at line 144 of file SemaOpenACC.h.
References clang::Wait.
getReductionOp()
OpenACCReductionOperator clang::SemaOpenACC::OpenACCParsedClause::getReductionOp () const inline
Definition at line 188 of file SemaOpenACC.h.
getVarList() [1/2]
ArrayRef<Expr *> clang::SemaOpenACC::OpenACCParsedClause::getVarList () inline
Definition at line 192 of file SemaOpenACC.h.
References clang::Attach, clang::Copy, clang::CopyIn, clang::CopyOut, clang::Create, clang::DevicePtr, clang::FirstPrivate, clang::NoCreate, clang::PCopy, clang::PCopyIn, clang::PCopyOut, clang::PCreate, clang::Present, clang::PresentOrCopy, clang::PresentOrCopyIn, clang::PresentOrCopyOut, clang::PresentOrCreate, clang::Private, and clang::Reduction.
Referenced by getVarList().
getVarList() [2/2]
ArrayRef<Expr *> clang::SemaOpenACC::OpenACCParsedClause::getVarList () const inline
Definition at line 220 of file SemaOpenACC.h.
References getVarList().
isReadOnly()
bool clang::SemaOpenACC::OpenACCParsedClause::isReadOnly () const inline
Definition at line 224 of file SemaOpenACC.h.
References clang::CopyIn, clang::PCopyIn, and clang::PresentOrCopyIn.
isZero()
bool clang::SemaOpenACC::OpenACCParsedClause::isZero () const inline
Definition at line 232 of file SemaOpenACC.h.
References clang::CopyOut, clang::Create, clang::PCopyOut, clang::PCreate, clang::PresentOrCopyOut, and clang::PresentOrCreate.
setConditionDetails()
void clang::SemaOpenACC::OpenACCParsedClause::setConditionDetails (Expr * ConditionExpr) inline
Definition at line 259 of file SemaOpenACC.h.
References clang::Expr::getType(), clang::If, clang::Expr::isInstantiationDependent(), clang::Type::isScalarType(), clang::Self, and clang::Update.
setDefaultDetails()
void clang::SemaOpenACC::OpenACCParsedClause::setDefaultDetails (OpenACCDefaultClauseKind DefKind) inline
Definition at line 253 of file SemaOpenACC.h.
References clang::Default.
setDeviceTypeDetails()
void clang::SemaOpenACC::OpenACCParsedClause::setDeviceTypeDetails (llvm::SmallVector< DeviceTypeArgument > && Archs) inline
Definition at line 375 of file SemaOpenACC.h.
References clang::DeviceType, and clang::DType.
setEndLoc()
void clang::SemaOpenACC::OpenACCParsedClause::setEndLoc (SourceLocation EndLoc) inline
Definition at line 251 of file SemaOpenACC.h.
References clang::SourceRange::setEnd().
setIntExprDetails() [1/2]
void clang::SemaOpenACC::OpenACCParsedClause::setIntExprDetails (ArrayRef< Expr * > IntExprs) inline
Definition at line 273 of file SemaOpenACC.h.
References clang::Async, clang::NumGangs, clang::NumWorkers, and clang::VectorLength.
setIntExprDetails() [2/2]
void clang::SemaOpenACC::OpenACCParsedClause::setIntExprDetails (llvm::SmallVector< Expr * > && IntExprs) inline
Definition at line 281 of file SemaOpenACC.h.
References clang::Async, clang::NumGangs, clang::NumWorkers, and clang::VectorLength.
setLParenLoc()
void clang::SemaOpenACC::OpenACCParsedClause::setLParenLoc (SourceLocation EndLoc) inline
Definition at line 250 of file SemaOpenACC.h.
setReductionDetails()
void clang::SemaOpenACC::OpenACCParsedClause::setReductionDetails (OpenACCReductionOperator Op, llvm::SmallVector< Expr * > && VarList) inline
Definition at line 361 of file SemaOpenACC.h.
References clang::Reduction.
setVarListDetails() [1/2]
void clang::SemaOpenACC::OpenACCParsedClause::setVarListDetails (ArrayRef< Expr * > VarList, bool IsReadOnly, bool IsZero) inline
Definition at line 290 of file SemaOpenACC.h.
References clang::Attach, clang::Copy, clang::CopyIn, clang::CopyOut, clang::Create, clang::DevicePtr, clang::FirstPrivate, clang::NoCreate, clang::PCopy, clang::PCopyIn, clang::PCopyOut, clang::PCreate, clang::Present, clang::PresentOrCopy, clang::PresentOrCopyIn, clang::PresentOrCopyOut, clang::PresentOrCreate, and clang::Private.
setVarListDetails() [2/2]
void clang::SemaOpenACC::OpenACCParsedClause::setVarListDetails (llvm::SmallVector< Expr * > && VarList, bool IsReadOnly, bool IsZero) inline
Definition at line 326 of file SemaOpenACC.h.
References clang::Attach, clang::Copy, clang::CopyIn, clang::CopyOut, clang::Create, clang::DevicePtr, clang::FirstPrivate, clang::NoCreate, clang::PCopy, clang::PCopyIn, clang::PCopyOut, clang::PCreate, clang::Present, clang::PresentOrCopy, clang::PresentOrCopyIn, clang::PresentOrCopyOut, clang::PresentOrCreate, and clang::Private.
setWaitDetails()
void clang::SemaOpenACC::OpenACCParsedClause::setWaitDetails (Expr * DevNum, SourceLocation QueuesLoc, llvm::SmallVector< Expr * > && IntExprs) inline
Definition at line 368 of file SemaOpenACC.h.
References clang::Wait.
The documentation for this class was generated from the following file:
include/clang/Sema/SemaOpenACC.h