clang: clang::CodeGen::CodeGenFunction::ParamValue Class Reference
clang::CodeGen::CodeGenFunction::ParamValue Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
bool isIndirect () const
llvm::Value * getAnyValue () const
llvm::Value * getDirectValue () const
Address getIndirectAddress () const
Static Public Member Functions
static ParamValue forDirect (llvm::Value *value)
static ParamValue forIndirect (Address addr)
Detailed Description
Definition at line 3374 of file CodeGenFunction.h.
Member Function Documentation
forDirect()
static ParamValue clang::CodeGen::CodeGenFunction::ParamValue::forDirect (llvm::Value * value) inline static
Definition at line 3386 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), and clang::CodeGen::CodeGenFunction::EmitInlinedInheritingCXXConstructorCall().
forIndirect()
static ParamValue clang::CodeGen::CodeGenFunction::ParamValue::forIndirect (Address addr) inline static
Definition at line 3389 of file CodeGenFunction.h.
References clang::CodeGen::Address::getAlignment(), and clang::CharUnits::isZero().
Referenced by clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), and clang::CodeGen::CodeGenFunction::EmitInlinedInheritingCXXConstructorCall().
getAnyValue()
llvm::Value* clang::CodeGen::CodeGenFunction::ParamValue::getAnyValue () const inline
Definition at line 3395 of file CodeGenFunction.h.
References Addr, clang::CodeGen::Address::getBasePointer(), clang::CodeGen::Address::hasOffset(), isIndirect(), and Value.
Referenced by clang::CodeGen::CodeGenFunction::EmitParmDecl().
getDirectValue()
llvm::Value* clang::CodeGen::CodeGenFunction::ParamValue::getDirectValue () const inline
Definition at line 3402 of file CodeGenFunction.h.
References isIndirect(), and Value.
Referenced by clang::CodeGen::CodeGenFunction::EmitParmDecl().
getIndirectAddress()
Address clang::CodeGen::CodeGenFunction::ParamValue::getIndirectAddress () const inline
Definition at line 3407 of file CodeGenFunction.h.
References Addr, and isIndirect().
Referenced by clang::CodeGen::CodeGenFunction::EmitParmDecl().
isIndirect()
bool clang::CodeGen::CodeGenFunction::ParamValue::isIndirect () const inline
Definition at line 3394 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitParmDecl(), getAnyValue(), getDirectValue(), and getIndirectAddress().
Member Data Documentation
Addr
Address clang::CodeGen::CodeGenFunction::ParamValue::Addr
Definition at line 3376 of file CodeGenFunction.h.
Referenced by getAnyValue(), and getIndirectAddress().
Value
llvm::Value* clang::CodeGen::CodeGenFunction::ParamValue::Value
Definition at line 3377 of file CodeGenFunction.h.
Referenced by getAnyValue(), and getDirectValue().
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h