clang: clang::api_notes::ObjCPropertyInfo Class Reference
clang::api_notes::ObjCPropertyInfo Class Reference
Describes API notes data for an Objective-C property.
#include "clang/APINotes/Types.h"
Public Member Functions
ObjCPropertyInfo ()
llvm::Optional< bool > getSwiftImportAsAccessors () const
void setSwiftImportAsAccessors (llvm::Optional< bool > Value)
ObjCPropertyInfo & operator|= (const ObjCContextInfo &RHS)
Merge class-wide information into the given property.
ObjCPropertyInfo & operator|= (const ObjCPropertyInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::VariableInfo
VariableInfo ()
llvm::Optional< NullabilityKind > getNullability () const
void setNullabilityAudited (NullabilityKind kind)
const std::string & getType () const
void setType (const std::string &type)
VariableInfo & operator|= (const VariableInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::CommonEntityInfo
CommonEntityInfo ()
llvm::Optional< bool > isSwiftPrivate () const
void setSwiftPrivate (llvm::Optional< bool > Private)
CommonEntityInfo & operator|= (const CommonEntityInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Friends
bool operator== (const ObjCPropertyInfo &, const ObjCPropertyInfo &)
Additional Inherited Members
Public Attributes inherited from clang::api_notes::CommonEntityInfo
std::string UnavailableMsg
Message to use when this entity is unavailable.
unsigned Unavailable: 1
Whether this entity is marked unavailable.
unsigned UnavailableInSwift: 1
Whether this entity is marked unavailable in Swift.
std::string SwiftName
Swift name of this entity.
Detailed Description
Describes API notes data for an Objective-C property.
Definition at line 354 of file Types.h.
Constructor & Destructor Documentation
ObjCPropertyInfo()
clang::api_notes::ObjCPropertyInfo::ObjCPropertyInfo () inline
Definition at line 359 of file Types.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::api_notes::ObjCPropertyInfo::dump (llvm::raw_ostream & OS) const
Definition at line 57 of file APINotesTypes.cpp.
References clang::api_notes::VariableInfo::dump().
getSwiftImportAsAccessors()
llvm::Optional<bool> clang::api_notes::ObjCPropertyInfo::getSwiftImportAsAccessors () const inline
Definition at line 362 of file Types.h.
Referenced by clang::api_notes::operator==(), and operator|=().
operator|=() [1/2]
ObjCPropertyInfo& clang::api_notes::ObjCPropertyInfo::operator|= (const ObjCContextInfo & RHS) inline
Merge class-wide information into the given property.
Definition at line 375 of file Types.h.
References clang::api_notes::ObjCContextInfo::getDefaultNullability(), clang::api_notes::VariableInfo::getNullability(), clang::Nullable, and clang::api_notes::VariableInfo::setNullabilityAudited().
operator|=() [2/2]
ObjCPropertyInfo& clang::api_notes::ObjCPropertyInfo::operator|= (const ObjCPropertyInfo & RHS) inline
Definition at line 386 of file Types.h.
References getSwiftImportAsAccessors(), and setSwiftImportAsAccessors().
setSwiftImportAsAccessors()
void clang::api_notes::ObjCPropertyInfo::setSwiftImportAsAccessors (llvm::Optional< bool > Value) inline
Definition at line 367 of file Types.h.
Referenced by operator|=().
Friends And Related Function Documentation
operator==
bool operator== (const ObjCPropertyInfo & LHS, const ObjCPropertyInfo & RHS) friend
Definition at line 398 of file Types.h.
The documentation for this class was generated from the following files:
include/clang/APINotes/Types.h
lib/APINotes/APINotesTypes.cpp