clang: clang::format::UnwrappedLineParser Class Reference
clang::format::UnwrappedLineParser Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Format/UnwrappedLineParser.h"
Public Member Functions
UnwrappedLineParser (SourceManager &SourceMgr, const FormatStyle &Style, const AdditionalKeywords &Keywords, unsigned FirstStartColumn, ArrayRef< FormatToken * > Tokens, UnwrappedLineConsumer &Callback, llvm::SpecificBumpPtrAllocator< FormatToken > &Allocator, IdentifierTable &IdentTable)
void parse ()
Friends
class ScopedLineState
class CompoundStatementIndenter
Detailed Description
Definition at line 98 of file UnwrappedLineParser.h.
Constructor & Destructor Documentation
UnwrappedLineParser()
clang::format::UnwrappedLineParser::UnwrappedLineParser (SourceManager & SourceMgr, const FormatStyle & Style, const AdditionalKeywords & Keywords, unsigned FirstStartColumn, ArrayRef< FormatToken * > Tokens, UnwrappedLineConsumer & Callback, llvm::SpecificBumpPtrAllocator< FormatToken > & Allocator, IdentifierTable & IdentTable)
Definition at line 155 of file UnwrappedLineParser.cpp.
Member Function Documentation
parse()
void clang::format::UnwrappedLineParser::parse ()
Definition at line 200 of file UnwrappedLineParser.cpp.
References clang::format::UnwrappedLineConsumer::consumeUnwrappedLine(), clang::format::UnwrappedLineConsumer::finishRun(), and clang::format::IndexedTokenSource::reset().
Friends And Related Function Documentation
CompoundStatementIndenter
friend class CompoundStatementIndenter friend
Definition at line 402 of file UnwrappedLineParser.h.
ScopedLineState
friend class ScopedLineState friend
Definition at line 401 of file UnwrappedLineParser.h.
The documentation for this class was generated from the following files:
lib/Format/UnwrappedLineParser.h
lib/Format/UnwrappedLineParser.cpp