clang: clang::driver::Tool Class Reference
clang::driver::Tool Class Reference abstract
Tool - Information on a specific compilation tool.
#include "clang/Driver/Tool.h"
Inherited by clang::driver::tools::aix::Assembler, clang::driver::tools::aix::Linker, clang::driver::tools::AMDGCN::Linker, clang::driver::tools::AMDGCN::OpenMPLinker, clang::driver::tools::amdgpu::Linker, clang::driver::tools::ananas::Assembler, clang::driver::tools::ananas::Linker, clang::driver::tools::AppendFooter, clang::driver::tools::AVR::Linker, clang::driver::tools::baremetal::Linker, clang::driver::tools::Clang, clang::driver::tools::ClangAs, clang::driver::tools::cloudabi::Linker, clang::driver::tools::CrossWindows::Assembler, clang::driver::tools::CrossWindows::Linker, clang::driver::tools::darwin::MachOTool, clang::driver::tools::dragonfly::Assembler, clang::driver::tools::dragonfly::Linker, clang::driver::tools::FileTableTform, clang::driver::tools::Flang, clang::driver::tools::freebsd::Assembler, clang::driver::tools::freebsd::Linker, clang::driver::tools::fuchsia::Linker, clang::driver::tools::gcc::Common, clang::driver::tools::gnutools::Assembler, clang::driver::tools::gnutools::Linker, clang::driver::tools::gnutools::StaticLibTool, clang::driver::tools::hexagon::Assembler, clang::driver::tools::hexagon::Linker, clang::driver::tools::HIPSPV::Linker, clang::driver::tools::ifstool::Merger, clang::driver::tools::LinkerWrapper, clang::driver::tools::MinGW::Assembler, clang::driver::tools::MinGW::Linker, clang::driver::tools::minix::Assembler, clang::driver::tools::minix::Linker, clang::driver::tools::msp430::Linker, clang::driver::tools::Myriad::Linker, clang::driver::tools::nacltools::Linker, clang::driver::tools::netbsd::Assembler, clang::driver::tools::netbsd::Linker, clang::driver::tools::NVPTX::Assembler, clang::driver::tools::NVPTX::Linker, clang::driver::tools::NVPTX::OpenMPLinker, clang::driver::tools::OffloadBundler, clang::driver::tools::OffloadDeps, clang::driver::tools::OffloadWrapper, clang::driver::tools::openbsd::Assembler, clang::driver::tools::openbsd::Linker, clang::driver::tools::PS4cpu::Assemble, clang::driver::tools::PS4cpu::Link, clang::driver::tools::RISCV::Linker, clang::driver::tools::SHAVE::Assembler, clang::driver::tools::SHAVE::Compiler, clang::driver::tools::solaris::Assembler, clang::driver::tools::solaris::Linker, clang::driver::tools::SPIRCheck, clang::driver::tools::SPIRV::Linker, clang::driver::tools::SPIRV::Translator, clang::driver::tools::SpirvToIrWrapper, clang::driver::tools::SPIRVTranslator, clang::driver::tools::SYCL::fpga::BackendCompiler, clang::driver::tools::SYCL::gen::BackendCompiler, clang::driver::tools::SYCL::Linker, clang::driver::tools::SYCL::x86_64::BackendCompiler, clang::driver::tools::SYCLPostLink, clang::driver::tools::visualstudio::Linker, clang::driver::tools::wasm::Linker, clang::driver::tools::XCore::Assembler, and clang::driver::tools::XCore::Linker.
Public Member Functions
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool hasIntegratedCPP () const =0
virtual bool isLinkJob () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const =0
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Tool - Information on a specific compilation tool.
Definition at line 32 of file Tool.h.
Constructor & Destructor Documentation
Tool()
Tool::Tool (const char * Name, const char * ShortName, const ToolChain & TC)
Definition at line 14 of file Tool.cpp.
~Tool()
Tool::~Tool () virtual
Definition at line 17 of file Tool.cpp.
Member Function Documentation
canEmitIR()
virtual bool clang::driver::Tool::canEmitIR () const inline virtual
Reimplemented in clang::driver::tools::Clang, and clang::driver::tools::Flang.
Definition at line 56 of file Tool.h.
ConstructJob()
virtual void clang::driver::Tool::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const pure virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implemented in clang::driver::tools::LinkerWrapper, clang::driver::tools::SpirvToIrWrapper, clang::driver::tools::AppendFooter, clang::driver::tools::FileTableTform, clang::driver::tools::SYCLPostLink, clang::driver::tools::SPIRCheck, clang::driver::tools::SPIRVTranslator, clang::driver::tools::OffloadDeps, clang::driver::tools::OffloadWrapper, clang::driver::tools::OffloadBundler, clang::driver::tools::ClangAs, clang::driver::tools::darwin::VerifyDebug, clang::driver::tools::NVPTX::OpenMPLinker, clang::driver::tools::Clang, clang::driver::tools::SYCL::x86_64::BackendCompiler, clang::driver::tools::darwin::Dsymutil, clang::driver::tools::NVPTX::Linker, clang::driver::tools::SYCL::gen::BackendCompiler, clang::driver::tools::darwin::Lipo, clang::driver::tools::gcc::Common, clang::driver::tools::NVPTX::Assembler, clang::driver::tools::baremetal::Linker, clang::driver::tools::darwin::StaticLibTool, clang::driver::tools::gnutools::StaticLibTool, clang::driver::tools::SYCL::fpga::BackendCompiler, clang::driver::tools::darwin::Linker, clang::driver::tools::msp430::Linker, clang::driver::tools::gnutools::Linker, clang::driver::tools::AVR::Linker, clang::driver::tools::Flang, clang::driver::tools::Myriad::Linker, clang::driver::tools::darwin::Assembler, clang::driver::tools::RISCV::Linker, clang::driver::tools::SYCL::Linker, clang::driver::tools::PS4cpu::Link, clang::driver::tools::gnutools::Assembler, clang::driver::tools::hexagon::Linker, clang::driver::tools::SPIRV::Linker, clang::driver::tools::MinGW::Linker, clang::driver::tools::openbsd::Linker, clang::driver::tools::CrossWindows::Linker, clang::driver::tools::freebsd::Linker, clang::driver::tools::solaris::Linker, clang::driver::tools::aix::Linker, clang::driver::tools::ananas::Linker, clang::driver::tools::dragonfly::Linker, clang::driver::tools::netbsd::Linker, clang::driver::tools::minix::Linker, clang::driver::tools::SHAVE::Assembler, clang::driver::tools::XCore::Linker, clang::driver::tools::nacltools::Linker, clang::driver::tools::SPIRV::Translator, clang::driver::tools::AMDGCN::OpenMPLinker, clang::driver::tools::PS4cpu::Assemble, clang::driver::tools::amdgpu::Linker, clang::driver::tools::visualstudio::Linker, clang::driver::tools::hexagon::Assembler, clang::driver::tools::MinGW::Assembler, clang::driver::tools::AMDGCN::Linker, clang::driver::tools::openbsd::Assembler, clang::driver::tools::cloudabi::Linker, clang::driver::tools::CrossWindows::Assembler, clang::driver::tools::freebsd::Assembler, clang::driver::tools::HIPSPV::Linker, clang::driver::tools::solaris::Assembler, clang::driver::tools::aix::Assembler, clang::driver::tools::ananas::Assembler, clang::driver::tools::dragonfly::Assembler, clang::driver::tools::fuchsia::Linker, clang::driver::tools::SHAVE::Compiler, clang::driver::tools::netbsd::Assembler, clang::driver::tools::XCore::Assembler, clang::driver::tools::minix::Assembler, clang::driver::tools::wasm::Linker, clang::driver::tools::ifstool::Merger, and clang::driver::tools::nacltools::AssemblerARM.
Referenced by clang::driver::tools::LinkerWrapper::ConstructJob(), and ConstructJobMultipleOutputs().
ConstructJobMultipleOutputs()
void Tool::ConstructJobMultipleOutputs (Compilation & C, const JobAction & JA, const InputInfoList & Outputs, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const virtual
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
The default implementation assumes a single output and is expected to be overloaded for the tools that support multiple inputs.
Parameters
TCArgs The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput If this output will eventually feed the linker, then this is the final output name of the linked image.
Reimplemented in clang::driver::tools::OffloadDeps, and clang::driver::tools::OffloadBundler.
Definition at line 20 of file Tool.cpp.
References ConstructJob().
getName()
const char* clang::driver::Tool::getName () const inline
Definition at line 48 of file Tool.h.
getShortName()
const char* clang::driver::Tool::getShortName () const inline
Definition at line 50 of file Tool.h.
Referenced by clang::driver::tools::ifstool::Merger::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::SPIRVTranslator::ConstructJob(), clang::driver::tools::SPIRCheck::ConstructJob(), clang::driver::tools::SYCLPostLink::ConstructJob(), clang::driver::tools::FileTableTform::ConstructJob(), clang::driver::tools::AppendFooter::ConstructJob(), clang::driver::tools::SpirvToIrWrapper::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), and clang::driver::Driver::ExecuteCompilation().
getToolChain()
const ToolChain& clang::driver::Tool::getToolChain () const inline
Definition at line 52 of file Tool.h.
Referenced by clang::driver::tools::ClangAs::AddMIPSTargetArgs(), clang::driver::tools::ClangAs::AddRISCVTargetArgs(), clang::driver::tools::ClangAs::AddX86TargetArgs(), clang::driver::tools::ifstool::Merger::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::SPIRVTranslator::ConstructJob(), clang::driver::tools::SPIRCheck::ConstructJob(), clang::driver::tools::SYCLPostLink::ConstructJob(), clang::driver::tools::FileTableTform::ConstructJob(), clang::driver::tools::AppendFooter::ConstructJob(), clang::driver::tools::SpirvToIrWrapper::ConstructJob(), clang::driver::tools::LinkerWrapper::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), clang::driver::tools::SYCL::constructLLVMForeachCommand(), clang::driver::tools::SPIRV::constructTranslateCommand(), clang::driver::CC1Command::Execute(), and clang::driver::tools::GetSDLFromOffloadArchive().
hasGoodDiagnostics()
virtual bool clang::driver::Tool::hasGoodDiagnostics () const inline virtual
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
Reimplemented in clang::driver::tools::SpirvToIrWrapper, clang::driver::tools::AppendFooter, clang::driver::tools::FileTableTform, clang::driver::tools::SYCLPostLink, clang::driver::tools::ClangAs, clang::driver::tools::gcc::Compiler, clang::driver::tools::Clang, clang::driver::tools::gcc::Preprocessor, and clang::driver::tools::Flang.
Definition at line 63 of file Tool.h.
Referenced by clang::driver::Driver::ExecuteCompilation().
hasIntegratedAssembler()
virtual bool clang::driver::Tool::hasIntegratedAssembler () const inline virtual
Reimplemented in clang::driver::tools::ClangAs, clang::driver::tools::Clang, clang::driver::tools::gcc::Common, clang::driver::tools::Flang, and clang::driver::tools::SPIRV::Translator.
Definition at line 54 of file Tool.h.
hasIntegratedBackend()
virtual bool clang::driver::Tool::hasIntegratedBackend () const inline virtual
Reimplemented in clang::driver::tools::Clang.
Definition at line 55 of file Tool.h.
hasIntegratedCPP()
virtual bool clang::driver::Tool::hasIntegratedCPP () const pure virtual
Implemented in clang::driver::tools::LinkerWrapper, clang::driver::tools::SpirvToIrWrapper, clang::driver::tools::AppendFooter, clang::driver::tools::FileTableTform, clang::driver::tools::SYCLPostLink, clang::driver::tools::SPIRCheck, clang::driver::tools::SPIRVTranslator, clang::driver::tools::OffloadDeps, clang::driver::tools::OffloadWrapper, clang::driver::tools::OffloadBundler, clang::driver::tools::ClangAs, clang::driver::tools::gcc::Linker, clang::driver::tools::darwin::VerifyDebug, clang::driver::tools::gcc::Compiler, clang::driver::tools::NVPTX::OpenMPLinker, clang::driver::tools::Clang, clang::driver::tools::SYCL::x86_64::BackendCompiler, clang::driver::tools::gcc::Preprocessor, clang::driver::tools::darwin::Dsymutil, clang::driver::tools::NVPTX::Linker, clang::driver::tools::SYCL::gen::BackendCompiler, clang::driver::tools::darwin::Lipo, clang::driver::tools::NVPTX::Assembler, clang::driver::tools::baremetal::Linker, clang::driver::tools::darwin::StaticLibTool, clang::driver::tools::gnutools::StaticLibTool, clang::driver::tools::SYCL::fpga::BackendCompiler, clang::driver::tools::darwin::Linker, clang::driver::tools::msp430::Linker, clang::driver::tools::AVR::Linker, clang::driver::tools::gnutools::Linker, clang::driver::tools::Flang, clang::driver::tools::Myriad::Linker, clang::driver::tools::darwin::Assembler, clang::driver::tools::RISCV::Linker, clang::driver::tools::SYCL::Linker, clang::driver::tools::PS4cpu::Link, clang::driver::tools::gnutools::Assembler, clang::driver::tools::SPIRV::Linker, clang::driver::tools::hexagon::Linker, clang::driver::tools::MinGW::Linker, clang::driver::tools::openbsd::Linker, clang::driver::tools::CrossWindows::Linker, clang::driver::tools::freebsd::Linker, clang::driver::tools::solaris::Linker, clang::driver::tools::aix::Linker, clang::driver::tools::ananas::Linker, clang::driver::tools::dragonfly::Linker, clang::driver::tools::SHAVE::Assembler, clang::driver::tools::netbsd::Linker, clang::driver::tools::XCore::Linker, clang::driver::tools::minix::Linker, clang::driver::tools::nacltools::Linker, clang::driver::tools::amdgpu::Linker, clang::driver::tools::AMDGCN::OpenMPLinker, clang::driver::tools::PS4cpu::Assemble, clang::driver::tools::SPIRV::Translator, clang::driver::tools::visualstudio::Linker, clang::driver::tools::MinGW::Assembler, clang::driver::tools::hexagon::Assembler, clang::driver::tools::AMDGCN::Linker, clang::driver::tools::openbsd::Assembler, clang::driver::tools::CrossWindows::Assembler, clang::driver::tools::freebsd::Assembler, clang::driver::tools::HIPSPV::Linker, clang::driver::tools::solaris::Assembler, clang::driver::tools::XCore::Assembler, clang::driver::tools::aix::Assembler, clang::driver::tools::ananas::Assembler, clang::driver::tools::cloudabi::Linker, clang::driver::tools::dragonfly::Assembler, clang::driver::tools::SHAVE::Compiler, clang::driver::tools::netbsd::Assembler, clang::driver::tools::fuchsia::Linker, clang::driver::tools::minix::Assembler, clang::driver::tools::wasm::Linker, and clang::driver::tools::ifstool::Merger.
isDsymutilJob()
virtual bool clang::driver::Tool::isDsymutilJob () const inline virtual
Reimplemented in clang::driver::tools::darwin::Dsymutil.
Definition at line 59 of file Tool.h.
Referenced by clang::driver::Driver::generateCompilationDiagnostics().
isLinkJob()
virtual bool clang::driver::Tool::isLinkJob () const inline virtual
Reimplemented in clang::driver::tools::gcc::Linker, clang::driver::tools::baremetal::Linker, clang::driver::tools::darwin::StaticLibTool, clang::driver::tools::gnutools::StaticLibTool, clang::driver::tools::darwin::Linker, clang::driver::tools::msp430::Linker, clang::driver::tools::AVR::Linker, clang::driver::tools::gnutools::Linker, clang::driver::tools::Myriad::Linker, clang::driver::tools::RISCV::Linker, clang::driver::tools::PS4cpu::Link, clang::driver::tools::SPIRV::Linker, clang::driver::tools::hexagon::Linker, clang::driver::tools::MinGW::Linker, clang::driver::tools::openbsd::Linker, clang::driver::tools::CrossWindows::Linker, clang::driver::tools::freebsd::Linker, clang::driver::tools::solaris::Linker, clang::driver::tools::aix::Linker, clang::driver::tools::ananas::Linker, clang::driver::tools::dragonfly::Linker, clang::driver::tools::netbsd::Linker, clang::driver::tools::XCore::Linker, clang::driver::tools::minix::Linker, clang::driver::tools::nacltools::Linker, clang::driver::tools::amdgpu::Linker, clang::driver::tools::visualstudio::Linker, clang::driver::tools::cloudabi::Linker, clang::driver::tools::fuchsia::Linker, clang::driver::tools::ifstool::Merger, and clang::driver::tools::wasm::Linker.
Definition at line 58 of file Tool.h.
Referenced by clang::driver::Driver::generateCompilationDiagnostics().
The documentation for this class was generated from the following files:
include/clang/Driver/Tool.h
lib/Driver/Tool.cpp