clang: clang::CallExpr Class Reference
clang::CallExpr Class Reference
CallExpr - Represents a function call (C99 6.5.2.2, C++ [expr.call]).
#include "clang/AST/Expr.h"
Public Types
enum class ADLCallKind : bool { NotADL , UsesADL }
typedef ExprIterator arg_iterator
typedef ConstExprIterator const_arg_iterator
typedef llvm::iterator_range< arg_iterator > arg_range
typedef llvm::iterator_range< const_arg_iterator > const_arg_range
Public Types inherited from clang::Expr
enum LValueClassification {
LV_Valid , LV_NotObjectType , LV_IncompleteVoidType , LV_DuplicateVectorComponents ,
LV_InvalidExpression , LV_InvalidMessageExpression , LV_MemberFunction , LV_SubObjCPropertySetting ,
LV_ClassTemporary , LV_ArrayTemporary
}
enum isModifiableLvalueResult {
MLV_Valid , MLV_NotObjectType , MLV_IncompleteVoidType , MLV_DuplicateVectorComponents ,
MLV_InvalidExpression , MLV_LValueCast , MLV_IncompleteType , MLV_ConstQualified ,
MLV_ConstQualifiedField , MLV_ConstAddrSpace , MLV_ArrayType , MLV_NoSetterProperty ,
MLV_MemberFunction , MLV_SubObjCPropertySetting , MLV_InvalidMessageExpression , MLV_ClassTemporary ,
MLV_ArrayTemporary
}
enum SideEffectsKind { SE_NoSideEffects , SE_AllowUndefinedBehavior , SE_AllowSideEffects }
enum class ConstantExprKind { Normal , NonClassTemplateArgument , ClassTemplateArgument , ImmediateInvocation }
enum NullPointerConstantKind {
NPCK_NotNull = 0 , NPCK_ZeroExpression , NPCK_ZeroLiteral , NPCK_CXX11_nullptr ,
NPCK_GNUNull
}
Enumeration used to describe the kind of Null pointer constant returned from isNullPointerConstant().
enum NullPointerConstantValueDependence { NPC_NeverValueDependent = 0 , NPC_ValueDependentIsNull , NPC_ValueDependentIsNotNull }
Enumeration used to describe how isNullPointerConstant() should cope with value-dependent expressions.
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1 , LH_None , LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpressions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
Expr * getCallee ()
const Expr * getCallee () const
void setCallee (Expr *F)
ADLCallKind getADLCallKind () const
void setADLCallKind (ADLCallKind V=UsesADL)
bool usesADL () const
bool hasStoredFPFeatures () const
Decl * getCalleeDecl ()
const Decl * getCalleeDecl () const
FunctionDecl * getDirectCallee ()
If the callee is a FunctionDecl, return it. Otherwise return null.
const FunctionDecl * getDirectCallee () const
unsigned getNumArgs () const
getNumArgs - Return the number of actual arguments to this call.
Expr ** getArgs ()
Retrieve the call arguments.
const Expr *const * getArgs () const
Expr * getArg (unsigned Arg)
getArg - Return the specified argument.
const Expr * getArg (unsigned Arg) const
void setArg (unsigned Arg, Expr *ArgExpr)
setArg - Set the specified argument.
void computeDependence ()
Compute and set dependence bits.
void shrinkNumArgs (unsigned NewNumArgs)
Reduce the number of arguments in this call expression.
void setNumArgsUnsafe (unsigned NewNumArgs)
Bluntly set a new number of arguments without doing any checks whatsoever.
arg_range arguments ()
const_arg_range arguments () const
arg_iterator arg_begin ()
arg_iterator arg_end ()
const_arg_iterator arg_begin () const
const_arg_iterator arg_end () const
ArrayRef< Stmt * > getRawSubExprs ()
This method provides fast access to all the subexpressions of a CallExpr without going through the slower virtual child_iterator interface.
FPOptionsOverride getStoredFPFeatures () const
Get FPOptionsOverride from trailing storage.
void setStoredFPFeatures (FPOptionsOverride F)
Set FPOptionsOverride in trailing storage. Used only by Serialization.
FPOptions getFPFeaturesInEffect (const LangOptions &LO) const
Get the FP features status of this operator.
FPOptionsOverride getFPFeatures () const
unsigned getBuiltinCallee () const
getBuiltinCallee - If this is a call to a builtin, return the builtin ID of the callee.
bool isUnevaluatedBuiltinCall (const ASTContext &Ctx) const
Returns true if this is a call to a builtin which does not evaluate side-effects within its arguments.
QualType getCallReturnType (const ASTContext &Ctx) const
getCallReturnType - Get the return type of the call expr.
const Attr * getUnusedResultAttr (const ASTContext &Ctx) const
Returns the WarnUnusedResultAttr that is either declared on the called function, or its return type declaration.
bool hasUnusedResultAttr (const ASTContext &Ctx) const
Returns true if this call expression should warn on unused results.
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation L)
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
bool isBuiltinAssumeFalse (const ASTContext &Ctx) const
Return true if this is a call to __assume() or __builtin_assume() with a non-value-dependent constant parameter evaluating as false.
void markDependentForPostponedNameLookup ()
Used by Sema to implement MSVC-compatible delayed name lookup.
bool isCallToStdMove () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Expr
Expr ()=delete
Expr (const Expr &)=delete
Expr (Expr &&)=delete
Expr & operator= (const Expr &)=delete
Expr & operator= (Expr &&)=delete
QualType getType () const
void setType (QualType t)
QualType getEnumCoercedType (const ASTContext &Ctx) const
If this expression is an enumeration constant, return the enumeration type under which said constant was declared.
ExprDependence getDependence () const
bool isValueDependent () const
Determines whether the value of this expression depends on.
bool isTypeDependent () const
Determines whether the type of this expression depends on.
bool isInstantiationDependent () const
Whether this expression is instantiation-dependent, meaning that it depends in some way on.
bool containsUnexpandedParameterPack () const
Whether this expression contains an unexpanded parameter pack (for C++11 variadic templates).
bool containsErrors () const
Whether this expression contains subexpressions which had errors, e.g.
SourceLocation getExprLoc () const LLVM_READONLY
getExprLoc - Return the preferred location for the arrow when diagnosing a problem with a generic expression.
bool isReadIfDiscardedInCPlusPlus11 () const
Determine whether an lvalue-to-rvalue conversion should implicitly be applied to this expression if it appears as a discarded-value expression in C++11 onwards.
bool isUnusedResultAWarning (const Expr *&WarnExpr, SourceLocation &Loc, SourceRange &R1, SourceRange &R2, ASTContext &Ctx) const
isUnusedResultAWarning - Return true if this immediate expression should be warned about if the result is unused.
bool isLValue () const
isLValue - True if this expression is an "l-value" according to the rules of the current language.
bool isPRValue () const
bool isXValue () const
bool isGLValue () const
LValueClassification ClassifyLValue (ASTContext &Ctx) const
Reasons why an expression might not be an l-value.
isModifiableLvalueResult isModifiableLvalue (ASTContext &Ctx, SourceLocation *Loc=nullptr) const
isModifiableLvalue - C99 6.3.2.1: an lvalue that does not have array type, does not have an incomplete type, does not have a const-qualified type, and if it is a structure or union, does not have any member (including, recursively, any member or element of all contained aggregates or unions) with a const-qualified type.
Classification Classify (ASTContext &Ctx) const
Classify - Classify this expression according to the C++11 expression taxonomy.
Classification ClassifyModifiable (ASTContext &Ctx, SourceLocation &Loc) const
ClassifyModifiable - Classify this expression according to the C++11 expression taxonomy, and see if it is valid on the left side of an assignment.
FPOptions getFPFeaturesInEffect (const LangOptions &LO) const
Returns the set of floating point options that apply to this expression.
ExprValueKind getValueKind () const
getValueKind - The value kind that this expression produces.
ExprObjectKind getObjectKind () const
getObjectKind - The object kind that this expression produces.
bool isOrdinaryOrBitFieldObject () const
void setValueKind (ExprValueKind Cat)
setValueKind - Set the value kind produced by this expression.
void setObjectKind (ExprObjectKind Cat)
setObjectKind - Set the object kind produced by this expression.
bool refersToBitField () const
Returns true if this expression is a gl-value that potentially refers to a bit-field.
FieldDecl * getSourceBitField ()
If this expression refers to a bit-field, retrieve the declaration of that bit-field.
EnumConstantDecl * getEnumConstantDecl ()
If this expression refers to an enum constant, retrieve its declaration.
const EnumConstantDecl * getEnumConstantDecl () const
const FieldDecl * getSourceBitField () const
Decl * getReferencedDeclOfCallee ()
const Decl * getReferencedDeclOfCallee () const
const ObjCPropertyRefExpr * getObjCProperty () const
If this expression is an l-value for an Objective C property, find the underlying property reference expression.
bool isObjCSelfExpr () const
Check if this expression is the ObjC 'self' implicit parameter.
bool refersToVectorElement () const
Returns whether this expression refers to a vector element.
bool refersToMatrixElement () const
Returns whether this expression refers to a matrix element.
bool refersToGlobalRegisterVar () const
Returns whether this expression refers to a global register variable.
bool hasPlaceholderType () const
Returns whether this expression has a placeholder type.
bool hasPlaceholderType (BuiltinType::Kind K) const
Returns whether this expression has a specific placeholder type.
bool isKnownToHaveBooleanValue (bool Semantic=true) const
isKnownToHaveBooleanValue - Return true if this is an integer expression that is known to return 0 or 1.
bool isFlexibleArrayMemberLike (ASTContext &Context, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel, bool IgnoreTemplateOrMacroSubstitution=false) const
Check whether this array fits the idiom of a flexible array member, depending on the value of -fstrict-flex-array.
std::optional< llvm::APSInt > getIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr) const
isIntegerConstantExpr - Return the value if this expression is a valid integer constant expression.
bool isIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr) const
bool isCXX98IntegralConstantExpr (const ASTContext &Ctx) const
isCXX98IntegralConstantExpr - Return true if this expression is an integral constant expression in C++98.
bool isCXX11ConstantExpr (const ASTContext &Ctx, APValue *Result=nullptr, SourceLocation *Loc=nullptr) const
isCXX11ConstantExpr - Return true if this expression is a constant expression in C++11.
bool isConstantInitializer (ASTContext &Ctx, bool ForRef, const Expr **Culprit=nullptr) const
isConstantInitializer - Returns true if this expression can be emitted to IR as a constant, and thus can be used as a constant initializer in C.
const ValueDecl * getAsBuiltinConstantDeclRef (const ASTContext &Context) const
If this expression is an unambiguous reference to a single declaration, in the style of __builtin_function_start, return that declaration.
bool EvaluateAsRValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsRValue - Return true if this is a constant which we can fold to an rvalue using any crazy technique (that has nothing to do with language standards) that we want to, even if the expression has side-effects.
bool EvaluateAsBooleanCondition (bool &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsBooleanCondition - Return true if this is a constant which we can fold and convert to a boolean condition using any crazy technique that we want to, even if the expression has side-effects.
bool EvaluateAsInt (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsInt - Return true if this is a constant which we can fold and convert to an integer, using any crazy technique that we want to.
bool EvaluateAsFloat (llvm::APFloat &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a floating point value, using any crazy technique that we want to.
bool EvaluateAsFixedPoint (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFixedPoint - Return true if this is a constant which we can fold and convert to a fixed point value.
bool isEvaluatable (const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects) const
isEvaluatable - Call EvaluateAsRValue to see if this expression can be constant folded without side-effects, but discard the result.
bool HasSideEffects (const ASTContext &Ctx, bool IncludePossibleEffects=true) const
HasSideEffects - This routine returns true for all those expressions which have any effect other than producing a value.
bool hasNonTrivialCall (const ASTContext &Ctx) const
Determine whether this expression involves a call to any function that is not trivial.
llvm::APSInt EvaluateKnownConstInt (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
EvaluateKnownConstInt - Call EvaluateAsRValue and return the folded integer.
llvm::APSInt EvaluateKnownConstIntCheckOverflow (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
void EvaluateForOverflow (const ASTContext &Ctx) const
bool EvaluateAsLValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsLValue - Evaluate an expression to see if we can fold it to an lvalue with link time known address, with no side-effects.
bool EvaluateAsInitializer (APValue &Result, const ASTContext &Ctx, const VarDecl *VD, SmallVectorImpl< PartialDiagnosticAt > &Notes, bool IsConstantInitializer) const
EvaluateAsInitializer - Evaluate an expression as if it were the initializer of the given declaration.
bool EvaluateWithSubstitution (APValue &Value, ASTContext &Ctx, const FunctionDecl *Callee, ArrayRef< const Expr * > Args, const Expr *This=nullptr) const
EvaluateWithSubstitution - Evaluate an expression as if from the context of a call to the given function with the given arguments, inside an unevaluated context.
bool EvaluateAsConstantExpr (EvalResult &Result, const ASTContext &Ctx, ConstantExprKind Kind=ConstantExprKind::Normal) const
Evaluate an expression that is required to be a constant expression.
bool tryEvaluateObjectSize (uint64_t &Result, ASTContext &Ctx, unsigned Type) const
If the current Expr is a pointer, this will try to statically determine the number of bytes available where the pointer is pointing.
bool tryEvaluateStrLen (uint64_t &Result, ASTContext &Ctx) const
If the current Expr is a pointer, this will try to statically determine the strlen of the string pointed to.
bool EvaluateCharRangeAsString (std::string &Result, const Expr *SizeExpression, const Expr *PtrExpression, ASTContext &Ctx, EvalResult &Status) const
NullPointerConstantKind isNullPointerConstant (ASTContext &Ctx, NullPointerConstantValueDependence NPC) const
isNullPointerConstant - C99 6.3.2.3p3 - Test if this reduces down to a Null pointer constant.
bool isOBJCGCCandidate (ASTContext &Ctx) const
isOBJCGCCandidate - Return true if this expression may be used in a read/ write barrier.
bool isBoundMemberFunction (ASTContext &Ctx) const
Returns true if this expression is a bound member function.
Expr * IgnoreUnlessSpelledInSource ()
Skip past any invisible AST nodes which might surround this statement, such as ExprWithCleanups or ImplicitCastExpr nodes, but also injected CXXMemberExpr and CXXConstructExpr which represent implicit conversions.
const Expr * IgnoreUnlessSpelledInSource () const
Expr * IgnoreImpCasts () LLVM_READONLY
Skip past any implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreImpCasts () const
Expr * IgnoreCasts () LLVM_READONLY
Skip past any casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreCasts () const
Expr * IgnoreImplicit () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicit () const
Expr * IgnoreImplicitAsWritten () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicitAsWritten () const
Expr * IgnoreParens () LLVM_READONLY
Skip past any parentheses which might surround this expression until reaching a fixed point.
const Expr * IgnoreParens () const
Expr * IgnoreParenImpCasts () LLVM_READONLY
Skip past any parentheses and implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenImpCasts () const
Expr * IgnoreParenCasts () LLVM_READONLY
Skip past any parentheses and casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenCasts () const
Expr * IgnoreConversionOperatorSingleStep () LLVM_READONLY
Skip conversion operators.
const Expr * IgnoreConversionOperatorSingleStep () const
Expr * IgnoreParenLValueCasts () LLVM_READONLY
Skip past any parentheses and lvalue casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenLValueCasts () const
Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) LLVM_READONLY
Skip past any parentheses and casts which do not change the value (including ptr->int casts of the same size) until reaching a fixed point.
const Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) const
Expr * IgnoreParenBaseCasts () LLVM_READONLY
Skip past any parentheses and derived-to-base casts until reaching a fixed point.
const Expr * IgnoreParenBaseCasts () const
bool isDefaultArgument () const
Determine whether this expression is a default function argument.
bool isTemporaryObject (ASTContext &Ctx, const CXXRecordDecl *TempTy) const
Determine whether the result of this expression is a temporary object of the given class type.
bool isImplicitCXXThis () const
Whether this expression is an implicit reference to 'this' in C++.
const CXXRecordDecl * getBestDynamicClassType () const
For an expression of class type or pointer to class type, return the most derived class decl the expression is known to refer to.
const Expr * getBestDynamicClassTypeExpr () const
Get the inner expression that determines the best dynamic class.
const Expr * skipRValueSubobjectAdjustments (SmallVectorImpl< const Expr * > &CommaLHS, SmallVectorImpl< SubobjectAdjustment > &Adjustments) const
Walk outwards from an expression we want to bind a reference to and find the expression whose lifetime needs to be extended.
const Expr * skipRValueSubobjectAdjustments () const
Public Member Functions inherited from clang::ValueStmt
const Expr * getExprStmt () const
Expr * getExprStmt ()
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical, bool ProfileLambdaExpr=false) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static CallExpr * Create (const ASTContext &Ctx, Expr *Fn, ArrayRef< Expr * > Args, QualType Ty, ExprValueKind VK, SourceLocation RParenLoc, FPOptionsOverride FPFeatures, unsigned MinNumArgs=0, ADLCallKind UsesADL=NotADL)
Create a call expression.
static CallExpr * CreateTemporary (void *Mem, Expr *Fn, QualType Ty, ExprValueKind VK, SourceLocation RParenLoc, ADLCallKind UsesADL=NotADL)
Create a temporary call expression with no arguments in the memory pointed to by Mem.
static CallExpr * CreateEmpty (const ASTContext &Ctx, unsigned NumArgs, bool HasFPFeatures, EmptyShell Empty)
Create an empty call expression, for deserialization.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Expr
static ExprValueKind getValueKindForType (QualType T)
getValueKindForType - Given a formal return or parameter type, give its value kind.
static bool isPotentialConstantExpr (const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExpr - Return true if this function's definition might be usable in a constant expression in C++11, if it were marked constexpr.
static bool isPotentialConstantExprUnevaluated (Expr *E, const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExprUnevaluated - Return true if this expression might be usable in a constant expression in C++11 in an unevaluated context, if it were in function FD marked constexpr.
static QualType findBoundMemberType (const Expr *expr)
Given an expression of bound-member type, find the type of the member.
static bool hasAnyTypeDependentArguments (ArrayRef< Expr * > Exprs)
hasAnyTypeDependentArguments - Determines if any of the expressions in Exprs is type-dependent.
static bool isSameComparisonOperand (const Expr *E1, const Expr *E2)
Checks that the two Expr's will refer to the same value as a comparison operand.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::ValueStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Static Public Attributes
static constexpr ADLCallKind NotADL = ADLCallKind::NotADL
static constexpr ADLCallKind UsesADL = ADLCallKind::UsesADL
Protected Member Functions
CallExpr (StmtClass SC, Expr *Fn, ArrayRef< Expr * > PreArgs, ArrayRef< Expr * > Args, QualType Ty, ExprValueKind VK, SourceLocation RParenLoc, FPOptionsOverride FPFeatures, unsigned MinNumArgs, ADLCallKind UsesADL)
Build a call expression, assuming that appropriate storage has been allocated for the trailing objects.
CallExpr (StmtClass SC, unsigned NumPreArgs, unsigned NumArgs, bool hasFPFeatures, EmptyShell Empty)
Build an empty call expression, for deserialization.
Stmt * getPreArg (unsigned I)
const Stmt * getPreArg (unsigned I) const
void setPreArg (unsigned I, Stmt *PreArg)
unsigned getNumPreArgs () const
FPOptionsOverride * getTrailingFPFeatures ()
Return a pointer to the trailing FPOptions.
const FPOptionsOverride * getTrailingFPFeatures () const
Protected Member Functions inherited from clang::Expr
Expr (StmtClass SC, QualType T, ExprValueKind VK, ExprObjectKind OK)
Expr (StmtClass SC, EmptyShell)
Construct an empty expression.
void setDependence (ExprDependence Deps)
Each concrete expr subclass is expected to compute its dependence and call this in the constructor.
Protected Member Functions inherited from clang::ValueStmt
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt (StmtClass SC)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Static Protected Member Functions
static unsigned sizeOfTrailingObjects (unsigned NumPreArgs, unsigned NumArgs, bool HasFPFeatures)
Return the size in bytes needed for the trailing objects.
Additional Inherited Members
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator< T, const T *const, const Stmt *const >
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator< Expr >
using ConstExprIterator = ConstCastIterator< Expr >
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
CallExpr - Represents a function call (C99 6.5.2.2, C++ [expr.call]).
CallExpr itself represents a normal function call, e.g., "f(x, 2)", while its subclasses may represent alternative syntax that (semantically) results in a function call. For example, CXXOperatorCallExpr is a subclass for overloaded operator calls that use operator syntax, e.g., "str1 + str2" to resolve to a function call.
Definition at line 2872 of file Expr.h.
Member Typedef Documentation
arg_iterator
typedef ExprIterator clang::CallExpr::arg_iterator
Definition at line 3106 of file Expr.h.
arg_range
typedef llvm::iterator_range<arg_iterator> clang::CallExpr::arg_range
Definition at line 3108 of file Expr.h.
const_arg_iterator
typedef ConstExprIterator clang::CallExpr::const_arg_iterator
Definition at line 3107 of file Expr.h.
const_arg_range
typedef llvm::iterator_range<const_arg_iterator> clang::CallExpr::const_arg_range
Definition at line 3109 of file Expr.h.
Member Enumeration Documentation
ADLCallKind
enum clang::CallExpr::ADLCallKind : bool strong
Enumerator
NotADL
UsesADL
Definition at line 2928 of file Expr.h.
Constructor & Destructor Documentation
CallExpr() [1/2]
CallExpr::CallExpr (StmtClass SC, Expr * Fn, ArrayRef< Expr * > PreArgs, ArrayRef< Expr * > Args, QualType Ty, ExprValueKind VK, SourceLocation RParenLoc, FPOptionsOverride FPFeatures, unsigned MinNumArgs, ADLCallKind UsesADL) protected
Build a call expression, assuming that appropriate storage has been allocated for the trailing objects.
Definition at line 1504 of file Expr.cpp.
References clang::Stmt::CallExprBits, computeDependence(), getNumPreArgs(), hasStoredFPFeatures(), clang::FPOptionsOverride::requiresTrailingStorage(), setArg(), setCallee(), setPreArg(), setStoredFPFeatures(), and UsesADL.
Referenced by Create(), CreateEmpty(), and CreateTemporary().
CallExpr() [2/2]
CallExpr::CallExpr (StmtClass SC, unsigned NumPreArgs, unsigned NumArgs, bool hasFPFeatures, EmptyShell Empty) protected
Build an empty call expression, for deserialization.
Definition at line 1536 of file Expr.cpp.
References clang::Stmt::CallExprBits, and getNumPreArgs().
Member Function Documentation
arg_begin() [1/2]
arg_iterator clang::CallExpr::arg_begin () inline
Definition at line 3116 of file Expr.h.
References getNumPreArgs().
Referenced by arg_end(), and arguments().
arg_begin() [2/2]
const_arg_iterator clang::CallExpr::arg_begin () const inline
Definition at line 3121 of file Expr.h.
References getNumPreArgs().
arg_end() [1/2]
arg_iterator clang::CallExpr::arg_end () inline
Definition at line 3119 of file Expr.h.
References arg_begin(), and getNumArgs().
Referenced by arguments().
arg_end() [2/2]
const_arg_iterator clang::CallExpr::arg_end () const inline
Definition at line 3124 of file Expr.h.
References arg_begin(), and getNumArgs().
arguments() [1/2]
arg_range clang::CallExpr::arguments () inline
Definition at line 3111 of file Expr.h.
References arg_begin(), and arg_end().
Referenced by clang::TrivialFunctionAnalysisVisitor::checkArguments(), commonEmitCXXMemberOrOperatorCall(), clang::Sema::DiagnoseImmediateEscalatingReason(), clang::CodeGen::CodeGenFunction::EmitAMDGPUDevicePrintfCallExpr(), clang::CodeGen::CodeGenFunction::EmitBlockCallExpr(), clang::CodeGen::CodeGenFunction::EmitBuiltinNewDeleteCall(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCXXMemberPointerCallExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitBuiltinCallExpr(), clang::ASTNodeImporter::VisitCallExpr(), and clang::ASTNodeImporter::VisitCXXMemberCallExpr().
arguments() [2/2]
const_arg_range clang::CallExpr::arguments () const inline
Definition at line 3112 of file Expr.h.
References arg_begin(), and arg_end().
children() [1/2]
child_range clang::CallExpr::children () inline
Definition at line 3206 of file Expr.h.
References getNumArgs(), and getNumPreArgs().
Referenced by clang::LexicallyOrderedRecursiveASTVisitor< Derived >::getStmtChildren().
children() [2/2]
const_child_range clang::CallExpr::children () const inline
Definition at line 3211 of file Expr.h.
References getNumArgs(), and getNumPreArgs().
classof()
static bool clang::CallExpr::classof (const Stmt * T) inline static
Definition at line 3200 of file Expr.h.
References clang::T.
computeDependence()
void clang::CallExpr::computeDependence () inline
Compute and set dependence bits.
Definition at line 3082 of file Expr.h.
References clang::computeDependence(), getNumPreArgs(), and clang::Expr::setDependence().
Referenced by clang::Sema::BuildResolvedCallExpr(), and CallExpr().
Create()
CallExpr * CallExpr::Create (const ASTContext & Ctx, Expr * Fn, ArrayRef< Expr * > Args, QualType Ty, ExprValueKind VK, SourceLocation RParenLoc, FPOptionsOverride FPFeatures, unsigned MinNumArgs = 0, ADLCallKind UsesADL = NotADL) static
Create a call expression.
Parameters
Fn The callee expression,
Args The argument array,
Ty The type of the call expression (which is not the return type in general),
VK The value kind of the call expression (lvalue, rvalue, ...),
RParenLoc The location of the right parenthesis in the call expression.
FPFeatures Floating-point features associated with the call,
MinNumArgs Specifies the minimum number of arguments. The actual number of arguments will be the greater of Args.size() and MinNumArgs. This is used in a few places to allocate enough storage for the default arguments.
UsesADL Specifies whether the callee was found through argument-dependent lookup.
Note that you can use CreateTemporary if you need a temporary call expression on the stack.
Definition at line 1549 of file Expr.cpp.
References clang::ASTContext::Allocate(), CallExpr(), clang::FPOptionsOverride::requiresTrailingStorage(), sizeOfTrailingObjects(), and UsesADL.
Referenced by clang::Sema::BuildCallExpr(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::CheckPlaceholderExpr(), create_dispatch_once(), create_dispatch_sync(), and clang::ASTNodeImporter::VisitCallExpr().
CreateEmpty()
CallExpr * CallExpr::CreateEmpty (const ASTContext & Ctx, unsigned NumArgs, bool HasFPFeatures, EmptyShell Empty) static
Create an empty call expression, for deserialization.
Definition at line 1573 of file Expr.cpp.
References clang::ASTContext::Allocate(), CallExpr(), and sizeOfTrailingObjects().
CreateTemporary()
CallExpr * CallExpr::CreateTemporary (void * Mem, Expr * Fn, QualType Ty, ExprValueKind VK, SourceLocation RParenLoc, ADLCallKind UsesADL = NotADL) static
Create a temporary call expression with no arguments in the memory pointed to by Mem.
Mem must points to at least sizeof(CallExpr)
sizeof(Stmt *) bytes of storage, aligned to alignof(CallExpr):
alignas(CallExpr) char Buffer[sizeof(CallExpr) + sizeof(Stmt *)];
CallExpr *TheCall = CallExpr::CreateTemporary(Buffer, etc);
Definition at line 1563 of file Expr.cpp.
References CallExpr(), and UsesADL.
getADLCallKind()
ADLCallKind clang::CallExpr::getADLCallKind () const inline
Definition at line 3026 of file Expr.h.
References clang::Stmt::CallExprBits.
Referenced by usesADL(), and clang::ASTNodeImporter::VisitCallExpr().
getArg() [1/2]
Expr* clang::CallExpr::getArg (unsigned Arg) inline
getArg - Return the specified argument.
Definition at line 3063 of file Expr.h.
References getArgs(), and getNumArgs().
Referenced by clang::Sema::BuiltinShuffleVector(), clang::Sema::BuiltinVectorMath(), CheckAtomicAlignment(), clang::Sema::CheckHLSLBuiltinFunctionCall(), clang::CodeGen::CodeGenFunction::checkTargetFeatures(), clang::analyze_os_log::computeOSLogBufferLayout(), clang::Sema::DiagnoseSelfMove(), clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr(), EmitAArch64TblBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitAMDGPUBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitARMBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitARMMVEBuiltinExpr(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicCmpXchgForMSIntrin(), EmitAtomicDecrementValue(), EmitAtomicIncrementValue(), EmitBinaryAtomicPost(), emitBinaryBuiltin(), emitBinaryExpMaybeConstrainedFPBuiltin(), emitBinaryMaybeConstrainedFPBuiltin(), EmitBitTestIntrinsic(), clang::CodeGen::CodeGenFunction::EmitBPFBuiltinExpr(), clang::CodeGen::CodeGenFunction::emitBuiltinOSLogFormat(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCommonNeonBuiltinExpr(), EmitCommonNeonSISDBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitCXXOperatorMemberCallExpr(), emitFPIntBuiltin(), emitFrexpBuiltin(), clang::CodeGen::CodeGenFunction::EmitHexagonBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitHLSLBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitIntelFPGAMemBuiltin(), clang::CodeGen::CodeGenFunction::EmitIntelFPGARegBuiltin(), clang::CodeGen::CodeGenFunction::EmitIntelSYCLPtrAnnotationBuiltin(), EmitISOVolatileLoad(), EmitISOVolatileStore(), emitMaybeConstrainedFPToIntRoundBuiltin(), clang::CodeGen::CodeGenFunction::EmitMSVCBuiltinExpr(), EmitNontemporalLoad(), EmitNontemporalStore(), clang::CodeGen::CodeGenFunction::EmitNVPTXBuiltinExpr(), EmitOverflowCheckedAbs(), emitPPCLoadReserveIntrinsic(), clang::CodeGen::CodeGenFunction::EmitRISCVBuiltinExpr(), clang::CodeGen::CodeGenFunction::emitRotate(), clang::CodeGen::CodeGenFunction::EmitScalarOrConstFoldImmArg(), clang::CodeGen::CodeGenFunction::EmitSVEMaskedLoad(), clang::CodeGen::CodeGenFunction::EmitSVEMaskedStore(), clang::CodeGen::CodeGenFunction::EmitSystemZBuiltinExpr(), EmitSystemZIntrinsicWithCC(), emitTernaryBuiltin(), emitTernaryMaybeConstrainedFPBuiltin(), emitUnaryMaybeConstrainedFPBuiltin(), clang::CodeGen::CodeGenFunction::EmitWebAssemblyBuiltinExpr(), EmitX86BitTestIntrinsic(), clang::CodeGen::CodeGenFunction::GetAArch64SVEProcessedOperands(), getArgumentValueString(), clang::UserDefinedLiteral::getBeginLoc(), getBeginLoc(), getBuiltinAlignArguments(), clang::UserDefinedLiteral::getCookedLiteral(), clang::ento::CXXMemberOperatorCall::getCXXThisExpr(), getEndLoc(), HandleOperatorDeleteCall(), HandleOperatorNewCall(), isBuiltinAssumeFalse(), clang::Expr::isUnusedResultAWarning(), MakeAtomicCmpXchgValue(), MakeBinaryAtomicValue(), and clang::interp::ByteCodeExprGen< Emitter >::VisitCallExpr().
getArg() [2/2]
const Expr* clang::CallExpr::getArg (unsigned Arg) const inline
Definition at line 3067 of file Expr.h.
References getArgs(), and getNumArgs().
getArgs() [1/2]
Expr** clang::CallExpr::getArgs () inline
Retrieve the call arguments.
Definition at line 3053 of file Expr.h.
References getNumPreArgs().
Referenced by clang::Sema::BuildResolvedCallExpr(), clang::Sema::CheckFunctionCall(), clang::computeDependence(), clang::analyze_os_log::computeOSLogBufferLayout(), getArg(), setArg(), and clang::interp::ByteCodeExprGen< Emitter >::VisitCallExpr().
getArgs() [2/2]
const Expr* const* clang::CallExpr::getArgs () const inline
Definition at line 3057 of file Expr.h.
References getNumPreArgs().
getBeginLoc()
SourceLocation CallExpr::getBeginLoc () const
Definition at line 1693 of file Expr.cpp.
References getArg(), clang::Stmt::getBeginLoc(), getCallee(), getNumArgs(), and clang::SourceLocation::isInvalid().
Referenced by clang::Sema::BuiltinShuffleVector(), CheckAtomicAlignment(), clang::CodeGen::CodeGenFunction::checkTargetFeatures(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCoroutineIntrinsic(), clang::CXXMemberCallExpr::getExprLoc(), HandleOperatorNewCall(), and clang::CodeGen::CGCallee::prepareConcreteCallee().
getBuiltinCallee()
unsigned CallExpr::getBuiltinCallee () const
getBuiltinCallee - If this is a call to a builtin, return the builtin ID of the callee.
If this is a call to a builtin, return the builtin ID. If not, return 0.
If not, return 0.
Definition at line 1634 of file Expr.cpp.
References getDirectCallee().
Referenced by CheckICE(), clang::analyze_os_log::computeOSLogBufferLayout(), clang::CodeGen::CodeGenFunction::EmitAMDGPUDevicePrintfCallExpr(), isBuiltinAssumeFalse(), isCallToStdMove(), IsNoOpCall(), isUnevaluatedBuiltinCall(), and clang::interp::ByteCodeExprGen< Emitter >::VisitCallExpr().
getCallee() [1/2]
Expr* clang::CallExpr::getCallee () inline
Definition at line 3022 of file Expr.h.
Referenced by clang::AnyCall::AnyCall(), clang::Sema::CheckFunctionCall(), clang::computeDependence(), clang::Sema::DiagnoseImmediateEscalatingReason(), clang::CodeGen::CodeGenFunction::EmitBlockCallExpr(), clang::CodeGen::CodeGenFunction::EmitCallExpr(), clang::CodeGen::CodeGenFunction::EmitCXXMemberCallExpr(), clang::CodeGen::CodeGenFunction::EmitCXXMemberPointerCallExpr(), emitLibraryCall(), clang::CodeGen::CodeGenFunction::EmitSimpleCallExpr(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicSetterCopyHelperFunction(), getBeginLoc(), clang::ento::BlockCall::getBlockRegion(), getCalleeDecl(), clang::ento::CheckerContext::getCalleeDecl(), getCallReturnType(), clang::CXXMemberCallExpr::getExprLoc(), clang::CXXMemberCallExpr::getImplicitObjectArgument(), clang::CXXMemberCallExpr::getMethodDecl(), clang::ento::CallEventManager::getSimpleCall(), hasRecursiveCallInPath(), isParenthesizedADLCallee(), isSwiftAsyncCallee(), clang::Expr::isUnusedResultAWarning(), clang::ASTNodeImporter::VisitCallExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitCallExpr(), and clang::ASTNodeImporter::VisitCXXMemberCallExpr().
getCallee() [2/2]
const Expr* clang::CallExpr::getCallee () const inline
Definition at line 3023 of file Expr.h.
getCalleeDecl() [1/2]
Decl* clang::CallExpr::getCalleeDecl () inline
Definition at line 3036 of file Expr.h.
References getCallee(), and clang::Expr::getReferencedDeclOfCallee().
Referenced by clang::AnyCall::AnyCall(), clang::CodeGen::CodeGenFunction::EmitBlockCallExpr(), getDirectCallee(), clang::UserDefinedLiteral::getLiteralOperatorKind(), clang::UserDefinedLiteral::getUDSuffix(), getUnusedResultAttr(), hasRecursiveCallInPath(), clang::Expr::isUnusedResultAWarning(), and clang::ento::CallDescription::matchesAsWritten().
getCalleeDecl() [2/2]
const Decl* clang::CallExpr::getCalleeDecl () const inline
Definition at line 3037 of file Expr.h.
References getCallee(), and clang::Expr::getReferencedDeclOfCallee().
getCallReturnType()
QualType CallExpr::getCallReturnType (const ASTContext & Ctx) const
getCallReturnType - Get the return type of the call expr.
This is not always the type of the expr itself, if the return type is a reference type.
Definition at line 1645 of file Expr.cpp.
References clang::Type::castAs(), clang::ASTContext::DependentTy, clang::Expr::findBoundMemberType(), clang::Type::getAs(), getCallee(), clang::Type::getPointeeType(), clang::FunctionType::getReturnType(), clang::Type::isDependentType(), clang::QualType::isNull(), clang::Type::isRecordType(), clang::Type::isSpecificPlaceholderType(), and clang::ASTContext::VoidTy.
Referenced by clang::ento::RetainSummaryManager::canEval(), clang::CodeGen::CodeGenFunction::EmitCallExprLValue(), getUnusedResultAttr(), clang::Expr::isUnusedResultAWarning(), clang::CodeGen::CodeGenFunction::LookupNeonLLVMIntrinsic(), and clang::interp::ByteCodeExprGen< Emitter >::VisitCallExpr().
getDirectCallee() [1/2]
FunctionDecl* clang::CallExpr::getDirectCallee () inline
If the callee is a FunctionDecl, return it. Otherwise return null.
Definition at line 3042 of file Expr.h.
References getCalleeDecl().
Referenced by clang::SemaOpenMP::ActOnOpenMPCall(), clang::Sema::BuiltinShuffleVector(), commonEmitCXXMemberOrOperatorCall(), clang::Sema::DiagnoseImmediateEscalatingReason(), clang::CodeGen::CodeGenFunction::EmitAMDGPUDevicePrintfCallExpr(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitIntelSYCLAllocaBuiltin(), getBuiltinCallee(), clang::ento::CheckerContext::getCalleeDecl(), getCalleeName(), clang::ento::SimpleFunctionCall::getDecl(), hasTrivialBody(), clang::interp::ByteCodeExprGen< Emitter >::VisitBuiltinCallExpr(), ImmediateCallVisitor::VisitCallExpr(), DiagDeviceFunction::VisitCallExpr(), clang::TrivialFunctionAnalysisVisitor::VisitCallExpr(), and clang::interp::ByteCodeExprGen< Emitter >::VisitCallExpr().
getDirectCallee() [2/2]
const FunctionDecl* clang::CallExpr::getDirectCallee () const inline
Definition at line 3045 of file Expr.h.
References getCalleeDecl().
getEndLoc()
SourceLocation CallExpr::getEndLoc () const
Definition at line 1702 of file Expr.cpp.
References getArg(), clang::Stmt::getEndLoc(), getNumArgs(), getRParenLoc(), and clang::SourceLocation::isInvalid().
Referenced by clang::Sema::BuiltinShuffleVector().
getFPFeatures()
FPOptionsOverride clang::CallExpr::getFPFeatures () const inline
Definition at line 3154 of file Expr.h.
References getStoredFPFeatures(), and hasStoredFPFeatures().
Referenced by clang::CodeGen::CodeGenFunction::EmitBuiltinExpr(), clang::ASTNodeImporter::VisitCallExpr(), and clang::ASTNodeImporter::VisitCXXMemberCallExpr().
getFPFeaturesInEffect()
FPOptions clang::CallExpr::getFPFeaturesInEffect (const LangOptions & LO) const inline
Get the FP features status of this operator.
Only meaningful for operations on floating point types.
Definition at line 3148 of file Expr.h.
References clang::FPOptionsOverride::applyOverrides(), clang::FPOptions::defaultWithoutTrailingStorage(), getStoredFPFeatures(), and hasStoredFPFeatures().
getNumArgs()
unsigned clang::CallExpr::getNumArgs () const inline
getNumArgs - Return the number of actual arguments to this call.
Definition at line 3050 of file Expr.h.
Referenced by arg_end(), clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuiltinShuffleVector(), clang::ento::RetainSummaryManager::canEval(), clang::Sema::CheckFunctionCall(), children(), clang::computeDependence(), clang::analyze_os_log::computeOSLogBufferLayout(), clang::Sema::DiagnoseSelfMove(), EmitAArch64TblBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitAMDGPUDevicePrintfCallExpr(), EmitAtomicCmpXchg128ForMSIntrin(), clang::CodeGen::CodeGenFunction::emitBuiltinOSLogFormat(), clang::CodeGen::CodeGenFunction::EmitCommonNeonBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitIntelFPGAMemBuiltin(), clang::CodeGen::CodeGenFunction::EmitIntelSYCLPtrAnnotationBuiltin(), clang::CodeGen::CodeGenFunction::EmitRISCVBuiltinExpr(), EmitSystemZIntrinsicWithCC(), clang::CodeGen::CodeGenFunction::EmitX86BuiltinExpr(), clang::CodeGen::CodeGenFunction::GetAArch64SVEProcessedOperands(), getArg(), getArgumentValueString(), getBeginLoc(), getEndLoc(), clang::UserDefinedLiteral::getLiteralOperatorKind(), clang::ento::SimpleFunctionCall::getNumArgs(), clang::ento::BlockCall::getNumArgs(), clang::ento::CXXStaticOperatorCall::getNumArgs(), clang::ento::CXXMemberOperatorCall::getNumArgs(), getOperatorNodeKind(), getRawSubExprs(), HandleOperatorDeleteCall(), HandleOperatorNewCall(), clang::CXXOperatorCallExpr::isInfixBinaryOp(), clang::Expr::isUnusedResultAWarning(), clang::ento::CallDescription::matchesAsWritten(), setArg(), shrinkNumArgs(), clang::ASTNodeImporter::VisitCallExpr(), clang::interp::ByteCodeExprGen< Emitter >::VisitCallExpr(), and clang::ASTNodeImporter::VisitCXXMemberCallExpr().
getNumPreArgs()
unsigned clang::CallExpr::getNumPreArgs () const inline protected
Definition at line 2965 of file Expr.h.
References clang::Stmt::CallExprBits.
Referenced by arg_begin(), CallExpr(), children(), computeDependence(), getArgs(), getPreArg(), getRawSubExprs(), and setPreArg().
getPreArg() [1/2]
Stmt* clang::CallExpr::getPreArg (unsigned I) inline protected
Definition at line 2952 of file Expr.h.
References getNumPreArgs().
Referenced by clang::CUDAKernelCallExpr::getConfig().
getPreArg() [2/2]
const Stmt* clang::CallExpr::getPreArg (unsigned I) const inline protected
Definition at line 2956 of file Expr.h.
References getNumPreArgs().
getRawSubExprs()
ArrayRef<Stmt *> clang::CallExpr::getRawSubExprs () inline
This method provides fast access to all the subexpressions of a CallExpr without going through the slower virtual child_iterator interface.
This provides efficient reverse iteration of the subexpressions. This is currently used for CFG construction.
Definition at line 3130 of file Expr.h.
References getNumArgs(), and getNumPreArgs().
getRParenLoc()
SourceLocation clang::CallExpr::getRParenLoc () const inline
Definition at line 3182 of file Expr.h.
Referenced by clang::UserDefinedLiteral::getBeginLoc(), clang::UserDefinedLiteral::getEndLoc(), getEndLoc(), clang::CXXOperatorCallExpr::getOperatorLoc(), clang::ASTNodeImporter::VisitCallExpr(), and clang::ASTNodeImporter::VisitCXXMemberCallExpr().
getStoredFPFeatures()
FPOptionsOverride clang::CallExpr::getStoredFPFeatures () const inline
Get FPOptionsOverride from trailing storage.
Definition at line 3136 of file Expr.h.
References getTrailingFPFeatures(), and hasStoredFPFeatures().
Referenced by getFPFeatures(), and getFPFeaturesInEffect().
getTrailingFPFeatures() [1/2]
FPOptionsOverride* clang::CallExpr::getTrailingFPFeatures () inline protected
Return a pointer to the trailing FPOptions.
Definition at line 2968 of file Expr.h.
References clang::Stmt::CallExprBits, and hasStoredFPFeatures().
Referenced by getStoredFPFeatures(), and setStoredFPFeatures().
getTrailingFPFeatures() [2/2]
const FPOptionsOverride* clang::CallExpr::getTrailingFPFeatures () const inline protected
Definition at line 2974 of file Expr.h.
References clang::Stmt::CallExprBits, and hasStoredFPFeatures().
getUnusedResultAttr()
const Attr * CallExpr::getUnusedResultAttr (const ASTContext & Ctx) const
Returns the WarnUnusedResultAttr that is either declared on the called function, or its return type declaration.
Definition at line 1675 of file Expr.cpp.
References clang::Decl::getAttr(), getCalleeDecl(), and getCallReturnType().
Referenced by hasUnusedResultAttr().
hasStoredFPFeatures()
bool clang::CallExpr::hasStoredFPFeatures () const inline
Definition at line 3034 of file Expr.h.
References clang::Stmt::CallExprBits.
Referenced by CallExpr(), clang::CodeGen::CodeGenFunction::EmitBuiltinExpr(), getFPFeatures(), getFPFeaturesInEffect(), getStoredFPFeatures(), getTrailingFPFeatures(), and setStoredFPFeatures().
hasUnusedResultAttr()
bool clang::CallExpr::hasUnusedResultAttr (const ASTContext & Ctx) const inline
Returns true if this call expression should warn on unused results.
Definition at line 3178 of file Expr.h.
References getUnusedResultAttr().
Referenced by clang::Expr::isUnusedResultAWarning().
isBuiltinAssumeFalse()
bool CallExpr::isBuiltinAssumeFalse (const ASTContext & Ctx) const
Return true if this is a call to __assume() or __builtin_assume() with a non-value-dependent constant parameter evaluating as false.
Definition at line 3550 of file Expr.cpp.
References clang::Expr::EvaluateAsBooleanCondition(), getArg(), getBuiltinCallee(), and clang::Expr::isValueDependent().
isCallToStdMove()
bool CallExpr::isCallToStdMove () const
Definition at line 3562 of file Expr.cpp.
References getBuiltinCallee().
Referenced by clang::Sema::DiagnoseSelfMove().
isUnevaluatedBuiltinCall()
bool CallExpr::isUnevaluatedBuiltinCall (const ASTContext & Ctx) const
Returns true if this is a call to a builtin which does not evaluate side-effects within its arguments.
Definition at line 1639 of file Expr.cpp.
References clang::ASTContext::BuiltinInfo, getBuiltinCallee(), and clang::Builtin::Context::isUnevaluated().
Referenced by clang::EvaluatedExprVisitorBase< Ptr, ImplClass >::VisitCallExpr().
markDependentForPostponedNameLookup()
void clang::CallExpr::markDependentForPostponedNameLookup () inline
Used by Sema to implement MSVC-compatible delayed name lookup.
(Usually Exprs themselves should set dependence).
Definition at line 3194 of file Expr.h.
References clang::Expr::getDependence(), and clang::Expr::setDependence().
setADLCallKind()
void clang::CallExpr::setADLCallKind (ADLCallKind V = UsesADL) inline
Definition at line 3029 of file Expr.h.
References clang::Stmt::CallExprBits, and V.
setArg()
void clang::CallExpr::setArg (unsigned Arg, Expr * ArgExpr) inline
setArg - Set the specified argument.
! the dependence bits might be stale after calling this setter, it is caller's responsibility to recompute them by calling computeDependence().
Definition at line 3076 of file Expr.h.
References getArgs(), and getNumArgs().
Referenced by clang::Sema::BuildResolvedCallExpr(), clang::Sema::BuiltinVectorMath(), and CallExpr().
setCallee()
void clang::CallExpr::setCallee (Expr * F) inline
Definition at line 3024 of file Expr.h.
Referenced by CallExpr().
setNumArgsUnsafe()
void clang::CallExpr::setNumArgsUnsafe (unsigned NewNumArgs) inline
Bluntly set a new number of arguments without doing any checks whatsoever.
Only used during construction of a CallExpr in a few places in Sema. FIXME: Find a way to remove it.
Definition at line 3104 of file Expr.h.
Referenced by clang::Sema::BuildResolvedCallExpr().
setPreArg()
void clang::CallExpr::setPreArg (unsigned I, Stmt * PreArg) inline protected
Definition at line 2960 of file Expr.h.
References getNumPreArgs().
Referenced by CallExpr().
setRParenLoc()
void clang::CallExpr::setRParenLoc (SourceLocation L) inline
Definition at line 3183 of file Expr.h.
setStoredFPFeatures()
void clang::CallExpr::setStoredFPFeatures (FPOptionsOverride F) inline
Set FPOptionsOverride in trailing storage. Used only by Serialization.
Definition at line 3141 of file Expr.h.
References getTrailingFPFeatures(), and hasStoredFPFeatures().
Referenced by CallExpr().
shrinkNumArgs()
void clang::CallExpr::shrinkNumArgs (unsigned NewNumArgs) inline
Reduce the number of arguments in this call expression.
This is used for example during error recovery to drop extra arguments. There is no way to perform the opposite because: 1.) We don't track how much storage we have for the argument array 2.) This would potentially require growing the argument array, something we cannot support since the arguments are stored in a trailing array.
Definition at line 3095 of file Expr.h.
References getNumArgs().
Referenced by clang::Sema::BuildResolvedCallExpr().
sizeOfTrailingObjects()
static unsigned clang::CallExpr::sizeOfTrailingObjects (unsigned NumPreArgs, unsigned NumArgs, bool HasFPFeatures) inline static protected
Return the size in bytes needed for the trailing objects.
Used by the derived classes to allocate the right amount of storage.
Definition at line 2946 of file Expr.h.
Referenced by clang::UserDefinedLiteral::Create(), clang::CXXMemberCallExpr::Create(), Create(), clang::CUDAKernelCallExpr::Create(), clang::CXXOperatorCallExpr::Create(), CreateEmpty(), clang::CXXOperatorCallExpr::CreateEmpty(), clang::CXXMemberCallExpr::CreateEmpty(), clang::CUDAKernelCallExpr::CreateEmpty(), and clang::UserDefinedLiteral::CreateEmpty().
usesADL()
bool clang::CallExpr::usesADL () const inline
Definition at line 3032 of file Expr.h.
References getADLCallKind(), and UsesADL.
Referenced by clang::JSONNodeDumper::VisitCallExpr().
Member Data Documentation
NotADL
constexpr ADLCallKind clang::CallExpr::NotADL = ADLCallKind::NotADL static constexpr
Definition at line 2929 of file Expr.h.
UsesADL
constexpr ADLCallKind clang::CallExpr::UsesADL = ADLCallKind::UsesADL static constexpr
Definition at line 2930 of file Expr.h.
Referenced by CallExpr(), Create(), clang::CXXOperatorCallExpr::Create(), CreateTemporary(), and usesADL().
The documentation for this class was generated from the following files:
include/clang/AST/Expr.h
lib/AST/Expr.cpp