clang: clang::interp::MemberPointer Class Reference
clang::interp::MemberPointer Class Reference final
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/MemberPointer.h"
Public Member Functions
MemberPointer ()=default
MemberPointer (Pointer Base, const Decl *Dcl)
MemberPointer (uint32_t Address, const Descriptor *D)
MemberPointer (const Decl *D)
uint64_t getIntegerRepresentation () const
std::optional< Pointer > toPointer (const Context &Ctx) const
FunctionPointer toFunctionPointer (const Context &Ctx) const
Pointer getBase () const
bool isMemberFunctionPointer () const
const CXXMethodDecl * getMemberFunction () const
const FieldDecl * getField () const
bool hasDecl () const
const Decl * getDecl () const
MemberPointer atInstanceBase (unsigned Offset) const
MemberPointer takeInstance (Pointer Instance) const
APValue toAPValue () const
bool isZero () const
bool hasBase () const
void print (llvm::raw_ostream &OS) const
std::string toDiagnosticString (const ASTContext &Ctx) const
ComparisonCategoryResult compare (const MemberPointer &RHS) const
Detailed Description
Definition at line 22 of file MemberPointer.h.
Constructor & Destructor Documentation
MemberPointer() [1/4]
clang::interp::MemberPointer::MemberPointer () default
Referenced by atInstanceBase(), and takeInstance().
MemberPointer() [2/4]
clang::interp::MemberPointer::MemberPointer (Pointer Base, const Decl * Dcl) inline
Definition at line 33 of file MemberPointer.h.
MemberPointer() [3/4]
clang::interp::MemberPointer::MemberPointer (uint32_t Address, const Descriptor * D) inline
Definition at line 34 of file MemberPointer.h.
MemberPointer() [4/4]
clang::interp::MemberPointer::MemberPointer (const Decl * D) inline
Definition at line 39 of file MemberPointer.h.
References D.
Member Function Documentation
atInstanceBase()
MemberPointer clang::interp::MemberPointer::atInstanceBase (unsigned Offset) const inline
Definition at line 72 of file MemberPointer.h.
References MemberPointer(), and Offset.
compare()
ComparisonCategoryResult clang::interp::MemberPointer::compare (const MemberPointer & RHS) const inline
Definition at line 97 of file MemberPointer.h.
References clang::Equal, and clang::Unordered.
getBase()
Pointer clang::interp::MemberPointer::getBase () const inline
Definition at line 54 of file MemberPointer.h.
getDecl()
const Decl* clang::interp::MemberPointer::getDecl () const inline
Definition at line 70 of file MemberPointer.h.
Referenced by toAPValue().
getField()
const FieldDecl* clang::interp::MemberPointer::getField () const inline
Definition at line 65 of file MemberPointer.h.
getIntegerRepresentation()
uint64_t clang::interp::MemberPointer::getIntegerRepresentation () const inline
Definition at line 43 of file MemberPointer.h.
getMemberFunction()
const CXXMethodDecl* clang::interp::MemberPointer::getMemberFunction () const inline
Definition at line 62 of file MemberPointer.h.
hasBase()
bool clang::interp::MemberPointer::hasBase () const inline
Definition at line 86 of file MemberPointer.h.
Referenced by toAPValue().
hasDecl()
bool clang::interp::MemberPointer::hasDecl () const inline
Definition at line 69 of file MemberPointer.h.
isMemberFunctionPointer()
bool clang::interp::MemberPointer::isMemberFunctionPointer () const inline
Definition at line 59 of file MemberPointer.h.
isZero()
bool clang::interp::MemberPointer::isZero () const inline
Definition at line 85 of file MemberPointer.h.
Referenced by toAPValue().
print()
void clang::interp::MemberPointer::print (llvm::raw_ostream & OS) const inline
Definition at line 88 of file MemberPointer.h.
Referenced by clang::interp::operator<<().
takeInstance()
MemberPointer clang::interp::MemberPointer::takeInstance (Pointer Instance) const inline
Definition at line 78 of file MemberPointer.h.
References clang::interp::Pointer::isZero(), and MemberPointer().
toAPValue()
APValue clang::interp::MemberPointer::toAPValue () const
Definition at line 63 of file MemberPointer.cpp.
References getDecl(), hasBase(), and isZero().
toDiagnosticString()
std::string clang::interp::MemberPointer::toDiagnosticString (const ASTContext & Ctx) const inline
Definition at line 93 of file MemberPointer.h.
toFunctionPointer()
FunctionPointer clang::interp::MemberPointer::toFunctionPointer (const Context & Ctx) const
Definition at line 59 of file MemberPointer.cpp.
References clang::interp::Program::getFunction(), and clang::interp::Context::getProgram().
toPointer()
std::optional< Pointer > clang::interp::MemberPointer::toPointer (const Context & Ctx) const
Definition at line 18 of file MemberPointer.cpp.
References clang::interp::Pointer::atField(), clang::interp::Pointer::block(), clang::interp::Context::collectBaseOffset(), clang::interp::Record::getDecl(), clang::interp::Block::getDescriptor(), clang::interp::Record::getField(), clang::interp::Descriptor::getMetadataSize(), clang::FieldDecl::getParent(), clang::interp::Pointer::getRecord(), clang::interp::Context::getRecord(), clang::interp::Block::getSize(), clang::interp::Record::Field::Offset, and Offset.
The documentation for this class was generated from the following files:
lib/AST/Interp/MemberPointer.h
lib/AST/Interp/MemberPointer.cpp