clang: clang::driver::toolchains::HexagonToolChain Class Reference
clang::driver::toolchains::HexagonToolChain Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/Hexagon.h"
Public Member Functions
HexagonToolChain (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
~HexagonToolChain () override
void addClangTargetOptions (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, Action::OffloadKind DeviceOffloadKind) const override
Add options that need to be passed to cc1 for this target.
void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add the clang cc1 arguments for system include paths.
void addLibStdCxxIncludePaths (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
void addLibCxxIncludePaths (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
const char * getDefaultLinker () const override
GetDefaultLinker - Get the default linker to use.
CXXStdlibType GetCXXStdlibType (const llvm::opt::ArgList &Args) const override
void AddCXXStdlibLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
StringRef GetGCCLibAndIncVersion () const
bool IsIntegratedAssemblerDefault () const override
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
std::string getHexagonTargetDir (const std::string &InstalledDir, const SmallVectorImpl< std::string > &PrefixDirs) const
Hexagon Toolchain.
void getHexagonLibraryPaths (const llvm::opt::ArgList &Args, ToolChain::path_list &LibPaths) const
std::string getCompilerRTPath () const override
Public Member Functions inherited from clang::driver::toolchains::Linux
Linux (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
bool HasNativeLLVMSupport () const override
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
std::string getMultiarchTriple (const Driver &D, const llvm::Triple &TargetTriple, StringRef SysRoot) const override
Get our best guess at the multiarch triple for a target.
void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add the clang cc1 arguments for system include paths.
void addLibStdCxxIncludePaths (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use system-specific CUDA includes.
void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use system-specific HIP includes.
void AddIAMCUIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use MCU GCC toolchain includes.
RuntimeLibType GetDefaultRuntimeLibType () const override
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
unsigned GetDefaultDwarfVersion () const override
CXXStdlibType GetDefaultCXXStdlibType () const override
bool IsAArch64OutlineAtomicsDefault (const llvm::opt::ArgList &Args) const override
Test whether this toolchain supports outline atomics by default.
bool isPIEDefault (const llvm::opt::ArgList &Args) const override
Test whether this toolchain defaults to PIE.
bool IsMathErrnoDefault () const override
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
SanitizerMask getSupportedSanitizers () const override
Return sanitizers which are available in this toolchain.
void addProfileRTLibs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
addProfileRTLibs - When -fprofile-instr-profile is specified, try to pass a suitable profile runtime library to the linker.
std::string computeSysRoot () const override
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
std::string getDynamicLinker (const llvm::opt::ArgList &Args) const override
void addExtraOpts (llvm::opt::ArgStringList &CmdArgs) const override
llvm::DenormalMode getDefaultDenormalModeForType (const llvm::opt::ArgList &DriverArgs, const JobAction &JA, const llvm::fltSemantics *FPType=nullptr) const override
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
Public Member Functions inherited from clang::driver::toolchains::Generic_ELF
Generic_ELF (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
Public Member Functions inherited from clang::driver::toolchains::Generic_GCC
Generic_GCC (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
~Generic_GCC () override
void printVerboseInfo (raw_ostream &OS) const override
Dispatch to the specific toolchain for verbose printing.
bool IsUnwindTablesDefault (const llvm::opt::ArgList &Args) const override
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
bool isPICDefault () const override
Test whether this toolchain defaults to PIC.
bool isPICDefaultForced () const override
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
llvm::opt::DerivedArgList * TranslateArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
Public Member Functions inherited from clang::driver::ToolChain
virtual ~ToolChain ()
const Driver & getDriver () const
llvm::vfs::FileSystem & getVFS () const
const llvm::Triple & getTriple () const
virtual const llvm::Triple * getAuxTriple () const
Get the toolchain's aux triple, if it has one.
virtual std::string getInputFilename (const InputInfo &Input) const
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
llvm::Triple::ArchType getArch () const
StringRef getArchName () const
StringRef getPlatform () const
StringRef getOS () const
StringRef getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
std::string getTripleString () const
const llvm::Triple & getEffectiveTriple () const
Get the toolchain's effective clang triple.
path_list & getLibraryPaths ()
const path_list & getLibraryPaths () const
path_list & getFilePaths ()
const path_list & getFilePaths () const
path_list & getProgramPaths ()
const path_list & getProgramPaths () const
const MultilibSet & getMultilibs () const
const Multilib & getMultilib () const
SanitizerArgs getSanitizerArgs (const llvm::opt::ArgList &JobArgs) const
const XRayArgs & getXRayArgs () const
const llvm::opt::Arg * getRTTIArg () const
RTTIMode getRTTIMode () const
virtual llvm::opt::DerivedArgList * TranslateOffloadTargetArgs (const llvm::opt::DerivedArgList &Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > &AllocatedArgs, Action::OffloadKind DeviceOffloadKind) const
TranslateOffloadTargetArgs - Create a new derived argument list for that contains the Offload target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val Also handles -Xsycl-target OR -Xsycl-target=<triple>
virtual void TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, llvm::opt::Arg *&A, llvm::opt::DerivedArgList *DAL, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs=nullptr) const
Append the argument following A to DAL assuming A is an Xarch argument.
virtual llvm::opt::DerivedArgList * TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs) const
Translate -Xarch_ arguments.
virtual Tool * SelectTool (const JobAction &JA) const
Choose a tool to use to handle the action JA.
std::string GetFilePath (const char *Name) const
std::string GetProgramPath (const char *Name) const
std::string GetLinkerPath (bool *LinkerIsLLD=nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
std::string GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
virtual bool isCrossCompiling () const
Returns true if the toolchain is targeting a non-native architecture.
virtual types::ID LookupTypeForExtension (StringRef Ext) const
LookupTypeForExtension - Return the default language type to use for the given extension.
virtual bool IsBlocksDefault () const
IsBlocksDefault - Does this tool chain enable -fblocks by default.
virtual bool useIntegratedAs () const
Check if the toolchain should use the integrated assembler.
virtual bool useIntegratedBackend () const
Check if the toolchain should use the integrated backend.
virtual bool parseInlineAsmUsingAsmParser () const
Check if the toolchain should use AsmParser to parse inlineAsm when integrated assembler is not default.
virtual bool IsEncodeExtendedBlockSignatureDefault () const
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
virtual bool IsObjCNonFragileABIDefault () const
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
virtual bool UseObjCMixedDispatch () const
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
virtual bool useRelaxRelocations () const
Check whether to enable x86 relax relocations by default.
bool defaultToIEEELongDouble () const
Check whether use IEEE binary128 as long double format by default.
virtual LangOptions::StackProtectorMode GetDefaultStackProtectorLevel (bool KernelOrKext) const
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
virtual LangOptions::TrivialAutoVarInitKind GetDefaultTrivialAutoVarInit () const
Get the default trivial automatic variable initialization.
virtual UnwindLibType GetDefaultUnwindLibType () const
virtual std::string getCompilerRT (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
const char * getCompilerRTArgString (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::string getCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
path_list getRuntimePaths () const
path_list getStdlibPaths () const
std::string getArchSpecificLibPath () const
virtual StringRef getOSLibName () const
virtual bool SupportsProfiling () const
SupportsProfiling - Does this tool chain support -pg.
virtual void CheckObjCARC () const
Complain if this tool chain doesn't support Objective-C ARC.
virtual codegenoptions::DebugInfoFormat getDefaultDebugFormat () const
Get the default debug info format. Typically, this is DWARF.
virtual bool UseDwarfDebugFlags () const
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
virtual std::string GetGlobalDebugPathRemapping () const
Add an additional -fdebug-prefix-map entry.
virtual unsigned getMaxDwarfVersion () const
virtual bool GetDefaultStandaloneDebug () const
virtual llvm::DebuggerKind getDefaultDebuggerTuning () const
virtual bool supportsDebugInfoOption (const llvm::opt::Arg *) const
Does this toolchain supports given debug info option or not.
virtual void adjustDebugInfoKind (codegenoptions::DebugInfoKind &DebugInfoKind, const llvm::opt::ArgList &Args) const
Adjust debug information kind considering all passed options.
virtual llvm::ExceptionHandling GetExceptionModel (const llvm::opt::ArgList &Args) const
GetExceptionModel - Return the tool chain exception model.
virtual bool SupportsEmbeddedBitcode () const
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
virtual std::string getThreadModel () const
getThreadModel() - Which thread model does this target use?
virtual bool isThreadModelSupported (const StringRef Model) const
isThreadModelSupported() - Does this target support a thread model?
virtual std::string ComputeLLVMTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
virtual std::string ComputeEffectiveClangTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
virtual ObjCRuntime getDefaultObjCRuntime (bool isNonFragile) const
getDefaultObjCRuntime - Return the default Objective-C runtime for this platform.
virtual bool hasBlocksRuntime () const
hasBlocksRuntime - Given that the user is compiling with -fblocks, does this tool chain guarantee the existence of a blocks runtime?
virtual void addClangWarningOptions (llvm::opt::ArgStringList &CC1Args) const
Add warning options that need to be passed to cc1 for this target.
virtual RuntimeLibType GetRuntimeLibType (const llvm::opt::ArgList &Args) const
virtual UnwindLibType GetUnwindLibType (const llvm::opt::ArgList &Args) const
virtual std::string detectLibcxxVersion (StringRef IncludePath) const
void AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
bool ShouldLinkCXXStdlib (const llvm::opt::ArgList &Args) const
Returns if the C++ standard library should be linked in.
void AddFilePathLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
virtual void AddCCKextLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
virtual bool isFastMathRuntimeAvailable (const llvm::opt::ArgList &Args, std::string &Path) const
If a runtime library exists that sets global flags for unsafe floating point math, return true.
bool addFastMathRuntimeIfAvailable (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
virtual VersionTuple computeMSVCVersion (const Driver *D, const llvm::opt::ArgList &Args) const
On Windows, returns the MSVC compatibility version.
virtual llvm::SmallVector< BitCodeLibraryInfo, 12 > getHIPDeviceLibs (const llvm::opt::ArgList &Args, const Action::OffloadKind DeviceOffloadingKind) const
Get paths of HIP device libraries.
virtual SanitizerMask getDefaultSanitizers () const
Return sanitizers which are enabled by default.
virtual bool canSplitThinLTOUnit () const
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
Static Public Member Functions
static bool isAutoHVXEnabled (const llvm::opt::ArgList &Args)
static StringRef GetDefaultCPU ()
static StringRef GetTargetCPUVersion (const llvm::opt::ArgList &Args)
static Optional< unsigned > getSmallDataThreshold (const llvm::opt::ArgList &Args)
Static Public Member Functions inherited from clang::driver::ToolChain
static ParsedClangName getTargetAndModeFromProgramName (StringRef ProgName)
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
static bool needsProfileRT (const llvm::opt::ArgList &Args)
needsProfileRT - returns true if instrumentation profile is on.
static bool needsGCovInstrumentation (const llvm::opt::ArgList &Args)
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
static llvm::Triple getOpenMPTriple (StringRef TripleStr)
Protected Member Functions
Tool * buildAssembler () const override
Tool * buildLinker () const override
unsigned getOptimizationLevel (const llvm::opt::ArgList &DriverArgs) const
Protected Member Functions inherited from clang::driver::toolchains::Linux
Tool * buildAssembler () const override
Tool * buildLinker () const override
Tool * buildStaticLibTool () const override
Protected Member Functions inherited from clang::driver::toolchains::Generic_GCC
Tool * getTool (Action::ActionClass AC) const override
bool isTarget64Bit () const
Check whether the target triple's architecture is 64-bits.
bool isTarget32Bit () const
Check whether the target triple's architecture is 32-bits.
void PushPPaths (ToolChain::path_list &PPaths)
void AddMultilibPaths (const Driver &D, const std::string &SysRoot, const std::string &OSLibDir, const std::string &MultiarchTriple, path_list &Paths)
void AddMultiarchPaths (const Driver &D, const std::string &SysRoot, const std::string &OSLibDir, path_list &Paths)
void AddMultilibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
bool addGCCLibStdCxxIncludePaths (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, StringRef DebianMultiarch) const
bool addLibStdCXXIncludePaths (Twine IncludeDir, StringRef Triple, Twine IncludeSuffix, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, bool DetectDebian=false) const
Protected Member Functions inherited from clang::driver::ToolChain
ToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
void setTripleEnvironment (llvm::Triple::EnvironmentType Env)
virtual Tool * buildBackendCompiler () const
virtual std::string buildCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type, bool AddArch) const
Protected Attributes
GCCVersion GCCLibAndIncVersion
Protected Attributes inherited from clang::driver::toolchains::Generic_GCC
GCCInstallationDetector GCCInstallation
CudaInstallationDetector CudaInstallation
RocmInstallationDetector RocmInstallation
Protected Attributes inherited from clang::driver::ToolChain
MultilibSet Multilibs
Multilib SelectedMultilib
Additional Inherited Members
Public Types inherited from clang::driver::ToolChain
enum CXXStdlibType { CST_Libcxx, CST_Libstdcxx }
enum RuntimeLibType { RLT_CompilerRT, RLT_Libgcc }
enum UnwindLibType { UNW_None, UNW_CompilerRT, UNW_Libgcc }
enum RTTIMode { RM_Enabled, RM_Disabled }
enum FileType { FT_Object, FT_Static, FT_Shared }
using path_list = SmallVector< std::string, 16 >
Public Attributes inherited from clang::driver::toolchains::Linux
std::vector< std::string > ExtraOpts
Static Protected Member Functions inherited from clang::driver::ToolChain
static void addSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory to CC1 arguments.
static void addExternCSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
static void addExternCSystemIncludeIfExists (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
static void addSystemIncludes (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, ArrayRef< StringRef > Paths)
Utility function to add a list of system include directories to CC1.
Detailed Description
Definition at line 61 of file Hexagon.h.
Constructor & Destructor Documentation
HexagonToolChain()
HexagonToolChain::HexagonToolChain (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args)
Definition at line 588 of file Hexagon.cpp.
References clang::driver::ToolChain::getFilePaths(), getHexagonLibraryPaths(), getHexagonTargetDir(), clang::driver::Driver::getInstalledDir(), clang::driver::ToolChain::getProgramPaths(), clang::driver::Driver::getVFS(), clang::driver::Driver::PrefixDirs, and string().
~HexagonToolChain()
HexagonToolChain::~HexagonToolChain () override
Definition at line 609 of file Hexagon.cpp.
Member Function Documentation
AddClangSystemIncludeArgs()
void HexagonToolChain::AddClangSystemIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add the clang cc1 arguments for system include paths.
This routine is responsible for adding the necessary cc1 arguments to include headers from standard system header directories.
Reimplemented from clang::driver::ToolChain.
Definition at line 681 of file Hexagon.cpp.
References clang::driver::ToolChain::addExternCSystemInclude(), clang::driver::toolchains::Generic_GCC::AddMultilibIncludeArgs(), clang::driver::ToolChain::addSystemInclude(), clang::driver::ToolChain::getDriver(), getHexagonTargetDir(), clang::driver::Driver::getInstalledDir(), clang::driver::ToolChain::getTriple(), P, clang::driver::Driver::PrefixDirs, clang::driver::Driver::ResourceDir, string(), and clang::driver::Driver::SysRoot.
addClangTargetOptions()
void HexagonToolChain::addClangTargetOptions (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, Action::OffloadKind DeviceOffloadKind) const override virtual
Add options that need to be passed to cc1 for this target.
Reimplemented from clang::driver::toolchains::Generic_ELF.
Definition at line 660 of file Hexagon.cpp.
References clang::driver::ToolChain::getTriple(), and isAutoHVXEnabled().
AddCXXStdlibLibArgs()
void HexagonToolChain::AddCXXStdlibLibArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const override virtual
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
Reimplemented from clang::driver::ToolChain.
Definition at line 611 of file Hexagon.cpp.
References clang::driver::ToolChain::CST_Libcxx, clang::driver::ToolChain::CST_Libstdcxx, and GetCXXStdlibType().
Referenced by constructHexagonLinkArgs().
addLibCxxIncludePaths()
void HexagonToolChain::addLibCxxIncludePaths (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Reimplemented from clang::driver::toolchains::Generic_GCC.
Definition at line 725 of file Hexagon.cpp.
References clang::driver::toolchains::Generic_GCC::addLibStdCXXIncludePaths(), clang::driver::ToolChain::getDriver(), getHexagonTargetDir(), clang::driver::ToolChain::getTriple(), clang::driver::Driver::InstalledDir, clang::driver::Driver::PrefixDirs, string(), and clang::driver::Driver::SysRoot.
addLibStdCxxIncludePaths()
void HexagonToolChain::addLibStdCxxIncludePaths (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Reimplemented from clang::driver::toolchains::Generic_GCC.
Definition at line 741 of file Hexagon.cpp.
References clang::driver::toolchains::Generic_GCC::addLibStdCXXIncludePaths(), clang::driver::ToolChain::getDriver(), getHexagonTargetDir(), clang::driver::Driver::InstalledDir, clang::driver::Driver::PrefixDirs, and string().
buildAssembler()
Tool * HexagonToolChain::buildAssembler () const override protected virtual
Reimplemented from clang::driver::toolchains::Generic_GCC.
Definition at line 627 of file Hexagon.cpp.
buildLinker()
Tool * HexagonToolChain::buildLinker () const override protected virtual
Reimplemented from clang::driver::toolchains::Generic_GCC.
Definition at line 631 of file Hexagon.cpp.
getCompilerRTPath()
std::string HexagonToolChain::getCompilerRTPath () const override virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 539 of file Hexagon.cpp.
References string().
GetCXXStdlibType()
ToolChain::CXXStdlibType HexagonToolChain::GetCXXStdlibType (const llvm::opt::ArgList & Args) const override virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 751 of file Hexagon.cpp.
References clang::driver::ToolChain::CST_Libcxx, clang::driver::ToolChain::CST_Libstdcxx, clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), and clang::driver::ToolChain::getTriple().
Referenced by AddCXXStdlibLibArgs().
GetDefaultCPU()
StringRef HexagonToolChain::GetDefaultCPU () static
Definition at line 782 of file Hexagon.cpp.
Referenced by GetTargetCPUVersion().
getDefaultLinker()
const char* clang::driver::toolchains::HexagonToolChain::getDefaultLinker () const inline override virtual
GetDefaultLinker - Get the default linker to use.
Reimplemented from clang::driver::ToolChain.
Definition at line 87 of file Hexagon.h.
GetGCCLibAndIncVersion()
StringRef clang::driver::toolchains::HexagonToolChain::GetGCCLibAndIncVersion () const inline
Definition at line 96 of file Hexagon.h.
getHexagonLibraryPaths()
void HexagonToolChain::getHexagonLibraryPaths (const llvm::opt::ArgList & Args, ToolChain::path_list & LibPaths) const
Definition at line 546 of file Hexagon.cpp.
References clang::driver::Driver::getInstalledDir(), clang::driver::Driver::PrefixDirs, and string().
Referenced by HexagonToolChain().
getHexagonTargetDir()
std::string HexagonToolChain::getHexagonTargetDir (const std::string & InstalledDir, const SmallVectorImpl< std::string > & PrefixDirs) const
Hexagon Toolchain.
Definition at line 505 of file Hexagon.cpp.
References clang::driver::Driver::getVFS(), and string().
Referenced by AddClangSystemIncludeArgs(), addLibCxxIncludePaths(), addLibStdCxxIncludePaths(), constructHexagonLinkArgs(), and HexagonToolChain().
getOptimizationLevel()
unsigned HexagonToolChain::getOptimizationLevel (const llvm::opt::ArgList & DriverArgs) const protected
Definition at line 635 of file Hexagon.cpp.
getSmallDataThreshold()
Optional< unsigned > HexagonToolChain::getSmallDataThreshold (const llvm::opt::ArgList & Args) static
Definition at line 522 of file Hexagon.cpp.
Referenced by constructHexagonLinkArgs(), and clang::driver::tools::hexagon::Assembler::ConstructJob().
GetTargetCPUVersion()
StringRef HexagonToolChain::GetTargetCPUVersion (const llvm::opt::ArgList & Args) static
Definition at line 786 of file Hexagon.cpp.
References GetDefaultCPU().
Referenced by constructHexagonLinkArgs(), and clang::driver::tools::hexagon::Assembler::ConstructJob().
isAutoHVXEnabled()
bool HexagonToolChain::isAutoHVXEnabled (const llvm::opt::ArgList & Args) static
Definition at line 771 of file Hexagon.cpp.
Referenced by addClangTargetOptions().
IsIntegratedAssemblerDefault()
bool clang::driver::toolchains::HexagonToolChain::IsIntegratedAssemblerDefault () const inline override virtual
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
Reimplemented from clang::driver::toolchains::Generic_GCC.
Definition at line 97 of file Hexagon.h.
Member Data Documentation
GCCLibAndIncVersion
GCCVersion clang::driver::toolchains::HexagonToolChain::GCCLibAndIncVersion protected
Definition at line 63 of file Hexagon.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Hexagon.h
lib/Driver/ToolChains/Hexagon.cpp