clang: clang::SYCLIntegrationFooter Class Reference
clang::SYCLIntegrationFooter Class Reference
#include "clang/Sema/SemaSYCL.h"
Public Member Functions
SYCLIntegrationFooter (SemaSYCL &S)
bool emit (StringRef MainSrc)
void addVarDecl (const VarDecl *VD)
Detailed Description
Definition at line 203 of file SemaSYCL.h.
Constructor & Destructor Documentation
SYCLIntegrationFooter()
clang::SYCLIntegrationFooter::SYCLIntegrationFooter (SemaSYCL & S) inline
Definition at line 205 of file SemaSYCL.h.
Member Function Documentation
addVarDecl()
void SYCLIntegrationFooter::addVarDecl (const VarDecl * VD)
Definition at line 5487 of file SemaSYCL.cpp.
References clang::QualType::getCanonicalType(), clang::Decl::getDeclContext(), clang::ValueDecl::getType(), clang::VarDecl::hasExternalStorage(), clang::VarDecl::hasLocalStorage(), clang::DeclContext::isDependentContext(), clang::VarDecl::isLocalVarDeclOrParm(), clang::SemaSYCL::isSyclType(), and clang::Type::isUndeducedType().
Referenced by clang::SemaSYCL::addSyclVarDecl().
emit()
bool SYCLIntegrationFooter::emit (StringRef MainSrc)
Definition at line 5529 of file SemaSYCL.cpp.
Referenced by clang::Sema::ActOnEndOfTranslationUnitFragment().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaSYCL.h
lib/Sema/SemaSYCL.cpp