clang: clang::extractapi::APISet Class Reference
clang::extractapi::APISet Class Reference
APISet holds the set of API records collected from given inputs.
#include "clang/ExtractAPI/API.h"
Public Types
template<typename RecordTy , typename = std::enable_if_t<std::is_base_of<APIRecord, RecordTy>::value>>
using RecordMap = llvm::MapVector< StringRef, std::unique_ptr< RecordTy > >
A mapping type to store a set of APIRecords with the USR as the key.
Public Member Functions
NamespaceRecord * addNamespace (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeaderg)
GlobalVariableRecord * addGlobalVar (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeadin, bool IsFromSystemHeaderg)
Create and add a global variable record into the API set.
GlobalVariableTemplateRecord * addGlobalVariableTemplate (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, bool IsFromSystemHeader)
GlobalFunctionRecord * addGlobalFunction (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, bool IsFromSystemHeader)
Create and add a function record into the API set.
GlobalFunctionTemplateRecord * addGlobalFunctionTemplate (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, Template Template, bool IsFromSystemHeader)
GlobalFunctionTemplateSpecializationRecord * addGlobalFunctionTemplateSpecialization (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, bool IsFromSystemHeader)
EnumConstantRecord * addEnumConstant (EnumRecord *Enum, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Create and add an enum constant record into the API set.
EnumRecord * addEnum (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Create and add an enum record into the API set.
RecordFieldRecord * addRecordField (RecordRecord *Record, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, APIRecord::RecordKind Kind, bool IsFromSystemHeader)
Create and add a record field record into the API set.
RecordRecord * addRecord (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, APIRecord::RecordKind Kind, bool IsFromSystemHeader)
Create and add a record record into the API set.
StaticFieldRecord * addStaticField (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, SymbolReference Context, AccessControl Access, bool IsFromSystemHeaderg)
CXXFieldRecord * addCXXField (APIRecord *CXXClass, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, AccessControl Access, bool IsFromSystemHeader)
CXXFieldTemplateRecord * addCXXFieldTemplate (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, AccessControl Access, Template Template, bool IsFromSystemHeader)
CXXClassRecord * addCXXClass (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, APIRecord::RecordKind Kind, AccessControl Access, bool IsFromSystemHeader)
ClassTemplateRecord * addClassTemplate (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, AccessControl Access, bool IsFromSystemHeader)
ClassTemplateSpecializationRecord * addClassTemplateSpecialization (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, AccessControl Access, bool IsFromSystemHeader)
ClassTemplatePartialSpecializationRecord * addClassTemplatePartialSpecialization (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, AccessControl Access, bool IsFromSystemHeader)
GlobalVariableTemplateSpecializationRecord * addGlobalVariableTemplateSpecialization (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
GlobalVariableTemplatePartialSpecializationRecord * addGlobalVariableTemplatePartialSpecialization (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, bool IsFromSystemHeader)
CXXMethodRecord * addCXXInstanceMethod (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, bool IsFromSystemHeader)
CXXMethodRecord * addCXXStaticMethod (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, bool IsFromSystemHeader)
CXXMethodRecord * addCXXSpecialMethod (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, bool IsFromSystemHeader)
CXXMethodTemplateRecord * addCXXMethodTemplate (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, Template Template, bool IsFromSystemHeader)
CXXMethodTemplateSpecializationRecord * addCXXMethodTemplateSpec (APIRecord *Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, bool IsFromSystemHeader)
ConceptRecord * addConcept (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, bool IsFromSystemHeader)
ObjCCategoryRecord * addObjCCategory (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, SymbolReference Interface, bool IsFromSystemHeader, bool IsFromExternalModule)
Create and add an Objective-C category record into the API set.
ObjCInterfaceRecord * addObjCInterface (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, SymbolReference SuperClass, bool IsFromSystemHeader)
Create and add an Objective-C interface record into the API set.
ObjCMethodRecord * addObjCMethod (ObjCContainerRecord *Container, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, bool IsInstanceMethod, bool IsFromSystemHeader)
Create and add an Objective-C method record into the API set.
ObjCPropertyRecord * addObjCProperty (ObjCContainerRecord *Container, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, ObjCPropertyRecord::AttributeKind Attributes, StringRef GetterName, StringRef SetterName, bool IsOptional, bool IsInstanceProperty, bool IsFromSystemHeader)
Create and add an Objective-C property record into the API set.
ObjCInstanceVariableRecord * addObjCInstanceVariable (ObjCContainerRecord *Container, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, ObjCInstanceVariableRecord::AccessControl Access, bool IsFromSystemHeader)
Create and add an Objective-C instance variable record into the API set.
ObjCProtocolRecord * addObjCProtocol (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Create and add an Objective-C protocol record into the API set.
MacroDefinitionRecord * addMacroDefinition (StringRef Name, StringRef USR, PresumedLoc Loc, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Create a macro definition record into the API set.
TypedefRecord * addTypedef (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment &Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, SymbolReference UnderlyingType, bool IsFromSystemHeader)
Create a typedef record into the API set.
const llvm::Triple & getTarget () const
Get the target triple for the ExtractAPI invocation.
Language getLanguage () const
Get the language used by the APIs.
const RecordMap< NamespaceRecord > & getNamespaces () const
const RecordMap< GlobalFunctionRecord > & getGlobalFunctions () const
const RecordMap< GlobalFunctionTemplateRecord > & getGlobalFunctionTemplates () const
const RecordMap< GlobalFunctionTemplateSpecializationRecord > & getGlobalFunctionTemplateSpecializations () const
const RecordMap< GlobalVariableRecord > & getGlobalVariables () const
const RecordMap< GlobalVariableTemplateRecord > & getGlobalVariableTemplates () const
const RecordMap< StaticFieldRecord > & getStaticFields () const
const RecordMap< GlobalVariableTemplateSpecializationRecord > & getGlobalVariableTemplateSpecializations () const
const RecordMap< GlobalVariableTemplatePartialSpecializationRecord > & getGlobalVariableTemplatePartialSpecializations () const
const RecordMap< EnumRecord > & getEnums () const
const RecordMap< RecordRecord > & getRecords () const
const RecordMap< CXXClassRecord > & getCXXClasses () const
const RecordMap< CXXMethodTemplateRecord > & getCXXMethodTemplates () const
const RecordMap< CXXInstanceMethodRecord > & getCXXInstanceMethods () const
const RecordMap< CXXStaticMethodRecord > & getCXXStaticMethods () const
const RecordMap< CXXFieldRecord > & getCXXFields () const
const RecordMap< CXXMethodTemplateSpecializationRecord > & getCXXMethodTemplateSpecializations () const
const RecordMap< CXXFieldTemplateRecord > & getCXXFieldTemplates () const
const RecordMap< ClassTemplateRecord > & getClassTemplates () const
const RecordMap< ClassTemplateSpecializationRecord > & getClassTemplateSpecializations () const
const RecordMap< ClassTemplatePartialSpecializationRecord > & getClassTemplatePartialSpecializations () const
const RecordMap< ConceptRecord > & getConcepts () const
const RecordMap< ObjCCategoryRecord > & getObjCCategories () const
const RecordMap< ObjCInterfaceRecord > & getObjCInterfaces () const
const RecordMap< ObjCProtocolRecord > & getObjCProtocols () const
const RecordMap< MacroDefinitionRecord > & getMacros () const
const RecordMap< TypedefRecord > & getTypedefs () const
APIRecord * findRecordForUSR (StringRef USR) const
Finds the APIRecord for a given USR.
StringRef recordUSR (const Decl *D)
Generate and store the USR of declaration D.
StringRef recordUSRForMacro (StringRef Name, SourceLocation SL, const SourceManager &SM)
Generate and store the USR for a macro Name.
StringRef copyString (StringRef String)
Copy String into the Allocator in this APISet.
APISet (const llvm::Triple &Target, Language Lang, const std::string &ProductName)
Public Attributes
const std::string ProductName
Detailed Description
APISet holds the set of API records collected from given inputs.
Definition at line 1193 of file API.h.
Member Typedef Documentation
RecordMap
template<typename RecordTy , typename = std::enable_if_t<std::is_base_of<APIRecord, RecordTy>::value>> using clang::extractapi::APISet::RecordMap = llvm::MapVector<StringRef, std::unique_ptr<RecordTy> >
A mapping type to store a set of APIRecords with the USR as the key.
Definition at line 1513 of file API.h.
Constructor & Destructor Documentation
APISet()
clang::extractapi::APISet::APISet (const llvm::Triple & Target, Language Lang, const std::string & ProductName) inline
Definition at line 1620 of file API.h.
Member Function Documentation
addClassTemplate()
ClassTemplateRecord * APISet::addClassTemplate (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, AccessControl Access, bool IsFromSystemHeader)
Definition at line 230 of file API.cpp.
addClassTemplatePartialSpecialization()
ClassTemplatePartialSpecializationRecord * APISet::addClassTemplatePartialSpecialization (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, AccessControl Access, bool IsFromSystemHeader)
Definition at line 261 of file API.cpp.
addClassTemplateSpecialization()
ClassTemplateSpecializationRecord * APISet::addClassTemplateSpecialization (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, AccessControl Access, bool IsFromSystemHeader)
Definition at line 245 of file API.cpp.
addConcept()
ConceptRecord * APISet::addConcept (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, bool IsFromSystemHeader)
Definition at line 301 of file API.cpp.
addCXXClass()
CXXClassRecord * APISet::addCXXClass (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, APIRecord::RecordKind Kind, AccessControl Access, bool IsFromSystemHeader)
Definition at line 216 of file API.cpp.
addCXXField()
CXXFieldRecord * APISet::addCXXField (APIRecord * CXXClass, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, AccessControl Access, bool IsFromSystemHeader)
Definition at line 187 of file API.cpp.
addCXXFieldTemplate()
CXXFieldTemplateRecord * APISet::addCXXFieldTemplate (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, AccessControl Access, Template Template, bool IsFromSystemHeader)
Definition at line 200 of file API.cpp.
addCXXInstanceMethod()
CXXMethodRecord * APISet::addCXXInstanceMethod (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, bool IsFromSystemHeader)
Definition at line 313 of file API.cpp.
addCXXMethodTemplate()
CXXMethodTemplateRecord * APISet::addCXXMethodTemplate (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, Template Template, bool IsFromSystemHeader)
Definition at line 347 of file API.cpp.
addCXXMethodTemplateSpec()
CXXMethodTemplateSpecializationRecord * APISet::addCXXMethodTemplateSpec (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, bool IsFromSystemHeader)
Definition at line 363 of file API.cpp.
addCXXSpecialMethod()
CXXMethodRecord* clang::extractapi::APISet::addCXXSpecialMethod (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, bool IsFromSystemHeader)
addCXXStaticMethod()
CXXMethodRecord * APISet::addCXXStaticMethod (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, AccessControl Access, bool IsFromSystemHeader)
Definition at line 330 of file API.cpp.
addEnum()
EnumRecord * APISet::addEnum (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Create and add an enum record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 136 of file API.cpp.
addEnumConstant()
EnumConstantRecord * APISet::addEnumConstant (EnumRecord * Enum, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Create and add an enum constant record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 120 of file API.cpp.
addGlobalFunction()
GlobalFunctionRecord * APISet::addGlobalFunction (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, bool IsFromSystemHeader)
Create and add a function record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 84 of file API.cpp.
addGlobalFunctionTemplate()
GlobalFunctionTemplateRecord * APISet::addGlobalFunctionTemplate (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, Template Template, bool IsFromSystemHeader)
Definition at line 95 of file API.cpp.
addGlobalFunctionTemplateSpecialization()
GlobalFunctionTemplateSpecializationRecord * APISet::addGlobalFunctionTemplateSpecialization (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, bool IsFromSystemHeader)
Definition at line 108 of file API.cpp.
addGlobalVar()
GlobalVariableRecord * APISet::addGlobalVar (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeadin, bool IsFromSystemHeaderg)
Create and add a global variable record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 63 of file API.cpp.
addGlobalVariableTemplate()
GlobalVariableTemplateRecord * APISet::addGlobalVariableTemplate (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, bool IsFromSystemHeader)
Definition at line 72 of file API.cpp.
addGlobalVariableTemplatePartialSpecialization()
GlobalVariableTemplatePartialSpecializationRecord * APISet::addGlobalVariableTemplatePartialSpecialization (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, Template Template, bool IsFromSystemHeader)
Definition at line 289 of file API.cpp.
addGlobalVariableTemplateSpecialization()
GlobalVariableTemplateSpecializationRecord * APISet::addGlobalVariableTemplateSpecialization (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Definition at line 277 of file API.cpp.
addMacroDefinition()
MacroDefinitionRecord * APISet::addMacroDefinition (StringRef Name, StringRef USR, PresumedLoc Loc, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Create a macro definition record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSRForMacro(StringRef Name, SourceLocation SL, const SourceManager &SM) is a helper method to generate the USR for the macro and keep it alive in APISet.
Definition at line 487 of file API.cpp.
addNamespace()
NamespaceRecord * APISet::addNamespace (APIRecord * Parent, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeaderg)
Definition at line 47 of file API.cpp.
addObjCCategory()
ObjCCategoryRecord * APISet::addObjCCategory (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, SymbolReference Interface, bool IsFromSystemHeader, bool IsFromExternalModule)
Create and add an Objective-C category record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 380 of file API.cpp.
addObjCInstanceVariable()
ObjCInstanceVariableRecord * APISet::addObjCInstanceVariable (ObjCContainerRecord * Container, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, ObjCInstanceVariableRecord::AccessControl Access, bool IsFromSystemHeader)
Create and add an Objective-C instance variable record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 460 of file API.cpp.
addObjCInterface()
ObjCInterfaceRecord * APISet::addObjCInterface (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, SymbolReference SuperClass, bool IsFromSystemHeader)
Create and add an Objective-C interface record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 402 of file API.cpp.
addObjCMethod()
ObjCMethodRecord * APISet::addObjCMethod (ObjCContainerRecord * Container, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, FunctionSignature Signature, bool IsInstanceMethod, bool IsFromSystemHeader)
Create and add an Objective-C method record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 414 of file API.cpp.
addObjCProperty()
ObjCPropertyRecord * APISet::addObjCProperty (ObjCContainerRecord * Container, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, ObjCPropertyRecord::AttributeKind Attributes, StringRef GetterName, StringRef SetterName, bool IsOptional, bool IsInstanceProperty, bool IsFromSystemHeader)
Create and add an Objective-C property record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 436 of file API.cpp.
addObjCProtocol()
ObjCProtocolRecord * APISet::addObjCProtocol (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, bool IsFromSystemHeader)
Create and add an Objective-C protocol record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 474 of file API.cpp.
addRecord()
RecordRecord * APISet::addRecord (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, APIRecord::RecordKind Kind, bool IsFromSystemHeader)
Create and add a record record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 161 of file API.cpp.
addRecordField()
RecordFieldRecord * APISet::addRecordField (RecordRecord * Record, StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, APIRecord::RecordKind Kind, bool IsFromSystemHeader)
Create and add a record field record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 147 of file API.cpp.
addStaticField()
StaticFieldRecord * APISet::addStaticField (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, LinkageInfo Linkage, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, SymbolReference Context, AccessControl Access, bool IsFromSystemHeaderg)
Definition at line 174 of file API.cpp.
addTypedef()
TypedefRecord * APISet::addTypedef (StringRef Name, StringRef USR, PresumedLoc Loc, AvailabilityInfo Availability, const DocComment & Comment, DeclarationFragments Declaration, DeclarationFragments SubHeading, SymbolReference UnderlyingType, bool IsFromSystemHeader)
Create a typedef record into the API set.
Note: the caller is responsible for keeping the StringRef Name and USR alive. APISet::copyString provides a way to copy strings into APISet itself, and APISet::recordUSR(const Decl *D) is a helper method to generate the USR for D and keep it alive in APISet.
Definition at line 496 of file API.cpp.
copyString()
StringRef APISet::copyString (StringRef String)
Copy String into the Allocator in this APISet.
Returns
a StringRef of the copied string in APISet::Allocator.
Definition at line 526 of file API.cpp.
References memcpy().
Referenced by clang::extractapi::TypedefUnderlyingTypeResolver::getSymbolReferenceForType().
findRecordForUSR()
APIRecord * APISet::findRecordForUSR (StringRef USR) const
Finds the APIRecord for a given USR.
Returns
a pointer to the APIRecord associated with that USR or nullptr.
Definition at line 506 of file API.cpp.
Referenced by clang::extractapi::SymbolGraphSerializer::serializeSingleSymbolSGF().
getClassTemplatePartialSpecializations()
const RecordMap<ClassTemplatePartialSpecializationRecord>& clang::extractapi::APISet::getClassTemplatePartialSpecializations () const inline
Definition at line 1579 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseClassTemplatePartialSpecializationRecords().
getClassTemplates()
const RecordMap<ClassTemplateRecord>& clang::extractapi::APISet::getClassTemplates () const inline
Definition at line 1571 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseClassTemplateRecords().
getClassTemplateSpecializations()
const RecordMap<ClassTemplateSpecializationRecord>& clang::extractapi::APISet::getClassTemplateSpecializations () const inline
Definition at line 1575 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseClassTemplateSpecializationRecords().
getConcepts()
const RecordMap<ConceptRecord>& clang::extractapi::APISet::getConcepts () const inline
Definition at line 1582 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseConcepts().
getCXXClasses()
const RecordMap<CXXClassRecord>& clang::extractapi::APISet::getCXXClasses () const inline
Definition at line 1553 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseCXXClassRecords().
getCXXFields()
const RecordMap<CXXFieldRecord>& clang::extractapi::APISet::getCXXFields () const inline
Definition at line 1563 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseCXXFields().
getCXXFieldTemplates()
const RecordMap<CXXFieldTemplateRecord>& clang::extractapi::APISet::getCXXFieldTemplates () const inline
Definition at line 1568 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseCXXFieldTemplates().
getCXXInstanceMethods()
const RecordMap<CXXInstanceMethodRecord>& clang::extractapi::APISet::getCXXInstanceMethods () const inline
Definition at line 1557 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseCXXInstanceMethods().
getCXXMethodTemplates()
const RecordMap<CXXMethodTemplateRecord>& clang::extractapi::APISet::getCXXMethodTemplates () const inline
Definition at line 1554 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseCXXMethodTemplates().
getCXXMethodTemplateSpecializations()
const RecordMap<CXXMethodTemplateSpecializationRecord>& clang::extractapi::APISet::getCXXMethodTemplateSpecializations () const inline
Definition at line 1565 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseCXXMethodTemplateSpecializations().
getCXXStaticMethods()
const RecordMap<CXXStaticMethodRecord>& clang::extractapi::APISet::getCXXStaticMethods () const inline
Definition at line 1560 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseCXXStaticMethods().
getEnums()
const RecordMap<EnumRecord>& clang::extractapi::APISet::getEnums () const inline
Definition at line 1551 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseEnumRecords(), and clang::extractapi::impl::ExtractAPIVisitorBase< Derived >::VisitTypedefNameDecl().
getGlobalFunctions()
const RecordMap<GlobalFunctionRecord>& clang::extractapi::APISet::getGlobalFunctions () const inline
Definition at line 1522 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionRecords().
getGlobalFunctionTemplates()
const RecordMap<GlobalFunctionTemplateRecord>& clang::extractapi::APISet::getGlobalFunctionTemplates () const inline
Definition at line 1526 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionTemplateRecords().
getGlobalFunctionTemplateSpecializations()
const RecordMap<GlobalFunctionTemplateSpecializationRecord>& clang::extractapi::APISet::getGlobalFunctionTemplateSpecializations () const inline
Definition at line 1530 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionTemplateSpecializationRecords().
getGlobalVariables()
const RecordMap<GlobalVariableRecord>& clang::extractapi::APISet::getGlobalVariables () const inline
Definition at line 1533 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableRecords().
getGlobalVariableTemplatePartialSpecializations()
const RecordMap<GlobalVariableTemplatePartialSpecializationRecord>& clang::extractapi::APISet::getGlobalVariableTemplatePartialSpecializations () const inline
Definition at line 1548 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplatePartialSpecializationRecords().
getGlobalVariableTemplates()
const RecordMap<GlobalVariableTemplateRecord>& clang::extractapi::APISet::getGlobalVariableTemplates () const inline
Definition at line 1537 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplateRecords().
getGlobalVariableTemplateSpecializations()
const RecordMap<GlobalVariableTemplateSpecializationRecord>& clang::extractapi::APISet::getGlobalVariableTemplateSpecializations () const inline
Definition at line 1544 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplateSpecializationRecords().
getLanguage()
Language clang::extractapi::APISet::getLanguage () const inline
Get the language used by the APIs.
Definition at line 1519 of file API.h.
Referenced by clang::extractapi::SymbolGraphSerializer::serializeSingleSymbolSGF(), and clang::extractapi::SymbolGraphSerializer::visitObjCCategoryRecord().
getMacros()
const RecordMap<MacroDefinitionRecord>& clang::extractapi::APISet::getMacros () const inline
Definition at line 1592 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseMacroDefinitionRecords().
getNamespaces()
const RecordMap<NamespaceRecord>& clang::extractapi::APISet::getNamespaces () const inline
Definition at line 1521 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseNamespaces().
getObjCCategories()
const RecordMap<ObjCCategoryRecord>& clang::extractapi::APISet::getObjCCategories () const inline
Definition at line 1583 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseObjCCategories().
getObjCInterfaces()
const RecordMap<ObjCInterfaceRecord>& clang::extractapi::APISet::getObjCInterfaces () const inline
Definition at line 1586 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseObjCInterfaces().
getObjCProtocols()
const RecordMap<ObjCProtocolRecord>& clang::extractapi::APISet::getObjCProtocols () const inline
Definition at line 1589 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseObjCProtocols().
getRecords()
const RecordMap<RecordRecord>& clang::extractapi::APISet::getRecords () const inline
Definition at line 1552 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseRecordRecords(), and clang::extractapi::impl::ExtractAPIVisitorBase< Derived >::VisitTypedefNameDecl().
getStaticFields()
const RecordMap<StaticFieldRecord>& clang::extractapi::APISet::getStaticFields () const inline
Definition at line 1540 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseStaticFieldRecords().
getTarget()
const llvm::Triple& clang::extractapi::APISet::getTarget () const inline
Get the target triple for the ExtractAPI invocation.
Definition at line 1516 of file API.h.
getTypedefs()
const RecordMap<TypedefRecord>& clang::extractapi::APISet::getTypedefs () const inline
Definition at line 1593 of file API.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseTypedefRecords().
recordUSR()
StringRef APISet::recordUSR (const Decl * D)
Generate and store the USR of declaration D.
Note: The USR string is stored in and owned by Allocator.
Returns
a StringRef of the generated USR string.
Definition at line 513 of file API.cpp.
References copyString(), and clang::index::generateUSRForDecl().
Referenced by clang::extractapi::impl::ExtractAPIVisitorBase< Derived >::VisitCXXMethodDecl().
recordUSRForMacro()
StringRef APISet::recordUSRForMacro (StringRef Name, SourceLocation SL, const SourceManager & SM)
Generate and store the USR for a macro Name.
Note: The USR string is stored in and owned by Allocator.
Returns
a StringRef to the generate USR string.
Definition at line 519 of file API.cpp.
Member Data Documentation
ProductName
const std::string clang::extractapi::APISet::ProductName
Definition at line 1669 of file API.h.
Referenced by clang::extractapi::SymbolGraphSerializer::serializeSingleSymbolSGF().
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/API.h
lib/ExtractAPI/API.cpp