clang: clang::extractapi::RecordContext Class Reference
clang::extractapi::RecordContext Class Reference
Base class used for specific record types that have children records this is analogous to the DeclContext for the AST.
#include "clang/ExtractAPI/API.h"
Classes
struct record_iterator
Public Types
using record_range = llvm::iterator_range< record_iterator >
Public Member Functions
RecordContext (APIRecord::RecordKind Kind)
void stealRecordChain (RecordContext &Other)
Append Other children chain into ours and empty out Other's record chain.
APIRecord::RecordKind getKind () const
record_range records () const
record_iterator records_begin () const
record_iterator records_end () const
bool records_empty () const
Static Public Member Functions
static bool classof (const APIRecord *Record)
static bool classofKind (APIRecord::RecordKind K)
static bool classof (const RecordContext *Context)
Protected Member Functions
void addToRecordChain (APIRecord *) const
Friends
class APISet
Detailed Description
Base class used for specific record types that have children records this is analogous to the DeclContext for the AST.
Definition at line 310 of file API.h.
Member Typedef Documentation
record_range
using clang::extractapi::RecordContext::record_range = llvm::iterator_range<record_iterator>
Definition at line 365 of file API.h.
Constructor & Destructor Documentation
RecordContext()
clang::extractapi::RecordContext::RecordContext (APIRecord::RecordKind Kind) inline
Definition at line 322 of file API.h.
Member Function Documentation
addToRecordChain()
void RecordContext::addToRecordChain (APIRecord * Record) const protected
Definition at line 77 of file API.cpp.
classof() [1/2]
static bool clang::extractapi::RecordContext::classof (const APIRecord * Record) inline static
Definition at line 312 of file API.h.
References classofKind().
Referenced by clang::extractapi::ToRecordContextCastInfoWrapper< FromTy, IsKnownSubType >::isPossible().
classof() [2/2]
static bool clang::extractapi::RecordContext::classof (const RecordContext * Context) inline static
Definition at line 320 of file API.h.
classofKind()
static bool clang::extractapi::RecordContext::classofKind (APIRecord::RecordKind K) inline static
Definition at line 315 of file API.h.
References clang::extractapi::APIRecord::RK_FirstRecordContext, and clang::extractapi::APIRecord::RK_LastRecordContext.
Referenced by classof().
getKind()
APIRecord::RecordKind clang::extractapi::RecordContext::getKind () const inline
Definition at line 328 of file API.h.
Referenced by clang::extractapi::APIRecord::castFromRecordContext(), clang::extractapi::FromRecordContextCastInfoWrapper< ToTy, IsKnownSubType >::isPossible(), and clang::extractapi::FromRecordContextCastInfoWrapper< ToTy, true >::isPossible().
records()
record_range clang::extractapi::RecordContext::records () const inline
Definition at line 366 of file API.h.
References records_begin(), and records_end().
records_begin()
record_iterator clang::extractapi::RecordContext::records_begin () const inline
Definition at line 369 of file API.h.
Referenced by records().
records_empty()
bool clang::extractapi::RecordContext::records_empty () const inline
Definition at line 371 of file API.h.
records_end()
record_iterator clang::extractapi::RecordContext::records_end () const inline
Definition at line 370 of file API.h.
Referenced by records().
stealRecordChain()
void RecordContext::stealRecordChain (RecordContext & Other)
Append Other children chain into ours and empty out Other's record chain.
Definition at line 62 of file API.cpp.
References clang::Other.
Referenced by clang::extractapi::impl::ExtractAPIVisitorBase< Derived >::maybeMergeWithAnonymousTag().
Friends And Related Function Documentation
APISet
friend class APISet friend
Definition at line 380 of file API.h.
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/API.h
lib/ExtractAPI/API.cpp