clang: clang::FieldDecl Class Reference
clang::FieldDecl Class Reference
Represents a member of a struct/union/class.
#include "clang/AST/Decl.h"
Public Member Functions
unsigned getFieldIndex () const
Returns the index of this field within its record, as appropriate for passing to ASTRecordLayout::getFieldOffset.
bool isMutable () const
Determines whether this field is mutable (C++ only).
bool isBitField () const
Determines whether this field is a bitfield.
bool isUnnamedBitfield () const
Determines whether this is an unnamed bitfield.
bool isAnonymousStructOrUnion () const
Determines whether this field is a representative for an anonymous struct or union.
Expr * getBitWidth () const
unsigned getBitWidthValue (const ASTContext &Ctx) const
void setBitWidth (Expr *Width)
Set the bit-field width for this member.
void removeBitWidth ()
Remove the bit-field width from this member.
bool isZeroLengthBitField (const ASTContext &Ctx) const
Is this a zero-length bit-field? Such bit-fields aren't really bit-fields at all and instead act as a separator between contiguous runs of other bit-fields.
bool isZeroSize (const ASTContext &Ctx) const
Determine if this field is a subobject of zero size, that is, either a zero-length bit-field or a field of empty class type with the [[no_unique_address]] attribute.
InClassInitStyle getInClassInitStyle () const
Get the kind of (C++11) default member initializer that this field has.
bool hasInClassInitializer () const
Determine whether this member has a C++11 default member initializer.
Expr * getInClassInitializer () const
Get the C++11 default member initializer for this member, or null if one has not been set.
void setInClassInitializer (Expr *Init)
Set the C++11 in-class initializer for this member.
void removeInClassInitializer ()
Remove the C++11 in-class initializer from this member.
bool hasCapturedVLAType () const
Determine whether this member captures the variable length array type.
const VariableArrayType * getCapturedVLAType () const
Get the captured variable length array type.
void setCapturedVLAType (const VariableArrayType *VLAType)
Set the captured variable length array type for this field.
const RecordDecl * getParent () const
Returns the parent of this field declaration, which is the struct in which this field is defined.
RecordDecl * getParent ()
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
FieldDecl * getCanonicalDecl () override
Retrieves the canonical declaration of this field.
const FieldDecl * getCanonicalDecl () const
Public Member Functions inherited from clang::DeclaratorDecl
TypeSourceInfo * getTypeSourceInfo () const
void setTypeSourceInfo (TypeSourceInfo *TI)
SourceLocation getInnerLocStart () const
Return start of source range ignoring outer template declarations.
void setInnerLocStart (SourceLocation L)
SourceLocation getOuterLocStart () const
Return start of source range taking into account any outer template declarations.
SourceLocation getBeginLoc () const LLVM_READONLY
NestedNameSpecifier * getQualifier () const
Retrieve the nested-name-specifier that qualifies the name of this declaration, if it was present in the source.
NestedNameSpecifierLoc getQualifierLoc () const
Retrieve the nested-name-specifier (with source-location information) that qualifies the name of this declaration, if it was present in the source.
void setQualifierInfo (NestedNameSpecifierLoc QualifierLoc)
Expr * getTrailingRequiresClause ()
Get the constraint-expression introduced by the trailing requires-clause in the function/member declaration, or null if no requires-clause was provided.
const Expr * getTrailingRequiresClause () const
void setTrailingRequiresClause (Expr *TrailingRequiresClause)
unsigned getNumTemplateParameterLists () const
TemplateParameterList * getTemplateParameterList (unsigned index) const
void setTemplateParameterListsInfo (ASTContext &Context, ArrayRef< TemplateParameterList * > TPLists)
SourceLocation getTypeSpecStartLoc () const
SourceLocation getTypeSpecEndLoc () const
Public Member Functions inherited from clang::ValueDecl
QualType getType () const
void setType (QualType newType)
bool isWeak () const
Determine whether this symbol is weakly-imported, or declared with the weak or weak-ref attr.
Public Member Functions inherited from clang::NamedDecl
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
virtual void printName (raw_ostream &os) const
Pretty-print the unqualified name of this declaration.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy, bool WithGlobalNsPrefix=false) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy, bool WithGlobalNsPrefix=false) const
std::string getQualifiedNameAsString (bool WithGlobalNsPrefix=false) const
virtual void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const
Appends a human-readable name for this declaration into the given stream.
bool declarationReplaces (NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
ReservedIdentifierStatus isReserved (const LangOptions &LangOpts) const
Determine if the declaration obeys the reserved identifier rules of the given language.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
Optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool isInExportDeclContext () const
Whether this declaration was exported in a lexical context.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
unsigned getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
virtual bool isOutOfLine () const
Determine whether this declaration is declared out of line (outside its semantic context).
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod () const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod ()
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual Stmt * getBody () const
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl ()
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
Public Member Functions inherited from clang::Mergeable< FieldDecl >
Mergeable ()=default
FieldDecl * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const FieldDecl * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
Returns true if this is the first declaration.
Static Public Member Functions
static FieldDecl * Create (const ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, QualType T, TypeSourceInfo *TInfo, Expr *BW, bool Mutable, InClassInitStyle InitStyle)
static FieldDecl * CreateDeserialized (ASTContext &C, unsigned ID)
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::DeclaratorDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::ValueDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::NamedDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Protected Member Functions
FieldDecl (Kind DK, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, QualType T, TypeSourceInfo *TInfo, Expr *BW, bool Mutable, InClassInitStyle InitStyle)
Protected Member Functions inherited from clang::DeclaratorDecl
DeclaratorDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N, QualType T, TypeSourceInfo *TInfo, SourceLocation StartL)
Protected Member Functions inherited from clang::ValueDecl
ValueDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N, QualType T)
Protected Member Functions inherited from clang::NamedDecl
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, unsigned ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
virtual Decl * getNextRedeclarationImpl ()
Returns the next redeclaration or itself if this is the only decl.
virtual Decl * getPreviousDeclImpl ()
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
virtual Decl * getMostRecentDeclImpl ()
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
ASTMutationListener * getASTMutationListener () const
Friends
class ASTDeclReader
class ASTDeclWriter
Additional Inherited Members
Public Types inherited from clang::NamedDecl
enum ExplicitVisibilityKind { VisibilityForType, VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001, IDNS_Tag = 0x0002, IDNS_Type = 0x0004, IDNS_Member = 0x0008,
IDNS_Namespace = 0x0010, IDNS_Ordinary = 0x0020, IDNS_ObjCProtocol = 0x0040, IDNS_OrdinaryFriend = 0x0080,
IDNS_TagFriend = 0x0100, IDNS_Using = 0x0200, IDNS_NonMemberOperator = 0x0400, IDNS_LocalExtern = 0x0800,
IDNS_OMPReduction = 0x1000, IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0, OBJC_TQ_In = 0x1, OBJC_TQ_Inout = 0x2, OBJC_TQ_Out = 0x4,
OBJC_TQ_Bycopy = 0x8, OBJC_TQ_Byref = 0x10, OBJC_TQ_Oneway = 0x20, OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum ModuleOwnershipKind : unsigned { ModuleOwnershipKind::Unowned, ModuleOwnershipKind::Visible, ModuleOwnershipKind::VisibleWhenImported, ModuleOwnershipKind::ModulePrivate }
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None, FOK_Declared, FOK_Undeclared }
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range< attr_iterator >
using redecl_range = llvm::iterator_range< redecl_iterator >
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 2, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Detailed Description
Represents a member of a struct/union/class.
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2839 of file Decl.h.
Constructor & Destructor Documentation
FieldDecl()
clang::FieldDecl::FieldDecl (Kind DK, DeclContext * DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo * Id, QualType T, TypeSourceInfo * TInfo, Expr * BW, bool Mutable, InClassInitStyle InitStyle) inline protected
Definition at line 2886 of file Decl.h.
References setBitWidth().
Referenced by Create(), and CreateDeserialized().
Member Function Documentation
classof()
static bool clang::FieldDecl::classof (const Decl * D) inline static
Definition at line 3046 of file Decl.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::FieldDecl::classofKind (Kind K) inline static
Definition at line 3047 of file Decl.h.
Referenced by classof().
Create()
FieldDecl * FieldDecl::Create (const ASTContext & C, DeclContext * DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo * Id, QualType T, TypeSourceInfo * TInfo, Expr * BW, bool Mutable, InClassInitStyle InitStyle) static
Definition at line 4193 of file Decl.cpp.
References AttributeLangSupport::C, FieldDecl(), and Id.
Referenced by addFieldToRecordDecl(), clang::Sema::BuildCaptureField(), clang::CodeGen::CGOpenMPRuntimeGPU::clear(), CreateAAPCSABIBuiltinVaListDecl(), CreateAArch64ABIBuiltinVaListDecl(), CreateHexagonBuiltinVaListDecl(), CreatePowerABIBuiltinVaListDecl(), CreateSystemZBuiltinVaListDecl(), CreateX86_64ABIBuiltinVaListDecl(), clang::ASTContext::getBlockDescriptorExtendedType(), clang::ASTContext::getBlockDescriptorType(), and clang::CodeGen::CodeGenModule::getObjCFastEnumerationStateType().
CreateDeserialized()
FieldDecl * FieldDecl::CreateDeserialized (ASTContext & C, unsigned ID) static
Definition at line 4202 of file Decl.cpp.
References AttributeLangSupport::C, FieldDecl(), and clang::ICIS_NoInit.
getBitWidth()
Expr* clang::FieldDecl::getBitWidth () const inline
Definition at line 2928 of file Decl.h.
References getInClassInitStyle().
Referenced by clang::Sema::CheckImplementationIvars(), getBitWidthValue(), getSourceRange(), IsStructurallyEquivalent(), isZeroLengthBitField(), removeInClassInitializer(), clang::ASTDeclWriter::VisitFieldDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFieldDecl(), and clang::ASTDeclWriter::VisitObjCIvarDecl().
getBitWidthValue()
unsigned FieldDecl::getBitWidthValue (const ASTContext & Ctx) const
Definition at line 4218 of file Decl.cpp.
References clang::Expr::EvaluateKnownConstInt(), getBitWidth(), and isBitField().
Referenced by clang::Sema::CheckImplementationIvars(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), getFieldSize(), isLayoutCompatible(), isZeroLengthBitField(), and truncateBitfieldValue().
getCanonicalDecl() [1/2]
const FieldDecl* clang::FieldDecl::getCanonicalDecl () const inline
Definition at line 3043 of file Decl.h.
References clang::Mergeable< FieldDecl >::getFirstDecl().
getCanonicalDecl() [2/2]
FieldDecl* clang::FieldDecl::getCanonicalDecl () inline override virtual
Retrieves the canonical declaration of this field.
Reimplemented from clang::Decl.
Reimplemented in clang::ObjCIvarDecl.
Definition at line 3042 of file Decl.h.
References clang::Mergeable< FieldDecl >::getFirstDecl().
Referenced by clang::CodeGen::CGRecordLayout::getBitFieldInfo(), clang::ObjCIvarDecl::getCanonicalDecl(), getFieldIndex(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), and clang::Sema::SetCtorInitializers().
getCapturedVLAType()
const VariableArrayType* clang::FieldDecl::getCapturedVLAType () const inline
Get the captured variable length array type.
Definition at line 3017 of file Decl.h.
References hasCapturedVLAType().
Referenced by clang::ASTDeclWriter::VisitFieldDecl(), and clang::ento::ExprEngine::VisitLambdaExpr().
getFieldIndex()
unsigned FieldDecl::getFieldIndex () const
Returns the index of this field within its record, as appropriate for passing to ASTRecordLayout::getFieldOffset.
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 4261 of file Decl.cpp.
References getCanonicalDecl(), and getFieldIndex().
Referenced by clang::CodeGen::CodeGenFunction::EmitLValueForField(), emitPreserveStructAccess(), getFieldIndex(), getFieldOffset(), clang::CodeGen::CodeGenFunction::getOverlapForFieldInit(), HandleConstructorCall(), HandleLValueMember(), and isDesignatorAtObjectEnd().
getInClassInitializer()
Expr* clang::FieldDecl::getInClassInitializer () const inline
Get the C++11 default member initializer for this member, or null if one has not been set.
If a valid declaration has a default member initializer, but this returns null, then we have not parsed and attached it yet.
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2986 of file Decl.h.
References hasInClassInitializer().
Referenced by clang::CXXCtorInitializer::getSourceRange(), getSourceRange(), clang::Sema::InstantiateInClassInitializer(), removeBitWidth(), setBitWidth(), setInClassInitializer(), clang::ASTDeclWriter::VisitFieldDecl(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFieldDecl().
getInClassInitStyle()
InClassInitStyle clang::FieldDecl::getInClassInitStyle () const inline
Get the kind of (C++11) default member initializer that this field has.
Definition at line 2972 of file Decl.h.
References clang::ICIS_NoInit.
Referenced by clang::Sema::ActOnFinishCXXInClassMemberInitializer(), getBitWidth(), hasInClassInitializer(), and clang::Sema::InstantiateInClassInitializer().
getParent() [1/2]
RecordDecl* clang::FieldDecl::getParent () inline
Definition at line 3035 of file Decl.h.
References clang::Decl::getDeclContext().
getParent() [2/2]
const RecordDecl* clang::FieldDecl::getParent () const inline
Returns the parent of this field declaration, which is the struct in which this field is defined.
Returns null if this is not a normal class/struct field declaration, e.g. ObjCAtDefsFieldDecl, ObjCIvarDecl.
Definition at line 3031 of file Decl.h.
References clang::Decl::getDeclContext().
Referenced by clang::Sema::CheckNontrivialField(), emitAddrOfFieldStorage(), EmitCapturedFieldLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), emitPreserveStructAccess(), evalBinOpFieldRegionFieldRegion(), EvaluateComparisonBinaryOperator(), getFieldOffset(), clang::CodeGen::CodeGenFunction::getOverlapForFieldInit(), HandleConstructorCall(), HandleLValueMember(), hasUnguardedAccess(), clang::Sema::InstantiateInClassInitializer(), isDesignatorAtObjectEnd(), clang::Sema::RefersToMemberWithReducedAlignment(), setCapturedVLAType(), and clang::Sema::SetCtorInitializers().
getSourceRange()
SourceRange FieldDecl::getSourceRange () const override virtual
Source range that this declaration covers.
Reimplemented from clang::DeclaratorDecl.
Definition at line 4281 of file Decl.cpp.
References getBitWidth(), clang::Stmt::getEndLoc(), getInClassInitializer(), clang::DeclaratorDecl::getInnerLocStart(), and clang::DeclaratorDecl::getSourceRange().
hasCapturedVLAType()
bool clang::FieldDecl::hasCapturedVLAType () const inline
Determine whether this member captures the variable length array type.
Definition at line 3012 of file Decl.h.
Referenced by getCapturedVLAType(), setBitWidth(), clang::ASTDeclWriter::VisitFieldDecl(), and clang::ento::ExprEngine::VisitLambdaExpr().
hasInClassInitializer()
bool clang::FieldDecl::hasInClassInitializer () const inline
Determine whether this member has a C++11 default member initializer.
Definition at line 2979 of file Decl.h.
References getInClassInitStyle(), and clang::ICIS_NoInit.
Referenced by clang::Sema::BuildCXXDefaultInitExpr(), getInClassInitializer(), clang::Sema::InstantiateInClassInitializer(), removeInClassInitializer(), setInClassInitializer(), clang::ASTDeclWriter::VisitFieldDecl(), and clang::JSONNodeDumper::VisitFieldDecl().
isAnonymousStructOrUnion()
bool FieldDecl::isAnonymousStructOrUnion () const
Determines whether this field is a representative for an anonymous struct or union.
Such fields are unnamed and are implicitly generated by the implementation to store the data for the anonymous union or struct.
Definition at line 4208 of file Decl.cpp.
References clang::NamedDecl::getDeclName(), clang::ValueDecl::getType(), and clang::Decl::isImplicit().
Referenced by IsStructurallyEquivalent().
isBitField()
bool clang::FieldDecl::isBitField () const inline
Determines whether this field is a bitfield.
Definition at line 2917 of file Decl.h.
Referenced by clang::Sema::ActOnLastBitfield(), clang::Sema::BuildDeclRefExpr(), clang::Sema::CheckImplementationIvars(), clang::CodeGen::CodeGenFunction::EmitAsanPrologueOrEpilogue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), findSubobject(), clang::CodeGen::CGRecordLayout::getBitFieldInfo(), getBitWidthValue(), getFieldSize(), clang::Expr::getSourceBitField(), HandleConstructorCall(), isIntegerLikeType(), isLayoutCompatible(), IsStructurallyEquivalent(), isUnnamedBitfield(), removeBitWidth(), setUsedBits(), truncateBitfieldValue(), clang::JSONNodeDumper::VisitFieldDecl(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFieldDecl().
isMutable()
bool clang::FieldDecl::isMutable () const inline
Determines whether this field is mutable (C++ only).
Definition at line 2914 of file Decl.h.
Referenced by clang::ASTDeclWriter::VisitFieldDecl(), clang::JSONNodeDumper::VisitFieldDecl(), and clang::TextNodeDumper::VisitFieldDecl().
isUnnamedBitfield()
bool clang::FieldDecl::isUnnamedBitfield () const inline
Determines whether this is an unnamed bitfield.
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2920 of file Decl.h.
References clang::NamedDecl::getDeclName(), and isBitField().
Referenced by isEmptyField(), isZeroLengthBitField(), and setUsedBits().
isZeroLengthBitField()
bool FieldDecl::isZeroLengthBitField (const ASTContext & Ctx) const
Is this a zero-length bit-field? Such bit-fields aren't really bit-fields at all and instead act as a separator between contiguous runs of other bit-fields.
Definition at line 4223 of file Decl.cpp.
References getBitWidth(), getBitWidthValue(), isUnnamedBitfield(), and clang::Expr::isValueDependent().
Referenced by clang::Sema::ActOnLastBitfield(), isZeroSize(), and setUsedBits().
isZeroSize()
bool FieldDecl::isZeroSize (const ASTContext & Ctx) const
Determine if this field is a subobject of zero size, that is, either a zero-length bit-field or a field of empty class type with the [[no_unique_address]] attribute.
Definition at line 4228 of file Decl.cpp.
References clang::Type::getAs(), clang::RecordDecl::getDefinition(), clang::ValueDecl::getType(), clang::Decl::isInvalidDecl(), and isZeroLengthBitField().
Referenced by emitAddrOfFieldStorage().
removeBitWidth()
void clang::FieldDecl::removeBitWidth () inline
Remove the bit-field width from this member.
Definition at line 2955 of file Decl.h.
References getInClassInitializer(), and isBitField().
removeInClassInitializer()
void clang::FieldDecl::removeInClassInitializer () inline
Remove the C++11 in-class initializer from this member.
Definition at line 3005 of file Decl.h.
References getBitWidth(), and hasInClassInitializer().
Referenced by clang::Sema::ActOnFinishCXXInClassMemberInitializer().
setBitWidth()
void clang::FieldDecl::setBitWidth (Expr * Width) inline
Set the bit-field width for this member.
Definition at line 2941 of file Decl.h.
References clang::Decl::getASTContext(), getInClassInitializer(), and hasCapturedVLAType().
Referenced by FieldDecl(), and clang::ASTDeclReader::VisitFieldDecl().
setCapturedVLAType()
void FieldDecl::setCapturedVLAType (const VariableArrayType * VLAType)
Set the captured variable length array type for this field.
Definition at line 4290 of file Decl.cpp.
References getParent().
setInClassInitializer()
void clang::FieldDecl::setInClassInitializer (Expr * Init) inline
Set the C++11 in-class initializer for this member.
Definition at line 2996 of file Decl.h.
References getInClassInitializer(), and hasInClassInitializer().
Referenced by clang::Sema::ActOnFinishCXXInClassMemberInitializer().
Friends And Related Function Documentation
ASTDeclReader
friend class ASTDeclReader friend
Definition at line 2898 of file Decl.h.
ASTDeclWriter
friend class ASTDeclWriter friend
Definition at line 2899 of file Decl.h.
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp