clang: clang::CodeGen::EHCatchScope Class Reference
clang::CodeGen::EHCatchScope Class Reference
A scope which attempts to handle some, possibly all, types of exceptions.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCleanup.h"
Classes
struct Handler
Public Member Functions
EHCatchScope (unsigned numHandlers, EHScopeStack::stable_iterator enclosingEHScope)
unsigned getNumHandlers () const
void setCatchAllHandler (unsigned I, llvm::BasicBlock *Block)
void setHandler (unsigned I, llvm::Constant *Type, llvm::BasicBlock *Block)
void setHandler (unsigned I, CatchTypeInfo Type, llvm::BasicBlock *Block)
const Handler & getHandler (unsigned I) const
void clearHandlerBlocks ()
iterator begin () const
iterator end () const
Public Member Functions inherited from clang::CodeGen::EHScope
EHScope (Kind kind, EHScopeStack::stable_iterator enclosingEHScope)
Kind getKind () const
llvm::BasicBlock * getCachedLandingPad () const
void setCachedLandingPad (llvm::BasicBlock *block)
llvm::BasicBlock * getCachedEHDispatchBlock () const
void setCachedEHDispatchBlock (llvm::BasicBlock *block)
bool hasEHBranches () const
EHScopeStack::stable_iterator getEnclosingEHScope () const
Static Public Member Functions
static size_t getSizeForNumHandlers (unsigned N)
static bool classof (const EHScope *Scope)
Public Attributes
const typedef Handler * iterator
Friends
class EHScopeStack
Additional Inherited Members
Public Types inherited from clang::CodeGen::EHScope
enum Kind { Cleanup, Catch, Terminate, Filter }
Protected Attributes inherited from clang::CodeGen::EHScope
union {
CommonBitFields CommonBits
CatchBitFields CatchBits
CleanupBitFields CleanupBits
FilterBitFields FilterBits
};
Detailed Description
A scope which attempts to handle some, possibly all, types of exceptions.
Objective C @finally blocks are represented using a cleanup scope after the catch scope.
Definition at line 146 of file CGCleanup.h.
Constructor & Destructor Documentation
EHCatchScope()
clang::CodeGen::EHCatchScope::EHCatchScope (unsigned numHandlers, EHScopeStack::stable_iterator enclosingEHScope) inline
Definition at line 180 of file CGCleanup.h.
References clang::CodeGen::EHScope::CatchBits.
Referenced by getSizeForNumHandlers().
Member Function Documentation
begin()
iterator clang::CodeGen::EHCatchScope::begin () const inline
Definition at line 222 of file CGCleanup.h.
classof()
static bool clang::CodeGen::EHCatchScope::classof (const EHScope * Scope) inline static
Definition at line 225 of file CGCleanup.h.
References clang::CodeGen::EHScope::Catch.
clearHandlerBlocks()
void clang::CodeGen::EHCatchScope::clearHandlerBlocks () inline
Definition at line 216 of file CGCleanup.h.
References clang::CodeGen::EHCatchScope::Handler::Block, getHandler(), and getNumHandlers().
end()
iterator clang::CodeGen::EHCatchScope::end () const inline
Definition at line 223 of file CGCleanup.h.
References getNumHandlers().
getHandler()
const Handler& clang::CodeGen::EHCatchScope::getHandler (unsigned I) const inline
Definition at line 207 of file CGCleanup.h.
References getNumHandlers().
Referenced by clearHandlerBlocks(), emitCatchDispatchBlock(), emitCatchPadBlock(), clang::CodeGen::CodeGenFunction::EmitLandingPad(), emitWasmCatchPadBlock(), clang::CodeGen::CodeGenFunction::FinallyInfo::exit(), and clang::CodeGen::CodeGenFunction::getEHDispatchBlock().
getNumHandlers()
unsigned clang::CodeGen::EHCatchScope::getNumHandlers () const inline
Definition at line 187 of file CGCleanup.h.
References clang::CodeGen::EHScope::CatchBits.
Referenced by clearHandlerBlocks(), emitCatchDispatchBlock(), emitCatchPadBlock(), clang::CodeGen::CodeGenFunction::EmitLandingPad(), emitWasmCatchPadBlock(), end(), clang::CodeGen::CodeGenFunction::getEHDispatchBlock(), getHandler(), clang::CodeGen::EHScopeStack::popCatch(), and setHandler().
getSizeForNumHandlers()
static size_t clang::CodeGen::EHCatchScope::getSizeForNumHandlers (unsigned N) inline static
Definition at line 176 of file CGCleanup.h.
References EHCatchScope().
Referenced by clang::CodeGen::EHScopeStack::iterator::operator++(), clang::CodeGen::EHScopeStack::popCatch(), and clang::CodeGen::EHScopeStack::pushCatch().
setCatchAllHandler()
void clang::CodeGen::EHCatchScope::setCatchAllHandler (unsigned I, llvm::BasicBlock * Block) inline
Definition at line 191 of file CGCleanup.h.
References clang::Block, and setHandler().
Referenced by clang::CodeGen::CodeGenFunction::FinallyInfo::enter().
setHandler() [1/2]
void clang::CodeGen::EHCatchScope::setHandler (unsigned I, CatchTypeInfo Type, llvm::BasicBlock * Block) inline
Definition at line 201 of file CGCleanup.h.
References clang::CodeGen::EHCatchScope::Handler::Block, clang::Block, getNumHandlers(), Type, and clang::CodeGen::EHCatchScope::Handler::Type.
setHandler() [2/2]
void clang::CodeGen::EHCatchScope::setHandler (unsigned I, llvm::Constant * Type, llvm::BasicBlock * Block) inline
Definition at line 195 of file CGCleanup.h.
References clang::CodeGen::EHCatchScope::Handler::Block, clang::Block, getNumHandlers(), Type, and clang::CodeGen::EHCatchScope::Handler::Type.
Referenced by setCatchAllHandler().
Friends And Related Function Documentation
EHScopeStack
friend class EHScopeStack friend
Definition at line 165 of file CGCleanup.h.
Member Data Documentation
iterator
const typedef Handler* clang::CodeGen::EHCatchScope::iterator
Definition at line 221 of file CGCleanup.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CGCleanup.h