clang: clang::driver::InputInfo Class Reference
clang::driver::InputInfo Class Reference
InputInfo - Wrapper for information about an input source.
#include "clang/Driver/InputInfo.h"
Public Member Functions
InputInfo ()
InputInfo (const Action *A, const char *_BaseInput)
InputInfo (types::ID _Type, const char *_Filename, const char *_BaseInput)
InputInfo (const Action *A, const char *_Filename, const char *_BaseInput)
InputInfo (types::ID _Type, const llvm::opt::Arg *_InputArg, const char *_BaseInput)
InputInfo (const Action *A, const llvm::opt::Arg *_InputArg, const char *_BaseInput)
bool isNothing () const
bool isFilename () const
bool isInputArg () const
types::ID getType () const
const char * getBaseInput () const
const Action * getAction () const
The action for which this InputInfo was created. May be null.
void setAction (const Action *A)
const char * getFilename () const
const llvm::opt::Arg & getInputArg () const
std::string getAsString () const
getAsString - Return a string name for this input, for debugging.
Detailed Description
InputInfo - Wrapper for information about an input source.
Definition at line 22 of file InputInfo.h.
Constructor & Destructor Documentation
InputInfo() [1/6]
clang::driver::InputInfo::InputInfo () inline
Definition at line 50 of file InputInfo.h.
InputInfo() [2/6]
clang::driver::InputInfo::InputInfo (const Action * A, const char * _BaseInput) inline
Definition at line 51 of file InputInfo.h.
InputInfo() [3/6]
clang::driver::InputInfo::InputInfo (types::ID _Type, const char * _Filename, const char * _BaseInput) inline
Definition at line 54 of file InputInfo.h.
InputInfo() [4/6]
clang::driver::InputInfo::InputInfo (const Action * A, const char * _Filename, const char * _BaseInput) inline
Definition at line 58 of file InputInfo.h.
InputInfo() [5/6]
clang::driver::InputInfo::InputInfo (types::ID _Type, const llvm::opt::Arg * _InputArg, const char * _BaseInput) inline
Definition at line 63 of file InputInfo.h.
InputInfo() [6/6]
clang::driver::InputInfo::InputInfo (const Action * A, const llvm::opt::Arg * _InputArg, const char * _BaseInput) inline
Definition at line 68 of file InputInfo.h.
Member Function Documentation
getAction()
const Action* clang::driver::InputInfo::getAction () const inline
The action for which this InputInfo was created. May be null.
Definition at line 80 of file InputInfo.h.
Referenced by clang::driver::tools::OffloadPackager::ConstructJob().
getAsString()
std::string clang::driver::InputInfo::getAsString () const inline
getAsString - Return a string name for this input, for debugging.
Definition at line 94 of file InputInfo.h.
References getFilename(), isFilename(), and isInputArg().
getBaseInput()
const char* clang::driver::InputInfo::getBaseInput () const inline
Definition at line 78 of file InputInfo.h.
Referenced by addPGOAndCoverageFlags(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::Clang::getBaseInputName(), clang::driver::tools::getStatsFileName(), and renderRemarksOptions().
getFilename()
const char* clang::driver::InputInfo::getFilename () const inline
Definition at line 83 of file InputInfo.h.
References isFilename().
Referenced by constructHexagonLinkArgs(), clang::driver::tools::aix::Assembler::ConstructJob(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::amdgpu::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::baremetal::StaticLibTool::ConstructJob(), clang::driver::tools::baremetal::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::tools::SPIRVTranslator::ConstructJob(), clang::driver::tools::SYCLPostLink::ConstructJob(), clang::driver::tools::FileTableTform::ConstructJob(), clang::driver::tools::AppendFooter::ConstructJob(), clang::driver::tools::SpirvToIrWrapper::ConstructJob(), clang::driver::tools::CrossWindows::Assembler::ConstructJob(), clang::driver::tools::CrossWindows::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::NVPTX::Assembler::ConstructJob(), clang::driver::tools::NVPTX::FatBinary::ConstructJob(), clang::driver::tools::NVPTX::Linker::ConstructJob(), clang::driver::tools::NVPTX::OpenMPLinker::ConstructJob(), clang::driver::tools::darwin::Assembler::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::darwin::StaticLibTool::ConstructJob(), clang::driver::tools::darwin::Lipo::ConstructJob(), clang::driver::tools::darwin::Dsymutil::ConstructJob(), clang::driver::tools::darwin::VerifyDebug::ConstructJob(), clang::driver::tools::dragonfly::Assembler::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::StaticLibTool::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::gnutools::StaticLibTool::ConstructJob(), clang::driver::tools::gcc::Common::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::AMDGCN::Linker::ConstructJob(), clang::driver::tools::HIPSPV::Linker::ConstructJob(), clang::driver::tools::hlsl::Validator::ConstructJob(), clang::driver::tools::ifstool::Merger::ConstructJob(), clang::driver::tools::MinGW::Assembler::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Assembler::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::SPIRV::Linker::ConstructJob(), clang::driver::tools::SYCL::fpga::BackendCompiler::ConstructJob(), clang::driver::tools::SYCL::gen::BackendCompiler::ConstructJob(), clang::driver::tools::SYCL::x86_64::BackendCompiler::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), clang::driver::tools::XCore::Assembler::ConstructJob(), clang::driver::tools::XCore::Linker::ConstructJob(), clang::driver::tools::zos::Assembler::ConstructJob(), clang::driver::tools::zos::Linker::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), clang::driver::tools::SPIRV::constructTranslateCommand(), getAsString(), clang::driver::ToolChain::getInputFilename(), clang::driver::tools::getStatsFileName(), clang::driver::Command::Print(), renderDebugOptions(), RenderModulesOptions(), and renderRemarksOptions().
getInputArg()
const llvm::opt::Arg& clang::driver::InputInfo::getInputArg () const inline
Definition at line 87 of file InputInfo.h.
References isInputArg().
getType()
types::ID clang::driver::InputInfo::getType () const inline
Definition at line 77 of file InputInfo.h.
Referenced by addDashXForInput(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), clang::driver::tools::SPIRV::constructTranslateCommand(), clang::driver::toolchains::CudaToolChain::getInputFilename(), RenderAnalyzerOptions(), RenderModulesOptions(), and RenderObjCOptions().
isFilename()
bool clang::driver::InputInfo::isFilename () const inline
Definition at line 75 of file InputInfo.h.
References Filename.
Referenced by clang::driver::tools::aix::Assembler::ConstructJob(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::baremetal::StaticLibTool::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::tools::SYCLPostLink::ConstructJob(), clang::driver::tools::FileTableTform::ConstructJob(), clang::driver::tools::NVPTX::Assembler::ConstructJob(), clang::driver::tools::NVPTX::Linker::ConstructJob(), clang::driver::tools::NVPTX::OpenMPLinker::ConstructJob(), clang::driver::tools::darwin::Assembler::ConstructJob(), clang::driver::tools::darwin::StaticLibTool::ConstructJob(), clang::driver::tools::darwin::Lipo::ConstructJob(), clang::driver::tools::darwin::Dsymutil::ConstructJob(), clang::driver::tools::darwin::VerifyDebug::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::StaticLibTool::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::gnutools::StaticLibTool::ConstructJob(), clang::driver::tools::gcc::Common::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::hlsl::Validator::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Assembler::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::XCore::Linker::ConstructJob(), clang::driver::tools::zos::Assembler::ConstructJob(), clang::driver::tools::zos::Linker::ConstructJob(), getAsString(), getFilename(), clang::driver::tools::getStatsFileName(), renderDebugOptions(), and renderRemarksOptions().
isInputArg()
bool clang::driver::InputInfo::isInputArg () const inline
Definition at line 76 of file InputInfo.h.
References InputArg.
Referenced by getAsString(), and getInputArg().
isNothing()
bool clang::driver::InputInfo::isNothing () const inline
Definition at line 74 of file InputInfo.h.
Referenced by clang::driver::tools::aix::Assembler::ConstructJob(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::NVPTX::Linker::ConstructJob(), clang::driver::tools::NVPTX::OpenMPLinker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gcc::Common::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::XCore::Linker::ConstructJob(), clang::driver::tools::zos::Assembler::ConstructJob(), and clang::driver::tools::zos::Linker::ConstructJob().
setAction()
void clang::driver::InputInfo::setAction (const Action * A) inline
Definition at line 81 of file InputInfo.h.
Member Data Documentation
Filename
const char* clang::driver::InputInfo::Filename
Definition at line 37 of file InputInfo.h.
Referenced by isFilename().
InputArg
const llvm::opt::Arg* clang::driver::InputInfo::InputArg
Definition at line 38 of file InputInfo.h.
Referenced by isInputArg().
The documentation for this class was generated from the following file:
include/clang/Driver/InputInfo.h