clang: clang::ento::SymExpr Class Reference
clang::ento::SymExpr Class Reference abstract
Symbolic value.
#include "clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h"
Classes
class symbol_iterator
Iterator over symbols that the current symbol depends on.
Public Types
enum Kind
Public Member Functions
virtual ~SymExpr ()=default
Kind getKind () const
virtual void dump () const
virtual void dumpToStream (raw_ostream &os) const
virtual QualType getType () const =0
virtual void Profile (llvm::FoldingSetNodeID &profile)=0
llvm::iterator_range< symbol_iterator > symbols () const
virtual unsigned computeComplexity () const =0
virtual const MemRegion * getOriginRegion () const
Find the region from which this symbol originates.
Protected Member Functions
SymExpr (Kind k)
Static Protected Member Functions
static bool isValidTypeForSymbol (QualType T)
Protected Attributes
unsigned Complexity = 0
Detailed Description
Symbolic value.
These values used to capture symbolic execution of the program.
Definition at line 30 of file SymExpr.h.
Member Enumeration Documentation
Kind
enum clang::ento::SymExpr::Kind
Definition at line 34 of file SymExpr.h.
Constructor & Destructor Documentation
SymExpr()
clang::ento::SymExpr::SymExpr (Kind k) inline protected
Definition at line 44 of file SymExpr.h.
~SymExpr()
virtual clang::ento::SymExpr::~SymExpr () virtual default
Member Function Documentation
computeComplexity()
virtual unsigned clang::ento::SymExpr::computeComplexity () const pure virtual
Implemented in clang::ento::SymbolData, clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >, clang::ento::UnarySymExpr, and clang::ento::SymbolCast.
Referenced by clang::ento::SValBuilder::makeSymExprValNN().
dump()
LLVM_DUMP_METHOD void SymExpr::dump () const virtual
Definition at line 44 of file SymbolManager.cpp.
References dumpToStream().
dumpToStream()
virtual void clang::ento::SymExpr::dumpToStream (raw_ostream & os) const inline virtual
Reimplemented in clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >, clang::ento::UnarySymExpr, clang::ento::SymbolCast, clang::ento::SymbolMetadata, clang::ento::SymbolExtent, clang::ento::SymbolDerived, clang::ento::SymbolConjured, and clang::ento::SymbolRegionValue.
Definition at line 61 of file SymExpr.h.
Referenced by dump(), clang::ento::SymbolCast::dumpToStream(), clang::ento::UnarySymExpr::dumpToStream(), clang::ento::BinarySymExpr::dumpToStreamImpl(), and clang::ento::operator<<().
getKind()
Kind clang::ento::SymExpr::getKind () const inline
Definition at line 57 of file SymExpr.h.
Referenced by clang::ento::SymbolRegionValue::classof(), clang::ento::SymbolConjured::classof(), clang::ento::SymbolDerived::classof(), clang::ento::SymbolExtent::classof(), clang::ento::SymbolMetadata::classof(), clang::ento::SymbolCast::classof(), clang::ento::UnarySymExpr::classof(), clang::ento::BinarySymExpr::classof(), clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::classof(), and clang::ento::SymbolData::classof().
getOriginRegion()
virtual const MemRegion* clang::ento::SymExpr::getOriginRegion () const inline virtual
Find the region from which this symbol originates.
Whenever the symbol was constructed to denote an unknown value of a certain memory region, return this region. This method allows checkers to make decisions depending on the origin of the symbol. Symbol classes for which the origin region is known include SymbolRegionValue which denotes the value of the region before the beginning of the analysis, and SymbolDerived which denotes the value of a certain memory region after its super region (a memory space or a larger record region) is default-bound with a certain symbol. It might return null.
Reimplemented in clang::ento::SymbolDerived, and clang::ento::SymbolRegionValue.
Definition at line 104 of file SymExpr.h.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), getOriginParam(), and unwrapRValueReferenceIndirection().
getType()
virtual QualType clang::ento::SymExpr::getType () const pure virtual
Implemented in clang::ento::BinarySymExpr, clang::ento::UnarySymExpr, clang::ento::SymbolCast, clang::ento::SymbolMetadata, clang::ento::SymbolExtent, clang::ento::SymbolDerived, clang::ento::SymbolConjured, and clang::ento::SymbolRegionValue.
Referenced by clang::ento::iterator::assumeNoOverflow(), clang::ento::RangedConstraintManager::assumeSymInclusiveRange(), clang::ento::RangedConstraintManager::assumeSymRel(), clang::ento::RangedConstraintManager::assumeSymUnsupported(), clang::ento::SMTConstraintManager::canReasonAbout(), clang::ento::ConstraintManager::checkNull(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), decomposeSymbol(), doRearrangeUnchecked(), clang::ento::retaincountchecker::RetainCountChecker::errorKindToBugKind(), clang::ento::SMTConv::fromData(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), clang::ento::SymbolicRegion::getPointeeStaticType(), clang::ento::SMTConv::getSymExpr(), clang::ento::SMTConstraintManager::getSymVal(), clang::ento::SymbolManager::getType(), isWithinConstantOverflowBounds(), clang::ento::SValBuilder::makeSymbolVal(), shouldRearrange(), clang::ento::nonloc::SymbolVal::SymbolVal(), tryRearrange(), unwrapRValueReferenceIndirection(), and clang::ento::SValExplainer::VisitSymbolicRegion().
isValidTypeForSymbol()
static bool clang::ento::SymExpr::isValidTypeForSymbol (QualType T) inline static protected
Definition at line 46 of file SymExpr.h.
References clang::Type::isVoidType(), and clang::T.
Referenced by clang::ento::BinarySymExpr::BinarySymExpr(), clang::ento::SymbolCast::SymbolCast(), clang::ento::SymbolConjured::SymbolConjured(), clang::ento::SymbolDerived::SymbolDerived(), clang::ento::SymbolMetadata::SymbolMetadata(), clang::ento::SymbolRegionValue::SymbolRegionValue(), and clang::ento::UnarySymExpr::UnarySymExpr().
Profile()
virtual void clang::ento::SymExpr::Profile (llvm::FoldingSetNodeID & profile) pure virtual
Implemented in clang::ento::SymbolMetadata, clang::ento::SymbolExtent, clang::ento::SymbolDerived, clang::ento::SymbolConjured, clang::ento::SymbolRegionValue, clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >, clang::ento::UnarySymExpr, and clang::ento::SymbolCast.
symbols()
llvm::iterator_range<symbol_iterator> clang::ento::SymExpr::symbols () const inline
Definition at line 87 of file SymExpr.h.
Referenced by clang::ento::taint::getTaintedSymbolsImpl(), and clang::ento::ScanReachableSymbols::scan().
Member Data Documentation
Complexity
unsigned clang::ento::SymExpr::Complexity = 0 mutable protected
Definition at line 52 of file SymExpr.h.
Referenced by clang::ento::SymbolCast::computeComplexity(), clang::ento::UnarySymExpr::computeComplexity(), and clang::ento::BinarySymExprImpl< LHSTYPE, RHSTYPE, ClassKind >::computeComplexity().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h
lib/StaticAnalyzer/Core/SymbolManager.cpp