clang: clang::serialization::TypeIdx Class Reference
clang::serialization::TypeIdx Class Reference
A type index; the type ID with the qualifier bits removed.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
TypeIdx ()=default
TypeIdx (uint32_t ModuleFileIdx, uint32_t Idx)
uint32_t getModuleFileIndex () const
uint64_t getValue () const
TypeID asTypeID (unsigned FastQuals) const
Static Public Member Functions
static TypeIdx fromTypeID (TypeID ID)
Detailed Description
A type index; the type ID with the qualifier bits removed.
Keep structure alignment 32-bit since the blob is assumed as 32-bit aligned.
Definition at line 99 of file ASTBitCodes.h.
Constructor & Destructor Documentation
TypeIdx() [1/2]
clang::serialization::TypeIdx::TypeIdx () default
Referenced by fromTypeID().
TypeIdx() [2/2]
clang::serialization::TypeIdx::TypeIdx (uint32_t ModuleFileIdx, uint32_t Idx) inline explicit
Definition at line 106 of file ASTBitCodes.h.
Member Function Documentation
asTypeID()
TypeID clang::serialization::TypeIdx::asTypeID (unsigned FastQuals) const inline
Definition at line 113 of file ASTBitCodes.h.
Referenced by MakeTypeID().
fromTypeID()
static TypeIdx clang::serialization::TypeIdx::fromTypeID (TypeID ID) inline static
Definition at line 121 of file ASTBitCodes.h.
References clang::Qualifiers::FastWidth, ID, and TypeIdx().
getModuleFileIndex()
uint32_t clang::serialization::TypeIdx::getModuleFileIndex () const inline
Definition at line 109 of file ASTBitCodes.h.
getValue()
uint64_t clang::serialization::TypeIdx::getValue () const inline
Definition at line 111 of file ASTBitCodes.h.
Referenced by clang::ASTWriter::GetOrCreateTypeID().
The documentation for this class was generated from the following file:
include/clang/Serialization/ASTBitCodes.h