clang: clang::installapi::HeaderFile Class Reference
clang::installapi::HeaderFile Class Reference
#include "clang/InstallAPI/HeaderFile.h"
Public Member Functions
HeaderFile ()=delete
HeaderFile (StringRef FullPath, HeaderType Type, StringRef IncludeName=StringRef(), std::optional< clang::Language > Language=std::nullopt)
HeaderType getType () const
StringRef getIncludeName () const
StringRef getPath () const
void setExtra (bool V=true)
void setExcluded (bool V=true)
void setUmbrellaHeader (bool V=true)
bool isExtra () const
bool isExcluded () const
bool isUmbrellaHeader () const
bool useIncludeName () const
bool operator== (const HeaderFile &Other) const
Static Public Member Functions
static llvm::Regex getFrameworkIncludeRule ()
Detailed Description
Definition at line 52 of file HeaderFile.h.
Constructor & Destructor Documentation
HeaderFile() [1/2]
clang::installapi::HeaderFile::HeaderFile () delete
HeaderFile() [2/2]
clang::installapi::HeaderFile::HeaderFile (StringRef FullPath, HeaderType Type, StringRef IncludeName = StringRef(), std::optional< clang::Language > Language = std::nullopt) inline
Definition at line 70 of file HeaderFile.h.
Member Function Documentation
getFrameworkIncludeRule()
llvm::Regex clang::installapi::HeaderFile::getFrameworkIncludeRule () static
Definition at line 15 of file HeaderFile.cpp.
getIncludeName()
StringRef clang::installapi::HeaderFile::getIncludeName () const inline
Definition at line 79 of file HeaderFile.h.
Referenced by clang::installapi::InstallAPIContext::addKnownHeader(), and clang::installapi::createInputBuffer().
getPath()
StringRef clang::installapi::HeaderFile::getPath () const inline
Definition at line 80 of file HeaderFile.h.
Referenced by clang::installapi::InstallAPIContext::addKnownHeader(), clang::installapi::createInputBuffer(), and clang::installapi::HeaderGlob::match().
getType()
HeaderType clang::installapi::HeaderFile::getType () const inline
Definition at line 78 of file HeaderFile.h.
Referenced by clang::installapi::InstallAPIContext::addKnownHeader(), clang::installapi::createInputBuffer(), and clang::installapi::HeaderGlob::match().
isExcluded()
bool clang::installapi::HeaderFile::isExcluded () const inline
Definition at line 86 of file HeaderFile.h.
Referenced by clang::installapi::createInputBuffer().
isExtra()
bool clang::installapi::HeaderFile::isExtra () const inline
Definition at line 85 of file HeaderFile.h.
isUmbrellaHeader()
bool clang::installapi::HeaderFile::isUmbrellaHeader () const inline
Definition at line 87 of file HeaderFile.h.
operator==()
bool clang::installapi::HeaderFile::operator== (const HeaderFile & Other) const inline
Definition at line 93 of file HeaderFile.h.
References clang::Other.
setExcluded()
void clang::installapi::HeaderFile::setExcluded (bool V = true) inline
Definition at line 83 of file HeaderFile.h.
References V.
setExtra()
void clang::installapi::HeaderFile::setExtra (bool V = true) inline
Definition at line 82 of file HeaderFile.h.
References V.
setUmbrellaHeader()
void clang::installapi::HeaderFile::setUmbrellaHeader (bool V = true) inline
Definition at line 84 of file HeaderFile.h.
References V.
useIncludeName()
bool clang::installapi::HeaderFile::useIncludeName () const inline
Definition at line 89 of file HeaderFile.h.
References clang::installapi::Project.
Referenced by clang::installapi::InstallAPIContext::addKnownHeader(), and clang::installapi::createInputBuffer().
The documentation for this class was generated from the following files:
include/clang/InstallAPI/HeaderFile.h
lib/InstallAPI/HeaderFile.cpp