clang: clang::interp::FunctionPointer Class Reference
clang::interp::FunctionPointer Class Reference final
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/FunctionPointer.h"
Public Member Functions
FunctionPointer (const Function *Func)
FunctionPointer (uintptr_t IntVal=0, const Descriptor *Desc=nullptr)
const Function * getFunction () const
bool isZero () const
bool isValid () const
bool isWeak () const
APValue toAPValue () const
void print (llvm::raw_ostream &OS) const
std::string toDiagnosticString (const ASTContext &Ctx) const
uint64_t getIntegerRepresentation () const
ComparisonCategoryResult compare (const FunctionPointer &RHS) const
Detailed Description
Definition at line 20 of file FunctionPointer.h.
Constructor & Destructor Documentation
FunctionPointer() [1/2]
clang::interp::FunctionPointer::FunctionPointer (const Function * Func) inline
Definition at line 26 of file FunctionPointer.h.
References clang::Func.
FunctionPointer() [2/2]
clang::interp::FunctionPointer::FunctionPointer (uintptr_t IntVal = 0, const Descriptor * Desc = nullptr) inline
Definition at line 30 of file FunctionPointer.h.
References clang::Func.
Member Function Documentation
compare()
ComparisonCategoryResult clang::interp::FunctionPointer::compare (const FunctionPointer & RHS) const inline
Definition at line 79 of file FunctionPointer.h.
References clang::Equal, clang::Func, and clang::Unordered.
getFunction()
const Function* clang::interp::FunctionPointer::getFunction () const inline
Definition at line 33 of file FunctionPointer.h.
References clang::Func.
getIntegerRepresentation()
uint64_t clang::interp::FunctionPointer::getIntegerRepresentation () const inline
Definition at line 75 of file FunctionPointer.h.
References clang::Func.
Referenced by toAPValue().
isValid()
bool clang::interp::FunctionPointer::isValid () const inline
Definition at line 35 of file FunctionPointer.h.
isWeak()
bool clang::interp::FunctionPointer::isWeak () const inline
Definition at line 36 of file FunctionPointer.h.
References clang::Func.
isZero()
bool clang::interp::FunctionPointer::isZero () const inline
Definition at line 34 of file FunctionPointer.h.
References clang::Func.
print()
void clang::interp::FunctionPointer::print (llvm::raw_ostream & OS) const inline
Definition at line 57 of file FunctionPointer.h.
References clang::Func.
Referenced by clang::interp::operator<<().
toAPValue()
APValue clang::interp::FunctionPointer::toAPValue () const inline
Definition at line 43 of file FunctionPointer.h.
References clang::CharUnits::fromQuantity(), clang::Func, getIntegerRepresentation(), and clang::CharUnits::Zero().
Referenced by toDiagnosticString().
toDiagnosticString()
std::string clang::interp::FunctionPointer::toDiagnosticString (const ASTContext & Ctx) const inline
Definition at line 68 of file FunctionPointer.h.
References clang::Func, clang::APValue::getAsString(), and toAPValue().
The documentation for this class was generated from the following file:
lib/AST/Interp/FunctionPointer.h