clang: clang::interp::ByteCodeEmitter Class Reference
clang::interp::ByteCodeEmitter Class Reference abstract
An emitter which links the program to bytecode for later use.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/ByteCodeEmitter.h"
Public Member Functions
Function * compileFunc (const FunctionDecl *FuncDecl)
Compiles the function into the module.
Protected Types
using LabelTy = uint32_t
using AddrTy = uintptr_t
using Local = Scope::Local
Protected Member Functions
ByteCodeEmitter (Context &Ctx, Program &P)
virtual ~ByteCodeEmitter ()
void emitLabel (LabelTy Label)
Define a label.
LabelTy getLabel ()
Create a label.
virtual bool visitFunc (const FunctionDecl *E)=0
Methods implemented by the compiler.
virtual bool visitExpr (const Expr *E)=0
virtual bool visitDecl (const VarDecl *E)=0
bool jumpTrue (const LabelTy &Label)
Emits jumps.
bool jumpFalse (const LabelTy &Label)
bool jump (const LabelTy &Label)
bool fallthrough (const LabelTy &Label)
Local createLocal (Descriptor *D)
Callback for local registration.
Protected Attributes
llvm::DenseMap< const ParmVarDecl *, ParamOffset > Params
Parameter indices.
llvm::DenseMap< const ValueDecl *, ParamOffset > LambdaCaptures
Lambda captures.
ParamOffset LambdaThisCapture {0, false}
Offset of the This parameter in a lambda record.
llvm::SmallVector< SmallVector< Local, 8 >, 2 > Descriptors
Local descriptors.
Detailed Description
An emitter which links the program to bytecode for later use.
Definition at line 26 of file ByteCodeEmitter.h.
Member Typedef Documentation
AddrTy
using clang::interp::ByteCodeEmitter::AddrTy = uintptr_t protected
Definition at line 29 of file ByteCodeEmitter.h.
LabelTy
using clang::interp::ByteCodeEmitter::LabelTy = uint32_t protected
Definition at line 28 of file ByteCodeEmitter.h.
Local
using clang::interp::ByteCodeEmitter::Local = Scope::Local protected
Definition at line 30 of file ByteCodeEmitter.h.
Constructor & Destructor Documentation
ByteCodeEmitter()
clang::interp::ByteCodeEmitter::ByteCodeEmitter (Context & Ctx, Program & P) inline protected
Definition at line 37 of file ByteCodeEmitter.h.
References P.
~ByteCodeEmitter()
virtual clang::interp::ByteCodeEmitter::~ByteCodeEmitter () inline protected virtual
Definition at line 39 of file ByteCodeEmitter.h.
Member Function Documentation
compileFunc()
Function * ByteCodeEmitter::compileFunc (const FunctionDecl * FuncDecl)
Compiles the function into the module.
Definition at line 33 of file ByteCodeEmitter.cpp.
References clang::interp::align(), clang::TemplateArgumentList::asArray(), clang::CXXRecordDecl::captures_begin(), clang::CXXRecordDecl::captures_end(), clang::interp::Context::classify(), clang::interp::Program::createDescriptor(), clang::interp::Program::createFunction(), clang::interp::Record::Field::Decl, clang::FunctionTemplateDecl::findSpecialization(), clang::Func, clang::FunctionDecl::getBuiltinID(), clang::FunctionDecl::getDescribedFunctionTemplate(), clang::interp::Record::getField(), clang::interp::Program::getFunction(), clang::CXXRecordDecl::getLambdaCallOperator(), clang::interp::Program::getOrCreateRecord(), clang::DeclContext::getParent(), clang::FieldDecl::getParent(), clang::FunctionDecl::getReturnType(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::FunctionDecl::isConstexpr(), clang::FunctionDecl::isDefined(), clang::CXXRecordDecl::isGenericLambda(), clang::isLambdaCallOperator(), clang::Type::isPointerType(), clang::Type::isReferenceType(), isUnevaluatedBuiltin(), clang::Type::isVoidType(), LambdaCaptures, LambdaThisCapture, clang::interp::Record::Field::Offset, Offset, clang::FunctionDecl::parameters(), Params, clang::interp::primSize(), clang::interp::PT_Ptr, clang::T, and visitFunc().
createLocal()
Scope::Local ByteCodeEmitter::createLocal (Descriptor * D) protected
Callback for local registration.
Definition at line 182 of file ByteCodeEmitter.cpp.
References clang::interp::align(), and clang::interp::Descriptor::getAllocSize().
emitLabel()
void ByteCodeEmitter::emitLabel (LabelTy Label) protected
Define a label.
Definition at line 189 of file ByteCodeEmitter.cpp.
References clang::interp::align(), clang::interp::aligned(), Label, and Offset.
Referenced by fallthrough().
fallthrough()
bool ByteCodeEmitter::fallthrough (const LabelTy & Label) protected
Definition at line 320 of file ByteCodeEmitter.cpp.
References emitLabel(), and Label.
getLabel()
LabelTy clang::interp::ByteCodeEmitter::getLabel () inline protected
Create a label.
Definition at line 44 of file ByteCodeEmitter.h.
jump()
bool ByteCodeEmitter::jump (const LabelTy & Label) protected
Definition at line 316 of file ByteCodeEmitter.cpp.
References Label.
jumpFalse()
bool ByteCodeEmitter::jumpFalse (const LabelTy & Label) protected
Definition at line 312 of file ByteCodeEmitter.cpp.
References Label.
jumpTrue()
bool ByteCodeEmitter::jumpTrue (const LabelTy & Label) protected
Emits jumps.
Definition at line 308 of file ByteCodeEmitter.cpp.
References Label.
visitDecl()
virtual bool clang::interp::ByteCodeEmitter::visitDecl (const VarDecl * E) protected pure virtual
visitExpr()
virtual bool clang::interp::ByteCodeEmitter::visitExpr (const Expr * E) protected pure virtual
visitFunc()
virtual bool clang::interp::ByteCodeEmitter::visitFunc (const FunctionDecl * E) protected pure virtual
Methods implemented by the compiler.
Referenced by compileFunc().
Member Data Documentation
Descriptors
llvm::SmallVector<SmallVector<Local, 8>, 2> clang::interp::ByteCodeEmitter::Descriptors protected
Local descriptors.
Definition at line 67 of file ByteCodeEmitter.h.
LambdaCaptures
llvm::DenseMap<const ValueDecl *, ParamOffset> clang::interp::ByteCodeEmitter::LambdaCaptures protected
Lambda captures.
Definition at line 63 of file ByteCodeEmitter.h.
Referenced by compileFunc().
LambdaThisCapture
ParamOffset clang::interp::ByteCodeEmitter::LambdaThisCapture {0, false} protected
Offset of the This parameter in a lambda record.
Definition at line 65 of file ByteCodeEmitter.h.
Referenced by compileFunc().
Params
llvm::DenseMap<const ParmVarDecl *, ParamOffset> clang::interp::ByteCodeEmitter::Params protected
Parameter indices.
Definition at line 61 of file ByteCodeEmitter.h.
Referenced by compileFunc().
The documentation for this class was generated from the following files:
lib/AST/Interp/ByteCodeEmitter.h
lib/AST/Interp/ByteCodeEmitter.cpp