clang: clang::ASTImporter::ImportPathTy Class Reference
clang::ASTImporter::ImportPathTy Class Reference
#include "clang/AST/ASTImporter.h"
Public Types
using VecTy = llvm::SmallVector< Decl *, 32 >
using Cycle = llvm::iterator_range< VecTy::const_reverse_iterator >
Public Member Functions
void push (Decl *D)
void pop ()
bool hasCycleAtBack () const
Returns true if the last element can be found earlier in the path.
Cycle getCycleAtBack () const
VecTy copyCycleAtBack () const
Returns the copy of the cycle.
Detailed Description
Definition at line 147 of file ASTImporter.h.
Member Typedef Documentation
Cycle
using clang::ASTImporter::ImportPathTy::Cycle = llvm::iterator_range<VecTy::const_reverse_iterator>
Definition at line 169 of file ASTImporter.h.
VecTy
using clang::ASTImporter::ImportPathTy::VecTy = llvm::SmallVector<Decl *, 32>
Definition at line 149 of file ASTImporter.h.
Member Function Documentation
copyCycleAtBack()
VecTy clang::ASTImporter::ImportPathTy::copyCycleAtBack () const inline
Returns the copy of the cycle.
Definition at line 178 of file ASTImporter.h.
References getCycleAtBack().
Referenced by clang::ASTImporter::Import().
getCycleAtBack()
Cycle clang::ASTImporter::ImportPathTy::getCycleAtBack () const inline
Definition at line 170 of file ASTImporter.h.
Referenced by copyCycleAtBack().
hasCycleAtBack()
bool clang::ASTImporter::ImportPathTy::hasCycleAtBack () const inline
Returns true if the last element can be found earlier in the path.
Definition at line 164 of file ASTImporter.h.
Referenced by clang::ASTImporter::Import().
pop()
void clang::ASTImporter::ImportPathTy::pop () inline
Definition at line 156 of file ASTImporter.h.
Referenced by clang::ASTImporter::Import().
push()
void clang::ASTImporter::ImportPathTy::push (Decl * D) inline
Definition at line 151 of file ASTImporter.h.
Referenced by clang::ASTImporter::Import().
The documentation for this class was generated from the following file:
include/clang/AST/ASTImporter.h