clang: clang::ParsingFieldDeclarator Class Reference
clang::ParsingFieldDeclarator Class Reference
A class for parsing a field declarator.
#include "clang/Parse/RAIIObjectsForParser.h"
Public Member Functions
ParsingFieldDeclarator (Parser &P, const ParsingDeclSpec &DS, const ParsedAttributes &DeclarationAttrs)
const ParsingDeclSpec & getDeclSpec () const
ParsingDeclSpec & getMutableDeclSpec () const
void complete (Decl *D)
Public Member Functions inherited from clang::FieldDeclarator
FieldDeclarator (const DeclSpec &DS, const ParsedAttributes &DeclarationAttrs)
Additional Inherited Members
Public Attributes inherited from clang::FieldDeclarator
Declarator D
Expr * BitfieldSize
Detailed Description
A class for parsing a field declarator.
Definition at line 229 of file RAIIObjectsForParser.h.
Constructor & Destructor Documentation
ParsingFieldDeclarator()
clang::ParsingFieldDeclarator::ParsingFieldDeclarator (Parser & P, const ParsingDeclSpec & DS, const ParsedAttributes & DeclarationAttrs) inline
Definition at line 233 of file RAIIObjectsForParser.h.
Member Function Documentation
complete()
void clang::ParsingFieldDeclarator::complete (Decl * D) inline
Definition at line 246 of file RAIIObjectsForParser.h.
References clang::ParsingDeclRAIIObject::complete(), and clang::FieldDeclarator::D.
getDeclSpec()
const ParsingDeclSpec& clang::ParsingFieldDeclarator::getDeclSpec () const inline
Definition at line 238 of file RAIIObjectsForParser.h.
References clang::FieldDeclarator::D, and clang::Declarator::getDeclSpec().
Referenced by getMutableDeclSpec().
getMutableDeclSpec()
ParsingDeclSpec& clang::ParsingFieldDeclarator::getMutableDeclSpec () const inline
Definition at line 242 of file RAIIObjectsForParser.h.
References getDeclSpec().
The documentation for this class was generated from the following file:
include/clang/Parse/RAIIObjectsForParser.h