clang: clang::ento::retaincountchecker::RefVal Class Reference
clang::ento::retaincountchecker::RefVal Class Reference
Metadata on reference.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h"
Public Types
enum Kind {
Owned = 0, NotOwned, Released, ReturnedOwned,
ReturnedNotOwned, ERROR_START, ErrorDeallocNotOwned, ErrorUseAfterRelease,
ErrorReleaseNotOwned, ERROR_LEAK_START, ErrorLeak, ErrorLeakReturned,
ErrorOverAutorelease, ErrorReturnedNotOwned
}
enum IvarAccessHistory { IvarAccessHistory::None, IvarAccessHistory::AccessedDirectly, IvarAccessHistory::ReleasedAfterDirectAccess }
Tracks how an object referenced by an ivar has been used.
Public Member Functions
Kind getKind () const
ObjKind getObjKind () const
unsigned getCount () const
unsigned getAutoreleaseCount () const
unsigned getCombinedCounts () const
void clearCounts ()
void setCount (unsigned i)
void setAutoreleaseCount (unsigned i)
QualType getType () const
IvarAccessHistory getIvarAccessHistory () const
Returns what the analyzer knows about direct accesses to a particular instance variable.
bool isOwned () const
bool isNotOwned () const
bool isReturnedOwned () const
bool isReturnedNotOwned () const
RefVal operator- (size_t i) const
RefVal operator+ (size_t i) const
RefVal operator^ (Kind k) const
RefVal autorelease () const
RefVal withIvarAccess () const
RefVal releaseViaIvar () const
bool hasSameState (const RefVal &X) const
bool operator== (const RefVal &X) const
void Profile (llvm::FoldingSetNodeID &ID) const
void print (raw_ostream &Out) const
Static Public Member Functions
static RefVal makeOwned (ObjKind o, QualType t)
Create a state for an object whose lifetime is the responsibility of the current function, at least partially.
static RefVal makeNotOwned (ObjKind o, QualType t)
Create a state for an object whose lifetime is not the responsibility of the current function.
Detailed Description
Metadata on reference.
Definition at line 51 of file RetainCountChecker.h.
Member Enumeration Documentation
IvarAccessHistory
enum clang::ento::retaincountchecker::RefVal::IvarAccessHistory strong
Tracks how an object referenced by an ivar has been used.
This accounts for us not knowing if an arbitrary ivar is supposed to be stored at +0 or +1.
Enumerator
None
AccessedDirectly
ReleasedAfterDirectAccess
Definition at line 75 of file RetainCountChecker.h.
Kind
enum clang::ento::retaincountchecker::RefVal::Kind
Enumerator
Owned
NotOwned
Released
ReturnedOwned
ReturnedNotOwned
ERROR_START
ErrorDeallocNotOwned
ErrorUseAfterRelease
ErrorReleaseNotOwned
ERROR_LEAK_START
ErrorLeak
ErrorLeakReturned
ErrorOverAutorelease
ErrorReturnedNotOwned
Definition at line 53 of file RetainCountChecker.h.
Member Function Documentation
autorelease()
RefVal clang::ento::retaincountchecker::RefVal::autorelease () const inline
Definition at line 199 of file RetainCountChecker.h.
References getAutoreleaseCount(), getCount(), getIvarAccessHistory(), getKind(), getObjKind(), and getType().
clearCounts()
void clang::ento::retaincountchecker::RefVal::clearCounts () inline
Definition at line 130 of file RetainCountChecker.h.
getAutoreleaseCount()
unsigned clang::ento::retaincountchecker::RefVal::getAutoreleaseCount () const inline
Definition at line 128 of file RetainCountChecker.h.
Referenced by autorelease(), operator+(), operator-(), operator^(), releaseViaIvar(), and withIvarAccess().
getCombinedCounts()
unsigned clang::ento::retaincountchecker::RefVal::getCombinedCounts () const inline
Definition at line 129 of file RetainCountChecker.h.
getCount()
unsigned clang::ento::retaincountchecker::RefVal::getCount () const inline
Definition at line 127 of file RetainCountChecker.h.
Referenced by autorelease(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), operator+(), operator-(), operator^(), print(), releaseViaIvar(), and withIvarAccess().
getIvarAccessHistory()
IvarAccessHistory clang::ento::retaincountchecker::RefVal::getIvarAccessHistory () const inline
Returns what the analyzer knows about direct accesses to a particular instance variable.
If the object with this refcount wasn't originally from an Objective-C ivar region, this should always return IvarAccessHistory::None.
Definition at line 148 of file RetainCountChecker.h.
Referenced by autorelease(), hasSameState(), operator+(), operator-(), operator^(), print(), releaseViaIvar(), and withIvarAccess().
getKind()
Kind clang::ento::retaincountchecker::RefVal::getKind () const inline
Definition at line 121 of file RetainCountChecker.h.
Referenced by autorelease(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), hasSameState(), isNotOwned(), isOwned(), isReturnedNotOwned(), isReturnedOwned(), operator+(), operator-(), print(), releaseViaIvar(), and withIvarAccess().
getObjKind()
ObjKind clang::ento::retaincountchecker::RefVal::getObjKind () const inline
Definition at line 123 of file RetainCountChecker.h.
Referenced by autorelease(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), operator+(), operator-(), operator==(), operator^(), releaseViaIvar(), and withIvarAccess().
getType()
QualType clang::ento::retaincountchecker::RefVal::getType () const inline
Definition at line 141 of file RetainCountChecker.h.
Referenced by autorelease(), operator+(), operator-(), operator^(), releaseViaIvar(), and withIvarAccess().
hasSameState()
bool clang::ento::retaincountchecker::RefVal::hasSameState (const RefVal & X) const inline
Definition at line 217 of file RetainCountChecker.h.
References getIvarAccessHistory(), getKind(), and clang::tooling::X().
Referenced by operator==().
isNotOwned()
bool clang::ento::retaincountchecker::RefVal::isNotOwned () const inline
Definition at line 156 of file RetainCountChecker.h.
References getKind(), and NotOwned.
Referenced by clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
isOwned()
bool clang::ento::retaincountchecker::RefVal::isOwned () const inline
Definition at line 152 of file RetainCountChecker.h.
References getKind(), and Owned.
Referenced by clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
isReturnedNotOwned()
bool clang::ento::retaincountchecker::RefVal::isReturnedNotOwned () const inline
Definition at line 164 of file RetainCountChecker.h.
References getKind(), and ReturnedNotOwned.
isReturnedOwned()
bool clang::ento::retaincountchecker::RefVal::isReturnedOwned () const inline
Definition at line 160 of file RetainCountChecker.h.
References getKind(), and ReturnedOwned.
makeNotOwned()
static RefVal clang::ento::retaincountchecker::RefVal::makeNotOwned (ObjKind o, QualType t) inline static
Create a state for an object whose lifetime is not the responsibility of the current function.
Most commonly, this is an unowned object with a retain count of +0.
Definition at line 180 of file RetainCountChecker.h.
References None, and NotOwned.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::ento::retaincountchecker::RetainCountChecker::processObjCLiterals(), refValFromRetEffect(), and updateOutParameters().
makeOwned()
static RefVal clang::ento::retaincountchecker::RefVal::makeOwned (ObjKind o, QualType t) inline static
Create a state for an object whose lifetime is the responsibility of the current function, at least partially.
Most commonly, this is an owned object with a retain count of +1.
Definition at line 172 of file RetainCountChecker.h.
References None, and Owned.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkBeginFunction(), refValFromRetEffect(), and updateOutParameters().
operator+()
RefVal clang::ento::retaincountchecker::RefVal::operator+ (size_t i) const inline
Definition at line 189 of file RetainCountChecker.h.
References getAutoreleaseCount(), getCount(), getIvarAccessHistory(), getKind(), getObjKind(), and getType().
operator-()
RefVal clang::ento::retaincountchecker::RefVal::operator- (size_t i) const inline
Definition at line 184 of file RetainCountChecker.h.
References getAutoreleaseCount(), getCount(), getIvarAccessHistory(), getKind(), getObjKind(), and getType().
operator==()
bool clang::ento::retaincountchecker::RefVal::operator== (const RefVal & X) const inline
Definition at line 222 of file RetainCountChecker.h.
References getObjKind(), hasSameState(), and clang::tooling::X().
operator^()
RefVal clang::ento::retaincountchecker::RefVal::operator^ (Kind k) const inline
Definition at line 194 of file RetainCountChecker.h.
References getAutoreleaseCount(), getCount(), getIvarAccessHistory(), getObjKind(), and getType().
print()
void RefVal::print (raw_ostream & Out) const
Definition at line 46 of file RetainCountChecker.cpp.
References AccessedDirectly, ErrorDeallocNotOwned, ErrorLeak, ErrorLeakReturned, ErrorOverAutorelease, ErrorReleaseNotOwned, ErrorReturnedNotOwned, ErrorUseAfterRelease, clang::QualType::getAsString(), getCount(), getIvarAccessHistory(), getKind(), clang::QualType::isNull(), None, NotOwned, Owned, Released, ReleasedAfterDirectAccess, ReturnedNotOwned, and ReturnedOwned.
Profile()
void clang::ento::retaincountchecker::RefVal::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 226 of file RetainCountChecker.h.
releaseViaIvar()
RefVal clang::ento::retaincountchecker::RefVal::releaseViaIvar () const inline
Definition at line 210 of file RetainCountChecker.h.
References AccessedDirectly, getAutoreleaseCount(), getCount(), getIvarAccessHistory(), getKind(), getObjKind(), getType(), and ReleasedAfterDirectAccess.
setAutoreleaseCount()
void clang::ento::retaincountchecker::RefVal::setAutoreleaseCount (unsigned i) inline
Definition at line 137 of file RetainCountChecker.h.
setCount()
void clang::ento::retaincountchecker::RefVal::setCount (unsigned i) inline
Definition at line 134 of file RetainCountChecker.h.
withIvarAccess()
RefVal clang::ento::retaincountchecker::RefVal::withIvarAccess () const inline
Definition at line 204 of file RetainCountChecker.h.
References AccessedDirectly, getAutoreleaseCount(), getCount(), getIvarAccessHistory(), getKind(), getObjKind(), getType(), and None.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt().
The documentation for this class was generated from the following files:
lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h
lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.cpp