clang: clang::format::ScopedMacroState Class Reference
clang::format::ScopedMacroState Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Format/FormatTokenSource.h"
Public Member Functions
ScopedMacroState (UnwrappedLine &Line, FormatTokenSource *&TokenSource, FormatToken *&ResetToken)
~ScopedMacroState () override
FormatToken * getNextToken () override
FormatToken * getPreviousToken () override
FormatToken * peekNextToken (bool SkipComment) override
bool isEOF () override
unsigned getPosition () override
FormatToken * setPosition (unsigned Position) override
FormatToken * insertTokens (ArrayRef< FormatToken * > Tokens) override
Public Member Functions inherited from clang::format::FormatTokenSource
virtual ~FormatTokenSource ()
FormatToken * getNextNonComment ()
Detailed Description
Definition at line 191 of file FormatTokenSource.h.
Constructor & Destructor Documentation
ScopedMacroState()
clang::format::ScopedMacroState::ScopedMacroState (UnwrappedLine & Line, FormatTokenSource *& TokenSource, FormatToken *& ResetToken) inline
Definition at line 193 of file FormatTokenSource.h.
References clang::comments::tok::eof, clang::Token::setKind(), clang::Token::startToken(), and clang::format::FormatToken::Tok.
~ScopedMacroState()
clang::format::ScopedMacroState::~ScopedMacroState () inline override
Definition at line 206 of file FormatTokenSource.h.
References clang::format::UnwrappedLine::InMacroBody, clang::format::UnwrappedLine::InPPDirective, and clang::format::UnwrappedLine::Level.
Member Function Documentation
getNextToken()
FormatToken* clang::format::ScopedMacroState::getNextToken () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 214 of file FormatTokenSource.h.
References clang::format::FormatTokenSource::getNextToken().
getPosition()
unsigned clang::format::ScopedMacroState::getPosition () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 237 of file FormatTokenSource.h.
References clang::format::FormatTokenSource::getPosition().
getPreviousToken()
FormatToken* clang::format::ScopedMacroState::getPreviousToken () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 225 of file FormatTokenSource.h.
References clang::format::FormatTokenSource::getPreviousToken().
insertTokens()
FormatToken* clang::format::ScopedMacroState::insertTokens (ArrayRef< FormatToken * > Tokens) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 245 of file FormatTokenSource.h.
isEOF()
bool clang::format::ScopedMacroState::isEOF () inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 235 of file FormatTokenSource.h.
References clang::format::FormatTokenSource::isEOF().
peekNextToken()
FormatToken* clang::format::ScopedMacroState::peekNextToken (bool SkipComment) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 229 of file FormatTokenSource.h.
References clang::format::FormatTokenSource::peekNextToken().
setPosition()
FormatToken* clang::format::ScopedMacroState::setPosition (unsigned Position) inline override virtual
Implements clang::format::FormatTokenSource.
Definition at line 239 of file FormatTokenSource.h.
References clang::format::FormatTokenSource::setPosition().
The documentation for this class was generated from the following file:
lib/Format/FormatTokenSource.h