clang: clang::ento::SymbolicRegion Class Reference
clang::ento::SymbolicRegion Class Reference
SymbolicRegion - A special, "non-concrete" region.
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
SymbolRef getSymbol () const
It might return null.
QualType getPointeeStaticType () const
Gets the type of the wrapped symbol.
bool isBoundable () const override
void Profile (llvm::FoldingSetNodeID &ID) const override
void dumpToStream (raw_ostream &os) const override
Public Member Functions inherited from clang::ento::SubRegion
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getSuperRegion () const
MemRegionManager & getMemRegionManager () const override
bool isSubRegionOf (const MemRegion *R) const override
Check if the region is a subregion of the given region.
Public Member Functions inherited from clang::ento::MemRegion
ASTContext & getContext () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemSpaceRegion * getMemorySpace () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getBaseRegion () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
virtual bool canPrintPrettyAsExpr () const
Returns true if this region's textual representation can be used as part of a larger expression.
virtual void printPrettyAsExpr (raw_ostream &os) const
Print the region as expression.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
LLVM_ATTRIBUTE_RETURNS_NONNULL const RegionTy * castAs () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Static Public Member Functions
static void ProfileRegion (llvm::FoldingSetNodeID &ID, SymbolRef sym, const MemRegion *superRegion)
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::SubRegion
static bool classof (const MemRegion *R)
Friends
class MemRegionManager
Additional Inherited Members
Public Types inherited from clang::ento::MemRegion
enum Kind
Protected Member Functions inherited from clang::ento::SubRegion
SubRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::MemRegion
MemRegion (Kind k)
virtual ~MemRegion ()
Protected Attributes inherited from clang::ento::SubRegion
const MemRegion * superRegion
Detailed Description
SymbolicRegion - A special, "non-concrete" region.
Unlike other region classes, SymbolicRegion represents a region that serves as an alias for either a real region, a NULL pointer, etc. It essentially is used to map the concept of symbolic values into the domain of regions. Symbolic regions do not need to be typed.
Definition at line 775 of file MemRegion.h.
Member Function Documentation
classof()
static bool clang::ento::SymbolicRegion::classof (const MemRegion * R) inline static
Definition at line 818 of file MemRegion.h.
References clang::ento::MemRegion::getKind().
dumpToStream()
void SymbolicRegion::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::MemRegion.
Definition at line 556 of file MemRegion.cpp.
References clang::ento::SubRegion::getSuperRegion().
getPointeeStaticType()
QualType clang::ento::SymbolicRegion::getPointeeStaticType () const inline
Gets the type of the wrapped symbol.
This type might not be accurate at all times - it's just our best guess. Consider these cases: void foo(void *data, char *str, base *obj) {...} The type of the pointee of data is of course not void, yet that's our best guess. str might point to any object and obj might point to some derived instance. TypedRegions other hand are representing the cases when we actually know their types.
Definition at line 804 of file MemRegion.h.
References clang::Type::getPointeeType(), and clang::ento::SymExpr::getType().
getSymbol()
SymbolRef clang::ento::SymbolicRegion::getSymbol () const inline
It might return null.
Definition at line 794 of file MemRegion.h.
Referenced by getOriginParam(), and clang::ento::SValExplainer::VisitSymbolicRegion().
isBoundable()
bool clang::ento::SymbolicRegion::isBoundable () const inline override virtual
Reimplemented from clang::ento::MemRegion.
Definition at line 808 of file MemRegion.h.
Profile()
void SymbolicRegion::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Implements clang::ento::MemRegion.
Definition at line 338 of file MemRegion.cpp.
References clang::ento::SubRegion::getSuperRegion(), ID, and ProfileRegion().
ProfileRegion()
void SymbolicRegion::ProfileRegion (llvm::FoldingSetNodeID & ID, SymbolRef sym, const MemRegion * superRegion) static
Definition at line 331 of file MemRegion.cpp.
References ID.
Referenced by Profile().
Friends And Related Function Documentation
MemRegionManager
friend class MemRegionManager friend
Definition at line 776 of file MemRegion.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp