clang: clang::ento::ConstraintManager::AssumeStackTy Class Reference
clang::ento::ConstraintManager::AssumeStackTy Class Reference
A helper class to simulate the call stack of nested assume calls.
#include "clang/StaticAnalyzer/Core/PathSensitive/ConstraintManager.h"
Public Member Functions
void push (const ProgramState *S)
void pop ()
bool contains (const ProgramState *S) const
Detailed Description
A helper class to simulate the call stack of nested assume calls.
Definition at line 149 of file ConstraintManager.h.
Member Function Documentation
contains()
bool clang::ento::ConstraintManager::AssumeStackTy::contains (const ProgramState * S) const inline
Definition at line 153 of file ConstraintManager.h.
Referenced by clang::ento::ConstraintManager::assumeDualImpl().
pop()
void clang::ento::ConstraintManager::AssumeStackTy::pop () inline
Definition at line 152 of file ConstraintManager.h.
Referenced by clang::ento::ConstraintManager::assumeDualImpl().
push()
void clang::ento::ConstraintManager::AssumeStackTy::push (const ProgramState * S) inline
Definition at line 151 of file ConstraintManager.h.
Referenced by clang::ento::ConstraintManager::assumeDualImpl().
The documentation for this class was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/ConstraintManager.h