clang: clang::CodeGen::CGBlockInfo::Capture Class Reference
clang::CodeGen::CGBlockInfo::Capture Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGBlocks.h"
Public Member Functions
bool isIndex () const
bool isConstant () const
unsigned getIndex () const
CharUnits getOffset () const
EHScopeStack::stable_iterator getCleanup () const
void setCleanup (EHScopeStack::stable_iterator cleanup)
llvm::Value * getConstant () const
QualType fieldType () const
bool isConstantOrTrivial () const
Static Public Member Functions
static Capture makeIndex (unsigned index, CharUnits offset, QualType FieldType, BlockCaptureEntityKind CopyKind, BlockFieldFlags CopyFlags, BlockCaptureEntityKind DisposeKind, BlockFieldFlags DisposeFlags, const BlockDecl::Capture *Cap)
static Capture makeConstant (llvm::Value *value, const BlockDecl::Capture *Cap)
Public Attributes
BlockCaptureEntityKind CopyKind = BlockCaptureEntityKind::None
BlockCaptureEntityKind DisposeKind = BlockCaptureEntityKind::None
BlockFieldFlags CopyFlags
BlockFieldFlags DisposeFlags
const BlockDecl::Capture * Cap
Detailed Description
Definition at line 164 of file CGBlocks.h.
Member Function Documentation
fieldType()
QualType clang::CodeGen::CGBlockInfo::Capture::fieldType () const inline
Definition at line 200 of file CGBlocks.h.
Referenced by clang::CodeGen::CodeGenFunction::GetAddrOfBlockDecl(), and getCaptureFieldType().
getCleanup()
EHScopeStack::stable_iterator clang::CodeGen::CGBlockInfo::Capture::getCleanup () const inline
Definition at line 186 of file CGBlocks.h.
References isIndex().
getConstant()
llvm::Value* clang::CodeGen::CGBlockInfo::Capture::getConstant () const inline
Definition at line 195 of file CGBlocks.h.
References isConstant().
Referenced by clang::CodeGen::CodeGenFunction::GenerateBlockFunction().
getIndex()
unsigned clang::CodeGen::CGBlockInfo::Capture::getIndex () const inline
Definition at line 178 of file CGBlocks.h.
References isIndex().
Referenced by clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), and clang::CodeGen::CodeGenFunction::GetAddrOfBlockDecl().
getOffset()
CharUnits clang::CodeGen::CGBlockInfo::Capture::getOffset () const inline
Definition at line 182 of file CGBlocks.h.
References clang::CharUnits::fromQuantity(), isIndex(), and Offset.
Referenced by getBlockCaptureStr().
isConstant()
bool clang::CodeGen::CGBlockInfo::Capture::isConstant () const inline
Definition at line 176 of file CGBlocks.h.
References isIndex().
Referenced by clang::CodeGen::CodeGenFunction::GenerateBlockFunction(), clang::CodeGen::CodeGenFunction::GetAddrOfBlockDecl(), and getConstant().
isConstantOrTrivial()
bool clang::CodeGen::CGBlockInfo::Capture::isConstantOrTrivial () const inline
Definition at line 229 of file CGBlocks.h.
References CopyKind, DisposeKind, and clang::CodeGen::None.
Referenced by clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), and clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction().
isIndex()
bool clang::CodeGen::CGBlockInfo::Capture::isIndex () const inline
Definition at line 175 of file CGBlocks.h.
Referenced by getCleanup(), getIndex(), getOffset(), isConstant(), and setCleanup().
makeConstant()
static Capture clang::CodeGen::CGBlockInfo::Capture::makeConstant (llvm::Value * value, const BlockDecl::Capture * Cap) inline static
Definition at line 221 of file CGBlocks.h.
References Cap, and v.
Referenced by computeBlockInfo().
makeIndex()
static Capture clang::CodeGen::CGBlockInfo::Capture::makeIndex (unsigned index, CharUnits offset, QualType FieldType, BlockCaptureEntityKind CopyKind, BlockFieldFlags CopyFlags, BlockCaptureEntityKind DisposeKind, BlockFieldFlags DisposeFlags, const BlockDecl::Capture * Cap) inline static
Definition at line 205 of file CGBlocks.h.
References Cap, CopyFlags, CopyKind, DisposeFlags, DisposeKind, clang::CharUnits::getQuantity(), and v.
setCleanup()
void clang::CodeGen::CGBlockInfo::Capture::setCleanup (EHScopeStack::stable_iterator cleanup) inline
Definition at line 190 of file CGBlocks.h.
References clang::format::cleanup(), and isIndex().
Member Data Documentation
Cap
const BlockDecl::Capture* clang::CodeGen::CGBlockInfo::Capture::Cap
Definition at line 237 of file CGBlocks.h.
Referenced by clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), getBlockCaptureStr(), makeConstant(), and makeIndex().
CopyFlags
BlockFieldFlags clang::CodeGen::CGBlockInfo::Capture::CopyFlags
Definition at line 236 of file CGBlocks.h.
Referenced by clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), getBlockCaptureStr(), and makeIndex().
CopyKind
BlockCaptureEntityKind clang::CodeGen::CGBlockInfo::Capture::CopyKind = BlockCaptureEntityKind::None
Definition at line 234 of file CGBlocks.h.
Referenced by clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), getBlockCaptureStr(), isConstantOrTrivial(), and makeIndex().
DisposeFlags
BlockFieldFlags clang::CodeGen::CGBlockInfo::Capture::DisposeFlags
Definition at line 236 of file CGBlocks.h.
Referenced by clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), getBlockCaptureStr(), and makeIndex().
DisposeKind
BlockCaptureEntityKind clang::CodeGen::CGBlockInfo::Capture::DisposeKind = BlockCaptureEntityKind::None
Definition at line 235 of file CGBlocks.h.
Referenced by clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), getBlockCaptureStr(), isConstantOrTrivial(), and makeIndex().
The documentation for this class was generated from the following file:
lib/CodeGen/CGBlocks.h