clang: clang::Designation Class Reference
clang::Designation Class Reference
Designation - Represent a full designation, which is a sequence of designators.
#include "clang/Sema/Designator.h"
Public Member Functions
void AddDesignator (Designator D)
AddDesignator - Add a designator to the end of this list.
bool empty () const
unsigned getNumDesignators () const
const Designator & getDesignator (unsigned Idx) const
Detailed Description
Designation - Represent a full designation, which is a sequence of designators.
This class is mostly a helper for InitListDesignations.
Definition at line 208 of file Designator.h.
Member Function Documentation
AddDesignator()
void clang::Designation::AddDesignator (Designator D) inline
AddDesignator - Add a designator to the end of this list.
Definition at line 214 of file Designator.h.
empty()
bool clang::Designation::empty () const inline
Definition at line 216 of file Designator.h.
getDesignator()
const Designator& clang::Designation::getDesignator (unsigned Idx) const inline
Definition at line 219 of file Designator.h.
Referenced by clang::Sema::ActOnDesignatedInitializer(), CheckArrayDesignatorSyntax(), and getDesignatedType().
getNumDesignators()
unsigned clang::Designation::getNumDesignators () const inline
Definition at line 218 of file Designator.h.
Referenced by clang::Sema::ActOnDesignatedInitializer(), CheckArrayDesignatorSyntax(), and getDesignatedType().
The documentation for this class was generated from the following file:
include/clang/Sema/Designator.h