clang: clang::ento::StackSpaceRegion Class Reference
clang::ento::StackSpaceRegion Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
LLVM_ATTRIBUTE_RETURNS_NONNULL const StackFrameContext * getStackFrame () const
void Profile (llvm::FoldingSetNodeID &ID) const override
Public Member Functions inherited from clang::ento::MemSpaceRegion
bool isBoundable () const override
Public Member Functions inherited from clang::ento::MemRegion
ASTContext & getContext () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemSpaceRegion * getMemorySpace () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getBaseRegion () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
virtual bool isSubRegionOf (const MemRegion *R) const
Check if the region is a subregion of the given region.
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
virtual void dumpToStream (raw_ostream &os) const
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
virtual bool canPrintPrettyAsExpr () const
Returns true if this region's textual representation can be used as part of a larger expression.
virtual void printPrettyAsExpr (raw_ostream &os) const
Print the region as expression.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
LLVM_ATTRIBUTE_RETURNS_NONNULL const RegionTy * castAs () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Static Public Member Functions
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::MemSpaceRegion
static bool classof (const MemRegion *R)
Protected Member Functions
StackSpaceRegion (MemRegionManager &mgr, Kind k, const StackFrameContext *sfc)
Protected Member Functions inherited from clang::ento::MemSpaceRegion
MemSpaceRegion (MemRegionManager &mgr, Kind k)
MemRegionManager & getMemRegionManager () const override
Protected Member Functions inherited from clang::ento::MemRegion
MemRegion (Kind k)
virtual ~MemRegion ()
Additional Inherited Members
Public Types inherited from clang::ento::MemRegion
enum Kind
Protected Attributes inherited from clang::ento::MemSpaceRegion
MemRegionManager & Mgr
Detailed Description
Definition at line 386 of file MemRegion.h.
Constructor & Destructor Documentation
StackSpaceRegion()
clang::ento::StackSpaceRegion::StackSpaceRegion (MemRegionManager & mgr, Kind k, const StackFrameContext * sfc) inline protected
Definition at line 392 of file MemRegion.h.
References classof().
Member Function Documentation
classof()
static bool clang::ento::StackSpaceRegion::classof (const MemRegion * R) inline static
Definition at line 404 of file MemRegion.h.
References clang::ento::MemRegion::getKind().
Referenced by StackSpaceRegion().
getStackFrame()
LLVM_ATTRIBUTE_RETURNS_NONNULL const StackFrameContext* clang::ento::StackSpaceRegion::getStackFrame () const inline
Definition at line 400 of file MemRegion.h.
Referenced by Profile().
Profile()
void StackSpaceRegion::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Reimplemented from clang::ento::MemSpaceRegion.
Definition at line 228 of file MemRegion.cpp.
References clang::ento::MemRegion::getKind(), getStackFrame(), and ID.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp