clang: clang::ento::SymbolData Class Reference
clang::ento::SymbolData Class Reference abstract
A symbol representing data which can be stored in a memory location (region).
#include "clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h"
Public Member Functions
~SymbolData () override=default
virtual StringRef getKindStr () const =0
Get a string representation of the kind of the region.
SymbolID getSymbolID () const
unsigned computeComplexity () const override
Public Member Functions inherited from clang::ento::SymExpr
virtual ~SymExpr ()=default
Kind getKind () const
virtual void dump () const
virtual void dumpToStream (raw_ostream &os) const
virtual QualType getType () const =0
virtual void Profile (llvm::FoldingSetNodeID &profile)=0
symbol_iterator symbol_begin () const
virtual const MemRegion * getOriginRegion () const
Find the region from which this symbol originates.
Static Public Member Functions
static bool classof (const SymExpr *SE)
Static Public Member Functions inherited from clang::ento::SymExpr
static symbol_iterator symbol_end ()
Protected Member Functions
SymbolData (Kind k, SymbolID sym)
Protected Member Functions inherited from clang::ento::SymExpr
SymExpr (Kind k)
Additional Inherited Members
Public Types inherited from clang::ento::SymExpr
enum Kind
Static Protected Member Functions inherited from clang::ento::SymExpr
static bool isValidTypeForSymbol (QualType T)
Protected Attributes inherited from clang::ento::SymExpr
unsigned Complexity = 0
Detailed Description
A symbol representing data which can be stored in a memory location (region).
Definition at line 116 of file SymExpr.h.
Constructor & Destructor Documentation
SymbolData()
clang::ento::SymbolData::SymbolData (Kind k, SymbolID sym) inline protected
Definition at line 122 of file SymExpr.h.
References classof().
~SymbolData()
clang::ento::SymbolData::~SymbolData () override default
Member Function Documentation
classof()
static bool clang::ento::SymbolData::classof (const SymExpr * SE) inline static
Definition at line 139 of file SymExpr.h.
References clang::ento::SymExpr::getKind().
Referenced by SymbolData().
computeComplexity()
unsigned clang::ento::SymbolData::computeComplexity () const inline override virtual
Implements clang::ento::SymExpr.
Definition at line 134 of file SymExpr.h.
getKindStr()
virtual StringRef clang::ento::SymbolData::getKindStr () const pure virtual
Get a string representation of the kind of the region.
Implemented in clang::ento::SymbolMetadata, clang::ento::SymbolExtent, clang::ento::SymbolDerived, clang::ento::SymbolConjured, and clang::ento::SymbolRegionValue.
Referenced by clang::ento::SMTConv::fromData().
getSymbolID()
SymbolID clang::ento::SymbolData::getSymbolID () const inline
Definition at line 132 of file SymExpr.h.
Referenced by clang::ento::SymbolRegionValue::dumpToStream(), clang::ento::SymbolConjured::dumpToStream(), clang::ento::SymbolDerived::dumpToStream(), clang::ento::SymbolExtent::dumpToStream(), clang::ento::SymbolMetadata::dumpToStream(), and clang::ento::SMTConv::fromData().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h
lib/StaticAnalyzer/Core/SymbolManager.cpp