clang: clang::DeclIDBase Class Reference
clang::DeclIDBase Class Reference
GlobalDeclID means DeclID in the current ASTContext and LocalDeclID means DeclID specific to a certain ModuleFile.
#include "clang/AST/DeclID.h"
Public Types
using DeclID = uint32_t
An ID number that refers to a declaration in an AST file.
Public Member Functions
DeclID get () const
operator DeclID () const
operator PredefinedDeclIDs () const
bool isValid () const
bool isInvalid () const
Protected Member Functions
DeclIDBase ()
DeclIDBase (DeclID ID)
Protected Attributes
DeclID ID
Friends
bool operator== (const DeclIDBase &LHS, const DeclIDBase &RHS)
bool operator!= (const DeclIDBase &LHS, const DeclIDBase &RHS)
bool operator< (const DeclIDBase &LHS, const DeclIDBase &RHS)
bool operator> (const DeclIDBase &LHS, const DeclIDBase &RHS)
bool operator<= (const DeclIDBase &LHS, const DeclIDBase &RHS)
bool operator>= (const DeclIDBase &LHS, const DeclIDBase &RHS)
Detailed Description
GlobalDeclID means DeclID in the current ASTContext and LocalDeclID means DeclID specific to a certain ModuleFile.
Specially, in ASTWriter, the LocalDeclID to the ModuleFile been writting is equal to the GlobalDeclID. Outside the serializer, all the DeclID been used should be GlobalDeclID. We can translate a LocalDeclID to the GlobalDeclID by ASTReader::getGlobalDeclID().
Definition at line 99 of file DeclID.h.
Member Typedef Documentation
DeclID
using clang::DeclIDBase::DeclID = uint32_t
An ID number that refers to a declaration in an AST file.
The ID numbers of declarations are consecutive (in order of discovery), with values below NUM_PREDEF_DECL_IDS being reserved. At the start of a chain of precompiled headers, declaration ID 1 is used for the translation unit declaration.
DeclID should only be used directly in serialization. All other users should use LocalDeclID or GlobalDeclID.
Definition at line 110 of file DeclID.h.
Constructor & Destructor Documentation
DeclIDBase() [1/2]
clang::DeclIDBase::DeclIDBase () inline protected
Definition at line 113 of file DeclID.h.
DeclIDBase() [2/2]
clang::DeclIDBase::DeclIDBase (DeclID ID) inline explicit protected
Definition at line 114 of file DeclID.h.
Member Function Documentation
get()
DeclID clang::DeclIDBase::get () const inline
Definition at line 117 of file DeclID.h.
References ID.
Referenced by clang::ASTReader::getGlobalDeclID(), llvm::DenseMapInfo< clang::GlobalDeclID >::getHashValue(), clang::ASTReader::mapGlobalIDToModuleFileGlobalID(), and clang::ASTDeclReader::VisitCXXRecordDeclImpl().
isInvalid()
bool clang::DeclIDBase::isInvalid () const inline
Definition at line 125 of file DeclID.h.
References ID, and clang::PREDEF_DECL_NULL_ID.
Referenced by clang::ASTDeclReader::VisitDecl(), and clang::ASTDeclReader::VisitRedeclarable().
isValid()
bool clang::DeclIDBase::isValid () const inline
Definition at line 123 of file DeclID.h.
References ID, and clang::PREDEF_DECL_NULL_ID.
Referenced by clang::ASTDeclReader::VisitNamespaceDecl().
operator DeclID()
clang::DeclIDBase::operator DeclID () const inline explicit
Definition at line 119 of file DeclID.h.
References ID.
operator PredefinedDeclIDs()
clang::DeclIDBase::operator PredefinedDeclIDs () const inline explicit
Definition at line 121 of file DeclID.h.
References ID.
Friends And Related Function Documentation
operator!=
bool operator!= (const DeclIDBase & LHS, const DeclIDBase & RHS) friend
Definition at line 130 of file DeclID.h.
operator<
bool operator< (const DeclIDBase & LHS, const DeclIDBase & RHS) friend
Definition at line 134 of file DeclID.h.
operator<=
bool operator<= (const DeclIDBase & LHS, const DeclIDBase & RHS) friend
Definition at line 140 of file DeclID.h.
operator==
bool operator== (const DeclIDBase & LHS, const DeclIDBase & RHS) friend
Definition at line 127 of file DeclID.h.
operator>
bool operator> (const DeclIDBase & LHS, const DeclIDBase & RHS) friend
Definition at line 137 of file DeclID.h.
operator>=
bool operator>= (const DeclIDBase & LHS, const DeclIDBase & RHS) friend
Definition at line 143 of file DeclID.h.
Member Data Documentation
ID
DeclID clang::DeclIDBase::ID protected
Definition at line 148 of file DeclID.h.
Referenced by get(), isInvalid(), isValid(), operator DeclID(), clang::GlobalDeclID::operator LocalDeclID(), operator PredefinedDeclIDs(), and clang::LocalDeclID::operator++().
The documentation for this class was generated from the following file:
include/clang/AST/DeclID.h