clang: clang::ento::CXXBaseObjectRegion Class Reference
clang::ento::CXXBaseObjectRegion Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
const CXXRecordDecl * getDecl () const
bool isVirtual () const
QualType getValueType () const override
void dumpToStream (raw_ostream &os) const override
void Profile (llvm::FoldingSetNodeID &ID) const override
bool canPrintPrettyAsExpr () const override
Returns true if this region's textual representation can be used as part of a larger expression.
void printPrettyAsExpr (raw_ostream &os) const override
Print the region as expression.
Public Member Functions inherited from clang::ento::TypedValueRegion
QualType getLocationType () const override
QualType getDesugaredValueType (ASTContext &Context) const
Public Member Functions inherited from clang::ento::TypedRegion
QualType getDesugaredLocationType (ASTContext &Context) const
bool isBoundable () const override
Public Member Functions inherited from clang::ento::SubRegion
const MemRegion * getSuperRegion () const
MemRegionManager & getMemRegionManager () const override
bool isSubRegionOf (const MemRegion *R) const override
Check if the region is a subregion of the given region.
Public Member Functions inherited from clang::ento::MemRegion
ASTContext & getContext () const
const MemSpaceRegion * getMemorySpace () const
const MemRegion * getBaseRegion () const
const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasGlobalsOrParametersStorage () const
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
const RegionTy * castAs () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Static Public Member Functions
static bool classof (const MemRegion *region)
Static Public Member Functions inherited from clang::ento::TypedValueRegion
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::TypedRegion
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::SubRegion
static bool classof (const MemRegion *R)
Friends
class MemRegionManager
Additional Inherited Members
Public Types inherited from clang::ento::MemRegion
enum Kind
Protected Member Functions inherited from clang::ento::TypedValueRegion
TypedValueRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::TypedRegion
TypedRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::SubRegion
SubRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::MemRegion
MemRegion (Kind k)
virtual ~MemRegion ()
Protected Attributes inherited from clang::ento::SubRegion
const MemRegion * superRegion
Detailed Description
Definition at line 1212 of file MemRegion.h.
Member Function Documentation
canPrintPrettyAsExpr()
bool CXXBaseObjectRegion::canPrintPrettyAsExpr () const override virtual
Returns true if this region's textual representation can be used as part of a larger expression.
Reimplemented from clang::ento::MemRegion.
Definition at line 657 of file MemRegion.cpp.
References clang::ento::MemRegion::canPrintPrettyAsExpr(), and clang::ento::SubRegion::superRegion.
classof()
static bool clang::ento::CXXBaseObjectRegion::classof (const MemRegion * region) inline static
Definition at line 1240 of file MemRegion.h.
References clang::ento::MemRegion::getKind().
dumpToStream()
void CXXBaseObjectRegion::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::MemRegion.
Definition at line 487 of file MemRegion.cpp.
References getDecl(), clang::NamedDecl::getName(), and clang::ento::SubRegion::superRegion.
getDecl()
const CXXRecordDecl* clang::ento::CXXBaseObjectRegion::getDecl () const inline
Definition at line 1227 of file MemRegion.h.
Referenced by dumpToStream(), clang::ento::MemRegionManager::getCXXBaseObjectRegionWithSuper(), getValueType(), Profile(), and clang::ento::SValExplainer::VisitCXXBaseObjectRegion().
getValueType()
QualType CXXBaseObjectRegion::getValueType () const override virtual
Implements clang::ento::TypedValueRegion.
Definition at line 173 of file MemRegion.cpp.
References getDecl().
isVirtual()
bool clang::ento::CXXBaseObjectRegion::isVirtual () const inline
Definition at line 1228 of file MemRegion.h.
Referenced by clang::ento::MemRegionManager::getCXXBaseObjectRegionWithSuper(), and Profile().
printPrettyAsExpr()
void CXXBaseObjectRegion::printPrettyAsExpr (raw_ostream & os) const override virtual
Print the region as expression.
When this region represents a subexpression, the method is for printing an expression containing it.
Reimplemented from clang::ento::MemRegion.
Definition at line 661 of file MemRegion.cpp.
References clang::ento::MemRegion::printPrettyAsExpr(), and clang::ento::SubRegion::superRegion.
Profile()
void CXXBaseObjectRegion::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Implements clang::ento::MemRegion.
Definition at line 402 of file MemRegion.cpp.
References getDecl(), isVirtual(), and clang::ento::SubRegion::superRegion.
Friends And Related Function Documentation
MemRegionManager
friend class MemRegionManager friend
Definition at line 1213 of file MemRegion.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp