clang: clang::serialization::reader::HeaderFileInfoTrait Class Reference
clang::serialization::reader::HeaderFileInfoTrait Class Reference
Trait class used to search the on-disk hash table containing all of the header search information.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Serialization/ASTReaderInternals.h"
Classes
struct internal_key_type
Public Types
using external_key_type = FileEntryRef
using internal_key_ref = const internal_key_type &
using data_type = HeaderFileInfo
using hash_value_type = unsigned
using offset_type = unsigned
Public Member Functions
HeaderFileInfoTrait (ASTReader &Reader, ModuleFile &M, HeaderSearch *HS, const char *FrameworkStrings)
internal_key_type GetInternalKey (external_key_type ekey)
bool EqualKey (internal_key_ref a, internal_key_ref b)
data_type ReadData (internal_key_ref, const unsigned char *d, unsigned DataLen)
Static Public Member Functions
static hash_value_type ComputeHash (internal_key_ref ikey)
static std::pair< unsigned, unsigned > ReadKeyDataLength (const unsigned char *&d)
static internal_key_type ReadKey (const unsigned char *d, unsigned)
Detailed Description
Trait class used to search the on-disk hash table containing all of the header search information.
The on-disk hash table contains a mapping from each header path to information about that header (how many times it has been included, its controlling macro, etc.). Note that we actually hash based on the size and mtime, and support "deep" comparisons of file names based on current inode numbers, so that the search can cope with non-normalized path names and symlinks.
Definition at line 243 of file ASTReaderInternals.h.
Member Typedef Documentation
data_type
using clang::serialization::reader::HeaderFileInfoTrait::data_type = HeaderFileInfo
Definition at line 261 of file ASTReaderInternals.h.
external_key_type
using clang::serialization::reader::HeaderFileInfoTrait::external_key_type = FileEntryRef
Definition at line 250 of file ASTReaderInternals.h.
hash_value_type
using clang::serialization::reader::HeaderFileInfoTrait::hash_value_type = unsigned
Definition at line 262 of file ASTReaderInternals.h.
internal_key_ref
using clang::serialization::reader::HeaderFileInfoTrait::internal_key_ref = const internal_key_type &
Definition at line 259 of file ASTReaderInternals.h.
offset_type
using clang::serialization::reader::HeaderFileInfoTrait::offset_type = unsigned
Definition at line 263 of file ASTReaderInternals.h.
Constructor & Destructor Documentation
HeaderFileInfoTrait()
clang::serialization::reader::HeaderFileInfoTrait::HeaderFileInfoTrait (ASTReader & Reader, ModuleFile & M, HeaderSearch * HS, const char * FrameworkStrings) inline
Definition at line 265 of file ASTReaderInternals.h.
Member Function Documentation
ComputeHash()
unsigned HeaderFileInfoTrait::ComputeHash (internal_key_ref ikey) static
Definition at line 1991 of file ASTReader.cpp.
References clang::format::hash_combine(), clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::ModTime, and clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::Size.
EqualKey()
bool HeaderFileInfoTrait::EqualKey (internal_key_ref a, internal_key_ref b)
Definition at line 2003 of file ASTReader.cpp.
References b, clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::Filename, clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::ModTime, and clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::Size.
GetInternalKey()
HeaderFileInfoTrait::internal_key_type HeaderFileInfoTrait::GetInternalKey (external_key_type ekey)
Definition at line 1996 of file ASTReader.cpp.
References clang::FileEntryRef::getModificationTime(), clang::FileEntryRef::getName(), clang::FileEntryRef::getSize(), and clang::serialization::ModuleFile::HasTimestamps.
ReadData()
HeaderFileInfoTrait::data_type HeaderFileInfoTrait::ReadData (internal_key_ref key, const unsigned char * d, unsigned DataLen)
Definition at line 2035 of file ASTReader.cpp.
References clang::ModuleMap::addHeader(), clang::HeaderFileInfo::ControllingMacroID, clang::HeaderFileInfo::DirInfo, End, clang::HeaderFileInfo::External, Filename, clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::Filename, clang::HeaderFileInfo::Framework, clang::FileManager::getOptionalFileRef(), clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::Imported, clang::HeaderFileInfo::IndexHeaderMapHeader, clang::HeaderFileInfo::isImport, clang::HeaderFileInfo::isPragmaOnce, clang::HeaderFileInfo::IsValid, and clang::HeaderFileInfo::mergeModuleMembership().
ReadKey()
HeaderFileInfoTrait::internal_key_type HeaderFileInfoTrait::ReadKey (const unsigned char * d, unsigned) static
Definition at line 2022 of file ASTReader.cpp.
References clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::Filename, clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::Imported, clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::ModTime, and clang::serialization::reader::HeaderFileInfoTrait::internal_key_type::Size.
ReadKeyDataLength()
std::pair< unsigned, unsigned > HeaderFileInfoTrait::ReadKeyDataLength (const unsigned char *& d) static
Definition at line 2017 of file ASTReader.cpp.
References readULEBKeyDataLength().
The documentation for this class was generated from the following files:
lib/Serialization/ASTReaderInternals.h
lib/Serialization/ASTReader.cpp