clang: clang::serialization::UnalignedUInt64 Class Reference
clang::serialization::UnalignedUInt64 Class Reference
32 aligned uint64_t in the AST file.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
UnalignedUInt64 ()=default
UnalignedUInt64 (uint64_t BitOffset)
void set (uint64_t Offset)
uint64_t get () const
Detailed Description
32 aligned uint64_t in the AST file.
Use splitted 64-bit integer into low/high parts to keep structure alignment 32-bit (it is important because blobs in bitstream are 32-bit aligned). This structure is serialized "as is" to the AST file.
Definition at line 194 of file ASTBitCodes.h.
Constructor & Destructor Documentation
UnalignedUInt64() [1/2]
clang::serialization::UnalignedUInt64::UnalignedUInt64 () default
UnalignedUInt64() [2/2]
clang::serialization::UnalignedUInt64::UnalignedUInt64 (uint64_t BitOffset) inline
Definition at line 200 of file ASTBitCodes.h.
References set().
Member Function Documentation
get()
uint64_t clang::serialization::UnalignedUInt64::get () const inline
Definition at line 207 of file ASTBitCodes.h.
Referenced by clang::serialization::DeclOffset::getBitOffset(), and clang::serialization::DeclOffset::getRawLoc().
set()
void clang::serialization::UnalignedUInt64::set (uint64_t Offset) inline
Definition at line 202 of file ASTBitCodes.h.
References Offset.
Referenced by clang::serialization::DeclOffset::setBitOffset(), and UnalignedUInt64().
The documentation for this class was generated from the following file:
include/clang/Serialization/ASTBitCodes.h