clang: clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData > Class Template Reference
clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData > Class Template Reference
A metaprogramming base class for TypeLoc classes which correspond to a particular Type subclass.
#include "clang/AST/TypeLoc.h"
Classes
struct HasNoInnerType
Public Member Functions
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (Derived other)
TypeLoc getNextTypeLoc () const
const TypeClass * getTypePtr () const
Protected Member Functions
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
LocalData * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Friends
class TypeLoc
Detailed Description
template<class Base, class Derived, class TypeClass, class LocalData>
class clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >
A metaprogramming base class for TypeLoc classes which correspond to a particular Type subclass.
It is accepted for a single TypeLoc class to correspond to multiple Type classes.
Template Parameters
Base a class from which to derive
Derived the class deriving from this one
TypeClass the concrete Type subclass associated with this location type
LocalData the structure type of local location data for this type
TypeLocs with non-constant amounts of local data should override getExtraLocalDataSize(); getExtraLocalData() will then point to this extra memory.
TypeLocs with an inner type should define QualType getInnerType() const and getInnerTypeLoc() will then point to this inner type's location data.
A word about hierarchies: this template is not designed to be derived from multiple times in a hierarchy. It is also not designed to be used for classes where subtypes might provide different amounts of source information. It should be subclassed only at the deepest portion of the hierarchy where all children have identical source information; if that's an abstract type, then further descendents should inherit from InheritingConcreteTypeLoc instead.
Definition at line 373 of file TypeLoc.h.
Member Function Documentation
copyLocal()
template<class Base , class Derived , class TypeClass , class LocalData > void clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal (Derived other) inline
Definition at line 403 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalData(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalDataSize(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalData(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalDataSize(), and memcpy().
getExtraLocalData()
template<class Base , class Derived , class TypeClass , class LocalData > void* clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalData () const inline protected
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
because it's of variable size).
Definition at line 441 of file TypeLoc.h.
References Data.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal().
getExtraLocalDataAlignment()
template<class Base , class Derived , class TypeClass , class LocalData > unsigned clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalDataAlignment () const inline protected
Definition at line 430 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalDataAlignment().
getExtraLocalDataSize()
template<class Base , class Derived , class TypeClass , class LocalData > unsigned clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalDataSize () const inline protected
Definition at line 426 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal().
getInnerType()
template<class Base , class Derived , class TypeClass , class LocalData > HasNoInnerType clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerType () const inline protected
Definition at line 456 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerTypeLoc(), and clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNextTypeLoc().
getInnerTypeLoc()
template<class Base , class Derived , class TypeClass , class LocalData > TypeLoc clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerTypeLoc () const inline protected
Definition at line 458 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerType(), clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNonLocalData(), and clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::TypeLoc.
getLocalData()
template<class Base , class Derived , class TypeClass , class LocalData > LocalData* clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalData () const inline protected
Definition at line 434 of file TypeLoc.h.
References Data.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal(), clang::MemberPointerTypeLoc::getClassTInfo(), clang::TypeOfTypeLoc::getUnmodifiedTInfo(), clang::MemberPointerTypeLoc::setClassTInfo(), and clang::TypeOfTypeLoc::setUnmodifiedTInfo().
getLocalDataAlignment()
template<class Base , class Derived , class TypeClass , class LocalData > unsigned clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalDataAlignment () const inline
Definition at line 390 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getExtraLocalDataAlignment(), and max().
Referenced by clang::ElaboratedTypeLoc::getLocalDataAlignment().
getLocalDataSize()
template<class Base , class Derived , class TypeClass , class LocalData > unsigned clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalDataSize () const inline
Definition at line 395 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::copyLocal(), and clang::ElaboratedTypeLoc::getLocalDataSize().
getNextTypeLoc()
template<class Base , class Derived , class TypeClass , class LocalData > TypeLoc clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNextTypeLoc () const inline
Definition at line 417 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerType().
getNonLocalData()
template<class Base , class Derived , class TypeClass , class LocalData > void* clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getNonLocalData () const inline protected
Definition at line 448 of file TypeLoc.h.
References Data.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerTypeLoc().
getTypePtr()
template<class Base , class Derived , class TypeClass , class LocalData > const TypeClass* clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr () const inline
Definition at line 421 of file TypeLoc.h.
Referenced by clang::comments::DeclInfo::fill(), fillAttributedTypeLoc(), clang::MemberPointerTypeLoc::getClass(), clang::ReferenceTypeLoc::getInnerType(), clang::Sema::getTemplateArgumentPackExpansionPattern(), clang::TypeOfExprTypeLoc::getUnderlyingExpr(), clang::TypeOfTypeLoc::getUnmodifiedType(), isEnableIf(), clang::TreeTransform< Derived >::TransformAttributedType(), clang::TreeTransform< Derived >::TransformDependentTemplateSpecializationType(), clang::TreeTransform< Derived >::TransformFunctionTypeParams(), clang::TreeTransform< Derived >::TransformReferenceType(), and clang::TreeTransform< Derived >::TransformTemplateSpecializationType().
Friends And Related Function Documentation
TypeLoc
template<class Base , class Derived , class TypeClass , class LocalData > friend class TypeLoc friend
Definition at line 374 of file TypeLoc.h.
Referenced by clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getInnerTypeLoc().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h