clang: clang::tooling::dependencies::DependencyScanningWorkerFilesystem Class Reference
clang::tooling::dependencies::DependencyScanningWorkerFilesystem Class Reference
A virtual file system optimized for the dependency discovery.
#include "clang/Tooling/DependencyScanning/DependencyScanningFilesystem.h"
Public Member Functions
DependencyScanningWorkerFilesystem (DependencyScanningFilesystemSharedCache &SharedCache, IntrusiveRefCntPtr< llvm::vfs::FileSystem > FS)
llvm::ErrorOr< llvm::vfs::Status > status (const Twine &Path) override
llvm::ErrorOr< std::unique_ptr< llvm::vfs::File > > openFileForRead (const Twine &Path) override
std::error_code getRealPath (const Twine &Path, SmallVectorImpl< char > &Output) override
std::error_code setCurrentWorkingDirectory (const Twine &Path) override
llvm::ErrorOr< EntryRef > getOrCreateFileSystemEntry (StringRef Filename)
Returns entry for the given filename.
bool ensureDirectiveTokensArePopulated (EntryRef Entry)
Ensure the directive tokens are populated for this file entry.
bool exists (const Twine &Path) override
Check whether Path exists.
Static Public Attributes
static const char ID = 0
Detailed Description
A virtual file system optimized for the dependency discovery.
It is primarily designed to work with source files whose contents was preprocessed to remove any tokens that are unlikely to affect the dependency computation.
This is not a thread safe VFS. A single instance is meant to be used only in one thread. Multiple instances are allowed to service multiple threads running in parallel.
Definition at line 337 of file DependencyScanningFilesystem.h.
Constructor & Destructor Documentation
DependencyScanningWorkerFilesystem()
DependencyScanningWorkerFilesystem::DependencyScanningWorkerFilesystem (DependencyScanningFilesystemSharedCache & SharedCache, IntrusiveRefCntPtr< llvm::vfs::FileSystem > FS)
Definition at line 211 of file DependencyScanningFilesystem.cpp.
Member Function Documentation
ensureDirectiveTokensArePopulated()
bool DependencyScanningWorkerFilesystem::ensureDirectiveTokensArePopulated (EntryRef Entry)
Ensure the directive tokens are populated for this file entry.
Returns true if the directive tokens are populated for this file entry, false if not (i.e. this entry is not a file or its scan fails).
Definition at line 44 of file DependencyScanningFilesystem.cpp.
References clang::tooling::dependencies::CachedFileContents::DepDirectives, clang::tooling::dependencies::CachedFileContents::DepDirectiveTokens, clang::tooling::dependencies::CachedFileContents::Original, clang::scanSourceForDependencyDirectives(), and clang::tooling::dependencies::CachedFileContents::ValueLock.
exists()
bool DependencyScanningWorkerFilesystem::exists (const Twine & Path) override
Check whether Path exists.
By default checks cached result of status(), and falls back on FS if unable to do so.
Definition at line 303 of file DependencyScanningFilesystem.cpp.
getOrCreateFileSystemEntry()
llvm::ErrorOr< EntryRef > DependencyScanningWorkerFilesystem::getOrCreateFileSystemEntry (StringRef Filename)
Returns entry for the given filename.
Attempts to use the local and shared caches first, then falls back to using the underlying filesystem.
Definition at line 273 of file DependencyScanningFilesystem.cpp.
References clang::tooling::dependencies::EntryRef::unwrapError().
Referenced by openFileForRead(), and status().
getRealPath()
std::error_code DependencyScanningWorkerFilesystem::getRealPath (const Twine & Path, SmallVectorImpl< char > & Output) override
Definition at line 375 of file DependencyScanningFilesystem.cpp.
References clang::tooling::dependencies::DependencyScanningFilesystemLocalCache::findRealPathByFilename(), clang::tooling::dependencies::DependencyScanningFilesystemSharedCache::getShardForFilename(), and clang::tooling::dependencies::DependencyScanningFilesystemLocalCache::insertRealPathForFilename().
openFileForRead()
llvm::ErrorOr< std::unique_ptr< llvm::vfs::File > > DependencyScanningWorkerFilesystem::openFileForRead (const Twine & Path) override
Definition at line 361 of file DependencyScanningFilesystem.cpp.
References clang::serialized_diags::create(), Filename, and getOrCreateFileSystemEntry().
setCurrentWorkingDirectory()
std::error_code DependencyScanningWorkerFilesystem::setCurrentWorkingDirectory (const Twine & Path) override
Definition at line 422 of file DependencyScanningFilesystem.cpp.
status()
llvm::ErrorOr< llvm::vfs::Status > DependencyScanningWorkerFilesystem::status (const Twine & Path) override
Definition at line 290 of file DependencyScanningFilesystem.cpp.
References Filename, and getOrCreateFileSystemEntry().
Member Data Documentation
ID
const char DependencyScanningWorkerFilesystem::ID = 0 static
Definition at line 341 of file DependencyScanningFilesystem.h.
The documentation for this class was generated from the following files:
include/clang/Tooling/DependencyScanning/DependencyScanningFilesystem.h
lib/Tooling/DependencyScanning/DependencyScanningFilesystem.cpp