clang: clang::OffloadBundler Class Reference
clang::OffloadBundler Class Reference
#include "clang/Driver/OffloadBundler.h"
Public Member Functions
OffloadBundler (const OffloadBundlerConfig &BC)
llvm::Error BundleFiles ()
Bundle the files. Return true if an error was found.
llvm::Error UnbundleFiles ()
llvm::Error UnbundleArchive ()
UnbundleArchive takes an archive file (".a") as input containing bundled code object files, and a list of offload targets (not host), and extracts the code objects into a new archive file for each offload target.
Static Public Member Functions
static llvm::Error ListBundleIDsInFile (llvm::StringRef InputFileName, const OffloadBundlerConfig &BundlerConfig)
Public Attributes
const OffloadBundlerConfig & BundlerConfig
Detailed Description
Definition at line 59 of file OffloadBundler.h.
Constructor & Destructor Documentation
OffloadBundler()
clang::OffloadBundler::OffloadBundler (const OffloadBundlerConfig & BC) inline
Definition at line 64 of file OffloadBundler.h.
Member Function Documentation
BundleFiles()
Error OffloadBundler::BundleFiles ()
Bundle the files. Return true if an error was found.
Definition at line 1846 of file OffloadBundler.cpp.
References clang::OffloadBundlerConfig::AllowNoHost, BundlerConfig, clang::OffloadBundlerConfig::Compress, clang::CompressedOffloadBundle::compress(), clang::OffloadBundlerConfig::CompressionFormat, clang::OffloadBundlerConfig::CompressionLevel, CreateFileHandler(), clang::OffloadBundlerConfig::FilesType, FilesTypeIsArchive(), clang::OffloadBundlerConfig::HostInputIndex, clang::OffloadBundlerConfig::InputFileNames, clang::OffloadBundlerConfig::OutputFileNames, clang::OffloadBundlerConfig::TargetNames, and clang::OffloadBundlerConfig::Verbose.
ListBundleIDsInFile()
Error OffloadBundler::ListBundleIDsInFile (llvm::StringRef InputFileName, const OffloadBundlerConfig & BundlerConfig) static
Definition at line 1721 of file OffloadBundler.cpp.
References BundlerConfig, CreateFileHandler(), clang::CompressedOffloadBundle::decompress(), clang::threadSafety::sx::toString(), and clang::OffloadBundlerConfig::Verbose.
UnbundleArchive()
Error OffloadBundler::UnbundleArchive ()
UnbundleArchive takes an archive file (".a") as input containing bundled code object files, and a list of offload targets (not host), and extracts the code objects into a new archive file for each offload target.
Each resulting archive file contains all code object files corresponding to that particular offload target. The created archive file does not contain an index of the symbols and code object files are named as <<Parent Bundle Name>-<CodeObject's TargetID>>, with ':' replaced with '_'.
Map of target names with list of object files that will form the device specific archive for that target
Iterate over all bundled code object files in the input archive.
Write out an archive for each target
Definition at line 2224 of file OffloadBundler.cpp.
References clang::OffloadBundlerConfig::AllowMissingBundles, BundlerConfig, CheckHeterogeneousArchive(), clang::OffloadBundlerConfig::CheckInputArchive, clang::serialized_diags::create(), CreateFileHandler(), clang::CompressedOffloadBundle::decompress(), clang::FileName, getCompatibleOffloadTargets(), getDefaultArchiveKindForHost(), getDeviceLibraryFileName(), clang::OffloadBundlerConfig::InputFileNames, clang::OffloadBundlerConfig::OutputFileNames, clang::OffloadBundlerConfig::TargetNames, clang::threadSafety::sx::toString(), and clang::OffloadBundlerConfig::Verbose.
UnbundleFiles()
Error OffloadBundler::UnbundleFiles ()
Definition at line 1927 of file OffloadBundler.cpp.
References clang::OffloadBundlerConfig::AllowMissingBundles, BundlerConfig, CreateFileHandler(), clang::CompressedOffloadBundle::decompress(), clang::OffloadBundlerConfig::FilesType, FilesTypeIsArchiveToList(), clang::OffloadBundlerConfig::HostInputIndex, clang::OffloadBundlerConfig::InputFileNames, isCodeObjectCompatible(), clang::Last, clang::OffloadBundlerConfig::OutputFileNames, clang::OffloadBundlerConfig::TargetNames, clang::threadSafety::sx::toString(), and clang::OffloadBundlerConfig::Verbose.
Member Data Documentation
BundlerConfig
const OffloadBundlerConfig& clang::OffloadBundler::BundlerConfig
Definition at line 61 of file OffloadBundler.h.
Referenced by BundleFiles(), ListBundleIDsInFile(), UnbundleArchive(), and UnbundleFiles().
The documentation for this class was generated from the following files:
include/clang/Driver/OffloadBundler.h
lib/Driver/OffloadBundler.cpp