clang: clang::tooling::dependencies::DependencyConsumer Class Reference
clang::tooling::dependencies::DependencyConsumer Class Reference abstract
#include "clang/Tooling/DependencyScanning/DependencyScanningWorker.h"
Public Member Functions
virtual ~DependencyConsumer ()
virtual void handleProvidedAndRequiredStdCXXModules (std::optional< P1689ModuleInfo > Provided, std::vector< P1689ModuleInfo > Requires)
virtual void handleBuildCommand (Command Cmd)
virtual void handleDependencyOutputOpts (const DependencyOutputOptions &Opts)=0
virtual void handleFileDependency (StringRef Filename)=0
virtual void handlePrebuiltModuleDependency (PrebuiltModuleDep PMD)=0
virtual void handleModuleDependency (ModuleDeps MD)=0
virtual void handleDirectModuleDependency (ModuleID MD)=0
virtual void handleContextHash (std::string Hash)=0
Detailed Description
Definition at line 40 of file DependencyScanningWorker.h.
Constructor & Destructor Documentation
~DependencyConsumer()
virtual clang::tooling::dependencies::DependencyConsumer::~DependencyConsumer () inline virtual
Definition at line 42 of file DependencyScanningWorker.h.
Member Function Documentation
handleBuildCommand()
virtual void clang::tooling::dependencies::DependencyConsumer::handleBuildCommand (Command Cmd) inline virtual
Reimplemented in clang::tooling::dependencies::FullDependencyConsumer.
Definition at line 48 of file DependencyScanningWorker.h.
Referenced by createAndRunToolInvocation().
handleContextHash()
virtual void clang::tooling::dependencies::DependencyConsumer::handleContextHash (std::string Hash) pure virtual
Implemented in clang::tooling::dependencies::FullDependencyConsumer.
Referenced by clang::tooling::dependencies::ModuleDepCollectorPP::LexedFileChanged().
handleDependencyOutputOpts()
virtual void clang::tooling::dependencies::DependencyConsumer::handleDependencyOutputOpts (const DependencyOutputOptions & Opts) pure virtual
Implemented in clang::tooling::dependencies::FullDependencyConsumer.
Referenced by clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile().
handleDirectModuleDependency()
virtual void clang::tooling::dependencies::DependencyConsumer::handleDirectModuleDependency (ModuleID MD) pure virtual
Implemented in clang::tooling::dependencies::FullDependencyConsumer.
Referenced by clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile().
handleFileDependency()
virtual void clang::tooling::dependencies::DependencyConsumer::handleFileDependency (StringRef Filename) pure virtual
Implemented in clang::tooling::dependencies::FullDependencyConsumer.
Referenced by clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile().
handleModuleDependency()
virtual void clang::tooling::dependencies::DependencyConsumer::handleModuleDependency (ModuleDeps MD) pure virtual
Implemented in clang::tooling::dependencies::FullDependencyConsumer.
Referenced by clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile().
handlePrebuiltModuleDependency()
virtual void clang::tooling::dependencies::DependencyConsumer::handlePrebuiltModuleDependency (PrebuiltModuleDep PMD) pure virtual
Implemented in clang::tooling::dependencies::FullDependencyConsumer.
Referenced by clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile().
handleProvidedAndRequiredStdCXXModules()
virtual void clang::tooling::dependencies::DependencyConsumer::handleProvidedAndRequiredStdCXXModules (std::optional< P1689ModuleInfo > Provided, std::vector< P1689ModuleInfo > Requires) inline virtual
Definition at line 44 of file DependencyScanningWorker.h.
Referenced by clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile().
The documentation for this class was generated from the following file:
include/clang/Tooling/DependencyScanning/DependencyScanningWorker.h