clang: clang::TypeLocVisitor< ImplClass, RetTy > Class Template Reference
clang::TypeLocVisitor< ImplClass, RetTy > Class Template Reference
#include "clang/AST/TypeLocVisitor.h"
Public Member Functions
RetTy Visit (TypeLoc TyLoc)
RetTy Visit (UnqualTypeLoc TyLoc)
RetTy VisitTypeLoc (TypeLoc TyLoc)
Detailed Description
template<typename ImplClass, typename RetTy = void>
class clang::TypeLocVisitor< ImplClass, RetTy >
Definition at line 25 of file TypeLocVisitor.h.
Member Function Documentation
Visit() [1/2]
template<typename ImplClass , typename RetTy = void> RetTy clang::TypeLocVisitor< ImplClass, RetTy >::Visit (TypeLoc TyLoc) inline
Definition at line 27 of file TypeLocVisitor.h.
References clang::TypeLoc::getTypeLocClass().
Referenced by clang::ASTRecordReader::readTypeLoc(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit(), and clang::TextNodeDumper::Visit().
Visit() [2/2]
template<typename ImplClass , typename RetTy = void> RetTy clang::TypeLocVisitor< ImplClass, RetTy >::Visit (UnqualTypeLoc TyLoc) inline
Definition at line 37 of file TypeLocVisitor.h.
References clang::UnqualTypeLoc::getTypeLocClass().
VisitTypeLoc()
template<typename ImplClass , typename RetTy = void> RetTy clang::TypeLocVisitor< ImplClass, RetTy >::VisitTypeLoc (TypeLoc TyLoc) inline
Definition at line 53 of file TypeLocVisitor.h.
The documentation for this class was generated from the following file:
include/clang/AST/TypeLocVisitor.h