clang: clang::EffectConditionExpr Class Reference
clang::EffectConditionExpr Class Reference
Wrap a function effect's condition expression in another struct so that FunctionProtoType's TrailingObjects can treat it separately.
#include "clang/AST/Type.h"
Public Member Functions
EffectConditionExpr ()=default
EffectConditionExpr (Expr *E)
Expr * getCondition () const
bool operator== (const EffectConditionExpr &RHS) const
Detailed Description
Wrap a function effect's condition expression in another struct so that FunctionProtoType's TrailingObjects can treat it separately.
Definition at line 4784 of file Type.h.
Constructor & Destructor Documentation
EffectConditionExpr() [1/2]
clang::EffectConditionExpr::EffectConditionExpr () default
EffectConditionExpr() [2/2]
clang::EffectConditionExpr::EffectConditionExpr (Expr * E) inline
Definition at line 4789 of file Type.h.
Member Function Documentation
getCondition()
Expr* clang::EffectConditionExpr::getCondition () const inline
Definition at line 4791 of file Type.h.
Referenced by clang::FunctionEffectWithCondition::description(), clang::Sema::diagnoseConflictingFunctionEffect(), clang::FunctionEffectDifferences::FunctionEffectDifferences(), clang::FunctionEffectSet::insert(), clang::TreeTransform< Derived >::TransformFunctionProtoType(), and clang::serialization::DataStreamBasicWriter< Impl >::writeEffectConditionExpr().
operator==()
bool clang::EffectConditionExpr::operator== (const EffectConditionExpr & RHS) const inline
Definition at line 4793 of file Type.h.
The documentation for this class was generated from the following file:
include/clang/AST/Type.h