clang: clang::driver::OffloadAction::HostDependence Class Reference
clang::driver::OffloadAction::HostDependence Class Reference final
Type used to communicate host actions.
#include "clang/Driver/Action.h"
Public Member Functions
HostDependence (Action &A, const ToolChain &TC, const char *BoundArch, const unsigned OffloadKinds)
HostDependence (Action &A, const ToolChain &TC, const char *BoundArch, const DeviceDependences &DDeps)
Constructor version that obtains the offload kinds from the device dependencies.
Action * getAction () const
const ToolChain * getToolChain () const
const char * getBoundArch () const
unsigned getOffloadKinds () const
Detailed Description
Type used to communicate host actions.
It associates bound architecture, toolchain, and offload kinds to the host action.
Definition at line 319 of file Action.h.
Constructor & Destructor Documentation
HostDependence() [1/2]
clang::driver::OffloadAction::HostDependence::HostDependence (Action & A, const ToolChain & TC, const char * BoundArch, const unsigned OffloadKinds) inline
Definition at line 333 of file Action.h.
HostDependence() [2/2]
OffloadAction::HostDependence::HostDependence (Action & A, const ToolChain & TC, const char * BoundArch, const DeviceDependences & DDeps)
Constructor version that obtains the offload kinds from the device dependencies.
Definition at line 332 of file Action.cpp.
References clang::driver::OffloadAction::DeviceDependences::getOffloadKinds().
Member Function Documentation
getAction()
Action* clang::driver::OffloadAction::HostDependence::getAction () const inline
Definition at line 342 of file Action.h.
Referenced by clang::driver::OffloadAction::OffloadAction(), and clang::driver::OffloadDepsJobAction::OffloadDepsJobAction().
getBoundArch()
const char* clang::driver::OffloadAction::HostDependence::getBoundArch () const inline
Definition at line 344 of file Action.h.
Referenced by clang::driver::OffloadAction::OffloadAction(), and clang::driver::OffloadDepsJobAction::OffloadDepsJobAction().
getOffloadKinds()
unsigned clang::driver::OffloadAction::HostDependence::getOffloadKinds () const inline
Definition at line 345 of file Action.h.
Referenced by clang::driver::OffloadAction::OffloadAction(), and clang::driver::OffloadDepsJobAction::OffloadDepsJobAction().
getToolChain()
const ToolChain* clang::driver::OffloadAction::HostDependence::getToolChain () const inline
Definition at line 343 of file Action.h.
The documentation for this class was generated from the following files:
include/clang/Driver/Action.h
lib/Driver/Action.cpp