clang: clang::SourceLocationEncoding Class Reference
clang::SourceLocationEncoding Class Reference
Serialized encoding of SourceLocations without context.
#include "clang/Serialization/SourceLocationEncoding.h"
Public Types
using RawLocEncoding = uint64_t
Static Public Member Functions
static RawLocEncoding encode (SourceLocation Loc, UIntTy BaseOffset, unsigned BaseModuleFileIndex, SourceLocationSequence *=nullptr)
static std::pair< SourceLocation, unsigned > decode (RawLocEncoding, SourceLocationSequence *=nullptr)
Detailed Description
Serialized encoding of SourceLocations without context.
Optimized to have small unsigned values (=> small after VBR encoding).
Definition at line 47 of file SourceLocationEncoding.h.
Member Typedef Documentation
RawLocEncoding
using clang::SourceLocationEncoding::RawLocEncoding = uint64_t
Definition at line 60 of file SourceLocationEncoding.h.
Member Function Documentation
decode()
std::pair< SourceLocation, unsigned > clang::SourceLocationEncoding::decode (RawLocEncoding Encoded, SourceLocationSequence * Seq = nullptr) inline static
Definition at line 186 of file SourceLocationEncoding.h.
References clang::SourceLocation::getFromRawEncoding(), Loc, and clang::Seq.
Referenced by clang::ASTReader::ReadUntranslatedSourceLocation().
encode()
SourceLocationEncoding::RawLocEncoding clang::SourceLocationEncoding::encode (SourceLocation Loc, UIntTy BaseOffset, unsigned BaseModuleFileIndex, SourceLocationSequence * Seq = nullptr) inline static
Definition at line 162 of file SourceLocationEncoding.h.
References Loc, and clang::Seq.
Referenced by clang::ASTWriter::getRawSourceLocationEncoding().
The documentation for this class was generated from the following file:
include/clang/Serialization/SourceLocationEncoding.h