clang: clang::interp::Record Class Reference
clang::interp::Record Class Reference final
Structure/Class descriptor.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Record.h"
Classes
struct Base
Describes a base class.
struct Field
Describes a record field.
Public Types
using FieldList = llvm::SmallVector< Field, 8 >
Mapping from identifiers to field descriptors.
using BaseList = llvm::SmallVector< Base, 8 >
Mapping from identifiers to base classes.
using VirtualBaseList = llvm::SmallVector< Base, 2 >
List of virtual base classes.
using const_field_iter = FieldList::const_iterator
using const_base_iter = BaseList::const_iterator
using const_virtual_iter = VirtualBaseList::const_iterator
Public Member Functions
const RecordDecl * getDecl () const
Returns the underlying declaration.
const std::string getName () const
Returns the name of the underlying declaration.
bool isUnion () const
Checks if the record is a union.
unsigned getSize () const
Returns the size of the record.
unsigned getFullSize () const
Returns the full size of the record, including records.
const Field * getField (const FieldDecl *FD) const
Returns a field.
const Base * getBase (const RecordDecl *FD) const
Returns a base descriptor.
const Base * getBase (QualType T) const
Returns a base descriptor.
const Base * getVirtualBase (const RecordDecl *RD) const
Returns a virtual base descriptor.
const CXXDestructorDecl * getDestructor () const
Returns the destructor of the record, if any.
llvm::iterator_range< const_field_iter > fields () const
unsigned getNumFields () const
const Field * getField (unsigned I) const
llvm::iterator_range< const_base_iter > bases () const
unsigned getNumBases () const
const Base * getBase (unsigned I) const
llvm::iterator_range< const_virtual_iter > virtual_bases () const
unsigned getNumVirtualBases () const
const Base * getVirtualBase (unsigned I) const
void dump (llvm::raw_ostream &OS, unsigned Indentation=0, unsigned Offset=0) const
void dump () const
Friends
class Program
Detailed Description
Structure/Class descriptor.
Definition at line 25 of file Record.h.
Member Typedef Documentation
BaseList
using clang::interp::Record::BaseList = llvm::SmallVector<Base, 8>
Mapping from identifiers to base classes.
Definition at line 46 of file Record.h.
const_base_iter
using clang::interp::Record::const_base_iter = BaseList::const_iterator
Definition at line 84 of file Record.h.
const_field_iter
using clang::interp::Record::const_field_iter = FieldList::const_iterator
Definition at line 76 of file Record.h.
const_virtual_iter
using clang::interp::Record::const_virtual_iter = VirtualBaseList::const_iterator
Definition at line 95 of file Record.h.
FieldList
using clang::interp::Record::FieldList = llvm::SmallVector<Field, 8>
Mapping from identifiers to field descriptors.
Definition at line 44 of file Record.h.
VirtualBaseList
using clang::interp::Record::VirtualBaseList = llvm::SmallVector<Base, 2>
List of virtual base classes.
Definition at line 48 of file Record.h.
Member Function Documentation
bases()
llvm::iterator_range<const_base_iter> clang::interp::Record::bases () const inline
Definition at line 85 of file Record.h.
Referenced by ctorRecord(), dtorRecord(), and dump().
dump() [1/2]
void clang::interp::Record::dump () const inline
Definition at line 105 of file Record.h.
References dump().
Referenced by dump().
dump() [2/2]
LLVM_DUMP_METHOD void Record::dump (llvm::raw_ostream & OS, unsigned Indentation = 0, unsigned Offset = 0) const
Definition at line 237 of file Disasm.cpp.
References bases(), fields(), getName(), clang::Indent(), and Offset.
fields()
llvm::iterator_range<const_field_iter> clang::interp::Record::fields () const inline
Definition at line 77 of file Record.h.
Referenced by ctorRecord(), dtorRecord(), dump(), moveRecord(), clang::interp::Pointer::toRValue(), and clang::interp::ByteCodeExprGen< Emitter >::VisitLambdaExpr().
getBase() [1/3]
const Record::Base * Record::getBase (const RecordDecl * FD) const
Returns a base descriptor.
Definition at line 45 of file Record.cpp.
Referenced by clang::interp::Pointer::toRValue(), clang::interp::ByteCodeStmtGen< Emitter >::visitFunc(), and clang::interp::ByteCodeExprGen< Emitter >::visitInitList().
getBase() [2/3]
const Record::Base * Record::getBase (QualType T) const
Returns a base descriptor.
Definition at line 51 of file Record.cpp.
References clang::Type::getAs(), getDecl(), clang::Type::isRecordType(), and clang::T.
getBase() [3/3]
const Base* clang::interp::Record::getBase (unsigned I) const inline
Definition at line 90 of file Record.h.
References getNumBases().
getDecl()
const RecordDecl* clang::interp::Record::getDecl () const inline
Returns the underlying declaration.
Definition at line 52 of file Record.h.
Referenced by getBase(), and isUnion().
getDestructor()
const CXXDestructorDecl* clang::interp::Record::getDestructor () const inline
Returns the destructor of the record, if any.
Definition at line 70 of file Record.h.
getField() [1/2]
const Record::Field * Record::getField (const FieldDecl * FD) const
Returns a field.
Definition at line 39 of file Record.cpp.
Referenced by clang::interp::ByteCodeEmitter::compileFunc(), clang::interp::Pointer::toRValue(), clang::interp::ByteCodeExprGen< Emitter >::VisitCXXUuidofExpr(), clang::interp::ByteCodeStmtGen< Emitter >::visitFunc(), clang::interp::ByteCodeExprGen< Emitter >::visitInitList(), clang::interp::ByteCodeExprGen< Emitter >::VisitMemberExpr(), and clang::interp::ByteCodeExprGen< Emitter >::VisitSourceLocExpr().
getField() [2/2]
const Field* clang::interp::Record::getField (unsigned I) const inline
Definition at line 82 of file Record.h.
getFullSize()
unsigned clang::interp::Record::getFullSize () const inline
Returns the full size of the record, including records.
Definition at line 60 of file Record.h.
getName()
const std::string Record::getName () const
Returns the name of the underlying declaration.
Definition at line 31 of file Record.cpp.
References clang::Decl::getASTContext(), clang::ASTContext::getPrintingPolicy(), and clang::interp::Ret().
Referenced by dump().
getNumBases()
unsigned clang::interp::Record::getNumBases () const inline
Definition at line 89 of file Record.h.
Referenced by getBase(), and clang::interp::Pointer::toRValue().
getNumFields()
unsigned clang::interp::Record::getNumFields () const inline
Definition at line 81 of file Record.h.
Referenced by clang::interp::Pointer::toRValue(), and clang::interp::ByteCodeExprGen< Emitter >::VisitSourceLocExpr().
getNumVirtualBases()
unsigned clang::interp::Record::getNumVirtualBases () const inline
Definition at line 100 of file Record.h.
Referenced by clang::interp::Pointer::toRValue().
getSize()
unsigned clang::interp::Record::getSize () const inline
Returns the size of the record.
Definition at line 58 of file Record.h.
Referenced by clang::interp::Program::getOrCreateRecord().
getVirtualBase() [1/2]
const Record::Base * Record::getVirtualBase (const RecordDecl * RD) const
Returns a virtual base descriptor.
Definition at line 59 of file Record.cpp.
Referenced by clang::interp::Pointer::toRValue().
getVirtualBase() [2/2]
const Base* clang::interp::Record::getVirtualBase (unsigned I) const inline
Definition at line 101 of file Record.h.
isUnion()
bool clang::interp::Record::isUnion () const inline
Checks if the record is a union.
Definition at line 56 of file Record.h.
References getDecl(), and clang::TagDecl::isUnion().
Referenced by ctorRecord().
virtual_bases()
llvm::iterator_range<const_virtual_iter> clang::interp::Record::virtual_bases () const inline
Definition at line 96 of file Record.h.
Referenced by ctorRecord(), and dtorRecord().
Friends And Related Function Documentation
Program
friend class Program friend
Definition at line 114 of file Record.h.
The documentation for this class was generated from the following files:
lib/AST/Interp/Record.h
lib/AST/Interp/Disasm.cpp
lib/AST/Interp/Record.cpp