clang: clang::ControlDependencyCalculator Class Reference
clang::ControlDependencyCalculator Class Reference
#include "clang/Analysis/Analyses/Dominators.h"
Public Member Functions
ControlDependencyCalculator (CFG *cfg)
const CFGPostDomTree & getCFGPostDomTree () const
const CFGBlockVector & getControlDependencies (CFGBlock *A)
bool isControlDependent (CFGBlock *A, CFGBlock *B)
Whether A is control dependent on B.
LLVM_DUMP_METHOD void dump ()
Public Member Functions inherited from clang::ManagedAnalysis
virtual ~ManagedAnalysis ()
Additional Inherited Members
Protected Member Functions inherited from clang::ManagedAnalysis
ManagedAnalysis ()=default
Detailed Description
Definition at line 215 of file Dominators.h.
Constructor & Destructor Documentation
ControlDependencyCalculator()
clang::ControlDependencyCalculator::ControlDependencyCalculator (CFG * cfg) inline
Definition at line 226 of file Dominators.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::ControlDependencyCalculator::dump () inline
Definition at line 254 of file Dominators.h.
References clang::CFGDominatorTreeImpl< IsPostDom >::getCFG(), and getControlDependencies().
getCFGPostDomTree()
const CFGPostDomTree& clang::ControlDependencyCalculator::getCFGPostDomTree () const inline
Definition at line 229 of file Dominators.h.
getControlDependencies()
const CFGBlockVector& clang::ControlDependencyCalculator::getControlDependencies (CFGBlock * A) inline
Definition at line 232 of file Dominators.h.
Referenced by dump(), and isControlDependent().
isControlDependent()
bool clang::ControlDependencyCalculator::isControlDependent (CFGBlock * A, CFGBlock * B) inline
Whether A is control dependent on B.
Definition at line 249 of file Dominators.h.
References getControlDependencies().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/Dominators.h