clang: clang::SemaPseudoObject Class Reference
clang::SemaPseudoObject Class Reference
#include "clang/Sema/SemaPseudoObject.h"
Public Member Functions
SemaPseudoObject (Sema &S)
ExprResult checkIncDec (Scope *S, SourceLocation OpLoc, UnaryOperatorKind Opcode, Expr *Op)
Check an increment or decrement of a pseudo-object expression.
ExprResult checkAssignment (Scope *S, SourceLocation OpLoc, BinaryOperatorKind Opcode, Expr *LHS, Expr *RHS)
ExprResult checkRValue (Expr *E)
Expr * recreateSyntacticForm (PseudoObjectExpr *E)
Given a pseudo-object expression, recreate what it looks like syntactically without the attendant OpaqueValueExprs.
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 26 of file SemaPseudoObject.h.
Constructor & Destructor Documentation
SemaPseudoObject()
SemaPseudoObject::SemaPseudoObject (Sema & S)
Definition at line 1595 of file SemaPseudoObject.cpp.
Member Function Documentation
checkAssignment()
ExprResult SemaPseudoObject::checkAssignment (Scope * S, SourceLocation OpLoc, BinaryOperatorKind Opcode, Expr * LHS, Expr * RHS)
Definition at line 1505 of file SemaPseudoObject.cpp.
Referenced by clang::TreeTransform< Derived >::RebuildCXXOperatorCallExpr().
checkIncDec()
ExprResult SemaPseudoObject::checkIncDec (Scope * S, SourceLocation OpLoc, UnaryOperatorKind Opcode, Expr * Op)
Check an increment or decrement of a pseudo-object expression.
Definition at line 1475 of file SemaPseudoObject.cpp.
References clang::UnaryOperator::Create(), Diag(), clang::ExprError(), clang::Expr::IgnoreParens(), clang::UnaryOperator::isIncrementDecrementOp(), clang::Expr::isTypeDependent(), clang::OK_Ordinary, and clang::VK_PRValue.
checkRValue()
ExprResult SemaPseudoObject::checkRValue (Expr * E)
Definition at line 1450 of file SemaPseudoObject.cpp.
References E, and clang::Expr::IgnoreParens().
recreateSyntacticForm()
Expr * SemaPseudoObject::recreateSyntacticForm (PseudoObjectExpr * E)
Given a pseudo-object expression, recreate what it looks like syntactically without the attendant OpaqueValueExprs.
This is a hack which should be removed when TreeTransform is capable of rebuilding a tree without stripping implicit operations.
Definition at line 1561 of file SemaPseudoObject.cpp.
References clang::UnaryOperator::Create(), clang::BinaryOperator::Create(), clang::CompoundAssignOperator::Create(), E, clang::Expr::getType(), clang::Expr::hasPlaceholderType(), and stripOpaqueValuesFromPseudoObjectRef().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaPseudoObject.h
lib/Sema/SemaPseudoObject.cpp