clang: clang::FunctionEffectsRef Class Reference
clang::FunctionEffectsRef Class Reference
An immutable set of FunctionEffects and possibly conditions attached to them.
#include "clang/AST/Type.h"
Public Types
using iterator = FunctionEffectIterator< FunctionEffectsRef >
Public Member Functions
FunctionEffectsRef ()=default
bool empty () const
size_t size () const
ArrayRef< FunctionEffect > effects () const
ArrayRef< EffectConditionExpr > conditions () const
iterator begin () const
iterator end () const
void dump (llvm::raw_ostream &OS) const
Static Public Member Functions
static FunctionEffectsRef get (QualType QT)
Extract the effects from a Type if it is a function, block, or member function pointer, or a reference or pointer to one.
static FunctionEffectsRef create (ArrayRef< FunctionEffect > FX, ArrayRef< EffectConditionExpr > Conds)
Asserts invariants.
Public Attributes
friend iterator
Friends
bool operator== (const FunctionEffectsRef &LHS, const FunctionEffectsRef &RHS)
bool operator!= (const FunctionEffectsRef &LHS, const FunctionEffectsRef &RHS)
Detailed Description
An immutable set of FunctionEffects and possibly conditions attached to them.
The effects and conditions reside in memory not managed by this object (typically, trailing objects in FunctionProtoType, or borrowed references from a FunctionEffectSet).
Invariants:
there is never more than one instance of any given effect.
the array of conditions is either empty or has the same size as the array of effects.
some conditions may be null expressions; each condition pertains to the effect at the same array index.
Also, if there are any conditions, at least one of those expressions will be dependent, but this is only asserted in the constructor of FunctionProtoType.
See also FunctionEffectSet, in Sema, which provides a mutable set.
Definition at line 4863 of file Type.h.
Member Typedef Documentation
iterator
using clang::FunctionEffectsRef::iterator = FunctionEffectIterator<FunctionEffectsRef>
Definition at line 4899 of file Type.h.
Constructor & Destructor Documentation
FunctionEffectsRef()
clang::FunctionEffectsRef::FunctionEffectsRef () default
Referenced by create().
Member Function Documentation
begin()
iterator clang::FunctionEffectsRef::begin () const inline
Definition at line 4901 of file Type.h.
Referenced by clang::FunctionEffectDifferences::FunctionEffectDifferences(), and clang::FunctionEffectSet::getIntersection().
conditions()
ArrayRef<EffectConditionExpr> clang::FunctionEffectsRef::conditions () const inline
Definition at line 4897 of file Type.h.
Referenced by clang::TreeTransform< Derived >::TransformFunctionProtoType().
create()
FunctionEffectsRef FunctionEffectsRef::create (ArrayRef< FunctionEffect > FX, ArrayRef< EffectConditionExpr > Conds) static
Asserts invariants.
Definition at line 5326 of file Type.cpp.
References FunctionEffectsRef().
dump()
LLVM_DUMP_METHOD void FunctionEffectsRef::dump (llvm::raw_ostream & OS) const
Definition at line 5303 of file Type.cpp.
References clang::Stmt::dump(), E, and clang::First.
Referenced by clang::FunctionEffectSet::dump().
effects()
ArrayRef<FunctionEffect> clang::FunctionEffectsRef::effects () const inline
Definition at line 4896 of file Type.h.
empty()
bool clang::FunctionEffectsRef::empty () const inline
Definition at line 4893 of file Type.h.
Referenced by clang::FunctionEffectSet::getUnion(), and clang::FunctionProtoType::ExtProtoInfo::requiresFunctionProtoTypeExtraBitfields().
end()
iterator clang::FunctionEffectsRef::end () const inline
Definition at line 4902 of file Type.h.
Referenced by clang::FunctionEffectDifferences::FunctionEffectDifferences(), and clang::FunctionEffectSet::getIntersection().
get()
FunctionEffectsRef clang::FunctionEffectsRef::get (QualType QT) inline static
Extract the effects from a Type if it is a function, block, or member function pointer, or a reference or pointer to one.
Definition at line 8649 of file Type.h.
References clang::Type::getAs(), clang::Type::getPointeeType(), and clang::QualType::isNull().
Referenced by clang::Sema::diagnoseFunctionEffectConversion().
size()
size_t clang::FunctionEffectsRef::size () const inline
Definition at line 4894 of file Type.h.
Friends And Related Function Documentation
operator!=
bool operator!= (const FunctionEffectsRef & LHS, const FunctionEffectsRef & RHS) friend
Definition at line 4908 of file Type.h.
operator==
bool operator== (const FunctionEffectsRef & LHS, const FunctionEffectsRef & RHS) friend
Definition at line 4904 of file Type.h.
Member Data Documentation
iterator
friend clang::FunctionEffectsRef::iterator
Definition at line 4900 of file Type.h.
The documentation for this class was generated from the following files:
include/clang/AST/Type.h
lib/AST/Type.cpp