clang: clang::arcmt::Transaction Class Reference
clang::arcmt::Transaction Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/ARCMigrate/Internals.h"
Public Member Functions
Transaction (TransformActions &TA)
~Transaction ()
void abort ()
bool isAborted () const
Detailed Description
Definition at line 124 of file Internals.h.
Constructor & Destructor Documentation
Transaction()
clang::arcmt::Transaction::Transaction (TransformActions & TA) inline
Definition at line 129 of file Internals.h.
References clang::arcmt::TransformActions::startTransaction().
~Transaction()
clang::arcmt::Transaction::~Transaction () inline
Definition at line 133 of file Internals.h.
References clang::arcmt::TransformActions::commitTransaction(), and isAborted().
Member Function Documentation
abort()
void clang::arcmt::Transaction::abort () inline
Definition at line 138 of file Internals.h.
References clang::arcmt::TransformActions::abortTransaction().
isAborted()
bool clang::arcmt::Transaction::isAborted () const inline
Definition at line 143 of file Internals.h.
Referenced by ~Transaction().
The documentation for this class was generated from the following file:
lib/ARCMigrate/Internals.h