clang: clang::CodeGen::CodeGenTBAA Class Reference
clang::CodeGen::CodeGenTBAA Class Reference
CodeGenTBAA - This class organizes the cross-module state that is used while lowering AST types to LLVM types.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenTBAA.h"
Public Member Functions
CodeGenTBAA (ASTContext &Ctx, llvm::Module &M, const CodeGenOptions &CGO, const LangOptions &Features, MangleContext &MContext)
~CodeGenTBAA ()
llvm::MDNode * getTypeInfo (QualType QTy)
getTypeInfo - Get metadata used to describe accesses to objects of the given type.
TBAAAccessInfo getAccessInfo (QualType AccessType)
getAccessInfo - Get TBAA information that describes an access to an object of the given type.
TBAAAccessInfo getVTablePtrAccessInfo (llvm::Type *VTablePtrType)
getVTablePtrAccessInfo - Get the TBAA information that describes an access to a virtual table pointer.
llvm::MDNode * getTBAAStructInfo (QualType QTy)
getTBAAStructInfo - Get the TBAAStruct MDNode to be used for a memcpy of the given type.
llvm::MDNode * getBaseTypeInfo (QualType QTy)
getBaseTypeInfo - Get metadata that describes the given base access type.
llvm::MDNode * getAccessTagInfo (TBAAAccessInfo Info)
getAccessTagInfo - Get TBAA tag for a given memory access.
TBAAAccessInfo mergeTBAAInfoForCast (TBAAAccessInfo SourceInfo, TBAAAccessInfo TargetInfo)
mergeTBAAInfoForCast - Get merged TBAA information for the purpose of type casts.
TBAAAccessInfo mergeTBAAInfoForConditionalOperator (TBAAAccessInfo InfoA, TBAAAccessInfo InfoB)
mergeTBAAInfoForConditionalOperator - Get merged TBAA information for the purpose of conditional operator.
TBAAAccessInfo mergeTBAAInfoForMemoryTransfer (TBAAAccessInfo DestInfo, TBAAAccessInfo SrcInfo)
mergeTBAAInfoForMemoryTransfer - Get merged TBAA information for the purpose of memory transfer calls.
Detailed Description
CodeGenTBAA - This class organizes the cross-module state that is used while lowering AST types to LLVM types.
Definition at line 116 of file CodeGenTBAA.h.
Constructor & Destructor Documentation
CodeGenTBAA()
CodeGenTBAA::CodeGenTBAA (ASTContext & Ctx, llvm::Module & M, const CodeGenOptions & CGO, const LangOptions & Features, MangleContext & MContext)
Definition at line 32 of file CodeGenTBAA.cpp.
~CodeGenTBAA()
CodeGenTBAA::~CodeGenTBAA ()
Definition at line 40 of file CodeGenTBAA.cpp.
Member Function Documentation
getAccessInfo()
TBAAAccessInfo CodeGenTBAA::getAccessInfo (QualType AccessType)
getAccessInfo - Get TBAA information that describes an access to an object of the given type.
Definition at line 255 of file CodeGenTBAA.cpp.
References clang::CodeGen::TBAAAccessInfo::getIncompleteInfo(), clang::CodeGen::TBAAAccessInfo::getMayAliasInfo(), clang::CharUnits::getQuantity(), getTypeInfo(), clang::ASTContext::getTypeSizeInChars(), clang::Type::isIncompleteType(), and TypeHasMayAlias().
getAccessTagInfo()
llvm::MDNode * CodeGenTBAA::getAccessTagInfo (TBAAAccessInfo Info)
getAccessTagInfo - Get TBAA tag for a given memory access.
Definition at line 396 of file CodeGenTBAA.cpp.
References clang::CodeGen::TBAAAccessInfo::AccessType, clang::CodeGen::TBAAAccessInfo::BaseType, clang::CodeGen::TBAAAccessInfo::isIncomplete(), clang::CodeGen::TBAAAccessInfo::isMayAlias(), clang::CodeGen::TBAAAccessInfo::Offset, and clang::CodeGen::TBAAAccessInfo::Size.
getBaseTypeInfo()
llvm::MDNode * CodeGenTBAA::getBaseTypeInfo (QualType QTy)
getBaseTypeInfo - Get metadata that describes the given base access type.
Return null if the type is not suitable for use in TBAA access tags.
Definition at line 381 of file CodeGenTBAA.cpp.
References clang::ASTContext::getCanonicalType(), clang::CanQual< T >::getTypePtr(), and isValidBaseType().
Referenced by getTypeInfo().
getTBAAStructInfo()
llvm::MDNode * CodeGenTBAA::getTBAAStructInfo (QualType QTy)
getTBAAStructInfo - Get the TBAAStruct MDNode to be used for a memcpy of the given type.
Definition at line 320 of file CodeGenTBAA.cpp.
References clang::ASTContext::getCanonicalType(), clang::CanQual< T >::getTypePtr(), and TypeHasMayAlias().
getTypeInfo()
llvm::MDNode * CodeGenTBAA::getTypeInfo (QualType QTy)
getTypeInfo - Get metadata used to describe accesses to objects of the given type.
Definition at line 225 of file CodeGenTBAA.cpp.
References getBaseTypeInfo(), clang::ASTContext::getCanonicalType(), clang::CanQual< T >::getTypePtr(), isValidBaseType(), and TypeHasMayAlias().
Referenced by getAccessInfo().
getVTablePtrAccessInfo()
TBAAAccessInfo CodeGenTBAA::getVTablePtrAccessInfo (llvm::Type * VTablePtrType)
getVTablePtrAccessInfo - Get the TBAA information that describes an access to a virtual table pointer.
Definition at line 268 of file CodeGenTBAA.cpp.
mergeTBAAInfoForCast()
TBAAAccessInfo CodeGenTBAA::mergeTBAAInfoForCast (TBAAAccessInfo SourceInfo, TBAAAccessInfo TargetInfo)
mergeTBAAInfoForCast - Get merged TBAA information for the purpose of type casts.
Definition at line 424 of file CodeGenTBAA.cpp.
References clang::CodeGen::TBAAAccessInfo::getMayAliasInfo(), and clang::CodeGen::TBAAAccessInfo::isMayAlias().
mergeTBAAInfoForConditionalOperator()
TBAAAccessInfo CodeGenTBAA::mergeTBAAInfoForConditionalOperator (TBAAAccessInfo InfoA, TBAAAccessInfo InfoB)
mergeTBAAInfoForConditionalOperator - Get merged TBAA information for the purpose of conditional operator.
Definition at line 432 of file CodeGenTBAA.cpp.
References clang::CodeGen::TBAAAccessInfo::getMayAliasInfo(), and clang::CodeGen::TBAAAccessInfo::isMayAlias().
mergeTBAAInfoForMemoryTransfer()
TBAAAccessInfo CodeGenTBAA::mergeTBAAInfoForMemoryTransfer (TBAAAccessInfo DestInfo, TBAAAccessInfo SrcInfo)
mergeTBAAInfoForMemoryTransfer - Get merged TBAA information for the purpose of memory transfer calls.
Definition at line 450 of file CodeGenTBAA.cpp.
References clang::CodeGen::TBAAAccessInfo::getMayAliasInfo(), and clang::CodeGen::TBAAAccessInfo::isMayAlias().
The documentation for this class was generated from the following files:
lib/CodeGen/CodeGenTBAA.h
lib/CodeGen/CodeGenTBAA.cpp