clang: clang::BackendConsumer Class Reference
clang::BackendConsumer Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/BackendConsumer.h"
Public Member Functions
BackendConsumer (BackendAction Action, DiagnosticsEngine &Diags, IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS, const HeaderSearchOptions &HeaderSearchOpts, const PreprocessorOptions &PPOpts, const CodeGenOptions &CodeGenOpts, const TargetOptions &TargetOpts, const LangOptions &LangOpts, const std::string &InFile, SmallVector< LinkModule, 4 > LinkModules, std::unique_ptr< raw_pwrite_stream > OS, llvm::LLVMContext &C, CoverageSourceInfo *CoverageInfo=nullptr)
BackendConsumer (BackendAction Action, DiagnosticsEngine &Diags, IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS, const HeaderSearchOptions &HeaderSearchOpts, const PreprocessorOptions &PPOpts, const CodeGenOptions &CodeGenOpts, const TargetOptions &TargetOpts, const LangOptions &LangOpts, llvm::Module *Module, SmallVector< LinkModule, 4 > LinkModules, llvm::LLVMContext &C, CoverageSourceInfo *CoverageInfo=nullptr)
llvm::Module * getModule () const
std::unique_ptr< llvm::Module > takeModule ()
CodeGenerator * getCodeGenerator ()
void HandleCXXStaticMemberVarInstantiation (VarDecl *VD) override
HandleCXXStaticMemberVarInstantiation - Tell the consumer that this.
void Initialize (ASTContext &Ctx) override
Initialize - This is called to initialize the consumer, providing the ASTContext.
bool HandleTopLevelDecl (DeclGroupRef D) override
HandleTopLevelDecl - Handle the specified top-level declaration.
void HandleInlineFunctionDefinition (FunctionDecl *D) override
This callback is invoked each time an inline (method or friend) function definition in a class is completed.
void HandleInterestingDecl (DeclGroupRef D) override
HandleInterestingDecl - Handle the specified interesting declaration.
void HandleTranslationUnit (ASTContext &C) override
HandleTranslationUnit - This method is called when the ASTs for entire translation unit have been parsed.
void HandleTagDeclDefinition (TagDecl *D) override
HandleTagDeclDefinition - This callback is invoked each time a TagDecl (e.g.
void HandleTagDeclRequiredDefinition (const TagDecl *D) override
This callback is invoked the first time each TagDecl is required to be complete.
void CompleteTentativeDefinition (VarDecl *D) override
CompleteTentativeDefinition - Callback invoked at the end of a translation unit to notify the consumer that the given tentative definition should be completed.
void CompleteExternalDeclaration (DeclaratorDecl *D) override
CompleteExternalDeclaration - Callback invoked at the end of a translation unit to notify the consumer that the given external declaration should be completed.
void AssignInheritanceModel (CXXRecordDecl *RD) override
Callback invoked when an MSInheritanceAttr has been attached to a CXXRecordDecl.
void HandleVTable (CXXRecordDecl *RD) override
Callback involved at the end of a translation unit to notify the consumer that a vtable for the given C++ class is required.
bool LinkInModules (llvm::Module *M)
const FullSourceLoc getBestLocationFromDebugLoc (const llvm::DiagnosticInfoWithLocationBase &D, bool &BadDebugInfo, StringRef &Filename, unsigned &Line, unsigned &Column) const
Get the best possible source location to represent a diagnostic that may have associated debug info.
std::optional< FullSourceLoc > getFunctionSourceLocation (const llvm::Function &F) const
void DiagnosticHandlerImpl (const llvm::DiagnosticInfo &DI)
This function is invoked when the backend needs to report something to the user.
bool InlineAsmDiagHandler (const llvm::DiagnosticInfoInlineAsm &D)
Specialized handler for InlineAsm diagnostic.
void SrcMgrDiagHandler (const llvm::DiagnosticInfoSrcMgr &D)
Specialized handler for diagnostics reported using SMDiagnostic.
bool StackSizeDiagHandler (const llvm::DiagnosticInfoStackSize &D)
Specialized handler for StackSize diagnostic.
bool ResourceLimitDiagHandler (const llvm::DiagnosticInfoResourceLimit &D)
Specialized handler for ResourceLimit diagnostic.
void UnsupportedDiagHandler (const llvm::DiagnosticInfoUnsupported &D)
Specialized handler for unsupported backend feature diagnostic.
void EmitOptimizationMessage (const llvm::DiagnosticInfoOptimizationBase &D, unsigned DiagID)
Specialized handlers for optimization remarks.
void OptimizationRemarkHandler (const llvm::DiagnosticInfoOptimizationBase &D)
void OptimizationRemarkHandler (const llvm::OptimizationRemarkAnalysisFPCommute &D)
void OptimizationRemarkHandler (const llvm::OptimizationRemarkAnalysisAliasing &D)
void OptimizationFailureHandler (const llvm::DiagnosticInfoOptimizationFailure &D)
void DontCallDiagHandler (const llvm::DiagnosticInfoDontCall &D)
void MisExpectDiagHandler (const llvm::DiagnosticInfoMisExpect &D)
Specialized handler for misexpect warnings.
void AspectMismatchDiagHandler (const llvm::DiagnosticInfoAspectsMismatch &D)
void SYCLIllegalVirtualCallDiagHandler (const llvm::DiagnosticInfoIllegalVirtualCall &D)
Public Member Functions inherited from clang::ASTConsumer
ASTConsumer ()=default
virtual ~ASTConsumer ()
virtual void HandleCXXImplicitFunctionInstantiation (FunctionDecl *D)
Invoked when a function is implicitly instantiated.
virtual void HandleTopLevelDeclInObjCContainer (DeclGroupRef D)
Handle the specified top-level declaration that occurred inside and ObjC container.
virtual void HandleImplicitImportDecl (ImportDecl *D)
Handle an ImportDecl that was implicitly created due to an inclusion directive.
virtual ASTMutationListener * GetASTMutationListener ()
If the consumer is interested in entities getting modified after their initial creation, it should return a pointer to an ASTMutationListener here.
virtual ASTDeserializationListener * GetASTDeserializationListener ()
If the consumer is interested in entities being deserialized from AST files, it should return a pointer to a ASTDeserializationListener here.
virtual void PrintStats ()
PrintStats - If desired, print any statistics.
virtual bool shouldSkipFunctionBody (Decl *D)
This callback is called for each function if the Parser was initialized with SkipFunctionBodies set to true.
Detailed Description
Definition at line 27 of file BackendConsumer.h.
Constructor & Destructor Documentation
BackendConsumer() [1/2]
clang::BackendConsumer::BackendConsumer (BackendAction Action, DiagnosticsEngine & Diags, IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS, const HeaderSearchOptions & HeaderSearchOpts, const PreprocessorOptions & PPOpts, const CodeGenOptions & CodeGenOpts, const TargetOptions & TargetOpts, const LangOptions & LangOpts, const std::string & InFile, SmallVector< LinkModule, 4 > LinkModules, std::unique_ptr< raw_pwrite_stream > OS, llvm::LLVMContext & C, CoverageSourceInfo * CoverageInfo = nullptr)
BackendConsumer() [2/2]
clang::BackendConsumer::BackendConsumer (BackendAction Action, DiagnosticsEngine & Diags, IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS, const HeaderSearchOptions & HeaderSearchOpts, const PreprocessorOptions & PPOpts, const CodeGenOptions & CodeGenOpts, const TargetOptions & TargetOpts, const LangOptions & LangOpts, llvm::Module * Module, SmallVector< LinkModule, 4 > LinkModules, llvm::LLVMContext & C, CoverageSourceInfo * CoverageInfo = nullptr)
Member Function Documentation
AspectMismatchDiagHandler()
void BackendConsumer::AspectMismatchDiagHandler (const llvm::DiagnosticInfoAspectsMismatch & D)
Definition at line 786 of file CodeGenAction.cpp.
References D, clang::installapi::demangle(), clang::SourceLocation::getFromRawEncoding(), clang::SourceLocation::isValid(), and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
AssignInheritanceModel()
void clang::BackendConsumer::AssignInheritanceModel (CXXRecordDecl * RD) override virtual
Callback invoked when an MSInheritanceAttr has been attached to a CXXRecordDecl.
Reimplemented from clang::ASTConsumer.
Definition at line 386 of file CodeGenAction.cpp.
CompleteExternalDeclaration()
void clang::BackendConsumer::CompleteExternalDeclaration (DeclaratorDecl * D) override virtual
CompleteExternalDeclaration - Callback invoked at the end of a translation unit to notify the consumer that the given external declaration should be completed.
Reimplemented from clang::ASTConsumer.
Definition at line 382 of file CodeGenAction.cpp.
References D.
CompleteTentativeDefinition()
void clang::BackendConsumer::CompleteTentativeDefinition (VarDecl * D) override virtual
CompleteTentativeDefinition - Callback invoked at the end of a translation unit to notify the consumer that the given tentative definition should be completed.
The variable declaration itself will be a tentative definition. If it had an incomplete array type, its type will have already been changed to an array of size 1. However, the declaration remains a tentative definition and has not been modified by the introduction of an implicit zero initializer.
Reimplemented from clang::ASTConsumer.
Definition at line 378 of file CodeGenAction.cpp.
References D.
DiagnosticHandlerImpl()
void BackendConsumer::DiagnosticHandlerImpl (const llvm::DiagnosticInfo & DI)
This function is invoked when the backend needs to report something to the user.
Definition at line 847 of file CodeGenAction.cpp.
References clang::StreamingDiagnostic::AddString(), AspectMismatchDiagHandler(), ComputeDiagID, ComputeDiagRemarkID, DontCallDiagHandler(), InlineAsmDiagHandler(), Loc, MisExpectDiagHandler(), OptimizationFailureHandler(), OptimizationRemarkHandler(), clang::DiagnosticsEngine::Report(), ResourceLimitDiagHandler(), SrcMgrDiagHandler(), StackSizeDiagHandler(), SYCLIllegalVirtualCallDiagHandler(), and UnsupportedDiagHandler().
Referenced by clang::ClangDiagnosticHandler::handleDiagnostics().
DontCallDiagHandler()
void BackendConsumer::DontCallDiagHandler (const llvm::DiagnosticInfoDontCall & D)
Definition at line 771 of file CodeGenAction.cpp.
References D, clang::installapi::demangle(), clang::SourceLocation::getFromRawEncoding(), clang::SourceLocation::isValid(), and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
EmitOptimizationMessage()
void BackendConsumer::EmitOptimizationMessage (const llvm::DiagnosticInfoOptimizationBase & D, unsigned DiagID)
Specialized handlers for optimization remarks.
Note that these handlers only accept remarks and they always handle them.
Definition at line 671 of file CodeGenAction.cpp.
References clang::Column, D, Filename, getBestLocationFromDebugLoc(), Loc, clang::Decl::print(), and clang::DiagnosticsEngine::Report().
Referenced by OptimizationFailureHandler(), and OptimizationRemarkHandler().
getBestLocationFromDebugLoc()
const FullSourceLoc BackendConsumer::getBestLocationFromDebugLoc (const llvm::DiagnosticInfoWithLocationBase & D, bool & BadDebugInfo, StringRef & Filename, unsigned & Line, unsigned & Column) const
Get the best possible source location to represent a diagnostic that may have associated debug info.
Definition at line 582 of file CodeGenAction.cpp.
References clang::Column, D, Filename, clang::FileManager::getFile(), clang::SourceManager::getFileManager(), getFunctionSourceLocation(), clang::Decl::getLocation(), clang::ASTContext::getSourceManager(), clang::SourceLocation::isInvalid(), Loc, clang::DiagnosticsEngine::Report(), and clang::SourceManager::translateFileLineCol().
Referenced by EmitOptimizationMessage(), MisExpectDiagHandler(), and UnsupportedDiagHandler().
getCodeGenerator()
CodeGenerator * clang::BackendConsumer::getCodeGenerator ()
Definition at line 167 of file CodeGenAction.cpp.
Referenced by clang::CodeGenAction::CreateASTConsumer(), and clang::CodeGenAction::getCodeGenerator().
getFunctionSourceLocation()
std::optional< FullSourceLoc > BackendConsumer::getFunctionSourceLocation (const llvm::Function & F) const
Definition at line 625 of file CodeGenAction.cpp.
References llvm::hash_value().
Referenced by getBestLocationFromDebugLoc(), ResourceLimitDiagHandler(), and StackSizeDiagHandler().
getModule()
llvm::Module * clang::BackendConsumer::getModule () const
Definition at line 159 of file CodeGenAction.cpp.
Referenced by HandleTranslationUnit().
HandleCXXStaticMemberVarInstantiation()
void clang::BackendConsumer::HandleCXXStaticMemberVarInstantiation (VarDecl * D) override virtual
HandleCXXStaticMemberVarInstantiation - Tell the consumer that this.
Reimplemented from clang::ASTConsumer.
Definition at line 171 of file CodeGenAction.cpp.
HandleInlineFunctionDefinition()
void clang::BackendConsumer::HandleInlineFunctionDefinition (FunctionDecl * D) override virtual
This callback is invoked each time an inline (method or friend) function definition in a class is completed.
Reimplemented from clang::ASTConsumer.
Definition at line 212 of file CodeGenAction.cpp.
References D, and clang::ASTContext::getSourceManager().
HandleInterestingDecl()
void clang::BackendConsumer::HandleInterestingDecl (DeclGroupRef D) override virtual
HandleInterestingDecl - Handle the specified interesting declaration.
This is called by the AST reader when deserializing things that might interest the consumer. The default implementation forwards to HandleTopLevelDecl.
Reimplemented from clang::ASTConsumer.
Definition at line 225 of file CodeGenAction.cpp.
References D, and HandleTopLevelDecl().
HandleTagDeclDefinition()
void clang::BackendConsumer::HandleTagDeclDefinition (TagDecl * D) override virtual
HandleTagDeclDefinition - This callback is invoked each time a TagDecl (e.g.
struct, union, enum, class) is completed. This allows the client to hack on the type, which can occur at any point in the file (because these can be defined in declspecs).
Reimplemented from clang::ASTConsumer.
Definition at line 367 of file CodeGenAction.cpp.
References D, and clang::ASTContext::getSourceManager().
HandleTagDeclRequiredDefinition()
void clang::BackendConsumer::HandleTagDeclRequiredDefinition (const TagDecl * D) override virtual
This callback is invoked the first time each TagDecl is required to be complete.
Reimplemented from clang::ASTConsumer.
Definition at line 374 of file CodeGenAction.cpp.
References D.
HandleTopLevelDecl()
bool clang::BackendConsumer::HandleTopLevelDecl (DeclGroupRef D) override virtual
HandleTopLevelDecl - Handle the specified top-level declaration.
This is called by the parser to process every top-level Decl*.
Returns
true to continue parsing, or false to abort parsing.
Reimplemented from clang::ASTConsumer.
Definition at line 189 of file CodeGenAction.cpp.
References D, and clang::ASTContext::getSourceManager().
Referenced by HandleInterestingDecl().
HandleTranslationUnit()
void clang::BackendConsumer::HandleTranslationUnit (ASTContext & Ctx) override virtual
HandleTranslationUnit - This method is called when the ASTs for entire translation unit have been parsed.
Reimplemented from clang::ASTConsumer.
Definition at line 268 of file CodeGenAction.cpp.
References clang::TargetOptions::CPU, clang::CodeGenOptions::DiagnosticsMisExpectTolerance, clang::EmbedBitcode(), clang::EmitBackendOutput(), clang::TargetOptions::Features, getModule(), llvm::hash_value(), LinkInModules(), and Loc.
HandleVTable()
void clang::BackendConsumer::HandleVTable (CXXRecordDecl * RD) override virtual
Callback involved at the end of a translation unit to notify the consumer that a vtable for the given C++ class is required.
Parameters
RD The class whose vtable was used.
Reimplemented from clang::ASTConsumer.
Definition at line 390 of file CodeGenAction.cpp.
Initialize()
void clang::BackendConsumer::Initialize (ASTContext & Context) override virtual
Initialize - This is called to initialize the consumer, providing the ASTContext.
Reimplemented from clang::ASTConsumer.
Definition at line 175 of file CodeGenAction.cpp.
InlineAsmDiagHandler()
bool BackendConsumer::InlineAsmDiagHandler (const llvm::DiagnosticInfoInlineAsm & D)
Specialized handler for InlineAsm diagnostic.
Returns
True if the diagnostic has been successfully reported, false otherwise.
Definition at line 527 of file CodeGenAction.cpp.
References clang::StreamingDiagnostic::AddString(), ComputeDiagID, D, clang::SourceLocation::getFromRawEncoding(), clang::SourceLocation::isValid(), Loc, and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
LinkInModules()
bool clang::BackendConsumer::LinkInModules (llvm::Module * M)
Definition at line 232 of file CodeGenAction.cpp.
References clang::Function, and clang::CodeGen::mergeDefaultFunctionDefinitionAttributes().
Referenced by HandleTranslationUnit(), and llvm::LinkInModulesPass::run().
MisExpectDiagHandler()
void BackendConsumer::MisExpectDiagHandler (const llvm::DiagnosticInfoMisExpect & D)
Specialized handler for misexpect warnings.
Note that misexpect remarks are emitted through ORE
Definition at line 826 of file CodeGenAction.cpp.
References clang::Column, D, Filename, getBestLocationFromDebugLoc(), Loc, and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
OptimizationFailureHandler()
void BackendConsumer::OptimizationFailureHandler (const llvm::DiagnosticInfoOptimizationFailure & D)
Definition at line 766 of file CodeGenAction.cpp.
References D, and EmitOptimizationMessage().
Referenced by DiagnosticHandlerImpl().
OptimizationRemarkHandler() [1/3]
void BackendConsumer::OptimizationRemarkHandler (const llvm::DiagnosticInfoOptimizationBase & D)
Definition at line 710 of file CodeGenAction.cpp.
References D, EmitOptimizationMessage(), clang::CodeGenOptions::OptimizationRemark, clang::CodeGenOptions::OptimizationRemarkAnalysis, clang::CodeGenOptions::OptimizationRemarkMissed, and clang::CodeGenOptions::OptRemark::patternMatches().
Referenced by DiagnosticHandlerImpl().
OptimizationRemarkHandler() [2/3]
void BackendConsumer::OptimizationRemarkHandler (const llvm::OptimizationRemarkAnalysisAliasing & D)
Definition at line 754 of file CodeGenAction.cpp.
References D, EmitOptimizationMessage(), clang::CodeGenOptions::OptimizationRemarkAnalysis, and clang::CodeGenOptions::OptRemark::patternMatches().
OptimizationRemarkHandler() [3/3]
void BackendConsumer::OptimizationRemarkHandler (const llvm::OptimizationRemarkAnalysisFPCommute & D)
Definition at line 742 of file CodeGenAction.cpp.
References D, EmitOptimizationMessage(), clang::CodeGenOptions::OptimizationRemarkAnalysis, and clang::CodeGenOptions::OptRemark::patternMatches().
ResourceLimitDiagHandler()
bool BackendConsumer::ResourceLimitDiagHandler (const llvm::DiagnosticInfoResourceLimit & D)
Specialized handler for ResourceLimit diagnostic.
Returns
True if the diagnostic has been successfully reported, false otherwise.
Definition at line 568 of file CodeGenAction.cpp.
References ComputeDiagID, D, clang::installapi::demangle(), getFunctionSourceLocation(), Loc, and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
SrcMgrDiagHandler()
void BackendConsumer::SrcMgrDiagHandler (const llvm::DiagnosticInfoSrcMgr & D)
Specialized handler for diagnostics reported using SMDiagnostic.
Definition at line 468 of file CodeGenAction.cpp.
References clang::StreamingDiagnostic::AddString(), clang::Column, ComputeDiagID, ConvertBackendLocation(), D, clang::SourceLocation::getFromRawEncoding(), clang::SourceLocation::getLocWithOffset(), clang::ASTContext::getSourceManager(), clang::SourceLocation::isValid(), Loc, clang::Decl::print(), Range, and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
StackSizeDiagHandler()
bool BackendConsumer::StackSizeDiagHandler (const llvm::DiagnosticInfoStackSize & D)
Specialized handler for StackSize diagnostic.
Returns
True if the diagnostic has been successfully reported, false otherwise.
Definition at line 552 of file CodeGenAction.cpp.
References D, clang::installapi::demangle(), getFunctionSourceLocation(), Loc, and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
SYCLIllegalVirtualCallDiagHandler()
void BackendConsumer::SYCLIllegalVirtualCallDiagHandler (const llvm::DiagnosticInfoIllegalVirtualCall & D)
Definition at line 804 of file CodeGenAction.cpp.
References D, clang::installapi::demangle(), clang::SourceLocation::getFromRawEncoding(), clang::SourceLocation::isValid(), and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
takeModule()
std::unique_ptr< llvm::Module > clang::BackendConsumer::takeModule ()
Definition at line 163 of file CodeGenAction.cpp.
Referenced by clang::CodeGenAction::EndSourceFileAction().
UnsupportedDiagHandler()
void BackendConsumer::UnsupportedDiagHandler (const llvm::DiagnosticInfoUnsupported & D)
Specialized handler for unsupported backend feature diagnostic.
Definition at line 634 of file CodeGenAction.cpp.
References clang::Column, D, Filename, getBestLocationFromDebugLoc(), Loc, clang::Decl::print(), and clang::DiagnosticsEngine::Report().
Referenced by DiagnosticHandlerImpl().
The documentation for this class was generated from the following files:
lib/CodeGen/BackendConsumer.h
lib/CodeGen/CodeGenAction.cpp