clang: clang::Sema::TemplateCompareNewDeclInfo Class Reference
clang::Sema::TemplateCompareNewDeclInfo Class Reference
#include "clang/Sema/Sema.h"
Public Member Functions
TemplateCompareNewDeclInfo (const NamedDecl *ND)
TemplateCompareNewDeclInfo (const DeclContext *DeclCtx, const DeclContext *LexicalDeclCtx, SourceLocation Loc)
bool isInvalid () const
const NamedDecl * getDecl () const
bool ContainsDecl (const NamedDecl *ND) const
const DeclContext * getLexicalDeclContext () const
const DeclContext * getDeclContext () const
SourceLocation getLocation () const
Detailed Description
Definition at line 9497 of file Sema.h.
Constructor & Destructor Documentation
TemplateCompareNewDeclInfo() [1/2]
clang::Sema::TemplateCompareNewDeclInfo::TemplateCompareNewDeclInfo (const NamedDecl * ND) inline
Definition at line 9504 of file Sema.h.
TemplateCompareNewDeclInfo() [2/2]
clang::Sema::TemplateCompareNewDeclInfo::TemplateCompareNewDeclInfo (const DeclContext * DeclCtx, const DeclContext * LexicalDeclCtx, SourceLocation Loc) inline
Definition at line 9505 of file Sema.h.
Member Function Documentation
ContainsDecl()
bool clang::Sema::TemplateCompareNewDeclInfo::ContainsDecl (const NamedDecl * ND) const inline
Definition at line 9521 of file Sema.h.
Referenced by clang::Sema::AreConstraintExpressionsEqual().
getDecl()
const NamedDecl* clang::Sema::TemplateCompareNewDeclInfo::getDecl () const inline
Definition at line 9519 of file Sema.h.
getDeclContext()
const DeclContext* clang::Sema::TemplateCompareNewDeclInfo::getDeclContext () const inline
Definition at line 9527 of file Sema.h.
References clang::Decl::getDeclContext().
getLexicalDeclContext()
const DeclContext* clang::Sema::TemplateCompareNewDeclInfo::getLexicalDeclContext () const inline
Definition at line 9523 of file Sema.h.
References clang::Decl::getLexicalDeclContext().
Referenced by clang::Sema::AreConstraintExpressionsEqual().
getLocation()
SourceLocation clang::Sema::TemplateCompareNewDeclInfo::getLocation () const inline
Definition at line 9531 of file Sema.h.
References clang::Decl::getLocation().
isInvalid()
bool clang::Sema::TemplateCompareNewDeclInfo::isInvalid () const inline
Definition at line 9517 of file Sema.h.
Referenced by clang::Sema::AreConstraintExpressionsEqual().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h