clang: clang::edit::Commit Class Reference
clang::edit::Commit Class Reference
#include "clang/Edit/Commit.h"
Classes
struct Edit
Public Types
enum EditKind { Act_Insert , Act_InsertFromRange , Act_Remove }
using edit_iterator = SmallVectorImpl< Edit >::const_iterator
Public Member Functions
Commit (EditedSource &Editor)
Commit (const SourceManager &SM, const LangOptions &LangOpts, const PPConditionalDirectiveRecord *PPRec=nullptr)
bool isCommitable () const
bool insert (SourceLocation loc, StringRef text, bool afterToken=false, bool beforePreviousInsertions=false)
bool insertAfterToken (SourceLocation loc, StringRef text, bool beforePreviousInsertions=false)
bool insertBefore (SourceLocation loc, StringRef text)
bool insertFromRange (SourceLocation loc, CharSourceRange range, bool afterToken=false, bool beforePreviousInsertions=false)
bool insertWrap (StringRef before, CharSourceRange range, StringRef after)
bool remove (CharSourceRange range)
bool replace (CharSourceRange range, StringRef text)
bool replaceWithInner (CharSourceRange range, CharSourceRange innerRange)
bool replaceText (SourceLocation loc, StringRef text, StringRef replacementText)
bool insertFromRange (SourceLocation loc, SourceRange TokenRange, bool afterToken=false, bool beforePreviousInsertions=false)
bool insertWrap (StringRef before, SourceRange TokenRange, StringRef after)
bool remove (SourceRange TokenRange)
bool replace (SourceRange TokenRange, StringRef text)
bool replaceWithInner (SourceRange TokenRange, SourceRange TokenInnerRange)
edit_iterator edit_begin () const
edit_iterator edit_end () const
Detailed Description
Definition at line 29 of file Commit.h.
Member Typedef Documentation
edit_iterator
using clang::edit::Commit::edit_iterator = SmallVectorImpl<Edit>::const_iterator
Definition at line 119 of file Commit.h.
Member Enumeration Documentation
EditKind
enum clang::edit::Commit::EditKind
Enumerator
Act_Insert
Act_InsertFromRange
Act_Remove
Definition at line 31 of file Commit.h.
Constructor & Destructor Documentation
Commit() [1/2]
Commit::Commit (EditedSource & Editor) explicit
Definition at line 43 of file Commit.cpp.
Commit() [2/2]
clang::edit::Commit::Commit (const SourceManager & SM, const LangOptions & LangOpts, const PPConditionalDirectiveRecord * PPRec = nullptr) inline
Definition at line 64 of file Commit.h.
Member Function Documentation
edit_begin()
edit_iterator clang::edit::Commit::edit_begin () const inline
Definition at line 121 of file Commit.h.
edit_end()
edit_iterator clang::edit::Commit::edit_end () const inline
Definition at line 122 of file Commit.h.
insert()
bool Commit::insert (SourceLocation loc, StringRef text, bool afterToken = false, bool beforePreviousInsertions = false)
Definition at line 48 of file Commit.cpp.
References clang::comments::tok::text.
Referenced by doRewriteToUTF8StringBoxedExpressionHelper(), clang::FixItRewriter::HandleDiagnostic(), insertAfterToken(), insertBefore(), insertWrap(), rewriteToBoolLiteral(), rewriteToCharLiteral(), and rewriteToNumberLiteral().
insertAfterToken()
bool clang::edit::Commit::insertAfterToken (SourceLocation loc, StringRef text, bool beforePreviousInsertions = false) inline
Definition at line 73 of file Commit.h.
References insert(), and clang::comments::tok::text.
Referenced by insertWrap(), rewriteToDictionaryLiteral(), and rewriteToObjCInterfaceDecl().
insertBefore()
bool clang::edit::Commit::insertBefore (SourceLocation loc, StringRef text) inline
Definition at line 78 of file Commit.h.
References insert(), and clang::comments::tok::text.
Referenced by doRewriteToUTF8StringBoxedExpressionHelper(), objectifyExpr(), rewriteToDictionaryLiteral(), rewriteToDictionarySubscriptSet(), and rewriteToNumericBoxedExpression().
insertFromRange() [1/2]
bool Commit::insertFromRange (SourceLocation loc, CharSourceRange range, bool afterToken = false, bool beforePreviousInsertions = false)
Definition at line 64 of file Commit.cpp.
References clang::PPConditionalDirectiveRecord::areInDifferentConditionalDirectiveRegion(), and clang::transformer::range().
Referenced by clang::FixItRewriter::HandleDiagnostic(), insertFromRange(), rewriteToDictionaryLiteral(), rewriteToDictionarySubscriptSet(), and rewriteToNSEnumDecl().
insertFromRange() [2/2]
bool clang::edit::Commit::insertFromRange (SourceLocation loc, SourceRange TokenRange, bool afterToken = false, bool beforePreviousInsertions = false) inline
Definition at line 95 of file Commit.h.
References clang::CharSourceRange::getTokenRange(), and insertFromRange().
insertWrap() [1/2]
bool Commit::insertWrap (StringRef before, CharSourceRange range, StringRef after)
Definition at line 103 of file Commit.cpp.
References clang::transformer::after(), clang::transformer::before(), insert(), insertAfterToken(), and clang::transformer::range().
Referenced by doRewriteToUTF8StringBoxedExpressionHelper(), insertWrap(), maybePutParensOnReceiver(), objectifyExpr(), rewriteToArrayLiteral(), rewriteToArraySubscriptSet(), rewriteToDictionaryLiteral(), rewriteToNumericBoxedExpression(), and rewriteToSubscriptGetCommon().
insertWrap() [2/2]
bool clang::edit::Commit::insertWrap (StringRef before, SourceRange TokenRange, StringRef after) inline
Definition at line 102 of file Commit.h.
References clang::transformer::after(), clang::transformer::before(), clang::CharSourceRange::getTokenRange(), and insertWrap().
isCommitable()
bool clang::edit::Commit::isCommitable () const inline
Definition at line 68 of file Commit.h.
Referenced by clang::FixItRewriter::HandleDiagnostic().
remove() [1/2]
bool Commit::remove (CharSourceRange range)
Definition at line 91 of file Commit.cpp.
References clang::transformer::range().
Referenced by clang::FixItRewriter::HandleDiagnostic(), remove(), replace(), rewriteToDictionaryLiteral(), rewriteToNSEnumDecl(), and rewriteToNSMacroDecl().
remove() [2/2]
bool clang::edit::Commit::remove (SourceRange TokenRange) inline
Definition at line 106 of file Commit.h.
References clang::CharSourceRange::getTokenRange(), and remove().
replace() [1/2]
bool Commit::replace (CharSourceRange range, StringRef text)
Definition at line 116 of file Commit.cpp.
References clang::transformer::range(), remove(), and clang::comments::tok::text.
Referenced by clang::FixItRewriter::HandleDiagnostic(), replace(), ReplaceWithClasstype(), ReplaceWithInstancetype(), rewriteToArrayLiteral(), rewriteToDictionaryLiteral(), rewriteToNSEnumDecl(), and rewriteToNSMacroDecl().
replace() [2/2]
bool clang::edit::Commit::replace (SourceRange TokenRange, StringRef text) inline
Definition at line 110 of file Commit.h.
References clang::CharSourceRange::getTokenRange(), replace(), and clang::comments::tok::text.
replaceText()
bool Commit::replaceText (SourceLocation loc, StringRef text, StringRef replacementText)
Definition at line 165 of file Commit.cpp.
References clang::comments::tok::text.
replaceWithInner() [1/2]
bool Commit::replaceWithInner (CharSourceRange range, CharSourceRange innerRange)
Definition at line 132 of file Commit.cpp.
References clang::CharSourceRange::getEnd(), clang::edit::FileOffset::getFID(), clang::edit::FileOffset::getOffset(), clang::edit::FileOffset::getWithOffset(), and clang::transformer::range().
Referenced by doRewriteToUTF8StringBoxedExpressionHelper(), replaceWithInner(), clang::edit::rewriteObjCRedundantCallWithLiteral(), rewriteToArrayLiteral(), rewriteToArraySubscriptSet(), rewriteToBoolLiteral(), rewriteToCharLiteral(), rewriteToDictionaryLiteral(), rewriteToDictionarySubscriptSet(), rewriteToNumberLiteral(), rewriteToNumericBoxedExpression(), and rewriteToSubscriptGetCommon().
replaceWithInner() [2/2]
bool clang::edit::Commit::replaceWithInner (SourceRange TokenRange, SourceRange TokenInnerRange) inline
Definition at line 114 of file Commit.h.
References clang::CharSourceRange::getTokenRange(), and replaceWithInner().
The documentation for this class was generated from the following files:
include/clang/Edit/Commit.h
lib/Edit/Commit.cpp