clang: clang::tooling::AllTUsToolExecutor Class Reference
clang::tooling::AllTUsToolExecutor Class Reference
Executes given frontend actions on all files/TUs in the compilation database.
#include "clang/Tooling/AllTUsExecution.h"
Public Member Functions
AllTUsToolExecutor (const CompilationDatabase &Compilations, unsigned ThreadCount, std::shared_ptr< PCHContainerOperations > PCHContainerOps=std::make_shared< PCHContainerOperations >())
Init with CompilationDatabase.
AllTUsToolExecutor (CommonOptionsParser Options, unsigned ThreadCount, std::shared_ptr< PCHContainerOperations > PCHContainerOps=std::make_shared< PCHContainerOperations >())
Init with CommonOptionsParser.
StringRef getExecutorName () const override
Returns the name of a specific executor.
llvm::Error execute (llvm::ArrayRef< std::pair< std::unique_ptr< FrontendActionFactory >, ArgumentsAdjuster >> Actions) override
Executes each action with a corresponding arguments adjuster.
ExecutionContext * getExecutionContext () override
Returns a reference to the execution context.
ToolResults * getToolResults () override
Returns a reference to the result container.
void mapVirtualFile (StringRef FilePath, StringRef Content) override
Map a virtual file to be used while running the tool.
virtual llvm::Error execute (llvm::ArrayRef< std::pair< std::unique_ptr< FrontendActionFactory >, ArgumentsAdjuster >> Actions)=0
Executes each action with a corresponding arguments adjuster.
llvm::Error execute (std::unique_ptr< FrontendActionFactory > Action)
Convenient functions for the above execute.
llvm::Error execute (std::unique_ptr< FrontendActionFactory > Action, ArgumentsAdjuster Adjuster)
Executes an action with an argument adjuster.
Public Member Functions inherited from clang::tooling::ToolExecutor
virtual ~ToolExecutor ()
llvm::Error execute (std::unique_ptr< FrontendActionFactory > Action)
Convenient functions for the above execute.
llvm::Error execute (std::unique_ptr< FrontendActionFactory > Action, ArgumentsAdjuster Adjuster)
Executes an action with an argument adjuster.
Static Public Attributes
static const char * ExecutorName = "AllTUsToolExecutor"
Detailed Description
Executes given frontend actions on all files/TUs in the compilation database.
Definition at line 25 of file AllTUsExecution.h.
Constructor & Destructor Documentation
AllTUsToolExecutor() [1/2]
clang::tooling::AllTUsToolExecutor::AllTUsToolExecutor (const CompilationDatabase & Compilations, unsigned ThreadCount, std::shared_ptr< PCHContainerOperations > PCHContainerOps = std::make_shared<PCHContainerOperations>())
Init with CompilationDatabase.
This uses ThreadCount threads to exececute the actions on all files in parallel. If ThreadCount is 0, this uses llvm::hardware_concurrency.
Definition at line 64 of file AllTUsExecution.cpp.
AllTUsToolExecutor() [2/2]
clang::tooling::AllTUsToolExecutor::AllTUsToolExecutor (CommonOptionsParser Options, unsigned ThreadCount, std::shared_ptr< PCHContainerOperations > PCHContainerOps = std::make_shared<PCHContainerOperations>())
Init with CommonOptionsParser.
This is expected to be used by createExecutorFromCommandLineArgs based on commandline options.
The executor takes ownership of Options.
Definition at line 70 of file AllTUsExecution.cpp.
Member Function Documentation
execute() [1/4]
llvm::Error clang::tooling::AllTUsToolExecutor::execute (llvm::ArrayRef< std::pair< std::unique_ptr< FrontendActionFactory >, ArgumentsAdjuster >> Actions) override virtual
Executes each action with a corresponding arguments adjuster.
Implements clang::tooling::ToolExecutor.
Definition at line 78 of file AllTUsExecution.cpp.
References clang::File, clang::tooling::Filter, clang::tooling::CompilationDatabase::getAllFiles(), clang::tooling::make_string_error(), and string().
execute() [2/4]
virtual llvm::Error clang::tooling::ToolExecutor::execute
Executes each action with a corresponding arguments adjuster.
execute() [3/4]
llvm::Error clang::tooling::ToolExecutor::execute
Convenient functions for the above execute.
Definition at line 43 of file Execution.cpp.
execute() [4/4]
llvm::Error clang::tooling::ToolExecutor::execute
Executes an action with an argument adjuster.
Definition at line 47 of file Execution.cpp.
getExecutionContext()
ExecutionContext* clang::tooling::AllTUsToolExecutor::getExecutionContext () inline override virtual
Returns a reference to the execution context.
This should be passed to tool callbacks, and tool callbacks should report results via the returned context.
Implements clang::tooling::ToolExecutor.
Definition at line 54 of file AllTUsExecution.h.
getExecutorName()
StringRef clang::tooling::AllTUsToolExecutor::getExecutorName () const inline override virtual
Returns the name of a specific executor.
Implements clang::tooling::ToolExecutor.
Definition at line 45 of file AllTUsExecution.h.
References ExecutorName.
getToolResults()
ToolResults* clang::tooling::AllTUsToolExecutor::getToolResults () inline override virtual
Returns a reference to the result container.
NOTE: This should only be used after the execution finishes. Tool callbacks should report results via ExecutionContext instead.
Implements clang::tooling::ToolExecutor.
Definition at line 56 of file AllTUsExecution.h.
mapVirtualFile()
void clang::tooling::AllTUsToolExecutor::mapVirtualFile (StringRef FilePath, StringRef Content) inline override virtual
Map a virtual file to be used while running the tool.
Parameters
FilePath The path at which the content will be mapped.
Content A buffer of the file's content.
Implements clang::tooling::ToolExecutor.
Definition at line 58 of file AllTUsExecution.h.
References string().
Member Data Documentation
ExecutorName
const char * clang::tooling::AllTUsToolExecutor::ExecutorName = "AllTUsToolExecutor" static
Definition at line 27 of file AllTUsExecution.h.
Referenced by getExecutorName().
The documentation for this class was generated from the following files:
include/clang/Tooling/AllTUsExecution.h
lib/Tooling/AllTUsExecution.cpp