clang: clang::CFGImplicitDtor Class Reference
clang::CFGImplicitDtor Class Reference
Represents C++ object destructor implicitly generated by compiler on various occasions.
#include "clang/Analysis/CFG.h"
Public Member Functions
const CXXDestructorDecl * getDestructorDecl (ASTContext &astContext) const
bool isNoReturn (ASTContext &astContext) const
Public Member Functions inherited from clang::CFGElement
template<typename T >
T castAs () const
Convert to the specified CFGElement type, asserting that this CFGElement is of the desired type.
template<typename T >
Optional< T > getAs () const
Convert to the specified CFGElement type, returning None if this CFGElement is not of the desired type.
Kind getKind () const
void dumpToStream (llvm::raw_ostream &OS) const
void dump () const
Protected Member Functions
CFGImplicitDtor ()=default
CFGImplicitDtor (Kind kind, const void *data1, const void *data2=nullptr)
Protected Member Functions inherited from clang::CFGElement
CFGElement (Kind kind, const void *Ptr1, const void *Ptr2=nullptr)
CFGElement ()=default
Friends
class CFGElement
Additional Inherited Members
Public Types inherited from clang::CFGElement
enum Kind {
Initializer, ScopeBegin, ScopeEnd, NewAllocator,
LifetimeEnds, LoopExit, Statement, Constructor,
CXXRecordTypedCall, STMT_BEGIN = Statement, STMT_END = CXXRecordTypedCall, AutomaticObjectDtor,
DeleteDtor, BaseDtor, MemberDtor, TemporaryDtor,
DTOR_BEGIN = AutomaticObjectDtor, DTOR_END = TemporaryDtor
}
Protected Attributes inherited from clang::CFGElement
llvm::PointerIntPair< void *, 2 > Data1
llvm::PointerIntPair< void *, 2 > Data2
Detailed Description
Represents C++ object destructor implicitly generated by compiler on various occasions.
Definition at line 364 of file CFG.h.
Constructor & Destructor Documentation
CFGImplicitDtor() [1/2]
clang::CFGImplicitDtor::CFGImplicitDtor () protected default
CFGImplicitDtor() [2/2]
clang::CFGImplicitDtor::CFGImplicitDtor (Kind kind, const void * data1, const void * data2 = nullptr) inline protected
Definition at line 368 of file CFG.h.
References clang::CFGElement::DTOR_BEGIN, and clang::CFGElement::DTOR_END.
Member Function Documentation
getDestructorDecl()
const CXXDestructorDecl * CFGImplicitDtor::getDestructorDecl (ASTContext & astContext) const
Definition at line 5110 of file CFG.cpp.
References clang::ast_matchers::arrayType, clang::CFGElement::AutomaticObjectDtor, clang::CFGElement::BaseDtor, clang::CFGElement::Constructor, clang::CFGElement::CXXRecordTypedCall, clang::CFGElement::DeleteDtor, clang::ASTContext::getAsArrayType(), clang::Type::getAsCXXRecordDecl(), clang::ASTContext::getBaseElementType(), clang::CXXDeleteExpr::getDestroyedType(), clang::CXXTemporary::getDestructor(), clang::CXXRecordDecl::getDestructor(), clang::CFGElement::getKind(), clang::QualType::getNonReferenceType(), getReferenceInitTemporaryType(), clang::CXXBindTemporaryExpr::getTemporary(), clang::CFGElement::Initializer, clang::Type::isReferenceType(), clang::CFGElement::LifetimeEnds, clang::CFGElement::LoopExit, clang::CFGElement::MemberDtor, clang::CFGElement::NewAllocator, clang::CFGElement::ScopeBegin, clang::CFGElement::ScopeEnd, clang::CFGElement::Statement, clang::CFGElement::TemporaryDtor, and clang::dataflow::var().
Referenced by clang::ento::ExprEngine::ProcessTemporaryDtor(), clang::consumed::ConsumedAnalyzer::run(), and clang::threadSafety::CFGWalker::walk().
isNoReturn()
bool clang::CFGImplicitDtor::isNoReturn (ASTContext & astContext) const
Friends And Related Function Documentation
CFGElement
friend class CFGElement friend
Definition at line 378 of file CFG.h.
The documentation for this class was generated from the following files:
include/clang/Analysis/CFG.h
lib/Analysis/CFG.cpp