clang: clang::CodeGen::LValue Class Reference
clang::CodeGen::LValue Class Reference
LValue - This represents an lvalue references.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGValue.h"
Public Member Functions
bool isSimple () const
bool isVectorElt () const
bool isBitField () const
bool isExtVectorElt () const
bool isGlobalReg () const
bool isMatrixElt () const
bool isVolatileQualified () const
bool isRestrictQualified () const
unsigned getVRQualifiers () const
QualType getType () const
Qualifiers::ObjCLifetime getObjCLifetime () const
bool isObjCIvar () const
void setObjCIvar (bool Value)
bool isObjCArray () const
void setObjCArray (bool Value)
bool isNonGC () const
void setNonGC (bool Value)
bool isGlobalObjCRef () const
void setGlobalObjCRef (bool Value)
bool isThreadLocalRef () const
void setThreadLocalRef (bool Value)
ARCPreciseLifetime_t isARCPreciseLifetime () const
void setARCPreciseLifetime (ARCPreciseLifetime_t value)
bool isNontemporal () const
void setNontemporal (bool Value)
bool isObjCWeak () const
bool isObjCStrong () const
bool isVolatile () const
Expr * getBaseIvarExp () const
void setBaseIvarExp (Expr *V)
TBAAAccessInfo getTBAAInfo () const
void setTBAAInfo (TBAAAccessInfo Info)
const Qualifiers & getQuals () const
Qualifiers & getQuals ()
LangAS getAddressSpace () const
CharUnits getAlignment () const
void setAlignment (CharUnits A)
LValueBaseInfo getBaseInfo () const
void setBaseInfo (LValueBaseInfo Info)
KnownNonNull_t isKnownNonNull () const
LValue setKnownNonNull ()
llvm::Value * getPointer (CodeGenFunction &CGF) const
llvm::Value * emitRawPointer (CodeGenFunction &CGF) const
Address getAddress (CodeGenFunction &CGF) const
void setAddress (Address address)
Address getVectorAddress () const
llvm::Value * getRawVectorPointer (CodeGenFunction &CGF) const
llvm::Value * getVectorPointer () const
llvm::Value * getVectorIdx () const
Address getMatrixAddress () const
llvm::Value * getMatrixPointer () const
llvm::Value * getMatrixIdx () const
Address getExtVectorAddress () const
llvm::Value * getRawExtVectorPointer (CodeGenFunction &CGF) const
llvm::Constant * getExtVectorElts () const
Address getBitFieldAddress () const
llvm::Value * getRawBitFieldPointer (CodeGenFunction &CGF) const
const CGBitFieldInfo & getBitFieldInfo () const
llvm::Value * getGlobalReg () const
RValue asAggregateRValue (CodeGenFunction &CGF) const
Static Public Member Functions
static LValue MakeAddr (Address Addr, QualType type, ASTContext &Context, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo)
static LValue MakeVectorElt (Address vecAddress, llvm::Value *Idx, QualType type, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo)
static LValue MakeExtVectorElt (Address Addr, llvm::Constant *Elts, QualType type, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo)
static LValue MakeBitfield (Address Addr, const CGBitFieldInfo &Info, QualType type, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo)
Create a new object to represent a bit-field access.
static LValue MakeGlobalReg (llvm::Value *V, CharUnits alignment, QualType type)
static LValue MakeMatrixElt (Address matAddress, llvm::Value *Idx, QualType type, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo)
Detailed Description
LValue - This represents an lvalue references.
Because C/C++ allow bitfields, this is not a simple LLVM pointer, it may be a pointer plus a bitrange.
Definition at line 181 of file CGValue.h.
Member Function Documentation
asAggregateRValue()
RValue clang::CodeGen::LValue::asAggregateRValue (CodeGenFunction & CGF) const inline
Definition at line 506 of file CGValue.h.
References getAddress(), clang::CodeGen::RValue::getAggregate(), and isVolatileQualified().
Referenced by clang::CodeGen::CodeGenFunction::convertTempToRValue(), and clang::CodeGen::CodeGenFunction::EmitRValueForField().
emitRawPointer()
llvm::Value* clang::CodeGen::LValue::emitRawPointer (CodeGenFunction & CGF) const inline
Definition at line 365 of file CGValue.h.
References Addr, clang::CodeGen::Address::emitRawPointer(), isSimple(), and clang::CodeGen::Address::isValid().
Referenced by clang::CodeGen::CodeGenFunction::EmitTypeCheck().
getAddress()
Address clang::CodeGen::LValue::getAddress (CodeGenFunction & CGF) const inline
Definition at line 370 of file CGValue.h.
References Addr.
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), asAggregateRValue(), clang::CodeGen::CodeGenFunction::callCStructCopyAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructCopyConstructor(), clang::CodeGen::CodeGenFunction::callCStructDefaultConstructor(), clang::CodeGen::CodeGenFunction::callCStructDestructor(), clang::CodeGen::CodeGenFunction::callCStructMoveAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructMoveConstructor(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::CodeGen::CallArg::copyInto(), clang::CodeGen::CodeGenFunction::defaultInitNonTrivialCStructVar(), drillIntoBlockVariable(), clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrong(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitArrayToPointerDecay(), clang::CodeGen::CodeGenFunction::EmitAtomicCompareExchange(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitCountedByFieldExpr(), clang::CodeGen::CodeGenFunction::EmitCXXMemberPointerCallExpr(), clang::CodeGen::CodeGenFunction::EmitCXXPseudoDestructorExpr(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), clang::CodeGen::CodeGenFunction::EmitInitializerForField(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), EmitLoadOfMatrixLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfReference(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr(), EmitMemberInitializer(), clang::CodeGen::CodeGenFunction::EmitMSVAListRef(), clang::CodeGen::CodeGenFunction::EmitObjCIsaExpr(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), emitOMPArraySectionBase(), clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr(), emitOMPAtomicCompareExpr(), clang::CodeGen::CodeGenFunction::EmitOMPFirstprivateClause(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), emitOutlinedFunctionPrologue(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::CodeGenFunction::EmitPointerToDataMemberBinaryExpr(), EmitPointerWithAlignment(), emitPrivatesInit(), clang::CodeGen::CodeGenFunction::EmitScalarInit(), clang::CodeGen::CodeGenFunction::EmitSimpleOMPExecutableDirective(), EmitStoreOfMatrixScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), EmitTypeidFromVTable(), clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue(), clang::CodeGen::CodeGenFunction::EmitVAListRef(), emitWriteback(), emitWritebackArg(), clang::CodeGen::AggValueSlot::forLValue(), clang::CodeGen::CodeGenFunction::generateObjCGetterBody(), clang::CodeGen::CodeGenFunction::generateObjCSetterBody(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), getPointerAndSize(), loadToBegin(), tryEmitARCCopyWeakInit(), and tryEmitARCRetainLoadOfScalar().
getAddressSpace()
LangAS clang::CodeGen::LValue::getAddressSpace () const inline
Definition at line 344 of file CGValue.h.
References clang::Qualifiers::getAddressSpace().
Referenced by clang::CodeGen::CodeGenFunction::EmitCall().
getAlignment()
CharUnits clang::CodeGen::LValue::getAlignment () const inline
Definition at line 346 of file CGValue.h.
References Addr, and clang::CodeGen::Address::getAlignment().
Referenced by clang::CodeGen::CodeGenFunction::EmitARCStoreStrong(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalFinalUpdate(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), and clang::CodeGen::CGOpenMPRuntime::getTaskReductionItem().
getBaseInfo()
LValueBaseInfo clang::CodeGen::LValue::getBaseInfo () const inline
Definition at line 349 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitArrayToPointerDecay(), EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), emitOMPArraySectionBase(), clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr(), EmitPointerWithAlignment(), EmitStoreOfMatrixScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue(), and loadToBegin().
getBaseIvarExp()
Expr* clang::CodeGen::LValue::getBaseIvarExp () const inline
Definition at line 335 of file CGValue.h.
getBitFieldAddress()
Address clang::CodeGen::LValue::getBitFieldAddress () const inline
Definition at line 423 of file CGValue.h.
References Addr, and isBitField().
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfBitfieldLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue().
getBitFieldInfo()
const CGBitFieldInfo& clang::CodeGen::LValue::getBitFieldInfo () const inline
Definition at line 432 of file CGValue.h.
References BitFieldInfo, and isBitField().
Referenced by EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitBinaryOperatorLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfBitfieldLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue().
getExtVectorAddress()
Address clang::CodeGen::LValue::getExtVectorAddress () const inline
Definition at line 409 of file CGValue.h.
References Addr, and isExtVectorElt().
Referenced by clang::CodeGen::CodeGenFunction::EmitExtVectorElementLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfExtVectorElementLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughExtVectorComponentLValue().
getExtVectorElts()
llvm::Constant* clang::CodeGen::LValue::getExtVectorElts () const inline
Definition at line 417 of file CGValue.h.
References isExtVectorElt(), and VectorElts.
Referenced by EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitExtVectorElementLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfExtVectorElementLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughExtVectorComponentLValue().
getGlobalReg()
llvm::Value* clang::CodeGen::LValue::getGlobalReg () const inline
Definition at line 438 of file CGValue.h.
References isGlobalReg(), and V.
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfGlobalRegLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughGlobalRegLValue().
getMatrixAddress()
Address clang::CodeGen::LValue::getMatrixAddress () const inline
Definition at line 395 of file CGValue.h.
References Addr, and isMatrixElt().
getMatrixIdx()
llvm::Value* clang::CodeGen::LValue::getMatrixIdx () const inline
Definition at line 403 of file CGValue.h.
References isMatrixElt(), and VectorIdx.
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue().
getMatrixPointer()
llvm::Value* clang::CodeGen::LValue::getMatrixPointer () const inline
Definition at line 399 of file CGValue.h.
References Addr, clang::CodeGen::Address::getBasePointer(), and isMatrixElt().
getObjCLifetime()
Qualifiers::ObjCLifetime clang::CodeGen::LValue::getObjCLifetime () const inline
Definition at line 296 of file CGValue.h.
References clang::Qualifiers::getObjCLifetime().
Referenced by clang::CodeGen::CodeGenFunction::EmitScalarInit(), emitWriteback(), and emitWritebackArg().
getPointer()
llvm::Value* clang::CodeGen::LValue::getPointer (CodeGenFunction & CGF) const inline
Definition at line 361 of file CGValue.h.
References Addr, clang::CodeGen::Address::getBasePointer(), and isSimple().
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), clang::CodeGen::CodeGenFunction::EmitCallee(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitCountedByFieldExpr(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CGOpenMPRuntime::emitErrorCall(), clang::CodeGen::CodeGenFunction::EmitObjCIvarRefLValue(), clang::CodeGen::CodeGenFunction::EmitReferenceBindingToExpr(), clang::CodeGen::CodeGenFunction::EmitRValueForField(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), emitStructSetterCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), getPointerAndSize(), clang::CodeGen::CGOpenMPRuntime::getTaskReductionItem(), clang::CodeGen::CGOpenMPRuntime::getThreadID(), and clang::CodeGen::CodeGenFunction::StartFunction().
getQuals() [1/2]
Qualifiers& clang::CodeGen::LValue::getQuals () inline
Definition at line 342 of file CGValue.h.
getQuals() [2/2]
const Qualifiers& clang::CodeGen::LValue::getQuals () const inline
Definition at line 341 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue(), clang::CodeGen::AggValueSlot::forLValue(), and clang::CodeGen::CodeGenFunction::generateObjCGetterBody().
getRawBitFieldPointer()
llvm::Value* clang::CodeGen::LValue::getRawBitFieldPointer (CodeGenFunction & CGF) const inline
Definition at line 427 of file CGValue.h.
References Addr, clang::CodeGen::Address::emitRawPointer(), and isBitField().
getRawExtVectorPointer()
llvm::Value* clang::CodeGen::LValue::getRawExtVectorPointer (CodeGenFunction & CGF) const inline
Definition at line 413 of file CGValue.h.
References Addr, clang::CodeGen::Address::emitRawPointer(), and isExtVectorElt().
getRawVectorPointer()
llvm::Value* clang::CodeGen::LValue::getRawVectorPointer (CodeGenFunction & CGF) const inline
Definition at line 382 of file CGValue.h.
References Addr, clang::CodeGen::Address::emitRawPointer(), and isVectorElt().
getTBAAInfo()
TBAAAccessInfo clang::CodeGen::LValue::getTBAAInfo () const inline
Definition at line 338 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfReference(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), EmitPointerWithAlignment(), emitPrivatesInit(), EmitStoreOfMatrixScalar(), and clang::CodeGen::CodeGenFunction::EmitStoreOfScalar().
getType()
QualType clang::CodeGen::LValue::getType () const inline
Definition at line 294 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::callCStructCopyAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructCopyConstructor(), clang::CodeGen::CodeGenFunction::callCStructDefaultConstructor(), clang::CodeGen::CodeGenFunction::callCStructDestructor(), clang::CodeGen::CodeGenFunction::callCStructMoveAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructMoveConstructor(), clang::CodeGen::CodeGenFunction::defaultInitNonTrivialCStructVar(), clang::CodeGen::CodeGenFunction::EmitAggregateCopyCtor(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrong(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitAtomicLoad(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::EmitExtVectorElementLValue(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalFinalUpdate(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), clang::CodeGen::CodeGenFunction::EmitLoadOfBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfExtVectorElementLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfGlobalRegLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), EmitLoadOfMatrixLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfReference(), clang::CodeGen::CodeGenFunction::EmitLoadOfReferenceLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitNullabilityCheck(), clang::CodeGen::CodeGenFunction::emitOMPSimpleStore(), emitOutlinedFunctionPrologue(), emitPreserveStructAccess(), emitPrivatesInit(), clang::CodeGen::CodeGenFunction::EmitScalarInit(), EmitStoreOfMatrixScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughExtVectorComponentLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughGlobalRegLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue(), loadToBegin(), and clang::CodeGen::CodeGenFunction::LValueIsSuitableForInlineAtomic().
getVectorAddress()
Address clang::CodeGen::LValue::getVectorAddress () const inline
Definition at line 378 of file CGValue.h.
References Addr, and isVectorElt().
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue().
getVectorIdx()
llvm::Value* clang::CodeGen::LValue::getVectorIdx () const inline
Definition at line 390 of file CGValue.h.
References isVectorElt(), and VectorIdx.
Referenced by EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue().
getVectorPointer()
llvm::Value* clang::CodeGen::LValue::getVectorPointer () const inline
Definition at line 386 of file CGValue.h.
References Addr, clang::CodeGen::Address::getBasePointer(), and isVectorElt().
getVRQualifiers()
unsigned clang::CodeGen::LValue::getVRQualifiers () const inline
Definition at line 290 of file CGValue.h.
References clang::Qualifiers::getCVRQualifiers().
Referenced by clang::CodeGen::CodeGenFunction::EmitLValueForField().
isARCPreciseLifetime()
ARCPreciseLifetime_t clang::CodeGen::LValue::isARCPreciseLifetime () const inline
Definition at line 315 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitARCStoreStrong(), and emitWriteback().
isBitField()
bool clang::CodeGen::LValue::isBitField () const inline
Definition at line 283 of file CGValue.h.
Referenced by EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitBinaryOperatorLValue(), clang::CodeGen::CodeGenFunction::EmitCheckedLValue(), clang::CodeGen::CodeGenFunction::EmitRValueForField(), getBitFieldAddress(), getBitFieldInfo(), and getRawBitFieldPointer().
isExtVectorElt()
bool clang::CodeGen::LValue::isExtVectorElt () const inline
Definition at line 284 of file CGValue.h.
Referenced by EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), getExtVectorAddress(), getExtVectorElts(), and getRawExtVectorPointer().
isGlobalObjCRef()
bool clang::CodeGen::LValue::isGlobalObjCRef () const inline
Definition at line 309 of file CGValue.h.
Referenced by setObjCGCLValueClass().
isGlobalReg()
bool clang::CodeGen::LValue::isGlobalReg () const inline
Definition at line 285 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), emitSimpleAtomicLoad(), emitSimpleAtomicStore(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), and getGlobalReg().
isKnownNonNull()
KnownNonNull_t clang::CodeGen::LValue::isKnownNonNull () const inline
Definition at line 352 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLValue().
isMatrixElt()
bool clang::CodeGen::LValue::isMatrixElt () const inline
Definition at line 286 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), getMatrixAddress(), getMatrixIdx(), and getMatrixPointer().
isNonGC()
bool clang::CodeGen::LValue::isNonGC () const inline
Definition at line 306 of file CGValue.h.
isNontemporal()
bool clang::CodeGen::LValue::isNontemporal () const inline
Definition at line 321 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitMemberExpr(), EmitStoreOfMatrixScalar(), and clang::CodeGen::CodeGenFunction::EmitStoreOfScalar().
isObjCArray()
bool clang::CodeGen::LValue::isObjCArray () const inline
Definition at line 303 of file CGValue.h.
Referenced by setObjCGCLValueClass().
isObjCIvar()
bool clang::CodeGen::LValue::isObjCIvar () const inline
Definition at line 300 of file CGValue.h.
Referenced by setObjCGCLValueClass().
isObjCStrong()
bool clang::CodeGen::LValue::isObjCStrong () const inline
Definition at line 327 of file CGValue.h.
References clang::Qualifiers::getObjCGCAttr(), and clang::Qualifiers::Strong.
Referenced by EmitDeclInit().
isObjCWeak()
bool clang::CodeGen::LValue::isObjCWeak () const inline
Definition at line 324 of file CGValue.h.
References clang::Qualifiers::getObjCGCAttr(), and clang::Qualifiers::Weak.
Referenced by EmitDeclInit(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), and clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue().
isRestrictQualified()
bool clang::CodeGen::LValue::isRestrictQualified () const inline
Definition at line 289 of file CGValue.h.
References clang::Qualifiers::hasRestrict().
isSimple()
bool clang::CodeGen::LValue::isSimple () const inline
Definition at line 281 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitCallArg(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitCheckedLValue(), clang::CodeGen::CodeGenFunction::EmitInitializerForField(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr(), emitRawPointer(), clang::CodeGen::CodeGenFunction::EmitReferenceBindingToExpr(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue(), and getPointer().
isThreadLocalRef()
bool clang::CodeGen::LValue::isThreadLocalRef () const inline
Definition at line 312 of file CGValue.h.
isVectorElt()
bool clang::CodeGen::LValue::isVectorElt () const inline
Definition at line 282 of file CGValue.h.
Referenced by EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue(), getRawVectorPointer(), getVectorAddress(), getVectorIdx(), and getVectorPointer().
isVolatile()
bool clang::CodeGen::LValue::isVolatile () const inline
Definition at line 331 of file CGValue.h.
References clang::Qualifiers::hasVolatile().
Referenced by clang::CodeGen::CodeGenFunction::callCStructCopyAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructCopyConstructor(), clang::CodeGen::CodeGenFunction::callCStructDefaultConstructor(), clang::CodeGen::CodeGenFunction::callCStructDestructor(), clang::CodeGen::CodeGenFunction::callCStructMoveAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructMoveConstructor(), clang::CodeGen::CodeGenFunction::defaultInitNonTrivialCStructVar(), clang::CodeGen::CodeGenFunction::EmitLoadOfReference(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), emitSimpleAtomicLoad(), emitSimpleAtomicStore(), EmitStoreOfMatrixScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CallArg::getRValue(), and clang::CodeGen::CodeGenFunction::LValueIsSuitableForInlineAtomic().
isVolatileQualified()
bool clang::CodeGen::LValue::isVolatileQualified () const inline
Definition at line 288 of file CGValue.h.
References clang::Qualifiers::hasVolatile().
Referenced by asAggregateRValue(), clang::CodeGen::CallArg::copyInto(), clang::CodeGen::CodeGenFunction::EmitAtomicLoad(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), clang::CodeGen::CodeGenFunction::EmitLoadOfBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfExtVectorElementLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), EmitMemberInitializer(), clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughExtVectorComponentLValue(), and clang::CodeGen::CodeGenFunction::EmitStoreThroughLValue().
MakeAddr()
static LValue clang::CodeGen::LValue::MakeAddr (Address Addr, QualType type, ASTContext & Context, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo) inline static
Definition at line 440 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::CodeGen::CodeGenFunction::MakeAddrLValueWithoutTBAA(), and clang::CodeGen::CodeGenFunction::MakeRawAddrLValue().
MakeBitfield()
static LValue clang::CodeGen::LValue::MakeBitfield (Address Addr, const CGBitFieldInfo & Info, QualType type, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo) inline static
Create a new object to represent a bit-field access.
Parameters
Addr - The base address of the bit-field sequence this bit-field refers to.
Info - The information describing how to perform the bit-field access.
Definition at line 476 of file CGValue.h.
References Addr, BitFieldInfo, and clang::ast_matchers::type.
Referenced by EmitAtomicUpdateValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), and clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset().
MakeExtVectorElt()
static LValue clang::CodeGen::LValue::MakeExtVectorElt (Address Addr, llvm::Constant * Elts, QualType type, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo) inline static
Definition at line 460 of file CGValue.h.
References Addr, clang::ast_matchers::type, and VectorElts.
Referenced by EmitAtomicUpdateValue(), and clang::CodeGen::CodeGenFunction::EmitExtVectorElementExpr().
MakeGlobalReg()
static LValue clang::CodeGen::LValue::MakeGlobalReg (llvm::Value * V, CharUnits alignment, QualType type) inline static
Definition at line 486 of file CGValue.h.
References clang::CodeGen::Decl, clang::CodeGen::Address::invalid(), clang::ast_matchers::type, and V.
MakeMatrixElt()
static LValue clang::CodeGen::LValue::MakeMatrixElt (Address matAddress, llvm::Value * Idx, QualType type, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo) inline static
Definition at line 496 of file CGValue.h.
References clang::ast_matchers::type, and VectorIdx.
Referenced by clang::CodeGen::CodeGenFunction::EmitMatrixSubscriptExpr().
MakeVectorElt()
static LValue clang::CodeGen::LValue::MakeVectorElt (Address vecAddress, llvm::Value * Idx, QualType type, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo) inline static
Definition at line 450 of file CGValue.h.
References clang::ast_matchers::type, and VectorIdx.
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), and EmitAtomicUpdateValue().
setAddress()
void clang::CodeGen::LValue::setAddress (Address address) inline
Definition at line 375 of file CGValue.h.
References Addr.
Referenced by drillIntoBlockVariable(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), emitGlobalToListCopyFunction(), emitListToGlobalCopyFunction(), EmitLoadOfMatrixLValue(), and clang::CodeGen::CodeGenFunction::EmitScalarInit().
setAlignment()
void clang::CodeGen::LValue::setAlignment (CharUnits A) inline
Definition at line 347 of file CGValue.h.
References Addr, and clang::CodeGen::Address::setAlignment().
setARCPreciseLifetime()
void clang::CodeGen::LValue::setARCPreciseLifetime (ARCPreciseLifetime_t value) inline
Definition at line 318 of file CGValue.h.
References clang::CodeGen::ARCImpreciseLifetime.
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue().
setBaseInfo()
void clang::CodeGen::LValue::setBaseInfo (LValueBaseInfo Info) inline
Definition at line 350 of file CGValue.h.
setBaseIvarExp()
void clang::CodeGen::LValue::setBaseIvarExp (Expr * V) inline
Definition at line 336 of file CGValue.h.
References V.
Referenced by setObjCGCLValueClass().
setGlobalObjCRef()
void clang::CodeGen::LValue::setGlobalObjCRef (bool Value) inline
Definition at line 310 of file CGValue.h.
Referenced by setObjCGCLValueClass().
setKnownNonNull()
LValue clang::CodeGen::LValue::setKnownNonNull () inline
Definition at line 355 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLValue().
setNonGC()
void clang::CodeGen::LValue::setNonGC (bool Value) inline
Definition at line 307 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitAutoVarInit(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), and clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue().
setNontemporal()
void clang::CodeGen::LValue::setNontemporal (bool Value) inline
Definition at line 322 of file CGValue.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::EmitMemberExpr(), EmitNontemporalLoad(), and EmitNontemporalStore().
setObjCArray()
void clang::CodeGen::LValue::setObjCArray (bool Value) inline
Definition at line 304 of file CGValue.h.
Referenced by setObjCGCLValueClass().
setObjCIvar()
void clang::CodeGen::LValue::setObjCIvar (bool Value) inline
Definition at line 301 of file CGValue.h.
Referenced by setObjCGCLValueClass().
setTBAAInfo()
void clang::CodeGen::LValue::setTBAAInfo (TBAAAccessInfo Info) inline
Definition at line 339 of file CGValue.h.
setThreadLocalRef()
void clang::CodeGen::LValue::setThreadLocalRef (bool Value) inline
Definition at line 313 of file CGValue.h.
Referenced by setObjCGCLValueClass().
Member Data Documentation
Addr
Address clang::CodeGen::LValue::Addr = Address::invalid()
Definition at line 192 of file CGValue.h.
Referenced by emitRawPointer(), getAddress(), getAlignment(), getBitFieldAddress(), getExtVectorAddress(), getMatrixAddress(), getMatrixPointer(), getPointer(), getRawBitFieldPointer(), getRawExtVectorPointer(), getRawVectorPointer(), getVectorAddress(), getVectorPointer(), MakeBitfield(), MakeExtVectorElt(), setAddress(), and setAlignment().
BitFieldInfo
const CGBitFieldInfo* clang::CodeGen::LValue::BitFieldInfo
Definition at line 204 of file CGValue.h.
Referenced by getBitFieldInfo(), and MakeBitfield().
V
llvm::Value* clang::CodeGen::LValue::V
Definition at line 193 of file CGValue.h.
Referenced by getGlobalReg(), MakeGlobalReg(), and setBaseIvarExp().
VectorElts
llvm::Constant* clang::CodeGen::LValue::VectorElts
Definition at line 201 of file CGValue.h.
Referenced by getExtVectorElts(), and MakeExtVectorElt().
VectorIdx
llvm::Value* clang::CodeGen::LValue::VectorIdx
Definition at line 198 of file CGValue.h.
Referenced by getMatrixIdx(), getVectorIdx(), MakeMatrixElt(), and MakeVectorElt().
The documentation for this class was generated from the following file:
lib/CodeGen/CGValue.h