clang: clang::OpenACCSeqClause Class Reference
clang::OpenACCSeqClause Class Reference
#include "clang/AST/OpenACCClause.h"
Public Member Functions
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClause
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Static Public Member Functions
static bool classof (const OpenACCClause *C)
static OpenACCSeqClause * Create (const ASTContext &Ctx, SourceLocation BeginLoc, SourceLocation EndLoc)
Static Public Member Functions inherited from clang::OpenACCClause
static bool classof (const OpenACCClause *)
Protected Member Functions
OpenACCSeqClause (SourceLocation BeginLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClause
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Additional Inherited Members
Public Types inherited from clang::OpenACCClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Detailed Description
Definition at line 101 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCSeqClause()
clang::OpenACCSeqClause::OpenACCSeqClause (SourceLocation BeginLoc, SourceLocation EndLoc) inline protected
Definition at line 103 of file OpenACCClause.h.
References clang::Seq.
Referenced by Create().
Member Function Documentation
children() [1/2]
child_range clang::OpenACCSeqClause::children () inline
Definition at line 114 of file OpenACCClause.h.
children() [2/2]
const_child_range clang::OpenACCSeqClause::children () const inline
Definition at line 117 of file OpenACCClause.h.
classof()
static bool clang::OpenACCSeqClause::classof (const OpenACCClause * C) inline static
Definition at line 107 of file OpenACCClause.h.
References clang::Seq.
Create()
OpenACCSeqClause * OpenACCSeqClause::Create (const ASTContext & Ctx, SourceLocation BeginLoc, SourceLocation EndLoc) static
Definition at line 337 of file OpenACCClause.cpp.
References OpenACCSeqClause().
Referenced by clang::ASTRecordReader::readOpenACCClause().
The documentation for this class was generated from the following files:
include/clang/AST/OpenACCClause.h
lib/AST/OpenACCClause.cpp