clang: clang::OpenACCClause Class Reference
clang::OpenACCClause Class Reference
This is the base type for all OpenACC Clauses.
#include "clang/AST/OpenACCClause.h"
Public Types
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Static Public Member Functions
static bool classof (const OpenACCClause *)
Protected Member Functions
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Detailed Description
This is the base type for all OpenACC Clauses.
Definition at line 22 of file OpenACCClause.h.
Member Typedef Documentation
child_iterator
using clang::OpenACCClause::child_iterator = StmtIterator
Definition at line 38 of file OpenACCClause.h.
child_range
using clang::OpenACCClause::child_range = llvm::iterator_range<child_iterator>
Definition at line 40 of file OpenACCClause.h.
const_child_iterator
using clang::OpenACCClause::const_child_iterator = ConstStmtIterator
Definition at line 39 of file OpenACCClause.h.
const_child_range
using clang::OpenACCClause::const_child_range = llvm::iterator_range<const_child_iterator>
Definition at line 41 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCClause()
clang::OpenACCClause::OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc) inline protected
Definition at line 27 of file OpenACCClause.h.
~OpenACCClause()
virtual clang::OpenACCClause::~OpenACCClause () virtual default
Member Function Documentation
children() [1/2]
OpenACCClause::child_range OpenACCClause::children ()
Definition at line 71 of file OpenACCClause.cpp.
References getClauseKind().
Referenced by children().
children() [2/2]
const_child_range clang::OpenACCClause::children () const inline
Definition at line 44 of file OpenACCClause.h.
References children().
classof()
static bool clang::OpenACCClause::classof (const OpenACCClause *) inline static
Definition at line 36 of file OpenACCClause.h.
getBeginLoc()
SourceLocation clang::OpenACCClause::getBeginLoc () const inline
Definition at line 33 of file OpenACCClause.h.
References clang::SourceRange::getBegin().
getClauseKind()
OpenACCClauseKind clang::OpenACCClause::getClauseKind () const inline
Definition at line 32 of file OpenACCClause.h.
Referenced by children().
getEndLoc()
SourceLocation clang::OpenACCClause::getEndLoc () const inline
Definition at line 34 of file OpenACCClause.h.
References clang::SourceRange::getEnd().
The documentation for this class was generated from the following files:
include/clang/AST/OpenACCClause.h
lib/AST/OpenACCClause.cpp