clang: clang::threadSafety::til::ArrayIndex Class Reference
clang::threadSafety::til::ArrayIndex Class Reference
If p is a reference to an array, then p[i] is a reference to the i'th element of the array.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
ArrayIndex (SExpr *A, SExpr *N)
ArrayIndex (const ArrayIndex &E, SExpr *A, SExpr *N)
SExpr * array ()
const SExpr * array () const
SExpr * index ()
const SExpr * index () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const ArrayIndex *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
SExpr & operator= (const SExpr &)=delete
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
If p is a reference to an array, then p[i] is a reference to the i'th element of the array.
Definition at line 1102 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
ArrayIndex() [1/2]
clang::threadSafety::til::ArrayIndex::ArrayIndex (SExpr * A, SExpr * N) inline
Definition at line 1104 of file ThreadSafetyTIL.h.
ArrayIndex() [2/2]
clang::threadSafety::til::ArrayIndex::ArrayIndex (const ArrayIndex & E, SExpr * A, SExpr * N) inline
Definition at line 1105 of file ThreadSafetyTIL.h.
Member Function Documentation
array() [1/2]
SExpr* clang::threadSafety::til::ArrayIndex::array () inline
Definition at line 1110 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayIndex().
array() [2/2]
const SExpr* clang::threadSafety::til::ArrayIndex::array () const inline
Definition at line 1111 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::ArrayIndex::classof (const SExpr * E) inline static
Definition at line 1108 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::ArrayIndex::compare (const ArrayIndex * E, C & Cmp) const inline
Definition at line 1124 of file ThreadSafetyTIL.h.
index() [1/2]
SExpr* clang::threadSafety::til::ArrayIndex::index () inline
Definition at line 1113 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printArrayIndex().
index() [2/2]
const SExpr* clang::threadSafety::til::ArrayIndex::index () const inline
Definition at line 1114 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::ArrayIndex::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1117 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h