clang: clang::CodeGen::CodeGenFunction::ConditionalEvaluation Class Reference
clang::CodeGen::CodeGenFunction::ConditionalEvaluation Class Reference
An object to manage conditionally-evaluated expressions.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
ConditionalEvaluation (CodeGenFunction &CGF)
void begin (CodeGenFunction &CGF)
void end (CodeGenFunction &CGF)
llvm::BasicBlock * getStartingBlock () const
Returns a block which will be executed prior to each evaluation of the conditional code.
Detailed Description
An object to manage conditionally-evaluated expressions.
Definition at line 1238 of file CodeGenFunction.h.
Constructor & Destructor Documentation
ConditionalEvaluation()
clang::CodeGen::CodeGenFunction::ConditionalEvaluation::ConditionalEvaluation (CodeGenFunction & CGF) inline
Definition at line 1242 of file CodeGenFunction.h.
Member Function Documentation
begin()
void clang::CodeGen::CodeGenFunction::ConditionalEvaluation::begin (CodeGenFunction & CGF) inline
Definition at line 1245 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitBranchOnBoolExpr(), clang::CodeGen::CGCUDARuntime::EmitCUDAKernelCallExpr(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), and emitWritebackArg().
end()
void clang::CodeGen::CodeGenFunction::ConditionalEvaluation::end (CodeGenFunction & CGF) inline
Definition at line 1251 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitBranchOnBoolExpr(), clang::CodeGen::CGCUDARuntime::EmitCUDAKernelCallExpr(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), and emitWritebackArg().
getStartingBlock()
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::ConditionalEvaluation::getStartingBlock () const inline
Returns a block which will be executed prior to each evaluation of the conditional code.
Definition at line 1259 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr(), and clang::CodeGen::CodeGenFunction::setBeforeOutermostConditional().
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h