clang: clang::SubstTemplateTemplateParmPackStorage Class Reference
clang::SubstTemplateTemplateParmPackStorage Class Reference
A structure for storing an already-substituted template template parameter pack.
#include "clang/AST/TemplateName.h"
Public Member Functions
SubstTemplateTemplateParmPackStorage (ArrayRef< TemplateArgument > ArgPack, Decl *AssociatedDecl, unsigned Index, bool Final)
Decl * getAssociatedDecl () const
A template-like entity which owns the whole pattern being substituted.
unsigned getIndex () const
Returns the index of the replaced parameter in the associated declaration.
bool getFinal () const
TemplateTemplateParmDecl * getParameterPack () const
Retrieve the template template parameter pack being substituted.
TemplateArgument getArgumentPack () const
Retrieve the template template argument pack with which this parameter was substituted.
void Profile (llvm::FoldingSetNodeID &ID, ASTContext &Context)
Public Member Functions inherited from clang::UncommonTemplateNameStorage
OverloadedTemplateStorage * getAsOverloadedStorage ()
AssumedTemplateStorage * getAsAssumedTemplateName ()
SubstTemplateTemplateParmStorage * getAsSubstTemplateTemplateParm ()
SubstTemplateTemplateParmPackStorage * getAsSubstTemplateTemplateParmPack ()
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, ASTContext &Context, const TemplateArgument &ArgPack, Decl *AssociatedDecl, unsigned Index, bool Final)
Additional Inherited Members
Protected Types inherited from clang::UncommonTemplateNameStorage
enum Kind { Overloaded , Assumed , SubstTemplateTemplateParm , SubstTemplateTemplateParmPack }
Protected Member Functions inherited from clang::UncommonTemplateNameStorage
UncommonTemplateNameStorage (Kind Kind, unsigned Index, unsigned Data)
Protected Attributes inherited from clang::UncommonTemplateNameStorage
union {
struct BitsTag Bits
void * PointerAlignment
};
Detailed Description
A structure for storing an already-substituted template template parameter pack.
This kind of template names occurs when the parameter pack has been provided with a template template argument pack in a context where its enclosing pack expansion could not be fully expanded.
Definition at line 140 of file TemplateName.h.
Constructor & Destructor Documentation
SubstTemplateTemplateParmPackStorage()
SubstTemplateTemplateParmPackStorage::SubstTemplateTemplateParmPackStorage (ArrayRef< TemplateArgument > ArgPack, Decl * AssociatedDecl, unsigned Index, bool Final)
Definition at line 69 of file TemplateName.cpp.
Member Function Documentation
getArgumentPack()
TemplateArgument SubstTemplateTemplateParmPackStorage::getArgumentPack () const
Retrieve the template template argument pack with which this parameter was substituted.
Definition at line 38 of file TemplateName.cpp.
References clang::UncommonTemplateNameStorage::Bits, and clang::UncommonTemplateNameStorage::BitsTag::Data.
Referenced by clang::ASTImporter::Import().
getAssociatedDecl()
Decl * SubstTemplateTemplateParmPackStorage::getAssociatedDecl () const
A template-like entity which owns the whole pattern being substituted.
This will own a set of template parameters.
Definition at line 84 of file TemplateName.cpp.
Referenced by getParameterPack(), and clang::ASTImporter::Import().
getFinal()
bool SubstTemplateTemplateParmPackStorage::getFinal () const
Definition at line 88 of file TemplateName.cpp.
Referenced by clang::ASTImporter::Import().
getIndex()
unsigned clang::SubstTemplateTemplateParmPackStorage::getIndex () const inline
Returns the index of the replaced parameter in the associated declaration.
This should match the result of getParameterPack()->getIndex().
Definition at line 156 of file TemplateName.h.
References clang::UncommonTemplateNameStorage::Bits, and clang::UncommonTemplateNameStorage::BitsTag::Index.
Referenced by clang::ASTImporter::Import().
getParameterPack()
TemplateTemplateParmDecl * SubstTemplateTemplateParmPackStorage::getParameterPack () const
Retrieve the template template parameter pack being substituted.
Definition at line 43 of file TemplateName.cpp.
References clang::UncommonTemplateNameStorage::Bits, getAssociatedDecl(), clang::getReplacedTemplateParameterList(), and clang::UncommonTemplateNameStorage::BitsTag::Index.
Profile() [1/2]
void SubstTemplateTemplateParmPackStorage::Profile (llvm::FoldingSetNodeID & ID, ASTContext & Context)
Definition at line 78 of file TemplateName.cpp.
Profile() [2/2]
void SubstTemplateTemplateParmPackStorage::Profile (llvm::FoldingSetNodeID & ID, ASTContext & Context, const TemplateArgument & ArgPack, Decl * AssociatedDecl, unsigned Index, bool Final) static
Definition at line 92 of file TemplateName.cpp.
The documentation for this class was generated from the following files:
include/clang/AST/TemplateName.h
lib/AST/TemplateName.cpp