clang: clang::CowCompilerInvocation Class Reference
clang::CowCompilerInvocation Class Reference
Same as CompilerInvocation, but with copy-on-write optimization.
#include "clang/Frontend/CompilerInvocation.h"
Public Member Functions
CowCompilerInvocation ()=default
CowCompilerInvocation (const CowCompilerInvocation &X)
CowCompilerInvocation (CowCompilerInvocation &&)=default
CowCompilerInvocation & operator= (const CowCompilerInvocation &X)
~CowCompilerInvocation ()=default
CowCompilerInvocation (const CompilerInvocation &X)
CowCompilerInvocation (CompilerInvocation &&X)
LangOptions & getMutLangOpts ()
Mutable getters.
TargetOptions & getMutTargetOpts ()
DiagnosticOptions & getMutDiagnosticOpts ()
HeaderSearchOptions & getMutHeaderSearchOpts ()
PreprocessorOptions & getMutPreprocessorOpts ()
AnalyzerOptions & getMutAnalyzerOpts ()
MigratorOptions & getMutMigratorOpts ()
APINotesOptions & getMutAPINotesOpts ()
CodeGenOptions & getMutCodeGenOpts ()
FileSystemOptions & getMutFileSystemOpts ()
FrontendOptions & getMutFrontendOpts ()
DependencyOutputOptions & getMutDependencyOutputOpts ()
PreprocessorOutputOptions & getMutPreprocessorOutputOpts ()
Public Member Functions inherited from clang::CompilerInvocationBase
const LangOptions & getLangOpts () const
Const getters.
const TargetOptions & getTargetOpts () const
const DiagnosticOptions & getDiagnosticOpts () const
const HeaderSearchOptions & getHeaderSearchOpts () const
const PreprocessorOptions & getPreprocessorOpts () const
const AnalyzerOptions & getAnalyzerOpts () const
const MigratorOptions & getMigratorOpts () const
const APINotesOptions & getAPINotesOpts () const
const CodeGenOptions & getCodeGenOpts () const
const FileSystemOptions & getFileSystemOpts () const
const FrontendOptions & getFrontendOpts () const
const DependencyOutputOptions & getDependencyOutputOpts () const
const PreprocessorOutputOptions & getPreprocessorOutputOpts () const
void generateCC1CommandLine (llvm::SmallVectorImpl< const char * > &Args, StringAllocator SA) const
Generate cc1-compatible command line arguments from this instance.
void generateCC1CommandLine (ArgumentConsumer Consumer) const
Generate cc1-compatible command line arguments from this instance.
std::vector< std::string > getCC1CommandLine () const
Generate cc1-compatible command line arguments from this instance, wrapping the result as a std::vector<std::string>.
Additional Inherited Members
Public Types inherited from clang::CompilerInvocationBase
using StringAllocator = llvm::function_ref< const char *(const Twine &)>
Command line generation.
using ArgumentConsumer = llvm::function_ref< void(const Twine &)>
Protected Member Functions inherited from clang::CompilerInvocationBase
CompilerInvocationBase ()
CompilerInvocationBase (EmptyConstructor)
CompilerInvocationBase (const CompilerInvocationBase &X)=delete
CompilerInvocationBase (CompilerInvocationBase &&X)=default
CompilerInvocationBase & operator= (const CompilerInvocationBase &X)=delete
CompilerInvocationBase & deep_copy_assign (const CompilerInvocationBase &X)
CompilerInvocationBase & shallow_copy_assign (const CompilerInvocationBase &X)
CompilerInvocationBase & operator= (CompilerInvocationBase &&X)=default
~CompilerInvocationBase ()=default
Protected Attributes inherited from clang::CompilerInvocationBase
std::shared_ptr< LangOptions > LangOpts
Options controlling the language variant.
std::shared_ptr< TargetOptions > TargetOpts
Options controlling the target.
IntrusiveRefCntPtr< DiagnosticOptions > DiagnosticOpts
Options controlling the diagnostic engine.
std::shared_ptr< HeaderSearchOptions > HSOpts
Options controlling the #include directive.
std::shared_ptr< PreprocessorOptions > PPOpts
Options controlling the preprocessor (aside from #include handling).
AnalyzerOptionsRef AnalyzerOpts
Options controlling the static analyzer.
std::shared_ptr< MigratorOptions > MigratorOpts
std::shared_ptr< APINotesOptions > APINotesOpts
Options controlling API notes.
std::shared_ptr< CodeGenOptions > CodeGenOpts
Options controlling IRgen and the backend.
std::shared_ptr< FileSystemOptions > FSOpts
Options controlling file system operations.
std::shared_ptr< FrontendOptions > FrontendOpts
Options controlling the frontend itself.
std::shared_ptr< DependencyOutputOptions > DependencyOutputOpts
Options controlling dependency output.
std::shared_ptr< PreprocessorOutputOptions > PreprocessorOutputOpts
Options controlling preprocessed output.
Detailed Description
Same as CompilerInvocation, but with copy-on-write optimization.
Definition at line 354 of file CompilerInvocation.h.
Constructor & Destructor Documentation
CowCompilerInvocation() [1/5]
clang::CowCompilerInvocation::CowCompilerInvocation () default
CowCompilerInvocation() [2/5]
clang::CowCompilerInvocation::CowCompilerInvocation (const CowCompilerInvocation & X) inline
Definition at line 357 of file CompilerInvocation.h.
References clang::CompilerInvocationBase::shallow_copy_assign(), and X.
CowCompilerInvocation() [3/5]
clang::CowCompilerInvocation::CowCompilerInvocation (CowCompilerInvocation &&) default
~CowCompilerInvocation()
clang::CowCompilerInvocation::~CowCompilerInvocation () default
CowCompilerInvocation() [4/5]
clang::CowCompilerInvocation::CowCompilerInvocation (const CompilerInvocation & X) inline
Definition at line 368 of file CompilerInvocation.h.
References clang::CompilerInvocationBase::deep_copy_assign(), and X.
CowCompilerInvocation() [5/5]
clang::CowCompilerInvocation::CowCompilerInvocation (CompilerInvocation && X) inline
Definition at line 373 of file CompilerInvocation.h.
Member Function Documentation
getMutAnalyzerOpts()
AnalyzerOptions & CowCompilerInvocation::getMutAnalyzerOpts ()
Definition at line 241 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::AnalyzerOpts.
getMutAPINotesOpts()
APINotesOptions & CowCompilerInvocation::getMutAPINotesOpts ()
Definition at line 249 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::APINotesOpts.
getMutCodeGenOpts()
CodeGenOptions & CowCompilerInvocation::getMutCodeGenOpts ()
Definition at line 253 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::CodeGenOpts.
getMutDependencyOutputOpts()
DependencyOutputOptions & CowCompilerInvocation::getMutDependencyOutputOpts ()
Definition at line 265 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::DependencyOutputOpts.
getMutDiagnosticOpts()
DiagnosticOptions & CowCompilerInvocation::getMutDiagnosticOpts ()
Definition at line 229 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::DiagnosticOpts.
getMutFileSystemOpts()
FileSystemOptions & CowCompilerInvocation::getMutFileSystemOpts ()
Definition at line 257 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::FSOpts.
getMutFrontendOpts()
FrontendOptions & CowCompilerInvocation::getMutFrontendOpts ()
Definition at line 261 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::FrontendOpts.
getMutHeaderSearchOpts()
HeaderSearchOptions & CowCompilerInvocation::getMutHeaderSearchOpts ()
Definition at line 233 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::HSOpts.
getMutLangOpts()
LangOptions & CowCompilerInvocation::getMutLangOpts ()
Mutable getters.
Definition at line 221 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::LangOpts.
getMutMigratorOpts()
MigratorOptions & CowCompilerInvocation::getMutMigratorOpts ()
Definition at line 245 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::MigratorOpts.
getMutPreprocessorOpts()
PreprocessorOptions & CowCompilerInvocation::getMutPreprocessorOpts ()
Definition at line 237 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::PPOpts.
getMutPreprocessorOutputOpts()
PreprocessorOutputOptions & CowCompilerInvocation::getMutPreprocessorOutputOpts ()
Definition at line 270 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::PreprocessorOutputOpts.
getMutTargetOpts()
TargetOptions & CowCompilerInvocation::getMutTargetOpts ()
Definition at line 225 of file CompilerInvocation.cpp.
References clang::CompilerInvocationBase::TargetOpts.
operator=()
CowCompilerInvocation& clang::CowCompilerInvocation::operator= (const CowCompilerInvocation & X) inline
Definition at line 362 of file CompilerInvocation.h.
References clang::CompilerInvocationBase::shallow_copy_assign(), and X.
The documentation for this class was generated from the following files:
include/clang/Frontend/CompilerInvocation.h
lib/Frontend/CompilerInvocation.cpp