clang: SYCLKernelNameTypeVisitor Class Reference
SYCLKernelNameTypeVisitor Class Reference
Public Member Functions
SYCLKernelNameTypeVisitor (SemaSYCL &S, SourceLocation KernelInvocationFuncLoc, QualType KernelNameType, bool IsUnnamedKernel)
bool isValid ()
void Visit (QualType T)
void Visit (const TemplateArgument &TA)
void VisitBuiltinType (const BuiltinType *TT)
void VisitTagType (const TagType *TT)
void DiagnoseKernelNameType (const NamedDecl *DeclNamed)
void VisitTypeTemplateArgument (const TemplateArgument &TA)
void VisitIntegralTemplateArgument (const TemplateArgument &TA)
void VisitTemplateTemplateArgument (const TemplateArgument &TA)
void VisitPackTemplateArgument (const TemplateArgument &TA)
Public Member Functions inherited from clang::TypeVisitor< SYCLKernelNameTypeVisitor >
void Visit (const Type *T)
Performs the operation associated with this visitor object.
void VisitType (const Type *)
Method called if ImpClass doesn't provide specific handler for some type class.
Public Member Functions inherited from clang::templateargumentvisitor::Base< Ref, ImplClass, RetTy, ParamTys >
RetTy Visit (REF(TemplateArgument) TA, ParamTys... P)
VISIT_METHOD (Null)
VISIT_METHOD (Type)
VISIT_METHOD (Declaration)
VISIT_METHOD (NullPtr)
VISIT_METHOD (Integral)
VISIT_METHOD (StructuralValue)
VISIT_METHOD (Template)
VISIT_METHOD (TemplateExpansion)
VISIT_METHOD (Expression)
VISIT_METHOD (Pack)
RetTy VisitTemplateArgument (REF(TemplateArgument), ParamTys...)
Detailed Description
Definition at line 3895 of file SemaSYCL.cpp.
Constructor & Destructor Documentation
SYCLKernelNameTypeVisitor()
SYCLKernelNameTypeVisitor::SYCLKernelNameTypeVisitor (SemaSYCL & S, SourceLocation KernelInvocationFuncLoc, QualType KernelNameType, bool IsUnnamedKernel) inline
Definition at line 3913 of file SemaSYCL.cpp.
Member Function Documentation
DiagnoseKernelNameType()
void SYCLKernelNameTypeVisitor::DiagnoseKernelNameType (const NamedDecl * DeclNamed) inline
Definition at line 3957 of file SemaSYCL.cpp.
isValid()
bool SYCLKernelNameTypeVisitor::isValid () inline
Definition at line 3918 of file SemaSYCL.cpp.
Referenced by clang::SemaSYCL::CheckSYCLKernelCall().
Visit() [1/2]
void SYCLKernelNameTypeVisitor::Visit (const TemplateArgument & TA) inline
Definition at line 3937 of file SemaSYCL.cpp.
References clang::TemplateArgument::isNull().
Visit() [2/2]
void SYCLKernelNameTypeVisitor::Visit (QualType T) inline
Definition at line 3920 of file SemaSYCL.cpp.
References clang::Type::getAsCXXRecordDecl(), and clang::T.
Referenced by clang::SemaSYCL::CheckSYCLKernelCall().
VisitBuiltinType()
void SYCLKernelNameTypeVisitor::VisitBuiltinType (const BuiltinType * TT) inline
Definition at line 3943 of file SemaSYCL.cpp.
References clang::Type::isNullPtrType().
VisitIntegralTemplateArgument()
void SYCLKernelNameTypeVisitor::VisitIntegralTemplateArgument (const TemplateArgument & TA) inline
Definition at line 4057 of file SemaSYCL.cpp.
References clang::Type::getAs(), clang::TemplateArgument::getIntegralType(), and clang::T.
VisitPackTemplateArgument()
void SYCLKernelNameTypeVisitor::VisitPackTemplateArgument (const TemplateArgument & TA) inline
Definition at line 4075 of file SemaSYCL.cpp.
References clang::TemplateArgument::getPackAsArray().
VisitTagType()
void SYCLKernelNameTypeVisitor::VisitTagType (const TagType * TT) inline
Definition at line 3953 of file SemaSYCL.cpp.
References clang::TagType::getDecl().
VisitTemplateTemplateArgument()
void SYCLKernelNameTypeVisitor::VisitTemplateTemplateArgument (const TemplateArgument & TA) inline
Definition at line 4063 of file SemaSYCL.cpp.
References clang::TemplateArgument::getAsTemplate(), clang::TemplateName::getAsTemplateDecl(), clang::TemplateDecl::getTemplateParameters(), P, and clang::TemplateParam.
VisitTypeTemplateArgument()
void SYCLKernelNameTypeVisitor::VisitTypeTemplateArgument (const TemplateArgument & TA) inline
Definition at line 4049 of file SemaSYCL.cpp.
References clang::Type::getAs(), clang::TemplateArgument::getAsType(), and clang::T.
The documentation for this class was generated from the following file:
lib/Sema/SemaSYCL.cpp