clang: clang::CompressedOffloadBundle Class Reference
clang::CompressedOffloadBundle Class Reference
#include "clang/Driver/OffloadBundler.h"
Static Public Member Functions
static llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > compress (llvm::compression::Params P, const llvm::MemoryBuffer &Input, bool Verbose=false)
static llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > decompress (const llvm::MemoryBuffer &Input, bool Verbose=false)
Detailed Description
Definition at line 114 of file OffloadBundler.h.
Member Function Documentation
compress()
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > CompressedOffloadBundle::compress (llvm::compression::Params P, const llvm::MemoryBuffer & Input, bool Verbose = false) static
Definition at line 1512 of file OffloadBundler.cpp.
Referenced by clang::OffloadBundler::BundleFiles().
decompress()
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > CompressedOffloadBundle::decompress (const llvm::MemoryBuffer & Input, bool Verbose = false) static
Definition at line 1599 of file OffloadBundler.cpp.
Referenced by clang::OffloadBundler::ListBundleIDsInFile(), clang::OffloadBundler::UnbundleArchive(), and clang::OffloadBundler::UnbundleFiles().
The documentation for this class was generated from the following files:
include/clang/Driver/OffloadBundler.h
lib/Driver/OffloadBundler.cpp