clang: clang::format::CommaSeparatedList Class Reference
clang::format::CommaSeparatedList Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Format/FormatToken.h"
Public Member Functions
CommaSeparatedList (const FormatStyle &Style)
void precomputeFormattingInfos (const FormatToken *Token) override
After the TokenAnnotator has finished annotating all the tokens, this function precomputes required information for formatting.
unsigned formatAfterToken (LineState &State, ContinuationIndenter *Indenter, bool DryRun) override
Same as formatFromToken, but assumes that the first token has already been set thereby deciding on the first line break.
unsigned formatFromToken (LineState &State, ContinuationIndenter *Indenter, bool DryRun) override
Apply the special formatting that the given role demands.
void CommaFound (const FormatToken *Token) override
Adds Token as the next comma to the CommaSeparated list.
const FormatToken * lastComma () override
Public Member Functions inherited from clang::format::TokenRole
TokenRole (const FormatStyle &Style)
virtual ~TokenRole ()
Additional Inherited Members
Protected Attributes inherited from clang::format::TokenRole
const FormatStyle & Style
Detailed Description
Definition at line 936 of file FormatToken.h.
Constructor & Destructor Documentation
CommaSeparatedList()
clang::format::CommaSeparatedList::CommaSeparatedList (const FormatStyle & Style) inline
Definition at line 938 of file FormatToken.h.
Member Function Documentation
CommaFound()
void clang::format::CommaSeparatedList::CommaFound (const FormatToken * Token) inline override virtual
Adds Token as the next comma to the CommaSeparated list.
Reimplemented from clang::format::TokenRole.
Definition at line 950 of file FormatToken.h.
formatAfterToken()
unsigned clang::format::CommaSeparatedList::formatAfterToken (LineState & State, ContinuationIndenter * Indenter, bool DryRun) override virtual
Same as formatFromToken, but assumes that the first token has already been set thereby deciding on the first line break.
Reimplemented from clang::format::TokenRole.
Definition at line 124 of file FormatToken.cpp.
References clang::format::BK_Block, clang::Column, clang::format::FormatStyle::ColumnLimit, Indenter, clang::format::FormatToken::is(), clang::format::FormatToken::isOneOf(), clang::format::FormatToken::MatchingParen, NewLine, clang::format::FormatToken::Next, State, and clang::format::TokenRole::Style.
formatFromToken()
unsigned clang::format::CommaSeparatedList::formatFromToken (LineState & State, ContinuationIndenter * Indenter, bool DryRun) override virtual
Apply the special formatting that the given role demands.
Assumes that the token having this role is already formatted.
Continues formatting from State leaving indentation to Indenter and returns the total penalty that this formatting incurs.
Reimplemented from clang::format::TokenRole.
Definition at line 184 of file FormatToken.cpp.
References State.
lastComma()
const FormatToken* clang::format::CommaSeparatedList::lastComma () inline override virtual
Reimplemented from clang::format::TokenRole.
Definition at line 954 of file FormatToken.h.
precomputeFormattingInfos()
void clang::format::CommaSeparatedList::precomputeFormattingInfos (const FormatToken * Token) override virtual
After the TokenAnnotator has finished annotating all the tokens, this function precomputes required information for formatting.
Reimplemented from clang::format::TokenRole.
Definition at line 202 of file FormatToken.cpp.
References clang::format::FormatStyle::AlignAfterOpenBracket, clang::format::FormatStyle::BAS_DontAlign, clang::format::FormatStyle::BinPackArguments, clang::format::FormatToken::CanBreakBefore, clang::format::CodePointsBetween(), clang::Column, clang::format::FormatStyle::ColumnLimit, clang::format::FormatStyle::Cpp11BracedListStyle, clang::format::FormatToken::getNextNonComment(), clang::format::FormatToken::getPreviousNonComment(), clang::format::FormatToken::HasUnescapedNewline, clang::if(), clang::Token::is(), clang::format::FormatToken::is(), clang::Token::isOneOf(), clang::format::FormatToken::isTrailingComment(), max(), min(), clang::format::FormatToken::MustBreakBefore, clang::format::FormatToken::Next, clang::format::FormatToken::Previous, clang::format::TokenRole::Style, and UINT_MAX.
The documentation for this class was generated from the following files:
lib/Format/FormatToken.h
lib/Format/FormatToken.cpp