clang: clang::ExternalASTSource Class Reference
clang::ExternalASTSource Class Reference
Abstract interface for external sources of AST nodes.
#include "clang/AST/ExternalASTSource.h"
Classes
class Deserializing
RAII class for safely pairing a StartedDeserializing call with FinishedDeserializing.
struct MemoryBufferSizes
Public Types
enum ExtKind { EK_Always, EK_Never, EK_ReplyHazy }
Public Member Functions
ExternalASTSource ()=default
virtual ~ExternalASTSource ()
uint32_t getGeneration () const
Get the current generation of this AST source.
virtual Decl * GetExternalDecl (uint32_t ID)
Resolve a declaration ID into a declaration, potentially building a new declaration.
virtual Selector GetExternalSelector (uint32_t ID)
Resolve a selector ID into a selector.
virtual uint32_t GetNumExternalSelectors ()
Returns the number of selectors known to the external AST source.
virtual Stmt * GetExternalDeclStmt (uint64_t Offset)
Resolve the offset of a statement in the decl stream into a statement.
virtual CXXCtorInitializer ** GetExternalCXXCtorInitializers (uint64_t Offset)
Resolve the offset of a set of C++ constructor initializers in the decl stream into an array of initializers.
virtual CXXBaseSpecifier * GetExternalCXXBaseSpecifiers (uint64_t Offset)
Resolve the offset of a set of C++ base specifiers in the decl stream into an array of specifiers.
virtual void updateOutOfDateIdentifier (IdentifierInfo &II)
Update an out-of-date identifier.
virtual bool FindExternalVisibleDeclsByName (const DeclContext *DC, DeclarationName Name)
Find all declarations with the given name in the given context, and add them to the context by calling SetExternalVisibleDeclsForName or SetNoExternalVisibleDeclsForName.
virtual void completeVisibleDeclsMap (const DeclContext *DC)
Ensures that the table of all visible declarations inside this context is up to date.
virtual Module * getModule (unsigned ID)
Retrieve the module that corresponds to the given module ID.
virtual llvm::Optional< ASTSourceDescriptor > getSourceDescriptor (unsigned ID)
Return a descriptor for the corresponding module, if one exists.
virtual ExtKind hasExternalDefinitions (const Decl *D)
virtual void FindExternalLexicalDecls (const DeclContext *DC, llvm::function_ref< bool(Decl::Kind)> IsKindWeWant, SmallVectorImpl< Decl * > &Result)
Finds all declarations lexically contained within the given DeclContext, after applying an optional filter predicate.
void FindExternalLexicalDecls (const DeclContext *DC, SmallVectorImpl< Decl * > &Result)
Finds all declarations lexically contained within the given DeclContext.
virtual void FindFileRegionDecls (FileID File, unsigned Offset, unsigned Length, SmallVectorImpl< Decl * > &Decls)
Get the decls that are contained in a file in the Offset/Length range.
virtual void CompleteRedeclChain (const Decl *D)
Gives the external AST source an opportunity to complete the redeclaration chain for a declaration.
virtual void CompleteType (TagDecl *Tag)
Gives the external AST source an opportunity to complete an incomplete type.
virtual void CompleteType (ObjCInterfaceDecl *Class)
Gives the external AST source an opportunity to complete an incomplete Objective-C class.
virtual void ReadComments ()
Loads comment ranges.
virtual void StartedDeserializing ()
Notify ExternalASTSource that we started deserialization of a decl or type so until FinishedDeserializing is called there may be decls that are initializing.
virtual void FinishedDeserializing ()
Notify ExternalASTSource that we finished the deserialization of a decl or type.
virtual void StartTranslationUnit (ASTConsumer *Consumer)
Function that will be invoked when we begin parsing a new translation unit involving this external AST source.
virtual void PrintStats ()
Print any statistics that have been gathered regarding the external AST source.
virtual bool layoutRecordType (const RecordDecl *Record, uint64_t &Size, uint64_t &Alignment, llvm::DenseMap< const FieldDecl *, uint64_t > &FieldOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > &BaseOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > &VirtualBaseOffsets)
Perform layout on the given record.
MemoryBufferSizes getMemoryBufferSizes () const
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
virtual void getMemoryBufferSizes (MemoryBufferSizes &sizes) const
Protected Member Functions
uint32_t incrementGeneration (ASTContext &C)
Increment the current generation.
Static Protected Member Functions
static DeclContextLookupResult SetExternalVisibleDeclsForName (const DeclContext *DC, DeclarationName Name, ArrayRef< NamedDecl * > Decls)
static DeclContextLookupResult SetNoExternalVisibleDeclsForName (const DeclContext *DC, DeclarationName Name)
Friends
class ExternalSemaSource
virtual bool isA (const void *ClassID) const
LLVM-style RTTI.
static bool classof (const ExternalASTSource *S)
Detailed Description
Abstract interface for external sources of AST nodes.
External AST sources provide AST nodes constructed from some external source, such as a precompiled header. External AST sources can resolve types and declarations from abstract IDs into actual type and declaration nodes, and read parts of declaration contexts.
Definition at line 60 of file ExternalASTSource.h.
Member Enumeration Documentation
ExtKind
enum clang::ExternalASTSource::ExtKind
Enumerator
EK_Always
EK_Never
EK_ReplyHazy
Definition at line 165 of file ExternalASTSource.h.
Constructor & Destructor Documentation
ExternalASTSource()
clang::ExternalASTSource::ExternalASTSource () default
~ExternalASTSource()
ExternalASTSource::~ExternalASTSource () virtual default
Member Function Documentation
classof()
static bool clang::ExternalASTSource::classof (const ExternalASTSource * S) inline static
Definition at line 299 of file ExternalASTSource.h.
CompleteRedeclChain()
void ExternalASTSource::CompleteRedeclChain (const Decl * D) virtual
Gives the external AST source an opportunity to complete the redeclaration chain for a declaration.
Called each time we need the most recent declaration of a declaration after the generation count is incremented.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 47 of file ExternalASTSource.cpp.
CompleteType() [1/2]
void ExternalASTSource::CompleteType (ObjCInterfaceDecl * Class) virtual
Gives the external AST source an opportunity to complete an incomplete Objective-C class.
This routine will only be invoked if the "externally completed" bit is set on the ObjCInterfaceDecl via the function ObjCInterfaceDecl::setExternallyCompleted().
Reimplemented in clang::ExternalASTMerger, and clang::MultiplexExternalSemaSource.
Definition at line 51 of file ExternalASTSource.cpp.
CompleteType() [2/2]
void ExternalASTSource::CompleteType (TagDecl * Tag) virtual
Gives the external AST source an opportunity to complete an incomplete type.
Reimplemented in clang::ExternalASTMerger, and clang::MultiplexExternalSemaSource.
Definition at line 49 of file ExternalASTSource.cpp.
Referenced by clang::ExternalASTMerger::CompleteType(), clang::ASTContext::getASTRecordLayout(), and IsStructurallyEquivalent().
completeVisibleDeclsMap()
void ExternalASTSource::completeVisibleDeclsMap (const DeclContext * DC) virtual
Ensures that the table of all visible declarations inside this context is up to date.
The default implementation of this function is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 103 of file ExternalASTSource.cpp.
Referenced by clang::DeclContext::lookups().
FindExternalLexicalDecls() [1/2]
void ExternalASTSource::FindExternalLexicalDecls (const DeclContext * DC, llvm::function_ref< bool(Decl::Kind)> IsKindWeWant, SmallVectorImpl< Decl * > & Result) virtual
Finds all declarations lexically contained within the given DeclContext, after applying an optional filter predicate.
Parameters
IsKindWeWant a predicate function that returns true if the passed declaration kind is one we are looking for.
The default implementation of this method is a no-op.
Reimplemented in clang::ExternalASTMerger, clang::MultiplexExternalSemaSource, and clang::ASTReader.
Definition at line 105 of file ExternalASTSource.cpp.
Referenced by FindExternalLexicalDecls().
FindExternalLexicalDecls() [2/2]
void clang::ExternalASTSource::FindExternalLexicalDecls (const DeclContext * DC, SmallVectorImpl< Decl * > & Result) inline
Finds all declarations lexically contained within the given DeclContext.
Definition at line 183 of file ExternalASTSource.h.
References FindExternalLexicalDecls().
FindExternalVisibleDeclsByName()
bool ExternalASTSource::FindExternalVisibleDeclsByName (const DeclContext * DC, DeclarationName Name) virtual
Find all declarations with the given name in the given context, and add them to the context by calling SetExternalVisibleDeclsForName or SetNoExternalVisibleDeclsForName.
Returns
true if any declarations might have been found, false if we definitely have no declarations with tbis name.
The default implementation of this method is a no-op returning false.
Reimplemented in clang::ASTReader, clang::ExternalASTMerger, and clang::MultiplexExternalSemaSource.
Definition at line 98 of file ExternalASTSource.cpp.
FindFileRegionDecls()
void ExternalASTSource::FindFileRegionDecls (FileID File, unsigned Offset, unsigned Length, SmallVectorImpl< Decl * > & Decls) virtual
Get the decls that are contained in a file in the Offset/Length range.
Length can be 0 to indicate a point at Offset instead of a range.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 43 of file ExternalASTSource.cpp.
FinishedDeserializing()
void ExternalASTSource::FinishedDeserializing () virtual
Notify ExternalASTSource that we finished the deserialization of a decl or type.
Must be paired with StartedDeserializing.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 57 of file ExternalASTSource.cpp.
Referenced by clang::ExternalASTSource::Deserializing::~Deserializing().
GetExternalCXXBaseSpecifiers()
CXXBaseSpecifier * ExternalASTSource::GetExternalCXXBaseSpecifiers (uint64_t Offset) virtual
Resolve the offset of a set of C++ base specifiers in the decl stream into an array of specifiers.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 93 of file ExternalASTSource.cpp.
GetExternalCXXCtorInitializers()
CXXCtorInitializer ** ExternalASTSource::GetExternalCXXCtorInitializers (uint64_t Offset) virtual
Resolve the offset of a set of C++ constructor initializers in the decl stream into an array of initializers.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 88 of file ExternalASTSource.cpp.
GetExternalDecl()
Decl * ExternalASTSource::GetExternalDecl (uint32_t ID) virtual
Resolve a declaration ID into a declaration, potentially building a new declaration.
This method only needs to be implemented if the AST source ever passes back decl sets as VisibleDeclaration objects.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 71 of file ExternalASTSource.cpp.
Referenced by clang::RedeclarableTemplateDecl::loadLazySpecializationsImpl().
GetExternalDeclStmt()
Stmt * ExternalASTSource::GetExternalDeclStmt (uint64_t Offset) virtual
Resolve the offset of a statement in the decl stream into a statement.
This operation is meant to be used via a LazyOffsetPtr. It only needs to be implemented if the AST source uses methods like FunctionDecl::setLazyBody when building decls.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 83 of file ExternalASTSource.cpp.
GetExternalSelector()
Selector ExternalASTSource::GetExternalSelector (uint32_t ID) virtual
Resolve a selector ID into a selector.
This operation only needs to be implemented if the AST source returns non-zero for GetNumKnownSelectors().
The default implementation of this method is a no-op.
Reimplemented in clang::MultiplexExternalSemaSource, and clang::ASTReader.
Definition at line 75 of file ExternalASTSource.cpp.
getGeneration()
uint32_t clang::ExternalASTSource::getGeneration () const inline
Get the current generation of this AST source.
This number is incremented each time the AST source lazily extends an existing entity.
Definition at line 93 of file ExternalASTSource.h.
Referenced by clang::ASTReader::ReadMethodPool().
getMemoryBufferSizes() [1/2]
MemoryBufferSizes clang::ExternalASTSource::getMemoryBufferSizes () const inline
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
Definition at line 288 of file ExternalASTSource.h.
Referenced by clang::MultiplexExternalSemaSource::getMemoryBufferSizes().
getMemoryBufferSizes() [2/2]
void ExternalASTSource::getMemoryBufferSizes (MemoryBufferSizes & sizes) const virtual
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 109 of file ExternalASTSource.cpp.
getModule()
virtual Module* clang::ExternalASTSource::getModule (unsigned ID) inline virtual
Retrieve the module that corresponds to the given module ID.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 160 of file ExternalASTSource.h.
GetNumExternalSelectors()
uint32_t ExternalASTSource::GetNumExternalSelectors () virtual
Returns the number of selectors known to the external AST source.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 79 of file ExternalASTSource.cpp.
getSourceDescriptor()
llvm::Optional< ASTSourceDescriptor > ExternalASTSource::getSourceDescriptor (unsigned ID) virtual
Return a descriptor for the corresponding module, if one exists.
Reimplemented in clang::ASTReader.
Definition at line 34 of file ExternalASTSource.cpp.
hasExternalDefinitions()
ExternalASTSource::ExtKind ExternalASTSource::hasExternalDefinitions (const Decl * D) virtual
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 39 of file ExternalASTSource.cpp.
References EK_ReplyHazy.
Referenced by adjustGVALinkageForExternalDefinitionKind().
incrementGeneration()
uint32_t ExternalASTSource::incrementGeneration (ASTContext & C) protected
Increment the current generation.
Definition at line 111 of file ExternalASTSource.cpp.
References P.
isA()
virtual bool clang::ExternalASTSource::isA (const void * ClassID) const inline virtual
LLVM-style RTTI.
Reimplemented in clang::MultiplexExternalSemaSource, and clang::ExternalSemaSource.
Definition at line 298 of file ExternalASTSource.h.
Referenced by clang::ExternalSemaSource::isA().
layoutRecordType()
bool ExternalASTSource::layoutRecordType (const RecordDecl * Record, uint64_t & Size, uint64_t & Alignment, llvm::DenseMap< const FieldDecl *, uint64_t > & FieldOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > & BaseOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > & VirtualBaseOffsets) virtual
Perform layout on the given record.
This routine allows the external AST source to provide an specific layout for a record, overriding the layout that would normally be constructed. It is intended for clients who receive specific layout details rather than source code (such as LLDB). The client is expected to fill in the field offsets, base offsets, virtual base offsets, and complete object size.
Parameters
Record The record whose layout is being requested.
Size The final size of the record, in bits.
Alignment The final alignment of the record, in bits.
FieldOffsets The offset of each of the fields within the record, expressed in bits. All of the fields must be provided with offsets.
BaseOffsets The offset of each of the direct, non-virtual base classes. If any bases are not given offsets, the bases will be laid out according to the ABI.
VirtualBaseOffsets The offset of each of the virtual base classes (either direct or not). If any bases are not given offsets, the bases will be laid out according to the ABI.
Returns
true if the record layout was provided, false otherwise.
Reimplemented in clang::MultiplexExternalSemaSource, and clang::LayoutOverrideSource.
Definition at line 63 of file ExternalASTSource.cpp.
PrintStats()
void ExternalASTSource::PrintStats () virtual
Print any statistics that have been gathered regarding the external AST source.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 61 of file ExternalASTSource.cpp.
ReadComments()
void ExternalASTSource::ReadComments () virtual
Loads comment ranges.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 53 of file ExternalASTSource.cpp.
SetExternalVisibleDeclsForName()
DeclContext::lookup_result ExternalASTSource::SetExternalVisibleDeclsForName (const DeclContext * DC, DeclarationName Name, ArrayRef< NamedDecl * > Decls) static protected
Definition at line 1416 of file DeclBase.cpp.
SetNoExternalVisibleDeclsForName()
DeclContext::lookup_result ExternalASTSource::SetNoExternalVisibleDeclsForName (const DeclContext * DC, DeclarationName Name) static protected
Definition at line 1401 of file DeclBase.cpp.
StartedDeserializing()
void ExternalASTSource::StartedDeserializing () virtual
Notify ExternalASTSource that we started deserialization of a decl or type so until FinishedDeserializing is called there may be decls that are initializing.
Must be paired with FinishedDeserializing.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 55 of file ExternalASTSource.cpp.
Referenced by clang::ExternalASTSource::Deserializing::Deserializing().
StartTranslationUnit()
void ExternalASTSource::StartTranslationUnit (ASTConsumer * Consumer) virtual
Function that will be invoked when we begin parsing a new translation unit involving this external AST source.
The default implementation of this method is a no-op.
Reimplemented in clang::ASTReader, and clang::MultiplexExternalSemaSource.
Definition at line 59 of file ExternalASTSource.cpp.
updateOutOfDateIdentifier()
virtual void clang::ExternalASTSource::updateOutOfDateIdentifier (IdentifierInfo & II) inline virtual
Update an out-of-date identifier.
Reimplemented in clang::ASTReader.
Definition at line 141 of file ExternalASTSource.h.
Referenced by clang::Decl::updateOutOfDate().
Friends And Related Function Documentation
ExternalSemaSource
friend class ExternalSemaSource friend
Definition at line 61 of file ExternalASTSource.h.
The documentation for this class was generated from the following files:
include/clang/AST/ExternalASTSource.h
lib/AST/DeclBase.cpp
lib/AST/ExternalASTSource.cpp