clang: clang::SVETypeFlags Class Reference
clang::SVETypeFlags Class Reference
Flags to identify the types for overloaded SVE builtins.
#include "clang/Basic/TargetBuiltins.h"
Public Types
enum EltType
enum MemEltType
enum MergeType
enum ImmCheckType
Public Member Functions
SVETypeFlags (uint64_t F)
EltType getEltType () const
MemEltType getMemEltType () const
MergeType getMergeType () const
unsigned getSplatOperand () const
bool hasSplatOperand () const
bool isLoad () const
bool isStore () const
bool isGatherLoad () const
bool isScatterStore () const
bool isStructLoad () const
bool isStructStore () const
bool isZExtReturn () const
bool isByteIndexed () const
bool isOverloadNone () const
bool isOverloadWhileOrMultiVecCvt () const
bool isOverloadDefault () const
bool isOverloadWhileRW () const
bool isOverloadCvt () const
bool isPrefetch () const
bool isReverseCompare () const
bool isAppendSVALL () const
bool isInsertOp1SVALL () const
bool isGatherPrefetch () const
bool isReverseUSDOT () const
bool isReverseMergeAnyBinOp () const
bool isReverseMergeAnyAccOp () const
bool isUndef () const
bool isTupleCreate () const
bool isTupleGet () const
bool isTupleSet () const
bool isReadZA () const
bool isWriteZA () const
bool isReductionQV () const
uint64_t getBits () const
bool isFlagSet (uint64_t Flag) const
Detailed Description
Flags to identify the types for overloaded SVE builtins.
Definition at line 222 of file TargetBuiltins.h.
Member Enumeration Documentation
EltType
enum clang::SVETypeFlags::EltType
Definition at line 234 of file TargetBuiltins.h.
ImmCheckType
enum clang::SVETypeFlags::ImmCheckType
Definition at line 252 of file TargetBuiltins.h.
MemEltType
enum clang::SVETypeFlags::MemEltType
Definition at line 240 of file TargetBuiltins.h.
MergeType
enum clang::SVETypeFlags::MergeType
Definition at line 246 of file TargetBuiltins.h.
Constructor & Destructor Documentation
SVETypeFlags()
clang::SVETypeFlags::SVETypeFlags (uint64_t F) inline
Definition at line 258 of file TargetBuiltins.h.
Member Function Documentation
getBits()
uint64_t clang::SVETypeFlags::getBits () const inline
Definition at line 315 of file TargetBuiltins.h.
getEltType()
EltType clang::SVETypeFlags::getEltType () const inline
Definition at line 265 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::getEltType(), clang::CodeGen::CodeGenFunction::getSVEPredType(), and clang::CodeGen::CodeGenFunction::getSVEType().
getMemEltType()
MemEltType clang::SVETypeFlags::getMemEltType () const inline
Definition at line 269 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::SVEBuiltinMemEltTy().
getMergeType()
MergeType clang::SVETypeFlags::getMergeType () const inline
Definition at line 273 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
getSplatOperand()
unsigned clang::SVETypeFlags::getSplatOperand () const inline
Definition at line 277 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitSVEPMull().
hasSplatOperand()
bool clang::SVETypeFlags::hasSplatOperand () const inline
Definition at line 281 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitSVEPMull().
isAppendSVALL()
bool clang::SVETypeFlags::isAppendSVALL () const inline
Definition at line 302 of file TargetBuiltins.h.
isByteIndexed()
bool clang::SVETypeFlags::isByteIndexed () const inline
Definition at line 292 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitSVEGatherLoad().
isFlagSet()
bool clang::SVETypeFlags::isFlagSet (uint64_t Flag) const inline
Definition at line 316 of file TargetBuiltins.h.
isGatherLoad()
bool clang::SVETypeFlags::isGatherLoad () const inline
Definition at line 287 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isGatherPrefetch()
bool clang::SVETypeFlags::isGatherPrefetch () const inline
Definition at line 304 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isInsertOp1SVALL()
bool clang::SVETypeFlags::isInsertOp1SVALL () const inline
Definition at line 303 of file TargetBuiltins.h.
isLoad()
bool clang::SVETypeFlags::isLoad () const inline
Definition at line 285 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SMEBuiltinExpr(), and clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isOverloadCvt()
bool clang::SVETypeFlags::isOverloadCvt () const inline
Definition at line 299 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::getSVEOverloadTypes().
isOverloadDefault()
bool clang::SVETypeFlags::isOverloadDefault () const inline
Definition at line 297 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::getSVEOverloadTypes().
isOverloadNone()
bool clang::SVETypeFlags::isOverloadNone () const inline
Definition at line 293 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SMEBuiltinExpr(), and clang::CodeGen::CodeGenFunction::getSVEOverloadTypes().
isOverloadWhileOrMultiVecCvt()
bool clang::SVETypeFlags::isOverloadWhileOrMultiVecCvt () const inline
Definition at line 294 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::getSVEOverloadTypes().
isOverloadWhileRW()
bool clang::SVETypeFlags::isOverloadWhileRW () const inline
Definition at line 298 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::getSVEOverloadTypes().
isPrefetch()
bool clang::SVETypeFlags::isPrefetch () const inline
Definition at line 300 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isReadZA()
bool clang::SVETypeFlags::isReadZA () const inline
Definition at line 312 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SMEBuiltinExpr(), and clang::CodeGen::CodeGenFunction::EmitSMEReadWrite().
isReductionQV()
bool clang::SVETypeFlags::isReductionQV () const inline
Definition at line 314 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::getSVEOverloadTypes().
isReverseCompare()
bool clang::SVETypeFlags::isReverseCompare () const inline
Definition at line 301 of file TargetBuiltins.h.
isReverseMergeAnyAccOp()
bool clang::SVETypeFlags::isReverseMergeAnyAccOp () const inline
Definition at line 307 of file TargetBuiltins.h.
isReverseMergeAnyBinOp()
bool clang::SVETypeFlags::isReverseMergeAnyBinOp () const inline
Definition at line 306 of file TargetBuiltins.h.
isReverseUSDOT()
bool clang::SVETypeFlags::isReverseUSDOT () const inline
Definition at line 305 of file TargetBuiltins.h.
isScatterStore()
bool clang::SVETypeFlags::isScatterStore () const inline
Definition at line 288 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isStore()
bool clang::SVETypeFlags::isStore () const inline
Definition at line 286 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SMEBuiltinExpr(), and clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isStructLoad()
bool clang::SVETypeFlags::isStructLoad () const inline
Definition at line 289 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isStructStore()
bool clang::SVETypeFlags::isStructStore () const inline
Definition at line 290 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isTupleCreate()
bool clang::SVETypeFlags::isTupleCreate () const inline
Definition at line 309 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr(), and clang::CodeGen::CodeGenFunction::EmitSVETupleCreate().
isTupleGet()
bool clang::SVETypeFlags::isTupleGet () const inline
Definition at line 310 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitSVETupleSetOrGet(), and clang::CodeGen::CodeGenFunction::GetAArch64SVEProcessedOperands().
isTupleSet()
bool clang::SVETypeFlags::isTupleSet () const inline
Definition at line 311 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitSVETupleSetOrGet(), and clang::CodeGen::CodeGenFunction::GetAArch64SVEProcessedOperands().
isUndef()
bool clang::SVETypeFlags::isUndef () const inline
Definition at line 308 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
isWriteZA()
bool clang::SVETypeFlags::isWriteZA () const inline
Definition at line 313 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SMEBuiltinExpr(), and clang::CodeGen::CodeGenFunction::EmitSMEReadWrite().
isZExtReturn()
bool clang::SVETypeFlags::isZExtReturn () const inline
Definition at line 291 of file TargetBuiltins.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAArch64SVEBuiltinExpr().
The documentation for this class was generated from the following file:
include/clang/Basic/TargetBuiltins.h