clang: clang::CodeGen::RegionCodeGenTy Class Reference
clang::CodeGen::RegionCodeGenTy Class Reference final
Class provides a way to call simple version of codegen for OpenMP region, or an advanced with possible pre|post-actions in codegen.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGOpenMPRuntime.h"
Public Member Functions
template<typename Callable >
RegionCodeGenTy (Callable &&CodeGen, std::enable_if_t<!std::is_same< std::remove_reference_t< Callable >, RegionCodeGenTy >::value > *=nullptr)
void setAction (PrePostActionTy &Action) const
void operator() (CodeGenFunction &CGF) const
Detailed Description
Class provides a way to call simple version of codegen for OpenMP region, or an advanced with possible pre|post-actions in codegen.
Definition at line 68 of file CGOpenMPRuntime.h.
Constructor & Destructor Documentation
RegionCodeGenTy()
template<typename Callable > clang::CodeGen::RegionCodeGenTy::RegionCodeGenTy (Callable && CodeGen, std::enable_if_t<!std::is_same< std::remove_reference_t< Callable >, RegionCodeGenTy >::value > * = nullptr) inline
Definition at line 82 of file CGOpenMPRuntime.h.
Member Function Documentation
operator()()
void RegionCodeGenTy::operator() (CodeGenFunction & CGF) const
Definition at line 596 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::EHStack, and clang::CodeGen::NormalAndEHCleanup.
setAction()
void clang::CodeGen::RegionCodeGenTy::setAction (PrePostActionTy & Action) const inline
Definition at line 89 of file CGOpenMPRuntime.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitCriticalRegion(), clang::CodeGen::CGOpenMPRuntime::emitMaskedRegion(), clang::CodeGen::CGOpenMPRuntime::emitMasterRegion(), clang::CodeGen::CGOpenMPRuntime::emitOrderedRegion(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelOutlinedFunction(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CGOpenMPRuntime::emitTargetOutlinedFunction(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskgroupRegion(), clang::CodeGen::CGOpenMPRuntime::emitTaskOutlinedFunction(), and clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsOutlinedFunction().
The documentation for this class was generated from the following files:
lib/CodeGen/CGOpenMPRuntime.h
lib/CodeGen/CGOpenMPRuntime.cpp