clang: clang::ASTNodeTraverser< Derived, NodeDelegateType > Class Template Reference
clang::ASTNodeTraverser< Derived, NodeDelegateType > Class Template Reference
ASTNodeTraverser traverses the Clang AST for dumping purposes.
#include "clang/AST/ASTNodeTraverser.h"
Public Member Functions
void setDeserialize (bool D)
bool getDeserialize () const
void SetTraversalKind (TraversalKind TK)
TraversalKind GetTraversalKind () const
void Visit (const Decl *D)
void Visit (const Stmt *Node, StringRef Label={})
void Visit (QualType T)
void Visit (const Type *T)
void Visit (const Attr *A)
void Visit (const CXXCtorInitializer *Init)
void Visit (const TemplateArgument &A, SourceRange R={}, const Decl *From=nullptr, const char *Label=nullptr)
void Visit (const BlockDecl::Capture &C)
void Visit (const OMPClause *C)
void Visit (const GenericSelectionExpr::ConstAssociation &A)
void Visit (const concepts::Requirement *R)
void Visit (const APValue &Value, QualType Ty)
void Visit (const comments::Comment *C, const comments::FullComment *FC)
void Visit (const DynTypedNode &N)
void dumpDeclContext (const DeclContext *DC)
void dumpTemplateParameters (const TemplateParameterList *TPL)
void dumpASTTemplateArgumentListInfo (const ASTTemplateArgumentListInfo *TALI)
void dumpTemplateArgumentLoc (const TemplateArgumentLoc &A, const Decl *From=nullptr, const char *Label=nullptr)
void dumpTemplateArgumentList (const TemplateArgumentList &TAL)
void dumpObjCTypeParamList (const ObjCTypeParamList *typeParams)
void VisitComplexType (const ComplexType *T)
void VisitLocInfoType (const LocInfoType *T)
void VisitPointerType (const PointerType *T)
void VisitBlockPointerType (const BlockPointerType *T)
void VisitReferenceType (const ReferenceType *T)
void VisitMemberPointerType (const MemberPointerType *T)
void VisitArrayType (const ArrayType *T)
void VisitVariableArrayType (const VariableArrayType *T)
void VisitDependentSizedArrayType (const DependentSizedArrayType *T)
void VisitDependentSizedExtVectorType (const DependentSizedExtVectorType *T)
void VisitVectorType (const VectorType *T)
void VisitFunctionType (const FunctionType *T)
void VisitFunctionProtoType (const FunctionProtoType *T)
void VisitTypeOfExprType (const TypeOfExprType *T)
void VisitDecltypeType (const DecltypeType *T)
void VisitUnaryTransformType (const UnaryTransformType *T)
void VisitAttributedType (const AttributedType *T)
void VisitBTFTagAttributedType (const BTFTagAttributedType *T)
void VisitSubstTemplateTypeParmType (const SubstTemplateTypeParmType *T)
void VisitSubstTemplateTypeParmPackType (const SubstTemplateTypeParmPackType *T)
void VisitTemplateSpecializationType (const TemplateSpecializationType *T)
void VisitObjCObjectPointerType (const ObjCObjectPointerType *T)
void VisitAtomicType (const AtomicType *T)
void VisitPipeType (const PipeType *T)
void VisitAdjustedType (const AdjustedType *T)
void VisitPackExpansionType (const PackExpansionType *T)
void VisitTypedefDecl (const TypedefDecl *D)
void VisitEnumConstantDecl (const EnumConstantDecl *D)
void VisitFunctionDecl (const FunctionDecl *D)
void VisitFieldDecl (const FieldDecl *D)
void VisitVarDecl (const VarDecl *D)
void VisitDecompositionDecl (const DecompositionDecl *D)
void VisitBindingDecl (const BindingDecl *D)
void VisitFileScopeAsmDecl (const FileScopeAsmDecl *D)
void VisitCapturedDecl (const CapturedDecl *D)
void VisitOMPThreadPrivateDecl (const OMPThreadPrivateDecl *D)
void VisitOMPDeclareReductionDecl (const OMPDeclareReductionDecl *D)
void VisitOMPDeclareMapperDecl (const OMPDeclareMapperDecl *D)
void VisitOMPCapturedExprDecl (const OMPCapturedExprDecl *D)
void VisitOMPAllocateDecl (const OMPAllocateDecl *D)
template<typename SpecializationDecl >
void dumpTemplateDeclSpecialization (const SpecializationDecl *D)
template<typename TemplateDecl >
void dumpTemplateDecl (const TemplateDecl *D)
void VisitTypeAliasDecl (const TypeAliasDecl *D)
void VisitTypeAliasTemplateDecl (const TypeAliasTemplateDecl *D)
void VisitStaticAssertDecl (const StaticAssertDecl *D)
void VisitFunctionTemplateDecl (const FunctionTemplateDecl *D)
void VisitClassTemplateDecl (const ClassTemplateDecl *D)
void VisitClassTemplateSpecializationDecl (const ClassTemplateSpecializationDecl *D)
void VisitClassTemplatePartialSpecializationDecl (const ClassTemplatePartialSpecializationDecl *D)
void VisitClassScopeFunctionSpecializationDecl (const ClassScopeFunctionSpecializationDecl *D)
void VisitVarTemplateDecl (const VarTemplateDecl *D)
void VisitBuiltinTemplateDecl (const BuiltinTemplateDecl *D)
void VisitVarTemplateSpecializationDecl (const VarTemplateSpecializationDecl *D)
void VisitVarTemplatePartialSpecializationDecl (const VarTemplatePartialSpecializationDecl *D)
void VisitTemplateTypeParmDecl (const TemplateTypeParmDecl *D)
void VisitNonTypeTemplateParmDecl (const NonTypeTemplateParmDecl *D)
void VisitTemplateTemplateParmDecl (const TemplateTemplateParmDecl *D)
void VisitConceptDecl (const ConceptDecl *D)
void VisitConceptSpecializationExpr (const ConceptSpecializationExpr *CSE)
void VisitUsingShadowDecl (const UsingShadowDecl *D)
void VisitFriendDecl (const FriendDecl *D)
void VisitObjCMethodDecl (const ObjCMethodDecl *D)
void VisitObjCCategoryDecl (const ObjCCategoryDecl *D)
void VisitObjCInterfaceDecl (const ObjCInterfaceDecl *D)
void VisitObjCImplementationDecl (const ObjCImplementationDecl *D)
void VisitBlockDecl (const BlockDecl *D)
void VisitDeclStmt (const DeclStmt *Node)
void VisitAttributedStmt (const AttributedStmt *Node)
void VisitCXXCatchStmt (const CXXCatchStmt *Node)
void VisitCapturedStmt (const CapturedStmt *Node)
void VisitOMPExecutableDirective (const OMPExecutableDirective *Node)
void VisitInitListExpr (const InitListExpr *ILE)
void VisitBlockExpr (const BlockExpr *Node)
void VisitOpaqueValueExpr (const OpaqueValueExpr *Node)
void VisitGenericSelectionExpr (const GenericSelectionExpr *E)
void VisitRequiresExpr (const RequiresExpr *E)
void VisitLambdaExpr (const LambdaExpr *Node)
void VisitSizeOfPackExpr (const SizeOfPackExpr *Node)
void VisitSubstNonTypeTemplateParmExpr (const SubstNonTypeTemplateParmExpr *E)
void VisitSubstNonTypeTemplateParmPackExpr (const SubstNonTypeTemplateParmPackExpr *E)
void VisitObjCAtCatchStmt (const ObjCAtCatchStmt *Node)
void VisitCXXForRangeStmt (const CXXForRangeStmt *Node)
void VisitCallExpr (const CallExpr *Node)
void VisitCXXRewrittenBinaryOperator (const CXXRewrittenBinaryOperator *Node)
void VisitExpressionTemplateArgument (const TemplateArgument &TA)
void VisitTypeTemplateArgument (const TemplateArgument &TA)
void VisitPackTemplateArgument (const TemplateArgument &TA)
Public Member Functions inherited from clang::declvisitor::Base< llvm::make_const_ptr, Derived, void >
void Visit (PTR(Decl) D)
void VisitDecl (PTR(Decl) D)
Public Member Functions inherited from clang::StmtVisitorBase< llvm::make_const_ptr, Derived, void, ParamTys... >
void Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) void VisitStmt(PTR(Stmt) Node
Public Member Functions inherited from clang::comments::CommentVisitorBase< llvm::make_const_ptr, Derived, void, ParamTys... >
void visit (PTR(Comment) C, ParamTys... P)
void visitComment (PTR(Comment) C, ParamTys... P)
Public Member Functions inherited from clang::TypeVisitor< Derived >
void Visit (const Type *T)
Performs the operation associated with this visitor object.
void VisitType (const Type *)
Method called if ImpClass doesn't provide specific handler for some type class.
Public Member Functions inherited from clang::attrvisitor::Base< llvm::make_const_ptr, Derived, void, ParamTys... >
void Visit (PTR(Attr) A)
void VisitAttr (PTR(Attr))
Public Member Functions inherited from clang::templateargumentvisitor::Base< llvm::make_const_ref, Derived, void, ParamTys... >
void Visit (REF(TemplateArgument) TA, ParamTys... P)
VISIT_METHOD (Null)
VISIT_METHOD (Type)
VISIT_METHOD (Declaration)
VISIT_METHOD (NullPtr)
VISIT_METHOD (Integral)
VISIT_METHOD (Template)
VISIT_METHOD (TemplateExpansion)
VISIT_METHOD (Expression)
VISIT_METHOD (Pack)
void VisitTemplateArgument (REF(TemplateArgument), ParamTys...)
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< llvm::make_const_ptr, Derived, void, ParamTys... >
ParamTys P
Detailed Description
template<typename Derived, typename NodeDelegateType>
class clang::ASTNodeTraverser< Derived, NodeDelegateType >
ASTNodeTraverser traverses the Clang AST for dumping purposes.
The Derived::doGetNodeDelegate() method is required to be an accessible member which returns a reference of type NodeDelegateType & which implements the following interface:
struct { template <typename Fn> void AddChild(Fn DoAddChild); template <typename Fn> void AddChild(StringRef Label, Fn DoAddChild);
void Visit(const comments::Comment *C, const comments::FullComment *FC); void Visit(const Attr *A); void Visit(const TemplateArgument &TA, SourceRange R = {}, const Decl *From = nullptr, StringRef Label = {}); void Visit(const Stmt *Node); void Visit(const Type *T); void Visit(QualType T); void Visit(const Decl *D); void Visit(const CXXCtorInitializer *Init); void Visit(const OMPClause *C); void Visit(const BlockDecl::Capture &C); void Visit(const GenericSelectionExpr::ConstAssociation &A); void Visit(const concepts::Requirement *R); void Visit(const APValue &Value, QualType Ty); };
Definition at line 61 of file ASTNodeTraverser.h.
Member Function Documentation
dumpASTTemplateArgumentListInfo()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpASTTemplateArgumentListInfo (const ASTTemplateArgumentListInfo * TALI) inline
Definition at line 313 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitClassScopeFunctionSpecializationDecl().
dumpDeclContext()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpDeclContext (const DeclContext * DC) inline
Definition at line 293 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::Visit(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitObjCMethodDecl().
dumpObjCTypeParamList()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpObjCTypeParamList (const ObjCTypeParamList * typeParams) inline
Definition at line 332 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitObjCCategoryDecl(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitObjCInterfaceDecl().
dumpTemplateArgumentList()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentList (const TemplateArgumentList & TAL) inline
Definition at line 327 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitClassTemplateSpecializationDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFunctionDecl(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVarTemplateSpecializationDecl().
dumpTemplateArgumentLoc()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateArgumentLoc (const TemplateArgumentLoc & A, const Decl * From = nullptr, const char * Label = nullptr) inline
Definition at line 321 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpASTTemplateArgumentListInfo(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitConceptSpecializationExpr(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTemplateTemplateParmDecl().
dumpTemplateDecl()
template<typename Derived , typename NodeDelegateType > template<typename TemplateDecl > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDecl (const TemplateDecl * D) inline
Definition at line 527 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitClassTemplateDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFunctionTemplateDecl(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVarTemplateDecl().
dumpTemplateDeclSpecialization()
template<typename Derived , typename NodeDelegateType > template<typename SpecializationDecl > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateDeclSpecialization (const SpecializationDecl * D) inline
Definition at line 508 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpTemplateDecl().
dumpTemplateParameters()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::dumpTemplateParameters (const TemplateParameterList * TPL) inline
Definition at line 301 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpTemplateDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitBuiltinTemplateDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitClassTemplatePartialSpecializationDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitConceptDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitLambdaExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTemplateTemplateParmDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTypeAliasTemplateDecl(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVarTemplatePartialSpecializationDecl().
getDeserialize()
template<typename Derived , typename NodeDelegateType > bool clang::ASTNodeTraverser< Derived, NodeDelegateType >::getDeserialize () const inline
Definition at line 83 of file ASTNodeTraverser.h.
GetTraversalKind()
template<typename Derived , typename NodeDelegateType > TraversalKind clang::ASTNodeTraverser< Derived, NodeDelegateType >::GetTraversalKind () const inline
Definition at line 86 of file ASTNodeTraverser.h.
setDeserialize()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::setDeserialize (bool D) inline
Definition at line 82 of file ASTNodeTraverser.h.
SetTraversalKind()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::SetTraversalKind (TraversalKind TK) inline
Definition at line 85 of file ASTNodeTraverser.h.
Visit() [1/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const APValue & Value, QualType Ty) inline
Definition at line 255 of file ASTNodeTraverser.h.
Visit() [2/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const Attr * A) inline
Definition at line 184 of file ASTNodeTraverser.h.
Visit() [3/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const BlockDecl::Capture & C) inline
Definition at line 208 of file ASTNodeTraverser.h.
Visit() [4/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const comments::Comment * C, const comments::FullComment * FC) inline
Definition at line 259 of file ASTNodeTraverser.h.
Visit() [5/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const concepts::Requirement * R) inline
Definition at line 233 of file ASTNodeTraverser.h.
Visit() [6/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const CXXCtorInitializer * Init) inline
Definition at line 191 of file ASTNodeTraverser.h.
Visit() [7/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const Decl * D) inline
Definition at line 88 of file ASTNodeTraverser.h.
Referenced by clang::comments::Comment::dump(), clang::APValue::dump(), clang::QualType::dump(), clang::comments::Comment::dumpColor(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpDeclContext(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpObjCTypeParamList(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpTemplateArgumentList(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpTemplateArgumentLoc(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpTemplateDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpTemplateDeclSpecialization(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::dumpTemplateParameters(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::Visit(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitAdjustedType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitArrayType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitAtomicType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitAttributedStmt(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitAttributedType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitBindingDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitBlockDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitBlockExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitBlockPointerType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitBTFTagAttributedType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitCallExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitCapturedDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitCapturedStmt(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitClassScopeFunctionSpecializationDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitComplexType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitConceptDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitCXXCatchStmt(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitCXXForRangeStmt(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitCXXRewrittenBinaryOperator(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitDeclStmt(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitDecltypeType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitDecompositionDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitDependentSizedArrayType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitDependentSizedExtVectorType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitEnumConstantDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitExpressionTemplateArgument(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFieldDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFileScopeAsmDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFriendDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFunctionDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFunctionProtoType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFunctionType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitGenericSelectionExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitInitListExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitLambdaExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitLocInfoType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitMemberPointerType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitNonTypeTemplateParmDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitObjCAtCatchStmt(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitObjCImplementationDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitObjCMethodDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitObjCObjectPointerType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitOMPAllocateDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitOMPCapturedExprDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitOMPDeclareMapperDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitOMPDeclareReductionDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitOMPExecutableDirective(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitOMPThreadPrivateDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitOpaqueValueExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitPackExpansionType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitPackTemplateArgument(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitPipeType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitPointerType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitReferenceType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitRequiresExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitSizeOfPackExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitStaticAssertDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitSubstNonTypeTemplateParmExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitSubstNonTypeTemplateParmPackExpr(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitSubstTemplateTypeParmPackType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitSubstTemplateTypeParmType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTemplateSpecializationType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTemplateTypeParmDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTypeAliasDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTypeAliasTemplateDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTypedefDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTypeOfExprType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitTypeTemplateArgument(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitUnaryTransformType(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitUsingShadowDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVarDecl(), clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVariableArrayType(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVectorType().
Visit() [8/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const DynTypedNode & N) inline
Definition at line 275 of file ASTNodeTraverser.h.
Visit() [9/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const GenericSelectionExpr::ConstAssociation & A) inline
Definition at line 224 of file ASTNodeTraverser.h.
Visit() [10/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const OMPClause * C) inline
Definition at line 216 of file ASTNodeTraverser.h.
Visit() [11/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const Stmt * Node, StringRef Label = {}) inline
Definition at line 122 of file ASTNodeTraverser.h.
Visit() [12/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const TemplateArgument & A, SourceRange R = {}, const Decl * From = nullptr, const char * Label = nullptr) inline
Definition at line 200 of file ASTNodeTraverser.h.
Visit() [13/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (const Type * T) inline
Definition at line 170 of file ASTNodeTraverser.h.
Visit() [14/14]
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::Visit (QualType T) inline
Definition at line 159 of file ASTNodeTraverser.h.
VisitAdjustedType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAdjustedType (const AdjustedType * T) inline
Definition at line 409 of file ASTNodeTraverser.h.
VisitArrayType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitArrayType (const ArrayType * T) inline
Definition at line 356 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVariableArrayType().
VisitAtomicType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAtomicType (const AtomicType * T) inline
Definition at line 407 of file ASTNodeTraverser.h.
VisitAttributedStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAttributedStmt (const AttributedStmt * Node) inline
Definition at line 679 of file ASTNodeTraverser.h.
VisitAttributedType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitAttributedType (const AttributedType * T) inline
Definition at line 385 of file ASTNodeTraverser.h.
VisitBindingDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBindingDecl (const BindingDecl * D) inline
Definition at line 467 of file ASTNodeTraverser.h.
VisitBlockDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockDecl (const BlockDecl * D) inline
Definition at line 665 of file ASTNodeTraverser.h.
VisitBlockExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockExpr (const BlockExpr * Node) inline
Definition at line 703 of file ASTNodeTraverser.h.
VisitBlockPointerType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBlockPointerType (const BlockPointerType * T) inline
Definition at line 346 of file ASTNodeTraverser.h.
VisitBTFTagAttributedType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBTFTagAttributedType (const BTFTagAttributedType * T) inline
Definition at line 389 of file ASTNodeTraverser.h.
VisitBuiltinTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitBuiltinTemplateDecl (const BuiltinTemplateDecl * D) inline
Definition at line 578 of file ASTNodeTraverser.h.
VisitCallExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCallExpr (const CallExpr * Node) inline
Definition at line 775 of file ASTNodeTraverser.h.
VisitCapturedDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCapturedDecl (const CapturedDecl * D) inline
Definition at line 478 of file ASTNodeTraverser.h.
VisitCapturedStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCapturedStmt (const CapturedStmt * Node) inline
Definition at line 688 of file ASTNodeTraverser.h.
VisitClassScopeFunctionSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassScopeFunctionSpecializationDecl (const ClassScopeFunctionSpecializationDecl * D) inline
Definition at line 571 of file ASTNodeTraverser.h.
VisitClassTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplateDecl (const ClassTemplateDecl * D) inline
Definition at line 556 of file ASTNodeTraverser.h.
VisitClassTemplatePartialSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplatePartialSpecializationDecl (const ClassTemplatePartialSpecializationDecl * D) inline
Definition at line 565 of file ASTNodeTraverser.h.
VisitClassTemplateSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitClassTemplateSpecializationDecl (const ClassTemplateSpecializationDecl * D) inline
Definition at line 560 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitClassTemplatePartialSpecializationDecl().
VisitComplexType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitComplexType (const ComplexType * T) inline
Definition at line 341 of file ASTNodeTraverser.h.
VisitConceptDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptDecl (const ConceptDecl * D) inline
Definition at line 620 of file ASTNodeTraverser.h.
VisitConceptSpecializationExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitConceptSpecializationExpr (const ConceptSpecializationExpr * CSE) inline
Definition at line 625 of file ASTNodeTraverser.h.
VisitCXXCatchStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXCatchStmt (const CXXCatchStmt * Node) inline
Definition at line 684 of file ASTNodeTraverser.h.
VisitCXXForRangeStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXForRangeStmt (const CXXForRangeStmt * Node) inline
Definition at line 766 of file ASTNodeTraverser.h.
VisitCXXRewrittenBinaryOperator()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitCXXRewrittenBinaryOperator (const CXXRewrittenBinaryOperator * Node) inline
Definition at line 786 of file ASTNodeTraverser.h.
VisitDeclStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDeclStmt (const DeclStmt * Node) inline
Definition at line 674 of file ASTNodeTraverser.h.
VisitDecltypeType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDecltypeType (const DecltypeType * T) inline
Definition at line 379 of file ASTNodeTraverser.h.
VisitDecompositionDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDecompositionDecl (const DecompositionDecl * D) inline
Definition at line 461 of file ASTNodeTraverser.h.
VisitDependentSizedArrayType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDependentSizedArrayType (const DependentSizedArrayType * T) inline
Definition at line 361 of file ASTNodeTraverser.h.
VisitDependentSizedExtVectorType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitDependentSizedExtVectorType (const DependentSizedExtVectorType * T) inline
Definition at line 365 of file ASTNodeTraverser.h.
VisitEnumConstantDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitEnumConstantDecl (const EnumConstantDecl * D) inline
Definition at line 419 of file ASTNodeTraverser.h.
VisitExpressionTemplateArgument()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitExpressionTemplateArgument (const TemplateArgument & TA) inline
Definition at line 795 of file ASTNodeTraverser.h.
VisitFieldDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFieldDecl (const FieldDecl * D) inline
Definition at line 446 of file ASTNodeTraverser.h.
VisitFileScopeAsmDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFileScopeAsmDecl (const FileScopeAsmDecl * D) inline
Definition at line 474 of file ASTNodeTraverser.h.
VisitFriendDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFriendDecl (const FriendDecl * D) inline
Definition at line 636 of file ASTNodeTraverser.h.
VisitFunctionDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl (const FunctionDecl * D) inline
Definition at line 424 of file ASTNodeTraverser.h.
VisitFunctionProtoType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionProtoType (const FunctionProtoType * T) inline
Definition at line 371 of file ASTNodeTraverser.h.
VisitFunctionTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionTemplateDecl (const FunctionTemplateDecl * D) inline
Definition at line 552 of file ASTNodeTraverser.h.
VisitFunctionType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionType (const FunctionType * T) inline
Definition at line 370 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitFunctionProtoType().
VisitGenericSelectionExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitGenericSelectionExpr (const GenericSelectionExpr * E) inline
Definition at line 710 of file ASTNodeTraverser.h.
VisitInitListExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitInitListExpr (const InitListExpr * ILE) inline
Definition at line 697 of file ASTNodeTraverser.h.
VisitLambdaExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLambdaExpr (const LambdaExpr * Node) inline
Definition at line 726 of file ASTNodeTraverser.h.
VisitLocInfoType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitLocInfoType (const LocInfoType * T) inline
Definition at line 342 of file ASTNodeTraverser.h.
VisitMemberPointerType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitMemberPointerType (const MemberPointerType * T) inline
Definition at line 352 of file ASTNodeTraverser.h.
VisitNonTypeTemplateParmDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitNonTypeTemplateParmDecl (const NonTypeTemplateParmDecl * D) inline
Definition at line 603 of file ASTNodeTraverser.h.
VisitObjCAtCatchStmt()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCAtCatchStmt (const ObjCAtCatchStmt * Node) inline
Definition at line 761 of file ASTNodeTraverser.h.
VisitObjCCategoryDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCCategoryDecl (const ObjCCategoryDecl * D) inline
Definition at line 652 of file ASTNodeTraverser.h.
VisitObjCImplementationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCImplementationDecl (const ObjCImplementationDecl * D) inline
Definition at line 660 of file ASTNodeTraverser.h.
VisitObjCInterfaceDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCInterfaceDecl (const ObjCInterfaceDecl * D) inline
Definition at line 656 of file ASTNodeTraverser.h.
VisitObjCMethodDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCMethodDecl (const ObjCMethodDecl * D) inline
Definition at line 641 of file ASTNodeTraverser.h.
VisitObjCObjectPointerType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitObjCObjectPointerType (const ObjCObjectPointerType * T) inline
Definition at line 404 of file ASTNodeTraverser.h.
VisitOMPAllocateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPAllocateDecl (const OMPAllocateDecl * D) inline
Definition at line 500 of file ASTNodeTraverser.h.
VisitOMPCapturedExprDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPCapturedExprDecl (const OMPCapturedExprDecl * D) inline
Definition at line 496 of file ASTNodeTraverser.h.
VisitOMPDeclareMapperDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPDeclareMapperDecl (const OMPDeclareMapperDecl * D) inline
Definition at line 491 of file ASTNodeTraverser.h.
VisitOMPDeclareReductionDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPDeclareReductionDecl (const OMPDeclareReductionDecl * D) inline
Definition at line 485 of file ASTNodeTraverser.h.
VisitOMPExecutableDirective()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPExecutableDirective (const OMPExecutableDirective * Node) inline
Definition at line 692 of file ASTNodeTraverser.h.
VisitOMPThreadPrivateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOMPThreadPrivateDecl (const OMPThreadPrivateDecl * D) inline
Definition at line 480 of file ASTNodeTraverser.h.
VisitOpaqueValueExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitOpaqueValueExpr (const OpaqueValueExpr * Node) inline
Definition at line 705 of file ASTNodeTraverser.h.
VisitPackExpansionType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPackExpansionType (const PackExpansionType * T) inline
Definition at line 410 of file ASTNodeTraverser.h.
VisitPackTemplateArgument()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPackTemplateArgument (const TemplateArgument & TA) inline
Definition at line 803 of file ASTNodeTraverser.h.
VisitPipeType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPipeType (const PipeType * T) inline
Definition at line 408 of file ASTNodeTraverser.h.
VisitPointerType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitPointerType (const PointerType * T) inline
Definition at line 345 of file ASTNodeTraverser.h.
VisitReferenceType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitReferenceType (const ReferenceType * T) inline
Definition at line 349 of file ASTNodeTraverser.h.
VisitRequiresExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitRequiresExpr (const RequiresExpr * E) inline
Definition at line 719 of file ASTNodeTraverser.h.
VisitSizeOfPackExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSizeOfPackExpr (const SizeOfPackExpr * Node) inline
Definition at line 746 of file ASTNodeTraverser.h.
VisitStaticAssertDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitStaticAssertDecl (const StaticAssertDecl * D) inline
Definition at line 547 of file ASTNodeTraverser.h.
VisitSubstNonTypeTemplateParmExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstNonTypeTemplateParmExpr (const SubstNonTypeTemplateParmExpr * E) inline
Definition at line 752 of file ASTNodeTraverser.h.
VisitSubstNonTypeTemplateParmPackExpr()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstNonTypeTemplateParmPackExpr (const SubstNonTypeTemplateParmPackExpr * E) inline
Definition at line 755 of file ASTNodeTraverser.h.
VisitSubstTemplateTypeParmPackType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstTemplateTypeParmPackType (const SubstTemplateTypeParmPackType * T) inline
Definition at line 396 of file ASTNodeTraverser.h.
VisitSubstTemplateTypeParmType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitSubstTemplateTypeParmType (const SubstTemplateTypeParmType * T) inline
Definition at line 392 of file ASTNodeTraverser.h.
VisitTemplateSpecializationType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateSpecializationType (const TemplateSpecializationType * T) inline
Definition at line 400 of file ASTNodeTraverser.h.
VisitTemplateTemplateParmDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTemplateParmDecl (const TemplateTemplateParmDecl * D) inline
Definition at line 612 of file ASTNodeTraverser.h.
VisitTemplateTypeParmDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTemplateTypeParmDecl (const TemplateTypeParmDecl * D) inline
Definition at line 594 of file ASTNodeTraverser.h.
VisitTypeAliasDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeAliasDecl (const TypeAliasDecl * D) inline
Definition at line 538 of file ASTNodeTraverser.h.
VisitTypeAliasTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeAliasTemplateDecl (const TypeAliasTemplateDecl * D) inline
Definition at line 542 of file ASTNodeTraverser.h.
VisitTypedefDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypedefDecl (const TypedefDecl * D) inline
Definition at line 417 of file ASTNodeTraverser.h.
VisitTypeOfExprType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeOfExprType (const TypeOfExprType * T) inline
Definition at line 376 of file ASTNodeTraverser.h.
VisitTypeTemplateArgument()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitTypeTemplateArgument (const TemplateArgument & TA) inline
Definition at line 799 of file ASTNodeTraverser.h.
VisitUnaryTransformType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitUnaryTransformType (const UnaryTransformType * T) inline
Definition at line 382 of file ASTNodeTraverser.h.
VisitUsingShadowDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitUsingShadowDecl (const UsingShadowDecl * D) inline
Definition at line 631 of file ASTNodeTraverser.h.
VisitVarDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarDecl (const VarDecl * D) inline
Definition at line 453 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitDecompositionDecl(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVarTemplateSpecializationDecl().
VisitVariableArrayType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVariableArrayType (const VariableArrayType * T) inline
Definition at line 357 of file ASTNodeTraverser.h.
VisitVarTemplateDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplateDecl (const VarTemplateDecl * D) inline
Definition at line 576 of file ASTNodeTraverser.h.
VisitVarTemplatePartialSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplatePartialSpecializationDecl (const VarTemplatePartialSpecializationDecl * D) inline
Definition at line 588 of file ASTNodeTraverser.h.
VisitVarTemplateSpecializationDecl()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarTemplateSpecializationDecl (const VarTemplateSpecializationDecl * D) inline
Definition at line 583 of file ASTNodeTraverser.h.
Referenced by clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::VisitVarTemplatePartialSpecializationDecl().
VisitVectorType()
template<typename Derived , typename NodeDelegateType > void clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVectorType (const VectorType * T) inline
Definition at line 369 of file ASTNodeTraverser.h.
The documentation for this class was generated from the following file:
include/clang/AST/ASTNodeTraverser.h