clang: clang::Sema::ConditionResult Class Reference
clang::Sema::ConditionResult Class Reference
#include "clang/Sema/Sema.h"
Public Member Functions
ConditionResult ()
bool isInvalid () const
std::pair< VarDecl *, Expr * > get () const
llvm::Optional< bool > getKnownValue () const
Friends
class Sema
Detailed Description
Definition at line 12527 of file Sema.h.
Constructor & Destructor Documentation
ConditionResult()
clang::Sema::ConditionResult::ConditionResult () inline
Definition at line 12547 of file Sema.h.
Member Function Documentation
get()
std::pair<VarDecl *, Expr *> clang::Sema::ConditionResult::get () const inline
Definition at line 12549 of file Sema.h.
References clang::Condition.
Referenced by clang::Sema::ActOnForStmt(), clang::Sema::ActOnIfStmt(), clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::ActOnWhileStmt(), and clang::Sema::BuildIfStmt().
getKnownValue()
llvm::Optional<bool> clang::Sema::ConditionResult::getKnownValue () const inline
Definition at line 12553 of file Sema.h.
References None.
isInvalid()
bool clang::Sema::ConditionResult::isInvalid () const inline
Definition at line 12548 of file Sema.h.
References Invalid.
Referenced by clang::Sema::ActOnForStmt(), clang::Sema::ActOnIfStmt(), clang::Sema::ActOnStartOfSwitchStmt(), clang::Sema::ActOnWhileStmt(), and clang::Sema::BuildIfStmt().
Friends And Related Function Documentation
Sema
friend class Sema friend
Definition at line 12534 of file Sema.h.
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h