clang: clang::ObjCForCollectionStmt Class Reference
clang::ObjCForCollectionStmt Class Reference
Represents Objective-C's collection statement.
#include "clang/AST/StmtObjC.h"
Public Member Functions
ObjCForCollectionStmt (Stmt *Elem, Expr *Collect, Stmt *Body, SourceLocation FCL, SourceLocation RPL)
ObjCForCollectionStmt (EmptyShell Empty)
Stmt * getElement ()
Expr * getCollection ()
Stmt * getBody ()
const Stmt * getElement () const
const Expr * getCollection () const
const Stmt * getBody () const
void setElement (Stmt *S)
void setCollection (Expr *E)
void setBody (Stmt *S)
SourceLocation getForLoc () const
void setForLoc (SourceLocation Loc)
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation Loc)
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Additional Inherited Members
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1, LH_None, LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpessions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator< T, const T *const, const Stmt *const >
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator< Expr >
using ConstExprIterator = ConstCastIterator< Expr >
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
Represents Objective-C's collection statement.
This is represented as 'for (element 'in' collection-expression)' stmt.
Definition at line 23 of file StmtObjC.h.
Constructor & Destructor Documentation
ObjCForCollectionStmt() [1/2]
ObjCForCollectionStmt::ObjCForCollectionStmt (Stmt * Elem, Expr * Collect, Stmt * Body, SourceLocation FCL, SourceLocation RPL)
Definition at line 20 of file StmtObjC.cpp.
ObjCForCollectionStmt() [2/2]
clang::ObjCForCollectionStmt::ObjCForCollectionStmt (EmptyShell Empty) inline explicit
Definition at line 31 of file StmtObjC.h.
Member Function Documentation
children() [1/2]
child_range clang::ObjCForCollectionStmt::children () inline
Definition at line 67 of file StmtObjC.h.
children() [2/2]
const_child_range clang::ObjCForCollectionStmt::children () const inline
Definition at line 71 of file StmtObjC.h.
classof()
static bool clang::ObjCForCollectionStmt::classof (const Stmt * T) inline static
Definition at line 62 of file StmtObjC.h.
References clang::Stmt::getStmtClass().
getBeginLoc()
SourceLocation clang::ObjCForCollectionStmt::getBeginLoc () const inline
Definition at line 57 of file StmtObjC.h.
getBody() [1/2]
Stmt* clang::ObjCForCollectionStmt::getBody () inline
Definition at line 38 of file StmtObjC.h.
getBody() [2/2]
const Stmt* clang::ObjCForCollectionStmt::getBody () const inline
Definition at line 44 of file StmtObjC.h.
getCollection() [1/2]
Expr* clang::ObjCForCollectionStmt::getCollection () inline
Definition at line 35 of file StmtObjC.h.
Referenced by assumeCollectionNonEmpty(), checkCollectionNonNil(), and checkElementNonNil().
getCollection() [2/2]
const Expr* clang::ObjCForCollectionStmt::getCollection () const inline
Definition at line 41 of file StmtObjC.h.
getElement() [1/2]
Stmt* clang::ObjCForCollectionStmt::getElement () inline
Definition at line 34 of file StmtObjC.h.
Referenced by checkElementNonNil().
getElement() [2/2]
const Stmt* clang::ObjCForCollectionStmt::getElement () const inline
Definition at line 40 of file StmtObjC.h.
getEndLoc()
SourceLocation clang::ObjCForCollectionStmt::getEndLoc () const inline
Definition at line 58 of file StmtObjC.h.
References clang::Stmt::getEndLoc().
getForLoc()
SourceLocation clang::ObjCForCollectionStmt::getForLoc () const inline
Definition at line 52 of file StmtObjC.h.
getRParenLoc()
SourceLocation clang::ObjCForCollectionStmt::getRParenLoc () const inline
Definition at line 54 of file StmtObjC.h.
setBody()
void clang::ObjCForCollectionStmt::setBody (Stmt * S) inline
Definition at line 50 of file StmtObjC.h.
setCollection()
void clang::ObjCForCollectionStmt::setCollection (Expr * E) inline
Definition at line 47 of file StmtObjC.h.
setElement()
void clang::ObjCForCollectionStmt::setElement (Stmt * S) inline
Definition at line 46 of file StmtObjC.h.
setForLoc()
void clang::ObjCForCollectionStmt::setForLoc (SourceLocation Loc) inline
Definition at line 53 of file StmtObjC.h.
setRParenLoc()
void clang::ObjCForCollectionStmt::setRParenLoc (SourceLocation Loc) inline
Definition at line 55 of file StmtObjC.h.
The documentation for this class was generated from the following files:
include/clang/AST/StmtObjC.h
lib/AST/StmtObjC.cpp