clang: clang::ObjCTypeParamTypeLoc Class Reference
clang::ObjCTypeParamTypeLoc Class Reference
ProtocolLAngleLoc, ProtocolRAngleLoc, and the source locations for protocol qualifiers are stored after Info.
#include "clang/AST/TypeLoc.h"
Public Member Functions
ObjCTypeParamDecl * getDecl () const
SourceLocation getNameLoc () const
void setNameLoc (SourceLocation Loc)
SourceLocation getProtocolLAngleLoc () const
void setProtocolLAngleLoc (SourceLocation Loc)
SourceLocation getProtocolRAngleLoc () const
void setProtocolRAngleLoc (SourceLocation Loc)
unsigned getNumProtocols () const
SourceLocation getProtocolLoc (unsigned i) const
void setProtocolLoc (unsigned i, SourceLocation Loc)
ObjCProtocolDecl * getProtocol (unsigned i) const
ArrayRef< SourceLocation > getProtocolLocs () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
SourceRange getLocalSourceRange () const
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (ObjCTypeParamTypeLoc other)
TypeLoc getNextTypeLoc () const
const ObjCTypeParamType * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
ObjCTypeParamTypeLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
ProtocolLAngleLoc, ProtocolRAngleLoc, and the source locations for protocol qualifiers are stored after Info.
Definition at line 757 of file TypeLoc.h.
Member Function Documentation
getDecl()
ObjCTypeParamDecl* clang::ObjCTypeParamTypeLoc::getDecl () const inline
Definition at line 767 of file TypeLoc.h.
References clang::ObjCTypeParamType::getDecl(), and clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getTypePtr().
getExtraLocalDataAlignment()
unsigned clang::ObjCTypeParamTypeLoc::getExtraLocalDataAlignment () const inline
Definition at line 829 of file TypeLoc.h.
getExtraLocalDataSize()
unsigned clang::ObjCTypeParamTypeLoc::getExtraLocalDataSize () const inline
Definition at line 822 of file TypeLoc.h.
References getNumProtocols().
getLocalSourceRange()
SourceRange clang::ObjCTypeParamTypeLoc::getLocalSourceRange () const inline
Definition at line 833 of file TypeLoc.h.
References getNameLoc(), getProtocolRAngleLoc(), and clang::SourceLocation::isInvalid().
getNameLoc()
SourceLocation clang::ObjCTypeParamTypeLoc::getNameLoc () const inline
Definition at line 769 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getLocalData(), and clang::ObjCTypeParamTypeLocInfo::NameLoc.
Referenced by getLocalSourceRange().
getNumProtocols()
unsigned clang::ObjCTypeParamTypeLoc::getNumProtocols () const inline
Definition at line 797 of file TypeLoc.h.
References clang::ObjCProtocolQualifiers< T >::getNumProtocols(), and clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getTypePtr().
Referenced by getExtraLocalDataSize(), getProtocol(), getProtocolLAngleLoc(), getProtocolLoc(), getProtocolLocs(), getProtocolRAngleLoc(), initializeLocal(), and setProtocolLoc().
getProtocol()
ObjCProtocolDecl* clang::ObjCTypeParamTypeLoc::getProtocol (unsigned i) const inline
Definition at line 811 of file TypeLoc.h.
References getNumProtocols(), clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getTypePtr(), and clang::ObjCProtocolQualifiers< T >::qual_begin().
getProtocolLAngleLoc()
SourceLocation clang::ObjCTypeParamTypeLoc::getProtocolLAngleLoc () const inline
Definition at line 777 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getExtraLocalData(), and getNumProtocols().
getProtocolLoc()
SourceLocation clang::ObjCTypeParamTypeLoc::getProtocolLoc (unsigned i) const inline
Definition at line 801 of file TypeLoc.h.
References getNumProtocols().
getProtocolLocs()
ArrayRef<SourceLocation> clang::ObjCTypeParamTypeLoc::getProtocolLocs () const inline
Definition at line 816 of file TypeLoc.h.
References getNumProtocols().
getProtocolRAngleLoc()
SourceLocation clang::ObjCTypeParamTypeLoc::getProtocolRAngleLoc () const inline
Definition at line 787 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getExtraLocalData(), and getNumProtocols().
Referenced by getLocalSourceRange().
initializeLocal()
void ObjCTypeParamTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc)
Definition at line 475 of file TypeLoc.cpp.
References getNumProtocols(), setNameLoc(), setProtocolLAngleLoc(), setProtocolLoc(), and setProtocolRAngleLoc().
setNameLoc()
void clang::ObjCTypeParamTypeLoc::setNameLoc (SourceLocation Loc) inline
Definition at line 773 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getLocalData(), and clang::ObjCTypeParamTypeLocInfo::NameLoc.
Referenced by initializeLocal().
setProtocolLAngleLoc()
void clang::ObjCTypeParamTypeLoc::setProtocolLAngleLoc (SourceLocation Loc) inline
Definition at line 783 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getExtraLocalData().
Referenced by initializeLocal().
setProtocolLoc()
void clang::ObjCTypeParamTypeLoc::setProtocolLoc (unsigned i, SourceLocation Loc) inline
Definition at line 806 of file TypeLoc.h.
References getNumProtocols().
Referenced by initializeLocal().
setProtocolRAngleLoc()
void clang::ObjCTypeParamTypeLoc::setProtocolRAngleLoc (SourceLocation Loc) inline
Definition at line 793 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, ObjCTypeParamTypeLoc, ObjCTypeParamType, ObjCTypeParamTypeLocInfo >::getExtraLocalData().
Referenced by initializeLocal().
The documentation for this class was generated from the following files:
include/clang/AST/TypeLoc.h
lib/AST/TypeLoc.cpp