clang: clang::ActionResult< PtrTy, true > Class Template Reference
clang::ActionResult< PtrTy, true > Class Template Reference
#include "clang/Sema/Ownership.h"
Public Member Functions
ActionResult (bool Invalid=false)
ActionResult (PtrTy V)
ActionResult (const DiagnosticBuilder &)
ActionResult (const void *)=delete
ActionResult (volatile void *)=delete
bool isInvalid () const
bool isUnset () const
bool isUsable () const
PtrTy get () const
template<typename T >
T * getAs ()
ActionResult & operator= (PtrTy RHS)
void * getAsOpaquePointer () const
Static Public Member Functions
static ActionResult getFromOpaquePointer (void *P)
Detailed Description
template<typename PtrTy>
class clang::ActionResult< PtrTy, true >
Definition at line 181 of file Ownership.h.
Constructor & Destructor Documentation
ActionResult() [1/5]
template<typename PtrTy > clang::ActionResult< PtrTy, true >::ActionResult (bool Invalid = false) inline
Definition at line 190 of file Ownership.h.
ActionResult() [2/5]
template<typename PtrTy > clang::ActionResult< PtrTy, true >::ActionResult (PtrTy V) inline
Definition at line 192 of file Ownership.h.
References V.
ActionResult() [3/5]
template<typename PtrTy > clang::ActionResult< PtrTy, true >::ActionResult (const DiagnosticBuilder &) inline
Definition at line 193 of file Ownership.h.
ActionResult() [4/5]
template<typename PtrTy > clang::ActionResult< PtrTy, true >::ActionResult (const void *) delete
ActionResult() [5/5]
template<typename PtrTy > clang::ActionResult< PtrTy, true >::ActionResult (volatile void *) delete
Member Function Documentation
get()
template<typename PtrTy > PtrTy clang::ActionResult< PtrTy, true >::get () const inline
Definition at line 203 of file Ownership.h.
getAs()
template<typename PtrTy > template<typename T > T* clang::ActionResult< PtrTy, true >::getAs () inline
Definition at line 207 of file Ownership.h.
References clang::ActionResult< PtrTy, Compress >::get(), and clang::T.
getAsOpaquePointer()
template<typename PtrTy > void* clang::ActionResult< PtrTy, true >::getAsOpaquePointer () const inline
Definition at line 225 of file Ownership.h.
getFromOpaquePointer()
template<typename PtrTy > static ActionResult clang::ActionResult< PtrTy, true >::getFromOpaquePointer (void * P) inline static
Definition at line 218 of file Ownership.h.
References P.
isInvalid()
template<typename PtrTy > bool clang::ActionResult< PtrTy, true >::isInvalid () const inline
Definition at line 199 of file Ownership.h.
isUnset()
template<typename PtrTy > bool clang::ActionResult< PtrTy, true >::isUnset () const inline
Definition at line 200 of file Ownership.h.
isUsable()
template<typename PtrTy > bool clang::ActionResult< PtrTy, true >::isUsable () const inline
Definition at line 201 of file Ownership.h.
References clang::ActionResult< PtrTy, Compress >::isInvalid(), and clang::ActionResult< PtrTy, Compress >::isUnset().
operator=()
template<typename PtrTy > ActionResult& clang::ActionResult< PtrTy, true >::operator= (PtrTy RHS) inline
Definition at line 209 of file Ownership.h.
The documentation for this class was generated from the following file:
include/clang/Sema/Ownership.h