clang: clang::DotMemberAccessHandler Class Reference
clang::DotMemberAccessHandler Class Reference
Public Member Functions
DotMemberAccessHandler (Sema &S, CodeCompletionContext CCC, std::vector< std::string > &Results)
void handleDeclaration (const CodeCompletionResult &Result) override
Converts a Declaration completion result to a completion string, and then stores it in Results.
void handleKeyword (const CodeCompletionResult &Result) override
Converts a Keyword completion result to a completion string, and then stores it in Results.
Public Member Functions inherited from clang::CompletionContextHandler
CompletionContextHandler (Sema &S, CodeCompletionContext CCC, std::vector< std::string > &Results)
virtual ~CompletionContextHandler ()=default
virtual void handlePattern (const CodeCompletionResult &Result)
Converts a Pattern completion result to a completion string, and then stores it in Results.
virtual void handleMacro (const CodeCompletionResult &Result)
Converts a Macro completion result to a completion string, and then stores it in Results.
Additional Inherited Members
Protected Attributes inherited from clang::CompletionContextHandler
CodeCompletionContext CCC
std::vector< std::string > & Results
Detailed Description
Definition at line 139 of file CodeCompletion.cpp.
Constructor & Destructor Documentation
DotMemberAccessHandler()
clang::DotMemberAccessHandler::DotMemberAccessHandler (Sema & S, CodeCompletionContext CCC, std::vector< std::string > & Results) inline
Definition at line 141 of file CodeCompletion.cpp.
Member Function Documentation
handleDeclaration()
void clang::DotMemberAccessHandler::handleDeclaration (const CodeCompletionResult & Result) inline override virtual
Converts a Declaration completion result to a completion string, and then stores it in Results.
Reimplemented from clang::CompletionContextHandler.
Definition at line 144 of file CodeCompletion.cpp.
References clang::CompletionContextHandler::CCC, clang::Type::getAsCXXRecordDecl(), clang::CodeCompletionContext::getBaseType(), clang::CXXRecordDecl::getCanonicalDecl(), ID, and clang::CompletionContextHandler::Results.
handleKeyword()
void clang::DotMemberAccessHandler::handleKeyword (const CodeCompletionResult & Result) inline override virtual
Converts a Keyword completion result to a completion string, and then stores it in Results.
Reimplemented from clang::CompletionContextHandler.
Definition at line 159 of file CodeCompletion.cpp.
The documentation for this class was generated from the following file:
lib/Interpreter/CodeCompletion.cpp