clang: clang::Sema::ContextRAII Class Reference
clang::Sema::ContextRAII Class Reference
A RAII object to temporarily push a declaration context.
#include "clang/Sema/Sema.h"
Public Member Functions
ContextRAII (Sema &S, DeclContext *ContextToPush, bool NewThisContext=true)
void pop ()
~ContextRAII ()
Detailed Description
A RAII object to temporarily push a declaration context.
Definition at line 1156 of file Sema.h.
Constructor & Destructor Documentation
ContextRAII()
clang::Sema::ContextRAII::ContextRAII (Sema & S, DeclContext * ContextToPush, bool NewThisContext = true) inline
Definition at line 1166 of file Sema.h.
~ContextRAII()
clang::Sema::ContextRAII::~ContextRAII () inline
Definition at line 1192 of file Sema.h.
References pop().
Member Function Documentation
pop()
void clang::Sema::ContextRAII::pop () inline
Definition at line 1182 of file Sema.h.
Referenced by clang::Sema::InstantiateEnum(), clang::Sema::InstantiateVariableDefinition(), and ~ContextRAII().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h