clang: clang::SemaX86 Class Reference
clang::SemaX86 Class Reference
#include "clang/Sema/SemaX86.h"
Public Member Functions
SemaX86 (Sema &S)
bool CheckBuiltinRoundingOrSAE (unsigned BuiltinID, CallExpr *TheCall)
bool CheckBuiltinGatherScatterScale (unsigned BuiltinID, CallExpr *TheCall)
bool CheckBuiltinTileArguments (unsigned BuiltinID, CallExpr *TheCall)
bool CheckBuiltinTileArgumentsRange (CallExpr *TheCall, ArrayRef< int > ArgNums)
bool CheckBuiltinTileDuplicate (CallExpr *TheCall, ArrayRef< int > ArgNums)
bool CheckBuiltinTileRangeAndDuplicate (CallExpr *TheCall, ArrayRef< int > ArgNums)
bool CheckBuiltinFunctionCall (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
void handleAnyInterruptAttr (Decl *D, const ParsedAttr &AL)
void handleForceAlignArgPointerAttr (Decl *D, const ParsedAttr &AL)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 25 of file SemaX86.h.
Constructor & Destructor Documentation
SemaX86()
clang::SemaX86::SemaX86 (Sema & S)
Definition at line 25 of file SemaX86.cpp.
Member Function Documentation
CheckBuiltinFunctionCall()
bool clang::SemaX86::CheckBuiltinFunctionCall (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 479 of file SemaX86.cpp.
References clang::Sema::BuiltinConstantArgRange(), CheckBuiltinGatherScatterScale(), CheckBuiltinRoundingOrSAE(), CheckBuiltinTileArguments(), clang::SemaBase::Diag(), clang::Stmt::getBeginLoc(), clang::CallExpr::getCallee(), clang::TargetInfo::getTriple(), clang::isX86_32Builtin(), and clang::SemaBase::SemaRef.
CheckBuiltinGatherScatterScale()
bool clang::SemaX86::CheckBuiltinGatherScatterScale (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 313 of file SemaX86.cpp.
References clang::Sema::BuiltinConstantArg(), clang::SemaBase::Diag(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), and clang::SemaBase::SemaRef.
Referenced by CheckBuiltinFunctionCall().
CheckBuiltinRoundingOrSAE()
bool clang::SemaX86::CheckBuiltinRoundingOrSAE (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 28 of file SemaX86.cpp.
References clang::Sema::BuiltinConstantArg(), clang::SemaBase::Diag(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), and clang::SemaBase::SemaRef.
Referenced by CheckBuiltinFunctionCall().
CheckBuiltinTileArguments()
bool clang::SemaX86::CheckBuiltinTileArguments (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 448 of file SemaX86.cpp.
References CheckBuiltinTileArgumentsRange(), and CheckBuiltinTileRangeAndDuplicate().
Referenced by CheckBuiltinFunctionCall().
CheckBuiltinTileArgumentsRange()
bool clang::SemaX86::CheckBuiltinTileArgumentsRange (CallExpr * TheCall, ArrayRef< int > ArgNums)
Definition at line 407 of file SemaX86.cpp.
References clang::Sema::BuiltinConstantArgRange(), clang::SemaBase::SemaRef, clang::TileRegHigh, and clang::TileRegLow.
Referenced by CheckBuiltinTileArguments(), and CheckBuiltinTileRangeAndDuplicate().
CheckBuiltinTileDuplicate()
bool clang::SemaX86::CheckBuiltinTileDuplicate (CallExpr * TheCall, ArrayRef< int > ArgNums)
Definition at line 417 of file SemaX86.cpp.
References clang::Sema::BuiltinConstantArg(), clang::SemaBase::Diag(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::SemaBase::SemaRef, clang::TileRegHigh, and clang::TileRegLow.
Referenced by CheckBuiltinTileRangeAndDuplicate().
CheckBuiltinTileRangeAndDuplicate()
bool clang::SemaX86::CheckBuiltinTileRangeAndDuplicate (CallExpr * TheCall, ArrayRef< int > ArgNums)
Definition at line 442 of file SemaX86.cpp.
References CheckBuiltinTileArgumentsRange(), and CheckBuiltinTileDuplicate().
Referenced by CheckBuiltinTileArguments().
handleAnyInterruptAttr()
void clang::SemaX86::handleAnyInterruptAttr (Decl * D, const ParsedAttr & AL)
Definition at line 880 of file SemaX86.cpp.
handleForceAlignArgPointerAttr()
void clang::SemaX86::handleForceAlignArgPointerAttr (Decl * D, const ParsedAttr & AL)
Definition at line 949 of file SemaX86.cpp.
References D, clang::SemaBase::Diag(), clang::ExpectedFunction, clang::SemaBase::getASTContext(), clang::AttributeCommonInfo::getLoc(), and clang::AttributeCommonInfo::isRegularKeywordAttribute().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaX86.h
lib/Sema/SemaX86.cpp