clang: clang::OMPChildren Class Reference
clang::OMPChildren Class Reference final
Contains data for OpenMP directives: clauses, children expressions/statements (helpers for codegen) and associated statement, if any.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
unsigned getNumClauses () const
unsigned getNumChildren () const
bool hasAssociatedStmt () const
void setAssociatedStmt (Stmt *S)
Set associated statement.
void setChildren (ArrayRef< Stmt * > Children)
void setClauses (ArrayRef< OMPClause * > Clauses)
Sets the list of variables for this clause.
const Stmt * getAssociatedStmt () const
Returns statement associated with the directive.
Stmt * getAssociatedStmt ()
MutableArrayRef< OMPClause * > getClauses ()
Get the clauses storage.
ArrayRef< OMPClause * > getClauses () const
const CapturedStmt * getCapturedStmt (OpenMPDirectiveKind RegionKind, ArrayRef< OpenMPDirectiveKind > CaptureRegions) const
Returns the captured statement associated with the component region within the (combined) directive.
CapturedStmt * getInnermostCapturedStmt (ArrayRef< OpenMPDirectiveKind > CaptureRegions)
Get innermost captured statement for the construct.
const CapturedStmt * getInnermostCapturedStmt (ArrayRef< OpenMPDirectiveKind > CaptureRegions) const
MutableArrayRef< Stmt * > getChildren ()
ArrayRef< Stmt * > getChildren () const
Stmt * getRawStmt ()
const Stmt * getRawStmt () const
Stmt::child_range getAssociatedStmtAsRange ()
Friends
class OMPClauseReader
class OMPExecutableDirective
template<typename T >
class OMPDeclarativeDirective
Detailed Description
Contains data for OpenMP directives: clauses, children expressions/statements (helpers for codegen) and associated statement, if any.
Definition at line 8776 of file OpenMPClause.h.
Member Function Documentation
getAssociatedStmt() [1/2]
Stmt* clang::OMPChildren::getAssociatedStmt () inline
Definition at line 8834 of file OpenMPClause.h.
getAssociatedStmt() [2/2]
const Stmt* clang::OMPChildren::getAssociatedStmt () const inline
Returns statement associated with the directive.
Definition at line 8831 of file OpenMPClause.h.
Referenced by clang::OMPExecutableDirective::getAssociatedStmt(), getCapturedStmt(), getInnermostCapturedStmt(), getRawStmt(), and clang::ASTRecordWriter::writeOMPChildren().
getAssociatedStmtAsRange()
Stmt::child_range clang::OMPChildren::getAssociatedStmtAsRange () inline
Definition at line 8909 of file OpenMPClause.h.
Referenced by clang::OMPExecutableDirective::children().
getCapturedStmt()
const CapturedStmt* clang::OMPChildren::getCapturedStmt (OpenMPDirectiveKind RegionKind, ArrayRef< OpenMPDirectiveKind > CaptureRegions) const inline
Returns the captured statement associated with the component region within the (combined) directive.
Parameters
RegionKind Component region kind.
Definition at line 8854 of file OpenMPClause.h.
References getAssociatedStmt().
Referenced by clang::OMPExecutableDirective::getCapturedStmt().
getChildren() [1/2]
MutableArrayRef< Stmt * > OMPChildren::getChildren ()
Definition at line 33 of file StmtOpenMP.cpp.
Referenced by clang::OMPLoopDirective::getCalcLastIteration(), getChildren(), clang::OMPLoopDirective::getCombinedCond(), clang::OMPLoopDirective::getCombinedDistCond(), clang::OMPLoopDirective::getCombinedEnsureUpperBound(), clang::OMPLoopDirective::getCombinedInit(), clang::OMPLoopDirective::getCombinedLowerBoundVariable(), clang::OMPLoopDirective::getCombinedNextLowerBound(), clang::OMPLoopDirective::getCombinedNextUpperBound(), clang::OMPLoopDirective::getCombinedParForInDistCond(), clang::OMPLoopDirective::getCombinedUpperBoundVariable(), clang::OMPLoopDirective::getCond(), clang::OMPAtomicDirective::getCondExpr(), clang::OMPAtomicDirective::getD(), clang::OMPLoopDirective::getDistInc(), clang::OMPLoopDirective::getEnsureUpperBound(), clang::OMPAtomicDirective::getExpr(), clang::OMPLoopDirective::getInc(), clang::OMPLoopDirective::getInit(), clang::OMPLoopDirective::getIsLastIterVariable(), clang::OMPLoopDirective::getIterationVariable(), clang::OMPLoopDirective::getLastIteration(), clang::OMPLoopDirective::getLowerBoundVariable(), clang::OMPDeclareMapperDecl::getMapperVarRef(), clang::OMPLoopDirective::getNextLowerBound(), clang::OMPLoopDirective::getNextUpperBound(), clang::OMPLoopDirective::getNumIterations(), clang::OMPLoopDirective::getPreCond(), clang::OMPLoopDirective::getPreInits(), clang::OMPTileDirective::getPreInits(), clang::OMPUnrollDirective::getPreInits(), clang::OMPLoopDirective::getPrevEnsureUpperBound(), clang::OMPLoopDirective::getPrevLowerBoundVariable(), clang::OMPLoopDirective::getPrevUpperBoundVariable(), clang::OMPTaskgroupDirective::getReductionRef(), clang::OMPLoopDirective::getStrideVariable(), clang::OMPParallelDirective::getTaskReductionRefExpr(), clang::OMPForDirective::getTaskReductionRefExpr(), clang::OMPSectionsDirective::getTaskReductionRefExpr(), clang::OMPParallelForDirective::getTaskReductionRefExpr(), clang::OMPParallelMasterDirective::getTaskReductionRefExpr(), clang::OMPParallelSectionsDirective::getTaskReductionRefExpr(), clang::OMPTargetParallelDirective::getTaskReductionRefExpr(), clang::OMPTargetParallelForDirective::getTaskReductionRefExpr(), clang::OMPDistributeParallelForDirective::getTaskReductionRefExpr(), clang::OMPTeamsDistributeParallelForDirective::getTaskReductionRefExpr(), clang::OMPTargetTeamsDistributeParallelForDirective::getTaskReductionRefExpr(), clang::OMPTileDirective::getTransformedStmt(), clang::OMPUnrollDirective::getTransformedStmt(), clang::OMPAtomicDirective::getUpdateExpr(), clang::OMPLoopDirective::getUpperBoundVariable(), clang::OMPAtomicDirective::getV(), clang::OMPAtomicDirective::getX(), clang::ASTRecordReader::readOMPChildren(), clang::OMPLoopDirective::setCalcLastIteration(), clang::OMPLoopDirective::setCombinedCond(), clang::OMPLoopDirective::setCombinedDistCond(), clang::OMPLoopDirective::setCombinedEnsureUpperBound(), clang::OMPLoopDirective::setCombinedInit(), clang::OMPLoopDirective::setCombinedLowerBoundVariable(), clang::OMPLoopDirective::setCombinedNextLowerBound(), clang::OMPLoopDirective::setCombinedNextUpperBound(), clang::OMPLoopDirective::setCombinedParForInDistCond(), clang::OMPLoopDirective::setCombinedUpperBoundVariable(), clang::OMPLoopDirective::setCond(), clang::OMPLoopDirective::setDistInc(), clang::OMPLoopDirective::setEnsureUpperBound(), clang::OMPLoopDirective::setInc(), clang::OMPLoopDirective::setInit(), clang::OMPLoopDirective::setIsLastIterVariable(), clang::OMPLoopDirective::setIterationVariable(), clang::OMPLoopDirective::setLastIteration(), clang::OMPLoopDirective::setLowerBoundVariable(), clang::OMPDeclareMapperDecl::setMapperVarRef(), clang::OMPLoopDirective::setNextLowerBound(), clang::OMPLoopDirective::setNextUpperBound(), clang::OMPLoopDirective::setNumIterations(), clang::OMPLoopDirective::setPreCond(), clang::OMPLoopDirective::setPreInits(), clang::OMPLoopDirective::setPrevEnsureUpperBound(), clang::OMPLoopDirective::setPrevLowerBoundVariable(), clang::OMPLoopDirective::setPrevUpperBoundVariable(), clang::OMPLoopDirective::setStrideVariable(), clang::OMPLoopDirective::setUpperBoundVariable(), clang::OMPThreadPrivateDecl::varlist_empty(), clang::OMPAllocateDecl::varlist_empty(), and clang::ASTRecordWriter::writeOMPChildren().
getChildren() [2/2]
ArrayRef<Stmt *> clang::OMPChildren::getChildren () const inline
Definition at line 8888 of file OpenMPClause.h.
References getChildren().
getClauses() [1/2]
MutableArrayRef<OMPClause *> clang::OMPChildren::getClauses () inline
Get the clauses storage.
Definition at line 8841 of file OpenMPClause.h.
Referenced by clang::OMPDeclareMapperDecl::clauselist_begin(), clang::OMPRequiresDecl::clauselist_begin(), clang::OMPAllocateDecl::clauselist_begin(), clang::OMPDeclareMapperDecl::clauselist_empty(), clang::OMPRequiresDecl::clauselist_empty(), clang::OMPAllocateDecl::clauselist_empty(), clang::OMPDeclareMapperDecl::clauselist_end(), clang::OMPRequiresDecl::clauselist_end(), clang::OMPAllocateDecl::clauselist_end(), clang::OMPDeclarativeDirective< ValueDecl >::clauses(), clang::OMPExecutableDirective::clauses(), getClauses(), and clang::ASTRecordWriter::writeOMPChildren().
getClauses() [2/2]
ArrayRef<OMPClause *> clang::OMPChildren::getClauses () const inline
Definition at line 8845 of file OpenMPClause.h.
References getClauses().
getInnermostCapturedStmt() [1/2]
CapturedStmt* clang::OMPChildren::getInnermostCapturedStmt (ArrayRef< OpenMPDirectiveKind > CaptureRegions) inline
Get innermost captured statement for the construct.
Definition at line 8871 of file OpenMPClause.h.
References getAssociatedStmt(), and hasAssociatedStmt().
Referenced by clang::OMPExecutableDirective::getInnermostCapturedStmt(), and getInnermostCapturedStmt().
getInnermostCapturedStmt() [2/2]
const CapturedStmt* clang::OMPChildren::getInnermostCapturedStmt (ArrayRef< OpenMPDirectiveKind > CaptureRegions) const inline
Definition at line 8882 of file OpenMPClause.h.
References getInnermostCapturedStmt().
getNumChildren()
unsigned clang::OMPChildren::getNumChildren () const inline
Definition at line 8814 of file OpenMPClause.h.
Referenced by clang::ASTRecordReader::readOMPChildren(), clang::OMPThreadPrivateDecl::varlist_size(), clang::OMPAllocateDecl::varlist_size(), and clang::ASTRecordWriter::writeOMPChildren().
getNumClauses()
unsigned clang::OMPChildren::getNumClauses () const inline
Definition at line 8813 of file OpenMPClause.h.
Referenced by clang::OMPDeclareMapperDecl::clauselist_size(), clang::OMPRequiresDecl::clauselist_size(), clang::OMPAllocateDecl::clauselist_size(), clang::OMPDeclarativeDirective< ValueDecl >::getNumClauses(), clang::OMPExecutableDirective::getNumClauses(), clang::ASTRecordReader::readOMPChildren(), and clang::ASTRecordWriter::writeOMPChildren().
getRawStmt() [1/2]
Stmt* clang::OMPChildren::getRawStmt () inline
Definition at line 8892 of file OpenMPClause.h.
References getAssociatedStmt().
Referenced by clang::OMPExecutableDirective::getRawStmt(), and getRawStmt().
getRawStmt() [2/2]
const Stmt* clang::OMPChildren::getRawStmt () const inline
Definition at line 8905 of file OpenMPClause.h.
References getRawStmt().
hasAssociatedStmt()
bool clang::OMPChildren::hasAssociatedStmt () const inline
Definition at line 8815 of file OpenMPClause.h.
Referenced by getInnermostCapturedStmt(), clang::OMPExecutableDirective::hasAssociatedStmt(), clang::ASTRecordReader::readOMPChildren(), and clang::ASTRecordWriter::writeOMPChildren().
setAssociatedStmt()
void clang::OMPChildren::setAssociatedStmt (Stmt * S) inline
Set associated statement.
Definition at line 8818 of file OpenMPClause.h.
Referenced by clang::ASTRecordReader::readOMPChildren().
setChildren()
void clang::OMPChildren::setChildren (ArrayRef< Stmt * > Children)
setClauses()
void OMPChildren::setClauses (ArrayRef< OMPClause * > Clauses)
Sets the list of variables for this clause.
Parameters
Clauses The list of clauses for the directive.
Definition at line 27 of file StmtOpenMP.cpp.
Referenced by clang::ASTRecordReader::readOMPChildren().
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 8779 of file OpenMPClause.h.
OMPDeclarativeDirective
template<typename T > friend class OMPDeclarativeDirective friend
Definition at line 8781 of file OpenMPClause.h.
OMPExecutableDirective
friend class OMPExecutableDirective friend
Definition at line 8780 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/StmtOpenMP.cpp