clang: clang::DependentAddressSpaceTypeLoc Class Reference
clang::DependentAddressSpaceTypeLoc Class Reference
#include "clang/AST/TypeLoc.h"
Public Member Functions
SourceLocation getAttrNameLoc () const
The location of the attribute name, i.e.
void setAttrNameLoc (SourceLocation loc)
Expr * getAttrExprOperand () const
The attribute's expression operand, if it has one.
void setAttrExprOperand (Expr *e)
SourceRange getAttrOperandParensRange () const
The location of the parentheses around the operand, if there is an operand.
void setAttrOperandParensRange (SourceRange range)
SourceRange getLocalSourceRange () const
QualType getInnerType () const
Returns the type before the address space attribute application area.
TypeLoc getPointeeTypeLoc () const
void initializeLocal (ASTContext &Context, SourceLocation loc)
Public Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (DependentAddressSpaceTypeLoc other)
TypeLoc getNextTypeLoc () const
const DependentAddressSpaceType * getTypePtr () const
Public Member Functions inherited from clang::UnqualTypeLoc
UnqualTypeLoc ()=default
UnqualTypeLoc (const Type *Ty, void *Data)
const Type * getTypePtr () const
TypeLocClass getTypeLocClass () const
Public Member Functions inherited from clang::TypeLoc
TypeLoc ()=default
TypeLoc (QualType ty, void *opaqueData)
TypeLoc (const Type *ty, void *opaqueData)
template<typename T >
T castAs () const
Convert to the specified TypeLoc type, asserting that this TypeLoc is of the desired type.
template<typename T >
T getAs () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
template<typename T >
T getAsAdjusted () const
Convert to the specified TypeLoc type, returning a null TypeLoc if this TypeLoc is not of the desired type.
TypeLocClass getTypeLocClass () const
bool isNull () const
operator bool () const
QualType getType () const
Get the type for which this source info wrapper provides information.
const Type * getTypePtr () const
void * getOpaqueData () const
Get the pointer where source information is stored.
SourceLocation getBeginLoc () const
Get the begin source location.
SourceLocation getEndLoc () const
Get the end source location.
SourceRange getSourceRange () const LLVM_READONLY
Get the full source range.
SourceRange getLocalSourceRange () const
Get the local source range.
unsigned getFullDataSize () const
Returns the size of the type source info data block.
TypeLoc getNextTypeLoc () const
Get the next TypeLoc pointed by this TypeLoc, e.g for "int*" the TypeLoc is a PointerLoc and next TypeLoc is for "int".
UnqualTypeLoc getUnqualifiedLoc () const
Skips past any qualifiers, if this is qualified.
TypeLoc IgnoreParens () const
TypeLoc findExplicitQualifierLoc () const
Find a type with the location of an explicit type qualifier.
AutoTypeLoc getContainedAutoTypeLoc () const
Get the typeloc of an AutoType whose type will be deduced for a variable with an initializer of this type.
SourceLocation getTemplateKeywordLoc () const
Get the SourceLocation of the template keyword (if any).
void initialize (ASTContext &Context, SourceLocation Loc) const
Initializes this to state that every location in this type is the given location.
void initializeFullCopy (TypeLoc Other)
Initializes this by copying its information from another TypeLoc of the same type.
void initializeFullCopy (TypeLoc Other, unsigned Size)
Initializes this by copying its information from another TypeLoc of the same type.
void copy (TypeLoc other)
Copies the other type loc into this one.
SourceLocation findNullabilityLoc () const
Find the location of the nullability specifier (__nonnull, __nullable, or __null_unspecifier), if there is one.
void dump () const
void dump (llvm::raw_ostream &, const ASTContext &) const
Additional Inherited Members
Public Types inherited from clang::TypeLoc
enum TypeLocClass { Qualified }
The kinds of TypeLocs.
Static Public Member Functions inherited from clang::TypeLoc
static unsigned getFullDataSizeForType (QualType Ty)
Returns the size of type source info data block for the given type.
static unsigned getLocalAlignmentForType (QualType Ty)
Returns the alignment of type source info data block for the given type.
Protected Member Functions inherited from clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
DependentAddressSpaceLocInfo * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Protected Attributes inherited from clang::TypeLoc
const void * Ty = nullptr
void * Data = nullptr
Detailed Description
Definition at line 1761 of file TypeLoc.h.
Member Function Documentation
getAttrExprOperand()
Expr* clang::DependentAddressSpaceTypeLoc::getAttrExprOperand () const inline
The attribute's expression operand, if it has one.
int * attribute((address_space(11))) ^~
Definition at line 1780 of file TypeLoc.h.
References clang::DependentAddressSpaceLocInfo::ExprOperand, and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >::getLocalData().
getAttrNameLoc()
SourceLocation clang::DependentAddressSpaceTypeLoc::getAttrNameLoc () const inline
The location of the attribute name, i.e.
int * attribute((address_space(11))) ^~~~~~~~~~~~~
Definition at line 1770 of file TypeLoc.h.
References clang::DependentAddressSpaceLocInfo::AttrLoc, and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >::getLocalData().
Referenced by getLocalSourceRange().
getAttrOperandParensRange()
SourceRange clang::DependentAddressSpaceTypeLoc::getAttrOperandParensRange () const inline
The location of the parentheses around the operand, if there is an operand.
int * attribute((address_space(11))) ^ ^
Definition at line 1791 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >::getLocalData(), and clang::DependentAddressSpaceLocInfo::OperandParens.
Referenced by getLocalSourceRange().
getInnerType()
QualType clang::DependentAddressSpaceTypeLoc::getInnerType () const inline
Returns the type before the address space attribute application area.
int * attribute((address_space(11))) * ^ ^
Definition at line 1808 of file TypeLoc.h.
References clang::DependentAddressSpaceType::getPointeeType(), and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >::getTypePtr().
getLocalSourceRange()
SourceRange clang::DependentAddressSpaceTypeLoc::getLocalSourceRange () const inline
Definition at line 1798 of file TypeLoc.h.
References getAttrNameLoc(), getAttrOperandParensRange(), and clang::transformer::range().
getPointeeTypeLoc()
TypeLoc clang::DependentAddressSpaceTypeLoc::getPointeeTypeLoc () const inline
Definition at line 1812 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >::getInnerTypeLoc().
initializeLocal()
void clang::DependentAddressSpaceTypeLoc::initializeLocal (ASTContext & Context, SourceLocation loc) inline
Definition at line 1816 of file TypeLoc.h.
setAttrExprOperand()
void clang::DependentAddressSpaceTypeLoc::setAttrExprOperand (Expr * e) inline
Definition at line 1783 of file TypeLoc.h.
References clang::DependentAddressSpaceLocInfo::ExprOperand, and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >::getLocalData().
Referenced by fillDependentAddressSpaceTypeLoc().
setAttrNameLoc()
void clang::DependentAddressSpaceTypeLoc::setAttrNameLoc (SourceLocation loc) inline
Definition at line 1773 of file TypeLoc.h.
References clang::DependentAddressSpaceLocInfo::AttrLoc, and clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >::getLocalData().
Referenced by fillDependentAddressSpaceTypeLoc().
setAttrOperandParensRange()
void clang::DependentAddressSpaceTypeLoc::setAttrOperandParensRange (SourceRange range) inline
Definition at line 1794 of file TypeLoc.h.
References clang::ConcreteTypeLoc< UnqualTypeLoc, DependentAddressSpaceTypeLoc, DependentAddressSpaceType, DependentAddressSpaceLocInfo >::getLocalData(), clang::DependentAddressSpaceLocInfo::OperandParens, and clang::transformer::range().
Referenced by fillDependentAddressSpaceTypeLoc().
The documentation for this class was generated from the following file:
include/clang/AST/TypeLoc.h