clang: clang::targets::NVPTXTargetInfo Class Reference
clang::targets::NVPTXTargetInfo Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Basic/Targets/NVPTX.h"
Public Member Functions
NVPTXTargetInfo (const llvm::Triple &Triple, const TargetOptions &Opts, unsigned TargetPointerWidth)
void getTargetDefines (const LangOptions &Opts, MacroBuilder &Builder) const override
===-— Other target property query methods -----------------------—===//
ArrayRef< Builtin::Info > getTargetBuiltins () const override
Return information about target-specific builtins for the current primary target, and info about which builtins are non-portable across the current set of primary and secondary targets.
bool initFeatureMap (llvm::StringMap< bool > &Features, DiagnosticsEngine &Diags, StringRef CPU, const std::vector< std::string > &FeaturesVec) const override
Initialize the map with the default set of target features for the CPU this should include all legal feature strings on the target.
bool hasFeature (StringRef Feature) const override
Determine whether the given target has the given feature.
ArrayRef< const char * > getGCCRegNames () const override
ArrayRef< TargetInfo::GCCRegAlias > getGCCRegAliases () const override
bool validateAsmConstraint (const char *&Name, TargetInfo::ConstraintInfo &Info) const override
const char * getClobbers () const override
Returns a string of target-specific clobbers, in LLVM format.
BuiltinVaListKind getBuiltinVaListKind () const override
Returns the kind of __builtin_va_list type that should be used with this target.
bool isValidCPUName (StringRef Name) const override
brief Determine whether this TargetInfo supports the given CPU name.
void fillValidCPUList (SmallVectorImpl< StringRef > &Values) const override
Fill a SmallVectorImpl with the valid values to setCPU.
bool setCPU (const std::string &Name) override
Target the specified CPU.
void setSupportedOpenCLOpts () override
Set supported OpenCL extensions and optional core features.
const llvm::omp::GV & getGridValue () const override
Optional< unsigned > getDWARFAddressSpace (unsigned AddressSpace) const override
CallingConvCheckResult checkCallingConvention (CallingConv CC) const override
Determines whether a given calling convention is valid for the target.
void adjust (DiagnosticsEngine &Diags, LangOptions &Opts) override
Set forced language options.
bool hasBitIntType () const override
Determine whether the _BitInt type is supported on this target.
Public Member Functions inherited from clang::TargetInfo
virtual ~TargetInfo ()
TargetOptions & getTargetOpts () const
Retrieve the target options.
IntType getSizeType () const
IntType getSignedSizeType () const
IntType getIntMaxType () const
IntType getUIntMaxType () const
IntType getPtrDiffType (unsigned AddrSpace) const
IntType getUnsignedPtrDiffType (unsigned AddrSpace) const
IntType getIntPtrType () const
IntType getUIntPtrType () const
IntType getWCharType () const
IntType getWIntType () const
IntType getChar16Type () const
IntType getChar32Type () const
IntType getInt64Type () const
IntType getUInt64Type () const
IntType getInt16Type () const
IntType getUInt16Type () const
IntType getSigAtomicType () const
IntType getProcessIDType () const
bool doUnsignedFixedPointTypesHavePadding () const
In the event this target uses the same number of fractional bits for its unsigned types as it does with its signed counterparts, there will be exactly one bit of padding.
unsigned getTypeWidth (IntType T) const
Return the width (in bits) of the specified integer type enum.
virtual IntType getIntTypeByWidth (unsigned BitWidth, bool IsSigned) const
Return integer type with specified width.
virtual IntType getLeastIntTypeByWidth (unsigned BitWidth, bool IsSigned) const
Return the smallest integer type with at least the specified width.
FloatModeKind getRealTypeByWidth (unsigned BitWidth, FloatModeKind ExplicitType) const
Return floating point type with specified width.
unsigned getTypeAlign (IntType T) const
Return the alignment (in bits) of the specified integer type enum.
uint64_t getPointerWidth (unsigned AddrSpace) const
Return the width of pointers on this target, for the specified address space.
uint64_t getPointerAlign (unsigned AddrSpace) const
virtual uint64_t getMaxPointerWidth () const
Return the maximum width of pointers on this target.
virtual uint64_t getNullPointerValue (LangAS AddrSpace) const
Get integer value for null pointer.
unsigned getBoolWidth () const
Return the size of '_Bool' and C++ 'bool' for this target, in bits.
unsigned getBoolAlign () const
Return the alignment of '_Bool' and C++ 'bool' for this target.
unsigned getCharWidth () const
unsigned getCharAlign () const
unsigned getShortWidth () const
Return the size of 'signed short' and 'unsigned short' for this target, in bits.
unsigned getShortAlign () const
Return the alignment of 'signed short' and 'unsigned short' for this target.
unsigned getIntWidth () const
getIntWidth/Align - Return the size of 'signed int' and 'unsigned int' for this target, in bits.
unsigned getIntAlign () const
unsigned getLongWidth () const
getLongWidth/Align - Return the size of 'signed long' and 'unsigned long' for this target, in bits.
unsigned getLongAlign () const
unsigned getLongLongWidth () const
getLongLongWidth/Align - Return the size of 'signed long long' and 'unsigned long long' for this target, in bits.
unsigned getLongLongAlign () const
unsigned getShortAccumWidth () const
getShortAccumWidth/Align - Return the size of 'signed short _Accum' and 'unsigned short _Accum' for this target, in bits.
unsigned getShortAccumAlign () const
unsigned getAccumWidth () const
getAccumWidth/Align - Return the size of 'signed _Accum' and 'unsigned _Accum' for this target, in bits.
unsigned getAccumAlign () const
unsigned getLongAccumWidth () const
getLongAccumWidth/Align - Return the size of 'signed long _Accum' and 'unsigned long _Accum' for this target, in bits.
unsigned getLongAccumAlign () const
unsigned getShortFractWidth () const
getShortFractWidth/Align - Return the size of 'signed short _Fract' and 'unsigned short _Fract' for this target, in bits.
unsigned getShortFractAlign () const
unsigned getFractWidth () const
getFractWidth/Align - Return the size of 'signed _Fract' and 'unsigned _Fract' for this target, in bits.
unsigned getFractAlign () const
unsigned getLongFractWidth () const
getLongFractWidth/Align - Return the size of 'signed long _Fract' and 'unsigned long _Fract' for this target, in bits.
unsigned getLongFractAlign () const
unsigned getShortAccumScale () const
getShortAccumScale/IBits - Return the number of fractional/integral bits in a 'signed short _Accum' type.
unsigned getShortAccumIBits () const
unsigned getAccumScale () const
getAccumScale/IBits - Return the number of fractional/integral bits in a 'signed _Accum' type.
unsigned getAccumIBits () const
unsigned getLongAccumScale () const
getLongAccumScale/IBits - Return the number of fractional/integral bits in a 'signed long _Accum' type.
unsigned getLongAccumIBits () const
unsigned getUnsignedShortAccumScale () const
getUnsignedShortAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned short _Accum' type.
unsigned getUnsignedShortAccumIBits () const
unsigned getUnsignedAccumScale () const
getUnsignedAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned _Accum' type.
unsigned getUnsignedAccumIBits () const
unsigned getUnsignedLongAccumScale () const
getUnsignedLongAccumScale/IBits - Return the number of fractional/integral bits in a 'unsigned long _Accum' type.
unsigned getUnsignedLongAccumIBits () const
unsigned getShortFractScale () const
getShortFractScale - Return the number of fractional bits in a 'signed short _Fract' type.
unsigned getFractScale () const
getFractScale - Return the number of fractional bits in a 'signed _Fract' type.
unsigned getLongFractScale () const
getLongFractScale - Return the number of fractional bits in a 'signed long _Fract' type.
unsigned getUnsignedShortFractScale () const
getUnsignedShortFractScale - Return the number of fractional bits in a 'unsigned short _Fract' type.
unsigned getUnsignedFractScale () const
getUnsignedFractScale - Return the number of fractional bits in a 'unsigned _Fract' type.
unsigned getUnsignedLongFractScale () const
getUnsignedLongFractScale - Return the number of fractional bits in a 'unsigned long _Fract' type.
virtual bool hasInt128Type () const
Determine whether the __int128 type is supported on this target.
virtual size_t getMaxBitIntWidth () const
virtual bool hasLegalHalfType () const
Determine whether _Float16 is supported on this target.
virtual bool hasFloat128Type () const
Determine whether the __float128 type is supported on this target.
virtual bool hasFloat16Type () const
Determine whether the _Float16 type is supported on this target.
virtual bool hasBFloat16Type () const
Determine whether the _BFloat16 type is supported on this target.
virtual bool hasIbm128Type () const
Determine whether the __ibm128 type is supported on this target.
virtual bool hasLongDoubleType () const
Determine whether the long double type is supported on this target.
virtual bool hasFPReturn () const
Determine whether return of a floating point value is supported on this target.
virtual bool hasStrictFP () const
Determine whether constrained floating point is supported on this target.
unsigned getSuitableAlign () const
Return the alignment that is the largest alignment ever used for any scalar/SIMD data type on the target machine you are compiling for (including types with an extended alignment requirement).
unsigned getDefaultAlignForAttributeAligned () const
Return the default alignment for attribute((aligned)) on this target, to be used if no alignment value is specified.
virtual unsigned getMinGlobalAlign (uint64_t) const
getMinGlobalAlign - Return the minimum alignment of a global variable, unless its alignment is explicitly reduced via attributes.
unsigned getNewAlign () const
Return the largest alignment for which a suitably-sized allocation with '::operator new(size_t)' is guaranteed to produce a correctly-aligned pointer.
unsigned getWCharWidth () const
getWCharWidth/Align - Return the size of 'wchar_t' for this target, in bits.
unsigned getWCharAlign () const
unsigned getChar16Width () const
getChar16Width/Align - Return the size of 'char16_t' for this target, in bits.
unsigned getChar16Align () const
unsigned getChar32Width () const
getChar32Width/Align - Return the size of 'char32_t' for this target, in bits.
unsigned getChar32Align () const
unsigned getHalfWidth () const
getHalfWidth/Align/Format - Return the size/align/format of 'half'.
unsigned getHalfAlign () const
const llvm::fltSemantics & getHalfFormat () const
unsigned getFloatWidth () const
getFloatWidth/Align/Format - Return the size/align/format of 'float'.
unsigned getFloatAlign () const
const llvm::fltSemantics & getFloatFormat () const
unsigned getBFloat16Width () const
getBFloat16Width/Align/Format - Return the size/align/format of '__bf16'.
unsigned getBFloat16Align () const
const llvm::fltSemantics & getBFloat16Format () const
unsigned getDoubleWidth () const
getDoubleWidth/Align/Format - Return the size/align/format of 'double'.
unsigned getDoubleAlign () const
const llvm::fltSemantics & getDoubleFormat () const
unsigned getLongDoubleWidth () const
getLongDoubleWidth/Align/Format - Return the size/align/format of 'long double'.
unsigned getLongDoubleAlign () const
const llvm::fltSemantics & getLongDoubleFormat () const
unsigned getFloat128Width () const
getFloat128Width/Align/Format - Return the size/align/format of '__float128'.
unsigned getFloat128Align () const
const llvm::fltSemantics & getFloat128Format () const
unsigned getIbm128Width () const
getIbm128Width/Align/Format - Return the size/align/format of '__ibm128'.
unsigned getIbm128Align () const
const llvm::fltSemantics & getIbm128Format () const
virtual const char * getLongDoubleMangling () const
Return the mangled code of long double.
virtual const char * getFloat128Mangling () const
Return the mangled code of __float128.
virtual const char * getIbm128Mangling () const
Return the mangled code of __ibm128.
virtual const char * getBFloat16Mangling () const
Return the mangled code of bfloat.
virtual LangOptions::FPEvalMethodKind getFPEvalMethod () const
Return the value for the C99 FLT_EVAL_METHOD macro.
virtual bool supportSourceEvalMethod () const
unsigned getLargeArrayMinWidth () const
unsigned getLargeArrayAlign () const
unsigned getMaxAtomicPromoteWidth () const
Return the maximum width lock-free atomic operation which will ever be supported for the given target.
unsigned getMaxAtomicInlineWidth () const
Return the maximum width lock-free atomic operation which can be inlined given the supported features of the given target.
virtual void setMaxAtomicWidth ()
Set the maximum inline or promote width lock-free atomic operation for the given target.
virtual bool hasBuiltinAtomic (uint64_t AtomicSizeInBits, uint64_t AlignmentInBits) const
Returns true if the given target supports lock-free atomic operations at the specified width and alignment.
unsigned getMaxVectorAlign () const
Return the maximum vector alignment supported for the given target.
unsigned getSimdDefaultAlign () const
Return default simd alignment for the given target.
unsigned getMaxOpenCLWorkGroupSize () const
virtual unsigned getExnObjectAlignment () const
Return the alignment (in bits) of the thrown exception object.
unsigned getIntMaxTWidth () const
Return the size of intmax_t and uintmax_t for this target, in bits.
unsigned getProgramAddressSpace () const
Return the address space for functions for the given target.
virtual unsigned getUnwindWordWidth () const
virtual unsigned getRegisterWidth () const
Return the "preferred" register width on this target.
const char * getUserLabelPrefix () const
Returns the default value of the USER_LABEL_PREFIX macro, which is the prefix given to user symbols by default.
const char * getMCountName () const
Returns the name of the mcount instrumentation function.
bool useSignedCharForObjCBool () const
Check if the Objective-C built-in boolean type should be signed char.
void noSignedCharForObjCBool ()
bool useBitFieldTypeAlignment () const
Check whether the alignment of bit-field types is respected when laying out structures.
bool useZeroLengthBitfieldAlignment () const
Check whether zero length bitfields should force alignment of the next member.
bool useLeadingZeroLengthBitfield () const
Check whether zero length bitfield alignment is respected if they are leading members.
unsigned getZeroLengthBitfieldBoundary () const
Get the fixed alignment value in bits for a member that follows a zero length bitfield.
unsigned getMaxAlignedAttribute () const
Get the maximum alignment in bits for a static variable with aligned attribute.
bool useExplicitBitFieldAlignment () const
Check whether explicit bitfield alignment attributes should be.
bool hasAlignMac68kSupport () const
Check whether this target support '#pragma options align=mac68k'.
const char * getTypeConstantSuffix (IntType T) const
Return the constant suffix for the specified integer type enum.
bool useObjCFPRetForRealType (FloatModeKind T) const
Check whether the given real type should use the "fpret" flavor of Objective-C message passing on this target.
bool useObjCFP2RetForComplexLongDouble () const
Check whether _Complex long double should use the "fp2ret" flavor of Objective-C message passing on this target.
virtual bool useFP16ConversionIntrinsics () const
Check whether llvm intrinsics such as llvm.convert.to.fp16 should be used to convert to and from __fp16.
bool useAddressSpaceMapMangling () const
Specify if mangling based on address space map should be used or not for language specific address spaces.
virtual Optional< std::pair< unsigned, unsigned > > getVScaleRange (const LangOptions &LangOpts) const
Returns target-specific min and max values VScale_Range.
virtual bool isCLZForZeroUndef () const
The __builtin_clz* and __builtin_ctz* built-in functions are specified to have undefined results for zero inputs, but on targets that support these operations in a way that provides well-defined results for zero without loss of performance, it is a good idea to avoid optimizing based on that undef behavior.
bool hasBuiltinMSVaList () const
Returns whether or not type __builtin_ms_va_list type is available on this target.
bool isRenderScriptTarget () const
Returns true for RenderScript.
bool hasAArch64SVETypes () const
Returns whether or not the AArch64 SVE built-in types are available on this target.
bool hasRISCVVTypes () const
Returns whether or not the RISC-V V built-in types are available on this target.
bool allowAMDGPUUnsafeFPAtomics () const
Returns whether or not the AMDGPU unsafe floating point atomics are allowed.
uint32_t getARMCDECoprocMask () const
For ARM targets returns a mask defining which coprocessors are configured as Custom Datapath.
bool isValidClobber (StringRef Name) const
Returns whether the passed in string is a valid clobber in an inline asm statement.
virtual bool isValidGCCRegisterName (StringRef Name) const
Returns whether the passed in string is a valid register name according to GCC.
StringRef getNormalizedGCCRegisterName (StringRef Name, bool ReturnCanonical=false) const
Returns the "normalized" GCC register name.
virtual bool isSPRegName (StringRef) const
virtual StringRef getConstraintRegister (StringRef Constraint, StringRef Expression) const
Extracts a register from the passed constraint (if it is a single-register constraint) and the asm label expression related to a variable in the input or output list of an inline asm statement.
virtual bool validateGlobalRegisterVariable (StringRef RegName, unsigned RegSize, bool &HasSizeMismatch) const
Validate register name used for global register variables.
bool validateOutputConstraint (ConstraintInfo &Info) const
bool validateInputConstraint (MutableArrayRef< ConstraintInfo > OutputConstraints, ConstraintInfo &info) const
virtual bool validateOutputSize (const llvm::StringMap< bool > &FeatureMap, StringRef, unsigned) const
virtual bool validateInputSize (const llvm::StringMap< bool > &FeatureMap, StringRef, unsigned) const
virtual bool validateConstraintModifier (StringRef, char, unsigned, std::string &) const
bool resolveSymbolicName (const char *&Name, ArrayRef< ConstraintInfo > OutputConstraints, unsigned &Index) const
virtual std::string convertConstraint (const char *&Constraint) const
virtual llvm::Optional< std::string > handleAsmEscapedChar (char C) const
Replace some escaped characters with another string based on target-specific rules.
virtual bool isNan2008 () const
Returns true if NaN encoding is IEEE 754-2008.
const llvm::Triple & getTriple () const
Returns the target triple of the primary target.
virtual llvm::Optional< std::string > getTargetID () const
Returns the target ID if supported.
const char * getDataLayoutString () const
virtual bool hasProtectedVisibility () const
Does this target support "protected" visibility?
virtual bool shouldDLLImportComdatSymbols () const
Does this target aim for semantic compatibility with Microsoft C++ code using dllimport/export attributes?
virtual bool hasPS4DLLImportExport () const
virtual void adjustTargetOptions (const CodeGenOptions &CGOpts, TargetOptions &TargetOpts) const
Adjust target options based on codegen options.
virtual StringRef getABI () const
Get the ABI currently in use.
TargetCXXABI getCXXABI () const
Get the C++ ABI currently in use.
virtual void fillValidTuneCPUList (SmallVectorImpl< StringRef > &Values) const
Fill a SmallVectorImpl with the valid values for tuning CPU.
virtual bool isValidTuneCPUName (StringRef Name) const
brief Determine whether this TargetInfo supports the given CPU name for
virtual bool supportsTargetAttributeTune () const
brief Determine whether this TargetInfo supports tune in target attribute.
virtual bool setABI (const std::string &Name)
Use the specified ABI.
virtual bool setFPMath (StringRef Name)
Use the specified unit for FP math.
virtual bool hasFeatureEnabled (const llvm::StringMap< bool > &Features, StringRef Name) const
Check if target has a given feature enabled.
virtual void setFeatureEnabled (llvm::StringMap< bool > &Features, StringRef Name, bool Enabled) const
Enable or disable a specific target feature; the feature name must be valid.
virtual bool isValidFeatureName (StringRef Feature) const
Determine whether this TargetInfo supports the given feature.
virtual bool isBranchProtectionSupportedArch (StringRef Arch) const
Determine if the Architecture in this TargetInfo supports branch protection.
virtual bool validateBranchProtection (StringRef Spec, StringRef Arch, BranchProtectionInfo &BPI, StringRef &Err) const
Determine if this TargetInfo supports the given branch protection specification.
virtual bool handleTargetFeatures (std::vector< std::string > &Features, DiagnosticsEngine &Diags)
Perform initialization based on the user configured set of features (e.g., +sse4).
bool supportsMultiVersioning () const
Identify whether this target supports multiversioning of functions, which requires support for cpu_supports and cpu_is functionality.
bool supportsIFunc () const
Identify whether this target supports IFuncs.
virtual bool validateCpuSupports (StringRef Name) const
virtual unsigned multiVersionSortPriority (StringRef Name) const
virtual bool validateCpuIs (StringRef Name) const
virtual bool validateCPUSpecificCPUDispatch (StringRef Name) const
virtual char CPUSpecificManglingCharacter (StringRef Name) const
virtual StringRef getCPUSpecificTuneName (StringRef Name) const
virtual void getCPUSpecificCPUDispatchFeatures (StringRef Name, llvm::SmallVectorImpl< StringRef > &Features) const
virtual Optional< unsigned > getCPUCacheLineSize () const
unsigned getRegParmMax () const
bool isTLSSupported () const
Whether the target supports thread-local storage.
unsigned getMaxTLSAlign () const
Return the maximum alignment (in bits) of a TLS variable.
bool isVLASupported () const
Whether target supports variable-length arrays.
bool isSEHTrySupported () const
Whether the target supports SEH __try.
bool hasNoAsmVariants () const
Return true if {|} are normal characters in the asm string.
virtual int getEHDataRegisterNumber (unsigned RegNo) const
Return the register number that __builtin_eh_return_regno would return with the specified argument.
virtual const char * getStaticInitSectionSpecifier () const
Return the section to use for C++ static initialization functions.
const LangASMap & getAddressSpaceMap () const
virtual LangAS getOpenCLBuiltinAddressSpace (unsigned AS) const
Map from the address space field in builtin description strings to the language address space.
virtual LangAS getCUDABuiltinAddressSpace (unsigned AS) const
Map from the address space field in builtin description strings to the language address space.
virtual llvm::Optional< LangAS > getConstantAddressSpace () const
Return an AST address space which can be used opportunistically for constant global memory.
StringRef getPlatformName () const
Retrieve the name of the platform as it is used in the availability attribute.
VersionTuple getPlatformMinVersion () const
Retrieve the minimum desired version of the platform, to which the program should be compiled.
bool isBigEndian () const
bool isLittleEndian () const
virtual bool supportsExtendIntArgs () const
Whether the option -fextend-arguments={32,64} is supported on the target.
virtual bool checkArithmeticFenceSupported () const
Controls if __arithmetic_fence is supported in the targeted backend.
virtual CallingConv getDefaultCallingConv () const
Gets the default calling convention for the given target and declaration context.
virtual CallingConvKind getCallingConvKind (bool ClangABICompat4) const
virtual bool hasSjLjLowering () const
Controls if __builtin_longjmp / __builtin_setjmp can be lowered to llvm.eh.sjlj.longjmp / llvm.eh.sjlj.setjmp.
virtual bool checkCFProtectionBranchSupported (DiagnosticsEngine &Diags) const
Check if the target supports CFProtection branch.
virtual bool checkCFProtectionReturnSupported (DiagnosticsEngine &Diags) const
Check if the target supports CFProtection branch.
virtual bool allowsLargerPreferedTypeAlignment () const
Whether target allows to overalign ABI-specified preferred alignment.
virtual bool defaultsToAIXPowerAlignment () const
Whether target defaults to the power alignment rules of AIX.
virtual void supportAllOpenCLOpts (bool V=true)
virtual void setCommandLineOpenCLOpts ()
Set supported OpenCL extensions as written on command line.
llvm::StringMap< bool > & getSupportedOpenCLOpts ()
Get supported OpenCL extensions and optional core features.
const llvm::StringMap< bool > & getSupportedOpenCLOpts () const
Get const supported OpenCL extensions and optional core features.
virtual LangAS getOpenCLTypeAddrSpace (OpenCLTypeKind TK) const
Get address space for OpenCL type.
virtual unsigned getVtblPtrAddressSpace () const
const llvm::VersionTuple & getSDKVersion () const
virtual bool validateTarget (DiagnosticsEngine &Diags) const
Check the target is valid after it is fully initialized.
virtual bool validateOpenCLTarget (const LangOptions &Opts, DiagnosticsEngine &Diags) const
Check that OpenCL target has valid options setting based on OpenCL version.
virtual void setAuxTarget (const TargetInfo *Aux)
virtual bool allowDebugInfoForExternalRef () const
Whether target allows debuginfo types for decl only variables/functions.
const llvm::Triple * getDarwinTargetVariantTriple () const
Returns the darwin target variant triple, the variant of the deployment target for which the code is being compiled.
const Optional< VersionTuple > getDarwinTargetVariantSDKVersion () const
Returns the version of the darwin target variant SDK which was used during the compilation if one was specified, or an empty version otherwise.
Additional Inherited Members
Public Types inherited from clang::TargetInfo
enum BuiltinVaListKind {
CharPtrBuiltinVaList = 0, VoidPtrBuiltinVaList, AArch64ABIBuiltinVaList, PNaClABIBuiltinVaList,
PowerABIBuiltinVaList, X86_64ABIBuiltinVaList, AAPCSABIBuiltinVaList, SystemZBuiltinVaList,
HexagonBuiltinVaList
}
The different kinds of __builtin_va_list types defined by the target implementation.
enum CallingConvCheckResult { CCCR_OK, CCCR_Warning, CCCR_Ignore, CCCR_Error }
enum CallingConvKind { CCK_Default, CCK_ClangABI4OrPS4, CCK_MicrosoftWin64 }
Public Types inherited from clang::TransferrableTargetInfo
enum IntType {
NoInt = 0, SignedChar, UnsignedChar, SignedShort,
UnsignedShort, SignedInt, UnsignedInt, SignedLong,
UnsignedLong, SignedLongLong, UnsignedLongLong
}
===-— Target Data Type Query Methods ----------------------------—===//
Static Public Member Functions inherited from clang::TargetInfo
static TargetInfo * CreateTargetInfo (DiagnosticsEngine &Diags, const std::shared_ptr< TargetOptions > &Opts)
Construct a target for the given options.
static IntType getCorrespondingUnsignedType (IntType T)
static bool isTypeSigned (IntType T)
Returns true if the type is signed; false otherwise.
static const char * getTypeName (IntType T)
Return the user string for the specified integer type enum.
static const char * getTypeFormatModifier (IntType T)
Return the printf format modifier for the specified integer type enum.
Public Attributes inherited from clang::TransferrableTargetInfo
unsigned char PointerWidth
unsigned char PointerAlign
unsigned char BoolWidth
unsigned char BoolAlign
unsigned char IntWidth
unsigned char IntAlign
unsigned char HalfWidth
unsigned char HalfAlign
unsigned char BFloat16Width
unsigned char BFloat16Align
unsigned char FloatWidth
unsigned char FloatAlign
unsigned char DoubleWidth
unsigned char DoubleAlign
unsigned char LongDoubleWidth
unsigned char LongDoubleAlign
unsigned char Float128Align
unsigned char Ibm128Align
unsigned char LargeArrayMinWidth
unsigned char LargeArrayAlign
unsigned char LongWidth
unsigned char LongAlign
unsigned char LongLongWidth
unsigned char LongLongAlign
unsigned char ShortAccumWidth
unsigned char ShortAccumAlign
unsigned char AccumWidth
unsigned char AccumAlign
unsigned char LongAccumWidth
unsigned char LongAccumAlign
unsigned char ShortFractWidth
unsigned char ShortFractAlign
unsigned char FractWidth
unsigned char FractAlign
unsigned char LongFractWidth
unsigned char LongFractAlign
bool PaddingOnUnsignedFixedPoint
unsigned char ShortAccumScale
unsigned char AccumScale
unsigned char LongAccumScale
unsigned char DefaultAlignForAttributeAligned
unsigned char MinGlobalAlign
unsigned short SuitableAlign
unsigned short NewAlign
unsigned MaxVectorAlign
unsigned MaxTLSAlign
const llvm::fltSemantics * HalfFormat
const llvm::fltSemantics * BFloat16Format
const llvm::fltSemantics * FloatFormat
const llvm::fltSemantics * DoubleFormat
const llvm::fltSemantics * LongDoubleFormat
const llvm::fltSemantics * Float128Format
const llvm::fltSemantics * Ibm128Format
Protected Member Functions inherited from clang::TargetInfo
TargetInfo (const llvm::Triple &T)
void resetDataLayout (StringRef DL, const char *UserLabelPrefix="")
void copyAuxTarget (const TargetInfo *Aux)
Copy type and layout related info.
virtual uint64_t getPointerWidthV (unsigned AddrSpace) const
virtual uint64_t getPointerAlignV (unsigned AddrSpace) const
virtual enum IntType getPtrDiffTypeV (unsigned AddrSpace) const
virtual ArrayRef< AddlRegName > getGCCAddlRegNames () const
Protected Attributes inherited from clang::TargetInfo
bool BigEndian
bool TLSSupported
bool VLASupported
bool NoAsmVariants
bool HasLegalHalfType
bool HasFloat128
bool HasFloat16
bool HasBFloat16
bool HasIbm128
bool HasLongDouble
bool HasFPReturn
bool HasStrictFP
unsigned char MaxAtomicPromoteWidth
unsigned char MaxAtomicInlineWidth
unsigned short SimdDefaultAlign
std::string DataLayoutString
const char * UserLabelPrefix
const char * MCountName
unsigned char RegParmMax
unsigned char SSERegParmMax
TargetCXXABI TheCXXABI
const LangASMap * AddrSpaceMap
unsigned ProgramAddrSpace
StringRef PlatformName
VersionTuple PlatformMinVersion
unsigned HasAlignMac68kSupport: 1
unsigned RealTypeUsesObjCFPRet: 3
unsigned ComplexLongDoubleUsesFP2Ret: 1
unsigned HasBuiltinMSVaList: 1
unsigned IsRenderScriptTarget: 1
unsigned HasAArch64SVETypes: 1
unsigned HasRISCVVTypes: 1
unsigned AllowAMDGPUUnsafeFPAtomics: 1
unsigned ARMCDECoprocMask: 8
unsigned MaxOpenCLWorkGroupSize
Optional< llvm::Triple > DarwinTargetVariantTriple
bool UseAddrSpaceMapMangling
Specify if mangling based on address space map should be used or not for language specific address spaces.
Protected Attributes inherited from clang::TransferrableTargetInfo
IntType SizeType
IntType IntMaxType
IntType PtrDiffType
IntType IntPtrType
IntType WCharType
IntType WIntType
IntType Char16Type
IntType Char32Type
IntType Int64Type
IntType Int16Type
IntType SigAtomicType
IntType ProcessIDType
unsigned UseSignedCharForObjCBool: 1
Whether Objective-C's built-in boolean type should be signed char.
unsigned UseBitFieldTypeAlignment: 1
Control whether the alignment of bit-field types is respected when laying out structures.
unsigned UseZeroLengthBitfieldAlignment: 1
Whether zero length bitfields (e.g., int : 0;) force alignment of the next bitfield.
unsigned UseLeadingZeroLengthBitfield: 1
Whether zero length bitfield alignment is respected if they are the leading members.
unsigned UseExplicitBitFieldAlignment: 1
Whether explicit bit field alignment attributes are honored.
unsigned ZeroLengthBitfieldBoundary
If non-zero, specifies a fixed alignment value for bitfields that follow zero length bitfield, regardless of the zero length bitfield type.
unsigned MaxAlignedAttribute
If non-zero, specifies a maximum alignment to truncate alignment specified in the aligned attribute of a static variable to this value.
Detailed Description
Definition at line 58 of file NVPTX.h.
Constructor & Destructor Documentation
NVPTXTargetInfo()
NVPTXTargetInfo::NVPTXTargetInfo (const llvm::Triple & Triple, const TargetOptions & Opts, unsigned TargetPointerWidth)
Definition at line 35 of file NVPTX.cpp.
References clang::TargetInfo::AddrSpaceMap, clang::targets::AllocateTarget(), clang::TransferrableTargetInfo::BoolAlign, clang::TransferrableTargetInfo::BoolWidth, clang::TransferrableTargetInfo::Char16Type, clang::TransferrableTargetInfo::Char32Type, clang::TransferrableTargetInfo::DefaultAlignForAttributeAligned, clang::TransferrableTargetInfo::DoubleAlign, clang::TransferrableTargetInfo::DoubleWidth, clang::TargetOptions::FeaturesAsWritten, clang::TransferrableTargetInfo::FloatAlign, clang::TransferrableTargetInfo::FloatWidth, clang::TransferrableTargetInfo::HalfAlign, clang::TransferrableTargetInfo::HalfWidth, clang::TargetInfo::HasFloat16, clang::TargetInfo::HasLegalHalfType, clang::TargetOptions::HostTriple, clang::TransferrableTargetInfo::Int64Type, clang::TransferrableTargetInfo::IntAlign, clang::TransferrableTargetInfo::IntMaxType, clang::TransferrableTargetInfo::IntPtrType, clang::TransferrableTargetInfo::IntWidth, clang::TransferrableTargetInfo::LongAlign, clang::TransferrableTargetInfo::LongLongAlign, clang::TransferrableTargetInfo::LongLongWidth, clang::TransferrableTargetInfo::LongWidth, clang::TargetInfo::MaxAtomicInlineWidth, clang::TransferrableTargetInfo::MinGlobalAlign, clang::TransferrableTargetInfo::NewAlign, clang::TargetInfo::NoAsmVariants, clang::targets::NVPTXAddrSpaceMap, clang::TargetOptions::NVPTXUseShortPointers, clang::TransferrableTargetInfo::PointerAlign, clang::TransferrableTargetInfo::PointerWidth, clang::TransferrableTargetInfo::ProcessIDType, clang::TransferrableTargetInfo::PtrDiffType, clang::TargetInfo::resetDataLayout(), clang::TransferrableTargetInfo::SigAtomicType, clang::TransferrableTargetInfo::SignedInt, clang::TransferrableTargetInfo::SignedLong, clang::TransferrableTargetInfo::SizeType, clang::SM_20, clang::TargetInfo::TLSSupported, clang::TransferrableTargetInfo::UnsignedInt, clang::TransferrableTargetInfo::UnsignedLong, clang::TargetInfo::UseAddrSpaceMapMangling, clang::TransferrableTargetInfo::UseBitFieldTypeAlignment, clang::TransferrableTargetInfo::UseExplicitBitFieldAlignment, clang::TransferrableTargetInfo::UseZeroLengthBitfieldAlignment, clang::TargetInfo::VLASupported, clang::TransferrableTargetInfo::WCharType, clang::TransferrableTargetInfo::WIntType, and clang::TransferrableTargetInfo::ZeroLengthBitfieldBoundary.
Member Function Documentation
adjust()
void clang::targets::NVPTXTargetInfo::adjust (DiagnosticsEngine & Diags, LangOptions & Opts) inline override virtual
Set forced language options.
adjust - Set forced language options.
Apply changes to the target information with respect to certain language options which change the target configuration and adjust the language based on the target options where applicable.
Reimplemented from clang::TargetInfo.
Definition at line 186 of file NVPTX.h.
References clang::TargetInfo::adjust().
checkCallingConvention()
CallingConvCheckResult clang::targets::NVPTXTargetInfo::checkCallingConvention (CallingConv CC) const inline override virtual
Determines whether a given calling convention is valid for the target.
A calling convention can either be accepted, produce a warning and be substituted with the default calling convention, or (someday) produce an error (such as using thiscall on a non-instance function).
Reimplemented from clang::TargetInfo.
Definition at line 176 of file NVPTX.h.
fillValidCPUList()
void clang::targets::NVPTXTargetInfo::fillValidCPUList (SmallVectorImpl< StringRef > & Values) const inline override virtual
Fill a SmallVectorImpl with the valid values to setCPU.
Reimplemented from clang::TargetInfo.
Definition at line 122 of file NVPTX.h.
References clang::CudaArchToString(), clang::Generic, and clang::SM_20.
getBuiltinVaListKind()
BuiltinVaListKind clang::targets::NVPTXTargetInfo::getBuiltinVaListKind () const inline override virtual
Returns the kind of __builtin_va_list type that should be used with this target.
Implements clang::TargetInfo.
Definition at line 113 of file NVPTX.h.
References clang::TargetInfo::CharPtrBuiltinVaList.
getClobbers()
const char* clang::targets::NVPTXTargetInfo::getClobbers () const inline override virtual
Returns a string of target-specific clobbers, in LLVM format.
Implements clang::TargetInfo.
Definition at line 108 of file NVPTX.h.
getDWARFAddressSpace()
Optional<unsigned> clang::targets::NVPTXTargetInfo::getDWARFAddressSpace (unsigned AddressSpace) const inline override virtual
Returns
If a target requires an address within a target specific address space AddressSpace to be converted in order to be used, then return the corresponding target specific DWARF address space.
Otherwise return None and no conversion will be emitted in the DWARF.
Reimplemented from clang::TargetInfo.
Definition at line 169 of file NVPTX.h.
References clang::targets::NVPTXDWARFAddrSpaceMap.
getGCCRegAliases()
ArrayRef<TargetInfo::GCCRegAlias> clang::targets::NVPTXTargetInfo::getGCCRegAliases () const inline override virtual
Implements clang::TargetInfo.
Definition at line 87 of file NVPTX.h.
getGCCRegNames()
ArrayRef< const char * > NVPTXTargetInfo::getGCCRegNames () const override virtual
Implements clang::TargetInfo.
Definition at line 170 of file NVPTX.cpp.
getGridValue()
const llvm::omp::GV& clang::targets::NVPTXTargetInfo::getGridValue () const inline override virtual
Reimplemented from clang::TargetInfo.
Definition at line 158 of file NVPTX.h.
getTargetBuiltins()
ArrayRef< Builtin::Info > NVPTXTargetInfo::getTargetBuiltins () const override virtual
Return information about target-specific builtins for the current primary target, and info about which builtins are non-portable across the current set of primary and secondary targets.
Implements clang::TargetInfo.
Definition at line 270 of file NVPTX.cpp.
References clang::Builtin::FirstTSBuiltin, and clang::NVPTX::LastTSBuiltin.
getTargetDefines()
void NVPTXTargetInfo::getTargetDefines (const LangOptions & Opts, MacroBuilder & Builder) const override virtual
===-— Other target property query methods -----------------------—===//
Appends the target-specific #define values for this target set to the specified buffer.
Implements clang::TargetInfo.
Definition at line 180 of file NVPTX.cpp.
hasBitIntType()
bool clang::targets::NVPTXTargetInfo::hasBitIntType () const inline override virtual
Determine whether the _BitInt type is supported on this target.
This limitation is put into place for ABI reasons. FIXME: _BitInt is a required type in C23, so there's not much utility in asking whether the target supported it or not; I think this should be removed once backends have been alerted to the type and have had the chance to do implementation work if needed.
Reimplemented from clang::TargetInfo.
Definition at line 192 of file NVPTX.h.
hasFeature()
bool NVPTXTargetInfo::hasFeature (StringRef Feature) const override virtual
Determine whether the given target has the given feature.
Reimplemented from clang::TargetInfo.
Definition at line 174 of file NVPTX.cpp.
initFeatureMap()
bool clang::targets::NVPTXTargetInfo::initFeatureMap (llvm::StringMap< bool > & Features, DiagnosticsEngine & Diags, StringRef CPU, const std::vector< std::string > & FeatureVec) const inline override virtual
Initialize the map with the default set of target features for the CPU this should include all legal feature strings on the target.
Returns
False on error (invalid features).
Reimplemented from clang::TargetInfo.
Definition at line 75 of file NVPTX.h.
References clang::CudaArchToString(), and clang::TargetInfo::initFeatureMap().
isValidCPUName()
bool clang::targets::NVPTXTargetInfo::isValidCPUName (StringRef Name) const inline override virtual
brief Determine whether this TargetInfo supports the given CPU name.
Reimplemented from clang::TargetInfo.
Definition at line 118 of file NVPTX.h.
setCPU()
bool clang::targets::NVPTXTargetInfo::setCPU (const std::string & Name) inline override virtual
Target the specified CPU.
Returns
False on error (invalid CPU name).
Reimplemented from clang::TargetInfo.
Definition at line 128 of file NVPTX.h.
setSupportedOpenCLOpts()
void clang::targets::NVPTXTargetInfo::setSupportedOpenCLOpts () inline override virtual
Set supported OpenCL extensions and optional core features.
Reimplemented from clang::TargetInfo.
Definition at line 133 of file NVPTX.h.
validateAsmConstraint()
bool clang::targets::NVPTXTargetInfo::validateAsmConstraint (const char *& Name, TargetInfo::ConstraintInfo & Info) const inline override virtual
Implements clang::TargetInfo.
Definition at line 92 of file NVPTX.h.
The documentation for this class was generated from the following files:
lib/Basic/Targets/NVPTX.h
lib/Basic/Targets/NVPTX.cpp