clang: clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo Class Reference
clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo Class Reference
API for captured statement code generation.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
CGCapturedStmtInfo (CapturedRegionKind K=CR_Default)
CGCapturedStmtInfo (const CapturedStmt &S, CapturedRegionKind K=CR_Default)
virtual ~CGCapturedStmtInfo ()
CapturedRegionKind getKind () const
virtual void setContextValue (llvm::Value *V)
virtual llvm::Value * getContextValue () const
virtual const FieldDecl * lookup (const VarDecl *VD) const
Lookup the captured field decl for a variable.
bool isCXXThisExprCaptured () const
virtual FieldDecl * getThisFieldDecl () const
virtual void EmitBody (CodeGenFunction &CGF, const Stmt *S)
Emit the captured statement body.
virtual StringRef getHelperName () const
Get the name of the capture helper.
llvm::SmallDenseMap< const VarDecl *, FieldDecl * > getCaptureFields ()
Get the CaptureFields.
Static Public Member Functions
static bool classof (const CGCapturedStmtInfo *)
Detailed Description
API for captured statement code generation.
Definition at line 406 of file CodeGenFunction.h.
Constructor & Destructor Documentation
CGCapturedStmtInfo() [1/2]
clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::CGCapturedStmtInfo (CapturedRegionKind K = CR_Default) inline explicit
Definition at line 408 of file CodeGenFunction.h.
CGCapturedStmtInfo() [2/2]
clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::CGCapturedStmtInfo (const CapturedStmt & S, CapturedRegionKind K = CR_Default) inline explicit
Definition at line 410 of file CodeGenFunction.h.
~CGCapturedStmtInfo()
CodeGenFunction::CGCapturedStmtInfo::~CGCapturedStmtInfo () virtual
Definition at line 2755 of file CodeGenFunction.cpp.
Member Function Documentation
classof()
static bool clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::classof (const CGCapturedStmtInfo *) inline static
Definition at line 444 of file CodeGenFunction.h.
EmitBody()
virtual void clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::EmitBody (CodeGenFunction & CGF, const Stmt * S) inline virtual
Emit the captured statement body.
Definition at line 449 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective().
getCaptureFields()
llvm::SmallDenseMap<const VarDecl *, FieldDecl *> clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::getCaptureFields () inline
Get the CaptureFields.
Definition at line 458 of file CodeGenFunction.h.
getContextValue()
virtual llvm::Value* clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::getContextValue () const inline virtual
Definition at line 434 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue().
getHelperName()
virtual StringRef clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::getHelperName () const inline virtual
Get the name of the capture helper.
Definition at line 455 of file CodeGenFunction.h.
getKind()
CapturedRegionKind clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::getKind () const inline
Definition at line 430 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::emitFunctionProlog().
getThisFieldDecl()
virtual FieldDecl* clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::getThisFieldDecl () const inline virtual
Definition at line 442 of file CodeGenFunction.h.
Referenced by isCXXThisExprCaptured().
isCXXThisExprCaptured()
bool clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::isCXXThisExprCaptured () const inline
Definition at line 441 of file CodeGenFunction.h.
References getThisFieldDecl().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas().
lookup()
virtual const FieldDecl* clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::lookup (const VarDecl * VD) const inline virtual
Lookup the captured field decl for a variable.
Definition at line 437 of file CodeGenFunction.h.
References clang::VarDecl::getCanonicalDecl().
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), and emitPrivatesInit().
setContextValue()
virtual void clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::setContextValue (llvm::Value * V) inline virtual
Definition at line 432 of file CodeGenFunction.h.
References V.
The documentation for this class was generated from the following files:
lib/CodeGen/CodeGenFunction.h
lib/CodeGen/CodeGenFunction.cpp