clang: clang::TypeOfTypeLoc Class Reference
clang::TypeOfTypeLoc Class Reference
#include "clang/AST/TypeLoc.h"
Public Member Functions
QualType getUnmodifiedType () const
TypeSourceInfo * getUnmodifiedTInfo () const
void setUnmodifiedTInfo (TypeSourceInfo *TI) const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
Public Member Functions inherited from clang::TypeofLikeTypeLoc< TypeOfTypeLoc, TypeOfType, TypeOfTypeLocInfo >
SourceLocation getTypeofLoc () const
void setTypeofLoc (SourceLocation Loc)
SourceLocation getLParenLoc () const
void setLParenLoc (SourceLocation Loc)
SourceLocation getRParenLoc () const
void setRParenLoc (SourceLocation Loc)
SourceRange getParensRange () const
void setParensRange (SourceRange range)
SourceRange getLocalSourceRange () const
void initializeLocal (ASTContext &Context, SourceLocation Loc)
Public Member Functions inherited from clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >
unsigned getLocalDataAlignment () const
unsigned getLocalDataSize () const
void copyLocal (Derived other)
TypeLoc getNextTypeLoc () const
const TypeClass * getTypePtr () const
Additional Inherited Members
Protected Member Functions inherited from clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >
unsigned getExtraLocalDataSize () const
unsigned getExtraLocalDataAlignment () const
LocalData * getLocalData () const
void * getExtraLocalData () const
Gets a pointer past the Info structure; useful for classes with local data that can't be captured in the Info (e.g.
void * getNonLocalData () const
HasNoInnerType getInnerType () const
TypeLoc getInnerTypeLoc () const
Detailed Description
Definition at line 2050 of file TypeLoc.h.
Member Function Documentation
getUnmodifiedTInfo()
TypeSourceInfo* clang::TypeOfTypeLoc::getUnmodifiedTInfo () const inline
Definition at line 2057 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalData().
getUnmodifiedType()
QualType clang::TypeOfTypeLoc::getUnmodifiedType () const inline
Definition at line 2053 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getTypePtr().
initializeLocal()
void TypeOfTypeLoc::initializeLocal (ASTContext & Context, SourceLocation Loc)
Definition at line 532 of file TypeLoc.cpp.
setUnmodifiedTInfo()
void clang::TypeOfTypeLoc::setUnmodifiedTInfo (TypeSourceInfo * TI) const inline
Definition at line 2061 of file TypeLoc.h.
References clang::ConcreteTypeLoc< Base, Derived, TypeClass, LocalData >::getLocalData().
The documentation for this class was generated from the following files:
include/clang/AST/TypeLoc.h
lib/AST/TypeLoc.cpp