clang: clang::api_notes::ObjCContextInfo Class Reference
clang::api_notes::ObjCContextInfo Class Reference
Describes API notes data for an Objective-C class or protocol.
#include "clang/APINotes/Types.h"
Public Member Functions
ObjCContextInfo ()
llvm::Optional< NullabilityKind > getDefaultNullability () const
Determine the default nullability for properties and methods of this class.
void setDefaultNullability (NullabilityKind Kind)
Set the default nullability for properties and methods of this class.
bool hasDesignatedInits () const
void setHasDesignatedInits (bool Value)
llvm::Optional< bool > getSwiftImportAsNonGeneric () const
void setSwiftImportAsNonGeneric (llvm::Optional< bool > Value)
llvm::Optional< bool > getSwiftObjCMembers () const
void setSwiftObjCMembers (llvm::Optional< bool > Value)
void stripModuleLocalInfo ()
Strip off any information within the class information structure that is module-local, such as 'audited' flags.
ObjCContextInfo & operator|= (const ObjCContextInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS)
Public Member Functions inherited from clang::api_notes::CommonTypeInfo
CommonTypeInfo ()
const llvm::Optional< std::string > & getSwiftBridge () const
void setSwiftBridge (const llvm::Optional< std::string > &SwiftType)
void setSwiftBridge (const llvm::Optional< llvm::StringRef > &SwiftType)
const llvm::Optional< std::string > & getNSErrorDomain () const
void setNSErrorDomain (const llvm::Optional< std::string > &Domain)
void setNSErrorDomain (const llvm::Optional< llvm::StringRef > &Domain)
CommonTypeInfo & operator|= (const CommonTypeInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::CommonEntityInfo
CommonEntityInfo ()
llvm::Optional< bool > isSwiftPrivate () const
void setSwiftPrivate (llvm::Optional< bool > Private)
CommonEntityInfo & operator|= (const CommonEntityInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Friends
bool operator== (const ObjCContextInfo &, const ObjCContextInfo &)
Additional Inherited Members
Public Attributes inherited from clang::api_notes::CommonEntityInfo
std::string UnavailableMsg
Message to use when this entity is unavailable.
unsigned Unavailable: 1
Whether this entity is marked unavailable.
unsigned UnavailableInSwift: 1
Whether this entity is marked unavailable in Swift.
std::string SwiftName
Swift name of this entity.
Detailed Description
Describes API notes data for an Objective-C class or protocol.
Definition at line 193 of file Types.h.
Constructor & Destructor Documentation
ObjCContextInfo()
clang::api_notes::ObjCContextInfo::ObjCContextInfo () inline
Definition at line 210 of file Types.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::api_notes::ObjCContextInfo::dump (llvm::raw_ostream & OS)
Definition at line 35 of file APINotesTypes.cpp.
References clang::api_notes::CommonTypeInfo::dump().
getDefaultNullability()
llvm::Optional<NullabilityKind> clang::api_notes::ObjCContextInfo::getDefaultNullability () const inline
Determine the default nullability for properties and methods of this class.
eturns the default nullability, if implied, or None if there is no
Definition at line 219 of file Types.h.
Referenced by clang::api_notes::operator==(), operator|=(), clang::api_notes::ObjCPropertyInfo::operator|=(), and clang::api_notes::ObjCMethodInfo::operator|=().
getSwiftImportAsNonGeneric()
llvm::Optional<bool> clang::api_notes::ObjCContextInfo::getSwiftImportAsNonGeneric () const inline
Definition at line 235 of file Types.h.
Referenced by clang::api_notes::operator==(), and operator|=().
getSwiftObjCMembers()
llvm::Optional<bool> clang::api_notes::ObjCContextInfo::getSwiftObjCMembers () const inline
Definition at line 245 of file Types.h.
Referenced by clang::api_notes::operator==(), and operator|=().
hasDesignatedInits()
bool clang::api_notes::ObjCContextInfo::hasDesignatedInits () const inline
Definition at line 232 of file Types.h.
operator|=()
ObjCContextInfo& clang::api_notes::ObjCContextInfo::operator|= (const ObjCContextInfo & RHS) inline
Definition at line 263 of file Types.h.
References getDefaultNullability(), getSwiftImportAsNonGeneric(), getSwiftObjCMembers(), setDefaultNullability(), setSwiftImportAsNonGeneric(), and setSwiftObjCMembers().
setDefaultNullability()
void clang::api_notes::ObjCContextInfo::setDefaultNullability (NullabilityKind Kind) inline
Set the default nullability for properties and methods of this class.
Definition at line 227 of file Types.h.
Referenced by operator|=().
setHasDesignatedInits()
void clang::api_notes::ObjCContextInfo::setHasDesignatedInits (bool Value) inline
Definition at line 233 of file Types.h.
setSwiftImportAsNonGeneric()
void clang::api_notes::ObjCContextInfo::setSwiftImportAsNonGeneric (llvm::Optional< bool > Value) inline
Definition at line 240 of file Types.h.
Referenced by operator|=().
setSwiftObjCMembers()
void clang::api_notes::ObjCContextInfo::setSwiftObjCMembers (llvm::Optional< bool > Value) inline
Definition at line 249 of file Types.h.
Referenced by operator|=().
stripModuleLocalInfo()
void clang::api_notes::ObjCContextInfo::stripModuleLocalInfo () inline
Strip off any information within the class information structure that is module-local, such as 'audited' flags.
Definition at line 256 of file Types.h.
Friends And Related Function Documentation
operator==
bool operator== (const ObjCContextInfo & LHS, const ObjCContextInfo & RHS) friend
Definition at line 286 of file Types.h.
The documentation for this class was generated from the following files:
include/clang/APINotes/Types.h
lib/APINotes/APINotesTypes.cpp