clang: clang::DeclContextLookupResult Class Reference
clang::DeclContextLookupResult Class Reference
The results of name lookup within a DeclContext.
#include "clang/AST/DeclBase.h"
Public Types
using iterator = DeclListNode::iterator
using const_iterator = iterator
using reference = iterator::reference
Public Member Functions
DeclContextLookupResult ()=default
DeclContextLookupResult (Decls Result)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
bool isSingleResult () const
reference front () const
template<class T >
T * find_first () const
Detailed Description
The results of name lookup within a DeclContext.
Definition at line 1371 of file DeclBase.h.
Member Typedef Documentation
const_iterator
using clang::DeclContextLookupResult::const_iterator = iterator
Definition at line 1382 of file DeclBase.h.
iterator
using clang::DeclContextLookupResult::iterator = DeclListNode::iterator
Definition at line 1381 of file DeclBase.h.
reference
using clang::DeclContextLookupResult::reference = iterator::reference
Definition at line 1383 of file DeclBase.h.
Constructor & Destructor Documentation
DeclContextLookupResult() [1/2]
clang::DeclContextLookupResult::DeclContextLookupResult () default
DeclContextLookupResult() [2/2]
clang::DeclContextLookupResult::DeclContextLookupResult (Decls Result) inline
Definition at line 1379 of file DeclBase.h.
Member Function Documentation
begin() [1/2]
iterator clang::DeclContextLookupResult::begin () inline
Definition at line 1385 of file DeclBase.h.
Referenced by begin(), clang::ObjCPropertyDecl::findPropertyDecl(), front(), clang::ObjCContainerDecl::getIvarDecl(), clang::ObjCContainerDecl::getMethod(), and clang::ObjCContainerDecl::HasUserDeclaredSetterMethod().
begin() [2/2]
const_iterator clang::DeclContextLookupResult::begin () const inline
Definition at line 1387 of file DeclBase.h.
References begin().
empty()
bool clang::DeclContextLookupResult::empty () const inline
Definition at line 1392 of file DeclBase.h.
Referenced by ClassImplementsAllMethodsAndProperties(), findImplicitlyDeclaredEqualityComparisons(), and lookupStdNamespace().
end() [1/2]
iterator clang::DeclContextLookupResult::end () inline
Definition at line 1386 of file DeclBase.h.
Referenced by clang::ObjCPropertyDecl::findPropertyDecl(), clang::ObjCContainerDecl::getIvarDecl(), clang::ObjCContainerDecl::getMethod(), and clang::ObjCContainerDecl::HasUserDeclaredSetterMethod().
end() [2/2]
const_iterator clang::DeclContextLookupResult::end () const inline
Definition at line 1390 of file DeclBase.h.
find_first()
template<class T > T* clang::DeclContextLookupResult::find_first () const inline
Definition at line 1400 of file DeclBase.h.
References clang::T.
Referenced by ClassImplementsAllMethodsAndProperties(), and clang::Sema::InstantiateClassMembers().
front()
reference clang::DeclContextLookupResult::front () const inline
Definition at line 1394 of file DeclBase.h.
References begin().
Referenced by allLookupResultsAreTheSame(), and lookupStdNamespace().
isSingleResult()
bool clang::DeclContextLookupResult::isSingleResult () const inline
Definition at line 1393 of file DeclBase.h.
Referenced by hasConflictingOverload().
The documentation for this class was generated from the following file:
include/clang/AST/DeclBase.h