clang: clang::driver::toolchains::MachO Class Reference
clang::driver::toolchains::MachO Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/Darwin.h"
Public Member Functions
MachO (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
~MachO () override
ToolChain Implementation
}
{
types::ID LookupTypeForExtension (StringRef Ext) const override
LookupTypeForExtension - Return the default language type to use for the given extension.
bool HasNativeLLVMSupport () const override
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
llvm::opt::DerivedArgList * TranslateArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
bool IsBlocksDefault () const override
IsBlocksDefault - Does this tool chain enable -fblocks by default.
bool IsIntegratedAssemblerDefault () const override
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
bool IsMathErrnoDefault () const override
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
bool IsEncodeExtendedBlockSignatureDefault () const override
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
bool IsObjCNonFragileABIDefault () const override
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
bool UseObjCMixedDispatch () const override
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
bool IsUnwindTablesDefault (const llvm::opt::ArgList &Args) const override
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
RuntimeLibType GetDefaultRuntimeLibType () const override
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
bool isPICDefault () const override
Test whether this toolchain defaults to PIC.
bool isPIEDefault (const llvm::opt::ArgList &Args) const override
Test whether this toolchain defaults to PIE.
bool isPICDefaultForced () const override
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
bool SupportsProfiling () const override
SupportsProfiling - Does this tool chain support -pg.
bool UseDwarfDebugFlags () const override
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
std::string GetGlobalDebugPathRemapping () const override
Add an additional -fdebug-prefix-map entry.
llvm::ExceptionHandling GetExceptionModel (const llvm::opt::ArgList &Args) const override
GetExceptionModel - Return the tool chain exception model.
virtual StringRef getOSLibraryNameSuffix (bool IgnoreSim=false) const
bool canSplitThinLTOUnit () const override
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
Public Member Functions inherited from clang::driver::ToolChain
virtual ~ToolChain ()
const Driver & getDriver () const
llvm::vfs::FileSystem & getVFS () const
const llvm::Triple & getTriple () const
virtual const llvm::Triple * getAuxTriple () const
Get the toolchain's aux triple, if it has one.
virtual std::string getInputFilename (const InputInfo &Input) const
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
llvm::Triple::ArchType getArch () const
StringRef getArchName () const
StringRef getPlatform () const
StringRef getOS () const
StringRef getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
std::string getTripleString () const
const llvm::Triple & getEffectiveTriple () const
Get the toolchain's effective clang triple.
path_list & getLibraryPaths ()
const path_list & getLibraryPaths () const
path_list & getFilePaths ()
const path_list & getFilePaths () const
path_list & getProgramPaths ()
const path_list & getProgramPaths () const
const MultilibSet & getMultilibs () const
const Multilib & getMultilib () const
SanitizerArgs getSanitizerArgs (const llvm::opt::ArgList &JobArgs) const
const XRayArgs & getXRayArgs () const
const llvm::opt::Arg * getRTTIArg () const
RTTIMode getRTTIMode () const
virtual llvm::opt::DerivedArgList * TranslateOffloadTargetArgs (const llvm::opt::DerivedArgList &Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > &AllocatedArgs, Action::OffloadKind DeviceOffloadKind) const
TranslateOffloadTargetArgs - Create a new derived argument list for that contains the Offload target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val Also handles -Xsycl-target OR -Xsycl-target=<triple>
virtual void TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, llvm::opt::Arg *&A, llvm::opt::DerivedArgList *DAL, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs=nullptr) const
Append the argument following A to DAL assuming A is an Xarch argument.
virtual llvm::opt::DerivedArgList * TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs) const
Translate -Xarch_ arguments.
virtual Tool * SelectTool (const JobAction &JA) const
Choose a tool to use to handle the action JA.
std::string GetFilePath (const char *Name) const
std::string GetProgramPath (const char *Name) const
std::string GetLinkerPath (bool *LinkerIsLLD=nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
std::string GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
virtual void printVerboseInfo (raw_ostream &OS) const
Dispatch to the specific toolchain for verbose printing.
virtual bool isCrossCompiling () const
Returns true if the toolchain is targeting a non-native architecture.
virtual bool useIntegratedAs () const
Check if the toolchain should use the integrated assembler.
virtual bool useIntegratedBackend () const
Check if the toolchain should use the integrated backend.
virtual bool parseInlineAsmUsingAsmParser () const
Check if the toolchain should use AsmParser to parse inlineAsm when integrated assembler is not default.
virtual bool useRelaxRelocations () const
Check whether to enable x86 relax relocations by default.
bool defaultToIEEELongDouble () const
Check whether use IEEE binary128 as long double format by default.
virtual LangOptions::StackProtectorMode GetDefaultStackProtectorLevel (bool KernelOrKext) const
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
virtual LangOptions::TrivialAutoVarInitKind GetDefaultTrivialAutoVarInit () const
Get the default trivial automatic variable initialization.
virtual const char * getDefaultLinker () const
GetDefaultLinker - Get the default linker to use.
virtual CXXStdlibType GetDefaultCXXStdlibType () const
virtual UnwindLibType GetDefaultUnwindLibType () const
virtual std::string getCompilerRTPath () const
virtual std::string getCompilerRT (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
const char * getCompilerRTArgString (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::string getCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
path_list getRuntimePaths () const
path_list getStdlibPaths () const
std::string getArchSpecificLibPath () const
virtual StringRef getOSLibName () const
virtual bool IsAArch64OutlineAtomicsDefault (const llvm::opt::ArgList &Args) const
Test whether this toolchain supports outline atomics by default.
virtual void CheckObjCARC () const
Complain if this tool chain doesn't support Objective-C ARC.
virtual codegenoptions::DebugInfoFormat getDefaultDebugFormat () const
Get the default debug info format. Typically, this is DWARF.
virtual unsigned GetDefaultDwarfVersion () const
virtual unsigned getMaxDwarfVersion () const
virtual bool GetDefaultStandaloneDebug () const
virtual llvm::DebuggerKind getDefaultDebuggerTuning () const
virtual bool supportsDebugInfoOption (const llvm::opt::Arg *) const
Does this toolchain supports given debug info option or not.
virtual void adjustDebugInfoKind (codegenoptions::DebugInfoKind &DebugInfoKind, const llvm::opt::ArgList &Args) const
Adjust debug information kind considering all passed options.
virtual bool SupportsEmbeddedBitcode () const
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
virtual std::string getThreadModel () const
getThreadModel() - Which thread model does this target use?
virtual bool isThreadModelSupported (const StringRef Model) const
isThreadModelSupported() - Does this target support a thread model?
virtual std::string getMultiarchTriple (const Driver &D, const llvm::Triple &TargetTriple, StringRef SysRoot) const
virtual std::string ComputeLLVMTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
virtual std::string ComputeEffectiveClangTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
virtual ObjCRuntime getDefaultObjCRuntime (bool isNonFragile) const
getDefaultObjCRuntime - Return the default Objective-C runtime for this platform.
virtual bool hasBlocksRuntime () const
hasBlocksRuntime - Given that the user is compiling with -fblocks, does this tool chain guarantee the existence of a blocks runtime?
virtual std::string computeSysRoot () const
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
virtual void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add the clang cc1 arguments for system include paths.
virtual void addClangTargetOptions (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, Action::OffloadKind DeviceOffloadKind) const
Add options that need to be passed to cc1 for this target.
virtual void addClangWarningOptions (llvm::opt::ArgStringList &CC1Args) const
Add warning options that need to be passed to cc1 for this target.
virtual RuntimeLibType GetRuntimeLibType (const llvm::opt::ArgList &Args) const
virtual CXXStdlibType GetCXXStdlibType (const llvm::opt::ArgList &Args) const
virtual UnwindLibType GetUnwindLibType (const llvm::opt::ArgList &Args) const
virtual std::string detectLibcxxVersion (StringRef IncludePath) const
virtual void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
void AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
bool ShouldLinkCXXStdlib (const llvm::opt::ArgList &Args) const
Returns if the C++ standard library should be linked in.
virtual void AddCXXStdlibLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
void AddFilePathLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
virtual void AddCCKextLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
virtual bool isFastMathRuntimeAvailable (const llvm::opt::ArgList &Args, std::string &Path) const
If a runtime library exists that sets global flags for unsafe floating point math, return true.
bool addFastMathRuntimeIfAvailable (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
virtual void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific CUDA includes.
virtual void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific HIP includes.
virtual void AddIAMCUIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use MCU GCC toolchain includes.
virtual VersionTuple computeMSVCVersion (const Driver *D, const llvm::opt::ArgList &Args) const
On Windows, returns the MSVC compatibility version.
virtual llvm::SmallVector< BitCodeLibraryInfo, 12 > getHIPDeviceLibs (const llvm::opt::ArgList &Args, const Action::OffloadKind DeviceOffloadingKind) const
Get paths of HIP device libraries.
virtual SanitizerMask getSupportedSanitizers () const
Return sanitizers which are available in this toolchain.
virtual SanitizerMask getDefaultSanitizers () const
Return sanitizers which are enabled by default.
virtual llvm::DenormalMode getDefaultDenormalModeForType (const llvm::opt::ArgList &DriverArgs, const JobAction &JA, const llvm::fltSemantics *FPType=nullptr) const
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
Protected Member Functions
Tool * buildAssembler () const override
Tool * buildLinker () const override
Tool * buildStaticLibTool () const override
Tool * getTool (Action::ActionClass AC) const override
Protected Member Functions inherited from clang::driver::ToolChain
ToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
void setTripleEnvironment (llvm::Triple::EnvironmentType Env)
virtual Tool * buildBackendCompiler () const
virtual std::string buildCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type, bool AddArch) const
MachO specific toolchain API
{
enum RuntimeLinkOptions : unsigned { RLO_AlwaysLink = 1 << 0, RLO_IsEmbedded = 1 << 1, RLO_AddRPath = 1 << 2 }
Options to control how a runtime library is linked.
StringRef getMachOArchName (const llvm::opt::ArgList &Args) const
Get the "MachO" arch name for a particular compiler invocation.
VersionTuple getLinkerVersion (const llvm::opt::ArgList &Args) const
Get the version of the linker known to be available for a particular compiler invocation (via the -mlinker-version= arg).
virtual void AddLinkARCArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
Add the linker arguments to link the ARC runtime library.
virtual void AddLinkRuntimeLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, bool ForceLinkBuiltinRT=false) const
Add the linker arguments to link the compiler runtime library.
virtual void addStartObjectFileArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
virtual void addMinVersionArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
virtual void addPlatformVersionArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
virtual bool isKernelStatic () const
On some iOS platforms, kernel and kernel modules were built statically.
bool isTargetIOSBased () const
Is the target either iOS or an iOS simulator?
void AddLinkRuntimeLib (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, StringRef Component, RuntimeLinkOptions Opts=RuntimeLinkOptions(), bool IsShared=false) const
Add a runtime library to the list of items to link.
void addProfileRTLibs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const override
Add any profiling runtime libraries that are needed.
Additional Inherited Members
Public Types inherited from clang::driver::ToolChain
enum CXXStdlibType { CST_Libcxx, CST_Libstdcxx }
enum RuntimeLibType { RLT_CompilerRT, RLT_Libgcc }
enum UnwindLibType { UNW_None, UNW_CompilerRT, UNW_Libgcc }
enum RTTIMode { RM_Enabled, RM_Disabled }
enum FileType { FT_Object, FT_Static, FT_Shared }
using path_list = SmallVector< std::string, 16 >
Static Public Member Functions inherited from clang::driver::ToolChain
static ParsedClangName getTargetAndModeFromProgramName (StringRef ProgName)
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
static bool needsProfileRT (const llvm::opt::ArgList &Args)
needsProfileRT - returns true if instrumentation profile is on.
static bool needsGCovInstrumentation (const llvm::opt::ArgList &Args)
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
static llvm::Triple getOpenMPTriple (StringRef TripleStr)
Static Protected Member Functions inherited from clang::driver::ToolChain
static void addSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory to CC1 arguments.
static void addExternCSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
static void addExternCSystemIncludeIfExists (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
static void addSystemIncludes (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, ArrayRef< StringRef > Paths)
Utility function to add a list of system include directories to CC1.
Protected Attributes inherited from clang::driver::ToolChain
MultilibSet Multilibs
Multilib SelectedMultilib
Detailed Description
Definition at line 138 of file Darwin.h.
Member Enumeration Documentation
RuntimeLinkOptions
enum clang::driver::toolchains::MachO::RuntimeLinkOptions : unsigned
Options to control how a runtime library is linked.
Enumerator
RLO_AlwaysLink
Link the library in even if it can't be found in the VFS.
RLO_IsEmbedded
Use the embedded runtime from the macho_embedded directory.
RLO_AddRPath
Emit rpaths for @executable_path as well as the resource directory.
Definition at line 200 of file Darwin.h.
Constructor & Destructor Documentation
MachO()
MachO::MachO (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args)
Definition at line 846 of file Darwin.cpp.
References clang::driver::ToolChain::getDriver(), and clang::driver::ToolChain::getProgramPaths().
~MachO()
MachO::~MachO () override
Definition at line 1005 of file Darwin.cpp.
Member Function Documentation
AddLinkARCArgs()
virtual void clang::driver::toolchains::MachO::AddLinkARCArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const inline virtual
Add the linker arguments to link the ARC runtime library.
Reimplemented in clang::driver::toolchains::DarwinClang.
Definition at line 170 of file Darwin.h.
AddLinkRuntimeLib()
void MachO::AddLinkRuntimeLib (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, StringRef Component, RuntimeLinkOptions Opts = RuntimeLinkOptions(), bool IsShared = false) const
Add a runtime library to the list of items to link.
Definition at line 1162 of file Darwin.cpp.
References clang::driver::ToolChain::getDriver(), getOSLibraryNameSuffix(), clang::driver::ToolChain::getVFS(), P, RLO_AddRPath, RLO_AlwaysLink, and RLO_IsEmbedded.
Referenced by AddLinkRuntimeLibArgs(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), and clang::driver::toolchains::Darwin::addProfileRTLibs().
AddLinkRuntimeLibArgs()
void MachO::AddLinkRuntimeLibArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, bool ForceLinkBuiltinRT = false) const virtual
Add the linker arguments to link the compiler runtime library.
FIXME: This API is intended for use with embedded libraries only, and is misleadingly named.
Reimplemented in clang::driver::toolchains::DarwinClang.
Definition at line 2644 of file Darwin.cpp.
References AddLinkRuntimeLib(), clang::driver::tools::arm::getARMFloatABI(), clang::driver::tools::arm::Hard, and RLO_IsEmbedded.
addMinVersionArgs()
virtual void clang::driver::toolchains::MachO::addMinVersionArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const inline virtual
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 185 of file Darwin.h.
addPlatformVersionArgs()
virtual void clang::driver::toolchains::MachO::addPlatformVersionArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const inline virtual
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 188 of file Darwin.h.
addProfileRTLibs()
void clang::driver::toolchains::MachO::addProfileRTLibs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const inline override virtual
Add any profiling runtime libraries that are needed.
This is essentially a MachO specific version of addProfileRT in Tools.cpp.
Reimplemented from clang::driver::ToolChain.
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 219 of file Darwin.h.
addStartObjectFileArgs()
virtual void clang::driver::toolchains::MachO::addStartObjectFileArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const inline virtual
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 181 of file Darwin.h.
buildAssembler()
Tool * MachO::buildAssembler () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 1056 of file Darwin.cpp.
buildLinker()
Tool * MachO::buildLinker () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 1050 of file Darwin.cpp.
buildStaticLibTool()
Tool * MachO::buildStaticLibTool () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 1052 of file Darwin.cpp.
canSplitThinLTOUnit()
bool clang::driver::toolchains::MachO::canSplitThinLTOUnit () const inline override virtual
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
Reimplemented from clang::driver::ToolChain.
Definition at line 283 of file Darwin.h.
GetDefaultRuntimeLibType()
RuntimeLibType clang::driver::toolchains::MachO::GetDefaultRuntimeLibType () const inline override virtual
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
Reimplemented from clang::driver::ToolChain.
Definition at line 259 of file Darwin.h.
References clang::driver::ToolChain::RLT_CompilerRT.
GetExceptionModel()
llvm::ExceptionHandling clang::driver::toolchains::MachO::GetExceptionModel (const llvm::opt::ArgList & Args) const inline override virtual
GetExceptionModel - Return the tool chain exception model.
Reimplemented from clang::driver::ToolChain.
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 273 of file Darwin.h.
References clang::XRayInstrKind::None.
Referenced by IsUnwindTablesDefault().
GetGlobalDebugPathRemapping()
std::string MachO::GetGlobalDebugPathRemapping () const override virtual
Add an additional -fdebug-prefix-map entry.
Reimplemented from clang::driver::ToolChain.
Definition at line 2840 of file Darwin.cpp.
getLinkerVersion()
VersionTuple MachO::getLinkerVersion (const llvm::opt::ArgList & Args) const
Get the version of the linker known to be available for a particular compiler invocation (via the -mlinker-version= arg).
Definition at line 982 of file Darwin.cpp.
References clang::driver::Driver::Diag(), and clang::driver::ToolChain::getDriver().
getMachOArchName()
StringRef MachO::getMachOArchName (const llvm::opt::ArgList & Args) const
Get the "MachO" arch name for a particular compiler invocation.
For example, Apple treats different ARM variations as distinct architectures.
Definition at line 954 of file Darwin.cpp.
References ArmMachOArchName(), ArmMachOArchNameCPU(), clang::driver::ToolChain::getArch(), clang::driver::ToolChain::getDefaultUniversalArchName(), and clang::driver::ToolChain::getTriple().
getOSLibraryNameSuffix()
virtual StringRef clang::driver::toolchains::MachO::getOSLibraryNameSuffix (bool IgnoreSim = false) const inline virtual
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 277 of file Darwin.h.
Referenced by AddLinkRuntimeLib().
getTool()
Tool * MachO::getTool (Action::ActionClass AC) const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 1031 of file Darwin.cpp.
References clang::driver::Action::DsymutilJobClass, clang::driver::ToolChain::getTool(), clang::driver::Action::LipoJobClass, and clang::driver::Action::VerifyDebugInfoJobClass.
HasNativeLLVMSupport()
bool MachO::HasNativeLLVMSupport () const override virtual
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
Reimplemented from clang::driver::ToolChain.
Definition at line 869 of file Darwin.cpp.
IsBlocksDefault()
bool clang::driver::toolchains::MachO::IsBlocksDefault () const inline override virtual
IsBlocksDefault - Does this tool chain enable -fblocks by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 236 of file Darwin.h.
IsEncodeExtendedBlockSignatureDefault()
bool clang::driver::toolchains::MachO::IsEncodeExtendedBlockSignatureDefault () const inline override virtual
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 248 of file Darwin.h.
IsIntegratedAssemblerDefault()
bool clang::driver::toolchains::MachO::IsIntegratedAssemblerDefault () const inline override virtual
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 241 of file Darwin.h.
isKernelStatic()
virtual bool clang::driver::toolchains::MachO::isKernelStatic () const inline virtual
On some iOS platforms, kernel and kernel modules were built statically.
Is this such a target?
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 194 of file Darwin.h.
IsMathErrnoDefault()
bool clang::driver::toolchains::MachO::IsMathErrnoDefault () const inline override virtual
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 246 of file Darwin.h.
IsObjCNonFragileABIDefault()
bool clang::driver::toolchains::MachO::IsObjCNonFragileABIDefault () const inline override virtual
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 250 of file Darwin.h.
isPICDefault()
bool MachO::isPICDefault () const override virtual
Test whether this toolchain defaults to PIC.
Implements clang::driver::ToolChain.
Definition at line 2867 of file Darwin.cpp.
isPICDefaultForced()
bool MachO::isPICDefaultForced () const override virtual
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
If this returns true, any PIC related flags should be ignored and instead the results of isPICDefault() and isPIEDefault(const llvm::opt::ArgList &Args) are used exclusively.
Implements clang::driver::ToolChain.
Definition at line 2871 of file Darwin.cpp.
References clang::driver::ToolChain::getArch().
isPIEDefault()
bool MachO::isPIEDefault (const llvm::opt::ArgList & Args) const override virtual
Test whether this toolchain defaults to PIE.
Implements clang::driver::ToolChain.
Definition at line 2869 of file Darwin.cpp.
isTargetIOSBased()
bool clang::driver::toolchains::MachO::isTargetIOSBased () const inline
Is the target either iOS or an iOS simulator?
Definition at line 197 of file Darwin.h.
IsUnwindTablesDefault()
bool MachO::IsUnwindTablesDefault (const llvm::opt::ArgList & Args) const override virtual
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 2825 of file Darwin.cpp.
References clang::driver::ToolChain::getArch(), and GetExceptionModel().
LookupTypeForExtension()
types::ID MachO::LookupTypeForExtension (StringRef Ext) const override virtual
LookupTypeForExtension - Return the default language type to use for the given extension.
Reimplemented from clang::driver::ToolChain.
Definition at line 859 of file Darwin.cpp.
References clang::driver::ToolChain::LookupTypeForExtension().
SupportsProfiling()
bool MachO::SupportsProfiling () const override virtual
SupportsProfiling - Does this tool chain support -pg.
Reimplemented from clang::driver::ToolChain.
Definition at line 2876 of file Darwin.cpp.
References clang::driver::ToolChain::getTriple().
Referenced by clang::driver::toolchains::Darwin::addStartObjectFileArgs().
TranslateArgs()
DerivedArgList * MachO::TranslateArgs (const llvm::opt::DerivedArgList & Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override virtual
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
If DeviceOffloadKind is specified the translation specific for that offload kind is performed.
Parameters
BoundArch - The bound architecture name, or 0.
DeviceOffloadKind - The device offload kind used for the translation.
Reimplemented from clang::driver::ToolChain.
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 2466 of file Darwin.cpp.
References clang::driver::ToolChain::getArchName(), clang::driver::ToolChain::getDriver(), clang::driver::Driver::getOpts(), clang::driver::options::LinkerInput, and clang::driver::ToolChain::TranslateXarchArgs().
Referenced by clang::driver::toolchains::Darwin::TranslateArgs().
UseDwarfDebugFlags()
bool MachO::UseDwarfDebugFlags () const override virtual
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
Reimplemented from clang::driver::ToolChain.
Definition at line 2834 of file Darwin.cpp.
UseObjCMixedDispatch()
bool clang::driver::toolchains::MachO::UseObjCMixedDispatch () const inline override virtual
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
Reimplemented from clang::driver::ToolChain.
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 255 of file Darwin.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Darwin.h
lib/Driver/ToolChains/Darwin.cpp