clang: clang::FPOptions Class Reference
clang::FPOptions Class Reference
#include "clang/Basic/LangOptions.h"
Public Types
using storage_type = uint32_t
using RoundingMode = llvm::RoundingMode
Public Member Functions
FPOptions ()
FPOptions (const LangOptions &LO)
bool allowFPContractWithinStatement () const
void setAllowFPContractWithinStatement ()
bool allowFPContractAcrossStatement () const
void setAllowFPContractAcrossStatement ()
bool isFPConstrained () const
RoundingMode getRoundingMode () const
LangOptions::FPExceptionModeKind getExceptionMode () const
bool operator== (FPOptions other) const
storage_type getAsOpaqueInt () const
FPOptionsOverride getChangesFrom (const FPOptions &Base) const
Return difference with the given option set.
void applyChanges (FPOptionsOverride FPO)
LLVM_DUMP_METHOD void dump ()
Static Public Member Functions
static FPOptions defaultWithoutTrailingStorage (const LangOptions &LO)
Return the default value of FPOptions that's used when trailing storage isn't required.
static FPOptions getFromOpaqueInt (storage_type Value)
Static Public Attributes
static constexpr unsigned StorageBitSize = 8 * sizeof(storage_type)
static constexpr storage_type FirstShift = 0
static constexpr storage_type FirstWidth = 0
static constexpr storage_type TotalWidth
Detailed Description
Definition at line 797 of file LangOptions.h.
Member Typedef Documentation
RoundingMode
using clang::FPOptions::RoundingMode = llvm::RoundingMode
Definition at line 802 of file LangOptions.h.
storage_type
using clang::FPOptions::storage_type = uint32_t
Definition at line 800 of file LangOptions.h.
Constructor & Destructor Documentation
FPOptions() [1/2]
clang::FPOptions::FPOptions () inline
Definition at line 829 of file LangOptions.h.
References clang::LangOptionsBase::FPE_Default, and clang::LangOptionsBase::FPM_Off.
FPOptions() [2/2]
clang::FPOptions::FPOptions (const LangOptions & LO) inline explicit
Definition at line 834 of file LangOptions.h.
References clang::LangOptionsBase::FPE_Strict, clang::LangOptionsBase::FPM_Fast, clang::LangOptionsBase::FPM_FastHonorPragmas, clang::LangOptionsBase::FPM_Off, clang::LangOptionsBase::FPM_On, getExceptionMode(), and getRoundingMode().
Member Function Documentation
allowFPContractAcrossStatement()
bool clang::FPOptions::allowFPContractAcrossStatement () const inline
Definition at line 870 of file LangOptions.h.
References clang::LangOptionsBase::FPM_Fast.
Referenced by clang::CodeGen::CodeGenFunction::SetFastMathFlags().
allowFPContractWithinStatement()
bool clang::FPOptions::allowFPContractWithinStatement () const inline
Definition at line 863 of file LangOptions.h.
References clang::LangOptionsBase::FPM_On.
Referenced by clang::UnaryOperator::isFPContractableWithinStatement(), and clang::BinaryOperator::isFPContractableWithinStatement().
applyChanges()
void clang::FPOptions::applyChanges (FPOptionsOverride FPO) inline
Definition at line 1065 of file LangOptions.h.
References clang::FPOptionsOverride::applyOverrides().
defaultWithoutTrailingStorage()
FPOptions FPOptions::defaultWithoutTrailingStorage (const LangOptions & LO) static
Return the default value of FPOptions that's used when trailing storage isn't required.
Definition at line 211 of file LangOptions.cpp.
Referenced by clang::Expr::getFPFeaturesInEffect(), clang::UnaryOperator::getFPFeaturesInEffect(), clang::CallExpr::getFPFeaturesInEffect(), clang::CastExpr::getFPFeaturesInEffect(), and clang::BinaryOperator::getFPFeaturesInEffect().
dump()
LLVM_DUMP_METHOD void FPOptions::dump ()
Definition at line 225 of file LangOptions.cpp.
getAsOpaqueInt()
storage_type clang::FPOptions::getAsOpaqueInt () const inline
Definition at line 912 of file LangOptions.h.
getChangesFrom()
FPOptionsOverride clang::FPOptions::getChangesFrom (const FPOptions & Base) const inline
Return difference with the given option set.
Definition at line 1059 of file LangOptions.h.
Referenced by clang::Sema::resetFPOptions().
getExceptionMode()
LangOptions::FPExceptionModeKind clang::FPOptions::getExceptionMode () const inline
Definition at line 895 of file LangOptions.h.
Referenced by clang::Sema::ActOnPragmaFloatControl(), checkFloatingPointResult(), FPOptions(), and isFPConstrained().
getFromOpaqueInt()
static FPOptions clang::FPOptions::getFromOpaqueInt (storage_type Value) inline static
Definition at line 913 of file LangOptions.h.
Referenced by clang::FPOptionsOverride::applyOverrides(), clang::FPOptionsOverride::getFromOpaqueInt(), and clang::ASTReader::ReadLateParsedTemplates().
getRoundingMode()
RoundingMode clang::FPOptions::getRoundingMode () const inline
Definition at line 883 of file LangOptions.h.
Referenced by checkFloatingPointResult(), FPOptions(), getActiveRoundingMode(), and isFPConstrained().
isFPConstrained()
bool clang::FPOptions::isFPConstrained () const inline
Definition at line 877 of file LangOptions.h.
References clang::LangOptionsBase::FPE_Ignore, getExceptionMode(), and getRoundingMode().
Referenced by EvaluateComparisonBinaryOperator().
operator==()
bool clang::FPOptions::operator== (FPOptions other) const inline
Definition at line 906 of file LangOptions.h.
setAllowFPContractAcrossStatement()
void clang::FPOptions::setAllowFPContractAcrossStatement () inline
Definition at line 873 of file LangOptions.h.
References clang::LangOptionsBase::FPM_Fast.
setAllowFPContractWithinStatement()
void clang::FPOptions::setAllowFPContractWithinStatement () inline
Definition at line 866 of file LangOptions.h.
References clang::LangOptionsBase::FPM_On.
Member Data Documentation
FirstShift
constexpr storage_type clang::FPOptions::FirstShift = 0 static constexpr
Definition at line 808 of file LangOptions.h.
FirstWidth
constexpr storage_type clang::FPOptions::FirstWidth = 0 static
Definition at line 808 of file LangOptions.h.
StorageBitSize
constexpr unsigned clang::FPOptions::StorageBitSize = 8 * sizeof(storage_type) static constexpr
Definition at line 804 of file LangOptions.h.
Referenced by clang::FPOptionsOverride::getAsOpaqueInt(), and clang::FPOptionsOverride::getFromOpaqueInt().
TotalWidth
constexpr storage_type clang::FPOptions::TotalWidth static constexpr
Initial value:
= 0
#define OPTION(NAME, TYPE, WIDTH, PREVIOUS)
Definition at line 817 of file LangOptions.h.
The documentation for this class was generated from the following files:
include/clang/Basic/LangOptions.h
lib/Basic/LangOptions.cpp