clang: clang::OMPInitClause Class Reference
clang::OMPInitClause Class Reference final
This represents the 'init' clause in '#pragma omp ...' directives.
#include "clang/AST/OpenMPClause.h"
Public Types
using prefs_iterator = MutableArrayRef< Expr * >::iterator
using const_prefs_iterator = ArrayRef< const Expr * >::iterator
using prefs_range = llvm::iterator_range< prefs_iterator >
using const_prefs_range = llvm::iterator_range< const_prefs_iterator >
Public Types inherited from clang::OMPVarListClause< OMPInitClause >
using varlist_iterator = MutableArrayRef< Expr * >::iterator
using varlist_const_iterator = ArrayRef< const Expr * >::iterator
using varlist_range = llvm::iterator_range< varlist_iterator >
using varlist_const_range = llvm::iterator_range< varlist_const_iterator >
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
SourceLocation getVarLoc () const
Returns the location of the interop variable.
Expr * getInteropVar ()
Returns the interop variable.
const Expr * getInteropVar () const
bool getIsTarget () const
Returns true is interop-type 'target' is used.
bool getIsTargetSync () const
Returns true is interop-type 'targetsync' is used.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
prefs_range prefs ()
const_prefs_range prefs () const
Public Member Functions inherited from clang::OMPVarListClause< OMPInitClause >
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_const_iterator varlist_begin () const
varlist_iterator varlist_end ()
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPInitClause * Create (const ASTContext &C, Expr *InteropVar, ArrayRef< Expr * > PrefExprs, bool IsTarget, bool IsTargetSync, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Creates a fully specified clause.
static OMPInitClause * CreateEmpty (const ASTContext &C, unsigned N)
Creates an empty clause with N expressions.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Protected Member Functions inherited from clang::OMPVarListClause< OMPInitClause >
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents the 'init' clause in '#pragma omp ...' directives.
#pragma omp interop init(target:obj)
Definition at line 7600 of file OpenMPClause.h.
Member Typedef Documentation
const_prefs_iterator
using clang::OMPInitClause::const_prefs_iterator = ArrayRef<const Expr *>::iterator
Definition at line 7699 of file OpenMPClause.h.
const_prefs_range
using clang::OMPInitClause::const_prefs_range = llvm::iterator_range<const_prefs_iterator>
Definition at line 7701 of file OpenMPClause.h.
prefs_iterator
using clang::OMPInitClause::prefs_iterator = MutableArrayRef<Expr *>::iterator
Definition at line 7698 of file OpenMPClause.h.
prefs_range
using clang::OMPInitClause::prefs_range = llvm::iterator_range<prefs_iterator>
Definition at line 7700 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPInitClause::children () inline
Definition at line 7681 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPInitClause >::varlist_begin(), and clang::OMPVarListClause< OMPInitClause >::varlist_end().
Referenced by children().
children() [2/2]
const_child_range clang::OMPInitClause::children () const inline
Definition at line 7686 of file OpenMPClause.h.
References children().
classof()
static bool clang::OMPInitClause::classof (const OMPClause * T) inline static
Definition at line 7713 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
Create()
OMPInitClause * OMPInitClause::Create (const ASTContext & C, Expr * InteropVar, ArrayRef< Expr * > PrefExprs, bool IsTarget, bool IsTargetSync, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc) static
Creates a fully specified clause.
Parameters
C AST context.
InteropVar The interop variable.
PrefExprs The list of preference expressions.
IsTarget Uses the 'target' interop-type.
IsTargetSync Uses the 'targetsync' interop-type.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
VarLoc Location of the interop variable.
EndLoc Ending location of the clause.
Definition at line 1579 of file OpenMPClause.cpp.
Referenced by clang::Sema::ActOnOpenMPInitClause().
CreateEmpty()
OMPInitClause * OMPInitClause::CreateEmpty (const ASTContext & C, unsigned N) static
Creates an empty clause with N expressions.
Parameters
C AST context.
N Number of expression items.
Definition at line 1595 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
getInteropVar() [1/2]
Expr* clang::OMPInitClause::getInteropVar () inline
Returns the interop variable.
Definition at line 7672 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPInitClause >::varlist_begin().
getInteropVar() [2/2]
const Expr* clang::OMPInitClause::getInteropVar () const inline
Definition at line 7673 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPInitClause >::varlist_begin().
getIsTarget()
bool clang::OMPInitClause::getIsTarget () const inline
Returns true is interop-type 'target' is used.
Definition at line 7676 of file OpenMPClause.h.
getIsTargetSync()
bool clang::OMPInitClause::getIsTargetSync () const inline
Returns true is interop-type 'targetsync' is used.
Definition at line 7679 of file OpenMPClause.h.
getVarLoc()
SourceLocation clang::OMPInitClause::getVarLoc () const inline
Returns the location of the interop variable.
Definition at line 7669 of file OpenMPClause.h.
prefs() [1/2]
prefs_range clang::OMPInitClause::prefs () inline
Definition at line 7703 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPInitClause >::varlist_begin(), and clang::OMPVarListClause< OMPInitClause >::varlist_end().
Referenced by prefs().
prefs() [2/2]
const_prefs_range clang::OMPInitClause::prefs () const inline
Definition at line 7708 of file OpenMPClause.h.
References prefs().
used_children() [1/2]
child_range clang::OMPInitClause::used_children () inline
Definition at line 7691 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPInitClause::used_children () const inline
Definition at line 7694 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 7603 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp