clang: clang::SemaMIPS Class Reference
clang::SemaMIPS Class Reference
#include "clang/Sema/SemaMIPS.h"
Public Member Functions
SemaMIPS (Sema &S)
bool CheckMipsBuiltinFunctionCall (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
bool CheckMipsBuiltinCpu (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
bool CheckMipsBuiltinArgument (unsigned BuiltinID, CallExpr *TheCall)
void handleInterruptAttr (Decl *D, const ParsedAttr &AL)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 24 of file SemaMIPS.h.
Constructor & Destructor Documentation
SemaMIPS()
clang::SemaMIPS::SemaMIPS (Sema & S)
Definition at line 22 of file SemaMIPS.cpp.
Member Function Documentation
CheckMipsBuiltinArgument()
bool clang::SemaMIPS::CheckMipsBuiltinArgument (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 65 of file SemaMIPS.cpp.
References clang::Sema::BuiltinConstantArgMultiple(), clang::Sema::BuiltinConstantArgRange(), and clang::SemaBase::SemaRef.
Referenced by CheckMipsBuiltinFunctionCall().
CheckMipsBuiltinCpu()
bool clang::SemaMIPS::CheckMipsBuiltinCpu (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 31 of file SemaMIPS.cpp.
References clang::SemaBase::Diag(), clang::CallExpr::getBeginLoc(), and clang::TargetInfo::hasFeature().
Referenced by CheckMipsBuiltinFunctionCall().
CheckMipsBuiltinFunctionCall()
bool clang::SemaMIPS::CheckMipsBuiltinFunctionCall (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 24 of file SemaMIPS.cpp.
References CheckMipsBuiltinArgument(), and CheckMipsBuiltinCpu().
handleInterruptAttr()
void clang::SemaMIPS::handleInterruptAttr (Decl * D, const ParsedAttr & AL)
Definition at line 242 of file SemaMIPS.cpp.
References clang::Sema::checkStringLiteralArgumentAttr(), D, clang::SemaBase::Diag(), clang::ExpectedFunctionOrMethod, clang::SemaBase::getASTContext(), clang::getFunctionOrMethodNumParams(), clang::getFunctionOrMethodResultType(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::hasFunctionProto(), clang::isFuncOrMethodForAttrSubject(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), Kind, and clang::SemaBase::SemaRef.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaMIPS.h
lib/Sema/SemaMIPS.cpp