clang: clang::OpenACCIndependentClause Class Reference
clang::OpenACCIndependentClause Class Reference
#include "clang/AST/OpenACCClause.h"
Public Member Functions
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClause
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Static Public Member Functions
static bool classof (const OpenACCClause *C)
static OpenACCIndependentClause * Create (const ASTContext &Ctx, SourceLocation BeginLoc, SourceLocation EndLoc)
Static Public Member Functions inherited from clang::OpenACCClause
static bool classof (const OpenACCClause *)
Protected Member Functions
OpenACCIndependentClause (SourceLocation BeginLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClause
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Additional Inherited Members
Public Types inherited from clang::OpenACCClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Detailed Description
Definition at line 80 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCIndependentClause()
clang::OpenACCIndependentClause::OpenACCIndependentClause (SourceLocation BeginLoc, SourceLocation EndLoc) inline protected
Definition at line 82 of file OpenACCClause.h.
References clang::Independent.
Referenced by Create().
Member Function Documentation
children() [1/2]
child_range clang::OpenACCIndependentClause::children () inline
Definition at line 93 of file OpenACCClause.h.
children() [2/2]
const_child_range clang::OpenACCIndependentClause::children () const inline
Definition at line 96 of file OpenACCClause.h.
classof()
static bool clang::OpenACCIndependentClause::classof (const OpenACCClause * C) inline static
Definition at line 86 of file OpenACCClause.h.
References clang::Independent.
Create()
OpenACCIndependentClause * OpenACCIndependentClause::Create (const ASTContext & Ctx, SourceLocation BeginLoc, SourceLocation EndLoc) static
Definition at line 331 of file OpenACCClause.cpp.
References OpenACCIndependentClause().
Referenced by clang::ASTRecordReader::readOpenACCClause().
The documentation for this class was generated from the following files:
include/clang/AST/OpenACCClause.h
lib/AST/OpenACCClause.cpp