clang: clang::CFGElement Class Reference
clang::CFGElement Class Reference
Represents a top-level expression in a basic block.
#include "clang/Analysis/CFG.h"
Public Types
enum Kind {
Initializer, ScopeBegin, ScopeEnd, NewAllocator,
LifetimeEnds, LoopExit, Statement, Constructor,
CXXRecordTypedCall, STMT_BEGIN = Statement, STMT_END = CXXRecordTypedCall, AutomaticObjectDtor,
DeleteDtor, BaseDtor, MemberDtor, TemporaryDtor,
DTOR_BEGIN = AutomaticObjectDtor, DTOR_END = TemporaryDtor
}
Public Member Functions
template<typename T >
T castAs () const
Convert to the specified CFGElement type, asserting that this CFGElement is of the desired type.
template<typename T >
Optional< T > getAs () const
Convert to the specified CFGElement type, returning None if this CFGElement is not of the desired type.
Kind getKind () const
void dumpToStream (llvm::raw_ostream &OS) const
void dump () const
Protected Member Functions
CFGElement (Kind kind, const void *Ptr1, const void *Ptr2=nullptr)
CFGElement ()=default
Protected Attributes
llvm::PointerIntPair< void *, 2 > Data1
llvm::PointerIntPair< void *, 2 > Data2
Detailed Description
Represents a top-level expression in a basic block.
Definition at line 55 of file CFG.h.
Member Enumeration Documentation
Kind
enum clang::CFGElement::Kind
Enumerator
Initializer
ScopeBegin
ScopeEnd
NewAllocator
LifetimeEnds
LoopExit
Statement
Constructor
CXXRecordTypedCall
STMT_BEGIN
STMT_END
AutomaticObjectDtor
DeleteDtor
BaseDtor
MemberDtor
TemporaryDtor
DTOR_BEGIN
DTOR_END
Definition at line 57 of file CFG.h.
Constructor & Destructor Documentation
CFGElement() [1/2]
clang::CFGElement::CFGElement (Kind kind, const void * Ptr1, const void * Ptr2 = nullptr) inline protected
Definition at line 86 of file CFG.h.
References getKind().
CFGElement() [2/2]
clang::CFGElement::CFGElement () protected default
Member Function Documentation
castAs()
template<typename T > T clang::CFGElement::castAs () const inline
Convert to the specified CFGElement type, asserting that this CFGElement is of the desired type.
Definition at line 98 of file CFG.h.
Referenced by CheckFallThrough(), clang::ento::CoreEngine::enqueueStmtNode(), getLocationForCaller(), print_elem(), clang::ento::ExprEngine::processCFGElement(), clang::ento::ExprEngine::ProcessImplicitDtor(), clang::consumed::ConsumedAnalyzer::run(), clang::ento::ExprEngine::VisitLogicalExpr(), and clang::threadSafety::CFGWalker::walk().
dump()
void clang::CFGElement::dump () const inline
Definition at line 127 of file CFG.h.
References dumpToStream().
dumpToStream()
void CFGElement::dumpToStream (llvm::raw_ostream & OS) const
Definition at line 5560 of file CFG.cpp.
References print_elem().
Referenced by dump().
getAs()
template<typename T > Optional<T> clang::CFGElement::getAs () const inline
Convert to the specified CFGElement type, returning None if this CFGElement is not of the desired type.
Definition at line 109 of file CFG.h.
Referenced by Accumulate(), CheckFallThrough(), clang::ento::CallEventManager::getCaller(), clang::ento::CallEvent::getConstructionContext(), clang::CFGBlock::getLastCondition(), isImmediateSinkBlock(), and ResolveCondition().
getKind()
Kind clang::CFGElement::getKind () const inline
Definition at line 118 of file CFG.h.
References Data1, Data2, and x.
Referenced by CFGElement(), clang::CFGImplicitDtor::getDestructorDecl(), getLocationForCaller(), print_elem(), clang::ento::ExprEngine::processCFGElement(), and clang::ento::ExprEngine::ProcessImplicitDtor().
Member Data Documentation
Data1
llvm::PointerIntPair<void *, 2> clang::CFGElement::Data1 protected
Definition at line 83 of file CFG.h.
Referenced by clang::CFGNewAllocator::getAllocatorExpr(), clang::CFGBaseDtor::getBaseSpecifier(), clang::CFGTemporaryDtor::getBindTemporaryExpr(), clang::CFGDeleteDtor::getCXXRecordDecl(), clang::CFGMemberDtor::getFieldDecl(), clang::CFGInitializer::getInitializer(), getKind(), clang::CFGLoopExit::getLoopStmt(), clang::CFGStmt::getStmt(), clang::CFGLifetimeEnds::getVarDecl(), clang::CFGScopeBegin::getVarDecl(), clang::CFGScopeEnd::getVarDecl(), and clang::CFGAutomaticObjDtor::getVarDecl().
Data2
llvm::PointerIntPair<void *, 2> clang::CFGElement::Data2 protected
Definition at line 84 of file CFG.h.
Referenced by clang::CFGConstructor::CFGConstructor(), clang::CFGCXXRecordTypedCall::CFGCXXRecordTypedCall(), clang::CFGConstructor::getConstructionContext(), clang::CFGCXXRecordTypedCall::getConstructionContext(), clang::CFGDeleteDtor::getDeleteExpr(), getKind(), clang::CFGLifetimeEnds::getTriggerStmt(), clang::CFGScopeBegin::getTriggerStmt(), clang::CFGScopeEnd::getTriggerStmt(), and clang::CFGAutomaticObjDtor::getTriggerStmt().
The documentation for this class was generated from the following files:
include/clang/Analysis/CFG.h
lib/Analysis/CFG.cpp