clang: clang::CodeGen::DefaultABIInfo Class Reference
clang::CodeGen::DefaultABIInfo Class Reference
DefaultABIInfo - The default implementation for ABI specific details.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/ABIInfoImpl.h"
Public Member Functions
DefaultABIInfo (CodeGen::CodeGenTypes &CGT)
virtual ~DefaultABIInfo ()
ABIArgInfo classifyReturnType (QualType RetTy) const
ABIArgInfo classifyArgumentType (QualType RetTy) const
void computeInfo (CGFunctionInfo &FI) const override
Address EmitVAArg (CodeGenFunction &CGF, Address VAListAddr, QualType Ty) const override
EmitVAArg - Emit the target dependent code to load a value of.
Public Member Functions inherited from clang::CodeGen::ABIInfo
ABIInfo (CodeGen::CodeGenTypes &cgt)
virtual ~ABIInfo ()
virtual bool allowBFloatArgsAndRet () const
CodeGen::CGCXXABI & getCXXABI () const
ASTContext & getContext () const
llvm::LLVMContext & getVMContext () const
const llvm::DataLayout & getDataLayout () const
const TargetInfo & getTarget () const
const CodeGenOptions & getCodeGenOpts () const
llvm::CallingConv::ID getRuntimeCC () const
Return the calling convention to use for system runtime functions.
bool isAndroid () const
bool isOHOSFamily () const
virtual CodeGen::Address EmitMSVAArg (CodeGen::CodeGenFunction &CGF, CodeGen::Address VAListAddr, QualType Ty) const
Emit the target dependent code to load a value of.
virtual bool isHomogeneousAggregateBaseType (QualType Ty) const
virtual bool isHomogeneousAggregateSmallEnough (const Type *Base, uint64_t Members) const
virtual bool isZeroLengthBitfieldPermittedInHomogeneousAggregate () const
bool isHomogeneousAggregate (QualType Ty, const Type *&Base, uint64_t &Members) const
isHomogeneousAggregate - Return true if a type is an ELFv2 homogeneous aggregate.
bool isPromotableIntegerTypeForABI (QualType Ty) const
CodeGen::ABIArgInfo getNaturalAlignIndirect (QualType Ty, bool ByVal=true, bool Realign=false, llvm::Type *Padding=nullptr) const
A convenience method to return an indirect ABIArgInfo with an expected alignment equal to the ABI alignment of the given type.
CodeGen::ABIArgInfo getNaturalAlignIndirectInReg (QualType Ty, bool Realign=false) const
virtual void appendAttributeMangling (TargetAttr *Attr, raw_ostream &Out) const
virtual void appendAttributeMangling (TargetVersionAttr *Attr, raw_ostream &Out) const
virtual void appendAttributeMangling (TargetClonesAttr *Attr, unsigned Index, raw_ostream &Out) const
virtual void appendAttributeMangling (StringRef AttrStr, raw_ostream &Out) const
Additional Inherited Members
Protected Attributes inherited from clang::CodeGen::ABIInfo
CodeGen::CodeGenTypes & CGT
llvm::CallingConv::ID RuntimeCC
Detailed Description
DefaultABIInfo - The default implementation for ABI specific details.
This implementation provides information which results in self-consistent and sensible LLVM IR generation, but does not conform to any particular ABI.
Definition at line 21 of file ABIInfoImpl.h.
Constructor & Destructor Documentation
DefaultABIInfo()
clang::CodeGen::DefaultABIInfo::DefaultABIInfo (CodeGen::CodeGenTypes & CGT) inline
Definition at line 23 of file ABIInfoImpl.h.
~DefaultABIInfo()
DefaultABIInfo::~DefaultABIInfo () virtual default
Member Function Documentation
classifyArgumentType()
ABIArgInfo DefaultABIInfo::classifyArgumentType (QualType RetTy) const
Definition at line 17 of file ABIInfoImpl.cpp.
References clang::Type::getAs(), clang::CodeGen::ABIInfo::getCXXABI(), clang::CodeGen::ABIInfo::getNaturalAlignIndirect(), clang::CodeGen::getRecordArgABI(), clang::CodeGen::isAggregateTypeForABI(), clang::CodeGen::CGCXXABI::RAA_DirectInMemory, and clang::CodeGen::useFirstFieldIfTransparentUnion().
Referenced by computeInfo(), and EmitVAArg().
classifyReturnType()
ABIArgInfo DefaultABIInfo::classifyReturnType (QualType RetTy) const
Definition at line 45 of file ABIInfoImpl.cpp.
References clang::Type::getAs(), clang::CodeGen::ABIInfo::getContext(), clang::CodeGen::ABIArgInfo::getDirect(), clang::CodeGen::ABIArgInfo::getExtend(), clang::CodeGen::ABIArgInfo::getIgnore(), clang::CodeGen::ABIInfo::getNaturalAlignIndirect(), clang::CodeGen::isAggregateTypeForABI(), clang::CodeGen::ABIInfo::isPromotableIntegerTypeForABI(), and clang::Type::isVoidType().
Referenced by computeInfo().
computeInfo()
void DefaultABIInfo::computeInfo (CGFunctionInfo & FI) const override virtual
Implements clang::CodeGen::ABIInfo.
Definition at line 67 of file ABIInfoImpl.cpp.
References clang::CodeGen::CGFunctionInfo::arguments(), classifyArgumentType(), classifyReturnType(), clang::CodeGen::ABIInfo::getCXXABI(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), and clang::CodeGen::CGFunctionInfo::getReturnType().
EmitVAArg()
Address DefaultABIInfo::EmitVAArg (CodeGenFunction & CGF, Address VAListAddr, QualType Ty) const override virtual
EmitVAArg - Emit the target dependent code to load a value of.
Ty from the va_list pointed to by
VAListAddr.
Implements clang::CodeGen::ABIInfo.
Definition at line 74 of file ABIInfoImpl.cpp.
References classifyArgumentType(), and clang::CodeGen::EmitVAArgInstr().
The documentation for this class was generated from the following files:
lib/CodeGen/ABIInfoImpl.h
lib/CodeGen/ABIInfoImpl.cpp