clang: clang::MicrosoftVTableContext Class Reference
clang::MicrosoftVTableContext Class Reference
#include "clang/AST/VTableBuilder.h"
Public Member Functions
MicrosoftVTableContext (ASTContext &Context)
~MicrosoftVTableContext () override
const VPtrInfoVector & getVFPtrOffsets (const CXXRecordDecl *RD)
const VTableLayout & getVFTableLayout (const CXXRecordDecl *RD, CharUnits VFPtrOffset)
MethodVFTableLocation getMethodVFTableLocation (GlobalDecl GD)
const ThunkInfoVectorTy * getThunkInfo (GlobalDecl GD) override
unsigned getVBTableIndex (const CXXRecordDecl *Derived, const CXXRecordDecl *VBase)
Returns the index of VBase in the vbtable of Derived.
const VPtrInfoVector & enumerateVBTables (const CXXRecordDecl *RD)
Public Member Functions inherited from clang::VTableContextBase
bool isMicrosoft () const
virtual ~VTableContextBase ()
Static Public Member Functions
static bool classof (const VTableContextBase *VT)
Static Public Member Functions inherited from clang::VTableContextBase
static bool hasVtableSlot (const CXXMethodDecl *MD)
Determine whether this function should be assigned a vtable slot.
Additional Inherited Members
Public Types inherited from clang::VTableContextBase
typedef SmallVector< ThunkInfo, 1 > ThunkInfoVectorTy
Public Attributes inherited from clang::VTableContextBase
bool IsMicrosoftABI
Protected Types inherited from clang::VTableContextBase
typedef llvm::DenseMap< const CXXMethodDecl *, ThunkInfoVectorTy > ThunksMapTy
Protected Member Functions inherited from clang::VTableContextBase
VTableContextBase (bool MS)
Protected Attributes inherited from clang::VTableContextBase
ThunksMapTy Thunks
Contains all thunks that a given method decl will need.
Detailed Description
Definition at line 544 of file VTableBuilder.h.
Constructor & Destructor Documentation
MicrosoftVTableContext()
clang::MicrosoftVTableContext::MicrosoftVTableContext (ASTContext & Context) inline
Definition at line 579 of file VTableBuilder.h.
~MicrosoftVTableContext()
MicrosoftVTableContext::~MicrosoftVTableContext () override
Definition at line 3416 of file VTableBuilder.cpp.
Member Function Documentation
classof()
static bool clang::MicrosoftVTableContext::classof (const VTableContextBase * VT) inline static
Definition at line 608 of file VTableBuilder.h.
References clang::VTableContextBase::isMicrosoft().
enumerateVBTables()
const VPtrInfoVector & MicrosoftVTableContext::enumerateVBTables (const CXXRecordDecl * RD)
Definition at line 3756 of file VTableBuilder.cpp.
References clang::VirtualBaseInfo::VBPtrPaths.
getMethodVFTableLocation()
MethodVFTableLocation MicrosoftVTableContext::getMethodVFTableLocation (GlobalDecl GD)
Definition at line 3779 of file VTableBuilder.cpp.
References clang::Dtor_Deleting, clang::GlobalDecl::getCanonicalDecl(), clang::GlobalDecl::getDecl(), clang::GlobalDecl::getDtorType(), clang::DeclContext::getParent(), and clang::VTableContextBase::hasVtableSlot().
getThunkInfo()
const ThunkInfoVectorTy* clang::MicrosoftVTableContext::getThunkInfo (GlobalDecl GD) inline override virtual
Reimplemented from clang::VTableContextBase.
Definition at line 591 of file VTableBuilder.h.
References clang::Dtor_Complete, clang::GlobalDecl::getDecl(), clang::GlobalDecl::getDtorType(), and clang::VTableContextBase::getThunkInfo().
getVBTableIndex()
unsigned MicrosoftVTableContext::getVBTableIndex (const CXXRecordDecl * Derived, const CXXRecordDecl * VBase)
Returns the index of VBase in the vbtable of Derived.
VBase must be a morally virtual base of Derived. The vbtable is an array of i32 offsets. The first entry is a self entry, and the rest are offsets from the vbptr to virtual bases.
Definition at line 3748 of file VTableBuilder.cpp.
References clang::VirtualBaseInfo::VBTableIndices.
getVFPtrOffsets()
const VPtrInfoVector & MicrosoftVTableContext::getVFPtrOffsets (const CXXRecordDecl * RD)
Definition at line 3761 of file VTableBuilder.cpp.
getVFTableLayout()
const VTableLayout & MicrosoftVTableContext::getVFTableLayout (const CXXRecordDecl * RD, CharUnits VFPtrOffset)
Definition at line 3769 of file VTableBuilder.cpp.
The documentation for this class was generated from the following files:
include/clang/AST/VTableBuilder.h
lib/AST/VTableBuilder.cpp