clang: clang::OMPMappableExprListClause< T > Class Template Reference
clang::OMPMappableExprListClause< T > Class Template Reference
This represents clauses with a list of expressions that are mappable.
#include "clang/AST/OpenMPClause.h"
Classes
class const_component_lists_iterator
Iterator that browse the components by lists.
Public Types
using const_component_lists_range = llvm::iterator_range< const_component_lists_iterator >
using const_all_decls_iterator = ArrayRef< ValueDecl * >::iterator
Iterators to access all the declarations, number of lists, list sizes, and components.
using const_all_decls_range = llvm::iterator_range< const_all_decls_iterator >
using const_all_num_lists_iterator = ArrayRef< unsigned >::iterator
using const_all_num_lists_range = llvm::iterator_range< const_all_num_lists_iterator >
using const_all_lists_sizes_iterator = ArrayRef< unsigned >::iterator
using const_all_lists_sizes_range = llvm::iterator_range< const_all_lists_sizes_iterator >
using const_all_components_iterator = ArrayRef< MappableComponent >::iterator
using const_all_components_range = llvm::iterator_range< const_all_components_iterator >
using mapperlist_iterator = MutableArrayRef< Expr * >::iterator
using mapperlist_const_iterator = ArrayRef< const Expr * >::iterator
using mapperlist_range = llvm::iterator_range< mapperlist_iterator >
using mapperlist_const_range = llvm::iterator_range< mapperlist_const_iterator >
Public Types inherited from clang::OMPVarListClause< T >
using varlist_iterator = MutableArrayRef< Expr * >::iterator
using varlist_const_iterator = ArrayRef< const Expr * >::iterator
using varlist_range = llvm::iterator_range< varlist_iterator >
using varlist_const_range = llvm::iterator_range< varlist_const_iterator >
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Types inherited from clang::OMPClauseMappableExprCommon
using MappableExprComponentList = SmallVector< MappableComponent, 8 >
using MappableExprComponentListRef = ArrayRef< MappableComponent >
using MappableExprComponentLists = SmallVector< MappableExprComponentList, 8 >
using MappableExprComponentListsRef = ArrayRef< MappableExprComponentList >
Public Member Functions
unsigned getUniqueDeclarationsNum () const
Return the number of unique base declarations in this clause.
unsigned getTotalComponentListNum () const
Return the number of lists derived from the clause expressions.
unsigned getTotalComponentsNum () const
Return the total number of components in all lists derived from the clause.
NestedNameSpecifierLoc getMapperQualifierLoc () const
Gets the nested name specifier for associated user-defined mapper.
const DeclarationNameInfo & getMapperIdInfo () const
Gets the name info for associated user-defined mapper.
const_component_lists_iterator component_lists_begin () const
Iterators for all component lists.
const_component_lists_iterator component_lists_end () const
const_component_lists_range component_lists () const
const_component_lists_iterator decl_component_lists_begin (const ValueDecl *VD) const
Iterators for component lists associated with the provided declaration.
const_component_lists_iterator decl_component_lists_end () const
const_component_lists_range decl_component_lists (const ValueDecl *VD) const
const_all_decls_range all_decls () const
const_all_num_lists_range all_num_lists () const
const_all_lists_sizes_range all_lists_sizes () const
const_all_components_range all_components () const
mapperlist_iterator mapperlist_begin ()
mapperlist_iterator mapperlist_end ()
mapperlist_const_iterator mapperlist_begin () const
mapperlist_const_iterator mapperlist_end () const
mapperlist_range mapperlists ()
mapperlist_const_range mapperlists () const
Public Member Functions inherited from clang::OMPVarListClause< T >
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_iterator varlist_end ()
varlist_const_iterator varlist_begin () const
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Protected Member Functions
OMPMappableExprListClause (OpenMPClauseKind K, const OMPVarListLocTy &Locs, const OMPMappableExprListSizeTy &Sizes, bool SupportsMapper=false, NestedNameSpecifierLoc *MapperQualifierLocPtr=nullptr, DeclarationNameInfo *MapperIdInfoPtr=nullptr)
Build a clause for NumUniqueDeclarations declarations, NumComponentLists total component lists, and NumComponents total components.
MutableArrayRef< ValueDecl * > getUniqueDeclsRef ()
Get the unique declarations that are in the trailing objects of the class.
ArrayRef< ValueDecl * > getUniqueDeclsRef () const
Get the unique declarations that are in the trailing objects of the class.
void setUniqueDecls (ArrayRef< ValueDecl * > UDs)
Set the unique declarations that are in the trailing objects of the class.
MutableArrayRef< unsigned > getDeclNumListsRef ()
Get the number of lists per declaration that are in the trailing objects of the class.
ArrayRef< unsigned > getDeclNumListsRef () const
Get the number of lists per declaration that are in the trailing objects of the class.
void setDeclNumLists (ArrayRef< unsigned > DNLs)
Set the number of lists per declaration that are in the trailing objects of the class.
MutableArrayRef< unsigned > getComponentListSizesRef ()
Get the cumulative component lists sizes that are in the trailing objects of the class.
ArrayRef< unsigned > getComponentListSizesRef () const
Get the cumulative component lists sizes that are in the trailing objects of the class.
void setComponentListSizes (ArrayRef< unsigned > CLSs)
Set the cumulative component lists sizes that are in the trailing objects of the class.
MutableArrayRef< MappableComponent > getComponentsRef ()
Get the components that are in the trailing objects of the class.
ArrayRef< MappableComponent > getComponentsRef () const
Get the components that are in the trailing objects of the class.
void setComponents (ArrayRef< MappableComponent > Components, ArrayRef< unsigned > CLSs)
Set the components that are in the trailing objects of the class.
void setClauseInfo (ArrayRef< ValueDecl * > Declarations, MappableExprComponentListsRef ComponentLists)
Fill the clause information from the list of declarations and associated component lists.
void setMapperQualifierLoc (NestedNameSpecifierLoc NNSL)
Set the nested name specifier of associated user-defined mapper.
void setMapperIdInfo (DeclarationNameInfo MapperId)
Set the name of associated user-defined mapper.
MutableArrayRef< Expr * > getUDMapperRefs ()
Get the user-defined mapper references that are in the trailing objects of the class.
ArrayRef< Expr * > getUDMapperRefs () const
Get the user-defined mappers references that are in the trailing objects of the class.
void setUDMapperRefs (ArrayRef< Expr * > DMDs)
Set the user-defined mappers that are in the trailing objects of the class.
Protected Member Functions inherited from clang::OMPVarListClause< T >
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Friends
class OMPClauseReader
Additional Inherited Members
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Protected Member Functions inherited from clang::OMPClauseMappableExprCommon
static unsigned getComponentsTotalNumber (MappableExprComponentListsRef ComponentLists)
static unsigned getUniqueDeclarationsTotalNumber (ArrayRef< const ValueDecl * > Declarations)
Detailed Description
template<class T>
class clang::OMPMappableExprListClause< T >
This represents clauses with a list of expressions that are mappable.
Examples of these clauses are 'map' in '#pragma omp target [enter|exit] [data]...' directives, and 'to' and 'from in '#pragma omp target update...' directives.
Definition at line 5311 of file OpenMPClause.h.
Member Typedef Documentation
const_all_components_iterator
template<class T > using clang::OMPMappableExprListClause< T >::const_all_components_iterator = ArrayRef<MappableComponent>::iterator
Definition at line 5831 of file OpenMPClause.h.
const_all_components_range
template<class T > using clang::OMPMappableExprListClause< T >::const_all_components_range = llvm::iterator_range<const_all_components_iterator>
Definition at line 5832 of file OpenMPClause.h.
const_all_decls_iterator
template<class T > using clang::OMPMappableExprListClause< T >::const_all_decls_iterator = ArrayRef<ValueDecl *>::iterator
Iterators to access all the declarations, number of lists, list sizes, and components.
Definition at line 5805 of file OpenMPClause.h.
const_all_decls_range
template<class T > using clang::OMPMappableExprListClause< T >::const_all_decls_range = llvm::iterator_range<const_all_decls_iterator>
Definition at line 5806 of file OpenMPClause.h.
const_all_lists_sizes_iterator
template<class T > using clang::OMPMappableExprListClause< T >::const_all_lists_sizes_iterator = ArrayRef<unsigned>::iterator
Definition at line 5822 of file OpenMPClause.h.
const_all_lists_sizes_range
template<class T > using clang::OMPMappableExprListClause< T >::const_all_lists_sizes_range = llvm::iterator_range<const_all_lists_sizes_iterator>
Definition at line 5823 of file OpenMPClause.h.
const_all_num_lists_iterator
template<class T > using clang::OMPMappableExprListClause< T >::const_all_num_lists_iterator = ArrayRef<unsigned>::iterator
Definition at line 5813 of file OpenMPClause.h.
const_all_num_lists_range
template<class T > using clang::OMPMappableExprListClause< T >::const_all_num_lists_range = llvm::iterator_range<const_all_num_lists_iterator>
Definition at line 5814 of file OpenMPClause.h.
const_component_lists_range
template<class T > using clang::OMPMappableExprListClause< T >::const_component_lists_range = llvm::iterator_range<const_component_lists_iterator>
Definition at line 5766 of file OpenMPClause.h.
mapperlist_const_iterator
template<class T > using clang::OMPMappableExprListClause< T >::mapperlist_const_iterator = ArrayRef<const Expr *>::iterator
Definition at line 5841 of file OpenMPClause.h.
mapperlist_const_range
template<class T > using clang::OMPMappableExprListClause< T >::mapperlist_const_range = llvm::iterator_range<mapperlist_const_iterator>
Definition at line 5843 of file OpenMPClause.h.
mapperlist_iterator
template<class T > using clang::OMPMappableExprListClause< T >::mapperlist_iterator = MutableArrayRef<Expr *>::iterator
Definition at line 5840 of file OpenMPClause.h.
mapperlist_range
template<class T > using clang::OMPMappableExprListClause< T >::mapperlist_range = llvm::iterator_range<mapperlist_iterator>
Definition at line 5842 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPMappableExprListClause()
template<class T > clang::OMPMappableExprListClause< T >::OMPMappableExprListClause (OpenMPClauseKind K, const OMPVarListLocTy & Locs, const OMPMappableExprListSizeTy & Sizes, bool SupportsMapper = false, NestedNameSpecifierLoc * MapperQualifierLocPtr = nullptr, DeclarationNameInfo * MapperIdInfoPtr = nullptr) inline protected
Build a clause for NumUniqueDeclarations declarations, NumComponentLists total component lists, and NumComponents total components.
Parameters
K Kind of the clause.
Locs Locations needed to build a mappable clause. It includes 1) StartLoc: starting location of the clause (the clause keyword); 2) LParenLoc: location of '('; 3) EndLoc: ending location of the clause.
Sizes All required sizes to build a mappable clause. It includes 1) NumVars: number of expressions listed in this clause; 2) NumUniqueDeclarations: number of unique base declarations in this clause; 3) NumComponentLists: number of component lists in this clause; and 4) NumComponents: total number of expression components in the clause.
SupportsMapper Indicates whether this clause is possible to have user-defined mappers associated.
MapperQualifierLocPtr C++ nested name specifier for the associated user-defined mapper.
MapperIdInfoPtr The identifier of associated user-defined mapper.
Definition at line 5354 of file OpenMPClause.h.
Member Function Documentation
all_components()
template<class T > const_all_components_range clang::OMPMappableExprListClause< T >::all_components () const inline
Definition at line 5835 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getComponentsRef().
all_decls()
template<class T > const_all_decls_range clang::OMPMappableExprListClause< T >::all_decls () const inline
Definition at line 5808 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getUniqueDeclsRef().
all_lists_sizes()
template<class T > const_all_lists_sizes_range clang::OMPMappableExprListClause< T >::all_lists_sizes () const inline
Definition at line 5826 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getComponentListSizesRef().
all_num_lists()
template<class T > const_all_num_lists_range clang::OMPMappableExprListClause< T >::all_num_lists () const inline
Definition at line 5817 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getDeclNumListsRef().
component_lists()
template<class T > const_component_lists_range clang::OMPMappableExprListClause< T >::component_lists () const inline
Definition at line 5783 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::component_lists_begin(), and clang::OMPMappableExprListClause< T >::component_lists_end().
component_lists_begin()
template<class T > const_component_lists_iterator clang::OMPMappableExprListClause< T >::component_lists_begin () const inline
Iterators for all component lists.
Definition at line 5770 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getComponentListSizesRef(), clang::OMPMappableExprListClause< T >::getComponentsRef(), clang::OMPMappableExprListClause< T >::getDeclNumListsRef(), clang::OMPMappableExprListClause< T >::getUDMapperRefs(), and clang::OMPMappableExprListClause< T >::getUniqueDeclsRef().
Referenced by clang::OMPMappableExprListClause< T >::component_lists().
component_lists_end()
template<class T > const_component_lists_iterator clang::OMPMappableExprListClause< T >::component_lists_end () const inline
Definition at line 5776 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getComponentsRef().
Referenced by clang::OMPMappableExprListClause< T >::component_lists(), and clang::OMPMappableExprListClause< T >::decl_component_lists_end().
decl_component_lists()
template<class T > const_component_lists_range clang::OMPMappableExprListClause< T >::decl_component_lists (const ValueDecl * VD) const inline
Definition at line 5799 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::decl_component_lists_begin(), and clang::OMPMappableExprListClause< T >::decl_component_lists_end().
decl_component_lists_begin()
template<class T > const_component_lists_iterator clang::OMPMappableExprListClause< T >::decl_component_lists_begin (const ValueDecl * VD) const inline
Iterators for component lists associated with the provided declaration.
Definition at line 5790 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getComponentListSizesRef(), clang::OMPMappableExprListClause< T >::getComponentsRef(), clang::OMPMappableExprListClause< T >::getDeclNumListsRef(), clang::OMPMappableExprListClause< T >::getUDMapperRefs(), and clang::OMPMappableExprListClause< T >::getUniqueDeclsRef().
Referenced by clang::OMPMappableExprListClause< T >::decl_component_lists().
decl_component_lists_end()
template<class T > const_component_lists_iterator clang::OMPMappableExprListClause< T >::decl_component_lists_end () const inline
Definition at line 5796 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::component_lists_end().
Referenced by clang::OMPMappableExprListClause< T >::decl_component_lists().
getComponentListSizesRef() [1/2]
template<class T > MutableArrayRef<unsigned> clang::OMPMappableExprListClause< T >::getComponentListSizesRef () inline protected
Get the cumulative component lists sizes that are in the trailing objects of the class.
They are appended after the number of lists.
Definition at line 5421 of file OpenMPClause.h.
References clang::T.
Referenced by clang::OMPMappableExprListClause< T >::all_lists_sizes(), clang::OMPMappableExprListClause< T >::component_lists_begin(), clang::OMPMappableExprListClause< T >::decl_component_lists_begin(), clang::OMPMappableExprListClause< T >::setClauseInfo(), and clang::OMPMappableExprListClause< T >::setComponentListSizes().
getComponentListSizesRef() [2/2]
template<class T > ArrayRef<unsigned> clang::OMPMappableExprListClause< T >::getComponentListSizesRef () const inline protected
Get the cumulative component lists sizes that are in the trailing objects of the class.
They are appended after the number of lists.
Definition at line 5430 of file OpenMPClause.h.
References clang::T.
getComponentsRef() [1/2]
template<class T > MutableArrayRef<MappableComponent> clang::OMPMappableExprListClause< T >::getComponentsRef () inline protected
Get the components that are in the trailing objects of the class.
Definition at line 5446 of file OpenMPClause.h.
References clang::T.
Referenced by clang::OMPMappableExprListClause< T >::all_components(), clang::OMPMappableExprListClause< T >::component_lists_begin(), clang::OMPMappableExprListClause< T >::component_lists_end(), and clang::OMPMappableExprListClause< T >::decl_component_lists_begin().
getComponentsRef() [2/2]
template<class T > ArrayRef<MappableComponent> clang::OMPMappableExprListClause< T >::getComponentsRef () const inline protected
Get the components that are in the trailing objects of the class.
Definition at line 5454 of file OpenMPClause.h.
References clang::T.
getDeclNumListsRef() [1/2]
template<class T > MutableArrayRef<unsigned> clang::OMPMappableExprListClause< T >::getDeclNumListsRef () inline protected
Get the number of lists per declaration that are in the trailing objects of the class.
Definition at line 5397 of file OpenMPClause.h.
References clang::T.
Referenced by clang::OMPMappableExprListClause< T >::all_num_lists(), clang::OMPMappableExprListClause< T >::component_lists_begin(), clang::OMPMappableExprListClause< T >::decl_component_lists_begin(), clang::OMPMappableExprListClause< T >::setClauseInfo(), and clang::OMPMappableExprListClause< T >::setDeclNumLists().
getDeclNumListsRef() [2/2]
template<class T > ArrayRef<unsigned> clang::OMPMappableExprListClause< T >::getDeclNumListsRef () const inline protected
Get the number of lists per declaration that are in the trailing objects of the class.
Definition at line 5405 of file OpenMPClause.h.
References clang::T.
getMapperIdInfo()
template<class T > const DeclarationNameInfo& clang::OMPMappableExprListClause< T >::getMapperIdInfo () const inline
Gets the name info for associated user-defined mapper.
Definition at line 5608 of file OpenMPClause.h.
getMapperQualifierLoc()
template<class T > NestedNameSpecifierLoc clang::OMPMappableExprListClause< T >::getMapperQualifierLoc () const inline
Gets the nested name specifier for associated user-defined mapper.
Definition at line 5603 of file OpenMPClause.h.
getTotalComponentListNum()
template<class T > unsigned clang::OMPMappableExprListClause< T >::getTotalComponentListNum () const inline
Return the number of lists derived from the clause expressions.
Definition at line 5596 of file OpenMPClause.h.
getTotalComponentsNum()
template<class T > unsigned clang::OMPMappableExprListClause< T >::getTotalComponentsNum () const inline
Return the total number of components in all lists derived from the clause.
Definition at line 5600 of file OpenMPClause.h.
getUDMapperRefs() [1/2]
template<class T > MutableArrayRef<Expr *> clang::OMPMappableExprListClause< T >::getUDMapperRefs () inline protected
Get the user-defined mapper references that are in the trailing objects of the class.
Definition at line 5561 of file OpenMPClause.h.
References clang::T.
Referenced by clang::OMPMappableExprListClause< T >::component_lists_begin(), clang::OMPMappableExprListClause< T >::decl_component_lists_begin(), clang::OMPMappableExprListClause< T >::mapperlist_begin(), clang::OMPMappableExprListClause< T >::mapperlist_end(), and clang::OMPMappableExprListClause< T >::setUDMapperRefs().
getUDMapperRefs() [2/2]
template<class T > ArrayRef<Expr *> clang::OMPMappableExprListClause< T >::getUDMapperRefs () const inline protected
Get the user-defined mappers references that are in the trailing objects of the class.
Definition at line 5572 of file OpenMPClause.h.
References clang::T.
getUniqueDeclarationsNum()
template<class T > unsigned clang::OMPMappableExprListClause< T >::getUniqueDeclarationsNum () const inline
Return the number of unique base declarations in this clause.
Definition at line 5593 of file OpenMPClause.h.
getUniqueDeclsRef() [1/2]
template<class T > MutableArrayRef<ValueDecl *> clang::OMPMappableExprListClause< T >::getUniqueDeclsRef () inline protected
Get the unique declarations that are in the trailing objects of the class.
Definition at line 5372 of file OpenMPClause.h.
References clang::T.
Referenced by clang::OMPMappableExprListClause< T >::all_decls(), clang::OMPMappableExprListClause< T >::component_lists_begin(), clang::OMPMappableExprListClause< T >::decl_component_lists_begin(), clang::OMPMappableExprListClause< T >::setClauseInfo(), and clang::OMPMappableExprListClause< T >::setUniqueDecls().
getUniqueDeclsRef() [2/2]
template<class T > ArrayRef<ValueDecl *> clang::OMPMappableExprListClause< T >::getUniqueDeclsRef () const inline protected
Get the unique declarations that are in the trailing objects of the class.
Definition at line 5380 of file OpenMPClause.h.
References clang::T.
mapperlist_begin() [1/2]
template<class T > mapperlist_iterator clang::OMPMappableExprListClause< T >::mapperlist_begin () inline
Definition at line 5846 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getUDMapperRefs().
Referenced by clang::OMPMappableExprListClause< T >::mapperlists().
mapperlist_begin() [2/2]
template<class T > mapperlist_const_iterator clang::OMPMappableExprListClause< T >::mapperlist_begin () const inline
Definition at line 5848 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getUDMapperRefs().
mapperlist_end() [1/2]
template<class T > mapperlist_iterator clang::OMPMappableExprListClause< T >::mapperlist_end () inline
Definition at line 5847 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getUDMapperRefs().
Referenced by clang::OMPMappableExprListClause< T >::mapperlists().
mapperlist_end() [2/2]
template<class T > mapperlist_const_iterator clang::OMPMappableExprListClause< T >::mapperlist_end () const inline
Definition at line 5851 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getUDMapperRefs().
mapperlists() [1/2]
template<class T > mapperlist_range clang::OMPMappableExprListClause< T >::mapperlists () inline
Definition at line 5854 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::mapperlist_begin(), and clang::OMPMappableExprListClause< T >::mapperlist_end().
mapperlists() [2/2]
template<class T > mapperlist_const_range clang::OMPMappableExprListClause< T >::mapperlists () const inline
Definition at line 5857 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::mapperlist_begin(), and clang::OMPMappableExprListClause< T >::mapperlist_end().
setClauseInfo()
template<class T > void clang::OMPMappableExprListClause< T >::setClauseInfo (ArrayRef< ValueDecl * > Declarations, MappableExprComponentListsRef ComponentLists) inline protected
Fill the clause information from the list of declarations and associated component lists.
Definition at line 5475 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getComponentListSizesRef(), clang::OMPClauseMappableExprCommon::getComponentsTotalNumber(), clang::OMPMappableExprListClause< T >::getDeclNumListsRef(), clang::OMPClauseMappableExprCommon::getUniqueDeclarationsTotalNumber(), and clang::OMPMappableExprListClause< T >::getUniqueDeclsRef().
Referenced by clang::OMPUseDevicePtrClause::Create(), clang::OMPIsDevicePtrClause::Create(), and clang::OMPMapClause::Create().
setComponentListSizes()
template<class T > void clang::OMPMappableExprListClause< T >::setComponentListSizes (ArrayRef< unsigned > CLSs) inline protected
Set the cumulative component lists sizes that are in the trailing objects of the class.
Definition at line 5439 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getComponentListSizesRef().
setComponents()
template<class T > void clang::OMPMappableExprListClause< T >::setComponents (ArrayRef< MappableComponent > Components, ArrayRef< unsigned > CLSs) inline protected
Set the components that are in the trailing objects of the class.
This requires the list sizes so that it can also fill the original expressions, which are the first component of each list.
Definition at line 5464 of file OpenMPClause.h.
setDeclNumLists()
template<class T > void clang::OMPMappableExprListClause< T >::setDeclNumLists (ArrayRef< unsigned > DNLs) inline protected
Set the number of lists per declaration that are in the trailing objects of the class.
Definition at line 5413 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getDeclNumListsRef().
setMapperIdInfo()
template<class T > void clang::OMPMappableExprListClause< T >::setMapperIdInfo (DeclarationNameInfo MapperId) inline protected
Set the name of associated user-defined mapper.
Definition at line 5555 of file OpenMPClause.h.
setMapperQualifierLoc()
template<class T > void clang::OMPMappableExprListClause< T >::setMapperQualifierLoc (NestedNameSpecifierLoc NNSL) inline protected
Set the nested name specifier of associated user-defined mapper.
Definition at line 5550 of file OpenMPClause.h.
setUDMapperRefs()
template<class T > void clang::OMPMappableExprListClause< T >::setUDMapperRefs (ArrayRef< Expr * > DMDs) inline protected
Set the user-defined mappers that are in the trailing objects of the class.
Definition at line 5583 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getUDMapperRefs().
Referenced by clang::OMPMapClause::Create().
setUniqueDecls()
template<class T > void clang::OMPMappableExprListClause< T >::setUniqueDecls (ArrayRef< ValueDecl * > UDs) inline protected
Set the unique declarations that are in the trailing objects of the class.
Definition at line 5389 of file OpenMPClause.h.
References clang::OMPMappableExprListClause< T >::getUniqueDeclsRef().
Friends And Related Function Documentation
OMPClauseReader
template<class T > friend class OMPClauseReader friend
Definition at line 5313 of file OpenMPClause.h.
The documentation for this class was generated from the following file:
include/clang/AST/OpenMPClause.h