clang: clang::InheritedConstructor Class Reference
clang::InheritedConstructor Class Reference
Description of a constructor that was inherited from a base class.
#include "clang/AST/DeclCXX.h"
Public Member Functions
InheritedConstructor ()=default
InheritedConstructor (ConstructorUsingShadowDecl *Shadow, CXXConstructorDecl *BaseCtor)
operator bool () const
ConstructorUsingShadowDecl * getShadowDecl () const
CXXConstructorDecl * getConstructor () const
Detailed Description
Description of a constructor that was inherited from a base class.
Definition at line 2503 of file DeclCXX.h.
Constructor & Destructor Documentation
InheritedConstructor() [1/2]
clang::InheritedConstructor::InheritedConstructor () default
InheritedConstructor() [2/2]
clang::InheritedConstructor::InheritedConstructor (ConstructorUsingShadowDecl * Shadow, CXXConstructorDecl * BaseCtor) inline
Definition at line 2509 of file DeclCXX.h.
Member Function Documentation
getConstructor()
CXXConstructorDecl* clang::InheritedConstructor::getConstructor () const inline
Definition at line 2516 of file DeclCXX.h.
Referenced by clang::ASTNodeImporter::ImportInheritedConstructor().
getShadowDecl()
ConstructorUsingShadowDecl* clang::InheritedConstructor::getShadowDecl () const inline
Definition at line 2515 of file DeclCXX.h.
Referenced by clang::ASTNodeImporter::ImportInheritedConstructor(), clang::CodeGen::CodeGenTypes::inheritingCtorHasParams(), and clang::Sema::NoteDeletedInheritingConstructor().
operator bool()
clang::InheritedConstructor::operator bool () const inline explicit
Definition at line 2513 of file DeclCXX.h.
The documentation for this class was generated from the following file:
include/clang/AST/DeclCXX.h