clang: clang::CharUnits Class Reference
clang::CharUnits Class Reference
CharUnits - This is an opaque type for sizes expressed in character units.
#include "clang/AST/CharUnits.h"
Public Types
typedef int64_t QuantityType
Public Member Functions
CharUnits ()=default
CharUnits - A default constructor.
CharUnits & operator+= (const CharUnits &Other)
CharUnits & operator++ ()
CharUnits operator++ (int)
CharUnits & operator-= (const CharUnits &Other)
CharUnits & operator-- ()
CharUnits operator-- (int)
bool operator== (const CharUnits &Other) const
bool operator!= (const CharUnits &Other) const
bool operator< (const CharUnits &Other) const
bool operator<= (const CharUnits &Other) const
bool operator> (const CharUnits &Other) const
bool operator>= (const CharUnits &Other) const
bool isZero () const
isZero - Test whether the quantity equals zero.
bool isOne () const
isOne - Test whether the quantity equals one.
bool isPositive () const
isPositive - Test whether the quantity is greater than zero.
bool isNegative () const
isNegative - Test whether the quantity is less than zero.
bool isPowerOfTwo () const
isPowerOfTwo - Test whether the quantity is a power of two.
bool isMultipleOf (CharUnits N) const
Test whether this is a multiple of the other value.
CharUnits operator* (QuantityType N) const
CharUnits & operator*= (QuantityType N)
CharUnits operator/ (QuantityType N) const
CharUnits & operator/= (QuantityType N)
QuantityType operator/ (const CharUnits &Other) const
CharUnits operator% (QuantityType N) const
QuantityType operator% (const CharUnits &Other) const
CharUnits operator+ (const CharUnits &Other) const
CharUnits operator- (const CharUnits &Other) const
CharUnits operator- () const
QuantityType getQuantity () const
getQuantity - Get the raw integer representation of this quantity.
llvm::Align getAsAlign () const
getAsAlign - Returns Quantity as a valid llvm::Align, Beware llvm::Align assumes power of two 8-bit bytes.
CharUnits alignTo (const CharUnits &Align) const
alignTo - Returns the next integer (mod 2**64) that is greater than or equal to this quantity and is a multiple of Align.
CharUnits alignmentAtOffset (CharUnits offset) const
Given that this is a non-zero alignment value, what is the alignment at the given offset?
CharUnits alignmentOfArrayElement (CharUnits elementSize) const
Given that this is the alignment of the first element of an array, return the minimum alignment of any element in the array.
Static Public Member Functions
static CharUnits Zero ()
Zero - Construct a CharUnits quantity of zero.
static CharUnits One ()
One - Construct a CharUnits quantity of one.
static CharUnits fromQuantity (QuantityType Quantity)
fromQuantity - Construct a CharUnits quantity from a raw integer type.
Detailed Description
CharUnits - This is an opaque type for sizes expressed in character units.
Instances of this type represent a quantity as a multiple of the size of the standard C type, char, on the target architecture. As an opaque type, CharUnits protects you from accidentally combining operations on quantities in bit units and character units.
In both C and C++, an object of type 'char', 'signed char', or 'unsigned char' occupies exactly one byte, so 'character unit' and 'byte' refer to the same quantity of storage. However, we use the term 'character unit' rather than 'byte' to avoid an implication that a character unit is exactly 8 bits.
For portability, never assume that a target character is 8 bits wide. Use CharUnit values wherever you calculate sizes, offsets, or alignments in character units.
Definition at line 38 of file CharUnits.h.
Member Typedef Documentation
QuantityType
typedef int64_t clang::CharUnits::QuantityType
Definition at line 40 of file CharUnits.h.
Constructor & Destructor Documentation
CharUnits()
clang::CharUnits::CharUnits () default
CharUnits - A default constructor.
Referenced by alignmentAtOffset(), alignTo(), fromQuantity(), One(), operator%(), operator*(), operator+(), operator++(), operator-(), operator--(), operator/(), and Zero().
Member Function Documentation
alignmentAtOffset()
CharUnits clang::CharUnits::alignmentAtOffset (CharUnits offset) const inline
Given that this is a non-zero alignment value, what is the alignment at the given offset?
Definition at line 194 of file CharUnits.h.
References CharUnits().
Referenced by alignmentOfArrayElement(), ApplyNonVirtualAndVirtualOffset(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), getArrayElementAlign(), and getBlockCaptureStr().
alignmentOfArrayElement()
CharUnits clang::CharUnits::alignmentOfArrayElement (CharUnits elementSize) const inline
Given that this is the alignment of the first element of an array, return the minimum alignment of any element in the array.
Definition at line 201 of file CharUnits.h.
References alignmentAtOffset().
Referenced by EmitArrayDelete(), clang::CodeGen::CodeGenFunction::EmitCXXAggrConstructorCall(), clang::CodeGen::CodeGenFunction::emitDestroy(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), emitNonZeroVLAInit(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), forConstantArrayExpansion(), and getArrayElementAlign().
alignTo()
CharUnits clang::CharUnits::alignTo (const CharUnits & Align) const inline
alignTo - Returns the next integer (mod 2**64) that is greater than or equal to this quantity and is a multiple of Align.
Align must be non-zero.
Definition at line 188 of file CharUnits.h.
References CharUnits().
Referenced by clang::CodeGen::ConstantAggregateBuilderBase::addPlaceholderWithSize(), computeBlockInfo(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), and clang::CodeGen::CodeGenFunction::getBlockByrefInfo().
fromQuantity()
static CharUnits clang::CharUnits::fromQuantity (QuantityType Quantity) inline static
fromQuantity - Construct a CharUnits quantity from a raw integer type.
Definition at line 63 of file CharUnits.h.
References CharUnits().
Referenced by clang::CodeGen::ConstantAggregateBuilderBase::addPlaceholderWithSize(), CheckAggExprForMemSetUse(), createPlaceholderSlot(), DumpRecordLayout(), emitAddressAtOffset(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrong(), clang::CodeGen::CodeGenFunction::EmitCall(), emitInterWarpCopyFunction(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), EmitX86_64VAArgFromMemory(), clang::CodeGen::CodeGenFunction::GenerateCXXGlobalInitFunc(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString(), clang::CodeGen::RValue::getAggregateAddress(), clang::CodeGen::AddressImpl< T, true >::getAlignment(), clang::CodeGen::LValue::getAlignment(), clang::CodeGen::CGFunctionInfo::getArgStructAlignment(), clang::ento::ElementRegion::getAsArrayOffset(), getBaseAlignmentAndOffsetFromLValue(), clang::CodeGen::CodeGenFunction::getBlockByrefInfo(), clang::CodeGen::swiftcall::SwiftAggLowering::getCoerceAndExpandTypes(), getConstantArrayInfoInChars(), clang::CodeGen::CodeGenFunction::getEHSelectorSlot(), llvm::DenseMapInfo< clang::BaseSubobject >::getEmptyKey(), llvm::DenseMapInfo< clang::CharUnits >::getEmptyKey(), clang::CodeGen::CodeGenFunction::ParamValue::getIndirectAddress(), clang::CodeGen::ABIArgInfo::getIndirectAlign(), clang::CodeGen::CodeGenTypeCache::getIntAlign(), clang::CodeGen::CodeGenTypeCache::getIntSize(), getLowBit(), getMaxAtomicAccessSize(), clang::CodeGen::swiftcall::getNaturalAlignment(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::CodeGen::CGBlockInfo::Capture::getOffset(), getOffsetAtStartOfUnit(), getOffsetOfFullPath(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenTypeCache::getPointerSize(), clang::CodeGen::CodeGenTypeCache::getSizeAlign(), clang::CodeGen::CodeGenTypeCache::getSizeSize(), llvm::DenseMapInfo< clang::BaseSubobject >::getTombstoneKey(), llvm::DenseMapInfo< clang::CharUnits >::getTombstoneKey(), getTypeAllocSize(), getTypeStoreSize(), initializeForBlockHeader(), isVarDeclStrongDefinition(), performTypeAdjustment(), clang::CodeGen::DominatingLLVMValue::save(), shuffleAndStore(), clang::analyze_os_log::OSLogBufferLayout::size(), clang::ASTContext::toCharUnitsFromBits(), and clang::ento::ExprEngine::VisitUnaryExprOrTypeTraitExpr().
getAsAlign()
llvm::Align clang::CharUnits::getAsAlign () const inline
getAsAlign - Returns Quantity as a valid llvm::Align, Beware llvm::Align assumes power of two 8-bit bytes.
Definition at line 183 of file CharUnits.h.
Referenced by buildGlobalBlock(), clang::CodeGen::CGBuilderTy::CreateAlignedStore(), CreateCoercedLoad(), CreateCoercedStore(), createLoadInstBefore(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), clang::CodeGen::CGBuilderTy::CreateMemCpyInline(), clang::CodeGen::CGBuilderTy::CreateMemMove(), clang::CodeGen::CGBuilderTy::CreateMemSet(), clang::CodeGen::CGBuilderTy::CreateStore(), createStoreInstBefore(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitDeleteCall(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), EmitNullBaseClassInitialization(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), clang::CodeGen::CodeGenFunction::EmitStaticVarDecl(), GenerateStringLiteral(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCString(), getInitThreadEpochPtr(), and clang::CodeGen::CodeGenFunction::setBeforeOutermostConditional().
getQuantity()
QuantityType clang::CharUnits::getQuantity () const inline
getQuantity - Get the raw integer representation of this quantity.
Definition at line 179 of file CharUnits.h.
Referenced by AddPointerLayoutOffset(), AddRelativeLayoutOffset(), clang::CodeGen::AddressImpl< T, true >::AddressImpl(), ApplyNonVirtualAndVirtualOffset(), clang::ASTContext::AtomicUsesUnsupportedLibcall(), buildBlockDescriptor(), buildGlobalBlock(), clang::Sema::BuildPredefinedExpr(), calculateOffset(), clang::ento::StoreManager::castRegion(), charUnitsToString(), clang::Sema::CheckCastAlign(), clang::Sema::CheckCXXThrowOperand(), computeBlockInfo(), clang::Sema::DefaultArgumentPromotion(), clang::Sema::DiagnoseSizeOfParametersAndReturnValue(), clang::CodeGen::ABIArgInfo::dump(), DumpRecordLayout(), clang::ento::RegionRawOffset::dumpToStream(), emitAlignedClause(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitAsanPrologueOrEpilogue(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), clang::CodeGen::CodeGenFunction::emitByrefStructureInit(), EmitCXXNewAllocSize(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CGOpenMPRuntime::emitDeclareSimdFunction(), clang::CodeGen::CodeGenFunction::EmitDeleteCall(), EmitISOVolatileLoad(), EmitISOVolatileStore(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), emitNonZeroVLAInit(), emitRoundPointerUpToAlignment(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), EvaluateComparisonBinaryOperator(), clang::Sema::FillInlineAsmIdentifierInfo(), clang::Sema::FinalizeDeclaration(), clang::CodeGen::CodeGenFunction::ParamValue::forIndirect(), clang::CodeGen::CodeGenModule::generateIntelFPGAAnnotation(), clang::CodeGen::CodeGenTBAA::getAccessInfo(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCString(), clang::CodeGen::RValue::getAggregate(), clang::CodeGen::CodeGenFunction::getBlockByrefInfo(), getConstantArrayInfoInChars(), llvm::DenseMapInfo< clang::CharUnits >::getHashValue(), clang::CodeGen::swiftcall::getNaturalAlignment(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), getOffsetAtStartOfUnit(), clang::CodeGen::CGOpenCLRuntime::getPipeElemAlign(), clang::CodeGen::CGOpenCLRuntime::getPipeElemSize(), clang::CodeGen::CGBuilderTy::getSize(), clang::CodeGen::CodeGenModule::getSize(), clang::analyze_os_log::OSLogBufferItem::getSizeByte(), HandleOperatorNewCall(), initializeForBlockHeader(), clang::CodeGen::SwiftABIInfo::isLegalVectorTypeForSwift(), clang::CodeGen::CGBlockInfo::Capture::makeIndex(), clang::CodeGen::CGBitFieldInfo::print(), clang::APValue::printPretty(), clang::CodeGen::BlockByrefHelpers::Profile(), clang::CodeGen::CodeGenModule::Release(), scaleValue(), clang::CodeGen::LValue::setAddress(), clang::CodeGen::LValue::setAlignment(), clang::CodeGen::CGFunctionInfo::setArgStruct(), clang::CodeGen::ABIArgInfo::setIndirectAlign(), setUsedBits(), clang::ASTContext::toBits(), and clang::ento::ExprEngine::VisitUnaryExprOrTypeTraitExpr().
isMultipleOf()
bool clang::CharUnits::isMultipleOf (CharUnits N) const inline
Test whether this is a multiple of the other value.
Among other things, this promises that self.alignTo(N) will just return self.
Definition at line 137 of file CharUnits.h.
isNegative()
bool clang::CharUnits::isNegative () const inline
isNegative - Test whether the quantity is less than zero.
Definition at line 125 of file CharUnits.h.
Referenced by EmitNullBaseClassInitialization(), and evenFlexibleArraySize().
isOne()
bool clang::CharUnits::isOne () const inline
isOne - Test whether the quantity equals one.
Definition at line 119 of file CharUnits.h.
Referenced by clang::Sema::CheckCastAlign(), EmitCXXNewAllocSize(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), clang::Sema::RefersToMemberWithReducedAlignment(), and clang::CodeGen::EHCleanupScope::setActiveFlag().
isPositive()
bool clang::CharUnits::isPositive () const inline
isPositive - Test whether the quantity is greater than zero.
Definition at line 122 of file CharUnits.h.
Referenced by clang::ASTContext::getObjCEncodingTypeSize().
isPowerOfTwo()
bool clang::CharUnits::isPowerOfTwo () const inline
isPowerOfTwo - Test whether the quantity is a power of two.
Zero is not a power of two.
Definition at line 129 of file CharUnits.h.
Referenced by clang::CodeGen::AddressImpl< T, true >::AddressImpl().
isZero()
bool clang::CharUnits::isZero () const inline
isZero - Test whether the quantity equals zero.
Definition at line 116 of file CharUnits.h.
Referenced by clang::CodeGen::AddressImpl< T, true >::AddressImpl(), ApplyNonVirtualAndVirtualOffset(), clang::ento::StoreManager::castRegion(), castValueToType(), clang::Sema::CheckSubtractionOperands(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrong(), clang::CodeGen::CodeGenFunction::EmitDeleteCall(), EmitNullBaseClassInitialization(), EmitNullConstant(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), clang::CodeGen::CodeGenFunction::EmitVTableAssumptionLoad(), EvaluateBuiltinConstantPForLValue(), evenFlexibleArraySize(), clang::CodeGen::CodeGenFunction::ParamValue::forIndirect(), clang::CodeGen::CodeGenFunction::GetAddressOfBaseClass(), GetAddrOfVTTVTable(), clang::CodeGen::CodeGenFunction::InitializeVTablePointer(), clang::CodeGen::CodeGenFunction::LoadCXXThisAddress(), and clang::CodeGen::CGOpenMPRuntime::registerTargetGlobalVariable().
One()
static CharUnits clang::CharUnits::One () inline static
One - Construct a CharUnits quantity of one.
Definition at line 58 of file CharUnits.h.
References CharUnits().
Referenced by clang::CodeGen::CodeGenFunction::createCleanupActiveFlag(), clang::CodeGen::CGBuilderTy::CreateFlagStore(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), EmitBitTestIntrinsic(), clang::CodeGen::CodeGenFunction::EmitConditionalOperatorLValue(), emitTlsGuardCheck(), clang::CodeGen::swiftcall::SwiftAggLowering::finish(), clang::CodeGen::CodeGenModule::getClassPointerAlignment(), clang::CodeGen::CodeGenModule::getMinimumClassObjectSize(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), and SetupCleanupBlockActivation().
operator!=()
bool clang::CharUnits::operator!= (const CharUnits & Other) const inline
Definition at line 95 of file CharUnits.h.
operator%() [1/2]
QuantityType clang::CharUnits::operator% (const CharUnits & Other) const inline
Definition at line 162 of file CharUnits.h.
operator%() [2/2]
CharUnits clang::CharUnits::operator% (QuantityType N) const inline
Definition at line 159 of file CharUnits.h.
References CharUnits().
operator*()
CharUnits clang::CharUnits::operator* (QuantityType N) const inline
Definition at line 142 of file CharUnits.h.
References CharUnits().
operator*=()
CharUnits& clang::CharUnits::operator*= (QuantityType N) inline
Definition at line 145 of file CharUnits.h.
operator+()
CharUnits clang::CharUnits::operator+ (const CharUnits & Other) const inline
Definition at line 165 of file CharUnits.h.
References CharUnits().
operator++() [1/2]
CharUnits& clang::CharUnits::operator++ () inline
Definition at line 72 of file CharUnits.h.
operator++() [2/2]
CharUnits clang::CharUnits::operator++ (int) inline
Definition at line 76 of file CharUnits.h.
References CharUnits().
operator+=()
CharUnits& clang::CharUnits::operator+= (const CharUnits & Other) inline
Definition at line 68 of file CharUnits.h.
operator-() [1/2]
CharUnits clang::CharUnits::operator- () const inline
Definition at line 171 of file CharUnits.h.
References CharUnits().
operator-() [2/2]
CharUnits clang::CharUnits::operator- (const CharUnits & Other) const inline
Definition at line 168 of file CharUnits.h.
References CharUnits().
operator--() [1/2]
CharUnits& clang::CharUnits::operator-- () inline
Definition at line 83 of file CharUnits.h.
operator--() [2/2]
CharUnits clang::CharUnits::operator-- (int) inline
Definition at line 87 of file CharUnits.h.
References CharUnits().
operator-=()
CharUnits& clang::CharUnits::operator-= (const CharUnits & Other) inline
Definition at line 79 of file CharUnits.h.
operator/() [1/2]
QuantityType clang::CharUnits::operator/ (const CharUnits & Other) const inline
Definition at line 156 of file CharUnits.h.
operator/() [2/2]
CharUnits clang::CharUnits::operator/ (QuantityType N) const inline
Definition at line 149 of file CharUnits.h.
References CharUnits().
operator/=()
CharUnits& clang::CharUnits::operator/= (QuantityType N) inline
Definition at line 152 of file CharUnits.h.
operator<()
bool clang::CharUnits::operator< (const CharUnits & Other) const inline
Definition at line 100 of file CharUnits.h.
operator<=()
bool clang::CharUnits::operator<= (const CharUnits & Other) const inline
Definition at line 103 of file CharUnits.h.
operator==()
bool clang::CharUnits::operator== (const CharUnits & Other) const inline
Definition at line 92 of file CharUnits.h.
operator>()
bool clang::CharUnits::operator> (const CharUnits & Other) const inline
Definition at line 106 of file CharUnits.h.
operator>=()
bool clang::CharUnits::operator>= (const CharUnits & Other) const inline
Definition at line 109 of file CharUnits.h.
Zero()
static CharUnits clang::CharUnits::Zero () inline static
Zero - Construct a CharUnits quantity of zero.
Definition at line 53 of file CharUnits.h.
References CharUnits().
Referenced by clang::CodeGen::swiftcall::SwiftAggLowering::addTypedData(), BuildAppleKextVirtualCall(), CalculateCookiePadding(), classifyType(), computeBlockInfo(), clang::CodeGen::CodeGenModule::computeNonVirtualBaseClassOffset(), clang::CodeGen::CodeGenFunction::defaultInitNonTrivialCStructVar(), DiagnoseReinterpretUpDownCast(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), clang::CodeGen::CodeGenFunction::EmitMemberExpr(), EmitNullBaseClassInitialization(), clang::SourceLocExpr::EvaluateInContext(), getAlignmentAndOffsetFromBinAddOrSub(), clang::CodeGen::CGCXXABI::GetArrayCookieSize(), clang::CodeGen::CGCXXABI::getArrayCookieSizeImpl(), getBaseAlignmentAndOffsetFromLValue(), getBaseAlignmentAndOffsetFromPtr(), clang::CodeGen::swiftcall::SwiftAggLowering::getCoerceAndExpandTypes(), getDerivedToBaseAlignmentAndOffset(), clang::ASTContext::getMemberPointerPathAdjustment(), GetNumNonZeroBytesInInit(), clang::ASTContext::getObjCEncodingTypeSize(), clang::ASTContext::getOffsetOfBaseWithVBPtr(), getOffsetOfFullPath(), getTypeExpansion(), clang::CodeGen::CGCXXABI::getVirtualFunctionPrologueThisAdjustment(), clang::CodeGen::CodeGenFunction::getVTablePointers(), clang::CodeGen::CodeGenFunction::InitializeVTablePointer(), clang::CodeGen::CGCXXABI::ReadArrayCookie(), clang::CodeGen::CGOpenMPRuntime::registerTargetGlobalVariable(), selectBestPath(), clang::interp::Pointer::toAPValue(), and clang::VTTBuilder::VTTBuilder().
The documentation for this class was generated from the following file:
include/clang/AST/CharUnits.h