clang: clang::SemaOpenMP Class Reference
clang::SemaOpenMP Class Reference
#include "clang/Sema/SemaOpenMP.h"
Classes
struct DeclareTargetContextInfo
struct OMPIteratorData
Data structure for iterator expression.
struct OpenMPVarListDataTy
Data used for processing a list of variables in OpenMP clauses.
struct UsesAllocatorsData
Data for list of allocators.
Public Types
using DeclGroupPtrTy = OpaquePtr< DeclGroupRef >
using CapturedParamNameType = std::pair< StringRef, QualType >
using VarsWithInheritedDSAType = llvm::SmallDenseMap< const ValueDecl *, const Expr *, 4 >
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Member Functions
SemaOpenMP (Sema &S)
SemaDiagnosticBuilder diagIfOpenMPDeviceCode (SourceLocation Loc, unsigned DiagID, const FunctionDecl *FD)
Creates a SemaDiagnosticBuilder that emits the diagnostic if the current context is "used as device code".
SemaDiagnosticBuilder diagIfOpenMPHostCode (SourceLocation Loc, unsigned DiagID, const FunctionDecl *FD)
Creates a SemaDiagnosticBuilder that emits the diagnostic if the current context is "used as host code".
void ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope (Scope *S, Declarator &D, MultiTemplateParamsArg TemplateParameterLists, SmallVectorImpl< FunctionDecl * > &Bases)
The declarator D defines a function in the scope S which is nested in an omp begin/end declare variant scope.
void ActOnFinishedFunctionDefinitionInOpenMPDeclareVariantScope (Decl *D, SmallVectorImpl< FunctionDecl * > &Bases)
Register D as specialization of all base functions in Bases in the current omp begin/end declare variant scope.
void ActOnFinishedFunctionDefinitionInOpenMPAssumeScope (Decl *D)
Act on D, a function definition inside of an omp [begin/end] assumes.
bool isInOpenMPDeclareVariantScope () const
Can we exit an OpenMP declare variant scope at the moment.
ExprResult VerifyPositiveIntegerConstantInClause (Expr *Op, OpenMPClauseKind CKind, bool StrictlyPositive=true, bool SuppressExprDiags=false)
ExprResult ActOnOpenMPCall (ExprResult Call, Scope *Scope, SourceLocation LParenLoc, MultiExprArg ArgExprs, SourceLocation RParenLoc, Expr *ExecConfig)
Given the potential call expression Call, determine if there is a specialization via the OpenMP declare variant mechanism available.
void ActOnOpenMPBeginDeclareVariant (SourceLocation Loc, OMPTraitInfo &TI)
Handle a omp begin declare variant.
void ActOnOpenMPEndDeclareVariant ()
Handle a omp end declare variant.
void tryCaptureOpenMPLambdas (ValueDecl *V)
Function tries to capture lambda's captured variables in the OpenMP region before the original lambda is captured.
bool isOpenMPCapturedByRef (const ValueDecl *D, unsigned Level, unsigned OpenMPCaptureLevel) const
Return true if the provided declaration VD should be captured by reference.
VarDecl * isOpenMPCapturedDecl (ValueDecl *D, bool CheckScopeInfo=false, unsigned StopAt=0)
Check if the specified variable is used in one of the private clauses (private, firstprivate, lastprivate, reduction etc.) in OpenMP constructs.
bool isOpenMPRebuildMemberExpr (ValueDecl *D)
The member expression(this->fd) needs to be rebuilt in the template instantiation to generate private copy for OpenMP when default clause is used.
ExprResult getOpenMPCapturedExpr (VarDecl *Capture, ExprValueKind VK, ExprObjectKind OK, SourceLocation Loc)
void startOpenMPLoop ()
If the current region is a loop-based region, mark the start of the loop construct.
void startOpenMPCXXRangeFor ()
If the current region is a range loop-based region, mark the start of the loop construct.
OpenMPClauseKind isOpenMPPrivateDecl (ValueDecl *D, unsigned Level, unsigned CapLevel) const
Check if the specified variable is used in 'private' clause.
void setOpenMPCaptureKind (FieldDecl *FD, const ValueDecl *D, unsigned Level)
Sets OpenMP capture kind (OMPC_private, OMPC_firstprivate, OMPC_map etc.) for FD based on DSA for the provided corresponding captured declaration D.
bool isOpenMPTargetCapturedDecl (const ValueDecl *D, unsigned Level, unsigned CaptureLevel) const
Check if the specified variable is captured by 'target' directive.
bool isOpenMPGlobalCapturedDecl (ValueDecl *D, unsigned Level, unsigned CaptureLevel) const
Check if the specified global variable must be captured by outer capture regions.
ExprResult PerformOpenMPImplicitIntegerConversion (SourceLocation OpLoc, Expr *Op)
void StartOpenMPDSABlock (OpenMPDirectiveKind K, const DeclarationNameInfo &DirName, Scope *CurScope, SourceLocation Loc)
Called on start of new data sharing attribute block.
void StartOpenMPClause (OpenMPClauseKind K)
Start analysis of clauses.
void EndOpenMPClause ()
End analysis of clauses.
void EndOpenMPDSABlock (Stmt *CurDirective)
Called on end of data sharing attribute block.
void ActOnOpenMPLoopInitialization (SourceLocation ForLoc, Stmt *Init)
Check if the current region is an OpenMP loop region and if it is, mark loop control variable, used in Init for loop initialization, as private by default.
StmtResult ActOnOpenMPMetaDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp metadirective' after parsing of the associated statement.
ExprResult ActOnOpenMPIdExpression (Scope *CurScope, CXXScopeSpec &ScopeSpec, const DeclarationNameInfo &Id, OpenMPDirectiveKind Kind)
Called on correct id-expression from the '#pragma omp threadprivate'.
DeclGroupPtrTy ActOnOpenMPThreadprivateDirective (SourceLocation Loc, ArrayRef< Expr * > VarList)
Called on well-formed '#pragma omp threadprivate'.
OMPThreadPrivateDecl * CheckOMPThreadPrivateDecl (SourceLocation Loc, ArrayRef< Expr * > VarList)
Builds a new OpenMPThreadPrivateDecl and checks its correctness.
DeclGroupPtrTy ActOnOpenMPAllocateDirective (SourceLocation Loc, ArrayRef< Expr * > VarList, ArrayRef< OMPClause * > Clauses, DeclContext *Owner=nullptr)
Called on well-formed '#pragma omp allocate'.
void ActOnOpenMPAssumesDirective (SourceLocation Loc, OpenMPDirectiveKind DKind, ArrayRef< std::string > Assumptions, bool SkippedClauses)
Called on well-formed '#pragma omp [begin] assume[s]'.
bool isInOpenMPAssumeScope () const
Check if there is an active global omp begin assumes directive.
bool hasGlobalOpenMPAssumes () const
Check if there is an active global omp assumes directive.
void ActOnOpenMPEndAssumesDirective ()
Called on well-formed '#pragma omp end assumes'.
DeclGroupPtrTy ActOnOpenMPRequiresDirective (SourceLocation Loc, ArrayRef< OMPClause * > ClauseList)
Called on well-formed '#pragma omp requires'.
OMPRequiresDecl * CheckOMPRequiresDecl (SourceLocation Loc, ArrayRef< OMPClause * > Clauses)
Check restrictions on Requires directive.
QualType ActOnOpenMPDeclareReductionType (SourceLocation TyLoc, TypeResult ParsedType)
Check if the specified type is allowed to be used in 'omp declare reduction' construct.
DeclGroupPtrTy ActOnOpenMPDeclareReductionDirectiveStart (Scope *S, DeclContext *DC, DeclarationName Name, ArrayRef< std::pair< QualType, SourceLocation >> ReductionTypes, AccessSpecifier AS, Decl *PrevDeclInScope=nullptr)
Called on start of '#pragma omp declare reduction'.
void ActOnOpenMPDeclareReductionCombinerStart (Scope *S, Decl *D)
Initialize declare reduction construct initializer.
void ActOnOpenMPDeclareReductionCombinerEnd (Decl *D, Expr *Combiner)
Finish current declare reduction construct initializer.
VarDecl * ActOnOpenMPDeclareReductionInitializerStart (Scope *S, Decl *D)
Initialize declare reduction construct initializer.
void ActOnOpenMPDeclareReductionInitializerEnd (Decl *D, Expr *Initializer, VarDecl *OmpPrivParm)
Finish current declare reduction construct initializer.
DeclGroupPtrTy ActOnOpenMPDeclareReductionDirectiveEnd (Scope *S, DeclGroupPtrTy DeclReductions, bool IsValid)
Called at the end of '#pragma omp declare reduction'.
TypeResult ActOnOpenMPDeclareMapperVarDecl (Scope *S, Declarator &D)
Check variable declaration in 'omp declare mapper' construct.
QualType ActOnOpenMPDeclareMapperType (SourceLocation TyLoc, TypeResult ParsedType)
Check if the specified type is allowed to be used in 'omp declare mapper' construct.
DeclGroupPtrTy ActOnOpenMPDeclareMapperDirective (Scope *S, DeclContext *DC, DeclarationName Name, QualType MapperType, SourceLocation StartLoc, DeclarationName VN, AccessSpecifier AS, Expr *MapperVarRef, ArrayRef< OMPClause * > Clauses, Decl *PrevDeclInScope=nullptr)
Called on start of '#pragma omp declare mapper'.
ExprResult ActOnOpenMPDeclareMapperDirectiveVarDecl (Scope *S, QualType MapperType, SourceLocation StartLoc, DeclarationName VN)
Build the mapper variable of '#pragma omp declare mapper'.
void ActOnOpenMPIteratorVarDecl (VarDecl *VD)
bool isOpenMPDeclareMapperVarDeclAllowed (const VarDecl *VD) const
const ValueDecl * getOpenMPDeclareMapperVarName () const
bool ActOnStartOpenMPDeclareTargetContext (DeclareTargetContextInfo &DTCI)
Called on the start of target region i.e. '#pragma omp declare target'.
const DeclareTargetContextInfo ActOnOpenMPEndDeclareTargetDirective ()
Called at the end of target region i.e. '#pragma omp end declare target'.
void ActOnFinishedOpenMPDeclareTargetContext (DeclareTargetContextInfo &DTCI)
Called once a target context is completed, that can be when a '#pragma omp end declare target' was encountered or when a '#pragma omp declare target' without declaration-definition-seq was encountered.
void DiagnoseUnterminatedOpenMPDeclareTarget ()
Report unterminated 'omp declare target' or 'omp begin declare target' at the end of a compilation unit.
NamedDecl * lookupOpenMPDeclareTargetName (Scope *CurScope, CXXScopeSpec &ScopeSpec, const DeclarationNameInfo &Id)
Searches for the provided declaration name for OpenMP declare target directive.
void ActOnOpenMPDeclareTargetName (NamedDecl *ND, SourceLocation Loc, OMPDeclareTargetDeclAttr::MapTypeTy MT, DeclareTargetContextInfo &DTCI)
Called on correct id-expression from the '#pragma omp declare target'.
void checkDeclIsAllowedInOpenMPTarget (Expr *E, Decl *D, SourceLocation IdLoc=SourceLocation())
Check declaration inside target region.
void ActOnOpenMPDeclareTargetInitializer (Decl *D)
Adds OMPDeclareTargetDeclAttr to referenced variables in declare target directive.
void finalizeOpenMPDelayedAnalysis (const FunctionDecl *Caller, const FunctionDecl *Callee, SourceLocation Loc)
Finishes analysis of the deferred functions calls that may be declared as host/nohost during device/host compilation.
bool isInOpenMPTaskUntiedContext () const
Return true if currently in OpenMP task with untied clause context.
bool isInOpenMPDeclareTargetContext () const
Return true inside OpenMP declare target region.
bool isInOpenMPTargetExecutionDirective () const
Return true inside OpenMP target region.
void ActOnOpenMPRegionStart (OpenMPDirectiveKind DKind, Scope *CurScope)
Initialization of captured region for OpenMP region.
StmtResult ActOnOpenMPCanonicalLoop (Stmt *AStmt)
Called for syntactical loops (ForStmt or CXXForRangeStmt) associated to an OpenMP loop directive.
StmtResult ActOnOpenMPLoopnest (Stmt *AStmt)
Process a canonical OpenMP loop nest that can either be a canonical literal loop (ForStmt or CXXForRangeStmt), or the generated loop of an OpenMP loop transformation construct.
StmtResult ActOnOpenMPRegionEnd (StmtResult S, ArrayRef< OMPClause * > Clauses)
End of OpenMP region.
StmtResult ActOnOpenMPExecutableDirective (OpenMPDirectiveKind Kind, const DeclarationNameInfo &DirName, OpenMPDirectiveKind CancelRegion, ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, OpenMPDirectiveKind PrevMappedDirective=llvm::omp::OMPD_unknown)
StmtResult ActOnOpenMPParallelDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp parallel' after parsing of the associated statement.
StmtResult ActOnOpenMPSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp simd' after parsing of the associated statement.
StmtResult ActOnOpenMPTileDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp tile' after parsing of its clauses and the associated statement.
StmtResult ActOnOpenMPUnrollDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp unroll' after parsing of its clauses and the associated statement.
StmtResult ActOnOpenMPForDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp for' after parsing of the associated statement.
StmtResult ActOnOpenMPForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp for simd' after parsing of the associated statement.
StmtResult ActOnOpenMPSectionsDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp sections' after parsing of the associated statement.
StmtResult ActOnOpenMPSectionDirective (Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp section' after parsing of the associated statement.
StmtResult ActOnOpenMPScopeDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp scope' after parsing of the associated statement.
StmtResult ActOnOpenMPSingleDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp single' after parsing of the associated statement.
StmtResult ActOnOpenMPMasterDirective (Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp master' after parsing of the associated statement.
StmtResult ActOnOpenMPCriticalDirective (const DeclarationNameInfo &DirName, ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp critical' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel for' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel for simd' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelMasterDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp parallel master' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelMaskedDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp parallel masked' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelSectionsDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp parallel sections' after parsing of the associated statement.
StmtResult ActOnOpenMPTaskDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp task' after parsing of the associated statement.
StmtResult ActOnOpenMPTaskyieldDirective (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp taskyield'.
StmtResult ActOnOpenMPErrorDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, bool InExContext=true)
Called on well-formed '#pragma omp error'.
StmtResult ActOnOpenMPBarrierDirective (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp barrier'.
StmtResult ActOnOpenMPTaskwaitDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp taskwait'.
StmtResult ActOnOpenMPTaskgroupDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp taskgroup'.
StmtResult ActOnOpenMPFlushDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp flush'.
StmtResult ActOnOpenMPDepobjDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp depobj'.
StmtResult ActOnOpenMPScanDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp scan'.
StmtResult ActOnOpenMPOrderedDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp ordered' after parsing of the associated statement.
StmtResult ActOnOpenMPAtomicDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp atomic' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp target' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetDataDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp target data' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetEnterDataDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, Stmt *AStmt)
Called on well-formed '#pragma omp target enter data' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetExitDataDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, Stmt *AStmt)
Called on well-formed '#pragma omp target exit data' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetParallelDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp target parallel' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target parallel for' after parsing of the associated statement.
StmtResult ActOnOpenMPTeamsDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp teams' after parsing of the associated statement.
StmtResult ActOnOpenMPTeamsGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams loop' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetTeamsGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams loop' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel loop' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetParallelGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target parallel loop' after parsing of the associated statement.
StmtResult ActOnOpenMPCancellationPointDirective (SourceLocation StartLoc, SourceLocation EndLoc, OpenMPDirectiveKind CancelRegion)
Called on well-formed '#pragma omp cancellation point'.
StmtResult ActOnOpenMPCancelDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, OpenMPDirectiveKind CancelRegion)
Called on well-formed '#pragma omp cancel'.
StmtResult ActOnOpenMPTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp taskloop' after parsing of the associated statement.
StmtResult ActOnOpenMPTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp taskloop simd' after parsing of the associated statement.
StmtResult ActOnOpenMPMasterTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp master taskloop' after parsing of the associated statement.
StmtResult ActOnOpenMPMasterTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp master taskloop simd' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelMasterTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel master taskloop' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelMasterTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel master taskloop simd' after parsing of the associated statement.
StmtResult ActOnOpenMPMaskedTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp masked taskloop' after parsing of the associated statement.
StmtResult ActOnOpenMPMaskedTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp masked taskloop simd' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelMaskedTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel masked taskloop' after parsing of the associated statement.
StmtResult ActOnOpenMPParallelMaskedTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel masked taskloop simd' after parsing of the associated statement.
StmtResult ActOnOpenMPDistributeDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp distribute' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetUpdateDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, Stmt *AStmt)
Called on well-formed '#pragma omp target update'.
StmtResult ActOnOpenMPDistributeParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp distribute parallel for' after parsing of the associated statement.
StmtResult ActOnOpenMPDistributeParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp distribute parallel for simd' after parsing of the associated statement.
StmtResult ActOnOpenMPDistributeSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp distribute simd' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target parallel for simd' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target simd' after parsing of the associated statement.
StmtResult ActOnOpenMPTeamsDistributeDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams distribute' after parsing of the associated statement.
StmtResult ActOnOpenMPTeamsDistributeSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams distribute simd' after parsing of the associated statement.
StmtResult ActOnOpenMPTeamsDistributeParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams distribute parallel for simd' after parsing of the associated statement.
StmtResult ActOnOpenMPTeamsDistributeParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams distribute parallel for' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetTeamsDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp target teams' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetTeamsDistributeDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams distribute' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetTeamsDistributeParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams distribute parallel for' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams distribute parallel for simd' after parsing of the associated statement.
StmtResult ActOnOpenMPTargetTeamsDistributeSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams distribute simd' after parsing of the associated statement.
StmtResult ActOnOpenMPInteropDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp interop'.
StmtResult ActOnOpenMPDispatchDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp dispatch' after parsing of the.
StmtResult ActOnOpenMPMaskedDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp masked' after parsing of the.
StmtResult ActOnOpenMPGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt *AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType &VarsWithImplicitDSA)
Called on well-formed '#pragma omp loop' after parsing of the associated statement.
bool CheckOpenMPLinearModifier (OpenMPLinearClauseKind LinKind, SourceLocation LinLoc)
Checks correctness of linear modifiers.
bool CheckOpenMPLinearDecl (const ValueDecl *D, SourceLocation ELoc, OpenMPLinearClauseKind LinKind, QualType Type, bool IsDeclareSimd=false)
Checks that the specified declaration matches requirements for the linear decls.
DeclGroupPtrTy ActOnOpenMPDeclareSimdDirective (DeclGroupPtrTy DG, OMPDeclareSimdDeclAttr::BranchStateTy BS, Expr *Simdlen, ArrayRef< Expr * > Uniforms, ArrayRef< Expr * > Aligneds, ArrayRef< Expr * > Alignments, ArrayRef< Expr * > Linears, ArrayRef< unsigned > LinModifiers, ArrayRef< Expr * > Steps, SourceRange SR)
Called on well-formed '#pragma omp declare simd' after parsing of the associated method/function.
std::optional< std::pair< FunctionDecl *, Expr * > > checkOpenMPDeclareVariantFunction (DeclGroupPtrTy DG, Expr *VariantRef, OMPTraitInfo &TI, unsigned NumAppendArgs, SourceRange SR)
Checks '#pragma omp declare variant' variant function and original functions after parsing of the associated method/function.
void ActOnOpenMPDeclareVariantDirective (FunctionDecl *FD, Expr *VariantRef, OMPTraitInfo &TI, ArrayRef< Expr * > AdjustArgsNothing, ArrayRef< Expr * > AdjustArgsNeedDevicePtr, ArrayRef< OMPInteropInfo > AppendArgs, SourceLocation AdjustArgsLoc, SourceLocation AppendArgsLoc, SourceRange SR)
Called on well-formed '#pragma omp declare variant' after parsing of the associated method/function.
OMPClause * ActOnOpenMPSingleExprClause (OpenMPClauseKind Kind, Expr *Expr, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
OMPClause * ActOnOpenMPAllocatorClause (Expr *Allocator, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'allocator' clause.
OMPClause * ActOnOpenMPIfClause (OpenMPDirectiveKind NameModifier, Expr *Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation NameModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Called on well-formed 'if' clause.
OMPClause * ActOnOpenMPFinalClause (Expr *Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'final' clause.
OMPClause * ActOnOpenMPNumThreadsClause (Expr *NumThreads, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'num_threads' clause.
OMPClause * ActOnOpenMPAlignClause (Expr *Alignment, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'align' clause.
OMPClause * ActOnOpenMPSafelenClause (Expr *Length, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'safelen' clause.
OMPClause * ActOnOpenMPSimdlenClause (Expr *Length, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'simdlen' clause.
OMPClause * ActOnOpenMPSizesClause (ArrayRef< Expr * > SizeExprs, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-form 'sizes' clause.
OMPClause * ActOnOpenMPFullClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-form 'full' clauses.
OMPClause * ActOnOpenMPPartialClause (Expr *FactorExpr, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-form 'partial' clauses.
OMPClause * ActOnOpenMPCollapseClause (Expr *NumForLoops, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'collapse' clause.
OMPClause * ActOnOpenMPOrderedClause (SourceLocation StartLoc, SourceLocation EndLoc, SourceLocation LParenLoc=SourceLocation(), Expr *NumForLoops=nullptr)
Called on well-formed 'ordered' clause.
OMPClause * ActOnOpenMPGrainsizeClause (OpenMPGrainsizeClauseModifier Modifier, Expr *Size, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Called on well-formed 'grainsize' clause.
OMPClause * ActOnOpenMPNumTasksClause (OpenMPNumTasksClauseModifier Modifier, Expr *NumTasks, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Called on well-formed 'num_tasks' clause.
OMPClause * ActOnOpenMPHintClause (Expr *Hint, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'hint' clause.
OMPClause * ActOnOpenMPDetachClause (Expr *Evt, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'detach' clause.
OMPClause * ActOnOpenMPSimpleClause (OpenMPClauseKind Kind, unsigned Argument, SourceLocation ArgumentLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
OMPClause * ActOnOpenMPWhenClause (OMPTraitInfo &TI, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'when' clause.
OMPClause * ActOnOpenMPDefaultClause (llvm::omp::DefaultKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'default' clause.
OMPClause * ActOnOpenMPProcBindClause (llvm::omp::ProcBindKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'proc_bind' clause.
OMPClause * ActOnOpenMPOrderClause (OpenMPOrderClauseModifier Modifier, OpenMPOrderClauseKind Kind, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation MLoc, SourceLocation KindLoc, SourceLocation EndLoc)
Called on well-formed 'order' clause.
OMPClause * ActOnOpenMPUpdateClause (OpenMPDependClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'update' clause.
OMPClause * ActOnOpenMPSingleExprWithArgClause (OpenMPClauseKind Kind, ArrayRef< unsigned > Arguments, Expr *Expr, SourceLocation StartLoc, SourceLocation LParenLoc, ArrayRef< SourceLocation > ArgumentsLoc, SourceLocation DelimLoc, SourceLocation EndLoc)
OMPClause * ActOnOpenMPScheduleClause (OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2, OpenMPScheduleClauseKind Kind, Expr *ChunkSize, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation M1Loc, SourceLocation M2Loc, SourceLocation KindLoc, SourceLocation CommaLoc, SourceLocation EndLoc)
Called on well-formed 'schedule' clause.
OMPClause * ActOnOpenMPClause (OpenMPClauseKind Kind, SourceLocation StartLoc, SourceLocation EndLoc)
OMPClause * ActOnOpenMPNowaitClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'nowait' clause.
OMPClause * ActOnOpenMPUntiedClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'untied' clause.
OMPClause * ActOnOpenMPMergeableClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'mergeable' clause.
OMPClause * ActOnOpenMPReadClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'read' clause.
OMPClause * ActOnOpenMPWriteClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'write' clause.
OMPClause * ActOnOpenMPUpdateClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'update' clause.
OMPClause * ActOnOpenMPCaptureClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'capture' clause.
OMPClause * ActOnOpenMPCompareClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'compare' clause.
OMPClause * ActOnOpenMPFailClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'fail' clause.
OMPClause * ActOnOpenMPFailClause (OpenMPClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
OMPClause * ActOnOpenMPSeqCstClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'seq_cst' clause.
OMPClause * ActOnOpenMPAcqRelClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'acq_rel' clause.
OMPClause * ActOnOpenMPAcquireClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'acquire' clause.
OMPClause * ActOnOpenMPReleaseClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'release' clause.
OMPClause * ActOnOpenMPRelaxedClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'relaxed' clause.
OMPClause * ActOnOpenMPWeakClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'weak' clause.
OMPClause * ActOnOpenMPInitClause (Expr *InteropVar, OMPInteropInfo &InteropInfo, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Called on well-formed 'init' clause.
OMPClause * ActOnOpenMPUseClause (Expr *InteropVar, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Called on well-formed 'use' clause.
OMPClause * ActOnOpenMPDestroyClause (Expr *InteropVar, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Called on well-formed 'destroy' clause.
OMPClause * ActOnOpenMPNovariantsClause (Expr *Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'novariants' clause.
OMPClause * ActOnOpenMPNocontextClause (Expr *Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'nocontext' clause.
OMPClause * ActOnOpenMPFilterClause (Expr *ThreadID, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'filter' clause.
OMPClause * ActOnOpenMPThreadsClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'threads' clause.
OMPClause * ActOnOpenMPSIMDClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'simd' clause.
OMPClause * ActOnOpenMPNogroupClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'nogroup' clause.
OMPClause * ActOnOpenMPUnifiedAddressClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'unified_address' clause.
OMPClause * ActOnOpenMPUnifiedSharedMemoryClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'unified_address' clause.
OMPClause * ActOnOpenMPReverseOffloadClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'reverse_offload' clause.
OMPClause * ActOnOpenMPDynamicAllocatorsClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'dynamic_allocators' clause.
OMPClause * ActOnOpenMPAtomicDefaultMemOrderClause (OpenMPAtomicDefaultMemOrderClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'atomic_default_mem_order' clause.
OMPClause * ActOnOpenMPAtClause (OpenMPAtClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'at' clause.
OMPClause * ActOnOpenMPSeverityClause (OpenMPSeverityClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'severity' clause.
OMPClause * ActOnOpenMPMessageClause (Expr *MS, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'message' clause.
OMPClause * ActOnOpenMPVarListClause (OpenMPClauseKind Kind, ArrayRef< Expr * > Vars, const OMPVarListLocTy &Locs, OpenMPVarListDataTy &Data)
OMPClause * ActOnOpenMPInclusiveClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'inclusive' clause.
OMPClause * ActOnOpenMPExclusiveClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'exclusive' clause.
OMPClause * ActOnOpenMPAllocateClause (Expr *Allocator, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation ColonLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'allocate' clause.
OMPClause * ActOnOpenMPPrivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'private' clause.
OMPClause * ActOnOpenMPFirstprivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'firstprivate' clause.
OMPClause * ActOnOpenMPLastprivateClause (ArrayRef< Expr * > VarList, OpenMPLastprivateModifier LPKind, SourceLocation LPKindLoc, SourceLocation ColonLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'lastprivate' clause.
OMPClause * ActOnOpenMPSharedClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'shared' clause.
OMPClause * ActOnOpenMPReductionClause (ArrayRef< Expr * > VarList, OpenMPReductionClauseModifier Modifier, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec &ReductionIdScopeSpec, const DeclarationNameInfo &ReductionId, ArrayRef< Expr * > UnresolvedReductions=std::nullopt)
Called on well-formed 'reduction' clause.
OMPClause * ActOnOpenMPTaskReductionClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec &ReductionIdScopeSpec, const DeclarationNameInfo &ReductionId, ArrayRef< Expr * > UnresolvedReductions=std::nullopt)
Called on well-formed 'task_reduction' clause.
OMPClause * ActOnOpenMPInReductionClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec &ReductionIdScopeSpec, const DeclarationNameInfo &ReductionId, ArrayRef< Expr * > UnresolvedReductions=std::nullopt)
Called on well-formed 'in_reduction' clause.
OMPClause * ActOnOpenMPLinearClause (ArrayRef< Expr * > VarList, Expr *Step, SourceLocation StartLoc, SourceLocation LParenLoc, OpenMPLinearClauseKind LinKind, SourceLocation LinLoc, SourceLocation ColonLoc, SourceLocation StepModifierLoc, SourceLocation EndLoc)
Called on well-formed 'linear' clause.
OMPClause * ActOnOpenMPAlignedClause (ArrayRef< Expr * > VarList, Expr *Alignment, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Called on well-formed 'aligned' clause.
OMPClause * ActOnOpenMPCopyinClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'copyin' clause.
OMPClause * ActOnOpenMPCopyprivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'copyprivate' clause.
OMPClause * ActOnOpenMPFlushClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'flush' pseudo clause.
OMPClause * ActOnOpenMPDepobjClause (Expr *Depobj, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'depobj' pseudo clause.
OMPClause * ActOnOpenMPDependClause (const OMPDependClause::DependDataTy &Data, Expr *DepModifier, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'depend' clause.
OMPClause * ActOnOpenMPDeviceClause (OpenMPDeviceClauseModifier Modifier, Expr *Device, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Called on well-formed 'device' clause.
OMPClause * ActOnOpenMPMapClause (Expr *IteratorModifier, ArrayRef< OpenMPMapModifierKind > MapTypeModifiers, ArrayRef< SourceLocation > MapTypeModifiersLoc, CXXScopeSpec &MapperIdScopeSpec, DeclarationNameInfo &MapperId, OpenMPMapClauseKind MapType, bool IsMapTypeImplicit, SourceLocation MapLoc, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs, bool NoDiagnose=false, ArrayRef< Expr * > UnresolvedMappers=std::nullopt)
Called on well-formed 'map' clause.
OMPClause * ActOnOpenMPNumTeamsClause (Expr *NumTeams, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'num_teams' clause.
OMPClause * ActOnOpenMPThreadLimitClause (Expr *ThreadLimit, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'thread_limit' clause.
OMPClause * ActOnOpenMPPriorityClause (Expr *Priority, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'priority' clause.
OMPClause * ActOnOpenMPDistScheduleClause (OpenMPDistScheduleClauseKind Kind, Expr *ChunkSize, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation KindLoc, SourceLocation CommaLoc, SourceLocation EndLoc)
Called on well-formed 'dist_schedule' clause.
OMPClause * ActOnOpenMPDefaultmapClause (OpenMPDefaultmapClauseModifier M, OpenMPDefaultmapClauseKind Kind, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation MLoc, SourceLocation KindLoc, SourceLocation EndLoc)
Called on well-formed 'defaultmap' clause.
OMPClause * ActOnOpenMPToClause (ArrayRef< OpenMPMotionModifierKind > MotionModifiers, ArrayRef< SourceLocation > MotionModifiersLoc, CXXScopeSpec &MapperIdScopeSpec, DeclarationNameInfo &MapperId, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs, ArrayRef< Expr * > UnresolvedMappers=std::nullopt)
Called on well-formed 'to' clause.
OMPClause * ActOnOpenMPFromClause (ArrayRef< OpenMPMotionModifierKind > MotionModifiers, ArrayRef< SourceLocation > MotionModifiersLoc, CXXScopeSpec &MapperIdScopeSpec, DeclarationNameInfo &MapperId, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs, ArrayRef< Expr * > UnresolvedMappers=std::nullopt)
Called on well-formed 'from' clause.
OMPClause * ActOnOpenMPUseDevicePtrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs)
Called on well-formed 'use_device_ptr' clause.
OMPClause * ActOnOpenMPUseDeviceAddrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs)
Called on well-formed 'use_device_addr' clause.
OMPClause * ActOnOpenMPIsDevicePtrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs)
Called on well-formed 'is_device_ptr' clause.
OMPClause * ActOnOpenMPHasDeviceAddrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy &Locs)
Called on well-formed 'has_device_addr' clause.
OMPClause * ActOnOpenMPNontemporalClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'nontemporal' clause.
OMPClause * ActOnOpenMPUsesAllocatorClause (SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< UsesAllocatorsData > Data)
Called on well-formed 'uses_allocators' clause.
OMPClause * ActOnOpenMPAffinityClause (SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, Expr *Modifier, ArrayRef< Expr * > Locators)
Called on well-formed 'affinity' clause.
OMPClause * ActOnOpenMPBindClause (OpenMPBindClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on a well-formed 'bind' clause.
OMPClause * ActOnOpenMPXDynCGroupMemClause (Expr *Size, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on a well-formed 'ompx_dyn_cgroup_mem' clause.
OMPClause * ActOnOpenMPDoacrossClause (OpenMPDoacrossClauseModifier DepType, SourceLocation DepLoc, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'doacross' clause.
OMPClause * ActOnOpenMPXAttributeClause (ArrayRef< const Attr * > Attrs, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on a well-formed 'ompx_attribute' clause.
OMPClause * ActOnOpenMPXBareClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on a well-formed 'ompx_bare' clause.
ExprResult ActOnOMPArraySectionExpr (Expr *Base, SourceLocation LBLoc, Expr *LowerBound, SourceLocation ColonLocFirst, SourceLocation ColonLocSecond, Expr *Length, Expr *Stride, SourceLocation RBLoc)
ExprResult ActOnOMPArrayShapingExpr (Expr *Base, SourceLocation LParenLoc, SourceLocation RParenLoc, ArrayRef< Expr * > Dims, ArrayRef< SourceRange > Brackets)
ExprResult ActOnOMPIteratorExpr (Scope *S, SourceLocation IteratorKwLoc, SourceLocation LLoc, SourceLocation RLoc, ArrayRef< OMPIteratorData > Data)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
Static Public Member Functions
static int getOpenMPCaptureLevels (OpenMPDirectiveKind Kind)
Return the number of captured regions created for an OpenMP directive.
Friends
class Parser
class Sema
Additional Inherited Members
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 46 of file SemaOpenMP.h.
Member Typedef Documentation
CapturedParamNameType
using clang::SemaOpenMP::CapturedParamNameType = std::pair<StringRef, QualType>
Definition at line 54 of file SemaOpenMP.h.
DeclGroupPtrTy
using clang::SemaOpenMP::DeclGroupPtrTy = OpaquePtr<DeclGroupRef>
Definition at line 53 of file SemaOpenMP.h.
VarsWithInheritedDSAType
using clang::SemaOpenMP::VarsWithInheritedDSAType = llvm::SmallDenseMap<const ValueDecl *, const Expr *, 4>
Definition at line 407 of file SemaOpenMP.h.
Constructor & Destructor Documentation
SemaOpenMP()
SemaOpenMP::SemaOpenMP (Sema & S)
Definition at line 25192 of file SemaOpenMP.cpp.
Member Function Documentation
ActOnFinishedFunctionDefinitionInOpenMPAssumeScope()
void SemaOpenMP::ActOnFinishedFunctionDefinitionInOpenMPAssumeScope (Decl * D)
Act on D, a function definition inside of an omp [begin/end] assumes.
Definition at line 7370 of file SemaOpenMP.cpp.
References clang::Decl::addAttr(), clang::Sema::inTemplateInstantiation(), clang::Decl::isInvalidDecl(), and clang::SemaBase::SemaRef.
ActOnFinishedFunctionDefinitionInOpenMPDeclareVariantScope()
void SemaOpenMP::ActOnFinishedFunctionDefinitionInOpenMPDeclareVariantScope (Decl * D, SmallVectorImpl< FunctionDecl * > & Bases)
Register D as specialization of all base functions in Bases in the current omp begin/end declare variant scope.
Definition at line 7477 of file SemaOpenMP.cpp.
References clang::DeclRefExpr::Create(), clang::SemaBase::getASTContext(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::SemaBase::SemaRef, clang::Unevaluated, clang::Sema::Unevaluated, and clang::VK_PRValue.
ActOnFinishedOpenMPDeclareTargetContext()
void SemaOpenMP::ActOnFinishedOpenMPDeclareTargetContext (DeclareTargetContextInfo & DTCI)
Called once a target context is completed, that can be when a '#pragma omp end declare target' was encountered or when a '#pragma omp declare target' without declaration-definition-seq was encountered.
Definition at line 23486 of file SemaOpenMP.cpp.
References ActOnOpenMPDeclareTargetName(), and clang::SemaOpenMP::DeclareTargetContextInfo::ExplicitlyMapped.
ActOnOMPArraySectionExpr()
ExprResult SemaOpenMP::ActOnOMPArraySectionExpr (Expr * Base, SourceLocation LBLoc, Expr * LowerBound, SourceLocation ColonLocFirst, SourceLocation ColonLocSecond, Expr * Length, Expr * Stride, SourceLocation RBLoc)
Definition at line 24631 of file SemaOpenMP.cpp.
ActOnOMPArrayShapingExpr()
ExprResult SemaOpenMP::ActOnOMPArrayShapingExpr (Expr * Base, SourceLocation LParenLoc, SourceLocation RParenLoc, ArrayRef< Expr * > Dims, ArrayRef< SourceRange > Brackets)
Definition at line 24817 of file SemaOpenMP.cpp.
ActOnOMPIteratorExpr()
ExprResult SemaOpenMP::ActOnOMPIteratorExpr (Scope * S, SourceLocation IteratorKwLoc, SourceLocation LLoc, SourceLocation RLoc, ArrayRef< OMPIteratorData > Data)
Act on the iterator variable declaration.
Definition at line 24892 of file SemaOpenMP.cpp.
ActOnOpenMPAcqRelClause()
OMPClause * SemaOpenMP::ActOnOpenMPAcqRelClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'acq_rel' clause.
Definition at line 17934 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPAcquireClause()
OMPClause * SemaOpenMP::ActOnOpenMPAcquireClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'acquire' clause.
Definition at line 17939 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPAffinityClause()
OMPClause * SemaOpenMP::ActOnOpenMPAffinityClause (SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, Expr * Modifier, ArrayRef< Expr * > Locators)
Called on well-formed 'affinity' clause.
Definition at line 24498 of file SemaOpenMP.cpp.
References clang::OMPAffinityClause::Create(), clang::Sema::CreateBuiltinUnaryOp(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::Expr::IgnoreParenImpCasts(), clang::Expr::isLValue(), clang::ActionResult< PtrTy, Compress >::isUsable(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPAlignClause()
OMPClause * SemaOpenMP::ActOnOpenMPAlignClause (Expr * Alignment, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'align' clause.
Definition at line 17444 of file SemaOpenMP.cpp.
References clang::OMPAlignClause::Create(), clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), and VerifyPositiveIntegerConstantInClause().
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPAlignedClause()
OMPClause * SemaOpenMP::ActOnOpenMPAlignedClause (ArrayRef< Expr * > VarList, Expr * Alignment, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Called on well-formed 'aligned' clause.
Definition at line 20714 of file SemaOpenMP.cpp.
References buildCapture(), clang::OMPAlignedClause::Create(), clang::VarDecl::DeclarationOnly, clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::QualType::getCanonicalType(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::QualType::getNonReferenceType(), getPrivateItem(), clang::ValueDecl::getType(), clang::QualType::getTypePtrOrNull(), clang::QualType::getUnqualifiedType(), clang::Type::isArrayType(), clang::ActionResult< PtrTy, Compress >::isInvalid(), isOpenMPCapturedDecl(), clang::Type::isPointerType(), clang::SemaBase::SemaRef, and VerifyPositiveIntegerConstantInClause().
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPAllocateClause()
OMPClause * SemaOpenMP::ActOnOpenMPAllocateClause (Expr * Allocator, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation ColonLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'allocate' clause.
Definition at line 24148 of file SemaOpenMP.cpp.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPAllocateDirective()
SemaOpenMP::DeclGroupPtrTy SemaOpenMP::ActOnOpenMPAllocateDirective (SourceLocation Loc, ArrayRef< Expr * > VarList, ArrayRef< OMPClause * > Clauses, DeclContext * Owner = nullptr)
Called on well-formed '#pragma omp allocate'.
Definition at line 3412 of file SemaOpenMP.cpp.
ActOnOpenMPAllocatorClause()
OMPClause * SemaOpenMP::ActOnOpenMPAllocatorClause (Expr * Allocator, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'allocator' clause.
Definition at line 17014 of file SemaOpenMP.cpp.
References DSAStack, findOMPAllocatorHandleT(), clang::Expr::getExprLoc(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPAssumesDirective()
void SemaOpenMP::ActOnOpenMPAssumesDirective (SourceLocation Loc, OpenMPDirectiveKind DKind, ArrayRef< std::string > Assumptions, bool SkippedClauses)
Called on well-formed '#pragma omp [begin] assume[s]'.
Definition at line 3503 of file SemaOpenMP.cpp.
References clang::Sema::CurContext, clang::DeclContext::decls(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::DeclContext::getLexicalParent(), and clang::SemaBase::SemaRef.
ActOnOpenMPAtClause()
OMPClause * SemaOpenMP::ActOnOpenMPAtClause (OpenMPAtClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'at' clause.
Definition at line 17298 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), getListOfPossibleValues(), and clang::OMPC_AT_unknown.
Referenced by ActOnOpenMPSimpleClause().
ActOnOpenMPAtomicDefaultMemOrderClause()
OMPClause * SemaOpenMP::ActOnOpenMPAtomicDefaultMemOrderClause (OpenMPAtomicDefaultMemOrderClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'atomic_default_mem_order' clause.
Definition at line 17283 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), getListOfPossibleValues(), and clang::OMPC_ATOMIC_DEFAULT_MEM_ORDER_unknown.
Referenced by ActOnOpenMPSimpleClause().
ActOnOpenMPAtomicDirective()
StmtResult SemaOpenMP::ActOnOpenMPAtomicDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp atomic' after parsing of the associated statement.
Definition at line 12781 of file SemaOpenMP.cpp.
ActOnOpenMPBarrierDirective()
StmtResult SemaOpenMP::ActOnOpenMPBarrierDirective (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp barrier'.
Definition at line 11449 of file SemaOpenMP.cpp.
References clang::OMPBarrierDirective::Create(), and clang::SemaBase::getASTContext().
ActOnOpenMPBeginDeclareVariant()
void SemaOpenMP::ActOnOpenMPBeginDeclareVariant (SourceLocation Loc, OMPTraitInfo & TI)
Handle a omp begin declare variant.
Definition at line 2716 of file SemaOpenMP.cpp.
ActOnOpenMPBindClause()
OMPClause * SemaOpenMP::ActOnOpenMPBindClause (OpenMPBindClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on a well-formed 'bind' clause.
Definition at line 24537 of file SemaOpenMP.cpp.
References clang::OMPBindClause::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), getListOfPossibleValues(), and clang::OMPC_BIND_unknown.
Referenced by ActOnOpenMPSimpleClause().
ActOnOpenMPCall()
ExprResult SemaOpenMP::ActOnOpenMPCall (ExprResult Call, Scope * Scope, SourceLocation LParenLoc, MultiExprArg ArgExprs, SourceLocation RParenLoc, Expr * ExecConfig)
Given the potential call expression Call, determine if there is a specialization via the OpenMP declare variant mechanism available.
If there is, return the specialized call expression, otherwise return the original Call.
Definition at line 7505 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::CallExpr::getDirectCallee(), clang::NamedDecl::getIdentifier(), clang::SemaBase::getLangOpts(), clang::NamedDecl::getName(), clang::Decl::hasAttr(), and clang::Scope::isOpenMPOrderClauseScope().
Referenced by clang::Sema::ActOnCallExpr().
ActOnOpenMPCancelDirective()
StmtResult SemaOpenMP::ActOnOpenMPCancelDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, OpenMPDirectiveKind CancelRegion)
Called on well-formed '#pragma omp cancel'.
Definition at line 13725 of file SemaOpenMP.cpp.
References clang::OMPCancelDirective::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), and clang::StmtError().
ActOnOpenMPCancellationPointDirective()
StmtResult SemaOpenMP::ActOnOpenMPCancellationPointDirective (SourceLocation StartLoc, SourceLocation EndLoc, OpenMPDirectiveKind CancelRegion)
Called on well-formed '#pragma omp cancellation point'.
Definition at line 13710 of file SemaOpenMP.cpp.
References clang::OMPCancellationPointDirective::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), and clang::StmtError().
ActOnOpenMPCanonicalLoop()
StmtResult SemaOpenMP::ActOnOpenMPCanonicalLoop (Stmt * AStmt)
Called for syntactical loops (ForStmt or CXXForRangeStmt) associated to an OpenMP loop directive.
Definition at line 5867 of file SemaOpenMP.cpp.
References clang::AssertSuccess(), clang::Sema::BuildDeclRefExpr(), buildDistanceFunc(), buildLoopVarFunc(), clang::Sema::BuildUnaryOp(), clang::IntegerLiteral::Create(), clang::OMPCanonicalLoop::create(), clang::SemaBase::getASTContext(), clang::ASTContext::getIntTypeForBitwidth(), clang::ASTContext::getIntWidth(), clang::DeclStmt::getSingleDecl(), clang::ValueDecl::getType(), clang::ASTContext::getUnsignedPointerDiffType(), clang::Expr::IgnoreImplicit(), clang::Type::isIntegerType(), clang::BinaryOperator::reverseComparisonOp(), clang::SemaBase::SemaRef, and clang::VK_LValue.
Referenced by ActOnOpenMPLoopnest().
ActOnOpenMPCaptureClause()
OMPClause * SemaOpenMP::ActOnOpenMPCaptureClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'capture' clause.
Definition at line 17900 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPClause()
OMPClause * SemaOpenMP::ActOnOpenMPClause (OpenMPClauseKind Kind, SourceLocation StartLoc, SourceLocation EndLoc)
Definition at line 17712 of file SemaOpenMP.cpp.
References ActOnOpenMPAcqRelClause(), ActOnOpenMPAcquireClause(), ActOnOpenMPCaptureClause(), ActOnOpenMPCompareClause(), ActOnOpenMPDestroyClause(), ActOnOpenMPDynamicAllocatorsClause(), ActOnOpenMPFailClause(), ActOnOpenMPFullClause(), ActOnOpenMPMergeableClause(), ActOnOpenMPNogroupClause(), ActOnOpenMPNowaitClause(), ActOnOpenMPOrderedClause(), ActOnOpenMPPartialClause(), ActOnOpenMPReadClause(), ActOnOpenMPRelaxedClause(), ActOnOpenMPReleaseClause(), ActOnOpenMPReverseOffloadClause(), ActOnOpenMPSeqCstClause(), ActOnOpenMPSIMDClause(), ActOnOpenMPThreadsClause(), ActOnOpenMPUnifiedAddressClause(), ActOnOpenMPUnifiedSharedMemoryClause(), ActOnOpenMPUntiedClause(), ActOnOpenMPUpdateClause(), ActOnOpenMPWeakClause(), ActOnOpenMPWriteClause(), and ActOnOpenMPXBareClause().
ActOnOpenMPCollapseClause()
OMPClause * SemaOpenMP::ActOnOpenMPCollapseClause (Expr * NumForLoops, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'collapse' clause.
Definition at line 17036 of file SemaOpenMP.cpp.
References clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), and VerifyPositiveIntegerConstantInClause().
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPCompareClause()
OMPClause * SemaOpenMP::ActOnOpenMPCompareClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'compare' clause.
Definition at line 17905 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPCopyinClause()
OMPClause * SemaOpenMP::ActOnOpenMPCopyinClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'copyin' clause.
Definition at line 20789 of file SemaOpenMP.cpp.
References clang::Sema::ActOnFinishFullExpr(), clang::Sema::BuildBinOp(), buildDeclRefExpr(), buildVarDecl(), clang::OMPCopyinClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::Decl::getAttrs(), clang::ASTContext::getBaseElementType(), clang::Expr::getExprLoc(), clang::QualType::getNonReferenceType(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), clang::Decl::hasAttrs(), clang::Type::isDependentType(), clang::Type::isInstantiationDependentType(), clang::ActionResult< PtrTy, Compress >::isInvalid(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPCopyprivateClause()
OMPClause * SemaOpenMP::ActOnOpenMPCopyprivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'copyprivate' clause.
Definition at line 20885 of file SemaOpenMP.cpp.
References clang::Sema::ActOnFinishFullExpr(), clang::Sema::BuildBinOp(), buildCapture(), buildDeclRefExpr(), buildVarDecl(), clang::OMPCopyprivateClause::Create(), clang::VarDecl::DeclarationOnly, clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::Decl::getAttrs(), clang::ASTContext::getBaseElementType(), clang::Decl::getLocation(), getPrivateItem(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), clang::Decl::hasAttrs(), clang::Type::isAnyPointerType(), clang::ActionResult< PtrTy, Compress >::isInvalid(), isOpenMPCapturedDecl(), clang::Type::isVariablyModifiedType(), reportOriginalDsa(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPCriticalDirective()
StmtResult SemaOpenMP::ActOnOpenMPCriticalDirective (const DeclarationNameInfo & DirName, ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp critical' after parsing of the associated statement.
Definition at line 11166 of file SemaOpenMP.cpp.
References clang::OMPCriticalDirective::Create(), clang::SemaBase::Diag(), DSAStack, clang::Expr::EvaluateKnownConstInt(), clang::SemaBase::getASTContext(), clang::DeclarationNameInfo::getName(), clang::Expr::isInstantiationDependent(), clang::Expr::isTypeDependent(), clang::SourceLocation::isValid(), clang::Expr::isValueDependent(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::StmtError(), and clang::threadSafety::sx::toString().
ActOnOpenMPDeclareMapperDirective()
SemaOpenMP::DeclGroupPtrTy SemaOpenMP::ActOnOpenMPDeclareMapperDirective (Scope * S, DeclContext * DC, DeclarationName Name, QualType MapperType, SourceLocation StartLoc, DeclarationName VN, AccessSpecifier AS, Expr * MapperVarRef, ArrayRef< OMPClause * > Clauses, Decl * PrevDeclInScope = nullptr)
Called on start of '#pragma omp declare mapper'.
Definition at line 22964 of file SemaOpenMP.cpp.
ActOnOpenMPDeclareMapperDirectiveVarDecl()
ExprResult SemaOpenMP::ActOnOpenMPDeclareMapperDirectiveVarDecl (Scope * S, QualType MapperType, SourceLocation StartLoc, DeclarationName VN)
Build the mapper variable of '#pragma omp declare mapper'.
Definition at line 23054 of file SemaOpenMP.cpp.
ActOnOpenMPDeclareMapperType()
QualType SemaOpenMP::ActOnOpenMPDeclareMapperType (SourceLocation TyLoc, TypeResult ParsedType)
Check if the specified type is allowed to be used in 'omp declare mapper' construct.
Definition at line 22948 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::OpaquePtr< PtrTy >::get(), clang::Sema::GetTypeFromParser(), clang::QualType::isNull(), clang::Type::isStructureOrClassType(), clang::Type::isUnionType(), and clang::SemaBase::SemaRef.
ActOnOpenMPDeclareMapperVarDecl()
TypeResult SemaOpenMP::ActOnOpenMPDeclareMapperVarDecl (Scope * S, Declarator & D)
Check variable declaration in 'omp declare mapper' construct.
Definition at line 22933 of file SemaOpenMP.cpp.
ActOnOpenMPDeclareReductionCombinerEnd()
void SemaOpenMP::ActOnOpenMPDeclareReductionCombinerEnd (Decl * D, Expr * Combiner)
Finish current declare reduction construct initializer.
Definition at line 22835 of file SemaOpenMP.cpp.
References clang::Sema::DiscardCleanupsInEvaluationContext(), clang::Sema::PopDeclContext(), clang::Sema::PopExpressionEvaluationContext(), clang::Sema::PopFunctionScopeInfo(), and clang::SemaBase::SemaRef.
ActOnOpenMPDeclareReductionCombinerStart()
void SemaOpenMP::ActOnOpenMPDeclareReductionCombinerStart (Scope * S, Decl * D)
Initialize declare reduction construct initializer.
Definition at line 22788 of file SemaOpenMP.cpp.
ActOnOpenMPDeclareReductionDirectiveEnd()
SemaOpenMP::DeclGroupPtrTy SemaOpenMP::ActOnOpenMPDeclareReductionDirectiveEnd (Scope * S, DeclGroupPtrTy DeclReductions, bool IsValid)
Called at the end of '#pragma omp declare reduction'.
Definition at line 22919 of file SemaOpenMP.cpp.
ActOnOpenMPDeclareReductionDirectiveStart()
SemaOpenMP::DeclGroupPtrTy SemaOpenMP::ActOnOpenMPDeclareReductionDirectiveStart (Scope * S, DeclContext * DC, DeclarationName Name, ArrayRef< std::pair< QualType, SourceLocation >> ReductionTypes, AccessSpecifier AS, Decl * PrevDeclInScope = nullptr)
Called on start of '#pragma omp declare reduction'.
Definition at line 22705 of file SemaOpenMP.cpp.
ActOnOpenMPDeclareReductionInitializerEnd()
void SemaOpenMP::ActOnOpenMPDeclareReductionInitializerEnd (Decl * D, Expr * Initializer, VarDecl * OmpPrivParm)
Finish current declare reduction construct initializer.
Definition at line 22898 of file SemaOpenMP.cpp.
References clang::Call, clang::Copy, clang::Direct, clang::Sema::DiscardCleanupsInEvaluationContext(), clang::VarDecl::getInit(), clang::VarDecl::hasInit(), clang::Initializer, clang::VarDecl::isDirectInit(), clang::Sema::PopDeclContext(), clang::Sema::PopExpressionEvaluationContext(), clang::Sema::PopFunctionScopeInfo(), and clang::SemaBase::SemaRef.
ActOnOpenMPDeclareReductionInitializerStart()
VarDecl * SemaOpenMP::ActOnOpenMPDeclareReductionInitializerStart (Scope * S, Decl * D)
Initialize declare reduction construct initializer.
Returns
omp_priv variable.
Definition at line 22850 of file SemaOpenMP.cpp.
ActOnOpenMPDeclareReductionType()
QualType SemaOpenMP::ActOnOpenMPDeclareReductionType (SourceLocation TyLoc, TypeResult ParsedType)
Check if the specified type is allowed to be used in 'omp declare reduction' construct.
Definition at line 22672 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::OpaquePtr< PtrTy >::get(), clang::Sema::GetTypeFromParser(), clang::QualType::hasQualifiers(), clang::Type::isArrayType(), clang::Type::isFunctionType(), clang::QualType::isNull(), clang::Type::isReferenceType(), and clang::SemaBase::SemaRef.
ActOnOpenMPDeclareSimdDirective()
SemaOpenMP::DeclGroupPtrTy SemaOpenMP::ActOnOpenMPDeclareSimdDirective (DeclGroupPtrTy DG, OMPDeclareSimdDeclAttr::BranchStateTy BS, Expr * Simdlen, ArrayRef< Expr * > Uniforms, ArrayRef< Expr * > Aligneds, ArrayRef< Expr * > Alignments, ArrayRef< Expr * > Linears, ArrayRef< unsigned > LinModifiers, ArrayRef< Expr * > Steps, SourceRange SR)
Called on well-formed '#pragma omp declare simd' after parsing of the associated method/function.
Definition at line 7094 of file SemaOpenMP.cpp.
References clang::Decl::addAttr(), clang::Sema::AllowFold, CheckOpenMPLinearDecl(), clang::Expr::containsUnexpandedParameterPack(), clang::SemaBase::Diag(), clang::OpaquePtr< PtrTy >::get(), clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::SourceRange::getBegin(), clang::VarDecl::getCanonicalDecl(), clang::FieldDecl::getCanonicalDecl(), clang::NamedDecl::getDeclName(), clang::Expr::getExprLoc(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::Stmt::getSourceRange(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::QualType::getTypePtrOrNull(), clang::Type::hasIntegerRepresentation(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isArrayType(), clang::Expr::isInstantiationDependent(), clang::Type::isPointerType(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), PerformOpenMPImplicitIntegerConversion(), clang::SemaBase::SemaRef, clang::Sema::VerifyIntegerConstantExpression(), and VerifyPositiveIntegerConstantInClause().
ActOnOpenMPDeclareTargetInitializer()
void SemaOpenMP::ActOnOpenMPDeclareTargetInitializer (Decl * D)
Adds OMPDeclareTargetDeclAttr to referenced variables in declare target directive.
Adding OMPDeclareTargetDeclAttr to variables with static storage duration that are referenced in the initializer expression list of variables with static storage duration in declare target directive.
Definition at line 23756 of file SemaOpenMP.cpp.
References GlobalDeclRefChecker::declareTargetInitializer().
Referenced by ActOnOpenMPDeclareTargetName().
ActOnOpenMPDeclareTargetName()
void SemaOpenMP::ActOnOpenMPDeclareTargetName (NamedDecl * ND, SourceLocation Loc, OMPDeclareTargetDeclAttr::MapTypeTy MT, DeclareTargetContextInfo & DTCI)
Called on correct id-expression from the '#pragma omp declare target'.
Definition at line 23534 of file SemaOpenMP.cpp.
References ActOnOpenMPDeclareTargetInitializer(), clang::Decl::addAttr(), checkDeclIsAllowedInOpenMPTarget(), clang::SemaBase::Diag(), clang::SemaOpenMP::DeclareTargetContextInfo::DT, clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), clang::NamedDecl::getNameAsString(), clang::Decl::hasAttr(), clang::HIP, clang::SemaOpenMP::DeclareTargetContextInfo::Indirect, clang::Decl::isReferenced(), and clang::Decl::isUsed().
Referenced by ActOnFinishedOpenMPDeclareTargetContext().
ActOnOpenMPDeclareVariantDirective()
void SemaOpenMP::ActOnOpenMPDeclareVariantDirective (FunctionDecl * FD, Expr * VariantRef, OMPTraitInfo & TI, ArrayRef< Expr * > AdjustArgsNothing, ArrayRef< Expr * > AdjustArgsNeedDevicePtr, ArrayRef< OMPInteropInfo > AppendArgs, SourceLocation AdjustArgsLoc, SourceLocation AppendArgsLoc, SourceRange SR)
Called on well-formed '#pragma omp declare variant' after parsing of the associated method/function.
Parameters
FD Function declaration to which declare variant directive is applied to.
VariantRef Expression that references the variant function, which must be used instead of the original one, specified in DG.
TI The context traits associated with the function variant.
AdjustArgsNothing The list of 'nothing' arguments.
AdjustArgsNeedDevicePtr The list of 'need_device_ptr' arguments.
AppendArgs The list of 'append_args' arguments.
AdjustArgsLoc The Location of an 'adjust_args' clause.
AppendArgsLoc The Location of an 'append_args' clause.
SR The SourceRange of the 'declare variant' directive.
Definition at line 7926 of file SemaOpenMP.cpp.
References clang::Decl::addAttr(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::OMPTraitInfo::getAsVariantMatchInfo(), clang::VarDecl::getCanonicalDecl(), clang::Expr::getExprLoc(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), and clang::Expr::IgnoreParenImpCasts().
ActOnOpenMPDefaultClause()
OMPClause * SemaOpenMP::ActOnOpenMPDefaultClause (llvm::omp::DefaultKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'default' clause.
Definition at line 17221 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), and getListOfPossibleValues().
Referenced by ActOnOpenMPSimpleClause().
ActOnOpenMPDefaultmapClause()
OMPClause * SemaOpenMP::ActOnOpenMPDefaultmapClause (OpenMPDefaultmapClauseModifier M, OpenMPDefaultmapClauseKind Kind, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation MLoc, SourceLocation KindLoc, SourceLocation EndLoc)
Called on well-formed 'defaultmap' clause.
Definition at line 23371 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), clang::getOpenMPSimpleClauseTypeName(), clang::SourceLocation::isInvalid(), clang::OMPC_DEFAULTMAP_MODIFIER_unknown, and clang::OMPC_DEFAULTMAP_unknown.
Referenced by ActOnOpenMPSingleExprWithArgClause().
ActOnOpenMPDependClause()
OMPClause * SemaOpenMP::ActOnOpenMPDependClause (const OMPDependClause::DependDataTy & Data, Expr * DepModifier, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'depend' clause.
Definition at line 21187 of file SemaOpenMP.cpp.
References clang::OMPDependClause::Create(), clang::Sema::CreateBuiltinUnaryOp(), Data, clang::SemaBase::Diag(), DSAStack, findOMPDependT(), clang::Type::getAsArrayTypeUnsafe(), clang::SemaBase::getASTContext(), clang::OMPArraySectionExpr::getBaseOriginalType(), clang::Expr::getExprLoc(), clang::SemaBase::getLangOpts(), getListOfPossibleValues(), clang::QualType::getNonReferenceType(), clang::Type::getPointeeType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::QualType::getTypePtr(), clang::Expr::IgnoreParenCasts(), clang::QualType::isNull(), clang::Type::isSpecificBuiltinType(), clang::ActionResult< PtrTy, Compress >::isUsable(), clang::OMPC_DEPEND_unknown, ProcessOpenMPDoacrossClauseCommon(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPDepobjClause()
OMPClause * SemaOpenMP::ActOnOpenMPDepobjClause (Expr * Depobj, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'depobj' pseudo clause.
Definition at line 21027 of file SemaOpenMP.cpp.
References clang::Expr::containsUnexpandedParameterPack(), clang::OMPDepobjClause::Create(), clang::SemaBase::Diag(), DSAStack, findOMPDependT(), clang::SemaBase::getASTContext(), clang::Expr::getExprLoc(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::Expr::isInstantiationDependent(), clang::Expr::isLValue(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPDepobjDirective()
StmtResult SemaOpenMP::ActOnOpenMPDepobjDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp depobj'.
Definition at line 11558 of file SemaOpenMP.cpp.
References clang::OMPDepobjDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), and clang::StmtError().
ActOnOpenMPDestroyClause()
OMPClause * SemaOpenMP::ActOnOpenMPDestroyClause (Expr * InteropVar, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Called on well-formed 'destroy' clause.
Definition at line 18166 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), isValidInteropVariable(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPClause().
ActOnOpenMPDetachClause()
OMPClause * SemaOpenMP::ActOnOpenMPDetachClause (Expr * Evt, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'detach' clause.
Definition at line 23268 of file SemaOpenMP.cpp.
References clang::Expr::containsUnexpandedParameterPack(), clang::SemaBase::Diag(), DSAStack, findOMPEventHandleT(), clang::SemaBase::getASTContext(), clang::DeclRefExpr::getDecl(), clang::Expr::getExprLoc(), clang::Stmt::getSourceRange(), clang::ValueDecl::getType(), clang::Expr::IgnoreParenImpCasts(), clang::QualType::isConstant(), clang::Expr::isInstantiationDependent(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), reportOriginalDsa(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPDeviceClause()
OMPClause * SemaOpenMP::ActOnOpenMPDeviceClause (OpenMPDeviceClauseModifier Modifier, Expr * Device, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Called on well-formed 'device' clause.
Definition at line 21380 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CurContext, clang::Device, clang::SemaBase::Diag(), DSAStack, clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getListOfPossibleValues(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), clang::SourceLocation::isInvalid(), isNonNegativeIntegerValue(), clang::SourceLocation::isValid(), clang::Sema::MakeFullExpr(), clang::OMPC_DEVICE_unknown, clang::SemaBase::SemaRef, and clang::Sema::targetDiag().
Referenced by ActOnOpenMPSingleExprWithArgClause().
ActOnOpenMPDispatchDirective()
StmtResult SemaOpenMP::ActOnOpenMPDispatchDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp dispatch' after parsing of the.
Definition at line 10803 of file SemaOpenMP.cpp.
References clang::StmtError().
ActOnOpenMPDistributeDirective()
StmtResult SemaOpenMP::ActOnOpenMPDistributeDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp distribute' after parsing of the associated statement.
Definition at line 14284 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPDistributeDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPDistributeParallelForDirective()
StmtResult SemaOpenMP::ActOnOpenMPDistributeParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp distribute parallel for' after parsing of the associated statement.
Definition at line 14314 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPDistributeParallelForDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPDistributeParallelForSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPDistributeParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp distribute parallel for simd' after parsing of the associated statement.
Definition at line 14358 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPDistributeParallelForSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPDistributeSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPDistributeSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp distribute simd' after parsing of the associated statement.
Definition at line 14415 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPDistributeSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPDistScheduleClause()
OMPClause * SemaOpenMP::ActOnOpenMPDistScheduleClause (OpenMPDistScheduleClauseKind Kind, Expr * ChunkSize, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation KindLoc, SourceLocation CommaLoc, SourceLocation EndLoc)
Called on well-formed 'dist_schedule' clause.
Definition at line 23317 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Expr::containsUnexpandedParameterPack(), clang::Sema::CurContext, clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::Stmt::getBeginLoc(), clang::Expr::getIntegerConstantExpr(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::getOpenMPSimpleClauseTypeName(), clang::Stmt::getSourceRange(), clang::DeclContext::isDependentContext(), clang::Expr::isInstantiationDependent(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::Sema::MakeFullExpr(), clang::OMPC_DIST_SCHEDULE_unknown, PerformOpenMPImplicitIntegerConversion(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprWithArgClause().
ActOnOpenMPDoacrossClause()
OMPClause * SemaOpenMP::ActOnOpenMPDoacrossClause (OpenMPDoacrossClauseModifier DepType, SourceLocation DepLoc, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'doacross' clause.
Definition at line 24583 of file SemaOpenMP.cpp.
References clang::OMPDoacrossClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), ProcessOpenMPDoacrossClauseCommon(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPDynamicAllocatorsClause()
OMPClause * SemaOpenMP::ActOnOpenMPDynamicAllocatorsClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'dynamic_allocators' clause.
Definition at line 17991 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPEndAssumesDirective()
void SemaOpenMP::ActOnOpenMPEndAssumesDirective ()
Called on well-formed '#pragma omp end assumes'.
Definition at line 3556 of file SemaOpenMP.cpp.
References isInOpenMPAssumeScope().
ActOnOpenMPEndDeclareTargetDirective()
const SemaOpenMP::DeclareTargetContextInfo SemaOpenMP::ActOnOpenMPEndDeclareTargetDirective ()
Called at the end of target region i.e. '#pragma omp end declare target'.
Definition at line 23480 of file SemaOpenMP.cpp.
ActOnOpenMPEndDeclareVariant()
void SemaOpenMP::ActOnOpenMPEndDeclareVariant ()
Handle a omp end declare variant.
Definition at line 2721 of file SemaOpenMP.cpp.
References isInOpenMPDeclareVariantScope().
ActOnOpenMPErrorDirective()
StmtResult SemaOpenMP::ActOnOpenMPErrorDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, bool InExContext = true)
Called on well-formed '#pragma omp error'.
Error direcitive is allowed in both declared and excutable contexts. Adding InExContext to identify which context is called from.
Definition at line 11454 of file SemaOpenMP.cpp.
References clang::OMPErrorDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::OMPAtClause::getAtKind(), clang::OMPAtClause::getAtKindKwLoc(), clang::OMPMessageClause::getMessageString(), clang::OMPSeverityClause::getSeverityKind(), clang::OMPSeverityClause::getSeverityKindKwLoc(), and clang::StmtError().
ActOnOpenMPExclusiveClause()
OMPClause * SemaOpenMP::ActOnOpenMPExclusiveClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'exclusive' clause.
Definition at line 24304 of file SemaOpenMP.cpp.
References clang::OMPExclusiveClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), getPrivateItem(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPExecutableDirective()
StmtResult SemaOpenMP::ActOnOpenMPExecutableDirective (OpenMPDirectiveKind Kind, const DeclarationNameInfo & DirName, OpenMPDirectiveKind CancelRegion, ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, OpenMPDirectiveKind PrevMappedDirective = llvm::omp::OMPD_unknown)
Definition at line 6330 of file SemaOpenMP.cpp.
References checkCancelRegion(), checkNestingOfRegions(), clang::Sema::CurContext, clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getLangOpts(), getOpenMPCaptureLevels(), clang::HIP, clang::DeclContext::isDependentContext(), clang::isOpenMPLoopTransformationDirective(), clang::isOpenMPTargetDataManagementDirective(), clang::isOpenMPTargetExecutionDirective(), clang::OMPC_BIND_unknown, clang::SemaBase::SemaRef, and clang::StmtError().
ActOnOpenMPFailClause() [1/2]
OMPClause * SemaOpenMP::ActOnOpenMPFailClause (OpenMPClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Definition at line 17915 of file SemaOpenMP.cpp.
References clang::checkFailClauseParameter(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), and clang::Parameter.
ActOnOpenMPFailClause() [2/2]
OMPClause * SemaOpenMP::ActOnOpenMPFailClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'fail' clause.
Definition at line 17910 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause(), and ActOnOpenMPSimpleClause().
ActOnOpenMPFilterClause()
OMPClause * SemaOpenMP::ActOnOpenMPFilterClause (Expr * ThreadID, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'filter' clause.
Definition at line 18250 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CurContext, DSAStack, clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPFinalClause()
OMPClause * SemaOpenMP::ActOnOpenMPFinalClause (Expr * Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'final' clause.
Definition at line 16734 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CheckBooleanCondition(), clang::Condition, clang::Sema::CurContext, DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPFirstprivateClause()
OMPClause * SemaOpenMP::ActOnOpenMPFirstprivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'firstprivate' clause.
Definition at line 18635 of file SemaOpenMP.cpp.
References clang::DeclContext::addDecl(), clang::Sema::AddInitializerToDecl(), buildCapture(), buildDeclRefExpr(), buildPreInits(), buildVarDecl(), clang::OMPFirstprivateClause::Create(), clang::InitializationKind::CreateCopy(), clang::Sema::CurContext, clang::ASTContext::Deallocate(), clang::VarDecl::DeclarationOnly, clang::Sema::DefaultLvalueConversion(), clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::Decl::getAttrs(), clang::ASTContext::getBaseElementType(), clang::DeclRefExpr::getDecl(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::QualType::getNonReferenceType(), getPrivateItem(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), clang::Decl::hasAttrs(), clang::InitializedEntity::InitializeVariable(), clang::Type::isAnyPointerType(), clang::Type::isArrayType(), clang::QualType::isConstant(), clang::DeclContext::isDependentContext(), clang::SourceLocation::isInvalid(), clang::Decl::isInvalidDecl(), isOpenMPCapturedDecl(), clang::isOpenMPDistributeDirective(), clang::isOpenMPParallelDirective(), clang::isOpenMPTargetExecutionDirective(), clang::isOpenMPTaskingDirective(), clang::isOpenMPTeamsDirective(), clang::isOpenMPWorksharingDirective(), clang::Type::isVariablyModifiedType(), clang::InitializationSequence::Perform(), reportOriginalDsa(), clang::Sema::RequireCompleteType(), clang::SemaBase::SemaRef, clang::VarDecl::setInit(), and clang::Decl::setInvalidDecl().
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPFlushClause()
OMPClause * SemaOpenMP::ActOnOpenMPFlushClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'flush' pseudo clause.
Definition at line 20999 of file SemaOpenMP.cpp.
References clang::OMPFlushClause::Create(), and clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPFlushDirective()
StmtResult SemaOpenMP::ActOnOpenMPFlushDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp flush'.
Definition at line 11519 of file SemaOpenMP.cpp.
References clang::OMPFlushDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::OMPClause::getBeginLoc(), clang::OMPClause::getClauseKind(), clang::OMPVarListClause< T >::getLParenLoc(), and clang::StmtError().
ActOnOpenMPForDirective()
StmtResult SemaOpenMP::ActOnOpenMPForDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp for' after parsing of the associated statement.
Definition at line 10663 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPForDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, and clang::StmtError().
ActOnOpenMPForSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp for simd' after parsing of the associated statement.
Definition at line 10703 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPForSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPFromClause()
OMPClause * SemaOpenMP::ActOnOpenMPFromClause (ArrayRef< OpenMPMotionModifierKind > MotionModifiers, ArrayRef< SourceLocation > MotionModifiersLoc, CXXScopeSpec & MapperIdScopeSpec, DeclarationNameInfo & MapperId, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs, ArrayRef< Expr * > UnresolvedMappers = std::nullopt)
Called on well-formed 'from' clause.
Definition at line 23799 of file SemaOpenMP.cpp.
References checkMappableExpressionList(), clang::OMPFromClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::CXXScopeSpec::getWithLocInContext(), clang::NumberOfOMPMotionModifiers, clang::OMPC_MOTION_MODIFIER_unknown, clang::SemaBase::SemaRef, and clang::OMPVarListLocTy::StartLoc.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPFullClause()
OMPClause * SemaOpenMP::ActOnOpenMPFullClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-form 'full' clauses.
Definition at line 17421 of file SemaOpenMP.cpp.
References clang::OMPFullClause::Create(), and clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPGenericLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp loop' after parsing of the associated statement.
Definition at line 10877 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkGenericLoopLastprivate(), checkOpenMPLoop(), clang::OMPGenericLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), getCollapseNumberExpr(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPGrainsizeClause()
OMPClause * SemaOpenMP::ActOnOpenMPGrainsizeClause (OpenMPGrainsizeClauseModifier Modifier, Expr * Size, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Called on well-formed 'grainsize' clause.
Definition at line 23170 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getListOfPossibleValues(), clang::SourceLocation::isInvalid(), isNonNegativeIntegerValue(), clang::SourceLocation::isValid(), clang::OMPC_GRAINSIZE_unknown, and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprWithArgClause().
ActOnOpenMPHasDeviceAddrClause()
OMPClause * SemaOpenMP::ActOnOpenMPHasDeviceAddrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs)
Called on well-formed 'has_device_addr' clause.
Definition at line 24061 of file SemaOpenMP.cpp.
References buildCapture(), clang::OMPHasDeviceAddrClause::Create(), clang::Sema::CurContext, clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::format::getBase(), clang::Expr::getExprLoc(), getPrivateItem(), clang::Stmt::getSourceRange(), clang::DeclContext::isDependentContext(), clang::isOpenMPPrivate(), reportOriginalDsa(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPHintClause()
OMPClause * SemaOpenMP::ActOnOpenMPHintClause (Expr * Hint, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'hint' clause.
Definition at line 23237 of file SemaOpenMP.cpp.
References clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), and VerifyPositiveIntegerConstantInClause().
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPIdExpression()
ExprResult SemaOpenMP::ActOnOpenMPIdExpression (Scope * CurScope, CXXScopeSpec & ScopeSpec, const DeclarationNameInfo & Id, OpenMPDirectiveKind Kind)
Called on correct id-expression from the '#pragma omp threadprivate'.
Definition at line 3060 of file SemaOpenMP.cpp.
ActOnOpenMPIfClause()
OMPClause * SemaOpenMP::ActOnOpenMPIfClause (OpenMPDirectiveKind NameModifier, Expr * Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation NameModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc)
Called on well-formed 'if' clause.
Definition at line 16701 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CheckBooleanCondition(), clang::Condition, clang::Sema::CurContext, DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprWithArgClause().
ActOnOpenMPInclusiveClause()
OMPClause * SemaOpenMP::ActOnOpenMPInclusiveClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'inclusive' clause.
Definition at line 24263 of file SemaOpenMP.cpp.
References clang::OMPInclusiveClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), getPrivateItem(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPInitClause()
OMPClause * SemaOpenMP::ActOnOpenMPInitClause (Expr * InteropVar, OMPInteropInfo & InteropInfo, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Called on well-formed 'init' clause.
Definition at line 18128 of file SemaOpenMP.cpp.
References clang::Expr::containsUnexpandedParameterPack(), clang::OMPInitClause::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::Expr::getExprLoc(), clang::Expr::isInstantiationDependent(), clang::Expr::isIntegerConstantExpr(), clang::Expr::isTypeDependent(), isValidInteropVariable(), clang::Expr::isValueDependent(), clang::OMPInteropInfo::PreferTypes, and clang::SemaBase::SemaRef.
ActOnOpenMPInReductionClause()
OMPClause * SemaOpenMP::ActOnOpenMPInReductionClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec & ReductionIdScopeSpec, const DeclarationNameInfo & ReductionId, ArrayRef< Expr * > UnresolvedReductions = std::nullopt)
Called on well-formed 'in_reduction' clause.
Definition at line 20394 of file SemaOpenMP.cpp.
References actOnOMPReductionKindClause(), buildPostUpdate(), buildPreInits(), clang::OMPInReductionClause::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::CXXScopeSpec::getWithLocInContext(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPInteropDirective()
StmtResult SemaOpenMP::ActOnOpenMPInteropDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp interop'.
Definition at line 17997 of file SemaOpenMP.cpp.
References clang::OMPInteropDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::OMPClause::getBeginLoc(), getPrivateItem(), hasClauses(), clang::SemaBase::SemaRef, and clang::StmtError().
ActOnOpenMPIsDevicePtrClause()
OMPClause * SemaOpenMP::ActOnOpenMPIsDevicePtrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs)
Called on well-formed 'is_device_ptr' clause.
Definition at line 23977 of file SemaOpenMP.cpp.
References clang::OMPIsDevicePtrClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::format::getBase(), clang::Expr::getExprLoc(), getPrivateItem(), clang::Stmt::getSourceRange(), clang::ValueDecl::getType(), clang::Type::isArrayType(), clang::isOpenMPPrivate(), clang::Type::isPointerType(), reportOriginalDsa(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPIteratorVarDecl()
void SemaOpenMP::ActOnOpenMPIteratorVarDecl (VarDecl * VD)
Definition at line 23069 of file SemaOpenMP.cpp.
References DSAStack.
ActOnOpenMPLastprivateClause()
OMPClause * SemaOpenMP::ActOnOpenMPLastprivateClause (ArrayRef< Expr * > VarList, OpenMPLastprivateModifier LPKind, SourceLocation LPKindLoc, SourceLocation ColonLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'lastprivate' clause.
Definition at line 18924 of file SemaOpenMP.cpp.
References clang::Sema::ActOnFinishFullExpr(), clang::Sema::BuildBinOp(), buildCapture(), buildDeclRefExpr(), buildPostUpdate(), buildPreInits(), buildVarDecl(), clang::OMPLastprivateClause::Create(), clang::Sema::CurContext, clang::VarDecl::DeclarationOnly, clang::Sema::DefaultLvalueConversion(), clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::Decl::getAttrs(), clang::ASTContext::getBaseElementType(), clang::SourceRange::getBegin(), clang::DeclRefExpr::getDecl(), getListOfPossibleValues(), clang::Decl::getLocation(), clang::QualType::getNonReferenceType(), getPrivateItem(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::Decl::hasAttrs(), clang::Sema::IgnoredValueConversions(), clang::DeclContext::isDependentContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), isOpenMPCapturedDecl(), clang::isOpenMPDistributeDirective(), clang::isOpenMPParallelDirective(), clang::isOpenMPTeamsDirective(), clang::isOpenMPWorksharingDirective(), clang::Type::isScalarType(), clang::ActionResult< PtrTy, Compress >::isUsable(), clang::SourceLocation::isValid(), clang::OMPC_LASTPRIVATE_unknown, rejectConstNotMutableType(), reportOriginalDsa(), clang::Sema::RequireCompleteType(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPLinearClause()
OMPClause * SemaOpenMP::ActOnOpenMPLinearClause (ArrayRef< Expr * > VarList, Expr * Step, SourceLocation StartLoc, SourceLocation LParenLoc, OpenMPLinearClauseKind LinKind, SourceLocation LinLoc, SourceLocation ColonLoc, SourceLocation StepModifierLoc, SourceLocation EndLoc)
Called on well-formed 'linear' clause.
Definition at line 20468 of file SemaOpenMP.cpp.
References clang::Sema::ActOnFinishFullExpr(), clang::Sema::AddInitializerToDecl(), clang::Sema::BuildBinOp(), buildCapture(), buildDeclRefExpr(), buildPostUpdate(), buildPreInits(), buildVarDecl(), CheckOpenMPLinearDecl(), CheckOpenMPLinearModifier(), clang::Expr::containsUnexpandedParameterPack(), clang::OMPLinearClause::Create(), clang::Sema::CurContext, clang::Sema::DefaultLvalueConversion(), clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::Decl::getAttrs(), clang::Stmt::getBeginLoc(), clang::Sema::getCurScope(), clang::DeclRefExpr::getDecl(), clang::Expr::getIntegerConstantExpr(), clang::SemaBase::getLangOpts(), clang::NamedDecl::getName(), getPrivateItem(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::Decl::hasAttr(), clang::Decl::hasAttrs(), clang::Sema::IgnoredValueConversions(), clang::DeclContext::isDependentContext(), clang::Expr::isInstantiationDependent(), clang::SourceLocation::isInvalid(), clang::ActionResult< PtrTy, Compress >::isInvalid(), isOpenMPCapturedDecl(), clang::Expr::isTypeDependent(), clang::ActionResult< PtrTy, Compress >::isUsable(), clang::SourceLocation::isValid(), clang::Expr::isValueDependent(), PerformOpenMPImplicitIntegerConversion(), clang::Private, reportOriginalDsa(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPLoopInitialization()
void SemaOpenMP::ActOnOpenMPLoopInitialization (SourceLocation ForLoc, Stmt * Init)
Check if the current region is an OpenMP loop region and if it is, mark loop control variable, used in Init for loop initialization, as private by default.
Parameters
Init First part of the for loop.
Definition at line 9359 of file SemaOpenMP.cpp.
References buildCapture(), buildDeclRefExpr(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::DeclRefExpr::getDecl(), clang::SemaBase::getLangOpts(), clang::QualType::getNonLValueExprType(), clang::ValueDecl::getType(), isOpenMPCapturedDecl(), clang::isOpenMPDistributeDirective(), clang::isOpenMPLoopDirective(), clang::isOpenMPSimdDirective(), clang::isOpenMPWorksharingDirective(), clang::Sema::MarkDeclarationsReferencedInExpr(), clang::Private, reportOriginalDsa(), and clang::SemaBase::SemaRef.
ActOnOpenMPLoopnest()
StmtResult SemaOpenMP::ActOnOpenMPLoopnest (Stmt * AStmt)
Process a canonical OpenMP loop nest that can either be a canonical literal loop (ForStmt or CXXForRangeStmt), or the generated loop of an OpenMP loop transformation construct.
Definition at line 6016 of file SemaOpenMP.cpp.
References ActOnOpenMPCanonicalLoop(), clang::OMPExecutableDirective::getDirectiveKind(), and clang::isOpenMPLoopTransformationDirective().
ActOnOpenMPMapClause()
OMPClause * SemaOpenMP::ActOnOpenMPMapClause (Expr * IteratorModifier, ArrayRef< OpenMPMapModifierKind > MapTypeModifiers, ArrayRef< SourceLocation > MapTypeModifiersLoc, CXXScopeSpec & MapperIdScopeSpec, DeclarationNameInfo & MapperId, OpenMPMapClauseKind MapType, bool IsMapTypeImplicit, SourceLocation MapLoc, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs, bool NoDiagnose = false, ArrayRef< Expr * > UnresolvedMappers = std::nullopt)
Called on well-formed 'map' clause.
Definition at line 22623 of file SemaOpenMP.cpp.
References checkMappableExpressionList(), clang::OMPMapClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::Expr::getExprLoc(), clang::Expr::getType(), clang::CXXScopeSpec::getWithLocInContext(), clang::Type::isSpecificBuiltinType(), clang::NumberOfOMPMapClauseModifiers, clang::OMPC_MAP_MODIFIER_unknown, clang::SemaBase::SemaRef, and clang::OMPVarListLocTy::StartLoc.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPMaskedDirective()
StmtResult SemaOpenMP::ActOnOpenMPMaskedDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp masked' after parsing of the.
Definition at line 11153 of file SemaOpenMP.cpp.
References clang::OMPMaskedDirective::Create(), clang::SemaBase::getASTContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPMaskedTaskLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPMaskedTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp masked taskloop' after parsing of the associated statement.
Definition at line 13894 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), clang::OMPMaskedTaskLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPMaskedTaskLoopSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp masked taskloop simd' after parsing of the associated statement.
Definition at line 13982 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), checkSimdlenSafelenSpecified(), clang::OMPMaskedTaskLoopSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::Sema::getCurScope(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPMasterDirective()
StmtResult SemaOpenMP::ActOnOpenMPMasterDirective (Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp master' after parsing of the associated statement.
Definition at line 11142 of file SemaOpenMP.cpp.
References clang::OMPMasterDirective::Create(), clang::SemaBase::getASTContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPMasterTaskLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPMasterTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp master taskloop' after parsing of the associated statement.
Definition at line 13856 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), clang::OMPMasterTaskLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPMasterTaskLoopSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp master taskloop simd' after parsing of the associated statement.
Definition at line 13932 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), checkSimdlenSafelenSpecified(), clang::OMPMasterTaskLoopSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::Sema::getCurScope(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPMergeableClause()
OMPClause * SemaOpenMP::ActOnOpenMPMergeableClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'mergeable' clause.
Definition at line 17880 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPMessageClause()
OMPClause * SemaOpenMP::ActOnOpenMPMessageClause (Expr * MS, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'message' clause.
passing string for message.
Definition at line 17330 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), and clang::Stmt::getBeginLoc().
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPMetaDirective()
StmtResult clang::SemaOpenMP::ActOnOpenMPMetaDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp metadirective' after parsing of the associated statement.
ActOnOpenMPNocontextClause()
OMPClause * SemaOpenMP::ActOnOpenMPNocontextClause (Expr * Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'nocontext' clause.
Definition at line 18218 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CheckBooleanCondition(), clang::Condition, clang::Sema::CurContext, DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPNogroupClause()
OMPClause * SemaOpenMP::ActOnOpenMPNogroupClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'nogroup' clause.
Definition at line 17969 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPNontemporalClause()
OMPClause * SemaOpenMP::ActOnOpenMPNontemporalClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'nontemporal' clause.
Definition at line 24211 of file SemaOpenMP.cpp.
References clang::OMPNontemporalClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), getPrivateItem(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPNovariantsClause()
OMPClause * SemaOpenMP::ActOnOpenMPNovariantsClause (Expr * Condition, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'novariants' clause.
Definition at line 18186 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CheckBooleanCondition(), clang::Condition, clang::Sema::CurContext, DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPNowaitClause()
OMPClause * SemaOpenMP::ActOnOpenMPNowaitClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'nowait' clause.
Definition at line 17868 of file SemaOpenMP.cpp.
References DSAStack, and clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPNumTasksClause()
OMPClause * SemaOpenMP::ActOnOpenMPNumTasksClause (OpenMPNumTasksClauseModifier Modifier, Expr * NumTasks, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation EndLoc)
Called on well-formed 'num_tasks' clause.
Definition at line 23204 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getListOfPossibleValues(), clang::SourceLocation::isInvalid(), isNonNegativeIntegerValue(), clang::SourceLocation::isValid(), clang::OMPC_NUMTASKS_unknown, and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprWithArgClause().
ActOnOpenMPNumTeamsClause()
OMPClause * SemaOpenMP::ActOnOpenMPNumTeamsClause (Expr * NumTeams, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'num_teams' clause.
Definition at line 23094 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CurContext, DSAStack, clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), isNonNegativeIntegerValue(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPNumThreadsClause()
OMPClause * SemaOpenMP::ActOnOpenMPNumThreadsClause (Expr * NumThreads, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'num_threads' clause.
Definition at line 16853 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CurContext, DSAStack, clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), isNonNegativeIntegerValue(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPOrderClause()
OMPClause * SemaOpenMP::ActOnOpenMPOrderClause (OpenMPOrderClauseModifier Modifier, OpenMPOrderClauseKind Kind, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation MLoc, SourceLocation KindLoc, SourceLocation EndLoc)
Called on well-formed 'order' clause.
Definition at line 17344 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getListOfPossibleValues(), clang::SourceLocation::isValid(), clang::OMPC_ORDER_MODIFIER_last, clang::OMPC_ORDER_MODIFIER_unknown, clang::OMPC_ORDER_unknown, and clang::Scope::OpenMPOrderClauseScope.
Referenced by ActOnOpenMPSingleExprWithArgClause().
ActOnOpenMPOrderedClause()
OMPClause * SemaOpenMP::ActOnOpenMPOrderedClause (SourceLocation StartLoc, SourceLocation EndLoc, SourceLocation LParenLoc = SourceLocation(), Expr * NumForLoops = nullptr)
Called on well-formed 'ordered' clause.
Definition at line 17053 of file SemaOpenMP.cpp.
References clang::OMPOrderedClause::Create(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::SourceLocation::isValid(), and VerifyPositiveIntegerConstantInClause().
Referenced by ActOnOpenMPClause(), and ActOnOpenMPSingleExprClause().
ActOnOpenMPOrderedDirective()
StmtResult SemaOpenMP::ActOnOpenMPOrderedDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp ordered' after parsing of the associated statement.
Definition at line 11611 of file SemaOpenMP.cpp.
References clang::OMPOrderedDirective::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::OMPClause::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::OMPClause::getClauseKind(), clang::SemaBase::getLangOpts(), clang::isOpenMPSimdDirective(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPParallelDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp parallel' after parsing of the associated statement.
Definition at line 7996 of file SemaOpenMP.cpp.
References clang::OMPParallelDirective::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelForDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel for' after parsing of the associated statement.
Definition at line 11223 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPParallelForDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelForSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel for simd' after parsing of the associated statement.
Definition at line 11267 of file SemaOpenMP.cpp.
References checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPParallelForSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelGenericLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel loop' after parsing of the associated statement.
Definition at line 11012 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkGenericLoopLastprivate(), checkOpenMPLoop(), clang::OMPParallelGenericLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelMaskedDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelMaskedDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp parallel masked' after parsing of the associated statement.
Definition at line 11332 of file SemaOpenMP.cpp.
References clang::OMPParallelMaskedDirective::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelMaskedTaskLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel masked taskloop' after parsing of the associated statement.
Definition at line 14089 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), clang::OMPParallelMaskedTaskLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelMaskedTaskLoopSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel masked taskloop simd' after parsing of the associated statement.
Definition at line 14215 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), checkSimdlenSafelenSpecified(), clang::OMPParallelMaskedTaskLoopSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelMasterDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelMasterDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp parallel master' after parsing of the associated statement.
Definition at line 11310 of file SemaOpenMP.cpp.
References clang::OMPParallelMasterDirective::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelMasterTaskLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel master taskloop' after parsing of the associated statement.
Definition at line 14032 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), clang::OMPParallelMasterTaskLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelMasterTaskLoopSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp parallel master taskloop simd' after parsing of the associated statement.
Definition at line 14146 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), checkSimdlenSafelenSpecified(), clang::OMPParallelMasterTaskLoopSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPParallelSectionsDirective()
StmtResult SemaOpenMP::ActOnOpenMPParallelSectionsDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp parallel sections' after parsing of the associated statement.
Definition at line 11354 of file SemaOpenMP.cpp.
References clang::CapturedStmt::getCapturedStmt(), and clang::StmtError().
ActOnOpenMPPartialClause()
OMPClause * SemaOpenMP::ActOnOpenMPPartialClause (Expr * FactorExpr, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-form 'partial' clauses.
Definition at line 17426 of file SemaOpenMP.cpp.
References clang::OMPPartialClause::Create(), clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), and VerifyPositiveIntegerConstantInClause().
Referenced by ActOnOpenMPClause(), and ActOnOpenMPSingleExprClause().
ActOnOpenMPPriorityClause()
OMPClause * SemaOpenMP::ActOnOpenMPPriorityClause (Expr * Priority, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'priority' clause.
Definition at line 23150 of file SemaOpenMP.cpp.
References DSAStack, clang::SemaBase::getASTContext(), isNonNegativeIntegerValue(), Priority, and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPPrivateClause()
OMPClause * SemaOpenMP::ActOnOpenMPPrivateClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'private' clause.
Definition at line 18487 of file SemaOpenMP.cpp.
References clang::Sema::ActOnUninitializedDecl(), buildCapture(), buildDeclRefExpr(), buildVarDecl(), clang::OMPPrivateClause::Create(), clang::Sema::CurContext, clang::VarDecl::DeclarationOnly, clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::Decl::getAttrs(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::QualType::getNonReferenceType(), getPrivateItem(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), clang::Decl::hasAttrs(), clang::Type::isAnyPointerType(), clang::DeclContext::isDependentContext(), clang::SourceLocation::isInvalid(), clang::Decl::isInvalidDecl(), clang::isOpenMPTargetExecutionDirective(), clang::isOpenMPTaskingDirective(), clang::Type::isVariablyModifiedType(), rejectConstNotMutableType(), reportOriginalDsa(), clang::Sema::RequireCompleteType(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPProcBindClause()
OMPClause * SemaOpenMP::ActOnOpenMPProcBindClause (llvm::omp::ProcBindKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'proc_bind' clause.
Definition at line 17255 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), and getListOfPossibleValues().
Referenced by ActOnOpenMPSimpleClause().
ActOnOpenMPReadClause()
OMPClause * SemaOpenMP::ActOnOpenMPReadClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'read' clause.
Definition at line 17885 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPReductionClause()
OMPClause * SemaOpenMP::ActOnOpenMPReductionClause (ArrayRef< Expr * > VarList, OpenMPReductionClauseModifier Modifier, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ModifierLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec & ReductionIdScopeSpec, const DeclarationNameInfo & ReductionId, ArrayRef< Expr * > UnresolvedReductions = std::nullopt)
Called on well-formed 'reduction' clause.
Definition at line 20329 of file SemaOpenMP.cpp.
References actOnOMPReductionKindClause(), buildPostUpdate(), buildPreInits(), clang::OMPReductionClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), getListOfPossibleValues(), clang::CXXScopeSpec::getWithLocInContext(), clang::SourceLocation::isValid(), clang::OMPC_REDUCTION_unknown, and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPRegionEnd()
StmtResult SemaOpenMP::ActOnOpenMPRegionEnd (StmtResult S, ArrayRef< OMPClause * > Clauses)
End of OpenMP region.
Parameters
S Statement associated with the current OpenMP region.
Clauses List of clauses for the current OpenMP region.
Returns
Statement for finished OpenMP region.
Definition at line 4835 of file SemaOpenMP.cpp.
ActOnOpenMPRegionStart()
void SemaOpenMP::ActOnOpenMPRegionStart (OpenMPDirectiveKind DKind, Scope * CurScope)
Initialization of captured region for OpenMP region.
Definition at line 4211 of file SemaOpenMP.cpp.
ActOnOpenMPRelaxedClause()
OMPClause * SemaOpenMP::ActOnOpenMPRelaxedClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'relaxed' clause.
Definition at line 17949 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPReleaseClause()
OMPClause * SemaOpenMP::ActOnOpenMPReleaseClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'release' clause.
Definition at line 17944 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPRequiresDirective()
SemaOpenMP::DeclGroupPtrTy SemaOpenMP::ActOnOpenMPRequiresDirective (SourceLocation Loc, ArrayRef< OMPClause * > ClauseList)
Called on well-formed '#pragma omp requires'.
Definition at line 3488 of file SemaOpenMP.cpp.
References clang::DeclContext::addDecl(), CheckOMPRequiresDecl(), clang::Sema::CurContext, clang::SemaBase::Diag(), DSAStack, clang::DeclContext::isFileContext(), clang::OpaquePtr< PtrTy >::make(), and clang::SemaBase::SemaRef.
ActOnOpenMPReverseOffloadClause()
OMPClause * SemaOpenMP::ActOnOpenMPReverseOffloadClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'reverse_offload' clause.
Definition at line 17985 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPSafelenClause()
OMPClause * SemaOpenMP::ActOnOpenMPSafelenClause (Expr * Length, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'safelen' clause.
Definition at line 16930 of file SemaOpenMP.cpp.
References clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), and VerifyPositiveIntegerConstantInClause().
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPScanDirective()
StmtResult SemaOpenMP::ActOnOpenMPScanDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp scan'.
Definition at line 11580 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), and clang::StmtError().
ActOnOpenMPScheduleClause()
OMPClause * SemaOpenMP::ActOnOpenMPScheduleClause (OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2, OpenMPScheduleClauseKind Kind, Expr * ChunkSize, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation M1Loc, SourceLocation M2Loc, SourceLocation KindLoc, SourceLocation CommaLoc, SourceLocation EndLoc)
Called on well-formed 'schedule' clause.
Definition at line 17623 of file SemaOpenMP.cpp.
References buildPreInits(), checkScheduleModifiers(), clang::Expr::containsUnexpandedParameterPack(), clang::Sema::CurContext, clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::Stmt::getBeginLoc(), clang::Expr::getIntegerConstantExpr(), clang::SemaBase::getLangOpts(), getListOfPossibleValues(), getOpenMPCaptureRegionForClause(), clang::getOpenMPSimpleClauseTypeName(), clang::Stmt::getSourceRange(), clang::DeclContext::isDependentContext(), clang::Expr::isInstantiationDependent(), clang::SourceLocation::isInvalid(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::Sema::MakeFullExpr(), clang::OMPC_SCHEDULE_MODIFIER_last, clang::OMPC_SCHEDULE_MODIFIER_unknown, clang::OMPC_SCHEDULE_unknown, PerformOpenMPImplicitIntegerConversion(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprWithArgClause().
ActOnOpenMPScopeDirective()
StmtResult SemaOpenMP::ActOnOpenMPScopeDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp scope' after parsing of the associated statement.
Definition at line 24250 of file SemaOpenMP.cpp.
References clang::OMPScopeDirective::Create(), clang::SemaBase::getASTContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPSectionDirective()
StmtResult SemaOpenMP::ActOnOpenMPSectionDirective (Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp section' after parsing of the associated statement.
Definition at line 10781 of file SemaOpenMP.cpp.
References clang::OMPSectionDirective::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPSectionsDirective()
StmtResult SemaOpenMP::ActOnOpenMPSectionsDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp sections' after parsing of the associated statement.
Definition at line 10743 of file SemaOpenMP.cpp.
References clang::CapturedStmt::getCapturedStmt(), and clang::StmtError().
ActOnOpenMPSeqCstClause()
OMPClause * SemaOpenMP::ActOnOpenMPSeqCstClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'seq_cst' clause.
Definition at line 17929 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPSeverityClause()
OMPClause * SemaOpenMP::ActOnOpenMPSeverityClause (OpenMPSeverityClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'severity' clause.
Definition at line 17314 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), getListOfPossibleValues(), and clang::OMPC_SEVERITY_unknown.
Referenced by ActOnOpenMPSimpleClause().
ActOnOpenMPSharedClause()
OMPClause * SemaOpenMP::ActOnOpenMPSharedClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'shared' clause.
Definition at line 19108 of file SemaOpenMP.cpp.
References buildCapture(), clang::OMPSharedClause::Create(), clang::Sema::CurContext, clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), getPrivateItem(), clang::DeclContext::isDependentContext(), isOpenMPCapturedDecl(), reportOriginalDsa(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPSIMDClause()
OMPClause * SemaOpenMP::ActOnOpenMPSIMDClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'simd' clause.
Definition at line 17964 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp simd' after parsing of the associated statement.
Definition at line 10620 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPSimdlenClause()
OMPClause * SemaOpenMP::ActOnOpenMPSimdlenClause (Expr * Length, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'simdlen' clause.
Definition at line 16944 of file SemaOpenMP.cpp.
References clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::ActionResult< PtrTy, Compress >::isInvalid(), and VerifyPositiveIntegerConstantInClause().
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPSimpleClause()
OMPClause * SemaOpenMP::ActOnOpenMPSimpleClause (OpenMPClauseKind Kind, unsigned Argument, SourceLocation ArgumentLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Definition at line 17079 of file SemaOpenMP.cpp.
References ActOnOpenMPAtClause(), ActOnOpenMPAtomicDefaultMemOrderClause(), ActOnOpenMPBindClause(), ActOnOpenMPDefaultClause(), ActOnOpenMPFailClause(), ActOnOpenMPProcBindClause(), ActOnOpenMPSeverityClause(), and ActOnOpenMPUpdateClause().
ActOnOpenMPSingleDirective()
StmtResult SemaOpenMP::ActOnOpenMPSingleDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp single' after parsing of the associated statement.
Definition at line 11110 of file SemaOpenMP.cpp.
References clang::OMPSingleDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::OMPClause::getBeginLoc(), clang::OMPClause::getClauseKind(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPSingleExprClause()
OMPClause * SemaOpenMP::ActOnOpenMPSingleExprClause (OpenMPClauseKind Kind, Expr * Expr, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Definition at line 15609 of file SemaOpenMP.cpp.
References ActOnOpenMPAlignClause(), ActOnOpenMPAllocatorClause(), ActOnOpenMPCollapseClause(), ActOnOpenMPDepobjClause(), ActOnOpenMPDetachClause(), ActOnOpenMPFilterClause(), ActOnOpenMPFinalClause(), ActOnOpenMPHintClause(), ActOnOpenMPMessageClause(), ActOnOpenMPNocontextClause(), ActOnOpenMPNovariantsClause(), ActOnOpenMPNumTeamsClause(), ActOnOpenMPNumThreadsClause(), ActOnOpenMPOrderedClause(), ActOnOpenMPPartialClause(), ActOnOpenMPPriorityClause(), ActOnOpenMPSafelenClause(), ActOnOpenMPSimdlenClause(), ActOnOpenMPThreadLimitClause(), and ActOnOpenMPXDynCGroupMemClause().
ActOnOpenMPSingleExprWithArgClause()
OMPClause * SemaOpenMP::ActOnOpenMPSingleExprWithArgClause (OpenMPClauseKind Kind, ArrayRef< unsigned > Arguments, Expr * Expr, SourceLocation StartLoc, SourceLocation LParenLoc, ArrayRef< SourceLocation > ArgumentsLoc, SourceLocation DelimLoc, SourceLocation EndLoc)
Definition at line 17455 of file SemaOpenMP.cpp.
References ActOnOpenMPDefaultmapClause(), ActOnOpenMPDeviceClause(), ActOnOpenMPDistScheduleClause(), ActOnOpenMPGrainsizeClause(), ActOnOpenMPIfClause(), ActOnOpenMPNumTasksClause(), ActOnOpenMPOrderClause(), and ActOnOpenMPScheduleClause().
ActOnOpenMPSizesClause()
OMPClause * SemaOpenMP::ActOnOpenMPSizesClause (ArrayRef< Expr * > SizeExprs, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-form 'sizes' clause.
Definition at line 17405 of file SemaOpenMP.cpp.
References clang::OMPSizesClause::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::ActionResult< PtrTy, Compress >::isUsable(), and VerifyPositiveIntegerConstantInClause().
ActOnOpenMPTargetDataDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetDataDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp target data' after parsing of the associated statement.
Definition at line 13543 of file SemaOpenMP.cpp.
References clang::OMPTargetDataDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), hasClauses(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPTargetDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp target' after parsing of the associated statement.
Definition at line 13358 of file SemaOpenMP.cpp.
References DSAStack, clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getOpenMPCaptureLevels(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetEnterDataDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetEnterDataDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, Stmt * AStmt)
Called on well-formed '#pragma omp target enter data' after parsing of the associated statement.
Definition at line 13573 of file SemaOpenMP.cpp.
References clang::OMPTargetEnterDataDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getOpenMPCaptureLevels(), hasClauses(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetExitDataDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetExitDataDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, Stmt * AStmt)
Called on well-formed '#pragma omp target exit data' after parsing of the associated statement.
Definition at line 13609 of file SemaOpenMP.cpp.
References clang::OMPTargetExitDataDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getOpenMPCaptureLevels(), hasClauses(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetParallelDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetParallelDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp target parallel' after parsing of the associated statement.
Definition at line 13424 of file SemaOpenMP.cpp.
References clang::OMPTargetParallelDirective::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getOpenMPCaptureLevels(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetParallelForDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target parallel for' after parsing of the associated statement.
Definition at line 13455 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPTargetParallelForDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetParallelForSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target parallel for simd' after parsing of the associated statement.
Definition at line 14471 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPTargetParallelForSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetParallelGenericLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetParallelGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target parallel loop' after parsing of the associated statement.
Definition at line 11061 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkGenericLoopLastprivate(), checkOpenMPLoop(), clang::OMPTargetParallelGenericLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target simd' after parsing of the associated statement.
Definition at line 14527 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPTargetSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), getOrderedNumberExpr(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetTeamsDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetTeamsDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp target teams' after parsing of the associated statement.
Definition at line 14800 of file SemaOpenMP.cpp.
References clang::OMPTargetTeamsDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::OMPClause::getBeginLoc(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getOpenMPCaptureLevels(), hasClauses(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetTeamsDistributeDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetTeamsDistributeDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams distribute' after parsing of the associated statement.
Definition at line 14843 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPTargetTeamsDistributeDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetTeamsDistributeParallelForDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams distribute parallel for' after parsing of the associated statement.
Definition at line 14886 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPTargetTeamsDistributeParallelForDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams distribute parallel for simd' after parsing of the associated statement.
Definition at line 14941 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPTargetTeamsDistributeParallelForSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetTeamsDistributeSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetTeamsDistributeSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams distribute simd' after parsing of the associated statement.
Definition at line 15000 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPTargetTeamsDistributeSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTargetTeamsGenericLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetTeamsGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp target teams loop' after parsing of the associated statement.
Definition at line 10962 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkGenericLoopLastprivate(), checkOpenMPLoop(), clang::OMPTargetTeamsGenericLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), clang::StmtError(), and teamsLoopCanBeParallelFor().
ActOnOpenMPTargetUpdateDirective()
StmtResult SemaOpenMP::ActOnOpenMPTargetUpdateDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc, Stmt * AStmt)
Called on well-formed '#pragma omp target update'.
Definition at line 13645 of file SemaOpenMP.cpp.
References clang::OMPTargetUpdateDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getOpenMPCaptureLevels(), hasClauses(), isClauseMappable(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTaskDirective()
StmtResult SemaOpenMP::ActOnOpenMPTaskDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp task' after parsing of the associated statement.
Definition at line 11416 of file SemaOpenMP.cpp.
References checkMutuallyExclusiveClauses(), clang::OMPTaskDirective::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTaskgroupDirective()
StmtResult SemaOpenMP::ActOnOpenMPTaskgroupDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp taskgroup'.
Definition at line 11504 of file SemaOpenMP.cpp.
References clang::OMPTaskgroupDirective::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPTaskLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPTaskLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp taskloop' after parsing of the associated statement.
Definition at line 13768 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), clang::OMPTaskLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPTaskLoopSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp taskloop simd' after parsing of the associated statement.
Definition at line 13806 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkMutuallyExclusiveClauses(), checkOpenMPLoop(), checkReductionClauseWithNogroup(), checkSimdlenSafelenSpecified(), clang::OMPTaskLoopSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), getCollapseNumberExpr(), clang::Sema::getCurScope(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), and clang::StmtError().
ActOnOpenMPTaskReductionClause()
OMPClause * SemaOpenMP::ActOnOpenMPTaskReductionClause (ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec & ReductionIdScopeSpec, const DeclarationNameInfo & ReductionId, ArrayRef< Expr * > UnresolvedReductions = std::nullopt)
Called on well-formed 'task_reduction' clause.
Definition at line 20374 of file SemaOpenMP.cpp.
References actOnOMPReductionKindClause(), buildPostUpdate(), buildPreInits(), clang::OMPTaskReductionClause::Create(), DSAStack, clang::SemaBase::getASTContext(), clang::CXXScopeSpec::getWithLocInContext(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPTaskwaitDirective()
StmtResult SemaOpenMP::ActOnOpenMPTaskwaitDirective (ArrayRef< OMPClause * > Clauses, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp taskwait'.
Definition at line 11486 of file SemaOpenMP.cpp.
References clang::OMPTaskwaitDirective::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), and clang::StmtError().
ActOnOpenMPTaskyieldDirective()
StmtResult SemaOpenMP::ActOnOpenMPTaskyieldDirective (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp taskyield'.
Definition at line 11444 of file SemaOpenMP.cpp.
References clang::OMPTaskyieldDirective::Create(), and clang::SemaBase::getASTContext().
ActOnOpenMPTeamsDirective()
StmtResult SemaOpenMP::ActOnOpenMPTeamsDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp teams' after parsing of the associated statement.
Definition at line 13683 of file SemaOpenMP.cpp.
References clang::OMPTeamsDirective::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::SemaBase::getLangOpts(), clang::HIP, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTeamsDistributeDirective()
StmtResult SemaOpenMP::ActOnOpenMPTeamsDistributeDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams distribute' after parsing of the associated statement.
Definition at line 14583 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPTeamsDistributeDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTeamsDistributeParallelForDirective()
StmtResult SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams distribute parallel for' after parsing of the associated statement.
Definition at line 14751 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), clang::OMPTeamsDistributeParallelForDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTeamsDistributeParallelForSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams distribute parallel for simd' after parsing of the associated statement.
Definition at line 14689 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPTeamsDistributeParallelForSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTeamsDistributeSimdDirective()
StmtResult SemaOpenMP::ActOnOpenMPTeamsDistributeSimdDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams distribute simd' after parsing of the associated statement.
Definition at line 14628 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkOpenMPLoop(), checkSimdlenSafelenSpecified(), clang::OMPTeamsDistributeSimdDirective::Create(), clang::Sema::CurContext, DSAStack, FinishOpenMPLinearClause(), clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), clang::Sema::getCurScope(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::OMPLoopBasedDirective::HelperExprs::IterationVarRef, clang::OMPLoopBasedDirective::HelperExprs::NumIterations, clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPTeamsGenericLoopDirective()
StmtResult SemaOpenMP::ActOnOpenMPTeamsGenericLoopDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc, VarsWithInheritedDSAType & VarsWithImplicitDSA)
Called on well-formed '#pragma omp teams loop' after parsing of the associated statement.
Definition at line 10913 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::HelperExprs::builtAll(), checkGenericLoopLastprivate(), checkOpenMPLoop(), clang::OMPTeamsGenericLoopDirective::Create(), clang::Sema::CurContext, DSAStack, clang::SemaBase::getASTContext(), clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), getCollapseNumberExpr(), getOpenMPCaptureLevels(), clang::DeclContext::isDependentContext(), clang::SemaBase::SemaRef, clang::Sema::setFunctionHasBranchProtectedScope(), clang::CapturedDecl::setNothrow(), and clang::StmtError().
ActOnOpenMPThreadLimitClause()
OMPClause * SemaOpenMP::ActOnOpenMPThreadLimitClause (Expr * ThreadLimit, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'thread_limit' clause.
Definition at line 23122 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CurContext, DSAStack, clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), isNonNegativeIntegerValue(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnOpenMPThreadprivateDirective()
SemaOpenMP::DeclGroupPtrTy SemaOpenMP::ActOnOpenMPThreadprivateDirective (SourceLocation Loc, ArrayRef< Expr * > VarList)
Called on well-formed '#pragma omp threadprivate'.
Definition at line 3190 of file SemaOpenMP.cpp.
References clang::DeclContext::addDecl(), CheckOMPThreadPrivateDecl(), clang::Sema::CurContext, clang::OpaquePtr< PtrTy >::make(), and clang::SemaBase::SemaRef.
ActOnOpenMPThreadsClause()
OMPClause * SemaOpenMP::ActOnOpenMPThreadsClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'threads' clause.
Definition at line 17959 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPTileDirective()
StmtResult SemaOpenMP::ActOnOpenMPTileDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp tile' after parsing of its clauses and the associated statement.
Definition at line 15106 of file SemaOpenMP.cpp.
ActOnOpenMPToClause()
OMPClause * SemaOpenMP::ActOnOpenMPToClause (ArrayRef< OpenMPMotionModifierKind > MotionModifiers, ArrayRef< SourceLocation > MotionModifiersLoc, CXXScopeSpec & MapperIdScopeSpec, DeclarationNameInfo & MapperId, SourceLocation ColonLoc, ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs, ArrayRef< Expr * > UnresolvedMappers = std::nullopt)
Called on well-formed 'to' clause.
Definition at line 23762 of file SemaOpenMP.cpp.
References checkMappableExpressionList(), clang::OMPToClause::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::CXXScopeSpec::getWithLocInContext(), clang::NumberOfOMPMotionModifiers, clang::OMPC_MOTION_MODIFIER_unknown, clang::SemaBase::SemaRef, and clang::OMPVarListLocTy::StartLoc.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPUnifiedAddressClause()
OMPClause * SemaOpenMP::ActOnOpenMPUnifiedAddressClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'unified_address' clause.
Definition at line 17974 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPUnifiedSharedMemoryClause()
OMPClause * SemaOpenMP::ActOnOpenMPUnifiedSharedMemoryClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'unified_address' clause.
Definition at line 17980 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPUnrollDirective()
StmtResult SemaOpenMP::ActOnOpenMPUnrollDirective (ArrayRef< OMPClause * > Clauses, Stmt * AStmt, SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed '#pragma omp unroll' after parsing of its clauses and the associated statement.
Definition at line 15323 of file SemaOpenMP.cpp.
ActOnOpenMPUntiedClause()
OMPClause * SemaOpenMP::ActOnOpenMPUntiedClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'untied' clause.
Definition at line 17874 of file SemaOpenMP.cpp.
References DSAStack, and clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPUpdateClause() [1/2]
OMPClause * SemaOpenMP::ActOnOpenMPUpdateClause (OpenMPDependClauseKind Kind, SourceLocation KindLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'update' clause.
Definition at line 17383 of file SemaOpenMP.cpp.
References clang::OMPUpdateClause::Create(), clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getListOfPossibleValues(), and clang::OMPC_DEPEND_unknown.
Referenced by ActOnOpenMPClause(), and ActOnOpenMPSimpleClause().
ActOnOpenMPUpdateClause() [2/2]
OMPClause * SemaOpenMP::ActOnOpenMPUpdateClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'update' clause.
Definition at line 17895 of file SemaOpenMP.cpp.
References clang::OMPUpdateClause::Create(), and clang::SemaBase::getASTContext().
ActOnOpenMPUseClause()
OMPClause * SemaOpenMP::ActOnOpenMPUseClause (Expr * InteropVar, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation VarLoc, SourceLocation EndLoc)
Called on well-formed 'use' clause.
Definition at line 18153 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext(), isValidInteropVariable(), and clang::SemaBase::SemaRef.
ActOnOpenMPUseDeviceAddrClause()
OMPClause * SemaOpenMP::ActOnOpenMPUseDeviceAddrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs)
Called on well-formed 'use_device_addr' clause.
Definition at line 23923 of file SemaOpenMP.cpp.
References buildCapture(), clang::OMPUseDeviceAddrClause::Create(), clang::Sema::DefaultFunctionArrayLvalueConversion(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), getPrivateItem(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPUseDevicePtrClause()
OMPClause * SemaOpenMP::ActOnOpenMPUseDevicePtrClause (ArrayRef< Expr * > VarList, const OMPVarListLocTy & Locs)
Called on well-formed 'use_device_ptr' clause.
Definition at line 23837 of file SemaOpenMP.cpp.
References clang::DeclContext::addDecl(), clang::Sema::AddInitializerToDecl(), buildCapture(), buildDeclRefExpr(), buildVarDecl(), clang::OMPUseDevicePtrClause::Create(), clang::Sema::CurContext, clang::Sema::DefaultLvalueConversion(), clang::SemaBase::Diag(), DSAStack, clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getASTContext(), clang::Decl::getAttrs(), clang::NamedDecl::getName(), getPrivateItem(), clang::ValueDecl::getType(), clang::Decl::hasAttrs(), clang::Type::isPointerType(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPVarListClause().
ActOnOpenMPUsesAllocatorClause()
OMPClause * SemaOpenMP::ActOnOpenMPUsesAllocatorClause (SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< UsesAllocatorsData > Data)
Called on well-formed 'uses_allocators' clause.
Definition at line 24363 of file SemaOpenMP.cpp.
ActOnOpenMPVarListClause()
OMPClause * SemaOpenMP::ActOnOpenMPVarListClause (OpenMPClauseKind Kind, ArrayRef< Expr * > Vars, const OMPVarListLocTy & Locs, OpenMPVarListDataTy & Data)
Definition at line 18272 of file SemaOpenMP.cpp.
References ActOnOpenMPAffinityClause(), ActOnOpenMPAlignedClause(), ActOnOpenMPAllocateClause(), ActOnOpenMPCopyinClause(), ActOnOpenMPCopyprivateClause(), ActOnOpenMPDependClause(), ActOnOpenMPDoacrossClause(), ActOnOpenMPExclusiveClause(), ActOnOpenMPFirstprivateClause(), ActOnOpenMPFlushClause(), ActOnOpenMPFromClause(), ActOnOpenMPHasDeviceAddrClause(), ActOnOpenMPInclusiveClause(), ActOnOpenMPInReductionClause(), ActOnOpenMPIsDevicePtrClause(), ActOnOpenMPLastprivateClause(), ActOnOpenMPLinearClause(), ActOnOpenMPMapClause(), ActOnOpenMPNontemporalClause(), ActOnOpenMPPrivateClause(), ActOnOpenMPReductionClause(), ActOnOpenMPSharedClause(), ActOnOpenMPTaskReductionClause(), ActOnOpenMPToClause(), ActOnOpenMPUseDeviceAddrClause(), ActOnOpenMPUseDevicePtrClause(), Data, clang::OMPVarListLocTy::EndLoc, clang::OMPVarListLocTy::LParenLoc, clang::OMPC_DEPEND_unknown, clang::OMPC_LASTPRIVATE_unknown, clang::OMPC_LINEAR_unknown, clang::OMPC_MAP_unknown, clang::OMPC_REDUCTION_unknown, and clang::OMPVarListLocTy::StartLoc.
ActOnOpenMPWeakClause()
OMPClause * SemaOpenMP::ActOnOpenMPWeakClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'weak' clause.
Definition at line 17954 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPWhenClause()
OMPClause* clang::SemaOpenMP::ActOnOpenMPWhenClause (OMPTraitInfo & TI, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on well-formed 'when' clause.
ActOnOpenMPWriteClause()
OMPClause * SemaOpenMP::ActOnOpenMPWriteClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on well-formed 'write' clause.
Definition at line 17890 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPXAttributeClause()
OMPClause * SemaOpenMP::ActOnOpenMPXAttributeClause (ArrayRef< const Attr * > Attrs, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on a well-formed 'ompx_attribute' clause.
Definition at line 24618 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
ActOnOpenMPXBareClause()
OMPClause * SemaOpenMP::ActOnOpenMPXBareClause (SourceLocation StartLoc, SourceLocation EndLoc)
Called on a well-formed 'ompx_bare' clause.
Definition at line 24626 of file SemaOpenMP.cpp.
References clang::SemaBase::getASTContext().
Referenced by ActOnOpenMPClause().
ActOnOpenMPXDynCGroupMemClause()
OMPClause * SemaOpenMP::ActOnOpenMPXDynCGroupMemClause (Expr * Size, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Called on a well-formed 'ompx_dyn_cgroup_mem' clause.
Definition at line 24554 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::CurContext, DSAStack, clang::Sema::FullExprArg::get(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), getOpenMPCaptureRegionForClause(), clang::DeclContext::isDependentContext(), isNonNegativeIntegerValue(), clang::Sema::MakeFullExpr(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPSingleExprClause().
ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope()
void SemaOpenMP::ActOnStartOfFunctionDefinitionInOpenMPDeclareVariantScope (Scope * S, Declarator & D, MultiTemplateParamsArg TemplateParameterLists, SmallVectorImpl< FunctionDecl * > & Bases)
The declarator D defines a function in the scope S which is nested in an omp begin/end declare variant scope.
In this method we create a declaration for D and rename D according to the OpenMP context selector of the surrounding scope. Return all base functions in Bases.
Definition at line 7394 of file SemaOpenMP.cpp.
ActOnStartOpenMPDeclareTargetContext()
bool SemaOpenMP::ActOnStartOpenMPDeclareTargetContext (DeclareTargetContextInfo & DTCI)
Called on the start of target region i.e. '#pragma omp declare target'.
Definition at line 23457 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::Sema::getCurLexicalContext(), clang::SemaBase::getLangOpts(), clang::HIP, clang::DeclContext::isExternCContext(), clang::DeclContext::isExternCXXContext(), clang::DeclContext::isFileContext(), clang::SemaOpenMP::DeclareTargetContextInfo::Loc, and clang::SemaBase::SemaRef.
checkDeclIsAllowedInOpenMPTarget()
void SemaOpenMP::checkDeclIsAllowedInOpenMPTarget (Expr * E, Decl * D, SourceLocation IdLoc = SourceLocation())
Check declaration inside target region.
Definition at line 23642 of file SemaOpenMP.cpp.
References clang::Decl::addAttr(), checkDeclInTargetContext(), checkValueDeclInTarget(), clang::SemaBase::Diag(), DSAStack, clang::SemaOpenMP::DeclareTargetContextInfo::DT, clang::SemaBase::getASTContext(), clang::Stmt::getBeginLoc(), clang::Expr::getExprLoc(), clang::SemaBase::getLangOpts(), clang::Decl::getLocation(), clang::Decl::getSourceRange(), clang::Stmt::getSourceRange(), clang::ValueDecl::getType(), clang::SemaOpenMP::DeclareTargetContextInfo::Indirect, clang::Type::isIncompleteType(), isInOpenMPDeclareTargetContext(), clang::Decl::isInvalidDecl(), clang::SourceLocation::isValid(), clang::SemaOpenMP::DeclareTargetContextInfo::Loc, reportOriginalDsa(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPDeclareTargetName(), lookupOpenMPDeclareTargetName(), and MarkExprReferenced().
CheckOMPRequiresDecl()
OMPRequiresDecl * SemaOpenMP::CheckOMPRequiresDecl (SourceLocation Loc, ArrayRef< OMPClause * > Clauses)
Check restrictions on Requires directive.
For target specific clauses, the requires directive cannot be specified after the handling of any of the target regions in the current compilation unit.
Definition at line 3562 of file SemaOpenMP.cpp.
References clang::OMPRequiresDecl::Create(), clang::SemaBase::Diag(), DSAStack, clang::SemaBase::getASTContext(), clang::Sema::getCurLexicalContext(), clang::SourceLocation::isInvalid(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPRequiresDirective().
CheckOMPThreadPrivateDecl()
OMPThreadPrivateDecl * SemaOpenMP::CheckOMPThreadPrivateDecl (SourceLocation Loc, ArrayRef< Expr * > VarList)
Builds a new OpenMPThreadPrivateDecl and checks its correctness.
Definition at line 3230 of file SemaOpenMP.cpp.
Referenced by ActOnOpenMPThreadprivateDirective().
checkOpenMPDeclareVariantFunction()
std::optional< std::pair< FunctionDecl *, Expr * > > SemaOpenMP::checkOpenMPDeclareVariantFunction (SemaOpenMP::DeclGroupPtrTy DG, Expr * VariantRef, OMPTraitInfo & TI, unsigned NumAppendArgs, SourceRange SR)
Checks '#pragma omp declare variant' variant function and original functions after parsing of the associated method/function.
Parameters
DG Function declaration to which declare variant directive is applied to.
VariantRef Expression that references the variant function, which must be used instead of the original one, specified in DG.
TI The trait info object representing the match clause.
NumAppendArgs The number of omp_interop_t arguments to account for in checking.
Returns
std::nullopt, if the function/variant function are not compatible with the pragma, pair of original function/variant ref expression otherwise.
Definition at line 7621 of file SemaOpenMP.cpp.
CheckOpenMPLinearDecl()
bool SemaOpenMP::CheckOpenMPLinearDecl (const ValueDecl * D, SourceLocation ELoc, OpenMPLinearClauseKind LinKind, QualType Type, bool IsDeclareSimd = false)
Checks that the specified declaration matches requirements for the linear decls.
Definition at line 20425 of file SemaOpenMP.cpp.
References clang::VarDecl::DeclarationOnly, clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::Decl::getLocation(), clang::getOpenMPSimpleClauseTypeName(), clang::Type::isReferenceType(), rejectConstNotMutableType(), clang::Sema::RequireCompleteType(), and clang::SemaBase::SemaRef.
Referenced by ActOnOpenMPDeclareSimdDirective(), and ActOnOpenMPLinearClause().
CheckOpenMPLinearModifier()
bool SemaOpenMP::CheckOpenMPLinearModifier (OpenMPLinearClauseKind LinKind, SourceLocation LinLoc)
Checks correctness of linear modifiers.
Definition at line 20414 of file SemaOpenMP.cpp.
References clang::CPlusPlus, clang::SemaBase::Diag(), clang::SemaBase::getLangOpts(), and clang::OMPC_LINEAR_unknown.
Referenced by ActOnOpenMPLinearClause().
diagIfOpenMPDeviceCode()
SemaBase::SemaDiagnosticBuilder SemaOpenMP::diagIfOpenMPDeviceCode (SourceLocation Loc, unsigned DiagID, const FunctionDecl * FD)
Creates a SemaDiagnosticBuilder that emits the diagnostic if the current context is "used as device code".
If CurContext is a declare target function or it is known that the function is emitted for the device, emits the diagnostics immediately.
If CurContext is a non-declare target function and we are compiling for the device, creates a diagnostic which is emitted if and when we realize that the function will be codegen'ed.
Example usage:
// Variable-length arrays are not allowed in NVPTX device code. if (diagIfOpenMPDeviceCode(Loc, diag::err_vla_unsupported)) return ExprError(); // Otherwise, continue parsing as normal.
Definition at line 2051 of file SemaOpenMP.cpp.
References clang::Sema::CUDADiscarded, clang::Sema::Emitted, clang::Sema::getEmissionStatus(), isOpenMPDeviceDelayedContext(), clang::Sema::OMPDiscarded, clang::Sema::TemplateDiscarded, and clang::Sema::Unknown.
diagIfOpenMPHostCode()
SemaBase::SemaDiagnosticBuilder SemaOpenMP::diagIfOpenMPHostCode (SourceLocation Loc, unsigned DiagID, const FunctionDecl * FD)
Creates a SemaDiagnosticBuilder that emits the diagnostic if the current context is "used as host code".
If CurContext is a declare target function or it is known that the function is emitted for the host, emits the diagnostics immediately.
If CurContext is a non-host function, just ignore it.
Example usage:
// Variable-length arrays are not allowed in NVPTX device code. if (diagIfOpenMPHostode(Loc, diag::err_vla_unsupported)) return ExprError(); // Otherwise, continue parsing as normal.
Definition at line 2090 of file SemaOpenMP.cpp.
References clang::Sema::CUDADiscarded, clang::Sema::Emitted, clang::Sema::getEmissionStatus(), clang::Sema::OMPDiscarded, clang::Sema::TemplateDiscarded, and clang::Sema::Unknown.
DiagnoseUnterminatedOpenMPDeclareTarget()
void SemaOpenMP::DiagnoseUnterminatedOpenMPDeclareTarget ()
Report unterminated 'omp declare target' or 'omp begin declare target' at the end of a compilation unit.
Definition at line 23492 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::SemaOpenMP::DeclareTargetContextInfo::Kind, and clang::SemaOpenMP::DeclareTargetContextInfo::Loc.
Referenced by clang::Sema::ActOnEndOfTranslationUnit().
EndOpenMPClause()
void SemaOpenMP::EndOpenMPClause ()
End analysis of clauses.
Definition at line 2798 of file SemaOpenMP.cpp.
References clang::Sema::CleanupVarDeclMarking(), DSAStack, and clang::SemaBase::SemaRef.
EndOpenMPDSABlock()
void SemaOpenMP::EndOpenMPDSABlock (Stmt * CurDirective)
Called on end of data sharing attribute block.
Definition at line 2884 of file SemaOpenMP.cpp.
References clang::Sema::ActOnUninitializedDecl(), clang::OMPUsesAllocatorsClause::Data::Allocator, buildDeclRefExpr(), buildVarDecl(), checkAllocateClauses(), checkReductionClauses(), clang::Sema::CurContext, clang::SemaBase::Diag(), DSAStack, clang::Decl::getAttrs(), clang::NamedDecl::getName(), clang::QualType::getNonReferenceType(), getPrivateItem(), clang::Decl::getSourceRange(), clang::ValueDecl::getType(), clang::Decl::hasAttrs(), clang::Expr::IgnoreParenImpCasts(), clang::DeclContext::isDependentContext(), clang::Decl::isInvalidDecl(), reportOriginalDsa(), and clang::SemaBase::SemaRef.
finalizeOpenMPDelayedAnalysis()
void SemaOpenMP::finalizeOpenMPDelayedAnalysis (const FunctionDecl * Caller, const FunctionDecl * Callee, SourceLocation Loc)
Finishes analysis of the deferred functions calls that may be declared as host/nohost during device/host compilation.
Definition at line 2728 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), clang::SemaBase::getLangOpts(), clang::Redeclarable< decl_type >::getMostRecentDecl(), and clang::getOpenMPSimpleClauseTypeName().
getOpenMPCapturedExpr()
ExprResult SemaOpenMP::getOpenMPCapturedExpr (VarDecl * Capture, ExprValueKind VK, ExprObjectKind OK, SourceLocation Loc)
Definition at line 18467 of file SemaOpenMP.cpp.
References clang::Sema::BuildDeclRefExpr(), clang::CPlusPlus, clang::Sema::CreateBuiltinUnaryOp(), clang::Sema::DefaultLvalueConversion(), clang::ExprError(), clang::ActionResult< PtrTy, Compress >::get(), clang::SemaBase::getLangOpts(), clang::Expr::isGLValue(), clang::ActionResult< PtrTy, Compress >::isUsable(), clang::OK_Ordinary, clang::SemaBase::SemaRef, and clang::VK_LValue.
getOpenMPCaptureLevels()
int SemaOpenMP::getOpenMPCaptureLevels (OpenMPDirectiveKind Kind) static
Return the number of captured regions created for an OpenMP directive.
Definition at line 4665 of file SemaOpenMP.cpp.
References clang::getOpenMPCaptureRegions().
Referenced by ActOnOpenMPDistributeParallelForDirective(), ActOnOpenMPDistributeParallelForSimdDirective(), ActOnOpenMPDistributeSimdDirective(), ActOnOpenMPExecutableDirective(), ActOnOpenMPParallelGenericLoopDirective(), ActOnOpenMPParallelMaskedTaskLoopDirective(), ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), ActOnOpenMPParallelMasterTaskLoopDirective(), ActOnOpenMPParallelMasterTaskLoopSimdDirective(), ActOnOpenMPTargetDirective(), ActOnOpenMPTargetEnterDataDirective(), ActOnOpenMPTargetExitDataDirective(), ActOnOpenMPTargetParallelDirective(), ActOnOpenMPTargetParallelForDirective(), ActOnOpenMPTargetParallelForSimdDirective(), ActOnOpenMPTargetParallelGenericLoopDirective(), ActOnOpenMPTargetSimdDirective(), ActOnOpenMPTargetTeamsDirective(), ActOnOpenMPTargetTeamsDistributeDirective(), ActOnOpenMPTargetTeamsDistributeParallelForDirective(), ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), ActOnOpenMPTargetTeamsDistributeSimdDirective(), ActOnOpenMPTargetTeamsGenericLoopDirective(), ActOnOpenMPTargetUpdateDirective(), ActOnOpenMPTeamsDistributeDirective(), ActOnOpenMPTeamsDistributeParallelForDirective(), ActOnOpenMPTeamsDistributeParallelForSimdDirective(), ActOnOpenMPTeamsDistributeSimdDirective(), ActOnOpenMPTeamsGenericLoopDirective(), and isOpenMPGlobalCapturedDecl().
getOpenMPDeclareMapperVarName()
const ValueDecl * SemaOpenMP::getOpenMPDeclareMapperVarName () const
Definition at line 23089 of file SemaOpenMP.cpp.
References DSAStack, and clang::SemaBase::getLangOpts().
hasGlobalOpenMPAssumes()
bool clang::SemaOpenMP::hasGlobalOpenMPAssumes () const inline
Check if there is an active global omp assumes directive.
Definition at line 244 of file SemaOpenMP.h.
isInOpenMPAssumeScope()
bool clang::SemaOpenMP::isInOpenMPAssumeScope () const inline
Check if there is an active global omp begin assumes directive.
Definition at line 241 of file SemaOpenMP.h.
Referenced by ActOnOpenMPEndAssumesDirective().
isInOpenMPDeclareTargetContext()
bool clang::SemaOpenMP::isInOpenMPDeclareTargetContext () const inline
Return true inside OpenMP declare target region.
Definition at line 369 of file SemaOpenMP.h.
Referenced by checkDeclIsAllowedInOpenMPTarget(), and MarkExprReferenced().
isInOpenMPDeclareVariantScope()
bool clang::SemaOpenMP::isInOpenMPDeclareVariantScope () const inline
Can we exit an OpenMP declare variant scope at the moment.
Definition at line 109 of file SemaOpenMP.h.
Referenced by ActOnOpenMPEndDeclareVariant().
isInOpenMPTargetExecutionDirective()
bool SemaOpenMP::isInOpenMPTargetExecutionDirective () const
Return true inside OpenMP target region.
Definition at line 2320 of file SemaOpenMP.cpp.
References DSAStack, and clang::isOpenMPTargetExecutionDirective().
Referenced by isOpenMPGlobalCapturedDecl().
isInOpenMPTaskUntiedContext()
bool SemaOpenMP::isInOpenMPTaskUntiedContext () const
Return true if currently in OpenMP task with untied clause context.
Definition at line 2315 of file SemaOpenMP.cpp.
References DSAStack, and clang::isOpenMPTaskingDirective().
Referenced by clang::Sema::BuildArrayType().
isOpenMPCapturedByRef()
bool SemaOpenMP::isOpenMPCapturedByRef (const ValueDecl * D, unsigned Level, unsigned OpenMPCaptureLevel) const
Return true if the provided declaration VD should be captured by reference.
Parameters
Level Relative level of nested OpenMP construct for that the check is performed.
OpenMPCaptureLevel Capture level within an OpenMP construct.
Definition at line 2131 of file SemaOpenMP.cpp.
References clang::Type::castAs(), DSAStack, clang::ASTContext::getAlignOfGlobalVarInChars(), clang::Decl::getCanonicalDecl(), clang::QualType::getNonReferenceType(), clang::ValueDecl::getType(), clang::ASTContext::getTypeAlignInChars(), clang::ASTContext::getTypeSizeInChars(), clang::ASTContext::getUIntPtrType(), getVariableCategoryFromDecl(), clang::Decl::hasAttr(), clang::Type::isAnyPointerType(), clang::isOpenMPTargetExecutionDirective(), clang::Type::isPointerType(), clang::Type::isReferenceType(), clang::Type::isScalarType(), and clang::Last.
isOpenMPCapturedDecl()
VarDecl * SemaOpenMP::isOpenMPCapturedDecl (ValueDecl * D, bool CheckScopeInfo = false, unsigned StopAt = 0)
Check if the specified variable is used in one of the private clauses (private, firstprivate, lastprivate, reduction etc.) in OpenMP constructs.
Definition at line 2354 of file SemaOpenMP.cpp.
References buildCaptureDecl(), clang::Sema::BuildCXXThisExpr(), buildDeclRefExpr(), clang::Sema::BuildMemberExpr(), clang::CR_OpenMP, clang::Sema::CurContext, DSAStack, clang::Sema::FunctionScopes, clang::Decl::getAccess(), getCanonicalDecl(), clang::Sema::getCurBlock(), clang::Sema::getCurCapturedRegion(), clang::Sema::getCurLambda(), clang::Sema::getCurrentThisType(), clang::DeclRefExpr::getDecl(), clang::NamedDecl::getIdentifier(), clang::QualType::getNonReferenceType(), clang::getOpenMPCaptureRegions(), clang::DeclContext::getParent(), clang::ValueDecl::getType(), clang::VarDecl::hasLocalStorage(), clang::VarDecl::isConstexpr(), clang::QualType::isNull(), clang::isOpenMPPrivate(), clang::isOpenMPThreadPrivate(), clang::DeclAccessPair::make(), clang::OK_Ordinary, clang::sema::CapturedRegionScopeInfo::OpenMPCaptureLevel, clang::sema::CapturedRegionScopeInfo::OpenMPLevel, and clang::VK_LValue.
Referenced by ActOnOpenMPAlignedClause(), ActOnOpenMPCopyprivateClause(), ActOnOpenMPFirstprivateClause(), ActOnOpenMPLastprivateClause(), ActOnOpenMPLinearClause(), ActOnOpenMPLoopInitialization(), and ActOnOpenMPSharedClause().
isOpenMPDeclareMapperVarDeclAllowed()
bool SemaOpenMP::isOpenMPDeclareMapperVarDeclAllowed (const VarDecl * VD) const
Definition at line 23074 of file SemaOpenMP.cpp.
References DSAStack, clang::SemaBase::getASTContext(), clang::Decl::getCanonicalDecl(), clang::VarDecl::getCanonicalDecl(), clang::DeclRefExpr::getDecl(), clang::SemaBase::getLangOpts(), and clang::VarDecl::isUsableInConstantExpressions().
isOpenMPGlobalCapturedDecl()
bool SemaOpenMP::isOpenMPGlobalCapturedDecl (ValueDecl * D, unsigned Level, unsigned CaptureLevel) const
Check if the specified global variable must be captured by outer capture regions.
Parameters
Level Relative level of nested OpenMP construct for that the check is performed.
Definition at line 2684 of file SemaOpenMP.cpp.
References DSAStack, clang::SemaBase::getLangOpts(), getOpenMPCaptureLevels(), clang::VarDecl::hasLocalStorage(), and isInOpenMPTargetExecutionDirective().
Referenced by clang::Sema::tryCaptureVariable().
isOpenMPPrivateDecl()
OpenMPClauseKind SemaOpenMP::isOpenMPPrivateDecl (ValueDecl * D, unsigned Level, unsigned CapLevel) const
Check if the specified variable is used in 'private' clause.
Parameters
Level Relative level of nested OpenMP construct for that the check is performed.
Definition at line 2534 of file SemaOpenMP.cpp.
References DSAStack, clang::Type::getAsCXXRecordDecl(), clang::Decl::getCanonicalDecl(), clang::QualType::getCanonicalType(), clang::QualType::getNonReferenceType(), clang::getOpenMPCaptureRegions(), clang::ValueDecl::getType(), clang::isOpenMPLoopDirective(), clang::isOpenMPLoopTransformationDirective(), clang::isOpenMPPrivate(), clang::isOpenMPSimdDirective(), clang::isOpenMPTargetExecutionDirective(), clang::isOpenMPTaskingDirective(), clang::isOpenMPTaskLoopDirective(), and clang::QualType::isTriviallyCopyableType().
Referenced by clang::Sema::tryCaptureVariable().
isOpenMPRebuildMemberExpr()
bool SemaOpenMP::isOpenMPRebuildMemberExpr (ValueDecl * D)
The member expression(this->fd) needs to be rebuilt in the template instantiation to generate private copy for OpenMP when default clause is used.
The function will return true if default cluse is used.
Definition at line 2331 of file SemaOpenMP.cpp.
References DSAStack, and clang::isOpenMPPrivate().
isOpenMPTargetCapturedDecl()
bool SemaOpenMP::isOpenMPTargetCapturedDecl (const ValueDecl * D, unsigned Level, unsigned CaptureLevel) const
Check if the specified variable is captured by 'target' directive.
Parameters
Level Relative level of nested OpenMP construct for that the check is performed.
Definition at line 2670 of file SemaOpenMP.cpp.
References DSAStack, clang::SemaBase::getLangOpts(), clang::getOpenMPCaptureRegions(), clang::VarDecl::hasLocalStorage(), and clang::isOpenMPTargetExecutionDirective().
Referenced by clang::Sema::tryCaptureVariable().
lookupOpenMPDeclareTargetName()
NamedDecl * SemaOpenMP::lookupOpenMPDeclareTargetName (Scope * CurScope, CXXScopeSpec & ScopeSpec, const DeclarationNameInfo & Id)
Searches for the provided declaration name for OpenMP declare target directive.
Definition at line 23500 of file SemaOpenMP.cpp.
References checkDeclIsAllowedInOpenMPTarget(), clang::Sema::CorrectTypo(), clang::Sema::CTK_ErrorRecovery, clang::SemaBase::Diag(), clang::Sema::diagnoseTypo(), clang::LookupResult::getAsSingle(), Id, clang::LookupResult::isAmbiguous(), clang::LookupResult::isSingleResult(), clang::Sema::LookupOrdinaryName, clang::Sema::LookupParsedName(), clang::Sema::PDiag(), clang::SemaBase::SemaRef, and clang::LookupResult::suppressDiagnostics().
PerformOpenMPImplicitIntegerConversion()
ExprResult SemaOpenMP::PerformOpenMPImplicitIntegerConversion (SourceLocation OpLoc, Expr * Op)
Definition at line 16767 of file SemaOpenMP.cpp.
References clang::ExprError().
Referenced by ActOnOpenMPDeclareSimdDirective(), ActOnOpenMPDistScheduleClause(), ActOnOpenMPLinearClause(), ActOnOpenMPScheduleClause(), and isNonNegativeIntegerValue().
setOpenMPCaptureKind()
void SemaOpenMP::setOpenMPCaptureKind (FieldDecl * FD, const ValueDecl * D, unsigned Level)
Sets OpenMP capture kind (OMPC_private, OMPC_firstprivate, OMPC_map etc.) for FD based on DSA for the provided corresponding captured declaration D.
Definition at line 2631 of file SemaOpenMP.cpp.
References DSAStack, getCanonicalDecl(), getVariableCategoryFromDecl(), and clang::isOpenMPTargetExecutionDirective().
StartOpenMPClause()
void SemaOpenMP::StartOpenMPClause (OpenMPClauseKind K)
Start analysis of clauses.
Definition at line 2794 of file SemaOpenMP.cpp.
References DSAStack.
startOpenMPCXXRangeFor()
void SemaOpenMP::startOpenMPCXXRangeFor ()
If the current region is a range loop-based region, mark the start of the loop construct.
Definition at line 2526 of file SemaOpenMP.cpp.
References DSAStack, and clang::isOpenMPLoopDirective().
StartOpenMPDSABlock()
void SemaOpenMP::StartOpenMPDSABlock (OpenMPDirectiveKind K, const DeclarationNameInfo & DirName, Scope * CurScope, SourceLocation Loc)
Called on start of new data sharing attribute block.
Definition at line 2786 of file SemaOpenMP.cpp.
References DSAStack, clang::Sema::PotentiallyEvaluated, clang::Sema::PushExpressionEvaluationContext(), and clang::SemaBase::SemaRef.
startOpenMPLoop()
void SemaOpenMP::startOpenMPLoop ()
If the current region is a loop-based region, mark the start of the loop construct.
Definition at line 2520 of file SemaOpenMP.cpp.
References DSAStack, and clang::isOpenMPLoopDirective().
tryCaptureOpenMPLambdas()
void SemaOpenMP::tryCaptureOpenMPLambdas (ValueDecl * V)
Function tries to capture lambda's captured variables in the OpenMP region before the original lambda is captured.
Definition at line 4765 of file SemaOpenMP.cpp.
References clang::Sema::CheckCXXThisCapture(), clang::Sema::CurContext, DSAStack, clang::DeclContext::Encloses(), clang::Type::getAsCXXRecordDecl(), clang::SemaBase::getASTContext(), clang::Sema::getCurrentThisType(), clang::Decl::getDeclContext(), clang::ValueDecl::getType(), clang::DeclContext::isDependentContext(), clang::QualType::isNull(), clang::isOpenMPTargetDataManagementDirective(), clang::isOpenMPTargetExecutionDirective(), clang::LCK_ByRef, clang::LCK_This, clang::Sema::MarkVariableReferenced(), clang::SemaBase::SemaRef, and V.
Referenced by MarkVarDeclODRUsed().
VerifyPositiveIntegerConstantInClause()
ExprResult SemaOpenMP::VerifyPositiveIntegerConstantInClause (Expr * Op, OpenMPClauseKind CKind, bool StrictlyPositive = true, bool SuppressExprDiags = false)
Definition at line 16881 of file SemaOpenMP.cpp.
References clang::Expr::containsUnexpandedParameterPack(), clang::ExprError(), clang::Expr::isInstantiationDependent(), clang::Expr::isTypeDependent(), and clang::Expr::isValueDependent().
Referenced by ActOnOpenMPAlignClause(), ActOnOpenMPAlignedClause(), ActOnOpenMPCollapseClause(), ActOnOpenMPDeclareSimdDirective(), ActOnOpenMPHintClause(), ActOnOpenMPOrderedClause(), ActOnOpenMPPartialClause(), ActOnOpenMPSafelenClause(), ActOnOpenMPSimdlenClause(), and ActOnOpenMPSizesClause().
Friends And Related Function Documentation
Parser
friend class Parser friend
Definition at line 50 of file SemaOpenMP.h.
Sema
friend class Sema friend
Definition at line 51 of file SemaOpenMP.h.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaOpenMP.h
lib/Sema/SemaOpenMP.cpp