clang: clang::ento::SuppressInlineDefensiveChecksVisitor Class Reference
clang::ento::SuppressInlineDefensiveChecksVisitor Class Reference final
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h"
Public Member Functions
SuppressInlineDefensiveChecksVisitor (DefinedSVal Val, const ExplodedNode *N)
void Profile (llvm::FoldingSetNodeID &ID) const override
PathDiagnosticPieceRef VisitNode (const ExplodedNode *Succ, BugReporterContext &BRC, PathSensitiveBugReport &BR) override
Return a diagnostic piece which should be associated with the given node.
Public Member Functions inherited from clang::ento::BugReporterVisitor
BugReporterVisitor ()=default
BugReporterVisitor (const BugReporterVisitor &)=default
BugReporterVisitor (BugReporterVisitor &&)
virtual ~BugReporterVisitor ()
virtual void finalizeVisitor (BugReporterContext &BRC, const ExplodedNode *EndPathNode, PathSensitiveBugReport &BR)
Last function called on the visitor, no further calls to VisitNode would follow.
virtual PathDiagnosticPieceRef getEndPath (BugReporterContext &BRC, const ExplodedNode *N, PathSensitiveBugReport &BR)
Provide custom definition for the final diagnostic piece on the path - the piece, which is displayed before the path is expanded.
Static Public Member Functions
static const char * getTag ()
Return the tag associated with this visitor.
Static Public Member Functions inherited from clang::ento::BugReporterVisitor
static PathDiagnosticPieceRef getDefaultEndPath (const BugReporterContext &BRC, const ExplodedNode *N, const PathSensitiveBugReport &BR)
Generates the default final diagnostic piece.
Detailed Description
Definition at line 564 of file BugReporterVisitors.h.
Constructor & Destructor Documentation
SuppressInlineDefensiveChecksVisitor()
SuppressInlineDefensiveChecksVisitor::SuppressInlineDefensiveChecksVisitor (DefinedSVal Val, const ExplodedNode * N)
Definition at line 1712 of file BugReporterVisitors.cpp.
Member Function Documentation
getTag()
const char * SuppressInlineDefensiveChecksVisitor::getTag () static
Return the tag associated with this visitor.
This tag will be used to make all PathDiagnosticPieces created by this visitor.
Definition at line 1727 of file BugReporterVisitors.cpp.
Profile()
void SuppressInlineDefensiveChecksVisitor::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Implements clang::ento::BugReporterVisitor.
Definition at line 1720 of file BugReporterVisitors.cpp.
References V.
VisitNode()
PathDiagnosticPieceRef SuppressInlineDefensiveChecksVisitor::VisitNode (const ExplodedNode * Succ, BugReporterContext & BRC, PathSensitiveBugReport & BR) override virtual
Return a diagnostic piece which should be associated with the given node.
Note that this function does not get run on the very last node of the report, as the PathDiagnosticPiece associated with the last node should be unique. Use getEndPath to customize the note associated with the report end instead.
The last parameter can be used to register a new visitor with the given BugReport while processing a node.
Implements clang::ento::BugReporterVisitor.
Definition at line 1732 of file BugReporterVisitors.cpp.
References clang::LocationContext::getAnalysisDeclContext(), clang::ProgramPoint::getAs(), clang::Stmt::getBeginLoc(), clang::CFGStmtMap::getBlock(), clang::AnalysisDeclContext::getCFGStmtMap(), clang::ento::PathSensitiveBugReport::getErrorNode(), clang::ento::ExplodedNode::getFirstPred(), clang::ento::ExplodedNode::getLocation(), clang::ento::ExplodedNode::getLocationContext(), getMacroName(), clang::ento::ExplodedNode::getState(), clang::CFGBlock::getTerminatorStmt(), clang::SourceLocation::isMacroID(), clang::LocationContext::isParentOf(), clang::ento::PathSensitiveBugReport::markInvalid(), and V.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h
lib/StaticAnalyzer/Core/BugReporterVisitors.cpp