clang: clang::EnterExpressionEvaluationContext Class Reference
clang::EnterExpressionEvaluationContext Class Reference
RAII object that enters a new expression evaluation context.
#include "clang/Sema/Sema.h"
Public Types
enum InitListTag { InitList }
Public Member Functions
EnterExpressionEvaluationContext (Sema &Actions, Sema::ExpressionEvaluationContext NewContext, Decl *LambdaContextDecl=nullptr, Sema::ExpressionEvaluationContextRecord::ExpressionKind ExprContext=Sema::ExpressionEvaluationContextRecord::EK_Other, bool ShouldEnter=true)
EnterExpressionEvaluationContext (Sema &Actions, Sema::ExpressionEvaluationContext NewContext, Sema::ReuseLambdaContextDecl_t, Sema::ExpressionEvaluationContextRecord::ExpressionKind ExprContext=Sema::ExpressionEvaluationContextRecord::EK_Other)
EnterExpressionEvaluationContext (Sema &Actions, InitListTag, bool ShouldEnter=true)
~EnterExpressionEvaluationContext ()
Detailed Description
RAII object that enters a new expression evaluation context.
Definition at line 13792 of file Sema.h.
Member Enumeration Documentation
InitListTag
enum clang::EnterExpressionEvaluationContext::InitListTag
Enumerator
InitList
Definition at line 13818 of file Sema.h.
Constructor & Destructor Documentation
EnterExpressionEvaluationContext() [1/3]
clang::EnterExpressionEvaluationContext::EnterExpressionEvaluationContext (Sema & Actions, Sema::ExpressionEvaluationContext NewContext, Decl * LambdaContextDecl = nullptr, Sema::ExpressionEvaluationContextRecord::ExpressionKind ExprContext = Sema::ExpressionEvaluationContextRecord::EK_Other, bool ShouldEnter = true) inline
Definition at line 13797 of file Sema.h.
References clang::Sema::PushExpressionEvaluationContext().
EnterExpressionEvaluationContext() [2/3]
clang::EnterExpressionEvaluationContext::EnterExpressionEvaluationContext (Sema & Actions, Sema::ExpressionEvaluationContext NewContext, Sema::ReuseLambdaContextDecl_t , Sema::ExpressionEvaluationContextRecord::ExpressionKind ExprContext = Sema::ExpressionEvaluationContextRecord::EK_Other) inline
Definition at line 13808 of file Sema.h.
References clang::Sema::PushExpressionEvaluationContext(), and clang::Sema::ReuseLambdaContextDecl.
EnterExpressionEvaluationContext() [3/3]
clang::EnterExpressionEvaluationContext::EnterExpressionEvaluationContext (Sema & Actions, InitListTag , bool ShouldEnter = true) inline
Definition at line 13819 of file Sema.h.
References clang::Sema::getLangOpts(), clang::Sema::isUnevaluatedContext(), clang::Sema::PushExpressionEvaluationContext(), and clang::Sema::UnevaluatedList.
~EnterExpressionEvaluationContext()
clang::EnterExpressionEvaluationContext::~EnterExpressionEvaluationContext () inline
Definition at line 13834 of file Sema.h.
References clang::Sema::PopExpressionEvaluationContext().
The documentation for this class was generated from the following file:
include/clang/Sema/Sema.h