clang: clang::OpenACCClauseWithParams Class Reference
clang::OpenACCClauseWithParams Class Reference
Represents a clause that has a list of parameters.
#include "clang/AST/OpenACCClause.h"
Public Member Functions
SourceLocation getLParenLoc () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClause
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Static Public Member Functions
static bool classof (const OpenACCClause *C)
Static Public Member Functions inherited from clang::OpenACCClause
static bool classof (const OpenACCClause *)
Protected Member Functions
OpenACCClauseWithParams (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClause
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Additional Inherited Members
Public Types inherited from clang::OpenACCClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Detailed Description
Represents a clause that has a list of parameters.
Definition at line 58 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCClauseWithParams()
clang::OpenACCClauseWithParams::OpenACCClauseWithParams (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline protected
Definition at line 63 of file OpenACCClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OpenACCClauseWithParams::children () inline
Definition at line 72 of file OpenACCClause.h.
children() [2/2]
const_child_range clang::OpenACCClauseWithParams::children () const inline
Definition at line 75 of file OpenACCClause.h.
classof()
bool OpenACCClauseWithParams::classof (const OpenACCClause * C) static
Definition at line 20 of file OpenACCClause.cpp.
References clang::OpenACCDeviceTypeClause::classof(), clang::OpenACCClauseWithCondition::classof(), and clang::OpenACCClauseWithExprs::classof().
getLParenLoc()
SourceLocation clang::OpenACCClauseWithParams::getLParenLoc () const inline
Definition at line 70 of file OpenACCClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenACCClause.h
lib/AST/OpenACCClause.cpp