clang: clang::DeclaratorDecl Class Reference
clang::DeclaratorDecl Class Reference
Represents a ValueDecl that came out of a declarator.
#include "clang/AST/Decl.h"
Public Member Functions
TypeSourceInfo * getTypeSourceInfo () const
void setTypeSourceInfo (TypeSourceInfo *TI)
SourceLocation getInnerLocStart () const
Return start of source range ignoring outer template declarations.
void setInnerLocStart (SourceLocation L)
SourceLocation getOuterLocStart () const
Return start of source range taking into account any outer template declarations.
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
SourceLocation getBeginLoc () const LLVM_READONLY
NestedNameSpecifier * getQualifier () const
Retrieve the nested-name-specifier that qualifies the name of this declaration, if it was present in the source.
NestedNameSpecifierLoc getQualifierLoc () const
Retrieve the nested-name-specifier (with source-location information) that qualifies the name of this declaration, if it was present in the source.
void setQualifierInfo (NestedNameSpecifierLoc QualifierLoc)
Expr * getTrailingRequiresClause ()
Get the constraint-expression introduced by the trailing requires-clause in the function/member declaration, or null if no requires-clause was provided.
const Expr * getTrailingRequiresClause () const
void setTrailingRequiresClause (Expr *TrailingRequiresClause)
unsigned getNumTemplateParameterLists () const
TemplateParameterList * getTemplateParameterList (unsigned index) const
void setTemplateParameterListsInfo (ASTContext &Context, ArrayRef< TemplateParameterList * > TPLists)
SourceLocation getTypeSpecStartLoc () const
SourceLocation getTypeSpecEndLoc () const
Public Member Functions inherited from clang::ValueDecl
QualType getType () const
void setType (QualType newType)
bool isWeak () const
Determine whether this symbol is weakly-imported, or declared with the weak or weak-ref attr.
bool isInitCapture () const
Whether this variable is the implicit variable for a lambda init-capture.
VarDecl * getPotentiallyDecomposedVarDecl ()
const VarDecl * getPotentiallyDecomposedVarDecl () const
Public Member Functions inherited from clang::NamedDecl
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
virtual void printName (raw_ostream &OS, const PrintingPolicy &Policy) const
Pretty-print the unqualified name of this declaration.
void printName (raw_ostream &OS) const
Calls printName() with the ASTContext printing policy from the decl.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy, bool WithGlobalNsPrefix=false) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy, bool WithGlobalNsPrefix=false) const
std::string getQualifiedNameAsString (bool WithGlobalNsPrefix=false) const
virtual void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const
Appends a human-readable name for this declaration into the given stream.
bool declarationReplaces (const NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
ReservedIdentifierStatus isReserved (const LangOptions &LangOpts) const
Determine if the declaration obeys the reserved identifier rules of the given language.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
std::optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
bool isPlaceholderVar (const LangOptions &LangOpts) const
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
DeclContext * getNonTransparentDeclContext ()
Return the non transparent context.
const DeclContext * getNonTransparentDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
bool isFileContextDecl () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename... Ts>
void dropAttrs ()
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool isInExportDeclContext () const
Whether this declaration was exported in a lexical context.
bool isInvisibleOutsideTheOwningModule () const
bool isInAnotherModuleUnit () const
Whether this declaration comes from another module unit.
bool isFromExplicitGlobalModule () const
Whether this declaration comes from explicit global module.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
DeclID getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
bool isReachable () const
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
virtual bool isOutOfLine () const
Determine whether this declaration is declared out of line (outside its semantic context).
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod (bool LexicalParent=false) const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod (bool LexicalParent=false)
virtual Decl * getCanonicalDecl ()
Retrieves the "canonical" declaration of the given declaration.
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual Stmt * getBody () const
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl () const
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
void clearIdentifierNamespace ()
Clears the namespace of this declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
bool isFunctionPointerType () const
Static Public Member Functions
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::ValueDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::NamedDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static bool isFlexibleArrayMemberLike (ASTContext &Context, const Decl *D, QualType Ty, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel, bool IgnoreTemplateOrMacroSubstitution)
Whether it resembles a flexible array member.
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Protected Member Functions
DeclaratorDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N, QualType T, TypeSourceInfo *TInfo, SourceLocation StartL)
Protected Member Functions inherited from clang::ValueDecl
ValueDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N, QualType T)
Protected Member Functions inherited from clang::NamedDecl
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclID ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
virtual Decl * getNextRedeclarationImpl ()
Returns the next redeclaration or itself if this is the only decl.
virtual Decl * getPreviousDeclImpl ()
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
virtual Decl * getMostRecentDeclImpl ()
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
ASTMutationListener * getASTMutationListener () const
Friends
class ASTDeclReader
class ASTDeclWriter
Additional Inherited Members
Public Types inherited from clang::NamedDecl
enum ExplicitVisibilityKind { VisibilityForType , VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned char {
Unowned , Visible , VisibleWhenImported , ReachableWhenImported ,
ModulePrivate
}
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using DeclID = uint32_t
An ID number that refers to a declaration in an AST file.
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range< attr_iterator >
using redecl_range = llvm::iterator_range< redecl_iterator >
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 3, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Detailed Description
Represents a ValueDecl that came out of a declarator.
Contains type source information through TypeSourceInfo.
Definition at line 771 of file Decl.h.
Constructor & Destructor Documentation
DeclaratorDecl()
clang::DeclaratorDecl::DeclaratorDecl (Kind DK, DeclContext * DC, SourceLocation L, DeclarationName N, QualType T, TypeSourceInfo * TInfo, SourceLocation StartL) inline protected
Definition at line 791 of file Decl.h.
Member Function Documentation
classof()
static bool clang::DeclaratorDecl::classof (const Decl * D) inline static
Definition at line 875 of file Decl.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::DeclaratorDecl::classofKind (Kind K) inline static
Definition at line 876 of file Decl.h.
Referenced by classof().
getBeginLoc()
SourceLocation clang::DeclaratorDecl::getBeginLoc () const inline
Definition at line 823 of file Decl.h.
References getOuterLocStart().
Referenced by clang::SemaHLSL::ActOnTopLevelFunction(), clang::Sema::CheckCXXDefaultArgExpr(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::CheckExplicitObjectOverride(), clang::checkUnsafeBufferUsage(), DiagnoseForRangeConstVariableCopies(), DiagnoseForRangeReferenceVariableCopies(), diagnoseOpenCLTypes(), clang::CodeGen::CGOpenMPRuntime::emitDeclareTargetFunction(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), emitOutlinedFunctionPrologue(), fixLocalVarDeclWithSpan(), fixVarDeclWithArray(), clang::CodeGen::CodeGenFunction::GenerateCXXGlobalVarDeclInitFunc(), clang::CodeGen::CodeGenFunction::generateDestroyHelper(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntime::getAddrOfDeclareTargetVar(), clang::CoroutineBodyStmt::getBeginLoc(), clang::ParmVarDecl::getSourceRange(), clang::OMPCapturedExprDecl::getSourceRange(), clang::Sema::InstantiateFunctionDefinition(), clang::Sema::InstantiateVariableDefinition(), clang::Sema::ModifyFnAttributesMSPragmaOptimize(), clang::CodeGen::CGOpenMPRuntime::registerTargetGlobalVariable(), clang::Sema::SubstDefaultArgument(), clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter(), and clang::ASTNodeImporter::VisitVarTemplateSpecializationDecl().
getInnerLocStart()
SourceLocation clang::DeclaratorDecl::getInnerLocStart () const inline
Return start of source range ignoring outer template declarations.
Definition at line 814 of file Decl.h.
Referenced by clang::FieldDecl::getSourceRange(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), clang::TreeTransform< Derived >::RebuildObjCExceptionDecl(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitDeclaratorDecl(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), clang::ASTNodeImporter::VisitNonTypeTemplateParmDecl(), and clang::ASTNodeImporter::VisitParmVarDecl().
getNumTemplateParameterLists()
unsigned clang::DeclaratorDecl::getNumTemplateParameterLists () const inline
Definition at line 859 of file Decl.h.
Referenced by clang::Sema::checkVarDeclRedefinition(), clang::comments::DeclInfo::fill(), getTemplateParameterList(), clang::ASTNodeImporter::ImportTemplateParameterLists(), and clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
getOuterLocStart()
SourceLocation DeclaratorDecl::getOuterLocStart () const
Return start of source range taking into account any outer template declarations.
Definition at line 2051 of file Decl.cpp.
References getTemplateOrInnerLocStart().
Referenced by clang::Sema::ActOnCXXForRangeDecl(), getBeginLoc(), getSourceRange(), clang::VarDecl::getSourceRange(), clang::ParmVarDecl::getSourceRange(), clang::FunctionDecl::getSourceRange(), clang::NonTypeTemplateParmDecl::getSourceRange(), clang::VarTemplateSpecializationDecl::getSourceRange(), clang::VarTemplatePartialSpecializationDecl::getSourceRange(), and clang::Sema::SubstDefaultArgument().
getQualifier()
NestedNameSpecifier* clang::DeclaratorDecl::getQualifier () const inline
Retrieve the nested-name-specifier that qualifies the name of this declaration, if it was present in the source.
Definition at line 829 of file Decl.h.
Referenced by adjustDeclContextForDeclaratorDecl(), and clang::TextNodeDumper::VisitVarDecl().
getQualifierLoc()
NestedNameSpecifierLoc clang::DeclaratorDecl::getQualifierLoc () const inline
Retrieve the nested-name-specifier (with source-location information) that qualifies the name of this declaration, if it was present in the source.
Definition at line 837 of file Decl.h.
Referenced by clang::Sema::BuildCallExpr(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::TemplateDeclInstantiator::VisitFunctionDecl(), and clang::ASTNodeImporter::VisitVarTemplateSpecializationDecl().
getSourceRange()
SourceRange DeclaratorDecl::getSourceRange () const override virtual
Source range that this declaration covers.
Reimplemented from clang::Decl.
Reimplemented in clang::VarTemplatePartialSpecializationDecl, clang::VarTemplateSpecializationDecl, clang::NonTypeTemplateParmDecl, clang::OMPCapturedExprDecl, clang::FieldDecl, clang::FunctionDecl, clang::ParmVarDecl, and clang::VarDecl.
Definition at line 2091 of file Decl.cpp.
References clang::NamedDecl::getDeclName(), clang::Decl::getLocation(), getOuterLocStart(), getTypeSourceInfo(), and typeIsPostfix().
Referenced by getNonCLikeKindForAnonymousStruct(), clang::VarDecl::getSourceRange(), clang::ParmVarDecl::getSourceRange(), clang::FieldDecl::getSourceRange(), and clang::NonTypeTemplateParmDecl::getSourceRange().
getTemplateParameterList()
TemplateParameterList* clang::DeclaratorDecl::getTemplateParameterList (unsigned index) const inline
Definition at line 863 of file Decl.h.
References getNumTemplateParameterLists().
Referenced by clang::comments::DeclInfo::fill(), clang::ASTNodeImporter::ImportTemplateParameterLists(), and clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
getTrailingRequiresClause() [1/2]
Expr* clang::DeclaratorDecl::getTrailingRequiresClause () inline
Get the constraint-expression introduced by the trailing requires-clause in the function/member declaration, or null if no requires-clause was provided.
Definition at line 847 of file Decl.h.
Referenced by clang::Sema::CheckFunctionConstraints(), clang::LambdaExpr::getTrailingRequiresClause(), clang::FunctionDecl::isMemberLikeConstrainedFriend(), IsOverloadOrOverrideImpl(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitFunctionDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
getTrailingRequiresClause() [2/2]
const Expr* clang::DeclaratorDecl::getTrailingRequiresClause () const inline
Definition at line 852 of file Decl.h.
getTypeSourceInfo()
TypeSourceInfo* clang::DeclaratorDecl::getTypeSourceInfo () const inline
Definition at line 800 of file Decl.h.
Referenced by clang::ASTContext::adjustExceptionSpec(), clang::Sema::AttachTypeConstraint(), CheckAbstractClassUsage(), clang::Sema::CheckEquivalentExceptionSpec(), clang::Sema::checkThisInStaticMemberFunctionExceptionSpec(), clang::Sema::checkThisInStaticMemberFunctionType(), clang::Sema::CompleteVarTemplateSpecializationDecl(), createDefaultTargetVersionFrom(), clang::Sema::DeduceVariableDeclarationType(), FormatFunctionParameter(), clang::FunctionDecl::getDeclaredReturnType(), clang::FunctionDecl::getExceptionSpecType(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForVar(), clang::extractapi::DeclarationFragmentsBuilder::getFragmentsForVarTemplate(), clang::FunctionDecl::getFunctionTypeLoc(), clang::ParmVarDecl::getOriginalType(), clang::Sema::getReturnTypeLoc(), getSourceRange(), getTypeSpecEndLoc(), getTypeSpecStartLoc(), hasDeducedReturnType(), implicitObjectParamIsLifetimeBound(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), clang::Sema::SubstExceptionSpec(), clang::TemplateDeclInstantiator::SubstFunctionType(), clang::Sema::SubstParmVarDecl(), clang::TreeTransform< Derived >::TransformFunctionTypeParam(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTDeclWriter::VisitDeclaratorDecl(), clang::ASTDeclReader::VisitFunctionDecl(), clang::ASTNodeImporter::VisitNonTypeTemplateParmDecl(), clang::ASTNodeImporter::VisitParmVarDecl(), clang::ASTNodeTraverser< Derived, NodeDelegateType >::VisitVarDecl(), and clang::ASTNodeImporter::VisitVarTemplateSpecializationDecl().
getTypeSpecEndLoc()
SourceLocation DeclaratorDecl::getTypeSpecEndLoc () const
Definition at line 1995 of file Decl.cpp.
References clang::TypeLoc::getEndLoc(), clang::TypeSourceInfo::getTypeLoc(), and getTypeSourceInfo().
Referenced by DiagnoseForRangeReferenceVariableCopies(), fixLocalVarDeclWithSpan(), and fixVarDeclWithArray().
getTypeSpecStartLoc()
SourceLocation DeclaratorDecl::getTypeSpecStartLoc () const
Definition at line 1989 of file Decl.cpp.
References clang::TypeLoc::getBeginLoc(), clang::TypeSourceInfo::getTypeLoc(), and getTypeSourceInfo().
Referenced by clang::Sema::ActOnConversionDeclarator(), clang::Sema::CompleteVarTemplateSpecializationDecl(), getFunctionSourceLocation(), clang::TemplateDeclInstantiator::InstantiateVarTemplatePartialSpecialization(), and clang::TemplateDeclInstantiator::SubstFunctionType().
setInnerLocStart()
void clang::DeclaratorDecl::setInnerLocStart (SourceLocation L) inline
Definition at line 815 of file Decl.h.
Referenced by clang::Sema::CompleteLambdaCallOperator(), and clang::ASTDeclReader::VisitDeclaratorDecl().
setQualifierInfo()
void DeclaratorDecl::setQualifierInfo (NestedNameSpecifierLoc QualifierLoc)
Definition at line 2001 of file Decl.cpp.
References clang::Decl::getASTContext().
Referenced by clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::ASTNodeImporter::VisitVarTemplateSpecializationDecl().
setTemplateParameterListsInfo()
void DeclaratorDecl::setTemplateParameterListsInfo (ASTContext & Context, ArrayRef< TemplateParameterList * > TPLists)
Definition at line 2035 of file Decl.cpp.
Referenced by clang::ASTNodeImporter::ImportTemplateParameterLists(), and clang::TemplateDeclInstantiator::VisitCXXMethodDecl().
setTrailingRequiresClause()
void DeclaratorDecl::setTrailingRequiresClause (Expr * TrailingRequiresClause)
Definition at line 2020 of file Decl.cpp.
References clang::Decl::getASTContext().
Referenced by clang::Sema::CompleteLambdaCallOperator().
setTypeSourceInfo()
void clang::DeclaratorDecl::setTypeSourceInfo (TypeSourceInfo * TI) inline
Definition at line 806 of file Decl.h.
Referenced by clang::Sema::CompleteLambdaCallOperator(), clang::Sema::RebuildTemplateParamsInCurrentInstantiation(), clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), clang::ASTDeclReader::VisitDeclaratorDecl(), and clang::ASTNodeImporter::VisitVarTemplateSpecializationDecl().
Friends And Related Function Documentation
ASTDeclReader
friend class ASTDeclReader friend
Definition at line 797 of file Decl.h.
ASTDeclWriter
friend class ASTDeclWriter friend
Definition at line 798 of file Decl.h.
The documentation for this class was generated from the following files:
include/clang/AST/Decl.h
lib/AST/Decl.cpp