clang: clang::ento::WorkList Class Reference
clang::ento::WorkList Class Reference abstract
#include "clang/StaticAnalyzer/Core/PathSensitive/WorkList.h"
Public Member Functions
virtual ~WorkList ()
virtual bool hasWork () const =0
virtual void enqueue (const WorkListUnit &U)=0
void enqueue (ExplodedNode *N, const CFGBlock *B, unsigned idx)
void enqueue (ExplodedNode *N)
virtual WorkListUnit dequeue ()=0
void setBlockCounter (BlockCounter C)
BlockCounter getBlockCounter () const
Static Public Member Functions
static std::unique_ptr< WorkList > makeDFS ()
static std::unique_ptr< WorkList > makeBFS ()
static std::unique_ptr< WorkList > makeBFSBlockDFSContents ()
static std::unique_ptr< WorkList > makeUnexploredFirst ()
static std::unique_ptr< WorkList > makeUnexploredFirstPriorityQueue ()
static std::unique_ptr< WorkList > makeUnexploredFirstPriorityLocationQueue ()
Detailed Description
Definition at line 60 of file WorkList.h.
Constructor & Destructor Documentation
~WorkList()
WorkList::~WorkList () virtual default
Member Function Documentation
dequeue()
virtual WorkListUnit clang::ento::WorkList::dequeue () pure virtual
enqueue() [1/3]
virtual void clang::ento::WorkList::enqueue (const WorkListUnit & U) pure virtual
Referenced by enqueue(), and clang::ento::ExprEngine::processCallExit().
enqueue() [2/3]
void clang::ento::WorkList::enqueue (ExplodedNode * N) inline
Definition at line 72 of file WorkList.h.
References enqueue(), clang::ProgramPoint::getKind(), clang::ento::ExplodedNode::getLocation(), and clang::ProgramPoint::PostStmtKind.
enqueue() [3/3]
void clang::ento::WorkList::enqueue (ExplodedNode * N, const CFGBlock * B, unsigned idx) inline
Definition at line 68 of file WorkList.h.
References enqueue().
getBlockCounter()
BlockCounter clang::ento::WorkList::getBlockCounter () const inline
Definition at line 80 of file WorkList.h.
hasWork()
virtual bool clang::ento::WorkList::hasWork () const pure virtual
Referenced by clang::ento::ExprEngine::hasEmptyWorkList().
makeBFS()
std::unique_ptr< WorkList > WorkList::makeBFS () static
Definition at line 85 of file WorkList.cpp.
Referenced by generateWorkList().
makeBFSBlockDFSContents()
std::unique_ptr< WorkList > WorkList::makeBFSBlockDFSContents () static
Definition at line 126 of file WorkList.cpp.
Referenced by generateWorkList().
makeDFS()
std::unique_ptr< WorkList > WorkList::makeDFS () static
Definition at line 81 of file WorkList.cpp.
Referenced by generateWorkList().
makeUnexploredFirst()
std::unique_ptr< WorkList > WorkList::makeUnexploredFirst () static
Definition at line 188 of file WorkList.cpp.
Referenced by generateWorkList().
makeUnexploredFirstPriorityLocationQueue()
std::unique_ptr< WorkList > WorkList::makeUnexploredFirstPriorityLocationQueue () static
Definition at line 299 of file WorkList.cpp.
Referenced by generateWorkList().
makeUnexploredFirstPriorityQueue()
std::unique_ptr< WorkList > WorkList::makeUnexploredFirstPriorityQueue () static
Definition at line 245 of file WorkList.cpp.
Referenced by generateWorkList().
setBlockCounter()
void clang::ento::WorkList::setBlockCounter (BlockCounter C) inline
Definition at line 79 of file WorkList.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/WorkList.h
lib/StaticAnalyzer/Core/WorkList.cpp