clang: clang::ento::ElementRegion Class Reference
clang::ento::ElementRegion Class Reference
ElementRegion is used to represent both array elements and casts.
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
Public Member Functions
NonLoc getIndex () const
QualType getValueType () const override
QualType getElementType () const
RegionRawOffset getAsArrayOffset () const
Compute the offset within the array. The array might also be a subobject.
void dumpToStream (raw_ostream &os) const override
void Profile (llvm::FoldingSetNodeID &ID) const override
Public Member Functions inherited from clang::ento::TypedValueRegion
QualType getLocationType () const override
QualType getDesugaredValueType (ASTContext &Context) const
Public Member Functions inherited from clang::ento::TypedRegion
QualType getDesugaredLocationType (ASTContext &Context) const
bool isBoundable () const override
Public Member Functions inherited from clang::ento::SubRegion
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getSuperRegion () const
MemRegionManager & getMemRegionManager () const override
bool isSubRegionOf (const MemRegion *R) const override
Check if the region is a subregion of the given region.
Public Member Functions inherited from clang::ento::MemRegion
ASTContext & getContext () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemSpaceRegion * getMemorySpace () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getBaseRegion () const
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * getMostDerivedObjectRegion () const
Recursively retrieve the region of the most derived class instance of regions of C++ base class instances.
LLVM_ATTRIBUTE_RETURNS_NONNULL const MemRegion * StripCasts (bool StripBaseAndDerivedCasts=true) const
const SymbolicRegion * getSymbolicBase () const
If this is a symbolic region, returns the region.
bool hasStackStorage () const
bool hasStackNonParametersStorage () const
bool hasStackParametersStorage () const
RegionOffset getAsOffset () const
Compute the offset within the top level memory object.
std::string getString () const
Get a string representation of a region for debug use.
void dump () const
virtual bool canPrintPretty () const
Returns true if this region can be printed in a user-friendly way.
virtual void printPretty (raw_ostream &os) const
Print the region for use in diagnostics.
virtual bool canPrintPrettyAsExpr () const
Returns true if this region's textual representation can be used as part of a larger expression.
virtual void printPrettyAsExpr (raw_ostream &os) const
Print the region as expression.
Kind getKind () const
template<typename RegionTy >
const RegionTy * getAs () const
template<typename RegionTy >
LLVM_ATTRIBUTE_RETURNS_NONNULL const RegionTy * castAs () const
std::string getDescriptiveName (bool UseQuotes=true) const
Get descriptive name for memory region.
SourceRange sourceRange () const
Retrieve source range from memory region.
Static Public Member Functions
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::TypedValueRegion
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::TypedRegion
static bool classof (const MemRegion *R)
Static Public Member Functions inherited from clang::ento::SubRegion
static bool classof (const MemRegion *R)
Friends
class MemRegionManager
Additional Inherited Members
Public Types inherited from clang::ento::MemRegion
enum Kind
Protected Member Functions inherited from clang::ento::TypedValueRegion
TypedValueRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::TypedRegion
TypedRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::SubRegion
SubRegion (const MemRegion *sReg, Kind k)
Protected Member Functions inherited from clang::ento::MemRegion
MemRegion (Kind k)
virtual ~MemRegion ()
Protected Attributes inherited from clang::ento::SubRegion
const MemRegion * superRegion
Detailed Description
ElementRegion is used to represent both array elements and casts.
Definition at line 1194 of file MemRegion.h.
Member Function Documentation
classof()
static bool clang::ento::ElementRegion::classof (const MemRegion * R) inline static
Definition at line 1227 of file MemRegion.h.
References clang::ento::MemRegion::getKind().
dumpToStream()
void ElementRegion::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::MemRegion.
Definition at line 533 of file MemRegion.cpp.
References getElementType(), and clang::ento::SubRegion::superRegion.
getAsArrayOffset()
RegionRawOffset ElementRegion::getAsArrayOffset () const
Compute the offset within the array. The array might also be a subobject.
Definition at line 1412 of file MemRegion.cpp.
References clang::CharUnits::fromQuantity(), clang::ento::SVal::getAs(), clang::ento::MemRegion::getContext(), getElementType(), getIndex(), clang::ento::SubRegion::getSuperRegion(), and clang::Type::isIncompleteType().
Referenced by clang::ento::StoreManager::castRegion().
getElementType()
QualType clang::ento::ElementRegion::getElementType () const inline
Definition at line 1218 of file MemRegion.h.
Referenced by dumpToStream(), getAsArrayOffset(), clang::ento::MemRegionManager::getElementRegionWithSuper(), and clang::ento::SValExplainer::VisitElementRegion().
getIndex()
NonLoc clang::ento::ElementRegion::getIndex () const inline
Definition at line 1214 of file MemRegion.h.
Referenced by getAsArrayOffset(), clang::ento::MemRegion::getDescriptiveName(), getElementRegionOffsetsWithBase(), clang::ento::MemRegionManager::getElementRegionWithSuper(), isArrayIndexOutOfBounds(), and clang::ento::SValExplainer::VisitElementRegion().
getValueType()
QualType clang::ento::ElementRegion::getValueType () const inline override virtual
Implements clang::ento::TypedValueRegion.
Definition at line 1216 of file MemRegion.h.
Referenced by isArrayIndexOutOfBounds().
Profile()
void ElementRegion::Profile (llvm::FoldingSetNodeID & ID) const override virtual
Implements clang::ento::MemRegion.
Definition at line 351 of file MemRegion.cpp.
References ID, and clang::ento::SubRegion::superRegion.
Friends And Related Function Documentation
MemRegionManager
friend class MemRegionManager friend
Definition at line 1195 of file MemRegion.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h
lib/StaticAnalyzer/Core/MemRegion.cpp