clang: clang::tooling::dependencies::DependencyScanningService Class Reference
clang::tooling::dependencies::DependencyScanningService Class Reference
The dependency scanning service contains the shared state that is used by the invidual dependency scanning workers.
#include "clang/Tooling/DependencyScanning/DependencyScanningService.h"
Public Member Functions
DependencyScanningService (ScanningMode Mode, ScanningOutputFormat Format, bool ReuseFileManager=true, bool SkipExcludedPPRanges=true, bool OptimizeArgs=false)
ScanningMode getMode () const
ScanningOutputFormat getFormat () const
bool canReuseFileManager () const
bool canSkipExcludedPPRanges () const
bool canOptimizeArgs () const
DependencyScanningFilesystemSharedCache & getSharedCache ()
Detailed Description
The dependency scanning service contains the shared state that is used by the invidual dependency scanning workers.
Definition at line 47 of file DependencyScanningService.h.
Constructor & Destructor Documentation
DependencyScanningService()
DependencyScanningService::DependencyScanningService (ScanningMode Mode, ScanningOutputFormat Format, bool ReuseFileManager = true, bool SkipExcludedPPRanges = true, bool OptimizeArgs = false)
Definition at line 16 of file DependencyScanningService.cpp.
Member Function Documentation
canOptimizeArgs()
bool clang::tooling::dependencies::DependencyScanningService::canOptimizeArgs () const inline
Definition at line 62 of file DependencyScanningService.h.
canReuseFileManager()
bool clang::tooling::dependencies::DependencyScanningService::canReuseFileManager () const inline
Definition at line 58 of file DependencyScanningService.h.
Referenced by clang::tooling::dependencies::DependencyScanningWorker::DependencyScanningWorker().
canSkipExcludedPPRanges()
bool clang::tooling::dependencies::DependencyScanningService::canSkipExcludedPPRanges () const inline
Definition at line 60 of file DependencyScanningService.h.
Referenced by clang::tooling::dependencies::DependencyScanningWorker::DependencyScanningWorker().
getFormat()
ScanningOutputFormat clang::tooling::dependencies::DependencyScanningService::getFormat () const inline
Definition at line 56 of file DependencyScanningService.h.
getMode()
ScanningMode clang::tooling::dependencies::DependencyScanningService::getMode () const inline
Definition at line 54 of file DependencyScanningService.h.
Referenced by clang::tooling::dependencies::DependencyScanningWorker::DependencyScanningWorker().
getSharedCache()
DependencyScanningFilesystemSharedCache& clang::tooling::dependencies::DependencyScanningService::getSharedCache () inline
Definition at line 64 of file DependencyScanningService.h.
Referenced by clang::tooling::dependencies::DependencyScanningWorker::DependencyScanningWorker().
The documentation for this class was generated from the following files:
include/clang/Tooling/DependencyScanning/DependencyScanningService.h
lib/Tooling/DependencyScanning/DependencyScanningService.cpp