clang: clang::OMPBindClause Class Reference
clang::OMPBindClause Class Reference final
This represents 'bind' clause in the '#pragma omp ...' directives.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
SourceLocation getLParenLoc () const
Returns the location of '('.
OpenMPBindClauseKind getBindKind () const
Returns kind of the clause.
SourceLocation getBindKindLoc () const
Returns location of clause kind.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPBindClause * Create (const ASTContext &C, OpenMPBindClauseKind K, SourceLocation KLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build 'bind' clause with kind K ('teams', 'parallel', or 'thread').
static OMPBindClause * CreateEmpty (const ASTContext &C)
Build an empty 'bind' clause.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents 'bind' clause in the '#pragma omp ...' directives.
#pragma omp loop bind(parallel)
Definition at line 8530 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPBindClause::children () inline
Definition at line 8595 of file OpenMPClause.h.
children() [2/2]
const_child_range clang::OMPBindClause::children () const inline
Definition at line 8599 of file OpenMPClause.h.
classof()
static bool clang::OMPBindClause::classof (const OMPClause * T) inline static
Definition at line 8610 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
Create()
OMPBindClause * OMPBindClause::Create (const ASTContext & C, OpenMPBindClauseKind K, SourceLocation KLoc, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) static
Build 'bind' clause with kind K ('teams', 'parallel', or 'thread').
Parameters
C AST context
K Binding kind of the clause ('teams', 'parallel' or 'thread').
KLoc Starting location of the binding kind.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
Definition at line 1601 of file OpenMPClause.cpp.
Referenced by clang::Sema::ActOnOpenMPBindClause().
CreateEmpty()
OMPBindClause * OMPBindClause::CreateEmpty (const ASTContext & C) static
Build an empty 'bind' clause.
Parameters
C AST context
Definition at line 1607 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
getBindKind()
OpenMPBindClauseKind clang::OMPBindClause::getBindKind () const inline
Returns kind of the clause.
Definition at line 8590 of file OpenMPClause.h.
getBindKindLoc()
SourceLocation clang::OMPBindClause::getBindKindLoc () const inline
Returns location of clause kind.
Definition at line 8593 of file OpenMPClause.h.
getLParenLoc()
SourceLocation clang::OMPBindClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 8587 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPBindClause::used_children () inline
Definition at line 8603 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPBindClause::used_children () const inline
Definition at line 8606 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 8531 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp