clang: clang::ASTWriter Class Reference
clang::ASTWriter Class Reference
Writes an AST file containing the contents of a translation unit.
#include "clang/Serialization/ASTWriter.h"
Public Types
using RecordData = SmallVector< uint64_t, 64 >
using RecordDataImpl = SmallVectorImpl< uint64_t >
using RecordDataRef = ArrayRef< uint64_t >
Public Member Functions
ASTWriter (llvm::BitstreamWriter &Stream, SmallVectorImpl< char > &Buffer, InMemoryModuleCache &ModuleCache, ArrayRef< std::shared_ptr< ModuleFileExtension >> Extensions, bool IncludeTimestamps=true, bool BuildingImplicitModule=false, bool GeneratingReducedBMI=false)
Create a new precompiled header writer that outputs to the given bitstream.
~ASTWriter () override
ASTContext & getASTContext () const
const LangOptions & getLangOpts () const
time_t getTimestampForOutput (const FileEntry *E) const
Get a timestamp for output into the AST file.
ASTFileSignature WriteAST (Sema &SemaRef, StringRef OutputFile, Module *WritingModule, StringRef isysroot, bool ShouldCacheASTInMemory=false)
Write a precompiled header for the given semantic analysis.
void AddToken (const Token &Tok, RecordDataImpl &Record)
Emit a token.
void AddAlignPackInfo (const Sema::AlignPackInfo &Info, RecordDataImpl &Record)
Emit a AlignPackInfo.
void AddFileID (FileID FID, RecordDataImpl &Record)
Emit a FileID.
void AddSourceLocation (SourceLocation Loc, RecordDataImpl &Record, LocSeq *Seq=nullptr)
Emit a source location.
void AddSourceRange (SourceRange Range, RecordDataImpl &Record, LocSeq *Seq=nullptr)
Emit a source range.
void AddIdentifierRef (const IdentifierInfo *II, RecordDataImpl &Record)
Emit a reference to an identifier.
serialization::SelectorID getSelectorRef (Selector Sel)
Get the unique number used to refer to the given selector.
serialization::IdentID getIdentifierRef (const IdentifierInfo *II)
Get the unique number used to refer to the given identifier.
serialization::MacroID getMacroRef (MacroInfo *MI, const IdentifierInfo *Name)
Get the unique number used to refer to the given macro.
serialization::MacroID getMacroID (MacroInfo *MI)
Determine the ID of an already-emitted macro.
uint32_t getMacroDirectivesOffset (const IdentifierInfo *Name)
void AddTypeRef (QualType T, RecordDataImpl &Record)
Emit a reference to a type.
serialization::TypeID GetOrCreateTypeID (QualType T)
Force a type to be emitted and get its ID.
serialization::TypeID getTypeID (QualType T) const
Determine the type ID of an already-emitted type.
const Decl * getFirstLocalDecl (const Decl *D)
Find the first local declaration of a given local redeclarable decl.
bool IsLocalDecl (const Decl *D)
Is this a local declaration (that is, one that will be written to our AST file)? This is the case for declarations that are neither imported from another AST file nor predefined.
void AddDeclRef (const Decl *D, RecordDataImpl &Record)
Emit a reference to a declaration.
void AddEmittedDeclRef (const Decl *D, RecordDataImpl &Record)
serialization::DeclID GetDeclRef (const Decl *D)
Force a declaration to be emitted and get its ID.
serialization::DeclID getDeclID (const Decl *D)
Determine the declaration ID of an already-emitted declaration.
bool wasDeclEmitted (const Decl *D) const
Whether or not the declaration got emitted.
unsigned getAnonymousDeclarationNumber (const NamedDecl *D)
void AddString (StringRef Str, RecordDataImpl &Record)
Add a string to the given record.
bool PreparePathForOutput (SmallVectorImpl< char > &Path)
Convert a path from this build process into one that is appropriate for emission in the module file.
void AddPath (StringRef Path, RecordDataImpl &Record)
Add a path to the given record.
void EmitRecordWithPath (unsigned Abbrev, RecordDataRef Record, StringRef Path)
Emit the current record with the given path as a blob.
void AddVersionTuple (const VersionTuple &Version, RecordDataImpl &Record)
Add a version tuple to the given record.
unsigned getLocalOrImportedSubmoduleID (const Module *Mod)
Retrieve or create a submodule ID for this module, or return 0 if the submodule is neither local (a submodle of the currently-written module) nor from an imported module.
void SetIdentifierOffset (const IdentifierInfo *II, uint32_t Offset)
Note that the identifier II occurs at the given offset within the identifier table.
void SetSelectorOffset (Selector Sel, uint32_t Offset)
Note that the selector Sel occurs at the given offset within the method pool/selector table.
unsigned RecordSwitchCaseID (SwitchCase *S)
Record an ID for the given switch-case statement.
unsigned getSwitchCaseID (SwitchCase *S)
Retrieve the ID for the given switch-case statement.
void ClearSwitchCaseIDs ()
unsigned getTypeExtQualAbbrev () const
unsigned getDeclParmVarAbbrev () const
unsigned getDeclRecordAbbrev () const
unsigned getDeclTypedefAbbrev () const
unsigned getDeclVarAbbrev () const
unsigned getDeclFieldAbbrev () const
unsigned getDeclEnumAbbrev () const
unsigned getDeclObjCIvarAbbrev () const
unsigned getDeclCXXMethodAbbrev (FunctionDecl::TemplatedKind Kind) const
unsigned getDeclTemplateTypeParmAbbrev () const
unsigned getDeclUsingShadowAbbrev () const
unsigned getDeclRefExprAbbrev () const
unsigned getCharacterLiteralAbbrev () const
unsigned getIntegerLiteralAbbrev () const
unsigned getExprImplicitCastAbbrev () const
unsigned getBinaryOperatorAbbrev () const
unsigned getCompoundAssignOperatorAbbrev () const
unsigned getCallExprAbbrev () const
unsigned getCXXOperatorCallExprAbbrev ()
unsigned getCXXMemberCallExprAbbrev ()
unsigned getCompoundStmtAbbrev () const
bool hasChain () const
ASTReader * getChain () const
bool isWritingStdCXXNamedModules () const
bool isGeneratingReducedBMI () const
bool getDoneWritingDeclsAndTypes () const
Public Member Functions inherited from clang::ASTDeserializationListener
virtual ~ASTDeserializationListener ()
virtual void DeclRead (serialization::DeclID ID, const Decl *D)
A decl was deserialized from the AST file.
virtual void ModuleImportRead (serialization::SubmoduleID ID, SourceLocation ImportLoc)
A module import was read from the AST file.
Public Member Functions inherited from clang::ASTMutationListener
virtual ~ASTMutationListener ()
Friends
class ASTDeclWriter
class ASTRecordWriter
Detailed Description
Writes an AST file containing the contents of a translation unit.
The ASTWriter class produces a bitstream containing the serialized representation of a given abstract syntax tree and its supporting data structures. This bitstream can be de-serialized via an instance of the ASTReader class.
Definition at line 85 of file ASTWriter.h.
Member Typedef Documentation
RecordData
using clang::ASTWriter::RecordData = SmallVector<uint64_t, 64>
Definition at line 91 of file ASTWriter.h.
RecordDataImpl
using clang::ASTWriter::RecordDataImpl = SmallVectorImpl<uint64_t>
Definition at line 92 of file ASTWriter.h.
RecordDataRef
using clang::ASTWriter::RecordDataRef = ArrayRef<uint64_t>
Definition at line 93 of file ASTWriter.h.
Constructor & Destructor Documentation
ASTWriter()
ASTWriter::ASTWriter (llvm::BitstreamWriter & Stream, SmallVectorImpl< char > & Buffer, InMemoryModuleCache & ModuleCache, ArrayRef< std::shared_ptr< ModuleFileExtension >> Extensions, bool IncludeTimestamps = true, bool BuildingImplicitModule = false, bool GeneratingReducedBMI = false)
Create a new precompiled header writer that outputs to the given bitstream.
Definition at line 4674 of file ASTWriter.cpp.
~ASTWriter()
ASTWriter::~ASTWriter () override default
Member Function Documentation
AddAlignPackInfo()
void ASTWriter::AddAlignPackInfo (const Sema::AlignPackInfo & Info, RecordDataImpl & Record)
Emit a AlignPackInfo.
Definition at line 5707 of file ASTWriter.cpp.
References clang::Sema::AlignPackInfo::getRawEncoding().
AddDeclRef()
void ASTWriter::AddDeclRef (const Decl * D, RecordDataImpl & Record)
Emit a reference to a declaration.
Definition at line 5970 of file ASTWriter.cpp.
References GetDeclRef().
Referenced by clang::ASTRecordWriter::AddCXXDefinitionData(), clang::ASTRecordWriter::AddCXXTemporary(), clang::ASTRecordWriter::AddDeclRef(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddTemplateParameterList(), and clang::ASTRecordWriter::AddUnresolvedSet().
AddEmittedDeclRef()
void ASTWriter::AddEmittedDeclRef (const Decl * D, RecordDataImpl & Record)
Definition at line 5963 of file ASTWriter.cpp.
References GetDeclRef(), and wasDeclEmitted().
Referenced by AddLazyVectorEmiitedDecls().
AddFileID()
void ASTWriter::AddFileID (FileID FID, RecordDataImpl & Record)
Emit a FileID.
Definition at line 5775 of file ASTWriter.cpp.
AddIdentifierRef()
void ASTWriter::AddIdentifierRef (const IdentifierInfo * II, RecordDataImpl & Record)
Emit a reference to an identifier.
Definition at line 5795 of file ASTWriter.cpp.
References getIdentifierRef().
Referenced by clang::ASTRecordWriter::AddIdentifierRef(), and clang::ASTRecordWriter::AddNestedNameSpecifierLoc().
AddPath()
void ASTWriter::AddPath (StringRef Path, RecordDataImpl & Record)
Add a path to the given record.
Definition at line 4626 of file ASTWriter.cpp.
Referenced by clang::ASTRecordWriter::AddPath().
AddSourceLocation()
void ASTWriter::AddSourceLocation (SourceLocation Loc, RecordDataImpl & Record, LocSeq * Seq = nullptr)
Emit a source location.
Definition at line 5779 of file ASTWriter.cpp.
References clang::SourceLocationEncoding::encode(), and clang::Seq.
Referenced by clang::ASTRecordWriter::AddASTTemplateArgumentListInfo(), clang::ASTRecordWriter::AddCXXBaseSpecifier(), clang::ASTRecordWriter::AddCXXDefinitionData(), clang::ASTRecordWriter::AddDeclarationNameInfo(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddSourceLocation(), AddSourceRange(), clang::ASTRecordWriter::AddTemplateArgumentLocInfo(), and clang::ASTRecordWriter::AddTemplateParameterList().
AddSourceRange()
void ASTWriter::AddSourceRange (SourceRange Range, RecordDataImpl & Record, LocSeq * Seq = nullptr)
Emit a source range.
Definition at line 5785 of file ASTWriter.cpp.
References AddSourceLocation(), and clang::Seq.
Referenced by clang::ASTRecordWriter::AddCXXBaseSpecifier(), clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), and clang::ASTRecordWriter::AddSourceRange().
AddString()
void ASTWriter::AddString (StringRef Str, RecordDataImpl & Record)
Add a string to the given record.
Definition at line 4598 of file ASTWriter.cpp.
Referenced by clang::ASTRecordWriter::AddString().
AddToken()
void ASTWriter::AddToken (const Token & Tok, RecordDataImpl & Record)
Emit a token.
Definition at line 4553 of file ASTWriter.cpp.
References clang::Token::getAnnotationEndLoc(), clang::Token::getAnnotationValue(), clang::Token::getFlags(), clang::Token::getIdentifierInfo(), clang::Token::getKind(), clang::Token::getLength(), clang::Token::getLocation(), clang::Token::isAnnotation(), and clang::T.
AddTypeRef()
void ASTWriter::AddTypeRef (QualType T, RecordDataImpl & Record)
Emit a reference to a type.
Definition at line 5923 of file ASTWriter.cpp.
References GetOrCreateTypeID(), and clang::T.
Referenced by clang::ASTRecordWriter::AddNestedNameSpecifierLoc(), clang::ASTRecordWriter::AddTypeRef(), and clang::ASTRecordWriter::AddTypeSourceInfo().
AddVersionTuple()
void ASTWriter::AddVersionTuple (const VersionTuple & Version, RecordDataImpl & Record)
Add a version tuple to the given record.
Definition at line 4639 of file ASTWriter.cpp.
Referenced by clang::ASTRecordWriter::AddVersionTuple().
ClearSwitchCaseIDs()
void ASTWriter::ClearSwitchCaseIDs ()
Definition at line 2913 of file ASTWriterStmt.cpp.
EmitRecordWithPath()
void ASTWriter::EmitRecordWithPath (unsigned Abbrev, RecordDataRef Record, StringRef Path)
Emit the current record with the given path as a blob.
Definition at line 4632 of file ASTWriter.cpp.
getAnonymousDeclarationNumber()
unsigned ASTWriter::getAnonymousDeclarationNumber (const NamedDecl * D)
Definition at line 6077 of file ASTWriter.cpp.
References clang::Decl::getLexicalDeclContext(), clang::serialization::needsAnonymousDeclarationNumber(), and clang::serialization::numberAnonymousDeclsWithin().
getASTContext()
ASTContext& clang::ASTWriter::getASTContext () const inline
Definition at line 626 of file ASTWriter.h.
getBinaryOperatorAbbrev()
unsigned clang::ASTWriter::getBinaryOperatorAbbrev () const inline
Definition at line 813 of file ASTWriter.h.
getCallExprAbbrev()
unsigned clang::ASTWriter::getCallExprAbbrev () const inline
Definition at line 817 of file ASTWriter.h.
getChain()
ASTReader* clang::ASTWriter::getChain () const inline
Definition at line 824 of file ASTWriter.h.
getCharacterLiteralAbbrev()
unsigned clang::ASTWriter::getCharacterLiteralAbbrev () const inline
Definition at line 810 of file ASTWriter.h.
getCompoundAssignOperatorAbbrev()
unsigned clang::ASTWriter::getCompoundAssignOperatorAbbrev () const inline
Definition at line 814 of file ASTWriter.h.
getCompoundStmtAbbrev()
unsigned clang::ASTWriter::getCompoundStmtAbbrev () const inline
Definition at line 821 of file ASTWriter.h.
getCXXMemberCallExprAbbrev()
unsigned clang::ASTWriter::getCXXMemberCallExprAbbrev () inline
Definition at line 819 of file ASTWriter.h.
getCXXOperatorCallExprAbbrev()
unsigned clang::ASTWriter::getCXXOperatorCallExprAbbrev () inline
Definition at line 818 of file ASTWriter.h.
getDeclCXXMethodAbbrev()
unsigned clang::ASTWriter::getDeclCXXMethodAbbrev (FunctionDecl::TemplatedKind Kind) const inline
Definition at line 787 of file ASTWriter.h.
References clang::FunctionDecl::TK_DependentFunctionTemplateSpecialization, clang::FunctionDecl::TK_DependentNonTemplate, clang::FunctionDecl::TK_FunctionTemplate, clang::FunctionDecl::TK_FunctionTemplateSpecialization, clang::FunctionDecl::TK_MemberSpecialization, and clang::FunctionDecl::TK_NonTemplate.
getDeclEnumAbbrev()
unsigned clang::ASTWriter::getDeclEnumAbbrev () const inline
Definition at line 785 of file ASTWriter.h.
getDeclFieldAbbrev()
unsigned clang::ASTWriter::getDeclFieldAbbrev () const inline
Definition at line 784 of file ASTWriter.h.
getDeclID()
DeclID ASTWriter::getDeclID (const Decl * D)
Determine the declaration ID of an already-emitted declaration.
Definition at line 6011 of file ASTWriter.cpp.
References clang::Decl::getGlobalID(), and clang::Decl::isFromASTFile().
getDeclObjCIvarAbbrev()
unsigned clang::ASTWriter::getDeclObjCIvarAbbrev () const inline
Definition at line 786 of file ASTWriter.h.
getDeclParmVarAbbrev()
unsigned clang::ASTWriter::getDeclParmVarAbbrev () const inline
Definition at line 780 of file ASTWriter.h.
getDeclRecordAbbrev()
unsigned clang::ASTWriter::getDeclRecordAbbrev () const inline
Definition at line 781 of file ASTWriter.h.
GetDeclRef()
DeclID ASTWriter::GetDeclRef (const Decl * D)
Force a declaration to be emitted and get its ID.
Definition at line 5974 of file ASTWriter.cpp.
References clang::Decl::getGlobalID(), ID, clang::Decl::isFromASTFile(), and Iter.
Referenced by AddDeclRef(), AddEmittedDeclRef(), and AddLazyVectorDecls().
getDeclRefExprAbbrev()
unsigned clang::ASTWriter::getDeclRefExprAbbrev () const inline
Definition at line 809 of file ASTWriter.h.
getDeclTemplateTypeParmAbbrev()
unsigned clang::ASTWriter::getDeclTemplateTypeParmAbbrev () const inline
Definition at line 804 of file ASTWriter.h.
getDeclTypedefAbbrev()
unsigned clang::ASTWriter::getDeclTypedefAbbrev () const inline
Definition at line 782 of file ASTWriter.h.
getDeclUsingShadowAbbrev()
unsigned clang::ASTWriter::getDeclUsingShadowAbbrev () const inline
Definition at line 807 of file ASTWriter.h.
getDeclVarAbbrev()
unsigned clang::ASTWriter::getDeclVarAbbrev () const inline
Definition at line 783 of file ASTWriter.h.
getDoneWritingDeclsAndTypes()
bool clang::ASTWriter::getDoneWritingDeclsAndTypes () const inline
Definition at line 832 of file ASTWriter.h.
getExprImplicitCastAbbrev()
unsigned clang::ASTWriter::getExprImplicitCastAbbrev () const inline
Definition at line 812 of file ASTWriter.h.
getFirstLocalDecl()
const Decl * ASTWriter::getFirstLocalDecl (const Decl * D)
Find the first local declaration of a given local redeclarable decl.
Definition at line 1999 of file ASTWriterDecl.cpp.
References clang::Decl::getCanonicalDecl(), and clang::Decl::getPreviousDecl().
Referenced by clang::ASTDeclWriter::RegisterTemplateSpecialization().
getIdentifierRef()
IdentID ASTWriter::getIdentifierRef (const IdentifierInfo * II)
Get the unique number used to refer to the given identifier.
Definition at line 5799 of file ASTWriter.cpp.
References ID.
Referenced by AddIdentifierRef().
getIntegerLiteralAbbrev()
unsigned clang::ASTWriter::getIntegerLiteralAbbrev () const inline
Definition at line 811 of file ASTWriter.h.
getLangOpts()
const LangOptions & ASTWriter::getLangOpts () const
Definition at line 4692 of file ASTWriter.cpp.
References clang::ASTContext::getLangOpts().
getLocalOrImportedSubmoduleID()
unsigned ASTWriter::getLocalOrImportedSubmoduleID (const Module * Mod)
Retrieve or create a submodule ID for this module, or return 0 if the submodule is neither local (a submodle of the currently-written module) nor from an imported module.
Definition at line 2753 of file ASTWriter.cpp.
References clang::Module::getTopLevelModule().
getMacroDirectivesOffset()
uint32_t ASTWriter::getMacroDirectivesOffset (const IdentifierInfo * Name)
Definition at line 5833 of file ASTWriter.cpp.
getMacroID()
MacroID ASTWriter::getMacroID (MacroInfo * MI)
Determine the ID of an already-emitted macro.
Definition at line 5825 of file ASTWriter.cpp.
References clang::MacroInfo::isBuiltinMacro().
getMacroRef()
MacroID ASTWriter::getMacroRef (MacroInfo * MI, const IdentifierInfo * Name)
Get the unique number used to refer to the given macro.
Definition at line 5809 of file ASTWriter.cpp.
GetOrCreateTypeID()
TypeID ASTWriter::GetOrCreateTypeID (QualType T)
Force a type to be emitted and get its ID.
Definition at line 5927 of file ASTWriter.cpp.
References clang::serialization::TypeIdx::getIndex(), clang::serialization::MakeTypeID(), and clang::T.
Referenced by AddTypeRef().
getSelectorRef()
SelectorID ASTWriter::getSelectorRef (Selector Sel)
Get the unique number used to refer to the given selector.
Definition at line 5841 of file ASTWriter.cpp.
References clang::Selector::getAsOpaquePtr().
getSwitchCaseID()
unsigned ASTWriter::getSwitchCaseID (SwitchCase * S)
Retrieve the ID for the given switch-case statement.
Definition at line 2908 of file ASTWriterStmt.cpp.
getTimestampForOutput()
time_t ASTWriter::getTimestampForOutput (const FileEntry * E) const
Get a timestamp for output into the AST file.
The actual timestamp of the specified file may be ignored if we have been instructed to not include timestamps in the output file.
Definition at line 4697 of file ASTWriter.cpp.
References clang::FileEntry::getModificationTime().
getTypeExtQualAbbrev()
unsigned clang::ASTWriter::getTypeExtQualAbbrev () const inline
Definition at line 776 of file ASTWriter.h.
getTypeID()
TypeID ASTWriter::getTypeID (QualType T) const
Determine the type ID of an already-emitted type.
Definition at line 5950 of file ASTWriter.cpp.
References clang::serialization::MakeTypeID(), and clang::T.
hasChain()
bool clang::ASTWriter::hasChain () const inline
Definition at line 823 of file ASTWriter.h.
isGeneratingReducedBMI()
bool clang::ASTWriter::isGeneratingReducedBMI () const inline
Definition at line 830 of file ASTWriter.h.
IsLocalDecl()
bool clang::ASTWriter::IsLocalDecl (const Decl * D) inline
Is this a local declaration (that is, one that will be written to our AST file)? This is the case for declarations that are neither imported from another AST file nor predefined.
Definition at line 707 of file ASTWriter.h.
References clang::Decl::isFromASTFile(), and clang::serialization::NUM_PREDEF_DECL_IDS.
isWritingStdCXXNamedModules()
bool clang::ASTWriter::isWritingStdCXXNamedModules () const inline
Definition at line 826 of file ASTWriter.h.
References clang::Module::isNamedModule().
PreparePathForOutput()
bool ASTWriter::PreparePathForOutput (SmallVectorImpl< char > & Path)
Convert a path from this build process into one that is appropriate for emission in the module file.
Definition at line 4603 of file ASTWriter.cpp.
RecordSwitchCaseID()
unsigned ASTWriter::RecordSwitchCaseID (SwitchCase * S)
Record an ID for the given switch-case statement.
Definition at line 2901 of file ASTWriterStmt.cpp.
SetIdentifierOffset()
void ASTWriter::SetIdentifierOffset (const IdentifierInfo * II, uint32_t Offset)
Note that the identifier II occurs at the given offset within the identifier table.
Definition at line 4654 of file ASTWriter.cpp.
References ID, and Offset.
SetSelectorOffset()
void ASTWriter::SetSelectorOffset (Selector Sel, uint32_t Offset)
Note that the selector Sel occurs at the given offset within the method pool/selector table.
Definition at line 4664 of file ASTWriter.cpp.
References ID, and Offset.
wasDeclEmitted()
bool ASTWriter::wasDeclEmitted (const Decl * D) const
Whether or not the declaration got emitted.
If not, it wouldn't be emitted.
This may only be called after we've done the job to write the declarations (marked by DoneWritingDeclsAndTypes).
A declaration may only be omitted in reduced BMI.
Definition at line 6024 of file ASTWriter.cpp.
References clang::Decl::isFromASTFile().
Referenced by AddEmittedDeclRef().
WriteAST()
ASTFileSignature ASTWriter::WriteAST (Sema & SemaRef, StringRef OutputFile, Module * WritingModule, StringRef isysroot, bool ShouldCacheASTInMemory = false)
Write a precompiled header for the given semantic analysis.
Parameters
SemaRef a reference to the semantic analysis object that processed the AST to be written into the precompiled header.
WritingModule The module that we are writing. If null, we are writing a precompiled header.
isysroot if non-empty, write a relocatable file whose headers are relative to the given system root. If we're writing a module, its build directory will be used in preference to this if both are available.
Returns
the module signature, which eventually will be a hash of the module but currently is merely a random 32-bit number.
Definition at line 4701 of file ASTWriter.cpp.
References clang::InMemoryModuleCache::addBuiltPCM(), clang::Sema::Context, clang::Preprocessor::getDiagnostics(), clang::DiagnosticsEngine::hasUncompilableErrorOccurred(), and clang::Sema::PP.
Referenced by clang::PCHGenerator::HandleTranslationUnit().
Friends And Related Function Documentation
ASTDeclWriter
friend class ASTDeclWriter friend
Definition at line 88 of file ASTWriter.h.
ASTRecordWriter
friend class ASTRecordWriter friend
Definition at line 89 of file ASTWriter.h.
The documentation for this class was generated from the following files:
include/clang/Serialization/ASTWriter.h
lib/Serialization/ASTWriter.cpp
lib/Serialization/ASTWriterDecl.cpp
lib/Serialization/ASTWriterStmt.cpp