clang: clang::SemaAMDGPU Class Reference
clang::SemaAMDGPU Class Reference
#include "clang/Sema/SemaAMDGPU.h"
Public Member Functions
SemaAMDGPU (Sema &S)
bool CheckAMDGCNBuiltinFunctionCall (unsigned BuiltinID, CallExpr *TheCall)
AMDGPUFlatWorkGroupSizeAttr * CreateAMDGPUFlatWorkGroupSizeAttr (const AttributeCommonInfo &CI, Expr *Min, Expr *Max)
Create an AMDGPUWavesPerEUAttr attribute.
void addAMDGPUFlatWorkGroupSizeAttr (Decl *D, const AttributeCommonInfo &CI, Expr *Min, Expr *Max)
addAMDGPUFlatWorkGroupSizeAttr - Adds an amdgpu_flat_work_group_size attribute to a particular declaration.
AMDGPUWavesPerEUAttr * CreateAMDGPUWavesPerEUAttr (const AttributeCommonInfo &CI, Expr *Min, Expr *Max)
Create an AMDGPUWavesPerEUAttr attribute.
void addAMDGPUWavesPerEUAttr (Decl *D, const AttributeCommonInfo &CI, Expr *Min, Expr *Max)
addAMDGPUWavePersEUAttr - Adds an amdgpu_waves_per_eu attribute to a particular declaration.
AMDGPUMaxNumWorkGroupsAttr * CreateAMDGPUMaxNumWorkGroupsAttr (const AttributeCommonInfo &CI, Expr *XExpr, Expr *YExpr, Expr *ZExpr)
Create an AMDGPUMaxNumWorkGroupsAttr attribute.
void addAMDGPUMaxNumWorkGroupsAttr (Decl *D, const AttributeCommonInfo &CI, Expr *XExpr, Expr *YExpr, Expr *ZExpr)
addAMDGPUMaxNumWorkGroupsAttr - Adds an amdgpu_max_num_work_groups attribute to a particular declaration.
void handleAMDGPUWavesPerEUAttr (Decl *D, const ParsedAttr &AL)
void handleAMDGPUNumSGPRAttr (Decl *D, const ParsedAttr &AL)
void handleAMDGPUNumVGPRAttr (Decl *D, const ParsedAttr &AL)
void handleAMDGPUMaxNumWorkGroupsAttr (Decl *D, const ParsedAttr &AL)
void handleAMDGPUFlatWorkGroupSizeAttr (Decl *D, const ParsedAttr &AL)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 24 of file SemaAMDGPU.h.
Constructor & Destructor Documentation
SemaAMDGPU()
clang::SemaAMDGPU::SemaAMDGPU (Sema & S)
Definition at line 23 of file SemaAMDGPU.cpp.
Member Function Documentation
addAMDGPUFlatWorkGroupSizeAttr()
void clang::SemaAMDGPU::addAMDGPUFlatWorkGroupSizeAttr (Decl * D, const AttributeCommonInfo & CI, Expr * Min, Expr * Max)
addAMDGPUFlatWorkGroupSizeAttr - Adds an amdgpu_flat_work_group_size attribute to a particular declaration.
Definition at line 153 of file SemaAMDGPU.cpp.
References CreateAMDGPUFlatWorkGroupSizeAttr(), and D.
Referenced by handleAMDGPUFlatWorkGroupSizeAttr().
addAMDGPUMaxNumWorkGroupsAttr()
void clang::SemaAMDGPU::addAMDGPUMaxNumWorkGroupsAttr (Decl * D, const AttributeCommonInfo & CI, Expr * XExpr, Expr * YExpr, Expr * ZExpr)
addAMDGPUMaxNumWorkGroupsAttr - Adds an amdgpu_max_num_work_groups attribute to a particular declaration.
Definition at line 296 of file SemaAMDGPU.cpp.
References CreateAMDGPUMaxNumWorkGroupsAttr(), and D.
Referenced by handleAMDGPUMaxNumWorkGroupsAttr().
addAMDGPUWavesPerEUAttr()
void clang::SemaAMDGPU::addAMDGPUWavesPerEUAttr (Decl * D, const AttributeCommonInfo & CI, Expr * Min, Expr * Max)
addAMDGPUWavePersEUAttr - Adds an amdgpu_waves_per_eu attribute to a particular declaration.
Definition at line 214 of file SemaAMDGPU.cpp.
References CreateAMDGPUWavesPerEUAttr(), and D.
Referenced by handleAMDGPUWavesPerEUAttr().
CheckAMDGCNBuiltinFunctionCall()
bool clang::SemaAMDGPU::CheckAMDGCNBuiltinFunctionCall (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 25 of file SemaAMDGPU.cpp.
References clang::SemaBase::Diag(), clang::ActionResult< PtrTy, Compress >::get(), clang::CallExpr::getArg(), clang::SemaBase::getASTContext(), clang::Expr::getExprLoc(), clang::APValue::getInt(), clang::Stmt::getSourceRange(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::SemaBase::SemaRef, clang::Expr::EvalResult::Val, and clang::Sema::VerifyIntegerConstantExpression().
CreateAMDGPUFlatWorkGroupSizeAttr()
AMDGPUFlatWorkGroupSizeAttr * clang::SemaAMDGPU::CreateAMDGPUFlatWorkGroupSizeAttr (const AttributeCommonInfo & CI, Expr * Min, Expr * Max)
Create an AMDGPUWavesPerEUAttr attribute.
Definition at line 142 of file SemaAMDGPU.cpp.
Referenced by addAMDGPUFlatWorkGroupSizeAttr().
CreateAMDGPUMaxNumWorkGroupsAttr()
AMDGPUMaxNumWorkGroupsAttr * clang::SemaAMDGPU::CreateAMDGPUMaxNumWorkGroupsAttr (const AttributeCommonInfo & CI, Expr * XExpr, Expr * YExpr, Expr * ZExpr)
Create an AMDGPUMaxNumWorkGroupsAttr attribute.
Definition at line 283 of file SemaAMDGPU.cpp.
Referenced by addAMDGPUMaxNumWorkGroupsAttr().
CreateAMDGPUWavesPerEUAttr()
AMDGPUWavesPerEUAttr * clang::SemaAMDGPU::CreateAMDGPUWavesPerEUAttr (const AttributeCommonInfo & CI, Expr * Min, Expr * Max)
Create an AMDGPUWavesPerEUAttr attribute.
Definition at line 203 of file SemaAMDGPU.cpp.
Referenced by addAMDGPUWavesPerEUAttr().
handleAMDGPUFlatWorkGroupSizeAttr()
void clang::SemaAMDGPU::handleAMDGPUFlatWorkGroupSizeAttr (Decl * D, const ParsedAttr & AL)
Definition at line 160 of file SemaAMDGPU.cpp.
References addAMDGPUFlatWorkGroupSizeAttr(), D, and clang::ParsedAttr::getArgAsExpr().
handleAMDGPUMaxNumWorkGroupsAttr()
void clang::SemaAMDGPU::handleAMDGPUMaxNumWorkGroupsAttr (Decl * D, const ParsedAttr & AL)
Definition at line 304 of file SemaAMDGPU.cpp.
References addAMDGPUMaxNumWorkGroupsAttr(), D, clang::ParsedAttr::getArgAsExpr(), and clang::ParsedAttr::getNumArgs().
handleAMDGPUNumSGPRAttr()
void clang::SemaAMDGPU::handleAMDGPUNumSGPRAttr (Decl * D, const ParsedAttr & AL)
Definition at line 230 of file SemaAMDGPU.cpp.
References clang::Sema::checkUInt32Argument(), D, clang::ParsedAttr::getArgAsExpr(), clang::SemaBase::getASTContext(), and clang::SemaBase::SemaRef.
handleAMDGPUNumVGPRAttr()
void clang::SemaAMDGPU::handleAMDGPUNumVGPRAttr (Decl * D, const ParsedAttr & AL)
Definition at line 240 of file SemaAMDGPU.cpp.
References clang::Sema::checkUInt32Argument(), D, clang::ParsedAttr::getArgAsExpr(), clang::SemaBase::getASTContext(), and clang::SemaBase::SemaRef.
handleAMDGPUWavesPerEUAttr()
void clang::SemaAMDGPU::handleAMDGPUWavesPerEUAttr (Decl * D, const ParsedAttr & AL)
Definition at line 220 of file SemaAMDGPU.cpp.
References addAMDGPUWavesPerEUAttr(), clang::ParsedAttr::checkAtLeastNumArgs(), clang::ParsedAttr::checkAtMostNumArgs(), D, clang::ParsedAttr::getArgAsExpr(), clang::ParsedAttr::getNumArgs(), and clang::SemaBase::SemaRef.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaAMDGPU.h
lib/Sema/SemaAMDGPU.cpp