clang: clang::TypeCoupledDeclRefInfo Class Reference
clang::TypeCoupledDeclRefInfo Class Reference
[BoundsSafety] Represents information of declarations referenced by the arguments of the counted_by attribute and the likes.
#include "clang/AST/Type.h"
Public Types
using BaseTy = llvm::PointerIntPair< ValueDecl *, 1, unsigned >
Public Member Functions
TypeCoupledDeclRefInfo (ValueDecl *D=nullptr, bool Deref=false)
D is to a declaration referenced by the argument of attribute.
bool isDeref () const
ValueDecl * getDecl () const
unsigned getInt () const
void * getOpaqueValue () const
bool operator== (const TypeCoupledDeclRefInfo &Other) const
void setFromOpaqueValue (void *V)
Detailed Description
[BoundsSafety] Represents information of declarations referenced by the arguments of the counted_by attribute and the likes.
Definition at line 2967 of file Type.h.
Member Typedef Documentation
BaseTy
using clang::TypeCoupledDeclRefInfo::BaseTy = llvm::PointerIntPair<ValueDecl *, 1, unsigned>
Definition at line 2969 of file Type.h.
Constructor & Destructor Documentation
TypeCoupledDeclRefInfo()
TypeCoupledDeclRefInfo::TypeCoupledDeclRefInfo (ValueDecl * D = nullptr, bool Deref = false)
D is to a declaration referenced by the argument of attribute.
Deref indicates whether D is referenced as a dereferenced form, e.g., Deref is true for *n in int *__counted_by(*n).
Definition at line 3772 of file Type.cpp.
References Data.
Member Function Documentation
getDecl()
ValueDecl * TypeCoupledDeclRefInfo::getDecl () const
Definition at line 3778 of file Type.cpp.
Referenced by clang::BoundsAttributedType::referencesFieldDecls(), and clang::ASTRecordWriter::writeTypeCoupledDeclRefInfo().
getInt()
unsigned TypeCoupledDeclRefInfo::getInt () const
Definition at line 3779 of file Type.cpp.
getOpaqueValue()
void * TypeCoupledDeclRefInfo::getOpaqueValue () const
Definition at line 3780 of file Type.cpp.
Referenced by operator==().
isDeref()
bool TypeCoupledDeclRefInfo::isDeref () const
Definition at line 3775 of file Type.cpp.
Referenced by clang::ASTRecordWriter::writeTypeCoupledDeclRefInfo().
operator==()
bool TypeCoupledDeclRefInfo::operator== (const TypeCoupledDeclRefInfo & Other) const
Definition at line 3783 of file Type.cpp.
References getOpaqueValue(), and clang::Other.
setFromOpaqueValue()
void TypeCoupledDeclRefInfo::setFromOpaqueValue (void * V)
Definition at line 3787 of file Type.cpp.
References V.
The documentation for this class was generated from the following files:
include/clang/AST/Type.h
lib/AST/Type.cpp