clang: clang::format::FormatTokenSource Class Reference
clang::format::FormatTokenSource Class Reference abstract
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Format/FormatTokenSource.h"
Public Member Functions
virtual ~FormatTokenSource ()
virtual FormatToken * getNextToken ()=0
virtual FormatToken * getPreviousToken ()=0
virtual FormatToken * peekNextToken (bool SkipComment=false)=0
virtual bool isEOF ()=0
virtual unsigned getPosition ()=0
virtual FormatToken * setPosition (unsigned Position)=0
virtual FormatToken * insertTokens (ArrayRef< FormatToken * > Tokens)=0
FormatToken * getNextNonComment ()
Detailed Description
Definition at line 29 of file FormatTokenSource.h.
Constructor & Destructor Documentation
~FormatTokenSource()
virtual clang::format::FormatTokenSource::~FormatTokenSource () inline virtual
Definition at line 31 of file FormatTokenSource.h.
Member Function Documentation
getNextNonComment()
FormatToken* clang::format::FormatTokenSource::getNextNonComment () inline
Definition at line 76 of file FormatTokenSource.h.
References getNextToken(), and clang::format::FormatToken::is().
getNextToken()
virtual FormatToken* clang::format::FormatTokenSource::getNextToken () pure virtual
Implemented in clang::format::ScopedMacroState, and clang::format::IndexedTokenSource.
Referenced by getNextNonComment(), and clang::format::ScopedMacroState::getNextToken().
getPosition()
virtual unsigned clang::format::FormatTokenSource::getPosition () pure virtual
Implemented in clang::format::ScopedMacroState, and clang::format::IndexedTokenSource.
Referenced by clang::format::ScopedMacroState::getPosition().
getPreviousToken()
virtual FormatToken* clang::format::FormatTokenSource::getPreviousToken () pure virtual
Implemented in clang::format::ScopedMacroState, and clang::format::IndexedTokenSource.
Referenced by clang::format::ScopedMacroState::getPreviousToken().
insertTokens()
virtual FormatToken* clang::format::FormatTokenSource::insertTokens (ArrayRef< FormatToken * > Tokens) pure virtual
Implemented in clang::format::ScopedMacroState, and clang::format::IndexedTokenSource.
isEOF()
virtual bool clang::format::FormatTokenSource::isEOF () pure virtual
Implemented in clang::format::ScopedMacroState, and clang::format::IndexedTokenSource.
Referenced by clang::format::ScopedMacroState::isEOF().
peekNextToken()
virtual FormatToken* clang::format::FormatTokenSource::peekNextToken (bool SkipComment = false) pure virtual
Implemented in clang::format::IndexedTokenSource, and clang::format::ScopedMacroState.
Referenced by clang::format::ScopedMacroState::peekNextToken().
setPosition()
virtual FormatToken* clang::format::FormatTokenSource::setPosition (unsigned Position) pure virtual
Implemented in clang::format::ScopedMacroState, and clang::format::IndexedTokenSource.
Referenced by clang::format::ScopedMacroState::setPosition().
The documentation for this class was generated from the following file:
lib/Format/FormatTokenSource.h