clang: clang::arcmt::CapturedDiagList Class Reference
clang::arcmt::CapturedDiagList Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/ARCMigrate/Internals.h"
Public Types
typedef ListTy::const_iterator iterator
Public Member Functions
void push_back (const StoredDiagnostic &diag)
bool clearDiagnostic (ArrayRef< unsigned > IDs, SourceRange range)
bool hasDiagnostic (ArrayRef< unsigned > IDs, SourceRange range) const
void reportDiagnostics (DiagnosticsEngine &diags) const
bool hasErrors () const
iterator begin () const
iterator end () const
Detailed Description
Definition at line 26 of file Internals.h.
Member Typedef Documentation
iterator
typedef ListTy::const_iterator clang::arcmt::CapturedDiagList::iterator
Definition at line 40 of file Internals.h.
Member Function Documentation
begin()
iterator clang::arcmt::CapturedDiagList::begin () const inline
Definition at line 41 of file Internals.h.
Referenced by clang::arcmt::checkForManualIssues().
clearDiagnostic()
bool CapturedDiagList::clearDiagnostic (ArrayRef< unsigned > IDs, SourceRange range)
Definition at line 29 of file ARCMT.cpp.
References clang::FullSourceLoc::isBeforeInTranslationUnitThan(), clang::DiagnosticsEngine::Note, and clang::transformer::range().
end()
iterator clang::arcmt::CapturedDiagList::end () const inline
Definition at line 42 of file Internals.h.
Referenced by clang::arcmt::checkForManualIssues().
hasDiagnostic()
bool CapturedDiagList::hasDiagnostic (ArrayRef< unsigned > IDs, SourceRange range) const
Definition at line 59 of file ARCMT.cpp.
References clang::FullSourceLoc::isBeforeInTranslationUnitThan(), and clang::transformer::range().
Referenced by clang::arcmt::TransformActions::hasDiagnostic().
hasErrors()
bool CapturedDiagList::hasErrors () const
Definition at line 86 of file ARCMT.cpp.
References clang::DiagnosticsEngine::Error.
Referenced by clang::arcmt::MigrationProcess::applyTransform(), and clang::arcmt::checkForManualIssues().
push_back()
void clang::arcmt::CapturedDiagList::push_back (const StoredDiagnostic & diag) inline
Definition at line 31 of file Internals.h.
reportDiagnostics()
void CapturedDiagList::reportDiagnostics (DiagnosticsEngine & diags) const
Definition at line 81 of file ARCMT.cpp.
References clang::DiagnosticsEngine::Report().
Referenced by clang::arcmt::MigrationProcess::applyTransform(), clang::arcmt::checkForManualIssues(), and emitPremigrationErrors().
The documentation for this class was generated from the following files:
lib/ARCMigrate/Internals.h
lib/ARCMigrate/ARCMT.cpp