clang: clang::ento::UnarySymExpr Class Reference
clang::ento::UnarySymExpr Class Reference
Represents a symbolic expression involving a unary operator.
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
Public Member Functions
UnarySymExpr (const SymExpr *In, UnaryOperator::Opcode Op, QualType T)
unsigned computeComplexity () const override
const SymExpr * getOperand () const
UnaryOperator::Opcode getOpcode () const
QualType getType () const override
void dumpToStream (raw_ostream &os) const override
void Profile (llvm::FoldingSetNodeID &ID) override
Public Member Functions inherited from clang::ento::SymExpr
virtual ~SymExpr ()=default
Kind getKind () const
virtual void dump () const
llvm::iterator_range< symbol_iterator > symbols () const
virtual const MemRegion * getOriginRegion () const
Find the region from which this symbol originates.
Static Public Member Functions
static void Profile (llvm::FoldingSetNodeID &ID, const SymExpr *In, UnaryOperator::Opcode Op, QualType T)
static bool classof (const SymExpr *SE)
Additional Inherited Members
Public Types inherited from clang::ento::SymExpr
enum Kind
Protected Member Functions inherited from clang::ento::SymExpr
SymExpr (Kind k)
Static Protected Member Functions inherited from clang::ento::SymExpr
static bool isValidTypeForSymbol (QualType T)
Protected Attributes inherited from clang::ento::SymExpr
unsigned Complexity = 0
Detailed Description
Represents a symbolic expression involving a unary operator.
Definition at line 329 of file SymbolManager.h.
Constructor & Destructor Documentation
UnarySymExpr()
clang::ento::UnarySymExpr::UnarySymExpr (const SymExpr * In, UnaryOperator::Opcode Op, QualType T) inline
Definition at line 335 of file SymbolManager.h.
References clang::ento::Loc::isLocType(), clang::ento::SymExpr::isValidTypeForSymbol(), and clang::T.
Member Function Documentation
classof()
static bool clang::ento::UnarySymExpr::classof (const SymExpr * SE) inline static
Definition at line 372 of file SymbolManager.h.
References clang::ento::SymExpr::getKind().
computeComplexity()
unsigned clang::ento::UnarySymExpr::computeComplexity () const inline override virtual
Implements clang::ento::SymExpr.
Definition at line 347 of file SymbolManager.h.
References clang::ento::SymExpr::Complexity.
dumpToStream()
void UnarySymExpr::dumpToStream (raw_ostream & os) const override virtual
Reimplemented from clang::ento::SymExpr.
Definition at line 73 of file SymbolManager.cpp.
References clang::ento::SymExpr::dumpToStream(), and clang::UnaryOperator::getOpcodeStr().
getOpcode()
UnaryOperator::Opcode clang::ento::UnarySymExpr::getOpcode () const inline
Definition at line 354 of file SymbolManager.h.
getOperand()
const SymExpr* clang::ento::UnarySymExpr::getOperand () const inline
Definition at line 353 of file SymbolManager.h.
getType()
QualType clang::ento::UnarySymExpr::getType () const inline override virtual
Implements clang::ento::SymExpr.
Definition at line 355 of file SymbolManager.h.
References clang::T.
Profile() [1/2]
void clang::ento::UnarySymExpr::Profile (llvm::FoldingSetNodeID & ID) inline override virtual
Implements clang::ento::SymExpr.
Definition at line 367 of file SymbolManager.h.
References ID, Profile(), and clang::T.
Profile() [2/2]
static void clang::ento::UnarySymExpr::Profile (llvm::FoldingSetNodeID & ID, const SymExpr * In, UnaryOperator::Opcode Op, QualType T) inline static
Definition at line 359 of file SymbolManager.h.
References ID, and clang::T.
Referenced by Profile().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h
lib/StaticAnalyzer/Core/SymbolManager.cpp