clang: clang::driver::toolchains::CudaToolChain Class Reference
clang::driver::toolchains::CudaToolChain Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/Cuda.h"
Public Member Functions
CudaToolChain (const Driver &D, const llvm::Triple &Triple, const ToolChain &HostTC, const llvm::opt::ArgList &Args, const Action::OffloadKind OK)
CUDA toolchain.
const llvm::Triple * getAuxTriple () const override
Get the toolchain's aux triple, if it has one.
std::string getInputFilename (const InputInfo &Input) const override
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
llvm::opt::DerivedArgList * TranslateArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
void addClangTargetOptions (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, Action::OffloadKind DeviceOffloadKind) const override
Add options that need to be passed to cc1 for this target.
llvm::DenormalMode getDefaultDenormalModeForType (const llvm::opt::ArgList &DriverArgs, const JobAction &JA, const llvm::fltSemantics *FPType=nullptr) const override
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
bool useIntegratedAs () const override
Check if the toolchain should use the integrated assembler.
bool isCrossCompiling () const override
Returns true if the toolchain is targeting a non-native architecture.
bool isPICDefault () const override
Test whether this toolchain defaults to PIC.
bool isPIEDefault (const llvm::opt::ArgList &Args) const override
Test whether this toolchain defaults to PIE.
bool isPICDefaultForced () const override
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
bool SupportsProfiling () const override
SupportsProfiling - Does this tool chain support -pg.
bool supportsDebugInfoOption (const llvm::opt::Arg *A) const override
Does this toolchain supports given debug info option or not.
void adjustDebugInfoKind (codegenoptions::DebugInfoKind &DebugInfoKind, const llvm::opt::ArgList &Args) const override
Adjust debug information kind considering all passed options.
bool IsMathErrnoDefault () const override
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use system-specific CUDA includes.
void addClangWarningOptions (llvm::opt::ArgStringList &CC1Args) const override
Add warning options that need to be passed to cc1 for this target.
CXXStdlibType GetCXXStdlibType (const llvm::opt::ArgList &Args) const override
void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add the clang cc1 arguments for system include paths.
void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CC1Args) const override
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
void AddIAMCUIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const override
Add arguments to use MCU GCC toolchain includes.
SanitizerMask getSupportedSanitizers () const override
Return sanitizers which are available in this toolchain.
VersionTuple computeMSVCVersion (const Driver *D, const llvm::opt::ArgList &Args) const override
On Windows, returns the MSVC compatibility version.
unsigned GetDefaultDwarfVersion () const override
unsigned getMaxDwarfVersion () const override
Tool * SelectTool (const JobAction &JA) const override
Choose a tool to use to handle the action JA.
Public Member Functions inherited from clang::driver::ToolChain
virtual ~ToolChain ()
const Driver & getDriver () const
llvm::vfs::FileSystem & getVFS () const
const llvm::Triple & getTriple () const
llvm::Triple::ArchType getArch () const
StringRef getArchName () const
StringRef getPlatform () const
StringRef getOS () const
StringRef getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
std::string getTripleString () const
const llvm::Triple & getEffectiveTriple () const
Get the toolchain's effective clang triple.
path_list & getLibraryPaths ()
const path_list & getLibraryPaths () const
path_list & getFilePaths ()
const path_list & getFilePaths () const
path_list & getProgramPaths ()
const path_list & getProgramPaths () const
const MultilibSet & getMultilibs () const
const Multilib & getMultilib () const
SanitizerArgs getSanitizerArgs (const llvm::opt::ArgList &JobArgs) const
const XRayArgs & getXRayArgs () const
const llvm::opt::Arg * getRTTIArg () const
RTTIMode getRTTIMode () const
virtual llvm::opt::DerivedArgList * TranslateOffloadTargetArgs (const llvm::opt::DerivedArgList &Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > &AllocatedArgs, Action::OffloadKind DeviceOffloadKind) const
TranslateOffloadTargetArgs - Create a new derived argument list for that contains the Offload target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val Also handles -Xsycl-target OR -Xsycl-target=<triple>
virtual void TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, llvm::opt::Arg *&A, llvm::opt::DerivedArgList *DAL, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs=nullptr) const
Append the argument following A to DAL assuming A is an Xarch argument.
virtual llvm::opt::DerivedArgList * TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs) const
Translate -Xarch_ arguments.
std::string GetFilePath (const char *Name) const
std::string GetProgramPath (const char *Name) const
std::string GetLinkerPath (bool *LinkerIsLLD=nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
std::string GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
virtual void printVerboseInfo (raw_ostream &OS) const
Dispatch to the specific toolchain for verbose printing.
virtual bool HasNativeLLVMSupport () const
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
virtual types::ID LookupTypeForExtension (StringRef Ext) const
LookupTypeForExtension - Return the default language type to use for the given extension.
virtual bool IsBlocksDefault () const
IsBlocksDefault - Does this tool chain enable -fblocks by default.
virtual bool IsIntegratedAssemblerDefault () const
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
virtual bool useIntegratedBackend () const
Check if the toolchain should use the integrated backend.
virtual bool parseInlineAsmUsingAsmParser () const
Check if the toolchain should use AsmParser to parse inlineAsm when integrated assembler is not default.
virtual bool IsEncodeExtendedBlockSignatureDefault () const
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
virtual bool IsObjCNonFragileABIDefault () const
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
virtual bool UseObjCMixedDispatch () const
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
virtual bool useRelaxRelocations () const
Check whether to enable x86 relax relocations by default.
bool defaultToIEEELongDouble () const
Check whether use IEEE binary128 as long double format by default.
virtual LangOptions::StackProtectorMode GetDefaultStackProtectorLevel (bool KernelOrKext) const
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
virtual LangOptions::TrivialAutoVarInitKind GetDefaultTrivialAutoVarInit () const
Get the default trivial automatic variable initialization.
virtual const char * getDefaultLinker () const
GetDefaultLinker - Get the default linker to use.
virtual RuntimeLibType GetDefaultRuntimeLibType () const
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
virtual CXXStdlibType GetDefaultCXXStdlibType () const
virtual UnwindLibType GetDefaultUnwindLibType () const
virtual std::string getCompilerRTPath () const
virtual std::string getCompilerRT (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
const char * getCompilerRTArgString (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::string getCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
path_list getRuntimePaths () const
path_list getStdlibPaths () const
std::string getArchSpecificLibPath () const
virtual StringRef getOSLibName () const
virtual bool IsUnwindTablesDefault (const llvm::opt::ArgList &Args) const
IsUnwindTablesDefault - Does this tool chain use -funwind-tables by default.
virtual bool IsAArch64OutlineAtomicsDefault (const llvm::opt::ArgList &Args) const
Test whether this toolchain supports outline atomics by default.
virtual void CheckObjCARC () const
Complain if this tool chain doesn't support Objective-C ARC.
virtual codegenoptions::DebugInfoFormat getDefaultDebugFormat () const
Get the default debug info format. Typically, this is DWARF.
virtual bool UseDwarfDebugFlags () const
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
virtual std::string GetGlobalDebugPathRemapping () const
Add an additional -fdebug-prefix-map entry.
virtual bool GetDefaultStandaloneDebug () const
virtual llvm::DebuggerKind getDefaultDebuggerTuning () const
virtual llvm::ExceptionHandling GetExceptionModel (const llvm::opt::ArgList &Args) const
GetExceptionModel - Return the tool chain exception model.
virtual bool SupportsEmbeddedBitcode () const
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
virtual std::string getThreadModel () const
getThreadModel() - Which thread model does this target use?
virtual bool isThreadModelSupported (const StringRef Model) const
isThreadModelSupported() - Does this target support a thread model?
virtual std::string getMultiarchTriple (const Driver &D, const llvm::Triple &TargetTriple, StringRef SysRoot) const
virtual std::string ComputeLLVMTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
virtual std::string ComputeEffectiveClangTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
virtual ObjCRuntime getDefaultObjCRuntime (bool isNonFragile) const
getDefaultObjCRuntime - Return the default Objective-C runtime for this platform.
virtual bool hasBlocksRuntime () const
hasBlocksRuntime - Given that the user is compiling with -fblocks, does this tool chain guarantee the existence of a blocks runtime?
virtual std::string computeSysRoot () const
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
virtual RuntimeLibType GetRuntimeLibType (const llvm::opt::ArgList &Args) const
virtual UnwindLibType GetUnwindLibType (const llvm::opt::ArgList &Args) const
virtual std::string detectLibcxxVersion (StringRef IncludePath) const
void AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
bool ShouldLinkCXXStdlib (const llvm::opt::ArgList &Args) const
Returns if the C++ standard library should be linked in.
virtual void AddCXXStdlibLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
void AddFilePathLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
virtual void AddCCKextLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
virtual bool isFastMathRuntimeAvailable (const llvm::opt::ArgList &Args, std::string &Path) const
If a runtime library exists that sets global flags for unsafe floating point math, return true.
bool addFastMathRuntimeIfAvailable (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
virtual void addProfileRTLibs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
addProfileRTLibs - When -fprofile-instr-profile is specified, try to pass a suitable profile runtime library to the linker.
virtual void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific HIP includes.
virtual llvm::SmallVector< BitCodeLibraryInfo, 12 > getHIPDeviceLibs (const llvm::opt::ArgList &Args, const Action::OffloadKind DeviceOffloadingKind) const
Get paths of HIP device libraries.
virtual SanitizerMask getDefaultSanitizers () const
Return sanitizers which are enabled by default.
virtual bool canSplitThinLTOUnit () const
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
Public Attributes
const ToolChain & HostTC
CudaInstallationDetector CudaInstallation
Protected Member Functions
Tool * buildAssembler () const override
Tool * buildLinker () const override
Protected Member Functions inherited from clang::driver::ToolChain
ToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
void setTripleEnvironment (llvm::Triple::EnvironmentType Env)
virtual Tool * buildBackendCompiler () const
virtual Tool * buildStaticLibTool () const
virtual Tool * getTool (Action::ActionClass AC) const
virtual std::string buildCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type, bool AddArch) const
Additional Inherited Members
Public Types inherited from clang::driver::ToolChain
enum CXXStdlibType { CST_Libcxx, CST_Libstdcxx }
enum RuntimeLibType { RLT_CompilerRT, RLT_Libgcc }
enum UnwindLibType { UNW_None, UNW_CompilerRT, UNW_Libgcc }
enum RTTIMode { RM_Enabled, RM_Disabled }
enum FileType { FT_Object, FT_Static, FT_Shared }
using path_list = SmallVector< std::string, 16 >
Static Public Member Functions inherited from clang::driver::ToolChain
static ParsedClangName getTargetAndModeFromProgramName (StringRef ProgName)
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
static bool needsProfileRT (const llvm::opt::ArgList &Args)
needsProfileRT - returns true if instrumentation profile is on.
static bool needsGCovInstrumentation (const llvm::opt::ArgList &Args)
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
static llvm::Triple getOpenMPTriple (StringRef TripleStr)
Static Protected Member Functions inherited from clang::driver::ToolChain
static void addSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory to CC1 arguments.
static void addExternCSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
static void addExternCSystemIncludeIfExists (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
static void addSystemIncludes (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, ArrayRef< StringRef > Paths)
Utility function to add a list of system include directories to CC1.
Protected Attributes inherited from clang::driver::ToolChain
MultilibSet Multilibs
Multilib SelectedMultilib
Detailed Description
Definition at line 151 of file Cuda.h.
Constructor & Destructor Documentation
CudaToolChain()
CudaToolChain::CudaToolChain (const Driver & D, const llvm::Triple & Triple, const ToolChain & HostTC, const llvm::opt::ArgList & Args, const Action::OffloadKind OK)
CUDA toolchain.
Our assembler is ptxas, and our "linker" is fatbinary, which isn't properly a linker but nonetheless performs the step of stitching together object files from the assembler into a single blob.
Definition at line 689 of file Cuda.cpp.
References CudaInstallation, clang::driver::CudaInstallationDetector::getBinPath(), clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getProgramPaths(), clang::driver::CudaInstallationDetector::isValid(), string(), and clang::driver::CudaInstallationDetector::WarnIfUnsupportedVersion().
Member Function Documentation
AddClangCXXStdlibIncludeArgs()
void CudaToolChain::AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
Reimplemented from clang::driver::ToolChain.
Definition at line 992 of file Cuda.cpp.
References clang::driver::ToolChain::AddClangCXXStdlibIncludeArgs(), and HostTC.
AddClangSystemIncludeArgs()
void CudaToolChain::AddClangSystemIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add the clang cc1 arguments for system include paths.
This routine is responsible for adding the necessary cc1 arguments to include headers from standard system header directories.
Reimplemented from clang::driver::ToolChain.
Definition at line 978 of file Cuda.cpp.
References clang::driver::ToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::SYCLToolChain::AddSYCLIncludeArgs(), CudaInstallation, clang::driver::ToolChain::getDriver(), clang::driver::CudaInstallationDetector::getIncludePath(), HostTC, and clang::driver::CudaInstallationDetector::isValid().
addClangTargetOptions()
void CudaToolChain::addClangTargetOptions (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, Action::OffloadKind DeviceOffloadKind) const override virtual
Add options that need to be passed to cc1 for this target.
Reimplemented from clang::driver::ToolChain.
Definition at line 725 of file Cuda.cpp.
References clang::driver::ToolChain::addClangTargetOptions(), clang::driver::tools::addOpenMPDeviceRTL(), clang::driver::tools::AddStaticDeviceLibsPostLinking(), clang::driver::toolchains::SYCLToolChain::AddSYCLIncludeArgs(), clang::CUDA_92, CudaInstallation, clang::CudaVersionToString(), clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), clang::driver::CudaInstallationDetector::getLibDeviceFile(), getLibSpirvTargetName(), clang::driver::tools::NVPTX::getNVPTXTargetFeatures(), clang::driver::ToolChain::getTriple(), HostTC, clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_OpenMP, clang::driver::Action::OFK_SYCL, string(), clang::UNKNOWN, and clang::driver::CudaInstallationDetector::version().
addClangWarningOptions()
void CudaToolChain::addClangWarningOptions (llvm::opt::ArgStringList & CC1Args) const override virtual
Add warning options that need to be passed to cc1 for this target.
Reimplemented from clang::driver::ToolChain.
Definition at line 969 of file Cuda.cpp.
References clang::driver::ToolChain::addClangWarningOptions(), and HostTC.
AddCudaIncludeArgs()
void CudaToolChain::AddCudaIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add arguments to use system-specific CUDA includes.
Reimplemented from clang::driver::ToolChain.
Definition at line 896 of file Cuda.cpp.
References clang::driver::CudaInstallationDetector::AddCudaIncludeArgs(), clang::driver::CudaInstallationDetector::CheckCudaVersionSupportsArch(), CudaInstallation, and clang::StringToCudaArch().
AddIAMCUIncludeArgs()
void CudaToolChain::AddIAMCUIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const override virtual
Add arguments to use MCU GCC toolchain includes.
Reimplemented from clang::driver::ToolChain.
Definition at line 997 of file Cuda.cpp.
References clang::driver::ToolChain::AddIAMCUIncludeArgs(), and HostTC.
adjustDebugInfoKind()
void CudaToolChain::adjustDebugInfoKind (codegenoptions::DebugInfoKind & DebugInfoKind, const llvm::opt::ArgList & Args) const override virtual
Adjust debug information kind considering all passed options.
Reimplemented from clang::driver::ToolChain.
Definition at line 881 of file Cuda.cpp.
References clang::codegenoptions::DebugDirectivesOnly, mustEmitDebugInfo(), and clang::codegenoptions::NoDebugInfo.
buildAssembler()
Tool * CudaToolChain::buildAssembler () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 946 of file Cuda.cpp.
buildLinker()
Tool * CudaToolChain::buildLinker () const override protected virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 950 of file Cuda.cpp.
References clang::driver::Action::OFK_OpenMP, and clang::driver::Action::OFK_SYCL.
computeMSVCVersion()
VersionTuple CudaToolChain::computeMSVCVersion (const Driver * D, const llvm::opt::ArgList & Args) const override virtual
On Windows, returns the MSVC compatibility version.
Reimplemented from clang::driver::ToolChain.
Definition at line 1015 of file Cuda.cpp.
References clang::driver::ToolChain::computeMSVCVersion(), and HostTC.
getAuxTriple()
const llvm::Triple* clang::driver::toolchains::CudaToolChain::getAuxTriple () const inline override virtual
Get the toolchain's aux triple, if it has one.
Exactly what the aux triple represents depends on the toolchain, but for example when compiling CUDA code for the GPU, the triple might be NVPTX, while the aux triple is the host (CPU) toolchain, e.g. x86-linux-gnu.
Reimplemented from clang::driver::ToolChain.
Definition at line 157 of file Cuda.h.
References clang::driver::ToolChain::getTriple().
GetCXXStdlibType()
ToolChain::CXXStdlibType CudaToolChain::GetCXXStdlibType (const llvm::opt::ArgList & Args) const override virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 974 of file Cuda.cpp.
References clang::driver::ToolChain::GetCXXStdlibType(), and HostTC.
getDefaultDenormalModeForType()
llvm::DenormalMode CudaToolChain::getDefaultDenormalModeForType (const llvm::opt::ArgList & DriverArgs, const JobAction & JA, const llvm::fltSemantics * FPType = nullptr) const override virtual
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
Otherwise, the default assumed mode for any floating point type.
Reimplemented from clang::driver::ToolChain.
Definition at line 855 of file Cuda.cpp.
References clang::driver::Action::getOffloadingDeviceKind(), clang::driver::Action::OFK_Cuda, and clang::driver::Action::OFK_Host.
GetDefaultDwarfVersion()
unsigned clang::driver::toolchains::CudaToolChain::GetDefaultDwarfVersion () const inline override virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 209 of file Cuda.h.
getInputFilename()
std::string CudaToolChain::getInputFilename (const InputInfo & Input) const override virtual
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
Reimplemented from clang::driver::ToolChain.
Definition at line 703 of file Cuda.cpp.
References Filename, clang::driver::ToolChain::getInputFilename(), clang::driver::InputInfo::getType(), clang::driver::Action::OFK_OpenMP, and string().
getMaxDwarfVersion()
unsigned clang::driver::toolchains::CudaToolChain::getMaxDwarfVersion () const inline override virtual
Reimplemented from clang::driver::ToolChain.
Definition at line 211 of file Cuda.h.
getSupportedSanitizers()
SanitizerMask CudaToolChain::getSupportedSanitizers () const override virtual
Return sanitizers which are available in this toolchain.
Reimplemented from clang::driver::ToolChain.
Definition at line 1002 of file Cuda.cpp.
References clang::driver::ToolChain::getSupportedSanitizers(), and HostTC.
isCrossCompiling()
bool clang::driver::toolchains::CudaToolChain::isCrossCompiling () const inline override virtual
Returns true if the toolchain is targeting a non-native architecture.
Reimplemented from clang::driver::ToolChain.
Definition at line 177 of file Cuda.h.
IsMathErrnoDefault()
bool clang::driver::toolchains::CudaToolChain::IsMathErrnoDefault () const inline override virtual
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
Reimplemented from clang::driver::ToolChain.
Definition at line 187 of file Cuda.h.
isPICDefault()
bool clang::driver::toolchains::CudaToolChain::isPICDefault () const inline override virtual
Test whether this toolchain defaults to PIC.
Implements clang::driver::ToolChain.
Definition at line 178 of file Cuda.h.
isPICDefaultForced()
bool clang::driver::toolchains::CudaToolChain::isPICDefaultForced () const inline override virtual
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
If this returns true, any PIC related flags should be ignored and instead the results of isPICDefault() and isPIEDefault(const llvm::opt::ArgList &Args) are used exclusively.
Implements clang::driver::ToolChain.
Definition at line 182 of file Cuda.h.
isPIEDefault()
bool clang::driver::toolchains::CudaToolChain::isPIEDefault (const llvm::opt::ArgList & Args) const inline override virtual
Test whether this toolchain defaults to PIE.
Implements clang::driver::ToolChain.
Definition at line 179 of file Cuda.h.
SelectTool()
Tool * CudaToolChain::SelectTool (const JobAction & JA) const override virtual
Choose a tool to use to handle the action JA.
This can be overridden when a particular ToolChain needs to use a compiler other than Clang.
Reimplemented from clang::driver::ToolChain.
Definition at line 958 of file Cuda.cpp.
References clang::driver::Action::getKind(), clang::driver::Action::getType(), clang::driver::Action::LinkJobClass, clang::driver::Action::OFK_SYCL, and clang::driver::ToolChain::SelectTool().
supportsDebugInfoOption()
bool CudaToolChain::supportsDebugInfoOption (const llvm::opt::Arg *) const override virtual
Does this toolchain supports given debug info option or not.
Reimplemented from clang::driver::ToolChain.
Definition at line 869 of file Cuda.cpp.
SupportsProfiling()
bool clang::driver::toolchains::CudaToolChain::SupportsProfiling () const inline override virtual
SupportsProfiling - Does this tool chain support -pg.
Reimplemented from clang::driver::ToolChain.
Definition at line 183 of file Cuda.h.
TranslateArgs()
llvm::opt::DerivedArgList * CudaToolChain::TranslateArgs (const llvm::opt::DerivedArgList & Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const override virtual
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
If DeviceOffloadKind is specified the translation specific for that offload kind is performed.
Parameters
BoundArch - The bound architecture name, or 0.
DeviceOffloadKind - The device offload kind used for the translation.
Reimplemented from clang::driver::ToolChain.
Definition at line 909 of file Cuda.cpp.
References clang::driver::ToolChain::getDriver(), clang::driver::Driver::getOpts(), HostTC, clang::driver::Action::OFK_OpenMP, and clang::driver::ToolChain::TranslateArgs().
useIntegratedAs()
bool clang::driver::toolchains::CudaToolChain::useIntegratedAs () const inline override virtual
Check if the toolchain should use the integrated assembler.
Reimplemented from clang::driver::ToolChain.
Definition at line 176 of file Cuda.h.
Member Data Documentation
CudaInstallation
CudaInstallationDetector clang::driver::toolchains::CudaToolChain::CudaInstallation
Definition at line 216 of file Cuda.h.
Referenced by AddClangSystemIncludeArgs(), addClangTargetOptions(), AddCudaIncludeArgs(), and CudaToolChain().
HostTC
const ToolChain& clang::driver::toolchains::CudaToolChain::HostTC
Definition at line 215 of file Cuda.h.
Referenced by AddClangCXXStdlibIncludeArgs(), AddClangSystemIncludeArgs(), addClangTargetOptions(), addClangWarningOptions(), AddIAMCUIncludeArgs(), computeMSVCVersion(), GetCXXStdlibType(), getSupportedSanitizers(), and TranslateArgs().
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Cuda.h
lib/Driver/ToolChains/Cuda.cpp