clang: clang::arcmt::FileRemapper Class Reference
clang::arcmt::FileRemapper Class Reference
#include "clang/ARCMigrate/FileRemapper.h"
Public Member Functions
FileRemapper ()
~FileRemapper ()
bool initFromDisk (StringRef outputDir, DiagnosticsEngine &Diag, bool ignoreIfFilesChanged)
bool initFromFile (StringRef filePath, DiagnosticsEngine &Diag, bool ignoreIfFilesChanged)
bool flushToDisk (StringRef outputDir, DiagnosticsEngine &Diag)
bool flushToFile (StringRef outputPath, DiagnosticsEngine &Diag)
bool overwriteOriginal (DiagnosticsEngine &Diag, StringRef outputDir=StringRef())
void remap (StringRef filePath, std::unique_ptr< llvm::MemoryBuffer > memBuf)
void applyMappings (PreprocessorOptions &PPOpts) const
void forEachMapping (llvm::function_ref< void(StringRef, StringRef)> CaptureFile, llvm::function_ref< void(StringRef, const llvm::MemoryBufferRef &)> CaptureBuffer) const
Iterate through all the mappings.
void clear (StringRef outputDir=StringRef())
Detailed Description
Definition at line 32 of file FileRemapper.h.
Constructor & Destructor Documentation
FileRemapper()
FileRemapper::FileRemapper ()
Definition at line 22 of file FileRemapper.cpp.
~FileRemapper()
FileRemapper::~FileRemapper ()
Definition at line 26 of file FileRemapper.cpp.
References clear().
Member Function Documentation
applyMappings()
void FileRemapper::applyMappings (PreprocessorOptions & PPOpts) const
Definition at line 209 of file FileRemapper.cpp.
References clang::PreprocessorOptions::addRemappedFile(), and clang::PreprocessorOptions::RetainRemappedFileBuffers.
Referenced by clang::arcmt::MigrationProcess::applyTransform().
clear()
void FileRemapper::clear (StringRef outputDir = StringRef())
Definition at line 30 of file FileRemapper.cpp.
References clang::transformer::remove(), and string().
Referenced by overwriteOriginal(), and ~FileRemapper().
flushToDisk()
bool FileRemapper::flushToDisk (StringRef outputDir, DiagnosticsEngine & Diag)
Definition at line 109 of file FileRemapper.cpp.
References Diag(), flushToFile(), and string().
Referenced by applyTransforms().
flushToFile()
bool FileRemapper::flushToFile (StringRef outputPath, DiagnosticsEngine & Diag)
Definition at line 119 of file FileRemapper.cpp.
References Diag(), clang::FileEntry::getModificationTime(), clang::FileEntry::getName(), remap(), and string().
Referenced by flushToDisk().
forEachMapping()
void FileRemapper::forEachMapping (llvm::function_ref< void(StringRef, StringRef)> CaptureFile, llvm::function_ref< void(StringRef, const llvm::MemoryBufferRef &)> CaptureBuffer) const
Iterate through all the mappings.
Definition at line 194 of file FileRemapper.cpp.
Referenced by clang::arcmt::getFileRemappings().
initFromDisk()
bool FileRemapper::initFromDisk (StringRef outputDir, DiagnosticsEngine & Diag, bool ignoreIfFilesChanged)
Definition at line 49 of file FileRemapper.cpp.
References Diag(), initFromFile(), and string().
Referenced by clang::arcmt::ObjCMigrateAction::BeginInvocation(), clang::arcmt::getFileRemappings(), and clang::arcmt::MigrationProcess::MigrationProcess().
initFromFile()
bool FileRemapper::initFromFile (StringRef filePath, DiagnosticsEngine & Diag, bool ignoreIfFilesChanged)
Definition at line 55 of file FileRemapper.cpp.
References Diag(), remap(), and string().
Referenced by initFromDisk().
overwriteOriginal()
bool FileRemapper::overwriteOriginal (DiagnosticsEngine & Diag, StringRef outputDir = StringRef())
Definition at line 168 of file FileRemapper.cpp.
References clear(), Diag(), and clang::FileEntry::getName().
Referenced by applyTransforms().
remap()
void FileRemapper::remap (StringRef filePath, std::unique_ptr< llvm::MemoryBuffer > memBuf)
Definition at line 223 of file FileRemapper.cpp.
Referenced by clang::arcmt::MigrationProcess::applyTransform(), flushToFile(), and initFromFile().
The documentation for this class was generated from the following files:
include/clang/ARCMigrate/FileRemapper.h
lib/ARCMigrate/FileRemapper.cpp