clang: clang::comments::HTMLStartTagComment::Attribute Class Reference
clang::comments::HTMLStartTagComment::Attribute Class Reference
#include "clang/AST/Comment.h"
Public Member Functions
Attribute ()
Attribute (SourceLocation NameLocBegin, StringRef Name)
Attribute (SourceLocation NameLocBegin, StringRef Name, SourceLocation EqualsLoc, SourceRange ValueRange, StringRef Value)
SourceLocation getNameLocEnd () const
SourceRange getNameRange () const
Public Attributes
SourceLocation NameLocBegin
StringRef Name
SourceLocation EqualsLoc
SourceRange ValueRange
StringRef Value
Detailed Description
Definition at line 435 of file Comment.h.
Constructor & Destructor Documentation
Attribute() [1/3]
clang::comments::HTMLStartTagComment::Attribute::Attribute () inline
Definition at line 445 of file Comment.h.
Attribute() [2/3]
clang::comments::HTMLStartTagComment::Attribute::Attribute (SourceLocation NameLocBegin, StringRef Name) inline
Definition at line 447 of file Comment.h.
Attribute() [3/3]
clang::comments::HTMLStartTagComment::Attribute::Attribute (SourceLocation NameLocBegin, StringRef Name, SourceLocation EqualsLoc, SourceRange ValueRange, StringRef Value) inline
Definition at line 450 of file Comment.h.
Member Function Documentation
getNameLocEnd()
SourceLocation clang::comments::HTMLStartTagComment::Attribute::getNameLocEnd () const inline
Definition at line 455 of file Comment.h.
References clang::SourceLocation::getLocWithOffset(), Name, and NameLocBegin.
Referenced by getNameRange().
getNameRange()
SourceRange clang::comments::HTMLStartTagComment::Attribute::getNameRange () const inline
Definition at line 459 of file Comment.h.
References getNameLocEnd(), and NameLocBegin.
Member Data Documentation
EqualsLoc
SourceLocation clang::comments::HTMLStartTagComment::Attribute::EqualsLoc
Definition at line 440 of file Comment.h.
Name
StringRef clang::comments::HTMLStartTagComment::Attribute::Name
Definition at line 438 of file Comment.h.
Referenced by getNameLocEnd().
NameLocBegin
SourceLocation clang::comments::HTMLStartTagComment::Attribute::NameLocBegin
Definition at line 437 of file Comment.h.
Referenced by getNameLocEnd(), and getNameRange().
Value
StringRef clang::comments::HTMLStartTagComment::Attribute::Value
Definition at line 443 of file Comment.h.
ValueRange
SourceRange clang::comments::HTMLStartTagComment::Attribute::ValueRange
Definition at line 442 of file Comment.h.
The documentation for this class was generated from the following file:
include/clang/AST/Comment.h