clang: clang::ExprMutationAnalyzer Class Reference
clang::ExprMutationAnalyzer Class Reference
Analyzes whether any mutative operations are applied to an expression within a given statement.
#include "clang/Analysis/Analyses/ExprMutationAnalyzer.h"
Classes
struct Analyzer
struct Memoized
Public Member Functions
ExprMutationAnalyzer (const Stmt &Stm, ASTContext &Context)
bool isMutated (const Expr *Exp)
bool isMutated (const Decl *Dec)
const Stmt * findMutation (const Expr *Exp)
const Stmt * findMutation (const Decl *Dec)
bool isPointeeMutated (const Expr *Exp)
bool isPointeeMutated (const Decl *Dec)
const Stmt * findPointeeMutation (const Expr *Exp)
const Stmt * findPointeeMutation (const Decl *Dec)
Static Public Member Functions
static bool isUnevaluated (const Stmt *Smt, const Stmt &Stm, ASTContext &Context)
Friends
class FunctionParmMutationAnalyzer
Detailed Description
Analyzes whether any mutative operations are applied to an expression within a given statement.
Definition at line 21 of file ExprMutationAnalyzer.h.
Constructor & Destructor Documentation
ExprMutationAnalyzer()
clang::ExprMutationAnalyzer::ExprMutationAnalyzer (const Stmt & Stm, ASTContext & Context) inline
Definition at line 83 of file ExprMutationAnalyzer.h.
Member Function Documentation
findMutation() [1/2]
const Stmt* clang::ExprMutationAnalyzer::findMutation (const Decl * Dec) inline
Definition at line 89 of file ExprMutationAnalyzer.h.
References clang::ExprMutationAnalyzer::Analyzer::findMutation().
findMutation() [2/2]
const Stmt* clang::ExprMutationAnalyzer::findMutation (const Expr * Exp) inline
Definition at line 88 of file ExprMutationAnalyzer.h.
References clang::ExprMutationAnalyzer::Analyzer::findMutation().
Referenced by isMutated().
findPointeeMutation() [1/2]
const Stmt* clang::ExprMutationAnalyzer::findPointeeMutation (const Decl * Dec) inline
Definition at line 100 of file ExprMutationAnalyzer.h.
References clang::ExprMutationAnalyzer::Analyzer::findPointeeMutation().
findPointeeMutation() [2/2]
const Stmt* clang::ExprMutationAnalyzer::findPointeeMutation (const Expr * Exp) inline
Definition at line 97 of file ExprMutationAnalyzer.h.
References clang::ExprMutationAnalyzer::Analyzer::findPointeeMutation().
Referenced by isPointeeMutated().
isMutated() [1/2]
bool clang::ExprMutationAnalyzer::isMutated (const Decl * Dec) inline
Definition at line 87 of file ExprMutationAnalyzer.h.
References findMutation().
isMutated() [2/2]
bool clang::ExprMutationAnalyzer::isMutated (const Expr * Exp) inline
Definition at line 86 of file ExprMutationAnalyzer.h.
References findMutation().
isPointeeMutated() [1/2]
bool clang::ExprMutationAnalyzer::isPointeeMutated (const Decl * Dec) inline
Definition at line 94 of file ExprMutationAnalyzer.h.
References findPointeeMutation().
isPointeeMutated() [2/2]
bool clang::ExprMutationAnalyzer::isPointeeMutated (const Expr * Exp) inline
Definition at line 91 of file ExprMutationAnalyzer.h.
References findPointeeMutation().
isUnevaluated()
static bool clang::ExprMutationAnalyzer::isUnevaluated (const Stmt * Smt, const Stmt & Stm, ASTContext & Context) inline static
Definition at line 104 of file ExprMutationAnalyzer.h.
Friends And Related Function Documentation
FunctionParmMutationAnalyzer
friend class FunctionParmMutationAnalyzer friend
Definition at line 22 of file ExprMutationAnalyzer.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ExprMutationAnalyzer.h