clang: clang::CodeGen::CodeGenFunction Class Reference
clang::CodeGen::CodeGenFunction Class Reference
CodeGenFunction - This class organizes the per-function state that is used while generating LLVM code.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Classes
class AbstractCallee
An abstract representation of regular/ObjC call/message targets.
class ArrayInitLoopExprScope
The scope of an ArrayInitLoopExpr.
class AutoVarEmission
struct AwaitSuspendWrapperInfo
class CallLifetimeEnd
class CGCapturedStmtInfo
API for captured statement code generation.
class CGCapturedStmtRAII
RAII for correct setting/restoring of CapturedStmtInfo.
struct CGCoroInfo
class CGFPOptionsRAII
class ConditionalEvaluation
An object to manage conditionally-evaluated expressions.
class ConstantEmission
class CurrentBuiltinIDRAII
Class to manage the BuiltinID for the current builtin expression during processing in EmitBuiltinExpr.
struct CXXDefaultArgExprScope
class CXXDefaultInitExprScope
The scope of a CXXDefaultInitExpr.
class FieldConstructionScope
A scope within which we are constructing the fields of an object which might use a CXXDefaultInitExpr.
class FinallyInfo
A class controlling the emission of a finally block.
class InlinedInheritingConstructorScope
struct JumpDest
A jump destination is an abstract label, branching to which may require a jump out through normal cleanups.
class LexicalScope
struct LifetimeExtendedCleanupHeader
Header for data within LifetimeExtendedCleanupStack.
struct MultiVersionResolverOption
struct OMPBuilderCBHelpers
class OMPCancelStackRAII
Controls insertion of cancellation exit blocks in worksharing constructs.
class OMPLocalDeclMapRAII
Save/restore original map of previously emitted local vars in case when we need to duplicate emission of the same code several times in the same function for OpenMP code.
class OMPMapVars
The class used to assign some variables some temporarily addresses.
class OMPPrivateScope
The scope used to remap some variables as private in the OpenMP loop body (or other captured region emitted without outlining), and to restore old vars back on exit.
struct OMPTargetDataInfo
class OpaqueValueMapping
An RAII object to set (and then clear) a mapping for an OpaqueValueExpr.
class OpaqueValueMappingData
A non-RAII class containing all the information about a bound opaque value.
class ParamValue
class ParentLoopDirectiveForScanRegion
Manages parent directive for scan directives.
class PeepholeProtection
An object which temporarily prevents a value from being destroyed by aggressive peephole optimizations that assume that all uses of a value have been realized in the IR.
struct PrototypeWrapper
class RunCleanupsScope
Enters a new scope for capturing cleanups, all of which will be executed once the scope is exited.
class SanitizerScope
RAII object to set/unset CodeGenFunction::IsSanitizerScope.
class StmtExprEvaluation
An RAII object to record that we're evaluating a statement expression.
struct VlaSizePair
struct VPtr
Struct with all information about dynamic [sub]class needed to set vptr.
Public Types
enum CFITypeCheckKind {
CFITCK_VCall , CFITCK_NVCall , CFITCK_DerivedCast , CFITCK_UnrelatedCast ,
CFITCK_ICall , CFITCK_NVMFCall , CFITCK_VMFCall
}
enum TypeCheckKind {
TCK_Load , TCK_Store , TCK_ReferenceBinding , TCK_MemberAccess ,
TCK_MemberCall , TCK_ConstructorCall , TCK_DowncastPointer , TCK_DowncastReference ,
TCK_Upcast , TCK_UpcastToVirtualBase , TCK_NonnullAssign , TCK_DynamicOperation
}
Situations in which we might emit a check for the suitability of a pointer or glvalue.
enum class GuardKind { VariableGuard , TlsGuard }
enum { NotSubtraction = false , IsSubtraction = true }
An enumeration which makes it easier to specify whether or not an operation is a subtraction.
enum BuiltinCheckKind { BCK_CTZPassedZero , BCK_CLZPassedZero }
Specifies which type of sanitizer check to apply when handling a particular builtin.
enum class EvaluationOrder { Default , ForceLeftToRight , ForceRightToLeft }
typedef std::pair< llvm::Value *, llvm::Value * > ComplexPairTy
typedef llvm::function_ref< void(CodeGenFunction &, const OMPLoopDirective &, JumpDest)> CodeGenLoopTy
typedef llvm::function_ref< void(CodeGenFunction &, SourceLocation, const unsigned, const bool)> CodeGenOrderedTy
typedef llvm::function_ref< std::pair< LValue, LValue > CodeGenFunction &, const OMPExecutableDirective &S)> CodeGenLoopBoundsTy
typedef llvm::function_ref< std::pair< llvm::Value *, llvm::Value * > CodeGenFunction &, const OMPExecutableDirective &S, Address LB, Address UB)> CodeGenDispatchBoundsTy
typedef llvm::DenseMap< const Decl *, Address > DeclMapTy
using SourceLocExprScopeGuard = CurrentSourceLocExprScope::SourceLocExprScopeGuard
typedef void Destroyer(CodeGenFunction &CGF, Address addr, QualType ty)
typedef llvm::SmallVector< VPtr, 4 > VPtrsVector
typedef llvm::SmallPtrSet< const CXXRecordDecl *, 4 > VisitedVirtualBasesSetTy
typedef void SpecialInitFn(CodeGenFunction &Init, const VarDecl &D, llvm::Value *Address)
typedef const llvm::function_ref< void(CodeGenFunction &, llvm::Function *, const OMPTaskDataTy &)> TaskGenTy
Public Member Functions
void InsertHelper (llvm::Instruction *I, const llvm::Twine &Name, llvm::BasicBlock *BB, llvm::BasicBlock::iterator InsertPt) const
CGBuilder insert helper.
bool isCoroutine () const
bool inSuspendBlock () const
llvm::Function * generateAwaitSuspendWrapper (Twine const &CoroName, Twine const &SuspendPointName, CoroutineSuspendExpr const &S)
bool hasLabelBeenSeenInCurrentScope () const
Return true if a label was seen in the current scope.
llvm::Instruction * getPostAllocaInsertPoint ()
Return PostAllocaInsertPt.
bool checkIfFunctionMustProgress ()
Returns true if a function must make progress, which means the mustprogress attribute can be added.
bool checkIfLoopMustProgress (bool HasConstantCond)
Returns true if a loop must make progress, which means the mustprogress attribute can be added.
llvm::BasicBlock * EmitLandingPad ()
Emits a landing pad for the current EH stack.
llvm::BasicBlock * getInvokeDestImpl ()
template<class T >
DominatingValue< T >::saved_type saveValueInCond (T value)
bool isSEHTryScope () const
Returns true inside SEH __try blocks.
bool isCleanupPadScope () const
Returns true while emitting a cleanuppad.
template<class T , class... As>
void pushFullExprCleanup (CleanupKind kind, As... A)
pushFullExprCleanup - Push a cleanup to be run at the end of the current full-expression.
template<class T , class... As>
void pushCleanupAfterFullExpr (CleanupKind Kind, As... A)
Queue a cleanup to be pushed after finishing the current full-expression, potentially with an active flag.
template<class T , class... As>
void pushCleanupAfterFullExprWithActiveFlag (CleanupKind Kind, RawAddress ActiveFlag, As... A)
void initFullExprCleanup ()
Set up the last cleanup that was pushed as a conditional full-expression cleanup.
void initFullExprCleanupWithFlag (RawAddress ActiveFlag)
RawAddress createCleanupActiveFlag ()
void PushDestructorCleanup (QualType T, Address Addr)
PushDestructorCleanup - Push a cleanup to call the complete-object destructor of an object of the given type at the given address.
void PushDestructorCleanup (const CXXDestructorDecl *Dtor, QualType T, Address Addr)
PushDestructorCleanup - Push a cleanup to call the complete-object variant of the given destructor on the object at the given address.
void PopCleanupBlock (bool FallThroughIsBranchThrough=false)
PopCleanupBlock - Will pop the cleanup entry on the stack and process all branch fixups.
void DeactivateCleanupBlock (EHScopeStack::stable_iterator Cleanup, llvm::Instruction *DominatingIP)
DeactivateCleanupBlock - Deactivates the given cleanup block.
void ActivateCleanupBlock (EHScopeStack::stable_iterator Cleanup, llvm::Instruction *DominatingIP)
ActivateCleanupBlock - Activates an initially-inactive cleanup.
void PopCleanupBlocks (EHScopeStack::stable_iterator OldCleanupStackSize, std::initializer_list< llvm::Value ** > ValuesToReload={})
Takes the old cleanup stack size and emits the cleanup blocks that have been added.
void PopCleanupBlocks (EHScopeStack::stable_iterator OldCleanupStackSize, size_t OldLifetimeExtendedStackSize, std::initializer_list< llvm::Value ** > ValuesToReload={})
Takes the old cleanup stack size and emits the cleanup blocks that have been added, then adds all lifetime-extended cleanups from the given position to the stack.
void ResolveBranchFixups (llvm::BasicBlock *Target)
JumpDest getJumpDestInCurrentScope (llvm::BasicBlock *Target)
The given basic block lies in the current EH scope, but may be a target of a potentially scope-crossing jump; get a stable handle to which we can perform this jump later.
JumpDest getJumpDestInCurrentScope (StringRef Name=StringRef())
The given basic block lies in the current EH scope, but may be a target of a potentially scope-crossing jump; get a stable handle to which we can perform this jump later.
void EmitBranchThroughCleanup (JumpDest Dest)
EmitBranchThroughCleanup - Emit a branch from the current insert block through the normal cleanup handling code (if any) and then on to.
bool isObviouslyBranchWithoutCleanups (JumpDest Dest) const
isObviouslyBranchWithoutCleanups - Return true if a branch to the specified destination obviously has no cleanups to run.
void popCatchScope ()
popCatchScope - Pops the catch scope at the top of the EHScope stack, emitting any required code (other than the catch handlers themselves).
llvm::BasicBlock * getEHResumeBlock (bool isCleanup)
llvm::BasicBlock * getEHDispatchBlock (EHScopeStack::stable_iterator scope)
llvm::BasicBlock * getFuncletEHDispatchBlock (EHScopeStack::stable_iterator scope)
bool isInConditionalBranch () const
isInConditionalBranch - Return true if we're currently emitting one branch or the other of a conditional expression.
void setBeforeOutermostConditional (llvm::Value *value, Address addr, CodeGenFunction &CGF)
void incrementProfileCounter (const Stmt *S, llvm::Value *StepV=nullptr)
Increment the profiler's counter for the given statement by StepV.
bool isMCDCCoverageEnabled () const
void maybeCreateMCDCCondBitmap ()
Allocate a temp value on the stack that MCDC can use to track condition results.
bool isBinaryLogicalOp (const Expr *E) const
void maybeResetMCDCCondBitmap (const Expr *E)
Zero-init the MCDC temp value.
void maybeUpdateMCDCTestVectorBitmap (const Expr *E)
Increment the profiler's counter for the given expression by StepV.
void maybeUpdateMCDCCondBitmap (const Expr *E, llvm::Value *Val)
Update the MCDC temp value with the condition's evaluated result.
uint64_t getProfileCount (const Stmt *S)
Get the profiler's count for the given statement.
void setCurrentProfileCount (uint64_t Count)
Set the profiler's current count.
uint64_t getCurrentProfileCount ()
Get the profiler's current count.
unsigned getCurrentBuiltinID () const
CodeGenFunction (CodeGenModule &cgm, bool suppressNewContext=false)
~CodeGenFunction ()
CodeGenTypes & getTypes () const
ASTContext & getContext () const
CGDebugInfo * getDebugInfo ()
void disableDebugInfo ()
void enableDebugInfo ()
bool shouldUseFusedARCCalls ()
const LangOptions & getLangOpts () const
Address getExceptionSlot ()
Returns a pointer to the function's exception object and selector slot, which is assigned in every landing pad.
Address getEHSelectorSlot ()
llvm::Value * getExceptionFromSlot ()
Returns the contents of the function's exception object and selector slots.
llvm::Value * getSelectorFromSlot ()
RawAddress getNormalCleanupDestSlot ()
llvm::BasicBlock * getUnreachableBlock ()
llvm::BasicBlock * getInvokeDest ()
bool currentFunctionUsesSEHTry () const
const TargetInfo & getTarget () const
llvm::LLVMContext & getLLVMContext ()
const TargetCodeGenInfo & getTargetHooks () const
void pushIrregularPartialArrayCleanup (llvm::Value *arrayBegin, Address arrayEndPointer, QualType elementType, CharUnits elementAlignment, Destroyer *destroyer)
pushIrregularPartialArrayCleanup - Push an EH cleanup to destroy already-constructed elements of the given array.
void pushRegularPartialArrayCleanup (llvm::Value *arrayBegin, llvm::Value *arrayEnd, QualType elementType, CharUnits elementAlignment, Destroyer *destroyer)
pushRegularPartialArrayCleanup - Push an EH cleanup to destroy already-constructed elements of the given array.
void pushDestroy (QualType::DestructionKind dtorKind, Address addr, QualType type)
pushDestroy - Push the standard destructor for the given type as at least a normal cleanup.
void pushEHDestroy (QualType::DestructionKind dtorKind, Address addr, QualType type)
pushEHDestroy - Push the standard destructor for the given type as an EH-only cleanup.
void pushDestroy (CleanupKind kind, Address addr, QualType type, Destroyer *destroyer, bool useEHCleanupForArray)
void pushLifetimeExtendedDestroy (CleanupKind kind, Address addr, QualType type, Destroyer *destroyer, bool useEHCleanupForArray)
void pushCallObjectDeleteCleanup (const FunctionDecl *OperatorDelete, llvm::Value *CompletePtr, QualType ElementType)
void pushStackRestore (CleanupKind kind, Address SPMem)
void pushKmpcAllocFree (CleanupKind Kind, std::pair< llvm::Value *, llvm::Value * > AddrSizePair)
void emitDestroy (Address addr, QualType type, Destroyer *destroyer, bool useEHCleanupForArray)
emitDestroy - Immediately perform the destruction of the given object.
llvm::Function * generateDestroyHelper (Address addr, QualType type, Destroyer *destroyer, bool useEHCleanupForArray, const VarDecl *VD)
generateDestroyHelper - Generates a helper function which, when invoked, destroys the given object.
void emitArrayDestroy (llvm::Value *begin, llvm::Value *end, QualType elementType, CharUnits elementAlign, Destroyer *destroyer, bool checkZeroLength, bool useEHCleanup)
emitArrayDestroy - Destroys all the elements of the given array, beginning from last to first.
Destroyer * getDestroyer (QualType::DestructionKind destructionKind)
bool needsEHCleanup (QualType::DestructionKind kind)
Determines whether an EH cleanup is required to destroy a type with the given destruction kind.
CleanupKind getCleanupKind (QualType::DestructionKind kind)
void GenerateObjCMethod (const ObjCMethodDecl *OMD)
Generate an Objective-C method.
void StartObjCMethod (const ObjCMethodDecl *MD, const ObjCContainerDecl *CD)
StartObjCMethod - Begin emission of an ObjCMethod.
void GenerateObjCGetter (ObjCImplementationDecl *IMP, const ObjCPropertyImplDecl *PID)
GenerateObjCGetter - Synthesize an Objective-C property getter function.
void generateObjCGetterBody (const ObjCImplementationDecl *classImpl, const ObjCPropertyImplDecl *propImpl, const ObjCMethodDecl *GetterMothodDecl, llvm::Constant *AtomicHelperFn)
void GenerateObjCCtorDtorMethod (ObjCImplementationDecl *IMP, ObjCMethodDecl *MD, bool ctor)
void GenerateObjCSetter (ObjCImplementationDecl *IMP, const ObjCPropertyImplDecl *PID)
GenerateObjCSetter - Synthesize an Objective-C property setter function for the given property.
void generateObjCSetterBody (const ObjCImplementationDecl *classImpl, const ObjCPropertyImplDecl *propImpl, llvm::Constant *AtomicHelperFn)
llvm::Value * EmitBlockLiteral (const BlockExpr *)
Emit block literal.
llvm::Function * GenerateBlockFunction (GlobalDecl GD, const CGBlockInfo &Info, const DeclMapTy &ldm, bool IsLambdaConversionToBlock, bool BuildGlobalBlock)
llvm::Constant * GenerateCopyHelperFunction (const CGBlockInfo &blockInfo)
Generate the copy-helper function for a block closure object: static void block_copy_helper(block_t *dst, block_t *src); The runtime will have previously initialized 'dst' by doing a bit-copy of 'src'.
llvm::Constant * GenerateDestroyHelperFunction (const CGBlockInfo &blockInfo)
Generate the destroy-helper function for a block closure object: static void block_destroy_helper(block_t *theBlock);.
llvm::Constant * GenerateObjCAtomicSetterCopyHelperFunction (const ObjCPropertyImplDecl *PID)
GenerateObjCAtomicSetterCopyHelperFunction - Given a c++ object type with non-trivial copy assignment function, produce following helper function.
llvm::Constant * GenerateObjCAtomicGetterCopyHelperFunction (const ObjCPropertyImplDecl *PID)
llvm::Value * EmitBlockCopyAndAutorelease (llvm::Value *Block, QualType Ty)
void BuildBlockRelease (llvm::Value *DeclPtr, BlockFieldFlags flags, bool CanThrow)
void emitByrefStructureInit (const AutoVarEmission &emission)
Initialize the structural components of a __block variable, i.e.
void enterByrefCleanup (CleanupKind Kind, Address Addr, BlockFieldFlags Flags, bool LoadBlockVarAddr, bool CanThrow)
Enter a cleanup to destroy a __block variable.
void setBlockContextParameter (const ImplicitParamDecl *D, unsigned argNum, llvm::Value *ptr)
Address LoadBlockStruct ()
Address GetAddrOfBlockDecl (const VarDecl *var)
Address emitBlockByrefAddress (Address baseAddr, const VarDecl *V, bool followForward=true)
BuildBlockByrefAddress - Computes the location of the data in a variable which is declared as __block.
Address emitBlockByrefAddress (Address baseAddr, const BlockByrefInfo &info, bool followForward, const llvm::Twine &name)
const BlockByrefInfo & getBlockByrefInfo (const VarDecl *var)
BuildByrefInfo - This routine changes a __block variable declared as T x into:
QualType BuildFunctionArgList (GlobalDecl GD, FunctionArgList &Args)
void GenerateCode (GlobalDecl GD, llvm::Function *Fn, const CGFunctionInfo &FnInfo)
void markAsIgnoreThreadCheckingAtRuntime (llvm::Function *Fn)
Annotate the function with an attribute that disables TSan checking at runtime.
void StartFunction (GlobalDecl GD, QualType RetTy, llvm::Function *Fn, const CGFunctionInfo &FnInfo, const FunctionArgList &Args, SourceLocation Loc=SourceLocation(), SourceLocation StartLoc=SourceLocation())
Emit code for the start of a function.
void EmitConstructorBody (FunctionArgList &Args)
EmitConstructorBody - Emits the body of the current constructor.
void EmitDestructorBody (FunctionArgList &Args)
EmitDestructorBody - Emits the body of the current destructor.
void emitImplicitAssignmentOperatorBody (FunctionArgList &Args)
void EmitFunctionBody (const Stmt *Body)
void EmitBlockWithFallThrough (llvm::BasicBlock *BB, const Stmt *S)
When instrumenting to collect profile data, the counts for some blocks such as switch cases need to not include the fall-through counts, so emit a branch around the instrumentation code.
void EmitForwardingCallToLambda (const CXXMethodDecl *LambdaCallOperator, CallArgList &CallArgs, const CGFunctionInfo *CallOpFnInfo=nullptr, llvm::Constant *CallOpFn=nullptr)
void EmitLambdaBlockInvokeBody ()
void EmitLambdaStaticInvokeBody (const CXXMethodDecl *MD)
void EmitLambdaDelegatingInvokeBody (const CXXMethodDecl *MD, CallArgList &CallArgs)
void EmitLambdaInAllocaImplFn (const CXXMethodDecl *CallOp, const CGFunctionInfo **ImplFnInfo, llvm::Function **ImplFn)
void EmitLambdaInAllocaCallOpBody (const CXXMethodDecl *MD)
void EmitLambdaVLACapture (const VariableArrayType *VAT, LValue LV)
void EmitAsanPrologueOrEpilogue (bool Prologue)
llvm::DebugLoc EmitReturnBlock ()
Emit the unified return block, trying to avoid its emission when possible.
void FinishFunction (SourceLocation EndLoc=SourceLocation())
FinishFunction - Complete IR generation of the current function.
void StartThunk (llvm::Function *Fn, GlobalDecl GD, const CGFunctionInfo &FnInfo, bool IsUnprototyped)
void EmitCallAndReturnForThunk (llvm::FunctionCallee Callee, const ThunkInfo *Thunk, bool IsUnprototyped)
void FinishThunk ()
void EmitMustTailThunk (GlobalDecl GD, llvm::Value *AdjustedThisPtr, llvm::FunctionCallee Callee)
Emit a musttail call for a thunk with a potentially adjusted this pointer.
void generateThunk (llvm::Function *Fn, const CGFunctionInfo &FnInfo, GlobalDecl GD, const ThunkInfo &Thunk, bool IsUnprototyped)
Generate a thunk for the given method.
llvm::Function * GenerateVarArgsThunk (llvm::Function *Fn, const CGFunctionInfo &FnInfo, GlobalDecl GD, const ThunkInfo &Thunk)
void EmitCtorPrologue (const CXXConstructorDecl *CD, CXXCtorType Type, FunctionArgList &Args)
EmitCtorPrologue - This routine generates necessary code to initialize base classes and non-static data members belonging to this constructor.
void EmitInitializerForField (FieldDecl *Field, LValue LHS, Expr *Init)
void InitializeVTablePointer (const VPtr &vptr)
Initialize the vtable pointer of the given subobject.
VPtrsVector getVTablePointers (const CXXRecordDecl *VTableClass)
void getVTablePointers (BaseSubobject Base, const CXXRecordDecl *NearestVBase, CharUnits OffsetFromNearestVBase, bool BaseIsNonVirtualPrimaryBase, const CXXRecordDecl *VTableClass, VisitedVirtualBasesSetTy &VBases, VPtrsVector &vptrs)
void InitializeVTablePointers (const CXXRecordDecl *ClassDecl)
llvm::Value * GetVTablePtr (Address This, llvm::Type *VTableTy, const CXXRecordDecl *VTableClass)
GetVTablePtr - Return the Value of the vtable pointer member pointed to by This.
void EmitVTablePtrCheckForCast (QualType T, Address Derived, bool MayBeNull, CFITypeCheckKind TCK, SourceLocation Loc)
Derived is the presumed address of an object of type T after a cast.
void EmitVTablePtrCheckForCall (const CXXRecordDecl *RD, llvm::Value *VTable, CFITypeCheckKind TCK, SourceLocation Loc)
EmitVTablePtrCheckForCall - Virtual method MD is being called via VTable.
void EmitVTablePtrCheck (const CXXRecordDecl *RD, llvm::Value *VTable, CFITypeCheckKind TCK, SourceLocation Loc)
EmitVTablePtrCheck - Emit a check that VTable is a valid virtual table for RD using llvm.type.test.
void EmitTypeMetadataCodeForVCall (const CXXRecordDecl *RD, llvm::Value *VTable, SourceLocation Loc)
If whole-program virtual table optimization is enabled, emit an assumption that VTable is a member of RD's type identifier.
bool ShouldEmitVTableTypeCheckedLoad (const CXXRecordDecl *RD)
Returns whether we should perform a type checked load when loading a virtual function for virtual calls to members of RD.
llvm::Value * EmitVTableTypeCheckedLoad (const CXXRecordDecl *RD, llvm::Value *VTable, llvm::Type *VTableTy, uint64_t VTableByteOffset)
Emit a type checked load from the given vtable.
void EnterDtorCleanups (const CXXDestructorDecl *Dtor, CXXDtorType Type)
EnterDtorCleanups - Enter the cleanups necessary to complete the given phase of destruction for a destructor.
bool ShouldInstrumentFunction ()
ShouldInstrumentFunction - Return true if the current function should be instrumented with __cyg_profile_func_* calls.
bool ShouldSkipSanitizerInstrumentation ()
ShouldSkipSanitizerInstrumentation - Return true if the current function should not be instrumented with sanitizers.
bool ShouldXRayInstrumentFunction () const
ShouldXRayInstrument - Return true if the current function should be instrumented with XRay nop sleds.
bool AlwaysEmitXRayCustomEvents () const
AlwaysEmitXRayCustomEvents - Return true if we must unconditionally emit XRay custom event handling calls.
bool AlwaysEmitXRayTypedEvents () const
AlwaysEmitXRayTypedEvents - Return true if clang must unconditionally emit XRay typed event handling calls.
llvm::ConstantInt * getUBSanFunctionTypeHash (QualType T) const
Return a type hash constant for a function instrumented by -fsanitize=function.
void EmitFunctionProlog (const CGFunctionInfo &FI, llvm::Function *Fn, const FunctionArgList &Args)
EmitFunctionProlog - Emit the target specific LLVM code to load the arguments for the given function.
void EmitFunctionEpilog (const CGFunctionInfo &FI, bool EmitRetDbgLoc, SourceLocation EndLoc)
EmitFunctionEpilog - Emit the target specific LLVM code to return the given temporary.
void EmitReturnValueCheck (llvm::Value *RV)
Emit a test that checks if the return value RV is nonnull.
void EmitStartEHSpec (const Decl *D)
EmitStartEHSpec - Emit the start of the exception spec.
void EmitEndEHSpec (const Decl *D)
EmitEndEHSpec - Emit the end of the exception spec.
llvm::BasicBlock * getTerminateLandingPad ()
getTerminateLandingPad - Return a landing pad that just calls terminate.
llvm::BasicBlock * getTerminateFunclet ()
getTerminateLandingPad - Return a cleanup funclet that just calls terminate.
llvm::BasicBlock * getTerminateHandler ()
getTerminateHandler - Return a handler (not a landing pad, just a catch handler) that just calls terminate.
llvm::Type * ConvertTypeForMem (QualType T)
llvm::Type * ConvertType (QualType T)
llvm::Type * ConvertType (const TypeDecl *T)
llvm::Value * LoadObjCSelf ()
LoadObjCSelf - Load the value of self.
QualType TypeOfSelfObject ()
TypeOfSelfObject - Return type of object that this self represents.
llvm::BasicBlock * createBasicBlock (const Twine &name="", llvm::Function *parent=nullptr, llvm::BasicBlock *before=nullptr)
createBasicBlock - Create an LLVM basic block.
JumpDest getJumpDestForLabel (const LabelDecl *S)
getBasicBlockForLabel - Return the LLVM basicblock that the specified label maps to.
void SimplifyForwardingBlocks (llvm::BasicBlock *BB)
SimplifyForwardingBlocks - If the given basic block is only a branch to another basic block, simplify it.
void EmitBlock (llvm::BasicBlock *BB, bool IsFinished=false)
EmitBlock - Emit the given block.
void EmitBlockAfterUses (llvm::BasicBlock *BB)
EmitBlockAfterUses - Emit the given block somewhere hopefully near its uses, and leave the insertion point in it.
void EmitBranch (llvm::BasicBlock *Block)
EmitBranch - Emit a branch to the specified basic block from the current insert block, taking care to avoid creation of branches from dummy blocks.
bool HaveInsertPoint () const
HaveInsertPoint - True if an insertion point is defined.
void EnsureInsertPoint ()
EnsureInsertPoint - Ensure that an insertion point is defined so that emitted IR has a place to go.
void ErrorUnsupported (const Stmt *S, const char *Type)
ErrorUnsupported - Print out an error that codegen doesn't support the specified stmt yet.
Address mergeAddressesInConditionalExpr (Address LHS, Address RHS, llvm::BasicBlock *LHSBlock, llvm::BasicBlock *RHSBlock, llvm::BasicBlock *MergeBlock, QualType MergedType)
Address makeNaturalAddressForPointer (llvm::Value *Ptr, QualType T, CharUnits Alignment=CharUnits::Zero(), bool ForPointeeType=false, LValueBaseInfo *BaseInfo=nullptr, TBAAAccessInfo *TBAAInfo=nullptr, KnownNonNull_t IsKnownNonNull=NotKnownNonNull)
Construct an address with the natural alignment of T.
LValue MakeAddrLValue (Address Addr, QualType T, AlignmentSource Source=AlignmentSource::Type)
LValue MakeAddrLValue (Address Addr, QualType T, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo)
LValue MakeAddrLValue (llvm::Value *V, QualType T, CharUnits Alignment, AlignmentSource Source=AlignmentSource::Type)
LValue MakeRawAddrLValue (llvm::Value *V, QualType T, CharUnits Alignment, AlignmentSource Source=AlignmentSource::Type)
Same as MakeAddrLValue above except that the pointer is known to be unsigned.
LValue MakeAddrLValueWithoutTBAA (Address Addr, QualType T, AlignmentSource Source=AlignmentSource::Type)
LValue MakeNaturalAlignPointeeAddrLValue (llvm::Value *V, QualType T)
Given a value of type T* that may not be to a complete object, construct an l-value with the natural pointee alignment of T.
LValue MakeNaturalAlignAddrLValue (llvm::Value *V, QualType T)
LValue MakeNaturalAlignPointeeRawAddrLValue (llvm::Value *V, QualType T)
Same as MakeNaturalAlignPointeeAddrLValue except that the pointer is known to be unsigned.
LValue MakeNaturalAlignRawAddrLValue (llvm::Value *V, QualType T)
Address EmitLoadOfReference (LValue RefLVal, LValueBaseInfo *PointeeBaseInfo=nullptr, TBAAAccessInfo *PointeeTBAAInfo=nullptr)
LValue EmitLoadOfReferenceLValue (LValue RefLVal)
LValue EmitLoadOfReferenceLValue (Address RefAddr, QualType RefTy, AlignmentSource Source=AlignmentSource::Type)
Address EmitLoadOfPointer (Address Ptr, const PointerType *PtrTy, LValueBaseInfo *BaseInfo=nullptr, TBAAAccessInfo *TBAAInfo=nullptr)
Load a pointer with type PtrTy stored at address Ptr.
LValue EmitLoadOfPointerLValue (Address Ptr, const PointerType *PtrTy)
llvm::AllocaInst * CreateTempAlloca (llvm::Type *Ty, const Twine &Name="tmp", llvm::Value *ArraySize=nullptr)
CreateTempAlloca - This creates an alloca and inserts it into the entry block if ArraySize is nullptr, otherwise inserts it at the current insertion point of the builder.
RawAddress CreateTempAlloca (llvm::Type *Ty, CharUnits align, const Twine &Name="tmp", llvm::Value *ArraySize=nullptr, RawAddress *Alloca=nullptr)
CreateTempAlloca - This creates a alloca and inserts it into the entry block.
RawAddress CreateTempAllocaWithoutCast (llvm::Type *Ty, CharUnits align, const Twine &Name="tmp", llvm::Value *ArraySize=nullptr)
CreateTempAlloca - This creates a alloca and inserts it into the entry block.
RawAddress CreateDefaultAlignTempAlloca (llvm::Type *Ty, const Twine &Name="tmp")
CreateDefaultAlignedTempAlloca - This creates an alloca with the default ABI alignment of the given LLVM type.
RawAddress CreateIRTemp (QualType T, const Twine &Name="tmp")
CreateIRTemp - Create a temporary IR object of the given type, with appropriate alignment.
RawAddress CreateMemTemp (QualType T, const Twine &Name="tmp", RawAddress *Alloca=nullptr)
CreateMemTemp - Create a temporary memory object of the given type, with appropriate alignmen and cast it to the default address space.
RawAddress CreateMemTemp (QualType T, CharUnits Align, const Twine &Name="tmp", RawAddress *Alloca=nullptr)
RawAddress CreateMemTempWithoutCast (QualType T, const Twine &Name="tmp")
CreateMemTemp - Create a temporary memory object of the given type, with appropriate alignmen without casting it to the default address space.
RawAddress CreateMemTempWithoutCast (QualType T, CharUnits Align, const Twine &Name="tmp")
AggValueSlot CreateAggTemp (QualType T, const Twine &Name="tmp", RawAddress *Alloca=nullptr)
CreateAggTemp - Create a temporary memory object for the given aggregate type.
llvm::Value * EvaluateExprAsBool (const Expr *E)
EvaluateExprAsBool - Perform the usual unary conversions on the specified expression and compare the result against zero, returning an Int1Ty value.
llvm::Value * EmitWithOriginalRHSBitfieldAssignment (const BinaryOperator *E, llvm::Value **Previous, QualType *SrcType)
Retrieve the implicit cast expression of the rhs in a binary operator expression by passing pointers to Value and QualType This is used for implicit bitfield conversion checks, which must compare with the value before potential truncation.
void EmitBitfieldConversionCheck (llvm::Value *Src, QualType SrcType, llvm::Value *Dst, QualType DstType, const CGBitFieldInfo &Info, SourceLocation Loc)
Emit a check that an [implicit] conversion of a bitfield.
void EmitIgnoredExpr (const Expr *E)
EmitIgnoredExpr - Emit an expression in a context which ignores the result.
RValue EmitAnyExpr (const Expr *E, AggValueSlot aggSlot=AggValueSlot::ignored(), bool ignoreResult=false)
EmitAnyExpr - Emit code to compute the specified expression which can have any type.
Address EmitVAListRef (const Expr *E)
Address EmitMSVAListRef (const Expr *E)
Emit a "reference" to a __builtin_ms_va_list; this is always the value of the expression, because a __builtin_ms_va_list is a pointer to a char.
RValue EmitAnyExprToTemp (const Expr *E)
EmitAnyExprToTemp - Similarly to EmitAnyExpr(), however, the result will always be accessible even if no aggregate location is provided.
void EmitAnyExprToMem (const Expr *E, Address Location, Qualifiers Quals, bool IsInitializer)
EmitAnyExprToMem - Emits the code necessary to evaluate an arbitrary expression into the given memory location.
void EmitAnyExprToExn (const Expr *E, Address Addr)
void EmitExprAsInit (const Expr *init, const ValueDecl *D, LValue lvalue, bool capturedByInit)
EmitExprAsInit - Emits the code necessary to initialize a location in memory with the given initializer.
bool hasVolatileMember (QualType T)
hasVolatileMember - returns true if aggregate type has a volatile member.
AggValueSlot::Overlap_t getOverlapForReturnValue ()
Determine whether a return value slot may overlap some other object.
AggValueSlot::Overlap_t getOverlapForFieldInit (const FieldDecl *FD)
Determine whether a field initialization may overlap some other object.
AggValueSlot::Overlap_t getOverlapForBaseInit (const CXXRecordDecl *RD, const CXXRecordDecl *BaseRD, bool IsVirtual)
Determine whether a base class initialization may overlap some other object.
void EmitAggregateAssign (LValue Dest, LValue Src, QualType EltTy)
Emit an aggregate assignment.
void EmitAggregateCopyCtor (LValue Dest, LValue Src, AggValueSlot::Overlap_t MayOverlap)
void EmitAggregateCopy (LValue Dest, LValue Src, QualType EltTy, AggValueSlot::Overlap_t MayOverlap, bool isVolatile=false)
EmitAggregateCopy - Emit an aggregate copy.
Address GetAddrOfLocalVar (const VarDecl *VD)
GetAddrOfLocalVar - Return the address of a local variable.
LValue getOrCreateOpaqueLValueMapping (const OpaqueValueExpr *e)
Given an opaque value expression, return its LValue mapping if it exists, otherwise create one.
RValue getOrCreateOpaqueRValueMapping (const OpaqueValueExpr *e)
Given an opaque value expression, return its RValue mapping if it exists, otherwise create one.
llvm::Value * getArrayInitIndex ()
Get the index of the current ArrayInitLoopExpr, if any.
llvm::BlockAddress * GetAddrOfLabel (const LabelDecl *L)
llvm::BasicBlock * GetIndirectGotoBlock ()
void EmitNullInitialization (Address DestPtr, QualType Ty)
EmitNullInitialization - Generate code to set a value of the given type to null, If the type contains data member pointers, they will be initialized to -1 in accordance with the Itanium C++ ABI.
llvm::Value * EmitVAStartEnd (llvm::Value *ArgValue, bool IsStart)
Emits a call to an LLVM variable-argument intrinsic, either llvm.va_start or llvm.va_end.
Address EmitVAArg (VAArgExpr *VE, Address &VAListAddr)
Generate code to get an argument from the passed in pointer and update it accordingly.
llvm::Value * emitArrayLength (const ArrayType *arrayType, QualType &baseType, Address &addr)
emitArrayLength - Compute the length of an array, even if it's a VLA, and drill down to the base element type.
void EmitVariablyModifiedType (QualType Ty)
EmitVLASize - Capture all the sizes for the VLA expressions in the given variably-modified type and store them in the VLASizeMap.
VlaSizePair getVLAElements1D (const VariableArrayType *vla)
Return the number of elements for a single dimension for the given array type.
VlaSizePair getVLAElements1D (QualType vla)
VlaSizePair getVLASize (const VariableArrayType *vla)
Returns an LLVM value that corresponds to the size, in non-variably-sized elements, of a variable length array type, plus that largest non-variably-sized element type.
VlaSizePair getVLASize (QualType vla)
llvm::Value * LoadCXXThis ()
LoadCXXThis - Load the value of 'this'.
Address LoadCXXThisAddress ()
llvm::Value * LoadCXXVTT ()
LoadCXXVTT - Load the VTT parameter to base constructors/destructors have virtual bases.
Address GetAddressOfDirectBaseInCompleteClass (Address Value, const CXXRecordDecl *Derived, const CXXRecordDecl *Base, bool BaseIsVirtual)
GetAddressOfBaseOfCompleteClass - Convert the given pointer to a complete class to the given direct base.
Address GetAddressOfBaseClass (Address Value, const CXXRecordDecl *Derived, CastExpr::path_const_iterator PathBegin, CastExpr::path_const_iterator PathEnd, bool NullCheckValue, SourceLocation Loc)
GetAddressOfBaseClass - This function will add the necessary delta to the load of 'this' and returns address of the base class.
Address GetAddressOfDerivedClass (Address Value, const CXXRecordDecl *Derived, CastExpr::path_const_iterator PathBegin, CastExpr::path_const_iterator PathEnd, bool NullCheckValue)
llvm::Value * GetVTTParameter (GlobalDecl GD, bool ForVirtualBase, bool Delegating)
GetVTTParameter - Return the VTT parameter that should be passed to a base constructor/destructor with virtual bases.
void EmitDelegateCXXConstructorCall (const CXXConstructorDecl *Ctor, CXXCtorType CtorType, const FunctionArgList &Args, SourceLocation Loc)
void EmitDelegatingCXXConstructorCall (const CXXConstructorDecl *Ctor, const FunctionArgList &Args)
void EmitInlinedInheritingCXXConstructorCall (const CXXConstructorDecl *Ctor, CXXCtorType CtorType, bool ForVirtualBase, bool Delegating, CallArgList &Args)
Emit a call to an inheriting constructor (that is, one that invokes a constructor inherited from a base class) by inlining its definition.
void EmitInheritedCXXConstructorCall (const CXXConstructorDecl *D, bool ForVirtualBase, Address This, bool InheritedFromVBase, const CXXInheritedCtorInitExpr *E)
Emit a call to a constructor inherited from a base class, passing the current constructor's arguments along unmodified (without even making a copy).
void EmitCXXConstructorCall (const CXXConstructorDecl *D, CXXCtorType Type, bool ForVirtualBase, bool Delegating, AggValueSlot ThisAVS, const CXXConstructExpr *E)
void EmitCXXConstructorCall (const CXXConstructorDecl *D, CXXCtorType Type, bool ForVirtualBase, bool Delegating, Address This, CallArgList &Args, AggValueSlot::Overlap_t Overlap, SourceLocation Loc, bool NewPointerIsChecked)
void EmitVTableAssumptionLoads (const CXXRecordDecl *ClassDecl, Address This)
Emit assumption load for all bases.
void EmitVTableAssumptionLoad (const VPtr &vptr, Address This)
Emit assumption that vptr load == global vtable.
void EmitSynthesizedCXXCopyCtorCall (const CXXConstructorDecl *D, Address This, Address Src, const CXXConstructExpr *E)
void EmitCXXAggrConstructorCall (const CXXConstructorDecl *D, const ArrayType *ArrayTy, Address ArrayPtr, const CXXConstructExpr *E, bool NewPointerIsChecked, bool ZeroInitialization=false)
EmitCXXAggrConstructorCall - Emit a loop to call a particular constructor for each of several members of an array.
void EmitCXXAggrConstructorCall (const CXXConstructorDecl *D, llvm::Value *NumElements, Address ArrayPtr, const CXXConstructExpr *E, bool NewPointerIsChecked, bool ZeroInitialization=false)
EmitCXXAggrConstructorCall - Emit a loop to call a particular constructor for each of several members of an array.
void EmitCXXDestructorCall (const CXXDestructorDecl *D, CXXDtorType Type, bool ForVirtualBase, bool Delegating, Address This, QualType ThisTy)
void EmitNewArrayInitializer (const CXXNewExpr *E, QualType elementType, llvm::Type *ElementTy, Address NewPtr, llvm::Value *NumElements, llvm::Value *AllocSizeWithoutCookie)
void EmitCXXTemporary (const CXXTemporary *Temporary, QualType TempType, Address Ptr)
Emits all the code to cause the given temporary to be cleaned up.
void EmitSehCppScopeBegin ()
void EmitSehCppScopeEnd ()
void EmitSehTryScopeBegin ()
void EmitSehTryScopeEnd ()
llvm::Value * EmitLifetimeStart (llvm::TypeSize Size, llvm::Value *Addr)
Emit a lifetime.begin marker if some criteria are satisfied.
void EmitLifetimeEnd (llvm::Value *Size, llvm::Value *Addr)
llvm::Value * EmitCXXNewExpr (const CXXNewExpr *E)
void EmitCXXDeleteExpr (const CXXDeleteExpr *E)
void EmitDeleteCall (const FunctionDecl *DeleteFD, llvm::Value *Ptr, QualType DeleteTy, llvm::Value *NumElements=nullptr, CharUnits CookieSize=CharUnits())
RValue EmitBuiltinNewDeleteCall (const FunctionProtoType *Type, const CallExpr *TheCallExpr, bool IsDelete)
llvm::Value * EmitCXXTypeidExpr (const CXXTypeidExpr *E)
llvm::Value * EmitDynamicCast (Address V, const CXXDynamicCastExpr *DCE)
Address EmitCXXUuidofExpr (const CXXUuidofExpr *E)
bool sanitizePerformTypeCheck () const
Whether any type-checking sanitizers are enabled.
void EmitTypeCheck (TypeCheckKind TCK, SourceLocation Loc, LValue LV, QualType Type, SanitizerSet SkippedChecks=SanitizerSet(), llvm::Value *ArraySize=nullptr)
void EmitTypeCheck (TypeCheckKind TCK, SourceLocation Loc, Address Addr, QualType Type, CharUnits Alignment=CharUnits::Zero(), SanitizerSet SkippedChecks=SanitizerSet(), llvm::Value *ArraySize=nullptr)
void EmitTypeCheck (TypeCheckKind TCK, SourceLocation Loc, llvm::Value *V, QualType Type, CharUnits Alignment=CharUnits::Zero(), SanitizerSet SkippedChecks=SanitizerSet(), llvm::Value *ArraySize=nullptr)
Emit a check that V is the address of storage of the appropriate size and alignment for an object of type Type (or if ArraySize is provided, for an array of that bound).
void EmitBoundsCheck (const Expr *E, const Expr *Base, llvm::Value *Index, QualType IndexType, bool Accessed)
Emit a check that Base points into an array object, which we can access at index Index.
void EmitBoundsCheckImpl (const Expr *E, llvm::Value *Bound, llvm::Value *Index, QualType IndexType, QualType IndexedType, bool Accessed)
const FieldDecl * FindFlexibleArrayMemberField (ASTContext &Ctx, const RecordDecl *RD, StringRef Name, uint64_t &Offset)
const FieldDecl * FindCountedByField (const FieldDecl *FD)
Find the FieldDecl specified in a FAM's "counted_by" attribute.
llvm::Value * EmitCountedByFieldExpr (const Expr *Base, const FieldDecl *FAMDecl, const FieldDecl *CountDecl)
Build an expression accessing the "counted_by" field.
llvm::Value * EmitScalarPrePostIncDec (const UnaryOperator *E, LValue LV, bool isInc, bool isPre)
ComplexPairTy EmitComplexPrePostIncDec (const UnaryOperator *E, LValue LV, bool isInc, bool isPre)
llvm::DebugLoc SourceLocToDebugLoc (SourceLocation Location)
Converts Location to a DebugLoc, if debug information is enabled.
unsigned getDebugInfoFIndex (const RecordDecl *Rec, unsigned FieldIndex)
Get the record field index as represented in debug info.
void EmitDecl (const Decl &D)
EmitDecl - Emit a declaration.
void EmitVarDecl (const VarDecl &D)
EmitVarDecl - Emit a local variable declaration.
void EmitScalarInit (const Expr *init, const ValueDecl *D, LValue lvalue, bool capturedByInit)
bool isTrivialInitializer (const Expr *Init)
Determine whether the given initializer is trivial in the sense that it requires no code to be generated.
void EmitAutoVarDecl (const VarDecl &D)
EmitAutoVarDecl - Emit an auto variable declaration.
AutoVarEmission EmitAutoVarAlloca (const VarDecl &var)
EmitAutoVarAlloca - Emit the alloca and debug information for a local variable.
void EmitAutoVarInit (const AutoVarEmission &emission)
void EmitAutoVarCleanups (const AutoVarEmission &emission)
void emitAutoVarTypeCleanup (const AutoVarEmission &emission, QualType::DestructionKind dtorKind)
Enter a destroy cleanup for the given local variable.
void EmitAndRegisterVariableArrayDimensions (CGDebugInfo *DI, const VarDecl &D, bool EmitDebugInfo)
Emits the alloca and debug information for the size expressions for each dimension of an array.
void EmitStaticVarDecl (const VarDecl &D, llvm::GlobalValue::LinkageTypes Linkage)
void EmitParmDecl (const VarDecl &D, ParamValue Arg, unsigned ArgNo)
EmitParmDecl - Emit a ParmVarDecl or an ImplicitParamDecl.
PeepholeProtection protectFromPeepholes (RValue rvalue)
protectFromPeepholes - Protect a value that we're intending to store to the side, but which will probably be used later, from aggressive peepholing optimizations that might delete it.
void unprotectFromPeepholes (PeepholeProtection protection)
void emitAlignmentAssumptionCheck (llvm::Value *Ptr, QualType Ty, SourceLocation Loc, SourceLocation AssumptionLoc, llvm::Value *Alignment, llvm::Value *OffsetValue, llvm::Value *TheCheck, llvm::Instruction *Assumption)
void emitAlignmentAssumption (llvm::Value *PtrValue, QualType Ty, SourceLocation Loc, SourceLocation AssumptionLoc, llvm::Value *Alignment, llvm::Value *OffsetValue=nullptr)
void emitAlignmentAssumption (llvm::Value *PtrValue, const Expr *E, SourceLocation AssumptionLoc, llvm::Value *Alignment, llvm::Value *OffsetValue=nullptr)
void EmitStopPoint (const Stmt *S)
EmitStopPoint - Emit a debug stoppoint if we are emitting debug info.
void EmitStmt (const Stmt *S, ArrayRef< const Attr * > Attrs=std::nullopt)
EmitStmt - Emit the code for the statement.
bool EmitSimpleStmt (const Stmt *S, ArrayRef< const Attr * > Attrs)
EmitSimpleStmt - Try to emit a "simple" statement which does not necessarily require an insertion point or debug information; typically because the statement amounts to a jump or a container of other statements.
Address EmitCompoundStmt (const CompoundStmt &S, bool GetLast=false, AggValueSlot AVS=AggValueSlot::ignored())
EmitCompoundStmt - Emit a compound statement {..} node.
Address EmitCompoundStmtWithoutScope (const CompoundStmt &S, bool GetLast=false, AggValueSlot AVS=AggValueSlot::ignored())
void EmitLabel (const LabelDecl *D)
EmitLabel - Emit the block for the given label.
void EmitLabelStmt (const LabelStmt &S)
void EmitAttributedStmt (const AttributedStmt &S)
void EmitGotoStmt (const GotoStmt &S)
void EmitIndirectGotoStmt (const IndirectGotoStmt &S)
void EmitIfStmt (const IfStmt &S)
void EmitWhileStmt (const WhileStmt &S, ArrayRef< const Attr * > Attrs=std::nullopt)
void EmitDoStmt (const DoStmt &S, ArrayRef< const Attr * > Attrs=std::nullopt)
void EmitForStmt (const ForStmt &S, ArrayRef< const Attr * > Attrs=std::nullopt)
void EmitReturnStmt (const ReturnStmt &S)
EmitReturnStmt - Note that due to GCC extensions, this can have an operand if the function returns void, or may be missing one if the function returns non-void.
void EmitDeclStmt (const DeclStmt &S)
void EmitBreakStmt (const BreakStmt &S)
void EmitContinueStmt (const ContinueStmt &S)
void EmitSwitchStmt (const SwitchStmt &S)
void EmitDefaultStmt (const DefaultStmt &S, ArrayRef< const Attr * > Attrs)
void EmitCaseStmt (const CaseStmt &S, ArrayRef< const Attr * > Attrs)
void EmitCaseStmtRange (const CaseStmt &S, ArrayRef< const Attr * > Attrs)
EmitCaseStmtRange - If case statement range is not too big then add multiple cases to switch instruction, one for each value within the range.
void EmitAsmStmt (const AsmStmt &S)
void EmitObjCForCollectionStmt (const ObjCForCollectionStmt &S)
void EmitObjCAtTryStmt (const ObjCAtTryStmt &S)
void EmitObjCAtThrowStmt (const ObjCAtThrowStmt &S)
void EmitObjCAtSynchronizedStmt (const ObjCAtSynchronizedStmt &S)
void EmitObjCAutoreleasePoolStmt (const ObjCAutoreleasePoolStmt &S)
void EmitCoroutineBody (const CoroutineBodyStmt &S)
void EmitCoreturnStmt (const CoreturnStmt &S)
RValue EmitCoawaitExpr (const CoawaitExpr &E, AggValueSlot aggSlot=AggValueSlot::ignored(), bool ignoreResult=false)
LValue EmitCoawaitLValue (const CoawaitExpr *E)
RValue EmitCoyieldExpr (const CoyieldExpr &E, AggValueSlot aggSlot=AggValueSlot::ignored(), bool ignoreResult=false)
LValue EmitCoyieldLValue (const CoyieldExpr *E)
RValue EmitCoroutineIntrinsic (const CallExpr *E, unsigned int IID)
void EnterCXXTryStmt (const CXXTryStmt &S, bool IsFnTryBlock=false)
void ExitCXXTryStmt (const CXXTryStmt &S, bool IsFnTryBlock=false)
void EmitCXXTryStmt (const CXXTryStmt &S)
void EmitSEHTryStmt (const SEHTryStmt &S)
void EmitSEHLeaveStmt (const SEHLeaveStmt &S)
void EnterSEHTryStmt (const SEHTryStmt &S)
void ExitSEHTryStmt (const SEHTryStmt &S)
void VolatilizeTryBlocks (llvm::BasicBlock *BB, llvm::SmallPtrSet< llvm::BasicBlock *, 10 > &V)
void pushSEHCleanup (CleanupKind kind, llvm::Function *FinallyFunc)
void startOutlinedSEHHelper (CodeGenFunction &ParentCGF, bool IsFilter, const Stmt *OutlinedStmt)
Arrange a function prototype that can be called by Windows exception handling personalities.
llvm::Function * GenerateSEHFilterFunction (CodeGenFunction &ParentCGF, const SEHExceptStmt &Except)
Create a stub filter function that will ultimately hold the code of the filter expression.
llvm::Function * GenerateSEHFinallyFunction (CodeGenFunction &ParentCGF, const SEHFinallyStmt &Finally)
void EmitSEHExceptionCodeSave (CodeGenFunction &ParentCGF, llvm::Value *ParentFP, llvm::Value *EntryEBP)
llvm::Value * EmitSEHExceptionCode ()
llvm::Value * EmitSEHExceptionInfo ()
llvm::Value * EmitSEHAbnormalTermination ()
void EmitSimpleOMPExecutableDirective (const OMPExecutableDirective &D)
Emit simple code for OpenMP directives in Simd-only mode.
void EmitCapturedLocals (CodeGenFunction &ParentCGF, const Stmt *OutlinedStmt, bool IsFilter)
Scan the outlined statement for captures from the parent function.
Address recoverAddrOfEscapedLocal (CodeGenFunction &ParentCGF, Address ParentVar, llvm::Value *ParentFP)
Recovers the address of a local in a parent function.
void EmitCXXForRangeStmt (const CXXForRangeStmt &S, ArrayRef< const Attr * > Attrs=std::nullopt)
llvm::Value * getTypeSize (QualType Ty)
Returns calculated size of the specified type.
LValue InitCapturedStruct (const CapturedStmt &S)
llvm::Function * EmitCapturedStmt (const CapturedStmt &S, CapturedRegionKind K)
Generate an outlined function for the body of a CapturedStmt, store any captured variables into the captured struct, and call the outlined function.
llvm::Function * GenerateCapturedStmtFunction (const CapturedStmt &S)
Creates the outlined function for a CapturedStmt.
Address GenerateCapturedStmtArgument (const CapturedStmt &S)
llvm::Function * GenerateOpenMPCapturedStmtFunction (const CapturedStmt &S, SourceLocation Loc)
void GenerateOpenMPCapturedVars (const CapturedStmt &S, SmallVectorImpl< llvm::Value * > &CapturedVars)
void emitOMPSimpleStore (LValue LVal, RValue RVal, QualType RValTy, SourceLocation Loc)
void EmitOMPAggregateAssign (Address DestAddr, Address SrcAddr, QualType OriginalType, const llvm::function_ref< void(Address, Address)> CopyGen)
Perform element by element copying of arrays with type OriginalType from SrcAddr to DestAddr using copying procedure generated by CopyGen.
void EmitOMPCopy (QualType OriginalType, Address DestAddr, Address SrcAddr, const VarDecl *DestVD, const VarDecl *SrcVD, const Expr *Copy)
Emit proper copying of data from one variable to another.
std::pair< bool, RValue > EmitOMPAtomicSimpleUpdateExpr (LValue X, RValue E, BinaryOperatorKind BO, bool IsXLHSInRHSPart, llvm::AtomicOrdering AO, SourceLocation Loc, const llvm::function_ref< RValue(RValue)> CommonGen)
Emit atomic update code for constructs: X = X BO E or X = E BO E.
bool EmitOMPFirstprivateClause (const OMPExecutableDirective &D, OMPPrivateScope &PrivateScope)
void EmitOMPPrivateClause (const OMPExecutableDirective &D, OMPPrivateScope &PrivateScope)
void EmitOMPUseDevicePtrClause (const OMPUseDevicePtrClause &C, OMPPrivateScope &PrivateScope, const llvm::DenseMap< const ValueDecl *, llvm::Value * > CaptureDeviceAddrMap)
void EmitOMPUseDeviceAddrClause (const OMPUseDeviceAddrClause &C, OMPPrivateScope &PrivateScope, const llvm::DenseMap< const ValueDecl *, llvm::Value * > CaptureDeviceAddrMap)
bool EmitOMPCopyinClause (const OMPExecutableDirective &D)
Emit code for copyin clause in D directive.
bool EmitOMPLastprivateClauseInit (const OMPExecutableDirective &D, OMPPrivateScope &PrivateScope)
Emit initial code for lastprivate variables.
void EmitOMPLastprivateClauseFinal (const OMPExecutableDirective &D, bool NoFinals, llvm::Value *IsLastIterCond=nullptr)
Emit final copying of lastprivate values to original variables at the end of the worksharing or simd directive.
void EmitOMPLinearClause (const OMPLoopDirective &D, CodeGenFunction::OMPPrivateScope &PrivateScope)
Emit initial code for linear clauses.
void EmitOMPLinearClauseFinal (const OMPLoopDirective &D, const llvm::function_ref< llvm::Value *(CodeGenFunction &)> CondGen)
Emit final code for linear clauses.
void EmitOMPReductionClauseInit (const OMPExecutableDirective &D, OMPPrivateScope &PrivateScope, bool ForInscan=false)
Emit initial code for reduction variables.
void EmitOMPReductionClauseFinal (const OMPExecutableDirective &D, const OpenMPDirectiveKind ReductionKind)
Emit final update of reduction values to original variables at the end of the directive.
bool EmitOMPLinearClauseInit (const OMPLoopDirective &D)
Emit initial code for linear variables.
void EmitOMPTaskBasedDirective (const OMPExecutableDirective &S, const OpenMPDirectiveKind CapturedRegion, const RegionCodeGenTy &BodyGen, const TaskGenTy &TaskGen, OMPTaskDataTy &Data)
void EmitOMPTargetTaskBasedDirective (const OMPExecutableDirective &S, const RegionCodeGenTy &BodyGen, OMPTargetDataInfo &InputInfo)
void processInReduction (const OMPExecutableDirective &S, OMPTaskDataTy &Data, CodeGenFunction &CGF, const CapturedStmt *CS, OMPPrivateScope &Scope)
void EmitOMPMetaDirective (const OMPMetaDirective &S)
void EmitOMPParallelDirective (const OMPParallelDirective &S)
void EmitOMPSimdDirective (const OMPSimdDirective &S)
void EmitOMPTileDirective (const OMPTileDirective &S)
void EmitOMPUnrollDirective (const OMPUnrollDirective &S)
void EmitOMPForDirective (const OMPForDirective &S)
void EmitOMPForSimdDirective (const OMPForSimdDirective &S)
void EmitOMPSectionsDirective (const OMPSectionsDirective &S)
void EmitOMPSectionDirective (const OMPSectionDirective &S)
void EmitOMPSingleDirective (const OMPSingleDirective &S)
void EmitOMPMasterDirective (const OMPMasterDirective &S)
void EmitOMPMaskedDirective (const OMPMaskedDirective &S)
void EmitOMPCriticalDirective (const OMPCriticalDirective &S)
void EmitOMPParallelForDirective (const OMPParallelForDirective &S)
void EmitOMPParallelForSimdDirective (const OMPParallelForSimdDirective &S)
void EmitOMPParallelSectionsDirective (const OMPParallelSectionsDirective &S)
void EmitOMPParallelMasterDirective (const OMPParallelMasterDirective &S)
void EmitOMPTaskDirective (const OMPTaskDirective &S)
void EmitOMPTaskyieldDirective (const OMPTaskyieldDirective &S)
void EmitOMPErrorDirective (const OMPErrorDirective &S)
void EmitOMPBarrierDirective (const OMPBarrierDirective &S)
void EmitOMPTaskwaitDirective (const OMPTaskwaitDirective &S)
void EmitOMPTaskgroupDirective (const OMPTaskgroupDirective &S)
void EmitOMPFlushDirective (const OMPFlushDirective &S)
void EmitOMPDepobjDirective (const OMPDepobjDirective &S)
void EmitOMPScanDirective (const OMPScanDirective &S)
void EmitOMPOrderedDirective (const OMPOrderedDirective &S)
void EmitOMPAtomicDirective (const OMPAtomicDirective &S)
void EmitOMPTargetDirective (const OMPTargetDirective &S)
void EmitOMPTargetDataDirective (const OMPTargetDataDirective &S)
void EmitOMPTargetEnterDataDirective (const OMPTargetEnterDataDirective &S)
void EmitOMPTargetExitDataDirective (const OMPTargetExitDataDirective &S)
void EmitOMPTargetUpdateDirective (const OMPTargetUpdateDirective &S)
void EmitOMPTargetParallelDirective (const OMPTargetParallelDirective &S)
void EmitOMPTargetParallelForDirective (const OMPTargetParallelForDirective &S)
void EmitOMPTeamsDirective (const OMPTeamsDirective &S)
void EmitOMPCancellationPointDirective (const OMPCancellationPointDirective &S)
void EmitOMPCancelDirective (const OMPCancelDirective &S)
void EmitOMPTaskLoopBasedDirective (const OMPLoopDirective &S)
void EmitOMPTaskLoopDirective (const OMPTaskLoopDirective &S)
void EmitOMPTaskLoopSimdDirective (const OMPTaskLoopSimdDirective &S)
void EmitOMPMasterTaskLoopDirective (const OMPMasterTaskLoopDirective &S)
void EmitOMPMasterTaskLoopSimdDirective (const OMPMasterTaskLoopSimdDirective &S)
void EmitOMPParallelMasterTaskLoopDirective (const OMPParallelMasterTaskLoopDirective &S)
void EmitOMPParallelMasterTaskLoopSimdDirective (const OMPParallelMasterTaskLoopSimdDirective &S)
void EmitOMPDistributeDirective (const OMPDistributeDirective &S)
void EmitOMPDistributeParallelForDirective (const OMPDistributeParallelForDirective &S)
void EmitOMPDistributeParallelForSimdDirective (const OMPDistributeParallelForSimdDirective &S)
void EmitOMPDistributeSimdDirective (const OMPDistributeSimdDirective &S)
void EmitOMPTargetParallelForSimdDirective (const OMPTargetParallelForSimdDirective &S)
void EmitOMPTargetSimdDirective (const OMPTargetSimdDirective &S)
void EmitOMPTeamsDistributeDirective (const OMPTeamsDistributeDirective &S)
void EmitOMPTeamsDistributeSimdDirective (const OMPTeamsDistributeSimdDirective &S)
void EmitOMPTeamsDistributeParallelForSimdDirective (const OMPTeamsDistributeParallelForSimdDirective &S)
void EmitOMPTeamsDistributeParallelForDirective (const OMPTeamsDistributeParallelForDirective &S)
void EmitOMPTargetTeamsDirective (const OMPTargetTeamsDirective &S)
void EmitOMPTargetTeamsDistributeDirective (const OMPTargetTeamsDistributeDirective &S)
void EmitOMPTargetTeamsDistributeParallelForDirective (const OMPTargetTeamsDistributeParallelForDirective &S)
void EmitOMPTargetTeamsDistributeParallelForSimdDirective (const OMPTargetTeamsDistributeParallelForSimdDirective &S)
void EmitOMPTargetTeamsDistributeSimdDirective (const OMPTargetTeamsDistributeSimdDirective &S)
void EmitOMPGenericLoopDirective (const OMPGenericLoopDirective &S)
void EmitOMPParallelGenericLoopDirective (const OMPLoopDirective &S)
void EmitOMPTargetParallelGenericLoopDirective (const OMPTargetParallelGenericLoopDirective &S)
Emit combined directive 'target parallel loop' as if its constituent constructs are 'target', 'parallel', and 'for'.
void EmitOMPTargetTeamsGenericLoopDirective (const OMPTargetTeamsGenericLoopDirective &S)
void EmitOMPTeamsGenericLoopDirective (const OMPTeamsGenericLoopDirective &S)
void EmitOMPInteropDirective (const OMPInteropDirective &S)
void EmitOMPParallelMaskedDirective (const OMPParallelMaskedDirective &S)
llvm::CanonicalLoopInfo * EmitOMPCollapsedCanonicalLoopNest (const Stmt *S, int Depth)
Emit the Stmt S and return its topmost canonical loop, if any.
void EmitOMPCanonicalLoop (const OMPCanonicalLoop *S)
Emit an OMPCanonicalLoop using the OpenMPIRBuilder.
void EmitOMPInnerLoop (const OMPExecutableDirective &S, bool RequiresCleanup, const Expr *LoopCond, const Expr *IncExpr, const llvm::function_ref< void(CodeGenFunction &)> BodyGen, const llvm::function_ref< void(CodeGenFunction &)> PostIncGen)
Emit inner loop of the worksharing/simd construct.
JumpDest getOMPCancelDestination (OpenMPDirectiveKind Kind)
void EmitOMPPrivateLoopCounters (const OMPLoopDirective &S, OMPPrivateScope &LoopScope)
Emit initial code for loop counters of loop-based directives.
void EmitOMPLoopBody (const OMPLoopDirective &D, JumpDest LoopExit)
Helper for the OpenMP loop directives.
bool EmitOMPWorksharingLoop (const OMPLoopDirective &S, Expr *EUB, const CodeGenLoopBoundsTy &CodeGenLoopBounds, const CodeGenDispatchBoundsTy &CGDispatchBounds)
Emit code for the worksharing loop-based directive.
void EmitOMPDistributeLoop (const OMPLoopDirective &S, const CodeGenLoopTy &CodeGenLoop, Expr *IncExpr)
Emit code for the distribute loop-based directive.
void EmitOMPSimdInit (const OMPLoopDirective &D)
Helpers for the OpenMP loop directives.
void EmitOMPSimdFinal (const OMPLoopDirective &D, const llvm::function_ref< llvm::Value *(CodeGenFunction &)> CondGen)
LValue EmitOMPSharedLValue (const Expr *E)
Emits the lvalue for the expression with possibly captured variable.
void EmitOpenACCComputeConstruct (const OpenACCComputeConstruct &S)
llvm::Value * EmitNonNullRValueCheck (RValue RV, QualType T)
Create a check that a scalar RValue is non-null.
RValue GetUndefRValue (QualType Ty)
GetUndefRValue - Get an appropriate 'undef' rvalue for the given type.
RValue EmitUnsupportedRValue (const Expr *E, const char *Name)
EmitUnsupportedRValue - Emit a dummy r-value using the type of E and issue an ErrorUnsupported style diagnostic (using the provided Name).
LValue EmitUnsupportedLValue (const Expr *E, const char *Name)
EmitUnsupportedLValue - Emit a dummy l-value using the type of E and issue an ErrorUnsupported style diagnostic (using the provided Name).
LValue EmitLValue (const Expr *E, KnownNonNull_t IsKnownNonNull=NotKnownNonNull)
EmitLValue - Emit code to compute a designator that specifies the location of the expression.
LValue EmitCheckedLValue (const Expr *E, TypeCheckKind TCK)
Same as EmitLValue but additionally we generate checking code to guard against undefined behavior.
RValue convertTempToRValue (Address addr, QualType type, SourceLocation Loc)
Given the address of a temporary variable, produce an r-value of its type.
void EmitAtomicInit (Expr *E, LValue lvalue)
bool LValueIsSuitableForInlineAtomic (LValue Src)
An LValue is a candidate for having its loads and stores be made atomic if we are operating under /volatile:ms and the LValue itself is volatile and performing such an operation can be performed without a libcall.
RValue EmitAtomicLoad (LValue LV, SourceLocation SL, AggValueSlot Slot=AggValueSlot::ignored())
RValue EmitAtomicLoad (LValue lvalue, SourceLocation loc, llvm::AtomicOrdering AO, bool IsVolatile=false, AggValueSlot slot=AggValueSlot::ignored())
Emit a load from an l-value of atomic type.
void EmitAtomicStore (RValue rvalue, LValue lvalue, bool isInit)
void EmitAtomicStore (RValue rvalue, LValue lvalue, llvm::AtomicOrdering AO, bool IsVolatile, bool isInit)
Emit a store to an l-value of atomic type.
std::pair< RValue, llvm::Value * > EmitAtomicCompareExchange (LValue Obj, RValue Expected, RValue Desired, SourceLocation Loc, llvm::AtomicOrdering Success=llvm::AtomicOrdering::SequentiallyConsistent, llvm::AtomicOrdering Failure=llvm::AtomicOrdering::SequentiallyConsistent, bool IsWeak=false, AggValueSlot Slot=AggValueSlot::ignored())
Emit a compare-and-exchange op for atomic type.
void EmitAtomicUpdate (LValue LVal, llvm::AtomicOrdering AO, const llvm::function_ref< RValue(RValue)> &UpdateOp, bool IsVolatile)
llvm::Value * EmitToMemory (llvm::Value *Value, QualType Ty)
EmitToMemory - Change a scalar value from its value representation to its in-memory representation.
llvm::Value * EmitFromMemory (llvm::Value *Value, QualType Ty)
EmitFromMemory - Change a scalar value from its memory representation to its value representation.
bool EmitScalarRangeCheck (llvm::Value *Value, QualType Ty, SourceLocation Loc)
Check if the scalar Value is within the valid range for the given type Ty.
llvm::Value * EmitLoadOfScalar (Address Addr, bool Volatile, QualType Ty, SourceLocation Loc, AlignmentSource Source=AlignmentSource::Type, bool isNontemporal=false)
EmitLoadOfScalar - Load a scalar value from an address, taking care to appropriately convert from the memory representation to the LLVM value representation.
llvm::Value * EmitLoadOfScalar (Address Addr, bool Volatile, QualType Ty, SourceLocation Loc, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo, bool isNontemporal=false)
llvm::Value * EmitLoadOfScalar (LValue lvalue, SourceLocation Loc)
EmitLoadOfScalar - Load a scalar value from an address, taking care to appropriately convert from the memory representation to the LLVM value representation.
void EmitStoreOfScalar (llvm::Value *Value, Address Addr, bool Volatile, QualType Ty, AlignmentSource Source=AlignmentSource::Type, bool isInit=false, bool isNontemporal=false)
EmitStoreOfScalar - Store a scalar value to an address, taking care to appropriately convert from the memory representation to the LLVM value representation.
void EmitStoreOfScalar (llvm::Value *Value, Address Addr, bool Volatile, QualType Ty, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo, bool isInit=false, bool isNontemporal=false)
void EmitStoreOfScalar (llvm::Value *value, LValue lvalue, bool isInit=false)
EmitStoreOfScalar - Store a scalar value to an address, taking care to appropriately convert from the memory representation to the LLVM value representation.
RValue EmitLoadOfLValue (LValue V, SourceLocation Loc)
EmitLoadOfLValue - Given an expression that represents a value lvalue, this method emits the address of the lvalue, then loads the result as an rvalue, returning the rvalue.
RValue EmitLoadOfExtVectorElementLValue (LValue V)
RValue EmitLoadOfBitfieldLValue (LValue LV, SourceLocation Loc)
RValue EmitLoadOfGlobalRegLValue (LValue LV)
Load of global gamed gegisters are always calls to intrinsics.
void EmitStoreThroughLValue (RValue Src, LValue Dst, bool isInit=false)
EmitStoreThroughLValue - Store the specified rvalue into the specified lvalue, where both are guaranteed to the have the same type, and that type is 'Ty'.
void EmitStoreThroughExtVectorComponentLValue (RValue Src, LValue Dst)
void EmitStoreThroughGlobalRegLValue (RValue Src, LValue Dst)
Store of global named registers are always calls to intrinsics.
void EmitStoreThroughBitfieldLValue (RValue Src, LValue Dst, llvm::Value **Result=nullptr)
EmitStoreThroughBitfieldLValue - Store Src into Dst with same constraints as EmitStoreThroughLValue.
LValue EmitComplexAssignmentLValue (const BinaryOperator *E)
Emit an l-value for an assignment (simple or compound) of complex type.
LValue EmitComplexCompoundAssignmentLValue (const CompoundAssignOperator *E)
LValue EmitScalarCompoundAssignWithComplex (const CompoundAssignOperator *E, llvm::Value *&Result)
LValue EmitBinaryOperatorLValue (const BinaryOperator *E)
LValue EmitCompoundAssignmentLValue (const CompoundAssignOperator *E)
LValue EmitCallExprLValue (const CallExpr *E)
LValue EmitVAArgExprLValue (const VAArgExpr *E)
LValue EmitDeclRefLValue (const DeclRefExpr *E)
LValue EmitStringLiteralLValue (const StringLiteral *E)
LValue EmitObjCEncodeExprLValue (const ObjCEncodeExpr *E)
LValue EmitPredefinedLValue (const PredefinedExpr *E)
LValue EmitUnaryOpLValue (const UnaryOperator *E)
LValue EmitArraySubscriptExpr (const ArraySubscriptExpr *E, bool Accessed=false)
LValue EmitMatrixSubscriptExpr (const MatrixSubscriptExpr *E)
LValue EmitOMPArraySectionExpr (const OMPArraySectionExpr *E, bool IsLowerBound=true)
LValue EmitExtVectorElementExpr (const ExtVectorElementExpr *E)
LValue EmitMemberExpr (const MemberExpr *E)
LValue EmitObjCIsaExpr (const ObjCIsaExpr *E)
LValue EmitCompoundLiteralLValue (const CompoundLiteralExpr *E)
LValue EmitInitListLValue (const InitListExpr *E)
void EmitIgnoredConditionalOperator (const AbstractConditionalOperator *E)
LValue EmitConditionalOperatorLValue (const AbstractConditionalOperator *E)
LValue EmitCastLValue (const CastExpr *E)
EmitCastLValue - Casts are never lvalues unless that cast is to a reference type.
LValue EmitMaterializeTemporaryExpr (const MaterializeTemporaryExpr *E)
LValue EmitOpaqueValueLValue (const OpaqueValueExpr *e)
Address EmitExtVectorElementLValue (LValue V)
Generates lvalue for partial ext_vector access.
RValue EmitRValueForField (LValue LV, const FieldDecl *FD, SourceLocation Loc)
Address EmitArrayToPointerDecay (const Expr *Array, LValueBaseInfo *BaseInfo=nullptr, TBAAAccessInfo *TBAAInfo=nullptr)
ConstantEmission tryEmitAsConstant (DeclRefExpr *refExpr)
Try to emit a reference to the given value without producing it as an l-value.
ConstantEmission tryEmitAsConstant (const MemberExpr *ME)
llvm::Value * emitScalarConstant (const ConstantEmission &Constant, Expr *E)
RValue EmitPseudoObjectRValue (const PseudoObjectExpr *e, AggValueSlot slot=AggValueSlot::ignored())
LValue EmitPseudoObjectLValue (const PseudoObjectExpr *e)
llvm::Value * EmitIvarOffset (const ObjCInterfaceDecl *Interface, const ObjCIvarDecl *Ivar)
llvm::Value * EmitIvarOffsetAsPointerDiff (const ObjCInterfaceDecl *Interface, const ObjCIvarDecl *Ivar)
LValue EmitLValueForField (LValue Base, const FieldDecl *Field)
LValue EmitLValueForLambdaField (const FieldDecl *Field)
LValue EmitLValueForLambdaField (const FieldDecl *Field, llvm::Value *ThisValue)
Given that we are currently emitting a lambda, emit an l-value for one of its members.
LValue EmitLValueForFieldInitialization (LValue Base, const FieldDecl *Field)
EmitLValueForFieldInitialization - Like EmitLValueForField, except that if the Field is a reference, this will return the address of the reference and not the address of the value stored in the reference.
LValue EmitLValueForIvar (QualType ObjectTy, llvm::Value *Base, const ObjCIvarDecl *Ivar, unsigned CVRQualifiers)
LValue EmitCXXConstructLValue (const CXXConstructExpr *E)
LValue EmitCXXBindTemporaryLValue (const CXXBindTemporaryExpr *E)
LValue EmitCXXTypeidLValue (const CXXTypeidExpr *E)
LValue EmitCXXUuidofLValue (const CXXUuidofExpr *E)
LValue EmitObjCMessageExprLValue (const ObjCMessageExpr *E)
LValue EmitObjCIvarRefLValue (const ObjCIvarRefExpr *E)
LValue EmitStmtExprLValue (const StmtExpr *E)
LValue EmitPointerToDataMemberBinaryExpr (const BinaryOperator *E)
LValue EmitObjCSelectorLValue (const ObjCSelectorExpr *E)
void EmitDeclRefExprDbgValue (const DeclRefExpr *E, const APValue &Init)
RValue EmitCall (const CGFunctionInfo &CallInfo, const CGCallee &Callee, ReturnValueSlot ReturnValue, const CallArgList &Args, llvm::CallBase **callOrInvoke, bool IsMustTail, SourceLocation Loc)
EmitCall - Generate a call of the given function, expecting the given result type, and using the given argument list which specifies both the LLVM arguments and the types they were derived from.
RValue EmitCall (const CGFunctionInfo &CallInfo, const CGCallee &Callee, ReturnValueSlot ReturnValue, const CallArgList &Args, llvm::CallBase **callOrInvoke=nullptr, bool IsMustTail=false)
RValue EmitCall (QualType FnType, const CGCallee &Callee, const CallExpr *E, ReturnValueSlot ReturnValue, llvm::Value *Chain=nullptr)
RValue EmitCallExpr (const CallExpr *E, ReturnValueSlot ReturnValue=ReturnValueSlot())
RValue EmitSimpleCallExpr (const CallExpr *E, ReturnValueSlot ReturnValue)
Emit a CallExpr without considering whether it might be a subclass.
CGCallee EmitCallee (const Expr *E)
void checkTargetFeatures (const CallExpr *E, const FunctionDecl *TargetDecl)
void checkTargetFeatures (SourceLocation Loc, const FunctionDecl *TargetDecl)
llvm::CallInst * EmitRuntimeCall (llvm::FunctionCallee callee, const Twine &name="")
llvm::CallInst * EmitRuntimeCall (llvm::FunctionCallee callee, ArrayRef< llvm::Value * > args, const Twine &name="")
llvm::CallInst * EmitNounwindRuntimeCall (llvm::FunctionCallee callee, const Twine &name="")
llvm::CallInst * EmitNounwindRuntimeCall (llvm::FunctionCallee callee, ArrayRef< Address > args, const Twine &name="")
llvm::CallInst * EmitNounwindRuntimeCall (llvm::FunctionCallee callee, ArrayRef< llvm::Value * > args, const Twine &name="")
SmallVector< llvm::OperandBundleDef, 1 > getBundlesForFunclet (llvm::Value *Callee)
llvm::CallBase * EmitCallOrInvoke (llvm::FunctionCallee Callee, ArrayRef< llvm::Value * > Args, const Twine &Name="")
Emits a call or invoke instruction to the given function, depending on the current state of the EH stack.
llvm::CallBase * EmitRuntimeCallOrInvoke (llvm::FunctionCallee callee, ArrayRef< llvm::Value * > args, const Twine &name="")
Emits a call or invoke instruction to the given runtime function.
llvm::CallBase * EmitRuntimeCallOrInvoke (llvm::FunctionCallee callee, const Twine &name="")
Emits a call or invoke instruction to the given nullary runtime function.
void EmitNoreturnRuntimeCallOrInvoke (llvm::FunctionCallee callee, ArrayRef< llvm::Value * > args)
Emits a call or invoke to the given noreturn runtime function.
CGCallee BuildAppleKextVirtualCall (const CXXMethodDecl *MD, NestedNameSpecifier *Qual, llvm::Type *Ty)
BuildAppleKextVirtualCall - This routine is to support gcc's kext ABI making indirect call to virtual functions.
CGCallee BuildAppleKextVirtualDestructorCall (const CXXDestructorDecl *DD, CXXDtorType Type, const CXXRecordDecl *RD)
BuildVirtualCall - This routine makes indirect vtable call for call to virtual destructors.
llvm::Value * getAsNaturalPointerTo (Address Addr, QualType PointeeType)
bool isPointerKnownNonNull (const Expr *E)
void defaultInitNonTrivialCStructVar (LValue Dst)
void callCStructDefaultConstructor (LValue Dst)
void callCStructDestructor (LValue Dst)
void callCStructCopyConstructor (LValue Dst, LValue Src)
void callCStructMoveConstructor (LValue Dst, LValue Src)
void callCStructCopyAssignmentOperator (LValue Dst, LValue Src)
void callCStructMoveAssignmentOperator (LValue Dst, LValue Src)
RValue EmitCXXMemberOrOperatorCall (const CXXMethodDecl *Method, const CGCallee &Callee, ReturnValueSlot ReturnValue, llvm::Value *This, llvm::Value *ImplicitParam, QualType ImplicitParamTy, const CallExpr *E, CallArgList *RtlArgs)
RValue EmitCXXDestructorCall (GlobalDecl Dtor, const CGCallee &Callee, llvm::Value *This, QualType ThisTy, llvm::Value *ImplicitParam, QualType ImplicitParamTy, const CallExpr *E)
RValue EmitCXXMemberCallExpr (const CXXMemberCallExpr *E, ReturnValueSlot ReturnValue)
RValue EmitCXXMemberOrOperatorMemberCallExpr (const CallExpr *CE, const CXXMethodDecl *MD, ReturnValueSlot ReturnValue, bool HasQualifier, NestedNameSpecifier *Qualifier, bool IsArrow, const Expr *Base)
Address EmitCXXMemberDataPointerAddress (const Expr *E, Address base, llvm::Value *memberPtr, const MemberPointerType *memberPtrType, LValueBaseInfo *BaseInfo=nullptr, TBAAAccessInfo *TBAAInfo=nullptr)
Emit the address of a field using a member data pointer.
RValue EmitCXXMemberPointerCallExpr (const CXXMemberCallExpr *E, ReturnValueSlot ReturnValue)
RValue EmitCXXOperatorMemberCallExpr (const CXXOperatorCallExpr *E, const CXXMethodDecl *MD, ReturnValueSlot ReturnValue)
RValue EmitCXXPseudoDestructorExpr (const CXXPseudoDestructorExpr *E)
RValue EmitCUDAKernelCallExpr (const CUDAKernelCallExpr *E, ReturnValueSlot ReturnValue)
RValue EmitNVPTXDevicePrintfCallExpr (const CallExpr *E)
RValue EmitAMDGPUDevicePrintfCallExpr (const CallExpr *E)
RValue EmitOpenMPDevicePrintfCallExpr (const CallExpr *E)
RValue EmitBuiltinExpr (const GlobalDecl GD, unsigned BuiltinID, const CallExpr *E, ReturnValueSlot ReturnValue)
RValue emitRotate (const CallExpr *E, bool IsRotateRight)
RValue emitBuiltinOSLogFormat (const CallExpr &E)
Emit IR for __builtin_os_log_format.
RValue EmitBuiltinIsAligned (const CallExpr *E)
Emit IR for __builtin_is_aligned.
RValue EmitBuiltinAlignTo (const CallExpr *E, bool AlignUp)
Emit IR for __builtin_align_up/__builtin_align_down.
llvm::Function * generateBuiltinOSLogHelperFunction (const analyze_os_log::OSLogBufferLayout &Layout, CharUnits BufferAlignment)
RValue EmitBlockCallExpr (const CallExpr *E, ReturnValueSlot ReturnValue)
llvm::Value * EmitTargetBuiltinExpr (unsigned BuiltinID, const CallExpr *E, ReturnValueSlot ReturnValue)
EmitTargetBuiltinExpr - Emit the given builtin call.
llvm::Value * EmitAArch64CompareBuiltinExpr (llvm::Value *Op, llvm::Type *Ty, const llvm::CmpInst::Predicate Fp, const llvm::CmpInst::Predicate Ip, const llvm::Twine &Name="")
llvm::Value * EmitARMBuiltinExpr (unsigned BuiltinID, const CallExpr *E, ReturnValueSlot ReturnValue, llvm::Triple::ArchType Arch)
llvm::Value * EmitARMMVEBuiltinExpr (unsigned BuiltinID, const CallExpr *E, ReturnValueSlot ReturnValue, llvm::Triple::ArchType Arch)
llvm::Value * EmitARMCDEBuiltinExpr (unsigned BuiltinID, const CallExpr *E, ReturnValueSlot ReturnValue, llvm::Triple::ArchType Arch)
llvm::Value * EmitCMSEClearRecord (llvm::Value *V, llvm::IntegerType *ITy, QualType RTy)
llvm::Value * EmitCMSEClearRecord (llvm::Value *V, llvm::ArrayType *ATy, QualType RTy)
llvm::Value * EmitCommonNeonBuiltinExpr (unsigned BuiltinID, unsigned LLVMIntrinsic, unsigned AltLLVMIntrinsic, const char *NameHint, unsigned Modifier, const CallExpr *E, SmallVectorImpl< llvm::Value * > &Ops, Address PtrOp0, Address PtrOp1, llvm::Triple::ArchType Arch)
llvm::Function * LookupNeonLLVMIntrinsic (unsigned IntrinsicID, unsigned Modifier, llvm::Type *ArgTy, const CallExpr *E)
llvm::Value * EmitNeonCall (llvm::Function *F, SmallVectorImpl< llvm::Value * > &O, const char *name, unsigned shift=0, bool rightshift=false)
llvm::Value * EmitNeonSplat (llvm::Value *V, llvm::Constant *Idx, const llvm::ElementCount &Count)
llvm::Value * EmitNeonSplat (llvm::Value *V, llvm::Constant *Idx)
llvm::Value * EmitNeonShiftVector (llvm::Value *V, llvm::Type *Ty, bool negateForRightShift)
llvm::Value * EmitNeonRShiftImm (llvm::Value *Vec, llvm::Value *Amt, llvm::Type *Ty, bool usgn, const char *name)
llvm::Value * vectorWrapScalar16 (llvm::Value *Op)
llvm::Type * SVEBuiltinMemEltTy (const SVETypeFlags &TypeFlags)
SVEBuiltinMemEltTy - Returns the memory element type for this memory access builtin.
SmallVector< llvm::Type *, 2 > getSVEOverloadTypes (const SVETypeFlags &TypeFlags, llvm::Type *ReturnType, ArrayRef< llvm::Value * > Ops)
llvm::Type * getEltType (const SVETypeFlags &TypeFlags)
llvm::ScalableVectorType * getSVEType (const SVETypeFlags &TypeFlags)
llvm::ScalableVectorType * getSVEPredType (const SVETypeFlags &TypeFlags)
llvm::Value * EmitSVETupleSetOrGet (const SVETypeFlags &TypeFlags, llvm::Type *ReturnType, ArrayRef< llvm::Value * > Ops)
llvm::Value * EmitSVETupleCreate (const SVETypeFlags &TypeFlags, llvm::Type *ReturnType, ArrayRef< llvm::Value * > Ops)
llvm::Value * EmitSVEAllTruePred (const SVETypeFlags &TypeFlags)
llvm::Value * EmitSVEDupX (llvm::Value *Scalar)
llvm::Value * EmitSVEDupX (llvm::Value *Scalar, llvm::Type *Ty)
llvm::Value * EmitSVEReinterpret (llvm::Value *Val, llvm::Type *Ty)
llvm::Value * EmitSVEPMull (const SVETypeFlags &TypeFlags, llvm::SmallVectorImpl< llvm::Value * > &Ops, unsigned BuiltinID)
llvm::Value * EmitSVEMovl (const SVETypeFlags &TypeFlags, llvm::ArrayRef< llvm::Value * > Ops, unsigned BuiltinID)
llvm::Value * EmitSVEPredicateCast (llvm::Value *Pred, llvm::ScalableVectorType *VTy)
llvm::Value * EmitSVEGatherLoad (const SVETypeFlags &TypeFlags, llvm::SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
llvm::Value * EmitSVEScatterStore (const SVETypeFlags &TypeFlags, llvm::SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
llvm::Value * EmitSVEMaskedLoad (const CallExpr *, llvm::Type *ReturnTy, SmallVectorImpl< llvm::Value * > &Ops, unsigned BuiltinID, bool IsZExtReturn)
llvm::Value * EmitSVEMaskedStore (const CallExpr *, SmallVectorImpl< llvm::Value * > &Ops, unsigned BuiltinID)
llvm::Value * EmitSVEPrefetchLoad (const SVETypeFlags &TypeFlags, SmallVectorImpl< llvm::Value * > &Ops, unsigned BuiltinID)
llvm::Value * EmitSVEGatherPrefetch (const SVETypeFlags &TypeFlags, SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
llvm::Value * EmitSVEStructLoad (const SVETypeFlags &TypeFlags, SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
llvm::Value * EmitSVEStructStore (const SVETypeFlags &TypeFlags, SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
llvm::Value * FormSVEBuiltinResult (llvm::Value *Call)
FormSVEBuiltinResult - Returns the struct of scalable vectors as a wider vector.
llvm::Value * EmitAArch64SVEBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitSMELd1St1 (const SVETypeFlags &TypeFlags, llvm::SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
llvm::Value * EmitSMEReadWrite (const SVETypeFlags &TypeFlags, llvm::SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
llvm::Value * EmitSMEZero (const SVETypeFlags &TypeFlags, llvm::SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
llvm::Value * EmitSMELdrStr (const SVETypeFlags &TypeFlags, llvm::SmallVectorImpl< llvm::Value * > &Ops, unsigned IntID)
void GetAArch64SVEProcessedOperands (unsigned BuiltinID, const CallExpr *E, SmallVectorImpl< llvm::Value * > &Ops, SVETypeFlags TypeFlags)
llvm::Value * EmitAArch64SMEBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitAArch64BuiltinExpr (unsigned BuiltinID, const CallExpr *E, llvm::Triple::ArchType Arch)
llvm::Value * EmitBPFBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * BuildVector (ArrayRef< llvm::Value * > Ops)
llvm::Value * EmitX86BuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitPPCBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitAMDGPUBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitHLSLBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitScalarOrConstFoldImmArg (unsigned ICEArguments, unsigned Idx, const CallExpr *E)
llvm::Value * EmitSystemZBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitNVPTXBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitWebAssemblyBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitHexagonBuiltinExpr (unsigned BuiltinID, const CallExpr *E)
llvm::Value * EmitRISCVBuiltinExpr (unsigned BuiltinID, const CallExpr *E, ReturnValueSlot ReturnValue)
void ProcessOrderScopeAMDGCN (llvm::Value *Order, llvm::Value *Scope, llvm::AtomicOrdering &AO, llvm::SyncScope::ID &SSID)
RValue EmitIntelFPGARegBuiltin (const CallExpr *E, ReturnValueSlot ReturnValue)
RValue EmitIntelFPGAMemBuiltin (const CallExpr *E)
RValue EmitIntelSYCLPtrAnnotationBuiltin (const CallExpr *E)
RValue EmitIntelSYCLAllocaBuiltin (unsigned BuiltinID, const CallExpr *E, ReturnValueSlot ReturnValue)
llvm::CallInst * MaybeEmitFPBuiltinofFD (llvm::FunctionType *IRFuncTy, const SmallVectorImpl< llvm::Value * > &IRArgs, llvm::Value *FnPtr, StringRef Name, unsigned FDBuiltinID)
llvm::Value * EmitMSVCBuiltinExpr (MSVCIntrin BuiltinID, const CallExpr *E)
llvm::Value * EmitBuiltinAvailable (const VersionTuple &Version)
llvm::Value * EmitObjCProtocolExpr (const ObjCProtocolExpr *E)
llvm::Value * EmitObjCStringLiteral (const ObjCStringLiteral *E)
Emits an instance of NSConstantString representing the object.
llvm::Value * EmitObjCBoxedExpr (const ObjCBoxedExpr *E)
EmitObjCBoxedExpr - This routine generates code to call the appropriate expression boxing method.
llvm::Value * EmitObjCArrayLiteral (const ObjCArrayLiteral *E)
llvm::Value * EmitObjCDictionaryLiteral (const ObjCDictionaryLiteral *E)
llvm::Value * EmitObjCCollectionLiteral (const Expr *E, const ObjCMethodDecl *MethodWithObjects)
llvm::Value * EmitObjCSelectorExpr (const ObjCSelectorExpr *E)
Emit a selector.
RValue EmitObjCMessageExpr (const ObjCMessageExpr *E, ReturnValueSlot Return=ReturnValueSlot())
CleanupKind getARCCleanupKind ()
Retrieves the default cleanup kind for an ARC cleanup.
void EmitARCInitWeak (Address addr, llvm::Value *value)
i8* @objc_initWeak(i8** addr, i8* value) Returns value.
void EmitARCDestroyWeak (Address addr)
void @objc_destroyWeak(i8** addr) Essentially objc_storeWeak(addr, nil).
llvm::Value * EmitARCLoadWeak (Address addr)
i8* @objc_loadWeak(i8** addr) Essentially objc_autorelease(objc_loadWeakRetained(addr)).
llvm::Value * EmitARCLoadWeakRetained (Address addr)
i8* @objc_loadWeakRetained(i8** addr)
llvm::Value * EmitARCStoreWeak (Address addr, llvm::Value *value, bool ignored)
i8* @objc_storeWeak(i8** addr, i8* value) Returns value.
void emitARCCopyAssignWeak (QualType Ty, Address DstAddr, Address SrcAddr)
void emitARCMoveAssignWeak (QualType Ty, Address DstAddr, Address SrcAddr)
void EmitARCCopyWeak (Address dst, Address src)
void @objc_copyWeak(i8** dest, i8** src) Disregards the current value in dest.
void EmitARCMoveWeak (Address dst, Address src)
void @objc_moveWeak(i8** dest, i8** src) Disregards the current value in dest.
llvm::Value * EmitARCRetainAutorelease (QualType type, llvm::Value *value)
Do a fused retain/autorelease of the given object.
llvm::Value * EmitARCRetainAutoreleaseNonBlock (llvm::Value *value)
Do a fused retain/autorelease of the given object.
llvm::Value * EmitARCStoreStrong (LValue lvalue, llvm::Value *value, bool resultIgnored)
Store into a strong object.
llvm::Value * EmitARCStoreStrongCall (Address addr, llvm::Value *value, bool resultIgnored)
Store into a strong object.
llvm::Value * EmitARCRetain (QualType type, llvm::Value *value)
Produce the code to do a retain.
llvm::Value * EmitARCRetainNonBlock (llvm::Value *value)
Retain the given object, with normal retain semantics.
llvm::Value * EmitARCRetainBlock (llvm::Value *value, bool mandatory)
Retain the given block, with _Block_copy semantics.
void EmitARCDestroyStrong (Address addr, ARCPreciseLifetime_t precise)
Destroy a __strong variable.
void EmitARCRelease (llvm::Value *value, ARCPreciseLifetime_t precise)
Release the given object.
llvm::Value * EmitARCAutorelease (llvm::Value *value)
Autorelease the given object.
llvm::Value * EmitARCAutoreleaseReturnValue (llvm::Value *value)
Autorelease the given object.
llvm::Value * EmitARCRetainAutoreleaseReturnValue (llvm::Value *value)
Do a fused retain/autorelease of the given object.
llvm::Value * EmitARCRetainAutoreleasedReturnValue (llvm::Value *value)
Retain the given object which is the result of a function call.
llvm::Value * EmitARCUnsafeClaimAutoreleasedReturnValue (llvm::Value *value)
Claim a possibly-autoreleased return value at +0.
llvm::Value * EmitObjCAutorelease (llvm::Value *value, llvm::Type *returnType)
Autorelease the given object.
llvm::Value * EmitObjCRetainNonBlock (llvm::Value *value, llvm::Type *returnType)
Retain the given object, with normal retain semantics.
void EmitObjCRelease (llvm::Value *value, ARCPreciseLifetime_t precise)
Release the given object.
std::pair< LValue, llvm::Value * > EmitARCStoreAutoreleasing (const BinaryOperator *e)
std::pair< LValue, llvm::Value * > EmitARCStoreStrong (const BinaryOperator *e, bool ignored)
std::pair< LValue, llvm::Value * > EmitARCStoreUnsafeUnretained (const BinaryOperator *e, bool ignored)
llvm::Value * EmitObjCAlloc (llvm::Value *value, llvm::Type *returnType)
Allocate the given objc object.
llvm::Value * EmitObjCAllocWithZone (llvm::Value *value, llvm::Type *returnType)
Allocate the given objc object.
llvm::Value * EmitObjCAllocInit (llvm::Value *value, llvm::Type *resultType)
llvm::Value * EmitObjCThrowOperand (const Expr *expr)
llvm::Value * EmitObjCConsumeObject (QualType T, llvm::Value *Ptr)
Produce the code for a CK_ARCConsumeObject.
llvm::Value * EmitObjCExtendObjectLifetime (QualType T, llvm::Value *Ptr)
llvm::Value * EmitARCExtendBlockObject (const Expr *expr)
llvm::Value * EmitARCReclaimReturnedObject (const Expr *e, bool allowUnsafeClaim)
llvm::Value * EmitARCRetainScalarExpr (const Expr *expr)
EmitARCRetainScalarExpr - Semantically equivalent to EmitARCRetainObject(e->getType(), EmitScalarExpr(e)), but making a best-effort attempt to peephole expressions that naturally produce retained objects.
llvm::Value * EmitARCRetainAutoreleaseScalarExpr (const Expr *expr)
llvm::Value * EmitARCUnsafeUnretainedScalarExpr (const Expr *expr)
EmitARCUnsafeUnretainedScalarExpr - Semantically equivalent to immediately releasing the resut of EmitARCRetainScalarExpr, but avoiding any spurious retains, including by performing reclaims with objc_unsafeClaimAutoreleasedReturnValue.
void EmitARCIntrinsicUse (ArrayRef< llvm::Value * > values)
Given a number of pointers, inform the optimizer that they're being intrinsically used up until this point in the program.
void EmitARCNoopIntrinsicUse (ArrayRef< llvm::Value * > values)
Emit a call to "clang.arc.noop.use", which consumes the result of a call that has operand bundle "clang.arc.attachedcall".
void EmitObjCAutoreleasePoolPop (llvm::Value *Ptr)
Produce the code to do a primitive release.
llvm::Value * EmitObjCAutoreleasePoolPush ()
Produce the code to do a objc_autoreleasepool_push.
llvm::Value * EmitObjCMRRAutoreleasePoolPush ()
Produce the code to do an MRR version objc_autoreleasepool_push.
void EmitObjCAutoreleasePoolCleanup (llvm::Value *Ptr)
void EmitObjCMRRAutoreleasePoolPop (llvm::Value *Ptr)
Produce the code to do a primitive release.
RValue EmitReferenceBindingToExpr (const Expr *E)
Emits a reference binding to the passed in expression.
llvm::Value * EmitScalarExpr (const Expr *E, bool IgnoreResultAssign=false)
EmitScalarExpr - Emit the computation of the specified expression of LLVM scalar type, returning the result.
llvm::Value * EmitScalarConversion (llvm::Value *Src, QualType SrcTy, QualType DstTy, SourceLocation Loc)
Emit a conversion from the specified type to the specified destination type, both of which are LLVM scalar types.
llvm::Value * EmitComplexToScalarConversion (ComplexPairTy Src, QualType SrcTy, QualType DstTy, SourceLocation Loc)
Emit a conversion from the specified complex type to the specified destination type, where the destination type is an LLVM scalar type.
void EmitAggExpr (const Expr *E, AggValueSlot AS)
EmitAggExpr - Emit the computation of the specified expression of aggregate type.
LValue EmitAggExprToLValue (const Expr *E)
EmitAggExprToLValue - Emit the computation of the specified expression of aggregate type into a temporary LValue.
void EmitAggregateStore (llvm::Value *Val, Address Dest, bool DestIsVolatile)
Build all the stores needed to initialize an aggregate at Dest with the value Val.
void EmitExtendGCLifetime (llvm::Value *object)
EmitExtendGCLifetime - Given a pointer to an Objective-C object, make sure it survives garbage collection until this point.
ComplexPairTy EmitComplexExpr (const Expr *E, bool IgnoreReal=false, bool IgnoreImag=false)
EmitComplexExpr - Emit the computation of the specified expression of complex type, returning the result.
void EmitComplexExprIntoLValue (const Expr *E, LValue dest, bool isInit)
EmitComplexExprIntoLValue - Emit the given expression of complex type and place its result into the specified l-value.
void EmitStoreOfComplex (ComplexPairTy V, LValue dest, bool isInit)
EmitStoreOfComplex - Store a complex number into the specified l-value.
ComplexPairTy EmitLoadOfComplex (LValue src, SourceLocation loc)
EmitLoadOfComplex - Load a complex number from the specified l-value.
ComplexPairTy EmitPromotedComplexExpr (const Expr *E, QualType PromotionType)
llvm::Value * EmitPromotedScalarExpr (const Expr *E, QualType PromotionType)
ComplexPairTy EmitPromotedValue (ComplexPairTy result, QualType PromotionType)
ComplexPairTy EmitUnPromotedValue (ComplexPairTy result, QualType PromotionType)
Address emitAddrOfRealComponent (Address complex, QualType complexType)
Address emitAddrOfImagComponent (Address complex, QualType complexType)
llvm::GlobalVariable * AddInitializerToStaticVarDecl (const VarDecl &D, llvm::GlobalVariable *GV)
AddInitializerToStaticVarDecl - Add the initializer for 'D' to the global variable that has already been created for it.
void EmitInvariantStart (llvm::Constant *Addr, CharUnits Size)
void EmitCXXGlobalVarDeclInit (const VarDecl &D, llvm::GlobalVariable *GV, bool PerformInit)
EmitCXXGlobalVarDeclInit - Create the initializer for a C++ variable with global storage.
llvm::Function * createAtExitStub (const VarDecl &VD, llvm::FunctionCallee Dtor, llvm::Constant *Addr)
Create a stub function, suitable for being passed to atexit, which passes the given address to the given destructor function.
llvm::Function * createTLSAtExitStub (const VarDecl &VD, llvm::FunctionCallee Dtor, llvm::Constant *Addr, llvm::FunctionCallee &AtExit)
Create a stub function, suitable for being passed to __pt_atexit_np, which passes the given address to the given destructor function.
void registerGlobalDtorWithAtExit (const VarDecl &D, llvm::FunctionCallee fn, llvm::Constant *addr)
Call atexit() with a function that passes the given argument to the given function.
void registerGlobalDtorWithLLVM (const VarDecl &D, llvm::FunctionCallee fn, llvm::Constant *addr)
Registers the dtor using 'llvm.global_dtors' for platforms that do not support an 'atexit()' function.
void registerGlobalDtorWithAtExit (llvm::Constant *dtorStub)
Call atexit() with function dtorStub.
llvm::Value * unregisterGlobalDtorWithUnAtExit (llvm::Constant *dtorStub)
Call unatexit() with function dtorStub.
void EmitCXXGuardedInit (const VarDecl &D, llvm::GlobalVariable *DeclPtr, bool PerformInit)
Emit code in this function to perform a guarded variable initialization.
void EmitCXXGuardedInitBranch (llvm::Value *NeedsInit, llvm::BasicBlock *InitBlock, llvm::BasicBlock *NoInitBlock, GuardKind Kind, const VarDecl *D)
Emit a branch to select whether or not to perform guarded initialization.
void GenerateCXXGlobalInitFunc (llvm::Function *Fn, ArrayRef< llvm::Function * > CXXThreadLocals, ConstantAddress Guard=ConstantAddress::invalid())
GenerateCXXGlobalInitFunc - Generates code for initializing global variables.
void GenerateCXXGlobalCleanUpFunc (llvm::Function *Fn, ArrayRef< std::tuple< llvm::FunctionType *, llvm::WeakTrackingVH, llvm::Constant * >> DtorsOrStermFinalizers)
GenerateCXXGlobalCleanUpFunc - Generates code for cleaning up global variables.
void GenerateCXXGlobalVarDeclInitFunc (llvm::Function *Fn, const VarDecl *D, llvm::GlobalVariable *Addr, bool PerformInit)
Emit the code necessary to initialize the given global variable.
void EmitCXXConstructExpr (const CXXConstructExpr *E, AggValueSlot Dest)
void EmitSynthesizedCXXCopyCtor (Address Dest, Address Src, const Expr *Exp)
void EmitCXXThrowExpr (const CXXThrowExpr *E, bool KeepInsertionPoint=true)
RValue EmitAtomicExpr (AtomicExpr *E)
llvm::Value * EmitAnnotationCall (llvm::Function *AnnotationFn, llvm::Value *AnnotatedVal, StringRef AnnotationStr, SourceLocation Location, const AnnotateAttr *Attr=nullptr)
Emit an annotation call (intrinsic).
void EmitVarAnnotations (const VarDecl *D, llvm::Value *V)
Emit local annotations for the local variable V, declared by D.
Address EmitFieldAnnotations (const FieldDecl *D, Address V)
Emit field annotations for the given field & value.
llvm::Value * EmitSYCLAnnotationCall (llvm::Function *AnnotationFn, llvm::Value *AnnotatedVal, SourceLocation Location, const SYCLAddIRAnnotationsMemberAttr *Attr)
Emit a "sycl-properties" annotation call (intrinsic).
llvm::Value * EmitSYCLAnnotationCall (llvm::Function *AnnotationFn, llvm::Value *AnnotatedVal, SourceLocation Location, llvm::SmallVectorImpl< std::pair< std::string, std::string >> &Pair)
Address EmitFieldSYCLAnnotations (const FieldDecl *D, Address V)
Emit sycl field annotations for given field & value.
Address EmitIntelFPGAFieldAnnotations (const FieldDecl *D, Address V, StringRef AnnotStr)
Emit Intel FPGA field annotations for the given field and value.
Address EmitIntelFPGAFieldAnnotations (SourceLocation Location, Address V, StringRef AnnotStr)
bool ConstantFoldsToSimpleInteger (const Expr *Cond, bool &Result, bool AllowLabels=false)
ConstantFoldsToSimpleInteger - If the specified expression does not fold to a constant, or if it does but contains a label, return false.
bool ConstantFoldsToSimpleInteger (const Expr *Cond, llvm::APSInt &Result, bool AllowLabels=false)
ConstantFoldsToSimpleInteger - If the specified expression does not fold to a constant, or if it does but contains a label, return false.
void EmitBranchToCounterBlock (const Expr *Cond, BinaryOperator::Opcode LOp, llvm::BasicBlock *TrueBlock, llvm::BasicBlock *FalseBlock, uint64_t TrueCount=0, Stmt::Likelihood LH=Stmt::LH_None, const Expr *CntrIdx=nullptr)
EmitBranchToCounterBlock - Emit a conditional branch to a new block that increments a profile counter based on the semantics of the given logical operator opcode.
void EmitBranchOnBoolExpr (const Expr *Cond, llvm::BasicBlock *TrueBlock, llvm::BasicBlock *FalseBlock, uint64_t TrueCount, Stmt::Likelihood LH=Stmt::LH_None, const Expr *ConditionalOp=nullptr)
EmitBranchOnBoolExpr - Emit a branch on a boolean condition (e.g.
void EmitNullabilityCheck (LValue LHS, llvm::Value *RHS, SourceLocation Loc)
Given an assignment *LHS = RHS, emit a test that checks if RHS is nonnull, if LHS is marked _Nonnull.
llvm::Value * EmitCheckedInBoundsGEP (llvm::Type *ElemTy, llvm::Value *Ptr, ArrayRef< llvm::Value * > IdxList, bool SignedIndices, bool IsSubtraction, SourceLocation Loc, const Twine &Name="")
Same as IRBuilder::CreateInBoundsGEP, but additionally emits a check to detect undefined behavior when the pointer overflow sanitizer is enabled.
Address EmitCheckedInBoundsGEP (Address Addr, ArrayRef< llvm::Value * > IdxList, llvm::Type *elementType, bool SignedIndices, bool IsSubtraction, SourceLocation Loc, CharUnits Align, const Twine &Name="")
llvm::Value * EmitCheckedArgForBuiltin (const Expr *E, BuiltinCheckKind Kind)
Emits an argument for a call to a builtin.
llvm::Constant * EmitCheckTypeDescriptor (QualType T)
Emit a description of a type in a format suitable for passing to a runtime sanitizer handler.
llvm::Value * EmitCheckValue (llvm::Value *V)
Convert a value into a format suitable for passing to a runtime sanitizer handler.
llvm::Constant * EmitCheckSourceLocation (SourceLocation Loc)
Emit a description of a source location in a format suitable for passing to a runtime sanitizer handler.
void EmitKCFIOperandBundle (const CGCallee &Callee, SmallVectorImpl< llvm::OperandBundleDef > &Bundles)
void EmitCheck (ArrayRef< std::pair< llvm::Value *, SanitizerMask >> Checked, SanitizerHandler Check, ArrayRef< llvm::Constant * > StaticArgs, ArrayRef< llvm::Value * > DynamicArgs)
Create a basic block that will either trap or call a handler function in the UBSan runtime with the provided arguments, and create a conditional branch to it.
void EmitCfiSlowPathCheck (SanitizerMask Kind, llvm::Value *Cond, llvm::ConstantInt *TypeId, llvm::Value *Ptr, ArrayRef< llvm::Constant * > StaticArgs)
Emit a slow path cross-DSO CFI check which calls __cfi_slowpath if Cond if false.
void EmitUnreachable (SourceLocation Loc)
Emit a reached-unreachable diagnostic if Loc is valid and runtime checking is enabled.
void EmitTrapCheck (llvm::Value *Checked, SanitizerHandler CheckHandlerID)
Create a basic block that will call the trap intrinsic, and emit a conditional branch to it, for the -ftrapv checks.
llvm::CallInst * EmitTrapCall (llvm::Intrinsic::ID IntrID)
Emit a call to trap or debugtrap and attach function attribute "trap-func-name" if specified.
void EmitCfiCheckStub ()
Emit a stub for the cross-DSO CFI check function.
void EmitCfiCheckFail ()
Emit a cross-DSO CFI failure handling function.
void EmitNonNullArgCheck (RValue RV, QualType ArgType, SourceLocation ArgLoc, AbstractCallee AC, unsigned ParmNum)
Create a check for a function parameter that may potentially be declared as non-null.
void EmitNonNullArgCheck (Address Addr, QualType ArgType, SourceLocation ArgLoc, AbstractCallee AC, unsigned ParmNum)
void EmitCallArg (CallArgList &args, const Expr *E, QualType ArgType)
EmitCallArg - Emit a single call argument.
void EmitDelegateCallArg (CallArgList &args, const VarDecl *param, SourceLocation loc)
EmitDelegateCallArg - We are performing a delegate call; that is, the current function is delegating to another one.
void SetFPAccuracy (llvm::Value *Val, float Accuracy)
SetFPAccuracy - Set the minimum required accuracy of the given floating point operation, expressed as the maximum relative error in ulp.
void SetSqrtFPAccuracy (llvm::Value *Val)
Set the minimum required accuracy of the given sqrt operation based on CodeGenOpts.
void SetDivFPAccuracy (llvm::Value *Val)
Set the minimum required accuracy of the given sqrt operation based on CodeGenOpts.
void SetFastMathFlags (FPOptions FPFeatures)
Set the codegen fast-math flags.
llvm::Value * emitBoolVecConversion (llvm::Value *SrcVec, unsigned NumElementsDst, const llvm::Twine &Name="")
llvm::CallBase * addControlledConvergenceToken (llvm::CallBase *Input)
void EmitCallArgs (CallArgList &Args, PrototypeWrapper Prototype, llvm::iterator_range< CallExpr::const_arg_iterator > ArgRange, AbstractCallee AC=AbstractCallee(), unsigned ParamsToSkip=0, EvaluationOrder Order=EvaluationOrder::Default)
EmitCallArgs - Emit call arguments for a function.
Address EmitPointerWithAlignment (const Expr *Addr, LValueBaseInfo *BaseInfo=nullptr, TBAAAccessInfo *TBAAInfo=nullptr, KnownNonNull_t IsKnownNonNull=NotKnownNonNull)
EmitPointerWithAlignment - Given an expression with a pointer type, emit the value and compute our best estimate of the alignment of the pointee.
llvm::Value * LoadPassedObjectSize (const Expr *E, QualType EltTy)
If E references a parameter with pass_object_size info or a constant array size modifier, emit the object size divided by the size of EltTy.
void EmitSanitizerStatReport (llvm::SanitizerStatKind SSK)
void EmitMultiVersionResolver (llvm::Function *Resolver, ArrayRef< MultiVersionResolverOption > Options)
void EmitX86MultiVersionResolver (llvm::Function *Resolver, ArrayRef< MultiVersionResolverOption > Options)
void EmitAArch64MultiVersionResolver (llvm::Function *Resolver, ArrayRef< MultiVersionResolverOption > Options)
Public Member Functions inherited from clang::CodeGen::CodeGenTypeCache
CharUnits getIntSize () const
CharUnits getIntAlign () const
CharUnits getSizeSize () const
CharUnits getSizeAlign () const
CharUnits getPointerSize () const
CharUnits getPointerAlign () const
llvm::CallingConv::ID getRuntimeCC () const
LangAS getASTAllocaAddressSpace () const
Static Public Member Functions
static bool cxxDestructorCanThrow (QualType T)
Check if T is a C++ class that has a destructor that can throw.
static bool IsConstructorDelegationValid (const CXXConstructorDecl *Ctor)
Checks whether the given constructor is a valid subject for the complete-to-base constructor delegation optimization, i.e.
static TypeEvaluationKind getEvaluationKind (QualType T)
getEvaluationKind - Return the TypeEvaluationKind of QualType T.
static bool hasScalarEvaluationKind (QualType T)
static bool hasAggregateEvaluationKind (QualType T)
static unsigned getAccessedFieldNo (unsigned Idx, const llvm::Constant *Elts)
getAccessedFieldNo - Given an encoded value and a result number, return the input field number being accessed.
static bool IsWrappedCXXThis (const Expr *E)
Check if E is a C++ "this" pointer wrapped in value-preserving casts.
static bool ShouldNullCheckClassCastValue (const CastExpr *Cast)
static bool isNullPointerAllowed (TypeCheckKind TCK)
Determine whether the pointer type check TCK permits null pointers.
static bool isVptrCheckRequired (TypeCheckKind TCK, QualType Ty)
Determine whether the pointer type check TCK requires a vptr check.
static void EmitOMPTargetDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetDirective &S)
Emit device code for the target directive.
static void EmitOMPTargetParallelDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetParallelDirective &S)
static void EmitOMPTargetParallelForDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetParallelForDirective &S)
Emit device code for the target parallel for directive.
static void EmitOMPTargetParallelForSimdDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetParallelForSimdDirective &S)
Emit device code for the target parallel for simd directive.
static void EmitOMPTargetTeamsDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetTeamsDirective &S)
Emit device code for the target teams directive.
static void EmitOMPTargetTeamsDistributeDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetTeamsDistributeDirective &S)
Emit device code for the target teams distribute directive.
static void EmitOMPTargetTeamsDistributeSimdDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetTeamsDistributeSimdDirective &S)
Emit device code for the target teams distribute simd directive.
static void EmitOMPTargetSimdDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetSimdDirective &S)
Emit device code for the target simd directive.
static void EmitOMPTargetTeamsDistributeParallelForSimdDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetTeamsDistributeParallelForSimdDirective &S)
Emit device code for the target teams distribute parallel for simd directive.
static void EmitOMPTargetTeamsGenericLoopDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetTeamsGenericLoopDirective &S)
Emit device code for the target teams loop directive.
static void EmitOMPTargetParallelGenericLoopDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetParallelGenericLoopDirective &S)
Emit device code for the target parallel loop directive.
static void EmitOMPTargetTeamsDistributeParallelForDeviceFunction (CodeGenModule &CGM, StringRef ParentName, const OMPTargetTeamsDistributeParallelForDirective &S)
static std::string getNonTrivialCopyConstructorStr (QualType QT, CharUnits Alignment, bool IsVolatile, ASTContext &Ctx)
static std::string getNonTrivialDestructorStr (QualType QT, CharUnits Alignment, bool IsVolatile, ASTContext &Ctx)
static bool ContainsLabel (const Stmt *S, bool IgnoreCaseStmts=false)
ContainsLabel - Return true if the statement contains a label in it.
static bool containsBreak (const Stmt *S)
containsBreak - Return true if the statement contains a break out of it.
static bool mightAddDeclToScope (const Stmt *S)
Determine if the given statement might introduce a declaration into the current scope, by being a (possibly-labelled) DeclStmt.
static const Expr * stripCond (const Expr *C)
Ignore parentheses and logical-NOT to track conditions consistently.
static bool isInstrumentedCondition (const Expr *C)
isInstrumentedCondition - Determine whether the given condition is an instrumentable condition (i.e.
Public Attributes
CodeGenModule & CGM
const TargetInfo & Target
CodeGenFunction * ParentCGF = nullptr
LoopInfoStack LoopStack
CGBuilderTy Builder
VarBypassDetector Bypasses
SmallVector< llvm::CanonicalLoopInfo *, 4 > OMPLoopNestStack
List of recently emitted OMPCanonicalLoops.
SmallVector< const BinaryOperator *, 16 > MCDCLogOpStack
Stack to track the Logical Operator recursion nest for MC/DC.
int ExpectedOMPLoopDepth = 0
Number of nested loop to be consumed by the last surrounding loop-associated directive.
const Decl * CurFuncDecl = nullptr
CurFuncDecl - Holds the Decl for the current outermost non-closure context.
const Decl * CurCodeDecl = nullptr
CurCodeDecl - This is the inner-most code context, which includes blocks.
const CGFunctionInfo * CurFnInfo = nullptr
QualType FnRetTy
llvm::Function * CurFn = nullptr
llvm::SmallVector< const ParmVarDecl *, 4 > FnArgs
Save Parameter Decl for coroutine.
CGCoroInfo CurCoro
AwaitSuspendWrapperInfo CurAwaitSuspendWrapper
GlobalDecl CurGD
CurGD - The GlobalDecl for the current function being compiled.
EHScopeStack::stable_iterator PrologueCleanupDepth
PrologueCleanupDepth - The cleanup depth enclosing all the cleanups associated with the parameters.
JumpDest ReturnBlock
ReturnBlock - Unified return block.
Address ReturnValue = Address::invalid()
ReturnValue - The temporary alloca to hold the return value.
Address ReturnValuePointer = Address::invalid()
ReturnValuePointer - The temporary alloca to hold a pointer to sret.
const Expr * RetExpr = nullptr
If a return statement is being visited, this holds the return statment's result expression.
llvm::AssertingVH< llvm::Instruction > AllocaInsertPt
AllocaInsertPoint - This is an instruction in the entry block before which we prefer to insert allocas.
CGCapturedStmtInfo * CapturedStmtInfo = nullptr
SanitizerSet SanOpts
Sanitizers enabled for this function.
bool IsSanitizerScope = false
True if CodeGen currently emits code implementing sanitizer checks.
bool CurFuncIsThunk = false
In C++, whether we are code generating a thunk.
bool AutoreleaseResult = false
In ARC, whether we should autorelease the return value.
bool SawAsmBlock = false
Whether we processed a Microsoft-style asm block during CodeGen.
GlobalDecl CurSEHParent
bool IsOutlinedSEHHelper = false
True if the current function is an outlined SEH helper.
bool IsInPreservedAIRegion = false
True if CodeGen currently emits code inside presereved access index region.
bool InNoMergeAttributedStmt = false
True if the current statement has nomerge attribute.
bool InNoInlineAttributedStmt = false
True if the current statement has noinline attribute.
bool InAlwaysInlineAttributedStmt = false
True if the current statement has always_inline attribute.
const CallExpr * MustTailCall = nullptr
const CodeGen::CGBlockInfo * BlockInfo = nullptr
llvm::Value * BlockPointer = nullptr
llvm::DenseMap< const ValueDecl *, FieldDecl * > LambdaCaptureFields
FieldDecl * LambdaThisCaptureField = nullptr
llvm::DenseMap< const VarDecl *, llvm::Value * > NRVOFlags
A mapping from NRVO variables to the flags used to indicate when the NRVO has been applied to this variable.
EHScopeStack EHStack
llvm::SmallVector< char, 256 > LifetimeExtendedCleanupStack
llvm::SmallVector< const JumpDest *, 2 > SEHTryEpilogueStack
llvm::Instruction * CurrentFuncletPad = nullptr
RawAddress NormalCleanupDest = RawAddress::invalid()
i32s containing the indexes of the cleanup destinations.
unsigned NextCleanupDestIndex = 1
llvm::BasicBlock * EHResumeBlock = nullptr
EHResumeBlock - Unified block containing a call to llvm.eh.resume.
llvm::Value * ExceptionSlot = nullptr
The exception slot.
llvm::AllocaInst * EHSelectorSlot = nullptr
The selector slot.
SmallVector< Address, 1 > SEHCodeSlotStack
A stack of exception code slots.
llvm::Value * SEHInfo = nullptr
Value returned by __exception_info intrinsic.
const OMPExecutableDirective * OMPParentLoopDirectiveForScan = nullptr
Parent loop-based directive for scan directive.
llvm::BasicBlock * OMPBeforeScanBlock = nullptr
llvm::BasicBlock * OMPAfterScanBlock = nullptr
llvm::BasicBlock * OMPScanExitBlock = nullptr
llvm::BasicBlock * OMPScanDispatch = nullptr
bool OMPFirstScanLoop = false
FPOptions CurFPFeatures
SmallVector< llvm::Value *, 8 > ObjCEHValueStack
ObjCEHValueStack - Stack of Objective-C exception values, used for rethrows.
EHScopeStack::stable_iterator CurrentCleanupScopeDepth
CurrentSourceLocExprScope CurSourceLocExprScope
Source location information about the default argument or member initializer expression we're evaluating, if any.
Public Attributes inherited from clang::CodeGen::CodeGenTypeCache
llvm::Type * VoidTy
void
llvm::IntegerType * Int8Ty
i8, i16, i32, and i64
llvm::IntegerType * Int16Ty
llvm::IntegerType * Int32Ty
llvm::IntegerType * Int64Ty
llvm::Type * HalfTy
half, bfloat, float, double
llvm::Type * BFloatTy
llvm::Type * FloatTy
llvm::Type * DoubleTy
llvm::IntegerType * IntTy
int
llvm::IntegerType * CharTy
char
union {
llvm::IntegerType * IntPtrTy
llvm::IntegerType * SizeTy
llvm::IntegerType * PtrDiffTy
};
intptr_t, size_t, and ptrdiff_t, which we assume are the same size.
union {
llvm::PointerType * UnqualPtrTy
llvm::PointerType * VoidPtrTy
llvm::PointerType * Int8PtrTy
llvm::PointerType * VoidPtrPtrTy
llvm::PointerType * Int8PtrPtrTy
};
void*, void** in address space 0
union {
llvm::PointerType * AllocaVoidPtrTy
llvm::PointerType * AllocaInt8PtrTy
};
void* in alloca address space
llvm::PointerType * DefaultInt8PtrTy
void* in target address space
union {
llvm::PointerType * GlobalsVoidPtrTy
llvm::PointerType * GlobalsInt8PtrTy
};
void* in default globals address space
llvm::PointerType * ConstGlobalsPtrTy
void* in the address space for constant globals
union {
unsigned char IntSizeInBytes
unsigned char IntAlignInBytes
};
The size and alignment of the builtin C type 'int'.
unsigned char PointerWidthInBits
The width of a pointer into the generic address space.
union {
unsigned char PointerAlignInBytes
unsigned char PointerSizeInBytes
};
The size and alignment of a pointer into the generic address space.
union {
unsigned char SizeSizeInBytes
unsigned char SizeAlignInBytes
};
The size and alignment of size_t.
LangAS ASTAllocaAddressSpace
llvm::CallingConv::ID RuntimeCC
Static Public Attributes
static Destroyer destroyCXXObject
static Destroyer destroyARCStrongImprecise
static Destroyer destroyARCStrongPrecise
static Destroyer destroyARCWeak
static Destroyer emitARCIntrinsicUse
static Destroyer destroyNonTrivialCStruct
Friends
class CGCXXABI
Detailed Description
CodeGenFunction - This class organizes the per-function state that is used while generating LLVM code.
Definition at line 256 of file CodeGenFunction.h.
Member Typedef Documentation
CodeGenDispatchBoundsTy
typedef llvm::function_ref<std::pair<llvm::Value *, llvm::Value *> CodeGenFunction &, const OMPExecutableDirective &S, Address LB, Address UB)> clang::CodeGen::CodeGenFunction::CodeGenDispatchBoundsTy
Definition at line 338 of file CodeGenFunction.h.
CodeGenLoopBoundsTy
typedef llvm::function_ref<std::pair<LValue, LValue> CodeGenFunction &, const OMPExecutableDirective &S)> clang::CodeGen::CodeGenFunction::CodeGenLoopBoundsTy
Definition at line 332 of file CodeGenFunction.h.
CodeGenLoopTy
typedef llvm::function_ref<void(CodeGenFunction &, const OMPLoopDirective &, JumpDest)> clang::CodeGen::CodeGenFunction::CodeGenLoopTy
Definition at line 324 of file CodeGenFunction.h.
CodeGenOrderedTy
typedef llvm::function_ref<void(CodeGenFunction &, SourceLocation, const unsigned, const bool)> clang::CodeGen::CodeGenFunction::CodeGenOrderedTy
Definition at line 327 of file CodeGenFunction.h.
ComplexPairTy
typedef std::pair<llvm::Value *, llvm::Value *> clang::CodeGen::CodeGenFunction::ComplexPairTy
Definition at line 292 of file CodeGenFunction.h.
DeclMapTy
typedef llvm::DenseMap<const Decl *, Address> clang::CodeGen::CodeGenFunction::DeclMapTy
Definition at line 1038 of file CodeGenFunction.h.
Destroyer
typedef void clang::CodeGen::CodeGenFunction::Destroyer(CodeGenFunction &CGF, Address addr, QualType ty)
Definition at line 2166 of file CodeGenFunction.h.
SourceLocExprScopeGuard
using clang::CodeGen::CodeGenFunction::SourceLocExprScopeGuard = CurrentSourceLocExprScope::SourceLocExprScopeGuard
Definition at line 1724 of file CodeGenFunction.h.
SpecialInitFn
typedef void clang::CodeGen::CodeGenFunction::SpecialInitFn(CodeGenFunction &Init, const VarDecl &D, llvm::Value *Address)
Definition at line 3274 of file CodeGenFunction.h.
TaskGenTy
typedef const llvm::function_ref<void(CodeGenFunction & , llvm::Function * , const OMPTaskDataTy &)> clang::CodeGen::CodeGenFunction::TaskGenTy
Definition at line 3722 of file CodeGenFunction.h.
VisitedVirtualBasesSetTy
typedef llvm::SmallPtrSet<const CXXRecordDecl *, 4> clang::CodeGen::CodeGenFunction::VisitedVirtualBasesSetTy
Definition at line 2419 of file CodeGenFunction.h.
VPtrsVector
typedef llvm::SmallVector<VPtr, 4> clang::CodeGen::CodeGenFunction::VPtrsVector
Definition at line 2417 of file CodeGenFunction.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
An enumeration which makes it easier to specify whether or not an operation is a subtraction.
Enumerator
NotSubtraction
IsSubtraction
Definition at line 4948 of file CodeGenFunction.h.
BuiltinCheckKind
enum clang::CodeGen::CodeGenFunction::BuiltinCheckKind
Specifies which type of sanitizer check to apply when handling a particular builtin.
Enumerator
BCK_CTZPassedZero
BCK_CLZPassedZero
Definition at line 4969 of file CodeGenFunction.h.
CFITypeCheckKind
enum clang::CodeGen::CodeGenFunction::CFITypeCheckKind
Enumerator
CFITCK_VCall
CFITCK_NVCall
CFITCK_DerivedCast
CFITCK_UnrelatedCast
CFITCK_ICall
CFITCK_NVMFCall
CFITCK_VMFCall
Definition at line 2435 of file CodeGenFunction.h.
EvaluationOrder
enum clang::CodeGen::CodeGenFunction::EvaluationOrder strong
Enumerator
Default
! No language constraints on evaluation order.
ForceLeftToRight
! Language semantics require left-to-right evaluation.
ForceRightToLeft
! Language semantics require right-to-left evaluation.
Definition at line 5144 of file CodeGenFunction.h.
GuardKind
enum clang::CodeGen::CodeGenFunction::GuardKind strong
Enumerator
VariableGuard
TlsGuard
Definition at line 4808 of file CodeGenFunction.h.
TypeCheckKind
enum clang::CodeGen::CodeGenFunction::TypeCheckKind
Situations in which we might emit a check for the suitability of a pointer or glvalue.
Needs to be kept in sync with ubsan_handlers.cpp in compiler-rt.
Enumerator
TCK_Load
Checking the operand of a load. Must be suitably sized and aligned.
TCK_Store
Checking the destination of a store. Must be suitably sized and aligned.
TCK_ReferenceBinding
Checking the bound value in a reference binding.
Must be suitably sized and aligned, but is not required to refer to an object (until the reference is used), per core issue 453.
TCK_MemberAccess
Checking the object expression in a non-static data member access.
Must be an object within its lifetime.
TCK_MemberCall
Checking the 'this' pointer for a call to a non-static member function.
Must be an object within its lifetime.
TCK_ConstructorCall
Checking the 'this' pointer for a constructor call.
TCK_DowncastPointer
Checking the operand of a static_cast to a derived pointer type.
Must be null or an object within its lifetime.
TCK_DowncastReference
Checking the operand of a static_cast to a derived reference type.
Must be an object within its lifetime.
TCK_Upcast
Checking the operand of a cast to a base object.
Must be suitably sized and aligned.
TCK_UpcastToVirtualBase
Checking the operand of a cast to a virtual base object.
Must be an object within its lifetime.
TCK_NonnullAssign
Checking the value assigned to a _Nonnull pointer. Must not be null.
TCK_DynamicOperation
Checking the operand of a dynamic_cast or a typeid expression.
Must be null or an object within its lifetime.
Definition at line 3147 of file CodeGenFunction.h.
Constructor & Destructor Documentation
CodeGenFunction()
CodeGenFunction::CodeGenFunction (CodeGenModule & cgm, bool suppressNewContext = false)
Definition at line 79 of file CodeGenFunction.cpp.
~CodeGenFunction()
CodeGenFunction::~CodeGenFunction ()
Definition at line 94 of file CodeGenFunction.cpp.
References CGM, CurFn, clang::CodeGen::CGOpenMPRuntime::functionFinished(), getLangOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CGOpenMPRuntime::getOMPBuilder(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and LifetimeExtendedCleanupStack.
Member Function Documentation
ActivateCleanupBlock()
void CodeGenFunction::ActivateCleanupBlock (EHScopeStack::stable_iterator Cleanup, llvm::Instruction * DominatingIP)
ActivateCleanupBlock - Activates an initially-inactive cleanup.
Activate a cleanup that was created in an inactivated state.
Cannot be used to resurrect a deactivated cleanup.
Parameters
DominatingIP - An instruction which is known to dominate the current IP (if set) and which lies along all paths of execution between the current IP and the the point at which the cleanup comes into scope.
Definition at line 1254 of file CGCleanup.cpp.
References ForActivation, and SetupCleanupBlockActivation().
addControlledConvergenceToken()
llvm::CallBase * CodeGenFunction::addControlledConvergenceToken (llvm::CallBase * Input)
Definition at line 1292 of file CGBuiltin.cpp.
Referenced by EmitCall().
AddInitializerToStaticVarDecl()
llvm::GlobalVariable * CodeGenFunction::AddInitializerToStaticVarDecl (const VarDecl & D, llvm::GlobalVariable * GV)
AddInitializerToStaticVarDecl - Add the initializer for 'D' to the global variable that has already been created for it.
If the initializer has a different type than GV does, this may free GV and return a different one. Otherwise it just returns GV.
Definition at line 349 of file CGDecl.cpp.
References CGM, clang::CPlusPlus, clang::QualType::DK_cxx_destructor, EmitCXXGlobalVarDeclInit(), EmitCXXGuardedInit(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::ConstantEmitter::finalize(), clang::CharUnits::fromQuantity(), clang::Decl::getAttr(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::VarDecl::getFlexibleArrayInitChars(), clang::VarDecl::getInit(), getLangOpts(), clang::CodeGen::CodeGenModule::getModule(), clang::ValueDecl::getType(), clang::ASTContext::getTypeSizeInChars(), clang::VarDecl::hasFlexibleArrayInit(), HaveInsertPoint(), clang::QualType::isConstantStorage(), clang::VarDecl::needsDestruction(), and clang::CodeGen::ConstantEmitter::tryEmitForInitializer().
Referenced by EmitStaticVarDecl().
AlwaysEmitXRayCustomEvents()
bool CodeGenFunction::AlwaysEmitXRayCustomEvents () const
AlwaysEmitXRayCustomEvents - Return true if we must unconditionally emit XRay custom event handling calls.
AlwaysEmitXRayCustomEvents - Return true if we should emit IR for calls to the __xray_customevent(...) builtin calls, when doing XRay instrumentation.
Definition at line 575 of file CodeGenFunction.cpp.
References CGM, clang::XRayInstrKind::Custom, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::XRayInstrSet::Mask, and clang::CodeGenOptions::XRayInstrumentationBundle.
AlwaysEmitXRayTypedEvents()
bool CodeGenFunction::AlwaysEmitXRayTypedEvents () const
AlwaysEmitXRayTypedEvents - Return true if clang must unconditionally emit XRay typed event handling calls.
Definition at line 582 of file CodeGenFunction.cpp.
References CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::XRayInstrSet::Mask, clang::XRayInstrKind::Typed, and clang::CodeGenOptions::XRayInstrumentationBundle.
BuildAppleKextVirtualCall()
CGCallee CodeGenFunction::BuildAppleKextVirtualCall (const CXXMethodDecl * MD, NestedNameSpecifier * Qual, llvm::Type * Ty)
BuildAppleKextVirtualCall - This routine is to support gcc's kext ABI making indirect call to virtual functions.
It makes the call through indexing into the vtable.
Definition at line 281 of file CGCXX.cpp.
References BuildAppleKextVirtualCall(), BuildAppleKextVirtualDestructorCall(), clang::Dtor_Complete, clang::Type::getAs(), clang::NestedNameSpecifier::getAsType(), clang::RecordType::getDecl(), clang::NestedNameSpecifier::getKind(), clang::T, and clang::NestedNameSpecifier::TypeSpec.
BuildAppleKextVirtualDestructorCall()
CGCallee CodeGenFunction::BuildAppleKextVirtualDestructorCall (const CXXDestructorDecl * DD, CXXDtorType Type, const CXXRecordDecl * RD)
BuildVirtualCall - This routine makes indirect vtable call for call to virtual destructors.
It returns 0 if it could not do it.
Definition at line 302 of file CGCXX.cpp.
References clang::CodeGen::CodeGenTypes::arrangeCXXStructorDeclaration(), BuildAppleKextVirtualCall(), CGM, clang::Dtor_Base, clang::Dtor_Complete, clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getTypes(), and clang::CXXMethodDecl::isVirtual().
Referenced by BuildAppleKextVirtualCall().
BuildBlockRelease()
void CodeGenFunction::BuildBlockRelease (llvm::Value * DeclPtr, BlockFieldFlags flags, bool CanThrow)
Definition at line 2770 of file CGBlocks.cpp.
References CanThrow(), CGM, EmitNounwindRuntimeCall(), EmitRuntimeCallOrInvoke(), clang::CodeGen::BlockFieldFlags::getBitMask(), clang::CodeGen::CodeGenModule::getBlockObjectDispose(), clang::CodeGen::CodeGenTypeCache::Int32Ty, and V.
BuildFunctionArgList()
QualType CodeGenFunction::BuildFunctionArgList (GlobalDecl GD, FunctionArgList & Args)
Definition at line 1565 of file CodeGenFunction.cpp.
References clang::CodeGen::CGCXXABI::addImplicitStructorParams(), clang::CodeGen::CGCXXABI::buildThisParam(), CGM, clang::ImplicitParamDecl::Create(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::GlobalDecl::getCtorType(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::GlobalDecl::getDecl(), clang::FunctionDecl::getReturnType(), clang::CXXMethodDecl::getThisType(), getTypes(), clang::CodeGen::CGCXXABI::hasMostDerivedReturn(), clang::CodeGen::CGCXXABI::HasThisReturn(), clang::CodeGen::CodeGenTypes::inheritingCtorHasParams(), clang::CXXMethodDecl::isImplicitObjectMemberFunction(), clang::Other, clang::FunctionDecl::parameters(), and clang::ASTContext::VoidPtrTy.
Referenced by EmitCall(), EmitInlinedInheritingCXXConstructorCall(), and GenerateCode().
BuildVector()
llvm::Value * CodeGenFunction::BuildVector (ArrayRef< llvm::Value * > Ops)
Definition at line 13621 of file CGBuiltin.cpp.
callCStructCopyAssignmentOperator()
void CodeGenFunction::callCStructCopyAssignmentOperator (LValue Dst, LValue Src)
Definition at line 890 of file CGNonTrivialStruct.cpp.
References callSpecialFunction(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getAlignment(), getContext(), clang::CodeGen::LValue::getType(), and clang::CodeGen::LValue::isVolatile().
callCStructCopyConstructor()
void CodeGenFunction::callCStructCopyConstructor (LValue Dst, LValue Src)
Definition at line 878 of file CGNonTrivialStruct.cpp.
References callSpecialFunction(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getAlignment(), getContext(), clang::CodeGen::LValue::getType(), and clang::CodeGen::LValue::isVolatile().
Referenced by GenerateCopyHelperFunction(), and generateObjCGetterBody().
callCStructDefaultConstructor()
void CodeGenFunction::callCStructDefaultConstructor (LValue Dst)
Definition at line 843 of file CGNonTrivialStruct.cpp.
References callSpecialFunction(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getAlignment(), getContext(), clang::CodeGen::LValue::getType(), and clang::CodeGen::LValue::isVolatile().
callCStructDestructor()
void CodeGenFunction::callCStructDestructor (LValue Dst)
Definition at line 867 of file CGNonTrivialStruct.cpp.
References callSpecialFunction(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getAlignment(), getContext(), clang::CodeGen::LValue::getType(), and clang::CodeGen::LValue::isVolatile().
callCStructMoveAssignmentOperator()
void CodeGenFunction::callCStructMoveAssignmentOperator (LValue Dst, LValue Src)
Definition at line 915 of file CGNonTrivialStruct.cpp.
References callSpecialFunction(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getAlignment(), getContext(), clang::CodeGen::LValue::getType(), and clang::CodeGen::LValue::isVolatile().
Referenced by generateObjCSetterBody().
callCStructMoveConstructor()
void CodeGenFunction::callCStructMoveConstructor (LValue Dst, LValue Src)
Definition at line 903 of file CGNonTrivialStruct.cpp.
References callSpecialFunction(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getAlignment(), getContext(), clang::CodeGen::LValue::getType(), and clang::CodeGen::LValue::isVolatile().
checkIfFunctionMustProgress()
bool clang::CodeGen::CodeGenFunction::checkIfFunctionMustProgress () inline
Returns true if a function must make progress, which means the mustprogress attribute can be added.
Definition at line 619 of file CodeGenFunction.h.
References CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), and getLangOpts().
Referenced by checkIfLoopMustProgress(), and GenerateCode().
checkIfLoopMustProgress()
bool clang::CodeGen::CodeGenFunction::checkIfLoopMustProgress (bool HasConstantCond) inline
Returns true if a loop must make progress, which means the mustprogress attribute can be added.
HasConstantCond indicates whether the branch condition is a known constant.
Definition at line 638 of file CodeGenFunction.h.
References CGM, checkIfFunctionMustProgress(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), and getLangOpts().
checkTargetFeatures() [1/2]
void CodeGenFunction::checkTargetFeatures (const CallExpr * E, const FunctionDecl * TargetDecl)
Definition at line 3006 of file CodeGenFunction.cpp.
References CGM, CurCodeDecl, clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::FunctionDecl::getBuiltinID(), clang::CodeGen::CodeGenModule::getContext(), clang::NamedDecl::getDeclName(), clang::CodeGen::CodeGenModule::getDiags(), clang::ASTContext::getFunctionFeatureMap(), clang::Expr::getIntegerConstantExpr(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), and clang::DiagnosticsEngine::Report().
Referenced by EmitCall().
checkTargetFeatures() [2/2]
void CodeGenFunction::checkTargetFeatures (SourceLocation Loc, const FunctionDecl * TargetDecl)
Definition at line 3031 of file CodeGenFunction.cpp.
References clang::ASTContext::BuiltinInfo, CGM, CurCodeDecl, clang::Builtin::evaluateRequiredTargetFeatures(), clang::ASTContext::filterFunctionTargetAttrs(), clang::Decl::getAttr(), clang::FunctionDecl::getBuiltinID(), clang::CodeGen::CodeGenModule::getContext(), clang::NamedDecl::getDeclName(), clang::CodeGen::CodeGenModule::getDiags(), clang::ASTContext::getFunctionFeatureMap(), getLangOpts(), clang::Builtin::Context::getRequiredFeatures(), clang::Decl::hasAttr(), clang::FunctionDecl::isMultiVersion(), and clang::DiagnosticsEngine::Report().
ConstantFoldsToSimpleInteger() [1/2]
bool CodeGenFunction::ConstantFoldsToSimpleInteger (const Expr * Cond, bool & ResultBool, bool AllowLabels = false)
ConstantFoldsToSimpleInteger - If the specified expression does not fold to a constant, or if it does but contains a label, return false.
If it constant folds return true and set the boolean result in Result.
Definition at line 1905 of file CodeGenFunction.cpp.
References CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGenOptions::hasProfileClangInstr().
Referenced by EmitBranchOnBoolExpr(), and clang::CodeGen::CGOpenMPRuntime::emitIfClause().
ConstantFoldsToSimpleInteger() [2/2]
bool CodeGenFunction::ConstantFoldsToSimpleInteger (const Expr * Cond, llvm::APSInt & ResultInt, bool AllowLabels = false)
ConstantFoldsToSimpleInteger - If the specified expression does not fold to a constant, or if it does but contains a label, return false.
If it constant folds return true and set the folded value.
Definition at line 1926 of file CodeGenFunction.cpp.
References ContainsLabel(), clang::Expr::EvaluateAsInt(), and getContext().
containsBreak()
bool CodeGenFunction::containsBreak (const Stmt * S) static
containsBreak - Return true if the statement contains a break out of it.
If the statement (recursively) contains a switch or loop with a break inside of it, this is fine.
Definition at line 1858 of file CodeGenFunction.cpp.
ContainsLabel()
bool CodeGenFunction::ContainsLabel (const Stmt * S, bool IgnoreCaseStmts = false) static
ContainsLabel - Return true if the statement contains a label in it.
If this statement is not executed normally, it not containing a label means that we can just remove the code.
Definition at line 1826 of file CodeGenFunction.cpp.
Referenced by ConstantFoldsToSimpleInteger(), and EmitAutoVarInit().
convertTempToRValue()
RValue CodeGenFunction::convertTempToRValue (Address addr, QualType type, SourceLocation Loc)
Given the address of a temporary variable, produce an r-value of its type.
Definition at line 6079 of file CGExpr.cpp.
References clang::CodeGen::LValue::asAggregateRValue(), clang::CodeGen::Decl, EmitLoadOfComplex(), EmitLoadOfScalar(), clang::CodeGen::RValue::get(), clang::CodeGen::RValue::getComplex(), getEvaluationKind(), MakeAddrLValue(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, and clang::ast_matchers::type.
Referenced by EmitAtomicExpr(), EmitCall(), and EmitDelegateCallArg().
ConvertType() [1/2]
llvm::Type* clang::CodeGen::CodeGenFunction::ConvertType (const TypeDecl * T) inline
Definition at line 2543 of file CodeGenFunction.h.
References ConvertType(), getContext(), and clang::T.
ConvertType() [2/2]
llvm::Type * CodeGenFunction::ConvertType (QualType T)
Definition at line 232 of file CodeGenFunction.cpp.
References CGM, clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CodeGenModule::getTypes(), and clang::T.
Referenced by AdjustObjCObjectType(), ConvertType(), emitArgumentDemotion(), emitArrayLength(), EmitArraySubscriptExpr(), EmitArrayToPointerDecay(), EmitAtomicDecrementValue(), EmitAtomicIncrementValue(), EmitBitfieldConversionCheck(), EmitCall(), EmitCastLValue(), emitCmdValueForGetterSetterBody(), EmitCommonNeonSISDBuiltinExpr(), EmitCountedByFieldExpr(), EmitCXXUuidofExpr(), EmitDeleteCall(), EmitDynamicCastToNull(), emitFrexpBuiltin(), EmitFromMemory(), EmitFunctionEpilog(), EmitFunctionProlog(), EmitIvarOffsetAsPointerDiff(), EmitLoadOfBitfieldLValue(), EmitLoadOfScalar(), emitMaybeConstrainedFPToIntRoundBuiltin(), EmitObjCBoxedExpr(), EmitObjCIsaExpr(), emitOMPArraySectionBase(), EmitPointerWithAlignment(), EmitPromotedValue(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), EmitUnPromotedValue(), emitWritebackArg(), generateObjCGetterBody(), GenerateSEHFilterFunction(), GetAddressOfBaseClass(), GetAddressOfDerivedClass(), GetAddressOfDirectBaseInCompleteClass(), getItaniumDynamicCastFn(), GetUndefRValue(), performTypeAdjustment(), StartFunction(), tryEmitSpecializedAllocInit(), and tryGenerateSpecializedMessageSend().
ConvertTypeForMem()
llvm::Type * CodeGenFunction::ConvertTypeForMem (QualType T)
Definition at line 228 of file CodeGenFunction.cpp.
References CGM, clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::CodeGenModule::getTypes(), and clang::T.
Referenced by castValueToType(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), complexTempStructure(), createPlaceholderSlot(), EmitAnyExprToExn(), emitArrayDestroy(), emitArrayLength(), emitArraySubscriptGEP(), EmitArrayToPointerDecay(), EmitAtomicExpr(), EmitAutoVarAlloca(), EmitCall(), EmitCastLValue(), clang::CodeGen::ReductionCodeGen::emitCleanups(), EmitCXXDeleteExpr(), EmitCXXMemberDataPointerAddress(), EmitCXXNewExpr(), EmitDeclDestroy(), EmitDeclRefLValue(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), EmitFunctionProlog(), emitGlobalToListCopyFunction(), emitInterWarpCopyFunction(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), emitListToGlobalCopyFunction(), EmitLValueForFieldInitialization(), EmitMaterializeTemporaryExpr(), EmitNewArrayInitializer(), EmitObjCIsaExpr(), emitOMPArraySectionBase(), EmitOMPUseDeviceAddrClause(), EmitOMPUseDevicePtrClause(), EmitParmDecl(), emitPartialArrayDestroy(), emitPointerArithmetic(), EmitPointerWithAlignment(), emitPrivatesInit(), emitShuffleAndReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), EmitStaticVarDecl(), EmitStoreThroughBitfieldLValue(), EmitToMemory(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), clang::CodeGen::EmitVAArgInstr(), clang::CodeGen::emitVoidPtrVAArg(), emitWritebackArg(), EmitX86_64VAArgFromMemory(), GenerateObjCAtomicGetterCopyHelperFunction(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), getBlockByrefInfo(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), clang::CodeGen::getVAListElementType(), InitCatchParam(), loadToBegin(), makeNaturalAddressForPointer(), MakeNaturalAlignAddrLValue(), MakeRawAddrLValue(), PerformReturnAdjustment(), and shuffleAndStore().
CreateAggTemp()
AggValueSlot clang::CodeGen::CodeGenFunction::CreateAggTemp (QualType T, const Twine & Name = "tmp", RawAddress * Alloca = nullptr) inline
CreateAggTemp - Create a temporary memory object for the given aggregate type.
Definition at line 2799 of file CodeGenFunction.h.
Referenced by EmitAnyExpr(), EmitAnyExprToTemp(), EmitCallArg(), EmitCXXBindTemporaryLValue(), and EmitCXXConstructLValue().
createAtExitStub()
llvm::Function * CodeGenFunction::createAtExitStub (const VarDecl & VD, llvm::FunctionCallee Dtor, llvm::Constant * Addr)
Create a stub function, suitable for being passed to atexit, which passes the given address to the given destructor function.
Definition at line 238 of file CGDeclCXX.cpp.
References clang::CodeGen::CodeGenTypes::arrangeNullaryFunction(), clang::AtExit, Builder, CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), clang::CodeGen::CodeGenModule::CreateGlobalInitOrCleanUpFunction(), FinishFunction(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::Expr::getExprLoc(), clang::VarDecl::getInit(), clang::Decl::getLocation(), clang::CodeGen::CGCXXABI::getMangleContext(), clang::CodeGen::CodeGenModule::getTypes(), clang::MangleContext::mangleDynamicAtExitDestructor(), StartFunction(), clang::ASTContext::VoidTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
Referenced by emitGlobalDtorWithTLRegDtor(), registerGlobalDtorWithAtExit(), and registerGlobalDtorWithLLVM().
createBasicBlock()
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::createBasicBlock (const Twine & name = "", llvm::Function * parent = nullptr, llvm::BasicBlock * before = nullptr) inline
createBasicBlock - Create an LLVM basic block.
Definition at line 2566 of file CodeGenFunction.h.
References clang::transformer::before(), getLLVMContext(), and clang::transformer::name().
Referenced by CreateNormalEntry(), clang::CodeGen::CatchRetScope::Emit(), emitArrayDestroy(), emitAtomicCmpXchgFailureSet(), EmitAtomicExpr(), EmitAtomicOp(), clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), EmitBranchOnBoolExpr(), EmitBranchToCounterBlock(), EmitCall(), clang::CodeGen::CGOpenMPRuntime::emitCancellationPointCall(), emitCatchDispatchBlock(), EmitCfiSlowPathCheck(), EmitCheck(), EmitCleanup(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), clang::CodeGen::CGCUDARuntime::EmitCUDAKernelCallExpr(), EmitCXXAggrConstructorCall(), EmitCXXDeleteExpr(), EmitCXXNewExpr(), EmitDynamicCast(), emitDynamicTlsInitialization(), emitFilterDispatchBlock(), clang::CodeGen::CGOpenMPRuntime::emitIfClause(), emitInterWarpCopyFunction(), EmitLandingPad(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), EmitMustTailThunk(), EmitNewArrayInitializer(), emitNonZeroVLAInit(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), emitPostUpdateForReductionClause(), EmitReturnValueCheck(), EmitSehScope(), emitShuffleAndReduceFunction(), EmitTrapCheck(), EmitTypeCheck(), EmitTypeidFromVTable(), clang::CodeGen::CGOpenMPRuntime::emitUDMapperArrayInitOrDel(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), EmitVTablePtrCheckForCast(), emitWasmCatchPadBlock(), emitWriteback(), emitWritebackArg(), EnsureInsertPoint(), clang::CodeGen::CodeGenFunction::FinallyInfo::enter(), GenerateCXXGlobalInitFunc(), GetAddressOfBaseClass(), GetAddressOfDerivedClass(), getEHDispatchBlock(), getEHResumeBlock(), getFuncletEHDispatchBlock(), GetIndirectGotoBlock(), getJumpDestForLabel(), getTerminateFunclet(), getTerminateHandler(), getTerminateLandingPad(), getUnreachableBlock(), PerformReturnAdjustment(), shuffleAndStore(), and StartFunction().
createCleanupActiveFlag()
RawAddress CodeGenFunction::createCleanupActiveFlag ()
Definition at line 268 of file CGCleanup.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateStore(), CreateTempAllocaWithoutCast(), clang::CharUnits::One(), and setBeforeOutermostConditional().
Referenced by initFullExprCleanup(), pushCleanupAfterFullExpr(), and pushLifetimeExtendedDestroy().
CreateDefaultAlignTempAlloca()
RawAddress CodeGenFunction::CreateDefaultAlignTempAlloca (llvm::Type * Ty, const Twine & Name = "tmp")
CreateDefaultAlignedTempAlloca - This creates an alloca with the default ABI alignment of the given LLVM type.
CreateDefaultAlignTempAlloca - This creates an alloca with the default alignment of the corresponding LLVM type, which is not guaranteed to be related in any way to the expected alignment of an AST type that might have been lowered to Ty.
IMPORTANT NOTE: This is not generally the right alignment for any given AST type that happens to have been lowered to the given IR type. This should only ever be used for function-local, IR-driven manipulations like saving and restoring a value. Do not hand this address off to arbitrary IRGen routines, and especially do not pass it as an argument to a function that might expect a properly ABI-aligned value.
Definition at line 129 of file CGExpr.cpp.
Referenced by EmitCheckValue(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsCall(), and StartFunction().
CreateIRTemp()
RawAddress CodeGenFunction::CreateIRTemp (QualType T, const Twine & Name = "tmp")
CreateIRTemp - Create a temporary IR object of the given type, with appropriate alignment.
This routine should only be used when an temporary value needs to be stored into an alloca (for example, to avoid explicit PHI construction), but the type is the IR type, not the type appropriate for storing in memory.
That is, this is exactly equivalent to CreateMemTemp, but calling ConvertType instead of ConvertTypeForMem.
Definition at line 136 of file CGExpr.cpp.
Referenced by EmitInlinedInheritingCXXConstructorCall(), maybeCreateMCDCCondBitmap(), and StartFunction().
CreateMemTemp() [1/2]
RawAddress CodeGenFunction::CreateMemTemp (QualType T, CharUnits Align, const Twine & Name = "tmp", RawAddress * Alloca = nullptr)
Definition at line 147 of file CGExpr.cpp.
CreateMemTemp() [2/2]
RawAddress CodeGenFunction::CreateMemTemp (QualType T, const Twine & Name = "tmp", RawAddress * Alloca = nullptr)
CreateMemTemp - Create a temporary memory object of the given type, with appropriate alignmen and cast it to the default address space.
Returns the original alloca instruction by Alloca if it is not nullptr.
Definition at line 141 of file CGExpr.cpp.
Referenced by castToBase(), castValueToType(), complexTempStructure(), EmitAggExprToLValue(), EmitAtomicExpr(), EmitCall(), EmitCompoundLiteralLValue(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitDoacrossOrdered(), EmitExtVectorElementExpr(), EmitFunctionProlog(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), EmitLambdaStaticInvokeBody(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), emitListToGlobalReduceFunction(), EmitObjCBoxedExpr(), EmitParmDecl(), EmitSEHExceptionCodeSave(), emitShuffleAndReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CGOpenMPRuntime::emitThreadIDAddress(), clang::CodeGen::EmitVAArgInstr(), EmitValToTemp(), GenerateBlockFunction(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), clang::CodeGen::CallArg::getRValue(), GetUndefRValue(), setBlockContextParameter(), and clang::CodeGen::CodeGenFunction::OMPMapVars::setVarAddr().
CreateMemTempWithoutCast() [1/2]
RawAddress CodeGenFunction::CreateMemTempWithoutCast (QualType T, CharUnits Align, const Twine & Name = "tmp")
Definition at line 164 of file CGExpr.cpp.
CreateMemTempWithoutCast() [2/2]
RawAddress CodeGenFunction::CreateMemTempWithoutCast (QualType T, const Twine & Name = "tmp")
CreateMemTemp - Create a temporary memory object of the given type, with appropriate alignmen without casting it to the default address space.
Definition at line 170 of file CGExpr.cpp.
Referenced by EmitCall().
CreateTempAlloca() [1/2]
RawAddress CodeGenFunction::CreateTempAlloca (llvm::Type * Ty, CharUnits Align, const Twine & Name = "tmp", llvm::Value * ArraySize = nullptr, RawAddress * AllocaAddr = nullptr)
CreateTempAlloca - This creates a alloca and inserts it into the entry block.
The alloca is casted to default address space if necessary.
Definition at line 85 of file CGExpr.cpp.
CreateTempAlloca() [2/2]
llvm::AllocaInst * CodeGenFunction::CreateTempAlloca (llvm::Type * Ty, const Twine & Name = "tmp", llvm::Value * ArraySize = nullptr)
CreateTempAlloca - This creates an alloca and inserts it into the entry block if ArraySize is nullptr, otherwise inserts it at the current insertion point of the builder.
The caller is responsible for setting an appropriate alignment on the alloca.
ArraySize is the number of array elements to be allocated if it is not nullptr.
LangAS::Default is the address space of pointers to local variables and temporaries, as exposed in the source language. In certain configurations, this is not the same as the alloca address space, and a cast is needed to lift the pointer from the alloca AS into LangAS::Default. This can happen when the target uses a restricted address space for the stack but the source language requires LangAS::Default to be a generic address space. The latter condition is common for most programming languages; OpenCL is an exception in that LangAS::Default is the private address space, which naturally maps to the stack.
Because the address of a temporary is often exposed to the program in various ways, this function will perform the cast. The original alloca instruction is returned through Alloca if it is not nullptr.
The cast is not performaed in CreateTempAllocaWithoutCast. This is more efficient if the caller knows that the address will not be exposed.
Definition at line 116 of file CGExpr.cpp.
Referenced by EmitAutoVarAlloca(), EmitBlockLiteral(), EmitCall(), EmitDeleteCall(), EmitFunctionProlog(), EmitNewArrayInitializer(), emitWritebackArg(), clang::CodeGen::CodeGenFunction::FinallyInfo::enter(), GenerateBlockFunction(), getEHSelectorSlot(), getExceptionSlot(), InitCatchParam(), clang::CodeGen::DominatingLLVMValue::save(), and SetupCleanupBlockActivation().
CreateTempAllocaWithoutCast()
RawAddress CodeGenFunction::CreateTempAllocaWithoutCast (llvm::Type * Ty, CharUnits align, const Twine & Name = "tmp", llvm::Value * ArraySize = nullptr)
CreateTempAlloca - This creates a alloca and inserts it into the entry block.
Definition at line 75 of file CGExpr.cpp.
Referenced by createCleanupActiveFlag().
createTLSAtExitStub()
llvm::Function * CodeGenFunction::createTLSAtExitStub (const VarDecl & VD, llvm::FunctionCallee Dtor, llvm::Constant * Addr, llvm::FunctionCallee & AtExit)
Create a stub function, suitable for being passed to __pt_atexit_np, which passes the given address to the given destructor function.
Definition at line 275 of file CGDeclCXX.cpp.
References clang::CodeGen::RequiredArgs::All, clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), clang::AtExit, Builder, CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), clang::CodeGen::CodeGenModule::CreateGlobalInitOrCleanUpFunction(), clang::CodeGen::CGBuilderTy::CreateStore(), FinishFunction(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::Expr::getExprLoc(), clang::VarDecl::getInit(), clang::Decl::getLocation(), clang::CodeGen::CGCXXABI::getMangleContext(), clang::CodeGen::CodeGenModule::getTypes(), clang::ASTContext::IntTy, clang::CodeGen::CodeGenTypeCache::IntTy, clang::MangleContext::mangleDynamicAtExitDestructor(), clang::CodeGen::None, clang::Other, ReturnValue, and StartFunction().
currentFunctionUsesSEHTry()
bool clang::CodeGen::CodeGenFunction::currentFunctionUsesSEHTry () const inline
Definition at line 2154 of file CodeGenFunction.h.
References CurSEHParent.
Referenced by EmitCall(), findDominatingStoreToReturnValue(), and getInvokeDestImpl().
cxxDestructorCanThrow()
bool CodeGenFunction::cxxDestructorCanThrow (QualType T) static
Check if T is a C++ class that has a destructor that can throw.
Definition at line 1676 of file CGBlocks.cpp.
References clang::Type::getAsCXXRecordDecl(), and clang::T.
Referenced by EmitAutoVarCleanups(), getBlockCaptureStr(), and pushCaptureCleanup().
DeactivateCleanupBlock()
void CodeGenFunction::DeactivateCleanupBlock (EHScopeStack::stable_iterator Cleanup, llvm::Instruction * DominatingIP)
DeactivateCleanupBlock - Deactivates the given cleanup block.
Deactive a cleanup that was created in an active state.
The block cannot be reactivated. Pops it if it's the top of the stack.
Parameters
DominatingIP - An instruction which is known to dominate the current IP (if set) and which lies along all paths of execution between the current IP and the the point at which the cleanup comes into scope.
Definition at line 1266 of file CGCleanup.cpp.
Referenced by deactivateArgCleanupsBeforeCall(), EmitAnyExprToExn(), EmitCXXNewExpr(), EmitNewArrayInitializer(), and generateObjCSetterBody().
defaultInitNonTrivialCStructVar()
void CodeGenFunction::defaultInitNonTrivialCStructVar (LValue Dst)
Definition at line 811 of file CGNonTrivialStruct.cpp.
References CGM, clang::CodeGen::LValue::getAddress(), getContext(), clang::CodeGen::LValue::getType(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::LValue::isVolatile(), clang::CodeGen::Address::withElementType(), clang::QualType::withVolatile(), and clang::CharUnits::Zero().
Referenced by EmitAutoVarInit().
disableDebugInfo()
void clang::CodeGen::CodeGenFunction::disableDebugInfo () inline
Definition at line 2120 of file CodeGenFunction.h.
EmitAArch64BuiltinExpr()
Value * CodeGenFunction::EmitAArch64BuiltinExpr (unsigned BuiltinID, const CallExpr * E, llvm::Triple::ArchType Arch)
Definition at line 10926 of file CGBuiltin.cpp.
References clang::AArch64::FirstSMEBuiltin, clang::AArch64::FirstSVEBuiltin, clang::Function, clang::AArch64::LastSMEBuiltin, and clang::AArch64::LastSVEBuiltin.
Referenced by EmitTargetArchBuiltinExpr().
EmitAArch64CompareBuiltinExpr()
Value * CodeGenFunction::EmitAArch64CompareBuiltinExpr (llvm::Value * Op, llvm::Type * Ty, const llvm::CmpInst::Predicate Fp, const llvm::CmpInst::Predicate Ip, const llvm::Twine & Name = "")
Definition at line 8386 of file CGBuiltin.cpp.
EmitAArch64MultiVersionResolver()
void CodeGenFunction::EmitAArch64MultiVersionResolver (llvm::Function * Resolver, ArrayRef< MultiVersionResolverOption > Options)
Definition at line 3203 of file CodeGenFunction.cpp.
EmitAArch64SMEBuiltinExpr()
Value * CodeGenFunction::EmitAArch64SMEBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 10882 of file CGBuiltin.cpp.
References AArch64SMEIntrinsicMap, AArch64SMEIntrinsicsProvenSorted, findARMVectorIntrinsicInMap(), clang::Function, clang::SVETypeFlags::isLoad(), clang::SVETypeFlags::isOverloadNone(), clang::SVETypeFlags::isReadZA(), clang::SVETypeFlags::isStore(), clang::SVETypeFlags::isWriteZA(), and swapCommutativeSMEOperands().
EmitAArch64SVEBuiltinExpr()
Value * CodeGenFunction::EmitAArch64SVEBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Should not happen
Definition at line 10497 of file CGBuiltin.cpp.
References AArch64SVEIntrinsicMap, AArch64SVEIntrinsicsProvenSorted, findARMVectorIntrinsicInMap(), clang::CallExpr::getArg(), clang::SVETypeFlags::getMergeType(), clang::Expr::getType(), InsertExplicitZeroOperand(), clang::SVETypeFlags::isGatherLoad(), clang::SVETypeFlags::isGatherPrefetch(), clang::SVETypeFlags::isLoad(), clang::SVETypeFlags::isPrefetch(), clang::SVETypeFlags::isScatterStore(), clang::SVETypeFlags::isStore(), clang::SVETypeFlags::isStructLoad(), clang::SVETypeFlags::isStructStore(), clang::SVETypeFlags::isTupleCreate(), clang::SVETypeFlags::isTupleGet(), clang::SVETypeFlags::isTupleSet(), clang::SVETypeFlags::isUndef(), and clang::SVETypeFlags::isZExtReturn().
emitAddrOfImagComponent()
Address CodeGenFunction::emitAddrOfImagComponent (Address complex, QualType complexType)
Definition at line 424 of file CGExprComplex.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateStructGEP(), and clang::CodeGen::Address::getName().
Referenced by EmitUnaryOpLValue().
emitAddrOfRealComponent()
Address CodeGenFunction::emitAddrOfRealComponent (Address complex, QualType complexType)
Definition at line 419 of file CGExprComplex.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateStructGEP(), and clang::CodeGen::Address::getName().
Referenced by EmitUnaryOpLValue().
EmitAggExpr()
void CodeGenFunction::EmitAggExpr (const Expr * E, AggValueSlot Slot)
EmitAggExpr - Emit the computation of the specified expression of aggregate type.
The result is computed into the given slot, which may be null to indicate that the value is not needed.
The result is computed into DestPtr. Note that if DestPtr is null, the value of the aggregate expression is not needed. If VolatileDest is true, DestPtr cannot be 0.
Definition at line 2063 of file CGExprAgg.cpp.
References CheckAggExprForMemSetUse(), clang::CodeGen::AggValueSlot::getAddress(), clang::Expr::getType(), hasAggregateEvaluationKind(), clang::CodeGen::AggValueSlot::isIgnored(), and clang::CodeGen::Address::isValid().
Referenced by EmitAggExprToLValue(), EmitAnyExpr(), EmitAnyExprToMem(), EmitAtomicInit(), EmitBaseInitializer(), EmitCallArg(), EmitCXXBindTemporaryLValue(), EmitCXXConstructExpr(), EmitDeclInit(), EmitDelegatingCXXConstructorCall(), EmitExprAsInit(), EmitInitializerForField(), EmitMaterializeTemporaryExpr(), EmitNewArrayInitializer(), emitPseudoObjectExpr(), GenerateObjCAtomicGetterCopyHelperFunction(), GenerateObjCCtorDtorMethod(), InitCatchParam(), and StoreAnyExprIntoOneUnit().
EmitAggExprToLValue()
LValue CodeGenFunction::EmitAggExprToLValue (const Expr * E)
EmitAggExprToLValue - Emit the computation of the specified expression of aggregate type into a temporary LValue.
Definition at line 2075 of file CGExprAgg.cpp.
References CreateMemTemp(), clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, EmitAggExpr(), clang::CodeGen::AggValueSlot::forLValue(), clang::Expr::getType(), hasAggregateEvaluationKind(), clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::AggValueSlot::IsNotDestructed, and MakeAddrLValue().
Referenced by EmitBinaryOperatorLValue(), EmitCastLValue(), EmitConditionalOperatorLValue(), EmitIgnoredConditionalOperator(), EmitInitListLValue(), and EmitVAArgExprLValue().
EmitAggregateAssign()
void clang::CodeGen::CodeGenFunction::EmitAggregateAssign (LValue Dest, LValue Src, QualType EltTy) inline
Emit an aggregate assignment.
Definition at line 2892 of file CodeGenFunction.h.
References EmitAggregateCopy(), hasVolatileMember(), and clang::CodeGen::AggValueSlot::MayOverlap.
Referenced by emitPrivatesInit().
EmitAggregateCopy()
void CodeGenFunction::EmitAggregateCopy (LValue Dest, LValue Src, QualType EltTy, AggValueSlot::Overlap_t MayOverlap, bool isVolatile = false)
EmitAggregateCopy - Emit an aggregate copy.
Parameters
isVolatile true iff either the source or the destination is volatile.
MayOverlap Whether the tail padding of the destination might be occupied by some other object. More efficient code can often be generated if not.
Definition at line 2126 of file CGExprAgg.cpp.
References Builder, CGM, clang::CPlusPlus, clang::CodeGen::CGBuilderTy::CreateMemCpy(), clang::CodeGen::CodeGenModule::DecorateInstructionWithTBAA(), emitArrayLength(), clang::CodeGen::CGObjCRuntime::EmitGCMemmoveCollectable(), clang::CodeGen::LValue::getAddress(), clang::Type::getAs(), clang::ASTContext::getBaseElementType(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::RecordType::getDecl(), getLangOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getObjCRuntime(), getTargetHooks(), clang::CodeGen::LValue::getTBAAInfo(), clang::CodeGen::CodeGenModule::getTBAAStructInfo(), clang::ASTContext::getTypeInfoDataSizeInChars(), clang::ASTContext::getTypeInfoInChars(), clang::RecordDecl::hasObjectMember(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::Type::isAnyComplexType(), clang::Type::isArrayType(), clang::Type::isCUDADeviceBuiltinSurfaceType(), clang::Type::isCUDADeviceBuiltinTextureType(), clang::CodeGen::CodeGenModule::mergeTBAAInfoForMemoryTransfer(), clang::LangOptionsBase::NonGC, clang::CodeGen::CodeGenTypeCache::SizeTy, clang::TypeInfo::Width, and clang::CodeGen::Address::withElementType().
Referenced by clang::CodeGen::CallArg::copyInto(), EmitAggregateAssign(), EmitAggregateCopyCtor(), emitGlobalToListCopyFunction(), emitListToGlobalCopyFunction(), EmitMemberInitializer(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), generateObjCGetterBody(), clang::CodeGen::CallArg::getRValue(), and InitCatchParam().
EmitAggregateCopyCtor()
void clang::CodeGen::CodeGenFunction::EmitAggregateCopyCtor (LValue Dest, LValue Src, AggValueSlot::Overlap_t MayOverlap) inline
Definition at line 2897 of file CodeGenFunction.h.
References EmitAggregateCopy(), and clang::CodeGen::LValue::getType().
Referenced by EmitCXXConstructorCall().
EmitAggregateStore()
void CodeGenFunction::EmitAggregateStore (llvm::Value * Val, Address Dest, bool DestIsVolatile)
Build all the stores needed to initialize an aggregate at Dest with the value Val.
Definition at line 1352 of file CGCall.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateStore(), and clang::CodeGen::CGBuilderTy::CreateStructGEP().
Referenced by CreateCoercedStore(), and EmitCall().
emitAlignmentAssumption() [1/2]
void CodeGenFunction::emitAlignmentAssumption (llvm::Value * PtrValue, const Expr * E, SourceLocation AssumptionLoc, llvm::Value * Alignment, llvm::Value * OffsetValue = nullptr)
Definition at line 2820 of file CodeGenFunction.cpp.
References emitAlignmentAssumption(), clang::Expr::getExprLoc(), and clang::Expr::getType().
emitAlignmentAssumption() [2/2]
void CodeGenFunction::emitAlignmentAssumption (llvm::Value * PtrValue, QualType Ty, SourceLocation Loc, SourceLocation AssumptionLoc, llvm::Value * Alignment, llvm::Value * OffsetValue = nullptr)
Definition at line 2780 of file CodeGenFunction.cpp.
References Builder, CGM, emitAlignmentAssumptionCheck(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenTypeCache::IntPtrTy, and SanOpts.
Referenced by emitAlignedClause(), and emitAlignmentAssumption().
emitAlignmentAssumptionCheck()
void CodeGenFunction::emitAlignmentAssumptionCheck (llvm::Value * Ptr, QualType Ty, SourceLocation Loc, SourceLocation AssumptionLoc, llvm::Value * Alignment, llvm::Value * OffsetValue, llvm::Value * TheCheck, llvm::Instruction * Assumption)
Definition at line 3295 of file CodeGenFunction.cpp.
References Builder, EmitCheck(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), EmitCheckValue(), clang::Type::getPointeeType(), clang::SanitizerSet::has(), clang::QualType::isVolatileQualified(), and SanOpts.
Referenced by emitAlignmentAssumption().
EmitAMDGPUBuiltinExpr()
Value * CodeGenFunction::EmitAMDGPUBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 18457 of file CGBuiltin.cpp.
References EmitPointerWithAlignment(), clang::CallExpr::getArg(), ID, and X.
Referenced by EmitTargetArchBuiltinExpr().
EmitAMDGPUDevicePrintfCallExpr()
RValue CodeGenFunction::EmitAMDGPUDevicePrintfCallExpr (const CallExpr * E)
Definition at line 189 of file CGGPUBuiltin.cpp.
References clang::TargetOptions::AMDGPUPrintfKindVal, clang::CallExpr::arguments(), clang::TargetOptions::Buffered, Builder, CGM, EmitCallArgs(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::RValue::get(), clang::Type::getAs(), clang::CallExpr::getBuiltinCallee(), clang::CallExpr::getDirectCallee(), clang::CallExpr::getNumArgs(), getTarget(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTargetOpts(), clang::ValueDecl::getType(), and clang::CodeGen::CodeGenTypeCache::IntTy.
EmitAndRegisterVariableArrayDimensions()
void CodeGenFunction::EmitAndRegisterVariableArrayDimensions (CGDebugInfo * DI, const VarDecl & D, bool EmitDebugInfo)
Emits the alloca and debug information for the size expressions for each dimension of an array.
It registers the association of its (1-dimensional) QualTypes and size expression's debug node, so that CGDebugInfo can reference this node when creating the DISubrange object to describe the array types.
Definition at line 1417 of file CGDecl.cpp.
References getContext(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), and getVLAElements1D().
EmitAnnotationCall()
llvm::Value * CodeGenFunction::EmitAnnotationCall (llvm::Function * AnnotationFn, llvm::Value * AnnotatedVal, StringRef AnnotationStr, SourceLocation Location, const AnnotateAttr * Attr = nullptr)
Emit an annotation call (intrinsic).
Definition at line 2832 of file CodeGenFunction.cpp.
References Builder, CGM, clang::CodeGen::CodeGenTypeCache::ConstGlobalsPtrTy, clang::CodeGen::CodeGenModule::EmitAnnotationArgs(), clang::CodeGen::CodeGenModule::EmitAnnotationLineNo(), clang::CodeGen::CodeGenModule::EmitAnnotationString(), clang::CodeGen::CodeGenModule::EmitAnnotationUnit(), and ID.
Referenced by EmitFieldAnnotations(), EmitIntelFPGAFieldAnnotations(), and EmitVarAnnotations().
EmitAnyExpr()
RValue CodeGenFunction::EmitAnyExpr (const Expr * E, AggValueSlot aggSlot = AggValueSlot::ignored(), bool ignoreResult = false)
EmitAnyExpr - Emit code to compute the specified expression which can have any type.
The result is returned as an RValue struct. If this is an aggregate expression, the aggloc/agglocvolatile arguments indicate where the result should be returned.
Parameters
ignoreResult True if the resulting value isn't used.
The result is returned as an RValue struct. If this is an aggregate expression, AggSlot indicates where the result should be returned.
Definition at line 219 of file CGExpr.cpp.
References clang::CodeGen::AggValueSlot::asRValue(), CreateAggTemp(), EmitAggExpr(), EmitComplexExpr(), EmitScalarExpr(), clang::CodeGen::RValue::get(), clang::CodeGen::RValue::getComplex(), getEvaluationKind(), clang::Expr::getType(), clang::CodeGen::AggValueSlot::isIgnored(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
Referenced by clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::bind(), EmitAnyExprToTemp(), EmitBinaryOperatorLValue(), EmitIgnoredExpr(), EmitObjCBoxedExpr(), emitOMPAtomicCaptureExpr(), emitOMPAtomicUpdateExpr(), emitOMPAtomicWriteExpr(), emitPseudoObjectExpr(), emitSimdlenSafelenClause(), GenerateObjCAtomicGetterCopyHelperFunction(), and getOrCreateOpaqueRValueMapping().
EmitAnyExprToExn()
void CodeGenFunction::EmitAnyExprToExn (const Expr * E, Address Addr)
Definition at line 397 of file CGException.cpp.
References clang::format::cleanup(), ConvertTypeForMem(), DeactivateCleanupBlock(), clang::CodeGen::EHCleanup, EHStack, EmitAnyExprToMem(), clang::CodeGen::Address::emitRawPointer(), clang::QualType::getQualifiers(), clang::Expr::getType(), clang::CodeGen::EHScopeStack::stable_begin(), and clang::CodeGen::Address::withElementType().
EmitAnyExprToMem()
void CodeGenFunction::EmitAnyExprToMem (const Expr * E, Address Location, Qualifiers Quals, bool IsInitializer)
EmitAnyExprToMem - Emits the code necessary to evaluate an arbitrary expression into the given memory location.
EmitAnyExprToMem - Evaluate an expression into a given memory location.
Definition at line 248 of file CGExpr.cpp.
References clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, EmitAggExpr(), EmitComplexExprIntoLValue(), EmitScalarExpr(), EmitStoreThroughLValue(), clang::CodeGen::AggValueSlot::forAddr(), clang::CodeGen::RValue::get(), getEvaluationKind(), clang::Expr::getType(), MakeAddrLValue(), clang::CodeGen::AggValueSlot::MayOverlap, clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
Referenced by EmitAnyExprToExn(), EmitCompoundLiteralLValue(), clang::CodeGen::ReductionCodeGen::emitInitialization(), EmitMaterializeTemporaryExpr(), EmitObjCBoxedExpr(), EmitOMPAggregateInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), and EmitValToTemp().
EmitAnyExprToTemp()
RValue CodeGenFunction::EmitAnyExprToTemp (const Expr * E)
EmitAnyExprToTemp - Similarly to EmitAnyExpr(), however, the result will always be accessible even if no aggregate location is provided.
EmitAnyExprToTemp - Similar to EmitAnyExpr(), however, the result will always be accessible even if no aggregate location is provided.
Definition at line 238 of file CGExpr.cpp.
References CreateAggTemp(), EmitAnyExpr(), clang::Expr::getType(), hasAggregateEvaluationKind(), and clang::CodeGen::AggValueSlot::ignored().
Referenced by EmitCallArg(), and EmitStmtExprLValue().
EmitARCAutorelease()
llvm::Value * CodeGenFunction::EmitARCAutorelease (llvm::Value * value)
Autorelease the given object.
call i8* @objc_autorelease(i8* value)
Definition at line 2535 of file CGObjC.cpp.
References CGM, emitARCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_autorelease.
Referenced by EmitARCRetainAutorelease(), and EmitARCRetainAutoreleaseScalarExpr().
EmitARCAutoreleaseReturnValue()
llvm::Value * CodeGenFunction::EmitARCAutoreleaseReturnValue (llvm::Value * value)
Autorelease the given object.
call i8* @objc_autoreleaseReturnValue(i8* value)
Definition at line 2544 of file CGObjC.cpp.
References CGM, emitARCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_autoreleaseReturnValue.
Referenced by emitAutoreleaseOfResult().
emitARCCopyAssignWeak()
void CodeGenFunction::emitARCCopyAssignWeak (QualType Ty, Address DstAddr, Address SrcAddr)
Definition at line 2662 of file CGObjC.cpp.
References EmitARCLoadWeakRetained(), EmitARCStoreWeak(), and EmitObjCConsumeObject().
EmitARCCopyWeak()
void CodeGenFunction::EmitARCCopyWeak (Address dst, Address src)
void @objc_copyWeak(i8** dest, i8** src) Disregards the current value in dest.
Essentially objc_release(objc_initWeak(dest, objc_readWeakRetained(src)))
Definition at line 2656 of file CGObjC.cpp.
References CGM, emitARCCopyOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_copyWeak.
Referenced by GenerateCopyHelperFunction(), and tryEmitARCCopyWeakInit().
EmitARCDestroyStrong()
void CodeGenFunction::EmitARCDestroyStrong (Address addr, ARCPreciseLifetime_t precise)
Destroy a __strong variable.
At -O0, emit a call to store 'null' into the address; instrumenting tools prefer this because the address is exposed, but it's relatively cumbersome to optimize.
At -O1 and above, just load and call objc_release.
call void @objc_storeStrong(i8** addr, i8* null)
Definition at line 2465 of file CGObjC.cpp.
References Builder, CGM, clang::CodeGen::CGBuilderTy::CreateLoad(), EmitARCRelease(), EmitARCStoreStrongCall(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), and getNullForVariable().
Referenced by EmitObjectDelete().
EmitARCDestroyWeak()
void CodeGenFunction::EmitARCDestroyWeak (Address addr)
void @objc_destroyWeak(i8** addr) Essentially objc_storeWeak(addr, nil).
Definition at line 2636 of file CGObjC.cpp.
References CGM, EmitNounwindRuntimeCall(), clang::CodeGen::Address::emitRawPointer(), getARCIntrinsic(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_destroyWeak.
Referenced by emitARCMoveAssignWeak(), EmitCXXPseudoDestructorExpr(), and EmitObjectDelete().
EmitARCExtendBlockObject()
llvm::Value * CodeGenFunction::EmitARCExtendBlockObject (const Expr * expr)
Definition at line 3479 of file CGObjC.cpp.
References EmitARCRetainBlock(), EmitObjCConsumeObject(), EmitScalarExpr(), clang::Expr::getType(), shouldEmitSeparateBlockRetain(), and tryEmitARCRetainScalarExpr().
EmitARCInitWeak()
void CodeGenFunction::EmitARCInitWeak (Address addr, llvm::Value * value)
i8* @objc_initWeak(i8** addr, i8* value) Returns value.
addr is known to not have a current weak entry. Essentially equivalent to: *addr = nil; objc_storeWeak(addr, value);
Definition at line 2618 of file CGObjC.cpp.
References Builder, CGM, clang::CodeGen::CGBuilderTy::CreateStore(), emitARCStoreOperation(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_initWeak.
Referenced by clang::CodeGen::CGObjCRuntime::EmitInitOfCatchParam(), EmitParmDecl(), EmitScalarInit(), and InitCatchParam().
EmitARCIntrinsicUse()
void CodeGenFunction::EmitARCIntrinsicUse (ArrayRef< llvm::Value * > values)
Given a number of pointers, inform the optimizer that they're being intrinsically used up until this point in the program.
Definition at line 2123 of file CGObjC.cpp.
References CGM, clang::CodeGen::ObjCEntrypoints::clang_arc_use, EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenModule::getIntrinsic(), and clang::CodeGen::CodeGenModule::getObjCEntrypoints().
Referenced by emitWriteback().
EmitARCLoadWeak()
llvm::Value * CodeGenFunction::EmitARCLoadWeak (Address addr)
i8* @objc_loadWeak(i8** addr) Essentially objc_autorelease(objc_loadWeakRetained(addr)).
Definition at line 2591 of file CGObjC.cpp.
References CGM, emitARCLoadOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_loadWeak.
Referenced by EmitLoadOfLValue(), and generateObjCGetterBody().
EmitARCLoadWeakRetained()
llvm::Value * CodeGenFunction::EmitARCLoadWeakRetained (Address addr)
i8* @objc_loadWeakRetained(i8** addr)
Definition at line 2598 of file CGObjC.cpp.
References CGM, emitARCLoadOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_loadWeakRetained.
Referenced by emitARCCopyAssignWeak(), emitARCMoveAssignWeak(), EmitLoadOfLValue(), EmitObjCMessageExpr(), and tryEmitARCRetainLoadOfScalar().
emitARCMoveAssignWeak()
void CodeGenFunction::emitARCMoveAssignWeak (QualType Ty, Address DstAddr, Address SrcAddr)
Definition at line 2669 of file CGObjC.cpp.
References EmitARCDestroyWeak(), EmitARCLoadWeakRetained(), EmitARCStoreWeak(), and EmitObjCConsumeObject().
EmitARCMoveWeak()
void CodeGenFunction::EmitARCMoveWeak (Address dst, Address src)
void @objc_moveWeak(i8** dest, i8** src) Disregards the current value in dest.
Leaves src pointing to nothing. Essentially (objc_copyWeak(dest, src), objc_destroyWeak(src)).
Definition at line 2647 of file CGObjC.cpp.
References CGM, emitARCCopyOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_moveWeak.
Referenced by tryEmitARCCopyWeakInit().
EmitARCNoopIntrinsicUse()
void CodeGenFunction::EmitARCNoopIntrinsicUse (ArrayRef< llvm::Value * > values)
Emit a call to "clang.arc.noop.use", which consumes the result of a call that has operand bundle "clang.arc.attachedcall".
Definition at line 2135 of file CGObjC.cpp.
References CGM, clang::CodeGen::ObjCEntrypoints::clang_arc_noop_use, EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenModule::getIntrinsic(), and clang::CodeGen::CodeGenModule::getObjCEntrypoints().
Referenced by emitOptimizedARCReturnCall().
EmitARCReclaimReturnedObject()
llvm::Value * CodeGenFunction::EmitARCReclaimReturnedObject (const Expr * e, bool allowUnsafeClaim)
Definition at line 3044 of file CGObjC.cpp.
References CGM, emitARCRetainCallResult(), emitARCUnsafeClaimCallResult(), EmitObjCConsumeObject(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::Expr::getType(), clang::ObjCRuntime::hasARCUnsafeClaimAutoreleasedReturnValue(), and clang::LangOptions::ObjCRuntime.
EmitARCRelease()
void CodeGenFunction::EmitARCRelease (llvm::Value * value, ARCPreciseLifetime_t precise)
Release the given object.
call void @objc_release(i8* value)
Definition at line 2436 of file CGObjC.cpp.
References clang::CodeGen::ARCImpreciseLifetime, Builder, CGM, EmitNounwindRuntimeCall(), getARCIntrinsic(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and clang::CodeGen::ObjCEntrypoints::objc_release.
Referenced by clang::CodeGen::CGObjCRuntime::destroyCalleeDestroyedArguments(), EmitARCDestroyStrong(), EmitARCStoreStrong(), EmitCXXPseudoDestructorExpr(), EmitScalarInit(), and emitWriteback().
EmitARCRetain()
llvm::Value * CodeGenFunction::EmitARCRetain (QualType type, llvm::Value * value)
Produce the code to do a retain.
Based on the type, calls one of: call i8* @objc_retain(i8* value) call i8* @objc_retainBlock(i8* value)
Definition at line 2284 of file CGObjC.cpp.
References EmitARCRetainBlock(), EmitARCRetainNonBlock(), and clang::ast_matchers::type.
Referenced by emitARCRetainLoadOfScalar(), EmitARCRetainScalarExpr(), and EmitARCStoreStrong().
EmitARCRetainAutorelease()
llvm::Value * CodeGenFunction::EmitARCRetainAutorelease (QualType type, llvm::Value * value)
Do a fused retain/autorelease of the given object.
call i8* @objc_retainAutorelease(i8* value) or retain = call i8* @objc_retainBlock(i8* value) call i8* @objc_autorelease(i8* retain)
Definition at line 2566 of file CGObjC.cpp.
References Builder, EmitARCAutorelease(), EmitARCRetainAutoreleaseNonBlock(), EmitARCRetainBlock(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and clang::ast_matchers::type.
Referenced by EmitARCRetainAutoreleaseScalarExpr(), EmitObjCExtendObjectLifetime(), and EmitObjCMessageExpr().
EmitARCRetainAutoreleasedReturnValue()
llvm::Value * CodeGenFunction::EmitARCRetainAutoreleasedReturnValue (llvm::Value * value)
Retain the given object which is the result of a function call.
call i8* @objc_retainAutoreleasedReturnValue(i8* value)
Yes, this function name is one character away from a different call with completely different semantics.
Definition at line 2418 of file CGObjC.cpp.
References emitOptimizedARCReturnCall().
Referenced by emitARCRetainCallResult(), and EmitForwardingCallToLambda().
EmitARCRetainAutoreleaseNonBlock()
llvm::Value * CodeGenFunction::EmitARCRetainAutoreleaseNonBlock (llvm::Value * value)
Do a fused retain/autorelease of the given object.
call i8* @objc_retainAutorelease(i8* value)
Definition at line 2583 of file CGObjC.cpp.
References CGM, emitARCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_retainAutorelease.
Referenced by EmitARCRetainAutorelease().
EmitARCRetainAutoreleaseReturnValue()
llvm::Value * CodeGenFunction::EmitARCRetainAutoreleaseReturnValue (llvm::Value * value)
Do a fused retain/autorelease of the given object.
call i8* @objc_retainAutoreleaseReturnValue(i8* value)
Definition at line 2554 of file CGObjC.cpp.
References CGM, emitARCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_retainAutoreleaseReturnValue.
Referenced by tryEmitFusedAutoreleaseOfResult().
EmitARCRetainAutoreleaseScalarExpr()
llvm::Value * CodeGenFunction::EmitARCRetainAutoreleaseScalarExpr (const Expr * expr)
Definition at line 3463 of file CGObjC.cpp.
References EmitARCAutorelease(), EmitARCRetainAutorelease(), clang::Expr::getType(), and tryEmitARCRetainScalarExpr().
Referenced by EmitARCStoreAutoreleasing(), EmitObjCThrowOperand(), and EmitScalarInit().
EmitARCRetainBlock()
llvm::Value * CodeGenFunction::EmitARCRetainBlock (llvm::Value * value, bool mandatory)
Retain the given block, with _Block_copy semantics.
call i8* @objc_retainBlock(i8* value)
Parameters
mandatory - If false, emit the call with metadata indicating that it's okay for the optimizer to eliminate this call if it can prove that the block never escapes except down the stack.
Definition at line 2305 of file CGObjC.cpp.
References Builder, CGM, emitARCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_retainBlock.
Referenced by EmitARCExtendBlockObject(), EmitARCRetain(), EmitARCRetainAutorelease(), and EmitARCStoreStrong().
EmitARCRetainNonBlock()
llvm::Value * CodeGenFunction::EmitARCRetainNonBlock (llvm::Value * value)
Retain the given object, with normal retain semantics.
call i8* @objc_retain(i8* value)
Definition at line 2293 of file CGObjC.cpp.
References CGM, emitARCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_retain.
Referenced by EmitARCRetain(), emitARCRetainCallResult(), clang::CodeGen::CGObjCRuntime::EmitInitOfCatchParam(), EmitObjCMessageExpr(), EmitParmDecl(), emitWriteback(), GenerateCopyHelperFunction(), and InitCatchParam().
EmitARCRetainScalarExpr()
llvm::Value * CodeGenFunction::EmitARCRetainScalarExpr (const Expr * expr)
EmitARCRetainScalarExpr - Semantically equivalent to EmitARCRetainObject(e->getType(), EmitScalarExpr(e)), but making a best-effort attempt to peephole expressions that naturally produce retained objects.
Definition at line 3448 of file CGObjC.cpp.
References EmitARCRetain(), clang::Expr::getType(), and tryEmitARCRetainScalarExpr().
Referenced by EmitScalarInit().
EmitARCStoreAutoreleasing()
std::pair< LValue, llvm::Value * > CodeGenFunction::EmitARCStoreAutoreleasing (const BinaryOperator * e)
Definition at line 3634 of file CGObjC.cpp.
References EmitARCRetainAutoreleaseScalarExpr(), EmitLValue(), EmitStoreOfScalar(), clang::BinaryOperator::getLHS(), and clang::BinaryOperator::getRHS().
Referenced by EmitBinaryOperatorLValue().
EmitARCStoreStrong() [1/2]
std::pair< LValue, llvm::Value * > CodeGenFunction::EmitARCStoreStrong (const BinaryOperator * e, bool ignored)
Definition at line 3603 of file CGObjC.cpp.
References EmitARCRelease(), EmitARCRetainBlock(), EmitARCStoreStrong(), EmitLoadOfScalar(), EmitLValue(), EmitStoreOfScalar(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::CodeGen::LValue::isARCPreciseLifetime(), clang::Type::isBlockPointerType(), and tryEmitARCRetainScalarExpr().
EmitARCStoreStrong() [2/2]
llvm::Value * CodeGenFunction::EmitARCStoreStrong (LValue dst, llvm::Value * newValue, bool ignored)
Store into a strong object.
Sometimes calls this: call void @objc_storeStrong(i8** addr, i8* value) Other times, breaks it down into components.
Definition at line 2500 of file CGObjC.cpp.
References EmitARCRelease(), EmitARCRetain(), EmitARCStoreStrongCall(), EmitLoadOfScalar(), EmitStoreOfScalar(), clang::CharUnits::fromQuantity(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getAlignment(), clang::CodeGen::LValue::getType(), clang::CodeGen::LValue::isARCPreciseLifetime(), clang::CharUnits::isZero(), clang::CodeGen::CodeGenTypeCache::PointerAlignInBytes, shouldUseFusedARCCalls(), and clang::ast_matchers::type.
Referenced by EmitARCStoreStrong(), and EmitBinaryOperatorLValue().
EmitARCStoreStrongCall()
llvm::Value * CodeGenFunction::EmitARCStoreStrongCall (Address addr, llvm::Value * value, bool ignored)
Store into a strong object.
Always calls this: call void @objc_storeStrong(i8** addr, i8* value)
Definition at line 2479 of file CGObjC.cpp.
References Builder, CGM, EmitNounwindRuntimeCall(), clang::CodeGen::Address::emitRawPointer(), getARCIntrinsic(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), clang::CodeGen::CodeGenTypeCache::Int8PtrPtrTy, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and clang::CodeGen::ObjCEntrypoints::objc_storeStrong.
Referenced by destroyARCStrongWithStore(), EmitARCDestroyStrong(), EmitARCStoreStrong(), EmitParmDecl(), and GenerateCopyHelperFunction().
EmitARCStoreUnsafeUnretained()
std::pair< LValue, llvm::Value * > CodeGenFunction::EmitARCStoreUnsafeUnretained (const BinaryOperator * e, bool ignored)
Definition at line 3584 of file CGObjC.cpp.
References EmitARCUnsafeUnretainedScalarExpr(), EmitLValue(), EmitScalarExpr(), EmitStoreOfScalar(), clang::BinaryOperator::getLHS(), and clang::BinaryOperator::getRHS().
EmitARCStoreWeak()
llvm::Value * CodeGenFunction::EmitARCStoreWeak (Address addr, llvm::Value * value, bool ignored)
i8* @objc_storeWeak(i8** addr, i8* value) Returns value.
Definition at line 2606 of file CGObjC.cpp.
References CGM, emitARCStoreOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_storeWeak.
Referenced by emitARCCopyAssignWeak(), emitARCMoveAssignWeak(), and EmitScalarInit().
EmitARCUnsafeClaimAutoreleasedReturnValue()
llvm::Value * CodeGenFunction::EmitARCUnsafeClaimAutoreleasedReturnValue (llvm::Value * value)
Claim a possibly-autoreleased return value at +0.
This is only valid to do in contexts which do not rely on the retain to keep the object valid for all of its uses; for example, when the value is ignored, or when it is being assigned to an __unsafe_unretained variable.
call i8* @objc_unsafeClaimAutoreleasedReturnValue(i8* value)
Definition at line 2430 of file CGObjC.cpp.
References emitOptimizedARCReturnCall().
Referenced by emitARCUnsafeClaimCallResult().
EmitARCUnsafeUnretainedScalarExpr()
llvm::Value * CodeGenFunction::EmitARCUnsafeUnretainedScalarExpr (const Expr * expr)
EmitARCUnsafeUnretainedScalarExpr - Semantically equivalent to immediately releasing the resut of EmitARCRetainScalarExpr, but avoiding any spurious retains, including by performing reclaims with objc_unsafeClaimAutoreleasedReturnValue.
Definition at line 3573 of file CGObjC.cpp.
References emitARCUnsafeUnretainedScalarExpr().
Referenced by EmitARCStoreUnsafeUnretained(), and EmitScalarInit().
EmitARMBuiltinExpr()
Value * CodeGenFunction::EmitARMBuiltinExpr (unsigned BuiltinID, const CallExpr * E, ReturnValueSlot ReturnValue, llvm::Triple::ArchType Arch)
Definition at line 8621 of file CGBuiltin.cpp.
References clang::Expr::EvaluateAsInt(), and clang::CallExpr::getArg().
Referenced by EmitTargetArchBuiltinExpr().
EmitARMCDEBuiltinExpr()
Value * CodeGenFunction::EmitARMCDEBuiltinExpr (unsigned BuiltinID, const CallExpr * E, ReturnValueSlot ReturnValue, llvm::Triple::ArchType Arch)
Definition at line 9528 of file CGBuiltin.cpp.
EmitARMMVEBuiltinExpr()
Value * CodeGenFunction::EmitARMMVEBuiltinExpr (unsigned BuiltinID, const CallExpr * E, ReturnValueSlot ReturnValue, llvm::Triple::ArchType Arch)
Definition at line 9427 of file CGBuiltin.cpp.
References clang::Function, clang::CallExpr::getArg(), clang::Expr::getType(), and ID.
emitArrayDestroy()
void CodeGenFunction::emitArrayDestroy (llvm::Value * begin, llvm::Value * end, QualType elementType, CharUnits elementAlign, Destroyer * destroyer, bool checkZeroLength, bool useEHCleanup)
emitArrayDestroy - Destroys all the elements of the given array, beginning from last to first.
The array cannot be zero-length.
Parameters
begin - a type* denoting the first element of the array
end - a type* denoting one past the end of the array
elementType - the element type of the array
destroyer - the function to call to destroy elements
useEHCleanup - whether to push an EH cleanup to destroy the remaining elements in case the destruction of a single element throws
Definition at line 2361 of file CGDecl.cpp.
References Builder, ConvertTypeForMem(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), EmitBlock(), clang::Type::isArrayType(), PopCleanupBlock(), pushRegularPartialArrayCleanup(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by EmitArrayDelete(), emitDestroy(), and emitPartialArrayDestroy().
emitArrayLength()
llvm::Value * CodeGenFunction::emitArrayLength (const ArrayType * arrayType, QualType & baseType, Address & addr)
emitArrayLength - Compute the length of an array, even if it's a VLA, and drill down to the base element type.
Computes the length of an array in elements, as well as the base element type and a properly-typed first element pointer.
Definition at line 2442 of file CodeGenFunction.cpp.
References clang::ast_matchers::arrayType, Builder, ConvertType(), ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::ASTContext::getAsArrayType(), getContext(), clang::CodeGen::Address::getElementType(), getVLASize(), clang::CodeGen::CodeGenFunction::VlaSizePair::NumElts, clang::CodeGen::CodeGenTypeCache::SizeTy, and clang::CodeGen::Address::withElementType().
Referenced by EmitAggregateCopy(), EmitCXXAggrConstructorCall(), emitDestroy(), EmitOMPAggregateInit(), and EmitOMPAggregateReduction().
EmitArraySubscriptExpr()
LValue CodeGenFunction::EmitArraySubscriptExpr (const ArraySubscriptExpr * E, bool Accessed = false)
Definition at line 4167 of file CGExpr.cpp.
References Array, clang::ast_matchers::arrayType, Builder, clang::Type::castAs(), CGM, ConvertType(), clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), emitArraySubscriptGEP(), EmitBoundsCheck(), EmitBoundsCheckImpl(), EmitExtVectorElementLValue(), EmitLValue(), EmitPointerWithAlignment(), clang::CodeGen::Address::emitRawPointer(), EmitScalarExpr(), FindCountedByField(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getAlignment(), getArrayElementAlign(), clang::Type::getAs(), clang::ArraySubscriptExpr::getBase(), clang::CodeGen::LValue::getBaseInfo(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::Address::getElementType(), clang::ArraySubscriptExpr::getExprLoc(), clang::ArraySubscriptExpr::getIdx(), clang::CodeGen::CodeGenTypeCache::getIntAlign(), getLangOpts(), clang::ArraySubscriptExpr::getLHS(), getOffsetDifferenceInBits(), clang::CharUnits::getQuantity(), clang::ArraySubscriptExpr::getRHS(), clang::CodeGen::CodeGenModule::getTBAAInfoForSubobject(), clang::Expr::getType(), clang::CodeGen::LValue::getType(), clang::ASTContext::getTypeSizeInChars(), getVLASize(), clang::SanitizerSet::has(), clang::Expr::IgnoreParenCasts(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::CodeGen::Address::invalid(), clang::Expr::isOBJCGCCandidate(), clang::Type::isSignedIntegerOrEnumerationType(), clang::CodeGen::LValue::isSimple(), isSimpleArrayDecayOperand(), clang::Type::isVectorType(), MakeAddrLValue(), clang::CodeGen::LValue::MakeVectorElt(), clang::LangOptionsBase::NonGC, clang::CodeGen::CodeGenFunction::VlaSizePair::NumElts, SanOpts, clang::CodeGen::LValue::setNonGC(), setObjCGCLValueClass(), and clang::ASTContext::toCharUnitsFromBits().
Referenced by EmitCheckedLValue(), and EmitOMPArraySectionExpr().
EmitArrayToPointerDecay()
Address CodeGenFunction::EmitArrayToPointerDecay (const Expr * Array, LValueBaseInfo * BaseInfo = nullptr, TBAAAccessInfo * TBAAInfo = nullptr)
Definition at line 3880 of file CGExpr.cpp.
References Builder, clang::Type::castAsArrayTypeUnsafe(), CGM, ConvertType(), ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstArrayGEP(), EmitLValue(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getBaseInfo(), clang::ArrayType::getElementType(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), clang::Expr::getType(), clang::Type::isArrayType(), clang::Type::isVariableArrayType(), and clang::CodeGen::Address::withElementType().
Referenced by EmitPointerWithAlignment().
EmitAsanPrologueOrEpilogue()
void CodeGenFunction::EmitAsanPrologueOrEpilogue (bool Prologue)
Definition at line 778 of file CGClass.cpp.
Referenced by EmitConstructorBody(), and EmitDestructorBody().
EmitAsmStmt()
void CodeGenFunction::EmitAsmStmt (const AsmStmt & S)
Definition at line 2529 of file CGStmt.cpp.
EmitAtomicCompareExchange()
std::pair< RValue, llvm::Value * > CodeGenFunction::EmitAtomicCompareExchange (LValue Obj, RValue Expected, RValue Desired, SourceLocation Loc, llvm::AtomicOrdering Success = llvm::AtomicOrdering::SequentiallyConsistent, llvm::AtomicOrdering Failure = llvm::AtomicOrdering::SequentiallyConsistent, bool IsWeak = false, AggValueSlot Slot = AggValueSlot::ignored())
Emit a compare-and-exchange op for atomic type.
Definition at line 2020 of file CGAtomic.cpp.
References clang::CodeGen::LValue::getAddress(), clang::CodeGen::RValue::getAggregateAddress(), clang::CodeGen::Address::getElementType(), and clang::CodeGen::RValue::isAggregate().
EmitAtomicExpr()
RValue CodeGenFunction::EmitAtomicExpr (AtomicExpr * E)
Definition at line 818 of file CGAtomic.cpp.
References clang::CodeGen::CallArgList::add(), clang::ASTContext::BoolTy, Builder, CGM, convertTempToRValue(), ConvertTypeForMem(), createBasicBlock(), CreateMemTemp(), CurFn, EmitAtomicInit(), emitAtomicLibcall(), EmitAtomicOp(), EmitPointerWithAlignment(), clang::CodeGen::Address::emitRawPointer(), EmitScalarExpr(), EmitStoreOfScalar(), EmitValToTemp(), clang::CodeGen::RValue::get(), clang::CodeGen::Address::getAlignment(), clang::Type::getAs(), clang::AtomicExpr::getBeginLoc(), getContext(), clang::CodeGen::CodeGenModule::getDiags(), clang::Expr::getExprLoc(), getLLVMContext(), clang::TargetInfo::getMaxAtomicInlineWidth(), clang::AtomicExpr::getOp(), clang::AtomicExpr::getOrder(), clang::AtomicExpr::getOrderFail(), clang::Type::getPointeeType(), clang::AtomicExpr::getPtr(), clang::CharUnits::getQuantity(), clang::AtomicExpr::getScope(), clang::AtomicExpr::getScopeModel(), clang::CodeGen::CodeGenModule::getSize(), clang::ASTContext::getSizeType(), getTarget(), clang::ASTContext::getTargetAddressSpace(), getTargetHooks(), clang::Expr::getType(), clang::ASTContext::getTypeInfoInChars(), clang::ASTContext::getTypeSizeInChars(), clang::QualType::getUnqualifiedType(), clang::AtomicExpr::getVal1(), clang::AtomicExpr::getVal2(), clang::AtomicExpr::getWeak(), int, clang::CodeGen::CodeGenTypeCache::IntTy, clang::CodeGen::Address::invalid(), clang::AtomicExpr::isCmpXChg(), clang::Type::isFloatingType(), clang::AtomicExpr::isOpenCL(), clang::Type::isPointerType(), clang::CodeGen::Address::isValid(), clang::Type::isVoidType(), MakeAddrLValue(), clang::opencl_generic, clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), clang::DiagnosticsEngine::Report(), clang::CodeGen::CodeGenTypeCache::SizeTy, clang::ASTContext::toBits(), clang::ASTContext::toCharUnitsFromBits(), V, clang::CodeGen::CodeGenTypeCache::VoidPtrTy, clang::ASTContext::VoidTy, and clang::CodeGen::Address::withElementType().
EmitAtomicInit()
void CodeGenFunction::EmitAtomicInit (Expr * E, LValue lvalue)
Definition at line 2045 of file CGAtomic.cpp.
References clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, EmitAggExpr(), EmitComplexExpr(), EmitScalarExpr(), clang::CodeGen::AggValueSlot::forLValue(), clang::CodeGen::RValue::get(), clang::CodeGen::RValue::getComplex(), clang::Expr::getType(), clang::Type::isAtomicType(), clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::AggValueSlot::IsNotDestructed, clang::CodeGen::AggValueSlot::IsNotZeroed, clang::CodeGen::AggValueSlot::IsZeroed, clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
Referenced by EmitAtomicExpr(), and EmitExprAsInit().
EmitAtomicLoad() [1/2]
RValue CodeGenFunction::EmitAtomicLoad (LValue LV, SourceLocation SL, AggValueSlot Slot = AggValueSlot::ignored())
Definition at line 1506 of file CGAtomic.cpp.
References clang::CodeGen::LValue::getType(), clang::Type::isAtomicType(), and clang::CodeGen::LValue::isVolatileQualified().
Referenced by EmitLoadOfScalar(), and emitSimpleAtomicLoad().
EmitAtomicLoad() [2/2]
RValue CodeGenFunction::EmitAtomicLoad (LValue src, SourceLocation loc, llvm::AtomicOrdering AO, bool IsVolatile = false, AggValueSlot resultSlot = AggValueSlot::ignored())
Emit a load from an l-value of atomic type.
Note that the r-value we produce is an r-value of the atomic value type.
Definition at line 1552 of file CGAtomic.cpp.
EmitAtomicStore() [1/2]
void CodeGenFunction::EmitAtomicStore (RValue rvalue, LValue lvalue, bool isInit)
Definition at line 1930 of file CGAtomic.cpp.
References clang::CodeGen::LValue::getType(), clang::Type::isAtomicType(), and clang::CodeGen::LValue::isVolatileQualified().
Referenced by clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), emitSimpleAtomicStore(), and EmitStoreOfScalar().
EmitAtomicStore() [2/2]
void CodeGenFunction::EmitAtomicStore (RValue rvalue, LValue dest, llvm::AtomicOrdering AO, bool IsVolatile, bool isInit)
Emit a store to an l-value of atomic type.
Note that the r-value is expected to be an r-value of the atomic type; this means that for aggregate r-values, it should include storage for any padding that was necessary.
Definition at line 1948 of file CGAtomic.cpp.
References clang::CodeGen::CallArgList::add(), Builder, CGM, clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenModule::DecorateInstructionWithTBAA(), emitAtomicLibcall(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::RValue::getAggregateAddress(), getContext(), clang::CodeGen::Address::getElementType(), clang::CodeGen::LValue::getTBAAInfo(), clang::Value::getType(), clang::CodeGen::CodeGenTypeCache::IntTy, clang::CodeGen::RValue::isAggregate(), clang::CodeGen::LValue::isSimple(), shouldCastToInt(), clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
EmitAtomicUpdate()
void CodeGenFunction::EmitAtomicUpdate (LValue LVal, llvm::AtomicOrdering AO, const llvm::function_ref< RValue(RValue)> & UpdateOp, bool IsVolatile)
Definition at line 2038 of file CGAtomic.cpp.
Referenced by EmitOMPAtomicSimpleUpdateExpr().
EmitAttributedStmt()
void CodeGenFunction::EmitAttributedStmt (const AttributedStmt & S)
Definition at line 712 of file CGStmt.cpp.
EmitAutoVarAlloca()
CodeGenFunction::AutoVarEmission CodeGenFunction::EmitAutoVarAlloca (const VarDecl & D)
EmitAutoVarAlloca - Emit the alloca and debug information for a local variable.
Does not emit initialization or destruction.
Definition at line 1479 of file CGDecl.cpp.
References Builder, Bypasses, CGM, ConvertTypeForMem(), clang::CPlusPlus, clang::CodeGen::CGBuilderTy::CreateStore(), CreateTempAlloca(), clang::CodeGen::Decl, clang::Default, clang::QualType::DK_cxx_destructor, EmitLifetimeStart(), clang::CodeGen::Address::emitRawPointer(), EmitStaticVarDecl(), EmitVariablyModifiedType(), EnsureInsertPoint(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::QualType::getAddressSpace(), clang::CodeGen::Address::getAlignment(), clang::Type::getAs(), getBlockByrefInfo(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::TargetInfo::getCXXABI(), clang::CodeGen::CodeGenModule::getDataLayout(), getDebugInfo(), clang::ASTContext::getDeclAlign(), clang::CodeGen::Address::getElementType(), clang::VarDecl::getInit(), clang::CodeGen::CGOpenMPRuntime::getKmpcAllocShared(), getLangOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::NamedDecl::getName(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::RawAddress::getPointer(), getTarget(), clang::ValueDecl::getType(), hasLabelBeenSeenInCurrentScope(), clang::CodeGenOptions::hasReducedDebugInfo(), HaveInsertPoint(), clang::CodeGen::RawAddress::invalid(), clang::CodeGen::Address::invalid(), clang::Type::isArrayType(), clang::CodeGen::VarBypassDetector::IsBypassed(), clang::Expr::isConstantInitializer(), clang::Type::isConstantSizeType(), clang::QualType::isConstantStorage(), clang::VarDecl::isConstexpr(), clang::VarDecl::isEscapingByref(), clang::VarDecl::isExceptionVariable(), clang::TargetCXXABI::isMicrosoft(), clang::VarDecl::isNRVOVariable(), clang::QualType::isPODType(), clang::Type::isRecordType(), clang::CodeGen::Address::isValid(), clang::Type::isVariablyModifiedType(), MakeAddrLValue(), clang::VarDecl::needsDestruction(), clang::CodeGen::NormalCleanup, NRVOFlags, clang::CharUnits::One(), clang::OpenCL, clang::opencl_constant, clang::opencl_private, pushKmpcAllocFree(), ReturnValue, and clang::CodeGen::CodeGenFunction::AutoVarEmission::useLifetimeMarkers().
Referenced by EmitAutoVarDecl(), getNumThreads(), and clang::CodeGen::CGOpenMPRuntime::getNumThreadsExprForTargetDirective().
EmitAutoVarCleanups()
void CodeGenFunction::EmitAutoVarCleanups (const AutoVarEmission & emission)
Definition at line 2167 of file CGDecl.cpp.
References clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration(), clang::CodeGen::BLOCK_FIELD_IS_BYREF, clang::CodeGen::BLOCK_FIELD_IS_WEAK, CGM, cxxDestructorCanThrow(), EHStack, emitAutoVarTypeCleanup(), enterByrefCleanup(), clang::LangOptionsBase::GCOnly, clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::Decl::getAttr(), getContext(), getLangOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::Decl::hasAttr(), HaveInsertPoint(), clang::QualType::isObjCGCWeak(), clang::VarDecl::needsDestruction(), clang::LangOptionsBase::NonGC, clang::CodeGen::NormalAndEHCleanup, and clang::CodeGen::NormalCleanup.
Referenced by EmitAutoVarDecl(), getNumThreads(), and clang::CodeGen::CGOpenMPRuntime::getNumThreadsExprForTargetDirective().
EmitAutoVarDecl()
void CodeGenFunction::EmitAutoVarDecl (const VarDecl & D)
EmitAutoVarDecl - Emit an auto variable declaration.
EmitAutoVarDecl - Emit code and set up an entry in LocalDeclMap for a variable declaration with auto, register, or no storage class specifier.
This function can be called with a null (unreachable) insert point.
These turn into simple stack objects, or GlobalValues depending on target.
Definition at line 1379 of file CGDecl.cpp.
References clang::CodeGen::CGSYCLRuntime::actOnAutoVarEmit(), CGM, EmitAutoVarAlloca(), EmitAutoVarCleanups(), EmitAutoVarInit(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenFunction::AutoVarEmission::getOriginalAllocatedAddress(), clang::CodeGen::RawAddress::getPointer(), clang::CodeGen::CodeGenModule::getSYCLRuntime(), and clang::VarDecl::isNRVOVariable().
Referenced by EmitVarDecl().
EmitAutoVarInit()
void CodeGenFunction::EmitAutoVarInit (const AutoVarEmission & emission)
Definition at line 1935 of file CGDecl.cpp.
References Builder, CGM, constWithPadding(), ContainsLabel(), clang::CodeGen::ApplyDebugLocation::CreateDefaultArtificial(), defaultInitNonTrivialCStructVar(), drillIntoBlockVariable(), emitBlockByrefAddress(), emitByrefStructureInit(), EmitExprAsInit(), emitStoresForConstant(), EmitStoreThroughLValue(), EnsureInsertPoint(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenFunction::AutoVarEmission::getAllocatedAddress(), clang::Decl::getAttr(), getContext(), clang::VarDecl::getInit(), clang::ASTContext::getLangOpts(), clang::Decl::getLocation(), clang::CodeGen::CodeGenFunction::AutoVarEmission::getObjectAddress(), clang::ValueDecl::getType(), HaveInsertPoint(), clang::CodeGen::CodeGenTypeCache::Int8Ty, isCapturedBy(), clang::VarDecl::isConstexpr(), isTrivialInitializer(), MakeAddrLValue(), clang::VarDecl::mightBeUsableInConstantExpressions(), No, clang::LangOptionsBase::Pattern, clang::QualType::PDIK_Struct, replaceUndef(), clang::CodeGen::LValue::setNonGC(), clang::CodeGen::ConstantEmitter::tryEmitAbstractForInitializer(), clang::ast_matchers::type, clang::LangOptionsBase::Uninitialized, clang::CodeGen::Address::withElementType(), and Yes.
Referenced by EmitAutoVarDecl().
emitAutoVarTypeCleanup()
void CodeGenFunction::emitAutoVarTypeCleanup (const AutoVarEmission & emission, QualType::DestructionKind dtorKind)
Enter a destroy cleanup for the given local variable.
Definition at line 2100 of file CGDecl.cpp.
References destroyARCStrongImprecise, destroyNonTrivialCStruct, clang::QualType::DK_cxx_destructor, clang::QualType::DK_none, clang::QualType::DK_nontrivial_c_struct, clang::QualType::DK_objc_strong_lifetime, clang::QualType::DK_objc_weak_lifetime, clang::CodeGen::EHCleanup, EHStack, getARCCleanupKind(), getDestroyer(), clang::CodeGen::CodeGenFunction::AutoVarEmission::getObjectAddress(), clang::CodeGen::NormalAndEHCleanup, clang::ast_matchers::type, and clang::dataflow::var().
Referenced by EmitAutoVarCleanups().
EmitBinaryOperatorLValue()
LValue CodeGenFunction::EmitBinaryOperatorLValue (const BinaryOperator * E)
Definition at line 5614 of file CGExpr.cpp.
References CGM, clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), EmitAggExprToLValue(), EmitAnyExpr(), EmitARCStoreAutoreleasing(), EmitARCStoreStrong(), EmitBitfieldConversionCheck(), EmitCheckedLValue(), EmitComplexAssignmentLValue(), EmitIgnoredExpr(), EmitLValue(), EmitNullabilityCheck(), EmitPointerToDataMemberBinaryExpr(), EmitStoreThroughBitfieldLValue(), EmitStoreThroughLValue(), EmitWithOriginalRHSBitfieldAssignment(), EnsureInsertPoint(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getBitFieldInfo(), getEvaluationKind(), clang::BinaryOperator::getExprLoc(), getLangOpts(), clang::BinaryOperator::getLHS(), clang::QualType::getObjCLifetime(), clang::BinaryOperator::getOpcode(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::BinaryOperator::getRHS(), clang::CodeGen::RValue::getScalarVal(), clang::Expr::getType(), clang::SanitizerSet::has(), clang::CodeGen::LValue::isBitField(), clang::CodeGen::RValue::isScalar(), clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, Previous, clang::Expr::refersToBitField(), SanOpts, TCK_Store, clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
EmitBitfieldConversionCheck()
void CodeGenFunction::EmitBitfieldConversionCheck (llvm::Value * Src, QualType SrcType, llvm::Value * Dst, QualType DstType, const CGBitFieldInfo & Info, SourceLocation Loc)
Emit a check that an [implicit] conversion of a bitfield.
It is not UB, so we use the value after conversion.
Definition at line 1311 of file CGExprScalar.cpp.
References Builder, ConvertType(), EmitBitfieldSignChangeCheckHelper(), EmitBitfieldTruncationCheckHelper(), EmitCheck(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), clang::Value::getType(), clang::SanitizerSet::has(), clang::Type::isBooleanType(), clang::Type::isSignedIntegerOrEnumerationType(), PromotionIsPotentiallyEligibleForImplicitIntegerConversionCheck(), SanOpts, and clang::CodeGen::CGBitFieldInfo::Size.
Referenced by EmitBinaryOperatorLValue().
EmitBlock()
void CodeGenFunction::EmitBlock (llvm::BasicBlock * BB, bool IsFinished = false)
EmitBlock - Emit the given block.
BB and set it as the insert point, adding a fall-through branch from the current insert block if necessary. It is legal to call this function even if there is no current insertion point.
IsFinished - If true, indicates that the caller has finished emitting branches to the given block and does not expect to emit code into it. This means the block can be ignored if it is unreachable.
Definition at line 578 of file CGStmt.cpp.
References Builder, CurFn, and EmitBranch().
Referenced by clang::CodeGen::CatchRetScope::Emit(), emitArrayDestroy(), EmitBranchOnBoolExpr(), EmitBranchToCounterBlock(), EmitCall(), emitCatchDispatchBlock(), EmitCfiSlowPathCheck(), EmitCheck(), EmitCleanup(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), EmitCtorPrologue(), clang::CodeGen::CGCUDARuntime::EmitCUDAKernelCallExpr(), EmitCXXAggrConstructorCall(), EmitCXXDeleteExpr(), EmitCXXNewExpr(), EmitDynamicCast(), emitFilterDispatchBlock(), clang::CodeGen::CGOpenMPRuntime::emitIfClause(), emitInterWarpCopyFunction(), EmitLabel(), EmitLandingPad(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), EmitMustTailThunk(), EmitNewArrayInitializer(), emitNonZeroVLAInit(), EmitObjectDelete(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), emitPostUpdateForReductionClause(), EmitReturnBlock(), EmitReturnValueCheck(), EmitSehScope(), emitShuffleAndReduceFunction(), EmitTrapCheck(), EmitTypeCheck(), EmitTypeidFromVTable(), clang::CodeGen::CGOpenMPRuntime::emitUDMapperArrayInitOrDel(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), EmitVTablePtrCheckForCast(), emitWasmCatchPadBlock(), emitWriteback(), emitWritebackArg(), EnsureInsertPoint(), clang::CodeGen::CodeGenFunction::FinallyInfo::exit(), FinishFunction(), GenerateCXXGlobalInitFunc(), GetAddressOfBaseClass(), GetAddressOfDerivedClass(), PerformReturnAdjustment(), and shuffleAndStore().
EmitBlockAfterUses()
void CodeGenFunction::EmitBlockAfterUses (llvm::BasicBlock * BB)
EmitBlockAfterUses - Emit the given block somewhere hopefully near its uses, and leave the insertion point in it.
Definition at line 615 of file CGStmt.cpp.
References Builder, and CurFn.
Referenced by emitCatchDispatchBlock(), emitCatchPadBlock(), emitFilterDispatchBlock(), and emitWasmCatchPadBlock().
emitBlockByrefAddress() [1/2]
Address CodeGenFunction::emitBlockByrefAddress (Address baseAddr, const BlockByrefInfo & info, bool followForward, const llvm::Twine & name)
Definition at line 2547 of file CGBlocks.cpp.
References Builder, clang::CodeGen::BlockByrefInfo::ByrefAlignment, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), clang::CodeGen::BlockByrefInfo::FieldIndex, clang::transformer::name(), and clang::CodeGen::BlockByrefInfo::Type.
emitBlockByrefAddress() [2/2]
Address CodeGenFunction::emitBlockByrefAddress (Address baseAddr, const VarDecl * V, bool followForward = true)
BuildBlockByrefAddress - Computes the location of the data in a variable which is declared as __block.
Definition at line 2540 of file CGBlocks.cpp.
References getBlockByrefInfo(), and clang::dataflow::var().
Referenced by drillIntoBlockVariable(), EmitAutoVarInit(), EmitDeclRefLValue(), EmitScalarInit(), GetAddrOfBlockDecl(), and clang::CodeGen::CodeGenFunction::AutoVarEmission::getObjectAddress().
EmitBlockCallExpr()
RValue CodeGenFunction::EmitBlockCallExpr (const CallExpr * E, ReturnValueSlot ReturnValue)
Definition at line 1156 of file CGBlocks.cpp.
References clang::CodeGen::CallArgList::add(), clang::CallExpr::arguments(), clang::CodeGen::CodeGenTypes::arrangeBlockFunctionCall(), Builder, clang::Type::castAs(), CGM, clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), EmitCall(), EmitCallArgs(), EmitScalarExpr(), clang::Func, clang::CodeGen::RValue::get(), clang::ASTContext::getAddrSpaceQualType(), clang::Type::getAs(), clang::CallExpr::getCallee(), clang::CallExpr::getCalleeDecl(), getContext(), clang::CodeGen::CodeGenModule::getGenericBlockLiteralType(), clang::CodeGen::CGOpenCLRuntime::getGenericVoidPointerType(), clang::CodeGen::CGOpenCLRuntime::getInvokeFunction(), getLangOpts(), clang::CodeGen::CodeGenModule::getOpenCLRuntime(), clang::Type::getPointeeType(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::ASTContext::getPointerType(), clang::Expr::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::OpenCL, clang::opencl_generic, ReturnValue, clang::CodeGen::CodeGenTypeCache::UnqualPtrTy, clang::ASTContext::VoidPtrTy, clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by EmitCallExpr().
EmitBlockCopyAndAutorelease()
llvm::Value * CodeGenFunction::EmitBlockCopyAndAutorelease (llvm::Value * Block, QualType Ty)
Definition at line 3908 of file CGObjC.cpp.
References Block, CGM, clang::CodeGen::CGObjCRuntime::GenerateMessageSend(), clang::IdentifierTable::get(), getContext(), clang::SelectorTable::getNullarySelector(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::ASTContext::Idents, and clang::ASTContext::Selectors.
EmitBlockLiteral()
llvm::Value * CodeGenFunction::EmitBlockLiteral (const BlockExpr * blockExpr)
Emit block literal.
Emit a block literal expression in the current function.
Returns
an LLVM value which is a pointer to a struct which contains information about the block, including the block invoke function, the captured variables, etc.
Definition at line 759 of file CGBlocks.cpp.
References Block, clang::CodeGen::CGBlockInfo::BlockAlign, clang::ast_matchers::blockExpr, clang::CodeGen::CGBlockInfo::BlockExpression, clang::CodeGen::CGBlockInfo::CanBeGlobal, CGM, computeBlockInfo(), CreateTempAlloca(), CurFn, clang::CodeGen::CodeGenModule::getAddrOfGlobalBlockIfEmitted(), clang::CodeGen::CGBlockInfo::LocalAddress, and clang::CodeGen::CGBlockInfo::StructureType.
EmitBlockWithFallThrough()
void CodeGenFunction::EmitBlockWithFallThrough (llvm::BasicBlock * BB, const Stmt * S)
When instrumenting to collect profile data, the counts for some blocks such as switch cases need to not include the fall-through counts, so emit a branch around the instrumentation code.
When not instrumenting, this just calls EmitBlock().
Definition at line 1528 of file CodeGenFunction.cpp.
emitBoolVecConversion()
llvm::Value * CodeGenFunction::emitBoolVecConversion (llvm::Value * SrcVec, unsigned NumElementsDst, const llvm::Twine & Name = "")
Definition at line 3375 of file CodeGenFunction.cpp.
Referenced by EmitFromMemory(), EmitLoadOfScalar(), and EmitStoreOfScalar().
EmitBoundsCheck()
void CodeGenFunction::EmitBoundsCheck (const Expr * E, const Expr * Base, llvm::Value * Index, QualType IndexType, bool Accessed)
Emit a check that Base points into an array object, which we can access at index Index.
Accessed should be false if we this expression is used as an lvalue, for instance in "&Arr[Idx]".
Definition at line 1162 of file CGExpr.cpp.
Referenced by EmitArraySubscriptExpr(), and emitPointerArithmetic().
EmitBoundsCheckImpl()
void CodeGenFunction::EmitBoundsCheckImpl (const Expr * E, llvm::Value * Bound, llvm::Value * Index, QualType IndexType, QualType IndexedType, bool Accessed)
Definition at line 1176 of file CGExpr.cpp.
Referenced by EmitArraySubscriptExpr().
EmitBPFBuiltinExpr()
Value * CodeGenFunction::EmitBPFBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 13513 of file CGBuiltin.cpp.
References clang::CallExpr::getArg(), clang::Expr::getExprLoc(), clang::Expr::getObjectKind(), clang::Expr::IgnoreParens(), and clang::OK_BitField.
Referenced by EmitTargetArchBuiltinExpr().
EmitBranch()
void CodeGenFunction::EmitBranch (llvm::BasicBlock * Block)
EmitBranch - Emit a branch to the specified basic block from the current insert block, taking care to avoid creation of branches from dummy blocks.
It is legal to call this function even if there is no current insertion point.
This function clears the current insertion point. The caller should follow calls to this function with calls to Emit*Block prior to generation new code.
Definition at line 598 of file CGStmt.cpp.
References Builder.
Referenced by EmitBlock(), EmitBranchToCounterBlock(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), clang::CodeGen::CGCUDARuntime::EmitCUDAKernelCallExpr(), EmitDynamicCast(), clang::CodeGen::CGOpenMPRuntime::emitIfClause(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), and shuffleAndStore().
EmitBranchOnBoolExpr()
void CodeGenFunction::EmitBranchOnBoolExpr (const Expr * Cond, llvm::BasicBlock * TrueBlock, llvm::BasicBlock * FalseBlock, uint64_t TrueCount, Stmt::Likelihood LH = Stmt::LH_None, const Expr * ConditionalOp = nullptr)
EmitBranchOnBoolExpr - Emit a branch on a boolean condition (e.g.
for an if statement) to the specified blocks. Based on the condition, this might try to simplify the codegen of the conditional based on the branch. TrueCount should be the number of times we expect the condition to evaluate to true based on PGO data.
for an if statement) to the specified blocks. Based on the condition, this might try to simplify the codegen of the conditional based on the branch.
Parameters
LH The value of the likelihood attribute on the True branch.
ConditionalOp Used by MC/DC code coverage to track the result of the ConditionalOperator (ternary) through a recursive call for the operator's LHS and RHS nodes.
Definition at line 2038 of file CodeGenFunction.cpp.
References clang::CodeGen::CodeGenFunction::ConditionalEvaluation::begin(), Builder, CGM, ConstantFoldsToSimpleInteger(), createBasicBlock(), double, EmitBlock(), EmitBranchToCounterBlock(), EmitCXXThrowExpr(), clang::CodeGen::CodeGenFunction::ConditionalEvaluation::end(), EvaluateExprAsBool(), clang::FunctionDecl::getBuiltinID(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getCurrentProfileCount(), getLLVMContext(), getProfileCount(), clang::CodeGenOptions::hasProfileClangInstr(), clang::Expr::IgnoreImpCasts(), clang::Expr::IgnoreParens(), incrementProfileCounter(), isInstrumentedCondition(), clang::Stmt::LH_Likely, clang::Stmt::LH_None, clang::Stmt::LH_Unlikely, max(), maybeUpdateMCDCCondBitmap(), MCDCLogOpStack, and setCurrentProfileCount().
Referenced by EmitBranchToCounterBlock(), clang::CodeGen::CGCUDARuntime::EmitCUDAKernelCallExpr(), and clang::CodeGen::CGOpenMPRuntime::emitIfClause().
EmitBranchThroughCleanup()
void CodeGenFunction::EmitBranchThroughCleanup (JumpDest Dest)
EmitBranchThroughCleanup - Emit a branch from the current insert block through the normal cleanup handling code (if any) and then on to.
Terminate the current block by emitting a branch which might leave the current cleanup-protected scope.
Dest.
The target scope may not yet be known, in which case this will require a fixup.
As a side-effect, this method clears the insertion point.
Definition at line 1070 of file CGCleanup.cpp.
References clang::CodeGen::EHScopeStack::stable_iterator::encloses(), and clang::CodeGen::CodeGenFunction::JumpDest::getScopeDepth().
Referenced by EmitForwardingCallToLambda(), EnterDtorCleanups(), clang::CodeGen::CodeGenFunction::FinallyInfo::exit(), and clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::FinalizeOMPRegion().
EmitBranchToCounterBlock()
void CodeGenFunction::EmitBranchToCounterBlock (const Expr * Cond, BinaryOperator::Opcode LOp, llvm::BasicBlock * TrueBlock, llvm::BasicBlock * FalseBlock, uint64_t TrueCount = 0, Stmt::Likelihood LH = Stmt::LH_None, const Expr * CntrIdx = nullptr)
EmitBranchToCounterBlock - Emit a conditional branch to a new block that increments a profile counter based on the semantics of the given logical operator opcode.
This is used to instrument branch condition coverage for logical operators.
Definition at line 1964 of file CodeGenFunction.cpp.
References CGM, createBasicBlock(), EmitBlock(), EmitBranch(), EmitBranchOnBoolExpr(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGenOptions::hasProfileClangInstr(), incrementProfileCounter(), and isInstrumentedCondition().
Referenced by EmitBranchOnBoolExpr().
EmitBreakStmt()
void CodeGenFunction::EmitBreakStmt (const BreakStmt & S)
Definition at line 1486 of file CGStmt.cpp.
EmitBuiltinAlignTo()
RValue CodeGenFunction::EmitBuiltinAlignTo (const CallExpr * E, bool AlignUp)
Emit IR for __builtin_align_up/__builtin_align_down.
Generate (x & ~(y-1)) to align down or ((x+(y-1)) & ~(y-1)) to align up.
Note: For pointer types we can avoid ptrtoint/inttoptr pairs by using the llvm.ptrmask intrinsic (with a GEP before in the align_up case).
Definition at line 22769 of file CGBuiltin.cpp.
EmitBuiltinAvailable()
llvm::Value * CodeGenFunction::EmitBuiltinAvailable (const VersionTuple & Version)
Definition at line 3988 of file CGObjC.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), emitIsPlatformVersionAtLeast(), EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTriple(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenModule::IsOSVersionAtLeastFn, and clang::Min.
EmitBuiltinExpr()
RValue CodeGenFunction::EmitBuiltinExpr (const GlobalDecl GD, unsigned BuiltinID, const CallExpr * E, ReturnValueSlot ReturnValue)
Definition at line 2694 of file CGBuiltin.cpp.
References ceil, copysign, cos, emitBinaryBuiltin(), emitUnaryMaybeConstrainedFPBuiltin(), clang::Expr::EvaluateAsRValue(), exp, exp2, clang::CodeGen::RValue::get(), clang::Decl::getAsFunction(), clang::GlobalDecl::getDecl(), clang::CallExpr::getFPFeatures(), clang::Decl::hasAttr(), clang::CallExpr::hasStoredFPFeatures(), clang::Expr::isPRValue(), and mutateLongDoubleBuiltin().
Referenced by EmitCallExpr().
EmitBuiltinIsAligned()
RValue CodeGenFunction::EmitBuiltinIsAligned (const CallExpr * E)
Emit IR for __builtin_is_aligned.
Generate (x & (y-1)) == 0.
Definition at line 22755 of file CGBuiltin.cpp.
EmitBuiltinNewDeleteCall()
RValue CodeGenFunction::EmitBuiltinNewDeleteCall (const FunctionProtoType * Type, const CallExpr * TheCallExpr, bool IsDelete)
Definition at line 1357 of file CGExprCXX.cpp.
References clang::CallExpr::arguments(), EmitCallArgs(), and getContext().
emitBuiltinOSLogFormat()
RValue CodeGenFunction::emitBuiltinOSLogFormat (const CallExpr & E)
Emit IR for __builtin_os_log_format.
Definition at line 2318 of file CGBuiltin.cpp.
References clang::CodeGen::CallArgList::add(), clang::analyze_os_log::computeOSLogBufferLayout(), EmitPointerWithAlignment(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::RValue::get(), clang::CallExpr::getArg(), clang::CallExpr::getNumArgs(), clang::Expr::IgnoreParenCasts(), clang::CodeGen::RawAddress::invalid(), clang::analyze_os_log::OSLogBufferLayout::Items, clang::analyze_os_log::OSLogBufferItem::MaskKind, clang::CodeGen::TEK_Scalar, and clang::ASTContext::VoidPtrTy.
emitByrefStructureInit()
void CodeGenFunction::emitByrefStructureInit (const AutoVarEmission & emission)
Initialize the structural components of a __block variable, i.e.
everything but the actual object.
Definition at line 2664 of file CGBlocks.cpp.
References clang::CodeGen::BLOCK_BYREF_HAS_COPY_DISPOSE, clang::CodeGen::BLOCK_BYREF_LAYOUT_EXTENDED, clang::CodeGen::BLOCK_BYREF_LAYOUT_MASK, clang::CodeGen::BLOCK_BYREF_LAYOUT_NON_OBJECT, clang::CodeGen::BLOCK_BYREF_LAYOUT_STRONG, clang::CodeGen::BLOCK_BYREF_LAYOUT_UNRETAINED, clang::CodeGen::BLOCK_BYREF_LAYOUT_WEAK, clang::CodeGen::CGObjCRuntime::BuildByrefLayout(), Builder, CGM, clang::CodeGen::BlockByrefHelpers::CopyHelper, clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), clang::CodeGen::BlockByrefHelpers::DisposeHelper, clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::BlockFlags::getBitMask(), clang::ASTContext::getByrefLifetime(), getContext(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenTypeCache::getIntSize(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::CodeGenTypeCache::getPointerSize(), clang::CharUnits::getQuantity(), clang::CodeGen::CodeGenModule::GetTargetTypeStoreSize(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenTypeCache::IntTy, clang::isa(), clang::transformer::name(), clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, printf(), clang::ast_matchers::type, and V.
Referenced by EmitAutoVarInit().
EmitCall() [1/3]
RValue CodeGenFunction::EmitCall (const CGFunctionInfo & CallInfo, const CGCallee & Callee, ReturnValueSlot ReturnValue, const CallArgList & Args, llvm::CallBase ** callOrInvoke, bool IsMustTail, SourceLocation Loc)
EmitCall - Generate a call of the given function, expecting the given result type, and using the given argument list which specifies both the LLVM arguments and the types they were derived from.
Definition at line 5099 of file CGCall.cpp.
References addControlledConvergenceToken(), clang::CodeGen::CGDebugInfo::addHeapAllocSiteMetadata(), clang::CodeGen::CodeGenModule::AdjustMemoryAttribute(), clang::CodeGen::CGFunctionInfo::arg_begin(), clang::CodeGen::CGFunctionInfo::arg_size(), Builder, CGM, clang::CodeGen::TargetCodeGenInfo::checkFunctionCallABI(), checkTargetFeatures(), clang::CodeGen::ABIArgInfo::CoerceAndExpand, clang::CodeGen::CodeGenModule::ConstructAttributeList(), convertTempToRValue(), ConvertType(), ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateAddrSpaceCast(), createBasicBlock(), CreateCoercedLoad(), CreateCoercedStore(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), CreateMemTemp(), CreateMemTempWithoutCast(), clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), CreateTempAlloca(), CurCodeDecl, CurFuncDecl, CurrentCleanupScopeDepth, currentFunctionUsesSEHTry(), deactivateArgCleanupsBeforeCall(), clang::Default, clang::CodeGen::ABIArgInfo::Direct, clang::QualType::DK_nontrivial_c_struct, EHStack, emitAddressAtOffset(), EmitAggregateStore(), EmitBlock(), EmitCMSEClearRecord(), EmitKCFIOperandBundle(), EmitLifetimeEnd(), EmitLifetimeStart(), EmitNounwindRuntimeCall(), clang::CodeGen::Address::emitRawPointer(), EmitUnreachable(), emitWritebacks(), clang::CodeGen::EHScopeStack::end(), EnsureInsertPoint(), clang::CodeGen::CodeGenModule::Error(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::ABIArgInfo::Expand, clang::CodeGen::ABIArgInfo::Extend, clang::CodeGen::EHScopeStack::find(), clang::CodeGen::CallArgList::freeArgumentMemory(), clang::CharUnits::fromQuantity(), clang::CodeGen::EHPersonality::get(), clang::CodeGen::RValue::get(), clang::FunctionType::ExtParameterInfo::getABI(), clang::CodeGen::LValue::getAddressSpace(), clang::CodeGen::RValue::getAggregate(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::LValue::getAlignment(), clang::CodeGen::CGFunctionInfo::getArgStruct(), clang::CodeGen::CGFunctionInfo::getArgStructAlignment(), clang::CharUnits::getAsAlign(), getAsNaturalPointerTo(), clang::CodeGen::CodeGenTypeCache::getASTAllocaAddressSpace(), getBundlesForFunclet(), clang::CodeGen::ABIArgInfo::getCanBeFlattened(), clang::CodeGen::EHCleanupScope::getCleanup(), clang::CodeGen::CallArgList::getCleanupsToDeactivate(), clang::CodeGen::ABIArgInfo::getCoerceAndExpandType(), clang::CodeGen::ABIArgInfo::getCoerceToType(), clang::CodeGen::RValue::getComplex(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), getDebugInfo(), clang::CodeGen::ABIArgInfo::getDirectOffset(), clang::CodeGen::RawAddress::getElementType(), clang::CodeGen::Address::getElementType(), getEvaluationKind(), clang::CodeGen::CGFunctionInfo::getExtParameterInfo(), clang::CodeGen::CGCallee::getFunctionPointer(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::ABIArgInfo::getInAllocaFieldIndex(), clang::CodeGen::ABIArgInfo::getInAllocaIndirect(), clang::CodeGen::ABIArgInfo::getIndirectAlign(), clang::CodeGen::ABIArgInfo::getIndirectByVal(), getInvokeDest(), clang::CodeGen::ABIArgInfo::getKind(), getLangOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), getLLVMContext(), clang::CodeGen::CodeGenModule::getLLVMContext(), getMaxVectorWidth(), clang::CodeGen::Address::getName(), clang::CodeGen::CGFunctionInfo::getNumRequiredArgs(), clang::CodeGen::ABIArgInfo::getPaddingType(), getParamType(), clang::Type::getPointeeType(), clang::CodeGen::RawAddress::getPointer(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::SourceLocation::getRawEncoding(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), clang::CodeGen::CGFunctionInfo::getReturnType(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::CallArgList::getStackBase(), getTarget(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), getTargetHooks(), clang::CodeGen::Address::getType(), getTypes(), GetUndefRValue(), clang::CodeGen::ABIArgInfo::getUnpaddedCoerceAndExpandType(), clang::SanitizerSet::has(), clang::Decl::hasAttr(), clang::SanitizerSet::hasOneOf(), clang::CodeGen::CallArgList::hasWritebacks(), HaveInsertPoint(), ID, clang::CodeGen::ABIArgInfo::Ignore, clang::CodeGen::ABIArgInfo::InAlloca, InAlwaysInlineAttributedStmt, clang::CodeGen::ABIArgInfo::Indirect, clang::CodeGen::ABIArgInfo::IndirectAliased, clang::CodeGen::CGFunctionInfoArgInfo::info, InNoInlineAttributedStmt, InNoMergeAttributedStmt, clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::RawAddress::invalid(), clang::CodeGen::Address::invalid(), IsArgumentMaybeUndef(), isCleanupPadScope(), clang::CodeGen::CGFunctionInfo::isCmseNSCall(), clang::CodeGen::ABIArgInfo::isCoerceAndExpand(), clang::QualType::isDestructedType(), clang::CodeGen::ABIArgInfo::isDirect(), clang::CodeGen::isEmptyRecord(), clang::CodeGen::ABIArgInfo::isInAlloca(), clang::CodeGen::ABIArgInfo::isIndirect(), clang::CodeGen::ABIArgInfo::isIndirectAliased(), clang::CodeGen::EHPersonality::isMSVCXXPersonality(), clang::CodeGen::ABIArgInfo::isPaddingForCoerceAndExpand(), clang::CodeGen::EHScopeStack::Cleanup::isRedundantBeforeReturn(), clang::CodeGen::RValue::isScalar(), isSEHTryScope(), clang::CodeGen::RawAddress::isValid(), clang::CodeGen::Address::isValid(), clang::interp::Load(), makeNaturalAddressForPointer(), max(), MaybeEmitFPBuiltinofFD(), MustTailCall, clang::CodeGen::NormalEHLifetimeMarker, clang::OpenCL, clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), PopCleanupBlock(), pushDestroy(), clang::interp::Ret(), ReturnValue, SanOpts, SetSqrtFPAccuracy(), clang::SwiftErrorResult, clang::T, clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, clang::CodeGen::CGFunctionInfoArgInfo::type, V, clang::CodeGen::CodeGenPGO::valueProfile(), clang::CodeGen::CodeGenTypeCache::VoidTy, and clang::CodeGen::Address::withElementType().
Referenced by emitAtomicLibcall(), EmitBlockCallExpr(), EmitCall(), EmitCallAndReturnForThunk(), EmitCallExpr(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), EmitCXXConstructorCall(), EmitCXXDestructorCall(), EmitCXXMemberCallExpr(), EmitCXXMemberOrOperatorCall(), EmitCXXMemberPointerCallExpr(), EmitForwardingCallToLambda(), emitLibraryCall(), EmitNewDeleteCall(), EmitSimpleCallExpr(), emitStructSetterCall(), generateObjCGetterBody(), and generateObjCSetterBody().
EmitCall() [2/3]
RValue clang::CodeGen::CodeGenFunction::EmitCall (const CGFunctionInfo & CallInfo, const CGCallee & Callee, ReturnValueSlot ReturnValue, const CallArgList & Args, llvm::CallBase ** callOrInvoke = nullptr, bool IsMustTail = false) inline
Definition at line 4295 of file CodeGenFunction.h.
References EmitCall(), and ReturnValue.
EmitCall() [3/3]
RValue CodeGenFunction::EmitCall (QualType FnType, const CGCallee & Callee, const CallExpr * E, ReturnValueSlot ReturnValue, llvm::Value * Chain = nullptr)
Definition at line 5824 of file CGExpr.cpp.
References clang::CodeGen::CallArgList::add(), clang::CallExpr::arguments(), clang::CodeGen::CodeGenTypes::arrangeFreeFunctionCall(), Builder, BuildFunctionArgList(), CFITCK_ICall, CGM, clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateConstGEP2_32(), clang::CodeGen::CodeGenModule::CreateCrossDsoCfiTypeId(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenModule::CreateMetadataIdentifierForType(), clang::CodeGen::CodeGenModule::CreateMetadataIdentifierGeneralized(), Default, EmitBlock(), EmitCall(), EmitCallArgs(), EmitCfiSlowPathCheck(), EmitCheck(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), EmitIgnoredExpr(), EmitSanitizerStatReport(), ForceLeftToRight, ForceRightToLeft, clang::CodeGen::RValue::get(), clang::CodeGen::CGCallee::getAbstractInfo(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::CodeGen::CGCalleeInfo::getCalleeDecl(), clang::ASTContext::getCanonicalType(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::CodeGenModule::getContext(), getDebugInfo(), clang::GlobalDecl::getDecl(), clang::CallExpr::getDirectCallee(), clang::Expr::getExprLoc(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenTypeCache::getIntAlign(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLangOpts(), getLLVMContext(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::CodeGen::CodeGenModule::getTriple(), clang::CodeGen::CodeGenModule::getTypes(), getTypes(), clang::CodeGen::TargetCodeGenInfo::getUBSanFunctionSignature(), getUBSanFunctionTypeHash(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::Type::isFunctionPointerType(), MustTailCall, ReturnValue, SanOpts, clang::Stub, and clang::ASTContext::VoidPtrTy.
EmitCallAndReturnForThunk()
void CodeGenFunction::EmitCallAndReturnForThunk (llvm::FunctionCallee Callee, const ThunkInfo * Thunk, bool IsUnprototyped)
Definition at line 296 of file CGVTables.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CGCXXABI::adjustCallArgsForDestructorThunk(), clang::CodeGen::CGFunctionInfo::arg_begin(), clang::CodeGen::CGFunctionInfo::arg_size(), clang::CodeGen::CodeGenTypes::arrangeCXXMethodCall(), AutoreleaseResult, clang::Type::castAs(), CGM, CurFnInfo, CurGD, EmitCall(), EmitDelegateCallArg(), EmitMustTailThunk(), clang::CodeGen::CGCXXABI::EmitReturnFromThunk(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), FinishThunk(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::RequiredArgs::forPrototypePlus(), clang::CodeGen::RValue::get(), clang::CodeGen::CGFunctionInfo::getCallingConvention(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::GlobalDecl::getDecl(), clang::CodeGen::ABIArgInfo::getKind(), clang::CodeGen::CGFunctionInfo::getRegParm(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), clang::FunctionType::getReturnType(), clang::CodeGen::CGFunctionInfo::getReturnType(), clang::CXXMethodDecl::getThisType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), hasAggregateEvaluationKind(), clang::CodeGen::CGCXXABI::hasMostDerivedReturn(), clang::CodeGen::CGCXXABI::HasThisReturn(), clang::CodeGen::ABIArgInfo::Indirect, clang::CodeGen::CGFunctionInfoArgInfo::info, clang::ReturnAdjustment::isEmpty(), clang::CodeGen::CGFunctionInfo::isNoReturn(), clang::CodeGen::ReturnValueSlot::isNull(), clang::CodeGen::CGFunctionInfo::isVariadic(), clang::Type::isVoidType(), clang::QualType::isVolatileQualified(), LoadCXXThis(), LoadCXXThisAddress(), clang::FunctionDecl::parameters(), PerformReturnAdjustment(), clang::CodeGen::CGCXXABI::performThisAdjustment(), clang::ThunkInfo::Return, ReturnValue, similar(), clang::ThunkInfo::This, clang::CodeGen::CGFunctionInfoArgInfo::type, clang::CodeGen::CGFunctionInfo::usesInAlloca(), and clang::ASTContext::VoidPtrTy.
Referenced by generateThunk().
EmitCallArg()
void CodeGenFunction::EmitCallArg (CallArgList & args, const Expr * E, QualType ArgType)
EmitCallArg - Emit a single call argument.
Definition at line 4748 of file CGCall.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CallArgList::addArgCleanupDeactivation(), clang::CodeGen::CallArgList::addUncopiedAggregate(), clang::CodeGen::AggValueSlot::asRValue(), Builder, CreateAggTemp(), createPlaceholderSlot(), clang::CodeGen::EHCleanup, EHStack, EmitAggExpr(), EmitAnyExprToTemp(), EmitLValue(), EmitReferenceBindingToExpr(), emitWritebackArg(), clang::CodeGen::AggValueSlot::getAddress(), clang::RecordType::getDecl(), getLangOpts(), clang::Expr::getObjectKind(), hasAggregateEvaluationKind(), clang::Expr::isGLValue(), clang::RecordDecl::isParamDestroyedInCallee(), clang::CodeGen::LValue::isSimple(), clang::CodeGen::CallArgList::isUsingInAlloca(), needsEHCleanup(), clang::OK_Ordinary, clang::CodeGen::AggValueSlot::setExternallyDestructed(), clang::CodeGen::EHScopeStack::stable_begin(), and clang::ast_matchers::type.
EmitCallArgs()
void CodeGenFunction::EmitCallArgs (CallArgList & Args, PrototypeWrapper Prototype, llvm::iterator_range< CallExpr::const_arg_iterator > ArgRange, AbstractCallee AC = AbstractCallee(), unsigned ParamsToSkip = 0, EvaluationOrder Order = EvaluationOrder::Default)
EmitCallArgs - Emit call arguments for a function.
Definition at line 4542 of file CGCall.cpp.
Referenced by commonEmitCXXMemberOrOperatorCall(), EmitAMDGPUDevicePrintfCallExpr(), EmitBlockCallExpr(), EmitBuiltinNewDeleteCall(), EmitCall(), EmitCXXConstructorCall(), EmitCXXMemberPointerCallExpr(), EmitCXXNewExpr(), EmitObjCMessageExpr(), and EmitSynthesizedCXXCopyCtorCall().
EmitCallee()
CGCallee CodeGenFunction::EmitCallee (const Expr * E)
Definition at line 5562 of file CGExpr.cpp.
References EmitDirectCallee(), EmitIgnoredExpr(), EmitLValue(), EmitScalarExpr(), clang::CodeGen::CGCallee::forPseudoDestructor(), clang::ast_matchers::functionType, clang::Type::getAs(), clang::CodeGen::LValue::getPointer(), clang::Expr::getReferencedDeclOfCallee(), clang::Expr::getType(), clang::Expr::IgnoreParens(), and clang::CodeGen::KnownNonNull.
Referenced by EmitCallExpr(), and EmitSimpleCallExpr().
EmitCallExpr()
RValue CodeGenFunction::EmitCallExpr (const CallExpr * E, ReturnValueSlot ReturnValue = ReturnValueSlot())
Definition at line 5459 of file CGExpr.cpp.
References EmitBlockCallExpr(), EmitBuiltinExpr(), EmitCall(), EmitCallee(), EmitCUDAKernelCallExpr(), EmitCXXMemberCallExpr(), EmitCXXOperatorMemberCallExpr(), EmitCXXPseudoDestructorExpr(), clang::CodeGen::CGCallee::getBuiltinDecl(), clang::CodeGen::CGCallee::getBuiltinID(), clang::CallExpr::getCallee(), clang::CodeGen::CGCallee::getPseudoDestructorExpr(), clang::Expr::getType(), clang::Type::isBlockPointerType(), clang::CodeGen::CGCallee::isBuiltin(), clang::CodeGen::CGCallee::isPseudoDestructor(), and ReturnValue.
Referenced by EmitCallExprLValue().
EmitCallExprLValue()
LValue CodeGenFunction::EmitCallExprLValue (const CallExpr * E)
Definition at line 5700 of file CGExpr.cpp.
References clang::CodeGen::Decl, EmitCallExpr(), clang::CodeGen::RValue::getAggregateAddress(), clang::CallExpr::getCallReturnType(), getContext(), clang::CodeGen::RValue::getScalarVal(), clang::Expr::getType(), clang::CodeGen::RValue::isScalar(), MakeAddrLValue(), and MakeNaturalAlignPointeeAddrLValue().
EmitCallOrInvoke()
llvm::CallBase * CodeGenFunction::EmitCallOrInvoke (llvm::FunctionCallee Callee, ArrayRef< llvm::Value * > Args, const Twine & Name = "")
Emits a call or invoke instruction to the given function, depending on the current state of the EH stack.
Definition at line 4953 of file CGCall.cpp.
Referenced by EmitObjCRelease(), emitObjCValueOperation(), and EmitRuntimeCallOrInvoke().
EmitCapturedLocals()
void CodeGenFunction::EmitCapturedLocals (CodeGenFunction & ParentCGF, const Stmt * OutlinedStmt, bool IsFilter)
Scan the outlined statement for captures from the parent function.
For each capture, mark the capture as escaped and emit a call to llvm.localrecover. Insert the localrecover result into the LocalDeclMap.
Definition at line 1871 of file CGException.cpp.
EmitCapturedStmt()
llvm::Function * CodeGenFunction::EmitCapturedStmt (const CapturedStmt & S, CapturedRegionKind K)
Generate an outlined function for the body of a CapturedStmt, store any captured variables into the captured struct, and call the outlined function.
Definition at line 3024 of file CGStmt.cpp.
EmitCaseStmt()
void CodeGenFunction::EmitCaseStmt (const CaseStmt & S, ArrayRef< const Attr * > Attrs)
Definition at line 1598 of file CGStmt.cpp.
EmitCaseStmtRange()
void CodeGenFunction::EmitCaseStmtRange (const CaseStmt & S, ArrayRef< const Attr * > Attrs)
EmitCaseStmtRange - If case statement range is not too big then add multiple cases to switch instruction, one for each value within the range.
If range is too big then emit "if" condition check.
Definition at line 1513 of file CGStmt.cpp.
EmitCastLValue()
LValue CodeGenFunction::EmitCastLValue (const CastExpr * E)
EmitCastLValue - Casts are never lvalues unless that cast is to a reference type.
If the cast is to a reference, we can have the usual lvalue result, otherwise if a cast is needed by the code generator in an lvalue context, then it must mean that we need the address of an aggregate in order to access one of its members. This can happen for all the reasons that casts are permitted with aggregate result, including noop aggregate casts, and cast from scalar to union.
Definition at line 5208 of file CGExpr.cpp.
References clang::Type::castAs(), CFITCK_DerivedCast, CFITCK_UnrelatedCast, CGM, clang::CastExpr::changesVolatileQualification(), ConvertType(), ConvertTypeForMem(), EmitAggExprToLValue(), EmitDynamicCast(), clang::CodeGen::CodeGenModule::EmitExplicitCastExprType(), EmitLValue(), EmitTypeCheck(), EmitUnsupportedLValue(), EmitVTablePtrCheckForCast(), clang::CodeGen::LValue::getAddress(), GetAddressOfBaseClass(), GetAddressOfDerivedClass(), clang::QualType::getAddressSpace(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::LValue::getBaseInfo(), clang::Stmt::getBeginLoc(), clang::CastExpr::getCastKind(), getContext(), clang::Expr::getExprLoc(), getLangOpts(), clang::CodeGen::LValue::getPointer(), clang::ASTContext::getPointerType(), clang::QualType::getQualifiers(), clang::CodeGen::LValue::getQuals(), clang::CastExpr::getSubExpr(), getTargetHooks(), clang::CodeGen::LValue::getTBAAInfo(), clang::CodeGen::CodeGenModule::getTBAAInfoForSubobject(), clang::Expr::getType(), clang::SanitizerSet::has(), clang::HLSL, clang::CodeGen::LValue::isSimple(), MakeAddrLValue(), MakeNaturalAlignRawAddrLValue(), clang::CastExpr::path_begin(), clang::CastExpr::path_end(), clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), sanitizePerformTypeCheck(), SanOpts, clang::CodeGen::LValue::setAddress(), clang::T, TCK_DowncastReference, clang::interp::This(), V, and clang::CodeGen::Address::withElementType().
EmitCfiCheckFail()
void CodeGenFunction::EmitCfiCheckFail ()
Emit a cross-DSO CFI failure handling function.
Definition at line 3724 of file CGExpr.cpp.
References clang::CodeGen::CodeGenModule::addUsedGlobal(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), Builder, CFITCK_DerivedCast, CFITCK_ICall, CFITCK_NVCall, CFITCK_UnrelatedCast, CFITCK_VCall, CGM, clang::CodeGen::CGBuilderTy::CreateConstGEP2_32(), clang::CodeGen::CGBuilderTy::CreateLoad(), Data, EmitCheck(), EmitLoadOfScalar(), EmitTrapCheck(), FinishFunction(), GetAddrOfLocalVar(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypeCache::getIntAlign(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getTypes(), clang::SanitizerSet::has(), clang::HiddenVisibility, clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::Other, clang::LangOptions::Sanitize, SanOpts, clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributes(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), StartFunction(), V, clang::ASTContext::VoidPtrTy, clang::CodeGen::CodeGenTypeCache::VoidPtrTy, clang::ASTContext::VoidTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
Referenced by clang::CodeGen::CodeGenModule::Release().
EmitCfiCheckStub()
void CodeGenFunction::EmitCfiCheckStub ()
Emit a stub for the cross-DSO CFI check function.
Definition at line 3685 of file CGExpr.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), CGM, FnArgs, getContext(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::Other, clang::CodeGen::CodeGenModule::setDSOLocal(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributes(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
Referenced by clang::CodeGen::CodeGenModule::Release().
EmitCfiSlowPathCheck()
void CodeGenFunction::EmitCfiSlowPathCheck (SanitizerMask Kind, llvm::Value * Cond, llvm::ConstantInt * TypeId, llvm::Value * Ptr, ArrayRef< llvm::Constant * > StaticArgs)
Emit a slow path cross-DSO CFI check which calls __cfi_slowpath if Cond if false.
Definition at line 3638 of file CGExpr.cpp.
References Builder, CGM, createBasicBlock(), clang::CodeGen::SanitizerMetadata::disableSanitizerForGlobal(), EmitBlock(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getLLVMContext(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getSanitizerMetadata(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, Node, clang::CodeGenOptions::SanitizeTrap, clang::CodeGen::CodeGenModule::setDSOLocal(), and clang::CodeGen::CodeGenTypeCache::VoidTy.
Referenced by EmitCall(), and EmitVTablePtrCheck().
EmitCheck()
void CodeGenFunction::EmitCheck (ArrayRef< std::pair< llvm::Value *, SanitizerMask >> Checked, SanitizerHandler Check, ArrayRef< llvm::Constant * > StaticArgs, ArrayRef< llvm::Value * > DynamicArgs)
Create a basic block that will either trap or call a handler function in the UBSan runtime with the provided arguments, and create a conditional branch to it.
Definition at line 3515 of file CGExpr.cpp.
References Builder, CGM, ClSanitizeGuardChecks(), createBasicBlock(), clang::CodeGen::SanitizerMetadata::disableSanitizerForGlobal(), EmitBlock(), emitCheckHandlerCall(), EmitCheckValue(), EmitTrapCheck(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::CodeGenModule::getIntrinsic(), getLLVMContext(), clang::CodeGen::CodeGenModule::getModule(), getRecoverableKind(), clang::CodeGen::CodeGenModule::getSanitizerMetadata(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, IsSanitizerScope, Node, clang::CodeGenOptions::SanitizeRecover, SanitizerHandlers, clang::CodeGenOptions::SanitizeTrap, SanOpts, and clang::CodeGen::CodeGenTypeCache::VoidTy.
Referenced by emitAlignmentAssumptionCheck(), EmitBitfieldConversionCheck(), EmitCall(), EmitCfiCheckFail(), EmitNullabilityCheck(), EmitOverflowCheckedAbs(), EmitReturnValueCheck(), EmitScalarRangeCheck(), EmitTypeCheck(), EmitUnreachable(), EmitVariablyModifiedType(), EmitVTablePtrCheck(), EmitVTableTypeCheckedLoad(), and GenerateCode().
EmitCheckedArgForBuiltin()
Value * CodeGenFunction::EmitCheckedArgForBuiltin (const Expr * E, BuiltinCheckKind Kind)
Emits an argument for a call to a builtin.
If the builtin sanitizer is enabled, a runtime check specified by Kind is also emitted.
Definition at line 2153 of file CGBuiltin.cpp.
EmitCheckedInBoundsGEP() [1/2]
Address clang::CodeGen::CodeGenFunction::EmitCheckedInBoundsGEP (Address Addr, ArrayRef< llvm::Value * > IdxList, llvm::Type * elementType, bool SignedIndices, bool IsSubtraction, SourceLocation Loc, CharUnits Align, const Twine & Name = "")
EmitCheckedInBoundsGEP() [2/2]
llvm::Value* clang::CodeGen::CodeGenFunction::EmitCheckedInBoundsGEP (llvm::Type * ElemTy, llvm::Value * Ptr, ArrayRef< llvm::Value * > IdxList, bool SignedIndices, bool IsSubtraction, SourceLocation Loc, const Twine & Name = "")
Same as IRBuilder::CreateInBoundsGEP, but additionally emits a check to detect undefined behavior when the pointer overflow sanitizer is enabled.
SignedIndices indicates whether any of the GEP indices are signed. IsSubtraction indicates whether the expression used to form the GEP is a subtraction.
Referenced by emitArraySubscriptGEP(), emitPointerArithmetic(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
EmitCheckedLValue()
LValue CodeGenFunction::EmitCheckedLValue (const Expr * E, TypeCheckKind TCK)
Same as EmitLValue but additionally we generate checking code to guard against undefined behavior.
This is only suitable when we know that the address will be used to access the object.
Definition at line 1462 of file CGExpr.cpp.
References EmitArraySubscriptExpr(), EmitLValue(), EmitTypeCheck(), clang::Expr::getExprLoc(), clang::Expr::getType(), clang::SanitizerSet::has(), clang::CodeGen::LValue::isBitField(), clang::CodeGen::LValue::isSimple(), IsWrappedCXXThis(), SanOpts, and clang::SanitizerSet::set().
Referenced by EmitBinaryOperatorLValue(), and EmitMemberExpr().
EmitCheckSourceLocation()
llvm::Constant * CodeGenFunction::EmitCheckSourceLocation (SourceLocation Loc)
Emit a description of a source location in a format suitable for passing to a runtime sanitizer handler.
Emit a representation of a SourceLocation for passing to a handler in a sanitizer runtime library.
The format for this data is:
struct SourceLocation {
  const char *Filename;
  int32_t Line, Column;
};
For an invalid SourceLocation, the Filename pointer is null.
Definition at line 3380 of file CGExpr.cpp.
References Builder, CGM, clang::Column, Data, clang::CodeGen::SanitizerMetadata::disableSanitizerForGlobal(), Filename, clang::CodeGen::CodeGenModule::GetAddrOfConstantCString(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::PresumedLoc::getColumn(), getContext(), clang::PresumedLoc::getFilename(), clang::PresumedLoc::getLine(), clang::SourceManager::getPresumedLoc(), clang::CodeGen::CodeGenModule::getSanitizerMetadata(), clang::ASTContext::getSourceManager(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, INT_MIN, and clang::PresumedLoc::isValid().
Referenced by emitAlignmentAssumptionCheck(), EmitBitfieldConversionCheck(), EmitCall(), EmitNullabilityCheck(), EmitOverflowCheckedAbs(), EmitReturnValueCheck(), EmitScalarRangeCheck(), EmitTypeCheck(), EmitUnreachable(), EmitVariablyModifiedType(), EmitVTablePtrCheck(), and GenerateCode().
EmitCheckTypeDescriptor()
llvm::Constant * CodeGenFunction::EmitCheckTypeDescriptor (QualType T)
Emit a description of a type in a format suitable for passing to a runtime sanitizer handler.
Emit a type description suitable for use by a runtime sanitizer library.
The format of a type descriptor is
{ i16 TypeKind, i16 TypeInfo }
followed by an array of i8 containing the type name. TypeKind is 0 for an integer, 1 for a floating point value, and -1 for anything else.
Definition at line 3300 of file CGExpr.cpp.
References clang::DiagnosticsEngine::ak_qualtype, CGM, clang::DiagnosticsEngine::ConvertArgToString(), getContext(), clang::CodeGen::CodeGenModule::getDiags(), clang::CodeGen::CodeGenModule::getTypeDescriptorFromMap(), clang::ASTContext::getTypeSize(), getTypeSize(), clang::Type::isFloatingType(), clang::Type::isIntegerType(), clang::Type::isSignedIntegerType(), and clang::T.
Referenced by emitAlignmentAssumptionCheck(), EmitBitfieldConversionCheck(), EmitCall(), EmitNullabilityCheck(), EmitOverflowCheckedAbs(), EmitScalarRangeCheck(), EmitTypeCheck(), EmitVariablyModifiedType(), and EmitVTablePtrCheck().
EmitCheckValue()
llvm::Value * CodeGenFunction::EmitCheckValue (llvm::Value * V)
Convert a value into a format suitable for passing to a runtime sanitizer handler.
Definition at line 3342 of file CGExpr.cpp.
References Builder, CreateDefaultAlignTempAlloca(), clang::CodeGen::CGBuilderTy::CreateStore(), getLLVMContext(), clang::CodeGen::RawAddress::getPointer(), clang::CodeGen::CodeGenTypeCache::IntPtrTy, and V.
Referenced by emitAlignmentAssumptionCheck(), EmitCheck(), and EmitScalarRangeCheck().
EmitCMSEClearRecord() [1/2]
llvm::Value * CodeGenFunction::EmitCMSEClearRecord (llvm::Value * V, llvm::ArrayType * ATy, QualType RTy)
Definition at line 3845 of file CGCall.cpp.
References Builder, buildMultiCharMask(), clang::Type::castAs(), CGM, clang::ASTContext::getCharWidth(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), and setUsedBits().
EmitCMSEClearRecord() [2/2]
llvm::Value * CodeGenFunction::EmitCMSEClearRecord (llvm::Value * V, llvm::IntegerType * ITy, QualType RTy)
Definition at line 3825 of file CGCall.cpp.
References Builder, buildMultiCharMask(), clang::Type::castAs(), CGM, clang::ASTContext::getCharWidth(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), and setUsedBits().
Referenced by EmitCall(), and EmitFunctionEpilog().
EmitCoawaitExpr()
RValue CodeGenFunction::EmitCoawaitExpr (const CoawaitExpr & E, AggValueSlot aggSlot = AggValueSlot::ignored(), bool ignoreResult = false)
Definition at line 373 of file CGCoroutine.cpp.
References CurCoro, clang::CodeGen::CodeGenFunction::CGCoroInfo::Data, and emitSuspendExpression().
EmitCoawaitLValue()
LValue CodeGenFunction::EmitCoawaitLValue (const CoawaitExpr * E)
Definition at line 474 of file CGCoroutine.cpp.
References CurCoro, clang::CodeGen::CodeGenFunction::CGCoroInfo::Data, emitSuspendExpression(), getContext(), getCoroutineSuspendExprReturnType(), and clang::CodeGen::AggValueSlot::ignored().
EmitCommonNeonBuiltinExpr()
Value * CodeGenFunction::EmitCommonNeonBuiltinExpr (unsigned BuiltinID, unsigned LLVMIntrinsic, unsigned AltLLVMIntrinsic, const char * NameHint, unsigned Modifier, const CallExpr * E, SmallVectorImpl< llvm::Value * > & Ops, Address PtrOp0, Address PtrOp1, llvm::Triple::ArchType Arch)
Definition at line 7690 of file CGBuiltin.cpp.
References clang::CallExpr::getArg(), clang::Expr::getIntegerConstantExpr(), GetNeonType(), and clang::CallExpr::getNumArgs().
EmitComplexAssignmentLValue()
LValue CodeGenFunction::EmitComplexAssignmentLValue (const BinaryOperator * E)
Emit an l-value for an assignment (simple or compound) of complex type.
Definition at line 1502 of file CGExprComplex.cpp.
References CGM, clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), getLangOpts(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), and clang::CodeGen::CodeGenModule::getOpenMPRuntime().
Referenced by EmitBinaryOperatorLValue().
EmitComplexCompoundAssignmentLValue()
LValue CodeGenFunction::EmitComplexCompoundAssignmentLValue (const CompoundAssignOperator * E)
Definition at line 1526 of file CGExprComplex.cpp.
References getComplexOp(), and clang::BinaryOperator::getOpcode().
EmitComplexExpr()
ComplexPairTy CodeGenFunction::EmitComplexExpr (const Expr * E, bool IgnoreReal = false, bool IgnoreImag = false)
EmitComplexExpr - Emit the computation of the specified expression of complex type, returning the result.
EmitComplexExpr - Emit the computation of the specified expression of complex type, ignoring the result.
Definition at line 1472 of file CGExprComplex.cpp.
References getComplexType(), and clang::Expr::getType().
Referenced by EmitAnyExpr(), EmitAtomicInit(), EmitExprAsInit(), and EvaluateExprAsBool().
EmitComplexExprIntoLValue()
void CodeGenFunction::EmitComplexExprIntoLValue (const Expr * E, LValue dest, bool isInit)
EmitComplexExprIntoLValue - Emit the given expression of complex type and place its result into the specified l-value.
Definition at line 1481 of file CGExprComplex.cpp.
References getComplexType(), and clang::Expr::getType().
Referenced by EmitAnyExprToMem(), EmitDeclInit(), EmitInitializerForField(), and StoreAnyExprIntoOneUnit().
EmitComplexPrePostIncDec()
CodeGenFunction::ComplexPairTy CodeGenFunction::EmitComplexPrePostIncDec (const UnaryOperator * E, LValue LV, bool isInc, bool isPre)
Definition at line 1200 of file CGExpr.cpp.
References Builder, clang::Type::castAs(), CGM, clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), EmitLoadOfComplex(), EmitStoreOfComplex(), getContext(), clang::UnaryOperator::getExprLoc(), getLangOpts(), getLLVMContext(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::UnaryOperator::getSubExpr(), and clang::Expr::getType().
Referenced by EmitUnaryOpLValue().
EmitComplexToScalarConversion()
Value * CodeGenFunction::EmitComplexToScalarConversion (ComplexPairTy Src, QualType SrcTy, QualType DstTy, SourceLocation Loc)
Emit a conversion from the specified complex type to the specified destination type, where the destination type is an LLVM scalar type.
Definition at line 5512 of file CGExprScalar.cpp.
References hasScalarEvaluationKind(), and clang::Type::isAnyComplexType().
Referenced by convertToScalarValue(), and EvaluateExprAsBool().
EmitCompoundAssignmentLValue()
LValue CodeGenFunction::EmitCompoundAssignmentLValue (const CompoundAssignOperator * E)
Definition at line 5559 of file CGExprScalar.cpp.
References COMPOUND_OP, clang::interp::Div(), clang::BinaryOperator::getOpcode(), clang::interp::Mul(), clang::Or, clang::interp::Rem(), clang::interp::Shl(), and clang::interp::Shr().
EmitCompoundLiteralLValue()
LValue CodeGenFunction::EmitCompoundLiteralLValue (const CompoundLiteralExpr * E)
Definition at line 5016 of file CGExpr.cpp.
References CGM, clang::CPlusPlus, CreateMemTemp(), clang::CodeGen::Decl, clang::CodeGen::EHCleanup, EmitAnyExprToMem(), EmitVariablyModifiedType(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCompoundLiteral(), getCleanupKind(), getDestroyer(), clang::CompoundLiteralExpr::getInitializer(), getLangOpts(), clang::QualType::getQualifiers(), clang::Expr::getType(), clang::QualType::isDestructedType(), clang::CompoundLiteralExpr::isFileScope(), clang::Type::isVariablyModifiedType(), MakeAddrLValue(), and pushLifetimeExtendedDestroy().
EmitCompoundStmt()
Address CodeGenFunction::EmitCompoundStmt (const CompoundStmt & S, bool GetLast = false, AggValueSlot AggSlot = AggValueSlot::ignored())
EmitCompoundStmt - Emit a compound statement {..} node.
If GetLast is true, this captures the expression result of the last sub-statement and returns it (for use by the statement expression extension).
Definition at line 492 of file CGStmt.cpp.
EmitCompoundStmtWithoutScope()
Address CodeGenFunction::EmitCompoundStmtWithoutScope (const CompoundStmt & S, bool GetLast = false, AggValueSlot AVS = AggValueSlot::ignored())
Definition at line 504 of file CGStmt.cpp.
Referenced by GenerateObjCMethod().
EmitConditionalOperatorLValue()
LValue CodeGenFunction::EmitConditionalOperatorLValue (const AbstractConditionalOperator * E)
Definition at line 5158 of file CGExpr.cpp.
References Builder, CGM, EmitAggExprToLValue(), EmitLValueOrThrowExpression(), EmitUnsupportedLValue(), clang::ast_matchers::expr, hasAggregateEvaluationKind(), MakeAddrLValue(), max(), mergeAddressesInConditionalExpr(), and clang::CodeGen::CodeGenModule::mergeTBAAInfoForConditionalOperator().
EmitConstructorBody()
void CodeGenFunction::EmitConstructorBody (FunctionArgList & Args)
EmitConstructorBody - Emits the body of the current constructor.
Definition at line 840 of file CGClass.cpp.
References CGM, clang::Ctor_Base, clang::Ctor_Complete, CurGD, EmitAsanPrologueOrEpilogue(), EmitCtorPrologue(), EmitDelegateCXXConstructorCall(), EmitStmt(), EnterCXXTryStmt(), ExitCXXTryStmt(), clang::CodeGen::CodeGenFunction::RunCleanupsScope::ForceCleanup(), clang::FunctionDecl::getBody(), clang::GlobalDecl::getCtorType(), clang::TargetInfo::getCXXABI(), clang::GlobalDecl::getDecl(), clang::Decl::getEndLoc(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetCXXABI::hasConstructorVariants(), incrementProfileCounter(), IsConstructorDelegationValid(), and maybeCreateMCDCCondBitmap().
Referenced by GenerateCode().
EmitContinueStmt()
void CodeGenFunction::EmitContinueStmt (const ContinueStmt & S)
Definition at line 1498 of file CGStmt.cpp.
EmitCoreturnStmt()
void CodeGenFunction::EmitCoreturnStmt (const CoreturnStmt & S)
Definition at line 387 of file CGCoroutine.cpp.
EmitCoroutineBody()
void CodeGenFunction::EmitCoroutineBody (const CoroutineBodyStmt & S)
Definition at line 775 of file CGCoroutine.cpp.
EmitCoroutineIntrinsic()
RValue CodeGenFunction::EmitCoroutineIntrinsic (const CallExpr * E, unsigned int IID)
Definition at line 957 of file CGCoroutine.cpp.
References Builder, CGM, CurAwaitSuspendWrapper, CurCoro, clang::CodeGen::CodeGenFunction::CGCoroInfo::Data, clang::CodeGen::CodeGenModule::Error(), clang::CodeGen::CodeGenFunction::AwaitSuspendWrapperInfo::FramePtr, clang::CodeGen::RValue::get(), and clang::CallExpr::getBeginLoc().
EmitCountedByFieldExpr()
llvm::Value * CodeGenFunction::EmitCountedByFieldExpr (const Expr * Base, const FieldDecl * FAMDecl, const FieldDecl * CountDecl)
Build an expression accessing the "counted_by" field.
This method is typically called in contexts where we can't generate side-effects, like in __builtin_dynamic_object_size.
When finding expressions, only choose those that have either already been emitted or can be loaded without side-effects.
FAMDecl: the Decl for the flexible array member. It may not be within the top-level struct.
CountDecl: must be within the same non-anonymous struct as FAMDecl.
Definition at line 1105 of file CGExpr.cpp.
References Builder, ConvertType(), clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), EmitDeclRefLValue(), EmitMemberExpr(), EmitPointerWithAlignment(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::LValue::getAddress(), getContext(), getGEPIndicesToField(), clang::CodeGen::CodeGenTypeCache::getIntAlign(), clang::DeclContext::getOuterLexicalRecordContext(), clang::FieldDecl::getParent(), clang::CodeGen::LValue::getPointer(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::Expr::HasSideEffects(), and clang::Type::isPointerType().
EmitCoyieldExpr()
RValue CodeGenFunction::EmitCoyieldExpr (const CoyieldExpr & E, AggValueSlot aggSlot = AggValueSlot::ignored(), bool ignoreResult = false)
Definition at line 380 of file CGCoroutine.cpp.
References CurCoro, clang::CodeGen::CodeGenFunction::CGCoroInfo::Data, and emitSuspendExpression().
EmitCoyieldLValue()
LValue CodeGenFunction::EmitCoyieldLValue (const CoyieldExpr * E)
Definition at line 484 of file CGCoroutine.cpp.
References CurCoro, clang::CodeGen::CodeGenFunction::CGCoroInfo::Data, emitSuspendExpression(), getContext(), getCoroutineSuspendExprReturnType(), and clang::CodeGen::AggValueSlot::ignored().
EmitCtorPrologue()
void CodeGenFunction::EmitCtorPrologue (const CXXConstructorDecl * CD, CXXCtorType Type, FunctionArgList & Args)
EmitCtorPrologue - This routine generates necessary code to initialize base classes and non-static data members belonging to this constructor.
Definition at line 1272 of file CGClass.cpp.
References Builder, CGM, clang::CodeGen::CGBuilderTy::CreateLaunderInvariantGroup(), clang::Ctor_Base, EmitBaseInitializer(), EmitBlock(), clang::CodeGen::CGCXXABI::EmitCtorCompleteObjectHandler(), EmitDelegatingCXXConstructorCall(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::TargetInfo::getCXXABI(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CXXRecordDecl::getNumVBases(), clang::CXXMethodDecl::getParent(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetCXXABI::hasConstructorVariants(), clang::CXXConstructorDecl::init_begin(), clang::CXXConstructorDecl::init_end(), InitializeVTablePointers(), clang::CXXRecordDecl::isAbstract(), clang::CXXConstructorDecl::isDelegatingConstructor(), isInitializerOfDynamicClass(), LoadCXXThis(), LoadCXXThisAddress(), and clang::Member.
Referenced by EmitConstructorBody(), and EmitInlinedInheritingCXXConstructorCall().
EmitCUDAKernelCallExpr()
RValue CodeGenFunction::EmitCUDAKernelCallExpr (const CUDAKernelCallExpr * E, ReturnValueSlot ReturnValue)
Definition at line 502 of file CGExprCXX.cpp.
References CGM, clang::CodeGen::CGCUDARuntime::EmitCUDAKernelCallExpr(), clang::CodeGen::CodeGenModule::getCUDARuntime(), and ReturnValue.
Referenced by EmitCallExpr().
EmitCXXAggrConstructorCall() [1/2]
void CodeGenFunction::EmitCXXAggrConstructorCall (const CXXConstructorDecl * ctor, const ArrayType * arrayType, Address arrayBegin, const CXXConstructExpr * E, bool NewPointerIsChecked, bool zeroInitialize = false)
EmitCXXAggrConstructorCall - Emit a loop to call a particular constructor for each of several members of an array.
Parameters
ctor the constructor to call for each element
arrayType the type of the array to initialize
arrayBegin an arrayType*
zeroInitialize true if each element should be zero-initialized before it is constructed
Definition at line 1983 of file CGClass.cpp.
References clang::ast_matchers::arrayType, and emitArrayLength().
Referenced by EmitCXXConstructExpr(), and EmitNewArrayInitializer().
EmitCXXAggrConstructorCall() [2/2]
void CodeGenFunction::EmitCXXAggrConstructorCall (const CXXConstructorDecl * ctor, llvm::Value * numElements, Address arrayBase, const CXXConstructExpr * E, bool NewPointerIsChecked, bool zeroInitialize = false)
EmitCXXAggrConstructorCall - Emit a loop to call a particular constructor for each of several members of an array.
Parameters
ctor the constructor to call for each element
numElements the number of elements in the array; may be zero
arrayBase a T*, where T is the type constructed by ctor
zeroInitialize true if each element should be zero-initialized before it is constructed
Definition at line 2004 of file CGClass.cpp.
References clang::CharUnits::alignmentOfArrayElement(), Builder, createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreateIsNull(), clang::Ctor_Complete, destroyCXXObject, clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, EmitBlock(), EmitCXXConstructorCall(), EmitNullInitialization(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::AggValueSlot::forAddr(), clang::CodeGen::Address::getAlignment(), getContext(), clang::CodeGen::Address::getElementType(), getLangOpts(), clang::CXXMethodDecl::getParent(), clang::ASTContext::getTypeDeclType(), clang::CXXRecordDecl::hasTrivialDestructor(), clang::CodeGen::AggValueSlot::IsDestructed, clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::AggValueSlot::IsNotSanitizerChecked, clang::CodeGen::AggValueSlot::IsNotZeroed, clang::CodeGen::AggValueSlot::IsSanitizerChecked, pushRegularPartialArrayCleanup(), clang::CodeGen::CodeGenTypeCache::SizeTy, and clang::ast_matchers::type.
EmitCXXBindTemporaryLValue()
LValue CodeGenFunction::EmitCXXBindTemporaryLValue (const CXXBindTemporaryExpr * E)
Definition at line 5743 of file CGExpr.cpp.
References CreateAggTemp(), clang::CodeGen::Decl, EmitAggExpr(), EmitCXXTemporary(), clang::CodeGen::AggValueSlot::getAddress(), clang::CXXBindTemporaryExpr::getSubExpr(), clang::CXXBindTemporaryExpr::getTemporary(), clang::Expr::getType(), MakeAddrLValue(), and clang::CodeGen::AggValueSlot::setExternallyDestructed().
EmitCXXConstructExpr()
void CodeGenFunction::EmitCXXConstructExpr (const CXXConstructExpr * E, AggValueSlot Dest)
Definition at line 595 of file CGExprCXX.cpp.
References clang::ast_matchers::arrayType, clang::Complete, clang::Ctor_Base, clang::Ctor_Complete, CurGD, clang::Delegating, EmitAggExpr(), EmitCXXAggrConstructorCall(), EmitCXXConstructorCall(), EmitNullBaseClassInitialization(), EmitNullInitialization(), clang::CodeGen::AggValueSlot::getAddress(), clang::CXXConstructExpr::getArg(), clang::CXXConstructExpr::getConstructionKind(), clang::CXXConstructExpr::getConstructor(), getContext(), clang::GlobalDecl::getCtorType(), getLangOpts(), clang::CXXMethodDecl::getParent(), clang::Expr::getType(), clang::CXXConstructorDecl::isDefaultConstructor(), clang::CXXConstructExpr::isElidable(), clang::CodeGen::AggValueSlot::isIgnored(), clang::CodeGen::AggValueSlot::isSanitizerChecked(), clang::Expr::isTemporaryObject(), clang::FunctionDecl::isTrivial(), clang::CodeGen::AggValueSlot::isZeroed(), clang::NonVirtualBase, clang::CXXConstructExpr::requiresZeroInitialization(), and clang::VirtualBase.
Referenced by EmitCXXConstructLValue().
EmitCXXConstructLValue()
LValue CodeGenFunction::EmitCXXConstructLValue (const CXXConstructExpr * E)
Definition at line 5719 of file CGExpr.cpp.
References CreateAggTemp(), clang::CodeGen::Decl, EmitCXXConstructExpr(), clang::CodeGen::AggValueSlot::getAddress(), clang::Type::getAsCXXRecordDecl(), clang::Expr::getType(), clang::CXXRecordDecl::hasTrivialDestructor(), and MakeAddrLValue().
EmitCXXConstructorCall() [1/2]
void CodeGenFunction::EmitCXXConstructorCall (const CXXConstructorDecl * D, CXXCtorType Type, bool ForVirtualBase, bool Delegating, Address This, CallArgList & Args, AggValueSlot::Overlap_t Overlap, SourceLocation Loc, bool NewPointerIsChecked)
Definition at line 2195 of file CGClass.cpp.
References clang::CodeGen::CGCXXABI::addImplicitConstructorArgs(), clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), canEmitDelegateCallArgs(), clang::CodeGen::CGCXXABI::canSpeculativelyEmitVTable(), CGM, clang::Ctor_Base, clang::Delegating, EmitAggregateCopyCtor(), EmitCall(), EmitInlinedInheritingCXXConstructorCall(), EmitTypeCheck(), EmitVTableAssumptionLoads(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::CodeGenModule::getAddrOfCXXStructor(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CXXConstructorDecl::getInheritedConstructor(), clang::QualType::getNonReferenceType(), clang::FunctionDecl::getParamDecl(), clang::CXXMethodDecl::getParent(), clang::ValueDecl::getType(), clang::ASTContext::getTypeDeclType(), clang::CodeGen::CodeGenModule::getTypes(), getTypes(), clang::CodeGen::CodeGenTypes::inheritingCtorHasParams(), clang::CXXConstructorDecl::isDefaultConstructor(), clang::CXXRecordDecl::isDynamicClass(), isMemcpyEquivalentSpecialMember(), clang::FunctionDecl::isTrivial(), MakeAddrLValue(), makeNaturalAddressForPointer(), clang::CodeGen::CGCXXABI::AddedStructorArgCounts::Prefix, clang::CodeGen::CGCXXABI::AddedStructorArgCounts::Suffix, TCK_ConstructorCall, clang::interp::This(), and clang::CharUnits::Zero().
EmitCXXConstructorCall() [2/2]
void CodeGenFunction::EmitCXXConstructorCall (const CXXConstructorDecl * D, CXXCtorType Type, bool ForVirtualBase, bool Delegating, AggValueSlot ThisAVS, const CXXConstructExpr * E)
Definition at line 2120 of file CGClass.cpp.
References clang::CodeGen::CallArgList::add(), clang::CXXConstructExpr::arguments(), clang::Type::castAs(), Default, clang::Delegating, EmitAggregateCopyCtor(), EmitCallArgs(), EmitLValue(), ForceLeftToRight, clang::CodeGen::RValue::get(), clang::CodeGen::AggValueSlot::getAddress(), clang::Qualifiers::getAddressSpace(), clang::QualType::getAddressSpace(), clang::CXXConstructExpr::getArg(), getAsNaturalPointerTo(), clang::CXXConstructExpr::getConstructor(), getContext(), clang::Expr::getExprLoc(), clang::CXXMethodDecl::getFunctionObjectParameterType(), getLLVMContext(), clang::CXXConstructExpr::getNumArgs(), clang::CXXMethodDecl::getParent(), clang::Type::getPointeeType(), clang::CodeGen::AggValueSlot::getQualifiers(), clang::ASTContext::getTargetAddressSpace(), getTargetHooks(), clang::CXXMethodDecl::getThisType(), clang::ValueDecl::getType(), clang::ASTContext::getTypeDeclType(), clang::CXXConstructExpr::isListInitialization(), isMemcpyEquivalentSpecialMember(), clang::CodeGen::AggValueSlot::isSanitizerChecked(), MakeAddrLValue(), clang::CodeGen::AggValueSlot::mayOverlap(), clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), and clang::interp::This().
Referenced by EmitCXXAggrConstructorCall(), EmitCXXConstructExpr(), EmitDelegateCXXConstructorCall(), EmitInheritedCXXConstructorCall(), and EmitSynthesizedCXXCopyCtorCall().
EmitCXXDeleteExpr()
void CodeGenFunction::EmitCXXDeleteExpr (const CXXDeleteExpr * E)
Definition at line 2082 of file CGExprCXX.cpp.
References Builder, ConvertTypeForMem(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreateIsNull(), EmitArrayDelete(), EmitBlock(), EmitDestroyingObjectDelete(), EmitObjectDelete(), EmitPointerWithAlignment(), clang::CodeGen::Address::getAlignment(), clang::CXXDeleteExpr::getArgument(), getContext(), clang::CXXDeleteExpr::getDestroyedType(), clang::CodeGen::Address::getElementType(), clang::CXXDeleteExpr::getOperatorDelete(), clang::CXXDeleteExpr::isArrayForm(), clang::Type::isConstantArrayType(), clang::FunctionDecl::isDestroyingOperatorDelete(), IsNull, and clang::CodeGen::Address::setKnownNonNull().
EmitCXXDestructorCall() [1/2]
void CodeGenFunction::EmitCXXDestructorCall (const CXXDestructorDecl * D, CXXDtorType Type, bool ForVirtualBase, bool Delegating, Address This, QualType ThisTy)
Definition at line 2511 of file CGClass.cpp.
References CGM, clang::Delegating, clang::CodeGen::CGCXXABI::EmitDestructorCall(), clang::CodeGen::CodeGenModule::getCXXABI(), and clang::interp::This().
Referenced by EmitDestructorBody(), and EmitObjectDelete().
EmitCXXDestructorCall() [2/2]
RValue CodeGenFunction::EmitCXXDestructorCall (GlobalDecl Dtor, const CGCallee & Callee, llvm::Value * This, QualType ThisTy, llvm::Value * ImplicitParam, QualType ImplicitParamTy, const CallExpr * E)
Definition at line 101 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenTypes::arrangeCXXStructorDeclaration(), CGM, commonEmitCXXMemberOrOperatorCall(), clang::CodeGen::CodeGenTypes::ConvertType(), EmitCall(), clang::Qualifiers::getAddressSpace(), clang::QualType::getAddressSpace(), clang::Type::getAsCXXRecordDecl(), clang::GlobalDecl::getDecl(), clang::Expr::getExprLoc(), clang::CXXMethodDecl::getMethodQualifiers(), clang::CXXMethodDecl::getParent(), getTargetHooks(), clang::CXXMethodDecl::getThisType(), clang::CodeGen::CodeGenModule::getTypes(), clang::QualType::isNull(), MustTailCall, clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), and clang::interp::This().
EmitCXXForRangeStmt()
void CodeGenFunction::EmitCXXForRangeStmt (const CXXForRangeStmt & S, ArrayRef< const Attr * > Attrs = std::nullopt)
Definition at line 1228 of file CGStmt.cpp.
EmitCXXGlobalVarDeclInit()
void CodeGenFunction::EmitCXXGlobalVarDeclInit (const VarDecl & D, llvm::GlobalVariable * GV, bool PerformInit)
EmitCXXGlobalVarDeclInit - Create the initializer for a C++ variable with global storage.
Definition at line 178 of file CGDeclCXX.cpp.
References CGM, clang::QualType::DK_cxx_destructor, EmitDeclDestroy(), EmitDeclInit(), EmitDeclInvariant(), EmitReferenceBindingToExpr(), EmitStoreOfScalar(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), clang::Decl::getAttr(), getContext(), clang::VarDecl::getInit(), getLangOpts(), getLLVMContext(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::CodeGenTypes::getTargetAddressSpace(), clang::ValueDecl::getType(), getTypes(), clang::Decl::hasAttr(), clang::QualType::isConstantStorage(), clang::Type::isReferenceType(), clang::VarDecl::needsDestruction(), and clang::T.
Referenced by AddInitializerToStaticVarDecl(), and GenerateCXXGlobalVarDeclInitFunc().
EmitCXXGuardedInit()
void CodeGenFunction::EmitCXXGuardedInit (const VarDecl & D, llvm::GlobalVariable * DeclPtr, bool PerformInit)
Emit code in this function to perform a guarded variable initialization.
Guarded initializations are used when it's not possible to prove that an initialization will be done exactly once, e.g. with a static local variable or a static data member of a class template.
Definition at line 389 of file CGDeclCXX.cpp.
References CGM, clang::CodeGen::CGCXXABI::EmitGuardedInit(), clang::CodeGen::CodeGenModule::Error(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getCXXABI(), and clang::Decl::getLocation().
Referenced by AddInitializerToStaticVarDecl(), and GenerateCXXGlobalVarDeclInitFunc().
EmitCXXGuardedInitBranch()
void CodeGenFunction::EmitCXXGuardedInitBranch (llvm::Value * NeedsInit, llvm::BasicBlock * InitBlock, llvm::BasicBlock * NoInitBlock, GuardKind Kind, const VarDecl * D)
Emit a branch to select whether or not to perform guarded initialization.
Definition at line 403 of file CGDeclCXX.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::getLLVMContext(), clang::VarDecl::getTLSKind(), clang::VarDecl::isLocalVarDecl(), TlsGuard, and VariableGuard.
Referenced by GenerateCXXGlobalInitFunc().
EmitCXXMemberCallExpr()
RValue CodeGenFunction::EmitCXXMemberCallExpr (const CXXMemberCallExpr * E, ReturnValueSlot ReturnValue)
Definition at line 188 of file CGExprCXX.cpp.
References CGM, EmitCall(), EmitCXXMemberOrOperatorMemberCallExpr(), EmitCXXMemberPointerCallExpr(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::MemberExpr::getBase(), clang::CallExpr::getCallee(), getContext(), clang::MemberExpr::getMemberDecl(), clang::MemberExpr::getQualifier(), clang::ValueDecl::getType(), clang::MemberExpr::hasQualifier(), clang::Expr::IgnoreParens(), clang::MemberExpr::isArrow(), clang::CXXMethodDecl::isStatic(), and ReturnValue.
Referenced by EmitCallExpr().
EmitCXXMemberDataPointerAddress()
Address CodeGenFunction::EmitCXXMemberDataPointerAddress (const Expr * E, Address base, llvm::Value * memberPtr, const MemberPointerType * memberPtrType, LValueBaseInfo * BaseInfo = nullptr, TBAAAccessInfo * TBAAInfo = nullptr)
Emit the address of a field using a member data pointer.
Parameters
E Only used for emergency diagnostics
Definition at line 151 of file CGClass.cpp.
References CGM, ConvertTypeForMem(), clang::CodeGen::CGCXXABI::EmitMemberDataPointerAddress(), clang::CodeGen::Address::getAlignment(), clang::Type::getAsCXXRecordDecl(), clang::MemberPointerType::getClass(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::CodeGenModule::getDynamicOffsetAlignment(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), and clang::MemberPointerType::getPointeeType().
Referenced by EmitMaterializeTemporaryExpr(), and EmitPointerToDataMemberBinaryExpr().
EmitCXXMemberOrOperatorCall()
RValue CodeGenFunction::EmitCXXMemberOrOperatorCall (const CXXMethodDecl * Method, const CGCallee & Callee, ReturnValueSlot ReturnValue, llvm::Value * This, llvm::Value * ImplicitParam, QualType ImplicitParamTy, const CallExpr * E, CallArgList * RtlArgs)
Definition at line 85 of file CGExprCXX.cpp.
References clang::CodeGen::CodeGenTypes::arrangeCXXMethodCall(), clang::Type::castAs(), CGM, commonEmitCXXMemberOrOperatorCall(), EmitCall(), clang::Expr::getExprLoc(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), MustTailCall, ReturnValue, and clang::interp::This().
EmitCXXMemberOrOperatorMemberCallExpr()
RValue CodeGenFunction::EmitCXXMemberOrOperatorMemberCallExpr (const CallExpr * CE, const CXXMethodDecl * MD, ReturnValueSlot ReturnValue, bool HasQualifier, NestedNameSpecifier * Qualifier, bool IsArrow, const Expr * Base)
Definition at line 215 of file CGExprCXX.cpp.
References clang::CXXMethodDecl::getCorrespondingMethodInClass(), clang::CXXMethodDecl::getDevirtualizedMethod(), getLangOpts(), clang::CXXMethodDecl::getParent(), and clang::CXXMethodDecl::isVirtual().
Referenced by EmitCXXMemberCallExpr(), and EmitCXXOperatorMemberCallExpr().
EmitCXXMemberPointerCallExpr()
RValue CodeGenFunction::EmitCXXMemberPointerCallExpr (const CXXMemberCallExpr * E, ReturnValueSlot ReturnValue)
Definition at line 442 of file CGExprCXX.cpp.
References clang::CodeGen::CallArgList::add(), clang::CallExpr::arguments(), clang::CodeGen::CodeGenTypes::arrangeCXXMethodCall(), clang::Type::castAs(), CGM, EmitCall(), EmitCallArgs(), clang::CodeGen::CGCXXABI::EmitLoadOfMemberFunctionPointer(), EmitLValue(), EmitPointerWithAlignment(), EmitScalarExpr(), EmitTypeCheck(), clang::CodeGen::RequiredArgs::forPrototypePlus(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), clang::CallExpr::getCallee(), getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::RecordType::getDecl(), clang::CXXMemberCallExpr::getExprLoc(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::MemberPointerType::getPointeeType(), clang::ASTContext::getPointerType(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::Expr::IgnoreParens(), clang::CodeGen::Address::invalid(), clang::CodeGen::KnownNonNull, MustTailCall, ReturnValue, TCK_MemberCall, and clang::interp::This().
Referenced by EmitCXXMemberCallExpr().
EmitCXXNewExpr()
llvm::Value * CodeGenFunction::EmitCXXNewExpr (const CXXNewExpr * E)
Definition at line 1574 of file CGExprCXX.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CGDebugInfo::addHeapAllocSiteMetadata(), std::arg(), clang::CodeGen::CodeGenFunction::ConditionalEvaluation::begin(), Builder, CalculateCookiePadding(), clang::Type::castAs(), CGM, ConvertTypeForMem(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateIsNull(), clang::CodeGen::CGBuilderTy::CreateLaunderInvariantGroup(), DeactivateCleanupBlock(), clang::CodeGen::Decl, EHStack, EmitBlock(), EmitCallArgs(), EmitCXXNewAllocSize(), EmitNewDeleteCall(), EmitNewInitializer(), EmitPointerWithAlignment(), clang::CodeGen::Address::emitRawPointer(), EmitTypeCheck(), clang::CodeGen::CodeGenFunction::ConditionalEvaluation::end(), EnterNewDeleteCleanup(), clang::CodeGen::RValue::get(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::LValueBaseInfo::getAlignmentSource(), clang::CXXNewExpr::getAllocatedType(), clang::CXXNewExpr::getAllocatedTypeSourceInfo(), clang::ASTContext::getBaseElementType(), clang::TypeLoc::getBeginLoc(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), getDebugInfo(), clang::EnumType::getDecl(), clang::Expr::getExprLoc(), clang::CXXParenListInitExpr::getInitExprs(), clang::CXXNewExpr::getInitializer(), clang::EnumDecl::getIntegerType(), clang::InitListExpr::getNumInits(), clang::FunctionProtoType::getNumParams(), clang::CXXNewExpr::getNumPlacementArgs(), clang::CXXNewExpr::getOperatorDelete(), clang::CXXNewExpr::getOperatorNew(), clang::FunctionProtoType::getParamType(), clang::CharUnits::getQuantity(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::CodeGenTypeCache::getSizeAlign(), clang::ASTContext::getSizeType(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::ASTContext::getTypeAlignInChars(), clang::TypeSourceInfo::getTypeLoc(), getTypeSize(), clang::CXXNewExpr::hasInitializer(), clang::CodeGen::CGCXXABI::InitializeArrayCookie(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::Address::invalid(), clang::CXXNewExpr::isArray(), clang::QualType::isPODType(), clang::FunctionDecl::isReplaceableGlobalAllocationFunction(), clang::FunctionDecl::isReservedGlobalPlacementOperator(), clang::InitListExpr::isStringLiteralInit(), clang::CodeGen::EHScopeStack::stable_iterator::isValid(), clang::FunctionDecl::isVariadic(), max(), clang::CXXNewExpr::passAlignment(), clang::CXXNewExpr::placement_arguments(), sanitizePerformTypeCheck(), clang::SanitizerSet::set(), clang::CodeGen::Address::setAlignment(), clang::CXXNewExpr::shouldNullCheckAllocation(), clang::CodeGen::CodeGenTypeCache::SizeTy, clang::CodeGen::EHScopeStack::stable_begin(), TCK_ConstructorCall, and clang::CodeGen::Address::withElementType().
EmitCXXOperatorMemberCallExpr()
RValue CodeGenFunction::EmitCXXOperatorMemberCallExpr (const CXXOperatorCallExpr * E, const CXXMethodDecl * MD, ReturnValueSlot ReturnValue)
Definition at line 492 of file CGExprCXX.cpp.
References EmitCXXMemberOrOperatorMemberCallExpr(), clang::CallExpr::getArg(), clang::CXXMethodDecl::isImplicitObjectMemberFunction(), and ReturnValue.
Referenced by EmitCallExpr().
EmitCXXPseudoDestructorExpr()
RValue CodeGenFunction::EmitCXXPseudoDestructorExpr (const CXXPseudoDestructorExpr * E)
Definition at line 127 of file CGExprCXX.cpp.
References clang::CodeGen::ARCPreciseLifetime, Builder, clang::Type::castAs(), clang::CodeGen::CGBuilderTy::CreateLoad(), EmitARCDestroyWeak(), EmitARCRelease(), EmitIgnoredExpr(), EmitLValue(), EmitPointerWithAlignment(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), clang::CXXPseudoDestructorExpr::getBase(), clang::CXXPseudoDestructorExpr::getDestroyedType(), clang::QualType::getObjCLifetime(), clang::QualType::getQualifiers(), clang::Expr::getType(), clang::QualType::hasStrongOrWeakObjCLifetime(), clang::CodeGen::Address::invalid(), clang::CXXPseudoDestructorExpr::isArrow(), clang::QualType::isVolatileQualified(), clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, and clang::Qualifiers::OCL_Weak.
Referenced by EmitCallExpr().
EmitCXXTemporary()
void CodeGenFunction::EmitCXXTemporary (const CXXTemporary * Temporary, QualType TempType, Address Ptr)
Emits all the code to cause the given temporary to be cleaned up.
Definition at line 1304 of file CGCleanup.cpp.
References clang::CodeGen::NormalAndEHCleanup.
Referenced by EmitCXXBindTemporaryLValue().
EmitCXXThrowExpr()
void CodeGenFunction::EmitCXXThrowExpr (const CXXThrowExpr * E, bool KeepInsertionPoint = true)
Definition at line 443 of file CGException.cpp.
References CGM, EmitTrapCall(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CXXThrowExpr::getSubExpr(), clang::Type::isObjCObjectPointerType(), and clang::T.
Referenced by EmitBranchOnBoolExpr(), and EmitLValueOrThrowExpression().
EmitCXXTryStmt()
void CodeGenFunction::EmitCXXTryStmt (const CXXTryStmt & S)
Definition at line 622 of file CGException.cpp.
EmitCXXTypeidExpr()
llvm::Value * CodeGenFunction::EmitCXXTypeidExpr (const CXXTypeidExpr * E)
Definition at line 2218 of file CGExprCXX.cpp.
References CGM, clang::Default, EmitTypeidFromVTable(), clang::CodeGen::CodeGenModule::GetAddrOfRTTIDescriptor(), getContext(), clang::CXXTypeidExpr::getExprOperand(), clang::CodeGen::CodeGenModule::GetGlobalVarAddressSpace(), getLLVMContext(), getTargetHooks(), clang::Expr::getType(), clang::CXXTypeidExpr::getTypeOperand(), clang::CXXTypeidExpr::isMostDerived(), clang::CXXTypeidExpr::isPotentiallyEvaluated(), clang::CXXTypeidExpr::isTypeOperand(), and clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast().
Referenced by EmitCXXTypeidLValue().
EmitCXXTypeidLValue()
LValue CodeGenFunction::EmitCXXTypeidLValue (const CXXTypeidExpr * E)
Definition at line 5728 of file CGExpr.cpp.
References EmitCXXTypeidExpr(), clang::Expr::getType(), and MakeNaturalAlignRawAddrLValue().
EmitCXXUuidofExpr()
Address CodeGenFunction::EmitCXXUuidofExpr (const CXXUuidofExpr * E)
Definition at line 5732 of file CGExpr.cpp.
References CGM, ConvertType(), clang::CodeGen::CodeGenModule::GetAddrOfMSGuidDecl(), clang::CXXUuidofExpr::getGuidDecl(), clang::Expr::getType(), and clang::CodeGen::ConstantAddress::withElementType().
Referenced by EmitCXXUuidofLValue().
EmitCXXUuidofLValue()
LValue CodeGenFunction::EmitCXXUuidofLValue (const CXXUuidofExpr * E)
Definition at line 5737 of file CGExpr.cpp.
References clang::CodeGen::Decl, EmitCXXUuidofExpr(), clang::Expr::getType(), and MakeAddrLValue().
EmitDecl()
void CodeGenFunction::EmitDecl (const Decl & D)
EmitDecl - Emit a declaration.
This function can be called with a null (unreachable) insert point.
Definition at line 49 of file CGDecl.cpp.
References Block, CGM, clang::CodeGen::CodeGenModule::EmitOMPDeclareMapper(), clang::CodeGen::CodeGenModule::EmitOMPDeclareReduction(), EmitVarDecl(), EmitVariablyModifiedType(), getContext(), getDebugInfo(), getDefinition(), clang::Decl::getKind(), clang::VarDecl::isLocalVarDecl(), clang::Type::isVariablyModifiedType(), and Label.
EmitDeclRefExprDbgValue()
void CodeGenFunction::EmitDeclRefExprDbgValue (const DeclRefExpr * E, const APValue & Init)
Definition at line 2745 of file CodeGenFunction.cpp.
References CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), getDebugInfo(), clang::DeclRefExpr::getDecl(), and clang::CodeGenOptions::hasReducedDebugInfo().
Referenced by tryEmitAsConstant().
EmitDeclRefLValue()
LValue CodeGenFunction::EmitDeclRefLValue (const DeclRefExpr * E)
Definition at line 2953 of file CGExpr.cpp.
References clang::CodeGen::ARCImpreciseLifetime, Builder, canEmitSpuriousReferenceToVariable(), CapturedStmtInfo, CGM, ConvertTypeForMem(), clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CodeGenModule::createUnnamedGlobalFrom(), CurCodeDecl, clang::CodeGen::Decl, clang::CodeGen::ConstantEmitter::emitAbstract(), emitBlockByrefAddress(), EmitCapturedFieldLValue(), EmitFunctionDeclLValue(), EmitGlobalNamedRegister(), EmitGlobalVarDeclLValue(), EmitLoadOfReferenceLValue(), EmitLValue(), clang::CodeGen::Address::emitRawPointer(), EmitStaticVarDecl(), EmitThreadPrivateVarDeclLValue(), clang::CodeGen::LValue::getAddress(), GetAddrOfBlockDecl(), clang::CodeGen::CodeGenModule::GetAddrOfMSGuidDecl(), clang::CodeGen::CodeGenModule::GetAddrOfTemplateParamObject(), clang::CodeGen::Address::getBasePointer(), getContext(), clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::getContextValue(), clang::DeclRefExpr::getDecl(), clang::CodeGen::Address::getElementType(), clang::Expr::getExprLoc(), clang::getLangASFromTargetAS(), getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMLinkageVarDefinition(), clang::DeclRefExpr::getLocation(), clang::CodeGen::CodeGenModule::getModuleDebugInfo(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl(), clang::CodeGen::LValue::getPointer(), clang::CodeGen::LValue::getQuals(), clang::ASTContext::getTargetAddressSpace(), getTargetHooks(), clang::CodeGen::LValue::getTBAAInfo(), clang::Expr::getType(), clang::CodeGen::Address::getType(), clang::CodeGen::LValue::getType(), getTypes(), clang::CodeGen::CodeGenModule::GetWeakRefReference(), clang::Decl::hasAttr(), clang::CodeGen::Address::invalid(), clang::DeclRefExpr::isNonOdrUse(), clang::CodeGen::CGOpenMPRuntime::isNontemporalDecl(), clang::Type::isReferenceType(), clang::Decl::isUsed(), clang::SourceLocation::isValid(), LambdaCaptureFields, clang::CodeGen::CodeGenFunction::CGCapturedStmtInfo::lookup(), MakeAddrLValue(), makeNaturalAddressForPointer(), clang::CodeGen::NotKnownNonNull, clang::NOUR_Constant, clang::NOUR_Unevaluated, clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), clang::DeclRefExpr::refersToEnclosingVariableOrCapture(), clang::Qualifiers::removeObjCGCAttr(), clang::SC_Register, clang::CodeGen::LValue::setARCPreciseLifetime(), clang::CodeGen::LValue::setNonGC(), clang::CodeGen::LValue::setNontemporal(), setObjCGCLValueClass(), clang::T, clang::VarDecl::TLS_None, clang::dataflow::var(), and clang::CodeGen::Address::withPointer().
Referenced by EmitCountedByFieldExpr(), EmitMemberExpr(), and LoadObjCSelf().
EmitDeclStmt()
void CodeGenFunction::EmitDeclStmt (const DeclStmt & S)
Definition at line 1476 of file CGStmt.cpp.
EmitDefaultStmt()
void CodeGenFunction::EmitDefaultStmt (const DefaultStmt & S, ArrayRef< const Attr * > Attrs)
Definition at line 1713 of file CGStmt.cpp.
EmitDelegateCallArg()
void CodeGenFunction::EmitDelegateCallArg (CallArgList & args, const VarDecl * param, SourceLocation loc)
EmitDelegateCallArg - We are performing a delegate call; that is, the current function is delegating to another one.
Produce a r-value suitable for passing the given parameter.
Definition at line 4154 of file CGCall.cpp.
References clang::CodeGen::CallArgList::add(), clang::CodeGen::CallArgList::addArgCleanupDeactivation(), Builder, clang::format::cleanup(), convertTempToRValue(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), CurFuncIsThunk, clang::CodeGen::RValue::get(), GetAddrOfLocalVar(), getContext(), clang::RecordType::getDecl(), getLangOpts(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::RecordDecl::isParamDestroyedInCallee(), local, clang::VarDecl::needsDestruction(), and clang::ast_matchers::type.
Referenced by EmitCallAndReturnForThunk(), EmitDelegateCXXConstructorCall(), EmitInheritedCXXConstructorCall(), EmitLambdaBlockInvokeBody(), and EmitLambdaDelegatingInvokeBody().
EmitDelegateCXXConstructorCall()
void CodeGenFunction::EmitDelegateCXXConstructorCall (const CXXConstructorDecl * Ctor, CXXCtorType CtorType, const FunctionArgList & Args, SourceLocation Loc)
Definition at line 2423 of file CGClass.cpp.
References clang::CodeGen::CallArgList::add(), CGM, CurGD, EmitCXXConstructorCall(), EmitDelegateCallArg(), clang::CodeGen::RValue::get(), getAsNaturalPointerTo(), clang::CodeGen::CodeGenModule::getCXXABI(), LoadCXXThisAddress(), clang::CodeGen::AggValueSlot::MayOverlap, clang::CodeGen::CGCXXABI::NeedsVTTParameter(), and clang::interp::This().
Referenced by EmitConstructorBody().
EmitDelegatingCXXConstructorCall()
void CodeGenFunction::EmitDelegatingCXXConstructorCall (const CXXConstructorDecl * Ctor, const FunctionArgList & Args)
Definition at line 2482 of file CGClass.cpp.
References CGM, clang::Ctor_Complete, CurGD, clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::Dtor_Base, clang::Dtor_Complete, clang::CodeGen::EHCleanup, EHStack, EmitAggExpr(), clang::CodeGen::AggValueSlot::forAddr(), clang::GlobalDecl::getCtorType(), clang::CXXRecordDecl::getDestructor(), clang::CXXCtorInitializer::getInit(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CXXMethodDecl::getParent(), clang::CXXRecordDecl::hasTrivialDestructor(), clang::CXXConstructorDecl::init_begin(), clang::CXXConstructorDecl::isDelegatingConstructor(), clang::CodeGen::AggValueSlot::IsDestructed, clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::AggValueSlot::IsNotZeroed, clang::CodeGen::AggValueSlot::IsSanitizerChecked, LoadCXXThisAddress(), and clang::CodeGen::AggValueSlot::MayOverlap.
Referenced by EmitCtorPrologue().
EmitDeleteCall()
void CodeGenFunction::EmitDeleteCall (const FunctionDecl * DeleteFD, llvm::Value * Ptr, QualType DeleteTy, llvm::Value * NumElements = nullptr, CharUnits CookieSize = CharUnits())
Definition at line 1801 of file CGExprCXX.cpp.
References Builder, clang::Type::castAs(), CGM, ConvertType(), clang::CodeGen::CodeGenTypes::ConvertType(), CreateTempAlloca(), EmitNewDeleteCall(), clang::CodeGen::RValue::get(), clang::CodeGen::RValue::getAggregate(), clang::CharUnits::getAsAlign(), getContext(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::FunctionDecl::getOverloadedOperator(), clang::CharUnits::getQuantity(), clang::ValueDecl::getType(), getTypes(), clang::ASTContext::getTypeSizeInChars(), getUsualDeleteParams(), clang::CharUnits::isZero(), clang::CodeGen::CodeGenTypeCache::SizeTy, and clang::ASTContext::toCharUnitsFromBits().
Referenced by EmitDestroyingObjectDelete(), and EnterDtorCleanups().
emitDestroy()
void CodeGenFunction::emitDestroy (Address addr, QualType type, Destroyer * destroyer, bool useEHCleanupForArray)
emitDestroy - Immediately perform the destruction of the given object.
Parameters
addr - the address of the object; a type*
type - the type of the object; if an array type, all objects are destroyed in reverse order
destroyer - the function to call to destroy individual elements
useEHCleanupForArray - whether an EH cleanup should be used when destroying array elements, in case one of the destructions throws an exception
Definition at line 2321 of file CGDecl.cpp.
References clang::CharUnits::alignmentOfArrayElement(), clang::ast_matchers::arrayType, Builder, clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), emitArrayDestroy(), emitArrayLength(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::ASTContext::getAsArrayType(), getContext(), clang::CodeGen::Address::getElementType(), length(), and clang::ast_matchers::type.
Referenced by generateDestroyHelper().
EmitDestructorBody()
void CodeGenFunction::EmitDestructorBody (FunctionArgList & Args)
EmitDestructorBody - Emits the body of the current destructor.
Definition at line 1438 of file CGClass.cpp.
References Builder, CanSkipVTablePointerInitialization(), CGM, clang::CodeGen::CGBuilderTy::CreateLaunderInvariantGroup(), CurFn, CurGD, clang::Dtor_Base, clang::Dtor_Comdat, clang::Dtor_Complete, clang::Dtor_Deleting, EmitAsanPrologueOrEpilogue(), EmitCXXDestructorCall(), EmitStmt(), EmitTrapCall(), EnterCXXTryStmt(), EnterDtorCleanups(), ExitCXXTryStmt(), clang::CodeGen::CodeGenFunction::RunCleanupsScope::ForceCleanup(), clang::FunctionDecl::getBody(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::GlobalDecl::getDecl(), clang::GlobalDecl::getDtorType(), clang::CXXMethodDecl::getFunctionObjectParameterType(), getLangOpts(), clang::CXXMethodDecl::getParent(), getTarget(), HaveInsertPoint(), incrementProfileCounter(), InitializeVTablePointers(), clang::CXXRecordDecl::isAbstract(), clang::Decl::isImplicit(), LoadCXXThis(), LoadCXXThisAddress(), and maybeCreateMCDCCondBitmap().
Referenced by GenerateCode().
EmitDoStmt()
void CodeGenFunction::EmitDoStmt (const DoStmt & S, ArrayRef< const Attr * > Attrs = std::nullopt)
Definition at line 1022 of file CGStmt.cpp.
EmitDynamicCast()
llvm::Value * CodeGenFunction::EmitDynamicCast (Address V, const CXXDynamicCastExpr * DCE)
Definition at line 2263 of file CGExprCXX.cpp.
References Builder, clang::Type::castAs(), CGM, createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateIsNull(), EmitBlock(), EmitBranch(), clang::CodeGen::CGCXXABI::emitDynamicCastCall(), EmitDynamicCastToNull(), clang::CodeGen::CGCXXABI::emitDynamicCastToVoid(), clang::CodeGen::CGCXXABI::emitExactDynamicCast(), clang::CodeGen::CodeGenModule::EmitExplicitCastExprType(), EmitTypeCheck(), clang::Type::getAs(), clang::Type::getAsCXXRecordDecl(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::Expr::getExprLoc(), clang::Type::getPointeeType(), clang::CastExpr::getSubExpr(), clang::Expr::getType(), clang::Value::getType(), clang::ExplicitCastExpr::getTypeAsWritten(), clang::CXXDynamicCastExpr::isAlwaysNull(), clang::CXXRecordDecl::isEffectivelyFinal(), IsNull, clang::Type::isPointerType(), clang::Type::isRecordType(), clang::Type::isVoidPointerType(), clang::CodeGen::CGCXXABI::shouldDynamicCastCallBeNullChecked(), clang::CodeGen::CGCXXABI::shouldEmitExactDynamicCast(), clang::T, and TCK_DynamicOperation.
Referenced by EmitCastLValue().
EmitEndEHSpec()
void CodeGenFunction::EmitEndEHSpec (const Decl * D)
EmitEndEHSpec - Emit the end of the exception spec.
Definition at line 580 of file CGException.cpp.
References clang::CodeGen::EHScopeStack::begin(), clang::FunctionProtoType::canThrow(), CGM, clang::CPlusPlus17, clang::CT_Cannot, EHStack, emitFilterDispatchBlock(), clang::CodeGen::EHScopeStack::empty(), clang::EST_Dynamic, clang::EST_DynamicNone, clang::Type::getAs(), clang::TargetInfo::getCXXABI(), clang::FunctionProtoType::getExceptionSpecType(), getLangOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), getTarget(), clang::ValueDecl::getType(), clang::LangOptions::hasWasmExceptions(), clang::TargetCXXABI::isMicrosoft(), clang::CodeGen::EHScopeStack::popFilter(), and clang::CodeGen::EHScopeStack::popTerminate().
Referenced by FinishFunction().
EmitExprAsInit()
void CodeGenFunction::EmitExprAsInit (const Expr * init, const ValueDecl * D, LValue lvalue, bool capturedByInit)
EmitExprAsInit - Emits the code necessary to initialize a location in memory with the given initializer.
Emit an expression as an initializer for an object (variable, field, etc.) at the given location.
The expression is not necessarily the normal initializer for the object, and the address is not necessarily its normal location.
Parameters
init the initializing expression
D the object to act as if we're initializing
lvalue the lvalue to initialize
capturedByInit true if D is a __block variable whose address is potentially changed by the initializer
Definition at line 2057 of file CGDecl.cpp.
References clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, drillIntoBlockVariable(), EmitAggExpr(), EmitAtomicInit(), EmitComplexExpr(), EmitReferenceBindingToExpr(), EmitScalarInit(), EmitStoreOfComplex(), EmitStoreThroughLValue(), clang::CodeGen::AggValueSlot::forLValue(), getEvaluationKind(), getOverlapForFieldInit(), clang::ValueDecl::getType(), clang::CodeGen::AggValueSlot::IsDestructed, clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::AggValueSlot::MayOverlap, clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, and clang::ast_matchers::type.
Referenced by EmitAutoVarInit(), EmitInitializerForField(), and emitPrivatesInit().
EmitExtendGCLifetime()
void CodeGenFunction::EmitExtendGCLifetime (llvm::Value * object)
EmitExtendGCLifetime - Given a pointer to an Objective-C object, make sure it survives garbage collection until this point.
Definition at line 3671 of file CGObjC.cpp.
References clang::CodeGen::RequiredArgs::All, EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
EmitExtVectorElementExpr()
LValue CodeGenFunction::EmitExtVectorElementExpr (const ExtVectorElementExpr * E)
Definition at line 4594 of file CGExpr.cpp.
References Builder, clang::Type::castAs(), CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::Decl, EmitLValue(), EmitPointerWithAlignment(), EmitScalarExpr(), clang::ExtVectorElementExpr::getBase(), clang::ExtVectorElementExpr::getEncodedElementAccess(), getLLVMContext(), clang::Expr::getType(), clang::ExtVectorElementExpr::isArrow(), clang::Expr::isGLValue(), clang::Type::isVectorType(), MakeAddrLValue(), clang::CodeGen::LValue::MakeExtVectorElt(), clang::ast_matchers::type, and clang::QualType::withCVRQualifiers().
EmitExtVectorElementLValue()
Address CodeGenFunction::EmitExtVectorElementLValue (LValue V)
Generates lvalue for partial ext_vector access.
Definition at line 2296 of file CGExpr.cpp.
References Builder, clang::Type::castAs(), CGM, clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP(), getAccessedFieldNo(), clang::CodeGen::LValue::getExtVectorAddress(), clang::CodeGen::LValue::getExtVectorElts(), clang::CodeGen::LValue::getType(), clang::CodeGen::CodeGenModule::getTypes(), and clang::CodeGen::Address::withElementType().
Referenced by EmitArraySubscriptExpr().
EmitFieldAnnotations()
Address CodeGenFunction::EmitFieldAnnotations (const FieldDecl * D, Address V)
Emit field annotations for the given field & value.
Returns the annotation result.
Definition at line 2863 of file CodeGenFunction.cpp.
References Builder, CGM, clang::CodeGen::CodeGenTypeCache::ConstGlobalsPtrTy, EmitAnnotationCall(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::Decl::getLocation(), clang::Decl::hasAttr(), clang::Decl::specific_attrs(), and V.
Referenced by EmitLValueForField().
EmitFieldSYCLAnnotations()
Address CodeGenFunction::EmitFieldSYCLAnnotations (const FieldDecl * D, Address V)
Emit sycl field annotations for given field & value.
Returns the annotation result.
Definition at line 2921 of file CodeGenFunction.cpp.
References Builder, CGM, clang::CodeGen::CodeGenTypeCache::ConstGlobalsPtrTy, clang::CodeGen::Address::emitRawPointer(), EmitSYCLAnnotationCall(), clang::CodeGen::Address::getAlignment(), clang::Decl::getAttr(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::Decl::getLocation(), and V.
Referenced by EmitLValueForField().
EmitForStmt()
void CodeGenFunction::EmitForStmt (const ForStmt & S, ArrayRef< const Attr * > Attrs = std::nullopt)
Definition at line 1095 of file CGStmt.cpp.
EmitForwardingCallToLambda()
void CodeGenFunction::EmitForwardingCallToLambda (const CXXMethodDecl * LambdaCallOperator, CallArgList & CallArgs, const CGFunctionInfo * CallOpFnInfo = nullptr, llvm::Constant * CallOpFn = nullptr)
Definition at line 2937 of file CGClass.cpp.
References clang::CodeGen::CodeGenTypes::arrangeCXXMethodDeclaration(), clang::transformer::callArgs(), clang::Type::castAs(), CGM, EmitARCRetainAutoreleasedReturnValue(), EmitBranchThroughCleanup(), EmitCall(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::ABIArgInfo::getKind(), getLangOpts(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), clang::FunctionType::getReturnType(), clang::CodeGen::CGFunctionInfo::getReturnType(), clang::CodeGen::RValue::getScalarVal(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), hasScalarEvaluationKind(), clang::CodeGen::ABIArgInfo::Indirect, clang::CodeGen::ReturnValueSlot::isNull(), ReturnBlock, and ReturnValue.
Referenced by EmitLambdaBlockInvokeBody(), and EmitLambdaDelegatingInvokeBody().
EmitFromMemory()
llvm::Value * CodeGenFunction::EmitFromMemory (llvm::Value * Value, QualType Ty)
EmitFromMemory - Change a scalar value from its memory representation to its value representation.
Definition at line 2023 of file CGExpr.cpp.
References Builder, ConvertType(), emitBoolVecConversion(), getContext(), clang::Value::getType(), getTypeSize(), hasBooleanRepresentation(), clang::Type::isExtVectorBoolType(), and V.
Referenced by EmitFromInt(), EmitLoadOfScalar(), and EmitStoreThroughBitfieldLValue().
EmitFunctionBody()
void CodeGenFunction::EmitFunctionBody (const Stmt * Body)
Definition at line 1515 of file CodeGenFunction.cpp.
References incrementProfileCounter(), and maybeCreateMCDCCondBitmap().
Referenced by GenerateCode().
EmitFunctionEpilog()
void CodeGenFunction::EmitFunctionEpilog (const CGFunctionInfo & FI, bool EmitRetDbgLoc, SourceLocation EndLoc)
EmitFunctionEpilog - Emit the target specific LLVM code to return the given temporary.
Definition at line 3871 of file CGCall.cpp.
References AutoreleaseResult, clang::CodeGen::CGBlockInfo::BlockExpression, BlockInfo, Builder, CGM, clang::CodeGen::ABIArgInfo::CoerceAndExpand, ConvertType(), clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), CreateCoercedLoad(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), CurCodeDecl, CurFn, CurFuncDecl, clang::CodeGen::ABIArgInfo::Direct, emitAddressAtOffset(), emitAutoreleaseOfResult(), EmitCMSEClearRecord(), EmitLoadOfComplex(), EmitReturnValueCheck(), EmitStoreOfComplex(), EmitStoreOfScalar(), EmitUnreachable(), clang::CodeGen::ABIArgInfo::Expand, clang::CodeGen::ABIArgInfo::Extend, findDominatingStoreToReturnValue(), clang::CodeGen::CGFunctionInfo::getArgStruct(), clang::QualType::getCanonicalType(), clang::CodeGen::ABIArgInfo::getCoerceAndExpandType(), clang::CodeGen::ABIArgInfo::getCoerceToType(), getContext(), clang::CodeGen::ABIArgInfo::getDirectOffset(), clang::CodeGen::Address::getElementType(), getEvaluationKind(), clang::BlockExpr::getFunctionType(), clang::CodeGen::ABIArgInfo::getInAllocaFieldIndex(), clang::CodeGen::ABIArgInfo::getInAllocaSRet(), clang::CodeGen::ABIArgInfo::getKind(), getLangOpts(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), clang::FunctionType::getReturnType(), clang::CodeGen::CGFunctionInfo::getReturnType(), clang::CodeGen::ABIArgInfo::getUnpaddedCoerceAndExpandType(), hasAggregateEvaluationKind(), clang::Decl::hasAttr(), clang::CodeGen::ABIArgInfo::Ignore, clang::CodeGen::ABIArgInfo::InAlloca, clang::CodeGen::ABIArgInfo::Indirect, clang::CodeGen::ABIArgInfo::IndirectAliased, clang::CodeGen::CGFunctionInfo::isNoReturn(), clang::Type::isObjCRetainableType(), clang::CodeGen::ABIArgInfo::isPaddingForCoerceAndExpand(), clang::CodeGen::CGFunctionInfo::isReturnsRetained(), clang::CodeGen::ABIArgInfo::isSRetAfterThis(), clang::CodeGen::Address::isValid(), clang::CodeGen::LValue::MakeAddr(), MakeAddrLValue(), MakeNaturalAlignAddrLValue(), clang::interp::Ret(), ReturnValue, clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, V, and clang::CodeGen::Address::withElementType().
Referenced by FinishFunction().
EmitFunctionProlog()
void CodeGenFunction::EmitFunctionProlog (const CGFunctionInfo & FI, llvm::Function * Fn, const FunctionArgList & Args)
EmitFunctionProlog - Emit the target specific LLVM code to load the arguments for the given function.
This is also responsible for naming the LLVM function arguments.
Definition at line 2999 of file CGCall.cpp.
References std::arg(), clang::CodeGen::CGFunctionInfo::arg_begin(), clang::CodeGen::CGFunctionInfo::arg_size(), Builder, CGM, clang::CodeGen::ABIArgInfo::CoerceAndExpand, ConvertType(), clang::CodeGen::CodeGenTypes::ConvertType(), ConvertTypeForMem(), CreateCoercedStore(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), CreateTempAlloca(), CurCodeDecl, clang::CodeGen::ABIArgInfo::Direct, EHStack, emitAddressAtOffset(), emitArgumentDemotion(), EmitLoadOfScalar(), EmitParmDecl(), clang::CodeGen::Address::emitRawPointer(), EmitScalarExpr(), clang::CodeGen::ABIArgInfo::Expand, clang::CodeGen::ABIArgInfo::Extend, clang::CodeGen::CodeGenFunction::ParamValue::forDirect(), clang::CodeGen::CodeGenFunction::ParamValue::forIndirect(), clang::FunctionType::ExtParameterInfo::getABI(), clang::QualType::getAddressSpace(), clang::CodeGen::RawAddress::getAlignment(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::CGFunctionInfo::getArgStruct(), clang::CodeGen::CGFunctionInfo::getArgStructAlignment(), clang::Type::getAs(), clang::CharUnits::getAsAlign(), clang::Decl::getAttr(), clang::DeclaratorDecl::getBeginLoc(), clang::CodeGen::ABIArgInfo::getCanBeFlattened(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::ABIArgInfo::getCoerceAndExpandType(), clang::CodeGen::ABIArgInfo::getCoerceToType(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::ABIArgInfo::getDirectOffset(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CGFunctionInfo::getExtParameterInfo(), clang::CodeGen::ABIArgInfo::getInAllocaFieldIndex(), clang::CodeGen::ABIArgInfo::getInAllocaIndirect(), clang::CodeGen::ABIArgInfo::getIndirectAlign(), clang::CodeGen::ABIArgInfo::getIndirectRealign(), clang::CodeGen::ABIArgInfo::getKind(), getLLVMContext(), clang::NamedDecl::getName(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), getNonNullAttr(), clang::Type::getPointeeType(), clang::CodeGen::RawAddress::getPointer(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), getTarget(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), getTypes(), clang::ASTContext::getTypeSizeInChars(), clang::SanitizerSet::has(), clang::Decl::hasAttr(), hasScalarEvaluationKind(), clang::CodeGen::ABIArgInfo::Ignore, clang::CodeGen::ABIArgInfo::InAlloca, clang::CodeGen::ABIArgInfo::Indirect, clang::CodeGen::ABIArgInfo::IndirectAliased, clang::CodeGen::CGFunctionInfoArgInfo::info, clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::CodeGen::Address::invalid(), clang::Type::isConstantSizeType(), clang::CodeGen::ABIArgInfo::isDirect(), clang::Type::isIncompleteType(), clang::CodeGen::ABIArgInfo::isIndirectAliased(), clang::CodeGen::ABIArgInfo::isPaddingForCoerceAndExpand(), clang::Type::isPointerType(), clang::QualType::isRestrictQualified(), clang::CodeGen::KnownNonNull, MakeAddrLValue(), makeNaturalAddressForPointer(), clang::CodeGen::NormalCleanup, ReturnValue, SanOpts, clang::Static, clang::SwiftErrorResult, clang::CodeGen::CGFunctionInfoArgInfo::type, V, and clang::CodeGen::Address::withElementType().
Referenced by StartFunction().
EmitGotoStmt()
void CodeGenFunction::EmitGotoStmt (const GotoStmt & S)
Definition at line 753 of file CGStmt.cpp.
EmitHexagonBuiltinExpr()
Value * CodeGenFunction::EmitHexagonBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 23493 of file CGBuiltin.cpp.
References EmitPointerWithAlignment(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::CallExpr::getArg(), getIntrinsicForHexagonNonClangBuiltin(), and ID.
Referenced by EmitTargetArchBuiltinExpr().
EmitHLSLBuiltinExpr()
Value * CodeGenFunction::EmitHLSLBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 18291 of file CGBuiltin.cpp.
References clang::CallExpr::getArg(), and clang::HLSL.
EmitIfStmt()
void CodeGenFunction::EmitIfStmt (const IfStmt & S)
Definition at line 785 of file CGStmt.cpp.
EmitIgnoredConditionalOperator()
void CodeGenFunction::EmitIgnoredConditionalOperator (const AbstractConditionalOperator * E)
Definition at line 5140 of file CGExpr.cpp.
References EmitAggExprToLValue(), EmitIgnoredExpr(), clang::Expr::getType(), hasAggregateEvaluationKind(), and clang::Expr::isGLValue().
Referenced by EmitIgnoredExpr().
EmitIgnoredExpr()
void CodeGenFunction::EmitIgnoredExpr (const Expr * E)
EmitIgnoredExpr - Emit an expression in a context which ignores the result.
EmitIgnoredExpr - Emit code to compute the specified expression, ignoring the result.
Definition at line 197 of file CGExpr.cpp.
References EmitAnyExpr(), EmitIgnoredConditionalOperator(), EmitLValue(), getContext(), clang::CodeGen::AggValueSlot::ignored(), clang::Expr::IgnoreParenNoopCasts(), clang::Expr::isPRValue(), and clang::OK_BitField.
Referenced by EmitBinaryOperatorLValue(), EmitCall(), EmitCallee(), EmitCXXPseudoDestructorExpr(), EmitIgnoredConditionalOperator(), emitInitWithReductionInitializer(), EmitMaterializeTemporaryExpr(), EmitMemberExpr(), emitPostUpdateForReductionClause(), emitPseudoObjectExpr(), emitReductionCombiner(), and EmitVariablyModifiedType().
emitImplicitAssignmentOperatorBody()
void CodeGenFunction::emitImplicitAssignmentOperatorBody (FunctionArgList & Args)
Definition at line 1553 of file CGClass.cpp.
References clang::CompoundStmt::body(), CurGD, clang::FunctionDecl::getBody(), clang::GlobalDecl::getDecl(), clang::Stmt::getSourceRange(), incrementProfileCounter(), and maybeCreateMCDCCondBitmap().
Referenced by GenerateCode().
EmitIndirectGotoStmt()
void CodeGenFunction::EmitIndirectGotoStmt (const IndirectGotoStmt & S)
Definition at line 764 of file CGStmt.cpp.
EmitInheritedCXXConstructorCall()
void CodeGenFunction::EmitInheritedCXXConstructorCall (const CXXConstructorDecl * D, bool ForVirtualBase, Address This, bool InheritedFromVBase, const CXXInheritedCtorInitExpr * E)
Emit a call to a constructor inherited from a base class, passing the current constructor's arguments along unmodified (without even making a copy).
Definition at line 2271 of file CGClass.cpp.
References CGM, clang::Ctor_Base, CurCodeDecl, EmitCXXConstructorCall(), EmitDelegateCallArg(), clang::CodeGen::RValue::get(), getAsNaturalPointerTo(), getContext(), clang::TargetInfo::getCXXABI(), clang::CXXInheritedCtorInitExpr::getLocation(), clang::FunctionDecl::getNumParams(), clang::Type::getPointeeType(), clang::CodeGen::CodeGenModule::getTarget(), clang::CXXMethodDecl::getThisType(), clang::TargetCXXABI::hasConstructorVariants(), clang::CodeGen::AggValueSlot::MayOverlap, and clang::interp::This().
EmitInitializerForField()
void CodeGenFunction::EmitInitializerForField (FieldDecl * Field, LValue LHS, Expr * Init)
Definition at line 692 of file CGClass.cpp.
References clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, EmitAggExpr(), EmitComplexExprIntoLValue(), EmitExprAsInit(), EmitScalarExpr(), EmitStoreThroughLValue(), clang::CodeGen::AggValueSlot::forLValue(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), getEvaluationKind(), getOverlapForFieldInit(), clang::CodeGen::AggValueSlot::IsDestructed, clang::QualType::isDestructedType(), clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::AggValueSlot::IsNotZeroed, clang::CodeGen::AggValueSlot::IsSanitizerChecked, clang::CodeGen::LValue::isSimple(), needsEHCleanup(), pushEHDestroy(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
Referenced by EmitMemberInitializer().
EmitInitListLValue()
LValue CodeGenFunction::EmitInitListLValue (const InitListExpr * E)
Definition at line 5043 of file CGExpr.cpp.
References EmitAggExprToLValue(), EmitLValue(), clang::InitListExpr::getInit(), clang::Expr::isGLValue(), and clang::InitListExpr::isTransparent().
EmitInlinedInheritingCXXConstructorCall()
void CodeGenFunction::EmitInlinedInheritingCXXConstructorCall (const CXXConstructorDecl * Ctor, CXXCtorType CtorType, bool ForVirtualBase, bool Delegating, CallArgList & Args)
Emit a call to an inheriting constructor (that is, one that invokes a constructor inherited from a base class) by inlining its definition.
This is necessary if the ABI does not support forwarding the arguments to the base class constructor (because they're variadic or similar).
Definition at line 2320 of file CGClass.cpp.
References clang::CodeGen::CGCXXABI::addImplicitConstructorArgs(), BuildFunctionArgList(), CGM, CreateIRTemp(), CurGD, clang::Delegating, EmitCtorPrologue(), clang::CodeGen::CGCXXABI::EmitInstanceFunctionProlog(), EmitParmDecl(), FnRetTy, clang::CodeGen::CodeGenFunction::ParamValue::forDirect(), clang::CodeGen::CodeGenFunction::ParamValue::forIndirect(), clang::CodeGen::RValue::getAggregateAddress(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::RValue::isComplex(), clang::CodeGen::RValue::isScalar(), clang::Type::isVoidType(), and ReturnValue.
Referenced by EmitCXXConstructorCall().
EmitIntelFPGAFieldAnnotations() [1/2]
Address CodeGenFunction::EmitIntelFPGAFieldAnnotations (const FieldDecl * D, Address V, StringRef AnnotStr)
Emit Intel FPGA field annotations for the given field and value.
Returns the annotation result.
Definition at line 2943 of file CodeGenFunction.cpp.
References clang::Decl::getLocation().
Referenced by EmitLValueForField().
EmitIntelFPGAFieldAnnotations() [2/2]
Address CodeGenFunction::EmitIntelFPGAFieldAnnotations (SourceLocation Location, Address V, StringRef AnnotStr)
Definition at line 2949 of file CodeGenFunction.cpp.
References Builder, CGM, clang::CodeGen::CodeGenTypeCache::ConstGlobalsPtrTy, EmitAnnotationCall(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLLVMContext(), and V.
EmitIntelFPGAMemBuiltin()
RValue CodeGenFunction::EmitIntelFPGAMemBuiltin (const CallExpr * E)
Definition at line 23717 of file CGBuiltin.cpp.
References clang::Function, clang::CodeGen::RValue::get(), clang::CallExpr::getArg(), clang::Expr::getIntegerConstantExpr(), clang::CallExpr::getNumArgs(), clang::Value::getType(), INT_MIN, and clang::threadSafety::sx::toString().
EmitIntelFPGARegBuiltin()
RValue CodeGenFunction::EmitIntelFPGARegBuiltin (const CallExpr * E, ReturnValueSlot ReturnValue)
Definition at line 23681 of file CGBuiltin.cpp.
References clang::CodeGen::RValue::getAggregate(), clang::CallExpr::getArg(), clang::Expr::getExprLoc(), clang::QualType::getQualifiers(), clang::Expr::getType(), clang::Type::isRecordType(), and V.
EmitIntelSYCLAllocaBuiltin()
RValue CodeGenFunction::EmitIntelSYCLAllocaBuiltin (unsigned BuiltinID, const CallExpr * E, ReturnValueSlot ReturnValue)
Definition at line 23927 of file CGBuiltin.cpp.
References clang::DeclRefExpr::Create(), clang::SYCLUniqueStableIdExpr::Create(), clang::TemplateArgumentList::get(), clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsType(), clang::CallExpr::getDirectCallee(), clang::Expr::getExprLoc(), clang::FunctionDecl::getTemplateSpecializationArgs(), clang::ValueDecl::getType(), clang::CodeGen::KnownNonNull, and clang::VK_LValue.
EmitIntelSYCLPtrAnnotationBuiltin()
RValue CodeGenFunction::EmitIntelSYCLPtrAnnotationBuiltin (const CallExpr * E)
Definition at line 23890 of file CGBuiltin.cpp.
References clang::Expr::EvaluateAsRValue(), clang::Function, clang::CodeGen::RValue::get(), clang::CallExpr::getArg(), clang::Expr::getExprLoc(), clang::Expr::getIntegerConstantExpr(), clang::CallExpr::getNumArgs(), clang::StringLiteral::getString(), clang::Value::getType(), clang::Expr::IgnoreParenCasts(), and clang::threadSafety::sx::toString().
EmitInvariantStart()
void CodeGenFunction::EmitInvariantStart (llvm::Constant * Addr, CharUnits Size)
Definition at line 159 of file CGDeclCXX.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLLVMContext(), ID, and clang::CodeGen::CodeGenTypeCache::Int64Ty.
Referenced by EmitDeclInvariant(), and GenerateCXXGlobalInitFunc().
EmitIvarOffset()
llvm::Value * CodeGenFunction::EmitIvarOffset (const ObjCInterfaceDecl * Interface, const ObjCIvarDecl * Ivar)
Definition at line 5771 of file CGExpr.cpp.
References CGM, clang::CodeGen::CGObjCRuntime::EmitIvarOffset(), clang::CodeGen::CodeGenModule::getObjCRuntime(), and clang::Interface.
Referenced by EmitIvarOffsetAsPointerDiff().
EmitIvarOffsetAsPointerDiff()
llvm::Value * CodeGenFunction::EmitIvarOffsetAsPointerDiff (const ObjCInterfaceDecl * Interface, const ObjCIvarDecl * Ivar)
Definition at line 5777 of file CGExpr.cpp.
References Builder, ConvertType(), EmitIvarOffset(), getContext(), clang::ASTContext::getPointerDiffType(), getTypes(), and clang::Interface.
Referenced by generateObjCGetterBody(), and generateObjCSetterBody().
EmitKCFIOperandBundle()
void CodeGenFunction::EmitKCFIOperandBundle (const CGCallee & Callee, SmallVectorImpl< llvm::OperandBundleDef > & Bundles)
Definition at line 3117 of file CodeGenFunction.cpp.
References CGM, clang::CodeGen::CodeGenModule::CreateKCFITypeId(), and clang::FunctionProtoType::desugar().
Referenced by EmitCall().
EmitLabel()
void CodeGenFunction::EmitLabel (const LabelDecl * D)
EmitLabel - Emit the block for the given label.
It is legal to call this function even if there is no current insertion point.
Definition at line 643 of file CGStmt.cpp.
References clang::CodeGen::CodeGenFunction::LexicalScope::addLabel(), Builder, CGM, EHStack, EmitBlock(), clang::CodeGen::CodeGenFunction::JumpDest::getBlock(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getDebugInfo(), getJumpDestInCurrentScope(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::CodeGen::CodeGenFunction::JumpDest::getScopeDepth(), clang::LabelDecl::getStmt(), clang::CodeGen::EHScopeStack::hasNormalCleanups(), clang::CodeGenOptions::hasReducedDebugInfo(), incrementProfileCounter(), clang::CodeGen::CodeGenFunction::JumpDest::isValid(), clang::CodeGen::EHScopeStack::stable_iterator::isValid(), ResolveBranchFixups(), clang::CodeGen::CodeGenFunction::JumpDest::setScopeDepth(), and clang::CodeGen::EHScopeStack::stable_begin().
EmitLabelStmt()
void CodeGenFunction::EmitLabelStmt (const LabelStmt & S)
Definition at line 702 of file CGStmt.cpp.
EmitLambdaBlockInvokeBody()
void CodeGenFunction::EmitLambdaBlockInvokeBody ()
Definition at line 2979 of file CGClass.cpp.
References clang::CodeGen::CallArgList::add(), BlockInfo, clang::BlockDecl::capture_begin(), CGM, CurCodeDecl, EmitDelegateCallArg(), EmitForwardingCallToLambda(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::RValue::get(), GetAddrOfBlockDecl(), clang::Type::getAsCXXRecordDecl(), getAsNaturalPointerTo(), clang::CodeGen::CGBlockInfo::getBlockDecl(), getContext(), clang::CXXRecordDecl::getLambdaCallOperator(), clang::ASTContext::getPointerType(), clang::ValueDecl::getType(), clang::CXXRecordDecl::isGenericLambda(), clang::FunctionDecl::isVariadic(), and clang::BlockDecl::parameters().
Referenced by GenerateBlockFunction().
EmitLambdaDelegatingInvokeBody()
void CodeGenFunction::EmitLambdaDelegatingInvokeBody (const CXXMethodDecl * MD, CallArgList & CallArgs)
Definition at line 3031 of file CGClass.cpp.
References clang::TemplateArgumentList::asArray(), EmitDelegateCallArg(), EmitForwardingCallToLambda(), EmitLambdaInAllocaImplFn(), clang::FunctionTemplateDecl::findSpecialization(), clang::FunctionDecl::getDescribedFunctionTemplate(), clang::CXXRecordDecl::getLambdaCallOperator(), clang::CXXMethodDecl::getParent(), clang::FunctionDecl::getTemplateSpecializationArgs(), clang::FunctionDecl::isFunctionTemplateSpecialization(), clang::CXXRecordDecl::isGenericLambda(), and clang::FunctionDecl::parameters().
Referenced by EmitLambdaInAllocaCallOpBody(), and EmitLambdaStaticInvokeBody().
EmitLambdaInAllocaCallOpBody()
void CodeGenFunction::EmitLambdaInAllocaCallOpBody (const CXXMethodDecl * MD)
Definition at line 3065 of file CGClass.cpp.
References clang::CodeGen::CallArgList::add(), CGM, CurFn, EmitLambdaDelegatingInvokeBody(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::RValue::get(), getContext(), clang::CXXMethodDecl::getParent(), clang::ASTContext::getPointerType(), clang::ASTContext::getRecordType(), and clang::FunctionDecl::isVariadic().
Referenced by GenerateCode().
EmitLambdaInAllocaImplFn()
void CodeGenFunction::EmitLambdaInAllocaImplFn (const CXXMethodDecl * CallOp, const CGFunctionInfo ** ImplFnInfo, llvm::Function ** ImplFn)
Definition at line 3083 of file CGClass.cpp.
References clang::CodeGen::CGFunctionInfo::arg_begin(), clang::CodeGen::CGFunctionInfo::arg_end(), clang::CodeGen::CodeGenTypes::arrangeCXXMethodDeclaration(), clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(), CGM, GenerateCode(), clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::GlobalDecl::getDecl(), clang::CodeGen::CGFunctionInfo::getExtInfo(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CGFunctionInfo::getRequiredArgs(), clang::CodeGen::CGFunctionInfo::getReturnType(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::IsDelegateCall, clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), and clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition().
Referenced by EmitLambdaDelegatingInvokeBody().
EmitLambdaStaticInvokeBody()
void CodeGenFunction::EmitLambdaStaticInvokeBody (const CXXMethodDecl * MD)
Definition at line 3009 of file CGClass.cpp.
References clang::CodeGen::CallArgList::add(), CGM, CreateMemTemp(), EmitLambdaDelegatingInvokeBody(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::RValue::get(), getContext(), clang::CXXMethodDecl::getParent(), clang::ASTContext::getPointerType(), clang::ASTContext::getRecordType(), and clang::FunctionDecl::isVariadic().
Referenced by GenerateCode().
EmitLambdaVLACapture()
void clang::CodeGen::CodeGenFunction::EmitLambdaVLACapture (const VariableArrayType * VAT, LValue LV) inline
Definition at line 2365 of file CodeGenFunction.h.
References EmitStoreThroughLValue(), clang::CodeGen::RValue::get(), and clang::VariableArrayType::getSizeExpr().
EmitLandingPad()
llvm::BasicBlock * CodeGenFunction::EmitLandingPad ()
Emits a landing pad for the current EH stack.
Definition at line 825 of file CGException.cpp.
References clang::CodeGen::EHScopeStack::begin(), Builder, clang::CodeGen::EHScope::Catch, CGM, clang::CodeGen::EHScope::Cleanup, createBasicBlock(), clang::CodeGen::ApplyDebugLocation::CreateDefaultArtificial(), clang::CodeGen::CGBuilderTy::CreateStore(), EHStack, EmitBlock(), clang::CodeGen::EHScopeStack::end(), clang::CodeGen::EHScope::Filter, clang::CodeGen::EHScopeStack::find(), clang::CodeGen::CatchTypeInfo::Flags, clang::CodeGen::EHScope::getCachedLandingPad(), getCatchAllValue(), getEHDispatchBlock(), getEHSelectorSlot(), getExceptionSlot(), clang::CodeGen::EHFilterScope::getFilter(), clang::CodeGen::EHCatchScope::getHandler(), clang::CodeGen::EHScopeStack::getInnermostEHScope(), clang::CodeGen::EHScope::getKind(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::EHFilterScope::getNumFilters(), clang::CodeGen::EHCatchScope::getNumHandlers(), getTerminateLandingPad(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::EHScopeStack::requiresLandingPad(), clang::CodeGen::CatchTypeInfo::RTTI, clang::CodeGen::EHScope::Terminate, and clang::CodeGen::EHCatchScope::Handler::Type.
Referenced by getInvokeDestImpl().
EmitLifetimeEnd()
void CodeGenFunction::EmitLifetimeEnd (llvm::Value * Size, llvm::Value * Addr)
Definition at line 1408 of file CGDecl.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::getDataLayout(), and clang::CodeGen::CodeGenModule::getLLVMLifetimeEndFn().
Referenced by clang::CodeGen::CodeGenFunction::CallLifetimeEnd::Emit(), and EmitCall().
EmitLifetimeStart()
llvm::Value * CodeGenFunction::EmitLifetimeStart (llvm::TypeSize Size, llvm::Value * Addr)
Emit a lifetime.begin marker if some criteria are satisfied.
Returns
a pointer to the temporary size Value if a marker was emitted, null otherwise
Definition at line 1392 of file CGDecl.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::CodeGenModule::getLLVMLifetimeStartFn(), and clang::CodeGen::CodeGenTypeCache::Int64Ty.
Referenced by EmitAutoVarAlloca(), EmitCall(), and EmitMaterializeTemporaryExpr().
EmitLoadOfBitfieldLValue()
RValue CodeGenFunction::EmitLoadOfBitfieldLValue (LValue LV, SourceLocation Loc)
Definition at line 2224 of file CGExpr.cpp.
References Builder, CGM, ConvertType(), clang::CodeGen::CGBuilderTy::CreateLoad(), EmitScalarRangeCheck(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getBitFieldAddress(), clang::CodeGen::LValue::getBitFieldInfo(), clang::CodeGen::CodeGenModule::getTarget(), clang::CodeGen::LValue::getType(), isAAPCS(), clang::CodeGen::CGBitFieldInfo::IsSigned, clang::CodeGen::LValue::isVolatileQualified(), clang::CodeGen::CGBitFieldInfo::Offset, Offset, clang::CodeGen::CGBitFieldInfo::Size, clang::CodeGen::CGBitFieldInfo::StorageSize, clang::CodeGen::CGBitFieldInfo::VolatileOffset, and clang::CodeGen::CGBitFieldInfo::VolatileStorageSize.
EmitLoadOfComplex()
ComplexPairTy CodeGenFunction::EmitLoadOfComplex (LValue src, SourceLocation loc)
EmitLoadOfComplex - Load a complex number from the specified l-value.
EmitLoadOfComplex - Load a complex number from the specified address.
Definition at line 1497 of file CGExprComplex.cpp.
Referenced by convertTempToRValue(), EmitComplexPrePostIncDec(), EmitFunctionEpilog(), emitGlobalToListCopyFunction(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), emitListToGlobalCopyFunction(), EmitRValueForField(), generateObjCGetterBody(), and InitCatchParam().
EmitLoadOfExtVectorElementLValue()
RValue CodeGenFunction::EmitLoadOfExtVectorElementLValue (LValue V)
Definition at line 2261 of file CGExpr.cpp.
References Builder, CGM, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::RValue::get(), getAccessedFieldNo(), clang::Type::getAs(), clang::CodeGen::LValue::getExtVectorAddress(), clang::CodeGen::LValue::getExtVectorElts(), getLangOpts(), clang::VectorType::getNumElements(), clang::CodeGen::LValue::getType(), clang::HLSL, clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::LValue::isVolatileQualified(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by EmitLoadOfLValue().
EmitLoadOfGlobalRegLValue()
RValue CodeGenFunction::EmitLoadOfGlobalRegLValue (LValue LV)
Load of global gamed gegisters are always calls to intrinsics.
Definition at line 2314 of file CGExpr.cpp.
References CGM, clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CodeGenTypes::getDataLayout(), clang::CodeGen::LValue::getGlobalReg(), clang::CodeGen::LValue::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::Type::isIntegerType(), and clang::Type::isPointerType().
Referenced by EmitLoadOfLValue().
EmitLoadOfLValue()
RValue CodeGenFunction::EmitLoadOfLValue (LValue V, SourceLocation Loc)
EmitLoadOfLValue - Given an expression that represents a value lvalue, this method emits the address of the lvalue, then loads the result as an rvalue, returning the rvalue.
Definition at line 2162 of file CGExpr.cpp.
References Builder, clang::Type::castAs(), CGM, clang::CodeGen::CGBuilderTy::CreateLoad(), EmitARCLoadWeak(), EmitARCLoadWeakRetained(), EmitLoadOfExtVectorElementLValue(), EmitLoadOfGlobalRegLValue(), EmitLoadOfMatrixLValue(), EmitLoadOfScalar(), EmitObjCConsumeObject(), clang::CodeGen::CGObjCRuntime::EmitObjCWeakRead(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getLangOpts(), clang::CodeGen::LValue::getMatrixIdx(), clang::Qualifiers::getObjCLifetime(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::LValue::getQuals(), clang::CodeGen::LValue::getType(), clang::CodeGen::LValue::getVectorAddress(), clang::CodeGen::LValue::getVectorIdx(), clang::Type::isConstantMatrixType(), clang::CodeGen::LValue::isExtVectorElt(), clang::Type::isFunctionType(), clang::CodeGen::LValue::isGlobalReg(), clang::CodeGen::LValue::isMatrixElt(), clang::CodeGen::LValue::isObjCWeak(), clang::CodeGen::LValue::isSimple(), clang::CodeGen::LValue::isVectorElt(), clang::CodeGen::LValue::isVolatileQualified(), clang::interp::Load(), and clang::Qualifiers::OCL_Weak.
Referenced by EmitAtomicUpdateValue(), EmitOMPAtomicSimpleUpdateExpr(), EmitRValueForField(), emitScalarConstant(), emitSimpleAtomicLoad(), emitWritebackArg(), generateObjCGetterBody(), StartFunction(), and tryEmitARCRetainLoadOfScalar().
EmitLoadOfPointer()
Address CodeGenFunction::EmitLoadOfPointer (Address Ptr, const PointerType * PtrTy, LValueBaseInfo * BaseInfo = nullptr, TBAAAccessInfo * TBAAInfo = nullptr)
Load a pointer with type PtrTy stored at address Ptr.
Note that PtrTy is the type of the loaded pointer, not the addresses it is loaded from.
Definition at line 2791 of file CGExpr.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::PointerType::getPointeeType(), and makeNaturalAddressForPointer().
Referenced by emitDeclTargetVarDeclLValue(), EmitLoadOfPointerLValue(), EmitOMPUseDeviceAddrClause(), and emitOutlinedFunctionPrologue().
EmitLoadOfPointerLValue()
LValue CodeGenFunction::EmitLoadOfPointerLValue (Address Ptr, const PointerType * PtrTy)
Definition at line 2801 of file CGExpr.cpp.
References EmitLoadOfPointer(), clang::PointerType::getPointeeType(), and MakeAddrLValue().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), and loadToBegin().
EmitLoadOfReference()
Address CodeGenFunction::EmitLoadOfReference (LValue RefLVal, LValueBaseInfo * PointeeBaseInfo = nullptr, TBAAAccessInfo * PointeeTBAAInfo = nullptr)
Definition at line 2771 of file CGExpr.cpp.
References Builder, CGM, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenModule::DecorateInstructionWithTBAA(), clang::CodeGen::LValue::getAddress(), clang::Type::getPointeeType(), clang::CodeGen::LValue::getTBAAInfo(), clang::CodeGen::LValue::getType(), clang::CodeGen::LValue::isVolatile(), clang::interp::Load(), and makeNaturalAddressForPointer().
Referenced by EmitLoadOfReferenceLValue(), EmitLValueForField(), emitOutlinedFunctionPrologue(), and GetAddrOfBlockDecl().
EmitLoadOfReferenceLValue() [1/2]
LValue clang::CodeGen::CodeGenFunction::EmitLoadOfReferenceLValue (Address RefAddr, QualType RefTy, AlignmentSource Source = AlignmentSource::Type) inline
Definition at line 2707 of file CodeGenFunction.h.
References CGM, EmitLoadOfReferenceLValue(), clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), and MakeAddrLValue().
EmitLoadOfReferenceLValue() [2/2]
LValue CodeGenFunction::EmitLoadOfReferenceLValue (LValue RefLVal)
Definition at line 2782 of file CGExpr.cpp.
References EmitLoadOfReference(), clang::Type::getPointeeType(), clang::CodeGen::LValue::getType(), and MakeAddrLValue().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), EmitDeclRefLValue(), EmitGlobalVarDeclLValue(), EmitLoadOfReferenceLValue(), EmitLValueForLambdaField(), and loadToBegin().
EmitLoadOfScalar() [1/3]
llvm::Value* clang::CodeGen::CodeGenFunction::EmitLoadOfScalar (Address Addr, bool Volatile, QualType Ty, SourceLocation Loc, AlignmentSource Source = AlignmentSource::Type, bool isNontemporal = false) inline
EmitLoadOfScalar - Load a scalar value from an address, taking care to appropriately convert from the memory representation to the LLVM value representation.
Definition at line 4107 of file CodeGenFunction.h.
References CGM, and clang::CodeGen::CodeGenModule::getTBAAAccessInfo().
Referenced by castValueToType(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), convertTempToRValue(), EmitARCStoreStrong(), EmitCfiCheckFail(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElements(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), EmitFunctionProlog(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalFinalUpdate(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), EmitLoadOfLValue(), EmitLoadOfMatrixLValue(), EmitLoadOfScalar(), EmitNontemporalLoad(), emitOutlinedFunctionPrologue(), EmitRValueForField(), EmitScalarInit(), emitShuffleAndReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), emitWriteback(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), clang::CodeGen::CGOpenMPRuntime::getThreadID(), InitCatchParam(), LoadObjCSelf(), LoadPassedObjectSize(), and shuffleAndStore().
EmitLoadOfScalar() [2/3]
llvm::Value * CodeGenFunction::EmitLoadOfScalar (Address Addr, bool Volatile, QualType Ty, SourceLocation Loc, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo, bool isNontemporal = false)
Definition at line 1931 of file CGExpr.cpp.
References Builder, clang::interp::Cast(), CGM, ConvertType(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenModule::DecorateInstructionWithTBAA(), EmitAtomicLoad(), emitBoolVecConversion(), EmitFromMemory(), EmitScalarRangeCheck(), clang::Type::getAs(), clang::CodeGen::Address::getBasePointer(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::Address::getElementType(), getLLVMContext(), clang::CodeGen::RValue::getScalarVal(), clang::Type::isAtomicType(), clang::interp::Load(), LValueIsSuitableForInlineAtomic(), clang::CodeGen::LValue::MakeAddr(), Node, clang::CodeGen::NotKnownNonNull, V, clang::CodeGen::Address::withElementType(), and clang::CodeGen::Address::withPointer().
EmitLoadOfScalar() [3/3]
llvm::Value * CodeGenFunction::EmitLoadOfScalar (LValue lvalue, SourceLocation Loc)
EmitLoadOfScalar - Load a scalar value from an address, taking care to appropriately convert from the memory representation to the LLVM value representation.
The l-value must be a simple l-value.
Definition at line 1835 of file CGExpr.cpp.
References EmitLoadOfScalar(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getBaseInfo(), clang::CodeGen::LValue::getTBAAInfo(), clang::CodeGen::LValue::getType(), clang::CodeGen::LValue::isNontemporal(), and clang::CodeGen::LValue::isVolatile().
EmitLValue()
LValue CodeGenFunction::EmitLValue (const Expr * E, KnownNonNull_t IsKnownNonNull = NotKnownNonNull)
EmitLValue - Emit code to compute a designator that specifies the location of the expression.
This can return one of two things: a simple address or a bitfield reference. In either case, the LLVM Value* in the LValue structure is guaranteed to be an LLVM pointer type.
If this returns a bitfield reference, nothing about the pointee type of the LLVM value is known: For example, it may not be a pointer to an integer.
If this returns a normal address, and if the lvalue's C type is fixed size, this method guarantees that the returned pointer type will point to an LLVM type of the same size of the lvalue's type. If the lvalue has a variable length type, this is not possible.
Definition at line 1497 of file CGExpr.cpp.
References clang::CodeGen::LValue::isKnownNonNull(), and clang::CodeGen::LValue::setKnownNonNull().
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::bind(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), EmitARCStoreAutoreleasing(), EmitARCStoreStrong(), EmitARCStoreUnsafeUnretained(), EmitArraySubscriptExpr(), EmitArrayToPointerDecay(), EmitBinaryOperatorLValue(), EmitCallArg(), EmitCallee(), EmitCastLValue(), EmitCheckedLValue(), emitCPPObjectAtomicSetterCall(), EmitCXXConstructorCall(), EmitCXXMemberPointerCallExpr(), EmitCXXPseudoDestructorExpr(), EmitDeclRefLValue(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElements(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), EmitExtVectorElementExpr(), EmitIgnoredExpr(), EmitInitListLValue(), EmitLValueOrThrowExpression(), EmitMatrixSubscriptExpr(), EmitMSVAListRef(), EmitObjCIsaExpr(), EmitObjCIvarRefLValue(), EmitObjCMessageExpr(), EmitOMPArraySectionExpr(), emitOMPAtomicCaptureExpr(), emitOMPAtomicCompareExpr(), emitOMPAtomicReadExpr(), emitOMPAtomicUpdateExpr(), emitOMPAtomicWriteExpr(), EmitOMPHelperVar(), EmitPointerToDataMemberBinaryExpr(), EmitPointerWithAlignment(), emitPrivatesInit(), emitPseudoObjectExpr(), EmitReferenceBindingToExpr(), EmitSimpleOMPExecutableDirective(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), emitStructSetterCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), EmitTypeidFromVTable(), EmitUnaryOpLValue(), EmitVAListRef(), emitWritebackArg(), getOrCreateOpaqueLValueMapping(), getPointerAndSize(), tryEmitARCCopyWeakInit(), and tryEmitARCRetainLoadOfScalar().
EmitLValueForField()
LValue CodeGenFunction::EmitLValueForField (LValue Base, const FieldDecl * Field)
Definition at line 4812 of file CGExpr.cpp.
References clang::CodeGen::TBAAAccessInfo::AccessType, clang::Qualifiers::addCVRQualifiers(), clang::Qualifiers::addVolatile(), clang::CodeGen::TBAAAccessInfo::BaseType, Builder, CGM, clang::CodeGen::CodeGenTypes::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreateLaunderInvariantGroup(), clang::CodeGen::CGBuilderTy::CreatePreserveStructAccessIndex(), clang::CodeGen::CGBuilderTy::CreatePreserveUnionAccessIndex(), clang::CodeGen::CGBuilderTy::CreateStripInvariantGroup(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), emitAddrOfFieldStorage(), EmitFieldAnnotations(), EmitFieldSYCLAnnotations(), EmitIntelFPGAFieldAnnotations(), EmitLoadOfReference(), emitPreserveStructAccess(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::CodeGenModule::generateIntelFPGAAnnotation(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::LValueBaseInfo::getAlignmentSource(), clang::ASTContext::getASTRecordLayout(), clang::CodeGen::LValue::getBaseInfo(), clang::CodeGen::CGRecordLayout::getBitFieldInfo(), clang::CodeGen::CodeGenTypes::getCGRecordLayout(), clang::ASTContext::getCharWidth(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), getDebugInfo(), getDebugInfoFIndex(), clang::CodeGen::Address::getElementType(), clang::CodeGen::getFieldAlignmentSource(), clang::FieldDecl::getFieldIndex(), clang::ASTRecordLayout::getFieldOffset(), getLangOpts(), getLLVMContext(), clang::CodeGen::CGRecordLayout::getLLVMFieldNo(), clang::Decl::getLocation(), clang::CodeGen::TBAAAccessInfo::getMayAliasInfo(), clang::NamedDecl::getName(), clang::Qualifiers::getObjCGCAttr(), clang::CodeGen::CGDebugInfo::getOrCreateRecordType(), clang::CodeGen::CGDebugInfo::getOrCreateStandaloneType(), clang::FieldDecl::getParent(), clang::Type::getPointeeType(), clang::CodeGen::LValue::getQuals(), clang::CharUnits::getQuantity(), clang::CodeGen::CodeGenModule::getTarget(), clang::CodeGen::CodeGenModule::getTBAABaseTypeInfo(), clang::CodeGen::LValue::getTBAAInfo(), clang::CodeGen::CodeGenModule::getTBAATypeInfo(), clang::ValueDecl::getType(), clang::CodeGen::LValue::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::ASTContext::getTypeSizeInChars(), clang::CodeGen::LValue::getVRQualifiers(), hasAnyVptr(), clang::Decl::hasAttr(), hasBPFPreserveStaticOffset(), isAAPCS(), clang::FieldDecl::isBitField(), IsInPreservedAIRegion, clang::CodeGen::TBAAAccessInfo::isMayAlias(), clang::Type::isReferenceType(), clang::TagDecl::isUnion(), clang::Type::isVectorType(), clang::QualType::isVolatileQualified(), MakeAddrLValue(), clang::CodeGen::LValue::MakeBitfield(), clang::CodeGen::TBAAAccessInfo::Offset, clang::Qualifiers::removeObjCGCAttr(), clang::CodeGen::TBAAAccessInfo::Size, clang::CodeGen::CGBitFieldInfo::StorageSize, clang::Qualifiers::Volatile, clang::CodeGen::CGBitFieldInfo::VolatileStorageOffset, clang::CodeGen::CGBitFieldInfo::VolatileStorageSize, clang::Qualifiers::Weak, clang::QualType::withCVRQualifiers(), clang::CodeGen::Address::withElementType(), and wrapWithBPFPreserveStaticOffset().
Referenced by clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), EmitLValueForFieldInitialization(), EmitLValueForLambdaField(), EmitMaterializeTemporaryExpr(), EmitMemberExpr(), emitPrivatesInit(), EmitRValueForField(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), and clang::CodeGen::CGOpenMPRuntime::getDepobjElements().
EmitLValueForFieldInitialization()
LValue CodeGenFunction::EmitLValueForFieldInitialization (LValue Base, const FieldDecl * Field)
EmitLValueForFieldInitialization - Like EmitLValueForField, except that if the Field is a reference, this will return the address of the reference and not the address of the value stored in the reference.
Definition at line 4993 of file CGExpr.cpp.
References CGM, ConvertTypeForMem(), emitAddrOfFieldStorage(), EmitLValueForField(), clang::CodeGen::LValueBaseInfo::getAlignmentSource(), clang::CodeGen::getFieldAlignmentSource(), clang::CodeGen::CodeGenModule::getTBAAInfoForSubobject(), clang::Type::isReferenceType(), MakeAddrLValue(), and V.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), EmitLValueForAnyFieldInitialization(), and EmitMemberInitializer().
EmitLValueForIvar()
LValue CodeGenFunction::EmitLValueForIvar (QualType ObjectTy, llvm::Value * Base, const ObjCIvarDecl * Ivar, unsigned CVRQualifiers)
Definition at line 5785 of file CGExpr.cpp.
References CGM, clang::CodeGen::CGObjCRuntime::EmitObjCValueForIvar(), and clang::CodeGen::CodeGenModule::getObjCRuntime().
Referenced by emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), EmitObjCIvarRefLValue(), emitStructSetterCall(), GenerateObjCCtorDtorMethod(), generateObjCGetterBody(), and generateObjCSetterBody().
EmitLValueForLambdaField() [1/2]
LValue CodeGenFunction::EmitLValueForLambdaField (const FieldDecl * Field)
Definition at line 4730 of file CGExpr.cpp.
Referenced by EmitCapturedFieldLValue(), and StartFunction().
EmitLValueForLambdaField() [2/2]
LValue CodeGenFunction::EmitLValueForLambdaField (const FieldDecl * Field, llvm::Value * ThisValue)
Given that we are currently emitting a lambda, emit an l-value for one of its members.
Definition at line 4703 of file CGExpr.cpp.
References CurCodeDecl, clang::CodeGen::Decl, EmitLoadOfReferenceLValue(), EmitLValueForField(), getContext(), clang::QualType::getNonReferenceType(), clang::ASTContext::getTagDeclType(), clang::ValueDecl::getType(), clang::Type::isReferenceType(), MakeAddrLValue(), and MakeNaturalAlignAddrLValue().
EmitMaterializeTemporaryExpr()
LValue CodeGenFunction::EmitMaterializeTemporaryExpr (const MaterializeTemporaryExpr * E)
Definition at line 446 of file CGExpr.cpp.
References clang::CFGBlock::back(), Block, Builder, CGM, ConvertTypeForMem(), createReferenceTemporary(), clang::CodeGen::Decl, clang::SubobjectAdjustment::DerivedToBaseAdjustment, clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, EmitAggExpr(), EmitAnyExprToMem(), EmitCXXMemberDataPointerAddress(), EmitIgnoredExpr(), EmitLifetimeStart(), EmitLValueForField(), clang::CodeGen::CodeGenModule::EmitNullConstant(), EmitOpaqueValueLValue(), EmitScalarExpr(), EmitScalarInit(), clang::SubobjectAdjustment::FieldAdjustment, clang::CodeGen::AggValueSlot::forAddr(), clang::CodeGen::LValue::getAddress(), GetAddressOfBaseClass(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::RawAddress::getElementType(), getEvaluationKind(), clang::Expr::getExprLoc(), clang::MaterializeTemporaryExpr::getExtendingDecl(), clang::QualType::getObjCLifetime(), clang::CodeGen::RawAddress::getPointer(), clang::QualType::getQualifiers(), clang::CodeGen::CodeGenFunction::ConditionalEvaluation::getStartingBlock(), clang::MaterializeTemporaryExpr::getStorageDuration(), clang::MaterializeTemporaryExpr::getSubExpr(), clang::Expr::getType(), clang::SanitizerSet::has(), inSuspendBlock(), clang::CodeGen::Address::invalid(), clang::CodeGen::AggValueSlot::IsDestructed, clang::QualType::isDestructedType(), isInConditionalBranch(), clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::LValue::isSimple(), MakeAddrLValue(), clang::SubobjectAdjustment::MemberPointerAdjustment, clang::CodeGen::NormalEHLifetimeMarker, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, pushTemporaryCleanup(), SanOpts, clang::SD_Automatic, clang::SD_FullExpression, clang::Expr::skipRValueSubobjectAdjustments(), clang::CodeGen::TEK_Aggregate, and clang::CodeGen::TEK_Scalar.
EmitMatrixSubscriptExpr()
LValue CodeGenFunction::EmitMatrixSubscriptExpr (const MatrixSubscriptExpr * E)
Definition at line 4379 of file CGExpr.cpp.
References Builder, clang::Type::castAs(), EmitLValue(), EmitScalarExpr(), clang::MatrixSubscriptExpr::getBase(), clang::MatrixSubscriptExpr::getColumnIdx(), clang::ConstantMatrixType::getNumRows(), clang::MatrixSubscriptExpr::getRowIdx(), clang::Expr::getType(), clang::MatrixSubscriptExpr::isIncomplete(), clang::CodeGen::LValue::MakeMatrixElt(), and MaybeConvertMatrixAddress().
EmitMemberExpr()
LValue CodeGenFunction::EmitMemberExpr (const MemberExpr * E)
Definition at line 4652 of file CGExpr.cpp.
References CGM, EmitCheckedLValue(), EmitDeclRefLValue(), EmitFunctionDeclLValue(), EmitIgnoredExpr(), EmitLValueForField(), EmitPointerWithAlignment(), EmitTypeCheck(), clang::MemberExpr::getBase(), getContext(), clang::MemberExpr::getExprLoc(), getLangOpts(), clang::MemberExpr::getMemberDecl(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::MemberExpr::isArrow(), clang::CodeGen::LValue::isNontemporal(), clang::CodeGen::CGOpenMPRuntime::isNontemporalDecl(), IsWrappedCXXThis(), MakeAddrLValue(), clang::SanitizerSet::set(), clang::CodeGen::LValue::setNontemporal(), setObjCGCLValueClass(), TCK_MemberAccess, tryToConvertMemberExprToDeclRefExpr(), and clang::CharUnits::Zero().
Referenced by EmitCountedByFieldExpr().
EmitMSVAListRef()
Address CodeGenFunction::EmitMSVAListRef (const Expr * E)
Emit a "reference" to a __builtin_ms_va_list; this is always the value of the expression, because a __builtin_ms_va_list is a pointer to a char.
Definition at line 2741 of file CodeGenFunction.cpp.
References EmitLValue(), and clang::CodeGen::LValue::getAddress().
Referenced by EmitVAArg().
EmitMSVCBuiltinExpr()
Value * CodeGenFunction::EmitMSVCBuiltinExpr (MSVCIntrin BuiltinID, const CallExpr * E)
Definition at line 1964 of file CGBuiltin.cpp.
References Begin, EmitPointerWithAlignment(), clang::CallExpr::getArg(), clang::CodeGen::Address::getElementType(), clang::Expr::getType(), and clang::Value::getType().
EmitMultiVersionResolver()
void CodeGenFunction::EmitMultiVersionResolver (llvm::Function * Resolver, ArrayRef< MultiVersionResolverOption > Options)
Definition at line 3183 of file CodeGenFunction.cpp.
EmitMustTailThunk()
void CodeGenFunction::EmitMustTailThunk (GlobalDecl GD, llvm::Value * AdjustedThisPtr, llvm::FunctionCallee Callee)
Emit a musttail call for a thunk with a potentially adjusted this pointer.
Definition at line 396 of file CGVTables.cpp.
References clang::CodeGen::CGFunctionInfo::arg_begin(), Builder, CGM, clang::CodeGen::CodeGenModule::ConstructAttributeList(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateStore(), CurFn, CurFnInfo, EmitBlock(), FinishThunk(), GetAddrOfLocalVar(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), ID, clang::CodeGen::CGFunctionInfoArgInfo::info, clang::CodeGen::ABIArgInfo::isDirect(), clang::CodeGen::ABIArgInfo::isInAlloca(), clang::CodeGen::ABIArgInfo::isIndirect(), and clang::CodeGen::ABIArgInfo::isSRetAfterThis().
Referenced by EmitCallAndReturnForThunk().
EmitNeonCall()
Value * CodeGenFunction::EmitNeonCall (llvm::Function * F, SmallVectorImpl< llvm::Value * > & O, const char * name, unsigned shift = 0, bool rightshift = false)
Definition at line 6433 of file CGBuiltin.cpp.
Referenced by EmitCommonNeonSISDBuiltinExpr().
EmitNeonRShiftImm()
Value * CodeGenFunction::EmitNeonRShiftImm (llvm::Value * Vec, llvm::Value * Amt, llvm::Type * Ty, bool usgn, const char * name)
Definition at line 6461 of file CGBuiltin.cpp.
References clang::prec::Shift.
EmitNeonShiftVector()
Value * CodeGenFunction::EmitNeonShiftVector (llvm::Value * V, llvm::Type * Ty, bool negateForRightShift)
Definition at line 6454 of file CGBuiltin.cpp.
References V.
EmitNeonSplat() [1/2]
llvm::Value* clang::CodeGen::CodeGenFunction::EmitNeonSplat (llvm::Value * V, llvm::Constant * Idx)
EmitNeonSplat() [2/2]
llvm::Value* clang::CodeGen::CodeGenFunction::EmitNeonSplat (llvm::Value * V, llvm::Constant * Idx, const llvm::ElementCount & Count)
EmitNewArrayInitializer()
void CodeGenFunction::EmitNewArrayInitializer (const CXXNewExpr * E, QualType elementType, llvm::Type * ElementTy, Address NewPtr, llvm::Value * NumElements, llvm::Value * AllocSizeWithoutCookie)
Definition at line 995 of file CGExprCXX.cpp.
References clang::CharUnits::alignmentAtOffset(), clang::CharUnits::alignmentOfArrayElement(), Builder, CGM, ConvertTypeForMem(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreateMemSet(), clang::CodeGen::CGBuilderTy::CreateStore(), CreateTempAlloca(), DeactivateCleanupBlock(), clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, EHStack, EmitAggExpr(), EmitBlock(), EmitCXXAggrConstructorCall(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::AggValueSlot::forAddr(), clang::CodeGen::Address::getAlignment(), clang::CXXNewExpr::getAllocatedType(), clang::InitListExpr::getArrayFiller(), clang::CXXParenListInitExpr::getArrayFiller(), clang::Type::getAs(), clang::Type::getAsArrayTypeUnsafe(), clang::ASTContext::getConstantArrayElementCount(), getContext(), getDestroyer(), clang::CodeGen::Address::getElementType(), clang::InitListExpr::getInit(), clang::CXXParenListInitExpr::getInitExprs(), clang::CXXNewExpr::getInitializer(), clang::InitListExpr::getNumInits(), clang::CXXMethodDecl::getParent(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::QualType::getQualifiers(), clang::CodeGen::CGBuilderTy::getSize(), clang::Expr::getType(), clang::CodeGen::Address::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::ASTContext::getTypeSizeInChars(), clang::CXXNewExpr::hasInitializer(), clang::InitListExpr::inits(), clang::CodeGen::Address::invalid(), clang::CodeGen::AggValueSlot::IsDestructed, clang::QualType::isDestructedType(), clang::CXXRecordDecl::isEmpty(), clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::AggValueSlot::IsNotZeroed, clang::CodeGen::AggValueSlot::IsSanitizerChecked, clang::InitListExpr::isStringLiteralInit(), clang::FunctionDecl::isTrivial(), clang::CodeGen::Address::isValid(), clang::CodeGen::CodeGenTypes::isZeroInitializable(), needsEHCleanup(), pushIrregularPartialArrayCleanup(), pushRegularPartialArrayCleanup(), clang::CodeGen::EHScopeStack::stable_begin(), StoreAnyExprIntoOneUnit(), and clang::CodeGen::Address::withElementType().
Referenced by EmitNewInitializer().
EmitNonNullArgCheck() [1/2]
void CodeGenFunction::EmitNonNullArgCheck (Address Addr, QualType ArgType, SourceLocation ArgLoc, AbstractCallee AC, unsigned ParmNum)
Definition at line 4496 of file CGCall.cpp.
EmitNonNullArgCheck() [2/2]
void CodeGenFunction::EmitNonNullArgCheck (RValue RV, QualType ArgType, SourceLocation ArgLoc, AbstractCallee AC, unsigned ParmNum)
Create a check for a function parameter that may potentially be declared as non-null.
Definition at line 4445 of file CGCall.cpp.
EmitNonNullRValueCheck()
llvm::Value * CodeGenFunction::EmitNonNullRValueCheck (RValue RV, QualType T)
Create a check that a scalar RValue is non-null.
Definition at line 1391 of file CGExpr.cpp.
References Builder, CGM, clang::CodeGen::CGCXXABI::EmitMemberPointerIsNotNull(), clang::Type::getAs(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::RValue::getScalarVal(), clang::T, and V.
EmitNoreturnRuntimeCallOrInvoke()
void CodeGenFunction::EmitNoreturnRuntimeCallOrInvoke (llvm::FunctionCallee callee, ArrayRef< llvm::Value * > args)
Emits a call or invoke to the given noreturn runtime function.
Definition at line 4912 of file CGCall.cpp.
References Builder, getBundlesForFunclet(), getInvokeDest(), clang::CodeGen::CodeGenTypeCache::getRuntimeCC(), and getUnreachableBlock().
EmitNounwindRuntimeCall() [1/3]
llvm::CallInst* clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall (llvm::FunctionCallee callee, ArrayRef< Address > args, const Twine & name = "")
EmitNounwindRuntimeCall() [2/3]
llvm::CallInst* clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall (llvm::FunctionCallee callee, ArrayRef< llvm::Value * > args, const Twine & name = "")
EmitNounwindRuntimeCall() [3/3]
llvm::CallInst* clang::CodeGen::CodeGenFunction::EmitNounwindRuntimeCall (llvm::FunctionCallee callee, const Twine & name = "")
Referenced by BuildBlockRelease(), CallBeginCatch(), emitARCCopyOperation(), EmitARCDestroyWeak(), EmitARCIntrinsicUse(), emitARCLoadOperation(), EmitARCNoopIntrinsicUse(), EmitARCRelease(), emitARCStoreOperation(), EmitARCStoreStrongCall(), emitARCValueOperation(), EmitBuiltinAvailable(), clang::CodeGen::CGOpenMPRuntime::emitCall(), EmitCall(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::EmitCaptureStmt(), emitCheckHandlerCall(), EmitExtendGCLifetime(), emitGlobalDtorWithTLRegDtor(), emitIsPlatformVersionAtLeast(), EmitObjCAutoreleasePoolPush(), clang::CodeGen::CGCXXABI::emitTerminateForUnexpectedException(), clang::CodeGen::CodeGenFunction::FinallyInfo::exit(), GenerateCopyHelperFunction(), InitCatchParam(), registerGlobalDtorWithAtExit(), and unregisterGlobalDtorWithUnAtExit().
EmitNullabilityCheck()
void CodeGenFunction::EmitNullabilityCheck (LValue LHS, llvm::Value * RHS, SourceLocation Loc)
Given an assignment *LHS = RHS, emit a test that checks if RHS is nonnull, if LHS is marked _Nonnull.
Definition at line 803 of file CGDecl.cpp.
References Builder, EmitCheck(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), clang::Type::getNullability(), clang::CodeGen::LValue::getType(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenTypeCache::Int8Ty, IsNotNull, clang::NonNull, SanOpts, and TCK_NonnullAssign.
Referenced by EmitBinaryOperatorLValue(), and EmitScalarInit().
EmitNullInitialization()
void CodeGenFunction::EmitNullInitialization (Address DestPtr, QualType Ty)
EmitNullInitialization - Generate code to set a value of the given type to null, If the type contains data member pointers, they will be initialized to -1 in accordance with the Itanium C++ ABI.
Definition at line 2343 of file CodeGenFunction.cpp.
References Builder, CGM, clang::CPlusPlus, clang::CodeGen::CGBuilderTy::CreateMemCpy(), clang::CodeGen::CGBuilderTy::CreateMemSet(), emitNonZeroVLAInit(), clang::CodeGen::CodeGenModule::EmitNullConstant(), clang::CodeGen::Address::getAlignment(), clang::Type::getAs(), clang::CharUnits::getAsAlign(), clang::ASTContext::getBaseElementType(), getContext(), clang::CodeGen::Address::getElementType(), getLangOpts(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getSize(), clang::CodeGen::CodeGenModule::getTypes(), clang::ASTContext::getTypeSizeInChars(), getVLASize(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CharUnits::isOne(), clang::CharUnits::isZero(), clang::CodeGen::CodeGenTypes::isZeroInitializable(), and clang::CodeGen::Address::withElementType().
Referenced by EmitCXXAggrConstructorCall(), EmitCXXConstructExpr(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitSynthesizedCXXCopyCtor(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
EmitNVPTXBuiltinExpr()
Value * CodeGenFunction::EmitNVPTXBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 19972 of file CGBuiltin.cpp.
References clang::CallExpr::getArg(), clang::Type::getPointeeType(), and clang::Expr::getType().
Referenced by EmitTargetArchBuiltinExpr().
EmitNVPTXDevicePrintfCallExpr()
RValue CodeGenFunction::EmitNVPTXDevicePrintfCallExpr (const CallExpr * E)
Definition at line 183 of file CGGPUBuiltin.cpp.
References CGM, clang::CodeGen::CodeGenModule::getModule(), and getTarget().
EmitObjCAlloc()
llvm::Value * CodeGenFunction::EmitObjCAlloc (llvm::Value * value, llvm::Type * resultType)
Allocate the given objc object.
call i8* @objc_alloc(i8* value)
Definition at line 2744 of file CGObjC.cpp.
References CGM, emitObjCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_alloc.
Referenced by tryGenerateSpecializedMessageSend().
EmitObjCAllocInit()
llvm::Value * CodeGenFunction::EmitObjCAllocInit (llvm::Value * value, llvm::Type * resultType)
Definition at line 2760 of file CGObjC.cpp.
References CGM, emitObjCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_alloc_init.
Referenced by tryEmitSpecializedAllocInit().
EmitObjCAllocWithZone()
llvm::Value * CodeGenFunction::EmitObjCAllocWithZone (llvm::Value * value, llvm::Type * resultType)
Allocate the given objc object.
call i8* @objc_allocWithZone(i8* value)
Definition at line 2753 of file CGObjC.cpp.
References CGM, emitObjCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_allocWithZone.
Referenced by tryGenerateSpecializedMessageSend().
EmitObjCArrayLiteral()
llvm::Value * CodeGenFunction::EmitObjCArrayLiteral (const ObjCArrayLiteral * E)
Definition at line 247 of file CGObjC.cpp.
References EmitObjCCollectionLiteral(), and clang::ObjCArrayLiteral::getArrayWithObjectsMethod().
EmitObjCAtSynchronizedStmt()
void CodeGenFunction::EmitObjCAtSynchronizedStmt (const ObjCAtSynchronizedStmt & S)
Definition at line 2089 of file CGObjC.cpp.
EmitObjCAtThrowStmt()
void CodeGenFunction::EmitObjCAtThrowStmt (const ObjCAtThrowStmt & S)
Definition at line 2085 of file CGObjC.cpp.
EmitObjCAtTryStmt()
void CodeGenFunction::EmitObjCAtTryStmt (const ObjCAtTryStmt & S)
Definition at line 2081 of file CGObjC.cpp.
EmitObjCAutorelease()
llvm::Value * CodeGenFunction::EmitObjCAutorelease (llvm::Value * value, llvm::Type * returnType)
Autorelease the given object.
call i8* @objc_autorelease(i8* value)
Definition at line 2803 of file CGObjC.cpp.
References CGM, emitObjCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_autoreleaseRuntimeFunction.
Referenced by tryGenerateSpecializedMessageSend().
EmitObjCAutoreleasePoolCleanup()
void CodeGenFunction::EmitObjCAutoreleasePoolCleanup (llvm::Value * Ptr)
Definition at line 2871 of file CGObjC.cpp.
References CGM, EHStack, clang::CodeGen::CodeGenModule::getLangOpts(), and clang::CodeGen::NormalCleanup.
Referenced by GenerateCXXGlobalInitFunc().
EmitObjCAutoreleasePoolPop()
void CodeGenFunction::EmitObjCAutoreleasePoolPop (llvm::Value * value)
Produce the code to do a primitive release.
call void @objc_autoreleasePoolPop(i8* ptr)
Definition at line 2689 of file CGObjC.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), EmitRuntimeCall(), EmitRuntimeCallOrInvoke(), getARCIntrinsic(), getInvokeDest(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::ObjCEntrypoints::objc_autoreleasePoolPop, clang::CodeGen::ObjCEntrypoints::objc_autoreleasePoolPopInvoke, and setARCRuntimeFunctionLinkage().
EmitObjCAutoreleasePoolPush()
llvm::Value * CodeGenFunction::EmitObjCAutoreleasePoolPush ()
Produce the code to do a objc_autoreleasepool_push.
call i8* @objc_autoreleasePoolPush(void)
Definition at line 2679 of file CGObjC.cpp.
References CGM, EmitNounwindRuntimeCall(), getARCIntrinsic(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_autoreleasePoolPush.
Referenced by GenerateCXXGlobalInitFunc().
EmitObjCAutoreleasePoolStmt()
void CodeGenFunction::EmitObjCAutoreleasePoolStmt (const ObjCAutoreleasePoolStmt & S)
Definition at line 3643 of file CGObjC.cpp.
References clang::ObjCAutoreleasePoolStmt::getSubStmt().
EmitObjCBoxedExpr()
llvm::Value * CodeGenFunction::EmitObjCBoxedExpr (const ObjCBoxedExpr * E)
EmitObjCBoxedExpr - This routine generates code to call the appropriate expression boxing method.
This will either be one of +[NSNumber numberWith<Type>:], or +[NSString stringWithUTF8String:], or [NSValue valueWithBytes:objCType:].
Definition at line 64 of file CGObjC.cpp.
References clang::CodeGen::CallArgList::add(), Builder, clang::interp::Cast(), CGM, ConvertType(), CreateMemTemp(), EmitAnyExpr(), EmitAnyExprToMem(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::CGObjCRuntime::GenerateMessageSend(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenModule::GetAddrOfConstantCString(), clang::ObjCBoxedExpr::getBoxingMethod(), clang::QualType::getCanonicalType(), clang::CodeGen::CGObjCRuntime::GetClass(), clang::ObjCMethodDecl::getClassInterface(), getContext(), clang::ASTContext::getObjCEncodingForType(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::ConstantAddress::getPointer(), clang::ObjCMethodDecl::getReturnType(), clang::CodeGen::RValue::getScalarVal(), clang::ObjCMethodDecl::getSelector(), clang::ObjCBoxedExpr::getSubExpr(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), clang::ObjCMethodDecl::isClassMethod(), clang::ObjCBoxedExpr::isExpressibleAsConstantInitializer(), clang::Type::isObjCBoxableRecordType(), clang::ObjCMethodDecl::param_begin(), clang::ObjCMethodDecl::parameters(), and clang::CodeGen::ConstantEmitter::tryEmitAbstract().
EmitObjCCollectionLiteral()
llvm::Value * CodeGenFunction::EmitObjCCollectionLiteral (const Expr * E, const ObjCMethodDecl * MethodWithObjects)
Definition at line 123 of file CGObjC.cpp.
Referenced by EmitObjCArrayLiteral(), and EmitObjCDictionaryLiteral().
EmitObjCConsumeObject()
llvm::Value * CodeGenFunction::EmitObjCConsumeObject (QualType type, llvm::Value * object)
Produce the code for a CK_ARCConsumeObject.
Does a primitive release at the end of the full-expression.
Definition at line 2108 of file CGObjC.cpp.
References getARCCleanupKind().
Referenced by emitARCCopyAssignWeak(), EmitARCExtendBlockObject(), emitARCMoveAssignWeak(), EmitARCReclaimReturnedObject(), and EmitLoadOfLValue().
EmitObjCDictionaryLiteral()
llvm::Value * CodeGenFunction::EmitObjCDictionaryLiteral (const ObjCDictionaryLiteral * E)
Definition at line 251 of file CGObjC.cpp.
References EmitObjCCollectionLiteral(), and clang::ObjCDictionaryLiteral::getDictWithObjectsMethod().
EmitObjCEncodeExprLValue()
LValue CodeGenFunction::EmitObjCEncodeExprLValue (const ObjCEncodeExpr * E)
Definition at line 3258 of file CGExpr.cpp.
References CGM, clang::CodeGen::Decl, clang::CodeGen::CodeGenModule::GetAddrOfConstantStringFromObjCEncode(), clang::Expr::getType(), and MakeAddrLValue().
EmitObjCExtendObjectLifetime()
llvm::Value * CodeGenFunction::EmitObjCExtendObjectLifetime (QualType T, llvm::Value * Ptr)
Definition at line 2116 of file CGObjC.cpp.
References EmitARCRetainAutorelease(), and clang::ast_matchers::type.
EmitObjCForCollectionStmt()
void CodeGenFunction::EmitObjCForCollectionStmt (const ObjCForCollectionStmt & S)
Definition at line 1761 of file CGObjC.cpp.
EmitObjCIsaExpr()
LValue CodeGenFunction::EmitObjCIsaExpr (const ObjCIsaExpr * E)
Definition at line 5539 of file CGExprScalar.cpp.
References ConvertType(), ConvertTypeForMem(), EmitLValue(), EmitScalarExpr(), clang::CodeGen::LValue::getAddress(), clang::ObjCIsaExpr::getBase(), clang::Type::getPointeeType(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::Expr::getType(), clang::CodeGen::Address::invalid(), clang::Expr::isPRValue(), MakeAddrLValue(), and clang::CodeGen::Address::withElementType().
EmitObjCIvarRefLValue()
LValue CodeGenFunction::EmitObjCIvarRefLValue (const ObjCIvarRefExpr * E)
Definition at line 5793 of file CGExpr.cpp.
References EmitLValue(), EmitLValueForIvar(), EmitScalarExpr(), clang::ObjCIvarRefExpr::getBase(), getContext(), clang::Qualifiers::getCVRQualifiers(), clang::ObjCIvarRefExpr::getDecl(), clang::Type::getPointeeType(), clang::CodeGen::LValue::getPointer(), clang::QualType::getQualifiers(), clang::Expr::getType(), clang::ObjCIvarRefExpr::isArrow(), and setObjCGCLValueClass().
EmitObjCMessageExpr()
RValue CodeGenFunction::EmitObjCMessageExpr (const ObjCMessageExpr * E, ReturnValueSlot Return = ReturnValueSlot())
Definition at line 573 of file CGObjC.cpp.
References AdjustObjCObjectType(), clang::ObjCMessageExpr::arguments(), Builder, clang::Type::castAs(), CGM, clang::ObjCMessageExpr::Class, clang::CodeGen::CGBuilderTy::CreateStore(), CurCodeDecl, CurFuncDecl, EmitARCLoadWeakRetained(), EmitARCRetainAutorelease(), EmitARCRetainNonBlock(), EmitCallArgs(), EmitLValue(), EmitScalarExpr(), findWeakLValue(), clang::CodeGen::CGObjCRuntime::GenerateMessageSendSuper(), clang::CodeGen::CGObjCRuntime::GeneratePossiblySpecializedMessageSend(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), GetAddrOfLocalVar(), clang::CodeGen::CGObjCRuntime::GetClass(), clang::ObjCMethodDecl::getClassInterface(), clang::ObjCMessageExpr::getClassReceiver(), clang::Decl::getDeclContext(), clang::CodeGen::Address::getElementType(), clang::ObjCMessageExpr::getInstanceReceiver(), getLangOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::ObjCMessageExpr::getMethodDecl(), clang::ObjCMethodDecl::getMethodFamily(), getNullForVariable(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::ObjCMessageExpr::getReceiverKind(), clang::ObjCMethodDecl::getReturnType(), clang::CodeGen::RValue::getScalarVal(), clang::ObjCMessageExpr::getSelector(), clang::ObjCMessageExpr::getSuperType(), clang::Expr::getType(), clang::Decl::hasAttr(), clang::ObjCMessageExpr::Instance, clang::ObjCMessageExpr::isDelegateInitCall(), clang::Type::isObjCClassType(), LoadObjCSelf(), clang::OMF_retain, shouldExtendReceiverForInnerPointerMessage(), clang::ObjCMessageExpr::SuperClass, clang::ObjCMessageExpr::SuperInstance, tryEmitARCRetainScalarExpr(), and tryEmitSpecializedAllocInit().
Referenced by EmitObjCMessageExprLValue().
EmitObjCMessageExprLValue()
LValue CodeGenFunction::EmitObjCMessageExprLValue (const ObjCMessageExpr * E)
Definition at line 5751 of file CGExpr.cpp.
References clang::CodeGen::Decl, EmitObjCMessageExpr(), clang::CodeGen::RValue::getAggregateAddress(), clang::ObjCMessageExpr::getMethodDecl(), clang::ObjCMethodDecl::getReturnType(), clang::CodeGen::RValue::getScalarVal(), clang::Expr::getType(), clang::Type::isReferenceType(), clang::CodeGen::RValue::isScalar(), MakeAddrLValue(), and MakeNaturalAlignPointeeAddrLValue().
EmitObjCMRRAutoreleasePoolPop()
void CodeGenFunction::EmitObjCMRRAutoreleasePoolPop (llvm::Value * Arg)
Produce the code to do a primitive release.
[tmp drain];
Definition at line 2769 of file CGObjC.cpp.
References CGM, clang::CodeGen::CGObjCRuntime::GenerateMessageSend(), clang::IdentifierTable::get(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::SelectorTable::getSelector(), clang::ASTContext::Idents, clang::ASTContext::Selectors, and clang::CodeGen::CodeGenTypeCache::VoidTy.
EmitObjCMRRAutoreleasePoolPush()
llvm::Value * CodeGenFunction::EmitObjCMRRAutoreleasePoolPush ()
Produce the code to do an MRR version objc_autoreleasepool_push.
Which is: [[NSAutoreleasePool alloc] init]; Where alloc is declared as: + (id) alloc; in NSAutoreleasePool class. init is declared as: - (id) init; in its NSObject super class.
Definition at line 2719 of file CGObjC.cpp.
References CGM, clang::CodeGen::CGObjCRuntime::EmitNSAutoreleasePoolClassRef(), clang::CodeGen::CGObjCRuntime::GenerateMessageSend(), clang::IdentifierTable::get(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::RValue::getScalarVal(), clang::SelectorTable::getSelector(), clang::ASTContext::Idents, and clang::ASTContext::Selectors.
EmitObjCProtocolExpr()
llvm::Value * CodeGenFunction::EmitObjCProtocolExpr (const ObjCProtocolExpr * E)
Definition at line 265 of file CGObjC.cpp.
References CGM, clang::CodeGen::CGObjCRuntime::GenerateProtocolRef(), clang::CodeGen::CodeGenModule::getObjCRuntime(), and clang::ObjCProtocolExpr::getProtocol().
EmitObjCRelease()
void CodeGenFunction::EmitObjCRelease (llvm::Value * value, ARCPreciseLifetime_t precise)
Release the given object.
call void @objc_release(i8* value)
Definition at line 2822 of file CGObjC.cpp.
References clang::CodeGen::ARCImpreciseLifetime, Builder, CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), EmitCallOrInvoke(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::ObjCEntrypoints::objc_releaseRuntimeFunction, and setARCRuntimeFunctionLinkage().
Referenced by tryGenerateSpecializedMessageSend().
EmitObjCRetainNonBlock()
llvm::Value * CodeGenFunction::EmitObjCRetainNonBlock (llvm::Value * value, llvm::Type * returnType)
Retain the given object, with normal retain semantics.
call i8* @objc_retain(i8* value)
Definition at line 2813 of file CGObjC.cpp.
References CGM, emitObjCValueOperation(), clang::CodeGen::CodeGenModule::getObjCEntrypoints(), and clang::CodeGen::ObjCEntrypoints::objc_retainRuntimeFunction.
Referenced by tryGenerateSpecializedMessageSend().
EmitObjCSelectorExpr()
llvm::Value * CodeGenFunction::EmitObjCSelectorExpr (const ObjCSelectorExpr * E)
Emit a selector.
Definition at line 257 of file CGObjC.cpp.
References CGM, clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::ObjCSelectorExpr::getSelector(), and clang::CodeGen::CGObjCRuntime::GetSelector().
EmitObjCSelectorLValue()
LValue CodeGenFunction::EmitObjCSelectorLValue (const ObjCSelectorExpr * E)
Definition at line 5765 of file CGExpr.cpp.
References CGM, clang::CodeGen::Decl, clang::CodeGen::CGObjCRuntime::GetAddrOfSelector(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::ObjCSelectorExpr::getSelector(), clang::Expr::getType(), MakeAddrLValue(), and V.
EmitObjCStringLiteral()
llvm::Value * CodeGenFunction::EmitObjCStringLiteral (const ObjCStringLiteral * E)
Emits an instance of NSConstantString representing the object.
Definition at line 51 of file CGObjC.cpp.
References CGM, clang::CodeGen::CGObjCRuntime::GenerateConstantString(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::ConstantAddress::getPointer(), and clang::ObjCStringLiteral::getString().
EmitObjCThrowOperand()
llvm::Value * CodeGenFunction::EmitObjCThrowOperand (const Expr * expr)
Definition at line 3497 of file CGObjC.cpp.
References EmitARCRetainAutoreleaseScalarExpr(), EmitScalarExpr(), clang::ast_matchers::expr, and getLangOpts().
EmitOMPAggregateAssign()
void CodeGenFunction::EmitOMPAggregateAssign (Address DestAddr, Address SrcAddr, QualType OriginalType, const llvm::function_ref< void(Address, Address)> CopyGen)
Perform element by element copying of arrays with type OriginalType from SrcAddr to DestAddr using copying procedure generated by CopyGen.
Parameters
DestAddr Address of the destination array.
SrcAddr Address of the source array.
OriginalType Type of destination and source arrays.
CopyGen Copying procedure that copies value of single array element to another single array element.
Definition at line 701 of file CGStmtOpenMP.cpp.
References clang::CodeGen::Address::emitRawPointer(), clang::Type::getAsArrayTypeUnsafe(), clang::CodeGen::Address::getElementType(), and clang::CodeGen::Address::withElementType().
Referenced by emitPrivatesInit().
EmitOMPArraySectionExpr()
LValue CodeGenFunction::EmitOMPArraySectionExpr (const OMPArraySectionExpr * E, bool IsLowerBound = true)
Definition at line 4435 of file CGExpr.cpp.
References Array, Builder, CGM, EmitArraySubscriptExpr(), emitArraySubscriptGEP(), EmitLValue(), emitOMPArraySectionBase(), EmitScalarExpr(), clang::CodeGen::LValue::getAddress(), clang::OMPArraySectionExpr::getBase(), clang::CodeGen::LValue::getBaseInfo(), clang::OMPArraySectionExpr::getBaseOriginalType(), clang::OMPArraySectionExpr::getColonLocFirst(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::OMPArraySectionExpr::getExprLoc(), getLangOpts(), clang::OMPArraySectionExpr::getLength(), clang::OMPArraySectionExpr::getLowerBound(), clang::Type::getPointeeType(), clang::CodeGen::CodeGenModule::getTBAAInfoForSubobject(), clang::Expr::getType(), getVLASize(), clang::Expr::IgnoreParenImpCasts(), clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::CodeGen::Address::invalid(), clang::SourceLocation::isInvalid(), clang::Type::isPointerType(), isSimpleArrayDecayOperand(), MakeAddrLValue(), clang::CodeGen::CodeGenFunction::VlaSizePair::NumElts, and clang::CodeGen::CodeGenTypeCache::PointerWidthInBits.
Referenced by emitOMPArraySectionBase(), and getPointerAndSize().
EmitOMPAtomicDirective()
void CodeGenFunction::EmitOMPAtomicDirective (const OMPAtomicDirective & S)
Definition at line 6547 of file CGStmtOpenMP.cpp.
EmitOMPAtomicSimpleUpdateExpr()
std::pair< bool, RValue > CodeGenFunction::EmitOMPAtomicSimpleUpdateExpr (LValue X, RValue E, BinaryOperatorKind BO, bool IsXLHSInRHSPart, llvm::AtomicOrdering AO, SourceLocation Loc, const llvm::function_ref< RValue(RValue)> CommonGen)
Emit atomic update code for constructs: X = X BO E or X = E BO E.
Parameters
X Value to be updated.
E Update value.
BO Binary operation for update operation.
IsXLHSInRHSPart true if X is LHS in RHS part of the update expression, false otherwise.
AO Atomic ordering of the generated atomic instructions.
CommonGen Code generator for complex expressions that cannot be expressed through atomicrmw instruction.
Returns
<true, OldAtomicValue> if simple 'atomicrmw' instruction was generated, <false, RValue::get(nullptr)> otherwise.
Definition at line 6238 of file CGStmtOpenMP.cpp.
References EmitAtomicUpdate(), EmitLoadOfLValue(), emitOMPAtomicRMW(), EmitStoreThroughLValue(), and X.
Referenced by emitOMPAtomicCaptureExpr(), and emitOMPAtomicUpdateExpr().
EmitOMPBarrierDirective()
void CodeGenFunction::EmitOMPBarrierDirective (const OMPBarrierDirective & S)
Definition at line 5319 of file CGStmtOpenMP.cpp.
EmitOMPCancelDirective()
void CodeGenFunction::EmitOMPCancelDirective (const OMPCancelDirective & S)
Definition at line 7204 of file CGStmtOpenMP.cpp.
EmitOMPCancellationPointDirective()
void CodeGenFunction::EmitOMPCancellationPointDirective (const OMPCancellationPointDirective & S)
Definition at line 7198 of file CGStmtOpenMP.cpp.
EmitOMPCanonicalLoop()
void CodeGenFunction::EmitOMPCanonicalLoop (const OMPCanonicalLoop * S)
Emit an OMPCanonicalLoop using the OpenMPIRBuilder.
Definition at line 2015 of file CGStmtOpenMP.cpp.
EmitOMPCollapsedCanonicalLoopNest()
llvm::CanonicalLoopInfo * CodeGenFunction::EmitOMPCollapsedCanonicalLoopNest (const Stmt * S, int Depth)
Emit the Stmt S and return its topmost canonical loop, if any.
TODO: The Depth paramter is not yet implemented and must be 1. In the future it is meant to be the number of loops expected in the loop nests (usually specified by the "collapse" clause) that are collapsed to a single loop by this function.
Definition at line 1989 of file CGStmtOpenMP.cpp.
EmitOMPCopy()
void CodeGenFunction::EmitOMPCopy (QualType OriginalType, Address DestAddr, Address SrcAddr, const VarDecl * DestVD, const VarDecl * SrcVD, const Expr * Copy)
Emit proper copying of data from one variable to another.
Parameters
OriginalType Original type of the copied variables.
DestAddr Destination address.
SrcAddr Source address.
DestVD Destination variable used in CopyExpr (for arrays, has type of the base array element).
SrcVD Source variable used in CopyExpr (for arrays, has type of the base array element).
Copy Actual copygin expression for copying data from SrcVD to DestVD.
Definition at line 766 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), clang::Copy, clang::Type::isArrayType(), and clang::CodeGen::CodeGenFunction::OMPPrivateScope::Privatize().
EmitOMPCopyinClause()
bool CodeGenFunction::EmitOMPCopyinClause (const OMPExecutableDirective & D)
Emit code for copyin clause in D directive.
The next code is generated at the start of outlined functions for directives:
threadprivate_var1 = master_threadprivate_var1;
operator=(threadprivate_var2, master_threadprivate_var2);
...
__kmpc_barrier(&loc, global_tid);
Parameters
D OpenMP directive possibly with 'copyin' clause(s).
Returns
true if at least one copyin variable is found, false otherwise.
Definition at line 973 of file CGStmtOpenMP.cpp.
References clang::VarDecl::getCanonicalDecl(), clang::OMPExecutableDirective::getClausesOfKind(), clang::ValueDecl::getType(), clang::CodeGen::Address::invalid(), clang::VarDecl::isStaticLocal(), and clang::VK_LValue.
EmitOMPCriticalDirective()
void CodeGenFunction::EmitOMPCriticalDirective (const OMPCriticalDirective & S)
Definition at line 4359 of file CGStmtOpenMP.cpp.
EmitOMPDepobjDirective()
void CodeGenFunction::EmitOMPDepobjDirective (const OMPDepobjDirective & S)
Definition at line 5398 of file CGStmtOpenMP.cpp.
EmitOMPDistributeDirective()
void CodeGenFunction::EmitOMPDistributeDirective (const OMPDistributeDirective & S)
Definition at line 5853 of file CGStmtOpenMP.cpp.
EmitOMPDistributeLoop()
void CodeGenFunction::EmitOMPDistributeLoop (const OMPLoopDirective & S, const CodeGenLoopTy & CodeGenLoop, Expr * IncExpr)
Emit code for the distribute loop-based directive.
Definition at line 5624 of file CGStmtOpenMP.cpp.
EmitOMPDistributeParallelForDirective()
void CodeGenFunction::EmitOMPDistributeParallelForDirective (const OMPDistributeParallelForDirective & S)
Definition at line 3212 of file CGStmtOpenMP.cpp.
EmitOMPDistributeParallelForSimdDirective()
void CodeGenFunction::EmitOMPDistributeParallelForSimdDirective (const OMPDistributeParallelForSimdDirective & S)
Definition at line 3222 of file CGStmtOpenMP.cpp.
EmitOMPDistributeSimdDirective()
void CodeGenFunction::EmitOMPDistributeSimdDirective (const OMPDistributeSimdDirective & S)
Definition at line 3232 of file CGStmtOpenMP.cpp.
EmitOMPErrorDirective()
void CodeGenFunction::EmitOMPErrorDirective (const OMPErrorDirective & S)
Definition at line 5309 of file CGStmtOpenMP.cpp.
EmitOMPFirstprivateClause()
bool CodeGenFunction::EmitOMPFirstprivateClause (const OMPExecutableDirective & D, OMPPrivateScope & PrivateScope)
Definition at line 803 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), clang::CodeGen::Decl, clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenFunction::AutoVarEmission::getAllocatedAddress(), getCanonicalDecl(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::VarDecl::getInit(), clang::getOpenMPCaptureRegions(), clang::CodeGen::CodeGenFunction::ConstantEmission::getReferenceLValue(), clang::ValueDecl::getType(), clang::CodeGen::Address::getType(), clang::Decl::hasAttr(), clang::Type::isArrayType(), clang::isOpenMPTargetExecutionDirective(), clang::CodeGen::CodeGenFunction::ConstantEmission::isReference(), clang::Type::isReferenceType(), V, and clang::VK_LValue.
EmitOMPFlushDirective()
void CodeGenFunction::EmitOMPFlushDirective (const OMPFlushDirective & S)
Definition at line 5383 of file CGStmtOpenMP.cpp.
EmitOMPForDirective()
void CodeGenFunction::EmitOMPForDirective (const OMPForDirective & S)
Definition at line 3905 of file CGStmtOpenMP.cpp.
EmitOMPForSimdDirective()
void CodeGenFunction::EmitOMPForSimdDirective (const OMPForSimdDirective & S)
Definition at line 3960 of file CGStmtOpenMP.cpp.
EmitOMPGenericLoopDirective()
void CodeGenFunction::EmitOMPGenericLoopDirective (const OMPGenericLoopDirective & S)
Definition at line 7894 of file CGStmtOpenMP.cpp.
EmitOMPInnerLoop()
void CodeGenFunction::EmitOMPInnerLoop (const OMPExecutableDirective & S, bool RequiresCleanup, const Expr * LoopCond, const Expr * IncExpr, const llvm::function_ref< void(CodeGenFunction &)> BodyGen, const llvm::function_ref< void(CodeGenFunction &)> PostIncGen)
Emit inner loop of the worksharing/simd construct.
Parameters
S Directive, for which the inner loop must be emitted.
RequiresCleanup true, if directive has some associated private variables.
LoopCond Bollean condition for loop continuation.
IncExpr Increment expression for loop control variable.
BodyGen Generator for the inner body of the inner loop.
PostIncGen Genrator for post-increment code (required for ordered loop directvies).
Definition at line 2090 of file CGStmtOpenMP.cpp.
EmitOMPInteropDirective()
void CodeGenFunction::EmitOMPInteropDirective (const OMPInteropDirective & S)
Definition at line 7025 of file CGStmtOpenMP.cpp.
EmitOMPLastprivateClauseFinal()
void CodeGenFunction::EmitOMPLastprivateClauseFinal (const OMPExecutableDirective & D, bool NoFinals, llvm::Value * IsLastIterCond = nullptr)
Emit final copying of lastprivate values to original variables at the end of the worksharing or simd directive.
Parameters
D Directive that has at least one 'lastprivate' directives.
IsLastIterCond Boolean condition that must be set to 'i1 true' if it is the last iteration of the loop code in associated directive, or to 'i1 false' otherwise. If this item is nullptr, no final check is required.
Definition at line 1108 of file CGStmtOpenMP.cpp.
References clang::OMPExecutableDirective::getBeginLoc(), and clang::OMPExecutableDirective::getClausesOfKind().
EmitOMPLastprivateClauseInit()
bool CodeGenFunction::EmitOMPLastprivateClauseInit (const OMPExecutableDirective & D, OMPPrivateScope & PrivateScope)
Emit initial code for lastprivate variables.
If some variable is not also firstprivate, then the default initialization is used. Otherwise initialization of this variable is performed by EmitOMPFirstprivateClause method.
Parameters
D Directive that may have 'lastprivate' directives.
PrivateScope Private scope for capturing lastprivate variables for proper codegen in internal captured statement.
Returns
true if there is at least one lastprivate variable, false otherwise.
Definition at line 1045 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), getCanonicalDecl(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::ValueDecl::getType(), clang::CodeGen::Address::invalid(), clang::isOpenMPSimdDirective(), clang::isOpenMPTaskLoopDirective(), and clang::VK_LValue.
EmitOMPLinearClause()
void CodeGenFunction::EmitOMPLinearClause (const OMPLoopDirective & D, CodeGenFunction::OMPPrivateScope & PrivateScope)
Emit initial code for linear clauses.
Definition at line 2342 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), clang::VarDecl::getCanonicalDecl(), getCanonicalDecl(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), and clang::isOpenMPSimdDirective().
EmitOMPLinearClauseFinal()
void CodeGenFunction::EmitOMPLinearClauseFinal (const OMPLoopDirective & D, const llvm::function_ref< llvm::Value *(CodeGenFunction &)> CondGen)
Emit final code for linear clauses.
Parameters
CondGen Optional conditional code for final part of codegen for linear clause.
Definition at line 2189 of file CGStmtOpenMP.cpp.
References clang::OMPExecutableDirective::getClausesOfKind().
EmitOMPLinearClauseInit()
bool CodeGenFunction::EmitOMPLinearClauseInit (const OMPLoopDirective & D)
Emit initial code for linear variables.
Creates private copies and initializes them with the values according to OpenMP standard.
Parameters
D Directive (possibly) with the 'linear' clause.
Returns
true if at least one linear variable is found that should be initialized with the value of the original variable, false otherwise.
Definition at line 2151 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::AutoVarEmission::getAllocatedAddress(), clang::OMPExecutableDirective::getClausesOfKind(), clang::Expr::getExprLoc(), clang::VarDecl::getInit(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::Expr::IgnoreImpCasts(), and clang::VK_LValue.
EmitOMPLoopBody()
void CodeGenFunction::EmitOMPLoopBody (const OMPLoopDirective & D, JumpDest LoopExit)
Helper for the OpenMP loop directives.
Definition at line 1891 of file CGStmtOpenMP.cpp.
References emitBody(), clang::OMPLoopDirective::finals_conditions(), clang::CodeGen::CodeGenFunction::JumpDest::getBlock(), clang::OMPLoopDirective::getBody(), clang::CapturedStmt::getCapturedStmt(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), clang::OMPLoopBasedDirective::getLoopsNumber(), clang::Stmt::IgnoreContainers(), clang::isOpenMPDistributeDirective(), clang::CodeGen::CodeGenFunction::OMPPrivateScope::Privatize(), clang::OMPLoopBasedDirective::tryToFindNextInnerLoop(), and clang::OMPLoopDirective::updates().
EmitOMPMaskedDirective()
void CodeGenFunction::EmitOMPMaskedDirective (const OMPMaskedDirective & S)
Definition at line 4324 of file CGStmtOpenMP.cpp.
EmitOMPMasterDirective()
void CodeGenFunction::EmitOMPMasterDirective (const OMPMasterDirective & S)
Definition at line 4284 of file CGStmtOpenMP.cpp.
EmitOMPMasterTaskLoopDirective()
void CodeGenFunction::EmitOMPMasterTaskLoopDirective (const OMPMasterTaskLoopDirective & S)
Definition at line 7812 of file CGStmtOpenMP.cpp.
EmitOMPMasterTaskLoopSimdDirective()
void CodeGenFunction::EmitOMPMasterTaskLoopSimdDirective (const OMPMasterTaskLoopSimdDirective & S)
Definition at line 7824 of file CGStmtOpenMP.cpp.
EmitOMPMetaDirective()
void CodeGenFunction::EmitOMPMetaDirective (const OMPMetaDirective & S)
Definition at line 1818 of file CGStmtOpenMP.cpp.
EmitOMPOrderedDirective()
void CodeGenFunction::EmitOMPOrderedDirective (const OMPOrderedDirective & S)
Definition at line 5897 of file CGStmtOpenMP.cpp.
EmitOMPParallelDirective()
void CodeGenFunction::EmitOMPParallelDirective (const OMPParallelDirective & S)
Definition at line 1736 of file CGStmtOpenMP.cpp.
EmitOMPParallelForDirective()
void CodeGenFunction::EmitOMPParallelForDirective (const OMPParallelForDirective & S)
Definition at line 4410 of file CGStmtOpenMP.cpp.
EmitOMPParallelForSimdDirective()
void CodeGenFunction::EmitOMPParallelForSimdDirective (const OMPParallelForSimdDirective & S)
Definition at line 4444 of file CGStmtOpenMP.cpp.
EmitOMPParallelGenericLoopDirective()
void CodeGenFunction::EmitOMPParallelGenericLoopDirective (const OMPLoopDirective & S)
Definition at line 7916 of file CGStmtOpenMP.cpp.
EmitOMPParallelMaskedDirective()
void CodeGenFunction::EmitOMPParallelMaskedDirective (const OMPParallelMaskedDirective & S)
Definition at line 4505 of file CGStmtOpenMP.cpp.
EmitOMPParallelMasterDirective()
void CodeGenFunction::EmitOMPParallelMasterDirective (const OMPParallelMasterDirective & S)
Definition at line 4478 of file CGStmtOpenMP.cpp.
EmitOMPParallelMasterTaskLoopDirective()
void CodeGenFunction::EmitOMPParallelMasterTaskLoopDirective (const OMPParallelMasterTaskLoopDirective & S)
Definition at line 7836 of file CGStmtOpenMP.cpp.
EmitOMPParallelMasterTaskLoopSimdDirective()
void CodeGenFunction::EmitOMPParallelMasterTaskLoopSimdDirective (const OMPParallelMasterTaskLoopSimdDirective & S)
Definition at line 7854 of file CGStmtOpenMP.cpp.
EmitOMPParallelSectionsDirective()
void CodeGenFunction::EmitOMPParallelSectionsDirective (const OMPParallelSectionsDirective & S)
Definition at line 4532 of file CGStmtOpenMP.cpp.
EmitOMPPrivateClause()
void CodeGenFunction::EmitOMPPrivateClause (const OMPExecutableDirective & D, CodeGenFunction::OMPPrivateScope & PrivateScope)
Definition at line 948 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), and clang::OMPExecutableDirective::getClausesOfKind().
EmitOMPPrivateLoopCounters()
void CodeGenFunction::EmitOMPPrivateLoopCounters (const OMPLoopDirective & S, CodeGenFunction::OMPPrivateScope & LoopScope)
Emit initial code for loop counters of loop-based directives.
Definition at line 2262 of file CGStmtOpenMP.cpp.
EmitOMPReductionClauseFinal()
void CodeGenFunction::EmitOMPReductionClauseFinal (const OMPExecutableDirective & D, const OpenMPDirectiveKind ReductionKind)
Emit final update of reduction values to original variables at the end of the directive.
Parameters
D Directive that has at least one 'reduction' directives.
ReductionKind The kind of reduction to perform.
Definition at line 1411 of file CGStmtOpenMP.cpp.
References clang::OMPExecutableDirective::getBeginLoc(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getEndLoc(), clang::OMPExecutableDirective::getSingleClause(), clang::isOpenMPParallelDirective(), and clang::isOpenMPWorksharingDirective().
EmitOMPReductionClauseInit()
void CodeGenFunction::EmitOMPReductionClauseInit (const OMPExecutableDirective & D, CodeGenFunction::OMPPrivateScope & PrivateScope, bool ForInscan = false)
Emit initial code for reduction variables.
Creates reduction copies and initializes them with the values according to OpenMP standard.
Parameters
D Directive (possibly) with the 'reduction' clause.
PrivateScope Private scope for capturing reduction variables for proper codegen in internal captured statement.
Definition at line 1199 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), Data, clang::CodeGen::ReductionCodeGen::emitAggregateType(), clang::CodeGen::ReductionCodeGen::emitInitialization(), clang::CodeGen::ReductionCodeGen::emitSharedOrigLValue(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenFunction::AutoVarEmission::getAllocatedAddress(), clang::CodeGen::ReductionCodeGen::getBaseDecl(), clang::OMPExecutableDirective::getBeginLoc(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::CodeGen::ReductionCodeGen::getSharedLValue(), clang::Expr::getType(), clang::isOpenMPWorksharingDirective(), clang::Type::isScalarType(), clang::Type::isVariablyModifiedType(), and clang::CodeGen::Address::withElementType().
EmitOMPScanDirective()
void CodeGenFunction::EmitOMPScanDirective (const OMPScanDirective & S)
Definition at line 5421 of file CGStmtOpenMP.cpp.
Referenced by EmitSimpleOMPExecutableDirective().
EmitOMPSectionDirective()
void CodeGenFunction::EmitOMPSectionDirective (const OMPSectionDirective & S)
Definition at line 4204 of file CGStmtOpenMP.cpp.
EmitOMPSectionsDirective()
void CodeGenFunction::EmitOMPSectionsDirective (const OMPSectionsDirective & S)
Definition at line 4135 of file CGStmtOpenMP.cpp.
EmitOMPSharedLValue()
LValue CodeGenFunction::EmitOMPSharedLValue (const Expr * E)
Emits the lvalue for the expression with possibly captured variable.
Definition at line 294 of file CGStmtOpenMP.cpp.
References clang::ValueDecl::getType(), and clang::VK_LValue.
EmitOMPSimdDirective()
void CodeGenFunction::EmitOMPSimdDirective (const OMPSimdDirective & S)
Definition at line 2675 of file CGStmtOpenMP.cpp.
EmitOMPSimdFinal()
void CodeGenFunction::EmitOMPSimdFinal (const OMPLoopDirective & D, const llvm::function_ref< llvm::Value *(CodeGenFunction &)> CondGen)
Definition at line 2420 of file CGStmtOpenMP.cpp.
References clang::OMPLoopDirective::counters(), clang::OMPLoopDirective::finals(), and clang::OMPLoopDirective::private_counters().
EmitOMPSimdInit()
void CodeGenFunction::EmitOMPSimdInit (const OMPLoopDirective & D)
Helpers for the OpenMP loop directives.
Definition at line 2401 of file CGStmtOpenMP.cpp.
References emitSimdlenSafelenClause(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getSingleClause(), and clang::isOpenMPSimdDirective().
emitOMPSimpleStore()
void CodeGenFunction::emitOMPSimpleStore (LValue LVal, RValue RVal, QualType RValTy, SourceLocation Loc)
Definition at line 6043 of file CGStmtOpenMP.cpp.
References convertToComplexValue(), convertToScalarValue(), EmitStoreOfComplex(), EmitStoreThroughLValue(), clang::CodeGen::RValue::get(), getEvaluationKind(), clang::CodeGen::LValue::getType(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
Referenced by emitOMPAtomicCaptureExpr(), and emitOMPAtomicReadExpr().
EmitOMPSingleDirective()
void CodeGenFunction::EmitOMPSingleDirective (const OMPSingleDirective & S)
Definition at line 4231 of file CGStmtOpenMP.cpp.
EmitOMPTargetDataDirective()
void CodeGenFunction::EmitOMPTargetDataDirective (const OMPTargetDataDirective & S)
Definition at line 7348 of file CGStmtOpenMP.cpp.
EmitOMPTargetDeviceFunction()
void CodeGenFunction::EmitOMPTargetDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetDirective & S) static
Emit device code for the target directive.
Definition at line 6732 of file CGStmtOpenMP.cpp.
EmitOMPTargetDirective()
void CodeGenFunction::EmitOMPTargetDirective (const OMPTargetDirective & S)
Definition at line 6746 of file CGStmtOpenMP.cpp.
EmitOMPTargetEnterDataDirective()
void CodeGenFunction::EmitOMPTargetEnterDataDirective (const OMPTargetEnterDataDirective & S)
Definition at line 7460 of file CGStmtOpenMP.cpp.
EmitOMPTargetExitDataDirective()
void CodeGenFunction::EmitOMPTargetExitDataDirective (const OMPTargetExitDataDirective & S)
Definition at line 7481 of file CGStmtOpenMP.cpp.
EmitOMPTargetParallelDeviceFunction()
void CodeGenFunction::EmitOMPTargetParallelDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetParallelDirective & S) static
Definition at line 7527 of file CGStmtOpenMP.cpp.
EmitOMPTargetParallelDirective()
void CodeGenFunction::EmitOMPTargetParallelDirective (const OMPTargetParallelDirective & S)
Definition at line 7541 of file CGStmtOpenMP.cpp.
EmitOMPTargetParallelForDeviceFunction()
void CodeGenFunction::EmitOMPTargetParallelForDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetParallelForDirective & S) static
Emit device code for the target parallel for directive.
Definition at line 7566 of file CGStmtOpenMP.cpp.
EmitOMPTargetParallelForDirective()
void CodeGenFunction::EmitOMPTargetParallelForDirective (const OMPTargetParallelForDirective & S)
Definition at line 7581 of file CGStmtOpenMP.cpp.
EmitOMPTargetParallelForSimdDeviceFunction()
void CodeGenFunction::EmitOMPTargetParallelForSimdDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetParallelForSimdDirective & S) static
Emit device code for the target parallel for simd directive.
Definition at line 7605 of file CGStmtOpenMP.cpp.
EmitOMPTargetParallelForSimdDirective()
void CodeGenFunction::EmitOMPTargetParallelForSimdDirective (const OMPTargetParallelForSimdDirective & S)
Definition at line 7620 of file CGStmtOpenMP.cpp.
EmitOMPTargetParallelGenericLoopDeviceFunction()
void CodeGenFunction::EmitOMPTargetParallelGenericLoopDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetParallelGenericLoopDirective & S) static
Emit device code for the target parallel loop directive.
Definition at line 8083 of file CGStmtOpenMP.cpp.
EmitOMPTargetParallelGenericLoopDirective()
void CodeGenFunction::EmitOMPTargetParallelGenericLoopDirective (const OMPTargetParallelGenericLoopDirective & S)
Emit combined directive 'target parallel loop' as if its constituent constructs are 'target', 'parallel', and 'for'.
Definition at line 8100 of file CGStmtOpenMP.cpp.
EmitOMPTargetSimdDeviceFunction()
void CodeGenFunction::EmitOMPTargetSimdDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetSimdDirective & S) static
Emit device code for the target simd directive.
Definition at line 3241 of file CGStmtOpenMP.cpp.
EmitOMPTargetSimdDirective()
void CodeGenFunction::EmitOMPTargetSimdDirective (const OMPTargetSimdDirective & S)
Definition at line 3255 of file CGStmtOpenMP.cpp.
EmitOMPTargetTaskBasedDirective()
void CodeGenFunction::EmitOMPTargetTaskBasedDirective (const OMPExecutableDirective & S, const RegionCodeGenTy & BodyGen, OMPTargetDataInfo & InputInfo)
Definition at line 5038 of file CGStmtOpenMP.cpp.
Referenced by emitTargetCallElse(), emitTargetCallKernelLaunch(), and clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall().
EmitOMPTargetTeamsDeviceFunction()
void CodeGenFunction::EmitOMPTargetTeamsDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetTeamsDirective & S) static
Emit device code for the target teams directive.
Definition at line 6819 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDirective()
void CodeGenFunction::EmitOMPTargetTeamsDirective (const OMPTargetTeamsDirective & S)
Definition at line 6833 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDistributeDeviceFunction()
void CodeGenFunction::EmitOMPTargetTeamsDistributeDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetTeamsDistributeDirective & S) static
Emit device code for the target teams distribute directive.
Definition at line 6865 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDistributeDirective()
void CodeGenFunction::EmitOMPTargetTeamsDistributeDirective (const OMPTargetTeamsDistributeDirective & S)
Definition at line 6879 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDistributeParallelForDeviceFunction()
void CodeGenFunction::EmitOMPTargetTeamsDistributeParallelForDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetTeamsDistributeParallelForDirective & S) static
Definition at line 7122 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDistributeParallelForDirective()
void CodeGenFunction::EmitOMPTargetTeamsDistributeParallelForDirective (const OMPTargetTeamsDistributeParallelForDirective & S)
Definition at line 7138 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDistributeParallelForSimdDeviceFunction()
void CodeGenFunction::EmitOMPTargetTeamsDistributeParallelForSimdDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetTeamsDistributeParallelForSimdDirective & S) static
Emit device code for the target teams distribute parallel for simd directive.
Definition at line 7174 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDistributeParallelForSimdDirective()
void CodeGenFunction::EmitOMPTargetTeamsDistributeParallelForSimdDirective (const OMPTargetTeamsDistributeParallelForSimdDirective & S)
Definition at line 7190 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDistributeSimdDeviceFunction()
void CodeGenFunction::EmitOMPTargetTeamsDistributeSimdDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetTeamsDistributeSimdDirective & S) static
Emit device code for the target teams distribute simd directive.
Definition at line 6911 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsDistributeSimdDirective()
void CodeGenFunction::EmitOMPTargetTeamsDistributeSimdDirective (const OMPTargetTeamsDistributeSimdDirective & S)
Definition at line 6925 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsGenericLoopDeviceFunction()
void CodeGenFunction::EmitOMPTargetTeamsGenericLoopDeviceFunction (CodeGenModule & CGM, StringRef ParentName, const OMPTargetTeamsGenericLoopDirective & S) static
Emit device code for the target teams loop directive.
Definition at line 8048 of file CGStmtOpenMP.cpp.
EmitOMPTargetTeamsGenericLoopDirective()
void CodeGenFunction::EmitOMPTargetTeamsGenericLoopDirective (const OMPTargetTeamsGenericLoopDirective & S)
Definition at line 8037 of file CGStmtOpenMP.cpp.
EmitOMPTargetUpdateDirective()
void CodeGenFunction::EmitOMPTargetUpdateDirective (const OMPTargetUpdateDirective & S)
Definition at line 7873 of file CGStmtOpenMP.cpp.
EmitOMPTaskBasedDirective()
void CodeGenFunction::EmitOMPTaskBasedDirective (const OMPExecutableDirective & S, const OpenMPDirectiveKind CapturedRegion, const RegionCodeGenTy & BodyGen, const TaskGenTy & TaskGen, OMPTaskDataTy & Data)
Definition at line 4621 of file CGStmtOpenMP.cpp.
EmitOMPTaskDirective()
void CodeGenFunction::EmitOMPTaskDirective (const OMPTaskDirective & S)
Definition at line 5272 of file CGStmtOpenMP.cpp.
EmitOMPTaskgroupDirective()
void CodeGenFunction::EmitOMPTaskgroupDirective (const OMPTaskgroupDirective & S)
Definition at line 5335 of file CGStmtOpenMP.cpp.
EmitOMPTaskLoopBasedDirective()
void CodeGenFunction::EmitOMPTaskLoopBasedDirective (const OMPLoopDirective & S)
Definition at line 7636 of file CGStmtOpenMP.cpp.
EmitOMPTaskLoopDirective()
void CodeGenFunction::EmitOMPTaskLoopDirective (const OMPTaskLoopDirective & S)
Definition at line 7798 of file CGStmtOpenMP.cpp.
EmitOMPTaskLoopSimdDirective()
void CodeGenFunction::EmitOMPTaskLoopSimdDirective (const OMPTaskLoopSimdDirective & S)
Definition at line 7804 of file CGStmtOpenMP.cpp.
EmitOMPTaskwaitDirective()
void CodeGenFunction::EmitOMPTaskwaitDirective (const OMPTaskwaitDirective & S)
Definition at line 5323 of file CGStmtOpenMP.cpp.
EmitOMPTaskyieldDirective()
void CodeGenFunction::EmitOMPTaskyieldDirective (const OMPTaskyieldDirective & S)
Definition at line 5304 of file CGStmtOpenMP.cpp.
EmitOMPTeamsDirective()
void CodeGenFunction::EmitOMPTeamsDirective (const OMPTeamsDirective & S)
Definition at line 6780 of file CGStmtOpenMP.cpp.
EmitOMPTeamsDistributeDirective()
void CodeGenFunction::EmitOMPTeamsDistributeDirective (const OMPTeamsDistributeDirective & S)
Definition at line 6933 of file CGStmtOpenMP.cpp.
EmitOMPTeamsDistributeParallelForDirective()
void CodeGenFunction::EmitOMPTeamsDistributeParallelForDirective (const OMPTeamsDistributeParallelForDirective & S)
Definition at line 6978 of file CGStmtOpenMP.cpp.
EmitOMPTeamsDistributeParallelForSimdDirective()
void CodeGenFunction::EmitOMPTeamsDistributeParallelForSimdDirective (const OMPTeamsDistributeParallelForSimdDirective & S)
Definition at line 7001 of file CGStmtOpenMP.cpp.
EmitOMPTeamsDistributeSimdDirective()
void CodeGenFunction::EmitOMPTeamsDistributeSimdDirective (const OMPTeamsDistributeSimdDirective & S)
Definition at line 6956 of file CGStmtOpenMP.cpp.
EmitOMPTeamsGenericLoopDirective()
void CodeGenFunction::EmitOMPTeamsGenericLoopDirective (const OMPTeamsGenericLoopDirective & S)
Definition at line 7935 of file CGStmtOpenMP.cpp.
EmitOMPTileDirective()
void CodeGenFunction::EmitOMPTileDirective (const OMPTileDirective & S)
Definition at line 2747 of file CGStmtOpenMP.cpp.
EmitOMPUnrollDirective()
void CodeGenFunction::EmitOMPUnrollDirective (const OMPUnrollDirective & S)
Definition at line 2753 of file CGStmtOpenMP.cpp.
EmitOMPUseDeviceAddrClause()
void CodeGenFunction::EmitOMPUseDeviceAddrClause (const OMPUseDeviceAddrClause & C, OMPPrivateScope & PrivateScope, const llvm::DenseMap< const ValueDecl *, llvm::Value * > CaptureDeviceAddrMap)
Definition at line 7299 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), clang::Type::castAs(), ConvertTypeForMem(), EmitLoadOfPointer(), getBaseDecl(), getContext(), clang::QualType::getNonReferenceType(), clang::ASTContext::getPointerType(), clang::ValueDecl::getType(), clang::Type::isArrayType(), clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::CodeGen::Address::withElementType().
EmitOMPUseDevicePtrClause()
void CodeGenFunction::EmitOMPUseDevicePtrClause (const OMPUseDevicePtrClause & C, OMPPrivateScope & PrivateScope, const llvm::DenseMap< const ValueDecl *, llvm::Value * > CaptureDeviceAddrMap)
Definition at line 7248 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), ConvertTypeForMem(), getContext(), and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
EmitOMPWorksharingLoop()
bool CodeGenFunction::EmitOMPWorksharingLoop (const OMPLoopDirective & S, Expr * EUB, const CodeGenLoopBoundsTy & CodeGenLoopBounds, const CodeGenDispatchBoundsTy & CGDispatchBounds)
Emit code for the worksharing loop-based directive.
Returns
true, if this construct has any lastprivate clause, false - otherwise.
Definition at line 3275 of file CGStmtOpenMP.cpp.
EmitOpaqueValueLValue()
LValue CodeGenFunction::EmitOpaqueValueLValue (const OpaqueValueExpr * e)
Definition at line 5398 of file CGExpr.cpp.
References getOrCreateOpaqueLValueMapping(), and clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::shouldBindAsLValue().
Referenced by EmitMaterializeTemporaryExpr().
EmitOpenACCComputeConstruct()
void clang::CodeGen::CodeGenFunction::EmitOpenACCComputeConstruct (const OpenACCComputeConstruct & S) inline
Definition at line 4002 of file CodeGenFunction.h.
EmitOpenMPDevicePrintfCallExpr()
RValue CodeGenFunction::EmitOpenMPDevicePrintfCallExpr (const CallExpr * E)
Definition at line 223 of file CGGPUBuiltin.cpp.
References CGM, and getTarget().
EmitParmDecl()
void CodeGenFunction::EmitParmDecl (const VarDecl & D, ParamValue Arg, unsigned ArgNo)
EmitParmDecl - Emit a ParmVarDecl or an ImplicitParamDecl.
Emit an alloca (or GlobalValue depending on target) for the specified parameter and set up LocalDeclMap.
Definition at line 2572 of file CGDecl.cpp.
References clang::CodeGen::ARCImpreciseLifetime, clang::CodeGen::ARCPreciseLifetime, clang::CodeGen::CGFunctionInfo::arguments(), BlockInfo, Builder, clang::Type::castAs(), CGM, ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateLoad(), CreateMemTemp(), CurFnInfo, CurFuncIsThunk, clang::Default, clang::QualType::DK_cxx_destructor, clang::QualType::DK_nontrivial_c_struct, EHStack, EmitARCInitWeak(), EmitARCRetainNonBlock(), EmitARCStoreStrongCall(), EmitAutoVarWithLifetime(), clang::CodeGen::CodeGenModule::EmitNullConstant(), clang::CodeGen::Address::emitRawPointer(), EmitStoreOfScalar(), EmitVarAnnotations(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::CodeGenFunction::ParamValue::getAnyValue(), getARCCleanupKind(), clang::CodeGen::CodeGenTypeCache::getASTAllocaAddressSpace(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), getDebugInfo(), clang::RecordType::getDecl(), clang::CodeGen::CodeGenFunction::ParamValue::getDirectValue(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenFunction::ParamValue::getIndirectAddress(), clang::CodeGen::ABIArgInfo::getIndirectByVal(), getLangOpts(), getLLVMContext(), clang::NamedDecl::getName(), clang::Type::getNullability(), clang::Qualifiers::getObjCLifetime(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::CodeGen::RawAddress::getPointer(), clang::ASTContext::getPointerType(), clang::QualType::getQualifiers(), clang::ASTContext::getTargetAddressSpace(), getTargetHooks(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::Qualifiers::hasConst(), clang::CodeGenOptions::hasReducedDebugInfo(), hasScalarEvaluationKind(), clang::CodeGen::Address::invalid(), clang::VarDecl::isARCPseudoStrong(), clang::CodeGen::ABIArgInfo::isIndirect(), clang::CodeGen::CodeGenFunction::ParamValue::isIndirect(), clang::CodeGen::Address::isKnownNonNull(), clang::RecordDecl::isParamDestroyedInCallee(), clang::Type::isRecordType(), clang::CodeGen::Address::isValid(), MakeAddrLValue(), clang::VarDecl::needsDestruction(), clang::NonNull, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, clang::opencl_private, pushDestroy(), setBlockContextParameter(), clang::CodeGen::EHScopeStack::stable_begin(), clang::T, clang::ThreadPrivateVar, V, clang::CodeGen::Address::withElementType(), and clang::CodeGen::Address::withPointer().
Referenced by EmitFunctionProlog(), and EmitInlinedInheritingCXXConstructorCall().
EmitPointerToDataMemberBinaryExpr()
LValue CodeGenFunction::EmitPointerToDataMemberBinaryExpr (const BinaryOperator * E)
Definition at line 6056 of file CGExpr.cpp.
References clang::Type::castAs(), EmitCXXMemberDataPointerAddress(), EmitLValue(), EmitPointerWithAlignment(), EmitScalarExpr(), clang::CodeGen::LValue::getAddress(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::CodeGen::Address::invalid(), and MakeAddrLValue().
Referenced by EmitBinaryOperatorLValue().
EmitPointerWithAlignment()
Address CodeGenFunction::EmitPointerWithAlignment (const Expr * Addr, LValueBaseInfo * BaseInfo = nullptr, TBAAAccessInfo * TBAAInfo = nullptr, KnownNonNull_t IsKnownNonNull = NotKnownNonNull)
EmitPointerWithAlignment - Given an expression with a pointer type, emit the value and compute our best estimate of the alignment of the pointee.
EmitPointerWithAlignment - Given an expression of pointer type, try to derive a more accurate bound on the alignment of the pointer.
Parameters
BaseInfo - If non-null, this will be initialized with information about the source of the alignment and the may-alias attribute. Note that this function will conservatively fall back on the type when it doesn't recognize the expression and may-alias will be set to false.
One reasonable way to use this information is when there's a language guarantee that the pointer must be aligned to some stricter value, and we're simply trying to ensure that sufficiently obvious uses of under- aligned objects don't get miscompiled; for example, a placement new into the address of a local variable. In such a case, it's quite reasonable to just ignore the returned alignment when it isn't from an explicit source.
Definition at line 1381 of file CGExpr.cpp.
References clang::CodeGen::Address::isKnownNonNull(), and clang::CodeGen::Address::setKnownNonNull().
Referenced by CheckAtomicAlignment(), EmitArraySubscriptExpr(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicExpr(), EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), EmitCountedByFieldExpr(), EmitCXXDeleteExpr(), EmitCXXMemberPointerCallExpr(), EmitCXXNewExpr(), EmitCXXPseudoDestructorExpr(), EmitExtVectorElementExpr(), EmitMemberExpr(), EmitNontemporalLoad(), EmitNontemporalStore(), emitOMPArraySectionBase(), EmitPointerToDataMemberBinaryExpr(), EmitPointerWithAlignment(), EmitSystemZIntrinsicWithCC(), EmitUnaryOpLValue(), EmitVAListRef(), and emitWritebackArg().
EmitPPCBuiltinExpr()
Value * CodeGenFunction::EmitPPCBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 16856 of file CGBuiltin.cpp.
References clang::Expr::getType(), and ID.
Referenced by EmitTargetArchBuiltinExpr().
EmitPredefinedLValue()
LValue CodeGenFunction::EmitPredefinedLValue (const PredefinedExpr * E)
Definition at line 3263 of file CGExpr.cpp.
References CurCodeDecl, CurFn, clang::PredefinedExpr::getFunctionName(), clang::PredefinedExpr::getIdentKind(), and clang::PredefinedExpr::getIdentKindName().
EmitPromotedComplexExpr()
ComplexPairTy CodeGenFunction::EmitPromotedComplexExpr (const Expr * E, QualType PromotionType)
Definition at line 1166 of file CGExprComplex.cpp.
EmitPromotedScalarExpr()
Value * CodeGenFunction::EmitPromotedScalarExpr (const Expr * E, QualType PromotionType)
Definition at line 5524 of file CGExprScalar.cpp.
References clang::QualType::isNull().
EmitPromotedValue()
ComplexPairTy CodeGenFunction::EmitPromotedValue (ComplexPairTy result, QualType PromotionType)
Definition at line 1121 of file CGExprComplex.cpp.
References Builder, clang::Type::castAs(), ConvertType(), and clang::ComplexType::getElementType().
EmitPseudoObjectLValue()
LValue CodeGenFunction::EmitPseudoObjectLValue (const PseudoObjectExpr * e)
Definition at line 6231 of file CGExpr.cpp.
References emitPseudoObjectExpr(), and clang::CodeGen::AggValueSlot::ignored().
EmitPseudoObjectRValue()
RValue CodeGenFunction::EmitPseudoObjectRValue (const PseudoObjectExpr * e, AggValueSlot slot = AggValueSlot::ignored())
Definition at line 6226 of file CGExpr.cpp.
References emitPseudoObjectExpr().
EmitReferenceBindingToExpr()
RValue CodeGenFunction::EmitReferenceBindingToExpr (const Expr * E)
Emits a reference binding to the passed in expression.
Definition at line 620 of file CGExpr.cpp.
References EmitLValue(), EmitTypeCheck(), clang::CodeGen::RValue::get(), clang::Expr::getExprLoc(), clang::CodeGen::LValue::getPointer(), clang::Expr::getType(), clang::Type::isFunctionType(), clang::CodeGen::LValue::isSimple(), sanitizePerformTypeCheck(), and TCK_ReferenceBinding.
Referenced by EmitCallArg(), EmitCXXGlobalVarDeclInit(), and EmitExprAsInit().
EmitReturnBlock()
llvm::DebugLoc CodeGenFunction::EmitReturnBlock ()
Emit the unified return block, trying to avoid its emission when possible.
Returns
The debug location of the user written return statement if the return block is avoided.
Definition at line 293 of file CodeGenFunction.cpp.
References Builder, EmitBlock(), clang::CodeGen::CodeGenFunction::JumpDest::getBlock(), and ReturnBlock.
Referenced by FinishFunction().
EmitReturnStmt()
void CodeGenFunction::EmitReturnStmt (const ReturnStmt & S)
EmitReturnStmt - Note that due to GCC extensions, this can have an operand if the function returns void, or may be missing one if the function returns non-void.
Fun stuff :).
Definition at line 1371 of file CGStmt.cpp.
Referenced by generateObjCGetterBody().
EmitReturnValueCheck()
void CodeGenFunction::EmitReturnValueCheck (llvm::Value * RV)
Emit a test that checks if the return value RV is nonnull.
Definition at line 4064 of file CGCall.cpp.
References Builder, createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateLoad(), CurCodeDecl, EmitBlock(), EmitCheck(), EmitCheckSourceLocation(), clang::Decl::getAttr(), clang::CodeGen::CodeGenFunction::JumpDest::getBlock(), clang::SanitizerSet::has(), clang::CodeGen::Address::invalid(), clang::CodeGen::CodeGenFunction::JumpDest::isValid(), ReturnBlock, and SanOpts.
Referenced by EmitFunctionEpilog().
EmitRISCVBuiltinExpr()
Value * CodeGenFunction::EmitRISCVBuiltinExpr (unsigned BuiltinID, const CallExpr * E, ReturnValueSlot ReturnValue)
Definition at line 24033 of file CGBuiltin.cpp.
References clang::RISCV::FirstRVVBuiltin, clang::ASTContext::GE_Missing_type, clang::ASTContext::GE_None, clang::CallExpr::getArg(), clang::CallExpr::getNumArgs(), clang::Expr::getType(), and clang::RISCV::LastRVVBuiltin.
Referenced by EmitTargetArchBuiltinExpr().
emitRotate()
RValue CodeGenFunction::emitRotate (const CallExpr * E, bool IsRotateRight)
Definition at line 2583 of file CGBuiltin.cpp.
References clang::CallExpr::getArg().
EmitRuntimeCall() [1/2]
llvm::CallInst* clang::CodeGen::CodeGenFunction::EmitRuntimeCall (llvm::FunctionCallee callee, ArrayRef< llvm::Value * > args, const Twine & name = "")
EmitRuntimeCall() [2/2]
llvm::CallInst* clang::CodeGen::CodeGenFunction::EmitRuntimeCall (llvm::FunctionCallee callee, const Twine & name = "")
Referenced by clang::CodeGen::CodeGenModule::createOpenCLIntToSamplerConversion(), createRuntimeShuffleFunction(), clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitBarrierCall(), clang::CodeGen::CGOpenMPRuntime::emitCall(), clang::CodeGen::CGOpenMPRuntime::emitCancellationPointCall(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::EmitCaptureStmt(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitDoacrossOrdered(), clang::CodeGen::CGOpenMPRuntime::emitErrorCall(), emitFilterDispatchBlock(), clang::CodeGen::CGOpenMPRuntime::emitFlush(), clang::CodeGen::CGOpenMPRuntime::emitForDispatchInit(), clang::CodeGen::CGOpenMPRuntime::emitForNext(), clang::CodeGen::CGOpenMPRuntime::emitForOrderedIterationEnd(), clang::CodeGen::CGOpenMPRuntime::emitForStaticFinish(), emitForStaticInitCall(), clang::CodeGen::CGOpenMPRuntime::emitNumTeamsClause(), clang::CodeGen::CGOpenMPRuntime::emitNumThreadsClause(), EmitObjCAutoreleasePoolPop(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), clang::CodeGen::CGOpenMPRuntime::emitProcBindClause(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFini(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskwaitCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskyieldCall(), clang::CodeGen::CGOpenMPRuntime::emitTeamsCall(), clang::CodeGen::CGOpenMPRuntime::emitThreadLimitClause(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarInit(), clang::CodeGen::CGOpenMPRuntime::emitUDMapperArrayInitOrDel(), GenerateCXXGlobalInitFunc(), clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), getEHResumeBlock(), clang::CodeGen::CGOpenMPRuntimeGPU::getGPUThreadID(), clang::CodeGen::CGOpenMPRuntimeGPU::getGPUWarpSize(), clang::CodeGen::CGOpenMPRuntimeGPU::getKmpcAllocShared(), clang::CodeGen::CGOpenMPRuntimeGPU::getKmpcFreeShared(), and clang::CodeGen::CGOpenMPRuntime::getTaskReductionItem().
EmitRuntimeCallOrInvoke() [1/2]
llvm::CallBase * CodeGenFunction::EmitRuntimeCallOrInvoke (llvm::FunctionCallee callee, ArrayRef< llvm::Value * > args, const Twine & name = "")
Emits a call or invoke instruction to the given runtime function.
Definition at line 4943 of file CGCall.cpp.
References EmitCallOrInvoke(), clang::CodeGen::CodeGenTypeCache::getRuntimeCC(), and clang::transformer::name().
Referenced by BuildBlockRelease(), EmitObjCAutoreleasePoolPop(), emitRTtypeidCall(), EmitRuntimeCallOrInvoke(), and GenerateCopyHelperFunction().
EmitRuntimeCallOrInvoke() [2/2]
llvm::CallBase * CodeGenFunction::EmitRuntimeCallOrInvoke (llvm::FunctionCallee callee, const Twine & name = "")
Emits a call or invoke instruction to the given nullary runtime function.
Definition at line 4936 of file CGCall.cpp.
References EmitRuntimeCallOrInvoke(), and clang::transformer::name().
EmitRValueForField()
RValue CodeGenFunction::EmitRValueForField (LValue LV, const FieldDecl * FD, SourceLocation Loc)
Definition at line 5431 of file CGExpr.cpp.
References clang::CodeGen::LValue::asAggregateRValue(), EmitLoadOfComplex(), EmitLoadOfLValue(), EmitLoadOfScalar(), EmitLValueForField(), clang::CodeGen::RValue::get(), clang::CodeGen::RValue::getComplex(), getEvaluationKind(), clang::CodeGen::LValue::getPointer(), clang::ValueDecl::getType(), clang::CodeGen::LValue::isBitField(), clang::Type::isReferenceType(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
EmitSanitizerStatReport()
void CodeGenFunction::EmitSanitizerStatReport (llvm::SanitizerStatKind SSK)
Definition at line 3108 of file CodeGenFunction.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGen::CodeGenModule::getSanStats().
Referenced by EmitCall(), EmitVTablePtrCheck(), and EmitVTableTypeCheckedLoad().
EmitScalarCompoundAssignWithComplex()
LValue CodeGenFunction::EmitScalarCompoundAssignWithComplex (const CompoundAssignOperator * E, llvm::Value *& Result)
Definition at line 1533 of file CGExprComplex.cpp.
References getComplexOp(), clang::BinaryOperator::getOpcode(), clang::CodeGen::RValue::getScalarVal(), and clang::interp::Ret().
emitScalarConstant()
llvm::Value * CodeGenFunction::emitScalarConstant (const ConstantEmission & Constant, Expr * E)
Definition at line 1825 of file CGExpr.cpp.
References EmitLoadOfLValue(), clang::Expr::getExprLoc(), clang::CodeGen::CodeGenFunction::ConstantEmission::getReferenceLValue(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::CodeGenFunction::ConstantEmission::getValue(), and clang::CodeGen::CodeGenFunction::ConstantEmission::isReference().
Referenced by tryEmitARCRetainLoadOfScalar().
EmitScalarConversion()
Value * CodeGenFunction::EmitScalarConversion (llvm::Value * Src, QualType SrcTy, QualType DstTy, SourceLocation Loc)
Emit a conversion from the specified type to the specified destination type, both of which are LLVM scalar types.
Definition at line 5502 of file CGExprScalar.cpp.
References hasScalarEvaluationKind().
Referenced by convertToComplexValue(), convertToScalarValue(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitDoacrossOrdered(), clang::CodeGen::CGOpenMPRuntime::emitForNext(), emitOMPAtomicCompareExpr(), emitRestoreIP(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), EmitWithOriginalRHSBitfieldAssignment(), EvaluateExprAsBool(), and getPointerAndSize().
EmitScalarExpr()
Value * CodeGenFunction::EmitScalarExpr (const Expr * E, bool IgnoreResultAssign = false)
EmitScalarExpr - Emit the computation of the specified expression of LLVM scalar type, returning the result.
Emit the computation of the specified expression of scalar type, ignoring the result.
Definition at line 5492 of file CGExprScalar.cpp.
References clang::Expr::getType(), and hasScalarEvaluationKind().
Referenced by emitAlignedClause(), EmitAnyExpr(), EmitAnyExprToMem(), EmitARCExtendBlockObject(), emitARCRetainCallResult(), EmitARCStoreUnsafeUnretained(), emitARCUnsafeClaimCallResult(), EmitArraySubscriptExpr(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicCmpXchgForMSIntrin(), EmitAtomicExpr(), EmitAtomicInit(), EmitBinaryAtomicPost(), emitBinaryBuiltin(), emitBinaryExpMaybeConstrainedFPBuiltin(), emitBinaryMaybeConstrainedFPBuiltin(), EmitBitTestIntrinsic(), EmitBlockCallExpr(), EmitCallee(), EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), clang::CodeGen::CGOpenMPRuntime::emitCriticalRegion(), EmitCXXMemberPointerCallExpr(), EmitCXXNewAllocSize(), EmitDeclInit(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), emitDeviceID(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitDoacrossOrdered(), emitDynCGGroupMem(), EmitExtVectorElementExpr(), emitFPIntBuiltin(), emitFrexpBuiltin(), EmitFunctionProlog(), EmitInitializerForField(), EmitISOVolatileLoad(), EmitISOVolatileStore(), clang::CodeGen::CGOpenMPRuntime::emitMaskedRegion(), EmitMaterializeTemporaryExpr(), EmitMatrixSubscriptExpr(), emitMaybeConstrainedFPToIntRoundBuiltin(), EmitNontemporalStore(), clang::CodeGen::CGOpenMPRuntime::emitNumTeamsClause(), clang::CodeGen::CGOpenMPRuntime::emitNumTeamsForTargetDirective(), clang::CodeGen::CGOpenMPRuntime::emitNumThreadsForTargetDirective(), EmitObjCIsaExpr(), EmitObjCIvarRefLValue(), EmitObjCMessageExpr(), EmitObjCThrowOperand(), EmitOMPArraySectionExpr(), emitOMPAtomicCompareExpr(), clang::CodeGen::CGOpenCLRuntime::emitOpenCLEnqueuedBlock(), EmitOverflowCheckedAbs(), EmitPointerToDataMemberBinaryExpr(), EmitPointerWithAlignment(), emitPPCLoadReserveIntrinsic(), emitRestoreIP(), EmitScalarInit(), EmitSystemZIntrinsicWithCC(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), emitTernaryBuiltin(), emitTernaryMaybeConstrainedFPBuiltin(), clang::CodeGen::CGOpenMPRuntime::emitThreadLimitClause(), emitUnaryMaybeConstrainedFPBuiltin(), EmitVariablyModifiedType(), EmitWithOriginalRHSBitfieldAssignment(), EvaluateExprAsBool(), GenerateSEHFilterFunction(), getPointerAndSize(), MakeBinaryAtomicValue(), tryEmitARCRetainLoadOfScalar(), and tryEmitSpecializedAllocInit().
EmitScalarInit()
void CodeGenFunction::EmitScalarInit (const Expr * init, const ValueDecl * D, LValue lvalue, bool capturedByInit)
Definition at line 824 of file CGDecl.cpp.
References clang::CodeGen::ARCImpreciseLifetime, CGM, drillIntoBlockVariable(), EmitARCInitWeak(), EmitARCRelease(), EmitARCRetainAutoreleaseScalarExpr(), EmitARCRetainScalarExpr(), EmitARCStoreWeak(), EmitARCUnsafeUnretainedScalarExpr(), emitBlockByrefAddress(), EmitLoadOfScalar(), EmitNullabilityCheck(), EmitScalarExpr(), EmitStoreOfScalar(), EmitStoreThroughLValue(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::Address::getElementType(), clang::Expr::getExprLoc(), clang::CodeGen::CodeGenModule::getNullPointer(), clang::CodeGen::LValue::getObjCLifetime(), clang::CodeGen::LValue::getType(), isAccessedBy(), clang::Qualifiers::OCL_Autoreleasing, clang::Qualifiers::OCL_ExplicitNone, clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, clang::Qualifiers::OCL_Weak, clang::CodeGen::LValue::setAddress(), and tryEmitARCCopyWeakInit().
Referenced by EmitDeclInit(), EmitExprAsInit(), EmitMaterializeTemporaryExpr(), and StoreAnyExprIntoOneUnit().
EmitScalarOrConstFoldImmArg()
llvm::Value * CodeGenFunction::EmitScalarOrConstFoldImmArg (unsigned ICEArguments, unsigned Idx, const CallExpr * E)
Definition at line 18256 of file CGBuiltin.cpp.
References clang::CallExpr::getArg(), and clang::Expr::getIntegerConstantExpr().
EmitScalarPrePostIncDec()
llvm::Value * CodeGenFunction::EmitScalarPrePostIncDec (const UnaryOperator * E, LValue LV, bool isInc, bool isPre)
Definition at line 5533 of file CGExprScalar.cpp.
Referenced by EmitUnaryOpLValue().
EmitScalarRangeCheck()
bool CodeGenFunction::EmitScalarRangeCheck (llvm::Value * Value, QualType Ty, SourceLocation Loc)
Check if the scalar Value is within the valid range for the given type Ty.
Returns true if a check is needed (even if the range is unknown).
Definition at line 1884 of file CGExpr.cpp.
References Builder, CGM, EmitCheck(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), EmitCheckValue(), End, clang::Type::getAs(), clang::CodeGen::CodeGenModule::getContext(), getLLVMContext(), getRangeForType(), clang::Value::getType(), clang::SanitizerSet::has(), hasBooleanRepresentation(), clang::NSAPI::isObjCBOOLType(), clang::Min, and SanOpts.
Referenced by EmitLoadOfBitfieldLValue(), and EmitLoadOfScalar().
EmitSEHAbnormalTermination()
llvm::Value * CodeGenFunction::EmitSEHAbnormalTermination ()
Definition at line 2158 of file CGException.cpp.
References Builder, CurFn, and clang::CodeGen::CodeGenTypeCache::Int32Ty.
EmitSehCppScopeBegin()
void CodeGenFunction::EmitSehCppScopeBegin ()
Definition at line 1328 of file CGCleanup.cpp.
References EmitSehScope().
EmitSehCppScopeEnd()
void CodeGenFunction::EmitSehCppScopeEnd ()
Definition at line 1339 of file CGCleanup.cpp.
References EmitSehScope().
EmitSEHExceptionCode()
llvm::Value * CodeGenFunction::EmitSEHExceptionCode ()
Definition at line 2153 of file CGException.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateLoad(), and SEHCodeSlotStack.
EmitSEHExceptionCodeSave()
void CodeGenFunction::EmitSEHExceptionCodeSave (CodeGenFunction & ParentCGF, llvm::Value * ParentFP, llvm::Value * EntryEBP)
Definition at line 2107 of file CGException.cpp.
References Builder, CGM, clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), CurFn, getContext(), clang::CodeGen::CodeGenTypeCache::getIntAlign(), getLLVMContext(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTriple(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenTypeCache::IntTy, ParentCGF, recoverAddrOfEscapedLocal(), SEHCodeSlotStack, SEHInfo, and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
EmitSEHExceptionInfo()
llvm::Value * CodeGenFunction::EmitSEHExceptionInfo ()
Definition at line 2144 of file CGException.cpp.
References clang::CodeGen::CodeGenTypeCache::Int8PtrTy, and SEHInfo.
EmitSEHLeaveStmt()
void CodeGenFunction::EmitSEHLeaveStmt (const SEHLeaveStmt & S)
Definition at line 2281 of file CGException.cpp.
EmitSehTryScopeBegin()
void CodeGenFunction::EmitSehTryScopeBegin ()
Definition at line 1349 of file CGCleanup.cpp.
References EmitSehScope().
EmitSehTryScopeEnd()
void CodeGenFunction::EmitSehTryScopeEnd ()
Definition at line 1359 of file CGCleanup.cpp.
References EmitSehScope().
EmitSEHTryStmt()
void CodeGenFunction::EmitSEHTryStmt (const SEHTryStmt & S)
Definition at line 1661 of file CGException.cpp.
EmitSimpleCallExpr()
RValue CodeGenFunction::EmitSimpleCallExpr (const CallExpr * E, ReturnValueSlot ReturnValue)
Emit a CallExpr without considering whether it might be a subclass.
Definition at line 5494 of file CGExpr.cpp.
References EmitCall(), EmitCallee(), clang::CallExpr::getCallee(), clang::Expr::getType(), and ReturnValue.
Referenced by clang::CodeGen::CGCUDARuntime::EmitCUDAKernelCallExpr().
EmitSimpleOMPExecutableDirective()
void CodeGenFunction::EmitSimpleOMPExecutableDirective (const OMPExecutableDirective & D)
Emit simple code for OpenMP directives in Simd-only mode.
Definition at line 8108 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate(), CGM, checkForLastprivateConditionalUpdate(), clang::CodeGen::CGOpenMPRuntime::LastprivateConditionalRAII::disable(), clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), EmitLValue(), EmitOMPScanDirective(), emitOMPSimdRegion(), EmitStmt(), EmitVarDecl(), clang::CodeGen::LValue::getAddress(), clang::OMPExecutableDirective::getAssociatedStmt(), clang::CapturedStmt::getCapturedStmt(), clang::OMPExecutableDirective::getClausesOfKind(), clang::OMPExecutableDirective::getDirectiveKind(), clang::OMPExecutableDirective::getInnermostCapturedStmt(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::OMPExecutableDirective::hasAssociatedStmt(), clang::VarDecl::hasLocalStorage(), clang::isOpenMPSimdDirective(), clang::isOpenMPTaskingDirective(), and clang::CodeGen::CodeGenFunction::OMPPrivateScope::Privatize().
EmitSimpleStmt()
bool CodeGenFunction::EmitSimpleStmt (const Stmt * S, ArrayRef< const Attr * > Attrs)
EmitSimpleStmt - Try to emit a "simple" statement which does not necessarily require an insertion point or debug information; typically because the statement amounts to a jump or a container of other statements.
Returns
True if the statement was handled.
Definition at line 448 of file CGStmt.cpp.
EmitSMELd1St1()
Value * CodeGenFunction::EmitSMELd1St1 (const SVETypeFlags & TypeFlags, llvm::SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 10251 of file CGBuiltin.cpp.
References clang::Function, and getSVEVectorForElementType().
EmitSMELdrStr()
Value * CodeGenFunction::EmitSMELdrStr (const SVETypeFlags & TypeFlags, llvm::SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 10303 of file CGBuiltin.cpp.
EmitSMEReadWrite()
Value * CodeGenFunction::EmitSMEReadWrite (const SVETypeFlags & TypeFlags, llvm::SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 10281 of file CGBuiltin.cpp.
References clang::Function, clang::SVETypeFlags::isReadZA(), and clang::SVETypeFlags::isWriteZA().
EmitSMEZero()
Value * CodeGenFunction::EmitSMEZero (const SVETypeFlags & TypeFlags, llvm::SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 10293 of file CGBuiltin.cpp.
References clang::Function.
EmitStartEHSpec()
void CodeGenFunction::EmitStartEHSpec (const Decl * D)
EmitStartEHSpec - Emit the start of the exception spec.
Definition at line 473 of file CGException.cpp.
References clang::FunctionProtoType::canThrow(), CGM, clang::CPlusPlus17, clang::CT_Cannot, EHStack, clang::EST_Dynamic, clang::EST_DynamicNone, clang::tooling::Filter, clang::CodeGen::CodeGenModule::GetAddrOfRTTIDescriptor(), clang::Type::getAs(), clang::TargetInfo::getCXXABI(), clang::CodeGen::CodeGenModule::getDiags(), clang::FunctionDecl::getExceptionSpecSourceRange(), clang::FunctionProtoType::getExceptionSpecType(), clang::FunctionProtoType::getExceptionType(), getLangOpts(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::Decl::getLocation(), clang::QualType::getNonReferenceType(), clang::FunctionProtoType::getNumExceptions(), getTarget(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), clang::LangOptions::hasWasmExceptions(), clang::TargetCXXABI::isMicrosoft(), clang::LangOptionsBase::None, clang::CodeGen::EHScopeStack::pushFilter(), clang::CodeGen::EHScopeStack::pushTerminate(), and clang::DiagnosticsEngine::Report().
Referenced by StartFunction().
EmitStaticVarDecl()
void CodeGenFunction::EmitStaticVarDecl (const VarDecl & D, llvm::GlobalValue::LinkageTypes Linkage)
Definition at line 443 of file CGDecl.cpp.
References clang::CodeGen::CodeGenModule::AddGlobalAnnotations(), clang::CodeGen::CodeGenModule::addGlobalIntelFPGAAnnotation(), AddInitializerToStaticVarDecl(), clang::CodeGen::CodeGenModule::addUsedGlobal(), clang::CodeGen::CodeGenModule::addUsedOrCompilerUsedGlobal(), CGM, ConvertTypeForMem(), clang::CodeGen::CGDebugInfo::EmitGlobalVariable(), EmitVariablyModifiedType(), clang::CharUnits::getAsAlign(), clang::Decl::getAttr(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), getDebugInfo(), clang::ASTContext::getDeclAlign(), clang::VarDecl::getInit(), getLangOpts(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl(), clang::CodeGen::CodeGenModule::getSanitizerMetadata(), clang::ValueDecl::getType(), clang::Decl::hasAttr(), clang::CodeGenOptions::hasReducedDebugInfo(), clang::Type::isVariablyModifiedType(), clang::CodeGen::SanitizerMetadata::reportGlobal(), clang::CodeGen::CGDebugInfo::setLocation(), clang::CodeGen::CodeGenModule::setStaticLocalDeclAddress(), and clang::dataflow::var().
Referenced by EmitAutoVarAlloca(), EmitDeclRefLValue(), EmitVarDecl(), clang::CodeGen::CGOpenCLRuntime::EmitWorkGroupLocalVarDecl(), and clang::CodeGen::CGSYCLRuntime::emitWorkGroupLocalVarDecl().
EmitStmt()
void CodeGenFunction::EmitStmt (const Stmt * S, ArrayRef< const Attr * > Attrs = std::nullopt)
EmitStmt - Emit the code for the statement.
S. It is legal to call this function even if there is no current insertion point.
This function may clear the current insertion point; callers should use EnsureInsertPoint if they wish to subsequently generate code without first calling EmitBlock, EmitBranch, or EmitStmt.
Definition at line 60 of file CGStmt.cpp.
Referenced by EmitConstructorBody(), EmitDestructorBody(), EmitSimpleOMPExecutableDirective(), GenerateBlockFunction(), GenerateObjCAtomicSetterCopyHelperFunction(), generateObjCSetterBody(), and GenerateSEHFinallyFunction().
EmitStmtExprLValue()
LValue CodeGenFunction::EmitStmtExprLValue (const StmtExpr * E)
Definition at line 5817 of file CGExpr.cpp.
References clang::CodeGen::Decl, EmitAnyExprToTemp(), clang::CodeGen::RValue::getAggregateAddress(), clang::Expr::getType(), and MakeAddrLValue().
EmitStopPoint()
void CodeGenFunction::EmitStopPoint (const Stmt * S)
EmitStopPoint - Emit a debug stoppoint if we are emitting debug info.
Definition at line 50 of file CGStmt.cpp.
EmitStoreOfComplex()
void CodeGenFunction::EmitStoreOfComplex (ComplexPairTy V, LValue dest, bool isInit)
EmitStoreOfComplex - Store a complex number into the specified l-value.
Definition at line 1491 of file CGExprComplex.cpp.
References V.
Referenced by complexTempStructure(), clang::CodeGen::CallArg::copyInto(), EmitAtomicUpdateValue(), EmitComplexPrePostIncDec(), EmitExprAsInit(), EmitFunctionEpilog(), emitGlobalToListCopyFunction(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), emitListToGlobalCopyFunction(), emitOMPSimpleStore(), generateObjCGetterBody(), and InitCatchParam().
EmitStoreOfScalar() [1/3]
void clang::CodeGen::CodeGenFunction::EmitStoreOfScalar (llvm::Value * Value, Address Addr, bool Volatile, QualType Ty, AlignmentSource Source = AlignmentSource::Type, bool isInit = false, bool isNontemporal = false) inline
EmitStoreOfScalar - Store a scalar value to an address, taking care to appropriately convert from the memory representation to the LLVM value representation.
Definition at line 4129 of file CodeGenFunction.h.
References CGM, and clang::CodeGen::CodeGenModule::getTBAAAccessInfo().
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), castValueToType(), clang::CodeGen::CallArg::copyInto(), EmitARCStoreAutoreleasing(), EmitARCStoreStrong(), EmitARCStoreUnsafeUnretained(), EmitAtomicExpr(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), EmitCXXGlobalVarDeclInit(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElements(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitDoacrossOrdered(), emitFrexpBuiltin(), EmitFunctionEpilog(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalFinalUpdate(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), EmitNontemporalStore(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), EmitParmDecl(), EmitScalarInit(), EmitStoreOfMatrixScalar(), EmitStoreOfScalar(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CGOpenMPRuntime::emitThreadIDAddress(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), emitWriteback(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), InitCatchParam(), shuffleAndStore(), and tryEmitARCRetainLoadOfScalar().
EmitStoreOfScalar() [2/3]
void CodeGenFunction::EmitStoreOfScalar (llvm::Value * Value, Address Addr, bool Volatile, QualType Ty, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo, bool isInit = false, bool isNontemporal = false)
Definition at line 2081 of file CGExpr.cpp.
References Builder, CGM, clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenModule::DecorateInstructionWithTBAA(), EmitAtomicStore(), emitBoolVecConversion(), EmitToMemory(), clang::CodeGen::RValue::get(), clang::Type::getAs(), clang::CodeGen::Address::getBasePointer(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::Address::getElementType(), clang::Value::getType(), clang::Type::isAtomicType(), LValueIsSuitableForInlineAtomic(), clang::CodeGen::LValue::MakeAddr(), Node, clang::CodeGen::NotKnownNonNull, clang::CodeGen::Address::withElementType(), and clang::CodeGen::Address::withPointer().
EmitStoreOfScalar() [3/3]
void CodeGenFunction::EmitStoreOfScalar (llvm::Value * value, LValue lvalue, bool isInit = false)
EmitStoreOfScalar - Store a scalar value to an address, taking care to appropriately convert from the memory representation to the LLVM value representation.
The l-value must be a simple l-value. The isInit flag indicates whether this is an initialization. If so, atomic qualifiers are ignored and the store is always non-atomic.
Definition at line 2137 of file CGExpr.cpp.
References EmitStoreOfMatrixScalar(), EmitStoreOfScalar(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getBaseInfo(), clang::CodeGen::LValue::getTBAAInfo(), clang::CodeGen::LValue::getType(), clang::Type::isConstantMatrixType(), clang::CodeGen::LValue::isNontemporal(), and clang::CodeGen::LValue::isVolatile().
EmitStoreThroughBitfieldLValue()
void CodeGenFunction::EmitStoreThroughBitfieldLValue (RValue Src, LValue Dst, llvm::Value ** Result = nullptr)
EmitStoreThroughBitfieldLValue - Store Src into Dst with same constraints as EmitStoreThroughLValue.
Parameters
Result [out] - If non-null, this will be set to a Value* for the bit-field contents after the store, appropriate for use as the result of an assignment to the bit-field.
Definition at line 2460 of file CGExpr.cpp.
References Builder, CGM, ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), EmitFromMemory(), clang::CodeGen::LValue::getBitFieldAddress(), clang::CodeGen::LValue::getBitFieldInfo(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::Address::getElementType(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::CodeGenModule::getTarget(), clang::CodeGen::LValue::getType(), hasBooleanRepresentation(), isAAPCS(), clang::CodeGen::CGBitFieldInfo::IsSigned, clang::CodeGen::LValue::isVolatileQualified(), clang::CodeGen::CGBitFieldInfo::Offset, Offset, clang::CodeGen::CGBitFieldInfo::Size, clang::CodeGen::CGBitFieldInfo::StorageSize, clang::CodeGen::CGBitFieldInfo::VolatileOffset, and clang::CodeGen::CGBitFieldInfo::VolatileStorageSize.
Referenced by EmitBinaryOperatorLValue().
EmitStoreThroughExtVectorComponentLValue()
void CodeGenFunction::EmitStoreThroughExtVectorComponentLValue (RValue Src, LValue Dst)
Definition at line 2538 of file CGExpr.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), getAccessedFieldNo(), clang::Type::getAs(), clang::CodeGen::Address::getElementType(), clang::CodeGen::LValue::getExtVectorAddress(), clang::CodeGen::LValue::getExtVectorElts(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::LValue::getType(), clang::Type::isVectorType(), clang::CodeGen::LValue::isVolatileQualified(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by EmitStoreThroughLValue().
EmitStoreThroughGlobalRegLValue()
void CodeGenFunction::EmitStoreThroughGlobalRegLValue (RValue Src, LValue Dst)
Store of global named registers are always calls to intrinsics.
Definition at line 2613 of file CGExpr.cpp.
References CGM, clang::CodeGen::CodeGenTypes::ConvertType(), clang::CodeGen::CodeGenTypes::getDataLayout(), clang::CodeGen::LValue::getGlobalReg(), clang::CodeGen::LValue::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::Type::isIntegerType(), and clang::Type::isPointerType().
Referenced by emitSimpleAtomicStore(), and EmitStoreThroughLValue().
EmitStoreThroughLValue()
void CodeGenFunction::EmitStoreThroughLValue (RValue Src, LValue Dst, bool isInit = false)
EmitStoreThroughLValue - Store the specified rvalue into the specified lvalue, where both are guaranteed to the have the same type, and that type is 'Ty'.
Definition at line 2338 of file CGExpr.cpp.
References Builder, clang::Type::castAs(), CGM, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), EmitStoreThroughExtVectorComponentLValue(), EmitStoreThroughGlobalRegLValue(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::LValue::getMatrixIdx(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::LValue::getType(), clang::CodeGen::LValue::getVectorAddress(), clang::CodeGen::LValue::getVectorIdx(), clang::CodeGen::LValue::isExtVectorElt(), clang::CodeGen::LValue::isGlobalReg(), clang::CodeGen::LValue::isMatrixElt(), clang::CodeGen::LValue::isSimple(), clang::CodeGen::LValue::isVectorElt(), and clang::CodeGen::LValue::isVolatileQualified().
Referenced by EmitAnyExprToMem(), EmitAtomicUpdateValue(), EmitAutoVarInit(), EmitBinaryOperatorLValue(), EmitExprAsInit(), EmitInitializerForField(), EmitLambdaVLACapture(), EmitOMPAtomicSimpleUpdateExpr(), emitOMPSimpleStore(), EmitScalarInit(), and emitWriteback().
EmitStringLiteralLValue()
LValue CodeGenFunction::EmitStringLiteralLValue (const StringLiteral * E)
Definition at line 3253 of file CGExpr.cpp.
References CGM, clang::CodeGen::Decl, clang::CodeGen::CodeGenModule::GetAddrOfConstantStringFromLiteral(), clang::Expr::getType(), and MakeAddrLValue().
Referenced by clang::CodeGen::CGOpenMPRuntime::emitErrorCall().
EmitSVEAllTruePred()
llvm::Value * CodeGenFunction::EmitSVEAllTruePred (const SVETypeFlags & TypeFlags)
Definition at line 9817 of file CGBuiltin.cpp.
References clang::Function.
EmitSVEDupX() [1/2]
llvm::Value* clang::CodeGen::CodeGenFunction::EmitSVEDupX (llvm::Value * Scalar)
EmitSVEDupX() [2/2]
llvm::Value* clang::CodeGen::CodeGenFunction::EmitSVEDupX (llvm::Value * Scalar, llvm::Type * Ty)
EmitSVEGatherLoad()
Value * CodeGenFunction::EmitSVEGatherLoad (const SVETypeFlags & TypeFlags, llvm::SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 9867 of file CGBuiltin.cpp.
References clang::Function, and clang::SVETypeFlags::isByteIndexed().
EmitSVEGatherPrefetch()
Value * CodeGenFunction::EmitSVEGatherPrefetch (const SVETypeFlags & TypeFlags, SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 9978 of file CGBuiltin.cpp.
EmitSVEMaskedLoad()
Value * CodeGenFunction::EmitSVEMaskedLoad (const CallExpr * , llvm::Type * ReturnTy, SmallVectorImpl< llvm::Value * > & Ops, unsigned BuiltinID, bool IsZExtReturn)
Definition at line 10153 of file CGBuiltin.cpp.
References clang::Type::castAs(), clang::CallExpr::getArg(), clang::PointerType::getPointeeType(), and clang::Expr::getType().
EmitSVEMaskedStore()
Value * CodeGenFunction::EmitSVEMaskedStore (const CallExpr * , SmallVectorImpl< llvm::Value * > & Ops, unsigned BuiltinID)
Definition at line 10203 of file CGBuiltin.cpp.
References clang::Type::castAs(), clang::CallExpr::getArg(), clang::PointerType::getPointeeType(), and clang::Expr::getType().
EmitSVEMovl()
Value * CodeGenFunction::EmitSVEMovl (const SVETypeFlags & TypeFlags, llvm::ArrayRef< llvm::Value * > Ops, unsigned BuiltinID)
Definition at line 10125 of file CGBuiltin.cpp.
References clang::Function.
EmitSVEPMull()
Value * CodeGenFunction::EmitSVEPMull (const SVETypeFlags & TypeFlags, llvm::SmallVectorImpl< llvm::Value * > & Ops, unsigned BuiltinID)
Definition at line 10107 of file CGBuiltin.cpp.
References clang::Function, clang::SVETypeFlags::getSplatOperand(), and clang::SVETypeFlags::hasSplatOperand().
EmitSVEPredicateCast()
Value * CodeGenFunction::EmitSVEPredicateCast (llvm::Value * Pred, llvm::ScalableVectorType * VTy)
Definition at line 9832 of file CGBuiltin.cpp.
References clang::Function, and clang::Value::getType().
EmitSVEPrefetchLoad()
Value * CodeGenFunction::EmitSVEPrefetchLoad (const SVETypeFlags & TypeFlags, SmallVectorImpl< llvm::Value * > & Ops, unsigned BuiltinID)
Definition at line 10132 of file CGBuiltin.cpp.
References getSVEVectorForElementType().
EmitSVEReinterpret()
Value * CodeGenFunction::EmitSVEReinterpret (llvm::Value * Val, llvm::Type * Ty)
Definition at line 10325 of file CGBuiltin.cpp.
EmitSVEScatterStore()
Value * CodeGenFunction::EmitSVEScatterStore (const SVETypeFlags & TypeFlags, llvm::SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 9921 of file CGBuiltin.cpp.
References clang::Function.
EmitSVEStructLoad()
Value * CodeGenFunction::EmitSVEStructLoad (const SVETypeFlags & TypeFlags, SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 10011 of file CGBuiltin.cpp.
EmitSVEStructStore()
Value * CodeGenFunction::EmitSVEStructStore (const SVETypeFlags & TypeFlags, SmallVectorImpl< llvm::Value * > & Ops, unsigned IntID)
Definition at line 10059 of file CGBuiltin.cpp.
EmitSVETupleCreate()
Value * CodeGenFunction::EmitSVETupleCreate (const SVETypeFlags & TypeFlags, llvm::Type * ReturnType, ArrayRef< llvm::Value * > Ops)
Definition at line 10390 of file CGBuiltin.cpp.
References clang::SVETypeFlags::isTupleCreate().
EmitSVETupleSetOrGet()
Value * CodeGenFunction::EmitSVETupleSetOrGet (const SVETypeFlags & TypeFlags, llvm::Type * ReturnType, ArrayRef< llvm::Value * > Ops)
Definition at line 10373 of file CGBuiltin.cpp.
References clang::SVETypeFlags::isTupleGet(), and clang::SVETypeFlags::isTupleSet().
EmitSwitchStmt()
void CodeGenFunction::EmitSwitchStmt (const SwitchStmt & S)
Definition at line 2023 of file CGStmt.cpp.
EmitSYCLAnnotationCall() [1/2]
llvm::Value * CodeGenFunction::EmitSYCLAnnotationCall (llvm::Function * AnnotationFn, llvm::Value * AnnotatedVal, SourceLocation Location, const SYCLAddIRAnnotationsMemberAttr * Attr)
Emit a "sycl-properties" annotation call (intrinsic).
Definition at line 2896 of file CodeGenFunction.cpp.
References getContext().
Referenced by EmitFieldSYCLAnnotations().
EmitSYCLAnnotationCall() [2/2]
llvm::Value * CodeGenFunction::EmitSYCLAnnotationCall (llvm::Function * AnnotationFn, llvm::Value * AnnotatedVal, SourceLocation Location, llvm::SmallVectorImpl< std::pair< std::string, std::string >> & Pair)
Definition at line 2907 of file CodeGenFunction.cpp.
References Builder, CGM, clang::CodeGen::CodeGenTypeCache::ConstGlobalsPtrTy, clang::CodeGen::CodeGenModule::EmitAnnotationLineNo(), clang::CodeGen::CodeGenModule::EmitAnnotationString(), clang::CodeGen::CodeGenModule::EmitAnnotationUnit(), and clang::CodeGen::CodeGenModule::EmitSYCLAnnotationArgs().
EmitSynthesizedCXXCopyCtor()
void CodeGenFunction::EmitSynthesizedCXXCopyCtor (Address Dest, Address Src, const Expr * Exp)
Definition at line 670 of file CGExprCXX.cpp.
References EmitNullInitialization(), EmitSynthesizedCXXCopyCtorCall(), clang::CXXConstructExpr::getConstructor(), getContext(), clang::Expr::getType(), and clang::CXXConstructExpr::requiresZeroInitialization().
Referenced by GenerateCopyHelperFunction().
EmitSynthesizedCXXCopyCtorCall()
void CodeGenFunction::EmitSynthesizedCXXCopyCtorCall (const CXXConstructorDecl * D, Address This, Address Src, const CXXConstructExpr * E)
Definition at line 2394 of file CGClass.cpp.
References clang::CXXConstructExpr::arguments(), Builder, clang::Type::castAs(), CGM, clang::CodeGen::CodeGenTypes::ConvertType(), clang::Ctor_Complete, EmitCallArgs(), EmitCXXConstructorCall(), clang::CodeGen::RValue::get(), getAsNaturalPointerTo(), clang::CXXConstructExpr::getConstructor(), clang::Expr::getExprLoc(), clang::CXXMethodDecl::getThisType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGen::AggValueSlot::MayOverlap, clang::FunctionProtoType::param_type_begin(), and clang::interp::This().
Referenced by EmitSynthesizedCXXCopyCtor().
EmitSystemZBuiltinExpr()
Value * CodeGenFunction::EmitSystemZBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 19193 of file CGBuiltin.cpp.
References clang::Function, and clang::CallExpr::getArg().
Referenced by EmitTargetArchBuiltinExpr().
EmitTargetBuiltinExpr()
Value * CodeGenFunction::EmitTargetBuiltinExpr (unsigned BuiltinID, const CallExpr * E, ReturnValueSlot ReturnValue)
EmitTargetBuiltinExpr - Emit the given builtin call.
Returns 0 if the call is unhandled by the current target.
Definition at line 6352 of file CGBuiltin.cpp.
References BuiltinInfo, and EmitTargetArchBuiltinExpr().
EmitToMemory()
llvm::Value * CodeGenFunction::EmitToMemory (llvm::Value * Value, QualType Ty)
EmitToMemory - Change a scalar value from its value representation to its in-memory representation.
Definition at line 2009 of file CGExpr.cpp.
References Builder, ConvertTypeForMem(), getContext(), clang::Value::getType(), getTypeSize(), and hasBooleanRepresentation().
Referenced by EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), EmitNontemporalStore(), EmitStoreOfScalar(), and EmitToInt().
EmitTrapCall()
llvm::CallInst * CodeGenFunction::EmitTrapCall (llvm::Intrinsic::ID IntrID)
Emit a call to trap or debugtrap and attach function attribute "trap-func-name" if specified.
Definition at line 3867 of file CGExpr.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getIntrinsic(), getLLVMContext(), and clang::CodeGenOptions::TrapFuncName.
Referenced by EmitCXXThrowExpr(), EmitDestructorBody(), and GenerateCode().
EmitTrapCheck()
void CodeGenFunction::EmitTrapCheck (llvm::Value * Checked, SanitizerHandler CheckHandlerID)
Create a basic block that will call the trap intrinsic, and emit a conditional branch to it, for the -ftrapv checks.
Definition at line 3823 of file CGExpr.cpp.
References Builder, CGM, ClSanitizeDebugDeoptimization(), createBasicBlock(), CurCodeDecl, EmitBlock(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getIntrinsic(), getLLVMContext(), clang::Decl::hasAttr(), clang::CodeGen::CodeGenTypeCache::Int8Ty, and clang::CodeGenOptions::TrapFuncName.
Referenced by EmitCfiCheckFail(), EmitCheck(), EmitOverflowCheckedAbs(), and EmitVTablePtrCheck().
EmitTypeCheck() [1/3]
void clang::CodeGen::CodeGenFunction::EmitTypeCheck (TypeCheckKind TCK, SourceLocation Loc, Address Addr, QualType Type, CharUnits Alignment = CharUnits::Zero(), SanitizerSet SkippedChecks = SanitizerSet(), llvm::Value * ArraySize = nullptr) inline
Definition at line 3202 of file CodeGenFunction.h.
References clang::CodeGen::Address::emitRawPointer(), EmitTypeCheck(), and sanitizePerformTypeCheck().
EmitTypeCheck() [2/3]
void CodeGenFunction::EmitTypeCheck (TypeCheckKind TCK, SourceLocation Loc, llvm::Value * V, QualType Type, CharUnits Alignment = CharUnits::Zero(), SanitizerSet SkippedChecks = SanitizerSet(), llvm::Value * ArraySize = nullptr)
Emit a check that V is the address of storage of the appropriate size and alignment for an object of type Type (or if ArraySize is provided, for an array of that bound).
Definition at line 680 of file CGExpr.cpp.
References Builder, CGM, clang::NoSanitizeList::containsType(), clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenModule::CreateRuntimeVariable(), EmitBlock(), EmitCheck(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), emitHash16Bytes(), clang::CodeGen::CodeGenModule::GetAddrOfRTTIDescriptor(), clang::CharUnits::getAsMaybeAlign(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::CodeGenModule::getIntrinsic(), getLLVMContext(), clang::CodeGen::CGCXXABI::getMangleContext(), clang::CodeGen::CodeGenModule::getMinimumObjectSize(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::ASTContext::getNoSanitizeList(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CharUnits::getQuantity(), clang::QualType::getUnqualifiedType(), clang::SanitizerSet::has(), clang::hash_value(), clang::CodeGen::CodeGenTypeCache::Int64Ty, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, clang::Type::isIncompleteType(), isNullPointerAllowed(), clang::QualType::isVolatileQualified(), isVptrCheckRequired(), clang::MangleContext::mangleCXXRTTI(), clang::Min, sanitizePerformTypeCheck(), and SanOpts.
EmitTypeCheck() [3/3]
void clang::CodeGen::CodeGenFunction::EmitTypeCheck (TypeCheckKind TCK, SourceLocation Loc, LValue LV, QualType Type, SanitizerSet SkippedChecks = SanitizerSet(), llvm::Value * ArraySize = nullptr) inline
Definition at line 3193 of file CodeGenFunction.h.
References clang::CodeGen::LValue::emitRawPointer(), clang::CodeGen::LValue::getAlignment(), and sanitizePerformTypeCheck().
Referenced by EmitCastLValue(), EmitCheckedLValue(), EmitCXXConstructorCall(), EmitCXXMemberPointerCallExpr(), EmitCXXNewExpr(), EmitDynamicCast(), EmitMemberExpr(), EmitObjectDelete(), EmitReferenceBindingToExpr(), EmitTypeCheck(), EmitTypeidFromVTable(), GetAddressOfBaseClass(), and StartFunction().
EmitTypeMetadataCodeForVCall()
void CodeGenFunction::EmitTypeMetadataCodeForVCall (const CXXRecordDecl * RD, llvm::Value * VTable, SourceLocation Loc)
If whole-program virtual table optimization is enabled, emit an assumption that VTable is a member of RD's type identifier.
Or, if vptr CFI is enabled, emit a check that VTable is a member of RD's type identifier.
Definition at line 2737 of file CGClass.cpp.
References clang::CodeGen::CodeGenModule::AlwaysHasLTOVisibilityPublic(), Builder, CFITCK_VCall, CGM, clang::CodeGen::CodeGenModule::CreateMetadataIdentifierForType(), EmitVTablePtrCheckForCall(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::TypeDecl::getTypeForDecl(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), ID, and SanOpts.
EmitUnaryOpLValue()
LValue CodeGenFunction::EmitUnaryOpLValue (const UnaryOperator * E)
Definition at line 3186 of file CGExpr.cpp.
References clang::Qualifiers::addQualifiers(), clang::Type::castAs(), CGM, emitAddrOfImagComponent(), emitAddrOfRealComponent(), EmitComplexPrePostIncDec(), EmitLValue(), EmitPointerWithAlignment(), EmitScalarPrePostIncDec(), clang::CodeGen::LValue::getAddress(), clang::QualType::getAddressSpace(), clang::CodeGen::LValue::getBaseInfo(), clang::ASTContext::getCanonicalType(), getContext(), clang::CodeGen::Address::getElementType(), getLangOpts(), clang::UnaryOperator::getOpcode(), clang::Type::getPointeeType(), clang::CodeGen::LValue::getQuals(), clang::UnaryOperator::getSubExpr(), clang::CodeGen::CodeGenModule::getTBAAInfoForSubobject(), clang::Expr::getType(), clang::CodeGen::LValue::getType(), clang::Type::isAnyComplexType(), clang::Type::isArithmeticType(), clang::Expr::isOBJCGCCandidate(), clang::CodeGen::LValue::isObjCWeak(), clang::CodeGen::LValue::isSimple(), MakeAddrLValue(), clang::LangOptionsBase::NonGC, clang::Qualifiers::setAddressSpace(), clang::CodeGen::LValue::setNonGC(), and clang::T.
EmitUnPromotedValue()
ComplexPairTy CodeGenFunction::EmitUnPromotedValue (ComplexPairTy result, QualType PromotionType)
Definition at line 1108 of file CGExprComplex.cpp.
References Builder, clang::Type::castAs(), ConvertType(), and clang::ComplexType::getElementType().
EmitUnreachable()
void CodeGenFunction::EmitUnreachable (SourceLocation Loc)
Emit a reached-unreachable diagnostic if Loc is valid and runtime checking is enabled.
Otherwise, just emit an unreachable instruction.
Definition at line 3812 of file CGExpr.cpp.
References Builder, EmitCheck(), EmitCheckSourceLocation(), clang::SanitizerSet::has(), and SanOpts.
Referenced by EmitCall(), and EmitFunctionEpilog().
EmitUnsupportedLValue()
LValue CodeGenFunction::EmitUnsupportedLValue (const Expr * E, const char * Name)
EmitUnsupportedLValue - Emit a dummy l-value using the type of E and issue an ErrorUnsupported style diagnostic (using the provided Name).
Definition at line 1430 of file CGExpr.cpp.
Referenced by EmitCastLValue(), and EmitConditionalOperatorLValue().
EmitUnsupportedRValue()
RValue CodeGenFunction::EmitUnsupportedRValue (const Expr * E, const char * Name)
EmitUnsupportedRValue - Emit a dummy r-value using the type of E and issue an ErrorUnsupported style diagnostic (using the provided Name).
Definition at line 1424 of file CGExpr.cpp.
EmitVAArg()
Address CodeGenFunction::EmitVAArg (VAArgExpr * VE, Address & VAListAddr)
Generate code to get an argument from the passed in pointer and update it accordingly.
Parameters
VE The VAArgExpr for which to generate code.
VAListAddr Receives a reference to the va_list as emitted by either EmitVAListRef or EmitMSVAListRef.
Returns
A pointer to the argument.
Definition at line 6097 of file CGCall.cpp.
References CGM, clang::CodeGen::ABIInfo::EmitMSVAArg(), EmitMSVAListRef(), clang::CodeGen::ABIInfo::EmitVAArg(), EmitVAListRef(), clang::CodeGen::CodeGenTypes::getABIInfo(), clang::VAArgExpr::getSubExpr(), clang::Expr::getType(), clang::CodeGen::CodeGenModule::getTypes(), and clang::VAArgExpr::isMicrosoftABI().
EmitVAArgExprLValue()
LValue CodeGenFunction::EmitVAArgExprLValue (const VAArgExpr * E)
Definition at line 5714 of file CGExpr.cpp.
References EmitAggExprToLValue().
EmitVAListRef()
Address CodeGenFunction::EmitVAListRef (const Expr * E)
Definition at line 2735 of file CodeGenFunction.cpp.
References EmitLValue(), EmitPointerWithAlignment(), clang::CodeGen::LValue::getAddress(), and getContext().
Referenced by EmitVAArg().
EmitVarAnnotations()
void CodeGenFunction::EmitVarAnnotations (const VarDecl * D, llvm::Value * V)
Emit local annotations for the local variable V, declared by D.
Definition at line 2856 of file CodeGenFunction.cpp.
References CGM, EmitAnnotationCall(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::Decl::getLocation(), clang::Decl::hasAttr(), clang::Decl::specific_attrs(), and V.
Referenced by EmitParmDecl().
EmitVarDecl()
void CodeGenFunction::EmitVarDecl (const VarDecl & D)
EmitVarDecl - Emit a local variable declaration.
EmitVarDecl - This method handles emission of any variable declaration inside a function, including static vars etc.
This function can be called with a null (unreachable) insert point.
Definition at line 191 of file CGDecl.cpp.
References CGM, EmitAutoVarDecl(), EmitStaticVarDecl(), clang::CodeGen::CGOpenCLRuntime::EmitWorkGroupLocalVarDecl(), clang::CodeGen::CGSYCLRuntime::emitWorkGroupLocalVarDecl(), clang::QualType::getAddressSpace(), clang::Decl::getAttr(), clang::CodeGen::CodeGenModule::getLLVMLinkageVarDefinition(), clang::CodeGen::CodeGenModule::getOpenCLRuntime(), clang::VarDecl::getStorageDuration(), clang::CodeGen::CodeGenModule::getSYCLRuntime(), clang::ValueDecl::getType(), clang::VarDecl::hasExternalStorage(), clang::VarDecl::hasLocalStorage(), clang::Type::isSamplerT(), clang::opencl_local, and clang::SD_Automatic.
Referenced by EmitDecl(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), EmitOMPHelperVar(), EmitSimpleOMPExecutableDirective(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), getNumThreads(), and clang::CodeGen::CGOpenMPRuntime::getNumThreadsExprForTargetDirective().
EmitVariablyModifiedType()
void CodeGenFunction::EmitVariablyModifiedType (QualType Ty)
EmitVLASize - Capture all the sizes for the VLA expressions in the given variably-modified type and store them in the VLASizeMap.
This function can be called with a null (unreachable) insert point.
Definition at line 2577 of file CodeGenFunction.cpp.
References Builder, EmitCheck(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), EmitIgnoredExpr(), EmitScalarExpr(), EnsureInsertPoint(), getContext(), clang::ArrayType::getElementType(), clang::VariableArrayType::getSizeExpr(), clang::Type::getTypeClass(), clang::SanitizerSet::has(), clang::Type::isSignedIntegerType(), Paren, SanOpts, clang::CodeGen::CodeGenTypeCache::SizeTy, and clang::ast_matchers::type.
Referenced by clang::CodeGen::ReductionCodeGen::emitAggregateType(), EmitAutoVarAlloca(), EmitCompoundLiteralLValue(), EmitDecl(), clang::CodeGen::CodeGenModule::EmitExplicitCastExprType(), EmitStaticVarDecl(), and StartFunction().
EmitVAStartEnd()
Value * CodeGenFunction::EmitVAStartEnd (llvm::Value * ArgValue, bool IsStart)
Emits a call to an LLVM variable-argument intrinsic, either llvm.va_start or llvm.va_end.
Parameters
ArgValue A reference to the va_list as emitted by either EmitVAListRef or EmitMSVAListRef.
IsStart If true, emits a call to llvm.va_start; otherwise, calls llvm.va_end.
Definition at line 871 of file CGBuiltin.cpp.
References ID.
EmitVTableAssumptionLoad()
void CodeGenFunction::EmitVTableAssumptionLoad (const VPtr & vptr, Address This)
Emit assumption that vptr load == global vtable.
Definition at line 2365 of file CGClass.cpp.
References ApplyNonVirtualAndVirtualOffset(), clang::CodeGen::CodeGenFunction::VPtr::Base, CGM, clang::BaseSubobject::getBaseOffset(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::CGCXXABI::getVTableAddressPoint(), GetVTablePtr(), clang::CharUnits::isZero(), clang::CodeGen::CodeGenFunction::VPtr::NearestVBase, clang::interp::This(), and clang::CodeGen::CodeGenFunction::VPtr::VTableClass.
Referenced by EmitVTableAssumptionLoads().
EmitVTableAssumptionLoads()
void CodeGenFunction::EmitVTableAssumptionLoads (const CXXRecordDecl * ClassDecl, Address This)
Emit assumption load for all bases.
Requires to be called only on most-derived class and not under construction of the object.
Definition at line 2386 of file CGClass.cpp.
References CGM, clang::CodeGen::CGCXXABI::doStructorsInitializeVPtrs(), EmitVTableAssumptionLoad(), clang::CodeGen::CodeGenModule::getCXXABI(), getVTablePointers(), and clang::interp::This().
Referenced by EmitCXXConstructorCall().
EmitVTablePtrCheck()
void CodeGenFunction::EmitVTablePtrCheck (const CXXRecordDecl * RD, llvm::Value * VTable, CFITypeCheckKind TCK, SourceLocation Loc)
EmitVTablePtrCheck - Emit a check that VTable is a valid virtual table for RD using llvm.type.test.
Definition at line 2819 of file CGClass.cpp.
References Builder, CFITCK_DerivedCast, CFITCK_ICall, CFITCK_NVCall, CFITCK_NVMFCall, CFITCK_UnrelatedCast, CFITCK_VCall, CFITCK_VMFCall, CGM, clang::CodeGen::CodeGenModule::CreateCrossDsoCfiTypeId(), clang::CodeGen::CodeGenModule::CreateMetadataIdentifierForType(), EmitCfiSlowPathCheck(), EmitCheck(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), EmitSanitizerStatReport(), EmitTrapCheck(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::CodeGenModule::getIntrinsic(), getLLVMContext(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::NamedDecl::getQualifiedNameAsString(), clang::TypeDecl::getTypeForDecl(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGenOptions::SanitizeTrap, and clang::TypeName.
Referenced by EmitVTablePtrCheckForCall(), and EmitVTablePtrCheckForCast().
EmitVTablePtrCheckForCall()
void CodeGenFunction::EmitVTablePtrCheckForCall (const CXXRecordDecl * RD, llvm::Value * VTable, CFITypeCheckKind TCK, SourceLocation Loc)
EmitVTablePtrCheckForCall - Virtual method MD is being called via VTable.
If vptr CFI is enabled, emit a check that VTable is valid.
Definition at line 2764 of file CGClass.cpp.
References EmitVTablePtrCheck(), clang::SanitizerSet::has(), LeastDerivedClassWithSameLayout(), and SanOpts.
Referenced by EmitTypeMetadataCodeForVCall().
EmitVTablePtrCheckForCast()
void CodeGenFunction::EmitVTablePtrCheckForCast (QualType T, Address Derived, bool MayBeNull, CFITypeCheckKind TCK, SourceLocation Loc)
Derived is the presumed address of an object of type T after a cast.
If T is a polymorphic class type, emit a check that the virtual table for Derived belongs to a class derived from T.
Definition at line 2774 of file CGClass.cpp.
References Builder, CGM, clang::CPlusPlus, createBasicBlock(), EmitBlock(), clang::CodeGen::Address::emitRawPointer(), EmitVTablePtrCheck(), clang::Type::getAs(), clang::CodeGen::CodeGenModule::getCXXABI(), getLangOpts(), clang::SanitizerSet::has(), clang::TagDecl::isCompleteDefinition(), clang::CXXRecordDecl::isDynamicClass(), LeastDerivedClassWithSameLayout(), clang::CodeGen::CGCXXABI::LoadVTablePtr(), SanOpts, and clang::T.
Referenced by EmitCastLValue(), and EmitPointerWithAlignment().
EmitVTableTypeCheckedLoad()
llvm::Value * CodeGenFunction::EmitVTableTypeCheckedLoad (const CXXRecordDecl * RD, llvm::Value * VTable, llvm::Type * VTableTy, uint64_t VTableByteOffset)
Emit a type checked load from the given vtable.
Definition at line 2909 of file CGClass.cpp.
References Builder, CGM, clang::CodeGen::CodeGenModule::CreateMetadataIdentifierForType(), EmitCheck(), EmitSanitizerStatReport(), getContext(), clang::CodeGen::CodeGenModule::getIntrinsic(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::NamedDecl::getQualifiedNameAsString(), clang::TypeDecl::getTypeForDecl(), clang::SanitizerSet::has(), SanOpts, and clang::TypeName.
EmitWebAssemblyBuiltinExpr()
Value * CodeGenFunction::EmitWebAssemblyBuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 22804 of file CGBuiltin.cpp.
References clang::Function, clang::CallExpr::getArg(), and clang::Expr::getType().
Referenced by EmitTargetArchBuiltinExpr().
EmitWhileStmt()
void CodeGenFunction::EmitWhileStmt (const WhileStmt & S, ArrayRef< const Attr * > Attrs = std::nullopt)
Definition at line 911 of file CGStmt.cpp.
EmitWithOriginalRHSBitfieldAssignment()
llvm::Value * CodeGenFunction::EmitWithOriginalRHSBitfieldAssignment (const BinaryOperator * E, llvm::Value ** Previous, QualType * SrcType)
Retrieve the implicit cast expression of the rhs in a binary operator expression by passing pointers to Value and QualType This is used for implicit bitfield conversion checks, which must compare with the value before potential truncation.
Definition at line 4758 of file CGExprScalar.cpp.
References EmitScalarConversion(), EmitScalarExpr(), clang::BinaryOperator::getRHS(), and Previous.
Referenced by EmitBinaryOperatorLValue().
EmitX86BuiltinExpr()
Value * CodeGenFunction::EmitX86BuiltinExpr (unsigned BuiltinID, const CallExpr * E)
Definition at line 14381 of file CGBuiltin.cpp.
References clang::ASTContext::GE_None, clang::CallExpr::getNumArgs(), ID, and translateX86ToMsvcIntrin().
Referenced by EmitTargetArchBuiltinExpr().
EmitX86MultiVersionResolver()
void CodeGenFunction::EmitX86MultiVersionResolver (llvm::Function * Resolver, ArrayRef< MultiVersionResolverOption > Options)
Definition at line 3249 of file CodeGenFunction.cpp.
enableDebugInfo()
void clang::CodeGen::CodeGenFunction::enableDebugInfo () inline
Definition at line 2121 of file CodeGenFunction.h.
EnsureInsertPoint()
void clang::CodeGen::CodeGenFunction::EnsureInsertPoint () inline
EnsureInsertPoint - Ensure that an insertion point is defined so that emitted IR has a place to go.
Note that by definition, if this function creates a block then that block is unreachable; callers may do better to detect when no insertion point is defined and simply skip IR generation.
Definition at line 2615 of file CodeGenFunction.h.
References createBasicBlock(), EmitBlock(), and HaveInsertPoint().
Referenced by EmitAutoVarAlloca(), EmitAutoVarInit(), EmitBinaryOperatorLValue(), EmitCall(), EmitVariablyModifiedType(), and clang::CodeGen::CodeGenFunction::StmtExprEvaluation::~StmtExprEvaluation().
enterByrefCleanup()
void CodeGenFunction::enterByrefCleanup (CleanupKind Kind, Address Addr, BlockFieldFlags Flags, bool LoadBlockVarAddr, bool CanThrow)
Enter a cleanup to destroy a __block variable.
Note that this cleanup should be a no-op if the variable hasn't left the stack yet; if a cleanup is required for the variable itself, that needs to be done externally.
Parameters
Kind Cleanup kind.
Addr When LoadBlockVarAddr is false, the address of the __block structure that will be passed to _Block_object_dispose. When LoadBlockVarAddr is true, the address of the field of the block structure that holds the address of the __block structure.
Flags The flag that will be passed to _Block_object_dispose.
LoadBlockVarAddr Indicates whether we need to emit a load from Addr to get the address of the __block structure.
Definition at line 2782 of file CGBlocks.cpp.
References CanThrow(), and EHStack.
Referenced by EmitAutoVarCleanups(), and pushCaptureCleanup().
EnterCXXTryStmt()
void CodeGenFunction::EnterCXXTryStmt (const CXXTryStmt & S, bool IsFnTryBlock = false)
Definition at line 635 of file CGException.cpp.
Referenced by EmitConstructorBody(), and EmitDestructorBody().
EnterDtorCleanups()
void CodeGenFunction::EnterDtorCleanups (const CXXDestructorDecl * DD, CXXDtorType DtorType)
EnterDtorCleanups - Enter the cleanups necessary to complete the given phase of destruction for a destructor.
Emit all code that comes at the end of class's destructor.
The end result should call destructors on members and base classes in reverse order of their construction.
This is to call destructors on members and base classes in reverse order of their construction.
For a deleting destructor, this also handles the case where a destroying operator delete completely overrides the definition.
Definition at line 1845 of file CGClass.cpp.
References clang::CXXRecordDecl::bases(), CGM, clang::Dtor_Base, clang::Dtor_Complete, clang::Dtor_Deleting, clang::CodeGen::EHCleanup, EHStack, EmitBranchThroughCleanup(), EmitDeleteCall(), clang::RecordDecl::fields(), getCleanupKind(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::RecordType::getDecl(), getDestroyer(), clang::CXXRecordDecl::getNumVBases(), clang::CXXDestructorDecl::getOperatorDelete(), clang::CXXMethodDecl::getParent(), clang::SanitizerSet::has(), clang::Decl::hasAttr(), clang::CXXRecordDecl::hasTrivialDestructor(), clang::RecordDecl::isAnonymousStructOrUnion(), clang::FunctionDecl::isDestroyingOperatorDelete(), clang::CXXRecordDecl::isEmpty(), clang::CXXRecordDecl::isPolymorphic(), clang::FunctionDecl::isTrivial(), clang::TagDecl::isUnion(), clang::CodeGen::NormalAndEHCleanup, ReturnBlock, SanOpts, clang::ast_matchers::type, and clang::CXXRecordDecl::vbases().
Referenced by EmitDestructorBody().
EnterSEHTryStmt()
void CodeGenFunction::EnterSEHTryStmt (const SEHTryStmt & S)
Definition at line 2170 of file CGException.cpp.
ErrorUnsupported()
void CodeGenFunction::ErrorUnsupported (const Stmt * S, const char * Type)
ErrorUnsupported - Print out an error that codegen doesn't support the specified stmt yet.
Definition at line 2287 of file CodeGenFunction.cpp.
EvaluateExprAsBool()
llvm::Value * CodeGenFunction::EvaluateExprAsBool (const Expr * E)
EvaluateExprAsBool - Perform the usual unary conversions on the specified expression and compare the result against zero, returning an Int1Ty value.
Definition at line 178 of file CGExpr.cpp.
References clang::ASTContext::BoolTy, CGM, EmitComplexExpr(), EmitComplexToScalarConversion(), clang::CodeGen::CGCXXABI::EmitMemberPointerIsNotNull(), EmitScalarConversion(), EmitScalarExpr(), clang::Type::getAs(), getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::Expr::getExprLoc(), clang::Expr::getType(), clang::Type::isAnyComplexType(), and clang::CodeGen::CodeGenPGO::setCurrentStmt().
Referenced by EmitBranchOnBoolExpr(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), getNumThreads(), and clang::CodeGen::CGOpenMPRuntime::getNumThreadsExprForTargetDirective().
ExitCXXTryStmt()
void CodeGenFunction::ExitCXXTryStmt (const CXXTryStmt & S, bool IsFnTryBlock = false)
Definition at line 1210 of file CGException.cpp.
Referenced by EmitConstructorBody(), and EmitDestructorBody().
ExitSEHTryStmt()
void CodeGenFunction::ExitSEHTryStmt (const SEHTryStmt & S)
Definition at line 2209 of file CGException.cpp.
FindCountedByField()
const FieldDecl * CodeGenFunction::FindCountedByField (const FieldDecl * FD)
Find the FieldDecl specified in a FAM's "counted_by" attribute.
Returns nullptr if either the attribute or the field doesn't exist.
Definition at line 1146 of file CGExpr.cpp.
References clang::Type::getAs(), and clang::ValueDecl::getType().
Referenced by EmitArraySubscriptExpr().
FindFlexibleArrayMemberField()
const FieldDecl * CodeGenFunction::FindFlexibleArrayMemberField (ASTContext & Ctx, const RecordDecl * RD, StringRef Name, uint64_t & Offset)
Definition at line 902 of file CGBuiltin.cpp.
FinishFunction()
void CodeGenFunction::FinishFunction (SourceLocation EndLoc = SourceLocation())
FinishFunction - Complete IR generation of the current function.
It is legal to call this function even if there is no current insertion point.
Definition at line 348 of file CodeGenFunction.cpp.
References AllocaInsertPt, Builder, CGM, clang::CodeGen::EHScopeStack::containsOnlyLifetimeMarkers(), clang::CodeGen::ApplyDebugLocation::CreateDefaultArtificial(), CurCodeDecl, CurFn, CurFnInfo, EHResumeBlock, EHStack, EmitBlock(), EmitEndEHSpec(), EmitFunctionEpilog(), EmitIfUsed(), clang::CodeGen::Address::emitRawPointer(), EmitReturnBlock(), clang::CodeGen::EHScopeStack::empty(), clang::CodeGen::CodeGenFunction::JumpDest::getBlock(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), getDebugInfo(), getLangOpts(), getLLVMContext(), clang::CodeGen::CGFunctionInfo::getMaxVectorWidth(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::RawAddress::getPointer(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getVScaleRange(), clang::CodeGen::Address::invalid(), isCoroutine(), clang::CodeGen::RawAddress::isValid(), clang::CodeGen::Address::isValid(), clang::CodeGen::CodeGenFunction::JumpDest::isValid(), max(), NormalCleanupDest, PopCleanupBlocks(), PrologueCleanupDepth, ReturnBlock, ReturnValue, ShouldInstrumentFunction(), and clang::CodeGen::EHScopeStack::stable_begin().
Referenced by createAtExitStub(), createTLSAtExitStub(), EmitCfiCheckFail(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), emitShuffleAndReduceFunction(), FinishThunk(), GenerateBlockFunction(), GenerateCode(), GenerateCopyHelperFunction(), GenerateCXXGlobalCleanUpFunc(), GenerateCXXGlobalInitFunc(), GenerateCXXGlobalVarDeclInitFunc(), generateDestroyHelper(), GenerateDestroyHelperFunction(), GenerateObjCAtomicGetterCopyHelperFunction(), GenerateObjCAtomicSetterCopyHelperFunction(), GenerateObjCGetter(), GenerateObjCMethod(), GenerateObjCSetter(), GenerateSEHFilterFunction(), and GenerateSEHFinallyFunction().
FinishThunk()
void CodeGenFunction::FinishThunk ()
Definition at line 287 of file CGVTables.cpp.
References CurCodeDecl, CurFuncDecl, and FinishFunction().
Referenced by EmitCallAndReturnForThunk(), and EmitMustTailThunk().
FormSVEBuiltinResult()
Value * CodeGenFunction::FormSVEBuiltinResult (llvm::Value * Call)
FormSVEBuiltinResult - Returns the struct of scalable vectors as a wider vector.
It extracts the scalable vector from the struct and inserts into the wider vector. This avoids the error when allocating space in llvm for struct of scalable vectors if a function returns struct.
Definition at line 10406 of file CGBuiltin.cpp.
References clang::interp::Ret().
generateAwaitSuspendWrapper()
llvm::Function * CodeGenFunction::generateAwaitSuspendWrapper (Twine const & CoroName, Twine const & SuspendPointName, CoroutineSuspendExpr const & S)
Definition at line 413 of file CGCoroutine.cpp.
GenerateBlockFunction()
llvm::Function * CodeGenFunction::GenerateBlockFunction (GlobalDecl GD, const CGBlockInfo & Info, const DeclMapTy & ldm, bool IsLambdaConversionToBlock, bool BuildGlobalBlock)
Definition at line 1414 of file CGBlocks.cpp.
References clang::interp::align(), clang::CodeGen::CodeGenTypes::arrangeBlockFunctionDeclaration(), clang::CodeGen::CodeGenPGO::assignRegionCounters(), clang::ast_matchers::blockDecl, BlockInfo, BlockPointer, Builder, buildGlobalBlock(), CGM, clang::CodeGen::ApplyDebugLocation::CreateEmpty(), clang::CodeGen::CGBuilderTy::CreateLoad(), CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), CreateTempAlloca(), CurGD, clang::CodeGen::CGBlockInfo::CXXThisIndex, EmitLambdaBlockInvokeBody(), clang::CodeGen::Address::emitRawPointer(), EmitStmt(), FinishFunction(), clang::IdentifierTable::get(), clang::Stmt::getBeginLoc(), clang::CodeGen::CGBlockInfo::getBlockDecl(), clang::CodeGen::CGBlockInfo::getBlockExpr(), clang::CodeGen::CodeGenModule::getBlockMangledName(), clang::BlockExpr::getBody(), clang::CodeGen::CGBlockInfo::getCapture(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CGBlockInfo::Capture::getConstant(), getContext(), clang::CodeGen::CodeGenModule::getContext(), getDebugInfo(), clang::ASTContext::getDeclAlign(), clang::BlockExpr::getEndLoc(), clang::BlockExpr::getFunctionType(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CGOpenCLRuntime::getGenericVoidPointerType(), clang::ASTContext::getLangOpts(), getLangOpts(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::CodeGenModule::getOpenCLRuntime(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::ASTContext::getPointerType(), clang::FunctionType::getReturnType(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::CodeGenOptions::hasReducedDebugInfo(), clang::ASTContext::Idents, incrementProfileCounter(), clang::CodeGen::CGBlockInfo::Capture::isConstant(), LoadBlockStruct(), clang::transformer::name(), clang::ObjCSelf, clang::OpenCL, clang::opencl_generic, clang::CodeGen::CodeGenModule::ReturnSlotInterferesWithArgs(), clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), StartFunction(), clang::CodeGen::CGBlockInfo::UsesStret, clang::dataflow::var(), clang::ASTContext::VoidPtrTy, clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
generateBuiltinOSLogHelperFunction()
llvm::Function * CodeGenFunction::generateBuiltinOSLogHelperFunction (const analyze_os_log::OSLogBufferLayout & Layout, CharUnits BufferAlignment)
Definition at line 2218 of file CGBuiltin.cpp.
GenerateCapturedStmtArgument()
Address CodeGenFunction::GenerateCapturedStmtArgument (const CapturedStmt & S)
Definition at line 3039 of file CGStmt.cpp.
GenerateCapturedStmtFunction()
llvm::Function * CodeGenFunction::GenerateCapturedStmtFunction (const CapturedStmt & S)
Creates the outlined function for a CapturedStmt.
Definition at line 3046 of file CGStmt.cpp.
GenerateCode()
void CodeGenFunction::GenerateCode (GlobalDecl GD, llvm::Function * Fn, const CGFunctionInfo & FnInfo)
Definition at line 1608 of file CodeGenFunction.cpp.
References clang::CodeGen::CodeGenPGO::assignRegionCounters(), Builder, BuildFunctionArgList(), Bypasses, CGM, clang::CodeGen::TargetCodeGenInfo::checkFunctionABI(), checkIfFunctionMustProgress(), clang::CPlusPlus, clang::CUDA, CurFn, CurGD, EmitCheck(), EmitCheckSourceLocation(), EmitConstructorBody(), EmitDestructorBody(), clang::CodeGen::CGCUDARuntime::emitDeviceStub(), EmitFunctionBody(), emitImplicitAssignmentOperatorBody(), EmitLambdaInAllocaCallOpBody(), EmitLambdaStaticInvokeBody(), EmitTrapCall(), FinishFunction(), FnArgs, clang::Decl::getASTContext(), clang::SourceRange::getBegin(), clang::FunctionDecl::getBody(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getCUDARuntime(), clang::GlobalDecl::getDecl(), clang::CodeGen::CodeGenModule::getDiags(), clang::SourceRange::getEnd(), clang::SyclOptReportHandler::GetInfo(), getLangOpts(), clang::Decl::getLocation(), clang::Redeclarable< decl_type >::getPreviousDecl(), clang::FunctionDecl::getReturnType(), clang::DiagnosticsEngine::getSYCLOptReport(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::FunctionDecl::getTemplateInstantiationPattern(), clang::SanitizerSet::has(), clang::Decl::hasAttr(), clang::FunctionDecl::hasImplicitReturnZero(), clang::SyclOptReportHandler::HasOptReportInfo(), clang::CodeGen::VarBypassDetector::Init(), clang::FunctionDecl::isDefaulted(), clang::CodeGen::CGFunctionInfo::isDelegateCall(), clang::FunctionDecl::isInlineBuiltinDeclaration(), clang::isLambdaCallOperator(), clang::Type::isVoidType(), clang::CodeGen::CodeGenModule::MayDropFunctionReturn(), clang::CodeGen::noSystemDebugInfo(), clang::FunctionDecl::parameters(), SanOpts, SawAsmBlock, SourceLocToDebugLoc(), StartFunction(), and TryMarkNoThrow().
Referenced by clang::CodeGen::CodeGenModule::codegenCXXStructor(), and EmitLambdaInAllocaImplFn().
GenerateCopyHelperFunction()
llvm::Constant * CodeGenFunction::GenerateCopyHelperFunction (const CGBlockInfo & blockInfo)
Generate the copy-helper function for a block closure object: static void block_copy_helper(block_t *dst, block_t *src); The runtime will have previously initialized 'dst' by doing a bit-copy of 'src'.
Note that this copies an entire block closure object to the heap; it should not be confused with a 'byref copy helper', which moves the contents of an individual __block variable to the heap.
Definition at line 1869 of file CGBlocks.cpp.
References clang::CodeGen::ARCStrong, clang::CodeGen::ARCWeak, clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CGBlockInfo::BlockAlign, clang::CodeGen::BlockObject, Builder, callCStructCopyConstructor(), clang::CodeGen::CGBlockInfo::Capture::Cap, clang::CodeGen::CGBlockInfo::CapturesNonExternalType, CGM, clang::CodeGen::CGBlockInfo::Capture::CopyFlags, clang::CodeGen::CGBlockInfo::Capture::CopyKind, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), clang::CodeGen::CXXRecord, EmitARCCopyWeak(), EmitARCRetainNonBlock(), EmitARCStoreStrongCall(), EmitNounwindRuntimeCall(), clang::CodeGen::Address::emitRawPointer(), EmitRuntimeCallOrInvoke(), EmitSynthesizedCXXCopyCtor(), FinishFunction(), clang::Func, GetAddrOfLocalVar(), clang::CodeGen::Address::getBasePointer(), clang::CodeGen::BlockFieldFlags::getBitMask(), clang::CodeGen::CodeGenModule::getBlockObjectAssign(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), getCopyDestroyHelperFuncName(), clang::BlockDecl::Capture::getCopyExpr(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CGBlockInfo::Capture::getIndex(), clang::CodeGen::CodeGenModule::getModule(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::BlockDecl::Capture::getVariable(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::BlockDecl::Capture::isByRef(), clang::CodeGen::CGBlockInfo::Capture::isConstantOrTrivial(), clang::QualType::isDestructedType(), MakeAddrLValue(), needsEHCleanup(), clang::CodeGen::None, clang::CodeGen::NonTrivialCStruct, clang::Other, pushCaptureCleanup(), setBlockHelperAttributesVisibility(), clang::CodeGen::CGBlockInfo::SortedCaptures, StartFunction(), clang::CodeGen::CGBlockInfo::StructureType, and clang::CodeGen::CodeGenModule::supportsCOMDAT().
Referenced by buildCopyHelper().
GenerateCXXGlobalCleanUpFunc()
void CodeGenFunction::GenerateCXXGlobalCleanUpFunc (llvm::Function * Fn, ArrayRef< std::tuple< llvm::FunctionType *, llvm::WeakTrackingVH, llvm::Constant * >> DtorsOrStermFinalizers)
GenerateCXXGlobalCleanUpFunc - Generates code for cleaning up global variables.
Definition at line 1105 of file CGDeclCXX.cpp.
References Builder, CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), clang::CodeGen::ApplyDebugLocation::CreateEmpty(), FinishFunction(), getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), getTypes(), StartFunction(), clang::CodeGen::CGCXXABI::useSinitAndSterm(), and clang::CodeGen::CodeGenTypeCache::VoidTy.
GenerateCXXGlobalInitFunc()
void CodeGenFunction::GenerateCXXGlobalInitFunc (llvm::Function * Fn, ArrayRef< llvm::Function * > CXXThreadLocals, ConstantAddress Guard = ConstantAddress::invalid())
GenerateCXXGlobalInitFunc - Generates code for initializing global variables.
Definition at line 1047 of file CGDeclCXX.cpp.
References Builder, CGM, clang::CPlusPlus, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), createBasicBlock(), clang::CodeGen::ApplyDebugLocation::CreateEmpty(), clang::CodeGen::CGBuilderTy::CreateIsNull(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), EmitBlock(), EmitCXXGuardedInitBranch(), EmitInvariantStart(), EmitObjCAutoreleasePoolCleanup(), EmitObjCAutoreleasePoolPush(), EmitRuntimeCall(), FinishFunction(), clang::CharUnits::fromQuantity(), getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), getLangOpts(), clang::CodeGen::ConstantAddress::getPointer(), getTypes(), clang::CodeGen::RawAddress::isValid(), StartFunction(), TlsGuard, and clang::CodeGen::CodeGenTypeCache::VoidTy.
GenerateCXXGlobalVarDeclInitFunc()
void CodeGenFunction::GenerateCXXGlobalVarDeclInitFunc (llvm::Function * Fn, const VarDecl * D, llvm::GlobalVariable * Addr, bool PerformInit)
Emit the code necessary to initialize the given global variable.
Definition at line 1009 of file CGDeclCXX.cpp.
References clang::CodeGen::CGHLSLRuntime::annotateHLSLResource(), CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), EmitCXXGlobalVarDeclInit(), EmitCXXGuardedInit(), FinishFunction(), clang::DeclaratorDecl::getBeginLoc(), getContext(), clang::CodeGen::CodeGenModule::getHLSLRuntime(), getLangOpts(), clang::VarDecl::getTemplateSpecializationKind(), clang::VarDecl::getTLSKind(), getTypes(), clang::Decl::hasAttr(), clang::HLSL, clang::Initializer, clang::isTemplateInstantiation(), clang::CodeGen::noSystemDebugInfo(), StartFunction(), clang::VarDecl::TLS_Dynamic, and clang::CodeGen::CodeGenTypeCache::VoidTy.
generateDestroyHelper()
llvm::Function * CodeGenFunction::generateDestroyHelper (Address addr, QualType type, Destroyer * destroyer, bool useEHCleanupForArray, const VarDecl * VD)
generateDestroyHelper - Generates a helper function which, when invoked, destroys the given object.
The address of the object should be in global memory.
Definition at line 1145 of file CGDeclCXX.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), clang::CodeGen::CodeGenModule::CreateGlobalInitOrCleanUpFunction(), emitDestroy(), FinishFunction(), clang::DeclaratorDecl::getBeginLoc(), getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getTypes(), clang::GlobalArrayDestructor, clang::Other, StartFunction(), clang::ast_matchers::type, clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
Referenced by EmitDeclDestroy(), and pushTemporaryCleanup().
GenerateDestroyHelperFunction()
llvm::Constant * CodeGenFunction::GenerateDestroyHelperFunction (const CGBlockInfo & blockInfo)
Generate the destroy-helper function for a block closure object: static void block_destroy_helper(block_t *theBlock);.
Note that this destroys a heap-allocated block closure object; it should not be confused with a 'byref destroy helper', which destroys the heap-allocated contents of an individual __block variable.
Definition at line 2058 of file CGBlocks.cpp.
References clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), clang::CodeGen::CGBlockInfo::BlockAlign, Builder, clang::CodeGen::CGBlockInfo::Capture::Cap, clang::CodeGen::CGBlockInfo::CapturesNonExternalType, CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), clang::CodeGen::CGBlockInfo::Capture::DisposeFlags, clang::CodeGen::CGBlockInfo::Capture::DisposeKind, FinishFunction(), clang::CodeGen::CodeGenFunction::RunCleanupsScope::ForceCleanup(), clang::Func, GetAddrOfLocalVar(), getContext(), getCopyDestroyHelperFuncName(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CodeGen::CGBlockInfo::Capture::getIndex(), clang::CodeGen::CodeGenModule::getModule(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::BlockDecl::Capture::getVariable(), clang::CodeGen::CGBlockInfo::Capture::isConstantOrTrivial(), markAsIgnoreThreadCheckingAtRuntime(), clang::Other, pushCaptureCleanup(), setBlockHelperAttributesVisibility(), clang::CodeGen::CGBlockInfo::SortedCaptures, StartFunction(), clang::CodeGen::CGBlockInfo::StructureType, and clang::CodeGen::CodeGenModule::supportsCOMDAT().
Referenced by buildDisposeHelper().
GenerateObjCAtomicGetterCopyHelperFunction()
llvm::Constant * CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction (const ObjCPropertyImplDecl * PID)
Definition at line 3788 of file CGObjC.cpp.
References clang::QualType::addConst(), clang::CXXConstructExpr::arg_begin(), clang::CXXConstructExpr::arg_end(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), CGM, ConvertTypeForMem(), clang::CPlusPlus, clang::ParmVarDecl::Create(), clang::FunctionDecl::Create(), clang::UnaryOperator::Create(), clang::CXXConstructExpr::Create(), clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, EmitAggExpr(), EmitAnyExpr(), FinishFunction(), clang::CodeGen::AggValueSlot::forAddr(), clang::IdentifierTable::get(), clang::CodeGen::CodeGenModule::getAtomicGetterHelperFnMap(), clang::CXXConstructExpr::getConstructionKind(), clang::CXXConstructExpr::getConstructor(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::ObjCPropertyImplDecl::getGetterCXXConstructor(), getLangOpts(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::getNonTrivialCStructCopyConstructor(), clang::Type::getPointeeType(), clang::ObjCPropertyDecl::getPropertyAttributes(), clang::ObjCPropertyImplDecl::getPropertyDecl(), clang::CodeGen::RValue::getScalarVal(), clang::ObjCPropertyDecl::getType(), clang::Expr::getType(), clang::ASTContext::getTypeAlignInChars(), clang::CodeGen::CodeGenModule::getTypes(), clang::CXXConstructExpr::hadMultipleCandidates(), clang::ObjCRuntime::hasAtomicCopyHelper(), hasTrivialGetExpr(), clang::ASTContext::Idents, clang::CodeGen::AggValueSlot::IsDestructed, clang::CXXConstructExpr::isElidable(), clang::CXXConstructExpr::isListInitialization(), clang::QualType::isNonTrivialToPrimitiveCopy(), clang::CodeGen::AggValueSlot::IsNotAliased, clang::Type::isRecordType(), clang::CXXConstructExpr::isStdInitListInitialization(), clang::QualType::isVolatileQualified(), clang::ObjCPropertyAttribute::kind_atomic, clang::OK_Ordinary, clang::QualType::PCK_Struct, clang::CXXConstructExpr::requiresZeroInitialization(), clang::SC_None, clang::SC_Static, clang::CodeGen::CodeGenModule::setAtomicGetterHelperFnMap(), clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), StartFunction(), clang::VK_LValue, and clang::VK_PRValue.
Referenced by GenerateObjCGetter().
GenerateObjCAtomicSetterCopyHelperFunction()
llvm::Constant * CodeGenFunction::GenerateObjCAtomicSetterCopyHelperFunction (const ObjCPropertyImplDecl * PID)
GenerateObjCAtomicSetterCopyHelperFunction - Given a c++ object type with non-trivial copy assignment function, produce following helper function.
static void copyHelper(Ty *dest, const Ty *source) { *dest = *source; }
Definition at line 3688 of file CGObjC.cpp.
References clang::QualType::addConst(), clang::CodeGen::CodeGenTypes::arrangeBuiltinFunctionDeclaration(), CGM, clang::CPlusPlus, clang::ParmVarDecl::Create(), clang::FunctionDecl::Create(), clang::UnaryOperator::Create(), clang::CXXOperatorCallExpr::Create(), EmitStmt(), FinishFunction(), clang::IdentifierTable::get(), clang::CodeGen::CodeGenModule::getAtomicSetterHelperFnMap(), clang::CallExpr::getCallee(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenTypes::GetFunctionType(), getLangOpts(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::getNonTrivialCStructMoveAssignmentOperator(), clang::Type::getPointeeType(), clang::ObjCPropertyDecl::getPropertyAttributes(), clang::ObjCPropertyImplDecl::getPropertyDecl(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), clang::ObjCPropertyImplDecl::getSetterCXXAssignment(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::ObjCRuntime::hasAtomicCopyHelper(), hasTrivialSetExpr(), clang::ASTContext::Idents, clang::QualType::isNonTrivialToPrimitiveCopy(), clang::Type::isRecordType(), clang::QualType::isVolatileQualified(), clang::ObjCPropertyAttribute::kind_atomic, clang::OK_Ordinary, clang::QualType::PCK_Struct, clang::SC_None, clang::SC_Static, clang::CodeGen::CodeGenModule::setAtomicSetterHelperFnMap(), clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), StartFunction(), clang::VK_LValue, and clang::VK_PRValue.
Referenced by GenerateObjCSetter().
GenerateObjCCtorDtorMethod()
void CodeGenFunction::GenerateObjCCtorDtorMethod (ObjCImplementationDecl * IMP, ObjCMethodDecl * MD, bool ctor)
Definition at line 1709 of file CGObjC.cpp.
References AutoreleaseResult, CGM, clang::ObjCMethodDecl::createImplicitParams(), clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::AggValueSlot::DoesNotOverlap, EmitAggExpr(), EmitLValueForIvar(), clang::CodeGen::AggValueSlot::forLValue(), clang::ObjCImplDecl::getClassInterface(), clang::CodeGen::CodeGenModule::getContext(), clang::ObjCImplementationDecl::inits(), clang::CodeGen::AggValueSlot::IsDestructed, clang::CodeGen::AggValueSlot::IsNotAliased, LoadObjCSelf(), StartObjCMethod(), and TypeOfSelfObject().
GenerateObjCGetter()
void CodeGenFunction::GenerateObjCGetter (ObjCImplementationDecl * IMP, const ObjCPropertyImplDecl * PID)
GenerateObjCGetter - Synthesize an Objective-C property getter function.
Generate an Objective-C property getter function.
The given Decl must be an ObjCImplementationDecl. @synthesize is illegal within a category.
Definition at line 1050 of file CGObjC.cpp.
References CGM, FinishFunction(), GenerateObjCAtomicGetterCopyHelperFunction(), generateObjCGetterBody(), clang::ObjCImplDecl::getClassInterface(), clang::ObjCMethodDecl::getEndLoc(), clang::ObjCPropertyImplDecl::getGetterMethodDecl(), and StartObjCMethod().
generateObjCGetterBody()
void CodeGenFunction::generateObjCGetterBody (const ObjCImplementationDecl * classImpl, const ObjCPropertyImplDecl * propImpl, const ObjCMethodDecl * GetterMothodDecl, llvm::Constant * AtomicHelperFn)
Definition at line 1136 of file CGObjC.cpp.
References clang::CodeGen::CallArgList::add(), AutoreleaseResult, Builder, callCStructCopyConstructor(), CGM, ConvertType(), clang::ReturnStmt::Create(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), EmitAggregateCopy(), EmitARCLoadWeak(), emitARCRetainLoadOfScalar(), EmitCall(), emitCmdValueForGetterSetterBody(), emitCPPObjectAtomicGetterCall(), EmitIvarOffsetAsPointerDiff(), EmitLoadOfComplex(), EmitLoadOfLValue(), EmitLValueForIvar(), clang::CodeGen::Address::emitRawPointer(), EmitReturnStmt(), EmitStoreOfComplex(), emitStructGetterCall(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), clang::ObjCImplDecl::getClassInterface(), getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), getEvaluationKind(), clang::ObjCPropertyImplDecl::getGetterCXXConstructor(), clang::ObjCPropertyImplDecl::getGetterMethodDecl(), getLangOpts(), getLLVMContext(), clang::Qualifiers::getObjCLifetime(), clang::CodeGen::CodeGenModule::getObjCRuntime(), getOverlapForReturnValue(), clang::ObjCPropertyImplDecl::getPropertyDecl(), clang::CodeGen::CGObjCRuntime::GetPropertyGetFunction(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), clang::CodeGen::LValue::getQuals(), clang::ObjCMethodDecl::getReturnType(), clang::CodeGen::RValue::getScalarVal(), clang::ValueDecl::getType(), clang::ObjCPropertyDecl::getType(), getTypes(), hasTrivialGetExpr(), clang::QualType::isNonTrivialToPrimitiveCopy(), clang::Type::isReferenceType(), LoadObjCSelf(), MakeAddrLValue(), clang::Qualifiers::OCL_Weak, clang::QualType::PCK_Struct, ReturnValue, clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, clang::ASTContext::toBits(), TypeOfSelfObject(), clang::CodeGen::CodeGenTypeCache::VoidPtrTy, and clang::CodeGen::Address::withElementType().
Referenced by GenerateObjCGetter().
GenerateObjCMethod()
void CodeGenFunction::GenerateObjCMethod (const ObjCMethodDecl * OMD)
Generate an Objective-C method.
An Objective-C method is a C function with its pointer, name, and types registered in the class structure.
Definition at line 808 of file CGObjC.cpp.
References clang::CodeGen::CodeGenPGO::assignRegionCounters(), CurFn, EmitCompoundStmtWithoutScope(), FinishFunction(), clang::ObjCMethodDecl::getBody(), clang::Decl::getBodyRBrace(), clang::ObjCMethodDecl::getClassInterface(), incrementProfileCounter(), and StartObjCMethod().
Referenced by clang::CodeGen::CodeGenModule::EmitTopLevelDecl().
GenerateObjCSetter()
void CodeGenFunction::GenerateObjCSetter (ObjCImplementationDecl * IMP, const ObjCPropertyImplDecl * PID)
GenerateObjCSetter - Synthesize an Objective-C property setter function for the given property.
Generate an Objective-C property setter function.
The given Decl must be an ObjCImplementationDecl. @synthesize is illegal within a category.
Definition at line 1629 of file CGObjC.cpp.
References CGM, FinishFunction(), GenerateObjCAtomicSetterCopyHelperFunction(), generateObjCSetterBody(), clang::ObjCImplDecl::getClassInterface(), clang::ObjCMethodDecl::getEndLoc(), clang::ObjCPropertyImplDecl::getSetterMethodDecl(), and StartObjCMethod().
generateObjCSetterBody()
void CodeGenFunction::generateObjCSetterBody (const ObjCImplementationDecl * classImpl, const ObjCPropertyImplDecl * propImpl, llvm::Constant * AtomicHelperFn)
Definition at line 1433 of file CGObjC.cpp.
References clang::CodeGen::CallArgList::add(), AllocaInsertPt, std::arg(), Builder, callCStructMoveAssignmentOperator(), CGM, clang::BinaryOperator::Create(), clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStore(), DeactivateCleanupBlock(), EmitCall(), emitCmdValueForGetterSetterBody(), emitCPPObjectAtomicSetterCall(), EmitIvarOffsetAsPointerDiff(), EmitLValueForIvar(), EmitStmt(), emitStructSetterCall(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::CGCallee::forDirect(), clang::CodeGen::RValue::get(), clang::CodeGen::LValue::getAddress(), GetAddrOfLocalVar(), clang::ObjCImplDecl::getClassInterface(), getContext(), getLLVMContext(), clang::QualType::getNonReferenceType(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::CodeGen::CGObjCRuntime::GetOptimizedPropertySetFunction(), clang::ObjCPropertyImplDecl::getPropertyIvarDecl(), clang::CodeGen::CGObjCRuntime::GetPropertySetFunction(), clang::ObjCMethodDecl::getSelfDecl(), clang::ObjCPropertyImplDecl::getSetterCXXAssignment(), clang::ObjCPropertyImplDecl::getSetterMethodDecl(), clang::ValueDecl::getType(), clang::Expr::getType(), getTypes(), clang::QualType::getUnqualifiedType(), hasTrivialSetExpr(), clang::Type::isAtomicType(), clang::Type::isBlockPointerType(), clang::QualType::isNonTrivialToPrimitiveCopy(), clang::Type::isObjCObjectPointerType(), clang::Type::isPointerType(), LoadObjCSelf(), MakeAddrLValue(), clang::OK_Ordinary, clang::ImplicitCastExpr::OnStack, clang::ObjCMethodDecl::param_begin(), clang::QualType::PCK_Struct, TypeOfSelfObject(), UseOptimizedSetter(), clang::VK_LValue, clang::VK_PRValue, clang::CodeGen::CodeGenTypeCache::VoidPtrTy, clang::CodeGen::CodeGenTypeCache::VoidTy, and clang::CodeGen::Address::withElementType().
Referenced by GenerateObjCSetter().
GenerateOpenMPCapturedStmtFunction()
llvm::Function * CodeGenFunction::GenerateOpenMPCapturedStmtFunction (const CapturedStmt & S, SourceLocation Loc)
Definition at line 617 of file CGStmtOpenMP.cpp.
Referenced by emitParallelOrTeamsOutlinedFunction(), and clang::CodeGen::CGOpenMPRuntime::emitTargetOutlinedFunctionHelper().
GenerateOpenMPCapturedVars()
void CodeGenFunction::GenerateOpenMPCapturedVars (const CapturedStmt & S, SmallVectorImpl< llvm::Value * > & CapturedVars)
Definition at line 330 of file CGStmtOpenMP.cpp.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), and emitTargetCallFallback().
GenerateSEHFilterFunction()
llvm::Function * CodeGenFunction::GenerateSEHFilterFunction (CodeGenFunction & ParentCGF, const SEHExceptStmt & Except)
Create a stub filter function that will ultimately hold the code of the filter expression.
The EH preparation passes in LLVM will outline the code from the main function body into this stub.
Definition at line 2077 of file CGException.cpp.
References Builder, ConvertType(), clang::CodeGen::CGBuilderTy::CreateStore(), CurFn, EmitScalarExpr(), FinishFunction(), getContext(), clang::Stmt::getEndLoc(), clang::SEHExceptStmt::getFilterExpr(), clang::Expr::getType(), clang::Type::isSignedIntegerType(), ParentCGF, ReturnValue, and startOutlinedSEHHelper().
GenerateSEHFinallyFunction()
llvm::Function * CodeGenFunction::GenerateSEHFinallyFunction (CodeGenFunction & ParentCGF, const SEHFinallyStmt & Finally)
Definition at line 2094 of file CGException.cpp.
References CurFn, EmitStmt(), FinishFunction(), clang::SEHFinallyStmt::getBlock(), clang::Stmt::getEndLoc(), ParentCGF, and startOutlinedSEHHelper().
generateThunk()
void CodeGenFunction::generateThunk (llvm::Function * Fn, const CGFunctionInfo & FnInfo, GlobalDecl GD, const ThunkInfo & Thunk, bool IsUnprototyped)
Generate a thunk for the given method.
Definition at line 449 of file CGVTables.cpp.
References CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::CodeGen::CodeGenTypes::GetFunctionType(), getLLVMContext(), clang::CodeGen::CodeGenModule::getTypes(), and StartThunk().
GenerateVarArgsThunk()
llvm::Function * CodeGenFunction::GenerateVarArgsThunk (llvm::Function * Fn, const CGFunctionInfo & FnInfo, GlobalDecl GD, const ThunkInfo & Thunk)
Definition at line 160 of file CGVTables.cpp.
References Builder, clang::Type::castAs(), CGM, CurFn, clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenModule::GetAddrOfFunction(), clang::CodeGen::CodeGenModule::getClassPointerAlignment(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::GlobalDecl::getDecl(), clang::CXXMethodDecl::getFunctionObjectParameterType(), clang::CodeGen::CodeGenTypes::GetFunctionType(), clang::CXXMethodDecl::getParent(), clang::FunctionType::getReturnType(), clang::CodeGen::RValue::getScalarVal(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenModule::getTypes(), clang::FunctionDecl::isDefined(), clang::ReturnAdjustment::isEmpty(), clang::CodeGen::CGFunctionInfo::isVariadic(), makeNaturalAddressForPointer(), PerformReturnAdjustment(), clang::CodeGen::CGCXXABI::performThisAdjustment(), resolveTopLevelMetadata(), clang::ThunkInfo::Return, clang::CodeGen::CodeGenModule::ReturnTypeUsesSRet(), clang::T, and clang::ThunkInfo::This.
GetAArch64SVEProcessedOperands()
void CodeGenFunction::GetAArch64SVEProcessedOperands (unsigned BuiltinID, const CallExpr * E, SmallVectorImpl< llvm::Value * > & Ops, SVETypeFlags TypeFlags)
Definition at line 10441 of file CGBuiltin.cpp.
References clang::ASTContext::GE_None, clang::CallExpr::getArg(), clang::Expr::getIntegerConstantExpr(), clang::CallExpr::getNumArgs(), clang::SVETypeFlags::isTupleGet(), and clang::SVETypeFlags::isTupleSet().
getAccessedFieldNo()
unsigned CodeGenFunction::getAccessedFieldNo (unsigned Idx, const llvm::Constant * Elts) static
getAccessedFieldNo - Given an encoded value and a result number, return the input field number being accessed.
Definition at line 642 of file CGExpr.cpp.
Referenced by EmitExtVectorElementLValue(), EmitLoadOfExtVectorElementLValue(), and EmitStoreThroughExtVectorComponentLValue().
GetAddressOfBaseClass()
Address CodeGenFunction::GetAddressOfBaseClass (Address Value, const CXXRecordDecl * Derived, CastExpr::path_const_iterator PathBegin, CastExpr::path_const_iterator PathEnd, bool NullCheckValue, SourceLocation Loc)
GetAddressOfBaseClass - This function will add the necessary delta to the load of 'this' and returns address of the base class.
Definition at line 293 of file CGClass.cpp.
References ApplyNonVirtualAndVirtualOffset(), Builder, CGM, clang::CodeGen::CodeGenModule::computeNonVirtualBaseClassOffset(), ConvertType(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateIsNull(), EmitBlock(), EmitTypeCheck(), clang::ASTContext::getASTRecordLayout(), clang::CodeGen::CodeGenModule::getClassPointerAlignment(), getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::RecordType::getDecl(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::ASTContext::getRecordType(), clang::Value::getType(), clang::ASTRecordLayout::getVBaseClassOffset(), clang::CodeGen::CGCXXABI::GetVirtualBaseClassOffset(), clang::Decl::hasAttr(), clang::CharUnits::isZero(), clang::CodeGen::NotKnownNonNull, sanitizePerformTypeCheck(), clang::SanitizerSet::set(), TCK_Upcast, and TCK_UpcastToVirtualBase.
Referenced by EmitCastLValue(), EmitMaterializeTemporaryExpr(), and EmitPointerWithAlignment().
GetAddressOfDerivedClass()
Address CodeGenFunction::GetAddressOfDerivedClass (Address Value, const CXXRecordDecl * Derived, CastExpr::path_const_iterator PathBegin, CastExpr::path_const_iterator PathEnd, bool NullCheckValue)
Definition at line 402 of file CGClass.cpp.
References Builder, CGM, ConvertType(), createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreateIsNull(), EmitBlock(), clang::CodeGen::Address::emitRawPointer(), clang::ASTContext::getCanonicalType(), clang::CodeGen::CodeGenModule::getClassPointerAlignment(), getContext(), clang::CodeGen::Address::getElementType(), clang::CodeGen::CodeGenModule::GetNonVirtualBaseClassOffset(), clang::Value::getType(), clang::CodeGen::CodeGenTypeCache::Int8Ty, IsNull, and clang::CodeGen::Address::withElementType().
Referenced by EmitCastLValue().
GetAddressOfDirectBaseInCompleteClass()
Address CodeGenFunction::GetAddressOfDirectBaseInCompleteClass (Address This, const CXXRecordDecl * Derived, const CXXRecordDecl * Base, bool BaseIsVirtual)
GetAddressOfBaseOfCompleteClass - Convert the given pointer to a complete class to the given direct base.
Gets the address of a direct base class within a complete object.
This should only be used for (1) non-virtual bases or (2) virtual bases when the type is known to be complete (e.g. in complete destructors).
The object pointed to by 'This' is assumed to be non-null.
Definition at line 222 of file CGClass.cpp.
References Builder, ConvertType(), clang::CodeGen::CGBuilderTy::CreateConstInBoundsByteGEP(), clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), getContext(), clang::ASTRecordLayout::getVBaseClassOffset(), clang::CodeGen::CodeGenTypeCache::Int8Ty, Offset, clang::interp::This(), and V.
Referenced by EmitBaseInitializer().
GetAddrOfBlockDecl()
Address CodeGenFunction::GetAddrOfBlockDecl (const VarDecl * var)
Definition at line 1217 of file CGBlocks.cpp.
References BlockInfo, Builder, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), emitBlockByrefAddress(), EmitLoadOfReference(), clang::CodeGen::CGBlockInfo::Capture::fieldType(), getBlockByrefInfo(), clang::CodeGen::CGBlockInfo::getCapture(), clang::CodeGen::CGBlockInfo::Capture::getIndex(), clang::NamedDecl::getName(), clang::CodeGen::CGBlockInfo::Capture::isConstant(), clang::VarDecl::isEscapingByref(), clang::VarDecl::isNonEscapingByref(), clang::Type::isReferenceType(), LoadBlockStruct(), and MakeAddrLValue().
Referenced by EmitDeclRefLValue(), and EmitLambdaBlockInvokeBody().
GetAddrOfLabel()
llvm::BlockAddress * CodeGenFunction::GetAddrOfLabel (const LabelDecl * L)
Definition at line 2413 of file CodeGenFunction.cpp.
References CurFn, clang::CodeGen::CodeGenFunction::JumpDest::getBlock(), GetIndirectGotoBlock(), and getJumpDestForLabel().
GetAddrOfLocalVar()
Address clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar (const VarDecl * VD) inline
GetAddrOfLocalVar - Return the address of a local variable.
Definition at line 2914 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CGObjCRuntime::canMessageReceiverBeNull(), EmitCfiCheckFail(), emitCmdValueForGetterSetterBody(), EmitDelegateCallArg(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), clang::CodeGen::CGObjCRuntime::EmitInitOfCatchParam(), emitInterWarpCopyFunction(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), EmitMemberInitializer(), EmitMustTailThunk(), EmitObjCMessageExpr(), EmitOMPAggregateReduction(), emitOutlinedFunctionPrologue(), emitPrivatesInit(), emitShuffleAndReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), GenerateCopyHelperFunction(), GenerateDestroyHelperFunction(), generateObjCSetterBody(), clang::CodeGen::CGOpenMPRuntime::getParameterAddress(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), clang::CodeGen::CGCXXABI::loadIncomingCXXThis(), mapParam(), and tryRemoveRetainOfSelf().
getARCCleanupKind()
CleanupKind clang::CodeGen::CodeGenFunction::getARCCleanupKind () inline
Retrieves the default cleanup kind for an ARC cleanup.
Except under -fobjc-arc-eh, ARC cleanups are normal-only.
Definition at line 4618 of file CodeGenFunction.h.
References CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::NormalAndEHCleanup, and clang::CodeGen::NormalCleanup.
Referenced by emitAutoVarTypeCleanup(), EmitAutoVarWithLifetime(), EmitObjCConsumeObject(), EmitParmDecl(), pushTemporaryCleanup(), and StartObjCMethod().
getArrayInitIndex()
llvm::Value* clang::CodeGen::CodeGenFunction::getArrayInitIndex () inline
Get the index of the current ArrayInitLoopExpr, if any.
Definition at line 2930 of file CodeGenFunction.h.
getAsNaturalPointerTo()
llvm::Value* clang::CodeGen::CodeGenFunction::getAsNaturalPointerTo (Address Addr, QualType PointeeType) inline
Definition at line 4348 of file CodeGenFunction.h.
References clang::CodeGen::Address::getBasePointer().
Referenced by EmitCall(), EmitCXXConstructorCall(), EmitDelegateCXXConstructorCall(), EmitInheritedCXXConstructorCall(), EmitLambdaBlockInvokeBody(), clang::CodeGen::CGCXXABI::EmitLoadOfMemberFunctionPointer(), and EmitSynthesizedCXXCopyCtorCall().
getBlockByrefInfo()
const BlockByrefInfo & CodeGenFunction::getBlockByrefInfo (const VarDecl * D)
BuildByrefInfo - This routine changes a __block variable declared as T x into:
struct { void *__isa; void *__forwarding; int32_t __flags; int32_t __size; void *__copy_helper; // only if needed void *__destroy_helper; // only if needed void *__byref_variable_layout;// only if needed char padding[X]; // only if needed T x; } x
void *__copy_helper;
void *__destroy_helper;
void *__byref_variable_layout;
Definition at line 2576 of file CGBlocks.cpp.
References clang::CharUnits::alignTo(), clang::ASTContext::BlockRequiresCopying(), clang::CodeGen::BlockByrefInfo::ByrefAlignment, CGM, ConvertTypeForMem(), clang::serialized_diags::create(), clang::CodeGen::BlockByrefInfo::FieldIndex, clang::CodeGen::BlockByrefInfo::FieldOffset, clang::CharUnits::fromQuantity(), getContext(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::ASTContext::getDeclAlign(), getLLVMContext(), clang::NamedDecl::getNameAsString(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), clang::CodeGen::CodeGenTypeCache::getPointerSize(), clang::CharUnits::getQuantity(), clang::ValueDecl::getType(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8Ty, max(), clang::Qualifiers::OCL_None, clang::CodeGen::CodeGenTypeCache::PointerSizeInBytes, clang::CodeGen::BlockByrefInfo::Type, and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
Referenced by EmitAutoVarAlloca(), emitBlockByrefAddress(), and GetAddrOfBlockDecl().
getBundlesForFunclet()
SmallVector< llvm::OperandBundleDef, 1 > CodeGenFunction::getBundlesForFunclet (llvm::Value * Callee)
Definition at line 4880 of file CGCall.cpp.
References CurrentFuncletPad.
Referenced by emitAutoreleasedReturnValueMarker(), EmitCall(), EmitNoreturnRuntimeCallOrInvoke(), and EmitSehScope().
getCleanupKind()
CleanupKind clang::CodeGen::CodeGenFunction::getCleanupKind (QualType::DestructionKind kind) inline
Definition at line 2224 of file CodeGenFunction.h.
References needsEHCleanup(), clang::CodeGen::NormalAndEHCleanup, and clang::CodeGen::NormalCleanup.
Referenced by EmitCompoundLiteralLValue(), emitCXXDestructMethod(), EnterDtorCleanups(), pushCaptureCleanup(), and pushDestroy().
getContext()
ASTContext& clang::CodeGen::CodeGenFunction::getContext () const inline
Definition at line 2114 of file CodeGenFunction.h.
References CGM, and clang::CodeGen::CodeGenModule::getContext().
Referenced by AddInitializerToStaticVarDecl(), BuildFunctionArgList(), clang::CodeGen::CGCXXABI::buildThisParam(), callCStructCopyAssignmentOperator(), callCStructCopyConstructor(), callCStructDefaultConstructor(), callCStructDestructor(), callCStructMoveAssignmentOperator(), callCStructMoveConstructor(), canEmitDelegateCallArgs(), canEmitSpuriousReferenceToVariable(), CanSkipVTablePointerInitialization(), castToBase(), castValueToType(), CheckAggExprForMemSetUse(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), CheckAtomicAlignment(), ConstantFoldsToSimpleInteger(), ConvertType(), createRuntimeShuffleFunction(), createTLSAtExitStub(), defaultInitNonTrivialCStructVar(), EmitAArch64TblBuiltinExpr(), emitAddrOfFieldStorage(), emitAddrOfZeroSizeField(), EmitAggregateCopy(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), emitAlignedClause(), EmitAndRegisterVariableArrayDimensions(), EmitArrayDelete(), emitArrayLength(), EmitArraySubscriptExpr(), emitArraySubscriptGEP(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicCmpXchgForMSIntrin(), EmitAtomicExpr(), EmitAtomicStore(), EmitAutoVarAlloca(), EmitAutoVarCleanups(), EmitAutoVarInit(), EmitBaseInitializer(), EmitBinaryAtomicPost(), EmitBlockCallExpr(), EmitBlockCopyAndAutorelease(), EmitBuiltinNewDeleteCall(), emitByrefStructureInit(), EmitCall(), EmitCallExprLValue(), EmitCastLValue(), EmitCfiCheckFail(), EmitCfiCheckStub(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), emitCmdValueForGetterSetterBody(), EmitCoawaitLValue(), EmitComplexPrePostIncDec(), EmitCountedByFieldExpr(), EmitCoyieldLValue(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), EmitCXXAggrConstructorCall(), EmitCXXConstructExpr(), EmitCXXConstructorCall(), EmitCXXDeleteExpr(), EmitCXXGlobalVarDeclInit(), EmitCXXMemberCallExpr(), EmitCXXMemberPointerCallExpr(), EmitCXXNewAllocSize(), EmitCXXNewExpr(), EmitCXXTypeidExpr(), EmitDecl(), EmitDeclDestroy(), EmitDeclInit(), EmitDeclInvariant(), EmitDeclRefLValue(), emitDeclTargetVarDeclLValue(), EmitDelegateCallArg(), EmitDeleteCall(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), emitDestroy(), EmitDirectCallee(), clang::CodeGen::CGOpenMPRuntime::emitForNext(), EmitFromMemory(), EmitFunctionDeclLValue(), EmitFunctionEpilog(), EmitFunctionProlog(), emitGlobalToListReduceFunction(), EmitGlobalVarDeclLValue(), EmitIgnoredExpr(), EmitInheritedCXXConstructorCall(), clang::CodeGen::ReductionCodeGen::emitInitialization(), EmitISOVolatileLoad(), EmitISOVolatileStore(), EmitIvarOffsetAsPointerDiff(), EmitLambdaBlockInvokeBody(), EmitLambdaInAllocaCallOpBody(), EmitLambdaStaticInvokeBody(), emitListToGlobalReduceFunction(), clang::CodeGen::CGCXXABI::EmitLoadOfMemberFunctionPointer(), EmitLoadOfScalar(), EmitLValueForField(), EmitLValueForLambdaField(), emitMappingInformation(), EmitMemberExpr(), EmitMemberInitializer(), EmitNewArrayInitializer(), emitNonZeroVLAInit(), EmitNullBaseClassInitialization(), EmitNullInitialization(), EmitObjCBoxedExpr(), EmitObjCIvarRefLValue(), EmitObjCMRRAutoreleasePoolPop(), EmitObjCMRRAutoreleasePoolPush(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), EmitOMPArraySectionExpr(), EmitOMPUseDeviceAddrClause(), EmitOMPUseDevicePtrClause(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), EmitParmDecl(), emitPartialArrayDestroy(), emitPointerArithmetic(), emitPrivatesInit(), EmitSEHExceptionCodeSave(), EmitStaticVarDecl(), EmitStoreOfScalar(), emitStructSetterCall(), EmitSYCLAnnotationCall(), EmitSynthesizedCXXCopyCtor(), emitTargetTeamsLoopCodegenStatus(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitThreadIDAddress(), EmitToMemory(), EmitUnaryOpLValue(), clang::CodeGen::CGOpenMPRuntime::emitUpdateLocation(), clang::CodeGen::EmitVAArgInstr(), EmitVAListRef(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), EmitVariablyModifiedType(), EmitVTablePtrCheck(), EmitVTableTypeCheckedLoad(), EmitX86_64VAArgFromMemory(), EmitX86BitTestIntrinsic(), EnterDtorCleanups(), EvaluateExprAsBool(), FinishFunction(), GenerateBlockFunction(), GenerateCopyHelperFunction(), GenerateCXXGlobalCleanUpFunc(), GenerateCXXGlobalInitFunc(), GenerateCXXGlobalVarDeclInitFunc(), generateDestroyHelper(), GenerateDestroyHelperFunction(), GenerateObjCAtomicGetterCopyHelperFunction(), GenerateObjCAtomicSetterCopyHelperFunction(), generateObjCGetterBody(), generateObjCSetterBody(), GenerateSEHFilterFunction(), GetAddressOfBaseClass(), GetAddressOfDerivedClass(), GetAddressOfDirectBaseInCompleteClass(), getArrayIndexingBound(), getBlockByrefInfo(), getCaptureFieldType(), getFieldOffsetInBits(), getIdentStringFromSourceLocation(), getItaniumDynamicCastFn(), GetNumNonZeroBytesInInit(), clang::CodeGen::CGOpenMPRuntime::getNumTeamsExprForTargetDirective(), getNumThreads(), clang::CodeGen::CGOpenMPRuntime::getNumThreadsExprForTargetDirective(), getOverlapForBaseInit(), getOverlapForFieldInit(), getPointerAndSize(), getRangeForType(), getUBSanFunctionTypeHash(), clang::CodeGen::getVAListElementType(), getVLAElements1D(), getVLASize(), getVTablePointers(), GetVTTParameter(), isCheapEnoughToEvaluateUnconditionally(), isSimpleZero(), LoadObjCSelf(), LoadPassedObjectSize(), loadToBegin(), LValueIsSuitableForInlineAtomic(), MakeAddrLValue(), MakeAddrLValueWithoutTBAA(), MakeAtomicCmpXchgValue(), MakeBinaryAtomicValue(), MakeRawAddrLValue(), maybeCreateMCDCCondBitmap(), performTypeAdjustment(), setBlockContextParameter(), ShouldEmitVTableTypeCheckedLoad(), shuffleAndStore(), StartFunction(), tryEmitAsConstant(), tryToConvertMemberExprToDeclRefExpr(), and TypeOfSelfObject().
getCurrentBuiltinID()
unsigned clang::CodeGen::CodeGenFunction::getCurrentBuiltinID () const inline
Definition at line 1717 of file CodeGenFunction.h.
getCurrentProfileCount()
uint64_t clang::CodeGen::CodeGenFunction::getCurrentProfileCount () inline
Get the profiler's current count.
This is generally the count for the most recently incremented counter.
Definition at line 1653 of file CodeGenFunction.h.
Referenced by EmitBranchOnBoolExpr().
getDebugInfo()
CGDebugInfo* clang::CodeGen::CodeGenFunction::getDebugInfo () inline
Definition at line 2115 of file CodeGenFunction.h.
Referenced by clang::CodeGen::ApplyDebugLocation::ApplyDebugLocation(), clang::CodeGen::ApplyInlineDebugLocation::ApplyInlineDebugLocation(), emitArraySubscriptGEP(), EmitAutoVarAlloca(), EmitCall(), EmitCXXNewExpr(), EmitDecl(), EmitDeclRefExprDbgValue(), EmitLabel(), EmitLValueForField(), EmitParmDecl(), emitPreserveStructAccess(), EmitStaticVarDecl(), FinishFunction(), GenerateBlockFunction(), IsPreserveAIArrayBase(), clang::CodeGen::CodeGenFunction::LexicalScope::LexicalScope(), setBlockContextParameter(), SourceLocToDebugLoc(), StartFunction(), clang::CodeGen::ApplyInlineDebugLocation::~ApplyInlineDebugLocation(), and clang::CodeGen::CodeGenFunction::LexicalScope::~LexicalScope().
getDebugInfoFIndex()
unsigned CodeGenFunction::getDebugInfoFIndex (const RecordDecl * Rec, unsigned FieldIndex)
Get the record field index as represented in debug info.
Get the field index in the debug info.
The debug info structure/union will ignore the unnamed bitfields.
Definition at line 4736 of file CGExpr.cpp.
References clang::RecordDecl::fields(), and clang::RecordDecl::getDefinition().
Referenced by EmitLValueForField(), and emitPreserveStructAccess().
getDestroyer()
CodeGenFunction::Destroyer * CodeGenFunction::getDestroyer (QualType::DestructionKind destructionKind)
Definition at line 2215 of file CGDecl.cpp.
References destroyARCStrongPrecise, destroyARCWeak, destroyCXXObject, destroyNonTrivialCStruct, clang::QualType::DK_cxx_destructor, clang::QualType::DK_none, clang::QualType::DK_nontrivial_c_struct, clang::QualType::DK_objc_strong_lifetime, and clang::QualType::DK_objc_weak_lifetime.
Referenced by EmitArrayDelete(), emitAutoVarTypeCleanup(), EmitCompoundLiteralLValue(), emitCXXDestructMethod(), EmitDeclDestroy(), EmitNewArrayInitializer(), EnterDtorCleanups(), pushCaptureCleanup(), pushDestroy(), and pushEHDestroy().
getEHDispatchBlock()
llvm::BasicBlock * CodeGenFunction::getEHDispatchBlock (EHScopeStack::stable_iterator scope)
Definition at line 673 of file CGException.cpp.
References clang::CodeGen::EHCatchScope::Handler::Block, clang::CodeGen::EHScope::Catch, clang::CodeGen::EHScope::Cleanup, createBasicBlock(), EHStack, clang::CodeGen::EHScope::Filter, clang::CodeGen::EHScopeStack::find(), clang::CodeGen::EHPersonality::get(), clang::CodeGen::EHScope::getCachedEHDispatchBlock(), getEHResumeBlock(), getFuncletEHDispatchBlock(), clang::CodeGen::EHCatchScope::getHandler(), clang::CodeGen::EHScope::getKind(), clang::CodeGen::EHCatchScope::getNumHandlers(), getTerminateHandler(), clang::CodeGen::EHCatchScope::Handler::isCatchAll(), clang::CodeGen::EHScope::setCachedEHDispatchBlock(), clang::CodeGen::EHScopeStack::stable_end(), clang::CodeGen::EHScope::Terminate, and clang::CodeGen::EHPersonality::usesFuncletPads().
Referenced by emitCatchDispatchBlock(), emitCatchPadBlock(), EmitLandingPad(), emitWasmCatchPadBlock(), and getInvokeDestImpl().
getEHResumeBlock()
llvm::BasicBlock * CodeGenFunction::getEHResumeBlock (bool isCleanup)
Definition at line 1625 of file CGException.cpp.
References Builder, clang::CodeGen::EHPersonality::CatchallRethrowFn, CGM, createBasicBlock(), EHResumeBlock, EmitRuntimeCall(), clang::CodeGen::EHPersonality::get(), getCatchallRethrowFn(), getExceptionFromSlot(), and getSelectorFromSlot().
Referenced by emitFilterDispatchBlock(), and getEHDispatchBlock().
getEHSelectorSlot()
Address CodeGenFunction::getEHSelectorSlot ()
Definition at line 429 of file CGException.cpp.
References CreateTempAlloca(), EHSelectorSlot, clang::CharUnits::fromQuantity(), and clang::CodeGen::CodeGenTypeCache::Int32Ty.
Referenced by EmitLandingPad(), and getSelectorFromSlot().
getEltType()
llvm::Type * CodeGenFunction::getEltType (const SVETypeFlags & TypeFlags)
Definition at line 9710 of file CGBuiltin.cpp.
References clang::SVETypeFlags::getEltType().
getEvaluationKind()
TypeEvaluationKind CodeGenFunction::getEvaluationKind (QualType T) static
getEvaluationKind - Return the TypeEvaluationKind of QualType T.
Definition at line 236 of file CodeGenFunction.cpp.
References clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, clang::CodeGen::TEK_Scalar, and clang::ast_matchers::type.
Referenced by convertTempToRValue(), convertToComplexValue(), convertToType(), EmitAnyExpr(), EmitAnyExprToMem(), EmitBinaryOperatorLValue(), EmitCall(), EmitDeclInit(), EmitExprAsInit(), EmitFunctionEpilog(), emitGlobalToListCopyFunction(), EmitInitializerForField(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), emitListToGlobalCopyFunction(), EmitMaterializeTemporaryExpr(), emitOMPSimpleStore(), EmitRValueForField(), generateObjCGetterBody(), GetUndefRValue(), hasAggregateEvaluationKind(), hasScalarEvaluationKind(), InitCatchParam(), and StoreAnyExprIntoOneUnit().
getExceptionFromSlot()
llvm::Value * CodeGenFunction::getExceptionFromSlot ()
Returns the contents of the function's exception object and selector slots.
Definition at line 435 of file CGException.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateLoad(), and getExceptionSlot().
Referenced by emitFilterDispatchBlock(), clang::CodeGen::CodeGenFunction::FinallyInfo::exit(), getEHResumeBlock(), getTerminateHandler(), and InitCatchParam().
getExceptionSlot()
Address CodeGenFunction::getExceptionSlot ()
Returns a pointer to the function's exception object and selector slot, which is assigned in every landing pad.
Definition at line 423 of file CGException.cpp.
References CreateTempAlloca(), ExceptionSlot, clang::CodeGen::CodeGenTypeCache::getPointerAlign(), and clang::CodeGen::CodeGenTypeCache::Int8PtrTy.
Referenced by EmitLandingPad(), emitWasmCatchPadBlock(), and getExceptionFromSlot().
getFuncletEHDispatchBlock()
llvm::BasicBlock * CodeGenFunction::getFuncletEHDispatchBlock (EHScopeStack::stable_iterator scope)
Definition at line 720 of file CGException.cpp.
References Builder, clang::CodeGen::EHScope::Catch, clang::CodeGen::EHScope::Cleanup, createBasicBlock(), EHStack, clang::CodeGen::EHScope::Filter, clang::CodeGen::EHScopeStack::find(), clang::CodeGen::EHScope::getCachedEHDispatchBlock(), clang::CodeGen::EHScope::getKind(), getTerminateFunclet(), clang::CodeGen::EHScope::setCachedEHDispatchBlock(), clang::CodeGen::EHScopeStack::stable_end(), and clang::CodeGen::EHScope::Terminate.
Referenced by getEHDispatchBlock().
GetIndirectGotoBlock()
llvm::BasicBlock * CodeGenFunction::GetIndirectGotoBlock ()
Definition at line 2425 of file CodeGenFunction.cpp.
References createBasicBlock(), and clang::CodeGen::CodeGenTypeCache::Int8PtrTy.
Referenced by GetAddrOfLabel().
getInvokeDest()
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::getInvokeDest () inline
Definition at line 2149 of file CodeGenFunction.h.
References EHStack, getInvokeDestImpl(), and clang::CodeGen::EHScopeStack::requiresLandingPad().
Referenced by EmitCall(), EmitNoreturnRuntimeCallOrInvoke(), EmitObjCAutoreleasePoolPop(), and EmitSehScope().
getInvokeDestImpl()
llvm::BasicBlock * CodeGenFunction::getInvokeDestImpl ()
Definition at line 775 of file CGException.cpp.
References clang::CodeGen::EHScopeStack::begin(), CGM, CurFn, currentFunctionUsesSEHTry(), EHStack, EmitLandingPad(), clang::CodeGen::EHScopeStack::empty(), clang::CodeGen::EHPersonality::get(), clang::CodeGen::EHScope::getCachedLandingPad(), getEHDispatchBlock(), clang::CodeGen::EHScopeStack::getInnermostEHScope(), clang::CodeGen::CodeGenModule::getLangOpts(), getOpaquePersonalityFn(), isNonEHScope(), clang::CodeGen::EHScopeStack::requiresLandingPad(), and clang::CodeGen::EHPersonality::usesFuncletPads().
Referenced by getInvokeDest().
getJumpDestForLabel()
CodeGenFunction::JumpDest CodeGenFunction::getJumpDestForLabel (const LabelDecl * S)
getBasicBlockForLabel - Return the LLVM basicblock that the specified label maps to.
Definition at line 632 of file CGStmt.cpp.
References createBasicBlock(), clang::NamedDecl::getName(), clang::CodeGen::EHScopeStack::stable_iterator::invalid(), clang::CodeGen::CodeGenFunction::JumpDest::isValid(), and NextCleanupDestIndex.
Referenced by GetAddrOfLabel().
getJumpDestInCurrentScope() [1/2]
JumpDest clang::CodeGen::CodeGenFunction::getJumpDestInCurrentScope (llvm::BasicBlock * Target) inline
The given basic block lies in the current EH scope, but may be a target of a potentially scope-crossing jump; get a stable handle to which we can perform this jump later.
Definition at line 1204 of file CodeGenFunction.h.
References EHStack, clang::CodeGen::EHScopeStack::getInnermostNormalCleanup(), and NextCleanupDestIndex.
Referenced by EmitLabel(), clang::CodeGen::CodeGenFunction::FinallyInfo::enter(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::FinalizeOMPRegion(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::InlinedRegionBodyRAII::InlinedRegionBodyRAII(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OutlinedRegionBodyRAII::OutlinedRegionBodyRAII(), and StartFunction().
getJumpDestInCurrentScope() [2/2]
JumpDest clang::CodeGen::CodeGenFunction::getJumpDestInCurrentScope (StringRef Name = StringRef()) inline
The given basic block lies in the current EH scope, but may be a target of a potentially scope-crossing jump; get a stable handle to which we can perform this jump later.
Definition at line 1213 of file CodeGenFunction.h.
getLangOpts()
const LangOptions& clang::CodeGen::CodeGenFunction::getLangOpts () const inline
Definition at line 2127 of file CodeGenFunction.h.
References CGM, and clang::CodeGen::CodeGenModule::getLangOpts().
Referenced by AddInitializerToStaticVarDecl(), canEmitSpuriousReferenceToVariable(), clang::CodeGen::CodeGenFunction::CGFPOptionsRAII::CGFPOptionsRAII(), CheckAggExprForMemSetUse(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), checkIfFunctionMustProgress(), checkIfLoopMustProgress(), checkTargetFeatures(), EmitAggregateCopy(), EmitArraySubscriptExpr(), EmitAutoVarAlloca(), EmitAutoVarCleanups(), EmitBinaryOperatorLValue(), EmitBlockCallExpr(), EmitCall(), EmitCallArg(), EmitCastLValue(), EmitComplexAssignmentLValue(), EmitComplexPrePostIncDec(), EmitCompoundLiteralLValue(), EmitCXXAggrConstructorCall(), EmitCXXConstructExpr(), EmitCXXGlobalVarDeclInit(), EmitCXXMemberOrOperatorMemberCallExpr(), EmitDeclRefLValue(), EmitDelegateCallArg(), EmitDestructorBody(), EmitEndEHSpec(), EmitForwardingCallToLambda(), EmitFunctionEpilog(), EmitGlobalVarDeclLValue(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalFinalUpdate(), EmitLoadOfExtVectorElementLValue(), EmitLoadOfLValue(), EmitLValueForField(), EmitMemberExpr(), EmitNullInitialization(), clang::CodeGen::CGOpenMPRuntime::emitNumTeamsForTargetDirective(), EmitObjCMessageExpr(), EmitObjCThrowOperand(), EmitOMPArraySectionExpr(), EmitParmDecl(), emitPointerArithmetic(), EmitStartEHSpec(), EmitStaticVarDecl(), EmitTargetArchBuiltinExpr(), EmitUnaryOpLValue(), EmitVTablePtrCheckForCast(), FinishFunction(), GenerateBlockFunction(), GenerateCode(), GenerateCXXGlobalInitFunc(), GenerateCXXGlobalVarDeclInitFunc(), GenerateObjCAtomicGetterCopyHelperFunction(), GenerateObjCAtomicSetterCopyHelperFunction(), generateObjCGetterBody(), clang::CodeGen::CGOpenMPRuntime::getNumThreadsExprForTargetDirective(), getRangeForType(), getTerminateHandler(), getTerminateLandingPad(), clang::CodeGen::CGOpenMPRuntime::getThreadID(), initializeAlloca(), needsEHCleanup(), pushCaptureCleanup(), pushTemporaryCleanup(), setBlockContextParameter(), SetDivFPAccuracy(), SetSqrtFPAccuracy(), StartFunction(), tryEmitARCRetainLoadOfScalar(), tryEmitSpecializedAllocInit(), and ~CodeGenFunction().
getLLVMContext()
llvm::LLVMContext& clang::CodeGen::CodeGenFunction::getLLVMContext () inline
Definition at line 2157 of file CodeGenFunction.h.
References CGM, and clang::CodeGen::CodeGenModule::getLLVMContext().
Referenced by createBasicBlock(), clang::CodeGen::TargetCodeGenInfo::createEnqueuedBlockKernel(), createPlaceholderSlot(), emitAlignedClause(), EmitAtomicCmpXchg128ForMSIntrin(), EmitAtomicExpr(), emitAtomicLibcall(), emitAutoreleasedReturnValueMarker(), EmitBinaryAtomicPost(), EmitBranchOnBoolExpr(), EmitCall(), emitCatchPadBlock(), EmitCfiSlowPathCheck(), EmitCheck(), emitCheckHandlerCall(), EmitCheckValue(), EmitComplexPrePostIncDec(), EmitCXXConstructorCall(), EmitCXXGlobalVarDeclInit(), EmitCXXTypeidExpr(), EmitExtVectorElementExpr(), EmitFunctionProlog(), EmitISOVolatileLoad(), EmitLoadOfScalar(), EmitLValueForField(), clang::CodeGen::CGCXXABI::EmitMemberDataPointerAddress(), EmitParmDecl(), emitPPCLoadReserveIntrinsic(), emitRangedBuiltin(), EmitScalarRangeCheck(), EmitSEHExceptionCodeSave(), EmitTrapCall(), EmitTrapCheck(), EmitTypeCheck(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), clang::CodeGen::emitVoidPtrVAArg(), EmitVTablePtrCheck(), emitWasmCatchPadBlock(), EmitX86BitTestIntrinsic(), EmitX86CvtF16ToFloatExpr(), FinishFunction(), generateObjCGetterBody(), generateObjCSetterBody(), generateThunk(), getBlockByrefInfo(), getItaniumDynamicCastFn(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), getUnreachableBlock(), InitCatchParam(), MakeAtomicCmpXchgValue(), MakeBinaryAtomicValue(), setBlockContextParameter(), SetFPAccuracy(), and StartFunction().
getNonTrivialCopyConstructorStr()
std::string CodeGenFunction::getNonTrivialCopyConstructorStr (QualType QT, CharUnits Alignment, bool IsVolatile, ASTContext & Ctx) static
Definition at line 853 of file CGNonTrivialStruct.cpp.
Referenced by getBlockCaptureStr().
getNonTrivialDestructorStr()
std::string CodeGenFunction::getNonTrivialDestructorStr (QualType QT, CharUnits Alignment, bool IsVolatile, ASTContext & Ctx) static
Definition at line 859 of file CGNonTrivialStruct.cpp.
Referenced by getBlockCaptureStr().
getNormalCleanupDestSlot()
RawAddress CodeGenFunction::getNormalCleanupDestSlot ()
Definition at line 1296 of file CGCleanup.cpp.
Referenced by ResolveAllBranchFixups(), and TransitionToCleanupSwitch().
getOMPCancelDestination()
CodeGenFunction::JumpDest CodeGenFunction::getOMPCancelDestination (OpenMPDirectiveKind Kind)
Definition at line 7234 of file CGStmtOpenMP.cpp.
References ReturnBlock.
getOrCreateOpaqueLValueMapping()
LValue CodeGenFunction::getOrCreateOpaqueLValueMapping (const OpaqueValueExpr * e)
Given an opaque value expression, return its LValue mapping if it exists, otherwise create one.
Definition at line 5404 of file CGExpr.cpp.
References EmitLValue(), clang::OpaqueValueExpr::getSourceExpr(), clang::OpaqueValueExpr::isUnique(), and clang::CodeGen::CodeGenFunction::OpaqueValueMapping::shouldBindAsLValue().
Referenced by EmitOpaqueValueLValue().
getOrCreateOpaqueRValueMapping()
RValue CodeGenFunction::getOrCreateOpaqueRValueMapping (const OpaqueValueExpr * e)
Given an opaque value expression, return its RValue mapping if it exists, otherwise create one.
Definition at line 5418 of file CGExpr.cpp.
References EmitAnyExpr(), clang::OpaqueValueExpr::getSourceExpr(), clang::OpaqueValueExpr::isUnique(), and clang::CodeGen::CodeGenFunction::OpaqueValueMapping::shouldBindAsLValue().
getOverlapForBaseInit()
AggValueSlot::Overlap_t CodeGenFunction::getOverlapForBaseInit (const CXXRecordDecl * RD, const CXXRecordDecl * BaseRD, bool IsVirtual)
Determine whether a base class initialization may overlap some other object.
Definition at line 2105 of file CGExprAgg.cpp.
References clang::CodeGen::AggValueSlot::DoesNotOverlap, clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), getContext(), clang::ASTRecordLayout::getNonVirtualSize(), and clang::CodeGen::AggValueSlot::MayOverlap.
Referenced by EmitBaseInitializer().
getOverlapForFieldInit()
AggValueSlot::Overlap_t CodeGenFunction::getOverlapForFieldInit (const FieldDecl * FD)
Determine whether a field initialization may overlap some other object.
Definition at line 2087 of file CGExprAgg.cpp.
References clang::CodeGen::AggValueSlot::DoesNotOverlap, clang::ASTContext::getASTRecordLayout(), getContext(), clang::FieldDecl::getFieldIndex(), clang::ASTRecordLayout::getFieldOffset(), clang::ASTRecordLayout::getNonVirtualSize(), clang::FieldDecl::getParent(), clang::ValueDecl::getType(), getTypeSize(), clang::Decl::hasAttr(), clang::Type::isRecordType(), and clang::CodeGen::AggValueSlot::MayOverlap.
Referenced by EmitExprAsInit(), EmitInitializerForField(), and EmitMemberInitializer().
getOverlapForReturnValue()
AggValueSlot::Overlap_t clang::CodeGen::CodeGenFunction::getOverlapForReturnValue () inline
Determine whether a return value slot may overlap some other object.
Definition at line 2875 of file CodeGenFunction.h.
References clang::CodeGen::AggValueSlot::DoesNotOverlap.
Referenced by generateObjCGetterBody().
getPostAllocaInsertPoint()
llvm::Instruction* clang::CodeGen::CodeGenFunction::getPostAllocaInsertPoint () inline
Return PostAllocaInsertPt.
If it is not yet created, then insert it immediately after AllocaInsertPt.
Definition at line 443 of file CodeGenFunction.h.
References AllocaInsertPt.
getProfileCount()
uint64_t clang::CodeGen::CodeGenFunction::getProfileCount (const Stmt * S) inline
Get the profiler's count for the given statement.
Definition at line 1642 of file CodeGenFunction.h.
Referenced by EmitBranchOnBoolExpr().
getSelectorFromSlot()
llvm::Value * CodeGenFunction::getSelectorFromSlot ()
Definition at line 439 of file CGException.cpp.
References Builder, clang::CodeGen::CGBuilderTy::CreateLoad(), and getEHSelectorSlot().
Referenced by emitCatchDispatchBlock(), emitFilterDispatchBlock(), and getEHResumeBlock().
getSVEOverloadTypes()
SmallVector< llvm::Type *, 2 > CodeGenFunction::getSVEOverloadTypes (const SVETypeFlags & TypeFlags, llvm::Type * ReturnType, ArrayRef< llvm::Value * > Ops)
Definition at line 10348 of file CGBuiltin.cpp.
References clang::SVETypeFlags::isOverloadCvt(), clang::SVETypeFlags::isOverloadDefault(), clang::SVETypeFlags::isOverloadNone(), clang::SVETypeFlags::isOverloadWhileOrMultiVecCvt(), clang::SVETypeFlags::isOverloadWhileRW(), and clang::SVETypeFlags::isReductionQV().
getSVEPredType()
llvm::ScalableVectorType * CodeGenFunction::getSVEPredType (const SVETypeFlags & TypeFlags)
Definition at line 9747 of file CGBuiltin.cpp.
References clang::SVETypeFlags::getEltType().
getSVEType()
llvm::ScalableVectorType * CodeGenFunction::getSVEType (const SVETypeFlags & TypeFlags)
Definition at line 9782 of file CGBuiltin.cpp.
References clang::SVETypeFlags::getEltType().
getTarget()
const TargetInfo& clang::CodeGen::CodeGenFunction::getTarget () const inline
Definition at line 2156 of file CodeGenFunction.h.
References Target.
Referenced by canEmitDelegateCallArgs(), EmitAMDGPUDevicePrintfCallExpr(), EmitAtomicExpr(), EmitAutoVarAlloca(), EmitBitTestIntrinsic(), EmitCall(), EmitDestructorBody(), EmitEndEHSpec(), EmitFunctionProlog(), emitGlobalDtorWithCXAAtExit(), emitInterWarpCopyFunction(), EmitNVPTXDevicePrintfCallExpr(), EmitOpenMPDevicePrintfCallExpr(), emitPPCLoadReserveIntrinsic(), EmitSignBit(), EmitStartEHSpec(), EmitTargetArchBuiltinExpr(), EmitX86BitTestIntrinsic(), GetNumNonZeroBytesInInit(), getNVPTXLaneID(), getNVPTXWarpID(), StartFunction(), and wrapWithBPFPreserveStaticOffset().
getTargetHooks()
const TargetCodeGenInfo& clang::CodeGen::CodeGenFunction::getTargetHooks () const inline
Definition at line 2158 of file CodeGenFunction.h.
References CGM, and clang::CodeGen::CodeGenModule::getTargetCodeGenInfo().
Referenced by EmitAggregateCopy(), EmitAtomicExpr(), EmitAtomicOp(), EmitCall(), EmitCastLValue(), emitCatchDispatchBlock(), EmitCXXConstructorCall(), EmitCXXDestructorCall(), EmitCXXTypeidExpr(), EmitDeclRefLValue(), clang::CodeGen::CGOpenCLRuntime::emitOpenCLEnqueuedBlock(), EmitParmDecl(), and tryUseTestFPKind().
getTerminateFunclet()
llvm::BasicBlock * CodeGenFunction::getTerminateFunclet ()
getTerminateLandingPad - Return a cleanup funclet that just calls terminate.
Definition at line 1590 of file CGException.cpp.
References Builder, CGM, createBasicBlock(), CurrentFuncletPad, clang::CodeGen::CGCXXABI::emitTerminateForUnexpectedException(), clang::CodeGen::EHPersonality::get(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::CodeGenModule::getLLVMContext(), and clang::CodeGen::EHPersonality::usesFuncletPads().
Referenced by getFuncletEHDispatchBlock().
getTerminateHandler()
llvm::BasicBlock * CodeGenFunction::getTerminateHandler ()
getTerminateHandler - Return a handler (not a landing pad, just a catch handler) that just calls terminate.
This is used when a terminate scope encloses a try.
Definition at line 1566 of file CGException.cpp.
References Builder, CGM, clang::CPlusPlus, createBasicBlock(), clang::CodeGen::CGCXXABI::emitTerminateForUnexpectedException(), clang::CodeGen::CodeGenModule::getCXXABI(), getExceptionFromSlot(), and getLangOpts().
Referenced by getEHDispatchBlock().
getTerminateLandingPad()
llvm::BasicBlock * CodeGenFunction::getTerminateLandingPad ()
getTerminateLandingPad - Return a landing pad that just calls terminate.
Definition at line 1532 of file CGException.cpp.
References Builder, CGM, clang::CPlusPlus, createBasicBlock(), CurFn, clang::CodeGen::CGCXXABI::emitTerminateForUnexpectedException(), clang::CodeGen::EHPersonality::get(), getCatchAllValue(), clang::CodeGen::CodeGenModule::getCXXABI(), getLangOpts(), getOpaquePersonalityFn(), clang::CodeGen::CodeGenTypeCache::Int32Ty, and clang::CodeGen::CodeGenTypeCache::Int8PtrTy.
Referenced by EmitLandingPad().
getTypes()
CodeGenTypes& clang::CodeGen::CodeGenFunction::getTypes () const inline
Definition at line 2113 of file CodeGenFunction.h.
References CGM, and clang::CodeGen::CodeGenModule::getTypes().
Referenced by BuildFunctionArgList(), commonEmitCXXMemberOrOperatorCall(), EmitCall(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), EmitCXXConstructorCall(), EmitCXXGlobalVarDeclInit(), EmitDeclRefLValue(), EmitDeleteCall(), EmitFunctionProlog(), emitGlobalDtorWithCXAAtExit(), EmitGlobalVarDeclLValue(), EmitIvarOffsetAsPointerDiff(), emitStructSetterCall(), GenerateCXXGlobalCleanUpFunc(), GenerateCXXGlobalInitFunc(), GenerateCXXGlobalVarDeclInitFunc(), generateObjCGetterBody(), generateObjCSetterBody(), GetNumNonZeroBytesInInit(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), and isSimpleZero().
getTypeSize()
llvm::Value * CodeGenFunction::getTypeSize (QualType Ty)
Returns calculated size of the specified type.
Definition at line 310 of file CGStmtOpenMP.cpp.
References clang::CodeGen::CodeGenFunction::VlaSizePair::Type.
Referenced by clang::CodeGen::ReductionCodeGen::emitAggregateType(), EmitCheckTypeDescriptor(), EmitCXXNewExpr(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElements(), EmitFromMemory(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), emitTargetCallKernelLaunch(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), EmitToMemory(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntimeGPU::getKmpcAllocShared(), getOverlapForFieldInit(), getPointerAndSize(), and LValueIsSuitableForInlineAtomic().
getUBSanFunctionTypeHash()
llvm::ConstantInt * CodeGenFunction::getUBSanFunctionTypeHash (QualType T) const
Return a type hash constant for a function instrumented by -fsanitize=function.
Definition at line 590 of file CodeGenFunction.cpp.
References CGM, clang::EST_None, getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::ASTContext::getFunctionTypeWithExceptionSpec(), clang::CodeGen::CGCXXABI::getMangleContext(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::Type::isFunctionNoProtoType(), and clang::MangleContext::mangleCanonicalTypeName().
Referenced by EmitCall(), and StartFunction().
GetUndefRValue()
RValue CodeGenFunction::GetUndefRValue (QualType Ty)
GetUndefRValue - Get an appropriate 'undef' rvalue for the given type.
Definition at line 1398 of file CGExpr.cpp.
References clang::Type::castAs(), ConvertType(), CreateMemTemp(), clang::CodeGen::RValue::get(), clang::CodeGen::RValue::getAggregate(), clang::CodeGen::RValue::getComplex(), clang::ComplexType::getElementType(), getEvaluationKind(), clang::Type::isVoidType(), clang::CodeGen::TEK_Aggregate, clang::CodeGen::TEK_Complex, and clang::CodeGen::TEK_Scalar.
Referenced by EmitCall().
getUnreachableBlock()
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::getUnreachableBlock () inline
Definition at line 2141 of file CodeGenFunction.h.
References createBasicBlock(), and getLLVMContext().
Referenced by destroyOptimisticNormalEntry(), EmitNoreturnRuntimeCallOrInvoke(), and clang::CodeGen::CodeGenFunction::FinallyInfo::enter().
getVLAElements1D() [1/2]
CodeGenFunction::VlaSizePair CodeGenFunction::getVLAElements1D (const VariableArrayType * vla)
Return the number of elements for a single dimension for the given array type.
Definition at line 2570 of file CodeGenFunction.cpp.
References clang::ArrayType::getElementType(), clang::VariableArrayType::getSizeExpr(), and clang::CodeGen::CodeGenTypeCache::SizeTy.
Referenced by EmitAndRegisterVariableArrayDimensions(), and getVLAElements1D().
getVLAElements1D() [2/2]
CodeGenFunction::VlaSizePair CodeGenFunction::getVLAElements1D (QualType vla)
Definition at line 2563 of file CodeGenFunction.cpp.
References clang::ASTContext::getAsVariableArrayType(), getContext(), getVLAElements1D(), and clang::ast_matchers::type.
getVLASize() [1/2]
CodeGenFunction::VlaSizePair CodeGenFunction::getVLASize (const VariableArrayType * vla)
Returns an LLVM value that corresponds to the size, in non-variably-sized elements, of a variable length array type, plus that largest non-variably-sized element type.
Assumes that the type has already been emitted with EmitVariablyModifiedType.
Definition at line 2539 of file CodeGenFunction.cpp.
References Builder, getContext(), clang::CodeGen::CodeGenTypeCache::SizeTy, and clang::ast_matchers::type.
Referenced by emitArrayLength(), EmitArraySubscriptExpr(), emitGlobalToListReduceFunction(), emitListToGlobalReduceFunction(), EmitNullInitialization(), EmitOMPArraySectionExpr(), emitPointerArithmetic(), getArrayIndexingBound(), and getVLASize().
getVLASize() [2/2]
CodeGenFunction::VlaSizePair CodeGenFunction::getVLASize (QualType vla)
Definition at line 2532 of file CodeGenFunction.cpp.
References clang::ASTContext::getAsVariableArrayType(), getContext(), getVLASize(), and clang::ast_matchers::type.
getVTablePointers() [1/2]
void CodeGenFunction::getVTablePointers (BaseSubobject Base, const CXXRecordDecl * NearestVBase, CharUnits OffsetFromNearestVBase, bool BaseIsNonVirtualPrimaryBase, const CXXRecordDecl * VTableClass, VisitedVirtualBasesSetTy & VBases, VPtrsVector & vptrs)
Definition at line 2617 of file CGClass.cpp.
References clang::CXXRecordDecl::bases(), clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), getContext(), clang::RecordType::getDecl(), clang::ASTRecordLayout::getPrimaryBase(), clang::ASTRecordLayout::getVBaseClassOffset(), getVTablePointers(), and clang::CharUnits::Zero().
getVTablePointers() [2/2]
CodeGenFunction::VPtrsVector CodeGenFunction::getVTablePointers (const CXXRecordDecl * VTableClass)
Definition at line 2606 of file CGClass.cpp.
References clang::CharUnits::Zero().
Referenced by EmitVTableAssumptionLoads(), getVTablePointers(), and InitializeVTablePointers().
GetVTablePtr()
llvm::Value * CodeGenFunction::GetVTablePtr (Address This, llvm::Type * VTableTy, const CXXRecordDecl * VTableClass)
GetVTablePtr - Return the Value of the vtable pointer member pointed to by This.
Definition at line 2688 of file CGClass.cpp.
References Builder, CGM, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::CodeGen::CodeGenModule::DecorateInstructionWithInvariantGroup(), clang::CodeGen::CodeGenModule::DecorateInstructionWithTBAA(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getTBAAVTablePtrAccessInfo(), and clang::interp::This().
Referenced by EmitVTableAssumptionLoad().
GetVTTParameter()
llvm::Value * CodeGenFunction::GetVTTParameter (GlobalDecl GD, bool ForVirtualBase, bool Delegating)
GetVTTParameter - Return the VTT parameter that should be passed to a base constructor/destructor with virtual bases.
FIXME: VTTs are Itanium ABI-specific, so the definition should move to ItaniumCXXABI.cpp together with all the references to VTT.
Definition at line 462 of file CGClass.cpp.
References Builder, CGM, CurCodeDecl, CurGD, clang::Delegating, clang::CodeGen::CodeGenVTables::GetAddrOfVTT(), clang::ASTContext::getASTRecordLayout(), clang::ASTRecordLayout::getBaseClassOffset(), getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::GlobalDecl::getDecl(), clang::DeclContext::getParent(), clang::CodeGen::CodeGenVTables::getSubVTTIndex(), clang::ASTRecordLayout::getVBaseClassOffset(), clang::CodeGen::CodeGenModule::getVTables(), LoadCXXVTT(), clang::CodeGen::CGCXXABI::NeedsVTTParameter(), and clang::CodeGen::CodeGenTypeCache::VoidPtrTy.
hasAggregateEvaluationKind()
static bool clang::CodeGen::CodeGenFunction::hasAggregateEvaluationKind (QualType T) inline static
Definition at line 2561 of file CodeGenFunction.h.
References getEvaluationKind(), clang::T, and clang::CodeGen::TEK_Aggregate.
Referenced by EmitAggExpr(), EmitAggExprToLValue(), EmitAnyExprToTemp(), EmitCallAndReturnForThunk(), EmitCallArg(), EmitConditionalOperatorLValue(), EmitFunctionEpilog(), EmitIgnoredConditionalOperator(), emitPseudoObjectExpr(), clang::CodeGen::CGCXXABI::EmitReturnFromThunk(), and clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::shouldBindAsLValue().
hasLabelBeenSeenInCurrentScope()
bool clang::CodeGen::CodeGenFunction::hasLabelBeenSeenInCurrentScope () const inline
Return true if a label was seen in the current scope.
Definition at line 419 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::LexicalScope::hasLabels().
Referenced by EmitAutoVarAlloca().
hasScalarEvaluationKind()
static bool clang::CodeGen::CodeGenFunction::hasScalarEvaluationKind (QualType T) inline static
Definition at line 2557 of file CodeGenFunction.h.
References getEvaluationKind(), clang::T, and clang::CodeGen::TEK_Scalar.
Referenced by convertToScalarValue(), EmitComplexToScalarConversion(), EmitForwardingCallToLambda(), EmitFunctionProlog(), EmitParmDecl(), EmitScalarConversion(), EmitScalarExpr(), clang::CodeGen::isAggregateTypeForABI(), and StartFunction().
hasVolatileMember()
bool clang::CodeGen::CodeGenFunction::hasVolatileMember (QualType T) inline
hasVolatileMember - returns true if aggregate type has a volatile member.
Definition at line 2866 of file CodeGenFunction.h.
References clang::Type::getAs(), clang::RecordDecl::hasVolatileMember(), and clang::T.
Referenced by EmitAggregateAssign(), and LValueIsSuitableForInlineAtomic().
HaveInsertPoint()
bool clang::CodeGen::CodeGenFunction::HaveInsertPoint () const inline
HaveInsertPoint - True if an insertion point is defined.
If not, this indicates that the current code being emitted is unreachable.
Definition at line 2607 of file CodeGenFunction.h.
References Builder.
Referenced by AddInitializerToStaticVarDecl(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OMPAllocateCleanupTy::Emit(), emitAlignedClause(), EmitAutoVarAlloca(), EmitAutoVarCleanups(), EmitAutoVarInit(), clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitBarrierCall(), EmitCall(), clang::CodeGen::CGOpenMPRuntime::emitCancelCall(), clang::CodeGen::CGOpenMPRuntime::emitCancellationPointCall(), EmitCleanup(), clang::CodeGen::CGOpenMPRuntime::emitCriticalRegion(), EmitDestructorBody(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), clang::CodeGen::CGOpenMPRuntime::emitFlush(), clang::CodeGen::CGOpenMPRuntime::emitForDispatchInit(), clang::CodeGen::CGOpenMPRuntime::emitForOrderedIterationEnd(), clang::CodeGen::CGOpenMPRuntime::emitForStaticFinish(), emitForStaticInitCall(), clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), clang::CodeGen::CGOpenMPRuntime::emitMaskedRegion(), clang::CodeGen::CGOpenMPRuntime::emitMasterRegion(), clang::CodeGen::CGOpenMPRuntime::emitNumTeamsClause(), clang::CodeGen::CGOpenMPRuntime::emitNumThreadsClause(), clang::CodeGen::CGOpenMPRuntime::emitOrderedRegion(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), emitPostUpdateForReductionClause(), clang::CodeGen::CGOpenMPRuntime::emitProcBindClause(), emitSimdlenSafelenClause(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CGOpenMPRuntime::emitTargetCall(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskgroupRegion(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskwaitCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskyieldCall(), clang::CodeGen::CGOpenMPRuntime::emitTeamsCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsCall(), EnsureInsertPoint(), and protectFromPeepholes().
incrementProfileCounter()
void clang::CodeGen::CodeGenFunction::incrementProfileCounter (const Stmt * S, llvm::Value * StepV = nullptr) inline
Increment the profiler's counter for the given statement by StepV.
If StepV is null, the default increment is 1.
Definition at line 1587 of file CodeGenFunction.h.
Referenced by EmitBranchOnBoolExpr(), EmitBranchToCounterBlock(), EmitConstructorBody(), EmitDestructorBody(), EmitFunctionBody(), emitImplicitAssignmentOperatorBody(), EmitLabel(), GenerateBlockFunction(), and GenerateObjCMethod().
InitCapturedStruct()
LValue CodeGenFunction::InitCapturedStruct (const CapturedStmt & S)
Definition at line 2998 of file CGStmt.cpp.
initFullExprCleanup()
void clang::CodeGen::CodeGenFunction::initFullExprCleanup () inline
Set up the last cleanup that was pushed as a conditional full-expression cleanup.
Definition at line 880 of file CodeGenFunction.h.
References createCleanupActiveFlag(), and initFullExprCleanupWithFlag().
Referenced by EnterNewDeleteCleanup(), and pushFullExprCleanup().
initFullExprCleanupWithFlag()
void CodeGenFunction::initFullExprCleanupWithFlag (RawAddress ActiveFlag)
Definition at line 283 of file CGCleanup.cpp.
References clang::CodeGen::EHScopeStack::begin(), clang::format::cleanup(), and EHStack.
Referenced by initFullExprCleanup(), and pushLifetimeExtendedDestroy().
InitializeVTablePointer()
void CodeGenFunction::InitializeVTablePointer (const VPtr & vptr)
Initialize the vtable pointer of the given subobject.
Definition at line 2552 of file CGClass.cpp.
References ApplyNonVirtualAndVirtualOffset(), clang::CodeGen::CodeGenFunction::VPtr::Base, Builder, CGM, clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenModule::DecorateInstructionWithInvariantGroup(), clang::CodeGen::CodeGenModule::DecorateInstructionWithTBAA(), clang::BaseSubobject::getBaseOffset(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::CodeGenModule::getTBAAVTablePtrAccessInfo(), clang::CodeGen::CGCXXABI::GetVirtualBaseClassOffset(), clang::CodeGen::CGCXXABI::getVTableAddressPointInStructor(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CGCXXABI::isVirtualOffsetNeededForVTableField(), clang::CharUnits::isZero(), LoadCXXThisAddress(), clang::CodeGen::CodeGenFunction::VPtr::NearestVBase, clang::CodeGen::CodeGenFunction::VPtr::OffsetFromNearestVBase, clang::CodeGen::CodeGenFunction::VPtr::VTableClass, clang::CodeGen::Address::withElementType(), and clang::CharUnits::Zero().
Referenced by InitializeVTablePointers().
InitializeVTablePointers()
void CodeGenFunction::InitializeVTablePointers (const CXXRecordDecl * ClassDecl)
Definition at line 2674 of file CGClass.cpp.
References CGM, clang::CodeGen::CGCXXABI::doStructorsInitializeVPtrs(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CXXRecordDecl::getNumVBases(), getVTablePointers(), clang::CodeGen::CGCXXABI::initializeHiddenVirtualInheritanceMembers(), InitializeVTablePointer(), and clang::CXXRecordDecl::isDynamicClass().
Referenced by EmitBaseInitializer(), EmitCtorPrologue(), and EmitDestructorBody().
InsertHelper()
void CodeGenFunction::InsertHelper (llvm::Instruction * I, const llvm::Twine & Name, llvm::BasicBlock * BB, llvm::BasicBlock::iterator InsertPt) const
CGBuilder insert helper.
This function is called after an instruction is created using Builder.
Definition at line 2987 of file CodeGenFunction.cpp.
inSuspendBlock()
bool clang::CodeGen::CodeGenFunction::inSuspendBlock () const inline
Definition at line 373 of file CodeGenFunction.h.
References CurCoro, clang::CodeGen::CodeGenFunction::CGCoroInfo::InSuspendBlock, and isCoroutine().
Referenced by EmitMaterializeTemporaryExpr().
isBinaryLogicalOp()
bool clang::CodeGen::CodeGenFunction::isBinaryLogicalOp (const Expr * E) const inline
Definition at line 1611 of file CodeGenFunction.h.
References clang::Expr::IgnoreParens(), and clang::BinaryOperator::isLogicalOp().
Referenced by maybeResetMCDCCondBitmap(), and maybeUpdateMCDCTestVectorBitmap().
isCleanupPadScope()
bool clang::CodeGen::CodeGenFunction::isCleanupPadScope () const inline
Returns true while emitting a cleanuppad.
Definition at line 816 of file CodeGenFunction.h.
References CurrentFuncletPad.
Referenced by EmitCall().
IsConstructorDelegationValid()
bool CodeGenFunction::IsConstructorDelegationValid (const CXXConstructorDecl * Ctor) static
Checks whether the given constructor is a valid subject for the complete-to-base constructor delegation optimization, i.e.
emitting the complete constructor as a simple call to the base constructor.
Definition at line 730 of file CGClass.cpp.
References clang::Type::castAs(), clang::CXXRecordDecl::getNumVBases(), clang::CXXMethodDecl::getParent(), clang::ValueDecl::getType(), clang::CXXConstructorDecl::isDelegatingConstructor(), and clang::FunctionProtoType::isVariadic().
Referenced by clang::CodeGen::CodeGenPGO::assignRegionCounters(), and EmitConstructorBody().
isCoroutine()
bool clang::CodeGen::CodeGenFunction::isCoroutine () const inline
Definition at line 369 of file CodeGenFunction.h.
References CurCoro, and clang::CodeGen::CodeGenFunction::CGCoroInfo::Data.
Referenced by FinishFunction(), and inSuspendBlock().
isInConditionalBranch()
bool clang::CodeGen::CodeGenFunction::isInConditionalBranch () const inline
isInConditionalBranch - Return true if we're currently emitting one branch or the other of a conditional expression.
Definition at line 1266 of file CodeGenFunction.h.
Referenced by EmitMaterializeTemporaryExpr(), EnterNewDeleteCleanup(), pushCleanupAfterFullExpr(), pushFullExprCleanup(), pushLifetimeExtendedDestroy(), setBeforeOutermostConditional(), and SetupCleanupBlockActivation().
isInstrumentedCondition()
bool CodeGenFunction::isInstrumentedCondition (const Expr * C) static
isInstrumentedCondition - Determine whether the given condition is an instrumentable condition (i.e.
Determine whether the given condition is an instrumentable condition (i.e.
no "&&" or "||").
Definition at line 1955 of file CodeGenFunction.cpp.
References clang::BinaryOperator::isLogicalOp(), and stripCond().
Referenced by EmitBranchOnBoolExpr(), and EmitBranchToCounterBlock().
isMCDCCoverageEnabled()
bool clang::CodeGen::CodeGenFunction::isMCDCCoverageEnabled () const inline
Definition at line 1595 of file CodeGenFunction.h.
References CGM, CurFn, clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGenOptions::hasProfileClangInstr().
Referenced by maybeCreateMCDCCondBitmap(), maybeResetMCDCCondBitmap(), maybeUpdateMCDCCondBitmap(), and maybeUpdateMCDCTestVectorBitmap().
isNullPointerAllowed()
bool CodeGenFunction::isNullPointerAllowed (TypeCheckKind TCK) static
Determine whether the pointer type check TCK permits null pointers.
Definition at line 660 of file CGExpr.cpp.
References TCK_DowncastPointer, TCK_DynamicOperation, TCK_Upcast, and TCK_UpcastToVirtualBase.
Referenced by EmitTypeCheck().
isObviouslyBranchWithoutCleanups()
bool CodeGenFunction::isObviouslyBranchWithoutCleanups (JumpDest Dest) const
isObviouslyBranchWithoutCleanups - Return true if a branch to the specified destination obviously has no cleanups to run.
'false' is always a conservatively correct answer for this method.
Definition at line 1045 of file CGCleanup.cpp.
References clang::CodeGen::EHScopeStack::stable_iterator::encloses(), and clang::CodeGen::CodeGenFunction::JumpDest::getScopeDepth().
isPointerKnownNonNull()
bool clang::CodeGen::CodeGenFunction::isPointerKnownNonNull (const Expr * E)
isSEHTryScope()
bool clang::CodeGen::CodeGenFunction::isSEHTryScope () const inline
Returns true inside SEH __try blocks.
Definition at line 813 of file CodeGenFunction.h.
References SEHTryEpilogueStack.
Referenced by EmitCall().
isTrivialInitializer()
bool CodeGenFunction::isTrivialInitializer (const Expr * Init)
Determine whether the given initializer is trivial in the sense that it requires no code to be generated.
Definition at line 1813 of file CGDecl.cpp.
Referenced by AllTrivialInitializers(), checkInitIsRequired(), EmitAutoVarInit(), clang::CodeGen::ReductionCodeGen::emitInitialization(), and emitPrivatesInit().
isVptrCheckRequired()
bool CodeGenFunction::isVptrCheckRequired (TypeCheckKind TCK, QualType Ty) static
Determine whether the pointer type check TCK requires a vptr check.
Definition at line 665 of file CGExpr.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::CXXRecordDecl::hasDefinition(), clang::CXXRecordDecl::isDynamicClass(), TCK_DowncastPointer, TCK_DowncastReference, TCK_DynamicOperation, TCK_MemberAccess, TCK_MemberCall, and TCK_UpcastToVirtualBase.
Referenced by EmitTypeCheck().
IsWrappedCXXThis()
bool CodeGenFunction::IsWrappedCXXThis (const Expr * E) static
Check if E is a C++ "this" pointer wrapped in value-preserving casts.
Definition at line 1439 of file CGExpr.cpp.
Referenced by EmitCheckedLValue(), and EmitMemberExpr().
LoadBlockStruct()
Address CodeGenFunction::LoadBlockStruct ()
Definition at line 1408 of file CGBlocks.cpp.
References clang::CodeGen::CGBlockInfo::BlockAlign, BlockInfo, BlockPointer, and clang::CodeGen::CGBlockInfo::StructureType.
Referenced by GenerateBlockFunction(), and GetAddrOfBlockDecl().
LoadCXXThis()
llvm::Value* clang::CodeGen::CodeGenFunction::LoadCXXThis () inline
LoadCXXThis - Load the value of 'this'.
This function is only valid while generating code for an C++ member function.
Definition at line 2998 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), EmitCallAndReturnForThunk(), EmitCtorPrologue(), EmitDestructorBody(), EmitMemberInitializer(), and LoadCXXThisAddress().
LoadCXXThisAddress()
Address CodeGenFunction::LoadCXXThisAddress ()
Definition at line 130 of file CGClass.cpp.
References CGM, CurFuncDecl, clang::CodeGen::CodeGenModule::getClassPointerAlignment(), clang::CharUnits::isZero(), clang::CodeGen::KnownNonNull, LoadCXXThis(), and makeNaturalAddressForPointer().
Referenced by EmitBaseInitializer(), EmitCallAndReturnForThunk(), EmitCtorPrologue(), EmitDelegateCXXConstructorCall(), EmitDelegatingCXXConstructorCall(), EmitDestructorBody(), and InitializeVTablePointer().
LoadCXXVTT()
llvm::Value* clang::CodeGen::CodeGenFunction::LoadCXXVTT () inline
LoadCXXVTT - Load the VTT parameter to base constructors/destructors have virtual bases.
Definition at line 3008 of file CodeGenFunction.h.
Referenced by GetVTTParameter().
LoadObjCSelf()
llvm::Value * CodeGenFunction::LoadObjCSelf ()
LoadObjCSelf - Load the value of self.
This function is only valid while generating code for an Objective-C method.
Definition at line 1745 of file CGObjC.cpp.
References CurCodeDecl, CurFuncDecl, EmitDeclRefLValue(), EmitLoadOfScalar(), getContext(), and clang::VK_LValue.
Referenced by emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), emitCXXDestructMethod(), EmitObjCMessageExpr(), emitStructSetterCall(), GenerateObjCCtorDtorMethod(), generateObjCGetterBody(), and generateObjCSetterBody().
LoadPassedObjectSize()
llvm::Value * CodeGenFunction::LoadPassedObjectSize (const Expr * E, QualType EltTy)
If E references a parameter with pass_object_size info or a constant array size modifier, emit the object size divided by the size of EltTy.
Otherwise return null.
Definition at line 880 of file CGExpr.cpp.
References Builder, EmitLoadOfScalar(), getContext(), clang::Expr::getExprLoc(), and clang::Expr::IgnoreParenImpCasts().
Referenced by getArrayIndexingBound().
LookupNeonLLVMIntrinsic()
Function * CodeGenFunction::LookupNeonLLVMIntrinsic (unsigned IntrinsicID, unsigned Modifier, llvm::Type * ArgTy, const CallExpr * E)
Definition at line 7589 of file CGBuiltin.cpp.
References Add1ArgType, Add2ArgTypes, AddRetType, clang::Function, clang::CallExpr::getCallReturnType(), InventFloatType, Use128BitVectors, Use64BitVectors, VectorizeArgTypes, and VectorizeRetType.
Referenced by EmitCommonNeonSISDBuiltinExpr().
LValueIsSuitableForInlineAtomic()
bool CodeGenFunction::LValueIsSuitableForInlineAtomic (LValue Src)
An LValue is a candidate for having its loads and stores be made atomic if we are operating under /volatile:ms and the LValue itself is volatile and performing such an operation can be performed without a libcall.
Definition at line 1493 of file CGAtomic.cpp.
References CGM, getContext(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::LValue::getType(), getTypeSize(), hasVolatileMember(), and clang::CodeGen::LValue::isVolatile().
Referenced by EmitLoadOfScalar(), and EmitStoreOfScalar().
MakeAddrLValue() [1/3]
LValue clang::CodeGen::CodeGenFunction::MakeAddrLValue (Address Addr, QualType T, AlignmentSource Source = AlignmentSource::Type) inline
Definition at line 2658 of file CodeGenFunction.h.
References CGM, clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), and clang::T.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), complexTempStructure(), convertTempToRValue(), clang::CodeGen::CallArg::copyInto(), EmitAggExprToLValue(), EmitAnyExprToMem(), EmitArraySubscriptExpr(), EmitAtomicExpr(), EmitAtomicUpdateValue(), EmitAutoVarAlloca(), EmitAutoVarInit(), EmitCallExprLValue(), EmitCastLValue(), EmitCompoundLiteralLValue(), EmitConditionalOperatorLValue(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), EmitCXXBindTemporaryLValue(), EmitCXXConstructLValue(), EmitCXXConstructorCall(), EmitCXXUuidofLValue(), EmitDeclInit(), EmitDeclRefLValue(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitExtVectorElementExpr(), EmitFunctionDeclLValue(), EmitFunctionEpilog(), EmitFunctionProlog(), emitGlobalToListCopyFunction(), EmitGlobalVarDeclLValue(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), emitListToGlobalCopyFunction(), EmitLoadOfPointerLValue(), EmitLoadOfReferenceLValue(), EmitLValueForField(), EmitLValueForFieldInitialization(), EmitLValueForLambdaField(), EmitMaterializeTemporaryExpr(), EmitMemberExpr(), EmitNontemporalLoad(), EmitNontemporalStore(), EmitObjCEncodeExprLValue(), EmitObjCIsaExpr(), EmitObjCMessageExprLValue(), EmitObjCSelectorLValue(), EmitOMPArraySectionExpr(), emitOutlinedFunctionPrologue(), EmitParmDecl(), EmitPointerToDataMemberBinaryExpr(), emitPrivatesInit(), emitPseudoObjectExpr(), EmitStmtExprLValue(), EmitStringLiteralLValue(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitThreadIDAddress(), EmitThreadPrivateVarDeclLValue(), EmitUnaryOpLValue(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), emitWritebackArg(), GenerateCopyHelperFunction(), generateObjCGetterBody(), generateObjCSetterBody(), GetAddrOfBlockDecl(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), clang::CodeGen::CallArg::getRValue(), InitCatchParam(), loadToBegin(), MakeAddrLValue(), MakeNaturalAlignAddrLValue(), and StoreAnyExprIntoOneUnit().
MakeAddrLValue() [2/3]
LValue clang::CodeGen::CodeGenFunction::MakeAddrLValue (Address Addr, QualType T, LValueBaseInfo BaseInfo, TBAAAccessInfo TBAAInfo) inline
Definition at line 2664 of file CodeGenFunction.h.
References getContext(), clang::CodeGen::LValue::MakeAddr(), and clang::T.
MakeAddrLValue() [3/3]
LValue clang::CodeGen::CodeGenFunction::MakeAddrLValue (llvm::Value * V, QualType T, CharUnits Alignment, AlignmentSource Source = AlignmentSource::Type) inline
Definition at line 2669 of file CodeGenFunction.h.
References CGM, clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), MakeAddrLValue(), makeNaturalAddressForPointer(), clang::T, and V.
MakeAddrLValueWithoutTBAA()
LValue clang::CodeGen::CodeGenFunction::MakeAddrLValueWithoutTBAA (Address Addr, QualType T, AlignmentSource Source = AlignmentSource::Type) inline
Definition at line 2685 of file CodeGenFunction.h.
References getContext(), clang::CodeGen::LValue::MakeAddr(), and clang::T.
makeNaturalAddressForPointer()
Address clang::CodeGen::CodeGenFunction::makeNaturalAddressForPointer (llvm::Value * Ptr, QualType T, CharUnits Alignment = CharUnits::Zero(), bool ForPointeeType = false, LValueBaseInfo * BaseInfo = nullptr, TBAAAccessInfo * TBAAInfo = nullptr, KnownNonNull_t IsKnownNonNull = NotKnownNonNull) inline
Construct an address with the natural alignment of T.
If a pointer to T is expected to be signed, the pointer passed to this function must have been signed, and the returned Address will have the pointer authentication information needed to authenticate the signed pointer.
Definition at line 2646 of file CodeGenFunction.h.
References CGM, ConvertTypeForMem(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), and clang::T.
Referenced by EmitCall(), EmitCXXConstructorCall(), EmitDeclRefLValue(), EmitFunctionProlog(), EmitLoadOfPointer(), EmitLoadOfReference(), EmitPointerWithAlignment(), GenerateVarArgsThunk(), clang::CodeGen::CGCXXABI::getThisAddress(), LoadCXXThisAddress(), MakeAddrLValue(), and StartFunction().
MakeNaturalAlignAddrLValue()
LValue CodeGenFunction::MakeNaturalAlignAddrLValue (llvm::Value * V, QualType T)
Definition at line 209 of file CodeGenFunction.cpp.
References MakeNaturalAlignAddrLValue(), clang::T, and V.
Referenced by emitFrexpBuiltin(), EmitFunctionEpilog(), EmitLValueForLambdaField(), EmitMemberInitializer(), clang::CodeGen::CodeGenFunction::ConstantEmission::getReferenceLValue(), and InitCatchParam().
MakeNaturalAlignPointeeAddrLValue()
LValue CodeGenFunction::MakeNaturalAlignPointeeAddrLValue (llvm::Value * V, QualType T)
Given a value of type T* that may not be to a complete object, construct an l-value with the natural pointee alignment of T.
Definition at line 214 of file CodeGenFunction.cpp.
References MakeNaturalAlignAddrLValue(), clang::T, and V.
Referenced by EmitCallExprLValue(), EmitMemberInitializer(), and EmitObjCMessageExprLValue().
MakeNaturalAlignPointeeRawAddrLValue()
LValue CodeGenFunction::MakeNaturalAlignPointeeRawAddrLValue (llvm::Value * V, QualType T)
Same as MakeNaturalAlignPointeeAddrLValue except that the pointer is known to be unsigned.
Definition at line 223 of file CodeGenFunction.cpp.
References MakeNaturalAlignAddrLValue(), clang::T, and V.
MakeNaturalAlignRawAddrLValue()
LValue CodeGenFunction::MakeNaturalAlignRawAddrLValue (llvm::Value * V, QualType T)
Definition at line 218 of file CodeGenFunction.cpp.
References MakeNaturalAlignAddrLValue(), clang::T, and V.
Referenced by EmitCastLValue(), EmitCXXTypeidLValue(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), and clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset().
MakeRawAddrLValue()
LValue clang::CodeGen::CodeGenFunction::MakeRawAddrLValue (llvm::Value * V, QualType T, CharUnits Alignment, AlignmentSource Source = AlignmentSource::Type) inline
Same as MakeAddrLValue above except that the pointer is known to be unsigned.
Definition at line 2677 of file CodeGenFunction.h.
References CGM, ConvertTypeForMem(), getContext(), clang::CodeGen::CodeGenModule::getTBAAAccessInfo(), clang::CodeGen::LValue::MakeAddr(), clang::T, and V.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalFinalUpdate(), and clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate().
markAsIgnoreThreadCheckingAtRuntime()
void CodeGenFunction::markAsIgnoreThreadCheckingAtRuntime (llvm::Function * Fn)
Annotate the function with an attribute that disables TSan checking at runtime.
Definition at line 856 of file CodeGenFunction.cpp.
References clang::SanitizerSet::has(), and SanOpts.
Referenced by GenerateDestroyHelperFunction(), and StartFunction().
maybeCreateMCDCCondBitmap()
void clang::CodeGen::CodeGenFunction::maybeCreateMCDCCondBitmap () inline
Allocate a temp value on the stack that MCDC can use to track condition results.
Definition at line 1603 of file CodeGenFunction.h.
References Builder, CreateIRTemp(), getContext(), and isMCDCCoverageEnabled().
Referenced by EmitConstructorBody(), EmitDestructorBody(), EmitFunctionBody(), and emitImplicitAssignmentOperatorBody().
MaybeEmitFPBuiltinofFD()
llvm::CallInst * CodeGenFunction::MaybeEmitFPBuiltinofFD (llvm::FunctionType * IRFuncTy, const SmallVectorImpl< llvm::Value * > & IRArgs, llvm::Value * FnPtr, StringRef Name, unsigned FDBuiltinID)
Definition at line 23765 of file CGBuiltin.cpp.
Referenced by EmitCall().
maybeResetMCDCCondBitmap()
void clang::CodeGen::CodeGenFunction::maybeResetMCDCCondBitmap (const Expr * E) inline
Zero-init the MCDC temp value.
Definition at line 1617 of file CodeGenFunction.h.
References Builder, isBinaryLogicalOp(), and isMCDCCoverageEnabled().
maybeUpdateMCDCCondBitmap()
void clang::CodeGen::CodeGenFunction::maybeUpdateMCDCCondBitmap (const Expr * E, llvm::Value * Val) inline
Update the MCDC temp value with the condition's evaluated result.
Definition at line 1634 of file CodeGenFunction.h.
References Builder, and isMCDCCoverageEnabled().
Referenced by EmitBranchOnBoolExpr().
maybeUpdateMCDCTestVectorBitmap()
void clang::CodeGen::CodeGenFunction::maybeUpdateMCDCTestVectorBitmap (const Expr * E) inline
Increment the profiler's counter for the given expression by StepV.
If StepV is null, the default increment is 1.
Definition at line 1626 of file CodeGenFunction.h.
References Builder, isBinaryLogicalOp(), and isMCDCCoverageEnabled().
mergeAddressesInConditionalExpr()
Address clang::CodeGen::CodeGenFunction::mergeAddressesInConditionalExpr (Address LHS, Address RHS, llvm::BasicBlock * LHSBlock, llvm::BasicBlock * RHSBlock, llvm::BasicBlock * MergeBlock, QualType MergedType) inline
Definition at line 2628 of file CodeGenFunction.h.
References Builder, clang::CodeGen::Address::getAlignment(), clang::CodeGen::Address::getBasePointer(), clang::CodeGen::Address::getType(), min(), clang::CodeGen::Address::replaceBasePointer(), and clang::CodeGen::Address::setAlignment().
Referenced by EmitConditionalOperatorLValue().
mightAddDeclToScope()
bool CodeGenFunction::mightAddDeclToScope (const Stmt * S) static
Determine if the given statement might introduce a declaration into the current scope, by being a (possibly-labelled) DeclStmt.
Definition at line 1879 of file CodeGenFunction.cpp.
needsEHCleanup()
bool clang::CodeGen::CodeGenFunction::needsEHCleanup (QualType::DestructionKind kind) inline
Determines whether an EH cleanup is required to destroy a type with the given destruction kind.
Definition at line 2209 of file CodeGenFunction.h.
References CGM, clang::QualType::DK_cxx_destructor, clang::QualType::DK_none, clang::QualType::DK_nontrivial_c_struct, clang::QualType::DK_objc_strong_lifetime, clang::QualType::DK_objc_weak_lifetime, clang::CodeGen::CodeGenModule::getCodeGenOpts(), and getLangOpts().
Referenced by EmitArrayDelete(), EmitCallArg(), EmitDeclDestroy(), EmitInitializerForField(), EmitMemberInitializer(), EmitNewArrayInitializer(), GenerateCopyHelperFunction(), getCleanupKind(), pushCaptureCleanup(), and pushEHDestroy().
popCatchScope()
void CodeGenFunction::popCatchScope ()
popCatchScope - Pops the catch scope at the top of the EHScope stack, emitting any required code (other than the catch handlers themselves).
Definition at line 1203 of file CGException.cpp.
References clang::CodeGen::EHScopeStack::begin(), EHStack, emitCatchDispatchBlock(), clang::CodeGen::EHScope::hasEHBranches(), and clang::CodeGen::EHScopeStack::popCatch().
Referenced by clang::CodeGen::CodeGenFunction::FinallyInfo::exit().
PopCleanupBlock()
void CodeGenFunction::PopCleanupBlock (bool FallthroughIsBranchThrough = false)
PopCleanupBlock - Will pop the cleanup entry on the stack and process all branch fixups.
Pops a cleanup block.
If the block includes a normal cleanup, the current insertion point is threaded through the cleanup, as are any branch fixups on the cleanup.
Definition at line 637 of file CGCleanup.cpp.
References clang::CodeGen::Address::invalid().
Referenced by EmitArrayDelete(), emitArrayDestroy(), EmitCall(), EmitObjectDelete(), and clang::CodeGen::CodeGenFunction::FinallyInfo::exit().
PopCleanupBlocks() [1/2]
void CodeGenFunction::PopCleanupBlocks (EHScopeStack::stable_iterator OldCleanupStackSize, size_t OldLifetimeExtendedStackSize, std::initializer_list< llvm::Value ** > ValuesToReload = {})
Takes the old cleanup stack size and emits the cleanup blocks that have been added, then adds all lifetime-extended cleanups from the given position to the stack.
Pops cleanup blocks until the given savepoint is reached, then add the cleanups from the given savepoint in the lifetime-extended cleanups stack.
Definition at line 466 of file CGCleanup.cpp.
References clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::getKind(), clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::getSize(), and clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::isConditional().
PopCleanupBlocks() [2/2]
void CodeGenFunction::PopCleanupBlocks (EHScopeStack::stable_iterator OldCleanupStackSize, std::initializer_list< llvm::Value ** > ValuesToReload = {})
Takes the old cleanup stack size and emits the cleanup blocks that have been added.
Pops cleanup blocks until the given savepoint is reached.
Definition at line 410 of file CGCleanup.cpp.
References clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::EHScopeStack::stable_iterator::isValid(), and clang::CodeGen::EHScopeStack::stable_iterator::strictlyEncloses().
Referenced by FinishFunction().
processInReduction()
void CodeGenFunction::processInReduction (const OMPExecutableDirective & S, OMPTaskDataTy & Data, CodeGenFunction & CGF, const CapturedStmt * CS, OMPPrivateScope & Scope)
Definition at line 5185 of file CGStmtOpenMP.cpp.
ProcessOrderScopeAMDGCN()
void CodeGenFunction::ProcessOrderScopeAMDGCN (llvm::Value * Order, llvm::Value * Scope, llvm::AtomicOrdering & AO, llvm::SyncScope::ID & SSID)
Definition at line 18225 of file CGBuiltin.cpp.
protectFromPeepholes()
CodeGenFunction::PeepholeProtection CodeGenFunction::protectFromPeepholes (RValue rvalue)
protectFromPeepholes - Protect a value that we're intending to store to the side, but which will probably be used later, from aggressive peepholing optimizations that might delete it.
Pass the result to unprotectFromPeepholes to declare that protection is no longer required.
There's no particular reason why this shouldn't apply to l-values, it's just that no existing peepholes work on pointers.
Definition at line 2754 of file CodeGenFunction.cpp.
References Builder, clang::CodeGen::RValue::getScalarVal(), HaveInsertPoint(), and clang::CodeGen::RValue::isScalar().
Referenced by clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::bind().
pushCallObjectDeleteCleanup()
void CodeGenFunction::pushCallObjectDeleteCleanup (const FunctionDecl * OperatorDelete, llvm::Value * CompletePtr, QualType ElementType)
Definition at line 1892 of file CGExprCXX.cpp.
References EHStack, and clang::CodeGen::NormalAndEHCleanup.
pushCleanupAfterFullExpr()
template<class T , class... As> void clang::CodeGen::CodeGenFunction::pushCleanupAfterFullExpr (CleanupKind Kind, As... A) inline
Queue a cleanup to be pushed after finishing the current full-expression, potentially with an active flag.
Definition at line 842 of file CodeGenFunction.h.
References createCleanupActiveFlag(), clang::CodeGen::RawAddress::invalid(), isInConditionalBranch(), saveValueInCond(), and clang::T.
pushCleanupAfterFullExprWithActiveFlag()
template<class T , class... As> void clang::CodeGen::CodeGenFunction::pushCleanupAfterFullExprWithActiveFlag (CleanupKind Kind, RawAddress ActiveFlag, As... A) inline
Definition at line 859 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::IsConditional, clang::CodeGen::RawAddress::isValid(), LifetimeExtendedCleanupStack, clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::Size, and clang::T.
pushDestroy() [1/2]
void CodeGenFunction::pushDestroy (CleanupKind kind, Address addr, QualType type, Destroyer * destroyer, bool useEHCleanupForArray)
Definition at line 2251 of file CGDecl.cpp.
References clang::ast_matchers::type.
pushDestroy() [2/2]
void CodeGenFunction::pushDestroy (QualType::DestructionKind dtorKind, Address addr, QualType type)
pushDestroy - Push the standard destructor for the given type as at least a normal cleanup.
Definition at line 2242 of file CGDecl.cpp.
References clang::CodeGen::EHCleanup, getCleanupKind(), getDestroyer(), and clang::ast_matchers::type.
Referenced by EmitAutoVarWithLifetime(), EmitCall(), clang::CodeGen::ReductionCodeGen::emitCleanups(), EmitParmDecl(), pushCaptureCleanup(), pushEHDestroy(), and pushTemporaryCleanup().
PushDestructorCleanup() [1/2]
void CodeGenFunction::PushDestructorCleanup (const CXXDestructorDecl * Dtor, QualType T, Address Addr)
PushDestructorCleanup - Push a cleanup to call the complete-object variant of the given destructor on the object at the given address.
Definition at line 2537 of file CGClass.cpp.
References EHStack, clang::CodeGen::NormalAndEHCleanup, and clang::T.
PushDestructorCleanup() [2/2]
void CodeGenFunction::PushDestructorCleanup (QualType T, Address Addr)
PushDestructorCleanup - Push a cleanup to call the complete-object destructor of an object of the given type at the given address.
Does nothing if T is not a C++ class type with a non-trivial destructor.
Definition at line 2542 of file CGClass.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::CXXRecordDecl::getDestructor(), clang::CXXRecordDecl::hasTrivialDestructor(), clang::Decl::isUsed(), and clang::T.
pushEHDestroy()
void CodeGenFunction::pushEHDestroy (QualType::DestructionKind dtorKind, Address addr, QualType type)
pushEHDestroy - Push the standard destructor for the given type as an EH-only cleanup.
Definition at line 2232 of file CGDecl.cpp.
References clang::CodeGen::EHCleanup, getDestroyer(), needsEHCleanup(), pushDestroy(), and clang::ast_matchers::type.
Referenced by EmitInitializerForField(), and EmitMemberInitializer().
pushFullExprCleanup()
template<class T , class... As> void clang::CodeGen::CodeGenFunction::pushFullExprCleanup (CleanupKind kind, As... A) inline
pushFullExprCleanup - Push a cleanup to be run at the end of the current full-expression.
Safe against the possibility that we're currently inside a conditionally-evaluated expression.
Definition at line 824 of file CodeGenFunction.h.
References EHStack, initFullExprCleanup(), isInConditionalBranch(), clang::CodeGen::EHScopeStack::pushCleanupTuple(), saveValueInCond(), and clang::T.
pushIrregularPartialArrayCleanup()
void CodeGenFunction::pushIrregularPartialArrayCleanup (llvm::Value * arrayBegin, Address arrayEndPointer, QualType elementType, CharUnits elementAlign, Destroyer * destroyer)
pushIrregularPartialArrayCleanup - Push an EH cleanup to destroy already-constructed elements of the given array.
The cleanup may be popped with DeactivateCleanupBlock or PopCleanupBlock.
Parameters
elementType - the immediate element type of the array; possibly still an array type
Definition at line 2505 of file CGDecl.cpp.
References clang::CodeGen::EHCleanup.
Referenced by EmitNewArrayInitializer().
pushKmpcAllocFree()
void CodeGenFunction::pushKmpcAllocFree (CleanupKind Kind, std::pair< llvm::Value *, llvm::Value * > AddrSizePair)
Definition at line 2262 of file CGDecl.cpp.
References EHStack.
Referenced by EmitAutoVarAlloca().
pushLifetimeExtendedDestroy()
void CodeGenFunction::pushLifetimeExtendedDestroy (CleanupKind kind, Address addr, QualType type, Destroyer * destroyer, bool useEHCleanupForArray)
Definition at line 2267 of file CGDecl.cpp.
References createCleanupActiveFlag(), clang::CodeGen::EHCleanup, EHStack, initFullExprCleanupWithFlag(), clang::CodeGen::Address::invalid(), isInConditionalBranch(), clang::CodeGen::NormalCleanup, saveValueInCond(), and clang::ast_matchers::type.
Referenced by EmitCompoundLiteralLValue(), and pushTemporaryCleanup().
pushRegularPartialArrayCleanup()
void CodeGenFunction::pushRegularPartialArrayCleanup (llvm::Value * arrayBegin, llvm::Value * arrayEnd, QualType elementType, CharUnits elementAlign, Destroyer * destroyer)
pushRegularPartialArrayCleanup - Push an EH cleanup to destroy already-constructed elements of the given array.
The cleanup may be popped with DeactivateCleanupBlock or PopCleanupBlock.
Parameters
elementType - the immediate element type of the array; possibly still an array type
Definition at line 2522 of file CGDecl.cpp.
References clang::CodeGen::EHCleanup.
Referenced by emitArrayDestroy(), EmitCXXAggrConstructorCall(), and EmitNewArrayInitializer().
pushSEHCleanup()
void CodeGenFunction::pushSEHCleanup (CleanupKind kind, llvm::Function * FinallyFunc)
Definition at line 2165 of file CGException.cpp.
References EHStack.
pushStackRestore()
void CodeGenFunction::pushStackRestore (CleanupKind kind, Address SPMem)
Definition at line 2258 of file CGDecl.cpp.
References EHStack.
recoverAddrOfEscapedLocal()
Address CodeGenFunction::recoverAddrOfEscapedLocal (CodeGenFunction & ParentCGF, Address ParentVar, llvm::Value * ParentFP)
Recovers the address of a local in a parent function.
ParentVar is the address of the variable used in the immediate parent function. It can either be an alloca or a call to llvm.localrecover if there are nested outlined functions. ParentFP is the frame pointer of the outermost parent frame.
Definition at line 1832 of file CGException.cpp.
References AllocaInsertPt, Builder, CGM, CurFn, clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getBasePointer(), clang::CodeGen::CodeGenModule::getModule(), clang::CodeGen::Address::getName(), clang::CodeGen::Address::getType(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::KnownNonNull, ParentCGF, and clang::CodeGen::Address::withPointer().
Referenced by EmitSEHExceptionCodeSave().
registerGlobalDtorWithAtExit() [1/2]
void CodeGenFunction::registerGlobalDtorWithAtExit (const VarDecl & D, llvm::FunctionCallee fn, llvm::Constant * addr)
Call atexit() with a function that passes the given argument to the given function.
Register a global destructor using the C atexit runtime function.
Definition at line 326 of file CGDeclCXX.cpp.
References createAtExitStub().
registerGlobalDtorWithAtExit() [2/2]
void CodeGenFunction::registerGlobalDtorWithAtExit (llvm::Constant * dtorStub)
Call atexit() with function dtorStub.
Definition at line 343 of file CGDeclCXX.cpp.
References CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenTypeCache::IntTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
registerGlobalDtorWithLLVM()
void CodeGenFunction::registerGlobalDtorWithLLVM (const VarDecl & D, llvm::FunctionCallee fn, llvm::Constant * addr)
Registers the dtor using 'llvm.global_dtors' for platforms that do not support an 'atexit()' function.
Register a global destructor using the LLVM 'llvm.global_dtors' global.
Definition at line 335 of file CGDeclCXX.cpp.
References clang::CodeGen::CodeGenModule::AddGlobalDtor(), CGM, and createAtExitStub().
ResolveBranchFixups()
void CodeGenFunction::ResolveBranchFixups (llvm::BasicBlock * Target)
Definition at line 371 of file CGCleanup.cpp.
References Block, clang::CodeGen::BranchFixup::Destination, clang::CodeGen::BranchFixup::OptimisticBranchBlock, clang::Switch, and TransitionToCleanupSwitch().
Referenced by EmitLabel().
sanitizePerformTypeCheck()
bool CodeGenFunction::sanitizePerformTypeCheck () const
Whether any type-checking sanitizers are enabled.
If false, calls to EmitTypeCheck can be skipped.
Definition at line 673 of file CGExpr.cpp.
References clang::SanitizerSet::has(), and SanOpts.
Referenced by EmitCastLValue(), EmitCXXNewExpr(), EmitReferenceBindingToExpr(), EmitTypeCheck(), and GetAddressOfBaseClass().
saveValueInCond()
template<class T > DominatingValue<T>::saved_type clang::CodeGen::CodeGenFunction::saveValueInCond (T value) inline
Definition at line 764 of file CodeGenFunction.h.
References clang::CodeGen::InvariantValue< T >::save().
Referenced by pushCleanupAfterFullExpr(), pushFullExprCleanup(), and pushLifetimeExtendedDestroy().
setBeforeOutermostConditional()
void clang::CodeGen::CodeGenFunction::setBeforeOutermostConditional (llvm::Value * value, Address addr, CodeGenFunction & CGF) inline
Definition at line 1268 of file CodeGenFunction.h.
References clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::CharUnits::getAsAlign(), clang::CodeGen::CodeGenFunction::ConditionalEvaluation::getStartingBlock(), and isInConditionalBranch().
Referenced by createCleanupActiveFlag(), and SetupCleanupBlockActivation().
setBlockContextParameter()
void CodeGenFunction::setBlockContextParameter (const ImplicitParamDecl * D, unsigned argNum, llvm::Value * ptr)
Definition at line 1375 of file CGBlocks.cpp.
References std::arg(), BlockInfo, BlockPointer, Builder, CGM, CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::Stmt::getBeginLoc(), clang::CodeGen::CGBlockInfo::getBlockExpr(), clang::BlockExpr::getBody(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), getDebugInfo(), getLangOpts(), getLLVMContext(), clang::Decl::getLocation(), clang::NamedDecl::getName(), clang::CodeGen::RawAddress::getPointer(), clang::ValueDecl::getType(), clang::CodeGenOptions::hasReducedDebugInfo(), clang::OpenCL, and clang::opencl_generic.
Referenced by EmitParmDecl().
setCurrentProfileCount()
void clang::CodeGen::CodeGenFunction::setCurrentProfileCount (uint64_t Count) inline
Set the profiler's current count.
Definition at line 1647 of file CodeGenFunction.h.
Referenced by EmitBranchOnBoolExpr().
SetDivFPAccuracy()
void CodeGenFunction::SetDivFPAccuracy (llvm::Value * Val)
Set the minimum required accuracy of the given sqrt operation based on CodeGenOpts.
Definition at line 6126 of file CGExpr.cpp.
References CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), getLangOpts(), clang::HIP, clang::OpenCL, and SetFPAccuracy().
SetFastMathFlags()
void CodeGenFunction::SetFastMathFlags (FPOptions FPFeatures)
Set the codegen fast-math flags.
Definition at line 123 of file CodeGenFunction.cpp.
References clang::FPOptions::allowFPContractAcrossStatement(), and Builder.
SetFPAccuracy()
void CodeGenFunction::SetFPAccuracy (llvm::Value * Val, float Accuracy)
SetFPAccuracy - Set the minimum required accuracy of the given floating point operation, expressed as the maximum relative error in ulp.
Definition at line 6094 of file CGExpr.cpp.
References getLLVMContext(), and Node.
Referenced by SetDivFPAccuracy(), and SetSqrtFPAccuracy().
SetSqrtFPAccuracy()
void CodeGenFunction::SetSqrtFPAccuracy (llvm::Value * Val)
Set the minimum required accuracy of the given sqrt operation based on CodeGenOpts.
Definition at line 6105 of file CGExpr.cpp.
References CGM, clang::CodeGen::CodeGenModule::getCodeGenOpts(), getLangOpts(), clang::HIP, clang::OpenCL, and SetFPAccuracy().
Referenced by EmitCall().
ShouldEmitVTableTypeCheckedLoad()
bool CodeGenFunction::ShouldEmitVTableTypeCheckedLoad (const CXXRecordDecl * RD)
Returns whether we should perform a type checked load when loading a virtual function for virtual calls to members of RD.
This is generally true when both vcall CFI and whole-program-vtables are enabled.
Definition at line 2892 of file CGClass.cpp.
References CGM, clang::NoSanitizeList::containsType(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::ASTContext::getNoSanitizeList(), clang::NamedDecl::getQualifiedNameAsString(), clang::SanitizerSet::has(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), clang::CodeGenOptions::SanitizeTrap, SanOpts, and clang::TypeName.
ShouldInstrumentFunction()
bool CodeGenFunction::ShouldInstrumentFunction ()
ShouldInstrumentFunction - Return true if the current function should be instrumented with __cyg_profile_func_* calls.
Definition at line 551 of file CodeGenFunction.cpp.
References CGM, CurFuncDecl, clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::Decl::hasAttr().
Referenced by FinishFunction(), and StartFunction().
ShouldNullCheckClassCastValue()
bool CodeGenFunction::ShouldNullCheckClassCastValue (const CastExpr * Cast) static
Definition at line 2192 of file CGExprScalar.cpp.
References clang::CastExpr::getCastKind(), clang::CastExpr::getSubExpr(), and clang::Expr::IgnoreParens().
Referenced by EmitPointerWithAlignment().
ShouldSkipSanitizerInstrumentation()
bool CodeGenFunction::ShouldSkipSanitizerInstrumentation ()
ShouldSkipSanitizerInstrumentation - Return true if the current function should not be instrumented with sanitizers.
Definition at line 561 of file CodeGenFunction.cpp.
References CurFuncDecl, and clang::Decl::hasAttr().
Referenced by StartFunction().
shouldUseFusedARCCalls()
bool clang::CodeGen::CodeGenFunction::shouldUseFusedARCCalls () inline
Definition at line 2123 of file CodeGenFunction.h.
References CGM, and clang::CodeGen::CodeGenModule::getCodeGenOpts().
Referenced by EmitARCStoreStrong(), and emitAutoreleaseOfResult().
ShouldXRayInstrumentFunction()
bool CodeGenFunction::ShouldXRayInstrumentFunction () const
ShouldXRayInstrument - Return true if the current function should be instrumented with XRay nop sleds.
Definition at line 569 of file CodeGenFunction.cpp.
References CGM, and clang::CodeGen::CodeGenModule::getCodeGenOpts().
Referenced by StartFunction().
SimplifyForwardingBlocks()
void CodeGenFunction::SimplifyForwardingBlocks (llvm::BasicBlock * BB)
SimplifyForwardingBlocks - If the given basic block is only a branch to another basic block, simplify it.
This assumes that no other code could potentially reference the basic block.
Definition at line 556 of file CGStmt.cpp.
References EHStack, and clang::CodeGen::EHScopeStack::empty().
SourceLocToDebugLoc()
llvm::DebugLoc CodeGenFunction::SourceLocToDebugLoc (SourceLocation Location)
Converts Location to a DebugLoc, if debug information is enabled.
Definition at line 3344 of file CodeGenFunction.cpp.
References getDebugInfo().
Referenced by GenerateCode().
StartFunction()
void CodeGenFunction::StartFunction (GlobalDecl GD, QualType RetTy, llvm::Function * Fn, const CGFunctionInfo & FnInfo, const FunctionArgList & Args, SourceLocation Loc = SourceLocation(), SourceLocation StartLoc = SourceLocation())
Emit code for the start of a function.
Parameters
Loc The location to be associated with the function.
StartLoc The location of the function body.
Definition at line 912 of file CodeGenFunction.cpp.
References clang::CodeGen::CGSYCLRuntime::actOnFunctionStart(), AllocaInsertPt, clang::ProfileList::Allow, AutoreleaseResult, Builder, CGM, ConvertType(), clang::CPlusPlus, clang::CodeGen::CGBuilderTy::CreateAlignedLoad(), createBasicBlock(), CreateDefaultAlignTempAlloca(), CreateIRTemp(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CGBuilderTy::CreateStructGEP(), clang::CUDA, CurCodeDecl, CurFn, CurFnInfo, CurFuncDecl, CurFuncIsThunk, CurSEHParent, EHStack, clang::CodeGen::CGHLSLRuntime::emitEntryFunction(), clang::CodeGen::CGOpenMPRuntime::emitFunctionProlog(), EmitFunctionProlog(), clang::CodeGen::CGCXXABI::EmitInstanceFunctionProlog(), EmitLoadOfLValue(), EmitLValueForLambdaField(), clang::CodeGen::Address::emitRawPointer(), EmitStartEHSpec(), EmitTypeCheck(), EmitVariablyModifiedType(), endsWithReturn(), clang::RecordDecl::fields(), FnRetTy, clang::ProfileList::Forbid, clang::XRayInstrKind::FunctionEntry, clang::XRayInstrKind::FunctionExit, clang::CodeGen::CGFunctionInfo::getArgStruct(), clang::Decl::getAttr(), clang::FunctionDecl::getBody(), clang::CXXRecordDecl::getCaptureFields(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), getContext(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), getDebugInfo(), clang::GlobalDecl::getDecl(), clang::LangOptions::getDefaultRoundingMode(), clang::CodeGen::CodeGenModule::getDiags(), clang::CodeGen::CodeGenModule::getHLSLRuntime(), clang::CodeGen::ABIArgInfo::getInAllocaFieldIndex(), clang::CodeGen::ABIArgInfo::getIndirectAlign(), clang::CodeGen::ABIArgInfo::getIndirectByVal(), getJumpDestInCurrentScope(), clang::CodeGen::ABIArgInfo::getKind(), getLangOpts(), getLLVMContext(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::Decl::getNonClosureContext(), clang::Type::getNullability(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), clang::FunctionDecl::getOverloadedOperator(), clang::CXXMethodDecl::getParent(), clang::CodeGen::LValue::getPointer(), clang::CodeGen::CodeGenTypeCache::getPointerAlign(), getPrologueSignature(), clang::SourceLocation::getRawEncoding(), clang::CodeGen::CGFunctionInfo::getReturnInfo(), clang::CodeGen::CGFunctionInfo::getReturnType(), clang::CodeGen::RValue::getScalarVal(), clang::Stmt::getStmtClass(), clang::CodeGen::CodeGenModule::getSYCLRuntime(), getTarget(), clang::CXXMethodDecl::getThisType(), clang::ValueDecl::getType(), clang::CodeGen::Address::getType(), getUBSanFunctionTypeHash(), clang::SanitizerSet::has(), clang::XRayInstrSet::has(), clang::Decl::hasAttr(), clang::SanitizerSet::hasOneOf(), clang::CodeGenOptions::hasSanitizeBinaryMetadata(), clang::CodeGenOptions::hasSanitizeCoverage(), hasScalarEvaluationKind(), clang::HIP, clang::CodeGen::CodeGenModule::imbueXRayAttrs(), clang::CodeGen::ABIArgInfo::InAlloca, clang::CodeGen::ABIArgInfo::Indirect, clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8PtrTy, clang::CodeGen::Address::invalid(), clang::CXXRecordDecl::isCapturelessLambda(), clang::CodeGen::CodeGenModule::isFunctionBlockedFromProfileInstr(), clang::DiagnosticsEngine::isIgnored(), clang::CXXMethodDecl::isImplicitObjectMemberFunction(), clang::CXXRecordDecl::isLambda(), clang::isLambdaCallOperator(), clang::FunctionDecl::isMain(), clang::FunctionDecl::isMSVCRTEntryPoint(), clang::Type::isObjCRetainableType(), clang::Type::isPointerType(), clang::Type::isRecordType(), clang::CodeGen::CGFunctionInfo::isReturnsRetained(), clang::CodeGen::ABIArgInfo::isSRetAfterThis(), clang::CXXMethodDecl::isStatic(), clang::IdentifierInfo::isStr(), clang::Type::isVariablyModifiedType(), clang::Type::isVoidType(), clang::CodeGen::KnownNonNull, LambdaCaptureFields, LambdaThisCaptureField, makeNaturalAddressForPointer(), markAsIgnoreThreadCheckingAtRuntime(), clang::SanitizerSet::Mask, matchesStlAllocatorFn(), clang::NonNull, Offset, clang::OMF_dealloc, clang::OMF_initialize, clang::OpenCL, clang::CodeGenOptions::ProfileNone, PrologueCleanupDepth, clang::DiagnosticsEngine::Report(), ReturnBlock, ReturnValue, ReturnValuePointer, clang::CodeGenOptions::SampleProfileFile, SanOpts, clang::SanitizerSet::set(), ShouldInstrumentFunction(), ShouldSkipSanitizerInstrumentation(), ShouldXRayInstrumentFunction(), clang::ProfileList::Skip, clang::Decl::specific_attrs(), clang::CodeGen::EHScopeStack::stable_begin(), TCK_ConstructorCall, TCK_MemberCall, clang::ToConstrainedExceptMD(), UINT_MAX, clang::FunctionDecl::UsesFPIntrin(), clang::FunctionDecl::usesSEHTry(), and clang::CodeGenOptions::XRayInstrumentationBundle.
Referenced by createAtExitStub(), createTLSAtExitStub(), EmitCfiCheckFail(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), emitInterWarpCopyFunction(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), emitOutlinedFunctionPrologue(), emitShuffleAndReduceFunction(), GenerateBlockFunction(), GenerateCode(), GenerateCopyHelperFunction(), GenerateCXXGlobalCleanUpFunc(), GenerateCXXGlobalInitFunc(), GenerateCXXGlobalVarDeclInitFunc(), generateDestroyHelper(), GenerateDestroyHelperFunction(), GenerateObjCAtomicGetterCopyHelperFunction(), GenerateObjCAtomicSetterCopyHelperFunction(), StartObjCMethod(), and StartThunk().
StartObjCMethod()
void CodeGenFunction::StartObjCMethod (const ObjCMethodDecl * OMD, const ObjCContainerDecl * CD)
StartObjCMethod - Begin emission of an ObjCMethod.
This generates the LLVM function and sets the other context used by CodeGenFunction.
Definition at line 752 of file CGObjC.cpp.
References clang::CodeGen::CodeGenTypes::arrangeObjCMethodDeclaration(), CGM, CurGD, EHStack, clang::CodeGen::CGObjCRuntime::GenerateDirectMethodPrologue(), clang::CodeGen::CGObjCRuntime::GenerateMethod(), getARCCleanupKind(), clang::ObjCMethodDecl::getBeginLoc(), clang::ObjCMethodDecl::getCmdDecl(), clang::ObjCMethodDecl::getEndLoc(), clang::Selector::getIdentifierInfoForSlot(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::Decl::getLocation(), clang::CodeGen::CodeGenModule::getObjCRuntime(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), clang::ObjCMethodDecl::getSelfDecl(), clang::CodeGen::CodeGenModule::getTypes(), clang::Decl::hasAttr(), clang::HiddenVisibility, clang::ObjCMethodDecl::isDirectMethod(), clang::ObjCMethodDecl::isInstanceMethod(), clang::IdentifierInfo::isStr(), clang::Selector::isUnarySelector(), clang::CodeGen::noSystemDebugInfo(), clang::ObjCMethodDecl::param_begin(), clang::ObjCMethodDecl::param_end(), clang::CodeGen::CodeGenModule::SetInternalFunctionAttributes(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributes(), clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition(), and StartFunction().
Referenced by GenerateObjCCtorDtorMethod(), GenerateObjCGetter(), GenerateObjCMethod(), and GenerateObjCSetter().
startOutlinedSEHHelper()
void CodeGenFunction::startOutlinedSEHHelper (CodeGenFunction & ParentCGF, bool IsFilter, const Stmt * OutlinedStmt)
Arrange a function prototype that can be called by Windows exception handling personalities.
On Win64, the prototype looks like: RetTy func(void *EHPtrs, void *ParentFP);
Definition at line 2015 of file CGException.cpp.
References clang::Stmt::getBeginLoc().
Referenced by GenerateSEHFilterFunction(), and GenerateSEHFinallyFunction().
StartThunk()
void CodeGenFunction::StartThunk (llvm::Function * Fn, GlobalDecl GD, const CGFunctionInfo & FnInfo, bool IsUnprototyped)
Definition at line 240 of file CGVTables.cpp.
References clang::CodeGen::CGCXXABI::addImplicitStructorParams(), clang::CodeGen::CGCXXABI::buildThisParam(), clang::Type::castAs(), CGM, clang::CodeGen::ApplyDebugLocation::CreateArtificial(), clang::CodeGen::ApplyDebugLocation::CreateEmpty(), CurCodeDecl, CurFuncDecl, CurFuncIsThunk, CurGD, clang::CodeGen::CGCXXABI::EmitInstanceFunctionProlog(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::GlobalDecl::getDecl(), clang::Decl::getLocation(), clang::CXXMethodDecl::getThisType(), clang::ValueDecl::getType(), clang::CodeGen::CGCXXABI::hasMostDerivedReturn(), clang::CodeGen::CGCXXABI::HasThisReturn(), clang::FunctionDecl::param_begin(), clang::FunctionDecl::param_end(), StartFunction(), clang::ASTContext::VoidPtrTy, and clang::ASTContext::VoidTy.
Referenced by generateThunk().
stripCond()
const Expr * CodeGenFunction::stripCond (const Expr * C) static
Ignore parentheses and logical-NOT to track conditions consistently.
Strip parentheses and simplistic logical-NOT operators.
Definition at line 1944 of file CodeGenFunction.cpp.
Referenced by isInstrumentedCondition().
SVEBuiltinMemEltTy()
llvm::Type * CodeGenFunction::SVEBuiltinMemEltTy (const SVETypeFlags & TypeFlags)
SVEBuiltinMemEltTy - Returns the memory element type for this memory access builtin.
Only required if it can't be inferred from the base pointer operand.
Definition at line 9694 of file CGBuiltin.cpp.
References clang::SVETypeFlags::getMemEltType().
tryEmitAsConstant() [1/2]
CodeGenFunction::ConstantEmission CodeGenFunction::tryEmitAsConstant (const MemberExpr * ME)
Definition at line 1819 of file CGExpr.cpp.
References tryEmitAsConstant(), and tryToConvertMemberExprToDeclRefExpr().
tryEmitAsConstant() [2/2]
CodeGenFunction::ConstantEmission CodeGenFunction::tryEmitAsConstant (DeclRefExpr * refExpr)
Try to emit a reference to the given value without producing it as an l-value.
This is just an optimization, but it avoids us needing to emit global copies of variables if they're named without triggering a formal use in a context where we can't emit a direct reference to them, for instance if a block or lambda or a member of a local class uses a const int variable or constexpr variable from an enclosing function.
Definition at line 1721 of file CGExpr.cpp.
References CEK_AsReferenceOnly, CEK_AsValueOnly, CEK_None, CGM, checkVarTypeForConstantEmission(), CurCodeDecl, clang::APValue::LValueBase::dyn_cast(), clang::CodeGen::ConstantEmitter::emitAbstract(), EmitDeclRefExprDbgValue(), clang::Expr::EvaluateAsLValue(), clang::Expr::EvaluateAsRValue(), clang::CodeGen::CodeGenFunction::ConstantEmission::forReference(), clang::CodeGen::CodeGenFunction::ConstantEmission::forValue(), getContext(), clang::DeclRefExpr::getDecl(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::DeclRefExpr::getLocation(), clang::APValue::getLValueBase(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::Expr::EvalStatus::HasSideEffects, clang::APValue::isLValue(), clang::DeclRefExpr::refersToEnclosingVariableOrCapture(), clang::Expr::EvalResult::Val, and clang::dataflow::var().
Referenced by tryEmitARCRetainLoadOfScalar(), and tryEmitAsConstant().
TypeOfSelfObject()
QualType CodeGenFunction::TypeOfSelfObject ()
TypeOfSelfObject - Return type of object that this self represents.
Definition at line 1753 of file CGObjC.cpp.
References CurFuncDecl, getContext(), clang::ObjCObjectPointerType::getPointeeType(), clang::ObjCMethodDecl::getSelfDecl(), and clang::ValueDecl::getType().
Referenced by emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), emitStructSetterCall(), GenerateObjCCtorDtorMethod(), generateObjCGetterBody(), and generateObjCSetterBody().
unprotectFromPeepholes()
void CodeGenFunction::unprotectFromPeepholes (PeepholeProtection protection)
Definition at line 2773 of file CodeGenFunction.cpp.
Referenced by clang::CodeGen::CodeGenFunction::OpaqueValueMappingData::unbind().
unregisterGlobalDtorWithUnAtExit()
llvm::Value * CodeGenFunction::unregisterGlobalDtorWithUnAtExit (llvm::Constant * dtorStub)
Call unatexit() with function dtorStub.
Definition at line 364 of file CGDeclCXX.cpp.
References CGM, clang::CodeGen::CodeGenModule::CreateRuntimeFunction(), EmitNounwindRuntimeCall(), clang::CodeGen::CodeGenTypeCache::IntTy, and clang::CodeGen::CodeGenTypeCache::VoidTy.
vectorWrapScalar16()
Value * CodeGenFunction::vectorWrapScalar16 (llvm::Value * Op)
Definition at line 9682 of file CGBuiltin.cpp.
VolatilizeTryBlocks()
void CodeGenFunction::VolatilizeTryBlocks (llvm::BasicBlock * BB, llvm::SmallPtrSet< llvm::BasicBlock *, 10 > & V)
Definition at line 1696 of file CGException.cpp.
References Builder, SEHTryEpilogueStack, and V.
Friends And Related Function Documentation
CGCXXABI
friend class CGCXXABI friend
Definition at line 260 of file CodeGenFunction.h.
Member Data Documentation
AllocaInsertPt
llvm::AssertingVH<llvm::Instruction> clang::CodeGen::CodeGenFunction::AllocaInsertPt
AllocaInsertPoint - This is an instruction in the entry block before which we prefer to insert allocas.
Definition at line 427 of file CodeGenFunction.h.
Referenced by emitOffloadingArrays(), emitTargetCallKernelLaunch(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), FinishFunction(), generateObjCSetterBody(), getPostAllocaInsertPoint(), clang::CodeGen::CGOpenMPRuntime::getThreadID(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::InlinedRegionBodyRAII::InlinedRegionBodyRAII(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OutlinedRegionBodyRAII::OutlinedRegionBodyRAII(), recoverAddrOfEscapedLocal(), clang::CodeGen::CGOpenMPRuntime::setLocThreadIdInsertPt(), StartFunction(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::InlinedRegionBodyRAII::~InlinedRegionBodyRAII(), and clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OutlinedRegionBodyRAII::~OutlinedRegionBodyRAII().
AutoreleaseResult
bool clang::CodeGen::CodeGenFunction::AutoreleaseResult = false
In ARC, whether we should autorelease the return value.
Definition at line 588 of file CodeGenFunction.h.
Referenced by EmitCallAndReturnForThunk(), EmitFunctionEpilog(), GenerateObjCCtorDtorMethod(), generateObjCGetterBody(), and StartFunction().
BlockInfo
const CodeGen::CGBlockInfo* clang::CodeGen::CodeGenFunction::BlockInfo = nullptr
Definition at line 661 of file CodeGenFunction.h.
Referenced by EmitFunctionEpilog(), EmitLambdaBlockInvokeBody(), EmitParmDecl(), GenerateBlockFunction(), GetAddrOfBlockDecl(), getCaptureFieldType(), LoadBlockStruct(), and setBlockContextParameter().
BlockPointer
llvm::Value* clang::CodeGen::CodeGenFunction::BlockPointer = nullptr
Definition at line 662 of file CodeGenFunction.h.
Referenced by GenerateBlockFunction(), LoadBlockStruct(), and setBlockContextParameter().
Builder
CGBuilderTy clang::CodeGen::CodeGenFunction::Builder
Definition at line 294 of file CodeGenFunction.h.
Referenced by AdjustObjCObjectType(), clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), clang::CodeGen::CallArgList::allocateArgumentMemory(), clang::CodeGen::ApplyDebugLocation::ApplyDebugLocation(), clang::CodeGen::ApplyInlineDebugLocation::ApplyInlineDebugLocation(), ApplyNonVirtualAndVirtualOffset(), BuildAppleKextVirtualCall(), castToBase(), castValueToType(), CheckAggExprForMemSetUse(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), CoerceIntOrPtrToIntOrPtr(), complexTempStructure(), createAtExitStub(), createCleanupActiveFlag(), CreateCoercedLoad(), CreateCoercedStore(), CreateMultiVersionResolverReturn(), createPlaceholderSlot(), createRuntimeShuffleFunction(), createTLSAtExitStub(), clang::CodeGen::CatchRetScope::Emit(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OMPAllocateCleanupTy::Emit(), EmitAbs(), emitAddressAtOffset(), emitAddrOfFieldStorage(), emitAddrOfImagComponent(), emitAddrOfRealComponent(), emitAddrOfZeroSizeField(), EmitAggregateCopy(), EmitAggregateStore(), clang::CodeGen::ReductionCodeGen::emitAggregateType(), emitAlignmentAssumption(), emitAlignmentAssumptionCheck(), EmitAMDGPUDevicePrintfCallExpr(), EmitAnnotationCall(), emitARCCopyOperation(), EmitARCDestroyStrong(), EmitARCInitWeak(), emitARCOperationAfterCall(), EmitARCRelease(), EmitARCRetainAutorelease(), EmitARCRetainBlock(), emitARCStoreOperation(), EmitARCStoreStrongCall(), emitARCValueOperation(), emitArgumentDemotion(), EmitArrayDelete(), emitArrayDestroy(), emitArrayLength(), EmitArraySubscriptExpr(), emitArraySubscriptGEP(), EmitArrayToPointerDecay(), emitAtomicCmpXchg(), EmitAtomicCmpXchg128ForMSIntrin(), emitAtomicCmpXchgFailureSet(), EmitAtomicCmpXchgForMSIntrin(), EmitAtomicDecrementValue(), EmitAtomicExpr(), EmitAtomicIncrementValue(), EmitAtomicOp(), EmitAtomicStore(), emitAutoreleasedReturnValueMarker(), EmitAutoVarAlloca(), EmitAutoVarInit(), clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), EmitBinaryAtomicPost(), emitBinaryBuiltin(), emitBinaryExpMaybeConstrainedFPBuiltin(), EmitBitfieldConversionCheck(), EmitBitTestIntrinsic(), EmitBlock(), EmitBlockAfterUses(), emitBlockByrefAddress(), EmitBlockCallExpr(), EmitBranch(), EmitBranchOnBoolExpr(), EmitBuiltinAvailable(), emitByrefStructureInit(), EmitCall(), EmitCallArg(), emitCallMaybeConstrainedFPBuiltin(), clang::CodeGen::CGOpenMPRuntime::emitCancellationPointCall(), emitCapturedStmtCall(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::EmitCaptureStmt(), emitCatchDispatchBlock(), emitCatchPadBlock(), EmitCfiCheckFail(), EmitCfiSlowPathCheck(), EmitCheck(), EmitCheckedMixedSignMultiply(), EmitCheckedUnsignedMultiplySignedResult(), emitCheckHandlerCall(), EmitCheckSourceLocation(), EmitCheckValue(), EmitCleanup(), emitCmdValueForGetterSetterBody(), EmitCMSEClearRecord(), EmitCommonNeonSISDBuiltinExpr(), EmitComplexPrePostIncDec(), EmitConditionalOperatorLValue(), EmitCoroutineIntrinsic(), EmitCountedByFieldExpr(), clang::CodeGen::CGOpenMPRuntime::emitCriticalRegion(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), EmitCtorPrologue(), EmitCXXAggrConstructorCall(), EmitCXXDeleteExpr(), EmitCXXGuardedInitBranch(), EmitCXXNewAllocSize(), EmitCXXNewExpr(), EmitCXXPseudoDestructorExpr(), EmitDeclRefLValue(), EmitDelegateCallArg(), EmitDeleteCall(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), emitDependData(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElements(), clang::CodeGen::CGOpenMPRuntime::emitDepobjElementsSizes(), emitDestroy(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), EmitDestructorBody(), emitDeviceID(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitDoacrossOrdered(), EmitDynamicCast(), EmitDynamicCastToNull(), emitDynamicTlsInitialization(), emitDynamicTlsInitializationCall(), emitDynCGGroupMem(), clang::CodeGen::CGOpenMPRuntime::emitErrorCall(), EmitExtVectorElementExpr(), EmitExtVectorElementLValue(), EmitFAbs(), EmitFieldAnnotations(), EmitFieldSYCLAnnotations(), emitFilterDispatchBlock(), clang::CodeGen::CGOpenMPRuntime::emitFlush(), clang::CodeGen::CGOpenMPRuntime::emitForDispatchInit(), emitForStaticInitCall(), emitFPIntBuiltin(), emitFrexpBuiltin(), EmitFromInt(), EmitFromMemory(), EmitFunctionEpilog(), EmitFunctionProlog(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), EmitGlobalVarDeclLValue(), clang::CodeGen::CGObjCRuntime::EmitInitOfCatchParam(), EmitIntelFPGAFieldAnnotations(), emitInterWarpCopyFunction(), EmitInvariantStart(), EmitISOVolatileLoad(), EmitISOVolatileStore(), emitIsPlatformVersionAtLeast(), EmitIvarOffsetAsPointerDiff(), EmitLabel(), EmitLandingPad(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalUpdate(), EmitLifetimeEnd(), EmitLifetimeStart(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), EmitllvmFAbs(), EmitLoadOfBitfieldLValue(), EmitLoadOfExtVectorElementLValue(), EmitLoadOfLValue(), EmitLoadOfPointer(), EmitLoadOfReference(), EmitLoadOfScalar(), EmitLValueForField(), EmitMaterializeTemporaryExpr(), EmitMatrixSubscriptExpr(), emitMaybeConstrainedFPToIntRoundBuiltin(), EmitMemberInitializer(), clang::CodeGen::CGCXXABI::EmitMemberPointerComparison(), clang::CodeGen::CGCXXABI::EmitMemberPointerIsNotNull(), EmitMustTailThunk(), EmitNewArrayInitializer(), EmitNonNullRValueCheck(), emitNonZeroVLAInit(), EmitNoreturnRuntimeCallOrInvoke(), EmitNullabilityCheck(), EmitNullBaseClassInitialization(), EmitNullInitialization(), clang::CodeGen::CGOpenMPRuntime::emitNumTeamsClause(), clang::CodeGen::CGOpenMPRuntime::emitNumTeamsForTargetDirective(), clang::CodeGen::CGOpenMPRuntime::emitNumThreadsClause(), clang::CodeGen::CGOpenMPRuntime::emitNumThreadsForTargetDirective(), EmitObjCAutoreleasePoolPop(), EmitObjCBoxedExpr(), EmitObjCMessageExpr(), EmitObjCRelease(), emitObjCValueOperation(), emitOffloadingArrays(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), emitOMPArraySectionBase(), EmitOMPArraySectionExpr(), emitOMPAtomicCompareExpr(), clang::CodeGen::CGOpenMPRuntimeGPU::emitOutlinedFunctionCall(), EmitOverflowCheckedAbs(), EmitOverflowIntrinsic(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), EmitParmDecl(), emitPartialArrayDestroy(), emitPointerArithmetic(), EmitPointerWithAlignment(), emitPostUpdateForReductionClause(), emitPPCLoadReserveIntrinsic(), emitPreserveStructAccess(), emitPrivatesInit(), EmitPromotedValue(), emitRangedBuiltin(), emitRestoreIP(), EmitReturnBlock(), EmitReturnValueCheck(), clang::CodeGen::emitRoundPointerUpToAlignment(), EmitSanitizerStatReport(), EmitScalarFMAExpr(), EmitScalarRangeCheck(), EmitSEHAbnormalTermination(), EmitSEHExceptionCode(), EmitSEHExceptionCodeSave(), EmitSehScope(), emitShuffleAndReduceFunction(), EmitSignBit(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), EmitStoreOfScalar(), EmitStoreThroughBitfieldLValue(), EmitStoreThroughExtVectorComponentLValue(), EmitStoreThroughLValue(), emitStructSetterCall(), EmitSYCLAnnotationCall(), EmitSynthesizedCXXCopyCtorCall(), EmitSystemZIntrinsicWithCC(), emitTargetCallFallback(), emitTargetCallKernelLaunch(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskLoopCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFini(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups(), clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskwaitCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskyieldCall(), clang::CodeGen::CGOpenMPRuntime::emitTeamsCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsCall(), emitTernaryBuiltin(), emitTernaryMaybeConstrainedFPBuiltin(), clang::CodeGen::CGOpenMPRuntime::emitThreadLimitClause(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarInit(), emitTlsGuardCheck(), EmitToInt(), EmitToMemory(), EmitTrapCall(), EmitTrapCheck(), EmitTypeCheck(), EmitTypeidFromVTable(), EmitTypeMetadataCodeForVCall(), clang::CodeGen::CGOpenMPRuntime::emitUDMapperArrayInitOrDel(), EmitUnPromotedValue(), EmitUnreachable(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), clang::CodeGen::EmitVAArgInstr(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), EmitVariablyModifiedType(), clang::CodeGen::emitVoidPtrDirectVAArg(), clang::CodeGen::emitVoidPtrVAArg(), EmitVTablePtrCheck(), EmitVTablePtrCheckForCast(), EmitVTableTypeCheckedLoad(), emitWasmCatchPadBlock(), emitWriteback(), emitWritebackArg(), EmitX86_64VAArgFromMemory(), EmitX86BitTestIntrinsic(), EmitX86CompressExpand(), EmitX86CompressStore(), EmitX86ConvertIntToFp(), EmitX86CvtF16ToFloatExpr(), EmitX86ExpandLoad(), EmitX86FMAExpr(), EmitX86FunnelShift(), EmitX86MaskedLoad(), EmitX86MaskedStore(), EmitX86MaskLogic(), EmitX86Muldq(), EmitX86ScalarSelect(), EmitX86Select(), EmitX86SExtMask(), EmitX86Ternlog(), clang::CodeGen::CodeGenFunction::FinallyInfo::enter(), EnterStructPointerForCoercedAccess(), clang::CodeGen::CodeGenFunction::FinallyInfo::exit(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::FinalizeOMPRegion(), findDominatingStoreToReturnValue(), FinishFunction(), forConstantArrayExpansion(), clang::CodeGen::CallArgList::freeArgumentMemory(), GenerateBlockFunction(), GenerateCode(), GenerateCopyHelperFunction(), GenerateCXXGlobalCleanUpFunc(), GenerateCXXGlobalInitFunc(), GenerateDestroyHelperFunction(), generateObjCGetterBody(), generateObjCSetterBody(), GenerateSEHFilterFunction(), GenerateVarArgsThunk(), clang::CodeGen::CodeGenModule::GenKernelArgMetadata(), GetAddressOfBaseClass(), GetAddressOfDerivedClass(), GetAddressOfDirectBaseInCompleteClass(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), GetAddrOfBlockDecl(), clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), getArrayIndexingBound(), clang::CodeGen::getCXXDestructorImplicitParam(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), getEHResumeBlock(), getExceptionFromSlot(), getFuncletEHDispatchBlock(), getGEPIndicesToField(), clang::CodeGen::CGOpenMPRuntimeGPU::getGPUNumThreads(), clang::CodeGen::CGOpenMPRuntimeGPU::getKmpcAllocShared(), getMaskVecValue(), getNVPTXLaneID(), getNVPTXWarpID(), clang::CodeGen::CGOpenMPRuntimeGPU::getParameterAddress(), getPointerAndSize(), getSelectorFromSlot(), clang::CodeGen::CGOpenMPRuntime::getTaskReductionItem(), getTerminateFunclet(), getTerminateHandler(), getTerminateLandingPad(), clang::CodeGen::CGOpenMPRuntime::getThreadID(), getVLASize(), GetVTablePtr(), GetVTTParameter(), HaveInsertPoint(), InitCatchParam(), initializeAlloca(), InitializeVTablePointer(), clang::CodeGen::CodeGenFunction::LexicalScope::LexicalScope(), clang::CodeGen::CGCXXABI::loadIncomingCXXThis(), LoadPassedObjectSize(), MakeBinaryAtomicValue(), maybeCreateMCDCCondBitmap(), maybeResetMCDCCondBitmap(), maybeUpdateMCDCCondBitmap(), maybeUpdateMCDCTestVectorBitmap(), mergeAddressesInConditionalExpr(), clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), PerformReturnAdjustment(), performTypeAdjustment(), protectFromPeepholes(), clang::CodeGen::CGCXXABI::ReadArrayCookie(), recoverAddrOfEscapedLocal(), ResolveAllBranchFixups(), clang::CodeGen::DominatingLLVMValue::restore(), clang::CodeGen::DominatingLLVMValue::save(), setBlockContextParameter(), SetFastMathFlags(), clang::CodeGen::CGOpenMPRuntime::setLocThreadIdInsertPt(), SetupCleanupBlockActivation(), clang::CodeGen::CodeGenFunction::OMPMapVars::setVarAddr(), shuffleAndStore(), SimplifyCleanupEntry(), StartFunction(), tryEmitFusedAutoreleaseOfResult(), tryRemoveRetainOfSelf(), tryUseTestFPKind(), VolatilizeTryBlocks(), wrapWithBPFPreserveStaticOffset(), clang::CodeGen::ApplyDebugLocation::~ApplyDebugLocation(), clang::CodeGen::ApplyInlineDebugLocation::~ApplyInlineDebugLocation(), and clang::CodeGen::CodeGenFunction::LexicalScope::~LexicalScope().
Bypasses
VarBypassDetector clang::CodeGen::CodeGenFunction::Bypasses
Definition at line 298 of file CodeGenFunction.h.
Referenced by EmitAutoVarAlloca(), and GenerateCode().
CapturedStmtInfo
CGCapturedStmtInfo* clang::CodeGen::CodeGenFunction::CapturedStmtInfo = nullptr
Definition at line 528 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), clang::CodeGen::CodeGenFunction::CGCapturedStmtRAII::CGCapturedStmtRAII(), clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), clang::CodeGen::CGOpenMPRuntime::emitCancelCall(), clang::CodeGen::CGOpenMPRuntime::emitCancellationPointCall(), EmitDeclRefLValue(), clang::CodeGen::CGOpenMPRuntimeGPU::emitFunctionProlog(), clang::CodeGen::CGOpenMPRuntime::emitInlinedDirective(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskwaitCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskyieldCall(), clang::CodeGen::CGOpenMPRuntime::emitThreadIDAddress(), clang::CodeGen::CGOpenMPRuntime::getThreadID(), and clang::CodeGen::CodeGenFunction::CGCapturedStmtRAII::~CGCapturedStmtRAII().
CGM
CodeGenModule& clang::CodeGen::CodeGenFunction::CGM
Definition at line 286 of file CodeGenFunction.h.
Referenced by AddInitializerToStaticVarDecl(), AddVariableConstraints(), AlwaysEmitXRayCustomEvents(), AlwaysEmitXRayTypedEvents(), ApplyNonVirtualAndVirtualOffset(), BuildAppleKextVirtualCall(), BuildAppleKextVirtualDestructorCall(), BuildBlockRelease(), BuildFunctionArgList(), CalculateCookiePadding(), CallBeginCatch(), callSpecialFunction(), canEmitDelegateCallArgs(), canEmitSpuriousReferenceToVariable(), CheckAtomicAlignment(), checkIfFunctionMustProgress(), checkIfLoopMustProgress(), checkTargetFeatures(), CoerceIntOrPtrToIntOrPtr(), commonEmitCXXMemberOrOperatorCall(), complexTempStructure(), ConstantFoldsToSimpleInteger(), ConvertType(), ConvertTypeForMem(), createAtExitStub(), CreateCoercedLoad(), CreateCoercedStore(), createCoroData(), createRuntimeShuffleFunction(), createTLSAtExitStub(), defaultInitNonTrivialCStructVar(), emitAddrOfFieldStorage(), EmitAggregateCopy(), emitAlignmentAssumption(), EmitAMDGPUDevicePrintfCallExpr(), EmitAnnotationCall(), EmitARCAutorelease(), EmitARCAutoreleaseReturnValue(), emitARCCopyOperation(), EmitARCCopyWeak(), EmitARCDestroyStrong(), EmitARCDestroyWeak(), EmitARCInitWeak(), EmitARCIntrinsicUse(), emitARCLoadOperation(), EmitARCLoadWeak(), EmitARCLoadWeakRetained(), EmitARCMoveWeak(), EmitARCNoopIntrinsicUse(), EmitARCReclaimReturnedObject(), EmitARCRelease(), EmitARCRetainAutoreleaseNonBlock(), EmitARCRetainAutoreleaseReturnValue(), EmitARCRetainBlock(), EmitARCRetainNonBlock(), emitARCStoreOperation(), EmitARCStoreStrongCall(), EmitARCStoreWeak(), emitARCValueOperation(), EmitArrayDelete(), EmitArraySubscriptExpr(), EmitArrayToPointerDecay(), EmitAtomicExpr(), emitAtomicLibcall(), EmitAtomicOp(), EmitAtomicStore(), emitAutoreleasedReturnValueMarker(), EmitAutoVarAlloca(), EmitAutoVarCleanups(), EmitAutoVarDecl(), EmitAutoVarInit(), clang::CodeGen::CGOpenMPRuntime::emitBarrierCall(), EmitBaseInitializer(), emitBinaryBuiltin(), emitBinaryExpMaybeConstrainedFPBuiltin(), EmitBinaryOperatorLValue(), EmitBlockCallExpr(), EmitBlockCopyAndAutorelease(), EmitBlockLiteral(), EmitBranchOnBoolExpr(), EmitBranchToCounterBlock(), EmitBuiltinAvailable(), emitByrefStructureInit(), EmitCall(), EmitCallAndReturnForThunk(), emitCallMaybeConstrainedFPBuiltin(), EmitCastLValue(), emitCatchDispatchBlock(), EmitCfiCheckFail(), EmitCfiCheckStub(), EmitCfiSlowPathCheck(), EmitCheck(), emitCheckHandlerCall(), EmitCheckSourceLocation(), EmitCheckTypeDescriptor(), EmitCMSEClearRecord(), EmitComplexAssignmentLValue(), EmitComplexPrePostIncDec(), EmitCompoundLiteralLValue(), EmitConditionalOperatorLValue(), EmitConstructorBody(), EmitCoroutineIntrinsic(), emitCPPObjectAtomicGetterCall(), emitCPPObjectAtomicSetterCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitCriticalRegion(), EmitCtorPrologue(), EmitCUDAKernelCallExpr(), EmitCXXConstructorCall(), EmitCXXDestructorCall(), EmitCXXGlobalVarDeclInit(), EmitCXXGuardedInit(), EmitCXXGuardedInitBranch(), EmitCXXMemberCallExpr(), EmitCXXMemberDataPointerAddress(), EmitCXXMemberOrOperatorCall(), EmitCXXMemberPointerCallExpr(), EmitCXXNewAllocSize(), EmitCXXNewExpr(), EmitCXXThrowExpr(), EmitCXXTypeidExpr(), EmitCXXUuidofExpr(), EmitDecl(), EmitDeclDestroy(), EmitDeclInit(), EmitDeclRefExprDbgValue(), EmitDeclRefLValue(), emitDeclTargetVarDeclLValue(), EmitDelegateCXXConstructorCall(), EmitDelegatingCXXConstructorCall(), EmitDeleteCall(), emitDependData(), EmitDestroyingObjectDelete(), EmitDestructorBody(), EmitDirectCallee(), EmitDynamicCast(), EmitDynamicCastToNull(), emitDynamicTlsInitialization(), emitDynamicTlsInitializationCall(), EmitEndEHSpec(), EmitExtVectorElementLValue(), EmitFAbs(), EmitFieldAnnotations(), EmitFieldSYCLAnnotations(), emitFilterDispatchBlock(), clang::CodeGen::CGOpenMPRuntime::emitFlush(), emitForStaticInitCall(), EmitForwardingCallToLambda(), emitFPIntBuiltin(), emitFrexpBuiltin(), EmitFunctionDeclLValue(), EmitFunctionEpilog(), clang::CodeGen::CGOpenMPRuntimeGPU::emitFunctionProlog(), EmitFunctionProlog(), emitGlobalDtorWithTLRegDtor(), EmitGlobalVarDeclLValue(), EmitInheritedCXXConstructorCall(), emitInitWithReductionInitializer(), EmitInlinedInheritingCXXConstructorCall(), EmitIntelFPGAFieldAnnotations(), emitInterWarpCopyFunction(), EmitInvariantStart(), emitIsPlatformVersionAtLeast(), EmitIvarOffset(), EmitKCFIOperandBundle(), EmitLabel(), EmitLambdaBlockInvokeBody(), EmitLambdaInAllocaCallOpBody(), EmitLambdaInAllocaImplFn(), EmitLambdaStaticInvokeBody(), EmitLandingPad(), EmitLifetimeEnd(), EmitLifetimeStart(), EmitllvmFAbs(), EmitLoadOfBitfieldLValue(), EmitLoadOfExtVectorElementLValue(), EmitLoadOfGlobalRegLValue(), EmitLoadOfLValue(), EmitLoadOfReference(), EmitLoadOfReferenceLValue(), EmitLoadOfScalar(), EmitLValueForField(), EmitLValueForFieldInitialization(), EmitLValueForIvar(), EmitMaterializeTemporaryExpr(), emitMaybeConstrainedFPToIntRoundBuiltin(), EmitMemberExpr(), EmitMemberInitializer(), EmitMustTailThunk(), EmitNewArrayInitializer(), EmitNewDeleteCall(), EmitNonNullRValueCheck(), EmitNullBaseClassInitialization(), EmitNullInitialization(), clang::CodeGen::CGOpenMPRuntime::emitNumTeamsClause(), EmitNVPTXDevicePrintfCallExpr(), EmitObjCAlloc(), EmitObjCAllocInit(), EmitObjCAllocWithZone(), EmitObjCAutorelease(), EmitObjCAutoreleasePoolCleanup(), EmitObjCAutoreleasePoolPop(), EmitObjCAutoreleasePoolPush(), EmitObjCBoxedExpr(), EmitObjCEncodeExprLValue(), EmitObjCMessageExpr(), EmitObjCMRRAutoreleasePoolPop(), EmitObjCMRRAutoreleasePoolPush(), EmitObjCProtocolExpr(), EmitObjCRelease(), EmitObjCRetainNonBlock(), EmitObjCSelectorExpr(), EmitObjCSelectorLValue(), EmitObjCStringLiteral(), emitObjCValueOperation(), EmitObjectDelete(), emitOffloadingArrays(), emitOMPArraySectionBase(), EmitOMPArraySectionExpr(), emitOMPAtomicCaptureExpr(), emitOMPAtomicCompareExpr(), emitOMPAtomicReadExpr(), emitOMPAtomicUpdateExpr(), emitOMPAtomicWriteExpr(), EmitOpenMPDevicePrintfCallExpr(), emitOptimizedARCReturnCall(), emitOutlinedFunctionPrologue(), EmitOverflowIntrinsic(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), EmitParmDecl(), emitPointerArithmetic(), EmitPointerWithAlignment(), emitPreserveStructAccess(), emitRangedBuiltin(), emitReductionCombiner(), emitRestoreIP(), emitRTtypeidCall(), EmitSanitizerStatReport(), EmitScalarFMAExpr(), EmitScalarInit(), EmitScalarRangeCheck(), EmitSEHExceptionCodeSave(), EmitSignBit(), EmitSimpleOMPExecutableDirective(), EmitStartEHSpec(), EmitStaticVarDecl(), EmitStoreOfScalar(), EmitStoreThroughBitfieldLValue(), EmitStoreThroughGlobalRegLValue(), EmitStoreThroughLValue(), EmitStringLiteralLValue(), emitStructSetterCall(), EmitSYCLAnnotationCall(), EmitSynthesizedCXXCopyCtorCall(), EmitSystemZIntrinsicWithCC(), emitTargetCallKernelLaunch(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataCalls(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), emitTargetTeamsLoopCodegenStatus(), clang::CodeGen::CGOpenMPRuntime::emitTaskwaitCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskyieldCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsOutlinedFunction(), clang::CodeGen::CGCXXABI::emitTerminateForUnexpectedException(), emitTernaryBuiltin(), emitTernaryMaybeConstrainedFPBuiltin(), clang::CodeGen::CGOpenMPRuntime::emitThreadLimitClause(), EmitThreadPrivateVarDeclLValue(), EmitTrapCall(), EmitTrapCheck(), EmitTypeCheck(), EmitTypeidFromVTable(), EmitTypeMetadataCodeForVCall(), EmitUnaryOpLValue(), EmitVAArg(), clang::CodeGen::CGObjCRuntime::EmitValueForIvarAtOffset(), EmitVarAnnotations(), EmitVarDecl(), clang::CodeGen::emitVoidPtrDirectVAArg(), clang::CodeGen::emitVoidPtrVAArg(), EmitVTableAssumptionLoad(), EmitVTableAssumptionLoads(), EmitVTablePtrCheck(), EmitVTablePtrCheckForCast(), EmitVTableTypeCheckedLoad(), emitWasmCatchPadBlock(), emitWritebackArg(), EmitX86CompressExpand(), EmitX86CompressStore(), EmitX86ConvertIntToFp(), EmitX86CvtF16ToFloatExpr(), EmitX86ExpandLoad(), EmitX86FMAExpr(), EmitX86FunnelShift(), EmitX86Ternlog(), EnterDtorCleanups(), EnterStructPointerForCoercedAccess(), EvaluateExprAsBool(), FinishFunction(), GenerateBlockFunction(), GenerateCode(), GenerateCopyHelperFunction(), GenerateCXXGlobalCleanUpFunc(), GenerateCXXGlobalInitFunc(), GenerateCXXGlobalVarDeclInitFunc(), generateDestroyHelper(), GenerateDestroyHelperFunction(), GenerateObjCAtomicGetterCopyHelperFunction(), GenerateObjCAtomicSetterCopyHelperFunction(), GenerateObjCCtorDtorMethod(), GenerateObjCGetter(), generateObjCGetterBody(), GenerateObjCSetter(), generateObjCSetterBody(), generateThunk(), GenerateVarArgsThunk(), clang::CodeGen::EHPersonality::get(), GetAddressOfBaseClass(), GetAddressOfDerivedClass(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), getARCCleanupKind(), getAsmSrcLocInfo(), getBadCastFn(), getBadTypeidFn(), getBlockByrefInfo(), getContext(), getEHResumeBlock(), getGEPIndicesToField(), clang::CodeGen::CGOpenMPRuntimeGPU::getGPUNumThreads(), getIntrinsic(), getInvokeDestImpl(), getItaniumDynamicCastFn(), getLangOpts(), getLLVMContext(), getNVPTXLaneID(), getNVPTXWarpID(), getPrologueSignature(), getTargetHooks(), getTerminateFunclet(), getTerminateHandler(), getTerminateLandingPad(), getTypes(), getUBSanFunctionTypeHash(), GetVTablePtr(), GetVTTParameter(), InitCatchParam(), initializeAlloca(), InitializeVTablePointer(), InitializeVTablePointers(), isMCDCCoverageEnabled(), isProvablyNonNull(), LoadCXXThisAddress(), loadToBegin(), LValueIsSuitableForInlineAtomic(), MakeAddrLValue(), makeNaturalAddressForPointer(), MakeNaturalAlignAddrLValue(), MakeRawAddrLValue(), needsEHCleanup(), clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast(), PerformReturnAdjustment(), performTypeAdjustment(), clang::CodeGen::CGCallee::prepareConcreteCallee(), pushTemporaryCleanup(), recoverAddrOfEscapedLocal(), registerGlobalDtorWithAtExit(), registerGlobalDtorWithLLVM(), clang::CodeGen::DominatingLLVMValue::save(), setBlockContextParameter(), SetDivFPAccuracy(), SetSqrtFPAccuracy(), ShouldEmitVTableTypeCheckedLoad(), ShouldInstrumentFunction(), shouldUseFusedARCCalls(), ShouldXRayInstrumentFunction(), StartFunction(), StartObjCMethod(), StartThunk(), tryEmitAsConstant(), tryEmitFusedAutoreleaseOfResult(), tryEmitSpecializedAllocInit(), tryGenerateSpecializedMessageSend(), tryRemoveRetainOfSelf(), tryUseTestFPKind(), unregisterGlobalDtorWithUnAtExit(), wrapWithBPFPreserveStaticOffset(), and ~CodeGenFunction().
CurAwaitSuspendWrapper
AwaitSuspendWrapperInfo clang::CodeGen::CodeGenFunction::CurAwaitSuspendWrapper
Definition at line 383 of file CodeGenFunction.h.
Referenced by EmitCoroutineIntrinsic().
CurCodeDecl
const Decl* clang::CodeGen::CodeGenFunction::CurCodeDecl = nullptr
CurCodeDecl - This is the inner-most code context, which includes blocks.
Definition at line 350 of file CodeGenFunction.h.
Referenced by canEmitSpuriousReferenceToVariable(), clang::CodeGen::CGObjCRuntime::canMessageReceiverBeNull(), checkTargetFeatures(), EmitCall(), EmitDeclRefLValue(), EmitFunctionEpilog(), EmitFunctionProlog(), EmitInheritedCXXConstructorCall(), EmitLambdaBlockInvokeBody(), EmitLValueForLambdaField(), EmitObjCMessageExpr(), EmitPredefinedLValue(), emitPrivatesInit(), EmitReturnValueCheck(), EmitTrapCheck(), FinishFunction(), FinishThunk(), clang::CodeGen::EHPersonality::get(), clang::CodeGen::getCXXDestructorImplicitParam(), GetVTTParameter(), clang::CodeGen::CodeGenFunction::InlinedInheritingConstructorScope::InlinedInheritingConstructorScope(), LoadObjCSelf(), StartFunction(), StartThunk(), tryEmitAsConstant(), and tryRemoveRetainOfSelf().
CurCoro
CGCoroInfo clang::CodeGen::CodeGenFunction::CurCoro
Definition at line 367 of file CodeGenFunction.h.
Referenced by createCoroData(), EmitCoawaitExpr(), EmitCoawaitLValue(), EmitCoroutineIntrinsic(), EmitCoyieldExpr(), EmitCoyieldLValue(), inSuspendBlock(), and isCoroutine().
CurFn
llvm::Function* clang::CodeGen::CodeGenFunction::CurFn = nullptr
Definition at line 353 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::checkAndEmitLastprivateConditional(), clang::CodeGen::CGOpenMPRuntime::checkAndEmitSharedLastprivateConditional(), clang::CodeGen::CGOpenMPRuntime::clearLocThreadIdInsertPt(), emitAtomicCmpXchgFailureSet(), EmitAtomicExpr(), EmitAtomicOp(), EmitBlock(), EmitBlockAfterUses(), EmitBlockLiteral(), EmitDestructorBody(), EmitDirectCallee(), emitDynamicTlsInitialization(), EmitFunctionEpilog(), clang::CodeGen::CGOpenMPRuntimeGPU::emitFunctionProlog(), EmitIfUsed(), EmitLambdaInAllocaCallOpBody(), clang::CodeGen::CGOpenMPRuntime::emitLastprivateConditionalInit(), EmitMustTailThunk(), EmitPredefinedLValue(), EmitSEHAbnormalTermination(), EmitSEHExceptionCodeSave(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsOutlinedFunction(), clang::CodeGen::CGOpenMPRuntime::emitUserDefinedReduction(), FinishFunction(), clang::CodeGen::CGOpenMPRuntime::functionFinished(), clang::CodeGen::CGOpenMPRuntimeGPU::functionFinished(), GenerateCode(), GenerateObjCMethod(), GenerateSEHFilterFunction(), GenerateSEHFinallyFunction(), GenerateVarArgsThunk(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), GetAddrOfLabel(), clang::CodeGen::getCXXDestructorImplicitParam(), getInvokeDestImpl(), clang::CodeGen::CGOpenMPRuntime::getOutlinedHelperName(), getTerminateLandingPad(), clang::CodeGen::CGOpenMPRuntime::getThreadID(), clang::CodeGen::CGOpenMPRuntimeGPU::isDelayedVariableLengthDecl(), clang::CodeGen::CGOpenMPRuntime::isLocalVarInUntiedTask(), isMCDCCoverageEnabled(), recoverAddrOfEscapedLocal(), clang::CodeGen::CGOpenMPRuntime::setLocThreadIdInsertPt(), StartFunction(), clang::CodeGen::CGOpenMPRuntime::UntiedTaskLocalDeclsRAII::UntiedTaskLocalDeclsRAII(), and ~CodeGenFunction().
CurFnInfo
const CGFunctionInfo* clang::CodeGen::CodeGenFunction::CurFnInfo = nullptr
Definition at line 351 of file CodeGenFunction.h.
Referenced by EmitCallAndReturnForThunk(), EmitMustTailThunk(), EmitParmDecl(), FinishFunction(), and StartFunction().
CurFPFeatures
FPOptions clang::CodeGen::CodeGenFunction::CurFPFeatures
Definition at line 782 of file CodeGenFunction.h.
CurFuncDecl
const Decl* clang::CodeGen::CodeGenFunction::CurFuncDecl = nullptr
CurFuncDecl - Holds the Decl for the current outermost non-closure context.
Definition at line 348 of file CodeGenFunction.h.
Referenced by computeBlockInfo(), EmitCall(), EmitFunctionEpilog(), EmitObjCMessageExpr(), clang::CodeGen::CGOpenMPRuntime::emitUpdateLocation(), FinishThunk(), clang::CodeGen::getCXXDestructorImplicitParam(), getIdentStringFromSourceLocation(), clang::CodeGen::CodeGenFunction::InlinedInheritingConstructorScope::InlinedInheritingConstructorScope(), LoadCXXThisAddress(), LoadObjCSelf(), ShouldInstrumentFunction(), ShouldSkipSanitizerInstrumentation(), StartFunction(), StartThunk(), and TypeOfSelfObject().
CurFuncIsThunk
bool clang::CodeGen::CodeGenFunction::CurFuncIsThunk = false
In C++, whether we are code generating a thunk.
This controls whether we should emit cleanups.
Definition at line 585 of file CodeGenFunction.h.
Referenced by EmitDelegateCallArg(), EmitParmDecl(), StartFunction(), and StartThunk().
CurGD
GlobalDecl clang::CodeGen::CodeGenFunction::CurGD
CurGD - The GlobalDecl for the current function being compiled.
Definition at line 397 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGCXXABI::buildThisParam(), EmitCallAndReturnForThunk(), EmitConstructorBody(), EmitCXXConstructExpr(), EmitDelegateCXXConstructorCall(), EmitDelegatingCXXConstructorCall(), EmitDestructorBody(), emitImplicitAssignmentOperatorBody(), EmitInlinedInheritingCXXConstructorCall(), EmitMemberInitializer(), GenerateBlockFunction(), GenerateCode(), GetVTTParameter(), clang::CodeGen::CodeGenFunction::InlinedInheritingConstructorScope::InlinedInheritingConstructorScope(), StartObjCMethod(), and StartThunk().
CurrentCleanupScopeDepth
EHScopeStack::stable_iterator clang::CodeGen::CodeGenFunction::CurrentCleanupScopeDepth
Initial value:
=
      EHScopeStack::stable_end()
Definition at line 982 of file CodeGenFunction.h.
Referenced by EmitCall(), and clang::CodeGen::CodeGenFunction::RunCleanupsScope::RunCleanupsScope().
CurrentFuncletPad
llvm::Instruction* clang::CodeGen::CodeGenFunction::CurrentFuncletPad = nullptr
Definition at line 675 of file CodeGenFunction.h.
Referenced by emitCatchPadBlock(), EmitSehScope(), emitWasmCatchPadBlock(), getBundlesForCoroEnd(), getBundlesForFunclet(), getTerminateFunclet(), and isCleanupPadScope().
CurSEHParent
GlobalDecl clang::CodeGen::CodeGenFunction::CurSEHParent
Definition at line 594 of file CodeGenFunction.h.
Referenced by currentFunctionUsesSEHTry(), clang::CodeGen::EHPersonality::get(), and StartFunction().
CurSourceLocExprScope
CurrentSourceLocExprScope clang::CodeGen::CodeGenFunction::CurSourceLocExprScope
Source location information about the default argument or member initializer expression we're evaluating, if any.
Definition at line 1723 of file CodeGenFunction.h.
destroyARCStrongImprecise
void CodeGenFunction::destroyARCStrongImprecise static
Definition at line 4683 of file CodeGenFunction.h.
Referenced by emitAutoVarTypeCleanup(), EmitAutoVarWithLifetime(), pushCaptureCleanup(), and pushTemporaryCleanup().
destroyARCStrongPrecise
void CodeGenFunction::destroyARCStrongPrecise static
Definition at line 4684 of file CodeGenFunction.h.
Referenced by EmitAutoVarWithLifetime(), getDestroyer(), and pushTemporaryCleanup().
destroyARCWeak
void CodeGenFunction::destroyARCWeak static
Definition at line 4685 of file CodeGenFunction.h.
Referenced by EmitAutoVarWithLifetime(), getDestroyer(), and pushTemporaryCleanup().
destroyCXXObject
void CodeGenFunction::destroyCXXObject static
Definition at line 3108 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGObjCRuntime::destroyCalleeDestroyedArguments(), EmitCXXAggrConstructorCall(), getDestroyer(), and pushTemporaryCleanup().
destroyNonTrivialCStruct
void CodeGenFunction::destroyNonTrivialCStruct static
Definition at line 4687 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CGObjCRuntime::destroyCalleeDestroyedArguments(), emitAutoVarTypeCleanup(), and getDestroyer().
EHResumeBlock
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::EHResumeBlock = nullptr
EHResumeBlock - Unified block containing a call to llvm.eh.resume.
Definition at line 714 of file CodeGenFunction.h.
Referenced by FinishFunction(), and getEHResumeBlock().
EHSelectorSlot
llvm::AllocaInst* clang::CodeGen::CodeGenFunction::EHSelectorSlot = nullptr
The selector slot.
Under the MandatoryCleanup model, all landing pads write the current selector value into this alloca.
Definition at line 722 of file CodeGenFunction.h.
Referenced by getEHSelectorSlot().
EHStack
EHScopeStack clang::CodeGen::CodeGenFunction::EHStack
Definition at line 671 of file CodeGenFunction.h.
Referenced by CallBeginCatch(), EmitAnyExprToExn(), EmitArrayDelete(), EmitAutoVarCleanups(), emitAutoVarTypeCleanup(), EmitBaseInitializer(), EmitCall(), EmitCallArg(), emitCXXDestructMethod(), EmitCXXNewExpr(), EmitDelegatingCXXConstructorCall(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitEndEHSpec(), clang::CodeGen::CGOpenMPRuntimeGPU::emitFunctionProlog(), EmitFunctionProlog(), EmitLabel(), EmitLandingPad(), EmitNewArrayInitializer(), EmitObjCAutoreleasePoolCleanup(), EmitObjectDelete(), EmitParmDecl(), EmitStartEHSpec(), clang::CodeGen::CodeGenFunction::FinallyInfo::enter(), enterByrefCleanup(), EnterDtorCleanups(), EnterNewDeleteCleanup(), clang::CodeGen::CodeGenFunction::FinallyInfo::exit(), FinishFunction(), getEHDispatchBlock(), getFuncletEHDispatchBlock(), getInvokeDest(), getInvokeDestImpl(), getJumpDestInCurrentScope(), clang::CodeGen::CGOpenMPRuntime::getThreadID(), InitCatchParam(), initFullExprCleanupWithFlag(), clang::CodeGen::RegionCodeGenTy::operator()(), popCatchScope(), pushCallObjectDeleteCleanup(), PushDestructorCleanup(), pushFullExprCleanup(), pushKmpcAllocFree(), pushLifetimeExtendedDestroy(), pushSEHCleanup(), pushStackRestore(), clang::CodeGen::CodeGenFunction::RunCleanupsScope::requiresCleanups(), clang::CodeGen::CodeGenFunction::LexicalScope::rescopeLabels(), ResolveAllBranchFixups(), clang::CodeGen::CodeGenFunction::RunCleanupsScope::RunCleanupsScope(), SetupCleanupBlockActivation(), SimplifyForwardingBlocks(), StartFunction(), and StartObjCMethod().
emitARCIntrinsicUse
void CodeGenFunction::emitARCIntrinsicUse static
Definition at line 4686 of file CodeGenFunction.h.
ExceptionSlot
llvm::Value* clang::CodeGen::CodeGenFunction::ExceptionSlot = nullptr
The exception slot.
All landing pads write the current exception pointer into this alloca.
Definition at line 718 of file CodeGenFunction.h.
Referenced by getExceptionSlot().
ExpectedOMPLoopDepth
int clang::CodeGen::CodeGenFunction::ExpectedOMPLoopDepth = 0
Number of nested loop to be consumed by the last surrounding loop-associated directive.
Definition at line 319 of file CodeGenFunction.h.
FnArgs
llvm::SmallVector<const ParmVarDecl *, 4> clang::CodeGen::CodeGenFunction::FnArgs
Save Parameter Decl for coroutine.
Definition at line 356 of file CodeGenFunction.h.
Referenced by EmitCfiCheckStub(), and GenerateCode().
FnRetTy
QualType clang::CodeGen::CodeGenFunction::FnRetTy
Definition at line 352 of file CodeGenFunction.h.
Referenced by EmitInlinedInheritingCXXConstructorCall(), clang::CodeGen::CodeGenFunction::InlinedInheritingConstructorScope::InlinedInheritingConstructorScope(), and StartFunction().
InAlwaysInlineAttributedStmt
bool clang::CodeGen::CodeGenFunction::InAlwaysInlineAttributedStmt = false
True if the current statement has always_inline attribute.
Definition at line 611 of file CodeGenFunction.h.
Referenced by EmitCall().
InNoInlineAttributedStmt
bool clang::CodeGen::CodeGenFunction::InNoInlineAttributedStmt = false
True if the current statement has noinline attribute.
Definition at line 608 of file CodeGenFunction.h.
Referenced by EmitCall().
InNoMergeAttributedStmt
bool clang::CodeGen::CodeGenFunction::InNoMergeAttributedStmt = false
True if the current statement has nomerge attribute.
Definition at line 605 of file CodeGenFunction.h.
Referenced by EmitCall().
IsInPreservedAIRegion
bool clang::CodeGen::CodeGenFunction::IsInPreservedAIRegion = false
True if CodeGen currently emits code inside presereved access index region.
Definition at line 602 of file CodeGenFunction.h.
Referenced by emitArraySubscriptGEP(), and EmitLValueForField().
IsOutlinedSEHHelper
bool clang::CodeGen::CodeGenFunction::IsOutlinedSEHHelper = false
True if the current function is an outlined SEH helper.
This can be a finally block or filter expression.
Definition at line 598 of file CodeGenFunction.h.
IsSanitizerScope
bool clang::CodeGen::CodeGenFunction::IsSanitizerScope = false
True if CodeGen currently emits code implementing sanitizer checks.
Definition at line 573 of file CodeGenFunction.h.
Referenced by EmitCheck(), and clang::CodeGen::CodeGenFunction::SanitizerScope::SanitizerScope().
LambdaCaptureFields
llvm::DenseMap<const ValueDecl *, FieldDecl *> clang::CodeGen::CodeGenFunction::LambdaCaptureFields
Definition at line 664 of file CodeGenFunction.h.
Referenced by EmitDeclRefLValue(), emitPrivatesInit(), getCaptureFieldType(), and StartFunction().
LambdaThisCaptureField
FieldDecl* clang::CodeGen::CodeGenFunction::LambdaThisCaptureField = nullptr
Definition at line 665 of file CodeGenFunction.h.
Referenced by StartFunction().
LifetimeExtendedCleanupStack
llvm::SmallVector<char, 256> clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupStack
Definition at line 672 of file CodeGenFunction.h.
Referenced by pushCleanupAfterFullExprWithActiveFlag(), clang::CodeGen::CodeGenFunction::RunCleanupsScope::RunCleanupsScope(), and ~CodeGenFunction().
LoopStack
LoopInfoStack clang::CodeGen::CodeGenFunction::LoopStack
Definition at line 293 of file CodeGenFunction.h.
Referenced by AddIVDepMetadata(), and emitSimdlenSafelenClause().
MCDCLogOpStack
SmallVector<const BinaryOperator *, 16> clang::CodeGen::CodeGenFunction::MCDCLogOpStack
Stack to track the Logical Operator recursion nest for MC/DC.
Definition at line 315 of file CodeGenFunction.h.
Referenced by EmitBranchOnBoolExpr().
MustTailCall
const CallExpr* clang::CodeGen::CodeGenFunction::MustTailCall = nullptr
Definition at line 615 of file CodeGenFunction.h.
Referenced by EmitCall(), EmitCXXDestructorCall(), EmitCXXMemberOrOperatorCall(), and EmitCXXMemberPointerCallExpr().
NextCleanupDestIndex
unsigned clang::CodeGen::CodeGenFunction::NextCleanupDestIndex = 1
Definition at line 711 of file CodeGenFunction.h.
Referenced by getJumpDestForLabel(), and getJumpDestInCurrentScope().
NormalCleanupDest
RawAddress clang::CodeGen::CodeGenFunction::NormalCleanupDest = RawAddress::invalid()
i32s containing the indexes of the cleanup destinations.
Definition at line 709 of file CodeGenFunction.h.
Referenced by destroyOptimisticNormalEntry(), and FinishFunction().
NRVOFlags
llvm::DenseMap<const VarDecl *, llvm::Value *> clang::CodeGen::CodeGenFunction::NRVOFlags
A mapping from NRVO variables to the flags used to indicate when the NRVO has been applied to this variable.
Definition at line 669 of file CodeGenFunction.h.
Referenced by EmitAutoVarAlloca().
ObjCEHValueStack
SmallVector<llvm::Value*, 8> clang::CodeGen::CodeGenFunction::ObjCEHValueStack
ObjCEHValueStack - Stack of Objective-C exception values, used for rethrows.
Definition at line 787 of file CodeGenFunction.h.
OMPAfterScanBlock
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::OMPAfterScanBlock = nullptr
Definition at line 740 of file CodeGenFunction.h.
OMPBeforeScanBlock
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::OMPBeforeScanBlock = nullptr
Definition at line 739 of file CodeGenFunction.h.
OMPFirstScanLoop
bool clang::CodeGen::CodeGenFunction::OMPFirstScanLoop = false
Definition at line 743 of file CodeGenFunction.h.
OMPLoopNestStack
SmallVector<llvm::CanonicalLoopInfo *, 4> clang::CodeGen::CodeGenFunction::OMPLoopNestStack
List of recently emitted OMPCanonicalLoops.
Since OMPCanonicalLoops are nested inside other statements (in particular CapturedStmt generated by OMPExecutableDirective and non-perfectly nested loops), we cannot directly call OMPEmitOMPCanonicalLoop and receive its llvm::CanonicalLoopInfo. Instead, we call EmitStmt and any OMPEmitOMPCanonicalLoop called by it will add its CanonicalLoopInfo to this stack when done. Entering a new loop requires clearing this list; it either means we start parsing a new loop nest (in which case the previous loop nest goes out of scope) or a second loop in the same level in which case it would be ambiguous into which of the two (or more) loops the loop nest would extend.
Definition at line 312 of file CodeGenFunction.h.
OMPParentLoopDirectiveForScan
const OMPExecutableDirective* clang::CodeGen::CodeGenFunction::OMPParentLoopDirectiveForScan = nullptr
Parent loop-based directive for scan directive.
Definition at line 738 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::ParentLoopDirectiveForScanRegion::ParentLoopDirectiveForScanRegion(), and clang::CodeGen::CodeGenFunction::ParentLoopDirectiveForScanRegion::~ParentLoopDirectiveForScanRegion().
OMPScanDispatch
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::OMPScanDispatch = nullptr
Definition at line 742 of file CodeGenFunction.h.
OMPScanExitBlock
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::OMPScanExitBlock = nullptr
Definition at line 741 of file CodeGenFunction.h.
ParentCGF
CodeGenFunction* clang::CodeGen::CodeGenFunction::ParentCGF = nullptr
Definition at line 290 of file CodeGenFunction.h.
Referenced by EmitSEHExceptionCodeSave(), GenerateSEHFilterFunction(), GenerateSEHFinallyFunction(), and recoverAddrOfEscapedLocal().
PrologueCleanupDepth
EHScopeStack::stable_iterator clang::CodeGen::CodeGenFunction::PrologueCleanupDepth
PrologueCleanupDepth - The cleanup depth enclosing all the cleanups associated with the parameters.
Definition at line 401 of file CodeGenFunction.h.
Referenced by FinishFunction(), and StartFunction().
RetExpr
const Expr* clang::CodeGen::CodeGenFunction::RetExpr = nullptr
If a return statement is being visited, this holds the return statment's result expression.
Definition at line 416 of file CodeGenFunction.h.
ReturnBlock
JumpDest clang::CodeGen::CodeGenFunction::ReturnBlock
ReturnBlock - Unified return block.
Definition at line 404 of file CodeGenFunction.h.
Referenced by EmitForwardingCallToLambda(), EmitReturnBlock(), EmitReturnValueCheck(), EnterDtorCleanups(), FinishFunction(), getOMPCancelDestination(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OutlinedRegionBodyRAII::OutlinedRegionBodyRAII(), StartFunction(), and clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::OutlinedRegionBodyRAII::~OutlinedRegionBodyRAII().
ReturnValue
Address clang::CodeGen::CodeGenFunction::ReturnValue = Address::invalid()
ReturnValue - The temporary alloca to hold the return value.
This is invalid iff the function has no return value.
Definition at line 408 of file CodeGenFunction.h.
Referenced by createTLSAtExitStub(), EmitAutoVarAlloca(), EmitBlockCallExpr(), EmitCall(), EmitCallAndReturnForThunk(), EmitCallExpr(), EmitCUDAKernelCallExpr(), EmitCXXMemberCallExpr(), EmitCXXMemberOrOperatorCall(), EmitCXXMemberPointerCallExpr(), EmitCXXOperatorMemberCallExpr(), EmitForwardingCallToLambda(), EmitFunctionEpilog(), EmitFunctionProlog(), EmitInlinedInheritingCXXConstructorCall(), EmitSimpleCallExpr(), findDominatingStoreToReturnValue(), FinishFunction(), generateObjCGetterBody(), GenerateSEHFilterFunction(), clang::CodeGen::CodeGenFunction::InlinedInheritingConstructorScope::InlinedInheritingConstructorScope(), and StartFunction().
ReturnValuePointer
Address clang::CodeGen::CodeGenFunction::ReturnValuePointer = Address::invalid()
ReturnValuePointer - The temporary alloca to hold a pointer to sret.
This is invalid if sret is not in use.
Definition at line 412 of file CodeGenFunction.h.
Referenced by StartFunction().
SanOpts
SanitizerSet clang::CodeGen::CodeGenFunction::SanOpts
Sanitizers enabled for this function.
Definition at line 570 of file CodeGenFunction.h.
Referenced by emitAlignmentAssumption(), emitAlignmentAssumptionCheck(), EmitArraySubscriptExpr(), EmitBinaryOperatorLValue(), EmitBitfieldConversionCheck(), EmitCall(), EmitCastLValue(), EmitCfiCheckFail(), EmitCheck(), EmitCheckedLValue(), EmitFunctionProlog(), EmitMaterializeTemporaryExpr(), EmitNullabilityCheck(), emitPointerArithmetic(), EmitPointerWithAlignment(), EmitReturnValueCheck(), EmitScalarRangeCheck(), EmitTypeCheck(), EmitTypeMetadataCodeForVCall(), EmitUnreachable(), EmitVariablyModifiedType(), EmitVTablePtrCheckForCall(), EmitVTablePtrCheckForCast(), EmitVTableTypeCheckedLoad(), EnterDtorCleanups(), GenerateCode(), markAsIgnoreThreadCheckingAtRuntime(), sanitizePerformTypeCheck(), ShouldEmitVTableTypeCheckedLoad(), and StartFunction().
SawAsmBlock
bool clang::CodeGen::CodeGenFunction::SawAsmBlock = false
Whether we processed a Microsoft-style asm block during CodeGen.
These can potentially set the return value.
Definition at line 592 of file CodeGenFunction.h.
Referenced by GenerateCode().
SEHCodeSlotStack
SmallVector<Address, 1> clang::CodeGen::CodeGenFunction::SEHCodeSlotStack
A stack of exception code slots.
Entering an __except block pushes a slot on the stack and leaving pops one. The __exception_code() intrinsic loads a value from the top of the stack.
Definition at line 727 of file CodeGenFunction.h.
Referenced by EmitSEHExceptionCode(), and EmitSEHExceptionCodeSave().
SEHInfo
llvm::Value* clang::CodeGen::CodeGenFunction::SEHInfo = nullptr
Value returned by __exception_info intrinsic.
Definition at line 730 of file CodeGenFunction.h.
Referenced by EmitSEHExceptionCodeSave(), and EmitSEHExceptionInfo().
SEHTryEpilogueStack
llvm::SmallVector<const JumpDest *, 2> clang::CodeGen::CodeGenFunction::SEHTryEpilogueStack
Definition at line 673 of file CodeGenFunction.h.
Referenced by isSEHTryScope(), and VolatilizeTryBlocks().
Target
const TargetInfo& clang::CodeGen::CodeGenFunction::Target
Definition at line 287 of file CodeGenFunction.h.
Referenced by getTarget().
The documentation for this class was generated from the following files:
lib/CodeGen/CodeGenFunction.h
lib/CodeGen/CGAtomic.cpp
lib/CodeGen/CGBlocks.cpp
lib/CodeGen/CGBuiltin.cpp
lib/CodeGen/CGCall.cpp
lib/CodeGen/CGClass.cpp
lib/CodeGen/CGCleanup.cpp
lib/CodeGen/CGCoroutine.cpp
lib/CodeGen/CGCXX.cpp
lib/CodeGen/CGDecl.cpp
lib/CodeGen/CGDeclCXX.cpp
lib/CodeGen/CGException.cpp
lib/CodeGen/CGExpr.cpp
lib/CodeGen/CGExprAgg.cpp
lib/CodeGen/CGExprComplex.cpp
lib/CodeGen/CGExprCXX.cpp
lib/CodeGen/CGExprScalar.cpp
lib/CodeGen/CGGPUBuiltin.cpp
lib/CodeGen/CGNonTrivialStruct.cpp
lib/CodeGen/CGObjC.cpp
lib/CodeGen/CGStmt.cpp
lib/CodeGen/CGStmtOpenMP.cpp
lib/CodeGen/CGVTables.cpp
lib/CodeGen/CodeGenFunction.cpp
lib/CodeGen/CodeGenModule.cpp
lib/CodeGen/CodeGenPGO.cpp