clang: clang::LinkageComputer Class Reference
clang::LinkageComputer Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Linkage.h"
Public Member Functions
LinkageInfo computeLVForDecl (const NamedDecl *D, LVComputationKind computation, bool IgnoreVarTypeLinkage=false)
LinkageInfo getLVForDecl (const NamedDecl *D, LVComputationKind computation)
getLVForDecl - Get the linkage and visibility for the given declaration.
LinkageInfo computeTypeLinkageInfo (const Type *T)
LinkageInfo computeTypeLinkageInfo (QualType T)
LinkageInfo getDeclLinkageAndVisibility (const NamedDecl *D)
LinkageInfo getTypeLinkageAndVisibility (const Type *T)
LinkageInfo getTypeLinkageAndVisibility (QualType T)
Detailed Description
Definition at line 77 of file Linkage.h.
Member Function Documentation
computeLVForDecl()
LinkageInfo LinkageComputer::computeLVForDecl (const NamedDecl * D, LVComputationKind computation, bool IgnoreVarTypeLinkage = false)
Definition at line 1450 of file Decl.cpp.
References clang::Decl::getASTContext(), clang::Decl::getDeclContext(), getExternalLinkageFor(), clang::Decl::getKind(), clang::ASTContext::getLangOpts(), getLVForDecl(), clang::DeclContext::getRedeclContext(), clang::Decl::hasAttr(), clang::LinkageInfo::internal(), clang::DeclContext::isFileContext(), clang::DeclContext::isFunctionOrMethod(), clang::DeclContext::isRecord(), Label, clang::LinkageInfo::merge(), clang::LinkageInfo::none(), and clang::LinkageInfo::visible_none().
Referenced by getLVForDecl(), and clang::NamedDecl::isLinkageValid().
computeTypeLinkageInfo() [1/2]
LinkageInfo LinkageComputer::computeTypeLinkageInfo (const Type * T)
Definition at line 4515 of file Type.cpp.
References clang::LinkageInfo::external(), getDeclLinkageAndVisibility(), clang::Type::getTypeClass(), clang::Type::isInstantiationDependentType(), clang::LinkageInfo::merge(), and clang::T.
Referenced by computeTypeLinkageInfo(), getTypeLinkageAndVisibility(), and clang::Type::isLinkageValid().
computeTypeLinkageInfo() [2/2]
LinkageInfo clang::LinkageComputer::computeTypeLinkageInfo (QualType T) inline
Definition at line 156 of file Linkage.h.
References computeTypeLinkageInfo(), and clang::T.
getDeclLinkageAndVisibility()
LinkageInfo LinkageComputer::getDeclLinkageAndVisibility (const NamedDecl * D)
Definition at line 1614 of file Decl.cpp.
References clang::LVComputationKind::forLinkageOnly(), clang::Decl::getASTContext(), clang::ASTContext::getLangOpts(), getLVForDecl(), usesTypeVisibility(), clang::NamedDecl::VisibilityForType, and clang::NamedDecl::VisibilityForValue.
Referenced by computeTypeLinkageInfo(), and clang::NamedDecl::getLinkageAndVisibility().
getLVForDecl()
LinkageInfo LinkageComputer::getLVForDecl (const NamedDecl * D, LVComputationKind computation)
getLVForDecl - Get the linkage and visibility for the given declaration.
Definition at line 1568 of file Decl.cpp.
References computeLVForDecl(), clang::DefaultVisibility, clang::Decl::getASTContext(), clang::Decl::getCachedLinkage(), clang::ASTContext::getLangOpts(), clang::LinkageInfo::getLinkage(), clang::Decl::hasAttr(), clang::Decl::hasCachedLinkage(), clang::LVComputationKind::IgnoreAllVisibility, clang::LinkageInfo::internal(), clang::Decl::redecls(), clang::Decl::setCachedLinkage(), and clang::T.
Referenced by computeLVForDecl(), getDeclLinkageAndVisibility(), and clang::NamedDecl::getLinkageInternal().
getTypeLinkageAndVisibility() [1/2]
LinkageInfo LinkageComputer::getTypeLinkageAndVisibility (const Type * T)
Definition at line 4603 of file Type.cpp.
References computeTypeLinkageInfo(), clang::Type::getCanonicalTypeInternal(), clang::Type::getLinkage(), clang::LinkageInfo::getLinkage(), clang::Type::isCanonicalUnqualified(), and clang::T.
Referenced by clang::Type::getLinkageAndVisibility(), and getTypeLinkageAndVisibility().
getTypeLinkageAndVisibility() [2/2]
LinkageInfo clang::LinkageComputer::getTypeLinkageAndVisibility (QualType T) inline
Definition at line 163 of file Linkage.h.
References getTypeLinkageAndVisibility(), and clang::T.
The documentation for this class was generated from the following files:
lib/AST/Linkage.h
lib/AST/APValue.cpp
lib/AST/Decl.cpp
lib/AST/Type.cpp