clang: clang::extractapi::APISetVisitor< Derived > Class Template Reference
clang::extractapi::APISetVisitor< Derived > Class Template Reference
The base interface of visitors for API information.
#include "clang/ExtractAPI/Serialization/SerializerBase.h"
Public Member Functions
void traverseAPISet ()
void traverseNamespaces ()
void traverseGlobalFunctionRecords ()
void traverseGlobalVariableRecords ()
void traverseEnumRecords ()
void traverseRecordRecords ()
void traverseStaticFieldRecords ()
void traverseCXXClassRecords ()
void traverseCXXMethodTemplates ()
void traverseCXXMethodTemplateSpecializations ()
void traverseClassTemplateRecords ()
void traverseClassTemplateSpecializationRecords ()
void traverseClassTemplatePartialSpecializationRecords ()
void traverseCXXInstanceMethods ()
void traverseCXXStaticMethods ()
void traverseCXXFields ()
void traverseCXXFieldTemplates ()
void traverseGlobalVariableTemplateRecords ()
void traverseGlobalVariableTemplateSpecializationRecords ()
void traverseGlobalVariableTemplatePartialSpecializationRecords ()
void traverseGlobalFunctionTemplateRecords ()
void traverseGlobalFunctionTemplateSpecializationRecords ()
void traverseConcepts ()
void traverseObjCInterfaces ()
void traverseObjCProtocols ()
void traverseObjCCategories ()
void traverseMacroDefinitionRecords ()
void traverseTypedefRecords ()
void visitNamespaceRecord (const NamespaceRecord &Record)
void visitGlobalFunctionRecord (const GlobalFunctionRecord &Record)
Visit a global function record.
void visitGlobalVariableRecord (const GlobalVariableRecord &Record)
Visit a global variable record.
void visitEnumRecord (const EnumRecord &Record)
Visit an enum record.
void visitRecordRecord (const RecordRecord &Record)
Visit a record record.
void visitStaticFieldRecord (const StaticFieldRecord &Record)
void visitCXXClassRecord (const CXXClassRecord &Record)
void visitClassTemplateRecord (const ClassTemplateRecord &Record)
void visitClassTemplateSpecializationRecord (const ClassTemplateSpecializationRecord &Record)
void visitClassTemplatePartialSpecializationRecord (const ClassTemplatePartialSpecializationRecord &Record)
void visitCXXInstanceRecord (const CXXInstanceMethodRecord &Record)
void visitCXXStaticRecord (const CXXStaticMethodRecord &Record)
void visitMethodTemplateRecord (const CXXMethodTemplateRecord &Record)
void visitMethodTemplateSpecializationRecord (const CXXMethodTemplateSpecializationRecord &Record)
void visitCXXFieldTemplateRecord (const CXXFieldTemplateRecord &Record)
void visitGlobalVariableTemplateRecord (const GlobalVariableTemplateRecord &Record)
void visitGlobalVariableTemplateSpecializationRecord (const GlobalVariableTemplateSpecializationRecord &Record)
void visitGlobalVariableTemplatePartialSpecializationRecord (const GlobalVariableTemplatePartialSpecializationRecord &Record)
void visitGlobalFunctionTemplateRecord (const GlobalFunctionTemplateRecord &Record)
void visitGlobalFunctionTemplateSpecializationRecord (const GlobalFunctionTemplateSpecializationRecord &Record)
void visitObjCContainerRecord (const ObjCContainerRecord &Record)
Visit an Objective-C container record.
void visitObjCCategoryRecord (const ObjCCategoryRecord &Record)
Visit an Objective-C category record.
void visitMacroDefinitionRecord (const MacroDefinitionRecord &Record)
Visit a macro definition record.
void visitTypedefRecord (const TypedefRecord &Record)
Visit a typedef record.
APISetVisitor ()=delete
APISetVisitor (const APISetVisitor &)=delete
APISetVisitor (APISetVisitor &&)=delete
APISetVisitor & operator= (const APISetVisitor &)=delete
APISetVisitor & operator= (APISetVisitor &&)=delete
Protected Member Functions
APISetVisitor (const APISet &API)
~APISetVisitor ()=default
Derived * getDerived ()
Protected Attributes
const APISet & API
Detailed Description
template<typename Derived>
class clang::extractapi::APISetVisitor< Derived >
The base interface of visitors for API information.
Definition at line 23 of file SerializerBase.h.
Constructor & Destructor Documentation
APISetVisitor() [1/4]
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::APISetVisitor () delete
APISetVisitor() [2/4]
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::APISetVisitor (const APISetVisitor< Derived > &) delete
APISetVisitor() [3/4]
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::APISetVisitor (APISetVisitor< Derived > &&) delete
APISetVisitor() [4/4]
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::APISetVisitor (const APISet & API) inline protected
Definition at line 305 of file SerializerBase.h.
~APISetVisitor()
template<typename Derived > clang::extractapi::APISetVisitor< Derived >::~APISetVisitor () protected default
Member Function Documentation
getDerived()
template<typename Derived > Derived* clang::extractapi::APISetVisitor< Derived >::getDerived () inline protected
Definition at line 308 of file SerializerBase.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseAPISet(), clang::extractapi::APISetVisitor< Derived >::traverseClassTemplatePartialSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseClassTemplateRecords(), clang::extractapi::APISetVisitor< Derived >::traverseClassTemplateSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseConcepts(), clang::extractapi::APISetVisitor< Derived >::traverseCXXClassRecords(), clang::extractapi::APISetVisitor< Derived >::traverseCXXFields(), clang::extractapi::APISetVisitor< Derived >::traverseCXXFieldTemplates(), clang::extractapi::APISetVisitor< Derived >::traverseCXXInstanceMethods(), clang::extractapi::APISetVisitor< Derived >::traverseCXXMethodTemplates(), clang::extractapi::APISetVisitor< Derived >::traverseCXXMethodTemplateSpecializations(), clang::extractapi::APISetVisitor< Derived >::traverseCXXStaticMethods(), clang::extractapi::APISetVisitor< Derived >::traverseEnumRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionTemplateRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionTemplateSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplatePartialSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplateRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplateSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseMacroDefinitionRecords(), clang::extractapi::APISetVisitor< Derived >::traverseNamespaces(), clang::extractapi::APISetVisitor< Derived >::traverseObjCCategories(), clang::extractapi::APISetVisitor< Derived >::traverseObjCInterfaces(), clang::extractapi::APISetVisitor< Derived >::traverseObjCProtocols(), clang::extractapi::APISetVisitor< Derived >::traverseRecordRecords(), clang::extractapi::APISetVisitor< Derived >::traverseStaticFieldRecords(), and clang::extractapi::APISetVisitor< Derived >::traverseTypedefRecords().
operator=() [1/2]
template<typename Derived > APISetVisitor& clang::extractapi::APISetVisitor< Derived >::operator= (APISetVisitor< Derived > &&) delete
operator=() [2/2]
template<typename Derived > APISetVisitor& clang::extractapi::APISetVisitor< Derived >::operator= (const APISetVisitor< Derived > &) delete
traverseAPISet()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseAPISet () inline
Definition at line 25 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseClassTemplatePartialSpecializationRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseClassTemplatePartialSpecializationRecords () inline
Definition at line 140 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getClassTemplatePartialSpecializations(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseClassTemplateRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseClassTemplateRecords () inline
Definition at line 128 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getClassTemplates(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseClassTemplateSpecializationRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseClassTemplateSpecializationRecords () inline
Definition at line 133 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getClassTemplateSpecializations(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseConcepts()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseConcepts () inline
Definition at line 200 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getConcepts(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseCXXClassRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseCXXClassRecords () inline
Definition at line 111 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::Class, clang::extractapi::APISet::getCXXClasses(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseCXXFields()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseCXXFields () inline
Definition at line 157 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getCXXFields(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseCXXFieldTemplates()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseCXXFieldTemplates () inline
Definition at line 162 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getCXXFieldTemplates(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseCXXInstanceMethods()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseCXXInstanceMethods () inline
Definition at line 147 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getCXXInstanceMethods(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseCXXMethodTemplates()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseCXXMethodTemplates () inline
Definition at line 116 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getCXXMethodTemplates(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseCXXMethodTemplateSpecializations()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseCXXMethodTemplateSpecializations () inline
Definition at line 121 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getCXXMethodTemplateSpecializations(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseCXXStaticMethods()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseCXXStaticMethods () inline
Definition at line 152 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISet::getCXXStaticMethods(), and clang::extractapi::APISetVisitor< Derived >::getDerived().
traverseEnumRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseEnumRecords () inline
Definition at line 96 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getEnums().
traverseGlobalFunctionRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionRecords () inline
Definition at line 86 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalFunctions().
traverseGlobalFunctionTemplateRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionTemplateRecords () inline
Definition at line 187 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalFunctionTemplates().
traverseGlobalFunctionTemplateSpecializationRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionTemplateSpecializationRecords () inline
Definition at line 193 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalFunctionTemplateSpecializations().
traverseGlobalVariableRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableRecords () inline
Definition at line 91 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalVariables().
traverseGlobalVariableTemplatePartialSpecializationRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplatePartialSpecializationRecords () inline
Definition at line 180 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalVariableTemplatePartialSpecializations().
traverseGlobalVariableTemplateRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplateRecords () inline
Definition at line 167 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalVariableTemplates().
traverseGlobalVariableTemplateSpecializationRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplateSpecializationRecords () inline
Definition at line 173 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getGlobalVariableTemplateSpecializations().
traverseMacroDefinitionRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseMacroDefinitionRecords () inline
Definition at line 220 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getMacros().
traverseNamespaces()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseNamespaces () inline
Definition at line 81 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getNamespaces().
traverseObjCCategories()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseObjCCategories () inline
Definition at line 215 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, Category, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getObjCCategories().
traverseObjCInterfaces()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseObjCInterfaces () inline
Definition at line 205 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), clang::extractapi::APISet::getObjCInterfaces(), and clang::Interface.
traverseObjCProtocols()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseObjCProtocols () inline
Definition at line 210 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getObjCProtocols().
traverseRecordRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseRecordRecords () inline
Definition at line 101 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getRecords().
traverseStaticFieldRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseStaticFieldRecords () inline
Definition at line 106 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getStaticFields().
traverseTypedefRecords()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::traverseTypedefRecords () inline
Definition at line 225 of file SerializerBase.h.
References clang::extractapi::APISetVisitor< Derived >::API, clang::extractapi::APISetVisitor< Derived >::getDerived(), and clang::extractapi::APISet::getTypedefs().
visitClassTemplatePartialSpecializationRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitClassTemplatePartialSpecializationRecord (const ClassTemplatePartialSpecializationRecord & Record) inline
Definition at line 253 of file SerializerBase.h.
visitClassTemplateRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitClassTemplateRecord (const ClassTemplateRecord & Record) inline
Definition at line 248 of file SerializerBase.h.
visitClassTemplateSpecializationRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitClassTemplateSpecializationRecord (const ClassTemplateSpecializationRecord & Record) inline
Definition at line 250 of file SerializerBase.h.
visitCXXClassRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitCXXClassRecord (const CXXClassRecord & Record) inline
Definition at line 246 of file SerializerBase.h.
visitCXXFieldTemplateRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitCXXFieldTemplateRecord (const CXXFieldTemplateRecord & Record) inline
Definition at line 265 of file SerializerBase.h.
visitCXXInstanceRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitCXXInstanceRecord (const CXXInstanceMethodRecord & Record) inline
Definition at line 256 of file SerializerBase.h.
visitCXXStaticRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitCXXStaticRecord (const CXXStaticMethodRecord & Record) inline
Definition at line 258 of file SerializerBase.h.
visitEnumRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitEnumRecord (const EnumRecord & Record) inline
Visit an enum record.
Definition at line 239 of file SerializerBase.h.
visitGlobalFunctionRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalFunctionRecord (const GlobalFunctionRecord & Record) inline
Visit a global function record.
Definition at line 233 of file SerializerBase.h.
visitGlobalFunctionTemplateRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalFunctionTemplateRecord (const GlobalFunctionTemplateRecord & Record) inline
Definition at line 276 of file SerializerBase.h.
visitGlobalFunctionTemplateSpecializationRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalFunctionTemplateSpecializationRecord (const GlobalFunctionTemplateSpecializationRecord & Record) inline
Definition at line 279 of file SerializerBase.h.
visitGlobalVariableRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalVariableRecord (const GlobalVariableRecord & Record) inline
Visit a global variable record.
Definition at line 236 of file SerializerBase.h.
visitGlobalVariableTemplatePartialSpecializationRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalVariableTemplatePartialSpecializationRecord (const GlobalVariableTemplatePartialSpecializationRecord & Record) inline
Definition at line 273 of file SerializerBase.h.
visitGlobalVariableTemplateRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalVariableTemplateRecord (const GlobalVariableTemplateRecord & Record) inline
Definition at line 267 of file SerializerBase.h.
visitGlobalVariableTemplateSpecializationRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitGlobalVariableTemplateSpecializationRecord (const GlobalVariableTemplateSpecializationRecord & Record) inline
Definition at line 270 of file SerializerBase.h.
visitMacroDefinitionRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitMacroDefinitionRecord (const MacroDefinitionRecord & Record) inline
Visit a macro definition record.
Definition at line 289 of file SerializerBase.h.
visitMethodTemplateRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitMethodTemplateRecord (const CXXMethodTemplateRecord & Record) inline
Definition at line 260 of file SerializerBase.h.
visitMethodTemplateSpecializationRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitMethodTemplateSpecializationRecord (const CXXMethodTemplateSpecializationRecord & Record) inline
Definition at line 262 of file SerializerBase.h.
visitNamespaceRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitNamespaceRecord (const NamespaceRecord & Record) inline
Definition at line 230 of file SerializerBase.h.
visitObjCCategoryRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitObjCCategoryRecord (const ObjCCategoryRecord & Record) inline
Visit an Objective-C category record.
Definition at line 286 of file SerializerBase.h.
visitObjCContainerRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitObjCContainerRecord (const ObjCContainerRecord & Record) inline
Visit an Objective-C container record.
Definition at line 283 of file SerializerBase.h.
visitRecordRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitRecordRecord (const RecordRecord & Record) inline
Visit a record record.
Definition at line 242 of file SerializerBase.h.
visitStaticFieldRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitStaticFieldRecord (const StaticFieldRecord & Record) inline
Definition at line 244 of file SerializerBase.h.
visitTypedefRecord()
template<typename Derived > void clang::extractapi::APISetVisitor< Derived >::visitTypedefRecord (const TypedefRecord & Record) inline
Visit a typedef record.
Definition at line 292 of file SerializerBase.h.
Member Data Documentation
API
template<typename Derived > const APISet& clang::extractapi::APISetVisitor< Derived >::API protected
Definition at line 295 of file SerializerBase.h.
Referenced by clang::extractapi::APISetVisitor< Derived >::traverseClassTemplatePartialSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseClassTemplateRecords(), clang::extractapi::APISetVisitor< Derived >::traverseClassTemplateSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseConcepts(), clang::extractapi::APISetVisitor< Derived >::traverseCXXClassRecords(), clang::extractapi::APISetVisitor< Derived >::traverseCXXFields(), clang::extractapi::APISetVisitor< Derived >::traverseCXXFieldTemplates(), clang::extractapi::APISetVisitor< Derived >::traverseCXXInstanceMethods(), clang::extractapi::APISetVisitor< Derived >::traverseCXXMethodTemplates(), clang::extractapi::APISetVisitor< Derived >::traverseCXXMethodTemplateSpecializations(), clang::extractapi::APISetVisitor< Derived >::traverseCXXStaticMethods(), clang::extractapi::APISetVisitor< Derived >::traverseEnumRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionTemplateRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalFunctionTemplateSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplatePartialSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplateRecords(), clang::extractapi::APISetVisitor< Derived >::traverseGlobalVariableTemplateSpecializationRecords(), clang::extractapi::APISetVisitor< Derived >::traverseMacroDefinitionRecords(), clang::extractapi::APISetVisitor< Derived >::traverseNamespaces(), clang::extractapi::APISetVisitor< Derived >::traverseObjCCategories(), clang::extractapi::APISetVisitor< Derived >::traverseObjCInterfaces(), clang::extractapi::APISetVisitor< Derived >::traverseObjCProtocols(), clang::extractapi::APISetVisitor< Derived >::traverseRecordRecords(), clang::extractapi::APISetVisitor< Derived >::traverseStaticFieldRecords(), and clang::extractapi::APISetVisitor< Derived >::traverseTypedefRecords().
The documentation for this class was generated from the following file:
include/clang/ExtractAPI/Serialization/SerializerBase.h