clang: clang::ento::NodeBuilderWithSinks Class Reference
clang::ento::NodeBuilderWithSinks Class Reference
This node builder keeps track of the generated sink nodes.
#include "clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h"
Public Member Functions
NodeBuilderWithSinks (ExplodedNode *Pred, ExplodedNodeSet &DstSet, const NodeBuilderContext &Ctx, ProgramPoint &L)
ExplodedNode * generateNode (ProgramStateRef State, ExplodedNode *Pred, const ProgramPointTag *Tag=nullptr)
ExplodedNode * generateSink (ProgramStateRef State, ExplodedNode *Pred, const ProgramPointTag *Tag=nullptr)
const SmallVectorImpl< ExplodedNode * > & getSinks () const
Public Member Functions inherited from clang::ento::NodeBuilder
NodeBuilder (ExplodedNode *SrcNode, ExplodedNodeSet &DstSet, const NodeBuilderContext &Ctx, bool F=true)
NodeBuilder (const ExplodedNodeSet &SrcSet, ExplodedNodeSet &DstSet, const NodeBuilderContext &Ctx, bool F=true)
virtual ~NodeBuilder ()=default
ExplodedNode * generateNode (const ProgramPoint &PP, ProgramStateRef State, ExplodedNode *Pred)
Generates a node in the ExplodedGraph.
ExplodedNode * generateSink (const ProgramPoint &PP, ProgramStateRef State, ExplodedNode *Pred)
Generates a sink in the ExplodedGraph.
const ExplodedNodeSet & getResults ()
iterator begin ()
Iterators through the results frontier.
iterator end ()
const NodeBuilderContext & getContext ()
bool hasGeneratedNodes ()
void takeNodes (const ExplodedNodeSet &S)
void takeNodes (ExplodedNode *N)
void addNodes (const ExplodedNodeSet &S)
void addNodes (ExplodedNode *N)
Protected Attributes
SmallVector< ExplodedNode *, 2 > sinksGenerated
ProgramPoint & Location
Protected Attributes inherited from clang::ento::NodeBuilder
const NodeBuilderContext & C
bool Finalized
Specifies if the builder results have been finalized.
bool HasGeneratedNodes = false
ExplodedNodeSet & Frontier
The frontier set - a set of nodes which need to be propagated after the builder dies.
Additional Inherited Members
Public Types inherited from clang::ento::NodeBuilder
using iterator = ExplodedNodeSet::iterator
Protected Member Functions inherited from clang::ento::NodeBuilder
virtual bool checkResults ()
Checks if the results are ready.
bool hasNoSinksInFrontier ()
virtual void finalizeResults ()
Allow subclasses to finalize results before result_begin() is executed.
ExplodedNode * generateNodeImpl (const ProgramPoint &PP, ProgramStateRef State, ExplodedNode *Pred, bool MarkAsSink=false)
Detailed Description
This node builder keeps track of the generated sink nodes.
Definition at line 345 of file CoreEngine.h.
Constructor & Destructor Documentation
NodeBuilderWithSinks()
clang::ento::NodeBuilderWithSinks::NodeBuilderWithSinks (ExplodedNode * Pred, ExplodedNodeSet & DstSet, const NodeBuilderContext & Ctx, ProgramPoint & L) inline
Definition at line 353 of file CoreEngine.h.
Member Function Documentation
generateNode()
ExplodedNode* clang::ento::NodeBuilderWithSinks::generateNode (ProgramStateRef State, ExplodedNode * Pred, const ProgramPointTag * Tag = nullptr) inline
Definition at line 357 of file CoreEngine.h.
References clang::ento::NodeBuilder::generateNode(), Location, State, and clang::ProgramPoint::withTag().
Referenced by clang::ento::ExprEngine::processCFGBlockEntrance().
generateSink()
ExplodedNode* clang::ento::NodeBuilderWithSinks::generateSink (ProgramStateRef State, ExplodedNode * Pred, const ProgramPointTag * Tag = nullptr) inline
Definition at line 364 of file CoreEngine.h.
References clang::ento::NodeBuilder::generateSink(), clang::ento::ExplodedNode::isSink(), Location, sinksGenerated, State, and clang::ProgramPoint::withTag().
Referenced by clang::ento::ExprEngine::processCFGBlockEntrance().
getSinks()
const SmallVectorImpl<ExplodedNode*>& clang::ento::NodeBuilderWithSinks::getSinks () const inline
Definition at line 373 of file CoreEngine.h.
References sinksGenerated.
Member Data Documentation
Location
ProgramPoint& clang::ento::NodeBuilderWithSinks::Location protected
Definition at line 350 of file CoreEngine.h.
Referenced by generateNode(), and generateSink().
sinksGenerated
SmallVector<ExplodedNode*, 2> clang::ento::NodeBuilderWithSinks::sinksGenerated protected
Definition at line 349 of file CoreEngine.h.
Referenced by generateSink(), and getSinks().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h
lib/StaticAnalyzer/Core/CoreEngine.cpp