clang: clang::driver::tools::baremetal::Linker Class Reference
clang::driver::tools::baremetal::Linker Class Reference final
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/BareMetal.h"
Public Member Functions
Linker (const ToolChain &TC)
bool isLinkJob () const override
bool hasIntegratedCPP () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
virtual void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Detailed Description
Definition at line 102 of file BareMetal.h.
Constructor & Destructor Documentation
Linker()
clang::driver::tools::baremetal::Linker::Linker (const ToolChain & TC) inline
Definition at line 104 of file BareMetal.h.
Member Function Documentation
ConstructJob()
void baremetal::Linker::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 424 of file BareMetal.cpp.
References clang::driver::tools::AddLinkerInputs(), clang::driver::tools::arm::appendBE8LinkFlag(), clang::driver::ResponseFileSupport::AtFileCurCP(), clang::driver::ToolChain::getArch(), clang::driver::InputInfo::getFilename(), isARMBareMetal(), and clang::driver::tools::arm::isARMBigEndian().
hasIntegratedCPP()
bool clang::driver::tools::baremetal::Linker::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 106 of file BareMetal.h.
isLinkJob()
bool clang::driver::tools::baremetal::Linker::isLinkJob () const inline override virtual
Reimplemented from clang::driver::Tool.
Definition at line 105 of file BareMetal.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/BareMetal.h
lib/Driver/ToolChains/BareMetal.cpp