clang: clang::tooling::LocationCallFormatterCpp Class Reference
clang::tooling::LocationCallFormatterCpp Class Reference
#include "clang/Tooling/NodeIntrospection.h"
Static Public Member Functions
static void print (const LocationCall &Call, llvm::raw_ostream &OS)
static std::string format (const LocationCall &Call)
Detailed Description
Definition at line 54 of file NodeIntrospection.h.
Member Function Documentation
format()
std::string clang::tooling::LocationCallFormatterCpp::format (const LocationCall & Call) static
Definition at line 35 of file NodeIntrospection.cpp.
References print(), and string().
print()
void clang::tooling::LocationCallFormatterCpp::print (const LocationCall & Call, llvm::raw_ostream & OS) static
Definition at line 22 of file NodeIntrospection.cpp.
Referenced by format().
The documentation for this class was generated from the following files:
include/clang/Tooling/NodeIntrospection.h
lib/Tooling/NodeIntrospection.cpp