clang: clang::CodeGen::EHFilterScope Class Reference
clang::CodeGen::EHFilterScope Class Reference
An exceptions scope which filters exceptions thrown through it.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCleanup.h"
Public Member Functions
EHFilterScope (unsigned numFilters)
unsigned getNumFilters () const
void setFilter (unsigned i, llvm::Value *filterValue)
llvm::Value * getFilter (unsigned i) const
Public Member Functions inherited from clang::CodeGen::EHScope
EHScope (Kind kind, EHScopeStack::stable_iterator enclosingEHScope)
Kind getKind () const
llvm::BasicBlock * getCachedLandingPad () const
void setCachedLandingPad (llvm::BasicBlock *block)
llvm::BasicBlock * getCachedEHDispatchBlock () const
void setCachedEHDispatchBlock (llvm::BasicBlock *block)
bool hasEHBranches () const
EHScopeStack::stable_iterator getEnclosingEHScope () const
Static Public Member Functions
static size_t getSizeForNumFilters (unsigned numFilters)
static bool classof (const EHScope *scope)
Additional Inherited Members
Public Types inherited from clang::CodeGen::EHScope
enum Kind { Cleanup , Catch , Terminate , Filter }
Protected Attributes inherited from clang::CodeGen::EHScope
union {
CommonBitFields CommonBits
CatchBitFields CatchBits
CleanupBitFields CleanupBits
FilterBitFields FilterBits
};
Detailed Description
An exceptions scope which filters exceptions thrown through it.
Only exceptions matching the filter types will be permitted to be thrown.
This is used to implement C++ exception specifications.
Definition at line 446 of file CGCleanup.h.
Constructor & Destructor Documentation
EHFilterScope()
clang::CodeGen::EHFilterScope::EHFilterScope (unsigned numFilters) inline
Definition at line 459 of file CGCleanup.h.
References clang::CodeGen::EHScope::FilterBits.
Referenced by getSizeForNumFilters().
Member Function Documentation
classof()
static bool clang::CodeGen::EHFilterScope::classof (const EHScope * scope) inline static
Definition at line 481 of file CGCleanup.h.
References clang::CodeGen::EHScope::Filter, and clang::CodeGen::EHScope::getKind().
getFilter()
llvm::Value* clang::CodeGen::EHFilterScope::getFilter (unsigned i) const inline
Definition at line 476 of file CGCleanup.h.
References getNumFilters().
Referenced by clang::CodeGen::CodeGenFunction::EmitLandingPad().
getNumFilters()
unsigned clang::CodeGen::EHFilterScope::getNumFilters () const inline
Definition at line 469 of file CGCleanup.h.
References clang::CodeGen::EHScope::FilterBits.
Referenced by emitFilterDispatchBlock(), clang::CodeGen::CodeGenFunction::EmitLandingPad(), getFilter(), clang::CodeGen::EHScopeStack::popFilter(), and setFilter().
getSizeForNumFilters()
static size_t clang::CodeGen::EHFilterScope::getSizeForNumFilters (unsigned numFilters) inline static
Definition at line 465 of file CGCleanup.h.
References EHFilterScope().
Referenced by clang::CodeGen::EHScopeStack::iterator::operator++(), clang::CodeGen::EHScopeStack::popFilter(), and clang::CodeGen::EHScopeStack::pushFilter().
setFilter()
void clang::CodeGen::EHFilterScope::setFilter (unsigned i, llvm::Value * filterValue) inline
Definition at line 471 of file CGCleanup.h.
References getNumFilters().
The documentation for this class was generated from the following file:
lib/CodeGen/CGCleanup.h