clang: clang::PostOrderCFGView Class Reference
clang::PostOrderCFGView Class Reference
#include "clang/Analysis/Analyses/PostOrderCFGView.h"
Classes
struct BlockOrderCompare
class CFGBlockSet
Implements a set of CFGBlocks using a BitVector.
Public Types
using iterator = std::vector< const CFGBlock * >::reverse_iterator
using const_iterator = std::vector< const CFGBlock * >::const_reverse_iterator
Public Member Functions
PostOrderCFGView (const CFG *cfg)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
BlockOrderCompare getComparator () const
Public Member Functions inherited from clang::ManagedAnalysis
virtual ~ManagedAnalysis ()
Static Public Member Functions
static const void * getTag ()
static std::unique_ptr< PostOrderCFGView > create (AnalysisDeclContext &analysisContext)
Friends
struct BlockOrderCompare
Additional Inherited Members
Protected Member Functions inherited from clang::ManagedAnalysis
ManagedAnalysis ()=default
Detailed Description
Definition at line 28 of file PostOrderCFGView.h.
Member Typedef Documentation
const_iterator
using clang::PostOrderCFGView::const_iterator = std::vector<const CFGBlock *>::const_reverse_iterator
Definition at line 83 of file PostOrderCFGView.h.
iterator
using clang::PostOrderCFGView::iterator = std::vector<const CFGBlock *>::reverse_iterator
Definition at line 82 of file PostOrderCFGView.h.
Constructor & Destructor Documentation
PostOrderCFGView()
PostOrderCFGView::PostOrderCFGView (const CFG * cfg)
Definition at line 21 of file PostOrderCFGView.cpp.
References clang::CFG::getNumBlockIDs().
Member Function Documentation
begin() [1/2]
iterator clang::PostOrderCFGView::begin () inline
Definition at line 87 of file PostOrderCFGView.h.
Referenced by empty().
begin() [2/2]
const_iterator clang::PostOrderCFGView::begin () const inline
Definition at line 90 of file PostOrderCFGView.h.
create()
std::unique_ptr< PostOrderCFGView > PostOrderCFGView::create (AnalysisDeclContext & analysisContext) static
Definition at line 33 of file PostOrderCFGView.cpp.
References clang::AnalysisDeclContext::getCFG().
empty()
bool clang::PostOrderCFGView::empty () const inline
Definition at line 93 of file PostOrderCFGView.h.
References begin(), and end().
end() [1/2]
iterator clang::PostOrderCFGView::end () inline
Definition at line 88 of file PostOrderCFGView.h.
Referenced by empty().
end() [2/2]
const_iterator clang::PostOrderCFGView::end () const inline
Definition at line 91 of file PostOrderCFGView.h.
getComparator()
BlockOrderCompare clang::PostOrderCFGView::getComparator () const inline
Definition at line 104 of file PostOrderCFGView.h.
References BlockOrderCompare.
Referenced by clang::ForwardDataflowWorklist::ForwardDataflowWorklist().
getTag()
const void * PostOrderCFGView::getTag () static
Definition at line 40 of file PostOrderCFGView.cpp.
References x.
Friends And Related Function Documentation
BlockOrderCompare
friend struct BlockOrderCompare friend
Definition at line 80 of file PostOrderCFGView.h.
Referenced by getComparator().
The documentation for this class was generated from the following files:
include/clang/Analysis/Analyses/PostOrderCFGView.h
lib/Analysis/PostOrderCFGView.cpp