clang: clang::api_notes::APINotesReader::Implementation Class Reference
clang::api_notes::APINotesReader::Implementation Class Reference
Public Types
using SerializedIdentifierTable = llvm::OnDiskIterableChainedHashTable< IdentifierTableInfo >
using SerializedObjCContextIDTable = llvm::OnDiskIterableChainedHashTable< ObjCContextIDTableInfo >
using SerializedObjCContextInfoTable = llvm::OnDiskIterableChainedHashTable< ObjCContextInfoTableInfo >
using SerializedObjCPropertyTable = llvm::OnDiskIterableChainedHashTable< ObjCPropertyTableInfo >
using SerializedObjCMethodTable = llvm::OnDiskIterableChainedHashTable< ObjCMethodTableInfo >
using SerializedObjCSelectorTable = llvm::OnDiskIterableChainedHashTable< ObjCSelectorTableInfo >
using SerializedGlobalVariableTable = llvm::OnDiskIterableChainedHashTable< GlobalVariableTableInfo >
using SerializedGlobalFunctionTable = llvm::OnDiskIterableChainedHashTable< GlobalFunctionTableInfo >
using SerializedEnumConstantTable = llvm::OnDiskIterableChainedHashTable< EnumConstantTableInfo >
using SerializedTagTable = llvm::OnDiskIterableChainedHashTable< TagTableInfo >
using SerializedTypedefTable = llvm::OnDiskIterableChainedHashTable< TypedefTableInfo >
Public Member Functions
std::optional< IdentifierID > getIdentifier (llvm::StringRef Str)
Retrieve the identifier ID for the given string, or an empty optional if the string is unknown.
std::optional< SelectorID > getSelector (ObjCSelectorRef Selector)
Retrieve the selector ID for the given selector, or an empty optional if the string is unknown.
bool readControlBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readIdentifierBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readObjCContextBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readObjCPropertyBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readObjCMethodBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readObjCSelectorBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readGlobalVariableBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readGlobalFunctionBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readEnumConstantBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readTagBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
bool readTypedefBlock (llvm::BitstreamCursor &Cursor, llvm::SmallVectorImpl< uint64_t > &Scratch)
Public Attributes
llvm::MemoryBuffer * InputBuffer
The input buffer for the API notes data.
llvm::VersionTuple SwiftVersion
The Swift version to use for filtering.
std::string ModuleName
The name of the module that we read from the control block.
std::optional< std::pair< off_t, time_t > > SourceFileSizeAndModTime
std::unique_ptr< SerializedIdentifierTable > IdentifierTable
The identifier table.
std::unique_ptr< SerializedObjCContextIDTable > ObjCContextIDTable
The Objective-C context ID table.
std::unique_ptr< SerializedObjCContextInfoTable > ObjCContextInfoTable
The Objective-C context info table.
std::unique_ptr< SerializedObjCPropertyTable > ObjCPropertyTable
The Objective-C property table.
std::unique_ptr< SerializedObjCMethodTable > ObjCMethodTable
The Objective-C method table.
std::unique_ptr< SerializedObjCSelectorTable > ObjCSelectorTable
The Objective-C selector table.
std::unique_ptr< SerializedGlobalVariableTable > GlobalVariableTable
The global variable table.
std::unique_ptr< SerializedGlobalFunctionTable > GlobalFunctionTable
The global function table.
std::unique_ptr< SerializedEnumConstantTable > EnumConstantTable
The enumerator table.
std::unique_ptr< SerializedTagTable > TagTable
The tag table.
std::unique_ptr< SerializedTypedefTable > TypedefTable
The typedef table.
Detailed Description
Definition at line 589 of file APINotesReader.cpp.
Member Typedef Documentation
SerializedEnumConstantTable
using clang::api_notes::APINotesReader::Implementation::SerializedEnumConstantTable = llvm::OnDiskIterableChainedHashTable<EnumConstantTableInfo>
Definition at line 652 of file APINotesReader.cpp.
SerializedGlobalFunctionTable
using clang::api_notes::APINotesReader::Implementation::SerializedGlobalFunctionTable = llvm::OnDiskIterableChainedHashTable<GlobalFunctionTableInfo>
Definition at line 646 of file APINotesReader.cpp.
SerializedGlobalVariableTable
using clang::api_notes::APINotesReader::Implementation::SerializedGlobalVariableTable = llvm::OnDiskIterableChainedHashTable<GlobalVariableTableInfo>
Definition at line 640 of file APINotesReader.cpp.
SerializedIdentifierTable
using clang::api_notes::APINotesReader::Implementation::SerializedIdentifierTable = llvm::OnDiskIterableChainedHashTable<IdentifierTableInfo>
Definition at line 604 of file APINotesReader.cpp.
SerializedObjCContextIDTable
using clang::api_notes::APINotesReader::Implementation::SerializedObjCContextIDTable = llvm::OnDiskIterableChainedHashTable<ObjCContextIDTableInfo>
Definition at line 610 of file APINotesReader.cpp.
SerializedObjCContextInfoTable
using clang::api_notes::APINotesReader::Implementation::SerializedObjCContextInfoTable = llvm::OnDiskIterableChainedHashTable<ObjCContextInfoTableInfo>
Definition at line 616 of file APINotesReader.cpp.
SerializedObjCMethodTable
using clang::api_notes::APINotesReader::Implementation::SerializedObjCMethodTable = llvm::OnDiskIterableChainedHashTable<ObjCMethodTableInfo>
Definition at line 628 of file APINotesReader.cpp.
SerializedObjCPropertyTable
using clang::api_notes::APINotesReader::Implementation::SerializedObjCPropertyTable = llvm::OnDiskIterableChainedHashTable<ObjCPropertyTableInfo>
Definition at line 622 of file APINotesReader.cpp.
SerializedObjCSelectorTable
using clang::api_notes::APINotesReader::Implementation::SerializedObjCSelectorTable = llvm::OnDiskIterableChainedHashTable<ObjCSelectorTableInfo>
Definition at line 634 of file APINotesReader.cpp.
SerializedTagTable
using clang::api_notes::APINotesReader::Implementation::SerializedTagTable = llvm::OnDiskIterableChainedHashTable<TagTableInfo>
Definition at line 658 of file APINotesReader.cpp.
SerializedTypedefTable
using clang::api_notes::APINotesReader::Implementation::SerializedTypedefTable = llvm::OnDiskIterableChainedHashTable<TypedefTableInfo>
Definition at line 663 of file APINotesReader.cpp.
Member Function Documentation
getIdentifier()
std::optional< IdentifierID > clang::api_notes::APINotesReader::Implementation::getIdentifier (llvm::StringRef Str)
Retrieve the identifier ID for the given string, or an empty optional if the string is unknown.
Definition at line 702 of file APINotesReader.cpp.
References clang::IdentifierTable::end(), and clang::IdentifierTable::find().
getSelector()
std::optional< SelectorID > clang::api_notes::APINotesReader::Implementation::getSelector (ObjCSelectorRef Selector)
Retrieve the selector ID for the given selector, or an empty optional if the string is unknown.
Definition at line 717 of file APINotesReader.cpp.
References getIdentifier(), clang::api_notes::StoredObjCSelector::Identifiers, and clang::api_notes::StoredObjCSelector::NumArgs.
Referenced by clang::api_notes::APINotesReader::lookupObjCMethod().
readControlBlock()
bool clang::api_notes::APINotesReader::Implementation::readControlBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 739 of file APINotesReader.cpp.
References clang::api_notes::CONTROL_BLOCK_ID.
readEnumConstantBlock()
bool clang::api_notes::APINotesReader::Implementation::readEnumConstantBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 1373 of file APINotesReader.cpp.
References clang::api_notes::ENUM_CONSTANT_BLOCK_ID.
readGlobalFunctionBlock()
bool clang::api_notes::APINotesReader::Implementation::readGlobalFunctionBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 1297 of file APINotesReader.cpp.
References clang::api_notes::GLOBAL_FUNCTION_BLOCK_ID.
readGlobalVariableBlock()
bool clang::api_notes::APINotesReader::Implementation::readGlobalVariableBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 1221 of file APINotesReader.cpp.
References clang::api_notes::GLOBAL_VARIABLE_BLOCK_ID.
readIdentifierBlock()
bool clang::api_notes::APINotesReader::Implementation::readIdentifierBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 826 of file APINotesReader.cpp.
References clang::api_notes::IDENTIFIER_BLOCK_ID.
readObjCContextBlock()
bool clang::api_notes::APINotesReader::Implementation::readObjCContextBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 902 of file APINotesReader.cpp.
References clang::api_notes::OBJC_CONTEXT_BLOCK_ID.
readObjCMethodBlock()
bool clang::api_notes::APINotesReader::Implementation::readObjCMethodBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 1070 of file APINotesReader.cpp.
References clang::api_notes::OBJC_METHOD_BLOCK_ID.
readObjCPropertyBlock()
bool clang::api_notes::APINotesReader::Implementation::readObjCPropertyBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 993 of file APINotesReader.cpp.
References clang::api_notes::OBJC_PROPERTY_BLOCK_ID.
readObjCSelectorBlock()
bool clang::api_notes::APINotesReader::Implementation::readObjCSelectorBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 1145 of file APINotesReader.cpp.
References clang::api_notes::OBJC_SELECTOR_BLOCK_ID.
readTagBlock()
bool clang::api_notes::APINotesReader::Implementation::readTagBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 1449 of file APINotesReader.cpp.
References clang::api_notes::TAG_BLOCK_ID.
readTypedefBlock()
bool clang::api_notes::APINotesReader::Implementation::readTypedefBlock (llvm::BitstreamCursor & Cursor, llvm::SmallVectorImpl< uint64_t > & Scratch)
Definition at line 1524 of file APINotesReader.cpp.
References clang::api_notes::TYPEDEF_BLOCK_ID.
Member Data Documentation
EnumConstantTable
std::unique_ptr<SerializedEnumConstantTable> clang::api_notes::APINotesReader::Implementation::EnumConstantTable
The enumerator table.
Definition at line 656 of file APINotesReader.cpp.
GlobalFunctionTable
std::unique_ptr<SerializedGlobalFunctionTable> clang::api_notes::APINotesReader::Implementation::GlobalFunctionTable
The global function table.
Definition at line 650 of file APINotesReader.cpp.
GlobalVariableTable
std::unique_ptr<SerializedGlobalVariableTable> clang::api_notes::APINotesReader::Implementation::GlobalVariableTable
The global variable table.
Definition at line 644 of file APINotesReader.cpp.
IdentifierTable
std::unique_ptr<SerializedIdentifierTable> clang::api_notes::APINotesReader::Implementation::IdentifierTable
The identifier table.
Definition at line 608 of file APINotesReader.cpp.
InputBuffer
llvm::MemoryBuffer* clang::api_notes::APINotesReader::Implementation::InputBuffer
The input buffer for the API notes data.
Definition at line 592 of file APINotesReader.cpp.
Referenced by clang::api_notes::APINotesReader::~APINotesReader().
ModuleName
std::string clang::api_notes::APINotesReader::Implementation::ModuleName
The name of the module that we read from the control block.
Definition at line 598 of file APINotesReader.cpp.
ObjCContextIDTable
std::unique_ptr<SerializedObjCContextIDTable> clang::api_notes::APINotesReader::Implementation::ObjCContextIDTable
The Objective-C context ID table.
Definition at line 614 of file APINotesReader.cpp.
ObjCContextInfoTable
std::unique_ptr<SerializedObjCContextInfoTable> clang::api_notes::APINotesReader::Implementation::ObjCContextInfoTable
The Objective-C context info table.
Definition at line 620 of file APINotesReader.cpp.
ObjCMethodTable
std::unique_ptr<SerializedObjCMethodTable> clang::api_notes::APINotesReader::Implementation::ObjCMethodTable
The Objective-C method table.
Definition at line 632 of file APINotesReader.cpp.
Referenced by clang::api_notes::APINotesReader::lookupObjCMethod().
ObjCPropertyTable
std::unique_ptr<SerializedObjCPropertyTable> clang::api_notes::APINotesReader::Implementation::ObjCPropertyTable
The Objective-C property table.
Definition at line 626 of file APINotesReader.cpp.
ObjCSelectorTable
std::unique_ptr<SerializedObjCSelectorTable> clang::api_notes::APINotesReader::Implementation::ObjCSelectorTable
The Objective-C selector table.
Definition at line 638 of file APINotesReader.cpp.
SourceFileSizeAndModTime
std::optional<std::pair<off_t, time_t> > clang::api_notes::APINotesReader::Implementation::SourceFileSizeAndModTime
Definition at line 602 of file APINotesReader.cpp.
SwiftVersion
llvm::VersionTuple clang::api_notes::APINotesReader::Implementation::SwiftVersion
The Swift version to use for filtering.
Definition at line 595 of file APINotesReader.cpp.
Referenced by clang::api_notes::APINotesReader::lookupObjCMethod().
TagTable
std::unique_ptr<SerializedTagTable> clang::api_notes::APINotesReader::Implementation::TagTable
The tag table.
Definition at line 661 of file APINotesReader.cpp.
TypedefTable
std::unique_ptr<SerializedTypedefTable> clang::api_notes::APINotesReader::Implementation::TypedefTable
The typedef table.
Definition at line 667 of file APINotesReader.cpp.
The documentation for this class was generated from the following file:
lib/APINotes/APINotesReader.cpp