clang: clang::CodeGen::Address Class Reference
clang::CodeGen::Address Class Reference
Like RawAddress, an abstract representation of an aligned address, but the pointer contained in this class is possibly signed.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/Address.h"
Public Member Functions
Address (llvm::Value *pointer, llvm::Type *elementType, CharUnits alignment, KnownNonNull_t IsKnownNonNull=NotKnownNonNull)
Address (llvm::Value *BasePtr, llvm::Type *ElementType, CharUnits Alignment, llvm::Value *Offset, KnownNonNull_t IsKnownNonNull=NotKnownNonNull)
Address (RawAddress RawAddr)
bool isValid () const
void replaceBasePointer (llvm::Value *P)
This function is used in situations where the caller is doing some sort of opaque "laundering" of the pointer.
CharUnits getAlignment () const
void setAlignment (CharUnits Value)
llvm::Value * getBasePointer () const
llvm::PointerType * getType () const
Return the type of the pointer value.
llvm::Type * getElementType () const
Return the type of the values stored in this address.
unsigned getAddressSpace () const
Return the address space that this address resides in.
llvm::StringRef getName () const
Return the IR name of the pointer value.
void setElementType (llvm::Type *Ty)
KnownNonNull_t isKnownNonNull () const
Whether the pointer is known not to be null.
Address setKnownNonNull ()
bool hasOffset () const
llvm::Value * getOffset () const
llvm::Value * emitRawPointer (CodeGenFunction &CGF) const
Return the pointer contained in this class after authenticating it and adding offset to it if necessary.
Address withPointer (llvm::Value *NewPointer, KnownNonNull_t IsKnownNonNull) const
Return address with different pointer, but same element type and alignment.
Address withAlignment (CharUnits NewAlignment) const
Return address with different alignment, but same pointer and element type.
Address withElementType (llvm::Type *ElemTy) const
Return address with different element type, but same pointer and alignment.
Static Public Member Functions
static Address invalid ()
Protected Member Functions
Address (std::nullptr_t)
Friends
class CGBuilderTy
Detailed Description
Like RawAddress, an abstract representation of an aligned address, but the pointer contained in this class is possibly signed.
Definition at line 111 of file Address.h.
Constructor & Destructor Documentation
Address() [1/4]
clang::CodeGen::Address::Address (std::nullptr_t) inline protected
Definition at line 130 of file Address.h.
Referenced by invalid(), withAlignment(), withElementType(), and withPointer().
Address() [2/4]
clang::CodeGen::Address::Address (llvm::Value * pointer, llvm::Type * elementType, CharUnits alignment, KnownNonNull_t IsKnownNonNull = NotKnownNonNull) inline
Definition at line 133 of file Address.h.
References clang::CharUnits::isZero().
Address() [3/4]
clang::CodeGen::Address::Address (llvm::Value * BasePtr, llvm::Type * ElementType, CharUnits Alignment, llvm::Value * Offset, KnownNonNull_t IsKnownNonNull = NotKnownNonNull) inline
Definition at line 142 of file Address.h.
Address() [4/4]
clang::CodeGen::Address::Address (RawAddress RawAddr) inline
Definition at line 147 of file Address.h.
Member Function Documentation
emitRawPointer()
llvm::Value* clang::CodeGen::Address::emitRawPointer (CodeGenFunction & CGF) const inline
Return the pointer contained in this class after authenticating it and adding offset to it if necessary.
Definition at line 220 of file Address.h.
References getBasePointer().
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), clang::CodeGen::CGOpenMPRuntimeGPU::adjustTargetSpecificDataForLambdas(), ApplyNonVirtualAndVirtualOffset(), clang::CodeGen::CGObjCRuntime::canMessageReceiverBeNull(), clang::CodeGen::CGBuilderTy::CreateAtomicRMW(), CreateCoercedLoad(), CreateCoercedStore(), createLoadInstBefore(), createStoreInstBefore(), clang::CodeGen::CodeGenFunction::EmitAnyExprToExn(), emitARCCopyOperation(), clang::CodeGen::CodeGenFunction::EmitARCDestroyWeak(), emitARCLoadOperation(), emitARCStoreOperation(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrongCall(), EmitArrayDelete(), clang::CodeGen::CodeGenFunction::emitArrayLength(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), emitArraySubscriptGEP(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::emitBuiltinOSLogFormat(), clang::CodeGen::CodeGenFunction::emitByrefStructureInit(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCountedByFieldExpr(), clang::CodeGen::CodeGenFunction::EmitCXXAggrConstructorCall(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::emitDestroy(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), EmitDestroyingObjectDelete(), clang::CodeGen::CGOpenMPRuntime::emitDoacrossInit(), EmitDoacrossOrdered(), clang::CodeGen::CodeGenFunction::EmitFieldAnnotations(), clang::CodeGen::CodeGenFunction::EmitFieldSYCLAnnotations(), clang::CodeGen::CGOpenMPRuntime::emitForNext(), emitForStaticInitCall(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), emitGlobalToListCopyFunction(), emitGlobalToListReduceFunction(), clang::CodeGen::CodeGenFunction::EmitHexagonBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitIntelFPGAFieldAnnotations(), clang::CodeGen::CodeGenFunction::EmitLambdaStaticInvokeBody(), emitListToGlobalCopyFunction(), emitListToGlobalReduceFunction(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), emitNonZeroVLAInit(), clang::CodeGen::CodeGenFunction::EmitObjCBoxedExpr(), EmitObjectDelete(), clang::CodeGen::CodeGenFunction::EmitOMPAggregateAssign(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), emitOMPAtomicCompareExpr(), clang::CodeGen::CGOpenMPRuntime::emitParallelCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitParallelCall(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::LValue::emitRawPointer(), clang::CodeGen::AggValueSlot::emitRawPointer(), emitShuffleAndReduceFunction(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskwaitCall(), clang::CodeGen::CGOpenMPRuntimeGPU::emitTeamsCall(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarInit(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), clang::CodeGen::CGOpenMPRuntime::emitUpdateClause(), clang::CodeGen::EmitVAArgInstr(), clang::CodeGen::emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheckForCast(), emitWritebackArg(), EnterNewDeleteCleanup(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CodeGenFunction::GenerateBlockFunction(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::generateObjCGetterBody(), clang::CodeGen::RValue::get(), clang::CodeGen::CodeGenFunction::GetAddressOfDerivedClass(), clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), getPointerAndSize(), clang::CodeGen::LValue::getRawBitFieldPointer(), clang::CodeGen::LValue::getRawExtVectorPointer(), clang::CodeGen::LValue::getRawVectorPointer(), InitCatchParam(), performTypeAdjustment(), pushTemporaryCleanup(), clang::CodeGen::CGCXXABI::ReadArrayCookie(), clang::CodeGen::CodeGenFunction::recoverAddrOfEscapedLocal(), clang::CodeGen::DominatingLLVMValue::save(), clang::CodeGen::CodeGenFunction::setBeforeOutermostConditional(), clang::CodeGen::CodeGenFunction::OMPMapVars::setVarAddr(), shuffleAndStore(), clang::CodeGen::CodeGenFunction::StartFunction(), and wrapWithBPFPreserveStaticOffset().
getAddressSpace()
unsigned clang::CodeGen::Address::getAddressSpace () const inline
Return the address space that this address resides in.
Definition at line 190 of file Address.h.
References getType().
getAlignment()
CharUnits clang::CodeGen::Address::getAlignment () const inline
Definition at line 166 of file Address.h.
Referenced by ApplyNonVirtualAndVirtualOffset(), clang::CodeGen::CodeGenFunction::callCStructCopyAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructCopyConstructor(), clang::CodeGen::CodeGenFunction::callCStructDefaultConstructor(), clang::CodeGen::CodeGenFunction::callCStructDestructor(), clang::CodeGen::CodeGenFunction::callCStructMoveAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructMoveConstructor(), CheckAtomicAlignment(), clang::CodeGen::CGBuilderTy::CreateAtomicRMW(), CreateCoercedLoad(), CreateCoercedStore(), createLoadInstBefore(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), clang::CodeGen::CGBuilderTy::CreateMemCpyInline(), clang::CodeGen::CGBuilderTy::CreateMemMove(), clang::CodeGen::CGBuilderTy::CreateMemSet(), clang::CodeGen::CGBuilderTy::CreateMemSetInline(), clang::CodeGen::CGBuilderTy::CreateStore(), createStoreInstBefore(), clang::CodeGen::CodeGenFunction::CXXDefaultInitExprScope::CXXDefaultInitExprScope(), EmitArrayDelete(), clang::CodeGen::CodeGenFunction::emitArrayLength(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), emitArraySubscriptGEP(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitCXXAggrConstructorCall(), clang::CodeGen::CodeGenFunction::EmitCXXDeleteExpr(), clang::CodeGen::CodeGenFunction::EmitCXXMemberDataPointerAddress(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::emitDestroy(), clang::CodeGen::CodeGenFunction::EmitFieldAnnotations(), clang::CodeGen::CodeGenFunction::EmitFieldSYCLAnnotations(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), emitGlobalToListCopyFunction(), clang::CodeGen::CodeGenFunction::EmitHexagonBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitIntelFPGAFieldAnnotations(), emitListToGlobalCopyFunction(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), emitNonZeroVLAInit(), EmitNullBaseClassInitialization(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::CodeGenFunction::ParamValue::forIndirect(), clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), clang::CodeGen::LValue::getAlignment(), clang::CodeGen::AggValueSlot::getAlignment(), clang::CodeGen::CodeGenFunction::mergeAddressesInConditionalExpr(), clang::CodeGen::DominatingValue< Address >::save(), clang::CodeGen::CodeGenFunction::setBeforeOutermostConditional(), shuffleAndStore(), withElementType(), withPointer(), and wrapWithBPFPreserveStaticOffset().
getBasePointer()
llvm::Value* clang::CodeGen::Address::getBasePointer () const inline
Definition at line 170 of file Address.h.
References isValid(), and Pointer.
Referenced by clang::CodeGen::CGBuilderTy::CreateLaunderInvariantGroup(), clang::CodeGen::CGBuilderTy::CreatePreserveUnionAccessIndex(), clang::CodeGen::CGBuilderTy::CreateStripInvariantGroup(), clang::CodeGen::CodeGenFunction::CXXDefaultInitExprScope::CXXDefaultInitExprScope(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), emitRawPointer(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), emitWriteback(), emitWritebackArg(), findDominatingStoreToReturnValue(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::RValue::getAggregatePointer(), clang::CodeGen::CodeGenFunction::ParamValue::getAnyValue(), clang::CodeGen::CodeGenFunction::getAsNaturalPointerTo(), clang::CodeGen::LValue::getMatrixPointer(), clang::CodeGen::LValue::getPointer(), clang::CodeGen::LValue::getVectorPointer(), isProvablyNonNull(), clang::CodeGen::CodeGenFunction::mergeAddressesInConditionalExpr(), clang::CodeGen::DominatingValue< Address >::needsSaving(), clang::CodeGen::CodeGenFunction::recoverAddrOfEscapedLocal(), clang::CodeGen::DominatingValue< Address >::save(), tryRemoveRetainOfSelf(), and withElementType().
getElementType()
llvm::Type* clang::CodeGen::Address::getElementType () const inline
Return the type of the values stored in this address.
Definition at line 184 of file Address.h.
References isValid().
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), CheckAtomicAlignment(), CreateCoercedLoad(), CreateCoercedStore(), createLoadInstBefore(), emitARCStoreOperation(), clang::CodeGen::CodeGenFunction::EmitARCStoreStrongCall(), EmitArrayDelete(), clang::CodeGen::CodeGenFunction::emitArrayLength(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), emitArraySubscriptGEP(), clang::CodeGen::CodeGenFunction::EmitArrayToPointerDecay(), clang::CodeGen::CodeGenFunction::EmitAtomicCompareExchange(), clang::CodeGen::CodeGenFunction::EmitAtomicStore(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::emitByrefStructureInit(), clang::CodeGen::CodeGenFunction::EmitCall(), EmitCheckedMixedSignMultiply(), clang::CodeGen::CodeGenFunction::EmitCXXAggrConstructorCall(), clang::CodeGen::CodeGenFunction::EmitCXXDeleteExpr(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::emitDestroy(), clang::CodeGen::CGOpenMPRuntime::emitDestroyClause(), clang::CodeGen::CodeGenFunction::EmitFieldAnnotations(), clang::CodeGen::CodeGenFunction::EmitFieldSYCLAnnotations(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::CodeGenFunction::EmitIntelFPGAFieldAnnotations(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitMSVCBuiltinExpr(), clang::CodeGen::CodeGenFunction::EmitMustTailThunk(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), emitNonZeroVLAInit(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), clang::CodeGen::CodeGenFunction::EmitObjCMessageExpr(), clang::CodeGen::CodeGenFunction::EmitOMPAggregateAssign(), EmitOMPAggregateInit(), EmitOMPAggregateReduction(), emitOMPArraySectionBase(), emitOMPAtomicCompareExpr(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::CodeGenFunction::EmitScalarInit(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::CodeGenFunction::EmitStoreThroughBitfieldLValue(), clang::CodeGen::CodeGenFunction::EmitStoreThroughExtVectorComponentLValue(), clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue(), clang::CodeGen::emitVoidPtrDirectVAArg(), emitWriteback(), EnterStructPointerForCoercedAccess(), findDominatingStoreToReturnValue(), clang::CodeGen::CodeGenFunction::GetAddressOfDerivedClass(), clang::CodeGen::CGOpenMPRuntime::getAddrOfThreadPrivate(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), getNullForVariable(), getPointerAndSize(), clang::CodeGen::DominatingValue< Address >::save(), shuffleAndStore(), tryEmitARCCopyWeakInit(), withAlignment(), withPointer(), and wrapWithBPFPreserveStaticOffset().
getName()
llvm::StringRef clang::CodeGen::Address::getName () const inline
Return the IR name of the pointer value.
Definition at line 193 of file Address.h.
References Pointer.
Referenced by CreateCoercedLoad(), clang::CodeGen::CodeGenFunction::emitAddrOfImagComponent(), clang::CodeGen::CodeGenFunction::emitAddrOfRealComponent(), clang::CodeGen::CodeGenFunction::EmitCall(), and clang::CodeGen::CodeGenFunction::recoverAddrOfEscapedLocal().
getOffset()
llvm::Value* clang::CodeGen::Address::getOffset () const inline
Definition at line 216 of file Address.h.
References Offset.
Referenced by clang::CodeGen::DominatingValue< Address >::needsSaving(), and clang::CodeGen::DominatingValue< Address >::save().
getType()
llvm::PointerType* clang::CodeGen::Address::getType () const inline
Return the type of the pointer value.
Definition at line 176 of file Address.h.
References Pointer.
Referenced by clang::CodeGen::ReductionCodeGen::adjustPrivateAddress(), castToBase(), emitARCCopyOperation(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::ReductionCodeGen::emitInitialization(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), emitNonZeroVLAInit(), clang::CodeGen::CodeGenFunction::EmitOMPFirstprivateClause(), emitOutlinedFunctionPrologue(), EmitPointerWithAlignment(), emitPseudoObjectExpr(), getAddressSpace(), clang::CodeGen::CodeGenFunction::mergeAddressesInConditionalExpr(), clang::CodeGen::CodeGenFunction::recoverAddrOfEscapedLocal(), clang::CodeGen::DominatingValue< Address >::save(), shuffleAndStore(), and clang::CodeGen::CodeGenFunction::StartFunction().
hasOffset()
bool clang::CodeGen::Address::hasOffset () const inline
Definition at line 214 of file Address.h.
References Offset.
Referenced by clang::CodeGen::CodeGenFunction::ParamValue::getAnyValue(), setElementType(), and withElementType().
invalid()
static Address clang::CodeGen::Address::invalid () inline static
Definition at line 153 of file Address.h.
References Address().
Referenced by castToBase(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCXXMemberPointerCallExpr(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitCXXPseudoDestructorExpr(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), emitDeclTargetVarDeclLValue(), clang::CodeGen::CGOpenMPRuntime::emitDependClause(), clang::CodeGen::CGOpenMPRuntime::emitDepobjDependClause(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), emitInterWarpCopyFunction(), clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr(), clang::CodeGen::ABIInfo::EmitMSVAArg(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), clang::CodeGen::CodeGenFunction::EmitObjCIsaExpr(), EmitOMPAggregateInit(), clang::CodeGen::CodeGenFunction::EmitOMPArraySectionExpr(), clang::CodeGen::CodeGenFunction::EmitOMPCopyinClause(), clang::CodeGen::CodeGenFunction::EmitOMPLastprivateClauseInit(), emitOutlinedFunctionPrologue(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::CodeGenFunction::EmitPointerToDataMemberBinaryExpr(), clang::CodeGen::CodeGenFunction::EmitReturnValueCheck(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CGOpenMPRuntime::emitTaskCall(), clang::CodeGen::CGOpenMPRuntime::emitTaskInit(), clang::CodeGen::CGOpenMPRuntime::emitTaskwaitCall(), clang::CodeGen::emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::CGOpenMPRuntime::getAddressOfLocalVariable(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPSIMDRuntime::getAddressOfLocalVariable(), clang::CodeGen::CGOpenMPRuntimeGPU::getAddressOfLocalVariable(), clang::CodeGen::AggValueSlot::ignored(), clang::CodeGen::CGCXXABI::InitializeArrayCookie(), clang::CodeGen::CodeGenFunction::InlinedInheritingConstructorScope::InlinedInheritingConstructorScope(), clang::CodeGen::LValue::MakeGlobalReg(), clang::CodeGen::CodeGenFunction::PopCleanupBlock(), clang::CodeGen::CodeGenFunction::pushLifetimeExtendedDestroy(), clang::CodeGen::CodeGenFunction::OMPMapVars::setVarAddr(), and clang::CodeGen::CodeGenFunction::StartFunction().
isKnownNonNull()
KnownNonNull_t clang::CodeGen::Address::isKnownNonNull () const inline
Whether the pointer is known not to be null.
Definition at line 203 of file Address.h.
References isValid(), and Pointer.
Referenced by clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), withAlignment(), and withElementType().
isValid()
bool clang::CodeGen::Address::isValid () const inline
Definition at line 154 of file Address.h.
References Pointer.
Referenced by castToBase(), CheckAggExprForMemSetUse(), clang::CodeGen::CodeGenFunction::EmitAggExpr(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), clang::CodeGen::CodeGenFunction::EmitCall(), EmitCleanup(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), EmitGlobalVarDeclLValue(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), emitPrivatesInit(), clang::CodeGen::LValue::emitRawPointer(), clang::CodeGen::AggValueSlot::emitRawPointer(), clang::CodeGen::CGOpenMPRuntime::emitSingleRegion(), clang::CodeGen::CodeGenFunction::FinishFunction(), clang::CodeGen::AggValueSlot::forAddr(), getBasePointer(), getElementType(), clang::CodeGen::EHCleanupScope::hasActiveFlag(), clang::CodeGen::AggValueSlot::isIgnored(), isKnownNonNull(), clang::CodeGen::ReturnValueSlot::isNull(), replaceBasePointer(), and setKnownNonNull().
replaceBasePointer()
void clang::CodeGen::Address::replaceBasePointer (llvm::Value * P) inline
This function is used in situations where the caller is doing some sort of opaque "laundering" of the pointer.
Definition at line 158 of file Address.h.
References isValid(), P, and Pointer.
Referenced by clang::CodeGen::CGBuilderTy::CreateLaunderInvariantGroup(), clang::CodeGen::CGBuilderTy::CreatePreserveUnionAccessIndex(), clang::CodeGen::CGBuilderTy::CreateStripInvariantGroup(), and clang::CodeGen::CodeGenFunction::mergeAddressesInConditionalExpr().
setAlignment()
void clang::CodeGen::Address::setAlignment (CharUnits Value) inline
Definition at line 168 of file Address.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::mergeAddressesInConditionalExpr(), and clang::CodeGen::LValue::setAlignment().
setElementType()
void clang::CodeGen::Address::setElementType (llvm::Type * Ty) inline
Definition at line 196 of file Address.h.
References hasOffset().
setKnownNonNull()
Address clang::CodeGen::Address::setKnownNonNull () inline
Definition at line 208 of file Address.h.
References isValid(), clang::CodeGen::KnownNonNull, and Pointer.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXDeleteExpr(), clang::CodeGen::CodeGenFunction::EmitPointerWithAlignment(), and clang::CodeGen::AggValueSlot::forAddr().
withAlignment()
Address clang::CodeGen::Address::withAlignment (CharUnits NewAlignment) const inline
Return address with different alignment, but same pointer and element type.
Definition at line 234 of file Address.h.
References Address(), getElementType(), isKnownNonNull(), and Pointer.
Referenced by CheckAtomicAlignment(), emitOutlinedFunctionPrologue(), and emitPrivatesInit().
withElementType()
Address clang::CodeGen::Address::withElementType (llvm::Type * ElemTy) const inline
Return address with different element type, but same pointer and alignment.
Definition at line 241 of file Address.h.
References Address(), getAlignment(), getBasePointer(), hasOffset(), and isKnownNonNull().
Referenced by castValueToType(), CheckAggExprForMemSetUse(), complexTempStructure(), CreateCoercedLoad(), CreateCoercedStore(), clang::CodeGen::CodeGenFunction::defaultInitNonTrivialCStructVar(), emitAddressAtOffset(), clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::EmitAnyExprToExn(), clang::CodeGen::CodeGenFunction::emitArrayLength(), clang::CodeGen::CodeGenFunction::EmitArrayToPointerDecay(), EmitAtomicCmpXchg128ForMSIntrin(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), clang::CodeGen::CodeGenFunction::EmitAutoVarInit(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::ReductionCodeGen::emitCleanups(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitExtVectorElementLValue(), clang::CodeGen::CodeGenFunction::EmitFunctionEpilog(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), emitNonZeroVLAInit(), EmitNullBaseClassInitialization(), clang::CodeGen::CodeGenFunction::EmitNullInitialization(), clang::CodeGen::CodeGenFunction::EmitObjCIsaExpr(), clang::CodeGen::CodeGenFunction::EmitOMPAggregateAssign(), emitOMPArraySectionBase(), clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), clang::CodeGen::CodeGenFunction::EmitOMPUseDeviceAddrClause(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), EmitThreadPrivateVarDeclLValue(), clang::CodeGen::emitVoidPtrDirectVAArg(), clang::CodeGen::CodeGenFunction::generateObjCGetterBody(), clang::CodeGen::CodeGenFunction::generateObjCSetterBody(), clang::CodeGen::CodeGenFunction::GetAddressOfDerivedClass(), clang::CodeGen::CGOpenMPRuntime::getDepobjElements(), clang::CodeGen::CodeGenFunction::InitializeVTablePointer(), loadToBegin(), performTypeAdjustment(), clang::CodeGen::CGCXXABI::ReadArrayCookie(), and tryEmitARCCopyWeakInit().
withPointer()
Address clang::CodeGen::Address::withPointer (llvm::Value * NewPointer, KnownNonNull_t IsKnownNonNull) const inline
Return address with different pointer, but same element type and alignment.
Definition at line 226 of file Address.h.
References Address(), getAlignment(), and getElementType().
Referenced by castToBase(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::EmitLoadOfScalar(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), and clang::CodeGen::CodeGenFunction::recoverAddrOfEscapedLocal().
Friends And Related Function Documentation
CGBuilderTy
friend class CGBuilderTy friend
Definition at line 112 of file Address.h.
The documentation for this class was generated from the following file:
lib/CodeGen/Address.h