clang: clang::ento::BugReporterContext Class Reference
clang::ento::BugReporterContext Class Reference
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
Public Member Functions
BugReporterContext (PathSensitiveBugReporter &br)
virtual ~BugReporterContext ()=default
PathSensitiveBugReporter & getBugReporter ()
const PathSensitiveBugReporter & getBugReporter () const
ProgramStateManager & getStateManager () const
ASTContext & getASTContext () const
const SourceManager & getSourceManager () const
const AnalyzerOptions & getAnalyzerOptions () const
Detailed Description
Definition at line 716 of file BugReporter.h.
Constructor & Destructor Documentation
BugReporterContext()
clang::ento::BugReporterContext::BugReporterContext (PathSensitiveBugReporter & br) inline
Definition at line 722 of file BugReporter.h.
~BugReporterContext()
virtual clang::ento::BugReporterContext::~BugReporterContext () virtual default
Member Function Documentation
getAnalyzerOptions()
const AnalyzerOptions& clang::ento::BugReporterContext::getAnalyzerOptions () const inline
Definition at line 741 of file BugReporter.h.
References clang::ento::BugReporter::getAnalyzerOptions().
Referenced by constructDebugPieceForTrackedCondition().
getASTContext()
ASTContext& clang::ento::BugReporterContext::getASTContext () const inline
Definition at line 733 of file BugReporter.h.
References clang::ento::BugReporter::getContext().
Referenced by constructDebugPieceForTrackedCondition(), clang::ento::FalsePositiveRefutationBRVisitor::finalizeVisitor(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), getMacroName(), and clang::ento::ConditionBRVisitor::patternMatch().
getBugReporter() [1/2]
PathSensitiveBugReporter& clang::ento::BugReporterContext::getBugReporter () inline
Definition at line 726 of file BugReporter.h.
getBugReporter() [2/2]
const PathSensitiveBugReporter& clang::ento::BugReporterContext::getBugReporter () const inline
Definition at line 727 of file BugReporter.h.
getSourceManager()
const SourceManager& clang::ento::BugReporterContext::getSourceManager () const inline
Definition at line 737 of file BugReporter.h.
References clang::ento::BugReporter::getSourceManager().
Referenced by constructDebugPieceForTrackedCondition(), clang::ento::bugreporter::StoreHandler::constructNote(), getMacroName(), clang::ento::ConditionBRVisitor::patternMatch(), clang::ento::ConditionBRVisitor::VisitConditionVariable(), clang::ento::TrackConstraintBRVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::TagVisitor::VisitNode(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
getStateManager()
ProgramStateManager& clang::ento::BugReporterContext::getStateManager () const inline
Definition at line 729 of file BugReporter.h.
References clang::ento::PathSensitiveBugReporter::getStateManager().
Referenced by clang::ento::NoStateChangeFuncVisitor::VisitNode(), clang::ento::UndefOrNullArgVisitor::VisitNode(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), and clang::ento::ConditionBRVisitor::VisitTrueTest().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h
lib/StaticAnalyzer/Core/BugReporter.cpp