clang: clang::MultiplexExternalSemaSource Class Reference
clang::MultiplexExternalSemaSource Class Reference
An abstract interface that should be implemented by external AST sources that also provide information for semantic analysis.
#include "clang/Sema/MultiplexExternalSemaSource.h"
Public Member Functions
MultiplexExternalSemaSource (ExternalSemaSource *S1, ExternalSemaSource *S2)
Constructs a new multiplexing external sema source and appends the given element to it.
~MultiplexExternalSemaSource () override
void AddSource (ExternalSemaSource *Source)
Appends new source to the source list.
Decl * GetExternalDecl (Decl::DeclID ID) override
Resolve a declaration ID into a declaration, potentially building a new declaration.
void CompleteRedeclChain (const Decl *D) override
Complete the redeclaration chain if it's been extended since the previous generation of the AST source.
Selector GetExternalSelector (uint32_t ID) override
Resolve a selector ID into a selector.
uint32_t GetNumExternalSelectors () override
Returns the number of selectors known to the external AST source.
Stmt * GetExternalDeclStmt (uint64_t Offset) override
Resolve the offset of a statement in the decl stream into a statement.
CXXBaseSpecifier * GetExternalCXXBaseSpecifiers (uint64_t Offset) override
Resolve the offset of a set of C++ base specifiers in the decl stream into an array of specifiers.
CXXCtorInitializer ** GetExternalCXXCtorInitializers (uint64_t Offset) override
Resolve a handle to a list of ctor initializers into the list of initializers themselves.
ExtKind hasExternalDefinitions (const Decl *D) override
bool FindExternalVisibleDeclsByName (const DeclContext *DC, DeclarationName Name) override
Find all declarations with the given name in the given context.
void completeVisibleDeclsMap (const DeclContext *DC) override
Ensures that the table of all visible declarations inside this context is up to date.
void FindExternalLexicalDecls (const DeclContext *DC, llvm::function_ref< bool(Decl::Kind)> IsKindWeWant, SmallVectorImpl< Decl * > &Result) override
Finds all declarations lexically contained within the given DeclContext, after applying an optional filter predicate.
void FindFileRegionDecls (FileID File, unsigned Offset, unsigned Length, SmallVectorImpl< Decl * > &Decls) override
Get the decls that are contained in a file in the Offset/Length range.
void CompleteType (TagDecl *Tag) override
Gives the external AST source an opportunity to complete an incomplete type.
void CompleteType (ObjCInterfaceDecl *Class) override
Gives the external AST source an opportunity to complete an incomplete Objective-C class.
void ReadComments () override
Loads comment ranges.
void StartedDeserializing () override
Notify ExternalASTSource that we started deserialization of a decl or type so until FinishedDeserializing is called there may be decls that are initializing.
void FinishedDeserializing () override
Notify ExternalASTSource that we finished the deserialization of a decl or type.
void StartTranslationUnit (ASTConsumer *Consumer) override
Function that will be invoked when we begin parsing a new translation unit involving this external AST source.
void PrintStats () override
Print any statistics that have been gathered regarding the external AST source.
Module * getModule (unsigned ID) override
Retrieve the module that corresponds to the given module ID.
bool layoutRecordType (const RecordDecl *Record, uint64_t &Size, uint64_t &Alignment, llvm::DenseMap< const FieldDecl *, uint64_t > &FieldOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > &BaseOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > &VirtualBaseOffsets) override
Perform layout on the given record.
void getMemoryBufferSizes (MemoryBufferSizes &sizes) const override
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
void InitializeSema (Sema &S) override
Initialize the semantic source with the Sema instance being used to perform semantic analysis on the abstract syntax tree.
void ForgetSema () override
Inform the semantic consumer that Sema is no longer available.
void ReadMethodPool (Selector Sel) override
Load the contents of the global method pool for a given selector.
void updateOutOfDateSelector (Selector Sel) override
Load the contents of the global method pool for a given selector if necessary.
void ReadKnownNamespaces (SmallVectorImpl< NamespaceDecl * > &Namespaces) override
Load the set of namespaces that are known to the external source, which will be used during typo correction.
void ReadUndefinedButUsed (llvm::MapVector< NamedDecl *, SourceLocation > &Undefined) override
Load the set of used but not defined functions or variables with internal linkage, or used but not defined inline functions.
void ReadMismatchingDeleteExpressions (llvm::MapVector< FieldDecl *, llvm::SmallVector< std::pair< SourceLocation, bool >, 4 >> &Exprs) override
bool LookupUnqualified (LookupResult &R, Scope *S) override
Do last resort, unqualified lookup on a LookupResult that Sema cannot find.
void ReadTentativeDefinitions (SmallVectorImpl< VarDecl * > &Defs) override
Read the set of tentative definitions known to the external Sema source.
void ReadUnusedFileScopedDecls (SmallVectorImpl< const DeclaratorDecl * > &Decls) override
Read the set of unused file-scope declarations known to the external Sema source.
void ReadDelegatingConstructors (SmallVectorImpl< CXXConstructorDecl * > &Decls) override
Read the set of delegating constructors known to the external Sema source.
void ReadExtVectorDecls (SmallVectorImpl< TypedefNameDecl * > &Decls) override
Read the set of ext_vector type declarations known to the external Sema source.
void ReadUnusedLocalTypedefNameCandidates (llvm::SmallSetVector< const TypedefNameDecl *, 4 > &Decls) override
Read the set of potentially unused typedefs known to the source.
void ReadReferencedSelectors (SmallVectorImpl< std::pair< Selector, SourceLocation > > &Sels) override
Read the set of referenced selectors known to the external Sema source.
void ReadWeakUndeclaredIdentifiers (SmallVectorImpl< std::pair< IdentifierInfo *, WeakInfo > > &WI) override
Read the set of weak, undeclared identifiers known to the external Sema source.
void ReadUsedVTables (SmallVectorImpl< ExternalVTableUse > &VTables) override
Read the set of used vtables known to the external Sema source.
void ReadPendingInstantiations (SmallVectorImpl< std::pair< ValueDecl *, SourceLocation > > &Pending) override
Read the set of pending instantiations known to the external Sema source.
void ReadLateParsedTemplates (llvm::MapVector< const FunctionDecl *, std::unique_ptr< LateParsedTemplate >> &LPTMap) override
Read the set of late parsed template functions for this source.
void ReadDeclsToCheckForDeferredDiags (llvm::SmallSetVector< Decl *, 4 > &Decls) override
Read the set of decls to be checked for deferred diags.
TypoCorrection CorrectTypo (const DeclarationNameInfo &Typo, int LookupKind, Scope *S, CXXScopeSpec *SS, CorrectionCandidateCallback &CCC, DeclContext *MemberContext, bool EnteringContext, const ObjCObjectPointerType *OPT) override
Try to "correct" a typo in the source code by finding visible declarations whose names are similar to the name that was present in the source code.
bool MaybeDiagnoseMissingCompleteType (SourceLocation Loc, QualType T) override
Produces a diagnostic note if one of the attached sources contains a complete definition for T.
void AssignedLambdaNumbering (const CXXRecordDecl *Lambda) override
Notify the external source that a lambda was assigned a mangling number.
Public Member Functions inherited from clang::ExternalSemaSource
ExternalSemaSource ()=default
~ExternalSemaSource () override
Public Member Functions inherited from clang::ExternalASTSource
ExternalASTSource ()=default
virtual ~ExternalASTSource ()
uint32_t getGeneration () const
Get the current generation of this AST source.
virtual void updateOutOfDateIdentifier (const IdentifierInfo &II)
Update an out-of-date identifier.
virtual std::optional< ASTSourceDescriptor > getSourceDescriptor (unsigned ID)
Return a descriptor for the corresponding module, if one exists.
void FindExternalLexicalDecls (const DeclContext *DC, SmallVectorImpl< Decl * > &Result)
Finds all declarations lexically contained within the given DeclContext.
MemoryBufferSizes getMemoryBufferSizes () const
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
bool isA (const void *ClassID) const override
LLVM-style RTTI.
static bool classof (const ExternalASTSource *S)
Additional Inherited Members
Public Types inherited from clang::ExternalASTSource
enum ExtKind { EK_Always , EK_Never , EK_ReplyHazy }
Static Public Member Functions inherited from clang::ExternalSemaSource
static bool classof (const ExternalASTSource *S)
Static Public Member Functions inherited from clang::ExternalASTSource
static bool classof (const ExternalASTSource *S)
Protected Member Functions inherited from clang::ExternalASTSource
uint32_t incrementGeneration (ASTContext &C)
Increment the current generation.
Static Protected Member Functions inherited from clang::ExternalASTSource
static DeclContextLookupResult SetExternalVisibleDeclsForName (const DeclContext *DC, DeclarationName Name, ArrayRef< NamedDecl * > Decls)
static DeclContextLookupResult SetNoExternalVisibleDeclsForName (const DeclContext *DC, DeclarationName Name)
Detailed Description
An abstract interface that should be implemented by external AST sources that also provide information for semantic analysis.
Definition at line 38 of file MultiplexExternalSemaSource.h.
Constructor & Destructor Documentation
MultiplexExternalSemaSource()
MultiplexExternalSemaSource::MultiplexExternalSemaSource (ExternalSemaSource * S1, ExternalSemaSource * S2)
Constructs a new multiplexing external sema source and appends the given element to it.
Parameters
[in] S1 - A non-null (old) ExternalSemaSource.
[in] S2 - A non-null (new) ExternalSemaSource.
Definition at line 22 of file MultiplexExternalSemaSource.cpp.
~MultiplexExternalSemaSource()
MultiplexExternalSemaSource::~MultiplexExternalSemaSource () override
Definition at line 31 of file MultiplexExternalSemaSource.cpp.
Member Function Documentation
AddSource()
void MultiplexExternalSemaSource::AddSource (ExternalSemaSource * Source)
Appends new source to the source list.
Parameters
[in] Source - An ExternalSemaSource.
[in] source - An ExternalSemaSource.
Definition at line 40 of file MultiplexExternalSemaSource.cpp.
AssignedLambdaNumbering()
void MultiplexExternalSemaSource::AssignedLambdaNumbering (const CXXRecordDecl * Lambda) override virtual
Notify the external source that a lambda was assigned a mangling number.
This enables the external source to track the correspondence between lambdas and mangling numbers if necessary.
Reimplemented from clang::ExternalSemaSource.
Definition at line 345 of file MultiplexExternalSemaSource.cpp.
classof()
static bool clang::MultiplexExternalSemaSource::classof (const ExternalASTSource * S) inline static
Definition at line 371 of file MultiplexExternalSemaSource.h.
CompleteRedeclChain()
void MultiplexExternalSemaSource::CompleteRedeclChain (const Decl * D) override virtual
Complete the redeclaration chain if it's been extended since the previous generation of the AST source.
Reimplemented from clang::ExternalASTSource.
Definition at line 56 of file MultiplexExternalSemaSource.cpp.
CompleteType() [1/2]
void MultiplexExternalSemaSource::CompleteType (ObjCInterfaceDecl * Class) override virtual
Gives the external AST source an opportunity to complete an incomplete Objective-C class.
This routine will only be invoked if the "externally completed" bit is set on the ObjCInterfaceDecl via the function ObjCInterfaceDecl::setExternallyCompleted().
Reimplemented from clang::ExternalASTSource.
Definition at line 143 of file MultiplexExternalSemaSource.cpp.
References clang::Class, and CompleteType().
CompleteType() [2/2]
void MultiplexExternalSemaSource::CompleteType (TagDecl * Tag) override virtual
Gives the external AST source an opportunity to complete an incomplete type.
Reimplemented from clang::ExternalASTSource.
Definition at line 138 of file MultiplexExternalSemaSource.cpp.
Referenced by CompleteType().
completeVisibleDeclsMap()
void MultiplexExternalSemaSource::completeVisibleDeclsMap (const DeclContext * DC) override virtual
Ensures that the table of all visible declarations inside this context is up to date.
Reimplemented from clang::ExternalASTSource.
Definition at line 118 of file MultiplexExternalSemaSource.cpp.
CorrectTypo()
TypoCorrection MultiplexExternalSemaSource::CorrectTypo (const DeclarationNameInfo & Typo, int LookupKind, Scope * S, CXXScopeSpec * SS, CorrectionCandidateCallback & CCC, DeclContext * MemberContext, bool EnteringContext, const ObjCObjectPointerType * OPT) override virtual
Try to "correct" a typo in the source code by finding visible declarations whose names are similar to the name that was present in the source code.
Parameters
TypoName the DeclarationNameInfo structure that contains the name that was present in the source code along with its location.
LookupKind the name-lookup criteria used to search for the name.
S the scope in which name lookup occurs.
SS the nested-name-specifier that precedes the name we're looking for, if present.
CCC A CorrectionCandidateCallback object that provides further validation of typo correction candidates. It also provides flags for determining the set of keywords permitted.
MemberContext if non-NULL, the context in which to look for a member access expression.
EnteringContext whether we're entering the context described by the nested-name-specifier SS.
OPT when non-NULL, the search for visible declarations will also walk the protocols in the qualified interfaces of OPT.
Returns
a TypoCorrection containing the corrected name if the typo along with information such as the NamedDecl where the corrected name was declared, and any additional NestedNameSpecifier needed to access it (C++ only). The TypoCorrection is empty if there is no correction.
Note
LookupKind must correspond to a valid Sema::LookupNameKind
ExternalSemaSource::CorrectTypo is always given the first chance to correct a typo (really, to offer suggestions to repair a failed lookup). It will even be called when SpellChecking is turned off or after a fatal error has already been detected.
Note
Returns the first nonempty correction.
Reimplemented from clang::ExternalSemaSource.
Definition at line 320 of file MultiplexExternalSemaSource.cpp.
FindExternalLexicalDecls()
void MultiplexExternalSemaSource::FindExternalLexicalDecls (const DeclContext * DC, llvm::function_ref< bool(Decl::Kind)> IsKindWeWant, SmallVectorImpl< Decl * > & Result) override virtual
Finds all declarations lexically contained within the given DeclContext, after applying an optional filter predicate.
Parameters
IsKindWeWant a predicate function that returns true if the passed declaration kind is one we are looking for.
Reimplemented from clang::ExternalASTSource.
Definition at line 123 of file MultiplexExternalSemaSource.cpp.
FindExternalVisibleDeclsByName()
bool MultiplexExternalSemaSource::FindExternalVisibleDeclsByName (const DeclContext * DC, DeclarationName Name) override virtual
Find all declarations with the given name in the given context.
Reimplemented from clang::ExternalASTSource.
Definition at line 110 of file MultiplexExternalSemaSource.cpp.
FindFileRegionDecls()
void MultiplexExternalSemaSource::FindFileRegionDecls (FileID File, unsigned Offset, unsigned Length, SmallVectorImpl< Decl * > & Decls) override virtual
Get the decls that are contained in a file in the Offset/Length range.
Length can be 0 to indicate a point at Offset instead of a range.
Reimplemented from clang::ExternalASTSource.
Definition at line 130 of file MultiplexExternalSemaSource.cpp.
References clang::File, and Offset.
FinishedDeserializing()
void MultiplexExternalSemaSource::FinishedDeserializing () override virtual
Notify ExternalASTSource that we finished the deserialization of a decl or type.
Must be paired with StartedDeserializing.
Reimplemented from clang::ExternalASTSource.
Definition at line 158 of file MultiplexExternalSemaSource.cpp.
ForgetSema()
void MultiplexExternalSemaSource::ForgetSema () override virtual
Inform the semantic consumer that Sema is no longer available.
Reimplemented from clang::ExternalSemaSource.
Definition at line 210 of file MultiplexExternalSemaSource.cpp.
GetExternalCXXBaseSpecifiers()
CXXBaseSpecifier * MultiplexExternalSemaSource::GetExternalCXXBaseSpecifiers (uint64_t Offset) override virtual
Resolve the offset of a set of C++ base specifiers in the decl stream into an array of specifiers.
Reimplemented from clang::ExternalASTSource.
Definition at line 85 of file MultiplexExternalSemaSource.cpp.
References Offset.
GetExternalCXXCtorInitializers()
CXXCtorInitializer ** MultiplexExternalSemaSource::GetExternalCXXCtorInitializers (uint64_t Offset) override virtual
Resolve a handle to a list of ctor initializers into the list of initializers themselves.
Reimplemented from clang::ExternalASTSource.
Definition at line 94 of file MultiplexExternalSemaSource.cpp.
GetExternalDecl()
Decl * MultiplexExternalSemaSource::GetExternalDecl (Decl::DeclID ID) override virtual
Resolve a declaration ID into a declaration, potentially building a new declaration.
Reimplemented from clang::ExternalASTSource.
Definition at line 49 of file MultiplexExternalSemaSource.cpp.
GetExternalDeclStmt()
Stmt * MultiplexExternalSemaSource::GetExternalDeclStmt (uint64_t Offset) override virtual
Resolve the offset of a statement in the decl stream into a statement.
Reimplemented from clang::ExternalASTSource.
Definition at line 78 of file MultiplexExternalSemaSource.cpp.
References Offset.
GetExternalSelector()
Selector MultiplexExternalSemaSource::GetExternalSelector (uint32_t ID) override virtual
Resolve a selector ID into a selector.
Reimplemented from clang::ExternalASTSource.
Definition at line 61 of file MultiplexExternalSemaSource.cpp.
References clang::Selector::isNull().
getMemoryBufferSizes()
void MultiplexExternalSemaSource::getMemoryBufferSizes (MemoryBufferSizes & sizes) const override virtual
Return the amount of memory used by memory buffers, breaking down by heap-backed versus mmap'ed memory.
Reimplemented from clang::ExternalASTSource.
Definition at line 193 of file MultiplexExternalSemaSource.cpp.
References clang::ExternalASTSource::getMemoryBufferSizes().
getModule()
Module * MultiplexExternalSemaSource::getModule (unsigned ID) override virtual
Retrieve the module that corresponds to the given module ID.
Reimplemented from clang::ExternalASTSource.
Definition at line 173 of file MultiplexExternalSemaSource.cpp.
GetNumExternalSelectors()
uint32_t MultiplexExternalSemaSource::GetNumExternalSelectors () override virtual
Returns the number of selectors known to the external AST source.
Reimplemented from clang::ExternalASTSource.
Definition at line 71 of file MultiplexExternalSemaSource.cpp.
hasExternalDefinitions()
ExternalASTSource::ExtKind MultiplexExternalSemaSource::hasExternalDefinitions (const Decl * D) override virtual
Reimplemented from clang::ExternalASTSource.
Definition at line 102 of file MultiplexExternalSemaSource.cpp.
InitializeSema()
void MultiplexExternalSemaSource::InitializeSema (Sema & S) override virtual
Initialize the semantic source with the Sema instance being used to perform semantic analysis on the abstract syntax tree.
Reimplemented from clang::ExternalSemaSource.
Definition at line 205 of file MultiplexExternalSemaSource.cpp.
isA()
bool clang::MultiplexExternalSemaSource::isA (const void * ClassID) const inline override virtual
LLVM-style RTTI.
Reimplemented from clang::ExternalSemaSource.
Definition at line 368 of file MultiplexExternalSemaSource.h.
References clang::ExternalSemaSource::isA().
layoutRecordType()
bool MultiplexExternalSemaSource::layoutRecordType (const RecordDecl * Record, uint64_t & Size, uint64_t & Alignment, llvm::DenseMap< const FieldDecl *, uint64_t > & FieldOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > & BaseOffsets, llvm::DenseMap< const CXXRecordDecl *, CharUnits > & VirtualBaseOffsets) override virtual
Perform layout on the given record.
This routine allows the external AST source to provide an specific layout for a record, overriding the layout that would normally be constructed. It is intended for clients who receive specific layout details rather than source code (such as LLDB). The client is expected to fill in the field offsets, base offsets, virtual base offsets, and complete object size.
Parameters
Record The record whose layout is being requested.
Size The final size of the record, in bits.
Alignment The final alignment of the record, in bits.
FieldOffsets The offset of each of the fields within the record, expressed in bits. All of the fields must be provided with offsets.
BaseOffsets The offset of each of the direct, non-virtual base classes. If any bases are not given offsets, the bases will be laid out according to the ABI.
VirtualBaseOffsets The offset of each of the virtual base classes (either direct or not). If any bases are not given offsets, the bases will be laid out according to the ABI.
Returns
true if the record layout was provided, false otherwise.
Reimplemented from clang::ExternalASTSource.
Definition at line 180 of file MultiplexExternalSemaSource.cpp.
LookupUnqualified()
bool MultiplexExternalSemaSource::LookupUnqualified (LookupResult & R, Scope * S) override virtual
Do last resort, unqualified lookup on a LookupResult that Sema cannot find.
Parameters
R a LookupResult that is being recovered.
S the Scope of the identifier occurrence.
Returns
true to tell Sema to recover using the LookupResult.
Reimplemented from clang::ExternalSemaSource.
Definition at line 245 of file MultiplexExternalSemaSource.cpp.
MaybeDiagnoseMissingCompleteType()
bool MultiplexExternalSemaSource::MaybeDiagnoseMissingCompleteType (SourceLocation Loc, QualType T) override virtual
Produces a diagnostic note if one of the attached sources contains a complete definition for T.
Queries the sources in list order until the first one claims that a diagnostic was produced.
Parameters
Loc the location at which a complete type was required but not provided
T the QualType that should have been complete at Loc
Returns
true if a diagnostic was produced, false otherwise.
Reimplemented from clang::ExternalSemaSource.
Definition at line 336 of file MultiplexExternalSemaSource.cpp.
References clang::T.
PrintStats()
void MultiplexExternalSemaSource::PrintStats () override virtual
Print any statistics that have been gathered regarding the external AST source.
Reimplemented from clang::ExternalASTSource.
Definition at line 168 of file MultiplexExternalSemaSource.cpp.
ReadComments()
void MultiplexExternalSemaSource::ReadComments () override virtual
Loads comment ranges.
Reimplemented from clang::ExternalASTSource.
Definition at line 148 of file MultiplexExternalSemaSource.cpp.
ReadDeclsToCheckForDeferredDiags()
void MultiplexExternalSemaSource::ReadDeclsToCheckForDeferredDiags (llvm::SmallSetVector< Decl *, 4 > & Decls) override virtual
Read the set of decls to be checked for deferred diags.
The external source should append its own potentially emitted function and variable decls which may cause deferred diags. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 276 of file MultiplexExternalSemaSource.cpp.
ReadDelegatingConstructors()
void MultiplexExternalSemaSource::ReadDelegatingConstructors (SmallVectorImpl< CXXConstructorDecl * > & Decls) override virtual
Read the set of delegating constructors known to the external Sema source.
The external source should append its own delegating constructors to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 264 of file MultiplexExternalSemaSource.cpp.
ReadExtVectorDecls()
void MultiplexExternalSemaSource::ReadExtVectorDecls (SmallVectorImpl< TypedefNameDecl * > & Decls) override virtual
Read the set of ext_vector type declarations known to the external Sema source.
The external source should append its own ext_vector type declarations to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 270 of file MultiplexExternalSemaSource.cpp.
ReadKnownNamespaces()
void MultiplexExternalSemaSource::ReadKnownNamespaces (SmallVectorImpl< NamespaceDecl * > & Namespaces) override virtual
Load the set of namespaces that are known to the external source, which will be used during typo correction.
Reimplemented from clang::ExternalSemaSource.
Definition at line 225 of file MultiplexExternalSemaSource.cpp.
ReadLateParsedTemplates()
void MultiplexExternalSemaSource::ReadLateParsedTemplates (llvm::MapVector< const FunctionDecl *, std::unique_ptr< LateParsedTemplate >> & LPTMap) override virtual
Read the set of late parsed template functions for this source.
The external source should insert its own late parsed template functions into the map. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same map entries repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 313 of file MultiplexExternalSemaSource.cpp.
ReadMethodPool()
void MultiplexExternalSemaSource::ReadMethodPool (Selector Sel) override virtual
Load the contents of the global method pool for a given selector.
Reimplemented from clang::ExternalSemaSource.
Definition at line 215 of file MultiplexExternalSemaSource.cpp.
ReadMismatchingDeleteExpressions()
void MultiplexExternalSemaSource::ReadMismatchingDeleteExpressions (llvm::MapVector< FieldDecl *, llvm::SmallVector< std::pair< SourceLocation, bool >, 4 >> & Exprs) override virtual
Reimplemented from clang::ExternalSemaSource.
Definition at line 237 of file MultiplexExternalSemaSource.cpp.
ReadPendingInstantiations()
void MultiplexExternalSemaSource::ReadPendingInstantiations (SmallVectorImpl< std::pair< ValueDecl *, SourceLocation > > & Pending) override virtual
Read the set of pending instantiations known to the external Sema source.
The external source should append its own pending instantiations to the given vector. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same instantiations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 306 of file MultiplexExternalSemaSource.cpp.
ReadReferencedSelectors()
void MultiplexExternalSemaSource::ReadReferencedSelectors (SmallVectorImpl< std::pair< Selector, SourceLocation > > & Sels) override virtual
Read the set of referenced selectors known to the external Sema source.
The external source should append its own referenced selectors to the given vector of selectors. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same selectors repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 288 of file MultiplexExternalSemaSource.cpp.
ReadTentativeDefinitions()
void MultiplexExternalSemaSource::ReadTentativeDefinitions (SmallVectorImpl< VarDecl * > & Defs) override virtual
Read the set of tentative definitions known to the external Sema source.
The external source should append its own tentative definitions to the given vector of tentative definitions. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 252 of file MultiplexExternalSemaSource.cpp.
ReadUndefinedButUsed()
void MultiplexExternalSemaSource::ReadUndefinedButUsed (llvm::MapVector< NamedDecl *, SourceLocation > & Undefined) override virtual
Load the set of used but not defined functions or variables with internal linkage, or used but not defined inline functions.
Reimplemented from clang::ExternalSemaSource.
Definition at line 231 of file MultiplexExternalSemaSource.cpp.
References clang::RISCV::Undefined.
ReadUnusedFileScopedDecls()
void MultiplexExternalSemaSource::ReadUnusedFileScopedDecls (SmallVectorImpl< const DeclaratorDecl * > & Decls) override virtual
Read the set of unused file-scope declarations known to the external Sema source.
The external source should append its own unused, filed-scope to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 258 of file MultiplexExternalSemaSource.cpp.
ReadUnusedLocalTypedefNameCandidates()
void MultiplexExternalSemaSource::ReadUnusedLocalTypedefNameCandidates (llvm::SmallSetVector< const TypedefNameDecl *, 4 > & Decls) override virtual
Read the set of potentially unused typedefs known to the source.
The external source should append its own potentially unused local typedefs to the given vector of declarations. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same declarations repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 282 of file MultiplexExternalSemaSource.cpp.
ReadUsedVTables()
void MultiplexExternalSemaSource::ReadUsedVTables (SmallVectorImpl< ExternalVTableUse > & VTables) override virtual
Read the set of used vtables known to the external Sema source.
The external source should append its own used vtables to the given vector. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same vtables repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 300 of file MultiplexExternalSemaSource.cpp.
ReadWeakUndeclaredIdentifiers()
void MultiplexExternalSemaSource::ReadWeakUndeclaredIdentifiers (SmallVectorImpl< std::pair< IdentifierInfo *, WeakInfo > > & WI) override virtual
Read the set of weak, undeclared identifiers known to the external Sema source.
The external source should append its own weak, undeclared identifiers to the given vector. Note that this routine may be invoked multiple times; the external source should take care not to introduce the same identifiers repeatedly.
Reimplemented from clang::ExternalSemaSource.
Definition at line 294 of file MultiplexExternalSemaSource.cpp.
StartedDeserializing()
void MultiplexExternalSemaSource::StartedDeserializing () override virtual
Notify ExternalASTSource that we started deserialization of a decl or type so until FinishedDeserializing is called there may be decls that are initializing.
Must be paired with FinishedDeserializing.
Reimplemented from clang::ExternalASTSource.
Definition at line 153 of file MultiplexExternalSemaSource.cpp.
StartTranslationUnit()
void MultiplexExternalSemaSource::StartTranslationUnit (ASTConsumer * Consumer) override virtual
Function that will be invoked when we begin parsing a new translation unit involving this external AST source.
Reimplemented from clang::ExternalASTSource.
Definition at line 163 of file MultiplexExternalSemaSource.cpp.
updateOutOfDateSelector()
void MultiplexExternalSemaSource::updateOutOfDateSelector (Selector Sel) override virtual
Load the contents of the global method pool for a given selector if necessary.
Reimplemented from clang::ExternalSemaSource.
Definition at line 220 of file MultiplexExternalSemaSource.cpp.
The documentation for this class was generated from the following files:
include/clang/Sema/MultiplexExternalSemaSource.h
lib/Sema/MultiplexExternalSemaSource.cpp