clang: clang::CodeGen::CodeGenFunction::OMPMapVars Class Reference
clang::CodeGen::CodeGenFunction::OMPMapVars Class Reference
The class used to assign some variables some temporarily addresses.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
OMPMapVars ()=default
~OMPMapVars ()
bool setVarAddr (CodeGenFunction &CGF, const VarDecl *LocalVD, Address TempAddr)
Sets the address of the variable LocalVD to be TempAddr in function CGF.
bool apply (CodeGenFunction &CGF)
Applies new addresses to the list of the variables.
void restore (CodeGenFunction &CGF)
Restores original addresses of the variables.
Detailed Description
The class used to assign some variables some temporarily addresses.
Definition at line 987 of file CodeGenFunction.h.
Constructor & Destructor Documentation
OMPMapVars()
clang::CodeGen::CodeGenFunction::OMPMapVars::OMPMapVars () explicit default
~OMPMapVars()
clang::CodeGen::CodeGenFunction::OMPMapVars::~OMPMapVars () inline
Definition at line 995 of file CodeGenFunction.h.
Member Function Documentation
apply()
bool clang::CodeGen::CodeGenFunction::OMPMapVars::apply (CodeGenFunction & CGF) inline
Applies new addresses to the list of the variables.
Returns
true if at least one variable is using new address, false otherwise.
Definition at line 1030 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::OMPPrivateScope::Privatize().
restore()
void clang::CodeGen::CodeGenFunction::OMPMapVars::restore (CodeGenFunction & CGF) inline
Restores original addresses of the variables.
Definition at line 1037 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::OMPPrivateScope::ForceCleanup().
setVarAddr()
bool clang::CodeGen::CodeGenFunction::OMPMapVars::setVarAddr (CodeGenFunction & CGF, const VarDecl * LocalVD, Address TempAddr) inline
Sets the address of the variable LocalVD to be TempAddr in function CGF.
Returns
true if at least one variable was set already, false otherwise.
Definition at line 1002 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::CGBuilderTy::CreateStore(), clang::VarDecl::getCanonicalDecl(), clang::CodeGen::Address::getPointer(), clang::ValueDecl::getType(), clang::CodeGen::Address::invalid(), and clang::Type::isReferenceType().
Referenced by clang::CodeGen::CodeGenFunction::OMPPrivateScope::addPrivate().
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h