clang: clang::arcmt::MigrationProcess Class Reference
clang::arcmt::MigrationProcess Class Reference
#include "clang/ARCMigrate/ARCMT.h"
Classes
class RewriteListener
Public Member Functions
MigrationProcess (CompilerInvocation &CI, std::shared_ptr< PCHContainerOperations > PCHContainerOps, DiagnosticConsumer *diagClient, StringRef outputDir=StringRef())
bool applyTransform (TransformFn trans, RewriteListener *listener=nullptr)
FileRemapper & getRemapper ()
Public Attributes
bool HadARCErrors
Detailed Description
Definition at line 96 of file ARCMT.h.
Constructor & Destructor Documentation
MigrationProcess()
MigrationProcess::MigrationProcess (CompilerInvocation & CI, std::shared_ptr< PCHContainerOperations > PCHContainerOps, DiagnosticConsumer * diagClient, StringRef outputDir = StringRef())
Definition at line 507 of file ARCMT.cpp.
References clang::CompilerInvocation::getDiagnosticOpts(), and clang::arcmt::FileRemapper::initFromDisk().
Member Function Documentation
applyTransform()
bool MigrationProcess::applyTransform (TransformFn trans, RewriteListener * listener = nullptr)
Definition at line 522 of file ARCMT.cpp.
References clang::arcmt::FileRemapper::applyMappings(), clang::arcmt::TransformActions::applyRewrites(), clang::DiagnosticConsumer::BeginSourceFile(), clang::Rewriter::buffer_begin(), clang::Rewriter::buffer_end(), createInvocationForMigration(), clang::DiagnosticConsumer::EndSourceFile(), clang::SourceManager::getFileEntryRefForID(), clang::CompilerInvocation::getLangOpts(), clang::ASTContext::getLangOpts(), clang::FileEntryRef::getName(), clang::DiagnosticConsumer::getNumErrors(), clang::ASTContext::getSourceManager(), HadARCErrors, clang::arcmt::CapturedDiagList::hasErrors(), clang::ASTUnit::LoadFromCompilerInvocationAction(), clang::arcmt::FileRemapper::remap(), clang::arcmt::CapturedDiagList::reportDiagnostics(), and clang::RewriteBuffer::write().
Referenced by applyTransforms().
getRemapper()
FileRemapper& clang::arcmt::MigrationProcess::getRemapper () inline
Definition at line 123 of file ARCMT.h.
Referenced by applyTransforms().
Member Data Documentation
HadARCErrors
bool clang::arcmt::MigrationProcess::HadARCErrors
Definition at line 103 of file ARCMT.h.
Referenced by applyTransform().
The documentation for this class was generated from the following files:
include/clang/ARCMigrate/ARCMT.h
lib/ARCMigrate/ARCMT.cpp