clang: clang::CodeGen::CGPointerAuthInfo Class Reference
clang::CodeGen::CGPointerAuthInfo Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGPointerAuthInfo.h"
Public Member Functions
CGPointerAuthInfo ()
CGPointerAuthInfo (unsigned Key, PointerAuthenticationMode AuthenticationMode, bool IsIsaPointer, bool AuthenticatesNullValues, llvm::Value *Discriminator)
operator bool () const
bool isSigned () const
unsigned getKey () const
llvm::Value * getDiscriminator () const
PointerAuthenticationMode getAuthenticationMode () const
bool isIsaPointer () const
bool authenticatesNullValues () const
bool shouldStrip () const
bool shouldSign () const
bool shouldAuth () const
Friends
bool operator!= (const CGPointerAuthInfo &LHS, const CGPointerAuthInfo &RHS)
bool operator== (const CGPointerAuthInfo &LHS, const CGPointerAuthInfo &RHS)
Detailed Description
Definition at line 24 of file CGPointerAuthInfo.h.
Constructor & Destructor Documentation
CGPointerAuthInfo() [1/2]
clang::CodeGen::CGPointerAuthInfo::CGPointerAuthInfo () inline
Definition at line 33 of file CGPointerAuthInfo.h.
CGPointerAuthInfo() [2/2]
clang::CodeGen::CGPointerAuthInfo::CGPointerAuthInfo (unsigned Key, PointerAuthenticationMode AuthenticationMode, bool IsIsaPointer, bool AuthenticatesNullValues, llvm::Value * Discriminator) inline
Definition at line 37 of file CGPointerAuthInfo.h.
Member Function Documentation
authenticatesNullValues()
bool clang::CodeGen::CGPointerAuthInfo::authenticatesNullValues () const inline
Definition at line 68 of file CGPointerAuthInfo.h.
getAuthenticationMode()
PointerAuthenticationMode clang::CodeGen::CGPointerAuthInfo::getAuthenticationMode () const inline
Definition at line 62 of file CGPointerAuthInfo.h.
getDiscriminator()
llvm::Value* clang::CodeGen::CGPointerAuthInfo::getDiscriminator () const inline
Definition at line 57 of file CGPointerAuthInfo.h.
References isSigned().
Referenced by EmitPointerAuthCommon(), and clang::CodeGen::CodeGenFunction::EmitPointerAuthOperandBundle().
getKey()
unsigned clang::CodeGen::CGPointerAuthInfo::getKey () const inline
Definition at line 53 of file CGPointerAuthInfo.h.
References isSigned().
Referenced by EmitPointerAuthCommon(), clang::CodeGen::CodeGenFunction::EmitPointerAuthOperandBundle(), and EmitStrip().
isIsaPointer()
bool clang::CodeGen::CGPointerAuthInfo::isIsaPointer () const inline
Definition at line 66 of file CGPointerAuthInfo.h.
isSigned()
bool clang::CodeGen::CGPointerAuthInfo::isSigned () const inline
Definition at line 49 of file CGPointerAuthInfo.h.
References clang::None.
Referenced by clang::CodeGen::CodeGenFunction::EmitPointerAuthOperandBundle(), getDiscriminator(), getKey(), and operator bool().
operator bool()
clang::CodeGen::CGPointerAuthInfo::operator bool () const inline explicit
Definition at line 47 of file CGPointerAuthInfo.h.
References isSigned().
shouldAuth()
bool clang::CodeGen::CGPointerAuthInfo::shouldAuth () const inline
Definition at line 80 of file CGPointerAuthInfo.h.
References clang::SignAndAuth.
Referenced by clang::CodeGen::CodeGenFunction::EmitPointerAuthAuth().
shouldSign()
bool clang::CodeGen::CGPointerAuthInfo::shouldSign () const inline
Definition at line 75 of file CGPointerAuthInfo.h.
References clang::SignAndAuth, and clang::SignAndStrip.
Referenced by clang::CodeGen::CodeGenFunction::EmitPointerAuthSign().
shouldStrip()
bool clang::CodeGen::CGPointerAuthInfo::shouldStrip () const inline
Definition at line 70 of file CGPointerAuthInfo.h.
References clang::SignAndStrip, and clang::Strip.
Referenced by clang::CodeGen::CodeGenFunction::EmitPointerAuthAuth().
Friends And Related Function Documentation
operator!=
bool operator!= (const CGPointerAuthInfo & LHS, const CGPointerAuthInfo & RHS) friend
Definition at line 84 of file CGPointerAuthInfo.h.
operator==
bool operator== (const CGPointerAuthInfo & LHS, const CGPointerAuthInfo & RHS) friend
Definition at line 90 of file CGPointerAuthInfo.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CGPointerAuthInfo.h