clang: clang::ento::CallEvent Class Reference
clang::ento::CallEvent Class Reference abstract
Represents an abstract call to a function or method along a particular path.
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
Public Types
using Kind = CallEventKind
using FrameBindingTy = std::pair< SVal, SVal >
using BindingsTy = SmallVectorImpl< FrameBindingTy >
using param_type_iterator = llvm::mapped_iterator< ArrayRef< ParmVarDecl * >::iterator, GetTypeFn >
Public Member Functions
CallEvent & operator= (const CallEvent &)=delete
virtual ~CallEvent ()=default
virtual Kind getKind () const =0
Returns the kind of call this is.
virtual StringRef getKindAsString () const =0
virtual const Decl * getDecl () const
Returns the declaration of the function or method that will be called.
const ProgramStateRef & getState () const
The state in which the call is being evaluated.
const LocationContext * getLocationContext () const
The context in which the call is being evaluated.
virtual RuntimeDefinition getRuntimeDefinition () const =0
Returns the definition of the function or method that will be called.
virtual const Expr * getOriginExpr () const
Returns the expression whose value will be the result of this call.
virtual unsigned getNumArgs () const =0
Returns the number of arguments (explicit and implicit).
bool isInSystemHeader () const
Returns true if the callee is known to be from a system header.
virtual SourceRange getSourceRange () const
Returns a source range for the entire call, suitable for outputting in diagnostics.
virtual SVal getArgSVal (unsigned Index) const
Returns the value of a given argument at the time of the call.
virtual const Expr * getArgExpr (unsigned Index) const
Returns the expression associated with a given argument.
virtual SourceRange getArgSourceRange (unsigned Index) const
Returns the source range for errors associated with this argument.
QualType getResultType () const
Returns the result type, adjusted for references.
SVal getReturnValue () const
Returns the return value of the call.
bool hasNonNullArgumentsWithType (bool(*Condition)(QualType)) const
Returns true if the type of any of the non-null arguments satisfies the condition.
bool hasNonZeroCallbackArg () const
Returns true if any of the arguments appear to represent callbacks.
bool hasVoidPointerToNonConstArg () const
Returns true if any of the arguments is void*.
virtual bool argumentsMayEscape () const
Returns true if any of the arguments are known to escape to long- term storage, even if this method will not modify them.
bool isGlobalCFunction (StringRef SpecificName=StringRef()) const
Returns true if the callee is an externally-visible function in the top-level namespace, such as malloc.
const IdentifierInfo * getCalleeIdentifier () const
Returns the name of the callee, if its name is a simple identifier.
ProgramPoint getProgramPoint (bool IsPreVisit=false, const ProgramPointTag *Tag=nullptr) const
Returns an appropriate ProgramPoint for this call.
ProgramStateRef invalidateRegions (unsigned BlockCount, ProgramStateRef Orig=nullptr) const
Returns a new state with all argument regions invalidated.
virtual void getInitialStackFrameContents (const StackFrameContext *CalleeCtx, BindingsTy &Bindings) const =0
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
template<typename T >
CallEventRef< T > cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
CallEventRef cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
AnalysisDeclContext * getCalleeAnalysisDeclContext () const
Returns AnalysisDeclContext for the callee stack frame.
const StackFrameContext * getCalleeStackFrame (unsigned BlockCount) const
Returns the callee stack frame.
const ParamVarRegion * getParameterLocation (unsigned Index, unsigned BlockCount) const
Returns memory location for a parameter variable within the callee stack frame.
bool isArgumentConstructedDirectly (unsigned Index) const
Returns true if on the current path, the argument was constructed by calling a C++ constructor over it.
virtual Optional< unsigned > getAdjustedParameterIndex (unsigned ASTArgumentIndex) const
Some calls have parameter numbering mismatched from argument numbering.
virtual unsigned getASTArgumentIndex (unsigned CallArgumentIndex) const
Some call event sub-classes conveniently adjust mismatching AST indices to match parameter indices.
const ConstructionContext * getConstructionContext () const
Returns the construction context of the call, if it is a C++ constructor call or a call of a function returning a C++ class instance.
Optional< SVal > getReturnValueUnderConstruction () const
If the call returns a C++ record type then the region of its return value can be retrieved from its construction context.
virtual ArrayRef< ParmVarDecl * > parameters () const =0
Return call's formal parameters.
param_type_iterator param_type_begin () const
Returns an iterator over the types of the call's formal parameters.
param_type_iterator param_type_end () const
void dump (raw_ostream &Out) const
void dump () const
Static Public Member Functions
static bool isCallStmt (const Stmt *S)
Returns true if this is a statement is a function or method call of some kind.
static QualType getDeclaredResultType (const Decl *D)
Returns the result type of a function or method declaration.
static bool isVariadic (const Decl *D)
Returns true if the given decl is known to be variadic.
Protected Types
using ValueList = SmallVectorImpl< SVal >
Protected Member Functions
CallEvent (const Expr *E, ProgramStateRef state, const LocationContext *lctx)
CallEvent (const Decl *D, ProgramStateRef state, const LocationContext *lctx)
CallEvent (const CallEvent &Original)
virtual void cloneTo (void *Dest) const =0
Copies this CallEvent, with vtable intact, into a new block of memory.
SVal getSVal (const Stmt *S) const
Get the value of arbitrary expressions at this point in the path.
virtual void getExtraInvalidatedValues (ValueList &Values, RegionAndSymbolInvalidationTraits *ETraits) const
Used to specify non-argument regions that will be invalidated as a result of this call.
Protected Attributes
const void * Data
SourceLocation Location
Friends
template<typename T >
struct llvm::IntrusiveRefCntPtrInfo
class CallEventManager
Detailed Description
Represents an abstract call to a function or method along a particular path.
CallEvents are created through the factory methods of CallEventManager.
CallEvents should always be cheap to create and destroy. In order for CallEventManager to be able to re-use CallEvent-sized memory blocks, subclasses of CallEvent may not add any data members to the base class. Use the "Data" and "Location" fields instead.
Definition at line 142 of file CallEvent.h.
Member Typedef Documentation
BindingsTy
using clang::ento::CallEvent::BindingsTy = SmallVectorImpl<FrameBindingTy>
Definition at line 349 of file CallEvent.h.
FrameBindingTy
using clang::ento::CallEvent::FrameBindingTy = std::pair<SVal, SVal>
Definition at line 348 of file CallEvent.h.
Kind
using clang::ento::CallEvent::Kind = CallEventKind
Definition at line 144 of file CallEvent.h.
param_type_iterator
using clang::ento::CallEvent::param_type_iterator = llvm::mapped_iterator<ArrayRef<ParmVarDecl *>::iterator, GetTypeFn>
Definition at line 447 of file CallEvent.h.
ValueList
using clang::ento::CallEvent::ValueList = SmallVectorImpl<SVal> protected
Definition at line 190 of file CallEvent.h.
Constructor & Destructor Documentation
CallEvent() [1/3]
clang::ento::CallEvent::CallEvent (const Expr * E, ProgramStateRef state, const LocationContext * lctx) inline protected
Definition at line 171 of file CallEvent.h.
CallEvent() [2/3]
clang::ento::CallEvent::CallEvent (const Decl * D, ProgramStateRef state, const LocationContext * lctx) inline protected
Definition at line 174 of file CallEvent.h.
CallEvent() [3/3]
clang::ento::CallEvent::CallEvent (const CallEvent & Original) inline protected
Definition at line 178 of file CallEvent.h.
~CallEvent()
virtual clang::ento::CallEvent::~CallEvent () virtual default
Member Function Documentation
argumentsMayEscape()
virtual bool clang::ento::CallEvent::argumentsMayEscape () const inline virtual
Returns true if any of the arguments are known to escape to long- term storage, even if this method will not modify them.
Reimplemented in clang::ento::ObjCMethodCall, clang::ento::BlockCall, and clang::ento::AnyFunctionCall.
Definition at line 301 of file CallEvent.h.
References hasNonZeroCallbackArg().
Referenced by clang::ento::AnyFunctionCall::argumentsMayEscape(), clang::ento::ObjCMethodCall::argumentsMayEscape(), and invalidateRegions().
cloneTo()
virtual void clang::ento::CallEvent::cloneTo (void * Dest) const protected pure virtual
Copies this CallEvent, with vtable intact, into a new block of memory.
Implemented in clang::ento::ObjCMethodCall, clang::ento::CXXDeallocatorCall, clang::ento::CXXAllocatorCall, clang::ento::CXXInheritedConstructorCall, clang::ento::CXXConstructorCall, clang::ento::CXXDestructorCall, clang::ento::CXXMemberOperatorCall, clang::ento::CXXMemberCall, clang::ento::BlockCall, and clang::ento::SimpleFunctionCall.
Referenced by cloneWithState().
cloneWithState() [1/2]
template<typename T > CallEventRef< T > clang::ento::CallEvent::cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
Definition at line 1328 of file CallEvent.h.
References cloneTo(), and State.
Referenced by clang::ento::ExprEngine::defaultEvalCall().
cloneWithState() [2/2]
CallEventRef clang::ento::CallEvent::cloneWithState (ProgramStateRef NewState) const inline
Returns a copy of this CallEvent, but using the given state.
Definition at line 361 of file CallEvent.h.
dump() [1/2]
LLVM_DUMP_METHOD void CallEvent::dump () const
Definition at line 327 of file CallEvent.cpp.
dump() [2/2]
void CallEvent::dump (raw_ostream & Out) const
Definition at line 329 of file CallEvent.cpp.
References getDecl(), getKindAsString(), getOriginExpr(), clang::ASTContext::getPrintingPolicy(), and getState().
getAdjustedParameterIndex()
virtual Optional<unsigned> clang::ento::CallEvent::getAdjustedParameterIndex (unsigned ASTArgumentIndex) const inline virtual
Some calls have parameter numbering mismatched from argument numbering.
This function converts an argument index to the corresponding parameter index. Returns None is the argument doesn't correspond to any parameter variable.
Reimplemented in clang::ento::CXXMemberOperatorCall.
Definition at line 412 of file CallEvent.h.
Referenced by invalidateRegions().
getArgExpr()
virtual const Expr* clang::ento::CallEvent::getArgExpr (unsigned Index) const inline virtual
Returns the expression associated with a given argument.
May be null if this expression does not appear in the source.
Reimplemented in clang::ento::ObjCMethodCall, clang::ento::CXXDeallocatorCall, clang::ento::CXXAllocatorCall, clang::ento::CXXInheritedConstructorCall, clang::ento::CXXConstructorCall, clang::ento::CXXMemberOperatorCall, clang::ento::CXXMemberCall, clang::ento::BlockCall, and clang::ento::SimpleFunctionCall.
Definition at line 270 of file CallEvent.h.
getArgSourceRange()
SourceRange CallEvent::getArgSourceRange (unsigned Index) const virtual
Returns the source range for errors associated with this argument.
May be invalid if the argument is not written in the source.
Definition at line 313 of file CallEvent.cpp.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkSummary().
getArgSVal()
SVal CallEvent::getArgSVal (unsigned Index) const virtual
Returns the value of a given argument at the time of the call.
Reimplemented in clang::ento::CXXInheritedConstructorCall.
Definition at line 306 of file CallEvent.cpp.
Referenced by clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), clang::ento::retaincountchecker::RetainCountChecker::checkSummary(), hasNonNullArgumentsWithType(), invalidateRegions(), clang::ento::retaincountchecker::RetainCountChecker::processSummaryOfInlined(), and updateOutParameters().
getASTArgumentIndex()
virtual unsigned clang::ento::CallEvent::getASTArgumentIndex (unsigned CallArgumentIndex) const inline virtual
Some call event sub-classes conveniently adjust mismatching AST indices to match parameter indices.
This function converts an argument index as understood by CallEvent to the argument index as understood by the AST.
Reimplemented in clang::ento::CXXMemberOperatorCall.
Definition at line 419 of file CallEvent.h.
getCalleeAnalysisDeclContext()
AnalysisDeclContext * CallEvent::getCalleeAnalysisDeclContext () const
Returns AnalysisDeclContext for the callee stack frame.
Currently may fail; returns null on failure.
Definition at line 153 of file CallEvent.cpp.
References clang::LocationContext::getAnalysisDeclContext(), clang::AnalysisDeclContextManager::getContext(), getDecl(), and clang::AnalysisDeclContext::getManager().
Referenced by getCalleeStackFrame().
getCalleeIdentifier()
const IdentifierInfo* clang::ento::CallEvent::getCalleeIdentifier () const inline
Returns the name of the callee, if its name is a simple identifier.
Note that this will fail for Objective-C methods, blocks, and C++ overloaded operators. The former is named by a Selector rather than a simple identifier, and the latter two do not have names.
Definition at line 330 of file CallEvent.h.
References getDecl().
Referenced by clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), and clang::ento::mpi::MPIChecker::checkUnmatchedWaits().
getCalleeStackFrame()
const StackFrameContext * CallEvent::getCalleeStackFrame (unsigned BlockCount) const
Returns the callee stack frame.
That stack frame will only be entered during analysis if the call is inlined, but it may still be useful in intermediate calculations even if the call isn't inlined. May fail; returns null on failure.
Definition at line 165 of file CallEvent.cpp.
References clang::LocationContext::getAnalysisDeclContext(), clang::CFGStmtMap::getBlock(), getCalleeAnalysisDeclContext(), clang::AnalysisDeclContext::getCFGStmtMap(), clang::AnalysisDeclContext::getManager(), getOriginExpr(), clang::AnalysisDeclContextManager::getStackFrame(), and clang::CFGBlock::size().
Referenced by getConstructionContext().
getConstructionContext()
const ConstructionContext * CallEvent::getConstructionContext () const
Returns the construction context of the call, if it is a C++ constructor call or a call of a function returning a C++ class instance.
Otherwise return nullptr.
Definition at line 463 of file CallEvent.cpp.
References clang::CFGElement::getAs(), getCalleeStackFrame(), and clang::StackFrameContext::getCallSiteCFGElement().
Referenced by getReturnValueUnderConstruction().
getDecl()
virtual const Decl* clang::ento::CallEvent::getDecl () const inline virtual
Returns the declaration of the function or method that will be called.
May be null.
Reimplemented in clang::ento::ObjCMethodCall, clang::ento::CXXDeallocatorCall, clang::ento::CXXAllocatorCall, clang::ento::CXXInheritedConstructorCall, clang::ento::CXXConstructorCall, clang::ento::CXXInstanceCall, clang::ento::BlockCall, clang::ento::SimpleFunctionCall, and clang::ento::AnyFunctionCall.
Definition at line 207 of file CallEvent.h.
Referenced by dump(), getCalleeAnalysisDeclContext(), getCalleeIdentifier(), clang::ento::AnyFunctionCall::getDecl(), getProgramPoint(), hasNonNullArgumentsWithType(), invalidateRegions(), isGlobalCFunction(), and isInSystemHeader().
getDeclaredResultType()
QualType CallEvent::getDeclaredResultType (const Decl * D) static
Returns the result type of a function or method declaration.
This will return a null QualType if the result type cannot be determined.
Definition at line 349 of file CallEvent.cpp.
References clang::Type::getAs(), and clang::Type::isDependentType().
Referenced by clang::ento::ExprEngine::processCallExit().
getExtraInvalidatedValues()
virtual void clang::ento::CallEvent::getExtraInvalidatedValues (ValueList & Values, RegionAndSymbolInvalidationTraits * ETraits) const inline protected virtual
Used to specify non-argument regions that will be invalidated as a result of this call.
Reimplemented in clang::ento::ObjCMethodCall, clang::ento::AnyCXXConstructorCall, clang::ento::CXXInstanceCall, and clang::ento::BlockCall.
Definition at line 194 of file CallEvent.h.
Referenced by invalidateRegions().
getInitialStackFrameContents()
virtual void clang::ento::CallEvent::getInitialStackFrameContents (const StackFrameContext * CalleeCtx, BindingsTy & Bindings) const pure virtual
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
Implemented in clang::ento::ObjCMethodCall, clang::ento::AnyCXXConstructorCall, clang::ento::CXXInstanceCall, clang::ento::BlockCall, and clang::ento::AnyFunctionCall.
getKind()
virtual Kind clang::ento::CallEvent::getKind () const pure virtual
Returns the kind of call this is.
Implemented in clang::ento::ObjCMethodCall, clang::ento::CXXDeallocatorCall, clang::ento::CXXAllocatorCall, clang::ento::CXXInheritedConstructorCall, clang::ento::CXXConstructorCall, clang::ento::CXXDestructorCall, clang::ento::CXXMemberOperatorCall, clang::ento::CXXMemberCall, clang::ento::BlockCall, and clang::ento::SimpleFunctionCall.
Referenced by clang::ento::AnyFunctionCall::classof(), clang::ento::SimpleFunctionCall::classof(), clang::ento::BlockCall::classof(), clang::ento::CXXInstanceCall::classof(), clang::ento::CXXMemberCall::classof(), clang::ento::CXXMemberOperatorCall::classof(), clang::ento::CXXDestructorCall::classof(), clang::ento::CXXConstructorCall::classof(), clang::ento::CXXInheritedConstructorCall::classof(), clang::ento::CXXAllocatorCall::classof(), clang::ento::CXXDeallocatorCall::classof(), clang::ento::ObjCMethodCall::classof(), and invalidateRegions().
getKindAsString()
virtual StringRef clang::ento::CallEvent::getKindAsString () const pure virtual
Implemented in clang::ento::ObjCMethodCall, clang::ento::CXXDeallocatorCall, clang::ento::CXXAllocatorCall, clang::ento::CXXInheritedConstructorCall, clang::ento::CXXConstructorCall, clang::ento::CXXDestructorCall, clang::ento::CXXMemberOperatorCall, clang::ento::CXXMemberCall, clang::ento::BlockCall, and clang::ento::SimpleFunctionCall.
Referenced by dump().
getLocationContext()
const LocationContext* clang::ento::CallEvent::getLocationContext () const inline
The context in which the call is being evaluated.
Definition at line 217 of file CallEvent.h.
Referenced by clang::ento::CXXInheritedConstructorCall::getInheritingStackFrame(), clang::ento::ObjCMethodCall::getMessageKind(), clang::ento::CXXAllocatorCall::getObjectUnderConstruction(), getProgramPoint(), clang::ento::ObjCMethodCall::getReceiverSVal(), getReturnValueUnderConstruction(), clang::ento::AnyFunctionCall::getRuntimeDefinition(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), invalidateRegions(), and clang::ento::ObjCMethodCall::isReceiverSelfOrSuper().
getNumArgs()
virtual unsigned clang::ento::CallEvent::getNumArgs () const pure virtual
Returns the number of arguments (explicit and implicit).
Note that this may be greater than the number of parameters in the callee's declaration, and that it may include arguments not written in the source.
Implemented in clang::ento::ObjCMethodCall, clang::ento::CXXDeallocatorCall, clang::ento::CXXAllocatorCall, clang::ento::CXXInheritedConstructorCall, clang::ento::CXXConstructorCall, clang::ento::CXXDestructorCall, clang::ento::CXXMemberOperatorCall, clang::ento::CXXMemberCall, clang::ento::BlockCall, and clang::ento::SimpleFunctionCall.
Referenced by clang::ento::mpi::MPIChecker::checkDoubleNonblocking(), clang::ento::retaincountchecker::RetainCountChecker::checkSummary(), hasNonNullArgumentsWithType(), invalidateRegions(), clang::ento::retaincountchecker::RetainCountChecker::processSummaryOfInlined(), and updateOutParameters().
getOriginExpr()
virtual const Expr* clang::ento::CallEvent::getOriginExpr () const inline virtual
Returns the expression whose value will be the result of this call.
May be null.
Reimplemented in clang::ento::ObjCMethodCall, clang::ento::CXXDeallocatorCall, clang::ento::CXXAllocatorCall, clang::ento::CXXInheritedConstructorCall, clang::ento::CXXConstructorCall, clang::ento::CXXMemberOperatorCall, clang::ento::CXXMemberCall, clang::ento::BlockCall, and clang::ento::SimpleFunctionCall.
Definition at line 227 of file CallEvent.h.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkSummary(), dump(), getCalleeStackFrame(), clang::ento::CXXInstanceCall::getDecl(), clang::ento::SimpleFunctionCall::getOriginExpr(), clang::ento::BlockCall::getOriginExpr(), clang::ento::CXXMemberCall::getOriginExpr(), clang::ento::CXXMemberOperatorCall::getOriginExpr(), clang::ento::CXXConstructorCall::getOriginExpr(), clang::ento::CXXInheritedConstructorCall::getOriginExpr(), clang::ento::CXXAllocatorCall::getOriginExpr(), clang::ento::CXXDeallocatorCall::getOriginExpr(), clang::ento::ObjCMethodCall::getOriginExpr(), getProgramPoint(), getResultType(), getReturnValue(), getReturnValueUnderConstruction(), getSourceRange(), and invalidateRegions().
getParameterLocation()
const ParamVarRegion * CallEvent::getParameterLocation (unsigned Index, unsigned BlockCount) const
Returns memory location for a parameter variable within the callee stack frame.
The behavior is undefined if the block count is different from the one that is there when call happens. May fail; returns null on failure.
Definition at line 195 of file CallEvent.cpp.
Referenced by invalidateRegions().
getProgramPoint()
ProgramPoint CallEvent::getProgramPoint (bool IsPreVisit = false, const ProgramPointTag * Tag = nullptr) const
Returns an appropriate ProgramPoint for this call.
Definition at line 289 of file CallEvent.cpp.
References clang::SourceRange::getBegin(), getDecl(), getLocationContext(), getOriginExpr(), and getSourceRange().
getResultType()
QualType CallEvent::getResultType () const
Returns the result type, adjusted for references.
Definition at line 72 of file CallEvent.cpp.
References getOriginExpr(), clang::ASTContext::getReferenceQualifiedType(), getState(), and clang::ASTContext::VoidTy.
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkSummary(), and updateOutParameters().
getReturnValue()
SVal CallEvent::getReturnValue () const
Returns the return value of the call.
This should only be called if the CallEvent was created using a state in which the return value has already been bound to the origin expression.
Definition at line 320 of file CallEvent.cpp.
References getOriginExpr(), and getSVal().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkSummary(), clang::ento::retaincountchecker::RetainCountChecker::processSummaryOfInlined(), and updateOutParameters().
getReturnValueUnderConstruction()
Optional< SVal > CallEvent::getReturnValueUnderConstruction () const
If the call returns a C++ record type then the region of its return value can be retrieved from its construction context.
Definition at line 481 of file CallEvent.cpp.
References clang::ento::ExprEngine::computeObjectUnderConstruction(), getConstructionContext(), getLocationContext(), getOriginExpr(), and getState().
getRuntimeDefinition()
virtual RuntimeDefinition clang::ento::CallEvent::getRuntimeDefinition () const pure virtual
Returns the definition of the function or method that will be called.
Implemented in clang::ento::ObjCMethodCall, clang::ento::CXXDestructorCall, clang::ento::CXXMemberCall, clang::ento::CXXInstanceCall, clang::ento::BlockCall, and clang::ento::AnyFunctionCall.
getSourceRange()
virtual SourceRange clang::ento::CallEvent::getSourceRange () const inline virtual
Returns a source range for the entire call, suitable for outputting in diagnostics.
Reimplemented in clang::ento::ObjCMethodCall, and clang::ento::CXXDestructorCall.
Definition at line 261 of file CallEvent.h.
References getOriginExpr(), and clang::Stmt::getSourceRange().
Referenced by getProgramPoint(), clang::ento::mpi::MPIBugReporter::reportDoubleNonblocking(), and clang::ento::mpi::MPIBugReporter::reportUnmatchedWait().
getState()
const ProgramStateRef& clang::ento::CallEvent::getState () const inline
The state in which the call is being evaluated.
Definition at line 212 of file CallEvent.h.
References State.
Referenced by clang::ento::ObjCMethodCall::canBeOverridenInSubclass(), dump(), clang::ento::ObjCMethodCall::getExtraInvalidatedValues(), clang::ento::AnyFunctionCall::getInitialStackFrameContents(), clang::ento::BlockCall::getInitialStackFrameContents(), clang::ento::CXXInstanceCall::getInitialStackFrameContents(), clang::ento::AnyCXXConstructorCall::getInitialStackFrameContents(), clang::ento::ObjCMethodCall::getInitialStackFrameContents(), clang::ento::CXXAllocatorCall::getObjectUnderConstruction(), clang::ento::ObjCMethodCall::getReceiverSVal(), getResultType(), getReturnValueUnderConstruction(), clang::ento::AnyFunctionCall::getRuntimeDefinition(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), clang::ento::ObjCMethodCall::getRuntimeDefinition(), invalidateRegions(), isInSystemHeader(), and clang::ento::ObjCMethodCall::isReceiverSelfOrSuper().
getSVal()
SVal clang::ento::CallEvent::getSVal (const Stmt * S) const inline protected
Get the value of arbitrary expressions at this point in the path.
Definition at line 186 of file CallEvent.h.
Referenced by clang::ento::BlockCall::getBlockRegion(), clang::ento::CXXInstanceCall::getCXXThisVal(), clang::ento::SimpleFunctionCall::getDecl(), clang::ento::CXXInstanceCall::getDecl(), clang::ento::ObjCMethodCall::getReceiverSVal(), getReturnValue(), and clang::ento::ObjCMethodCall::isReceiverSelfOrSuper().
hasNonNullArgumentsWithType()
bool CallEvent::hasNonNullArgumentsWithType (bool(*)(QualType) Condition) const
Returns true if the type of any of the non-null arguments satisfies the condition.
Definition at line 114 of file CallEvent.cpp.
References clang::Condition, getArgSVal(), getDecl(), getNumArgs(), param_type_begin(), and param_type_end().
Referenced by hasNonZeroCallbackArg(), and hasVoidPointerToNonConstArg().
hasNonZeroCallbackArg()
bool CallEvent::hasNonZeroCallbackArg () const
Returns true if any of the arguments appear to represent callbacks.
Definition at line 137 of file CallEvent.cpp.
References hasNonNullArgumentsWithType(), and isCallback().
Referenced by argumentsMayEscape().
hasVoidPointerToNonConstArg()
bool CallEvent::hasVoidPointerToNonConstArg () const
Returns true if any of the arguments is void*.
Definition at line 141 of file CallEvent.cpp.
References hasNonNullArgumentsWithType(), and isVoidPointerToNonConst().
Referenced by clang::ento::AnyFunctionCall::argumentsMayEscape().
invalidateRegions()
ProgramStateRef CallEvent::invalidateRegions (unsigned BlockCount, ProgramStateRef Orig = nullptr) const
Returns a new state with all argument regions invalidated.
This accepts an alternate state in case some processing has already occurred.
Definition at line 234 of file CallEvent.cpp.
References argumentsMayEscape(), clang::ento::CE_CXXAllocator, findPtrToConstParams(), getAdjustedParameterIndex(), getArgSVal(), getDecl(), getExtraInvalidatedValues(), getKind(), getLocationContext(), getNumArgs(), getOriginExpr(), getParameterLocation(), getState(), isArgumentConstructedDirectly(), clang::ento::RegionAndSymbolInvalidationTraits::setTrait(), and clang::ento::RegionAndSymbolInvalidationTraits::TK_PreserveContents.
isArgumentConstructedDirectly()
bool clang::ento::CallEvent::isArgumentConstructedDirectly (unsigned Index) const inline
Returns true if on the current path, the argument was constructed by calling a C++ constructor over it.
This is an internal detail of the analysis which doesn't necessarily represent the program semantics: if we are supposed to construct an argument directly, we may still not do that because we don't know how (i.e., construction context is unavailable in the CFG or not supported by the analyzer).
Definition at line 401 of file CallEvent.h.
Referenced by invalidateRegions().
isCallStmt()
bool CallEvent::isCallStmt (const Stmt * S) static
Returns true if this is a statement is a function or method call of some kind.
Definition at line 345 of file CallEvent.cpp.
isGlobalCFunction()
bool CallEvent::isGlobalCFunction (StringRef SpecificName = StringRef()) const
Returns true if the callee is an externally-visible function in the top-level namespace, such as malloc.
You can use this call to determine that a particular function really is a library function and not, say, a C++ member function with the same name.
If a name is provided, the function must additionally match the given name.
Note that this deliberately excludes C++ library functions in the std namespace, but will include C library functions accessed through the std namespace. This also does not check if the function is declared as 'extern "C"', or if it uses C++ name mangling.
Definition at line 145 of file CallEvent.cpp.
References getDecl(), and clang::ento::CheckerContext::isCLibraryFunction().
isInSystemHeader()
bool clang::ento::CallEvent::isInSystemHeader () const inline
Returns true if the callee is known to be from a system header.
Definition at line 239 of file CallEvent.h.
References getDecl(), clang::Decl::getLocation(), getState(), clang::ento::DefinedSVal::isValid(), and SM.
Referenced by clang::ento::ObjCMethodCall::argumentsMayEscape().
isVariadic()
bool CallEvent::isVariadic (const Decl * D) static
Returns true if the given decl is known to be variadic.
D must not be null.
Definition at line 378 of file CallEvent.cpp.
Referenced by clang::ento::ExprEngine::computeObjectUnderConstruction().
operator=()
CallEvent& clang::ento::CallEvent::operator= (const CallEvent &) delete
param_type_begin()
param_type_iterator clang::ento::CallEvent::param_type_begin () const inline
Returns an iterator over the types of the call's formal parameters.
This uses the callee decl found by default name lookup rather than the definition because it represents a public interface, and probably has more annotations.
Definition at line 454 of file CallEvent.h.
References parameters().
Referenced by hasNonNullArgumentsWithType().
param_type_end()
param_type_iterator clang::ento::CallEvent::param_type_end () const inline
See also
param_type_begin()
Definition at line 458 of file CallEvent.h.
References parameters().
Referenced by hasNonNullArgumentsWithType().
parameters()
virtual ArrayRef<ParmVarDecl *> clang::ento::CallEvent::parameters () const pure virtual
Return call's formal parameters.
Remember that the number of formal parameters may not match the number of arguments for all calls. However, the first parameter will always correspond with the argument value returned by getArgSVal(0).
Implemented in clang::ento::ObjCMethodCall, clang::ento::BlockCall, and clang::ento::AnyFunctionCall.
Referenced by param_type_begin(), param_type_end(), and shouldEscapeOSArgumentOnCall().
Friends And Related Function Documentation
CallEventManager
friend class CallEventManager friend
Definition at line 169 of file CallEvent.h.
llvm::IntrusiveRefCntPtrInfo
template<typename T > friend struct llvm::IntrusiveRefCntPtrInfo friend
Definition at line 161 of file CallEvent.h.
Member Data Documentation
Data
const void* clang::ento::CallEvent::Data protected
Definition at line 153 of file CallEvent.h.
Referenced by clang::ento::AnyCXXConstructorCall::AnyCXXConstructorCall(), clang::ento::CXXDestructorCall::CXXDestructorCall(), clang::ento::CXXDestructorCall::getCXXThisVal(), clang::ento::AnyCXXConstructorCall::getCXXThisVal(), clang::ento::ObjCMethodCall::getMessageKind(), clang::ento::CXXDestructorCall::isBaseDestructor(), and clang::ento::ObjCMethodCall::ObjCMethodCall().
Location
SourceLocation clang::ento::CallEvent::Location protected
Definition at line 158 of file CallEvent.h.
Referenced by clang::ento::CXXDestructorCall::CXXDestructorCall(), and clang::ento::CXXDestructorCall::getSourceRange().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h
lib/StaticAnalyzer/Core/CallEvent.cpp