clang: clang::driver::RocmInstallationDetector Class Reference
clang::driver::RocmInstallationDetector Class Reference
A class to find a viable ROCM installation TODO: Generalize to handle libclc.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/ROCm.h"
Public Member Functions
RocmInstallationDetector (const Driver &D, const llvm::Triple &HostTriple, const llvm::opt::ArgList &Args, bool DetectHIPRuntime=true, bool DetectDeviceLib=false)
llvm::SmallVector< std::string, 12 > getCommonBitcodeLibs (const llvm::opt::ArgList &DriverArgs, StringRef LibDeviceFile, bool Wave64, bool DAZ, bool FiniteOnly, bool UnsafeMathOpt, bool FastRelaxedMath, bool CorrectSqrt, DeviceLibABIVersion ABIVer, bool isOpenMP) const
Get file paths of default bitcode libraries common to AMDGPU based toolchains.
bool checkCommonBitcodeLibs (StringRef GPUArch, StringRef LibDeviceFile, DeviceLibABIVersion ABIVer) const
Check file paths of default bitcode libraries common to AMDGPU based toolchains.
bool hasHIPRuntime () const
Check whether we detected a valid HIP runtime.
bool hasDeviceLibrary () const
Check whether we detected a valid ROCm device library.
void print (raw_ostream &OS) const
Print information about the detected ROCm installation.
StringRef getInstallPath () const
Get the detected Rocm install's version.
StringRef getIncludePath () const
Get the detected path to Rocm's bin directory.
StringRef getLibPath () const
Get the detected Rocm library path.
StringRef getLibDevicePath () const
Get the detected Rocm device library path.
StringRef getOCMLPath () const
StringRef getOCKLPath () const
StringRef getOpenCLPath () const
StringRef getHIPPath () const
StringRef getAsanRTLPath () const
Returns empty string of Asan runtime library is not available.
StringRef getWavefrontSize64Path (bool Enabled) const
StringRef getFiniteOnlyPath (bool Enabled) const
StringRef getUnsafeMathPath (bool Enabled) const
StringRef getDenormalsAreZeroPath (bool Enabled) const
StringRef getCorrectlyRoundedSqrtPath (bool Enabled) const
StringRef getABIVersionPath (DeviceLibABIVersion ABIVer) const
std::string getLibDeviceFile (StringRef Gpu) const
Get libdevice file for given architecture.
void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
void detectDeviceLibrary ()
void detectHIPRuntime ()
std::vector< std::string > getRocmDeviceLibPathArg () const
Get the values for –rocm-device-lib-path arguments.
StringRef getRocmPathArg () const
Get the value for –rocm-path argument.
StringRef getHIPVersionArg () const
Get the value for –hip-version argument.
std::string getHIPVersion () const
Detailed Description
A class to find a viable ROCM installation TODO: Generalize to handle libclc.
Definition at line 47 of file ROCm.h.
Constructor & Destructor Documentation
RocmInstallationDetector()
RocmInstallationDetector::RocmInstallationDetector (const Driver & D, const llvm::Triple & HostTriple, const llvm::opt::ArgList & Args, bool DetectHIPRuntime = true, bool DetectDeviceLib = false)
Definition at line 313 of file AMDGPU.cpp.
References detectDeviceLibrary(), detectHIPRuntime(), and clang::driver::Driver::Diag().
Member Function Documentation
AddHIPIncludeArgs()
void RocmInstallationDetector::AddHIPIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const
Definition at line 486 of file AMDGPU.cpp.
References clang::driver::Driver::Diag(), getIncludePath(), hasHIPRuntime(), P, and clang::driver::Driver::ResourceDir.
Referenced by clang::driver::toolchains::Linux::AddHIPIncludeArgs(), clang::driver::toolchains::FreeBSD::AddHIPIncludeArgs(), clang::driver::toolchains::HIPAMDToolChain::AddHIPIncludeArgs(), clang::driver::toolchains::MSVCToolChain::AddHIPIncludeArgs(), and clang::driver::toolchains::Darwin::AddHIPIncludeArgs().
checkCommonBitcodeLibs()
bool RocmInstallationDetector::checkCommonBitcodeLibs (StringRef GPUArch, StringRef LibDeviceFile, DeviceLibABIVersion ABIVer) const
Check file paths of default bitcode libraries common to AMDGPU based toolchains.
Returns
false if there are invalid or missing files.
Definition at line 872 of file AMDGPU.cpp.
References clang::driver::DeviceLibABIVersion::requiresLibrary(), and clang::driver::DeviceLibABIVersion::toString().
Referenced by clang::driver::toolchains::ROCMToolChain::addClangTargetOptions(), and clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames().
detectDeviceLibrary()
void RocmInstallationDetector::detectDeviceLibrary ()
Definition at line 362 of file AMDGPU.cpp.
Referenced by RocmInstallationDetector(), and clang::driver::toolchains::ROCMToolChain::ROCMToolChain().
detectHIPRuntime()
void RocmInstallationDetector::detectHIPRuntime ()
Definition at line 441 of file AMDGPU.cpp.
Referenced by RocmInstallationDetector().
getABIVersionPath()
StringRef clang::driver::RocmInstallationDetector::getABIVersionPath (DeviceLibABIVersion ABIVer) const inline
Definition at line 246 of file ROCm.h.
References clang::driver::DeviceLibABIVersion::ABIVersion.
getAsanRTLPath()
StringRef clang::driver::RocmInstallationDetector::getAsanRTLPath () const inline
Returns empty string of Asan runtime library is not available.
Definition at line 224 of file ROCm.h.
Referenced by clang::driver::toolchains::HIPAMDToolChain::getHIPDeviceLibs().
getCommonBitcodeLibs()
llvm::SmallVector< std::string, 12 > RocmInstallationDetector::getCommonBitcodeLibs (const llvm::opt::ArgList & DriverArgs, StringRef LibDeviceFile, bool Wave64, bool DAZ, bool FiniteOnly, bool UnsafeMathOpt, bool FastRelaxedMath, bool CorrectSqrt, DeviceLibABIVersion ABIVer, bool isOpenMP = false) const
Get file paths of default bitcode libraries common to AMDGPU based toolchains.
Definition at line 891 of file AMDGPU.cpp.
Referenced by clang::driver::toolchains::ROCMToolChain::addClangTargetOptions(), and clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames().
getCorrectlyRoundedSqrtPath()
StringRef clang::driver::RocmInstallationDetector::getCorrectlyRoundedSqrtPath (bool Enabled) const inline
Definition at line 242 of file ROCm.h.
getDenormalsAreZeroPath()
StringRef clang::driver::RocmInstallationDetector::getDenormalsAreZeroPath (bool Enabled) const inline
Definition at line 238 of file ROCm.h.
getFiniteOnlyPath()
StringRef clang::driver::RocmInstallationDetector::getFiniteOnlyPath (bool Enabled) const inline
Definition at line 230 of file ROCm.h.
getHIPPath()
StringRef clang::driver::RocmInstallationDetector::getHIPPath () const inline
Definition at line 218 of file ROCm.h.
References clang::HIP.
Referenced by clang::driver::toolchains::HIPAMDToolChain::getHIPDeviceLibs().
getHIPVersion()
std::string clang::driver::RocmInstallationDetector::getHIPVersion () const inline
Definition at line 275 of file ROCm.h.
getHIPVersionArg()
StringRef clang::driver::RocmInstallationDetector::getHIPVersionArg () const inline
Get the value for –hip-version argument.
Definition at line 273 of file ROCm.h.
getIncludePath()
StringRef clang::driver::RocmInstallationDetector::getIncludePath () const inline
Get the detected path to Rocm's bin directory.
Get the detected Rocm Include path.
Definition at line 195 of file ROCm.h.
Referenced by AddHIPIncludeArgs().
getInstallPath()
StringRef clang::driver::RocmInstallationDetector::getInstallPath () const inline
Get the detected Rocm install's version.
Get the detected Rocm installation path.
Definition at line 189 of file ROCm.h.
getLibDeviceFile()
std::string clang::driver::RocmInstallationDetector::getLibDeviceFile (StringRef Gpu) const inline
Get libdevice file for given architecture.
Definition at line 254 of file ROCm.h.
Referenced by clang::driver::toolchains::ROCMToolChain::addClangTargetOptions(), and clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames().
getLibDevicePath()
StringRef clang::driver::RocmInstallationDetector::getLibDevicePath () const inline
Get the detected Rocm device library path.
Definition at line 201 of file ROCm.h.
getLibPath()
StringRef clang::driver::RocmInstallationDetector::getLibPath () const inline
Get the detected Rocm library path.
Definition at line 198 of file ROCm.h.
getOCKLPath()
StringRef clang::driver::RocmInstallationDetector::getOCKLPath () const inline
Definition at line 208 of file ROCm.h.
getOCMLPath()
StringRef clang::driver::RocmInstallationDetector::getOCMLPath () const inline
Definition at line 203 of file ROCm.h.
getOpenCLPath()
StringRef clang::driver::RocmInstallationDetector::getOpenCLPath () const inline
Definition at line 213 of file ROCm.h.
References clang::OpenCL.
Referenced by clang::driver::toolchains::ROCMToolChain::addClangTargetOptions().
getRocmDeviceLibPathArg()
std::vector<std::string> clang::driver::RocmInstallationDetector::getRocmDeviceLibPathArg () const inline
Get the values for –rocm-device-lib-path arguments.
Definition at line 265 of file ROCm.h.
Referenced by clang::driver::toolchains::HIPAMDToolChain::getHIPDeviceLibs().
getRocmPathArg()
StringRef clang::driver::RocmInstallationDetector::getRocmPathArg () const inline
Get the value for –rocm-path argument.
Definition at line 270 of file ROCm.h.
getUnsafeMathPath()
StringRef clang::driver::RocmInstallationDetector::getUnsafeMathPath (bool Enabled) const inline
Definition at line 234 of file ROCm.h.
getWavefrontSize64Path()
StringRef clang::driver::RocmInstallationDetector::getWavefrontSize64Path (bool Enabled) const inline
Definition at line 226 of file ROCm.h.
hasDeviceLibrary()
bool clang::driver::RocmInstallationDetector::hasDeviceLibrary () const inline
Check whether we detected a valid ROCm device library.
Definition at line 180 of file ROCm.h.
Referenced by clang::driver::toolchains::HIPAMDToolChain::getHIPDeviceLibs().
hasHIPRuntime()
bool clang::driver::RocmInstallationDetector::hasHIPRuntime () const inline
Check whether we detected a valid HIP runtime.
Definition at line 177 of file ROCm.h.
Referenced by AddHIPIncludeArgs(), and print().
print()
void RocmInstallationDetector::print (raw_ostream & OS) const
Print information about the detected ROCm installation.
Definition at line 480 of file AMDGPU.cpp.
References hasHIPRuntime().
Referenced by clang::driver::toolchains::MSVCToolChain::printVerboseInfo(), clang::driver::toolchains::Generic_GCC::printVerboseInfo(), and clang::driver::toolchains::Darwin::printVerboseInfo().
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/ROCm.h
lib/Driver/ToolChains/AMDGPU.cpp