clang: clang::ento::BugType Class Reference
clang::ento::BugType Class Reference
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
Public Member Functions
BugType (CheckerNameRef CheckerName, StringRef Desc, StringRef Cat=categories::LogicError, bool SuppressOnSink=false)
BugType (const CheckerBase *Checker, StringRef Desc, StringRef Cat=categories::LogicError, bool SuppressOnSink=false)
virtual ~BugType ()=default
StringRef getDescription () const
StringRef getCategory () const
StringRef getCheckerName () const
bool isSuppressOnSink () const
isSuppressOnSink - Returns true if bug reports associated with this bug type should be suppressed if the end node of the report is post-dominated by a sink node.
Detailed Description
Definition at line 27 of file BugType.h.
Constructor & Destructor Documentation
BugType() [1/2]
clang::ento::BugType::BugType (CheckerNameRef CheckerName, StringRef Desc, StringRef Cat = categories::LogicError, bool SuppressOnSink = false) inline
Definition at line 38 of file BugType.h.
References Category.
BugType() [2/2]
clang::ento::BugType::BugType (const CheckerBase * Checker, StringRef Desc, StringRef Cat = categories::LogicError, bool SuppressOnSink = false) inline
Definition at line 42 of file BugType.h.
References Category.
~BugType()
virtual clang::ento::BugType::~BugType () virtual default
Member Function Documentation
getCategory()
StringRef clang::ento::BugType::getCategory () const inline
Definition at line 49 of file BugType.h.
References Category.
Referenced by generateDiagnosticForBasicReport(), and generateEmptyDiagnosticForReport().
getCheckerName()
StringRef clang::ento::BugType::getCheckerName () const inline
Definition at line 50 of file BugType.h.
References clang::ento::CheckerBase::getCheckerName(), and clang::interp::Ret().
Referenced by generateDiagnosticForBasicReport(), generateEmptyDiagnosticForReport(), and clang::ento::PathSensitiveBugReport::PathSensitiveBugReport().
getDescription()
StringRef clang::ento::BugType::getDescription () const inline
Definition at line 48 of file BugType.h.
Referenced by generateDiagnosticForBasicReport(), and generateEmptyDiagnosticForReport().
isSuppressOnSink()
bool clang::ento::BugType::isSuppressOnSink () const inline
isSuppressOnSink - Returns true if bug reports associated with this bug type should be suppressed if the end node of the report is post-dominated by a sink node.
Definition at line 64 of file BugType.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugType.h
lib/StaticAnalyzer/Core/BugReporter.cpp