clang: clang::DependentFunctionTemplateSpecializationInfo Class Reference
clang::DependentFunctionTemplateSpecializationInfo Class Reference final
Provides information about a dependent function-template specialization declaration.
#include "clang/AST/DeclTemplate.h"
Public Member Functions
unsigned getNumTemplates () const
Returns the number of function templates that this might be a specialization of.
FunctionTemplateDecl * getTemplate (unsigned I) const
Returns the i'th template candidate.
const TemplateArgumentLoc * getTemplateArgs () const
Returns the explicit template arguments that were given.
unsigned getNumTemplateArgs () const
Returns the number of explicit template arguments that were given.
llvm::ArrayRef< TemplateArgumentLoc > arguments () const
const TemplateArgumentLoc & getTemplateArg (unsigned I) const
Returns the nth template argument.
SourceLocation getLAngleLoc () const
SourceLocation getRAngleLoc () const
Static Public Member Functions
static DependentFunctionTemplateSpecializationInfo * Create (ASTContext &Context, const UnresolvedSetImpl &Templates, const TemplateArgumentListInfo &TemplateArgs)
Public Attributes
friend TrailingObjects
Detailed Description
Provides information about a dependent function-template specialization declaration.
Since explicit function template specialization and instantiation declarations can only appear in namespace scope, and you can only specialize a member of a fully-specialized class, the only way to get one of these is in a friend declaration like the following:
template \<class T> void foo(T);
template \<class T> class A {
  friend void foo<>(T);
};
Definition at line 684 of file DeclTemplate.h.
Member Function Documentation
arguments()
llvm::ArrayRef<TemplateArgumentLoc> clang::DependentFunctionTemplateSpecializationInfo::arguments () const inline
Definition at line 733 of file DeclTemplate.h.
References getNumTemplateArgs(), and getTemplateArgs().
Create()
DependentFunctionTemplateSpecializationInfo * DependentFunctionTemplateSpecializationInfo::Create (ASTContext & Context, const UnresolvedSetImpl & Templates, const TemplateArgumentListInfo & TemplateArgs) static
Definition at line 3912 of file Decl.cpp.
References clang::ASTContext::Allocate(), clang::UnresolvedSetImpl::size(), and clang::TemplateArgumentListInfo::size().
Referenced by clang::FunctionDecl::setDependentTemplateSpecialization().
getLAngleLoc()
SourceLocation clang::DependentFunctionTemplateSpecializationInfo::getLAngleLoc () const inline
Definition at line 743 of file DeclTemplate.h.
References clang::SourceRange::getBegin().
Referenced by clang::ASTDeclWriter::VisitFunctionDecl().
getNumTemplateArgs()
unsigned clang::DependentFunctionTemplateSpecializationInfo::getNumTemplateArgs () const inline
Returns the number of explicit template arguments that were given.
Definition at line 731 of file DeclTemplate.h.
Referenced by arguments(), getTemplateArg(), and clang::ASTDeclWriter::VisitFunctionDecl().
getNumTemplates()
unsigned clang::DependentFunctionTemplateSpecializationInfo::getNumTemplates () const inline
Returns the number of function templates that this might be a specialization of.
Definition at line 717 of file DeclTemplate.h.
Referenced by getTemplate(), and clang::ASTDeclWriter::VisitFunctionDecl().
getRAngleLoc()
SourceLocation clang::DependentFunctionTemplateSpecializationInfo::getRAngleLoc () const inline
Definition at line 747 of file DeclTemplate.h.
References clang::SourceRange::getEnd().
Referenced by clang::ASTDeclWriter::VisitFunctionDecl().
getTemplate()
FunctionTemplateDecl* clang::DependentFunctionTemplateSpecializationInfo::getTemplate (unsigned I) const inline
Returns the i'th template candidate.
Definition at line 720 of file DeclTemplate.h.
References getNumTemplates().
Referenced by clang::ASTDeclWriter::VisitFunctionDecl().
getTemplateArg()
const TemplateArgumentLoc& clang::DependentFunctionTemplateSpecializationInfo::getTemplateArg (unsigned I) const inline
Returns the nth template argument.
Definition at line 738 of file DeclTemplate.h.
References getNumTemplateArgs(), and getTemplateArgs().
Referenced by clang::ASTDeclWriter::VisitFunctionDecl().
getTemplateArgs()
const TemplateArgumentLoc* clang::DependentFunctionTemplateSpecializationInfo::getTemplateArgs () const inline
Returns the explicit template arguments that were given.
Definition at line 726 of file DeclTemplate.h.
Referenced by arguments(), and getTemplateArg().
Member Data Documentation
TrailingObjects
friend clang::DependentFunctionTemplateSpecializationInfo::TrailingObjects
Definition at line 709 of file DeclTemplate.h.
The documentation for this class was generated from the following files:
include/clang/AST/DeclTemplate.h
lib/AST/Decl.cpp