clang: clang::OMPCopyprivateClause Class Reference
clang::OMPCopyprivateClause Class Reference final
This represents clause 'copyprivate' in the '#pragma omp ...' directives.
#include "clang/AST/OpenMPClause.h"
Public Types
using helper_expr_iterator = MutableArrayRef< Expr * >::iterator
using helper_expr_const_iterator = ArrayRef< const Expr * >::iterator
using helper_expr_range = llvm::iterator_range< helper_expr_iterator >
using helper_expr_const_range = llvm::iterator_range< helper_expr_const_iterator >
Public Types inherited from clang::OMPVarListClause< OMPCopyprivateClause >
using varlist_iterator = MutableArrayRef< Expr * >::iterator
using varlist_const_iterator = ArrayRef< const Expr * >::iterator
using varlist_range = llvm::iterator_range< varlist_iterator >
using varlist_const_range = llvm::iterator_range< varlist_const_iterator >
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
helper_expr_const_range source_exprs () const
helper_expr_range source_exprs ()
helper_expr_const_range destination_exprs () const
helper_expr_range destination_exprs ()
helper_expr_const_range assignment_ops () const
helper_expr_range assignment_ops ()
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPVarListClause< OMPCopyprivateClause >
ArrayRef< const Expr * > getVarRefs () const
Fetches list of all variables in the clause.
unsigned varlist_size () const
bool varlist_empty () const
varlist_range varlists ()
varlist_const_range varlists () const
varlist_iterator varlist_begin ()
varlist_const_iterator varlist_begin () const
varlist_iterator varlist_end ()
varlist_const_iterator varlist_end () const
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Static Public Member Functions
static OMPCopyprivateClause * Create (const ASTContext &C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< Expr * > VL, ArrayRef< Expr * > SrcExprs, ArrayRef< Expr * > DstExprs, ArrayRef< Expr * > AssignmentOps)
Creates clause with a list of variables VL.
static OMPCopyprivateClause * CreateEmpty (const ASTContext &C, unsigned N)
Creates an empty clause with N variables.
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Friends
class OMPClauseReader
Additional Inherited Members
Protected Member Functions inherited from clang::OMPVarListClause< OMPCopyprivateClause >
OMPVarListClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, unsigned N)
Build a clause with N variables.
MutableArrayRef< Expr * > getVarRefs ()
Fetches list of variables associated with this clause.
void setVarRefs (ArrayRef< Expr * > VL)
Sets the list of variables for this clause.
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Detailed Description
This represents clause 'copyprivate' in the '#pragma omp ...' directives.
#pragma omp single copyprivate(a,b)
In this example directive '#pragma omp single' has clause 'copyprivate' with the variables 'a' and 'b'.
Definition at line 4592 of file OpenMPClause.h.
Member Typedef Documentation
helper_expr_const_iterator
using clang::OMPCopyprivateClause::helper_expr_const_iterator = ArrayRef<const Expr *>::iterator
Definition at line 4692 of file OpenMPClause.h.
helper_expr_const_range
using clang::OMPCopyprivateClause::helper_expr_const_range = llvm::iterator_range<helper_expr_const_iterator>
Definition at line 4694 of file OpenMPClause.h.
helper_expr_iterator
using clang::OMPCopyprivateClause::helper_expr_iterator = MutableArrayRef<Expr *>::iterator
Definition at line 4691 of file OpenMPClause.h.
helper_expr_range
using clang::OMPCopyprivateClause::helper_expr_range = llvm::iterator_range<helper_expr_iterator>
Definition at line 4693 of file OpenMPClause.h.
Member Function Documentation
assignment_ops() [1/2]
helper_expr_range clang::OMPCopyprivateClause::assignment_ops () inline
Definition at line 4721 of file OpenMPClause.h.
assignment_ops() [2/2]
helper_expr_const_range clang::OMPCopyprivateClause::assignment_ops () const inline
Definition at line 4716 of file OpenMPClause.h.
children() [1/2]
child_range clang::OMPCopyprivateClause::children () inline
Definition at line 4726 of file OpenMPClause.h.
References clang::OMPVarListClause< OMPCopyprivateClause >::varlist_begin(), and clang::OMPVarListClause< OMPCopyprivateClause >::varlist_end().
Referenced by children().
children() [2/2]
const_child_range clang::OMPCopyprivateClause::children () const inline
Definition at line 4731 of file OpenMPClause.h.
References children().
classof()
static bool clang::OMPCopyprivateClause::classof (const OMPClause * T) inline static
Definition at line 4743 of file OpenMPClause.h.
References clang::T.
Create()
OMPCopyprivateClause * OMPCopyprivateClause::Create (const ASTContext & C, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc, ArrayRef< Expr * > VL, ArrayRef< Expr * > SrcExprs, ArrayRef< Expr * > DstExprs, ArrayRef< Expr * > AssignmentOps) static
Creates clause with a list of variables VL.
Parameters
C AST context.
StartLoc Starting location of the clause.
LParenLoc Location of '('.
EndLoc Ending location of the clause.
VL List of references to the variables.
SrcExprs List of helper expressions for proper generation of assignment operation required for copyprivate clause. This list represents sources.
DstExprs List of helper expressions for proper generation of assignment operation required for copyprivate clause. This list represents destinations.
AssignmentOps List of helper expressions that represents assignment operation:
DstExprs = SrcExprs;
Required for proper codegen of final assignment performed by the copyprivate clause.
Definition at line 720 of file OpenMPClause.cpp.
References clang::OMPVarListClause< T >::setVarRefs().
Referenced by clang::SemaOpenMP::ActOnOpenMPCopyprivateClause().
CreateEmpty()
OMPCopyprivateClause * OMPCopyprivateClause::CreateEmpty (const ASTContext & C, unsigned N) static
Creates an empty clause with N variables.
Parameters
C AST context.
N The number of variables.
Definition at line 734 of file OpenMPClause.cpp.
Referenced by clang::OMPClauseReader::readClause().
destination_exprs() [1/2]
helper_expr_range clang::OMPCopyprivateClause::destination_exprs () inline
Definition at line 4711 of file OpenMPClause.h.
destination_exprs() [2/2]
helper_expr_const_range clang::OMPCopyprivateClause::destination_exprs () const inline
Definition at line 4706 of file OpenMPClause.h.
source_exprs() [1/2]
helper_expr_range clang::OMPCopyprivateClause::source_exprs () inline
Definition at line 4702 of file OpenMPClause.h.
source_exprs() [2/2]
helper_expr_const_range clang::OMPCopyprivateClause::source_exprs () const inline
Definition at line 4697 of file OpenMPClause.h.
used_children() [1/2]
child_range clang::OMPCopyprivateClause::used_children () inline
Definition at line 4736 of file OpenMPClause.h.
used_children() [2/2]
const_child_range clang::OMPCopyprivateClause::used_children () const inline
Definition at line 4739 of file OpenMPClause.h.
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 4595 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp