clang: clang::CodeGen::EHTerminateScope Class Reference
clang::CodeGen::EHTerminateScope Class Reference
An exceptions scope which calls std::terminate if any exception reaches it.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCleanup.h"
Public Member Functions
EHTerminateScope (EHScopeStack::stable_iterator enclosingEHScope)
Public Member Functions inherited from clang::CodeGen::EHScope
EHScope (Kind kind, EHScopeStack::stable_iterator enclosingEHScope)
Kind getKind () const
llvm::BasicBlock * getCachedLandingPad () const
void setCachedLandingPad (llvm::BasicBlock *block)
llvm::BasicBlock * getCachedEHDispatchBlock () const
void setCachedEHDispatchBlock (llvm::BasicBlock *block)
bool hasEHBranches () const
EHScopeStack::stable_iterator getEnclosingEHScope () const
Static Public Member Functions
static size_t getSize ()
static bool classof (const EHScope *scope)
Additional Inherited Members
Public Types inherited from clang::CodeGen::EHScope
enum Kind { Cleanup , Catch , Terminate , Filter }
Protected Attributes inherited from clang::CodeGen::EHScope
union {
CommonBitFields CommonBits
CatchBitFields CatchBits
CleanupBitFields CleanupBits
FilterBitFields FilterBits
};
Detailed Description
An exceptions scope which calls std::terminate if any exception reaches it.
Definition at line 488 of file CGCleanup.h.
Constructor & Destructor Documentation
EHTerminateScope()
clang::CodeGen::EHTerminateScope::EHTerminateScope (EHScopeStack::stable_iterator enclosingEHScope) inline
Definition at line 490 of file CGCleanup.h.
Referenced by getSize().
Member Function Documentation
classof()
static bool clang::CodeGen::EHTerminateScope::classof (const EHScope * scope) inline static
Definition at line 494 of file CGCleanup.h.
References clang::CodeGen::EHScope::getKind(), and clang::CodeGen::EHScope::Terminate.
getSize()
static size_t clang::CodeGen::EHTerminateScope::getSize () inline static
Definition at line 492 of file CGCleanup.h.
References EHTerminateScope().
Referenced by clang::CodeGen::EHScopeStack::iterator::operator++(), clang::CodeGen::EHScopeStack::popTerminate(), and clang::CodeGen::EHScopeStack::pushTerminate().
The documentation for this class was generated from the following file:
lib/CodeGen/CGCleanup.h