clang: clang::driver::Action Class Reference
clang::driver::Action Class Reference
Action - Represent an abstract compilation step to perform.
#include "clang/Driver/Action.h"
Public Types
enum ActionClass {
InputClass = 0 , BindArchClass , OffloadClass , ForEachWrappingClass ,
PreprocessJobClass , PrecompileJobClass , ExtractAPIJobClass , AnalyzeJobClass ,
MigrateJobClass , CompileJobClass , BackendJobClass , AssembleJobClass ,
LinkJobClass , IfsMergeJobClass , LipoJobClass , DsymutilJobClass ,
VerifyDebugInfoJobClass , VerifyPCHJobClass , OffloadBundlingJobClass , OffloadUnbundlingJobClass ,
OffloadWrapperJobClass , OffloadPackagerJobClass , OffloadDepsJobClass , SPIRVTranslatorJobClass ,
SYCLPostLinkJobClass , BackendCompileJobClass , FileTableTformJobClass , AppendFooterJobClass ,
SpirvToIrWrapperJobClass , LinkerWrapperJobClass , StaticLibJobClass , BinaryAnalyzeJobClass ,
JobClassFirst = PreprocessJobClass , JobClassLast = BinaryAnalyzeJobClass
}
enum OffloadKind {
OFK_None = 0x00 , OFK_Host = 0x01 , OFK_Cuda = 0x02 , OFK_OpenMP = 0x04 ,
OFK_HIP = 0x08 , OFK_SYCL = 0x10
}
using size_type = ActionList::size_type
using input_iterator = ActionList::iterator
using input_const_iterator = ActionList::const_iterator
using input_range = llvm::iterator_range< input_iterator >
using input_const_range = llvm::iterator_range< input_const_iterator >
Public Member Functions
virtual ~Action ()
const char * getClassName () const
ActionClass getKind () const
types::ID getType () const
ActionList & getInputs ()
const ActionList & getInputs () const
size_type size () const
input_iterator input_begin ()
input_iterator input_end ()
input_range inputs ()
input_const_iterator input_begin () const
input_const_iterator input_end () const
input_const_range inputs () const
void setCannotBeCollapsedWithNextDependentAction ()
Mark this action as not legal to collapse.
bool isCollapsingWithNextDependentActionLegal () const
Return true if this function can be collapsed with others.
std::string getOffloadingKindPrefix () const
Return a string containing the offload kind of the action.
void propagateDeviceOffloadInfo (OffloadKind OKind, const char *OArch, const ToolChain *OToolChain)
Set the device offload info of this action and propagate it to its dependences.
void propagateHostOffloadInfo (unsigned OKinds, const char *OArch)
Append the host offload info of this action and propagate it to its dependences.
void setHostOffloadInfo (unsigned OKinds, const char *OArch)
void propagateOffloadInfo (const Action *A)
Set the offload info of this action to be the same as the provided action, and propagate it to its dependences.
unsigned getOffloadingHostActiveKinds () const
OffloadKind getOffloadingDeviceKind () const
const char * getOffloadingArch () const
const ToolChain * getOffloadingToolChain () const
bool isHostOffloading (unsigned int OKind) const
Check if this action have any offload kinds.
bool isDeviceOffloading (OffloadKind OKind) const
bool isOffloading (OffloadKind OKind) const
Static Public Member Functions
static const char * getClassName (ActionClass AC)
static std::string GetOffloadingFileNamePrefix (OffloadKind Kind, StringRef NormalizedTriple, bool CreatePrefixForHost=false)
Return a string that can be used as prefix in order to generate unique files for each offloading kind.
static StringRef GetOffloadKindName (OffloadKind Kind)
Return a string containing a offload kind name.
Protected Member Functions
Action (ActionClass Kind, types::ID Type)
Action (ActionClass Kind, Action *Input, types::ID Type)
Action (ActionClass Kind, Action *Input)
Action (ActionClass Kind, const ActionList &Inputs, types::ID Type)
Protected Attributes
unsigned ActiveOffloadKindMask = 0u
Offload information.
OffloadKind OffloadingDeviceKind = OFK_None
Offloading kind of the device.
const char * OffloadingArch = nullptr
The Offloading architecture associated with this action.
const ToolChain * OffloadingToolChain = nullptr
The Offloading toolchain associated with this device action.
Detailed Description
Action - Represent an abstract compilation step to perform.
An action represents an edge in the compilation graph; typically it is a job to transform an input using some tool.
The current driver is hard wired to expect actions which produce a single primary output, at least in terms of controlling the compilation. Actions can produce auxiliary files, but can only produce a single output to feed into subsequent actions.
Actions are usually owned by a Compilation, which creates new actions via MakeAction().
Definition at line 49 of file Action.h.
Member Typedef Documentation
input_const_iterator
using clang::driver::Action::input_const_iterator = ActionList::const_iterator
Definition at line 53 of file Action.h.
input_const_range
using clang::driver::Action::input_const_range = llvm::iterator_range<input_const_iterator>
Definition at line 55 of file Action.h.
input_iterator
using clang::driver::Action::input_iterator = ActionList::iterator
Definition at line 52 of file Action.h.
input_range
using clang::driver::Action::input_range = llvm::iterator_range<input_iterator>
Definition at line 54 of file Action.h.
size_type
using clang::driver::Action::size_type = ActionList::size_type
Definition at line 51 of file Action.h.
Member Enumeration Documentation
ActionClass
enum clang::driver::Action::ActionClass
Enumerator
InputClass
BindArchClass
OffloadClass
ForEachWrappingClass
PreprocessJobClass
PrecompileJobClass
ExtractAPIJobClass
AnalyzeJobClass
MigrateJobClass
CompileJobClass
BackendJobClass
AssembleJobClass
LinkJobClass
IfsMergeJobClass
LipoJobClass
DsymutilJobClass
VerifyDebugInfoJobClass
VerifyPCHJobClass
OffloadBundlingJobClass
OffloadUnbundlingJobClass
OffloadWrapperJobClass
OffloadPackagerJobClass
OffloadDepsJobClass
SPIRVTranslatorJobClass
SYCLPostLinkJobClass
BackendCompileJobClass
FileTableTformJobClass
AppendFooterJobClass
SpirvToIrWrapperJobClass
LinkerWrapperJobClass
StaticLibJobClass
BinaryAnalyzeJobClass
JobClassFirst
JobClassLast
Definition at line 57 of file Action.h.
OffloadKind
enum clang::driver::Action::OffloadKind
Enumerator
OFK_None
OFK_Host
OFK_Cuda
OFK_OpenMP
OFK_HIP
OFK_SYCL
Definition at line 98 of file Action.h.
Constructor & Destructor Documentation
Action() [1/4]
clang::driver::Action::Action (ActionClass Kind, types::ID Type) inline protected
Definition at line 146 of file Action.h.
Action() [2/4]
clang::driver::Action::Action (ActionClass Kind, Action * Input, types::ID Type) inline protected
Definition at line 147 of file Action.h.
Action() [3/4]
clang::driver::Action::Action (ActionClass Kind, Action * Input) inline protected
Definition at line 149 of file Action.h.
Action() [4/4]
clang::driver::Action::Action (ActionClass Kind, const ActionList & Inputs, types::ID Type) inline protected
Definition at line 151 of file Action.h.
~Action()
Action::~Action () virtual default
Member Function Documentation
getClassName() [1/2]
const char* clang::driver::Action::getClassName () const inline
Definition at line 157 of file Action.h.
References getKind().
getClassName() [2/2]
const char * Action::getClassName (ActionClass AC) static
Definition at line 20 of file Action.cpp.
getInputs() [1/2]
ActionList& clang::driver::Action::getInputs () inline
Definition at line 162 of file Action.h.
Referenced by clang::driver::ExtractAPIJobAction::addHeaderInput(), clang::driver::Driver::BuildJobs(), clang::driver::Driver::BuildOffloadingActions(), CollectForEachInputs(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::darwin::Assembler::ConstructJob(), clang::driver::OffloadAction::doOnEachDeviceDependence(), clang::driver::OffloadAction::doOnHostDependence(), clang::driver::OffloadAction::getHostDependence(), clang::driver::ForEachWrappingAction::getJobAction(), clang::driver::OffloadAction::getSingleDeviceDependence(), clang::driver::ForEachWrappingAction::getTFormInput(), HasPreprocessOutput(), clang::driver::OffloadAction::hasSingleDeviceDependence(), and clang::driver::OffloadAction::OffloadAction().
getInputs() [2/2]
const ActionList& clang::driver::Action::getInputs () const inline
Definition at line 163 of file Action.h.
getKind()
ActionClass clang::driver::Action::getKind () const inline
Definition at line 159 of file Action.h.
Referenced by clang::driver::Driver::BuildInputs(), clang::driver::Driver::BuildJobs(), clang::driver::InputAction::classof(), clang::driver::BindArchAction::classof(), clang::driver::OffloadAction::classof(), clang::driver::JobAction::classof(), clang::driver::PreprocessJobAction::classof(), clang::driver::PrecompileJobAction::classof(), clang::driver::ExtractAPIJobAction::classof(), clang::driver::AnalyzeJobAction::classof(), clang::driver::MigrateJobAction::classof(), clang::driver::CompileJobAction::classof(), clang::driver::BackendJobAction::classof(), clang::driver::AssembleJobAction::classof(), clang::driver::IfsMergeJobAction::classof(), clang::driver::LinkJobAction::classof(), clang::driver::LipoJobAction::classof(), clang::driver::DsymutilJobAction::classof(), clang::driver::VerifyJobAction::classof(), clang::driver::VerifyDebugInfoJobAction::classof(), clang::driver::VerifyPCHJobAction::classof(), clang::driver::OffloadBundlingJobAction::classof(), clang::driver::OffloadUnbundlingJobAction::classof(), clang::driver::OffloadWrapperJobAction::classof(), clang::driver::OffloadPackagerJobAction::classof(), clang::driver::OffloadDepsJobAction::classof(), clang::driver::SPIRVTranslatorJobAction::classof(), clang::driver::SYCLPostLinkJobAction::classof(), clang::driver::BackendCompileJobAction::classof(), clang::driver::FileTableTformJobAction::classof(), clang::driver::AppendFooterJobAction::classof(), clang::driver::SpirvToIrWrapperJobAction::classof(), clang::driver::LinkerWrapperJobAction::classof(), clang::driver::StaticLibJobAction::classof(), clang::driver::ForEachWrappingAction::classof(), clang::driver::BinaryAnalyzeJobAction::classof(), clang::driver::tools::darwin::Assembler::ConstructJob(), getClassName(), getLinkerArgs(), clang::driver::toolchains::CudaToolChain::SelectTool(), and clang::driver::toolchains::HIPAMDToolChain::SelectTool().
getOffloadingArch()
const char* clang::driver::Action::getOffloadingArch () const inline
Definition at line 223 of file Action.h.
References OffloadingArch.
Referenced by clang::driver::toolchains::SYCLToolChain::AddImpliedTargetArgs(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::tools::SPIRVTranslator::ConstructJob(), clang::driver::tools::SYCLPostLink::ConstructJob(), clang::driver::tools::SpirvToIrWrapper::ConstructJob(), clang::driver::tools::NVPTX::Assembler::ConstructJob(), clang::driver::tools::SYCL::gen::BackendCompiler::ConstructJob(), clang::driver::toolchains::AMDGPUToolChain::getDefaultDenormalModeForType(), propagateOffloadInfo(), and renderRemarksOptions().
getOffloadingDeviceKind()
OffloadKind clang::driver::Action::getOffloadingDeviceKind () const inline
Definition at line 222 of file Action.h.
References OffloadingDeviceKind.
Referenced by clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::toolchains::AMDGPUToolChain::getDefaultDenormalModeForType(), clang::driver::toolchains::CudaToolChain::getDefaultDenormalModeForType(), clang::driver::Driver::GetNamedOutputPath(), GetSDLFromOffloadArchive(), propagateOffloadInfo(), and renderRemarksOptions().
GetOffloadingFileNamePrefix()
std::string Action::GetOffloadingFileNamePrefix (OffloadKind Kind, StringRef NormalizedTriple, bool CreatePrefixForHost = false) static
Return a string that can be used as prefix in order to generate unique files for each offloading kind.
By default, no prefix is used for non-device kinds, except if CreatePrefixForHost is set.
Definition at line 165 of file Action.cpp.
Referenced by renderRemarksOptions().
getOffloadingHostActiveKinds()
unsigned clang::driver::Action::getOffloadingHostActiveKinds () const inline
Definition at line 218 of file Action.h.
References ActiveOffloadKindMask.
Referenced by clang::driver::Driver::GetNamedOutputPath(), and propagateOffloadInfo().
getOffloadingKindPrefix()
std::string Action::getOffloadingKindPrefix () const
Return a string containing the offload kind of the action.
Definition at line 122 of file Action.cpp.
getOffloadingToolChain()
const ToolChain* clang::driver::Action::getOffloadingToolChain () const inline
Definition at line 224 of file Action.h.
References OffloadingToolChain.
Referenced by clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::Driver::ConstructPhaseAction(), clang::driver::Driver::GetNamedOutputPath(), and propagateOffloadInfo().
GetOffloadKindName()
StringRef Action::GetOffloadKindName (OffloadKind Kind) static
Return a string containing a offload kind name.
Return a string with the offload kind name.
If that is not defined, we assume 'host'.
Definition at line 181 of file Action.cpp.
Referenced by clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), GetSDLFromOffloadArchive(), and GetTriplePlusArchString().
getType()
types::ID clang::driver::Action::getType () const inline
Definition at line 160 of file Action.h.
Referenced by clang::driver::Driver::BuildJobs(), clang::driver::Driver::BuildOffloadingActions(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::darwin::Assembler::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::AMDGCN::Linker::ConstructJob(), clang::driver::tools::HIPSPV::Linker::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), clang::driver::Driver::ConstructPhaseAction(), GetModuleOutputPath(), clang::driver::Driver::GetNamedOutputPath(), clang::driver::tools::gcc::Compiler::RenderExtraToolArgs(), clang::driver::toolchains::CudaToolChain::SelectTool(), and clang::driver::toolchains::HIPAMDToolChain::SelectTool().
input_begin() [1/2]
input_iterator clang::driver::Action::input_begin () inline
Definition at line 167 of file Action.h.
Referenced by inputs(), clang::driver::Driver::ShouldUseClangCompiler(), and clang::driver::Driver::ShouldUseFlangCompiler().
input_begin() [2/2]
input_const_iterator clang::driver::Action::input_begin () const inline
Definition at line 170 of file Action.h.
input_end() [1/2]
input_iterator clang::driver::Action::input_end () inline
Definition at line 168 of file Action.h.
Referenced by inputs().
input_end() [2/2]
input_const_iterator clang::driver::Action::input_end () const inline
Definition at line 171 of file Action.h.
inputs() [1/2]
input_range clang::driver::Action::inputs () inline
Definition at line 169 of file Action.h.
References input_begin(), and input_end().
Referenced by ActionFailed(), ContainsAppendFooterAction(), ContainsCompileAction(), ContainsCompileOrAssembleAction(), ContainsOffloadDepsAction(), and ContainsWrapperAction().
inputs() [2/2]
input_const_range clang::driver::Action::inputs () const inline
Definition at line 172 of file Action.h.
References input_begin(), and input_end().
isCollapsingWithNextDependentActionLegal()
bool clang::driver::Action::isCollapsingWithNextDependentActionLegal () const inline
Return true if this function can be collapsed with others.
Definition at line 182 of file Action.h.
isDeviceOffloading()
bool clang::driver::Action::isDeviceOffloading (OffloadKind OKind) const inline
Definition at line 233 of file Action.h.
References OffloadingDeviceKind.
Referenced by clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::SPIRVTranslator::ConstructJob(), clang::driver::tools::NVPTX::Assembler::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), forAllAssociatedToolChains(), isOffloading(), RenderFloatingPointOptions(), renderRemarksOptions(), and ShouldEnableAutolink().
isHostOffloading()
bool clang::driver::Action::isHostOffloading (unsigned int OKind) const inline
Check if this action have any offload kinds.
Note that host offload kinds are only set if the action is a dependence to a host offload action.
Definition at line 230 of file Action.h.
References ActiveOffloadKindMask.
Referenced by clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::NVPTX::OpenMPLinker::ConstructJob(), forAllAssociatedToolChains(), and isOffloading().
isOffloading()
bool clang::driver::Action::isOffloading (OffloadKind OKind) const inline
Definition at line 236 of file Action.h.
References isDeviceOffloading(), and isHostOffloading().
Referenced by ActionFailed(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::NVPTX::Assembler::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::Driver::GetNamedOutputPath(), and RenderFloatingPointOptions().
propagateDeviceOffloadInfo()
void Action::propagateDeviceOffloadInfo (OffloadKind OKind, const char * OArch, const ToolChain * OToolChain)
Set the device offload info of this action and propagate it to its dependences.
Definition at line 76 of file Action.cpp.
Referenced by clang::driver::Driver::BuildOffloadingActions().
propagateHostOffloadInfo()
void Action::propagateHostOffloadInfo (unsigned OKinds, const char * OArch)
Append the host offload info of this action and propagate it to its dependences.
Definition at line 99 of file Action.cpp.
Referenced by clang::driver::OffloadAction::OffloadAction(), and clang::driver::OffloadDepsJobAction::OffloadDepsJobAction().
propagateOffloadInfo()
void Action::propagateOffloadInfo (const Action * A)
Set the offload info of this action to be the same as the provided action, and propagate it to its dependences.
Definition at line 113 of file Action.cpp.
References getOffloadingArch(), getOffloadingDeviceKind(), getOffloadingHostActiveKinds(), and getOffloadingToolChain().
setCannotBeCollapsedWithNextDependentAction()
void clang::driver::Action::setCannotBeCollapsedWithNextDependentAction () inline
Mark this action as not legal to collapse.
Definition at line 177 of file Action.h.
Referenced by clang::driver::Driver::BuildOffloadingActions().
setHostOffloadInfo()
void clang::driver::Action::setHostOffloadInfo (unsigned OKinds, const char * OArch) inline
Definition at line 209 of file Action.h.
References ActiveOffloadKindMask, and OffloadingArch.
size()
size_type clang::driver::Action::size () const inline
Definition at line 165 of file Action.h.
Referenced by clang::driver::Driver::BuildJobs(), clang::driver::OffloadAction::doOnEachDeviceDependence(), clang::driver::OffloadAction::OffloadAction(), clang::driver::Driver::ShouldUseClangCompiler(), and clang::driver::Driver::ShouldUseFlangCompiler().
Member Data Documentation
ActiveOffloadKindMask
unsigned clang::driver::Action::ActiveOffloadKindMask = 0u protected
Offload information.
The host offloading kind - a combination of kinds encoded in a mask. Multiple programming models may be supported simultaneously by the same host.
Definition at line 135 of file Action.h.
Referenced by getOffloadingHostActiveKinds(), isHostOffloading(), clang::driver::OffloadAction::OffloadAction(), clang::driver::OffloadDepsJobAction::OffloadDepsJobAction(), and setHostOffloadInfo().
OffloadingArch
const char* clang::driver::Action::OffloadingArch = nullptr protected
The Offloading architecture associated with this action.
Definition at line 141 of file Action.h.
Referenced by getOffloadingArch(), clang::driver::OffloadAction::OffloadAction(), clang::driver::OffloadDepsJobAction::OffloadDepsJobAction(), and setHostOffloadInfo().
OffloadingDeviceKind
OffloadKind clang::driver::Action::OffloadingDeviceKind = OFK_None protected
Offloading kind of the device.
Definition at line 138 of file Action.h.
Referenced by getOffloadingDeviceKind(), isDeviceOffloading(), and clang::driver::OffloadAction::OffloadAction().
OffloadingToolChain
const ToolChain* clang::driver::Action::OffloadingToolChain = nullptr protected
The Offloading toolchain associated with this device action.
Definition at line 144 of file Action.h.
Referenced by getOffloadingToolChain(), and clang::driver::OffloadAction::OffloadAction().
The documentation for this class was generated from the following files:
include/clang/Driver/Action.h
lib/Driver/Action.cpp