clang: clang::ento::ObjCMethodCall Class Reference
clang::ento::ObjCMethodCall Class Reference
Represents any expression that calls an Objective-C method.
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
Public Member Functions
const ObjCMessageExpr * getOriginExpr () const override
Returns the expression whose value will be the result of this call.
const ObjCMethodDecl * getDecl () const override
Returns the declaration of the function or method that will be called.
unsigned getNumArgs () const override
Returns the number of arguments (explicit and implicit).
const Expr * getArgExpr (unsigned Index) const override
Returns the expression associated with a given argument.
bool isInstanceMessage () const
ObjCMethodFamily getMethodFamily () const
Selector getSelector () const
SourceRange getSourceRange () const override
Returns a source range for the entire call, suitable for outputting in diagnostics.
SVal getReceiverSVal () const
Returns the value of the receiver at the time of this call.
const ObjCInterfaceDecl * getReceiverInterface () const
Get the interface for the receiver.
bool isReceiverSelfOrSuper () const
Checks if the receiver refers to 'self' or 'super'.
ObjCMessageKind getMessageKind () const
Returns how the message was written in the source (property access, subscript, or explicit message send).
bool isSetter () const
Returns true if this property access or subscript is a setter (has the form of an assignment).
const ObjCPropertyDecl * getAccessedProperty () const
RuntimeDefinition getRuntimeDefinition () const override
Returns the definition of the function or method that will be called.
bool argumentsMayEscape () const override
Returns true if any of the arguments are known to escape to long- term storage, even if this method will not modify them.
void getInitialStackFrameContents (const StackFrameContext *CalleeCtx, BindingsTy &Bindings) const override
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
ArrayRef< ParmVarDecl * > parameters () const override
Return call's formal parameters.
Kind getKind () const override
Returns the kind of call this is.
StringRef getKindAsString () const override
Public Member Functions inherited from clang::ento::CallEvent
CallEvent & operator= (const CallEvent &)=delete
virtual ~CallEvent ()=default
bool isForeign () const
void setForeign (bool B) const
const ProgramStateRef & getState () const
The state in which the call is being evaluated.
const LocationContext * getLocationContext () const
The context in which the call is being evaluated.
const CFGBlock::ConstCFGElementRef & getCFGElementRef () const
bool isInSystemHeader () const
Returns true if the callee is known to be from a system header.
virtual SVal getArgSVal (unsigned Index) const
Returns the value of a given argument at the time of the call.
virtual SourceRange getArgSourceRange (unsigned Index) const
Returns the source range for errors associated with this argument.
QualType getResultType () const
Returns the result type, adjusted for references.
SVal getReturnValue () const
Returns the return value of the call.
bool hasNonNullArgumentsWithType (bool(*Condition)(QualType)) const
Returns true if the type of any of the non-null arguments satisfies the condition.
bool hasNonZeroCallbackArg () const
Returns true if any of the arguments appear to represent callbacks.
bool hasVoidPointerToNonConstArg () const
Returns true if any of the arguments is void*.
bool isGlobalCFunction (StringRef SpecificName=StringRef()) const
Returns true if the callee is an externally-visible function in the top-level namespace, such as malloc.
const IdentifierInfo * getCalleeIdentifier () const
Returns the name of the callee, if its name is a simple identifier.
ProgramPoint getProgramPoint (bool IsPreVisit=false, const ProgramPointTag *Tag=nullptr) const
Returns an appropriate ProgramPoint for this call.
ProgramStateRef invalidateRegions (unsigned BlockCount, ProgramStateRef Orig=nullptr) const
Returns a new state with all argument regions invalidated.
template<typename T >
CallEventRef< T > cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
CallEventRef cloneWithState (ProgramStateRef NewState) const
Returns a copy of this CallEvent, but using the given state.
AnalysisDeclContext * getCalleeAnalysisDeclContext () const
Returns AnalysisDeclContext for the callee stack frame.
const StackFrameContext * getCalleeStackFrame (unsigned BlockCount) const
Returns the callee stack frame.
const ParamVarRegion * getParameterLocation (unsigned Index, unsigned BlockCount) const
Returns memory location for a parameter variable within the callee stack frame.
bool isArgumentConstructedDirectly (unsigned Index) const
Returns true if on the current path, the argument was constructed by calling a C++ constructor over it.
virtual std::optional< unsigned > getAdjustedParameterIndex (unsigned ASTArgumentIndex) const
Some calls have parameter numbering mismatched from argument numbering.
virtual unsigned getASTArgumentIndex (unsigned CallArgumentIndex) const
Some call event sub-classes conveniently adjust mismatching AST indices to match parameter indices.
const ConstructionContext * getConstructionContext () const
Returns the construction context of the call, if it is a C++ constructor call or a call of a function returning a C++ class instance.
std::optional< SVal > getReturnValueUnderConstruction () const
If the call returns a C++ record type then the region of its return value can be retrieved from its construction context.
const CallEventRef getCaller () const
bool isCalledFromSystemHeader () const
param_type_iterator param_type_begin () const
Returns an iterator over the types of the call's formal parameters.
param_type_iterator param_type_end () const
void dump (raw_ostream &Out) const
void dump () const
Static Public Member Functions
static bool classof (const CallEvent *CA)
Static Public Member Functions inherited from clang::ento::CallEvent
static bool isCallStmt (const Stmt *S)
Returns true if this is a statement is a function or method call of some kind.
static QualType getDeclaredResultType (const Decl *D)
Returns the result type of a function or method declaration.
static bool isVariadic (const Decl *D)
Returns true if the given decl is known to be variadic.
Protected Member Functions
ObjCMethodCall (const ObjCMessageExpr *Msg, ProgramStateRef St, const LocationContext *LCtx, CFGBlock::ConstCFGElementRef ElemRef)
ObjCMethodCall (const ObjCMethodCall &Other)=default
void cloneTo (void *Dest) const override
Copies this CallEvent, with vtable intact, into a new block of memory.
void getExtraInvalidatedValues (ValueList &Values, RegionAndSymbolInvalidationTraits *ETraits) const override
Used to specify non-argument regions that will be invalidated as a result of this call.
virtual bool canBeOverridenInSubclass (ObjCInterfaceDecl *IDecl, Selector Sel) const
Check if the selector may have multiple definitions (may have overrides).
Protected Member Functions inherited from clang::ento::CallEvent
CallEvent (const Expr *E, ProgramStateRef state, const LocationContext *lctx, CFGBlock::ConstCFGElementRef ElemRef)
CallEvent (const Decl *D, ProgramStateRef state, const LocationContext *lctx, CFGBlock::ConstCFGElementRef ElemRef)
CallEvent (const CallEvent &Original)
SVal getSVal (const Stmt *S) const
Get the value of arbitrary expressions at this point in the path.
Friends
class CallEventManager
Additional Inherited Members
Public Types inherited from clang::ento::CallEvent
using Kind = CallEventKind
using FrameBindingTy = std::pair< SVal, SVal >
using BindingsTy = SmallVectorImpl< FrameBindingTy >
using param_type_iterator = llvm::mapped_iterator< ArrayRef< ParmVarDecl * >::iterator, GetTypeFn >
Protected Types inherited from clang::ento::CallEvent
using ValueList = SmallVectorImpl< SVal >
Protected Attributes inherited from clang::ento::CallEvent
const void * Data
SourceLocation Location
Detailed Description
Represents any expression that calls an Objective-C method.
This includes all of the kinds listed in ObjCMessageKind.
Definition at line 1243 of file CallEvent.h.
Constructor & Destructor Documentation
ObjCMethodCall() [1/2]
clang::ento::ObjCMethodCall::ObjCMethodCall (const ObjCMessageExpr * Msg, ProgramStateRef St, const LocationContext * LCtx, CFGBlock::ConstCFGElementRef ElemRef) inline protected
Definition at line 1249 of file CallEvent.h.
References clang::ento::CallEvent::Data.
Referenced by cloneTo().
ObjCMethodCall() [2/2]
clang::ento::ObjCMethodCall::ObjCMethodCall (const ObjCMethodCall & Other) protected default
Member Function Documentation
argumentsMayEscape()
bool ObjCMethodCall::argumentsMayEscape () const override virtual
Returns true if any of the arguments are known to escape to long- term storage, even if this method will not modify them.
Reimplemented from clang::ento::CallEvent.
Definition at line 1374 of file CallEvent.cpp.
References clang::ento::CallEvent::argumentsMayEscape(), clang::Selector::getIdentifierInfoForSlot(), clang::Selector::getNumArgs(), getSelector(), isInstanceMessage(), clang::ento::CallEvent::isInSystemHeader(), and clang::IdentifierInfo::isStr().
canBeOverridenInSubclass()
bool ObjCMethodCall::canBeOverridenInSubclass (ObjCInterfaceDecl * IDecl, Selector Sel) const protected virtual
Check if the selector may have multiple definitions (may have overrides).
Definition at line 1131 of file CallEvent.cpp.
References clang::ObjCMethodDecl::getClassInterface(), clang::ObjCInterfaceDecl::getEndOfDefinitionLoc(), clang::Decl::getLocation(), getMessageKind(), clang::ento::CallEvent::getState(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ento::AnalysisManager::isInCodeFile(), clang::ObjCMethodDecl::isOverriding(), clang::SourceLocation::isValid(), clang::ObjCInterfaceDecl::lookupMethod(), and clang::ento::OCM_PropertyAccess.
Referenced by getRuntimeDefinition().
classof()
static bool clang::ento::ObjCMethodCall::classof (const CallEvent * CA) inline static
Definition at line 1344 of file CallEvent.h.
References clang::ento::CE_ObjCMessage, and clang::ento::CallEvent::getKind().
cloneTo()
void clang::ento::ObjCMethodCall::cloneTo (void * Dest) const inline override protected virtual
Copies this CallEvent, with vtable intact, into a new block of memory.
Implements clang::ento::CallEvent.
Definition at line 1258 of file CallEvent.h.
References ObjCMethodCall().
getAccessedProperty()
const ObjCPropertyDecl * ObjCMethodCall::getAccessedProperty () const
Definition at line 1109 of file CallEvent.cpp.
References clang::ObjCMethodDecl::findPropertyDecl(), getDecl(), getMessageKind(), getSyntacticFromForPseudoObjectExpr(), clang::ObjCMethodDecl::isPropertyAccessor(), and clang::ento::OCM_PropertyAccess.
Referenced by getExtraInvalidatedValues().
getArgExpr()
const Expr* clang::ento::ObjCMethodCall::getArgExpr (unsigned Index) const inline override virtual
Returns the expression associated with a given argument.
May be null if this expression does not appear in the source.
Reimplemented from clang::ento::CallEvent.
Definition at line 1279 of file CallEvent.h.
getDecl()
const ObjCMethodDecl* clang::ento::ObjCMethodCall::getDecl () const inline override virtual
Returns the declaration of the function or method that will be called.
May be null.
Reimplemented from clang::ento::CallEvent.
Definition at line 1273 of file CallEvent.h.
References clang::ObjCMessageExpr::getMethodDecl(), and getOriginExpr().
Referenced by getAccessedProperty(), and parameters().
getExtraInvalidatedValues()
void ObjCMethodCall::getExtraInvalidatedValues (ValueList & Values, RegionAndSymbolInvalidationTraits * ETraits) const override protected virtual
Used to specify non-argument regions that will be invalidated as a result of this call.
Reimplemented from clang::ento::CallEvent.
Definition at line 979 of file CallEvent.cpp.
References getAccessedProperty(), clang::ento::SVal::getAsRegion(), getReceiverSVal(), clang::ento::CallEvent::getState(), clang::ento::RegionAndSymbolInvalidationTraits::setTrait(), clang::ento::RegionAndSymbolInvalidationTraits::TK_DoNotInvalidateSuperRegion, and clang::ento::RegionAndSymbolInvalidationTraits::TK_SuppressEscape.
getInitialStackFrameContents()
void ObjCMethodCall::getInitialStackFrameContents (const StackFrameContext * CalleeCtx, BindingsTy & Bindings) const override virtual
Populates the given SmallVector with the bindings in the callee's stack frame at the start of this call.
Implements clang::ento::CallEvent.
Definition at line 1385 of file CallEvent.cpp.
References addParameterValuesToBindings(), clang::LocationContext::getAnalysisDeclContext(), clang::LocationContext::getDecl(), getReceiverSVal(), clang::ento::SValBuilder::getRegionManager(), clang::AnalysisDeclContext::getSelfDecl(), clang::ento::CallEvent::getState(), clang::ento::MemRegionManager::getVarRegion(), clang::ento::SVal::isUnknown(), and clang::ento::SValBuilder::makeLoc().
getKind()
Kind clang::ento::ObjCMethodCall::getKind () const inline override virtual
Returns the kind of call this is.
Implements clang::ento::CallEvent.
Definition at line 1341 of file CallEvent.h.
References clang::ento::CE_ObjCMessage.
getKindAsString()
StringRef clang::ento::ObjCMethodCall::getKindAsString () const inline override virtual
Implements clang::ento::CallEvent.
Definition at line 1342 of file CallEvent.h.
getMessageKind()
ObjCMessageKind ObjCMethodCall::getMessageKind () const
Returns how the message was written in the source (property access, subscript, or explicit message send).
Definition at line 1065 of file CallEvent.cpp.
References clang::ento::CallEvent::Data, clang::ento::CallEvent::getLocationContext(), and clang::LocationContext::getParentMap().
Referenced by canBeOverridenInSubclass(), describeUninitializedArgumentInCall(), getAccessedProperty(), getSourceRange(), and isSetter().
getMethodFamily()
ObjCMethodFamily clang::ento::ObjCMethodCall::getMethodFamily () const inline
Definition at line 1287 of file CallEvent.h.
References clang::ObjCMessageExpr::getMethodFamily(), and getOriginExpr().
getNumArgs()
unsigned clang::ento::ObjCMethodCall::getNumArgs () const inline override virtual
Returns the number of arguments (explicit and implicit).
Note that this may be greater than the number of parameters in the callee's declaration, and that it may include arguments not written in the source.
Implements clang::ento::CallEvent.
Definition at line 1277 of file CallEvent.h.
References clang::ObjCMessageExpr::getNumArgs(), and getOriginExpr().
Referenced by isSetter().
getOriginExpr()
const ObjCMessageExpr* clang::ento::ObjCMethodCall::getOriginExpr () const inline override virtual
Returns the expression whose value will be the result of this call.
May be null.
Reimplemented from clang::ento::CallEvent.
Definition at line 1269 of file CallEvent.h.
References clang::ento::CallEvent::getOriginExpr().
Referenced by getDecl(), getMethodFamily(), getNumArgs(), getReceiverInterface(), getReceiverSVal(), getRuntimeDefinition(), getSelector(), getSourceRange(), isInstanceMessage(), and isReceiverSelfOrSuper().
getReceiverInterface()
const ObjCInterfaceDecl* clang::ento::ObjCMethodCall::getReceiverInterface () const inline
Get the interface for the receiver.
This works whether this is an instance message or a class message. However, it currently just uses the static type of the receiver.
Definition at line 1302 of file CallEvent.h.
References getOriginExpr(), and clang::ObjCMessageExpr::getReceiverInterface().
Referenced by GetReceiverInterfaceName().
getReceiverSVal()
SVal ObjCMethodCall::getReceiverSVal () const
Returns the value of the receiver at the time of this call.
Definition at line 1004 of file CallEvent.cpp.
References clang::ento::CallEvent::getLocationContext(), getOriginExpr(), clang::ento::CallEvent::getState(), clang::ento::CallEvent::getSVal(), isInstanceMessage(), clang::ento::SVal::isValid(), and clang::ObjCMessageExpr::SuperInstance.
Referenced by getExtraInvalidatedValues(), getInitialStackFrameContents(), getReceiverNullability(), and getRuntimeDefinition().
getRuntimeDefinition()
RuntimeDefinition ObjCMethodCall::getRuntimeDefinition () const override virtual
Returns the definition of the function or method that will be called.
Implements clang::ento::CallEvent.
Definition at line 1271 of file CallEvent.cpp.
References clang::ento::DynamicTypeInfo::canBeASubClass(), canBeOverridenInSubclass(), findDefiningRedecl(), clang::ento::SVal::getAsRegion(), clang::ObjCMethodDecl::getCanonicalDecl(), clang::QualType::getCanonicalType(), clang::ento::getClassObjectDynamicTypeInfo(), clang::ento::getDynamicTypeInfo(), clang::ObjCObjectType::getInterface(), clang::ento::CallEvent::getLocationContext(), clang::ObjCMessageExpr::getMethodDecl(), getOriginExpr(), clang::ObjCMessageExpr::getReceiverInterface(), getReceiverSVal(), clang::ObjCMessageExpr::getSelector(), clang::ento::CallEvent::getState(), clang::ObjCMessageExpr::getSuperType(), clang::ento::DynamicTypeInfo::getType(), clang::ObjCMethodDecl::hasBody(), clang::ObjCMessageExpr::isInstanceMessage(), clang::QualType::isNull(), clang::ObjCObjectType::isObjCClass(), clang::ento::DynamicTypeInfo::isValid(), and lookupRuntimeDefinition().
getSelector()
Selector clang::ento::ObjCMethodCall::getSelector () const inline
Definition at line 1291 of file CallEvent.h.
References getOriginExpr(), and clang::ObjCMessageExpr::getSelector().
Referenced by argumentsMayEscape().
getSourceRange()
SourceRange ObjCMethodCall::getSourceRange () const override virtual
Returns a source range for the entire call, suitable for outputting in diagnostics.
Reimplemented from clang::ento::CallEvent.
Definition at line 1034 of file CallEvent.cpp.
References getMessageKind(), getOriginExpr(), clang::Stmt::getSourceRange(), clang::ento::OCM_Message, clang::ento::OCM_PropertyAccess, and clang::ento::OCM_Subscript.
isInstanceMessage()
bool clang::ento::ObjCMethodCall::isInstanceMessage () const inline
Definition at line 1283 of file CallEvent.h.
References getOriginExpr(), and clang::ObjCMessageExpr::isInstanceMessage().
Referenced by argumentsMayEscape(), getReceiverSVal(), and isReceiverSelfOrSuper().
isReceiverSelfOrSuper()
bool ObjCMethodCall::isReceiverSelfOrSuper () const
Checks if the receiver refers to 'self' or 'super'.
Definition at line 1020 of file CallEvent.cpp.
References clang::ento::CallEvent::getLocationContext(), getOriginExpr(), clang::ento::CallEvent::getState(), clang::ento::CallEvent::getSVal(), isInstanceMessage(), clang::ObjCMessageExpr::SuperClass, and clang::ObjCMessageExpr::SuperInstance.
Referenced by getReceiverNullability().
isSetter()
bool clang::ento::ObjCMethodCall::isSetter () const inline
Returns true if this property access or subscript is a setter (has the form of an assignment).
Definition at line 1315 of file CallEvent.h.
References getMessageKind(), getNumArgs(), clang::ento::OCM_Message, clang::ento::OCM_PropertyAccess, and clang::ento::OCM_Subscript.
Referenced by describeUninitializedArgumentInCall().
parameters()
ArrayRef< ParmVarDecl * > ObjCMethodCall::parameters () const override virtual
Return call's formal parameters.
Remember that the number of formal parameters may not match the number of arguments for all calls. However, the first parameter will always correspond with the argument value returned by getArgSVal(0).
Implements clang::ento::CallEvent.
Definition at line 972 of file CallEvent.cpp.
References getDecl(), and clang::ObjCMethodDecl::parameters().
Friends And Related Function Documentation
CallEventManager
friend class CallEventManager friend
Definition at line 1244 of file CallEvent.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h
lib/StaticAnalyzer/Core/CallEvent.cpp