clang: clang::ento::ModelConsumer Class Reference
clang::ento::ModelConsumer Class Reference
ASTConsumer to consume model files' AST.
#include "clang/StaticAnalyzer/Frontend/ModelConsumer.h"
Public Member Functions
ModelConsumer (llvm::StringMap< Stmt * > &Bodies)
bool HandleTopLevelDecl (DeclGroupRef D) override
HandleTopLevelDecl - Handle the specified top-level declaration.
Public Member Functions inherited from clang::ASTConsumer
ASTConsumer ()
virtual ~ASTConsumer ()
virtual void Initialize (ASTContext &Context)
Initialize - This is called to initialize the consumer, providing the ASTContext.
virtual void HandleInlineFunctionDefinition (FunctionDecl *D)
This callback is invoked each time an inline (method or friend) function definition in a class is completed.
virtual void HandleInterestingDecl (DeclGroupRef D)
HandleInterestingDecl - Handle the specified interesting declaration.
virtual void HandleTranslationUnit (ASTContext &Ctx)
HandleTranslationUnit - This method is called when the ASTs for entire translation unit have been parsed.
virtual void HandleTagDeclDefinition (TagDecl *D)
HandleTagDeclDefinition - This callback is invoked each time a TagDecl (e.g.
virtual void HandleTagDeclRequiredDefinition (const TagDecl *D)
This callback is invoked the first time each TagDecl is required to be complete.
virtual void HandleCXXImplicitFunctionInstantiation (FunctionDecl *D)
Invoked when a function is implicitly instantiated.
virtual void HandleTopLevelDeclInObjCContainer (DeclGroupRef D)
Handle the specified top-level declaration that occurred inside and ObjC container.
virtual void HandleImplicitImportDecl (ImportDecl *D)
Handle an ImportDecl that was implicitly created due to an inclusion directive.
virtual void CompleteTentativeDefinition (VarDecl *D)
CompleteTentativeDefinition - Callback invoked at the end of a translation unit to notify the consumer that the given tentative definition should be completed.
virtual void CompleteExternalDeclaration (VarDecl *D)
CompleteExternalDeclaration - Callback invoked at the end of a translation unit to notify the consumer that the given external declaration should be completed.
virtual void AssignInheritanceModel (CXXRecordDecl *RD)
Callback invoked when an MSInheritanceAttr has been attached to a CXXRecordDecl.
virtual void HandleCXXStaticMemberVarInstantiation (VarDecl *D)
HandleCXXStaticMemberVarInstantiation - Tell the consumer that this.
virtual void HandleVTable (CXXRecordDecl *RD)
Callback involved at the end of a translation unit to notify the consumer that a vtable for the given C++ class is required.
virtual ASTMutationListener * GetASTMutationListener ()
If the consumer is interested in entities getting modified after their initial creation, it should return a pointer to an ASTMutationListener here.
virtual ASTDeserializationListener * GetASTDeserializationListener ()
If the consumer is interested in entities being deserialized from AST files, it should return a pointer to a ASTDeserializationListener here.
virtual void PrintStats ()
PrintStats - If desired, print any statistics.
virtual bool shouldSkipFunctionBody (Decl *D)
This callback is called for each function if the Parser was initialized with SkipFunctionBodies set to true.
Detailed Description
ASTConsumer to consume model files' AST.
This consumer collects the bodies of function definitions into a StringMap from a model file.
Definition at line 31 of file ModelConsumer.h.
Constructor & Destructor Documentation
ModelConsumer()
ModelConsumer::ModelConsumer (llvm::StringMap< Stmt * > & Bodies)
Definition at line 28 of file ModelConsumer.cpp.
Member Function Documentation
HandleTopLevelDecl()
bool ModelConsumer::HandleTopLevelDecl (DeclGroupRef D) override virtual
HandleTopLevelDecl - Handle the specified top-level declaration.
This is called by the parser to process every top-level Decl*.
Returns
true to continue parsing, or false to abort parsing.
Reimplemented from clang::ASTConsumer.
Definition at line 31 of file ModelConsumer.cpp.
References clang::DeclGroupRef::begin(), clang::DeclGroupRef::end(), clang::FunctionDecl::getBody(), clang::NamedDecl::getName(), and clang::FunctionDecl::hasBody().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Frontend/ModelConsumer.h
lib/StaticAnalyzer/Frontend/ModelConsumer.cpp