clang: clang::ento::BugReporter Class Reference
clang::ento::BugReporter Class Reference
BugReporter is a utility class for generating PathDiagnostics for analysis.
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
Public Types
using EQClasses_iterator = llvm::FoldingSet< BugReportEquivClass >::iterator
Iterator over the set of BugReports tracked by the BugReporter.
Public Member Functions
BugReporter (BugReporterData &d)
virtual ~BugReporter ()
void FlushReports ()
Generate and flush diagnostics for all bug reports.
ArrayRef< PathDiagnosticConsumer * > getPathDiagnosticConsumers ()
llvm::iterator_range< EQClasses_iterator > equivalenceClasses ()
ASTContext & getContext ()
const SourceManager & getSourceManager ()
const AnalyzerOptions & getAnalyzerOptions ()
Preprocessor & getPreprocessor ()
const Decl * getAnalysisEntryPoint () const
Get the top-level entry point for the issue to be reported.
void setAnalysisEntryPoint (const Decl *EntryPoint)
virtual void emitReport (std::unique_ptr< BugReport > R)
Add the given report to the set of reports tracked by BugReporter.
void EmitBasicReport (const Decl *DeclWithIssue, const CheckerBase *Checker, StringRef BugName, StringRef BugCategory, StringRef BugStr, PathDiagnosticLocation Loc, ArrayRef< SourceRange > Ranges=std::nullopt, ArrayRef< FixItHint > Fixits=std::nullopt)
void EmitBasicReport (const Decl *DeclWithIssue, CheckerNameRef CheckerName, StringRef BugName, StringRef BugCategory, StringRef BugStr, PathDiagnosticLocation Loc, ArrayRef< SourceRange > Ranges=std::nullopt, ArrayRef< FixItHint > Fixits=std::nullopt)
Protected Member Functions
virtual std::unique_ptr< DiagnosticForConsumerMapTy > generateDiagnosticForConsumerMap (BugReport *exampleReport, ArrayRef< PathDiagnosticConsumer * > consumers, ArrayRef< BugReport * > bugReports)
Generate the diagnostics for the given bug report.
Detailed Description
BugReporter is a utility class for generating PathDiagnostics for analysis.
It collects the BugReports and BugTypes and knows how to generate and flush the corresponding diagnostics.
The base class is used for generating path-insensitive
Definition at line 585 of file BugReporter.h.
Member Typedef Documentation
EQClasses_iterator
using clang::ento::BugReporter::EQClasses_iterator = llvm::FoldingSet<BugReportEquivClass>::iterator
Iterator over the set of BugReports tracked by the BugReporter.
Definition at line 616 of file BugReporter.h.
Constructor & Destructor Documentation
BugReporter()
BugReporter::BugReporter (BugReporterData & d)
Definition at line 2475 of file BugReporter.cpp.
~BugReporter()
BugReporter::~BugReporter () virtual
Definition at line 2478 of file BugReporter.cpp.
Member Function Documentation
EmitBasicReport() [1/2]
void BugReporter::EmitBasicReport (const Decl * DeclWithIssue, CheckerNameRef CheckerName, StringRef BugName, StringRef BugCategory, StringRef BugStr, PathDiagnosticLocation Loc, ArrayRef< SourceRange > Ranges = std::nullopt, ArrayRef< FixItHint > Fixits = std::nullopt)
Definition at line 3348 of file BugReporter.cpp.
References clang::ento::BugReport::addFixItHint(), clang::ento::BugReport::addRange(), emitReport(), and clang::transformer::name().
EmitBasicReport() [2/2]
void BugReporter::EmitBasicReport (const Decl * DeclWithIssue, const CheckerBase * Checker, StringRef BugName, StringRef BugCategory, StringRef BugStr, PathDiagnosticLocation Loc, ArrayRef< SourceRange > Ranges = std::nullopt, ArrayRef< FixItHint > Fixits = std::nullopt)
Definition at line 3338 of file BugReporter.cpp.
Referenced by checkObjCUnusedIvar(), CompareReturnTypes(), and emitDiagnostics().
emitReport()
void BugReporter::emitReport (std::unique_ptr< BugReport > R) virtual
Add the given report to the set of reports tracked by BugReporter.
The reports are usually generated by the checkers. Further, they are folded based on the profile value, which is done to coalesce similar reports.
Reimplemented in clang::ento::PathSensitiveBugReporter.
Definition at line 2907 of file BugReporter.cpp.
References clang::interp::EQ(), ID, and clang::ento::BugSuppression::isSuppressed().
Referenced by EmitBasicReport(), clang::ento::CheckerContext::emitReport(), clang::ento::PathSensitiveBugReporter::emitReport(), clang::ento::mpi::MPIBugReporter::reportDoubleNonblocking(), clang::ento::mpi::MPIBugReporter::reportMissingWait(), and clang::ento::mpi::MPIBugReporter::reportUnmatchedWait().
equivalenceClasses()
llvm::iterator_range<EQClasses_iterator> clang::ento::BugReporter::equivalenceClasses () inline
Definition at line 617 of file BugReporter.h.
Referenced by clang::ento::ExprEngine::DumpGraph(), and llvm::DOTGraphTraits< ExplodedGraph * >::nodeHasBugReport().
FlushReports()
void BugReporter::FlushReports ()
Generate and flush diagnostics for all bug reports.
Definition at line 2488 of file BugReporter.cpp.
References clang::interp::EQ().
generateDiagnosticForConsumerMap()
std::unique_ptr< DiagnosticForConsumerMapTy > BugReporter::generateDiagnosticForConsumerMap (BugReport * exampleReport, ArrayRef< PathDiagnosticConsumer * > consumers, ArrayRef< BugReport * > bugReports) protected virtual
Generate the diagnostics for the given bug report.
Definition at line 3223 of file BugReporter.cpp.
References generateDiagnosticForBasicReport().
getAnalysisEntryPoint()
const Decl* clang::ento::BugReporter::getAnalysisEntryPoint () const inline
Get the top-level entry point for the issue to be reported.
Definition at line 630 of file BugReporter.h.
getAnalyzerOptions()
const AnalyzerOptions& clang::ento::BugReporter::getAnalyzerOptions () inline
Definition at line 625 of file BugReporter.h.
References clang::ento::BugReporterData::getAnalyzerOptions().
Referenced by clang::ento::BugReporterContext::getAnalyzerOptions().
getContext()
ASTContext& clang::ento::BugReporter::getContext () inline
Definition at line 621 of file BugReporter.h.
References clang::ento::BugReporterData::getASTContext().
Referenced by CheckObjCInstMethSignature(), and clang::ento::BugReporterContext::getASTContext().
getPathDiagnosticConsumers()
ArrayRef<PathDiagnosticConsumer*> clang::ento::BugReporter::getPathDiagnosticConsumers () inline
Definition at line 611 of file BugReporter.h.
References clang::ento::BugReporterData::getPathDiagnosticConsumers().
getPreprocessor()
Preprocessor& clang::ento::BugReporter::getPreprocessor () inline
Definition at line 627 of file BugReporter.h.
References clang::ento::BugReporterData::getPreprocessor().
Referenced by clang::ento::CheckerContext::getPreprocessor().
getSourceManager()
const SourceManager& clang::ento::BugReporter::getSourceManager () inline
Definition at line 623 of file BugReporter.h.
References clang::ento::BugReporterData::getSourceManager().
Referenced by checkObjCUnusedIvar(), CompareReturnTypes(), emitDiagnostics(), clang::ento::CheckerContext::getSourceManager(), and clang::ento::BugReporterContext::getSourceManager().
setAnalysisEntryPoint()
void clang::ento::BugReporter::setAnalysisEntryPoint (const Decl * EntryPoint) inline
Definition at line 632 of file BugReporter.h.
Referenced by clang::ento::ExprEngine::ExecuteWorkList().
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h
lib/StaticAnalyzer/Core/BugReporter.cpp