clang: clang::dataflow::StorageLocation Class Reference
clang::dataflow::StorageLocation Class Reference
Base class for elements of the local variable store and of the heap.
#include "clang/Analysis/FlowSensitive/StorageLocation.h"
Public Types
enum class Kind { Scalar , Record }
Public Member Functions
StorageLocation (Kind LocKind, QualType Type)
StorageLocation (const StorageLocation &)=delete
StorageLocation & operator= (const StorageLocation &)=delete
virtual ~StorageLocation ()=default
Kind getKind () const
QualType getType () const
Detailed Description
Base class for elements of the local variable store and of the heap.
Each storage location holds a value. The mapping from storage locations to values is stored in the environment.
Definition at line 32 of file StorageLocation.h.
Member Enumeration Documentation
Kind
enum clang::dataflow::StorageLocation::Kind strong
Enumerator
Scalar
Record
Definition at line 34 of file StorageLocation.h.
Constructor & Destructor Documentation
StorageLocation() [1/2]
clang::dataflow::StorageLocation::StorageLocation (Kind LocKind, QualType Type) inline
Definition at line 39 of file StorageLocation.h.
References clang::Type::isReferenceType().
StorageLocation() [2/2]
clang::dataflow::StorageLocation::StorageLocation (const StorageLocation &) delete
~StorageLocation()
virtual clang::dataflow::StorageLocation::~StorageLocation () virtual default
Member Function Documentation
getKind()
Kind clang::dataflow::StorageLocation::getKind () const inline
Definition at line 51 of file StorageLocation.h.
Referenced by clang::dataflow::ScalarStorageLocation::classof(), and clang::dataflow::RecordStorageLocation::classof().
getType()
QualType clang::dataflow::StorageLocation::getType () const inline
Definition at line 53 of file StorageLocation.h.
Referenced by clang::dataflow::copyRecord(), clang::dataflow::Environment::initializeFieldsWithValues(), and clang::dataflow::recordsEqual().
operator=()
StorageLocation& clang::dataflow::StorageLocation::operator= (const StorageLocation &) delete
The documentation for this class was generated from the following file:
include/clang/Analysis/FlowSensitive/StorageLocation.h