clang: clang::driver::tools::OffloadBundler Class Reference
clang::driver::tools::OffloadBundler Class Reference final
Offload bundler tool.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/Clang.h"
Public Member Functions
OffloadBundler (const ToolChain &TC)
bool hasIntegratedCPP () const override
void ConstructJob (Compilation &C, const JobAction &JA, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
void ConstructJobMultipleOutputs (Compilation &C, const JobAction &JA, const InputInfoList &Outputs, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const char *LinkingOutput) const override
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
Public Member Functions inherited from clang::driver::Tool
Tool (const char *Name, const char *ShortName, const ToolChain &TC)
virtual ~Tool ()
const char * getName () const
const char * getShortName () const
const ToolChain & getToolChain () const
virtual bool hasIntegratedAssembler () const
virtual bool hasIntegratedBackend () const
virtual bool canEmitIR () const
virtual bool isLinkJob () const
virtual bool isDsymutilJob () const
virtual bool hasGoodDiagnostics () const
Does this tool have "good" standardized diagnostics, or should the driver add an additional "command failed" diagnostic on failures.
Detailed Description
Offload bundler tool.
Definition at line 150 of file Clang.h.
Constructor & Destructor Documentation
OffloadBundler()
clang::driver::tools::OffloadBundler::OffloadBundler (const ToolChain & TC) inline
Definition at line 152 of file Clang.h.
Member Function Documentation
ConstructJob()
void OffloadBundler::ConstructJob (Compilation & C, const JobAction & JA, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
ConstructJob - Construct jobs to perform the action JA, writing to Output and with Inputs, and add the jobs to C.
Parameters
TCArgs - The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput - If this output will eventually feed the linker, then this is the final output name of the linked image.
Implements clang::driver::Tool.
Definition at line 9546 of file Clang.cpp.
References clang::driver::tools::addOffloadCompressArgs(), clang::driver::ToolChain::getArchName(), clang::driver::tools::Clang::getBaseInputName(), clang::driver::InputInfo::getFilename(), clang::driver::ToolChain::getInputFilename(), clang::driver::Action::getInputs(), clang::driver::Action::getOffloadingArch(), clang::driver::Action::getOffloadingDeviceKind(), clang::driver::Action::GetOffloadKindName(), clang::driver::Tool::getShortName(), clang::driver::Tool::getToolChain(), clang::driver::ToolChain::getTriple(), clang::driver::InputInfo::getType(), clang::driver::types::getTypeName(), clang::driver::types::getTypeTempSuffix(), clang::driver::ResponseFileSupport::None(), clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_HIP, clang::driver::Action::OFK_Host, clang::driver::Action::OFK_OpenMP, clang::driver::Action::OFK_SYCL, clang::driver::tools::SYCL::shouldDoPerObjectFileLinking(), and clang::T.
ConstructJobMultipleOutputs()
void OffloadBundler::ConstructJobMultipleOutputs (Compilation & C, const JobAction & JA, const InputInfoList & Outputs, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const char * LinkingOutput) const override virtual
Construct jobs to perform the action JA, writing to the Outputs and with Inputs, and add the jobs to C.
The default implementation assumes a single output and is expected to be overloaded for the tools that support multiple inputs.
Parameters
TCArgs The argument list for this toolchain, with any tool chain specific translations applied.
LinkingOutput If this output will eventually feed the linker, then this is the final output name of the linked image.
Reimplemented from clang::driver::Tool.
Definition at line 9721 of file Clang.cpp.
References Cmd, clang::driver::tools::SYCL::constructLLVMForeachCommand(), clang::driver::InputInfo::getFilename(), clang::driver::Action::GetOffloadKindName(), clang::driver::Tool::getShortName(), clang::driver::Tool::getToolChain(), clang::driver::ToolChain::getTriple(), clang::driver::Action::getType(), clang::driver::InputInfo::getType(), clang::driver::types::getTypeName(), clang::driver::types::getTypeTempSuffix(), clang::driver::types::isFPGA(), clang::driver::ResponseFileSupport::None(), clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_HIP, clang::driver::Action::OFK_Host, clang::driver::Action::OFK_OpenMP, clang::driver::Action::OFK_SYCL, and clang::TypeName.
hasIntegratedCPP()
bool clang::driver::tools::OffloadBundler::hasIntegratedCPP () const inline override virtual
Implements clang::driver::Tool.
Definition at line 155 of file Clang.h.
The documentation for this class was generated from the following files:
lib/Driver/ToolChains/Clang.h
lib/Driver/ToolChains/Clang.cpp