clang: clang::dataflow::TypeErasedDataflowAnalysis Class Reference
clang::dataflow::TypeErasedDataflowAnalysis Class Reference abstract
Type-erased base class for dataflow analyses built on a single lattice type.
#include "clang/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.h"
Public Member Functions
TypeErasedDataflowAnalysis ()
TypeErasedDataflowAnalysis (bool ApplyBuiltinTransfer)
virtual ~TypeErasedDataflowAnalysis ()
virtual ASTContext & getASTContext ()=0
Returns the ASTContext that is used by the analysis.
virtual TypeErasedLattice typeErasedInitialElement ()=0
Returns a type-erased lattice element that models the initial state of a basic block.
virtual LatticeJoinEffect joinTypeErased (TypeErasedLattice &, const TypeErasedLattice &)=0
Joins two type-erased lattice elements by computing their least upper bound.
virtual bool isEqualTypeErased (const TypeErasedLattice &, const TypeErasedLattice &)=0
Returns true if and only if the two given type-erased lattice elements are equal.
virtual void transferTypeErased (const Stmt *, TypeErasedLattice &, Environment &)=0
Applies the analysis transfer function for a given statement and type-erased lattice element.
bool applyBuiltinTransfer () const
Determines whether to apply the built-in transfer functions, which model the heap and stack in the Environment.
Public Member Functions inherited from clang::dataflow::Environment::ValueModel
virtual ~ValueModel ()=default
virtual bool compareEquivalent (QualType Type, const Value &Val1, const Environment &Env1, const Value &Val2, const Environment &Env2)
Returns true if and only if Val1 is equivalent to Val2.
virtual bool merge (QualType Type, const Value &Val1, const Environment &Env1, const Value &Val2, const Environment &Env2, Value &MergedVal, Environment &MergedEnv)
Modifies MergedVal to approximate both Val1 and Val2.
Detailed Description
Type-erased base class for dataflow analyses built on a single lattice type.
Definition at line 44 of file TypeErasedDataflowAnalysis.h.
Constructor & Destructor Documentation
TypeErasedDataflowAnalysis() [1/2]
clang::dataflow::TypeErasedDataflowAnalysis::TypeErasedDataflowAnalysis () inline
Definition at line 52 of file TypeErasedDataflowAnalysis.h.
TypeErasedDataflowAnalysis() [2/2]
clang::dataflow::TypeErasedDataflowAnalysis::TypeErasedDataflowAnalysis (bool ApplyBuiltinTransfer) inline
Definition at line 53 of file TypeErasedDataflowAnalysis.h.
~TypeErasedDataflowAnalysis()
virtual clang::dataflow::TypeErasedDataflowAnalysis::~TypeErasedDataflowAnalysis () inline virtual
Definition at line 56 of file TypeErasedDataflowAnalysis.h.
Member Function Documentation
applyBuiltinTransfer()
bool clang::dataflow::TypeErasedDataflowAnalysis::applyBuiltinTransfer () const inline
Determines whether to apply the built-in transfer functions, which model the heap and stack in the Environment.
Definition at line 83 of file TypeErasedDataflowAnalysis.h.
Referenced by clang::dataflow::computeBlockInputState(), and clang::dataflow::transferBlock().
getASTContext()
virtual ASTContext& clang::dataflow::TypeErasedDataflowAnalysis::getASTContext () pure virtual
Returns the ASTContext that is used by the analysis.
Implemented in clang::dataflow::DataflowAnalysis< Derived, LatticeT >, and clang::dataflow::DataflowAnalysis< UncheckedOptionalAccessModel, SourceLocationsLattice >.
isEqualTypeErased()
virtual bool clang::dataflow::TypeErasedDataflowAnalysis::isEqualTypeErased (const TypeErasedLattice & , const TypeErasedLattice &) pure virtual
Returns true if and only if the two given type-erased lattice elements are equal.
Implemented in clang::dataflow::DataflowAnalysis< Derived, LatticeT >, and clang::dataflow::DataflowAnalysis< UncheckedOptionalAccessModel, SourceLocationsLattice >.
Referenced by clang::dataflow::runTypeErasedDataflowAnalysis().
joinTypeErased()
virtual LatticeJoinEffect clang::dataflow::TypeErasedDataflowAnalysis::joinTypeErased (TypeErasedLattice & , const TypeErasedLattice &) pure virtual
Joins two type-erased lattice elements by computing their least upper bound.
Places the join result in the left element and returns an effect indicating whether any changes were made to it.
Implemented in clang::dataflow::DataflowAnalysis< Derived, LatticeT >, and clang::dataflow::DataflowAnalysis< UncheckedOptionalAccessModel, SourceLocationsLattice >.
Referenced by clang::dataflow::computeBlockInputState().
transferTypeErased()
virtual void clang::dataflow::TypeErasedDataflowAnalysis::transferTypeErased (const Stmt * , TypeErasedLattice & , Environment &) pure virtual
Applies the analysis transfer function for a given statement and type-erased lattice element.
Implemented in clang::dataflow::DataflowAnalysis< Derived, LatticeT >, and clang::dataflow::DataflowAnalysis< UncheckedOptionalAccessModel, SourceLocationsLattice >.
typeErasedInitialElement()
virtual TypeErasedLattice clang::dataflow::TypeErasedDataflowAnalysis::typeErasedInitialElement () pure virtual
Returns a type-erased lattice element that models the initial state of a basic block.
Implemented in clang::dataflow::DataflowAnalysis< Derived, LatticeT >, and clang::dataflow::DataflowAnalysis< UncheckedOptionalAccessModel, SourceLocationsLattice >.
Referenced by clang::dataflow::computeBlockInputState(), and clang::dataflow::runTypeErasedDataflowAnalysis().
The documentation for this class was generated from the following file:
include/clang/Analysis/FlowSensitive/TypeErasedDataflowAnalysis.h