clang: clang::OpenACCClauseWithExprs Class Reference
clang::OpenACCClauseWithExprs Class Reference
Represents a clause that has one or more expressions associated with it.
#include "clang/AST/OpenACCClause.h"
Public Member Functions
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClauseWithParams
SourceLocation getLParenLoc () const
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::OpenACCClause
OpenACCClauseKind getClauseKind () const
SourceLocation getBeginLoc () const
SourceLocation getEndLoc () const
child_range children ()
const_child_range children () const
virtual ~OpenACCClause ()=default
Static Public Member Functions
static bool classof (const OpenACCClause *C)
Static Public Member Functions inherited from clang::OpenACCClauseWithParams
static bool classof (const OpenACCClause *C)
Static Public Member Functions inherited from clang::OpenACCClause
static bool classof (const OpenACCClause *)
Protected Member Functions
OpenACCClauseWithExprs (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
void setExprs (MutableArrayRef< Expr * > NewExprs)
Used only for initialization, the leaf class can initialize this to trailing storage.
llvm::ArrayRef< Expr * > getExprs () const
Gets the entire list of expressions, but leave it to the individual clauses to expose this how they'd like.
Protected Member Functions inherited from clang::OpenACCClauseWithParams
OpenACCClauseWithParams (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OpenACCClause
OpenACCClause (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation EndLoc)
Additional Inherited Members
Public Types inherited from clang::OpenACCClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Detailed Description
Represents a clause that has one or more expressions associated with it.
Definition at line 378 of file OpenACCClause.h.
Constructor & Destructor Documentation
OpenACCClauseWithExprs()
clang::OpenACCClauseWithExprs::OpenACCClauseWithExprs (OpenACCClauseKind K, SourceLocation BeginLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline protected
Definition at line 382 of file OpenACCClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OpenACCClauseWithExprs::children () inline
Definition at line 399 of file OpenACCClause.h.
Referenced by children().
children() [2/2]
const_child_range clang::OpenACCClauseWithExprs::children () const inline
Definition at line 404 of file OpenACCClause.h.
References children().
classof()
bool OpenACCClauseWithExprs::classof (const OpenACCClause * C) static
Definition at line 25 of file OpenACCClause.cpp.
References clang::OpenACCWaitClause::classof(), clang::OpenACCNumGangsClause::classof(), clang::OpenACCClauseWithSingleIntExpr::classof(), and clang::OpenACCClauseWithVarList::classof().
Referenced by clang::OpenACCClauseWithParams::classof().
getExprs()
llvm::ArrayRef<Expr *> clang::OpenACCClauseWithExprs::getExprs () const inline protected
Gets the entire list of expressions, but leave it to the individual clauses to expose this how they'd like.
Definition at line 395 of file OpenACCClause.h.
Referenced by clang::OpenACCWaitClause::getDevNumExpr(), clang::OpenACCClauseWithSingleIntExpr::getIntExpr(), clang::OpenACCNumGangsClause::getIntExprs(), clang::OpenACCWaitClause::getQueueIdExprs(), clang::OpenACCClauseWithVarList::getVarList(), clang::OpenACCWaitClause::hasDevNumExpr(), and clang::OpenACCClauseWithSingleIntExpr::hasIntExpr().
setExprs()
void clang::OpenACCClauseWithExprs::setExprs (MutableArrayRef< Expr * > NewExprs) inline protected
Used only for initialization, the leaf class can initialize this to trailing storage.
Definition at line 388 of file OpenACCClause.h.
Referenced by clang::OpenACCClauseWithSingleIntExpr::OpenACCClauseWithSingleIntExpr().
The documentation for this class was generated from the following files:
include/clang/AST/OpenACCClause.h
lib/AST/OpenACCClause.cpp