clang: clang::SemaPPC Class Reference
clang::SemaPPC Class Reference
#include "clang/Sema/SemaPPC.h"
Public Member Functions
SemaPPC (Sema &S)
bool CheckPPCBuiltinFunctionCall (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
void checkAIXMemberAlignment (SourceLocation Loc, const Expr *Arg)
bool BuiltinPPCMMACall (CallExpr *TheCall, unsigned BuiltinID, const char *TypeDesc)
BuiltinPPCMMACall - Check the call to a PPC MMA builtin for validity.
bool CheckPPCMMAType (QualType Type, SourceLocation TypeLoc)
bool BuiltinVSX (CallExpr *TheCall)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 23 of file SemaPPC.h.
Constructor & Destructor Documentation
SemaPPC()
clang::SemaPPC::SemaPPC (Sema & S)
Definition at line 27 of file SemaPPC.cpp.
Member Function Documentation
BuiltinPPCMMACall()
bool clang::SemaPPC::BuiltinPPCMMACall (CallExpr * TheCall, unsigned BuiltinID, const char * TypeDesc)
BuiltinPPCMMACall - Check the call to a PPC MMA builtin for validity.
Emit an error and return true on failure; return false on success. TypeStr is a string containing the type descriptor of the value returned by the builtin and the descriptors of the expected type of the arguments.
Definition at line 331 of file SemaPPC.cpp.
BuiltinVSX()
bool clang::SemaPPC::BuiltinVSX (CallExpr * TheCall)
Definition at line 397 of file SemaPPC.cpp.
References clang::Sema::checkArgCount(), clang::SemaBase::Diag(), clang::CallExpr::getArg(), clang::SemaBase::getASTContext(), clang::CallExpr::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::CallExpr::getDirectCallee(), clang::Stmt::getEndLoc(), clang::Expr::getType(), clang::Type::isDependentType(), clang::Expr::isIntegerConstantExpr(), clang::Type::isVectorType(), clang::SemaBase::SemaRef, and clang::Expr::setType().
checkAIXMemberAlignment()
void clang::SemaPPC::checkAIXMemberAlignment (SourceLocation Loc, const Expr * Arg)
Definition at line 29 of file SemaPPC.cpp.
References clang::Type::castAs(), clang::SemaBase::Diag(), clang::RecordDecl::fields(), clang::SemaBase::getASTContext(), clang::RecordType::getDecl(), clang::CharUnits::getQuantity(), clang::Expr::getType(), clang::Expr::IgnoreParens(), Loc, and clang::ASTContext::toCharUnitsFromBits().
CheckPPCBuiltinFunctionCall()
bool clang::SemaPPC::CheckPPCBuiltinFunctionCall (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 92 of file SemaPPC.cpp.
CheckPPCMMAType()
bool clang::SemaPPC::CheckPPCMMAType (QualType Type, SourceLocation TypeLoc)
Definition at line 256 of file SemaPPC.cpp.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaPPC.h
lib/Sema/SemaPPC.cpp