clang: clang::driver::Driver Class Reference
clang::driver::Driver Class Reference
Driver - Encapsulate logic for constructing compilation processes from a set of gcc-driver-like command line arguments.
#include "clang/Driver/Driver.h"
Classes
struct CompilationDiagnosticReport
Contains the files in the compilation diagnostic report generated by generateCompilationDiagnostics.
Public Types
enum OpenMPRuntimeKind { OMPRT_Unknown , OMPRT_OMP , OMPRT_GOMP , OMPRT_IOMP5 }
typedef SmallVector< std::string, 4 > prefix_list
A prefix directory used to emulate a limited subset of GCC's '-Bprefix' functionality.
using InputTy = std::pair< types::ID, const llvm::opt::Arg * >
An input type and its arguments.
using InputList = SmallVector< InputTy, 16 >
A list of inputs and their types for the given arguments.
using CC1ToolFunc = llvm::function_ref< int(SmallVectorImpl< const char * > &ArgV)>
Pointer to the ExecuteCC1Tool function, if available.
Public Member Functions
DiagnosticBuilder Diag (unsigned DiagID) const
bool CCCIsCXX () const
Whether the driver should follow g++ like behavior.
bool CCCIsCPP () const
Whether the driver is just the preprocessor.
bool CCCIsCC () const
Whether the driver should follow gcc like behavior.
bool IsCLMode () const
Whether the driver should follow cl.exe like behavior.
bool IsFlangMode () const
Whether the driver should invoke flang for fortran inputs.
bool IsDXCMode () const
Whether the driver should follow dxc.exe like behavior.
phases::ID getFinalPhase (const llvm::opt::DerivedArgList &DAL, llvm::opt::Arg **FinalPhaseArg=nullptr) const
Driver (StringRef ClangExecutable, StringRef TargetTriple, DiagnosticsEngine &Diags, std::string Title="clang LLVM compiler", IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS=nullptr)
bool getOffloadStaticLibSeen () const
bool getUseNewOffloadingDriver () const
getUseNewOffloadingDriver - use the new offload driver for OpenMP.
void addFPGATempDepFile (const std::string &DepName, const std::string &FileName) const
addFPGATempDepFile - Add a file to be added to the bundling step of an FPGA object.
const std::string getFPGATempDepFile (const std::string &FileName) const
getFPGATempDepFile - Get a file to be added to the bundling step of an FPGA object.
bool isSYCLDefaultTripleImplied () const
isSYCLDefaultTripleImplied - The default SYCL triple (spir64) has been added or should be added given proper criteria.
void addIntegrationFiles (StringRef IntHeaderName, StringRef IntFooterName, StringRef FileName) const
addIntegrationFiles - Add the integration files that will be populated by the device compilation and used by the host compile.
StringRef getIntegrationHeader (StringRef FileName) const
getIntegrationHeader - Get the integration header file
StringRef getIntegrationFooter (StringRef FileName) const
getIntegrationFooter - Get the integration footer file
void createAppendedFooterInput (Action *&Input, Compilation &C, const llvm::opt::ArgList &Args) const
createAppendedFooterInput - Create new source file.
void addSYCLTargetMacroArg (const llvm::opt::ArgList &Args, StringRef Macro) const
addSYCLTargetMacroArg - Add the given macro to the vector of args to be added to the host compilation step.
llvm::ArrayRef< std::string > getSYCLTargetMacroArgs () const
getSYCLTargetMacroArgs - return the previously gathered macro target args.
void addSYCLUniqueID (StringRef UniqueID, StringRef FileName) const
setSYCLUniqueID - set the Unique ID that is used for all FE invocations when performing compilations for SYCL.
StringRef getSYCLUniqueID (StringRef FileName) const
getSYCLUniqueID - Get the Unique ID associated with the file.
void populateSYCLDeviceTraitsMacrosArgs (const llvm::opt::ArgList &Args, const llvm::SmallVector< llvm::Triple, 4 > &UniqueSYCLTriplesVec)
Reads device config file to find information about the SYCL targets in UniqueSYCLTriplesVec, and defines device traits macros accordingly.
llvm::opt::ArgStringList getDeviceTraitsMacrosArgs () const
Accessors
const std::string & getCCCGenericGCCName () const
Name to use when invoking gcc/g++.
llvm::ArrayRef< std::string > getConfigFiles () const
const llvm::opt::OptTable & getOpts () const
DiagnosticsEngine & getDiags () const
llvm::vfs::FileSystem & getVFS () const
bool getCheckInputsExist () const
void setCheckInputsExist (bool Value)
bool getProbePrecompiled () const
void setProbePrecompiled (bool Value)
const char * getPrependArg () const
void setPrependArg (const char *Value)
void setTargetAndMode (const ParsedClangName &TM)
const std::string & getTitle ()
void setTitle (std::string Value)
std::string getTargetTriple () const
const char * getClangProgramPath () const
Get the path to the main clang executable.
const char * getInstalledDir () const
Get the path to where the clang executable was installed.
bool isDumpDeviceCodeEnabled () const
bool isSaveTempsEnabled () const
bool isSaveTempsObj () const
bool embedBitcodeEnabled () const
bool embedBitcodeInObject () const
bool embedBitcodeMarkerOnly () const
bool offloadHostOnly () const
bool offloadDeviceOnly () const
void setFlangF128MathLibrary (std::string name)
StringRef getFlangF128MathLibrary () const
OpenMPRuntimeKind getOpenMPRuntime (const llvm::opt::ArgList &Args) const
Compute the desired OpenMP runtime from the flags provided.
Static Public Member Functions
static std::string GetResourcesPath (StringRef BinaryPath, StringRef CustomResourceDir="")
Takes the path to a binary that's either in bin/ or lib/ and returns the path to clang's resource directory.
static bool GetReleaseVersion (StringRef Str, unsigned &Major, unsigned &Minor, unsigned &Micro, bool &HadExtra)
GetReleaseVersion - Parse (([0-9]+)(.
static bool GetReleaseVersion (StringRef Str, MutableArrayRef< unsigned > Digits)
Parse digits from a string Str and fulfill Digits with the parsed numbers.
static bool getDefaultModuleCachePath (SmallVectorImpl< char > &Result)
Compute the default -fmodule-cache-path.
Public Attributes
std::string Name
The name the driver was invoked as.
std::string Dir
The path the driver executable was in, as invoked from the command line.
std::string ClangExecutable
The original path to the clang executable.
ParsedClangName ClangNameParts
Target and driver mode components extracted from clang executable name.
std::string ResourceDir
The path to the compiler resource directory.
std::string SystemConfigDir
System directory for config files.
std::string UserConfigDir
User directory for config files.
prefix_list PrefixDirs
std::string SysRoot
sysroot, if present
std::string DyldPrefix
Dynamic loader prefix, if present.
std::string DriverTitle
Driver title to use with help.
std::string HostBits
Information about the host which can be overridden by the user.
std::string HostMachine
std::string HostSystem
std::string HostRelease
std::string CCPrintStatReportFilename
The file to log CC_PRINT_PROC_STAT_FILE output to, if enabled.
std::string CCPrintInternalStatReportFilename
The file to log CC_PRINT_INTERNAL_STAT_FILE output to, if enabled.
std::string CCPrintOptionsFilename
The file to log CC_PRINT_OPTIONS output to, if enabled.
std::string CCPrintHeadersFilename
The file to log CC_PRINT_HEADERS output to, if enabled.
std::string CCLogDiagnosticsFilename
The file to log CC_LOG_DIAGNOSTICS output to, if enabled.
unsigned CCCPrintBindings: 1
Only print tool bindings, don't build any jobs.
unsigned CCPrintOptions: 1
Set CC_PRINT_OPTIONS mode, which is like -v but logs the commands to CCPrintOptionsFilename or to stderr.
HeaderIncludeFormatKind CCPrintHeadersFormat = HIFMT_None
The format of the header information that is emitted.
HeaderIncludeFilteringKind CCPrintHeadersFiltering = HIFIL_None
This flag determines whether clang should filter the header information that is emitted.
std::string FlangF128MathLibrary
Name of the library that provides implementations of IEEE-754 128-bit float math functions used by Fortran F128 runtime library.
unsigned CCLogDiagnostics: 1
Set CC_LOG_DIAGNOSTICS mode, which causes the frontend to log diagnostics to CCLogDiagnosticsFilename or to stderr, in a stable machine readable format.
unsigned CCGenDiagnostics: 1
Whether the driver is generating diagnostics for debugging purposes.
unsigned CCPrintProcessStats: 1
Set CC_PRINT_PROC_STAT mode, which causes the driver to dump performance report to CC_PRINT_PROC_STAT_FILE or to stdout.
unsigned CCPrintInternalStats: 1
Set CC_PRINT_INTERNAL_STAT mode, which causes the driver to dump internal performance report to CC_PRINT_INTERNAL_STAT_FILE or to stdout.
CC1ToolFunc CC1Main = nullptr
Primary Functionality
enum class CommandStatus { Crash = 1 , Error , Ok }
enum class ReproLevel { Off = 0 , OnCrash = static_cast<int>(CommandStatus::Crash) , OnError = static_cast<int>(CommandStatus::Error) , Always = static_cast<int>(CommandStatus::Ok) }
void CreateOffloadingDeviceToolChains (Compilation &C, InputList &Inputs)
CreateOffloadingDeviceToolChains - create all the toolchains required to support offloading devices given the programming models specified in the current compilation.
Compilation * BuildCompilation (ArrayRef< const char * > Args)
BuildCompilation - Construct a compilation object for a command line argument vector.
llvm::opt::InputArgList ParseArgStrings (ArrayRef< const char * > Args, bool UseDriverMode, bool &ContainsError)
ParseArgStrings - Parse the given list of strings into an ArgList.
void BuildInputs (const ToolChain &TC, llvm::opt::DerivedArgList &Args, InputList &Inputs) const
BuildInputs - Construct the list of inputs and their types from the given arguments.
void BuildActions (Compilation &C, llvm::opt::DerivedArgList &Args, const InputList &Inputs, ActionList &Actions) const
BuildActions - Construct the list of actions to perform for the given arguments, which are only done for a single architecture.
void BuildUniversalActions (Compilation &C, const ToolChain &TC, const InputList &BAInputs) const
BuildUniversalActions - Construct the list of actions to perform for the given arguments, which may require a universal build.
Action * BuildOffloadingActions (Compilation &C, llvm::opt::DerivedArgList &Args, const InputTy &Input, Action *HostAction) const
BuildOffloadingActions - Construct the list of actions to perform for the offloading toolchain that will be embedded in the host.
llvm::DenseSet< StringRef > getOffloadArchs (Compilation &C, const llvm::opt::DerivedArgList &Args, Action::OffloadKind Kind, const ToolChain *TC, bool SuppressError=false) const
Returns the set of bound architectures active for this offload kind.
bool DiagnoseInputExistence (const llvm::opt::DerivedArgList &Args, StringRef Value, types::ID Ty, bool TypoCorrect) const
Check that the file referenced by Value exists.
void BuildJobs (Compilation &C) const
BuildJobs - Bind actions to concrete tools and translate arguments to form the list of jobs to run.
int ExecuteCompilation (Compilation &C, SmallVectorImpl< std::pair< int, const Command * > > &FailingCommands)
ExecuteCompilation - Execute the compilation according to the command line arguments and return an appropriate exit code.
void generateCompilationDiagnostics (Compilation &C, const Command &FailingCommand, StringRef AdditionalInformation="", CompilationDiagnosticReport *GeneratedReport=nullptr)
generateCompilationDiagnostics - Generate diagnostics information including preprocessed source file(s).
bool maybeGenerateCompilationDiagnostics (CommandStatus CS, ReproLevel Level, Compilation &C, const Command &FailingCommand, StringRef AdditionalInformation="", CompilationDiagnosticReport *GeneratedReport=nullptr)
Helper Methods
enum DeviceMode { UnsetDeviceMode , FPGAHWMode , FPGAEmulationMode }
enum clang::driver::Driver::DeviceMode OffloadCompileMode = UnsetDeviceMode
llvm::Triple MakeSYCLDeviceTriple (StringRef TargetArch="spir64") const
MakeSYCLDeviceTriple - Returns the SYCL device triple for the specified subarch.
void PrintActions (const Compilation &C) const
PrintActions - Print the list of actions.
void PrintHelp (bool ShowHidden) const
PrintHelp - Print the help text.
void PrintSYCLToolHelp (const Compilation &C) const
PrintSYCLToolHelp - Print help text from offline compiler tools.
void PrintVersion (const Compilation &C, raw_ostream &OS) const
PrintVersion - Print the driver version.
std::string GetFilePath (StringRef Name, const ToolChain &TC) const
GetFilePath - Lookup Name in the list of file search paths.
std::string GetProgramPath (StringRef Name, const ToolChain &TC) const
GetProgramPath - Lookup Name in the list of program search paths.
std::string GetStdModuleManifestPath (const Compilation &C, const ToolChain &TC) const
Lookup the path to the Standard library module manifest.
void HandleAutocompletions (StringRef PassedFlags) const
HandleAutocompletions - Handle –autocomplete by searching and printing possible flags, descriptions, and its arguments.
bool HandleImmediateArgs (const Compilation &C)
HandleImmediateArgs - Handle any arguments which should be treated before building actions or binding tools.
Action * ConstructPhaseAction (Compilation &C, const llvm::opt::ArgList &Args, phases::ID Phase, Action *Input, Action::OffloadKind TargetDeviceOffloadKind=Action::OFK_None) const
ConstructAction - Construct the appropriate action to do for Phase on the Input, taking in to account arguments like -fsyntax-only or –analyze.
InputInfoList BuildJobsForAction (Compilation &C, const Action *A, const ToolChain *TC, StringRef BoundArch, bool AtTopLevel, bool MultipleArchs, const char *LinkingOutput, std::map< std::pair< const Action *, std::string >, InputInfoList > &CachedResults, Action::OffloadKind TargetDeviceOffloadKind) const
BuildJobsForAction - Construct the jobs to perform for the action A and return an InputInfo for the result of running A.
const char * getDefaultImageName () const
Returns the default name for linked images (e.g., "a.out").
const char * CreateTempFile (Compilation &C, StringRef Prefix, StringRef Suffix, bool MultipleArchs=false, StringRef BoundArch={}, types::ID Type=types::TY_Nothing, bool NeedUniqueDirectory=false) const
Creates a temp file.
const char * GetNamedOutputPath (Compilation &C, const JobAction &JA, const char *BaseInput, StringRef BoundArch, bool AtTopLevel, bool MultipleArchs, StringRef NormalizedTriple) const
GetNamedOutputPath - Return the name to use for the output of the action JA.
std::string GetTemporaryPath (StringRef Prefix, StringRef Suffix) const
GetTemporaryPath - Return the pathname of a temporary file to use as part of compilation; the file will have the given prefix and suffix.
std::string GetUniquePath (StringRef BaseName, StringRef Ext) const
GetUniquePath = Return the pathname of a unique file to use as part of compilation.
std::string GetTemporaryDirectory (StringRef Prefix) const
GetTemporaryDirectory - Return the pathname of a temporary directory to use as part of compilation; the directory will have the given prefix.
std::string GetClPchPath (Compilation &C, StringRef BaseName) const
Return the pathname of the pch file in clang-cl mode.
bool ShouldUseClangCompiler (const JobAction &JA) const
ShouldUseClangCompiler - Should the clang compiler be used to handle this action.
bool ShouldUseFlangCompiler (const JobAction &JA) const
ShouldUseFlangCompiler - Should the flang compiler be used to handle this action.
bool ShouldEmitStaticLibrary (const llvm::opt::ArgList &Args) const
ShouldEmitStaticLibrary - Should the linker emit a static library.
bool hasHeaderMode () const
Returns true if the user has indicated a C++20 header unit mode.
ModuleHeaderMode getModuleHeaderMode () const
Get the mode for handling headers as set by fmodule-header{=}.
bool isUsingLTO (bool IsOffload=false) const
Returns true if we are performing any kind of LTO.
LTOKind getLTOMode (bool IsOffload=false) const
Get the specific kind of LTO being performed.
bool IsFPGAHWMode () const
bool IsFPGAEmulationMode () const
void setOffloadCompileMode (DeviceMode ModeValue)
DeviceMode getOffloadCompileMode ()
Detailed Description
Driver - Encapsulate logic for constructing compilation processes from a set of gcc-driver-like command line arguments.
Definition at line 77 of file Driver.h.
Member Typedef Documentation
CC1ToolFunc
using clang::driver::Driver::CC1ToolFunc = llvm::function_ref<int(SmallVectorImpl<const char *> &ArgV)>
Pointer to the ExecuteCC1Tool function, if available.
When the clangDriver lib is used through clang.exe, this provides a shortcut for executing the -cc1 command-line directly, in the same process.
Definition at line 282 of file Driver.h.
InputList
using clang::driver::Driver::InputList = SmallVector<InputTy, 16>
A list of inputs and their types for the given arguments.
Definition at line 212 of file Driver.h.
InputTy
using clang::driver::Driver::InputTy = std::pair<types::ID, const llvm::opt::Arg *>
An input type and its arguments.
Definition at line 209 of file Driver.h.
prefix_list
typedef SmallVector<std::string, 4> clang::driver::Driver::prefix_list
A prefix directory used to emulate a limited subset of GCC's '-Bprefix' functionality.
FIXME: This type of customization should be removed in favor of the universal driver when it is ready.
Definition at line 178 of file Driver.h.
Member Enumeration Documentation
CommandStatus
enum clang::driver::Driver::CommandStatus strong
Enumerator
Crash
Error
Ok
Definition at line 561 of file Driver.h.
DeviceMode
enum clang::driver::Driver::DeviceMode
Enumerator
UnsetDeviceMode
FPGAHWMode
FPGAEmulationMode
Definition at line 748 of file Driver.h.
OpenMPRuntimeKind
enum clang::driver::Driver::OpenMPRuntimeKind
Enumerator
OMPRT_Unknown
An unknown OpenMP runtime.
We can't generate effective OpenMP code without knowing what runtime to target.
OMPRT_OMP
The LLVM OpenMP runtime.
When completed and integrated, this will become the default for Clang.
OMPRT_GOMP
The GNU OpenMP runtime.
Clang doesn't support generating OpenMP code for this runtime but can swallow the pragmas, and find and link against the runtime library itself.
OMPRT_IOMP5
The legacy name for the LLVM OpenMP runtime from when it was the Intel OpenMP runtime.
We support this mode for users with existing dependencies on this runtime library name.
Definition at line 125 of file Driver.h.
ReproLevel
enum clang::driver::Driver::ReproLevel strong
Enumerator
Off
OnCrash
OnError
Always
Definition at line 567 of file Driver.h.
Constructor & Destructor Documentation
Driver()
Driver::Driver (StringRef ClangExecutable, StringRef TargetTriple, DiagnosticsEngine & Diags, std::string Title = "clang LLVM compiler", IntrusiveRefCntPtr< llvm::vfs::FileSystem > VFS = nullptr)
Definition at line 201 of file Driver.cpp.
References ClangExecutable, Dir, GetResourcesPath(), Name, P, ResourceDir, SysRoot, SystemConfigDir, and UserConfigDir.
Member Function Documentation
addFPGATempDepFile()
void clang::driver::Driver::addFPGATempDepFile (const std::string & DepName, const std::string & FileName) const inline
addFPGATempDepFile - Add a file to be added to the bundling step of an FPGA object.
Definition at line 922 of file Driver.h.
References clang::FileName.
addIntegrationFiles()
void clang::driver::Driver::addIntegrationFiles (StringRef IntHeaderName, StringRef IntFooterName, StringRef FileName) const inline
addIntegrationFiles - Add the integration files that will be populated by the device compilation and used by the host compile.
Definition at line 938 of file Driver.h.
References clang::FileName.
Referenced by BuildActions().
addSYCLTargetMacroArg()
void clang::driver::Driver::addSYCLTargetMacroArg (const llvm::opt::ArgList & Args, StringRef Macro) const inline
addSYCLTargetMacroArg - Add the given macro to the vector of args to be added to the host compilation step.
Definition at line 957 of file Driver.h.
Referenced by clang::driver::tools::Clang::ConstructJob().
addSYCLUniqueID()
void clang::driver::Driver::addSYCLUniqueID (StringRef UniqueID, StringRef FileName) const inline
setSYCLUniqueID - set the Unique ID that is used for all FE invocations when performing compilations for SYCL.
Definition at line 968 of file Driver.h.
References clang::FileName.
Referenced by BuildActions().
BuildActions()
void Driver::BuildActions (Compilation & C, llvm::opt::DerivedArgList & Args, const InputList & Inputs, ActionList & Actions) const
BuildActions - Construct the list of actions to perform for the given arguments, which are only done for a single architecture.
Parameters
C - The compilation that is being built.
Args - The input arguments.
Actions - The list to store the resulting actions onto.
Definition at line 7231 of file Driver.cpp.
References addIntegrationFiles(), addSYCLUniqueID(), Diag(), clang::driver::types::getCompilationPhases(), getOpts(), isSaveTempsEnabled(), clang::driver::types::isSrcFile(), clang::driver::Action::OFK_OpenMP, and V.
Referenced by BuildUniversalActions(), and generateCompilationDiagnostics().
BuildCompilation()
Compilation * Driver::BuildCompilation (ArrayRef< const char * > Args)
BuildCompilation - Construct a compilation object for a command line argument vector.
Returns
A compilation, or 0 if none was built for the given argument vector. A null return value does not necessarily indicate an error condition, the diagnostics should be queried to determine if an error occurred.
Definition at line 1548 of file Driver.cpp.
References appendOneArg(), CCCIsCC(), CCCPrintBindings, CCPrintProcessStats, CCPrintStatReportFilename, ClangExecutable, Diag(), Dir, DyldPrefix, clang::driver::getDriverMode(), IsCLMode(), IsDXCMode(), Name, ParseArgStrings(), clang::driver::toolchains::HLSLToolChain::parseTargetProfile(), PrefixDirs, ResourceDir, SysRoot, and clang::T.
Referenced by clang::createInvocation().
BuildInputs()
void Driver::BuildInputs (const ToolChain & TC, llvm::opt::DerivedArgList & Args, InputList & Inputs) const
BuildInputs - Construct the list of inputs and their types from the given arguments.
Parameters
TC - The default host tool chain.
Args - The input arguments.
Inputs - The list to store the resulting compilation inputs onto.
Definition at line 3093 of file Driver.cpp.
References CCCIsCPP(), CCCIsCXX(), CCGenDiagnostics, CXXHeaderUnitType(), Diag(), DiagnoseInputExistence(), clang::driver::Action::getKind(), getOpts(), clang::driver::types::getTypeName(), hasHeaderMode(), IsCLMode(), IsDXCMode(), IsFlangMode(), clang::driver::options::LinkerInput, clang::driver::types::lookupCXXTypeForCType(), clang::driver::ToolChain::LookupTypeForExtension(), clang::driver::types::lookupTypeForTypeSpecifier(), MakeInputArg(), Previous, and clang::driver::types::TY_INVALID.
Referenced by generateCompilationDiagnostics().
BuildJobs()
void Driver::BuildJobs (Compilation & C) const
BuildJobs - Bind actions to concrete tools and translate arguments to form the list of jobs to run.
Parameters
C - The compilation that is being built.
Definition at line 8156 of file Driver.cpp.
References clang::driver::Action::BindArchClass, BuildJobsForAction(), CCPrintProcessStats, CCPrintStatReportFilename, Cmd, clang::driver::Action::CompileJobClass, Diag(), getDefaultImageName(), clang::driver::Action::getInputs(), clang::driver::Action::getKind(), clang::driver::Action::getType(), clang::if(), clang::driver::Action::IfsMergeJobClass, clang::driver::Action::OffloadClass, clang::driver::Action::OFK_None, and clang::driver::Action::size().
Referenced by generateCompilationDiagnostics().
BuildJobsForAction()
InputInfoList Driver::BuildJobsForAction (Compilation & C, const Action * A, const ToolChain * TC, StringRef BoundArch, bool AtTopLevel, bool MultipleArchs, const char * LinkingOutput, std::map< std::pair< const Action *, std::string >, InputInfoList > & CachedResults, Action::OffloadKind TargetDeviceOffloadKind) const
BuildJobsForAction - Construct the jobs to perform for the action A and return an InputInfo for the result of running A.
Will only construct jobs for a given (Action, ToolChain, BoundArch, DeviceKind) tuple once.
Definition at line 8714 of file Driver.cpp.
References GetTriplePlusArchString().
Referenced by BuildJobs().
BuildOffloadingActions()
Action * Driver::BuildOffloadingActions (Compilation & C, llvm::opt::DerivedArgList & Args, const InputTy & Input, Action * HostAction) const
BuildOffloadingActions - Construct the list of actions to perform for the offloading toolchain that will be embedded in the host.
Parameters
C - The compilation that is being built.
Args - The input arguments.
Input - The input type and arguments
HostAction - The host action used in the offloading toolchain.
Definition at line 7823 of file Driver.cpp.
References clang::driver::OffloadAction::DeviceDependences::add(), ConstructPhaseAction(), clang::driver::types::getCompilationPhases(), getFinalPhase(), clang::driver::Action::getInputs(), getOffloadArchs(), clang::driver::Action::getType(), clang::driver::types::isCuda(), clang::driver::types::isHIP(), clang::driver::types::isSrcFile(), clang::driver::phases::Link, clang::driver::options::LinkerInput, offloadDeviceOnly(), offloadHostOnly(), clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_HIP, clang::driver::Action::OFK_Host, clang::driver::Action::OFK_OpenMP, clang::driver::Action::OFK_SYCL, clang::driver::phases::Preprocess, clang::driver::Action::propagateDeviceOffloadInfo(), and clang::driver::Action::setCannotBeCollapsedWithNextDependentAction().
BuildUniversalActions()
void Driver::BuildUniversalActions (Compilation & C, const ToolChain & TC, const InputList & BAInputs) const
BuildUniversalActions - Construct the list of actions to perform for the given arguments, which may require a universal build.
Parameters
C - The compilation that is being built.
TC - The default host tool chain.
Definition at line 2914 of file Driver.cpp.
References BuildActions(), clang::driver::types::canLipoType(), ContainsCompileOrAssembleAction(), Diag(), clang::driver::tools::darwin::getArchTypeForMachOArchName(), clang::driver::ToolChain::getDefaultUniversalArchName(), clang::driver::types::getTypeName(), and clang::driver::willEmitRemarks().
Referenced by generateCompilationDiagnostics().
CCCIsCC()
bool clang::driver::Driver::CCCIsCC () const inline
Whether the driver should follow gcc like behavior.
Definition at line 221 of file Driver.h.
Referenced by BuildCompilation().
CCCIsCPP()
bool clang::driver::Driver::CCCIsCPP () const inline
Whether the driver is just the preprocessor.
Definition at line 218 of file Driver.h.
Referenced by BuildInputs(), CheckPreprocessingOptions(), and getFinalPhase().
CCCIsCXX()
bool clang::driver::Driver::CCCIsCXX () const inline
Whether the driver should follow g++ like behavior.
Definition at line 215 of file Driver.h.
Referenced by AddLibgcc(), AddUnwindLibrary(), BuildInputs(), constructHexagonLinkArgs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::gcc::Common::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), and clang::driver::ToolChain::ShouldLinkCXXStdlib().
ConstructPhaseAction()
Action * Driver::ConstructPhaseAction (Compilation & C, const llvm::opt::ArgList & Args, phases::ID Phase, Action * Input, Action::OffloadKind TargetDeviceOffloadKind = Action::OFK_None) const
ConstructAction - Construct the appropriate action to do for Phase on the Input, taking in to account arguments like -fsyntax-only or –analyze.
Definition at line 7996 of file Driver.cpp.
References clang::driver::phases::Assemble, clang::driver::phases::Backend, CCGenDiagnostics, clang::driver::phases::Compile, clang::driver::Action::getOffloadingToolChain(), clang::driver::types::getPrecompiledType(), clang::driver::types::getPreprocessedType(), clang::driver::ToolChain::getTriple(), clang::driver::Action::getType(), clang::driver::phases::IfsMerge, isUsingLTO(), clang::driver::phases::Link, offloadDeviceOnly(), clang::driver::Action::OFK_HIP, clang::driver::Action::OFK_None, clang::driver::Action::OFK_OpenMP, clang::driver::phases::Precompile, clang::driver::phases::Preprocess, and clang::driver::types::TY_INVALID.
Referenced by BuildOffloadingActions().
createAppendedFooterInput()
void clang::driver::Driver::createAppendedFooterInput (Action *& Input, Compilation & C, const llvm::opt::ArgList & Args) const
createAppendedFooterInput - Create new source file.
CreateOffloadingDeviceToolChains()
void Driver::CreateOffloadingDeviceToolChains (Compilation & C, InputList & Inputs)
CreateOffloadingDeviceToolChains - create all the toolchains required to support offloading devices given the programming models specified in the current compilation.
Also, update the host tool chain kind accordingly.
Definition at line 850 of file Driver.cpp.
References addSYCLDefaultTriple(), clang::driver::toolchains::NVPTXToolChain::CudaInstallation, clang::Device, Diag(), getDefaultSYCLArch(), getHIPOffloadTargetTriple(), getNVIDIAOffloadTargetTriple(), getOffloadArchs(), getOpenMPRuntime(), clang::driver::ToolChain::getOpenMPTriple(), clang::getProcessorFromTargetID(), clang::driver::ToolChain::getTriple(), clang::IsAMDGpuArch(), clang::driver::types::isCuda(), clang::driver::types::isHIP(), clang::IsNVIDIAGpuArch(), clang::driver::CudaInstallationDetector::isValid(), isValidSYCLTriple(), MakeSYCLDeviceTriple(), clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_HIP, clang::driver::Action::OFK_Host, clang::driver::Action::OFK_None, clang::driver::Action::OFK_OpenMP, clang::driver::Action::OFK_SYCL, OMPRT_IOMP5, OMPRT_OMP, populateSYCLDeviceTraitsMacrosArgs(), clang::StringToCudaArch(), clang::T, and clang::driver::CudaInstallationDetector::WarnIfUnsupportedVersion().
CreateTempFile()
const char * Driver::CreateTempFile (Compilation & C, StringRef Prefix, StringRef Suffix, bool MultipleArchs = false, StringRef BoundArch = {}, types::ID Type = types::TY_Nothing, bool NeedUniqueDirectory = false) const
Creates a temp file.
If MultipleArch is false or BoundArch is empty, the temp file is in the temporary directory with name $Prefix-%%%%%%.$Suffix.
If MultipleArch is true and BoundArch is not empty, 2a. If NeedUniqueDirectory is false, the temp file is in the temporary directory with name $Prefix-$BoundArch-%%%%%.$Suffix. 2b. If NeedUniqueDirectory is true, the temp file is in a unique subdiretory with random name under the temporary directory, and the temp file itself has name $Prefix-$BoundArch.$Suffix.
Definition at line 9311 of file Driver.cpp.
References CCGenDiagnostics, Diag(), GetTemporaryDirectory(), GetTemporaryPath(), and getVFS().
Referenced by generateCompilationDiagnostics(), and GetNamedOutputPath().
Diag()
DiagnosticBuilder clang::driver::Driver::Diag (unsigned DiagID) const inline
Definition at line 146 of file Driver.h.
References clang::DiagnosticsEngine::Report().
Referenced by clang::driver::SanitizerArgs::addArgs(), clang::driver::toolchains::DarwinClang::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::CudaToolChain::addClangTargetOptions(), clang::driver::toolchains::HIPAMDToolChain::addClangTargetOptions(), addCoveragePrefixMapArg(), clang::driver::CudaInstallationDetector::AddCudaIncludeArgs(), addDefaultIgnorelists(), addFloatingPointOptions(), addFortranMain(), clang::driver::toolchains::HIPSPVToolChain::AddHIPIncludeArgs(), clang::driver::toolchains::SYCLToolChain::AddImpliedTargetArgs(), clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), clang::driver::tools::addLinkerCompressDebugSectionsOption(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), clang::driver::tools::addMachineOutlinerArgs(), addMacroPrefixMapArg(), clang::driver::tools::addOpenMPDeviceRTL(), clang::driver::tools::addOutlineAtomicsArgs(), addPGOAndCoverageFlags(), addPgProfilingLinkArgs(), addTocDataOptions(), clang::driver::tools::ClangAs::AddX86TargetArgs(), clang::driver::toolchains::AVRToolChain::AVRToolChain(), BuildActions(), clang::driver::toolchains::MSVCToolChain::buildAssembler(), BuildCompilation(), BuildInputs(), BuildJobs(), BuildUniversalActions(), clang::driver::tools::checkAMDGPUCodeObjectVersion(), checkARMArchName(), checkARMCPUName(), checkARMFloatABI(), CheckCodeGenerationOptions(), clang::driver::CudaInstallationDetector::CheckCudaVersionSupportsArch(), checkDebugInfoOption(), clang::driver::toolchains::Darwin::CheckObjCARC(), CheckPreprocessingOptions(), checkRemarksOptions(), clang::driver::toolchains::AMDGPUToolChain::checkTargetID(), clang::driver::toolchains::HIPAMDToolChain::checkTargetID(), clang::driver::Compilation::CleanupFile(), CollectArgsForIntegratedAssembler(), CollectARMPACBTIOptions(), clang::driver::ToolChain::computeMSVCVersion(), computeTargetTriple(), clang::driver::tools::aix::Assembler::ConstructJob(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::baremetal::StaticLibTool::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::CrossWindows::Linker::ConstructJob(), clang::driver::tools::darwin::StaticLibTool::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::fuchsia::StaticLibTool::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::gnutools::StaticLibTool::ConstructJob(), clang::driver::tools::gcc::Common::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), CreateOffloadingDeviceToolChains(), CreateTempFile(), DecodeAArch64Features(), DiagnoseInputExistence(), EmitComplexRangeDiag(), clang::driver::Compilation::ExecuteCommand(), ExecuteCompilation(), findPassPlugin(), generateCompilationDiagnostics(), getARMFPUFeatures(), getARMHWDivFeatures(), getCSKYFPUFeatures(), clang::driver::ToolChain::GetCXXStdlibType(), clang::driver::toolchains::Fuchsia::GetCXXStdlibType(), clang::driver::toolchains::HexagonToolChain::GetCXXStdlibType(), clang::driver::toolchains::MipsLLVMToolChain::GetCXXStdlibType(), clang::driver::toolchains::NaClToolChain::GetCXXStdlibType(), clang::driver::toolchains::OHOS::GetCXXStdlibType(), clang::driver::toolchains::AMDGPUOpenMPToolChain::getDeviceLibs(), clang::driver::toolchains::HIPAMDToolChain::getDeviceLibs(), clang::driver::toolchains::HIPSPVToolChain::getDeviceLibs(), clang::driver::tools::getDwarfVersion(), getHIPOffloadTargetTriple(), clang::driver::ToolChain::GetLinkerPath(), clang::driver::tools::solaris::Linker::getLinkerPath(), clang::driver::tools::wasm::Linker::getLinkerPath(), clang::driver::toolchains::MachO::getLinkerVersion(), GetNamedOutputPath(), getNVIDIAOffloadTargetTriple(), getOffloadTargetTriple(), getOpenMPRuntime(), getRefinementStep(), getRISCFeaturesFromMcpu(), clang::driver::ToolChain::GetRuntimeLibType(), clang::driver::toolchains::DarwinClang::GetRuntimeLibType(), clang::driver::toolchains::Fuchsia::GetRuntimeLibType(), clang::driver::toolchains::OHOS::GetRuntimeLibType(), getStaticPIE(), clang::driver::tools::getStatsFileName(), GetTemporaryDirectory(), GetTemporaryPath(), GetUniquePath(), clang::driver::ToolChain::GetUnwindLibType(), handleHVXWarnings(), clang::driver::toolchains::Generic_GCC::GCCInstallationDetector::init(), clang::driver::tools::isTLSDESCEnabled(), ParseArgStrings(), parseArgValues(), parseBinaryMetadataFeatures(), parseClangCLEHFlags(), parseCoverageFeatures(), ParseDebugDefaultVersion(), parseLTOMode(), ParseMPreferVectorWidth(), ParseMRecip(), parseSpecialCaseListArg(), clang::driver::toolchains::PPCLinuxToolChain::PPCLinuxToolChain(), ProcessVSRuntimeLibrary(), clang::driver::toolchains::PS4PS5Base::PS4PS5Base(), RenderARCMigrateToolOptions(), RenderDebugInfoCompressionArgs(), renderDebugOptions(), RenderDiagnosticsOptions(), renderDwarfFormat(), clang::driver::tools::gcc::Compiler::RenderExtraToolArgs(), RenderFloatingPointOptions(), RenderModulesOptions(), RenderObjCOptions(), RenderOpenACCOptions(), RenderSSPOptions(), RenderTrivialAutoVarInitOptions(), clang::driver::toolchains::HLSLToolChain::requiresValidation(), clang::driver::RocmInstallationDetector::RocmInstallationDetector(), clang::driver::SanitizerArgs::SanitizerArgs(), SetRISCVSmallDataLimit(), clang::driver::toolchains::SYCLToolChain::SYCLToolChain(), clang::driver::toolchains::AMDGPUToolChain::TranslateArgs(), clang::driver::toolchains::AMDGPUOpenMPToolChain::TranslateArgs(), clang::driver::toolchains::CudaToolChain::TranslateArgs(), clang::driver::toolchains::Darwin::TranslateArgs(), clang::driver::toolchains::HLSLToolChain::TranslateArgs(), clang::driver::toolchains::SYCLToolChain::TranslateTargetOpt(), clang::driver::ToolChain::useIntegratedBackend(), validateSpecialCaseListFormat(), WarnForDeprecatedBackendOpts(), and clang::driver::XRayArgs::XRayArgs().
DiagnoseInputExistence()
bool Driver::DiagnoseInputExistence (const llvm::opt::DerivedArgList & Args, StringRef Value, types::ID Ty, bool TypoCorrect) const
Check that the file referenced by Value exists.
If it doesn't, issue a diagnostic and return false. If TypoCorrect is true and the file does not exist, see if it looks like a likely typo for a flag and if so print a "did you mean" blurb.
Definition at line 3002 of file Driver.cpp.
References Diag(), getCheckInputsExist(), getOpts(), getVFS(), and IsCLMode().
Referenced by BuildInputs().
embedBitcodeEnabled()
bool clang::driver::Driver::embedBitcodeEnabled () const inline
Definition at line 438 of file Driver.h.
embedBitcodeInObject()
bool clang::driver::Driver::embedBitcodeInObject () const inline
Definition at line 439 of file Driver.h.
embedBitcodeMarkerOnly()
bool clang::driver::Driver::embedBitcodeMarkerOnly () const inline
Definition at line 440 of file Driver.h.
ExecuteCompilation()
int Driver::ExecuteCompilation (Compilation & C, SmallVectorImpl< std::pair< int, const Command * > > & FailingCommands)
ExecuteCompilation - Execute the compilation according to the command line arguments and return an appropriate exit code.
This routine handles additional processing that must be done in addition to just running the subprocesses, for example reporting errors, setting up response files, removing temporary files, etc.
Definition at line 2300 of file Driver.cpp.
References Diag(), clang::driver::Command::getCreator(), clang::driver::Command::getDiagForErrorCode(), clang::driver::Tool::getShortName(), clang::driver::Command::getSource(), clang::DiagnosticsEngine::hasErrorOccurred(), clang::driver::Tool::hasGoodDiagnostics(), and isSaveTempsEnabled().
generateCompilationDiagnostics()
void Driver::generateCompilationDiagnostics (Compilation & C, const Command & FailingCommand, StringRef AdditionalInformation = "", CompilationDiagnosticReport * GeneratedReport = nullptr)
generateCompilationDiagnostics - Generate diagnostics information including preprocessed source file(s).
Definition at line 2054 of file Driver.cpp.
References BugReporMsg, BuildActions(), BuildInputs(), BuildJobs(), BuildUniversalActions(), CCGenDiagnostics, Cmd, CreateTempFile(), Diag(), clang::driver::Command::Execute(), clang::driver::CrashReportInfo::Filename, clang::driver::Command::getArguments(), clang::getClangFullVersion(), clang::driver::Command::getCreator(), clang::driver::types::getPreprocessedType(), clang::driver::ToolChain::getTriple(), clang::DiagnosticErrorTrap::hasErrorOccurred(), clang::driver::Tool::isDsymutilJob(), clang::driver::Tool::isLinkJob(), Name, printArgList(), PrintVersion(), clang::driver::Command::replaceArguments(), clang::driver::Driver::CompilationDiagnosticReport::TemporaryFiles, and clang::driver::types::TY_INVALID.
Referenced by maybeGenerateCompilationDiagnostics().
getCCCGenericGCCName()
const std::string& clang::driver::Driver::getCCCGenericGCCName () const inline
Name to use when invoking gcc/g++.
Definition at line 395 of file Driver.h.
Referenced by clang::driver::tools::gcc::Common::ConstructJob().
getCheckInputsExist()
bool clang::driver::Driver::getCheckInputsExist () const inline
Definition at line 407 of file Driver.h.
Referenced by DiagnoseInputExistence().
getClangProgramPath()
const char* clang::driver::Driver::getClangProgramPath () const inline
Get the path to the main clang executable.
Definition at line 425 of file Driver.h.
References ClangExecutable.
Referenced by clang::driver::tools::Clang::ConstructJob().
GetClPchPath()
std::string Driver::GetClPchPath (Compilation & C, StringRef BaseName) const
Return the pathname of the pch file in clang-cl mode.
Definition at line 9890 of file Driver.cpp.
Referenced by GetNamedOutputPath().
getConfigFiles()
llvm::ArrayRef<std::string> clang::driver::Driver::getConfigFiles () const inline
Definition at line 397 of file Driver.h.
getDefaultImageName()
const char * Driver::getDefaultImageName () const
Returns the default name for linked images (e.g., "a.out").
Definition at line 9262 of file Driver.cpp.
References normalize().
Referenced by BuildJobs(), and GetNamedOutputPath().
getDefaultModuleCachePath()
bool Driver::getDefaultModuleCachePath (SmallVectorImpl< char > & Result) static
Compute the default -fmodule-cache-path.
Returns
True if the system provides a default cache directory.
Definition at line 3991 of file Clang.cpp.
Referenced by RenderModulesOptions().
getDeviceTraitsMacrosArgs()
llvm::opt::ArgStringList clang::driver::Driver::getDeviceTraitsMacrosArgs () const inline
Definition at line 982 of file Driver.h.
Referenced by clang::driver::tools::Clang::ConstructJob().
getDiags()
DiagnosticsEngine& clang::driver::Driver::getDiags () const inline
Definition at line 403 of file Driver.h.
Referenced by clang::driver::tools::Flang::ConstructJob(), clang::driver::toolchains::HIPAMDToolChain::getDeviceLibs(), clang::driver::toolchains::HIPAMDToolChain::HIPAMDToolChain(), RenderDiagnosticsOptions(), and shouldSkipSanitizeOption().
GetFilePath()
std::string Driver::GetFilePath (StringRef Name, const ToolChain & TC) const
GetFilePath - Lookup Name in the list of file search paths.
Parameters
TC - The tool chain for additional information on directories to search.
Definition at line 9709 of file Driver.cpp.
References Dir, clang::driver::ToolChain::getCompilerRTPath(), clang::driver::ToolChain::getFilePaths(), clang::driver::ToolChain::getLibraryPaths(), Name, P, PrefixDirs, ResourceDir, and SysRoot.
Referenced by GetStdModuleManifestPath(), and HandleImmediateArgs().
getFinalPhase()
phases::ID Driver::getFinalPhase (const llvm::opt::DerivedArgList & DAL, llvm::opt::Arg ** FinalPhaseArg = nullptr) const
Definition at line 355 of file Driver.cpp.
References clang::driver::phases::Assemble, clang::driver::phases::Backend, CCCIsCPP(), CCGenDiagnostics, clang::driver::phases::Compile, clang::driver::phases::IfsMerge, clang::driver::phases::Link, clang::driver::phases::Precompile, and clang::driver::phases::Preprocess.
Referenced by BuildOffloadingActions(), and clang::driver::types::getCompilationPhases().
getFlangF128MathLibrary()
StringRef clang::driver::Driver::getFlangF128MathLibrary () const inline
Definition at line 448 of file Driver.h.
References FlangF128MathLibrary.
getFPGATempDepFile()
const std::string clang::driver::Driver::getFPGATempDepFile (const std::string & FileName) const inline
getFPGATempDepFile - Get a file to be added to the bundling step of an FPGA object.
Definition at line 928 of file Driver.h.
References clang::FileName.
getInstalledDir()
const char* clang::driver::Driver::getInstalledDir () const inline
Get the path to where the clang executable was installed.
Definition at line 430 of file Driver.h.
References Dir.
Referenced by clang::driver::toolchains::SYCLToolChain::AddSYCLIncludeArgs().
getIntegrationFooter()
StringRef clang::driver::Driver::getIntegrationFooter (StringRef FileName) const inline
getIntegrationFooter - Get the integration footer file
Definition at line 948 of file Driver.h.
References clang::FileName.
Referenced by clang::driver::tools::Clang::ConstructJob().
getIntegrationHeader()
StringRef clang::driver::Driver::getIntegrationHeader (StringRef FileName) const inline
getIntegrationHeader - Get the integration header file
Definition at line 944 of file Driver.h.
References clang::FileName.
Referenced by clang::driver::tools::Clang::ConstructJob().
getLTOMode()
LTOKind clang::driver::Driver::getLTOMode (bool IsOffload = false) const inline
Get the specific kind of LTO being performed.
Definition at line 743 of file Driver.h.
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), and isUsingLTO().
getModuleHeaderMode()
ModuleHeaderMode clang::driver::Driver::getModuleHeaderMode () const inline
Get the mode for handling headers as set by fmodule-header{=}.
Definition at line 735 of file Driver.h.
GetNamedOutputPath()
const char * Driver::GetNamedOutputPath (Compilation & C, const JobAction & JA, const char * BaseInput, StringRef BoundArch, bool AtTopLevel, bool MultipleArchs, StringRef NormalizedTriple) const
GetNamedOutputPath - Return the name to use for the output of the action JA.
The result is appended to the compilation's list of temporary or result files, as appropriate.
Parameters
C - The compilation.
JA - The action of interest.
BaseInput - The original input file that this action was triggered by.
BoundArch - The bound architecture.
AtTopLevel - Whether this is a "top-level" action.
MultipleArchs - Whether multiple -arch options were supplied.
NormalizedTriple - The normalized triple of the relevant target.
Definition at line 9374 of file Driver.cpp.
References clang::driver::types::appendSuffixForType(), CCGenDiagnostics, CreateTempFile(), Diag(), End, GetClPchPath(), getDefaultImageName(), GetModuleOutputPath(), clang::driver::Action::getOffloadingDeviceKind(), clang::driver::Action::getOffloadingHostActiveKinds(), clang::driver::Action::getOffloadingToolChain(), GetTemporaryPath(), clang::driver::ToolChain::getTriple(), clang::driver::Action::getType(), clang::driver::types::getTypeTempSuffix(), GetUniquePath(), HasPreprocessOutput(), IsCLMode(), IsDXCMode(), clang::driver::Action::isOffloading(), isSaveTempsEnabled(), isSaveTempsObj(), MakeCLOutputFilename(), Name, clang::driver::Action::OFK_HIP, clang::driver::Action::OFK_Host, clang::driver::Action::OFK_None, and clang::driver::Action::OFK_OpenMP.
getOffloadArchs()
llvm::DenseSet< StringRef > Driver::getOffloadArchs (Compilation & C, const llvm::opt::DerivedArgList & Args, Action::OffloadKind Kind, const ToolChain * TC, bool SuppressError = false) const
Returns the set of bound architectures active for this offload kind.
If there are no bound architctures we return a set containing only the empty string. The SuppressError option is used to suppress errors.
Definition at line 7719 of file Driver.cpp.
References clang::driver::ToolChain::getOpenMPTriple(), and clang::driver::ToolChain::getTriple().
Referenced by BuildOffloadingActions(), and CreateOffloadingDeviceToolChains().
getOffloadCompileMode()
DeviceMode clang::driver::Driver::getOffloadCompileMode () inline
Definition at line 764 of file Driver.h.
References OffloadCompileMode.
getOffloadStaticLibSeen()
bool clang::driver::Driver::getOffloadStaticLibSeen () const inline
Definition at line 915 of file Driver.h.
getOpenMPRuntime()
Driver::OpenMPRuntimeKind Driver::getOpenMPRuntime (const llvm::opt::ArgList & Args) const
Compute the desired OpenMP runtime from the flags provided.
Definition at line 775 of file Driver.cpp.
References Diag(), OMPRT_GOMP, OMPRT_IOMP5, OMPRT_OMP, and OMPRT_Unknown.
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), and CreateOffloadingDeviceToolChains().
getOpts()
const llvm::opt::OptTable& clang::driver::Driver::getOpts () const inline
Definition at line 401 of file Driver.h.
References clang::driver::getDriverOptTable().
Referenced by BuildActions(), BuildInputs(), DiagnoseInputExistence(), getStaticPIE(), HandleAutocompletions(), ParseArgStrings(), PrintHelp(), clang::driver::toolchains::AMDGPUToolChain::TranslateArgs(), clang::driver::toolchains::AMDGPUOpenMPToolChain::TranslateArgs(), clang::driver::toolchains::CudaToolChain::TranslateArgs(), clang::driver::toolchains::MachO::TranslateArgs(), clang::driver::toolchains::Generic_GCC::TranslateArgs(), clang::driver::toolchains::HIPAMDToolChain::TranslateArgs(), clang::driver::toolchains::HLSLToolChain::TranslateArgs(), clang::driver::toolchains::MSVCToolChain::TranslateArgs(), clang::driver::toolchains::SYCLToolChain::TranslateArgs(), clang::driver::ToolChain::TranslateOffloadTargetArgs(), and clang::driver::ToolChain::TranslateXarchArgs().
getPrependArg()
const char* clang::driver::Driver::getPrependArg () const inline
Definition at line 414 of file Driver.h.
Referenced by clang::driver::tools::Clang::ConstructJob().
getProbePrecompiled()
bool clang::driver::Driver::getProbePrecompiled () const inline
Definition at line 411 of file Driver.h.
GetProgramPath()
std::string Driver::GetProgramPath (StringRef Name, const ToolChain & TC) const
GetProgramPath - Lookup Name in the list of program search paths.
Parameters
TC - The provided tool chain for additional information on directories to search.
Definition at line 9769 of file Driver.cpp.
References Name, P, PrefixDirs, and ScanDirForExecutable().
Referenced by clang::driver::tools::Flang::ConstructJob(), and HandleImmediateArgs().
GetReleaseVersion() [1/2]
bool Driver::GetReleaseVersion (StringRef Str, MutableArrayRef< unsigned > Digits) static
Parse digits from a string Str and fulfill Digits with the parsed numbers.
This method assumes that the max number of digits to look for is equal to Digits.size().
Returns
True if the entire string was parsed and there are no extra characters remaining at the end.
Definition at line 10243 of file Driver.cpp.
GetReleaseVersion() [2/2]
bool Driver::GetReleaseVersion (StringRef Str, unsigned & Major, unsigned & Minor, unsigned & Micro, bool & HadExtra) static
GetReleaseVersion - Parse (([0-9]+)(.
([0-9]+)(.([0-9]+)?))?)? and return the grouped values as integers. Numbers which are not provided are set to 0.
Returns
True if the entire string was parsed (9.2), or all groups were parsed (10.3.5extrastuff). HadExtra is true if all groups were parsed but extra characters remain at the end.
([0-9]+)(.([0-9]+)?))?)? and return the grouped values as integers. Numbers which are not provided are set to 0.
Returns
True if the entire string was parsed (9.2), or all groups were parsed (10.3.5extrastuff).
Definition at line 10208 of file Driver.cpp.
Referenced by getSystemOrSDKMacOSVersion().
GetResourcesPath()
std::string Driver::GetResourcesPath (StringRef BinaryPath, StringRef CustomResourceDir = "") static
Takes the path to a binary that's either in bin/ or lib/ and returns the path to clang's resource directory.
Definition at line 173 of file Driver.cpp.
References P.
Referenced by Driver().
GetStdModuleManifestPath()
std::string Driver::GetStdModuleManifestPath (const Compilation & C, const ToolChain & TC) const
Lookup the path to the Standard library module manifest.
Parameters
C - The compilation.
TC - The tool chain for additional information on directories to search.
Definition at line 9811 of file Driver.cpp.
References clang::driver::ToolChain::CST_Libcxx, clang::driver::ToolChain::CST_Libstdcxx, clang::driver::ToolChain::GetCXXStdlibType(), GetFilePath(), and clang::driver::ToolChain::getVFS().
Referenced by HandleImmediateArgs().
getSYCLTargetMacroArgs()
llvm::ArrayRef<std::string> clang::driver::Driver::getSYCLTargetMacroArgs () const inline
getSYCLTargetMacroArgs - return the previously gathered macro target args.
Definition at line 962 of file Driver.h.
Referenced by clang::driver::tools::Clang::ConstructJob().
getSYCLUniqueID()
StringRef clang::driver::Driver::getSYCLUniqueID (StringRef FileName) const inline
getSYCLUniqueID - Get the Unique ID associated with the file.
Definition at line 972 of file Driver.h.
References clang::FileName.
Referenced by clang::driver::tools::Clang::ConstructJob().
getTargetTriple()
std::string clang::driver::Driver::getTargetTriple () const inline
Definition at line 422 of file Driver.h.
Referenced by computeBaseSysRoot(), clang::driver::tools::aix::Assembler::ConstructJob(), clang::driver::tools::aix::Linker::ConstructJob(), getLiteralTriple(), GetSDLFromOffloadArchive(), and clang::driver::toolchains::RISCVToolChain::hasGCCToolchain().
GetTemporaryDirectory()
std::string Driver::GetTemporaryDirectory (StringRef Prefix) const
GetTemporaryDirectory - Return the pathname of a temporary directory to use as part of compilation; the directory will have the given prefix.
Definition at line 9879 of file Driver.cpp.
References Diag().
Referenced by CreateTempFile().
GetTemporaryPath()
std::string Driver::GetTemporaryPath (StringRef Prefix, StringRef Suffix) const
GetTemporaryPath - Return the pathname of a temporary file to use as part of compilation; the file will have the given prefix and suffix.
GCC goes to extra lengths here to be a bit more robust.
Definition at line 9856 of file Driver.cpp.
References Diag().
Referenced by CreateTempFile(), GetNamedOutputPath(), and GetSDLFromOffloadArchive().
getTitle()
const std::string& clang::driver::Driver::getTitle () inline
Definition at line 419 of file Driver.h.
References DriverTitle.
GetUniquePath()
std::string Driver::GetUniquePath (StringRef BaseName, StringRef Ext) const
GetUniquePath = Return the pathname of a unique file to use as part of compilation.
The file will have the given base name (BaseName) and extension (Ext).
Definition at line 9867 of file Driver.cpp.
References Diag().
Referenced by GetNamedOutputPath().
getUseNewOffloadingDriver()
bool clang::driver::Driver::getUseNewOffloadingDriver () const inline
getUseNewOffloadingDriver - use the new offload driver for OpenMP.
Definition at line 918 of file Driver.h.
getVFS()
llvm::vfs::FileSystem& clang::driver::Driver::getVFS () const inline
Definition at line 405 of file Driver.h.
Referenced by clang::driver::toolchains::BareMetal::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::Hurd::AddClangSystemIncludeArgs(), clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), addDefaultIgnorelists(), clang::driver::toolchains::Generic_GCC::addLibCxxIncludePaths(), addPGOAndCoverageFlags(), computeBaseSysRoot(), clang::driver::tools::Clang::ConstructJob(), CreateTempFile(), DiagnoseInputExistence(), findAndroidArmMultilibs(), findBiarchMultilibs(), findCSKYMultilibs(), findMSP430Multilibs(), findRISCVBareMetalMultilibs(), findRISCVMultilibs(), clang::driver::toolchains::FreeBSD::FreeBSD(), clang::driver::toolchains::HexagonToolChain::getHexagonTargetDir(), clang::driver::toolchains::Hurd::getMultiarchTriple(), clang::driver::toolchains::Linux::getMultiarchTriple(), clang::driver::ToolChain::getVFS(), clang::driver::toolchains::HexagonToolChain::HexagonToolChain(), clang::driver::toolchains::Generic_GCC::GCCInstallationDetector::init(), clang::driver::toolchains::Linux::Linux(), maybeHasClangPchSignature(), parseSpecialCaseListArg(), renderDebugOptions(), clang::driver::RocmInstallationDetector::RocmInstallationDetector(), validateSpecialCaseListFormat(), and clang::driver::XRayArgs::XRayArgs().
HandleAutocompletions()
void Driver::HandleAutocompletions (StringRef PassedFlags) const
HandleAutocompletions - Handle –autocomplete by searching and printing possible flags, descriptions, and its arguments.
Definition at line 2507 of file Driver.cpp.
References clang::driver::options::CC1Option, clang::driver::options::ClangOption, clang::driver::options::FlangOption, getOpts(), clang::driver::options::Ignored, IsFlangMode(), and clang::driver::options::Unsupported.
Referenced by HandleImmediateArgs().
HandleImmediateArgs()
bool Driver::HandleImmediateArgs (const Compilation & C)
HandleImmediateArgs - Handle any arguments which should be treated before building actions or binding tools.
Returns
Whether any compilation should be built for this invocation.
Definition at line 2594 of file Driver.cpp.
References clang::driver::ToolChain::ComputeEffectiveClangTriple(), clang::driver::MultilibSet::expandFlags(), clang::driver::Multilib::gccSuffix(), clang::driver::ToolChain::getCompilerRT(), clang::driver::ToolChain::getCompilerRTPath(), clang::DiagnosticIDs::getDiagnosticFlags(), GetFilePath(), clang::driver::ToolChain::getFilePaths(), clang::driver::ToolChain::getMultilibFlags(), clang::driver::ToolChain::getMultilibs(), GetProgramPath(), clang::driver::ToolChain::getProgramPaths(), clang::driver::ToolChain::GetRuntimeLibType(), clang::driver::ToolChain::getRuntimePath(), clang::driver::ToolChain::getSelectedMultilibs(), GetStdModuleManifestPath(), clang::driver::ToolChain::getTripleString(), HandleAutocompletions(), PrefixDirs, PrintDiagnosticCategories(), PrintHelp(), PrintSYCLToolHelp(), clang::driver::ToolChain::printVerboseInfo(), PrintVersion(), ResourceDir, clang::driver::ToolChain::RLT_CompilerRT, clang::driver::ToolChain::RLT_Libgcc, SystemConfigDir, and UserConfigDir.
hasHeaderMode()
bool clang::driver::Driver::hasHeaderMode () const inline
Returns true if the user has indicated a C++20 header unit mode.
Definition at line 732 of file Driver.h.
References clang::driver::HeaderMode_None.
Referenced by BuildInputs().
IsCLMode()
bool clang::driver::Driver::IsCLMode () const inline
Whether the driver should follow cl.exe like behavior.
Definition at line 224 of file Driver.h.
Referenced by BuildCompilation(), BuildInputs(), CheckPreprocessingOptions(), clang::driver::tools::Clang::ConstructJob(), DiagnoseInputExistence(), clang::driver::Compilation::ExecuteJobs(), GetNamedOutputPath(), ParseArgStrings(), and renderDebugOptions().
isDumpDeviceCodeEnabled()
bool clang::driver::Driver::isDumpDeviceCodeEnabled () const inline
Definition at line 433 of file Driver.h.
Referenced by clang::driver::Compilation::CleanupFile().
IsDXCMode()
bool clang::driver::Driver::IsDXCMode () const inline
Whether the driver should follow dxc.exe like behavior.
Definition at line 231 of file Driver.h.
Referenced by BuildCompilation(), BuildInputs(), and GetNamedOutputPath().
IsFlangMode()
bool clang::driver::Driver::IsFlangMode () const inline
Whether the driver should invoke flang for fortran inputs.
Other modes fall back to calling gcc which in turn calls gfortran.
Definition at line 228 of file Driver.h.
Referenced by BuildInputs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), HandleAutocompletions(), clang::driver::ToolChain::LookupTypeForExtension(), PrintVersion(), and clang::driver::ToolChain::SelectTool().
IsFPGAEmulationMode()
bool clang::driver::Driver::IsFPGAEmulationMode () const inline
Definition at line 756 of file Driver.h.
References FPGAEmulationMode, and OffloadCompileMode.
IsFPGAHWMode()
bool clang::driver::Driver::IsFPGAHWMode () const inline
Definition at line 754 of file Driver.h.
References FPGAHWMode, and OffloadCompileMode.
isSaveTempsEnabled()
bool clang::driver::Driver::isSaveTempsEnabled () const inline
Definition at line 435 of file Driver.h.
Referenced by BuildActions(), ExecuteCompilation(), GetNamedOutputPath(), clang::driver::Compilation::initCompilationForDiagnostics(), and clang::driver::Compilation::~Compilation().
isSaveTempsObj()
bool clang::driver::Driver::isSaveTempsObj () const inline
Definition at line 436 of file Driver.h.
Referenced by GetNamedOutputPath().
isSYCLDefaultTripleImplied()
bool clang::driver::Driver::isSYCLDefaultTripleImplied () const inline
isSYCLDefaultTripleImplied - The default SYCL triple (spir64) has been added or should be added given proper criteria.
Definition at line 934 of file Driver.h.
isUsingLTO()
bool clang::driver::Driver::isUsingLTO (bool IsOffload = false) const inline
Returns true if we are performing any kind of LTO.
Definition at line 738 of file Driver.h.
References getLTOMode(), and clang::driver::LTOK_None.
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), and ConstructPhaseAction().
MakeSYCLDeviceTriple()
llvm::Triple Driver::MakeSYCLDeviceTriple (StringRef TargetArch = "spir64") const
MakeSYCLDeviceTriple - Returns the SYCL device triple for the specified subarch.
Definition at line 2395 of file Driver.cpp.
Referenced by CreateOffloadingDeviceToolChains(), and PrintSYCLToolHelp().
maybeGenerateCompilationDiagnostics()
bool clang::driver::Driver::maybeGenerateCompilationDiagnostics (CommandStatus CS, ReproLevel Level, Compilation & C, const Command & FailingCommand, StringRef AdditionalInformation = "", CompilationDiagnosticReport * GeneratedReport = nullptr) inline
Definition at line 574 of file Driver.h.
References Crash, generateCompilationDiagnostics(), clang::DiagnosticsEngine::Report(), and clang::DiagnosticsEngine::setLastDiagnosticIgnored().
offloadDeviceOnly()
bool clang::driver::Driver::offloadDeviceOnly () const inline
Definition at line 443 of file Driver.h.
Referenced by BuildOffloadingActions(), and ConstructPhaseAction().
offloadHostOnly()
bool clang::driver::Driver::offloadHostOnly () const inline
Definition at line 442 of file Driver.h.
Referenced by BuildOffloadingActions().
ParseArgStrings()
InputArgList Driver::ParseArgStrings (ArrayRef< const char * > Args, bool UseDriverMode, bool & ContainsError)
ParseArgStrings - Parse the given list of strings into an ArgList.
Definition at line 260 of file Driver.cpp.
References clang::driver::options::CC1Option, clang::driver::options::Deprecated, Diag(), clang::DiagnosticsEngine::getDiagnosticLevel(), getOpts(), IsCLMode(), clang::DiagnosticsEngine::Report(), clang::driver::options::Unsupported, Used, and clang::DiagnosticsEngine::Warning.
Referenced by BuildCompilation().
populateSYCLDeviceTraitsMacrosArgs()
void Driver::populateSYCLDeviceTraitsMacrosArgs (const llvm::opt::ArgList & Args, const llvm::SmallVector< llvm::Triple, 4 > & UniqueSYCLTriplesVec)
Reads device config file to find information about the SYCL targets in UniqueSYCLTriplesVec, and defines device traits macros accordingly.
Definition at line 10421 of file Driver.cpp.
Referenced by CreateOffloadingDeviceToolChains().
PrintActions()
void Driver::PrintActions (const Compilation & C) const
PrintActions - Print the list of actions.
Definition at line 2898 of file Driver.cpp.
References PrintActions1().
PrintHelp()
void Driver::PrintHelp (bool ShowHidden) const
PrintHelp - Print the help text.
Parameters
ShowHidden - Show hidden options.
Definition at line 2386 of file Driver.cpp.
References DriverTitle, getOpts(), and Name.
Referenced by HandleImmediateArgs().
PrintSYCLToolHelp()
void Driver::PrintSYCLToolHelp (const Compilation & C) const
PrintSYCLToolHelp - Print help text from offline compiler tools.
Definition at line 2412 of file Driver.cpp.
References MakeSYCLDeviceTriple(), and clang::T.
Referenced by HandleImmediateArgs().
PrintVersion()
void Driver::PrintVersion (const Compilation & C, raw_ostream & OS) const
PrintVersion - Print the driver version.
Definition at line 2464 of file Driver.cpp.
References Dir, clang::getClangFullVersion(), clang::getClangToolFullVersion(), clang::driver::ToolChain::getThreadModel(), clang::driver::ToolChain::getTripleString(), IsFlangMode(), and clang::driver::ToolChain::isThreadModelSupported().
Referenced by generateCompilationDiagnostics(), and HandleImmediateArgs().
setCheckInputsExist()
void clang::driver::Driver::setCheckInputsExist (bool Value) inline
Definition at line 409 of file Driver.h.
Referenced by clang::createInvocation().
setFlangF128MathLibrary()
void clang::driver::Driver::setFlangF128MathLibrary (std::string name) inline
Definition at line 445 of file Driver.h.
References FlangF128MathLibrary, and clang::transformer::name().
setOffloadCompileMode()
void clang::driver::Driver::setOffloadCompileMode (DeviceMode ModeValue) inline
Definition at line 760 of file Driver.h.
References OffloadCompileMode.
setPrependArg()
void clang::driver::Driver::setPrependArg (const char * Value) inline
Definition at line 415 of file Driver.h.
setProbePrecompiled()
void clang::driver::Driver::setProbePrecompiled (bool Value) inline
Definition at line 412 of file Driver.h.
Referenced by clang::createInvocation().
setTargetAndMode()
void clang::driver::Driver::setTargetAndMode (const ParsedClangName & TM) inline
Definition at line 417 of file Driver.h.
References ClangNameParts.
setTitle()
void clang::driver::Driver::setTitle (std::string Value) inline
Definition at line 420 of file Driver.h.
References DriverTitle.
Referenced by newDriver().
ShouldEmitStaticLibrary()
bool Driver::ShouldEmitStaticLibrary (const llvm::opt::ArgList & Args) const
ShouldEmitStaticLibrary - Should the linker emit a static library.
Definition at line 10196 of file Driver.cpp.
ShouldUseClangCompiler()
bool Driver::ShouldUseClangCompiler (const JobAction & JA) const
ShouldUseClangCompiler - Should the clang compiler be used to handle this action.
Definition at line 10167 of file Driver.cpp.
References clang::driver::Action::input_begin(), clang::driver::types::isAcceptedByClang(), and clang::driver::Action::size().
ShouldUseFlangCompiler()
bool Driver::ShouldUseFlangCompiler (const JobAction & JA) const
ShouldUseFlangCompiler - Should the flang compiler be used to handle this action.
Definition at line 10182 of file Driver.cpp.
References clang::driver::Action::input_begin(), clang::driver::types::isAcceptedByFlang(), and clang::driver::Action::size().
Member Data Documentation
CC1Main
CC1ToolFunc clang::driver::Driver::CC1Main = nullptr
Definition at line 284 of file Driver.h.
CCCPrintBindings
unsigned clang::driver::Driver::CCCPrintBindings
Only print tool bindings, don't build any jobs.
Definition at line 235 of file Driver.h.
Referenced by BuildCompilation().
CCGenDiagnostics
unsigned clang::driver::Driver::CCGenDiagnostics
Whether the driver is generating diagnostics for debugging purposes.
Definition at line 266 of file Driver.h.
Referenced by BuildInputs(), ConstructPhaseAction(), CreateTempFile(), generateCompilationDiagnostics(), getFinalPhase(), and GetNamedOutputPath().
CCLogDiagnostics
unsigned clang::driver::Driver::CCLogDiagnostics
Set CC_LOG_DIAGNOSTICS mode, which causes the frontend to log diagnostics to CCLogDiagnosticsFilename or to stderr, in a stable machine readable format.
Definition at line 262 of file Driver.h.
CCLogDiagnosticsFilename
std::string clang::driver::Driver::CCLogDiagnosticsFilename
The file to log CC_LOG_DIAGNOSTICS output to, if enabled.
Definition at line 206 of file Driver.h.
CCPrintHeadersFilename
std::string clang::driver::Driver::CCPrintHeadersFilename
The file to log CC_PRINT_HEADERS output to, if enabled.
Definition at line 203 of file Driver.h.
CCPrintHeadersFiltering
HeaderIncludeFilteringKind clang::driver::Driver::CCPrintHeadersFiltering = HIFIL_None
This flag determines whether clang should filter the header information that is emitted.
If enviroment variable CC_PRINT_HEADERS_FILTERING is set to "only-direct-system", only system headers that are directly included from non-system headers are emitted.
Definition at line 251 of file Driver.h.
CCPrintHeadersFormat
HeaderIncludeFormatKind clang::driver::Driver::CCPrintHeadersFormat = HIFMT_None
The format of the header information that is emitted.
If CC_PRINT_HEADERS is set, the format is textual. Otherwise, the format is determined by the enviroment variable CC_PRINT_HEADERS_FORMAT.
Definition at line 245 of file Driver.h.
CCPrintInternalStatReportFilename
std::string clang::driver::Driver::CCPrintInternalStatReportFilename
The file to log CC_PRINT_INTERNAL_STAT_FILE output to, if enabled.
Definition at line 197 of file Driver.h.
Referenced by clang::driver::tools::getStatsFileName().
CCPrintInternalStats
unsigned clang::driver::Driver::CCPrintInternalStats
Set CC_PRINT_INTERNAL_STAT mode, which causes the driver to dump internal performance report to CC_PRINT_INTERNAL_STAT_FILE or to stdout.
Definition at line 276 of file Driver.h.
Referenced by clang::driver::tools::getStatsFileName().
CCPrintOptions
unsigned clang::driver::Driver::CCPrintOptions
Set CC_PRINT_OPTIONS mode, which is like -v but logs the commands to CCPrintOptionsFilename or to stderr.
Definition at line 240 of file Driver.h.
CCPrintOptionsFilename
std::string clang::driver::Driver::CCPrintOptionsFilename
The file to log CC_PRINT_OPTIONS output to, if enabled.
Definition at line 200 of file Driver.h.
CCPrintProcessStats
unsigned clang::driver::Driver::CCPrintProcessStats
Set CC_PRINT_PROC_STAT mode, which causes the driver to dump performance report to CC_PRINT_PROC_STAT_FILE or to stdout.
Definition at line 271 of file Driver.h.
Referenced by BuildCompilation(), and BuildJobs().
CCPrintStatReportFilename
std::string clang::driver::Driver::CCPrintStatReportFilename
The file to log CC_PRINT_PROC_STAT_FILE output to, if enabled.
Definition at line 194 of file Driver.h.
Referenced by BuildCompilation(), and BuildJobs().
ClangExecutable
std::string clang::driver::Driver::ClangExecutable
The original path to the clang executable.
Definition at line 160 of file Driver.h.
Referenced by BuildCompilation(), clang::driver::tools::aix::Linker::ConstructJob(), Driver(), and getClangProgramPath().
ClangNameParts
ParsedClangName clang::driver::Driver::ClangNameParts
Target and driver mode components extracted from clang executable name.
Definition at line 163 of file Driver.h.
Referenced by setTargetAndMode().
Dir
std::string clang::driver::Driver::Dir
The path the driver executable was in, as invoked from the command line.
Definition at line 157 of file Driver.h.
Referenced by clang::driver::toolchains::Fuchsia::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::OHOS::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::NaClToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::NaClToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::HexagonToolChain::addLibStdCxxIncludePaths(), clang::driver::tools::AddStaticDeviceLibs(), BuildCompilation(), computeBaseSysRoot(), clang::driver::toolchains::Linux::computeSysRoot(), clang::driver::toolchains::OHOS::computeSysRoot(), constructHexagonLinkArgs(), clang::driver::tools::LinkerWrapper::ConstructJob(), Driver(), findClangRelativeSysroot(), GetFilePath(), clang::driver::toolchains::HexagonToolChain::getHexagonLibraryPaths(), getInstalledDir(), clang::driver::ToolChain::getStdlibPath(), clang::driver::toolchains::RISCVToolChain::hasGCCToolchain(), clang::driver::toolchains::HexagonToolChain::HexagonToolChain(), clang::driver::toolchains::Generic_GCC::GCCInstallationDetector::init(), PrintVersion(), clang::driver::toolchains::PS4PS5Base::PS4PS5Base(), ScanDirForExecutable(), clang::driver::SYCLInstallationDetector::SYCLInstallationDetector(), and testTriple().
DriverTitle
std::string clang::driver::Driver::DriverTitle
Driver title to use with help.
Definition at line 188 of file Driver.h.
Referenced by getTitle(), PrintHelp(), and setTitle().
DyldPrefix
std::string clang::driver::Driver::DyldPrefix
Dynamic loader prefix, if present.
Definition at line 185 of file Driver.h.
Referenced by BuildCompilation(), clang::driver::tools::fuchsia::Linker::ConstructJob(), and clang::driver::tools::gnutools::Linker::ConstructJob().
FlangF128MathLibrary
std::string clang::driver::Driver::FlangF128MathLibrary
Name of the library that provides implementations of IEEE-754 128-bit float math functions used by Fortran F128 runtime library.
It should be linked as needed by the linker job.
Definition at line 256 of file Driver.h.
Referenced by getFlangF128MathLibrary(), and setFlangF128MathLibrary().
HostBits
std::string clang::driver::Driver::HostBits
Information about the host which can be overridden by the user.
Definition at line 191 of file Driver.h.
HostMachine
std::string clang::driver::Driver::HostMachine
Definition at line 191 of file Driver.h.
HostRelease
std::string clang::driver::Driver::HostRelease
Definition at line 191 of file Driver.h.
HostSystem
std::string clang::driver::Driver::HostSystem
Definition at line 191 of file Driver.h.
Name
std::string clang::driver::Driver::Name
The name the driver was invoked as.
Definition at line 153 of file Driver.h.
Referenced by BuildCompilation(), Driver(), generateCompilationDiagnostics(), GetFilePath(), GetNamedOutputPath(), GetProgramPath(), PrintHelp(), and ScanDirForExecutable().
OffloadCompileMode
enum clang::driver::Driver::DeviceMode clang::driver::Driver::OffloadCompileMode = UnsetDeviceMode
Referenced by getOffloadCompileMode(), IsFPGAEmulationMode(), IsFPGAHWMode(), and setOffloadCompileMode().
PrefixDirs
prefix_list clang::driver::Driver::PrefixDirs
Definition at line 179 of file Driver.h.
Referenced by clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::HexagonToolChain::addLibStdCxxIncludePaths(), BuildCompilation(), constructHexagonLinkArgs(), GetFilePath(), clang::driver::toolchains::HexagonToolChain::getHexagonLibraryPaths(), GetProgramPath(), HandleImmediateArgs(), and clang::driver::toolchains::HexagonToolChain::HexagonToolChain().
ResourceDir
std::string clang::driver::Driver::ResourceDir
The path to the compiler resource directory.
Definition at line 166 of file Driver.h.
Referenced by clang::driver::toolchains::AIX::AddClangSystemIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::DarwinClang::AddClangSystemIncludeArgs(), clang::driver::toolchains::DragonFly::AddClangSystemIncludeArgs(), clang::driver::toolchains::FreeBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangSystemIncludeArgs(), clang::driver::toolchains::Haiku::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Hurd::AddClangSystemIncludeArgs(), clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), clang::driver::toolchains::MipsLLVMToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::NaClToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::NetBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::OHOS::AddClangSystemIncludeArgs(), clang::driver::toolchains::OpenBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::PPCFreeBSDToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::PPCLinuxToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::PS4PS5Base::AddClangSystemIncludeArgs(), clang::driver::toolchains::Solaris::AddClangSystemIncludeArgs(), clang::driver::toolchains::ZOS::AddClangSystemIncludeArgs(), clang::driver::CudaInstallationDetector::AddCudaIncludeArgs(), addDefaultIgnorelists(), clang::driver::RocmInstallationDetector::AddHIPIncludeArgs(), BuildCompilation(), clang::driver::tools::Flang::ConstructJob(), Driver(), GetFilePath(), clang::driver::ToolChain::getRuntimePath(), HandleImmediateArgs(), and RenderModulesOptions().
SysRoot
std::string clang::driver::Driver::SysRoot
sysroot, if present
Definition at line 182 of file Driver.h.
Referenced by clang::driver::toolchains::CrossWindowsToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::DragonFly::AddClangSystemIncludeArgs(), clang::driver::toolchains::FreeBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangSystemIncludeArgs(), clang::driver::toolchains::Haiku::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::NetBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::OpenBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::Solaris::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::addLibCxxIncludePaths(), BuildCompilation(), computeBaseSysRoot(), clang::driver::ToolChain::computeSysRoot(), clang::driver::toolchains::Linux::computeSysRoot(), clang::driver::toolchains::MipsLLVMToolChain::computeSysRoot(), clang::driver::toolchains::OHOS::computeSysRoot(), constructHexagonLinkArgs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::CrossWindows::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), Driver(), clang::driver::toolchains::AVRToolChain::findAVRLibcInstallation(), clang::driver::toolchains::Fuchsia::Fuchsia(), GetFilePath(), clang::driver::SYCLInstallationDetector::getSYCLDeviceLibPath(), clang::driver::Compilation::getSysRoot(), clang::driver::toolchains::Generic_GCC::GCCInstallationDetector::init(), clang::driver::toolchains::MinGW::MinGW(), and testTriple().
SystemConfigDir
std::string clang::driver::Driver::SystemConfigDir
System directory for config files.
Definition at line 169 of file Driver.h.
Referenced by Driver(), and HandleImmediateArgs().
UserConfigDir
std::string clang::driver::Driver::UserConfigDir
User directory for config files.
Definition at line 172 of file Driver.h.
Referenced by Driver(), and HandleImmediateArgs().
The documentation for this class was generated from the following files:
include/clang/Driver/Driver.h
lib/Driver/Driver.cpp
lib/Driver/ToolChains/Clang.cpp