clang: clang::AttributeCommonInfo::Form Class Reference
clang::AttributeCommonInfo::Form Class Reference
Combines information about the source-code form of an attribute, including its syntax and spelling.
#include "clang/Basic/AttributeCommonInfo.h"
Public Member Functions
constexpr Form (Syntax SyntaxUsed, unsigned SpellingIndex, bool IsAlignas, bool IsRegularKeywordAttribute)
constexpr Form (tok::TokenKind Tok)
Syntax getSyntax () const
unsigned getSpellingIndex () const
bool isAlignas () const
bool isRegularKeywordAttribute () const
Static Public Member Functions
static Form GNU ()
static Form CXX11 ()
static Form C23 ()
static Form Declspec ()
static Form Microsoft ()
static Form Keyword (bool IsAlignas, bool IsRegularKeywordAttribute)
static Form Pragma ()
static Form ContextSensitiveKeyword ()
static Form HLSLAnnotation ()
static Form Implicit ()
Detailed Description
Combines information about the source-code form of an attribute, including its syntax and spelling.
Definition at line 95 of file AttributeCommonInfo.h.
Constructor & Destructor Documentation
Form() [1/2]
constexpr clang::AttributeCommonInfo::Form::Form (Syntax SyntaxUsed, unsigned SpellingIndex, bool IsAlignas, bool IsRegularKeywordAttribute) inline constexpr
Definition at line 97 of file AttributeCommonInfo.h.
Referenced by Keyword().
Form() [2/2]
constexpr clang::AttributeCommonInfo::Form::Form (tok::TokenKind Tok) inline constexpr
Definition at line 102 of file AttributeCommonInfo.h.
Member Function Documentation
C23()
static Form clang::AttributeCommonInfo::Form::C23 () inline static
Definition at line 114 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_C23.
ContextSensitiveKeyword()
static Form clang::AttributeCommonInfo::Form::ContextSensitiveKeyword () inline static
Definition at line 122 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_ContextSensitiveKeyword.
Referenced by addContextSensitiveTypeNullability().
CXX11()
static Form clang::AttributeCommonInfo::Form::CXX11 () inline static
Definition at line 113 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_CXX11.
Declspec()
static Form clang::AttributeCommonInfo::Form::Declspec () inline static
Definition at line 115 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_Declspec.
getSpellingIndex()
unsigned clang::AttributeCommonInfo::Form::getSpellingIndex () const inline
Definition at line 108 of file AttributeCommonInfo.h.
getSyntax()
Syntax clang::AttributeCommonInfo::Form::getSyntax () const inline
Definition at line 107 of file AttributeCommonInfo.h.
GNU()
static Form clang::AttributeCommonInfo::Form::GNU () inline static
Definition at line 112 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_GNU.
HLSLAnnotation()
static Form clang::AttributeCommonInfo::Form::HLSLAnnotation () inline static
Definition at line 123 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_HLSLAnnotation.
Implicit()
static Form clang::AttributeCommonInfo::Form::Implicit () inline static
Definition at line 124 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_Implicit.
isAlignas()
bool clang::AttributeCommonInfo::Form::isAlignas () const inline
Definition at line 109 of file AttributeCommonInfo.h.
isRegularKeywordAttribute()
bool clang::AttributeCommonInfo::Form::isRegularKeywordAttribute () const inline
Definition at line 110 of file AttributeCommonInfo.h.
Keyword()
static Form clang::AttributeCommonInfo::Form::Keyword (bool IsAlignas, bool IsRegularKeywordAttribute) inline static
Definition at line 117 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_Keyword, Form(), and clang::AttributeCommonInfo::SpellingNotCalculated.
Microsoft()
static Form clang::AttributeCommonInfo::Form::Microsoft () inline static
Definition at line 116 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_Microsoft.
Pragma()
static Form clang::AttributeCommonInfo::Form::Pragma () inline static
Definition at line 121 of file AttributeCommonInfo.h.
References clang::AttributeCommonInfo::AS_Pragma.
Referenced by clang::Sema::AddCFAuditedAttribute().
The documentation for this class was generated from the following file:
include/clang/Basic/AttributeCommonInfo.h