clang: clang::IncrementalCompilerBuilder Class Reference
clang::IncrementalCompilerBuilder Class Reference
Create a pre-configured CompilerInstance for incremental processing.
#include "clang/Interpreter/Interpreter.h"
Static Public Member Functions
static llvm::Expected< std::unique_ptr< CompilerInstance > > create (std::vector< const char * > &ClangArgv)
Detailed Description
Create a pre-configured CompilerInstance for incremental processing.
Definition at line 41 of file Interpreter.h.
Member Function Documentation
create()
llvm::Expected< std::unique_ptr< CompilerInstance > > IncrementalCompilerBuilder::create (std::vector< const char * > & ClangArgv) static
Definition at line 125 of file Interpreter.cpp.
References clang::driver::Driver::BuildCompilation(), clang::CreateAndPopulateDiagOpts(), clang::driver::Driver::setCheckInputsExist(), and string().
The documentation for this class was generated from the following files:
include/clang/Interpreter/Interpreter.h
lib/Interpreter/Interpreter.cpp