clang: clang::ComparisonCategories Class Reference
clang::ComparisonCategories Class Reference
#include "clang/AST/ComparisonCategories.h"
Public Member Functions
const ComparisonCategoryInfo & getInfo (ComparisonCategoryType Kind) const
Return the comparison category information for the category specified by 'Kind'.
const ComparisonCategoryInfo & getInfoForType (QualType Ty) const
Return the comparison category information as specified by getCategoryForType(Ty).
const ComparisonCategoryInfo * lookupInfo (ComparisonCategoryType Kind) const
Return the cached comparison category information for the specified 'Kind'.
ComparisonCategoryInfo * lookupInfo (ComparisonCategoryType Kind)
const ComparisonCategoryInfo * lookupInfoForType (QualType Ty) const
Static Public Member Functions
static StringRef getCategoryString (ComparisonCategoryType Kind)
static StringRef getResultString (ComparisonCategoryResult Kind)
static std::vector< ComparisonCategoryResult > getPossibleResultsForType (ComparisonCategoryType Type)
Return the list of results which are valid for the specified comparison category type.
Friends
class ASTContext
Detailed Description
Definition at line 173 of file ComparisonCategories.h.
Member Function Documentation
getCategoryString()
StringRef ComparisonCategories::getCategoryString (ComparisonCategoryType Kind) static
Definition at line 171 of file ComparisonCategories.cpp.
References clang::ComparisonCategoryInfo::Kind.
Referenced by clang::Sema::CheckComparisonCategoryType().
getInfo()
const ComparisonCategoryInfo& clang::ComparisonCategories::getInfo (ComparisonCategoryType Kind) const inline
Return the comparison category information for the category specified by 'Kind'.
Definition at line 185 of file ComparisonCategories.h.
References lookupInfo().
getInfoForType()
const ComparisonCategoryInfo & ComparisonCategories::getInfoForType (QualType Ty) const
Return the comparison category information as specified by getCategoryForType(Ty).
If the information is not already cached, the declaration is looked up and a cache entry is created. NOTE: Lookup is expected to succeed. Use lookupInfo if failure is possible.
Definition at line 160 of file ComparisonCategories.cpp.
getPossibleResultsForType()
std::vector< ComparisonCategoryResult > ComparisonCategories::getPossibleResultsForType (ComparisonCategoryType Type) static
Return the list of results which are valid for the specified comparison category type.
Definition at line 202 of file ComparisonCategories.cpp.
Referenced by clang::Sema::CheckComparisonCategoryType().
getResultString()
StringRef ComparisonCategories::getResultString (ComparisonCategoryResult Kind) static
Definition at line 184 of file ComparisonCategories.cpp.
References clang::ComparisonCategoryInfo::Kind.
Referenced by clang::Sema::CheckComparisonCategoryType().
lookupInfo() [1/2]
ComparisonCategoryInfo* clang::ComparisonCategories::lookupInfo (ComparisonCategoryType Kind) inline
Definition at line 206 of file ComparisonCategories.h.
References clang::interp::This().
lookupInfo() [2/2]
const ComparisonCategoryInfo * ComparisonCategories::lookupInfo (ComparisonCategoryType Kind) const
Return the cached comparison category information for the specified 'Kind'.
If no cache entry is present the comparison category type is looked up. If lookup fails nullptr is returned. Otherwise, a new cache entry is created and returned
Definition at line 112 of file ComparisonCategories.cpp.
References clang::ComparisonCategoryInfo::Kind, lookupCXXRecordDecl(), and lookupStdNamespace().
Referenced by clang::Sema::CheckComparisonCategoryType(), and getInfo().
lookupInfoForType()
const ComparisonCategoryInfo * ComparisonCategories::lookupInfoForType (QualType Ty) const
Definition at line 125 of file ComparisonCategories.cpp.
References End, clang::Type::getAsCXXRecordDecl(), clang::CXXRecordDecl::getCanonicalDecl(), clang::QualType::isNull(), clang::ComparisonCategoryInfo::Kind, and clang::ComparisonCategoryInfo::Record.
Referenced by clang::Sema::BuildSynthesizedThreeWayComparison().
Friends And Related Function Documentation
ASTContext
friend class ASTContext friend
Definition at line 214 of file ComparisonCategories.h.
The documentation for this class was generated from the following files:
include/clang/AST/ComparisonCategories.h
lib/AST/ComparisonCategories.cpp