clang: clang::concepts::ExprRequirement Class Reference
clang::concepts::ExprRequirement Class Reference
A requires-expression requirement which queries the validity and properties of an expression ('simple' and 'compound' requirements).
#include "clang/AST/ExprConcepts.h"
Classes
class ReturnTypeRequirement
Public Types
enum SatisfactionStatus {
SS_Dependent , SS_ExprSubstitutionFailure , SS_NoexceptNotMet , SS_TypeRequirementSubstitutionFailure ,
SS_ConstraintsNotSatisfied , SS_Satisfied
}
Public Types inherited from clang::concepts::Requirement
enum RequirementKind { RK_Type , RK_Simple , RK_Compound , RK_Nested }
Public Member Functions
ExprRequirement (Expr *E, bool IsSimple, SourceLocation NoexceptLoc, ReturnTypeRequirement Req, SatisfactionStatus Status, ConceptSpecializationExpr *SubstitutedConstraintExpr=nullptr)
Construct a compound requirement.
ExprRequirement (SubstitutionDiagnostic *E, bool IsSimple, SourceLocation NoexceptLoc, ReturnTypeRequirement Req={})
Construct a compound requirement whose expression was a substitution failure.
bool isSimple () const
bool isCompound () const
bool hasNoexceptRequirement () const
SourceLocation getNoexceptLoc () const
SatisfactionStatus getSatisfactionStatus () const
bool isExprSubstitutionFailure () const
const ReturnTypeRequirement & getReturnTypeRequirement () const
ConceptSpecializationExpr * getReturnTypeRequirementSubstitutedConstraintExpr () const
SubstitutionDiagnostic * getExprSubstitutionDiagnostic () const
Expr * getExpr () const
Public Member Functions inherited from clang::concepts::Requirement
Requirement (RequirementKind Kind, bool IsDependent, bool ContainsUnexpandedParameterPack, bool IsSatisfied=true)
RequirementKind getKind () const
bool isSatisfied () const
void setSatisfied (bool IsSatisfied)
void setDependent (bool IsDependent)
bool isDependent () const
void setContainsUnexpandedParameterPack (bool Contains)
bool containsUnexpandedParameterPack () const
Static Public Member Functions
static bool classof (const Requirement *R)
Public Attributes
friend ASTStmtReader
friend ASTStmtWriter
Detailed Description
A requires-expression requirement which queries the validity and properties of an expression ('simple' and 'compound' requirements).
Definition at line 280 of file ExprConcepts.h.
Member Enumeration Documentation
SatisfactionStatus
enum clang::concepts::ExprRequirement::SatisfactionStatus
Enumerator
SS_Dependent
SS_ExprSubstitutionFailure
SS_NoexceptNotMet
SS_TypeRequirementSubstitutionFailure
SS_ConstraintsNotSatisfied
SS_Satisfied
Definition at line 282 of file ExprConcepts.h.
Constructor & Destructor Documentation
ExprRequirement() [1/2]
concepts::ExprRequirement::ExprRequirement (Expr * E, bool IsSimple, SourceLocation NoexceptLoc, ReturnTypeRequirement Req, SatisfactionStatus Status, ConceptSpecializationExpr * SubstitutedConstraintExpr = nullptr)
Construct a compound requirement.
Parameters
E the expression which is checked by this requirement.
IsSimple whether this was a simple requirement in source.
NoexceptLoc the location of the noexcept keyword, if it was specified, otherwise an empty location.
Req the requirement for the type of the checked expression.
Status the satisfaction status of this requirement.
Definition at line 1639 of file SemaConcept.cpp.
ExprRequirement() [2/2]
concepts::ExprRequirement::ExprRequirement (SubstitutionDiagnostic * E, bool IsSimple, SourceLocation NoexceptLoc, ReturnTypeRequirement Req = {})
Construct a compound requirement whose expression was a substitution failure.
The requirement is not satisfied.
Parameters
E the diagnostic emitted while instantiating the original expression.
IsSimple whether this was a simple requirement in source.
NoexceptLoc the location of the noexcept keyword, if it was specified, otherwise an empty location.
Req the requirement for the type of the checked expression (omit if no requirement was specified).
Definition at line 1657 of file SemaConcept.cpp.
Member Function Documentation
classof()
static bool clang::concepts::ExprRequirement::classof (const Requirement * R) inline static
Definition at line 422 of file ExprConcepts.h.
References clang::concepts::Requirement::getKind(), clang::concepts::Requirement::RK_Compound, and clang::concepts::Requirement::RK_Simple.
getExpr()
Expr* clang::concepts::ExprRequirement::getExpr () const inline
Definition at line 415 of file ExprConcepts.h.
References isExprSubstitutionFailure().
Referenced by clang::TreeTransform< Derived >::TransformExprRequirement(), and clang::RecursiveASTVisitor< Derived >::TraverseConceptExprRequirement().
getExprSubstitutionDiagnostic()
SubstitutionDiagnostic* clang::concepts::ExprRequirement::getExprSubstitutionDiagnostic () const inline
Definition at line 408 of file ExprConcepts.h.
References isExprSubstitutionFailure().
Referenced by clang::TreeTransform< Derived >::TransformExprRequirement().
getNoexceptLoc()
SourceLocation clang::concepts::ExprRequirement::getNoexceptLoc () const inline
Definition at line 390 of file ExprConcepts.h.
Referenced by clang::TreeTransform< Derived >::TransformExprRequirement().
getReturnTypeRequirement()
const ReturnTypeRequirement& clang::concepts::ExprRequirement::getReturnTypeRequirement () const inline
Definition at line 398 of file ExprConcepts.h.
Referenced by clang::TreeTransform< Derived >::TransformExprRequirement(), and clang::RecursiveASTVisitor< Derived >::TraverseConceptExprRequirement().
getReturnTypeRequirementSubstitutedConstraintExpr()
ConceptSpecializationExpr* clang::concepts::ExprRequirement::getReturnTypeRequirementSubstitutedConstraintExpr () const inline
Definition at line 403 of file ExprConcepts.h.
References SS_TypeRequirementSubstitutionFailure.
getSatisfactionStatus()
SatisfactionStatus clang::concepts::ExprRequirement::getSatisfactionStatus () const inline
Definition at line 392 of file ExprConcepts.h.
hasNoexceptRequirement()
bool clang::concepts::ExprRequirement::hasNoexceptRequirement () const inline
Definition at line 389 of file ExprConcepts.h.
References clang::SourceLocation::isValid().
isCompound()
bool clang::concepts::ExprRequirement::isCompound () const inline
Definition at line 387 of file ExprConcepts.h.
References clang::concepts::Requirement::getKind(), and clang::concepts::Requirement::RK_Compound.
isExprSubstitutionFailure()
bool clang::concepts::ExprRequirement::isExprSubstitutionFailure () const inline
Definition at line 394 of file ExprConcepts.h.
References SS_ExprSubstitutionFailure.
Referenced by getExpr(), getExprSubstitutionDiagnostic(), clang::TreeTransform< Derived >::TransformExprRequirement(), and clang::RecursiveASTVisitor< Derived >::TraverseConceptExprRequirement().
isSimple()
bool clang::concepts::ExprRequirement::isSimple () const inline
Definition at line 386 of file ExprConcepts.h.
References clang::concepts::Requirement::getKind(), and clang::concepts::Requirement::RK_Simple.
Referenced by clang::TreeTransform< Derived >::TransformExprRequirement().
Member Data Documentation
ASTStmtReader
friend clang::concepts::ExprRequirement::ASTStmtReader
Definition at line 359 of file ExprConcepts.h.
ASTStmtWriter
friend clang::concepts::ExprRequirement::ASTStmtWriter
Definition at line 360 of file ExprConcepts.h.
The documentation for this class was generated from the following files:
include/clang/AST/ExprConcepts.h
lib/Sema/SemaConcept.cpp