clang: clang::interp::Compiler< Emitter > Class Template Reference
clang::interp::Compiler< Emitter > Class Template Reference
Compilation context for expressions.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Compiler.h"
Public Member Functions
template<typename... Tys>
Compiler (Context &Ctx, Program &P, Tys &&...Args)
Initializes the compiler and the backend emitter.
bool VisitCastExpr (const CastExpr *E)
bool VisitIntegerLiteral (const IntegerLiteral *E)
bool VisitFloatingLiteral (const FloatingLiteral *E)
bool VisitImaginaryLiteral (const ImaginaryLiteral *E)
bool VisitParenExpr (const ParenExpr *E)
bool VisitBinaryOperator (const BinaryOperator *E)
bool VisitLogicalBinOp (const BinaryOperator *E)
bool VisitPointerArithBinOp (const BinaryOperator *E)
Perform addition/subtraction of a pointer and an integer or subtraction of two pointers.
bool VisitComplexBinOp (const BinaryOperator *E)
bool VisitCXXDefaultArgExpr (const CXXDefaultArgExpr *E)
bool VisitCallExpr (const CallExpr *E)
bool VisitBuiltinCallExpr (const CallExpr *E)
bool VisitCXXDefaultInitExpr (const CXXDefaultInitExpr *E)
bool VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr *E)
bool VisitCXXNullPtrLiteralExpr (const CXXNullPtrLiteralExpr *E)
bool VisitGNUNullExpr (const GNUNullExpr *E)
bool VisitCXXThisExpr (const CXXThisExpr *E)
bool VisitUnaryOperator (const UnaryOperator *E)
bool VisitComplexUnaryOperator (const UnaryOperator *E)
bool VisitDeclRefExpr (const DeclRefExpr *E)
bool VisitImplicitValueInitExpr (const ImplicitValueInitExpr *E)
bool VisitSubstNonTypeTemplateParmExpr (const SubstNonTypeTemplateParmExpr *E)
bool VisitArraySubscriptExpr (const ArraySubscriptExpr *E)
bool VisitInitListExpr (const InitListExpr *E)
bool VisitCXXParenListInitExpr (const CXXParenListInitExpr *E)
bool VisitConstantExpr (const ConstantExpr *E)
bool VisitUnaryExprOrTypeTraitExpr (const UnaryExprOrTypeTraitExpr *E)
bool VisitMemberExpr (const MemberExpr *E)
bool VisitArrayInitIndexExpr (const ArrayInitIndexExpr *E)
bool VisitArrayInitLoopExpr (const ArrayInitLoopExpr *E)
bool VisitOpaqueValueExpr (const OpaqueValueExpr *E)
bool VisitAbstractConditionalOperator (const AbstractConditionalOperator *E)
bool VisitStringLiteral (const StringLiteral *E)
bool VisitObjCStringLiteral (const ObjCStringLiteral *E)
bool VisitObjCEncodeExpr (const ObjCEncodeExpr *E)
bool VisitSYCLUniqueStableNameExpr (const SYCLUniqueStableNameExpr *E)
bool VisitCharacterLiteral (const CharacterLiteral *E)
bool VisitCompoundAssignOperator (const CompoundAssignOperator *E)
bool VisitFloatCompoundAssignOperator (const CompoundAssignOperator *E)
bool VisitPointerCompoundAssignOperator (const CompoundAssignOperator *E)
bool VisitExprWithCleanups (const ExprWithCleanups *E)
bool VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr *E)
bool VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr *E)
bool VisitCompoundLiteralExpr (const CompoundLiteralExpr *E)
bool VisitTypeTraitExpr (const TypeTraitExpr *E)
bool VisitArrayTypeTraitExpr (const ArrayTypeTraitExpr *E)
bool VisitLambdaExpr (const LambdaExpr *E)
bool VisitPredefinedExpr (const PredefinedExpr *E)
bool VisitCXXThrowExpr (const CXXThrowExpr *E)
bool VisitCXXReinterpretCastExpr (const CXXReinterpretCastExpr *E)
bool VisitCXXNoexceptExpr (const CXXNoexceptExpr *E)
bool VisitCXXConstructExpr (const CXXConstructExpr *E)
bool VisitSourceLocExpr (const SourceLocExpr *E)
bool VisitOffsetOfExpr (const OffsetOfExpr *E)
bool VisitCXXScalarValueInitExpr (const CXXScalarValueInitExpr *E)
bool VisitSizeOfPackExpr (const SizeOfPackExpr *E)
bool VisitGenericSelectionExpr (const GenericSelectionExpr *E)
bool VisitChooseExpr (const ChooseExpr *E)
bool VisitEmbedExpr (const EmbedExpr *E)
bool VisitObjCBoolLiteralExpr (const ObjCBoolLiteralExpr *E)
bool VisitCXXInheritedCtorInitExpr (const CXXInheritedCtorInitExpr *E)
bool VisitExpressionTraitExpr (const ExpressionTraitExpr *E)
bool VisitCXXUuidofExpr (const CXXUuidofExpr *E)
bool VisitRequiresExpr (const RequiresExpr *E)
bool VisitConceptSpecializationExpr (const ConceptSpecializationExpr *E)
bool VisitCXXRewrittenBinaryOperator (const CXXRewrittenBinaryOperator *E)
bool VisitPseudoObjectExpr (const PseudoObjectExpr *E)
bool VisitPackIndexingExpr (const PackIndexingExpr *E)
bool VisitRecoveryExpr (const RecoveryExpr *E)
bool VisitAddrLabelExpr (const AddrLabelExpr *E)
bool VisitConvertVectorExpr (const ConvertVectorExpr *E)
bool VisitShuffleVectorExpr (const ShuffleVectorExpr *E)
bool VisitExtVectorElementExpr (const ExtVectorElementExpr *E)
bool VisitObjCBoxedExpr (const ObjCBoxedExpr *E)
bool VisitCXXStdInitializerListExpr (const CXXStdInitializerListExpr *E)
bool VisitStmtExpr (const StmtExpr *E)
bool VisitCXXNewExpr (const CXXNewExpr *E)
bool VisitCXXDeleteExpr (const CXXDeleteExpr *E)
bool visitCompoundStmt (const CompoundStmt *S)
bool visitLoopBody (const Stmt *S)
Visits the given statment without creating a variable scope for it in case it is a compound statement.
bool visitDeclStmt (const DeclStmt *DS)
bool visitReturnStmt (const ReturnStmt *RS)
bool visitIfStmt (const IfStmt *IS)
bool visitWhileStmt (const WhileStmt *S)
bool visitDoStmt (const DoStmt *S)
bool visitForStmt (const ForStmt *S)
bool visitCXXForRangeStmt (const CXXForRangeStmt *S)
bool visitBreakStmt (const BreakStmt *S)
bool visitContinueStmt (const ContinueStmt *S)
bool visitSwitchStmt (const SwitchStmt *S)
bool visitCaseStmt (const CaseStmt *S)
bool visitDefaultStmt (const DefaultStmt *S)
bool visitAttributedStmt (const AttributedStmt *S)
bool visitCXXTryStmt (const CXXTryStmt *S)
Public Member Functions inherited from clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
RetTy Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) RetTy VisitStmt(PTR(Stmt) Node
Protected Types
using LabelTy = typename Emitter::LabelTy
using AddrTy = typename Emitter::AddrTy
using OptLabelTy = std::optional< LabelTy >
using CaseMap = llvm::DenseMap< const SwitchCase *, LabelTy >
Protected Member Functions
bool visitStmt (const Stmt *S)
bool visitExpr (const Expr *E) override
bool visitFunc (const FunctionDecl *F) override
bool visitDeclAndReturn (const VarDecl *VD, bool ConstantContext) override
Toplevel visitDeclAndReturn().
void emitCleanup ()
Emits scope cleanup instructions.
const RecordType * getRecordTy (QualType Ty)
Returns a record type from a record or pointer type.
Record * getRecord (QualType Ty)
Returns a record from a record or pointer type.
Record * getRecord (const RecordDecl *RD)
const Function * getFunction (const FunctionDecl *FD)
Returns a function for the given FunctionDecl.
std::optional< PrimType > classify (const Expr *E) const
std::optional< PrimType > classify (QualType Ty) const
PrimType classifyPrim (QualType Ty) const
Classifies a known primitive type.
PrimType classifyPrim (const Expr *E) const
Classifies a known primitive expression.
bool visit (const Expr *E)
Evaluates an expression and places the result on the stack.
bool visitInitializer (const Expr *E)
Compiles an initializer.
bool discard (const Expr *E)
Evaluates an expression for side effects and discards the result.
bool delegate (const Expr *E)
Just pass evaluation on to E.
VarCreationState visitVarDecl (const VarDecl *VD, bool Toplevel=false)
Creates and initializes a variable from the given decl.
VarCreationState visitDecl (const VarDecl *VD)
bool visitAPValue (const APValue &Val, PrimType ValType, const Expr *E)
Visit an APValue.
bool visitAPValueInitializer (const APValue &Val, const Expr *E)
bool visitDeclRef (const ValueDecl *D, const Expr *E)
Visit the given decl as if we have a reference to it.
bool visitBool (const Expr *E)
Visits an expression and converts it to a boolean.
bool visitInitList (ArrayRef< const Expr * > Inits, const Expr *ArrayFiller, const Expr *E)
bool visitArrayElemInit (unsigned ElemIndex, const Expr *Init)
Pointer to the array(not the element!) must be on the stack when calling this.
unsigned allocateLocalPrimitive (DeclTy &&Decl, PrimType Ty, bool IsConst, bool IsExtended=false)
Creates a local primitive value.
std::optional< unsigned > allocateLocal (DeclTy &&Decl, const ValueDecl *ExtendingDecl=nullptr)
Allocates a space storing a local given its type.
Protected Attributes
Context & Ctx
Current compilation context.
Program & P
Program to link to.
llvm::DenseMap< const ValueDecl *, Scope::Local > Locals
Variable to storage mapping.
llvm::DenseMap< const OpaqueValueExpr *, unsigned > OpaqueExprs
OpaqueValueExpr to location mapping.
VariableScope< Emitter > * VarScope = nullptr
Current scope.
std::optional< uint64_t > ArrayIndex
Current argument index. Needed to emit ArrayInitIndexExpr.
const Expr * SourceLocDefaultExpr = nullptr
DefaultInit- or DefaultArgExpr, needed for SourceLocExpr.
bool DiscardResult = false
Flag indicating if return value is to be discarded.
bool InStmtExpr = false
bool Initializing = false
Flag inidicating if we're initializing an already created variable.
const ValueDecl * InitializingDecl = nullptr
llvm::SmallVector< InitLink > InitStack
bool InitStackActive = false
bool GlobalDecl = false
Flag indicating if we're initializing a global variable.
std::optional< PrimType > ReturnType
Type of the expression returned by the function.
CaseMap CaseLabels
Switch case mapping.
OptLabelTy BreakLabel
Point to break to.
OptLabelTy ContinueLabel
Point to continue to.
OptLabelTy DefaultLabel
Default case label.
Friends
class VariableScope< Emitter >
class LocalScope< Emitter >
class DestructorScope< Emitter >
class DeclScope< Emitter >
class InitLinkScope< Emitter >
class OptionScope< Emitter >
class ArrayIndexScope< Emitter >
class SourceLocScope< Emitter >
struct InitLink
class LoopScope< Emitter >
class LabelScope< Emitter >
class SwitchScope< Emitter >
class StmtExprScope< Emitter >
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
ParamTys P { return RetTy()
Detailed Description
template<class Emitter>
class clang::interp::Compiler< Emitter >
Compilation context for expressions.
Definition at line 96 of file Compiler.h.
Member Typedef Documentation
AddrTy
template<class Emitter > using clang::interp::Compiler< Emitter >::AddrTy = typename Emitter::AddrTy protected
Definition at line 101 of file Compiler.h.
CaseMap
template<class Emitter > using clang::interp::Compiler< Emitter >::CaseMap = llvm::DenseMap<const SwitchCase *, LabelTy> protected
Definition at line 103 of file Compiler.h.
LabelTy
template<class Emitter > using clang::interp::Compiler< Emitter >::LabelTy = typename Emitter::LabelTy protected
Definition at line 100 of file Compiler.h.
OptLabelTy
template<class Emitter > using clang::interp::Compiler< Emitter >::OptLabelTy = std::optional<LabelTy> protected
Definition at line 102 of file Compiler.h.
Constructor & Destructor Documentation
Compiler()
template<class Emitter > template<typename... Tys> clang::interp::Compiler< Emitter >::Compiler (Context & Ctx, Program & P, Tys &&... Args) inline
Initializes the compiler and the backend emitter.
Definition at line 113 of file Compiler.h.
Member Function Documentation
allocateLocal()
template<class Emitter > std::optional< unsigned > Compiler::allocateLocal (DeclTy && Decl, const ValueDecl * ExtendingDecl = nullptr) protected
Allocates a space storing a local given its type.
Definition at line 3477 of file Compiler.cpp.
References D, E, clang::Expr::getType(), clang::QualType::getTypePtr(), clang::interp::Init(), clang::interp::Descriptor::InlineDescMD, clang::QualType::isConstQualified(), and P.
allocateLocalPrimitive()
template<class Emitter > unsigned Compiler::allocateLocalPrimitive (DeclTy && Decl, PrimType Ty, bool IsConst, bool IsExtended = false) protected
Creates a local primitive value.
Definition at line 3452 of file Compiler.cpp.
References D, clang::interp::Descriptor::InlineDescMD, and P.
classify() [1/2]
template<class Emitter > std::optional<PrimType> clang::interp::Compiler< Emitter >::classify (const Expr * E) const inline protected
Definition at line 236 of file Compiler.h.
References clang::interp::Context::classify(), clang::interp::Compiler< Emitter >::Ctx, and E.
Referenced by clang::interp::Compiler< Emitter >::classifyPrim().
classify() [2/2]
template<class Emitter > std::optional<PrimType> clang::interp::Compiler< Emitter >::classify (QualType Ty) const inline protected
Definition at line 239 of file Compiler.h.
References clang::interp::Context::classify(), and clang::interp::Compiler< Emitter >::Ctx.
classifyPrim() [1/2]
template<class Emitter > PrimType clang::interp::Compiler< Emitter >::classifyPrim (const Expr * E) const inline protected
Classifies a known primitive expression.
Definition at line 251 of file Compiler.h.
References clang::interp::Compiler< Emitter >::classify(), E, and clang::T.
classifyPrim() [2/2]
template<class Emitter > PrimType clang::interp::Compiler< Emitter >::classifyPrim (QualType Ty) const inline protected
Classifies a known primitive type.
Definition at line 244 of file Compiler.h.
References clang::interp::Compiler< Emitter >::classify(), and clang::T.
delegate()
template<class Emitter > bool Compiler::delegate (const Expr * E) protected
Just pass evaluation on to E.
This leaves all the parsing flags intact.
Definition at line 3205 of file Compiler.cpp.
References clang::Expr::containsErrors(), and E.
discard()
template<class Emitter > bool Compiler::discard (const Expr * E) protected
Evaluates an expression for side effects and discards the result.
Definition at line 3199 of file Compiler.cpp.
References E.
emitCleanup()
template<class Emitter > void Compiler::emitCleanup protected
Emits scope cleanup instructions.
Definition at line 5268 of file Compiler.cpp.
getFunction()
template<class Emitter > const Function * Compiler::getFunction (const FunctionDecl * FD) protected
Returns a function for the given FunctionDecl.
If the function does not exist yet, it is compiled.
Definition at line 3536 of file Compiler.cpp.
getRecord() [1/2]
template<class Emitter > Record * Compiler::getRecord (const RecordDecl * RD) protected
Definition at line 3531 of file Compiler.cpp.
References P.
getRecord() [2/2]
template<class Emitter > Record * Compiler::getRecord (QualType Ty) protected
Returns a record from a record or pointer type.
Definition at line 3524 of file Compiler.cpp.
getRecordTy()
template<class Emitter > const RecordType * Compiler::getRecordTy (QualType Ty) protected
Returns a record type from a record or pointer type.
Definition at line 3518 of file Compiler.cpp.
References clang::Type::getAs(), and clang::Type::getPointeeType().
visit()
template<class Emitter > bool Compiler::visit (const Expr * E) protected
Evaluates an expression and places the result on the stack.
If the expression is of composite type, a local variable will be created and a pointer to said variable will be placed on the stack.
Definition at line 3215 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::Expr::isGLValue(), clang::QualType::isNull(), and clang::Type::isVoidType().
VisitAbstractConditionalOperator()
template<class Emitter > bool Compiler::VisitAbstractConditionalOperator (const AbstractConditionalOperator * E)
Definition at line 1840 of file Compiler.cpp.
References clang::Condition, and E.
VisitAddrLabelExpr()
template<class Emitter > bool Compiler::VisitAddrLabelExpr (const AddrLabelExpr * E)
Definition at line 2986 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isVoidPointerType(), Offset, and clang::interp::PT_Ptr.
visitAPValue()
template<class Emitter > bool Compiler::visitAPValue (const APValue & Val, PrimType ValType, const Expr * E) protected
Visit an APValue.
Definition at line 3773 of file Compiler.cpp.
References E, clang::APValue::getFloat(), clang::APValue::getInt(), clang::APValue::getLValueBase(), clang::APValue::getMemberPointerDecl(), clang::APValue::isFloat(), clang::APValue::isInt(), clang::APValue::isLValue(), clang::APValue::isMemberPointer(), and clang::APValue::isNullPointer().
visitAPValueInitializer()
template<class Emitter > bool Compiler::visitAPValueInitializer (const APValue & Val, const Expr * E) protected
Definition at line 3800 of file Compiler.cpp.
References E, clang::APValue::getArrayInitializedElt(), clang::APValue::getArraySize(), clang::interp::Record::getField(), clang::FieldDecl::getParent(), clang::APValue::getStructField(), clang::APValue::getStructNumFields(), clang::Expr::getType(), clang::APValue::getUnionField(), clang::APValue::getUnionValue(), clang::APValue::isArray(), clang::APValue::isFloat(), clang::APValue::isInt(), clang::APValue::isLValue(), clang::APValue::isMemberPointer(), clang::APValue::isStruct(), clang::APValue::isUnion(), and clang::T.
visitArrayElemInit()
template<class Emitter > bool Compiler::visitArrayElemInit (unsigned ElemIndex, const Expr * Init) protected
Pointer to the array(not the element!) must be on the stack when calling this.
Definition at line 1538 of file Compiler.cpp.
References clang::interp::Init(), and clang::T.
VisitArrayInitIndexExpr()
template<class Emitter > bool Compiler::VisitArrayInitIndexExpr (const ArrayInitIndexExpr * E)
Definition at line 1765 of file Compiler.cpp.
References E.
VisitArrayInitLoopExpr()
template<class Emitter > bool Compiler::VisitArrayInitLoopExpr (const ArrayInitLoopExpr * E)
Definition at line 1774 of file Compiler.cpp.
References clang::interp::LocalScope< Emitter >::destroyLocals(), and E.
VisitArraySubscriptExpr()
template<class Emitter > bool Compiler::VisitArraySubscriptExpr (const ArraySubscriptExpr * E)
Definition at line 1270 of file Compiler.cpp.
References E.
VisitArrayTypeTraitExpr()
template<class Emitter > bool Compiler::VisitArrayTypeTraitExpr (const ArrayTypeTraitExpr * E)
Definition at line 2371 of file Compiler.cpp.
References E.
visitAttributedStmt()
template<class Emitter > bool Compiler::visitAttributedStmt (const AttributedStmt * S)
Definition at line 4602 of file Compiler.cpp.
VisitBinaryOperator()
template<class Emitter > bool Compiler::VisitBinaryOperator (const BinaryOperator * E)
Definition at line 677 of file Compiler.cpp.
References clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::BinaryOperator::isCommaOp(), clang::BinaryOperator::isComparisonOp(), clang::Type::isFloatingType(), clang::BinaryOperator::isLogicalOp(), clang::Expr::isLValue(), clang::BinaryOperator::isPtrMemOp(), clang::interp::isPtrType(), clang::Type::isVoidType(), clang::interp::LT(), clang::interp::PT_Bool, clang::interp::PT_MemberPtr, clang::Expr::refersToBitField(), and clang::T.
visitBool()
template<class Emitter > bool Compiler::visitBool (const Expr * E) protected
Visits an expression and converts it to a boolean.
Definition at line 3253 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::interp::PT_Bool, clang::interp::PT_Float, clang::interp::PT_FnPtr, clang::interp::PT_Ptr, and clang::T.
visitBreakStmt()
template<class Emitter > bool Compiler::visitBreakStmt (const BreakStmt * S)
Definition at line 4502 of file Compiler.cpp.
VisitBuiltinCallExpr()
template<class Emitter > bool Compiler::VisitBuiltinCallExpr (const CallExpr * E)
Definition at line 3863 of file Compiler.cpp.
References E, clang::Func, clang::Expr::getType(), clang::interp::isPtrType(), clang::Type::isVoidType(), P, and clang::interp::PT_Ptr.
VisitCallExpr()
template<class Emitter > bool Compiler::VisitCallExpr (const CallExpr * E)
Definition at line 3918 of file Compiler.cpp.
References clang::interp::align(), clang::interp::collectNonNullArgs(), E, clang::Func, clang::Type::isVoidType(), clang::interp::primSize(), clang::interp::PT_FnPtr, clang::interp::PT_MemberPtr, clang::interp::PT_Ptr, and clang::T.
visitCaseStmt()
template<class Emitter > bool Compiler::visitCaseStmt (const CaseStmt * S)
Definition at line 4590 of file Compiler.cpp.
VisitCastExpr()
template<class Emitter > bool Compiler::VisitCastExpr (const CastExpr * E)
Definition at line 178 of file Compiler.cpp.
References clang::Type::getAs(), clang::CastExpr::getCastKind(), clang::MemberPointerType::getClass(), clang::Type::getPointeeType(), clang::CastExpr::getSubExpr(), clang::Expr::getType(), clang::QualType::getTypePtr(), clang::interp::Descriptor::InlineDescMD, clang::Type::isAnyComplexType(), clang::Type::isAtomicType(), clang::Type::isFloatingType(), clang::Type::isIntegralOrEnumerationType(), clang::QualType::isNull(), clang::Type::isPointerType(), clang::interp::isPtrType(), clang::Type::isVectorType(), clang::Type::isVoidPointerType(), clang::Type::isVoidType(), P, clang::CastExpr::path(), clang::interp::PT_IntAP, clang::interp::PT_IntAPS, clang::interp::PT_MemberPtr, clang::interp::PT_Ptr, clang::interp::Reinterpret, and clang::T.
VisitCharacterLiteral()
template<class Emitter > bool Compiler::VisitCharacterLiteral (const CharacterLiteral * E)
Definition at line 1969 of file Compiler.cpp.
References E.
VisitChooseExpr()
template<class Emitter > bool Compiler::VisitChooseExpr (const ChooseExpr * E)
Definition at line 2731 of file Compiler.cpp.
References E.
VisitComplexBinOp()
template<class Emitter > bool Compiler::VisitComplexBinOp (const BinaryOperator * E)
Definition at line 958 of file Compiler.cpp.
References E, clang::Type::getAs(), clang::ComplexType::getElementType(), clang::Expr::getType(), clang::Type::isAnyComplexType(), Offset, clang::interp::PT_Float, and clang::interp::PT_Ptr.
VisitComplexUnaryOperator()
template<class Emitter > bool Compiler::VisitComplexUnaryOperator (const UnaryOperator * E)
Definition at line 5029 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isAnyComplexType(), Offset, and clang::interp::PT_Ptr.
VisitCompoundAssignOperator()
template<class Emitter > bool Compiler::VisitCompoundAssignOperator (const CompoundAssignOperator * E)
Definition at line 2087 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isFloatingType(), clang::Type::isPointerType(), clang::interp::LT(), clang::interp::PT_Float, and clang::Expr::refersToBitField().
VisitCompoundLiteralExpr()
template<class Emitter > bool Compiler::VisitCompoundLiteralExpr (const CompoundLiteralExpr * E)
Definition at line 2297 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::interp::Init(), clang::Expr::isLValue(), P, and clang::T.
visitCompoundStmt()
template<class Emitter > bool Compiler::visitCompoundStmt (const CompoundStmt * S)
Definition at line 4226 of file Compiler.cpp.
VisitConceptSpecializationExpr()
template<class Emitter > bool Compiler::VisitConceptSpecializationExpr (const ConceptSpecializationExpr * E)
Definition at line 2937 of file Compiler.cpp.
References E, clang::Expr::getType(), and clang::interp::PT_Bool.
VisitConstantExpr()
template<class Emitter > bool Compiler::VisitConstantExpr (const ConstantExpr * E)
Definition at line 1576 of file Compiler.cpp.
References E, clang::Expr::getType(), and clang::T.
visitContinueStmt()
template<class Emitter > bool Compiler::visitContinueStmt (const ContinueStmt * S)
Definition at line 4511 of file Compiler.cpp.
VisitConvertVectorExpr()
template<class Emitter > bool Compiler::VisitConvertVectorExpr (const ConvertVectorExpr * E)
Definition at line 2996 of file Compiler.cpp.
References clang::Type::castAs(), E, clang::VectorType::getElementType(), clang::Expr::getType(), and clang::interp::PT_Ptr.
VisitCXXBindTemporaryExpr()
template<class Emitter > bool Compiler::VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr * E)
Definition at line 2291 of file Compiler.cpp.
References E.
VisitCXXBoolLiteralExpr()
template<class Emitter > bool Compiler::VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr * E)
Definition at line 4102 of file Compiler.cpp.
References E.
VisitCXXConstructExpr()
template<class Emitter > bool Compiler::VisitCXXConstructExpr (const CXXConstructExpr * E)
Definition at line 2451 of file Compiler.cpp.
References clang::interp::align(), E, clang::Func, clang::Type::getAsCXXRecordDecl(), clang::Expr::getType(), clang::ConstantArrayType::getZExtSize(), clang::Type::isArrayType(), clang::CXXConstructorDecl::isCopyOrMoveConstructor(), clang::FunctionDecl::isDefaulted(), clang::Type::isRecordType(), clang::Expr::isTemporaryObject(), clang::FunctionDecl::isTrivial(), clang::interp::primSize(), clang::interp::PT_Ptr, and clang::T.
VisitCXXDefaultArgExpr()
template<class Emitter > bool Compiler::VisitCXXDefaultArgExpr (const CXXDefaultArgExpr * E)
Definition at line 4090 of file Compiler.cpp.
References E, and clang::T.
VisitCXXDefaultInitExpr()
template<class Emitter > bool Compiler::VisitCXXDefaultInitExpr (const CXXDefaultInitExpr * E)
Definition at line 4078 of file Compiler.cpp.
References E.
VisitCXXDeleteExpr()
template<class Emitter > bool Compiler::VisitCXXDeleteExpr (const CXXDeleteExpr * E)
Definition at line 2875 of file Compiler.cpp.
References E.
visitCXXForRangeStmt()
template<class Emitter > bool Compiler::visitCXXForRangeStmt (const CXXForRangeStmt * S)
Definition at line 4444 of file Compiler.cpp.
VisitCXXInheritedCtorInitExpr()
template<class Emitter > bool Compiler::VisitCXXInheritedCtorInitExpr (const CXXInheritedCtorInitExpr * E)
Definition at line 2744 of file Compiler.cpp.
References clang::interp::align(), E, clang::interp::Function::hasRVO(), clang::interp::Function::hasThisPointer(), clang::FunctionDecl::isTrivial(), Offset, clang::FunctionDecl::parameters(), clang::interp::primSize(), and clang::interp::PT_Ptr.
VisitCXXNewExpr()
template<class Emitter > bool Compiler::VisitCXXNewExpr (const CXXNewExpr * E)
Definition at line 2775 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::QualType::getTypePtr(), clang::interp::Init(), clang::interp::Descriptor::InlineDescMD, clang::Type::isNothrowT(), P, and clang::interp::PT_Ptr.
VisitCXXNoexceptExpr()
template<class Emitter > bool Compiler::VisitCXXNoexceptExpr (const CXXNoexceptExpr * E)
Definition at line 2442 of file Compiler.cpp.
References E, clang::Expr::getType(), and clang::Type::isBooleanType().
VisitCXXNullPtrLiteralExpr()
template<class Emitter > bool Compiler::VisitCXXNullPtrLiteralExpr (const CXXNullPtrLiteralExpr * E)
Definition at line 4110 of file Compiler.cpp.
References E.
VisitCXXParenListInitExpr()
template<class Emitter > bool Compiler::VisitCXXParenListInitExpr (const CXXParenListInitExpr * E)
Definition at line 1564 of file Compiler.cpp.
References E.
VisitCXXReinterpretCastExpr()
template<class Emitter > bool Compiler::VisitCXXReinterpretCastExpr (const CXXReinterpretCastExpr * E)
Definition at line 2433 of file Compiler.cpp.
References E, and clang::interp::Reinterpret.
VisitCXXRewrittenBinaryOperator()
template<class Emitter > bool Compiler::VisitCXXRewrittenBinaryOperator (const CXXRewrittenBinaryOperator * E)
Definition at line 2946 of file Compiler.cpp.
References E.
VisitCXXScalarValueInitExpr()
template<class Emitter > bool Compiler::VisitCXXScalarValueInitExpr (const CXXScalarValueInitExpr * E)
Definition at line 2661 of file Compiler.cpp.
References E, clang::Type::getAs(), clang::Expr::getType(), clang::Type::isVoidType(), and clang::T.
VisitCXXStdInitializerListExpr()
template<class Emitter > bool Compiler::VisitCXXStdInitializerListExpr (const CXXStdInitializerListExpr * E)
Definition at line 3140 of file Compiler.cpp.
References clang::interp::Record::Field::Decl, E, clang::interp::Record::getField(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::Expr::isGLValue(), clang::interp::isIntegralType(), clang::interp::Record::Field::Offset, clang::interp::PT_Ptr, and clang::interp::PT_Uint64.
VisitCXXThisExpr()
template<class Emitter > bool Compiler::VisitCXXThisExpr (const CXXThisExpr * E)
Definition at line 4130 of file Compiler.cpp.
References E, clang::interp::InitLink::K_Field, and Kind.
VisitCXXThrowExpr()
template<class Emitter > bool Compiler::VisitCXXThrowExpr (const CXXThrowExpr * E)
Definition at line 2425 of file Compiler.cpp.
References E.
visitCXXTryStmt()
template<class Emitter > bool Compiler::visitCXXTryStmt (const CXXTryStmt * S)
Definition at line 4633 of file Compiler.cpp.
VisitCXXUuidofExpr()
template<class Emitter > bool Compiler::VisitCXXUuidofExpr (const CXXUuidofExpr * E)
Definition at line 2892 of file Compiler.cpp.
References E, clang::MSGuidDecl::getAsAPValue(), clang::Type::getAsRecordDecl(), clang::ValueDecl::getType(), clang::Expr::getType(), clang::TagDecl::isCompleteDefinition(), clang::APValue::None, P, and V.
visitDecl()
template<class Emitter > VarCreationState Compiler::visitDecl (const VarDecl * VD) protected
Definition at line 3579 of file Compiler.cpp.
References clang::interp::InitializerFailed, clang::interp::GlobalInlineDescriptor::InitState, clang::interp::Block::invokeDtor(), P, clang::interp::Block::rawData(), and clang::interp::Context::shouldBeGloballyIndexed().
visitDeclAndReturn()
template<class Emitter > bool Compiler::visitDeclAndReturn (const VarDecl * VD, bool ConstantContext) override protected
Toplevel visitDeclAndReturn().
We get here from evaluateAsInitializer(). We need to evaluate the initializer and return its value.
Definition at line 3607 of file Compiler.cpp.
References clang::interp::LocalScope< Emitter >::destroyLocals(), clang::VarDecl::getAnyInitializer(), clang::ValueDecl::getType(), clang::interp::InitializerFailed, clang::interp::GlobalInlineDescriptor::InitState, clang::interp::Block::invokeDtor(), P, clang::interp::PT_Ptr, clang::interp::Block::rawData(), and clang::interp::Context::shouldBeGloballyIndexed().
visitDeclRef()
template<class Emitter > bool Compiler::visitDeclRef (const ValueDecl * D, const Expr * E) protected
Visit the given decl as if we have a reference to it.
Definition at line 5136 of file Compiler.cpp.
References D, and E.
Referenced by clang::interp::InitLink::emit().
VisitDeclRefExpr()
template<class Emitter > bool Compiler::VisitDeclRefExpr (const DeclRefExpr * E)
Definition at line 5263 of file Compiler.cpp.
References D, and E.
visitDeclStmt()
template<class Emitter > bool Compiler::visitDeclStmt (const DeclStmt * DS)
Definition at line 4235 of file Compiler.cpp.
References D, clang::DeclStmt::decls(), and clang::isa().
visitDefaultStmt()
template<class Emitter > bool Compiler::visitDefaultStmt (const DefaultStmt * S)
Definition at line 4596 of file Compiler.cpp.
visitDoStmt()
template<class Emitter > bool Compiler::visitDoStmt (const DoStmt * S)
Definition at line 4365 of file Compiler.cpp.
VisitEmbedExpr()
template<class Emitter > bool Compiler::VisitEmbedExpr (const EmbedExpr * E)
Definition at line 1592 of file Compiler.cpp.
References E.
visitExpr()
template<class Emitter > bool Compiler::visitExpr (const Expr * E) override protected
Definition at line 3540 of file Compiler.cpp.
References clang::interp::LocalScope< Emitter >::destroyLocals(), E, clang::Expr::getType(), clang::Type::isVoidType(), and clang::T.
VisitExpressionTraitExpr()
template<class Emitter > bool Compiler::VisitExpressionTraitExpr (const ExpressionTraitExpr * E)
Definition at line 2886 of file Compiler.cpp.
References E.
VisitExprWithCleanups()
template<class Emitter > bool Compiler::VisitExprWithCleanups (const ExprWithCleanups * E)
Definition at line 2208 of file Compiler.cpp.
References clang::interp::LocalScope< Emitter >::destroyLocals(), and E.
VisitExtVectorElementExpr()
template<class Emitter > bool Compiler::VisitExtVectorElementExpr (const ExtVectorElementExpr * E)
Definition at line 3070 of file Compiler.cpp.
References E, clang::Type::getAs(), clang::VectorType::getElementType(), clang::VectorType::getNumElements(), clang::PointerType::getPointeeType(), clang::Expr::getType(), clang::Expr::isGLValue(), clang::Type::isVectorType(), clang::interp::PT_Ptr, and clang::interp::PT_Uint32.
VisitFloatCompoundAssignOperator()
template<class Emitter > bool Compiler::VisitFloatCompoundAssignOperator (const CompoundAssignOperator * E)
Definition at line 1976 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isFloatingType(), and clang::interp::LT().
VisitFloatingLiteral()
template<class Emitter > bool Compiler::VisitFloatingLiteral (const FloatingLiteral * E)
Definition at line 640 of file Compiler.cpp.
References E.
visitForStmt()
template<class Emitter > bool Compiler::visitForStmt (const ForStmt * S)
Definition at line 4396 of file Compiler.cpp.
visitFunc()
template<class Emitter > bool Compiler::visitFunc (const FunctionDecl * F) override protected
Definition at line 4689 of file Compiler.cpp.
References clang::interp::InitLink::Field(), clang::interp::Record::getBase(), clang::FunctionDecl::getBody(), clang::interp::Record::getField(), clang::DeclContext::getParent(), clang::FunctionDecl::getReturnType(), clang::interp::Record::getVirtualBase(), clang::interp::Init(), clang::CXXMethodDecl::isLambdaStaticInvoker(), clang::Type::isVoidType(), clang::Member, P, clang::T, and clang::interp::InitLink::This().
VisitGenericSelectionExpr()
template<class Emitter > bool Compiler::VisitGenericSelectionExpr (const GenericSelectionExpr * E)
Definition at line 2725 of file Compiler.cpp.
References E.
VisitGNUNullExpr()
template<class Emitter > bool Compiler::VisitGNUNullExpr (const GNUNullExpr * E)
Definition at line 4119 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isIntegerType(), and clang::T.
visitIfStmt()
template<class Emitter > bool Compiler::visitIfStmt (const IfStmt * IS)
Definition at line 4286 of file Compiler.cpp.
References clang::interp::LocalScope< Emitter >::destroyLocals(), clang::IfStmt::getCond(), clang::IfStmt::getConditionVariableDeclStmt(), clang::IfStmt::getElse(), clang::IfStmt::getInit(), clang::IfStmt::getThen(), clang::IfStmt::isNegatedConsteval(), and clang::IfStmt::isNonNegatedConsteval().
VisitImaginaryLiteral()
template<class Emitter > bool Compiler::VisitImaginaryLiteral (const ImaginaryLiteral * E)
Definition at line 648 of file Compiler.cpp.
References E, clang::Expr::getType(), and clang::Type::isAnyComplexType().
VisitImplicitValueInitExpr()
template<class Emitter > bool Compiler::VisitImplicitValueInitExpr (const ImplicitValueInitExpr * E)
Definition at line 1186 of file Compiler.cpp.
References E, clang::Type::getAs(), clang::Type::getAsArrayTypeUnsafe(), clang::Type::getAsRecordDecl(), clang::Expr::getType(), clang::Type::isArrayType(), clang::Type::isIncompleteArrayType(), clang::Decl::isInvalidDecl(), clang::Type::isRecordType(), clang::TagDecl::isUnion(), and clang::T.
visitInitializer()
template<class Emitter > bool Compiler::visitInitializer (const Expr * E) protected
Compiles an initializer.
This is like visit() but it will never create a variable and instead rely on a variable already having been created. visitInitializer() then relies on a pointer to this variable being on top of the stack.
Definition at line 3242 of file Compiler.cpp.
References clang::Expr::containsErrors(), E, and clang::Expr::getType().
visitInitList()
template<class Emitter > bool Compiler::visitInitList (ArrayRef< const Expr * > Inits, const Expr * ArrayFiller, const Expr * E) protected
Definition at line 1290 of file Compiler.cpp.
References clang::interp::Record::Field::Decl, E, clang::interp::InitLink::Field(), clang::Type::getAs(), clang::interp::Record::getBase(), clang::interp::Record::getField(), clang::interp::Record::getNumFields(), clang::Expr::getType(), clang::interp::Init(), clang::Type::isArrayType(), clang::Type::isRecordType(), clang::interp::Record::isUnion(), clang::FieldDecl::isUnnamedBitField(), clang::Type::isVoidType(), and clang::T.
VisitInitListExpr()
template<class Emitter > bool Compiler::VisitInitListExpr (const InitListExpr * E)
Definition at line 1559 of file Compiler.cpp.
References E.
VisitIntegerLiteral()
template<class Emitter > bool Compiler::VisitIntegerLiteral (const IntegerLiteral * E)
Definition at line 632 of file Compiler.cpp.
References clang::interp::LE().
VisitLambdaExpr()
template<class Emitter > bool Compiler::VisitLambdaExpr (const LambdaExpr * E)
Definition at line 2378 of file Compiler.cpp.
References E, clang::interp::Record::fields(), clang::interp::Init(), P, and clang::T.
VisitLogicalBinOp()
template<class Emitter > bool Compiler::VisitLogicalBinOp (const BinaryOperator * E)
Definition at line 897 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::interp::PT_Bool, and clang::T.
visitLoopBody()
template<class Emitter > bool Compiler::visitLoopBody (const Stmt * S)
Visits the given statment without creating a variable scope for it in case it is a compound statement.
Definition at line 4211 of file Compiler.cpp.
VisitMaterializeTemporaryExpr()
template<class Emitter > bool Compiler::VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr * E)
Definition at line 2218 of file Compiler.cpp.
References E, IsStatic, P, and clang::SD_Static.
VisitMemberExpr()
template<class Emitter > bool Compiler::VisitMemberExpr (const MemberExpr * E)
Definition at line 1713 of file Compiler.cpp.
References E, clang::interp::Record::getField(), clang::DeclContext::getParent(), clang::Expr::isGLValue(), clang::Member, P, clang::interp::PT_Ptr, and clang::T.
VisitObjCBoolLiteralExpr()
template<class Emitter > bool Compiler::VisitObjCBoolLiteralExpr (const ObjCBoolLiteralExpr * E)
Definition at line 2736 of file Compiler.cpp.
References E.
VisitObjCBoxedExpr()
template<class Emitter > bool Compiler::VisitObjCBoxedExpr (const ObjCBoxedExpr * E)
Definition at line 3132 of file Compiler.cpp.
References E.
VisitObjCEncodeExpr()
template<class Emitter > bool Compiler::VisitObjCEncodeExpr (const ObjCEncodeExpr * E)
Definition at line 1934 of file Compiler.cpp.
References clang::StringLiteral::Create(), E, clang::Expr::getType(), and clang::Ordinary.
VisitObjCStringLiteral()
template<class Emitter > bool Compiler::VisitObjCStringLiteral (const ObjCStringLiteral * E)
Definition at line 1929 of file Compiler.cpp.
References E.
VisitOffsetOfExpr()
template<class Emitter > bool Compiler::VisitOffsetOfExpr (const OffsetOfExpr * E)
Definition at line 2626 of file Compiler.cpp.
References clang::OffsetOfNode::Array, E, clang::Expr::getType(), Node, clang::interp::PT_Sint64, and clang::T.
VisitOpaqueValueExpr()
template<class Emitter > bool Compiler::VisitOpaqueValueExpr (const OpaqueValueExpr * E)
Definition at line 1804 of file Compiler.cpp.
References E, and clang::interp::PT_Ptr.
VisitPackIndexingExpr()
template<class Emitter > bool Compiler::VisitPackIndexingExpr (const PackIndexingExpr * E)
Definition at line 2976 of file Compiler.cpp.
References E.
VisitParenExpr()
template<class Emitter > bool Compiler::VisitParenExpr (const ParenExpr * E)
Definition at line 672 of file Compiler.cpp.
References E.
VisitPointerArithBinOp()
template<class Emitter > bool Compiler::VisitPointerArithBinOp (const BinaryOperator * E)
Perform addition/subtraction of a pointer and an integer or subtraction of two pointers.
Definition at line 849 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isIntegerType(), clang::Type::isPointerType(), and clang::interp::LT().
VisitPointerCompoundAssignOperator()
template<class Emitter > bool Compiler::VisitPointerCompoundAssignOperator (const CompoundAssignOperator * E)
Definition at line 2050 of file Compiler.cpp.
References E, clang::Expr::getType(), and clang::interp::LT().
VisitPredefinedExpr()
template<class Emitter > bool Compiler::VisitPredefinedExpr (const PredefinedExpr * E)
Definition at line 2417 of file Compiler.cpp.
References E.
VisitPseudoObjectExpr()
template<class Emitter > bool Compiler::VisitPseudoObjectExpr (const PseudoObjectExpr * E)
Definition at line 2952 of file Compiler.cpp.
References E.
VisitRecoveryExpr()
template<class Emitter > bool Compiler::VisitRecoveryExpr (const RecoveryExpr * E)
Definition at line 2981 of file Compiler.cpp.
References E.
VisitRequiresExpr()
template<class Emitter > bool Compiler::VisitRequiresExpr (const RequiresExpr * E)
Definition at line 2929 of file Compiler.cpp.
References E, clang::Expr::getType(), and clang::interp::PT_Bool.
visitReturnStmt()
template<class Emitter > bool Compiler::visitReturnStmt (const ReturnStmt * RS)
Definition at line 4252 of file Compiler.cpp.
References clang::ReturnStmt::getRetValue().
VisitShuffleVectorExpr()
template<class Emitter > bool Compiler::VisitShuffleVectorExpr (const ShuffleVectorExpr * E)
Definition at line 3028 of file Compiler.cpp.
References clang::Type::castAs(), E, clang::VectorType::getElementType(), clang::VectorType::getNumElements(), clang::Expr::getType(), and clang::interp::PT_Ptr.
VisitSizeOfPackExpr()
template<class Emitter > bool Compiler::VisitSizeOfPackExpr (const SizeOfPackExpr * E)
Definition at line 2720 of file Compiler.cpp.
References E.
VisitSourceLocExpr()
template<class Emitter > bool Compiler::VisitSourceLocExpr (const SourceLocExpr * E)
Definition at line 2570 of file Compiler.cpp.
References E, clang::interp::Record::getField(), clang::APValue::getInt(), clang::APValue::getLValueBase(), clang::APValue::getLValuePath(), clang::interp::Record::getNumFields(), clang::Expr::getType(), clang::APValue::isInt(), clang::Type::isIntegerType(), clang::APValue::isLValue(), clang::Type::isPointerType(), P, and V.
visitStmt()
template<class Emitter > bool Compiler::visitStmt (const Stmt * S) protected
Definition at line 4160 of file Compiler.cpp.
VisitStmtExpr()
template<class Emitter > bool Compiler::VisitStmtExpr (const StmtExpr * E)
Definition at line 3173 of file Compiler.cpp.
References E, and clang::CompoundStmt::getStmtExprResult().
VisitStringLiteral()
template<class Emitter > bool Compiler::VisitStringLiteral (const StringLiteral * E)
Definition at line 1872 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::ConstantArrayType::getZExtSize(), min(), and P.
VisitSubstNonTypeTemplateParmExpr()
template<class Emitter > bool Compiler::VisitSubstNonTypeTemplateParmExpr (const SubstNonTypeTemplateParmExpr * E)
Definition at line 1570 of file Compiler.cpp.
References E.
visitSwitchStmt()
template<class Emitter > bool Compiler::visitSwitchStmt (const SwitchStmt * S)
Definition at line 4520 of file Compiler.cpp.
VisitSYCLUniqueStableNameExpr()
template<class Emitter > bool Compiler::VisitSYCLUniqueStableNameExpr (const SYCLUniqueStableNameExpr * E)
Definition at line 1945 of file Compiler.cpp.
References clang::StringLiteral::Create(), E, clang::Normal, clang::Ordinary, P, and clang::QualType::withConst().
VisitTypeTraitExpr()
template<class Emitter > bool Compiler::VisitTypeTraitExpr (const TypeTraitExpr * E)
Definition at line 2362 of file Compiler.cpp.
References E, clang::Expr::getType(), and clang::Type::isBooleanType().
VisitUnaryExprOrTypeTraitExpr()
template<class Emitter > bool Compiler::VisitUnaryExprOrTypeTraitExpr (const UnaryExprOrTypeTraitExpr * E)
Definition at line 1621 of file Compiler.cpp.
References AlignOfType(), E, clang::Type::getAs(), clang::ASTContext::getDeclAlign(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::ASTContext::getTypeInfoDataSizeInChars(), clang::ASTContext::getTypeSizeInChars(), clang::Expr::IgnoreParens(), clang::Type::isConstantSizeType(), clang::Type::isDependentType(), clang::Type::isFunctionType(), clang::Type::isVoidType(), Kind, clang::CharUnits::One(), and clang::TypeInfoChars::Width.
VisitUnaryOperator()
template<class Emitter > bool Compiler::VisitUnaryOperator (const UnaryOperator * E)
Definition at line 4810 of file Compiler.cpp.
References E, clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::Expr::isGLValue(), clang::interp::isIntegralType(), clang::Type::isMemberPointerType(), clang::interp::PT_Bool, clang::interp::PT_Float, clang::interp::PT_FnPtr, clang::interp::PT_Ptr, and clang::T.
visitVarDecl()
template<class Emitter > VarCreationState Compiler::visitVarDecl (const VarDecl * VD, bool Toplevel = false) protected
Creates and initializes a variable from the given decl.
Definition at line 3667 of file Compiler.cpp.
References clang::interp::InitLink::Decl(), clang::VarDecl::getInit(), clang::ValueDecl::getType(), clang::interp::Init(), clang::QualType::isConstQualified(), clang::VarDecl::isLocalVarDecl(), clang::QualType::isNull(), clang::VarDecl::isStaticLocal(), clang::interp::VarCreationState::NotCreated(), Offset, P, and clang::interp::Context::shouldBeGloballyIndexed().
visitWhileStmt()
template<class Emitter > bool Compiler::visitWhileStmt (const WhileStmt * S)
Definition at line 4331 of file Compiler.cpp.
Friends And Related Function Documentation
ArrayIndexScope< Emitter >
template<class Emitter > friend class ArrayIndexScope< Emitter > friend
Definition at line 293 of file Compiler.h.
DeclScope< Emitter >
template<class Emitter > friend class DeclScope< Emitter > friend
Definition at line 293 of file Compiler.h.
DestructorScope< Emitter >
template<class Emitter > friend class DestructorScope< Emitter > friend
Definition at line 293 of file Compiler.h.
InitLink
template<class Emitter > friend struct InitLink friend
Definition at line 304 of file Compiler.h.
InitLinkScope< Emitter >
template<class Emitter > friend class InitLinkScope< Emitter > friend
Definition at line 293 of file Compiler.h.
LabelScope< Emitter >
template<class Emitter > friend class LabelScope< Emitter > friend
Definition at line 304 of file Compiler.h.
LocalScope< Emitter >
template<class Emitter > friend class LocalScope< Emitter > friend
Definition at line 293 of file Compiler.h.
LoopScope< Emitter >
template<class Emitter > friend class LoopScope< Emitter > friend
Definition at line 304 of file Compiler.h.
OptionScope< Emitter >
template<class Emitter > friend class OptionScope< Emitter > friend
Definition at line 293 of file Compiler.h.
SourceLocScope< Emitter >
template<class Emitter > friend class SourceLocScope< Emitter > friend
Definition at line 293 of file Compiler.h.
StmtExprScope< Emitter >
template<class Emitter > friend class StmtExprScope< Emitter > friend
Definition at line 304 of file Compiler.h.
SwitchScope< Emitter >
template<class Emitter > friend class SwitchScope< Emitter > friend
Definition at line 304 of file Compiler.h.
VariableScope< Emitter >
template<class Emitter > friend class VariableScope< Emitter > friend
Definition at line 293 of file Compiler.h.
Member Data Documentation
ArrayIndex
template<class Emitter > std::optional<uint64_t> clang::interp::Compiler< Emitter >::ArrayIndex protected
Current argument index. Needed to emit ArrayInitIndexExpr.
Definition at line 365 of file Compiler.h.
BreakLabel
template<class Emitter > OptLabelTy clang::interp::Compiler< Emitter >::BreakLabel protected
Point to break to.
Definition at line 393 of file Compiler.h.
Referenced by clang::interp::LoopScope< Emitter >::LoopScope(), and clang::interp::SwitchScope< Emitter >::SwitchScope().
CaseLabels
template<class Emitter > CaseMap clang::interp::Compiler< Emitter >::CaseLabels protected
Switch case mapping.
Definition at line 390 of file Compiler.h.
Referenced by clang::interp::SwitchScope< Emitter >::SwitchScope().
ContinueLabel
template<class Emitter > OptLabelTy clang::interp::Compiler< Emitter >::ContinueLabel protected
Point to continue to.
Definition at line 395 of file Compiler.h.
Referenced by clang::interp::LoopScope< Emitter >::LoopScope().
Ctx
template<class Emitter > Context& clang::interp::Compiler< Emitter >::Ctx protected
Current compilation context.
Definition at line 106 of file Compiler.h.
Referenced by clang::interp::Compiler< Emitter >::classify().
DefaultLabel
template<class Emitter > OptLabelTy clang::interp::Compiler< Emitter >::DefaultLabel protected
Default case label.
Definition at line 397 of file Compiler.h.
Referenced by clang::interp::SwitchScope< Emitter >::SwitchScope().
DiscardResult
template<class Emitter > bool clang::interp::Compiler< Emitter >::DiscardResult = false protected
Flag indicating if return value is to be discarded.
Definition at line 371 of file Compiler.h.
Referenced by clang::interp::OptionScope< Emitter >::OptionScope().
GlobalDecl
template<class Emitter > bool clang::interp::Compiler< Emitter >::GlobalDecl = false protected
Flag indicating if we're initializing a global variable.
Definition at line 384 of file Compiler.h.
Referenced by clang::interp::DeclScope< Emitter >::DeclScope().
Initializing
template<class Emitter > bool clang::interp::Compiler< Emitter >::Initializing = false protected
Flag inidicating if we're initializing an already created variable.
This is set in visitInitializer().
Definition at line 377 of file Compiler.h.
Referenced by clang::interp::OptionScope< Emitter >::OptionScope().
InitializingDecl
template<class Emitter > const ValueDecl* clang::interp::Compiler< Emitter >::InitializingDecl = nullptr protected
Definition at line 378 of file Compiler.h.
Referenced by clang::interp::DeclScope< Emitter >::DeclScope().
InitStack
template<class Emitter > llvm::SmallVector<InitLink> clang::interp::Compiler< Emitter >::InitStack protected
Definition at line 380 of file Compiler.h.
Referenced by clang::interp::DeclScope< Emitter >::DeclScope(), and clang::interp::InitLinkScope< Emitter >::InitLinkScope().
InitStackActive
template<class Emitter > bool clang::interp::Compiler< Emitter >::InitStackActive = false protected
Definition at line 381 of file Compiler.h.
InStmtExpr
template<class Emitter > bool clang::interp::Compiler< Emitter >::InStmtExpr = false protected
Definition at line 373 of file Compiler.h.
Referenced by clang::interp::StmtExprScope< Emitter >::StmtExprScope().
Locals
template<class Emitter > llvm::DenseMap<const ValueDecl *, Scope::Local> clang::interp::Compiler< Emitter >::Locals protected
Variable to storage mapping.
Definition at line 356 of file Compiler.h.
OpaqueExprs
template<class Emitter > llvm::DenseMap<const OpaqueValueExpr *, unsigned> clang::interp::Compiler< Emitter >::OpaqueExprs protected
OpaqueValueExpr to location mapping.
Definition at line 359 of file Compiler.h.
P
template<class Emitter > Program& clang::interp::Compiler< Emitter >::P protected
Program to link to.
Definition at line 108 of file Compiler.h.
ReturnType
template<class Emitter > std::optional<PrimType> clang::interp::Compiler< Emitter >::ReturnType protected
Type of the expression returned by the function.
Definition at line 387 of file Compiler.h.
SourceLocDefaultExpr
template<class Emitter > const Expr* clang::interp::Compiler< Emitter >::SourceLocDefaultExpr = nullptr protected
DefaultInit- or DefaultArgExpr, needed for SourceLocExpr.
Definition at line 368 of file Compiler.h.
Referenced by clang::interp::SourceLocScope< Emitter >::SourceLocScope().
VarScope
template<class Emitter > VariableScope<Emitter>* clang::interp::Compiler< Emitter >::VarScope = nullptr protected
Current scope.
Definition at line 362 of file Compiler.h.
Referenced by clang::interp::VariableScope< Emitter >::VariableScope().
The documentation for this class was generated from the following files:
lib/AST/Interp/Compiler.h
lib/AST/Interp/Compiler.cpp