clang: clang::CodeGen::EHScope Class Reference
clang::CodeGen::EHScope Class Reference
A protected scope for zero-cost EH handling.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCleanup.h"
Classes
class CatchBitFields
class CleanupBitFields
class FilterBitFields
Public Types
enum Kind { Cleanup , Catch , Terminate , Filter }
Public Member Functions
EHScope (Kind kind, EHScopeStack::stable_iterator enclosingEHScope)
Kind getKind () const
llvm::BasicBlock * getCachedLandingPad () const
void setCachedLandingPad (llvm::BasicBlock *block)
llvm::BasicBlock * getCachedEHDispatchBlock () const
void setCachedEHDispatchBlock (llvm::BasicBlock *block)
bool hasEHBranches () const
EHScopeStack::stable_iterator getEnclosingEHScope () const
Protected Attributes
union {
CommonBitFields CommonBits
CatchBitFields CatchBits
CleanupBitFields CleanupBits
FilterBitFields FilterBits
};
Detailed Description
A protected scope for zero-cost EH handling.
Definition at line 42 of file CGCleanup.h.
Member Enumeration Documentation
Kind
enum clang::CodeGen::EHScope::Kind
Enumerator
Cleanup
Catch
Terminate
Filter
Definition at line 44 of file CGCleanup.h.
Constructor & Destructor Documentation
EHScope()
clang::CodeGen::EHScope::EHScope (Kind kind, EHScopeStack::stable_iterator enclosingEHScope) inline
Definition at line 115 of file CGCleanup.h.
References CommonBits.
Member Function Documentation
getCachedEHDispatchBlock()
llvm::BasicBlock* clang::CodeGen::EHScope::getCachedEHDispatchBlock () const inline
Definition at line 131 of file CGCleanup.h.
Referenced by emitCatchDispatchBlock(), emitCatchPadBlock(), emitFilterDispatchBlock(), emitWasmCatchPadBlock(), clang::CodeGen::CodeGenFunction::getEHDispatchBlock(), clang::CodeGen::CodeGenFunction::getFuncletEHDispatchBlock(), and hasEHBranches().
getCachedLandingPad()
llvm::BasicBlock* clang::CodeGen::EHScope::getCachedLandingPad () const inline
Definition at line 123 of file CGCleanup.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLandingPad(), and clang::CodeGen::CodeGenFunction::getInvokeDestImpl().
getEnclosingEHScope()
EHScopeStack::stable_iterator clang::CodeGen::EHScope::getEnclosingEHScope () const inline
Definition at line 145 of file CGCleanup.h.
Referenced by emitCatchDispatchBlock(), emitCatchPadBlock(), emitWasmCatchPadBlock(), IsUsedAsEHCleanup(), clang::CodeGen::EHScopeStack::popCatch(), clang::CodeGen::EHScopeStack::popFilter(), and clang::CodeGen::EHScopeStack::popTerminate().
getKind()
Kind clang::CodeGen::EHScope::getKind () const inline
Definition at line 121 of file CGCleanup.h.
References CommonBits.
Referenced by clang::CodeGen::EHFilterScope::classof(), clang::CodeGen::EHTerminateScope::classof(), clang::CodeGen::CodeGenFunction::EmitLandingPad(), clang::CodeGen::CodeGenFunction::getEHDispatchBlock(), and clang::CodeGen::CodeGenFunction::getFuncletEHDispatchBlock().
hasEHBranches()
bool clang::CodeGen::EHScope::hasEHBranches () const inline
Definition at line 139 of file CGCleanup.h.
References getCachedEHDispatchBlock().
Referenced by IsUsedAsEHCleanup(), and clang::CodeGen::CodeGenFunction::popCatchScope().
setCachedEHDispatchBlock()
void clang::CodeGen::EHScope::setCachedEHDispatchBlock (llvm::BasicBlock * block) inline
Definition at line 135 of file CGCleanup.h.
Referenced by clang::CodeGen::CodeGenFunction::getEHDispatchBlock(), and clang::CodeGen::CodeGenFunction::getFuncletEHDispatchBlock().
setCachedLandingPad()
void clang::CodeGen::EHScope::setCachedLandingPad (llvm::BasicBlock * block) inline
Definition at line 127 of file CGCleanup.h.
Member Data Documentation
union { ... }
CatchBits
CatchBitFields clang::CodeGen::EHScope::CatchBits
Definition at line 109 of file CGCleanup.h.
Referenced by clang::CodeGen::EHCatchScope::EHCatchScope(), and clang::CodeGen::EHCatchScope::getNumHandlers().
CleanupBits
CleanupBitFields clang::CodeGen::EHScope::CleanupBits
Definition at line 110 of file CGCleanup.h.
Referenced by clang::CodeGen::EHCleanupScope::EHCleanupScope(), clang::CodeGen::EHCleanupScope::getAllocatedSize(), clang::CodeGen::EHCleanupScope::getCleanupSize(), clang::CodeGen::EHCleanupScope::isActive(), clang::CodeGen::EHCleanupScope::isEHCleanup(), clang::CodeGen::EHCleanupScope::isLifetimeMarker(), clang::CodeGen::EHCleanupScope::isNormalCleanup(), clang::CodeGen::EHCleanupScope::setActive(), clang::CodeGen::EHCleanupScope::setLifetimeMarker(), clang::CodeGen::EHCleanupScope::setTestFlagInEHCleanup(), clang::CodeGen::EHCleanupScope::setTestFlagInNormalCleanup(), clang::CodeGen::EHCleanupScope::shouldTestFlagInEHCleanup(), and clang::CodeGen::EHCleanupScope::shouldTestFlagInNormalCleanup().
CommonBits
CommonBitFields clang::CodeGen::EHScope::CommonBits
Definition at line 108 of file CGCleanup.h.
Referenced by EHScope(), and getKind().
FilterBits
FilterBitFields clang::CodeGen::EHScope::FilterBits
Definition at line 111 of file CGCleanup.h.
Referenced by clang::CodeGen::EHFilterScope::EHFilterScope(), and clang::CodeGen::EHFilterScope::getNumFilters().
The documentation for this class was generated from the following file:
lib/CodeGen/CGCleanup.h