clang: clang::SemaHexagon Class Reference
clang::SemaHexagon Class Reference
#include "clang/Sema/SemaHexagon.h"
Public Member Functions
SemaHexagon (Sema &S)
bool CheckHexagonBuiltinFunctionCall (unsigned BuiltinID, CallExpr *TheCall)
bool CheckHexagonBuiltinArgument (unsigned BuiltinID, CallExpr *TheCall)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 20 of file SemaHexagon.h.
Constructor & Destructor Documentation
SemaHexagon()
clang::SemaHexagon::SemaHexagon (Sema & S)
Definition at line 22 of file SemaHexagon.cpp.
Member Function Documentation
CheckHexagonBuiltinArgument()
bool clang::SemaHexagon::CheckHexagonBuiltinArgument (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 24 of file SemaHexagon.cpp.
References clang::Sema::BuiltinConstantArgMultiple(), clang::Sema::BuiltinConstantArgRange(), BuiltinInfo, clang::Max, clang::Min, clang::SemaBase::SemaRef, and true.
Referenced by CheckHexagonBuiltinFunctionCall().
CheckHexagonBuiltinFunctionCall()
bool clang::SemaHexagon::CheckHexagonBuiltinFunctionCall (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 285 of file SemaHexagon.cpp.
References CheckHexagonBuiltinArgument().
The documentation for this class was generated from the following files:
include/clang/Sema/SemaHexagon.h
lib/Sema/SemaHexagon.cpp