clang: clang::CodeGen::CodeGenFunction::LexicalScope Class Reference
clang::CodeGen::CodeGenFunction::LexicalScope Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
LexicalScope (CodeGenFunction &CGF, SourceRange Range)
Enter a new cleanup scope.
void addLabel (const LabelDecl *label)
~LexicalScope ()
Exit this cleanup scope, emitting any accumulated cleanups.
void ForceCleanup ()
Force the emission of cleanups now, instead of waiting until this object is destroyed.
bool hasLabels () const
void rescopeLabels ()
Change the cleanup scope of the labels in this lexical scope to match the scope of the enclosing context.
Public Member Functions inherited from clang::CodeGen::CodeGenFunction::RunCleanupsScope
RunCleanupsScope (CodeGenFunction &CGF)
Enter a new cleanup scope.
~RunCleanupsScope ()
Exit this cleanup scope, emitting any accumulated cleanups.
bool requiresCleanups () const
Determine whether this scope requires any cleanups.
void ForceCleanup (std::initializer_list< llvm::Value ** > ValuesToReload={})
Force the emission of cleanups now, instead of waiting until this object is destroyed.
Additional Inherited Members
Protected Attributes inherited from clang::CodeGen::CodeGenFunction::RunCleanupsScope
bool PerformCleanup
CodeGenFunction & CGF
Detailed Description
Definition at line 985 of file CodeGenFunction.h.
Constructor & Destructor Documentation
LexicalScope()
clang::CodeGen::CodeGenFunction::LexicalScope::LexicalScope (CodeGenFunction & CGF, SourceRange Range) inline explicit
Enter a new cleanup scope.
Definition at line 995 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::RunCleanupsScope::CGF, and clang::CodeGen::CodeGenFunction::getDebugInfo().
~LexicalScope()
clang::CodeGen::CodeGenFunction::LexicalScope::~LexicalScope () inline
Exit this cleanup scope, emitting any accumulated cleanups.
Definition at line 1009 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::RunCleanupsScope::CGF, ForceCleanup(), clang::CodeGen::CodeGenFunction::getDebugInfo(), and clang::CodeGen::CodeGenFunction::RunCleanupsScope::PerformCleanup.
Member Function Documentation
addLabel()
void clang::CodeGen::CodeGenFunction::LexicalScope::addLabel (const LabelDecl * label) inline
Definition at line 1002 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::RunCleanupsScope::PerformCleanup.
Referenced by clang::CodeGen::CodeGenFunction::EmitLabel().
ForceCleanup()
void clang::CodeGen::CodeGenFunction::LexicalScope::ForceCleanup () inline
Force the emission of cleanups now, instead of waiting until this object is destroyed.
Definition at line 1023 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::RunCleanupsScope::CGF, clang::CodeGen::CodeGenFunction::RunCleanupsScope::ForceCleanup(), and rescopeLabels().
Referenced by ~LexicalScope().
hasLabels()
bool clang::CodeGen::CodeGenFunction::LexicalScope::hasLabels () const inline
Definition at line 1031 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::hasLabelBeenSeenInCurrentScope().
rescopeLabels()
void CodeGenFunction::LexicalScope::rescopeLabels ()
Change the cleanup scope of the labels in this lexical scope to match the scope of the enclosing context.
Definition at line 680 of file CGStmt.cpp.
References clang::CodeGen::CodeGenFunction::RunCleanupsScope::CGF, clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::EHScopeStack::stable_iterator::encloses(), clang::CodeGen::EHScopeStack::getInnermostNormalCleanup(), clang::CodeGen::CodeGenFunction::JumpDest::getScopeDepth(), clang::CodeGen::EHScopeStack::stable_iterator::isValid(), clang::CodeGen::CodeGenFunction::JumpDest::setScopeDepth(), and clang::CodeGen::EHScopeStack::stable_end().
Referenced by ForceCleanup().
The documentation for this class was generated from the following files:
lib/CodeGen/CodeGenFunction.h
lib/CodeGen/CGStmt.cpp