clang: clang::ento::mpi::MPIBugReporter Class Reference
clang::ento::mpi::MPIBugReporter Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Checkers/MPI-Checker/MPIBugReporter.h"
Public Member Functions
MPIBugReporter (const CheckerBase &CB)
void reportDoubleNonblocking (const CallEvent &MPICallEvent, const Request &Req, const MemRegion *const RequestRegion, const ExplodedNode *const ExplNode, BugReporter &BReporter) const
Report duplicate request use by nonblocking calls without intermediate wait.
void reportMissingWait (const Request &Req, const MemRegion *const RequestRegion, const ExplodedNode *const ExplNode, BugReporter &BReporter) const
Report a missing wait for a nonblocking call.
void reportUnmatchedWait (const CallEvent &CE, const MemRegion *const RequestRegion, const ExplodedNode *const ExplNode, BugReporter &BReporter) const
Report a wait on a request that has not been used at all before.
Detailed Description
Definition at line 25 of file MPIBugReporter.h.
Constructor & Destructor Documentation
MPIBugReporter()
clang::ento::mpi::MPIBugReporter::MPIBugReporter (const CheckerBase & CB) inline
Definition at line 27 of file MPIBugReporter.h.
Member Function Documentation
reportDoubleNonblocking()
void clang::ento::mpi::MPIBugReporter::reportDoubleNonblocking (const CallEvent & MPICallEvent, const Request & Req, const MemRegion *const RequestRegion, const ExplodedNode *const ExplNode, BugReporter & BReporter) const
Report duplicate request use by nonblocking calls without intermediate wait.
Parameters
MPICallEvent MPI call that caused the double nonblocking
Req request that was used by two nonblocking calls in sequence
RequestRegion memory region of the request
ExplNode node in the graph the bug appeared at
BReporter bug reporter for current context
Definition at line 23 of file MPIBugReporter.cpp.
References clang::ento::BugReporter::emitReport(), clang::ento::MemRegion::getDescriptiveName(), clang::ento::CallEvent::getSourceRange(), clang::ento::MemRegion::sourceRange(), and string().
Referenced by clang::ento::mpi::MPIChecker::checkDoubleNonblocking().
reportMissingWait()
void clang::ento::mpi::MPIBugReporter::reportMissingWait (const Request & Req, const MemRegion *const RequestRegion, const ExplodedNode *const ExplNode, BugReporter & BReporter) const
Report a missing wait for a nonblocking call.
Parameters
Req request that is not matched by a wait
RequestRegion memory region of the request
ExplNode node in the graph the bug appeared at
BReporter bug reporter for current context
Definition at line 49 of file MPIBugReporter.cpp.
References clang::ento::BugReporter::emitReport(), clang::ento::MemRegion::getDescriptiveName(), clang::ento::MemRegion::sourceRange(), and string().
Referenced by clang::ento::mpi::MPIChecker::checkMissingWaits().
reportUnmatchedWait()
void clang::ento::mpi::MPIBugReporter::reportUnmatchedWait (const CallEvent & CE, const MemRegion *const RequestRegion, const ExplodedNode *const ExplNode, BugReporter & BReporter) const
Report a wait on a request that has not been used at all before.
Parameters
CE wait call that uses the request
RequestRegion memory region of the request
ExplNode node in the graph the bug appeared at
BReporter bug reporter for current context
Definition at line 69 of file MPIBugReporter.cpp.
References clang::ento::BugReporter::emitReport(), clang::ento::MemRegion::getDescriptiveName(), clang::ento::CallEvent::getSourceRange(), clang::ento::MemRegion::sourceRange(), and string().
Referenced by clang::ento::mpi::MPIChecker::checkUnmatchedWaits().
The documentation for this class was generated from the following files:
lib/StaticAnalyzer/Checkers/MPI-Checker/MPIBugReporter.h
lib/StaticAnalyzer/Checkers/MPI-Checker/MPIBugReporter.cpp