clang: clang::CXXRecordDecl Class Reference
clang::CXXRecordDecl Class Reference
Represents a C++ struct/union/class.
#include "clang/AST/DeclCXX.h"
Classes
class friend_iterator
An iterator over the friend declarations of a class.
struct LambdaNumbering
Information about how a lambda is numbered within its context.
Public Types
enum LambdaDependencyKind { LDK_Unknown = 0 , LDK_AlwaysDependent , LDK_NeverDependent }
using base_class_iterator = CXXBaseSpecifier *
Iterator that traverses the base classes of a class.
using base_class_const_iterator = const CXXBaseSpecifier *
Iterator that traverses the base classes of a class.
using base_class_range = llvm::iterator_range< base_class_iterator >
using base_class_const_range = llvm::iterator_range< base_class_const_iterator >
using method_iterator = specific_decl_iterator< CXXMethodDecl >
Iterator access to method members.
using method_range = llvm::iterator_range< specific_decl_iterator< CXXMethodDecl > >
using ctor_iterator = specific_decl_iterator< CXXConstructorDecl >
Iterator access to constructor members.
using ctor_range = llvm::iterator_range< specific_decl_iterator< CXXConstructorDecl > >
using friend_range = llvm::iterator_range< friend_iterator >
using capture_const_iterator = const LambdaCapture *
using capture_const_range = llvm::iterator_range< capture_const_iterator >
using conversion_iterator = UnresolvedSetIterator
using ForallBasesCallback = llvm::function_ref< bool(const CXXRecordDecl *BaseDefinition)>
Function type used by forallBases() as a callback.
using BaseMatchesCallback = llvm::function_ref< bool(const CXXBaseSpecifier *Specifier, CXXBasePath &Path)>
Function type used by lookupInBases() to determine whether a specific base class subobject matches the lookup criteria.
Public Types inherited from clang::RecordDecl
using field_iterator = specific_decl_iterator< FieldDecl >
using field_range = llvm::iterator_range< specific_decl_iterator< FieldDecl > >
Public Types inherited from clang::TagDecl
using TagKind = TagTypeKind
using redecl_range = redeclarable_base::redecl_range
using redecl_iterator = redeclarable_base::redecl_iterator
Public Types inherited from clang::NamedDecl
enum ExplicitVisibilityKind { VisibilityForType , VisibilityForValue }
Kinds of explicit visibility.
Public Types inherited from clang::Decl
enum Kind
Lists the kind of concrete classes of Decl.
enum IdentifierNamespace {
IDNS_Label = 0x0001 , IDNS_Tag = 0x0002 , IDNS_Type = 0x0004 , IDNS_Member = 0x0008 ,
IDNS_Namespace = 0x0010 , IDNS_Ordinary = 0x0020 , IDNS_ObjCProtocol = 0x0040 , IDNS_OrdinaryFriend = 0x0080 ,
IDNS_TagFriend = 0x0100 , IDNS_Using = 0x0200 , IDNS_NonMemberOperator = 0x0400 , IDNS_LocalExtern = 0x0800 ,
IDNS_OMPReduction = 0x1000 , IDNS_OMPMapper = 0x2000
}
IdentifierNamespace - The different namespaces in which declarations may appear.
enum ObjCDeclQualifier {
OBJC_TQ_None = 0x0 , OBJC_TQ_In = 0x1 , OBJC_TQ_Inout = 0x2 , OBJC_TQ_Out = 0x4 ,
OBJC_TQ_Bycopy = 0x8 , OBJC_TQ_Byref = 0x10 , OBJC_TQ_Oneway = 0x20 , OBJC_TQ_CSNullability = 0x40
}
ObjCDeclQualifier - 'Qualifiers' written next to the return and parameter types in method declarations.
enum class ModuleOwnershipKind : unsigned char {
Unowned , Visible , VisibleWhenImported , ReachableWhenImported ,
ModulePrivate
}
The kind of ownership a declaration has, for visibility purposes.
enum FriendObjectKind { FOK_None , FOK_Declared , FOK_Undeclared }
using DeclID = uint32_t
An ID number that refers to a declaration in an AST file.
using attr_iterator = AttrVec::const_iterator
using attr_range = llvm::iterator_range< attr_iterator >
using redecl_range = llvm::iterator_range< redecl_iterator >
Public Types inherited from clang::DeclContext
using decl_range = llvm::iterator_range< decl_iterator >
using lookup_result = DeclContextLookupResult
using lookup_iterator = lookup_result::iterator
using lookups_range = llvm::iterator_range< all_lookups_iterator >
using udir_iterator_base = llvm::iterator_adaptor_base< udir_iterator, lookup_iterator, typename lookup_iterator::iterator_category, UsingDirectiveDecl * >
using udir_range = llvm::iterator_range< udir_iterator >
using ddiag_range = llvm::iterator_range< DeclContext::ddiag_iterator >
Public Types inherited from clang::Redeclarable< TagDecl >
using redecl_range = llvm::iterator_range< redecl_iterator >
Public Member Functions
CXXRecordDecl * getCanonicalDecl () override
Retrieves the "canonical" declaration of the given declaration.
const CXXRecordDecl * getCanonicalDecl () const
CXXRecordDecl * getPreviousDecl ()
const CXXRecordDecl * getPreviousDecl () const
CXXRecordDecl * getMostRecentDecl ()
const CXXRecordDecl * getMostRecentDecl () const
CXXRecordDecl * getMostRecentNonInjectedDecl ()
const CXXRecordDecl * getMostRecentNonInjectedDecl () const
CXXRecordDecl * getDefinition () const
bool hasDefinition () const
bool isDynamicClass () const
bool mayBeDynamicClass () const
bool mayBeNonDynamicClass () const
void setIsParsingBaseSpecifiers ()
bool isParsingBaseSpecifiers () const
unsigned getODRHash () const
void setBases (CXXBaseSpecifier const *const *Bases, unsigned NumBases)
Sets the base classes of this struct or class.
unsigned getNumBases () const
Retrieves the number of base classes of this class.
base_class_range bases ()
base_class_const_range bases () const
base_class_iterator bases_begin ()
base_class_const_iterator bases_begin () const
base_class_iterator bases_end ()
base_class_const_iterator bases_end () const
unsigned getNumVBases () const
Retrieves the number of virtual base classes of this class.
base_class_range vbases ()
base_class_const_range vbases () const
base_class_iterator vbases_begin ()
base_class_const_iterator vbases_begin () const
base_class_iterator vbases_end ()
base_class_const_iterator vbases_end () const
bool hasAnyDependentBases () const
Determine whether this class has any dependent base classes which are not the current instantiation.
method_range methods () const
method_iterator method_begin () const
Method begin iterator.
method_iterator method_end () const
Method past-the-end iterator.
ctor_range ctors () const
ctor_iterator ctor_begin () const
ctor_iterator ctor_end () const
friend_range friends () const
friend_iterator friend_begin () const
friend_iterator friend_end () const
void pushFriendDecl (FriendDecl *FD)
bool hasFriends () const
Determines whether this record has any friends.
bool defaultedCopyConstructorIsDeleted () const
true if a defaulted copy constructor for this class would be deleted.
bool defaultedMoveConstructorIsDeleted () const
true if a defaulted move constructor for this class would be deleted.
bool defaultedDestructorIsDeleted () const
true if a defaulted destructor for this class would be deleted.
bool hasSimpleCopyConstructor () const
true if we know for sure that this class has a single, accessible, unambiguous copy constructor that is not deleted.
bool hasSimpleMoveConstructor () const
true if we know for sure that this class has a single, accessible, unambiguous move constructor that is not deleted.
bool hasSimpleCopyAssignment () const
true if we know for sure that this class has a single, accessible, unambiguous copy assignment operator that is not deleted.
bool hasSimpleMoveAssignment () const
true if we know for sure that this class has a single, accessible, unambiguous move assignment operator that is not deleted.
bool hasSimpleDestructor () const
true if we know for sure that this class has an accessible destructor that is not deleted.
bool hasDefaultConstructor () const
Determine whether this class has any default constructors.
bool needsImplicitDefaultConstructor () const
Determine if we need to declare a default constructor for this class.
bool hasUserDeclaredConstructor () const
Determine whether this class has any user-declared constructors.
bool hasUserProvidedDefaultConstructor () const
Whether this class has a user-provided default constructor per C++11.
bool hasUserDeclaredCopyConstructor () const
Determine whether this class has a user-declared copy constructor.
bool needsImplicitCopyConstructor () const
Determine whether this class needs an implicit copy constructor to be lazily declared.
bool needsOverloadResolutionForCopyConstructor () const
Determine whether we need to eagerly declare a defaulted copy constructor for this class.
bool implicitCopyConstructorHasConstParam () const
Determine whether an implicit copy constructor for this type would have a parameter with a const-qualified reference type.
bool hasCopyConstructorWithConstParam () const
Determine whether this class has a copy constructor with a parameter type which is a reference to a const-qualified type.
bool hasUserDeclaredMoveOperation () const
Whether this class has a user-declared move constructor or assignment operator.
bool hasUserDeclaredMoveConstructor () const
Determine whether this class has had a move constructor declared by the user.
bool hasMoveConstructor () const
Determine whether this class has a move constructor.
void setImplicitCopyConstructorIsDeleted ()
Set that we attempted to declare an implicit copy constructor, but overload resolution failed so we deleted it.
void setImplicitMoveConstructorIsDeleted ()
Set that we attempted to declare an implicit move constructor, but overload resolution failed so we deleted it.
void setImplicitDestructorIsDeleted ()
Set that we attempted to declare an implicit destructor, but overload resolution failed so we deleted it.
bool needsImplicitMoveConstructor () const
Determine whether this class should get an implicit move constructor or if any existing special member function inhibits this.
bool needsOverloadResolutionForMoveConstructor () const
Determine whether we need to eagerly declare a defaulted move constructor for this class.
bool hasUserDeclaredCopyAssignment () const
Determine whether this class has a user-declared copy assignment operator.
void setImplicitCopyAssignmentIsDeleted ()
Set that we attempted to declare an implicit copy assignment operator, but overload resolution failed so we deleted it.
bool needsImplicitCopyAssignment () const
Determine whether this class needs an implicit copy assignment operator to be lazily declared.
bool needsOverloadResolutionForCopyAssignment () const
Determine whether we need to eagerly declare a defaulted copy assignment operator for this class.
bool implicitCopyAssignmentHasConstParam () const
Determine whether an implicit copy assignment operator for this type would have a parameter with a const-qualified reference type.
bool hasCopyAssignmentWithConstParam () const
Determine whether this class has a copy assignment operator with a parameter type which is a reference to a const-qualified type or is not a reference.
bool hasUserDeclaredMoveAssignment () const
Determine whether this class has had a move assignment declared by the user.
bool hasMoveAssignment () const
Determine whether this class has a move assignment operator.
void setImplicitMoveAssignmentIsDeleted ()
Set that we attempted to declare an implicit move assignment operator, but overload resolution failed so we deleted it.
bool needsImplicitMoveAssignment () const
Determine whether this class should get an implicit move assignment operator or if any existing special member function inhibits this.
bool needsOverloadResolutionForMoveAssignment () const
Determine whether we need to eagerly declare a move assignment operator for this class.
bool hasUserDeclaredDestructor () const
Determine whether this class has a user-declared destructor.
bool needsImplicitDestructor () const
Determine whether this class needs an implicit destructor to be lazily declared.
bool needsOverloadResolutionForDestructor () const
Determine whether we need to eagerly declare a destructor for this class.
bool isLambda () const
Determine whether this class describes a lambda function object.
bool isGenericLambda () const
Determine whether this class describes a generic lambda function object (i.e.
bool lambdaIsDefaultConstructibleAndAssignable () const
Determine whether this lambda should have an implicit default constructor and copy and move assignment operators.
CXXMethodDecl * getLambdaCallOperator () const
Retrieve the lambda call operator of the closure type if this is a closure type.
FunctionTemplateDecl * getDependentLambdaCallOperator () const
Retrieve the dependent lambda call operator of the closure type if this is a templated closure type.
CXXMethodDecl * getLambdaStaticInvoker () const
Retrieve the lambda static invoker, the address of which is returned by the conversion operator, and the body of which is forwarded to the lambda call operator.
CXXMethodDecl * getLambdaStaticInvoker (CallingConv CC) const
TemplateParameterList * getGenericLambdaTemplateParameterList () const
Retrieve the generic lambda's template parameter list.
ArrayRef< NamedDecl * > getLambdaExplicitTemplateParameters () const
Retrieve the lambda template parameters that were specified explicitly.
LambdaCaptureDefault getLambdaCaptureDefault () const
bool isCapturelessLambda () const
void setCaptures (ASTContext &Context, ArrayRef< LambdaCapture > Captures)
Set the captures for this lambda closure type.
void getCaptureFields (llvm::DenseMap< const ValueDecl *, FieldDecl * > &Captures, FieldDecl *&ThisCapture) const
For a closure type, retrieve the mapping from captured variables and this to the non-static data members that store the values or references of the captures.
capture_const_range captures () const
capture_const_iterator captures_begin () const
capture_const_iterator captures_end () const
unsigned capture_size () const
const LambdaCapture * getCapture (unsigned I) const
conversion_iterator conversion_begin () const
conversion_iterator conversion_end () const
void removeConversion (const NamedDecl *Old)
Removes a conversion function from this class.
llvm::iterator_range< conversion_iterator > getVisibleConversionFunctions () const
Get all conversion functions visible in current class, including conversion function templates.
bool isAggregate () const
Determine whether this class is an aggregate (C++ [dcl.init.aggr]), which is a class with no user-declared constructors, no private or protected non-static data members, no base classes, and no virtual functions (C++ [dcl.init.aggr]p1).
bool hasInClassInitializer () const
Whether this class has any in-class initializers for non-static data members (including those in anonymous unions or structs).
bool hasUninitializedReferenceMember () const
Whether this class or any of its subobjects has any members of reference type which would make value-initialization ill-formed.
bool isPOD () const
Whether this class is a POD-type (C++ [class]p4)
bool isCLike () const
True if this class is C-like, without C++-specific features, e.g.
bool isEmpty () const
Determine whether this is an empty class in the sense of (C++11 [meta.unary.prop]).
void markEmpty ()
Marks this record as empty.
void setInitMethod (bool Val)
bool hasInitMethod () const
bool hasPrivateFields () const
bool hasProtectedFields () const
bool hasDirectFields () const
Determine whether this class has direct non-static data members.
bool isPolymorphic () const
Whether this class is polymorphic (C++ [class.virtual]), which means that the class contains or inherits a virtual function.
bool isAbstract () const
Determine whether this class has a pure virtual function.
bool isStandardLayout () const
Determine whether this class is standard-layout per C++ [class]p7.
bool isCXX11StandardLayout () const
Determine whether this class was standard-layout per C++11 [class]p7, specifically using the C++11 rules without any DRs.
bool hasMutableFields () const
Determine whether this class, or any of its class subobjects, contains a mutable field.
bool hasVariantMembers () const
Determine whether this class has any variant members.
bool hasTrivialDefaultConstructor () const
Determine whether this class has a trivial default constructor (C++11 [class.ctor]p5).
bool hasNonTrivialDefaultConstructor () const
Determine whether this class has a non-trivial default constructor (C++11 [class.ctor]p5).
bool hasConstexprNonCopyMoveConstructor () const
Determine whether this class has at least one constexpr constructor other than the copy or move constructors.
bool defaultedDefaultConstructorIsConstexpr () const
Determine whether a defaulted default constructor for this class would be constexpr.
bool hasConstexprDefaultConstructor () const
Determine whether this class has a constexpr default constructor.
bool hasTrivialCopyConstructor () const
Determine whether this class has a trivial copy constructor (C++ [class.copy]p6, C++11 [class.copy]p12)
bool hasTrivialCopyConstructorForCall () const
bool hasNonTrivialCopyConstructor () const
Determine whether this class has a non-trivial copy constructor (C++ [class.copy]p6, C++11 [class.copy]p12)
bool hasNonTrivialCopyConstructorForCall () const
bool hasTrivialMoveConstructor () const
Determine whether this class has a trivial move constructor (C++11 [class.copy]p12)
bool hasTrivialMoveConstructorForCall () const
bool hasNonTrivialMoveConstructor () const
Determine whether this class has a non-trivial move constructor (C++11 [class.copy]p12)
bool hasNonTrivialMoveConstructorForCall () const
bool hasTrivialCopyAssignment () const
Determine whether this class has a trivial copy assignment operator (C++ [class.copy]p11, C++11 [class.copy]p25)
bool hasNonTrivialCopyAssignment () const
Determine whether this class has a non-trivial copy assignment operator (C++ [class.copy]p11, C++11 [class.copy]p25)
bool hasTrivialMoveAssignment () const
Determine whether this class has a trivial move assignment operator (C++11 [class.copy]p25)
bool hasNonTrivialMoveAssignment () const
Determine whether this class has a non-trivial move assignment operator (C++11 [class.copy]p25)
bool defaultedDestructorIsConstexpr () const
Determine whether a defaulted default constructor for this class would be constexpr.
bool hasConstexprDestructor () const
Determine whether this class has a constexpr destructor.
bool hasTrivialDestructor () const
Determine whether this class has a trivial destructor (C++ [class.dtor]p3)
bool hasTrivialDestructorForCall () const
bool hasNonTrivialDestructor () const
Determine whether this class has a non-trivial destructor (C++ [class.dtor]p3)
bool hasNonTrivialDestructorForCall () const
void setHasTrivialSpecialMemberForCall ()
bool allowConstDefaultInit () const
Determine whether declaring a const variable with this type is ok per core issue 253.
bool hasIrrelevantDestructor () const
Determine whether this class has a destructor which has no semantic effect.
bool hasNonLiteralTypeFieldsOrBases () const
Determine whether this class has a non-literal or/ volatile type non-static data member or base class.
bool hasInheritedConstructor () const
Determine whether this class has a using-declaration that names a user-declared base class constructor.
bool hasInheritedAssignment () const
Determine whether this class has a using-declaration that names a base class assignment operator.
bool isTriviallyCopyable () const
Determine whether this class is considered trivially copyable per (C++11 [class]p6).
bool isTriviallyCopyConstructible () const
Determine whether this class is considered trivially copyable per.
bool isTrivial () const
Determine whether this class is considered trivial.
bool isLiteral () const
Determine whether this class is a literal type.
bool isStructural () const
Determine whether this is a structural type.
void addedSelectedDestructor (CXXDestructorDecl *DD)
Notify the class that this destructor is now selected.
void addedEligibleSpecialMemberFunction (const CXXMethodDecl *MD, unsigned SMKind)
Notify the class that an eligible SMF has been added.
CXXRecordDecl * getInstantiatedFromMemberClass () const
If this record is an instantiation of a member class, retrieves the member class from which it was instantiated.
MemberSpecializationInfo * getMemberSpecializationInfo () const
If this class is an instantiation of a member class of a class template specialization, retrieves the member specialization information.
void setInstantiationOfMemberClass (CXXRecordDecl *RD, TemplateSpecializationKind TSK)
Specify that this record is an instantiation of the member class RD.
ClassTemplateDecl * getDescribedClassTemplate () const
Retrieves the class template that is described by this class declaration.
void setDescribedClassTemplate (ClassTemplateDecl *Template)
TemplateSpecializationKind getTemplateSpecializationKind () const
Determine whether this particular class is a specialization or instantiation of a class template or member class of a class template, and how it was instantiated or specialized.
void setTemplateSpecializationKind (TemplateSpecializationKind TSK)
Set the kind of specialization or template instantiation this is.
const CXXRecordDecl * getTemplateInstantiationPattern () const
Retrieve the record declaration from which this record could be instantiated.
CXXRecordDecl * getTemplateInstantiationPattern ()
CXXDestructorDecl * getDestructor () const
Returns the destructor decl for this class.
bool isAnyDestructorNoReturn () const
Returns true if the class destructor, or any implicitly invoked destructors are marked noreturn.
const FunctionDecl * isLocalClass () const
If the class is a local class [class.local], returns the enclosing function declaration.
FunctionDecl * isLocalClass ()
bool isCurrentInstantiation (const DeclContext *CurContext) const
Determine whether this dependent class is a current instantiation, when viewed from within the given context.
bool isDerivedFrom (const CXXRecordDecl *Base) const
Determine whether this class is derived from the class Base.
bool isDerivedFrom (const CXXRecordDecl *Base, CXXBasePaths &Paths) const
Determine whether this class is derived from the type Base.
bool isVirtuallyDerivedFrom (const CXXRecordDecl *Base) const
Determine whether this class is virtually derived from the class Base.
bool isProvablyNotDerivedFrom (const CXXRecordDecl *Base) const
Determine whether this class is provably not derived from the type Base.
bool forallBases (ForallBasesCallback BaseMatches) const
Determines if the given callback holds for all the direct or indirect base classes of this type.
bool lookupInBases (BaseMatchesCallback BaseMatches, CXXBasePaths &Paths, bool LookupInDependent=false) const
Look for entities within the base classes of this C++ class, transitively searching all base class subobjects.
void getFinalOverriders (CXXFinalOverriderMap &FinaOverriders) const
Retrieve the final overriders for each virtual member function in the class hierarchy where this class is the most-derived class in the class hierarchy.
void getIndirectPrimaryBases (CXXIndirectPrimaryBaseSet &Bases) const
Get the indirect primary bases for this class.
bool hasMemberName (DeclarationName N) const
Determine whether this class has a member with the given name, possibly in a non-dependent base class.
std::vector< const NamedDecl * > lookupDependentName (DeclarationName Name, llvm::function_ref< bool(const NamedDecl *ND)> Filter)
Performs an imprecise lookup of a dependent name in this class.
void viewInheritance (ASTContext &Context) const
Renders and displays an inheritance diagram for this C++ class and all of its base classes (transitively) using GraphViz.
void finishedDefaultedOrDeletedMember (CXXMethodDecl *MD)
Indicates that the declaration of a defaulted or deleted special member function is now complete.
void setTrivialForCallFlags (CXXMethodDecl *MD)
void completeDefinition () override
Indicates that the definition of this class is now complete.
void completeDefinition (CXXFinalOverriderMap *FinalOverriders)
Indicates that the definition of this class is now complete, and provides a final overrider map to help determine.
bool mayBeAbstract () const
Determine whether this class may end up being abstract, even though it is not yet known to be abstract.
bool isEffectivelyFinal () const
Determine whether it's impossible for a class to be derived from this class.
unsigned getLambdaManglingNumber () const
If this is the closure type of a lambda expression, retrieve the number to be used for name mangling in the Itanium C++ ABI.
bool hasKnownLambdaInternalLinkage () const
The lambda is known to has internal linkage no matter whether it has name mangling number.
Decl * getLambdaContextDecl () const
Retrieve the declaration that provides additional context for a lambda, when the normal declaration context is not specific enough.
unsigned getLambdaIndexInContext () const
Retrieve the index of this lambda within the context declaration returned by getLambdaContextDecl().
void setLambdaNumbering (LambdaNumbering Numbering)
Set the mangling numbers and context declaration for a lambda class.
LambdaNumbering getLambdaNumbering () const
unsigned getDeviceLambdaManglingNumber () const
Retrieve the device side mangling number.
MSInheritanceModel getMSInheritanceModel () const
Returns the inheritance model used for this record.
MSInheritanceModel calculateInheritanceModel () const
Calculate what the inheritance model would be for this class.
bool nullFieldOffsetIsZero () const
In the Microsoft C++ ABI, use zero for the field offset of a null data member pointer if we can guarantee that zero is not a valid field offset, or if the member pointer has multiple fields.
MSVtorDispMode getMSVtorDispMode () const
Controls when vtordisps will be emitted if this record is used as a virtual base.
bool isDependentLambda () const
Determine whether this lambda expression was known to be dependent at the time it was created, even if its context does not appear to be dependent.
bool isNeverDependentLambda () const
unsigned getLambdaDependencyKind () const
TypeSourceInfo * getLambdaTypeInfo () const
void setLambdaTypeInfo (TypeSourceInfo *TS)
void setLambdaDependencyKind (unsigned Kind)
void setLambdaIsGeneric (bool IsGeneric)
bool isInterfaceLike () const
void markAbstract ()
Public Member Functions inherited from clang::RecordDecl
RecordDecl * getPreviousDecl ()
const RecordDecl * getPreviousDecl () const
RecordDecl * getMostRecentDecl ()
const RecordDecl * getMostRecentDecl () const
bool hasFlexibleArrayMember () const
void setHasFlexibleArrayMember (bool V)
bool isAnonymousStructOrUnion () const
Whether this is an anonymous struct or union.
void setAnonymousStructOrUnion (bool Anon)
bool hasObjectMember () const
void setHasObjectMember (bool val)
bool hasVolatileMember () const
void setHasVolatileMember (bool val)
bool hasLoadedFieldsFromExternalStorage () const
void setHasLoadedFieldsFromExternalStorage (bool val) const
bool isNonTrivialToPrimitiveDefaultInitialize () const
Functions to query basic properties of non-trivial C structs.
void setNonTrivialToPrimitiveDefaultInitialize (bool V)
bool isNonTrivialToPrimitiveCopy () const
void setNonTrivialToPrimitiveCopy (bool V)
bool isNonTrivialToPrimitiveDestroy () const
void setNonTrivialToPrimitiveDestroy (bool V)
bool hasNonTrivialToPrimitiveDefaultInitializeCUnion () const
void setHasNonTrivialToPrimitiveDefaultInitializeCUnion (bool V)
bool hasNonTrivialToPrimitiveDestructCUnion () const
void setHasNonTrivialToPrimitiveDestructCUnion (bool V)
bool hasNonTrivialToPrimitiveCopyCUnion () const
void setHasNonTrivialToPrimitiveCopyCUnion (bool V)
bool canPassInRegisters () const
Determine whether this class can be passed in registers.
RecordArgPassingKind getArgPassingRestrictions () const
void setArgPassingRestrictions (RecordArgPassingKind Kind)
bool isParamDestroyedInCallee () const
void setParamDestroyedInCallee (bool V)
bool isRandomized () const
void setIsRandomized (bool V)
void reorderDecls (const SmallVectorImpl< Decl * > &Decls)
bool isInjectedClassName () const
Determines whether this declaration represents the injected class name.
bool isLambda () const
Determine whether this record is a class describing a lambda function object.
bool isCapturedRecord () const
Determine whether this record is a record for captured variables in CapturedStmt construct.
void setCapturedRecord ()
Mark the record as a record for captured variables in CapturedStmt construct.
RecordDecl * getDefinition () const
Returns the RecordDecl that actually defines this struct/union/class.
bool isOrContainsUnion () const
Returns whether this record is a union, or contains (at any nesting level) a union member.
field_range fields () const
field_iterator field_begin () const
field_iterator field_end () const
bool field_empty () const
bool isMsStruct (const ASTContext &C) const
Get whether or not this is an ms_struct which can be turned on with an attribute, pragma, or -mms-bitfields commandline option.
bool mayInsertExtraPadding (bool EmitRemark=false) const
Whether we are allowed to insert extra padding between fields.
const FieldDecl * findFirstNamedDataMember () const
Finds the first data member which has a name.
unsigned getODRHash ()
Get precomputed ODRHash or add a new one.
Public Member Functions inherited from clang::TagDecl
SourceRange getBraceRange () const
void setBraceRange (SourceRange R)
SourceLocation getInnerLocStart () const
Return SourceLocation representing start of source range ignoring outer template declarations.
SourceLocation getOuterLocStart () const
Return SourceLocation representing start of source range taking into account any outer template declarations.
SourceRange getSourceRange () const override LLVM_READONLY
Source range that this declaration covers.
const TagDecl * getCanonicalDecl () const
bool isThisDeclarationADefinition () const
Return true if this declaration is a completion definition of the type.
bool isCompleteDefinition () const
Return true if this decl has its body fully specified.
void setCompleteDefinition (bool V=true)
True if this decl has its body fully specified.
bool isCompleteDefinitionRequired () const
Return true if this complete decl is required to be complete for some existing use.
void setCompleteDefinitionRequired (bool V=true)
True if this complete decl is required to be complete for some existing use.
bool isBeingDefined () const
Return true if this decl is currently being defined.
bool isEmbeddedInDeclarator () const
True if this tag declaration is "embedded" (i.e., defined or declared for the very first time) in the syntax of a declarator.
void setEmbeddedInDeclarator (bool isInDeclarator)
True if this tag declaration is "embedded" (i.e., defined or declared for the very first time) in the syntax of a declarator.
bool isFreeStanding () const
True if this tag is free standing, e.g. "struct foo;".
void setFreeStanding (bool isFreeStanding=true)
True if this tag is free standing, e.g. "struct foo;".
bool mayHaveOutOfDateDef () const
Indicates whether it is possible for declarations of this kind to have an out-of-date definition.
bool isDependentType () const
Whether this declaration declares a type that is dependent, i.e., a type that somehow depends on template parameters.
bool isThisDeclarationADemotedDefinition () const
Whether this declaration was a definition in some module but was forced to be a declaration.
void demoteThisDefinitionToDeclaration ()
Mark a definition as a declaration and maintain information it was a definition.
void startDefinition ()
Starts the definition of this tag declaration.
TagDecl * getDefinition () const
Returns the TagDecl that actually defines this struct/union/class/enum.
StringRef getKindName () const
TagKind getTagKind () const
void setTagKind (TagKind TK)
bool isStruct () const
bool isInterface () const
bool isClass () const
bool isUnion () const
bool isEnum () const
bool hasNameForLinkage () const
Is this tag type named, either directly or via being defined in a typedef of this type?
TypedefNameDecl * getTypedefNameForAnonDecl () const
void setTypedefNameForAnonDecl (TypedefNameDecl *TDD)
NestedNameSpecifier * getQualifier () const
Retrieve the nested-name-specifier that qualifies the name of this declaration, if it was present in the source.
NestedNameSpecifierLoc getQualifierLoc () const
Retrieve the nested-name-specifier (with source-location information) that qualifies the name of this declaration, if it was present in the source.
void setQualifierInfo (NestedNameSpecifierLoc QualifierLoc)
unsigned getNumTemplateParameterLists () const
TemplateParameterList * getTemplateParameterList (unsigned i) const
void printName (raw_ostream &OS, const PrintingPolicy &Policy) const override
Pretty-print the unqualified name of this declaration.
void setTemplateParameterListsInfo (ASTContext &Context, ArrayRef< TemplateParameterList * > TPLists)
Public Member Functions inherited from clang::TypeDecl
const Type * getTypeForDecl () const
void setTypeForDecl (const Type *TD)
SourceLocation getBeginLoc () const LLVM_READONLY
void setLocStart (SourceLocation L)
Public Member Functions inherited from clang::NamedDecl
IdentifierInfo * getIdentifier () const
Get the identifier that names this declaration, if there is one.
StringRef getName () const
Get the name of identifier for this declaration as a StringRef.
std::string getNameAsString () const
Get a human-readable name for the declaration, even if it is one of the special kinds of names (C++ constructor, Objective-C selector, etc).
void printName (raw_ostream &OS) const
Calls printName() with the ASTContext printing policy from the decl.
DeclarationName getDeclName () const
Get the actual, stored name of the declaration, which may be a special name.
void setDeclName (DeclarationName N)
Set the name of this declaration.
void printQualifiedName (raw_ostream &OS) const
Returns a human-readable qualified name for this declaration, like A::B::i, for i being member of namespace A::B.
void printQualifiedName (raw_ostream &OS, const PrintingPolicy &Policy, bool WithGlobalNsPrefix=false) const
void printNestedNameSpecifier (raw_ostream &OS) const
Print only the nested name specifier part of a fully-qualified name, including the '::' at the end.
void printNestedNameSpecifier (raw_ostream &OS, const PrintingPolicy &Policy, bool WithGlobalNsPrefix=false) const
std::string getQualifiedNameAsString (bool WithGlobalNsPrefix=false) const
virtual void getNameForDiagnostic (raw_ostream &OS, const PrintingPolicy &Policy, bool Qualified) const
Appends a human-readable name for this declaration into the given stream.
bool declarationReplaces (const NamedDecl *OldD, bool IsKnownNewer=true) const
Determine whether this declaration, if known to be well-formed within its context, will replace the declaration OldD if introduced into scope.
bool hasLinkage () const
Determine whether this declaration has linkage.
bool isCXXClassMember () const
Determine whether this declaration is a C++ class member.
bool isCXXInstanceMember () const
Determine whether the given declaration is an instance member of a C++ class.
ReservedIdentifierStatus isReserved (const LangOptions &LangOpts) const
Determine if the declaration obeys the reserved identifier rules of the given language.
Linkage getLinkageInternal () const
Determine what kind of linkage this entity has.
Linkage getFormalLinkage () const
Get the linkage from a semantic point of view.
bool hasExternalFormalLinkage () const
True if this decl has external linkage.
bool isExternallyVisible () const
bool isExternallyDeclarable () const
Determine whether this declaration can be redeclared in a different translation unit.
Visibility getVisibility () const
Determines the visibility of this entity.
LinkageInfo getLinkageAndVisibility () const
Determines the linkage and visibility of this entity.
std::optional< Visibility > getExplicitVisibility (ExplicitVisibilityKind kind) const
If visibility was explicitly specified for this declaration, return that visibility.
bool isLinkageValid () const
True if the computed linkage is valid.
bool hasLinkageBeenComputed () const
True if something has required us to compute the linkage of this declaration.
bool isPlaceholderVar (const LangOptions &LangOpts) const
NamedDecl * getUnderlyingDecl ()
Looks through UsingDecls and ObjCCompatibleAliasDecls for the underlying named decl.
const NamedDecl * getUnderlyingDecl () const
NamedDecl * getMostRecentDecl ()
const NamedDecl * getMostRecentDecl () const
ObjCStringFormatFamily getObjCFStringFormattingFamily () const
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
Public Member Functions inherited from clang::Decl
Decl ()=delete
Decl (const Decl &)=delete
Decl (Decl &&)=delete
Decl & operator= (const Decl &)=delete
Decl & operator= (Decl &&)=delete
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceLocation getLocation () const
void setLocation (SourceLocation L)
Kind getKind () const
const char * getDeclKindName () const
Decl * getNextDeclInContext ()
const Decl * getNextDeclInContext () const
DeclContext * getDeclContext ()
const DeclContext * getDeclContext () const
DeclContext * getNonTransparentDeclContext ()
Return the non transparent context.
const DeclContext * getNonTransparentDeclContext () const
Decl * getNonClosureContext ()
Find the innermost non-closure ancestor of this declaration, walking up through blocks, lambdas, etc.
const Decl * getNonClosureContext () const
TranslationUnitDecl * getTranslationUnitDecl ()
const TranslationUnitDecl * getTranslationUnitDecl () const
bool isInAnonymousNamespace () const
bool isInStdNamespace () const
bool isFileContextDecl () const
ASTContext & getASTContext () const LLVM_READONLY
const LangOptions & getLangOpts () const LLVM_READONLY
Helper to get the language options from the ASTContext.
void setAccess (AccessSpecifier AS)
AccessSpecifier getAccess () const
AccessSpecifier getAccessUnsafe () const
Retrieve the access specifier for this declaration, even though it may not yet have been properly set.
bool hasAttrs () const
void setAttrs (const AttrVec &Attrs)
AttrVec & getAttrs ()
const AttrVec & getAttrs () const
void dropAttrs ()
void addAttr (Attr *A)
attr_range attrs () const
attr_iterator attr_begin () const
attr_iterator attr_end () const
template<typename... Ts>
void dropAttrs ()
template<typename T >
void dropAttr ()
template<typename T >
llvm::iterator_range< specific_attr_iterator< T > > specific_attrs () const
template<typename T >
specific_attr_iterator< T > specific_attr_begin () const
template<typename T >
specific_attr_iterator< T > specific_attr_end () const
template<typename T >
T * getAttr () const
template<typename T >
bool hasAttr () const
unsigned getMaxAlignment () const
getMaxAlignment - return the maximum alignment specified by attributes on this decl, 0 if there are none.
void setInvalidDecl (bool Invalid=true)
setInvalidDecl - Indicates the Decl had a semantic error.
bool isInvalidDecl () const
bool isImplicit () const
isImplicit - Indicates whether the declaration was implicitly generated by the implementation.
void setImplicit (bool I=true)
bool isUsed (bool CheckUsedAttr=true) const
Whether any (re-)declaration of the entity was used, meaning that a definition is required.
void setIsUsed ()
Set whether the declaration is used, in the sense of odr-use.
void markUsed (ASTContext &C)
Mark the declaration used, in the sense of odr-use.
bool isReferenced () const
Whether any declaration of this entity was referenced.
bool isThisDeclarationReferenced () const
Whether this declaration was referenced.
void setReferenced (bool R=true)
bool isTopLevelDeclInObjCContainer () const
Whether this declaration is a top-level declaration (function, global variable, etc.) that is lexically inside an objc container definition.
void setTopLevelDeclInObjCContainer (bool V=true)
ExternalSourceSymbolAttr * getExternalSourceSymbolAttr () const
Looks on this and related declarations for an applicable external source symbol attribute.
bool isModulePrivate () const
Whether this declaration was marked as being private to the module in which it was defined.
bool isInExportDeclContext () const
Whether this declaration was exported in a lexical context.
bool isInvisibleOutsideTheOwningModule () const
bool isInAnotherModuleUnit () const
Whether this declaration comes from another module unit.
bool isFromExplicitGlobalModule () const
Whether this declaration comes from explicit global module.
bool hasDefiningAttr () const
Return true if this declaration has an attribute which acts as definition of the entity, such as 'alias' or 'ifunc'.
const Attr * getDefiningAttr () const
Return this declaration's defining attribute if it has one.
void setFromASTFile ()
Set the FromASTFile flag.
void setOwningModuleID (unsigned ID)
Set the owning module ID.
AvailabilityResult getAvailability (std::string *Message=nullptr, VersionTuple EnclosingVersion=VersionTuple(), StringRef *RealizedPlatform=nullptr) const
Determine the availability of the given declaration.
VersionTuple getVersionIntroduced () const
Retrieve the version of the target platform in which this declaration was introduced.
bool isDeprecated (std::string *Message=nullptr) const
Determine whether this declaration is marked 'deprecated'.
bool isUnavailable (std::string *Message=nullptr) const
Determine whether this declaration is marked 'unavailable'.
bool isWeakImported () const
Determine whether this is a weak-imported symbol.
bool canBeWeakImported (bool &IsDefinition) const
Determines whether this symbol can be weak-imported, e.g., whether it would be well-formed to add the weak_import attribute.
bool isFromASTFile () const
Determine whether this declaration came from an AST file (such as a precompiled header or module) rather than having been parsed.
DeclID getGlobalID () const
Retrieve the global declaration ID associated with this declaration, which specifies where this Decl was loaded from.
unsigned getOwningModuleID () const
Retrieve the global ID of the module that owns this particular declaration.
Module * getImportedOwningModule () const
Get the imported owning module, if this decl is from an imported (non-local) module.
Module * getLocalOwningModule () const
Get the local owning module, if known.
void setLocalOwningModule (Module *M)
bool hasOwningModule () const
Is this declaration owned by some module?
Module * getOwningModule () const
Get the module that owns this declaration (for visibility purposes).
Module * getOwningModuleForLinkage (bool IgnoreLinkage=false) const
Get the module that owns this declaration for linkage purposes.
bool isUnconditionallyVisible () const
Determine whether this declaration is definitely visible to name lookup, independent of whether the owning module is visible.
bool isReachable () const
void setVisibleDespiteOwningModule ()
Set that this declaration is globally visible, even if it came from a module that is not visible.
ModuleOwnershipKind getModuleOwnershipKind () const
Get the kind of module ownership for this declaration.
void setModuleOwnershipKind (ModuleOwnershipKind MOK)
Set whether this declaration is hidden from name lookup.
unsigned getIdentifierNamespace () const
bool isInIdentifierNamespace (unsigned NS) const
bool hasTagIdentifierNamespace () const
DeclContext * getLexicalDeclContext ()
getLexicalDeclContext - The declaration context where this Decl was lexically declared (LexicalDC).
const DeclContext * getLexicalDeclContext () const
virtual bool isOutOfLine () const
Determine whether this declaration is declared out of line (outside its semantic context).
void setDeclContext (DeclContext *DC)
setDeclContext - Set both the semantic and lexical DeclContext to DC.
void setLexicalDeclContext (DeclContext *DC)
bool isTemplated () const
Determine whether this declaration is a templated entity (whether it is.
unsigned getTemplateDepth () const
Determine the number of levels of template parameter surrounding this declaration.
bool isDefinedOutsideFunctionOrMethod () const
isDefinedOutsideFunctionOrMethod - This predicate returns true if this scoped decl is defined outside the current function or method.
bool isInLocalScopeForInstantiation () const
Determine whether a substitution into this declaration would occur as part of a substitution into a dependent local scope.
const DeclContext * getParentFunctionOrMethod (bool LexicalParent=false) const
If this decl is defined inside a function/method/block it returns the corresponding DeclContext, otherwise it returns null.
DeclContext * getParentFunctionOrMethod (bool LexicalParent=false)
const Decl * getCanonicalDecl () const
bool isCanonicalDecl () const
Whether this particular Decl is a canonical one.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Decl * getPreviousDecl ()
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
const Decl * getPreviousDecl () const
Retrieve the previous declaration that declares the same entity as this declaration, or NULL if there is no previous declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
Decl * getMostRecentDecl ()
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
const Decl * getMostRecentDecl () const
Retrieve the most recent declaration that declares the same entity as this declaration (which may be this declaration).
virtual Stmt * getBody () const
getBody - If this Decl represents a declaration for a body of code, such as a function or method definition, this method returns the top-level Stmt* of that body.
virtual bool hasBody () const
Returns true if this Decl represents a declaration for a body of code, such as a function or method definition.
SourceLocation getBodyRBrace () const
getBodyRBrace - Gets the right brace of the body, if a body exists.
bool isTemplateParameter () const
isTemplateParameter - Determines whether this declaration is a template parameter.
bool isTemplateParameterPack () const
isTemplateParameter - Determines whether this declaration is a template parameter pack.
bool isParameterPack () const
Whether this declaration is a parameter pack.
bool isTemplateDecl () const
returns true if this declaration is a template
bool isFunctionOrFunctionTemplate () const
Whether this declaration is a function or function template.
TemplateDecl * getDescribedTemplate () const
If this is a declaration that describes some template, this method returns that template declaration.
const TemplateParameterList * getDescribedTemplateParams () const
If this is a declaration that describes some template or partial specialization, this returns the corresponding template parameter list.
FunctionDecl * getAsFunction () LLVM_READONLY
Returns the function itself, or the templated function if this is a function template.
const FunctionDecl * getAsFunction () const
void setLocalExternDecl ()
Changes the namespace of this declaration to reflect that it's a function-local extern declaration.
bool isLocalExternDecl () const
Determine whether this is a block-scope declaration with linkage.
void setObjectOfFriendDecl (bool PerformFriendInjection=false)
Changes the namespace of this declaration to reflect that it's the object of a friend declaration.
void clearIdentifierNamespace ()
Clears the namespace of this declaration.
FriendObjectKind getFriendObjectKind () const
Determines whether this declaration is the object of a friend declaration and, if so, what kind.
void setNonMemberOperator ()
Specifies that this declaration is a C++ overloaded non-member.
void print (raw_ostream &Out, unsigned Indentation=0, bool PrintInstantiation=false) const
void print (raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0, bool PrintInstantiation=false) const
void dump () const
void dumpColor () const
void dump (raw_ostream &Out, bool Deserialize=false, ASTDumpOutputFormat OutputFormat=ADOF_Default) const
int64_t getID () const
const FunctionType * getFunctionType (bool BlocksToo=true) const
Looks through the Decl's underlying type to extract a FunctionType when possible.
bool isFunctionPointerType () const
Public Member Functions inherited from clang::DeclContext
~DeclContext ()
bool hasValidDeclKind () const
Decl::Kind getDeclKind () const
const char * getDeclKindName () const
DeclContext * getParent ()
getParent - Returns the containing DeclContext.
const DeclContext * getParent () const
DeclContext * getLexicalParent ()
getLexicalParent - Returns the containing lexical DeclContext.
const DeclContext * getLexicalParent () const
DeclContext * getLookupParent ()
Find the parent context of this context that will be used for unqualified name lookup.
const DeclContext * getLookupParent () const
ASTContext & getParentASTContext () const
bool isClosure () const
const BlockDecl * getInnermostBlockDecl () const
Return this DeclContext if it is a BlockDecl.
bool isObjCContainer () const
bool isFunctionOrMethod () const
bool isLookupContext () const
Test whether the context supports looking up names.
bool isFileContext () const
bool isTranslationUnit () const
bool isRecord () const
bool isNamespace () const
bool isStdNamespace () const
bool isInlineNamespace () const
bool isDependentContext () const
Determines whether this context is dependent on a template parameter.
bool isTransparentContext () const
isTransparentContext - Determines whether this context is a "transparent" context, meaning that the members declared in this context are semantically declared in the nearest enclosing non-transparent (opaque) context but are lexically declared in this context.
bool isExternCContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C linkage.
const LinkageSpecDecl * getExternCContext () const
Retrieve the nearest enclosing C linkage specification context.
bool isExternCXXContext () const
Determines whether this context or some of its ancestors is a linkage specification context that specifies C++ linkage.
bool Equals (const DeclContext *DC) const
Determine whether this declaration context is equivalent to the declaration context DC.
bool Encloses (const DeclContext *DC) const
Determine whether this declaration context encloses the declaration context DC.
Decl * getNonClosureAncestor ()
Find the nearest non-closure ancestor of this context, i.e.
const Decl * getNonClosureAncestor () const
DeclContext * getNonTransparentContext ()
const DeclContext * getNonTransparentContext () const
DeclContext * getPrimaryContext ()
getPrimaryContext - There may be many different declarations of the same entity (including forward declarations of classes, multiple definitions of namespaces, etc.), each with a different set of declarations.
const DeclContext * getPrimaryContext () const
DeclContext * getRedeclContext ()
getRedeclContext - Retrieve the context in which an entity conflicts with other entities of the same name, or where it is a redeclaration if the two entities are compatible.
const DeclContext * getRedeclContext () const
DeclContext * getEnclosingNamespaceContext ()
Retrieve the nearest enclosing namespace context.
const DeclContext * getEnclosingNamespaceContext () const
RecordDecl * getOuterLexicalRecordContext ()
Retrieve the outermost lexically enclosing record context.
const RecordDecl * getOuterLexicalRecordContext () const
bool InEnclosingNamespaceSetOf (const DeclContext *NS) const
Test if this context is part of the enclosing namespace set of the context NS, as defined in C++0x [namespace.def]p9.
void collectAllContexts (SmallVectorImpl< DeclContext * > &Contexts)
Collects all of the declaration contexts that are semantically connected to this declaration context.
decl_range decls () const
decls_begin/decls_end - Iterate over the declarations stored in this context.
decl_iterator decls_begin () const
decl_iterator decls_end () const
bool decls_empty () const
decl_range noload_decls () const
noload_decls_begin/end - Iterate over the declarations stored in this context that are currently loaded; don't attempt to retrieve anything from an external source.
decl_iterator noload_decls_begin () const
decl_iterator noload_decls_end () const
void addDecl (Decl *D)
Add the declaration D into this context.
void addDeclInternal (Decl *D)
Add the declaration D into this context, but suppress searches for external declarations with the same name.
void addHiddenDecl (Decl *D)
Add the declaration D to this context without modifying any lookup tables.
void removeDecl (Decl *D)
Removes a declaration from this context.
bool containsDecl (Decl *D) const
Checks whether a declaration is in this context.
bool containsDeclAndLoad (Decl *D) const
Checks whether a declaration is in this context.
lookup_result lookup (DeclarationName Name) const
lookup - Find the declarations (if any) with the given Name in this context.
lookup_result noload_lookup (DeclarationName Name)
Find the declarations with the given name that are visible within this context; don't attempt to retrieve anything from an external source.
void localUncachedLookup (DeclarationName Name, SmallVectorImpl< NamedDecl * > &Results)
A simplistic name lookup mechanism that performs name lookup into this declaration context without consulting the external source.
void makeDeclVisibleInContext (NamedDecl *D)
Makes a declaration visible within this context.
lookups_range lookups () const
lookups_range noload_lookups (bool PreserveInternalState) const
all_lookups_iterator lookups_begin () const
Iterators over all possible lookups within this context.
all_lookups_iterator lookups_end () const
all_lookups_iterator noload_lookups_begin () const
Iterators over all possible lookups within this context that are currently loaded; don't attempt to retrieve anything from an external source.
all_lookups_iterator noload_lookups_end () const
udir_range using_directives () const
Returns iterator range [First, Last) of UsingDirectiveDecls stored within this context.
ddiag_range ddiags () const
void setMustBuildLookupTable ()
Mark that there are external lexical declarations that we need to include in our lookup table (and that are not available as external visible lookups).
StoredDeclsMap * getLookupPtr () const
Retrieve the internal representation of the lookup structure.
StoredDeclsMap * buildLookup ()
Ensure the lookup structure is fully-built and return it.
bool hasExternalLexicalStorage () const
Whether this DeclContext has external storage containing additional declarations that are lexically in this context.
void setHasExternalLexicalStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations lexically in this context.
bool hasExternalVisibleStorage () const
Whether this DeclContext has external storage containing additional declarations that are visible in this context.
void setHasExternalVisibleStorage (bool ES=true) const
State whether this DeclContext has external storage for declarations visible in this context.
bool isDeclInLexicalTraversal (const Decl *D) const
Determine whether the given declaration is stored in the list of declarations lexically within this context.
void setUseQualifiedLookup (bool use=true) const
bool shouldUseQualifiedLookup () const
void dumpAsDecl () const
void dumpAsDecl (const ASTContext *Ctx) const
void dumpDeclContext () const
void dumpLookups () const
void dumpLookups (llvm::raw_ostream &OS, bool DumpDecls=false, bool Deserialize=false) const
Public Member Functions inherited from clang::Redeclarable< TagDecl >
Redeclarable (const ASTContext &Ctx)
TagDecl * getPreviousDecl ()
Return the previous declaration of this declaration or NULL if this is the first declaration.
const TagDecl * getPreviousDecl () const
TagDecl * getFirstDecl ()
Return the first declaration of this declaration or itself if this is the only declaration.
const TagDecl * getFirstDecl () const
Return the first declaration of this declaration or itself if this is the only declaration.
bool isFirstDecl () const
True if this is the first declaration in its redeclaration chain.
TagDecl * getMostRecentDecl ()
Returns the most recent (re)declaration of this declaration.
const TagDecl * getMostRecentDecl () const
Returns the most recent (re)declaration of this declaration.
void setPreviousDecl (TagDecl *PrevDecl)
Set the previous declaration.
redecl_range redecls () const
Returns an iterator range for all the redeclarations of the same decl.
redecl_iterator redecls_begin () const
redecl_iterator redecls_end () const
Static Public Member Functions
static CXXRecordDecl * Create (const ASTContext &C, TagKind TK, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, CXXRecordDecl *PrevDecl=nullptr, bool DelayTypeCreation=false)
static CXXRecordDecl * CreateLambda (const ASTContext &C, DeclContext *DC, TypeSourceInfo *Info, SourceLocation Loc, unsigned DependencyKind, bool IsGeneric, LambdaCaptureDefault CaptureDefault)
static CXXRecordDecl * CreateDeserialized (const ASTContext &C, DeclID ID)
static bool FindBaseClass (const CXXBaseSpecifier *Specifier, CXXBasePath &Path, const CXXRecordDecl *BaseRecord)
Base-class lookup callback that determines whether the given base class specifier refers to a specific class declaration.
static bool FindVirtualBaseClass (const CXXBaseSpecifier *Specifier, CXXBasePath &Path, const CXXRecordDecl *BaseRecord)
Base-class lookup callback that determines whether the given base class specifier refers to a specific class declaration and describes virtual derivation.
static AccessSpecifier MergeAccess (AccessSpecifier PathAccess, AccessSpecifier DeclAccess)
Calculates the access of a decl that is reached along a path.
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::RecordDecl
static RecordDecl * Create (const ASTContext &C, TagKind TK, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, RecordDecl *PrevDecl=nullptr)
static RecordDecl * CreateDeserialized (const ASTContext &C, DeclID ID)
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::TagDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const TagDecl *D)
static TagDecl * castFromDeclContext (const DeclContext *DC)
Static Public Member Functions inherited from clang::TypeDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::NamedDecl
static bool classof (const Decl *D)
static bool classofKind (Kind K)
Static Public Member Functions inherited from clang::Decl
static bool isFlexibleArrayMemberLike (ASTContext &Context, const Decl *D, QualType Ty, LangOptions::StrictFlexArraysLevelKind StrictFlexArraysLevel, bool IgnoreTemplateOrMacroSubstitution)
Whether it resembles a flexible array member.
static unsigned getIdentifierNamespaceForKind (Kind DK)
static bool isTagIdentifierNamespace (unsigned NS)
static void add (Kind k)
static void EnableStatistics ()
static void PrintStats ()
static bool classofKind (Kind K)
static DeclContext * castToDeclContext (const Decl *)
static Decl * castFromDeclContext (const DeclContext *)
static void printGroup (Decl **Begin, unsigned NumDecls, raw_ostream &Out, const PrintingPolicy &Policy, unsigned Indentation=0)
Static Public Member Functions inherited from clang::DeclContext
static bool classof (const Decl *D)
static bool classof (const DeclContext *D)
Protected Member Functions
CXXRecordDecl (Kind K, TagKind TK, const ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, CXXRecordDecl *PrevDecl)
Protected Member Functions inherited from clang::RecordDecl
RecordDecl (Kind DK, TagKind TK, const ASTContext &C, DeclContext *DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo *Id, RecordDecl *PrevDecl)
Protected Member Functions inherited from clang::TagDecl
TagDecl (Kind DK, TagKind TK, const ASTContext &C, DeclContext *DC, SourceLocation L, IdentifierInfo *Id, TagDecl *PrevDecl, SourceLocation StartL)
TagDecl * getNextRedeclarationImpl () override
Returns the next redeclaration or itself if this is the only decl.
TagDecl * getPreviousDeclImpl () override
Implementation of getPreviousDecl(), to be overridden by any subclass that has a redeclaration chain.
TagDecl * getMostRecentDeclImpl () override
Implementation of getMostRecentDecl(), to be overridden by any subclass that has a redeclaration chain.
void completeDefinition ()
Completes the definition of this tag declaration.
void setBeingDefined (bool V=true)
True if this decl is currently being defined.
void setMayHaveOutOfDateDef (bool V=true)
Indicates whether it is possible for declarations of this kind to have an out-of-date definition.
Protected Member Functions inherited from clang::TypeDecl
TypeDecl (Kind DK, DeclContext *DC, SourceLocation L, const IdentifierInfo *Id, SourceLocation StartL=SourceLocation())
Protected Member Functions inherited from clang::NamedDecl
NamedDecl (Kind DK, DeclContext *DC, SourceLocation L, DeclarationName N)
Protected Member Functions inherited from clang::Decl
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclID ID, std::size_t Extra=0)
Allocate memory for a deserialized declaration.
void * operator new (std::size_t Size, const ASTContext &Ctx, DeclContext *Parent, std::size_t Extra=0)
Allocate memory for a non-deserialized declaration.
Decl (Kind DK, DeclContext *DC, SourceLocation L)
Decl (Kind DK, EmptyShell Empty)
virtual ~Decl ()
void updateOutOfDate (IdentifierInfo &II) const
Update a potentially out-of-date declaration.
Linkage getCachedLinkage () const
void setCachedLinkage (Linkage L) const
bool hasCachedLinkage () const
void setModulePrivate ()
Specify that this declaration was marked as being private to the module in which it was defined.
bool hasLocalOwningModuleStorage () const
ASTMutationListener * getASTMutationListener () const
Protected Member Functions inherited from clang::DeclContext
DeclContext (Decl::Kind K)
Protected Member Functions inherited from clang::Redeclarable< TagDecl >
TagDecl * getNextRedeclaration () const
Friends
class ASTDeclReader
class ASTDeclWriter
class ASTNodeImporter
class ASTReader
class ASTRecordWriter
class ASTWriter
class DeclContext
class LambdaExpr
class ODRDiagsEmitter
void FunctionDecl::setIsPureVirtual (bool)
void TagDecl::startDefinition ()
Additional Inherited Members
Protected Types inherited from clang::TagDecl
using redeclarable_base = Redeclarable< TagDecl >
Static Protected Member Functions inherited from clang::DeclContext
static std::pair< Decl *, Decl * > BuildDeclChain (ArrayRef< Decl * > Decls, bool FieldsAlreadyLoaded)
Build up a chain of declarations.
Static Protected Member Functions inherited from clang::Redeclarable< TagDecl >
static DeclLink PreviousDeclLink (TagDecl *D)
static DeclLink LatestDeclLink (const ASTContext &Ctx)
Protected Attributes inherited from clang::Decl
llvm::PointerIntPair< Decl *, 3, ModuleOwnershipKind > NextInContextAndBits
The next declaration within the same lexical DeclContext.
unsigned Access: 2
Access - Used by C++ decls for the access specifier.
unsigned FromASTFile: 1
Whether this declaration was loaded from an AST file.
unsigned IdentifierNamespace: 14
IdentifierNamespace - This specifies what IDNS_* namespace this lives in.
unsigned CacheValidAndLinkage: 3
If 0, we have not computed the linkage of this declaration.
Protected Attributes inherited from clang::DeclContext
union {
DeclContextBitfields DeclContextBits
TagDeclBitfields TagDeclBits
EnumDeclBitfields EnumDeclBits
RecordDeclBitfields RecordDeclBits
OMPDeclareReductionDeclBitfields OMPDeclareReductionDeclBits
FunctionDeclBitfields FunctionDeclBits
CXXConstructorDeclBitfields CXXConstructorDeclBits
ObjCMethodDeclBitfields ObjCMethodDeclBits
ObjCContainerDeclBitfields ObjCContainerDeclBits
LinkageSpecDeclBitfields LinkageSpecDeclBits
BlockDeclBitfields BlockDeclBits
};
This anonymous union stores the bits belonging to DeclContext and classes deriving from it.
Decl * FirstDecl = nullptr
FirstDecl - The first declaration stored within this declaration context.
Decl * LastDecl = nullptr
LastDecl - The last declaration stored within this declaration context.
Protected Attributes inherited from clang::Redeclarable< TagDecl >
DeclLink RedeclLink
Points to the next redeclaration in the chain.
TagDecl * First
Detailed Description
Represents a C++ struct/union/class.
Definition at line 258 of file DeclCXX.h.
Member Typedef Documentation
base_class_const_iterator
using clang::CXXRecordDecl::base_class_const_iterator = const CXXBaseSpecifier *
Iterator that traverses the base classes of a class.
Definition at line 521 of file DeclCXX.h.
base_class_const_range
using clang::CXXRecordDecl::base_class_const_range = llvm::iterator_range<base_class_const_iterator>
Definition at line 615 of file DeclCXX.h.
base_class_iterator
using clang::CXXRecordDecl::base_class_iterator = CXXBaseSpecifier *
Iterator that traverses the base classes of a class.
Definition at line 518 of file DeclCXX.h.
base_class_range
using clang::CXXRecordDecl::base_class_range = llvm::iterator_range<base_class_iterator>
Definition at line 614 of file DeclCXX.h.
BaseMatchesCallback
using clang::CXXRecordDecl::BaseMatchesCallback = llvm::function_ref<bool(const CXXBaseSpecifier *Specifier, CXXBasePath &Path)>
Function type used by lookupInBases() to determine whether a specific base class subobject matches the lookup criteria.
Parameters
Specifier the base-class specifier that describes the inheritance from the base class we are trying to match.
Path the current path, from the most-derived class down to the base named by the Specifier.
Returns
true if this base matched the search criteria, false otherwise.
Definition at line 1640 of file DeclCXX.h.
capture_const_iterator
using clang::CXXRecordDecl::capture_const_iterator = const LambdaCapture *
Definition at line 1097 of file DeclCXX.h.
capture_const_range
using clang::CXXRecordDecl::capture_const_range = llvm::iterator_range<capture_const_iterator>
Definition at line 1098 of file DeclCXX.h.
conversion_iterator
using clang::CXXRecordDecl::conversion_iterator = UnresolvedSetIterator
Definition at line 1122 of file DeclCXX.h.
ctor_iterator
using clang::CXXRecordDecl::ctor_iterator = specific_decl_iterator<CXXConstructorDecl>
Iterator access to constructor members.
Definition at line 676 of file DeclCXX.h.
ctor_range
using clang::CXXRecordDecl::ctor_range = llvm::iterator_range<specific_decl_iterator<CXXConstructorDecl> >
Definition at line 677 of file DeclCXX.h.
ForallBasesCallback
using clang::CXXRecordDecl::ForallBasesCallback = llvm::function_ref<bool(const CXXRecordDecl *BaseDefinition)>
Function type used by forallBases() as a callback.
Parameters
BaseDefinition the definition of the base class
Returns
true if this base matched the search criteria
Definition at line 1617 of file DeclCXX.h.
friend_range
using clang::CXXRecordDecl::friend_range = llvm::iterator_range<friend_iterator>
Definition at line 693 of file DeclCXX.h.
method_iterator
using clang::CXXRecordDecl::method_iterator = specific_decl_iterator<CXXMethodDecl>
Iterator access to method members.
The method iterator visits all method members of the class, including non-instance methods, special methods, etc.
Definition at line 656 of file DeclCXX.h.
method_range
using clang::CXXRecordDecl::method_range = llvm::iterator_range<specific_decl_iterator<CXXMethodDecl> >
Definition at line 657 of file DeclCXX.h.
Member Enumeration Documentation
LambdaDependencyKind
enum clang::CXXRecordDecl::LambdaDependencyKind
Enumerator
LDK_Unknown
LDK_AlwaysDependent
LDK_NeverDependent
Definition at line 284 of file DeclCXX.h.
Constructor & Destructor Documentation
CXXRecordDecl()
CXXRecordDecl::CXXRecordDecl (Kind K, TagKind TK, const ASTContext & C, DeclContext * DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo * Id, CXXRecordDecl * PrevDecl) protected
Definition at line 123 of file DeclCXX.cpp.
Referenced by CreateDeserialized(), and CreateLambda().
Member Function Documentation
addedEligibleSpecialMemberFunction()
void CXXRecordDecl::addedEligibleSpecialMemberFunction (const CXXMethodDecl * MD, unsigned SMKind)
Notify the class that an eligible SMF has been added.
This updates triviality and destructor based properties of the class accordingly.
Definition at line 1419 of file DeclCXX.cpp.
References clang::Decl::isImplicit(), clang::FunctionDecl::isTrivial(), clang::FunctionDecl::isTrivialForCall(), and clang::FunctionDecl::isUserProvided().
Referenced by addedSelectedDestructor().
addedSelectedDestructor()
void CXXRecordDecl::addedSelectedDestructor (CXXDestructorDecl * DD)
Notify the class that this destructor is now selected.
Important properties of the class depend on destructor properties. Since C++20, it is possible to have multiple destructor declarations in a class out of which one will be selected at the end. This is called separately from addedMember because it has to be deferred to the completion of the class.
Definition at line 1414 of file DeclCXX.cpp.
References addedEligibleSpecialMemberFunction(), and clang::FunctionDecl::setIneligibleOrNotSelected().
allowConstDefaultInit()
bool clang::CXXRecordDecl::allowConstDefaultInit () const inline
Determine whether declaring a const variable with this type is ok per core issue 253.
Definition at line 1391 of file DeclCXX.h.
References needsImplicitDefaultConstructor().
bases() [1/2]
base_class_range clang::CXXRecordDecl::bases () inline
Definition at line 618 of file DeclCXX.h.
References bases_begin(), and bases_end().
Referenced by clang::Sema::CheckComparisonCategoryType(), CheckConstexprDestructorSubobjects(), clang::Sema::checkIllFormedTrivialABIStruct(), collectPublicBases(), ComputeVMIClassTypeInfoFlags(), clang::Sema::DefineImplicitCopyAssignment(), clang::Sema::DefineImplicitMoveAssignment(), clang::Sema::DefineInheritingConstructor(), DiagnoseBaseOrMemInitializerOrder(), diagnoseMutableFields(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), FindBaseInitializer(), findDirectBaseWithType(), clang::CXXMethodDecl::getCorrespondingMethodInClass(), clang::NestedNameSpecifier::getDependence(), clang::CodeGen::CodeGenModule::getMostBaseClasses(), clang::dataflow::getOptionalBaseClass(), clang::interp::Context::getOverridingFunction(), clang::CodeGen::CodeGenModule::GetVCallVisibilityLevel(), clang::CodeGen::CodeGenFunction::getVTablePointers(), HandleDestructionImpl(), hasRepeatedBaseClass(), clang::SemaCUDA::inferTargetForImplicitSpecialMember(), isBaseClassPublic(), IsDerivedFromInclusive(), isDirectVBase(), clang::SemaCUDA::isEmptyDestructor(), IsPartOfAST(), isReadByLvalueToRvalueConversion(), isVirtualDirectBase(), isZeroInitialized(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), clang::Sema::MarkVirtualMembersReferenced(), mayBeAbstract(), clang::Sema::RequireLiteralType(), RequiresVtordisp(), serializeClassHierarchy(), clang::Sema::SetCtorInitializers(), clang::Sema::SpecialMemberIsTrivial(), clang::Sema::SubstBaseSpecifiers(), clang::TextNodeDumper::VisitCXXRecordDecl(), and clang::JSONNodeDumper::VisitCXXRecordDecl().
bases() [2/2]
base_class_const_range clang::CXXRecordDecl::bases () const inline
Definition at line 621 of file DeclCXX.h.
References bases_begin(), and bases_end().
bases_begin() [1/2]
base_class_iterator clang::CXXRecordDecl::bases_begin () inline
Definition at line 625 of file DeclCXX.h.
Referenced by addAssociatedClassesAndNamespaces(), bases(), bases_end(), CanUseSingleInheritance(), getNonCLikeKindForAnonymousStruct(), clang::interp::Context::getOverridingFunction(), getVisibleConversionFunctions(), HandleConstructorCall(), isInterfaceLike(), isLayoutCompatibleStruct(), LeastDerivedClassWithSameLayout(), and usesMultipleInheritanceModel().
bases_begin() [2/2]
base_class_const_iterator clang::CXXRecordDecl::bases_begin () const inline
Definition at line 626 of file DeclCXX.h.
bases_end() [1/2]
base_class_iterator clang::CXXRecordDecl::bases_end () inline
Definition at line 627 of file DeclCXX.h.
References bases_begin().
Referenced by addAssociatedClassesAndNamespaces(), bases(), getNonCLikeKindForAnonymousStruct(), and getVisibleConversionFunctions().
bases_end() [2/2]
base_class_const_iterator clang::CXXRecordDecl::bases_end () const inline
Definition at line 628 of file DeclCXX.h.
References bases_begin().
calculateInheritanceModel()
MSInheritanceModel CXXRecordDecl::calculateInheritanceModel () const
Calculate what the inheritance model would be for this class.
Definition at line 225 of file MicrosoftCXXABI.cpp.
References getNumVBases(), hasDefinition(), isParsingBaseSpecifiers(), clang::Multiple, clang::Single, clang::Unspecified, usesMultipleInheritanceModel(), and clang::Virtual.
capture_size()
unsigned clang::CXXRecordDecl::capture_size () const inline
Definition at line 1115 of file DeclCXX.h.
Referenced by getCapture(), and isCapturelessLambda().
captures()
capture_const_range clang::CXXRecordDecl::captures () const inline
Definition at line 1100 of file DeclCXX.h.
References captures_begin(), and captures_end().
Referenced by adjustCVQualifiersForCXXThisWithinLambda(), clang::SemaSYCL::CheckSYCLKernelCall(), clang::AnalysisDeclContext::getSelfDecl(), and clang::Sema::RebuildLambdaScopeInfo().
captures_begin()
capture_const_iterator clang::CXXRecordDecl::captures_begin () const inline
Definition at line 1104 of file DeclCXX.h.
References isLambda().
Referenced by clang::LambdaExpr::capture_begin(), captures(), captures_end(), clang::interp::ByteCodeEmitter::compileFunc(), and getCapture().
captures_end()
capture_const_iterator clang::CXXRecordDecl::captures_end () const inline
Definition at line 1110 of file DeclCXX.h.
References captures_begin(), and isLambda().
Referenced by clang::LambdaExpr::capture_end(), captures(), and clang::interp::ByteCodeEmitter::compileFunc().
classof()
static bool clang::CXXRecordDecl::classof (const Decl * D) inline static
Definition at line 1887 of file DeclCXX.h.
References classofKind(), and clang::Decl::getKind().
classofKind()
static bool clang::CXXRecordDecl::classofKind (Kind K) inline static
Definition at line 1888 of file DeclCXX.h.
Referenced by classof(), clang::ASTDeclWriter::VisitEnumDecl(), and clang::ASTDeclWriter::VisitRecordDecl().
completeDefinition() [1/2]
void CXXRecordDecl::completeDefinition () override virtual
Indicates that the definition of this class is now complete.
Reimplemented from clang::RecordDecl.
Definition at line 2054 of file DeclCXX.cpp.
completeDefinition() [2/2]
void CXXRecordDecl::completeDefinition (CXXFinalOverriderMap * FinalOverriders)
Indicates that the definition of this class is now complete, and provides a final overrider map to help determine.
Parameters
FinalOverriders The final overrider map for this class, which can be provided as an optimization for abstract-class checking. If NULL, final overriders will be computed if they are needed to complete the definition.
Definition at line 2058 of file DeclCXX.cpp.
References clang::RecordDecl::completeDefinition(), conversion_begin(), conversion_end(), getFinalOverriders(), and mayBeAbstract().
conversion_begin()
conversion_iterator clang::CXXRecordDecl::conversion_begin () const inline
Definition at line 1124 of file DeclCXX.h.
References clang::Decl::getASTContext().
Referenced by completeDefinition(), and isInterfaceLike().
conversion_end()
conversion_iterator clang::CXXRecordDecl::conversion_end () const inline
Definition at line 1128 of file DeclCXX.h.
References clang::Decl::getASTContext().
Referenced by completeDefinition(), and isInterfaceLike().
Create()
CXXRecordDecl * CXXRecordDecl::Create (const ASTContext & C, TagKind TK, DeclContext * DC, SourceLocation StartLoc, SourceLocation IdLoc, IdentifierInfo * Id, CXXRecordDecl * PrevDecl = nullptr, bool DelayTypeCreation = false) static
Definition at line 131 of file DeclCXX.cpp.
Referenced by clang::Sema::CreateCapturedStmtRecordDecl(), and clang::Sema::DeclareGlobalNewDelete().
CreateDeserialized()
CXXRecordDecl * CXXRecordDecl::CreateDeserialized (const ASTContext & C, Decl::DeclID ID) static
Definition at line 164 of file DeclCXX.cpp.
References CXXRecordDecl(), ID, and clang::Struct.
CreateLambda()
CXXRecordDecl * CXXRecordDecl::CreateLambda (const ASTContext & C, DeclContext * DC, TypeSourceInfo * Info, SourceLocation Loc, unsigned DependencyKind, bool IsGeneric, LambdaCaptureDefault CaptureDefault) static
Definition at line 147 of file DeclCXX.cpp.
References clang::Class, and CXXRecordDecl().
Referenced by clang::Sema::createLambdaClosureType().
ctor_begin()
ctor_iterator clang::CXXRecordDecl::ctor_begin () const inline
Definition at line 682 of file DeclCXX.h.
References clang::DeclContext::decls_begin().
Referenced by ctors().
ctor_end()
ctor_iterator clang::CXXRecordDecl::ctor_end () const inline
Definition at line 686 of file DeclCXX.h.
References clang::DeclContext::decls_end().
Referenced by ctors().
ctors()
ctor_range clang::CXXRecordDecl::ctors () const inline
Definition at line 680 of file DeclCXX.h.
References ctor_begin(), and ctor_end().
Referenced by canUseCtorHoming(), clang::Sema::checkIllFormedTrivialABIStruct(), clang::CodeGen::CGOpenMPRuntime::emitTargetGlobalVariable(), findUserDeclaredCtor(), isTrivialForMSVC(), and clang::Sema::ShouldDeleteSpecialMember().
defaultedCopyConstructorIsDeleted()
bool clang::CXXRecordDecl::defaultedCopyConstructorIsDeleted () const inline
true if a defaulted copy constructor for this class would be deleted.
Definition at line 707 of file DeclCXX.h.
References needsOverloadResolutionForCopyConstructor().
Referenced by clang::Sema::checkIllFormedTrivialABIStruct().
defaultedDefaultConstructorIsConstexpr()
bool clang::CXXRecordDecl::defaultedDefaultConstructorIsConstexpr () const inline
Determine whether a defaulted default constructor for this class would be constexpr.
Definition at line 1263 of file DeclCXX.h.
References clang::Decl::getLangOpts(), hasInClassInitializer(), hasVariantMembers(), and clang::TagDecl::isUnion().
Referenced by hasConstexprDefaultConstructor(), and hasConstexprNonCopyMoveConstructor().
defaultedDestructorIsConstexpr()
bool clang::CXXRecordDecl::defaultedDestructorIsConstexpr () const inline
Determine whether a defaulted default constructor for this class would be constexpr.
Definition at line 1356 of file DeclCXX.h.
References clang::Decl::getLangOpts().
Referenced by hasConstexprDestructor().
defaultedDestructorIsDeleted()
bool clang::CXXRecordDecl::defaultedDestructorIsDeleted () const inline
true if a defaulted destructor for this class would be deleted.
Definition at line 724 of file DeclCXX.h.
References needsOverloadResolutionForDestructor().
defaultedMoveConstructorIsDeleted()
bool clang::CXXRecordDecl::defaultedMoveConstructorIsDeleted () const inline
true if a defaulted move constructor for this class would be deleted.
Definition at line 716 of file DeclCXX.h.
References needsOverloadResolutionForMoveConstructor().
Referenced by clang::Sema::checkIllFormedTrivialABIStruct().
FindBaseClass()
bool CXXRecordDecl::FindBaseClass (const CXXBaseSpecifier * Specifier, CXXBasePath & Path, const CXXRecordDecl * BaseRecord) static
Base-class lookup callback that determines whether the given base class specifier refers to a specific class declaration.
This callback can be used with lookupInBases() to determine whether a given derived class has is a base class subobject of a particular type. The base record pointer should refer to the canonical CXXRecordDecl of the base class that we are searching for.
Definition at line 363 of file CXXInheritance.cpp.
References getCanonicalDecl(), and Specifier.
FindVirtualBaseClass()
bool CXXRecordDecl::FindVirtualBaseClass (const CXXBaseSpecifier * Specifier, CXXBasePath & Path, const CXXRecordDecl * BaseRecord) static
Base-class lookup callback that determines whether the given base class specifier refers to a specific class declaration and describes virtual derivation.
This callback can be used with lookupInBases() to determine whether a given derived class has is a virtual base class subobject of a particular type. The base record pointer should refer to the canonical CXXRecordDecl of the base class that we are searching for.
Definition at line 372 of file CXXInheritance.cpp.
References getCanonicalDecl(), and Specifier.
finishedDefaultedOrDeletedMember()
void CXXRecordDecl::finishedDefaultedOrDeletedMember (CXXMethodDecl * MD)
Indicates that the declaration of a defaulted or deleted special member function is now complete.
Definition at line 1466 of file DeclCXX.cpp.
References clang::AS_public, clang::Decl::getAccess(), clang::CXXMethodDecl::isCopyAssignmentOperator(), clang::FunctionDecl::isDeleted(), clang::Decl::isImplicit(), clang::FunctionDecl::isIneligibleOrNotSelected(), clang::CXXMethodDecl::isMoveAssignmentOperator(), clang::FunctionDecl::isTrivial(), and clang::FunctionDecl::isUserProvided().
forallBases()
bool CXXRecordDecl::forallBases (ForallBasesCallback BaseMatches) const
Determines if the given callback holds for all the direct or indirect base classes of this type.
The class itself does not count as a base class. This routine returns false if the class has non-computable base classes.
Parameters
BaseMatches Callback invoked for each (direct or indirect) base class of this type until a call returns false.
Definition at line 127 of file CXXInheritance.cpp.
References clang::Type::getAs(), clang::RecordType::getDecl(), and clang::RecordDecl::getDefinition().
Referenced by hasAnyDependentBases(), isOrIsDerivedFromSpecializationOf(), and isProvablyNotDerivedFrom().
friend_begin()
CXXRecordDecl::friend_iterator clang::CXXRecordDecl::friend_begin () const inline
Definition at line 238 of file DeclFriend.h.
Referenced by friends(), and IsRecordFullyDefined().
friend_end()
CXXRecordDecl::friend_iterator clang::CXXRecordDecl::friend_end () const inline
Definition at line 242 of file DeclFriend.h.
Referenced by friends(), and IsRecordFullyDefined().
friends()
CXXRecordDecl::friend_range clang::CXXRecordDecl::friends () const inline
Definition at line 246 of file DeclFriend.h.
References friend_begin(), and friend_end().
Referenced by findImplicitlyDeclaredEqualityComparisons().
getCanonicalDecl() [1/2]
const CXXRecordDecl* clang::CXXRecordDecl::getCanonicalDecl () const inline
Definition at line 527 of file DeclCXX.h.
References getCanonicalDecl().
getCanonicalDecl() [2/2]
CXXRecordDecl* clang::CXXRecordDecl::getCanonicalDecl () inline override virtual
Retrieves the "canonical" declaration of the given declaration.
Reimplemented from clang::TagDecl.
Definition at line 523 of file DeclCXX.h.
References clang::TagDecl::getCanonicalDecl().
Referenced by clang::Sema::CheckQualifiedMemberReference(), ClassifyImplicitMemberAccess(), FindBaseClass(), clang::ClassTemplateDecl::findPartialSpecInstantiatedFromMember(), FindVirtualBaseClass(), getCanonicalDecl(), clang::CXXMethodDecl::getCorrespondingMethodDeclaredInClass(), HandleBaseToDerivedCast(), clang::DotMemberAccessHandler::handleDeclaration(), HandleMemberPointerAccess(), clang::Sema::InstantiateClassTemplateSpecialization(), IsDerivedFromInclusive(), isInstantiationOf(), isValidBaseClass(), clang::ComparisonCategories::lookupInfoForType(), clang::ASTDeclReader::mergeRedeclarable(), regionMatchesCXXRecordType(), clang::ASTDeclReader::UpdateDecl(), and clang::ASTDeclReader::VisitCXXRecordDeclImpl().
getCapture()
const LambdaCapture* clang::CXXRecordDecl::getCapture (unsigned I) const inline
Definition at line 1117 of file DeclCXX.h.
References capture_size(), captures_begin(), and isLambda().
getCaptureFields()
void CXXRecordDecl::getCaptureFields (llvm::DenseMap< const ValueDecl *, FieldDecl * > & Captures, FieldDecl *& ThisCapture) const
For a closure type, retrieve the mapping from captured variables and this to the non-static data members that store the values or references of the captures.
Parameters
Captures Will be populated with the mapping from captured variables to the corresponding fields.
ThisCapture Will be set to the field declaration for the this capture.
Note
No entries will be added for init-captures, as they do not capture variables.
If multiple versions of the lambda are merged together, they may have different variable declarations corresponding to the same capture. In that case, all of those variable declarations will be added to the Captures list, so it may have more than one variable listed per field.
Definition at line 1640 of file DeclCXX.cpp.
Referenced by HandleFunctionCall(), clang::ento::isCapturedByReference(), clang::CodeGen::CodeGenFunction::StartFunction(), and clang::ento::ExprEngine::VisitCommonDeclRefExpr().
getDefinition()
CXXRecordDecl* clang::CXXRecordDecl::getDefinition () const inline
Definition at line 564 of file DeclCXX.h.
Referenced by clang::Sema::CheckComparisonCategoryType(), clang::Sema::DeclareAggregateDeductionGuideFromInitList(), clang::Sema::DeclareImplicitDeductionGuides(), getContainedDynamicClass(), clang::ASTContext::getCurrentKeyFunction(), getODRHash(), clang::ASTRecordLayout::getVBaseClassOffset(), clang::ASTNodeImporter::ImportImplicitMethods(), clang::Sema::InstantiateClass(), clang::Sema::InstantiateClassMembers(), clang::Sema::isAbstractType(), isEffectivelyFinal(), clang::isRefCountable(), clang::Sema::LookupSpecialMember(), and clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl().
getDependentLambdaCallOperator()
FunctionTemplateDecl * CXXRecordDecl::getDependentLambdaCallOperator () const
Retrieve the dependent lambda call operator of the closure type if this is a templated closure type.
Definition at line 1588 of file DeclCXX.cpp.
References getLambdaCallOperatorHelper().
getDescribedClassTemplate()
ClassTemplateDecl * CXXRecordDecl::getDescribedClassTemplate () const
Retrieves the class template that is described by this class declaration.
Every class template is represented as a ClassTemplateDecl and a CXXRecordDecl. The former contains template properties (such as the template parameter lists) while the latter contains the actual description of the template's contents. ClassTemplateDecl::getTemplatedDecl() retrieves the CXXRecordDecl that from a ClassTemplateDecl, while getDescribedClassTemplate() retrieves the ClassTemplateDecl from a CXXRecordDecl.
Definition at line 1896 of file DeclCXX.cpp.
Referenced by clang::Sema::ActOnReenterTemplateScope(), clang::ODRDiagsEmitter::diagnoseMismatch(), clang::installapi::InstallAPIVisitor::VisitCXXRecordDecl(), and clang::ASTDeclWriter::VisitCXXRecordDecl().
getDestructor()
CXXDestructorDecl * CXXRecordDecl::getDestructor () const
Returns the destructor decl for this class.
Definition at line 1974 of file DeclCXX.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitDelegatingCXXConstructorCall(), EmitDestroyingObjectDelete(), EmitObjectDelete(), clang::CodeGen::CGOpenMPRuntime::emitTargetGlobalVariable(), clang::CXXMethodDecl::getCorrespondingMethodDeclaredInClass(), clang::CFGImplicitDtor::getDestructorDecl(), HandleDestructionImpl(), hasConstexprDestructor(), clang::Sema::LookupSpecialMember(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), clang::ento::ExprEngine::ProcessDeleteDtor(), clang::CodeGen::CodeGenFunction::PushDestructorCleanup(), clang::Sema::RequireLiteralType(), and clang::CodeGen::CodeGenModule::TryEmitBaseDestructorAsAlias().
getDeviceLambdaManglingNumber()
unsigned CXXRecordDecl::getDeviceLambdaManglingNumber () const
Retrieve the device side mangling number.
Definition at line 1701 of file DeclCXX.cpp.
References clang::Decl::getASTContext(), and isLambda().
Referenced by clang::ASTRecordWriter::AddCXXDefinitionData(), and getLambdaNumbering().
getFinalOverriders()
void CXXRecordDecl::getFinalOverriders (CXXFinalOverriderMap & FinaOverriders) const
Retrieve the final overriders for each virtual member function in the class hierarchy where this class is the most-derived class in the class hierarchy.
Definition at line 642 of file CXXInheritance.cpp.
Referenced by completeDefinition(), clang::Sema::DiagnoseAbstractType(), and clang::Sema::MarkVirtualMembersReferenced().
getGenericLambdaTemplateParameterList()
TemplateParameterList * CXXRecordDecl::getGenericLambdaTemplateParameterList () const
Retrieve the generic lambda's template parameter list.
Returns null if the class does not represent a lambda or a generic lambda.
Definition at line 1661 of file DeclCXX.cpp.
References clang::FunctionDecl::getDescribedFunctionTemplate(), getLambdaCallOperator(), and isGenericLambda().
getIndirectPrimaryBases()
void CXXRecordDecl::getIndirectPrimaryBases (CXXIndirectPrimaryBaseSet & Bases) const
Get the indirect primary bases for this class.
Definition at line 703 of file CXXInheritance.cpp.
getInstantiatedFromMemberClass()
CXXRecordDecl * CXXRecordDecl::getInstantiatedFromMemberClass () const
If this record is an instantiation of a member class, retrieves the member class from which it was instantiated.
This routine will return non-null for (non-templated) member classes of class templates. For example, given:
template<typename T>
struct X {
  struct A { };
};
The declaration for X<int>::A is a (non-templated) CXXRecordDecl whose parent is the class template specialization X<int>. For this declaration, getInstantiatedFromMemberClass() will return the CXXRecordDecl X<T>::A. When a complete definition of X<int>::A is required, it will be instantiated from the declaration returned by getInstantiatedFromMemberClass().
Definition at line 1875 of file DeclCXX.cpp.
References getMemberSpecializationInfo().
Referenced by getDeclContextForTemplateInstationPattern(), getExplicitVisibilityAux(), getTemplateInstantiationPattern(), clang::Sema::InstantiateClass(), clang::Sema::InstantiateClassMembers(), and clang::TextNodeDumper::VisitCXXRecordDecl().
getLambdaCallOperator()
CXXMethodDecl * CXXRecordDecl::getLambdaCallOperator () const
Retrieve the lambda call operator of the closure type if this is a closure type.
Definition at line 1593 of file DeclCXX.cpp.
References getLambdaCallOperatorHelper().
Referenced by adjustCVQualifiersForCXXThisWithinLambda(), clang::Sema::CheckIfFunctionSpecializationIsImmediate(), clang::interp::ByteCodeEmitter::compileFunc(), clang::SemaSYCL::ConstructOpenCLKernel(), clang::Sema::DeduceReturnType(), clang::Sema::DefineImplicitLambdaToFunctionPointerConversion(), clang::CodeGen::CodeGenFunction::EmitLambdaBlockInvokeBody(), clang::CodeGen::CodeGenFunction::EmitLambdaDelegatingInvokeBody(), getGenericLambdaTemplateParameterList(), getLambdaStaticInvoker(), and clang::ento::BlockCall::getRuntimeDefinition().
getLambdaCaptureDefault()
LambdaCaptureDefault clang::CXXRecordDecl::getLambdaCaptureDefault () const inline
Definition at line 1062 of file DeclCXX.h.
References isLambda().
Referenced by isCapturelessLambda(), and clang::Sema::RebuildLambdaScopeInfo().
getLambdaContextDecl()
Decl * CXXRecordDecl::getLambdaContextDecl () const
Retrieve the declaration that provides additional context for a lambda, when the normal declaration context is not specific enough.
Certain contexts (default arguments of in-class function parameters and the initializers of data members) have separate name mangling rules for lambdas within the Itanium C++ ABI. For these cases, this routine provides the declaration in which the lambda occurs, e.g., the function parameter or the non-static data member. Otherwise, it returns NULL to imply that the declaration context suffices.
Definition at line 1684 of file DeclCXX.cpp.
References clang::ASTContext::getExternalSource(), clang::DeclContext::getParentASTContext(), and isLambda().
Referenced by clang::ASTReader::AssignedLambdaNumbering(), and getLambdaNumbering().
getLambdaDependencyKind()
unsigned clang::CXXRecordDecl::getLambdaDependencyKind () const inline
Definition at line 1855 of file DeclCXX.h.
References isLambda(), and LDK_Unknown.
Referenced by clang::TreeTransform< Derived >::ComputeLambdaDependency().
getLambdaExplicitTemplateParameters()
ArrayRef< NamedDecl * > CXXRecordDecl::getLambdaExplicitTemplateParameters () const
Retrieve the lambda template parameters that were specified explicitly.
Definition at line 1670 of file DeclCXX.cpp.
getLambdaIndexInContext()
unsigned clang::CXXRecordDecl::getLambdaIndexInContext () const inline
Retrieve the index of this lambda within the context declaration returned by getLambdaContextDecl().
Definition at line 1791 of file DeclCXX.h.
References isLambda().
Referenced by clang::ASTReader::AssignedLambdaNumbering(), and getLambdaNumbering().
getLambdaManglingNumber()
unsigned clang::CXXRecordDecl::getLambdaManglingNumber () const inline
If this is the closure type of a lambda expression, retrieve the number to be used for name mangling in the Itanium C++ ABI.
Zero indicates that this closure type has internal linkage, so the mangling number does not matter, while a non-zero value indicates which lambda expression this is in this particular context.
Definition at line 1766 of file DeclCXX.h.
References isLambda().
Referenced by getLambdaNumbering().
getLambdaNumbering()
LambdaNumbering clang::CXXRecordDecl::getLambdaNumbering () const inline
Definition at line 1809 of file DeclCXX.h.
References getDeviceLambdaManglingNumber(), getLambdaContextDecl(), getLambdaIndexInContext(), getLambdaManglingNumber(), and hasKnownLambdaInternalLinkage().
getLambdaStaticInvoker() [1/2]
CXXMethodDecl * CXXRecordDecl::getLambdaStaticInvoker () const
Retrieve the lambda static invoker, the address of which is returned by the conversion operator, and the body of which is forwarded to the lambda call operator.
The version that does not take a calling convention uses the 'default' calling convention for free functions if the Lambda's calling convention was not modified via attribute. Otherwise, it will return the calling convention specified for the lambda.
Definition at line 1605 of file DeclCXX.cpp.
References clang::Type::castAs(), getLambdaCallOperator(), and clang::ValueDecl::getType().
Referenced by clang::Sema::DefineImplicitLambdaToFunctionPointerConversion().
getLambdaStaticInvoker() [2/2]
CXXMethodDecl * CXXRecordDecl::getLambdaStaticInvoker (CallingConv CC) const
Definition at line 1625 of file DeclCXX.cpp.
References getInvokerAsMethod(), getLambdaStaticInvokers(), and isLambda().
getLambdaTypeInfo()
TypeSourceInfo* clang::CXXRecordDecl::getLambdaTypeInfo () const inline
Definition at line 1861 of file DeclCXX.h.
getMemberSpecializationInfo()
MemberSpecializationInfo * CXXRecordDecl::getMemberSpecializationInfo () const
If this class is an instantiation of a member class of a class template specialization, retrieves the member specialization information.
Definition at line 1882 of file DeclCXX.cpp.
Referenced by getInstantiatedFromMemberClass(), getTemplateInstantiationPattern(), getTemplateSpecializationKind(), setTemplateSpecializationKind(), clang::ASTDeclReader::UpdateDecl(), and clang::ASTDeclWriter::VisitCXXRecordDecl().
getMostRecentDecl() [1/2]
CXXRecordDecl* clang::CXXRecordDecl::getMostRecentDecl () inline
Definition at line 540 of file DeclCXX.h.
Referenced by getMostRecentDecl(), and getMostRecentNonInjectedDecl().
getMostRecentDecl() [2/2]
const CXXRecordDecl* clang::CXXRecordDecl::getMostRecentDecl () const inline
Definition at line 545 of file DeclCXX.h.
References getMostRecentDecl().
getMostRecentNonInjectedDecl() [1/2]
CXXRecordDecl* clang::CXXRecordDecl::getMostRecentNonInjectedDecl () inline
Definition at line 549 of file DeclCXX.h.
References getMostRecentDecl(), getPreviousDecl(), and clang::RecordDecl::isInjectedClassName().
Referenced by clang::MemberPointerType::getMostRecentCXXRecordDecl(), clang::ClassTemplateSpecializationDecl::getMostRecentDecl(), and getMostRecentNonInjectedDecl().
getMostRecentNonInjectedDecl() [2/2]
const CXXRecordDecl* clang::CXXRecordDecl::getMostRecentNonInjectedDecl () const inline
Definition at line 560 of file DeclCXX.h.
References getMostRecentNonInjectedDecl().
getMSInheritanceModel()
MSInheritanceModel CXXRecordDecl::getMSInheritanceModel () const
Returns the inheritance model used for this record.
Definition at line 235 of file MicrosoftCXXABI.cpp.
Referenced by getMSMemberPointerSlots(), and nullFieldOffsetIsZero().
getMSVtorDispMode()
MSVtorDispMode CXXRecordDecl::getMSVtorDispMode () const
Controls when vtordisps will be emitted if this record is used as a virtual base.
Definition at line 247 of file MicrosoftCXXABI.cpp.
References clang::Decl::getASTContext(), and clang::ASTContext::getLangOpts().
getNumBases()
unsigned clang::CXXRecordDecl::getNumBases () const inline
Retrieves the number of base classes of this class.
Definition at line 612 of file DeclCXX.h.
Referenced by CanUseSingleInheritance(), CheckConstexprFunctionBody(), clang::CodeGen::CodeGenModule::getMostBaseClasses(), getNonCLikeKindForAnonymousStruct(), clang::interp::Context::getOverridingFunction(), HandleClassZeroInitialization(), HandleConstructorCall(), HandleDestructionImpl(), isIdiomaticBraceElisionEntity(), isInterfaceLike(), isLayoutCompatibleStruct(), isTrivialForMSVC(), LeastDerivedClassWithSameLayout(), usesMultipleInheritanceModel(), and clang::JSONNodeDumper::VisitCXXRecordDecl().
getNumVBases()
unsigned clang::CXXRecordDecl::getNumVBases () const inline
Retrieves the number of virtual base classes of this class.
Definition at line 633 of file DeclCXX.h.
Referenced by clang::CodeGen::CodeGenTypes::arrangeMSCtorClosure(), clang::CodeGen::CGCXXABI::buildThisParam(), calculateInheritanceModel(), clang::Sema::CheckCompleteDestructorVariant(), CheckConstexprFunctionBody(), clang::Sema::CheckConstexprFunctionDefinition(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::CodeGen::CodeGenFunction::EmitCtorPrologue(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), clang::CodeGen::CodeGenVTables::GenerateClassData(), clang::CodeGen::CodeGenVTables::GetAddrOfVTT(), getCodegenToUse(), HandleConstructorCall(), HandleDestructionImpl(), clang::CodeGen::CodeGenFunction::InitializeVTablePointers(), clang::CodeGen::CodeGenFunction::IsConstructorDelegationValid(), isInterfaceLike(), isVirtualDirectBase(), isVirtuallyDerivedFrom(), LeastDerivedClassWithSameLayout(), clang::Sema::MarkVirtualMembersReferenced(), clang::Sema::RequireLiteralType(), and clang::Sema::SpecialMemberIsTrivial().
getODRHash()
unsigned CXXRecordDecl::getODRHash () const
Definition at line 494 of file DeclCXX.cpp.
References clang::ODRHash::AddCXXRecordDecl(), clang::ODRHash::CalculateHash(), getDefinition(), and hasDefinition().
Referenced by clang::ASTRecordWriter::AddCXXDefinitionData().
getPreviousDecl() [1/2]
CXXRecordDecl* clang::CXXRecordDecl::getPreviousDecl () inline
Definition at line 531 of file DeclCXX.h.
Referenced by getMostRecentNonInjectedDecl(), getPreviousDecl(), and clang::ASTDeclWriter::VisitClassTemplatePartialSpecializationDecl().
getPreviousDecl() [2/2]
const CXXRecordDecl* clang::CXXRecordDecl::getPreviousDecl () const inline
Definition at line 536 of file DeclCXX.h.
References getPreviousDecl().
getTemplateInstantiationPattern() [1/2]
CXXRecordDecl* clang::CXXRecordDecl::getTemplateInstantiationPattern () inline
Definition at line 1533 of file DeclCXX.h.
References getTemplateInstantiationPattern().
getTemplateInstantiationPattern() [2/2]
const CXXRecordDecl * CXXRecordDecl::getTemplateInstantiationPattern () const
Retrieve the record declaration from which this record could be instantiated.
Returns null if this class is not a template instantiation.
Definition at line 1929 of file DeclCXX.cpp.
References getInstantiatedFromMemberClass(), getMemberSpecializationInfo(), getTemplateSpecializationKind(), and clang::isTemplateInstantiation().
Referenced by clang::Sema::BuildCXXDefaultInitExpr(), getDeclContextForTemplateInstationPattern(), getTemplateInstantiationPattern(), clang::Sema::InstantiateClassMembers(), and clang::isRefCounted().
getTemplateSpecializationKind()
TemplateSpecializationKind CXXRecordDecl::getTemplateSpecializationKind () const
Determine whether this particular class is a specialization or instantiation of a class template or member class of a class template, and how it was instantiated or specialized.
Definition at line 1904 of file DeclCXX.cpp.
References getMemberSpecializationInfo(), and clang::TSK_Undeclared.
Referenced by clang::Sema::checkIllFormedTrivialABIStruct(), clang::Sema::FindInstantiatedDecl(), getTemplateInstantiationPattern(), clang::installapi::getVTableLinkage(), clang::CodeGen::CodeGenModule::getVTableLinkage(), clang::installapi::hasVTable(), isDefinedInClangModule(), clang::ClassTemplateSpecializationDecl::isExplicitInstantiationOrSpecialization(), clang::CodeGen::CodeGenVTables::isVTableExternal(), clang::Sema::usesPartialOrExplicitSpecialization(), and clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl().
getVisibleConversionFunctions()
llvm::iterator_range< CXXRecordDecl::conversion_iterator > CXXRecordDecl::getVisibleConversionFunctions () const
Get all conversion functions visible in current class, including conversion function templates.
getVisibleConversionFunctions - get all conversion functions visible in current class; including conversion function templates.
Definition at line 1832 of file DeclCXX.cpp.
References bases_begin(), bases_end(), CollectVisibleConversions(), clang::Decl::getASTContext(), and clang::Set.
Referenced by CollectVRQualifiers().
hasAnyDependentBases()
bool CXXRecordDecl::hasAnyDependentBases () const
Determine whether this class has any dependent base classes which are not the current instantiation.
Definition at line 568 of file DeclCXX.cpp.
References forallBases(), and clang::DeclContext::isDependentContext().
Referenced by clang::Sema::BuildBaseInitializer(), clang::Sema::CheckOverrideControl(), mayBeDynamicClass(), and mayBeNonDynamicClass().
hasConstexprDefaultConstructor()
bool clang::CXXRecordDecl::hasConstexprDefaultConstructor () const inline
Determine whether this class has a constexpr default constructor.
Definition at line 1270 of file DeclCXX.h.
References defaultedDefaultConstructorIsConstexpr(), and needsImplicitDefaultConstructor().
hasConstexprDestructor()
bool CXXRecordDecl::hasConstexprDestructor () const
Determine whether this class has a constexpr destructor.
Definition at line 563 of file DeclCXX.cpp.
References defaultedDestructorIsConstexpr(), and getDestructor().
Referenced by CheckConstexprDestructorSubobjects(), and clang::Sema::RequireLiteralType().
hasConstexprNonCopyMoveConstructor()
bool clang::CXXRecordDecl::hasConstexprNonCopyMoveConstructor () const inline
Determine whether this class has at least one constexpr constructor other than the copy or move constructors.
Definition at line 1255 of file DeclCXX.h.
References defaultedDefaultConstructorIsConstexpr(), and needsImplicitDefaultConstructor().
Referenced by canUseCtorHoming(), and clang::Sema::RequireLiteralType().
hasCopyAssignmentWithConstParam()
bool clang::CXXRecordDecl::hasCopyAssignmentWithConstParam () const inline
Determine whether this class has a copy assignment operator with a parameter type which is a reference to a const-qualified type or is not a reference.
Definition at line 956 of file DeclCXX.h.
References implicitCopyAssignmentHasConstParam(), and needsImplicitCopyAssignment().
hasCopyConstructorWithConstParam()
bool clang::CXXRecordDecl::hasCopyConstructorWithConstParam () const inline
Determine whether this class has a copy constructor with a parameter type which is a reference to a const-qualified type.
Definition at line 838 of file DeclCXX.h.
References implicitCopyConstructorHasConstParam(), and needsImplicitCopyConstructor().
hasDefaultConstructor()
bool clang::CXXRecordDecl::hasDefaultConstructor () const inline
Determine whether this class has any default constructors.
Definition at line 767 of file DeclCXX.h.
References needsImplicitDefaultConstructor().
Referenced by hasTrivialDefaultConstructor().
hasDefinition()
bool clang::CXXRecordDecl::hasDefinition () const inline
Definition at line 571 of file DeclCXX.h.
Referenced by calculateInheritanceModel(), canRecoverDotPseudoDestructorCallsOnPointerObjects(), clang::Sema::CheckComparisonCategoryType(), clang::SemaSYCL::CheckSYCLKernelCall(), CollectVRQualifiers(), clang::Sema::computeDeclContext(), EmitObjectDelete(), clang::CodeGen::CodeGenModule::EmitTopLevelDecl(), clang::CodeGen::CodeGenModule::getClassPointerAlignment(), clang::Sema::getFixItZeroInitializerForType(), clang::CodeGen::CodeGenModule::getMinimumClassObjectSize(), getODRHash(), clang::dataflow::getOptionalBaseClass(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), clang::installapi::getVTableLinkage(), clang::hasPublicMethodInBase(), clang::installapi::hasRTTI(), clang::installapi::hasVTable(), isCLike(), IsDerivedFromInclusive(), isInterfaceLike(), clang::CodeGen::CodeGenFunction::isVptrCheckRequired(), mayBeDynamicClass(), mayBeNonDynamicClass(), and nullFieldOffsetIsZero().
hasDirectFields()
bool clang::CXXRecordDecl::hasDirectFields () const inline
Determine whether this class has direct non-static data members.
Definition at line 1207 of file DeclCXX.h.
hasFriends()
bool clang::CXXRecordDecl::hasFriends () const inline
Determines whether this record has any friends.
Definition at line 701 of file DeclCXX.h.
Referenced by isInterfaceLike().
hasInClassInitializer()
bool clang::CXXRecordDecl::hasInClassInitializer () const inline
Whether this class has any in-class initializers for non-static data members (including those in anonymous unions or structs).
Definition at line 1151 of file DeclCXX.h.
Referenced by defaultedDefaultConstructorIsConstexpr().
hasInheritedAssignment()
bool clang::CXXRecordDecl::hasInheritedAssignment () const inline
Determine whether this class has a using-declaration that names a base class assignment operator.
Definition at line 1420 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass().
hasInheritedConstructor()
bool clang::CXXRecordDecl::hasInheritedConstructor () const inline
Determine whether this class has a using-declaration that names a user-declared base class constructor.
Definition at line 1414 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass().
hasInitMethod()
bool clang::CXXRecordDecl::hasInitMethod () const inline
Definition at line 1196 of file DeclCXX.h.
hasIrrelevantDestructor()
bool clang::CXXRecordDecl::hasIrrelevantDestructor () const inline
Determine whether this class has a destructor which has no semantic effect.
Any such destructor will be trivial, public, defaulted and not deleted, and will call only irrelevant destructors.
Definition at line 1402 of file DeclCXX.h.
Referenced by clang::Sema::CheckCXXThrowOperand(), clang::Interpreter::CompileDtorCall(), clang::Sema::FinalizeVarWithDestructor(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), and clang::Sema::MarkVirtualBaseDestructorsReferenced().
hasKnownLambdaInternalLinkage()
bool clang::CXXRecordDecl::hasKnownLambdaInternalLinkage () const inline
The lambda is known to has internal linkage no matter whether it has name mangling number.
Definition at line 1773 of file DeclCXX.h.
References isLambda().
Referenced by getLambdaNumbering().
hasMemberName()
bool CXXRecordDecl::hasMemberName (DeclarationName N) const
Determine whether this class has a member with the given name, possibly in a non-dependent base class.
No check for ambiguity is performed, so this should never be used when implementing language semantics, but it may be appropriate for warnings, static analysis, or similar.
Definition at line 397 of file CXXInheritance.cpp.
hasMoveAssignment()
bool clang::CXXRecordDecl::hasMoveAssignment () const inline
Determine whether this class has a move assignment operator.
Definition at line 969 of file DeclCXX.h.
References needsImplicitMoveAssignment().
Referenced by hasSimpleMoveAssignment(), and hasTrivialMoveAssignment().
hasMoveConstructor()
bool clang::CXXRecordDecl::hasMoveConstructor () const inline
Determine whether this class has a move constructor.
Definition at line 861 of file DeclCXX.h.
References needsImplicitMoveConstructor().
Referenced by hasSimpleMoveConstructor(), hasTrivialMoveConstructor(), and hasTrivialMoveConstructorForCall().
hasMutableFields()
bool clang::CXXRecordDecl::hasMutableFields () const inline
Determine whether this class, or any of its class subobjects, contains a mutable field.
Definition at line 1233 of file DeclCXX.h.
Referenced by diagnoseMutableFields(), and clang::ento::CXXInstanceCall::getExtraInvalidatedValues().
hasNonLiteralTypeFieldsOrBases()
bool clang::CXXRecordDecl::hasNonLiteralTypeFieldsOrBases () const inline
Determine whether this class has a non-literal or/ volatile type non-static data member or base class.
Definition at line 1408 of file DeclCXX.h.
Referenced by clang::Sema::RequireLiteralType(), and setBases().
hasNonTrivialCopyAssignment()
bool clang::CXXRecordDecl::hasNonTrivialCopyAssignment () const inline
Determine whether this class has a non-trivial copy assignment operator (C++ [class.copy]p11, C++11 [class.copy]p25)
Definition at line 1334 of file DeclCXX.h.
References hasTrivialCopyAssignment().
Referenced by EvaluateUnaryTypeTrait(), isTrivialForMSVC(), and isTriviallyCopyable().
hasNonTrivialCopyConstructor()
bool clang::CXXRecordDecl::hasNonTrivialCopyConstructor () const inline
Determine whether this class has a non-trivial copy constructor (C++ [class.copy]p6, C++11 [class.copy]p12)
Definition at line 1288 of file DeclCXX.h.
References hasTrivialCopyConstructor().
Referenced by EvaluateUnaryTypeTrait(), isTriviallyCopyable(), and isTriviallyCopyConstructible().
hasNonTrivialCopyConstructorForCall()
bool clang::CXXRecordDecl::hasNonTrivialCopyConstructorForCall () const inline
Definition at line 1293 of file DeclCXX.h.
References hasTrivialCopyConstructorForCall().
hasNonTrivialDefaultConstructor()
bool clang::CXXRecordDecl::hasNonTrivialDefaultConstructor () const inline
Determine whether this class has a non-trivial default constructor (C++11 [class.ctor]p5).
Definition at line 1247 of file DeclCXX.h.
References needsImplicitDefaultConstructor().
Referenced by EvaluateUnaryTypeTrait().
hasNonTrivialDestructor()
bool clang::CXXRecordDecl::hasNonTrivialDestructor () const inline
Determine whether this class has a non-trivial destructor (C++ [class.dtor]p3)
Definition at line 1376 of file DeclCXX.h.
Referenced by clang::ConstructionContext::createFromLayers(), and isTrivialForMSVC().
hasNonTrivialDestructorForCall()
bool clang::CXXRecordDecl::hasNonTrivialDestructorForCall () const inline
Definition at line 1380 of file DeclCXX.h.
hasNonTrivialMoveAssignment()
bool clang::CXXRecordDecl::hasNonTrivialMoveAssignment () const inline
Determine whether this class has a non-trivial move assignment operator (C++11 [class.copy]p25)
Definition at line 1348 of file DeclCXX.h.
References needsImplicitMoveAssignment().
Referenced by EvaluateUnaryTypeTrait(), and isTriviallyCopyable().
hasNonTrivialMoveConstructor()
bool clang::CXXRecordDecl::hasNonTrivialMoveConstructor () const inline
Determine whether this class has a non-trivial move constructor (C++11 [class.copy]p12)
Definition at line 1313 of file DeclCXX.h.
References needsImplicitMoveConstructor().
Referenced by EvaluateUnaryTypeTrait(), and isTriviallyCopyable().
hasNonTrivialMoveConstructorForCall()
bool clang::CXXRecordDecl::hasNonTrivialMoveConstructorForCall () const inline
Definition at line 1319 of file DeclCXX.h.
References needsImplicitMoveConstructor().
hasPrivateFields()
bool clang::CXXRecordDecl::hasPrivateFields () const inline
Definition at line 1198 of file DeclCXX.h.
Referenced by isTrivialForMSVC().
hasProtectedFields()
bool clang::CXXRecordDecl::hasProtectedFields () const inline
Definition at line 1202 of file DeclCXX.h.
Referenced by isTrivialForMSVC().
hasSimpleCopyAssignment()
bool clang::CXXRecordDecl::hasSimpleCopyAssignment () const inline
true if we know for sure that this class has a single, accessible, unambiguous copy assignment operator that is not deleted.
Definition at line 747 of file DeclCXX.h.
References hasUserDeclaredCopyAssignment().
hasSimpleCopyConstructor()
bool clang::CXXRecordDecl::hasSimpleCopyConstructor () const inline
true if we know for sure that this class has a single, accessible, unambiguous copy constructor that is not deleted.
Definition at line 733 of file DeclCXX.h.
References hasUserDeclaredCopyConstructor().
hasSimpleDestructor()
bool clang::CXXRecordDecl::hasSimpleDestructor () const inline
true if we know for sure that this class has an accessible destructor that is not deleted.
Definition at line 761 of file DeclCXX.h.
References hasUserDeclaredDestructor().
hasSimpleMoveAssignment()
bool clang::CXXRecordDecl::hasSimpleMoveAssignment () const inline
true if we know for sure that this class has a single, accessible, unambiguous move assignment operator that is not deleted.
Definition at line 754 of file DeclCXX.h.
References hasMoveAssignment(), and hasUserDeclaredMoveAssignment().
hasSimpleMoveConstructor()
bool clang::CXXRecordDecl::hasSimpleMoveConstructor () const inline
true if we know for sure that this class has a single, accessible, unambiguous move constructor that is not deleted.
Definition at line 740 of file DeclCXX.h.
References hasMoveConstructor(), and hasUserDeclaredMoveConstructor().
hasTrivialCopyAssignment()
bool clang::CXXRecordDecl::hasTrivialCopyAssignment () const inline
Determine whether this class has a trivial copy assignment operator (C++ [class.copy]p11, C++11 [class.copy]p25)
Definition at line 1328 of file DeclCXX.h.
Referenced by EvaluateUnaryTypeTrait(), and hasNonTrivialCopyAssignment().
hasTrivialCopyConstructor()
bool clang::CXXRecordDecl::hasTrivialCopyConstructor () const inline
Determine whether this class has a trivial copy constructor (C++ [class.copy]p6, C++11 [class.copy]p12)
Definition at line 1278 of file DeclCXX.h.
Referenced by EvaluateUnaryTypeTrait(), and hasNonTrivialCopyConstructor().
hasTrivialCopyConstructorForCall()
bool clang::CXXRecordDecl::hasTrivialCopyConstructorForCall () const inline
Definition at line 1282 of file DeclCXX.h.
Referenced by hasNonTrivialCopyConstructorForCall().
hasTrivialDefaultConstructor()
bool clang::CXXRecordDecl::hasTrivialDefaultConstructor () const inline
Determine whether this class has a trivial default constructor (C++11 [class.ctor]p5).
Definition at line 1240 of file DeclCXX.h.
References hasDefaultConstructor().
Referenced by canUseCtorHoming(), EvaluateUnaryTypeTrait(), isTrivial(), and clang::Sema::RequireLiteralType().
hasTrivialDestructor()
bool clang::CXXRecordDecl::hasTrivialDestructor () const inline
Determine whether this class has a trivial destructor (C++ [class.dtor]p3)
Definition at line 1366 of file DeclCXX.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXAggrConstructorCall(), clang::CodeGen::CodeGenFunction::EmitCXXConstructLValue(), clang::CodeGen::CodeGenFunction::EmitDelegatingCXXConstructorCall(), EmitObjectDelete(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), EvaluateUnaryTypeTrait(), HandleDestructionImpl(), clang::Expr::isConstantInitializer(), isTriviallyCopyable(), isTriviallyCopyConstructible(), clang::CodeGen::CodeGenFunction::PushDestructorCleanup(), and clang::Sema::RequireLiteralType().
hasTrivialDestructorForCall()
bool clang::CXXRecordDecl::hasTrivialDestructorForCall () const inline
Definition at line 1370 of file DeclCXX.h.
hasTrivialMoveAssignment()
bool clang::CXXRecordDecl::hasTrivialMoveAssignment () const inline
Determine whether this class has a trivial move assignment operator (C++11 [class.copy]p25)
Definition at line 1341 of file DeclCXX.h.
References hasMoveAssignment().
Referenced by EvaluateUnaryTypeTrait().
hasTrivialMoveConstructor()
bool clang::CXXRecordDecl::hasTrivialMoveConstructor () const inline
Determine whether this class has a trivial move constructor (C++11 [class.copy]p12)
Definition at line 1301 of file DeclCXX.h.
References hasMoveConstructor().
Referenced by EvaluateUnaryTypeTrait().
hasTrivialMoveConstructorForCall()
bool clang::CXXRecordDecl::hasTrivialMoveConstructorForCall () const inline
Definition at line 1306 of file DeclCXX.h.
References hasMoveConstructor().
hasUninitializedReferenceMember()
bool clang::CXXRecordDecl::hasUninitializedReferenceMember () const inline
Whether this class or any of its subobjects has any members of reference type which would make value-initialization ill-formed.
Per C++03 [dcl.init]p5:
if T is a non-union class type without a user-declared constructor, then every non-static data member and base-class component of T is value-initialized [...] A program that calls for [...] value-initialization of an entity of reference type is ill-formed.
Definition at line 1161 of file DeclCXX.h.
References hasUserDeclaredConstructor(), and clang::TagDecl::isUnion().
hasUserDeclaredConstructor()
bool clang::CXXRecordDecl::hasUserDeclaredConstructor () const inline
Determine whether this class has any user-declared constructors.
When true, a default constructor will not be implicitly declared.
Definition at line 790 of file DeclCXX.h.
Referenced by CheckAggExprForMemSetUse(), hasUninitializedReferenceMember(), and isInterfaceLike().
hasUserDeclaredCopyAssignment()
bool clang::CXXRecordDecl::hasUserDeclaredCopyAssignment () const inline
Determine whether this class has a user-declared copy assignment operator.
When false, a copy assignment operator will be implicitly declared.
Definition at line 913 of file DeclCXX.h.
Referenced by hasSimpleCopyAssignment(), needsImplicitMoveAssignment(), and needsImplicitMoveConstructor().
hasUserDeclaredCopyConstructor()
bool clang::CXXRecordDecl::hasUserDeclaredCopyConstructor () const inline
Determine whether this class has a user-declared copy constructor.
When false, a copy constructor will be implicitly declared.
Definition at line 803 of file DeclCXX.h.
Referenced by hasSimpleCopyConstructor(), needsImplicitMoveAssignment(), and needsImplicitMoveConstructor().
hasUserDeclaredDestructor()
bool clang::CXXRecordDecl::hasUserDeclaredDestructor () const inline
Determine whether this class has a user-declared destructor.
When false, a destructor will be implicitly declared.
Definition at line 1004 of file DeclCXX.h.
Referenced by hasSimpleDestructor(), isInterfaceLike(), needsImplicitMoveAssignment(), and needsImplicitMoveConstructor().
hasUserDeclaredMoveAssignment()
bool clang::CXXRecordDecl::hasUserDeclaredMoveAssignment () const inline
Determine whether this class has had a move assignment declared by the user.
Definition at line 964 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), hasSimpleMoveAssignment(), needsImplicitMoveConstructor(), and clang::Sema::ShouldDeleteSpecialMember().
hasUserDeclaredMoveConstructor()
bool clang::CXXRecordDecl::hasUserDeclaredMoveConstructor () const inline
Determine whether this class has had a move constructor declared by the user.
Definition at line 856 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), hasSimpleMoveConstructor(), needsImplicitMoveAssignment(), and clang::Sema::ShouldDeleteSpecialMember().
hasUserDeclaredMoveOperation()
bool clang::CXXRecordDecl::hasUserDeclaredMoveOperation () const inline
Whether this class has a user-declared move constructor or assignment operator.
When false, a move constructor and assignment operator may be implicitly declared.
Definition at line 849 of file DeclCXX.h.
hasUserProvidedDefaultConstructor()
bool clang::CXXRecordDecl::hasUserProvidedDefaultConstructor () const inline
Whether this class has a user-provided default constructor per C++11.
Definition at line 796 of file DeclCXX.h.
Referenced by clang::Sema::getFixItZeroInitializerForType().
hasVariantMembers()
bool clang::CXXRecordDecl::hasVariantMembers () const inline
Determine whether this class has any variant members.
Definition at line 1236 of file DeclCXX.h.
Referenced by CheckConstexprFunctionBody(), and defaultedDefaultConstructorIsConstexpr().
implicitCopyAssignmentHasConstParam()
bool clang::CXXRecordDecl::implicitCopyAssignmentHasConstParam () const inline
Determine whether an implicit copy assignment operator for this type would have a parameter with a const-qualified reference type.
Definition at line 949 of file DeclCXX.h.
Referenced by clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::DeclareImplicitCopyAssignment(), and hasCopyAssignmentWithConstParam().
implicitCopyConstructorHasConstParam()
bool clang::CXXRecordDecl::implicitCopyConstructorHasConstParam () const inline
Determine whether an implicit copy constructor for this type would have a parameter with a const-qualified reference type.
Definition at line 830 of file DeclCXX.h.
References isAbstract().
Referenced by clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::DeclareImplicitCopyConstructor(), and hasCopyConstructorWithConstParam().
isAbstract()
bool clang::CXXRecordDecl::isAbstract () const inline
Determine whether this class has a pure virtual function.
The class is abstract per (C++ [class.abstract]p2) if it declares a pure virtual function or inherits a pure virtual function that is not overridden.
Definition at line 1221 of file DeclCXX.h.
Referenced by clang::Sema::CheckVirtualDtorCall(), clang::CodeGen::CodeGenFunction::EmitCtorPrologue(), clang::CodeGen::CodeGenFunction::EmitDestructorBody(), EvaluateUnaryTypeTrait(), clang::installapi::hasVTable(), implicitCopyConstructorHasConstParam(), clang::SemaCUDA::inferTargetForImplicitSpecialMember(), clang::Sema::isAbstractType(), clang::installapi::isRTTIWeakDef(), clang::Sema::MarkBaseAndMemberDestructorsReferenced(), and clang::Sema::SetCtorInitializers().
isAggregate()
bool clang::CXXRecordDecl::isAggregate () const inline
Determine whether this class is an aggregate (C++ [dcl.init.aggr]), which is a class with no user-declared constructors, no private or protected non-static data members, no base classes, and no virtual functions (C++ [dcl.init.aggr]p1).
Definition at line 1146 of file DeclCXX.h.
Referenced by canUseCtorHoming(), clang::Sema::getFixItZeroInitializerForType(), and clang::Sema::RequireLiteralType().
isAnyDestructorNoReturn()
bool clang::CXXRecordDecl::isAnyDestructorNoReturn () const inline
Returns true if the class destructor, or any implicitly invoked destructors are marked noreturn.
Definition at line 1543 of file DeclCXX.h.
isCapturelessLambda()
bool clang::CXXRecordDecl::isCapturelessLambda () const inline
Definition at line 1067 of file DeclCXX.h.
References capture_size(), getLambdaCaptureDefault(), isLambda(), and clang::LCD_None.
Referenced by clang::Sema::DiagnoseInvalidExplicitObjectParameterInLambda(), lambdaIsDefaultConstructibleAndAssignable(), and clang::CodeGen::CodeGenFunction::StartFunction().
isCLike()
bool CXXRecordDecl::isCLike () const
True if this class is C-like, without C++-specific features, e.g.
it contains only public fields, no bases, tag kind is not 'class', etc.
Definition at line 1552 of file DeclCXX.cpp.
References clang::Class, clang::TagDecl::getTagKind(), hasDefinition(), clang::Interface, and isPOD().
isCurrentInstantiation()
bool CXXRecordDecl::isCurrentInstantiation (const DeclContext * CurContext) const
Determine whether this dependent class is a current instantiation, when viewed from within the given context.
Definition at line 117 of file CXXInheritance.cpp.
References clang::DeclContext::Equals(), clang::DeclContext::getParent(), clang::DeclContext::isDependentContext(), and clang::DeclContext::isFileContext().
Referenced by clang::computeDependence().
isCXX11StandardLayout()
bool clang::CXXRecordDecl::isCXX11StandardLayout () const inline
Determine whether this class was standard-layout per C++11 [class]p7, specifically using the C++11 rules without any DRs.
Definition at line 1229 of file DeclCXX.h.
Referenced by mustSkipTailPadding().
isDependentLambda()
bool clang::CXXRecordDecl::isDependentLambda () const inline
Determine whether this lambda expression was known to be dependent at the time it was created, even if its context does not appear to be dependent.
This flag is a workaround for an issue with parsing, where default arguments are parsed before their enclosing function declarations have been created. This means that any lambda expressions within those default arguments will have as their DeclContext the context enclosing the function declaration, which may be non-dependent even when the function declaration itself is dependent. This flag indicates when we know that the lambda is dependent despite that.
Definition at line 1847 of file DeclCXX.h.
References isLambda(), and LDK_AlwaysDependent.
isDerivedFrom() [1/2]
bool CXXRecordDecl::isDerivedFrom (const CXXRecordDecl * Base) const
Determine whether this class is derived from the class Base.
This routine only determines whether this class is derived from Base, but does not account for factors that may make a Derived -> Base class ill-formed, such as private/protected inheritance or multiple, ambiguous base class subobjects.
Parameters
Base the base class we are searching for.
Returns
true if this class is derived from Base, false otherwise.
Definition at line 67 of file CXXInheritance.cpp.
Referenced by DiagnoseReinterpretUpDownCast(), clang::ento::CXXInstanceCall::getRuntimeDefinition(), clang::Sema::IsDerivedFrom(), and clang::FunctionCallFilterCCC::ValidateCandidate().
isDerivedFrom() [2/2]
bool CXXRecordDecl::isDerivedFrom (const CXXRecordDecl * Base, CXXBasePaths & Paths) const
Determine whether this class is derived from the type Base.
This routine only determines whether this class is derived from Base, but does not account for factors that may make a Derived -> Base class ill-formed, such as private/protected inheritance or multiple, ambiguous base class subobjects.
Parameters
Base the base class we are searching for.
Paths will contain the paths taken from the current class to the given Base class.
Returns
true if this class is derived from Base, false otherwise.
Todo:
add a separate parameter to configure IsDerivedFrom, rather than tangling input and output in Paths
Definition at line 73 of file CXXInheritance.cpp.
isDynamicClass()
bool clang::CXXRecordDecl::isDynamicClass () const inline
Definition at line 584 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), CanSkipVTablePointerInitialization(), CanUseSingleInheritance(), clang::CodeGen::CGDebugInfo::completeUnusedClass(), clang::ASTContext::DeclMustBeEmitted(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheckForCast(), getContainedDynamicClass(), getTypeInfoLinkage(), clang::installapi::getVTableLinkage(), clang::installapi::hasRTTI(), clang::installapi::hasVTable(), clang::CodeGen::CodeGenFunction::InitializeVTablePointers(), clang::SemaCUDA::isEmptyConstructor(), clang::SemaCUDA::isEmptyDestructor(), clang::installapi::isRTTIWeakDef(), clang::CodeGen::CodeGenFunction::isVptrCheckRequired(), clang::CodeGen::CodeGenVTables::isVTableExternal(), mayBeDynamicClass(), mayBeNonDynamicClass(), and clang::Sema::SpecialMemberIsTrivial().
isEffectivelyFinal()
bool CXXRecordDecl::isEffectivelyFinal () const
Determine whether it's impossible for a class to be derived from this class.
This is best-effort, and may conservatively return false.
Definition at line 2114 of file DeclCXX.cpp.
References getDefinition().
Referenced by clang::CodeGen::CGCXXABI::buildThisParam(), CanSkipVTablePointerInitialization(), clang::CodeGen::CodeGenFunction::EmitDynamicCast(), clang::CodeGen::CodeGenModule::getClassPointerAlignment(), clang::CXXMethodDecl::getDevirtualizedMethod(), and clang::CodeGen::CodeGenModule::getMinimumClassObjectSize().
isEmpty()
bool clang::CXXRecordDecl::isEmpty () const inline
Determine whether this is an empty class in the sense of (C++11 [meta.unary.prop]).
The CXXRecordDecl is a class type, but not a union type, with no non-static data members other than bit-fields of length 0, no virtual member functions, no virtual base classes, and no base class B for which is_empty<B>::value is false.
Note
This does NOT include a check for union-ness.
Definition at line 1189 of file DeclCXX.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), EmitNullConstant(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), EvaluateUnaryTypeTrait(), and isReadByLvalueToRvalueConversion().
isGenericLambda()
bool CXXRecordDecl::isGenericLambda () const
Determine whether this class describes a generic lambda function object (i.e.
function call operator is a template).
Definition at line 1563 of file DeclCXX.cpp.
References isLambda().
Referenced by clang::interp::ByteCodeEmitter::compileFunc(), clang::Sema::DefineImplicitLambdaToBlockPointerConversion(), clang::CodeGen::CodeGenFunction::EmitLambdaBlockInvokeBody(), clang::CodeGen::CodeGenFunction::EmitLambdaDelegatingInvokeBody(), getGenericLambdaTemplateParameterList(), clang::isGenericLambdaCallOperatorOrStaticInvokerSpecialization(), and clang::isGenericLambdaCallOperatorSpecialization().
isInterfaceLike()
bool CXXRecordDecl::isInterfaceLike () const
Definition at line 2003 of file DeclCXX.cpp.
References clang::AS_public, bases_begin(), conversion_begin(), conversion_end(), clang::RecordDecl::field_empty(), clang::Decl::getDeclContext(), clang::NamedDecl::getName(), getNumBases(), getNumVBases(), hasDefinition(), hasFriends(), hasUserDeclaredConstructor(), hasUserDeclaredDestructor(), isDeclContextInNamespace(), clang::DeclContext::isExternCContext(), clang::TagDecl::isInterface(), isLambda(), clang::TagDecl::isStruct(), and methods().
Referenced by clang::Sema::AttachBaseSpecifiers().
isLambda()
bool clang::CXXRecordDecl::isLambda () const inline
Determine whether this class describes a lambda function object.
Definition at line 1021 of file DeclCXX.h.
Referenced by canUseCtorHoming(), captures_begin(), captures_end(), clang::SemaSYCL::CheckSYCLKernelCall(), clang::SemaSYCL::ConstructOpenCLKernel(), getCapture(), getDeviceLambdaManglingNumber(), getLambdaCallOperatorHelper(), getLambdaCaptureDefault(), getLambdaContextDecl(), getLambdaDependencyKind(), getLambdaIndexInContext(), getLambdaManglingNumber(), getLambdaStaticInvoker(), getLambdaStaticInvokers(), clang::AnalysisDeclContext::getSelfDecl(), hasKnownLambdaInternalLinkage(), isCapturelessLambda(), isDependentLambda(), IsDerivedFromInclusive(), isGenericLambda(), isInterfaceLike(), clang::isLambdaCallOperator(), clang::CXXConversionDecl::isLambdaToBlockPointerConversion(), isNeverDependentLambda(), lambdaIsDefaultConstructibleAndAssignable(), needsImplicitDefaultConstructor(), needsImplicitMoveAssignment(), clang::Sema::RequireLiteralType(), setLambdaNumbering(), clang::Sema::ShouldDeleteSpecialMember(), clang::CodeGen::CodeGenFunction::StartFunction(), and clang::ASTDeclWriter::VisitCXXRecordDecl().
isLiteral()
bool CXXRecordDecl::isLiteral () const
Determine whether this class is a literal type.
C++20 [basic.types]p10: A class type that has all the following properties:
it has a constexpr destructor
all of its non-static non-variant data members and base classes are of non-volatile literal types, and it:
is a closure type
is an aggregate union type that has either no variant members or at least one variant member of non-volatile literal type
is a non-union aggregate type for which each of its anonymous union members satisfies the above requirements for an aggregate union type, or
has at least one constexpr constructor or constructor template that is not a copy or move constructor.
Definition at line 1389 of file DeclCXX.cpp.
Referenced by isStructural().
isLocalClass() [1/2]
FunctionDecl* clang::CXXRecordDecl::isLocalClass () inline
Definition at line 1554 of file DeclCXX.h.
References isLocalClass().
isLocalClass() [2/2]
const FunctionDecl* clang::CXXRecordDecl::isLocalClass () const inline
If the class is a local class [class.local], returns the enclosing function declaration.
Definition at line 1547 of file DeclCXX.h.
References clang::Decl::getDeclContext().
Referenced by clang::Sema::InstantiateClassMembers(), and isLocalClass().
isNeverDependentLambda()
bool clang::CXXRecordDecl::isNeverDependentLambda () const inline
Definition at line 1851 of file DeclCXX.h.
References isLambda(), and LDK_NeverDependent.
isParsingBaseSpecifiers()
bool clang::CXXRecordDecl::isParsingBaseSpecifiers () const inline
Definition at line 602 of file DeclCXX.h.
Referenced by calculateInheritanceModel().
isPOD()
bool clang::CXXRecordDecl::isPOD () const inline
Whether this class is a POD-type (C++ [class]p4)
For purposes of this function a class is POD if it is an aggregate that has no non-static non-POD data members, no reference data members, no user-defined copy assignment operator and no user-defined destructor.
Note that this is the C++ TR1 definition of POD.
Definition at line 1174 of file DeclCXX.h.
Referenced by isCLike(), and mustSkipTailPadding().
isPolymorphic()
bool clang::CXXRecordDecl::isPolymorphic () const inline
Whether this class is polymorphic (C++ [class.virtual]), which means that the class contains or inherits a virtual function.
Definition at line 1214 of file DeclCXX.h.
Referenced by clang::Sema::BuildCXXTypeId(), clang::Sema::checkIllFormedTrivialABIStruct(), clang::Sema::CheckVirtualDtorCall(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), EvaluateUnaryTypeTrait(), isTrivialForMSVC(), nullFieldOffsetIsZero(), and usesMultipleInheritanceModel().
isProvablyNotDerivedFrom()
bool CXXRecordDecl::isProvablyNotDerivedFrom (const CXXRecordDecl * Base) const
Determine whether this class is provably not derived from the type Base.
Definition at line 109 of file CXXInheritance.cpp.
References forallBases().
Referenced by clang::Sema::CheckQualifiedMemberReference().
isStandardLayout()
bool clang::CXXRecordDecl::isStandardLayout () const inline
Determine whether this class is standard-layout per C++ [class]p7.
Definition at line 1225 of file DeclCXX.h.
Referenced by clang::Sema::IsPointerInterconvertibleBaseOf().
isStructural()
bool clang::CXXRecordDecl::isStructural () const inline
Determine whether this is a structural type.
Definition at line 1458 of file DeclCXX.h.
References isLiteral().
isTrivial()
bool clang::CXXRecordDecl::isTrivial () const inline
Determine whether this class is considered trivial.
C++11 [class]p6: "A trivial class is a class that has a trivial default constructor and is trivially copyable."
Definition at line 1436 of file DeclCXX.h.
References hasTrivialDefaultConstructor(), and isTriviallyCopyable().
Referenced by mustSkipTailPadding().
isTriviallyCopyable()
bool CXXRecordDecl::isTriviallyCopyable () const
Determine whether this class is considered trivially copyable per (C++11 [class]p6).
Definition at line 575 of file DeclCXX.cpp.
References hasNonTrivialCopyAssignment(), hasNonTrivialCopyConstructor(), hasNonTrivialMoveAssignment(), hasNonTrivialMoveConstructor(), and hasTrivialDestructor().
Referenced by clang::Sema::CheckComparisonCategoryType(), and isTrivial().
isTriviallyCopyConstructible()
bool CXXRecordDecl::isTriviallyCopyConstructible () const
Determine whether this class is considered trivially copyable per.
Definition at line 592 of file DeclCXX.cpp.
References hasNonTrivialCopyConstructor(), and hasTrivialDestructor().
isVirtuallyDerivedFrom()
bool CXXRecordDecl::isVirtuallyDerivedFrom (const CXXRecordDecl * Base) const
Determine whether this class is virtually derived from the class Base.
This routine only determines whether this class is virtually derived from Base, but does not account for factors that may make a Derived -> Base class ill-formed, such as private/protected inheritance or multiple, ambiguous base class subobjects.
Parameters
Base the base class we are searching for.
Returns
true if this class is virtually derived from Base, false otherwise.
Definition at line 89 of file CXXInheritance.cpp.
References getNumVBases().
lambdaIsDefaultConstructibleAndAssignable()
bool CXXRecordDecl::lambdaIsDefaultConstructibleAndAssignable () const
Determine whether this lambda should have an implicit default constructor and copy and move assignment operators.
Definition at line 691 of file DeclCXX.cpp.
References clang::Decl::getASTContext(), clang::ASTContext::getLangOpts(), isCapturelessLambda(), and isLambda().
Referenced by needsImplicitDefaultConstructor(), needsImplicitMoveAssignment(), and clang::Sema::ShouldDeleteSpecialMember().
lookupDependentName()
std::vector< const NamedDecl * > CXXRecordDecl::lookupDependentName (DeclarationName Name, llvm::function_ref< bool(const NamedDecl *ND)> Filter)
Performs an imprecise lookup of a dependent name in this class.
This function does not follow strict semantic rules and should be used only when lookup rules can be relaxed, e.g. indexing.
Definition at line 432 of file CXXInheritance.cpp.
lookupInBases()
bool CXXRecordDecl::lookupInBases (BaseMatchesCallback BaseMatches, CXXBasePaths & Paths, bool LookupInDependent = false) const
Look for entities within the base classes of this C++ class, transitively searching all base class subobjects.
This routine uses the callback function BaseMatches to find base classes meeting some search criteria, walking all base class subobjects and populating the given Paths structure with the paths through the inheritance hierarchy that resulted in a match. On a successful search, the Paths structure can be queried to retrieve the matching paths and to determine if there were any ambiguities.
Parameters
BaseMatches callback function used to determine whether a given base matches the user-defined search criteria.
Paths used to record the paths from this class to its base class subobjects that match the search criteria.
LookupInDependent can be set to true to extend the search to dependent base classes.
Returns
true if there exists any path from this class to a base class subobject that matches the search criteria.
Definition at line 307 of file CXXInheritance.cpp.
markAbstract()
void clang::CXXRecordDecl::markAbstract () inline
Definition at line 1891 of file DeclCXX.h.
markEmpty()
void clang::CXXRecordDecl::markEmpty () inline
Marks this record as empty.
This is used by DWARFASTParserClang when parsing records with empty fields having [[no_unique_address]] attribute
Definition at line 1193 of file DeclCXX.h.
mayBeAbstract()
bool CXXRecordDecl::mayBeAbstract () const
Determine whether this class may end up being abstract, even though it is not yet known to be abstract.
Returns
true if this class is not known to be abstract but has any base classes that are abstract. In this case, completeDefinition() will need to compute final overriders to determine whether the class is actually abstract.
Definition at line 2099 of file DeclCXX.cpp.
References bases(), clang::RecordType::getDecl(), clang::DeclContext::isDependentContext(), and clang::Decl::isInvalidDecl().
Referenced by completeDefinition().
mayBeDynamicClass()
bool clang::CXXRecordDecl::mayBeDynamicClass () const inline
Returns
true if class is dynamic or might be dynamic because the definition is incomplete of dependent.
Definition at line 590 of file DeclCXX.h.
References hasAnyDependentBases(), hasDefinition(), and isDynamicClass().
Referenced by clang::QualType::mayBeDynamicClass().
mayBeNonDynamicClass()
bool clang::CXXRecordDecl::mayBeNonDynamicClass () const inline
Returns
true if class is non dynamic or might be non dynamic because the definition is incomplete of dependent.
Definition at line 596 of file DeclCXX.h.
References hasAnyDependentBases(), hasDefinition(), and isDynamicClass().
Referenced by clang::QualType::mayBeNotDynamicClass().
MergeAccess()
static AccessSpecifier clang::CXXRecordDecl::MergeAccess (AccessSpecifier PathAccess, AccessSpecifier DeclAccess) inline static
Calculates the access of a decl that is reached along a path.
Definition at line 1722 of file DeclCXX.h.
References clang::AS_none, and clang::AS_private.
Referenced by clang::Sema::LookupInSuper().
method_begin()
method_iterator clang::CXXRecordDecl::method_begin () const inline
Method begin iterator.
Iterates in the order the methods were declared.
Definition at line 666 of file DeclCXX.h.
References clang::DeclContext::decls_begin().
Referenced by methods().
method_end()
method_iterator clang::CXXRecordDecl::method_end () const inline
Method past-the-end iterator.
Definition at line 671 of file DeclCXX.h.
References clang::DeclContext::decls_end().
Referenced by methods().
methods()
method_range clang::CXXRecordDecl::methods () const inline
Definition at line 660 of file DeclCXX.h.
References method_begin(), and method_end().
Referenced by getMethodByName(), clang::ASTNodeImporter::ImportImplicitMethods(), clang::dataflow::isCheckLikeMethod(), isClassOrMethodDLLImport(), isInterfaceLike(), LeastDerivedClassWithSameLayout(), clang::Sema::MarkVirtualMemberExceptionSpecsNeeded(), clang::Sema::ShouldDeleteSpecialMember(), clang::Sema::SpecialMemberIsTrivial(), clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl(), and clang::installapi::InstallAPIVisitor::VisitCXXRecordDecl().
needsImplicitCopyAssignment()
bool clang::CXXRecordDecl::needsImplicitCopyAssignment () const inline
Determine whether this class needs an implicit copy assignment operator to be lazily declared.
Definition at line 928 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), clang::Sema::DeclareImplicitCopyAssignment(), and hasCopyAssignmentWithConstParam().
needsImplicitCopyConstructor()
bool clang::CXXRecordDecl::needsImplicitCopyConstructor () const inline
Determine whether this class needs an implicit copy constructor to be lazily declared.
Definition at line 809 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), clang::Sema::checkIllFormedTrivialABIStruct(), clang::Sema::DeclareImplicitCopyConstructor(), and hasCopyConstructorWithConstParam().
needsImplicitDefaultConstructor()
bool clang::CXXRecordDecl::needsImplicitDefaultConstructor () const inline
Determine if we need to declare a default constructor for this class.
This value is used for lazy creation of default constructors.
Definition at line 776 of file DeclCXX.h.
References isLambda(), and lambdaIsDefaultConstructibleAndAssignable().
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), allowConstDefaultInit(), clang::Sema::DeclareImplicitDefaultConstructor(), hasConstexprDefaultConstructor(), hasConstexprNonCopyMoveConstructor(), hasDefaultConstructor(), and hasNonTrivialDefaultConstructor().
needsImplicitDestructor()
bool clang::CXXRecordDecl::needsImplicitDestructor () const inline
Determine whether this class needs an implicit destructor to be lazily declared.
Definition at line 1010 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), clang::Sema::DeclareImplicitDestructor(), and clang::Sema::LookupSpecialMember().
needsImplicitMoveAssignment()
bool clang::CXXRecordDecl::needsImplicitMoveAssignment () const inline
Determine whether this class should get an implicit move assignment operator or if any existing special member function inhibits this.
Definition at line 986 of file DeclCXX.h.
References hasUserDeclaredCopyAssignment(), hasUserDeclaredCopyConstructor(), hasUserDeclaredDestructor(), hasUserDeclaredMoveConstructor(), isLambda(), and lambdaIsDefaultConstructibleAndAssignable().
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), clang::Sema::DeclareImplicitMoveAssignment(), hasMoveAssignment(), and hasNonTrivialMoveAssignment().
needsImplicitMoveConstructor()
bool clang::CXXRecordDecl::needsImplicitMoveConstructor () const inline
Determine whether this class should get an implicit move constructor or if any existing special member function inhibits this.
Definition at line 895 of file DeclCXX.h.
References hasUserDeclaredCopyAssignment(), hasUserDeclaredCopyConstructor(), hasUserDeclaredDestructor(), and hasUserDeclaredMoveAssignment().
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), clang::Sema::checkIllFormedTrivialABIStruct(), clang::Sema::DeclareImplicitMoveConstructor(), hasMoveConstructor(), hasNonTrivialMoveConstructor(), and hasNonTrivialMoveConstructorForCall().
needsOverloadResolutionForCopyAssignment()
bool clang::CXXRecordDecl::needsOverloadResolutionForCopyAssignment () const inline
Determine whether we need to eagerly declare a defaulted copy assignment operator for this class.
Definition at line 934 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), and setImplicitCopyAssignmentIsDeleted().
needsOverloadResolutionForCopyConstructor()
bool clang::CXXRecordDecl::needsOverloadResolutionForCopyConstructor () const inline
Determine whether we need to eagerly declare a defaulted copy constructor for this class.
Definition at line 815 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), createCopyConstructorDefinitionData(), defaultedCopyConstructorIsDeleted(), setImplicitCopyConstructorIsDeleted(), and clang::TextNodeDumper::VisitCXXRecordDecl().
needsOverloadResolutionForDestructor()
bool clang::CXXRecordDecl::needsOverloadResolutionForDestructor () const inline
Determine whether we need to eagerly declare a destructor for this class.
Definition at line 1016 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), createDestructorDefinitionData(), defaultedDestructorIsDeleted(), setImplicitDestructorIsDeleted(), and clang::TextNodeDumper::VisitCXXRecordDecl().
needsOverloadResolutionForMoveAssignment()
bool clang::CXXRecordDecl::needsOverloadResolutionForMoveAssignment () const inline
Determine whether we need to eagerly declare a move assignment operator for this class.
Definition at line 997 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), and setImplicitMoveAssignmentIsDeleted().
needsOverloadResolutionForMoveConstructor()
bool clang::CXXRecordDecl::needsOverloadResolutionForMoveConstructor () const inline
Determine whether we need to eagerly declare a defaulted move constructor for this class.
Definition at line 905 of file DeclCXX.h.
Referenced by clang::Sema::AddImplicitlyDeclaredMembersToClass(), createMoveConstructorDefinitionData(), defaultedMoveConstructorIsDeleted(), setImplicitMoveConstructorIsDeleted(), and clang::TextNodeDumper::VisitCXXRecordDecl().
nullFieldOffsetIsZero()
bool CXXRecordDecl::nullFieldOffsetIsZero () const
In the Microsoft C++ ABI, use zero for the field offset of a null data member pointer if we can guarantee that zero is not a valid field offset, or if the member pointer has multiple fields.
Polymorphic classes have a vfptr at offset zero, so we can use zero for null. If there are multiple fields, we can use zero even if it is a valid field offset because null-ness testing will check the other fields.
Definition at line 241 of file MicrosoftCXXABI.cpp.
References getMSInheritanceModel(), hasDefinition(), clang::inheritanceModelHasOnlyOneField(), and isPolymorphic().
pushFriendDecl()
void clang::CXXRecordDecl::pushFriendDecl (FriendDecl * FD) inline
Definition at line 250 of file DeclFriend.h.
removeConversion()
void CXXRecordDecl::removeConversion (const NamedDecl * Old)
Removes a conversion function from this class.
The conversion function must currently be a member of this class. Furthermore, this class must currently be in the process of being defined.
Definition at line 1850 of file DeclCXX.cpp.
References clang::ASTUnresolvedSet::erase(), clang::Decl::getASTContext(), and clang::ASTUnresolvedSet::size().
setBases()
void CXXRecordDecl::setBases (CXXBaseSpecifier const *const * Bases, unsigned NumBases)
Sets the base classes of this struct or class.
Definition at line 194 of file DeclCXX.cpp.
References clang::AS_public, clang::CanNeverPassInRegs, clang::Type::castAs(), clang::Type::getAsCXXRecordDecl(), clang::Decl::getASTContext(), clang::RecordType::getDecl(), hasNonLiteralTypeFieldsOrBases(), hasRepeatedBaseClass(), clang::Type::isDependentType(), clang::Type::isLiteralType(), clang::RecordDecl::setArgPassingRestrictions(), clang::RecordDecl::setHasObjectMember(), and clang::RecordDecl::setHasVolatileMember().
setCaptures()
void CXXRecordDecl::setCaptures (ASTContext & Context, ArrayRef< LambdaCapture > Captures)
Set the captures for this lambda closure type.
Definition at line 1513 of file DeclCXX.cpp.
setDescribedClassTemplate()
void CXXRecordDecl::setDescribedClassTemplate (ClassTemplateDecl * Template)
Definition at line 1900 of file DeclCXX.cpp.
setHasTrivialSpecialMemberForCall()
void clang::CXXRecordDecl::setHasTrivialSpecialMemberForCall () inline
Definition at line 1384 of file DeclCXX.h.
setImplicitCopyAssignmentIsDeleted()
void clang::CXXRecordDecl::setImplicitCopyAssignmentIsDeleted () inline
Set that we attempted to declare an implicit copy assignment operator, but overload resolution failed so we deleted it.
Definition at line 919 of file DeclCXX.h.
References needsOverloadResolutionForCopyAssignment().
setImplicitCopyConstructorIsDeleted()
void clang::CXXRecordDecl::setImplicitCopyConstructorIsDeleted () inline
Set that we attempted to declare an implicit copy constructor, but overload resolution failed so we deleted it.
Definition at line 868 of file DeclCXX.h.
References needsOverloadResolutionForCopyConstructor().
setImplicitDestructorIsDeleted()
void clang::CXXRecordDecl::setImplicitDestructorIsDeleted () inline
Set that we attempted to declare an implicit destructor, but overload resolution failed so we deleted it.
Definition at line 886 of file DeclCXX.h.
References needsOverloadResolutionForDestructor().
setImplicitMoveAssignmentIsDeleted()
void clang::CXXRecordDecl::setImplicitMoveAssignmentIsDeleted () inline
Set that we attempted to declare an implicit move assignment operator, but overload resolution failed so we deleted it.
Definition at line 976 of file DeclCXX.h.
References needsOverloadResolutionForMoveAssignment().
setImplicitMoveConstructorIsDeleted()
void clang::CXXRecordDecl::setImplicitMoveConstructorIsDeleted () inline
Set that we attempted to declare an implicit move constructor, but overload resolution failed so we deleted it.
Definition at line 877 of file DeclCXX.h.
References needsOverloadResolutionForMoveConstructor().
setInitMethod()
void clang::CXXRecordDecl::setInitMethod (bool Val) inline
Definition at line 1195 of file DeclCXX.h.
setInstantiationOfMemberClass()
void CXXRecordDecl::setInstantiationOfMemberClass (CXXRecordDecl * RD, TemplateSpecializationKind TSK)
Specify that this record is an instantiation of the member class RD.
Definition at line 1887 of file DeclCXX.cpp.
References clang::Decl::getASTContext().
setIsParsingBaseSpecifiers()
void clang::CXXRecordDecl::setIsParsingBaseSpecifiers () inline
Definition at line 600 of file DeclCXX.h.
setLambdaDependencyKind()
void clang::CXXRecordDecl::setLambdaDependencyKind (unsigned Kind) inline
Definition at line 1872 of file DeclCXX.h.
setLambdaIsGeneric()
void clang::CXXRecordDecl::setLambdaIsGeneric (bool IsGeneric) inline
Definition at line 1876 of file DeclCXX.h.
Referenced by clang::Sema::ActOnLambdaClosureParameters(), and clang::Sema::CompleteLambdaCallOperator().
setLambdaNumbering()
void CXXRecordDecl::setLambdaNumbering (LambdaNumbering Numbering)
Set the mangling numbers and context declaration for a lambda class.
Definition at line 1690 of file DeclCXX.cpp.
References clang::CXXRecordDecl::LambdaNumbering::ContextDecl, clang::CXXRecordDecl::LambdaNumbering::DeviceManglingNumber, clang::Decl::getASTContext(), clang::CXXRecordDecl::LambdaNumbering::HasKnownInternalLinkage, clang::CXXRecordDecl::LambdaNumbering::IndexInContext, isLambda(), and clang::CXXRecordDecl::LambdaNumbering::ManglingNumber.
setLambdaTypeInfo()
void clang::CXXRecordDecl::setLambdaTypeInfo (TypeSourceInfo * TS) inline
Definition at line 1865 of file DeclCXX.h.
Referenced by clang::Sema::CompleteLambdaCallOperator().
setTemplateSpecializationKind()
void CXXRecordDecl::setTemplateSpecializationKind (TemplateSpecializationKind TSK)
Set the kind of specialization or template instantiation this is.
Definition at line 1915 of file DeclCXX.cpp.
References getMemberSpecializationInfo().
Referenced by clang::ASTNodeImporter::VisitClassTemplateSpecializationDecl().
setTrivialForCallFlags()
void CXXRecordDecl::setTrivialForCallFlags (CXXMethodDecl * MD)
Definition at line 1535 of file DeclCXX.cpp.
References clang::FunctionDecl::isTrivialForCall().
vbases() [1/2]
base_class_range clang::CXXRecordDecl::vbases () inline
Definition at line 635 of file DeclCXX.h.
References vbases_begin(), and vbases_end().
Referenced by clang::Sema::CheckConstexprFunctionDefinition(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::Sema::DefineInheritingConstructor(), DiagnoseBaseOrMemInitializerOrder(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), clang::CodeGen::CodeGenModule::GetVCallVisibilityLevel(), clang::SemaCUDA::inferTargetForImplicitSpecialMember(), clang::Sema::MarkVirtualBaseDestructorsReferenced(), clang::Sema::RequireLiteralType(), and clang::Sema::SetCtorInitializers().
vbases() [2/2]
base_class_const_range clang::CXXRecordDecl::vbases () const inline
Definition at line 638 of file DeclCXX.h.
References vbases_begin(), and vbases_end().
vbases_begin() [1/2]
base_class_iterator clang::CXXRecordDecl::vbases_begin () inline
Definition at line 642 of file DeclCXX.h.
Referenced by clang::Sema::SpecialMemberIsTrivial(), vbases(), and vbases_end().
vbases_begin() [2/2]
base_class_const_iterator clang::CXXRecordDecl::vbases_begin () const inline
Definition at line 643 of file DeclCXX.h.
vbases_end() [1/2]
base_class_iterator clang::CXXRecordDecl::vbases_end () inline
Definition at line 644 of file DeclCXX.h.
References vbases_begin().
Referenced by vbases().
vbases_end() [2/2]
base_class_const_iterator clang::CXXRecordDecl::vbases_end () const inline
Definition at line 645 of file DeclCXX.h.
References vbases_begin().
viewInheritance()
void CXXRecordDecl::viewInheritance (ASTContext & Context) const
Renders and displays an inheritance diagram for this C++ class and all of its base classes (transitively) using GraphViz.
viewInheritance - Display the inheritance hierarchy of this C++ class using GraphViz.
Definition at line 136 of file InheritViz.cpp.
Friends And Related Function Documentation
ASTDeclReader
friend class ASTDeclReader friend
Definition at line 259 of file DeclCXX.h.
ASTDeclWriter
friend class ASTDeclWriter friend
Definition at line 260 of file DeclCXX.h.
ASTNodeImporter
friend class ASTNodeImporter friend
Definition at line 261 of file DeclCXX.h.
ASTReader
friend class ASTReader friend
Definition at line 262 of file DeclCXX.h.
ASTRecordWriter
friend class ASTRecordWriter friend
Definition at line 263 of file DeclCXX.h.
ASTWriter
friend class ASTWriter friend
Definition at line 264 of file DeclCXX.h.
DeclContext
friend class DeclContext friend
Definition at line 265 of file DeclCXX.h.
FunctionDecl::setIsPureVirtual
void FunctionDecl::setIsPureVirtual (bool) friend
LambdaExpr
friend class LambdaExpr friend
Definition at line 266 of file DeclCXX.h.
ODRDiagsEmitter
friend class ODRDiagsEmitter friend
Definition at line 267 of file DeclCXX.h.
TagDecl::startDefinition
void TagDecl::startDefinition () friend
The documentation for this class was generated from the following files:
include/clang/AST/DeclCXX.h
include/clang/AST/DeclFriend.h
lib/AST/CXXInheritance.cpp
lib/AST/DeclCXX.cpp
lib/AST/DeclFriend.cpp
lib/AST/InheritViz.cpp
lib/AST/MicrosoftCXXABI.cpp