clang: clang::driver::ToolChain Class Reference
clang::driver::ToolChain Class Reference abstract
ToolChain - Access to tools for a single platform.
#include "clang/Driver/ToolChain.h"
Classes
struct BitCodeLibraryInfo
Public Types
enum CXXStdlibType { CST_Libcxx , CST_Libstdcxx }
enum RuntimeLibType { RLT_CompilerRT , RLT_Libgcc }
enum UnwindLibType { UNW_None , UNW_CompilerRT , UNW_Libgcc }
enum class UnwindTableLevel { None , Synchronous , Asynchronous }
enum RTTIMode { RM_Enabled , RM_Disabled }
enum ExceptionsMode { EM_Enabled , EM_Disabled }
enum FileType { FT_Object , FT_Static , FT_Shared }
using path_list = SmallVector< std::string, 16 >
Public Member Functions
virtual ~ToolChain ()
const Driver & getDriver () const
llvm::vfs::FileSystem & getVFS () const
const llvm::Triple & getTriple () const
virtual const llvm::Triple * getAuxTriple () const
Get the toolchain's aux triple, if it has one.
virtual std::string getInputFilename (const InputInfo &Input) const
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
llvm::Triple::ArchType getArch () const
StringRef getArchName () const
StringRef getPlatform () const
StringRef getOS () const
StringRef getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
std::string getTripleString () const
const llvm::Triple & getEffectiveTriple () const
Get the toolchain's effective clang triple.
bool hasEffectiveTriple () const
path_list & getLibraryPaths ()
const path_list & getLibraryPaths () const
path_list & getFilePaths ()
const path_list & getFilePaths () const
path_list & getProgramPaths ()
const path_list & getProgramPaths () const
const MultilibSet & getMultilibs () const
const llvm::SmallVector< Multilib > & getSelectedMultilibs () const
Multilib::flags_list getMultilibFlags (const llvm::opt::ArgList &) const
Get flags suitable for multilib selection, based on the provided clang command line arguments.
SanitizerArgs getSanitizerArgs (const llvm::opt::ArgList &JobArgs) const
const XRayArgs & getXRayArgs () const
const llvm::opt::Arg * getRTTIArg () const
RTTIMode getRTTIMode () const
ExceptionsMode getExceptionsMode () const
virtual llvm::opt::DerivedArgList * TranslateArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
virtual llvm::opt::DerivedArgList * TranslateOffloadTargetArgs (const llvm::opt::DerivedArgList &Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > &AllocatedArgs, Action::OffloadKind DeviceOffloadKind) const
TranslateOffloadTargetArgs - Create a new derived argument list for that contains the Offload target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val Also handles -Xsycl-target OR -Xsycl-target=<triple>
virtual void TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, llvm::opt::Arg *&A, llvm::opt::DerivedArgList *DAL, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs=nullptr) const
Append the argument following A to DAL assuming A is an Xarch argument.
virtual llvm::opt::DerivedArgList * TranslateXarchArgs (const llvm::opt::DerivedArgList &Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > *AllocatedArgs) const
Translate -Xarch_ arguments.
virtual Tool * SelectTool (const JobAction &JA) const
Choose a tool to use to handle the action JA.
std::string GetFilePath (const char *Name) const
std::string GetProgramPath (const char *Name) const
std::string GetLinkerPath (bool *LinkerIsLLD=nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
std::string GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
virtual void printVerboseInfo (raw_ostream &OS) const
Dispatch to the specific toolchain for verbose printing.
virtual bool isCrossCompiling () const
Returns true if the toolchain is targeting a non-native architecture.
virtual bool HasNativeLLVMSupport () const
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
virtual types::ID LookupTypeForExtension (StringRef Ext) const
LookupTypeForExtension - Return the default language type to use for the given extension.
virtual bool IsBlocksDefault () const
IsBlocksDefault - Does this tool chain enable -fblocks by default.
virtual bool IsIntegratedAssemblerDefault () const
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
virtual bool IsIntegratedBackendDefault () const
IsIntegratedBackendDefault - Does this tool chain enable -fintegrated-objemitter by default.
virtual bool IsIntegratedBackendSupported () const
IsIntegratedBackendSupported - Does this tool chain support -fintegrated-objemitter.
virtual bool IsNonIntegratedBackendSupported () const
IsNonIntegratedBackendSupported - Does this tool chain support -fno-integrated-objemitter.
virtual bool useIntegratedAs () const
Check if the toolchain should use the integrated assembler.
virtual bool useIntegratedBackend () const
Check if the toolchain should use the integrated backend.
virtual bool parseInlineAsmUsingAsmParser () const
Check if the toolchain should use AsmParser to parse inlineAsm when integrated assembler is not default.
virtual bool IsMathErrnoDefault () const
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
virtual bool IsEncodeExtendedBlockSignatureDefault () const
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
virtual bool IsObjCNonFragileABIDefault () const
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
virtual bool UseObjCMixedDispatch () const
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
virtual bool useRelaxRelocations () const
Check whether to enable x86 relax relocations by default.
bool defaultToIEEELongDouble () const
Check whether use IEEE binary128 as long double format by default.
virtual LangOptions::StackProtectorMode GetDefaultStackProtectorLevel (bool KernelOrKext) const
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
virtual LangOptions::TrivialAutoVarInitKind GetDefaultTrivialAutoVarInit () const
Get the default trivial automatic variable initialization.
virtual const char * getDefaultLinker () const
GetDefaultLinker - Get the default linker to use.
virtual RuntimeLibType GetDefaultRuntimeLibType () const
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
virtual CXXStdlibType GetDefaultCXXStdlibType () const
virtual UnwindLibType GetDefaultUnwindLibType () const
virtual std::string getCompilerRTPath () const
virtual std::string getCompilerRT (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
const char * getCompilerRTArgString (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::string getCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type=ToolChain::FT_Static) const
std::optional< std::string > getRuntimePath () const
std::optional< std::string > getStdlibPath () const
virtual path_list getArchSpecificLibPaths () const
virtual StringRef getOSLibName () const
virtual UnwindTableLevel getDefaultUnwindTableLevel (const llvm::opt::ArgList &Args) const
How detailed should the unwind tables be by default.
virtual bool IsAArch64OutlineAtomicsDefault (const llvm::opt::ArgList &Args) const
Test whether this toolchain supports outline atomics by default.
virtual bool isPICDefault () const =0
Test whether this toolchain defaults to PIC.
virtual bool isPIEDefault (const llvm::opt::ArgList &Args) const =0
Test whether this toolchain defaults to PIE.
virtual bool isPICDefaultForced () const =0
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
virtual bool SupportsProfiling () const
SupportsProfiling - Does this tool chain support -pg.
virtual void CheckObjCARC () const
Complain if this tool chain doesn't support Objective-C ARC.
virtual llvm::codegenoptions::DebugInfoFormat getDefaultDebugFormat () const
Get the default debug info format. Typically, this is DWARF.
virtual bool UseDwarfDebugFlags () const
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
virtual std::string GetGlobalDebugPathRemapping () const
Add an additional -fdebug-prefix-map entry.
virtual unsigned GetDefaultDwarfVersion () const
virtual unsigned getMaxDwarfVersion () const
virtual bool GetDefaultStandaloneDebug () const
virtual llvm::DebuggerKind getDefaultDebuggerTuning () const
virtual bool supportsDebugInfoOption (const llvm::opt::Arg *) const
Does this toolchain supports given debug info option or not.
virtual void adjustDebugInfoKind (llvm::codegenoptions::DebugInfoKind &DebugInfoKind, const llvm::opt::ArgList &Args) const
Adjust debug information kind considering all passed options.
virtual llvm::ExceptionHandling GetExceptionModel (const llvm::opt::ArgList &Args) const
GetExceptionModel - Return the tool chain exception model.
virtual bool SupportsEmbeddedBitcode () const
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
virtual std::string getThreadModel () const
getThreadModel() - Which thread model does this target use?
virtual bool isThreadModelSupported (const StringRef Model) const
isThreadModelSupported() - Does this target support a thread model?
virtual bool isBareMetal () const
isBareMetal - Is this a bare metal target.
virtual std::string getMultiarchTriple (const Driver &D, const llvm::Triple &TargetTriple, StringRef SysRoot) const
virtual std::string ComputeLLVMTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
virtual std::string ComputeEffectiveClangTriple (const llvm::opt::ArgList &Args, types::ID InputType=types::TY_INVALID) const
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
virtual ObjCRuntime getDefaultObjCRuntime (bool isNonFragile) const
getDefaultObjCRuntime - Return the default Objective-C runtime for this platform.
virtual bool hasBlocksRuntime () const
hasBlocksRuntime - Given that the user is compiling with -fblocks, does this tool chain guarantee the existence of a blocks runtime?
virtual std::string computeSysRoot () const
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
virtual void AddClangSystemIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add the clang cc1 arguments for system include paths.
virtual void addClangTargetOptions (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, Action::OffloadKind DeviceOffloadKind) const
Add options that need to be passed to cc1 for this target.
virtual void addClangCC1ASTargetOptions (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CC1ASArgs) const
Add options that need to be passed to cc1as for this target.
virtual void addClangWarningOptions (llvm::opt::ArgStringList &CC1Args) const
Add warning options that need to be passed to cc1 for this target.
virtual RuntimeLibType GetRuntimeLibType (const llvm::opt::ArgList &Args) const
virtual CXXStdlibType GetCXXStdlibType (const llvm::opt::ArgList &Args) const
virtual UnwindLibType GetUnwindLibType (const llvm::opt::ArgList &Args) const
virtual std::string detectLibcxxVersion (StringRef IncludePath) const
virtual void AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
void AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
bool ShouldLinkCXXStdlib (const llvm::opt::ArgList &Args) const
Returns if the C++ standard library should be linked in.
virtual void AddCXXStdlibLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
void AddFilePathLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
virtual void AddCCKextLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
virtual bool isFastMathRuntimeAvailable (const llvm::opt::ArgList &Args, std::string &Path) const
If a runtime library exists that sets global flags for unsafe floating point math, return true.
bool addFastMathRuntimeIfAvailable (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
virtual Expected< SmallVector< std::string > > getSystemGPUArchs (const llvm::opt::ArgList &Args) const
getSystemGPUArchs - Use a tool to detect the user's availible GPUs.
virtual void addProfileRTLibs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
addProfileRTLibs - When -fprofile-instr-profile is specified, try to pass a suitable profile runtime library to the linker.
virtual void AddCudaIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific CUDA includes.
virtual void AddHIPIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use system-specific HIP includes.
virtual void AddIAMCUIncludeArgs (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args) const
Add arguments to use MCU GCC toolchain includes.
virtual VersionTuple computeMSVCVersion (const Driver *D, const llvm::opt::ArgList &Args) const
On Windows, returns the MSVC compatibility version.
virtual llvm::SmallVector< BitCodeLibraryInfo, 12 > getDeviceLibs (const llvm::opt::ArgList &Args, const Action::OffloadKind DeviceOffloadingKind) const
Get paths for device libraries.
virtual void AddHIPRuntimeLibArgs (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs) const
Add the system specific linker arguments to use for the given HIP runtime library type.
virtual SanitizerMask getSupportedSanitizers () const
Return sanitizers which are available in this toolchain.
virtual SanitizerMask getDefaultSanitizers () const
Return sanitizers which are enabled by default.
virtual bool canSplitThinLTOUnit () const
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
virtual llvm::DenormalMode getDefaultDenormalModeForType (const llvm::opt::ArgList &DriverArgs, const JobAction &JA, const llvm::fltSemantics *FPType=nullptr) const
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
Static Public Member Functions
static ParsedClangName getTargetAndModeFromProgramName (StringRef ProgName)
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
static bool needsProfileRT (const llvm::opt::ArgList &Args)
needsProfileRT - returns true if instrumentation profile is on.
static bool needsGCovInstrumentation (const llvm::opt::ArgList &Args)
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
static llvm::Triple getOpenMPTriple (StringRef TripleStr)
Protected Member Functions
ToolChain (const Driver &D, const llvm::Triple &T, const llvm::opt::ArgList &Args)
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > executeToolChainProgram (StringRef Executable) const
Executes the given Executable and returns the stdout.
void setTripleEnvironment (llvm::Triple::EnvironmentType Env)
virtual Tool * buildAssembler () const
virtual Tool * buildLinker () const
virtual Tool * buildBackendCompiler () const
virtual Tool * buildStaticLibTool () const
virtual Tool * getTool (Action::ActionClass AC) const
virtual std::string buildCompilerRTBasename (const llvm::opt::ArgList &Args, StringRef Component, FileType Type, bool AddArch) const
std::optional< std::string > getTargetSubDirPath (StringRef BaseDir) const
Find the target-specific subdirectory for the current target triple under BaseDir, doing fallback triple searches as necessary.
Static Protected Member Functions
Utilities for implementing subclasses.
static void addSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory to CC1 arguments.
static void addExternCSystemInclude (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
static void addExternCSystemIncludeIfExists (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, const Twine &Path)
static void addSystemIncludes (const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, ArrayRef< StringRef > Paths)
Utility function to add a list of system include directories to CC1.
static std::string concat (StringRef Path, const Twine &A, const Twine &B="", const Twine &C="", const Twine &D="")
Protected Attributes
MultilibSet Multilibs
llvm::SmallVector< Multilib > SelectedMultilibs
Friends
class RegisterEffectiveTriple
Detailed Description
ToolChain - Access to tools for a single platform.
Definition at line 92 of file ToolChain.h.
Member Typedef Documentation
path_list
using clang::driver::ToolChain::path_list = SmallVector<std::string, 16>
Definition at line 94 of file ToolChain.h.
Member Enumeration Documentation
CXXStdlibType
enum clang::driver::ToolChain::CXXStdlibType
Enumerator
CST_Libcxx
CST_Libstdcxx
Definition at line 96 of file ToolChain.h.
ExceptionsMode
enum clang::driver::ToolChain::ExceptionsMode
Enumerator
EM_Enabled
EM_Disabled
Definition at line 123 of file ToolChain.h.
FileType
enum clang::driver::ToolChain::FileType
Enumerator
FT_Object
FT_Static
FT_Shared
Definition at line 135 of file ToolChain.h.
RTTIMode
enum clang::driver::ToolChain::RTTIMode
Enumerator
RM_Enabled
RM_Disabled
Definition at line 118 of file ToolChain.h.
RuntimeLibType
enum clang::driver::ToolChain::RuntimeLibType
Enumerator
RLT_CompilerRT
RLT_Libgcc
Definition at line 101 of file ToolChain.h.
UnwindLibType
enum clang::driver::ToolChain::UnwindLibType
Enumerator
UNW_None
UNW_CompilerRT
UNW_Libgcc
Definition at line 106 of file ToolChain.h.
UnwindTableLevel
enum clang::driver::ToolChain::UnwindTableLevel strong
Enumerator
None
Synchronous
Asynchronous
Definition at line 112 of file ToolChain.h.
Constructor & Destructor Documentation
ToolChain()
ToolChain::ToolChain (const Driver & D, const llvm::Triple & T, const llvm::opt::ArgList & Args) protected
Definition at line 89 of file ToolChain.cpp.
~ToolChain()
ToolChain::~ToolChain () virtual default
Member Function Documentation
AddCCKextLibArgs()
void ToolChain::AddCCKextLibArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const virtual
AddCCKextLibArgs - Add the system specific linker arguments to use for kernel extensions (Darwin-specific).
Reimplemented in clang::driver::toolchains::DarwinClang.
Definition at line 1381 of file ToolChain.cpp.
addClangCC1ASTargetOptions()
void ToolChain::addClangCC1ASTargetOptions (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CC1ASArgs) const virtual
Add options that need to be passed to cc1as for this target.
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 1146 of file ToolChain.cpp.
Referenced by clang::driver::tools::ClangAs::ConstructJob().
AddClangCXXStdlibIncludeArgs()
void ToolChain::AddClangCXXStdlibIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const virtual
AddClangCXXStdlibIncludeArgs - Add the clang -cc1 level arguments to set the include paths to use for the given C++ standard library type.
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::OHOS, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Generic_GCC, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::DarwinClang, clang::driver::toolchains::CrossWindowsToolChain, clang::driver::toolchains::BareMetal, clang::driver::toolchains::AIX, clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, and clang::driver::toolchains::CudaToolChain.
Definition at line 1317 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::CudaToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::HIPAMDToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::HIPSPVToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::SYCLToolChain::AddClangCXXStdlibIncludeArgs(), and clang::driver::toolchains::DarwinClang::AddClangCXXStdlibIncludeArgs().
AddClangCXXStdlibIsystemArgs()
void ToolChain::AddClangCXXStdlibIsystemArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const
AddClangCXXStdlibIsystemArgs - Add the clang -cc1 level arguments to set the specified include paths for the C++ standard library.
Definition at line 1331 of file ToolChain.cpp.
References addSystemInclude(), and P.
AddClangSystemIncludeArgs()
void ToolChain::AddClangSystemIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const virtual
Add the clang cc1 arguments for system include paths.
This routine is responsible for adding the necessary cc1 arguments to include headers from standard system header directories.
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::Solaris, clang::driver::toolchains::RISCVToolChain, clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::PPCLinuxToolChain, clang::driver::toolchains::PPCFreeBSDToolChain, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::NetBSD, clang::driver::toolchains::NaClToolChain, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MSP430ToolChain, clang::driver::toolchains::MipsLLVMToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::Hurd, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::HexagonToolChain, clang::driver::toolchains::Haiku, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::DragonFly, clang::driver::toolchains::DarwinClang, clang::driver::toolchains::CudaToolChain, clang::driver::toolchains::CSKYToolChain, clang::driver::toolchains::CrossWindowsToolChain, clang::driver::toolchains::BareMetal, clang::driver::toolchains::AVRToolChain, clang::driver::toolchains::AMDGPUOpenMPToolChain, and clang::driver::toolchains::AIX.
Definition at line 1137 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::AMDGPUOpenMPToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::CudaToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::HIPAMDToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::HIPSPVToolChain::AddClangSystemIncludeArgs(), and clang::driver::toolchains::SYCLToolChain::AddClangSystemIncludeArgs().
addClangTargetOptions()
void ToolChain::addClangTargetOptions (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, Action::OffloadKind DeviceOffloadKind) const virtual
Add options that need to be passed to cc1 for this target.
Reimplemented in clang::driver::toolchains::RISCVToolChain, clang::driver::toolchains::MSP430ToolChain, clang::driver::toolchains::CSKYToolChain, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::NetBSD, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::HexagonToolChain, clang::driver::toolchains::Generic_ELF, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::Darwin, clang::driver::toolchains::CudaToolChain, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::BareMetal, clang::driver::toolchains::AVRToolChain, clang::driver::toolchains::AMDGPUOpenMPToolChain, clang::driver::toolchains::ROCMToolChain, clang::driver::toolchains::AMDGPUToolChain, clang::driver::toolchains::ZOS, clang::driver::toolchains::PS4PS5Base, and clang::driver::toolchains::AIX.
Definition at line 1142 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::AMDGPUOpenMPToolChain::addClangTargetOptions(), clang::driver::toolchains::CudaToolChain::addClangTargetOptions(), clang::driver::toolchains::HIPAMDToolChain::addClangTargetOptions(), clang::driver::toolchains::HIPSPVToolChain::addClangTargetOptions(), clang::driver::toolchains::SYCLToolChain::addClangTargetOptions(), and clang::driver::tools::Clang::ConstructJob().
addClangWarningOptions()
void ToolChain::addClangWarningOptions (llvm::opt::ArgStringList & CC1Args) const virtual
Add warning options that need to be passed to cc1 for this target.
Reimplemented in clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::DarwinClang, clang::driver::toolchains::CudaToolChain, clang::driver::toolchains::AMDGPUOpenMPToolChain, and clang::driver::toolchains::AMDGPUToolChain.
Definition at line 1149 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::AMDGPUOpenMPToolChain::addClangWarningOptions(), clang::driver::toolchains::CudaToolChain::addClangWarningOptions(), clang::driver::toolchains::HIPAMDToolChain::addClangWarningOptions(), clang::driver::toolchains::HIPSPVToolChain::addClangWarningOptions(), clang::driver::toolchains::SYCLToolChain::addClangWarningOptions(), and clang::driver::tools::Clang::ConstructJob().
AddCudaIncludeArgs()
void ToolChain::AddCudaIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const virtual
Add arguments to use system-specific CUDA includes.
Reimplemented in clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::Darwin, and clang::driver::toolchains::CudaToolChain.
Definition at line 1447 of file ToolChain.cpp.
AddCXXStdlibLibArgs()
void ToolChain::AddCXXStdlibLibArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const virtual
AddCXXStdlibLibArgs - Add the system specific linker arguments to use for the given C++ standard library type.
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::NaClToolChain, clang::driver::toolchains::MipsLLVMToolChain, clang::driver::toolchains::HexagonToolChain, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::DarwinClang, clang::driver::toolchains::CrossWindowsToolChain, clang::driver::toolchains::BareMetal, and clang::driver::toolchains::AIX.
Definition at line 1355 of file ToolChain.cpp.
References CST_Libcxx, CST_Libstdcxx, and GetCXXStdlibType().
Referenced by clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), and clang::driver::tools::zos::Linker::ConstructJob().
addExternCSystemInclude()
void ToolChain::addExternCSystemInclude (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, const Twine & Path) static protected
Utility function to add a system include directory with extern "C" semantics to CC1 arguments.
Note that this should be used rarely, and only for directories that historically and for legacy reasons are treated as having implicit extern "C" semantics. These semantics are ignored by and large today, but its important to preserve the preprocessor changes resulting from the classification.
Definition at line 1262 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::CrossWindowsToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::DarwinClang::AddClangSystemIncludeArgs(), clang::driver::toolchains::DragonFly::AddClangSystemIncludeArgs(), clang::driver::toolchains::FreeBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangSystemIncludeArgs(), clang::driver::toolchains::Haiku::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Hurd::AddClangSystemIncludeArgs(), clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), clang::driver::toolchains::NetBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::OHOS::AddClangSystemIncludeArgs(), clang::driver::toolchains::OpenBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::Solaris::AddClangSystemIncludeArgs(), and addExternCSystemIncludeIfExists().
addExternCSystemIncludeIfExists()
void ToolChain::addExternCSystemIncludeIfExists (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, const Twine & Path) static protected
Definition at line 1269 of file ToolChain.cpp.
References addExternCSystemInclude().
addFastMathRuntimeIfAvailable()
bool ToolChain::addFastMathRuntimeIfAvailable (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const
AddFastMathRuntimeIfAvailable - If a runtime library exists that sets global flags for unsafe floating point math, add it and return true.
This checks for presence of the -Ofast, -ffast-math or -funsafe-math flags.
Definition at line 1406 of file ToolChain.cpp.
References isFastMathRuntimeAvailable().
Referenced by clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
AddFilePathLibArgs()
void ToolChain::AddFilePathLibArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const
AddFilePathLibArgs - Add each thing in getFilePaths() as a "-L" option.
Definition at line 1374 of file ToolChain.cpp.
References getFilePaths().
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), and clang::driver::tools::zos::Linker::ConstructJob().
AddHIPIncludeArgs()
void ToolChain::AddHIPIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const virtual
Add arguments to use system-specific HIP includes.
Reimplemented in clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::FreeBSD, and clang::driver::toolchains::Darwin.
Definition at line 1450 of file ToolChain.cpp.
AddHIPRuntimeLibArgs()
virtual void clang::driver::ToolChain::AddHIPRuntimeLibArgs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const inline virtual
Add the system specific linker arguments to use for the given HIP runtime library type.
Reimplemented in clang::driver::toolchains::MSVCToolChain, and clang::driver::toolchains::Linux.
Definition at line 796 of file ToolChain.h.
Referenced by clang::driver::tools::addHIPRuntimeLibArgs().
AddIAMCUIncludeArgs()
void ToolChain::AddIAMCUIncludeArgs (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args) const virtual
Add arguments to use MCU GCC toolchain includes.
Reimplemented in clang::driver::toolchains::Linux, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::CudaToolChain, and clang::driver::toolchains::AMDGPUOpenMPToolChain.
Definition at line 1460 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::AMDGPUOpenMPToolChain::AddIAMCUIncludeArgs(), clang::driver::toolchains::CudaToolChain::AddIAMCUIncludeArgs(), clang::driver::toolchains::HIPAMDToolChain::AddIAMCUIncludeArgs(), and clang::driver::toolchains::HIPSPVToolChain::AddIAMCUIncludeArgs().
addProfileRTLibs()
void ToolChain::addProfileRTLibs (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) const virtual
addProfileRTLibs - When -fprofile-instr-profile is specified, try to pass a suitable profile runtime library to the linker.
Reimplemented in clang::driver::toolchains::OHOS, clang::driver::toolchains::Linux, clang::driver::toolchains::Darwin, clang::driver::toolchains::MachO, and clang::driver::toolchains::AIX.
Definition at line 1151 of file ToolChain.cpp.
References getCompilerRTArgString(), needsGCovInstrumentation(), and needsProfileRT().
Referenced by clang::driver::toolchains::AIX::addProfileRTLibs(), clang::driver::toolchains::Linux::addProfileRTLibs(), clang::driver::toolchains::OHOS::addProfileRTLibs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
addSystemInclude()
void ToolChain::addSystemInclude (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, const Twine & Path) static protected
Utility function to add a system include directory to CC1 arguments.
Definition at line 1247 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::AIX::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::BareMetal::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::DarwinClang::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::OHOS::AddClangCXXStdlibIncludeArgs(), AddClangCXXStdlibIsystemArgs(), clang::driver::toolchains::AIX::AddClangSystemIncludeArgs(), clang::driver::toolchains::AVRToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::BareMetal::AddClangSystemIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::CSKYToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::DarwinClang::AddClangSystemIncludeArgs(), clang::driver::toolchains::DragonFly::AddClangSystemIncludeArgs(), clang::driver::toolchains::FreeBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangSystemIncludeArgs(), clang::driver::toolchains::Haiku::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Hurd::AddClangSystemIncludeArgs(), clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), clang::driver::toolchains::MipsLLVMToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::MSP430ToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::NaClToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::NetBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::OHOS::AddClangSystemIncludeArgs(), clang::driver::toolchains::OpenBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::PPCLinuxToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::RISCVToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Solaris::AddClangSystemIncludeArgs(), clang::driver::toolchains::VEToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::ZOS::AddClangSystemIncludeArgs(), clang::driver::toolchains::Generic_GCC::addLibCxxIncludePaths(), clang::driver::toolchains::FreeBSD::addLibCxxIncludePaths(), clang::driver::toolchains::Haiku::addLibCxxIncludePaths(), clang::driver::toolchains::NaClToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::NetBSD::addLibCxxIncludePaths(), clang::driver::toolchains::OpenBSD::addLibCxxIncludePaths(), clang::driver::toolchains::Generic_GCC::addLibStdCXXIncludePaths(), clang::driver::toolchains::Generic_GCC::AddMultilibIncludeArgs(), clang::driver::toolchains::MSVCToolChain::AddSystemIncludeWithSubfolder(), and clang::driver::toolchains::ZOS::TryAddIncludeFromPath().
addSystemIncludes()
void ToolChain::addSystemIncludes (const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, ArrayRef< StringRef > Paths) static protected
Utility function to add a list of system include directories to CC1.
Definition at line 1277 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::VEToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::XCoreToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::VEToolChain::AddClangSystemIncludeArgs(), and clang::driver::toolchains::XCoreToolChain::AddClangSystemIncludeArgs().
adjustDebugInfoKind()
virtual void clang::driver::ToolChain::adjustDebugInfoKind (llvm::codegenoptions::DebugInfoKind & DebugInfoKind, const llvm::opt::ArgList & Args) const inline virtual
Adjust debug information kind considering all passed options.
Reimplemented in clang::driver::toolchains::HIPSPVToolChain, and clang::driver::toolchains::NVPTXToolChain.
Definition at line 627 of file ToolChain.h.
Referenced by renderDebugOptions().
buildAssembler()
Tool * ToolChain::buildAssembler () const protected virtual
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::Solaris, clang::driver::toolchains::PS5CPU, clang::driver::toolchains::PS4CPU, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::NetBSD, clang::driver::toolchains::NaClToolChain, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::Hurd, clang::driver::toolchains::HexagonToolChain, clang::driver::toolchains::Generic_GCC, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::DragonFly, clang::driver::toolchains::MachO, clang::driver::toolchains::CudaToolChain, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::CrossWindowsToolChain, and clang::driver::toolchains::AIX.
Definition at line 469 of file ToolChain.cpp.
buildBackendCompiler()
Tool * ToolChain::buildBackendCompiler () const protected virtual
Reimplemented in clang::driver::toolchains::SYCLToolChain.
Definition at line 477 of file ToolChain.cpp.
buildCompilerRTBasename()
std::string ToolChain::buildCompilerRTBasename (const llvm::opt::ArgList & Args, StringRef Component, FileType Type, bool AddArch) const protected virtual
Definition at line 717 of file ToolChain.cpp.
References Env, FT_Object, FT_Shared, FT_Static, getArchNameForCompilerRTLib(), and getTriple().
Referenced by getCompilerRT(), and clang::driver::toolchains::OpenBSD::getCompilerRT().
buildLinker()
Tool * ToolChain::buildLinker () const protected virtual
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::Solaris, clang::driver::toolchains::RISCVToolChain, clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::NetBSD, clang::driver::toolchains::NaClToolChain, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MSP430ToolChain, clang::driver::toolchains::MipsLLVMToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::Hurd, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::HexagonToolChain, clang::driver::toolchains::Haiku, clang::driver::toolchains::Generic_GCC, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::DragonFly, clang::driver::toolchains::MachO, clang::driver::toolchains::CudaToolChain, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::CSKYToolChain, clang::driver::toolchains::CrossWindowsToolChain, clang::driver::toolchains::BareMetal, clang::driver::toolchains::AVRToolChain, clang::driver::toolchains::AMDGPUOpenMPToolChain, clang::driver::toolchains::AMDGPUToolChain, and clang::driver::toolchains::AIX.
Definition at line 473 of file ToolChain.cpp.
buildStaticLibTool()
Tool * ToolChain::buildStaticLibTool () const protected virtual
Reimplemented in clang::driver::toolchains::Linux, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::MachO, and clang::driver::toolchains::BareMetal.
Definition at line 481 of file ToolChain.cpp.
canSplitThinLTOUnit()
virtual bool clang::driver::ToolChain::canSplitThinLTOUnit () const inline virtual
Returns true when it's possible to split LTO unit to use whole program devirtualization and CFI santiizers.
Reimplemented in clang::driver::toolchains::PS4CPU, and clang::driver::toolchains::MachO.
Definition at line 809 of file ToolChain.h.
CheckObjCARC()
virtual void clang::driver::ToolChain::CheckObjCARC () const inline virtual
Complain if this tool chain doesn't support Objective-C ARC.
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 586 of file ToolChain.h.
Referenced by RenderObjCOptions().
ComputeEffectiveClangTriple()
std::string ToolChain::ComputeEffectiveClangTriple (const llvm::opt::ArgList & Args, types::ID InputType = types::TY_INVALID) const virtual
ComputeEffectiveClangTriple - Return the Clang triple to use for this target, which may take into account the command line arguments.
For example, on Darwin the -mmacosx-version-min= command line argument (which sets the deployment target) determines the version in the triple passed to Clang.
Reimplemented in clang::driver::toolchains::NaClToolChain, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::Fuchsia, and clang::driver::toolchains::Darwin.
Definition at line 1128 of file ToolChain.cpp.
References ComputeLLVMTriple().
Referenced by clang::driver::toolchains::MSVCToolChain::ComputeEffectiveClangTriple(), getMultilibFlags(), and clang::driver::Driver::HandleImmediateArgs().
ComputeLLVMTriple()
std::string ToolChain::ComputeLLVMTriple (const llvm::opt::ArgList & Args, types::ID InputType = types::TY_INVALID) const virtual
ComputeLLVMTriple - Return the LLVM target triple to use, after taking command line arguments into account.
Definition at line 1080 of file ToolChain.cpp.
References getArch(), getDriver(), getTriple(), getTripleString(), clang::driver::tools::arm::setArchNameInTriple(), and clang::driver::tools::arm::setFloatABIInTriple().
Referenced by clang::driver::toolchains::Darwin::ComputeEffectiveClangTriple(), clang::driver::toolchains::Fuchsia::ComputeEffectiveClangTriple(), clang::driver::toolchains::NaClToolChain::ComputeEffectiveClangTriple(), ComputeEffectiveClangTriple(), and clang::driver::toolchains::Darwin::GetExceptionModel().
computeMSVCVersion()
VersionTuple ToolChain::computeMSVCVersion (const Driver * D, const llvm::opt::ArgList & Args) const virtual
On Windows, returns the MSVC compatibility version.
Reimplemented in clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::CudaToolChain, and clang::driver::toolchains::AMDGPUOpenMPToolChain.
Definition at line 1477 of file ToolChain.cpp.
References clang::driver::Driver::Diag(), and separateMSVCFullVersion().
Referenced by addVSDefines(), clang::driver::toolchains::AMDGPUOpenMPToolChain::computeMSVCVersion(), clang::driver::toolchains::CudaToolChain::computeMSVCVersion(), clang::driver::toolchains::HIPAMDToolChain::computeMSVCVersion(), clang::driver::toolchains::HIPSPVToolChain::computeMSVCVersion(), and clang::driver::toolchains::MSVCToolChain::computeMSVCVersion().
computeSysRoot()
std::string ToolChain::computeSysRoot () const virtual
Return the sysroot, possibly searching for a default sysroot using target-specific logic.
Reimplemented in clang::driver::toolchains::OHOS, clang::driver::toolchains::MipsLLVMToolChain, clang::driver::toolchains::Linux, and clang::driver::toolchains::BareMetal.
Definition at line 1133 of file ToolChain.cpp.
References clang::driver::Driver::SysRoot.
Referenced by clang::driver::toolchains::Hurd::AddClangSystemIncludeArgs(), clang::driver::toolchains::Generic_GCC::addLibCxxIncludePaths(), and clang::driver::toolchains::Hurd::Hurd().
concat()
std::string ToolChain::concat (StringRef Path, const Twine & A, const Twine & B = "", const Twine & C = "", const Twine & D = "") static protected
Definition at line 1286 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::DragonFly::AddClangSystemIncludeArgs(), clang::driver::toolchains::FreeBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::Haiku::AddClangSystemIncludeArgs(), clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), clang::driver::toolchains::NetBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::OpenBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::FreeBSD::addLibCxxIncludePaths(), clang::driver::toolchains::Haiku::addLibCxxIncludePaths(), clang::driver::toolchains::NetBSD::addLibCxxIncludePaths(), clang::driver::toolchains::OpenBSD::addLibCxxIncludePaths(), clang::driver::toolchains::DragonFly::addLibStdCxxIncludePaths(), clang::driver::toolchains::NetBSD::addLibStdCxxIncludePaths(), clang::driver::toolchains::DragonFly::DragonFly(), clang::driver::toolchains::FreeBSD::FreeBSD(), clang::driver::toolchains::Haiku::Haiku(), clang::driver::toolchains::NetBSD::NetBSD(), and clang::driver::toolchains::OpenBSD::OpenBSD().
defaultToIEEELongDouble()
bool ToolChain::defaultToIEEELongDouble () const
Check whether use IEEE binary128 as long double format by default.
Definition at line 184 of file ToolChain.cpp.
References getTriple().
detectLibcxxVersion()
std::string ToolChain::detectLibcxxVersion (StringRef IncludePath) const virtual
Definition at line 1294 of file ToolChain.cpp.
References getVFS(), and clang::interp::LE().
Referenced by clang::driver::toolchains::Fuchsia::AddClangCXXStdlibIncludeArgs(), and clang::driver::toolchains::Generic_GCC::addLibCxxIncludePaths().
executeToolChainProgram()
llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > ToolChain::executeToolChainProgram (StringRef Executable) const protected
Executes the given Executable and returns the stdout.
Definition at line 108 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::AMDGPUToolChain::getSystemGPUArchs().
getArch()
llvm::Triple::ArchType clang::driver::ToolChain::getArch () const inline
Definition at line 285 of file ToolChain.h.
Referenced by clang::driver::toolchains::NaClToolChain::AddClangSystemIncludeArgs(), addDefaultCRTLinkArgs(), clang::driver::toolchains::OHOS::addExtraOpts(), clang::driver::toolchains::NaClToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), clang::driver::toolchains::NaClToolChain::buildAssembler(), clang::driver::toolchains::HIPAMDToolChain::buildLinker(), clang::driver::toolchains::HIPSPVToolChain::buildLinker(), ComputeLLVMTriple(), clang::driver::tools::baremetal::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::dragonfly::Assembler::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), getArchNameForCompilerRTLib(), clang::driver::toolchains::NetBSD::GetDefaultCXXStdlibType(), clang::driver::toolchains::Linux::getDefaultDenormalModeForType(), clang::driver::toolchains::Fuchsia::getDefaultSanitizers(), clang::driver::toolchains::CrossWindowsToolChain::getDefaultUnwindTableLevel(), clang::driver::toolchains::MachO::getDefaultUnwindTableLevel(), clang::driver::toolchains::Generic_GCC::getDefaultUnwindTableLevel(), clang::driver::toolchains::MSVCToolChain::getDefaultUnwindTableLevel(), clang::driver::toolchains::OpenBSD::getDefaultUnwindTableLevel(), clang::driver::toolchains::Hurd::getDynamicLinker(), clang::driver::toolchains::Linux::getDynamicLinker(), clang::driver::toolchains::OHOS::getDynamicLinker(), clang::driver::toolchains::Darwin::GetExceptionModel(), clang::driver::toolchains::MachO::getMachOArchName(), clang::driver::toolchains::MSVCToolChain::getSubDirectoryPath(), clang::driver::toolchains::Linux::getSupportedSanitizers(), getTargetSubDirPath(), clang::driver::toolchains::MSVCToolChain::getUniversalCRTLibraryPath(), clang::driver::toolchains::MSVCToolChain::getWindowsSDKLibraryPath(), isCrossCompiling(), clang::driver::toolchains::Generic_GCC::IsIntegratedAssemblerDefault(), clang::driver::toolchains::CrossWindowsToolChain::isPICDefault(), clang::driver::toolchains::Generic_GCC::isPICDefault(), clang::driver::toolchains::MSVCToolChain::isPICDefault(), clang::driver::toolchains::CrossWindowsToolChain::isPICDefaultForced(), clang::driver::toolchains::MachO::isPICDefaultForced(), clang::driver::toolchains::Generic_GCC::isPICDefaultForced(), clang::driver::toolchains::MSVCToolChain::isPICDefaultForced(), clang::driver::toolchains::CrossWindowsToolChain::isPIEDefault(), RenderBuiltinOptions(), RenderFloatingPointOptions(), RenderObjCOptions(), clang::driver::toolchains::AMDGPUToolChain::TranslateArgs(), clang::driver::toolchains::AMDGPUOpenMPToolChain::TranslateArgs(), clang::driver::toolchains::CudaToolChain::TranslateArgs(), clang::driver::toolchains::MSVCToolChain::TranslateArgs(), TranslateOffloadTargetArgs(), and clang::driver::toolchains::MSVCToolChain::useUniversalCRT().
getArchName()
StringRef clang::driver::ToolChain::getArchName () const inline
Definition at line 286 of file ToolChain.h.
Referenced by clang::driver::toolchains::Darwin::addPlatformVersionArgs(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), and clang::driver::toolchains::MachO::TranslateArgs().
getArchSpecificLibPaths()
ToolChain::path_list ToolChain::getArchSpecificLibPaths () const virtual
Reimplemented in clang::driver::toolchains::OHOS.
Definition at line 892 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::VEToolChain::VEToolChain().
getAuxTriple()
virtual const llvm::Triple* clang::driver::ToolChain::getAuxTriple () const inline virtual
Get the toolchain's aux triple, if it has one.
Exactly what the aux triple represents depends on the toolchain, but for example when compiling CUDA code for the GPU, the triple might be NVPTX, while the aux triple is the host (CPU) toolchain, e.g. x86-linux-gnu.
Reimplemented in clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::CudaToolChain, and clang::driver::toolchains::AMDGPUOpenMPToolChain.
Definition at line 278 of file ToolChain.h.
Referenced by clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), and clang::driver::isSYCLNativeCPU().
getCompilerRT()
std::string ToolChain::getCompilerRT (const llvm::opt::ArgList & Args, StringRef Component, FileType Type = ToolChain::FT_Static) const virtual
Reimplemented in clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::MipsLLVMToolChain, and clang::driver::toolchains::AVRToolChain.
Definition at line 751 of file ToolChain.cpp.
References buildCompilerRTBasename(), getCompilerRTPath(), getLibraryPaths(), getTriple(), getVFS(), and P.
Referenced by addSanitizerDynamicList(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::toolchains::OpenBSD::getCompilerRT(), getCompilerRTArgString(), getCompilerRTBasename(), and clang::driver::Driver::HandleImmediateArgs().
getCompilerRTArgString()
const char * ToolChain::getCompilerRTArgString (const llvm::opt::ArgList & Args, StringRef Component, FileType Type = ToolChain::FT_Static) const
Definition at line 782 of file ToolChain.cpp.
References getCompilerRT().
Referenced by clang::driver::toolchains::BareMetal::AddLinkRuntimeLib(), addProfileRTLibs(), addSanitizerRuntime(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::RISCV::Linker::ConstructJob().
getCompilerRTBasename()
std::string ToolChain::getCompilerRTBasename (const llvm::opt::ArgList & Args, StringRef Component, FileType Type = ToolChain::FT_Static) const
Definition at line 710 of file ToolChain.cpp.
References getCompilerRT().
Referenced by clang::driver::SanitizerArgs::addArgs(), addPGOAndCoverageFlags(), and processVSRuntimeLibrary().
getCompilerRTPath()
std::string ToolChain::getCompilerRTPath () const virtual
Reimplemented in clang::driver::toolchains::HexagonToolChain.
Definition at line 695 of file ToolChain.cpp.
References getDriver(), getOSLibName(), isBareMetal(), and SelectedMultilibs.
Referenced by clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::toolchains::AVRToolChain::getCompilerRT(), getCompilerRT(), clang::driver::Driver::GetFilePath(), and clang::driver::Driver::HandleImmediateArgs().
GetCXXStdlibType()
ToolChain::CXXStdlibType ToolChain::GetCXXStdlibType (const llvm::opt::ArgList & Args) const virtual
Reimplemented in clang::driver::toolchains::VEToolChain, clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::OHOS, clang::driver::toolchains::NaClToolChain, clang::driver::toolchains::MipsLLVMToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::HexagonToolChain, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::CudaToolChain, and clang::driver::toolchains::AMDGPUOpenMPToolChain.
Definition at line 1221 of file ToolChain.cpp.
References CST_Libcxx, CST_Libstdcxx, clang::driver::Driver::Diag(), GetDefaultCXXStdlibType(), and getDriver().
Referenced by clang::driver::toolchains::AIX::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::BareMetal::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::DarwinClang::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::Generic_GCC::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::ZOS::AddClangCXXStdlibIncludeArgs(), AddCXXStdlibLibArgs(), clang::driver::toolchains::AIX::AddCXXStdlibLibArgs(), clang::driver::toolchains::BareMetal::AddCXXStdlibLibArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddCXXStdlibLibArgs(), clang::driver::toolchains::DarwinClang::AddCXXStdlibLibArgs(), clang::driver::toolchains::ZOS::AddCXXStdlibLibArgs(), clang::driver::toolchains::AMDGPUOpenMPToolChain::GetCXXStdlibType(), clang::driver::toolchains::CudaToolChain::GetCXXStdlibType(), clang::driver::toolchains::HIPAMDToolChain::GetCXXStdlibType(), clang::driver::toolchains::HIPSPVToolChain::GetCXXStdlibType(), clang::driver::toolchains::SYCLToolChain::GetCXXStdlibType(), clang::driver::Driver::GetStdModuleManifestPath(), and RenderObjCOptions().
GetDefaultCXXStdlibType()
virtual CXXStdlibType clang::driver::ToolChain::GetDefaultCXXStdlibType () const inline virtual
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::NetBSD, clang::driver::toolchains::Linux, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::Darwin, clang::driver::toolchains::BareMetal, and clang::driver::toolchains::AIX.
Definition at line 519 of file ToolChain.h.
References CST_Libstdcxx.
Referenced by GetCXXStdlibType().
getDefaultDebugFormat()
virtual llvm::codegenoptions::DebugInfoFormat clang::driver::ToolChain::getDefaultDebugFormat () const inline virtual
Get the default debug info format. Typically, this is DWARF.
Reimplemented in clang::driver::toolchains::SYCLToolChain, and clang::driver::toolchains::MSVCToolChain.
Definition at line 589 of file ToolChain.h.
Referenced by clang::driver::toolchains::SYCLToolChain::getDefaultDebugFormat(), and renderDebugOptions().
getDefaultDebuggerTuning()
virtual llvm::DebuggerKind clang::driver::ToolChain::getDefaultDebuggerTuning () const inline virtual
Reimplemented in clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::DarwinClang, and clang::driver::toolchains::AIX.
Definition at line 616 of file ToolChain.h.
Referenced by renderDebugOptions().
getDefaultDenormalModeForType()
virtual llvm::DenormalMode clang::driver::ToolChain::getDefaultDenormalModeForType (const llvm::opt::ArgList & DriverArgs, const JobAction & JA, const llvm::fltSemantics * FPType = nullptr) const inline virtual
Returns the output denormal handling type in the default floating point environment for the given FPType if given.
Otherwise, the default assumed mode for any floating point type.
Reimplemented in clang::driver::toolchains::Linux, clang::driver::toolchains::CudaToolChain, clang::driver::toolchains::AMDGPUToolChain, and clang::driver::toolchains::PS4PS5Base.
Definition at line 814 of file ToolChain.h.
Referenced by RenderFloatingPointOptions().
GetDefaultDwarfVersion()
virtual unsigned clang::driver::ToolChain::GetDefaultDwarfVersion () const inline virtual
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::PS5CPU, clang::driver::toolchains::PS4CPU, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::Haiku, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::DarwinClang, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::AMDGPUToolChain, and clang::driver::toolchains::AIX.
Definition at line 602 of file ToolChain.h.
Referenced by clang::driver::toolchains::Linux::GetDefaultDwarfVersion(), and clang::driver::tools::getDwarfVersion().
getDefaultLinker()
virtual const char* clang::driver::ToolChain::getDefaultLinker () const inline virtual
GetDefaultLinker - Get the default linker to use.
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::Solaris, clang::driver::toolchains::OHOS, clang::driver::toolchains::MipsLLVMToolChain, clang::driver::toolchains::Linux, clang::driver::toolchains::HexagonToolChain, clang::driver::toolchains::Haiku, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::BareMetal, and clang::driver::toolchains::AMDGPUToolChain.
Definition at line 512 of file ToolChain.h.
Referenced by clang::driver::toolchains::Linux::getDefaultLinker(), GetLinkerPath(), clang::driver::tools::solaris::Linker::getLinkerPath(), and clang::driver::tools::wasm::Linker::getLinkerPath().
getDefaultObjCRuntime()
ObjCRuntime ToolChain::getDefaultObjCRuntime (bool isNonFragile) const virtual
getDefaultObjCRuntime - Return the default Objective-C runtime for this platform.
FIXME: this really belongs on some sort of DeploymentTarget abstraction
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 1057 of file ToolChain.cpp.
References clang::ObjCRuntime::GCC, and clang::ObjCRuntime::GNUstep.
GetDefaultRuntimeLibType()
virtual RuntimeLibType clang::driver::ToolChain::GetDefaultRuntimeLibType () const inline virtual
GetDefaultRuntimeLibType - Get the default runtime library variant to use.
Reimplemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::RISCVToolChain, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::MipsLLVMToolChain, clang::driver::toolchains::Linux, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::MachO, clang::driver::toolchains::CSKYToolChain, clang::driver::toolchains::BareMetal, and clang::driver::toolchains::AIX.
Definition at line 515 of file ToolChain.h.
References RLT_Libgcc.
Referenced by clang::driver::toolchains::Linux::GetDefaultRuntimeLibType(), and GetRuntimeLibType().
getDefaultSanitizers()
virtual SanitizerMask clang::driver::ToolChain::getDefaultSanitizers () const inline virtual
Return sanitizers which are enabled by default.
Reimplemented in clang::driver::toolchains::Fuchsia.
Definition at line 803 of file ToolChain.h.
GetDefaultStackProtectorLevel()
virtual LangOptions::StackProtectorMode clang::driver::ToolChain::GetDefaultStackProtectorLevel (bool KernelOrKext) const inline virtual
GetDefaultStackProtectorLevel - Get the default stack protector level for this tool chain.
Reimplemented in clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::Darwin, and clang::driver::toolchains::CrossWindowsToolChain.
Definition at line 501 of file ToolChain.h.
References clang::LangOptionsBase::SSPOff.
Referenced by RenderSSPOptions().
GetDefaultStandaloneDebug()
virtual bool clang::driver::ToolChain::GetDefaultStandaloneDebug () const inline virtual
Reimplemented in clang::driver::toolchains::Haiku, clang::driver::toolchains::FreeBSD, and clang::driver::toolchains::DarwinClang.
Definition at line 613 of file ToolChain.h.
Referenced by renderDebugOptions().
GetDefaultTrivialAutoVarInit()
virtual LangOptions::TrivialAutoVarInitKind clang::driver::ToolChain::GetDefaultTrivialAutoVarInit () const inline virtual
Get the default trivial automatic variable initialization.
Definition at line 507 of file ToolChain.h.
References clang::LangOptionsBase::Uninitialized.
Referenced by RenderTrivialAutoVarInitOptions().
getDefaultUniversalArchName()
StringRef ToolChain::getDefaultUniversalArchName () const
Provide the default architecture name (as expected by -arch) for this toolchain.
Definition at line 423 of file ToolChain.cpp.
References getTriple().
Referenced by clang::driver::Driver::BuildUniversalActions(), and clang::driver::toolchains::MachO::getMachOArchName().
GetDefaultUnwindLibType()
virtual UnwindLibType clang::driver::ToolChain::GetDefaultUnwindLibType () const inline virtual
Reimplemented in clang::driver::toolchains::OHOS.
Definition at line 523 of file ToolChain.h.
References UNW_None.
Referenced by GetUnwindLibType().
getDefaultUnwindTableLevel()
ToolChain::UnwindTableLevel ToolChain::getDefaultUnwindTableLevel (const llvm::opt::ArgList & Args) const virtual
How detailed should the unwind tables be by default.
Reimplemented in clang::driver::toolchains::RISCVToolChain, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::NetBSD, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Generic_GCC, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::MachO, and clang::driver::toolchains::CrossWindowsToolChain.
Definition at line 453 of file ToolChain.cpp.
References None.
getDeviceLibs()
llvm::SmallVector< ToolChain::BitCodeLibraryInfo, 12 > ToolChain::getDeviceLibs (const llvm::opt::ArgList & Args, const Action::OffloadKind DeviceOffloadingKind) const virtual
Get paths for device libraries.
Reimplemented in clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, and clang::driver::toolchains::AMDGPUOpenMPToolChain.
Definition at line 1454 of file ToolChain.cpp.
getDriver()
const Driver& clang::driver::ToolChain::getDriver () const inline
Definition at line 269 of file ToolChain.h.
Referenced by clang::driver::SanitizerArgs::addArgs(), clang::driver::XRayArgs::addArgs(), clang::driver::toolchains::DarwinClang::AddCCKextLibArgs(), clang::driver::toolchains::BareMetal::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::DarwinClang::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::OHOS::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::ZOS::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::AIX::AddClangSystemIncludeArgs(), clang::driver::toolchains::BareMetal::AddClangSystemIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::CudaToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::DarwinClang::AddClangSystemIncludeArgs(), clang::driver::toolchains::DragonFly::AddClangSystemIncludeArgs(), clang::driver::toolchains::FreeBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangSystemIncludeArgs(), clang::driver::toolchains::Haiku::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Hurd::AddClangSystemIncludeArgs(), clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), clang::driver::toolchains::MipsLLVMToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::NaClToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::NetBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::OHOS::AddClangSystemIncludeArgs(), clang::driver::toolchains::OpenBSD::AddClangSystemIncludeArgs(), clang::driver::toolchains::PPCLinuxToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::RISCVToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Solaris::AddClangSystemIncludeArgs(), clang::driver::toolchains::VEToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::ZOS::AddClangSystemIncludeArgs(), clang::driver::toolchains::AIX::addClangTargetOptions(), clang::driver::toolchains::ROCMToolChain::addClangTargetOptions(), clang::driver::toolchains::AMDGPUOpenMPToolChain::addClangTargetOptions(), clang::driver::toolchains::CudaToolChain::addClangTargetOptions(), clang::driver::toolchains::HIPAMDToolChain::addClangTargetOptions(), addFortranMain(), clang::driver::toolchains::HIPSPVToolChain::AddHIPIncludeArgs(), clang::driver::toolchains::SYCLToolChain::AddImpliedTargetArgs(), clang::driver::toolchains::Generic_GCC::addLibCxxIncludePaths(), clang::driver::toolchains::FreeBSD::addLibCxxIncludePaths(), clang::driver::toolchains::Haiku::addLibCxxIncludePaths(), clang::driver::toolchains::HexagonToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::NaClToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::NetBSD::addLibCxxIncludePaths(), clang::driver::toolchains::OpenBSD::addLibCxxIncludePaths(), clang::driver::toolchains::DragonFly::addLibStdCxxIncludePaths(), clang::driver::toolchains::HexagonToolChain::addLibStdCxxIncludePaths(), clang::driver::toolchains::NetBSD::addLibStdCxxIncludePaths(), clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), clang::driver::tools::addLinkerCompressDebugSectionsOption(), clang::driver::toolchains::MachO::AddLinkRuntimeLib(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), addPGOAndCoverageFlags(), addPgProfilingLinkArgs(), clang::driver::tools::ClangAs::AddX86TargetArgs(), clang::driver::toolchains::AIX::AIX(), clang::driver::toolchains::AMDGPUOpenMPToolChain::AMDGPUOpenMPToolChain(), clang::driver::toolchains::BareMetal::BareMetal(), clang::driver::toolchains::MSVCToolChain::buildAssembler(), clang::driver::toolchains::Darwin::CheckObjCARC(), clang::driver::toolchains::AMDGPUToolChain::checkTargetID(), clang::driver::toolchains::HIPAMDToolChain::checkTargetID(), CollectARMPACBTIOptions(), ComputeLLVMTriple(), clang::driver::toolchains::BareMetal::computeSysRoot(), clang::driver::toolchains::Linux::computeSysRoot(), clang::driver::toolchains::MipsLLVMToolChain::computeSysRoot(), clang::driver::toolchains::OHOS::computeSysRoot(), constructHexagonLinkArgs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::tools::LinkerWrapper::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), clang::driver::tools::zos::Linker::ConstructJob(), clang::driver::toolchains::DragonFly::DragonFly(), clang::driver::CC1Command::Execute(), clang::driver::toolchains::AVRToolChain::findAVRLibcInstallation(), clang::driver::toolchains::FreeBSD::FreeBSD(), clang::driver::toolchains::Fuchsia::Fuchsia(), clang::driver::toolchains::Generic_GCC::Generic_GCC(), clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames(), clang::driver::toolchains::MipsLLVMToolChain::getCompilerRT(), clang::driver::toolchains::OHOS::getCompilerRT(), clang::driver::toolchains::OpenBSD::getCompilerRT(), getCompilerRTPath(), GetCXXStdlibType(), clang::driver::toolchains::Fuchsia::GetCXXStdlibType(), clang::driver::toolchains::HexagonToolChain::GetCXXStdlibType(), clang::driver::toolchains::MipsLLVMToolChain::GetCXXStdlibType(), clang::driver::toolchains::NaClToolChain::GetCXXStdlibType(), clang::driver::toolchains::OHOS::GetCXXStdlibType(), clang::driver::toolchains::AMDGPUOpenMPToolChain::getDeviceLibs(), clang::driver::toolchains::HIPAMDToolChain::getDeviceLibs(), clang::driver::toolchains::HIPSPVToolChain::getDeviceLibs(), clang::driver::tools::getDwarfVersion(), clang::driver::toolchains::Linux::getDynamicLinker(), clang::driver::toolchains::CudaToolChain::getInputFilename(), GetLinkerPath(), clang::driver::tools::solaris::Linker::getLinkerPath(), clang::driver::tools::wasm::Linker::getLinkerPath(), clang::driver::toolchains::MachO::getLinkerVersion(), GetRuntimeLibType(), clang::driver::toolchains::DarwinClang::GetRuntimeLibType(), clang::driver::toolchains::Fuchsia::GetRuntimeLibType(), clang::driver::toolchains::OHOS::GetRuntimeLibType(), getStaticPIE(), GetUnwindLibType(), getVFS(), clang::driver::toolchains::Haiku::Haiku(), clang::driver::toolchains::HIPAMDToolChain::HIPAMDToolChain(), clang::driver::toolchains::HIPSPVToolChain::HIPSPVToolChain(), clang::driver::tools::isTLSDESCEnabled(), clang::driver::toolchains::MachO::MachO(), clang::driver::toolchains::MinGW::MinGW(), clang::driver::toolchains::MSVCToolChain::MSVCToolChain(), clang::driver::toolchains::NaClToolChain::NaClToolChain(), clang::driver::toolchains::NetBSD::NetBSD(), clang::driver::toolchains::OpenBSD::OpenBSD(), ParseDebugDefaultVersion(), ProcessVSRuntimeLibrary(), clang::driver::toolchains::HLSLToolChain::requiresValidation(), clang::driver::SanitizerArgs::SanitizerArgs(), SelectTool(), SetRISCVSmallDataLimit(), ShouldLinkCXXStdlib(), shouldSkipSanitizeOption(), clang::driver::toolchains::SYCLToolChain::SYCLToolChain(), clang::driver::toolchains::TCEToolChain::TCEToolChain(), clang::driver::toolchains::AMDGPUToolChain::TranslateArgs(), clang::driver::toolchains::AMDGPUOpenMPToolChain::TranslateArgs(), clang::driver::toolchains::CudaToolChain::TranslateArgs(), clang::driver::toolchains::MachO::TranslateArgs(), clang::driver::toolchains::Darwin::TranslateArgs(), clang::driver::toolchains::Generic_GCC::TranslateArgs(), clang::driver::toolchains::HIPAMDToolChain::TranslateArgs(), clang::driver::toolchains::HLSLToolChain::TranslateArgs(), clang::driver::toolchains::MSVCToolChain::TranslateArgs(), clang::driver::toolchains::SYCLToolChain::TranslateArgs(), clang::driver::toolchains::SYCLToolChain::TranslateBackendTargetArgs(), clang::driver::toolchains::SYCLToolChain::TranslateLinkerTargetArgs(), TranslateOffloadTargetArgs(), clang::driver::toolchains::SYCLToolChain::TranslateTargetOpt(), TranslateXarchArgs(), and clang::driver::XRayArgs::XRayArgs().
getEffectiveTriple()
const llvm::Triple& clang::driver::ToolChain::getEffectiveTriple () const inline
Get the toolchain's effective clang triple.
Definition at line 299 of file ToolChain.h.
Referenced by clang::driver::toolchains::Darwin::addMinVersionArgs(), clang::driver::toolchains::Darwin::addPlatformVersionArgs(), CollectARMPACBTIOptions(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::isTLSDESCEnabled(), RenderSCPOptions(), and RenderSSPOptions().
GetExceptionModel()
llvm::ExceptionHandling ToolChain::GetExceptionModel (const llvm::opt::ArgList & Args) const virtual
GetExceptionModel - Return the tool chain exception model.
Reimplemented in clang::driver::toolchains::VEToolChain, clang::driver::toolchains::NetBSD, clang::driver::toolchains::MinGW, clang::driver::toolchains::Darwin, and clang::driver::toolchains::MachO.
Definition at line 1063 of file ToolChain.cpp.
References clang::XRayInstrKind::None.
getExceptionsMode()
ExceptionsMode clang::driver::ToolChain::getExceptionsMode () const inline
Definition at line 346 of file ToolChain.h.
Referenced by getMultilibFlags().
GetFilePath()
std::string ToolChain::GetFilePath (const char * Name) const
Definition at line 938 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::Darwin::addStartObjectFileArgs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), isFastMathRuntimeAvailable(), and clang::driver::toolchains::NaClToolChain::NaClToolChain().
getFilePaths() [1/2]
path_list& clang::driver::ToolChain::getFilePaths () inline
Definition at line 311 of file ToolChain.h.
Referenced by AddFilePathLibArgs(), clang::driver::tools::addOpenMPDeviceRTL(), clang::driver::toolchains::BareMetal::BareMetal(), constructHexagonLinkArgs(), clang::driver::toolchains::DragonFly::DragonFly(), clang::driver::toolchains::FreeBSD::FreeBSD(), clang::driver::toolchains::Fuchsia::Fuchsia(), clang::driver::Driver::GetFilePath(), clang::driver::toolchains::Haiku::Haiku(), clang::driver::Driver::HandleImmediateArgs(), clang::driver::toolchains::HexagonToolChain::HexagonToolChain(), clang::driver::toolchains::MinGW::MinGW(), clang::driver::toolchains::MipsLLVMToolChain::MipsLLVMToolChain(), clang::driver::toolchains::MSP430ToolChain::MSP430ToolChain(), clang::driver::toolchains::NaClToolChain::NaClToolChain(), clang::driver::toolchains::NetBSD::NetBSD(), clang::driver::toolchains::OHOS::OHOS(), clang::driver::toolchains::OpenBSD::OpenBSD(), clang::driver::toolchains::PS4PS5Base::PS4PS5Base(), and clang::driver::toolchains::VEToolChain::VEToolChain().
getFilePaths() [2/2]
const path_list& clang::driver::ToolChain::getFilePaths () const inline
Definition at line 312 of file ToolChain.h.
GetGlobalDebugPathRemapping()
virtual std::string clang::driver::ToolChain::GetGlobalDebugPathRemapping () const inline virtual
Add an additional -fdebug-prefix-map entry.
Reimplemented in clang::driver::toolchains::MachO.
Definition at line 598 of file ToolChain.h.
getInputFilename()
std::string ToolChain::getInputFilename (const InputInfo & Input) const virtual
Some toolchains need to modify the file name, for example to replace the extension for object files with .cubin for OpenMP offloading to Nvidia GPUs.
Reimplemented in clang::driver::toolchains::CudaToolChain.
Definition at line 448 of file ToolChain.cpp.
References clang::driver::InputInfo::getFilename().
Referenced by clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), and clang::driver::toolchains::CudaToolChain::getInputFilename().
getLibraryPaths() [1/2]
path_list& clang::driver::ToolChain::getLibraryPaths () inline
Definition at line 308 of file ToolChain.h.
Referenced by clang::driver::toolchains::AIX::AIX(), clang::driver::toolchains::BareMetal::BareMetal(), clang::driver::tools::MinGW::Linker::ConstructJob(), getCompilerRT(), clang::driver::Driver::GetFilePath(), and clang::driver::toolchains::OHOS::OHOS().
getLibraryPaths() [2/2]
const path_list& clang::driver::ToolChain::getLibraryPaths () const inline
Definition at line 309 of file ToolChain.h.
GetLinkerPath()
std::string ToolChain::GetLinkerPath (bool * LinkerIsLLD = nullptr) const
Returns the linker path, respecting the -fuse-ld= argument to determine the linker suffix or name.
If LinkerIsLLD is non-nullptr, it is set to true if the returned linker is LLD. If it's set, it can be assumed that the linker is LLD built at the same revision as clang, and clang can make assumptions about LLD's supported flags, error output, etc.
Definition at line 946 of file ToolChain.cpp.
References clang::driver::Driver::Diag(), getDefaultLinker(), getDriver(), and GetProgramPath().
Referenced by constructHexagonLinkArgs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::zos::Linker::ConstructJob().
getMaxDwarfVersion()
virtual unsigned clang::driver::ToolChain::getMaxDwarfVersion () const inline virtual
Reimplemented in clang::driver::toolchains::NVPTXToolChain.
Definition at line 607 of file ToolChain.h.
References UINT_MAX.
Referenced by renderDebugOptions().
getMultiarchTriple()
virtual std::string clang::driver::ToolChain::getMultiarchTriple (const Driver & D, const llvm::Triple & TargetTriple, StringRef SysRoot) const inline virtual
Reimplemented in clang::driver::toolchains::OHOS, clang::driver::toolchains::Linux, and clang::driver::toolchains::Hurd.
Definition at line 646 of file ToolChain.h.
getMultilibFlags()
Multilib::flags_list ToolChain::getMultilibFlags (const llvm::opt::ArgList & Args) const
Get flags suitable for multilib selection, based on the provided clang command line arguments.
The command line arguments aren't suitable to be used directly for multilib selection because they are not normalized and normalization is a complex process. The result of this function is similar to clang command line arguments except that the list of arguments is incomplete. Only certain command line arguments are processed. If more command line arguments are needed for multilib selection then this function should be extended. To allow users to find out what flags are returned, clang accepts a -print-multi-flags-experimental argument.
Definition at line 259 of file ToolChain.cpp.
References ComputeEffectiveClangTriple(), getAArch64MultilibFlags(), getARMMultilibFlags(), getExceptionsMode(), and getRTTIMode().
Referenced by clang::driver::Driver::HandleImmediateArgs().
getMultilibs()
const MultilibSet& clang::driver::ToolChain::getMultilibs () const inline
Definition at line 317 of file ToolChain.h.
References Multilibs.
Referenced by clang::driver::Driver::HandleImmediateArgs().
getOpenMPTriple()
static llvm::Triple clang::driver::ToolChain::getOpenMPTriple (StringRef TripleStr) inline static
Definition at line 822 of file ToolChain.h.
Referenced by clang::driver::tools::LinkerWrapper::ConstructJob(), clang::driver::Driver::CreateOffloadingDeviceToolChains(), and clang::driver::Driver::getOffloadArchs().
getOS()
StringRef clang::driver::ToolChain::getOS () const inline
Definition at line 288 of file ToolChain.h.
Referenced by clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), clang::driver::toolchains::MipsLLVMToolChain::getCompilerRT(), and getOSLibName().
getOSLibName()
StringRef ToolChain::getOSLibName () const virtual
Reimplemented in clang::driver::toolchains::BareMetal.
Definition at line 675 of file ToolChain.cpp.
References getOS().
Referenced by getCompilerRTPath().
getPlatform()
StringRef clang::driver::ToolChain::getPlatform () const inline
Definition at line 287 of file ToolChain.h.
GetProgramPath()
std::string ToolChain::GetProgramPath (const char * Name) const
Definition at line 942 of file ToolChain.cpp.
Referenced by clang::driver::tools::dragonfly::Assembler::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::ifstool::Merger::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::PScpu::Assembler::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::SPIRV::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), GetLinkerPath(), clang::driver::tools::wasm::Linker::getLinkerPath(), GetStaticLibToolPath(), clang::driver::toolchains::AMDGPUToolChain::getSystemGPUArchs(), and clang::driver::toolchains::HLSLToolChain::requiresValidation().
getProgramPaths() [1/2]
path_list& clang::driver::ToolChain::getProgramPaths () inline
Definition at line 314 of file ToolChain.h.
Referenced by clang::driver::toolchains::AIX::AIX(), clang::driver::toolchains::AMDGPUOpenMPToolChain::AMDGPUOpenMPToolChain(), clang::driver::toolchains::AVRToolChain::AVRToolChain(), clang::driver::toolchains::BareMetal::BareMetal(), clang::driver::toolchains::DragonFly::DragonFly(), clang::driver::toolchains::Fuchsia::Fuchsia(), clang::driver::toolchains::Generic_GCC::Generic_GCC(), clang::driver::Driver::HandleImmediateArgs(), clang::driver::toolchains::HexagonToolChain::HexagonToolChain(), clang::driver::toolchains::HIPAMDToolChain::HIPAMDToolChain(), clang::driver::toolchains::HIPSPVToolChain::HIPSPVToolChain(), clang::driver::toolchains::HLSLToolChain::HLSLToolChain(), clang::driver::toolchains::Hurd::Hurd(), clang::driver::toolchains::Linux::Linux(), clang::driver::toolchains::MachO::MachO(), clang::driver::toolchains::MinGW::MinGW(), clang::driver::toolchains::MSP430ToolChain::MSP430ToolChain(), clang::driver::toolchains::MSVCToolChain::MSVCToolChain(), clang::driver::toolchains::NaClToolChain::NaClToolChain(), clang::driver::toolchains::SYCLToolChain::SYCLToolChain(), clang::driver::toolchains::TCEToolChain::TCEToolChain(), and clang::driver::toolchains::VEToolChain::VEToolChain().
getProgramPaths() [2/2]
const path_list& clang::driver::ToolChain::getProgramPaths () const inline
Definition at line 315 of file ToolChain.h.
getRTTIArg()
const llvm::opt::Arg* clang::driver::ToolChain::getRTTIArg () const inline
Definition at line 340 of file ToolChain.h.
Referenced by clang::driver::SanitizerArgs::SanitizerArgs().
getRTTIMode()
RTTIMode clang::driver::ToolChain::getRTTIMode () const inline
Definition at line 343 of file ToolChain.h.
Referenced by getMultilibFlags(), and clang::driver::SanitizerArgs::SanitizerArgs().
GetRuntimeLibType()
ToolChain::RuntimeLibType ToolChain::GetRuntimeLibType (const llvm::opt::ArgList & Args) const virtual
Reimplemented in clang::driver::toolchains::OHOS, clang::driver::toolchains::Fuchsia, and clang::driver::toolchains::DarwinClang.
Definition at line 1159 of file ToolChain.cpp.
References clang::driver::Driver::Diag(), GetDefaultRuntimeLibType(), getDriver(), RLT_CompilerRT, and RLT_Libgcc.
Referenced by clang::driver::toolchains::BareMetal::AddLinkRuntimeLib(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), GetUnwindLibType(), clang::driver::Driver::HandleImmediateArgs(), and clang::driver::toolchains::Linux::IsAArch64OutlineAtomicsDefault().
getRuntimePath()
std::optional< std::string > ToolChain::getRuntimePath () const
Definition at line 874 of file ToolChain.cpp.
References getTargetSubDirPath(), P, clang::driver::Driver::ResourceDir, and clang::interp::Ret().
Referenced by clang::driver::Driver::HandleImmediateArgs().
getSanitizerArgs()
SanitizerArgs ToolChain::getSanitizerArgs (const llvm::opt::ArgList & JobArgs) const
Definition at line 301 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::NetBSD::addClangTargetOptions(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), collectSanitizerRuntimes(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::toolchains::Fuchsia::Fuchsia(), clang::driver::toolchains::HIPAMDToolChain::getDeviceLibs(), clang::driver::toolchains::Linux::getDynamicLinker(), clang::driver::toolchains::FreeBSD::isPIEDefault(), and clang::driver::toolchains::Linux::isPIEDefault().
getSelectedMultilibs()
const llvm::SmallVector<Multilib>& clang::driver::ToolChain::getSelectedMultilibs () const inline
Definition at line 319 of file ToolChain.h.
References SelectedMultilibs.
Referenced by clang::driver::Driver::HandleImmediateArgs().
GetStaticLibToolPath()
std::string ToolChain::GetStaticLibToolPath () const
Returns the linker path for emitting a static library.
Definition at line 1018 of file ToolChain.cpp.
References GetProgramPath().
getStdlibPath()
std::optional< std::string > ToolChain::getStdlibPath () const
Definition at line 886 of file ToolChain.cpp.
References clang::driver::Driver::Dir, getTargetSubDirPath(), and P.
Referenced by clang::driver::toolchains::VEToolChain::AddCXXStdlibLibArgs(), clang::driver::toolchains::Fuchsia::Fuchsia(), and clang::driver::toolchains::VEToolChain::VEToolChain().
getSupportedSanitizers()
SanitizerMask ToolChain::getSupportedSanitizers () const virtual
Return sanitizers which are available in this toolchain.
Reimplemented in clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::Solaris, clang::driver::toolchains::PS5CPU, clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::NetBSD, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::Darwin, clang::driver::toolchains::CudaToolChain, clang::driver::toolchains::CrossWindowsToolChain, clang::driver::toolchains::BareMetal, and clang::driver::toolchains::AMDGPUOpenMPToolChain.
Definition at line 1422 of file ToolChain.cpp.
References getTriple(), and clang::RISCV::Undefined.
Referenced by clang::driver::toolchains::AMDGPUOpenMPToolChain::getSupportedSanitizers(), clang::driver::toolchains::BareMetal::getSupportedSanitizers(), clang::driver::toolchains::CrossWindowsToolChain::getSupportedSanitizers(), clang::driver::toolchains::CudaToolChain::getSupportedSanitizers(), clang::driver::toolchains::Darwin::getSupportedSanitizers(), clang::driver::toolchains::FreeBSD::getSupportedSanitizers(), clang::driver::toolchains::Fuchsia::getSupportedSanitizers(), clang::driver::toolchains::HIPAMDToolChain::getSupportedSanitizers(), clang::driver::toolchains::HIPSPVToolChain::getSupportedSanitizers(), clang::driver::toolchains::Linux::getSupportedSanitizers(), clang::driver::toolchains::MinGW::getSupportedSanitizers(), clang::driver::toolchains::MSVCToolChain::getSupportedSanitizers(), clang::driver::toolchains::NetBSD::getSupportedSanitizers(), clang::driver::toolchains::OHOS::getSupportedSanitizers(), clang::driver::toolchains::OpenBSD::getSupportedSanitizers(), clang::driver::toolchains::PS4PS5Base::getSupportedSanitizers(), clang::driver::toolchains::Solaris::getSupportedSanitizers(), and clang::driver::SanitizerArgs::SanitizerArgs().
getSystemGPUArchs()
Expected< SmallVector< std::string > > ToolChain::getSystemGPUArchs (const llvm::opt::ArgList & Args) const virtual
getSystemGPUArchs - Use a tool to detect the user's availible GPUs.
Reimplemented in clang::driver::toolchains::NVPTXToolChain, and clang::driver::toolchains::AMDGPUToolChain.
Definition at line 1418 of file ToolChain.cpp.
getTargetAndModeFromProgramName()
ParsedClangName ToolChain::getTargetAndModeFromProgramName (StringRef ProgName) static
Return any implicit target and/or mode flag for an invocation of the compiler driver as ProgName.
For example, when called with i686-linux-android-g++, the first element of the return value will be set to "i686-linux-android" and the second will be set to "--driver-mode=g++"`. It is OK if the target name is not registered. In this case the return value contains false in the field TargetIsValid.
Precondition
llvm::InitializeAllTargets() has been called.
Parameters
ProgName The name the Clang driver was invoked with (from, e.g., argv[0]).
Returns
A structure of type ParsedClangName that contains the executable name parts.
Definition at line 399 of file ToolChain.cpp.
References normalizeProgramName(), and parseDriverSuffix().
Referenced by clang::tooling::addTargetAndModeForProgramName(), and clang::driver::getDriverMode().
getTargetSubDirPath()
std::optional< std::string > ToolChain::getTargetSubDirPath (StringRef BaseDir) const protected
Find the target-specific subdirectory for the current target triple under BaseDir, doing fallback triple searches as necessary.
Returns
The subdirectory path if it exists.
Definition at line 833 of file ToolChain.cpp.
References getArch(), getTriple(), getVFS(), and P.
Referenced by clang::driver::toolchains::Generic_GCC::addLibCxxIncludePaths(), getRuntimePath(), and getStdlibPath().
getThreadModel()
virtual std::string clang::driver::ToolChain::getThreadModel () const inline virtual
getThreadModel() - Which thread model does this target use?
Definition at line 638 of file ToolChain.h.
Referenced by clang::driver::Driver::PrintVersion().
getTool()
Tool * ToolChain::getTool (Action::ActionClass AC) const protected virtual
Reimplemented in clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::HLSLToolChain, clang::driver::toolchains::Generic_GCC, and clang::driver::toolchains::MachO.
Definition at line 581 of file ToolChain.cpp.
getTriple()
const llvm::Triple& clang::driver::ToolChain::getTriple () const inline
Definition at line 271 of file ToolChain.h.
Referenced by clang::driver::SanitizerArgs::addArgs(), clang::driver::tools::addAsNeededOption(), clang::driver::toolchains::DarwinClang::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::OHOS::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Hurd::AddClangSystemIncludeArgs(), clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), clang::driver::toolchains::NaClToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::OHOS::AddClangSystemIncludeArgs(), clang::driver::toolchains::CudaToolChain::addClangTargetOptions(), clang::driver::toolchains::HexagonToolChain::addClangTargetOptions(), clang::driver::toolchains::NetBSD::addClangTargetOptions(), clang::driver::toolchains::DarwinClang::addClangWarningOptions(), clang::driver::toolchains::FreeBSD::AddCXXStdlibLibArgs(), addExceptionArgs(), addFortranMain(), clang::driver::toolchains::SYCLToolChain::AddImpliedTargetArgs(), addIncludeLinkerOption(), clang::driver::toolchains::Generic_GCC::addLibCxxIncludePaths(), clang::driver::toolchains::HexagonToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::NaClToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs(), clang::driver::tools::ClangAs::AddMIPSTargetArgs(), addOpenMPDeviceLibC(), addPGOAndCoverageFlags(), clang::driver::toolchains::Darwin::addPlatformVersionArgs(), clang::driver::tools::ClangAs::AddRISCVTargetArgs(), addRunTimeWrapperOpts(), addSanitizerDynamicList(), AddUnwindLibrary(), addVSDefines(), clang::driver::toolchains::MSVCToolChain::buildAssembler(), clang::driver::toolchains::NaClToolChain::buildAssembler(), clang::driver::toolchains::SYCLToolChain::buildBackendCompiler(), buildCompilerRTBasename(), clang::driver::toolchains::AMDGPUOpenMPToolChain::buildLinker(), clang::driver::toolchains::AVRToolChain::buildLinker(), clang::driver::toolchains::HIPAMDToolChain::buildLinker(), clang::driver::toolchains::HIPSPVToolChain::buildLinker(), clang::driver::toolchains::SYCLToolChain::buildLinker(), clang::driver::Compilation::CleanupFile(), collectSanitizerRuntimes(), ComputeLLVMTriple(), clang::driver::toolchains::MSVCToolChain::computeMSVCVersion(), clang::driver::toolchains::BareMetal::computeSysRoot(), clang::driver::toolchains::Linux::computeSysRoot(), clang::driver::toolchains::OHOS::computeSysRoot(), constructHexagonLinkArgs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::tools::SPIRVTranslator::ConstructJob(), clang::driver::tools::SYCLPostLink::ConstructJob(), clang::driver::tools::LinkerWrapper::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::SYCL::fpga::BackendCompiler::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs(), clang::driver::Driver::ConstructPhaseAction(), clang::driver::Driver::CreateOffloadingDeviceToolChains(), defaultToIEEELongDouble(), clang::driver::Driver::generateCompilationDiagnostics(), getArchNameForCompilerRTLib(), clang::driver::Compilation::getArgsForToolChain(), clang::driver::toolchains::AMDGPUOpenMPToolChain::getAuxTriple(), clang::driver::toolchains::CudaToolChain::getAuxTriple(), clang::driver::toolchains::HIPAMDToolChain::getAuxTriple(), clang::driver::toolchains::HIPSPVToolChain::getAuxTriple(), clang::driver::toolchains::SYCLToolChain::getAuxTriple(), getCompilerRT(), clang::driver::toolchains::OHOS::getCompilerRT(), clang::driver::toolchains::HexagonToolChain::GetCXXStdlibType(), clang::driver::toolchains::Linux::GetDefaultCXXStdlibType(), clang::driver::toolchains::SYCLToolChain::getDefaultDebugFormat(), clang::driver::toolchains::AMDGPUToolChain::getDefaultDenormalModeForType(), clang::driver::toolchains::Linux::getDefaultDenormalModeForType(), clang::driver::toolchains::Linux::GetDefaultDwarfVersion(), clang::driver::toolchains::Linux::getDefaultLinker(), clang::driver::toolchains::Linux::GetDefaultRuntimeLibType(), clang::driver::toolchains::Fuchsia::getDefaultSanitizers(), getDefaultUniversalArchName(), clang::driver::toolchains::MSVCToolChain::getDefaultUnwindTableLevel(), clang::driver::toolchains::AMDGPUOpenMPToolChain::getDeviceLibs(), clang::driver::toolchains::HIPSPVToolChain::getDeviceLibs(), clang::driver::tools::getDwarfVersion(), clang::driver::toolchains::Linux::getDynamicLinker(), clang::driver::toolchains::OHOS::getDynamicLinker(), clang::driver::toolchains::Darwin::GetExceptionModel(), clang::driver::toolchains::NetBSD::GetExceptionModel(), clang::driver::toolchains::AMDGPUToolChain::getGPUArch(), getLibGccType(), getLibSpirvTargetName(), clang::driver::toolchains::MachO::getMachOArchName(), clang::driver::Driver::GetNamedOutputPath(), clang::driver::Driver::getOffloadArchs(), clang::driver::toolchains::AMDGPUToolChain::getParsedTargetID(), getSupportedSanitizers(), clang::driver::toolchains::BareMetal::getSupportedSanitizers(), clang::driver::toolchains::Darwin::getSupportedSanitizers(), clang::driver::toolchains::FreeBSD::getSupportedSanitizers(), clang::driver::toolchains::Linux::getSupportedSanitizers(), clang::driver::toolchains::NetBSD::getSupportedSanitizers(), clang::driver::toolchains::Solaris::getSupportedSanitizers(), getTargetSubDirPath(), GetTriplePlusArchString(), GetUnwindLibType(), clang::driver::toolchains::HIPAMDToolChain::HIPAMDToolChain(), clang::driver::toolchains::Linux::IsAArch64OutlineAtomicsDefault(), clang::driver::toolchains::Generic_GCC::IsIntegratedAssemblerDefault(), clang::driver::toolchains::Linux::IsMathErrnoDefault(), clang::driver::toolchains::Generic_GCC::isPICDefault(), clang::driver::toolchains::Generic_GCC::isPICDefaultForced(), clang::driver::toolchains::Linux::isPIEDefault(), clang::driver::isSYCLNativeCPU(), clang::driver::toolchains::MinGW::MinGW(), ProcessVSRuntimeLibrary(), processVSRuntimeLibrary(), renderDebugOptions(), clang::driver::SanitizerArgs::SanitizerArgs(), SetRISCVSmallDataLimit(), ShouldEnableAutolink(), shouldSkipSanitizeOption(), clang::driver::toolchains::MachO::SupportsProfiling(), clang::driver::toolchains::SYCLToolChain::SYCLToolChain(), clang::driver::toolchains::AMDGPUToolChain::TranslateArgs(), clang::driver::toolchains::SYCLToolChain::TranslateArgs(), TranslateOffloadTargetArgs(), clang::driver::toolchains::SYCLToolChain::TranslateTargetOpt(), and clang::driver::XRayArgs::XRayArgs().
getTripleString()
std::string clang::driver::ToolChain::getTripleString () const inline
Definition at line 294 of file ToolChain.h.
Referenced by clang::driver::toolchains::Fuchsia::AddClangCXXStdlibIncludeArgs(), checkDebugInfoOption(), ComputeLLVMTriple(), clang::driver::tools::OffloadPackager::ConstructJob(), clang::driver::Driver::HandleImmediateArgs(), clang::driver::Driver::PrintVersion(), and renderDebugOptions().
GetUnwindLibType()
ToolChain::UnwindLibType ToolChain::GetUnwindLibType (const llvm::opt::ArgList & Args) const virtual
Reimplemented in clang::driver::toolchains::RISCVToolChain, clang::driver::toolchains::OHOS, clang::driver::toolchains::MSP430ToolChain, and clang::driver::toolchains::CSKYToolChain.
Definition at line 1185 of file ToolChain.cpp.
References clang::driver::Driver::Diag(), GetDefaultUnwindLibType(), getDriver(), GetRuntimeLibType(), getTriple(), RLT_CompilerRT, RLT_Libgcc, UNW_CompilerRT, UNW_Libgcc, and UNW_None.
Referenced by AddUnwindLibrary(), and clang::driver::toolchains::OHOS::GetUnwindLibType().
getVFS()
llvm::vfs::FileSystem & ToolChain::getVFS () const
Definition at line 142 of file ToolChain.cpp.
References getDriver(), and clang::driver::Driver::getVFS().
Referenced by clang::driver::toolchains::DarwinClang::AddCCKextLibArgs(), clang::driver::toolchains::DarwinClang::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::OHOS::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::DarwinClang::AddCXXStdlibLibArgs(), clang::driver::toolchains::NetBSD::addLibCxxIncludePaths(), clang::driver::toolchains::Generic_GCC::addLibStdCXXIncludePaths(), clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), clang::driver::toolchains::MachO::AddLinkRuntimeLib(), clang::driver::toolchains::Linux::computeSysRoot(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), detectLibcxxVersion(), FindVisualStudioExecutable(), clang::driver::toolchains::Fuchsia::Fuchsia(), getCompilerRT(), clang::driver::toolchains::OpenBSD::getCompilerRT(), clang::driver::toolchains::Linux::getDynamicLinker(), clang::driver::Driver::GetStdModuleManifestPath(), getTargetSubDirPath(), clang::driver::toolchains::MSVCToolChain::getUniversalCRTLibraryPath(), clang::driver::toolchains::MSVCToolChain::getWindowsSDKLibraryPath(), clang::driver::toolchains::MinGW::MinGW(), clang::driver::toolchains::MSVCToolChain::MSVCToolChain(), clang::driver::toolchains::OHOS::OHOS(), clang::driver::toolchains::ZOS::TryAddIncludeFromPath(), and clang::driver::toolchains::MSVCToolChain::useUniversalCRT().
getXRayArgs()
const XRayArgs & ToolChain::getXRayArgs () const
Definition at line 307 of file ToolChain.cpp.
Referenced by clang::driver::toolchains::DarwinClang::AddLinkRuntimeLibArgs().
hasBlocksRuntime()
virtual bool clang::driver::ToolChain::hasBlocksRuntime () const inline virtual
hasBlocksRuntime - Given that the user is compiling with -fblocks, does this tool chain guarantee the existence of a blocks runtime?
FIXME: this really belongs on some sort of DeploymentTarget abstraction
Reimplemented in clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, and clang::driver::toolchains::Darwin.
Definition at line 678 of file ToolChain.h.
hasEffectiveTriple()
bool clang::driver::ToolChain::hasEffectiveTriple () const inline
Definition at line 304 of file ToolChain.h.
HasNativeLLVMSupport()
bool ToolChain::HasNativeLLVMSupport () const virtual
HasNativeLTOLinker - Check whether the linker and related tools have native LLVM support.
Reimplemented in clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::Hurd, clang::driver::toolchains::Haiku, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::MachO, clang::driver::toolchains::BareMetal, clang::driver::toolchains::AVRToolChain, clang::driver::toolchains::AMDGPUToolChain, and clang::driver::toolchains::AIX.
Definition at line 1037 of file ToolChain.cpp.
IsAArch64OutlineAtomicsDefault()
virtual bool clang::driver::ToolChain::IsAArch64OutlineAtomicsDefault (const llvm::opt::ArgList & Args) const inline virtual
Test whether this toolchain supports outline atomics by default.
Reimplemented in clang::driver::toolchains::Linux, and clang::driver::toolchains::Fuchsia.
Definition at line 566 of file ToolChain.h.
Referenced by clang::driver::tools::addOutlineAtomicsArgs().
isBareMetal()
virtual bool clang::driver::ToolChain::isBareMetal () const inline virtual
isBareMetal - Is this a bare metal target.
Reimplemented in clang::driver::toolchains::BareMetal.
Definition at line 644 of file ToolChain.h.
Referenced by getArchNameForCompilerRTLib(), and getCompilerRTPath().
IsBlocksDefault()
virtual bool clang::driver::ToolChain::IsBlocksDefault () const inline virtual
IsBlocksDefault - Does this tool chain enable -fblocks by default.
Reimplemented in clang::driver::toolchains::MachO.
Definition at line 449 of file ToolChain.h.
isCrossCompiling()
bool ToolChain::isCrossCompiling () const virtual
Returns true if the toolchain is targeting a non-native architecture.
Reimplemented in clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::Darwin, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::BareMetal, and clang::driver::toolchains::AMDGPUToolChain.
Definition at line 1041 of file ToolChain.cpp.
References getArch().
Referenced by clang::driver::toolchains::MinGW::MinGW().
IsEncodeExtendedBlockSignatureDefault()
virtual bool clang::driver::ToolChain::IsEncodeExtendedBlockSignatureDefault () const inline virtual
IsEncodeExtendedBlockSignatureDefault - Does this tool chain enable -fencode-extended-block-signature by default.
Reimplemented in clang::driver::toolchains::MachO.
Definition at line 482 of file ToolChain.h.
isFastMathRuntimeAvailable()
bool ToolChain::isFastMathRuntimeAvailable (const llvm::opt::ArgList & Args, std::string & Path) const virtual
If a runtime library exists that sets global flags for unsafe floating point math, return true.
This checks for presence of the -Ofast, -ffast-math or -funsafe-math flags.
Definition at line 1386 of file ToolChain.cpp.
References GetFilePath(), and clang::driver::isOptimizationLevelFast().
Referenced by addFastMathRuntimeIfAvailable(), and clang::driver::toolchains::Linux::getDefaultDenormalModeForType().
IsIntegratedAssemblerDefault()
virtual bool clang::driver::ToolChain::IsIntegratedAssemblerDefault () const inline virtual
IsIntegratedAssemblerDefault - Does this tool chain enable -integrated-as by default.
Reimplemented in clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::NaClToolChain, and clang::driver::toolchains::Generic_GCC.
Definition at line 453 of file ToolChain.h.
Referenced by useIntegratedAs().
IsIntegratedBackendDefault()
virtual bool clang::driver::ToolChain::IsIntegratedBackendDefault () const inline virtual
IsIntegratedBackendDefault - Does this tool chain enable -fintegrated-objemitter by default.
Reimplemented in clang::driver::toolchains::SPIRVToolChain.
Definition at line 457 of file ToolChain.h.
Referenced by useIntegratedBackend().
IsIntegratedBackendSupported()
virtual bool clang::driver::ToolChain::IsIntegratedBackendSupported () const inline virtual
IsIntegratedBackendSupported - Does this tool chain support -fintegrated-objemitter.
Definition at line 461 of file ToolChain.h.
Referenced by useIntegratedBackend().
IsMathErrnoDefault()
virtual bool clang::driver::ToolChain::IsMathErrnoDefault () const inline virtual
IsMathErrnoDefault - Does this tool chain use -fmath-errno by default.
Reimplemented in clang::driver::toolchains::TCEToolChain, clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::NetBSD, clang::driver::toolchains::Linux, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::Haiku, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::DragonFly, clang::driver::toolchains::MachO, clang::driver::toolchains::NVPTXToolChain, and clang::driver::toolchains::AMDGPUToolChain.
Definition at line 478 of file ToolChain.h.
Referenced by clang::driver::toolchains::Linux::IsMathErrnoDefault(), and RenderFloatingPointOptions().
IsNonIntegratedBackendSupported()
virtual bool clang::driver::ToolChain::IsNonIntegratedBackendSupported () const inline virtual
IsNonIntegratedBackendSupported - Does this tool chain support -fno-integrated-objemitter.
Reimplemented in clang::driver::toolchains::SPIRVToolChain.
Definition at line 465 of file ToolChain.h.
Referenced by useIntegratedBackend().
IsObjCNonFragileABIDefault()
virtual bool clang::driver::ToolChain::IsObjCNonFragileABIDefault () const inline virtual
IsObjCNonFragileABIDefault - Does this tool chain set -fobjc-nonfragile-abi by default.
Reimplemented in clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::NetBSD, clang::driver::toolchains::Haiku, clang::driver::toolchains::FreeBSD, and clang::driver::toolchains::MachO.
Definition at line 486 of file ToolChain.h.
isPICDefault()
virtual bool clang::driver::ToolChain::isPICDefault () const pure virtual
Test whether this toolchain defaults to PIC.
Implemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::TCEToolChain, clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::PS4PS5Base, clang::driver::toolchains::OHOS, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MSP430ToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::HLSLToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::Haiku, clang::driver::toolchains::Generic_GCC, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::MachO, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::CrossWindowsToolChain, clang::driver::toolchains::BareMetal, clang::driver::toolchains::AMDGPUToolChain, and clang::driver::toolchains::AIX.
Referenced by clang::driver::toolchains::SYCLToolChain::isPICDefault().
isPICDefaultForced()
virtual bool clang::driver::ToolChain::isPICDefaultForced () const pure virtual
Tests whether this toolchain forces its default for PIC, PIE or non-PIC.
If this returns true, any PIC related flags should be ignored and instead the results of isPICDefault() and isPIEDefault(const llvm::opt::ArgList &Args) are used exclusively.
Implemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::TCEToolChain, clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::OHOS, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MSP430ToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::HLSLToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::Generic_GCC, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::MachO, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::CrossWindowsToolChain, clang::driver::toolchains::BareMetal, clang::driver::toolchains::AMDGPUToolChain, and clang::driver::toolchains::AIX.
isPIEDefault()
virtual bool clang::driver::ToolChain::isPIEDefault (const llvm::opt::ArgList & Args) const pure virtual
Test whether this toolchain defaults to PIE.
Implemented in clang::driver::toolchains::ZOS, clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::TCEToolChain, clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::OpenBSD, clang::driver::toolchains::OHOS, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MSP430ToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Linux, clang::driver::toolchains::HLSLToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::Generic_GCC, clang::driver::toolchains::Fuchsia, clang::driver::toolchains::FreeBSD, clang::driver::toolchains::MachO, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::CrossWindowsToolChain, clang::driver::toolchains::BareMetal, clang::driver::toolchains::AMDGPUToolChain, and clang::driver::toolchains::AIX.
Referenced by clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), and getPIE().
isThreadModelSupported()
bool ToolChain::isThreadModelSupported (const StringRef Model) const virtual
isThreadModelSupported() - Does this target support a thread model?
Definition at line 1067 of file ToolChain.cpp.
Referenced by clang::driver::Driver::PrintVersion().
LookupTypeForExtension()
types::ID ToolChain::LookupTypeForExtension (StringRef Ext) const virtual
LookupTypeForExtension - Return the default language type to use for the given extension.
Reimplemented in clang::driver::toolchains::MachO.
Definition at line 1025 of file ToolChain.cpp.
References clang::driver::Driver::IsFlangMode(), and clang::driver::types::lookupTypeForExtension().
Referenced by clang::driver::Driver::BuildInputs(), and clang::driver::toolchains::MachO::LookupTypeForExtension().
needsGCovInstrumentation()
bool ToolChain::needsGCovInstrumentation (const llvm::opt::ArgList & Args) static
Returns true if gcov instrumentation (-fprofile-arcs or –coverage) is on.
Definition at line 922 of file ToolChain.cpp.
Referenced by addPGOAndCoverageFlags(), addProfileRTLibs(), and clang::driver::toolchains::Darwin::addProfileRTLibs().
needsProfileRT()
bool ToolChain::needsProfileRT (const llvm::opt::ArgList & Args) static
needsProfileRT - returns true if instrumentation profile is on.
Definition at line 908 of file ToolChain.cpp.
Referenced by addProfileRTLibs(), clang::driver::toolchains::AIX::addProfileRTLibs(), clang::driver::toolchains::Darwin::addProfileRTLibs(), clang::driver::toolchains::Linux::addProfileRTLibs(), and clang::driver::toolchains::OHOS::addProfileRTLibs().
parseInlineAsmUsingAsmParser()
virtual bool clang::driver::ToolChain::parseInlineAsmUsingAsmParser () const inline virtual
Check if the toolchain should use AsmParser to parse inlineAsm when integrated assembler is not default.
Reimplemented in clang::driver::toolchains::AIX.
Definition at line 475 of file ToolChain.h.
printVerboseInfo()
virtual void clang::driver::ToolChain::printVerboseInfo (raw_ostream & OS) const inline virtual
Dispatch to the specific toolchain for verbose printing.
This is used when handling the verbose option to print detailed, toolchain-specific information useful for understanding the behavior of the driver on a specific platform.
Reimplemented in clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::MinGW, clang::driver::toolchains::Generic_GCC, and clang::driver::toolchains::Darwin.
Definition at line 432 of file ToolChain.h.
Referenced by clang::driver::Driver::HandleImmediateArgs().
SelectTool()
Tool * ToolChain::SelectTool (const JobAction & JA) const virtual
Choose a tool to use to handle the action JA.
This can be overridden when a particular ToolChain needs to use a compiler other than Clang.
Reimplemented in clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::HIPAMDToolChain, and clang::driver::toolchains::CudaToolChain.
Definition at line 928 of file ToolChain.cpp.
References getDriver(), and clang::driver::Driver::IsFlangMode().
Referenced by clang::driver::toolchains::CudaToolChain::SelectTool(), and clang::driver::toolchains::HIPAMDToolChain::SelectTool().
setTripleEnvironment()
void ToolChain::setTripleEnvironment (llvm::Triple::EnvironmentType Env) protected
Definition at line 134 of file ToolChain.cpp.
References Env.
ShouldLinkCXXStdlib()
bool ToolChain::ShouldLinkCXXStdlib (const llvm::opt::ArgList & Args) const
Returns if the C++ standard library should be linked in.
Note that e.g. -lm should still be linked even if this returns false.
Definition at line 1349 of file ToolChain.cpp.
References clang::driver::Driver::CCCIsCXX(), and getDriver().
Referenced by constructHexagonLinkArgs(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), and clang::driver::tools::zos::Linker::ConstructJob().
supportsDebugInfoOption()
virtual bool clang::driver::ToolChain::supportsDebugInfoOption (const llvm::opt::Arg *) const inline virtual
Does this toolchain supports given debug info option or not.
Reimplemented in clang::driver::toolchains::NVPTXToolChain.
Definition at line 621 of file ToolChain.h.
Referenced by checkDebugInfoOption().
SupportsEmbeddedBitcode()
virtual bool clang::driver::ToolChain::SupportsEmbeddedBitcode () const inline virtual
SupportsEmbeddedBitcode - Does this tool chain support embedded bitcode.
Reimplemented in clang::driver::toolchains::Darwin.
Definition at line 635 of file ToolChain.h.
SupportsProfiling()
virtual bool clang::driver::ToolChain::SupportsProfiling () const inline virtual
SupportsProfiling - Does this tool chain support -pg.
Reimplemented in clang::driver::toolchains::XCoreToolChain, clang::driver::toolchains::VEToolChain, clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::MachO, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::BareMetal, and clang::driver::toolchains::AMDGPUToolChain.
Definition at line 583 of file ToolChain.h.
TranslateArgs()
virtual llvm::opt::DerivedArgList* clang::driver::ToolChain::TranslateArgs (const llvm::opt::DerivedArgList & Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind) const inline virtual
TranslateArgs - Create a new derived argument list for any argument translations this ToolChain may wish to perform, or 0 if no tool chain specific translations are needed.
If DeviceOffloadKind is specified the translation specific for that offload kind is performed.
Parameters
BoundArch - The bound architecture name, or 0.
DeviceOffloadKind - The device offload kind used for the translation.
Reimplemented in clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::MSVCToolChain, clang::driver::toolchains::HLSLToolChain, clang::driver::toolchains::HIPAMDToolChain, clang::driver::toolchains::Generic_GCC, clang::driver::toolchains::Darwin, clang::driver::toolchains::MachO, clang::driver::toolchains::CudaToolChain, clang::driver::toolchains::NVPTXToolChain, clang::driver::toolchains::AMDGPUOpenMPToolChain, and clang::driver::toolchains::AMDGPUToolChain.
Definition at line 375 of file ToolChain.h.
Referenced by clang::driver::Compilation::getArgsForToolChain(), clang::driver::toolchains::AMDGPUOpenMPToolChain::TranslateArgs(), clang::driver::toolchains::NVPTXToolChain::TranslateArgs(), clang::driver::toolchains::CudaToolChain::TranslateArgs(), clang::driver::toolchains::HIPAMDToolChain::TranslateArgs(), and clang::driver::toolchains::SYCLToolChain::TranslateArgs().
TranslateOffloadTargetArgs()
llvm::opt::DerivedArgList * ToolChain::TranslateOffloadTargetArgs (const llvm::opt::DerivedArgList & Args, bool SameTripleAsHost, SmallVectorImpl< llvm::opt::Arg * > & AllocatedArgs, Action::OffloadKind DeviceOffloadKind) const virtual
TranslateOffloadTargetArgs - Create a new derived argument list for that contains the Offload target specific flags passed via -Xopenmp-target -opt=val OR -Xopenmp-target=<triple> -opt=val Also handles -Xsycl-target OR -Xsycl-target=<triple>
Definition at line 1517 of file ToolChain.cpp.
References getArch(), getDriver(), clang::driver::Driver::getOpts(), getTriple(), clang::driver::Action::OFK_OpenMP, and clang::driver::Action::OFK_SYCL.
Referenced by clang::driver::Compilation::getArgsForToolChain().
TranslateXarchArgs() [1/2]
void ToolChain::TranslateXarchArgs (const llvm::opt::DerivedArgList & Args, llvm::opt::Arg *& A, llvm::opt::DerivedArgList * DAL, SmallVectorImpl< llvm::opt::Arg * > * AllocatedArgs = nullptr) const virtual
Append the argument following A to DAL assuming A is an Xarch argument.
If AllocatedArgs is null pointer, synthesized arguments are added to DAL, otherwise they are appended to AllocatedArgs.
Definition at line 1656 of file ToolChain.cpp.
References getDriver(), and clang::driver::Driver::getOpts().
Referenced by clang::driver::Compilation::getArgsForToolChain(), clang::driver::toolchains::MachO::TranslateArgs(), and TranslateXarchArgs().
TranslateXarchArgs() [2/2]
llvm::opt::DerivedArgList * ToolChain::TranslateXarchArgs (const llvm::opt::DerivedArgList & Args, StringRef BoundArch, Action::OffloadKind DeviceOffloadKind, SmallVectorImpl< llvm::opt::Arg * > * AllocatedArgs) const virtual
Translate -Xarch_ arguments.
If there are no such arguments, return a null pointer, otherwise return a DerivedArgList containing the translated arguments.
Definition at line 1698 of file ToolChain.cpp.
References clang::driver::Action::OFK_Host, clang::driver::Action::OFK_None, and TranslateXarchArgs().
UseDwarfDebugFlags()
virtual bool clang::driver::ToolChain::UseDwarfDebugFlags () const inline virtual
UseDwarfDebugFlags - Embed the compile options to clang into the Dwarf compile unit information.
Reimplemented in clang::driver::toolchains::MachO.
Definition at line 595 of file ToolChain.h.
useIntegratedAs()
bool ToolChain::useIntegratedAs () const virtual
Check if the toolchain should use the integrated assembler.
Reimplemented in clang::driver::toolchains::SYCLToolChain, clang::driver::toolchains::SPIRVToolChain, clang::driver::toolchains::HIPSPVToolChain, clang::driver::toolchains::NVPTXToolChain, and clang::driver::toolchains::BareMetal.
Definition at line 146 of file ToolChain.cpp.
References IsIntegratedAssemblerDefault().
Referenced by clang::driver::tools::Clang::ConstructJob(), renderDebugOptions(), and ShouldEnableAutolink().
useIntegratedBackend()
bool ToolChain::useIntegratedBackend () const virtual
Check if the toolchain should use the integrated backend.
Definition at line 152 of file ToolChain.cpp.
References clang::driver::Driver::Diag(), IsIntegratedBackendDefault(), IsIntegratedBackendSupported(), and IsNonIntegratedBackendSupported().
UseObjCMixedDispatch()
virtual bool clang::driver::ToolChain::UseObjCMixedDispatch () const inline virtual
UseObjCMixedDispatchDefault - When using non-legacy dispatch, should the mixed dispatch method be used?
Reimplemented in clang::driver::toolchains::Darwin, and clang::driver::toolchains::MachO.
Definition at line 490 of file ToolChain.h.
Referenced by RenderObjCOptions().
useRelaxRelocations()
bool ToolChain::useRelaxRelocations () const virtual
Check whether to enable x86 relax relocations by default.
Definition at line 180 of file ToolChain.cpp.
Friends And Related Function Documentation
RegisterEffectiveTriple
friend class RegisterEffectiveTriple friend
Definition at line 138 of file ToolChain.h.
Member Data Documentation
Multilibs
MultilibSet clang::driver::ToolChain::Multilibs protected
Definition at line 216 of file ToolChain.h.
Referenced by clang::driver::toolchains::CSKYToolChain::CSKYToolChain(), clang::driver::toolchains::BareMetal::findMultilibs(), clang::driver::toolchains::Fuchsia::Fuchsia(), getMultilibs(), clang::driver::toolchains::Hurd::Hurd(), clang::driver::toolchains::Linux::Linux(), clang::driver::toolchains::MipsLLVMToolChain::MipsLLVMToolChain(), clang::driver::toolchains::OHOS::OHOS(), and clang::driver::toolchains::RISCVToolChain::RISCVToolChain().
SelectedMultilibs
llvm::SmallVector<Multilib> clang::driver::ToolChain::SelectedMultilibs protected
Definition at line 217 of file ToolChain.h.
Referenced by clang::driver::toolchains::MipsLLVMToolChain::computeSysRoot(), clang::driver::toolchains::CSKYToolChain::CSKYToolChain(), clang::driver::toolchains::BareMetal::findMultilibs(), clang::driver::toolchains::Fuchsia::Fuchsia(), clang::driver::toolchains::MipsLLVMToolChain::getCompilerRT(), getCompilerRTPath(), getSelectedMultilibs(), clang::driver::toolchains::Hurd::Hurd(), clang::driver::toolchains::Linux::Linux(), clang::driver::toolchains::MipsLLVMToolChain::MipsLLVMToolChain(), clang::driver::toolchains::OHOS::OHOS(), and clang::driver::toolchains::RISCVToolChain::RISCVToolChain().
The documentation for this class was generated from the following files:
include/clang/Driver/ToolChain.h
lib/Driver/ToolChain.cpp