clang: clang::CodeGen::ReductionCodeGen Class Reference
clang::CodeGen::ReductionCodeGen Class Reference
Class intended to support codegen of all kind of the reduction clauses.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGOpenMPRuntime.h"
Public Member Functions
ReductionCodeGen (ArrayRef< const Expr * > Shareds, ArrayRef< const Expr * > Origs, ArrayRef< const Expr * > Privates, ArrayRef< const Expr * > ReductionOps)
void emitSharedOrigLValue (CodeGenFunction &CGF, unsigned N)
Emits lvalue for the shared and original reduction item.
void emitAggregateType (CodeGenFunction &CGF, unsigned N)
Emits the code for the variable-modified type, if required.
void emitAggregateType (CodeGenFunction &CGF, unsigned N, llvm::Value *Size)
Emits the code for the variable-modified type, if required.
void emitInitialization (CodeGenFunction &CGF, unsigned N, Address PrivateAddr, LValue SharedLVal, llvm::function_ref< bool(CodeGenFunction &)> DefaultInit)
Performs initialization of the private copy for the reduction item.
bool needCleanups (unsigned N)
Returns true if the private copy requires cleanups.
void emitCleanups (CodeGenFunction &CGF, unsigned N, Address PrivateAddr)
Emits cleanup code for the reduction item.
Address adjustPrivateAddress (CodeGenFunction &CGF, unsigned N, Address PrivateAddr)
Adjusts PrivatedAddr for using instead of the original variable address in normal operations.
LValue getSharedLValue (unsigned N) const
Returns LValue for the reduction item.
LValue getOrigLValue (unsigned N) const
Returns LValue for the original reduction item.
std::pair< llvm::Value *, llvm::Value * > getSizes (unsigned N) const
Returns the size of the reduction item (in chars and total number of elements in the item), or nullptr, if the size is a constant.
const VarDecl * getBaseDecl (unsigned N) const
Returns the base declaration of the reduction item.
const Expr * getRefExpr (unsigned N) const
Returns the base declaration of the reduction item.
bool usesReductionInitializer (unsigned N) const
Returns true if the initialization of the reduction item uses initializer from declare reduction construct.
Detailed Description
Class intended to support codegen of all kind of the reduction clauses.
Definition at line 129 of file CGOpenMPRuntime.h.
Constructor & Destructor Documentation
ReductionCodeGen()
ReductionCodeGen::ReductionCodeGen (ArrayRef< const Expr * > Shareds, ArrayRef< const Expr * > Origs, ArrayRef< const Expr * > Privates, ArrayRef< const Expr * > ReductionOps)
Definition at line 791 of file CGOpenMPRuntime.cpp.
References advance().
Member Function Documentation
adjustPrivateAddress()
Address ReductionCodeGen::adjustPrivateAddress (CodeGenFunction & CGF, unsigned N, Address PrivateAddr)
Adjusts PrivatedAddr for using instead of the original variable address in normal operations.
Parameters
N Number of the reduction item.
PrivateAddr Address of the corresponding private item.
Definition at line 1004 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, castToBase(), clang::CodeGen::CGBuilderTy::CreatePointerBitCastOrAddrSpaceCast(), clang::CodeGen::CodeGenFunction::EmitLValue(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::LValue::getAlignment(), getBaseDecl(), clang::CodeGen::Address::getPointer(), clang::CodeGen::LValue::getPointer(), clang::CodeGen::Address::getType(), and loadToBegin().
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit().
emitAggregateType() [1/2]
void ReductionCodeGen::emitAggregateType (CodeGenFunction & CGF, unsigned N)
Emits the code for the variable-modified type, if required.
Parameters
N Number of the reduction item.
Definition at line 825 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::EmitVariablyModifiedType(), clang::CodeGen::RValue::get(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::VariableArrayType::getSizeExpr(), clang::CodeGen::CodeGenFunction::getTypeSize(), and clang::Type::isVariablyModifiedType().
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
emitAggregateType() [2/2]
void ReductionCodeGen::emitAggregateType (CodeGenFunction & CGF, unsigned N, llvm::Value * Size)
Emits the code for the variable-modified type, if required.
Parameters
N Number of the reduction item.
Size Size of the type in chars.
Definition at line 862 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::EmitVariablyModifiedType(), clang::CodeGen::RValue::get(), clang::ASTContext::getAsVariableArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::VariableArrayType::getSizeExpr(), and clang::Type::isVariablyModifiedType().
emitCleanups()
void ReductionCodeGen::emitCleanups (CodeGenFunction & CGF, unsigned N, Address PrivateAddr)
Emits cleanup code for the reduction item.
Parameters
N Number of the reduction item.
PrivateAddr Address of the corresponding private item.
Definition at line 923 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::QualType::isDestructedType(), and clang::CodeGen::CodeGenFunction::pushDestroy().
emitInitialization()
void ReductionCodeGen::emitInitialization (CodeGenFunction & CGF, unsigned N, Address PrivateAddr, LValue SharedLVal, llvm::function_ref< bool(CodeGenFunction &)> DefaultInit)
Performs initialization of the private copy for the reduction item.
Parameters
N Number of the reduction item.
PrivateAddr Address of the corresponding private item.
DefaultInit Default initialization sequence that should be performed if no reduction specific initialization is found.
SharedLVal Address of the original shared variable.
Definition at line 881 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CGBuilderTy::CreateElementBitCast(), clang::CodeGen::CodeGenFunction::EmitAnyExprToMem(), emitInitWithReductionInitializer(), clang::CodeGen::LValue::getAddress(), clang::ASTContext::getAsArrayType(), clang::CodeGen::CodeGenFunction::getContext(), clang::OMPDeclareReductionDecl::getInitializer(), getReductionInit(), clang::CodeGen::CodeGenModule::getTBAAInfoForSubobject(), clang::CodeGen::Address::getType(), clang::CodeGen::LValue::getType(), clang::CodeGen::CodeGenFunction::isTrivialInitializer(), and clang::CodeGen::CodeGenFunction::MakeAddrLValue().
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit().
emitSharedOrigLValue()
void ReductionCodeGen::emitSharedOrigLValue (CodeGenFunction & CGF, unsigned N)
Emits lvalue for the shared and original reduction item.
Parameters
N Number of the reduction item.
Definition at line 810 of file CGOpenMPRuntime.cpp.
References clang::First.
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
getBaseDecl()
const VarDecl* clang::CodeGen::ReductionCodeGen::getBaseDecl (unsigned N) const inline
Returns the base declaration of the reduction item.
Definition at line 217 of file CGOpenMPRuntime.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit().
getOrigLValue()
LValue clang::CodeGen::ReductionCodeGen::getOrigLValue (unsigned N) const inline
Returns LValue for the original reduction item.
Definition at line 210 of file CGOpenMPRuntime.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
getRefExpr()
const Expr* clang::CodeGen::ReductionCodeGen::getRefExpr (unsigned N) const inline
Returns the base declaration of the reduction item.
Definition at line 219 of file CGOpenMPRuntime.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups().
getSharedLValue()
LValue clang::CodeGen::ReductionCodeGen::getSharedLValue (unsigned N) const inline
Returns LValue for the reduction item.
Definition at line 208 of file CGOpenMPRuntime.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
getSizes()
std::pair<llvm::Value *, llvm::Value *> clang::CodeGen::ReductionCodeGen::getSizes (unsigned N) const inline
Returns the size of the reduction item (in chars and total number of elements in the item), or nullptr, if the size is a constant.
Definition at line 213 of file CGOpenMPRuntime.h.
Referenced by clang::CodeGen::CGOpenMPRuntime::emitTaskReductionFixups(), and clang::CodeGen::CGOpenMPRuntime::emitTaskReductionInit().
needCleanups()
bool ReductionCodeGen::needCleanups (unsigned N)
Returns true if the private copy requires cleanups.
Definition at line 915 of file CGOpenMPRuntime.cpp.
References clang::QualType::DK_none, and clang::QualType::isDestructedType().
Referenced by emitReduceFiniFunction().
usesReductionInitializer()
bool ReductionCodeGen::usesReductionInitializer (unsigned N) const
Returns true if the initialization of the reduction item uses initializer from declare reduction construct.
Definition at line 1030 of file CGOpenMPRuntime.cpp.
References clang::OMPDeclareReductionDecl::getInitializer(), and getReductionInit().
The documentation for this class was generated from the following files:
lib/CodeGen/CGOpenMPRuntime.h
lib/CodeGen/CGOpenMPRuntime.cpp