clang: clang::ento::FunctionSummariesTy Class Reference
clang::ento::FunctionSummariesTy Class Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/FunctionSummary.h"
Public Member Functions
MapTy::iterator findOrInsertSummary (const Decl *D)
void markMayInline (const Decl *D)
void markShouldNotInline (const Decl *D)
void markReachedMaxBlockCount (const Decl *D)
std::optional< bool > mayInline (const Decl *D)
void markVisitedBasicBlock (unsigned ID, const Decl *D, unsigned TotalIDs)
unsigned getNumVisitedBasicBlocks (const Decl *D)
unsigned getNumTimesInlined (const Decl *D)
void bumpNumTimesInlined (const Decl *D)
unsigned getPercentBlocksReachable (const Decl *D)
Get the percentage of the reachable blocks.
unsigned getTotalNumBasicBlocks ()
unsigned getTotalNumVisitedBasicBlocks ()
Detailed Description
Definition at line 32 of file FunctionSummary.h.
Member Function Documentation
bumpNumTimesInlined()
void clang::ento::FunctionSummariesTy::bumpNumTimesInlined (const Decl * D) inline
Definition at line 120 of file FunctionSummary.h.
References findOrInsertSummary().
findOrInsertSummary()
MapTy::iterator clang::ento::FunctionSummariesTy::findOrInsertSummary (const Decl * D) inline
Definition at line 60 of file FunctionSummary.h.
Referenced by bumpNumTimesInlined(), markMayInline(), markShouldNotInline(), and markVisitedBasicBlock().
getNumTimesInlined()
unsigned clang::ento::FunctionSummariesTy::getNumTimesInlined (const Decl * D) inline
Definition at line 113 of file FunctionSummary.h.
getNumVisitedBasicBlocks()
unsigned clang::ento::FunctionSummariesTy::getNumVisitedBasicBlocks (const Decl * D) inline
Definition at line 106 of file FunctionSummary.h.
getPercentBlocksReachable()
unsigned clang::ento::FunctionSummariesTy::getPercentBlocksReachable (const Decl * D) inline
Get the percentage of the reachable blocks.
Definition at line 126 of file FunctionSummary.h.
getTotalNumBasicBlocks()
unsigned FunctionSummariesTy::getTotalNumBasicBlocks ()
Definition at line 18 of file FunctionSummary.cpp.
getTotalNumVisitedBasicBlocks()
unsigned FunctionSummariesTy::getTotalNumVisitedBasicBlocks ()
Definition at line 25 of file FunctionSummary.cpp.
markMayInline()
void clang::ento::FunctionSummariesTy::markMayInline (const Decl * D) inline
Definition at line 72 of file FunctionSummary.h.
References findOrInsertSummary().
markReachedMaxBlockCount()
void clang::ento::FunctionSummariesTy::markReachedMaxBlockCount (const Decl * D) inline
Definition at line 84 of file FunctionSummary.h.
References markShouldNotInline().
Referenced by clang::ento::ExprEngine::processCFGBlockEntrance().
markShouldNotInline()
void clang::ento::FunctionSummariesTy::markShouldNotInline (const Decl * D) inline
Definition at line 78 of file FunctionSummary.h.
References findOrInsertSummary().
Referenced by markReachedMaxBlockCount().
markVisitedBasicBlock()
void clang::ento::FunctionSummariesTy::markVisitedBasicBlock (unsigned ID, const Decl * D, unsigned TotalIDs) inline
Definition at line 95 of file FunctionSummary.h.
References findOrInsertSummary(), and ID.
Referenced by clang::ento::CoreEngine::ExecuteWorkList().
mayInline()
std::optional<bool> clang::ento::FunctionSummariesTy::mayInline (const Decl * D) inline
Definition at line 88 of file FunctionSummary.h.
The documentation for this class was generated from the following files:
include/clang/StaticAnalyzer/Core/PathSensitive/FunctionSummary.h
lib/StaticAnalyzer/Core/FunctionSummary.cpp