clang: clang::CodeGen::CodeGenFunction::AutoVarEmission Class Reference
clang::CodeGen::CodeGenFunction::AutoVarEmission Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
bool useLifetimeMarkers () const
llvm::Value * getSizeForLifetimeMarkers () const
Address getAllocatedAddress () const
Returns the raw, allocated address, which is not necessarily the address of the object itself.
RawAddress getOriginalAllocatedAddress () const
Returns the address for the original alloca instruction.
Address getObjectAddress (CodeGenFunction &CGF) const
Returns the address of the object within this declaration.
Static Public Member Functions
static AutoVarEmission invalid ()
Friends
class CodeGenFunction
Detailed Description
Definition at line 3286 of file CodeGenFunction.h.
Member Function Documentation
getAllocatedAddress()
Address clang::CodeGen::CodeGenFunction::AutoVarEmission::getAllocatedAddress () const inline
Returns the raw, allocated address, which is not necessarily the address of the object itself.
It is casted to default address space for address space agnostic languages.
Definition at line 3340 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAutoVarInit(), clang::CodeGen::CodeGenFunction::EmitOMPFirstprivateClause(), clang::CodeGen::CodeGenFunction::EmitOMPLinearClauseInit(), and clang::CodeGen::CodeGenFunction::EmitOMPReductionClauseInit().
getObjectAddress()
Address clang::CodeGen::CodeGenFunction::AutoVarEmission::getObjectAddress (CodeGenFunction & CGF) const inline
Returns the address of the object within this declaration.
Note that this does not chase the forwarding pointer for __block decls.
Definition at line 3350 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::emitBlockByrefAddress().
Referenced by clang::CodeGen::CodeGenFunction::EmitAutoVarInit(), and clang::CodeGen::CodeGenFunction::emitAutoVarTypeCleanup().
getOriginalAllocatedAddress()
RawAddress clang::CodeGen::CodeGenFunction::AutoVarEmission::getOriginalAllocatedAddress () const inline
Returns the address for the original alloca instruction.
Definition at line 3345 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAutoVarDecl().
getSizeForLifetimeMarkers()
llvm::Value* clang::CodeGen::CodeGenFunction::AutoVarEmission::getSizeForLifetimeMarkers () const inline
Definition at line 3332 of file CodeGenFunction.h.
References useLifetimeMarkers().
invalid()
static AutoVarEmission clang::CodeGen::CodeGenFunction::AutoVarEmission::invalid () inline static
Definition at line 3327 of file CodeGenFunction.h.
useLifetimeMarkers()
bool clang::CodeGen::CodeGenFunction::AutoVarEmission::useLifetimeMarkers () const inline
Definition at line 3329 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(), and getSizeForLifetimeMarkers().
Friends And Related Function Documentation
CodeGenFunction
friend class CodeGenFunction friend
Definition at line 3287 of file CodeGenFunction.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h