clang: clang::OMPNumTasksClause Class Reference
clang::OMPNumTasksClause Class Reference
This represents 'num_tasks' clause in the '#pragma omp ...' directive.
#include "clang/AST/OpenMPClause.h"
Public Member Functions
OMPNumTasksClause (Expr *Size, Stmt *HelperSize, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc)
Build 'num_tasks' clause.
OMPNumTasksClause ()
Build an empty clause.
void setLParenLoc (SourceLocation Loc)
Sets the location of '('.
SourceLocation getLParenLoc () const
Returns the location of '('.
Expr * getNumTasks () const
Return safe iteration space distance.
child_range children ()
const_child_range children () const
child_range used_children ()
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClause
SourceLocation getBeginLoc () const
Returns the starting location of the clause.
SourceLocation getEndLoc () const
Returns the ending location of the clause.
void setLocStart (SourceLocation Loc)
Sets the starting location of the clause.
void setLocEnd (SourceLocation Loc)
Sets the ending location of the clause.
OpenMPClauseKind getClauseKind () const
Returns kind of OpenMP clause (private, shared, reduction, etc.).
bool isImplicit () const
child_range children ()
const_child_range children () const
child_range used_children ()
Get the iterator range for the expressions used in the clauses.
const_child_range used_children () const
Public Member Functions inherited from clang::OMPClauseWithPreInit
const Stmt * getPreInitStmt () const
Get pre-initialization statement for the clause.
Stmt * getPreInitStmt ()
Get pre-initialization statement for the clause.
OpenMPDirectiveKind getCaptureRegion () const
Get capture region for the stmt in the clause.
Static Public Member Functions
static bool classof (const OMPClause *T)
Static Public Member Functions inherited from clang::OMPClause
static bool classof (const OMPClause *)
Static Public Member Functions inherited from clang::OMPClauseWithPreInit
static OMPClauseWithPreInit * get (OMPClause *C)
static const OMPClauseWithPreInit * get (const OMPClause *C)
Friends
class OMPClauseReader
Additional Inherited Members
Public Types inherited from clang::OMPClause
using child_iterator = StmtIterator
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Protected Member Functions inherited from clang::OMPClause
OMPClause (OpenMPClauseKind K, SourceLocation StartLoc, SourceLocation EndLoc)
Protected Member Functions inherited from clang::OMPClauseWithPreInit
OMPClauseWithPreInit (const OMPClause *This)
void setPreInitStmt (Stmt *S, OpenMPDirectiveKind ThisRegion=llvm::omp::OMPD_unknown)
Set pre-initialization statement for the clause.
Detailed Description
This represents 'num_tasks' clause in the '#pragma omp ...' directive.
#pragma omp taskloop num_tasks(4)
In this example directive '#pragma omp taskloop' has clause 'num_tasks' with single expression '4'.
Definition at line 6289 of file OpenMPClause.h.
Constructor & Destructor Documentation
OMPNumTasksClause() [1/2]
clang::OMPNumTasksClause::OMPNumTasksClause (Expr * Size, Stmt * HelperSize, OpenMPDirectiveKind CaptureRegion, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation EndLoc) inline
Build 'num_tasks' clause.
Parameters
Size Expression associated with this clause.
HelperSize Helper grainsize for the construct.
CaptureRegion Innermost OpenMP region where expressions in this clause must be captured.
StartLoc Starting location of the clause.
EndLoc Ending location of the clause.
Definition at line 6310 of file OpenMPClause.h.
References clang::OMPClauseWithPreInit::setPreInitStmt().
OMPNumTasksClause() [2/2]
clang::OMPNumTasksClause::OMPNumTasksClause () inline explicit
Build an empty clause.
Definition at line 6319 of file OpenMPClause.h.
Member Function Documentation
children() [1/2]
child_range clang::OMPNumTasksClause::children () inline
Definition at line 6333 of file OpenMPClause.h.
children() [2/2]
const_child_range clang::OMPNumTasksClause::children () const inline
Definition at line 6335 of file OpenMPClause.h.
classof()
static bool clang::OMPNumTasksClause::classof (const OMPClause * T) inline static
Definition at line 6345 of file OpenMPClause.h.
References clang::OMPClause::getClauseKind().
getLParenLoc()
SourceLocation clang::OMPNumTasksClause::getLParenLoc () const inline
Returns the location of '('.
Definition at line 6328 of file OpenMPClause.h.
getNumTasks()
Expr* clang::OMPNumTasksClause::getNumTasks () const inline
Return safe iteration space distance.
Definition at line 6331 of file OpenMPClause.h.
setLParenLoc()
void clang::OMPNumTasksClause::setLParenLoc (SourceLocation Loc) inline
Sets the location of '('.
Definition at line 6325 of file OpenMPClause.h.
used_children() [1/2]
OMPClause::child_range OMPNumTasksClause::used_children ()
Definition at line 299 of file OpenMPClause.cpp.
References getAddrOfExprAsWritten().
Referenced by used_children().
used_children() [2/2]
const_child_range clang::OMPNumTasksClause::used_children () const inline
Definition at line 6340 of file OpenMPClause.h.
References used_children().
Friends And Related Function Documentation
OMPClauseReader
friend class OMPClauseReader friend
Definition at line 6290 of file OpenMPClause.h.
The documentation for this class was generated from the following files:
include/clang/AST/OpenMPClause.h
lib/AST/OpenMPClause.cpp