clang: clang::Qualifiers Class Reference
clang::Qualifiers Class Reference
The collection of all-type qualifiers we support.
#include "clang/AST/Type.h"
Public Types
enum TQ { Const = 0x1, Restrict = 0x2, Volatile = 0x4, CVRMask = Const | Volatile | Restrict }
enum GC { GCNone = 0, Weak, Strong }
enum ObjCLifetime {
OCL_None, OCL_ExplicitNone, OCL_Strong, OCL_Weak,
OCL_Autoreleasing
}
enum { MaxAddressSpace = 0x7fffffu, FastWidth = 3, FastMask = (1 << FastWidth) - 1 }
Public Member Functions
unsigned getAsOpaqueValue () const
bool hasConst () const
bool hasOnlyConst () const
void removeConst ()
void addConst ()
bool hasVolatile () const
bool hasOnlyVolatile () const
void removeVolatile ()
void addVolatile ()
bool hasRestrict () const
bool hasOnlyRestrict () const
void removeRestrict ()
void addRestrict ()
bool hasCVRQualifiers () const
unsigned getCVRQualifiers () const
unsigned getCVRUQualifiers () const
void setCVRQualifiers (unsigned mask)
void removeCVRQualifiers (unsigned mask)
void removeCVRQualifiers ()
void addCVRQualifiers (unsigned mask)
void addCVRUQualifiers (unsigned mask)
bool hasUnaligned () const
void setUnaligned (bool flag)
void removeUnaligned ()
void addUnaligned ()
bool hasObjCGCAttr () const
GC getObjCGCAttr () const
void setObjCGCAttr (GC type)
void removeObjCGCAttr ()
void addObjCGCAttr (GC type)
Qualifiers withoutObjCGCAttr () const
Qualifiers withoutObjCLifetime () const
Qualifiers withoutAddressSpace () const
bool hasObjCLifetime () const
ObjCLifetime getObjCLifetime () const
void setObjCLifetime (ObjCLifetime type)
void removeObjCLifetime ()
void addObjCLifetime (ObjCLifetime type)
bool hasNonTrivialObjCLifetime () const
True if the lifetime is neither None or ExplicitNone.
bool hasStrongOrWeakObjCLifetime () const
True if the lifetime is either strong or weak.
bool hasAddressSpace () const
LangAS getAddressSpace () const
bool hasTargetSpecificAddressSpace () const
unsigned getAddressSpaceAttributePrintValue () const
Get the address space attribute value to be printed by diagnostics.
void setAddressSpace (LangAS space)
void removeAddressSpace ()
void addAddressSpace (LangAS space, bool AllowDefaultAddrSpace=false)
bool hasFastQualifiers () const
unsigned getFastQualifiers () const
void setFastQualifiers (unsigned mask)
void removeFastQualifiers (unsigned mask)
void removeFastQualifiers ()
void addFastQualifiers (unsigned mask)
bool hasNonFastQualifiers () const
Return true if the set contains any qualifiers which require an ExtQuals node to be allocated.
Qualifiers getNonFastQualifiers () const
bool hasQualifiers () const
Return true if the set contains any qualifiers.
bool empty () const
void addQualifiers (Qualifiers Q)
Add the qualifiers from the given set to this set.
void removeQualifiers (Qualifiers Q)
Remove the qualifiers from the given set from this set.
void addConsistentQualifiers (Qualifiers qs)
Add the qualifiers from the given set to this set, given that they don't conflict.
bool isAddressSpaceSupersetOf (Qualifiers other) const
Returns true if the address space in these qualifiers is equal to or a superset of the address space in the argument qualifiers.
bool compatiblyIncludes (Qualifiers other) const
Determines if these qualifiers compatibly include another set.
bool compatiblyIncludesObjCLifetime (Qualifiers other) const
Determines if these qualifiers compatibly include another set of qualifiers from the narrow perspective of Objective-C ARC lifetime.
bool isStrictSupersetOf (Qualifiers Other) const
Determine whether this set of qualifiers is a strict superset of another set of qualifiers, not considering qualifier compatibility.
bool operator== (Qualifiers Other) const
bool operator!= (Qualifiers Other) const
operator bool () const
Qualifiers & operator+= (Qualifiers R)
Qualifiers & operator-= (Qualifiers R)
std::string getAsString () const
std::string getAsString (const PrintingPolicy &Policy) const
bool isEmptyWhenPrinted (const PrintingPolicy &Policy) const
void print (raw_ostream &OS, const PrintingPolicy &Policy, bool appendSpaceIfNonEmpty=false) const
void Profile (llvm::FoldingSetNodeID &ID) const
Static Public Member Functions
static Qualifiers removeCommonQualifiers (Qualifiers &L, Qualifiers &R)
Returns the common set of qualifiers while removing them from the given sets.
static Qualifiers fromFastMask (unsigned Mask)
static Qualifiers fromCVRMask (unsigned CVR)
static Qualifiers fromCVRUMask (unsigned CVRU)
static Qualifiers fromOpaqueValue (unsigned opaque)
static bool isAddressSpaceSupersetOf (LangAS A, LangAS B)
Returns true if address space A is equal to or a superset of B.
static std::string getAddrSpaceAsString (LangAS AS)
Friends
Qualifiers operator+ (Qualifiers L, Qualifiers R)
Qualifiers operator- (Qualifiers L, Qualifiers R)
Compute the difference between two qualifier sets.
Detailed Description
The collection of all-type qualifiers we support.
Clang supports five independent qualifiers:
C99: const, volatile, and restrict
MS: __unaligned
Embedded C (TR18037): address spaces
Objective C: the GC attributes (none, weak, or strong)
Definition at line 147 of file Type.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MaxAddressSpace
The maximum supported address space number.
23 bits should be enough for anyone.
FastWidth
The width of the "fast" qualifier mask.
FastMask
The fast qualifier mask.
Definition at line 184 of file Type.h.
GC
enum clang::Qualifiers::GC
Enumerator
GCNone
Weak
Strong
Definition at line 156 of file Type.h.
ObjCLifetime
enum clang::Qualifiers::ObjCLifetime
Enumerator
OCL_None
There is no lifetime qualification on this type.
OCL_ExplicitNone
This object can be modified without requiring retains or releases.
OCL_Strong
Assigning into this object requires the old value to be released and the new value to be retained.
The timing of the release of the old value is inexact: it may be moved to immediately after the last known point where the value is live.
OCL_Weak
Reading or writing from this object requires a barrier call.
OCL_Autoreleasing
Assigning into this object requires a lifetime extension.
Definition at line 162 of file Type.h.
TQ
enum clang::Qualifiers::TQ
Enumerator
Const
Restrict
Volatile
CVRMask
Definition at line 149 of file Type.h.
Member Function Documentation
addAddressSpace()
void clang::Qualifiers::addAddressSpace (LangAS space, bool AllowDefaultAddrSpace = false) inline
Definition at line 389 of file Type.h.
References clang::Default, and setAddressSpace().
Referenced by clang::Sema::ActOnStartOfLambdaDefinition(), addQualifiers(), clang::ASTContext::getAddrSpaceQualType(), and clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter().
addConsistentQualifiers()
void clang::Qualifiers::addConsistentQualifiers (Qualifiers qs) inline
Add the qualifiers from the given set to this set, given that they don't conflict.
Definition at line 463 of file Type.h.
References getAddressSpace(), getObjCGCAttr(), getObjCLifetime(), hasAddressSpace(), hasObjCGCAttr(), and hasObjCLifetime().
Referenced by clang::ASTContext::getBaseElementType(), clang::SplitQualType::getSingleStepDesugaredType(), clang::ASTContext::getUnqualifiedArrayType(), and clang::QualifierCollector::strip().
addConst()
void clang::Qualifiers::addConst () inline
Definition at line 267 of file Type.h.
References Const.
Referenced by clang::Sema::ActOnBlockArguments(), clang::Sema::ActOnStartOfLambdaDefinition(), clang::Sema::AddBuiltinOperatorCandidates(), clang::Sema::CheckFunctionTemplateSpecialization(), and clang::Sema::IsOverload().
addCVRQualifiers()
void clang::Qualifiers::addCVRQualifiers (unsigned mask) inline
Definition at line 294 of file Type.h.
References CVRMask.
Referenced by clang::CodeGen::CodeGenFunction::EmitLValueForField(), fromCVRMask(), and removeCommonQualifiers().
addCVRUQualifiers()
void clang::Qualifiers::addCVRUQualifiers (unsigned mask) inline
Definition at line 298 of file Type.h.
References CVRMask.
Referenced by fromCVRUMask().
addFastQualifiers()
void clang::Qualifiers::addFastQualifiers (unsigned mask) inline
Definition at line 409 of file Type.h.
References FastMask.
Referenced by fromFastMask(), clang::QualType::getLocalQualifiers(), clang::QualType::getQualifiers(), clang::QualType::split(), and clang::QualifierCollector::strip().
addObjCGCAttr()
void clang::Qualifiers::addObjCGCAttr (GC type) inline
Definition at line 316 of file Type.h.
References setObjCGCAttr().
Referenced by addQualifiers(), and clang::ASTContext::getObjCGCQualType().
addObjCLifetime()
void clang::Qualifiers::addObjCLifetime (ObjCLifetime type) inline
Definition at line 344 of file Type.h.
References hasObjCLifetime().
Referenced by addQualifiers(), and clang::ASTContext::getLifetimeQualifiedType().
addQualifiers()
void clang::Qualifiers::addQualifiers (Qualifiers Q) inline
Add the qualifiers from the given set to this set.
Definition at line 428 of file Type.h.
References addAddressSpace(), addObjCGCAttr(), addObjCLifetime(), CVRMask, getAddressSpace(), getObjCGCAttr(), getObjCLifetime(), hasAddressSpace(), hasObjCGCAttr(), and hasObjCLifetime().
Referenced by clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue(), and operator+=().
addRestrict()
void clang::Qualifiers::addRestrict () inline
Definition at line 277 of file Type.h.
References Restrict.
Referenced by CollectVRQualifiers(), and clang::CodeGen::CGOpenMPRuntimeGPU::translateParameter().
addUnaligned()
void clang::Qualifiers::addUnaligned () inline
Definition at line 308 of file Type.h.
addVolatile()
void clang::Qualifiers::addVolatile () inline
Definition at line 272 of file Type.h.
References Volatile.
Referenced by CollectVRQualifiers(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), and clang::CodeGen::AggValueSlot::setVolatile().
compatiblyIncludes()
bool clang::Qualifiers::compatiblyIncludes (Qualifiers other) const inline
Determines if these qualifiers compatibly include another set.
Generally this answers the question of whether an object with the other qualifiers can be safely used as an object with these qualifiers.
Definition at line 517 of file Type.h.
References CVRMask, getObjCGCAttr(), getObjCLifetime(), hasObjCGCAttr(), hasUnaligned(), and isAddressSpaceSupersetOf().
Referenced by AdoptQualifiers(), compareOverloads(), clang::Sema::handlerCanCatch(), clang::QualType::isAtLeastAsQualifiedAs(), clang::QualType::isMoreQualifiedThan(), clang::Sema::isObjCWritebackConversion(), isQualificationConversionStep(), and TryStaticCast().
compatiblyIncludesObjCLifetime()
bool clang::Qualifiers::compatiblyIncludesObjCLifetime (Qualifiers other) const inline
Determines if these qualifiers compatibly include another set of qualifiers from the narrow perspective of Objective-C ARC lifetime.
One set of Objective-C lifetime qualifiers compatibly includes the other if the lifetime qualifiers match, or if both are non-__weak and the including set also contains the 'const' qualifier, or both are non-__weak and one is None (which can only happen in non-ARC modes).
Definition at line 538 of file Type.h.
References getObjCLifetime(), hasConst(), OCL_None, and OCL_Weak.
Referenced by CastsAwayConstness(), and isQualificationConversionStep().
empty()
bool clang::Qualifiers::empty () const inline
Definition at line 425 of file Type.h.
Referenced by clang::Sema::CheckQualifiedFunctionForTypeId(), clang::ASTContext::getAsArrayType(), clang::ASTContext::getUnqualifiedArrayType(), clang::Expr::isNullPointerConstant(), clang::Sema::isObjCWritebackConversion(), clang::TreeTransform< KernelBodyTransform >::TransformNestedNameSpecifierLoc(), and TypeInfoIsInStandardLibrary().
fromCVRMask()
static Qualifiers clang::Qualifiers::fromCVRMask (unsigned CVR) inline static
Definition at line 240 of file Type.h.
References addCVRQualifiers().
Referenced by clang::Sema::BuildQualifiedType(), CastsAwayConstness(), clang::ASTContext::getCVRQualifiedType(), and clang::ArrayType::getIndexTypeQualifiers().
fromCVRUMask()
static Qualifiers clang::Qualifiers::fromCVRUMask (unsigned CVRU) inline static
Definition at line 246 of file Type.h.
References addCVRUQualifiers().
Referenced by clang::Sema::FindCompositePointerType().
fromFastMask()
static Qualifiers clang::Qualifiers::fromFastMask (unsigned Mask) inline static
Definition at line 234 of file Type.h.
References addFastQualifiers().
Referenced by clang::FunctionType::getFastTypeQuals(), and clang::QualType::split().
fromOpaqueValue()
static Qualifiers clang::Qualifiers::fromOpaqueValue (unsigned opaque) inline static
Definition at line 253 of file Type.h.
Referenced by clang::ASTRecordReader::readQualifiers(), and clang::serialization::DataStreamBasicReader< ASTRecordReader >::readQualifiers().
getAddressSpace()
LangAS clang::Qualifiers::getAddressSpace () const inline
Definition at line 363 of file Type.h.
Referenced by addConsistentQualifiers(), addQualifiers(), clang::Sema::CheckExplicitlyDefaultedSpecialMember(), clang::CodeGen::CodeGenTypes::DeriveThisType(), clang::Sema::DiagnoseAssignmentResult(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), clang::CodeGen::CodeGenFunction::EmitCXXDestructorCall(), EmitDeclDestroy(), clang::Sema::FindCompositePointerType(), clang::CodeGen::LValue::getAddressSpace(), clang::QualType::getAddressSpace(), clang::ExtQuals::getAddressSpace(), getAddressSpaceAttributePrintValue(), clang::ASTContext::getTargetAddressSpace(), hasInconsistentOrSupersetQualifiersOf(), hasTargetSpecificAddressSpace(), isAddressSpaceSupersetOf(), IsModifiable(), isQualificationConversionStep(), isStrictSupersetOf(), clang::ASTContext::mergeObjCGCQualifiers(), clang::ASTContext::mergeTypes(), clang::TreeTransform< KernelBodyTransform >::RebuildQualifiedType(), removeCommonQualifiers(), and removeQualifiers().
getAddressSpaceAttributePrintValue()
unsigned clang::Qualifiers::getAddressSpaceAttributePrintValue () const inline
Get the address space attribute value to be printed by diagnostics.
Definition at line 370 of file Type.h.
References clang::Default, getAddressSpace(), hasTargetSpecificAddressSpace(), and clang::toTargetAddressSpace().
Referenced by clang::Sema::CheckAllocatedType().
getAddrSpaceAsString()
std::string Qualifiers::getAddrSpaceAsString (LangAS AS) static
Definition at line 2179 of file TypePrinter.cpp.
getAsOpaqueValue()
unsigned clang::Qualifiers::getAsOpaqueValue () const inline
Definition at line 260 of file Type.h.
Referenced by clang::ODRHash::AddQualType(), clang::ASTContext::mergeTypes(), clang::operator<<(), and clang::serialization::DataStreamBasicWriter< ASTRecordWriter >::writeQualifiers().
getAsString() [1/2]
std::string Qualifiers::getAsString () const
Definition at line 2147 of file TypePrinter.cpp.
Referenced by getFunctionQualifiersAsString(), clang::TextNodeDumper::Visit(), clang::JSONNodeDumper::Visit(), clang::JSONNodeDumper::VisitArrayType(), and clang::TextNodeDumper::VisitArrayType().
getAsString() [2/2]
std::string Qualifiers::getAsString (const PrintingPolicy & Policy) const
Definition at line 2155 of file TypePrinter.cpp.
getCVRQualifiers()
unsigned clang::Qualifiers::getCVRQualifiers () const inline
Definition at line 280 of file Type.h.
References CVRMask.
Referenced by CastsAwayConstness(), clang::CodeGen::CodeGenFunction::EmitObjCIvarRefLValue(), clang::CodeGen::LValue::getVRQualifiers(), hasCVRQualifiers(), hasInconsistentOrSupersetQualifiersOf(), hasMangledSubstitutionQualifiers(), isQualificationConversionStep(), clang::ASTContext::mergeObjCGCQualifiers(), clang::ASTContext::mergeTypes(), and removeCommonQualifiers().
getCVRUQualifiers()
unsigned clang::Qualifiers::getCVRUQualifiers () const inline
Definition at line 281 of file Type.h.
References CVRMask.
Referenced by clang::Sema::FindCompositePointerType().
getFastQualifiers()
unsigned clang::Qualifiers::getFastQualifiers () const inline
Definition at line 397 of file Type.h.
References FastMask.
Referenced by clang::QualifierCollector::apply(), clang::ASTContext::getQualifiedType(), hasFastQualifiers(), and clang::ASTContext::removeAddrSpaceQualType().
getNonFastQualifiers()
Qualifiers clang::Qualifiers::getNonFastQualifiers () const inline
Definition at line 417 of file Type.h.
References setFastQualifiers().
getObjCGCAttr()
GC clang::Qualifiers::getObjCGCAttr () const inline
Definition at line 311 of file Type.h.
Referenced by addConsistentQualifiers(), addQualifiers(), compatiblyIncludes(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), clang::Sema::FindCompositePointerType(), clang::QualType::getObjCGCAttr(), clang::ExtQuals::getObjCGCAttr(), hasInconsistentOrSupersetQualifiersOf(), clang::CodeGen::LValue::isObjCStrong(), clang::CodeGen::LValue::isObjCWeak(), isQualificationConversionStep(), isStrictSupersetOf(), clang::ASTContext::mergeObjCGCQualifiers(), clang::ASTContext::mergeTypes(), removeCommonQualifiers(), and removeQualifiers().
getObjCLifetime()
ObjCLifetime clang::Qualifiers::getObjCLifetime () const inline
Definition at line 337 of file Type.h.
Referenced by addConsistentQualifiers(), addQualifiers(), clang::ASTContext::BlockRequiresCopying(), compatiblyIncludes(), compatiblyIncludesObjCLifetime(), computeCopyInfoForBlockCapture(), clang::Sema::DiagnoseAssignmentResult(), clang::CodeGen::CGObjCRuntime::EmitInitOfCatchParam(), clang::CodeGen::CodeGenFunction::EmitLoadOfLValue(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), clang::Sema::FindCompositePointerType(), clang::CodeGen::CodeGenFunction::generateObjCGetterBody(), clang::CodeGen::LValue::getObjCLifetime(), clang::CodeGen::AggValueSlot::getObjCLifetime(), clang::QualType::getObjCLifetime(), clang::ExtQuals::getObjCLifetime(), hasInconsistentOrSupersetQualifiersOf(), hasNonTrivialObjCLifetime(), hasStrongOrWeakObjCLifetime(), InitCatchParam(), isNonTrivialObjCLifetimeConversion(), clang::QualType::isNonTrivialToPrimitiveCopy(), clang::Sema::isObjCWritebackConversion(), isQualificationConversionStep(), isStrictSupersetOf(), clang::ASTContext::mergeTypes(), removeCommonQualifiers(), and removeQualifiers().
hasAddressSpace()
bool clang::Qualifiers::hasAddressSpace () const inline
Definition at line 362 of file Type.h.
Referenced by addConsistentQualifiers(), addQualifiers(), clang::ASTContext::getAddrSpaceQualType(), clang::QualType::hasAddressSpace(), clang::ExtQuals::hasAddressSpace(), hasInconsistentOrSupersetQualifiersOf(), hasMangledSubstitutionQualifiers(), and isStrictSupersetOf().
hasConst()
bool clang::Qualifiers::hasConst () const inline
Definition at line 264 of file Type.h.
References Const.
Referenced by CastsAwayConstness(), compatiblyIncludesObjCLifetime(), DiagnoseCastQual(), clang::CodeGen::CodeGenFunction::EmitParmDecl(), getNextQualifier(), clang::FunctionType::isConst(), isConstantEmittableObjectType(), isNonTrivialObjCLifetimeConversion(), and isQualificationConversionStep().
hasCVRQualifiers()
bool clang::Qualifiers::hasCVRQualifiers () const inline
Definition at line 279 of file Type.h.
References getCVRQualifiers().
hasFastQualifiers()
bool clang::Qualifiers::hasFastQualifiers () const inline
Definition at line 396 of file Type.h.
References getFastQualifiers().
Referenced by clang::ExtQuals::ExtQuals(), and clang::ExtQuals::Profile().
hasNonFastQualifiers()
bool clang::Qualifiers::hasNonFastQualifiers () const inline
Return true if the set contains any qualifiers which require an ExtQuals node to be allocated.
Definition at line 416 of file Type.h.
References FastMask.
Referenced by clang::QualifierCollector::apply(), clang::ExtQuals::ExtQuals(), clang::ASTContext::getQualifiedType(), and clang::ASTContext::removeAddrSpaceQualType().
hasNonTrivialObjCLifetime()
bool clang::Qualifiers::hasNonTrivialObjCLifetime () const inline
True if the lifetime is neither None or ExplicitNone.
Definition at line 351 of file Type.h.
References getObjCLifetime(), and OCL_ExplicitNone.
Referenced by clang::QualType::hasNonTrivialObjCLifetime().
hasObjCGCAttr()
bool clang::Qualifiers::hasObjCGCAttr () const inline
Definition at line 310 of file Type.h.
Referenced by addConsistentQualifiers(), addQualifiers(), compatiblyIncludes(), clang::ASTContext::getObjCGCQualType(), hasInconsistentOrSupersetQualifiersOf(), clang::ExtQuals::hasObjCGCAttr(), isQualificationConversionStep(), and isStrictSupersetOf().
hasObjCLifetime()
bool clang::Qualifiers::hasObjCLifetime () const inline
Definition at line 336 of file Type.h.
Referenced by addConsistentQualifiers(), addObjCLifetime(), addQualifiers(), computeDestroyInfoForBlockCapture(), clang::ASTContext::getCanonicalFunctionResultType(), hasInconsistentOrSupersetQualifiersOf(), clang::ExtQuals::hasObjCLifetime(), isStrictSupersetOf(), clang::TreeTransform< KernelBodyTransform >::RebuildQualifiedType(), and rewriteToObjCProperty().
hasOnlyConst()
bool clang::Qualifiers::hasOnlyConst () const inline
Definition at line 265 of file Type.h.
References Const.
hasOnlyRestrict()
bool clang::Qualifiers::hasOnlyRestrict () const inline
Definition at line 275 of file Type.h.
References Restrict.
hasOnlyVolatile()
bool clang::Qualifiers::hasOnlyVolatile () const inline
Definition at line 270 of file Type.h.
References Volatile.
hasQualifiers()
bool clang::Qualifiers::hasQualifiers () const inline
Return true if the set contains any qualifiers.
Definition at line 424 of file Type.h.
Referenced by operator bool(), and clang::ASTNodeTraverser< ASTDumper, TextNodeDumper >::Visit().
hasRestrict()
bool clang::Qualifiers::hasRestrict () const inline
Definition at line 274 of file Type.h.
References Restrict.
Referenced by clang::Sema::BuildQualifiedType(), CollectVRQualifiers(), getNextQualifier(), clang::FunctionType::isRestrict(), clang::CodeGen::LValue::isRestrictQualified(), and clang::TreeTransform< KernelBodyTransform >::RebuildQualifiedType().
hasStrongOrWeakObjCLifetime()
bool clang::Qualifiers::hasStrongOrWeakObjCLifetime () const inline
True if the lifetime is either strong or weak.
Definition at line 357 of file Type.h.
References getObjCLifetime(), OCL_Strong, and OCL_Weak.
Referenced by clang::QualType::hasStrongOrWeakObjCLifetime().
hasTargetSpecificAddressSpace()
bool clang::Qualifiers::hasTargetSpecificAddressSpace () const inline
Definition at line 366 of file Type.h.
References getAddressSpace(), and clang::isTargetAddressSpace().
Referenced by getAddressSpaceAttributePrintValue().
hasUnaligned()
bool clang::Qualifiers::hasUnaligned () const inline
Definition at line 303 of file Type.h.
Referenced by compatiblyIncludes(), decomposeTypeForEH(), GetAlignOfType(), clang::ASTContext::getDeclAlign(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), hasMangledSubstitutionQualifiers(), clang::ASTContext::mergeTypes(), clang::Sema::PerformImplicitConversion(), clang::Sema::RefersToMemberWithReducedAlignment(), and withoutUnaligned().
hasVolatile()
bool clang::Qualifiers::hasVolatile () const inline
Definition at line 269 of file Type.h.
References Volatile.
Referenced by CollectVRQualifiers(), DiagnoseCastQual(), getNextQualifier(), isConstantEmittableObjectType(), clang::QualType::isNonTrivialToPrimitiveCopy(), clang::CodeGen::LValue::isVolatile(), clang::CodeGen::AggValueSlot::isVolatile(), clang::FunctionType::isVolatile(), and clang::CodeGen::LValue::isVolatileQualified().
isAddressSpaceSupersetOf() [1/2]
static bool clang::Qualifiers::isAddressSpaceSupersetOf (LangAS A, LangAS B) inline static
Returns true if address space A is equal to or a superset of B.
OpenCL v2.0 defines conversion rules (OpenCLC v2.0 s6.5.5) and notion of overlapping address spaces. CL1.1 or CL1.2: every address space is a superset of itself. CL2.0 adds: __generic is a superset of any address space except for __constant.
Definition at line 480 of file Type.h.
References clang::cuda_constant, clang::cuda_device, clang::cuda_shared, clang::Default, clang::isPtrSizeAddressSpace(), clang::opencl_constant, clang::opencl_generic, clang::opencl_global, clang::opencl_global_device, clang::opencl_global_host, clang::sycl_global, clang::sycl_global_device, clang::sycl_global_host, clang::sycl_local, and clang::sycl_private.
Referenced by compatiblyIncludes(), clang::Sema::FindCompositePointerType(), clang::QualType::isAddressSpaceOverlapping(), isAddressSpaceSupersetOf(), isQualificationConversionStep(), clang::ASTContext::mergeTypes(), clang::Sema::PerformImplicitConversion(), TryAddressSpaceCast(), and TryReinterpretCast().
isAddressSpaceSupersetOf() [2/2]
bool clang::Qualifiers::isAddressSpaceSupersetOf (Qualifiers other) const inline
Returns true if the address space in these qualifiers is equal to or a superset of the address space in the argument qualifiers.
Definition at line 510 of file Type.h.
References getAddressSpace(), and isAddressSpaceSupersetOf().
isEmptyWhenPrinted()
bool Qualifiers::isEmptyWhenPrinted (const PrintingPolicy & Policy) const
Definition at line 2162 of file TypePrinter.cpp.
isStrictSupersetOf()
bool Qualifiers::isStrictSupersetOf (Qualifiers Other) const
Determine whether this set of qualifiers is a strict superset of another set of qualifiers, not considering qualifier compatibility.
Definition at line 58 of file Type.cpp.
References CVRMask, getAddressSpace(), getObjCGCAttr(), getObjCLifetime(), hasAddressSpace(), hasObjCGCAttr(), and hasObjCLifetime().
operator bool()
clang::Qualifiers::operator bool () const inline explicit
Definition at line 558 of file Type.h.
References hasQualifiers().
operator!=()
bool clang::Qualifiers::operator!= (Qualifiers Other) const inline
Definition at line 556 of file Type.h.
operator+=()
Qualifiers& clang::Qualifiers::operator+= (Qualifiers R) inline
Definition at line 560 of file Type.h.
References addQualifiers().
operator-=()
Qualifiers& clang::Qualifiers::operator-= (Qualifiers R) inline
Definition at line 572 of file Type.h.
References removeQualifiers().
operator==()
bool clang::Qualifiers::operator== (Qualifiers Other) const inline
Definition at line 555 of file Type.h.
print()
void Qualifiers::print (raw_ostream & OS, const PrintingPolicy & Policy, bool appendSpaceIfNonEmpty = false) const
Definition at line 2222 of file TypePrinter.cpp.
Profile()
void clang::Qualifiers::Profile (llvm::FoldingSetNodeID & ID) const inline
Definition at line 592 of file Type.h.
Referenced by clang::ExtQuals::Profile().
removeAddressSpace()
void clang::Qualifiers::removeAddressSpace () inline
Definition at line 388 of file Type.h.
References clang::Default, and setAddressSpace().
Referenced by clang::Expr::isNullPointerConstant(), clang::ASTContext::mergeTypes(), RemoveAddressSpaceFromPtr(), clang::ASTContext::removeAddrSpaceQualType(), removeCommonQualifiers(), removeQualifiers(), stripUnusedQualifiers(), and withoutAddressSpace().
removeCommonQualifiers()
static Qualifiers clang::Qualifiers::removeCommonQualifiers (Qualifiers & L, Qualifiers & R) inline static
Returns the common set of qualifiers while removing them from the given sets.
Definition at line 198 of file Type.h.
References addCVRQualifiers(), CVRMask, getAddressSpace(), getCVRQualifiers(), getObjCGCAttr(), getObjCLifetime(), removeAddressSpace(), removeCVRQualifiers(), removeObjCGCAttr(), removeObjCLifetime(), setAddressSpace(), setObjCGCAttr(), and setObjCLifetime().
Referenced by UnwrapTypeForDebugInfo().
removeConst()
void clang::Qualifiers::removeConst () inline
Definition at line 266 of file Type.h.
References Const.
Referenced by clang::Sema::BuildQualifiedType(), CastsAwayConstness(), getNextQualifier(), and TypeInfoIsInStandardLibrary().
removeCVRQualifiers() [1/2]
void clang::Qualifiers::removeCVRQualifiers () inline
Definition at line 291 of file Type.h.
References CVRMask.
removeCVRQualifiers() [2/2]
void clang::Qualifiers::removeCVRQualifiers (unsigned mask) inline
Definition at line 287 of file Type.h.
References CVRMask.
Referenced by clang::ASTContext::hasCvrSimilarType(), removeCommonQualifiers(), and shouldBeModeledWithNoOp().
removeFastQualifiers() [1/2]
void clang::Qualifiers::removeFastQualifiers () inline
Definition at line 406 of file Type.h.
References FastMask.
removeFastQualifiers() [2/2]
void clang::Qualifiers::removeFastQualifiers (unsigned mask) inline
Definition at line 402 of file Type.h.
References FastMask.
removeObjCGCAttr()
void clang::Qualifiers::removeObjCGCAttr () inline
Definition at line 315 of file Type.h.
References GCNone, and setObjCGCAttr().
Referenced by clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::EmitLValueForField(), isQualificationConversionStep(), removeCommonQualifiers(), removeQualifiers(), stripUnusedQualifiers(), TryStaticCast(), and withoutObjCGCAttr().
removeObjCLifetime()
void clang::Qualifiers::removeObjCLifetime () inline
Definition at line 343 of file Type.h.
References OCL_None, and setObjCLifetime().
Referenced by BuildSimilarlyQualifiedPointerType(), clang::ASTContext::getCanonicalFunctionResultType(), clang::ASTContext::getUnqualifiedObjCPointerType(), isQualificationConversionStep(), clang::TreeTransform< KernelBodyTransform >::RebuildQualifiedType(), removeCommonQualifiers(), removeQualifiers(), rewriteToObjCProperty(), stripUnusedQualifiers(), TryStaticCast(), and withoutObjCLifetime().
removeQualifiers()
void clang::Qualifiers::removeQualifiers (Qualifiers Q) inline
Remove the qualifiers from the given set from this set.
Definition at line 445 of file Type.h.
References CVRMask, getAddressSpace(), getObjCGCAttr(), getObjCLifetime(), removeAddressSpace(), removeObjCGCAttr(), and removeObjCLifetime().
Referenced by operator-=().
removeRestrict()
void clang::Qualifiers::removeRestrict () inline
Definition at line 276 of file Type.h.
References Restrict.
Referenced by clang::Sema::BuildQualifiedType(), and getNextQualifier().
removeUnaligned()
void clang::Qualifiers::removeUnaligned () inline
Definition at line 307 of file Type.h.
Referenced by clang::QualType::isAtLeastAsQualifiedAs(), isQualificationConversionStep(), stripUnusedQualifiers(), and withoutUnaligned().
removeVolatile()
void clang::Qualifiers::removeVolatile () inline
Definition at line 271 of file Type.h.
References Volatile.
Referenced by clang::Sema::BuildQualifiedType(), getNextQualifier(), and clang::CodeGen::AggValueSlot::setVolatile().
setAddressSpace()
void clang::Qualifiers::setAddressSpace (LangAS space) inline
Definition at line 383 of file Type.h.
References MaxAddressSpace.
Referenced by addAddressSpace(), clang::Sema::BuildCallExpr(), clang::CodeGen::CodeGenFunction::EmitUnaryOpLValue(), clang::Sema::FindCompositePointerType(), clang::ASTContext::InitBuiltinTypes(), removeAddressSpace(), and removeCommonQualifiers().
setCVRQualifiers()
void clang::Qualifiers::setCVRQualifiers (unsigned mask) inline
Definition at line 283 of file Type.h.
References CVRMask.
setFastQualifiers()
void clang::Qualifiers::setFastQualifiers (unsigned mask) inline
Definition at line 398 of file Type.h.
References FastMask.
Referenced by getNonFastQualifiers().
setObjCGCAttr()
void clang::Qualifiers::setObjCGCAttr (GC type) inline
Definition at line 312 of file Type.h.
Referenced by addObjCGCAttr(), clang::Sema::FindCompositePointerType(), clang::CodeGen::LValue::MakeAddr(), removeCommonQualifiers(), and removeObjCGCAttr().
setObjCLifetime()
void clang::Qualifiers::setObjCLifetime (ObjCLifetime type) inline
Definition at line 340 of file Type.h.
Referenced by clang::Sema::FindCompositePointerType(), clang::Sema::isObjCWritebackConversion(), removeCommonQualifiers(), and removeObjCLifetime().
setUnaligned()
void clang::Qualifiers::setUnaligned (bool flag) inline
Definition at line 304 of file Type.h.
Referenced by clang::Sema::BuildQualifiedType().
withoutAddressSpace()
Qualifiers clang::Qualifiers::withoutAddressSpace () const inline
Definition at line 330 of file Type.h.
References removeAddressSpace().
withoutObjCGCAttr()
Qualifiers clang::Qualifiers::withoutObjCGCAttr () const inline
Definition at line 320 of file Type.h.
References removeObjCGCAttr().
withoutObjCLifetime()
Qualifiers clang::Qualifiers::withoutObjCLifetime () const inline
Definition at line 325 of file Type.h.
References removeObjCLifetime().
Referenced by clang::Sema::isObjCWritebackConversion().
Friends And Related Function Documentation
operator+
Qualifiers operator+ (Qualifiers L, Qualifiers R) friend
Definition at line 567 of file Type.h.
operator-
Qualifiers operator- (Qualifiers L, Qualifiers R) friend
Compute the difference between two qualifier sets.
Definition at line 578 of file Type.h.
The documentation for this class was generated from the following files:
include/clang/AST/Type.h
lib/AST/Type.cpp
lib/AST/TypePrinter.cpp