clang: clang::CodeGen::CGOpenMPRuntime::LastprivateConditionalRAII Class Reference
clang::CodeGen::CGOpenMPRuntime::LastprivateConditionalRAII Class Reference
Manages list of lastprivate conditional decls for the specified directive.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGOpenMPRuntime.h"
Public Member Functions
LastprivateConditionalRAII (CodeGenFunction &CGF, const OMPExecutableDirective &S, LValue IVLVal)
~LastprivateConditionalRAII ()
Static Public Member Functions
static LastprivateConditionalRAII disable (CodeGenFunction &CGF, const OMPExecutableDirective &S)
Detailed Description
Manages list of lastprivate conditional decls for the specified directive.
Definition at line 279 of file CGOpenMPRuntime.h.
Constructor & Destructor Documentation
LastprivateConditionalRAII()
CGOpenMPRuntime::LastprivateConditionalRAII::LastprivateConditionalRAII (CodeGenFunction & CGF, const OMPExecutableDirective & S, LValue IVLVal) explicit
Definition at line 11516 of file CGOpenMPRuntime.cpp.
~LastprivateConditionalRAII()
CGOpenMPRuntime::LastprivateConditionalRAII::~LastprivateConditionalRAII ()
Definition at line 11573 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::CodeGen::CGOpenMPRuntime::LastprivateConditionalStack.
Member Function Documentation
disable()
CGOpenMPRuntime::LastprivateConditionalRAII CGOpenMPRuntime::LastprivateConditionalRAII::disable (CodeGenFunction & CGF, const OMPExecutableDirective & S) static
Definition at line 11568 of file CGOpenMPRuntime.cpp.
Referenced by clang::CodeGen::CodeGenFunction::EmitSimpleOMPExecutableDirective().
The documentation for this class was generated from the following files:
lib/CodeGen/CGOpenMPRuntime.h
lib/CodeGen/CGOpenMPRuntime.cpp