clang: clang::threadSafety::til::Code Class Reference
clang::threadSafety::til::Code Class Reference
A block of code – e.g. the body of a function.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Member Functions
Code (SExpr *T, SExpr *B)
Code (const Code &C, SExpr *T, SExpr *B)
SExpr * returnType ()
const SExpr * returnType () const
SExpr * body ()
const SExpr * body () const
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Code *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
Protected Attributes inherited from clang::threadSafety::til::SExpr
const unsigned char Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
A block of code – e.g. the body of a function.
Definition at line 765 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Code() [1/2]
clang::threadSafety::til::Code::Code (SExpr * T, SExpr * B) inline
Definition at line 767 of file ThreadSafetyTIL.h.
Code() [2/2]
clang::threadSafety::til::Code::Code (const Code & C, SExpr * T, SExpr * B) inline
Definition at line 768 of file ThreadSafetyTIL.h.
Member Function Documentation
body() [1/2]
SExpr* clang::threadSafety::til::Code::body () inline
Definition at line 776 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printCode().
body() [2/2]
const SExpr* clang::threadSafety::til::Code::body () const inline
Definition at line 777 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::Code::classof (const SExpr * E) inline static
Definition at line 771 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Code::compare (const Code * E, C & Cmp) const inline
Definition at line 787 of file ThreadSafetyTIL.h.
returnType() [1/2]
SExpr* clang::threadSafety::til::Code::returnType () inline
Definition at line 773 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::printCode().
returnType() [2/2]
const SExpr* clang::threadSafety::til::Code::returnType () const inline
Definition at line 774 of file ThreadSafetyTIL.h.
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Code::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 780 of file ThreadSafetyTIL.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h