clang: clang::SemaARM Class Reference
clang::SemaARM Class Reference
#include "clang/Sema/SemaARM.h"
Public Types
enum ArmStreamingType { ArmNonStreaming , ArmStreaming , ArmStreamingCompatible , VerifyRuntimeMode }
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Public Member Functions
SemaARM (Sema &S)
bool CheckARMBuiltinExclusiveCall (unsigned BuiltinID, CallExpr *TheCall, unsigned MaxWidth)
bool CheckNeonBuiltinFunctionCall (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
bool CheckMVEBuiltinFunctionCall (unsigned BuiltinID, CallExpr *TheCall)
bool CheckSVEBuiltinFunctionCall (unsigned BuiltinID, CallExpr *TheCall)
bool ParseSVEImmChecks (CallExpr *TheCall, llvm::SmallVector< std::tuple< int, int, int >, 3 > &ImmChecks)
bool CheckSMEBuiltinFunctionCall (unsigned BuiltinID, CallExpr *TheCall)
bool CheckCDEBuiltinFunctionCall (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
bool CheckARMCoprocessorImmediate (const TargetInfo &TI, const Expr *CoprocArg, bool WantCDE)
bool CheckARMBuiltinFunctionCall (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
bool CheckAArch64BuiltinFunctionCall (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
bool BuiltinARMSpecialReg (unsigned BuiltinID, CallExpr *TheCall, int ArgNum, unsigned ExpectedFieldNum, bool AllowName)
BuiltinARMSpecialReg - Handle a check if argument ArgNum of CallExpr TheCall is an ARM/AArch64 special register string literal.
bool BuiltinARMMemoryTaggingCall (unsigned BuiltinID, CallExpr *TheCall)
BuiltinARMMemoryTaggingCall - Handle calls of memory tagging extensions.
bool MveAliasValid (unsigned BuiltinID, StringRef AliasName)
bool CdeAliasValid (unsigned BuiltinID, StringRef AliasName)
bool SveAliasValid (unsigned BuiltinID, StringRef AliasName)
bool SmeAliasValid (unsigned BuiltinID, StringRef AliasName)
void handleBuiltinAliasAttr (Decl *D, const ParsedAttr &AL)
void handleNewAttr (Decl *D, const ParsedAttr &AL)
void handleCmseNSEntryAttr (Decl *D, const ParsedAttr &AL)
void handleInterruptAttr (Decl *D, const ParsedAttr &AL)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Additional Inherited Members
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Detailed Description
Definition at line 26 of file SemaARM.h.
Member Enumeration Documentation
ArmStreamingType
enum clang::SemaARM::ArmStreamingType
Enumerator
ArmNonStreaming
ArmStreaming
Intrinsic is only available in normal mode.
ArmStreamingCompatible
Intrinsic is only available in Streaming-SVE mode.
VerifyRuntimeMode
Intrinsic is available both in normal and Streaming-SVE mode.
Intrinsic is available in normal mode with SVE flags, or in Streaming-SVE mode with SME flags. Do Sema checks for the runtime mode.
Definition at line 30 of file SemaARM.h.
Constructor & Destructor Documentation
SemaARM()
clang::SemaARM::SemaARM (Sema & S)
Definition at line 22 of file SemaARM.cpp.
Member Function Documentation
BuiltinARMMemoryTaggingCall()
bool clang::SemaARM::BuiltinARMMemoryTaggingCall (unsigned BuiltinID, CallExpr * TheCall)
BuiltinARMMemoryTaggingCall - Handle calls of memory tagging extensions.
Definition at line 25 of file SemaARM.cpp.
Referenced by CheckAArch64BuiltinFunctionCall().
BuiltinARMSpecialReg()
bool clang::SemaARM::BuiltinARMSpecialReg (unsigned BuiltinID, CallExpr * TheCall, int ArgNum, unsigned ExpectedFieldNum, bool AllowName)
BuiltinARMSpecialReg - Handle a check if argument ArgNum of CallExpr TheCall is an ARM/AArch64 special register string literal.
Definition at line 187 of file SemaARM.cpp.
References clang::Sema::BuiltinConstantArgRange(), clang::SemaBase::Diag(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::CallExpr::getNumArgs(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreParenImpCasts(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), and clang::SemaBase::SemaRef.
Referenced by CheckAArch64BuiltinFunctionCall(), and CheckARMBuiltinFunctionCall().
CdeAliasValid()
bool clang::SemaARM::CdeAliasValid (unsigned BuiltinID, StringRef AliasName)
Definition at line 1176 of file SemaARM.cpp.
References clang::BuiltinAliasValid().
CheckAArch64BuiltinFunctionCall()
bool clang::SemaARM::CheckAArch64BuiltinFunctionCall (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 1063 of file SemaARM.cpp.
References BuiltinARMMemoryTaggingCall(), BuiltinARMSpecialReg(), clang::Sema::BuiltinConstantArgRange(), CheckARMBuiltinExclusiveCall(), CheckNeonBuiltinFunctionCall(), CheckSMEBuiltinFunctionCall(), CheckSVEBuiltinFunctionCall(), and clang::SemaBase::SemaRef.
CheckARMBuiltinExclusiveCall()
bool clang::SemaARM::CheckARMBuiltinExclusiveCall (unsigned BuiltinID, CallExpr * TheCall, unsigned MaxWidth)
Definition at line 866 of file SemaARM.cpp.
Referenced by CheckAArch64BuiltinFunctionCall(), and CheckARMBuiltinFunctionCall().
CheckARMBuiltinFunctionCall()
bool clang::SemaARM::CheckARMBuiltinFunctionCall (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 985 of file SemaARM.cpp.
References BuiltinARMSpecialReg(), clang::Sema::BuiltinConstantArgRange(), CheckARMBuiltinExclusiveCall(), CheckARMCoprocessorImmediate(), CheckCDEBuiltinFunctionCall(), CheckMVEBuiltinFunctionCall(), CheckNeonBuiltinFunctionCall(), clang::CallExpr::getArg(), and clang::SemaBase::SemaRef.
CheckARMCoprocessorImmediate()
bool clang::SemaARM::CheckARMCoprocessorImmediate (const TargetInfo & TI, const Expr * CoprocArg, bool WantCDE)
Definition at line 841 of file SemaARM.cpp.
Referenced by CheckARMBuiltinFunctionCall(), and CheckCDEBuiltinFunctionCall().
CheckCDEBuiltinFunctionCall()
bool clang::SemaARM::CheckCDEBuiltinFunctionCall (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 825 of file SemaARM.cpp.
References CheckARMCoprocessorImmediate(), and clang::CallExpr::getArg().
Referenced by CheckARMBuiltinFunctionCall().
CheckMVEBuiltinFunctionCall()
bool clang::SemaARM::CheckMVEBuiltinFunctionCall (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 816 of file SemaARM.cpp.
Referenced by CheckARMBuiltinFunctionCall().
CheckNeonBuiltinFunctionCall()
bool clang::SemaARM::CheckNeonBuiltinFunctionCall (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 727 of file SemaARM.cpp.
References clang::Sema::AA_Assigning, ArmNonStreaming, clang::Sema::BuiltinConstantArg(), clang::Sema::BuiltinConstantArgRange(), clang::checkArmStreamingBuiltin(), clang::Sema::CheckSingleAssignmentConstraints(), clang::Sema::DefaultFunctionArrayLvalueConversion(), clang::SemaBase::Diag(), clang::Sema::DiagnoseAssignmentResult(), clang::ActionResult< PtrTy, Compress >::get(), clang::CallExpr::getArg(), clang::SemaBase::getASTContext(), clang::CallExpr::getBeginLoc(), clang::Stmt::getBeginLoc(), clang::Sema::getCurFunctionDecl(), clang::TargetInfo::getInt64Type(), clang::getNeonEltType(), clang::CallExpr::getNumArgs(), clang::ASTContext::getPointerType(), clang::Stmt::getSourceRange(), clang::TargetInfo::getTriple(), clang::Expr::getType(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::SemaBase::SemaRef, clang::TransferrableTargetInfo::SignedLong, and clang::QualType::withConst().
Referenced by CheckAArch64BuiltinFunctionCall(), and CheckARMBuiltinFunctionCall().
CheckSMEBuiltinFunctionCall()
bool clang::SemaARM::CheckSMEBuiltinFunctionCall (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 659 of file SemaARM.cpp.
References clang::ArmZAMask, clang::ArmZT0Mask, clang::checkArmStreamingBuiltin(), clang::SemaBase::Diag(), clang::CallExpr::getBeginLoc(), clang::Sema::getCurFunctionDecl(), clang::getSMEState(), clang::Stmt::getSourceRange(), clang::hasArmZAState(), clang::hasArmZT0State(), ParseSVEImmChecks(), and clang::SemaBase::SemaRef.
Referenced by CheckAArch64BuiltinFunctionCall().
CheckSVEBuiltinFunctionCall()
bool clang::SemaARM::CheckSVEBuiltinFunctionCall (unsigned BuiltinID, CallExpr * TheCall)
Definition at line 699 of file SemaARM.cpp.
References clang::checkArmStreamingBuiltin(), clang::Sema::getCurFunctionDecl(), ParseSVEImmChecks(), and clang::SemaBase::SemaRef.
Referenced by CheckAArch64BuiltinFunctionCall().
handleBuiltinAliasAttr()
void clang::SemaARM::handleBuiltinAliasAttr (Decl * D, const ParsedAttr & AL)
Definition at line 1195 of file SemaARM.cpp.
handleCmseNSEntryAttr()
void clang::SemaARM::handleCmseNSEntryAttr (Decl * D, const ParsedAttr & AL)
Definition at line 1295 of file SemaARM.cpp.
References clang::CPlusPlus, D, clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::SemaBase::getLangOpts(), and clang::AttributeCommonInfo::getLoc().
handleInterruptAttr()
void clang::SemaARM::handleInterruptAttr (Decl * D, const ParsedAttr & AL)
Definition at line 1310 of file SemaARM.cpp.
References clang::Sema::checkStringLiteralArgumentAttr(), D, clang::SemaBase::Diag(), clang::SemaBase::getASTContext(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::hasFeature(), Kind, and clang::SemaBase::SemaRef.
handleNewAttr()
void clang::SemaARM::handleNewAttr (Decl * D, const ParsedAttr & AL)
Definition at line 1242 of file SemaARM.cpp.
References D, clang::SemaBase::Diag(), clang::AttributeCommonInfo::getLoc(), clang::ParsedAttr::getNumArgs(), and clang::ParsedAttr::setInvalid().
MveAliasValid()
bool clang::SemaARM::MveAliasValid (unsigned BuiltinID, StringRef AliasName)
Definition at line 1168 of file SemaARM.cpp.
References clang::BuiltinAliasValid().
ParseSVEImmChecks()
bool clang::SemaARM::ParseSVEImmChecks (CallExpr * TheCall, llvm::SmallVector< std::tuple< int, int, int >, 3 > & ImmChecks)
Definition at line 406 of file SemaARM.cpp.
References bool, clang::Sema::BuiltinConstantArg(), clang::Sema::BuiltinConstantArgMultiple(), clang::Sema::BuiltinConstantArgRange(), clang::SemaBase::Diag(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::SemaBase::SemaRef, and V.
Referenced by CheckSMEBuiltinFunctionCall(), and CheckSVEBuiltinFunctionCall().
SmeAliasValid()
bool clang::SemaARM::SmeAliasValid (unsigned BuiltinID, StringRef AliasName)
Definition at line 1188 of file SemaARM.cpp.
References clang::ASTContext::BuiltinInfo, BuiltinInfo, clang::AArch64::FirstSMEBuiltin, clang::SemaBase::getASTContext(), clang::Builtin::Context::getAuxBuiltinID(), and clang::AArch64::LastSMEBuiltin.
SveAliasValid()
bool clang::SemaARM::SveAliasValid (unsigned BuiltinID, StringRef AliasName)
Definition at line 1181 of file SemaARM.cpp.
References clang::ASTContext::BuiltinInfo, BuiltinInfo, clang::AArch64::FirstSVEBuiltin, clang::SemaBase::getASTContext(), clang::Builtin::Context::getAuxBuiltinID(), and clang::AArch64::LastSVEBuiltin.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaARM.h
lib/Sema/SemaARM.cpp