clang: clang::api_notes::TagInfo Class Reference
clang::api_notes::TagInfo Class Reference
Describes API notes data for a tag.
#include "clang/APINotes/Types.h"
Public Member Functions
TagInfo ()
llvm::Optional< bool > isFlagEnum () const
void setFlagEnum (llvm::Optional< bool > Value)
TagInfo & operator|= (const TagInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS)
Public Member Functions inherited from clang::api_notes::CommonTypeInfo
CommonTypeInfo ()
const llvm::Optional< std::string > & getSwiftBridge () const
void setSwiftBridge (const llvm::Optional< std::string > &SwiftType)
void setSwiftBridge (const llvm::Optional< llvm::StringRef > &SwiftType)
const llvm::Optional< std::string > & getNSErrorDomain () const
void setNSErrorDomain (const llvm::Optional< std::string > &Domain)
void setNSErrorDomain (const llvm::Optional< llvm::StringRef > &Domain)
CommonTypeInfo & operator|= (const CommonTypeInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Member Functions inherited from clang::api_notes::CommonEntityInfo
CommonEntityInfo ()
llvm::Optional< bool > isSwiftPrivate () const
void setSwiftPrivate (llvm::Optional< bool > Private)
CommonEntityInfo & operator|= (const CommonEntityInfo &RHS)
LLVM_DUMP_METHOD void dump (llvm::raw_ostream &OS) const
Public Attributes
llvm::Optional< EnumExtensibilityKind > EnumExtensibility
Public Attributes inherited from clang::api_notes::CommonEntityInfo
std::string UnavailableMsg
Message to use when this entity is unavailable.
unsigned Unavailable: 1
Whether this entity is marked unavailable.
unsigned UnavailableInSwift: 1
Whether this entity is marked unavailable in Swift.
std::string SwiftName
Swift name of this entity.
Friends
bool operator== (const TagInfo &, const TagInfo &)
Detailed Description
Describes API notes data for a tag.
Definition at line 654 of file Types.h.
Constructor & Destructor Documentation
TagInfo()
clang::api_notes::TagInfo::TagInfo () inline
Definition at line 661 of file Types.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void clang::api_notes::TagInfo::dump (llvm::raw_ostream & OS)
Definition at line 90 of file APINotesTypes.cpp.
References clang::api_notes::CommonTypeInfo::dump(), and EnumExtensibility.
isFlagEnum()
llvm::Optional<bool> clang::api_notes::TagInfo::isFlagEnum () const inline
Definition at line 663 of file Types.h.
Referenced by clang::api_notes::operator==(), and operator|=().
operator|=()
TagInfo& clang::api_notes::TagInfo::operator|= (const TagInfo & RHS) inline
Definition at line 673 of file Types.h.
References EnumExtensibility, isFlagEnum(), and setFlagEnum().
setFlagEnum()
void clang::api_notes::TagInfo::setFlagEnum (llvm::Optional< bool > Value) inline
Definition at line 668 of file Types.h.
Referenced by operator|=().
Friends And Related Function Documentation
operator==
bool operator== (const TagInfo & LHS, const TagInfo & RHS) friend
Definition at line 690 of file Types.h.
Member Data Documentation
EnumExtensibility
llvm::Optional<EnumExtensibilityKind> clang::api_notes::TagInfo::EnumExtensibility
Definition at line 659 of file Types.h.
Referenced by dump(), clang::api_notes::operator==(), and operator|=().
The documentation for this class was generated from the following files:
include/clang/APINotes/Types.h
lib/APINotes/APINotesTypes.cpp