clang: clang::DiagnosticConsumer Class Reference
clang::DiagnosticConsumer Class Reference
Abstract interface, implemented by clients of the front-end, which formats and prints fully processed diagnostics.
#include "clang/Basic/Diagnostic.h"
Public Member Functions
DiagnosticConsumer ()=default
virtual ~DiagnosticConsumer ()
unsigned getNumErrors () const
unsigned getNumWarnings () const
virtual void clear ()
virtual void BeginSourceFile (const LangOptions &LangOpts, const Preprocessor *PP=nullptr)
Callback to inform the diagnostic client that processing of a source file is beginning.
virtual void EndSourceFile ()
Callback to inform the diagnostic client that processing of a source file has ended.
virtual void finish ()
Callback to inform the diagnostic client that processing of all source files has ended.
virtual bool IncludeInDiagnosticCounts () const
Indicates whether the diagnostics handled by this DiagnosticConsumer should be included in the number of diagnostics reported by DiagnosticsEngine.
virtual void HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const Diagnostic &Info)
Handle this diagnostic, reporting it to the user or capturing it to a log as needed.
Protected Attributes
unsigned NumWarnings = 0
Number of warnings reported.
unsigned NumErrors = 0
Number of errors reported.
Detailed Description
Abstract interface, implemented by clients of the front-end, which formats and prints fully processed diagnostics.
Definition at line 1728 of file Diagnostic.h.
Constructor & Destructor Documentation
DiagnosticConsumer()
clang::DiagnosticConsumer::DiagnosticConsumer () default
~DiagnosticConsumer()
DiagnosticConsumer::~DiagnosticConsumer () virtual default
Member Function Documentation
BeginSourceFile()
virtual void clang::DiagnosticConsumer::BeginSourceFile (const LangOptions & LangOpts, const Preprocessor * PP = nullptr) inline virtual
Callback to inform the diagnostic client that processing of a source file is beginning.
Note that diagnostics may be emitted outside the processing of a source file, for example during the parsing of command line options. However, diagnostics with source range information are required to only be emitted in between BeginSourceFile() and EndSourceFile().
Parameters
LangOpts The language options for the source file being processed.
PP The preprocessor object being used for the source; this is optional, e.g., it may not be present when processing AST source files.
Reimplemented in clang::LogDiagnosticPrinter, clang::TextDiagnosticPrinter, clang::ChainedDiagnosticConsumer, and clang::VerifyDiagnosticConsumer.
Definition at line 1752 of file Diagnostic.h.
Referenced by clang::arcmt::MigrationProcess::applyTransform(), clang::ChainedDiagnosticConsumer::BeginSourceFile(), clang::FrontendAction::BeginSourceFile(), clang::VerifyDiagnosticConsumer::BeginSourceFile(), clang::arcmt::checkForManualIssues(), clang::ASTUnit::enableSourceFileDiagnostics(), and clang::ASTMergeAction::ExecuteAction().
clear()
virtual void clang::DiagnosticConsumer::clear () inline virtual
Reimplemented in clang::ForwardingDiagnosticConsumer.
Definition at line 1739 of file Diagnostic.h.
References NumErrors, and NumWarnings.
Referenced by clang::FixItRecompile::BeginInvocation(), clang::ForwardingDiagnosticConsumer::clear(), and clang::PCHGenerator::HandleTranslationUnit().
EndSourceFile()
virtual void clang::DiagnosticConsumer::EndSourceFile () inline virtual
Callback to inform the diagnostic client that processing of a source file has ended.
The diagnostic client should assume that any objects made available via BeginSourceFile() are inaccessible.
Reimplemented in clang::VerifyDiagnosticConsumer, clang::LogDiagnosticPrinter, clang::TextDiagnosticPrinter, and clang::ChainedDiagnosticConsumer.
Definition at line 1760 of file Diagnostic.h.
Referenced by clang::arcmt::MigrationProcess::applyTransform(), clang::FrontendAction::BeginSourceFile(), clang::arcmt::checkForManualIssues(), clang::ChainedDiagnosticConsumer::EndSourceFile(), clang::FrontendAction::EndSourceFile(), clang::VerifyDiagnosticConsumer::EndSourceFile(), clang::ASTMergeAction::ExecuteAction(), and clang::ASTUnit::~ASTUnit().
finish()
virtual void clang::DiagnosticConsumer::finish () inline virtual
Callback to inform the diagnostic client that processing of all source files has ended.
Reimplemented in clang::ChainedDiagnosticConsumer.
Definition at line 1764 of file Diagnostic.h.
Referenced by clang::CompilerInstance::ExecuteAction(), and clang::ChainedDiagnosticConsumer::finish().
getNumErrors()
unsigned clang::DiagnosticConsumer::getNumErrors () const inline
Definition at line 1737 of file Diagnostic.h.
References NumErrors.
Referenced by clang::arcmt::MigrationProcess::applyTransform().
getNumWarnings()
unsigned clang::DiagnosticConsumer::getNumWarnings () const inline
Definition at line 1738 of file Diagnostic.h.
References NumWarnings.
HandleDiagnostic()
void DiagnosticConsumer::HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const Diagnostic & Info) virtual
Handle this diagnostic, reporting it to the user or capturing it to a log as needed.
The default implementation just keeps track of the total number of warnings and errors.
Reimplemented in clang::TextDiagnosticPrinter, clang::ForwardingDiagnosticConsumer, clang::VerifyDiagnosticConsumer, clang::FixItRewriter, clang::LogDiagnosticPrinter, clang::ChainedDiagnosticConsumer, clang::TextDiagnosticBuffer, and clang::format::FatalDiagnosticConsumer.
Definition at line 561 of file Diagnostic.cpp.
References clang::DiagnosticsEngine::Error, IncludeInDiagnosticCounts(), NumErrors, NumWarnings, and clang::DiagnosticsEngine::Warning.
Referenced by clang::TextDiagnosticPrinter::HandleDiagnostic(), clang::TextDiagnosticBuffer::HandleDiagnostic(), clang::ChainedDiagnosticConsumer::HandleDiagnostic(), clang::LogDiagnosticPrinter::HandleDiagnostic(), clang::FixItRewriter::HandleDiagnostic(), clang::ForwardingDiagnosticConsumer::HandleDiagnostic(), and clang::DiagnosticsEngine::Report().
IncludeInDiagnosticCounts()
bool DiagnosticConsumer::IncludeInDiagnosticCounts () const virtual
Indicates whether the diagnostics handled by this DiagnosticConsumer should be included in the number of diagnostics reported by DiagnosticsEngine.
IncludeInDiagnosticCounts - This method (whose default implementation returns true) indicates whether the diagnostics handled by this DiagnosticConsumer should be included in the number of diagnostics reported by DiagnosticsEngine.
The default implementation returns true.
Reimplemented in clang::ForwardingDiagnosticConsumer, clang::FixItRewriter, and clang::ChainedDiagnosticConsumer.
Definition at line 1145 of file Diagnostic.cpp.
Referenced by HandleDiagnostic(), clang::ChainedDiagnosticConsumer::IncludeInDiagnosticCounts(), clang::FixItRewriter::IncludeInDiagnosticCounts(), clang::ForwardingDiagnosticConsumer::IncludeInDiagnosticCounts(), and clang::DiagnosticsEngine::Report().
Member Data Documentation
NumErrors
unsigned clang::DiagnosticConsumer::NumErrors = 0 protected
Number of errors reported.
Definition at line 1731 of file Diagnostic.h.
Referenced by clear(), getNumErrors(), and HandleDiagnostic().
NumWarnings
unsigned clang::DiagnosticConsumer::NumWarnings = 0 protected
Number of warnings reported.
Definition at line 1730 of file Diagnostic.h.
Referenced by clear(), getNumWarnings(), and HandleDiagnostic().
The documentation for this class was generated from the following files:
include/clang/Basic/Diagnostic.h
lib/Basic/Diagnostic.cpp