clang: clang::CodeGen::BlockFieldFlags Class Reference
clang::CodeGen::BlockFieldFlags Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGBlocks.h"
Public Member Functions
BlockFieldFlags ()
BlockFieldFlags (BlockFieldFlag_t flag)
uint32_t getBitMask () const
bool empty () const
bool isSpecialPointer () const
Answers whether the flags indicate that this field is an object or block pointer that requires _Block_object_assign/dispose.
bool operator== (BlockFieldFlags Other) const
Friends
BlockFieldFlags operator| (BlockFieldFlags l, BlockFieldFlags r)
BlockFieldFlags & operator|= (BlockFieldFlags &l, BlockFieldFlags r)
bool operator& (BlockFieldFlags l, BlockFieldFlags r)
Detailed Description
Definition at line 102 of file CGBlocks.h.
Constructor & Destructor Documentation
BlockFieldFlags() [1/2]
clang::CodeGen::BlockFieldFlags::BlockFieldFlags () inline
Definition at line 107 of file CGBlocks.h.
BlockFieldFlags() [2/2]
clang::CodeGen::BlockFieldFlags::BlockFieldFlags (BlockFieldFlag_t flag) inline
Definition at line 108 of file CGBlocks.h.
Member Function Documentation
empty()
bool clang::CodeGen::BlockFieldFlags::empty () const inline
Definition at line 111 of file CGBlocks.h.
getBitMask()
uint32_t clang::CodeGen::BlockFieldFlags::getBitMask () const inline
Definition at line 110 of file CGBlocks.h.
Referenced by clang::CodeGen::CodeGenFunction::BuildBlockRelease(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), and getBlockCaptureStr().
isSpecialPointer()
bool clang::CodeGen::BlockFieldFlags::isSpecialPointer () const inline
Answers whether the flags indicate that this field is an object or block pointer that requires _Block_object_assign/dispose.
Definition at line 115 of file CGBlocks.h.
References clang::CodeGen::BLOCK_FIELD_IS_OBJECT.
operator==()
bool clang::CodeGen::BlockFieldFlags::operator== (BlockFieldFlags Other) const inline
Definition at line 127 of file CGBlocks.h.
Friends And Related Function Documentation
operator&
bool operator& (BlockFieldFlags l, BlockFieldFlags r) friend
Definition at line 124 of file CGBlocks.h.
operator|
BlockFieldFlags operator| (BlockFieldFlags l, BlockFieldFlags r) friend
Definition at line 117 of file CGBlocks.h.
operator|=
BlockFieldFlags& operator|= (BlockFieldFlags & l, BlockFieldFlags r) friend
Definition at line 120 of file CGBlocks.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CGBlocks.h