clang: clang::LogDiagnosticPrinter Class Reference
clang::LogDiagnosticPrinter Class Reference
#include "clang/Frontend/LogDiagnosticPrinter.h"
Public Member Functions
LogDiagnosticPrinter (raw_ostream &OS, DiagnosticOptions *Diags, std::unique_ptr< raw_ostream > StreamOwner)
void setDwarfDebugFlags (StringRef Value)
void BeginSourceFile (const LangOptions &LO, const Preprocessor *PP) override
Callback to inform the diagnostic client that processing of a source file is beginning.
void EndSourceFile () override
Callback to inform the diagnostic client that processing of a source file has ended.
void HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const Diagnostic &Info) override
Handle this diagnostic, reporting it to the user or capturing it to a log as needed.
Public Member Functions inherited from clang::DiagnosticConsumer
DiagnosticConsumer ()=default
virtual ~DiagnosticConsumer ()
unsigned getNumErrors () const
unsigned getNumWarnings () const
virtual void clear ()
virtual void finish ()
Callback to inform the diagnostic client that processing of all source files has ended.
virtual bool IncludeInDiagnosticCounts () const
Indicates whether the diagnostics handled by this DiagnosticConsumer should be included in the number of diagnostics reported by DiagnosticsEngine.
Additional Inherited Members
Protected Attributes inherited from clang::DiagnosticConsumer
unsigned NumWarnings = 0
Number of warnings reported.
unsigned NumErrors = 0
Number of errors reported.
Detailed Description
Definition at line 21 of file LogDiagnosticPrinter.h.
Constructor & Destructor Documentation
LogDiagnosticPrinter()
LogDiagnosticPrinter::LogDiagnosticPrinter (raw_ostream & OS, DiagnosticOptions * Diags, std::unique_ptr< raw_ostream > StreamOwner)
Definition at line 20 of file LogDiagnosticPrinter.cpp.
Member Function Documentation
BeginSourceFile()
void clang::LogDiagnosticPrinter::BeginSourceFile (const LangOptions & LangOpts, const Preprocessor * PP) inline override virtual
Callback to inform the diagnostic client that processing of a source file is beginning.
Note that diagnostics may be emitted outside the processing of a source file, for example during the parsing of command line options. However, diagnostics with source range information are required to only be emitted in between BeginSourceFile() and EndSourceFile().
Parameters
LangOpts The language options for the source file being processed.
PP The preprocessor object being used for the source; this is optional, e.g., it may not be present when processing AST source files.
Reimplemented from clang::DiagnosticConsumer.
Definition at line 72 of file LogDiagnosticPrinter.h.
EndSourceFile()
void LogDiagnosticPrinter::EndSourceFile () override virtual
Callback to inform the diagnostic client that processing of a source file has ended.
The diagnostic client should assume that any objects made available via BeginSourceFile() are inaccessible.
Reimplemented from clang::DiagnosticConsumer.
Definition at line 76 of file LogDiagnosticPrinter.cpp.
References clang::markup::EmitString().
HandleDiagnostic()
void LogDiagnosticPrinter::HandleDiagnostic (DiagnosticsEngine::Level DiagLevel, const Diagnostic & Info) override virtual
Handle this diagnostic, reporting it to the user or capturing it to a log as needed.
The default implementation just keeps track of the total number of warnings and errors.
Reimplemented from clang::DiagnosticConsumer.
Definition at line 111 of file LogDiagnosticPrinter.cpp.
References clang::Diagnostic::FormatDiagnostic(), clang::PresumedLoc::getColumn(), clang::PresumedLoc::getFilename(), clang::Diagnostic::getID(), clang::PresumedLoc::getLine(), clang::Diagnostic::getLocation(), clang::FileEntry::getName(), clang::Diagnostic::getSourceManager(), clang::DiagnosticIDs::getWarningOptionForDiag(), clang::DiagnosticConsumer::HandleDiagnostic(), clang::Diagnostic::hasSourceManager(), clang::PresumedLoc::isInvalid(), clang::FileID::isValid(), clang::SourceLocation::isValid(), clang::FileEntry::isValid(), SM, and string().
setDwarfDebugFlags()
void clang::LogDiagnosticPrinter::setDwarfDebugFlags (StringRef Value) inline
Definition at line 68 of file LogDiagnosticPrinter.h.
References string().
The documentation for this class was generated from the following files:
include/clang/Frontend/LogDiagnosticPrinter.h
lib/Frontend/LogDiagnosticPrinter.cpp