clang: clang::interp::ByteCodeExprGen< Emitter > Class Template Reference
clang::interp::ByteCodeExprGen< Emitter > Class Template Reference
Compilation context for expressions.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/ByteCodeExprGen.h"
Public Member Functions
template<typename... Tys>
ByteCodeExprGen (Context &Ctx, Program &P, Tys &&... Args)
Initializes the compiler and the backend emitter.
bool VisitCastExpr (const CastExpr *E)
bool VisitIntegerLiteral (const IntegerLiteral *E)
bool VisitFloatingLiteral (const FloatingLiteral *E)
bool VisitImaginaryLiteral (const ImaginaryLiteral *E)
bool VisitParenExpr (const ParenExpr *E)
bool VisitBinaryOperator (const BinaryOperator *E)
bool VisitLogicalBinOp (const BinaryOperator *E)
bool VisitPointerArithBinOp (const BinaryOperator *E)
Perform addition/subtraction of a pointer and an integer or subtraction of two pointers.
bool VisitComplexBinOp (const BinaryOperator *E)
bool VisitCXXDefaultArgExpr (const CXXDefaultArgExpr *E)
bool VisitCallExpr (const CallExpr *E)
bool VisitBuiltinCallExpr (const CallExpr *E)
bool VisitCXXDefaultInitExpr (const CXXDefaultInitExpr *E)
bool VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr *E)
bool VisitCXXNullPtrLiteralExpr (const CXXNullPtrLiteralExpr *E)
bool VisitGNUNullExpr (const GNUNullExpr *E)
bool VisitCXXThisExpr (const CXXThisExpr *E)
bool VisitUnaryOperator (const UnaryOperator *E)
bool VisitComplexUnaryOperator (const UnaryOperator *E)
bool VisitDeclRefExpr (const DeclRefExpr *E)
bool VisitImplicitValueInitExpr (const ImplicitValueInitExpr *E)
bool VisitSubstNonTypeTemplateParmExpr (const SubstNonTypeTemplateParmExpr *E)
bool VisitArraySubscriptExpr (const ArraySubscriptExpr *E)
bool VisitInitListExpr (const InitListExpr *E)
bool VisitCXXParenListInitExpr (const CXXParenListInitExpr *E)
bool VisitConstantExpr (const ConstantExpr *E)
bool VisitUnaryExprOrTypeTraitExpr (const UnaryExprOrTypeTraitExpr *E)
bool VisitMemberExpr (const MemberExpr *E)
bool VisitArrayInitIndexExpr (const ArrayInitIndexExpr *E)
bool VisitArrayInitLoopExpr (const ArrayInitLoopExpr *E)
bool VisitOpaqueValueExpr (const OpaqueValueExpr *E)
bool VisitAbstractConditionalOperator (const AbstractConditionalOperator *E)
bool VisitStringLiteral (const StringLiteral *E)
bool VisitObjCStringLiteral (const ObjCStringLiteral *E)
bool VisitSYCLUniqueStableNameExpr (const SYCLUniqueStableNameExpr *E)
bool VisitCharacterLiteral (const CharacterLiteral *E)
bool VisitCompoundAssignOperator (const CompoundAssignOperator *E)
bool VisitFloatCompoundAssignOperator (const CompoundAssignOperator *E)
bool VisitPointerCompoundAssignOperator (const CompoundAssignOperator *E)
bool VisitExprWithCleanups (const ExprWithCleanups *E)
bool VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr *E)
bool VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr *E)
bool VisitCompoundLiteralExpr (const CompoundLiteralExpr *E)
bool VisitTypeTraitExpr (const TypeTraitExpr *E)
bool VisitArrayTypeTraitExpr (const ArrayTypeTraitExpr *E)
bool VisitLambdaExpr (const LambdaExpr *E)
bool VisitPredefinedExpr (const PredefinedExpr *E)
bool VisitCXXThrowExpr (const CXXThrowExpr *E)
bool VisitCXXReinterpretCastExpr (const CXXReinterpretCastExpr *E)
bool VisitCXXNoexceptExpr (const CXXNoexceptExpr *E)
bool VisitCXXConstructExpr (const CXXConstructExpr *E)
bool VisitSourceLocExpr (const SourceLocExpr *E)
bool VisitOffsetOfExpr (const OffsetOfExpr *E)
bool VisitCXXScalarValueInitExpr (const CXXScalarValueInitExpr *E)
bool VisitSizeOfPackExpr (const SizeOfPackExpr *E)
bool VisitGenericSelectionExpr (const GenericSelectionExpr *E)
bool VisitChooseExpr (const ChooseExpr *E)
bool VisitObjCBoolLiteralExpr (const ObjCBoolLiteralExpr *E)
bool VisitCXXInheritedCtorInitExpr (const CXXInheritedCtorInitExpr *E)
bool VisitExpressionTraitExpr (const ExpressionTraitExpr *E)
bool VisitCXXUuidofExpr (const CXXUuidofExpr *E)
bool VisitRequiresExpr (const RequiresExpr *E)
bool VisitConceptSpecializationExpr (const ConceptSpecializationExpr *E)
bool VisitCXXRewrittenBinaryOperator (const CXXRewrittenBinaryOperator *E)
bool VisitPseudoObjectExpr (const PseudoObjectExpr *E)
bool VisitPackIndexingExpr (const PackIndexingExpr *E)
bool VisitRecoveryExpr (const RecoveryExpr *E)
bool VisitAddrLabelExpr (const AddrLabelExpr *E)
bool VisitConvertVectorExpr (const ConvertVectorExpr *E)
bool VisitShuffleVectorExpr (const ShuffleVectorExpr *E)
bool VisitObjCBoxedExpr (const ObjCBoxedExpr *E)
Public Member Functions inherited from clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
RetTy Visit (PTR(Stmt) S, ParamTys... P)
BINOP_FALLBACK (PtrMemD) BINOP_FALLBACK(PtrMemI) BINOP_FALLBACK(Mul) BINOP_FALLBACK(Div) BINOP_FALLBACK(Rem) BINOP_FALLBACK(Add) BINOP_FALLBACK(Sub) BINOP_FALLBACK(Shl) BINOP_FALLBACK(LT) BINOP_FALLBACK(GT) BINOP_FALLBACK(LE) BINOP_FALLBACK(GE) BINOP_FALLBACK(EQ) BINOP_FALLBACK(NE) BINOP_FALLBACK(And) BINOP_FALLBACK(Xor) BINOP_FALLBACK(Or) BINOP_FALLBACK(LAnd) BINOP_FALLBACK(LOr) CAO_FALLBACK(MulAssign) CAO_FALLBACK(DivAssign) CAO_FALLBACK(RemAssign) CAO_FALLBACK(AddAssign) CAO_FALLBACK(SubAssign) CAO_FALLBACK(ShlAssign) CAO_FALLBACK(ShrAssign) CAO_FALLBACK(AndAssign) CAO_FALLBACK(OrAssign) UNARYOP_FALLBACK(PostInc) UNARYOP_FALLBACK(PostDec) UNARYOP_FALLBACK(PreInc) UNARYOP_FALLBACK(PreDec) UNARYOP_FALLBACK(AddrOf) UNARYOP_FALLBACK(Deref) UNARYOP_FALLBACK(Plus) UNARYOP_FALLBACK(Minus) UNARYOP_FALLBACK(Not) UNARYOP_FALLBACK(LNot) UNARYOP_FALLBACK(Real) UNARYOP_FALLBACK(Imag) UNARYOP_FALLBACK(Extension) UNARYOP_FALLBACK(Coawait) RetTy VisitStmt(PTR(Stmt) Node
Protected Types
using LabelTy = typename Emitter::LabelTy
using AddrTy = typename Emitter::AddrTy
Protected Member Functions
bool visitExpr (const Expr *E) override
bool visitDecl (const VarDecl *VD) override
Toplevel visitDecl().
void emitCleanup ()
Emits scope cleanup instructions.
const RecordType * getRecordTy (QualType Ty)
Returns a record type from a record or pointer type.
Record * getRecord (QualType Ty)
Returns a record from a record or pointer type.
Record * getRecord (const RecordDecl *RD)
const Function * getFunction (const FunctionDecl *FD)
std::optional< PrimType > classify (const Expr *E) const
std::optional< PrimType > classify (QualType Ty) const
PrimType classifyPrim (QualType Ty) const
Classifies a known primitive type.
PrimType classifyPrim (const Expr *E) const
Classifies a known primitive expression.
bool visit (const Expr *E)
Evaluates an expression and places the result on the stack.
bool visitInitializer (const Expr *E)
Compiles an initializer.
bool discard (const Expr *E)
Evaluates an expression for side effects and discards the result.
bool delegate (const Expr *E)
Just pass evaluation on to E.
bool visitVarDecl (const VarDecl *VD)
Creates and initializes a variable from the given decl.
bool visitAPValue (const APValue &Val, PrimType ValType, const Expr *E)
Visit an APValue.
bool visitAPValueInitializer (const APValue &Val, const Expr *E)
bool visitBool (const Expr *E)
Visits an expression and converts it to a boolean.
bool visitLocalInitializer (const Expr *Init, unsigned I)
Visits an initializer for a local.
bool visitGlobalInitializer (const Expr *Init, unsigned I)
Visits an initializer for a global.
bool visitThisInitializer (const Expr *I)
Visits a delegated initializer.
bool visitInitList (ArrayRef< const Expr * > Inits, const Expr *ArrayFiller, const Expr *E)
bool visitArrayElemInit (unsigned ElemIndex, const Expr *Init)
Pointer to the array(not the element!) must be on the stack when calling this.
unsigned allocateLocalPrimitive (DeclTy &&Decl, PrimType Ty, bool IsConst, bool IsExtended=false)
Creates a local primitive value.
std::optional< unsigned > allocateLocal (DeclTy &&Decl, const ValueDecl *ExtendingDecl=nullptr)
Allocates a space storing a local given its type.
Protected Attributes
Context & Ctx
Current compilation context.
Program & P
Program to link to.
llvm::DenseMap< const ValueDecl *, Scope::Local > Locals
Variable to storage mapping.
llvm::DenseMap< const OpaqueValueExpr *, unsigned > OpaqueExprs
OpaqueValueExpr to location mapping.
VariableScope< Emitter > * VarScope = nullptr
Current scope.
std::optional< uint64_t > ArrayIndex
Current argument index. Needed to emit ArrayInitIndexExpr.
const Expr * SourceLocDefaultExpr = nullptr
DefaultInit- or DefaultArgExpr, needed for SourceLocExpr.
bool DiscardResult = false
Flag indicating if return value is to be discarded.
bool Initializing = false
Flag inidicating if we're initializing an already created variable.
bool GlobalDecl = false
Flag indicating if we're initializing a global variable.
Friends
class VariableScope< Emitter >
class LocalScope< Emitter >
class DestructorScope< Emitter >
class DeclScope< Emitter >
class OptionScope< Emitter >
class ArrayIndexScope< Emitter >
class SourceLocScope< Emitter >
Additional Inherited Members
Public Attributes inherited from clang::StmtVisitorBase< Ptr, ImplClass, RetTy, ParamTys >
ParamTys P { return RetTy()
Detailed Description
template<class Emitter>
class clang::interp::ByteCodeExprGen< Emitter >
Compilation context for expressions.
Definition at line 41 of file ByteCodeExprGen.h.
Member Typedef Documentation
AddrTy
template<class Emitter > using clang::interp::ByteCodeExprGen< Emitter >::AddrTy = typename Emitter::AddrTy protected
Definition at line 46 of file ByteCodeExprGen.h.
LabelTy
template<class Emitter > using clang::interp::ByteCodeExprGen< Emitter >::LabelTy = typename Emitter::LabelTy protected
Definition at line 45 of file ByteCodeExprGen.h.
Constructor & Destructor Documentation
ByteCodeExprGen()
template<class Emitter > template<typename... Tys> clang::interp::ByteCodeExprGen< Emitter >::ByteCodeExprGen (Context & Ctx, Program & P, Tys &&... Args) inline
Initializes the compiler and the backend emitter.
Definition at line 56 of file ByteCodeExprGen.h.
Member Function Documentation
allocateLocal()
template<class Emitter > std::optional< unsigned > ByteCodeExprGen::allocateLocal (DeclTy && Decl, const ValueDecl * ExtendingDecl = nullptr) protected
Allocates a space storing a local given its type.
Definition at line 2938 of file ByteCodeExprGen.cpp.
References clang::Expr::getType(), clang::QualType::getTypePtr(), clang::interp::Init(), clang::interp::Descriptor::InlineDescMD, clang::QualType::isConstQualified(), and P.
allocateLocalPrimitive()
template<class Emitter > unsigned ByteCodeExprGen::allocateLocalPrimitive (DeclTy && Decl, PrimType Ty, bool IsConst, bool IsExtended = false) protected
Creates a local primitive value.
Definition at line 2912 of file ByteCodeExprGen.cpp.
References clang::interp::Descriptor::InlineDescMD, and P.
classify() [1/2]
template<class Emitter > std::optional<PrimType> clang::interp::ByteCodeExprGen< Emitter >::classify (const Expr * E) const inline protected
Definition at line 151 of file ByteCodeExprGen.h.
References clang::interp::Context::classify(), and clang::interp::ByteCodeExprGen< Emitter >::Ctx.
Referenced by clang::interp::ByteCodeExprGen< Emitter >::classifyPrim().
classify() [2/2]
template<class Emitter > std::optional<PrimType> clang::interp::ByteCodeExprGen< Emitter >::classify (QualType Ty) const inline protected
Definition at line 154 of file ByteCodeExprGen.h.
References clang::interp::Context::classify(), and clang::interp::ByteCodeExprGen< Emitter >::Ctx.
classifyPrim() [1/2]
template<class Emitter > PrimType clang::interp::ByteCodeExprGen< Emitter >::classifyPrim (const Expr * E) const inline protected
Classifies a known primitive expression.
Definition at line 166 of file ByteCodeExprGen.h.
References clang::interp::ByteCodeExprGen< Emitter >::classify(), and clang::T.
classifyPrim() [2/2]
template<class Emitter > PrimType clang::interp::ByteCodeExprGen< Emitter >::classifyPrim (QualType Ty) const inline protected
Classifies a known primitive type.
Definition at line 159 of file ByteCodeExprGen.h.
References clang::interp::ByteCodeExprGen< Emitter >::classify(), and clang::T.
delegate()
template<class Emitter > bool ByteCodeExprGen::delegate (const Expr * E) protected
Just pass evaluation on to E.
This leaves all the parsing flags intact.
Definition at line 2667 of file ByteCodeExprGen.cpp.
discard()
template<class Emitter > bool ByteCodeExprGen::discard (const Expr * E) protected
Evaluates an expression for side effects and discards the result.
Definition at line 2660 of file ByteCodeExprGen.cpp.
emitCleanup()
template<class Emitter > void ByteCodeExprGen::emitCleanup protected
Emits scope cleanup instructions.
Definition at line 3842 of file ByteCodeExprGen.cpp.
getFunction()
template<class Emitter > const Function * ByteCodeExprGen::getFunction (const FunctionDecl * FD) protected
Definition at line 2999 of file ByteCodeExprGen.cpp.
getRecord() [1/2]
template<class Emitter > Record * ByteCodeExprGen::getRecord (const RecordDecl * RD) protected
Definition at line 2994 of file ByteCodeExprGen.cpp.
References P.
getRecord() [2/2]
template<class Emitter > Record * ByteCodeExprGen::getRecord (QualType Ty) protected
Returns a record from a record or pointer type.
Definition at line 2987 of file ByteCodeExprGen.cpp.
getRecordTy()
template<class Emitter > const RecordType * ByteCodeExprGen::getRecordTy (QualType Ty) protected
Returns a record type from a record or pointer type.
Definition at line 2980 of file ByteCodeExprGen.cpp.
References clang::Type::getAs(), and clang::Type::getPointeeType().
visit()
template<class Emitter > bool ByteCodeExprGen::visit (const Expr * E) protected
Evaluates an expression and places the result on the stack.
If the expression is of composite type, a local variable will be created and a pointer to said variable will be placed on the stack.
Definition at line 2674 of file ByteCodeExprGen.cpp.
References clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::Expr::isGLValue(), clang::QualType::isNull(), and clang::Type::isVoidType().
VisitAbstractConditionalOperator()
template<class Emitter > bool ByteCodeExprGen::VisitAbstractConditionalOperator (const AbstractConditionalOperator * E)
Definition at line 1552 of file ByteCodeExprGen.cpp.
References clang::Condition, clang::AbstractConditionalOperator::getCond(), clang::AbstractConditionalOperator::getFalseExpr(), and clang::AbstractConditionalOperator::getTrueExpr().
VisitAddrLabelExpr()
template<class Emitter > bool ByteCodeExprGen::VisitAddrLabelExpr (const AddrLabelExpr * E)
Definition at line 2567 of file ByteCodeExprGen.cpp.
References clang::AddrLabelExpr::getLabel(), clang::Expr::getType(), clang::Type::isVoidPointerType(), Offset, and clang::interp::PT_Ptr.
visitAPValue()
template<class Emitter > bool ByteCodeExprGen::visitAPValue (const APValue & Val, PrimType ValType, const Expr * E) protected
Visit an APValue.
Definition at line 3155 of file ByteCodeExprGen.cpp.
References clang::APValue::getInt(), clang::APValue::getLValueBase(), clang::APValue::isInt(), and clang::APValue::isLValue().
visitAPValueInitializer()
template<class Emitter > bool ByteCodeExprGen::visitAPValueInitializer (const APValue & Val, const Expr * E) protected
Definition at line 3171 of file ByteCodeExprGen.cpp.
References clang::APValue::getArrayInitializedElt(), clang::APValue::getArraySize(), clang::interp::Record::getField(), clang::APValue::getStructField(), clang::APValue::getStructNumFields(), clang::Expr::getType(), clang::APValue::isArray(), clang::APValue::isInt(), clang::APValue::isStruct(), and clang::T.
visitArrayElemInit()
template<class Emitter > bool ByteCodeExprGen::visitArrayElemInit (unsigned ElemIndex, const Expr * Init) protected
Pointer to the array(not the element!) must be on the stack when calling this.
Definition at line 1256 of file ByteCodeExprGen.cpp.
References clang::interp::Init(), and clang::T.
VisitArrayInitIndexExpr()
template<class Emitter > bool ByteCodeExprGen::VisitArrayInitIndexExpr (const ArrayInitIndexExpr * E)
Definition at line 1477 of file ByteCodeExprGen.cpp.
VisitArrayInitLoopExpr()
template<class Emitter > bool ByteCodeExprGen::VisitArrayInitLoopExpr (const ArrayInitLoopExpr * E)
Definition at line 1487 of file ByteCodeExprGen.cpp.
References clang::ArrayInitLoopExpr::getArraySize(), clang::ArrayInitLoopExpr::getCommonExpr(), and clang::ArrayInitLoopExpr::getSubExpr().
VisitArraySubscriptExpr()
template<class Emitter > bool ByteCodeExprGen::VisitArraySubscriptExpr (const ArraySubscriptExpr * E)
Definition at line 1004 of file ByteCodeExprGen.cpp.
References clang::ArraySubscriptExpr::getBase().
VisitArrayTypeTraitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitArrayTypeTraitExpr (const ArrayTypeTraitExpr * E)
Definition at line 2072 of file ByteCodeExprGen.cpp.
References clang::ArrayTypeTraitExpr::getValue().
VisitBinaryOperator()
template<class Emitter > bool ByteCodeExprGen::VisitBinaryOperator (const BinaryOperator * E)
Definition at line 511 of file ByteCodeExprGen.cpp.
References clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::BinaryOperator::isCommaOp(), clang::BinaryOperator::isComparisonOp(), clang::Type::isFloatingType(), clang::BinaryOperator::isLogicalOp(), clang::Expr::isLValue(), clang::BinaryOperator::isPtrMemOp(), clang::interp::isPtrType(), clang::Type::isVoidType(), clang::interp::LT(), clang::interp::PT_Bool, clang::Expr::refersToBitField(), and clang::T.
visitBool()
template<class Emitter > bool ByteCodeExprGen::visitBool (const Expr * E) protected
Visits an expression and converts it to a boolean.
Definition at line 2713 of file ByteCodeExprGen.cpp.
References clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::interp::PT_Bool, clang::interp::PT_Float, clang::interp::PT_FnPtr, clang::interp::PT_Ptr, and clang::T.
VisitBuiltinCallExpr()
template<class Emitter > bool ByteCodeExprGen::VisitBuiltinCallExpr (const CallExpr * E)
Definition at line 3219 of file ByteCodeExprGen.cpp.
References clang::CallExpr::arguments(), clang::Func, clang::CallExpr::getDirectCallee(), clang::Expr::getType(), and clang::Type::isVoidType().
VisitCallExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCallExpr (const CallExpr * E)
Definition at line 3256 of file ByteCodeExprGen.cpp.
References clang::interp::align(), clang::interp::collectNonNullArgs(), clang::Func, clang::CallExpr::getArg(), clang::CallExpr::getArgs(), clang::CallExpr::getBuiltinCallee(), clang::CallExpr::getCallee(), clang::CallExpr::getCallReturnType(), clang::CallExpr::getDirectCallee(), clang::CallExpr::getNumArgs(), clang::Type::isVoidType(), clang::interp::primSize(), clang::interp::PT_FnPtr, clang::interp::PT_Ptr, and clang::T.
VisitCastExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCastExpr (const CastExpr * E)
Definition at line 73 of file ByteCodeExprGen.cpp.
References clang::Type::getAs(), clang::CastExpr::getCastKind(), clang::Type::getPointeeType(), clang::CastExpr::getSubExpr(), clang::Expr::getType(), clang::QualType::getTypePtr(), clang::interp::Descriptor::InlineDescMD, clang::Type::isAnyComplexType(), clang::Type::isAtomicType(), clang::Type::isIntegralOrEnumerationType(), clang::QualType::isNull(), clang::Type::isPointerType(), clang::interp::isPtrType(), clang::Type::isVectorType(), clang::Type::isVoidType(), P, clang::CastExpr::path(), clang::interp::PT_IntAP, clang::interp::PT_IntAPS, clang::interp::PT_Ptr, clang::interp::Reinterpret, and clang::T.
VisitCharacterLiteral()
template<class Emitter > bool ByteCodeExprGen::VisitCharacterLiteral (const CharacterLiteral * E)
Definition at line 1671 of file ByteCodeExprGen.cpp.
References clang::CharacterLiteral::getValue().
VisitChooseExpr()
template<class Emitter > bool ByteCodeExprGen::VisitChooseExpr (const ChooseExpr * E)
Definition at line 2430 of file ByteCodeExprGen.cpp.
References clang::ChooseExpr::getChosenSubExpr().
VisitComplexBinOp()
template<class Emitter > bool ByteCodeExprGen::VisitComplexBinOp (const BinaryOperator * E)
Definition at line 777 of file ByteCodeExprGen.cpp.
References clang::Type::getAs(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::Type::isAnyComplexType(), Offset, clang::interp::PT_Float, and clang::interp::PT_Ptr.
VisitComplexUnaryOperator()
template<class Emitter > bool ByteCodeExprGen::VisitComplexUnaryOperator (const UnaryOperator * E)
Definition at line 3645 of file ByteCodeExprGen.cpp.
References clang::UnaryOperator::getSubExpr(), clang::Expr::getType(), clang::Type::isAnyComplexType(), Offset, and clang::interp::PT_Ptr.
VisitCompoundAssignOperator()
template<class Emitter > bool ByteCodeExprGen::VisitCompoundAssignOperator (const CompoundAssignOperator * E)
Definition at line 1790 of file ByteCodeExprGen.cpp.
References clang::CompoundAssignOperator::getComputationLHSType(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::Type::isFloatingType(), clang::Type::isPointerType(), clang::interp::LT(), clang::interp::PT_Float, and clang::Expr::refersToBitField().
VisitCompoundLiteralExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCompoundLiteralExpr (const CompoundLiteralExpr * E)
Definition at line 1997 of file ByteCodeExprGen.cpp.
References clang::CompoundLiteralExpr::getInitializer(), clang::Expr::getType(), clang::interp::Init(), clang::CompoundLiteralExpr::isFileScope(), clang::Expr::isLValue(), P, and clang::T.
VisitConceptSpecializationExpr()
template<class Emitter > bool ByteCodeExprGen::VisitConceptSpecializationExpr (const ConceptSpecializationExpr * E)
Definition at line 2516 of file ByteCodeExprGen.cpp.
References clang::Expr::getType(), clang::ConceptSpecializationExpr::isSatisfied(), and clang::interp::PT_Bool.
VisitConstantExpr()
template<class Emitter > bool ByteCodeExprGen::VisitConstantExpr (const ConstantExpr * E)
Definition at line 1294 of file ByteCodeExprGen.cpp.
References clang::ConstantExpr::getAPValueResult(), clang::FullExpr::getSubExpr(), clang::Expr::getType(), clang::ConstantExpr::hasAPValueResult(), and clang::T.
VisitConvertVectorExpr()
template<class Emitter > bool ByteCodeExprGen::VisitConvertVectorExpr (const ConvertVectorExpr * E)
Definition at line 2577 of file ByteCodeExprGen.cpp.
References clang::Type::castAs(), clang::VectorType::getElementType(), clang::ConvertVectorExpr::getSrcExpr(), clang::Expr::getType(), and clang::interp::PT_Ptr.
VisitCXXBindTemporaryExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXBindTemporaryExpr (const CXXBindTemporaryExpr * E)
Definition at line 1991 of file ByteCodeExprGen.cpp.
References clang::CXXBindTemporaryExpr::getSubExpr().
VisitCXXBoolLiteralExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXBoolLiteralExpr (const CXXBoolLiteralExpr * E)
Definition at line 3408 of file ByteCodeExprGen.cpp.
References clang::CXXBoolLiteralExpr::getValue().
VisitCXXConstructExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXConstructExpr (const CXXConstructExpr * E)
Definition at line 2156 of file ByteCodeExprGen.cpp.
References clang::interp::align(), clang::CXXConstructExpr::arguments(), clang::Func, clang::CXXConstructExpr::getArg(), clang::CXXConstructExpr::getConstructor(), clang::CXXConstructExpr::getNumArgs(), clang::Expr::getType(), clang::ConstantArrayType::getZExtSize(), clang::Type::isArrayType(), clang::Type::isRecordType(), clang::FunctionDecl::isTrivial(), clang::interp::primSize(), clang::interp::PT_Ptr, clang::CXXConstructExpr::requiresZeroInitialization(), and clang::T.
VisitCXXDefaultArgExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXDefaultArgExpr (const CXXDefaultArgExpr * E)
Definition at line 3395 of file ByteCodeExprGen.cpp.
References clang::CXXDefaultArgExpr::getExpr(), and clang::T.
VisitCXXDefaultInitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXDefaultInitExpr (const CXXDefaultInitExpr * E)
Definition at line 3388 of file ByteCodeExprGen.cpp.
References clang::CXXDefaultInitExpr::getExpr().
VisitCXXInheritedCtorInitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXInheritedCtorInitExpr (const CXXInheritedCtorInitExpr * E)
Definition at line 2444 of file ByteCodeExprGen.cpp.
References clang::interp::align(), clang::CXXInheritedCtorInitExpr::getConstructor(), clang::interp::Function::hasRVO(), clang::interp::Function::hasThisPointer(), clang::FunctionDecl::isTrivial(), Offset, clang::FunctionDecl::parameters(), clang::interp::primSize(), and clang::interp::PT_Ptr.
VisitCXXNoexceptExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXNoexceptExpr (const CXXNoexceptExpr * E)
Definition at line 2147 of file ByteCodeExprGen.cpp.
References clang::Expr::getType(), clang::CXXNoexceptExpr::getValue(), and clang::Type::isBooleanType().
VisitCXXNullPtrLiteralExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXNullPtrLiteralExpr (const CXXNullPtrLiteralExpr * E)
Definition at line 3417 of file ByteCodeExprGen.cpp.
VisitCXXParenListInitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXParenListInitExpr (const CXXParenListInitExpr * E)
Definition at line 1282 of file ByteCodeExprGen.cpp.
References clang::CXXParenListInitExpr::getArrayFiller(), and clang::CXXParenListInitExpr::getInitExprs().
VisitCXXReinterpretCastExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXReinterpretCastExpr (const CXXReinterpretCastExpr * E)
Definition at line 2138 of file ByteCodeExprGen.cpp.
References clang::CastExpr::getSubExpr(), and clang::interp::Reinterpret.
VisitCXXRewrittenBinaryOperator()
template<class Emitter > bool ByteCodeExprGen::VisitCXXRewrittenBinaryOperator (const CXXRewrittenBinaryOperator * E)
Definition at line 2525 of file ByteCodeExprGen.cpp.
References clang::CXXRewrittenBinaryOperator::getSemanticForm().
VisitCXXScalarValueInitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXScalarValueInitExpr (const CXXScalarValueInitExpr * E)
Definition at line 2360 of file ByteCodeExprGen.cpp.
References clang::Type::getAs(), clang::Expr::getType(), clang::Type::isVoidType(), and clang::T.
VisitCXXThisExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXThisExpr (const CXXThisExpr * E)
Definition at line 3437 of file ByteCodeExprGen.cpp.
VisitCXXThrowExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXThrowExpr (const CXXThrowExpr * E)
Definition at line 2130 of file ByteCodeExprGen.cpp.
References clang::CXXThrowExpr::getSubExpr().
VisitCXXUuidofExpr()
template<class Emitter > bool ByteCodeExprGen::VisitCXXUuidofExpr (const CXXUuidofExpr * E)
Definition at line 2482 of file ByteCodeExprGen.cpp.
References clang::MSGuidDecl::getAsAPValue(), clang::CXXUuidofExpr::getGuidDecl(), clang::Expr::getType(), clang::APValue::None, P, and V.
visitDecl()
template<class Emitter > bool ByteCodeExprGen::visitDecl (const VarDecl * VD) override protected
Toplevel visitDecl().
We get here from evaluateAsInitializer(). We need to evaluate the initializer and return its value.
Definition at line 3046 of file ByteCodeExprGen.cpp.
References clang::Decl::isInvalidDecl().
VisitDeclRefExpr()
template<class Emitter > bool ByteCodeExprGen::VisitDeclRefExpr (const DeclRefExpr * E)
Definition at line 3738 of file ByteCodeExprGen.cpp.
References clang::DeclRefExpr::getDecl().
visitExpr()
template<class Emitter > bool ByteCodeExprGen::visitExpr (const Expr * E) override protected
Definition at line 3004 of file ByteCodeExprGen.cpp.
References clang::interp::LocalScope< Emitter >::destroyLocals(), clang::Expr::getType(), clang::Type::isVoidType(), and clang::T.
VisitExpressionTraitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitExpressionTraitExpr (const ExpressionTraitExpr * E)
Definition at line 2475 of file ByteCodeExprGen.cpp.
References clang::ExpressionTraitExpr::getValue().
VisitExprWithCleanups()
template<class Emitter > bool ByteCodeExprGen::VisitExprWithCleanups (const ExprWithCleanups * E)
Definition at line 1908 of file ByteCodeExprGen.cpp.
References clang::interp::LocalScope< Emitter >::destroyLocals(), clang::ExprWithCleanups::getNumObjects(), and clang::FullExpr::getSubExpr().
VisitFloatCompoundAssignOperator()
template<class Emitter > bool ByteCodeExprGen::VisitFloatCompoundAssignOperator (const CompoundAssignOperator * E)
Definition at line 1679 of file ByteCodeExprGen.cpp.
References clang::CompoundAssignOperator::getComputationLHSType(), clang::CompoundAssignOperator::getComputationResultType(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::Type::isFloatingType(), and clang::interp::LT().
VisitFloatingLiteral()
template<class Emitter > bool ByteCodeExprGen::VisitFloatingLiteral (const FloatingLiteral * E)
Definition at line 473 of file ByteCodeExprGen.cpp.
References clang::FloatingLiteral::getValue().
VisitGenericSelectionExpr()
template<class Emitter > bool ByteCodeExprGen::VisitGenericSelectionExpr (const GenericSelectionExpr * E)
Definition at line 2424 of file ByteCodeExprGen.cpp.
References clang::GenericSelectionExpr::getResultExpr().
visitGlobalInitializer()
template<class Emitter > bool clang::interp::ByteCodeExprGen< Emitter >::visitGlobalInitializer (const Expr * Init, unsigned I) inline protected
Visits an initializer for a global.
Definition at line 211 of file ByteCodeExprGen.h.
References clang::interp::Init(), and clang::interp::ByteCodeExprGen< Emitter >::visitInitializer().
VisitGNUNullExpr()
template<class Emitter > bool ByteCodeExprGen::VisitGNUNullExpr (const GNUNullExpr * E)
Definition at line 3426 of file ByteCodeExprGen.cpp.
References clang::Expr::getType(), clang::Type::isIntegerType(), and clang::T.
VisitImaginaryLiteral()
template<class Emitter > bool ByteCodeExprGen::VisitImaginaryLiteral (const ImaginaryLiteral * E)
Definition at line 481 of file ByteCodeExprGen.cpp.
References clang::ImaginaryLiteral::getSubExpr(), clang::Expr::getType(), and clang::Type::isAnyComplexType().
VisitImplicitValueInitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitImplicitValueInitExpr (const ImplicitValueInitExpr * E)
Definition at line 921 of file ByteCodeExprGen.cpp.
References clang::Type::getAs(), clang::Type::getAsArrayTypeUnsafe(), clang::Type::getAsRecordDecl(), clang::Expr::getType(), clang::Type::isArrayType(), clang::Type::isIncompleteArrayType(), clang::Decl::isInvalidDecl(), clang::Type::isRecordType(), clang::TagDecl::isUnion(), and clang::T.
visitInitializer()
template<class Emitter > bool ByteCodeExprGen::visitInitializer (const Expr * E) protected
Compiles an initializer.
This is like visit() but it will never create a variable and instead rely on a variable already having been created. visitInitializer() then relies on a pointer to this variable being on top of the stack.
Definition at line 2701 of file ByteCodeExprGen.cpp.
References clang::Expr::containsErrors(), and clang::Expr::getType().
Referenced by clang::interp::ByteCodeExprGen< Emitter >::visitGlobalInitializer(), clang::interp::ByteCodeExprGen< Emitter >::visitLocalInitializer(), and clang::interp::ByteCodeExprGen< Emitter >::visitThisInitializer().
visitInitList()
template<class Emitter > bool ByteCodeExprGen::visitInitList (ArrayRef< const Expr * > Inits, const Expr * ArrayFiller, const Expr * E) protected
Definition at line 1025 of file ByteCodeExprGen.cpp.
References clang::interp::Record::Field::Decl, clang::interp::Record::getBase(), clang::interp::Record::getField(), clang::interp::Record::getNumFields(), clang::Expr::getType(), clang::interp::Init(), clang::Type::isArrayType(), clang::Type::isRecordType(), clang::interp::Record::isUnion(), clang::FieldDecl::isUnnamedBitField(), clang::Type::isVoidType(), and clang::T.
VisitInitListExpr()
template<class Emitter > bool ByteCodeExprGen::VisitInitListExpr (const InitListExpr * E)
Definition at line 1277 of file ByteCodeExprGen.cpp.
References clang::InitListExpr::getArrayFiller(), and clang::InitListExpr::inits().
VisitIntegerLiteral()
template<class Emitter > bool ByteCodeExprGen::VisitIntegerLiteral (const IntegerLiteral * E)
Definition at line 465 of file ByteCodeExprGen.cpp.
References clang::interp::LE().
VisitLambdaExpr()
template<class Emitter > bool ByteCodeExprGen::VisitLambdaExpr (const LambdaExpr * E)
Definition at line 2080 of file ByteCodeExprGen.cpp.
References clang::LambdaExpr::capture_init_begin(), clang::interp::Record::fields(), clang::LambdaExpr::getLambdaClass(), clang::interp::Init(), P, and clang::T.
visitLocalInitializer()
template<class Emitter > bool clang::interp::ByteCodeExprGen< Emitter >::visitLocalInitializer (const Expr * Init, unsigned I) inline protected
Visits an initializer for a local.
Definition at line 197 of file ByteCodeExprGen.h.
References clang::interp::Init(), and clang::interp::ByteCodeExprGen< Emitter >::visitInitializer().
VisitLogicalBinOp()
template<class Emitter > bool ByteCodeExprGen::VisitLogicalBinOp (const BinaryOperator * E)
Definition at line 716 of file ByteCodeExprGen.cpp.
References clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::BinaryOperator::isLogicalOp(), clang::interp::PT_Bool, and clang::T.
VisitMaterializeTemporaryExpr()
template<class Emitter > bool ByteCodeExprGen::VisitMaterializeTemporaryExpr (const MaterializeTemporaryExpr * E)
Definition at line 1919 of file ByteCodeExprGen.cpp.
References clang::MaterializeTemporaryExpr::getLifetimeExtendedTemporaryDecl(), clang::MaterializeTemporaryExpr::getStorageDuration(), clang::MaterializeTemporaryExpr::getSubExpr(), IsStatic, P, and clang::SD_Static.
VisitMemberExpr()
template<class Emitter > bool ByteCodeExprGen::VisitMemberExpr (const MemberExpr * E)
Definition at line 1425 of file ByteCodeExprGen.cpp.
References clang::MemberExpr::getBase(), clang::interp::Record::getField(), clang::MemberExpr::getMemberDecl(), clang::DeclContext::getParent(), clang::Expr::isGLValue(), clang::Member, P, clang::interp::PT_Ptr, and clang::T.
VisitObjCBoolLiteralExpr()
template<class Emitter > bool ByteCodeExprGen::VisitObjCBoolLiteralExpr (const ObjCBoolLiteralExpr * E)
Definition at line 2435 of file ByteCodeExprGen.cpp.
References clang::ObjCBoolLiteralExpr::getValue().
VisitObjCBoxedExpr()
template<class Emitter > bool ByteCodeExprGen::VisitObjCBoxedExpr (const ObjCBoxedExpr * E)
Definition at line 2653 of file ByteCodeExprGen.cpp.
References clang::ObjCBoxedExpr::getSubExpr(), and clang::ObjCBoxedExpr::isExpressibleAsConstantInitializer().
VisitObjCStringLiteral()
template<class Emitter > bool ByteCodeExprGen::VisitObjCStringLiteral (const ObjCStringLiteral * E)
Definition at line 1641 of file ByteCodeExprGen.cpp.
References clang::ObjCStringLiteral::getString().
VisitOffsetOfExpr()
template<class Emitter > bool ByteCodeExprGen::VisitOffsetOfExpr (const OffsetOfExpr * E)
Definition at line 2325 of file ByteCodeExprGen.cpp.
References clang::OffsetOfNode::Array, clang::OffsetOfExpr::getComponent(), clang::OffsetOfExpr::getIndexExpr(), clang::OffsetOfExpr::getNumComponents(), clang::Expr::getType(), Node, clang::interp::PT_Sint64, and clang::T.
VisitOpaqueValueExpr()
template<class Emitter > bool ByteCodeExprGen::VisitOpaqueValueExpr (const OpaqueValueExpr * E)
Definition at line 1516 of file ByteCodeExprGen.cpp.
References clang::OpaqueValueExpr::getSourceExpr(), and clang::interp::PT_Ptr.
VisitPackIndexingExpr()
template<class Emitter > bool ByteCodeExprGen::VisitPackIndexingExpr (const PackIndexingExpr * E)
Definition at line 2556 of file ByteCodeExprGen.cpp.
References clang::PackIndexingExpr::getSelectedExpr().
VisitParenExpr()
template<class Emitter > bool ByteCodeExprGen::VisitParenExpr (const ParenExpr * E)
Definition at line 506 of file ByteCodeExprGen.cpp.
References clang::ParenExpr::getSubExpr().
VisitPointerArithBinOp()
template<class Emitter > bool ByteCodeExprGen::VisitPointerArithBinOp (const BinaryOperator * E)
Perform addition/subtraction of a pointer and an integer or subtraction of two pointers.
Definition at line 668 of file ByteCodeExprGen.cpp.
References clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), clang::Type::isIntegerType(), clang::Type::isPointerType(), and clang::interp::LT().
VisitPointerCompoundAssignOperator()
template<class Emitter > bool ByteCodeExprGen::VisitPointerCompoundAssignOperator (const CompoundAssignOperator * E)
Definition at line 1753 of file ByteCodeExprGen.cpp.
References clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), clang::Expr::getType(), and clang::interp::LT().
VisitPredefinedExpr()
template<class Emitter > bool ByteCodeExprGen::VisitPredefinedExpr (const PredefinedExpr * E)
Definition at line 2122 of file ByteCodeExprGen.cpp.
References clang::PredefinedExpr::getFunctionName().
VisitPseudoObjectExpr()
template<class Emitter > bool ByteCodeExprGen::VisitPseudoObjectExpr (const PseudoObjectExpr * E)
Definition at line 2531 of file ByteCodeExprGen.cpp.
References clang::PseudoObjectExpr::getResultExpr(), and clang::PseudoObjectExpr::semantics().
VisitRecoveryExpr()
template<class Emitter > bool ByteCodeExprGen::VisitRecoveryExpr (const RecoveryExpr * E)
Definition at line 2562 of file ByteCodeExprGen.cpp.
VisitRequiresExpr()
template<class Emitter > bool ByteCodeExprGen::VisitRequiresExpr (const RequiresExpr * E)
Definition at line 2508 of file ByteCodeExprGen.cpp.
References clang::Expr::getType(), clang::RequiresExpr::isSatisfied(), and clang::interp::PT_Bool.
VisitShuffleVectorExpr()
template<class Emitter > bool ByteCodeExprGen::VisitShuffleVectorExpr (const ShuffleVectorExpr * E)
Definition at line 2610 of file ByteCodeExprGen.cpp.
References clang::Type::castAs(), clang::VectorType::getElementType(), clang::ShuffleVectorExpr::getExpr(), clang::VectorType::getNumElements(), clang::ShuffleVectorExpr::getNumSubExprs(), clang::ShuffleVectorExpr::getShuffleMaskIdx(), clang::Expr::getType(), and clang::interp::PT_Ptr.
VisitSizeOfPackExpr()
template<class Emitter > bool ByteCodeExprGen::VisitSizeOfPackExpr (const SizeOfPackExpr * E)
Definition at line 2419 of file ByteCodeExprGen.cpp.
References clang::SizeOfPackExpr::getPackLength().
VisitSourceLocExpr()
template<class Emitter > bool ByteCodeExprGen::VisitSourceLocExpr (const SourceLocExpr * E)
Definition at line 2269 of file ByteCodeExprGen.cpp.
References clang::SourceLocExpr::EvaluateInContext(), clang::interp::Record::getField(), clang::APValue::getInt(), clang::APValue::getLValueBase(), clang::APValue::getLValuePath(), clang::interp::Record::getNumFields(), clang::Expr::getType(), clang::APValue::isInt(), clang::Type::isIntegerType(), clang::APValue::isLValue(), clang::Type::isPointerType(), P, and V.
VisitStringLiteral()
template<class Emitter > bool ByteCodeExprGen::VisitStringLiteral (const StringLiteral * E)
Definition at line 1584 of file ByteCodeExprGen.cpp.
References clang::StringLiteral::getCharByteWidth(), clang::StringLiteral::getCodeUnit(), clang::StringLiteral::getLength(), clang::Expr::getType(), clang::ConstantArrayType::getZExtSize(), min(), and P.
VisitSubstNonTypeTemplateParmExpr()
template<class Emitter > bool ByteCodeExprGen::VisitSubstNonTypeTemplateParmExpr (const SubstNonTypeTemplateParmExpr * E)
Definition at line 1288 of file ByteCodeExprGen.cpp.
References clang::SubstNonTypeTemplateParmExpr::getReplacement().
VisitSYCLUniqueStableNameExpr()
template<class Emitter > bool ByteCodeExprGen::VisitSYCLUniqueStableNameExpr (const SYCLUniqueStableNameExpr * E)
Definition at line 1647 of file ByteCodeExprGen.cpp.
References clang::SYCLUniqueStableNameExpr::ComputeName(), clang::StringLiteral::Create(), clang::SYCLUniqueStableNameExpr::getLocation(), clang::Normal, clang::Ordinary, P, and clang::QualType::withConst().
visitThisInitializer()
template<class Emitter > bool clang::interp::ByteCodeExprGen< Emitter >::visitThisInitializer (const Expr * I) inline protected
Visits a delegated initializer.
Definition at line 225 of file ByteCodeExprGen.h.
References clang::interp::ByteCodeExprGen< Emitter >::visitInitializer().
VisitTypeTraitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitTypeTraitExpr (const TypeTraitExpr * E)
Definition at line 2063 of file ByteCodeExprGen.cpp.
References clang::Expr::getType(), clang::TypeTraitExpr::getValue(), and clang::Type::isBooleanType().
VisitUnaryExprOrTypeTraitExpr()
template<class Emitter > bool ByteCodeExprGen::VisitUnaryExprOrTypeTraitExpr (const UnaryExprOrTypeTraitExpr * E)
Definition at line 1333 of file ByteCodeExprGen.cpp.
References AlignOfType(), clang::UnaryExprOrTypeTraitExpr::getArgumentExpr(), clang::Type::getAs(), clang::ASTContext::getDeclAlign(), clang::UnaryExprOrTypeTraitExpr::getKind(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::ASTContext::getTypeInfoDataSizeInChars(), clang::UnaryExprOrTypeTraitExpr::getTypeOfArgument(), clang::ASTContext::getTypeSizeInChars(), clang::Expr::IgnoreParens(), clang::UnaryExprOrTypeTraitExpr::isArgumentType(), clang::Type::isConstantSizeType(), clang::Type::isDependentType(), clang::Type::isFunctionType(), clang::Type::isSizelessVectorType(), clang::Type::isVoidType(), clang::CharUnits::One(), and clang::TypeInfoChars::Width.
VisitUnaryOperator()
template<class Emitter > bool ByteCodeExprGen::VisitUnaryOperator (const UnaryOperator * E)
Definition at line 3451 of file ByteCodeExprGen.cpp.
References clang::UnaryOperator::getOpcode(), clang::UnaryOperator::getSubExpr(), clang::Expr::getType(), clang::Type::isAnyComplexType(), clang::Expr::isGLValue(), clang::interp::isIntegralType(), clang::interp::PT_Bool, clang::interp::PT_Float, clang::interp::PT_FnPtr, clang::interp::PT_Ptr, and clang::T.
visitVarDecl()
template<class Emitter > bool ByteCodeExprGen::visitVarDecl (const VarDecl * VD) protected
Creates and initializes a variable from the given decl.
Definition at line 3092 of file ByteCodeExprGen.cpp.
References clang::VarDecl::getInit(), clang::ValueDecl::getType(), clang::interp::Init(), clang::QualType::isConstQualified(), clang::QualType::isNull(), Offset, P, and clang::interp::Context::shouldBeGloballyIndexed().
Friends And Related Function Documentation
ArrayIndexScope< Emitter >
template<class Emitter > friend class ArrayIndexScope< Emitter > friend
Definition at line 245 of file ByteCodeExprGen.h.
DeclScope< Emitter >
template<class Emitter > friend class DeclScope< Emitter > friend
Definition at line 245 of file ByteCodeExprGen.h.
DestructorScope< Emitter >
template<class Emitter > friend class DestructorScope< Emitter > friend
Definition at line 245 of file ByteCodeExprGen.h.
LocalScope< Emitter >
template<class Emitter > friend class LocalScope< Emitter > friend
Definition at line 245 of file ByteCodeExprGen.h.
OptionScope< Emitter >
template<class Emitter > friend class OptionScope< Emitter > friend
Definition at line 245 of file ByteCodeExprGen.h.
SourceLocScope< Emitter >
template<class Emitter > friend class SourceLocScope< Emitter > friend
Definition at line 245 of file ByteCodeExprGen.h.
VariableScope< Emitter >
template<class Emitter > friend class VariableScope< Emitter > friend
Definition at line 245 of file ByteCodeExprGen.h.
Member Data Documentation
ArrayIndex
template<class Emitter > std::optional<uint64_t> clang::interp::ByteCodeExprGen< Emitter >::ArrayIndex protected
Current argument index. Needed to emit ArrayInitIndexExpr.
Definition at line 310 of file ByteCodeExprGen.h.
Ctx
template<class Emitter > Context& clang::interp::ByteCodeExprGen< Emitter >::Ctx protected
Current compilation context.
Definition at line 49 of file ByteCodeExprGen.h.
Referenced by clang::interp::ByteCodeExprGen< Emitter >::classify().
DiscardResult
template<class Emitter > bool clang::interp::ByteCodeExprGen< Emitter >::DiscardResult = false protected
Flag indicating if return value is to be discarded.
Definition at line 316 of file ByteCodeExprGen.h.
Referenced by clang::interp::OptionScope< Emitter >::OptionScope().
GlobalDecl
template<class Emitter > bool clang::interp::ByteCodeExprGen< Emitter >::GlobalDecl = false protected
Flag indicating if we're initializing a global variable.
Definition at line 323 of file ByteCodeExprGen.h.
Referenced by clang::interp::DeclScope< Emitter >::DeclScope().
Initializing
template<class Emitter > bool clang::interp::ByteCodeExprGen< Emitter >::Initializing = false protected
Flag inidicating if we're initializing an already created variable.
This is set in visitInitializer().
Definition at line 320 of file ByteCodeExprGen.h.
Referenced by clang::interp::OptionScope< Emitter >::OptionScope().
Locals
template<class Emitter > llvm::DenseMap<const ValueDecl *, Scope::Local> clang::interp::ByteCodeExprGen< Emitter >::Locals protected
Variable to storage mapping.
Definition at line 301 of file ByteCodeExprGen.h.
OpaqueExprs
template<class Emitter > llvm::DenseMap<const OpaqueValueExpr *, unsigned> clang::interp::ByteCodeExprGen< Emitter >::OpaqueExprs protected
OpaqueValueExpr to location mapping.
Definition at line 304 of file ByteCodeExprGen.h.
P
template<class Emitter > Program& clang::interp::ByteCodeExprGen< Emitter >::P protected
Program to link to.
Definition at line 51 of file ByteCodeExprGen.h.
SourceLocDefaultExpr
template<class Emitter > const Expr* clang::interp::ByteCodeExprGen< Emitter >::SourceLocDefaultExpr = nullptr protected
DefaultInit- or DefaultArgExpr, needed for SourceLocExpr.
Definition at line 313 of file ByteCodeExprGen.h.
Referenced by clang::interp::SourceLocScope< Emitter >::SourceLocScope().
VarScope
template<class Emitter > VariableScope<Emitter>* clang::interp::ByteCodeExprGen< Emitter >::VarScope = nullptr protected
Current scope.
Definition at line 307 of file ByteCodeExprGen.h.
Referenced by clang::interp::VariableScope< Emitter >::VariableScope().
The documentation for this class was generated from the following files:
lib/AST/Interp/ByteCodeExprGen.h
lib/AST/Interp/ByteCodeExprGen.cpp