clang: clang::extractapi::SymbolGraphSerializer Class Reference
clang::extractapi::SymbolGraphSerializer Class Reference
The visitor that organizes API information in the Symbol Graph format.
#include "clang/ExtractAPI/Serialization/SymbolGraphSerializer.h"
Public Types
enum RelationshipKind { MemberOf , InheritsFrom , ConformsTo , ExtensionTo }
The kind of a relationship between two symbols.
enum ConstraintKind { Conformance , ConditionalConformance }
Public Member Functions
Object serialize ()
Serialize the APIs in APISet in the Symbol Graph format.
void serialize (raw_ostream &os)
Wrap serialize(void) and write out the serialized JSON object to os.
void visitNamespaceRecord (const NamespaceRecord &Record)
void visitGlobalFunctionRecord (const GlobalFunctionRecord &Record)
Visit a global function record.
void visitGlobalVariableRecord (const GlobalVariableRecord &Record)
Visit a global variable record.
void visitEnumRecord (const EnumRecord &Record)
Visit an enum record.
void visitRecordRecord (const RecordRecord &Record)
Visit a record record.
void visitStaticFieldRecord (const StaticFieldRecord &Record)
void visitCXXClassRecord (const CXXClassRecord &Record)
void visitClassTemplateRecord (const ClassTemplateRecord &Record)
void visitClassTemplateSpecializationRecord (const ClassTemplateSpecializationRecord &Record)
void visitClassTemplatePartialSpecializationRecord (const ClassTemplatePartialSpecializationRecord &Record)
void visitCXXInstanceMethodRecord (const CXXInstanceMethodRecord &Record)
void visitCXXStaticMethodRecord (const CXXStaticMethodRecord &Record)
void visitMethodTemplateRecord (const CXXMethodTemplateRecord &Record)
void visitMethodTemplateSpecializationRecord (const CXXMethodTemplateSpecializationRecord &Record)
void visitCXXFieldRecord (const CXXFieldRecord &Record)
void visitCXXFieldTemplateRecord (const CXXFieldTemplateRecord &Record)
void visitConceptRecord (const ConceptRecord &Record)
void visitGlobalVariableTemplateRecord (const GlobalVariableTemplateRecord &Record)
void visitGlobalVariableTemplateSpecializationRecord (const GlobalVariableTemplateSpecializationRecord &Record)
void visitGlobalVariableTemplatePartialSpecializationRecord (const GlobalVariableTemplatePartialSpecializationRecord &Record)
void visitGlobalFunctionTemplateRecord (const GlobalFunctionTemplateRecord &Record)
void visitGlobalFunctionTemplateSpecializationRecord (const GlobalFunctionTemplateSpecializationRecord &Record)
void visitObjCContainerRecord (const ObjCContainerRecord &Record)
Visit an Objective-C container record.
void visitObjCCategoryRecord (const ObjCCategoryRecord &Record)
Visit an Objective-C category record.
void visitMacroDefinitionRecord (const MacroDefinitionRecord &Record)
Visit a macro definition record.
void visitTypedefRecord (const TypedefRecord &Record)
Visit a typedef record.
void serializeSingleRecord (const APIRecord *Record)
Serialize a single record.
SymbolGraphSerializer (const APISet &API, const APIIgnoresList &IgnoresList, SymbolGraphSerializerOption Options={}, bool ShouldRecurse=true)
Public Member Functions inherited from clang::extractapi::APISetVisitor< SymbolGraphSerializer >
void traverseAPISet ()
void traverseNamespaces ()
void traverseGlobalFunctionRecords ()
void traverseGlobalVariableRecords ()
void traverseEnumRecords ()
void traverseRecordRecords ()
void traverseStaticFieldRecords ()
void traverseCXXClassRecords ()
void traverseCXXMethodTemplates ()
void traverseCXXMethodTemplateSpecializations ()
void traverseClassTemplateRecords ()
void traverseClassTemplateSpecializationRecords ()
void traverseClassTemplatePartialSpecializationRecords ()
void traverseCXXInstanceMethods ()
void traverseCXXStaticMethods ()
void traverseCXXFields ()
void traverseCXXFieldTemplates ()
void traverseGlobalVariableTemplateRecords ()
void traverseGlobalVariableTemplateSpecializationRecords ()
void traverseGlobalVariableTemplatePartialSpecializationRecords ()
void traverseGlobalFunctionTemplateRecords ()
void traverseGlobalFunctionTemplateSpecializationRecords ()
void traverseConcepts ()
void traverseObjCInterfaces ()
void traverseObjCProtocols ()
void traverseObjCCategories ()
void traverseMacroDefinitionRecords ()
void traverseTypedefRecords ()
void visitNamespaceRecord (const NamespaceRecord &Record)
void visitGlobalFunctionRecord (const GlobalFunctionRecord &Record)
Visit a global function record.
void visitGlobalVariableRecord (const GlobalVariableRecord &Record)
Visit a global variable record.
void visitEnumRecord (const EnumRecord &Record)
Visit an enum record.
void visitRecordRecord (const RecordRecord &Record)
Visit a record record.
void visitStaticFieldRecord (const StaticFieldRecord &Record)
void visitCXXClassRecord (const CXXClassRecord &Record)
void visitClassTemplateRecord (const ClassTemplateRecord &Record)
void visitClassTemplateSpecializationRecord (const ClassTemplateSpecializationRecord &Record)
void visitClassTemplatePartialSpecializationRecord (const ClassTemplatePartialSpecializationRecord &Record)
void visitCXXInstanceRecord (const CXXInstanceMethodRecord &Record)
void visitCXXStaticRecord (const CXXStaticMethodRecord &Record)
void visitMethodTemplateRecord (const CXXMethodTemplateRecord &Record)
void visitMethodTemplateSpecializationRecord (const CXXMethodTemplateSpecializationRecord &Record)
void visitCXXFieldTemplateRecord (const CXXFieldTemplateRecord &Record)
void visitGlobalVariableTemplateRecord (const GlobalVariableTemplateRecord &Record)
void visitGlobalVariableTemplateSpecializationRecord (const GlobalVariableTemplateSpecializationRecord &Record)
void visitGlobalVariableTemplatePartialSpecializationRecord (const GlobalVariableTemplatePartialSpecializationRecord &Record)
void visitGlobalFunctionTemplateRecord (const GlobalFunctionTemplateRecord &Record)
void visitGlobalFunctionTemplateSpecializationRecord (const GlobalFunctionTemplateSpecializationRecord &Record)
void visitObjCContainerRecord (const ObjCContainerRecord &Record)
Visit an Objective-C container record.
void visitObjCCategoryRecord (const ObjCCategoryRecord &Record)
Visit an Objective-C category record.
void visitMacroDefinitionRecord (const MacroDefinitionRecord &Record)
Visit a macro definition record.
void visitTypedefRecord (const TypedefRecord &Record)
Visit a typedef record.
APISetVisitor ()=delete
APISetVisitor (const APISetVisitor &)=delete
APISetVisitor (APISetVisitor &&)=delete
APISetVisitor & operator= (const APISetVisitor &)=delete
APISetVisitor & operator= (APISetVisitor &&)=delete
Static Public Member Functions
static std::optional< Object > serializeSingleSymbolSGF (StringRef USR, const APISet &API)
Serialize a single symbol SGF.
static StringRef getRelationshipString (RelationshipKind Kind)
Get the string representation of the relationship kind.
static StringRef getConstraintString (ConstraintKind Kind)
Protected Attributes
const APIIgnoresList & IgnoresList
The list of symbols to ignore.
SymbolGraphSerializerOption Options
llvm::StringSet visitedCategories
Protected Attributes inherited from clang::extractapi::APISetVisitor< SymbolGraphSerializer >
const APISet & API
Additional Inherited Members
Protected Member Functions inherited from clang::extractapi::APISetVisitor< SymbolGraphSerializer >
APISetVisitor (const APISet &API)
~APISetVisitor ()=default
SymbolGraphSerializer * getDerived ()
Detailed Description
The visitor that organizes API information in the Symbol Graph format.
The Symbol Graph format (https://github.com/apple/swift-docc-symbolkit) models an API set as a directed graph, where nodes are symbol declarations, and edges are relationships between the connected symbols.
Definition at line 46 of file SymbolGraphSerializer.h.
Member Enumeration Documentation
ConstraintKind
enum clang::extractapi::SymbolGraphSerializer::ConstraintKind
Enumerator
Conformance
ConditionalConformance
Definition at line 100 of file SymbolGraphSerializer.h.
RelationshipKind
enum clang::extractapi::SymbolGraphSerializer::RelationshipKind
The kind of a relationship between two symbols.
Enumerator
MemberOf
The source symbol is a member of the target symbol.
For example enum constants are members of the enum, class/instance methods are members of the class, etc.
InheritsFrom
The source symbol is inherited from the target symbol.
ConformsTo
The source symbol conforms to the target symbol.
For example Objective-C protocol conformances.
ExtensionTo
The source symbol is an extension to the target symbol.
For example Objective-C categories extending an external type.
Definition at line 79 of file SymbolGraphSerializer.h.
Constructor & Destructor Documentation
SymbolGraphSerializer()
clang::extractapi::SymbolGraphSerializer::SymbolGraphSerializer (const APISet & API, const APIIgnoresList & IgnoresList, SymbolGraphSerializerOption Options = {}, bool ShouldRecurse = true) inline
Definition at line 233 of file SymbolGraphSerializer.h.
Member Function Documentation
getConstraintString()
StringRef SymbolGraphSerializer::getConstraintString (ConstraintKind Kind) static
Definition at line 818 of file SymbolGraphSerializer.cpp.
getRelationshipString()
StringRef SymbolGraphSerializer::getRelationshipString (RelationshipKind Kind) static
Get the string representation of the relationship kind.
Definition at line 804 of file SymbolGraphSerializer.cpp.
serialize() [1/2]
Object SymbolGraphSerializer::serialize (void)
Serialize the APIs in APISet in the Symbol Graph format.
Returns
a JSON object that contains the root of the formatted Symbol Graph.
Definition at line 1230 of file SymbolGraphSerializer.cpp.
Referenced by clang::ExtractAPIActionBase::ImplEndSourceFileAction().
serialize() [2/2]
void SymbolGraphSerializer::serialize (raw_ostream & os)
Wrap serialize(void) and write out the serialized JSON object to os.
Definition at line 1246 of file SymbolGraphSerializer.cpp.
serializeSingleRecord()
void SymbolGraphSerializer::serializeSingleRecord (const APIRecord * Record)
Serialize a single record.
Definition at line 1160 of file SymbolGraphSerializer.cpp.
References clang::extractapi::APIRecord::RK_CXXClass, clang::extractapi::APIRecord::RK_Enum, clang::extractapi::APIRecord::RK_GlobalFunction, clang::extractapi::APIRecord::RK_GlobalVariable, clang::extractapi::APIRecord::RK_MacroDefinition, clang::extractapi::APIRecord::RK_ObjCCategory, clang::extractapi::APIRecord::RK_ObjCInterface, clang::extractapi::APIRecord::RK_ObjCProtocol, clang::extractapi::APIRecord::RK_StaticField, clang::extractapi::APIRecord::RK_Struct, clang::extractapi::APIRecord::RK_Typedef, clang::extractapi::APIRecord::RK_Union, and clang::extractapi::APIRecord::RK_Unknown.
Referenced by serializeSingleSymbolSGF().
serializeSingleSymbolSGF()
std::optional< Object > SymbolGraphSerializer::serializeSingleSymbolSGF (StringRef USR, const APISet & API) static
Serialize a single symbol SGF.
This is primarily used for libclang.
Returns
an optional JSON Object representing the payload that libclang expects for providing symbol information for a single symbol. If this is not a known symbol returns std::nullopt.
Definition at line 1255 of file SymbolGraphSerializer.cpp.
References Array, clang::extractapi::APISet::findRecordForUSR(), clang::PresumedLoc::getFilename(), clang::extractapi::APISet::getLanguage(), clang::format::getLanguageName(), clang::extractapi::APIRecord::IsFromSystemHeader, clang::extractapi::APIRecord::Location, clang::extractapi::APISet::ProductName, serializeSingleRecord(), and clang::extractapi::APIRecord::USR.
visitClassTemplatePartialSpecializationRecord()
void SymbolGraphSerializer::visitClassTemplatePartialSpecializationRecord (const ClassTemplatePartialSpecializationRecord & Record)
Definition at line 938 of file SymbolGraphSerializer.cpp.
References clang::Class.
visitClassTemplateRecord()
void SymbolGraphSerializer::visitClassTemplateRecord (const ClassTemplateRecord & Record)
Definition at line 909 of file SymbolGraphSerializer.cpp.
References clang::Class.
visitClassTemplateSpecializationRecord()
void SymbolGraphSerializer::visitClassTemplateSpecializationRecord (const ClassTemplateSpecializationRecord & Record)
Definition at line 923 of file SymbolGraphSerializer.cpp.
References clang::Class.
visitConceptRecord()
void SymbolGraphSerializer::visitConceptRecord (const ConceptRecord & Record)
Definition at line 1025 of file SymbolGraphSerializer.cpp.
visitCXXClassRecord()
void SymbolGraphSerializer::visitCXXClassRecord (const CXXClassRecord & Record)
Definition at line 896 of file SymbolGraphSerializer.cpp.
References clang::Class.
visitCXXFieldRecord()
void SymbolGraphSerializer::visitCXXFieldRecord (const CXXFieldRecord & Record)
Definition at line 1001 of file SymbolGraphSerializer.cpp.
visitCXXFieldTemplateRecord()
void SymbolGraphSerializer::visitCXXFieldTemplateRecord (const CXXFieldTemplateRecord & Record)
Definition at line 1012 of file SymbolGraphSerializer.cpp.
visitCXXInstanceMethodRecord()
void SymbolGraphSerializer::visitCXXInstanceMethodRecord (const CXXInstanceMethodRecord & Record)
Definition at line 953 of file SymbolGraphSerializer.cpp.
visitCXXStaticMethodRecord()
void SymbolGraphSerializer::visitCXXStaticMethodRecord (const CXXStaticMethodRecord & Record)
Definition at line 964 of file SymbolGraphSerializer.cpp.
visitEnumRecord()
void SymbolGraphSerializer::visitEnumRecord (const EnumRecord & Record)
Visit an enum record.
Definition at line 869 of file SymbolGraphSerializer.cpp.
visitGlobalFunctionRecord()
void SymbolGraphSerializer::visitGlobalFunctionRecord (const GlobalFunctionRecord & Record)
Visit a global function record.
Definition at line 851 of file SymbolGraphSerializer.cpp.
visitGlobalFunctionTemplateRecord()
void SymbolGraphSerializer::visitGlobalFunctionTemplateRecord (const GlobalFunctionTemplateRecord & Record)
Definition at line 1058 of file SymbolGraphSerializer.cpp.
visitGlobalFunctionTemplateSpecializationRecord()
void SymbolGraphSerializer::visitGlobalFunctionTemplateSpecializationRecord (const GlobalFunctionTemplateSpecializationRecord & Record)
Definition at line 1066 of file SymbolGraphSerializer.cpp.
visitGlobalVariableRecord()
void SymbolGraphSerializer::visitGlobalVariableRecord (const GlobalVariableRecord & Record)
Visit a global variable record.
Definition at line 860 of file SymbolGraphSerializer.cpp.
visitGlobalVariableTemplatePartialSpecializationRecord()
void SymbolGraphSerializer::visitGlobalVariableTemplatePartialSpecializationRecord (const GlobalVariableTemplatePartialSpecializationRecord & Record)
Definition at line 1049 of file SymbolGraphSerializer.cpp.
visitGlobalVariableTemplateRecord()
void SymbolGraphSerializer::visitGlobalVariableTemplateRecord (const GlobalVariableTemplateRecord & Record)
Definition at line 1033 of file SymbolGraphSerializer.cpp.
visitGlobalVariableTemplateSpecializationRecord()
void SymbolGraphSerializer::visitGlobalVariableTemplateSpecializationRecord (const GlobalVariableTemplateSpecializationRecord & Record)
Definition at line 1041 of file SymbolGraphSerializer.cpp.
visitMacroDefinitionRecord()
void SymbolGraphSerializer::visitMacroDefinitionRecord (const MacroDefinitionRecord & Record)
Visit a macro definition record.
Definition at line 1150 of file SymbolGraphSerializer.cpp.
visitMethodTemplateRecord()
void SymbolGraphSerializer::visitMethodTemplateRecord (const CXXMethodTemplateRecord & Record)
Definition at line 975 of file SymbolGraphSerializer.cpp.
visitMethodTemplateSpecializationRecord()
void SymbolGraphSerializer::visitMethodTemplateSpecializationRecord (const CXXMethodTemplateSpecializationRecord & Record)
Definition at line 988 of file SymbolGraphSerializer.cpp.
visitNamespaceRecord()
void SymbolGraphSerializer::visitNamespaceRecord (const NamespaceRecord & Record)
Definition at line 840 of file SymbolGraphSerializer.cpp.
visitObjCCategoryRecord()
void SymbolGraphSerializer::visitObjCCategoryRecord (const ObjCCategoryRecord & Record)
Visit an Objective-C category record.
Definition at line 1111 of file SymbolGraphSerializer.cpp.
References clang::extractapi::APISet::getLanguage(), and clang::extractapi::APIRecord::RK_ObjCCategoryModule.
visitObjCContainerRecord()
void SymbolGraphSerializer::visitObjCContainerRecord (const ObjCContainerRecord & Record)
Visit an Objective-C container record.
Definition at line 1074 of file SymbolGraphSerializer.cpp.
References Category.
visitRecordRecord()
void SymbolGraphSerializer::visitRecordRecord (const RecordRecord & Record)
Visit a record record.
Definition at line 878 of file SymbolGraphSerializer.cpp.
visitStaticFieldRecord()
void SymbolGraphSerializer::visitStaticFieldRecord (const StaticFieldRecord & Record)
Definition at line 887 of file SymbolGraphSerializer.cpp.
visitTypedefRecord()
void SymbolGraphSerializer::visitTypedefRecord (const TypedefRecord & Record)
Visit a typedef record.
Definition at line 1211 of file SymbolGraphSerializer.cpp.
Member Data Documentation
IgnoresList
const APIIgnoresList& clang::extractapi::SymbolGraphSerializer::IgnoresList protected
The list of symbols to ignore.
Note: This should be consulted before emitting a symbol.
Definition at line 155 of file SymbolGraphSerializer.h.
Options
SymbolGraphSerializerOption clang::extractapi::SymbolGraphSerializer::Options protected
Definition at line 157 of file SymbolGraphSerializer.h.
visitedCategories
llvm::StringSet clang::extractapi::SymbolGraphSerializer::visitedCategories protected
Definition at line 159 of file SymbolGraphSerializer.h.
The documentation for this class was generated from the following files:
include/clang/ExtractAPI/Serialization/SymbolGraphSerializer.h
lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp