clang: clang::ObjCListBase Class Reference
clang::ObjCListBase Class Reference
#include "clang/AST/DeclObjC.h"
Public Member Functions
ObjCListBase ()=default
ObjCListBase (const ObjCListBase &)=delete
ObjCListBase & operator= (const ObjCListBase &)=delete
unsigned size () const
bool empty () const
Protected Member Functions
void set (void *const *InList, unsigned Elts, ASTContext &Ctx)
Protected Attributes
void ** List = nullptr
List is an array of pointers to objects that are not owned by this object.
unsigned NumElts = 0
Detailed Description
Definition at line 60 of file DeclObjC.h.
Constructor & Destructor Documentation
ObjCListBase() [1/2]
clang::ObjCListBase::ObjCListBase () default
ObjCListBase() [2/2]
clang::ObjCListBase::ObjCListBase (const ObjCListBase &) delete
Member Function Documentation
empty()
bool clang::ObjCListBase::empty () const inline
Definition at line 72 of file DeclObjC.h.
References NumElts.
Referenced by rewriteToObjCInterfaceDecl().
operator=()
ObjCListBase& clang::ObjCListBase::operator= (const ObjCListBase &) delete
set()
void ObjCListBase::set (void *const * InList, unsigned Elts, ASTContext & Ctx) protected
Definition at line 45 of file DeclObjC.cpp.
References List, memcpy(), and NumElts.
Referenced by clang::ObjCList< clang::ObjCProtocolDecl >::set().
size()
unsigned clang::ObjCListBase::size () const inline
Definition at line 71 of file DeclObjC.h.
References NumElts.
Referenced by clang::ObjCProtocolList::loc_end(), and clang::ObjCCategoryDecl::protocol_size().
Member Data Documentation
List
void** clang::ObjCListBase::List = nullptr protected
List is an array of pointers to objects that are not owned by this object.
Definition at line 63 of file DeclObjC.h.
Referenced by clang::ObjCList< clang::ObjCProtocolDecl >::begin(), clang::ObjCList< clang::ObjCProtocolDecl >::end(), clang::ObjCList< clang::ObjCProtocolDecl >::operator[](), and set().
NumElts
unsigned clang::ObjCListBase::NumElts = 0 protected
Definition at line 64 of file DeclObjC.h.
Referenced by empty(), clang::ObjCList< clang::ObjCProtocolDecl >::end(), clang::ObjCList< clang::ObjCProtocolDecl >::operator[](), set(), and size().
The documentation for this class was generated from the following files:
include/clang/AST/DeclObjC.h
lib/AST/DeclObjC.cpp