clang: clang::SemaRISCV Class Reference
clang::SemaRISCV Class Reference
#include "clang/Sema/SemaRISCV.h"
Public Member Functions
SemaRISCV (Sema &S)
bool CheckLMUL (CallExpr *TheCall, unsigned ArgNum)
bool CheckBuiltinFunctionCall (const TargetInfo &TI, unsigned BuiltinID, CallExpr *TheCall)
void checkRVVTypeSupport (QualType Ty, SourceLocation Loc, Decl *D, const llvm::StringMap< bool > &FeatureMap)
bool isValidRVVBitcast (QualType srcType, QualType destType)
Are the two types RVV-bitcast-compatible types? I.e.
void handleInterruptAttr (Decl *D, const ParsedAttr &AL)
bool isAliasValid (unsigned BuiltinID, StringRef AliasName)
Public Member Functions inherited from clang::SemaBase
SemaBase (Sema &S)
ASTContext & getASTContext () const
DiagnosticsEngine & getDiagnostics () const
const LangOptions & getLangOpts () const
void addFDToReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
bool isFDReachableFromSyclDevice (const FunctionDecl *Callee, const FunctionDecl *Caller)
SemaDiagnosticBuilder Diag (SourceLocation Loc, unsigned DiagID, bool DeferHint=false)
Emit a diagnostic.
SemaDiagnosticBuilder Diag (SourceLocation Loc, const PartialDiagnostic &PD, bool DeferHint=false)
Emit a partial diagnostic.
PartialDiagnostic PDiag (unsigned DiagID=0)
Build a partial diagnostic.
Public Attributes
bool DeclareRVVBuiltins = false
Indicate RISC-V vector builtin functions enabled or not.
bool DeclareSiFiveVectorBuiltins = false
Indicate RISC-V SiFive vector builtin functions enabled or not.
std::unique_ptr< sema::RISCVIntrinsicManager > IntrinsicManager
Public Attributes inherited from clang::SemaBase
Sema & SemaRef
Additional Inherited Members
Public Types inherited from clang::SemaBase
enum class DeviceDiagnosticReason {
None = 0 , OmpDevice = 1 << 0 , OmpHost = 1 << 1 , OmpAll = OmpDevice | OmpHost ,
CudaDevice = 1 << 2 , CudaHost = 1 << 3 , CudaAll = CudaDevice | CudaHost , Sycl = 1 << 4 ,
Esimd = 1 << 5 , All = OmpAll | CudaAll | Sycl | Esimd
}
Bitmask to contain the list of reasons a single diagnostic should be emitted, based on its language.
Detailed Description
Definition at line 29 of file SemaRISCV.h.
Constructor & Destructor Documentation
SemaRISCV()
clang::SemaRISCV::SemaRISCV (Sema & S)
Definition at line 1489 of file SemaRISCV.cpp.
Member Function Documentation
CheckBuiltinFunctionCall()
bool clang::SemaRISCV::CheckBuiltinFunctionCall (const TargetInfo & TI, unsigned BuiltinID, CallExpr * TheCall)
Definition at line 559 of file SemaRISCV.cpp.
CheckLMUL()
bool clang::SemaRISCV::CheckLMUL (CallExpr * TheCall, unsigned ArgNum)
Definition at line 509 of file SemaRISCV.cpp.
References Diag(), clang::CallExpr::getArg(), clang::CallExpr::getBeginLoc(), clang::Stmt::getSourceRange(), clang::Expr::isTypeDependent(), and clang::Expr::isValueDependent().
checkRVVTypeSupport()
void clang::SemaRISCV::checkRVVTypeSupport (QualType Ty, SourceLocation Loc, Decl * D, const llvm::StringMap< bool > & FeatureMap)
Definition at line 1374 of file SemaRISCV.cpp.
References clang::Type::castAs(), D, Diag(), clang::ASTContext::BuiltinVectorTypeInfo::EC, clang::ASTContext::BuiltinVectorTypeInfo::ElementType, clang::RISCV::Float, clang::Type::isBFloat16Type(), clang::Type::isFloat16Type(), clang::Type::isIntegerType(), clang::Type::isSpecificBuiltinType(), and Loc.
handleInterruptAttr()
void clang::SemaRISCV::handleInterruptAttr (Decl * D, const ParsedAttr & AL)
Definition at line 1426 of file SemaRISCV.cpp.
References clang::Decl::addAttr(), clang::ParsedAttr::checkAtMostNumArgs(), D, Diag(), clang::ExpectedFunction, clang::Decl::getAttr(), clang::SourceRange::getBegin(), clang::getFunctionOrMethodNumParams(), clang::getFunctionOrMethodResultType(), clang::Decl::getFunctionType(), clang::AttributeCommonInfo::getLoc(), clang::Decl::getLocation(), clang::ParsedAttr::getNumArgs(), clang::AttributeCommonInfo::getRange(), clang::hasFunctionProto(), clang::AttributeCommonInfo::isRegularKeywordAttribute(), and Kind.
isAliasValid()
bool clang::SemaRISCV::isAliasValid (unsigned BuiltinID, StringRef AliasName)
Definition at line 1484 of file SemaRISCV.cpp.
References clang::RISCV::FirstRVVBuiltin, and clang::RISCV::LastRVVBuiltin.
isValidRVVBitcast()
bool clang::SemaRISCV::isValidRVVBitcast (QualType srcTy, QualType destTy)
Are the two types RVV-bitcast-compatible types? I.e.
is bitcasting from the first RVV type (e.g. an RVV scalable type) to the second type (e.g. an RVV VLS type) allowed?
This will also return false if the two given types do not make sense from the perspective of RVV bitcasts.
Definition at line 1411 of file SemaRISCV.cpp.
References clang::VectorType::getVectorKind(), clang::Type::isRVVSizelessBuiltinType(), and clang::Type::isVectorType().
Member Data Documentation
DeclareRVVBuiltins
bool clang::SemaRISCV::DeclareRVVBuiltins = false
Indicate RISC-V vector builtin functions enabled or not.
Definition at line 45 of file SemaRISCV.h.
DeclareSiFiveVectorBuiltins
bool clang::SemaRISCV::DeclareSiFiveVectorBuiltins = false
Indicate RISC-V SiFive vector builtin functions enabled or not.
Definition at line 48 of file SemaRISCV.h.
IntrinsicManager
std::unique_ptr<sema::RISCVIntrinsicManager> clang::SemaRISCV::IntrinsicManager
Definition at line 50 of file SemaRISCV.h.
The documentation for this class was generated from the following files:
include/clang/Sema/SemaRISCV.h
lib/Sema/SemaRISCV.cpp