clang: clang::BitsPacker Class Reference
clang::BitsPacker Class Reference
A simple helper class to pack several bits in order into (a) 32 bit integer(s).
#include "clang/Serialization/ASTWriter.h"
Public Member Functions
BitsPacker ()=default
BitsPacker (const BitsPacker &)=delete
BitsPacker (BitsPacker &&)=delete
BitsPacker operator= (const BitsPacker &)=delete
BitsPacker operator= (BitsPacker &&)=delete
~BitsPacker ()=default
bool canWriteNextNBits (uint32_t BitsWidth) const
void reset (uint32_t Value)
void addBit (bool Value)
void addBits (uint32_t Value, uint32_t BitsWidth)
operator uint32_t ()
Detailed Description
A simple helper class to pack several bits in order into (a) 32 bit integer(s).
Definition at line 950 of file ASTWriter.h.
Constructor & Destructor Documentation
BitsPacker() [1/3]
clang::BitsPacker::BitsPacker () default
BitsPacker() [2/3]
clang::BitsPacker::BitsPacker (const BitsPacker &) delete
BitsPacker() [3/3]
clang::BitsPacker::BitsPacker (BitsPacker &&) delete
~BitsPacker()
clang::BitsPacker::~BitsPacker () default
Member Function Documentation
addBit()
void clang::BitsPacker::addBit (bool Value) inline
Definition at line 970 of file ASTWriter.h.
References addBits().
Referenced by clang::ASTRecordWriter::AddCXXDefinitionData(), clang::ASTDeclWriter::VisitDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::ASTDeclWriter::VisitNamespaceDecl(), clang::ASTDeclWriter::VisitParmVarDecl(), clang::ASTDeclWriter::VisitRecordDecl(), clang::ASTDeclWriter::VisitTagDecl(), and clang::ASTDeclWriter::VisitVarDecl().
addBits()
void clang::BitsPacker::addBits (uint32_t Value, uint32_t BitsWidth) inline
Definition at line 971 of file ASTWriter.h.
References canWriteNextNBits().
Referenced by addBit(), clang::ASTRecordWriter::AddCXXDefinitionData(), clang::ASTDeclWriter::VisitDecl(), clang::ASTDeclWriter::VisitEnumDecl(), clang::ASTDeclWriter::VisitFunctionDecl(), clang::ASTDeclWriter::VisitParmVarDecl(), clang::ASTDeclWriter::VisitRecordDecl(), clang::ASTDeclWriter::VisitTagDecl(), and clang::ASTDeclWriter::VisitVarDecl().
canWriteNextNBits()
bool clang::BitsPacker::canWriteNextNBits (uint32_t BitsWidth) const inline
Definition at line 961 of file ASTWriter.h.
Referenced by addBits().
operator uint32_t()
clang::BitsPacker::operator uint32_t () inline
Definition at line 981 of file ASTWriter.h.
operator=() [1/2]
BitsPacker clang::BitsPacker::operator= (BitsPacker &&) delete
operator=() [2/2]
BitsPacker clang::BitsPacker::operator= (const BitsPacker &) delete
reset()
void clang::BitsPacker::reset (uint32_t Value) inline
Definition at line 965 of file ASTWriter.h.
The documentation for this class was generated from the following file:
include/clang/Serialization/ASTWriter.h