clang: clang::FixItAction Class Reference
clang::FixItAction Class Reference
#include "clang/Rewrite/Frontend/FrontendActions.h"
Public Member Functions
FixItAction ()
~FixItAction () override
Public Member Functions inherited from clang::ASTFrontendAction
ASTFrontendAction ()
bool usesPreprocessorOnly () const override
Does this action only use the preprocessor?
Public Member Functions inherited from clang::FrontendAction
FrontendAction ()
virtual ~FrontendAction ()
CompilerInstance & getCompilerInstance () const
void setCompilerInstance (CompilerInstance *Value)
bool isCurrentFileAST () const
const FrontendInputFile & getCurrentInput () const
StringRef getCurrentFile () const
StringRef getCurrentFileOrBufferName () const
InputKind getCurrentFileKind () const
ASTUnit & getCurrentASTUnit () const
Module * getCurrentModule () const
std::unique_ptr< ASTUnit > takeCurrentASTUnit ()
void setCurrentInput (const FrontendInputFile &CurrentInput, std::unique_ptr< ASTUnit > AST=nullptr)
virtual bool isModelParsingAction () const
Is this action invoked on a model file?
virtual TranslationUnitKind getTranslationUnitKind ()
For AST-based actions, the kind of translation unit we're handling.
virtual bool hasPCHSupport () const
Does this action support use with PCH?
virtual bool hasIRSupport () const
Does this action support use with IR files?
virtual bool hasCodeCompletionSupport () const
Does this action support use with code completion?
bool PrepareToExecute (CompilerInstance &CI)
Prepare the action to execute on the given compiler instance.
bool BeginSourceFile (CompilerInstance &CI, const FrontendInputFile &Input)
Prepare the action for processing the input file Input.
llvm::Error Execute ()
Set the source manager's main input file, and run the action.
virtual void EndSourceFile ()
Perform any per-file post processing, deallocate per-file objects, and run statistics and output file cleanup code.
Protected Member Functions
std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, StringRef InFile) override
Create the AST consumer object for this action, if supported.
bool BeginSourceFileAction (CompilerInstance &CI) override
Callback at the start of processing a single input.
void EndSourceFileAction () override
Callback at the end of processing a single input.
bool hasASTFileSupport () const override
Does this action support use with AST files?
Protected Member Functions inherited from clang::ASTFrontendAction
void ExecuteAction () override
Implement the ExecuteAction interface by running Sema on the already-initialized AST consumer.
Protected Member Functions inherited from clang::FrontendAction
virtual bool PrepareToExecuteAction (CompilerInstance &CI)
Prepare to execute the action on the given CompilerInstance.
virtual bool BeginInvocation (CompilerInstance &CI)
Callback before starting processing a single input, giving the opportunity to modify the CompilerInvocation or do some other action before BeginSourceFileAction is called.
virtual bool shouldEraseOutputFiles ()
Callback at the end of processing a single input, to determine if the output files should be erased or not.
Protected Attributes
std::unique_ptr< FixItRewriter > Rewriter
std::unique_ptr< FixItOptions > FixItOpts
Detailed Description
Definition at line 29 of file FrontendActions.h.
Constructor & Destructor Documentation
FixItAction()
FixItAction::FixItAction ()
Definition at line 48 of file FrontendActions.cpp.
~FixItAction()
FixItAction::~FixItAction () override
Definition at line 49 of file FrontendActions.cpp.
Member Function Documentation
BeginSourceFileAction()
bool FixItAction::BeginSourceFileAction (CompilerInstance & CI) override protected virtual
Callback at the start of processing a single input.
Returns
True on success; on failure ExecutionAction() and EndSourceFileAction() will not be called.
Reimplemented from clang::FrontendAction.
Definition at line 96 of file FrontendActions.cpp.
References FixItOpts, clang::FrontendOptions::FixItSuffix, clang::FrontendOptions::FixWhatYouCan, clang::FrontendAction::getCompilerInstance(), clang::CompilerInstance::getDiagnostics(), clang::CompilerInstance::getFrontendOpts(), clang::CompilerInstance::getLangOpts(), and clang::CompilerInstance::getSourceManager().
CreateASTConsumer()
std::unique_ptr< ASTConsumer > FixItAction::CreateASTConsumer (CompilerInstance & CI, StringRef InFile) override protected virtual
Create the AST consumer object for this action, if supported.
This routine is called as part of BeginSourceFile(), which will fail if the AST consumer cannot be created. This will not be called if the action has indicated that it only uses the preprocessor.
Parameters
CI - The current compiler instance, provided as a convenience, see getCompilerInstance().
InFile - The current input file, provided as a convenience, see getCurrentFile().
Returns
The new AST consumer, or null on failure.
Implements clang::FrontendAction.
Definition at line 52 of file FrontendActions.cpp.
EndSourceFileAction()
void FixItAction::EndSourceFileAction () override protected virtual
Callback at the end of processing a single input.
This is guaranteed to only be called following a successful call to BeginSourceFileAction (and BeginSourceFile).
Reimplemented from clang::FrontendAction.
Definition at line 110 of file FrontendActions.cpp.
hasASTFileSupport()
bool clang::FixItAction::hasASTFileSupport () const inline override protected virtual
Does this action support use with AST files?
Reimplemented from clang::FrontendAction.
Definition at line 41 of file FrontendActions.h.
Member Data Documentation
FixItOpts
std::unique_ptr<FixItOptions> clang::FixItAction::FixItOpts protected
Definition at line 32 of file FrontendActions.h.
Referenced by BeginSourceFileAction().
Rewriter
std::unique_ptr<FixItRewriter> clang::FixItAction::Rewriter protected
Definition at line 31 of file FrontendActions.h.
The documentation for this class was generated from the following files:
include/clang/Rewrite/Frontend/FrontendActions.h
lib/Frontend/Rewrite/FrontendActions.cpp