clang: clang::CodeGen::CGOpenMPRuntime::DisableAutoDeclareTargetRAII Class Reference
clang::CodeGen::CGOpenMPRuntime::DisableAutoDeclareTargetRAII Class Reference
Allows to disable automatic handling of functions used in target regions as those marked as omp declare target.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGOpenMPRuntime.h"
Public Member Functions
DisableAutoDeclareTargetRAII (CodeGenModule &CGM)
~DisableAutoDeclareTargetRAII ()
Detailed Description
Allows to disable automatic handling of functions used in target regions as those marked as omp declare target.
Definition at line 233 of file CGOpenMPRuntime.h.
Constructor & Destructor Documentation
DisableAutoDeclareTargetRAII()
CGOpenMPRuntime::DisableAutoDeclareTargetRAII::DisableAutoDeclareTargetRAII (CodeGenModule & CGM)
Definition at line 10084 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::CodeGen::CGOpenMPRuntime::ShouldMarkAsGlobal.
~DisableAutoDeclareTargetRAII()
CGOpenMPRuntime::DisableAutoDeclareTargetRAII::~DisableAutoDeclareTargetRAII ()
Definition at line 10093 of file CGOpenMPRuntime.cpp.
References clang::CodeGen::CGOpenMPRuntime::CGM, clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getOpenMPRuntime(), and clang::CodeGen::CGOpenMPRuntime::ShouldMarkAsGlobal.
The documentation for this class was generated from the following files:
lib/CodeGen/CGOpenMPRuntime.h
lib/CodeGen/CGOpenMPRuntime.cpp