clang: clang::CodeGen::CodeGenFunction::ConstantEmission Class Reference
clang::CodeGen::CodeGenFunction::ConstantEmission Class Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
ConstantEmission ()
operator bool () const
bool isReference () const
LValue getReferenceLValue (CodeGenFunction &CGF, Expr *refExpr) const
llvm::Constant * getValue () const
Static Public Member Functions
static ConstantEmission forReference (llvm::Constant *C)
static ConstantEmission forValue (llvm::Constant *C)
Detailed Description
Definition at line 3931 of file CodeGenFunction.h.
Constructor & Destructor Documentation
ConstantEmission()
clang::CodeGen::CodeGenFunction::ConstantEmission::ConstantEmission () inline
Definition at line 3936 of file CodeGenFunction.h.
Referenced by forReference(), and forValue().
Member Function Documentation
forReference()
static ConstantEmission clang::CodeGen::CodeGenFunction::ConstantEmission::forReference (llvm::Constant * C) inline static
Definition at line 3937 of file CodeGenFunction.h.
References ConstantEmission().
Referenced by clang::CodeGen::CodeGenFunction::tryEmitAsConstant().
forValue()
static ConstantEmission clang::CodeGen::CodeGenFunction::ConstantEmission::forValue (llvm::Constant * C) inline static
Definition at line 3940 of file CodeGenFunction.h.
References ConstantEmission().
Referenced by clang::CodeGen::CodeGenFunction::tryEmitAsConstant().
getReferenceLValue()
LValue clang::CodeGen::CodeGenFunction::ConstantEmission::getReferenceLValue (CodeGenFunction & CGF, Expr * refExpr) const inline
Definition at line 3949 of file CodeGenFunction.h.
References clang::Expr::getType(), isReference(), and clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue().
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPFirstprivateClause(), and clang::CodeGen::CodeGenFunction::emitScalarConstant().
getValue()
llvm::Constant* clang::CodeGen::CodeGenFunction::ConstantEmission::getValue () const inline
Definition at line 3955 of file CodeGenFunction.h.
References isReference().
Referenced by clang::CodeGen::CodeGenFunction::emitScalarConstant().
isReference()
bool clang::CodeGen::CodeGenFunction::ConstantEmission::isReference () const inline
Definition at line 3948 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitOMPFirstprivateClause(), clang::CodeGen::CodeGenFunction::emitScalarConstant(), getReferenceLValue(), and getValue().
operator bool()
clang::CodeGen::CodeGenFunction::ConstantEmission::operator bool () const inline explicit
Definition at line 3944 of file CodeGenFunction.h.
The documentation for this class was generated from the following file:
lib/CodeGen/CodeGenFunction.h