clang: clang::threadSafety::til::Phi Class Reference
clang::threadSafety::til::Phi Class Reference
Phi Node, for code in SSA form.
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
Public Types
enum Status { PH_MultiVal = 0 , PH_SingleVal , PH_Incomplete }
using ValArray = SimpleArray< SExpr * >
Public Member Functions
Phi ()
Phi (MemRegionRef A, unsigned Nvals)
Phi (const Phi &P, ValArray &&Vs)
const ValArray & values () const
ValArray & values ()
Status status () const
void setStatus (Status s)
const ValueDecl * clangDecl () const
Return the clang declaration of the variable for this Phi node, if any.
void setClangDecl (const ValueDecl *Cvd)
Set the clang variable associated with this Phi node.
template<class V >
V::R_SExpr traverse (V &Vs, typename V::R_Ctx Ctx)
template<class C >
C::CType compare (const Phi *E, C &Cmp) const
Public Member Functions inherited from clang::threadSafety::til::SExpr
SExpr ()=delete
TIL_Opcode opcode () const
void * operator new (size_t S, MemRegionRef &R)
void * operator new (size_t)=delete
SExpr objects must be created in an arena.
void operator delete (void *)=delete
SExpr objects cannot be deleted.
unsigned id () const
Returns the instruction ID for this expression.
BasicBlock * block () const
Returns the block, if this is an instruction in a basic block, otherwise returns null.
void setID (BasicBlock *B, unsigned id)
Set the basic block and instruction ID for this expression.
Static Public Member Functions
static bool classof (const SExpr *E)
Additional Inherited Members
Protected Member Functions inherited from clang::threadSafety::til::SExpr
SExpr (TIL_Opcode Op)
SExpr (const SExpr &E)
SExpr & operator= (const SExpr &)=delete
Protected Attributes inherited from clang::threadSafety::til::SExpr
const TIL_Opcode Opcode
unsigned char Reserved = 0
unsigned short Flags = 0
unsigned SExprID = 0
BasicBlock * Block = nullptr
Detailed Description
Phi Node, for code in SSA form.
Each Phi node has an array of possible values that it can take, depending on where control flow comes from.
Definition at line 1302 of file ThreadSafetyTIL.h.
Member Typedef Documentation
ValArray
using clang::threadSafety::til::Phi::ValArray = SimpleArray<SExpr *>
Definition at line 1304 of file ThreadSafetyTIL.h.
Member Enumeration Documentation
Status
enum clang::threadSafety::til::Phi::Status
Enumerator
PH_MultiVal
PH_SingleVal
PH_Incomplete
Definition at line 1309 of file ThreadSafetyTIL.h.
Constructor & Destructor Documentation
Phi() [1/3]
clang::threadSafety::til::Phi::Phi () inline
Definition at line 1315 of file ThreadSafetyTIL.h.
Phi() [2/3]
clang::threadSafety::til::Phi::Phi (MemRegionRef A, unsigned Nvals) inline
Definition at line 1316 of file ThreadSafetyTIL.h.
Phi() [3/3]
clang::threadSafety::til::Phi::Phi (const Phi & P, ValArray && Vs) inline
Definition at line 1317 of file ThreadSafetyTIL.h.
Member Function Documentation
clangDecl()
const ValueDecl* clang::threadSafety::til::Phi::clangDecl () const inline
Return the clang declaration of the variable for this Phi node, if any.
Definition at line 1328 of file ThreadSafetyTIL.h.
classof()
static bool clang::threadSafety::til::Phi::classof (const SExpr * E) inline static
Definition at line 1319 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::opcode().
compare()
template<class C > C::CType clang::threadSafety::til::Phi::compare (const Phi * E, C & Cmp) const inline
Definition at line 1344 of file ThreadSafetyTIL.h.
setClangDecl()
void clang::threadSafety::til::Phi::setClangDecl (const ValueDecl * Cvd) inline
Set the clang variable associated with this Phi node.
Definition at line 1331 of file ThreadSafetyTIL.h.
setStatus()
void clang::threadSafety::til::Phi::setStatus (Status s) inline
Definition at line 1325 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags, and s.
Referenced by clang::threadSafety::til::simplifyIncompleteArg().
status()
Status clang::threadSafety::til::Phi::status () const inline
Definition at line 1324 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SExpr::Flags.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printPhi(), and clang::threadSafety::til::simplifyIncompleteArg().
traverse()
template<class V > V::R_SExpr clang::threadSafety::til::Phi::traverse (V & Vs, typename V::R_Ctx Ctx) inline
Definition at line 1334 of file ThreadSafetyTIL.h.
References clang::threadSafety::til::SimpleArray< T >::size().
values() [1/2]
ValArray& clang::threadSafety::til::Phi::values () inline
Definition at line 1322 of file ThreadSafetyTIL.h.
values() [2/2]
const ValArray& clang::threadSafety::til::Phi::values () const inline
Definition at line 1321 of file ThreadSafetyTIL.h.
Referenced by clang::threadSafety::til::PrettyPrinter< Self, StreamType >::printPhi(), and clang::threadSafety::til::simplifyIncompleteArg().
The documentation for this class was generated from the following file:
include/clang/Analysis/Analyses/ThreadSafetyTIL.h