clang: clang::CXXConstructExpr Class Reference
clang::CXXConstructExpr Class Reference
Represents a call to a C++ constructor.
#include "clang/AST/ExprCXX.h"
Public Types
enum ConstructionKind { CK_Complete, CK_NonVirtualBase, CK_VirtualBase, CK_Delegating }
using arg_iterator = ExprIterator
using const_arg_iterator = ConstExprIterator
using arg_range = llvm::iterator_range< arg_iterator >
using const_arg_range = llvm::iterator_range< const_arg_iterator >
Public Types inherited from clang::Expr
enum LValueClassification {
LV_Valid, LV_NotObjectType, LV_IncompleteVoidType, LV_DuplicateVectorComponents,
LV_InvalidExpression, LV_InvalidMessageExpression, LV_MemberFunction, LV_SubObjCPropertySetting,
LV_ClassTemporary, LV_ArrayTemporary
}
enum isModifiableLvalueResult {
MLV_Valid, MLV_NotObjectType, MLV_IncompleteVoidType, MLV_DuplicateVectorComponents,
MLV_InvalidExpression, MLV_LValueCast, MLV_IncompleteType, MLV_ConstQualified,
MLV_ConstQualifiedField, MLV_ConstAddrSpace, MLV_ArrayType, MLV_NoSetterProperty,
MLV_MemberFunction, MLV_SubObjCPropertySetting, MLV_InvalidMessageExpression, MLV_ClassTemporary,
MLV_ArrayTemporary
}
enum SideEffectsKind { SE_NoSideEffects, SE_AllowUndefinedBehavior, SE_AllowSideEffects }
enum ConstantExprKind { ConstantExprKind::Normal, ConstantExprKind::NonClassTemplateArgument, ConstantExprKind::ClassTemplateArgument, ConstantExprKind::ImmediateInvocation }
enum NullPointerConstantKind {
NPCK_NotNull = 0, NPCK_ZeroExpression, NPCK_ZeroLiteral, NPCK_CXX11_nullptr,
NPCK_GNUNull
}
Enumeration used to describe the kind of Null pointer constant returned from isNullPointerConstant().
enum NullPointerConstantValueDependence { NPC_NeverValueDependent = 0, NPC_ValueDependentIsNull, NPC_ValueDependentIsNotNull }
Enumeration used to describe how isNullPointerConstant() should cope with value-dependent expressions.
Public Types inherited from clang::Stmt
enum StmtClass { NoStmtClass = 0 }
enum Likelihood { LH_Unlikely = -1, LH_None, LH_Likely }
The likelihood of a branch being taken.
using child_iterator = StmtIterator
Child Iterators: All subclasses must implement 'children' to permit easy iteration over the substatements/subexpessions of an AST node.
using const_child_iterator = ConstStmtIterator
using child_range = llvm::iterator_range< child_iterator >
using const_child_range = llvm::iterator_range< const_child_iterator >
Public Member Functions
CXXConstructorDecl * getConstructor () const
Get the constructor that this expression will (ultimately) call.
SourceLocation getLocation () const
void setLocation (SourceLocation Loc)
bool isElidable () const
Whether this construction is elidable.
void setElidable (bool E)
bool hadMultipleCandidates () const
Whether the referred constructor was resolved from an overloaded set having size greater than 1.
void setHadMultipleCandidates (bool V)
bool isListInitialization () const
Whether this constructor call was written as list-initialization.
void setListInitialization (bool V)
bool isStdInitListInitialization () const
Whether this constructor call was written as list-initialization, but was interpreted as forming a std::initializer_list<T> from the list and passing that as a single constructor argument.
void setStdInitListInitialization (bool V)
bool requiresZeroInitialization () const
Whether this construction first requires zero-initialization before the initializer is called.
void setRequiresZeroInitialization (bool ZeroInit)
ConstructionKind getConstructionKind () const
Determine whether this constructor is actually constructing a base class (rather than a complete object).
void setConstructionKind (ConstructionKind CK)
arg_range arguments ()
const_arg_range arguments () const
arg_iterator arg_begin ()
arg_iterator arg_end ()
const_arg_iterator arg_begin () const
const_arg_iterator arg_end () const
Expr ** getArgs ()
const Expr *const * getArgs () const
unsigned getNumArgs () const
Return the number of arguments to the constructor call.
Expr * getArg (unsigned Arg)
Return the specified argument.
const Expr * getArg (unsigned Arg) const
void setArg (unsigned Arg, Expr *ArgExpr)
Set the specified argument.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
SourceRange getParenOrBraceRange () const
void setParenOrBraceRange (SourceRange Range)
child_range children ()
const_child_range children () const
Public Member Functions inherited from clang::Expr
Expr ()=delete
Expr (const Expr &)=delete
Expr (Expr &&)=delete
Expr & operator= (const Expr &)=delete
Expr & operator= (Expr &&)=delete
QualType getType () const
void setType (QualType t)
ExprDependence getDependence () const
bool isValueDependent () const
Determines whether the value of this expression depends on.
bool isTypeDependent () const
Determines whether the type of this expression depends on.
bool isInstantiationDependent () const
Whether this expression is instantiation-dependent, meaning that it depends in some way on.
bool containsUnexpandedParameterPack () const
Whether this expression contains an unexpanded parameter pack (for C++11 variadic templates).
bool containsErrors () const
Whether this expression contains subexpressions which had errors, e.g.
SourceLocation getExprLoc () const LLVM_READONLY
getExprLoc - Return the preferred location for the arrow when diagnosing a problem with a generic expression.
bool isReadIfDiscardedInCPlusPlus11 () const
Determine whether an lvalue-to-rvalue conversion should implicitly be applied to this expression if it appears as a discarded-value expression in C++11 onwards.
bool isUnusedResultAWarning (const Expr *&WarnExpr, SourceLocation &Loc, SourceRange &R1, SourceRange &R2, ASTContext &Ctx) const
isUnusedResultAWarning - Return true if this immediate expression should be warned about if the result is unused.
bool isLValue () const
isLValue - True if this expression is an "l-value" according to the rules of the current language.
bool isPRValue () const
bool isXValue () const
bool isGLValue () const
LValueClassification ClassifyLValue (ASTContext &Ctx) const
Reasons why an expression might not be an l-value.
isModifiableLvalueResult isModifiableLvalue (ASTContext &Ctx, SourceLocation *Loc=nullptr) const
isModifiableLvalue - C99 6.3.2.1: an lvalue that does not have array type, does not have an incomplete type, does not have a const-qualified type, and if it is a structure or union, does not have any member (including, recursively, any member or element of all contained aggregates or unions) with a const-qualified type.
Classification Classify (ASTContext &Ctx) const
Classify - Classify this expression according to the C++11 expression taxonomy.
Classification ClassifyModifiable (ASTContext &Ctx, SourceLocation &Loc) const
ClassifyModifiable - Classify this expression according to the C++11 expression taxonomy, and see if it is valid on the left side of an assignment.
FPOptions getFPFeaturesInEffect (const LangOptions &LO) const
Returns the set of floating point options that apply to this expression.
ExprValueKind getValueKind () const
getValueKind - The value kind that this expression produces.
ExprObjectKind getObjectKind () const
getObjectKind - The object kind that this expression produces.
bool isOrdinaryOrBitFieldObject () const
void setValueKind (ExprValueKind Cat)
setValueKind - Set the value kind produced by this expression.
void setObjectKind (ExprObjectKind Cat)
setObjectKind - Set the object kind produced by this expression.
bool refersToBitField () const
Returns true if this expression is a gl-value that potentially refers to a bit-field.
FieldDecl * getSourceBitField ()
If this expression refers to a bit-field, retrieve the declaration of that bit-field.
const FieldDecl * getSourceBitField () const
Decl * getReferencedDeclOfCallee ()
const Decl * getReferencedDeclOfCallee () const
const ObjCPropertyRefExpr * getObjCProperty () const
If this expression is an l-value for an Objective C property, find the underlying property reference expression.
bool isObjCSelfExpr () const
Check if this expression is the ObjC 'self' implicit parameter.
bool refersToVectorElement () const
Returns whether this expression refers to a vector element.
bool refersToMatrixElement () const
Returns whether this expression refers to a matrix element.
bool refersToGlobalRegisterVar () const
Returns whether this expression refers to a global register variable.
bool hasPlaceholderType () const
Returns whether this expression has a placeholder type.
bool hasPlaceholderType (BuiltinType::Kind K) const
Returns whether this expression has a specific placeholder type.
bool isKnownToHaveBooleanValue (bool Semantic=true) const
isKnownToHaveBooleanValue - Return true if this is an integer expression that is known to return 0 or 1.
Optional< llvm::APSInt > getIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr, bool isEvaluated=true) const
isIntegerConstantExpr - Return the value if this expression is a valid integer constant expression.
bool isIntegerConstantExpr (const ASTContext &Ctx, SourceLocation *Loc=nullptr) const
bool isCXX98IntegralConstantExpr (const ASTContext &Ctx) const
isCXX98IntegralConstantExpr - Return true if this expression is an integral constant expression in C++98.
bool isCXX11ConstantExpr (const ASTContext &Ctx, APValue *Result=nullptr, SourceLocation *Loc=nullptr) const
isCXX11ConstantExpr - Return true if this expression is a constant expression in C++11.
bool isConstantInitializer (ASTContext &Ctx, bool ForRef, const Expr **Culprit=nullptr) const
isConstantInitializer - Returns true if this expression can be emitted to IR as a constant, and thus can be used as a constant initializer in C.
const ValueDecl * getAsBuiltinConstantDeclRef (const ASTContext &Context) const
If this expression is an unambiguous reference to a single declaration, in the style of __builtin_function_start, return that declaration.
bool EvaluateAsRValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsRValue - Return true if this is a constant which we can fold to an rvalue using any crazy technique (that has nothing to do with language standards) that we want to, even if the expression has side-effects.
bool EvaluateAsBooleanCondition (bool &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsBooleanCondition - Return true if this is a constant which we can fold and convert to a boolean condition using any crazy technique that we want to, even if the expression has side-effects.
bool EvaluateAsInt (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsInt - Return true if this is a constant which we can fold and convert to an integer, using any crazy technique that we want to.
bool EvaluateAsFloat (llvm::APFloat &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a floating point value, using any crazy technique that we want to.
bool EvaluateAsFixedPoint (EvalResult &Result, const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects, bool InConstantContext=false) const
EvaluateAsFloat - Return true if this is a constant which we can fold and convert to a fixed point value.
bool isEvaluatable (const ASTContext &Ctx, SideEffectsKind AllowSideEffects=SE_NoSideEffects) const
isEvaluatable - Call EvaluateAsRValue to see if this expression can be constant folded without side-effects, but discard the result.
bool HasSideEffects (const ASTContext &Ctx, bool IncludePossibleEffects=true) const
HasSideEffects - This routine returns true for all those expressions which have any effect other than producing a value.
bool hasNonTrivialCall (const ASTContext &Ctx) const
Determine whether this expression involves a call to any function that is not trivial.
llvm::APSInt EvaluateKnownConstInt (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
EvaluateKnownConstInt - Call EvaluateAsRValue and return the folded integer.
llvm::APSInt EvaluateKnownConstIntCheckOverflow (const ASTContext &Ctx, SmallVectorImpl< PartialDiagnosticAt > *Diag=nullptr) const
void EvaluateForOverflow (const ASTContext &Ctx) const
bool EvaluateAsLValue (EvalResult &Result, const ASTContext &Ctx, bool InConstantContext=false) const
EvaluateAsLValue - Evaluate an expression to see if we can fold it to an lvalue with link time known address, with no side-effects.
bool EvaluateAsInitializer (APValue &Result, const ASTContext &Ctx, const VarDecl *VD, SmallVectorImpl< PartialDiagnosticAt > &Notes, bool IsConstantInitializer) const
EvaluateAsInitializer - Evaluate an expression as if it were the initializer of the given declaration.
bool EvaluateWithSubstitution (APValue &Value, ASTContext &Ctx, const FunctionDecl *Callee, ArrayRef< const Expr * > Args, const Expr *This=nullptr) const
EvaluateWithSubstitution - Evaluate an expression as if from the context of a call to the given function with the given arguments, inside an unevaluated context.
bool EvaluateAsConstantExpr (EvalResult &Result, const ASTContext &Ctx, ConstantExprKind Kind=ConstantExprKind::Normal) const
Evaluate an expression that is required to be a constant expression.
bool tryEvaluateObjectSize (uint64_t &Result, ASTContext &Ctx, unsigned Type) const
If the current Expr is a pointer, this will try to statically determine the number of bytes available where the pointer is pointing.
bool tryEvaluateStrLen (uint64_t &Result, ASTContext &Ctx) const
If the current Expr is a pointer, this will try to statically determine the strlen of the string pointed to.
NullPointerConstantKind isNullPointerConstant (ASTContext &Ctx, NullPointerConstantValueDependence NPC) const
isNullPointerConstant - C99 6.3.2.3p3 - Test if this reduces down to a Null pointer constant.
bool isOBJCGCCandidate (ASTContext &Ctx) const
isOBJCGCCandidate - Return true if this expression may be used in a read/ write barrier.
bool isBoundMemberFunction (ASTContext &Ctx) const
Returns true if this expression is a bound member function.
Expr * IgnoreUnlessSpelledInSource ()
Skip past any invisble AST nodes which might surround this statement, such as ExprWithCleanups or ImplicitCastExpr nodes, but also injected CXXMemberExpr and CXXConstructExpr which represent implicit conversions.
const Expr * IgnoreUnlessSpelledInSource () const
Expr * IgnoreImpCasts () LLVM_READONLY
Skip past any implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreImpCasts () const
Expr * IgnoreCasts () LLVM_READONLY
Skip past any casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreCasts () const
Expr * IgnoreImplicit () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicit () const
Expr * IgnoreImplicitAsWritten () LLVM_READONLY
Skip past any implicit AST nodes which might surround this expression until reaching a fixed point.
const Expr * IgnoreImplicitAsWritten () const
Expr * IgnoreParens () LLVM_READONLY
Skip past any parentheses which might surround this expression until reaching a fixed point.
const Expr * IgnoreParens () const
Expr * IgnoreParenImpCasts () LLVM_READONLY
Skip past any parentheses and implicit casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenImpCasts () const
Expr * IgnoreParenCasts () LLVM_READONLY
Skip past any parentheses and casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenCasts () const
Expr * IgnoreConversionOperatorSingleStep () LLVM_READONLY
Skip conversion operators.
const Expr * IgnoreConversionOperatorSingleStep () const
Expr * IgnoreParenLValueCasts () LLVM_READONLY
Skip past any parentheses and lvalue casts which might surround this expression until reaching a fixed point.
const Expr * IgnoreParenLValueCasts () const
Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) LLVM_READONLY
Skip past any parenthese and casts which do not change the value (including ptr->int casts of the same size) until reaching a fixed point.
const Expr * IgnoreParenNoopCasts (const ASTContext &Ctx) const
Expr * IgnoreParenBaseCasts () LLVM_READONLY
Skip past any parentheses and derived-to-base casts until reaching a fixed point.
const Expr * IgnoreParenBaseCasts () const
bool isDefaultArgument () const
Determine whether this expression is a default function argument.
bool isTemporaryObject (ASTContext &Ctx, const CXXRecordDecl *TempTy) const
Determine whether the result of this expression is a temporary object of the given class type.
bool isImplicitCXXThis () const
Whether this expression is an implicit reference to 'this' in C++.
const CXXRecordDecl * getBestDynamicClassType () const
For an expression of class type or pointer to class type, return the most derived class decl the expression is known to refer to.
const Expr * getBestDynamicClassTypeExpr () const
Get the inner expression that determines the best dynamic class.
const Expr * skipRValueSubobjectAdjustments (SmallVectorImpl< const Expr * > &CommaLHS, SmallVectorImpl< SubobjectAdjustment > &Adjustments) const
Walk outwards from an expression we want to bind a reference to and find the expression whose lifetime needs to be extended.
const Expr * skipRValueSubobjectAdjustments () const
Public Member Functions inherited from clang::ValueStmt
const Expr * getExprStmt () const
Expr * getExprStmt ()
Public Member Functions inherited from clang::Stmt
void * operator new (size_t bytes, const ASTContext &C, unsigned alignment=8)
void * operator new (size_t bytes, const ASTContext *C, unsigned alignment=8)
void * operator new (size_t bytes, void *mem) noexcept
void operator delete (void *, const ASTContext &, unsigned) noexcept
void operator delete (void *, const ASTContext *, unsigned) noexcept
void operator delete (void *, size_t) noexcept
void operator delete (void *, void *) noexcept
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt & operator= (const Stmt &)=delete
Stmt & operator= (Stmt &&)=delete
Stmt (StmtClass SC)
StmtClass getStmtClass () const
const char * getStmtClassName () const
SourceRange getSourceRange () const LLVM_READONLY
SourceLocation tokens are not useful in isolation - they are low level value objects created/interpreted by SourceManager.
SourceLocation getBeginLoc () const LLVM_READONLY
SourceLocation getEndLoc () const LLVM_READONLY
void dump () const
Dumps the specified AST fragment and all subtrees to llvm::errs().
void dump (raw_ostream &OS, const ASTContext &Context) const
int64_t getID (const ASTContext &Context) const
void dumpColor () const
dumpColor - same as dump(), but forces color highlighting.
void dumpPretty (const ASTContext &Context) const
dumpPretty/printPretty - These two methods do a "pretty print" of the AST back to its original source language syntax.
void printPretty (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printPrettyControlled (raw_ostream &OS, PrinterHelper *Helper, const PrintingPolicy &Policy, unsigned Indentation=0, StringRef NewlineSymbol="\n", const ASTContext *Context=nullptr) const
void printJson (raw_ostream &Out, PrinterHelper *Helper, const PrintingPolicy &Policy, bool AddQuotes) const
Pretty-prints in JSON format.
void viewAST () const
viewAST - Visualize an AST rooted at this Stmt* using GraphViz.
Stmt * IgnoreContainers (bool IgnoreCaptured=false)
Skip no-op (attributed, compound) container stmts and skip captured stmt at the top, if IgnoreCaptured is true.
const Stmt * IgnoreContainers (bool IgnoreCaptured=false) const
const Stmt * stripLabelLikeStatements () const
Strip off all label-like statements.
Stmt * stripLabelLikeStatements ()
child_range children ()
const_child_range children () const
child_iterator child_begin ()
child_iterator child_end ()
const_child_iterator child_begin () const
const_child_iterator child_end () const
void Profile (llvm::FoldingSetNodeID &ID, const ASTContext &Context, bool Canonical) const
Produce a unique representation of the given statement.
void ProcessODRHash (llvm::FoldingSetNodeID &ID, ODRHash &Hash) const
Calculate a unique representation for a statement that is stable across compiler invocations.
Static Public Member Functions
static CXXConstructExpr * Create (const ASTContext &Ctx, QualType Ty, SourceLocation Loc, CXXConstructorDecl *Ctor, bool Elidable, ArrayRef< Expr * > Args, bool HadMultipleCandidates, bool ListInitialization, bool StdInitListInitialization, bool ZeroInitialization, ConstructionKind ConstructKind, SourceRange ParenOrBraceRange)
Create a C++ construction expression.
static CXXConstructExpr * CreateEmpty (const ASTContext &Ctx, unsigned NumArgs)
Create an empty C++ construction expression.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Expr
static ExprValueKind getValueKindForType (QualType T)
getValueKindForType - Given a formal return or parameter type, give its value kind.
static bool isPotentialConstantExpr (const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExpr - Return true if this function's definition might be usable in a constant expression in C++11, if it were marked constexpr.
static bool isPotentialConstantExprUnevaluated (Expr *E, const FunctionDecl *FD, SmallVectorImpl< PartialDiagnosticAt > &Diags)
isPotentialConstantExprUnevaluted - Return true if this expression might be usable in a constant expression in C++11 in an unevaluated context, if it were in function FD marked constexpr.
static QualType findBoundMemberType (const Expr *expr)
Given an expression of bound-member type, find the type of the member.
static bool hasAnyTypeDependentArguments (ArrayRef< Expr * > Exprs)
hasAnyTypeDependentArguments - Determines if any of the expressions in Exprs is type-dependent.
static bool isSameComparisonOperand (const Expr *E1, const Expr *E2)
Checks that the two Expr's will refer to the same value as a comparison operand.
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::ValueStmt
static bool classof (const Stmt *T)
Static Public Member Functions inherited from clang::Stmt
static void addStmtClass (const StmtClass s)
static void EnableStatistics ()
static void PrintStats ()
static Likelihood getLikelihood (ArrayRef< const Attr * > Attrs)
static Likelihood getLikelihood (const Stmt *S)
static const Attr * getLikelihoodAttr (const Stmt *S)
static Likelihood getLikelihood (const Stmt *Then, const Stmt *Else)
static std::tuple< bool, const Attr *, const Attr * > determineLikelihoodConflict (const Stmt *Then, const Stmt *Else)
Protected Member Functions
CXXConstructExpr (StmtClass SC, QualType Ty, SourceLocation Loc, CXXConstructorDecl *Ctor, bool Elidable, ArrayRef< Expr * > Args, bool HadMultipleCandidates, bool ListInitialization, bool StdInitListInitialization, bool ZeroInitialization, ConstructionKind ConstructKind, SourceRange ParenOrBraceRange)
Build a C++ construction expression.
CXXConstructExpr (StmtClass SC, EmptyShell Empty, unsigned NumArgs)
Build an empty C++ construction expression.
Protected Member Functions inherited from clang::Expr
Expr (StmtClass SC, QualType T, ExprValueKind VK, ExprObjectKind OK)
Expr (StmtClass SC, EmptyShell)
Construct an empty expression.
void setDependence (ExprDependence Deps)
Each concrete expr subclass is expected to compute its dependence and call this in the constructor.
Protected Member Functions inherited from clang::ValueStmt
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Stmt ()=delete
Stmt (const Stmt &)=delete
Stmt (Stmt &&)=delete
Stmt (StmtClass SC)
Protected Member Functions inherited from clang::Stmt
void * operator new (size_t bytes) noexcept
void operator delete (void *data) noexcept
Stmt (StmtClass SC, EmptyShell)
Construct an empty statement.
Static Protected Member Functions
static unsigned sizeOfTrailingObjects (unsigned NumArgs)
Return the size in bytes of the trailing objects.
Friends
class ASTStmtReader
Additional Inherited Members
Protected Types inherited from clang::Stmt
enum { NumStmtBits = 8 }
enum { NumExprBits = NumStmtBits + 5 + llvm::BitWidth<ExprDependence> }
enum { NumCallExprBits = 32 }
enum { NumOverloadExprBits = NumExprBits + 1 }
template<typename T >
using ConstCastIterator = CastIterator< T, const T *const, const Stmt *const >
Const iterator for iterating over Stmt * arrays that contain only T *.
using ExprIterator = CastIterator< Expr >
using ConstExprIterator = ConstCastIterator< Expr >
Protected Attributes inherited from clang::Stmt
union {
StmtBitfields StmtBits
NullStmtBitfields NullStmtBits
CompoundStmtBitfields CompoundStmtBits
LabelStmtBitfields LabelStmtBits
AttributedStmtBitfields AttributedStmtBits
IfStmtBitfields IfStmtBits
SwitchStmtBitfields SwitchStmtBits
WhileStmtBitfields WhileStmtBits
DoStmtBitfields DoStmtBits
ForStmtBitfields ForStmtBits
GotoStmtBitfields GotoStmtBits
ContinueStmtBitfields ContinueStmtBits
BreakStmtBitfields BreakStmtBits
ReturnStmtBitfields ReturnStmtBits
SwitchCaseBitfields SwitchCaseBits
ExprBitfields ExprBits
ConstantExprBitfields ConstantExprBits
PredefinedExprBitfields PredefinedExprBits
DeclRefExprBitfields DeclRefExprBits
FloatingLiteralBitfields FloatingLiteralBits
StringLiteralBitfields StringLiteralBits
CharacterLiteralBitfields CharacterLiteralBits
UnaryOperatorBitfields UnaryOperatorBits
UnaryExprOrTypeTraitExprBitfields UnaryExprOrTypeTraitExprBits
ArrayOrMatrixSubscriptExprBitfields ArrayOrMatrixSubscriptExprBits
CallExprBitfields CallExprBits
MemberExprBitfields MemberExprBits
CastExprBitfields CastExprBits
BinaryOperatorBitfields BinaryOperatorBits
InitListExprBitfields InitListExprBits
ParenListExprBitfields ParenListExprBits
GenericSelectionExprBitfields GenericSelectionExprBits
PseudoObjectExprBitfields PseudoObjectExprBits
SourceLocExprBitfields SourceLocExprBits
StmtExprBitfields StmtExprBits
CXXOperatorCallExprBitfields CXXOperatorCallExprBits
CXXRewrittenBinaryOperatorBitfields CXXRewrittenBinaryOperatorBits
CXXBoolLiteralExprBitfields CXXBoolLiteralExprBits
CXXNullPtrLiteralExprBitfields CXXNullPtrLiteralExprBits
CXXThisExprBitfields CXXThisExprBits
CXXThrowExprBitfields CXXThrowExprBits
CXXDefaultArgExprBitfields CXXDefaultArgExprBits
CXXDefaultInitExprBitfields CXXDefaultInitExprBits
CXXScalarValueInitExprBitfields CXXScalarValueInitExprBits
CXXNewExprBitfields CXXNewExprBits
CXXDeleteExprBitfields CXXDeleteExprBits
TypeTraitExprBitfields TypeTraitExprBits
DependentScopeDeclRefExprBitfields DependentScopeDeclRefExprBits
CXXConstructExprBitfields CXXConstructExprBits
ExprWithCleanupsBitfields ExprWithCleanupsBits
CXXUnresolvedConstructExprBitfields CXXUnresolvedConstructExprBits
CXXDependentScopeMemberExprBitfields CXXDependentScopeMemberExprBits
OverloadExprBitfields OverloadExprBits
UnresolvedLookupExprBitfields UnresolvedLookupExprBits
UnresolvedMemberExprBitfields UnresolvedMemberExprBits
CXXNoexceptExprBitfields CXXNoexceptExprBits
SubstNonTypeTemplateParmExprBitfields SubstNonTypeTemplateParmExprBits
LambdaExprBitfields LambdaExprBits
RequiresExprBitfields RequiresExprBits
CoawaitExprBitfields CoawaitBits
ObjCIndirectCopyRestoreExprBitfields ObjCIndirectCopyRestoreExprBits
OpaqueValueExprBitfields OpaqueValueExprBits
};
Detailed Description
Represents a call to a C++ constructor.
Definition at line 1460 of file ExprCXX.h.
Member Typedef Documentation
arg_iterator
using clang::CXXConstructExpr::arg_iterator = ExprIterator
Definition at line 1587 of file ExprCXX.h.
arg_range
using clang::CXXConstructExpr::arg_range = llvm::iterator_range<arg_iterator>
Definition at line 1589 of file ExprCXX.h.
const_arg_iterator
using clang::CXXConstructExpr::const_arg_iterator = ConstExprIterator
Definition at line 1588 of file ExprCXX.h.
const_arg_range
using clang::CXXConstructExpr::const_arg_range = llvm::iterator_range<const_arg_iterator>
Definition at line 1590 of file ExprCXX.h.
Member Enumeration Documentation
ConstructionKind
enum clang::CXXConstructExpr::ConstructionKind
Enumerator
CK_Complete
CK_NonVirtualBase
CK_VirtualBase
CK_Delegating
Definition at line 1464 of file ExprCXX.h.
Constructor & Destructor Documentation
CXXConstructExpr() [1/2]
CXXConstructExpr::CXXConstructExpr (StmtClass SC, QualType Ty, SourceLocation Loc, CXXConstructorDecl * Ctor, bool Elidable, ArrayRef< Expr * > Args, bool HadMultipleCandidates, bool ListInitialization, bool StdInitListInitialization, bool ZeroInitialization, ConstructionKind ConstructKind, SourceRange ParenOrBraceRange) protected
Build a C++ construction expression.
Definition at line 1056 of file ExprCXX.cpp.
References clang::computeDependence(), clang::Stmt::CXXConstructExprBits, and clang::Expr::setDependence().
Referenced by Create(), and CreateEmpty().
CXXConstructExpr() [2/2]
CXXConstructExpr::CXXConstructExpr (StmtClass SC, EmptyShell Empty, unsigned NumArgs) protected
Build an empty C++ construction expression.
Definition at line 1081 of file ExprCXX.cpp.
Member Function Documentation
arg_begin() [1/2]
arg_iterator clang::CXXConstructExpr::arg_begin () inline
Definition at line 1597 of file ExprCXX.h.
Referenced by arg_end(), arguments(), and clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction().
arg_begin() [2/2]
const_arg_iterator clang::CXXConstructExpr::arg_begin () const inline
Definition at line 1599 of file ExprCXX.h.
arg_end() [1/2]
arg_iterator clang::CXXConstructExpr::arg_end () inline
Definition at line 1598 of file ExprCXX.h.
References arg_begin(), and getNumArgs().
Referenced by arguments(), and clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction().
arg_end() [2/2]
const_arg_iterator clang::CXXConstructExpr::arg_end () const inline
Definition at line 1600 of file ExprCXX.h.
References arg_begin(), and getNumArgs().
arguments() [1/2]
arg_range clang::CXXConstructExpr::arguments () inline
Definition at line 1592 of file ExprCXX.h.
References arg_begin(), and arg_end().
Referenced by clang::computeDependence(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), clang::CodeGen::CodeGenFunction::EmitSynthesizedCXXCopyCtorCall(), clang::ASTNodeImporter::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr().
arguments() [2/2]
const_arg_range clang::CXXConstructExpr::arguments () const inline
Definition at line 1593 of file ExprCXX.h.
References arg_begin(), and arg_end().
children() [1/2]
child_range clang::CXXConstructExpr::children () inline
Definition at line 1637 of file ExprCXX.h.
References getNumArgs().
Referenced by children().
children() [2/2]
const_child_range clang::CXXConstructExpr::children () const inline
Definition at line 1641 of file ExprCXX.h.
References children().
classof()
static bool clang::CXXConstructExpr::classof (const Stmt * T) inline static
Definition at line 1631 of file ExprCXX.h.
References clang::Stmt::getStmtClass().
Create()
CXXConstructExpr * CXXConstructExpr::Create (const ASTContext & Ctx, QualType Ty, SourceLocation Loc, CXXConstructorDecl * Ctor, bool Elidable, ArrayRef< Expr * > Args, bool HadMultipleCandidates, bool ListInitialization, bool StdInitListInitialization, bool ZeroInitialization, ConstructionKind ConstructKind, SourceRange ParenOrBraceRange) static
Create a C++ construction expression.
Definition at line 1032 of file ExprCXX.cpp.
References clang::ASTContext::Allocate(), CXXConstructExpr(), and sizeOfTrailingObjects().
Referenced by clang::Sema::BuildCXXConstructExpr(), buildFakeCtorCall(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), and clang::ASTNodeImporter::VisitCXXConstructExpr().
CreateEmpty()
CXXConstructExpr * CXXConstructExpr::CreateEmpty (const ASTContext & Ctx, unsigned NumArgs) static
Create an empty C++ construction expression.
Definition at line 1047 of file ExprCXX.cpp.
References clang::ASTContext::Allocate(), CXXConstructExpr(), and sizeOfTrailingObjects().
getArg() [1/2]
Expr* clang::CXXConstructExpr::getArg (unsigned Arg) inline
Return the specified argument.
Definition at line 1611 of file ExprCXX.h.
References getArgs(), and getNumArgs().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructExpr(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), getEndLoc(), clang::CXXTemporaryObjectExpr::getEndLoc(), clang::Expr::isConstantInitializer(), and clang::TreeTransform< KernelBodyTransform >::TransformInitializer().
getArg() [2/2]
const Expr* clang::CXXConstructExpr::getArg (unsigned Arg) const inline
Definition at line 1615 of file ExprCXX.h.
References getArgs(), and getNumArgs().
getArgs() [1/2]
Expr** clang::CXXConstructExpr::getArgs () inline
Definition at line 1602 of file ExprCXX.h.
Referenced by getArg(), setArg(), and clang::TreeTransform< KernelBodyTransform >::TransformInitializer().
getArgs() [2/2]
const Expr* const * clang::CXXConstructExpr::getArgs () const inline
Definition at line 1603 of file ExprCXX.h.
getBeginLoc()
SourceLocation CXXConstructExpr::getBeginLoc () const
Definition at line 509 of file ExprCXX.cpp.
References getLocation().
Referenced by clang::TreeTransform< KernelBodyTransform >::TransformInitializer(), and clang::UsedDeclVisitor< Derived >::VisitCXXConstructExpr().
getConstructionKind()
ConstructionKind clang::CXXConstructExpr::getConstructionKind () const inline
Determine whether this constructor is actually constructing a base class (rather than a complete object).
Definition at line 1580 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructExpr(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::JSONNodeDumper::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXConstructExpr().
getConstructor()
CXXConstructorDecl* clang::CXXConstructExpr::getConstructor () const inline
Get the constructor that this expression will (ultimately) call.
Definition at line 1532 of file ExprCXX.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructExpr(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), EmitMemberInitializer(), clang::CodeGen::CodeGenFunction::EmitSynthesizedCXXCopyCtor(), clang::CodeGen::CodeGenFunction::EmitSynthesizedCXXCopyCtorCall(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::ento::CXXConstructorCall::getDecl(), hasNonTrivialConstructorCall(), clang::Expr::isConstantInitializer(), ShouldDiagnoseUnusedDecl(), clang::UsedDeclVisitor< Derived >::VisitCXXConstructExpr(), clang::JSONNodeDumper::VisitCXXConstructExpr(), clang::ASTNodeImporter::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr().
getEndLoc()
SourceLocation CXXConstructExpr::getEndLoc () const
Definition at line 515 of file ExprCXX.cpp.
References End, getArg(), clang::SourceRange::getEnd(), clang::Stmt::getEndLoc(), getLocation(), getNumArgs(), clang::Expr::isDefaultArgument(), clang::SourceLocation::isValid(), and clang::SourceRange::isValid().
Referenced by clang::TreeTransform< KernelBodyTransform >::TransformInitializer().
getLocation()
SourceLocation clang::CXXConstructExpr::getLocation () const inline
Definition at line 1534 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
Referenced by getBeginLoc(), getEndLoc(), and clang::ASTNodeImporter::VisitCXXConstructExpr().
getNumArgs()
unsigned clang::CXXConstructExpr::getNumArgs () const inline
Return the number of arguments to the constructor call.
Definition at line 1608 of file ExprCXX.h.
Referenced by arg_end(), children(), clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), getArg(), getEndLoc(), clang::CXXTemporaryObjectExpr::getEndLoc(), clang::ento::CXXConstructorCall::getNumArgs(), clang::ento::CXXInheritedConstructorCall::getNumArgs(), clang::Expr::isConstantInitializer(), setArg(), clang::TreeTransform< KernelBodyTransform >::TransformInitializer(), clang::ASTNodeImporter::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr().
getParenOrBraceRange()
SourceRange clang::CXXConstructExpr::getParenOrBraceRange () const inline
Definition at line 1628 of file ExprCXX.h.
Referenced by clang::CXXTemporaryObjectExpr::getEndLoc(), clang::TreeTransform< KernelBodyTransform >::TransformInitializer(), clang::ASTNodeImporter::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr().
hadMultipleCandidates()
bool clang::CXXConstructExpr::hadMultipleCandidates () const inline
Whether the referred constructor was resolved from an overloaded set having size greater than 1.
Definition at line 1543 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
Referenced by clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::JSONNodeDumper::VisitCXXConstructExpr(), clang::ASTNodeImporter::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr().
isElidable()
bool clang::CXXConstructExpr::isElidable () const inline
Whether this construction is elidable.
Definition at line 1538 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructExpr(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), ShouldDiagnoseUnusedDecl(), clang::JSONNodeDumper::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXConstructExpr().
isListInitialization()
bool clang::CXXConstructExpr::isListInitialization () const inline
Whether this constructor call was written as list-initialization.
Definition at line 1551 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::TreeTransform< KernelBodyTransform >::TransformInitializer(), clang::JSONNodeDumper::VisitCXXConstructExpr(), clang::ASTNodeImporter::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr().
isStdInitListInitialization()
bool clang::CXXConstructExpr::isStdInitListInitialization () const inline
Whether this constructor call was written as list-initialization, but was interpreted as forming a std::initializer_list<T> from the list and passing that as a single constructor argument.
See C++11 [over.match.list]p1 bullet 1.
Definition at line 1562 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
Referenced by clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::TreeTransform< KernelBodyTransform >::TransformInitializer(), clang::JSONNodeDumper::VisitCXXConstructExpr(), clang::ASTNodeImporter::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr().
requiresZeroInitialization()
bool clang::CXXConstructExpr::requiresZeroInitialization () const inline
Whether this construction first requires zero-initialization before the initializer is called.
Definition at line 1571 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructExpr(), clang::CodeGen::CodeGenFunction::EmitSynthesizedCXXCopyCtor(), clang::CodeGen::CodeGenFunction::GenerateObjCAtomicGetterCopyHelperFunction(), clang::JSONNodeDumper::VisitCXXConstructExpr(), clang::ASTNodeImporter::VisitCXXConstructExpr(), and clang::ASTNodeImporter::VisitCXXTemporaryObjectExpr().
setArg()
void clang::CXXConstructExpr::setArg (unsigned Arg, Expr * ArgExpr) inline
Set the specified argument.
Definition at line 1621 of file ExprCXX.h.
References getArgs(), and getNumArgs().
setConstructionKind()
void clang::CXXConstructExpr::setConstructionKind (ConstructionKind CK) inline
Definition at line 1583 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
setElidable()
void clang::CXXConstructExpr::setElidable (bool E) inline
Definition at line 1539 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
setHadMultipleCandidates()
void clang::CXXConstructExpr::setHadMultipleCandidates (bool V) inline
Definition at line 1546 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits, and V.
setListInitialization()
void clang::CXXConstructExpr::setListInitialization (bool V) inline
Definition at line 1554 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits, and V.
setLocation()
void clang::CXXConstructExpr::setLocation (SourceLocation Loc) inline
Definition at line 1535 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
setParenOrBraceRange()
void clang::CXXConstructExpr::setParenOrBraceRange (SourceRange Range) inline
Definition at line 1629 of file ExprCXX.h.
setRequiresZeroInitialization()
void clang::CXXConstructExpr::setRequiresZeroInitialization (bool ZeroInit) inline
Definition at line 1574 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits.
setStdInitListInitialization()
void clang::CXXConstructExpr::setStdInitListInitialization (bool V) inline
Definition at line 1565 of file ExprCXX.h.
References clang::Stmt::CXXConstructExprBits, and V.
sizeOfTrailingObjects()
static unsigned clang::CXXConstructExpr::sizeOfTrailingObjects (unsigned NumArgs) inline static protected
Return the size in bytes of the trailing objects.
Used by CXXTemporaryObjectExpr to allocate the right amount of storage.
Definition at line 1515 of file ExprCXX.h.
Referenced by Create(), clang::CXXTemporaryObjectExpr::Create(), CreateEmpty(), and clang::CXXTemporaryObjectExpr::CreateEmpty().
Friends And Related Function Documentation
ASTStmtReader
friend class ASTStmtReader friend
Definition at line 1461 of file ExprCXX.h.
The documentation for this class was generated from the following files:
include/clang/AST/ExprCXX.h
lib/AST/ExprCXX.cpp