clang: clang::ParsedAttributes Class Reference
clang::ParsedAttributes Class Reference
ParsedAttributes - A collection of parsed attributes.
#include "clang/Sema/ParsedAttr.h"
Public Member Functions
ParsedAttributes (AttributeFactory &factory)
ParsedAttributes (const ParsedAttributes &)=delete
AttributePool & getPool () const
void takeAllFrom (ParsedAttributes &Other)
void takeOneFrom (ParsedAttributes &Other, ParsedAttr *PA)
void clear ()
ParsedAttr * addNew (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, ArgsUnion *args, unsigned numArgs, ParsedAttr::Syntax syntax, SourceLocation ellipsisLoc=SourceLocation())
Add attribute with expression arguments.
ParsedAttr * addNew (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, IdentifierLoc *Param, const AvailabilityChange &introduced, const AvailabilityChange &deprecated, const AvailabilityChange &obsoleted, SourceLocation unavailable, const Expr *MessageExpr, ParsedAttr::Syntax syntax, SourceLocation strict, const Expr *ReplacementExpr)
Add availability attribute.
ParsedAttr * addNew (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, IdentifierLoc *Param1, IdentifierLoc *Param2, IdentifierLoc *Param3, ParsedAttr::Syntax syntax)
Add objc_bridge_related attribute.
ParsedAttr * addNewTypeTagForDatatype (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, IdentifierLoc *argumentKind, ParsedType matchingCType, bool layoutCompatible, bool mustBeNull, ParsedAttr::Syntax syntax)
Add type_tag_for_datatype attribute.
ParsedAttr * addNewTypeAttr (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, ParsedType typeArg, ParsedAttr::Syntax syntaxUsed)
Add an attribute with a single type argument.
ParsedAttr * addNewPropertyAttr (IdentifierInfo *attrName, SourceRange attrRange, IdentifierInfo *scopeName, SourceLocation scopeLoc, IdentifierInfo *getterId, IdentifierInfo *setterId, ParsedAttr::Syntax syntaxUsed)
Add microsoft __delspec(property) attribute.
Public Member Functions inherited from clang::ParsedAttributesView
bool empty () const
SizeType size () const
ParsedAttr & operator[] (SizeType pos)
const ParsedAttr & operator[] (SizeType pos) const
void addAtEnd (ParsedAttr *newAttr)
void remove (ParsedAttr *ToBeRemoved)
void clearListOnly ()
void addAll (iterator B, iterator E)
void addAll (const_iterator B, const_iterator E)
void addAllAtEnd (iterator B, iterator E)
void addAllAtEnd (const_iterator B, const_iterator E)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
ParsedAttr & front ()
const ParsedAttr & front () const
ParsedAttr & back ()
const ParsedAttr & back () const
bool hasAttribute (ParsedAttr::Kind K) const
Additional Inherited Members
Public Attributes inherited from clang::ParsedAttributesView
SourceRange Range
Detailed Description
ParsedAttributes - A collection of parsed attributes.
Currently we don't differentiate between the various attribute syntaxes, which is basically silly.
Right now this is a very lightweight container, but the expectation is that this will become significantly more serious.
Definition at line 1006 of file ParsedAttr.h.
Constructor & Destructor Documentation
ParsedAttributes() [1/2]
clang::ParsedAttributes::ParsedAttributes (AttributeFactory & factory) inline
Definition at line 1008 of file ParsedAttr.h.
ParsedAttributes() [2/2]
clang::ParsedAttributes::ParsedAttributes (const ParsedAttributes &) delete
Member Function Documentation
addNew() [1/3]
ParsedAttr* clang::ParsedAttributes::addNew (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, ArgsUnion * args, unsigned numArgs, ParsedAttr::Syntax syntax, SourceLocation ellipsisLoc = SourceLocation()) inline
Add attribute with expression arguments.
Definition at line 1037 of file ParsedAttr.h.
References clang::ParsedAttributesView::addAtEnd(), clang::ast_matchers::attr, and clang::AttributePool::create().
addNew() [2/3]
ParsedAttr* clang::ParsedAttributes::addNew (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, IdentifierLoc * Param, const AvailabilityChange & introduced, const AvailabilityChange & deprecated, const AvailabilityChange & obsoleted, SourceLocation unavailable, const Expr * MessageExpr, ParsedAttr::Syntax syntax, SourceLocation strict, const Expr * ReplacementExpr) inline
Add availability attribute.
Definition at line 1049 of file ParsedAttr.h.
References clang::ParsedAttributesView::addAtEnd(), clang::ast_matchers::attr, and clang::AttributePool::create().
addNew() [3/3]
ParsedAttr* clang::ParsedAttributes::addNew (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, IdentifierLoc * Param1, IdentifierLoc * Param2, IdentifierLoc * Param3, ParsedAttr::Syntax syntax) inline
Add objc_bridge_related attribute.
Definition at line 1065 of file ParsedAttr.h.
References clang::ParsedAttributesView::addAtEnd(), clang::ast_matchers::attr, and clang::AttributePool::create().
addNewPropertyAttr()
ParsedAttr* clang::ParsedAttributes::addNewPropertyAttr (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, IdentifierInfo * getterId, IdentifierInfo * setterId, ParsedAttr::Syntax syntaxUsed) inline
Add microsoft __delspec(property) attribute.
Definition at line 1102 of file ParsedAttr.h.
References clang::ParsedAttributesView::addAtEnd(), clang::ast_matchers::attr, and clang::AttributePool::createPropertyAttribute().
addNewTypeAttr()
ParsedAttr* clang::ParsedAttributes::addNewTypeAttr (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, ParsedType typeArg, ParsedAttr::Syntax syntaxUsed) inline
Add an attribute with a single type argument.
Definition at line 1090 of file ParsedAttr.h.
References clang::ParsedAttributesView::addAtEnd(), clang::ast_matchers::attr, and clang::AttributePool::createTypeAttribute().
addNewTypeTagForDatatype()
ParsedAttr* clang::ParsedAttributes::addNewTypeTagForDatatype (IdentifierInfo * attrName, SourceRange attrRange, IdentifierInfo * scopeName, SourceLocation scopeLoc, IdentifierLoc * argumentKind, ParsedType matchingCType, bool layoutCompatible, bool mustBeNull, ParsedAttr::Syntax syntax) inline
Add type_tag_for_datatype attribute.
Definition at line 1077 of file ParsedAttr.h.
References clang::ParsedAttributesView::addAtEnd(), clang::ast_matchers::attr, and clang::AttributePool::createTypeTagForDatatype().
clear()
void clang::ParsedAttributes::clear () inline
Definition at line 1030 of file ParsedAttr.h.
References clang::AttributePool::clear(), clang::ParsedAttributesView::clearListOnly(), and clang::ParsedAttributesView::Range.
getPool()
AttributePool& clang::ParsedAttributes::getPool () const inline
Definition at line 1011 of file ParsedAttr.h.
Referenced by addContextSensitiveTypeNullability(), clang::DeclSpec::getAttributePool(), clang::Declarator::getAttributePool(), takeDeclAttributes(), and takeOneFrom().
takeAllFrom()
void clang::ParsedAttributes::takeAllFrom (ParsedAttributes & Other) inline
Definition at line 1013 of file ParsedAttr.h.
References clang::ParsedAttributesView::addAll(), clang::ParsedAttributesView::begin(), clang::ParsedAttributesView::clearListOnly(), clang::ParsedAttributesView::end(), and clang::AttributePool::takeAllFrom().
Referenced by clang::DeclaratorChunk::getFunction(), clang::Declarator::takeAttributes(), and clang::DeclSpec::takeAttributesFrom().
takeOneFrom()
void clang::ParsedAttributes::takeOneFrom (ParsedAttributes & Other, ParsedAttr * PA) inline
Definition at line 1021 of file ParsedAttr.h.
References clang::ParsedAttributesView::addAtEnd(), getPool(), and clang::ParsedAttributesView::remove().
Referenced by distributeObjCPointerTypeAttrFromDeclarator().
The documentation for this class was generated from the following file:
include/clang/Sema/ParsedAttr.h