clang: lib/CodeGen/CodeGenTBAA.cpp File Reference
CodeGenTBAA.cpp File Reference
#include "CodeGenTBAA.h"
#include "CGRecordLayout.h"
#include "CodeGenTypes.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/RecordLayout.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
Functions
static bool TypeHasMayAlias (QualType QTy)
static bool isValidBaseType (QualType QTy)
Check if the given type is a valid base type to be used in access tags.
Function Documentation
isValidBaseType()
static bool isValidBaseType (QualType QTy) static
Check if the given type is a valid base type to be used in access tags.
Definition at line 100 of file CodeGenTBAA.cpp.
References clang::Type::getAs(), clang::RecordDecl::getDefinition(), clang::RecordDecl::hasFlexibleArrayMember(), clang::TagDecl::isClass(), and clang::TagDecl::isStruct().
Referenced by clang::CodeGen::CodeGenTBAA::getBaseTypeInfo(), and clang::CodeGen::CodeGenTBAA::getTypeInfo().
TypeHasMayAlias()
static bool TypeHasMayAlias (QualType QTy) static
Definition at line 82 of file CodeGenTBAA.cpp.
References clang::Type::getAs(), and clang::Type::getAsTagDecl().
Referenced by clang::CodeGen::CodeGenTBAA::getAccessInfo(), clang::CodeGen::CodeGenTBAA::getTBAAStructInfo(), and clang::CodeGen::CodeGenTBAA::getTypeInfo().