clang: lib/CodeGen/CodeGenAction.cpp File Reference
CodeGenAction.cpp File Reference
#include "clang/CodeGen/CodeGenAction.h"
#include "CGCall.h"
#include "CodeGenModule.h"
#include "CoverageMappingGen.h"
#include "MacroPPCallbacks.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclGroup.h"
#include "clang/Basic/DiagnosticFrontend.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/LangStandard.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/CodeGen/BackendUtil.h"
#include "clang/CodeGen/ModuleBuilder.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendActions.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "clang/Frontend/MultiplexConsumer.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Serialization/ASTWriter.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/CodeGen/MachineOptimizationRemarkEmitter.h"
#include "llvm/Demangle/Demangle.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LLVMRemarkStreamer.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/LTO/LTOBackend.h"
#include "llvm/Linker/Linker.h"
#include "llvm/Pass.h"
#include "llvm/SYCLLowerIR/LowerWGScope.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Transforms/IPO/Internalize.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include <memory>
#include <optional>
Classes
class clang::ClangDiagnosticHandler
class clang::BackendConsumer
Namespaces
llvm
Diagnostic wrappers for TextAPI types for error reporting.
clang
The JSON file list parser is used to communicate input to InstallAPI.
Macros
#define DEBUG_TYPE "codegenaction"
#define ComputeDiagID(Severity, GroupName, DiagID)
#define ComputeDiagRemarkID(Severity, GroupName, DiagID)
Functions
static void clang::reportOptRecordError (Error E, DiagnosticsEngine &Diags, const CodeGenOptions &CodeGenOpts)
static FullSourceLoc ConvertBackendLocation (const llvm::SMDiagnostic &D, SourceManager &CSM)
ConvertBackendLocation - Convert a location in a temporary llvm::SourceMgr buffer to be a valid FullSourceLoc.
static std::unique_ptr< raw_pwrite_stream > GetOutputStream (CompilerInstance &CI, StringRef InFile, BackendAction Action)
Variables
cl::opt< bool > llvm::ClRelinkBuiltinBitcodePostop
Macro Definition Documentation
ComputeDiagID
#define ComputeDiagID (Severity, GroupName, DiagID)
Value:
  do {                                                                         \
    switch (Severity) {                                                        \
    case llvm::DS_Error:                                                       \
      DiagID = diag::err_fe_##GroupName;                                       \
      break;                                                                   \
    case llvm::DS_Warning:                                                     \
      DiagID = diag::warn_fe_##GroupName;                                      \
      break;                                                                   \
    case llvm::DS_Remark:                                                      \
      llvm_unreachable("'remark' severity not expected");                      \
      break;                                                                   \
    case llvm::DS_Note:                                                        \
      DiagID = diag::note_fe_##GroupName;                                      \
      break;                                                                   \
    }                                                                          \
  } while (false)
Definition at line 555 of file CodeGenAction.cpp.
ComputeDiagRemarkID
#define ComputeDiagRemarkID (Severity, GroupName, DiagID)
Value:
  do {                                                                         \
    switch (Severity) {                                                        \
    case llvm::DS_Error:                                                       \
      DiagID = diag::err_fe_##GroupName;                                       \
      break;                                                                   \
    case llvm::DS_Warning:                                                     \
      DiagID = diag::warn_fe_##GroupName;                                      \
      break;                                                                   \
    case llvm::DS_Remark:                                                      \
      DiagID = diag::remark_fe_##GroupName;                                    \
      break;                                                                   \
    case llvm::DS_Note:                                                        \
      DiagID = diag::note_fe_##GroupName;                                      \
      break;                                                                   \
    }                                                                          \
  } while (false)
Definition at line 573 of file CodeGenAction.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "codegenaction"
Definition at line 63 of file CodeGenAction.cpp.
Function Documentation
ConvertBackendLocation()
static FullSourceLoc ConvertBackendLocation (const llvm::SMDiagnostic & D, SourceManager & CSM) static
ConvertBackendLocation - Convert a location in a temporary llvm::SourceMgr buffer to be a valid FullSourceLoc.
Definition at line 528 of file CodeGenAction.cpp.
References clang::SourceManager::createFileID(), clang::SourceManager::getLocForStartOfFile(), clang::SourceLocation::getLocWithOffset(), and Offset.
Referenced by clang::BackendConsumer::SrcMgrDiagHandler().
GetOutputStream()
static std::unique_ptr<raw_pwrite_stream> GetOutputStream (CompilerInstance & CI, StringRef InFile, BackendAction Action) static
Definition at line 1126 of file CodeGenAction.cpp.
References clang::Backend_EmitAssembly, clang::Backend_EmitBC, clang::Backend_EmitLL, clang::Backend_EmitMCNull, clang::Backend_EmitNothing, clang::Backend_EmitObj, clang::CompilerInstance::createDefaultOutputFile(), and clang::CompilerInstance::createNullOutputFile().
Referenced by clang::CodeGenAction::CreateASTConsumer(), and clang::CodeGenAction::ExecuteAction().