clang: lib/CodeGen/CodeGenFunction.cpp File Reference
CodeGenFunction.cpp File Reference
#include "CodeGenFunction.h"
#include "CGBlocks.h"
#include "CGCUDARuntime.h"
#include "CGCXXABI.h"
#include "CGCleanup.h"
#include "CGDebugInfo.h"
#include "CGHLSLRuntime.h"
#include "CGOpenMPRuntime.h"
#include "CGSYCLRuntime.h"
#include "CodeGenModule.h"
#include "CodeGenPGO.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/Expr.h"
#include "clang/AST/StmtCXX.h"
#include "clang/AST/StmtObjC.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/TargetBuiltins.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/CodeGen/CGFunctionInfo.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/FPEnv.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/CRC.h"
#include "llvm/Support/xxhash.h"
#include "llvm/Transforms/Scalar/LowerExpectIntrinsic.h"
#include "llvm/Transforms/Utils/PromoteMemToReg.h"
#include <optional>
#include "clang/AST/TypeNodes.inc"
#include "clang/Basic/Sanitizers.def"
Namespaces
llvm
Diagnostic wrappers for TextAPI types for error reporting.
Macros
#define TYPE(name, parent)
#define ABSTRACT_TYPE(name, parent)
#define NON_CANONICAL_TYPE(name, parent) case Type::name:
#define DEPENDENT_TYPE(name, parent) case Type::name:
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(name, parent) case Type::name:
#define SANITIZER(NAME, ID)
#define TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base) case Type::Class:
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
Functions
static bool shouldEmitLifetimeMarkers (const CodeGenOptions &CGOpts, const LangOptions &LangOpts)
shouldEmitLifetimeMarkers - Decide whether we need emit the life-time markers.
static LValue MakeNaturalAlignAddrLValue (llvm::Value *V, QualType T, bool ForPointeeType, CodeGenFunction &CGF)
static void EmitIfUsed (CodeGenFunction &CGF, llvm::BasicBlock *BB)
static bool endsWithReturn (const Decl *F)
Determine whether the function F ends with a return stmt.
static bool matchesStlAllocatorFn (const Decl *D, const ASTContext &Ctx)
static llvm::Constant * getPrologueSignature (CodeGenModule &CGM, const FunctionDecl *FD)
Return the UBSan prologue signature for FD if one is available.
static void TryMarkNoThrow (llvm::Function *F)
Tries to mark the given function nounwind based on the non-existence of any throwing calls within it.
static void emitNonZeroVLAInit (CodeGenFunction &CGF, QualType baseType, Address dest, Address src, llvm::Value *sizeInChars)
emitNonZeroVLAInit - Emit the "zero" initialization of a variable-length array whose elements have a non-zero bit-pattern.
static void CreateMultiVersionResolverReturn (CodeGenModule &CGM, llvm::Function *Resolver, CGBuilderTy &Builder, llvm::Function *FuncToReturn, bool SupportsIFunc)
Macro Definition Documentation
ABSTRACT_TYPE [1/2]
#define ABSTRACT_TYPE (Class, Base)
ABSTRACT_TYPE [2/2]
#define ABSTRACT_TYPE (name, parent)
DEPENDENT_TYPE [1/2]
#define DEPENDENT_TYPE (Class, Base) case Type::Class:
DEPENDENT_TYPE [2/2]
#define DEPENDENT_TYPE (name, parent) case Type::name:
NON_CANONICAL_TYPE [1/2]
#define NON_CANONICAL_TYPE (Class, Base)
NON_CANONICAL_TYPE [2/2]
#define NON_CANONICAL_TYPE (name, parent) case Type::name:
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [1/2]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE [2/2]
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (name, parent) case Type::name:
SANITIZER
#define SANITIZER (NAME, ID)
Value:
  if (SanOpts.empty())                                                         \
    break;                                                                     \
  if (SanOpts.has(SanitizerKind::ID))                                          \
    if (CGM.isInNoSanitizeList(SanitizerKind::ID, Fn, Loc))                    \
      SanOpts.set(SanitizerKind::ID, false);
TYPE [1/2]
#define TYPE (Class, Base)
TYPE [2/2]
#define TYPE (name, parent)
Function Documentation
CreateMultiVersionResolverReturn()
static void CreateMultiVersionResolverReturn (CodeGenModule & CGM, llvm::Function * Resolver, CGBuilderTy & Builder, llvm::Function * FuncToReturn, bool SupportsIFunc) static
Definition at line 3161 of file CodeGenFunction.cpp.
References clang::CodeGen::CodeGenFunction::Builder.
EmitIfUsed()
static void EmitIfUsed (CodeGenFunction & CGF, llvm::BasicBlock * BB) static
Definition at line 339 of file CodeGenFunction.cpp.
References clang::CodeGen::CodeGenFunction::CurFn.
Referenced by clang::CodeGen::CodeGenFunction::FinishFunction().
emitNonZeroVLAInit()
static void emitNonZeroVLAInit (CodeGenFunction & CGF, QualType baseType, Address dest, Address src, llvm::Value * sizeInChars) static
emitNonZeroVLAInit - Emit the "zero" initialization of a variable-length array whose elements have a non-zero bit-pattern.
Parameters
baseType the inner-most element type of the array
src - a char* pointing to the bit-pattern for a single base element of the array
sizeInChars - the total size of the VLA, in chars
Definition at line 2298 of file CodeGenFunction.cpp.
References clang::CharUnits::alignmentOfArrayElement(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::createBasicBlock(), clang::CodeGen::CGBuilderTy::CreateInBoundsGEP(), clang::CodeGen::CGBuilderTy::CreateMemCpy(), clang::CodeGen::CodeGenFunction::EmitBlock(), clang::CodeGen::Address::emitRawPointer(), clang::CodeGen::Address::getAlignment(), clang::CodeGen::CodeGenFunction::getContext(), clang::CodeGen::Address::getElementType(), clang::CharUnits::getQuantity(), clang::CodeGen::Address::getType(), clang::ASTContext::getTypeSizeInChars(), clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::CodeGen::CodeGenTypeCache::IntPtrTy, and clang::CodeGen::Address::withElementType().
Referenced by clang::CodeGen::CodeGenFunction::EmitNullInitialization().
endsWithReturn()
static bool endsWithReturn (const Decl * F) static
Determine whether the function F ends with a return stmt.
Definition at line 841 of file CodeGenFunction.cpp.
References clang::FunctionDecl::getBody().
Referenced by clang::CodeGen::CodeGenFunction::StartFunction().
getPrologueSignature()
static llvm::Constant* getPrologueSignature (CodeGenModule & CGM, const FunctionDecl * FD) static
Return the UBSan prologue signature for FD if one is available.
Definition at line 904 of file CodeGenFunction.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::CodeGen::TargetCodeGenInfo::getUBSanFunctionSignature(), and clang::CXXMethodDecl::isStatic().
Referenced by clang::CodeGen::CodeGenFunction::StartFunction().
MakeNaturalAlignAddrLValue()
static LValue MakeNaturalAlignAddrLValue (llvm::Value * V, QualType T, bool ForPointeeType, CodeGenFunction & CGF) static
Definition at line 198 of file CodeGenFunction.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::ConvertTypeForMem(), clang::CodeGen::CodeGenModule::getNaturalTypeAlignment(), clang::CodeGen::CodeGenFunction::MakeAddrLValue(), clang::T, and V.
Referenced by clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue(), clang::CodeGen::CodeGenFunction::MakeNaturalAlignPointeeAddrLValue(), clang::CodeGen::CodeGenFunction::MakeNaturalAlignPointeeRawAddrLValue(), and clang::CodeGen::CodeGenFunction::MakeNaturalAlignRawAddrLValue().
matchesStlAllocatorFn()
static bool matchesStlAllocatorFn (const Decl * D, const ASTContext & Ctx) static
Definition at line 870 of file CodeGenFunction.cpp.
References clang::ASTContext::getSizeType().
Referenced by clang::CodeGen::CodeGenFunction::StartFunction().
shouldEmitLifetimeMarkers()
static bool shouldEmitLifetimeMarkers (const CodeGenOptions & CGOpts, const LangOptions & LangOpts) static
shouldEmitLifetimeMarkers - Decide whether we need emit the life-time markers.
Definition at line 64 of file CodeGenFunction.cpp.
TryMarkNoThrow()
static void TryMarkNoThrow (llvm::Function * F) static
Tries to mark the given function nounwind based on the non-existence of any throwing calls within it.
We believe this is lightweight enough to do at -O0.
Definition at line 1552 of file CodeGenFunction.cpp.
Referenced by clang::CodeGen::CodeGenFunction::GenerateCode().