clang: lib/CodeGen/CodeGenModule.cpp File Reference
CodeGenModule.cpp File Reference
#include "CodeGenModule.h"
#include "ABIInfo.h"
#include "CGBlocks.h"
#include "CGCUDARuntime.h"
#include "CGCXXABI.h"
#include "CGCall.h"
#include "CGDebugInfo.h"
#include "CGHLSLRuntime.h"
#include "CGObjCRuntime.h"
#include "CGOpenCLRuntime.h"
#include "CGOpenMPRuntime.h"
#include "CGOpenMPRuntimeGPU.h"
#include "CGSYCLRuntime.h"
#include "CodeGenFunction.h"
#include "CodeGenPGO.h"
#include "ConstantEmitter.h"
#include "CoverageMappingGen.h"
#include "TargetInfo.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/Version.h"
#include "clang/CodeGen/BackendUtil.h"
#include "clang/CodeGen/ConstantInitBuilder.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaSYCL.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/AttributeMask.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/ProfileData/SampleProf.h"
#include "llvm/Support/CRC.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/Support/xxhash.h"
#include "llvm/TargetParser/RISCVISAInfo.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/TargetParser/X86TargetParser.h"
#include <optional>
Functions
static llvm::cl::opt< bool > LimitedCoverage ("limited-coverage-experimental", llvm::cl::Hidden, llvm::cl::desc("Emit limited coverage mapping information (experimental)"))
static CGCXXABI * createCXXABI (CodeGenModule &CGM)
static bool SYCLCUDAIsHost (const clang::LangOptions &LangOpts)
static bool SYCLCUDAIsSYCLDevice (const clang::LangOptions &LangOpts)
static std::unique_ptr< TargetCodeGenInfo > createTargetCodeGenInfo (CodeGenModule &CGM)
static const llvm::GlobalValue * getAliasedGlobal (const llvm::GlobalValue *GV)
static bool checkAliasedGlobal (const ASTContext &Context, DiagnosticsEngine &Diags, SourceLocation Location, bool IsIFunc, const llvm::GlobalValue *Alias, const llvm::GlobalValue *&GV, const llvm::MapVector< GlobalDecl, StringRef > &MangledDeclNames, SourceRange AliasRange)
static void checkAliasForTocData (llvm::GlobalVariable *GVar, const CodeGenOptions &CodeGenOpts, DiagnosticsEngine &Diags, SourceLocation Location)
static std::optional< llvm::GlobalValue::VisibilityTypes > getLLVMVisibility (clang::LangOptions::VisibilityFromDLLStorageClassKinds K)
void setLLVMVisibility (llvm::GlobalValue &GV, std::optional< llvm::GlobalValue::VisibilityTypes > V)
static void setVisibilityFromDLLStorageClass (const clang::LangOptions &LO, llvm::Module &M)
static llvm::MDNode * getAspectsMD (ASTContext &ASTContext, llvm::LLVMContext &Ctx, StringRef Name, const SYCLUsesAspectsAttr *A)
static llvm::MDNode * getAspectEnumValueMD (ASTContext &ASTContext, llvm::LLVMContext &Ctx, const EnumConstantDecl *ECD)
static bool isStackProtectorOn (const LangOptions &LangOpts, const llvm::Triple &Triple, clang::LangOptions::StackProtectorMode Mode)
static bool shouldAssumeDSOLocal (const CodeGenModule &CGM, llvm::GlobalValue *GV)
static llvm::GlobalVariable::ThreadLocalMode GetLLVMTLSModel (StringRef S)
static std::string getCPUSpecificMangling (const CodeGenModule &CGM, StringRef Name)
static void AppendCPUSpecificCPUDispatchMangling (const CodeGenModule &CGM, const CPUSpecificAttr *Attr, unsigned CPUIndex, raw_ostream &Out)
static bool isUniqueInternalLinkageDecl (GlobalDecl GD, CodeGenModule &CGM)
static std::string getMangledNameImpl (CodeGenModule &CGM, GlobalDecl GD, const NamedDecl *ND, bool OmitMultiVersionMangling=false)
static void removeImageAccessQualifier (std::string &TyName)
static unsigned ArgInfoAddressSpace (LangAS AS)
static bool hasUnwindExceptions (const LangOptions &LangOpts)
Determines whether the language options require us to model unwind exceptions.
static bool requiresMemberFunctionPointerTypeMetadata (CodeGenModule &CGM, const CXXMethodDecl *MD)
static bool checkIfDeclaredInSYCLNamespace (const Decl *D)
Function checks whether given DeclContext contains a topmost namespace with name "sycl".
static void setLinkageForGV (llvm::GlobalValue *GV, const NamedDecl *ND)
static bool allowKCFIIdentifier (StringRef Name)
template<typename AttrT >
void applySYCLAspectsMD (AttrT *A, ASTContext &ACtx, llvm::LLVMContext &LLVMCtx, llvm::Function *F, StringRef MDName)
static void emitUsed (CodeGenModule &CGM, StringRef Name, std::vector< llvm::WeakTrackingVH > &List)
static void addLinkOptionsPostorder (CodeGenModule &CGM, Module *Mod, SmallVectorImpl< llvm::MDNode * > &Metadata, llvm::SmallPtrSet< Module *, 16 > &Visited)
Add link options implied by the given module, including modules it depends on, using a postorder walk.
static void addSYCLUniqueID (llvm::GlobalVariable *GV, const VarDecl *VD, ASTContext &Context)
template<typename AttrT >
static bool hasImplicitAttr (const ValueDecl *D)
static bool HasNonDllImportDtor (QualType T)
static void ReplaceUsesOfNonProtoTypeWithRealFunction (llvm::GlobalValue *Old, llvm::Function *NewFn)
ReplaceUsesOfNonProtoTypeWithRealFunction - This function is called when we implement a function with no prototype, e.g.
static unsigned TargetMVPriority (const TargetInfo &TI, const CodeGenFunction::MultiVersionResolverOption &RO)
llvm::GlobalValue::LinkageTypes getMultiversionLinkage (CodeGenModule &CGM, GlobalDecl GD)
static FunctionDecl * createDefaultTargetVersionFrom (const FunctionDecl *FD)
static const FunctionDecl * GetRuntimeFunctionDecl (ASTContext &C, StringRef Name)
static void maybeEmitPipeStorageMetadata (const VarDecl *D, llvm::GlobalVariable *GV, CodeGenModule &CGM)
static llvm::Constant * castStringLiteralToDefaultAddressSpace (CodeGenModule &CGM, llvm::GlobalVariable *GV)
static bool shouldBeInCOMDAT (CodeGenModule &CGM, const Decl &D)
static bool isVarDeclStrongDefinition (const ASTContext &Context, CodeGenModule &CGM, const VarDecl *D, bool NoCommon)
static void replaceUsesOfNonProtoConstant (llvm::Constant *old, llvm::Function *newFn)
Replace the uses of a function that was declared with a non-proto type.
static llvm::StringMapEntry< llvm::GlobalVariable * > & GetConstantCFStringEntry (llvm::StringMap< llvm::GlobalVariable * > &Map, const StringLiteral *Literal, bool TargetIsLSB, bool &IsUTF16, unsigned &StringLength)
static llvm::GlobalVariable * GenerateStringLiteral (llvm::Constant *C, llvm::GlobalValue::LinkageTypes LT, CodeGenModule &CGM, StringRef GlobalName, CharUnits Alignment)
static bool needsDestructMethod (ObjCImplementationDecl *impl)
static bool AllTrivialInitializers (CodeGenModule &CGM, ObjCImplementationDecl *D)
static llvm::Constant * GetPointerConstant (llvm::LLVMContext &Context, const void *Ptr)
Turns the given pointer into a constant.
static void EmitGlobalDeclMetadata (CodeGenModule &CGM, llvm::NamedMDNode *&GlobalMetadata, GlobalDecl D, llvm::GlobalValue *Addr)
static QualType GeneralizeType (ASTContext &Ctx, QualType Ty)
static QualType GeneralizeFunctionType (ASTContext &Ctx, QualType Ty)
Variables
static const char AnnotationSection [] = "llvm.metadata"
Function Documentation
addLinkOptionsPostorder()
static void addLinkOptionsPostorder (CodeGenModule & CGM, Module * Mod, SmallVectorImpl< llvm::MDNode * > & Metadata, llvm::SmallPtrSet< Module *, 16 > & Visited) static
Add link options implied by the given module, including modules it depends on, using a postorder walk.
Definition at line 3181 of file CodeGenModule.cpp.
References clang::Module::Imports, clang::Module::Parent, and Visited.
addSYCLUniqueID()
static void addSYCLUniqueID (llvm::GlobalVariable * GV, const VarDecl * VD, ASTContext & Context) static
Definition at line 3663 of file CodeGenModule.cpp.
allowKCFIIdentifier()
static bool allowKCFIIdentifier (StringRef Name) static
Definition at line 2921 of file CodeGenModule.cpp.
AllTrivialInitializers()
static bool AllTrivialInitializers (CodeGenModule & CGM, ObjCImplementationDecl * D) static
Definition at line 7262 of file CodeGenModule.cpp.
References clang::CXXCtorInitializer::getInit(), clang::ObjCImplementationDecl::init_begin(), clang::ObjCImplementationDecl::init_end(), and clang::CodeGen::CodeGenFunction::isTrivialInitializer().
AppendCPUSpecificCPUDispatchMangling()
static void AppendCPUSpecificCPUDispatchMangling (const CodeGenModule & CGM, const CPUSpecificAttr * Attr, unsigned CPUIndex, raw_ostream & Out) static
Definition at line 1847 of file CodeGenModule.cpp.
References getCPUSpecificMangling(), clang::CodeGen::CodeGenModule::getTarget(), and clang::TargetInfo::supportsIFunc().
Referenced by getMangledNameImpl().
applySYCLAspectsMD()
template<typename AttrT > void applySYCLAspectsMD (AttrT * A, ASTContext & ACtx, llvm::LLVMContext & LLVMCtx, llvm::Function * F, StringRef MDName)
Definition at line 2962 of file CodeGenModule.cpp.
References clang::T.
ArgInfoAddressSpace()
static unsigned ArgInfoAddressSpace (LangAS AS) static
Definition at line 2237 of file CodeGenModule.cpp.
References clang::opencl_constant, clang::opencl_generic, clang::opencl_global, clang::opencl_global_device, clang::opencl_global_host, clang::opencl_local, clang::sycl_global, clang::sycl_global_device, clang::sycl_global_host, and clang::sycl_local.
Referenced by clang::CodeGen::CodeGenModule::GenKernelArgMetadata().
castStringLiteralToDefaultAddressSpace()
static llvm::Constant* castStringLiteralToDefaultAddressSpace (CodeGenModule & CGM, llvm::GlobalVariable * GV) static
Definition at line 5660 of file CodeGenModule.cpp.
References clang::interp::Cast(), clang::Default, clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::GetGlobalConstantAddressSpace(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::ASTContext::getTargetAddressSpace(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), and clang::CodeGen::TargetCodeGenInfo::performAddrSpaceCast().
checkAliasedGlobal()
static bool checkAliasedGlobal (const ASTContext & Context, DiagnosticsEngine & Diags, SourceLocation Location, bool IsIFunc, const llvm::GlobalValue * Alias, const llvm::GlobalValue *& GV, const llvm::MapVector< GlobalDecl, StringRef > & MangledDeclNames, SourceRange AliasRange) static
Definition at line 592 of file CodeGenModule.cpp.
checkAliasForTocData()
static void checkAliasForTocData (llvm::GlobalVariable * GVar, const CodeGenOptions & CodeGenOpts, DiagnosticsEngine & Diags, SourceLocation Location) static
Definition at line 653 of file CodeGenModule.cpp.
References clang::DiagnosticsEngine::Report(), and clang::CodeGenOptions::TocDataVarsUserSpecified.
checkIfDeclaredInSYCLNamespace()
static bool checkIfDeclaredInSYCLNamespace (const Decl * D) static
Function checks whether given DeclContext contains a topmost namespace with name "sycl".
Definition at line 2512 of file CodeGenModule.cpp.
References clang::Decl::getDeclContext(), clang::DeclContext::getEnclosingNamespaceContext(), and Parent.
Referenced by clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition().
createCXXABI()
static CGCXXABI* createCXXABI (CodeGenModule & CGM) static
Definition at line 90 of file CodeGenModule.cpp.
References clang::CodeGen::CreateItaniumCXXABI(), clang::CodeGen::CreateMicrosoftCXXABI(), clang::CodeGen::CodeGenModule::getContext(), and clang::ASTContext::getCXXABIKind().
createDefaultTargetVersionFrom()
static FunctionDecl* createDefaultTargetVersionFrom (const FunctionDecl * FD) static
Definition at line 4544 of file CodeGenModule.cpp.
References clang::Decl::getASTContext(), clang::FunctionDecl::getStorageClass(), clang::ASTContext::getTranslationUnitDecl(), and clang::DeclaratorDecl::getTypeSourceInfo().
createTargetCodeGenInfo()
static std::unique_ptr<TargetCodeGenInfo> createTargetCodeGenInfo (CodeGenModule & CGM) static
Definition at line 120 of file CodeGenModule.cpp.
References clang::CodeGen::AAPCS, clang::CodeGen::AAPCS16_VFP, clang::CodeGen::AAPCS_VFP, clang::CodeGen::AAPCSSoft, clang::CodeGen::APCS, clang::CodeGen::AVX, clang::CodeGen::AVX512, clang::CodeGen::createAArch64TargetCodeGenInfo(), clang::CodeGen::createAIXTargetCodeGenInfo(), clang::CodeGen::createAMDGPUTargetCodeGenInfo(), clang::CodeGen::createARCTargetCodeGenInfo(), clang::CodeGen::createARMTargetCodeGenInfo(), clang::CodeGen::createAVRTargetCodeGenInfo(), clang::CodeGen::createBPFTargetCodeGenInfo(), clang::CodeGen::createCommonSPIRTargetCodeGenInfo(), clang::CodeGen::createCSKYTargetCodeGenInfo(), clang::CodeGen::createDefaultTargetCodeGenInfo(), clang::CodeGen::createHexagonTargetCodeGenInfo(), clang::CodeGen::createLanaiTargetCodeGenInfo(), clang::CodeGen::createLoongArchTargetCodeGenInfo(), clang::CodeGen::createM68kTargetCodeGenInfo(), clang::CodeGen::createMIPSTargetCodeGenInfo(), clang::CodeGen::createMSP430TargetCodeGenInfo(), clang::CodeGen::createNVPTXTargetCodeGenInfo(), clang::CodeGen::createPNaClTargetCodeGenInfo(), clang::CodeGen::createPPC32TargetCodeGenInfo(), clang::CodeGen::createPPC64_SVR4_TargetCodeGenInfo(), clang::CodeGen::createPPC64TargetCodeGenInfo(), clang::CodeGen::createRISCVTargetCodeGenInfo(), clang::CodeGen::createSparcV8TargetCodeGenInfo(), clang::CodeGen::createSparcV9TargetCodeGenInfo(), clang::CodeGen::createSPIRVTargetCodeGenInfo(), clang::CodeGen::createSystemZTargetCodeGenInfo(), clang::CodeGen::createTCETargetCodeGenInfo(), clang::CodeGen::createVETargetCodeGenInfo(), clang::CodeGen::createWebAssemblyTargetCodeGenInfo(), clang::CodeGen::createWindowsAArch64TargetCodeGenInfo(), clang::CodeGen::createWindowsARMTargetCodeGenInfo(), clang::CodeGen::createWinX86_32TargetCodeGenInfo(), clang::CodeGen::createWinX86_64TargetCodeGenInfo(), clang::CodeGen::createX86_32TargetCodeGenInfo(), clang::CodeGen::createX86_64TargetCodeGenInfo(), clang::CodeGen::createXCoreTargetCodeGenInfo(), clang::CodeGen::DarwinPCS, clang::Default, clang::CodeGen::ELFv1, clang::CodeGen::ELFv2, clang::CodeGen::ExperimentalMV, clang::CodeGenOptions::FloatABI, clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTriple(), clang::CodeGen::MVP, clang::CodeGen::None, and clang::CodeGen::Win64.
Referenced by clang::CodeGen::CodeGenModule::getTargetCodeGenInfo().
EmitGlobalDeclMetadata()
static void EmitGlobalDeclMetadata (CodeGenModule & CGM, llvm::NamedMDNode *& GlobalMetadata, GlobalDecl D, llvm::GlobalValue * Addr) static
Definition at line 7778 of file CodeGenModule.cpp.
References clang::GlobalDecl::getDecl(), clang::CodeGen::CodeGenModule::getLLVMContext(), clang::CodeGen::CodeGenModule::getModule(), and GetPointerConstant().
emitUsed()
static void emitUsed (CodeGenModule & CGM, StringRef Name, std::vector< llvm::WeakTrackingVH > & List) static
Definition at line 3113 of file CodeGenModule.cpp.
GeneralizeFunctionType()
static QualType GeneralizeFunctionType (ASTContext & Ctx, QualType Ty) static
Definition at line 8070 of file CodeGenModule.cpp.
References GeneralizeType(), clang::Type::getAs(), clang::ASTContext::getFunctionNoProtoType(), and clang::ASTContext::getFunctionType().
Referenced by clang::CodeGen::CodeGenModule::CreateMetadataIdentifierGeneralized().
GeneralizeType()
static QualType GeneralizeType (ASTContext & Ctx, QualType Ty) static
Definition at line 8060 of file CodeGenModule.cpp.
References clang::QualType::getCVRQualifiers(), clang::Type::getPointeeType(), clang::ASTContext::getPointerType(), clang::Type::isPointerType(), clang::ASTContext::VoidTy, and clang::QualType::withCVRQualifiers().
Referenced by GeneralizeFunctionType().
GenerateStringLiteral()
static llvm::GlobalVariable* GenerateStringLiteral (llvm::Constant * C, llvm::GlobalValue::LinkageTypes LT, CodeGenModule & CGM, StringRef GlobalName, CharUnits Alignment) static
Definition at line 6973 of file CodeGenModule.cpp.
References clang::CharUnits::getAsAlign(), clang::CodeGen::CodeGenModule::getContext(), clang::CodeGen::CodeGenModule::GetGlobalConstantAddressSpace(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenModule::getModule(), clang::ASTContext::getTargetAddressSpace(), LT, clang::CodeGen::CodeGenModule::setDSOLocal(), and clang::CodeGen::CodeGenModule::supportsCOMDAT().
getAliasedGlobal()
static const llvm::GlobalValue* getAliasedGlobal (const llvm::GlobalValue * GV) static
Definition at line 572 of file CodeGenModule.cpp.
getAspectEnumValueMD()
static llvm::MDNode* getAspectEnumValueMD (ASTContext & ASTContext, llvm::LLVMContext & Ctx, const EnumConstantDecl * ECD) static
Definition at line 857 of file CodeGenModule.cpp.
References clang::EnumConstantDecl::getInitVal(), and clang::NamedDecl::getName().
getAspectsMD()
static llvm::MDNode* getAspectsMD (ASTContext & ASTContext, llvm::LLVMContext & Ctx, StringRef Name, const SYCLUsesAspectsAttr * A) static
Definition at line 844 of file CodeGenModule.cpp.
GetConstantCFStringEntry()
static llvm::StringMapEntry<llvm::GlobalVariable *>& GetConstantCFStringEntry (llvm::StringMap< llvm::GlobalVariable * > & Map, const StringLiteral * Literal, bool TargetIsLSB, bool & IsUTF16, unsigned & StringLength) static
Definition at line 6670 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::GetAddrOfConstantCFString().
getCPUSpecificMangling()
static std::string getCPUSpecificMangling (const CodeGenModule & CGM, StringRef Name) static
Definition at line 1841 of file CodeGenModule.cpp.
Referenced by AppendCPUSpecificCPUDispatchMangling().
GetLLVMTLSModel()
static llvm::GlobalVariable::ThreadLocalMode GetLLVMTLSModel (StringRef S) static
Definition at line 1804 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::setTLSMode().
getLLVMVisibility()
static std::optional<llvm::GlobalValue::VisibilityTypes> getLLVMVisibility (clang::LangOptions::VisibilityFromDLLStorageClassKinds K) static
Definition at line 776 of file CodeGenModule.cpp.
References clang::LangOptionsBase::Default, clang::DefaultVisibility, clang::LangOptionsBase::Hidden, clang::HiddenVisibility, clang::LangOptionsBase::Keep, clang::LangOptionsBase::Protected, and clang::ProtectedVisibility.
Referenced by setVisibilityFromDLLStorageClass().
getMangledNameImpl()
static std::string getMangledNameImpl (CodeGenModule & CGM, GlobalDecl GD, const NamedDecl * ND, bool OmitMultiVersionMangling = false) static
Definition at line 1868 of file CodeGenModule.cpp.
References AppendCPUSpecificCPUDispatchMangling(), clang::CC_X86RegCall, clang::CPUDispatch, clang::CPUSpecific, clang::CodeGen::TargetCodeGenInfo::getABIInfo(), clang::FunctionType::getCallConv(), clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::NamedDecl::getIdentifier(), clang::GlobalDecl::getKernelReferenceKind(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CGCXXABI::getMangleContext(), clang::CodeGen::CodeGenModule::getModuleNameHash(), clang::GlobalDecl::getMultiVersionIndex(), clang::IdentifierInfo::getName(), clang::CodeGen::CodeGenModule::getTargetCodeGenInfo(), clang::GlobalDecl::getWithDecl(), isUniqueInternalLinkageDecl(), clang::MangleContext::mangleName(), clang::MangleContext::needsUniqueInternalLinkageNames(), clang::MangleContext::shouldMangleDeclName(), clang::Stub, clang::Target, clang::TargetClones, and clang::TargetVersion.
Referenced by clang::CodeGen::CodeGenModule::getMangledName().
getMultiversionLinkage()
llvm::GlobalValue::LinkageTypes getMultiversionLinkage (CodeGenModule & CGM, GlobalDecl GD)
Definition at line 4536 of file CodeGenModule.cpp.
References clang::GlobalDecl::getDecl(), clang::NamedDecl::getFormalLinkage(), and clang::Internal.
GetPointerConstant()
static llvm::Constant* GetPointerConstant (llvm::LLVMContext & Context, const void * Ptr) static
Turns the given pointer into a constant.
Definition at line 7771 of file CodeGenModule.cpp.
Referenced by EmitGlobalDeclMetadata().
GetRuntimeFunctionDecl()
static const FunctionDecl* GetRuntimeFunctionDecl (ASTContext & C, StringRef Name) static
Definition at line 5145 of file CodeGenModule.cpp.
hasImplicitAttr()
template<typename AttrT > static bool hasImplicitAttr (const ValueDecl * D) static
Definition at line 3993 of file CodeGenModule.cpp.
References clang::Decl::getAttr(), and clang::Decl::isImplicit().
HasNonDllImportDtor()
static bool HasNonDllImportDtor (QualType T) static
Definition at line 4242 of file CodeGenModule.cpp.
References clang::Type::getAs(), clang::Type::getBaseElementTypeUnsafe(), and clang::T.
hasUnwindExceptions()
static bool hasUnwindExceptions (const LangOptions & LangOpts) static
Determines whether the language options require us to model unwind exceptions.
We treat -fexceptions as mandating this except under the fragile ObjC ABI with only ObjC exceptions enabled. This means, for example, that C with -fexceptions enables this.
Definition at line 2467 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition().
isStackProtectorOn()
static bool isStackProtectorOn (const LangOptions & LangOpts, const llvm::Triple & Triple, clang::LangOptions::StackProtectorMode Mode) static
Definition at line 868 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition().
isUniqueInternalLinkageDecl()
static bool isUniqueInternalLinkageDecl (GlobalDecl GD, CodeGenModule & CGM) static
Definition at line 1861 of file CodeGenModule.cpp.
References clang::GlobalDecl::getDecl(), clang::CodeGen::CodeGenModule::getFunctionLinkage(), and clang::CodeGen::CodeGenModule::getModuleNameHash().
Referenced by getMangledNameImpl().
isVarDeclStrongDefinition()
static bool isVarDeclStrongDefinition (const ASTContext & Context, CodeGenModule & CGM, const VarDecl * D, bool NoCommon) static
Definition at line 6169 of file CodeGenModule.cpp.
LimitedCoverage()
static llvm::cl::opt<bool> LimitedCoverage ("limited-coverage-experimental" , llvm::cl::Hidden , llvm::cl::desc("Emit limited coverage mapping information (experimental)")) static
Referenced by clang::CodeGen::CodeGenModule::AddDeferredUnusedCoverageMapping().
maybeEmitPipeStorageMetadata()
static void maybeEmitPipeStorageMetadata (const VarDecl * D, llvm::GlobalVariable * GV, CodeGenModule & CGM) static
Definition at line 5222 of file CodeGenModule.cpp.
References clang::Decl::getAttr(), clang::ValueDecl::getType(), ID, and clang::Type::isStructureType().
needsDestructMethod()
static bool needsDestructMethod (ObjCImplementationDecl * impl) static
Definition at line 7252 of file CodeGenModule.cpp.
References clang::ObjCInterfaceDecl::all_declared_ivar_begin(), clang::ObjCImplDecl::getClassInterface(), and clang::ObjCIvarDecl::getNextIvar().
removeImageAccessQualifier()
static void removeImageAccessQualifier (std::string & TyName) static
Definition at line 2211 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::GenKernelArgMetadata().
replaceUsesOfNonProtoConstant()
static void replaceUsesOfNonProtoConstant (llvm::Constant * old, llvm::Function * newFn) static
Replace the uses of a function that was declared with a non-proto type.
We want to silently drop extra arguments from call sites
Definition at line 6338 of file CodeGenModule.cpp.
Referenced by ReplaceUsesOfNonProtoTypeWithRealFunction().
ReplaceUsesOfNonProtoTypeWithRealFunction()
static void ReplaceUsesOfNonProtoTypeWithRealFunction (llvm::GlobalValue * Old, llvm::Function * NewFn) static
ReplaceUsesOfNonProtoTypeWithRealFunction - This function is called when we implement a function with no prototype, e.g.
"int foo() {}". If there are existing call uses of the old function in the module, this adjusts them to call the new function directly.
This is not just a cleanup: the always_inline pass requires direct calls to functions to be able to inline them. If there is a bitcast in the way, it won't inline them. Instcombine normally deletes these calls, but it isn't run at -O0.
Definition at line 6444 of file CodeGenModule.cpp.
References replaceUsesOfNonProtoConstant().
requiresMemberFunctionPointerTypeMetadata()
static bool requiresMemberFunctionPointerTypeMetadata (CodeGenModule & CGM, const CXXMethodDecl * MD) static
Definition at line 2482 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), clang::CXXMethodDecl::getParent(), clang::CodeGen::CodeGenModule::HasHiddenLTOVisibility(), clang::CXXMethodDecl::isImplicitObjectMemberFunction(), and clang::CXXMethodDecl::isVirtual().
Referenced by clang::CodeGen::CodeGenModule::SetLLVMFunctionAttributesForDefinition().
setLinkageForGV()
static void setLinkageForGV (llvm::GlobalValue * GV, const NamedDecl * ND) static
Definition at line 2881 of file CodeGenModule.cpp.
References clang::LinkageInfo::getLinkage(), clang::NamedDecl::getLinkageAndVisibility(), clang::Decl::hasAttr(), clang::isExternallyVisible(), clang::Decl::isWeakImported(), and clang::LinkageInfo::setLinkage().
setLLVMVisibility()
void setLLVMVisibility (llvm::GlobalValue & GV, std::optional< llvm::GlobalValue::VisibilityTypes > V)
Definition at line 791 of file CodeGenModule.cpp.
References V.
Referenced by setVisibilityFromDLLStorageClass().
setVisibilityFromDLLStorageClass()
static void setVisibilityFromDLLStorageClass (const clang::LangOptions & LO, llvm::Module & M) static
Definition at line 805 of file CodeGenModule.cpp.
References getLLVMVisibility(), and setLLVMVisibility().
shouldAssumeDSOLocal()
static bool shouldAssumeDSOLocal (const CodeGenModule & CGM, llvm::GlobalValue * GV) static
Definition at line 1656 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getCodeGenOpts(), and clang::CodeGen::CodeGenModule::getTriple().
Referenced by clang::CodeGen::CodeGenModule::setDSOLocal().
shouldBeInCOMDAT()
static bool shouldBeInCOMDAT (CodeGenModule & CGM, const Decl & D) static
Definition at line 5708 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::GetGVALinkageForFunction(), clang::ASTContext::GetGVALinkageForVariable(), clang::GVA_AvailableExternally, clang::GVA_DiscardableODR, clang::GVA_Internal, clang::GVA_StrongExternal, clang::GVA_StrongODR, clang::Decl::hasAttr(), and clang::CodeGen::CodeGenModule::supportsCOMDAT().
Referenced by clang::CodeGen::CodeGenModule::maybeSetTrivialComdat().
SYCLCUDAIsHost()
static bool SYCLCUDAIsHost (const clang::LangOptions & LangOpts) static
Definition at line 110 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::EmitGlobal().
SYCLCUDAIsSYCLDevice()
static bool SYCLCUDAIsSYCLDevice (const clang::LangOptions & LangOpts) static
Definition at line 114 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::EmitGlobal().
TargetMVPriority()
static unsigned TargetMVPriority (const TargetInfo & TI, const CodeGenFunction::MultiVersionResolverOption & RO) static
Definition at line 4513 of file CodeGenModule.cpp.
References clang::CodeGen::CodeGenFunction::MultiVersionResolverOption::Conds::Architecture, clang::CodeGen::CodeGenFunction::MultiVersionResolverOption::Conditions, clang::CodeGen::CodeGenFunction::MultiVersionResolverOption::Conds::Features, max(), clang::TargetInfo::multiVersionFeatureCost(), clang::TargetInfo::multiVersionSortPriority(), and Priority.
Variable Documentation
AnnotationSection
const char AnnotationSection[] = "llvm.metadata" static
Definition at line 88 of file CodeGenModule.cpp.
Referenced by clang::CodeGen::CodeGenModule::EmitAnnotationArgs(), clang::CodeGen::CodeGenModule::EmitAnnotationString(), clang::CodeGen::CodeGenModule::EmitGlobalAnnotations(), and clang::CodeGen::CodeGenModule::EmitSYCLAnnotationArgs().