clang: lib/CodeGen/Targets/AArch64.cpp File Reference
AArch64.cpp File Reference
#include "ABIInfoImpl.h"
#include "TargetInfo.h"
#include "clang/AST/Decl.h"
#include "clang/Basic/DiagnosticFrontend.h"
#include "llvm/TargetParser/AArch64TargetParser.h"
Functions
static bool isStreamingCompatible (const FunctionDecl *F)
static void diagnoseIfNeedsFPReg (DiagnosticsEngine &Diags, const StringRef ABIName, const AArch64ABIInfo &ABIInfo, const QualType &Ty, const NamedDecl *D)
Function Documentation
diagnoseIfNeedsFPReg()
static void diagnoseIfNeedsFPReg (DiagnosticsEngine & Diags, const StringRef ABIName, const AArch64ABIInfo & ABIInfo, const QualType & Ty, const NamedDecl * D) static
Definition at line 840 of file AArch64.cpp.
References D, clang::Decl::getLocation(), clang::Type::isFloatingType(), clang::CodeGen::ABIInfo::isHomogeneousAggregate(), clang::Type::isVectorType(), and clang::DiagnosticsEngine::Report().
isStreamingCompatible()
static bool isStreamingCompatible (const FunctionDecl * F) static
Definition at line 831 of file AArch64.cpp.
References clang::FunctionProtoType::getAArch64SMEAttributes(), clang::Type::getAs(), clang::ValueDecl::getType(), clang::FunctionType::SME_PStateSMCompatibleMask, and clang::T.