clang: lib/Driver/Compilation.cpp File Reference
Compilation.cpp File Reference
#include "clang/Driver/Compilation.h"
#include "clang/Basic/LLVM.h"
#include "clang/Driver/Action.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Job.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/ToolChain.h"
#include "clang/Driver/Util.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/OptSpecifier.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SimpleTable.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
#include <cassert>
#include <fstream>
#include <string>
#include <system_error>
#include <utility>
Typedefs
using FailingCommandList = SmallVectorImpl< std::pair< int, const Command * > >
Functions
static void HandleXarchArgs (DerivedArgList *OffloadArgList, const Driver &D, bool IsDevice)
static bool ActionFailed (const Action *A, const FailingCommandList &FailingCommands)
static bool InputsOk (const Command &C, const FailingCommandList &FailingCommands)
Typedef Documentation
FailingCommandList
using FailingCommandList = SmallVectorImpl<std::pair<int, const Command *> >
Definition at line 334 of file Compilation.cpp.
Function Documentation
ActionFailed()
static bool ActionFailed (const Action * A, const FailingCommandList & FailingCommands) static
Definition at line 336 of file Compilation.cpp.
References clang::driver::Action::inputs(), clang::driver::Action::isOffloading(), clang::driver::Action::OFK_Cuda, clang::driver::Action::OFK_HIP, and clang::driver::Action::OFK_SYCL.
Referenced by InputsOk().
HandleXarchArgs()
static void HandleXarchArgs (DerivedArgList * OffloadArgList, const Driver & D, bool IsDevice) static
Definition at line 63 of file Compilation.cpp.
Referenced by clang::driver::Compilation::getArgsForToolChain().
InputsOk()
static bool InputsOk (const Command & C, const FailingCommandList & FailingCommands) static
Definition at line 363 of file Compilation.cpp.
References ActionFailed().
Referenced by clang::driver::Compilation::ExecuteJobs().