clang: lib/Frontend/CompilerInstance.cpp File Reference
CompilerInstance.cpp File Reference
#include "clang/Frontend/CompilerInstance.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/DiagnosticOptions.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/LangStandard.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Stack.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/Version.h"
#include "clang/Config/config.h"
#include "clang/Frontend/ChainedDiagnosticConsumer.h"
#include "clang/Frontend/FrontendAction.h"
#include "clang/Frontend/FrontendActions.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "clang/Frontend/FrontendPluginRegistry.h"
#include "clang/Frontend/LogDiagnosticPrinter.h"
#include "clang/Frontend/SARIFDiagnosticPrinter.h"
#include "clang/Frontend/SerializedDiagnosticPrinter.h"
#include "clang/Frontend/TextDiagnosticPrinter.h"
#include "clang/Frontend/Utils.h"
#include "clang/Frontend/VerifyDiagnosticConsumer.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "clang/Sema/CodeCompleteConsumer.h"
#include "clang/Sema/Sema.h"
#include "clang/Serialization/ASTReader.h"
#include "clang/Serialization/GlobalModuleIndex.h"
#include "clang/Serialization/InMemoryModuleCache.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/BuryPointer.h"
#include "llvm/Support/CrashRecoveryContext.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/LockFileManager.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Host.h"
#include <optional>
#include <time.h>
#include <utility>
Functions
static void collectHeaderMaps (const HeaderSearch &HS, std::shared_ptr< ModuleDependencyCollector > MDC)
static void collectIncludePCH (CompilerInstance &CI, std::shared_ptr< ModuleDependencyCollector > MDC)
static void collectVFSEntries (CompilerInstance &CI, std::shared_ptr< ModuleDependencyCollector > MDC)
static void SetUpDiagnosticLog (DiagnosticOptions *DiagOpts, const CodeGenOptions *CodeGenOpts, DiagnosticsEngine &Diags)
static void SetupSerializedDiagnostics (DiagnosticOptions *DiagOpts, DiagnosticsEngine &Diags, StringRef OutputFile)
static void InitializeFileRemapping (DiagnosticsEngine &Diags, SourceManager &SourceMgr, FileManager &FileMgr, const PreprocessorOptions &InitOpts)
static bool EnableCodeCompletion (Preprocessor &PP, StringRef Filename, unsigned Line, unsigned Column)
static Language getLanguageFromOptions (const LangOptions &LangOpts)
Determine the appropriate source input kind based on language options.
static bool compileModuleImpl (CompilerInstance &ImportingInstance, SourceLocation ImportLoc, StringRef ModuleName, FrontendInputFile Input, StringRef OriginalModuleMapFile, StringRef ModuleFileName, llvm::function_ref< void(CompilerInstance &)> PreBuildStep=[](CompilerInstance &) {}, llvm::function_ref< void(CompilerInstance &)> PostBuildStep=[](CompilerInstance &) {})
Compile a module file for the given module, using the options provided by the importing compiler instance.
static OptionalFileEntryRef getPublicModuleMap (FileEntryRef File, FileManager &FileMgr)
static bool compileModule (CompilerInstance &ImportingInstance, SourceLocation ImportLoc, Module *Module, StringRef ModuleFileName)
Compile a module file for the given module in a separate compiler instance, using the options provided by the importing compiler instance.
static bool readASTAfterCompileModule (CompilerInstance &ImportingInstance, SourceLocation ImportLoc, SourceLocation ModuleNameLoc, Module *Module, StringRef ModuleFileName, bool *OutOfDate)
Read the AST right after compiling the module.
static bool compileModuleAndReadASTImpl (CompilerInstance &ImportingInstance, SourceLocation ImportLoc, SourceLocation ModuleNameLoc, Module *Module, StringRef ModuleFileName)
Compile a module in a separate compiler instance and read the AST, returning true if the module compiles without errors.
static bool compileModuleAndReadASTBehindLock (CompilerInstance &ImportingInstance, SourceLocation ImportLoc, SourceLocation ModuleNameLoc, Module *Module, StringRef ModuleFileName)
Compile a module in a separate compiler instance and read the AST, returning true if the module compiles without errors, using a lock manager to avoid building the same module in multiple compiler instances.
static bool compileModuleAndReadAST (CompilerInstance &ImportingInstance, SourceLocation ImportLoc, SourceLocation ModuleNameLoc, Module *Module, StringRef ModuleFileName)
Compile a module in a separate compiler instance and read the AST, returning true if the module compiles without errors, potentially using a lock manager to avoid building the same module in multiple compiler instances.
static void checkConfigMacro (Preprocessor &PP, StringRef ConfigMacro, Module *Mod, SourceLocation ImportLoc)
Diagnose differences between the current definition of the given configuration macro and the definition provided on the command line.
static void checkConfigMacros (Preprocessor &PP, Module *M, SourceLocation ImportLoc)
static void writeTimestampFile (StringRef TimestampFile)
Write a new timestamp file with the given path.
static void pruneModuleCache (const HeaderSearchOptions &HSOpts)
Prune the module cache of modules that haven't been accessed in a long time.
static ModuleSource selectModuleSource (Module *M, StringRef ModuleName, std::string &ModuleFilename, const std::map< std::string, std::string, std::less<>> &BuiltModules, HeaderSearch &HS)
Select a source for loading the named module and compute the filename to load it from.
Function Documentation
checkConfigMacro()
static void checkConfigMacro (Preprocessor & PP, StringRef ConfigMacro, Module * Mod, SourceLocation ImportLoc) static
Diagnose differences between the current definition of the given configuration macro and the definition provided on the command line.
Definition at line 1557 of file CompilerInstance.cpp.
References clang::Preprocessor::Diag(), clang::SourceManager::getFileID(), clang::Module::getFullModuleName(), clang::Preprocessor::getIdentifierInfo(), clang::Preprocessor::getLocalMacroDirectiveHistory(), clang::Preprocessor::getMacroInfo(), clang::Preprocessor::getPredefinesFileID(), clang::Preprocessor::getSourceManager(), Id, and clang::FileID::isInvalid().
Referenced by checkConfigMacros().
checkConfigMacros()
static void checkConfigMacros (Preprocessor & PP, Module * M, SourceLocation ImportLoc) static
Definition at line 1613 of file CompilerInstance.cpp.
References checkConfigMacro(), clang::Module::ConfigMacros, and clang::Module::getTopLevelModule().
Referenced by clang::CompilerInstance::loadModule().
collectHeaderMaps()
static void collectHeaderMaps (const HeaderSearch & HS, std::shared_ptr< ModuleDependencyCollector > MDC) static
Definition at line 223 of file CompilerInstance.cpp.
References clang::HeaderSearch::getHeaderMapFileNames().
Referenced by clang::CompilerInstance::createPreprocessor().
collectIncludePCH()
static void collectIncludePCH (CompilerInstance & CI, std::shared_ptr< ModuleDependencyCollector > MDC) static
Definition at line 231 of file CompilerInstance.cpp.
References clang::CompilerInstance::getFileManager(), clang::FileManager::getOptionalDirectoryRef(), clang::CompilerInstance::getPreprocessorOpts(), and clang::PreprocessorOptions::ImplicitPCHInclude.
Referenced by clang::CompilerInstance::createPreprocessor().
collectVFSEntries()
static void collectVFSEntries (CompilerInstance & CI, std::shared_ptr< ModuleDependencyCollector > MDC) static
Definition at line 264 of file CompilerInstance.cpp.
References clang::CompilerInstance::getHeaderSearchOpts(), and clang::HeaderSearchOptions::VFSOverlayFiles.
Referenced by clang::CompilerInstance::createPreprocessor().
compileModule()
static bool compileModule (CompilerInstance & ImportingInstance, SourceLocation ImportLoc, Module * Module, StringRef ModuleFileName) static
Compile a module file for the given module in a separate compiler instance, using the options provided by the importing compiler instance.
Returns true if the module was built without errors.
Definition at line 1330 of file CompilerInstance.cpp.
References compileModuleImpl(), clang::Module::Directory, clang::FrontendOptions::GenerateGlobalModuleIndex, clang::ModuleMap::getContainingModuleMapFileID(), clang::SourceManager::getFileCharacteristic(), clang::SourceManager::getFileEntryRefForID(), clang::SourceManager::getFileID(), clang::CompilerInstance::getFileManager(), clang::CompilerInstance::getFrontendOpts(), clang::Preprocessor::getHeaderSearchInfo(), clang::SourceManager::getIncludeLoc(), clang::CompilerInstance::getLangOpts(), getLanguageFromOptions(), clang::HeaderSearch::getModuleMap(), clang::ModuleMap::getModuleMapFileForUniquing(), clang::DirectoryEntryRef::getName(), clang::FileEntryRef::getName(), clang::FileEntryRef::getNameAsRequested(), clang::CompilerInstance::getPreprocessor(), getPublicModuleMap(), clang::CompilerInstance::getSourceManager(), clang::Module::getTopLevelModuleName(), clang::SrcMgr::isModuleMap(), clang::Module::IsSystem, clang::FileID::isValid(), clang::SourceLocation::isValid(), clang::InputKind::ModuleMap, clang::Module::print(), and clang::CompilerInstance::setBuildGlobalModuleIndex().
Referenced by compileModuleAndReadASTImpl().
compileModuleAndReadAST()
static bool compileModuleAndReadAST (CompilerInstance & ImportingInstance, SourceLocation ImportLoc, SourceLocation ModuleNameLoc, Module * Module, StringRef ModuleFileName) static
Compile a module in a separate compiler instance and read the AST, returning true if the module compiles without errors, potentially using a lock manager to avoid building the same module in multiple compiler instances.
Definition at line 1540 of file CompilerInstance.cpp.
References clang::FrontendOptions::BuildingImplicitModuleUsesLock, compileModuleAndReadASTBehindLock(), compileModuleAndReadASTImpl(), clang::CompilerInvocation::getFrontendOpts(), and clang::CompilerInstance::getInvocation().
compileModuleAndReadASTBehindLock()
static bool compileModuleAndReadASTBehindLock (CompilerInstance & ImportingInstance, SourceLocation ImportLoc, SourceLocation ModuleNameLoc, Module * Module, StringRef ModuleFileName) static
Compile a module in a separate compiler instance and read the AST, returning true if the module compiles without errors, using a lock manager to avoid building the same module in multiple compiler instances.
Uses a lock file manager and exponential backoff to reduce the chances that multiple instances will compete to create the same module. On timeout, deletes the lock file in order to avoid deadlock from crashing processes or bugs in the lock file manager.
Definition at line 1470 of file CompilerInstance.cpp.
References compileModuleAndReadASTImpl(), clang::CompilerInstance::getDiagnostics(), clang::Module::Name, readASTAfterCompileModule(), and clang::DiagnosticsEngine::Report().
Referenced by compileModuleAndReadAST().
compileModuleAndReadASTImpl()
static bool compileModuleAndReadASTImpl (CompilerInstance & ImportingInstance, SourceLocation ImportLoc, SourceLocation ModuleNameLoc, Module * Module, StringRef ModuleFileName) static
Compile a module in a separate compiler instance and read the AST, returning true if the module compiles without errors.
Definition at line 1444 of file CompilerInstance.cpp.
References compileModule(), clang::CompilerInstance::getDiagnostics(), clang::Module::Name, readASTAfterCompileModule(), and clang::DiagnosticsEngine::Report().
Referenced by compileModuleAndReadAST(), and compileModuleAndReadASTBehindLock().
compileModuleImpl()
static bool compileModuleImpl (CompilerInstance & ImportingInstance, SourceLocation ImportLoc, StringRef ModuleName, FrontendInputFile Input, StringRef OriginalModuleMapFile, StringRef ModuleFileName, llvm::function_ref< void(CompilerInstance &)> PreBuildStep = [](CompilerInstance &) {}, llvm::function_ref< void(CompilerInstance &)> PostBuildStep = [](CompilerInstance &) {}) static
Compile a module file for the given module, using the options provided by the importing compiler instance.
Returns true if the module was built without errors.
Definition at line 1166 of file CompilerInstance.cpp.
Referenced by compileModule(), and clang::CompilerInstance::createModuleFromSource().
EnableCodeCompletion()
static bool EnableCodeCompletion (Preprocessor & PP, StringRef Filename, unsigned Line, unsigned Column) static
Definition at line 694 of file CompilerInstance.cpp.
References clang::Column, Filename, clang::Preprocessor::getDiagnostics(), clang::Preprocessor::getFileManager(), clang::FileManager::getOptionalFileRef(), clang::DiagnosticsEngine::Report(), and clang::Preprocessor::SetCodeCompletionPoint().
Referenced by clang::CompilerInstance::createCodeCompletionConsumer().
getLanguageFromOptions()
static Language getLanguageFromOptions (const LangOptions & LangOpts) static
Determine the appropriate source input kind based on language options.
Definition at line 1152 of file CompilerInstance.cpp.
Referenced by compileModule(), and clang::CompilerInstance::createModuleFromSource().
getPublicModuleMap()
static OptionalFileEntryRef getPublicModuleMap (FileEntryRef File, FileManager & FileMgr) static
Definition at line 1314 of file CompilerInstance.cpp.
References clang::File, Filename, and clang::FileManager::getOptionalFileRef().
Referenced by compileModule().
InitializeFileRemapping()
static void InitializeFileRemapping (DiagnosticsEngine & Diags, SourceManager & SourceMgr, FileManager & FileMgr, const PreprocessorOptions & InitOpts) static
Definition at line 398 of file CompilerInstance.cpp.
References clang::FileManager::getOptionalFileRef(), clang::FileEntryRef::getSize(), clang::FileManager::getVirtualFile(), clang::FileManager::getVirtualFileRef(), clang::SourceManager::overrideFileContents(), clang::PreprocessorOptions::RemappedFileBuffers, clang::PreprocessorOptions::RemappedFiles, clang::PreprocessorOptions::RemappedFilesKeepOriginalName, clang::DiagnosticsEngine::Report(), clang::PreprocessorOptions::RetainRemappedFileBuffers, and clang::SourceManager::setOverridenFilesKeepOriginalName().
Referenced by clang::CompilerInstance::createPreprocessor().
pruneModuleCache()
static void pruneModuleCache (const HeaderSearchOptions & HSOpts) static
Prune the module cache of modules that haven't been accessed in a long time.
Definition at line 1629 of file CompilerInstance.cpp.
References clang::File, clang::HeaderSearchOptions::ModuleCachePath, clang::HeaderSearchOptions::ModuleCachePruneAfter, clang::HeaderSearchOptions::ModuleCachePruneInterval, clang::transformer::remove(), and writeTimestampFile().
Referenced by clang::CompilerInstance::createASTReader().
readASTAfterCompileModule()
static bool readASTAfterCompileModule (CompilerInstance & ImportingInstance, SourceLocation ImportLoc, SourceLocation ModuleNameLoc, Module * Module, StringRef ModuleFileName, bool * OutOfDate) static
Read the AST right after compiling the module.
Definition at line 1409 of file CompilerInstance.cpp.
References clang::ASTReader::ARR_Missing, clang::ASTReader::ARR_OutOfDate, clang::CompilerInstance::getASTReader(), clang::CompilerInstance::getDiagnostics(), clang::DiagnosticsEngine::hasErrorOccurred(), clang::ASTReader::Missing, clang::serialization::MK_ImplicitModule, clang::Module::Name, clang::ASTReader::OutOfDate, clang::DiagnosticsEngine::Report(), and clang::ASTReader::Success.
Referenced by compileModuleAndReadASTBehindLock(), and compileModuleAndReadASTImpl().
selectModuleSource()
static ModuleSource selectModuleSource (Module * M, StringRef ModuleName, std::string & ModuleFilename, const std::map< std::string, std::string, std::less<>> & BuiltModules, HeaderSearch & HS) static
Select a source for loading the named module and compute the filename to load it from.
Definition at line 1817 of file CompilerInstance.cpp.
References clang::HeaderSearchOptions::EnablePrebuiltImplicitModules, clang::HeaderSearch::getCachedModuleFileName(), clang::HeaderSearch::getHeaderSearchOpts(), clang::HeaderSearch::getPrebuiltImplicitModuleFileName(), clang::HeaderSearch::getPrebuiltModuleFileName(), clang::HeaderSearchOptions::PrebuiltModuleFiles, and clang::HeaderSearchOptions::PrebuiltModulePaths.
SetUpDiagnosticLog()
static void SetUpDiagnosticLog (DiagnosticOptions * DiagOpts, const CodeGenOptions * CodeGenOpts, DiagnosticsEngine & Diags) static
Definition at line 285 of file CompilerInstance.cpp.
References clang::DiagnosticOptions::DiagnosticLogFile, clang::CodeGenOptions::DwarfDebugFlags, clang::DiagnosticsEngine::getClient(), clang::DiagnosticsEngine::ownsClient(), clang::DiagnosticsEngine::Report(), clang::DiagnosticsEngine::setClient(), and clang::DiagnosticsEngine::takeClient().
Referenced by clang::CompilerInstance::createDiagnostics().
SetupSerializedDiagnostics()
static void SetupSerializedDiagnostics (DiagnosticOptions * DiagOpts, DiagnosticsEngine & Diags, StringRef OutputFile) static
Definition at line 320 of file CompilerInstance.cpp.
References clang::serialized_diags::create(), clang::DiagnosticsEngine::getClient(), clang::DiagnosticsEngine::ownsClient(), clang::DiagnosticsEngine::setClient(), and clang::DiagnosticsEngine::takeClient().
Referenced by clang::CompilerInstance::createDiagnostics().
writeTimestampFile()
static void writeTimestampFile (StringRef TimestampFile) static
Write a new timestamp file with the given path.
Definition at line 1622 of file CompilerInstance.cpp.
Referenced by pruneModuleCache().