clang: lib/StaticAnalyzer/Core/CoreEngine.cpp File Reference
CoreEngine.cpp File Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtCXX.h"
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/Analysis/CFG.h"
#include "clang/Analysis/ProgramPoint.h"
#include "clang/Basic/LLVM.h"
#include "clang/StaticAnalyzer/Core/AnalyzerOptions.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/BlockCounter.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExplodedGraph.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/FunctionSummary.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/WorkList.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <cassert>
#include <memory>
#include <optional>
#include <utility>
Macros
#define DEBUG_TYPE "CoreEngine"
Functions
STATISTIC (NumSteps, "The # of steps executed.")
STATISTIC (NumSTUSteps, "The # of STU steps executed.")
STATISTIC (NumCTUSteps, "The # of CTU steps executed.")
STATISTIC (NumReachedMaxSteps, "The # of times we reached the max number of steps.")
STATISTIC (NumPathsExplored, "The # of paths explored by the analyzer.")
static std::unique_ptr< WorkList > generateWorkList (AnalyzerOptions &Opts)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "CoreEngine"
Definition at line 42 of file CoreEngine.cpp.
Function Documentation
generateWorkList()
static std::unique_ptr<WorkList> generateWorkList (AnalyzerOptions & Opts) static
Definition at line 57 of file CoreEngine.cpp.
References clang::BFS, clang::BFSBlockDFSContents, clang::DFS, clang::AnalyzerOptions::getExplorationStrategy(), clang::ento::WorkList::makeBFS(), clang::ento::WorkList::makeBFSBlockDFSContents(), clang::ento::WorkList::makeDFS(), clang::ento::WorkList::makeUnexploredFirst(), clang::ento::WorkList::makeUnexploredFirstPriorityLocationQueue(), clang::ento::WorkList::makeUnexploredFirstPriorityQueue(), clang::UnexploredFirst, clang::UnexploredFirstLocationQueue, and clang::UnexploredFirstQueue.
STATISTIC() [1/5]
STATISTIC (NumCTUSteps , "The # of CTU steps executed.")
STATISTIC() [2/5]
STATISTIC (NumPathsExplored , "The # of paths explored by the analyzer.")
STATISTIC() [3/5]
STATISTIC (NumReachedMaxSteps , "The # of times we reached the max number of steps.")
STATISTIC() [4/5]
STATISTIC (NumSteps , "The # of steps executed.")
STATISTIC() [5/5]
STATISTIC (NumSTUSteps , "The # of STU steps executed.")