clang: lib/CodeGen/CoverageMappingGen.cpp File Reference
CoverageMappingGen.cpp File Reference
#include "CoverageMappingGen.h"
#include "CodeGenFunction.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/FileManager.h"
#include "clang/Frontend/FrontendDiagnostic.h"
#include "clang/Lex/Lexer.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
#include "llvm/ProfileData/Coverage/CoverageMappingReader.h"
#include "llvm/ProfileData/Coverage/CoverageMappingWriter.h"
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include <optional>
#include "llvm/ProfileData/InstrProfData.inc"
Namespaces
llvm
Diagnostic wrappers for TextAPI types for error reporting.
Macros
#define COVMAP_V3
#define COVMAP_FUNC_RECORD(Type, LLVMType, Name, Init) LLVMType,
#define COVMAP_FUNC_RECORD(Type, LLVMType, Name, Init) Init,
#define COVMAP_HEADER(Type, LLVMType, Name, Init) LLVMType,
#define COVMAP_HEADER(Type, LLVMType, Name, Init) Init,
Functions
cl::opt< bool > llvm::EnableSingleByteCoverage ("enable-single-byte-coverage", llvm::cl::ZeroOrMore, llvm::cl::desc("Enable single byte coverage"), llvm::cl::Hidden, llvm::cl::init(false))
static llvm::cl::opt< bool > EmptyLineCommentCoverage ("emptyline-comment-coverage", llvm::cl::desc("Emit emptylines and comment lines as skipped regions (only " "disable it on test)"), llvm::cl::init(true), llvm::cl::Hidden)
llvm::cl::opt< bool > SystemHeadersCoverage ("system-headers-coverage", llvm::cl::desc("Enable collecting coverage from system headers"), llvm::cl::init(false), llvm::cl::Hidden)
static void dump (llvm::raw_ostream &OS, StringRef FunctionName, ArrayRef< CounterExpression > Expressions, ArrayRef< CounterMappingRegion > Regions)
static std::string getInstrProfSection (const CodeGenModule &CGM, llvm::InstrProfSectKind SK)
Macro Definition Documentation
COVMAP_FUNC_RECORD [1/2]
#define COVMAP_FUNC_RECORD (Type, LLVMType, Name, Init) LLVMType,
COVMAP_FUNC_RECORD [2/2]
#define COVMAP_FUNC_RECORD (Type, LLVMType, Name, Init) Init,
COVMAP_HEADER [1/2]
#define COVMAP_HEADER (Type, LLVMType, Name, Init) LLVMType,
COVMAP_HEADER [2/2]
#define COVMAP_HEADER (Type, LLVMType, Name, Init) Init,
COVMAP_V3
#define COVMAP_V3
Definition at line 32 of file CoverageMappingGen.cpp.
Function Documentation
dump()
static void dump (llvm::raw_ostream & OS, StringRef FunctionName, ArrayRef< CounterExpression > Expressions, ArrayRef< CounterMappingRegion > Regions) static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2191 of file CoverageMappingGen.cpp.
Referenced by clang::CodeGen::CoverageMappingModuleGen::addFunctionMappingRecord(), clang::ConceptReference::dump(), clang::Decl::dump(), clang::QualType::dump(), and clang::ASTReader::PrintStats().
EmptyLineCommentCoverage()
static llvm::cl::opt<bool> EmptyLineCommentCoverage ("emptyline-comment-coverage" , llvm::cl::desc("Emit emptylines and comment lines as skipped regions (only " "disable it on test)") , llvm::cl::init(true) , llvm::cl::Hidden) static
Referenced by clang::CoverageSourceInfo::AddSkippedRange(), and clang::CodeGen::CoverageMappingModuleGen::setUpCoverageCallbacks().
getInstrProfSection()
static std::string getInstrProfSection (const CodeGenModule & CGM, llvm::InstrProfSectKind SK) static
Definition at line 2277 of file CoverageMappingGen.cpp.
References clang::CodeGen::CodeGenModule::getContext(), clang::ASTContext::getTargetInfo(), and clang::TargetInfo::getTriple().
Referenced by clang::CodeGen::CoverageMappingModuleGen::emit().
SystemHeadersCoverage()
llvm::cl::opt<bool> SystemHeadersCoverage ("system-headers-coverage" , llvm::cl::desc("Enable collecting coverage from system headers") , llvm::cl::init(false) , llvm::cl::Hidden)