clang: lib/StaticAnalyzer/Checkers/DeadStoresChecker.cpp File Reference
DeadStoresChecker.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/ParentMap.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Analysis/Analyses/LiveVariables.h"
#include "clang/Lex/Lexer.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/SaveAndRestore.h"
Functions
static const Expr * LookThroughTransitiveAssignmentsAndCommaOperators (const Expr *Ex)
Function Documentation
LookThroughTransitiveAssignmentsAndCommaOperators()
static const Expr* LookThroughTransitiveAssignmentsAndCommaOperators (const Expr * Ex) static
Definition at line 104 of file DeadStoresChecker.cpp.
References clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), and clang::Expr::IgnoreParenCasts().