clang: lib/AST/DeclTemplate.cpp File Reference
DeclTemplate.cpp File Reference
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExternalASTSource.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <utility>
Namespaces
clang
Functions
static bool AdoptTemplateParameterList (TemplateParameterList *Params, DeclContext *Owner)
void * clang::allocateDefaultArgStorageChain (const ASTContext &C)
static void ProfileTemplateParameterList (ASTContext &C, llvm::FoldingSetNodeID &ID, const TemplateParameterList *TPL)
static TemplateParameterList * createMakeIntegerSeqParameterList (const ASTContext &C, DeclContext *DC)
static TemplateParameterList * createTypePackElementParameterList (const ASTContext &C, DeclContext *DC)
static TemplateParameterList * createBuiltinTemplateParameterList (const ASTContext &C, DeclContext *DC, BuiltinTemplateKind BTK)
Function Documentation
AdoptTemplateParameterList()
static bool AdoptTemplateParameterList (TemplateParameterList * Params, DeclContext * Owner) static
Definition at line 169 of file DeclTemplate.cpp.
References P.
createBuiltinTemplateParameterList()
static TemplateParameterList* createBuiltinTemplateParameterList (const ASTContext & C, DeclContext * DC, BuiltinTemplateKind BTK) static
Definition at line 1460 of file DeclTemplate.cpp.
References clang::BTK__make_integer_seq, clang::BTK__type_pack_element, createMakeIntegerSeqParameterList(), and createTypePackElementParameterList().
createMakeIntegerSeqParameterList()
static TemplateParameterList* createMakeIntegerSeqParameterList (const ASTContext & C, DeclContext * DC) static
Definition at line 1390 of file DeclTemplate.cpp.
References clang::TemplateParameterList::Create(), clang::TemplateTypeParmDecl::Create(), clang::NonTypeTemplateParmDecl::Create(), clang::TemplateTemplateParmDecl::Create(), clang::TypeSourceInfo::getType(), and P.
Referenced by createBuiltinTemplateParameterList().
createTypePackElementParameterList()
static TemplateParameterList* createTypePackElementParameterList (const ASTContext & C, DeclContext * DC) static
Definition at line 1439 of file DeclTemplate.cpp.
Referenced by createBuiltinTemplateParameterList().
ProfileTemplateParameterList()
static void ProfileTemplateParameterList (ASTContext & C, llvm::FoldingSetNodeID & ID, const TemplateParameterList * TPL) static
Definition at line 510 of file DeclTemplate.cpp.
References clang::TemplateParameterList::getRequiresClause(), clang::Stmt::Profile(), and clang::TemplateParameterList::size().
Referenced by clang::ClassTemplatePartialSpecializationDecl::Profile(), and clang::VarTemplatePartialSpecializationDecl::Profile().