clang: lib/Sema/DeclSpec.cpp File Reference
DeclSpec.cpp File Reference
#include "clang/Sema/DeclSpec.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/Expr.h"
#include "clang/AST/LocInfoType.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaDiagnostic.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include <cstring>
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/TransformTypeTraits.def"
Macros
#define GENERIC_IMAGE_TYPE(ImgType, Id) case TST_##ImgType##_t:
#define TRANSFORM_TYPE_TRAIT_DEF(_, Trait) case TST_##Trait:
#define TRANSFORM_TYPE_TRAIT_DEF(_, Trait)
#define GENERIC_IMAGE_TYPE(ImgType, Id)
Functions
template<class T >
static bool BadSpecifier (T TNew, T TPrev, const char *&PrevSpec, unsigned &DiagID, bool IsExtension=true)
Macro Definition Documentation
GENERIC_IMAGE_TYPE [1/2]
#define GENERIC_IMAGE_TYPE (ImgType, Id) case TST_##ImgType##_t:
GENERIC_IMAGE_TYPE [2/2]
#define GENERIC_IMAGE_TYPE (ImgType, Id)
Value:
  case DeclSpec::TST_##ImgType##_t: \
    return #ImgType "_t";
TRANSFORM_TYPE_TRAIT_DEF [1/2]
#define TRANSFORM_TYPE_TRAIT_DEF (_, Trait) case TST_##Trait:
TRANSFORM_TYPE_TRAIT_DEF [2/2]
#define TRANSFORM_TYPE_TRAIT_DEF (_, Trait)
Value:
  case DeclSpec::TST_##Trait:                                                  \
    return "__" #Trait;
Function Documentation
BadSpecifier()
template<class T > static bool BadSpecifier (T TNew, T TPrev, const char *& PrevSpec, unsigned & DiagID, bool IsExtension = true) static
Definition at line 486 of file DeclSpec.cpp.
References clang::DeclSpec::getSpecifierName().
Referenced by clang::DeclSpec::SetConstexprSpec(), clang::DeclSpec::SetStorageClassSpecThread(), clang::DeclSpec::SetTypeQual(), clang::DeclSpec::SetTypeSpecComplex(), and clang::DeclSpec::SetTypeSpecWidth().