clang: lib/AST/DeclPrinter.cpp File Reference
DeclPrinter.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclVisitor.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/Basic/Module.h"
#include "llvm/Support/raw_ostream.h"
#include "clang/Basic/AttrLeftSideCanPrintList.inc"
#include "clang/Basic/AttrLeftSideMustPrintList.inc"
#include "clang/Basic/AttrList.inc"
Macros
#define ATTR(X)
#define PRAGMA_SPELLING_ATTR(X) case attr::X:
Functions
static QualType GetBaseType (QualType T)
static QualType getDeclType (Decl *D)
static bool canPrintOnLeftSide (attr::Kind kind)
static bool canPrintOnLeftSide (const Attr *A)
static bool mustPrintOnLeftSide (attr::Kind kind)
static bool mustPrintOnLeftSide (const Attr *A)
static void printExplicitSpecifier (ExplicitSpecifier ES, llvm::raw_ostream &Out, PrintingPolicy &Policy, unsigned Indentation, const ASTContext &Context)
static void MaybePrintTagKeywordIfSupressingScopes (PrintingPolicy &Policy, QualType T, llvm::raw_ostream &Out)
Macro Definition Documentation
ATTR
#define ATTR (X)
PRAGMA_SPELLING_ATTR
#define PRAGMA_SPELLING_ATTR (X) case attr::X:
Function Documentation
canPrintOnLeftSide() [1/2]
static bool canPrintOnLeftSide (attr::Kind kind) static
Definition at line 259 of file DeclPrinter.cpp.
Referenced by canPrintOnLeftSide().
canPrintOnLeftSide() [2/2]
static bool canPrintOnLeftSide (const Attr * A) static
Definition at line 272 of file DeclPrinter.cpp.
References canPrintOnLeftSide(), clang::Attr::getKind(), and clang::AttributeCommonInfo::isStandardAttributeSyntax().
GetBaseType()
static QualType GetBaseType (QualType T) static
Definition at line 166 of file DeclPrinter.cpp.
References clang::Type::getAs(), clang::Type::getPointeeType(), and clang::Type::isSpecifierType().
getDeclType()
static QualType getDeclType (Decl * D) static
Definition at line 196 of file DeclPrinter.cpp.
MaybePrintTagKeywordIfSupressingScopes()
static void MaybePrintTagKeywordIfSupressingScopes (PrintingPolicy & Policy, QualType T, llvm::raw_ostream & Out) static
Definition at line 688 of file DeclPrinter.cpp.
References clang::Type::isClassType(), clang::Type::isStructureType(), and clang::Type::isUnionType().
mustPrintOnLeftSide() [1/2]
static bool mustPrintOnLeftSide (attr::Kind kind) static
Definition at line 279 of file DeclPrinter.cpp.
Referenced by mustPrintOnLeftSide().
mustPrintOnLeftSide() [2/2]
static bool mustPrintOnLeftSide (const Attr * A) static
Definition at line 292 of file DeclPrinter.cpp.
References clang::Attr::getKind(), clang::AttributeCommonInfo::isDeclspecAttribute(), and mustPrintOnLeftSide().
printExplicitSpecifier()
static void printExplicitSpecifier (ExplicitSpecifier ES, llvm::raw_ostream & Out, PrintingPolicy & Policy, unsigned Indentation, const ASTContext & Context) static
Definition at line 672 of file DeclPrinter.cpp.