clang: lib/AST/Decl.cpp File Reference
Decl.cpp File Reference
#include "clang/AST/Decl.h"
#include "Linkage.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CanonicalType.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExternalASTSource.h"
#include "clang/AST/ODRHash.h"
#include "clang/AST/PrettyDeclStackTrace.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/AST/Redeclarable.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/Linkage.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/NoSanitizeList.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/Sanitizers.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TargetCXXABI.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/Visibility.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstring>
#include <memory>
#include <string>
#include <tuple>
#include <type_traits>
#include "clang/AST/DeclNodes.inc"
Macros
#define DECL(Type, Base)
#define ABSTRACT_DECL(DECL)
Functions
static bool hasExplicitVisibilityAlready (LVComputationKind computation)
Does this computation kind permit us to consider additional visibility settings from attributes and the like?
static LVComputationKind withExplicitVisibilityAlready (LVComputationKind Kind)
Given an LVComputationKind, return one of the same type/value sort that records that it already has explicit visibility.
static Optional< Visibility > getExplicitVisibility (const NamedDecl *D, LVComputationKind kind)
static bool usesTypeVisibility (const NamedDecl *D)
Is the given declaration a "type" or a "value" for the purposes of visibility computation?
template<class T >
static std::enable_if<!std::is_base_of< RedeclarableTemplateDecl, T >::value, bool >::type isExplicitMemberSpecialization (const T *D)
Does the given declaration have member specialization information, and if so, is it an explicit specialization?
static bool isExplicitMemberSpecialization (const RedeclarableTemplateDecl *D)
For templates, this question is easier: a member template can't be explicitly instantiated, so there's a single bit indicating whether or not this is an explicit member specialization.
template<class T >
static Visibility getVisibilityFromAttr (const T *attr)
Given a visibility attribute, return the explicit visibility associated with it.
static Optional< Visibility > getVisibilityOf (const NamedDecl *D, NamedDecl::ExplicitVisibilityKind kind)
Return the explicit visibility of the given declaration.
static const Decl * getOutermostFuncOrBlockContext (const Decl *D)
static bool shouldConsiderTemplateVisibility (const FunctionDecl *fn, const FunctionTemplateSpecializationInfo *specInfo)
static bool hasDirectVisibilityAttribute (const NamedDecl *D, LVComputationKind computation)
Does the given declaration have a direct visibility attribute that would match the given rules?
static bool shouldConsiderTemplateVisibility (const ClassTemplateSpecializationDecl *spec, LVComputationKind computation)
Should we consider visibility associated with the template arguments and parameters of the given class template specialization?
static bool shouldConsiderTemplateVisibility (const VarTemplateSpecializationDecl *spec, LVComputationKind computation)
Should we consider visibility associated with the template arguments and parameters of the given variable template specialization? As usual, follow class template specialization logic up to initialization.
static bool useInlineVisibilityHidden (const NamedDecl *D)
template<typename T >
static bool isFirstInExternCContext (T *D)
static bool isSingleLineLanguageLinkage (const Decl &D)
static bool isInModulePurview (const NamedDecl *D)
Determine whether D is declared in the purview of a named module.
static bool isExportedFromModuleInterfaceUnit (const NamedDecl *D)
static LinkageInfo getInternalLinkageFor (const NamedDecl *D)
static LinkageInfo getExternalLinkageFor (const NamedDecl *D)
static StorageClass getStorageClass (const Decl *D)
static Optional< Visibility > getExplicitVisibilityAux (const NamedDecl *ND, NamedDecl::ExplicitVisibilityKind kind, bool IsMostRecent)
template<typename T >
static bool isRedeclarableImpl (Redeclarable< T > *)
static bool isRedeclarableImpl (...)
static bool isRedeclarable (Decl::Kind K)
template<typename DeclT >
static SourceLocation getTemplateOrInnerLocStart (const DeclT *decl)
static bool typeIsPostfix (QualType QT)
template<typename T >
static LanguageLinkage getDeclLanguageLinkage (const T &D)
template<typename T >
static bool isDeclExternC (const T &D)
template<typename DeclT >
static DeclT * getDefinitionOrSelf (DeclT *D)
template<std::size_t Len>
static bool isNamed (const NamedDecl *ND, const char(&Str)[Len])
static bool redeclForcesDefMSVC (const FunctionDecl *Redecl)
static bool RedeclForcesDefC99 (const FunctionDecl *Redecl)
static unsigned getNumModuleIdentifiers (Module *Mod)
Retrieve the number of module identifiers needed to name the given module.
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (DECL)
DECL
#define DECL (Type, Base)
Value:
  case Decl::Type: \
    return isRedeclarableImpl((Type##Decl *)nullptr);
Function Documentation
getDeclLanguageLinkage()
template<typename T > static LanguageLinkage getDeclLanguageLinkage (const T & D) static
Definition at line 2102 of file Decl.cpp.
References clang::CLanguageLinkage, clang::CXXLanguageLinkage, clang::ASTContext::getLangOpts(), isFirstInExternCContext(), clang::DeclContext::isRecord(), and clang::NoLanguageLinkage.
Referenced by clang::VarDecl::getLanguageLinkage(), and clang::FunctionDecl::getLanguageLinkage().
getDefinitionOrSelf()
template<typename DeclT > static DeclT* getDefinitionOrSelf (DeclT * D) static
Definition at line 2559 of file Decl.cpp.
Referenced by clang::VarDecl::getTemplateInstantiationPattern(), clang::FunctionDecl::getTemplateInstantiationPattern(), and clang::EnumDecl::getTemplateInstantiationPattern().
getExplicitVisibility()
static Optional<Visibility> getExplicitVisibility (const NamedDecl * D, LVComputationKind kind) static
Definition at line 171 of file Decl.cpp.
References clang::NamedDecl::getExplicitVisibility().
getExplicitVisibilityAux()
static Optional<Visibility> getExplicitVisibilityAux (const NamedDecl * ND, NamedDecl::ExplicitVisibilityKind kind, bool IsMostRecent) static
Definition at line 1156 of file Decl.cpp.
References clang::CXXRecordDecl::getInstantiatedFromMemberClass(), clang::FunctionDecl::getInstantiatedFromMemberFunction(), clang::VarDecl::getInstantiatedFromStaticDataMember(), clang::NamedDecl::getMostRecentDecl(), clang::VarTemplateSpecializationDecl::getSpecializedTemplate(), clang::VarTemplateDecl::getTemplatedDecl(), clang::FunctionDecl::getTemplateSpecializationInfo(), getVisibilityOf(), and V.
Referenced by clang::NamedDecl::getExplicitVisibility().
getExternalLinkageFor()
static LinkageInfo getExternalLinkageFor (const NamedDecl * D) static
Definition at line 609 of file Decl.cpp.
References clang::DefaultVisibility, clang::LinkageInfo::external(), clang::Decl::getCanonicalDecl(), isExportedFromModuleInterfaceUnit(), isInModulePurview(), and clang::ModuleLinkage.
Referenced by clang::LinkageComputer::computeLVForDecl().
getInternalLinkageFor()
static LinkageInfo getInternalLinkageFor (const NamedDecl * D) static
Definition at line 598 of file Decl.cpp.
References clang::DefaultVisibility, clang::LinkageInfo::internal(), isInModulePurview(), and clang::ModuleInternalLinkage.
Referenced by clang::LinkageComputer::computeLVForDecl(), and clang::LinkageComputer::getLVForDecl().
getNumModuleIdentifiers()
static unsigned getNumModuleIdentifiers (Module * Mod) static
Retrieve the number of module identifiers needed to name the given module.
Definition at line 5128 of file Decl.cpp.
Referenced by clang::ImportDecl::getIdentifierLocs().
getOutermostFuncOrBlockContext()
static const Decl* getOutermostFuncOrBlockContext (const Decl * D) static
Definition at line 302 of file Decl.cpp.
References clang::Decl::getDeclContext(), clang::DeclContext::getDeclKind(), clang::DeclContext::getParent(), and Ret().
getStorageClass()
static StorageClass getStorageClass (const Decl * D) static
Definition at line 627 of file Decl.cpp.
References clang::SC_None.
getTemplateOrInnerLocStart()
template<typename DeclT > static SourceLocation getTemplateOrInnerLocStart (const DeclT * decl) static
Definition at line 1882 of file Decl.cpp.
References clang::ast_matchers::decl.
Referenced by clang::DeclaratorDecl::getOuterLocStart(), and clang::TagDecl::getOuterLocStart().
getVisibilityFromAttr()
template<class T > static Visibility getVisibilityFromAttr (const T * attr) static
Given a visibility attribute, return the explicit visibility associated with it.
Definition at line 208 of file Decl.cpp.
References clang::ast_matchers::attr, clang::DefaultVisibility, clang::HiddenVisibility, and clang::ProtectedVisibility.
Referenced by getVisibilityOf().
getVisibilityOf()
static Optional<Visibility> getVisibilityOf (const NamedDecl * D, NamedDecl::ExplicitVisibilityKind kind) static
Return the explicit visibility of the given declaration.
Definition at line 221 of file Decl.cpp.
References clang::Decl::getAttr(), getVisibilityFromAttr(), and clang::NamedDecl::VisibilityForType.
Referenced by getExplicitVisibilityAux().
hasDirectVisibilityAttribute()
static bool hasDirectVisibilityAttribute (const NamedDecl * D, LVComputationKind computation) static
Does the given declaration have a direct visibility attribute that would match the given rules?
Definition at line 415 of file Decl.cpp.
References clang::Decl::hasAttr(), clang::LVComputationKind::IgnoreAllVisibility, and clang::LVComputationKind::isTypeVisibility().
Referenced by shouldConsiderTemplateVisibility().
hasExplicitVisibilityAlready()
static bool hasExplicitVisibilityAlready (LVComputationKind computation) static
Does this computation kind permit us to consider additional visibility settings from attributes and the like?
Definition at line 159 of file Decl.cpp.
References clang::LVComputationKind::IgnoreExplicitVisibility.
Referenced by shouldConsiderTemplateVisibility().
isDeclExternC()
template<typename T > static bool isDeclExternC (const T & D) static
Definition at line 2130 of file Decl.cpp.
References clang::CLanguageLinkage, and clang::DeclContext::isRecord().
Referenced by clang::VarDecl::isExternC(), and clang::FunctionDecl::isExternC().
isExplicitMemberSpecialization() [1/2]
static bool isExplicitMemberSpecialization (const RedeclarableTemplateDecl * D) static
For templates, this question is easier: a member template can't be explicitly instantiated, so there's a single bit indicating whether or not this is an explicit member specialization.
Definition at line 201 of file Decl.cpp.
References clang::RedeclarableTemplateDecl::isMemberSpecialization().
isExplicitMemberSpecialization() [2/2]
template<class T > static std::enable_if<!std::is_base_of<RedeclarableTemplateDecl, T>::value, bool>::type isExplicitMemberSpecialization (const T * D) static
Does the given declaration have member specialization information, and if so, is it an explicit specialization?
Definition at line 190 of file Decl.cpp.
References clang::transformer::member().
isExportedFromModuleInterfaceUnit()
static bool isExportedFromModuleInterfaceUnit (const NamedDecl * D) static
Definition at line 585 of file Decl.cpp.
References clang::Decl::getModuleOwnershipKind(), isInModulePurview(), clang::Decl::ModulePrivate, clang::Decl::Unowned, clang::Decl::Visible, and clang::Decl::VisibleWhenImported.
Referenced by getExternalLinkageFor().
isFirstInExternCContext()
template<typename T > static bool isFirstInExternCContext (T * D) static
Definition at line 566 of file Decl.cpp.
References clang::First.
Referenced by getDeclLanguageLinkage().
isInModulePurview()
static bool isInModulePurview (const NamedDecl * D) static
Determine whether D is declared in the purview of a named module.
Definition at line 579 of file Decl.cpp.
References clang::Decl::getOwningModule().
Referenced by getExternalLinkageFor(), getInternalLinkageFor(), and isExportedFromModuleInterfaceUnit().
isNamed()
template<std::size_t Len> static bool isNamed (const NamedDecl * ND, const char(&) Str[Len]) static
Definition at line 3079 of file Decl.cpp.
References clang::NamedDecl::getIdentifier(), and clang::IdentifierInfo::isStr().
Referenced by clang::FunctionDecl::isMain().
isRedeclarable()
static bool isRedeclarable (Decl::Kind K) static
Definition at line 1757 of file Decl.cpp.
Referenced by clang::NamedDecl::declarationReplaces().
isRedeclarableImpl() [1/2]
static bool isRedeclarableImpl (...) static
Definition at line 1756 of file Decl.cpp.
isRedeclarableImpl() [2/2]
template<typename T > static bool isRedeclarableImpl (Redeclarable< T > *) static
Definition at line 1753 of file Decl.cpp.
isSingleLineLanguageLinkage()
static bool isSingleLineLanguageLinkage (const Decl & D) static
Definition at line 571 of file Decl.cpp.
References clang::Decl::getDeclContext().
Referenced by clang::VarDecl::isThisDeclarationADefinition().
RedeclForcesDefC99()
static bool RedeclForcesDefC99 (const FunctionDecl * Redecl) static
Definition at line 3481 of file Decl.cpp.
References clang::Decl::getLexicalDeclContext(), clang::FunctionDecl::getStorageClass(), clang::Decl::isImplicit(), clang::FunctionDecl::isInlineSpecified(), clang::DeclContext::isTranslationUnit(), and clang::SC_Extern.
Referenced by clang::FunctionDecl::doesDeclarationForceExternallyVisibleDefinition(), and clang::FunctionDecl::isInlineDefinitionExternallyVisible().
redeclForcesDefMSVC()
static bool redeclForcesDefMSVC (const FunctionDecl * Redecl) static
Definition at line 3469 of file Decl.cpp.
References clang::Redeclarable< decl_type >::getPreviousDecl(), clang::FunctionDecl::getStorageClass(), and clang::SC_Extern.
Referenced by clang::FunctionDecl::doesDeclarationForceExternallyVisibleDefinition().
shouldConsiderTemplateVisibility() [1/3]
static bool shouldConsiderTemplateVisibility (const ClassTemplateSpecializationDecl * spec, LVComputationKind computation) static
Should we consider visibility associated with the template arguments and parameters of the given class template specialization?
Definition at line 426 of file Decl.cpp.
References hasDirectVisibilityAttribute(), hasExplicitVisibilityAlready(), clang::ClassTemplateSpecializationDecl::isExplicitInstantiationOrSpecialization(), and clang::ClassTemplateSpecializationDecl::isExplicitSpecialization().
shouldConsiderTemplateVisibility() [2/3]
static bool shouldConsiderTemplateVisibility (const FunctionDecl * fn, const FunctionTemplateSpecializationInfo * specInfo) static
Definition at line 368 of file Decl.cpp.
References clang::Decl::hasAttr(), and clang::FunctionTemplateSpecializationInfo::isExplicitInstantiationOrSpecialization().
shouldConsiderTemplateVisibility() [3/3]
static bool shouldConsiderTemplateVisibility (const VarTemplateSpecializationDecl * spec, LVComputationKind computation) static
Should we consider visibility associated with the template arguments and parameters of the given variable template specialization? As usual, follow class template specialization logic up to initialization.
Definition at line 490 of file Decl.cpp.
References hasDirectVisibilityAttribute(), hasExplicitVisibilityAlready(), clang::VarTemplateSpecializationDecl::isExplicitInstantiationOrSpecialization(), and clang::VarTemplateSpecializationDecl::isExplicitSpecialization().
typeIsPostfix()
static bool typeIsPostfix (QualType QT) static
Definition at line 1956 of file Decl.cpp.
References clang::Type::getPointeeType(), clang::Type::getTypeClass(), clang::QualType::getTypePtr(), and Paren.
Referenced by clang::DeclaratorDecl::getSourceRange(), and clang::TypedefDecl::getSourceRange().
useInlineVisibilityHidden()
static bool useInlineVisibilityHidden (const NamedDecl * D) static
Definition at line 538 of file Decl.cpp.
References clang::Decl::getASTContext(), clang::ASTContext::getLangOpts(), clang::VarDecl::getTemplateSpecializationKind(), clang::Decl::hasAttr(), clang::FunctionDecl::isInlined(), clang::TSK_ExplicitInstantiationDeclaration, clang::TSK_ExplicitInstantiationDefinition, and clang::TSK_Undeclared.
usesTypeVisibility()
static bool usesTypeVisibility (const NamedDecl * D) static
Is the given declaration a "type" or a "value" for the purposes of visibility computation?
Definition at line 180 of file Decl.cpp.
Referenced by clang::LinkageComputer::getDeclLinkageAndVisibility().
withExplicitVisibilityAlready()
static LVComputationKind withExplicitVisibilityAlready (LVComputationKind Kind) static
Given an LVComputationKind, return one of the same type/value sort that records that it already has explicit visibility.
Definition at line 166 of file Decl.cpp.