clang: lib/Rewrite/DeltaTree.cpp File Reference
DeltaTree.cpp File Reference
#include "clang/Rewrite/Core/DeltaTree.h"
#include "clang/Basic/LLVM.h"
#include "llvm/Support/Casting.h"
#include <cassert>
#include <cstring>
Functions
static DeltaTreeNode * getRoot (void *Root)
Function Documentation
getRoot()
static DeltaTreeNode* getRoot (void * Root) static
Definition at line 386 of file DeltaTree.cpp.
Referenced by clang::DeltaTree::AddDelta(), clang::DeltaTree::DeltaTree(), clang::DeltaTree::getDeltaAt(), clang::ento::BlockCounter::Factory::GetEmptyCounter(), and clang::DeltaTree::~DeltaTree().