clang: lib/Tooling/DependencyScanning/DependencyScanningWorker.cpp File Reference
DependencyScanningWorker.cpp File Reference
#include "clang/Tooling/DependencyScanning/DependencyScanningWorker.h"
#include "clang/Basic/DiagnosticDriver.h"
#include "clang/Basic/DiagnosticFrontend.h"
#include "clang/Basic/DiagnosticSerialization.h"
#include "clang/CodeGen/ObjectFilePCHContainerOperations.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/Job.h"
#include "clang/Driver/Tool.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/CompilerInvocation.h"
#include "clang/Frontend/FrontendActions.h"
#include "clang/Frontend/TextDiagnosticPrinter.h"
#include "clang/Frontend/Utils.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "clang/Tooling/DependencyScanning/DependencyScanningService.h"
#include "clang/Tooling/DependencyScanning/ModuleDepCollector.h"
#include "clang/Tooling/Tooling.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Error.h"
#include "llvm/TargetParser/Host.h"
#include <optional>
Functions
static bool forEachDriverJob (ArrayRef< std::string > ArgStrs, DiagnosticsEngine &Diags, FileManager &FM, llvm::function_ref< bool(const driver::Command &Cmd)> Callback)
static bool createAndRunToolInvocation (std::vector< std::string > CommandLine, DependencyScanningAction &Action, FileManager &FM, std::shared_ptr< clang::PCHContainerOperations > &PCHContainerOps, DiagnosticsEngine &Diags, DependencyConsumer &Consumer)
Function Documentation
createAndRunToolInvocation()
static bool createAndRunToolInvocation (std::vector< std::string > CommandLine, DependencyScanningAction & Action, FileManager & FM, std::shared_ptr< clang::PCHContainerOperations > & PCHContainerOps, DiagnosticsEngine & Diags, DependencyConsumer & Consumer) static
Definition at line 569 of file DependencyScanningWorker.cpp.
References clang::DiagnosticsEngine::getClient(), clang::DiagnosticsEngine::getDiagnosticOptions(), clang::tooling::dependencies::DependencyConsumer::handleBuildCommand(), clang::tooling::ToolInvocation::run(), clang::tooling::ToolInvocation::setDiagnosticConsumer(), and clang::tooling::ToolInvocation::setDiagnosticOptions().
Referenced by clang::tooling::dependencies::DependencyScanningWorker::computeDependencies().
forEachDriverJob()
static bool forEachDriverJob (ArrayRef< std::string > ArgStrs, DiagnosticsEngine & Diags, FileManager & FM, llvm::function_ref< bool(const driver::Command &Cmd)> Callback) static
Definition at line 529 of file DependencyScanningWorker.cpp.
Referenced by clang::tooling::dependencies::DependencyScanningWorker::computeDependencies().