clang: lib/Lex/DependencyDirectivesSourceMinimizer.cpp File Reference
DependencyDirectivesSourceMinimizer.cpp File Reference
#include "clang/Lex/DependencyDirectivesSourceMinimizer.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Lex/LexDiagnostic.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/MemoryBuffer.h"
Functions
static void skipOverSpaces (const char *&First, const char *const End)
static LLVM_NODISCARD bool isRawStringLiteral (const char *First, const char *Current)
static void skipRawString (const char *&First, const char *const End)
static unsigned isEOL (const char *First, const char *const End)
static void skipString (const char *&First, const char *const End)
static unsigned skipNewline (const char *&First, const char *End)
static bool wasLineContinuation (const char *First, unsigned EOLLen)
static void skipToNewlineRaw (const char *&First, const char *const End)
static const char * findLastNonSpace (const char *First, const char *Last)
static const char * findLastNonSpaceNonBackslash (const char *First, const char *Last)
static const char * findFirstTrailingSpace (const char *First, const char *Last)
static void skipLineComment (const char *&First, const char *const End)
static void skipBlockComment (const char *&First, const char *const End)
static bool isQuoteCppDigitSeparator (const char *const Start, const char *const Cur, const char *const End)
static void skipLine (const char *&First, const char *const End)
static void skipDirective (StringRef Name, const char *&First, const char *const End)
static void skipWhitespace (const char *&First, const char *const End)
static const LLVM_NODISCARD char * lexRawIdentifier (const char *First, const char *const End)
static const LLVM_NODISCARD char * getIdentifierContinuation (const char *First, const char *const End)
static bool isStartOfRelevantLine (char First)
static void skipUTF8ByteOrderMark (const char *&First, const char *const End)
Detailed Description
This is the implementation for minimizing header and source files to the minimum necessary preprocessor directives for evaluating includes. It reduces the source down to #define, include, #import, @import, and any conditional preprocessor logic that contains one of those.
Definition in file DependencyDirectivesSourceMinimizer.cpp.
Function Documentation
findFirstTrailingSpace()
static const char* findFirstTrailingSpace (const char * First, const char * Last) static
Definition at line 282 of file DependencyDirectivesSourceMinimizer.cpp.
References findLastNonSpace(), clang::First, clang::isHorizontalWhitespace(), and clang::Last.
findLastNonSpace()
static const char* findLastNonSpace (const char * First, const char * Last) static
Definition at line 266 of file DependencyDirectivesSourceMinimizer.cpp.
References clang::First, clang::isHorizontalWhitespace(), and clang::Last.
Referenced by findFirstTrailingSpace().
findLastNonSpaceNonBackslash()
static const char* findLastNonSpaceNonBackslash (const char * First, const char * Last) static
Definition at line 273 of file DependencyDirectivesSourceMinimizer.cpp.
References clang::First, clang::isHorizontalWhitespace(), and clang::Last.
getIdentifierContinuation()
static const LLVM_NODISCARD char* getIdentifierContinuation (const char * First, const char *const End) static
Definition at line 544 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, clang::isAsciiIdentifierContinue(), clang::isVerticalWhitespace(), and skipNewline().
isEOL()
static unsigned isEOL (const char * First, const char *const End) static
Definition at line 190 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, and clang::isVerticalWhitespace().
Referenced by skipNewline(), skipString(), and skipToNewlineRaw().
isQuoteCppDigitSeparator()
static bool isQuoteCppDigitSeparator (const char *const Start, const char *const Cur, const char *const End) static
Returns
True if the current single quotation mark character is a C++ 14 digit separator.
Definition at line 312 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::isAsciiIdentifierContinue(), and clang::isPreprocessingNumberBody().
Referenced by skipLine().
isRawStringLiteral()
static LLVM_NODISCARD bool isRawStringLiteral (const char * First, const char * Current) static
Definition at line 122 of file DependencyDirectivesSourceMinimizer.cpp.
Referenced by skipLine().
isStartOfRelevantLine()
static bool isStartOfRelevantLine (char First) static
Definition at line 820 of file DependencyDirectivesSourceMinimizer.cpp.
References clang::First.
lexRawIdentifier()
static const LLVM_NODISCARD char* lexRawIdentifier (const char * First, const char *const End) static
Definition at line 534 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, clang::isAsciiIdentifierContinue(), and clang::Last.
skipBlockComment()
static void skipBlockComment (const char *& First, const char *const End) static
Definition at line 297 of file DependencyDirectivesSourceMinimizer.cpp.
References End, and clang::First.
Referenced by skipLine(), and skipWhitespace().
skipDirective()
static void skipDirective (StringRef Name, const char *& First, const char *const End) static
Definition at line 386 of file DependencyDirectivesSourceMinimizer.cpp.
skipLine()
static void skipLine (const char *& First, const char *const End) static
Definition at line 334 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, isQuoteCppDigitSeparator(), isRawStringLiteral(), clang::isVerticalWhitespace(), skipBlockComment(), skipLineComment(), skipNewline(), skipRawString(), skipString(), and wasLineContinuation().
skipLineComment()
static void skipLineComment (const char *& First, const char *const End) static
Definition at line 291 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, and skipToNewlineRaw().
Referenced by skipLine(), and skipWhitespace().
skipNewline()
static unsigned skipNewline (const char *& First, const char * End) static
Definition at line 229 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, isEOL(), and clang::isVerticalWhitespace().
Referenced by getIdentifierContinuation(), skipLine(), and skipWhitespace().
skipOverSpaces()
static void skipOverSpaces (const char *& First, const char *const End) static
Definition at line 117 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, and clang::isHorizontalWhitespace().
Referenced by skipString(), and skipWhitespace().
skipRawString()
static void skipRawString (const char *& First, const char *const End) static
Definition at line 147 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, and clang::Last.
Referenced by skipLine().
skipString()
static void skipString (const char *& First, const char *const End) static
Definition at line 199 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, isEOL(), clang::isVerticalWhitespace(), clang::isWhitespace(), and skipOverSpaces().
Referenced by skipLine().
skipToNewlineRaw()
static void skipToNewlineRaw (const char *& First, const char *const End) static
Definition at line 243 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, and isEOL().
Referenced by skipLineComment().
skipUTF8ByteOrderMark()
static void skipUTF8ByteOrderMark (const char *& First, const char *const End) static
Definition at line 903 of file DependencyDirectivesSourceMinimizer.cpp.
References End, and clang::First.
skipWhitespace()
static void skipWhitespace (const char *& First, const char *const End) static
Definition at line 458 of file DependencyDirectivesSourceMinimizer.cpp.
References End, clang::First, clang::isVerticalWhitespace(), skipBlockComment(), skipLineComment(), skipNewline(), and skipOverSpaces().
wasLineContinuation()
static bool wasLineContinuation (const char * First, unsigned EOLLen) static
Definition at line 239 of file DependencyDirectivesSourceMinimizer.cpp.
References clang::First, and int.
Referenced by skipLine().