clang: lib/AST/Interp/Descriptor.cpp File Reference
Descriptor.cpp File Reference
#include "Descriptor.h"
#include "Boolean.h"
#include "Floating.h"
#include "FunctionPointer.h"
#include "IntegralAP.h"
#include "MemberPointer.h"
#include "Pointer.h"
#include "PrimType.h"
#include "Record.h"
Functions
template<typename T >
static void ctorTy (Block *, std::byte *Ptr, bool, bool, bool, const Descriptor *)
template<typename T >
static void dtorTy (Block *, std::byte *Ptr, const Descriptor *)
template<typename T >
static void moveTy (Block *, const std::byte *Src, std::byte *Dst, const Descriptor *)
template<typename T >
static void ctorArrayTy (Block *, std::byte *Ptr, bool, bool, bool, const Descriptor *D)
template<typename T >
static void dtorArrayTy (Block *, std::byte *Ptr, const Descriptor *D)
template<typename T >
static void moveArrayTy (Block *, const std::byte *Src, std::byte *Dst, const Descriptor *D)
static void ctorArrayDesc (Block *B, std::byte *Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor *D)
static void dtorArrayDesc (Block *B, std::byte *Ptr, const Descriptor *D)
static void moveArrayDesc (Block *B, const std::byte *Src, std::byte *Dst, const Descriptor *D)
static void initField (Block *B, std::byte *Ptr, bool IsConst, bool IsMutable, bool IsActive, bool IsUnion, const Descriptor *D, unsigned FieldOffset)
static void initBase (Block *B, std::byte *Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor *D, unsigned FieldOffset)
static void ctorRecord (Block *B, std::byte *Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor *D)
static void destroyField (Block *B, std::byte *Ptr, const Descriptor *D, unsigned FieldOffset)
static void destroyBase (Block *B, std::byte *Ptr, const Descriptor *D, unsigned FieldOffset)
static void dtorRecord (Block *B, std::byte *Ptr, const Descriptor *D)
static void moveRecord (Block *B, const std::byte *Src, std::byte *Dst, const Descriptor *D)
static BlockCtorFn getCtorPrim (PrimType Type)
static BlockDtorFn getDtorPrim (PrimType Type)
static BlockMoveFn getMovePrim (PrimType Type)
static BlockCtorFn getCtorArrayPrim (PrimType Type)
static BlockDtorFn getDtorArrayPrim (PrimType Type)
static BlockMoveFn getMoveArrayPrim (PrimType Type)
Function Documentation
ctorArrayDesc()
static void ctorArrayDesc (Block * B, std::byte * Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor * D) static
Definition at line 84 of file Descriptor.cpp.
References D.
ctorArrayTy()
template<typename T > static void ctorArrayTy (Block * , std::byte * Ptr, bool , bool , bool , const Descriptor * D) static
Definition at line 42 of file Descriptor.cpp.
References D, clang::interp::NE(), and clang::T.
ctorRecord()
static void ctorRecord (Block * B, std::byte * Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor * D) static
Definition at line 187 of file Descriptor.cpp.
References D, initBase(), initField(), and V.
ctorTy()
template<typename T > static void ctorTy (Block * , std::byte * Ptr, bool , bool , bool , const Descriptor *) static
Definition at line 23 of file Descriptor.cpp.
References clang::T.
destroyBase()
static void destroyBase (Block * B, std::byte * Ptr, const Descriptor * D, unsigned FieldOffset) static
Definition at line 203 of file Descriptor.cpp.
References D, destroyField(), and V.
Referenced by dtorRecord().
destroyField()
static void destroyField (Block * B, std::byte * Ptr, const Descriptor * D, unsigned FieldOffset) static
Definition at line 197 of file Descriptor.cpp.
References D.
Referenced by destroyBase(), and dtorRecord().
dtorArrayDesc()
static void dtorArrayDesc (Block * B, std::byte * Ptr, const Descriptor * D) static
Definition at line 110 of file Descriptor.cpp.
References D.
dtorArrayTy()
template<typename T > static void dtorArrayTy (Block * , std::byte * Ptr, const Descriptor * D) static
Definition at line 53 of file Descriptor.cpp.
References D, clang::interp::NE(), and clang::T.
dtorRecord()
static void dtorRecord (Block * B, std::byte * Ptr, const Descriptor * D) static
Definition at line 214 of file Descriptor.cpp.
References D, destroyBase(), and destroyField().
dtorTy()
template<typename T > static void dtorTy (Block * , std::byte * Ptr, const Descriptor *) static
Definition at line 29 of file Descriptor.cpp.
References clang::T.
getCtorArrayPrim()
static BlockCtorFn getCtorArrayPrim (PrimType Type) static
Definition at line 268 of file Descriptor.cpp.
References TYPE_SWITCH.
getCtorPrim()
static BlockCtorFn getCtorPrim (PrimType Type) static
Definition at line 234 of file Descriptor.cpp.
References COMPOSITE_TYPE_SWITCH, clang::interp::PT_Float, clang::interp::PT_IntAP, clang::interp::PT_IntAPS, clang::interp::PT_MemberPtr, and clang::T.
getDtorArrayPrim()
static BlockDtorFn getDtorArrayPrim (PrimType Type) static
Definition at line 273 of file Descriptor.cpp.
References TYPE_SWITCH.
getDtorPrim()
static BlockDtorFn getDtorPrim (PrimType Type) static
Definition at line 249 of file Descriptor.cpp.
References COMPOSITE_TYPE_SWITCH, clang::interp::PT_Float, clang::interp::PT_IntAP, clang::interp::PT_IntAPS, clang::interp::PT_MemberPtr, and clang::T.
getMoveArrayPrim()
static BlockMoveFn getMoveArrayPrim (PrimType Type) static
Definition at line 278 of file Descriptor.cpp.
References TYPE_SWITCH.
getMovePrim()
static BlockMoveFn getMovePrim (PrimType Type) static
Definition at line 264 of file Descriptor.cpp.
References COMPOSITE_TYPE_SWITCH.
initBase()
static void initBase (Block * B, std::byte * Ptr, bool IsConst, bool IsMutable, bool IsActive, const Descriptor * D, unsigned FieldOffset) static
Definition at line 164 of file Descriptor.cpp.
References D, initField(), clang::interp::InlineDescriptor::Offset, and V.
Referenced by ctorRecord().
initField()
static void initField (Block * B, std::byte * Ptr, bool IsConst, bool IsMutable, bool IsActive, bool IsUnion, const Descriptor * D, unsigned FieldOffset) static
Definition at line 147 of file Descriptor.cpp.
References D, and clang::interp::InlineDescriptor::Offset.
Referenced by ctorRecord(), and initBase().
moveArrayDesc()
static void moveArrayDesc (Block * B, const std::byte * Src, std::byte * Dst, const Descriptor * D) static
Definition at line 125 of file Descriptor.cpp.
References D.
moveArrayTy()
template<typename T > static void moveArrayTy (Block * , const std::byte * Src, std::byte * Dst, const Descriptor * D) static
Definition at line 65 of file Descriptor.cpp.
References D, clang::interp::NE(), and clang::T.
moveRecord()
static void moveRecord (Block * B, const std::byte * Src, std::byte * Dst, const Descriptor * D) static
Definition at line 223 of file Descriptor.cpp.
References D.
moveTy()
template<typename T > static void moveTy (Block * , const std::byte * Src, std::byte * Dst, const Descriptor *) static
Definition at line 34 of file Descriptor.cpp.
References clang::T.