clang: lib/Basic/DiagnosticIDs.cpp File Reference
DiagnosticIDs.cpp File Reference
#include "clang/Basic/DiagnosticIDs.h"
#include "clang/Basic/AllDiagnostics.h"
#include "clang/Basic/DiagnosticCategories.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/ErrorHandling.h"
#include <map>
#include "clang/Basic/DiagnosticCommonKinds.inc"
#include "clang/Basic/DiagnosticDriverKinds.inc"
#include "clang/Basic/DiagnosticFrontendKinds.inc"
#include "clang/Basic/DiagnosticSerializationKinds.inc"
#include "clang/Basic/DiagnosticLexKinds.inc"
#include "clang/Basic/DiagnosticParseKinds.inc"
#include "clang/Basic/DiagnosticASTKinds.inc"
#include "clang/Basic/DiagnosticCommentKinds.inc"
#include "clang/Basic/DiagnosticCrossTUKinds.inc"
#include "clang/Basic/DiagnosticSemaKinds.inc"
#include "clang/Basic/DiagnosticAnalysisKinds.inc"
#include "clang/Basic/DiagnosticRefactoringKinds.inc"
#include "clang/Basic/DiagnosticGroups.inc"
Classes
class clang::diag::CustomDiagInfo
Namespaces
clang
clang::diag
Macros
#define DIAG(ENUM, CLASS, DEFAULT_SEVERITY, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, SHOWINSYSMACRO, DEFERRABLE, CATEGORY) char ENUM##_desc[sizeof(DESC)];
#define DIAG(ENUM, CLASS, DEFAULT_SEVERITY, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, SHOWINSYSMACRO, DEFERRABLE, CATEGORY) DESC,
#define DIAG(ENUM, CLASS, DEFAULT_SEVERITY, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, SHOWINSYSMACRO, DEFERRABLE, CATEGORY) offsetof(StaticDiagInfoDescriptionStringTable, ENUM##_desc),
#define STRINGIFY_NAME(NAME) #NAME
#define VALIDATE_DIAG_SIZE(NAME)
#define DIAG(ENUM, CLASS, DEFAULT_SEVERITY, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, SHOWINSYSMACRO, DEFERRABLE, CATEGORY)
#define CATEGORY(NAME, PREV)
#define GET_CATEGORY_TABLE
#define CATEGORY(X, ENUM) { X, STR_SIZE(X, uint8_t) },
#define GET_DIAG_ARRAYS
#define DIAG_ENTRY(GroupName, FlagNameOffset, Members, SubGroups) {FlagNameOffset, Members, SubGroups},
Functions
static const StaticDiagInfoRec * GetDiagInfo (unsigned DiagID)
GetDiagInfo - Return the StaticDiagInfoRec entry for the specified DiagID, or null if the ID is invalid.
static DiagnosticMapping GetDefaultDiagMapping (unsigned DiagID)
static unsigned getBuiltinDiagClass (unsigned DiagID)
getBuiltinDiagClass - Return the class field of the diagnostic.
static DiagnosticIDs::Level toLevel (diag::Severity SV)
static bool getDiagnosticsInGroup (diag::Flavor Flavor, const WarningOption *Group, SmallVectorImpl< diag::kind > &Diags)
Return true if any diagnostics were found in this group, even if they were filtered out due to having the wrong flavor.
Variables
static const unsigned StaticDiagInfoSize = llvm::array_lengthof(StaticDiagInfo)
static const StaticDiagCategoryRec CategoryNameTable []
static const WarningOption OptionTable []
Macro Definition Documentation
CATEGORY [1/2]
#define CATEGORY (NAME, PREV)
Value:
  if (DiagID > DIAG_START_##NAME) { \
    Offset += NUM_BUILTIN_##PREV##_DIAGNOSTICS - DIAG_START_##PREV - 1; \
    ID -= DIAG_START_##NAME - DIAG_START_##PREV; \
  }
CATEGORY [2/2]
#define CATEGORY (X, ENUM) { X, STR_SIZE(X, uint8_t) },
DIAG [1/4]
#define DIAG (ENUM, CLASS, DEFAULT_SEVERITY, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, SHOWINSYSMACRO, DEFERRABLE, CATEGORY) char ENUM##_desc[sizeof(DESC)];
Definition at line 35 of file DiagnosticIDs.cpp.
DIAG [2/4]
#define DIAG (ENUM, CLASS, DEFAULT_SEVERITY, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, SHOWINSYSMACRO, DEFERRABLE, CATEGORY) DESC,
Definition at line 35 of file DiagnosticIDs.cpp.
DIAG [3/4]
#define DIAG (ENUM, CLASS, DEFAULT_SEVERITY, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, SHOWINSYSMACRO, DEFERRABLE, CATEGORY) offsetof(StaticDiagInfoDescriptionStringTable, ENUM##_desc),
Definition at line 35 of file DiagnosticIDs.cpp.
DIAG [4/4]
#define DIAG (ENUM, CLASS, DEFAULT_SEVERITY, DESC, GROUP, SFINAE, NOWERROR, SHOWINSYSHEADER, SHOWINSYSMACRO, DEFERRABLE, CATEGORY)
Value:
  {                                                                            \
      diag::ENUM,                                                              \
      DEFAULT_SEVERITY,                                                        \
      CLASS,                                                                   \
      DiagnosticIDs::SFINAE,                                                   \
      CATEGORY,                                                                \
      NOWERROR,                                                                \
      SHOWINSYSHEADER,                                                         \
      SHOWINSYSMACRO,                                                          \
      GROUP,                                                                   \
      DEFERRABLE,                                                              \
      STR_SIZE(DESC, uint16_t)},
Definition at line 35 of file DiagnosticIDs.cpp.
DIAG_ENTRY
#define DIAG_ENTRY (GroupName, FlagNameOffset, Members, SubGroups) {FlagNameOffset, Members, SubGroups},
GET_CATEGORY_TABLE
#define GET_CATEGORY_TABLE
GET_DIAG_ARRAYS
#define GET_DIAG_ARRAYS
Definition at line 601 of file DiagnosticIDs.cpp.
STRINGIFY_NAME
#define STRINGIFY_NAME (NAME) #NAME
Definition at line 146 of file DiagnosticIDs.cpp.
VALIDATE_DIAG_SIZE
#define VALIDATE_DIAG_SIZE (NAME)
Value:
  static_assert(                                                               \
      static_cast<unsigned>(diag::NUM_BUILTIN_##NAME##_DIAGNOSTICS) <          \
          static_cast<unsigned>(diag::DIAG_START_##NAME) +                     \
              static_cast<unsigned>(diag::DIAG_SIZE_##NAME),                   \
      STRINGIFY_NAME(                                                          \
          DIAG_SIZE_##NAME) " is insufficient to contain all "                 \
                            "diagnostics, it may need to be made larger in "   \
                            "DiagnosticIDs.h.");
Definition at line 147 of file DiagnosticIDs.cpp.
Function Documentation
getBuiltinDiagClass()
static unsigned getBuiltinDiagClass (unsigned DiagID) static
getBuiltinDiagClass - Return the class field of the diagnostic.
Definition at line 349 of file DiagnosticIDs.cpp.
References GetDiagInfo().
Referenced by clang::DiagnosticIDs::isBuiltinExtensionDiag(), clang::DiagnosticIDs::isBuiltinNote(), and clang::DiagnosticIDs::isBuiltinWarningOrExtension().
GetDefaultDiagMapping()
static DiagnosticMapping GetDefaultDiagMapping (unsigned DiagID) static
Definition at line 258 of file DiagnosticIDs.cpp.
References clang::diag::Fatal, GetDiagInfo(), clang::DiagnosticMapping::getSeverity(), clang::DiagnosticMapping::Make(), clang::DiagnosticMapping::setNoWarningAsError(), clang::DiagnosticMapping::setSeverity(), and clang::diag::Warning.
Referenced by clang::DiagnosticIDs::isBuiltinExtensionDiag(), and clang::DiagnosticIDs::isDefaultMappingAsError().
GetDiagInfo()
static const StaticDiagInfoRec* GetDiagInfo (unsigned DiagID) static
GetDiagInfo - Return the StaticDiagInfoRec entry for the specified DiagID, or null if the ID is invalid.
Definition at line 209 of file DiagnosticIDs.cpp.
References ANALYSIS, CATEGORY, COMMENT, clang::diag::DIAG_START_COMMON, clang::diag::DIAG_UPPER_LIMIT, Offset, and StaticDiagInfoSize.
Referenced by getBuiltinDiagClass(), clang::DiagnosticIDs::getCategoryNumberForDiag(), GetDefaultDiagMapping(), clang::DiagnosticIDs::getDescription(), clang::DiagnosticIDs::getDiagnosticSFINAEResponse(), getDiagnosticsInGroup(), clang::DiagnosticIDs::getWarningOptionForDiag(), and clang::DiagnosticIDs::isDeferrable().
getDiagnosticsInGroup()
static bool getDiagnosticsInGroup (diag::Flavor Flavor, const WarningOption * Group, SmallVectorImpl< diag::kind > & Diags) static
Return true if any diagnostics were found in this group, even if they were filtered out due to having the wrong flavor.
Definition at line 655 of file DiagnosticIDs.cpp.
References GetDiagInfo(), clang::Member, OptionTable, and clang::diag::Remark.
Referenced by clang::DiagnosticIDs::getDiagnosticsInGroup().
toLevel()
static DiagnosticIDs::Level toLevel (diag::Severity SV) static
Definition at line 471 of file DiagnosticIDs.cpp.
References clang::diag::Error, clang::DiagnosticIDs::Error, clang::diag::Fatal, clang::DiagnosticIDs::Fatal, clang::diag::Ignored, clang::DiagnosticIDs::Ignored, clang::diag::Remark, clang::DiagnosticIDs::Remark, clang::diag::Warning, and clang::DiagnosticIDs::Warning.
Variable Documentation
CategoryNameTable
const StaticDiagCategoryRec CategoryNameTable[] static
Initial value:
= {
#define GET_CATEGORY_TABLE
#define CATEGORY(X, ENUM)
  { nullptr, 0 }
}
Definition at line 310 of file DiagnosticIDs.cpp.
Referenced by clang::DiagnosticIDs::getCategoryNameFromID(), and clang::DiagnosticIDs::getNumberOfCategories().
OptionTable
const WarningOption OptionTable[] static
Initial value:
= {
#define DIAG_ENTRY(GroupName, FlagNameOffset, Members, SubGroups)
}
Definition at line 620 of file DiagnosticIDs.cpp.
Referenced by clang::DiagnosticIDs::getDiagnosticsInGroup(), getDiagnosticsInGroup(), clang::DiagnosticIDs::getNearestOption(), and clang::DiagnosticIDs::getWarningOptionForGroup().
StaticDiagInfoSize
const unsigned StaticDiagInfoSize = llvm::array_lengthof(StaticDiagInfo) static
Definition at line 205 of file DiagnosticIDs.cpp.
Referenced by clang::DiagnosticIDs::getAllDiagnostics(), and GetDiagInfo().