clang: lib/AST/Interp/Disasm.cpp File Reference
Disasm.cpp File Reference
#include "Boolean.h"
#include "Floating.h"
#include "Function.h"
#include "FunctionPointer.h"
#include "Integral.h"
#include "IntegralAP.h"
#include "InterpFrame.h"
#include "Opcode.h"
#include "PrimType.h"
#include "Program.h"
#include "clang/AST/ASTDumperUtils.h"
#include "clang/AST/DeclCXX.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Format.h"
#include "Opcodes.inc"
Macros
#define GET_DISASM
Functions
template<typename T >
T ReadArg (Program &P, CodePtr &OpPC)
template<>
Floating ReadArg< Floating > (Program &P, CodePtr &OpPC)
template<>
IntegralAP< false > ReadArg< IntegralAP< false > > (Program &P, CodePtr &OpPC)
template<>
IntegralAP< true > ReadArg< IntegralAP< true > > (Program &P, CodePtr &OpPC)
static const char * primTypeToString (PrimType T)
Macro Definition Documentation
GET_DISASM
#define GET_DISASM
Function Documentation
primTypeToString()
static const char* primTypeToString (PrimType T) static
Definition at line 93 of file Disasm.cpp.
References clang::interp::PT_Bool, clang::interp::PT_Float, clang::interp::PT_FnPtr, clang::interp::PT_IntAP, clang::interp::PT_IntAPS, clang::interp::PT_Ptr, clang::interp::PT_Sint16, clang::interp::PT_Sint32, clang::interp::PT_Sint64, clang::interp::PT_Sint8, clang::interp::PT_Uint16, clang::interp::PT_Uint32, clang::interp::PT_Uint64, clang::interp::PT_Uint8, and clang::T.
Referenced by clang::interp::Program::dump().
ReadArg()
template<typename T > T ReadArg (Program & P, CodePtr & OpPC) inline
Definition at line 31 of file Disasm.cpp.
References ID, P, clang::interp::CodePtr::read(), and clang::T.
ReadArg< Floating >()
template<> Floating ReadArg< Floating > (Program & P, CodePtr & OpPC) inline
Definition at line 40 of file Disasm.cpp.
References clang::interp::align(), clang::interp::Floating::bytesToSerialize(), and clang::interp::Floating::deserialize().
ReadArg< IntegralAP< false > >()
template<> IntegralAP<false> ReadArg< IntegralAP< false > > (Program & P, CodePtr & OpPC) inline
Definition at line 40 of file Disasm.cpp.
ReadArg< IntegralAP< true > >()
template<> IntegralAP<true> ReadArg< IntegralAP< true > > (Program & P, CodePtr & OpPC) inline
Definition at line 40 of file Disasm.cpp.