clang: lib/Driver/Distro.cpp File Reference
Distro.cpp File Reference
#include "clang/Driver/Distro.h"
#include "clang/Basic/LLVM.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Threading.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/Triple.h"
Functions
static Distro::DistroType DetectOsRelease (llvm::vfs::FileSystem &VFS)
static Distro::DistroType DetectLsbRelease (llvm::vfs::FileSystem &VFS)
static Distro::DistroType DetectDistro (llvm::vfs::FileSystem &VFS)
static Distro::DistroType GetDistro (llvm::vfs::FileSystem &VFS, const llvm::Triple &TargetOrHost)
Function Documentation
DetectDistro()
static Distro::DistroType DetectDistro (llvm::vfs::FileSystem & VFS) static
Definition at line 102 of file Distro.cpp.
References Data, clang::driver::Distro::DebianBookworm, clang::driver::Distro::DebianBullseye, clang::driver::Distro::DebianBuster, clang::driver::Distro::DebianJessie, clang::driver::Distro::DebianLenny, clang::driver::Distro::DebianSqueeze, clang::driver::Distro::DebianStretch, clang::driver::Distro::DebianTrixie, clang::driver::Distro::DebianWheezy, DetectLsbRelease(), DetectOsRelease(), clang::driver::Distro::Fedora, clang::File, clang::driver::Distro::Gentoo, clang::driver::Distro::OpenSUSE, clang::driver::Distro::RHEL5, clang::driver::Distro::RHEL6, clang::driver::Distro::RHEL7, and clang::driver::Distro::UnknownDistro.
Referenced by GetDistro().
DetectLsbRelease()
static Distro::DistroType DetectLsbRelease (llvm::vfs::FileSystem & VFS) static
Definition at line 51 of file Distro.cpp.
References clang::File, clang::driver::Distro::UbuntuArtful, clang::driver::Distro::UbuntuBionic, clang::driver::Distro::UbuntuCosmic, clang::driver::Distro::UbuntuDisco, clang::driver::Distro::UbuntuEoan, clang::driver::Distro::UbuntuFocal, clang::driver::Distro::UbuntuGroovy, clang::driver::Distro::UbuntuHardy, clang::driver::Distro::UbuntuHirsute, clang::driver::Distro::UbuntuImpish, clang::driver::Distro::UbuntuIntrepid, clang::driver::Distro::UbuntuJammy, clang::driver::Distro::UbuntuJaunty, clang::driver::Distro::UbuntuKarmic, clang::driver::Distro::UbuntuKinetic, clang::driver::Distro::UbuntuLucid, clang::driver::Distro::UbuntuLunar, clang::driver::Distro::UbuntuMantic, clang::driver::Distro::UbuntuMaverick, clang::driver::Distro::UbuntuNatty, clang::driver::Distro::UbuntuNoble, clang::driver::Distro::UbuntuOneiric, clang::driver::Distro::UbuntuPrecise, clang::driver::Distro::UbuntuQuantal, clang::driver::Distro::UbuntuRaring, clang::driver::Distro::UbuntuSaucy, clang::driver::Distro::UbuntuTrusty, clang::driver::Distro::UbuntuUtopic, clang::driver::Distro::UbuntuVivid, clang::driver::Distro::UbuntuWily, clang::driver::Distro::UbuntuXenial, clang::driver::Distro::UbuntuYakkety, clang::driver::Distro::UbuntuZesty, and clang::driver::Distro::UnknownDistro.
Referenced by DetectDistro().
DetectOsRelease()
static Distro::DistroType DetectOsRelease (llvm::vfs::FileSystem & VFS) static
Definition at line 23 of file Distro.cpp.
References clang::driver::Distro::AlpineLinux, clang::driver::Distro::ArchLinux, clang::driver::Distro::Exherbo, clang::driver::Distro::Fedora, clang::File, clang::driver::Distro::Gentoo, clang::driver::Distro::OpenSUSE, and clang::driver::Distro::UnknownDistro.
Referenced by DetectDistro().
GetDistro()
static Distro::DistroType GetDistro (llvm::vfs::FileSystem & VFS, const llvm::Triple & TargetOrHost) static
Definition at line 210 of file Distro.cpp.
References DetectDistro(), and clang::driver::Distro::UnknownDistro.