clang: lib/Driver/ToolChains/Arch/ARM.cpp File Reference
ARM.cpp File Reference
#include "ARM.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Option/ArgList.h"
#include "llvm/TargetParser/ARMTargetParser.h"
#include "llvm/TargetParser/Host.h"
Functions
static void getARMHWDivFeatures (const Driver &D, const Arg *A, const ArgList &Args, StringRef HWDiv, std::vector< StringRef > &Features)
static llvm::ARM::FPUKind getARMFPUFeatures (const Driver &D, const Arg *A, const ArgList &Args, StringRef FPU, std::vector< StringRef > &Features)
static bool DecodeARMFeatures (const Driver &D, StringRef text, StringRef CPU, llvm::ARM::ArchKind ArchKind, std::vector< StringRef > &Features, llvm::ARM::FPUKind &ArgFPUKind)
static void DecodeARMFeaturesFromCPU (const Driver &D, StringRef CPU, std::vector< StringRef > &Features)
static void checkARMArchName (const Driver &D, const Arg *A, const ArgList &Args, llvm::StringRef ArchName, llvm::StringRef CPUName, std::vector< StringRef > &Features, const llvm::Triple &Triple, llvm::ARM::FPUKind &ArgFPUKind)
static void checkARMCPUName (const Driver &D, const Arg *A, const ArgList &Args, llvm::StringRef CPUName, llvm::StringRef ArchName, std::vector< StringRef > &Features, const llvm::Triple &Triple, llvm::ARM::FPUKind &ArgFPUKind)
static void checkARMFloatABI (const Driver &D, const ArgList &Args, bool HasFPRegs)
static bool hasIntegerMVE (const std::vector< StringRef > &F)
Function Documentation
checkARMArchName()
static void checkARMArchName (const Driver & D, const Arg * A, const ArgList & Args, llvm::StringRef ArchName, llvm::StringRef CPUName, std::vector< StringRef > & Features, const llvm::Triple & Triple, llvm::ARM::FPUKind & ArgFPUKind) static
Definition at line 126 of file ARM.cpp.
References DecodeARMFeatures(), clang::driver::Driver::Diag(), clang::driver::tools::arm::getARMArch(), and clang::driver::tools::Split.
checkARMCPUName()
static void checkARMCPUName (const Driver & D, const Arg * A, const ArgList & Args, llvm::StringRef CPUName, llvm::StringRef ArchName, std::vector< StringRef > & Features, const llvm::Triple & Triple, llvm::ARM::FPUKind & ArgFPUKind) static
Definition at line 144 of file ARM.cpp.
References DecodeARMFeatures(), clang::driver::Driver::Diag(), clang::driver::tools::arm::getARMTargetCPU(), clang::driver::tools::arm::getLLVMArchKindForARM(), and clang::driver::tools::Split.
checkARMFloatABI()
static void checkARMFloatABI (const Driver & D, const ArgList & Args, bool HasFPRegs) static
Definition at line 163 of file ARM.cpp.
References clang::driver::Driver::Diag().
DecodeARMFeatures()
static bool DecodeARMFeatures (const Driver & D, StringRef text, StringRef CPU, llvm::ARM::ArchKind ArchKind, std::vector< StringRef > & Features, llvm::ARM::FPUKind & ArgFPUKind) static
Definition at line 99 of file ARM.cpp.
References clang::driver::tools::Split, and clang::comments::tok::text.
Referenced by checkARMArchName(), and checkARMCPUName().
DecodeARMFeaturesFromCPU()
static void DecodeARMFeaturesFromCPU (const Driver & D, StringRef CPU, std::vector< StringRef > & Features) static
Definition at line 113 of file ARM.cpp.
getARMFPUFeatures()
static llvm::ARM::FPUKind getARMFPUFeatures (const Driver & D, const Arg * A, const ArgList & Args, StringRef FPU, std::vector< StringRef > & Features) static
Definition at line 89 of file ARM.cpp.
References clang::driver::Driver::Diag().
getARMHWDivFeatures()
static void getARMHWDivFeatures (const Driver & D, const Arg * A, const ArgList & Args, StringRef HWDiv, std::vector< StringRef > & Features) static
Definition at line 80 of file ARM.cpp.
References clang::driver::Driver::Diag().
hasIntegerMVE()
static bool hasIntegerMVE (const std::vector< StringRef > & F) static
Definition at line 480 of file ARM.cpp.
References distance().