clang: lib/Driver/Driver.cpp File Reference
Driver.cpp File Reference
#include "clang/Driver/Driver.h"
#include "ToolChains/AIX.h"
#include "ToolChains/AMDGPU.h"
#include "ToolChains/AMDGPUOpenMP.h"
#include "ToolChains/AVR.h"
#include "ToolChains/Arch/RISCV.h"
#include "ToolChains/BareMetal.h"
#include "ToolChains/CSKYToolChain.h"
#include "ToolChains/Clang.h"
#include "ToolChains/CrossWindows.h"
#include "ToolChains/Cuda.h"
#include "ToolChains/Darwin.h"
#include "ToolChains/DragonFly.h"
#include "ToolChains/FreeBSD.h"
#include "ToolChains/Fuchsia.h"
#include "ToolChains/Gnu.h"
#include "ToolChains/HIPAMD.h"
#include "ToolChains/HIPSPV.h"
#include "ToolChains/HLSL.h"
#include "ToolChains/Haiku.h"
#include "ToolChains/Hexagon.h"
#include "ToolChains/Hurd.h"
#include "ToolChains/Lanai.h"
#include "ToolChains/Linux.h"
#include "ToolChains/MSP430.h"
#include "ToolChains/MSVC.h"
#include "ToolChains/MinGW.h"
#include "ToolChains/MipsLinux.h"
#include "ToolChains/NaCl.h"
#include "ToolChains/NetBSD.h"
#include "ToolChains/OHOS.h"
#include "ToolChains/OpenBSD.h"
#include "ToolChains/PPCFreeBSD.h"
#include "ToolChains/PPCLinux.h"
#include "ToolChains/PS4CPU.h"
#include "ToolChains/RISCVToolchain.h"
#include "ToolChains/SPIRV.h"
#include "ToolChains/SYCL.h"
#include "ToolChains/Solaris.h"
#include "ToolChains/TCE.h"
#include "ToolChains/VEToolchain.h"
#include "ToolChains/WebAssembly.h"
#include "ToolChains/XCore.h"
#include "ToolChains/ZOS.h"
#include "clang/Basic/DiagnosticDriver.h"
#include "clang/Basic/TargetID.h"
#include "clang/Basic/Version.h"
#include "clang/Config/config.h"
#include "clang/Driver/Action.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Job.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/Phases.h"
#include "clang/Driver/SanitizerArgs.h"
#include "clang/Driver/Tool.h"
#include "clang/Driver/ToolChain.h"
#include "clang/Driver/Types.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/OptSpecifier.h"
#include "llvm/Option/OptTable.h"
#include "llvm/Option/Option.h"
#include "llvm/SYCLLowerIR/DeviceConfigFile.hpp"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ExitCodes.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/LineIterator.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/RISCVISAInfo.h"
#include <cstdlib>
#include <map>
#include <memory>
#include <optional>
#include <regex>
#include <sstream>
#include <set>
#include <utility>
Enumerations
enum { TopLevelAction = 0 , HeadSibAction = 1 , OtherSibAction = 2 }
Functions
static std::optional< llvm::Triple > getOffloadTargetTriple (const Driver &D, const ArgList &Args)
static std::optional< llvm::Triple > getNVIDIAOffloadTargetTriple (const Driver &D, const ArgList &Args, const llvm::Triple &HostTriple)
static std::optional< llvm::Triple > getHIPOffloadTargetTriple (const Driver &D, const ArgList &Args)
static Arg * MakeInputArg (DerivedArgList &Args, const OptTable &Opts, StringRef Value, bool Claim=true)
static llvm::Triple computeTargetTriple (const Driver &D, StringRef TargetTriple, const ArgList &Args, StringRef DarwinArchName="")
Compute target triple from args.
static driver::LTOKind parseLTOMode (Driver &D, const llvm::opt::ArgList &Args, OptSpecifier OptEq, OptSpecifier OptNeg)
static bool isValidSYCLTriple (llvm::Triple T)
static const char * getDefaultSYCLArch (Compilation &C)
static bool addSYCLDefaultTriple (Compilation &C, SmallVectorImpl< llvm::Triple > &SYCLTriples)
static void appendOneArg (InputArgList &Args, const Arg *Opt, const Arg *BaseArg)
static void printArgList (raw_ostream &OS, const llvm::opt::ArgList &Args)
static void PrintDiagnosticCategories (raw_ostream &OS)
PrintDiagnosticCategories - Implement the –print-diagnostic-categories option.
static unsigned PrintActions1 (const Compilation &C, Action *A, std::map< Action *, unsigned > &Ids, Twine Indent={}, int Kind=TopLevelAction)
static bool ContainsCompileOrAssembleAction (const Action *A)
Check whether the given input tree contains any compilation or assembly actions.
static types::ID CXXHeaderUnitType (ModuleHeaderMode HM)
static bool runBundler (const SmallVectorImpl< StringRef > &InputArgs, Compilation &C)
static bool hasFPGABinary (Compilation &C, std::string Object, types::ID Type)
static SmallVector< std::string, 4 > getOffloadSections (Compilation &C, const StringRef &File)
static bool hasSYCLDefaultSection (Compilation &C, const StringRef &File)
static bool hasOffloadSections (Compilation &C, const StringRef &File, DerivedArgList &Args)
static bool optionMatches (const std::string &Option, const std::string &OptCheck)
static SmallVector< const char *, 16 > getLinkerArgs (Compilation &C, DerivedArgList &Args, bool IncludeObj=false)
static bool IsSYCLDeviceLibObj (std::string ObjFilePath, bool isMSVCEnv)
static bool ContainsOffloadDepsAction (const Action *A)
Check whether the given input tree contains any clang-offload-dependency actions.
static StringRef getCanonicalArchString (Compilation &C, const llvm::opt::DerivedArgList &Args, StringRef ArchStr, const llvm::Triple &Triple, bool SuppressError=false)
Returns the canonical name for the offloading architecture when using a HIP or CUDA architecture.
static std::optional< std::pair< llvm::StringRef, llvm::StringRef > > getConflictOffloadArchCombination (const llvm::DenseSet< StringRef > &Archs, llvm::Triple Triple)
Checks if the set offloading architectures does not conflict.
static std::string GetTriplePlusArchString (const ToolChain *TC, StringRef BoundArch, Action::OffloadKind OffloadKind)
Return a string that uniquely identifies the result of a job.
static void CollectForEachInputs (InputInfoList &InputInfos, const Action *SourceAction, const ToolChain *TC, StringRef BoundArch, Action::OffloadKind TargetDeviceOffloadKind, const std::map< std::pair< const Action *, std::string >, InputInfoList > &CachedResults, const ForEachWrappingAction *FEA)
static void handleTimeTrace (Compilation &C, const ArgList &Args, const JobAction *JA, const char *BaseInput, const InputInfo &Result)
static const char * MakeCLOutputFilename (const ArgList &Args, StringRef ArgValue, StringRef BaseName, types::ID FileType)
Create output filename based on ArgValue, which could either be a full filename, filename without extension, or a directory.
static bool HasPreprocessOutput (const Action &JA)
static const char * GetModuleOutputPath (Compilation &C, const JobAction &JA, const char *BaseInput)
static bool ScanDirForExecutable (SmallString< 128 > &Dir, StringRef Name)
static const char * GetStableCStr (llvm::StringSet<> &SavedStrings, StringRef S)
static void applyOneOverrideOption (raw_ostream &OS, SmallVectorImpl< const char * > &Args, StringRef Edit, llvm::StringSet<> &SavedStrings)
Apply a list of edits to the input argument lists.
Variables
static const char BugReporMsg []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TopLevelAction
HeadSibAction
OtherSibAction
Definition at line 2802 of file Driver.cpp.
Function Documentation
addSYCLDefaultTriple()
static bool addSYCLDefaultTriple (Compilation & C, SmallVectorImpl< llvm::Triple > & SYCLTriples) static
Returns true if a triple is added to SYCLTriples, false otherwise
Definition at line 828 of file Driver.cpp.
References getDefaultSYCLArch().
Referenced by clang::driver::Driver::CreateOffloadingDeviceToolChains().
appendOneArg()
static void appendOneArg (InputArgList & Args, const Arg * Opt, const Arg * BaseArg) static
Definition at line 1331 of file Driver.cpp.
Referenced by clang::driver::Driver::BuildCompilation().
applyOneOverrideOption()
static void applyOneOverrideOption (raw_ostream & OS, SmallVectorImpl< const char * > & Args, StringRef Edit, llvm::StringSet<> & SavedStrings) static
Apply a list of edits to the input argument lists.
The input string is a space separated list of edits to perform, they are applied in order to the input argument lists. Edits should be one of the following forms:
'#': Silence information about the changes to the command line arguments.
'^': Add FOO as a new argument at the beginning of the command line.
'+': Add FOO as a new argument at the end of the command line.
's/XXX/YYY/': Substitute the regular expression XXX with YYY in the command line.
'xOPTION': Removes all instances of the literal argument OPTION.
'XOPTION': Removes all instances of the literal argument OPTION, and the following argument.
'Ox': Removes all flags matching 'O' or 'O[sz0-9]' and adds 'Ox' at the end of the command line.
Parameters
OS - The stream to write edit information to.
Args - The vector of command line arguments.
Edit - The override command to perform.
SavedStrings - Set to use for storing string representations.
Definition at line 10538 of file Driver.cpp.
References GetStableCStr().
CollectForEachInputs()
static void CollectForEachInputs (InputInfoList & InputInfos, const Action * SourceAction, const ToolChain * TC, StringRef BoundArch, Action::OffloadKind TargetDeviceOffloadKind, const std::map< std::pair< const Action *, std::string >, InputInfoList > & CachedResults, const ForEachWrappingAction * FEA) static
Definition at line 8691 of file Driver.cpp.
References clang::driver::Action::getInputs(), clang::driver::ForEachWrappingAction::getSerialActions(), and GetTriplePlusArchString().
computeTargetTriple()
static llvm::Triple computeTargetTriple (const Driver & D, StringRef TargetTriple, const ArgList & Args, StringRef DarwinArchName = "") static
Compute target triple from args.
This routine provides the logic to compute a target triple from various args passed to the driver and the default triple string.
Definition at line 550 of file Driver.cpp.
References clang::driver::Driver::Diag(), clang::driver::toolchains::MinGW::fixTripleArch(), clang::driver::tools::riscv::getRISCVArch(), normalize(), clang::driver::tools::darwin::setTripleTypeForMachOArchName(), and clang::T.
ContainsCompileOrAssembleAction()
static bool ContainsCompileOrAssembleAction (const Action * A) static
Check whether the given input tree contains any compilation or assembly actions.
Definition at line 2906 of file Driver.cpp.
References clang::driver::Action::inputs().
Referenced by clang::driver::Driver::BuildUniversalActions().
ContainsOffloadDepsAction()
static bool ContainsOffloadDepsAction (const Action * A) static
Check whether the given input tree contains any clang-offload-dependency actions.
Definition at line 3754 of file Driver.cpp.
References clang::driver::Action::inputs().
CXXHeaderUnitType()
static types::ID CXXHeaderUnitType (ModuleHeaderMode HM) static
Definition at line 3078 of file Driver.cpp.
References clang::driver::HeaderMode_Default, clang::driver::HeaderMode_None, clang::driver::HeaderMode_System, and clang::driver::HeaderMode_User.
Referenced by clang::driver::Driver::BuildInputs().
getCanonicalArchString()
static StringRef getCanonicalArchString (Compilation & C, const llvm::opt::DerivedArgList & Args, StringRef ArchStr, const llvm::Triple & Triple, bool SuppressError = false) static
Returns the canonical name for the offloading architecture when using a HIP or CUDA architecture.
Definition at line 7664 of file Driver.cpp.
References clang::CudaArchToString(), clang::getCanonicalTargetID(), getHIPOffloadTargetTriple(), clang::getProcessorFromTargetID(), clang::IsAMDGpuArch(), clang::IsNVIDIAGpuArch(), clang::parseTargetID(), clang::StringToCudaArch(), and clang::UNKNOWN.
getConflictOffloadArchCombination()
static std::optional<std::pair<llvm::StringRef, llvm::StringRef> > getConflictOffloadArchCombination (const llvm::DenseSet< StringRef > & Archs, llvm::Triple Triple) static
Checks if the set offloading architectures does not conflict.
Returns the incompatible pair if a conflict occurs.
Definition at line 7708 of file Driver.cpp.
References clang::getConflictTargetIDCombination().
getDefaultSYCLArch()
static const char* getDefaultSYCLArch (Compilation & C) static
Definition at line 822 of file Driver.cpp.
Referenced by addSYCLDefaultTriple(), clang::driver::Driver::CreateOffloadingDeviceToolChains(), and hasSYCLDefaultSection().
getHIPOffloadTargetTriple()
static std::optional<llvm::Triple> getHIPOffloadTargetTriple (const Driver & D, const ArgList & Args) static
Definition at line 155 of file Driver.cpp.
References clang::driver::Driver::Diag(), and getOffloadTargetTriple().
Referenced by clang::driver::Driver::CreateOffloadingDeviceToolChains(), and getCanonicalArchString().
getLinkerArgs()
static SmallVector<const char *, 16> getLinkerArgs (Compilation & C, DerivedArgList & Args, bool IncludeObj = false) static
Definition at line 3517 of file Driver.cpp.
References clang::FileName, clang::driver::Action::getKind(), clang::driver::isObjectFile(), IsStatic, clang::driver::isStaticArchiveFile(), optionMatches(), and V.
GetModuleOutputPath()
static const char* GetModuleOutputPath (Compilation & C, const JobAction & JA, const char * BaseInput) static
Definition at line 9362 of file Driver.cpp.
References clang::driver::tools::getCXX20NamedModuleOutputPath(), and clang::driver::Action::getType().
Referenced by clang::driver::Driver::GetNamedOutputPath().
getNVIDIAOffloadTargetTriple()
static std::optional<llvm::Triple> getNVIDIAOffloadTargetTriple (const Driver & D, const ArgList & Args, const llvm::Triple & HostTriple) static
Definition at line 137 of file Driver.cpp.
References clang::driver::Driver::Diag(), and getOffloadTargetTriple().
Referenced by clang::driver::Driver::CreateOffloadingDeviceToolChains().
getOffloadSections()
static SmallVector<std::string, 4> getOffloadSections (Compilation & C, const StringRef & File) static
Definition at line 3414 of file Driver.cpp.
References clang::File, clang::driver::isObjectFile(), and clang::driver::isStaticArchiveFile().
Referenced by hasOffloadSections().
getOffloadTargetTriple()
static std::optional<llvm::Triple> getOffloadTargetTriple (const Driver & D, const ArgList & Args) static
Definition at line 117 of file Driver.cpp.
References clang::driver::Driver::Diag().
Referenced by getHIPOffloadTargetTriple(), and getNVIDIAOffloadTargetTriple().
GetStableCStr()
static const char* GetStableCStr (llvm::StringSet<> & SavedStrings, StringRef S) static
Definition at line 10507 of file Driver.cpp.
Referenced by applyOneOverrideOption().
GetTriplePlusArchString()
static std::string GetTriplePlusArchString (const ToolChain * TC, StringRef BoundArch, Action::OffloadKind OffloadKind) static
Return a string that uniquely identifies the result of a job.
The bound arch is not necessarily represented in the toolchain's triple – for example, armv7 and armv7s both map to the same triple – so we need both in our map. Also, we need to add the offloading device kind, as the same tool chain can be used for host and device for some programming models, e.g. OpenMP.
Definition at line 8678 of file Driver.cpp.
References clang::driver::Action::GetOffloadKindName(), and clang::driver::ToolChain::getTriple().
Referenced by clang::driver::Driver::BuildJobsForAction(), and CollectForEachInputs().
handleTimeTrace()
static void handleTimeTrace (Compilation & C, const ArgList & Args, const JobAction * JA, const char * BaseInput, const InputInfo & Result) static
Definition at line 8733 of file Driver.cpp.
hasFPGABinary()
static bool hasFPGABinary (Compilation & C, std::string Object, types::ID Type) static
Definition at line 3386 of file Driver.cpp.
References clang::driver::types::getTypeName(), clang::driver::types::isFPGA(), clang::driver::isStaticArchiveFile(), and runBundler().
hasOffloadSections()
static bool hasOffloadSections (Compilation & C, const StringRef & File, DerivedArgList & Args) static
Definition at line 3500 of file Driver.cpp.
References clang::File, and getOffloadSections().
HasPreprocessOutput()
static bool HasPreprocessOutput (const Action & JA) static
Definition at line 9300 of file Driver.cpp.
References clang::driver::Action::getInputs().
Referenced by clang::driver::Driver::GetNamedOutputPath().
hasSYCLDefaultSection()
static bool hasSYCLDefaultSection (Compilation & C, const StringRef & File) static
Definition at line 3480 of file Driver.cpp.
References clang::File, getDefaultSYCLArch(), clang::driver::isObjectFile(), clang::driver::isStaticArchiveFile(), and runBundler().
IsSYCLDeviceLibObj()
static bool IsSYCLDeviceLibObj (std::string ObjFilePath, bool isMSVCEnv) static
Definition at line 3683 of file Driver.cpp.
References clang::interp::Ret().
isValidSYCLTriple()
static bool isValidSYCLTriple (llvm::Triple T) static
Definition at line 800 of file Driver.cpp.
References clang::T.
Referenced by clang::driver::Driver::CreateOffloadingDeviceToolChains().
MakeCLOutputFilename()
static const char* MakeCLOutputFilename (const ArgList & Args, StringRef ArgValue, StringRef BaseName, types::ID FileType) static
Create output filename based on ArgValue, which could either be a full filename, filename without extension, or a directory.
If ArgValue does not provide a filename, then use BaseName, and use the extension suitable for FileType.
Definition at line 9271 of file Driver.cpp.
References Filename, and clang::driver::types::getTypeTempSuffix().
Referenced by clang::driver::Driver::GetNamedOutputPath().
MakeInputArg()
static Arg* MakeInputArg (DerivedArgList & Args, const OptTable & Opts, StringRef Value, bool Claim = true) static
Definition at line 410 of file Driver.cpp.
Referenced by clang::driver::Driver::BuildInputs().
optionMatches()
static bool optionMatches (const std::string & Option, const std::string & OptCheck) static
Definition at line 3508 of file Driver.cpp.
Referenced by getLinkerArgs().
parseLTOMode()
static driver::LTOKind parseLTOMode (Driver & D, const llvm::opt::ArgList & Args, OptSpecifier OptEq, OptSpecifier OptNeg) static
Definition at line 733 of file Driver.cpp.
References clang::driver::Driver::Diag(), clang::driver::LTOK_Full, clang::driver::LTOK_None, clang::driver::LTOK_Thin, and clang::driver::LTOK_Unknown.
PrintActions1()
static unsigned PrintActions1 (const Compilation & C, Action * A, std::map< Action *, unsigned > & Ids, Twine Indent = {}, int Kind = TopLevelAction) static
Definition at line 2811 of file Driver.cpp.
Referenced by clang::driver::Driver::PrintActions().
printArgList()
static void printArgList (raw_ostream & OS, const llvm::opt::ArgList & Args) static
Definition at line 1938 of file Driver.cpp.
Referenced by clang::driver::Driver::generateCompilationDiagnostics().
PrintDiagnosticCategories()
static void PrintDiagnosticCategories (raw_ostream & OS) static
PrintDiagnosticCategories - Implement the –print-diagnostic-categories option.
Definition at line 2500 of file Driver.cpp.
References clang::DiagnosticIDs::getCategoryNameFromID(), clang::DiagnosticIDs::getNumberOfCategories(), and max().
Referenced by clang::driver::Driver::HandleImmediateArgs().
runBundler()
static bool runBundler (const SmallVectorImpl< StringRef > & InputArgs, Compilation & C) static
Definition at line 3359 of file Driver.cpp.
Referenced by hasFPGABinary(), and hasSYCLDefaultSection().
ScanDirForExecutable()
static bool ScanDirForExecutable (SmallString< 128 > & Dir, StringRef Name) static
Definition at line 9761 of file Driver.cpp.
References clang::driver::Driver::Dir, and clang::driver::Driver::Name.
Referenced by clang::driver::Driver::GetProgramPath().
Variable Documentation
BugReporMsg
const char BugReporMsg[] static
Initial value:
=
    "\n********************\n\n"
    "PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:\n"
    "Preprocessed source(s) and associated run script(s) are located at:"
Definition at line 2046 of file Driver.cpp.
Referenced by clang::driver::Driver::generateCompilationDiagnostics().