clang: lib/Driver/ToolChains/MSP430.cpp File Reference
MSP430.cpp File Reference
#include "MSP430.h"
#include "CommonArgs.h"
#include "Gnu.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Multilib.h"
#include "clang/Driver/Options.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "clang/Basic/MSP430Target.def"
Macros
#define MSP430_MCU(NAME) .Case(NAME, true)
#define MSP430_MCU_FEAT(NAME, HWMULT) .Case(NAME, HWMULT)
Functions
static bool isSupportedMCU (const StringRef MCU)
static StringRef getSupportedHWMult (const Arg *MCU)
static StringRef getHWMultLib (const ArgList &Args)
static void AddSspArgs (const ArgList &Args, ArgStringList &CmdArgs)
static void AddImplicitLinkerScript (const std::string SysRoot, const ArgList &Args, ArgStringList &CmdArgs)
Macro Definition Documentation
MSP430_MCU
#define MSP430_MCU (NAME) .Case(NAME, true)
MSP430_MCU_FEAT
#define MSP430_MCU_FEAT (NAME, HWMULT) .Case(NAME, HWMULT)
Function Documentation
AddImplicitLinkerScript()
static void AddImplicitLinkerScript (const std::string SysRoot, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 240 of file MSP430.cpp.
Referenced by clang::driver::tools::msp430::Linker::ConstructJob().
AddSspArgs()
static void AddSspArgs (const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 228 of file MSP430.cpp.
Referenced by clang::driver::tools::msp430::Linker::ConstructJob().
getHWMultLib()
static StringRef getHWMultLib (const ArgList & Args) static
Definition at line 43 of file MSP430.cpp.
References getSupportedHWMult().
getSupportedHWMult()
static StringRef getSupportedHWMult (const Arg * MCU) static
Definition at line 33 of file MSP430.cpp.
Referenced by getHWMultLib().
isSupportedMCU()
static bool isSupportedMCU (const StringRef MCU) static
Definition at line 26 of file MSP430.cpp.