clang: lib/StaticAnalyzer/Core/DynamicType.cpp File Reference
DynamicType.cpp File Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicType.h"
#include "clang/Basic/JsonSupport.h"
#include "clang/Basic/LLVM.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Functions
REGISTER_MAP_WITH_PROGRAMSTATE (DynamicTypeMap, const clang::ento::MemRegion *, clang::ento::DynamicTypeInfo) REGISTER_MAP_WITH_PROGRAMSTATE(DynamicCastMap
The GDM component containing the dynamic type info.
const clang::ento::MemRegion CastSet REGISTER_MAP_WITH_PROGRAMSTATE (DynamicClassObjectMap, clang::ento::SymbolRef, clang::ento::DynamicTypeInfo) namespace clang
Function Documentation
REGISTER_MAP_WITH_PROGRAMSTATE() [1/2]
const clang::ento::MemRegion CastSet REGISTER_MAP_WITH_PROGRAMSTATE (DynamicClassObjectMap , clang::ento::SymbolRef , clang::ento::DynamicTypeInfo)
Definition at line 38 of file DynamicType.cpp.
References clang::interp::Cast(), clang::ento::getClassObjectDynamicTypeInfo(), clang::ento::getDynamicCastInfo(), clang::ento::getDynamicTypeInfo(), clang::ento::getRawDynamicTypeInfo(), clang::ento::removeDeadCasts(), clang::ento::removeDeadClassObjectTypes(), clang::ento::removeDeadTypes(), clang::ento::setClassObjectDynamicTypeInfo(), clang::ento::setDynamicTypeAndCastInfo(), clang::ento::setDynamicTypeInfo(), and State.
REGISTER_MAP_WITH_PROGRAMSTATE() [2/2]
REGISTER_MAP_WITH_PROGRAMSTATE (DynamicTypeMap , const clang::ento::MemRegion * , clang::ento::DynamicTypeInfo)
The GDM component containing the dynamic type info.
This is a map from a symbol to its most likely type. A set factory of dynamic cast informations. A map from symbols to cast informations.