clang: lib/StaticAnalyzer/Core/DynamicExtent.cpp File Reference
DynamicExtent.cpp File Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicExtent.h"
#include "clang/AST/Expr.h"
#include "clang/Basic/LLVM.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
Functions
REGISTER_MAP_WITH_PROGRAMSTATE (DynamicExtentMap, const clang::ento::MemRegion *, clang::ento::DefinedOrUnknownSVal) namespace clang
Function Documentation
REGISTER_MAP_WITH_PROGRAMSTATE()
REGISTER_MAP_WITH_PROGRAMSTATE (DynamicExtentMap , const clang::ento::MemRegion * , clang::ento::DefinedOrUnknownSVal)
Definition at line 22 of file DynamicExtent.cpp.
References clang::ento::SVal::getAs(), clang::ento::SVal::getAsRegion(), clang::ento::getDynamicElementCount(), clang::ento::getDynamicElementCountWithOffset(), clang::ento::getDynamicExtent(), clang::ento::getDynamicExtentWithOffset(), clang::ento::getElementExtent(), Offset, clang::ento::setDynamicExtent(), and State.