clang: lib/StaticAnalyzer/Core/ExplodedGraph.cpp File Reference
ExplodedGraph.cpp File Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/ExplodedGraph.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/ParentMap.h"
#include "clang/AST/Stmt.h"
#include "clang/Analysis/CFGStmtMap.h"
#include "clang/Analysis/ProgramPoint.h"
#include "clang/Analysis/Support/BumpVector.h"
#include "clang/Basic/LLVM.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState_Fwd.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Casting.h"
#include <cassert>
#include <memory>
Typedefs
using ExplodedNodeVector = BumpVector< ExplodedNode * >
using GroupStorage = llvm::PointerUnion< ExplodedNode *, ExplodedNodeVector * >
Functions
static const LocationContext * findTopAutosynthesizedParentContext (const LocationContext *LC)
Typedef Documentation
ExplodedNodeVector
using ExplodedNodeVector = BumpVector<ExplodedNode *>
Definition at line 201 of file ExplodedGraph.cpp.
GroupStorage
using GroupStorage = llvm::PointerUnion<ExplodedNode *, ExplodedNodeVector *>
Definition at line 202 of file ExplodedGraph.cpp.
Function Documentation
findTopAutosynthesizedParentContext()
static const LocationContext* findTopAutosynthesizedParentContext (const LocationContext * LC) static
Definition at line 308 of file ExplodedGraph.cpp.
References clang::LocationContext::getAnalysisDeclContext(), clang::LocationContext::getParent(), and clang::AnalysisDeclContext::isBodyAutosynthesized().
Referenced by clang::ento::ExplodedNode::getStmtForDiagnostics().