clang: lib/StaticAnalyzer/Core/ExprEngineCXX.cpp File Reference
ExprEngineCXX.cpp File Reference
#include "clang/AST/DeclCXX.h"
#include "clang/AST/ParentMap.h"
#include "clang/AST/StmtCXX.h"
#include "clang/Analysis/ConstructionContext.h"
#include "clang/Basic/PrettyStackTrace.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SVals.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include <optional>
Functions
static ProgramStateRef bindRequiredArrayElementToEnvironment (ProgramStateRef State, const ArrayInitLoopExpr *AILE, const LocationContext *LCtx, SVal Idx)
Function Documentation
bindRequiredArrayElementToEnvironment()
static ProgramStateRef bindRequiredArrayElementToEnvironment (ProgramStateRef State, const ArrayInitLoopExpr * AILE, const LocationContext * LCtx, SVal Idx) static
Definition at line 514 of file ExprEngineCXX.cpp.
References clang::extractElementInitializerFromNestedAILE(), clang::ArrayInitLoopExpr::getCommonExpr(), clang::OpaqueValueExpr::getSourceExpr(), and State.