clang: lib/StaticAnalyzer/Core/ExprEngineC.cpp File Reference
ExprEngineC.cpp File Reference
#include "clang/AST/DeclCXX.h"
#include "clang/AST/ExprCXX.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include <optional>
Functions
static SVal conjureOffsetSymbolOnLocation (SVal Symbol, SVal Other, Expr *Expression, SValBuilder &svalBuilder, unsigned Count, const LocationContext *LCtx)
Optionally conjure and return a symbol for offset when processing an expression Expression.
Function Documentation
conjureOffsetSymbolOnLocation()
static SVal conjureOffsetSymbolOnLocation (SVal Symbol, SVal Other, Expr * Expression, SValBuilder & svalBuilder, unsigned Count, const LocationContext * LCtx) static
Optionally conjure and return a symbol for offset when processing an expression Expression.
If Other is a location, conjure a symbol for Symbol (offset) if it is unknown so that memory arithmetic always results in an ElementRegion. Count The number of times the current basic block was visited.
Definition at line 29 of file ExprEngineC.cpp.
References clang::ento::SValBuilder::conjureSymbolVal(), clang::Type::isIntegralOrEnumerationType(), clang::ento::SVal::isUnknown(), and clang::Other.
Referenced by clang::ento::ExprEngine::VisitBinaryOperator().