clang: lib/AST/Expr.cpp File Reference
Expr.cpp File Reference
#include "clang/AST/Expr.h"
#include "clang/AST/APValue.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/ComputeDependence.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DependenceFlags.h"
#include "clang/AST/EvaluatedExprVisitor.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/IgnoreExpr.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Lexer.h"
#include "clang/Lex/LiteralSupport.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstring>
#include "clang/AST/StmtNodes.inc"
#include "clang/AST/OperationKinds.def"
Macros
#define ABSTRACT_STMT(type)
#define STMT(type, base) case Stmt::type##Class: break;
#define EXPR(type, base) case Stmt::type##Class: return getExprLocImpl<type>(this, &type::getExprLoc);
#define UNARY_OPERATION(Name, Spelling) case UO_##Name: return Spelling;
#define CAST_OPERATION(Name) case CK_##Name: return #Name;
#define ABSTRACT_STMT(x)
#define CASTEXPR(Type, Base)
#define STMT(Type, Base)
#define BINARY_OPERATION(Name, Spelling) case BO_##Name: return Spelling;
#define ABSTRACT_STMT(Type)
#define STMT(Type, Base) case Type##Class:
#define EXPR(Type, Base)
Functions
static void AssertResultStorageKind (ConstantExpr::ResultStorageKind Kind)
static llvm::Optional< unsigned > UniqueStableNameDiscriminator (ASTContext &, const NamedDecl *ND)
static QualType getDecayedSourceLocExprType (const ASTContext &Ctx, SourceLocExpr::IdentKind Kind)
static const Expr * skipTemporaryBindingsNoOpCastsAndParens (const Expr *E)
Skip over any no-op casts and any temporary-binding expressions.
Macro Definition Documentation
ABSTRACT_STMT [1/3]
#define ABSTRACT_STMT (type)
ABSTRACT_STMT [2/3]
#define ABSTRACT_STMT (Type)
ABSTRACT_STMT [3/3]
#define ABSTRACT_STMT (x)
BINARY_OPERATION
#define BINARY_OPERATION (Name, Spelling) case BO_##Name: return Spelling;
CAST_OPERATION
#define CAST_OPERATION (Name) case CK_##Name: return #Name;
CASTEXPR
#define CASTEXPR (Type, Base)
Value:
  case Stmt::Type##Class:                                                      \
    return static_cast<Type *>(this)->getTrailingObjects<CXXBaseSpecifier *>();
EXPR [1/2]
#define EXPR (type, base) case Stmt::type##Class: return getExprLocImpl<type>(this, &type::getExprLoc);
EXPR [2/2]
#define EXPR (Type, Base)
STMT [1/3]
#define STMT (type, base) case Stmt::type##Class: break;
STMT [2/3]
#define STMT (Type, Base)
STMT [3/3]
#define STMT (Type, Base) case Type##Class:
UNARY_OPERATION
#define UNARY_OPERATION (Name, Spelling) case UO_##Name: return Spelling;
Function Documentation
AssertResultStorageKind()
static void AssertResultStorageKind (ConstantExpr::ResultStorageKind Kind) static
Definition at line 263 of file Expr.cpp.
References clang::ConstantExpr::RSK_APValue, clang::ConstantExpr::RSK_Int64, and clang::ConstantExpr::RSK_None.
Referenced by clang::ConstantExpr::Create(), and clang::ConstantExpr::CreateEmpty().
getDecayedSourceLocExprType()
static QualType getDecayedSourceLocExprType (const ASTContext & Ctx, SourceLocExpr::IdentKind Kind) static
Definition at line 2193 of file Expr.cpp.
References clang::ASTContext::CharTy, clang::SourceLocExpr::Column, clang::SourceLocExpr::File, clang::SourceLocExpr::Function, clang::Type::getAsArrayTypeUnsafe(), clang::ArrayType::getElementType(), clang::ASTContext::getPointerType(), clang::ASTContext::getStringLiteralArrayType(), clang::SourceLocExpr::Line, and clang::ASTContext::UnsignedIntTy.
skipTemporaryBindingsNoOpCastsAndParens()
static const Expr* skipTemporaryBindingsNoOpCastsAndParens (const Expr * E) static
Skip over any no-op casts and any temporary-binding expressions.
Definition at line 3056 of file Expr.cpp.
References clang::Expr::IgnoreParens().
Referenced by clang::Expr::isTemporaryObject().
UniqueStableNameDiscriminator()
static llvm::Optional<unsigned> UniqueStableNameDiscriminator (ASTContext & , const NamedDecl * ND) static
Definition at line 562 of file Expr.cpp.
Referenced by clang::SYCLUniqueStableNameExpr::ComputeName(), and clang::SYCLUniqueStableIdExpr::ComputeName().