clang: lib/StaticAnalyzer/Checkers/ExprInspectionChecker.cpp File Reference
ExprInspectionChecker.cpp File Reference
#include "clang/Analysis/IssueHash.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Checkers/SValExplainer.h"
#include "clang/StaticAnalyzer/Checkers/Taint.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicExtent.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/ScopedPrinter.h"
#include <optional>
Functions
static const char * getArgumentValueString (const CallExpr *CE, CheckerContext &C)
static void printHelper (llvm::raw_svector_ostream &Out, CheckerContext &C, const llvm::APSInt &I)
static void printHelper (llvm::raw_svector_ostream &Out, CheckerContext &C, SymbolRef Sym)
static void printHelper (llvm::raw_svector_ostream &Out, CheckerContext &C, SVal V)
Function Documentation
getArgumentValueString()
static const char* getArgumentValueString (const CallExpr * CE, CheckerContext & C) static
Definition at line 133 of file ExprInspectionChecker.cpp.
References clang::ento::SVal::castAs(), clang::CallExpr::getArg(), clang::ento::ExplodedNode::getLocationContext(), clang::CallExpr::getNumArgs(), clang::ento::ExplodedNode::getState(), clang::ento::SVal::isUndef(), and State.
printHelper() [1/3]
static void printHelper (llvm::raw_svector_ostream & Out, CheckerContext & C, const llvm::APSInt & I) static
Definition at line 263 of file ExprInspectionChecker.cpp.
printHelper() [2/3]
static void printHelper (llvm::raw_svector_ostream & Out, CheckerContext & C, SVal V) static
Definition at line 274 of file ExprInspectionChecker.cpp.
References V.
printHelper() [3/3]
static void printHelper (llvm::raw_svector_ostream & Out, CheckerContext & C, SymbolRef Sym) static
Definition at line 269 of file ExprInspectionChecker.cpp.