clang: lib/Driver/ToolChains/Gnu.cpp File Reference
Gnu.cpp File Reference
#include "Gnu.h"
#include "Arch/ARM.h"
#include "Arch/CSKY.h"
#include "Arch/LoongArch.h"
#include "Arch/Mips.h"
#include "Arch/PPC.h"
#include "Arch/RISCV.h"
#include "Arch/Sparc.h"
#include "Arch/SystemZ.h"
#include "CommonArgs.h"
#include "Linux.h"
#include "clang/Config/config.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/MultilibBuilder.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/Tool.h"
#include "clang/Driver/ToolChain.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/TargetParser/RISCVISAInfo.h"
#include "llvm/TargetParser/TargetParser.h"
#include <system_error>
Functions
static bool forwardToGCC (const Option &O)
static void normalizeCPUNamesForAssembler (const ArgList &Args, ArgStringList &CmdArgs)
static const char * getLDMOption (const llvm::Triple &T, const ArgList &Args)
static bool getStaticPIE (const ArgList &Args, const ToolChain &TC)
static bool getStatic (const ArgList &Args)
static bool isSoftFloatABI (const ArgList &Args)
static bool isArmOrThumbArch (llvm::Triple::ArchType Arch)
static bool isMipsEL (llvm::Triple::ArchType Arch)
static bool isMips16 (const ArgList &Args)
static bool isMicroMips (const ArgList &Args)
static bool isMSP430 (llvm::Triple::ArchType Arch)
static bool findMipsCsMultilibs (const Multilib::flags_list &Flags, FilterNonExistent &NonExistent, DetectedMultilibs &Result)
static bool findMipsAndroidMultilibs (llvm::vfs::FileSystem &VFS, StringRef Path, const Multilib::flags_list &Flags, FilterNonExistent &NonExistent, DetectedMultilibs &Result)
static bool findMipsMuslMultilibs (const Multilib::flags_list &Flags, FilterNonExistent &NonExistent, DetectedMultilibs &Result)
static bool findMipsMtiMultilibs (const Multilib::flags_list &Flags, FilterNonExistent &NonExistent, DetectedMultilibs &Result)
static bool findMipsImgMultilibs (const Multilib::flags_list &Flags, FilterNonExistent &NonExistent, DetectedMultilibs &Result)
static void findAndroidArmMultilibs (const Driver &D, const llvm::Triple &TargetTriple, StringRef Path, const ArgList &Args, DetectedMultilibs &Result)
static bool findMSP430Multilibs (const Driver &D, const llvm::Triple &TargetTriple, StringRef Path, const ArgList &Args, DetectedMultilibs &Result)
static void findCSKYMultilibs (const Driver &D, const llvm::Triple &TargetTriple, StringRef Path, const ArgList &Args, DetectedMultilibs &Result)
static bool selectRISCVMultilib (const MultilibSet &RISCVMultilibSet, StringRef Arch, const Multilib::flags_list &Flags, llvm::SmallVectorImpl< Multilib > &SelectedMultilibs)
Extend the multi-lib re-use selection mechanism for RISC-V.
static void findRISCVBareMetalMultilibs (const Driver &D, const llvm::Triple &TargetTriple, StringRef Path, const ArgList &Args, DetectedMultilibs &Result)
static void findRISCVMultilibs (const Driver &D, const llvm::Triple &TargetTriple, StringRef Path, const ArgList &Args, DetectedMultilibs &Result)
static bool findBiarchMultilibs (const Driver &D, const llvm::Triple &TargetTriple, StringRef Path, const ArgList &Args, bool NeedsBiarchSuffix, DetectedMultilibs &Result)
static llvm::StringRef getGCCToolchainDir (const ArgList &Args, llvm::StringRef SysRoot)
Function Documentation
findAndroidArmMultilibs()
static void findAndroidArmMultilibs (const Driver & D, const llvm::Triple & TargetTriple, StringRef Path, const ArgList & Args, DetectedMultilibs & Result) static
Definition at line 1731 of file Gnu.cpp.
References clang::driver::tools::addMultilibFlag(), clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibSet::FilterOut(), clang::driver::MultilibBuilder::flag(), clang::driver::Driver::getVFS(), clang::driver::MultilibSetBuilder::makeMultilibSet(), and clang::driver::MultilibSet::select().
findBiarchMultilibs()
static bool findBiarchMultilibs (const Driver & D, const llvm::Triple & TargetTriple, StringRef Path, const ArgList & Args, bool NeedsBiarchSuffix, DetectedMultilibs & Result) static
Definition at line 2084 of file Gnu.cpp.
References clang::driver::tools::addMultilibFlag(), clang::Default, clang::driver::MultilibBuilder::flag(), clang::driver::MultilibBuilder::gccSuffix(), clang::driver::Driver::getVFS(), clang::driver::MultilibBuilder::makeMultilib(), and clang::UNKNOWN.
findCSKYMultilibs()
static void findCSKYMultilibs (const Driver & D, const llvm::Triple & TargetTriple, StringRef Path, const ArgList & Args, DetectedMultilibs & Result) static
Definition at line 1802 of file Gnu.cpp.
References clang::driver::tools::addMultilibFlag(), clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibSet::FilterOut(), clang::driver::MultilibBuilder::flag(), clang::driver::tools::csky::getCSKYArchName(), clang::driver::tools::csky::getCSKYFloatABI(), clang::driver::Driver::getVFS(), clang::driver::tools::csky::Hard, clang::driver::MultilibSetBuilder::makeMultilibSet(), clang::driver::MultilibSetBuilder::Maybe(), clang::driver::MultilibSet::select(), clang::driver::tools::csky::Soft, and clang::driver::tools::csky::SoftFP.
findMipsAndroidMultilibs()
static bool findMipsAndroidMultilibs (llvm::vfs::FileSystem & VFS, StringRef Path, const Multilib::flags_list & Flags, FilterNonExistent & NonExistent, DetectedMultilibs & Result) static
Definition at line 1286 of file Gnu.cpp.
References clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibSet::FilterOut(), clang::driver::MultilibSetBuilder::makeMultilibSet(), clang::driver::MultilibSetBuilder::Maybe(), and clang::driver::MultilibSet::select().
findMipsCsMultilibs()
static bool findMipsCsMultilibs (const Multilib::flags_list & Flags, FilterNonExistent & NonExistent, DetectedMultilibs & Result) static
Definition at line 1182 of file Gnu.cpp.
References clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibSetBuilder::FilterOut(), clang::driver::MultilibSet::FilterOut(), clang::driver::MultilibBuilder::flag(), clang::driver::MultilibBuilder::gccSuffix(), clang::driver::Multilib::includeSuffix(), clang::driver::MultilibSetBuilder::makeMultilibSet(), clang::driver::MultilibSetBuilder::Maybe(), clang::driver::MultilibSet::setIncludeDirsCallback(), and clang::driver::MultilibSet::size().
findMipsImgMultilibs()
static bool findMipsImgMultilibs (const Multilib::flags_list & Flags, FilterNonExistent & NonExistent, DetectedMultilibs & Result) static
Definition at line 1552 of file Gnu.cpp.
References clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibSet::FilterOut(), clang::driver::MultilibBuilder::flag(), clang::driver::Multilib::gccSuffix(), clang::driver::Multilib::includeSuffix(), clang::driver::MultilibSetBuilder::makeMultilibSet(), clang::driver::MultilibSetBuilder::Maybe(), clang::driver::MultilibBuilder::osSuffix(), and clang::driver::MultilibSet::setIncludeDirsCallback().
findMipsMtiMultilibs()
static bool findMipsMtiMultilibs (const Multilib::flags_list & Flags, FilterNonExistent & NonExistent, DetectedMultilibs & Result) static
Definition at line 1366 of file Gnu.cpp.
References clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibSetBuilder::FilterOut(), clang::driver::MultilibSet::FilterOut(), clang::driver::MultilibBuilder::flag(), clang::driver::Multilib::gccSuffix(), clang::driver::Multilib::includeSuffix(), clang::driver::MultilibSetBuilder::makeMultilibSet(), clang::driver::MultilibSetBuilder::Maybe(), clang::driver::MultilibBuilder::osSuffix(), and clang::driver::MultilibSet::setIncludeDirsCallback().
findMipsMuslMultilibs()
static bool findMipsMuslMultilibs (const Multilib::flags_list & Flags, FilterNonExistent & NonExistent, DetectedMultilibs & Result) static
Definition at line 1332 of file Gnu.cpp.
References clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibBuilder::flag(), clang::driver::MultilibSetBuilder::makeMultilibSet(), clang::driver::Multilib::osSuffix(), clang::driver::MultilibBuilder::osSuffix(), clang::driver::MultilibSet::select(), and clang::driver::MultilibSet::setIncludeDirsCallback().
findMSP430Multilibs()
static bool findMSP430Multilibs (const Driver & D, const llvm::Triple & TargetTriple, StringRef Path, const ArgList & Args, DetectedMultilibs & Result) static
Definition at line 1774 of file Gnu.cpp.
References clang::driver::tools::addMultilibFlag(), clang::driver::MultilibBuilder::flag(), clang::driver::Driver::getVFS(), and clang::driver::MultilibBuilder::makeMultilib().
findRISCVBareMetalMultilibs()
static void findRISCVBareMetalMultilibs (const Driver & D, const llvm::Triple & TargetTriple, StringRef Path, const ArgList & Args, DetectedMultilibs & Result) static
Definition at line 1986 of file Gnu.cpp.
References clang::driver::Driver::getVFS().
Referenced by findRISCVMultilibs().
findRISCVMultilibs()
static void findRISCVMultilibs (const Driver & D, const llvm::Triple & TargetTriple, StringRef Path, const ArgList & Args, DetectedMultilibs & Result) static
Definition at line 2042 of file Gnu.cpp.
References clang::driver::tools::addMultilibFlag(), clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibSetBuilder::FilterOut(), findRISCVBareMetalMultilibs(), clang::driver::MultilibBuilder::flag(), clang::driver::tools::riscv::getRISCVABI(), clang::driver::Driver::getVFS(), and clang::driver::MultilibSet::select().
forwardToGCC()
static bool forwardToGCC (const Option & O) static
Definition at line 46 of file Gnu.cpp.
References clang::driver::options::LinkerInput, and clang::driver::options::LinkOption.
Referenced by clang::driver::tools::gcc::Common::ConstructJob().
getGCCToolchainDir()
static llvm::StringRef getGCCToolchainDir (const ArgList & Args, llvm::StringRef SysRoot) static
Definition at line 2335 of file Gnu.cpp.
Referenced by clang::driver::toolchains::Generic_GCC::GCCInstallationDetector::init().
getLDMOption()
static const char* getLDMOption (const llvm::Triple & T, const ArgList & Args) static
Definition at line 224 of file Gnu.cpp.
References clang::driver::tools::mips::hasMipsAbiArg(), clang::driver::tools::arm::isARMBigEndian(), and clang::T.
Referenced by clang::driver::tools::gnutools::Linker::ConstructJob().
getStatic()
static bool getStatic (const ArgList & Args) static
Definition at line 308 of file Gnu.cpp.
Referenced by clang::driver::tools::gnutools::Linker::ConstructJob().
getStaticPIE()
static bool getStaticPIE (const ArgList & Args, const ToolChain & TC) static
Definition at line 296 of file Gnu.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), and clang::driver::Driver::getOpts().
Referenced by clang::driver::tools::gnutools::Linker::ConstructJob().
isArmOrThumbArch()
static bool isArmOrThumbArch (llvm::Triple::ArchType Arch) static
Definition at line 1160 of file Gnu.cpp.
isMicroMips()
static bool isMicroMips (const ArgList & Args) static
Definition at line 1173 of file Gnu.cpp.
isMips16()
static bool isMips16 (const ArgList & Args) static
Definition at line 1168 of file Gnu.cpp.
isMipsEL()
static bool isMipsEL (llvm::Triple::ArchType Arch) static
Definition at line 1164 of file Gnu.cpp.
isMSP430()
static bool isMSP430 (llvm::Triple::ArchType Arch) static
Definition at line 1178 of file Gnu.cpp.
isSoftFloatABI()
static bool isSoftFloatABI (const ArgList & Args) static
Definition at line 1149 of file Gnu.cpp.
normalizeCPUNamesForAssembler()
static void normalizeCPUNamesForAssembler (const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 56 of file Gnu.cpp.
selectRISCVMultilib()
static bool selectRISCVMultilib (const MultilibSet & RISCVMultilibSet, StringRef Arch, const Multilib::flags_list & Flags, llvm::SmallVectorImpl< Multilib > & SelectedMultilibs) static
Extend the multi-lib re-use selection mechanism for RISC-V.
This function will try to re-use multi-lib if they are compatible. Definition of compatible:
ABI must be the same.
multi-lib is a subset of current arch, e.g. multi-lib=march=rv32im is a subset of march=rv32imc.
march that contains atomic extension can't reuse multi-lib that doesn't have atomic, vice versa. e.g. multi-lib=march=rv32im and march=rv32ima are not compatible, because software and hardware atomic operation can't work together correctly.
Definition at line 1878 of file Gnu.cpp.
References clang::driver::tools::addMultilibFlag(), clang::driver::MultilibSetBuilder::Either(), clang::driver::MultilibBuilder::flag(), clang::driver::MultilibSetBuilder::makeMultilibSet(), and clang::driver::MultilibSet::select().