clang: lib/Lex/HeaderSearch.cpp File Reference
HeaderSearch.cpp File Reference
#include "clang/Lex/HeaderSearch.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Lex/DirectoryLookup.h"
#include "clang/Lex/ExternalPreprocessorSource.h"
#include "clang/Lex/HeaderMap.h"
#include "clang/Lex/HeaderSearchOptions.h"
#include "clang/Lex/LexDiagnostic.h"
#include "clang/Lex/ModuleMap.h"
#include "clang/Lex/Preprocessor.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Capacity.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VirtualFileSystem.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdio>
#include <cstring>
#include <string>
#include <system_error>
#include <utility>
Macros
#define DEBUG_TYPE "file-search"
Functions
ALWAYS_ENABLED_STATISTIC (NumIncluded, "Number of attempted #includes.")
ALWAYS_ENABLED_STATISTIC (NumMultiIncludeFileOptzn, "Number of #includes skipped due to the multi-include optimization.")
ALWAYS_ENABLED_STATISTIC (NumFrameworkLookups, "Number of framework lookups.")
ALWAYS_ENABLED_STATISTIC (NumSubFrameworkLookups, "Number of subframework lookups.")
static OptionalDirectoryEntryRef getTopFrameworkDir (FileManager &FileMgr, StringRef DirName, SmallVectorImpl< std::string > &SubmodulePath)
Given a framework directory, find the top-most framework directory.
static bool needModuleLookup (Module *RequestingModule, bool HasSuggestedModule)
static bool checkMSVCHeaderSearch (DiagnosticsEngine &Diags, OptionalFileEntryRef MSFE, const FileEntry *FE, SourceLocation IncludeLoc)
Return true with a diagnostic if the file that MSVC would have found fails to match the one that Clang would have found with MSVC header search disabled.
static const char * copyString (StringRef Str, llvm::BumpPtrAllocator &Alloc)
static bool isFrameworkStylePath (StringRef Path, bool &IsPrivateHeader, SmallVectorImpl< char > &FrameworkName, SmallVectorImpl< char > &IncludeSpelling)
static void diagnoseFrameworkInclude (DiagnosticsEngine &Diags, SourceLocation IncludeLoc, StringRef Includer, StringRef IncludeFilename, FileEntryRef IncludeFE, bool isAngled=false, bool FoundByHeaderMap=false)
static void mergeHeaderFileInfoModuleBits (HeaderFileInfo &HFI, bool isModuleHeader, bool isTextualModuleHeader)
static void mergeHeaderFileInfo (HeaderFileInfo &HFI, const HeaderFileInfo &OtherHFI)
Merge the header file info provided by OtherHFI into the current header file info (HFI)
static bool suggestModule (HeaderSearch &HS, FileEntryRef File, Module *RequestingModule, ModuleMap::KnownHeader *SuggestedModule)
static OptionalFileEntryRef getPrivateModuleMap (FileEntryRef File, FileManager &FileMgr, DiagnosticsEngine &Diags)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "file-search"
Definition at line 51 of file HeaderSearch.cpp.
Function Documentation
ALWAYS_ENABLED_STATISTIC() [1/4]
ALWAYS_ENABLED_STATISTIC (NumFrameworkLookups , "Number of framework lookups.")
ALWAYS_ENABLED_STATISTIC() [2/4]
ALWAYS_ENABLED_STATISTIC (NumIncluded , "Number of attempted #includes.")
ALWAYS_ENABLED_STATISTIC() [3/4]
ALWAYS_ENABLED_STATISTIC (NumMultiIncludeFileOptzn , "Number of #includes skipped due to the multi-include optimization.")
ALWAYS_ENABLED_STATISTIC() [4/4]
ALWAYS_ENABLED_STATISTIC (NumSubFrameworkLookups , "Number of subframework lookups.")
checkMSVCHeaderSearch()
static bool checkMSVCHeaderSearch (DiagnosticsEngine & Diags, OptionalFileEntryRef MSFE, const FileEntry * FE, SourceLocation IncludeLoc) static
Return true with a diagnostic if the file that MSVC would have found fails to match the one that Clang would have found with MSVC header search disabled.
Definition at line 778 of file HeaderSearch.cpp.
References clang::FileEntryRef::getName(), and clang::DiagnosticsEngine::Report().
Referenced by clang::HeaderSearch::LookupFile().
copyString()
static const char* copyString (StringRef Str, llvm::BumpPtrAllocator & Alloc) static
Definition at line 789 of file HeaderSearch.cpp.
Referenced by clang::HeaderSearch::LookupFile().
diagnoseFrameworkInclude()
static void diagnoseFrameworkInclude (DiagnosticsEngine & Diags, SourceLocation IncludeLoc, StringRef Includer, StringRef IncludeFilename, FileEntryRef IncludeFE, bool isAngled = false, bool FoundByHeaderMap = false) static
Definition at line 839 of file HeaderSearch.cpp.
References clang::FixItHint::CreateReplacement(), clang::FileEntryRef::getName(), isFrameworkStylePath(), and clang::DiagnosticsEngine::Report().
Referenced by clang::HeaderSearch::LookupFile().
getPrivateModuleMap()
static OptionalFileEntryRef getPrivateModuleMap (FileEntryRef File, FileManager & FileMgr, DiagnosticsEngine & Diags) static
Definition at line 1755 of file HeaderSearch.cpp.
References clang::File, Filename, clang::FileManager::getOptionalFileRef(), and clang::DiagnosticsEngine::Report().
getTopFrameworkDir()
static OptionalDirectoryEntryRef getTopFrameworkDir (FileManager & FileMgr, StringRef DirName, SmallVectorImpl< std::string > & SubmodulePath) static
Given a framework directory, find the top-most framework directory.
Parameters
FileMgr The file manager to use for directory lookups.
DirName The name of the framework directory.
SubmodulePath Will be populated with the submodule path from the returned top-level module to the originally named framework.
Definition at line 560 of file HeaderSearch.cpp.
References clang::FileManager::getCanonicalName(), and clang::FileManager::getOptionalDirectoryRef().
isFrameworkStylePath()
static bool isFrameworkStylePath (StringRef Path, bool & IsPrivateHeader, SmallVectorImpl< char > & FrameworkName, SmallVectorImpl< char > & IncludeSpelling) static
Definition at line 797 of file HeaderSearch.cpp.
Referenced by diagnoseFrameworkInclude(), and clang::HeaderSearch::suggestPathToFileForDiagnostics().
mergeHeaderFileInfo()
static void mergeHeaderFileInfo (HeaderFileInfo & HFI, const HeaderFileInfo & OtherHFI) static
Merge the header file info provided by OtherHFI into the current header file info (HFI)
Definition at line 1335 of file HeaderSearch.cpp.
References clang::HeaderFileInfo::ControllingMacro, clang::HeaderFileInfo::ControllingMacroID, clang::HeaderFileInfo::DirInfo, clang::HeaderFileInfo::External, clang::HeaderFileInfo::Framework, clang::HeaderFileInfo::IndexHeaderMapHeader, clang::HeaderFileInfo::isImport, clang::HeaderFileInfo::isModuleHeader, clang::HeaderFileInfo::isPragmaOnce, clang::HeaderFileInfo::isTextualModuleHeader, clang::HeaderFileInfo::IsValid, and mergeHeaderFileInfoModuleBits().
Referenced by clang::HeaderSearch::getExistingFileInfo(), and clang::HeaderSearch::getFileInfo().
mergeHeaderFileInfoModuleBits()
static void mergeHeaderFileInfoModuleBits (HeaderFileInfo & HFI, bool isModuleHeader, bool isTextualModuleHeader) static
Definition at line 1316 of file HeaderSearch.cpp.
References clang::HeaderFileInfo::isModuleHeader, and clang::HeaderFileInfo::isTextualModuleHeader.
Referenced by mergeHeaderFileInfo(), and clang::HeaderFileInfo::mergeModuleMembership().
needModuleLookup()
static bool needModuleLookup (Module * RequestingModule, bool HasSuggestedModule) static
Definition at line 605 of file HeaderSearch.cpp.
References clang::Module::NoUndeclaredIncludes.
suggestModule()
static bool suggestModule (HeaderSearch & HS, FileEntryRef File, Module * RequestingModule, ModuleMap::KnownHeader * SuggestedModule) static
Definition at line 1682 of file HeaderSearch.cpp.
References clang::Module::directlyUses(), clang::File, clang::HeaderSearch::findModuleForHeader(), clang::HeaderSearch::getModuleMap(), clang::ModuleMap::isBuiltinHeader(), clang::Module::NoUndeclaredIncludes, clang::ModuleMap::resolveUses(), and clang::ModuleMap::TextualHeader.