clang: lib/Driver/ToolChains/HIPAMD.cpp File Reference
HIPAMD.cpp File Reference
#include "HIPAMD.h"
#include "AMDGPU.h"
#include "CommonArgs.h"
#include "HIPUtility.h"
#include "clang/Basic/Cuda.h"
#include "clang/Basic/TargetID.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/TargetParser/TargetParser.h"
Macros
#define NULL_FILE "/dev/null"
Functions
static bool shouldSkipSanitizeOption (const ToolChain &TC, const llvm::opt::ArgList &DriverArgs, StringRef TargetID, const llvm::opt::Arg *A)
static const char * getLibSpirvTargetName (const ToolChain &HostTC)
Macro Definition Documentation
NULL_FILE
#define NULL_FILE "/dev/null"
Definition at line 35 of file HIPAMD.cpp.
Function Documentation
getLibSpirvTargetName()
static const char* getLibSpirvTargetName (const ToolChain & HostTC) static
Definition at line 242 of file HIPAMD.cpp.
Referenced by clang::driver::toolchains::HIPAMDToolChain::addClangTargetOptions().
shouldSkipSanitizeOption()
static bool shouldSkipSanitizeOption (const ToolChain & TC, const llvm::opt::ArgList & DriverArgs, StringRef TargetID, const llvm::opt::Arg * A) static
Definition at line 38 of file HIPAMD.cpp.
References clang::driver::Driver::getDiags(), clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getTriple(), clang::parseSanitizerValue(), and clang::parseTargetID().
Referenced by clang::driver::toolchains::HIPAMDToolChain::TranslateArgs().