clang: lib/StaticAnalyzer/Core/HTMLDiagnostics.cpp File Reference
HTMLDiagnostics.cpp File Reference
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/Stmt.h"
#include "clang/Analysis/IssueHash.h"
#include "clang/Analysis/MacroExpansionContext.h"
#include "clang/Analysis/PathDiagnostic.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Lex/Lexer.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/Token.h"
#include "clang/Rewrite/Core/HTMLRewrite.h"
#include "clang/Rewrite/Core/Rewriter.h"
#include "clang/StaticAnalyzer/Core/PathDiagnosticConsumers.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <system_error>
#include <utility>
#include <vector>
Functions
static llvm::SmallString< 32 > getIssueHash (const PathDiagnostic &D, const Preprocessor &PP)
static bool shouldDisplayPopUpRange (const SourceRange &Range)
static void HandlePopUpPieceStartTag (Rewriter &R, const std::vector< SourceRange > &PopUpRanges)
static void HandlePopUpPieceEndTag (Rewriter &R, const PathDiagnosticPopUpPiece &Piece, std::vector< SourceRange > &PopUpRanges, unsigned int LastReportedPieceIndex, unsigned int PopUpPieceIndex)
static void EmitAlphaCounter (raw_ostream &os, unsigned n)
std::string getSpanBeginForControl (const char *ClassName, unsigned Index)
std::string getSpanBeginForControlStart (unsigned Index)
std::string getSpanBeginForControlEnd (unsigned Index)
document addEventListener ("DOMContentLoaded", function() { document .querySelector('input[id="showinvocation"]') .addEventListener("click", drawArrows);document .querySelector('input[name="showCounterexample"]') .addEventListener("change", drawArrows);document .querySelector('input[name="showArrows"]') .addEventListener("change", toggleArrows);drawArrows();highlightArrowsForSelectedEvent();})
Variables
var drawArrows
Function Documentation
addEventListener()
document addEventListener ("DOMContentLoaded" , function() { document .querySelector('input[id="showinvocation"]') .addEventListener("click", drawArrows);document .querySelector('input[name="showCounterexample"]') .addEventListener("change", drawArrows);document .querySelector('input[name="showArrows"]') .addEventListener("change", toggleArrows);drawArrows();highlightArrowsForSelectedEvent();})
EmitAlphaCounter()
static void EmitAlphaCounter (raw_ostream & os, unsigned n) static
Definition at line 1032 of file HTMLDiagnostics.cpp.
References clang::FullSourceLoc::getBufferData(), clang::FullSourceLoc::getDecomposedLoc(), clang::FullSourceLoc::getExpansionLoc(), clang::Preprocessor::getLangOpts(), clang::Token::getLength(), clang::SourceLocation::isFileID(), clang::Lexer::LexFromRawLexer(), and SM.
getIssueHash()
static llvm::SmallString<32> getIssueHash (const PathDiagnostic & D, const Preprocessor & PP) static
Definition at line 251 of file HTMLDiagnostics.cpp.
References clang::ento::PathDiagnosticLocation::asLocation(), clang::ento::PathDiagnostic::getBugType(), clang::ento::PathDiagnostic::getCheckerName(), clang::ento::PathDiagnostic::getDeclWithIssue(), clang::SourceManager::getExpansionLoc(), clang::getIssueHash(), clang::Preprocessor::getLangOpts(), clang::ento::PathDiagnostic::getLocation(), clang::Preprocessor::getSourceManager(), clang::ento::PathDiagnostic::getUniqueingLoc(), and clang::ento::PathDiagnosticLocation::isValid().
getSpanBeginForControl()
std::string getSpanBeginForControl (const char * ClassName, unsigned Index)
Definition at line 1085 of file HTMLDiagnostics.cpp.
getSpanBeginForControlEnd()
std::string getSpanBeginForControlEnd (unsigned Index)
Definition at line 1096 of file HTMLDiagnostics.cpp.
References clang::html::HighlightRange().
getSpanBeginForControlStart()
std::string getSpanBeginForControlStart (unsigned Index)
Definition at line 1092 of file HTMLDiagnostics.cpp.
HandlePopUpPieceEndTag()
static void HandlePopUpPieceEndTag (Rewriter & R, const PathDiagnosticPopUpPiece & Piece, std::vector< SourceRange > & PopUpRanges, unsigned int LastReportedPieceIndex, unsigned int PopUpPieceIndex) static
Definition at line 665 of file HTMLDiagnostics.cpp.
HandlePopUpPieceStartTag()
static void HandlePopUpPieceStartTag (Rewriter & R, const std::vector< SourceRange > & PopUpRanges) static
Definition at line 653 of file HTMLDiagnostics.cpp.
shouldDisplayPopUpRange()
static bool shouldDisplayPopUpRange (const SourceRange & Range) static
Definition at line 648 of file HTMLDiagnostics.cpp.
References clang::ento::PathDiagnostic::getVerboseDescription(), and s.
Variable Documentation
drawArrows
var drawArrows
Initial value:
= function() {
  const numOfArrows = document.querySelectorAll("path[id^=arrow]").length;
  for (var i = 0; i < numOfArrows; ++i) {
    drawArrow(i);
  }
}
var toggleArrows = function(event) {
  const arrows = document.querySelector("#arrows");
  if (event.target.checked) {
    arrows.setAttribute("visibility", "visible");
  } else {
    arrows.setAttribute("visibility", "hidden");
  }
}
window.addEventListener("resize", drawArrows)
Definition at line 1476 of file HTMLDiagnostics.cpp.