clang: lib/Index/IndexingAction.cpp File Reference
IndexingAction.cpp File Reference
#include "clang/Index/IndexingAction.h"
#include "IndexingContext.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendAction.h"
#include "clang/Frontend/MultiplexConsumer.h"
#include "clang/Index/IndexDataConsumer.h"
#include "clang/Lex/PPCallbacks.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Serialization/ASTReader.h"
#include "llvm/ADT/STLExtras.h"
#include <memory>
Functions
static bool topLevelDeclVisitor (void *context, const Decl *D)
static void indexTranslationUnit (ASTUnit &Unit, IndexingContext &IndexCtx)
static void indexPreprocessorMacro (const IdentifierInfo *II, const MacroInfo *MI, MacroDirective::Kind DirectiveKind, SourceLocation Loc, IndexDataConsumer &DataConsumer)
static void indexPreprocessorMacros (Preprocessor &PP, IndexDataConsumer &DataConsumer)
static void indexPreprocessorModuleMacros (Preprocessor &PP, serialization::ModuleFile &Mod, IndexDataConsumer &DataConsumer)
Function Documentation
indexPreprocessorMacro()
static void indexPreprocessorMacro (const IdentifierInfo * II, const MacroInfo * MI, MacroDirective::Kind DirectiveKind, SourceLocation Loc, IndexDataConsumer & DataConsumer) static
Definition at line 210 of file IndexingAction.cpp.
References clang::index::Definition, clang::index::IndexDataConsumer::handleMacroOccurrence(), clang::MacroDirective::MD_Define, clang::MacroDirective::MD_Visibility, and clang::index::Undefinition.
Referenced by indexPreprocessorMacros(), and indexPreprocessorModuleMacros().
indexPreprocessorMacros()
static void indexPreprocessorMacros (Preprocessor & PP, IndexDataConsumer & DataConsumer) static
Definition at line 232 of file IndexingAction.cpp.
References clang::MacroDefinition::getMacroInfo(), indexPreprocessorMacro(), and clang::Preprocessor::macros().
Referenced by clang::index::indexASTUnit(), and clang::index::indexTopLevelDecls().
indexPreprocessorModuleMacros()
static void indexPreprocessorModuleMacros (Preprocessor & PP, serialization::ModuleFile & Mod, IndexDataConsumer & DataConsumer) static
Definition at line 242 of file IndexingAction.cpp.
References clang::serialization::ModuleFile::File, clang::Preprocessor::getLeafModuleMacros(), indexPreprocessorMacro(), clang::Preprocessor::macros(), and clang::MacroDirective::MD_Define.
Referenced by clang::index::indexModuleFile().
indexTranslationUnit()
static void indexTranslationUnit (ASTUnit & Unit, IndexingContext & IndexCtx) static
Definition at line 206 of file IndexingAction.cpp.
References topLevelDeclVisitor(), and clang::ASTUnit::visitLocalTopLevelDecls().
Referenced by clang::index::indexASTUnit().
topLevelDeclVisitor()
static bool topLevelDeclVisitor (void * context, const Decl * D) static
Definition at line 201 of file IndexingAction.cpp.
References clang::index::IndexingContext::indexTopLevelDecl().
Referenced by indexTranslationUnit().