clang: lib/Tooling/CMakeLists.txt File Reference
lib/Tooling/CMakeLists.txt File Reference
Functions
set (LLVM_LINK_COMPONENTS Option FrontendOpenMP Support) add_subdirectory(Core) add_subdirectory(Inclusions) add_subdirectory(Refactoring) add_subdirectory(ASTDiff) add_subdirectory(DumpTool) add_subdirectory(Syntax) add_subdirectory(DependencyScanning) add_subdirectory(Transformer) string(FIND $
lib PATH_LIB_START REVERSE if (PATH_LIB_START EQUAL -1) message(FATAL_ERROR "Couldn't find lib component in binary directory") endif() math(EXPR PATH_LIB_END "$
string (SUBSTRING ${CMAKE_CURRENT_BINARY_DIR} 0 ${PATH_LIB_START} PATH_HEAD) string(SUBSTRING $
Function Documentation
if()
lib PATH_LIB_START REVERSE if (PATH_LIB_START EQUAL - 1)
Definition at line 18 of file CMakeLists.txt.
set()
set (LLVM_LINK_COMPONENTS Option FrontendOpenMP Support)
Definition at line 1 of file CMakeLists.txt.
string()
string (SUBSTRING ${CMAKE_CURRENT_BINARY_DIR} 0 ${PATH_LIB_START} PATH_HEAD)
Definition at line 22 of file CMakeLists.txt.
Referenced by clang::Sema::ActOnGCCAsmStmt(), clang::Sema::ActOnModuleDecl(), clang::Sema::ActOnModuleImport(), clang::Sema::ActOnOpenMPDefaultmapClause(), clang::Sema::ActOnOpenMPDependClause(), clang::Sema::ActOnOpenMPDeviceClause(), clang::Sema::ActOnOpenMPDistScheduleClause(), clang::Sema::ActOnOpenMPScheduleClause(), clang::Sema::ActOnOpenMPTileDirective(), clang::Sema::ActOnOpenMPUnrollDirective(), clang::comments::Sema::actOnParamCommandDirectionArg(), clang::Sema::ActOnPragmaClangSection(), clang::NodeStreamer::AddChild(), clang::driver::toolchains::BareMetal::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::MinGW::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::Fuchsia::AddClangCXXStdlibIncludeArgs(), clang::driver::toolchains::AVRToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::Hurd::AddClangSystemIncludeArgs(), clang::driver::toolchains::Linux::AddClangSystemIncludeArgs(), clang::driver::toolchains::CrossWindowsToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::HexagonToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), clang::driver::toolchains::HIPAMDToolChain::addClangTargetOptions(), clang::driver::toolchains::AMDGPUOpenMPToolChain::addClangTargetOptions(), clang::driver::toolchains::ROCMToolChain::addClangTargetOptions(), clang::driver::toolchains::CudaToolChain::addClangTargetOptions(), clang::driver::toolchains::Darwin::addClangTargetOptions(), addDefaultIgnorelists(), clang::DependencyCollector::addDependency(), addDiagnosticArgs(), clang::driver::ToolChain::addFastMathRuntimeIfAvailable(), clang::DiagnosticBuilder::addFlagValue(), AddFunctionParameterChunks(), AddFunctionTypeQualsToCompletionString(), clang::driver::toolchains::Generic_GCC::addGCCLibStdCxxIncludePaths(), clang::tooling::AtomicChange::addHeader(), clang::html::AddHeaderFooterInternalBuiltinCSS(), clang::HeaderSearch::AddIncludeAlias(), clang::driver::toolchains::NetBSD::addLibCxxIncludePaths(), clang::driver::toolchains::MyriadToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::HexagonToolChain::addLibCxxIncludePaths(), clang::driver::toolchains::Generic_GCC::addLibCxxIncludePaths(), clang::driver::toolchains::Linux::addLibStdCxxIncludePaths(), clang::driver::toolchains::HexagonToolChain::addLibStdCxxIncludePaths(), clang::driver::toolchains::Generic_GCC::addLibStdCXXIncludePaths(), clang::html::AddLineNumbers(), clang::ento::PathDiagnostic::addMeta(), clang::serialization::ModuleManager::addModule(), clang::driver::tools::addMultilibFlag(), clang::driver::toolchains::Generic_GCC::AddMultilibIncludeArgs(), clang::driver::tools::addOpenMPDeviceRTL(), AddOverloadParameterChunks(), clang::driver::toolchains::Darwin::addPlatformVersionArgs(), clang::arcmt::trans::MigrationContext::addPropertyAttribute(), AddQualifierToCompletionString(), clang::PreprocessorOptions::addRemappedFile(), clang::Module::addRequirement(), clang::transformer::addressOf(), clang::driver::tools::AddStaticDeviceLibs(), clang::StreamingDiagnostic::AddString(), clang::tooling::addTargetAndModeForProgramName(), AddTemplateParameterChunks(), clang::Module::addTopHeaderFilename(), clang::GCCAsmStmt::AnalyzeAsmString(), annotateConsumedSummaryMismatch(), annotateStartParameter(), appendRecordType(), clang::tooling::applyAllReplacements(), applyEditsToTemp(), clang::arcmt::MigrationProcess::applyTransform(), clang::ast_matchers::AST_MATCHER_REGEX(), clang::tooling::AtomicChange::AtomicChange(), clang::driver::toolchains::AVRToolChain::AVRToolChain(), clang::driver::toolchains::BareMetal::BareMetal(), clang::FrontendAction::BeginSourceFile(), clang::PrecompiledPreamble::Build(), clang::tooling::buildAccess(), clang::driver::Driver::BuildActions(), clang::tooling::buildAddressOf(), buildBlockDescriptor(), clang::driver::ToolChain::buildCompilerRTBasename(), buildFixItInsertionLine(), clang::Sema::BuildObjCEncodeExpression(), clang::Sema::BuildStaticAssertDeclaration(), bytes(), clang::tooling::calculateRangesAfterReplacements(), clang::MinComplexityConstraint::calculateStmtComplexity(), clang::CodeGen::CodeGenFunction::callCStructCopyAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructCopyConstructor(), clang::CodeGen::CodeGenFunction::callCStructDefaultConstructor(), clang::CodeGen::CodeGenFunction::callCStructDestructor(), clang::CodeGen::CodeGenFunction::callCStructMoveAssignmentOperator(), clang::CodeGen::CodeGenFunction::callCStructMoveConstructor(), checkARMArchName(), checkARMCPUName(), CheckAvailability(), clang::Sema::CheckComparisonCategoryType(), clang::ento::CheckerRegistry::CheckerRegistry(), clang::arcmt::checkForManualIssues(), checkLanguageOptions(), CheckLists(), clang::Sema::CheckObjCBridgeRelatedConversions(), checkObjCUnusedIvar(), clang::CodeGen::CodeGenFunction::checkTargetFeatures(), clang::Sema::CheckVirtualDtorCall(), clang::driver::Compilation::CleanupFileList(), clang::arcmt::FileRemapper::clear(), clang::driver::toolchains::CloudABI::CloudABI(), clang::ASTUnit::CodeComplete(), clang::Sema::CodeCompleteIncludedFile(), collectVFSEntries(), CompareReturnTypes(), compileModule(), clang::tooling::dependencies::DependencyScanningWorker::computeDependencies(), clang::PredefinedExpr::ComputeName(), clang::SYCLUniqueStableNameExpr::ComputeName(), clang::SYCLUniqueStableIdExpr::ComputeName(), clang::syntax::computeReplacements(), clang::driver::toolchains::MipsLLVMToolChain::computeSysRoot(), clang::driver::toolchains::Linux::computeSysRoot(), clang::driver::toolchains::BareMetal::computeSysRoot(), constructDebugPieceForTrackedCondition(), constructHexagonLinkArgs(), clang::driver::tools::ifstool::Merger::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::SHAVE::Compiler::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::CrossWindows::Assembler::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), clang::driver::tools::amdgpu::Linker::ConstructJob(), clang::driver::tools::AMDGCN::OpenMPLinker::ConstructJob(), clang::driver::tools::SHAVE::Assembler::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), clang::driver::tools::SPIRV::Linker::ConstructJob(), clang::driver::tools::SYCL::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::Myriad::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::Flang::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::SYCL::fpga::BackendCompiler::ConstructJob(), clang::driver::tools::gcc::Common::ConstructJob(), clang::driver::tools::SYCL::gen::BackendCompiler::ConstructJob(), clang::driver::tools::SYCL::x86_64::BackendCompiler::ConstructJob(), clang::driver::tools::Clang::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::OffloadWrapper::ConstructJob(), clang::driver::tools::SPIRVTranslator::ConstructJob(), clang::driver::tools::SYCLPostLink::ConstructJob(), clang::driver::tools::SYCL::constructLLVMForeachCommand(), clang::Sema::ConstructOpenCLKernel(), clang::targets::M68kTargetInfo::convertConstraint(), clang::targets::RISCVTargetInfo::convertConstraint(), clang::targets::AArch64TargetInfo::convertConstraint(), clang::targets::ARMTargetInfo::convertConstraint(), clang::targets::X86TargetInfo::convertConstraint(), clang::targets::MipsTargetInfo::convertConstraint(), clang::targets::PPCTargetInfo::convertConstraint(), clang::TargetInfo::convertConstraint(), ConvertTypeToDiagnosticString(), clang::IncrementalCompilerBuilder::create(), clang::VerifyDiagnosticConsumer::Directive::create(), clang::ast_matchers::dynamic::internal::VariadicOperatorMatcherDescriptor::create(), clang::ast_matchers::internal::createAndVerifyRegex(), createArtifactLocation(), clang::RewriteObjCAction::CreateASTConsumer(), clang::CodeGenAction::CreateASTConsumer(), clang::GeneratePCHAction::CreateASTConsumer(), clang::GenerateModuleAction::CreateASTConsumer(), clang::CompilerInstance::createASTReader(), clang::createChainedIncludesSource(), clang::CodeCompletionResult::createCodeCompletionStringForDecl(), clang::CodeCompletionResult::createCodeCompletionStringForOverride(), clang::CodeGen::TargetCodeGenInfo::createEnqueuedBlockKernel(), clang::CreateFrontendBaseAction(), clang::FixItHint::CreateInsertion(), createInvocationForMigration(), clang::CompilerInstance::createModuleFromSource(), clang::driver::Driver::CreateOffloadingDeviceToolChains(), clang::CompilerInstance::createPreprocessor(), clang::FixItHint::CreateReplacement(), createRule(), clang::CodeGen::CodeGenModule::createUnnamedGlobalFrom(), clang::driver::CudaInstallationDetector::CudaInstallationDetector(), clang::driver::toolchains::CudaToolChain::CudaToolChain(), clang::dataflow::DebugString(), denormalizeStringVector(), clang::transformer::deref(), describeRegion(), describeSanitizeArg(), clang::driver::ToolChain::detectLibcxxVersion(), clang::driver::toolchains::AMDGPUToolChain::detectSystemGPUs(), clang::Sema::DiagnoseAlwaysNonNullPointer(), clang::Sema::DiagnoseAvailabilityOfDecl(), clang::Sema::DiagnoseDeprecatedAttribute(), clang::driver::Driver::DiagnoseInputExistence(), clang::Sema::diagnoseMissingImport(), diagnoseNoViableConversion(), clang::Sema::DiagnoseSentinelCalls(), clang::Sema::diagnoseTypo(), clang::BackendConsumer::DiagnosticHandlerImpl(), clang::tooling::DiagnosticMessage::DiagnosticMessage(), disambiguateSpellingInScope(), clang::driver::Driver::Driver(), clang::syntax::Node::dump(), clang::syntax::Token::dumpForTests(), clang::syntax::TokenBuffer::dumpForTests(), dumpRecord(), clang::syntax::Node::dumpTokens(), clang::CodeGen::CoverageMappingModuleGen::emit(), emitAArch64DeclareSimdFunction(), clang::CodeGen::CodeGenFunction::EmitAtomicExpr(), emitCheckHandlerCall(), clang::CodeGen::CodeGenFunction::EmitCheckSourceLocation(), emitCombinerOrInitializer(), emitCopyprivateCopyFunction(), emitDestructorsFunction(), emitDiagnostics(), EmitDirectCallee(), emitInitWithReductionInitializer(), emitMappingInformation(), clang::CodeGen::CodeGenFunction::EmitObjCBoxedExpr(), emitOffloadingArrays(), clang::BackendConsumer::EmitOptimizationMessage(), emitPPCLoadReserveIntrinsic(), clang::CodeGen::CodeGenFunction::EmitPredefinedLValue(), emitProxyTaskFunction(), emitReduceCombFunction(), emitReduceFiniFunction(), emitReduceInitFunction(), clang::CodeGen::CGOpenMPRuntime::emitReductionFunction(), clang::CodeGen::CGOpenMPRuntime::emitRequiresDirectiveRegFun(), EmitShim(), EmitShims(), clang::CodeGen::CGOpenMPRuntime::emitTargetOutlinedFunctionHelper(), emitTaskDupFunction(), emitTaskPrivateMappingFunction(), clang::CodeGen::CGOpenMPRuntime::emitThreadPrivateVarDefinition(), EmitUnknownDiagWarning(), clang::CodeGen::CGOpenMPRuntime::emitUpdateLocation(), clang::CodeGen::CGOpenMPRuntime::emitUserDefinedMapper(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheck(), clang::CodeGen::CodeGenFunction::EmitVTableTypeCheckedLoad(), clang::CodeGen::CodeGenModule::EmitVTableTypeMetadata(), EmitX86BitTestIntrinsic(), clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile(), clang::Preprocessor::EnterSourceFile(), clang::serialization::reader::HeaderFileInfoTrait::EqualKey(), clang::CodeGen::CodeGenModule::ErrorUnsupported(), clang::html::EscapeText(), clang::SourceLocExpr::EvaluateInContext(), EvaluateValue(), clang::tooling::AllTUsToolExecutor::execute(), clang::driver::Command::Execute(), clang::RewriteIncludesAction::ExecuteAction(), clang::DumpModuleInfoAction::ExecuteAction(), clang::VerifyPCHAction::ExecuteAction(), clang::driver::Compilation::ExecuteCommand(), clang::transformer::expression(), clang::tooling::FileByteRange::FileByteRange(), clang::tooling::dependencies::ModuleDepCollectorPP::FileChanged(), fileNameToURI(), clang::ASTContext::filterFunctionTargetAttrs(), clang::driver::MultilibSet::FilterOut(), findClangRelativeSysroot(), findCompilationDatabaseFromDirectory(), clang::Sema::findFailedBooleanCondition(), findGccVersion(), findPassPlugin(), clang::transformer::detail::findSelectedCase(), FindVisualStudioExecutable(), clang::Preprocessor::FinishLexStringLiteral(), clang::driver::Multilib::flag(), clang::arcmt::FileRemapper::flushToDisk(), clang::arcmt::FileRemapper::flushToFile(), clang::tooling::LocationCallFormatterCpp::format(), formatBlockPlaceholder(), clang::Diagnostic::FormatDiagnostic(), FormatFunctionParameter(), formatModuleId(), formatObjCParamQualifiers(), formatTemplateParameterPlaceholder(), clang::ParsedSourceLocation::FromString(), clang::driver::toolchains::Fuchsia::Fuchsia(), GCRewriteFinalize(), clang::GCCAsmStmt::generateAsmString(), clang::MSAsmStmt::generateAsmString(), clang::CodeGen::CodeGenFunction::GenerateCode(), clang::driver::Driver::generateCompilationDiagnostics(), clang::CodeGen::CodeGenFunction::GenerateCopyHelperFunction(), clang::CodeGen::CodeGenFunction::GenerateDestroyHelperFunction(), clang::ento::NoteTag::generateMessage(), generateUniqueName(), clang::CodeGen::CodeGenModule::GenOpenCLArgMetadata(), clang::ParsedAttrInfo::get(), getAArch64ArchFeaturesFromMarch(), getAArch64ArchFeaturesFromMcpu(), getAArch64MicroArchFeaturesFromMcpu(), getAArch64MicroArchFeaturesFromMtune(), clang::CodeGen::CodeGenModule::GetAddrOfConstantStringFromObjCEncode(), clang::CodeGen::CodeGenFunction::OMPBuilderCBHelpers::getAddrOfThreadPrivate(), clang::ASTNameGenerator::Implementation::getAllManglings(), getAllowListFilenames(), clang::driver::ToolChain::getArchSpecificLibPath(), clang::driver::InputInfo::getAsString(), clang::TypoCorrection::getAsString(), clang::DeclarationName::getAsString(), clang::APValue::getAsString(), clang::ObjCRuntime::getAsString(), clang::CodeCompletionString::getAsString(), clang::DeclarationNameInfo::getAsString(), clang::Selector::getAsString(), clang::Decl::getAvailability(), clang::driver::tools::Clang::getBaseInputStem(), getBestNamespaceSubstr(), getBlockCaptureStr(), getBlockDescriptorName(), getBlockLayoutInfoString(), getBufferForFileHandlingRemapping(), clang::tooling::dependencies::ModuleDeps::getCanonicalCommandLine(), clang::getCanonicalTargetID(), clang::getClangFullCPPVersion(), clang::getClangFullRepositoryVersion(), clang::getClangToolFullVersion(), clang::driver::Driver::GetClPchPath(), clang::tooling::dependencies::FullDependencies::getCommandLineWithoutModulePaths(), clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames(), clang::tooling::JSONCompilationDatabase::getCompileCommands(), clang::tooling::FixedCompilationDatabase::getCompileCommands(), clang::driver::toolchains::MipsLLVMToolChain::getCompilerRT(), clang::driver::toolchains::OpenBSD::getCompilerRT(), clang::driver::ToolChain::getCompilerRT(), clang::driver::ToolChain::getCompilerRTBasename(), clang::driver::toolchains::HexagonToolChain::getCompilerRTPath(), clang::driver::ToolChain::getCompilerRTPath(), getCopyDestroyHelperFuncName(), clang::CodeGen::CGOpenMPRuntime::getCriticalRegionLock(), clang::diff::SyntaxTree::Impl::getDeclValue(), clang::driver::toolchains::Linux::getDefaultDenormalModeForType(), GetDefaultValueString(), clang::tooling::dependencies::DependencyScanningTool::getDependencyFile(), clang::ento::MemRegion::getDescriptiveName(), clang::DiagnosticIDs::getDiagnosticFlags(), clang::driver::getDriverMode(), clang::driver::toolchains::Linux::getDynamicLinker(), GetEnclosingDeclContextSignature(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), clang::arcmt::getFileRemappingsFromFileList(), clang::Sema::getFixItZeroInitializerForType(), clang::RawComment::getFormattedText(), clang::tooling::dependencies::DependencyScanningTool::getFullDependencies(), clang::Module::getFullModuleName(), clang::AnalysisDeclContext::getFunctionName(), getFunctionQualifiersAsString(), clang::HeaderSearch::getHeaderMapFileNames(), clang::driver::toolchains::HexagonToolChain::getHexagonLibraryPaths(), clang::driver::toolchains::HexagonToolChain::getHexagonTargetDir(), clang::driver::toolchains::HIPSPVToolChain::getHIPDeviceLibs(), clang::driver::toolchains::HIPAMDToolChain::getHIPDeviceLibs(), clang::diff::getInitializerValue(), clang::driver::toolchains::CudaToolChain::getInputFilename(), getIvarAccessString(), getLinkerArgs(), clang::driver::tools::wasm::Linker::getLinkerPath(), clang::driver::ToolChain::GetLinkerPath(), clang::driver::tools::arm::getLLVMArchKindForARM(), clang::cross_tu::CrossTranslationUnitContext::getLookupName(), clang::data_collection::getMacroStack(), clang::CodeGen::CodeGenModule::getMangledName(), clang::OMPTraitInfo::getMangledName(), getMangledNameImpl(), clang::ASTSourceDescriptor::getModuleName(), clang::driver::toolchains::Linux::getMultiarchTriple(), getName(), clang::ASTNameGenerator::Implementation::getName(), clang::MultiKeywordSelector::getName(), clang::CodeGen::CGOpenMPRuntime::getName(), clang::ObjCImplementationDecl::getNameAsString(), clang::driver::Driver::GetNamedOutputPath(), llvm::DOTGraphTraits< const Stmt * >::getNodeLabel(), llvm::DOTGraphTraits< ExplodedGraph * >::getNodeLabel(), llvm::DOTGraphTraits< const CFG * >::getNodeLabel(), clang::CodeGen::getNonTrivialCStructCopyAssignmentOperator(), clang::CodeGen::getNonTrivialCStructCopyConstructor(), clang::CodeGen::getNonTrivialCStructDefaultConstructor(), clang::CodeGen::getNonTrivialCStructDestructor(), clang::CodeGen::getNonTrivialCStructMoveAssignmentOperator(), clang::CodeGen::getNonTrivialCStructMoveConstructor(), clang::AttributeCommonInfo::getNormalizedFullName(), getNoteTag(), clang::ento::CheckerContext::getNoteTag(), clang::ASTContext::getObjCEncodingForBlock(), clang::ASTContext::getObjCEncodingForFunctionDecl(), clang::ASTContext::getObjCEncodingForMethodDecl(), clang::driver::Action::GetOffloadingFileNamePrefix(), clang::driver::Action::getOffloadingKindPrefix(), clang::LangOptions::getOpenCLVersionString(), clang::diag::CustomDiagInfo::getOrCreateDiagID(), clang::Sema::GetOrCreateMSAsmLabel(), clang::CodeGen::CodeGenModule::getOrCreateStaticVarDecl(), clang::ASTReader::getOriginalSourceFile(), getOverloadAsString(), clang::HeaderSearch::getPrebuiltImplicitModuleFileName(), clang::HeaderSearch::getPrebuiltModuleFileName(), getPrettyTypeName(), getPrioritySuffix(), clang::NamedDecl::getQualifiedNameAsString(), clang::diff::SyntaxTree::Impl::getRelativeName(), clang::analyze_format_string::ArgType::getRepresentativeTypeName(), clang::CompilerInvocation::GetResourcesPath(), clang::driver::Driver::GetResourcesPath(), clang::Rewriter::getRewrittenText(), clang::driver::toolchains::BareMetal::getRuntimesDir(), clang::driver::tools::GetSDLFromOffloadArchive(), GetSignature(), clang::threadSafety::getSourceLiteralString(), clang::CompilerInstance::getSpecificModuleCachePath(), clang::Lexer::getSpelling(), getStaticDeclName(), clang::ento::MemRegion::getString(), getStringOption(), clang::CodeGen::CGObjCRuntime::getSymbolNameForMethod(), getSystemOrSDKMacOSVersion(), clang::driver::ToolChain::getTargetAndModeFromProgramName(), clang::targets::AMDGPUTargetInfo::getTargetID(), clang::Sema::getTemplateArgumentBindingsText(), clang::driver::Driver::GetTemporaryDirectory(), clang::driver::Driver::GetTemporaryPath(), getTopFrameworkDir(), GetTriplePlusArchString(), clang::ast_matchers::dynamic::VariantMatcher::PolymorphicPayload::getTypeAsString(), clang::ast_matchers::dynamic::VariantMatcher::VariadicOpPayload::getTypeAsString(), clang::driver::Driver::GetUniquePath(), clang::driver::toolchains::MSVCToolChain::getUniversalCRTLibraryPath(), clang::tooling::getUSRForDecl(), clang::ento::getVariableName(), clang::driver::toolchains::MSVCToolChain::getWindowsSDKLibraryPath(), clang::targets::M68kTargetInfo::handleAsmEscapedChar(), clang::driver::Driver::HandleAutocompletions(), clang::VerifyDiagnosticConsumer::HandleComment(), clang::TextDiagnosticBuffer::HandleDiagnostic(), clang::LogDiagnosticPrinter::HandleDiagnostic(), handleHVXTargetFeatures(), clang::driver::Driver::HandleImmediateArgs(), clang::Preprocessor::HandlePragmaDependency(), clang::Preprocessor::HandlePragmaHdrstop(), clang::targets::RISCVTargetInfo::handleTargetFeatures(), clang::targets::HexagonTargetInfo::handleTargetFeatures(), clang::tooling::RenamingASTConsumer::HandleTranslationUnit(), clang::targets::HexagonTargetInfo::hasFeature(), clang::ento::hasSuspiciousStmt(), clang::driver::toolchains::HexagonToolChain::HexagonToolChain(), clang::driver::toolchains::Hurd::Hurd(), clang::Sema::ImpCastExprToType(), clang::tooling::dependencies::ModuleDepCollectorPP::InclusionDirective(), clang::driver::toolchains::Generic_GCC::GCCInstallationDetector::init(), clang::targets::RISCVTargetInfo::initFeatureMap(), clang::targets::ARMTargetInfo::initFeatureMap(), clang::arcmt::FileRemapper::initFromDisk(), clang::arcmt::FileRemapper::initFromFile(), clang::InitializePreprocessor(), clang::BackendConsumer::InlineAsmDiagHandler(), clang::tooling::FileMatchTrieNode::insert(), clang::tooling::HeaderIncludes::insert(), insertAndValidate(), clang::format::insertQualifierBefore(), clang::Sema::InstantiateClass(), clang::Sema::InstantiateFunctionDefinition(), isExactClass(), IsHeaderFile(), clang::CodeGen::CodeGenModule::isInNoSanitizeList(), clang::driver::isObjectFile(), isSubclass(), isTargetArch(), isTargetEnvironment(), isTargetOS(), clang::JsonFormat(), clang::LayoutOverrideSource::LayoutOverrideSource(), clang::Preprocessor::LexAfterModuleImport(), clang::driver::toolchains::Linux::Linux(), clang::ASTUnit::LoadFromASTFile(), clang::ASTUnit::LoadFromCommandLine(), clang::ASTUnit::LoadFromCompilerInvocationAction(), clang::tooling::CompilationDatabase::loadFromDirectory(), clang::CompilerInstance::LoadRequestedPlugins(), clang::targets::M68kTargetInfo::M68kTargetInfo(), clang::MacroPPCallbacks::MacroDefined(), main(), makeParamDesc(), makeStandaloneDiagnostic(), mangleVectorParameters(), clang::tooling::AllTUsToolExecutor::mapVirtualFile(), clang::transformer::maybeAddressOf(), clang::transformer::maybeDeref(), clang::tooling::ReplacementError::message(), clang::driver::toolchains::MinGW::MinGW(), clang::driver::toolchains::NaClToolChain::NaClToolChain(), nodeToCommandLine(), normalizePathSegment(), normalizeProgramName(), normalizeString(), clang::Sema::NoteOverloadCandidate(), clang::operator<(), clang::dataflow::operator<<(), clang::operator<<(), clang::comments::BriefParser::Parse(), clang::driver::toolchains::Generic_GCC::GCCVersion::Parse(), clang::driver::Driver::ParseArgStrings(), clang::cross_tu::parseCrossTUIndex(), ParseDependencyOutputArgs(), ParseFrontendArgs(), ParseHeaderSearchArgs(), parseModuleFileExtensionMetadata(), clang::Preprocessor::ParsePragmaPushOrPopMacro(), parseRangeSelectorImpl(), parseSpecialCaseListArg(), parseTestModuleFileExtensionArg(), percentEncodeURICharacter(), clang::targets::PPC64TargetInfo::PPC64TargetInfo(), PragmaLoopHintString(), clang::driver::Command::Print(), clang::ento::CheckerRegistryData::printCheckerOptionList(), printExplicitSpecifier(), clang::driver::Driver::PrintHelp(), clang::Sema::PrintInstantiationStack(), clang::ento::SVal::printJson(), clang::Stmt::printJson(), printNode(), PrintPreprocessedTokens(), clang::printSourceLocationAsJson(), printTemplateArgs(), clang::CFGBlock::printTerminatorJson(), ProcessCharEscape(), pruneModuleCache(), clang::driver::toolchains::PS4CPU::PS4CPU(), clang::ASTReader::readASTFileControlBlock(), readConstraintSatisfaction(), clang::serialization::reader::HeaderFileInfoTrait::ReadData(), clang::ASTReader::ReadPath(), clang::ASTReader::ReadString(), readSubstitutionDiagnostic(), clang::CodeGen::CGOpenMPRuntime::registerTargetGlobalVariable(), clang::PrintingCallbacks::remapPath(), clang::tooling::AtomicChange::removeHeader(), removeImageAccessQualifier(), RenderDiagnosticsOptions(), RenderModulesOptions(), RenderOpenCLOptions(), renderRemarksOptions(), RenderSSPOptions(), clang::format::replaceCRLF(), clang::tooling::replaceNestedName(), ReplaceWithClasstype(), ReplaceWithInstancetype(), clang::ento::mpi::MPIBugReporter::reportDoubleNonblocking(), clang::CodeGen::SanitizerMetadata::reportGlobalToASan(), clang::ento::mpi::MPIBugReporter::reportMissingWait(), clang::ento::mpi::MPIBugReporter::reportUnmatchedWait(), resolveFileRelativeToOriginalDir(), rewriteInputConstraintReferences(), clang::RewriteMacrosInInput(), rewriteToNSEnumDecl(), rewriteToNSMacroDecl(), rewriteToObjCInterfaceDecl(), rewriteToObjCProperty(), clang::format::rotateTokens(), RoundTrip(), clang::tooling::ReplaceNodeWithTemplate::run(), clang::tooling::ToolInvocation::run(), clang::tooling::ClangTool::run(), clang::ento::CheckerManager::runCheckersForEvalCall(), runWithDiags(), clang::driver::SanitizerArgs::SanitizerArgs(), clang::driver::tools::SDLSearch(), clang::ento::PathDiagnosticCallPiece::setCallStackMessage(), clang::TargetInfo::setCommandLineOpenCLOpts(), clang::LogDiagnosticPrinter::setDwarfDebugFlags(), clang::tooling::AtomicChange::setError(), clang::driver::Driver::setInstalledDir(), clang::HeaderSearch::setModuleCachePath(), clang::HeaderSearch::setModuleHash(), clang::api_notes::CommonTypeInfo::setNSErrorDomain(), clang::Preprocessor::setPredefines(), clang::ast_matchers::dynamic::VariantValue::setString(), clang::api_notes::CommonTypeInfo::setSwiftBridge(), clang::Sema::SetSYCLKernelNames(), shouldDisplayPopUpRange(), clang::CodeGen::CodeGenFunction::ShouldEmitVTableTypeCheckedLoad(), SimplifyConstraint(), clang::TestModuleFileExtension::str(), clang::syntax::Token::str(), stringFromPath(), clang::Lexer::Stringify(), clang::MacroArgs::StringifyArgument(), stripPositionalArgs(), clang::driver::toolchains::TCEToolChain::TCEToolChain(), testTriple(), clang::TestClangConfig::toString(), clang::tooling::Replacement::toString(), clang::ast_matchers::dynamic::Diagnostics::toString(), toString(), clang::ast_matchers::dynamic::Diagnostics::toStringFull(), clang::tooling::AtomicChange::toYAMLString(), clang::driver::toolchains::AMDGPUOpenMPToolChain::TranslateArgs(), TranslateDArg(), clang::BackendConsumer::UnsupportedDiagHandler(), updateModuleTimestamp(), validateSpecialCaseListFormat(), clang::ento::ExprEngine::ViewGraph(), clang::JSONNodeDumper::Visit(), clang::JSONNodeDumper::VisitArrayType(), clang::JSONNodeDumper::VisitElaboratedType(), clang::ento::SValExplainer::VisitElementRegion(), clang::ento::SValExplainer::VisitLocConcreteInt(), clang::ento::SValExplainer::VisitMemRegion(), clang::JSONNodeDumper::VisitNamedDecl(), clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode(), clang::ento::SValExplainer::VisitNonLocConcreteInt(), clang::ento::SValExplainer::VisitNonParamVarRegion(), clang::JSONNodeDumper::VisitObjCBoxedExpr(), clang::JSONNodeDumper::VisitObjCMessageExpr(), clang::JSONNodeDumper::VisitObjCSelectorExpr(), clang::ento::SValExplainer::VisitParamVarRegion(), clang::ASTDeclReader::VisitPragmaCommentDecl(), clang::ASTDeclReader::VisitPragmaDetectMismatchDecl(), clang::JSONNodeDumper::VisitStringLiteral(), clang::ento::SValExplainer::VisitSVal(), clang::JSONNodeDumper::VisitTemplateSpecializationType(), clang::ento::ConditionBRVisitor::VisitTrueTest(), clang::JSONNodeDumper::VisitUsingDecl(), clang::driver::CudaInstallationDetector::WarnIfUnsupportedVersion(), clang::targets::WindowsX86_32TargetInfo::WindowsX86_32TargetInfo(), clang::FixItRewriter::WriteFixedFiles(), WriteJSON(), and clang::driver::XRayArgs::XRayArgs().