clang: lib/Analysis/LiveVariables.cpp File Reference
LiveVariables.cpp File Reference
#include "clang/Analysis/Analyses/LiveVariables.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/Analysis/CFG.h"
#include "clang/Analysis/FlowSensitive/DataflowWorklist.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <optional>
#include <vector>
Functions
static LiveVariablesImpl & getImpl (void *x)
static bool isAlwaysAlive (const VarDecl *D)
static const VariableArrayType * FindVA (QualType Ty)
static const Expr * LookThroughExpr (const Expr *E)
static void AddLiveExpr (llvm::ImmutableSet< const Expr * > &Set, llvm::ImmutableSet< const Expr * >::Factory &F, const Expr *E)
static bool writeShouldKill (const VarDecl *VD)
Function Documentation
AddLiveExpr()
static void AddLiveExpr (llvm::ImmutableSet< const Expr * > & Set, llvm::ImmutableSet< const Expr * >::Factory & F, const Expr * E) static
Definition at line 211 of file LiveVariables.cpp.
References LookThroughExpr(), and clang::Set.
FindVA()
static const VariableArrayType* FindVA (QualType Ty) static
Definition at line 181 of file LiveVariables.cpp.
References clang::QualType::getTypePtr().
getImpl()
static LiveVariablesImpl& getImpl (void * x) static
Definition at line 59 of file LiveVariables.cpp.
Referenced by clang::LiveVariables::dumpBlockLiveness(), clang::LiveVariables::dumpExprLiveness(), clang::LiveVariables::isLive(), and clang::LiveVariables::runOnAllBlocks().
isAlwaysAlive()
static bool isAlwaysAlive (const VarDecl * D) static
Definition at line 137 of file LiveVariables.cpp.
References clang::VarDecl::hasGlobalStorage().
Referenced by clang::LiveVariables::isLive(), and writeShouldKill().
LookThroughExpr()
static const Expr* LookThroughExpr (const Expr * E) static
Definition at line 194 of file LiveVariables.cpp.
References clang::Expr::IgnoreParens().
Referenced by AddLiveExpr().
writeShouldKill()
static bool writeShouldKill (const VarDecl * VD) static
Definition at line 328 of file LiveVariables.cpp.
References clang::ValueDecl::getType(), isAlwaysAlive(), and clang::Type::isReferenceType().