clang: lib/Analysis/MacroExpansionContext.cpp File Reference
MacroExpansionContext.cpp File Reference
#include "clang/Analysis/MacroExpansionContext.h"
#include "llvm/Support/Debug.h"
#include <optional>
Classes
class clang::detail::MacroExpansionRangeRecorder
Namespaces
clang
The JSON file list parser is used to communicate input to InstallAPI.
clang::detail
Macros
#define DEBUG_TYPE "macro-expansion-context"
Functions
static void dumpTokenInto (const clang::Preprocessor &PP, clang::raw_ostream &OS, clang::Token Tok)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "macro-expansion-context"
Definition at line 13 of file MacroExpansionContext.cpp.
Function Documentation
dumpTokenInto()
static void dumpTokenInto (const clang::Preprocessor & PP, clang::raw_ostream & OS, clang::Token Tok) static
Definition at line 177 of file MacroExpansionContext.cpp.
References clang::Token::getIdentifierInfo(), clang::Token::getLength(), clang::Token::getLiteralData(), clang::Preprocessor::getSpelling(), clang::Token::isAnnotation(), clang::Token::isLiteral(), clang::Token::isNot(), and clang::Token::needsCleaning().
Referenced by clang::detail::MacroExpansionRangeRecorder::MacroExpands().