clang: lib/AST/Mangle.cpp File Reference
Mangle.cpp File Reference
#include "clang/AST/Attr.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/VTableBuilder.h"
#include "clang/Basic/ABI.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Mangler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
Classes
class clang::ASTNameGenerator::Implementation
Enumerations
enum CCMangling {
CCM_Other, CCM_Fast, CCM_RegCall, CCM_Vector,
CCM_Std, CCM_WasmMainArgcArgv
}
Functions
static void mangleFunctionBlock (MangleContext &Context, StringRef Outer, const BlockDecl *BD, raw_ostream &Out)
static bool isExternC (const NamedDecl *ND)
static CCMangling getCallingConvMangling (const ASTContext &Context, const NamedDecl *ND)
Enumeration Type Documentation
CCMangling
enum CCMangling
Enumerator
CCM_Other
CCM_Fast
CCM_RegCall
CCM_Vector
CCM_Std
CCM_WasmMainArgcArgv
Definition at line 49 of file Mangle.cpp.
Function Documentation
getCallingConvMangling()
static CCMangling getCallingConvMangling (const ASTContext & Context, const NamedDecl * ND) static
Definition at line 66 of file Mangle.cpp.
References clang::Type::castAs(), clang::CC_X86FastCall, clang::CC_X86StdCall, clang::CC_X86VectorCall, CCM_Fast, CCM_Other, CCM_Std, CCM_Vector, CCM_WasmMainArgcArgv, clang::FunctionType::getCallConv(), clang::TargetInfo::getCXXABI(), clang::ASTContext::getLangOpts(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::ValueDecl::getType(), and isExternC().
Referenced by clang::MangleContext::mangleName(), and clang::MangleContext::shouldMangleDeclName().
isExternC()
static bool isExternC (const NamedDecl * ND) static
Definition at line 58 of file Mangle.cpp.
Referenced by getCallingConvMangling().
mangleFunctionBlock()
static void mangleFunctionBlock (MangleContext & Context, StringRef Outer, const BlockDecl * BD, raw_ostream & Out) static
Definition at line 36 of file Mangle.cpp.
Referenced by clang::MangleContext::mangleBlock(), clang::MangleContext::mangleCtorBlock(), and clang::MangleContext::mangleDtorBlock().