clang: lib/StaticAnalyzer/Checkers/MIGChecker.cpp File Reference
MIGChecker.cpp File Reference
#include "clang/AST/Attr.h"
#include "clang/Analysis/AnyCall.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallDescription.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include <optional>
Macros
#define CALL(required_args, deallocated_arg, ...) {{{__VA_ARGS__}, required_args}, deallocated_arg}
Functions
static const ParmVarDecl * getOriginParam (SVal V, CheckerContext &C, bool IncludeBaseRegions=false)
static bool isInMIGCall (CheckerContext &C)
static bool mayBeSuccess (SVal V, CheckerContext &C)
Macro Definition Documentation
CALL
#define CALL (required_args, deallocated_arg, ...) {{{__VA_ARGS__}, required_args}, deallocated_arg}
Function Documentation
getOriginParam()
static const ParmVarDecl* getOriginParam (SVal V, CheckerContext & C, bool IncludeBaseRegions = false) static
Definition at line 120 of file MIGChecker.cpp.
References clang::ento::SymExpr::getOriginRegion(), clang::ento::SymbolicRegion::getSymbol(), clang::ento::MemRegion::getSymbolicBase(), and V.
isInMIGCall()
static bool isInMIGCall (CheckerContext & C) static
Definition at line 148 of file MIGChecker.cpp.
References clang::LocationContext::getDecl(), clang::LocationContext::getParent(), and clang::LocationContext::getStackFrame().
mayBeSuccess()
static bool mayBeSuccess (SVal V, CheckerContext & C) static
Definition at line 229 of file MIGChecker.cpp.
References clang::ento::SValBuilder::evalEQ(), clang::ASTContext::IntTy, clang::ento::SValBuilder::makeIntVal(), State, and V.