clang: lib/Driver/ToolChains/MinGW.cpp File Reference
MinGW.cpp File Reference
#include "MinGW.h"
#include "CommonArgs.h"
#include "clang/Config/config.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VirtualFileSystem.h"
#include <system_error>
Functions
static bool isCrossCompiling (const llvm::Triple &T, bool RequireArchMatch)
static bool findGccVersion (StringRef LibDir, std::string &GccLibDir, std::string &Ver, toolchains::Generic_GCC::GCCVersion &Version)
static llvm::Triple getLiteralTriple (const Driver &D, const llvm::Triple &T)
static llvm::ErrorOr< std::string > findGcc (const llvm::Triple &LiteralTriple, const llvm::Triple &T)
static llvm::ErrorOr< std::string > findClangRelativeSysroot (const Driver &D, const llvm::Triple &LiteralTriple, const llvm::Triple &T, std::string &SubdirName)
static bool looksLikeMinGWSysroot (const std::string &Directory)
static bool testTriple (const Driver &D, const llvm::Triple &Triple, const ArgList &Args)
static llvm::Triple adjustTriple (const Driver &D, const llvm::Triple &Triple, const ArgList &Args)
Function Documentation
adjustTriple()
static llvm::Triple adjustTriple (const Driver & D, const llvm::Triple & Triple, const ArgList & Args) static
Definition at line 814 of file MinGW.cpp.
References testTriple().
Referenced by clang::driver::toolchains::MinGW::fixTripleArch().
findClangRelativeSysroot()
static llvm::ErrorOr<std::string> findClangRelativeSysroot (const Driver & D, const llvm::Triple & LiteralTriple, const llvm::Triple & T, std::string & SubdirName) static
Definition at line 457 of file MinGW.cpp.
References clang::driver::Driver::Dir, clang::make_error_code(), and clang::T.
Referenced by clang::driver::toolchains::MinGW::MinGW(), and testTriple().
findGcc()
static llvm::ErrorOr<std::string> findGcc (const llvm::Triple & LiteralTriple, const llvm::Triple & T) static
Definition at line 437 of file MinGW.cpp.
References clang::make_error_code(), and clang::T.
Referenced by clang::driver::toolchains::MinGW::MinGW(), and testTriple().
findGccVersion()
static bool findGccVersion (StringRef LibDir, std::string & GccLibDir, std::string & Ver, toolchains::Generic_GCC::GCCVersion & Version) static
Definition at line 382 of file MinGW.cpp.
References clang::interp::LE().
getLiteralTriple()
static llvm::Triple getLiteralTriple (const Driver & D, const llvm::Triple & T) static
Definition at line 403 of file MinGW.cpp.
References clang::driver::Driver::getTargetTriple(), and clang::T.
Referenced by clang::driver::toolchains::MinGW::MinGW(), and testTriple().
isCrossCompiling()
static bool isCrossCompiling (const llvm::Triple & T, bool RequireArchMatch) static
Definition at line 372 of file MinGW.cpp.
References normalize(), and clang::T.
Referenced by clang::driver::toolchains::MinGW::AddClangSystemIncludeArgs().
looksLikeMinGWSysroot()
static bool looksLikeMinGWSysroot (const std::string & Directory) static
Definition at line 477 of file MinGW.cpp.
Referenced by clang::driver::toolchains::MinGW::MinGW(), and testTriple().
testTriple()
static bool testTriple (const Driver & D, const llvm::Triple & Triple, const ArgList & Args) static
Definition at line 791 of file MinGW.cpp.
References clang::driver::Driver::Dir, findClangRelativeSysroot(), findGcc(), getLiteralTriple(), looksLikeMinGWSysroot(), and clang::driver::Driver::SysRoot.
Referenced by adjustTriple().