clang: lib/StaticAnalyzer/Checkers/MoveChecker.cpp File Reference
MoveChecker.cpp File Reference
#include "clang/AST/Attr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "llvm/ADT/StringSet.h"
Namespaces
clang
The JSON file list parser is used to communicate input to InstallAPI.
clang::ento
clang::ento::move
Functions
bool clang::ento::move::isMovedFrom (ProgramStateRef State, const MemRegion *Region)
Returns true if the object is known to have been recently std::moved.
static ProgramStateRef removeFromState (ProgramStateRef State, const MemRegion *Region)
static bool isAnyBaseRegionReported (ProgramStateRef State, const MemRegion *Region)
static const MemRegion * unwrapRValueReferenceIndirection (const MemRegion *MR)
Function Documentation
isAnyBaseRegionReported()
static bool isAnyBaseRegionReported (ProgramStateRef State, const MemRegion * Region) static
Definition at line 255 of file MoveChecker.cpp.
References clang::ento::MemRegion::isSubRegionOf(), and State.
removeFromState()
static ProgramStateRef removeFromState (ProgramStateRef State, const MemRegion * Region) static
Definition at line 244 of file MoveChecker.cpp.
References State.
unwrapRValueReferenceIndirection()
static const MemRegion* unwrapRValueReferenceIndirection (const MemRegion * MR) static
Definition at line 264 of file MoveChecker.cpp.
References clang::ento::SymExpr::getOriginRegion(), clang::ento::SymExpr::getType(), and clang::Type::isRValueReferenceType().