clang: lib/Driver/ToolChains/MSVC.cpp File Reference
MSVC.cpp File Reference
#include "MSVC.h"
#include "CommonArgs.h"
#include "Darwin.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/Version.h"
#include "clang/Config/config.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/VirtualFileSystem.h"
#include <cstdio>
Functions
static bool canExecute (llvm::vfs::FileSystem &VFS, StringRef Path)
static bool getSystemRegistryString (const char *keyPath, const char *valueName, std::string &value, std::string *phValue)
Read registry string.
static std::string getHighestNumericTupleInDirectory (llvm::vfs::FileSystem &VFS, StringRef Directory)
static bool findVCToolChainViaCommandLine (llvm::vfs::FileSystem &VFS, const ArgList &Args, std::string &Path, MSVCToolChain::ToolsetLayout &VSLayout)
static bool findVCToolChainViaEnvironment (llvm::vfs::FileSystem &VFS, std::string &Path, MSVCToolChain::ToolsetLayout &VSLayout)
static bool findVCToolChainViaSetupConfig (llvm::vfs::FileSystem &VFS, std::string &Path, MSVCToolChain::ToolsetLayout &VSLayout)
static bool findVCToolChainViaRegistry (std::string &Path, MSVCToolChain::ToolsetLayout &VSLayout)
static std::string FindVisualStudioExecutable (const ToolChain &TC, const char *Exe)
static const char * llvmArchToWindowsSDKArch (llvm::Triple::ArchType Arch)
static const char * llvmArchToLegacyVCArch (llvm::Triple::ArchType Arch)
static const char * llvmArchToDevDivInternalArch (llvm::Triple::ArchType Arch)
static bool getWindows10SDKVersionFromPath (llvm::vfs::FileSystem &VFS, const std::string &SDKPath, std::string &SDKVersion)
static bool getWindowsSDKDirViaCommandLine (llvm::vfs::FileSystem &VFS, const ArgList &Args, std::string &Path, int &Major, std::string &Version)
static bool getWindowsSDKDir (llvm::vfs::FileSystem &VFS, const ArgList &Args, std::string &Path, int &Major, std::string &WindowsSDKIncludeVersion, std::string &WindowsSDKLibVersion)
Get Windows SDK installation directory.
static bool getUniversalCRTSdkDir (llvm::vfs::FileSystem &VFS, const ArgList &Args, std::string &Path, std::string &UCRTVersion)
static VersionTuple getMSVCVersionFromTriple (const llvm::Triple &Triple)
static VersionTuple getMSVCVersionFromExe (const std::string &BinDir)
static void TranslateOptArg (Arg *A, llvm::opt::DerivedArgList &DAL, bool SupportsForcingFramePointer, const char *ExpandChar, const OptTable &Opts)
static void TranslateDArg (Arg *A, llvm::opt::DerivedArgList &DAL, const OptTable &Opts)
static void TranslatePermissive (Arg *A, llvm::opt::DerivedArgList &DAL, const OptTable &Opts)
static void TranslatePermissiveMinus (Arg *A, llvm::opt::DerivedArgList &DAL, const OptTable &Opts)
Function Documentation
canExecute()
static bool canExecute (llvm::vfs::FileSystem & VFS, StringRef Path) static
Definition at line 66 of file MSVC.cpp.
Referenced by clang::driver::tools::visualstudio::Linker::ConstructJob(), and FindVisualStudioExecutable().
findVCToolChainViaCommandLine()
static bool findVCToolChainViaCommandLine (llvm::vfs::FileSystem & VFS, const ArgList & Args, std::string & Path, MSVCToolChain::ToolsetLayout & VSLayout) static
Definition at line 105 of file MSVC.cpp.
References getHighestNumericTupleInDirectory(), string(), and clang::driver::toolchains::MSVCToolChain::VS2017OrNewer.
Referenced by clang::driver::toolchains::MSVCToolChain::MSVCToolChain().
findVCToolChainViaEnvironment()
static bool findVCToolChainViaEnvironment (llvm::vfs::FileSystem & VFS, std::string & Path, MSVCToolChain::ToolsetLayout & VSLayout) static
Definition at line 133 of file MSVC.cpp.
References clang::driver::toolchains::MSVCToolChain::DevDivInternal, End, clang::driver::toolchains::MSVCToolChain::OlderVS, string(), and clang::driver::toolchains::MSVCToolChain::VS2017OrNewer.
Referenced by clang::driver::toolchains::MSVCToolChain::MSVCToolChain().
findVCToolChainViaRegistry()
static bool findVCToolChainViaRegistry (std::string & Path, MSVCToolChain::ToolsetLayout & VSLayout) static
Definition at line 340 of file MSVC.cpp.
References getSystemRegistryString(), clang::driver::toolchains::MSVCToolChain::OlderVS, and string().
Referenced by clang::driver::toolchains::MSVCToolChain::MSVCToolChain().
findVCToolChainViaSetupConfig()
static bool findVCToolChainViaSetupConfig (llvm::vfs::FileSystem & VFS, std::string & Path, MSVCToolChain::ToolsetLayout & VSLayout) static
Definition at line 248 of file MSVC.cpp.
References string().
Referenced by clang::driver::toolchains::MSVCToolChain::MSVCToolChain().
FindVisualStudioExecutable()
static std::string FindVisualStudioExecutable (const ToolChain & TC, const char * Exe) static
Definition at line 364 of file MSVC.cpp.
References clang::driver::toolchains::MSVCToolChain::Bin, canExecute(), clang::driver::ToolChain::getVFS(), and string().
Referenced by clang::driver::tools::visualstudio::Linker::ConstructJob().
getHighestNumericTupleInDirectory()
static std::string getHighestNumericTupleInDirectory (llvm::vfs::FileSystem & VFS, StringRef Directory) static
Definition at line 78 of file MSVC.cpp.
References string().
Referenced by findVCToolChainViaCommandLine(), getWindows10SDKVersionFromPath(), and getWindowsSDKDirViaCommandLine().
getMSVCVersionFromExe()
static VersionTuple getMSVCVersionFromExe (const std::string & BinDir) static
Definition at line 1260 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::computeMSVCVersion().
getMSVCVersionFromTriple()
static VersionTuple getMSVCVersionFromTriple (const llvm::Triple & Triple) static
Definition at line 1252 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::computeMSVCVersion().
getSystemRegistryString()
static bool getSystemRegistryString (const char * keyPath, const char * valueName, std::string & value, std::string * phValue) static
Read registry string.
This also supports a means to look for high-versioned keys by use of a $VERSION placeholder in the key path. $VERSION in the key path is a placeholder for the version number, causing the highest value path to be searched for and used. I.e. "SOFTWARE\\Microsoft\\VisualStudio\\$VERSION". There can be additional characters in the component. Only the numeric characters are compared. This function only searches HKLM.
Definition at line 973 of file MSVC.cpp.
References clang::isDigit(), NULL, and string().
Referenced by findVCToolChainViaRegistry(), getUniversalCRTSdkDir(), and getWindowsSDKDir().
getUniversalCRTSdkDir()
static bool getUniversalCRTSdkDir (llvm::vfs::FileSystem & VFS, const ArgList & Args, std::string & Path, std::string & UCRTVersion) static
Definition at line 1210 of file MSVC.cpp.
References getSystemRegistryString(), getWindows10SDKVersionFromPath(), and getWindowsSDKDirViaCommandLine().
Referenced by clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), and clang::driver::toolchains::MSVCToolChain::getUniversalCRTLibraryPath().
getWindows10SDKVersionFromPath()
static bool getWindows10SDKVersionFromPath (llvm::vfs::FileSystem & VFS, const std::string & SDKPath, std::string & SDKVersion) static
Definition at line 1064 of file MSVC.cpp.
References getHighestNumericTupleInDirectory().
Referenced by getUniversalCRTSdkDir(), getWindowsSDKDir(), and getWindowsSDKDirViaCommandLine().
getWindowsSDKDir()
static bool getWindowsSDKDir (llvm::vfs::FileSystem & VFS, const ArgList & Args, std::string & Path, int & Major, std::string & WindowsSDKIncludeVersion, std::string & WindowsSDKLibVersion) static
Get Windows SDK installation directory.
Definition at line 1110 of file MSVC.cpp.
References getSystemRegistryString(), getWindows10SDKVersionFromPath(), getWindowsSDKDirViaCommandLine(), and string().
Referenced by clang::driver::toolchains::MSVCToolChain::AddClangSystemIncludeArgs(), and clang::driver::toolchains::MSVCToolChain::getWindowsSDKLibraryPath().
getWindowsSDKDirViaCommandLine()
static bool getWindowsSDKDirViaCommandLine (llvm::vfs::FileSystem & VFS, const ArgList & Args, std::string & Path, int & Major, std::string & Version) static
Definition at line 1073 of file MSVC.cpp.
References getHighestNumericTupleInDirectory(), getWindows10SDKVersionFromPath(), and string().
Referenced by getUniversalCRTSdkDir(), and getWindowsSDKDir().
llvmArchToDevDivInternalArch()
static const char* llvmArchToDevDivInternalArch (llvm::Triple::ArchType Arch) static
Definition at line 865 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::getSubDirectoryPath().
llvmArchToLegacyVCArch()
static const char* llvmArchToLegacyVCArch (llvm::Triple::ArchType Arch) static
Definition at line 846 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::getSubDirectoryPath().
llvmArchToWindowsSDKArch()
static const char* llvmArchToWindowsSDKArch (llvm::Triple::ArchType Arch) static
Definition at line 829 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::getSubDirectoryPath(), clang::driver::toolchains::MSVCToolChain::getUniversalCRTLibraryPath(), and clang::driver::toolchains::MSVCToolChain::getWindowsSDKLibraryPath().
TranslateDArg()
static void TranslateDArg (Arg * A, llvm::opt::DerivedArgList & DAL, const OptTable & Opts) static
Definition at line 1549 of file MSVC.cpp.
References string().
Referenced by clang::driver::toolchains::MSVCToolChain::TranslateArgs().
TranslateOptArg()
static void TranslateOptArg (Arg * A, llvm::opt::DerivedArgList & DAL, bool SupportsForcingFramePointer, const char * ExpandChar, const OptTable & Opts) static
Definition at line 1453 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::TranslateArgs().
TranslatePermissive()
static void TranslatePermissive (Arg * A, llvm::opt::DerivedArgList & DAL, const OptTable & Opts) static
Definition at line 1565 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::TranslateArgs().
TranslatePermissiveMinus()
static void TranslatePermissiveMinus (Arg * A, llvm::opt::DerivedArgList & DAL, const OptTable & Opts) static
Definition at line 1572 of file MSVC.cpp.
Referenced by clang::driver::toolchains::MSVCToolChain::TranslateArgs().