clang: lib/Driver/MultilibBuilder.cpp File Reference
MultilibBuilder.cpp File Reference
#include "clang/Driver/MultilibBuilder.h"
#include "ToolChains/CommonArgs.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void normalizePathSegment (std::string &Segment)
normalize Segment to "/foo/bar" or "".
static MultilibBuilder compose (const MultilibBuilder &Base, const MultilibBuilder &New)
Function Documentation
compose()
static MultilibBuilder compose (const MultilibBuilder & Base, const MultilibBuilder & New) static
Definition at line 134 of file MultilibBuilder.cpp.
References clang::driver::MultilibBuilder::flags(), clang::driver::MultilibBuilder::gccSuffix(), clang::driver::MultilibBuilder::includeSuffix(), and clang::driver::MultilibBuilder::osSuffix().
Referenced by clang::driver::MultilibSetBuilder::Either().
normalizePathSegment()
static void normalizePathSegment (std::string & Segment) static
normalize Segment to "/foo/bar" or "".
Definition at line 21 of file MultilibBuilder.cpp.
Referenced by clang::driver::MultilibBuilder::MultilibBuilder().