clang: clang::edit Namespace Reference
clang::edit Namespace Reference
Classes
class Commit
class EditedSource
class EditsReceiver
class FileOffset
Functions
bool rewriteObjCRedundantCallWithLiteral (const ObjCMessageExpr *Msg, const NSAPI &NS, Commit &commit)
bool rewriteToObjCLiteralSyntax (const ObjCMessageExpr *Msg, const NSAPI &NS, Commit &commit, const ParentMap *PMap)
bool rewriteToObjCSubscriptSyntax (const ObjCMessageExpr *Msg, const NSAPI &NS, Commit &commit)
Function Documentation
rewriteObjCRedundantCallWithLiteral()
bool clang::edit::rewriteObjCRedundantCallWithLiteral (const ObjCMessageExpr * Msg, const NSAPI & NS, Commit & commit)
Definition at line 58 of file RewriteObjCFoundationAPI.cpp.
References checkForLiteralCreation(), clang::NSAPI::ClassId_NSArray, clang::NSAPI::ClassId_NSDictionary, clang::NSAPI::ClassId_NSString, clang::ObjCMessageExpr::getArg(), clang::NSAPI::getASTContext(), clang::ASTContext::getLangOpts(), clang::NSAPI::getNSArraySelector(), clang::NSAPI::getNSClassId(), clang::NSAPI::getNSDictionarySelector(), clang::NSAPI::getNSStringSelector(), clang::ObjCMessageExpr::getNumArgs(), clang::ObjCMessageExpr::getSelector(), clang::Stmt::getSourceRange(), clang::Expr::IgnoreParenImpCasts(), clang::NSAPI::NSArr_arrayWithArray, clang::NSAPI::NSArr_initWithArray, clang::NSAPI::NSDict_dictionaryWithDictionary, clang::NSAPI::NSDict_initWithDictionary, clang::NSAPI::NSStr_initWithString, clang::NSAPI::NSStr_stringWithString, and clang::edit::Commit::replaceWithInner().
rewriteToObjCLiteralSyntax()
bool clang::edit::rewriteToObjCLiteralSyntax (const ObjCMessageExpr * Msg, const NSAPI & NS, Commit & commit, const ParentMap * PMap)
Definition at line 338 of file RewriteObjCFoundationAPI.cpp.
References checkForLiteralCreation(), clang::NSAPI::ClassId_NSArray, clang::NSAPI::ClassId_NSDictionary, clang::NSAPI::ClassId_NSNumber, clang::NSAPI::ClassId_NSString, clang::NSAPI::getASTContext(), clang::ASTContext::getLangOpts(), clang::NSAPI::getNSClassId(), rewriteToArrayLiteral(), rewriteToDictionaryLiteral(), rewriteToNumberLiteral(), and rewriteToStringBoxedExpression().
rewriteToObjCSubscriptSyntax()
bool clang::edit::rewriteToObjCSubscriptSyntax (const ObjCMessageExpr * Msg, const NSAPI & NS, Commit & commit)
Definition at line 289 of file RewriteObjCFoundationAPI.cpp.
References clang::NSAPI::getASTContext(), clang::ObjCMessageExpr::getMethodDecl(), clang::NSAPI::getNSArraySelector(), clang::NSAPI::getNSDictionarySelector(), clang::ObjCMessageExpr::getNumArgs(), clang::ASTContext::getObjContainingInterface(), clang::ObjCMessageExpr::getReceiverKind(), clang::ObjCMessageExpr::getSelector(), clang::ObjCMessageExpr::Instance, clang::ObjCMessageExpr::isImplicit(), clang::NSAPI::NSArr_objectAtIndex, clang::NSAPI::NSDict_objectForKey, clang::NSAPI::NSMutableArr_replaceObjectAtIndex, clang::NSAPI::NSMutableDict_setObjectForKey, rewriteToArraySubscriptGet(), rewriteToArraySubscriptSet(), rewriteToDictionarySubscriptGet(), and rewriteToDictionarySubscriptSet().