clang: clang::ento::checker_registry Namespace Reference
clang::ento::checker_registry Namespace Reference
Classes
struct FullNameLT
Typedefs
using PackageNameLT = FullNameLT< PackageInfo >
using CheckerNameLT = FullNameLT< CheckerInfo >
Functions
template<class CheckerOrPackageInfoList >
std::conditional_t< std::is_const< CheckerOrPackageInfoList >::value, typename CheckerOrPackageInfoList::const_iterator, typename CheckerOrPackageInfoList::iterator > binaryFind (CheckerOrPackageInfoList &Collection, StringRef FullName)
Typedef Documentation
CheckerNameLT
using clang::ento::checker_registry::CheckerNameLT = typedef FullNameLT<CheckerInfo>
Definition at line 173 of file CheckerRegistryData.h.
PackageNameLT
using clang::ento::checker_registry::PackageNameLT = typedef FullNameLT<PackageInfo>
Definition at line 172 of file CheckerRegistryData.h.
Function Documentation
binaryFind()
template<class CheckerOrPackageInfoList > std::conditional_t<std::is_const<CheckerOrPackageInfoList>::value, typename CheckerOrPackageInfoList::const_iterator, typename CheckerOrPackageInfoList::iterator> clang::ento::checker_registry::binaryFind (CheckerOrPackageInfoList & Collection, StringRef FullName)
Definition at line 179 of file CheckerRegistryData.h.
Referenced by clang::ento::CheckerRegistryData::getMutableCheckersForCmdLineArg(), insertOptionToCollection(), and clang::ento::CheckerRegistry::resolveDependencies().