clang: clang::internal Namespace Reference
clang::internal Namespace Reference
Classes
struct CFGIntervalNode
Typedefs
using CFGIntervalGraph = std::deque< CFGIntervalNode >
Functions
std::vector< const CFGBlock * > buildInterval (const CFGBlock *Header)
CFGIntervalGraph partitionIntoIntervals (const CFG &Cfg)
CFGIntervalGraph partitionIntoIntervals (const CFGIntervalGraph &Graph)
bool anyConflict (const llvm::SmallVectorImpl< FixItHint > &FixIts, const SourceManager &SM)
static unsigned getID (const CFGBlock &B)
static unsigned getID (const CFGIntervalNode &I)
template<typename Node >
BuildResult< Node > buildInterval (llvm::BitVector &Partitioned, const Node *Header)
template<typename Node >
void fillIntervalNode (CFGIntervalGraph &Graph, std::vector< CFGIntervalNode * > &Index, std::queue< const Node * > &Successors, llvm::BitVector &Partitioned, const Node *Header)
template<typename Node >
CFGIntervalGraph partitionIntoIntervalsImpl (unsigned NumBlockIDs, const Node *EntryBlock)
Typedef Documentation
CFGIntervalGraph
using clang::internal::CFGIntervalGraph = typedef std::deque<CFGIntervalNode>
Definition at line 108 of file IntervalPartition.h.
Function Documentation
anyConflict()
bool clang::internal::anyConflict (const llvm::SmallVectorImpl< FixItHint > & FixIts, const SourceManager & SM)
Definition at line 1495 of file UnsafeBufferUsage.cpp.
References clang::CharSourceRange::getEnd(), clang::FixItHint::RemoveRange, and SM.
buildInterval() [1/2]
std::vector< const CFGBlock * > clang::internal::buildInterval (const CFGBlock * Header)
Definition at line 199 of file IntervalPartition.cpp.
References clang::CFG::getNumBlockIDs(), and clang::CFGBlock::getParent().
buildInterval() [2/2]
template<typename Node > BuildResult<Node> clang::internal::buildInterval (llvm::BitVector & Partitioned, const Node * Header)
Definition at line 39 of file IntervalPartition.cpp.
References getID(), Node, and clang::BuildResult< Node >::Nodes.
fillIntervalNode()
template<typename Node > void clang::internal::fillIntervalNode (CFGIntervalGraph & Graph, std::vector< CFGIntervalNode * > & Index, std::queue< const Node * > & Successors, llvm::BitVector & Partitioned, const Node * Header)
Definition at line 105 of file IntervalPartition.cpp.
getID() [1/2]
static unsigned clang::internal::getID (const CFGBlock & B) static
Definition at line 34 of file IntervalPartition.cpp.
References clang::CFGBlock::getBlockID().
Referenced by buildInterval().
getID() [2/2]
static unsigned clang::internal::getID (const CFGIntervalNode & I) static
Definition at line 35 of file IntervalPartition.cpp.
References clang::internal::CFGIntervalNode::ID.
partitionIntoIntervals() [1/2]
CFGIntervalGraph clang::internal::partitionIntoIntervals (const CFG & Cfg)
Definition at line 204 of file IntervalPartition.cpp.
References clang::CFG::getEntry(), clang::CFG::getNumBlockIDs(), and partitionIntoIntervalsImpl().
Referenced by clang::getIntervalWTO().
partitionIntoIntervals() [2/2]
CFGIntervalGraph clang::internal::partitionIntoIntervals (const CFGIntervalGraph & Graph)
Definition at line 208 of file IntervalPartition.cpp.
References partitionIntoIntervalsImpl().
partitionIntoIntervalsImpl()
template<typename Node > CFGIntervalGraph clang::internal::partitionIntoIntervalsImpl (unsigned NumBlockIDs, const Node * EntryBlock)
Definition at line 141 of file IntervalPartition.cpp.
Referenced by partitionIntoIntervals().