clang: clang::driver::tools::SYCL::gen Namespace Reference
clang::driver::tools::SYCL::gen Namespace Reference
Classes
class BackendCompiler
Functions
StringRef resolveGenDevice (StringRef DeviceName)
SmallString< 64 > getGenDeviceMacro (StringRef DeviceName)
StringRef getGenGRFFlag (StringRef GRFMode)
template<auto GPUArh>
std::optional< StringRef > isGPUTarget (StringRef Target)
Variables
constexpr char IntelGPU [] = "intel_gpu_"
constexpr char NvidiaGPU [] = "nvidia_gpu_"
constexpr char AmdGPU [] = "amd_gpu_"
Function Documentation
getGenDeviceMacro()
SmallString< 64 > clang::driver::tools::SYCL::gen::getGenDeviceMacro (StringRef DeviceName)
Definition at line 1001 of file SYCL.cpp.
Referenced by clang::driver::tools::Clang::ConstructJob().
getGenGRFFlag()
StringRef clang::driver::tools::SYCL::gen::getGenGRFFlag (StringRef GRFMode)
Definition at line 857 of file SYCL.cpp.
References GRFModeFlagMap.
Referenced by clang::driver::toolchains::SYCLToolChain::AddImpliedTargetArgs().
isGPUTarget()
template<auto GPUArh> std::optional<StringRef> clang::driver::tools::SYCL::gen::isGPUTarget (StringRef Target)
Definition at line 125 of file SYCL.h.
References resolveGenDevice().
resolveGenDevice()
StringRef clang::driver::tools::SYCL::gen::resolveGenDevice (StringRef DeviceName)
Definition at line 907 of file SYCL.cpp.
References clang::Device.
Referenced by isGPUTarget(), and clang::driver::toolchains::SYCLToolChain::TranslateTargetOpt().
Variable Documentation
AmdGPU
constexpr char clang::driver::tools::SYCL::gen::AmdGPU[] = "amd_gpu_" constexpr
Definition at line 123 of file SYCL.h.
IntelGPU
constexpr char clang::driver::tools::SYCL::gen::IntelGPU[] = "intel_gpu_" constexpr
Definition at line 121 of file SYCL.h.
NvidiaGPU
constexpr char clang::driver::tools::SYCL::gen::NvidiaGPU[] = "nvidia_gpu_" constexpr
Definition at line 122 of file SYCL.h.