clang: clang::tooling::fixit::internal Namespace Reference
clang::tooling::fixit::internal Namespace Reference
Functions
StringRef getText (CharSourceRange Range, const ASTContext &Context)
CharSourceRange getSourceRange (const SourceRange &Range)
Returns the token CharSourceRange corresponding to Range.
CharSourceRange getSourceRange (const SourceLocation &Loc)
Returns the CharSourceRange of the token at Location Loc.
template<typename T >
CharSourceRange getSourceRange (const T &Node)
Returns the CharSourceRange of an given Node.
Function Documentation
getSourceRange() [1/3]
CharSourceRange clang::tooling::fixit::internal::getSourceRange (const SourceLocation & Loc) inline
Returns the CharSourceRange of the token at Location Loc.
Definition at line 37 of file FixIt.h.
References clang::CharSourceRange::getTokenRange().
getSourceRange() [2/3]
CharSourceRange clang::tooling::fixit::internal::getSourceRange (const SourceRange & Range) inline
Returns the token CharSourceRange corresponding to Range.
Definition at line 32 of file FixIt.h.
References clang::CharSourceRange::getTokenRange().
Referenced by clang::Sema::CreateOverloadedArraySubscriptExpr(), clang::Sema::CreateOverloadedBinOp(), clang::tooling::fixit::createRemoval(), clang::tooling::fixit::createReplacement(), DiagnoseBaseOrMemInitializerOrder(), clang::TypeOfExprTypeLoc::getLocalSourceRange(), and clang::TemplateArgumentLoc::getLocation().
getSourceRange() [3/3]
template<typename T > CharSourceRange clang::tooling::fixit::internal::getSourceRange (const T & Node)
Returns the CharSourceRange of an given Node.
Node is typically a 'Stmt', 'Expr' or a 'Decl'.
Definition at line 43 of file FixIt.h.
References clang::CharSourceRange::getTokenRange(), and Node.
getText()
StringRef clang::tooling::fixit::internal::getText (CharSourceRange Range, const ASTContext & Context)
Definition at line 21 of file FixIt.cpp.