clang: clang::ento::tagged_union_modeling Namespace Reference
clang::ento::tagged_union_modeling Namespace Reference
Functions
const CXXConstructorDecl * getConstructorDeclarationForCall (const CallEvent &Call)
bool isCopyConstructorCall (const CallEvent &Call)
bool isCopyAssignmentCall (const CallEvent &Call)
bool isMoveConstructorCall (const CallEvent &Call)
bool isMoveAssignmentCall (const CallEvent &Call)
bool isStdType (const Type *Type, llvm::StringRef TypeName)
bool isStdVariant (const Type *Type)
bool isStdType (const Type *Type, const std::string &TypeName)
template<class TypeMap >
ProgramStateRef removeInformationStoredForDeadInstances (const CallEvent &Call, ProgramStateRef State, ArrayRef< const MemRegion * > Regions)
template<class TypeMap >
void handleConstructorAndAssignment (const CallEvent &Call, CheckerContext &C, SVal ThisSVal)
Function Documentation
getConstructorDeclarationForCall()
const CXXConstructorDecl* clang::ento::tagged_union_modeling::getConstructorDeclarationForCall (const CallEvent & Call)
Definition at line 35 of file StdVariantChecker.cpp.
Referenced by isCopyConstructorCall(), and isMoveConstructorCall().
handleConstructorAndAssignment()
template<class TypeMap > void clang::ento::tagged_union_modeling::handleConstructorAndAssignment (const CallEvent & Call, CheckerContext & C, SVal ThisSVal)
Definition at line 53 of file TaggedUnionModeling.h.
References clang::ento::SVal::getAsRegion(), clang::Type::getPointeeType(), isCopyAssignmentCall(), isCopyConstructorCall(), isMoveAssignmentCall(), isMoveConstructorCall(), and State.
isCopyAssignmentCall()
bool clang::ento::tagged_union_modeling::isCopyAssignmentCall (const CallEvent & Call)
Definition at line 50 of file StdVariantChecker.cpp.
Referenced by handleConstructorAndAssignment().
isCopyConstructorCall()
bool clang::ento::tagged_union_modeling::isCopyConstructorCall (const CallEvent & Call)
Definition at line 43 of file StdVariantChecker.cpp.
References getConstructorDeclarationForCall().
Referenced by handleConstructorAndAssignment().
isMoveAssignmentCall()
bool clang::ento::tagged_union_modeling::isMoveAssignmentCall (const CallEvent & Call)
Definition at line 68 of file StdVariantChecker.cpp.
Referenced by handleConstructorAndAssignment().
isMoveConstructorCall()
bool clang::ento::tagged_union_modeling::isMoveConstructorCall (const CallEvent & Call)
Definition at line 59 of file StdVariantChecker.cpp.
References getConstructorDeclarationForCall(), and clang::CXXConstructorDecl::isMoveConstructor().
Referenced by handleConstructorAndAssignment().
isStdType() [1/2]
bool clang::ento::tagged_union_modeling::isStdType (const Type * Type, const std::string & TypeName)
isStdType() [2/2]
bool clang::ento::tagged_union_modeling::isStdType (const Type * Type, llvm::StringRef TypeName)
Definition at line 79 of file StdVariantChecker.cpp.
References clang::Type::getAsRecordDecl(), clang::Decl::isInStdNamespace(), and clang::TypeName.
Referenced by isStdVariant().
isStdVariant()
bool clang::ento::tagged_union_modeling::isStdVariant (const Type * Type)
Definition at line 86 of file StdVariantChecker.cpp.
References isStdType().
removeInformationStoredForDeadInstances()
template<class TypeMap > ProgramStateRef clang::ento::tagged_union_modeling::removeInformationStoredForDeadInstances (const CallEvent & Call, ProgramStateRef State, ArrayRef< const MemRegion * > Regions)
Definition at line 37 of file TaggedUnionModeling.h.
References State.