clang: std Namespace Reference
std Namespace Reference
Classes
struct is_error_code_enum< clang::BuildPreambleError >
struct is_error_code_enum< clang::format::ParseError >
struct is_error_code_enum< clang::serialized_diags::SDError >
Functions
template<class _Tp >
__DEVICE__ _Tp abs (const std::complex< _Tp > &__c)
template<class _Tp >
__DEVICE__ _Tp arg (const std::complex< _Tp > &__c)
template<class _Tp >
enable_if< is_integral< _Tp >::value||is_same< _Tp, double >::value, double >::type arg (_Tp __re)
template<class _Tp >
enable_if< is_same< _Tp, float >::value, float >::type arg (_Tp __re)
template<class _Tp >
__DEVICE__ _Tp norm (const std::complex< _Tp > &__c)
template<class _Tp >
std::complex< _Tp > conj (const std::complex< _Tp > &__c)
template<class _Tp >
std::complex< _Tp > proj (const std::complex< _Tp > &__c)
template<class _Tp >
complex< _Tp > polar (const _Tp &__rho, const _Tp &__theta=_Tp())
template<class _Tp >
std::complex< _Tp > log (const std::complex< _Tp > &__x)
template<class _Tp >
std::complex< _Tp > log10 (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > sqrt (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > exp (const std::complex< _Tp > &__x)
template<class _Tp >
std::complex< _Tp > pow (const std::complex< _Tp > &__x, const std::complex< _Tp > &__y)
template<class _Tp >
std::complex< _Tp > __sqr (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > asinh (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > acosh (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > atanh (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > sinh (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > cosh (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > tanh (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > asin (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > acos (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > atan (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > sin (const std::complex< _Tp > &__x)
template<class _Tp >
std::complex< _Tp > cos (const std::complex< _Tp > &__x)
template<class _Tp >
__DEVICE__ std::complex< _Tp > tan (const std::complex< _Tp > &__x)
Function Documentation
__sqr()
template<class _Tp > std::complex<_Tp> std::__sqr (const std::complex< _Tp > & __x)
Definition at line 165 of file complex_cmath.h.
References __x.
Referenced by acos(), acosh(), and asinh().
abs()
template<class _Tp > __DEVICE__ _Tp std::abs (const std::complex< _Tp > & __c)
Definition at line 34 of file complex_cmath.h.
References __c, and hypot.
Referenced by acos(), acosh(), atanh(), cosh(), clang::isStackNearlyExhausted(), log(), norm(), and sqrt().
acos()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::acos (const std::complex< _Tp > & __x)
Definition at line 325 of file complex_cmath.h.
References __sqr(), __x, abs(), atan2, isinf(), isnan(), log(), signbit(), and sqrt().
acosh()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::acosh (const std::complex< _Tp > & __x)
Definition at line 202 of file complex_cmath.h.
References __sqr(), __x, abs(), atan2, copysign, isinf(), isnan(), log(), and sqrt().
arg() [1/3]
template<class _Tp > enable_if<is_integral<_Tp>::value || is_same<_Tp, double>::value, double>::type std::arg (_Tp __re)
Definition at line 47 of file complex_cmath.h.
References atan2.
arg() [2/3]
template<class _Tp > enable_if<is_same<_Tp, float>::value, float>::type std::arg (_Tp __re)
Definition at line 52 of file complex_cmath.h.
References atan2f().
arg() [3/3]
template<class _Tp > __DEVICE__ _Tp std::arg (const std::complex< _Tp > & __c)
Definition at line 40 of file complex_cmath.h.
References __c, and atan2.
Referenced by clang::CodeGen::CGCXXABI::addImplicitConstructorArgs(), arrangeFreeFunctionLikeCall(), clang::Sema::CheckMessageArgumentTypes(), clang::Sema::checkUnknownAnyArg(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::Sema::GatherArgumentsForCall(), clang::CodeGen::CodeGenFunction::generateObjCSetterBody(), getArgTypesForCall(), getArgTypesForDeclaration(), clang::CodeGen::getImplicitCXXConstructorArgs(), log(), clang::CodeGen::CodeGenFunction::setBlockContextParameter(), clang::ParmVarDecl::setUninstantiatedDefaultArg(), sqrt(), and tryGenerateSpecializedMessageSend().
asin()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::asin (const std::complex< _Tp > & __x)
Definition at line 317 of file complex_cmath.h.
References __x, and asinh().
asinh()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::asinh (const std::complex< _Tp > & __x)
Definition at line 174 of file complex_cmath.h.
References __sqr(), __x, atan2, copysign, isinf(), isnan(), log(), and sqrt().
Referenced by asin().
atan()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::atan (const std::complex< _Tp > & __x)
Definition at line 359 of file complex_cmath.h.
References __x, and atanh().
atanh()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::atanh (const std::complex< _Tp > & __x)
Definition at line 235 of file complex_cmath.h.
References __x, abs(), atan2, copysign, INFINITY, isinf(), isnan(), and log().
Referenced by atan().
conj()
template<class _Tp > std::complex<_Tp> std::conj (const std::complex< _Tp > & __c)
Definition at line 68 of file complex_cmath.h.
References __c.
cos()
template<class _Tp > std::complex<_Tp> std::cos (const std::complex< _Tp > & __x)
Definition at line 374 of file complex_cmath.h.
References __x, and cosh().
Referenced by cosh(), exp(), polar(), sinh(), and tanh().
cosh()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::cosh (const std::complex< _Tp > & __x)
Definition at line 279 of file complex_cmath.h.
References __x, abs(), cos(), isfinite(), isinf(), NAN, sin(), and sinh().
Referenced by cos(), sinh(), and tanh().
exp()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::exp (const std::complex< _Tp > & __x)
Definition at line 138 of file complex_cmath.h.
References __x, cos(), isfinite(), isinf(), isnan(), NAN, and sin().
Referenced by pow().
log()
template<class _Tp > std::complex<_Tp> std::log (const std::complex< _Tp > & __x)
Definition at line 108 of file complex_cmath.h.
References __x, abs(), and arg().
Referenced by acos(), acosh(), asinh(), atanh(), log10(), and pow().
log10()
template<class _Tp > std::complex<_Tp> std::log10 (const std::complex< _Tp > & __x)
Definition at line 114 of file complex_cmath.h.
References __x, and log().
norm()
template<class _Tp > __DEVICE__ _Tp std::norm (const std::complex< _Tp > & __c)
Definition at line 58 of file complex_cmath.h.
References __c, abs(), and isinf().
polar()
template<class _Tp > complex<_Tp> std::polar (const _Tp & __rho, const _Tp & __theta = _Tp())
Definition at line 84 of file complex_cmath.h.
References __x, __y, cos(), isinf(), isnan(), NAN, signbit(), and sin().
Referenced by sqrt().
pow()
template<class _Tp > std::complex<_Tp> std::pow (const std::complex< _Tp > & __x, const std::complex< _Tp > & __y)
Definition at line 158 of file complex_cmath.h.
References __x, __y, exp(), and log().
proj()
template<class _Tp > std::complex<_Tp> std::proj (const std::complex< _Tp > & __c)
Definition at line 74 of file complex_cmath.h.
References __c, copysign, INFINITY, and isinf().
sin()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::sin (const std::complex< _Tp > & __x)
Definition at line 367 of file complex_cmath.h.
References __x, and sinh().
Referenced by cosh(), exp(), polar(), sinh(), and tanh().
sinh()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::sinh (const std::complex< _Tp > & __x)
Definition at line 265 of file complex_cmath.h.
References __x, cos(), cosh(), isfinite(), isinf(), NAN, and sin().
Referenced by cosh(), sin(), and tanh().
sqrt()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::sqrt (const std::complex< _Tp > & __x)
Definition at line 121 of file complex_cmath.h.
References __x, abs(), arg(), copysign, INFINITY, isinf(), isnan(), and polar().
Referenced by acos(), acosh(), and asinh().
tan()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::tan (const std::complex< _Tp > & __x)
Definition at line 381 of file complex_cmath.h.
References __x, and tanh().
tanh()
template<class _Tp > __DEVICE__ std::complex<_Tp> std::tanh (const std::complex< _Tp > & __x)
Definition at line 295 of file complex_cmath.h.
References __x, copysign, cos(), cosh(), isfinite(), isinf(), isnan(), sin(), and sinh().
Referenced by tan().