clang: clang::driver::tools Namespace Reference
clang::driver::tools Namespace Reference
Namespaces
aarch64
aix
Directly call system default assembler and linker.
AMDGCN
amdgpu
arm
AVR
baremetal
CrossWindows
csky
CSKY
darwin
dragonfly
Directly call GNU Binutils assembler and linker.
freebsd
Directly call GNU Binutils assembler and linker.
fuchsia
gcc
gcc - Generic GCC tool implementations.
gnutools
Directly call GNU Binutils' assembler and linker.
haiku
Directly call GNU Binutils assembler and linker.
hexagon
HIP
HIPSPV
hlsl
ifstool
loongarch
m68k
MinGW
Directly call GNU Binutils assembler and linker.
mips
msp430
nacltools
netbsd
Directly call GNU Binutils assembler and linker.
NVPTX
openbsd
Directly call GNU Binutils assembler and linker.
ppc
PScpu
riscv
RISCV
solaris
Directly call Solaris assembler and linker.
sparc
SPIRV
SYCL
systemz
ve
visualstudio
Visual studio tools.
wasm
x86
XCore
zos
Directly call system default assembler and linker.
Classes
class Clang
Clang compiler tool.
class ClangAs
Clang integrated assembler tool.
class OffloadBundler
Offload bundler tool.
class OffloadWrapper
Offload wrapper tool.
class OffloadPackager
Offload binary tool.
class OffloadDeps
Offload deps tool.
class SPIRVTranslator
SPIR-V translator tool.
class SYCLPostLink
SYCL post-link device code processing tool.
class FileTableTform
File table transformation tool.
class AppendFooter
Append Footer tool.
class SpirvToIrWrapper
SPIR-V to LLVM-IR wrapper tool.
class LinkerWrapper
Linker wrapper tool.
class Flang
Flang compiler tool.
Enumerations
enum class DwarfFissionKind { None , Split , Single }
Functions
DwarfFissionKind getDebugFissionKind (const Driver &D, const llvm::opt::ArgList &Args, llvm::opt::Arg *&Arg)
llvm::SmallString< 256 > getCXX20NamedModuleOutputPath (const llvm::opt::ArgList &Args, const char *BaseInput)
void addPathIfExists (const Driver &D, const Twine &Path, ToolChain::path_list &Paths)
void AddLinkerInputs (const ToolChain &TC, const InputInfoList &Inputs, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const JobAction &JA)
void addLinkerCompressDebugSectionsOption (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void claimNoWarnArgs (const llvm::opt::ArgList &Args)
bool addSanitizerRuntimes (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void linkSanitizerRuntimeDeps (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
bool addXRayRuntime (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void linkXRayRuntimeDeps (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void AddRunTimeLibs (const ToolChain &TC, const Driver &D, llvm::opt::ArgStringList &CmdArgs, const llvm::opt::ArgList &Args)
void AddStaticDeviceLibsLinking (Compilation &C, const Tool &T, const JobAction &JA, const InputInfoList &Inputs, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL)
void AddStaticDeviceLibsPostLinking (const Driver &D, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
void AddStaticDeviceLibs (Compilation *C, const Tool *T, const JobAction *JA, const InputInfoList *Inputs, const Driver &D, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL)
const char * SplitDebugName (const JobAction &JA, const llvm::opt::ArgList &Args, const InputInfo &Input, const InputInfo &Output)
void SplitDebugInfo (const ToolChain &TC, Compilation &C, const Tool &T, const JobAction &JA, const llvm::opt::ArgList &Args, const InputInfo &Output, const char *OutFile)
void addLTOOptions (const ToolChain &ToolChain, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const InputInfo &Output, const InputInfo &Input, bool IsThinLTO)
const char * RelocationModelName (llvm::Reloc::Model Model)
std::tuple< llvm::Reloc::Model, unsigned, bool > ParsePICArgs (const ToolChain &ToolChain, const llvm::opt::ArgList &Args)
unsigned ParseFunctionAlignment (const ToolChain &TC, const llvm::opt::ArgList &Args)
void addDebugInfoKind (llvm::opt::ArgStringList &CmdArgs, llvm::codegenoptions::DebugInfoKind DebugInfoKind)
llvm::codegenoptions::DebugInfoKind debugLevelToInfoKind (const llvm::opt::Arg &A)
unsigned DwarfVersionNum (StringRef ArgValue)
const llvm::opt::Arg * getDwarfNArg (const llvm::opt::ArgList &Args)
unsigned getDwarfVersion (const ToolChain &TC, const llvm::opt::ArgList &Args)
void AddAssemblerKPIC (const ToolChain &ToolChain, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void addArchSpecificRPath (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void addOpenMPRuntimeLibraryPath (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
bool addOpenMPRuntime (const Compilation &C, llvm::opt::ArgStringList &CmdArgs, const ToolChain &TC, const llvm::opt::ArgList &Args, bool ForceStaticHostRuntime=false, bool IsOffloadingHost=false, bool GompNeedsRT=false)
Returns true, if an OpenMP runtime has been added.
void addFortranRuntimeLibs (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
Adds Fortran runtime libraries to CmdArgs.
void addFortranRuntimeLibraryPath (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
Adds the path for the Fortran runtime libraries to CmdArgs.
void addHIPRuntimeLibArgs (const ToolChain &TC, Compilation &C, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
void addAsNeededOption (const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, bool as_needed)
llvm::opt::Arg * getLastCSProfileGenerateArg (const llvm::opt::ArgList &Args)
llvm::opt::Arg * getLastProfileUseArg (const llvm::opt::ArgList &Args)
llvm::opt::Arg * getLastProfileSampleUseArg (const llvm::opt::ArgList &Args)
bool isObjCAutoRefCount (const llvm::opt::ArgList &Args)
llvm::StringRef getLTOParallelism (const llvm::opt::ArgList &Args, const Driver &D)
bool areOptimizationsEnabled (const llvm::opt::ArgList &Args)
bool isDependentLibAdded (const llvm::opt::ArgList &Args, StringRef Lib)
bool isUseSeparateSections (const llvm::Triple &Triple)
bool isTLSDESCEnabled (const ToolChain &TC, const llvm::opt::ArgList &Args)
void addDirectoryList (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const char *ArgName, const char *EnvVar)
EnvVar is split by system delimiter for environment variables.
void AddTargetFeature (const llvm::opt::ArgList &Args, std::vector< StringRef > &Features, llvm::opt::OptSpecifier OnOpt, llvm::opt::OptSpecifier OffOpt, StringRef FeatureName)
std::string getCPUName (const Driver &D, const llvm::opt::ArgList &Args, const llvm::Triple &T, bool FromAs=false)
void getTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, bool ForAS, bool IsAux=false)
void handleTargetFeaturesGroup (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, std::vector< StringRef > &Features, llvm::opt::OptSpecifier Group)
Iterate Args and convert -mxxx to +xxx and -mno-xxx to -xxx and append it to Features.
SmallVector< StringRef > unifyTargetFeatures (ArrayRef< StringRef > Features)
If there are multiple +xxx or -xxx features, keep the last one.
SmallString< 128 > getStatsFileName (const llvm::opt::ArgList &Args, const InputInfo &Output, const InputInfo &Input, const Driver &D)
Handles the -save-stats option and returns the filename to save statistics to.
void addMultilibFlag (bool Enabled, const StringRef Flag, Multilib::flags_list &Flags)
Flag must be a flag accepted by the driver.
void addX86AlignBranchArgs (const Driver &D, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, bool IsLTO, const StringRef PluginOptPrefix="")
void checkAMDGPUCodeObjectVersion (const Driver &D, const llvm::opt::ArgList &Args)
unsigned getAMDGPUCodeObjectVersion (const Driver &D, const llvm::opt::ArgList &Args)
bool haveAMDGPUCodeObjectVersionArgument (const Driver &D, const llvm::opt::ArgList &Args)
void addMachineOutlinerArgs (const Driver &D, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const llvm::Triple &Triple, bool IsLTO, const StringRef PluginOptPrefix="")
void addOpenMPDeviceRTL (const Driver &D, const llvm::opt::ArgList &DriverArgs, llvm::opt::ArgStringList &CC1Args, StringRef BitcodeSuffix, const llvm::Triple &Triple, const ToolChain &HostTC)
void addOutlineAtomicsArgs (const Driver &D, const ToolChain &TC, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const llvm::Triple &Triple)
void addOffloadCompressArgs (const llvm::opt::ArgList &TCArgs, llvm::opt::ArgStringList &CmdArgs)
Enumeration Type Documentation
DwarfFissionKind
enum clang::driver::tools::DwarfFissionKind strong
Enumerator
None
Split
Single
Definition at line 301 of file Clang.h.
Function Documentation
addArchSpecificRPath()
void clang::driver::tools::addArchSpecificRPath (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by clang::driver::toolchains::VEToolChain::AddCXXStdlibLibArgs(), and addSanitizerRuntime().
addAsNeededOption()
void clang::driver::tools::addAsNeededOption (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, bool as_needed)
Definition at line 1382 of file CommonArgs.cpp.
References clang::driver::ToolChain::getTriple(), and clang::driver::tools::solaris::isLinkerGnuLd().
Referenced by AddUnwindLibrary(), and clang::driver::tools::solaris::Linker::ConstructJob().
AddAssemblerKPIC()
void clang::driver::tools::AddAssemblerKPIC (const ToolChain & ToolChain, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), and clang::driver::tools::openbsd::Assembler::ConstructJob().
addDebugInfoKind()
void clang::driver::tools::addDebugInfoKind (llvm::opt::ArgStringList & CmdArgs, llvm::codegenoptions::DebugInfoKind DebugInfoKind)
Referenced by RenderDebugEnablingArgs().
addDirectoryList()
void clang::driver::tools::addDirectoryList (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const char * ArgName, const char * EnvVar)
EnvVar is split by system delimiter for environment variables.
If ArgName is "-I", "-L", or an empty string, each entry from EnvVar is prefixed by ArgName then added to Args. Otherwise, for each entry of EnvVar, ArgName is added to Args first, then the entry itself is added.
Referenced by clang::driver::tools::NVPTX::Linker::ConstructJob(), clang::driver::tools::NVPTX::OpenMPLinker::ConstructJob(), clang::driver::toolchains::HIPAMDToolChain::getDeviceLibs(), and clang::driver::toolchains::HIPSPVToolChain::getDeviceLibs().
addFortranRuntimeLibraryPath()
void clang::driver::tools::addFortranRuntimeLibraryPath (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Adds the path for the Fortran runtime libraries to CmdArgs.
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
addFortranRuntimeLibs()
void clang::driver::tools::addFortranRuntimeLibs (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Adds Fortran runtime libraries to CmdArgs.
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
addHIPRuntimeLibArgs()
void clang::driver::tools::addHIPRuntimeLibArgs (const ToolChain & TC, Compilation & C, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Definition at line 2850 of file CommonArgs.cpp.
References clang::driver::ToolChain::AddHIPRuntimeLibArgs(), and clang::driver::Action::OFK_HIP.
Referenced by clang::driver::tools::gnutools::Linker::ConstructJob(), and clang::driver::tools::visualstudio::Linker::ConstructJob().
addLinkerCompressDebugSectionsOption()
void clang::driver::tools::addLinkerCompressDebugSectionsOption (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Definition at line 452 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), and V.
Referenced by clang::driver::tools::amdgpu::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), and clang::driver::tools::haiku::Linker::ConstructJob().
AddLinkerInputs()
void clang::driver::tools::AddLinkerInputs (const ToolChain & TC, const InputInfoList & Inputs, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const JobAction & JA)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::amdgpu::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::baremetal::Linker::ConstructJob(), clang::driver::tools::CrossWindows::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::nacltools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), clang::driver::tools::PScpu::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::solaris::Linker::ConstructJob(), clang::driver::tools::SPIRV::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), clang::driver::tools::XCore::Linker::ConstructJob(), and clang::driver::tools::zos::Linker::ConstructJob().
addLTOOptions()
void clang::driver::tools::addLTOOptions (const ToolChain & ToolChain, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const InputInfo & Output, const InputInfo & Input, bool IsThinLTO)
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::amdgpu::Linker::ConstructJob(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::MinGW::Linker::ConstructJob(), and clang::driver::tools::openbsd::Linker::ConstructJob().
addMachineOutlinerArgs()
void clang::driver::tools::addMachineOutlinerArgs (const Driver & D, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const llvm::Triple & Triple, bool IsLTO, const StringRef PluginOptPrefix = "")
Definition at line 2752 of file CommonArgs.cpp.
References clang::driver::Driver::Diag().
addMultilibFlag()
void clang::driver::tools::addMultilibFlag (bool Enabled, const StringRef Flag, Multilib::flags_list & Flags)
Flag must be a flag accepted by the driver.
Definition at line 2323 of file CommonArgs.cpp.
Referenced by findAndroidArmMultilibs(), findBiarchMultilibs(), findCSKYMultilibs(), findMSP430Multilibs(), findOHOSMultilibs(), findRISCVMultilibs(), clang::driver::MultilibBuilder::flag(), clang::driver::toolchains::Fuchsia::Fuchsia(), and selectRISCVMultilib().
addOffloadCompressArgs()
void clang::driver::tools::addOffloadCompressArgs (const llvm::opt::ArgList & TCArgs, llvm::opt::ArgStringList & CmdArgs)
Definition at line 2890 of file CommonArgs.cpp.
Referenced by clang::driver::tools::OffloadBundler::ConstructJob(), and clang::driver::tools::LinkerWrapper::ConstructJob().
addOpenMPDeviceRTL()
void clang::driver::tools::addOpenMPDeviceRTL (const Driver & D, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CC1Args, StringRef BitcodeSuffix, const llvm::Triple & Triple, const ToolChain & HostTC)
Definition at line 2785 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), and clang::driver::ToolChain::getFilePaths().
Referenced by clang::driver::toolchains::CudaToolChain::addClangTargetOptions().
addOpenMPRuntime()
bool clang::driver::tools::addOpenMPRuntime (const Compilation & C, llvm::opt::ArgStringList & CmdArgs, const ToolChain & TC, const llvm::opt::ArgList & Args, bool ForceStaticHostRuntime = false, bool IsOffloadingHost = false, bool GompNeedsRT = false)
Returns true, if an OpenMP runtime has been added.
Referenced by clang::driver::tools::darwin::Linker::ConstructJob(), clang::driver::tools::dragonfly::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::haiku::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
addOpenMPRuntimeLibraryPath()
void clang::driver::tools::addOpenMPRuntimeLibraryPath (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
addOutlineAtomicsArgs()
void clang::driver::tools::addOutlineAtomicsArgs (const Driver & D, const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const llvm::Triple & Triple)
Definition at line 2865 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), and clang::driver::ToolChain::IsAArch64OutlineAtomicsDefault().
addPathIfExists()
void clang::driver::tools::addPathIfExists (const Driver & D, const Twine & Path, ToolChain::path_list & Paths)
Definition at line 290 of file CommonArgs.cpp.
Referenced by clang::driver::toolchains::MSP430ToolChain::MSP430ToolChain().
AddRunTimeLibs()
void clang::driver::tools::AddRunTimeLibs (const ToolChain & TC, const Driver & D, llvm::opt::ArgStringList & CmdArgs, const llvm::opt::ArgList & Args)
Referenced by clang::driver::tools::aix::Linker::ConstructJob(), clang::driver::tools::CrossWindows::Linker::ConstructJob(), clang::driver::tools::CSKY::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::msp430::Linker::ConstructJob(), clang::driver::tools::visualstudio::Linker::ConstructJob(), clang::driver::tools::RISCV::Linker::ConstructJob(), clang::driver::tools::wasm::Linker::ConstructJob(), and clang::driver::tools::zos::Linker::ConstructJob().
addSanitizerRuntimes()
bool clang::driver::tools::addSanitizerRuntimes (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
AddStaticDeviceLibs()
void clang::driver::tools::AddStaticDeviceLibs (Compilation * C, const Tool * T, const JobAction * JA, const InputInfoList * Inputs, const Driver & D, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL)
Definition at line 2639 of file CommonArgs.cpp.
References clang::driver::Driver::Dir, clang::FileName, GetSDLFromOffloadArchive(), clang::driver::types::lookupTypeForExtension(), SDLSearch(), clang::T, and clang::driver::types::TY_INVALID.
Referenced by AddStaticDeviceLibsLinking(), and AddStaticDeviceLibsPostLinking().
AddStaticDeviceLibsLinking()
void clang::driver::tools::AddStaticDeviceLibsLinking (Compilation & C, const Tool & T, const JobAction & JA, const InputInfoList & Inputs, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL)
Definition at line 2592 of file CommonArgs.cpp.
References AddStaticDeviceLibs(), and clang::T.
Referenced by clang::driver::tools::NVPTX::OpenMPLinker::ConstructJob().
AddStaticDeviceLibsPostLinking()
void clang::driver::tools::AddStaticDeviceLibsPostLinking (const Driver & D, const llvm::opt::ArgList & DriverArgs, llvm::opt::ArgStringList & CmdArgs, StringRef Arch, StringRef Target, bool isBitCodeSDL, bool postClangLink)
Definition at line 2605 of file CommonArgs.cpp.
References AddStaticDeviceLibs().
Referenced by clang::driver::toolchains::CudaToolChain::addClangTargetOptions().
AddTargetFeature()
void clang::driver::tools::AddTargetFeature (const llvm::opt::ArgList & Args, std::vector< StringRef > & Features, llvm::opt::OptSpecifier OnOpt, llvm::opt::OptSpecifier OffOpt, StringRef FeatureName)
addX86AlignBranchArgs()
void clang::driver::tools::addX86AlignBranchArgs (const Driver & D, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, bool IsLTO, const StringRef PluginOptPrefix = "")
Referenced by clang::driver::tools::ClangAs::AddX86TargetArgs().
addXRayRuntime()
bool clang::driver::tools::addXRayRuntime (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), and clang::driver::tools::openbsd::Linker::ConstructJob().
areOptimizationsEnabled()
bool clang::driver::tools::areOptimizationsEnabled (const llvm::opt::ArgList & Args)
Referenced by useFramePointerForTargetByDefault().
checkAMDGPUCodeObjectVersion()
void clang::driver::tools::checkAMDGPUCodeObjectVersion (const Driver & D, const llvm::opt::ArgList & Args)
Definition at line 2715 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), and getAMDGPUCodeObjectArgument().
claimNoWarnArgs()
void clang::driver::tools::claimNoWarnArgs (const llvm::opt::ArgList & Args)
Referenced by clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::CrossWindows::Assembler::ConstructJob(), clang::driver::tools::dragonfly::Assembler::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), clang::driver::tools::hexagon::Assembler::ConstructJob(), clang::driver::tools::MinGW::Assembler::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::PScpu::Assembler::ConstructJob(), clang::driver::tools::SPIRV::Translator::ConstructJob(), and clang::driver::tools::XCore::Assembler::ConstructJob().
debugLevelToInfoKind()
llvm::codegenoptions::DebugInfoKind clang::driver::tools::debugLevelToInfoKind (const llvm::opt::Arg & A)
Referenced by renderDebugOptions().
DwarfVersionNum()
unsigned clang::driver::tools::DwarfVersionNum (StringRef ArgValue)
Definition at line 2115 of file CommonArgs.cpp.
Referenced by CollectArgsForIntegratedAssembler(), and getDwarfVersion().
getAMDGPUCodeObjectVersion()
unsigned clang::driver::tools::getAMDGPUCodeObjectVersion (const Driver & D, const llvm::opt::ArgList & Args)
Definition at line 2739 of file CommonArgs.cpp.
References getAMDGPUCodeObjectArgument().
Referenced by clang::driver::toolchains::ROCMToolChain::addClangTargetOptions(), clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames(), and handleAMDGPUCodeObjectVersionOptions().
getCPUName()
std::string clang::driver::tools::getCPUName (const Driver & D, const llvm::opt::ArgList & Args, const llvm::Triple & T, bool FromAs = false)
Referenced by clang::driver::toolchains::AVRToolChain::AVRToolChain(), clang::driver::tools::AVR::Linker::ConstructJob(), clang::driver::tools::ClangAs::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::fuchsia::Linker::ConstructJob(), clang::driver::tools::gnutools::Linker::ConstructJob(), clang::driver::tools::netbsd::Assembler::ConstructJob(), and clang::driver::tools::openbsd::Assembler::ConstructJob().
getCXX20NamedModuleOutputPath()
llvm::SmallString<256> clang::driver::tools::getCXX20NamedModuleOutputPath (const llvm::opt::ArgList & Args, const char * BaseInput)
Referenced by GetModuleOutputPath().
getDebugFissionKind()
DwarfFissionKind clang::driver::tools::getDebugFissionKind (const Driver & D, const llvm::opt::ArgList & Args, llvm::opt::Arg *& Arg)
Referenced by renderDebugOptions().
getDwarfNArg()
const llvm::opt::Arg* clang::driver::tools::getDwarfNArg (const llvm::opt::ArgList & Args)
Referenced by getDwarfVersion(), and renderDebugOptions().
getDwarfVersion()
unsigned clang::driver::tools::getDwarfVersion (const ToolChain & TC, const llvm::opt::ArgList & Args)
Definition at line 2130 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), DwarfVersionNum(), clang::driver::ToolChain::GetDefaultDwarfVersion(), clang::driver::ToolChain::getDriver(), getDwarfNArg(), clang::driver::ToolChain::getTriple(), and ParseDebugDefaultVersion().
Referenced by renderDebugOptions().
getLastCSProfileGenerateArg()
llvm::opt::Arg* clang::driver::tools::getLastCSProfileGenerateArg (const llvm::opt::ArgList & Args)
Referenced by addPGOAndCoverageFlags().
getLastProfileSampleUseArg()
llvm::opt::Arg* clang::driver::tools::getLastProfileSampleUseArg (const llvm::opt::ArgList & Args)
Referenced by addPGOAndCoverageFlags().
getLastProfileUseArg()
llvm::opt::Arg* clang::driver::tools::getLastProfileUseArg (const llvm::opt::ArgList & Args)
Referenced by addPGOAndCoverageFlags(), and renderRemarksOptions().
getLTOParallelism()
llvm::StringRef clang::driver::tools::getLTOParallelism (const llvm::opt::ArgList & Args, const Driver & D)
Referenced by clang::driver::tools::darwin::Linker::ConstructJob(), and clang::driver::tools::PScpu::Linker::ConstructJob().
getStatsFileName()
SmallString< 128 > clang::driver::tools::getStatsFileName (const llvm::opt::ArgList & Args, const InputInfo & Output, const InputInfo & Input, const Driver & D)
Handles the -save-stats option and returns the filename to save statistics to.
Definition at line 2292 of file CommonArgs.cpp.
References clang::driver::Driver::CCPrintInternalStatReportFilename, clang::driver::Driver::CCPrintInternalStats, clang::driver::Driver::Diag(), clang::driver::InputInfo::getBaseInput(), clang::driver::InputInfo::getFilename(), and clang::driver::InputInfo::isFilename().
Referenced by clang::driver::tools::darwin::Linker::ConstructJob().
getTargetFeatures()
void clang::driver::tools::getTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, bool ForAS, bool IsAux = false)
Referenced by clang::driver::tools::ClangAs::ConstructJob(), and clang::driver::tools::OffloadPackager::ConstructJob().
handleTargetFeaturesGroup()
void clang::driver::tools::handleTargetFeaturesGroup (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, std::vector< StringRef > & Features, llvm::opt::OptSpecifier Group)
Iterate Args and convert -mxxx to +xxx and -mno-xxx to -xxx and append it to Features.
Note: Since Features may contain default values before calling this function, or may be appended with entries to override arguments, entries in Features are not unique.
Referenced by clang::driver::tools::amdgpu::getAMDGPUTargetFeatures(), and getWebAssemblyTargetFeatures().
haveAMDGPUCodeObjectVersionArgument()
bool clang::driver::tools::haveAMDGPUCodeObjectVersionArgument (const Driver & D, const llvm::opt::ArgList & Args)
Definition at line 2747 of file CommonArgs.cpp.
References getAMDGPUCodeObjectArgument().
Referenced by handleAMDGPUCodeObjectVersionOptions().
isDependentLibAdded()
bool clang::driver::tools::isDependentLibAdded (const llvm::opt::ArgList & Args, StringRef Lib)
Referenced by clang::driver::tools::visualstudio::Linker::ConstructJob().
isObjCAutoRefCount()
bool clang::driver::tools::isObjCAutoRefCount (const llvm::opt::ArgList & Args)
Referenced by clang::driver::toolchains::DarwinClang::AddLinkARCArgs(), isObjCRuntimeLinked(), and RenderObjCOptions().
isTLSDESCEnabled()
bool clang::driver::tools::isTLSDESCEnabled (const ToolChain & TC, const llvm::opt::ArgList & Args)
Definition at line 739 of file CommonArgs.cpp.
References clang::driver::Driver::Diag(), clang::driver::ToolChain::getDriver(), clang::driver::ToolChain::getEffectiveTriple(), clang::driver::options::Unsupported, and V.
isUseSeparateSections()
bool clang::driver::tools::isUseSeparateSections (const llvm::Triple & Triple)
Definition at line 735 of file CommonArgs.cpp.
linkSanitizerRuntimeDeps()
void clang::driver::tools::linkSanitizerRuntimeDeps (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::openbsd::Linker::ConstructJob(), and clang::driver::tools::solaris::Linker::ConstructJob().
linkXRayRuntimeDeps()
void clang::driver::tools::linkXRayRuntimeDeps (const ToolChain & TC, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs)
Referenced by constructHexagonLinkArgs(), clang::driver::tools::freebsd::Linker::ConstructJob(), clang::driver::tools::netbsd::Linker::ConstructJob(), and clang::driver::tools::openbsd::Linker::ConstructJob().
ParseFunctionAlignment()
unsigned clang::driver::tools::ParseFunctionAlignment (const ToolChain & TC, const llvm::opt::ArgList & Args)
Referenced by clang::driver::tools::Clang::ConstructJob().
ParsePICArgs()
std::tuple<llvm::Reloc::Model, unsigned, bool> clang::driver::tools::ParsePICArgs (const ToolChain & ToolChain, const llvm::opt::ArgList & Args)
RelocationModelName()
const char * clang::driver::tools::RelocationModelName (llvm::Reloc::Model Model)
Definition at line 1795 of file CommonArgs.cpp.
SplitDebugInfo()
void clang::driver::tools::SplitDebugInfo (const ToolChain & TC, Compilation & C, const Tool & T, const JobAction & JA, const llvm::opt::ArgList & Args, const InputInfo & Output, const char * OutFile)
Referenced by clang::driver::tools::MinGW::Assembler::ConstructJob().
SplitDebugName()
const char* clang::driver::tools::SplitDebugName (const JobAction & JA, const llvm::opt::ArgList & Args, const InputInfo & Input, const InputInfo & Output)
Referenced by clang::driver::tools::MinGW::Assembler::ConstructJob().
unifyTargetFeatures()
SmallVector< StringRef > clang::driver::tools::unifyTargetFeatures (ArrayRef< StringRef > Features)
If there are multiple +xxx or -xxx features, keep the last one.
Definition at line 328 of file CommonArgs.cpp.
Referenced by getAArch64MultilibFlags(), and getARMMultilibFlags().