clang: llvm::MachO Namespace Reference
llvm::MachO Namespace Reference
Functions
const DiagnosticBuilder & operator<< (const DiagnosticBuilder &DB, const Architecture &Arch)
const DiagnosticBuilder & operator<< (const DiagnosticBuilder &DB, const ArchitectureSet &ArchSet)
const DiagnosticBuilder & operator<< (const DiagnosticBuilder &DB, const PlatformType &Platform)
const DiagnosticBuilder & operator<< (const DiagnosticBuilder &DB, const PlatformVersionSet &Platforms)
const DiagnosticBuilder & operator<< (const DiagnosticBuilder &DB, const FileType &Type)
const DiagnosticBuilder & operator<< (const DiagnosticBuilder &DB, const PackedVersion &Version)
const clang::DiagnosticBuilder & operator<< (const clang::DiagnosticBuilder &DB, const StringMapEntry< ArchitectureSet > &LibAttr)
Function Documentation
operator<<() [1/7]
const clang::DiagnosticBuilder & llvm::MachO::operator<< (const clang::DiagnosticBuilder & DB, const StringMapEntry< ArchitectureSet > & LibAttr)
Definition at line 98 of file DiagnosticBuilderWrappers.cpp.
References clang::StreamingDiagnostic::AddString().
operator<<() [2/7]
const clang::DiagnosticBuilder & llvm::MachO::operator<< (const DiagnosticBuilder & DB, const Architecture & Arch)
Definition at line 19 of file DiagnosticBuilderWrappers.cpp.
References clang::StreamingDiagnostic::AddString().
operator<<() [3/7]
const clang::DiagnosticBuilder & llvm::MachO::operator<< (const DiagnosticBuilder & DB, const ArchitectureSet & ArchSet)
Definition at line 25 of file DiagnosticBuilderWrappers.cpp.
References clang::StreamingDiagnostic::AddString().
operator<<() [4/7]
const clang::DiagnosticBuilder & llvm::MachO::operator<< (const DiagnosticBuilder & DB, const FileType & Type)
Definition at line 55 of file DiagnosticBuilderWrappers.cpp.
References clang::StreamingDiagnostic::AddString(), clang::XRayInstrKind::All, and Type.
operator<<() [5/7]
const clang::DiagnosticBuilder & llvm::MachO::operator<< (const DiagnosticBuilder & DB, const PackedVersion & Version)
Definition at line 89 of file DiagnosticBuilderWrappers.cpp.
References clang::StreamingDiagnostic::AddString().
operator<<() [6/7]
const clang::DiagnosticBuilder & llvm::MachO::operator<< (const DiagnosticBuilder & DB, const PlatformType & Platform)
Definition at line 31 of file DiagnosticBuilderWrappers.cpp.
References clang::StreamingDiagnostic::AddString(), and getPlatformName().
operator<<() [7/7]
const clang::DiagnosticBuilder & llvm::MachO::operator<< (const DiagnosticBuilder & DB, const PlatformVersionSet & Platforms)
Definition at line 37 of file DiagnosticBuilderWrappers.cpp.
References clang::StreamingDiagnostic::AddString(), and getPlatformName().