clang: clang::driver::tools::AMDGCN Namespace Reference
clang::driver::tools::AMDGCN Namespace Reference
Classes
class Linker
class OpenMPLinker
class SYCLLinker
Functions
void constructHIPFatbinCommand (Compilation &C, const JobAction &JA, StringRef OutputFileName, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const Tool &T)
Function Documentation
constructHIPFatbinCommand()
void clang::driver::tools::AMDGCN::constructHIPFatbinCommand (Compilation & C, const JobAction & JA, StringRef OutputFileName, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const Tool & T)
Definition at line 102 of file HIP.cpp.
References clang::driver::tools::getAMDGPUCodeObjectVersion(), clang::driver::ToolChain::GetProgramPath(), clang::driver::Tool::getToolChain(), clang::driver::tools::haveAMDGPUCodeObjectVersionArgument(), clang::driver::ResponseFileSupport::None(), NULL_FILE, and string().
Referenced by clang::driver::tools::AMDGCN::Linker::ConstructJob().