clang: llvm Namespace Reference
llvm Namespace Reference
Diagnostic wrappers for TextAPI types for error reporting.
Namespaces
cl
IDFCalculatorDetail
json
MachO
opt
orc
vfs
yaml
Classes
struct GraphTraits< clang::DomTreeNode * >
DominatorTree GraphTraits specialization so the DominatorTree can be iterable by generic graph iterators.
struct GraphTraits< clang::CFGDomTree * >
struct DenseMapInfo< clang::CallGraphNode::CallRecord >
struct GraphTraits< clang::CallGraphNode * >
struct GraphTraits< const clang::CallGraphNode * >
struct GraphTraits< clang::CallGraph * >
struct GraphTraits< const clang::CallGraph * >
struct simplify_type< ::clang::CFGTerminator >
Implement simplify_type for CFGTerminator, so that we can dyn_cast from CFGTerminator to a specific Stmt class.
struct GraphTraits< ::clang::CFGBlock * >
struct GraphTraits< const ::clang::CFGBlock * >
struct GraphTraits< Inverse< ::clang::CFGBlock * > >
struct GraphTraits< Inverse< const ::clang::CFGBlock * > >
struct GraphTraits< ::clang::CFG * >
struct GraphTraits< const ::clang::CFG * >
struct GraphTraits< Inverse< ::clang::CFG * > >
struct GraphTraits< Inverse< const ::clang::CFG * > >
struct DenseMapInfo< clang::dataflow::Atom >
struct DenseMapInfo< clang::ProgramPoint >
struct FoldingSetTrait< ArgEffect >
struct FoldingSetTrait< RetEffect >
struct DenseMapInfo< ObjCSummaryKey >
struct PointerLikeTypeTraits< clang::TypeInfoLValue >
struct PointerLikeTypeTraits< clang::DynamicAllocLValue >
struct DenseMapInfo< clang::APValue::LValueBase >
class SmallPtrSet
struct DenseMapInfo< clang::ASTNodeKind >
struct DenseMapInfo< clang::DynTypedNode >
struct DenseMapInfo< clang::BaseSubobject >
struct simplify_type< ::clang::CanQual< T > >
Implement simplify_type for CanQual<T>, so that we can dyn_cast from CanQual<T> to a specific Type class.
struct PointerLikeTypeTraits< clang::CanQual< T > >
struct DenseMapInfo< clang::CharUnits >
struct DenseMapInfo< clang::DeclarationName >
Define DenseMapInfo so that DeclarationNames can be used as keys in DenseMap and DenseSets.
struct PointerLikeTypeTraits< clang::DeclarationName >
struct PointerLikeTypeTraits<::clang::NamedDecl * >
struct isa_impl< To, ::clang::DeclContext >
isa<T>(DeclContext*)
struct cast_convert_val< ToTy, const ::clang::DeclContext, const ::clang::DeclContext >
cast<T>(DeclContext*)
struct cast_convert_val< ToTy, ::clang::DeclContext, ::clang::DeclContext >
struct cast_convert_val< ToTy, const ::clang::DeclContext *, const ::clang::DeclContext * >
struct cast_convert_val< ToTy, ::clang::DeclContext *, ::clang::DeclContext * >
struct cast_convert_val< ::clang::DeclContext, FromTy, FromTy >
Implement cast_convert_val for Decl -> DeclContext conversions.
struct cast_convert_val< ::clang::DeclContext, FromTy *, FromTy * >
struct cast_convert_val< const ::clang::DeclContext, FromTy, FromTy >
struct cast_convert_val< const ::clang::DeclContext, FromTy *, FromTy * >
struct PointerLikeTypeTraits
struct PointerLikeTypeTraits< clang::DeclGroupRef >
struct PointerLikeTypeTraits< clang::LazyGenerationalUpdatePtr< Owner, T, Update > >
Specialize PointerLikeTypeTraits to allow LazyGenerationalUpdatePtr to be placed into a PointerUnion.
struct DenseMapInfo< clang::GlobalDecl >
struct DenseMapInfo< clang::NestedNameSpecifierLoc >
class SmallVectorImpl
struct DenseMapInfo< clang::CanonicalDeclPtr< decl_type > >
struct PointerLikeTypeTraits< clang::CanonicalDeclPtr< decl_type > >
struct GraphTraits< clang::Stmt * >
struct GraphTraits< const clang::Stmt * >
struct PointerLikeTypeTraits< clang::Expr * >
struct PointerLikeTypeTraits< clang::TemplateName >
The clang::TemplateName class is effectively a pointer.
struct PointerLikeTypeTraits< ::clang::Type * >
struct PointerLikeTypeTraits< ::clang::ExtQuals * >
struct simplify_type< ::clang::QualType >
Implement simplify_type for QualType, so that we can dyn_cast from QualType to a specific Type class.
struct PointerLikeTypeTraits< clang::QualType >
struct DenseMapInfo< clang::QualType >
struct DenseMapInfo< clang::CanQualType >
struct PointerLikeTypeTraits< clang::DirectoryEntryRef >
struct DenseMapInfo< clang::DirectoryEntryRef >
Specialisation of DenseMapInfo for DirectoryEntryRef.
struct DenseMapInfo< clang::FileEntryRef >
Specialisation of DenseMapInfo for FileEntryRef.
struct DenseMapInfo< clang::Selector >
Define DenseMapInfo so that Selectors can be used as keys in DenseMap and DenseSets.
struct PointerLikeTypeTraits< clang::Selector >
class ArrayRef
class MutableArrayRef
class OwningArrayRef
class SmallString
class SmallVector
class Expected
struct SaveAndRestore
class IntrusiveRefCntPtr
struct IntrusiveRefCntPtrInfo
class RefCountedBase
struct FoldingSetTrait
struct DenseMapInfo< clang::FileID, void >
Define DenseMapInfo so that FileID's can be used as keys in DenseMap and DenseSets.
struct DenseMapInfo< clang::SourceLocation, void >
Define DenseMapInfo so that SourceLocation's can be used as keys in DenseMap and DenseSet.
struct FoldingSetTrait< clang::SourceLocation, void >
struct DenseMapInfo< clang::tok::PPKeywordKind >
struct PointerLikeTypeTraits< ::clang::CodeGen::ConstantInitBuilderBase * >
struct PointerLikeTypeTraits< ::clang::CodeGen::ConstantInitFuture >
struct CastInfo<::clang::extractapi::RecordContext, FromTy * >
struct CastInfo<::clang::extractapi::RecordContext, const FromTy * >
struct CastInfo< ToTy, ::clang::extractapi::RecordContext * >
struct CastInfo< ToTy, const ::clang::extractapi::RecordContext * >
class SmallSetVector
struct PointerLikeTypeTraits< clang::OpaquePtr< T > >
class DenseSet
struct DenseMapInfo< clang::SemaCUDA::FunctionDeclAndLoc >
struct DenseMapInfo< clang::serialization::DeclarationNameKey >
struct DenseMapInfo< clang::serialization::GlobalDeclID >
struct simplify_type< clang::ento::CallEventRef< T > >
struct GraphTraits< clang::ento::ExplodedGraph * >
struct IntrusiveRefCntPtrInfo< const clang::ento::ProgramState >
struct CastInfo< To, From, std::enable_if_t< std::is_base_of<::clang::ento::SVal, From >::value > >
struct DenseMapInfo< clang::tooling::dependencies::ModuleID >
struct DenseMapInfo< clang::tooling::stdlib::Header >
struct DenseMapInfo< clang::tooling::stdlib::Symbol >
struct DOTGraphTraits< const CallGraph * >
struct DOTGraphTraits< const CFG * >
struct DenseMapInfo< clang::api_notes::StoredObjCSelector >
struct DenseMapInfo< clang::api_notes::ContextTableKey >
struct DenseMapInfo< EditEntry >
struct DenseMapInfo< ObjectUnderConstruction >
struct DenseMapInfo< DecompositionDeclName >
struct DOTGraphTraits< const Stmt * >
struct DenseMapInfo< clang::CodeGen::TBAAAccessInfo >
struct DenseMapInfo< CatchHandlerType >
struct GraphTraits< ModuleManager >
struct DOTGraphTraits< ModuleManager >
struct FoldingSetTrait< AllocKind >
struct FoldingSetTrait< ObjectState >
struct FoldingSetTrait< SValData >
struct FoldingSetTrait< SValPair >
struct DenseMapInfo< PrivateMethodKey >
struct DOTGraphTraits< ExplodedGraph * >
Functions
hash_code hash_value (const clang::tooling::dependencies::ModuleID &ID)
template<typename T >
bool isDenseMapKeyEmpty (T V)
template<typename T >
bool isDenseMapKeyTombstone (T V)
template<typename T >
std::optional< bool > areDenseMapKeysEqualSpecialValues (T LHS, T RHS)
static cl::opt< bool > ClSanitizeOnOptimizerEarlyEP ("sanitizer-early-opt-ep", cl::Optional, cl::desc("Insert sanitizers on OptimizerEarlyEP."))
static cl::opt< PGOOptions::ColdFuncOpt > ClPGOColdFuncAttr ("pgo-cold-func-opt", cl::init(PGOOptions::ColdFuncOpt::Default), cl::Hidden, cl::desc("Function attribute to apply to cold functions as determined by PGO"), cl::values(clEnumValN(PGOOptions::ColdFuncOpt::Default, "default", "Default (no attribute)"), clEnumValN(PGOOptions::ColdFuncOpt::OptSize, "optsize", "Mark cold functions with optsize."), clEnumValN(PGOOptions::ColdFuncOpt::MinSize, "minsize", "Mark cold functions with minsize."), clEnumValN(PGOOptions::ColdFuncOpt::OptNone, "optnone", "Mark cold functions with optnone.")))
cl::opt< bool > ClRelinkBuiltinBitcodePostop ("relink-builtin-bitcode-postop", cl::Optional, cl::desc("Re-link builtin bitcodes after optimization."), cl::init(false))
static cl::opt< bool > SYCLNativeCPUBackend ("sycl-native-cpu-backend", cl::init(false), cl::desc("Re-link builtin bitcodes after optimization."))
cl::opt< bool > EnableSingleByteCoverage ("enable-single-byte-coverage", llvm::cl::ZeroOrMore, llvm::cl::desc("Enable single byte coverage"), llvm::cl::Hidden, llvm::cl::init(false))
static raw_ostream & operator<< (raw_ostream &Out, BindingKey K)
Variables
cl::opt< bool > PrintPipelinePasses
cl::opt< InstrProfCorrelator::ProfCorrelatorKind > ProfileCorrelate
cl::opt< bool > EnableSingleByteCoverage
cl::opt< bool > ClRelinkBuiltinBitcodePostop
Detailed Description
Diagnostic wrappers for TextAPI types for error reporting.
YAML serialization mapping.
Function Documentation
areDenseMapKeysEqualSpecialValues()
template<typename T > std::optional<bool> llvm::areDenseMapKeysEqualSpecialValues (T LHS, T RHS)
Definition at line 89 of file ItaniumCXXABI.cpp.
References isDenseMapKeyEmpty(), and isDenseMapKeyTombstone().
Referenced by llvm::DenseMapInfo< DecompositionDeclName >::isEqual().
ClPGOColdFuncAttr()
static cl::opt<PGOOptions::ColdFuncOpt> llvm::ClPGOColdFuncAttr ("pgo-cold-func-opt" , cl::init(PGOOptions::ColdFuncOpt::Default) , cl::Hidden , cl::desc("Function attribute to apply to cold functions as determined by PGO") , cl::values(clEnumValN(PGOOptions::ColdFuncOpt::Default, "default", "Default (no attribute)"), clEnumValN(PGOOptions::ColdFuncOpt::OptSize, "optsize", "Mark cold functions with optsize."), clEnumValN(PGOOptions::ColdFuncOpt::MinSize, "minsize", "Mark cold functions with minsize."), clEnumValN(PGOOptions::ColdFuncOpt::OptNone, "optnone", "Mark cold functions with optnone."))) static
ClRelinkBuiltinBitcodePostop()
cl::opt<bool> llvm::ClRelinkBuiltinBitcodePostop ("relink-builtin-bitcode-postop" , cl::Optional , cl::desc("Re-link builtin bitcodes after optimization.") , cl::init(false))
ClSanitizeOnOptimizerEarlyEP()
static cl::opt<bool> llvm::ClSanitizeOnOptimizerEarlyEP ("sanitizer-early-opt-ep" , cl::Optional , cl::desc("Insert sanitizers on OptimizerEarlyEP.")) static
EnableSingleByteCoverage()
cl::opt<bool> llvm::EnableSingleByteCoverage ("enable-single-byte-coverage" , llvm::cl::ZeroOrMore , llvm::cl::desc("Enable single byte coverage") , llvm::cl::Hidden , llvm::cl::init(false))
hash_value()
hash_code llvm::hash_value (const clang::tooling::dependencies::ModuleID & ID) inline
Definition at line 321 of file ModuleDepCollector.h.
References clang::format::hash_combine(), and ID.
Referenced by clang::BackendConsumer::getFunctionSourceLocation(), llvm::DenseMapInfo< clang::DirectoryEntryRef >::getHashValue(), llvm::DenseMapInfo< clang::api_notes::StoredObjCSelector >::getHashValue(), llvm::DenseMapInfo< clang::FileEntryRef >::getHashValue(), llvm::DenseMapInfo< clang::tooling::stdlib::Header >::getHashValue(), clang::DynTypedNode::DenseMapInfo::getHashValue(), llvm::DenseMapInfo< clang::tooling::dependencies::ModuleID >::getHashValue(), clang::tooling::dependencies::DependencyScanningFilesystemSharedCache::getShardForFilename(), clang::hash_value(), and clang::api_notes::ContextTableKey::hashValue().
isDenseMapKeyEmpty()
template<typename T > bool llvm::isDenseMapKeyEmpty (T V)
Definition at line 79 of file ItaniumCXXABI.cpp.
References V.
Referenced by areDenseMapKeysEqualSpecialValues().
isDenseMapKeyTombstone()
template<typename T > bool llvm::isDenseMapKeyTombstone (T V)
Definition at line 83 of file ItaniumCXXABI.cpp.
References V.
Referenced by areDenseMapKeysEqualSpecialValues().
operator<<()
static raw_ostream& llvm::operator<< (raw_ostream & Out, BindingKey K) inline static
Definition at line 125 of file RegionStore.cpp.
SYCLNativeCPUBackend()
static cl::opt<bool> llvm::SYCLNativeCPUBackend ("sycl-native-cpu-backend" , cl::init(false) , cl::desc("Re-link builtin bitcodes after optimization.")) static
Variable Documentation
ClRelinkBuiltinBitcodePostop
cl::opt<bool> llvm::ClRelinkBuiltinBitcodePostop extern
EnableSingleByteCoverage
cl::opt< bool > llvm::EnableSingleByteCoverage extern
Definition at line 32 of file CGExprComplex.cpp.
Referenced by clang::CodeGen::CodeGenPGO::setProfileVersion().
PrintPipelinePasses
cl::opt<bool> llvm::PrintPipelinePasses extern
ProfileCorrelate
cl::opt<InstrProfCorrelator::ProfCorrelatorKind> llvm::ProfileCorrelate extern