clang: clang::analyze_os_log Namespace Reference
clang::analyze_os_log Namespace Reference
Classes
class OSLogBufferItem
An OSLogBufferItem represents a single item in the data written by a call to os_log() or os_trace().
class OSLogBufferLayout
Functions
bool computeOSLogBufferLayout (clang::ASTContext &Ctx, const clang::CallExpr *E, OSLogBufferLayout &layout)
Function Documentation
computeOSLogBufferLayout()
bool clang::analyze_os_log::computeOSLogBufferLayout (clang::ASTContext & Ctx, const clang::CallExpr * E, OSLogBufferLayout & layout)
Definition at line 181 of file OSLog.cpp.
References Data, clang::CallExpr::getArg(), clang::CallExpr::getArgs(), clang::CallExpr::getBuiltinCallee(), clang::ASTContext::getLangOpts(), clang::CallExpr::getNumArgs(), clang::StringLiteral::getString(), clang::ASTContext::getTargetInfo(), clang::Expr::IgnoreParenCasts(), clang::StringLiteral::isOrdinary(), clang::StringLiteral::isUTF8(), and clang::analyze_format_string::ParsePrintfString().
Referenced by clang::CodeGen::CodeGenFunction::emitBuiltinOSLogFormat().