clang: clang::driver::tools::NVPTX Namespace Reference
clang::driver::tools::NVPTX Namespace Reference
Classes
class Assembler
class Linker
class OpenMPLinker
class SYCLLinker
Functions
void getNVPTXTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, std::vector< StringRef > &Features, Optional< clang::CudaVersion > Version=None)
Function Documentation
getNVPTXTargetFeatures()
void clang::driver::tools::NVPTX::getNVPTXTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, std::vector< StringRef > & Features, Optional< clang::CudaVersion > Version = None)
Definition at line 648 of file Cuda.cpp.
References CASE_CUDA_VERSION, and clang::driver::CudaInstallationDetector::version().
Referenced by clang::driver::toolchains::CudaToolChain::addClangTargetOptions(), and getTargetFeatures().