clang: clang::markup Namespace Reference
clang::markup Namespace Reference
Typedefs
using FIDMap = llvm::DenseMap< FileID, unsigned >
Functions
unsigned AddFID (FIDMap &FIDs, SmallVectorImpl< FileID > &V, FileID FID)
unsigned AddFID (FIDMap &FIDs, SmallVectorImpl< FileID > &V, const SourceManager &SM, SourceLocation L)
unsigned GetFID (const FIDMap &FIDs, FileID FID)
unsigned GetFID (const FIDMap &FIDs, const SourceManager &SM, SourceLocation L)
raw_ostream & Indent (raw_ostream &o, const unsigned indent)
raw_ostream & EmitPlistHeader (raw_ostream &o)
raw_ostream & EmitInteger (raw_ostream &o, int64_t value)
raw_ostream & EmitString (raw_ostream &o, StringRef s)
void EmitLocation (raw_ostream &o, const SourceManager &SM, SourceLocation L, const FIDMap &FM, unsigned indent)
void EmitRange (raw_ostream &o, const SourceManager &SM, CharSourceRange R, const FIDMap &FM, unsigned indent)
Typedef Documentation
FIDMap
using clang::markup::FIDMap = typedef llvm::DenseMap<FileID, unsigned>
Definition at line 25 of file PlistSupport.h.
Function Documentation
AddFID() [1/2]
unsigned clang::markup::AddFID (FIDMap & FIDs, SmallVectorImpl< FileID > & V, const SourceManager & SM, SourceLocation L) inline
Definition at line 38 of file PlistSupport.h.
References AddFID(), SM, and V.
AddFID() [2/2]
unsigned clang::markup::AddFID (FIDMap & FIDs, SmallVectorImpl< FileID > & V, FileID FID) inline
Definition at line 27 of file PlistSupport.h.
References V.
Referenced by AddFID(), printCoverage(), and clang::arcmt::writeARCDiagsToPlist().
EmitInteger()
raw_ostream& clang::markup::EmitInteger (raw_ostream & o, int64_t value) inline
Definition at line 71 of file PlistSupport.h.
Referenced by EmitLocation(), and printCoverage().
EmitLocation()
void clang::markup::EmitLocation (raw_ostream & o, const SourceManager & SM, SourceLocation L, const FIDMap & FM, unsigned indent) inline
Definition at line 107 of file PlistSupport.h.
References EmitInteger(), clang::FullSourceLoc::getExpansionColumnNumber(), clang::FullSourceLoc::getExpansionLineNumber(), GetFID(), Indent(), clang::SourceLocation::isInvalid(), and SM.
Referenced by EmitRange(), and clang::arcmt::writeARCDiagsToPlist().
EmitPlistHeader()
raw_ostream& clang::markup::EmitPlistHeader (raw_ostream & o) inline
Definition at line 62 of file PlistSupport.h.
Referenced by clang::arcmt::writeARCDiagsToPlist().
EmitRange()
void clang::markup::EmitRange (raw_ostream & o, const SourceManager & SM, CharSourceRange R, const FIDMap & FM, unsigned indent) inline
Definition at line 123 of file PlistSupport.h.
References EmitLocation(), clang::CharSourceRange::getBegin(), clang::CharSourceRange::getEnd(), clang::SourceLocation::getLocWithOffset(), Indent(), clang::CharSourceRange::isCharRange(), clang::CharSourceRange::isInvalid(), and SM.
Referenced by clang::arcmt::writeARCDiagsToPlist().
EmitString()
raw_ostream& clang::markup::EmitString (raw_ostream & o, StringRef s) inline
Definition at line 78 of file PlistSupport.h.
References c, and s.
Referenced by clang::LogDiagnosticPrinter::EndSourceFile(), and clang::arcmt::writeARCDiagsToPlist().
GetFID() [1/2]
unsigned clang::markup::GetFID (const FIDMap & FIDs, const SourceManager & SM, SourceLocation L) inline
Definition at line 50 of file PlistSupport.h.
References GetFID(), and SM.
GetFID() [2/2]
unsigned clang::markup::GetFID (const FIDMap & FIDs, FileID FID) inline
Definition at line 44 of file PlistSupport.h.
Referenced by EmitLocation(), and GetFID().
Indent()
raw_ostream& clang::markup::Indent (raw_ostream & o, const unsigned indent) inline
Definition at line 56 of file PlistSupport.h.
Referenced by EmitLocation(), and EmitRange().