clang: clang::arcmt::trans Namespace Reference
clang::arcmt::trans Namespace Reference
Classes
class ASTTraverser
class BlockObjCVariableTraverser
class BodyContext
class BodyTransform
class GCAttrsTraverser
class GCCollectableCallsTraverser
class MigrationContext
class ObjCImplementationContext
class PropertyRewriteTraverser
class ProtectedScopeTraverser
Typedefs
typedef llvm::DenseSet< Expr * > ExprSet
Functions
void rewriteAutoreleasePool (MigrationPass &pass)
void rewriteUnbridgedCasts (MigrationPass &pass)
void makeAssignARCSafe (MigrationPass &pass)
void removeRetainReleaseDeallocFinalize (MigrationPass &pass)
void removeZeroOutPropsInDeallocFinalize (MigrationPass &pass)
void rewriteUnusedInitDelegate (MigrationPass &pass)
void checkAPIUses (MigrationPass &pass)
void removeEmptyStatementsAndDeallocFinalize (MigrationPass &pass)
bool canApplyWeak (ASTContext &Ctx, QualType type, bool AllowOnUnknownClass=false)
Determine whether we can add weak to the given type.
bool isPlusOneAssign (const BinaryOperator *E)
bool isPlusOne (const Expr *E)
SourceLocation findLocationAfterSemi (SourceLocation loc, ASTContext &Ctx, bool IsDecl=false)
'Loc' is the end of a statement range.
SourceLocation findSemiAfterLocation (SourceLocation loc, ASTContext &Ctx, bool IsDecl=false)
'Loc' is the end of a statement range.
bool hasSideEffects (Expr *E, ASTContext &Ctx)
bool isGlobalVar (Expr *E)
StringRef getNilString (MigrationPass &Pass)
Returns "nil" or "0" if 'nil' macro is not actually defined.
void clearRefsIn (Stmt *S, ExprSet &refs)
template<typename iterator >
void clearRefsIn (iterator begin, iterator end, ExprSet &refs)
void collectRefs (ValueDecl *D, Stmt *S, ExprSet &refs)
void collectRemovables (Stmt *S, ExprSet &exprs)
Typedef Documentation
ExprSet
typedef llvm::DenseSet<Expr *> clang::arcmt::trans::ExprSet
Definition at line 205 of file Transforms.h.
Function Documentation
canApplyWeak()
bool clang::arcmt::trans::canApplyWeak (ASTContext & Ctx, QualType type, bool AllowOnUnknownClass = false)
Determine whether we can add weak to the given type.
Definition at line 38 of file Transforms.cpp.
References clang::Type::getAs(), clang::ASTContext::getLangOpts(), clang::Type::getPointeeType(), clang::ASTContext::getTargetInfo(), clang::TargetInfo::getTriple(), clang::QualType::isNull(), and clang::ast_matchers::type.
Referenced by checkAllAtProps(), checkWeakGCAttrs(), and clang::arcmt::trans::BlockObjCVariableTraverser::traverseBody().
checkAPIUses()
void clang::arcmt::trans::checkAPIUses (MigrationPass & pass)
Definition at line 105 of file TransAPIUses.cpp.
References clang::arcmt::MigrationPass::Ctx, and clang::ASTContext::getTranslationUnitDecl().
Referenced by independentTransforms().
clearRefsIn() [1/2]
template<typename iterator > void clang::arcmt::trans::clearRefsIn (iterator begin, iterator end, ExprSet & refs)
Definition at line 209 of file Transforms.h.
References clearRefsIn().
clearRefsIn() [2/2]
void clang::arcmt::trans::clearRefsIn (Stmt * S, ExprSet & refs)
Definition at line 299 of file Transforms.cpp.
Referenced by clearRefsIn().
collectRefs()
void clang::arcmt::trans::collectRefs (ValueDecl * D, Stmt * S, ExprSet & refs)
Definition at line 303 of file Transforms.cpp.
collectRemovables()
void clang::arcmt::trans::collectRemovables (Stmt * S, ExprSet & exprs)
Definition at line 307 of file Transforms.cpp.
findLocationAfterSemi()
SourceLocation clang::arcmt::trans::findLocationAfterSemi (SourceLocation loc, ASTContext & Ctx, bool IsDecl = false)
'Loc' is the end of a statement range.
This returns the location immediately after the semicolon following the statement. If no semicolon is found or the location is inside a macro, the returned source location will be invalid.
Definition at line 116 of file Transforms.cpp.
References findSemiAfterLocation(), clang::SourceLocation::getLocWithOffset(), and clang::SourceLocation::isInvalid().
Referenced by rewriteToNSEnumDecl().
findSemiAfterLocation()
SourceLocation clang::arcmt::trans::findSemiAfterLocation (SourceLocation loc, ASTContext & Ctx, bool IsDecl = false)
'Loc' is the end of a statement range.
This returns the location of the semicolon following the statement. If no semicolon is found or the location is inside a macro, the returned source location will be invalid.
Loc is the end of a statement range. This returns the location of the semicolon following the statement. If no semicolon is found or the location is inside a macro, the returned source location will be invalid.
Definition at line 128 of file Transforms.cpp.
References clang::ASTContext::getLangOpts(), clang::Token::getLocation(), clang::Lexer::getLocForEndOfToken(), clang::ASTContext::getSourceManager(), clang::Lexer::isAtEndOfMacroExpansion(), clang::SourceLocation::isMacroID(), clang::Token::isNot(), clang::Lexer::LexFromRawLexer(), and SM.
Referenced by findLocationAfterSemi(), and rewriteToNSEnumDecl().
getNilString()
StringRef clang::arcmt::trans::getNilString (MigrationPass & Pass)
Returns "nil" or "0" if 'nil' macro is not actually defined.
Definition at line 207 of file Transforms.cpp.
References clang::Preprocessor::isMacroDefined(), clang::Sema::PP, and clang::arcmt::MigrationPass::SemaRef.
hasSideEffects()
bool clang::arcmt::trans::hasSideEffects (Expr * E, ASTContext & Ctx)
Definition at line 166 of file Transforms.cpp.
References clang::ObjCMessageExpr::getInstanceReceiver(), clang::ObjCMessageExpr::getMethodFamily(), clang::ObjCMessageExpr::getReceiverKind(), clang::Expr::HasSideEffects(), clang::Expr::IgnoreParenCasts(), clang::ObjCMessageExpr::Instance, clang::OMF_autorelease, clang::OMF_dealloc, clang::OMF_release, clang::OMF_retain, and clang::ObjCMessageExpr::SuperInstance.
isGlobalVar()
bool clang::arcmt::trans::isGlobalVar (Expr * E)
Definition at line 195 of file Transforms.cpp.
References clang::Expr::IgnoreParenCasts().
isPlusOne()
bool clang::arcmt::trans::isPlusOne (const Expr * E)
Definition at line 74 of file Transforms.cpp.
References clang::CastExpr::getCastKind(), clang::CastExpr::getSubExpr(), clang::Expr::IgnoreParenCasts(), clang::ento::cocoa::isRefType(), and clang::OMF_retain.
Referenced by isPlusOneAssign().
isPlusOneAssign()
bool clang::arcmt::trans::isPlusOneAssign (const BinaryOperator * E)
Definition at line 67 of file Transforms.cpp.
References clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getRHS(), and isPlusOne().
makeAssignARCSafe()
void clang::arcmt::trans::makeAssignARCSafe (MigrationPass & pass)
Definition at line 74 of file TransARCAssign.cpp.
References clang::arcmt::MigrationPass::Ctx, and clang::ASTContext::getTranslationUnitDecl().
Referenced by independentTransforms().
removeEmptyStatementsAndDeallocFinalize()
void clang::arcmt::trans::removeEmptyStatementsAndDeallocFinalize (MigrationPass & pass)
Definition at line 240 of file TransEmptyStatementsAndDealloc.cpp.
References clang::arcmt::MigrationPass::ARCMTMacroLocs, cleanupDeallocOrFinalize(), clang::arcmt::MigrationPass::Ctx, clang::ASTContext::getTranslationUnitDecl(), clang::arcmt::TransformActions::remove(), and clang::arcmt::MigrationPass::TA.
Referenced by clang::arcmt::getAllTransformations().
removeRetainReleaseDeallocFinalize()
void clang::arcmt::trans::removeRetainReleaseDeallocFinalize (MigrationPass & pass)
Definition at line 456 of file TransRetainReleaseDealloc.cpp.
References clang::arcmt::MigrationPass::Ctx, clang::ASTContext::getTranslationUnitDecl(), and clang::RecursiveASTVisitor< BodyTransform< BODY_TRANS > >::TraverseDecl().
Referenced by independentTransforms().
removeZeroOutPropsInDeallocFinalize()
void clang::arcmt::trans::removeZeroOutPropsInDeallocFinalize (MigrationPass & pass)
Definition at line 221 of file TransZeroOutPropsInDealloc.cpp.
References clang::arcmt::MigrationPass::Ctx, and clang::ASTContext::getTranslationUnitDecl().
Referenced by independentTransforms().
rewriteAutoreleasePool()
void clang::arcmt::trans::rewriteAutoreleasePool (MigrationPass & pass)
Definition at line 432 of file TransAutoreleasePool.cpp.
References clang::arcmt::MigrationPass::Ctx, clang::ASTContext::getTranslationUnitDecl(), and clang::RecursiveASTVisitor< BodyTransform< BODY_TRANS > >::TraverseDecl().
Referenced by independentTransforms().
rewriteUnbridgedCasts()
void clang::arcmt::trans::rewriteUnbridgedCasts (MigrationPass & pass)
Definition at line 463 of file TransUnbridgedCasts.cpp.
References clang::arcmt::MigrationPass::Ctx, clang::ASTContext::getTranslationUnitDecl(), and clang::RecursiveASTVisitor< BodyTransform< BODY_TRANS > >::TraverseDecl().
Referenced by independentTransforms().
rewriteUnusedInitDelegate()
void clang::arcmt::trans::rewriteUnusedInitDelegate (MigrationPass & pass)
Definition at line 74 of file TransUnusedInitDelegate.cpp.
References clang::arcmt::MigrationPass::Ctx, clang::ASTContext::getTranslationUnitDecl(), and clang::RecursiveASTVisitor< BodyTransform< BODY_TRANS > >::TraverseDecl().
Referenced by independentTransforms().