clang: clang::driver::tools::mips Namespace Reference
clang::driver::tools::mips Namespace Reference
Enumerations
enum IEEE754Standard { Legacy = 1, Std2008 = 2 }
enum FloatABI { FloatABI::Invalid, FloatABI::Soft, FloatABI::Hard }
Functions
IEEE754Standard getIEEE754Standard (StringRef &CPU)
bool hasCompactBranches (StringRef &CPU)
void getMipsCPUAndABI (const llvm::opt::ArgList &Args, const llvm::Triple &Triple, StringRef &CPUName, StringRef &ABIName)
void getMIPSTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, std::vector< StringRef > &Features)
StringRef getGnuCompatibleMipsABIName (StringRef ABI)
mips::FloatABI getMipsFloatABI (const Driver &D, const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
std::string getMipsABILibSuffix (const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
bool hasMipsAbiArg (const llvm::opt::ArgList &Args, const char *Value)
bool isUCLibc (const llvm::opt::ArgList &Args)
bool isNaN2008 (const Driver &D, const llvm::opt::ArgList &Args, const llvm::Triple &Triple)
bool isFP64ADefault (const llvm::Triple &Triple, StringRef CPUName)
bool isFPXXDefault (const llvm::Triple &Triple, StringRef CPUName, StringRef ABIName, mips::FloatABI FloatABI)
bool shouldUseFPXX (const llvm::opt::ArgList &Args, const llvm::Triple &Triple, StringRef CPUName, StringRef ABIName, mips::FloatABI FloatABI)
bool supportsIndirectJumpHazardBarrier (StringRef &CPU)
Enumeration Type Documentation
FloatABI
enum clang::driver::tools::mips::FloatABI strong
Enumerator
Invalid
Soft
Hard
Definition at line 26 of file Mips.h.
IEEE754Standard
enum clang::driver::tools::mips::IEEE754Standard
Enumerator
Legacy
Std2008
Definition at line 24 of file Mips.h.
Function Documentation
getGnuCompatibleMipsABIName()
StringRef clang::driver::tools::mips::getGnuCompatibleMipsABIName (StringRef ABI)
Definition at line 143 of file Mips.cpp.
Referenced by clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), and clang::driver::tools::gnutools::Assembler::ConstructJob().
getIEEE754Standard()
mips::IEEE754Standard clang::driver::tools::mips::getIEEE754Standard (StringRef & CPU)
Definition at line 402 of file Mips.cpp.
References Legacy, and Std2008.
getMipsABILibSuffix()
std::string clang::driver::tools::mips::getMipsABILibSuffix (const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
Referenced by clang::driver::toolchains::Linux::getDynamicLinker(), and clang::driver::toolchains::MipsLLVMToolChain::MipsLLVMToolChain().
getMipsCPUAndABI()
void clang::driver::tools::mips::getMipsCPUAndABI (const llvm::opt::ArgList & Args, const llvm::Triple & Triple, StringRef & CPUName, StringRef & ABIName)
Referenced by clang::driver::tools::ClangAs::AddMIPSTargetArgs(), clang::driver::tools::netbsd::Assembler::ConstructJob(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::openbsd::Assembler::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), and getOSLibDir().
getMipsFloatABI()
mips::FloatABI clang::driver::tools::mips::getMipsFloatABI (const Driver & D, const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
Referenced by clang::driver::tools::gnutools::Assembler::ConstructJob().
getMIPSTargetFeatures()
void clang::driver::tools::mips::getMIPSTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, std::vector< StringRef > & Features)
Referenced by getTargetFeatures().
hasCompactBranches()
bool clang::driver::tools::mips::hasCompactBranches (StringRef & CPU)
Definition at line 426 of file Mips.cpp.
hasMipsAbiArg()
bool clang::driver::tools::mips::hasMipsAbiArg (const llvm::opt::ArgList & Args, const char * Value)
Referenced by clang::driver::tools::netbsd::Linker::ConstructJob(), clang::driver::tools::freebsd::Linker::ConstructJob(), getLDMOption(), getOSLibDir(), and clang::driver::toolchains::NetBSD::NetBSD().
isFP64ADefault()
bool clang::driver::tools::mips::isFP64ADefault (const llvm::Triple & Triple, StringRef CPUName)
Definition at line 458 of file Mips.cpp.
isFPXXDefault()
bool clang::driver::tools::mips::isFPXXDefault (const llvm::Triple & Triple, StringRef CPUName, StringRef ABIName, mips::FloatABI FloatABI)
Definition at line 468 of file Mips.cpp.
References Soft.
isNaN2008()
bool clang::driver::tools::mips::isNaN2008 (const Driver & D, const llvm::opt::ArgList & Args, const llvm::Triple & Triple)
Referenced by clang::driver::toolchains::Linux::getDynamicLinker().
isUCLibc()
bool clang::driver::tools::mips::isUCLibc (const llvm::opt::ArgList & Args)
Referenced by clang::driver::toolchains::Linux::getDynamicLinker().
shouldUseFPXX()
bool clang::driver::tools::mips::shouldUseFPXX (const llvm::opt::ArgList & Args, const llvm::Triple & Triple, StringRef CPUName, StringRef ABIName, mips::FloatABI FloatABI)
Referenced by clang::driver::tools::gnutools::Assembler::ConstructJob().
supportsIndirectJumpHazardBarrier()
bool clang::driver::tools::mips::supportsIndirectJumpHazardBarrier (StringRef & CPU)
Definition at line 504 of file Mips.cpp.