clang: clang::driver::tools::HIP Namespace Reference
clang::driver::tools::HIP Namespace Reference
Functions
void constructHIPFatbinCommand (Compilation &C, const JobAction &JA, StringRef OutputFileName, const InputInfoList &Inputs, const llvm::opt::ArgList &TCArgs, const Tool &T)
void constructGenerateObjFileFromHIPFatBinary (Compilation &C, const InputInfo &Output, const InputInfoList &Inputs, const llvm::opt::ArgList &Args, const JobAction &JA, const Tool &T)
Function Documentation
constructGenerateObjFileFromHIPFatBinary()
void clang::driver::tools::HIP::constructGenerateObjFileFromHIPFatBinary (Compilation & C, const InputInfo & Output, const InputInfoList & Inputs, const llvm::opt::ArgList & Args, const JobAction & JA, const Tool & T)
Referenced by clang::driver::tools::HIPSPV::Linker::ConstructJob(), and clang::driver::tools::AMDGCN::Linker::ConstructJob().
constructHIPFatbinCommand()
void clang::driver::tools::HIP::constructHIPFatbinCommand (Compilation & C, const JobAction & JA, StringRef OutputFileName, const InputInfoList & Inputs, const llvm::opt::ArgList & TCArgs, const Tool & T)
Referenced by clang::driver::tools::HIPSPV::Linker::ConstructJob(), and clang::driver::tools::AMDGCN::Linker::ConstructJob().