clang: clang::dataflow Namespace Reference
clang::dataflow Namespace Reference
Dataflow Directional Tag Classes.
Classes
class AdornedCFG
Holds CFG with additional information derived from it that is needed to perform dataflow analysis.
class Arena
The Arena owns the objects that model data within an analysis.
class RecordInitListHelper
Helper class for initialization of a record with an InitListExpr.
struct ReferencedDecls
A collection of several types of declarations, all referenced from the same function.
class CFGMatchSwitchBuilder
Collects cases of a "match switch": a collection of matchers paired with callbacks, which together define a switch that can be applied to an AST node contained in a CFG element.
class DataflowAnalysis
Base class template for dataflow analyses built on a single lattice type.
struct DataflowAnalysisState
class DataflowModel
Abstract base class for dataflow "models": reusable analysis components that model a particular aspect of program semantics in the Environment.
struct ContextSensitiveOptions
class DataflowAnalysisContext
Owns objects that encompass the state of a program and stores context that is used during dataflow analysis.
struct WidenResult
The result of a widen operation.
class Environment
Holds the state of the program (store and heap) at a given program point.
struct forward_analysis_tag
struct backward_analysis_tag
class Formula
class Logger
A logger is notified as the analysis progresses.
class MapLattice
A lattice that maps keys to individual lattice elements.
struct TransferState
A common form of state shared between the cases of a transfer function.
struct TransferStateForDiagnostics
A read-only version of TransferState.
class ASTMatchSwitchBuilder
Collects cases of a "match switch": a collection of matchers paired with callbacks, which together define a switch that can be applied to a node whose type derives from BaseT.
class ChromiumCheckModel
Models the behavior of Chromium's CHECK, DCHECK, etc.
struct UncheckedOptionalAccessModelOptions
class UncheckedOptionalAccessModel
Dataflow analysis that models whether optionals hold values or not.
class UncheckedOptionalAccessDiagnoser
class NoopAnalysis
class NoopLattice
Trivial lattice for dataflow analysis with exactly one element.
struct SimplifyConstraintsInfo
Information on the way a set of constraints was simplified.
class Solver
An interface for a SAT solver that can be used by dataflow analyses.
class StorageLocation
Base class for elements of the local variable store and of the heap.
class ScalarStorageLocation
A storage location that is not subdivided further for the purposes of abstract interpretation.
class RecordStorageLocation
A storage location for a record (struct, class, or union).
class StmtToEnvMap
Maps statements to the environments of basic blocks that contain them.
struct DataflowAnalysisOptions
struct TypeErasedLattice
Type-erased lattice element container.
class TypeErasedDataflowAnalysis
Type-erased base class for dataflow analyses built on a single lattice type.
struct TypeErasedDataflowAnalysisState
Type-erased model of the program at a given program point.
class Value
Base class for all values computed by abstract interpretation.
class BoolValue
Models a boolean.
class TopBoolValue
A TopBoolValue represents a boolean that is explicitly unconstrained.
class AtomicBoolValue
Models an atomic boolean.
class FormulaBoolValue
Models a compound boolean formula.
class IntegerValue
Models an integer.
class PointerValue
Models a symbolic pointer. Specifically, any value of type T*.
class WatchedLiteralsSolver
A SAT solver that is an implementation of Algorithm D from Knuth's The Art of Computer Programming Volume 4: Satisfiability, Fascicle 6.
struct CNFFormula
A boolean formula in conjunctive normal form.
struct CNFFormulaBuilder
Applies simplifications while building up a BooleanFormula.
class WatchedLiteralsSolverImpl
Typedefs
using FieldSet = llvm::SmallSetVector< const FieldDecl *, 4 >
A set of FieldDecl *.
template<typename State , typename Result = void>
using CFGMatchSwitch = std::function< Result(const CFGElement &, ASTContext &, State &)>
using LatticeJoinEffect = LatticeEffect
template<typename ElementLattice >
using VarMapLattice = MapLattice< const clang::VarDecl *, ElementLattice >
Convenience alias that captures the common use of map lattices to model in-scope variables.
template<typename T >
using MatchSwitchMatcher = ast_matchers::internal::Matcher< T >
template<typename T , typename State , typename Result = void>
using MatchSwitchAction = std::function< Result(const T *, const ast_matchers::MatchFinder::MatchResult &, State &)>
template<typename BaseT , typename State , typename Result = void>
using ASTMatchSwitch = std::function< Result(const BaseT &, ASTContext &, State &)>
using Variable = uint32_t
Boolean variables are represented as positive integers.
using Literal = uint32_t
Literals are represented as positive integers.
using ClauseID = uint32_t
Clause identifiers are represented as positive integers.
Enumerations
enum class ComparisonResult { Same , Different , Unknown }
Indicates the result of a tentative comparison.
enum class LatticeEffect { Unchanged , Changed }
Effect indicating whether a lattice operation resulted in a new value.
enum class Atom : unsigned
Identifies an atomic boolean variable such as "V1".
Functions
const Expr & ignoreCFGOmittedNodes (const Expr &E)
Skip past nodes that the CFG does not emit.
const Stmt & ignoreCFGOmittedNodes (const Stmt &S)
FieldSet getObjectFields (QualType Type)
Returns the set of all fields in the type.
bool containsSameFields (const FieldSet &Fields, const RecordStorageLocation::FieldToLoc &FieldLocs)
Returns whether Fields and FieldLocs contain the same fields.
ReferencedDecls getReferencedDecls (const FunctionDecl &FD)
Returns declarations that are declared in or referenced from FD.
ReferencedDecls getReferencedDecls (const Stmt &S)
Returns declarations that are declared in or referenced from S.
template<typename AnalysisT >
llvm::Expected< std::vector< std::optional< DataflowAnalysisState< typename AnalysisT::Lattice > > > > runDataflowAnalysis (const AdornedCFG &ACFG, AnalysisT &Analysis, const Environment &InitEnv, std::function< void(const CFGElement &, const DataflowAnalysisState< typename AnalysisT::Lattice > &)> PostVisitCFG=nullptr, std::int32_t MaxBlockVisits=20 '000)
Performs dataflow analysis and returns a mapping from basic block IDs to dataflow analysis states that model the respective basic blocks.
template<typename AnalysisT >
auto createAnalysis (ASTContext &ASTCtx, Environment &Env) -> decltype(AnalysisT(ASTCtx, Env))
template<typename AnalysisT , typename Diagnostic >
llvm::Expected< llvm::SmallVector< Diagnostic > > diagnoseFunction (const FunctionDecl &FuncDecl, ASTContext &ASTCtx, llvm::function_ref< llvm::SmallVector< Diagnostic >(const CFGElement &, ASTContext &, const TransferStateForDiagnostics< typename AnalysisT::Lattice > &)> Diagnoser, std::int64_t MaxSATIterations=1 '000 '000 '000, std::int32_t MaxBlockVisits=20 '000)
Runs a dataflow analysis over the given function and then runs Diagnoser over the results.
RecordStorageLocation * getImplicitObjectLocation (const CXXMemberCallExpr &MCE, const Environment &Env)
Returns the storage location for the implicit object of a CXXMemberCallExpr, or null if none is defined in the environment.
RecordStorageLocation * getBaseObjectLocation (const MemberExpr &ME, const Environment &Env)
Returns the storage location for the base object of a MemberExpr, or null if none is defined in the environment.
llvm::StringRef debugString (Value::Kind Kind)
Returns a string representation of a value kind.
llvm::StringRef debugString (Solver::Result::Status Status)
Returns a string representation of the result status of a SAT check.
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, Atom A)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Formula &F)
template<typename Key , typename ElementLattice >
std::ostream & operator<< (std::ostream &Os, const clang::dataflow::MapLattice< Key, ElementLattice > &M)
template<typename ElementLattice >
std::ostream & operator<< (std::ostream &Os, const clang::dataflow::VarMapLattice< ElementLattice > &M)
std::ostream & operator<< (std::ostream &OS, const NoopLattice &)
void copyRecord (RecordStorageLocation &Src, RecordStorageLocation &Dst, Environment &Env)
Copies a record (struct, class, or union) from Src to Dst.
bool recordsEqual (const RecordStorageLocation &Loc1, const Environment &Env1, const RecordStorageLocation &Loc2, const Environment &Env2)
Returns whether the records Loc1 and Loc2 are equal.
bool recordsEqual (const RecordStorageLocation &Loc1, const RecordStorageLocation &Loc2, const Environment &Env)
void simplifyConstraints (llvm::SetVector< const Formula * > &Constraints, Arena &arena, SimplifyConstraintsInfo *Info=nullptr)
Simplifies a set of constraints (implicitly connected by "and") in a way that does not change satisfiability of the constraints.
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const Solver::Result &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, Solver::Result::Assignment)
void transfer (const StmtToEnvMap &StmtToEnv, const Stmt &S, Environment &Env, Environment::ValueModel &Model)
Evaluates S and updates Env accordingly.
llvm::Expected< std::vector< std::optional< TypeErasedDataflowAnalysisState > > > runTypeErasedDataflowAnalysis (const AdornedCFG &ACFG, TypeErasedDataflowAnalysis &Analysis, const Environment &InitEnv, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG, std::int32_t MaxBlockVisits)
Performs dataflow analysis and returns a mapping from basic block IDs to dataflow analysis states that model the respective basic blocks.
bool areEquivalentValues (const Value &Val1, const Value &Val2)
An equivalence relation for values.
raw_ostream & operator<< (raw_ostream &OS, const Value &Val)
static llvm::DenseMap< const Stmt *, const CFGBlock * > buildStmtToBasicBlockMap (const CFG &Cfg)
Returns a map from statements to basic blocks that contain them.
static llvm::BitVector findReachableBlocks (const CFG &Cfg)
static llvm::DenseSet< const CFGBlock * > buildContainsExprConsumedInDifferentBlock (const CFG &Cfg, const llvm::DenseMap< const Stmt *, const CFGBlock * > &StmtToBlock)
static std::pair< const Formula *, const Formula * > canonicalFormulaPair (const Formula &LHS, const Formula &RHS)
template<class Key , class ComputeFunc >
const Formula & cached (llvm::DenseMap< Key, const Formula * > &Cache, Key K, ComputeFunc &&Compute)
static void getFieldsFromClassHierarchy (QualType Type, FieldSet &Fields)
template<class InitListT >
static std::vector< const FieldDecl * > getFieldsForInitListExpr (const InitListT *InitList)
Returns the fields of a RecordDecl that are initialized by an InitListExpr or CXXParenListInitExpr, in the order in which they appear in InitListExpr::inits() / CXXParenListInitExpr::getInitExprs().
static void insertIfGlobal (const Decl &D, llvm::DenseSet< const VarDecl * > &Globals)
static void insertIfFunction (const Decl &D, llvm::DenseSet< const FunctionDecl * > &Funcs)
static MemberExpr * getMemberForAccessor (const CXXMemberCallExpr &C)
static void getReferencedDecls (const Decl &D, ReferencedDecls &Referenced)
static void getReferencedDecls (const Stmt &S, ReferencedDecls &Referenced)
Traverses S and inserts into Referenced any declarations that are declared in or referenced from sub-statements.
template<typename T >
static llvm::DenseSet< llvm::StringRef > getKeys (const llvm::StringMap< T > &Map)
static void printAtomList (const llvm::SmallVector< Atom > &Atoms, llvm::raw_ostream &OS)
static std::unique_ptr< Logger > makeLoggerFromCommandLine ()
static llvm::DenseMap< const ValueDecl *, StorageLocation * > intersectDeclToLoc (const llvm::DenseMap< const ValueDecl *, StorageLocation * > &DeclToLoc1, const llvm::DenseMap< const ValueDecl *, StorageLocation * > &DeclToLoc2)
Returns a map consisting of key-value entries that are present in both maps.
template<typename MapT >
MapT joinExprMaps (const MapT &Map1, const MapT &Map2)
static bool equateUnknownValues (Value::Kind K)
static bool compareDistinctValues (QualType Type, Value &Val1, const Environment &Env1, Value &Val2, const Environment &Env2, Environment::ValueModel &Model)
static Value * joinDistinctValues (QualType Type, Value &Val1, const Environment &Env1, Value &Val2, const Environment &Env2, Environment &JoinedEnv, Environment::ValueModel &Model)
Attempts to join distinct values Val1 and Val2 in Env1 and Env2, respectively, of the same type Type.
static WidenResult widenDistinctValues (QualType Type, Value &Prev, const Environment &PrevEnv, Value &Current, Environment &CurrentEnv, Environment::ValueModel &Model)
template<typename Key >
bool compareKeyToValueMaps (const llvm::MapVector< Key, Value * > &Map1, const llvm::MapVector< Key, Value * > &Map2, const Environment &Env1, const Environment &Env2, Environment::ValueModel &Model)
static llvm::MapVector< const StorageLocation *, Value * > joinLocToVal (const llvm::MapVector< const StorageLocation *, Value * > &LocToVal, const llvm::MapVector< const StorageLocation *, Value * > &LocToVal2, const Environment &Env1, const Environment &Env2, Environment &JoinedEnv, Environment::ValueModel &Model)
template<typename Key >
llvm::MapVector< Key, Value * > widenKeyToValueMap (const llvm::MapVector< Key, Value * > &CurMap, const llvm::MapVector< Key, Value * > &PrevMap, Environment &CurEnv, const Environment &PrevEnv, Environment::ValueModel &Model, LatticeEffect &Effect)
static llvm::StringLiteral sigil (Formula::Kind K)
bool isCheckLikeMethod (llvm::SmallDenseSet< const CXXMethodDecl * > &CheckDecls, const CXXMethodDecl &D)
Determines whether D is one of the methods used to implement Chromium's CHECK macros.
static bool isTopLevelNamespaceWithName (const NamespaceDecl &NS, llvm::StringRef Name)
static bool hasOptionalClassName (const CXXRecordDecl &RD)
static const CXXRecordDecl * getOptionalBaseClass (const CXXRecordDecl *RD)
static void copyField (const ValueDecl &Field, StorageLocation *SrcFieldLoc, StorageLocation *DstFieldLoc, RecordStorageLocation &Dst, Environment &Env)
static void copySyntheticField (QualType FieldType, StorageLocation &SrcFieldLoc, StorageLocation &DstFieldLoc, Environment &Env)
static const Formula & substitute (const Formula &F, const llvm::DenseMap< Atom, const Formula * > &Substitutions, Arena &arena)
static llvm::DenseSet< Atom > projectToLeaders (const llvm::DenseSet< Atom > &Atoms, llvm::EquivalenceClasses< Atom > &EquivalentAtoms)
static llvm::SmallVector< Atom > atomsInEquivalenceClass (const llvm::EquivalenceClasses< Atom > &EquivalentAtoms, llvm::EquivalenceClasses< Atom >::iterator LeaderIt)
static BoolValue & evaluateBooleanEquality (const Expr &LHS, const Expr &RHS, Environment &Env)
static BoolValue & unpackValue (BoolValue &V, Environment &Env)
static Value * maybeUnpackLValueExpr (const Expr &E, Environment &Env)
static void propagateValue (const Expr &From, const Expr &To, Environment &Env)
static void propagateStorageLocation (const Expr &From, const Expr &To, Environment &Env)
static void propagateValueOrStorageLocation (const Expr &From, const Expr &To, Environment &Env)
static int blockIndexInPredecessor (const CFGBlock &Pred, const CFGBlock &Block)
Returns the index of Block in the successors of Pred.
static bool isBackedgeNode (const CFGBlock &B)
static const Expr * getTerminatorCondition (const Stmt *TerminatorStmt)
static TypeErasedDataflowAnalysisState computeBlockInputState (const CFGBlock &Block, AnalysisContext &AC)
Computes the input state for a given basic block by joining the output states of its predecessors.
static void builtinTransferStatement (unsigned CurBlockID, const CFGStmt &Elt, TypeErasedDataflowAnalysisState &InputState, AnalysisContext &AC)
Built-in transfer function for CFGStmt.
static void builtinTransferInitializer (const CFGInitializer &Elt, TypeErasedDataflowAnalysisState &InputState)
Built-in transfer function for CFGInitializer.
static void builtinTransfer (unsigned CurBlockID, const CFGElement &Elt, TypeErasedDataflowAnalysisState &State, AnalysisContext &AC)
static TypeErasedDataflowAnalysisState transferCFGBlock (const CFGBlock &Block, AnalysisContext &AC, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG=nullptr)
Transfers State by evaluating each element in the Block based on the AC.Analysis specified.
static bool areEquivalentIndirectionValues (const Value &Val1, const Value &Val2)
static constexpr Literal posLit (Variable V)
Returns the positive literal V.
static constexpr bool isPosLit (Literal L)
static constexpr bool isNegLit (Literal L)
static constexpr Literal negLit (Variable V)
Returns the negative literal !V.
static constexpr Literal notLit (Literal L)
Returns the negated literal !L.
static constexpr Variable var (Literal L)
Returns the variable of L.
CNFFormula buildCNF (const llvm::ArrayRef< const Formula * > &Vals)
Converts the conjunction of Vals into a formula in conjunctive normal form where each clause has at least one and at most three literals.
Variables
static constexpr int MaxCompositeValueDepth = 3
static constexpr int MaxCompositeValueSize = 1000
static constexpr Variable NullVar = 0
A null boolean variable is used as a placeholder in various data structures and algorithms.
static constexpr Literal NullLit = 0
A null literal is used as a placeholder in various data structures and algorithms.
static constexpr ClauseID NullClause = 0
A null clause identifier is used as a placeholder in various data structures and algorithms.
Detailed Description
Dataflow Directional Tag Classes.
These are used for tag dispatching within the dataflow solver/transfer functions to determine what direction a dataflow analysis flows.
Typedef Documentation
ASTMatchSwitch
template<typename BaseT , typename State , typename Result = void> using clang::dataflow::ASTMatchSwitch = typedef std::function<Result(const BaseT &, ASTContext &, State &)>
Definition at line 72 of file MatchSwitch.h.
CFGMatchSwitch
template<typename State , typename Result = void> using clang::dataflow::CFGMatchSwitch = typedef std::function<Result(const CFGElement &, ASTContext &, State &)>
Definition at line 33 of file CFGMatchSwitch.h.
ClauseID
using clang::dataflow::ClauseID = typedef uint32_t
Clause identifiers are represented as positive integers.
Definition at line 81 of file WatchedLiteralsSolver.cpp.
FieldSet
using clang::dataflow::FieldSet = typedef llvm::SmallSetVector<const FieldDecl *, 4>
A set of FieldDecl *.
Use SmallSetVector to guarantee deterministic iteration order.
Definition at line 41 of file ASTOps.h.
LatticeJoinEffect
using clang::dataflow::LatticeJoinEffect = typedef LatticeEffect
Definition at line 26 of file DataflowLattice.h.
Literal
using clang::dataflow::Literal = typedef uint32_t
Literals are represented as positive integers.
Specifically, for a boolean variable V that is represented as the positive integer I, the positive literal V is represented as the integer 2*I and the negative literal !V is represented as the integer 2*I+1.
Definition at line 58 of file WatchedLiteralsSolver.cpp.
MatchSwitchAction
template<typename T , typename State , typename Result = void> using clang::dataflow::MatchSwitchAction = typedef std::function<Result(const T *, const ast_matchers::MatchFinder::MatchResult &, State &)>
Definition at line 68 of file MatchSwitch.h.
MatchSwitchMatcher
template<typename T > using clang::dataflow::MatchSwitchMatcher = typedef ast_matchers::internal::Matcher<T>
Definition at line 65 of file MatchSwitch.h.
Variable
using clang::dataflow::Variable = typedef uint32_t
Boolean variables are represented as positive integers.
Definition at line 48 of file WatchedLiteralsSolver.cpp.
VarMapLattice
template<typename ElementLattice > using clang::dataflow::VarMapLattice = typedef MapLattice<const clang::VarDecl *, ElementLattice>
Convenience alias that captures the common use of map lattices to model in-scope variables.
Definition at line 112 of file MapLattice.h.
Enumeration Type Documentation
Atom
enum clang::dataflow::Atom : unsigned strong
Identifies an atomic boolean variable such as "V1".
This often represents an assertion that is interesting to the analysis but cannot immediately be proven true or false. For example:
V1 may mean "the program reaches this point",
V2 may mean "the parameter was null"
We can use these variables in formulas to describe relationships we know to be true: "if the parameter was null, the program reaches this point". We also express hypotheses as formulas, and use a SAT solver to check whether they are consistent with the known facts.
Definition at line 34 of file Formula.h.
ComparisonResult
enum clang::dataflow::ComparisonResult strong
Indicates the result of a tentative comparison.
Enumerator
Same
Different
Unknown
Definition at line 41 of file DataflowEnvironment.h.
LatticeEffect
enum clang::dataflow::LatticeEffect strong
Effect indicating whether a lattice operation resulted in a new value.
Enumerator
Unchanged
Changed
Definition at line 21 of file DataflowLattice.h.
Function Documentation
areEquivalentIndirectionValues()
static bool clang::dataflow::areEquivalentIndirectionValues (const Value & Val1, const Value & Val2) static
Definition at line 20 of file Value.cpp.
Referenced by areEquivalentValues().
areEquivalentValues()
bool clang::dataflow::areEquivalentValues (const Value & Val1, const Value & Val2)
An equivalence relation for values.
It obeys reflexivity, symmetry and transitivity. It does not include comparison of Properties.
Computes equivalence for these subclasses:
PointerValue – pointee locations are equal. Does not compute deep equality of Value at said location.
TopBoolValue – both are TopBoolValues.
Otherwise, falls back to pointer equality.
Definition at line 29 of file Value.cpp.
References areEquivalentIndirectionValues(), clang::dataflow::Value::getKind(), and clang::dataflow::Value::properties().
atomsInEquivalenceClass()
static llvm::SmallVector<Atom> clang::dataflow::atomsInEquivalenceClass (const llvm::EquivalenceClasses< Atom > & EquivalentAtoms, llvm::EquivalenceClasses< Atom >::iterator LeaderIt) static
Definition at line 66 of file SimplifyConstraints.cpp.
Referenced by simplifyConstraints().
blockIndexInPredecessor()
static int clang::dataflow::blockIndexInPredecessor (const CFGBlock & Pred, const CFGBlock & Block) static
Returns the index of Block in the successors of Pred.
Definition at line 44 of file TypeErasedDataflowAnalysis.cpp.
References Block, clang::CFGBlock::succ_begin(), and clang::CFGBlock::succs().
buildCNF()
CNFFormula clang::dataflow::buildCNF (const llvm::ArrayRef< const Formula * > & Vals)
Converts the conjunction of Vals into a formula in conjunctive normal form where each clause has at least one and at most three literals.
Definition at line 261 of file WatchedLiteralsSolver.cpp.
References clang::dataflow::CNFFormulaBuilder::addClause(), clang::dataflow::CNFFormula::addClause(), clang::dataflow::Formula::And, clang::dataflow::CNFFormula::Atomics, clang::dataflow::Formula::AtomRef, clang::dataflow::CNFFormula::clauseLiterals(), clang::dataflow::CNFFormula::clauseSize(), clang::dataflow::CNFFormula::ClauseStarts, clang::dataflow::Formula::Equal, clang::dataflow::Formula::getAtom(), clang::dataflow::Formula::Implies, clang::dataflow::CNFFormulaBuilder::isKnownContradictory(), clang::dataflow::Formula::kind(), clang::dataflow::Formula::Literal, clang::dataflow::Formula::literal(), negLit(), clang::dataflow::Formula::Not, clang::dataflow::Formula::operands(), clang::dataflow::Formula::Or, and posLit().
buildContainsExprConsumedInDifferentBlock()
static llvm::DenseSet<const CFGBlock *> clang::dataflow::buildContainsExprConsumedInDifferentBlock (const CFG & Cfg, const llvm::DenseMap< const Stmt *, const CFGBlock * > & StmtToBlock) static
Definition at line 98 of file AdornedCFG.cpp.
buildStmtToBasicBlockMap()
static llvm::DenseMap<const Stmt *, const CFGBlock *> clang::dataflow::buildStmtToBasicBlockMap (const CFG & Cfg) static
Returns a map from statements to basic blocks that contain them.
Definition at line 29 of file AdornedCFG.cpp.
References Block.
builtinTransfer()
static void clang::dataflow::builtinTransfer (unsigned CurBlockID, const CFGElement & Elt, TypeErasedDataflowAnalysisState & State, AnalysisContext & AC) static
Definition at line 379 of file TypeErasedDataflowAnalysis.cpp.
builtinTransferInitializer()
static void clang::dataflow::builtinTransferInitializer (const CFGInitializer & Elt, TypeErasedDataflowAnalysisState & InputState) static
Built-in transfer function for CFGInitializer.
Definition at line 324 of file TypeErasedDataflowAnalysis.cpp.
References clang::IndirectFieldDecl::chain(), clang::dataflow::TypeErasedDataflowAnalysisState::Env, Env, clang::dataflow::RecordStorageLocation::getChild(), clang::CFGInitializer::getInitializer(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getThisPointeeStorageLocation(), clang::dataflow::Environment::getValue(), clang::Member, clang::dataflow::RecordStorageLocation::setChild(), and clang::dataflow::Environment::setValue().
builtinTransferStatement()
static void clang::dataflow::builtinTransferStatement (unsigned CurBlockID, const CFGStmt & Elt, TypeErasedDataflowAnalysisState & InputState, AnalysisContext & AC) static
Built-in transfer function for CFGStmt.
Definition at line 313 of file TypeErasedDataflowAnalysis.cpp.
cached()
template<class Key , class ComputeFunc > const Formula& clang::dataflow::cached (llvm::DenseMap< Key, const Formula * > & Cache, Key K, ComputeFunc && Compute)
Definition at line 26 of file Arena.cpp.
References clang::Compute.
Referenced by clang::dataflow::Arena::makeAnd(), clang::dataflow::Arena::makeAtomRef(), clang::dataflow::Arena::makeEquals(), clang::dataflow::Arena::makeImplies(), clang::dataflow::Arena::makeNot(), and clang::dataflow::Arena::makeOr().
canonicalFormulaPair()
static std::pair<const Formula *, const Formula *> clang::dataflow::canonicalFormulaPair (const Formula & LHS, const Formula & RHS) static
Definition at line 18 of file Arena.cpp.
Referenced by clang::dataflow::Arena::makeAnd(), clang::dataflow::Arena::makeEquals(), and clang::dataflow::Arena::makeOr().
compareDistinctValues()
static bool clang::dataflow::compareDistinctValues (QualType Type, Value & Val1, const Environment & Env1, Value & Val2, const Environment & Env2, Environment::ValueModel & Model) static
Definition at line 90 of file DataflowEnvironment.cpp.
compareKeyToValueMaps()
template<typename Key > bool clang::dataflow::compareKeyToValueMaps (const llvm::MapVector< Key, Value * > & Map1, const llvm::MapVector< Key, Value * > & Map2, const Environment & Env1, const Environment & Env2, Environment::ValueModel & Model)
Definition at line 196 of file DataflowEnvironment.cpp.
computeBlockInputState()
static TypeErasedDataflowAnalysisState clang::dataflow::computeBlockInputState (const CFGBlock & Block, AnalysisContext & AC) static
Computes the input state for a given basic block by joining the output states of its predecessors.
Requirements:
All predecessors of Block except those with loop back edges must have already been transferred. States in AC.BlockStates that are set to std::nullopt represent basic blocks that are not evaluated yet.
Definition at line 219 of file TypeErasedDataflowAnalysis.cpp.
containsSameFields()
bool clang::dataflow::containsSameFields (const FieldSet & Fields, const RecordStorageLocation::FieldToLoc & FieldLocs)
Returns whether Fields and FieldLocs contain the same fields.
Definition at line 72 of file ASTOps.cpp.
Referenced by clang::dataflow::DataflowAnalysisContext::createRecordStorageLocation().
copyField()
static void clang::dataflow::copyField (const ValueDecl & Field, StorageLocation * SrcFieldLoc, StorageLocation * DstFieldLoc, RecordStorageLocation & Dst, Environment & Env) static
Definition at line 19 of file RecordOps.cpp.
References clang::dataflow::Environment::clearValue(), copyRecord(), Env, clang::dataflow::Environment::getValue(), clang::dataflow::RecordStorageLocation::setChild(), and clang::dataflow::Environment::setValue().
Referenced by copyRecord().
copyRecord()
void clang::dataflow::copyRecord (RecordStorageLocation & Src, RecordStorageLocation & Dst, Environment & Env)
Copies a record (struct, class, or union) from Src to Dst.
This performs a deep copy, i.e. it copies every field (including synthetic fields) and recurses on fields of record type.
If there is a RecordValue associated with Dst in the environment, this function creates a new RecordValue and associates it with Dst; clients need to be aware of this and must not assume that the RecordValue associated with Dst remains the same after the call.
Requirements:
Either:
Src and Dest must have the same canonical unqualified type, or
The type of Src must be derived from Dest, or
The type of Dest must be derived from Src (in this case, any fields that are only present in Dest are not overwritten).
Definition at line 51 of file RecordOps.cpp.
References clang::dataflow::RecordStorageLocation::children(), copyField(), Env, clang::Type::getAsCXXRecordDecl(), clang::QualType::getCanonicalType(), clang::dataflow::RecordStorageLocation::getChild(), clang::dataflow::StorageLocation::getType(), and clang::QualType::getUnqualifiedType().
Referenced by copyField(), and copySyntheticField().
copySyntheticField()
static void clang::dataflow::copySyntheticField (QualType FieldType, StorageLocation & SrcFieldLoc, StorageLocation & DstFieldLoc, Environment & Env) static
Definition at line 38 of file RecordOps.cpp.
References clang::dataflow::Environment::clearValue(), copyRecord(), Env, clang::dataflow::Environment::getValue(), clang::Type::isRecordType(), and clang::dataflow::Environment::setValue().
createAnalysis()
template<typename AnalysisT > auto clang::dataflow::createAnalysis (ASTContext & ASTCtx, Environment & Env) -> decltype(AnalysisT(ASTCtx, Env))
Definition at line 248 of file DataflowAnalysis.h.
References Env.
debugString() [1/2]
llvm::StringRef clang::dataflow::debugString (Solver::Result::Status Status)
Returns a string representation of the result status of a SAT check.
Definition at line 52 of file DebugSupport.cpp.
debugString() [2/2]
llvm::StringRef clang::dataflow::debugString (Value::Kind Kind)
Returns a string representation of a value kind.
Definition at line 25 of file DebugSupport.cpp.
References clang::dataflow::Value::AtomicBool, clang::dataflow::Value::FormulaBool, clang::dataflow::Value::Integer, clang::dataflow::Value::Pointer, and clang::dataflow::Value::TopBool.
Referenced by operator<<().
diagnoseFunction()
template<typename AnalysisT , typename Diagnostic > llvm::Expected<llvm::SmallVector<Diagnostic> > clang::dataflow::diagnoseFunction (const FunctionDecl & FuncDecl, ASTContext & ASTCtx, llvm::function_ref< llvm::SmallVector< Diagnostic >(const CFGElement &, ASTContext &, const TransferStateForDiagnostics< typename AnalysisT::Lattice > &)> Diagnoser, std::int64_t MaxSATIterations = 1'000'000'000, std::int32_t MaxBlockVisits = 20'000)
Runs a dataflow analysis over the given function and then runs Diagnoser over the results.
Returns a list of diagnostics for FuncDecl or an error. Currently, errors can occur (at least) because the analysis requires too many iterations over the CFG or the SAT solver times out.
The default value of MaxSATIterations was chosen based on the following observations:
Non-pathological calls to the solver typically require only a few hundred iterations.
This limit is still low enough to keep runtimes acceptable (on typical machines) in cases where we hit the limit.
MaxBlockVisits caps the number of block visits during analysis. See runDataflowAnalysis for a full description and explanation of the default value.
Definition at line 274 of file DataflowAnalysis.h.
equateUnknownValues()
static bool clang::dataflow::equateUnknownValues (Value::Kind K) static
Definition at line 80 of file DataflowEnvironment.cpp.
References clang::dataflow::Value::Integer, and clang::dataflow::Value::Pointer.
evaluateBooleanEquality()
static BoolValue& clang::dataflow::evaluateBooleanEquality (const Expr & LHS, const Expr & RHS, Environment & Env) static
Definition at line 55 of file Transfer.cpp.
References Env, clang::dataflow::Environment::getBoolLiteralValue(), clang::dataflow::Environment::getValue(), clang::dataflow::Environment::makeAtomicBoolValue(), and clang::dataflow::Environment::makeIff().
findReachableBlocks()
static llvm::BitVector clang::dataflow::findReachableBlocks (const CFG & Cfg) static
Definition at line 75 of file AdornedCFG.cpp.
References Block, clang::CFG::getEntry(), and clang::CFG::getNumBlockIDs().
getBaseObjectLocation()
RecordStorageLocation * clang::dataflow::getBaseObjectLocation (const MemberExpr & ME, const Environment & Env)
Returns the storage location for the base object of a MemberExpr, or null if none is defined in the environment.
Dereferences the pointer if the member expression was written using ->.
Definition at line 1228 of file DataflowEnvironment.cpp.
References Env, clang::dataflow::Environment::get(), clang::MemberExpr::getBase(), and clang::MemberExpr::isArrow().
getFieldsForInitListExpr()
template<class InitListT > static std::vector<const FieldDecl *> clang::dataflow::getFieldsForInitListExpr (const InitListT * InitList) static
Returns the fields of a RecordDecl that are initialized by an InitListExpr or CXXParenListInitExpr, in the order in which they appear in InitListExpr::inits() / CXXParenListInitExpr::getInitExprs().
InitList->getType() must be a record type.
Definition at line 88 of file ASTOps.cpp.
References clang::RecordDecl::fields().
getFieldsFromClassHierarchy()
static void clang::dataflow::getFieldsFromClassHierarchy (QualType Type, FieldSet & Fields) static
Definition at line 53 of file ASTOps.cpp.
References clang::RecordDecl::fields(), clang::Type::getAsCXXRecordDecl(), clang::Type::getAsRecordDecl(), clang::Type::isDependentType(), clang::Type::isIncompleteType(), and clang::Type::isRecordType().
Referenced by getObjectFields().
getImplicitObjectLocation()
RecordStorageLocation * clang::dataflow::getImplicitObjectLocation (const CXXMemberCallExpr & MCE, const Environment & Env)
Returns the storage location for the implicit object of a CXXMemberCallExpr, or null if none is defined in the environment.
Dereferences the pointer if the member call expression was written using ->.
Definition at line 1214 of file DataflowEnvironment.cpp.
References Env, clang::dataflow::Environment::get(), clang::CXXMemberCallExpr::getImplicitObjectArgument(), clang::dataflow::Environment::getStorageLocation(), clang::Expr::getType(), and clang::Type::isPointerType().
getKeys()
template<typename T > static llvm::DenseSet<llvm::StringRef> clang::dataflow::getKeys (const llvm::StringMap< T > & Map) static
Definition at line 88 of file DataflowAnalysisContext.cpp.
Referenced by clang::dataflow::DataflowAnalysisContext::createRecordStorageLocation().
getMemberForAccessor()
static MemberExpr* clang::dataflow::getMemberForAccessor (const CXXMemberCallExpr & C) static
Definition at line 168 of file ASTOps.cpp.
getObjectFields()
FieldSet clang::dataflow::getObjectFields (QualType Type)
Returns the set of all fields in the type.
Gets the set of all fields in the type.
Definition at line 66 of file ASTOps.cpp.
References getFieldsFromClassHierarchy().
Referenced by clang::dataflow::DataflowAnalysisContext::getModeledFields().
getOptionalBaseClass()
static const CXXRecordDecl* clang::dataflow::getOptionalBaseClass (const CXXRecordDecl * RD) static
Definition at line 67 of file UncheckedOptionalAccessModel.cpp.
References clang::CXXRecordDecl::bases(), clang::CXXRecordDecl::hasDefinition(), and hasOptionalClassName().
Referenced by clang::dataflow::UncheckedOptionalAccessModel::UncheckedOptionalAccessModel().
getReferencedDecls() [1/4]
static void clang::dataflow::getReferencedDecls (const Decl & D, ReferencedDecls & Referenced) static
Definition at line 183 of file ASTOps.cpp.
References clang::dataflow::ReferencedDecls::Fields, clang::dataflow::ReferencedDecls::Functions, clang::dataflow::ReferencedDecls::Globals, insertIfFunction(), and insertIfGlobal().
getReferencedDecls() [2/4]
ReferencedDecls clang::dataflow::getReferencedDecls (const FunctionDecl & FD)
Returns declarations that are declared in or referenced from FD.
Definition at line 238 of file ASTOps.cpp.
References clang::RecordDecl::fields(), clang::FunctionDecl::getBody(), and clang::FieldDecl::getParent().
getReferencedDecls() [3/4]
ReferencedDecls clang::dataflow::getReferencedDecls (const Stmt & S)
Returns declarations that are declared in or referenced from S.
Definition at line 264 of file ASTOps.cpp.
getReferencedDecls() [4/4]
static void clang::dataflow::getReferencedDecls (const Stmt & S, ReferencedDecls & Referenced) static
Traverses S and inserts into Referenced any declarations that are declared in or referenced from sub-statements.
Definition at line 196 of file ASTOps.cpp.
getTerminatorCondition()
static const Expr* clang::dataflow::getTerminatorCondition (const Stmt * TerminatorStmt) static
Definition at line 205 of file TypeErasedDataflowAnalysis.cpp.
hasOptionalClassName()
static bool clang::dataflow::hasOptionalClassName (const CXXRecordDecl & RD) static
Definition at line 47 of file UncheckedOptionalAccessModel.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::NamedDecl::getName(), clang::DeclarationName::isIdentifier(), and isTopLevelNamespaceWithName().
Referenced by getOptionalBaseClass().
ignoreCFGOmittedNodes() [1/2]
const Expr & clang::dataflow::ignoreCFGOmittedNodes (const Expr & E)
Skip past nodes that the CFG does not emit.
These nodes are invisible to flow-sensitive analysis, and should be ignored as they will effectively not exist.
ParenExpr - The CFG takes the operator precedence into account, but otherwise omits the node afterwards.
ExprWithCleanups - The CFG will generate the appropriate calls to destructors and then omit the node.
Definition at line 34 of file ASTOps.cpp.
Referenced by clang::dataflow::DataflowAnalysisContext::getStableStorageLocation(), clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getValue(), clang::dataflow::Environment::setStorageLocation(), and clang::dataflow::Environment::setValue().
ignoreCFGOmittedNodes() [2/2]
const Stmt & clang::dataflow::ignoreCFGOmittedNodes (const Stmt & S)
Definition at line 45 of file ASTOps.cpp.
insertIfFunction()
static void clang::dataflow::insertIfFunction (const Decl & D, llvm::DenseSet< const FunctionDecl * > & Funcs) static
Definition at line 162 of file ASTOps.cpp.
Referenced by getReferencedDecls().
insertIfGlobal()
static void clang::dataflow::insertIfGlobal (const Decl & D, llvm::DenseSet< const VarDecl * > & Globals) static
Definition at line 155 of file ASTOps.cpp.
References V.
Referenced by getReferencedDecls().
intersectDeclToLoc()
static llvm::DenseMap<const ValueDecl *, StorageLocation *> clang::dataflow::intersectDeclToLoc (const llvm::DenseMap< const ValueDecl *, StorageLocation * > & DeclToLoc1, const llvm::DenseMap< const ValueDecl *, StorageLocation * > & DeclToLoc2) static
Returns a map consisting of key-value entries that are present in both maps.
Definition at line 44 of file DataflowEnvironment.cpp.
isBackedgeNode()
static bool clang::dataflow::isBackedgeNode (const CFGBlock & B) static
Definition at line 59 of file TypeErasedDataflowAnalysis.cpp.
References clang::CFGBlock::getLoopTarget().
isCheckLikeMethod()
bool clang::dataflow::isCheckLikeMethod (llvm::SmallDenseSet< const CXXMethodDecl * > & CheckDecls, const CXXMethodDecl & D)
Determines whether D is one of the methods used to implement Chromium's CHECK macros.
Populates CheckDecls, if empty.
Definition at line 19 of file ChromiumCheckModel.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::NamedDecl::getName(), clang::CXXMethodDecl::getParent(), clang::DeclarationName::isIdentifier(), clang::CXXMethodDecl::isStatic(), and clang::CXXRecordDecl::methods().
isNegLit()
static constexpr bool clang::dataflow::isNegLit (Literal L) static constexpr
Definition at line 69 of file WatchedLiteralsSolver.cpp.
isPosLit()
static constexpr bool clang::dataflow::isPosLit (Literal L) static constexpr
Definition at line 67 of file WatchedLiteralsSolver.cpp.
isTopLevelNamespaceWithName()
static bool clang::dataflow::isTopLevelNamespaceWithName (const NamespaceDecl & NS, llvm::StringRef Name) static
Definition at line 41 of file UncheckedOptionalAccessModel.cpp.
Referenced by hasOptionalClassName().
joinDistinctValues()
static Value* clang::dataflow::joinDistinctValues (QualType Type, Value & Val1, const Environment & Env1, Value & Val2, const Environment & Env2, Environment & JoinedEnv, Environment::ValueModel & Model) static
Attempts to join distinct values Val1 and Val2 in Env1 and Env2, respectively, of the same type Type.
Joining generally produces a single value that (soundly) approximates the two inputs, although the actual meaning depends on Model.
Definition at line 115 of file DataflowEnvironment.cpp.
joinExprMaps()
template<typename MapT > MapT clang::dataflow::joinExprMaps (const MapT & Map1, const MapT & Map2)
Definition at line 61 of file DataflowEnvironment.cpp.
joinLocToVal()
static llvm::MapVector<const StorageLocation *, Value *> clang::dataflow::joinLocToVal (const llvm::MapVector< const StorageLocation *, Value * > & LocToVal, const llvm::MapVector< const StorageLocation *, Value * > & LocToVal2, const Environment & Env1, const Environment & Env2, Environment & JoinedEnv, Environment::ValueModel & Model) static
Definition at line 223 of file DataflowEnvironment.cpp.
makeLoggerFromCommandLine()
static std::unique_ptr<Logger> clang::dataflow::makeLoggerFromCommandLine () static
Definition at line 313 of file DataflowAnalysisContext.cpp.
References DataflowLog(), and clang::File.
maybeUnpackLValueExpr()
static Value* clang::dataflow::maybeUnpackLValueExpr (const Expr & E, Environment & Env) static
Definition at line 81 of file Transfer.cpp.
References Env, clang::dataflow::Environment::getStorageLocation(), clang::dataflow::Environment::getValue(), clang::dataflow::Environment::setValue(), and unpackValue().
negLit()
static constexpr Literal clang::dataflow::negLit (Variable V) static constexpr
Returns the negative literal !V.
Definition at line 72 of file WatchedLiteralsSolver.cpp.
References V.
Referenced by buildCNF(), clang::dataflow::WatchedLiteralsSolverImpl::solve(), and clang::dataflow::WatchedLiteralsSolverImpl::WatchedLiteralsSolverImpl().
notLit()
static constexpr Literal clang::dataflow::notLit (Literal L) static constexpr
Returns the negated literal !L.
Definition at line 75 of file WatchedLiteralsSolver.cpp.
operator<<() [1/8]
llvm::raw_ostream & clang::dataflow::operator<< (llvm::raw_ostream & OS, const Solver::Result & R)
Definition at line 64 of file DebugSupport.cpp.
References debugString(), clang::dataflow::Solver::Result::getSolution(), and clang::dataflow::Solver::Result::getStatus().
operator<<() [2/8]
llvm::raw_ostream & clang::dataflow::operator<< (llvm::raw_ostream & OS, Solver::Result::Assignment Assignment)
Definition at line 41 of file DebugSupport.cpp.
References clang::dataflow::Solver::Result::AssignedFalse, clang::dataflow::Solver::Result::AssignedTrue, and clang::prec::Assignment.
operator<<() [3/8]
llvm::raw_ostream& clang::dataflow::operator<< (llvm::raw_ostream & OS, Atom A) inline
Definition at line 125 of file Formula.h.
operator<<() [4/8]
llvm::raw_ostream& clang::dataflow::operator<< (llvm::raw_ostream & OS, const Formula & F) inline
Definition at line 128 of file Formula.h.
References clang::dataflow::Formula::print().
operator<<() [5/8]
raw_ostream & clang::dataflow::operator<< (raw_ostream & OS, const Value & Val)
Definition at line 43 of file Value.cpp.
References clang::dataflow::Value::AtomicBool, clang::dataflow::Value::FormulaBool, clang::dataflow::Value::getKind(), clang::dataflow::Value::Integer, clang::dataflow::Value::Pointer, and clang::dataflow::Value::TopBool.
operator<<() [6/8]
template<typename Key , typename ElementLattice > std::ostream& clang::dataflow::operator<< (std::ostream & Os, const clang::dataflow::MapLattice< Key, ElementLattice > & M)
Definition at line 115 of file MapLattice.h.
operator<<() [7/8]
template<typename ElementLattice > std::ostream& clang::dataflow::operator<< (std::ostream & Os, const clang::dataflow::VarMapLattice< ElementLattice > & M)
Definition at line 128 of file MapLattice.h.
operator<<() [8/8]
std::ostream& clang::dataflow::operator<< (std::ostream & OS, const NoopLattice &) inline
Definition at line 34 of file NoopLattice.h.
posLit()
static constexpr Literal clang::dataflow::posLit (Variable V) static constexpr
Returns the positive literal V.
Definition at line 65 of file WatchedLiteralsSolver.cpp.
References V.
Referenced by buildCNF(), clang::dataflow::WatchedLiteralsSolverImpl::solve(), and clang::dataflow::WatchedLiteralsSolverImpl::WatchedLiteralsSolverImpl().
printAtomList()
static void clang::dataflow::printAtomList (const llvm::SmallVector< Atom > & Atoms, llvm::raw_ostream & OS) static
Definition at line 243 of file DataflowAnalysisContext.cpp.
Referenced by clang::dataflow::DataflowAnalysisContext::dumpFlowCondition().
projectToLeaders()
static llvm::DenseSet<Atom> clang::dataflow::projectToLeaders (const llvm::DenseSet< Atom > & Atoms, llvm::EquivalenceClasses< Atom > & EquivalentAtoms) static
Definition at line 53 of file SimplifyConstraints.cpp.
Referenced by simplifyConstraints().
propagateStorageLocation()
static void clang::dataflow::propagateStorageLocation (const Expr & From, const Expr & To, Environment & Env) static
Definition at line 105 of file Transfer.cpp.
References Env, clang::dataflow::Environment::getStorageLocation(), and clang::dataflow::Environment::setStorageLocation().
Referenced by propagateValueOrStorageLocation().
propagateValue()
static void clang::dataflow::propagateValue (const Expr & From, const Expr & To, Environment & Env) static
Definition at line 98 of file Transfer.cpp.
References Env, clang::Expr::getType(), clang::dataflow::Environment::getValue(), clang::Type::isRecordType(), and clang::dataflow::Environment::setValue().
Referenced by propagateValueOrStorageLocation().
propagateValueOrStorageLocation()
static void clang::dataflow::propagateValueOrStorageLocation (const Expr & From, const Expr & To, Environment & Env) static
Definition at line 114 of file Transfer.cpp.
References Env, clang::Expr::isGLValue(), propagateStorageLocation(), and propagateValue().
recordsEqual() [1/2]
bool clang::dataflow::recordsEqual (const RecordStorageLocation & Loc1, const Environment & Env1, const RecordStorageLocation & Loc2, const Environment & Env2)
Returns whether the records Loc1 and Loc2 are equal.
Values for Loc1 are retrieved from Env1, and values for Loc2 are retrieved from Env2. A convenience overload retrieves values for Loc1 and Loc2 from the same environment.
This performs a deep comparison, i.e. it compares every field (including synthetic fields) and recurses on fields of record type. Fields of reference type compare equal if they refer to the same storage location.
Note on how to interpret the result:
If this returns true, the records are guaranteed to be equal at runtime.
If this returns false, the records may still be equal at runtime; our analysis merely cannot guarantee that they will be equal.
Requirements:
Src and Dst must have the same canonical unqualified type.
Definition at line 88 of file RecordOps.cpp.
References clang::dataflow::RecordStorageLocation::children(), clang::QualType::getCanonicalType(), clang::dataflow::RecordStorageLocation::getChild(), clang::dataflow::StorageLocation::getType(), clang::QualType::getUnqualifiedType(), and clang::dataflow::Environment::getValue().
Referenced by recordsEqual().
recordsEqual() [2/2]
bool clang::dataflow::recordsEqual (const RecordStorageLocation & Loc1, const RecordStorageLocation & Loc2, const Environment & Env) inline
Definition at line 63 of file RecordOps.h.
References Env, and recordsEqual().
runDataflowAnalysis()
template<typename AnalysisT > llvm::Expected<std::vector< std::optional<DataflowAnalysisState<typename AnalysisT::Lattice> > > > clang::dataflow::runDataflowAnalysis (const AdornedCFG & ACFG, AnalysisT & Analysis, const Environment & InitEnv, std::function< void(const CFGElement &, const DataflowAnalysisState< typename AnalysisT::Lattice > &)> PostVisitCFG = nullptr, std::int32_t MaxBlockVisits = 20'000)
Performs dataflow analysis and returns a mapping from basic block IDs to dataflow analysis states that model the respective basic blocks.
The returned vector, if any, will have the same size as the number of CFG blocks, with indices corresponding to basic block IDs. Returns an error if the dataflow analysis cannot be performed successfully. Otherwise, calls PostVisitCFG on each CFG element with the final analysis results at that program point.
MaxBlockVisits caps the number of block visits during analysis. See runTypeErasedDataflowAnalysis for a full description. The default value is essentially arbitrary – large enough to accommodate what seems like any reasonable CFG, but still small enough to limit the cost of hitting the limit.
Definition at line 197 of file DataflowAnalysis.h.
runTypeErasedDataflowAnalysis()
llvm::Expected< std::vector< std::optional< TypeErasedDataflowAnalysisState > > > clang::dataflow::runTypeErasedDataflowAnalysis (const AdornedCFG & ACFG, TypeErasedDataflowAnalysis & Analysis, const Environment & InitEnv, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG, std::int32_t MaxBlockVisits)
Performs dataflow analysis and returns a mapping from basic block IDs to dataflow analysis states that model the respective basic blocks.
Indices of the returned vector correspond to basic block IDs. Returns an error if the dataflow analysis cannot be performed successfully. Otherwise, calls PostVisitCFG on each CFG element with the final analysis results at that program point.
MaxBlockVisits caps the number of block visits during analysis. It doesn't distinguish between repeat visits to the same block and visits to distinct blocks. This parameter is a backstop to prevent infinite loops, in the case of bugs in the lattice and/or transfer functions that prevent the analysis from converging.
Definition at line 469 of file TypeErasedDataflowAnalysis.cpp.
References ACFG, Analysis, BlockStates, clang::dataflow::Environment::callStackSize(), clang::ForwardDataflowWorklist::enqueueSuccessors(), clang::dataflow::Environment::fork(), clang::CFGBlock::getBlockID(), clang::dataflow::AdornedCFG::getCFG(), clang::CFG::getEntry(), InitEnv, clang::dataflow::Environment::initialize(), clang::CFG::size(), and clang::dataflow::TypeErasedDataflowAnalysis::typeErasedInitialElement().
sigil()
static llvm::StringLiteral clang::dataflow::sigil (Formula::Kind K) static
Definition at line 39 of file Formula.cpp.
References clang::dataflow::Formula::And, clang::dataflow::Formula::AtomRef, clang::dataflow::Formula::Equal, clang::dataflow::Formula::Implies, clang::dataflow::Formula::Literal, clang::dataflow::Formula::Not, and clang::dataflow::Formula::Or.
Referenced by clang::dataflow::Formula::print().
simplifyConstraints()
void clang::dataflow::simplifyConstraints (llvm::SetVector< const Formula * > & Constraints, Arena & arena, SimplifyConstraintsInfo * Info = nullptr)
Simplifies a set of constraints (implicitly connected by "and") in a way that does not change satisfiability of the constraints.
This does not mean that the set of solutions is the same before and after simplification. Info, if non-null, will be populated with information about the simplifications that were made to the formula (e.g. to display to the user).
Definition at line 75 of file SimplifyConstraints.cpp.
References clang::dataflow::Formula::And, clang::dataflow::Formula::AtomRef, atomsInEquivalenceClass(), End, clang::dataflow::Formula::Equal, clang::dataflow::SimplifyConstraintsInfo::EquivalentAtoms, clang::dataflow::SimplifyConstraintsInfo::FalseAtoms, clang::dataflow::Formula::isLiteral(), clang::dataflow::Formula::kind(), clang::dataflow::Arena::makeAtomRef(), clang::dataflow::Arena::makeLiteral(), clang::dataflow::Formula::Not, clang::dataflow::Formula::operands(), projectToLeaders(), substitute(), and clang::dataflow::SimplifyConstraintsInfo::TrueAtoms.
Referenced by clang::dataflow::DataflowAnalysisContext::dumpFlowCondition().
substitute()
static const Formula& clang::dataflow::substitute (const Formula & F, const llvm::DenseMap< Atom, const Formula * > & Substitutions, Arena & arena) static
Definition at line 18 of file SimplifyConstraints.cpp.
References clang::dataflow::Formula::And, clang::dataflow::Formula::AtomRef, clang::dataflow::Formula::Equal, clang::dataflow::Formula::getAtom(), clang::dataflow::Formula::Implies, clang::dataflow::Formula::kind(), clang::dataflow::Formula::Literal, clang::dataflow::Arena::makeAnd(), clang::dataflow::Arena::makeEquals(), clang::dataflow::Arena::makeImplies(), clang::dataflow::Arena::makeNot(), clang::dataflow::Arena::makeOr(), clang::dataflow::Formula::Not, clang::dataflow::Formula::operands(), and clang::dataflow::Formula::Or.
Referenced by simplifyConstraints().
transfer()
void clang::dataflow::transfer (const StmtToEnvMap & StmtToEnv, const Stmt & S, Environment & Env, Environment::ValueModel & Model)
Evaluates S and updates Env accordingly.
Requirements:
S must not be ParenExpr or ExprWithCleanups.
Definition at line 844 of file Transfer.cpp.
transferCFGBlock()
static TypeErasedDataflowAnalysisState clang::dataflow::transferCFGBlock (const CFGBlock & Block, AnalysisContext & AC, std::function< void(const CFGElement &, const TypeErasedDataflowAnalysisState &)> PostVisitCFG = nullptr) static
Transfers State by evaluating each element in the Block based on the AC.Analysis specified.
Built-in transfer functions (if the option for ApplyBuiltinTransfer is set by the analysis) will be applied to the element before evaluation by the user-specified analysis. PostVisitCFG (if provided) will be applied to the element after evaluation by the user-specified analysis.
Definition at line 413 of file TypeErasedDataflowAnalysis.cpp.
unpackValue()
static BoolValue& clang::dataflow::unpackValue (BoolValue & V, Environment & Env) static
Definition at line 70 of file Transfer.cpp.
References clang::dataflow::DataflowAnalysisContext::arena(), Env, clang::dataflow::Environment::getDataflowAnalysisContext(), clang::dataflow::Arena::makeBoolValue(), and V.
Referenced by maybeUnpackLValueExpr().
var()
static constexpr Variable clang::dataflow::var (Literal L) static constexpr
Returns the variable of L.
Definition at line 78 of file WatchedLiteralsSolver.cpp.
Referenced by clang::Sema::ActOnBlockStmtExpr(), clang::Sema::ActOnForEachDeclStmt(), clang::Sema::CheckCompleteVariableDeclaration(), considerVariable(), drillIntoBlockVariable(), emitArgumentDemotion(), clang::CodeGen::CodeGenFunction::emitAutoVarTypeCleanup(), EmitAutoVarWithLifetime(), clang::CodeGen::CodeGenFunction::emitBlockByrefAddress(), clang::CodeGen::CodeGenFunction::EmitDeclRefLValue(), clang::CodeGen::CodeGenFunction::EmitStaticVarDecl(), clang::CodeGen::CodeGenFunction::GenerateBlockFunction(), clang::CodeGen::CGBlockInfo::getCapture(), clang::CFGImplicitDtor::getDestructorDecl(), clang::Sema::inferObjCARCLifetime(), isAccessedBy(), isBlockVarRef(), isInvalidICRSource(), clang::CodeGen::ConstantEmitter::setInConstantContext(), SetupCleanupBlockActivation(), shouldExtendReceiverForInnerPointerMessage(), clang::arcmt::trans::BlockObjCVariableTraverser::traverseBody(), tryCaptureAsConstant(), and clang::CodeGen::CodeGenFunction::tryEmitAsConstant().
widenDistinctValues()
static WidenResult clang::dataflow::widenDistinctValues (QualType Type, Value & Prev, const Environment & PrevEnv, Value & Current, Environment & CurrentEnv, Environment::ValueModel & Model) static
Definition at line 155 of file DataflowEnvironment.cpp.
widenKeyToValueMap()
template<typename Key > llvm::MapVector<Key, Value *> clang::dataflow::widenKeyToValueMap (const llvm::MapVector< Key, Value * > & CurMap, const llvm::MapVector< Key, Value * > & PrevMap, Environment & CurEnv, const Environment & PrevEnv, Environment::ValueModel & Model, LatticeEffect & Effect)
Definition at line 253 of file DataflowEnvironment.cpp.
Variable Documentation
MaxCompositeValueDepth
constexpr int clang::dataflow::MaxCompositeValueDepth = 3 static constexpr
Definition at line 40 of file DataflowEnvironment.cpp.
MaxCompositeValueSize
constexpr int clang::dataflow::MaxCompositeValueSize = 1000 static constexpr
Definition at line 41 of file DataflowEnvironment.cpp.
Referenced by clang::dataflow::Environment::createValue(), and clang::dataflow::Environment::initializeFieldsWithValues().
NullClause
constexpr ClauseID clang::dataflow::NullClause = 0 static constexpr
A null clause identifier is used as a placeholder in various data structures and algorithms.
Definition at line 85 of file WatchedLiteralsSolver.cpp.
NullLit
constexpr Literal clang::dataflow::NullLit = 0 static constexpr
A null literal is used as a placeholder in various data structures and algorithms.
Definition at line 62 of file WatchedLiteralsSolver.cpp.
Referenced by clang::dataflow::CNFFormulaBuilder::addClause(), and clang::dataflow::CNFFormula::addClause().
NullVar
constexpr Variable clang::dataflow::NullVar = 0 static constexpr
A null boolean variable is used as a placeholder in various data structures and algorithms.
Definition at line 52 of file WatchedLiteralsSolver.cpp.
Referenced by clang::dataflow::WatchedLiteralsSolverImpl::WatchedLiteralsSolverImpl().