clang: clang::tooling::stdlib Namespace Reference
clang::tooling::stdlib Namespace Reference
Classes
class Header
class Recognizer
class Symbol
Typedefs
using NSSymbolMap = llvm::DenseMap< llvm::StringRef, unsigned >
Functions
static int initialize ()
static void ensureInitialized ()
Variables
static llvm::StringRef * HeaderNames
static std::pair< llvm::StringRef, llvm::StringRef > * SymbolNames
static unsigned * SymbolHeaderIDs
static llvm::DenseMap< llvm::StringRef, unsigned > * HeaderIDs
static llvm::DenseMap< llvm::StringRef, NSSymbolMap * > * NamespaceSymbols
Typedef Documentation
NSSymbolMap
using clang::tooling::stdlib::NSSymbolMap = typedef llvm::DenseMap<llvm::StringRef, unsigned>
Definition at line 23 of file StandardLibrary.cpp.
Function Documentation
ensureInitialized()
static void clang::tooling::stdlib::ensureInitialized () static
Definition at line 74 of file StandardLibrary.cpp.
References initialize().
Referenced by clang::tooling::stdlib::Recognizer::Recognizer().
initialize()
static int clang::tooling::stdlib::initialize () static
Definition at line 26 of file StandardLibrary.cpp.
References clang::interp::Add(), HeaderIDs, NamespaceSymbols, SymbolHeaderIDs, and SymbolNames.
Referenced by ensureInitialized().
Variable Documentation
HeaderIDs
llvm::DenseMap<llvm::StringRef, unsigned>* clang::tooling::stdlib::HeaderIDs static
Definition at line 21 of file StandardLibrary.cpp.
Referenced by initialize().
HeaderNames
llvm::StringRef* clang::tooling::stdlib::HeaderNames static
Definition at line 18 of file StandardLibrary.cpp.
Referenced by clang::tooling::stdlib::Header::name().
NamespaceSymbols
llvm::DenseMap<llvm::StringRef, NSSymbolMap *>* clang::tooling::stdlib::NamespaceSymbols static
Definition at line 24 of file StandardLibrary.cpp.
Referenced by initialize().
SymbolHeaderIDs
unsigned* clang::tooling::stdlib::SymbolHeaderIDs static
Definition at line 20 of file StandardLibrary.cpp.
Referenced by clang::tooling::stdlib::Symbol::header(), and initialize().
SymbolNames
std::pair<llvm::StringRef, llvm::StringRef>* clang::tooling::stdlib::SymbolNames static
Definition at line 19 of file StandardLibrary.cpp.
Referenced by initialize(), clang::tooling::stdlib::Symbol::name(), and clang::tooling::stdlib::Symbol::scope().