clang: clang::sema Namespace Reference
clang::sema Namespace Reference
Classes
class AnalysisBasedWarnings
class AccessedEntity
A declaration being accessed, together with information about how it was accessed.
class DelayedDiagnostic
A diagnostic message which has been conditionally emitted pending the complete parsing of the current declaration.
class DelayedDiagnosticPool
A collection of diagnostics which were delayed.
class RISCVIntrinsicManager
class CompoundScopeInfo
Contains information about the compound statement currently being parsed.
class PossiblyUnreachableDiag
class FunctionScopeInfo
Retains information about a function, method, or block that is currently being parsed.
class Capture
class CapturingScopeInfo
class BlockScopeInfo
Retains information about a block that is currently being parsed.
class CapturedRegionScopeInfo
Retains information about a captured region.
class LambdaScopeInfo
class TemplateDeductionInfo
Provides information about an attempted template argument deduction, whose success or failure was described by a TemplateDeductionResult value.
struct AssignedEntity
Describes an entity that is being assigned.
class SemaPPCallbacks
Enumerations
enum class FirstCoroutineStmtKind { CoReturn , CoAwait , CoYield }
enum PathLifetimeKind { Extend , ShouldExtend , NoExtend }
Whether a path to an object supports lifetime extension.
Functions
static LifetimeResult getEntityLifetime (const InitializedEntity *Entity, const InitializedEntity *InitField=nullptr)
Determine the declaration which an initialized entity ultimately refers to, for the purpose of lifetime-extending a temporary bound to a reference in the initialization of Entity.
static bool isVarOnPath (IndirectLocalPath &Path, VarDecl *VD)
static bool pathContainsInit (IndirectLocalPath &Path)
static void visitLocalsRetainedByInitializer (IndirectLocalPath &Path, Expr *Init, LocalVisitor Visit, bool RevisitSubinits, bool EnableLifetimeWarnings)
Visit the locals that would be reachable through an object initialized by the prvalue expression Init.
static void visitLocalsRetainedByReferenceBinding (IndirectLocalPath &Path, Expr *Init, ReferenceKind RK, LocalVisitor Visit, bool EnableLifetimeWarnings)
Visit the locals that would be reachable through a reference bound to the glvalue expression Init.
template<typename T >
static bool isRecordWithAttr (QualType Type)
static bool isInStlNamespace (const Decl *D)
static bool shouldTrackImplicitObjectArg (const CXXMethodDecl *Callee)
static bool shouldTrackFirstArgument (const FunctionDecl *FD)
static void handleGslAnnotatedTypes (IndirectLocalPath &Path, Expr *Call, LocalVisitor Visit)
static bool implicitObjectParamIsLifetimeBound (const FunctionDecl *FD)
static void visitLifetimeBoundArguments (IndirectLocalPath &Path, Expr *Call, LocalVisitor Visit)
static PathLifetimeKind shouldLifetimeExtendThroughPath (const IndirectLocalPath &Path)
Determine whether this is an indirect path to a temporary that we are supposed to lifetime-extend along.
static SourceRange nextPathEntryRange (const IndirectLocalPath &Path, unsigned I, Expr *E)
Find the range for the first interesting entry in the path at or after I.
static bool pathOnlyInitializesGslPointer (IndirectLocalPath &Path)
static void checkExprLifetimeImpl (Sema &SemaRef, const InitializedEntity *InitEntity, const InitializedEntity *ExtendingEntity, LifetimeKind LK, const AssignedEntity *AEntity, Expr *Init)
void checkExprLifetime (Sema &SemaRef, const InitializedEntity &Entity, Expr *Init)
Check that the lifetime of the given expr (and its subobjects) is sufficient for initializing the entity, and perform lifetime extension (when permitted) if not.
void checkExprLifetime (Sema &SemaRef, const AssignedEntity &Entity, Expr *Init)
Check that the lifetime of the given expr (and its subobjects) is sufficient for assigning to the entity.
Attr * instantiateTemplateAttribute (const Attr *At, ASTContext &C, Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs)
Attr * instantiateTemplateAttributeForDecl (const Attr *At, ASTContext &C, Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs)
Enumeration Type Documentation
FirstCoroutineStmtKind
enum clang::sema::FirstCoroutineStmtKind strong
Enumerator
CoReturn
CoAwait
CoYield
Definition at line 100 of file ScopeInfo.h.
PathLifetimeKind
enum clang::sema::PathLifetimeKind
Whether a path to an object supports lifetime extension.
Enumerator
Extend
Lifetime-extend along this path.
ShouldExtend
We should lifetime-extend, but we don't because (due to technical limitations) we can't.
This happens for default member initializers, which we don't clone for every use, so we don't have a unique MaterializeTemporaryExpr to update.
NoExtend
Do not lifetime extend along this path.
Definition at line 903 of file CheckExprLifetime.cpp.
Function Documentation
checkExprLifetime() [1/2]
void clang::sema::checkExprLifetime (Sema & SemaRef, const AssignedEntity & Entity, Expr * Init)
Check that the lifetime of the given expr (and its subobjects) is sufficient for assigning to the entity.
Definition at line 1290 of file CheckExprLifetime.cpp.
References checkExprLifetimeImpl(), clang::Expr::getType(), clang::Type::isPointerType(), and clang::sema::AssignedEntity::LHS.
checkExprLifetime() [2/2]
void clang::sema::checkExprLifetime (Sema & SemaRef, const InitializedEntity & Entity, Expr * Init)
Check that the lifetime of the given expr (and its subobjects) is sufficient for initializing the entity, and perform lifetime extension (when permitted) if not.
Definition at line 1282 of file CheckExprLifetime.cpp.
References checkExprLifetimeImpl(), and getEntityLifetime().
Referenced by clang::Sema::checkInitializerLifetime().
checkExprLifetimeImpl()
static void clang::sema::checkExprLifetimeImpl (Sema & SemaRef, const InitializedEntity * InitEntity, const InitializedEntity * ExtendingEntity, LifetimeKind LK, const AssignedEntity * AEntity, Expr * Init) static
Definition at line 974 of file CheckExprLifetime.cpp.
References clang::InitializedEntity::allocateManglingNumber(), clang::SemaBase::Diag(), Extend, clang::SourceRange::getBegin(), clang::InitializedEntity::getDecl(), clang::NamedDecl::getDeclName(), clang::Sema::getDiagnostics(), clang::Sema::getLangOpts(), clang::Decl::getLocation(), clang::InitializedEntity::getParent(), clang::ValueDecl::getType(), clang::InitializedEntity::getType(), clang::DiagnosticsEngine::isIgnored(), clang::Decl::isImplicit(), clang::ValueDecl::isInitCapture(), clang::Type::isReferenceType(), clang::SourceLocation::isValid(), clang::LCK_ByRef, clang::sema::AssignedEntity::LHS, clang::Member, nextPathEntryRange(), NoExtend, Path, pathContainsInit(), pathOnlyInitializesGslPointer(), ShouldExtend, shouldLifetimeExtendThroughPath(), visitLocalsRetainedByInitializer(), and visitLocalsRetainedByReferenceBinding().
Referenced by checkExprLifetime().
getEntityLifetime()
static LifetimeResult clang::sema::getEntityLifetime (const InitializedEntity * Entity, const InitializedEntity * InitField = nullptr) static
Determine the declaration which an initialized entity ultimately refers to, for the purpose of lifetime-extending a temporary bound to a reference in the initialization of Entity.
Definition at line 56 of file CheckExprLifetime.cpp.
References clang::InitializedEntity::EK_ArrayElement, clang::InitializedEntity::EK_Base, clang::InitializedEntity::EK_Binding, clang::InitializedEntity::EK_BlockElement, clang::InitializedEntity::EK_ComplexElement, clang::InitializedEntity::EK_CompoundLiteralInit, clang::InitializedEntity::EK_Delegating, clang::InitializedEntity::EK_Exception, clang::InitializedEntity::EK_LambdaCapture, clang::InitializedEntity::EK_LambdaToBlockConversionBlockElement, clang::InitializedEntity::EK_Member, clang::InitializedEntity::EK_New, clang::InitializedEntity::EK_Parameter, clang::InitializedEntity::EK_Parameter_CF_Audited, clang::InitializedEntity::EK_ParenAggInitMember, clang::InitializedEntity::EK_RelatedResult, clang::InitializedEntity::EK_Result, clang::InitializedEntity::EK_StmtExprResult, clang::InitializedEntity::EK_TemplateParameter, clang::InitializedEntity::EK_Temporary, clang::InitializedEntity::EK_Variable, clang::InitializedEntity::EK_VectorElement, clang::InitializedEntity::getKind(), clang::InitializedEntity::getParent(), clang::interp::InitField(), and clang::InitializedEntity::isDefaultMemberInitializer().
Referenced by checkExprLifetime().
handleGslAnnotatedTypes()
static void clang::sema::handleGslAnnotatedTypes (IndirectLocalPath & Path, Expr * Call, LocalVisitor Visit) static
Definition at line 328 of file CheckExprLifetime.cpp.
References D, clang::DeclContext::getParent(), clang::Decl::hasAttr(), Path, shouldTrackFirstArgument(), shouldTrackImplicitObjectArg(), visitLocalsRetainedByInitializer(), and visitLocalsRetainedByReferenceBinding().
Referenced by visitLocalsRetainedByReferenceBinding().
implicitObjectParamIsLifetimeBound()
static bool clang::sema::implicitObjectParamIsLifetimeBound (const FunctionDecl * FD) static
Definition at line 387 of file CheckExprLifetime.cpp.
References clang::TypeLoc::getAsAdjusted(), clang::Decl::getASTContext(), clang::AttributedTypeLoc::getAttrAs(), clang::DeclarationName::getCXXOverloadedOperator(), clang::NamedDecl::getDeclName(), clang::ASTContext::getLValueReferenceType(), clang::AttributedTypeLoc::getModifiedLoc(), clang::FunctionDecl::getReturnType(), clang::TypeSourceInfo::getTypeLoc(), clang::DeclaratorDecl::getTypeSourceInfo(), clang::ASTContext::hasSameType(), clang::isCompoundAssignmentOperator(), and clang::Type::isLValueReferenceType().
Referenced by visitLifetimeBoundArguments().
instantiateTemplateAttribute()
Attr* clang::sema::instantiateTemplateAttribute (const Attr * At, ASTContext & C, Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs)
Referenced by clang::Sema::InstantiateAttrs().
instantiateTemplateAttributeForDecl()
Attr* clang::sema::instantiateTemplateAttributeForDecl (const Attr * At, ASTContext & C, Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs)
Referenced by clang::Sema::InstantiateAttrsForDecl().
isInStlNamespace()
static bool clang::sema::isInStlNamespace (const Decl * D) static
Definition at line 255 of file CheckExprLifetime.cpp.
References D.
Referenced by shouldTrackImplicitObjectArg().
isRecordWithAttr()
template<typename T > static bool clang::sema::isRecordWithAttr (QualType Type) static
Definition at line 246 of file CheckExprLifetime.cpp.
References clang::Type::getAsCXXRecordDecl(), and clang::T.
isVarOnPath()
static bool clang::sema::isVarOnPath (IndirectLocalPath & Path, VarDecl * VD) static
Definition at line 222 of file CheckExprLifetime.cpp.
References E, and Path.
Referenced by visitLocalsRetainedByInitializer(), and visitLocalsRetainedByReferenceBinding().
nextPathEntryRange()
static SourceRange clang::sema::nextPathEntryRange (const IndirectLocalPath & Path, unsigned I, Expr * E) static
Find the range for the first interesting entry in the path at or after I.
Definition at line 930 of file CheckExprLifetime.cpp.
References D, E, Kind, and Path.
Referenced by checkExprLifetimeImpl().
pathContainsInit()
static bool clang::sema::pathContainsInit (IndirectLocalPath & Path) static
Definition at line 229 of file CheckExprLifetime.cpp.
References E, and Path.
Referenced by checkExprLifetimeImpl().
pathOnlyInitializesGslPointer()
static bool clang::sema::pathOnlyInitializesGslPointer (IndirectLocalPath & Path) static
Definition at line 960 of file CheckExprLifetime.cpp.
References Path.
Referenced by checkExprLifetimeImpl().
shouldLifetimeExtendThroughPath()
static PathLifetimeKind clang::sema::shouldLifetimeExtendThroughPath (const IndirectLocalPath & Path) static
Determine whether this is an indirect path to a temporary that we are supposed to lifetime-extend along.
Definition at line 918 of file CheckExprLifetime.cpp.
References Extend, Kind, NoExtend, Path, and ShouldExtend.
Referenced by checkExprLifetimeImpl().
shouldTrackFirstArgument()
static bool clang::sema::shouldTrackFirstArgument (const FunctionDecl * FD) static
Definition at line 304 of file CheckExprLifetime.cpp.
References clang::NamedDecl::getIdentifier(), clang::NamedDecl::getName(), clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::Type::getPointeeCXXRecordDecl(), clang::FunctionDecl::getReturnType(), clang::ValueDecl::getType(), clang::Decl::isInStdNamespace(), clang::Type::isPointerType(), and clang::Type::isReferenceType().
Referenced by handleGslAnnotatedTypes().
shouldTrackImplicitObjectArg()
static bool clang::sema::shouldTrackImplicitObjectArg (const CXXMethodDecl * Callee) static
Definition at line 270 of file CheckExprLifetime.cpp.
References isInStlNamespace().
Referenced by handleGslAnnotatedTypes().
visitLifetimeBoundArguments()
static void clang::sema::visitLifetimeBoundArguments (IndirectLocalPath & Path, Expr * Call, LocalVisitor Visit) static
Definition at line 424 of file CheckExprLifetime.cpp.
References clang::Sema::CanBeGetReturnObject(), D, clang::Expr::IgnoreImplicit(), implicitObjectParamIsLifetimeBound(), clang::interp::LE(), Path, visitLocalsRetainedByInitializer(), and visitLocalsRetainedByReferenceBinding().
Referenced by visitLocalsRetainedByReferenceBinding().
visitLocalsRetainedByInitializer()
static void clang::sema::visitLocalsRetainedByInitializer (IndirectLocalPath & Path, Expr * Init, LocalVisitor Visit, bool RevisitSubinits, bool EnableLifetimeWarnings) static
Visit the locals that would be reachable through an object initialized by the prvalue expression Init.
Definition at line 627 of file CheckExprLifetime.cpp.
References isVarOnPath(), Path, and visitLocalsRetainedByReferenceBinding().
Referenced by checkExprLifetimeImpl(), handleGslAnnotatedTypes(), visitLifetimeBoundArguments(), and visitLocalsRetainedByReferenceBinding().
visitLocalsRetainedByReferenceBinding()
static void clang::sema::visitLocalsRetainedByReferenceBinding (IndirectLocalPath & Path, Expr * Init, ReferenceKind RK, LocalVisitor Visit, bool EnableLifetimeWarnings) static
Visit the locals that would be reachable through a reference bound to the glvalue expression Init.
Definition at line 491 of file CheckExprLifetime.cpp.
References clang::format::getBase(), handleGslAnnotatedTypes(), isVarOnPath(), Path, visitLifetimeBoundArguments(), and visitLocalsRetainedByInitializer().
Referenced by checkExprLifetimeImpl(), handleGslAnnotatedTypes(), visitLifetimeBoundArguments(), and visitLocalsRetainedByInitializer().