clang: clang::ento::retaincountchecker Namespace Reference
clang::ento::retaincountchecker Namespace Reference
Classes
class RefVal
Metadata on reference.
class RetainCountChecker
class RefCountReportVisitor
class RefLeakReportVisitor
class RefCountBug
class RefCountReport
class RefLeakReport
Functions
const RefVal * getRefBinding (ProgramStateRef State, SymbolRef Sym)
bool isSynthesizedAccessor (const StackFrameContext *SFC)
Returns true if this stack frame is for an Objective-C method that is a property getter or setter whose body has been synthesized by the analyzer.
Function Documentation
getRefBinding()
const RefVal * clang::ento::retaincountchecker::getRefBinding (ProgramStateRef State, SymbolRef Sym)
Definition at line 29 of file RetainCountChecker.cpp.
References State.
Referenced by annotateConsumedSummaryMismatch(), annotateStartParameter(), clang::ento::retaincountchecker::RetainCountChecker::checkDeadSymbols(), clang::ento::retaincountchecker::RetainCountChecker::checkPostCall(), clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt(), clang::ento::retaincountchecker::RetainCountChecker::checkSummary(), GetAllocationSite(), clang::ento::retaincountchecker::RefLeakReportVisitor::getEndPath(), clang::ento::retaincountchecker::RetainCountChecker::processNonLeakError(), clang::ento::retaincountchecker::RetainCountChecker::processObjCLiterals(), clang::ento::retaincountchecker::RetainCountChecker::processSummaryOfInlined(), and clang::ento::retaincountchecker::RefCountReportVisitor::VisitNode().
isSynthesizedAccessor()
bool clang::ento::retaincountchecker::isSynthesizedAccessor (const StackFrameContext * SFC) inline
Returns true if this stack frame is for an Objective-C method that is a property getter or setter whose body has been synthesized by the analyzer.
Definition at line 383 of file RetainCountChecker.h.
References clang::LocationContext::getAnalysisDeclContext(), clang::LocationContext::getDecl(), and clang::AnalysisDeclContext::isBodyAutosynthesized().
Referenced by clang::ento::retaincountchecker::RetainCountChecker::checkPostStmt().