clang: clang::driver::tools::SYCL Namespace Reference
clang::driver::tools::SYCL Namespace Reference
Namespaces
fpga
Directly call FPGA Compiler and Linker.
gen
x86_64
Classes
class Linker
Functions
void constructLLVMForeachCommand (Compilation &C, const JobAction &JA, std::unique_ptr< Command > InputCommand, const InputInfoList &InputFiles, const InputInfo &Output, const Tool *T, StringRef Increment, StringRef Ext="out", StringRef ParallelJobs="")
SmallVector< std::string, 8 > getDeviceLibraries (const Compilation &C, const llvm::Triple &TargetTriple, bool IsSpirvAOT)
bool shouldDoPerObjectFileLinking (const Compilation &C)
Function Documentation
constructLLVMForeachCommand()
void clang::driver::tools::SYCL::constructLLVMForeachCommand (Compilation & C, const JobAction & JA, std::unique_ptr< Command > InputCommand, const InputInfoList & InputFiles, const InputInfo & Output, const Tool * T, StringRef Increment, StringRef Ext = "out", StringRef ParallelJobs = "")
Definition at line 65 of file SYCL.cpp.
References addFPGATimingDiagnostic(), Cmd, Filename, clang::driver::ResponseFileSupport::None(), and clang::T.
Referenced by clang::driver::tools::SpirvToIrWrapper::ConstructJob(), clang::driver::tools::SYCL::fpga::BackendCompiler::ConstructJob(), clang::driver::tools::SYCL::gen::BackendCompiler::ConstructJob(), clang::driver::tools::SYCL::x86_64::BackendCompiler::ConstructJob(), and clang::driver::tools::OffloadBundler::ConstructJobMultipleOutputs().
getDeviceLibraries()
SmallVector< std::string, 8 > clang::driver::tools::SYCL::getDeviceLibraries (const Compilation & C, const llvm::Triple & TargetTriple, bool IsSpirvAOT)
Definition at line 209 of file SYCL.cpp.
References selectBfloatLibs().
Referenced by clang::driver::tools::LinkerWrapper::ConstructJob().
shouldDoPerObjectFileLinking()
bool clang::driver::tools::SYCL::shouldDoPerObjectFileLinking (const Compilation & C)
Definition at line 154 of file SYCL.cpp.
Referenced by clang::driver::tools::OffloadBundler::ConstructJob().