clang: clang::ento::smartptr Namespace Reference
clang::ento::smartptr Namespace Reference
Functions
bool isStdSmartPtrCall (const CallEvent &Call)
Returns true if the event call is on smart pointer.
bool isStdSmartPtr (const CXXRecordDecl *RD)
bool isStdSmartPtr (const Expr *E)
bool isNullSmartPtr (const ProgramStateRef State, const MemRegion *ThisRegion)
Returns whether the smart pointer is null or not.
const BugType * getNullDereferenceBugType ()
Function Documentation
getNullDereferenceBugType()
const BugType * clang::ento::smartptr::getNullDereferenceBugType ()
Definition at line 54 of file SmartPtrChecker.cpp.
isNullSmartPtr()
bool clang::ento::smartptr::isNullSmartPtr (const ProgramStateRef State, const MemRegion * ThisRegion)
Returns whether the smart pointer is null or not.
Definition at line 149 of file SmartPtrModeling.cpp.
References State.
isStdSmartPtr() [1/2]
bool clang::ento::smartptr::isStdSmartPtr (const CXXRecordDecl * RD)
Definition at line 134 of file SmartPtrModeling.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::DeclarationName::isIdentifier(), and clang::DeclContext::isStdNamespace().
Referenced by isPotentiallyComparisionOpCall().
isStdSmartPtr() [2/2]
bool clang::ento::smartptr::isStdSmartPtr (const Expr * E)
Definition at line 145 of file SmartPtrModeling.cpp.
References clang::Type::getAsCXXRecordDecl(), clang::Expr::getType(), and isStdSmartPtr().
isStdSmartPtrCall()
bool clang::ento::smartptr::isStdSmartPtrCall (const CallEvent & Call)
Returns true if the event call is on smart pointer.
Definition at line 127 of file SmartPtrModeling.cpp.
References isStdSmartPtr().