clang: clang::threadSafety::sx Namespace Reference
clang::threadSafety::sx Namespace Reference
Functions
bool equals (const til::SExpr *E1, const til::SExpr *E2)
bool matches (const til::SExpr *E1, const til::SExpr *E2)
bool partiallyMatches (const til::SExpr *E1, const til::SExpr *E2)
std::string toString (const til::SExpr *E)
Function Documentation
equals()
bool clang::threadSafety::sx::equals (const til::SExpr * E1, const til::SExpr * E2) inline
Definition at line 65 of file ThreadSafetyCommon.h.
References clang::threadSafety::til::EqualsComparator::compareExprs().
Referenced by clang::driver::Compilation::CleanupFile(), clang::threadSafety::CapabilityExpr::equals(), and clang::Diagnostic::FormatDiagnostic().
matches()
bool clang::threadSafety::sx::matches (const til::SExpr * E1, const til::SExpr * E2) inline
Definition at line 69 of file ThreadSafetyCommon.h.
References clang::threadSafety::til::MatchComparator::compareExprs().
Referenced by clang::ast_matchers::AST_POLYMORPHIC_MATCHER_P2(), and clang::threadSafety::CapabilityExpr::matches().
partiallyMatches()
bool clang::threadSafety::sx::partiallyMatches (const til::SExpr * E1, const til::SExpr * E2) inline
Definition at line 81 of file ThreadSafetyCommon.h.
Referenced by clang::threadSafety::CapabilityExpr::partiallyMatches().
toString()
std::string clang::threadSafety::sx::toString (const til::SExpr * E) inline
Definition at line 91 of file ThreadSafetyCommon.h.
References clang::threadSafety::til::PrettyPrinter< StdPrinter, std::ostream >::print().
Referenced by clang::SemaOpenMP::ActOnOpenMPCriticalDirective(), clang::Sema::ActOnPragmaClangSection(), clang::tooling::applyAtomicChanges(), clang::ast_matchers::AST_MATCHER_P(), clang::Sema::BuildArrayType(), CheckedIntArithmetic(), clang::Sema::CheckLoopHintExpr(), CreateEmptyFile(), clang::tooling::internal::createExecutorFromCommandLineArgsImpl(), DiagTemplateArg(), clang::CodeGen::CodeGenFunction::EmitIntelFPGAMemBuiltin(), clang::CodeGen::CodeGenFunction::EmitIntelSYCLPtrAnnotationBuiltin(), EvaluateDirectiveSubExpr(), getModuleContextHash(), clang::CompilerInvocation::getModuleHash(), clang::threadSafety::getSourceLiteralString(), clang::tooling::RenamingASTConsumer::HandleTranslationUnit(), clang::OffloadBundler::ListBundleIDsInFile(), llvm::yaml::MappingTraits< clang::tooling::DiagnosticMessage >::mapping(), clang::operator<<(), clang::Rewriter::overwriteChangedFiles(), PrettyPrintInRange(), clang::tooling::HeaderIncludes::remove(), clang::format::replaceToken(), clang::tooling::ReplaceStmtWithText::run(), clang::tooling::ReplaceStmtWithStmt::run(), clang::tooling::ReplaceIfStmtWithItsBody::run(), clang::tooling::ClangTool::run(), clang::ento::CheckerManager::runCheckersForEvalCall(), clang::threadSafety::CapabilityExpr::toString(), clang::driver::toolchains::AMDGPUToolChain::TranslateArgs(), clang::driver::toolchains::NVPTXToolChain::TranslateArgs(), clang::OffloadBundler::UnbundleArchive(), clang::OffloadBundler::UnbundleFiles(), clang::Sema::VerifyBitField(), clang::TextNodeDumper::VisitIntegerLiteral(), clang::Interpreter::~Interpreter(), and clang::SavedStreamPosition::~SavedStreamPosition().