clang: clang::driver::tools::SPIRV Namespace Reference
clang::driver::tools::SPIRV Namespace Reference
Classes
class Linker
class Translator
Functions
void addTranslatorArgs (const llvm::opt::ArgList &InArgs, llvm::opt::ArgStringList &OutArgs)
void constructTranslateCommand (Compilation &C, const Tool &T, const JobAction &JA, const InputInfo &Output, const InputInfo &Input, const llvm::opt::ArgStringList &Args)
Function Documentation
addTranslatorArgs()
void clang::driver::tools::SPIRV::addTranslatorArgs (const llvm::opt::ArgList & InArgs, llvm::opt::ArgStringList & OutArgs)
constructTranslateCommand()
void clang::driver::tools::SPIRV::constructTranslateCommand (Compilation & C, const Tool & T, const JobAction & JA, const InputInfo & Output, const InputInfo & Input, const llvm::opt::ArgStringList & Args)
Definition at line 20 of file SPIRV.cpp.
References clang::driver::InputInfo::getFilename(), clang::driver::ToolChain::GetProgramPath(), clang::driver::Tool::getToolChain(), clang::driver::InputInfo::getType(), and clang::driver::ResponseFileSupport::None().
Referenced by clang::driver::tools::SPIRV::Translator::ConstructJob().