clang: clang::ento::bugreporter Namespace Reference
clang::ento::bugreporter Namespace Reference
Enumerations
enum TrackingKind { TrackingKind::Thorough, TrackingKind::Condition }
Specifies the type of tracking for an expression.
Functions
bool trackExpressionValue (const ExplodedNode *N, const Expr *E, PathSensitiveBugReport &R, TrackingKind TKind=TrackingKind::Thorough, bool EnableNullFPSuppression=true)
Attempts to add visitors to track expression value back to its point of origin.
const Expr * getDerefExpr (const Stmt *S)
Enumeration Type Documentation
TrackingKind
enum clang::ento::bugreporter::TrackingKind strong
Specifies the type of tracking for an expression.
Enumerator
Thorough
Default tracking kind – specifies that as much information should be gathered about the tracked expression value as possible.
Condition
Specifies that a more moderate tracking should be used for the expression value.
This will essentially make sure that functions relevant to it aren't pruned, but otherwise relies on the user reading the code or following the arrows.
Definition at line 91 of file BugReporterVisitors.h.
Function Documentation
getDerefExpr()
const Expr* clang::ento::bugreporter::getDerefExpr (const Stmt * S)
Referenced by peelOffOuterExpr().
trackExpressionValue()
bool clang::ento::bugreporter::trackExpressionValue (const ExplodedNode * N, const Expr * E, PathSensitiveBugReport & R, TrackingKind TKind = TrackingKind::Thorough, bool EnableNullFPSuppression = true)
Attempts to add visitors to track expression value back to its point of origin.
Parameters
N A node "downstream" from the evaluation of the statement.
E The expression value which we are tracking
R The bug report to which visitors should be attached.
EnableNullFPSuppression Whether we should employ false positive suppression (inlined defensive checks, returned null).
Returns
Whether or not the function was able to add visitors for this statement. Note that returning true does not actually imply that any visitors were added.
Referenced by emitBug(), trackRValueExpression(), and clang::ento::FindLastStoreBRVisitor::VisitNode().