clang: clang::driver::tools::arm Namespace Reference
clang::driver::tools::arm Namespace Reference
Enumerations
enum ReadTPMode { ReadTPMode::Invalid, ReadTPMode::Soft, ReadTPMode::Cp15 }
enum FloatABI { FloatABI::Invalid, FloatABI::Soft, FloatABI::SoftFP, FloatABI::Hard }
Functions
std::string getARMTargetCPU (StringRef CPU, llvm::StringRef Arch, const llvm::Triple &Triple)
std::string getARMArch (llvm::StringRef Arch, const llvm::Triple &Triple)
StringRef getARMCPUForMArch (llvm::StringRef Arch, const llvm::Triple &Triple)
llvm::ARM::ArchKind getLLVMArchKindForARM (StringRef CPU, StringRef Arch, const llvm::Triple &Triple)
getLLVMArchSuffixForARM - Get the LLVM ArchKind value to use for a particular CPU (or Arch, if CPU is generic).
StringRef getLLVMArchSuffixForARM (llvm::StringRef CPU, llvm::StringRef Arch, const llvm::Triple &Triple)
void appendBE8LinkFlag (const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs, const llvm::Triple &Triple)
FloatABI getDefaultFloatABI (const llvm::Triple &Triple)
FloatABI getARMFloatABI (const ToolChain &TC, const llvm::opt::ArgList &Args)
FloatABI getARMFloatABI (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
void setFloatABIInTriple (const Driver &D, const llvm::opt::ArgList &Args, llvm::Triple &triple)
bool isHardTPSupported (const llvm::Triple &Triple)
ReadTPMode getReadTPMode (const Driver &D, const llvm::opt::ArgList &Args, const llvm::Triple &Triple, bool ForAS)
void setArchNameInTriple (const Driver &D, const llvm::opt::ArgList &Args, types::ID InputType, llvm::Triple &Triple)
bool useAAPCSForMachO (const llvm::Triple &T)
void getARMArchCPUFromArgs (const llvm::opt::ArgList &Args, llvm::StringRef &Arch, llvm::StringRef &CPU, bool FromAs=false)
void getARMTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, std::vector< llvm::StringRef > &Features, bool ForAS)
int getARMSubArchVersionNumber (const llvm::Triple &Triple)
bool isARMMProfile (const llvm::Triple &Triple)
bool isARMAProfile (const llvm::Triple &Triple)
Enumeration Type Documentation
FloatABI
enum clang::driver::tools::arm::FloatABI strong
Enumerator
Invalid
Soft
SoftFP
Hard
Definition at line 44 of file ARM.h.
ReadTPMode
enum clang::driver::tools::arm::ReadTPMode strong
Enumerator
Invalid
Soft
Cp15
Definition at line 38 of file ARM.h.
Function Documentation
appendBE8LinkFlag()
void clang::driver::tools::arm::appendBE8LinkFlag (const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs, const llvm::Triple & Triple)
Referenced by clang::driver::tools::netbsd::Linker::ConstructJob(), and clang::driver::tools::gnutools::Linker::ConstructJob().
getARMArch()
std::string clang::driver::tools::arm::getARMArch (llvm::StringRef Arch, const llvm::Triple & Triple)
Referenced by checkARMArchName(), and getLLVMArchKindForARM().
getARMArchCPUFromArgs()
void clang::driver::tools::arm::getARMArchCPUFromArgs (const llvm::opt::ArgList & Args, llvm::StringRef & Arch, llvm::StringRef & CPU, bool FromAs = false)
Referenced by clang::driver::tools::netbsd::Assembler::ConstructJob(), and clang::driver::tools::openbsd::Assembler::ConstructJob().
getARMCPUForMArch()
StringRef clang::driver::tools::arm::getARMCPUForMArch (llvm::StringRef Arch, const llvm::Triple & Triple)
getARMFloatABI() [1/2]
FloatABI clang::driver::tools::arm::getARMFloatABI (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args)
getARMFloatABI() [2/2]
FloatABI clang::driver::tools::arm::getARMFloatABI (const ToolChain & TC, const llvm::opt::ArgList & Args)
Referenced by clang::driver::toolchains::MachO::AddLinkRuntimeLibArgs(), clang::driver::tools::freebsd::Assembler::ConstructJob(), clang::driver::tools::gnutools::Assembler::ConstructJob(), getArchNameForCompilerRTLib(), and clang::driver::toolchains::Linux::getDynamicLinker().
getARMSubArchVersionNumber()
int clang::driver::tools::arm::getARMSubArchVersionNumber (const llvm::Triple & Triple)
Definition at line 25 of file ARM.cpp.
Referenced by getDefaultFloatABI(), and isHardTPSupported().
getARMTargetCPU()
std::string clang::driver::tools::arm::getARMTargetCPU (StringRef CPU, llvm::StringRef Arch, const llvm::Triple & Triple)
Referenced by checkARMCPUName(), clang::driver::tools::netbsd::Assembler::ConstructJob(), and clang::driver::tools::openbsd::Assembler::ConstructJob().
getARMTargetFeatures()
void clang::driver::tools::arm::getARMTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, std::vector< llvm::StringRef > & Features, bool ForAS)
Referenced by getTargetFeatures().
getDefaultFloatABI()
arm::FloatABI clang::driver::tools::arm::getDefaultFloatABI (const llvm::Triple & Triple)
Definition at line 316 of file ARM.cpp.
References getARMSubArchVersionNumber(), and useAAPCSForMachO().
getLLVMArchKindForARM()
llvm::ARM::ArchKind clang::driver::tools::arm::getLLVMArchKindForARM (StringRef CPU, StringRef Arch, const llvm::Triple & Triple)
getLLVMArchSuffixForARM - Get the LLVM ArchKind value to use for a particular CPU (or Arch, if CPU is generic).
This is needed to pass to functions like llvm::ARM::getDefaultFPU which need an ArchKind as well as a CPU name.
Definition at line 944 of file ARM.cpp.
References getARMArch(), and string().
Referenced by checkARMCPUName().
getLLVMArchSuffixForARM()
StringRef clang::driver::tools::arm::getLLVMArchSuffixForARM (llvm::StringRef CPU, llvm::StringRef Arch, const llvm::Triple & Triple)
getReadTPMode()
ReadTPMode clang::driver::tools::arm::getReadTPMode (const Driver & D, const llvm::opt::ArgList & Args, const llvm::Triple & Triple, bool ForAS)
isARMAProfile()
bool clang::driver::tools::arm::isARMAProfile (const llvm::Triple & Triple)
Definition at line 37 of file ARM.cpp.
isARMMProfile()
bool clang::driver::tools::arm::isARMMProfile (const llvm::Triple & Triple)
Definition at line 31 of file ARM.cpp.
Referenced by useAAPCSForMachO().
isHardTPSupported()
bool clang::driver::tools::arm::isHardTPSupported (const llvm::Triple & Triple)
Definition at line 154 of file ARM.cpp.
References getARMSubArchVersionNumber().
Referenced by RenderSSPOptions().
setArchNameInTriple()
void clang::driver::tools::arm::setArchNameInTriple (const Driver & D, const llvm::opt::ArgList & Args, types::ID InputType, llvm::Triple & Triple)
Referenced by clang::driver::ToolChain::ComputeLLVMTriple().
setFloatABIInTriple()
void clang::driver::tools::arm::setFloatABIInTriple (const Driver & D, const llvm::opt::ArgList & Args, llvm::Triple & triple)
Referenced by clang::driver::ToolChain::ComputeLLVMTriple().
useAAPCSForMachO()
bool clang::driver::tools::arm::useAAPCSForMachO (const llvm::Triple & T)
Definition at line 143 of file ARM.cpp.
References isARMMProfile().
Referenced by getDefaultFloatABI().