clang: clang::comments Namespace Reference
clang::comments Namespace Reference
Namespaces
tok
Classes
class Comment
Any part of the comment.
class InlineContentComment
Inline content (contained within a block).
class TextComment
Plain text.
class InlineCommandComment
A command with word-like arguments that is considered inline content.
class HTMLTagComment
Abstract class for opening and closing HTML tags.
class HTMLStartTagComment
An opening HTML tag with attributes.
class HTMLEndTagComment
A closing HTML tag.
class BlockContentComment
Block content (contains inline content).
class ParagraphComment
A single paragraph that contains inline content.
class BlockCommandComment
A command that has zero or more word-like arguments (number of word-like arguments depends on command name) and a paragraph as an argument (e.
class ParamCommandComment
Doxygen \param command.
class TParamCommandComment
Doxygen \tparam command, describes a template parameter.
class VerbatimBlockLineComment
A line of text contained in a verbatim block.
class VerbatimBlockComment
A verbatim block command (e.
class VerbatimLineComment
A verbatim line command.
struct DeclInfo
Information about the declaration, useful to clients of FullComment.
class FullComment
A full comment attached to a declaration, contains block content.
class BriefParser
A very simple comment parser that extracts "a brief description".
struct CommandInfo
Information about a single command.
class CommandTraits
This class provides information about commands that can be used in comments.
class Token
Comment token.
class Lexer
Comment lexer.
class Parser
Doxygen comment parser.
class Sema
class CommentVisitorBase
class CommentVisitor
class ConstCommentVisitor
class TextTokenRetokenizer
Re-lexes a sequence of tok::text tokens.
Enumerations
enum CommandMarkerKind { CMK_Backslash = 0 , CMK_At = 1 }
Describes the syntax that was used in a documentation command.
enum class CommentKind {
None = 0 , COMMENT , COMMENT_RANGE , LAST_COMMENT_RANGE ,
ABSTRACT_COMMENT
}
enum class InlineCommandRenderKind {
Normal , Bold , Monospaced , Emphasized ,
Anchor
}
The most appropriate rendering mode for this command, chosen on command semantics in Doxygen.
enum class ParamCommandPassDirection { In , Out , InOut }
Functions
static TypeLoc lookThroughTypedefOrTypeAliasLocs (TypeLoc &SrcTL)
static bool getFunctionTypeLoc (TypeLoc TL, FunctionTypeLoc &ResFTL)
static bool isHTMLNamedCharacterReferenceCharacter (char C)
static bool isHTMLDecimalCharacterReferenceCharacter (char C)
static bool isHTMLHexCharacterReferenceCharacter (char C)
static StringRef convertCodePointToUTF8 (llvm::BumpPtrAllocator &Allocator, unsigned CodePoint)
static ParamCommandPassDirection getParamPassDirection (StringRef Arg)
Turn a string into the corresponding PassDirection or -1 if it's not valid.
static bool isClassOrStructDeclImpl (const Decl *D)
Enumeration Type Documentation
CommandMarkerKind
enum clang::comments::CommandMarkerKind
Describes the syntax that was used in a documentation command.
Exact values of this enumeration are important because they used to select parts of diagnostic messages. Audit diagnostics before changing or adding a new value.
Enumerator
CMK_Backslash
Command started with a backslash character:
\foo
CMK_At
Command started with an 'at' character:
@foo
Definition at line 38 of file Comment.h.
CommentKind
enum clang::comments::CommentKind strong
Enumerator
None
COMMENT
COMMENT_RANGE
LAST_COMMENT_RANGE
ABSTRACT_COMMENT
Definition at line 52 of file Comment.h.
InlineCommandRenderKind
enum clang::comments::InlineCommandRenderKind strong
The most appropriate rendering mode for this command, chosen on command semantics in Doxygen.
Enumerator
Normal
Bold
Monospaced
Emphasized
Anchor
Definition at line 326 of file Comment.h.
ParamCommandPassDirection
enum clang::comments::ParamCommandPassDirection strong
Enumerator
In
Out
InOut
Definition at line 708 of file Comment.h.
Function Documentation
convertCodePointToUTF8()
static StringRef clang::comments::convertCodePointToUTF8 (llvm::BumpPtrAllocator & Allocator, unsigned CodePoint) inline static
Definition at line 39 of file CommentLexer.cpp.
getFunctionTypeLoc()
static bool clang::comments::getFunctionTypeLoc (TypeLoc TL, FunctionTypeLoc & ResFTL) static
Definition at line 156 of file Comment.cpp.
References clang::TemplateArgumentLoc::getArgument(), clang::TypeLoc::getAs(), clang::TemplateArgument::getKind(), clang::TypeSourceInfo::getTypeLoc(), clang::TemplateArgumentLoc::getTypeSourceInfo(), clang::TypeLoc::getUnqualifiedLoc(), lookThroughTypedefOrTypeAliasLocs(), and clang::TemplateArgument::Type.
Referenced by clang::comments::DeclInfo::fill().
getParamPassDirection()
static ParamCommandPassDirection clang::comments::getParamPassDirection (StringRef Arg) static
Turn a string into the corresponding PassDirection or -1 if it's not valid.
Definition at line 222 of file CommentSema.cpp.
References In, InOut, and Out.
Referenced by clang::comments::Sema::actOnParamCommandDirectionArg().
isClassOrStructDeclImpl()
static bool clang::comments::isClassOrStructDeclImpl (const Decl * D) static
Definition at line 875 of file CommentSema.cpp.
isHTMLDecimalCharacterReferenceCharacter()
static bool clang::comments::isHTMLDecimalCharacterReferenceCharacter (char C) inline static
Definition at line 31 of file CommentLexer.cpp.
References clang::isDigit().
isHTMLHexCharacterReferenceCharacter()
static bool clang::comments::isHTMLHexCharacterReferenceCharacter (char C) inline static
Definition at line 35 of file CommentLexer.cpp.
References clang::isHexDigit().
isHTMLNamedCharacterReferenceCharacter()
static bool clang::comments::isHTMLNamedCharacterReferenceCharacter (char C) inline static
Definition at line 27 of file CommentLexer.cpp.
References clang::isLetter().
lookThroughTypedefOrTypeAliasLocs()
static TypeLoc clang::comments::lookThroughTypedefOrTypeAliasLocs (TypeLoc & SrcTL) static
Definition at line 128 of file Comment.cpp.
References clang::TypeLoc::getAs(), clang::TypeLoc::getUnqualifiedLoc(), and clang::TypeLoc::IgnoreParens().
Referenced by getFunctionTypeLoc().