clang: clang::driver::tools::ppc Namespace Reference
clang::driver::tools::ppc Namespace Reference
Enumerations
enum FloatABI { FloatABI::Invalid, FloatABI::Soft, FloatABI::Hard }
enum ReadGOTPtrMode { ReadGOTPtrMode::Bss, ReadGOTPtrMode::SecurePlt }
Functions
bool hasPPCAbiArg (const llvm::opt::ArgList &Args, const char *Value)
FloatABI getPPCFloatABI (const Driver &D, const llvm::opt::ArgList &Args)
std::string getPPCTargetCPU (const llvm::opt::ArgList &Args)
const char * getPPCAsmModeForCPU (StringRef Name)
ReadGOTPtrMode getPPCReadGOTPtrMode (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args)
void getPPCTargetFeatures (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, std::vector< llvm::StringRef > &Features)
Enumeration Type Documentation
FloatABI
enum clang::driver::tools::ppc::FloatABI strong
Enumerator
Invalid
Soft
Hard
Definition at line 25 of file PPC.h.
ReadGOTPtrMode
enum clang::driver::tools::ppc::ReadGOTPtrMode strong
Enumerator
Bss
SecurePlt
Definition at line 31 of file PPC.h.
Function Documentation
getPPCAsmModeForCPU()
const char * clang::driver::tools::ppc::getPPCAsmModeForCPU (StringRef Name)
Definition at line 93 of file PPC.cpp.
Referenced by clang::driver::tools::gnutools::Assembler::ConstructJob().
getPPCFloatABI()
FloatABI clang::driver::tools::ppc::getPPCFloatABI (const Driver & D, const llvm::opt::ArgList & Args)
getPPCReadGOTPtrMode()
ReadGOTPtrMode clang::driver::tools::ppc::getPPCReadGOTPtrMode (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args)
getPPCTargetCPU()
std::string clang::driver::tools::ppc::getPPCTargetCPU (const llvm::opt::ArgList & Args)
getPPCTargetFeatures()
void clang::driver::tools::ppc::getPPCTargetFeatures (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, std::vector< llvm::StringRef > & Features)
Referenced by getTargetFeatures().
hasPPCAbiArg()
bool clang::driver::tools::ppc::hasPPCAbiArg (const llvm::opt::ArgList & Args, const char * Value)
Referenced by clang::driver::toolchains::Linux::getDynamicLinker().