clang: lib/ARCMigrate/ObjCMT.cpp File Reference
ObjCMT.cpp File Reference
#include "Transforms.h"
#include "clang/Analysis/RetainSummaryManager.h"
#include "clang/ARCMigrate/ARCMT.h"
#include "clang/ARCMigrate/ARCMTActions.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/NSAPI.h"
#include "clang/AST/ParentMap.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Analysis/DomainSpecific/CocoaConventions.h"
#include "clang/Basic/FileManager.h"
#include "clang/Edit/Commit.h"
#include "clang/Edit/EditedSource.h"
#include "clang/Edit/EditsReceiver.h"
#include "clang/Edit/Rewriters.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/MultiplexConsumer.h"
#include "clang/Lex/PPConditionalDirectiveRecord.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Rewrite/Core/Rewriter.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/YAMLParser.h"
Classes
struct llvm::DenseMapInfo< EditEntry >
Namespaces
llvm
YAML serialization mapping.
Functions
static void append_attr (std::string &PropertyString, const char *attr, bool &LParenAdded)
static void MigrateBlockOrFunctionPointerTypeVariable (std::string &PropertyString, const std::string &TypeString, const char *name)
static const char * PropertyMemoryAttribute (ASTContext &Context, QualType ArgType)
static void rewriteToObjCProperty (const ObjCMethodDecl *Getter, const ObjCMethodDecl *Setter, const NSAPI &NS, edit::Commit &commit, unsigned LengthOfPrefix, bool Atomic, bool UseNsIosOnlyMacro, bool AvailabilityArgsMatch)
static bool IsCategoryNameWithDeprecatedSuffix (ObjCContainerDecl *D)
static bool ClassImplementsAllMethodsAndProperties (ASTContext &Ctx, const ObjCImplementationDecl *ImpDecl, const ObjCInterfaceDecl *IDecl, ObjCProtocolDecl *Protocol)
static bool rewriteToObjCInterfaceDecl (const ObjCInterfaceDecl *IDecl, llvm::SmallVectorImpl< ObjCProtocolDecl * > &ConformingProtocols, const NSAPI &NS, edit::Commit &commit)
static StringRef GetUnsignedName (StringRef NSIntegerName)
static bool rewriteToNSEnumDecl (const EnumDecl *EnumDcl, const TypedefDecl *TypedefDcl, const NSAPI &NS, edit::Commit &commit, StringRef NSIntegerName, bool NSOptions)
static void rewriteToNSMacroDecl (ASTContext &Ctx, const EnumDecl *EnumDcl, const TypedefDecl *TypedefDcl, const NSAPI &NS, edit::Commit &commit, bool IsNSIntegerType)
static bool UseNSOptionsMacro (Preprocessor &PP, ASTContext &Ctx, const EnumDecl *EnumDcl)
static void ReplaceWithInstancetype (ASTContext &Ctx, const ObjCMigrateASTConsumer &ASTC, ObjCMethodDecl *OM)
static void ReplaceWithClasstype (const ObjCMigrateASTConsumer &ASTC, ObjCMethodDecl *OM)
static bool TypeIsInnerPointer (QualType T)
static bool versionsMatch (const VersionTuple &X, const VersionTuple &Y)
Check whether the two versions match.
static bool AvailabilityAttrsMatch (Attr *At1, Attr *At2)
AvailabilityAttrsMatch - This routine checks that if comparing two availability attributes, all their components match.
static bool MatchTwoAttributeLists (const AttrVec &Attrs1, const AttrVec &Attrs2, bool &AvailabilityArgsMatch)
static bool AttributesMatch (const Decl *Decl1, const Decl *Decl2, bool &AvailabilityArgsMatch)
AttributesMatch - This routine checks list of attributes for two decls.
static bool IsValidIdentifier (ASTContext &Ctx, const char *Name)
static bool IsVoidStarType (QualType Ty)
static bool AuditedType (QualType AT)
AuditedType - This routine audits the type AT and returns false if it is one of known CF object types or of the "void *" variety.
static bool hasSuperInitCall (const ObjCMethodDecl *MD)
static std::vector< std::string > getAllowListFilenames (StringRef DirPath)
static bool reportDiag (const Twine &Err, DiagnosticsEngine &Diag)
static std::string applyEditsToTemp (FileEntryRef FE, ArrayRef< EditEntry > Edits, FileManager &FileMgr, DiagnosticsEngine &Diag)
Function Documentation
append_attr()
static void append_attr (std::string & PropertyString, const char * attr, bool & LParenAdded) static
Definition at line 386 of file ObjCMT.cpp.
References clang::ast_matchers::attr.
Referenced by rewriteToObjCProperty().
applyEditsToTemp()
static std::string applyEditsToTemp (FileEntryRef FE, ArrayRef< EditEntry > Edits, FileManager & FileMgr, DiagnosticsEngine & Diag) static
Definition at line 2154 of file ObjCMT.cpp.
References clang::edit::EditedSource::applyRewrites(), clang::SrcMgr::C_User, clang::edit::EditedSource::commit(), Diag(), clang::CharSourceRange::getCharRange(), clang::FileEntryRef::getName(), clang::Rewriter::getRewriteBufferFor(), clang::edit::Commit::insert(), clang::ento::OS, clang::edit::Commit::remove(), clang::edit::Commit::replace(), reportDiag(), SM, string(), and clang::RewriteBuffer::write().
Referenced by clang::arcmt::getFileRemappingsFromFileList().
AttributesMatch()
static bool AttributesMatch (const Decl * Decl1, const Decl * Decl2, bool & AvailabilityArgsMatch) static
AttributesMatch - This routine checks list of attributes for two decls.
It returns false, if there is a mismatch in kind of attributes seen in the decls. It returns true if the two decls have list of same kind of attributes. Furthermore, when there are availability attributes in the two decls, it sets the AvailabilityArgsMatch to false if availability attributes have different versions, etc.
Definition at line 1129 of file ObjCMT.cpp.
References clang::Decl::getAttrs(), clang::Decl::hasAttrs(), clang::ast_matchers::match(), and MatchTwoAttributeLists().
AuditedType()
static bool AuditedType (QualType AT) static
AuditedType - This routine audits the type AT and returns false if it is one of known CF object types or of the "void *" variety.
It returns true if we don't care about the type such as a non-pointer or pointers which have no ownership issues (such as "int *").
Definition at line 1372 of file ObjCMT.cpp.
References clang::Type::isAnyPointerType(), clang::Type::isBlockPointerType(), clang::ento::coreFoundation::isCFObjectRef(), clang::Type::isObjCBuiltinType(), clang::Type::isObjCObjectPointerType(), and IsVoidStarType().
AvailabilityAttrsMatch()
static bool AvailabilityAttrsMatch (Attr * At1, Attr * At2) static
AvailabilityAttrsMatch - This routine checks that if comparing two availability attributes, all their components match.
It returns true, if not dealing with availability or when all components of availability attributes match. This routine is only called when the attributes are of the same kind.
Definition at line 1080 of file ObjCMT.cpp.
References versionsMatch().
Referenced by MatchTwoAttributeLists().
ClassImplementsAllMethodsAndProperties()
static bool ClassImplementsAllMethodsAndProperties (ASTContext & Ctx, const ObjCImplementationDecl * ImpDecl, const ObjCInterfaceDecl * IDecl, ObjCProtocolDecl * Protocol) static
Definition at line 601 of file ObjCMT.cpp.
References clang::DeclContextLookupResult::empty(), clang::DeclContextLookupResult::find_first(), clang::ObjCImplDecl::FindPropertyImplDecl(), clang::ASTContext::hasSameType(), clang::DeclContext::lookup(), clang::ast_matchers::match(), clang::ASTContext::ObjCMethodsAreEqual(), clang::ObjCMethodDecl::Optional, clang::ObjCPropertyDecl::Optional, and clang::Property.
getAllowListFilenames()
static std::vector<std::string> getAllowListFilenames (StringRef DirPath) static
Definition at line 1989 of file ObjCMT.cpp.
References string().
Referenced by clang::arcmt::MigrateSourceAction::CreateASTConsumer().
GetUnsignedName()
static StringRef GetUnsignedName (StringRef NSIntegerName) static
Definition at line 694 of file ObjCMT.cpp.
Referenced by rewriteToNSEnumDecl().
hasSuperInitCall()
static bool hasSuperInitCall (const ObjCMethodDecl * MD) static
Definition at line 1694 of file ObjCMT.cpp.
References clang::ObjCMethodDecl::getBody().
IsCategoryNameWithDeprecatedSuffix()
static bool IsCategoryNameWithDeprecatedSuffix (ObjCContainerDecl * D) static
Definition at line 565 of file ObjCMT.cpp.
IsValidIdentifier()
static bool IsValidIdentifier (ASTContext & Ctx, const char * Name) static
Definition at line 1144 of file ObjCMT.cpp.
IsVoidStarType()
static bool IsVoidStarType (QualType Ty) static
Definition at line 1355 of file ObjCMT.cpp.
References clang::Type::castAs(), clang::PointerType::getPointeeType(), clang::QualType::getTypePtr(), clang::QualType::getUnqualifiedType(), clang::Type::isPointerType(), and clang::Type::isVoidType().
Referenced by AuditedType().
MatchTwoAttributeLists()
static bool MatchTwoAttributeLists (const AttrVec & Attrs1, const AttrVec & Attrs2, bool & AvailabilityArgsMatch) static
Definition at line 1100 of file ObjCMT.cpp.
References AvailabilityAttrsMatch(), getKind(), and clang::ast_matchers::match().
Referenced by AttributesMatch().
MigrateBlockOrFunctionPointerTypeVariable()
static void MigrateBlockOrFunctionPointerTypeVariable (std::string & PropertyString, const std::string & TypeString, const char * name) static
Definition at line 398 of file ObjCMT.cpp.
References clang::transformer::name().
Referenced by rewriteToObjCProperty().
PropertyMemoryAttribute()
static const char* PropertyMemoryAttribute (ASTContext & Context, QualType ArgType) static
Definition at line 429 of file ObjCMT.cpp.
References clang::IdentifierTable::get(), clang::Type::getAs(), clang::QualType::getObjCLifetime(), clang::ASTContext::Idents, clang::Type::isBlockPointerType(), clang::Type::isObjCRetainableType(), clang::ObjCInterfaceDecl::lookupNestedProtocol(), clang::Qualifiers::OCL_None, clang::Qualifiers::OCL_Strong, and clang::Qualifiers::OCL_Weak.
Referenced by rewriteToObjCProperty().
ReplaceWithClasstype()
static void ReplaceWithClasstype (const ObjCMigrateASTConsumer & ASTC, ObjCMethodDecl * OM) static
Definition at line 978 of file ObjCMT.cpp.
References clang::TypeLoc::getBeginLoc(), clang::ObjCMethodDecl::getBeginLoc(), clang::ObjCMethodDecl::getClassInterface(), clang::TypeLoc::getEndLoc(), clang::NamedDecl::getName(), clang::ObjCMethodDecl::getReturnTypeSourceInfo(), clang::edit::Commit::replace(), and string().
ReplaceWithInstancetype()
static void ReplaceWithInstancetype (ASTContext & Ctx, const ObjCMigrateASTConsumer & ASTC, ObjCMethodDecl * OM) static
Definition at line 955 of file ObjCMT.cpp.
References clang::TypeLoc::getBeginLoc(), clang::ObjCMethodDecl::getBeginLoc(), clang::TypeLoc::getEndLoc(), clang::ASTContext::getObjCInstanceType(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getReturnTypeSourceInfo(), clang::ObjCMethodDecl::isInstanceMethod(), clang::edit::Commit::replace(), and string().
reportDiag()
static bool reportDiag (const Twine & Err, DiagnosticsEngine & Diag) static
Definition at line 2148 of file ObjCMT.cpp.
References Diag(), and clang::DiagnosticsEngine::Error.
Referenced by applyEditsToTemp().
rewriteToNSEnumDecl()
static bool rewriteToNSEnumDecl (const EnumDecl * EnumDcl, const TypedefDecl * TypedefDcl, const NSAPI & NS, edit::Commit & commit, StringRef NSIntegerName, bool NSOptions) static
Definition at line 705 of file ObjCMT.cpp.
References clang::arcmt::trans::findLocationAfterSemi(), clang::arcmt::trans::findSemiAfterLocation(), clang::NSAPI::getASTContext(), clang::TypeDecl::getBeginLoc(), clang::Decl::getEndLoc(), clang::NamedDecl::getIdentifier(), clang::SourceLocation::getLocWithOffset(), clang::IdentifierInfo::getName(), GetUnsignedName(), clang::edit::Commit::insertFromRange(), clang::SourceLocation::isValid(), clang::edit::Commit::remove(), clang::edit::Commit::replace(), and string().
rewriteToNSMacroDecl()
static void rewriteToNSMacroDecl (ASTContext & Ctx, const EnumDecl * EnumDcl, const TypedefDecl * TypedefDcl, const NSAPI & NS, edit::Commit & commit, bool IsNSIntegerType) static
Definition at line 759 of file ObjCMT.cpp.
References clang::QualType::getAsString(), clang::SourceRange::getBegin(), clang::TypeDecl::getBeginLoc(), clang::TagDecl::getBraceRange(), clang::CharSourceRange::getCharRange(), clang::Decl::getEndLoc(), clang::NamedDecl::getIdentifier(), clang::EnumDecl::getIntegerType(), clang::SourceLocation::getLocWithOffset(), clang::IdentifierInfo::getName(), clang::ASTContext::getPrintingPolicy(), clang::SourceLocation::isInvalid(), clang::QualType::isNull(), clang::edit::Commit::remove(), clang::edit::Commit::replace(), and string().
rewriteToObjCInterfaceDecl()
static bool rewriteToObjCInterfaceDecl (const ObjCInterfaceDecl * IDecl, llvm::SmallVectorImpl< ObjCProtocolDecl * > & ConformingProtocols, const NSAPI & NS, edit::Commit & commit) static
Definition at line 662 of file ObjCMT.cpp.
References clang::ObjCListBase::empty(), clang::Decl::getLocation(), clang::ObjCInterfaceDecl::getReferencedProtocols(), clang::ObjCInterfaceDecl::getSuperClass(), clang::ObjCInterfaceDecl::getSuperClassLoc(), clang::edit::Commit::insertAfterToken(), clang::ObjCInterfaceDecl::protocol_loc_end(), and string().
rewriteToObjCProperty()
static void rewriteToObjCProperty (const ObjCMethodDecl * Getter, const ObjCMethodDecl * Setter, const NSAPI & NS, edit::Commit & commit, unsigned LengthOfPrefix, bool Atomic, bool UseNsIosOnlyMacro, bool AvailabilityArgsMatch) static
Definition at line 455 of file ObjCMT.cpp.
References append_attr(), clang::QualType::getAsString(), clang::NSAPI::getASTContext(), clang::ObjCMethodDecl::getBeginLoc(), clang::ASTContext::getCanonicalType(), clang::CharSourceRange::getCharRange(), clang::ObjCMethodDecl::getDeclaratorEndLoc(), clang::SourceLocation::getLocWithOffset(), clang::NamedDecl::getNameAsString(), clang::Selector::getNameForSlot(), clang::ASTContext::getPrintingPolicy(), clang::ASTContext::getQualifiedType(), clang::QualType::getQualifiers(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), clang::ObjCMethodDecl::getSelectorStartLoc(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), clang::Qualifiers::hasObjCLifetime(), clang::Type::isBlockPointerType(), clang::Type::isFunctionPointerType(), clang::NSAPI::isMacroDefined(), clang::Type::isRealType(), clang::isUppercase(), MigrateBlockOrFunctionPointerTypeVariable(), clang::ObjCMethodDecl::param_begin(), PropertyMemoryAttribute(), clang::edit::Commit::remove(), clang::Qualifiers::removeObjCLifetime(), clang::edit::Commit::replace(), string(), clang::PrintingPolicy::SuppressLifetimeQualifiers, clang::PrintingPolicy::SuppressStrongLifetime, and clang::toLowercase().
TypeIsInnerPointer()
static bool TypeIsInnerPointer (QualType T) static
Definition at line 1046 of file ObjCMT.cpp.
References clang::Type::getAs(), clang::RecordType::getDecl(), clang::PointerType::getPointeeType(), clang::QualType::getTypePtr(), clang::QualType::getUnqualifiedType(), clang::Type::isAnyPointerType(), clang::Type::isBlockPointerType(), clang::ento::coreFoundation::isCFObjectRef(), clang::TagDecl::isCompleteDefinition(), clang::Type::isFunctionPointerType(), clang::Type::isObjCBuiltinType(), clang::Type::isObjCObjectPointerType(), and clang::Type::isPointerType().
UseNSOptionsMacro()
static bool UseNSOptionsMacro (Preprocessor & PP, ASTContext & Ctx, const EnumDecl * EnumDcl) static
Definition at line 790 of file ObjCMT.cpp.
References clang::EnumDecl::enumerators(), clang::Token::getLength(), clang::Token::getLiteralData(), clang::Preprocessor::getRawToken(), clang::Expr::IgnoreParenCasts(), clang::Token::isLiteral(), and clang::toLowercase().
versionsMatch()
static bool versionsMatch (const VersionTuple & X, const VersionTuple & Y) static
Check whether the two versions match.
Definition at line 1071 of file ObjCMT.cpp.
References clang::tooling::X().
Referenced by AvailabilityAttrsMatch().