clang: lib/StaticAnalyzer/Checkers/ObjCContainersASTChecker.cpp File Reference
ObjCContainersASTChecker.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/raw_ostream.h"
Functions
static StringRef getCalleeName (CallExpr *CE)
Function Documentation
getCalleeName()
static StringRef getCalleeName (CallExpr * CE) static
Definition at line 84 of file ObjCContainersASTChecker.cpp.
References clang::CallExpr::getDirectCallee(), clang::NamedDecl::getIdentifier(), and clang::IdentifierInfo::getName().