clang: lib/AST/OpenMPClause.cpp File Reference
OpenMPClause.cpp File Reference
#include "clang/AST/OpenMPClause.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/OpenMPKinds.h"
#include "clang/Basic/TargetInfo.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <cassert>
#include "llvm/Frontend/OpenMP/OMP.inc"
Macros
#define GEN_CLANG_CLAUSE_CLASS
#define CLAUSE_CLASS(Enum, Str, Class)
#define GEN_CLANG_CLAUSE_CLASS
#define CLAUSE_CLASS(Enum, Str, Class)
#define CLAUSE_NO_CLASS(Enum, Str)
Functions
static Stmt ** getAddrOfExprAsWritten (Stmt *S)
Gets the address of the original, non-captured, expression used in the clause as the preinitializer.
template<typename T >
static void PrintMapper (raw_ostream &OS, T *Node, const PrintingPolicy &Policy)
Macro Definition Documentation
CLAUSE_CLASS [1/2]
#define CLAUSE_CLASS (Enum, Str, Class)
Value:
  case Enum:                                                                   \
    return static_cast<Class *>(this)->children();
CLAUSE_CLASS [2/2]
#define CLAUSE_CLASS (Enum, Str, Class)
Value:
  case Enum:                                                                   \
    return static_cast<Class *>(this)->used_children();
CLAUSE_NO_CLASS
#define CLAUSE_NO_CLASS (Enum, Str)
Value:
  case Enum:                                                                   \
    break;
GEN_CLANG_CLAUSE_CLASS [1/2]
#define GEN_CLANG_CLAUSE_CLASS
GEN_CLANG_CLAUSE_CLASS [2/2]
#define GEN_CLANG_CLAUSE_CLASS
Function Documentation
getAddrOfExprAsWritten()
static Stmt** getAddrOfExprAsWritten (Stmt * S) static
Gets the address of the original, non-captured, expression used in the clause as the preinitializer.
Definition at line 276 of file OpenMPClause.cpp.
Referenced by clang::OMPIfClause::used_children(), clang::OMPFinalClause::used_children(), clang::OMPPriorityClause::used_children(), clang::OMPGrainsizeClause::used_children(), clang::OMPNumTasksClause::used_children(), clang::OMPNovariantsClause::used_children(), and clang::OMPNocontextClause::used_children().
PrintMapper()
template<typename T > static void PrintMapper (raw_ostream & OS, T * Node, const PrintingPolicy & Policy) static
Definition at line 2147 of file OpenMPClause.cpp.
References Node, and clang::NestedNameSpecifier::print().