clang: lib/StaticAnalyzer/Checkers/OSObjectCStyleCast.cpp File Reference
OSObjectCStyleCast.cpp File Reference
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "llvm/Support/Debug.h"
Namespaces
clang
The JSON file list parser is used to communicate input to InstallAPI.
clang::ast_matchers
Functions
clang::ast_matchers::AST_MATCHER_P (StringLiteral, mentionsBoundType, std::string, BindingID)
static void emitDiagnostics (const BoundNodes &Nodes, BugReporter &BR, AnalysisDeclContext *ADC, const OSObjectCStyleCastChecker *Checker)
static decltype(auto) hasTypePointingTo (DeclarationMatcher DeclM)
Function Documentation
emitDiagnostics()
static void emitDiagnostics (const BoundNodes & Nodes, BugReporter & BR, AnalysisDeclContext * ADC, const OSObjectCStyleCastChecker * Checker) static
Definition at line 51 of file OSObjectCStyleCast.cpp.
References clang::ento::PathDiagnosticLocation::createBegin(), clang::ento::BugReporter::EmitBasicReport(), clang::AnalysisDeclContext::getDecl(), clang::ento::BugReporter::getSourceManager(), Nodes, and clang::ento::categories::SecurityError.
hasTypePointingTo()
static decltype(auto) hasTypePointingTo (DeclarationMatcher DeclM) static
Definition at line 76 of file OSObjectCStyleCast.cpp.
References clang::ast_matchers::hasDeclaration(), and clang::ast_matchers::pointerType.