clang: lib/Parse/ParseHLSL.cpp File Reference
ParseHLSL.cpp File Reference
#include "clang/AST/Attr.h"
#include "clang/Basic/AttributeCommonInfo.h"
#include "clang/Parse/ParseDiagnostic.h"
#include "clang/Parse/Parser.h"
#include "clang/Parse/RAIIObjectsForParser.h"
#include "clang/Sema/SemaHLSL.h"
Functions
static bool validateDeclsInsideHLSLBuffer (Parser::DeclGroupPtrTy DG, SourceLocation BufferLoc, bool IsCBuffer, Parser &P)
static void fixSeparateAttrArgAndNumber (StringRef ArgStr, SourceLocation ArgLoc, Token Tok, ArgsVector &ArgExprs, Parser &P, ASTContext &Ctx, Preprocessor &PP)
Function Documentation
fixSeparateAttrArgAndNumber()
static void fixSeparateAttrArgAndNumber (StringRef ArgStr, SourceLocation ArgLoc, Token Tok, ArgsVector & ArgExprs, Parser & P, ASTContext & Ctx, Preprocessor & PP) static
Definition at line 105 of file ParseHLSL.cpp.
References clang::IdentifierLoc::create(), clang::FixItHint::CreateReplacement(), clang::Token::getEndLoc(), clang::Preprocessor::getIdentifierInfo(), clang::Token::getLength(), clang::Token::getLiteralData(), and P.
validateDeclsInsideHLSLBuffer()
static bool validateDeclsInsideHLSLBuffer (Parser::DeclGroupPtrTy DG, SourceLocation BufferLoc, bool IsCBuffer, Parser & P) static
Definition at line 22 of file ParseHLSL.cpp.
References clang::DeclGroupRef::begin(), clang::DeclGroupRef::end(), clang::OpaquePtr< PtrTy >::get(), clang::Decl::getLocation(), and P.