clang: lib/Parse/ParseInit.cpp File Reference
ParseInit.cpp File Reference
#include "clang/Basic/TokenKinds.h"
#include "clang/Parse/ParseDiagnostic.h"
#include "clang/Parse/Parser.h"
#include "clang/Parse/RAIIObjectsForParser.h"
#include "clang/Sema/Designator.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Ownership.h"
#include "clang/Sema/Scope.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
Functions
static void CheckArrayDesignatorSyntax (Parser &P, SourceLocation Loc, Designation &Desig)
Function Documentation
CheckArrayDesignatorSyntax()
static void CheckArrayDesignatorSyntax (Parser & P, SourceLocation Loc, Designation & Desig) static
Definition at line 107 of file ParseInit.cpp.
References clang::Designation::getDesignator(), clang::Designation::getNumDesignators(), clang::Designator::isArrayDesignator(), clang::Designator::isArrayRangeDesignator(), and P.