clang: lib/Parse/ParseDecl.cpp File Reference
ParseDecl.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/PrettyDeclStackTrace.h"
#include "clang/Basic/AddressSpaces.h"
#include "clang/Basic/AttributeCommonInfo.h"
#include "clang/Basic/Attributes.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/TokenKinds.h"
#include "clang/Parse/ParseDiagnostic.h"
#include "clang/Parse/Parser.h"
#include "clang/Parse/RAIIObjectsForParser.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/SemaCUDA.h"
#include "clang/Sema/SemaDiagnostic.h"
#include "clang/Sema/SemaOpenMP.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include <optional>
#include "clang/Parse/AttrParserStringSwitches.inc"
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/TransformTypeTraits.def"
Macros
#define CLANG_ATTR_LATE_PARSED_LIST
#define CLANG_ATTR_IDENTIFIER_ARG_LIST
#define CLANG_ATTR_STRING_LITERAL_ARG_LIST
#define CLANG_ATTR_VARIADIC_IDENTIFIER_ARG_LIST
#define CLANG_ATTR_THIS_ISA_IDENTIFIER_ARG_LIST
#define CLANG_ATTR_ACCEPTS_EXPR_PACK
#define CLANG_ATTR_TYPE_ARG_LIST
#define CLANG_ATTR_ARG_CONTEXT_LIST
#define IMAGE_READ_WRITE_TYPE(Type, Id, Ext)
#define IMAGE_WRITE_TYPE(Type, Id, Ext)
#define IMAGE_READ_TYPE(ImgType, Id, Ext)
#define TRANSFORM_TYPE_TRAIT_DEF(_, Trait) case tok::kw___##Trait:
#define GENERIC_IMAGE_TYPE(ImgType, Id) case tok::kw_##ImgType##_t:
#define GENERIC_IMAGE_TYPE(ImgType, Id) case tok::kw_##ImgType##_t:
#define GENERIC_IMAGE_TYPE(ImgType, Id) case tok::kw_##ImgType##_t:
Functions
static StringRef normalizeAttrName (StringRef Name)
Normalizes an attribute name by dropping prefixed and suffixed __.
static bool isAttributeLateParsed (const IdentifierInfo &II)
isAttributeLateParsed - Return true if the attribute has arguments that require late parsing.
static bool FindLocsWithCommonFileID (Preprocessor &PP, SourceLocation StartLoc, SourceLocation EndLoc)
Check if the a start and end source location expand to the same macro.
static bool attributeHasIdentifierArg (const IdentifierInfo &II)
Determine whether the given attribute has an identifier argument.
static ParsedAttributeArgumentsProperties attributeStringLiteralListArg (const llvm::Triple &T, const IdentifierInfo &II)
Determine whether the given attribute has an identifier argument.
static bool attributeHasVariadicIdentifierArg (const IdentifierInfo &II)
Determine whether the given attribute has a variadic identifier argument.
static bool attributeTreatsKeywordThisAsIdentifier (const IdentifierInfo &II)
Determine whether the given attribute treats kw_this as an identifier.
static bool attributeAcceptsExprPack (const IdentifierInfo &II)
Determine if an attribute accepts parameter packs.
static bool attributeIsTypeArgAttr (const IdentifierInfo &II)
Determine whether the given attribute parses a type argument.
static bool attributeParsedArgsUnevaluated (const IdentifierInfo &II)
Determine whether the given attribute requires parsing its arguments in an unevaluated context or not.
static bool VersionNumberSeparator (const char Separator)
static bool isValidAfterIdentifierInDeclarator (const Token &T)
isValidAfterIdentifierInDeclaratorAfterDeclSpec - Return true if the specified token is valid after the identifier in a declarator which immediately follows the declspec.
static void DiagnoseCountAttributedTypeInUnnamedAnon (ParsingDeclSpec &DS, Parser &P)
static bool isPtrOperatorToken (tok::TokenKind Kind, const LangOptions &Lang, DeclaratorContext TheContext)
static bool isPipeDeclarator (const Declarator &D)
static SourceLocation getMissingDeclaratorIdLoc (Declarator &D, SourceLocation Loc)
Macro Definition Documentation
CLANG_ATTR_ACCEPTS_EXPR_PACK
#define CLANG_ATTR_ACCEPTS_EXPR_PACK
CLANG_ATTR_ARG_CONTEXT_LIST
#define CLANG_ATTR_ARG_CONTEXT_LIST
CLANG_ATTR_IDENTIFIER_ARG_LIST
#define CLANG_ATTR_IDENTIFIER_ARG_LIST
CLANG_ATTR_LATE_PARSED_LIST
#define CLANG_ATTR_LATE_PARSED_LIST
CLANG_ATTR_STRING_LITERAL_ARG_LIST
#define CLANG_ATTR_STRING_LITERAL_ARG_LIST
CLANG_ATTR_THIS_ISA_IDENTIFIER_ARG_LIST
#define CLANG_ATTR_THIS_ISA_IDENTIFIER_ARG_LIST
CLANG_ATTR_TYPE_ARG_LIST
#define CLANG_ATTR_TYPE_ARG_LIST
CLANG_ATTR_VARIADIC_IDENTIFIER_ARG_LIST
#define CLANG_ATTR_VARIADIC_IDENTIFIER_ARG_LIST
GENERIC_IMAGE_TYPE [1/3]
#define GENERIC_IMAGE_TYPE (ImgType, Id) case tok::kw_##ImgType##_t:
GENERIC_IMAGE_TYPE [2/3]
#define GENERIC_IMAGE_TYPE (ImgType, Id) case tok::kw_##ImgType##_t:
GENERIC_IMAGE_TYPE [3/3]
#define GENERIC_IMAGE_TYPE (ImgType, Id) case tok::kw_##ImgType##_t:
IMAGE_READ_TYPE
#define IMAGE_READ_TYPE (ImgType, Id, Ext)
Value:
    case tok::kw_##ImgType##_t: \
      if (!handleOpenCLImageKW(Ext, DeclSpec::TST_##ImgType##_t)) \
        goto DoneWithDeclSpec; \
      break;
IMAGE_READ_WRITE_TYPE
#define IMAGE_READ_WRITE_TYPE (Type, Id, Ext)
IMAGE_WRITE_TYPE
#define IMAGE_WRITE_TYPE (Type, Id, Ext)
TRANSFORM_TYPE_TRAIT_DEF
#define TRANSFORM_TYPE_TRAIT_DEF (_, Trait) case tok::kw___##Trait:
Function Documentation
attributeAcceptsExprPack()
static bool attributeAcceptsExprPack (const IdentifierInfo & II) static
Determine if an attribute accepts parameter packs.
Definition at line 323 of file ParseDecl.cpp.
References clang::IdentifierInfo::getName(), and normalizeAttrName().
attributeHasIdentifierArg()
static bool attributeHasIdentifierArg (const IdentifierInfo & II) static
Determine whether the given attribute has an identifier argument.
Definition at line 286 of file ParseDecl.cpp.
References clang::IdentifierInfo::getName(), and normalizeAttrName().
attributeHasVariadicIdentifierArg()
static bool attributeHasVariadicIdentifierArg (const IdentifierInfo & II) static
Determine whether the given attribute has a variadic identifier argument.
Definition at line 305 of file ParseDecl.cpp.
References clang::IdentifierInfo::getName(), and normalizeAttrName().
attributeIsTypeArgAttr()
static bool attributeIsTypeArgAttr (const IdentifierInfo & II) static
Determine whether the given attribute parses a type argument.
Definition at line 332 of file ParseDecl.cpp.
References clang::IdentifierInfo::getName(), and normalizeAttrName().
attributeParsedArgsUnevaluated()
static bool attributeParsedArgsUnevaluated (const IdentifierInfo & II) static
Determine whether the given attribute requires parsing its arguments in an unevaluated context or not.
Definition at line 342 of file ParseDecl.cpp.
References clang::IdentifierInfo::getName(), and normalizeAttrName().
attributeStringLiteralListArg()
static ParsedAttributeArgumentsProperties attributeStringLiteralListArg (const llvm::Triple & T, const IdentifierInfo & II) static
Determine whether the given attribute has an identifier argument.
Definition at line 296 of file ParseDecl.cpp.
References clang::IdentifierInfo::getName(), and normalizeAttrName().
attributeTreatsKeywordThisAsIdentifier()
static bool attributeTreatsKeywordThisAsIdentifier (const IdentifierInfo & II) static
Determine whether the given attribute treats kw_this as an identifier.
Definition at line 314 of file ParseDecl.cpp.
References clang::IdentifierInfo::getName(), and normalizeAttrName().
DiagnoseCountAttributedTypeInUnnamedAnon()
static void DiagnoseCountAttributedTypeInUnnamedAnon (ParsingDeclSpec & DS, Parser & P) static
Definition at line 4735 of file ParseDecl.cpp.
References clang::DeclSpec::getRepAsDecl(), clang::DeclSpec::getTypeSpecType(), P, and clang::DeclSpec::TST_struct.
FindLocsWithCommonFileID()
static bool FindLocsWithCommonFileID (Preprocessor & PP, SourceLocation StartLoc, SourceLocation EndLoc) static
Check if the a start and end source location expand to the same macro.
Definition at line 105 of file ParseDecl.cpp.
References clang::Preprocessor::getLangOpts(), clang::Preprocessor::getSourceManager(), clang::Lexer::isAtEndOfMacroExpansion(), clang::Lexer::isAtStartOfMacroExpansion(), clang::SourceLocation::isMacroID(), and SM.
getMissingDeclaratorIdLoc()
static SourceLocation getMissingDeclaratorIdLoc (Declarator & D, SourceLocation Loc) static
Definition at line 6620 of file ParseDecl.cpp.
References clang::UnqualifiedId::EndLocation, clang::Declarator::getName(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isValid(), and clang::UnqualifiedId::StartLocation.
isAttributeLateParsed()
static bool isAttributeLateParsed (const IdentifierInfo & II) static
isAttributeLateParsed - Return true if the attribute has arguments that require late parsing.
Definition at line 96 of file ParseDecl.cpp.
References clang::IdentifierInfo::getName(), and normalizeAttrName().
isPipeDeclarator()
static bool isPipeDeclarator (const Declarator & D) static
Definition at line 6412 of file ParseDecl.cpp.
References clang::Declarator::getNumTypeObjects(), clang::Declarator::getTypeObject(), clang::DeclaratorChunk::Kind, and clang::DeclaratorChunk::Pipe.
isPtrOperatorToken()
static bool isPtrOperatorToken (tok::TokenKind Kind, const LangOptions & Lang, DeclaratorContext TheContext) static
Definition at line 6383 of file ParseDecl.cpp.
References clang::ConversionId, and clang::CXXNew.
isValidAfterIdentifierInDeclarator()
static bool isValidAfterIdentifierInDeclarator (const Token & T) static
isValidAfterIdentifierInDeclaratorAfterDeclSpec - Return true if the specified token is valid after the identifier in a declarator which immediately follows the declspec.
For example, these things are valid:
 int x   [             4];         // direct-declarator
 int x   (             int y);     // direct-declarator
int(int x) // direct-declarator int x ; // simple-declaration int x = 17; // init-declarator-list int x , y; // init-declarator-list int x asm ("foo"); // init-declarator-list int x : 4; // struct-declarator int x { 5}; // C++'0x unified initializers
This is not, because 'x' does not immediately follow the declspec (though ')' happens to be valid anyway). int (x)
Definition at line 2886 of file ParseDecl.cpp.
References clang::T.
normalizeAttrName()
static StringRef normalizeAttrName (StringRef Name) static
Normalizes an attribute name by dropping prefixed and suffixed __.
Definition at line 88 of file ParseDecl.cpp.
Referenced by attributeAcceptsExprPack(), attributeHasIdentifierArg(), attributeHasVariadicIdentifierArg(), attributeIsTypeArgAttr(), attributeParsedArgsUnevaluated(), attributeStringLiteralListArg(), attributeTreatsKeywordThisAsIdentifier(), and isAttributeLateParsed().
VersionNumberSeparator()
static bool VersionNumberSeparator (const char Separator) static
Definition at line 1072 of file ParseDecl.cpp.