clang: lib/Parse/ParseDeclCXX.cpp File Reference
ParseDeclCXX.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/PrettyDeclStackTrace.h"
#include "clang/Basic/AttributeCommonInfo.h"
#include "clang/Basic/Attributes.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/OperatorKinds.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/TokenKinds.h"
#include "clang/Lex/LiteralSupport.h"
#include "clang/Parse/ParseDiagnostic.h"
#include "clang/Parse/Parser.h"
#include "clang/Parse/RAIIObjectsForParser.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/Scope.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/TimeProfiler.h"
#include <optional>
#include "clang/Basic/TransformTypeTraits.def"
Macros
#define TRANSFORM_TYPE_TRAIT_DEF(_, Trait)
#define TRANSFORM_TYPE_TRAIT_DEF(_, Trait) tok::kw___##Trait,
Functions
static FixItHint getStaticAssertNoMessageFixIt (const Expr *AssertExpr, SourceLocation EndExprLoc)
static void diagnoseDynamicExceptionSpecification (Parser &P, SourceRange Range, bool IsNoexcept)
static bool IsBuiltInOrStandardCXX11Attribute (IdentifierInfo *AttrName, IdentifierInfo *ScopeName)
Macro Definition Documentation
TRANSFORM_TYPE_TRAIT_DEF [1/2]
#define TRANSFORM_TYPE_TRAIT_DEF (_, Trait)
Value:
  case tok::kw___##Trait:                                                      \
    return DeclSpec::TST_##Trait;
TRANSFORM_TYPE_TRAIT_DEF [2/2]
#define TRANSFORM_TYPE_TRAIT_DEF (_, Trait) tok::kw___##Trait,
Function Documentation
diagnoseDynamicExceptionSpecification()
static void diagnoseDynamicExceptionSpecification (Parser & P, SourceRange Range, bool IsNoexcept) static
Definition at line 4171 of file ParseDeclCXX.cpp.
References clang::FixItHint::CreateReplacement(), and P.
getStaticAssertNoMessageFixIt()
static FixItHint getStaticAssertNoMessageFixIt (const Expr * AssertExpr, SourceLocation EndExprLoc) static
Definition at line 959 of file ParseDeclCXX.cpp.
References clang::FixItHint::CreateInsertion(), and clang::FixItHint::CreateReplacement().
IsBuiltInOrStandardCXX11Attribute()
static bool IsBuiltInOrStandardCXX11Attribute (IdentifierInfo * AttrName, IdentifierInfo * ScopeName) static
Definition at line 4539 of file ParseDeclCXX.cpp.
References clang::AttributeCommonInfo::AS_CXX11, clang::IdentifierInfo::getName(), and clang::AttributeCommonInfo::getParsedKind().