clang: lib/Parse/ParseOpenMP.cpp File Reference
ParseOpenMP.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/OpenMPClause.h"
#include "clang/AST/StmtOpenMP.h"
#include "clang/Basic/OpenMPKinds.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/TokenKinds.h"
#include "clang/Parse/ParseDiagnostic.h"
#include "clang/Parse/Parser.h"
#include "clang/Parse/RAIIObjectsForParser.h"
#include "clang/Sema/Scope.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/UniqueVector.h"
#include "llvm/Frontend/OpenMP/OMPAssume.h"
#include "llvm/Frontend/OpenMP/OMPContext.h"
Functions
static unsigned getOpenMPDirectiveKindEx (StringRef S)
static OpenMPDirectiveKindExWrapper parseOpenMPDirectiveKind (Parser &P)
static DeclarationName parseOpenMPReductionId (Parser &P)
static bool parseDeclareSimdClauses (Parser &P, OMPDeclareSimdDeclAttr::BranchStateTy &BS, ExprResult &SimdLen, SmallVectorImpl< Expr * > &Uniforms, SmallVectorImpl< Expr * > &Aligneds, SmallVectorImpl< Expr * > &Alignments, SmallVectorImpl< Expr * > &Linears, SmallVectorImpl< unsigned > &LinModifiers, SmallVectorImpl< Expr * > &Steps)
Parses clauses for 'declare simd' directive.
static bool checkExtensionProperty (Parser &P, SourceLocation Loc, OMPTraitProperty &TIProperty, OMPTraitSelector &TISelector, llvm::StringMap< SourceLocation > &Seen)
static ExprResult parseContextScore (Parser &P)
Parse optional 'score' '(' <expr> ')' ':'.
static Optional< OMPDeclareVariantAttr::InteropType > parseInteropTypeList (Parser &P)
Parse a list of interop-types.
static Optional< SimpleClauseData > parseOpenMPSimpleClause (Parser &P, OpenMPClauseKind Kind)
static bool ParseReductionId (Parser &P, CXXScopeSpec &ReductionIdScopeSpec, UnqualifiedId &ReductionId)
static OpenMPMapModifierKind isMapModifier (Parser &P)
Checks if the token is a valid map-type-modifier.
static OpenMPMapClauseKind isMapType (Parser &P)
Checks if the token is a valid map-type.
static void parseMapType (Parser &P, Parser::OpenMPVarListDataTy &Data)
Parse map-type in map clause.
Detailed Description
This file implements parsing of all OpenMP directives and clauses.
Definition in file ParseOpenMP.cpp.
Function Documentation
checkExtensionProperty()
static bool checkExtensionProperty (Parser & P, SourceLocation Loc, OMPTraitProperty & TIProperty, OMPTraitSelector & TISelector, llvm::StringMap< SourceLocation > & Seen) static
Definition at line 941 of file ParseOpenMP.cpp.
References clang::OMPTraitProperty::Kind, clang::OMPTraitSelector::Kind, P, clang::OMPTraitSelector::Properties, and clang::OMPTraitProperty::RawString.
getOpenMPDirectiveKindEx()
static unsigned getOpenMPDirectiveKindEx (StringRef S) static
Definition at line 99 of file ParseOpenMP.cpp.
Referenced by parseOpenMPDirectiveKind().
isMapModifier()
static OpenMPMapModifierKind isMapModifier (Parser & P) static
Checks if the token is a valid map-type-modifier.
FIXME: It will return an OpenMPMapClauseKind if that's what it parses.
Definition at line 3877 of file ParseOpenMP.cpp.
References clang::getOpenMPSimpleClauseType(), clang::Preprocessor::getSpelling(), clang::Token::is(), clang::OMPC_MAP_MODIFIER_unknown, and P.
Referenced by clang::Parser::parseMapTypeModifiers().
isMapType()
static OpenMPMapClauseKind isMapType (Parser & P) static
Checks if the token is a valid map-type.
FIXME: It will return an OpenMPMapModifierKind if that's what it parses.
Definition at line 3963 of file ParseOpenMP.cpp.
References clang::getOpenMPSimpleClauseType(), clang::Preprocessor::getSpelling(), clang::Token::isOneOf(), clang::OMPC_MAP_unknown, and P.
Referenced by parseMapType().
parseContextScore()
static ExprResult parseContextScore (Parser & P) static
Parse optional 'score' '(' <expr> ')' ':'.
Definition at line 1089 of file ParseOpenMP.cpp.
References P.
parseDeclareSimdClauses()
static bool parseDeclareSimdClauses (Parser & P, OMPDeclareSimdDeclAttr::BranchStateTy & BS, ExprResult & SimdLen, SmallVectorImpl< Expr * > & Uniforms, SmallVectorImpl< Expr * > & Aligneds, SmallVectorImpl< Expr * > & Alignments, SmallVectorImpl< Expr * > & Linears, SmallVectorImpl< unsigned > & LinModifiers, SmallVectorImpl< Expr * > & Steps) static
Parses clauses for 'declare simd' directive.
clause: 'inbranch' | 'notinbranch' 'simdlen' '(' <expr> ')' { 'uniform' '(' <argument_list> ')' } { 'aligned '(' <argument_list> [ ':' <alignment> ] ')' } { 'linear '(' <argument_list> [ ':' <step> ] ')' }
Definition at line 707 of file ParseOpenMP.cpp.
References clang::Parser::OpenMPVarListDataTy::DepModOrTailExpr, clang::Parser::OpenMPVarListDataTy::ExtraModifier, clang::Parser::OpenMPVarListDataTy::ExtraModifierLoc, clang::Token::getEndLoc(), clang::Token::getIdentifierInfo(), clang::Token::getLocation(), clang::IdentifierInfo::getName(), clang::Token::is(), clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::Token::isNot(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::OMPC_LINEAR_unknown, and P.
parseInteropTypeList()
static Optional<OMPDeclareVariantAttr::InteropType> parseInteropTypeList (Parser & P) static
Parse a list of interop-types.
These are 'target' and 'targetsync'. Both are allowed but duplication of either is not meaningful.
Definition at line 1498 of file ParseOpenMP.cpp.
References clang::Token::getIdentifierInfo(), clang::Token::is(), clang::IdentifierInfo::isStr(), and P.
parseMapType()
static void parseMapType (Parser & P, Parser::OpenMPVarListDataTy & Data) static
Parse map-type in map clause.
map([ [map-type-modifier[,] [map-type-modifier[,] ...] map-type : ] list) where, map-type ::= to | from | tofrom | alloc | release | delete
Definition at line 3978 of file ParseOpenMP.cpp.
References clang::Parser::OpenMPVarListDataTy::ExtraModifier, clang::Token::is(), isMapType(), clang::OMPC_MAP_unknown, and P.
Referenced by clang::Parser::ParseOpenMPVarList().
parseOpenMPDirectiveKind()
static OpenMPDirectiveKindExWrapper parseOpenMPDirectiveKind (Parser & P) static
Definition at line 120 of file ParseOpenMP.cpp.
References getOpenMPDirectiveKindEx(), clang::Token::isAnnotation(), and P.
parseOpenMPReductionId()
static DeclarationName parseOpenMPReductionId (Parser & P) static
Definition at line 217 of file ParseOpenMP.cpp.
References clang::ASTContext::DeclarationNames, clang::Sema::getASTContext(), clang::Token::getIdentifierInfo(), clang::Token::getKind(), clang::Token::getLocation(), clang::Token::is(), clang::OO_None, P, and clang::Parser::StopBeforeMatch.
parseOpenMPSimpleClause()
static Optional<SimpleClauseData> parseOpenMPSimpleClause (Parser & P, OpenMPClauseKind Kind) static
Definition at line 1792 of file ParseOpenMP.cpp.
References clang::BalancedDelimiterTracker::consumeClose(), clang::BalancedDelimiterTracker::expectAndConsume(), clang::BalancedDelimiterTracker::getCloseLocation(), clang::Token::getLocation(), clang::getOpenMPSimpleClauseType(), clang::Token::isAnnotation(), clang::Token::isNot(), and P.
ParseReductionId()
static bool ParseReductionId (Parser & P, CXXScopeSpec & ReductionIdScopeSpec, UnqualifiedId & ReductionId) static
Definition at line 3828 of file ParseOpenMP.cpp.
References clang::CXXScopeSpec::isEmpty(), clang::OO_None, P, and clang::UnqualifiedId::setOperatorFunctionId().
Referenced by clang::Parser::ParseOpenMPVarList().