clang: lib/StaticAnalyzer/Core/PlistDiagnostics.cpp File Reference
PlistDiagnostics.cpp File Reference
#include "clang/Analysis/IssueHash.h"
#include "clang/Analysis/MacroExpansionContext.h"
#include "clang/Analysis/PathDiagnostic.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/PlistSupport.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Version.h"
#include "clang/CrossTU/CrossTranslationUnit.h"
#include "clang/Frontend/ASTUnit.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/TokenConcatenation.h"
#include "clang/Rewrite/Core/HTMLRewrite.h"
#include "clang/StaticAnalyzer/Core/PathDiagnosticConsumers.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Support/Casting.h"
#include <memory>
#include <optional>
Functions
static void printCoverage (const PathDiagnostic *D, unsigned InputIndentLevel, SmallVectorImpl< FileID > &Fids, FIDMap &FM, llvm::raw_fd_ostream &o)
Print coverage information to output stream o.
static std::optional< StringRef > getExpandedMacro (SourceLocation MacroLoc, const cross_tu::CrossTranslationUnitContext &CTU, const MacroExpansionContext &MacroExpansions, const SourceManager &SM)
Function Documentation
getExpandedMacro()
static std::optional< StringRef > getExpandedMacro (SourceLocation MacroLoc, const cross_tu::CrossTranslationUnitContext & CTU, const MacroExpansionContext & MacroExpansions, const SourceManager & SM) static
Definition at line 828 of file PlistDiagnostics.cpp.
References clang::MacroExpansionContext::getExpandedText(), and clang::cross_tu::CrossTranslationUnitContext::getMacroExpansionContextForSourceLocation().
printCoverage()
static void printCoverage (const PathDiagnostic * D, unsigned InputIndentLevel, SmallVectorImpl< FileID > & Fids, FIDMap & FM, llvm::raw_fd_ostream & o) static
Print coverage information to output stream o.
May modify the used list of files Fids by inserting new ones.
Definition at line 488 of file PlistDiagnostics.cpp.
References clang::markup::AddFID(), clang::markup::EmitInteger(), clang::ento::PathDiagnostic::getExecutedLines(), and clang::Indent().