clang: lib/Lex/Pragma.cpp File Reference
Pragma.cpp File Reference
#include "clang/Lex/Pragma.h"
#include "clang/Basic/CLWarnings.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/DiagnosticLex.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TokenKinds.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/LexDiagnostic.h"
#include "clang/Lex/Lexer.h"
#include "clang/Lex/LiteralSupport.h"
#include "clang/Lex/MacroInfo.h"
#include "clang/Lex/ModuleLoader.h"
#include "clang/Lex/PPCallbacks.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/PreprocessorLexer.h"
#include "clang/Lex/PreprocessorOptions.h"
#include "clang/Lex/Token.h"
#include "clang/Lex/TokenLexer.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Timer.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <string>
#include <utility>
#include <vector>
Functions
static llvm::Optional< Token > LexHeader (Preprocessor &PP, Optional< FileEntryRef > &File, bool SuppressIncludeNotFoundError)
static bool LexModuleNameComponent (Preprocessor &PP, Token &Tok, std::pair< IdentifierInfo *, SourceLocation > &ModuleNameComponent, bool First)
static bool LexModuleName (Preprocessor &PP, Token &Tok, llvm::SmallVectorImpl< std::pair< IdentifierInfo *, SourceLocation >> &ModuleName)
Function Documentation
LexHeader()
static llvm::Optional<Token> LexHeader (Preprocessor & PP, Optional< FileEntryRef > & File, bool SuppressIncludeNotFoundError) static
Definition at line 506 of file Pragma.cpp.
References clang::Preprocessor::Diag(), clang::File, Filename, clang::Preprocessor::GetIncludeFilenameSpelling(), clang::Token::getLocation(), clang::Preprocessor::getSpelling(), clang::Token::isNot(), clang::Preprocessor::LexHeaderName(), and clang::Preprocessor::LookupFile().
Referenced by clang::Preprocessor::HandlePragmaDependency(), and clang::Preprocessor::HandlePragmaIncludeInstead().
LexModuleName()
static bool LexModuleName (Preprocessor & PP, Token & Tok, llvm::SmallVectorImpl< std::pair< IdentifierInfo *, SourceLocation >> & ModuleName) static
Definition at line 827 of file Pragma.cpp.
References clang::Token::isNot(), LexModuleNameComponent(), and clang::Preprocessor::LexUnexpandedToken().
LexModuleNameComponent()
static bool LexModuleNameComponent (Preprocessor & PP, Token & Tok, std::pair< IdentifierInfo *, SourceLocation > & ModuleNameComponent, bool First) static
Definition at line 806 of file Pragma.cpp.
References clang::Preprocessor::Diag(), clang::First, clang::Token::getIdentifierInfo(), clang::Preprocessor::getIdentifierInfo(), clang::Token::getLocation(), clang::Token::hasUDSuffix(), clang::Token::is(), clang::Token::isAnnotation(), and clang::Preprocessor::LexUnexpandedToken().
Referenced by clang::Preprocessor::HandlePragmaModuleBuild(), and LexModuleName().