clang: lib/Basic/ProfileList.cpp File Reference
ProfileList.cpp File Reference
#include "clang/Basic/ProfileList.h"
#include "clang/Basic/FileManager.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/Support/SpecialCaseList.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
Classes
class clang::ProfileSpecialCaseList
Namespaces
clang
The JSON file list parser is used to communicate input to InstallAPI.
Functions
static StringRef getSectionName (CodeGenOptions::ProfileInstrKind Kind)
Function Documentation
getSectionName()
static StringRef getSectionName (CodeGenOptions::ProfileInstrKind Kind) static
Definition at line 74 of file ProfileList.cpp.
References clang::CodeGenOptions::ProfileClangInstr, clang::CodeGenOptions::ProfileCSIRInstr, clang::CodeGenOptions::ProfileIRInstr, and clang::CodeGenOptions::ProfileNone.
Referenced by clang::ProfileList::getDefault(), clang::ProfileList::isFileExcluded(), and clang::ProfileList::isFunctionExcluded().