clang: lib/Driver/ToolChains/PS4CPU.cpp File Reference
PS4CPU.cpp File Reference
#include "PS4CPU.h"
#include "FreeBSD.h"
#include "CommonArgs.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include <cstdlib>
Functions
static void AddPS4SanitizerArgs (const ToolChain &TC, const ArgList &Args, ArgStringList &CmdArgs)
Function Documentation
AddPS4SanitizerArgs()
static void AddPS4SanitizerArgs (const ToolChain & TC, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 72 of file PS4CPU.cpp.
References clang::driver::ToolChain::getSanitizerArgs(), clang::driver::SanitizerArgs::needsAsanRt(), and clang::driver::SanitizerArgs::needsUbsanRt().
Referenced by clang::driver::tools::PS4cpu::Link::ConstructJob().