clang: lib/StaticAnalyzer/Core/RegionStore.cpp File Reference
RegionStore.cpp File Reference
#include "clang/AST/Attr.h"
#include "clang/AST/CharUnits.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/Analysis/Analyses/LiveVariables.h"
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/Basic/JsonSupport.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramStateTrait.h"
#include "llvm/ADT/ImmutableMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
#include <utility>
Namespaces
llvm
Diagnostic wrappers for TextAPI types for error reporting.
Typedefs
typedef llvm::ImmutableMap< BindingKey, SVal > ClusterBindings
typedef llvm::ImmutableMapRef< BindingKey, SVal > ClusterBindingsRef
typedef std::pair< BindingKey, SVal > BindingPair
typedef llvm::ImmutableMap< const MemRegion *, ClusterBindings > RegionBindings
typedef const RegionBindingsRef & RegionBindingsConstRef
typedef SmallVector< const FieldDecl *, 8 > FieldVector
Functions
static raw_ostream & llvm::operator<< (raw_ostream &Out, BindingKey K)
static bool isUnionField (const FieldRegion *FR)
static void getSymbolicOffsetFields (BindingKey K, FieldVector &Fields)
static bool isCompatibleWithFields (BindingKey K, const FieldVector &Fields)
static void collectSubRegionBindings (SmallVectorImpl< BindingPair > &Bindings, SValBuilder &SVB, const ClusterBindings &Cluster, const SubRegion *Top, BindingKey TopKey, bool IncludeAllDefaultBindings)
Collects all bindings in Cluster that may refer to bindings within Top.
static void collectSubRegionBindings (SmallVectorImpl< BindingPair > &Bindings, SValBuilder &SVB, const ClusterBindings &Cluster, const SubRegion *Top, bool IncludeAllDefaultBindings)
static QualType getUnderlyingType (const SubRegion *R)
static std::optional< nonloc::LazyCompoundVal > getExistingLazyBinding (SValBuilder &SVB, RegionBindingsConstRef B, const SubRegion *R, bool AllowSubregionBindings)
Checks to see if store B has a lazy binding for region R.
static SmallVector< uint64_t, 2 > getConstantArrayExtents (const ConstantArrayType *CAT)
This is a helper function for getConstantValFromConstArrayInitializer.
static std::pair< SmallVector< SVal, 2 >, const MemRegion * > getElementRegionOffsetsWithBase (const ElementRegion *ER)
This is a helper function for getConstantValFromConstArrayInitializer.
static std::optional< SVal > convertOffsetsFromSvalToUnsigneds (const SmallVector< SVal, 2 > &SrcOffsets, const SmallVector< uint64_t, 2 > ArrayExtents, SmallVector< uint64_t, 2 > &DstOffsets)
static std::optional< SVal > getDerivedSymbolForBinding (RegionBindingsConstRef B, const TypedValueRegion *BaseRegion, const TypedValueRegion *SubReg, const ASTContext &Ctx, SValBuilder &SVB)
static bool isRecordEmpty (const RecordDecl *RD)
Typedef Documentation
BindingPair
typedef std::pair<BindingKey, SVal> BindingPair
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 149 of file RegionStore.cpp.
ClusterBindings
typedef llvm::ImmutableMap<BindingKey, SVal> ClusterBindings
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 147 of file RegionStore.cpp.
ClusterBindingsRef
typedef llvm::ImmutableMapRef<BindingKey, SVal> ClusterBindingsRef
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 148 of file RegionStore.cpp.
FieldVector
typedef SmallVector<const FieldDecl *, 8> FieldVector
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 805 of file RegionStore.cpp.
RegionBindings
typedef llvm::ImmutableMap<const MemRegion *, ClusterBindings> RegionBindings
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 152 of file RegionStore.cpp.
RegionBindingsConstRef
typedef const RegionBindingsRef& RegionBindingsConstRef
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 265 of file RegionStore.cpp.
Function Documentation
collectSubRegionBindings() [1/2]
static void collectSubRegionBindings (SmallVectorImpl< BindingPair > & Bindings, SValBuilder & SVB, const ClusterBindings & Cluster, const SubRegion * Top, BindingKey TopKey, bool IncludeAllDefaultBindings) static
Collects all bindings in Cluster that may refer to bindings within Top.
Each binding is a pair whose first is the key (a BindingKey) and whose second is the value (an SVal).
The IncludeAllDefaultBindings parameter specifies whether to include default bindings that may extend beyond Top itself, e.g. if Top is an aggregate within a larger aggregate with a default binding.
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 851 of file RegionStore.cpp.
References clang::ento::SVal::getAs(), clang::ASTContext::getCharWidth(), clang::ento::SValBuilder::getContext(), clang::ento::SubRegion::getMemRegionManager(), clang::ento::MemRegionManager::getStaticSize(), getSymbolicOffsetFields(), isCompatibleWithFields(), and clang::ento::SubRegion::isSubRegionOf().
Referenced by collectSubRegionBindings(), and getExistingLazyBinding().
collectSubRegionBindings() [2/2]
static void collectSubRegionBindings (SmallVectorImpl< BindingPair > & Bindings, SValBuilder & SVB, const ClusterBindings & Cluster, const SubRegion * Top, bool IncludeAllDefaultBindings) static
Definition at line 922 of file RegionStore.cpp.
References collectSubRegionBindings().
convertOffsetsFromSvalToUnsigneds()
static std::optional<SVal> convertOffsetsFromSvalToUnsigneds (const SmallVector< SVal, 2 > & SrcOffsets, const SmallVector< uint64_t, 2 > ArrayExtents, SmallVector< uint64_t, 2 > & DstOffsets) static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1670 of file RegionStore.cpp.
References Offset, and V.
getConstantArrayExtents()
static SmallVector<uint64_t, 2> getConstantArrayExtents (const ConstantArrayType * CAT) static
This is a helper function for getConstantValFromConstArrayInitializer.
Return an array of extents of the declared array type.
E.g. for int x[1][2][3]; returns { 1, 2, 3 }.
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1611 of file RegionStore.cpp.
References clang::Type::getCanonicalTypeInternal(), clang::ArrayType::getElementType(), and clang::ConstantArrayType::getZExtSize().
getDerivedSymbolForBinding()
static std::optional<SVal> getDerivedSymbolForBinding (RegionBindingsConstRef B, const TypedValueRegion * BaseRegion, const TypedValueRegion * SubReg, const ASTContext & Ctx, SValBuilder & SVB) static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1883 of file RegionStore.cpp.
References clang::ento::SValBuilder::getDerivedRegionValueSymbolVal(), clang::ASTContext::getTypeSizeInChars(), clang::ento::TypedValueRegion::getValueType(), and clang::Type::isScalarType().
getElementRegionOffsetsWithBase()
static std::pair<SmallVector<SVal, 2>, const MemRegion *> getElementRegionOffsetsWithBase (const ElementRegion * ER) static
This is a helper function for getConstantValFromConstArrayInitializer.
Return an array of offsets from nested ElementRegions and a root base region. The array is never empty and a base region is never null.
E.g. for Element{Element{Element{VarRegion},1},2},3} returns { 3, 2, 1 }. This represents an access through indirection: arr[1][2][3];
Parameters
ER The given (possibly nested) ElementRegion.
Note
The result array is in the reverse order of indirection expression: arr[1][2][3] -> { 3, 2, 1 }. This helps to provide complexity O(n), where n is a number of indirections. It may not affect performance in real-life code, though.
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1636 of file RegionStore.cpp.
References clang::ento::ElementRegion::getIndex(), and clang::ento::SubRegion::getSuperRegion().
getExistingLazyBinding()
static std::optional<nonloc::LazyCompoundVal> getExistingLazyBinding (SValBuilder & SVB, RegionBindingsConstRef B, const SubRegion * R, bool AllowSubregionBindings) static
Checks to see if store B has a lazy binding for region R.
If AllowSubregionBindings is false, a lazy binding will be rejected if there are additional bindings within R.
Note that unlike RegionStoreManager::findLazyBinding, this will not search for lazy bindings for super-regions of R.
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1529 of file RegionStore.cpp.
References collectSubRegionBindings(), clang::ento::MemRegion::getBaseRegion(), clang::ento::SValBuilder::getContext(), getUnderlyingType(), clang::ASTContext::hasSameUnqualifiedType(), clang::QualType::isNull(), clang::Type::isVoidPointerType(), and V.
getSymbolicOffsetFields()
static void getSymbolicOffsetFields (BindingKey K, FieldVector & Fields) static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 807 of file RegionStore.cpp.
References isUnionField().
Referenced by collectSubRegionBindings(), and isCompatibleWithFields().
getUnderlyingType()
static QualType getUnderlyingType (const SubRegion * R) static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 1510 of file RegionStore.cpp.
Referenced by clang::UsingType::desugar(), getExistingLazyBinding(), MarkUsedTemplateParameters(), and clang::UsingType::Profile().
isCompatibleWithFields()
static bool isCompatibleWithFields (BindingKey K, const FieldVector & Fields) static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 822 of file RegionStore.cpp.
References getSymbolicOffsetFields().
Referenced by collectSubRegionBindings().
isRecordEmpty()
static bool isRecordEmpty (const RecordDecl * RD) static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 2295 of file RegionStore.cpp.
References clang::RecordDecl::field_empty().
isUnionField()
static bool isUnionField (const FieldRegion * FR) inline static
Examples
/home/runner/work/llvm/llvm/repo/clang/lib/StaticAnalyzer/Core/RegionStore.cpp.
Definition at line 801 of file RegionStore.cpp.
References clang::ento::FieldRegion::getDecl(), clang::FieldDecl::getParent(), and clang::TagDecl::isUnion().
Referenced by getSymbolicOffsetFields().