clang: lib/Tooling/Transformer/RewriteRule.cpp File Reference
RewriteRule.cpp File Reference
#include "clang/Tooling/Transformer/RewriteRule.h"
#include "clang/AST/ASTTypeTraits.h"
#include "clang/AST/Stmt.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/ASTMatchers/ASTMatchers.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Tooling/Transformer/SourceCode.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include <map>
#include <string>
#include <utility>
#include <vector>
Typedefs
using MatchResult = MatchFinder::MatchResult
Functions
static Expected< SmallVector< transformer::Edit, 1 > > translateEdits (const MatchResult &Result, ArrayRef< ASTEdit > ASTEdits)
static TextGenerator makeText (std::string S)
static std::string formatHeaderPath (StringRef Header, IncludeFormat Format)
template<typename T >
llvm::Expected< SmallVector< clang::transformer::Edit, 1 > > rewriteDescendantsImpl (const T &Node, RewriteRule Rule, const MatchResult &Result)
static bool hasValidKind (const DynTypedMatcher &M)
static std::vector< DynTypedMatcher > taggedMatchers (StringRef TagBase, const SmallVectorImpl< std::pair< size_t, RewriteRule::Case >> &Cases, TraversalKind DefaultTraversalKind)
Typedef Documentation
MatchResult
using MatchResult = MatchFinder::MatchResult
Definition at line 31 of file RewriteRule.cpp.
Function Documentation
formatHeaderPath()
static std::string formatHeaderPath (StringRef Header, IncludeFormat Format) static
Definition at line 150 of file RewriteRule.cpp.
References clang::transformer::Angled, and clang::transformer::Quoted.
Referenced by clang::transformer::addInclude().
hasValidKind()
static bool hasValidKind (const DynTypedMatcher & M) static
Definition at line 353 of file RewriteRule.cpp.
Referenced by clang::transformer::detail::buildMatchers().
makeText()
static TextGenerator makeText (std::string S) static
Definition at line 142 of file RewriteRule.cpp.
Referenced by clang::transformer::addInclude().
rewriteDescendantsImpl()
template<typename T > llvm::Expected<SmallVector<clang::transformer::Edit, 1> > rewriteDescendantsImpl (const T & Node, RewriteRule Rule, const MatchResult & Result)
Definition at line 284 of file RewriteRule.cpp.
Referenced by clang::transformer::detail::rewriteDescendants().
taggedMatchers()
static std::vector<DynTypedMatcher> taggedMatchers (StringRef TagBase, const SmallVectorImpl< std::pair< size_t, RewriteRule::Case >> & Cases, TraversalKind DefaultTraversalKind) static
Definition at line 362 of file RewriteRule.cpp.
translateEdits()
static Expected<SmallVector<transformer::Edit, 1> > translateEdits (const MatchResult & Result, ArrayRef< ASTEdit > ASTEdits) static
Definition at line 36 of file RewriteRule.cpp.
References clang::tooling::getRangeForEdit(), clang::transformer::Edit::Kind, clang::transformer::Edit::Metadata, clang::transformer::Range, clang::transformer::Edit::Range, and clang::transformer::Edit::Replacement.
Referenced by clang::transformer::edit(), and clang::transformer::editList().