clang: lib/CodeGen/SanitizerMetadata.cpp File Reference
SanitizerMetadata.cpp File Reference
#include "SanitizerMetadata.h"
#include "CodeGenModule.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Type.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/Constants.h"
Functions
static bool isAsanHwasanOrMemTag (const SanitizerSet &SS)
Function Documentation
isAsanHwasanOrMemTag()
static bool isAsanHwasanOrMemTag (const SanitizerSet & SS) static
Definition at line 25 of file SanitizerMetadata.cpp.
References clang::SanitizerSet::hasOneOf().
Referenced by clang::CodeGen::SanitizerMetadata::disableSanitizerForGlobal(), and clang::CodeGen::SanitizerMetadata::reportGlobalToASan().