clang: lib/Basic/Sarif.cpp File Reference
Sarif.cpp File Reference
This file contains the declaration of the SARIFDocumentWriter class, and associated builders such as:
#include "clang/Basic/Sarif.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/Path.h"
#include <optional>
#include <string>
#include <utility>
Functions
static StringRef getFileName (FileEntryRef FE)
static unsigned int adjustColumnPos (FullSourceLoc Loc, unsigned int TokenLen=0)
Calculate the column position expressed in the number of UTF-8 code points from column start to the source location.
URI
static std::string percentEncodeURICharacter (char C)
static std::string fileNameToURI (StringRef Filename)
SARIF Utilities
json::Object createMessage (StringRef Text)
static json::Object createTextRegion (const SourceManager &SM, const CharSourceRange &R)
static json::Object createLocation (json::Object &&PhysicalLocation, StringRef Message="")
static StringRef importanceToStr (ThreadFlowImportance I)
static StringRef resultLevelToStr (SarifResultLevel R)
static json::Object createThreadFlowLocation (json::Object &&Location, const ThreadFlowImportance &Importance)
Detailed Description
This file contains the declaration of the SARIFDocumentWriter class, and associated builders such as:
SarifArtifact
SarifArtifactLocation
SarifRule
SarifResult
Definition in file Sarif.cpp.
Function Documentation
adjustColumnPos()
static unsigned int adjustColumnPos (FullSourceLoc Loc, unsigned int TokenLen = 0) static
Calculate the column position expressed in the number of UTF-8 code points from column start to the source location.
Parameters
Loc The source location whose column needs to be calculated.
TokenLen Optional hint for when the token is multiple bytes long.
Returns
The column number as a UTF-8 aware byte offset from column start to the effective source location.
Definition at line 117 of file Sarif.cpp.
References clang::SourceManager::getBufferOrNone(), clang::FullSourceLoc::getDecomposedExpansionLoc(), clang::FullSourceLoc::getExpansionColumnNumber(), clang::FullSourceLoc::getManager(), clang::SourceLocation::isInvalid(), and clang::interp::Ret().
Referenced by createTextRegion().
createLocation()
static json::Object createLocation (json::Object && PhysicalLocation, StringRef Message = "") static
Definition at line 166 of file Sarif.cpp.
References createMessage(), and clang::interp::Ret().
Referenced by clang::SarifDocumentWriter::appendResult().
createMessage()
json::Object createMessage (StringRef Text)
Definition at line 144 of file Sarif.cpp.
References Text.
Referenced by clang::SarifDocumentWriter::appendResult(), and createLocation().
createTextRegion()
static json::Object createTextRegion (const SourceManager & SM, const CharSourceRange & R) static
Definition at line 150 of file Sarif.cpp.
References adjustColumnPos(), clang::CharSourceRange::getBegin(), clang::CharSourceRange::getEnd(), and SM.
createThreadFlowLocation()
static json::Object createThreadFlowLocation (json::Object && Location, const ThreadFlowImportance & Importance) static
Definition at line 202 of file Sarif.cpp.
References importanceToStr().
fileNameToURI()
static std::string fileNameToURI (StringRef Filename) static
Definition at line 71 of file Sarif.cpp.
References End, Filename, Iter, percentEncodeURICharacter(), and clang::interp::Ret().
getFileName()
static StringRef getFileName (FileEntryRef FE) static
Definition at line 38 of file Sarif.cpp.
References Filename, clang::FileEntryRef::getFileEntry(), clang::FileEntryRef::getName(), and clang::FileEntry::tryGetRealPathName().
importanceToStr()
static StringRef importanceToStr (ThreadFlowImportance I) static
Definition at line 174 of file Sarif.cpp.
References clang::Essential, clang::Important, and clang::Unimportant.
Referenced by createThreadFlowLocation().
percentEncodeURICharacter()
static std::string percentEncodeURICharacter (char C) static
Definition at line 54 of file Sarif.cpp.
References contains().
Referenced by fileNameToURI().
resultLevelToStr()
static StringRef resultLevelToStr (SarifResultLevel R) static
Definition at line 186 of file Sarif.cpp.
References clang::Error, clang::None, clang::Note, and clang::Warning.
Referenced by clang::SarifDocumentWriter::appendResult(), and clang::SarifDocumentWriter::endRun().