clang: lib/Sema/SemaTemplateInstantiateDecl.cpp File Reference
SemaTemplateInstantiateDecl.cpp File Reference
#include "TreeTransform.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclVisitor.h"
#include "clang/AST/DependentDiagnostic.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/PrettyDeclStackTrace.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaCUDA.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/SemaOpenMP.h"
#include "clang/Sema/Template.h"
#include "clang/Sema/TemplateInstCallback.h"
#include "llvm/Support/TimeProfiler.h"
#include <optional>
#include "clang/Sema/AttrTemplateInstantiate.inc"
Functions
static bool isDeclWithinFunction (const Decl *D)
template<typename DeclT >
static bool SubstQualifier (Sema &SemaRef, const DeclT *OldDecl, DeclT *NewDecl, const MultiLevelTemplateArgumentList &TemplateArgs)
static void instantiateDependentAlignedAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AlignedAttr *Aligned, Decl *New, bool IsPackExpansion)
static void instantiateDependentAlignedAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AlignedAttr *Aligned, Decl *New)
static void instantiateDependentAssumeAlignedAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AssumeAlignedAttr *Aligned, Decl *New)
static void instantiateDependentAlignValueAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AlignValueAttr *Aligned, Decl *New)
static void instantiateDependentAllocAlignAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AllocAlignAttr *Align, Decl *New)
static void instantiateDependentAnnotationAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AnnotateAttr *Attr, Decl *New)
static Expr * instantiateDependentFunctionAttrCondition (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const Attr *A, Expr *OldCond, const Decl *Tmpl, FunctionDecl *New)
static void instantiateDependentEnableIfAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const EnableIfAttr *EIA, const Decl *Tmpl, FunctionDecl *New)
static void instantiateDependentDiagnoseIfAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const DiagnoseIfAttr *DIA, const Decl *Tmpl, FunctionDecl *New)
static void instantiateDependentCUDALaunchBoundsAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const CUDALaunchBoundsAttr &Attr, Decl *New)
static void instantiateDependentModeAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const ModeAttr &Attr, Decl *New)
static void instantiateOMPDeclareSimdDeclAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const OMPDeclareSimdDeclAttr &Attr, Decl *New)
Instantiation of 'declare simd' attribute and its arguments.
static void instantiateOMPDeclareVariantAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const OMPDeclareVariantAttr &Attr, Decl *New)
Instantiation of 'declare variant' attribute and its arguments.
static void instantiateDependentAMDGPUFlatWorkGroupSizeAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AMDGPUFlatWorkGroupSizeAttr &Attr, Decl *New)
static void instantiateDependentAMDGPUWavesPerEUAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AMDGPUWavesPerEUAttr &Attr, Decl *New)
static void instantiateDependentAMDGPUMaxNumWorkGroupsAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const AMDGPUMaxNumWorkGroupsAttr &Attr, Decl *New)
static void instantiateSYCLIntelForcePow2DepthAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelForcePow2DepthAttr *Attr, Decl *New)
static void instantiateSYCLIntelBankWidthAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelBankWidthAttr *Attr, Decl *New)
static void instantiateSYCLIntelNumBanksAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelNumBanksAttr *Attr, Decl *New)
static void instantiateSYCLIntelBankBitsAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelBankBitsAttr *Attr, Decl *New)
static void instantiateSYCLDeviceHasAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLDeviceHasAttr *Attr, Decl *New)
static void instantiateSYCLUsesAspectsAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLUsesAspectsAttr *Attr, Decl *New)
static void instantiateSYCLIntelPipeIOAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelPipeIOAttr *Attr, Decl *New)
static void instantiateSYCLIntelLoopFuseAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelLoopFuseAttr *Attr, Decl *New)
static void instantiateIntelReqdSubGroupSize (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const IntelReqdSubGroupSizeAttr *A, Decl *New)
static void instantiateSYCLIntelNumSimdWorkItemsAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelNumSimdWorkItemsAttr *A, Decl *New)
static void instantiateSYCLIntelSchedulerTargetFmaxMhzAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelSchedulerTargetFmaxMhzAttr *A, Decl *New)
static void instantiateSYCLIntelNoGlobalWorkOffsetAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelNoGlobalWorkOffsetAttr *A, Decl *New)
static void instantiateSYCLIntelMaxGlobalWorkDimAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelMaxGlobalWorkDimAttr *A, Decl *New)
static void instantiateSYCLIntelMinWorkGroupsPerComputeUnitAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelMinWorkGroupsPerComputeUnitAttr *A, Decl *New)
static void instantiateSYCLIntelMaxWorkGroupsPerMultiprocessorAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelMaxWorkGroupsPerMultiprocessorAttr *A, Decl *New)
static void instantiateSYCLIntelMaxConcurrencyAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelMaxConcurrencyAttr *A, Decl *New)
static void instantiateSYCLIntelPrivateCopiesAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelPrivateCopiesAttr *A, Decl *New)
static void instantiateSYCLIntelMaxReplicatesAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelMaxReplicatesAttr *A, Decl *New)
static void instantiateSYCLIntelInitiationIntervalAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelInitiationIntervalAttr *A, Decl *New)
static void instantiateSYCLIntelESimdVectorizeAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelESimdVectorizeAttr *A, Decl *New)
static void instantiateSYCLAddIRAttributesFunctionAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLAddIRAttributesFunctionAttr *A, Decl *New)
static void instantiateSYCLAddIRAttributesKernelParameterAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLAddIRAttributesKernelParameterAttr *A, Decl *New)
static void instantiateSYCLAddIRAttributesGlobalVariableAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLAddIRAttributesGlobalVariableAttr *A, Decl *New)
static void instantiateSYCLAddIRAnnotationsMemberAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLAddIRAnnotationsMemberAttr *A, Decl *New)
static void instantiateSYCLWorkGroupSizeHintAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLWorkGroupSizeHintAttr *A, Decl *New)
static void instantiateSYCLIntelMaxWorkGroupSizeAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLIntelMaxWorkGroupSizeAttr *A, Decl *New)
static void instantiateSYCLReqdWorkGroupSizeAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLReqdWorkGroupSizeAttr *A, Decl *New)
static void instantiateDependentSYCLKernelAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const SYCLKernelAttr &Attr, Decl *New)
static bool isRelevantAttr (Sema &S, const Decl *D, const Attr *A)
Determine whether the attribute A might be relevant to the declaration D.
static void instantiateDependentHLSLParamModifierAttr (Sema &S, const MultiLevelTemplateArgumentList &TemplateArgs, const HLSLParamModifierAttr *Attr, Decl *New)
static Sema::RetainOwnershipKind attrToRetainOwnershipKind (const Attr *A)
template<typename DeclT >
static DeclT * getPreviousDeclForInstantiation (DeclT *D)
Get the previous declaration of a declaration for the purposes of template instantiation.
static QualType adjustFunctionTypeForInstantiation (ASTContext &Context, FunctionDecl *D, TypeSourceInfo *TInfo)
Adjust the given function type for an instantiation of the given declaration, to cope with modifications to the function's type that aren't reflected in the type-source information.
static void collectUnexpandedParameterPacks (Sema &S, TemplateParameterList *Params, SmallVectorImpl< UnexpandedParameterPack > &Unexpanded)
static bool isInstantiationOf (ClassTemplateDecl *Pattern, ClassTemplateDecl *Instance)
static bool isInstantiationOf (FunctionTemplateDecl *Pattern, FunctionTemplateDecl *Instance)
static bool isInstantiationOf (ClassTemplatePartialSpecializationDecl *Pattern, ClassTemplatePartialSpecializationDecl *Instance)
static bool isInstantiationOf (CXXRecordDecl *Pattern, CXXRecordDecl *Instance)
static bool isInstantiationOf (FunctionDecl *Pattern, FunctionDecl *Instance)
static bool isInstantiationOf (EnumDecl *Pattern, EnumDecl *Instance)
static bool isInstantiationOf (UsingShadowDecl *Pattern, UsingShadowDecl *Instance, ASTContext &C)
static bool isInstantiationOf (UsingDecl *Pattern, UsingDecl *Instance, ASTContext &C)
template<typename T >
static bool isInstantiationOfUnresolvedUsingDecl (T *Pattern, Decl *Other, ASTContext &Ctx)
static bool isInstantiationOfStaticDataMember (VarDecl *Pattern, VarDecl *Instance)
static bool isInstantiationOf (ASTContext &Ctx, NamedDecl *D, Decl *Other)
template<typename ForwardIterator >
static NamedDecl * findInstantiationOf (ASTContext &Ctx, NamedDecl *D, ForwardIterator first, ForwardIterator last)
static bool isDependentContextAtLevel (DeclContext *DC, unsigned Level)
Determine whether the given context is dependent on template parameters at level Level or below.
static void processFunctionInstantiation (Sema &S, SourceLocation PointOfInstantiation, FunctionDecl *FD, bool DefinitionRequired, MangleContext &MC)
Function Documentation
adjustFunctionTypeForInstantiation()
static QualType adjustFunctionTypeForInstantiation (ASTContext & Context, FunctionDecl * D, TypeSourceInfo * TInfo) static
Adjust the given function type for an instantiation of the given declaration, to cope with modifications to the function's type that aren't reflected in the type-source information.
Parameters
D The declaration we're instantiating.
TInfo The already-instantiated type.
Definition at line 2591 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::TemplateDeclInstantiator::VisitCXXMethodDecl(), and clang::TemplateDeclInstantiator::VisitFunctionDecl().
attrToRetainOwnershipKind()
static Sema::RetainOwnershipKind attrToRetainOwnershipKind (const Attr * A) static
Definition at line 1048 of file SemaTemplateInstantiateDecl.cpp.
References clang::Sema::CF, clang::Attr::getKind(), clang::Sema::NS, and clang::Sema::OS.
Referenced by clang::Sema::InstantiateAttrs().
collectUnexpandedParameterPacks()
static void collectUnexpandedParameterPacks (Sema & S, TemplateParameterList * Params, SmallVectorImpl< UnexpandedParameterPack > & Unexpanded) static
Definition at line 3653 of file SemaTemplateInstantiateDecl.cpp.
findInstantiationOf()
template<typename ForwardIterator > static NamedDecl* findInstantiationOf (ASTContext & Ctx, NamedDecl * D, ForwardIterator first, ForwardIterator last) static
Definition at line 6648 of file SemaTemplateInstantiateDecl.cpp.
References isInstantiationOf().
getPreviousDeclForInstantiation()
template<typename DeclT > static DeclT* getPreviousDeclForInstantiation (DeclT * D) static
Get the previous declaration of a declaration for the purposes of template instantiation.
If this finds a previous declaration, then the previous declaration of the instantiation of D should be an instantiation of the result of this function.
Definition at line 1403 of file SemaTemplateInstantiateDecl.cpp.
References clang::Decl::getLexicalDeclContext(), and clang::Decl::getPreviousDecl().
Referenced by clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(), and clang::TemplateDeclInstantiator::VisitBaseUsingDecls().
instantiateDependentAlignedAttr() [1/2]
static void instantiateDependentAlignedAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AlignedAttr * Aligned, Decl * New) static
Definition at line 112 of file SemaTemplateInstantiateDecl.cpp.
instantiateDependentAlignedAttr() [2/2]
static void instantiateDependentAlignedAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AlignedAttr * Aligned, Decl * New, bool IsPackExpansion) static
Definition at line 90 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentAlignValueAttr()
static void instantiateDependentAlignValueAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AlignValueAttr * Aligned, Decl * New) static
Definition at line 173 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentAllocAlignAttr()
static void instantiateDependentAllocAlignAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AllocAlignAttr * Align, Decl * New) static
Definition at line 184 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentAMDGPUFlatWorkGroupSizeAttr()
static void instantiateDependentAMDGPUFlatWorkGroupSizeAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AMDGPUFlatWorkGroupSizeAttr & Attr, Decl * New) static
Definition at line 549 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentAMDGPUMaxNumWorkGroupsAttr()
static void instantiateDependentAMDGPUMaxNumWorkGroupsAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AMDGPUMaxNumWorkGroupsAttr & Attr, Decl * New) static
Definition at line 613 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentAMDGPUWavesPerEUAttr()
static void instantiateDependentAMDGPUWavesPerEUAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AMDGPUWavesPerEUAttr & Attr, Decl * New) static
Definition at line 590 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentAnnotationAttr()
static void instantiateDependentAnnotationAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AnnotateAttr * Attr, Decl * New) static
Definition at line 194 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentAssumeAlignedAttr()
static void instantiateDependentAssumeAlignedAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const AssumeAlignedAttr * Aligned, Decl * New) static
Definition at line 150 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentCUDALaunchBoundsAttr()
static void instantiateDependentCUDALaunchBoundsAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const CUDALaunchBoundsAttr & Attr, Decl * New) static
Definition at line 288 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentDiagnoseIfAttr()
static void instantiateDependentDiagnoseIfAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const DiagnoseIfAttr * DIA, const Decl * Tmpl, FunctionDecl * New) static
Definition at line 274 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentEnableIfAttr()
static void instantiateDependentEnableIfAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const EnableIfAttr * EIA, const Decl * Tmpl, FunctionDecl * New) static
Definition at line 263 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentFunctionAttrCondition()
static Expr* instantiateDependentFunctionAttrCondition (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const Attr * A, Expr * OldCond, const Decl * Tmpl, FunctionDecl * New) static
Definition at line 232 of file SemaTemplateInstantiateDecl.cpp.
instantiateDependentHLSLParamModifierAttr()
static void instantiateDependentHLSLParamModifierAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const HLSLParamModifierAttr * Attr, Decl * New) static
Definition at line 1013 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentModeAttr()
static void instantiateDependentModeAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const ModeAttr & Attr, Decl * New) static
Definition at line 320 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateDependentSYCLKernelAttr()
static void instantiateDependentSYCLKernelAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLKernelAttr & Attr, Decl * New) static
Definition at line 960 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateIntelReqdSubGroupSize()
static void instantiateIntelReqdSubGroupSize (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const IntelReqdSubGroupSizeAttr * A, Decl * New) static
Definition at line 730 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateOMPDeclareSimdDeclAttr()
static void instantiateOMPDeclareSimdDeclAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const OMPDeclareSimdDeclAttr & Attr, Decl * New) static
Instantiation of 'declare simd' attribute and its arguments.
Definition at line 328 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateOMPDeclareVariantAttr()
static void instantiateOMPDeclareVariantAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const OMPDeclareVariantAttr & Attr, Decl * New) static
Instantiation of 'declare variant' attribute and its arguments.
Definition at line 411 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLAddIRAnnotationsMemberAttr()
static void instantiateSYCLAddIRAnnotationsMemberAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLAddIRAnnotationsMemberAttr * A, Decl * New) static
Definition at line 888 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLAddIRAttributesFunctionAttr()
static void instantiateSYCLAddIRAttributesFunctionAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLAddIRAttributesFunctionAttr * A, Decl * New) static
Definition at line 852 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLAddIRAttributesGlobalVariableAttr()
static void instantiateSYCLAddIRAttributesGlobalVariableAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLAddIRAttributesGlobalVariableAttr * A, Decl * New) static
Definition at line 876 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLAddIRAttributesKernelParameterAttr()
static void instantiateSYCLAddIRAttributesKernelParameterAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLAddIRAttributesKernelParameterAttr * A, Decl * New) static
Definition at line 864 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLDeviceHasAttr()
static void instantiateSYCLDeviceHasAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLDeviceHasAttr * Attr, Decl * New) static
Definition at line 682 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelBankBitsAttr()
static void instantiateSYCLIntelBankBitsAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelBankBitsAttr * Attr, Decl * New) static
Definition at line 666 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelBankWidthAttr()
static void instantiateSYCLIntelBankWidthAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelBankWidthAttr * Attr, Decl * New) static
Definition at line 646 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelESimdVectorizeAttr()
static void instantiateSYCLIntelESimdVectorizeAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelESimdVectorizeAttr * A, Decl * New) static
Definition at line 842 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelForcePow2DepthAttr()
static void instantiateSYCLIntelForcePow2DepthAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelForcePow2DepthAttr * Attr, Decl * New) static
Definition at line 636 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelInitiationIntervalAttr()
static void instantiateSYCLIntelInitiationIntervalAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelInitiationIntervalAttr * A, Decl * New) static
Definition at line 832 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelLoopFuseAttr()
static void instantiateSYCLIntelLoopFuseAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelLoopFuseAttr * Attr, Decl * New) static
Definition at line 720 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelMaxConcurrencyAttr()
static void instantiateSYCLIntelMaxConcurrencyAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelMaxConcurrencyAttr * A, Decl * New) static
Definition at line 802 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelMaxGlobalWorkDimAttr()
static void instantiateSYCLIntelMaxGlobalWorkDimAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelMaxGlobalWorkDimAttr * A, Decl * New) static
Definition at line 770 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelMaxReplicatesAttr()
static void instantiateSYCLIntelMaxReplicatesAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelMaxReplicatesAttr * A, Decl * New) static
Definition at line 822 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelMaxWorkGroupSizeAttr()
static void instantiateSYCLIntelMaxWorkGroupSizeAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelMaxWorkGroupSizeAttr * A, Decl * New) static
Definition at line 919 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelMaxWorkGroupsPerMultiprocessorAttr()
static void instantiateSYCLIntelMaxWorkGroupsPerMultiprocessorAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelMaxWorkGroupsPerMultiprocessorAttr * A, Decl * New) static
Definition at line 791 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelMinWorkGroupsPerComputeUnitAttr()
static void instantiateSYCLIntelMinWorkGroupsPerComputeUnitAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelMinWorkGroupsPerComputeUnitAttr * A, Decl * New) static
Definition at line 780 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelNoGlobalWorkOffsetAttr()
static void instantiateSYCLIntelNoGlobalWorkOffsetAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelNoGlobalWorkOffsetAttr * A, Decl * New) static
Definition at line 760 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelNumBanksAttr()
static void instantiateSYCLIntelNumBanksAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelNumBanksAttr * Attr, Decl * New) static
Definition at line 656 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelNumSimdWorkItemsAttr()
static void instantiateSYCLIntelNumSimdWorkItemsAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelNumSimdWorkItemsAttr * A, Decl * New) static
Definition at line 740 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelPipeIOAttr()
static void instantiateSYCLIntelPipeIOAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelPipeIOAttr * Attr, Decl * New) static
Definition at line 709 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelPrivateCopiesAttr()
static void instantiateSYCLIntelPrivateCopiesAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelPrivateCopiesAttr * A, Decl * New) static
Definition at line 812 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLIntelSchedulerTargetFmaxMhzAttr()
static void instantiateSYCLIntelSchedulerTargetFmaxMhzAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLIntelSchedulerTargetFmaxMhzAttr * A, Decl * New) static
Definition at line 750 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLReqdWorkGroupSizeAttr()
static void instantiateSYCLReqdWorkGroupSizeAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLReqdWorkGroupSizeAttr * A, Decl * New) static
Definition at line 938 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLUsesAspectsAttr()
static void instantiateSYCLUsesAspectsAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLUsesAspectsAttr * Attr, Decl * New) static
Definition at line 694 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
instantiateSYCLWorkGroupSizeHintAttr()
static void instantiateSYCLWorkGroupSizeHintAttr (Sema & S, const MultiLevelTemplateArgumentList & TemplateArgs, const SYCLWorkGroupSizeHintAttr * A, Decl * New) static
Definition at line 900 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs().
isDeclWithinFunction()
static bool isDeclWithinFunction (const Decl * D) static
Definition at line 40 of file SemaTemplateInstantiateDecl.cpp.
References clang::Decl::getDeclContext(), clang::DeclContext::isFunctionOrMethod(), and clang::DeclContext::isRecord().
isDependentContextAtLevel()
static bool isDependentContextAtLevel (DeclContext * DC, unsigned Level) static
Determine whether the given context is dependent on template parameters at level Level or below.
Sometimes we only substitute an inner set of template arguments and leave the outer templates alone. In such cases, contexts dependent only on the outer levels are not effectively dependent.
Definition at line 6677 of file SemaTemplateInstantiateDecl.cpp.
References clang::DeclContext::isDependentContext().
Referenced by clang::Sema::FindInstantiatedDecl().
isInstantiationOf() [1/9]
static bool isInstantiationOf (ASTContext & Ctx, NamedDecl * D, Decl * Other) static
Definition at line 6595 of file SemaTemplateInstantiateDecl.cpp.
References clang::declaresSameEntity(), clang::Function, clang::NamedDecl::getDeclName(), clang::ASTContext::getInstantiatedFromUnnamedFieldDecl(), clang::Decl::getKind(), isInstantiationOf(), isInstantiationOfStaticDataMember(), isInstantiationOfUnresolvedUsingDecl(), clang::VarDecl::isStaticDataMember(), and clang::Other.
isInstantiationOf() [2/9]
static bool isInstantiationOf (ClassTemplateDecl * Pattern, ClassTemplateDecl * Instance) static
Definition at line 6458 of file SemaTemplateInstantiateDecl.cpp.
References clang::ClassTemplateDecl::getCanonicalDecl().
Referenced by clang::Sema::FindInstantiatedDecl(), findInstantiationOf(), and isInstantiationOf().
isInstantiationOf() [3/9]
static bool isInstantiationOf (ClassTemplatePartialSpecializationDecl * Pattern, ClassTemplatePartialSpecializationDecl * Instance) static
Definition at line 6485 of file SemaTemplateInstantiateDecl.cpp.
References clang::CXXRecordDecl::getCanonicalDecl().
isInstantiationOf() [4/9]
static bool isInstantiationOf (CXXRecordDecl * Pattern, CXXRecordDecl * Instance) static
Definition at line 6500 of file SemaTemplateInstantiateDecl.cpp.
References clang::CXXRecordDecl::getCanonicalDecl().
isInstantiationOf() [5/9]
static bool isInstantiationOf (EnumDecl * Pattern, EnumDecl * Instance) static
Definition at line 6526 of file SemaTemplateInstantiateDecl.cpp.
References clang::EnumDecl::getCanonicalDecl().
isInstantiationOf() [6/9]
static bool isInstantiationOf (FunctionDecl * Pattern, FunctionDecl * Instance) static
Definition at line 6513 of file SemaTemplateInstantiateDecl.cpp.
References clang::FunctionDecl::getCanonicalDecl().
isInstantiationOf() [7/9]
static bool isInstantiationOf (FunctionTemplateDecl * Pattern, FunctionTemplateDecl * Instance) static
Definition at line 6471 of file SemaTemplateInstantiateDecl.cpp.
References clang::FunctionTemplateDecl::getCanonicalDecl().
isInstantiationOf() [8/9]
static bool isInstantiationOf (UsingDecl * Pattern, UsingDecl * Instance, ASTContext & C) static
Definition at line 6546 of file SemaTemplateInstantiateDecl.cpp.
References clang::declaresSameEntity().
isInstantiationOf() [9/9]
static bool isInstantiationOf (UsingShadowDecl * Pattern, UsingShadowDecl * Instance, ASTContext & C) static
Definition at line 6539 of file SemaTemplateInstantiateDecl.cpp.
References clang::declaresSameEntity().
isInstantiationOfStaticDataMember()
static bool isInstantiationOfStaticDataMember (VarDecl * Pattern, VarDecl * Instance) static
Definition at line 6578 of file SemaTemplateInstantiateDecl.cpp.
References clang::VarDecl::getCanonicalDecl().
Referenced by isInstantiationOf().
isInstantiationOfUnresolvedUsingDecl()
template<typename T > static bool isInstantiationOfUnresolvedUsingDecl (T * Pattern, Decl * Other, ASTContext & Ctx) static
Definition at line 6552 of file SemaTemplateInstantiateDecl.cpp.
References clang::declaresSameEntity(), clang::ASTContext::getInstantiatedFromUsingDecl(), and clang::Other.
Referenced by isInstantiationOf().
isRelevantAttr()
static bool isRelevantAttr (Sema & S, const Decl * D, const Attr * A) static
Determine whether the attribute A might be relevant to the declaration D.
If not, we can skip instantiating it. The attribute may or may not have been instantiated yet.
Definition at line 969 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::InstantiateAttrs(), and clang::Sema::InstantiateAttrsForDecl().
processFunctionInstantiation()
static void processFunctionInstantiation (Sema & S, SourceLocation PointOfInstantiation, FunctionDecl * FD, bool DefinitionRequired, MangleContext & MC) static
Definition at line 7010 of file SemaTemplateInstantiateDecl.cpp.
Referenced by clang::Sema::PerformPendingInstantiations().
SubstQualifier()
template<typename DeclT > static bool SubstQualifier (Sema & SemaRef, const DeclT * OldDecl, DeclT * NewDecl, const MultiLevelTemplateArgumentList & TemplateArgs) static
Definition at line 52 of file SemaTemplateInstantiateDecl.cpp.
References clang::Sema::SubstNestedNameSpecifierLoc().
Referenced by clang::TemplateDeclInstantiator::SubstQualifier().