clang: lib/Sema/SemaAPINotes.cpp File Reference
SemaAPINotes.cpp File Reference
#include "clang/APINotes/APINotesReader.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclObjC.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Lex/Lexer.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Basic/AttrList.inc"
Macros
#define ATTR(X)
Functions
static bool isIndirectPointerType (QualType Type)
Determine whether this is a multi-level pointer type.
static void applyNullability (Sema &S, Decl *D, NullabilityKind Nullability, VersionedInfoMetadata Metadata)
Apply nullability to the given declaration.
static StringRef ASTAllocateString (ASTContext &Ctx, StringRef String)
Copy a string into ASTContext-allocated memory.
static AttributeCommonInfo getPlaceholderAttrInfo ()
template<typename A >
static void handleAPINotedRetainCountAttribute (Sema &S, Decl *D, bool ShouldAddAttribute, VersionedInfoMetadata Metadata)
static void handleAPINotedRetainCountConvention (Sema &S, Decl *D, VersionedInfoMetadata Metadata, std::optional< api_notes::RetainCountConventionKind > Convention)
static void ProcessAPINotes (Sema &S, Decl *D, const api_notes::CommonEntityInfo &Info, VersionedInfoMetadata Metadata)
static void ProcessAPINotes (Sema &S, Decl *D, const api_notes::CommonTypeInfo &Info, VersionedInfoMetadata Metadata)
static bool checkAPINotesReplacementType (Sema &S, SourceLocation Loc, QualType OrigType, QualType ReplacementType)
Check that the replacement type provided by API notes is reasonable.
static void ProcessAPINotes (Sema &S, Decl *D, const api_notes::VariableInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for a variable or property.
static void ProcessAPINotes (Sema &S, ParmVarDecl *D, const api_notes::ParamInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for a parameter.
static void ProcessAPINotes (Sema &S, VarDecl *D, const api_notes::GlobalVariableInfo &Info, VersionedInfoMetadata metadata)
Process API notes for a global variable.
static void ProcessAPINotes (Sema &S, ObjCPropertyDecl *D, const api_notes::ObjCPropertyInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for an Objective-C property.
static void ProcessAPINotes (Sema &S, FunctionOrMethod AnyFunc, const api_notes::FunctionInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for a function or method.
static void ProcessAPINotes (Sema &S, FunctionDecl *D, const api_notes::GlobalFunctionInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for a global function.
static void ProcessAPINotes (Sema &S, EnumConstantDecl *D, const api_notes::EnumConstantInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for an enumerator.
static void ProcessAPINotes (Sema &S, ObjCMethodDecl *D, const api_notes::ObjCMethodInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for an Objective-C method.
static void ProcessAPINotes (Sema &S, TagDecl *D, const api_notes::TagInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for a tag.
static void ProcessAPINotes (Sema &S, TypedefNameDecl *D, const api_notes::TypedefInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for a typedef.
static void ProcessAPINotes (Sema &S, ObjCContainerDecl *D, const api_notes::ObjCContextInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for an Objective-C class or protocol.
static void ProcessAPINotes (Sema &S, ObjCInterfaceDecl *D, const api_notes::ObjCContextInfo &Info, VersionedInfoMetadata Metadata)
Process API notes for an Objective-C class.
template<typename SpecificInfo >
static void maybeAttachUnversionedSwiftName (Sema &S, Decl *D, const api_notes::APINotesReader::VersionedInfo< SpecificInfo > Info)
If we're applying API notes with an active, non-default version, and the versioned API notes have a SwiftName but the declaration normally wouldn't have one, add a removal attribute to make it clear that the new SwiftName attribute only applies to the active version of D, not to all versions.
template<typename SpecificDecl , typename SpecificInfo >
static void ProcessVersionedAPINotes (Sema &S, SpecificDecl *D, const api_notes::APINotesReader::VersionedInfo< SpecificInfo > Info)
Processes all versions of versioned API notes.
Macro Definition Documentation
ATTR
#define ATTR (X)
Value:
  template <> struct AttrKindFor<X##Attr> {                                    \
    static const attr::Kind value = attr::X;                                   \
  };
Definition at line 127 of file SemaAPINotes.cpp.
Function Documentation
applyNullability()
static void applyNullability (Sema & S, Decl * D, NullabilityKind Nullability, VersionedInfoMetadata Metadata) static
Apply nullability to the given declaration.
Definition at line 50 of file SemaAPINotes.cpp.
ASTAllocateString()
static StringRef ASTAllocateString (ASTContext & Ctx, StringRef String) static
Copy a string into ASTContext-allocated memory.
Definition at line 110 of file SemaAPINotes.cpp.
References clang::ASTContext::Allocate(), and memcpy().
checkAPINotesReplacementType()
static bool checkAPINotesReplacementType (Sema & S, SourceLocation Loc, QualType OrigType, QualType ReplacementType) static
Check that the replacement type provided by API notes is reasonable.
This is a very weak form of ABI check.
Definition at line 345 of file SemaAPINotes.cpp.
getPlaceholderAttrInfo()
static AttributeCommonInfo getPlaceholderAttrInfo () static
Definition at line 116 of file SemaAPINotes.cpp.
References clang::AttributeCommonInfo::AS_GNU, and clang::AttributeCommonInfo::UnknownAttribute.
handleAPINotedRetainCountAttribute()
template<typename A > static void handleAPINotedRetainCountAttribute (Sema & S, Decl * D, bool ShouldAddAttribute, VersionedInfoMetadata Metadata) static
Definition at line 194 of file SemaAPINotes.cpp.
handleAPINotedRetainCountConvention()
static void handleAPINotedRetainCountConvention (Sema & S, Decl * D, VersionedInfoMetadata Metadata, std::optional< api_notes::RetainCountConventionKind > Convention) static
Definition at line 213 of file SemaAPINotes.cpp.
isIndirectPointerType()
static bool isIndirectPointerType (QualType Type) static
Determine whether this is a multi-level pointer type.
Definition at line 40 of file SemaAPINotes.cpp.
References clang::Type::getPointeeType(), clang::Type::isAnyPointerType(), clang::Type::isMemberPointerType(), clang::QualType::isNull(), and clang::Type::isObjCObjectPointerType().
maybeAttachUnversionedSwiftName()
template<typename SpecificInfo > static void maybeAttachUnversionedSwiftName (Sema & S, Decl * D, const api_notes::APINotesReader::VersionedInfo< SpecificInfo > Info) static
If we're applying API notes with an active, non-default version, and the versioned API notes have a SwiftName but the declaration normally wouldn't have one, add a removal attribute to make it clear that the new SwiftName attribute only applies to the active version of D, not to all versions.
This must be run before processing API notes for D, because otherwise any existing SwiftName attribute will have been packaged up in a SwiftVersionedAdditionAttr.
Definition at line 709 of file SemaAPINotes.cpp.
ProcessAPINotes() [1/14]
static void ProcessAPINotes (Sema & S, Decl * D, const api_notes::CommonEntityInfo & Info, VersionedInfoMetadata Metadata) static
Definition at line 247 of file SemaAPINotes.cpp.
ProcessAPINotes() [2/14]
static void ProcessAPINotes (Sema & S, Decl * D, const api_notes::CommonTypeInfo & Info, VersionedInfoMetadata Metadata) static
Definition at line 315 of file SemaAPINotes.cpp.
ProcessAPINotes() [3/14]
static void ProcessAPINotes (Sema & S, Decl * D, const api_notes::VariableInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for a variable or property.
Definition at line 359 of file SemaAPINotes.cpp.
ProcessAPINotes() [4/14]
static void ProcessAPINotes (Sema & S, EnumConstantDecl * D, const api_notes::EnumConstantInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for an enumerator.
Definition at line 555 of file SemaAPINotes.cpp.
ProcessAPINotes() [5/14]
static void ProcessAPINotes (Sema & S, FunctionDecl * D, const api_notes::GlobalFunctionInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for a global function.
Definition at line 546 of file SemaAPINotes.cpp.
ProcessAPINotes() [6/14]
static void ProcessAPINotes (Sema & S, FunctionOrMethod AnyFunc, const api_notes::FunctionInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for a function or method.
Definition at line 454 of file SemaAPINotes.cpp.
ProcessAPINotes() [7/14]
static void ProcessAPINotes (Sema & S, ObjCContainerDecl * D, const api_notes::ObjCContextInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for an Objective-C class or protocol.
Definition at line 667 of file SemaAPINotes.cpp.
ProcessAPINotes() [8/14]
static void ProcessAPINotes (Sema & S, ObjCInterfaceDecl * D, const api_notes::ObjCContextInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for an Objective-C class.
Definition at line 676 of file SemaAPINotes.cpp.
ProcessAPINotes() [9/14]
static void ProcessAPINotes (Sema & S, ObjCMethodDecl * D, const api_notes::ObjCMethodInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for an Objective-C method.
Definition at line 564 of file SemaAPINotes.cpp.
ProcessAPINotes() [10/14]
static void ProcessAPINotes (Sema & S, ObjCPropertyDecl * D, const api_notes::ObjCPropertyInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for an Objective-C property.
Definition at line 433 of file SemaAPINotes.cpp.
ProcessAPINotes() [11/14]
static void ProcessAPINotes (Sema & S, ParmVarDecl * D, const api_notes::ParamInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for a parameter.
Definition at line 405 of file SemaAPINotes.cpp.
ProcessAPINotes() [12/14]
static void ProcessAPINotes (Sema & S, TagDecl * D, const api_notes::TagInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for a tag.
Definition at line 585 of file SemaAPINotes.cpp.
ProcessAPINotes() [13/14]
static void ProcessAPINotes (Sema & S, TypedefNameDecl * D, const api_notes::TypedefInfo & Info, VersionedInfoMetadata Metadata) static
Process API notes for a typedef.
Definition at line 630 of file SemaAPINotes.cpp.
ProcessAPINotes() [14/14]
static void ProcessAPINotes (Sema & S, VarDecl * D, const api_notes::GlobalVariableInfo & Info, VersionedInfoMetadata metadata) static
Process API notes for a global variable.
Definition at line 424 of file SemaAPINotes.cpp.
ProcessVersionedAPINotes()
template<typename SpecificDecl , typename SpecificInfo > static void ProcessVersionedAPINotes (Sema & S, SpecificDecl * D, const api_notes::APINotesReader::VersionedInfo< SpecificInfo > Info) static
Processes all versions of versioned API notes.
Just dispatches to the various ProcessAPINotes functions in this file.
Definition at line 747 of file SemaAPINotes.cpp.