clang: lib/Sema/SemaSYCL.cpp File Reference
SemaSYCL.cpp File Reference
#include "clang/Sema/SemaSYCL.h"
#include "TreeTransform.h"
#include "clang/AST/AST.h"
#include "clang/AST/Mangle.h"
#include "clang/AST/QualTypeNames.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/TemplateArgumentVisitor.h"
#include "clang/AST/TypeVisitor.h"
#include "clang/Analysis/CallGraph.h"
#include "clang/Basic/Attributes.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/Version.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Sema.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <array>
#include <functional>
#include <initializer_list>
Classes
class DiagDeviceFunction
class DeviceFunctionTracker
class SingleDeviceFunctionTracker
class KernelBodyTransform
class MarkWIScopeFnVisitor
class SYCLKernelNameTypeVisitor
class SYCLFwdDeclEmitter
class SYCLKernelNameTypePrinter
Macros
#define KF_FOR_EACH(FUNC, Item, Qt)
#define CASE(x)
Typedefs
using KernelParamKind = SYCLIntegrationHeader::kernel_param_kind_t
using ParamDesc = std::tuple< QualType, IdentifierInfo *, TypeSourceInfo * >
Enumerations
enum target {
global_buffer = 2014 , constant_buffer , local , image ,
host_buffer , host_image , image_array
}
enum KernelInvocationKind { InvokeUnknown , InvokeSingleTask , InvokeParallelFor , InvokeParallelForWorkGroup }
Functions
static bool isSyclAccessorType (QualType Ty)
static bool isAccessorPropertyType (QualType Ty, SYCLTypeAttr::SYCLType TypeName)
static bool isSyclSpecialType (QualType Ty, SemaSYCL &S)
static bool IsSyclMathFunc (unsigned BuiltinID)
static bool isZeroSizedArray (SemaSYCL &S, QualType Ty)
static void checkSYCLType (SemaSYCL &S, QualType Ty, SourceRange Loc, llvm::DenseSet< QualType > Visited, SourceRange UsedAtLoc=SourceRange())
static bool isSYCLKernelBodyFunction (FunctionDecl *FD)
static bool isSYCLUndefinedAllowed (const FunctionDecl *Callee, const SourceManager &SrcMgr)
static void reportConflictingAttrs (SemaSYCL &S, FunctionDecl *F, const Attr *A1, const Attr *A2)
static int64_t getIntExprValue (const Expr *E, ASTContext &Ctx)
Returns the signed constant integer value represented by given expression.
static void collectSYCLAttributes (SemaSYCL &S, FunctionDecl *FD, llvm::SmallVectorImpl< Attr * > &Attrs, bool DirectlyCalled)
static bool isDeclaredInSYCLNamespace (const Decl *D)
This function checks whether given DeclContext contains a topmost namespace with name "sycl".
static bool isSYCLPrivateMemoryVar (VarDecl *VD)
static void addScopeAttrToLocalVars (CXXMethodDecl &F)
static CXXMethodDecl * getMethodByName (const CXXRecordDecl *CRD, StringRef MethodName)
Return method by name.
static KernelInvocationKind getKernelInvocationKind (FunctionDecl *KernelCallerFunc)
static QualType GetSYCLKernelObjectType (const FunctionDecl *KernelCaller)
static ParamDesc makeParamDesc (const FieldDecl *Src, QualType Ty)
Creates a kernel parameter descriptor.
static ParamDesc makeParamDesc (ASTContext &Ctx, StringRef Name, QualType Ty)
static target getAccessTarget (QualType FieldTy, const ClassTemplateSpecializationDecl *AccTy)
static QualType calculateKernelNameType (ASTContext &Ctx, const FunctionDecl *KernelCallerFunc)
static std::pair< std::string, std::string > constructKernelName (SemaSYCL &S, const FunctionDecl *KernelCallerFunc, MangleContext &MC)
static bool isDefaultSPIRArch (ASTContext &Context)
static ParmVarDecl * getSyclKernelHandlerArg (FunctionDecl *KernelCallerFunc)
static bool isReadOnlyAccessor (const TemplateArgument &AccessModeArg)
static std::pair< LangOptions::SubGroupSizeType, int64_t > CalcEffectiveSubGroup (ASTContext &Ctx, const LangOptions &LO, const FunctionDecl *FD)
static SourceLocation GetSubGroupLoc (const FunctionDecl *FD)
static void CheckSYCL2020SubGroupSizes (SemaSYCL &S, FunctionDecl *SYCLKernel, const FunctionDecl *FD)
static void CheckSYCL2020Attributes (SemaSYCL &S, FunctionDecl *SYCLKernel, FunctionDecl *KernelBody, const llvm::SmallPtrSetImpl< FunctionDecl * > &CalledFuncs)
static void PropagateAndDiagnoseDeviceAttr (SemaSYCL &S, const SingleDeviceFunctionTracker &Tracker, Attr *A, FunctionDecl *SYCLKernel, FunctionDecl *KernelBody)
static const char * paramKind2Str (KernelParamKind K)
Returns a string ID of given parameter kind - used in header emission.
static void OutputStableNameChar (raw_ostream &O, char C)
static void OutputStableNameInChars (raw_ostream &O, StringRef Name)
template<typename BeforeFn , typename AfterFn >
static void PrintNSHelper (BeforeFn Before, AfterFn After, raw_ostream &OS, const DeclContext *DC)
static void PrintNamespaces (raw_ostream &OS, const DeclContext *DC)
static void PrintNSClosingBraces (raw_ostream &OS, const DeclContext *DC)
static std::string EmitShim (raw_ostream &OS, unsigned &ShimCounter, const std::string &LastShim, const NamespaceDecl *AnonNS)
static void EmitShims (raw_ostream &OS, unsigned &ShimCounter, const DeclContext *DC, std::string &NameForLastShim, PrintingPolicy &Policy)
static std::string EmitShims (raw_ostream &OS, unsigned &ShimCounter, PrintingPolicy &Policy, const VarDecl *VD)
Variables
static constexpr llvm::StringLiteral InitMethodName = "__init"
static constexpr llvm::StringLiteral InitESIMDMethodName = "__init_esimd"
static constexpr llvm::StringLiteral InitSpecConstantsBuffer
static constexpr llvm::StringLiteral FinalizeMethodName = "__finalize"
static constexpr llvm::StringLiteral LibstdcxxFailedAssertion
constexpr unsigned MaxKernelArgsSize = 2048
Macro Definition Documentation
CASE
#define CASE (x)
Value:
  case SYCLIntegrationHeader::kind_##x:                                        \
    return "kind_" #x
KF_FOR_EACH
#define KF_FOR_EACH (FUNC, Item, Qt)
Value:
  handleField(                                                                 \
      Item, Qt,                                                                \
      std::bind(static_cast<bool (std::decay_t<decltype(Handlers)>::*)(        \
                    bind_param_t<decltype(Item)>, QualType)>(                  \
                    &std::decay_t<decltype(Handlers)>::FUNC),                  \
                std::ref(Handlers), _1, _2)...)
Definition at line 1190 of file SemaSYCL.cpp.
Typedef Documentation
KernelParamKind
using KernelParamKind = SYCLIntegrationHeader::kernel_param_kind_t
Definition at line 43 of file SemaSYCL.cpp.
ParamDesc
using ParamDesc = std::tuple<QualType, IdentifierInfo *, TypeSourceInfo *>
Definition at line 55 of file SemaSYCL.cpp.
Enumeration Type Documentation
KernelInvocationKind
enum KernelInvocationKind
Enumerator
InvokeUnknown
InvokeSingleTask
InvokeParallelFor
InvokeParallelForWorkGroup
Definition at line 57 of file SemaSYCL.cpp.
target
enum target
Enumerator
global_buffer
constant_buffer
local
image
host_buffer
host_image
image_array
Definition at line 45 of file SemaSYCL.cpp.
Function Documentation
addScopeAttrToLocalVars()
static void addScopeAttrToLocalVars (CXXMethodDecl & F) static
Definition at line 984 of file SemaSYCL.cpp.
References clang::Decl::addAttr(), clang::DeclContext::decls(), clang::Decl::getASTContext(), clang::VarDecl::getStorageDuration(), isSYCLPrivateMemoryVar(), and clang::SD_Automatic.
CalcEffectiveSubGroup()
static std::pair<LangOptions::SubGroupSizeType, int64_t> CalcEffectiveSubGroup (ASTContext & Ctx, const LangOptions & LO, const FunctionDecl * FD) static
Definition at line 4329 of file SemaSYCL.cpp.
References clang::LangOptionsBase::Auto, clang::Decl::getAttr(), getIntExprValue(), clang::LangOptionsBase::Integer, and clang::LangOptionsBase::Primary.
calculateKernelNameType()
static QualType calculateKernelNameType (ASTContext & Ctx, const FunctionDecl * KernelCallerFunc) static
Definition at line 1069 of file SemaSYCL.cpp.
References clang::TemplateArgumentList::get(), clang::TemplateArgument::getAsType(), clang::QualType::getCanonicalType(), and clang::FunctionDecl::getTemplateSpecializationArgs().
Referenced by clang::SemaSYCL::CheckSYCLKernelCall(), and clang::SemaSYCL::ConstructOpenCLKernel().
CheckSYCL2020Attributes()
static void CheckSYCL2020Attributes (SemaSYCL & S, FunctionDecl * SYCLKernel, FunctionDecl * KernelBody, const llvm::SmallPtrSetImpl< FunctionDecl * > & CalledFuncs) static
Definition at line 4407 of file SemaSYCL.cpp.
Referenced by clang::SemaSYCL::MarkDevices().
CheckSYCL2020SubGroupSizes()
static void CheckSYCL2020SubGroupSizes (SemaSYCL & S, FunctionDecl * SYCLKernel, const FunctionDecl * FD) static
Definition at line 4355 of file SemaSYCL.cpp.
checkSYCLType()
static void checkSYCLType (SemaSYCL & S, QualType Ty, SourceRange Loc, llvm::DenseSet< QualType > Visited, SourceRange UsedAtLoc = SourceRange()) static
Definition at line 410 of file SemaSYCL.cpp.
Referenced by clang::SemaSYCL::checkSYCLDeviceVarDecl().
collectSYCLAttributes()
static void collectSYCLAttributes (SemaSYCL & S, FunctionDecl * FD, llvm::SmallVectorImpl< Attr * > & Attrs, bool DirectlyCalled) static
Definition at line 532 of file SemaSYCL.cpp.
Referenced by clang::SemaSYCL::copySYCLKernelAttrs().
constructKernelName()
static std::pair<std::string, std::string> constructKernelName (SemaSYCL & S, const FunctionDecl * KernelCallerFunc, MangleContext & MC) static
Definition at line 1080 of file SemaSYCL.cpp.
Referenced by clang::SemaSYCL::ConstructOpenCLKernel(), and clang::SemaSYCL::SetSYCLKernelNames().
EmitShim()
static std::string EmitShim (raw_ostream & OS, unsigned & ShimCounter, const std::string & LastShim, const NamespaceDecl * AnonNS) static
Definition at line 5599 of file SemaSYCL.cpp.
References clang::Decl::castToDeclContext(), PrintNamespaces(), and PrintNSClosingBraces().
Referenced by EmitShims().
EmitShims() [1/2]
static void EmitShims (raw_ostream & OS, unsigned & ShimCounter, const DeclContext * DC, std::string & NameForLastShim, PrintingPolicy & Policy) static
Definition at line 5619 of file SemaSYCL.cpp.
References EmitShim(), clang::NamedDecl::getNameAsString(), and clang::DeclContext::isTranslationUnit().
Referenced by EmitShims().
EmitShims() [2/2]
static std::string EmitShims (raw_ostream & OS, unsigned & ShimCounter, PrintingPolicy & Policy, const VarDecl * VD) static
Definition at line 5662 of file SemaSYCL.cpp.
References EmitShims(), clang::Decl::getDeclContext(), clang::NamedDecl::getNameForDiagnostic(), and clang::Decl::isInAnonymousNamespace().
getAccessTarget()
static target getAccessTarget (QualType FieldTy, const ClassTemplateSpecializationDecl * AccTy) static
Returns
the target of given SYCL accessor type
Definition at line 1058 of file SemaSYCL.cpp.
References clang::ClassTemplateSpecializationDecl::getTemplateArgs(), clang::SemaSYCL::isSyclType(), and local.
getIntExprValue()
static int64_t getIntExprValue (const Expr * E, ASTContext & Ctx) static
Returns the signed constant integer value represented by given expression.
Definition at line 527 of file SemaSYCL.cpp.
References clang::Expr::getIntegerConstantExpr().
Referenced by CalcEffectiveSubGroup().
getKernelInvocationKind()
static KernelInvocationKind getKernelInvocationKind (FunctionDecl * KernelCallerFunc) static
Definition at line 1017 of file SemaSYCL.cpp.
References clang::NamedDecl::getName(), InvokeParallelFor, InvokeParallelForWorkGroup, InvokeSingleTask, and InvokeUnknown.
getMethodByName()
static CXXMethodDecl* getMethodByName (const CXXRecordDecl * CRD, StringRef MethodName) static
Return method by name.
Definition at line 1005 of file SemaSYCL.cpp.
References clang::CXXRecordDecl::methods().
GetSubGroupLoc()
static SourceLocation GetSubGroupLoc (const FunctionDecl * FD) static
Definition at line 4347 of file SemaSYCL.cpp.
References clang::Decl::getAttr().
getSyclKernelHandlerArg()
static ParmVarDecl* getSyclKernelHandlerArg (FunctionDecl * KernelCallerFunc) static
Definition at line 1118 of file SemaSYCL.cpp.
References clang::SemaSYCL::isSyclType(), clang::FunctionDecl::param_end(), and clang::FunctionDecl::parameters().
Referenced by clang::SemaSYCL::ConstructOpenCLKernel().
GetSYCLKernelObjectType()
static QualType GetSYCLKernelObjectType (const FunctionDecl * KernelCaller) static
Definition at line 1029 of file SemaSYCL.cpp.
References clang::FunctionDecl::getNumParams(), clang::FunctionDecl::getParamDecl(), clang::Type::getPointeeType(), clang::ValueDecl::getType(), clang::QualType::getUnqualifiedType(), and clang::Type::isReferenceType().
Referenced by clang::SemaSYCL::CheckSYCLKernelCall(), and clang::SemaSYCL::ConstructOpenCLKernel().
isAccessorPropertyType()
static bool isAccessorPropertyType (QualType Ty, SYCLTypeAttr::SYCLType TypeName) static
Definition at line 99 of file SemaSYCL.cpp.
References clang::Type::getAsCXXRecordDecl(), Parent, and clang::TypeName.
isDeclaredInSYCLNamespace()
static bool isDeclaredInSYCLNamespace (const Decl * D) static
This function checks whether given DeclContext contains a topmost namespace with name "sycl".
Definition at line 743 of file SemaSYCL.cpp.
References clang::Decl::getDeclContext(), clang::DeclContext::getEnclosingNamespaceContext(), and Parent.
isDefaultSPIRArch()
static bool isDefaultSPIRArch (ASTContext & Context) static
Definition at line 1111 of file SemaSYCL.cpp.
isReadOnlyAccessor()
static bool isReadOnlyAccessor (const TemplateArgument & AccessModeArg) static
Definition at line 1133 of file SemaSYCL.cpp.
References clang::Type::castAs(), clang::TemplateArgument::getAsIntegral(), and clang::TemplateArgument::getIntegralType().
isSyclAccessorType()
static bool isSyclAccessorType (QualType Ty) static
Definition at line 90 of file SemaSYCL.cpp.
References clang::SemaSYCL::isSyclType().
isSYCLKernelBodyFunction()
static bool isSYCLKernelBodyFunction (FunctionDecl * FD) static
Definition at line 492 of file SemaSYCL.cpp.
References clang::FunctionDecl::getOverloadedOperator().
Referenced by clang::SemaSYCL::copySYCLKernelAttrs().
IsSyclMathFunc()
static bool IsSyclMathFunc (unsigned BuiltinID) static
Definition at line 320 of file SemaSYCL.cpp.
Referenced by DiagDeviceFunction::VisitCallExpr().
isSYCLPrivateMemoryVar()
static bool isSYCLPrivateMemoryVar (VarDecl * VD) static
Definition at line 980 of file SemaSYCL.cpp.
References clang::ValueDecl::getType(), and clang::SemaSYCL::isSyclType().
Referenced by addScopeAttrToLocalVars().
isSyclSpecialType()
static bool isSyclSpecialType (QualType Ty, SemaSYCL & S) static
Definition at line 109 of file SemaSYCL.cpp.
isSYCLUndefinedAllowed()
static bool isSYCLUndefinedAllowed (const FunctionDecl * Callee, const SourceManager & SrcMgr) static
Definition at line 496 of file SemaSYCL.cpp.
References clang::SourceManager::isInSystemHeader(), and LibstdcxxFailedAssertion.
Referenced by clang::SemaSYCL::finalizeSYCLDelayedAnalysis().
isZeroSizedArray()
static bool isZeroSizedArray (SemaSYCL & S, QualType Ty) static
Definition at line 404 of file SemaSYCL.cpp.
Referenced by clang::SemaSYCL::deepTypeCheckForDevice().
makeParamDesc() [1/2]
static ParamDesc makeParamDesc (ASTContext & Ctx, StringRef Name, QualType Ty) static
Definition at line 1052 of file SemaSYCL.cpp.
makeParamDesc() [2/2]
static ParamDesc makeParamDesc (const FieldDecl * Src, QualType Ty) static
Creates a kernel parameter descriptor.
Parameters
Src field declaration to construct name from
Ty the desired parameter type
Returns
the constructed descriptor
Definition at line 1045 of file SemaSYCL.cpp.
References clang::Decl::getASTContext().
OutputStableNameChar()
static void OutputStableNameChar (raw_ostream & O, char C) static
Definition at line 5164 of file SemaSYCL.cpp.
OutputStableNameInChars()
static void OutputStableNameInChars (raw_ostream & O, StringRef Name) static
Definition at line 5173 of file SemaSYCL.cpp.
Referenced by clang::SYCLIntegrationHeader::emit().
paramKind2Str()
static const char* paramKind2Str (KernelParamKind K) static
Returns a string ID of given parameter kind - used in header emission.
Definition at line 4785 of file SemaSYCL.cpp.
References CASE.
Referenced by clang::SYCLIntegrationHeader::emit().
PrintNamespaces()
static void PrintNamespaces (raw_ostream & OS, const DeclContext * DC) static
Definition at line 5570 of file SemaSYCL.cpp.
References clang::NamedDecl::getName(), clang::NamespaceDecl::isAnonymousNamespace(), clang::NamespaceDecl::isInline(), and PrintNSHelper().
Referenced by EmitShim().
PrintNSClosingBraces()
static void PrintNSClosingBraces (raw_ostream & OS, const DeclContext * DC) static
Definition at line 5583 of file SemaSYCL.cpp.
References clang::NamedDecl::getName(), clang::if(), clang::NamespaceDecl::isAnonymousNamespace(), clang::NamespaceDecl::isInline(), and PrintNSHelper().
Referenced by EmitShim().
PrintNSHelper()
template<typename BeforeFn , typename AfterFn > static void PrintNSHelper (BeforeFn Before, AfterFn After, raw_ostream & OS, const DeclContext * DC) static
Definition at line 5545 of file SemaSYCL.cpp.
References clang::frontend::After, and clang::DeclContext::isTranslationUnit().
Referenced by PrintNamespaces(), and PrintNSClosingBraces().
PropagateAndDiagnoseDeviceAttr()
static void PropagateAndDiagnoseDeviceAttr (SemaSYCL & S, const SingleDeviceFunctionTracker & Tracker, Attr * A, FunctionDecl * SYCLKernel, FunctionDecl * KernelBody) static
Definition at line 4453 of file SemaSYCL.cpp.
Referenced by clang::SemaSYCL::MarkDevices().
reportConflictingAttrs()
static void reportConflictingAttrs (SemaSYCL & S, FunctionDecl * F, const Attr * A1, const Attr * A2) static
Definition at line 518 of file SemaSYCL.cpp.
Variable Documentation
FinalizeMethodName
constexpr llvm::StringLiteral FinalizeMethodName = "__finalize" static constexpr
Definition at line 68 of file SemaSYCL.cpp.
InitESIMDMethodName
constexpr llvm::StringLiteral InitESIMDMethodName = "__init_esimd" static constexpr
Definition at line 65 of file SemaSYCL.cpp.
InitMethodName
constexpr llvm::StringLiteral InitMethodName = "__init" static constexpr
Definition at line 64 of file SemaSYCL.cpp.
InitSpecConstantsBuffer
constexpr llvm::StringLiteral InitSpecConstantsBuffer static constexpr
Initial value:
=
    "__init_specialization_constants_buffer"
Definition at line 66 of file SemaSYCL.cpp.
LibstdcxxFailedAssertion
constexpr llvm::StringLiteral LibstdcxxFailedAssertion static constexpr
Initial value:
=
    "__failed_assertion"
Definition at line 69 of file SemaSYCL.cpp.
Referenced by isSYCLUndefinedAllowed().
MaxKernelArgsSize
constexpr unsigned MaxKernelArgsSize = 2048 constexpr
Definition at line 71 of file SemaSYCL.cpp.