clang: lib/Sema/SemaOpenMP.cpp File Reference
SemaOpenMP.cpp File Reference
This file implements semantic analysis for OpenMP directives and clauses.
#include "clang/Sema/SemaOpenMP.h"
#include "TreeTransform.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/OpenMPClause.h"
#include "clang/AST/StmtCXX.h"
#include "clang/AST/StmtOpenMP.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/AST/TypeOrdering.h"
#include "clang/Basic/DiagnosticSema.h"
#include "clang/Basic/OpenMPKinds.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ParsedAttr.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/IndexedMap.h"
#include "llvm/ADT/PointerEmbeddedInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Frontend/OpenMP/OMPAssume.h"
#include "llvm/Frontend/OpenMP/OMPConstants.h"
#include "llvm/IR/Assumptions.h"
#include <optional>
#include <set>
Classes
struct Kind2Unsigned
class GlobalDeclRefChecker
This class visits every VarDecl that the initializer references and adds OMPDeclareTargetDeclAttr to each of them.
Macros
#define DSAStack static_cast<DSAStackTy *>(VarDataSharingAttributesStack)
Functions
static const Expr * checkMapClauseExpressionBase (Sema &SemaRef, Expr *E, OMPClauseMappableExprCommon::MappableExprComponentList &CurComponents, OpenMPClauseKind CKind, OpenMPDirectiveKind DKind, bool NoDiagnose)
Return the expression of the base of the mappable expression or null if it cannot be determined and do all the necessary checks to see if the expression is valid as a standalone mappable expression.
static const Expr * getExprAsWritten (const Expr *E)
static Expr * getExprAsWritten (Expr *E)
static const ValueDecl * getCanonicalDecl (const ValueDecl *D)
static ValueDecl * getCanonicalDecl (ValueDecl *D)
static VarDecl * buildVarDecl (Sema &SemaRef, SourceLocation Loc, QualType Type, StringRef Name, const AttrVec *Attrs=nullptr, DeclRefExpr *OrigRef=nullptr)
Build a variable declaration for OpenMP loop iteration variable.
static DeclRefExpr * buildDeclRefExpr (Sema &S, VarDecl *D, QualType Ty, SourceLocation Loc, bool RefersToCapture=false)
static bool isConstNotMutableType (Sema &SemaRef, QualType Type, bool AcceptIfMutable=true, bool *IsClassType=nullptr)
static bool rejectConstNotMutableType (Sema &SemaRef, const ValueDecl *D, QualType Type, OpenMPClauseKind CKind, SourceLocation ELoc, bool AcceptIfMutable=true, bool ListItemNotVar=false)
static bool isOpenMPDeviceDelayedContext (Sema &S)
static OpenMPDefaultmapClauseKind getVariableCategoryFromDecl (const LangOptions &LO, const ValueDecl *VD)
static OMPCapturedExprDecl * buildCaptureDecl (Sema &S, IdentifierInfo *Id, Expr *CaptureExpr, bool WithInit, DeclContext *CurContext, bool AsExpression)
static std::pair< ValueDecl *, bool > getPrivateItem (Sema &S, Expr *&RefExpr, SourceLocation &ELoc, SourceRange &ERange, bool AllowArraySection=false, StringRef DiagType="")
static void checkReductionClauses (Sema &S, DSAStackTy *Stack, ArrayRef< OMPClause * > Clauses)
Check consistency of the reduction clauses.
static void checkAllocateClauses (Sema &S, DSAStackTy *Stack, ArrayRef< OMPClause * > Clauses)
static DeclRefExpr * buildCapture (Sema &S, ValueDecl *D, Expr *CaptureExpr, bool WithInit)
static void reportOriginalDsa (Sema &SemaRef, const DSAStackTy *Stack, const ValueDecl *D, const DSAStackTy::DSAVarData &DVar, bool IsLoopIterVar=false)
static bool FinishOpenMPLinearClause (OMPLinearClause &Clause, DeclRefExpr *IV, Expr *NumIterations, Sema &SemaRef, Scope *S, DSAStackTy *Stack)
static bool finishLinearClauses (Sema &SemaRef, ArrayRef< OMPClause * > Clauses, OMPLoopBasedDirective::HelperExprs &B, DSAStackTy *Stack)
static OMPAllocateDeclAttr::AllocatorTypeTy getAllocatorKind (Sema &S, DSAStackTy *Stack, Expr *Allocator)
static bool checkPreviousOMPAllocateAttribute (Sema &S, DSAStackTy *Stack, Expr *RefExpr, VarDecl *VD, OMPAllocateDeclAttr::AllocatorTypeTy AllocatorKind, Expr *Allocator)
static void applyOMPAllocateAttribute (Sema &S, VarDecl *VD, OMPAllocateDeclAttr::AllocatorTypeTy AllocatorKind, Expr *Allocator, Expr *Alignment, SourceRange SR)
static OpenMPMapClauseKind getMapClauseKindFromModifier (OpenMPDefaultmapClauseModifier M, bool IsAggregateOrDeclareTarget)
static void handleDeclareVariantConstructTrait (DSAStackTy *Stack, OpenMPDirectiveKind DKind, bool ScopeEntry)
static SmallVector< SemaOpenMP::CapturedParamNameType > getParallelRegionParams (Sema &SemaRef, bool LoopBoundSharing)
static SmallVector< SemaOpenMP::CapturedParamNameType > getTeamsRegionParams (Sema &SemaRef)
static SmallVector< SemaOpenMP::CapturedParamNameType > getTaskRegionParams (Sema &SemaRef)
static SmallVector< SemaOpenMP::CapturedParamNameType > getTargetRegionParams (Sema &SemaRef)
static SmallVector< SemaOpenMP::CapturedParamNameType > getUnknownRegionParams (Sema &SemaRef)
static SmallVector< SemaOpenMP::CapturedParamNameType > getTaskloopRegionParams (Sema &SemaRef)
static void processCapturedRegions (Sema &SemaRef, OpenMPDirectiveKind DKind, Scope *CurScope, SourceLocation Loc)
static ExprResult buildCapture (Sema &S, Expr *CaptureExpr, DeclRefExpr *&Ref, StringRef Name)
static bool checkOrderedOrderSpecified (Sema &S, const ArrayRef< OMPClause * > Clauses)
static bool checkCancelRegion (Sema &SemaRef, OpenMPDirectiveKind CurrentRegion, OpenMPDirectiveKind CancelRegion, SourceLocation StartLoc)
static bool checkNestingOfRegions (Sema &SemaRef, const DSAStackTy *Stack, OpenMPDirectiveKind CurrentRegion, const DeclarationNameInfo &CurrentName, OpenMPDirectiveKind CancelRegion, OpenMPBindClauseKind BindKind, SourceLocation StartLoc)
static bool checkIfClauses (Sema &S, OpenMPDirectiveKind Kind, ArrayRef< OMPClause * > Clauses, ArrayRef< OpenMPDirectiveKind > AllowedNameModifiers)
static VarDecl * precomputeExpr (Sema &Actions, SmallVectorImpl< Stmt * > &BodyStmts, Expr *E, StringRef Name)
static CapturedStmt * buildDistanceFunc (Sema &Actions, QualType LogicalTy, BinaryOperator::Opcode Rel, Expr *StartExpr, Expr *StopExpr, Expr *StepExpr)
Create a closure that computes the number of iterations of a loop.
static CapturedStmt * buildLoopVarFunc (Sema &Actions, QualType LoopVarTy, QualType LogicalTy, DeclRefExpr *StartExpr, Expr *Step, bool Deref)
Create a closure that computes the loop variable from the logical iteration number.
static ExprResult buildUserDefinedMapperRef (Sema &SemaRef, Scope *S, CXXScopeSpec &MapperIdScopeSpec, const DeclarationNameInfo &MapperId, QualType Type, Expr *UnresolvedMapper)
static void processImplicitMapsWithDefaultMappers (Sema &S, DSAStackTy *Stack, SmallVectorImpl< OMPClause * > &Clauses)
Perform DFS through the structure/class data members trying to find member(s) with user-defined 'default' mapper and generate implicit map clauses for such members with the found 'default' mapper.
static bool teamsLoopCanBeParallelFor (Stmt *AStmt, Sema &SemaRef)
static void setPrototype (Sema &S, FunctionDecl *FD, FunctionDecl *FDWithProto, QualType NewType)
static CapturedStmt * setBranchProtectedScope (Sema &SemaRef, OpenMPDirectiveKind DKind, Stmt *AStmt)
static bool checkOpenMPIterationSpace (OpenMPDirectiveKind DKind, Stmt *S, Sema &SemaRef, DSAStackTy &DSA, unsigned CurrentNestedLoopCount, unsigned NestedLoopCount, unsigned TotalNestedLoopCount, Expr *CollapseLoopCountExpr, Expr *OrderedLoopCountExpr, SemaOpenMP::VarsWithInheritedDSAType &VarsWithImplicitDSA, llvm::MutableArrayRef< LoopIterationSpace > ResultIterSpaces, llvm::MapVector< const Expr *, DeclRefExpr * > &Captures)
Called on a for stmt to check and extract its iteration space for further processing (such as collapsing).
static ExprResult buildCounterInit (Sema &SemaRef, Scope *S, SourceLocation Loc, ExprResult VarRef, ExprResult Start, bool IsNonRectangularLB, llvm::MapVector< const Expr *, DeclRefExpr * > &Captures)
Build 'VarRef = Start.
static ExprResult buildCounterUpdate (Sema &SemaRef, Scope *S, SourceLocation Loc, ExprResult VarRef, ExprResult Start, ExprResult Iter, ExprResult Step, bool Subtract, bool IsNonRectangularLB, llvm::MapVector< const Expr *, DeclRefExpr * > *Captures=nullptr)
Build 'VarRef = Start + Iter * Step'.
static ExprResult widenIterationCount (unsigned Bits, Expr *E, Sema &SemaRef)
Convert integer expression E to make it have at least Bits bits.
static bool fitsInto (unsigned Bits, bool Signed, const Expr *E, Sema &SemaRef)
Check if the given expression E is a constant integer that fits into Bits bits.
static Stmt * buildPreInits (ASTContext &Context, MutableArrayRef< Decl * > PreInits)
Build preinits statement for the given declarations.
static void appendFlattenedStmtList (SmallVectorImpl< Stmt * > &TargetList, Stmt *Item)
Append the Item or the content of a CompoundStmt to the list TargetList.
static Stmt * buildPreInits (ASTContext &Context, const llvm::MapVector< const Expr *, DeclRefExpr * > &Captures)
Build preinits statement for the given declarations.
static Stmt * buildPreInits (ASTContext &Context, ArrayRef< Stmt * > PreInits)
Build pre-init statement for the given statements.
static Expr * buildPostUpdate (Sema &S, ArrayRef< Expr * > PostUpdates)
Build postupdate expression for the given list of postupdates expressions.
static unsigned checkOpenMPLoop (OpenMPDirectiveKind DKind, Expr *CollapseLoopCountExpr, Expr *OrderedLoopCountExpr, Stmt *AStmt, Sema &SemaRef, DSAStackTy &DSA, SemaOpenMP::VarsWithInheritedDSAType &VarsWithImplicitDSA, OMPLoopBasedDirective::HelperExprs &Built)
Called on a for stmt to check itself and nested loops (if any).
static Expr * getCollapseNumberExpr (ArrayRef< OMPClause * > Clauses)
static Expr * getOrderedNumberExpr (ArrayRef< OMPClause * > Clauses)
static bool checkSimdlenSafelenSpecified (Sema &S, const ArrayRef< OMPClause * > Clauses)
static bool checkGenericLoopLastprivate (Sema &S, ArrayRef< OMPClause * > Clauses, OpenMPDirectiveKind K, DSAStackTy *Stack)
static bool checkSectionsDirective (Sema &SemaRef, OpenMPDirectiveKind DKind, Stmt *AStmt, DSAStackTy *Stack)
static Expr * getDirectCallExpr (Expr *E)
static bool checkMutuallyExclusiveClauses (Sema &S, ArrayRef< OMPClause * > Clauses, ArrayRef< OpenMPClauseKind > MutuallyExclusiveClauses)
Find and diagnose mutually exclusive clause kinds.
static bool hasClauses (ArrayRef< OMPClause * > Clauses, const OpenMPClauseKind K)
Check for existence of a map clause in the list of clauses.
template<typename... Params>
static bool hasClauses (ArrayRef< OMPClause * > Clauses, const OpenMPClauseKind K, const Params... ClauseTypes)
static bool isClauseMappable (ArrayRef< OMPClause * > Clauses)
Check if the variables in the mapping clause are externally visible.
static bool checkReductionClauseWithNogroup (Sema &S, ArrayRef< OMPClause * > Clauses)
static void addLoopPreInits (ASTContext &Context, OMPLoopBasedDirective::HelperExprs &LoopHelper, Stmt *LoopStmt, ArrayRef< Stmt * > OriginalInit, SmallVectorImpl< Stmt * > &PreInits)
Add preinit statements that need to be propageted from the selected loop.
static void collectLoopStmts (Stmt *AStmt, MutableArrayRef< Stmt * > LoopStmts)
Collect the loop statements (ForStmt or CXXRangeForStmt) of the affected loop of a construct.
static OpenMPDirectiveKind getOpenMPCaptureRegionForClause (OpenMPDirectiveKind DKind, OpenMPClauseKind CKind, unsigned OpenMPVersion, OpenMPDirectiveKind NameModifier=OMPD_unknown)
static bool isNonNegativeIntegerValue (Expr *&ValExpr, Sema &SemaRef, OpenMPClauseKind CKind, bool StrictlyPositive, bool BuildCapture=false, OpenMPDirectiveKind DKind=OMPD_unknown, OpenMPDirectiveKind *CaptureRegion=nullptr, Stmt **HelperValStmt=nullptr)
static bool findOMPAllocatorHandleT (Sema &S, SourceLocation Loc, DSAStackTy *Stack)
Tries to find omp_allocator_handle_t type.
static std::string getListOfPossibleValues (OpenMPClauseKind K, unsigned First, unsigned Last, ArrayRef< unsigned > Exclude=std::nullopt)
static bool checkScheduleModifiers (Sema &S, OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2, SourceLocation M1Loc, SourceLocation M2Loc)
static bool isValidInteropVariable (Sema &SemaRef, Expr *InteropVarExpr, SourceLocation VarLoc, OpenMPClauseKind Kind)
template<typename T , typename U >
static T filterLookupForUDReductionAndMapper (SmallVectorImpl< U > &Lookups, const llvm::function_ref< T(ValueDecl *)> Gen)
static NamedDecl * findAcceptableDecl (Sema &SemaRef, NamedDecl *D)
static void argumentDependentLookup (Sema &SemaRef, const DeclarationNameInfo &Id, SourceLocation Loc, QualType Ty, SmallVectorImpl< UnresolvedSet< 8 >> &Lookups)
static ExprResult buildDeclareReductionRef (Sema &SemaRef, SourceLocation Loc, SourceRange Range, Scope *S, CXXScopeSpec &ReductionIdScopeSpec, const DeclarationNameInfo &ReductionId, QualType Ty, CXXCastPath &BasePath, Expr *UnresolvedReduction)
static bool checkOMPArraySectionConstantForReduction (ASTContext &Context, const ArraySectionExpr *OASE, bool &SingleElement, SmallVectorImpl< llvm::APSInt > &ArraySizes)
static BinaryOperatorKind getRelatedCompoundReductionOp (BinaryOperatorKind BOK)
static bool actOnOMPReductionKindClause (Sema &S, DSAStackTy *Stack, OpenMPClauseKind ClauseKind, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec &ReductionIdScopeSpec, const DeclarationNameInfo &ReductionId, ArrayRef< Expr * > UnresolvedReductions, ReductionData &RD)
static bool findOMPDependT (Sema &S, SourceLocation Loc, DSAStackTy *Stack, bool Diagnose=true)
Tries to find omp_depend_t. type.
static DoacrossDataInfoTy ProcessOpenMPDoacrossClauseCommon (Sema &SemaRef, bool IsSource, ArrayRef< Expr * > VarList, DSAStackTy *Stack, SourceLocation EndLoc)
static bool checkTypeMappable (SourceLocation SL, SourceRange SR, Sema &SemaRef, DSAStackTy *Stack, QualType QTy, bool FullCheck=true)
static bool checkArrayExpressionDoesNotReferToWholeSize (Sema &SemaRef, const Expr *E, QualType BaseQTy)
Return true if it can be proven that the provided array expression (array section or array subscript) does NOT specify the whole size of the array whose base type is BaseQTy.
static bool checkArrayExpressionDoesNotReferToUnitySize (Sema &SemaRef, const Expr *E, QualType BaseQTy)
static bool checkMapConflicts (Sema &SemaRef, DSAStackTy *DSAS, const ValueDecl *VD, const Expr *E, bool CurrentRegionOnly, OMPClauseMappableExprCommon::MappableExprComponentListRef CurComponents, OpenMPClauseKind CKind)
static void checkMappableExpressionList (Sema &SemaRef, DSAStackTy *DSAS, OpenMPClauseKind CKind, MappableVarListInfo &MVLI, SourceLocation StartLoc, CXXScopeSpec &MapperIdScopeSpec, DeclarationNameInfo MapperId, ArrayRef< Expr * > UnresolvedMappers, OpenMPMapClauseKind MapType=OMPC_MAP_unknown, ArrayRef< OpenMPMapModifierKind > Modifiers=std::nullopt, bool IsMapTypeImplicit=false, bool NoDiagnose=false)
static bool findOMPEventHandleT (Sema &S, SourceLocation Loc, DSAStackTy *Stack)
Tries to find omp_event_handle_t type.
static void checkDeclInTargetContext (SourceLocation SL, SourceRange SR, Sema &SemaRef, Decl *D)
static bool checkValueDeclInTarget (SourceLocation SL, SourceRange SR, Sema &SemaRef, DSAStackTy *Stack, ValueDecl *VD)
static bool findOMPAlloctraitT (Sema &S, SourceLocation Loc, DSAStackTy *Stack)
Tries to find omp_alloctrait_t type.
static void checkOMPAssumeAttr (Sema &S, SourceLocation Loc, StringRef AssumptionStr)
Check if AssumptionStr is a known assumption and warn if not.
Detailed Description
This file implements semantic analysis for OpenMP directives and clauses.
Definition in file SemaOpenMP.cpp.
Macro Definition Documentation
DSAStack
#define DSAStack static_cast<DSAStackTy *>(VarDataSharingAttributesStack)
Definition at line 2029 of file SemaOpenMP.cpp.
Function Documentation
actOnOMPReductionKindClause()
static bool actOnOMPReductionKindClause (Sema & S, DSAStackTy * Stack, OpenMPClauseKind ClauseKind, ArrayRef< Expr * > VarList, SourceLocation StartLoc, SourceLocation LParenLoc, SourceLocation ColonLoc, SourceLocation EndLoc, CXXScopeSpec & ReductionIdScopeSpec, const DeclarationNameInfo & ReductionId, ArrayRef< Expr * > UnresolvedReductions, ReductionData & RD) static
Definition at line 17857 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPInReductionClause(), clang::SemaOpenMP::ActOnOpenMPReductionClause(), and clang::SemaOpenMP::ActOnOpenMPTaskReductionClause().
addLoopPreInits()
static void addLoopPreInits (ASTContext & Context, OMPLoopBasedDirective::HelperExprs & LoopHelper, Stmt * LoopStmt, ArrayRef< Stmt * > OriginalInit, SmallVectorImpl< Stmt * > & PreInits) static
Add preinit statements that need to be propageted from the selected loop.
Definition at line 14056 of file SemaOpenMP.cpp.
appendFlattenedStmtList()
static void appendFlattenedStmtList (SmallVectorImpl< Stmt * > & TargetList, Stmt * Item) static
Append the Item or the content of a CompoundStmt to the list TargetList.
A CompoundStmt is used as container in case multiple statements need to be stored in lieu of using an explicit list. Flattening is necessary because contained DeclStmts need to be visible after the execution of the list. Used for OpenMP pre-init declarations/statements.
Definition at line 9506 of file SemaOpenMP.cpp.
Referenced by checkOpenMPLoop().
applyOMPAllocateAttribute()
static void applyOMPAllocateAttribute (Sema & S, VarDecl * VD, OMPAllocateDeclAttr::AllocatorTypeTy AllocatorKind, Expr * Allocator, Expr * Alignment, SourceRange SR) static
Definition at line 3416 of file SemaOpenMP.cpp.
argumentDependentLookup()
static void argumentDependentLookup (Sema & SemaRef, const DeclarationNameInfo & Id, SourceLocation Loc, QualType Ty, SmallVectorImpl< UnresolvedSet< 8 >> & Lookups) static
Definition at line 17506 of file SemaOpenMP.cpp.
References D, findAcceptableDecl(), clang::Sema::FindAssociatedClassesAndNamespaces(), Id, clang::Sema::isVisible(), Loc, and clang::VK_LValue.
buildCapture() [1/2]
static ExprResult buildCapture (Sema & S, Expr * CaptureExpr, DeclRefExpr *& Ref, StringRef Name) static
Definition at line 4475 of file SemaOpenMP.cpp.
buildCapture() [2/2]
static DeclRefExpr * buildCapture (Sema & S, ValueDecl * D, Expr * CaptureExpr, bool WithInit) static
Definition at line 4462 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPAlignedClause(), clang::SemaOpenMP::ActOnOpenMPCopyprivateClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPHasDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPLoopInitialization(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPSharedClause(), clang::SemaOpenMP::ActOnOpenMPUseDeviceAddrClause(), and clang::SemaOpenMP::ActOnOpenMPUseDevicePtrClause().
buildCaptureDecl()
static OMPCapturedExprDecl * buildCaptureDecl (Sema & S, IdentifierInfo * Id, Expr * CaptureExpr, bool WithInit, DeclContext * CurContext, bool AsExpression) static
Definition at line 4431 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::isOpenMPCapturedDecl().
buildCounterInit()
static ExprResult buildCounterInit (Sema & SemaRef, Scope * S, SourceLocation Loc, ExprResult VarRef, ExprResult Start, bool IsNonRectangularLB, llvm::MapVector< const Expr *, DeclRefExpr * > & Captures) static
Build 'VarRef = Start.
Definition at line 9363 of file SemaOpenMP.cpp.
buildCounterUpdate()
static ExprResult buildCounterUpdate (Sema & SemaRef, Scope * S, SourceLocation Loc, ExprResult VarRef, ExprResult Start, ExprResult Iter, ExprResult Step, bool Subtract, bool IsNonRectangularLB, llvm::MapVector< const Expr *, DeclRefExpr * > * Captures = nullptr) static
Build 'VarRef = Start + Iter * Step'.
Definition at line 9387 of file SemaOpenMP.cpp.
buildDeclareReductionRef()
static ExprResult buildDeclareReductionRef (Sema & SemaRef, SourceLocation Loc, SourceRange Range, Scope * S, CXXScopeSpec & ReductionIdScopeSpec, const DeclarationNameInfo & ReductionId, QualType Ty, CXXCastPath & BasePath, Expr * UnresolvedReduction) static
Definition at line 17564 of file SemaOpenMP.cpp.
buildDeclRefExpr()
static DeclRefExpr* buildDeclRefExpr (Sema & S, VarDecl * D, QualType Ty, SourceLocation Loc, bool RefersToCapture = false) static
Definition at line 1573 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPCopyinClause(), clang::SemaOpenMP::ActOnOpenMPCopyprivateClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPLoopInitialization(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPUseDevicePtrClause(), buildDistanceFunc(), clang::SemaOpenMP::EndOpenMPDSABlock(), and clang::SemaOpenMP::isOpenMPCapturedDecl().
buildDistanceFunc()
static CapturedStmt* buildDistanceFunc (Sema & Actions, QualType LogicalTy, BinaryOperator::Opcode Rel, Expr * StartExpr, Expr * StopExpr, Expr * StepExpr) static
Create a closure that computes the number of iterations of a loop.
Parameters
Actions The Sema object.
LogicalTy Type for the logical iteration number.
Rel Comparison operator of the loop condition.
StartExpr Value of the loop counter at the first iteration.
StopExpr Expression the loop counter is compared against in the loop condition.
StepExpr Amount of increment after each iteration.
Returns
Closure (CapturedStmt) of the distance calculation.
Definition at line 5397 of file SemaOpenMP.cpp.
References clang::Sema::ActOnCapturedRegionEnd(), clang::Sema::ActOnCapturedRegionStart(), clang::Sema::ActOnCompoundStmt(), clang::Sema::ActOnConditionalOp(), clang::AssertSuccess(), clang::Sema::BuildBinOp(), clang::Sema::BuildCStyleCastExpr(), buildDeclRefExpr(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildUnaryOp(), clang::CR_Default, clang::IntegerLiteral::Create(), clang::Sema::CurContext, clang::Sema::getASTContext(), clang::Sema::getCurScope(), clang::ASTContext::getIntWidth(), clang::ASTContext::getLValueReferenceType(), clang::CapturedDecl::getParam(), clang::ASTContext::getTrivialTypeSourceInfo(), clang::ValueDecl::getType(), precomputeExpr(), Range, and clang::VK_LValue.
Referenced by clang::SemaOpenMP::ActOnOpenMPCanonicalLoop().
buildLoopVarFunc()
static CapturedStmt* buildLoopVarFunc (Sema & Actions, QualType LoopVarTy, QualType LogicalTy, DeclRefExpr * StartExpr, Expr * Step, bool Deref) static
Create a closure that computes the loop variable from the logical iteration number.
Parameters
Actions The Sema object.
LoopVarTy Type for the loop variable used for result value.
LogicalTy Type for the logical iteration number.
StartExpr Value of the loop counter at the first iteration.
Step Amount of increment after each iteration.
Deref Whether the loop variable is a dereference of the loop counter variable.
Returns
Closure (CapturedStmt) of the loop value calculation.
Definition at line 5545 of file SemaOpenMP.cpp.
References clang::Sema::ActOnCapturedRegionEnd(), clang::Sema::ActOnCapturedRegionStart(), clang::AssertSuccess(), clang::Sema::BuildBinOp(), clang::Sema::BuildDeclRefExpr(), clang::Sema::BuildUnaryOp(), clang::CR_Default, clang::Sema::CurContext, clang::Sema::getASTContext(), clang::Sema::getCurScope(), clang::DeclRefExpr::getDecl(), clang::ASTContext::getLValueReferenceType(), clang::Sema::TryCapture_ExplicitByVal, clang::Sema::tryCaptureVariable(), and clang::VK_LValue.
Referenced by clang::SemaOpenMP::ActOnOpenMPCanonicalLoop().
buildPostUpdate()
static Expr* buildPostUpdate (Sema & S, ArrayRef< Expr * > PostUpdates) static
Build postupdate expression for the given list of postupdates expressions.
Definition at line 9543 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPInReductionClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPReductionClause(), and clang::SemaOpenMP::ActOnOpenMPTaskReductionClause().
buildPreInits() [1/3]
static Stmt* buildPreInits (ASTContext & Context, ArrayRef< Stmt * > PreInits) static
Build pre-init statement for the given statements.
Definition at line 9532 of file SemaOpenMP.cpp.
buildPreInits() [2/3]
static Stmt* buildPreInits (ASTContext & Context, const llvm::MapVector< const Expr *, DeclRefExpr * > & Captures) static
Build preinits statement for the given declarations.
Definition at line 9520 of file SemaOpenMP.cpp.
buildPreInits() [3/3]
static Stmt* buildPreInits (ASTContext & Context, MutableArrayRef< Decl * > PreInits) static
Build preinits statement for the given declarations.
Definition at line 9489 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPDistScheduleClause(), clang::SemaOpenMP::ActOnOpenMPFilterClause(), clang::SemaOpenMP::ActOnOpenMPFinalClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPIfClause(), clang::SemaOpenMP::ActOnOpenMPInReductionClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPNocontextClause(), clang::SemaOpenMP::ActOnOpenMPNovariantsClause(), clang::SemaOpenMP::ActOnOpenMPNumTeamsClause(), clang::SemaOpenMP::ActOnOpenMPNumThreadsClause(), clang::SemaOpenMP::ActOnOpenMPReductionClause(), clang::SemaOpenMP::ActOnOpenMPScheduleClause(), clang::SemaOpenMP::ActOnOpenMPTaskReductionClause(), clang::SemaOpenMP::ActOnOpenMPThreadLimitClause(), clang::SemaOpenMP::ActOnOpenMPXDynCGroupMemClause(), and isNonNegativeIntegerValue().
buildUserDefinedMapperRef()
static ExprResult buildUserDefinedMapperRef (Sema & SemaRef, Scope * S, CXXScopeSpec & MapperIdScopeSpec, const DeclarationNameInfo & MapperId, QualType Type, Expr * UnresolvedMapper) static
Definition at line 20427 of file SemaOpenMP.cpp.
Referenced by checkMappableExpressionList().
buildVarDecl()
static VarDecl* buildVarDecl (Sema & SemaRef, SourceLocation Loc, QualType Type, StringRef Name, const AttrVec * Attrs = nullptr, DeclRefExpr * OrigRef = nullptr) static
Build a variable declaration for OpenMP loop iteration variable.
Definition at line 1552 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPCopyinClause(), clang::SemaOpenMP::ActOnOpenMPCopyprivateClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPUseDevicePtrClause(), and clang::SemaOpenMP::EndOpenMPDSABlock().
checkAllocateClauses()
static void checkAllocateClauses (Sema & S, DSAStackTy * Stack, ArrayRef< OMPClause * > Clauses) static
Definition at line 5238 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::EndOpenMPDSABlock().
checkArrayExpressionDoesNotReferToUnitySize()
static bool checkArrayExpressionDoesNotReferToUnitySize (Sema & SemaRef, const Expr * E, QualType BaseQTy) static
Definition at line 19766 of file SemaOpenMP.cpp.
References E, clang::Sema::getASTContext(), and clang::QualType::getTypePtr().
checkArrayExpressionDoesNotReferToWholeSize()
static bool checkArrayExpressionDoesNotReferToWholeSize (Sema & SemaRef, const Expr * E, QualType BaseQTy) static
Return true if it can be proven that the provided array expression (array section or array subscript) does NOT specify the whole size of the array whose base type is BaseQTy.
Definition at line 19708 of file SemaOpenMP.cpp.
References E, clang::Expr::EvaluateAsInt(), clang::Sema::getASTContext(), clang::QualType::getTypePtr(), and clang::Type::isPointerType().
Referenced by checkMapConflicts().
checkCancelRegion()
static bool checkCancelRegion (Sema & SemaRef, OpenMPDirectiveKind CurrentRegion, OpenMPDirectiveKind CancelRegion, SourceLocation StartLoc) static
Definition at line 4764 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag().
Referenced by clang::SemaOpenMP::ActOnOpenMPExecutableDirective().
checkDeclInTargetContext()
static void checkDeclInTargetContext (SourceLocation SL, SourceRange SR, Sema & SemaRef, Decl * D) static
Definition at line 21864 of file SemaOpenMP.cpp.
References D, clang::SemaBase::Diag(), clang::Sema::getCurBlock(), clang::Sema::getCurCapturedRegion(), clang::Sema::getCurLambda(), clang::Decl::getLocation(), and clang::Sema::LangOpts.
Referenced by clang::SemaOpenMP::checkDeclIsAllowedInOpenMPTarget().
checkGenericLoopLastprivate()
static bool checkGenericLoopLastprivate (Sema & S, ArrayRef< OMPClause * > Clauses, OpenMPDirectiveKind K, DSAStackTy * Stack) static
Definition at line 10551 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsGenericLoopDirective(), and clang::SemaOpenMP::ActOnOpenMPTeamsGenericLoopDirective().
checkIfClauses()
static bool checkIfClauses (Sema & S, OpenMPDirectiveKind Kind, ArrayRef< OMPClause * > Clauses, ArrayRef< OpenMPDirectiveKind > AllowedNameModifiers) static
Definition at line 5072 of file SemaOpenMP.cpp.
checkMapClauseExpressionBase()
static const Expr* checkMapClauseExpressionBase (Sema & SemaRef, Expr * E, OMPClauseMappableExprCommon::MappableExprComponentList & CurComponents, OpenMPClauseKind CKind, OpenMPDirectiveKind DKind, bool NoDiagnose) static
Return the expression of the base of the mappable expression or null if it cannot be determined and do all the necessary checks to see if the expression is valid as a standalone mappable expression.
In the process, record all the components of the expression.
Definition at line 20148 of file SemaOpenMP.cpp.
References clang::SemaBase::Diag(), E, clang::Expr::getExprLoc(), clang::Sema::getLangOpts(), clang::ArraySectionExpr::getLength(), clang::Stmt::getSourceRange(), and clang::Expr::IgnoreParens().
Referenced by checkMappableExpressionList().
checkMapConflicts()
static bool checkMapConflicts (Sema & SemaRef, DSAStackTy * DSAS, const ValueDecl * VD, const Expr * E, bool CurrentRegionOnly, OMPClauseMappableExprCommon::MappableExprComponentListRef CurComponents, OpenMPClauseKind CKind) static
Definition at line 20180 of file SemaOpenMP.cpp.
References advance(), Begin, checkArrayExpressionDoesNotReferToWholeSize(), clang::SemaBase::Diag(), E, End, clang::for(), clang::Expr::getExprLoc(), clang::QualType::getNonReferenceType(), clang::Stmt::getSourceRange(), clang::if(), clang::Type::isAnyPointerType(), Kind, and clang::Sema::LangOpts.
Referenced by checkMappableExpressionList().
checkMappableExpressionList()
static void checkMappableExpressionList (Sema & SemaRef, DSAStackTy * DSAS, OpenMPClauseKind CKind, MappableVarListInfo & MVLI, SourceLocation StartLoc, CXXScopeSpec & MapperIdScopeSpec, DeclarationNameInfo MapperId, ArrayRef< Expr * > UnresolvedMappers, OpenMPMapClauseKind MapType = OMPC_MAP_unknown, ArrayRef< OpenMPMapModifierKind > Modifiers = std::nullopt, bool IsMapTypeImplicit = false, bool NoDiagnose = false) static
Definition at line 20568 of file SemaOpenMP.cpp.
References buildUserDefinedMapperRef(), checkMapClauseExpressionBase(), checkMapConflicts(), checkTypeMappable(), clang::Expr::containsUnexpandedParameterPack(), clang::ASTContext::DeclarationNames, clang::SemaBase::Diag(), clang::ActionResult< PtrTy, Compress >::get(), clang::IdentifierTable::get(), clang::Type::getAsArrayTypeUnsafe(), clang::OMPClauseMappableExprCommon::MappableComponent::getAssociatedDeclaration(), clang::Sema::getASTContext(), clang::ArraySectionExpr::getBase(), clang::ArraySectionExpr::getBaseOriginalType(), clang::QualType::getCanonicalType(), clang::Sema::getCurScope(), clang::Expr::getExprLoc(), clang::Sema::getLangOpts(), clang::DeclarationNameInfo::getName(), clang::getOpenMPSimpleClauseTypeName(), clang::Type::getPointeeType(), clang::Stmt::getSourceRange(), clang::Expr::getType(), clang::ASTContext::Idents, clang::Expr::IgnoreParenCasts(), clang::Expr::IgnoreParenLValueCasts(), clang::Expr::IgnoreParens(), clang::Decl::isCanonicalDecl(), clang::DeclarationName::isEmpty(), clang::Expr::isInstantiationDependent(), clang::ActionResult< PtrTy, Compress >::isInvalid(), clang::Expr::isLValue(), clang::isOpenMPPrivate(), clang::isOpenMPTargetExecutionDirective(), clang::Expr::isTypeDependent(), clang::SourceLocation::isValid(), clang::Expr::isValueDependent(), clang::Sema::LangOpts, reportOriginalDsa(), clang::DeclarationNameInfo::setLoc(), and clang::DeclarationNameInfo::setName().
Referenced by clang::SemaOpenMP::ActOnOpenMPFromClause(), clang::SemaOpenMP::ActOnOpenMPMapClause(), and clang::SemaOpenMP::ActOnOpenMPToClause().
checkMutuallyExclusiveClauses()
static bool checkMutuallyExclusiveClauses (Sema & S, ArrayRef< OMPClause * > Clauses, ArrayRef< OpenMPClauseKind > MutuallyExclusiveClauses) static
Find and diagnose mutually exclusive clause kinds.
Definition at line 10941 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTaskDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopDirective(), and clang::SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective().
checkNestingOfRegions()
static bool checkNestingOfRegions (Sema & SemaRef, const DSAStackTy * Stack, OpenMPDirectiveKind CurrentRegion, const DeclarationNameInfo & CurrentName, OpenMPDirectiveKind CancelRegion, OpenMPBindClauseKind BindKind, SourceLocation StartLoc) static
Definition at line 4780 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPExecutableDirective().
checkOMPArraySectionConstantForReduction()
static bool checkOMPArraySectionConstantForReduction (ASTContext & Context, const ArraySectionExpr * OASE, bool & SingleElement, SmallVectorImpl< llvm::APSInt > & ArraySizes) static
Definition at line 17776 of file SemaOpenMP.cpp.
checkOMPAssumeAttr()
static void checkOMPAssumeAttr (Sema & S, SourceLocation Loc, StringRef AssumptionStr) static
Check if AssumptionStr is a known assumption and warn if not.
Definition at line 23453 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::handleOMPAssumeAttr().
checkOpenMPIterationSpace()
static bool checkOpenMPIterationSpace (OpenMPDirectiveKind DKind, Stmt * S, Sema & SemaRef, DSAStackTy & DSA, unsigned CurrentNestedLoopCount, unsigned NestedLoopCount, unsigned TotalNestedLoopCount, Expr * CollapseLoopCountExpr, Expr * OrderedLoopCountExpr, SemaOpenMP::VarsWithInheritedDSAType & VarsWithImplicitDSA, llvm::MutableArrayRef< LoopIterationSpace > ResultIterSpaces, llvm::MapVector< const Expr *, DeclRefExpr * > & Captures) static
Called on a for stmt to check and extract its iteration space for further processing (such as collapsing).
Definition at line 9145 of file SemaOpenMP.cpp.
Referenced by checkOpenMPLoop().
checkOpenMPLoop()
static unsigned checkOpenMPLoop (OpenMPDirectiveKind DKind, Expr * CollapseLoopCountExpr, Expr * OrderedLoopCountExpr, Stmt * AStmt, Sema & SemaRef, DSAStackTy & DSA, SemaOpenMP::VarsWithInheritedDSAType & VarsWithImplicitDSA, OMPLoopBasedDirective::HelperExprs & Built) static
Called on a for stmt to check itself and nested loops (if any).
Returns
Returns 0 if one of the collapsed stmts is not canonical for loop, number of collapsed loops otherwise.
Definition at line 9566 of file SemaOpenMP.cpp.
References appendFlattenedStmtList(), checkOpenMPIterationSpace(), clang::OMPLoopBasedDirective::HelperExprs::clear(), clang::SemaBase::Diag(), clang::OMPLoopBasedDirective::doForAllLoops(), clang::Expr::EvaluateAsInt(), clang::Sema::getASTContext(), clang::Expr::getExprLoc(), clang::APValue::getInt(), clang::Stmt::getSourceRange(), clang::Stmt::IgnoreContainers(), clang::isOpenMPLoopTransformationDirective(), clang::Expr::isValueDependent(), clang::Sema::LangOpts, max(), and clang::Expr::EvalResult::Val.
Referenced by clang::SemaOpenMP::ActOnOpenMPDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPForDirective(), clang::SemaOpenMP::ActOnOpenMPForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeSimdDirective(), and clang::SemaOpenMP::ActOnOpenMPTeamsGenericLoopDirective().
checkOrderedOrderSpecified()
static bool checkOrderedOrderSpecified (Sema & S, const ArrayRef< OMPClause * > Clauses) static
Definition at line 4565 of file SemaOpenMP.cpp.
checkPreviousOMPAllocateAttribute()
static bool checkPreviousOMPAllocateAttribute (Sema & S, DSAStackTy * Stack, Expr * RefExpr, VarDecl * VD, OMPAllocateDeclAttr::AllocatorTypeTy AllocatorKind, Expr * Allocator) static
Definition at line 3365 of file SemaOpenMP.cpp.
checkReductionClauses()
static void checkReductionClauses (Sema & S, DSAStackTy * Stack, ArrayRef< OMPClause * > Clauses) static
Check consistency of the reduction clauses.
Definition at line 2811 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::EndOpenMPDSABlock().
checkReductionClauseWithNogroup()
static bool checkReductionClauseWithNogroup (Sema & S, ArrayRef< OMPClause * > Clauses) static
Definition at line 13165 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopDirective(), and clang::SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective().
checkScheduleModifiers()
static bool checkScheduleModifiers (Sema & S, OpenMPScheduleClauseModifier M1, OpenMPScheduleClauseModifier M2, SourceLocation M1Loc, SourceLocation M2Loc) static
Definition at line 15859 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPScheduleClause().
checkSectionsDirective()
static bool checkSectionsDirective (Sema & SemaRef, OpenMPDirectiveKind DKind, Stmt * AStmt, DSAStackTy * Stack) static
Definition at line 10432 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPParallelSectionsDirective(), and clang::SemaOpenMP::ActOnOpenMPSectionsDirective().
checkSimdlenSafelenSpecified()
static bool checkSimdlenSafelenSpecified (Sema & S, const ArrayRef< OMPClause * > Clauses) static
Definition at line 10280 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), and clang::SemaOpenMP::ActOnOpenMPTeamsDistributeSimdDirective().
checkTypeMappable()
static bool checkTypeMappable (SourceLocation SL, SourceRange SR, Sema & SemaRef, DSAStackTy * Stack, QualType QTy, bool FullCheck = true) static
Definition at line 19694 of file SemaOpenMP.cpp.
Referenced by checkMappableExpressionList().
checkValueDeclInTarget()
static bool checkValueDeclInTarget (SourceLocation SL, SourceRange SR, Sema & SemaRef, DSAStackTy * Stack, ValueDecl * VD) static
Definition at line 21895 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::checkDeclIsAllowedInOpenMPTarget().
collectLoopStmts()
static void collectLoopStmts (Stmt * AStmt, MutableArrayRef< Stmt * > LoopStmts) static
Collect the loop statements (ForStmt or CXXRangeForStmt) of the affected loop of a construct.
Definition at line 14098 of file SemaOpenMP.cpp.
References clang::OMPLoopBasedDirective::doForAllLoops().
filterLookupForUDReductionAndMapper()
template<typename T , typename U > static T filterLookupForUDReductionAndMapper (SmallVectorImpl< U > & Lookups, const llvm::function_ref< T(ValueDecl *)> Gen) static
Definition at line 17478 of file SemaOpenMP.cpp.
References D, clang::Set, and clang::T.
findAcceptableDecl()
static NamedDecl* findAcceptableDecl (Sema & SemaRef, NamedDecl * D) static
Definition at line 17489 of file SemaOpenMP.cpp.
References D, clang::LookupResult::isVisible(), and clang::Decl::redecls().
Referenced by argumentDependentLookup().
findOMPAllocatorHandleT()
static bool findOMPAllocatorHandleT (Sema & S, SourceLocation Loc, DSAStackTy * Stack) static
Tries to find omp_allocator_handle_t type.
Definition at line 15181 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPAllocatorClause().
findOMPAlloctraitT()
static bool findOMPAlloctraitT (Sema & S, SourceLocation Loc, DSAStackTy * Stack) static
Tries to find omp_alloctrait_t type.
Definition at line 22609 of file SemaOpenMP.cpp.
findOMPDependT()
static bool findOMPDependT (Sema & S, SourceLocation Loc, DSAStackTy * Stack, bool Diagnose = true) static
Tries to find omp_depend_t. type.
Definition at line 19270 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPDependClause(), and clang::SemaOpenMP::ActOnOpenMPDepobjClause().
findOMPEventHandleT()
static bool findOMPEventHandleT (Sema & S, SourceLocation Loc, DSAStackTy * Stack) static
Tries to find omp_event_handle_t type.
Definition at line 21512 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPDetachClause().
finishLinearClauses()
static bool finishLinearClauses (Sema & SemaRef, ArrayRef< OMPClause * > Clauses, OMPLoopBasedDirective::HelperExprs & B, DSAStackTy * Stack) static
Definition at line 3016 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPForDirective(), clang::SemaOpenMP::ActOnOpenMPForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), and clang::SemaOpenMP::ActOnOpenMPTeamsDistributeSimdDirective().
FinishOpenMPLinearClause()
static bool FinishOpenMPLinearClause (OMPLinearClause & Clause, DeclRefExpr * IV, Expr * NumIterations, Sema & SemaRef, Scope * S, DSAStackTy * Stack) static
Definition at line 18870 of file SemaOpenMP.cpp.
fitsInto()
static bool fitsInto (unsigned Bits, bool Signed, const Expr * E, Sema & SemaRef) static
Check if the given expression E is a constant integer that fits into Bits bits.
Definition at line 9479 of file SemaOpenMP.cpp.
References clang::Sema::Context, E, clang::Expr::getIntegerConstantExpr(), and clang::Signed.
getAllocatorKind()
static OMPAllocateDeclAttr::AllocatorTypeTy getAllocatorKind (Sema & S, DSAStackTy * Stack, Expr * Allocator) static
Definition at line 3340 of file SemaOpenMP.cpp.
getCanonicalDecl() [1/2]
static const ValueDecl* getCanonicalDecl (const ValueDecl * D) static
Definition at line 1274 of file SemaOpenMP.cpp.
References D, clang::VarDecl::getCanonicalDecl(), clang::FieldDecl::getCanonicalDecl(), and getExprAsWritten().
Referenced by getCanonicalDecl(), clang::SemaOpenMP::isOpenMPCapturedDecl(), and clang::SemaOpenMP::setOpenMPCaptureKind().
getCanonicalDecl() [2/2]
static ValueDecl* getCanonicalDecl (ValueDecl * D) static
Definition at line 1291 of file SemaOpenMP.cpp.
References D, and getCanonicalDecl().
getCollapseNumberExpr()
static Expr* getCollapseNumberExpr (ArrayRef< OMPClause * > Clauses) static
Definition at line 10264 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPForDirective(), clang::SemaOpenMP::ActOnOpenMPForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeSimdDirective(), and clang::SemaOpenMP::ActOnOpenMPTeamsGenericLoopDirective().
getDirectCallExpr()
static Expr* getDirectCallExpr (Expr * E) static
Definition at line 10493 of file SemaOpenMP.cpp.
References E, clang::Expr::IgnoreImplicit(), and clang::Expr::IgnoreParenCasts().
getExprAsWritten() [1/2]
static const Expr* getExprAsWritten (const Expr * E) static
Definition at line 1255 of file SemaOpenMP.cpp.
References E, and clang::Expr::IgnoreParens().
Referenced by getCanonicalDecl(), and getExprAsWritten().
getExprAsWritten() [2/2]
static Expr* getExprAsWritten (Expr * E) static
Definition at line 1270 of file SemaOpenMP.cpp.
References E, and getExprAsWritten().
getListOfPossibleValues()
static std::string getListOfPossibleValues (OpenMPClauseKind K, unsigned First, unsigned Last, ArrayRef< unsigned > Exclude = std::nullopt) static
Definition at line 15423 of file SemaOpenMP.cpp.
References clang::First, clang::getOpenMPSimpleClauseTypeName(), and clang::Last.
Referenced by clang::SemaOpenMP::ActOnOpenMPAtClause(), clang::SemaOpenMP::ActOnOpenMPAtomicDefaultMemOrderClause(), clang::SemaOpenMP::ActOnOpenMPBindClause(), clang::SemaOpenMP::ActOnOpenMPDefaultClause(), clang::SemaOpenMP::ActOnOpenMPDependClause(), clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPGrainsizeClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPNumTasksClause(), clang::SemaOpenMP::ActOnOpenMPOrderClause(), clang::SemaOpenMP::ActOnOpenMPProcBindClause(), clang::SemaOpenMP::ActOnOpenMPReductionClause(), clang::SemaOpenMP::ActOnOpenMPScheduleClause(), clang::SemaOpenMP::ActOnOpenMPSeverityClause(), and clang::SemaOpenMP::ActOnOpenMPUpdateClause().
getMapClauseKindFromModifier()
static OpenMPMapClauseKind getMapClauseKindFromModifier (OpenMPDefaultmapClauseModifier M, bool IsAggregateOrDeclareTarget) static
Definition at line 3684 of file SemaOpenMP.cpp.
References Kind, clang::OMPC_DEFAULTMAP_MODIFIER_last, clang::OMPC_DEFAULTMAP_MODIFIER_unknown, and clang::OMPC_MAP_unknown.
getOpenMPCaptureRegionForClause()
static OpenMPDirectiveKind getOpenMPCaptureRegionForClause (OpenMPDirectiveKind DKind, OpenMPClauseKind CKind, unsigned OpenMPVersion, OpenMPDirectiveKind NameModifier = OMPD_unknown) static
Definition at line 14808 of file SemaOpenMP.cpp.
References E, End, clang::getOpenMPCaptureRegions(), and clang::isOpenMPCapturingDirective().
Referenced by clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPDistScheduleClause(), clang::SemaOpenMP::ActOnOpenMPFilterClause(), clang::SemaOpenMP::ActOnOpenMPFinalClause(), clang::SemaOpenMP::ActOnOpenMPIfClause(), clang::SemaOpenMP::ActOnOpenMPNocontextClause(), clang::SemaOpenMP::ActOnOpenMPNovariantsClause(), clang::SemaOpenMP::ActOnOpenMPNumTeamsClause(), clang::SemaOpenMP::ActOnOpenMPNumThreadsClause(), clang::SemaOpenMP::ActOnOpenMPScheduleClause(), clang::SemaOpenMP::ActOnOpenMPThreadLimitClause(), clang::SemaOpenMP::ActOnOpenMPXDynCGroupMemClause(), and isNonNegativeIntegerValue().
getOrderedNumberExpr()
static Expr* getOrderedNumberExpr (ArrayRef< OMPClause * > Clauses) static
Definition at line 10272 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPForDirective(), clang::SemaOpenMP::ActOnOpenMPForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective(), and clang::SemaOpenMP::ActOnOpenMPTargetSimdDirective().
getParallelRegionParams()
static SmallVector<SemaOpenMP::CapturedParamNameType> getParallelRegionParams (Sema & SemaRef, bool LoopBoundSharing) static
Definition at line 4240 of file SemaOpenMP.cpp.
Referenced by getTeamsRegionParams(), and processCapturedRegions().
getPrivateItem()
static std::pair< ValueDecl *, bool > getPrivateItem (Sema & S, Expr *& RefExpr, SourceLocation & ELoc, SourceRange & ERange, bool AllowArraySection = false, StringRef DiagType = "") static
Definition at line 5147 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPAlignedClause(), clang::SemaOpenMP::ActOnOpenMPCopyprivateClause(), clang::SemaOpenMP::ActOnOpenMPExclusiveClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPHasDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPInclusiveClause(), clang::SemaOpenMP::ActOnOpenMPInteropDirective(), clang::SemaOpenMP::ActOnOpenMPIsDevicePtrClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPNontemporalClause(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPSharedClause(), clang::SemaOpenMP::ActOnOpenMPUseDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPUseDevicePtrClause(), clang::SemaOpenMP::EndOpenMPDSABlock(), getTeamsReductionVars(), and isValidInteropVariable().
getRelatedCompoundReductionOp()
static BinaryOperatorKind getRelatedCompoundReductionOp (BinaryOperatorKind BOK) static
Definition at line 17843 of file SemaOpenMP.cpp.
getTargetRegionParams()
static SmallVector<SemaOpenMP::CapturedParamNameType> getTargetRegionParams (Sema & SemaRef) static
Definition at line 4291 of file SemaOpenMP.cpp.
Referenced by processCapturedRegions().
getTaskloopRegionParams()
static SmallVector<SemaOpenMP::CapturedParamNameType> getTaskloopRegionParams (Sema & SemaRef) static
Definition at line 4312 of file SemaOpenMP.cpp.
Referenced by processCapturedRegions().
getTaskRegionParams()
static SmallVector<SemaOpenMP::CapturedParamNameType> getTaskRegionParams (Sema & SemaRef) static
Definition at line 4267 of file SemaOpenMP.cpp.
Referenced by processCapturedRegions().
getTeamsRegionParams()
static SmallVector<SemaOpenMP::CapturedParamNameType> getTeamsRegionParams (Sema & SemaRef) static
Definition at line 4262 of file SemaOpenMP.cpp.
References getParallelRegionParams().
Referenced by processCapturedRegions().
getUnknownRegionParams()
static SmallVector<SemaOpenMP::CapturedParamNameType> getUnknownRegionParams (Sema & SemaRef) static
Definition at line 4304 of file SemaOpenMP.cpp.
Referenced by processCapturedRegions().
getVariableCategoryFromDecl()
static OpenMPDefaultmapClauseKind getVariableCategoryFromDecl (const LangOptions & LO, const ValueDecl * VD) static
Definition at line 2120 of file SemaOpenMP.cpp.
References clang::QualType::getNonReferenceType(), clang::ValueDecl::getType(), clang::Type::isAnyPointerType(), and clang::Type::isScalarType().
Referenced by clang::SemaOpenMP::isOpenMPCapturedByRef(), and clang::SemaOpenMP::setOpenMPCaptureKind().
handleDeclareVariantConstructTrait()
static void handleDeclareVariantConstructTrait (DSAStackTy * Stack, OpenMPDirectiveKind DKind, bool ScopeEntry) static
Definition at line 4222 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPRegionStart().
hasClauses() [1/2]
static bool hasClauses (ArrayRef< OMPClause * > Clauses, const OpenMPClauseKind K) static
Check for existence of a map clause in the list of clauses.
Definition at line 12990 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPInteropDirective(), clang::SemaOpenMP::ActOnOpenMPTargetDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetEnterDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetExitDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPTargetUpdateDirective(), and hasClauses().
hasClauses() [2/2]
template<typename... Params> static bool hasClauses (ArrayRef< OMPClause * > Clauses, const OpenMPClauseKind K, const Params... ClauseTypes) static
Definition at line 12997 of file SemaOpenMP.cpp.
References hasClauses().
isClauseMappable()
static bool isClauseMappable (ArrayRef< OMPClause * > Clauses) static
Check if the variables in the mapping clause are externally visible.
Definition at line 13003 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPTargetUpdateDirective().
isConstNotMutableType()
static bool isConstNotMutableType (Sema & SemaRef, QualType Type, bool AcceptIfMutable = true, bool * IsClassType = nullptr) static
Definition at line 1708 of file SemaOpenMP.cpp.
Referenced by isValidInteropVariable().
isNonNegativeIntegerValue()
static bool isNonNegativeIntegerValue (Expr *& ValExpr, Sema & SemaRef, OpenMPClauseKind CKind, bool StrictlyPositive, bool BuildCapture = false, OpenMPDirectiveKind DKind = OMPD_unknown, OpenMPDirectiveKind * CaptureRegion = nullptr, Stmt ** HelperValStmt = nullptr) static
Definition at line 15034 of file SemaOpenMP.cpp.
References buildPreInits(), clang::Sema::Context, clang::Sema::CurContext, clang::SemaBase::Diag(), clang::Sema::FullExprArg::get(), clang::Expr::getExprLoc(), clang::Expr::getIntegerConstantExpr(), getOpenMPCaptureRegionForClause(), clang::Stmt::getSourceRange(), clang::DeclContext::isDependentContext(), clang::Expr::isInstantiationDependent(), clang::Expr::isTypeDependent(), clang::Expr::isValueDependent(), clang::Sema::LangOpts, Loc, clang::Sema::MakeFullExpr(), clang::Sema::OpenMP(), and clang::SemaOpenMP::PerformOpenMPImplicitIntegerConversion().
Referenced by clang::SemaOpenMP::ActOnOpenMPDeviceClause(), clang::SemaOpenMP::ActOnOpenMPGrainsizeClause(), clang::SemaOpenMP::ActOnOpenMPNumTasksClause(), clang::SemaOpenMP::ActOnOpenMPNumTeamsClause(), clang::SemaOpenMP::ActOnOpenMPNumThreadsClause(), clang::SemaOpenMP::ActOnOpenMPPriorityClause(), clang::SemaOpenMP::ActOnOpenMPSizesClause(), clang::SemaOpenMP::ActOnOpenMPThreadLimitClause(), and clang::SemaOpenMP::ActOnOpenMPXDynCGroupMemClause().
isOpenMPDeviceDelayedContext()
static bool isOpenMPDeviceDelayedContext (Sema & S) static
Definition at line 2037 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::diagIfOpenMPDeviceCode().
isValidInteropVariable()
static bool isValidInteropVariable (Sema & SemaRef, Expr * InteropVarExpr, SourceLocation VarLoc, OpenMPClauseKind Kind) static
Definition at line 16329 of file SemaOpenMP.cpp.
References clang::Sema::Context, clang::SemaBase::Diag(), clang::IdentifierTable::get(), clang::Sema::getCurScope(), getPrivateItem(), clang::Expr::getType(), clang::QualType::getUnqualifiedType(), clang::ASTContext::hasSameType(), clang::ASTContext::Idents, isConstNotMutableType(), Kind, clang::Sema::LookupName(), and clang::Sema::LookupOrdinaryName.
Referenced by clang::SemaOpenMP::ActOnOpenMPDestroyClause(), clang::SemaOpenMP::ActOnOpenMPInitClause(), and clang::SemaOpenMP::ActOnOpenMPUseClause().
precomputeExpr()
static VarDecl* precomputeExpr (Sema & Actions, SmallVectorImpl< Stmt * > & BodyStmts, Expr * E, StringRef Name) static
Definition at line 5374 of file SemaOpenMP.cpp.
Referenced by buildDistanceFunc().
processCapturedRegions()
static void processCapturedRegions (Sema & SemaRef, OpenMPDirectiveKind DKind, Scope * CurScope, SourceLocation Loc) static
Definition at line 4345 of file SemaOpenMP.cpp.
References clang::Sema::ActOnCapturedRegionStart(), clang::CR_OpenMP, clang::Sema::getASTContext(), clang::Sema::getCurCapturedRegion(), clang::getOpenMPCaptureRegions(), getParallelRegionParams(), getTargetRegionParams(), getTaskloopRegionParams(), getTaskRegionParams(), getTeamsRegionParams(), getUnknownRegionParams(), clang::isOpenMPLoopBoundSharingDirective(), and Loc.
Referenced by clang::SemaOpenMP::ActOnOpenMPRegionStart().
processImplicitMapsWithDefaultMappers()
static void processImplicitMapsWithDefaultMappers (Sema & S, DSAStackTy * Stack, SmallVectorImpl< OMPClause * > & Clauses) static
Perform DFS through the structure/class data members trying to find member(s) with user-defined 'default' mapper and generate implicit map clauses for such members with the found 'default' mapper.
Definition at line 5780 of file SemaOpenMP.cpp.
ProcessOpenMPDoacrossClauseCommon()
static DoacrossDataInfoTy ProcessOpenMPDoacrossClauseCommon (Sema & SemaRef, bool IsSource, ArrayRef< Expr * > VarList, DSAStackTy * Stack, SourceLocation EndLoc) static
Definition at line 19328 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPDependClause(), and clang::SemaOpenMP::ActOnOpenMPDoacrossClause().
rejectConstNotMutableType()
static bool rejectConstNotMutableType (Sema & SemaRef, const ValueDecl * D, QualType Type, OpenMPClauseKind CKind, SourceLocation ELoc, bool AcceptIfMutable = true, bool ListItemNotVar = false) static
Definition at line 1727 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), and clang::SemaOpenMP::CheckOpenMPLinearDecl().
reportOriginalDsa()
static void reportOriginalDsa (Sema & SemaRef, const DSAStackTy * Stack, const ValueDecl * D, const DSAStackTy::DSAVarData & DVar, bool IsLoopIterVar = false) static
Definition at line 3626 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPCopyprivateClause(), clang::SemaOpenMP::ActOnOpenMPDetachClause(), clang::SemaOpenMP::ActOnOpenMPFirstprivateClause(), clang::SemaOpenMP::ActOnOpenMPHasDeviceAddrClause(), clang::SemaOpenMP::ActOnOpenMPIsDevicePtrClause(), clang::SemaOpenMP::ActOnOpenMPLastprivateClause(), clang::SemaOpenMP::ActOnOpenMPLinearClause(), clang::SemaOpenMP::ActOnOpenMPLoopInitialization(), clang::SemaOpenMP::ActOnOpenMPPrivateClause(), clang::SemaOpenMP::ActOnOpenMPSharedClause(), clang::SemaOpenMP::checkDeclIsAllowedInOpenMPTarget(), checkMappableExpressionList(), and clang::SemaOpenMP::EndOpenMPDSABlock().
setBranchProtectedScope()
static CapturedStmt* setBranchProtectedScope (Sema & SemaRef, OpenMPDirectiveKind DKind, Stmt * AStmt) static
Definition at line 7664 of file SemaOpenMP.cpp.
References clang::CapturedStmt::getCapturedDecl(), clang::CapturedStmt::getCapturedStmt(), clang::SemaOpenMP::getOpenMPCaptureLevels(), clang::Sema::OpenMP(), clang::Sema::setFunctionHasBranchProtectedScope(), and clang::CapturedDecl::setNothrow().
Referenced by clang::SemaOpenMP::ActOnOpenMPDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMaskedTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopDirective(), clang::SemaOpenMP::ActOnOpenMPParallelMasterTaskLoopSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetDirective(), clang::SemaOpenMP::ActOnOpenMPTargetEnterDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetExitDataDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetParallelGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsDistributeSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTargetTeamsGenericLoopDirective(), clang::SemaOpenMP::ActOnOpenMPTargetUpdateDirective(), clang::SemaOpenMP::ActOnOpenMPTaskDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeParallelForSimdDirective(), clang::SemaOpenMP::ActOnOpenMPTeamsDistributeSimdDirective(), and clang::SemaOpenMP::ActOnOpenMPTeamsGenericLoopDirective().
setPrototype()
static void setPrototype (Sema & S, FunctionDecl * FD, FunctionDecl * FDWithProto, QualType NewType) static
Definition at line 7014 of file SemaOpenMP.cpp.
teamsLoopCanBeParallelFor()
static bool teamsLoopCanBeParallelFor (Stmt * AStmt, Sema & SemaRef) static
Definition at line 5977 of file SemaOpenMP.cpp.
Referenced by clang::SemaOpenMP::ActOnOpenMPTargetTeamsGenericLoopDirective().
widenIterationCount()
static ExprResult widenIterationCount (unsigned Bits, Expr * E, Sema & SemaRef) static
Convert integer expression E to make it have at least Bits bits.
Definition at line 9463 of file SemaOpenMP.cpp.
References clang::Sema::AA_Converting, clang::Sema::Context, E, clang::ExprError(), clang::Expr::getType(), and clang::Sema::PerformImplicitConversion().