clang: lib/Sema/SemaHLSL.cpp File Reference
SemaHLSL.cpp File Reference
#include "clang/Sema/SemaHLSL.h"
#include "clang/AST/Decl.h"
#include "clang/AST/Expr.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Basic/DiagnosticSema.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/ParsedAttr.h"
#include "clang/Sema/Sema.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/TargetParser/Triple.h"
#include <iterator>
Functions
static unsigned calculateLegacyCbufferSize (const ASTContext &Context, QualType T)
static bool isLegalTypeForHLSLSV_DispatchThreadID (QualType T)
bool CheckVectorElementCallArgs (Sema *S, CallExpr *TheCall)
bool CheckArgsTypesAreCorrect (Sema *S, CallExpr *TheCall, QualType ExpectedType, llvm::function_ref< bool(clang::QualType PassedType)> Check)
bool CheckAllArgsHaveFloatRepresentation (Sema *S, CallExpr *TheCall)
bool CheckFloatOrHalfRepresentations (Sema *S, CallExpr *TheCall)
bool CheckNoDoubleVectors (Sema *S, CallExpr *TheCall)
bool CheckUnsignedIntRepresentation (Sema *S, CallExpr *TheCall)
void SetElementTypeAsReturnType (Sema *S, CallExpr *TheCall, QualType ReturnType)
Function Documentation
calculateLegacyCbufferSize()
static unsigned calculateLegacyCbufferSize (const ASTContext & Context, QualType T) static
Definition at line 49 of file SemaHLSL.cpp.
CheckAllArgsHaveFloatRepresentation()
bool CheckAllArgsHaveFloatRepresentation (Sema * S, CallExpr * TheCall)
Definition at line 966 of file SemaHLSL.cpp.
Referenced by clang::SemaHLSL::CheckBuiltinFunctionCall().
CheckArgsTypesAreCorrect()
bool CheckArgsTypesAreCorrect (Sema * S, CallExpr * TheCall, QualType ExpectedType, llvm::function_ref< bool(clang::QualType PassedType)> Check)
Definition at line 948 of file SemaHLSL.cpp.
CheckFloatOrHalfRepresentations()
bool CheckFloatOrHalfRepresentations (Sema * S, CallExpr * TheCall)
Definition at line 974 of file SemaHLSL.cpp.
Referenced by clang::SemaHLSL::CheckBuiltinFunctionCall().
CheckNoDoubleVectors()
bool CheckNoDoubleVectors (Sema * S, CallExpr * TheCall)
Definition at line 986 of file SemaHLSL.cpp.
Referenced by clang::SemaHLSL::CheckBuiltinFunctionCall().
CheckUnsignedIntRepresentation()
bool CheckUnsignedIntRepresentation (Sema * S, CallExpr * TheCall)
Definition at line 996 of file SemaHLSL.cpp.
Referenced by clang::SemaHLSL::CheckBuiltinFunctionCall().
CheckVectorElementCallArgs()
bool CheckVectorElementCallArgs (Sema * S, CallExpr * TheCall)
Definition at line 898 of file SemaHLSL.cpp.
Referenced by clang::SemaHLSL::CheckBuiltinFunctionCall().
isLegalTypeForHLSLSV_DispatchThreadID()
static bool isLegalTypeForHLSLSV_DispatchThreadID (QualType T) static
Definition at line 351 of file SemaHLSL.cpp.
References clang::Type::getAs(), clang::Type::hasUnsignedIntegerRepresentation(), and clang::T.
Referenced by clang::SemaHLSL::handleSV_DispatchThreadIDAttr().
SetElementTypeAsReturnType()
void SetElementTypeAsReturnType (Sema * S, CallExpr * TheCall, QualType ReturnType)
Definition at line 1004 of file SemaHLSL.cpp.
Referenced by clang::SemaHLSL::CheckBuiltinFunctionCall().