clang: lib/Sema/SemaStmtAttr.cpp File Reference
SemaStmtAttr.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/EvaluatedExprVisitor.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Sema/DelayedDiagnostic.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaInternal.h"
#include "llvm/ADT/StringExtras.h"
#include <optional>
#include "clang/Sema/AttrParsedAttrImpl.inc"
Macros
#define WANT_STMT_MERGE_LOGIC
Enumerations
enum class IVDepExprResult {
Invalid , Null , Dependent , Array ,
SafeLen
}
Functions
static Attr * handleFallThroughAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleSuppressAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleSYCLIntelMaxConcurrencyAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static Attr * handleSYCLIntelInitiationIntervalAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static Attr * handleSYCLIntelMaxInterleavingAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static Attr * handleSYCLIntelLoopCoalesceAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static Attr * handleSYCLIntelSpeculatedIterationsAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static Attr * handleSYCLIntelDisableLoopPipeliningAttr (Sema &S, Stmt *, const ParsedAttr &A)
static bool checkSYCLIntelIVDepSafeLen (Sema &S, llvm::APSInt &Value, Expr *E)
static IVDepExprResult HandleIVDepAttrExpr (Sema &S, Expr *E, unsigned &SafelenValue)
template<typename T >
static void FilterAttributeList (ArrayRef< const Attr * > Attrs, SmallVectorImpl< const T * > &FilteredAttrs)
static void CheckRedundantSYCLIntelIVDepAttrs (Sema &S, ArrayRef< const Attr * > Attrs)
static Attr * handleIntelIVDepAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static void CheckForDuplicateSYCLIntelLoopCountAttrs (Sema &S, ArrayRef< const Attr * > Attrs)
static Attr * handleSYCLIntelLoopCountAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static Attr * handleIntelNofusionAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static Attr * handleSYCLIntelMaxReinvocationDelayAttr (Sema &S, Stmt *St, const ParsedAttr &A)
static Attr * handleSYCLIntelEnableLoopPipeliningAttr (Sema &S, Stmt *, const ParsedAttr &A)
static Attr * handleLoopHintAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange)
static Attr * handleNoMergeAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
template<typename OtherAttr , int DiagIdx>
static bool CheckStmtInlineAttr (Sema &SemaRef, const Stmt *OrigSt, const Stmt *CurSt, const AttributeCommonInfo &A)
static Attr * handleNoInlineAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleAlwaysInlineAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleCXXAssumeAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleMustTailAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleLikely (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleUnlikely (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * handleCodeAlignAttr (Sema &S, Stmt *St, const ParsedAttr &A)
template<typename LoopAttrT >
static void CheckForDuplicateLoopAttrs (Sema &S, ArrayRef< const Attr * > Attrs)
static Attr * handleMSConstexprAttr (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static void CheckForIncompatibleAttributes (Sema &S, const SmallVectorImpl< const Attr * > &Attrs)
template<typename LoopAttrT >
static void CheckForDuplicationSYCLLoopAttribute (Sema &S, const SmallVectorImpl< const Attr * > &Attrs, bool isIntelFPGAAttr=true)
template<typename LoopAttrT >
static void CheckForDuplicateAttrs (Sema &S, ArrayRef< const Attr * > Attrs)
static void CheckForIncompatibleSYCLLoopAttributes (Sema &S, const SmallVectorImpl< const Attr * > &Attrs)
void CheckForIncompatibleUnrollHintAttributes (Sema &S, const SmallVectorImpl< const Attr * > &Attrs, SourceRange Range)
static bool CheckLoopUnrollAttrExpr (Sema &S, Expr *E, const AttributeCommonInfo &A, unsigned *UnrollFactor=nullptr)
static Attr * handleLoopUnrollHint (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
static Attr * ProcessStmtAttribute (Sema &S, Stmt *St, const ParsedAttr &A, SourceRange Range)
Macro Definition Documentation
WANT_STMT_MERGE_LOGIC
#define WANT_STMT_MERGE_LOGIC
Definition at line 849 of file SemaStmtAttr.cpp.
Enumeration Type Documentation
IVDepExprResult
enum IVDepExprResult strong
Enumerator
Invalid
Null
Dependent
Array
SafeLen
Definition at line 237 of file SemaStmtAttr.cpp.
Function Documentation
CheckForDuplicateAttrs()
template<typename LoopAttrT > static void CheckForDuplicateAttrs (Sema & S, ArrayRef< const Attr * > Attrs) static
Definition at line 997 of file SemaStmtAttr.cpp.
CheckForDuplicateLoopAttrs()
template<typename LoopAttrT > static void CheckForDuplicateLoopAttrs (Sema & S, ArrayRef< const Attr * > Attrs) static
Definition at line 801 of file SemaStmtAttr.cpp.
CheckForDuplicateSYCLIntelLoopCountAttrs()
static void CheckForDuplicateSYCLIntelLoopCountAttrs (Sema & S, ArrayRef< const Attr * > Attrs) static
Definition at line 395 of file SemaStmtAttr.cpp.
CheckForDuplicationSYCLLoopAttribute()
template<typename LoopAttrT > static void CheckForDuplicationSYCLLoopAttribute (Sema & S, const SmallVectorImpl< const Attr * > & Attrs, bool isIntelFPGAAttr = true) static
Definition at line 975 of file SemaStmtAttr.cpp.
CheckForIncompatibleAttributes()
static void CheckForIncompatibleAttributes (Sema & S, const SmallVectorImpl< const Attr * > & Attrs) static
Definition at line 854 of file SemaStmtAttr.cpp.
CheckForIncompatibleSYCLLoopAttributes()
static void CheckForIncompatibleSYCLLoopAttributes (Sema & S, const SmallVectorImpl< const Attr * > & Attrs) static
Definition at line 1035 of file SemaStmtAttr.cpp.
CheckForIncompatibleUnrollHintAttributes()
void CheckForIncompatibleUnrollHintAttributes (Sema & S, const SmallVectorImpl< const Attr * > & Attrs, SourceRange Range)
Definition at line 1053 of file SemaStmtAttr.cpp.
CheckLoopUnrollAttrExpr()
static bool CheckLoopUnrollAttrExpr (Sema & S, Expr * E, const AttributeCommonInfo & A, unsigned * UnrollFactor = nullptr) static
Definition at line 1080 of file SemaStmtAttr.cpp.
Referenced by clang::Sema::BuildLoopUnrollHintAttr(), and clang::Sema::BuildOpenCLLoopUnrollHintAttr().
CheckRedundantSYCLIntelIVDepAttrs()
static void CheckRedundantSYCLIntelIVDepAttrs (Sema & S, ArrayRef< const Attr * > Attrs) static
Definition at line 329 of file SemaStmtAttr.cpp.
Referenced by clang::Sema::CheckRebuiltAttributedStmtAttributes().
CheckStmtInlineAttr()
template<typename OtherAttr , int DiagIdx> static bool CheckStmtInlineAttr (Sema & SemaRef, const Stmt * OrigSt, const Stmt * CurSt, const AttributeCommonInfo & A) static
Definition at line 650 of file SemaStmtAttr.cpp.
References clang::SemaBase::Diag(), and clang::Stmt::getBeginLoc().
checkSYCLIntelIVDepSafeLen()
static bool checkSYCLIntelIVDepSafeLen (Sema & S, llvm::APSInt & Value, Expr * E) static
Definition at line 227 of file SemaStmtAttr.cpp.
FilterAttributeList()
template<typename T > static void FilterAttributeList (ArrayRef< const Attr * > Attrs, SmallVectorImpl< const T * > & FilteredAttrs) static
Definition at line 314 of file SemaStmtAttr.cpp.
References clang::interp::Cast(), clang::transformer::remove(), and clang::T.
handleAlwaysInlineAttr()
static Attr* handleAlwaysInlineAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 717 of file SemaStmtAttr.cpp.
handleCodeAlignAttr()
static Attr* handleCodeAlignAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 792 of file SemaStmtAttr.cpp.
handleCXXAssumeAttr()
static Attr* handleCXXAssumeAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 732 of file SemaStmtAttr.cpp.
handleFallThroughAttr()
static Attr* handleFallThroughAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 27 of file SemaStmtAttr.cpp.
handleIntelIVDepAttr()
static Attr* handleIntelIVDepAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 384 of file SemaStmtAttr.cpp.
handleIntelNofusionAttr()
static Attr* handleIntelNofusionAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 453 of file SemaStmtAttr.cpp.
HandleIVDepAttrExpr()
static IVDepExprResult HandleIVDepAttrExpr (Sema & S, Expr * E, unsigned & SafelenValue) static
Definition at line 245 of file SemaStmtAttr.cpp.
Referenced by clang::Sema::BuildSYCLIntelIVDepAttr().
handleLikely()
static Attr* handleLikely (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 747 of file SemaStmtAttr.cpp.
handleLoopHintAttr()
static Attr* handleLoopHintAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange) static
Definition at line 492 of file SemaStmtAttr.cpp.
handleLoopUnrollHint()
static Attr* handleLoopUnrollHint (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 1116 of file SemaStmtAttr.cpp.
handleMSConstexprAttr()
static Attr* handleMSConstexprAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 839 of file SemaStmtAttr.cpp.
handleMustTailAttr()
static Attr* handleMustTailAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 741 of file SemaStmtAttr.cpp.
handleNoInlineAttr()
static Attr* handleNoInlineAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 702 of file SemaStmtAttr.cpp.
handleNoMergeAttr()
static Attr* handleNoMergeAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 635 of file SemaStmtAttr.cpp.
handleSuppressAttr()
static Attr* handleSuppressAttr (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 54 of file SemaStmtAttr.cpp.
handleSYCLIntelDisableLoopPipeliningAttr()
static Attr* handleSYCLIntelDisableLoopPipeliningAttr (Sema & S, Stmt * , const ParsedAttr & A) static
Definition at line 221 of file SemaStmtAttr.cpp.
handleSYCLIntelEnableLoopPipeliningAttr()
static Attr* handleSYCLIntelEnableLoopPipeliningAttr (Sema & S, Stmt * , const ParsedAttr & A) static
Definition at line 487 of file SemaStmtAttr.cpp.
handleSYCLIntelInitiationIntervalAttr()
static Attr* handleSYCLIntelInitiationIntervalAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 127 of file SemaStmtAttr.cpp.
handleSYCLIntelLoopCoalesceAttr()
static Attr* handleSYCLIntelLoopCoalesceAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 184 of file SemaStmtAttr.cpp.
handleSYCLIntelLoopCountAttr()
static Attr* handleSYCLIntelLoopCountAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 445 of file SemaStmtAttr.cpp.
handleSYCLIntelMaxConcurrencyAttr()
static Attr* handleSYCLIntelMaxConcurrencyAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 98 of file SemaStmtAttr.cpp.
handleSYCLIntelMaxInterleavingAttr()
static Attr* handleSYCLIntelMaxInterleavingAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 155 of file SemaStmtAttr.cpp.
handleSYCLIntelMaxReinvocationDelayAttr()
static Attr* handleSYCLIntelMaxReinvocationDelayAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 479 of file SemaStmtAttr.cpp.
handleSYCLIntelSpeculatedIterationsAttr()
static Attr* handleSYCLIntelSpeculatedIterationsAttr (Sema & S, Stmt * St, const ParsedAttr & A) static
Definition at line 213 of file SemaStmtAttr.cpp.
handleUnlikely()
static Attr* handleUnlikely (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 756 of file SemaStmtAttr.cpp.
ProcessStmtAttribute()
static Attr* ProcessStmtAttribute (Sema & S, Stmt * St, const ParsedAttr & A, SourceRange Range) static
Definition at line 1133 of file SemaStmtAttr.cpp.