clang: lib/Sema/SemaExpr.cpp File Reference
SemaExpr.cpp File Reference
#include "TreeTransform.h"
#include "UsedDeclVisitor.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/ASTMutationListener.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/EvaluatedExprVisitor.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/ExprOpenMP.h"
#include "clang/AST/OperationKinds.h"
#include "clang/AST/ParentMapContext.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/DiagnosticSema.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Basic/TypeTraits.h"
#include "clang/Lex/LiteralSupport.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/AnalysisBasedWarnings.h"
#include "clang/Sema/DeclSpec.h"
#include "clang/Sema/DelayedDiagnostic.h"
#include "clang/Sema/Designator.h"
#include "clang/Sema/EnterExpressionEvaluationContext.h"
#include "clang/Sema/Initialization.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/Overload.h"
#include "clang/Sema/ParsedTemplate.h"
#include "clang/Sema/Scope.h"
#include "clang/Sema/ScopeInfo.h"
#include "clang/Sema/SemaCUDA.h"
#include "clang/Sema/SemaFixItUtils.h"
#include "clang/Sema/SemaInternal.h"
#include "clang/Sema/SemaOpenMP.h"
#include "clang/Sema/Template.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/STLForwardCompat.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/TypeSize.h"
#include <optional>
#include "clang/AST/DeclNodes.inc"
#include "clang/AST/TypeNodes.inc"
#include "clang/Basic/OpenCLImageTypes.def"
#include "clang/Basic/OpenCLExtensionTypes.def"
#include "clang/Basic/AArch64SVEACLETypes.def"
#include "clang/Basic/PPCTypes.def"
#include "clang/Basic/RISCVVTypes.def"
#include "clang/Basic/WebAssemblyReferenceTypes.def"
#include "clang/AST/BuiltinTypes.def"
Classes
struct ImmediateCallVisitor
struct EnsureImmediateInvocationInDefaultArgs
Macros
#define ABSTRACT_DECL(kind)
#define VALUE(type, base)
#define DECL(type, base) case Decl::type:
#define TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base) case Type::Class:
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE(Class, Base)
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Id:
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Sampled##Id:
#define IMAGE_WRITE_TYPE(Type, Id, Ext)
#define IMAGE_READ_WRITE_TYPE(Type, Id, Ext)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext) case BuiltinType::Id:
#define SVE_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define PPC_VECTOR_TYPE(Name, Id, Size) case BuiltinType::Id:
#define RVV_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define WASM_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define PLACEHOLDER_TYPE(ID, SINGLETON_ID)
#define BUILTIN_TYPE(ID, SINGLETON_ID) case BuiltinType::ID:
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Id:
#define IMAGE_TYPE(ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Sampled##Id:
#define IMAGE_WRITE_TYPE(Type, Id, Ext)
#define IMAGE_READ_WRITE_TYPE(Type, Id, Ext)
#define EXT_OPAQUE_TYPE(ExtType, Id, Ext) case BuiltinType::Id:
#define SVE_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define PPC_VECTOR_TYPE(Name, Id, Size) case BuiltinType::Id:
#define RVV_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define WASM_TYPE(Name, Id, SingletonId) case BuiltinType::Id:
#define BUILTIN_TYPE(Id, SingletonId) case BuiltinType::Id:
#define PLACEHOLDER_TYPE(Id, SingletonId)
Typedefs
typedef ExprResult PerformCastFn(Sema &S, Expr *operand, QualType toType)
Enumerations
enum NonConstCaptureKind { NCCK_None , NCCK_Block , NCCK_Lambda }
Is the given expression (which must be 'const') a reference to a variable which was originally non-const, but which has become 'const' due to being captured within a block?
enum {
ConstFunction , ConstVariable , ConstMember , ConstMethod ,
NestedConstMember , ConstUnknown
}
enum OriginalExprKind { OEK_Variable , OEK_Member , OEK_LValue }
Functions
static void DiagnoseUnusedOfDecl (Sema &S, NamedDecl *D, SourceLocation Loc)
static bool hasAnyExplicitStorageClass (const FunctionDecl *D)
Determine whether a FunctionDecl was ever declared with an explicit storage class.
static void diagnoseUseOfInternalDeclInInlineFunction (Sema &S, const NamedDecl *D, SourceLocation Loc)
Check whether we're in an extern inline function and referring to a variable or function with internal linkage (C11 6.7.4p3).
static void CheckForNullPointerDereference (Sema &S, Expr *E)
static void DiagnoseDirectIsaAccess (Sema &S, const ObjCIvarRefExpr *OIRE, SourceLocation AssignLoc, const Expr *RHS)
static bool handleComplexIntegerToFloatConversion (Sema &S, ExprResult &IntExpr, ExprResult &ComplexExpr, QualType IntTy, QualType ComplexTy, bool SkipCast)
Convert complex integers to complex floats and real integers to real floats as required for complex arithmetic.
static QualType handleComplexFloatConversion (Sema &S, ExprResult &Shorter, QualType ShorterType, QualType LongerType, bool PromotePrecision)
static QualType handleComplexConversion (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType LHSType, QualType RHSType, bool IsCompAssign)
Handle arithmetic conversion with complex types.
static QualType handleIntToFloatConversion (Sema &S, ExprResult &FloatExpr, ExprResult &IntExpr, QualType FloatTy, QualType IntTy, bool ConvertFloat, bool ConvertInt)
Handle arithmetic conversion from integer to float.
static QualType handleFloatConversion (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType LHSType, QualType RHSType, bool IsCompAssign)
Handle arithmethic conversion with floating point types.
static bool unsupportedTypeConversion (const Sema &S, QualType LHSType, QualType RHSType)
Diagnose attempts to convert between __float128, __ibm128 and long double if there is no support for such conversion.
template<PerformCastFn doLHSCast, PerformCastFn doRHSCast>
static QualType handleIntegerConversion (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType LHSType, QualType RHSType, bool IsCompAssign)
Handle integer arithmetic conversions.
static QualType handleComplexIntConversion (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType LHSType, QualType RHSType, bool IsCompAssign)
Handle conversions with GCC complex int extension.
static unsigned GetFixedPointRank (QualType Ty)
Return the rank of a given fixed point or integer type.
static QualType handleFixedPointConversion (Sema &S, QualType LHSTy, QualType RHSTy)
handleFixedPointConversion - Fixed point operations between fixed point types and integers or other fixed point types do not fall under usual arithmetic conversion since these conversions could result in loss of precsision (N1169 4.1.4).
static void checkEnumArithmeticConversions (Sema &S, Expr *LHS, Expr *RHS, SourceLocation Loc, Sema::ArithConvKind ACK)
Check that the usual arithmetic conversions can be performed on this pair of expressions that might be of enumeration type.
static PredefinedIdentKind getPredefinedExprKind (tok::TokenKind Kind)
static Decl * getPredefinedExprDecl (DeclContext *DC)
getPredefinedExprDecl - Returns Decl of a given DeclContext that can be used to determine the value of a PredefinedExpr.
static SourceLocation getUDSuffixLoc (Sema &S, SourceLocation TokLoc, unsigned Offset)
getUDSuffixLoc - Create a SourceLocation for a ud-suffix, given the location of the token and the offset of the ud-suffix within it.
static ExprResult BuildCookedLiteralOperatorCall (Sema &S, Scope *Scope, IdentifierInfo *UDSuffix, SourceLocation UDSuffixLoc, ArrayRef< Expr * > Args, SourceLocation LitEndLoc)
BuildCookedLiteralOperatorCall - A user-defined literal was found.
static bool isCapturingReferenceToHostVarInCUDADeviceLambda (const Sema &S, VarDecl *VD)
static void emitEmptyLookupTypoDiagnostic (const TypoCorrection &TC, Sema &SemaRef, const CXXScopeSpec &SS, DeclarationName Typo, SourceLocation TypoLoc, ArrayRef< Expr * > Args, unsigned DiagnosticID, unsigned DiagnosticSuggestID)
static Expr * recoverFromMSUnqualifiedLookup (Sema &S, ASTContext &Context, DeclarationNameInfo &NameInfo, SourceLocation TemplateKWLoc, const TemplateArgumentListInfo *TemplateArgs)
In Microsoft mode, if we are inside a template class whose parent class has dependent base classes, and we can't resolve an unqualified identifier, then assume the identifier is a member of a dependent base class.
static bool CheckDeclInExpr (Sema &S, SourceLocation Loc, NamedDecl *D, bool AcceptInvalid)
Diagnoses obvious problems with the use of the given declaration as an expression.
static bool ShouldLookupResultBeMultiVersionOverload (const LookupResult &R)
static void diagnoseUncapturableValueReferenceOrBinding (Sema &S, SourceLocation loc, ValueDecl *var)
static void ConvertUTF8ToWideString (unsigned CharByteWidth, StringRef Source, SmallString< 32 > &Target)
static Expr * BuildFloatingLiteral (Sema &S, NumericLiteralParser &Literal, QualType Ty, SourceLocation Loc)
static bool CheckVecStepTraitOperandType (Sema &S, QualType T, SourceLocation Loc, SourceRange ArgRange)
static bool CheckVectorElementsTraitOperandType (Sema &S, QualType T, SourceLocation Loc, SourceRange ArgRange)
static bool CheckExtensionTraitOperandType (Sema &S, QualType T, SourceLocation Loc, SourceRange ArgRange, UnaryExprOrTypeTrait TraitKind)
static bool CheckObjCTraitOperandConstraints (Sema &S, QualType T, SourceLocation Loc, SourceRange ArgRange, UnaryExprOrTypeTrait TraitKind)
static void warnOnSizeofOnArrayDecay (Sema &S, SourceLocation Loc, QualType T, const Expr *E)
Check whether E is a pointer from a decayed array type (the decayed pointer type is equal to T) and emit a warning if it is.
static bool CheckAlignOfExpr (Sema &S, Expr *E, UnaryExprOrTypeTrait ExprKind)
static void captureVariablyModifiedType (ASTContext &Context, QualType T, CapturingScopeInfo *CSI)
static QualType CheckRealImagOperand (Sema &S, ExprResult &V, SourceLocation Loc, bool IsReal)
static bool checkArithmeticOnObjCPointer (Sema &S, SourceLocation opLoc, Expr *op)
Diagnose if arithmetic on the given ObjC pointer is illegal.
static bool isMSPropertySubscriptExpr (Sema &S, Expr *Base)
static QualType getDependentArraySubscriptType (Expr *LHS, Expr *RHS, const ASTContext &Ctx)
static TypoCorrection TryTypoCorrectionForCall (Sema &S, Expr *Fn, FunctionDecl *FDecl, ArrayRef< Expr * > Args)
static void DiagnoseCalleeStaticArrayParam (Sema &S, ParmVarDecl *PVD)
static ExprResult rebuildUnknownAnyFunction (Sema &S, Expr *fn)
Given a function expression of unknown-any type, try to rebuild it to have a function type.
static bool isPlaceholderToRemoveAsArg (QualType type)
Is the given type a placeholder that we need to lower out immediately during argument processing?
static FunctionDecl * rewriteBuiltinFunctionDecl (Sema *Sema, ASTContext &Context, FunctionDecl *FDecl, MultiExprArg ArgExprs)
If a builtin function has a pointer argument with no explicit address space, then it should be able to accept a pointer to any address space as input.
static void checkDirectCallValidity (Sema &S, const Expr *Fn, FunctionDecl *Callee, MultiExprArg ArgExprs)
static bool enclosingClassIsRelatedToClassInWhichMembersWereFound (const UnresolvedMemberExpr *const UME, Sema &S)
static void tryImplicitlyCaptureThisIfImplicitMemberFunctionAccessWithDependentArgs (Sema &S, const UnresolvedMemberExpr *const UME, SourceLocation CallLoc)
static void DiagnosedUnqualifiedCallsToStdFunctions (Sema &S, const CallExpr *Call)
static bool breakDownVectorType (QualType type, uint64_t &len, QualType &eltType)
static bool checkCondition (Sema &S, const Expr *Cond, SourceLocation QuestionLoc)
Return false if the condition expression is valid, true otherwise.
static bool checkConditionalNullPointer (Sema &S, ExprResult &NullExpr, QualType PointerTy)
Return false if the NullExpr can be promoted to PointerTy, true otherwise.
static QualType checkConditionalPointerCompatibility (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
Checks compatibility between two pointers and return the resulting type.
static QualType checkConditionalBlockPointerCompatibility (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
Return the resulting type when the operands are both block pointers.
static QualType checkConditionalObjectPointersCompatibility (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
Return the resulting type when the operands are both pointers.
static bool checkPointerIntegerMismatch (Sema &S, ExprResult &Int, Expr *PointerExpr, SourceLocation Loc, bool IsIntFirstExpr)
Return false if the first expression is not an integer and the second expression is not a pointer, true otherwise.
static QualType OpenCLArithmeticConversions (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation QuestionLoc)
Simple conversion between integer and floating point types.
static QualType OpenCLConvertScalarsToVectors (Sema &S, ExprResult &LHS, ExprResult &RHS, QualType CondTy, SourceLocation QuestionLoc)
Convert scalar operands to a vector that matches the condition in length.
static bool checkOpenCLConditionVector (Sema &S, Expr *Cond, SourceLocation QuestionLoc)
Return false if this is a valid OpenCL condition vector.
static bool checkVectorResult (Sema &S, QualType CondTy, QualType VecResTy, SourceLocation QuestionLoc)
Return false if the vector condition type and the vector result type are compatible.
static QualType OpenCLCheckVectorConditional (Sema &S, ExprResult &Cond, ExprResult &LHS, ExprResult &RHS, SourceLocation QuestionLoc)
Return the resulting type for the conditional operator in OpenCL (aka "ternary selection operator", OpenCL v1.1 s6.3.i) when the condition is a vector type.
static bool checkBlockType (Sema &S, const Expr *E)
Return true if the Expr is block type.
static void SuggestParentheses (Sema &Self, SourceLocation Loc, const PartialDiagnostic &Note, SourceRange ParenRange)
SuggestParentheses - Emit a note with a fixit hint that wraps ParenRange in parentheses.
static bool IsArithmeticOp (BinaryOperatorKind Opc)
static bool IsArithmeticBinaryExpr (const Expr *E, BinaryOperatorKind *Opcode, const Expr **RHSExprs)
IsArithmeticBinaryExpr - Returns true if E is an arithmetic binary expression, either using a built-in or overloaded operator, and sets *OpCode to the opcode and *RHSExprs to the right-hand side expression.
static bool ExprLooksBoolean (const Expr *E)
ExprLooksBoolean - Returns true if E looks boolean, i.e.
static void DiagnoseConditionalPrecedence (Sema &Self, SourceLocation OpLoc, Expr *Condition, const Expr *LHSExpr, const Expr *RHSExpr)
DiagnoseConditionalPrecedence - Emit a warning when a conditional operator and binary operator are mixed in a way that suggests the programmer assumed the conditional operator has higher precedence, for example: "int x = a + someBinaryCondition ? 1 : 2".
static QualType computeConditionalNullability (QualType ResTy, bool IsBin, QualType LHSTy, QualType RHSTy, ASTContext &Ctx)
Compute the nullability of a conditional expression.
static bool IsInvalidCmseNSCallConversion (Sema &S, QualType FromType, QualType ToType)
static Sema::AssignConvertType checkPointerTypesForAssignment (Sema &S, QualType LHSType, QualType RHSType, SourceLocation Loc)
static Sema::AssignConvertType checkBlockPointerTypesForAssignment (Sema &S, QualType LHSType, QualType RHSType)
checkBlockPointerTypesForAssignment - This routine determines whether two block pointer types are compatible or whether a block and normal pointer are compatible.
static Sema::AssignConvertType checkObjCPointerTypesForAssignment (Sema &S, QualType LHSType, QualType RHSType)
checkObjCPointerTypesForAssignment - Compares two objective-c pointer types for assignment compatibility.
static bool isVector (QualType QT, QualType ElementType)
This helper function returns true if QT is a vector type that has element type ElementType.
static void ConstructTransparentUnion (Sema &S, ASTContext &C, ExprResult &EResult, QualType UnionType, FieldDecl *Field)
Constructs a transparent union from an expression that is used to initialize the transparent union.
static bool tryVectorConvertAndSplat (Sema &S, ExprResult *scalar, QualType scalarTy, QualType vectorEltTy, QualType vectorTy, unsigned &DiagID)
Try to convert a value of non-vector type to a vector type by converting the type to the element type of the vector and then performing a splat.
static ExprResult convertVector (Expr *E, QualType ElementType, Sema &S)
Convert vector E to a vector with the same number of elements but different element type.
static bool canConvertIntToOtherIntTy (Sema &S, ExprResult *Int, QualType OtherIntTy)
Test if a (constant) integer Int can be casted to another integer type IntTy without losing precision.
static bool canConvertIntTyToFloatTy (Sema &S, ExprResult *Int, QualType FloatTy)
Test if a (constant) integer Int can be casted to floating point type FloatTy without losing precision.
static bool tryGCCVectorConvertAndSplat (Sema &S, ExprResult *Scalar, ExprResult *Vector)
Attempt to convert and splat Scalar into a vector whose types matches Vector following GCC conversion rules.
static void checkArithmeticNull (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, bool IsCompare)
static void DiagnoseDivisionSizeofPointerOrArray (Sema &S, Expr *LHS, Expr *RHS, SourceLocation Loc)
static void DiagnoseBadDivideOrRemainderValues (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, bool IsDiv)
static void diagnoseArithmeticOnTwoVoidPointers (Sema &S, SourceLocation Loc, Expr *LHSExpr, Expr *RHSExpr)
Diagnose invalid arithmetic on two void pointers.
static void diagnoseArithmeticOnVoidPointer (Sema &S, SourceLocation Loc, Expr *Pointer)
Diagnose invalid arithmetic on a void pointer.
static void diagnoseArithmeticOnNullPointer (Sema &S, SourceLocation Loc, Expr *Pointer, bool IsGNUIdiom)
Diagnose invalid arithmetic on a null pointer.
static void diagnoseSubtractionOnNullPointer (Sema &S, SourceLocation Loc, Expr *Pointer, bool BothNull)
Diagnose invalid subraction on a null pointer.
static void diagnoseArithmeticOnTwoFunctionPointers (Sema &S, SourceLocation Loc, Expr *LHS, Expr *RHS)
Diagnose invalid arithmetic on two function pointers.
static void diagnoseArithmeticOnFunctionPointer (Sema &S, SourceLocation Loc, Expr *Pointer)
Diagnose invalid arithmetic on a function pointer.
static bool checkArithmeticIncompletePointerType (Sema &S, SourceLocation Loc, Expr *Operand)
Emit error if Operand is incomplete pointer type.
static bool checkArithmeticOpPointerOperand (Sema &S, SourceLocation Loc, Expr *Operand)
Check the validity of an arithmetic pointer operand.
static bool checkArithmeticBinOpPointerOperands (Sema &S, SourceLocation Loc, Expr *LHSExpr, Expr *RHSExpr)
Check the validity of a binary arithmetic operation w.r.t.
static void diagnoseStringPlusInt (Sema &Self, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
diagnoseStringPlusInt - Emit a warning when adding an integer to a string literal.
static void diagnoseStringPlusChar (Sema &Self, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
Emit a warning when adding a char literal to a string.
static void diagnosePointerIncompatibility (Sema &S, SourceLocation Loc, Expr *LHSExpr, Expr *RHSExpr)
Emit error when two pointers are incompatible.
static bool isScopedEnumerationType (QualType T)
static void DiagnoseBadShiftValues (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, BinaryOperatorKind Opc, QualType LHSType)
static QualType checkVectorShift (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, bool IsCompAssign)
Return the resulting type when a vector is shifted by a scalar or vector shift amount.
static QualType checkSizelessVectorShift (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, bool IsCompAssign)
static void diagnoseDistinctPointerComparison (Sema &S, SourceLocation Loc, ExprResult &LHS, ExprResult &RHS, bool IsError)
Diagnose bad pointer comparisons.
static bool convertPointersToCompositeType (Sema &S, SourceLocation Loc, ExprResult &LHS, ExprResult &RHS)
Returns false if the pointers are converted to a composite type, true otherwise.
static void diagnoseFunctionPointerToVoidComparison (Sema &S, SourceLocation Loc, ExprResult &LHS, ExprResult &RHS, bool IsError)
static bool isObjCObjectLiteral (ExprResult &E)
static bool hasIsEqualMethod (Sema &S, const Expr *LHS, const Expr *RHS)
static void diagnoseObjCLiteralComparison (Sema &S, SourceLocation Loc, ExprResult &LHS, ExprResult &RHS, BinaryOperator::Opcode Opc)
static void diagnoseLogicalNotOnLHSofCheck (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, BinaryOperatorKind Opc)
Warns on !x < y, !x & y where !(x < y), !(x & y) was probably intended.
static bool checkForArray (const Expr *E)
static void diagnoseTautologicalComparison (Sema &S, SourceLocation Loc, Expr *LHS, Expr *RHS, BinaryOperatorKind Opc)
Diagnose some forms of syntactically-obvious tautological comparison.
static ImplicitConversionKind castKindToImplicitConversionKind (CastKind CK)
static bool checkThreeWayNarrowingConversion (Sema &S, QualType ToType, Expr *E, QualType FromType, SourceLocation Loc)
static QualType checkArithmeticOrEnumeralThreeWayCompare (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
static QualType checkArithmeticOrEnumeralCompare (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc, BinaryOperatorKind Opc)
static void diagnoseXorMisusedAsPow (Sema &S, const ExprResult &XorLHS, const ExprResult &XorRHS, const SourceLocation Loc)
static bool isLegalBoolVectorBinaryOp (BinaryOperatorKind Opc)
static bool IsReadonlyMessage (Expr *E, Sema &S)
static NonConstCaptureKind isReferenceToNonConstCapture (Sema &S, Expr *E)
static bool IsTypeModifiable (QualType Ty, bool IsDereference)
static void DiagnoseConstAssignment (Sema &S, const Expr *E, SourceLocation Loc)
Emit the "read-only variable not assignable" error and print notes to give more information about why the variable is not assignable, such as pointing to the declaration of a const variable, showing that a method is const, or that the function is returning a const reference.
static void DiagnoseRecursiveConstFields (Sema &S, const ValueDecl *VD, const RecordType *Ty, SourceLocation Loc, SourceRange Range, OriginalExprKind OEK, bool &DiagnosticEmitted)
static void DiagnoseRecursiveConstFields (Sema &S, const Expr *E, SourceLocation Loc)
Emit an error for the case where a record we are trying to assign to has a const-qualified field somewhere in its hierarchy.
static bool CheckForModifiableLvalue (Expr *E, SourceLocation Loc, Sema &S)
CheckForModifiableLvalue - Verify that E is a modifiable lvalue.
static void CheckIdentityFieldAssignment (Expr *LHSExpr, Expr *RHSExpr, SourceLocation Loc, Sema &Sema)
static bool IgnoreCommaOperand (const Expr *E, const ASTContext &Context)
static QualType CheckCommaOperands (Sema &S, ExprResult &LHS, ExprResult &RHS, SourceLocation Loc)
static QualType CheckIncrementDecrementOperand (Sema &S, Expr *Op, ExprValueKind &VK, ExprObjectKind &OK, SourceLocation OpLoc, bool IsInc, bool IsPrefix)
CheckIncrementDecrementOperand - unlike most "Check" methods, this routine doesn't need to call UsualUnaryConversions or UsualArithmeticConversions.
static ValueDecl * getPrimaryDecl (Expr *E)
getPrimaryDecl - Helper function for CheckAddressOfOperand().
static void diagnoseAddressOfInvalidType (Sema &S, SourceLocation Loc, Expr *E, unsigned Type)
Diagnose invalid operand for address of operations.
static void RecordModifiableNonNullParam (Sema &S, const Expr *Exp)
static QualType CheckIndirectionOperand (Sema &S, Expr *Op, ExprValueKind &VK, SourceLocation OpLoc, bool IsAfterAmp=false)
CheckIndirectionOperand - Type check unary indirection (prefix '*').
static UnaryOperatorKind ConvertTokenKindToUnaryOpcode (tok::TokenKind Kind)
static void DiagnoseSelfAssignment (Sema &S, Expr *LHSExpr, Expr *RHSExpr, SourceLocation OpLoc, bool IsBuiltin)
DiagnoseSelfAssignment - Emits a warning if a value is assigned to itself.
static void checkObjCPointerIntrospection (Sema &S, ExprResult &L, ExprResult &R, SourceLocation OpLoc)
Check if a bitwise-& is performed on an Objective-C pointer.
static NamedDecl * getDeclFromExpr (Expr *E)
static ExprResult convertHalfVecBinOp (Sema &S, ExprResult LHS, ExprResult RHS, BinaryOperatorKind Opc, QualType ResultTy, ExprValueKind VK, ExprObjectKind OK, bool IsCompAssign, SourceLocation OpLoc, FPOptionsOverride FPFeatures)
static std::pair< ExprResult, ExprResult > CorrectDelayedTyposInBinOp (Sema &S, BinaryOperatorKind Opc, Expr *LHSExpr, Expr *RHSExpr)
static bool needsConversionOfHalfVec (bool OpRequiresConversion, ASTContext &Ctx, Expr *E0, Expr *E1=nullptr)
Returns true if conversion between vectors of halfs and vectors of floats is needed.
static void DiagnoseBitwisePrecedence (Sema &Self, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
DiagnoseBitwisePrecedence - Emit a warning when bitwise and comparison operators are mixed in a way that suggests that the programmer forgot that comparison operators have higher precedence.
static void EmitDiagnosticForLogicalAndInLogicalOr (Sema &Self, SourceLocation OpLoc, BinaryOperator *Bop)
It accepts a '&&' expr that is inside a '||' one.
static void DiagnoseLogicalAndInLogicalOrLHS (Sema &S, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
Look for '&&' in the left hand of a '||' expr.
static void DiagnoseLogicalAndInLogicalOrRHS (Sema &S, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
Look for '&&' in the right hand of a '||' expr.
static void DiagnoseBitwiseOpInBitwiseOp (Sema &S, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr *SubExpr)
Look for bitwise op in the left or right hand of a bitwise op with lower precedence and emit a diagnostic together with a fixit hint that wraps the '&' expression in parentheses.
static void DiagnoseAdditionInShift (Sema &S, SourceLocation OpLoc, Expr *SubExpr, StringRef Shift)
static void DiagnoseShiftCompare (Sema &S, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
static void DiagnoseBinOpPrecedence (Sema &Self, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr *LHSExpr, Expr *RHSExpr)
DiagnoseBinOpPrecedence - Emit warnings for expressions with tricky precedence.
static ExprResult BuildOverloadedBinOp (Sema &S, Scope *Sc, SourceLocation OpLoc, BinaryOperatorKind Opc, Expr *LHS, Expr *RHS)
Build an overloaded binary operator expression in the given scope.
static bool isOverflowingIntegerType (ASTContext &Ctx, QualType T)
static CXXRecordDecl * LookupStdSourceLocationImpl (Sema &S, SourceLocation Loc)
static bool maybeDiagnoseAssignmentToFunction (Sema &S, QualType DstType, const Expr *SrcExpr)
static void EvaluateAndDiagnoseImmediateInvocation (Sema &SemaRef, Sema::ImmediateInvocationCandidate Candidate)
static void RemoveNestedImmediateInvocation (Sema &SemaRef, Sema::ExpressionEvaluationContextRecord &Rec, SmallVector< Sema::ImmediateInvocationCandidate, 4 >::reverse_iterator It)
static void HandleImmediateInvocations (Sema &SemaRef, Sema::ExpressionEvaluationContextRecord &Rec)
static bool isPotentiallyConstantEvaluatedContext (Sema &SemaRef)
Are we in a context that is potentially constant evaluated per C++20 [expr.const]p12?
static bool funcHasParameterSizeMangling (Sema &S, FunctionDecl *FD)
Return true if this function has a calling convention that requires mangling in the size of the parameter pack.
static void CheckCompleteParameterTypesForMangler (Sema &S, FunctionDecl *FD, SourceLocation Loc)
Require that all of the parameter types of function be complete.
static OdrUseContext isOdrUseContext (Sema &SemaRef)
Are we within a context in which references to resolved functions or to variables result in odr-use?
static bool isImplicitlyDefinableConstexprFunction (FunctionDecl *Func)
static void MarkVarDeclODRUsed (ValueDecl *V, SourceLocation Loc, Sema &SemaRef, const unsigned *const FunctionScopeIndexToStopAt=nullptr)
Directly mark a variable odr-used.
static bool isVariableAlreadyCapturedInScopeInfo (CapturingScopeInfo *CSI, ValueDecl *Var, bool &SubCapturesAreNested, QualType &CaptureType, QualType &DeclRefType)
static DeclContext * getParentOfCapturingContextOrNull (DeclContext *DC, ValueDecl *Var, SourceLocation Loc, const bool Diagnose, Sema &S)
static bool isVariableCapturable (CapturingScopeInfo *CSI, ValueDecl *Var, SourceLocation Loc, const bool Diagnose, Sema &S)
static bool captureInBlock (BlockScopeInfo *BSI, ValueDecl *Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType &CaptureType, QualType &DeclRefType, const bool Nested, Sema &S, bool Invalid)
static bool captureInCapturedRegion (CapturedRegionScopeInfo *RSI, ValueDecl *Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType &CaptureType, QualType &DeclRefType, const bool RefersToCapturedVariable, Sema::TryCaptureKind Kind, bool IsTopScope, Sema &S, bool Invalid)
Capture the given variable in the captured region.
static bool captureInLambda (LambdaScopeInfo *LSI, ValueDecl *Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType &CaptureType, QualType &DeclRefType, const bool RefersToCapturedVariable, const Sema::TryCaptureKind Kind, SourceLocation EllipsisLoc, const bool IsTopScope, Sema &S, bool Invalid)
Capture the given variable in the lambda.
static bool canCaptureVariableByCopy (ValueDecl *Var, const ASTContext &Context)
static void buildLambdaCaptureFixit (Sema &Sema, LambdaScopeInfo *LSI, ValueDecl *Var)
Create up to 4 fix-its for explicit reference and value capture of Var or default capture.
static ExprResult rebuildPotentialResultsAsNonOdrUsed (Sema &S, Expr *E, NonOdrUseReason NOUR)
Walk the set of potential results of an expression and mark them all as non-odr-uses if they satisfy the side-conditions of the NonOdrUseReason.
static void DoMarkPotentialCapture (Sema &SemaRef, SourceLocation Loc, ValueDecl *Var, Expr *E)
static void DoMarkVarDeclReferenced (Sema &SemaRef, SourceLocation Loc, VarDecl *Var, Expr *E, llvm::DenseMap< const VarDecl *, int > &RefsMinusAssignments)
static void DoMarkBindingDeclReferenced (Sema &SemaRef, SourceLocation Loc, BindingDecl *BD, Expr *E)
static void FixDependencyOfIdExpressionsInLambdaWithDependentObjectParameter (Sema &SemaRef, ValueDecl *D, Expr *E)
static void MarkExprReferenced (Sema &SemaRef, SourceLocation Loc, Decl *D, Expr *E, bool MightBeOdrUse, llvm::DenseMap< const VarDecl *, int > &RefsMinusAssignments)
static ExprResult diagnoseUnknownAnyExpr (Sema &S, Expr *E)
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (kind)
ABSTRACT_TYPE
#define ABSTRACT_TYPE (Class, Base)
BUILTIN_TYPE [1/2]
#define BUILTIN_TYPE (ID, SINGLETON_ID) case BuiltinType::ID:
BUILTIN_TYPE [2/2]
#define BUILTIN_TYPE (Id, SingletonId) case BuiltinType::Id:
DECL
#define DECL (type, base) case Decl::type:
DEPENDENT_TYPE
#define DEPENDENT_TYPE (Class, Base) case Type::Class:
EXT_OPAQUE_TYPE [1/2]
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext) case BuiltinType::Id:
EXT_OPAQUE_TYPE [2/2]
#define EXT_OPAQUE_TYPE (ExtType, Id, Ext) case BuiltinType::Id:
IMAGE_READ_WRITE_TYPE [1/2]
#define IMAGE_READ_WRITE_TYPE (Type, Id, Ext)
IMAGE_READ_WRITE_TYPE [2/2]
#define IMAGE_READ_WRITE_TYPE (Type, Id, Ext)
IMAGE_TYPE [1/4]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Id:
IMAGE_TYPE [2/4]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Sampled##Id:
IMAGE_TYPE [3/4]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Id:
IMAGE_TYPE [4/4]
#define IMAGE_TYPE (ImgType, Id, SingletonId, Access, Suffix) case BuiltinType::Sampled##Id:
IMAGE_WRITE_TYPE [1/2]
#define IMAGE_WRITE_TYPE (Type, Id, Ext)
IMAGE_WRITE_TYPE [2/2]
#define IMAGE_WRITE_TYPE (Type, Id, Ext)
NON_CANONICAL_TYPE
#define NON_CANONICAL_TYPE (Class, Base)
NON_CANONICAL_UNLESS_DEPENDENT_TYPE
#define NON_CANONICAL_UNLESS_DEPENDENT_TYPE (Class, Base)
PLACEHOLDER_TYPE [1/2]
#define PLACEHOLDER_TYPE (ID, SINGLETON_ID)
PLACEHOLDER_TYPE [2/2]
#define PLACEHOLDER_TYPE (Id, SingletonId)
PPC_VECTOR_TYPE [1/2]
#define PPC_VECTOR_TYPE (Name, Id, Size) case BuiltinType::Id:
PPC_VECTOR_TYPE [2/2]
#define PPC_VECTOR_TYPE (Name, Id, Size) case BuiltinType::Id:
RVV_TYPE [1/2]
#define RVV_TYPE (Name, Id, SingletonId) case BuiltinType::Id:
RVV_TYPE [2/2]
#define RVV_TYPE (Name, Id, SingletonId) case BuiltinType::Id:
SVE_TYPE [1/2]
#define SVE_TYPE (Name, Id, SingletonId) case BuiltinType::Id:
SVE_TYPE [2/2]
#define SVE_TYPE (Name, Id, SingletonId) case BuiltinType::Id:
TYPE
#define TYPE (Class, Base)
VALUE
#define VALUE (type, base)
WASM_TYPE [1/2]
#define WASM_TYPE (Name, Id, SingletonId) case BuiltinType::Id:
WASM_TYPE [2/2]
#define WASM_TYPE (Name, Id, SingletonId) case BuiltinType::Id:
Typedef Documentation
PerformCastFn
typedef ExprResult PerformCastFn(Sema &S, Expr *operand, QualType toType)
Definition at line 1364 of file SemaExpr.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ConstFunction
ConstVariable
ConstMember
ConstMethod
NestedConstMember
ConstUnknown
Definition at line 13730 of file SemaExpr.cpp.
NonConstCaptureKind
enum NonConstCaptureKind
Is the given expression (which must be 'const') a reference to a variable which was originally non-const, but which has become 'const' due to being captured within a block?
Enumerator
NCCK_None
NCCK_Block
NCCK_Lambda
Definition at line 13684 of file SemaExpr.cpp.
OriginalExprKind
enum OriginalExprKind
Enumerator
OEK_Variable
OEK_Member
OEK_LValue
Definition at line 13862 of file SemaExpr.cpp.
Function Documentation
breakDownVectorType()
static bool breakDownVectorType (QualType type, uint64_t & len, QualType & eltType) static
Definition at line 7766 of file SemaExpr.cpp.
References clang::Type::isScalarType(), and clang::ast_matchers::type.
Referenced by clang::Sema::areVectorTypesSameSize().
BuildCookedLiteralOperatorCall()
static ExprResult BuildCookedLiteralOperatorCall (Sema & S, Scope * Scope, IdentifierInfo * UDSuffix, SourceLocation UDSuffixLoc, ArrayRef< Expr * > Args, SourceLocation LitEndLoc) static
BuildCookedLiteralOperatorCall - A user-defined literal was found.
Look up the corresponding cooked (non-raw) literal operator, and build a call to it.
Definition at line 2012 of file SemaExpr.cpp.
Referenced by clang::Sema::ActOnCharacterConstant().
BuildFloatingLiteral()
static Expr* BuildFloatingLiteral (Sema & S, NumericLiteralParser & Literal, QualType Ty, SourceLocation Loc) static
Definition at line 3922 of file SemaExpr.cpp.
Referenced by clang::Sema::ActOnNumericConstant().
buildLambdaCaptureFixit()
static void buildLambdaCaptureFixit (Sema & Sema, LambdaScopeInfo * LSI, ValueDecl * Var) static
Create up to 4 fix-its for explicit reference and value capture of Var or default capture.
Fixes may be omitted if they aren't allowed by the standard, for example we can't emit a default copy capture fix-it if we already explicitly copy capture capture another variable.
Definition at line 19184 of file SemaExpr.cpp.
References canCaptureVariableByCopy(), clang::sema::CapturingScopeInfo::Captures, clang::FixItHint::CreateInsertion(), clang::SemaBase::Diag(), clang::Sema::getASTContext(), clang::SourceRange::getBegin(), clang::sema::CapturingScopeInfo::getCXXThisCapture(), clang::NamedDecl::getDeclName(), clang::SourceRange::getEnd(), clang::Sema::getLangOpts(), clang::SourceLocation::getLocWithOffset(), clang::NamedDecl::getName(), clang::sema::CapturingScopeInfo::ImpCap_None, clang::sema::CapturingScopeInfo::ImpCaptureStyle, clang::sema::LambdaScopeInfo::IntroducerRange, clang::sema::Capture::isCopyCapture(), clang::sema::CapturingScopeInfo::isCXXThisCaptured(), clang::DeclarationName::isIdentifier(), and clang::sema::LambdaScopeInfo::NumExplicitCaptures.
Referenced by clang::Sema::tryCaptureVariable().
BuildOverloadedBinOp()
static ExprResult BuildOverloadedBinOp (Sema & S, Scope * Sc, SourceLocation OpLoc, BinaryOperatorKind Opc, Expr * LHS, Expr * RHS) static
Build an overloaded binary operator expression in the given scope.
Definition at line 15626 of file SemaExpr.cpp.
canCaptureVariableByCopy()
static bool canCaptureVariableByCopy (ValueDecl * Var, const ASTContext & Context) static
Definition at line 19158 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Type::getAsCXXRecordDecl(), clang::QualType::getNonReferenceType(), clang::ValueDecl::getType(), clang::Type::isDependentType(), and clang::T.
Referenced by buildLambdaCaptureFixit().
canConvertIntToOtherIntTy()
static bool canConvertIntToOtherIntTy (Sema & S, ExprResult * Int, QualType OtherIntTy) static
Test if a (constant) integer Int can be casted to another integer type IntTy without losing precision.
Definition at line 10421 of file SemaExpr.cpp.
canConvertIntTyToFloatTy()
static bool canConvertIntTyToFloatTy (Sema & S, ExprResult * Int, QualType FloatTy) static
Test if a (constant) integer Int can be casted to floating point type FloatTy without losing precision.
Definition at line 10459 of file SemaExpr.cpp.
captureInBlock()
static bool captureInBlock (BlockScopeInfo * BSI, ValueDecl * Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType & CaptureType, QualType & DeclRefType, const bool Nested, Sema & S, bool Invalid) static
Definition at line 18948 of file SemaExpr.cpp.
Referenced by clang::Sema::tryCaptureVariable().
captureInCapturedRegion()
static bool captureInCapturedRegion (CapturedRegionScopeInfo * RSI, ValueDecl * Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType & CaptureType, QualType & DeclRefType, const bool RefersToCapturedVariable, Sema::TryCaptureKind Kind, bool IsTopScope, Sema & S, bool Invalid) static
Capture the given variable in the captured region.
Definition at line 19016 of file SemaExpr.cpp.
Referenced by clang::Sema::tryCaptureVariable().
captureInLambda()
static bool captureInLambda (LambdaScopeInfo * LSI, ValueDecl * Var, SourceLocation Loc, const bool BuildAndDiagnose, QualType & CaptureType, QualType & DeclRefType, const bool RefersToCapturedVariable, const Sema::TryCaptureKind Kind, SourceLocation EllipsisLoc, const bool IsTopScope, Sema & S, bool Invalid) static
Capture the given variable in the lambda.
Definition at line 19056 of file SemaExpr.cpp.
Referenced by clang::Sema::tryCaptureVariable().
captureVariablyModifiedType()
static void captureVariablyModifiedType (ASTContext & Context, QualType T, CapturingScopeInfo * CSI) static
Definition at line 4690 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand(), clang::Sema::CreateBuiltinArraySubscriptExpr(), and clang::Sema::tryCaptureVariable().
castKindToImplicitConversionKind()
static ImplicitConversionKind castKindToImplicitConversionKind (CastKind CK) static
Definition at line 12378 of file SemaExpr.cpp.
References clang::CastExpr::getCastKindName(), clang::ICK_Array_To_Pointer, clang::ICK_Complex_Conversion, clang::ICK_Complex_Real, clang::ICK_Floating_Conversion, clang::ICK_Floating_Integral, clang::ICK_Function_To_Pointer, clang::ICK_HLSL_Array_RValue, clang::ICK_Identity, clang::ICK_Integral_Conversion, and clang::ICK_Lvalue_To_Rvalue.
CheckAlignOfExpr()
static bool CheckAlignOfExpr (Sema & S, Expr * E, UnaryExprOrTypeTrait ExprKind) static
Definition at line 4624 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateUnaryExprOrTypeTraitExpr().
checkArithmeticBinOpPointerOperands()
static bool checkArithmeticBinOpPointerOperands (Sema & S, SourceLocation Loc, Expr * LHSExpr, Expr * RHSExpr) static
Check the validity of a binary arithmetic operation w.r.t.
pointer operands.
This routine will diagnose any invalid arithmetic on pointer operands much like
See also
checkArithmeticOpPointerOperand. However, it has special logic for emitting a single diagnostic even for operations where both LHS and RHS are (potentially problematic) pointers.
Returns
True when the operand is valid to use (even if as an extension).
Definition at line 11233 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckSubtractionOperands().
checkArithmeticIncompletePointerType()
static bool checkArithmeticIncompletePointerType (Sema & S, SourceLocation Loc, Expr * Operand) static
Emit error if Operand is incomplete pointer type.
Returns
True if pointer has incomplete type
Definition at line 11179 of file SemaExpr.cpp.
checkArithmeticNull()
static void checkArithmeticNull (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, bool IsCompare) static
Definition at line 10923 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAdditionOperands(), clang::Sema::CheckBitwiseOperands(), clang::Sema::CheckCompareOperands(), clang::Sema::CheckMultiplyDivideOperands(), clang::Sema::CheckRemainderOperands(), clang::Sema::CheckShiftOperands(), and clang::Sema::CheckSubtractionOperands().
checkArithmeticOnObjCPointer()
static bool checkArithmeticOnObjCPointer (Sema & S, SourceLocation opLoc, Expr * op) static
Diagnose if arithmetic on the given ObjC pointer is illegal.
Returns
true on error
Definition at line 5081 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAdditionOperands(), and clang::Sema::CheckSubtractionOperands().
checkArithmeticOpPointerOperand()
static bool checkArithmeticOpPointerOperand (Sema & S, SourceLocation Loc, Expr * Operand) static
Check the validity of an arithmetic pointer operand.
If the operand has pointer type, this code will check for pointer types which are invalid in arithmetic operations. These will be diagnosed appropriately, including whether or not the use is supported as an extension.
Returns
True when the operand is valid to use (even if as an extension).
Definition at line 11201 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAdditionOperands(), and clang::Sema::CheckSubtractionOperands().
checkArithmeticOrEnumeralCompare()
static QualType checkArithmeticOrEnumeralCompare (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, BinaryOperatorKind Opc) static
Definition at line 12542 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckCompareOperands().
checkArithmeticOrEnumeralThreeWayCompare()
static QualType checkArithmeticOrEnumeralThreeWayCompare (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Definition at line 12460 of file SemaExpr.cpp.
checkBlockPointerTypesForAssignment()
static Sema::AssignConvertType checkBlockPointerTypesForAssignment (Sema & S, QualType LHSType, QualType RHSType) static
checkBlockPointerTypesForAssignment - This routine determines whether two block pointer types are compatible or whether a block and normal pointer are compatible.
It is more restrict than comparing two function pointer
Definition at line 9526 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAssignmentConstraints().
checkBlockType()
static bool checkBlockType (Sema & S, const Expr * E) static
Return true if the Expr is block type.
Definition at line 8700 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckConditionalOperands().
CheckCommaOperands()
static QualType CheckCommaOperands (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Definition at line 14315 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinBinOp().
CheckCompleteParameterTypesForMangler()
static void CheckCompleteParameterTypesForMangler (Sema & S, FunctionDecl * FD, SourceLocation Loc) static
Require that all of the parameter types of function be complete.
Normally, parameter types are only required to be complete when a function is called or defined, but to mangle functions with certain calling conventions, the mangler needs to know the size of the parameter list. In this situation, MSVC doesn't emit an error or instantiate templates. Instead, MSVC mangles the function as _foo@0, i.e. zero bytes of parameters, which will usually result in a linker error. Clang doesn't implement this behavior, and instead attempts to error at compile time.
Definition at line 18328 of file SemaExpr.cpp.
Referenced by clang::Sema::MarkFunctionReferenced().
checkCondition()
static bool checkCondition (Sema & S, const Expr * Cond, SourceLocation QuestionLoc) static
Return false if the condition expression is valid, true otherwise.
Definition at line 8265 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckConditionalOperands().
checkConditionalBlockPointerCompatibility()
static QualType checkConditionalBlockPointerCompatibility (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Return the resulting type when the operands are both block pointers.
Definition at line 8430 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckConditionalOperands().
checkConditionalNullPointer()
static bool checkConditionalNullPointer (Sema & S, ExprResult & NullExpr, QualType PointerTy) static
Return false if the NullExpr can be promoted to PointerTy, true otherwise.
Definition at line 8286 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckConditionalOperands().
checkConditionalObjectPointersCompatibility()
static QualType checkConditionalObjectPointersCompatibility (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Return the resulting type when the operands are both pointers.
Definition at line 8456 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckConditionalOperands().
checkConditionalPointerCompatibility()
static QualType checkConditionalPointerCompatibility (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc) static
Checks compatibility between two pointers and return the resulting type.
Definition at line 8299 of file SemaExpr.cpp.
CheckDeclInExpr()
static bool CheckDeclInExpr (Sema & S, SourceLocation Loc, NamedDecl * D, bool AcceptInvalid) static
Diagnoses obvious problems with the use of the given declaration as an expression.
This is only actually called for lookups that were not overloaded, and it doesn't promise that the declaration will in fact be used.
Definition at line 3468 of file SemaExpr.cpp.
Referenced by clang::Sema::BuildDeclarationNameExpr().
checkDirectCallValidity()
static void checkDirectCallValidity (Sema & S, const Expr * Fn, FunctionDecl * Callee, MultiExprArg ArgExprs) static
Definition at line 6544 of file SemaExpr.cpp.
Referenced by clang::Sema::BuildCallExpr().
checkEnumArithmeticConversions()
static void checkEnumArithmeticConversions (Sema & S, Expr * LHS, Expr * RHS, SourceLocation Loc, Sema::ArithConvKind ACK) static
Check that the usual arithmetic conversions can be performed on this pair of expressions that might be of enumeration type.
Definition at line 1564 of file SemaExpr.cpp.
Referenced by clang::Sema::UsualArithmeticConversions().
CheckExtensionTraitOperandType()
static bool CheckExtensionTraitOperandType (Sema & S, QualType T, SourceLocation Loc, SourceRange ArgRange, UnaryExprOrTypeTrait TraitKind) static
Definition at line 4446 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand().
checkForArray()
static bool checkForArray (const Expr * E) static
Definition at line 12232 of file SemaExpr.cpp.
References clang::ValueDecl::getType(), clang::Type::isArrayType(), and clang::ValueDecl::isWeak().
CheckForModifiableLvalue()
static bool CheckForModifiableLvalue (Expr * E, SourceLocation Loc, Sema & S) static
CheckForModifiableLvalue - Verify that E is a modifiable lvalue.
If not, emit an error and return true. If so, return false.
Definition at line 13932 of file SemaExpr.cpp.
Referenced by clang::Sema::BuildVAArgExpr(), and clang::Sema::CheckAssignmentOperands().
CheckForNullPointerDereference()
static void CheckForNullPointerDereference (Sema & S, Expr * E) static
Definition at line 637 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAssignmentOperands().
CheckIdentityFieldAssignment()
static void CheckIdentityFieldAssignment (Expr * LHSExpr, Expr * RHSExpr, SourceLocation Loc, Sema & Sema) static
Definition at line 14060 of file SemaExpr.cpp.
References clang::SemaBase::Diag(), clang::Type::getAs(), clang::MemberExpr::getBase(), clang::ObjCIvarRefExpr::getBase(), clang::Decl::getCanonicalDecl(), clang::DeclRefExpr::getDecl(), clang::ObjCIvarRefExpr::getDecl(), clang::Expr::getExprLoc(), clang::MemberExpr::getMemberDecl(), clang::ValueDecl::getType(), clang::Expr::IgnoreImpCasts(), clang::Sema::inTemplateInstantiation(), clang::SourceLocation::isInvalid(), clang::SourceLocation::isMacroID(), clang::Sema::isUnevaluatedContext(), and clang::QualType::isVolatileQualified().
Referenced by clang::Sema::CheckAssignmentOperands().
CheckIncrementDecrementOperand()
static QualType CheckIncrementDecrementOperand (Sema & S, Expr * Op, ExprValueKind & VK, ExprObjectKind & OK, SourceLocation OpLoc, bool IsInc, bool IsPrefix) static
CheckIncrementDecrementOperand - unlike most "Check" methods, this routine doesn't need to call UsualUnaryConversions or UsualArithmeticConversions.
Definition at line 14351 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinUnaryOp().
CheckIndirectionOperand()
static QualType CheckIndirectionOperand (Sema & S, Expr * Op, ExprValueKind & VK, SourceLocation OpLoc, bool IsAfterAmp = false) static
CheckIndirectionOperand - Type check unary indirection (prefix '*').
Definition at line 14791 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinUnaryOp().
checkObjCPointerIntrospection()
static void checkObjCPointerIntrospection (Sema & S, ExprResult & L, ExprResult & R, SourceLocation OpLoc) static
Check if a bitwise-& is performed on an Objective-C pointer.
This is usually indicative of introspection within the Objective-C pointer.
Definition at line 14992 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinBinOp().
checkObjCPointerTypesForAssignment()
static Sema::AssignConvertType checkObjCPointerTypesForAssignment (Sema & S, QualType LHSType, QualType RHSType) static
checkObjCPointerTypesForAssignment - Compares two objective-c pointer types for assignment compatibility.
Definition at line 9577 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAssignmentConstraints().
CheckObjCTraitOperandConstraints()
static bool CheckObjCTraitOperandConstraints (Sema & S, QualType T, SourceLocation Loc, SourceRange ArgRange, UnaryExprOrTypeTrait TraitKind) static
Definition at line 4476 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand().
checkOpenCLConditionVector()
static bool checkOpenCLConditionVector (Sema & S, Expr * Cond, SourceLocation QuestionLoc) static
Return false if this is a valid OpenCL condition vector.
Definition at line 8614 of file SemaExpr.cpp.
checkPointerIntegerMismatch()
static bool checkPointerIntegerMismatch (Sema & S, ExprResult & Int, Expr * PointerExpr, SourceLocation Loc, bool IsIntFirstExpr) static
Return false if the first expression is not an integer and the second expression is not a pointer, true otherwise.
Definition at line 8495 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckConditionalOperands().
checkPointerTypesForAssignment()
static Sema::AssignConvertType checkPointerTypesForAssignment (Sema & S, QualType LHSType, QualType RHSType, SourceLocation Loc) static
Definition at line 9374 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAssignmentConstraints().
CheckRealImagOperand()
static QualType CheckRealImagOperand (Sema & S, ExprResult & V, SourceLocation Loc, bool IsReal) static
Definition at line 5024 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinUnaryOp().
checkSizelessVectorShift()
static QualType checkSizelessVectorShift (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, bool IsCompAssign) static
Definition at line 11833 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckShiftOperands().
checkThreeWayNarrowingConversion()
static bool checkThreeWayNarrowingConversion (Sema & S, QualType ToType, Expr * E, QualType FromType, SourceLocation Loc) static
Definition at line 12417 of file SemaExpr.cpp.
CheckVecStepTraitOperandType()
static bool CheckVecStepTraitOperandType (Sema & S, QualType T, SourceLocation Loc, SourceRange ArgRange) static
Definition at line 4416 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand().
CheckVectorElementsTraitOperandType()
static bool CheckVectorElementsTraitOperandType (Sema & S, QualType T, SourceLocation Loc, SourceRange ArgRange) static
Definition at line 4434 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand().
checkVectorResult()
static bool checkVectorResult (Sema & S, QualType CondTy, QualType VecResTy, SourceLocation QuestionLoc) static
Return false if the vector condition type and the vector result type are compatible.
OpenCL v1.1 s6.11.6 requires that both vector types have the same number of elements, and their element types have the same number of bits.
Definition at line 8634 of file SemaExpr.cpp.
checkVectorShift()
static QualType checkVectorShift (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, bool IsCompAssign) static
Return the resulting type when a vector is shifted by a scalar or vector shift amount.
Definition at line 11739 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckShiftOperands().
computeConditionalNullability()
static QualType computeConditionalNullability (QualType ResTy, bool IsBin, QualType LHSTy, QualType RHSTy, ASTContext & Ctx) static
Compute the nullability of a conditional expression.
Definition at line 9178 of file SemaExpr.cpp.
References clang::ASTContext::getAttributedType(), clang::Type::getNullability(), clang::AttributedType::getNullabilityAttrKind(), clang::QualType::getSingleStepDesugaredType(), clang::Type::isAnyPointerType(), clang::NonNull, clang::Nullable, clang::NullableResult, and clang::Unspecified.
Referenced by clang::Sema::ActOnConditionalOp().
ConstructTransparentUnion()
static void ConstructTransparentUnion (Sema & S, ASTContext & C, ExprResult & EResult, QualType UnionType, FieldDecl * Field) static
Constructs a transparent union from an expression that is used to initialize the transparent union.
Definition at line 10014 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckTransparentUnionArgumentConstraints().
convertHalfVecBinOp()
static ExprResult convertHalfVecBinOp (Sema & S, ExprResult LHS, ExprResult RHS, BinaryOperatorKind Opc, QualType ResultTy, ExprValueKind VK, ExprObjectKind OK, bool IsCompAssign, SourceLocation OpLoc, FPOptionsOverride FPFeatures) static
Definition at line 15048 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinBinOp().
convertPointersToCompositeType()
static bool convertPointersToCompositeType (Sema & S, SourceLocation Loc, ExprResult & LHS, ExprResult & RHS) static
Returns false if the pointers are converted to a composite type, true otherwise.
Definition at line 12000 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckCompareOperands().
ConvertTokenKindToUnaryOpcode()
static UnaryOperatorKind ConvertTokenKindToUnaryOpcode (tok::TokenKind Kind) inline static
Definition at line 14894 of file SemaExpr.cpp.
ConvertUTF8ToWideString()
static void ConvertUTF8ToWideString (unsigned CharByteWidth, StringRef Source, SmallString< 32 > & Target) static
Definition at line 3792 of file SemaExpr.cpp.
Referenced by clang::Sema::BuildPredefinedExpr().
convertVector()
static ExprResult convertVector (Expr * E, QualType ElementType, Sema & S) static
Convert vector E to a vector with the same number of elements but different element type.
Definition at line 10400 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinUnaryOp().
CorrectDelayedTyposInBinOp()
static std::pair<ExprResult, ExprResult> CorrectDelayedTyposInBinOp (Sema & S, BinaryOperatorKind Opc, Expr * LHSExpr, Expr * RHSExpr) static
Definition at line 15081 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinBinOp().
DiagnoseAdditionInShift()
static void DiagnoseAdditionInShift (Sema & S, SourceLocation OpLoc, Expr * SubExpr, StringRef Shift) static
Definition at line 15522 of file SemaExpr.cpp.
Referenced by DiagnoseBinOpPrecedence().
diagnoseAddressOfInvalidType()
static void diagnoseAddressOfInvalidType (Sema & S, SourceLocation Loc, Expr * E, unsigned Type) static
Diagnose invalid operand for address of operations.
Parameters
Type The type of operand which cannot have its address taken.
Definition at line 14516 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAddressOfOperand().
diagnoseArithmeticOnFunctionPointer()
static void diagnoseArithmeticOnFunctionPointer (Sema & S, SourceLocation Loc, Expr * Pointer) static
Diagnose invalid arithmetic on a function pointer.
Definition at line 11165 of file SemaExpr.cpp.
diagnoseArithmeticOnNullPointer()
static void diagnoseArithmeticOnNullPointer (Sema & S, SourceLocation Loc, Expr * Pointer, bool IsGNUIdiom) static
Diagnose invalid arithmetic on a null pointer.
If IsGNUIdiom is true, the operation is using the 'p = (i8*)nullptr + n' idiom, which we recognize as a GNU extension.
Definition at line 11120 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAdditionOperands(), and clang::Sema::CheckSubtractionOperands().
diagnoseArithmeticOnTwoFunctionPointers()
static void diagnoseArithmeticOnTwoFunctionPointers (Sema & S, SourceLocation Loc, Expr * LHS, Expr * RHS) static
Diagnose invalid arithmetic on two function pointers.
Definition at line 11149 of file SemaExpr.cpp.
diagnoseArithmeticOnTwoVoidPointers()
static void diagnoseArithmeticOnTwoVoidPointers (Sema & S, SourceLocation Loc, Expr * LHSExpr, Expr * RHSExpr) static
Diagnose invalid arithmetic on two void pointers.
Definition at line 11097 of file SemaExpr.cpp.
diagnoseArithmeticOnVoidPointer()
static void diagnoseArithmeticOnVoidPointer (Sema & S, SourceLocation Loc, Expr * Pointer) static
Diagnose invalid arithmetic on a void pointer.
Definition at line 11107 of file SemaExpr.cpp.
DiagnoseBadDivideOrRemainderValues()
static void DiagnoseBadDivideOrRemainderValues (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, bool IsDiv) static
Definition at line 11007 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckMultiplyDivideOperands(), and clang::Sema::CheckRemainderOperands().
DiagnoseBadShiftValues()
static void DiagnoseBadShiftValues (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, BinaryOperatorKind Opc, QualType LHSType) static
Definition at line 11638 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckShiftOperands().
DiagnoseBinOpPrecedence()
static void DiagnoseBinOpPrecedence (Sema & Self, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
DiagnoseBinOpPrecedence - Emit warnings for expressions with tricky precedence.
Definition at line 15564 of file SemaExpr.cpp.
References DiagnoseAdditionInShift(), DiagnoseBitwiseOpInBitwiseOp(), DiagnoseBitwisePrecedence(), DiagnoseLogicalAndInLogicalOrLHS(), DiagnoseLogicalAndInLogicalOrRHS(), DiagnoseShiftCompare(), clang::BinaryOperator::getOpcodeStr(), clang::Expr::getType(), clang::BinaryOperator::isBitwiseOp(), clang::BinaryOperator::isComparisonOp(), clang::Type::isIntegralType(), clang::SourceLocation::isMacroID(), and clang::prec::Shift.
DiagnoseBitwiseOpInBitwiseOp()
static void DiagnoseBitwiseOpInBitwiseOp (Sema & S, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr * SubExpr) static
Look for bitwise op in the left or right hand of a bitwise op with lower precedence and emit a diagnostic together with a fixit hint that wraps the '&' expression in parentheses.
Definition at line 15507 of file SemaExpr.cpp.
Referenced by DiagnoseBinOpPrecedence().
DiagnoseBitwisePrecedence()
static void DiagnoseBitwisePrecedence (Sema & Self, BinaryOperatorKind Opc, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
DiagnoseBitwisePrecedence - Emit a warning when bitwise and comparison operators are mixed in a way that suggests that the programmer forgot that comparison operators have higher precedence.
The most typical example of such code is "flags & 0x0020 != 0", which is equivalent to "flags & 1".
Definition at line 15416 of file SemaExpr.cpp.
References clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::BinaryOperator::getLHS(), clang::BinaryOperator::getOpcodeStr(), clang::BinaryOperator::getRHS(), clang::BinaryOperator::isBitwiseOp(), clang::BinaryOperator::isComparisonOp(), and SuggestParentheses().
Referenced by DiagnoseBinOpPrecedence().
DiagnoseCalleeStaticArrayParam()
static void DiagnoseCalleeStaticArrayParam (Sema & S, ParmVarDecl * PVD) static
Definition at line 6303 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckStaticArrayArgument().
DiagnoseConditionalPrecedence()
static void DiagnoseConditionalPrecedence (Sema & Self, SourceLocation OpLoc, Expr * Condition, const Expr * LHSExpr, const Expr * RHSExpr) static
DiagnoseConditionalPrecedence - Emit a warning when a conditional operator and binary operator are mixed in a way that suggests the programmer assumed the conditional operator has higher precedence, for example: "int x = a + someBinaryCondition ? 1 : 2".
Definition at line 9144 of file SemaExpr.cpp.
References clang::Condition, ExprLooksBoolean(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::BinaryOperator::getOpcodeStr(), IsArithmeticBinaryExpr(), clang::BinaryOperator::isBitwiseOp(), and SuggestParentheses().
Referenced by clang::Sema::ActOnConditionalOp().
DiagnoseConstAssignment()
static void DiagnoseConstAssignment (Sema & S, const Expr * E, SourceLocation Loc) static
Emit the "read-only variable not assignable" error and print notes to give more information about why the variable is not assignable, such as pointing to the declaration of a const variable, showing that a method is const, or that the function is returning a const reference.
Definition at line 13743 of file SemaExpr.cpp.
DiagnoseDirectIsaAccess()
static void DiagnoseDirectIsaAccess (Sema & S, const ObjCIvarRefExpr * OIRE, SourceLocation AssignLoc, const Expr * RHS) static
Definition at line 662 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinBinOp().
diagnoseDistinctPointerComparison()
static void diagnoseDistinctPointerComparison (Sema & S, SourceLocation Loc, ExprResult & LHS, ExprResult & RHS, bool IsError) static
Diagnose bad pointer comparisons.
Definition at line 11989 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckCompareOperands().
DiagnoseDivisionSizeofPointerOrArray()
static void DiagnoseDivisionSizeofPointerOrArray (Sema & S, Expr * LHS, Expr * RHS, SourceLocation Loc) static
Definition at line 10959 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckMultiplyDivideOperands().
DiagnosedUnqualifiedCallsToStdFunctions()
static void DiagnosedUnqualifiedCallsToStdFunctions (Sema & S, const CallExpr * Call) static
Definition at line 6654 of file SemaExpr.cpp.
Referenced by clang::Sema::ActOnCallExpr().
diagnoseFunctionPointerToVoidComparison()
static void diagnoseFunctionPointerToVoidComparison (Sema & S, SourceLocation Loc, ExprResult & LHS, ExprResult & RHS, bool IsError) static
Definition at line 12029 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckCompareOperands().
DiagnoseLogicalAndInLogicalOrLHS()
static void DiagnoseLogicalAndInLogicalOrLHS (Sema & S, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
Look for '&&' in the left hand of a '||' expr.
Definition at line 15471 of file SemaExpr.cpp.
Referenced by DiagnoseBinOpPrecedence().
DiagnoseLogicalAndInLogicalOrRHS()
static void DiagnoseLogicalAndInLogicalOrRHS (Sema & S, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
Look for '&&' in the right hand of a '||' expr.
Definition at line 15492 of file SemaExpr.cpp.
Referenced by DiagnoseBinOpPrecedence().
diagnoseLogicalNotOnLHSofCheck()
static void diagnoseLogicalNotOnLHSofCheck (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation Loc, BinaryOperatorKind Opc) static
Warns on !x < y, !x & y where !(x < y), !(x & y) was probably intended.
Definition at line 12190 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckBitwiseOperands(), and clang::Sema::CheckCompareOperands().
diagnoseObjCLiteralComparison()
static void diagnoseObjCLiteralComparison (Sema & S, SourceLocation Loc, ExprResult & LHS, ExprResult & RHS, BinaryOperator::Opcode Opc) static
Definition at line 12140 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckCompareOperands().
diagnosePointerIncompatibility()
static void diagnosePointerIncompatibility (Sema & S, SourceLocation Loc, Expr * LHSExpr, Expr * RHSExpr) static
Emit error when two pointers are incompatible.
Definition at line 11367 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckSubtractionOperands().
DiagnoseRecursiveConstFields() [1/2]
static void DiagnoseRecursiveConstFields (Sema & S, const Expr * E, SourceLocation Loc) static
Emit an error for the case where a record we are trying to assign to has a const-qualified field somewhere in its hierarchy.
Definition at line 13909 of file SemaExpr.cpp.
DiagnoseRecursiveConstFields() [2/2]
static void DiagnoseRecursiveConstFields (Sema & S, const ValueDecl * VD, const RecordType * Ty, SourceLocation Loc, SourceRange Range, OriginalExprKind OEK, bool & DiagnosticEmitted) static
Definition at line 13868 of file SemaExpr.cpp.
DiagnoseSelfAssignment()
static void DiagnoseSelfAssignment (Sema & S, Expr * LHSExpr, Expr * RHSExpr, SourceLocation OpLoc, bool IsBuiltin) static
DiagnoseSelfAssignment - Emits a warning if a value is assigned to itself.
This warning suppressed in the event of macro expansions.
Definition at line 14950 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinBinOp().
DiagnoseShiftCompare()
static void DiagnoseShiftCompare (Sema & S, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
Definition at line 15536 of file SemaExpr.cpp.
Referenced by DiagnoseBinOpPrecedence().
diagnoseStringPlusChar()
static void diagnoseStringPlusChar (Sema & Self, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
Emit a warning when adding a char literal to a string.
Definition at line 11316 of file SemaExpr.cpp.
References clang::ASTContext::CharTy, clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateReplacement(), clang::Stmt::getBeginLoc(), clang::ASTContext::getCharWidth(), clang::Stmt::getEndLoc(), clang::Type::getPointeeType(), clang::Expr::getType(), clang::CharacterLiteral::getValue(), clang::Expr::IgnoreImpCasts(), clang::Type::isAnyCharacterType(), clang::Type::isAnyPointerType(), and clang::Type::isIntegerType().
Referenced by clang::Sema::CheckAdditionOperands().
diagnoseStringPlusInt()
static void diagnoseStringPlusInt (Sema & Self, SourceLocation OpLoc, Expr * LHSExpr, Expr * RHSExpr) static
diagnoseStringPlusInt - Emit a warning when adding an integer to a string literal.
Definition at line 11286 of file SemaExpr.cpp.
References clang::FixItHint::CreateInsertion(), clang::FixItHint::CreateReplacement(), clang::Stmt::getBeginLoc(), clang::Stmt::getEndLoc(), clang::Expr::getType(), clang::Expr::IgnoreImpCasts(), clang::Type::isIntegralOrUnscopedEnumerationType(), and clang::Expr::isValueDependent().
Referenced by clang::Sema::CheckAdditionOperands().
diagnoseSubtractionOnNullPointer()
static void diagnoseSubtractionOnNullPointer (Sema & S, SourceLocation Loc, Expr * Pointer, bool BothNull) static
Diagnose invalid subraction on a null pointer.
Definition at line 11132 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckSubtractionOperands().
diagnoseTautologicalComparison()
static void diagnoseTautologicalComparison (Sema & S, SourceLocation Loc, Expr * LHS, Expr * RHS, BinaryOperatorKind Opc) static
Diagnose some forms of syntactically-obvious tautological comparison.
Definition at line 12246 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckCompareOperands(), clang::Sema::CheckSizelessVectorCompareOperands(), and clang::Sema::CheckVectorCompareOperands().
diagnoseUncapturableValueReferenceOrBinding()
void diagnoseUncapturableValueReferenceOrBinding (Sema & S, SourceLocation loc, ValueDecl * var) static
Definition at line 18775 of file SemaExpr.cpp.
Referenced by clang::Sema::tryCaptureVariable().
diagnoseUnknownAnyExpr()
static ExprResult diagnoseUnknownAnyExpr (Sema & S, Expr * E) static
Definition at line 21248 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckPlaceholderExpr().
DiagnoseUnusedOfDecl()
static void DiagnoseUnusedOfDecl (Sema & S, NamedDecl * D, SourceLocation Loc) static
Definition at line 105 of file SemaExpr.cpp.
diagnoseUseOfInternalDeclInInlineFunction()
static void diagnoseUseOfInternalDeclInInlineFunction (Sema & S, const NamedDecl * D, SourceLocation Loc) static
Check whether we're in an extern inline function and referring to a variable or function with internal linkage (C11 6.7.4p3).
This is only a warning because we used to silently accept this code, but in many cases it will not behave correctly. This is not enabled in C++ mode because the restriction language is a bit weaker (C++11 [basic.def.odr]p6) and so while there may still be user mistakes, most of the time we can't prove that there are errors.
Definition at line 160 of file SemaExpr.cpp.
diagnoseXorMisusedAsPow()
static void diagnoseXorMisusedAsPow (Sema & S, const ExprResult & XorLHS, const ExprResult & XorRHS, const SourceLocation Loc) static
Definition at line 13250 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckBitwiseOperands().
DoMarkBindingDeclReferenced()
static void DoMarkBindingDeclReferenced (Sema & SemaRef, SourceLocation Loc, BindingDecl * BD, Expr * E) static
Definition at line 20197 of file SemaExpr.cpp.
References DoMarkPotentialCapture(), clang::Decl::isInvalidDecl(), isOdrUseContext(), clang::SemaBase::SemaRef, clang::Decl::setReferenced(), clang::Sema::TryCapture_Implicit, clang::Sema::tryCaptureVariable(), and Used.
Referenced by MarkExprReferenced().
DoMarkPotentialCapture()
static void DoMarkPotentialCapture (Sema & SemaRef, SourceLocation Loc, ValueDecl * Var, Expr * E) static
Definition at line 19994 of file SemaExpr.cpp.
References clang::sema::LambdaScopeInfo::addPotentialCapture(), clang::sema::LambdaScopeInfo::CallOperator, clang::Sema::Context, clang::Sema::CurContext, clang::DeclContext::Encloses(), clang::Sema::getCurLambda(), clang::Decl::getDeclContext(), clang::ValueDecl::getPotentiallyDecomposedVarDecl(), clang::ValueDecl::getType(), clang::VarDecl::hasLocalStorage(), clang::Expr::IgnoreParens(), clang::DeclContext::isFunctionOrMethod(), clang::Type::isReferenceType(), clang::VarDecl::isUsableInConstantExpressions(), and clang::SemaBase::SemaRef.
Referenced by DoMarkBindingDeclReferenced(), and DoMarkVarDeclReferenced().
DoMarkVarDeclReferenced()
static void DoMarkVarDeclReferenced (Sema & SemaRef, SourceLocation Loc, VarDecl * Var, Expr * E, llvm::DenseMap< const VarDecl *, int > & RefsMinusAssignments) static
Definition at line 20026 of file SemaExpr.cpp.
References clang::Sema::checkSpecializationVisibility(), clang::Sema::Context, DoMarkPotentialCapture(), clang::VarDecl::getMemberSpecializationInfo(), clang::VarDecl::getPointOfInstantiation(), clang::VarDecl::getTemplateSpecializationKind(), clang::MemberSpecializationInfo::getTemplateSpecializationKind(), clang::VarDecl::hasExternalStorage(), clang::Sema::InstantiateVariableDefinition(), clang::SourceLocation::isInvalid(), clang::Decl::isInvalidDecl(), clang::VarDecl::isLocalVarDeclOrParm(), isOdrUseContext(), isPotentiallyConstantEvaluatedContext(), clang::isTemplateInstantiation(), clang::Sema::isUnevaluatedContext(), clang::VarDecl::isUsableInConstantExpressions(), Iter, MarkVarDeclODRUsed(), clang::Sema::MaybeODRUseExprs, clang::VarDecl::mightBeUsableInConstantExpressions(), clang::XRayInstrKind::None, P, clang::Sema::PendingInstantiations, clang::Sema::RefsMinusAssignments, clang::Sema::runWithSufficientStackSpace(), clang::Sema::SavedPendingInstantiations, clang::SemaBase::SemaRef, clang::Decl::setReferenced(), clang::VarDecl::setTemplateSpecializationKind(), clang::TSK_ExplicitInstantiationDeclaration, clang::TSK_ImplicitInstantiation, clang::TSK_Undeclared, and Used.
Referenced by MarkExprReferenced(), and clang::Sema::MarkVariableReferenced().
EmitDiagnosticForLogicalAndInLogicalOr()
static void EmitDiagnosticForLogicalAndInLogicalOr (Sema & Self, SourceLocation OpLoc, BinaryOperator * Bop) static
It accepts a '&&' expr that is inside a '||' one.
Emit a diagnostic together with a fixit hint that wraps the '&&' expression in parentheses.
Definition at line 15459 of file SemaExpr.cpp.
References clang::BinaryOperator::getOpcode(), clang::BinaryOperator::getOpcodeStr(), clang::BinaryOperator::getOperatorLoc(), clang::Stmt::getSourceRange(), and SuggestParentheses().
emitEmptyLookupTypoDiagnostic()
static void emitEmptyLookupTypoDiagnostic (const TypoCorrection & TC, Sema & SemaRef, const CXXScopeSpec & SS, DeclarationName Typo, SourceLocation TypoLoc, ArrayRef< Expr * > Args, unsigned DiagnosticID, unsigned DiagnosticSuggestID) static
Definition at line 2441 of file SemaExpr.cpp.
enclosingClassIsRelatedToClassInWhichMembersWereFound()
static bool enclosingClassIsRelatedToClassInWhichMembersWereFound (const UnresolvedMemberExpr *const UME, Sema & S) static
Definition at line 6571 of file SemaExpr.cpp.
EvaluateAndDiagnoseImmediateInvocation()
static void EvaluateAndDiagnoseImmediateInvocation (Sema & SemaRef, Sema::ImmediateInvocationCandidate Candidate) static
Definition at line 17937 of file SemaExpr.cpp.
References clang::interp::Cast(), clang::Sema::Context, clang::Expr::EvalStatus::Diag, clang::SemaBase::Diag(), clang::Sema::DiagnoseImmediateEscalatingReason(), clang::Expr::EvaluateAsConstantExpr(), clang::Sema::FailedImmediateInvocations, clang::FunctionalCast, clang::Sema::getASTContext(), clang::ConstantExpr::getBeginLoc(), clang::FullExpr::getSubExpr(), clang::Expr::IgnoreImplicit(), clang::Expr::ImmediateInvocation, clang::Sema::InnermostDeclarationWithDelayedImmediateInvocations(), clang::FunctionDecl::isConsteval(), clang::FunctionDecl::isImmediateFunction(), clang::Decl::isInvalidDecl(), clang::ConstantExpr::MoveIntoResult(), clang::SemaBase::SemaRef, and clang::Expr::EvalResult::Val.
ExprLooksBoolean()
static bool ExprLooksBoolean (const Expr * E) static
ExprLooksBoolean - Returns true if E looks boolean, i.e.
it has boolean type or is a logical expression such as (x==y) which has int type, but is commonly interpreted as boolean.
Definition at line 9123 of file SemaExpr.cpp.
References clang::Expr::getType(), clang::Expr::IgnoreParenImpCasts(), clang::Type::isBooleanType(), and clang::Type::isPointerType().
Referenced by DiagnoseConditionalPrecedence().
FixDependencyOfIdExpressionsInLambdaWithDependentObjectParameter()
static void FixDependencyOfIdExpressionsInLambdaWithDependentObjectParameter (Sema & SemaRef, ValueDecl * D, Expr * E) static
Definition at line 20229 of file SemaExpr.cpp.
References clang::Sema::CurContext, clang::Sema::FunctionScopes, clang::Type::getAs(), clang::Sema::getASTContext(), ID, clang::sema::CapturingScopeInfo::ImpCap_LambdaByval, clang::Type::isDependentType(), and clang::SemaBase::SemaRef.
Referenced by MarkExprReferenced().
funcHasParameterSizeMangling()
static bool funcHasParameterSizeMangling (Sema & S, FunctionDecl * FD) static
Return true if this function has a calling convention that requires mangling in the size of the parameter pack.
Definition at line 18294 of file SemaExpr.cpp.
Referenced by clang::Sema::MarkFunctionReferenced().
getDeclFromExpr()
static NamedDecl* getDeclFromExpr (Expr * E) static
Definition at line 15033 of file SemaExpr.cpp.
getDependentArraySubscriptType()
static QualType getDependentArraySubscriptType (Expr * LHS, Expr * RHS, const ASTContext & Ctx) static
Definition at line 5114 of file SemaExpr.cpp.
References clang::ASTContext::DependentTy, clang::Type::getAs(), clang::Type::getAsArrayTypeUnsafe(), clang::Expr::getType(), clang::Type::isIntegralOrUnscopedEnumerationType(), and clang::Expr::isTypeDependent().
Referenced by clang::Sema::CreateBuiltinArraySubscriptExpr().
GetFixedPointRank()
static unsigned GetFixedPointRank (QualType Ty) static
Return the rank of a given fixed point or integer type.
The value itself doesn't matter, but the values must be increasing with proper increasing rank as described in N1169 4.1.1.
Definition at line 1478 of file SemaExpr.cpp.
References clang::Type::getAs().
getParentOfCapturingContextOrNull()
static DeclContext* getParentOfCapturingContextOrNull (DeclContext * DC, ValueDecl * Var, SourceLocation Loc, const bool Diagnose, Sema & S) static
Definition at line 18849 of file SemaExpr.cpp.
Referenced by clang::Sema::tryCaptureVariable().
getPredefinedExprDecl()
static Decl* getPredefinedExprDecl (DeclContext * DC) static
getPredefinedExprDecl - Returns Decl of a given DeclContext that can be used to determine the value of a PredefinedExpr.
This can be either a block, lambda, captured statement, function, otherwise a nullptr.
Definition at line 1996 of file SemaExpr.cpp.
References clang::DeclContext::getParent().
Referenced by clang::Sema::BuildPredefinedExpr(), and clang::Sema::ExpandFunctionLocalPredefinedMacros().
getPredefinedExprKind()
static PredefinedIdentKind getPredefinedExprKind (tok::TokenKind Kind) static
Definition at line 1972 of file SemaExpr.cpp.
References clang::Func, clang::FuncDName, clang::FuncSig, clang::Function, clang::LFuncSig, clang::LFunction, and clang::PrettyFunction.
Referenced by clang::Sema::ActOnPredefinedExpr().
getPrimaryDecl()
static ValueDecl* getPrimaryDecl (Expr * E) static
getPrimaryDecl - Helper function for CheckAddressOfOperand().
This routine allows us to typecheck complex/recursive expressions where the declaration is needed for type checking. We only need to handle cases when the expression references a function designator or is an lvalue. Here are some examples:
&(x) => x
&*****f => f for f a function designator.
&s.xx => s
&s.zz[1].yy -> s, if zz is an array
*(x + 1) -> x, if x is an array
&"123"[2] -> 0
& real x -> x
FIXME: We don't recurse to the RHS of a comma, nor handle pointers to members.
Definition at line 14456 of file SemaExpr.cpp.
References clang::format::getBase(), clang::UnaryOperator::getOpcode(), clang::Stmt::getStmtClass(), and clang::UnaryOperator::getSubExpr().
Referenced by clang::Sema::CheckAddressOfOperand().
getUDSuffixLoc()
static SourceLocation getUDSuffixLoc (Sema & S, SourceLocation TokLoc, unsigned Offset) static
getUDSuffixLoc - Create a SourceLocation for a ud-suffix, given the location of the token and the offset of the ud-suffix within it.
Definition at line 2004 of file SemaExpr.cpp.
Referenced by clang::Sema::ActOnCharacterConstant(), and clang::Sema::ActOnNumericConstant().
handleComplexConversion()
static QualType handleComplexConversion (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType LHSType, QualType RHSType, bool IsCompAssign) static
Handle arithmetic conversion with complex types.
Helper function of UsualArithmeticConversions()
Definition at line 1234 of file SemaExpr.cpp.
handleComplexFloatConversion()
static QualType handleComplexFloatConversion (Sema & S, ExprResult & Shorter, QualType ShorterType, QualType LongerType, bool PromotePrecision) static
Definition at line 1211 of file SemaExpr.cpp.
handleComplexIntConversion()
static QualType handleComplexIntConversion (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType LHSType, QualType RHSType, bool IsCompAssign) static
Handle conversions with GCC complex int extension.
Helper function of UsualArithmeticConversions()
Definition at line 1432 of file SemaExpr.cpp.
handleComplexIntegerToFloatConversion()
static bool handleComplexIntegerToFloatConversion (Sema & S, ExprResult & IntExpr, ExprResult & ComplexExpr, QualType IntTy, QualType ComplexTy, bool SkipCast) static
Convert complex integers to complex floats and real integers to real floats as required for complex arithmetic.
Helper function of UsualArithmeticConversions()
Returns
false if the integer expression is an integer type and is successfully converted to the (complex) float type.
Definition at line 1183 of file SemaExpr.cpp.
handleFixedPointConversion()
static QualType handleFixedPointConversion (Sema & S, QualType LHSTy, QualType RHSTy) static
handleFixedPointConversion - Fixed point operations between fixed point types and integers or other fixed point types do not fall under usual arithmetic conversion since these conversions could result in loss of precsision (N1169 4.1.4).
These operations should be calculated with the full precision of their result type (N1169 4.1.6.2.1).
Definition at line 1525 of file SemaExpr.cpp.
handleFloatConversion()
static QualType handleFloatConversion (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType LHSType, QualType RHSType, bool IsCompAssign) static
Handle arithmethic conversion with floating point types.
Helper function of UsualArithmeticConversions()
Definition at line 1289 of file SemaExpr.cpp.
HandleImmediateInvocations()
static void HandleImmediateInvocations (Sema & SemaRef, Sema::ExpressionEvaluationContextRecord & Rec) static
When we have more than 1 ImmediateInvocationCandidates or previously failed immediate invocations, we need to check for nested ImmediateInvocationCandidates in order to avoid duplicate diagnostics. Otherwise we only need to remove ReferenceToConsteval in the immediate invocation.
Prevent sema calls during the tree transform from adding pointers that are already in the sets.
Prevent diagnostic during tree transfrom as they are duplicates
Definition at line 18076 of file SemaExpr.cpp.
References clang::Sema::FailedImmediateInvocations, clang::Sema::ExpressionEvaluationContextRecord::ImmediateInvocationCandidates, clang::Sema::RebuildingImmediateInvocation, clang::Sema::ExpressionEvaluationContextRecord::ReferenceToConsteval, RemoveNestedImmediateInvocation(), and clang::SemaBase::SemaRef.
Referenced by clang::Sema::PopExpressionEvaluationContext().
handleIntegerConversion()
template<PerformCastFn doLHSCast, PerformCastFn doRHSCast> static QualType handleIntegerConversion (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType LHSType, QualType RHSType, bool IsCompAssign) static
Handle integer arithmetic conversions.
Helper function of UsualArithmeticConversions()
Definition at line 1382 of file SemaExpr.cpp.
handleIntToFloatConversion()
static QualType handleIntToFloatConversion (Sema & S, ExprResult & FloatExpr, ExprResult & IntExpr, QualType FloatTy, QualType IntTy, bool ConvertFloat, bool ConvertInt) static
Handle arithmetic conversion from integer to float.
Helper function of UsualArithmeticConversions()
Definition at line 1258 of file SemaExpr.cpp.
hasAnyExplicitStorageClass()
static bool hasAnyExplicitStorageClass (const FunctionDecl * D) static
Determine whether a FunctionDecl was ever declared with an explicit storage class.
Definition at line 144 of file SemaExpr.cpp.
References clang::Redeclarable< decl_type >::redecls(), and clang::SC_None.
Referenced by clang::Sema::MaybeSuggestAddingStaticToDecl().
hasIsEqualMethod()
static bool hasIsEqualMethod (Sema & S, const Expr * LHS, const Expr * RHS) static
Definition at line 12052 of file SemaExpr.cpp.
IgnoreCommaOperand()
static bool IgnoreCommaOperand (const Expr * E, const ASTContext & Context) static
Definition at line 14243 of file SemaExpr.cpp.
Referenced by clang::Sema::DiagnoseCommaOperator().
IsArithmeticBinaryExpr()
static bool IsArithmeticBinaryExpr (const Expr * E, BinaryOperatorKind * Opcode, const Expr ** RHSExprs) static
IsArithmeticBinaryExpr - Returns true if E is an arithmetic binary expression, either using a built-in or overloaded operator, and sets *OpCode to the opcode and *RHSExprs to the right-hand side expression.
Definition at line 9078 of file SemaExpr.cpp.
References clang::BinaryOperator::getOverloadedOpcode(), clang::Expr::IgnoreConversionOperatorSingleStep(), clang::Expr::IgnoreImpCasts(), and IsArithmeticOp().
Referenced by DiagnoseConditionalPrecedence().
IsArithmeticOp()
static bool IsArithmeticOp (BinaryOperatorKind Opc) static
Definition at line 9063 of file SemaExpr.cpp.
References clang::BinaryOperator::isAdditiveOp(), clang::BinaryOperator::isMultiplicativeOp(), and clang::BinaryOperator::isShiftOp().
Referenced by IsArithmeticBinaryExpr().
isCapturingReferenceToHostVarInCUDADeviceLambda()
static bool isCapturingReferenceToHostVarInCUDADeviceLambda (const Sema & S, VarDecl * VD) static
Definition at line 2295 of file SemaExpr.cpp.
Referenced by clang::Sema::getNonOdrUseReasonInCurrentContext().
isImplicitlyDefinableConstexprFunction()
static bool isImplicitlyDefinableConstexprFunction (FunctionDecl * Func) static
Definition at line 18414 of file SemaExpr.cpp.
References clang::Func.
Referenced by clang::Sema::MarkFunctionReferenced().
IsInvalidCmseNSCallConversion()
static bool IsInvalidCmseNSCallConversion (Sema & S, QualType FromType, QualType ToType) static
Definition at line 9353 of file SemaExpr.cpp.
isLegalBoolVectorBinaryOp()
static bool isLegalBoolVectorBinaryOp (BinaryOperatorKind Opc) static
Definition at line 13480 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckBitwiseOperands().
isMSPropertySubscriptExpr()
static bool isMSPropertySubscriptExpr (Sema & S, Expr * Base) static
Definition at line 5095 of file SemaExpr.cpp.
isObjCObjectLiteral()
static bool isObjCObjectLiteral (ExprResult & E) static
Definition at line 12039 of file SemaExpr.cpp.
References clang::ActionResult< PtrTy, Compress >::get(), clang::Stmt::getStmtClass(), and clang::Expr::IgnoreParenImpCasts().
Referenced by clang::Sema::CheckCompareOperands().
isOdrUseContext()
static OdrUseContext isOdrUseContext (Sema & SemaRef) static
Are we within a context in which references to resolved functions or to variables result in odr-use?
Definition at line 18382 of file SemaExpr.cpp.
References clang::Sema::ConstantEvaluated, clang::Sema::CurContext, clang::Sema::DiscardedStatement, clang::Sema::ExprEvalContexts, clang::Sema::ImmediateFunctionContext, clang::DeclContext::isDependentContext(), clang::XRayInstrKind::None, clang::Sema::PotentiallyEvaluated, clang::Sema::PotentiallyEvaluatedIfUsed, clang::SemaBase::SemaRef, clang::Sema::Unevaluated, clang::Sema::UnevaluatedAbstract, clang::Sema::UnevaluatedList, and Used.
Referenced by DoMarkBindingDeclReferenced(), DoMarkVarDeclReferenced(), and clang::Sema::MarkFunctionReferenced().
isOverflowingIntegerType()
static bool isOverflowingIntegerType (ASTContext & Ctx, QualType T) static
Definition at line 15809 of file SemaExpr.cpp.
References clang::ASTContext::getIntWidth(), clang::ASTContext::IntTy, clang::Type::isDependentType(), clang::ASTContext::isPromotableIntegerType(), and clang::T.
Referenced by clang::Sema::CreateBuiltinUnaryOp().
isPlaceholderToRemoveAsArg()
static bool isPlaceholderToRemoveAsArg (QualType type) static
Is the given type a placeholder that we need to lower out immediately during argument processing?
Definition at line 6379 of file SemaExpr.cpp.
References clang::BuiltinType::getKind(), and clang::ast_matchers::type.
Referenced by clang::Sema::CheckArgsForPlaceholders().
isPotentiallyConstantEvaluatedContext()
static bool isPotentiallyConstantEvaluatedContext (Sema & SemaRef) static
Are we in a context that is potentially constant evaluated per C++20 [expr.const]p12?
C++2a [expr.const]p12:
Definition at line 18263 of file SemaExpr.cpp.
References clang::Sema::ConstantEvaluated, clang::Sema::DiscardedStatement, clang::Sema::ExprEvalContexts, clang::Sema::ImmediateFunctionContext, clang::Sema::PotentiallyEvaluated, clang::Sema::PotentiallyEvaluatedIfUsed, clang::SemaBase::SemaRef, clang::Sema::Unevaluated, clang::Sema::UnevaluatedAbstract, and clang::Sema::UnevaluatedList.
Referenced by DoMarkVarDeclReferenced(), and clang::Sema::MarkFunctionReferenced().
IsReadonlyMessage()
static bool IsReadonlyMessage (Expr * E, Sema & S) static
Definition at line 13671 of file SemaExpr.cpp.
isReferenceToNonConstCapture()
static NonConstCaptureKind isReferenceToNonConstCapture (Sema & S, Expr * E) static
Definition at line 13685 of file SemaExpr.cpp.
isScopedEnumerationType()
static bool isScopedEnumerationType (QualType T) static
Definition at line 11632 of file SemaExpr.cpp.
References clang::Type::getAs(), and clang::T.
Referenced by clang::Sema::CheckShiftOperands(), and clang::Sema::CreateBuiltinUnaryOp().
IsTypeModifiable()
static bool IsTypeModifiable (QualType Ty, bool IsDereference) static
Definition at line 13721 of file SemaExpr.cpp.
References clang::QualType::getNonReferenceType(), clang::Type::getPointeeType(), clang::QualType::isConstQualified(), and clang::Type::isPointerType().
isVariableAlreadyCapturedInScopeInfo()
static bool isVariableAlreadyCapturedInScopeInfo (CapturingScopeInfo * CSI, ValueDecl * Var, bool & SubCapturesAreNested, QualType & CaptureType, QualType & DeclRefType) static
Definition at line 18816 of file SemaExpr.cpp.
References clang::QualType::addConst(), clang::sema::CapturingScopeInfo::CaptureMap, clang::CR_OpenMP, clang::sema::CapturingScopeInfo::getCapture(), clang::sema::Capture::getCaptureType(), clang::QualType::getNonReferenceType(), and clang::sema::Capture::isCopyCapture().
Referenced by clang::Sema::tryCaptureVariable().
isVariableCapturable()
static bool isVariableCapturable (CapturingScopeInfo * CSI, ValueDecl * Var, SourceLocation Loc, const bool Diagnose, Sema & S) static
Definition at line 18868 of file SemaExpr.cpp.
Referenced by clang::Sema::tryCaptureVariable().
isVector()
static bool isVector (QualType QT, QualType ElementType) static
This helper function returns true if QT is a vector type that has element type ElementType.
Definition at line 9626 of file SemaExpr.cpp.
References clang::Type::getAs().
Referenced by clang::Sema::CreateBuiltinBinOp().
LookupStdSourceLocationImpl()
static CXXRecordDecl* LookupStdSourceLocationImpl (Sema & S, SourceLocation Loc) static
Definition at line 17009 of file SemaExpr.cpp.
Referenced by clang::Sema::ActOnSourceLocExpr().
MarkExprReferenced()
static void MarkExprReferenced (Sema & SemaRef, SourceLocation Loc, Decl * D, Expr * E, bool MightBeOdrUse, llvm::DenseMap< const VarDecl *, int > & RefsMinusAssignments) static
Definition at line 20275 of file SemaExpr.cpp.
References clang::SemaOpenMP::checkDeclIsAllowedInOpenMPTarget(), DoMarkBindingDeclReferenced(), DoMarkVarDeclReferenced(), FixDependencyOfIdExpressionsInLambdaWithDependentObjectParameter(), clang::MemberExpr::getBase(), clang::CXXMethodDecl::getDevirtualizedMethod(), clang::Sema::getLangOpts(), clang::MemberExpr::getMemberDecl(), clang::SemaOpenMP::isInOpenMPDeclareTargetContext(), clang::CXXMethodDecl::isVirtual(), clang::Sema::MarkAnyDeclReferenced(), clang::Sema::OpenMP(), clang::MemberExpr::performsVirtualDispatch(), clang::Sema::RefsMinusAssignments, and clang::SemaBase::SemaRef.
Referenced by clang::Sema::MarkDeclRefReferenced(), clang::Sema::MarkFunctionParmPackReferenced(), and clang::Sema::MarkMemberReferenced().
MarkVarDeclODRUsed()
static void MarkVarDeclODRUsed (ValueDecl * V, SourceLocation Loc, Sema & SemaRef, const unsigned *const FunctionScopeIndexToStopAt = nullptr) static
Directly mark a variable odr-used.
Given a choice, prefer to use MarkVariableReferenced since it does additional checks and then calls MarkVarDeclODRUsed. If the variable must be captured:
if FunctionScopeIndexToStopAt is null, capture it in the CurContext
else capture it in the DeclContext that maps to the *FunctionScopeIndexToStopAt on the FunctionScopeInfo stack.
Definition at line 18699 of file SemaExpr.cpp.
References clang::Sema::Context, clang::Sema::CUDA(), clang::ASTContext::CUDADeviceVarODRUsedByHost, clang::ASTContext::CUDAExternalDeviceDeclODRUsedByHost, clang::Sema::CurContext, clang::SemaCUDA::CVT_Device, clang::SemaCUDA::CVT_Host, clang::VarDecl::DeclarationOnly, clang::Device, clang::Sema::getASTContext(), clang::VarDecl::getCanonicalDecl(), clang::ASTContext::GetGVALinkageForFunction(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::Global, clang::GVA_StrongExternal, clang::Decl::hasAttr(), clang::VarDecl::hasDefinition(), clang::VarDecl::hasExternalStorage(), clang::VarDecl::hasGlobalStorage(), clang::VarDecl::hasInit(), clang::Host, clang::HostDevice, clang::SemaCUDA::IdentifyTarget(), clang::QualType::isConstQualified(), clang::NamedDecl::isExternallyVisible(), clang::Sema::isExternalWithNoLinkageType(), clang::VarDecl::isInline(), clang::SourceLocation::isInvalid(), clang::VarDecl::isStaticDataMember(), clang::Sema::LangOpts, clang::Sema::OpenMP(), clang::SemaBase::SemaRef, clang::Sema::targetDiag(), clang::Sema::TryCapture_Implicit, clang::SemaOpenMP::tryCaptureOpenMPLambdas(), clang::Sema::tryCaptureVariable(), clang::Sema::UndefinedButUsed, and V.
Referenced by clang::Sema::CleanupVarDeclMarking(), DoMarkVarDeclReferenced(), and clang::Sema::MarkCaptureUsedInEnclosingContext().
maybeDiagnoseAssignmentToFunction()
static bool maybeDiagnoseAssignmentToFunction (Sema & S, QualType DstType, const Expr * SrcExpr) static
Definition at line 17172 of file SemaExpr.cpp.
Referenced by clang::Sema::DiagnoseAssignmentResult().
needsConversionOfHalfVec()
static bool needsConversionOfHalfVec (bool OpRequiresConversion, ASTContext & Ctx, Expr * E0, Expr * E1 = nullptr) static
Returns true if conversion between vectors of halfs and vectors of floats is needed.
Definition at line 15104 of file SemaExpr.cpp.
References clang::Type::getAs(), clang::ASTContext::getLangOpts(), clang::ASTContext::getTargetInfo(), clang::Expr::getType(), clang::ASTContext::HalfTy, clang::Expr::IgnoreImplicit(), clang::Neon, and clang::TargetInfo::useFP16ConversionIntrinsics().
Referenced by clang::Sema::CreateBuiltinBinOp(), and clang::Sema::CreateBuiltinUnaryOp().
OpenCLArithmeticConversions()
static QualType OpenCLArithmeticConversions (Sema & S, ExprResult & LHS, ExprResult & RHS, SourceLocation QuestionLoc) static
Simple conversion between integer and floating point types.
Used when handling the OpenCL conditional operator where the condition is a vector while the other operands are scalar.
OpenCL v1.1 s6.3.i and s6.11.6 together require that the scalar types are either integer or floating type. Between the two operands, the type with the higher rank is defined as the "result type". The other operand needs to be promoted to the same type. No other type promotion is allowed. We cannot use UsualArithmeticConversions() for this purpose, since it always promotes promotable types.
Definition at line 8525 of file SemaExpr.cpp.
OpenCLCheckVectorConditional()
static QualType OpenCLCheckVectorConditional (Sema & S, ExprResult & Cond, ExprResult & LHS, ExprResult & RHS, SourceLocation QuestionLoc) static
Return the resulting type for the conditional operator in OpenCL (aka "ternary selection operator", OpenCL v1.1 s6.3.i) when the condition is a vector type.
Definition at line 8662 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckConditionalOperands().
OpenCLConvertScalarsToVectors()
static QualType OpenCLConvertScalarsToVectors (Sema & S, ExprResult & LHS, ExprResult & RHS, QualType CondTy, SourceLocation QuestionLoc) static
Convert scalar operands to a vector that matches the condition in length.
Used when handling the OpenCL conditional operator where the condition is a vector while the other operands are scalar.
We first compute the "result type" for the scalar operands according to OpenCL v1.1 s6.3.i. Both operands are then converted into a vector of that type where the length matches the condition vector type. s6.11.6 requires that the element types of the result and the condition must have the same number of bits.
Definition at line 8580 of file SemaExpr.cpp.
rebuildPotentialResultsAsNonOdrUsed()
static ExprResult rebuildPotentialResultsAsNonOdrUsed (Sema & S, Expr * E, NonOdrUseReason NOUR) static
Walk the set of potential results of an expression and mark them all as non-odr-uses if they satisfy the side-conditions of the NonOdrUseReason.
Returns
A new expression if we found any potential results, ExprEmpty() if not, and ExprError() if we diagnosed an error.
Definition at line 19610 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckLValueToRValueConversionOperand().
rebuildUnknownAnyFunction()
static ExprResult rebuildUnknownAnyFunction (Sema & S, Expr * fn) static
Given a function expression of unknown-any type, try to rebuild it to have a function type.
Definition at line 20853 of file SemaExpr.cpp.
Referenced by clang::Sema::BuildCallExpr(), and clang::Sema::BuildResolvedCallExpr().
RecordModifiableNonNullParam()
static void RecordModifiableNonNullParam (Sema & S, const Expr * Exp) static
Definition at line 14773 of file SemaExpr.cpp.
Referenced by clang::Sema::CreateBuiltinBinOp(), and clang::Sema::CreateBuiltinUnaryOp().
recoverFromMSUnqualifiedLookup()
static Expr* recoverFromMSUnqualifiedLookup (Sema & S, ASTContext & Context, DeclarationNameInfo & NameInfo, SourceLocation TemplateKWLoc, const TemplateArgumentListInfo * TemplateArgs) static
In Microsoft mode, if we are inside a template class whose parent class has dependent base classes, and we can't resolve an unqualified identifier, then assume the identifier is a member of a dependent base class.
We can only recover successfully in static methods, instance methods, and other contexts where 'this' is available. This doesn't precisely match MSVC's instantiation model, but it's close enough.
Definition at line 2719 of file SemaExpr.cpp.
RemoveNestedImmediateInvocation()
static void RemoveNestedImmediateInvocation (Sema & SemaRef, Sema::ExpressionEvaluationContextRecord & Rec, SmallVector< Sema::ImmediateInvocationCandidate, 4 >::reverse_iterator It) static
Base::TransfromCXXOperatorCallExpr doesn't traverse the callee so we need to remove its DeclRefExpr from the DRSet.
Base::TransformUserDefinedLiteral doesn't preserve the UserDefinedLiteral node.
Base::TransformInitializer skips ConstantExpr so we need to visit them here.
ConstantExpr are the first layer of implicit node to be removed so if Init isn't a ConstantExpr, no ConstantExpr will be skipped.
CXXConstructExpr with a single argument are getting skipped by TreeTransform in some situtation because they could be implicit. This can only occur for the top-level CXXConstructExpr because it is used nowhere in the expression being transformed therefore will not be rebuilt. Setting AllowSkippingFirstCXXConstructExpr to false will prevent from skipping the first CXXConstructExpr.
Definition at line 17979 of file SemaExpr.cpp.
References clang::SemaBase::SemaRef.
Referenced by HandleImmediateInvocations().
rewriteBuiltinFunctionDecl()
static FunctionDecl* rewriteBuiltinFunctionDecl (Sema * Sema, ASTContext & Context, FunctionDecl * FDecl, MultiExprArg ArgExprs) static
If a builtin function has a pointer argument with no explicit address space, then it should be able to accept a pointer to any address space as input.
In order to do this, we need to replace the standard builtin declaration with one that uses the same address space as the call.
Returns
nullptr If this builtin is not a candidate for a rewrite i.e. it does not contain any pointer arguments without an address space qualifer. Otherwise the rewritten FunctionDecl is returned. TODO: Handle pointer return types.
Definition at line 6471 of file SemaExpr.cpp.
Referenced by clang::Sema::BuildCallExpr().
ShouldLookupResultBeMultiVersionOverload()
static bool ShouldLookupResultBeMultiVersionOverload (const LookupResult & R) static
Definition at line 3493 of file SemaExpr.cpp.
References clang::LookupResult::getFoundDecl(), and clang::LookupResult::isSingleResult().
Referenced by clang::Sema::BuildDeclarationNameExpr().
SuggestParentheses()
static void SuggestParentheses (Sema & Self, SourceLocation Loc, const PartialDiagnostic & Note, SourceRange ParenRange) static
SuggestParentheses - Emit a note with a fixit hint that wraps ParenRange in parentheses.
Definition at line 9048 of file SemaExpr.cpp.
References clang::FixItHint::CreateInsertion(), clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::SourceLocation::isFileID(), and clang::SourceLocation::isValid().
Referenced by DiagnoseBitwisePrecedence(), DiagnoseConditionalPrecedence(), and EmitDiagnosticForLogicalAndInLogicalOr().
tryGCCVectorConvertAndSplat()
static bool tryGCCVectorConvertAndSplat (Sema & S, ExprResult * Scalar, ExprResult * Vector) static
Attempt to convert and splat Scalar into a vector whose types matches Vector following GCC conversion rules.
The rule is that implicit conversion can occur when Scalar can be casted to match Vector's element type without causing truncation of Scalar.
Definition at line 10503 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckSizelessVectorOperands(), and clang::Sema::CheckVectorOperands().
tryImplicitlyCaptureThisIfImplicitMemberFunctionAccessWithDependentArgs()
static void tryImplicitlyCaptureThisIfImplicitMemberFunctionAccessWithDependentArgs (Sema & S, const UnresolvedMemberExpr *const UME, SourceLocation CallLoc) static
Definition at line 6613 of file SemaExpr.cpp.
Referenced by clang::Sema::BuildCallExpr().
TryTypoCorrectionForCall()
static TypoCorrection TryTypoCorrectionForCall (Sema & S, Expr * Fn, FunctionDecl * FDecl, ArrayRef< Expr * > Args) static
Definition at line 6016 of file SemaExpr.cpp.
Referenced by clang::Sema::ConvertArgumentsForCall().
tryVectorConvertAndSplat()
static bool tryVectorConvertAndSplat (Sema & S, ExprResult * scalar, QualType scalarTy, QualType vectorEltTy, QualType vectorTy, unsigned & DiagID) static
Try to convert a value of non-vector type to a vector type by converting the type to the element type of the vector and then performing a splat.
If the language is OpenCL, we only use conversions that promote scalar rank; for C, Obj-C, and C++ we allow any real scalar conversion except for float->int.
OpenCL V2.0 6.2.6.p2: An error shall occur if any scalar operand type has greater rank than the type of the vector element.
Parameters
scalar - if non-null, actually perform the conversions
Returns
true if the operation fails (but without diagnosing the failure)
Definition at line 10353 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckVectorOperands().
unsupportedTypeConversion()
static bool unsupportedTypeConversion (const Sema & S, QualType LHSType, QualType RHSType) static
Diagnose attempts to convert between __float128, __ibm128 and long double if there is no support for such conversion.
Helper function of UsualArithmeticConversions().
Definition at line 1339 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckAssignmentConstraints(), and clang::Sema::CheckConditionalOperands().
warnOnSizeofOnArrayDecay()
static void warnOnSizeofOnArrayDecay (Sema & S, SourceLocation Loc, QualType T, const Expr * E) static
Check whether E is a pointer from a decayed array type (the decayed pointer type is equal to T) and emit a warning if it is.
Definition at line 4494 of file SemaExpr.cpp.
Referenced by clang::Sema::CheckUnaryExprOrTypeTraitOperand().