clang: lib/Tooling/Transformer/SourceCodeBuilders.cpp File Reference
SourceCodeBuilders.cpp File Reference
#include "clang/Tooling/Transformer/SourceCodeBuilders.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/ASTMatchers/ASTMatchers.h"
#include "clang/Tooling/Transformer/SourceCode.h"
#include "llvm/ADT/Twine.h"
#include <string>
Functions
static llvm::Optional< std::string > buildAccessForValue (const Expr &E, const ASTContext &Context)
static llvm::Optional< std::string > buildAccessForPointer (const Expr &E, const ASTContext &Context)
static const Expr * maybeGetOperatorObjectArg (const Expr &E, OverloadedOperatorKind K)
static bool treatLikePointer (QualType Ty, PLTClass C, ASTContext &Context)
Function Documentation
buildAccessForPointer()
static llvm::Optional<std::string> buildAccessForPointer (const Expr & E, const ASTContext & Context) static
Definition at line 158 of file SourceCodeBuilders.cpp.
References clang::tooling::getText(), clang::Expr::IgnoreParenImpCasts(), clang::tooling::needParensBeforeDotOrArrow(), and Text.
Referenced by clang::tooling::buildAccess(), and clang::tooling::buildArrow().
buildAccessForValue()
static llvm::Optional<std::string> buildAccessForValue (const Expr & E, const ASTContext & Context) static
Definition at line 132 of file SourceCodeBuilders.cpp.
References clang::tooling::getText(), clang::Expr::IgnoreParenImpCasts(), clang::tooling::needParensBeforeDotOrArrow(), and Text.
Referenced by clang::tooling::buildAccess(), and clang::tooling::buildDot().
maybeGetOperatorObjectArg()
static const Expr* maybeGetOperatorObjectArg (const Expr & E, OverloadedOperatorKind K) static
Definition at line 192 of file SourceCodeBuilders.cpp.
Referenced by clang::tooling::buildAccess().
treatLikePointer()
static bool treatLikePointer (QualType Ty, PLTClass C, ASTContext & Context) static
Definition at line 201 of file SourceCodeBuilders.cpp.
References clang::tooling::isKnownPointerLikeType(), clang::tooling::Pointer, and clang::tooling::Value.
Referenced by clang::tooling::buildAccess().