clang: lib/Tooling/Transformer/Stencil.cpp File Reference
Stencil.cpp File Reference
#include "clang/Tooling/Transformer/Stencil.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTTypeTraits.h"
#include "clang/AST/Expr.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/ASTMatchers/ASTMatchers.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Lex/Lexer.h"
#include "clang/Tooling/Transformer/SourceCode.h"
#include "clang/Tooling/Transformer/SourceCodeBuilders.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include <atomic>
#include <memory>
#include <string>
Functions
static llvm::Expected< DynTypedNode > getNode (const ast_matchers::BoundNodes &Nodes, StringRef Id)
static Error printNode (StringRef Id, const MatchFinder::MatchResult &Match, std::string *Result)
static bool isSmartPointerType (QualType Ty, ASTContext &Context)
static const Expr * isSmartDereference (const Expr &E, ASTContext &Context)
Function Documentation
getNode()
static llvm::Expected<DynTypedNode> getNode (const ast_matchers::BoundNodes & Nodes, StringRef Id) static
Definition at line 37 of file Stencil.cpp.
References Id, and Nodes.
Referenced by printNode().
isSmartDereference()
static const Expr* isSmartDereference (const Expr & E, ASTContext & Context) static
Definition at line 78 of file Stencil.cpp.
References clang::ast_matchers::cxxMethodDecl, clang::ast_matchers::cxxOperatorCallExpr, clang::ast_matchers::cxxRecordDecl, clang::ast_matchers::expr, clang::ast_matchers::hasOverloadedOperatorName(), clang::ast_matchers::match(), clang::ast_matchers::qualType, and clang::ast_matchers::type.
isSmartPointerType()
static bool isSmartPointerType (QualType Ty, ASTContext & Context) static
Definition at line 59 of file Stencil.cpp.
References clang::ast_matchers::anyOf, clang::ast_matchers::cxxMethodDecl, clang::ast_matchers::cxxRecordDecl, clang::ast_matchers::hasAnyName, clang::ast_matchers::hasDeclaration(), clang::ast_matchers::hasOverloadedOperatorName(), clang::ast_matchers::match(), clang::ast_matchers::qualType, and clang::ast_matchers::type.
printNode()
static Error printNode (StringRef Id, const MatchFinder::MatchResult & Match, std::string * Result) static
Definition at line 46 of file Stencil.cpp.
References clang::ast_matchers::MatchFinder::MatchResult::Context, clang::ASTContext::getLangOpts(), getNode(), Id, clang::ast_matchers::MatchFinder::MatchResult::Nodes, and string().