clang: lib/StaticAnalyzer/Checkers/StreamChecker.cpp File Reference
StreamChecker.cpp File Reference
#include "NoOwnershipChangeVisitor.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/ASTMatchers/ASTMatchers.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallDescription.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerHelpers.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramState.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramStateTrait.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h"
#include "llvm/ADT/Sequence.h"
#include <functional>
#include <optional>
Functions
static std::optional< int64_t > getKnownValue (ProgramStateRef State, SVal V)
static ProgramStateRef escapeByStartIndexAndCount (ProgramStateRef State, const CallEvent &Call, unsigned BlockCount, const SubRegion *Buffer, QualType ElemType, int64_t StartIndex, int64_t ElementCount)
Invalidate only the requested elements instead of the whole buffer.
static ProgramStateRef escapeArgs (ProgramStateRef State, CheckerContext &C, const CallEvent &Call, ArrayRef< unsigned int > EscapingArgs)
static QualType getPointeeType (const MemRegion *R)
static std::optional< NonLoc > getStartIndex (SValBuilder &SVB, const MemRegion *R)
static ProgramStateRef tryToInvalidateFReadBufferByElements (ProgramStateRef State, CheckerContext &C, const CallEvent &Call, NonLoc SizeVal, NonLoc NMembVal)
Function Documentation
escapeArgs()
static ProgramStateRef escapeArgs (ProgramStateRef State, CheckerContext & C, const CallEvent & Call, ArrayRef< unsigned int > EscapingArgs) static
Definition at line 850 of file StreamChecker.cpp.
References State.
escapeByStartIndexAndCount()
static ProgramStateRef escapeByStartIndexAndCount (ProgramStateRef State, const CallEvent & Call, unsigned BlockCount, const SubRegion * Buffer, QualType ElemType, int64_t StartIndex, int64_t ElementCount) static
Invalidate only the requested elements instead of the whole buffer.
This is basically a refinement of the more generic 'escapeArgs' or the plain old 'invalidateRegions'.
Definition at line 820 of file StreamChecker.cpp.
References clang::ento::SubRegion::getMemRegionManager(), and State.
Referenced by tryToInvalidateFReadBufferByElements().
getKnownValue()
static std::optional<int64_t> getKnownValue (ProgramStateRef State, SVal V) static
Definition at line 809 of file StreamChecker.cpp.
References clang::ento::SValBuilder::getKnownValue(), State, and V.
Referenced by tryToInvalidateFReadBufferByElements().
getPointeeType()
static QualType getPointeeType (const MemRegion * R) static
Definition at line 1037 of file StreamChecker.cpp.
Referenced by clang::Sema::CheckUnresolvedMemberAccess(), computeCachedProperties(), clang::LinkageComputer::computeTypeLinkageInfo(), clang::Sema::DefineImplicitMoveAssignment(), DiagnoseCallingConvCast(), clang::CodeGen::CodeGenFunction::EmitDynamicCast(), emitPointerArithmetic(), emitWritebackArg(), encodeTypeForFunctionPointerAuth(), evaluateLValueAsAllocSize(), clang::Expr::findBoundMemberType(), clang::CXXNewExpr::getAllocatedType(), clang::CXXDeleteExpr::getDestroyedType(), clang::Decl::getFunctionType(), clang::UnresolvedMemberExpr::getNamingClass(), clang::AtomicExpr::getValueType(), clang::ASTContext::getVariableArrayDecayedType(), clang::SemaSwift::handleAsyncAttr(), clang::CompletionContextHandler::handleDeclaration(), isDesignatorAtObjectEnd(), clang::SemaOpenMP::isOpenMPCapturedByRef(), MarkUsedTemplateParameters(), clang::ASTContext::mergeObjCGCQualifiers(), clang::ASTContext::mergeTypes(), clang::Sema::MergeVarDeclExceptionSpecs(), clang::Sema::PerformImplicitConversion(), clang::PointerType::Profile(), clang::BlockPointerType::Profile(), clang::MemberPointerType::Profile(), clang::ObjCObjectPointerType::Profile(), setObjCGCLValueClass(), and tryToInvalidateFReadBufferByElements().
getStartIndex()
static std::optional<NonLoc> getStartIndex (SValBuilder & SVB, const MemRegion * R) static
Definition at line 1049 of file StreamChecker.cpp.
References clang::ento::SValBuilder::getBasicValueFactory(), and clang::ento::BasicValueFactory::getIntValue().
Referenced by tryToInvalidateFReadBufferByElements().
tryToInvalidateFReadBufferByElements()
static ProgramStateRef tryToInvalidateFReadBufferByElements (ProgramStateRef State, CheckerContext & C, const CallEvent & Call, NonLoc SizeVal, NonLoc NMembVal) static
Definition at line 1069 of file StreamChecker.cpp.
References escapeByStartIndexAndCount(), getKnownValue(), getPointeeType(), clang::CharUnits::getQuantity(), getStartIndex(), clang::ASTContext::getTypeSizeInChars(), clang::QualType::isNull(), and State.