clang: clang::tooling::DiagnosticMessage Struct Reference
clang::tooling::DiagnosticMessage Struct Reference
Represents the diagnostic message with the error message associated and the information on the location of the problem.
#include "clang/Tooling/Core/Diagnostic.h"
Public Member Functions
DiagnosticMessage (llvm::StringRef Message="")
DiagnosticMessage (llvm::StringRef Message, const SourceManager &Sources, SourceLocation Loc)
Constructs a diagnostic message with anoffset to the diagnostic within the file where the problem occurred.
Public Attributes
std::string Message
std::string FilePath
unsigned FileOffset
llvm::StringMap< Replacements > Fix
Fixes for this diagnostic, grouped by file path.
llvm::SmallVector< FileByteRange, 1 > Ranges
Extra source ranges associated with the note, in addition to the location of the Message itself.
Detailed Description
Represents the diagnostic message with the error message associated and the information on the location of the problem.
Definition at line 42 of file Diagnostic.h.
Constructor & Destructor Documentation
DiagnosticMessage() [1/2]
clang::tooling::DiagnosticMessage::DiagnosticMessage (llvm::StringRef Message = "")
Definition at line 21 of file Diagnostic.cpp.
DiagnosticMessage() [2/2]
clang::tooling::DiagnosticMessage::DiagnosticMessage (llvm::StringRef Message, const SourceManager & Sources, SourceLocation Loc)
Constructs a diagnostic message with anoffset to the diagnostic within the file where the problem occurred.
Parameters
Loc Should be a file location, it is not meaningful for a macro location.
Definition at line 24 of file Diagnostic.cpp.
References FileOffset, FilePath, clang::SourceManager::getFilename(), clang::SourceManager::getFileOffset(), clang::SourceLocation::isFileID(), clang::SourceLocation::isValid(), and string().
Member Data Documentation
FileOffset
unsigned clang::tooling::DiagnosticMessage::FileOffset
Definition at line 56 of file Diagnostic.h.
Referenced by DiagnosticMessage(), and llvm::yaml::MappingTraits< clang::tooling::DiagnosticMessage >::mapping().
FilePath
std::string clang::tooling::DiagnosticMessage::FilePath
Definition at line 55 of file Diagnostic.h.
Referenced by DiagnosticMessage(), and llvm::yaml::MappingTraits< clang::tooling::DiagnosticMessage >::mapping().
Fix
llvm::StringMap<Replacements> clang::tooling::DiagnosticMessage::Fix
Fixes for this diagnostic, grouped by file path.
Definition at line 59 of file Diagnostic.h.
Referenced by llvm::yaml::MappingTraits< clang::tooling::DiagnosticMessage >::mapping(), and clang::tooling::selectFirstFix().
Message
std::string clang::tooling::DiagnosticMessage::Message
Definition at line 54 of file Diagnostic.h.
Referenced by llvm::yaml::MappingTraits< clang::tooling::DiagnosticMessage >::mapping().
Ranges
llvm::SmallVector<FileByteRange, 1> clang::tooling::DiagnosticMessage::Ranges
Extra source ranges associated with the note, in addition to the location of the Message itself.
Definition at line 63 of file Diagnostic.h.
Referenced by llvm::yaml::MappingTraits< clang::tooling::DiagnosticMessage >::mapping().
The documentation for this struct was generated from the following files:
include/clang/Tooling/Core/Diagnostic.h
lib/Tooling/Core/Diagnostic.cpp