clang: clang::CodeGen::DominatingLLVMValue Struct Reference
clang::CodeGen::DominatingLLVMValue Struct Reference
Helper class with most of the code for saving a value for a conditional expression cleanup.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Types
typedef llvm::PointerIntPair< llvm::Value *, 1, bool > saved_type
Static Public Member Functions
static bool needsSaving (llvm::Value *value)
Answer whether the given value needs extra work to be saved.
static saved_type save (CodeGenFunction &CGF, llvm::Value *value)
static llvm::Value * restore (CodeGenFunction &CGF, saved_type value)
Detailed Description
Helper class with most of the code for saving a value for a conditional expression cleanup.
Definition at line 147 of file CodeGenFunction.h.
Member Typedef Documentation
saved_type
typedef llvm::PointerIntPair<llvm::Value*, 1, bool> clang::CodeGen::DominatingLLVMValue::saved_type
Definition at line 148 of file CodeGenFunction.h.
Member Function Documentation
needsSaving()
static bool clang::CodeGen::DominatingLLVMValue::needsSaving (llvm::Value * value) inline static
Answer whether the given value needs extra work to be saved.
Definition at line 151 of file CodeGenFunction.h.
Referenced by clang::CodeGen::DominatingValue< Address >::needsSaving(), and save().
restore()
llvm::Value * clang::CodeGen::DominatingLLVMValue::restore (CodeGenFunction & CGF, saved_type value) inline static
Definition at line 4910 of file CodeGenFunction.h.
References clang::CodeGen::CodeGenFunction::Builder, and clang::CodeGen::CGBuilderTy::CreateAlignedLoad().
Referenced by clang::CodeGen::DominatingPointer< T, true >::restore(), and clang::CodeGen::DominatingValue< Address >::restore().
save()
DominatingLLVMValue::saved_type clang::CodeGen::DominatingLLVMValue::save (CodeGenFunction & CGF, llvm::Value * value) inline static
Definition at line 4897 of file CodeGenFunction.h.
References clang::interp::align(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateStore(), clang::CodeGen::CodeGenFunction::CreateTempAlloca(), clang::CharUnits::fromQuantity(), clang::CodeGen::CodeGenModule::getDataLayout(), clang::CodeGen::Address::getPointer(), and needsSaving().
Referenced by clang::CodeGen::DominatingValue< Address >::save().
The documentation for this struct was generated from the following file:
lib/CodeGen/CodeGenFunction.h