clang: clang::ReplCodeCompleter Struct Reference
clang::ReplCodeCompleter Struct Reference
#include "clang/Interpreter/CodeCompletion.h"
Public Member Functions
ReplCodeCompleter ()=default
void codeComplete (CompilerInstance *InterpCI, llvm::StringRef Content, unsigned Line, unsigned Col, const CompilerInstance *ParentCI, std::vector< std::string > &CCResults)
Public Attributes
std::string Prefix
Detailed Description
Definition at line 26 of file CodeCompletion.h.
Constructor & Destructor Documentation
ReplCodeCompleter()
clang::ReplCodeCompleter::ReplCodeCompleter () default
Member Function Documentation
codeComplete()
void clang::ReplCodeCompleter::codeComplete (CompilerInstance * InterpCI, llvm::StringRef Content, unsigned Line, unsigned Col, const CompilerInstance * ParentCI, std::vector< std::string > & CCResults)
Parameters
InterpCI [in] The compiler instance that is used to trigger code completion
Content [in] The string where code completion is triggered.
Line [in] The line number of the code completion point.
Col [in] The column number of the code completion point.
ParentCI [in] The running interpreter compiler instance that provides ASTContexts.
CCResults [out] The completion results.
Definition at line 355 of file CodeCompletion.cpp.
References clang::CodeCompletionFileName, clang::CXX, clang::CompilerInstance::getDiagnosticsPtr(), clang::CompilerInstance::getFrontendOpts(), clang::CompilerInstance::getInvocationPtr(), clang::FrontendOptions::Inputs, clang::ASTUnit::LoadFromCompilerInvocationAction(), and clang::InputKind::Source.
Member Data Documentation
Prefix
std::string clang::ReplCodeCompleter::Prefix
Definition at line 28 of file CodeCompletion.h.
The documentation for this struct was generated from the following files:
include/clang/Interpreter/CodeCompletion.h
lib/Interpreter/CodeCompletion.cpp