clang: clang::interp::InitMap Struct Reference
clang::interp::InitMap Struct Reference
Bitfield tracking the initialisation status of elements of primitive arrays.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Descriptor.h"
Public Member Functions
bool initialize (unsigned I)
Initializes an element. Returns true when object if fully initialized.
bool isInitialized (unsigned I)
Checks if an element was initialized.
Static Public Member Functions
static InitMap * allocate (unsigned N)
Allocates a map holding N elements.
Detailed Description
Bitfield tracking the initialisation status of elements of primitive arrays.
A pointer to this is embedded at the end of all primitive arrays. If the map was not yet created and nothing was initialized, the pointer to this structure is 0. If the object was fully initialized, the pointer is -1.
Definition at line 189 of file Descriptor.h.
Member Function Documentation
allocate()
InitMap * InitMap::allocate (unsigned N) static
Allocates a map holding N elements.
Definition at line 288 of file Descriptor.cpp.
References clang::interp::align().
Referenced by clang::interp::Pointer::initialize().
initialize()
bool InitMap::initialize (unsigned I)
Initializes an element. Returns true when object if fully initialized.
Definition at line 272 of file Descriptor.cpp.
Referenced by clang::interp::Pointer::initialize().
isInitialized()
bool InitMap::isInitialized (unsigned I)
Checks if an element was initialized.
Definition at line 282 of file Descriptor.cpp.
Referenced by clang::interp::Pointer::isInitialized().
The documentation for this struct was generated from the following files:
lib/AST/Interp/Descriptor.h
lib/AST/Interp/Descriptor.cpp