clang: clang::edit::Commit::Edit Struct Reference
clang::edit::Commit::Edit Struct Reference
#include "clang/Edit/Commit.h"
Public Member Functions
SourceLocation getFileLocation (SourceManager &SM) const
CharSourceRange getFileRange (SourceManager &SM) const
CharSourceRange getInsertFromRange (SourceManager &SM) const
Public Attributes
EditKind Kind
StringRef Text
SourceLocation OrigLoc
FileOffset Offset
FileOffset InsertFromRangeOffs
unsigned Length
bool BeforePrev
Detailed Description
Definition at line 37 of file Commit.h.
Member Function Documentation
getFileLocation()
SourceLocation Commit::Edit::getFileLocation (SourceManager & SM) const
Definition at line 24 of file Commit.cpp.
References clang::edit::FileOffset::getFID(), clang::SourceLocation::getLocWithOffset(), clang::edit::FileOffset::getOffset(), clang::SourceLocation::isFileID(), Offset, and SM.
getFileRange()
CharSourceRange Commit::Edit::getFileRange (SourceManager & SM) const
Definition at line 31 of file Commit.cpp.
References clang::CharSourceRange::getCharRange(), clang::SourceLocation::getLocWithOffset(), and SM.
getInsertFromRange()
CharSourceRange Commit::Edit::getInsertFromRange (SourceManager & SM) const
Definition at line 36 of file Commit.cpp.
References clang::CharSourceRange::getCharRange(), clang::SourceLocation::getLocWithOffset(), clang::SourceLocation::isFileID(), and SM.
Member Data Documentation
BeforePrev
bool clang::edit::Commit::Edit::BeforePrev
Definition at line 44 of file Commit.h.
InsertFromRangeOffs
FileOffset clang::edit::Commit::Edit::InsertFromRangeOffs
Definition at line 42 of file Commit.h.
Kind
EditKind clang::edit::Commit::Edit::Kind
Definition at line 38 of file Commit.h.
Length
unsigned clang::edit::Commit::Edit::Length
Definition at line 43 of file Commit.h.
Offset
FileOffset clang::edit::Commit::Edit::Offset
Definition at line 41 of file Commit.h.
Referenced by getFileLocation().
OrigLoc
SourceLocation clang::edit::Commit::Edit::OrigLoc
Definition at line 40 of file Commit.h.
Text
StringRef clang::edit::Commit::Edit::Text
Definition at line 39 of file Commit.h.
The documentation for this struct was generated from the following files:
include/clang/Edit/Commit.h
lib/Edit/Commit.cpp