clang: clang::CodeGen::CallArg Struct Reference
clang::CodeGen::CallArg Struct Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCall.h"
Public Member Functions
CallArg (RValue rv, QualType ty)
CallArg (LValue lv, QualType ty)
bool hasLValue () const
QualType getType () const
RValue getRValue (CodeGenFunction &CGF) const
LValue getKnownLValue () const
RValue getKnownRValue () const
void setRValue (RValue _RV)
bool isAggregate () const
void copyInto (CodeGenFunction &CGF, Address A) const
Public Attributes
QualType Ty
RValue RV
LValue LV
Detailed Description
Definition at line 217 of file CGCall.h.
Constructor & Destructor Documentation
CallArg() [1/2]
clang::CodeGen::CallArg::CallArg (RValue rv, QualType ty) inline
Definition at line 231 of file CGCall.h.
CallArg() [2/2]
clang::CodeGen::CallArg::CallArg (LValue lv, QualType ty) inline
Definition at line 233 of file CGCall.h.
Member Function Documentation
copyInto()
void CallArg::copyInto (CodeGenFunction & CGF, Address A) const
Definition at line 4358 of file CGCall.cpp.
References clang::CodeGen::AggValueSlot::DoesNotOverlap, clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::EmitStoreOfComplex(), clang::CodeGen::CodeGenFunction::EmitStoreOfScalar(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::RValue::getAggregateAddress(), clang::CodeGen::RValue::getComplexVal(), clang::CodeGen::RValue::getScalarVal(), clang::CodeGen::RValue::isComplex(), clang::CodeGen::RValue::isScalar(), clang::CodeGen::RValue::isVolatileQualified(), clang::CodeGen::LValue::isVolatileQualified(), LV, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), RV, and Ty.
getKnownLValue()
LValue clang::CodeGen::CallArg::getKnownLValue () const inline
Definition at line 242 of file CGCall.h.
References LV.
getKnownRValue()
RValue clang::CodeGen::CallArg::getKnownRValue () const inline
Definition at line 246 of file CGCall.h.
References RV.
getRValue()
RValue CallArg::getRValue (CodeGenFunction & CGF) const
Returns
an independent RValue. If the CallArg contains an LValue, a temporary copy is returned.
Definition at line 4348 of file CGCall.cpp.
References clang::CodeGen::CodeGenFunction::CreateMemTemp(), clang::CodeGen::AggValueSlot::DoesNotOverlap, clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::RValue::getAggregate(), clang::CodeGen::LValue::isVolatile(), LV, clang::CodeGen::CodeGenFunction::MakeAddrLValue(), RV, and Ty.
getType()
QualType clang::CodeGen::CallArg::getType () const inline
Definition at line 236 of file CGCall.h.
References Ty.
hasLValue()
bool clang::CodeGen::CallArg::hasLValue () const inline
Definition at line 235 of file CGCall.h.
isAggregate()
bool clang::CodeGen::CallArg::isAggregate () const inline
Definition at line 255 of file CGCall.h.
References clang::CodeGen::RValue::isAggregate(), and RV.
setRValue()
void clang::CodeGen::CallArg::setRValue (RValue _RV) inline
Definition at line 250 of file CGCall.h.
References RV.
Member Data Documentation
LV
LValue clang::CodeGen::CallArg::LV
Definition at line 221 of file CGCall.h.
Referenced by copyInto(), getKnownLValue(), and getRValue().
RV
RValue clang::CodeGen::CallArg::RV
Definition at line 220 of file CGCall.h.
Referenced by copyInto(), getKnownRValue(), getRValue(), isAggregate(), and setRValue().
Ty
QualType clang::CodeGen::CallArg::Ty
Definition at line 230 of file CGCall.h.
Referenced by copyInto(), getRValue(), and getType().
The documentation for this struct was generated from the following files:
lib/CodeGen/CGCall.h
lib/CodeGen/CGCall.cpp