clang: clang::FunctionEffectDifferences Struct Reference
clang::FunctionEffectDifferences Struct Reference
#include "clang/Sema/Sema.h"
Public Member Functions
FunctionEffectDifferences (const FunctionEffectsRef &Old, const FunctionEffectsRef &New)
Caller should short-circuit by checking for equality first.
Detailed Description
Definition at line 528 of file Sema.h.
Constructor & Destructor Documentation
FunctionEffectDifferences()
FunctionEffectDifferences::FunctionEffectDifferences (const FunctionEffectsRef & Old, const FunctionEffectsRef & New)
Caller should short-circuit by checking for equality first.
Definition at line 2859 of file Sema.cpp.
References clang::FunctionEffectDiff::Added, clang::FunctionEffectsRef::begin(), clang::FunctionEffectWithCondition::Cond, clang::FunctionEffectDiff::ConditionMismatch, clang::FunctionEffectWithCondition::Effect, clang::FunctionEffectsRef::end(), clang::EffectConditionExpr::getCondition(), clang::FunctionEffect::kind(), and clang::FunctionEffectDiff::Removed.
The documentation for this struct was generated from the following files:
include/clang/Sema/Sema.h
lib/Sema/Sema.cpp