clang: clang::serialization::UnderalignedInt64 Struct Reference
clang::serialization::UnderalignedInt64 Struct Reference
Offset in the AST file.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
UnderalignedInt64 ()=default
UnderalignedInt64 (uint64_t BitOffset)
void setBitOffset (uint64_t Offset)
uint64_t getBitOffset () const
Public Attributes
uint32_t BitOffsetLow = 0
uint32_t BitOffsetHigh = 0
Detailed Description
Offset in the AST file.
Use splitted 64-bit integer into low/high parts to keep structure alignment 32-bit (it is important because blobs in bitstream are 32-bit aligned). This structure is serialized "as is" to the AST file.
Definition at line 223 of file ASTBitCodes.h.
Constructor & Destructor Documentation
UnderalignedInt64() [1/2]
clang::serialization::UnderalignedInt64::UnderalignedInt64 () default
UnderalignedInt64() [2/2]
clang::serialization::UnderalignedInt64::UnderalignedInt64 (uint64_t BitOffset) inline
Definition at line 228 of file ASTBitCodes.h.
References setBitOffset().
Member Function Documentation
getBitOffset()
uint64_t clang::serialization::UnderalignedInt64::getBitOffset () const inline
Definition at line 235 of file ASTBitCodes.h.
References BitOffsetHigh, and BitOffsetLow.
Referenced by clang::serialization::DeclOffset::getBitOffset().
setBitOffset()
void clang::serialization::UnderalignedInt64::setBitOffset (uint64_t Offset) inline
Definition at line 230 of file ASTBitCodes.h.
References BitOffsetHigh, BitOffsetLow, and Offset.
Referenced by clang::serialization::DeclOffset::setBitOffset(), and UnderalignedInt64().
Member Data Documentation
BitOffsetHigh
uint32_t clang::serialization::UnderalignedInt64::BitOffsetHigh = 0
Definition at line 225 of file ASTBitCodes.h.
Referenced by getBitOffset(), and setBitOffset().
BitOffsetLow
uint32_t clang::serialization::UnderalignedInt64::BitOffsetLow = 0
Definition at line 224 of file ASTBitCodes.h.
Referenced by getBitOffset(), and setBitOffset().
The documentation for this struct was generated from the following file:
include/clang/Serialization/ASTBitCodes.h