clang: llvm::DenseMapInfo< clang::FileEntryRef > Struct Reference
llvm::DenseMapInfo< clang::FileEntryRef > Struct Reference
Specialisation of DenseMapInfo for FileEntryRef.
#include "clang/Basic/FileEntry.h"
Static Public Member Functions
static clang::FileEntryRef getEmptyKey ()
static clang::FileEntryRef getTombstoneKey ()
static unsigned getHashValue (clang::FileEntryRef Val)
static bool isEqual (clang::FileEntryRef LHS, clang::FileEntryRef RHS)
static unsigned getHashValue (const clang::FileEntry *Val)
Support for finding const FileEntry * in a DenseMap<FileEntryRef, T>.
static bool isEqual (const clang::FileEntry *LHS, clang::FileEntryRef RHS)
Detailed Description
Specialisation of DenseMapInfo for FileEntryRef.
Definition at line 239 of file FileEntry.h.
Member Function Documentation
getEmptyKey()
static clang::FileEntryRef llvm::DenseMapInfo< clang::FileEntryRef >::getEmptyKey () inline static
Definition at line 240 of file FileEntry.h.
getHashValue() [1/2]
static unsigned llvm::DenseMapInfo< clang::FileEntryRef >::getHashValue (clang::FileEntryRef Val) inline static
Definition at line 248 of file FileEntry.h.
References clang::hash_value().
getHashValue() [2/2]
static unsigned llvm::DenseMapInfo< clang::FileEntryRef >::getHashValue (const clang::FileEntry * Val) inline static
Support for finding const FileEntry * in a DenseMap<FileEntryRef, T>.
Definition at line 267 of file FileEntry.h.
References llvm::hash_value().
getTombstoneKey()
static clang::FileEntryRef llvm::DenseMapInfo< clang::FileEntryRef >::getTombstoneKey () inline static
Definition at line 244 of file FileEntry.h.
isEqual() [1/2]
static bool llvm::DenseMapInfo< clang::FileEntryRef >::isEqual (clang::FileEntryRef LHS, clang::FileEntryRef RHS) inline static
Definition at line 252 of file FileEntry.h.
References clang::FileEntryRef::isSameRef().
isEqual() [2/2]
static bool llvm::DenseMapInfo< clang::FileEntryRef >::isEqual (const clang::FileEntry * LHS, clang::FileEntryRef RHS) inline static
Definition at line 270 of file FileEntry.h.
The documentation for this struct was generated from the following file:
include/clang/Basic/FileEntry.h