clang: llvm::DenseMapInfo< clang::SourceLocation > Struct Reference
llvm::DenseMapInfo< clang::SourceLocation > Struct Reference
Define DenseMapInfo so that SourceLocation's can be used as keys in DenseMap and DenseSet.
#include "clang/Basic/SourceLocation.h"
Static Public Member Functions
static clang::SourceLocation getEmptyKey ()
static clang::SourceLocation getTombstoneKey ()
static unsigned getHashValue (clang::SourceLocation Loc)
static bool isEqual (clang::SourceLocation LHS, clang::SourceLocation RHS)
Detailed Description
Define DenseMapInfo so that SourceLocation's can be used as keys in DenseMap and DenseSet.
This trait class is eqivalent to DenseMapInfo<unsigned> which uses SourceLocation::ID is used as a key.
Definition at line 490 of file SourceLocation.h.
Member Function Documentation
getEmptyKey()
static clang::SourceLocation llvm::DenseMapInfo< clang::SourceLocation >::getEmptyKey () inline static
Definition at line 491 of file SourceLocation.h.
References clang::SourceLocation::getFromRawEncoding().
getHashValue()
static unsigned llvm::DenseMapInfo< clang::SourceLocation >::getHashValue (clang::SourceLocation Loc) inline static
Definition at line 499 of file SourceLocation.h.
References clang::SourceLocation::getHashValue().
getTombstoneKey()
static clang::SourceLocation llvm::DenseMapInfo< clang::SourceLocation >::getTombstoneKey () inline static
Definition at line 495 of file SourceLocation.h.
References clang::SourceLocation::getFromRawEncoding().
isEqual()
static bool llvm::DenseMapInfo< clang::SourceLocation >::isEqual (clang::SourceLocation LHS, clang::SourceLocation RHS) inline static
Definition at line 503 of file SourceLocation.h.
The documentation for this struct was generated from the following file:
include/clang/Basic/SourceLocation.h