clang: clang::ast_matchers::dynamic::internal::ArgTypeTraits< llvm::Regex::RegexFlags > Struct Reference
clang::ast_matchers::dynamic::internal::ArgTypeTraits< llvm::Regex::RegexFlags > Struct Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/ASTMatchers/Dynamic/Marshallers.h"
Static Public Member Functions
static bool hasCorrectType (const VariantValue &Value)
static bool hasCorrectValue (const VariantValue &Value)
static llvm::Regex::RegexFlags get (const VariantValue &Value)
static ArgKind getKind ()
static std::optional< std::string > getBestGuess (const VariantValue &Value)
Detailed Description
Definition at line 220 of file Marshallers.h.
Member Function Documentation
get()
static llvm::Regex::RegexFlags clang::ast_matchers::dynamic::internal::ArgTypeTraits< llvm::Regex::RegexFlags >::get (const VariantValue & Value) inline static
Definition at line 232 of file Marshallers.h.
References clang::installapi::getFlags().
getBestGuess()
std::optional< std::string > clang::ast_matchers::dynamic::internal::ArgTypeTraits< llvm::Regex::RegexFlags >::getBestGuess (const VariantValue & Value) static
Definition at line 155 of file Marshallers.cpp.
References getCloseRegexMatch().
getKind()
static ArgKind clang::ast_matchers::dynamic::internal::ArgTypeTraits< llvm::Regex::RegexFlags >::getKind () inline static
Definition at line 236 of file Marshallers.h.
References clang::ast_matchers::dynamic::ArgKind::AK_String.
hasCorrectType()
static bool clang::ast_matchers::dynamic::internal::ArgTypeTraits< llvm::Regex::RegexFlags >::hasCorrectType (const VariantValue & Value) inline static
Definition at line 225 of file Marshallers.h.
hasCorrectValue()
static bool clang::ast_matchers::dynamic::internal::ArgTypeTraits< llvm::Regex::RegexFlags >::hasCorrectValue (const VariantValue & Value) inline static
Definition at line 228 of file Marshallers.h.
References clang::installapi::getFlags().
The documentation for this struct was generated from the following files:
lib/ASTMatchers/Dynamic/Marshallers.h
lib/ASTMatchers/Dynamic/Marshallers.cpp