clang: clang::WeakInfo::DenseMapInfoByAliasOnly Struct Reference
clang::WeakInfo::DenseMapInfoByAliasOnly Struct Reference
#include "clang/Sema/Weak.h"
Static Public Member Functions
static WeakInfo getEmptyKey ()
static WeakInfo getTombstoneKey ()
static unsigned getHashValue (const WeakInfo &W)
static bool isEqual (const WeakInfo &LHS, const WeakInfo &RHS)
Detailed Description
Definition at line 37 of file Weak.h.
Member Function Documentation
getEmptyKey()
static WeakInfo clang::WeakInfo::DenseMapInfoByAliasOnly::getEmptyKey () inline static
Definition at line 39 of file Weak.h.
References clang::WeakInfo::WeakInfo().
getHashValue()
static unsigned clang::WeakInfo::DenseMapInfoByAliasOnly::getHashValue (const WeakInfo & W) inline static
Definition at line 45 of file Weak.h.
References clang::WeakInfo::getAlias().
getTombstoneKey()
static WeakInfo clang::WeakInfo::DenseMapInfoByAliasOnly::getTombstoneKey () inline static
Definition at line 42 of file Weak.h.
References clang::WeakInfo::WeakInfo().
isEqual()
static bool clang::WeakInfo::DenseMapInfoByAliasOnly::isEqual (const WeakInfo & LHS, const WeakInfo & RHS) inline static
Definition at line 48 of file Weak.h.
References clang::WeakInfo::getAlias().
The documentation for this struct was generated from the following file:
include/clang/Sema/Weak.h