clang: clang::CodeGen::CodeGenFunction::OMPTargetDataInfo Struct Reference
clang::CodeGen::CodeGenFunction::OMPTargetDataInfo Struct Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
OMPTargetDataInfo ()=default
OMPTargetDataInfo (Address BasePointersArray, Address PointersArray, Address SizesArray, Address MappersArray, unsigned NumberOfTargetItems)
Public Attributes
Address BasePointersArray = Address::invalid()
Address PointersArray = Address::invalid()
Address SizesArray = Address::invalid()
Address MappersArray = Address::invalid()
unsigned NumberOfTargetItems = 0
Detailed Description
Definition at line 3727 of file CodeGenFunction.h.
Constructor & Destructor Documentation
OMPTargetDataInfo() [1/2]
clang::CodeGen::CodeGenFunction::OMPTargetDataInfo::OMPTargetDataInfo () explicit default
OMPTargetDataInfo() [2/2]
clang::CodeGen::CodeGenFunction::OMPTargetDataInfo::OMPTargetDataInfo (Address BasePointersArray, Address PointersArray, Address SizesArray, Address MappersArray, unsigned NumberOfTargetItems) inline
Definition at line 3734 of file CodeGenFunction.h.
Member Data Documentation
BasePointersArray
Address clang::CodeGen::CodeGenFunction::OMPTargetDataInfo::BasePointersArray = Address::invalid()
Definition at line 3728 of file CodeGenFunction.h.
Referenced by emitTargetCallKernelLaunch(), and clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall().
MappersArray
Address clang::CodeGen::CodeGenFunction::OMPTargetDataInfo::MappersArray = Address::invalid()
Definition at line 3731 of file CodeGenFunction.h.
Referenced by emitTargetCallKernelLaunch(), and clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall().
NumberOfTargetItems
unsigned clang::CodeGen::CodeGenFunction::OMPTargetDataInfo::NumberOfTargetItems = 0
Definition at line 3732 of file CodeGenFunction.h.
Referenced by emitTargetCallKernelLaunch(), and clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall().
PointersArray
Address clang::CodeGen::CodeGenFunction::OMPTargetDataInfo::PointersArray = Address::invalid()
Definition at line 3729 of file CodeGenFunction.h.
Referenced by emitTargetCallKernelLaunch(), and clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall().
SizesArray
Address clang::CodeGen::CodeGenFunction::OMPTargetDataInfo::SizesArray = Address::invalid()
Definition at line 3730 of file CodeGenFunction.h.
Referenced by emitTargetCallKernelLaunch(), and clang::CodeGen::CGOpenMPRuntime::emitTargetDataStandAloneCall().
The documentation for this struct was generated from the following file:
lib/CodeGen/CodeGenFunction.h