clang: clang::CanProxyAdaptor< FunctionProtoType > Struct Reference
clang::CanProxyAdaptor< FunctionProtoType > Struct Reference
#include "clang/AST/CanonicalType.h"
Public Types
using param_type_iterator = CanTypeIterator< FunctionProtoType::param_type_iterator >
Public Member Functions
LLVM_CLANG_CANPROXY_SIMPLE_ACCESSOR (ArrayRef< FunctionProtoType::ExtParameterInfo >, getExtParameterInfos) CanQualType getParamType(unsigned i) const
param_type_iterator param_type_begin () const
param_type_iterator param_type_end () const
Public Member Functions inherited from clang::CanProxyBase< FunctionProtoType >
const FunctionProtoType * getTypePtr () const
Retrieve the pointer to the underlying Type.
operator const FunctionProtoType * () const
Implicit conversion to the underlying pointer.
CanProxy< U > getAs () const
Try to convert the given canonical type to a specific structural type.
const CanProxyAdaptor< FunctionProtoType > * operator-> () const
Retrieve the proxy-adaptor type.
Additional Inherited Members
Protected Attributes inherited from clang::CanProxyBase< FunctionProtoType >
CanQual< FunctionProtoType > Stored
Detailed Description
Definition at line 499 of file CanonicalType.h.
Member Typedef Documentation
param_type_iterator
using clang::CanProxyAdaptor< FunctionProtoType >::param_type_iterator = CanTypeIterator<FunctionProtoType::param_type_iterator>
Definition at line 515 of file CanonicalType.h.
Member Function Documentation
LLVM_CLANG_CANPROXY_SIMPLE_ACCESSOR()
clang::CanProxyAdaptor< FunctionProtoType >::LLVM_CLANG_CANPROXY_SIMPLE_ACCESSOR (ArrayRef< FunctionProtoType::ExtParameterInfo > , getExtParameterInfos) const inline
Definition at line 505 of file CanonicalType.h.
References clang::CanQual< Type >::CreateUnsafe(), getParamType(), and clang::CanProxyBase< T >::getTypePtr().
param_type_begin()
param_type_iterator clang::CanProxyAdaptor< FunctionProtoType >::param_type_begin () const inline
Definition at line 518 of file CanonicalType.h.
References clang::CanProxyBase< T >::getTypePtr().
param_type_end()
param_type_iterator clang::CanProxyAdaptor< FunctionProtoType >::param_type_end () const inline
Definition at line 522 of file CanonicalType.h.
References clang::CanProxyBase< T >::getTypePtr().
The documentation for this struct was generated from the following file:
include/clang/AST/CanonicalType.h