clang: clang::CodeGen::CodeGenFunction::CleanupDeactivationScope Struct Reference
clang::CodeGen::CodeGenFunction::CleanupDeactivationScope Struct Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
CleanupDeactivationScope (CodeGenFunction &CGF)
void ForceDeactivate ()
~CleanupDeactivationScope ()
Public Attributes
CodeGenFunction & CGF
size_t OldDeactivateCleanupStackSize
bool Deactivated
Detailed Description
Definition at line 674 of file CodeGenFunction.h.
Constructor & Destructor Documentation
CleanupDeactivationScope()
clang::CodeGen::CodeGenFunction::CleanupDeactivationScope::CleanupDeactivationScope (CodeGenFunction & CGF) inline
Definition at line 678 of file CodeGenFunction.h.
~CleanupDeactivationScope()
clang::CodeGen::CodeGenFunction::CleanupDeactivationScope::~CleanupDeactivationScope () inline
Definition at line 695 of file CodeGenFunction.h.
References Deactivated, and ForceDeactivate().
Member Function Documentation
ForceDeactivate()
void clang::CodeGen::CodeGenFunction::CleanupDeactivationScope::ForceDeactivate () inline
Definition at line 683 of file CodeGenFunction.h.
References Deactivated.
Referenced by clang::CodeGen::CodeGenFunction::EmitNewArrayInitializer(), and ~CleanupDeactivationScope().
Member Data Documentation
CGF
CodeGenFunction& clang::CodeGen::CodeGenFunction::CleanupDeactivationScope::CGF
Definition at line 675 of file CodeGenFunction.h.
Deactivated
bool clang::CodeGen::CodeGenFunction::CleanupDeactivationScope::Deactivated
Definition at line 677 of file CodeGenFunction.h.
Referenced by ForceDeactivate(), and ~CleanupDeactivationScope().
OldDeactivateCleanupStackSize
size_t clang::CodeGen::CodeGenFunction::CleanupDeactivationScope::OldDeactivateCleanupStackSize
Definition at line 676 of file CodeGenFunction.h.
The documentation for this struct was generated from the following file:
lib/CodeGen/CodeGenFunction.h