clang: clang::ForwardDataflowWorklist Struct Reference
clang::ForwardDataflowWorklist Struct Reference
A worklist implementation for forward dataflow analysis.
#include "clang/Analysis/FlowSensitive/DataflowWorklist.h"
Public Member Functions
ForwardDataflowWorklist (const CFG &Cfg, PostOrderCFGView *POV)
ForwardDataflowWorklist (const CFG &Cfg, AnalysisDeclContext &Ctx)
void enqueueSuccessors (const CFGBlock *Block)
Public Member Functions inherited from clang::DataflowWorklistBase< ReversePostOrderCompare, 20 >
DataflowWorklistBase (const CFG &Cfg, PostOrderCFGView *POV, ReversePostOrderCompare C)
const PostOrderCFGView * getCFGView () const
void enqueueBlock (const CFGBlock *Block)
const CFGBlock * dequeue ()
Detailed Description
A worklist implementation for forward dataflow analysis.
The enqueued blocks will be dequeued in reverse post order. The worklist cannot contain the same block multiple times at once.
Definition at line 62 of file DataflowWorklist.h.
Constructor & Destructor Documentation
ForwardDataflowWorklist() [1/2]
clang::ForwardDataflowWorklist::ForwardDataflowWorklist (const CFG & Cfg, PostOrderCFGView * POV) inline
Definition at line 64 of file DataflowWorklist.h.
References clang::PostOrderCFGView::getComparator().
ForwardDataflowWorklist() [2/2]
clang::ForwardDataflowWorklist::ForwardDataflowWorklist (const CFG & Cfg, AnalysisDeclContext & Ctx) inline
Definition at line 68 of file DataflowWorklist.h.
Member Function Documentation
enqueueSuccessors()
void clang::ForwardDataflowWorklist::enqueueSuccessors (const CFGBlock * Block) inline
Definition at line 71 of file DataflowWorklist.h.
References clang::Block, and clang::DataflowWorklistBase< ReversePostOrderCompare, 20 >::enqueueBlock().
Referenced by clang::dataflow::runTypeErasedDataflowAnalysis(), and clang::runUninitializedVariablesAnalysis().
The documentation for this struct was generated from the following file:
include/clang/Analysis/FlowSensitive/DataflowWorklist.h