clang: clang::dependency_directives_scan::Token Struct Reference
clang::dependency_directives_scan::Token Struct Reference
Token lexed as part of dependency directive scanning.
#include "clang/Lex/DependencyDirectivesScanner.h"
Public Member Functions
Token (unsigned Offset, unsigned Length, tok::TokenKind Kind, unsigned short Flags)
unsigned getEnd () const
bool is (tok::TokenKind K) const
bool isNot (tok::TokenKind K) const
bool isOneOf (tok::TokenKind K1, tok::TokenKind K2) const
template<typename... Ts>
bool isOneOf (tok::TokenKind K1, Ts... Ks) const
Public Attributes
unsigned Offset
Offset into the original source input.
unsigned Length
tok::TokenKind Kind
unsigned short Flags
Detailed Description
Token lexed as part of dependency directive scanning.
Definition at line 34 of file DependencyDirectivesScanner.h.
Constructor & Destructor Documentation
Token()
clang::dependency_directives_scan::Token::Token (unsigned Offset, unsigned Length, tok::TokenKind Kind, unsigned short Flags) inline
Definition at line 41 of file DependencyDirectivesScanner.h.
Member Function Documentation
getEnd()
unsigned clang::dependency_directives_scan::Token::getEnd () const inline
Definition at line 45 of file DependencyDirectivesScanner.h.
References Length, and Offset.
Referenced by clang::printDependencyDirectivesAsSource().
is()
bool clang::dependency_directives_scan::Token::is (tok::TokenKind K) const inline
Definition at line 47 of file DependencyDirectivesScanner.h.
References Kind.
Referenced by isOneOf().
isNot()
bool clang::dependency_directives_scan::Token::isNot (tok::TokenKind K) const inline
Definition at line 48 of file DependencyDirectivesScanner.h.
References Kind.
isOneOf() [1/2]
bool clang::dependency_directives_scan::Token::isOneOf (tok::TokenKind K1, tok::TokenKind K2) const inline
Definition at line 49 of file DependencyDirectivesScanner.h.
References is().
Referenced by isOneOf(), and clang::printDependencyDirectivesAsSource().
isOneOf() [2/2]
template<typename... Ts> bool clang::dependency_directives_scan::Token::isOneOf (tok::TokenKind K1, Ts... Ks) const inline
Definition at line 52 of file DependencyDirectivesScanner.h.
References is(), and isOneOf().
Member Data Documentation
Flags
unsigned short clang::dependency_directives_scan::Token::Flags
Definition at line 39 of file DependencyDirectivesScanner.h.
Kind
tok::TokenKind clang::dependency_directives_scan::Token::Kind
Definition at line 38 of file DependencyDirectivesScanner.h.
Referenced by is(), isNot(), and clang::printDependencyDirectivesAsSource().
Length
unsigned clang::dependency_directives_scan::Token::Length
Definition at line 37 of file DependencyDirectivesScanner.h.
Referenced by getEnd().
Offset
unsigned clang::dependency_directives_scan::Token::Offset
Offset into the original source input.
Definition at line 36 of file DependencyDirectivesScanner.h.
Referenced by getEnd(), and clang::printDependencyDirectivesAsSource().
The documentation for this struct was generated from the following file:
include/clang/Lex/DependencyDirectivesScanner.h