clang: clang::ThisAdjustment Struct Reference
clang::ThisAdjustment Struct Reference
A this pointer adjustment.
#include "clang/Basic/Thunk.h"
Classes
union VirtualAdjustment
Holds the ABI-specific information about the virtual this adjustment, if needed.
Public Member Functions
ThisAdjustment ()
bool isEmpty () const
Public Attributes
int64_t NonVirtual
The non-virtual adjustment from the derived object to its nearest virtual base.
union clang::ThisAdjustment::VirtualAdjustment Virtual
Friends
bool operator== (const ThisAdjustment &LHS, const ThisAdjustment &RHS)
bool operator!= (const ThisAdjustment &LHS, const ThisAdjustment &RHS)
bool operator< (const ThisAdjustment &LHS, const ThisAdjustment &RHS)
Detailed Description
A this pointer adjustment.
Definition at line 91 of file Thunk.h.
Constructor & Destructor Documentation
ThisAdjustment()
clang::ThisAdjustment::ThisAdjustment () inline
Definition at line 134 of file Thunk.h.
Member Function Documentation
isEmpty()
bool clang::ThisAdjustment::isEmpty () const inline
Definition at line 136 of file Thunk.h.
References clang::ThisAdjustment::VirtualAdjustment::isEmpty(), NonVirtual, and Virtual.
Referenced by dumpMicrosoftThunkAdjustment(), and clang::ThunkInfo::isEmpty().
Friends And Related Function Documentation
operator!=
bool operator!= (const ThisAdjustment & LHS, const ThisAdjustment & RHS) friend
Definition at line 142 of file Thunk.h.
operator<
bool operator< (const ThisAdjustment & LHS, const ThisAdjustment & RHS) friend
Definition at line 146 of file Thunk.h.
operator==
bool operator== (const ThisAdjustment & LHS, const ThisAdjustment & RHS) friend
Definition at line 138 of file Thunk.h.
Member Data Documentation
NonVirtual
int64_t clang::ThisAdjustment::NonVirtual
The non-virtual adjustment from the derived object to its nearest virtual base.
Definition at line 94 of file Thunk.h.
Referenced by dumpMicrosoftThunkAdjustment(), isEmpty(), and mangleThunkThisAdjustment().
Virtual
union clang::ThisAdjustment::VirtualAdjustment clang::ThisAdjustment::Virtual
Referenced by dumpMicrosoftThunkAdjustment(), isEmpty(), and mangleThunkThisAdjustment().
The documentation for this struct was generated from the following file:
include/clang/Basic/Thunk.h