clang: clang::SanitizerSet Struct Reference
clang::SanitizerSet Struct Reference
#include "clang/Basic/Sanitizers.h"
Public Member Functions
bool has (SanitizerMask K) const
Check if a certain (single) sanitizer is enabled.
bool hasOneOf (SanitizerMask K) const
Check if one or more sanitizers are enabled.
void set (SanitizerMask K, bool Value)
Enable or disable a certain (single) sanitizer.
void set (SanitizerMask K)
void clear (SanitizerMask K=SanitizerKind::All)
Disable the sanitizers specified in K.
bool empty () const
Returns true if no sanitizers are enabled.
Public Attributes
SanitizerMask Mask
Bitmask of enabled sanitizers.
Detailed Description
Definition at line 157 of file Sanitizers.h.
Member Function Documentation
clear()
void clang::SanitizerSet::clear (SanitizerMask K = SanitizerKind::All) inline
Disable the sanitizers specified in K.
Definition at line 176 of file Sanitizers.h.
References Mask.
Referenced by clang::CompilerInvocation::getModuleHash().
empty()
bool clang::SanitizerSet::empty () const inline
Returns true if no sanitizers are enabled.
Definition at line 179 of file Sanitizers.h.
References Mask.
Referenced by clang::CompilerInvocation::getModuleHash(), and clang::driver::SanitizerArgs::hasAnySanitizer().
has()
bool clang::SanitizerSet::has (SanitizerMask K) const inline
Check if a certain (single) sanitizer is enabled.
Definition at line 159 of file Sanitizers.h.
References clang::SanitizerMask::isPowerOf2(), and Mask.
Referenced by clang::CodeGen::CodeGenModule::CreateFunctionTypeMetadataForIcall(), clang::CodeGen::CodeGenFunction::emitAlignmentAssumption(), clang::CodeGen::CodeGenFunction::emitAlignmentAssumptionCheck(), clang::CodeGen::CodeGenFunction::EmitArraySubscriptExpr(), clang::CodeGen::CodeGenFunction::EmitBinaryOperatorLValue(), clang::CodeGen::CodeGenFunction::EmitBitfieldConversionCheck(), clang::CodeGen::CodeGenFunction::EmitCall(), clang::CodeGen::CodeGenFunction::EmitCastLValue(), clang::CodeGen::CodeGenFunction::EmitCfiCheckFail(), clang::CodeGen::CodeGenFunction::EmitCfiSlowPathCheck(), clang::CodeGen::CodeGenFunction::EmitCheck(), clang::CodeGen::CodeGenFunction::EmitCheckedLValue(), clang::CodeGen::CodeGenFunction::EmitFunctionProlog(), clang::CodeGen::CodeGenFunction::EmitMaterializeTemporaryExpr(), clang::CodeGen::CodeGenFunction::EmitNullabilityCheck(), emitPointerArithmetic(), EmitPointerWithAlignment(), clang::CodeGen::CodeGenFunction::EmitReturnValueCheck(), clang::CodeGen::CodeGenFunction::EmitScalarRangeCheck(), clang::CodeGen::CodeGenFunction::EmitTypeCheck(), clang::CodeGen::CodeGenFunction::EmitTypeMetadataCodeForVCall(), clang::CodeGen::CodeGenFunction::EmitUnreachable(), clang::CodeGen::CodeGenFunction::EmitVariablyModifiedType(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheck(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheckForCall(), clang::CodeGen::CodeGenFunction::EmitVTablePtrCheckForCast(), clang::CodeGen::CodeGenFunction::EmitVTableTypeCheckedLoad(), clang::CodeGen::CodeGenFunction::EnterDtorCleanups(), clang::CodeGen::CodeGenFunction::GenerateCode(), clang::driver::SanitizerArgs::hasMemtagGlobals(), clang::driver::SanitizerArgs::hasMemtagHeap(), clang::driver::SanitizerArgs::hasMemtagStack(), clang::driver::SanitizerArgs::hasShadowCallStack(), clang::CodeGen::CodeGenFunction::markAsIgnoreThreadCheckingAtRuntime(), clang::driver::SanitizerArgs::needsAsanRt(), clang::driver::SanitizerArgs::needsDfsanRt(), clang::driver::SanitizerArgs::needsFuzzer(), clang::driver::SanitizerArgs::needsHwasanRt(), clang::driver::SanitizerArgs::needsLsanRt(), clang::driver::SanitizerArgs::needsMsanRt(), clang::driver::SanitizerArgs::needsScudoRt(), clang::driver::SanitizerArgs::needsTsanRt(), clang::CodeGen::CodeGenModule::Release(), clang::CodeGen::CodeGenVTables::RemoveHwasanMetadata(), clang::CodeGen::CodeGenFunction::sanitizePerformTypeCheck(), clang::CodeGen::CodeGenFunction::ShouldEmitVTableTypeCheckedLoad(), and clang::CodeGen::CodeGenFunction::StartFunction().
hasOneOf()
bool clang::SanitizerSet::hasOneOf (SanitizerMask K) const inline
Check if one or more sanitizers are enabled.
Definition at line 165 of file Sanitizers.h.
References Mask.
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), isAsanHwasanOrMemTag(), and clang::CodeGen::CodeGenFunction::StartFunction().
set() [1/2]
void clang::SanitizerSet::set (SanitizerMask K) inline
Definition at line 173 of file Sanitizers.h.
References Mask.
set() [2/2]
void clang::SanitizerSet::set (SanitizerMask K, bool Value) inline
Enable or disable a certain (single) sanitizer.
Definition at line 168 of file Sanitizers.h.
References clang::SanitizerMask::isPowerOf2(), and Mask.
Referenced by clang::CodeGen::CodeGenFunction::EmitCheckedLValue(), clang::CodeGen::CodeGenFunction::EmitCXXNewExpr(), clang::CodeGen::CodeGenFunction::EmitMemberExpr(), clang::CodeGen::CodeGenFunction::GetAddressOfBaseClass(), and clang::CodeGen::CodeGenFunction::StartFunction().
Member Data Documentation
Mask
SanitizerMask clang::SanitizerSet::Mask
Bitmask of enabled sanitizers.
Definition at line 182 of file Sanitizers.h.
Referenced by clear(), empty(), clang::CompilerInvocation::getModuleHash(), has(), hasOneOf(), set(), and clang::CodeGen::CodeGenFunction::StartFunction().
The documentation for this struct was generated from the following file:
include/clang/Basic/Sanitizers.h