clang: clang::tooling::dependencies::FullDependencies Struct Reference
clang::tooling::dependencies::FullDependencies Struct Reference
The full dependencies and module graph for a specific input.
#include "clang/Tooling/DependencyScanning/DependencyScanningTool.h"
Public Member Functions
std::vector< std::string > getCommandLine (std::function< StringRef(ModuleID)> LookupPCMPath) const
Get the full command line.
std::vector< std::string > getCommandLineWithoutModulePaths () const
Get the full command line, excluding -fmodule-file=" arguments.
std::vector< std::string > getAdditionalArgsWithoutModulePaths () const
Get additional arguments suitable for appending to the original Clang command line, excluding "-fmodule-file=" arguments.
Public Attributes
ModuleID ID
The identifier of the C++20 module this translation unit exports.
std::vector< std::string > FileDeps
A collection of absolute paths to files that this translation unit directly depends on, not including transitive dependencies.
std::vector< PrebuiltModuleDep > PrebuiltModuleDeps
A collection of prebuilt modules this translation unit directly depends on, not including transitive dependencies.
std::vector< ModuleID > ClangModuleDeps
A list of modules this translation unit directly depends on, not including transitive dependencies.
std::vector< std::string > OriginalCommandLine
The original command line of the TU (excluding the compiler executable).
Detailed Description
The full dependencies and module graph for a specific input.
Definition at line 24 of file DependencyScanningTool.h.
Member Function Documentation
getAdditionalArgsWithoutModulePaths()
std::vector< std::string > clang::tooling::dependencies::FullDependencies::getAdditionalArgsWithoutModulePaths () const
Get additional arguments suitable for appending to the original Clang command line, excluding "-fmodule-file=" arguments.
Definition at line 46 of file DependencyScanningTool.cpp.
References PrebuiltModuleDeps.
Referenced by getCommandLineWithoutModulePaths().
getCommandLine()
std::vector< std::string > clang::tooling::dependencies::FullDependencies::getCommandLine (std::function< StringRef(ModuleID)> LookupPCMPath) const
Get the full command line.
Parameters
LookupPCMPath This function is called to fill in "-fmodule-file=" arguments and the "-o" argument. It needs to return a path for where the PCM for the given module is to be located.
Definition at line 16 of file DependencyScanningTool.cpp.
References ClangModuleDeps, getCommandLineWithoutModulePaths(), and Ret().
getCommandLineWithoutModulePaths()
std::vector< std::string > clang::tooling::dependencies::FullDependencies::getCommandLineWithoutModulePaths () const
Get the full command line, excluding -fmodule-file=" arguments.
Definition at line 27 of file DependencyScanningTool.cpp.
References getAdditionalArgsWithoutModulePaths(), OriginalCommandLine, and string().
Referenced by getCommandLine().
Member Data Documentation
ClangModuleDeps
std::vector<ModuleID> clang::tooling::dependencies::FullDependencies::ClangModuleDeps
A list of modules this translation unit directly depends on, not including transitive dependencies.
This may include modules with a different context hash when it can be determined that the differences are benign for this compilation.
Definition at line 43 of file DependencyScanningTool.h.
Referenced by getCommandLine(), and clang::tooling::dependencies::DependencyScanningTool::getFullDependencies().
FileDeps
std::vector<std::string> clang::tooling::dependencies::FullDependencies::FileDeps
A collection of absolute paths to files that this translation unit directly depends on, not including transitive dependencies.
Definition at line 32 of file DependencyScanningTool.h.
Referenced by clang::tooling::dependencies::DependencyScanningTool::getFullDependencies().
ID
ModuleID clang::tooling::dependencies::FullDependencies::ID
The identifier of the C++20 module this translation unit exports.
If the translation unit is not a module then ID.ModuleName is empty.
Definition at line 28 of file DependencyScanningTool.h.
Referenced by clang::tooling::dependencies::DependencyScanningTool::getFullDependencies().
OriginalCommandLine
std::vector<std::string> clang::tooling::dependencies::FullDependencies::OriginalCommandLine
The original command line of the TU (excluding the compiler executable).
Definition at line 46 of file DependencyScanningTool.h.
Referenced by getCommandLineWithoutModulePaths(), and clang::tooling::dependencies::DependencyScanningTool::getFullDependencies().
PrebuiltModuleDeps
std::vector<PrebuiltModuleDep> clang::tooling::dependencies::FullDependencies::PrebuiltModuleDeps
A collection of prebuilt modules this translation unit directly depends on, not including transitive dependencies.
Definition at line 36 of file DependencyScanningTool.h.
Referenced by getAdditionalArgsWithoutModulePaths(), and clang::tooling::dependencies::DependencyScanningTool::getFullDependencies().
The documentation for this struct was generated from the following files:
include/clang/Tooling/DependencyScanning/DependencyScanningTool.h
lib/Tooling/DependencyScanning/DependencyScanningTool.cpp