clang: clang::interp::Descriptor Struct Reference
clang::interp::Descriptor Struct Reference final
Describes a memory block created by an allocation site.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Descriptor.h"
Classes
struct UnknownSize
Token to denote structures of unknown size.
Public Types
using MetadataSize = std::optional< unsigned >
Public Member Functions
Descriptor (const DeclTy &D, PrimType Type, MetadataSize MD, bool IsConst, bool IsTemporary, bool IsMutable)
Allocates a descriptor for a primitive.
Descriptor (const DeclTy &D, PrimType Type, MetadataSize MD, size_t NumElems, bool IsConst, bool IsTemporary, bool IsMutable)
Allocates a descriptor for an array of primitives.
Descriptor (const DeclTy &D, PrimType Type, MetadataSize MDSize, bool IsTemporary, UnknownSize)
Allocates a descriptor for an array of primitives of unknown size.
Descriptor (const DeclTy &D, const Descriptor *Elem, MetadataSize MD, unsigned NumElems, bool IsConst, bool IsTemporary, bool IsMutable)
Allocates a descriptor for an array of composites.
Descriptor (const DeclTy &D, const Descriptor *Elem, MetadataSize MD, bool IsTemporary, UnknownSize)
Allocates a descriptor for an array of composites of unknown size.
Descriptor (const DeclTy &D, const Record *R, MetadataSize MD, bool IsConst, bool IsTemporary, bool IsMutable)
Allocates a descriptor for a record.
Descriptor (const DeclTy &D)
Allocates a dummy descriptor.
void makeDummy ()
Make this descriptor a dummy descriptor.
QualType getType () const
QualType getElemQualType () const
SourceLocation getLocation () const
const Decl * asDecl () const
const Expr * asExpr () const
const DeclTy & getSource () const
const ValueDecl * asValueDecl () const
const VarDecl * asVarDecl () const
const FieldDecl * asFieldDecl () const
const RecordDecl * asRecordDecl () const
unsigned getSize () const
Returns the size of the object without metadata.
PrimType getPrimType () const
unsigned getAllocSize () const
Returns the allocated size, including metadata.
unsigned getElemSize () const
returns the size of an element when the structure is viewed as an array.
unsigned getMetadataSize () const
Returns the size of the metadata.
unsigned getNumElems () const
Returns the number of elements stored in the block.
bool isPrimitiveArray () const
Checks if the descriptor is of an array of primitives.
bool isCompositeArray () const
Checks if the descriptor is of an array of composites.
bool isZeroSizeArray () const
Checks if the descriptor is of an array of zero size.
bool isUnknownSizeArray () const
Checks if the descriptor is of an array of unknown size.
bool isPrimitive () const
Checks if the descriptor is of a primitive.
bool isArray () const
Checks if the descriptor is of an array.
bool isRecord () const
Checks if the descriptor is of a record.
bool isDummy () const
Checks if this is a dummy descriptor.
void dump () const
void dump (llvm::raw_ostream &OS) const
Public Attributes
const Record *const ElemRecord = nullptr
Pointer to the record, if block contains records.
const Descriptor *const ElemDesc = nullptr
Descriptor of the array element.
const std::optional< PrimType > PrimT = std::nullopt
The primitive type this descriptor was created for, or the primitive element type in case this is a primitive array.
const bool IsConst = false
Flag indicating if the block is mutable.
const bool IsMutable = false
Flag indicating if a field is mutable.
const bool IsTemporary = false
Flag indicating if the block is a temporary.
const bool IsArray = false
Flag indicating if the block is an array.
bool IsDummy = false
Flag indicating if this is a dummy descriptor.
const BlockCtorFn CtorFn = nullptr
Storage management methods.
const BlockDtorFn DtorFn = nullptr
const BlockMoveFn MoveFn = nullptr
Static Public Attributes
static constexpr MetadataSize InlineDescMD = sizeof(InlineDescriptor)
static constexpr MetadataSize GlobalMD = sizeof(GlobalInlineDescriptor)
static constexpr unsigned MaxArrayElemBytes
Maximum number of bytes to be used for array elements.
Detailed Description
Describes a memory block created by an allocation site.
Definition at line 105 of file Descriptor.h.
Member Typedef Documentation
MetadataSize
using clang::interp::Descriptor::MetadataSize = std::optional<unsigned>
Definition at line 125 of file Descriptor.h.
Constructor & Destructor Documentation
Descriptor() [1/7]
Descriptor::Descriptor (const DeclTy & D, PrimType Type, MetadataSize MD, bool IsConst, bool IsTemporary, bool IsMutable)
Allocates a descriptor for a primitive.
Primitives.
Definition at line 284 of file Descriptor.cpp.
Descriptor() [2/7]
Descriptor::Descriptor (const DeclTy & D, PrimType Type, MetadataSize MD, size_t NumElems, bool IsConst, bool IsTemporary, bool IsMutable)
Allocates a descriptor for an array of primitives.
Primitive arrays.
Definition at line 296 of file Descriptor.cpp.
References MaxArrayElemBytes.
Descriptor() [3/7]
Descriptor::Descriptor (const DeclTy & D, PrimType Type, MetadataSize MDSize, bool IsTemporary, UnknownSize)
Allocates a descriptor for an array of primitives of unknown size.
Primitive unknown-size arrays.
Definition at line 310 of file Descriptor.cpp.
Descriptor() [4/7]
Descriptor::Descriptor (const DeclTy & D, const Descriptor * Elem, MetadataSize MD, unsigned NumElems, bool IsConst, bool IsTemporary, bool IsMutable)
Allocates a descriptor for an array of composites.
Arrays of composite elements.
Definition at line 322 of file Descriptor.cpp.
Descriptor() [5/7]
Descriptor::Descriptor (const DeclTy & D, const Descriptor * Elem, MetadataSize MD, bool IsTemporary, UnknownSize)
Allocates a descriptor for an array of composites of unknown size.
Unknown-size arrays of composite elements.
Definition at line 335 of file Descriptor.cpp.
Descriptor() [6/7]
Descriptor::Descriptor (const DeclTy & D, const Record * R, MetadataSize MD, bool IsConst, bool IsTemporary, bool IsMutable)
Allocates a descriptor for a record.
Composite records.
Definition at line 346 of file Descriptor.cpp.
Descriptor() [7/7]
Descriptor::Descriptor (const DeclTy & D)
Allocates a dummy descriptor.
Dummy.
Definition at line 357 of file Descriptor.cpp.
Member Function Documentation
asDecl()
const Decl* clang::interp::Descriptor::asDecl () const inline
Definition at line 192 of file Descriptor.h.
Referenced by asFieldDecl(), asRecordDecl(), asValueDecl(), asVarDecl(), dump(), getType(), clang::interp::Pointer::isField(), and clang::interp::Pointer::toAPValue().
asExpr()
const Expr* clang::interp::Descriptor::asExpr () const inline
Definition at line 193 of file Descriptor.h.
Referenced by clang::interp::DynamicAllocator::allocate(), dump(), clang::interp::Program::dump(), getType(), and clang::interp::Pointer::toAPValue().
asFieldDecl()
const FieldDecl* clang::interp::Descriptor::asFieldDecl () const inline
Definition at line 204 of file Descriptor.h.
References asDecl().
Referenced by clang::interp::Pointer::getField(), and clang::interp::Pointer::toRValue().
asRecordDecl()
const RecordDecl* clang::interp::Descriptor::asRecordDecl () const inline
Definition at line 208 of file Descriptor.h.
References asDecl().
asValueDecl()
const ValueDecl* clang::interp::Descriptor::asValueDecl () const inline
Definition at line 196 of file Descriptor.h.
References asDecl().
Referenced by getType(), and clang::interp::Pointer::toAPValue().
asVarDecl()
const VarDecl* clang::interp::Descriptor::asVarDecl () const inline
Definition at line 200 of file Descriptor.h.
References asDecl().
dump() [1/2]
LLVM_DUMP_METHOD void Descriptor::dump () const
Definition at line 209 of file Disasm.cpp.
Referenced by clang::interp::InlineDescriptor::dump(), clang::interp::Block::dump(), and clang::interp::Program::dump().
dump() [2/2]
LLVM_DUMP_METHOD void Descriptor::dump (llvm::raw_ostream & OS) const
Definition at line 214 of file Disasm.cpp.
References asDecl(), asExpr(), isCompositeArray(), isDummy(), isPrimitive(), isPrimitiveArray(), isRecord(), isUnknownSizeArray(), and isZeroSizeArray().
getAllocSize()
unsigned clang::interp::Descriptor::getAllocSize () const inline
Returns the allocated size, including metadata.
Definition at line 224 of file Descriptor.h.
Referenced by clang::interp::Program::createDescriptor(), clang::interp::Program::getOrCreateDummy(), clang::interp::Program::getOrCreateRecord(), clang::interp::Block::getSize(), and clang::interp::Block::invokeCtor().
getElemQualType()
QualType Descriptor::getElemQualType () const
Definition at line 374 of file Descriptor.cpp.
References clang::Type::getAs(), clang::Type::getAsArrayTypeUnsafe(), getType(), isArray(), and clang::T.
getElemSize()
unsigned clang::interp::Descriptor::getElemSize () const inline
returns the size of an element when the structure is viewed as an array.
Definition at line 226 of file Descriptor.h.
Referenced by clang::interp::Pointer::elemSize(), and getNumElems().
getLocation()
SourceLocation Descriptor::getLocation () const
Definition at line 386 of file Descriptor.cpp.
References D, E, clang::Expr::getExprLoc(), and clang::Decl::getLocation().
Referenced by clang::interp::Pointer::getDeclLoc().
getMetadataSize()
unsigned clang::interp::Descriptor::getMetadataSize () const inline
Returns the size of the metadata.
Definition at line 228 of file Descriptor.h.
Referenced by clang::interp::Block::data(), clang::interp::InterpState::deallocate(), clang::interp::Pointer::expand(), and clang::interp::MemberPointer::toPointer().
getNumElems()
unsigned clang::interp::Descriptor::getNumElems () const inline
Returns the number of elements stored in the block.
Definition at line 231 of file Descriptor.h.
References getElemSize(), and getSize().
Referenced by clang::interp::collectBlocks(), and clang::interp::Pointer::initialize().
getPrimType()
PrimType clang::interp::Descriptor::getPrimType () const inline
Definition at line 218 of file Descriptor.h.
References isPrimitive(), isPrimitiveArray(), and PrimT.
Referenced by clang::interp::collectBlocks(), and clang::interp::Program::dump().
getSize()
unsigned clang::interp::Descriptor::getSize () const inline
Returns the size of the object without metadata.
Definition at line 213 of file Descriptor.h.
References isUnknownSizeArray().
Referenced by clang::interp::Pointer::elemSize(), getNumElems(), and clang::interp::Pointer::getSize().
getSource()
const DeclTy& clang::interp::Descriptor::getSource () const inline
Definition at line 194 of file Descriptor.h.
Referenced by clang::interp::Pointer::getSource().
getType()
QualType Descriptor::getType () const
Definition at line 364 of file Descriptor.cpp.
References asDecl(), asExpr(), asValueDecl(), D, E, clang::Expr::getType(), and clang::T.
Referenced by getElemQualType(), and clang::interp::Pointer::getType().
isArray()
bool clang::interp::Descriptor::isArray () const inline
Checks if the descriptor is of an array.
Definition at line 248 of file Descriptor.h.
References IsArray.
Referenced by getElemQualType().
isCompositeArray()
bool clang::interp::Descriptor::isCompositeArray () const inline
Checks if the descriptor is of an array of composites.
Definition at line 238 of file Descriptor.h.
References ElemDesc, and IsArray.
Referenced by clang::interp::collectBlocks(), and dump().
isDummy()
bool clang::interp::Descriptor::isDummy () const inline
Checks if this is a dummy descriptor.
Definition at line 252 of file Descriptor.h.
References IsDummy.
Referenced by dump(), clang::interp::Program::dump(), clang::interp::Program::getOrCreateDummy(), and clang::interp::Pointer::isDummy().
isPrimitive()
bool clang::interp::Descriptor::isPrimitive () const inline
Checks if the descriptor is of a primitive.
Definition at line 245 of file Descriptor.h.
References ElemRecord, and IsArray.
Referenced by clang::interp::collectBlocks(), dump(), clang::interp::Program::dump(), and getPrimType().
isPrimitiveArray()
bool clang::interp::Descriptor::isPrimitiveArray () const inline
Checks if the descriptor is of an array of primitives.
Definition at line 236 of file Descriptor.h.
References ElemDesc, and IsArray.
Referenced by clang::interp::collectBlocks(), dump(), getPrimType(), clang::interp::Pointer::initialize(), clang::interp::Pointer::inPrimitiveArray(), and clang::interp::Pointer::isInitialized().
isRecord()
bool clang::interp::Descriptor::isRecord () const inline
Checks if the descriptor is of a record.
Definition at line 250 of file Descriptor.h.
References ElemRecord, and IsArray.
Referenced by dump().
isUnknownSizeArray()
bool clang::interp::Descriptor::isUnknownSizeArray () const inline
Checks if the descriptor is of an array of unknown size.
Definition at line 242 of file Descriptor.h.
Referenced by dump(), getSize(), and clang::interp::Pointer::isUnknownSizeArray().
isZeroSizeArray()
bool clang::interp::Descriptor::isZeroSizeArray () const inline
Checks if the descriptor is of an array of zero size.
Definition at line 240 of file Descriptor.h.
Referenced by dump(), and clang::interp::Pointer::isZeroSizeArray().
makeDummy()
void clang::interp::Descriptor::makeDummy () inline
Make this descriptor a dummy descriptor.
Definition at line 186 of file Descriptor.h.
References IsDummy.
Referenced by clang::interp::Program::getOrCreateDummy().
Member Data Documentation
CtorFn
const BlockCtorFn clang::interp::Descriptor::CtorFn = nullptr
Storage management methods.
Definition at line 154 of file Descriptor.h.
Referenced by clang::interp::Block::invokeCtor().
DtorFn
const BlockDtorFn clang::interp::Descriptor::DtorFn = nullptr
Definition at line 155 of file Descriptor.h.
Referenced by clang::interp::Block::invokeDtor().
ElemDesc
const Descriptor* const clang::interp::Descriptor::ElemDesc = nullptr
Descriptor of the array element.
Definition at line 137 of file Descriptor.h.
Referenced by clang::interp::Pointer::getElemRecord(), isCompositeArray(), and isPrimitiveArray().
ElemRecord
const Record* const clang::interp::Descriptor::ElemRecord = nullptr
Pointer to the record, if block contains records.
Definition at line 135 of file Descriptor.h.
Referenced by clang::interp::collectBlocks(), clang::interp::Pointer::getElemRecord(), clang::interp::Pointer::getRecord(), isPrimitive(), and isRecord().
GlobalMD
constexpr MetadataSize clang::interp::Descriptor::GlobalMD = sizeof(GlobalInlineDescriptor) static constexpr
Definition at line 127 of file Descriptor.h.
InlineDescMD
constexpr MetadataSize clang::interp::Descriptor::InlineDescMD = sizeof(InlineDescriptor) static constexpr
Definition at line 126 of file Descriptor.h.
Referenced by clang::interp::DynamicAllocator::allocate(), clang::interp::Compiler< Emitter >::allocateLocal(), clang::interp::Compiler< Emitter >::allocateLocalPrimitive(), clang::interp::Compiler< Emitter >::VisitCastExpr(), and clang::interp::Compiler< Emitter >::VisitCXXNewExpr().
IsArray
const bool clang::interp::Descriptor::IsArray = false
Flag indicating if the block is an array.
Definition at line 149 of file Descriptor.h.
Referenced by clang::interp::Pointer::expand(), clang::interp::Pointer::hasSameArray(), clang::interp::Pointer::inArray(), isArray(), isCompositeArray(), isPrimitive(), isPrimitiveArray(), and isRecord().
IsConst
const bool clang::interp::Descriptor::IsConst = false
Flag indicating if the block is mutable.
Definition at line 143 of file Descriptor.h.
Referenced by clang::interp::Block::invokeCtor(), and clang::interp::Pointer::isConst().
IsDummy
bool clang::interp::Descriptor::IsDummy = false
Flag indicating if this is a dummy descriptor.
Definition at line 151 of file Descriptor.h.
Referenced by isDummy(), and makeDummy().
IsMutable
const bool clang::interp::Descriptor::IsMutable = false
Flag indicating if a field is mutable.
Definition at line 145 of file Descriptor.h.
Referenced by clang::interp::Block::invokeCtor().
IsTemporary
const bool clang::interp::Descriptor::IsTemporary = false
Flag indicating if the block is a temporary.
Definition at line 147 of file Descriptor.h.
Referenced by clang::interp::Program::dump(), and clang::interp::Block::isTemporary().
MaxArrayElemBytes
constexpr unsigned clang::interp::Descriptor::MaxArrayElemBytes static constexpr
Initial value:
=
      std::numeric_limits<decltype(AllocSize)>::max() - sizeof(InitMapPtr) -
      align(std::max(*InlineDescMD, *GlobalMD))
Maximum number of bytes to be used for array elements.
Definition at line 130 of file Descriptor.h.
Referenced by Descriptor().
MoveFn
const BlockMoveFn clang::interp::Descriptor::MoveFn = nullptr
Definition at line 156 of file Descriptor.h.
Referenced by clang::interp::InterpState::deallocate().
PrimT
const std::optional<PrimType> clang::interp::Descriptor::PrimT = std::nullopt
The primitive type this descriptor was created for, or the primitive element type in case this is a primitive array.
Definition at line 141 of file Descriptor.h.
Referenced by getPrimType().
The documentation for this struct was generated from the following files:
lib/AST/Interp/Descriptor.h
lib/AST/Interp/Descriptor.cpp
lib/AST/Interp/Disasm.cpp