clang: clang::driver::DeviceLibABIVersion Struct Reference
clang::driver::DeviceLibABIVersion Struct Reference
ABI version of device library.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Driver/ToolChains/ROCm.h"
Public Member Functions
DeviceLibABIVersion (unsigned V)
bool requiresLibrary ()
Whether ABI version bc file is requested.
std::string toString ()
Static Public Member Functions
static DeviceLibABIVersion fromCodeObjectVersion (unsigned CodeObjectVersion)
Public Attributes
unsigned ABIVersion = 0
Detailed Description
ABI version of device library.
Definition at line 26 of file ROCm.h.
Constructor & Destructor Documentation
DeviceLibABIVersion()
clang::driver::DeviceLibABIVersion::DeviceLibABIVersion (unsigned V) inline
Definition at line 28 of file ROCm.h.
Referenced by fromCodeObjectVersion().
Member Function Documentation
fromCodeObjectVersion()
static DeviceLibABIVersion clang::driver::DeviceLibABIVersion::fromCodeObjectVersion (unsigned CodeObjectVersion) inline static
Definition at line 29 of file ROCm.h.
References DeviceLibABIVersion().
Referenced by clang::driver::toolchains::ROCMToolChain::addClangTargetOptions(), and clang::driver::toolchains::ROCMToolChain::getCommonDeviceLibNames().
requiresLibrary()
bool clang::driver::DeviceLibABIVersion::requiresLibrary () inline
Whether ABI version bc file is requested.
ABIVersion is code object version multiplied by 100. Code object v4 and below works with ROCm 5.0 and below which does not have abi_version_*.bc. Code object v5 requires abi_version_500.bc.
Definition at line 38 of file ROCm.h.
References ABIVersion.
Referenced by clang::driver::RocmInstallationDetector::checkCommonBitcodeLibs().
toString()
std::string clang::driver::DeviceLibABIVersion::toString () inline
Definition at line 39 of file ROCm.h.
References ABIVersion.
Referenced by clang::driver::RocmInstallationDetector::checkCommonBitcodeLibs().
Member Data Documentation
ABIVersion
unsigned clang::driver::DeviceLibABIVersion::ABIVersion = 0
Definition at line 27 of file ROCm.h.
Referenced by clang::driver::RocmInstallationDetector::getABIVersionPath(), requiresLibrary(), and toString().
The documentation for this struct was generated from the following file:
lib/Driver/ToolChains/ROCm.h