clang: clang::ASTFileSignature Struct Reference
clang::ASTFileSignature Struct Reference
The signature of a module, which is a hash of the AST content.
#include "clang/Basic/Module.h"
Public Types
using BaseT = std::array< uint8_t, 20 >
Public Member Functions
ASTFileSignature (BaseT S={{0}})
operator bool () const
uint64_t truncatedValue () const
Returns the value truncated to the size of an uint64_t.
Static Public Member Functions
static ASTFileSignature create (std::array< uint8_t, 20 > Bytes)
static ASTFileSignature createDISentinel ()
static ASTFileSignature createDummy ()
template<typename InputIt >
static ASTFileSignature create (InputIt First, InputIt Last)
Static Public Attributes
static constexpr size_t size = std::tuple_size<BaseT>::value
Detailed Description
The signature of a module, which is a hash of the AST content.
Definition at line 57 of file Module.h.
Member Typedef Documentation
BaseT
using clang::ASTFileSignature::BaseT = std::array<uint8_t, 20>
Definition at line 58 of file Module.h.
Constructor & Destructor Documentation
ASTFileSignature()
clang::ASTFileSignature::ASTFileSignature (BaseT S = {{0}}) inline
Definition at line 62 of file Module.h.
Referenced by create().
Member Function Documentation
create() [1/2]
template<typename InputIt > static ASTFileSignature clang::ASTFileSignature::create (InputIt First, InputIt Last) inline static
Definition at line 92 of file Module.h.
References distance(), clang::First, clang::Last, and size.
create() [2/2]
static ASTFileSignature clang::ASTFileSignature::create (std::array< uint8_t, 20 > Bytes) inline static
Definition at line 75 of file Module.h.
References ASTFileSignature().
Referenced by readASTFileSignature().
createDISentinel()
static ASTFileSignature clang::ASTFileSignature::createDISentinel () inline static
Definition at line 79 of file Module.h.
createDummy()
static ASTFileSignature clang::ASTFileSignature::createDummy () inline static
Definition at line 85 of file Module.h.
Referenced by readASTFileSignature().
operator bool()
clang::ASTFileSignature::operator bool () const inline explicit
Definition at line 64 of file Module.h.
truncatedValue()
uint64_t clang::ASTFileSignature::truncatedValue () const inline
Returns the value truncated to the size of an uint64_t.
Definition at line 67 of file Module.h.
Member Data Documentation
size
constexpr size_t clang::ASTFileSignature::size = std::tuple_size<BaseT>::value static constexpr
Definition at line 60 of file Module.h.
Referenced by create(), and clang::ASTReader::readASTFileControlBlock().
The documentation for this struct was generated from the following file:
include/clang/Basic/Module.h