clang: clang::ASTNodeKind::DenseMapInfo Struct Reference
clang::ASTNodeKind::DenseMapInfo Struct Reference
Hooks for using ASTNodeKind as a key in a DenseMap.
#include "clang/AST/ASTTypeTraits.h"
Static Public Member Functions
static ASTNodeKind getEmptyKey ()
static ASTNodeKind getTombstoneKey ()
static unsigned getHashValue (const ASTNodeKind &Val)
static bool isEqual (const ASTNodeKind &LHS, const ASTNodeKind &RHS)
Detailed Description
Hooks for using ASTNodeKind as a key in a DenseMap.
Definition at line 110 of file ASTTypeTraits.h.
Member Function Documentation
getEmptyKey()
static ASTNodeKind clang::ASTNodeKind::DenseMapInfo::getEmptyKey () inline static
Definition at line 112 of file ASTTypeTraits.h.
References clang::ASTNodeKind::ASTNodeKind().
Referenced by clang::DynTypedNode::DenseMapInfo::getEmptyKey(), and clang::DynTypedNode::DenseMapInfo::isEqual().
getHashValue()
static unsigned clang::ASTNodeKind::DenseMapInfo::getHashValue (const ASTNodeKind & Val) inline static
Definition at line 118 of file ASTTypeTraits.h.
getTombstoneKey()
static ASTNodeKind clang::ASTNodeKind::DenseMapInfo::getTombstoneKey () inline static
Definition at line 115 of file ASTTypeTraits.h.
References clang::ASTNodeKind::ASTNodeKind().
Referenced by clang::DynTypedNode::DenseMapInfo::getTombstoneKey(), and clang::DynTypedNode::DenseMapInfo::isEqual().
isEqual()
static bool clang::ASTNodeKind::DenseMapInfo::isEqual (const ASTNodeKind & LHS, const ASTNodeKind & RHS) inline static
Definition at line 119 of file ASTTypeTraits.h.
Referenced by clang::DynTypedNode::DenseMapInfo::isEqual().
The documentation for this struct was generated from the following file:
include/clang/AST/ASTTypeTraits.h