clang: clang::AvailabilityInfo Struct Reference
clang::AvailabilityInfo Struct Reference
Storage of availability attributes for a declaration.
#include "clang/AST/Availability.h"
Public Member Functions
AvailabilityInfo ()=default
bool isDefault () const
Determine if this AvailabilityInfo represents the default availability.
bool isObsoleted () const
Check if the symbol has been obsoleted.
bool isUnavailable () const
Check if the symbol is unavailable unconditionally or on the active platform and os version.
bool isUnconditionallyDeprecated () const
Check if the symbol is unconditionally deprecated.
bool isUnconditionallyUnavailable () const
Check if the symbol is unconditionally unavailable.
AvailabilityInfo (StringRef Domain, VersionTuple I, VersionTuple D, VersionTuple O, bool U, bool UD, bool UU)
Static Public Member Functions
static AvailabilityInfo createFromDecl (const Decl *Decl)
Public Attributes
llvm::SmallString< 32 > Domain
The domain is the platform for which this availability info applies to.
VersionTuple Introduced
VersionTuple Deprecated
VersionTuple Obsoleted
bool Unavailable = false
bool UnconditionallyDeprecated = false
bool UnconditionallyUnavailable = false
Friends
bool operator== (const AvailabilityInfo &Lhs, const AvailabilityInfo &Rhs)
Detailed Description
Storage of availability attributes for a declaration.
Definition at line 64 of file Availability.h.
Constructor & Destructor Documentation
AvailabilityInfo() [1/2]
clang::AvailabilityInfo::AvailabilityInfo () default
Referenced by isDefault().
AvailabilityInfo() [2/2]
clang::AvailabilityInfo::AvailabilityInfo (StringRef Domain, VersionTuple I, VersionTuple D, VersionTuple O, bool U, bool UD, bool UU) inline
Definition at line 100 of file Availability.h.
Member Function Documentation
createFromDecl()
AvailabilityInfo clang::AvailabilityInfo::createFromDecl (const Decl * Decl) static
Definition at line 21 of file Availability.cpp.
isDefault()
bool clang::AvailabilityInfo::isDefault () const inline
Determine if this AvailabilityInfo represents the default availability.
Definition at line 77 of file Availability.h.
References AvailabilityInfo().
isObsoleted()
bool clang::AvailabilityInfo::isObsoleted () const inline
Check if the symbol has been obsoleted.
Definition at line 80 of file Availability.h.
References Obsoleted.
isUnavailable()
bool clang::AvailabilityInfo::isUnavailable () const inline
Check if the symbol is unavailable unconditionally or on the active platform and os version.
Definition at line 84 of file Availability.h.
References isUnconditionallyUnavailable(), and Unavailable.
isUnconditionallyDeprecated()
bool clang::AvailabilityInfo::isUnconditionallyDeprecated () const inline
Check if the symbol is unconditionally deprecated.
i.e.
__attribute__((deprecated))
Definition at line 91 of file Availability.h.
References UnconditionallyDeprecated.
isUnconditionallyUnavailable()
bool clang::AvailabilityInfo::isUnconditionallyUnavailable () const inline
Check if the symbol is unconditionally unavailable.
i.e.
__attribute__((unavailable))
Definition at line 96 of file Availability.h.
References UnconditionallyUnavailable.
Referenced by isUnavailable().
Friends And Related Function Documentation
operator==
bool operator== (const AvailabilityInfo & Lhs, const AvailabilityInfo & Rhs) friend
Definition at line 113 of file Availability.h.
Member Data Documentation
Deprecated
VersionTuple clang::AvailabilityInfo::Deprecated
Definition at line 68 of file Availability.h.
Domain
llvm::SmallString<32> clang::AvailabilityInfo::Domain
The domain is the platform for which this availability info applies to.
Definition at line 66 of file Availability.h.
Introduced
VersionTuple clang::AvailabilityInfo::Introduced
Definition at line 67 of file Availability.h.
Obsoleted
VersionTuple clang::AvailabilityInfo::Obsoleted
Definition at line 69 of file Availability.h.
Referenced by isObsoleted().
Unavailable
bool clang::AvailabilityInfo::Unavailable = false
Definition at line 70 of file Availability.h.
Referenced by isUnavailable().
UnconditionallyDeprecated
bool clang::AvailabilityInfo::UnconditionallyDeprecated = false
Definition at line 71 of file Availability.h.
Referenced by isUnconditionallyDeprecated().
UnconditionallyUnavailable
bool clang::AvailabilityInfo::UnconditionallyUnavailable = false
Definition at line 72 of file Availability.h.
Referenced by isUnconditionallyUnavailable().
The documentation for this struct was generated from the following files:
include/clang/AST/Availability.h
lib/AST/Availability.cpp