clang: clang::CodeGen::EHPersonality Struct Reference
clang::CodeGen::EHPersonality Struct Reference
The exceptions personality for a function.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CGCleanup.h"
Public Member Functions
bool usesFuncletPads () const
Does this personality use landingpads or the family of pad instructions designed to form funclets?
bool isMSVCPersonality () const
bool isWasmPersonality () const
bool isMSVCXXPersonality () const
Static Public Member Functions
static const EHPersonality & get (CodeGenModule &CGM, const FunctionDecl *FD)
static const EHPersonality & get (CodeGenFunction &CGF)
Public Attributes
const char * PersonalityFn
const char * CatchallRethrowFn
Static Public Attributes
static const EHPersonality GNU_C = { "__gcc_personality_v0", nullptr }
static const EHPersonality GNU_C_SJLJ = { "__gcc_personality_sj0", nullptr }
static const EHPersonality GNU_C_SEH = { "__gcc_personality_seh0", nullptr }
static const EHPersonality GNU_ObjC = {"__gnu_objc_personality_v0", "objc_exception_throw"}
static const EHPersonality GNU_ObjC_SJLJ = {"__gnu_objc_personality_sj0", "objc_exception_throw"}
static const EHPersonality GNU_ObjC_SEH = {"__gnu_objc_personality_seh0", "objc_exception_throw"}
static const EHPersonality GNUstep_ObjC = { "__gnustep_objc_personality_v0", nullptr }
static const EHPersonality GNU_ObjCXX = { "__gnustep_objcxx_personality_v0", nullptr }
static const EHPersonality NeXT_ObjC = { "__objc_personality_v0", nullptr }
static const EHPersonality GNU_CPlusPlus = { "__gxx_personality_v0", nullptr }
static const EHPersonality GNU_CPlusPlus_SJLJ = { "__gxx_personality_sj0", nullptr }
static const EHPersonality GNU_CPlusPlus_SEH = { "__gxx_personality_seh0", nullptr }
static const EHPersonality MSVC_except_handler = { "_except_handler3", nullptr }
static const EHPersonality MSVC_C_specific_handler = { "__C_specific_handler", nullptr }
static const EHPersonality MSVC_CxxFrameHandler3 = { "__CxxFrameHandler3", nullptr }
static const EHPersonality GNU_Wasm_CPlusPlus = { "__gxx_wasm_personality_v0", nullptr }
static const EHPersonality XL_CPlusPlus
Detailed Description
The exceptions personality for a function.
Definition at line 588 of file CGCleanup.h.
Member Function Documentation
get() [1/2]
const EHPersonality & EHPersonality::get (CodeGenFunction & CGF) static
Definition at line 247 of file CGException.cpp.
References clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::CurCodeDecl, clang::CodeGen::CodeGenFunction::CurSEHParent, and get().
get() [2/2]
const EHPersonality & EHPersonality::get (CodeGenModule & CGM, const FunctionDecl * FD) static
Definition at line 230 of file CGException.cpp.
References getCPersonality(), getCXXPersonality(), clang::CodeGen::CodeGenModule::getLangOpts(), getObjCPersonality(), getObjCXXPersonality(), getSEHPersonalityMSVC(), clang::CodeGen::CodeGenModule::getTarget(), clang::TargetInfo::getTriple(), clang::Target, and clang::FunctionDecl::usesSEHTry().
Referenced by clang::CodeGen::CodeGenFunction::EmitCall(), emitCatchDispatchBlock(), emitCatchPadBlock(), get(), clang::CodeGen::CodeGenFunction::getEHDispatchBlock(), clang::CodeGen::CodeGenFunction::getEHResumeBlock(), clang::CodeGen::CodeGenFunction::getInvokeDestImpl(), clang::CodeGen::CodeGenFunction::getTerminateFunclet(), and clang::CodeGen::CodeGenFunction::getTerminateLandingPad().
isMSVCPersonality()
bool clang::CodeGen::EHPersonality::isMSVCPersonality () const inline
Definition at line 623 of file CGCleanup.h.
References MSVC_C_specific_handler, MSVC_CxxFrameHandler3, and MSVC_except_handler.
Referenced by usesFuncletPads().
isMSVCXXPersonality()
bool clang::CodeGen::EHPersonality::isMSVCXXPersonality () const inline
Definition at line 630 of file CGCleanup.h.
References MSVC_CxxFrameHandler3.
Referenced by clang::CodeGen::CodeGenFunction::EmitCall().
isWasmPersonality()
bool clang::CodeGen::EHPersonality::isWasmPersonality () const inline
Definition at line 628 of file CGCleanup.h.
References GNU_Wasm_CPlusPlus.
Referenced by usesFuncletPads().
usesFuncletPads()
bool clang::CodeGen::EHPersonality::usesFuncletPads () const inline
Does this personality use landingpads or the family of pad instructions designed to form funclets?
Definition at line 619 of file CGCleanup.h.
References isMSVCPersonality(), and isWasmPersonality().
Referenced by clang::CodeGen::CodeGenFunction::getEHDispatchBlock(), clang::CodeGen::CodeGenFunction::getInvokeDestImpl(), and clang::CodeGen::CodeGenFunction::getTerminateFunclet().
Member Data Documentation
CatchallRethrowFn
const char* clang::CodeGen::EHPersonality::CatchallRethrowFn
Definition at line 594 of file CGCleanup.h.
Referenced by clang::CodeGen::CodeGenFunction::getEHResumeBlock().
GNU_C
const EHPersonality EHPersonality::GNU_C = { "__gcc_personality_v0", nullptr } static
Definition at line 599 of file CGCleanup.h.
Referenced by getCPersonality().
GNU_C_SEH
const EHPersonality EHPersonality::GNU_C_SEH = { "__gcc_personality_seh0", nullptr } static
Definition at line 601 of file CGCleanup.h.
Referenced by getCPersonality().
GNU_C_SJLJ
const EHPersonality EHPersonality::GNU_C_SJLJ = { "__gcc_personality_sj0", nullptr } static
Definition at line 600 of file CGCleanup.h.
Referenced by getCPersonality().
GNU_CPlusPlus
const EHPersonality EHPersonality::GNU_CPlusPlus = { "__gxx_personality_v0", nullptr } static
Definition at line 608 of file CGCleanup.h.
Referenced by getCXXPersonality().
GNU_CPlusPlus_SEH
const EHPersonality EHPersonality::GNU_CPlusPlus_SEH = { "__gxx_personality_seh0", nullptr } static
Definition at line 610 of file CGCleanup.h.
Referenced by getCXXPersonality().
GNU_CPlusPlus_SJLJ
const EHPersonality EHPersonality::GNU_CPlusPlus_SJLJ = { "__gxx_personality_sj0", nullptr } static
Definition at line 609 of file CGCleanup.h.
Referenced by getCXXPersonality().
GNU_ObjC
const EHPersonality EHPersonality::GNU_ObjC = {"__gnu_objc_personality_v0", "objc_exception_throw"} static
Definition at line 602 of file CGCleanup.h.
Referenced by getObjCPersonality().
GNU_ObjC_SEH
const EHPersonality EHPersonality::GNU_ObjC_SEH = {"__gnu_objc_personality_seh0", "objc_exception_throw"} static
Definition at line 604 of file CGCleanup.h.
Referenced by getObjCPersonality().
GNU_ObjC_SJLJ
const EHPersonality EHPersonality::GNU_ObjC_SJLJ = {"__gnu_objc_personality_sj0", "objc_exception_throw"} static
Definition at line 603 of file CGCleanup.h.
Referenced by getObjCPersonality().
GNU_ObjCXX
const EHPersonality EHPersonality::GNU_ObjCXX = { "__gnustep_objcxx_personality_v0", nullptr } static
Definition at line 606 of file CGCleanup.h.
Referenced by getObjCXXPersonality().
GNU_Wasm_CPlusPlus
const EHPersonality EHPersonality::GNU_Wasm_CPlusPlus = { "__gxx_wasm_personality_v0", nullptr } static
Definition at line 614 of file CGCleanup.h.
Referenced by getCXXPersonality(), and isWasmPersonality().
GNUstep_ObjC
const EHPersonality EHPersonality::GNUstep_ObjC = { "__gnustep_objc_personality_v0", nullptr } static
Definition at line 605 of file CGCleanup.h.
Referenced by getObjCPersonality().
MSVC_C_specific_handler
const EHPersonality EHPersonality::MSVC_C_specific_handler = { "__C_specific_handler", nullptr } static
Definition at line 612 of file CGCleanup.h.
Referenced by getSEHPersonalityMSVC(), and isMSVCPersonality().
MSVC_CxxFrameHandler3
const EHPersonality EHPersonality::MSVC_CxxFrameHandler3 = { "__CxxFrameHandler3", nullptr } static
Definition at line 613 of file CGCleanup.h.
Referenced by getCPersonality(), getCXXPersonality(), getObjCPersonality(), getObjCXXPersonality(), isMSVCPersonality(), and isMSVCXXPersonality().
MSVC_except_handler
const EHPersonality EHPersonality::MSVC_except_handler = { "_except_handler3", nullptr } static
Definition at line 611 of file CGCleanup.h.
Referenced by getSEHPersonalityMSVC(), and isMSVCPersonality().
NeXT_ObjC
const EHPersonality EHPersonality::NeXT_ObjC = { "__objc_personality_v0", nullptr } static
Definition at line 607 of file CGCleanup.h.
Referenced by getObjCPersonality().
PersonalityFn
const char* clang::CodeGen::EHPersonality::PersonalityFn
Definition at line 589 of file CGCleanup.h.
Referenced by getPersonalityFn().
XL_CPlusPlus
const EHPersonality EHPersonality::XL_CPlusPlus static
Initial value:
= {"__xlcxx_personality_v1",
                                                   nullptr}
Definition at line 615 of file CGCleanup.h.
Referenced by getCXXPersonality().
The documentation for this struct was generated from the following files:
lib/CodeGen/CGCleanup.h
lib/CodeGen/CGException.cpp