clang: clang::format::RawStringFormatStyleManager Struct Reference
clang::format::RawStringFormatStyleManager Struct Reference
#include "/home/runner/work/llvm/llvm/repo/clang/lib/Format/ContinuationIndenter.h"
Public Member Functions
RawStringFormatStyleManager (const FormatStyle &CodeStyle)
llvm::Optional< FormatStyle > getDelimiterStyle (StringRef Delimiter) const
llvm::Optional< FormatStyle > getEnclosingFunctionStyle (StringRef EnclosingFunction) const
Public Attributes
llvm::StringMap< FormatStyle > DelimiterStyle
llvm::StringMap< FormatStyle > EnclosingFunctionStyle
Detailed Description
Definition at line 38 of file ContinuationIndenter.h.
Constructor & Destructor Documentation
RawStringFormatStyleManager()
clang::format::RawStringFormatStyleManager::RawStringFormatStyleManager (const FormatStyle & CodeStyle)
Definition at line 184 of file ContinuationIndenter.cpp.
References clang::format::FormatStyle::ColumnLimit, DelimiterStyle, EnclosingFunctionStyle, clang::format::FormatStyle::GetLanguageStyle(), clang::format::getLLVMStyle(), clang::format::getPredefinedStyle(), clang::format::FormatStyle::Language, and clang::format::FormatStyle::RawStringFormats.
Member Function Documentation
getDelimiterStyle()
llvm::Optional< FormatStyle > clang::format::RawStringFormatStyleManager::getDelimiterStyle (StringRef Delimiter) const
Definition at line 207 of file ContinuationIndenter.cpp.
References DelimiterStyle.
getEnclosingFunctionStyle()
llvm::Optional< FormatStyle > clang::format::RawStringFormatStyleManager::getEnclosingFunctionStyle (StringRef EnclosingFunction) const
Definition at line 215 of file ContinuationIndenter.cpp.
References EnclosingFunctionStyle.
Member Data Documentation
DelimiterStyle
llvm::StringMap<FormatStyle> clang::format::RawStringFormatStyleManager::DelimiterStyle
Definition at line 39 of file ContinuationIndenter.h.
Referenced by getDelimiterStyle(), and RawStringFormatStyleManager().
EnclosingFunctionStyle
llvm::StringMap<FormatStyle> clang::format::RawStringFormatStyleManager::EnclosingFunctionStyle
Definition at line 40 of file ContinuationIndenter.h.
Referenced by getEnclosingFunctionStyle(), and RawStringFormatStyleManager().
The documentation for this struct was generated from the following files:
lib/Format/ContinuationIndenter.h
lib/Format/ContinuationIndenter.cpp