clang: clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader Struct Reference
clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader Struct Reference
Header for data within LifetimeExtendedCleanupStack.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
size_t getSize () const
CleanupKind getKind () const
bool isConditional () const
Public Attributes
unsigned Size
The size of the following cleanup object.
unsigned Kind: 31
The kind of cleanup to push.
unsigned IsConditional: 1
Whether this is a conditional cleanup.
Detailed Description
Header for data within LifetimeExtendedCleanupStack.
Definition at line 693 of file CodeGenFunction.h.
Member Function Documentation
getKind()
CleanupKind clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::getKind () const inline
Definition at line 704 of file CodeGenFunction.h.
References Kind.
Referenced by clang::CodeGen::CodeGenFunction::PopCleanupBlocks().
getSize()
size_t clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::getSize () const inline
Definition at line 703 of file CodeGenFunction.h.
References Size.
Referenced by clang::CodeGen::CodeGenFunction::PopCleanupBlocks().
isConditional()
bool clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::isConditional () const inline
Definition at line 705 of file CodeGenFunction.h.
References IsConditional.
Referenced by clang::CodeGen::CodeGenFunction::PopCleanupBlocks().
Member Data Documentation
IsConditional
unsigned clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::IsConditional
Whether this is a conditional cleanup.
Definition at line 701 of file CodeGenFunction.h.
Referenced by isConditional(), and clang::CodeGen::CodeGenFunction::pushCleanupAfterFullExprWithActiveFlag().
Kind
unsigned clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::Kind
The kind of cleanup to push.
Definition at line 698 of file CodeGenFunction.h.
Referenced by getKind().
Size
unsigned clang::CodeGen::CodeGenFunction::LifetimeExtendedCleanupHeader::Size
The size of the following cleanup object.
Definition at line 695 of file CodeGenFunction.h.
Referenced by getSize(), and clang::CodeGen::CodeGenFunction::pushCleanupAfterFullExprWithActiveFlag().
The documentation for this struct was generated from the following file:
lib/CodeGen/CodeGenFunction.h