clang: llvm::GraphTraits< const clang::CallGraph * > Struct Reference
llvm::GraphTraits< const clang::CallGraph * > Struct Reference
#include "clang/Analysis/CallGraph.h"
Public Types
using nodes_iterator = mapped_iterator< clang::CallGraph::const_iterator, decltype(&CGGetValue)>
Public Types inherited from llvm::GraphTraits< const clang::CallGraphNode * >
using NodeType = const clang::CallGraphNode
using NodeRef = const clang::CallGraphNode *
using ChildIteratorType = NodeType::const_iterator
Static Public Member Functions
static NodeType * getEntryNode (const clang::CallGraph *CGN)
static clang::CallGraphNode * CGGetValue (clang::CallGraph::const_iterator::value_type &P)
static nodes_iterator nodes_begin (const clang::CallGraph *CG)
static nodes_iterator nodes_end (const clang::CallGraph *CG)
static unsigned size (const clang::CallGraph *CG)
Static Public Member Functions inherited from llvm::GraphTraits< const clang::CallGraphNode * >
static NodeType * getEntryNode (const clang::CallGraphNode *CGN)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
Detailed Description
Definition at line 305 of file CallGraph.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< const clang::CallGraph * >::nodes_iterator = mapped_iterator<clang::CallGraph::const_iterator, decltype(&CGGetValue)>
Definition at line 317 of file CallGraph.h.
Member Function Documentation
CGGetValue()
static clang::CallGraphNode* llvm::GraphTraits< const clang::CallGraph * >::CGGetValue (clang::CallGraph::const_iterator::value_type & P) inline static
Definition at line 312 of file CallGraph.h.
References P.
getEntryNode()
static NodeType* llvm::GraphTraits< const clang::CallGraph * >::getEntryNode (const clang::CallGraph * CGN) inline static
Definition at line 307 of file CallGraph.h.
References clang::CallGraph::getRoot().
nodes_begin()
static nodes_iterator llvm::GraphTraits< const clang::CallGraph * >::nodes_begin (const clang::CallGraph * CG) inline static
Definition at line 320 of file CallGraph.h.
References clang::CallGraph::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< const clang::CallGraph * >::nodes_end (const clang::CallGraph * CG) inline static
Definition at line 324 of file CallGraph.h.
References clang::CallGraph::end().
size()
static unsigned llvm::GraphTraits< const clang::CallGraph * >::size (const clang::CallGraph * CG) inline static
Definition at line 328 of file CallGraph.h.
References clang::CallGraph::size().
The documentation for this struct was generated from the following file:
include/clang/Analysis/CallGraph.h