clang: clang::serialization::PPSkippedRange Struct Reference
clang::serialization::PPSkippedRange Struct Reference
Source range of a skipped preprocessor region.
#include "clang/Serialization/ASTBitCodes.h"
Public Member Functions
PPSkippedRange (SourceRange R)
SourceLocation getBegin () const
SourceLocation getEnd () const
Public Attributes
SourceLocation::UIntTy Begin
Raw source location of beginning of range.
SourceLocation::UIntTy End
Raw source location of end of range.
Detailed Description
Source range of a skipped preprocessor region.
Definition at line 274 of file ASTBitCodes.h.
Constructor & Destructor Documentation
PPSkippedRange()
clang::serialization::PPSkippedRange::PPSkippedRange (SourceRange R) inline
Definition at line 280 of file ASTBitCodes.h.
Member Function Documentation
getBegin()
SourceLocation clang::serialization::PPSkippedRange::getBegin () const inline
Definition at line 284 of file ASTBitCodes.h.
References Begin, and clang::SourceLocation::getFromRawEncoding().
Referenced by clang::ASTReader::ReadSkippedRange().
getEnd()
SourceLocation clang::serialization::PPSkippedRange::getEnd () const inline
Definition at line 287 of file ASTBitCodes.h.
References End, and clang::SourceLocation::getFromRawEncoding().
Referenced by clang::ASTReader::ReadSkippedRange().
Member Data Documentation
Begin
SourceLocation::UIntTy clang::serialization::PPSkippedRange::Begin
Raw source location of beginning of range.
Definition at line 276 of file ASTBitCodes.h.
Referenced by getBegin().
End
SourceLocation::UIntTy clang::serialization::PPSkippedRange::End
Raw source location of end of range.
Definition at line 278 of file ASTBitCodes.h.
Referenced by getEnd().
The documentation for this struct was generated from the following file:
include/clang/Serialization/ASTBitCodes.h