clang: clang::interp::VarCreationState Struct Reference
clang::interp::VarCreationState Struct Reference
State encapsulating if a the variable creation has been successful, unsuccessful, or no variable has been created at all.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/AST/Interp/Compiler.h"
Public Member Functions
VarCreationState ()=default
VarCreationState (bool b)
operator bool () const
bool notCreated () const
Static Public Member Functions
static VarCreationState NotCreated ()
Public Attributes
std::optional< bool > S = std::nullopt
Detailed Description
State encapsulating if a the variable creation has been successful, unsuccessful, or no variable has been created at all.
Definition at line 84 of file Compiler.h.
Constructor & Destructor Documentation
VarCreationState() [1/2]
clang::interp::VarCreationState::VarCreationState () default
Referenced by NotCreated().
VarCreationState() [2/2]
clang::interp::VarCreationState::VarCreationState (bool b) inline
Definition at line 87 of file Compiler.h.
Member Function Documentation
NotCreated()
static VarCreationState clang::interp::VarCreationState::NotCreated () inline static
Definition at line 88 of file Compiler.h.
References VarCreationState().
Referenced by clang::interp::Compiler< Emitter >::visitVarDecl().
notCreated()
bool clang::interp::VarCreationState::notCreated () const inline
Definition at line 91 of file Compiler.h.
References S.
operator bool()
clang::interp::VarCreationState::operator bool () const inline
Definition at line 90 of file Compiler.h.
References S.
Member Data Documentation
S
std::optional<bool> clang::interp::VarCreationState::S = std::nullopt
Definition at line 85 of file Compiler.h.
Referenced by notCreated(), and operator bool().
The documentation for this struct was generated from the following file:
lib/AST/Interp/Compiler.h