clang: llvm::DenseMapInfo< clang::NestedNameSpecifierLoc > Struct Reference
llvm::DenseMapInfo< clang::NestedNameSpecifierLoc > Struct Reference
#include "clang/AST/NestedNameSpecifier.h"
Public Types
using FirstInfo = DenseMapInfo< clang::NestedNameSpecifier * >
using SecondInfo = DenseMapInfo< void * >
Static Public Member Functions
static clang::NestedNameSpecifierLoc getEmptyKey ()
static clang::NestedNameSpecifierLoc getTombstoneKey ()
static unsigned getHashValue (const clang::NestedNameSpecifierLoc &PairVal)
static bool isEqual (const clang::NestedNameSpecifierLoc &LHS, const clang::NestedNameSpecifierLoc &RHS)
Detailed Description
Definition at line 533 of file NestedNameSpecifier.h.
Member Typedef Documentation
FirstInfo
using llvm::DenseMapInfo< clang::NestedNameSpecifierLoc >::FirstInfo = DenseMapInfo<clang::NestedNameSpecifier *>
Definition at line 534 of file NestedNameSpecifier.h.
SecondInfo
using llvm::DenseMapInfo< clang::NestedNameSpecifierLoc >::SecondInfo = DenseMapInfo<void *>
Definition at line 535 of file NestedNameSpecifier.h.
Member Function Documentation
getEmptyKey()
static clang::NestedNameSpecifierLoc llvm::DenseMapInfo< clang::NestedNameSpecifierLoc >::getEmptyKey () inline static
Definition at line 537 of file NestedNameSpecifier.h.
getHashValue()
static unsigned llvm::DenseMapInfo< clang::NestedNameSpecifierLoc >::getHashValue (const clang::NestedNameSpecifierLoc & PairVal) inline static
Definition at line 547 of file NestedNameSpecifier.h.
References clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), clang::NestedNameSpecifierLoc::getOpaqueData(), and clang::format::hash_combine().
getTombstoneKey()
static clang::NestedNameSpecifierLoc llvm::DenseMapInfo< clang::NestedNameSpecifierLoc >::getTombstoneKey () inline static
Definition at line 542 of file NestedNameSpecifier.h.
isEqual()
static bool llvm::DenseMapInfo< clang::NestedNameSpecifierLoc >::isEqual (const clang::NestedNameSpecifierLoc & LHS, const clang::NestedNameSpecifierLoc & RHS) inline static
Definition at line 553 of file NestedNameSpecifier.h.
The documentation for this struct was generated from the following file:
include/clang/AST/NestedNameSpecifier.h