clang: llvm::GraphTraits< ::clang::CFG * > Struct Reference
llvm::GraphTraits< ::clang::CFG * > Struct Reference
#include "clang/Analysis/CFG.h"
Public Types
using nodes_iterator = ::clang::CFG::iterator
Public Types inherited from llvm::GraphTraits< ::clang::CFGBlock * >
using NodeRef = ::clang::CFGBlock *
using ChildIteratorType = ::clang::CFGBlock::succ_iterator
Static Public Member Functions
static NodeRef getEntryNode (::clang::CFG *F)
static nodes_iterator nodes_begin (::clang::CFG *F)
static nodes_iterator nodes_end (::clang::CFG *F)
static unsigned size (::clang::CFG *F)
Static Public Member Functions inherited from llvm::GraphTraits< ::clang::CFGBlock * >
static NodeRef getEntryNode (::clang::CFGBlock *BB)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 1532 of file CFG.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< ::clang::CFG * >::nodes_iterator = ::clang::CFG::iterator
Definition at line 1534 of file CFG.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< ::clang::CFG * >::getEntryNode (::clang::CFG * F) inline static
Definition at line 1536 of file CFG.h.
References clang::CFG::getEntry().
nodes_begin()
static nodes_iterator llvm::GraphTraits< ::clang::CFG * >::nodes_begin (::clang::CFG * F) inline static
Definition at line 1537 of file CFG.h.
References clang::CFG::nodes_begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< ::clang::CFG * >::nodes_end (::clang::CFG * F) inline static
Definition at line 1538 of file CFG.h.
References clang::CFG::nodes_end().
size()
static unsigned llvm::GraphTraits< ::clang::CFG * >::size (::clang::CFG * F) inline static
Definition at line 1539 of file CFG.h.
References clang::CFG::size().
The documentation for this struct was generated from the following file:
include/clang/Analysis/CFG.h