clang: clang::DynTypedNode::DenseMapInfo Struct Reference
clang::DynTypedNode::DenseMapInfo Struct Reference
Hooks for using DynTypedNode as a key in a DenseMap.
#include "clang/AST/ASTTypeTraits.h"
Static Public Member Functions
static DynTypedNode getEmptyKey ()
static DynTypedNode getTombstoneKey ()
static unsigned getHashValue (const DynTypedNode &Val)
static bool isEqual (const DynTypedNode &LHS, const DynTypedNode &RHS)
Detailed Description
Hooks for using DynTypedNode as a key in a DenseMap.
Definition at line 366 of file ASTTypeTraits.h.
Member Function Documentation
getEmptyKey()
static DynTypedNode clang::DynTypedNode::DenseMapInfo::getEmptyKey () inline static
Definition at line 367 of file ASTTypeTraits.h.
References clang::ASTNodeKind::DenseMapInfo::getEmptyKey(), and Node.
getHashValue()
static unsigned clang::DynTypedNode::DenseMapInfo::getHashValue (const DynTypedNode & Val) inline static
Definition at line 377 of file ASTTypeTraits.h.
References clang::DynTypedNode::getMemoizationData(), clang::DynTypedNode::getUnchecked(), clang::format::hash_combine(), and clang::hash_value().
getTombstoneKey()
static DynTypedNode clang::DynTypedNode::DenseMapInfo::getTombstoneKey () inline static
Definition at line 372 of file ASTTypeTraits.h.
References clang::ASTNodeKind::DenseMapInfo::getTombstoneKey(), and Node.
isEqual()
static bool clang::DynTypedNode::DenseMapInfo::isEqual (const DynTypedNode & LHS, const DynTypedNode & RHS) inline static
Definition at line 395 of file ASTTypeTraits.h.
References clang::ASTNodeKind::DenseMapInfo::getEmptyKey(), clang::ASTNodeKind::DenseMapInfo::getTombstoneKey(), and clang::ASTNodeKind::DenseMapInfo::isEqual().
The documentation for this struct was generated from the following file:
include/clang/AST/ASTTypeTraits.h