clang: clang::Parser::ReenterClassScopeRAII Struct Reference
clang::Parser::ReenterClassScopeRAII Struct Reference
Utility to re-enter a class scope while parsing its late-parsed components.
Public Member Functions
ReenterClassScopeRAII (Parser &P, ParsingClass &Class)
~ReenterClassScopeRAII ()
Public Member Functions inherited from clang::Parser::ReenterTemplateScopeRAII
ReenterTemplateScopeRAII (Parser &P, Decl *MaybeTemplated, bool Enter=true)
Public Attributes
ParsingClass & Class
Public Attributes inherited from clang::Parser::ReenterTemplateScopeRAII
Parser & P
MultiParseScope Scopes
TemplateParameterDepthRAII CurTemplateDepthTracker
Detailed Description
Utility to re-enter a class scope while parsing its late-parsed components.
Definition at line 306 of file ParseCXXInlineMethods.cpp.
Constructor & Destructor Documentation
ReenterClassScopeRAII()
clang::Parser::ReenterClassScopeRAII::ReenterClassScopeRAII (Parser & P, ParsingClass & Class) inline
Definition at line 309 of file ParseCXXInlineMethods.cpp.
References clang::Sema::ActOnStartDelayedMemberDeclarations(), clang::Parser::ReenterClassScopeRAII::Class, clang::Parser::MultiParseScope::Enter(), clang::Parser::getCurScope(), clang::Parser::ReenterTemplateScopeRAII::P, and clang::Parser::ReenterTemplateScopeRAII::Scopes.
~ReenterClassScopeRAII()
clang::Parser::ReenterClassScopeRAII::~ReenterClassScopeRAII () inline
Definition at line 322 of file ParseCXXInlineMethods.cpp.
References clang::Sema::ActOnFinishDelayedMemberDeclarations(), clang::Parser::ReenterClassScopeRAII::Class, clang::Parser::getCurScope(), and clang::Parser::ReenterTemplateScopeRAII::P.
Member Data Documentation
Class
ParsingClass& clang::Parser::ReenterClassScopeRAII::Class
Definition at line 307 of file ParseCXXInlineMethods.cpp.
Referenced by clang::Parser::ReenterClassScopeRAII::ReenterClassScopeRAII(), and clang::Parser::ReenterClassScopeRAII::~ReenterClassScopeRAII().
The documentation for this struct was generated from the following file:
lib/Parse/ParseCXXInlineMethods.cpp