clang: clang::ExprMutationAnalyzer::Analyzer Struct Reference
clang::ExprMutationAnalyzer::Analyzer Struct Reference
#include "clang/Analysis/Analyses/ExprMutationAnalyzer.h"
Public Member Functions
Analyzer (const Stmt &Stm, ASTContext &Context, Memoized &Memorized)
const Stmt * findMutation (const Expr *Exp)
const Stmt * findMutation (const Decl *Dec)
const Stmt * findPointeeMutation (const Expr *Exp)
const Stmt * findPointeeMutation (const Decl *Dec)
Static Public Member Functions
static bool isUnevaluated (const Stmt *Smt, const Stmt &Stm, ASTContext &Context)
Detailed Description
Definition at line 41 of file ExprMutationAnalyzer.h.
Constructor & Destructor Documentation
Analyzer()
clang::ExprMutationAnalyzer::Analyzer::Analyzer (const Stmt & Stm, ASTContext & Context, Memoized & Memorized) inline
Definition at line 42 of file ExprMutationAnalyzer.h.
Member Function Documentation
findMutation() [1/2]
const Stmt * clang::ExprMutationAnalyzer::Analyzer::findMutation (const Decl * Dec)
Definition at line 216 of file ExprMutationAnalyzer.cpp.
References findMutation().
findMutation() [2/2]
const Stmt * clang::ExprMutationAnalyzer::Analyzer::findMutation (const Expr * Exp)
Definition at line 203 of file ExprMutationAnalyzer.cpp.
Referenced by findMutation(), and clang::ExprMutationAnalyzer::findMutation().
findPointeeMutation() [1/2]
const Stmt * clang::ExprMutationAnalyzer::Analyzer::findPointeeMutation (const Decl * Dec)
Definition at line 226 of file ExprMutationAnalyzer.cpp.
References findPointeeMutation().
findPointeeMutation() [2/2]
const Stmt * clang::ExprMutationAnalyzer::Analyzer::findPointeeMutation (const Expr * Exp)
Definition at line 221 of file ExprMutationAnalyzer.cpp.
Referenced by findPointeeMutation(), and clang::ExprMutationAnalyzer::findPointeeMutation().
isUnevaluated()
bool clang::ExprMutationAnalyzer::Analyzer::isUnevaluated (const Stmt * Smt, const Stmt & Stm, ASTContext & Context) static
Definition at line 270 of file ExprMutationAnalyzer.cpp.
The documentation for this struct was generated from the following files:
include/clang/Analysis/Analyses/ExprMutationAnalyzer.h
lib/Analysis/ExprMutationAnalyzer.cpp