clang: clang::DefaultInitializedTypeVisitor< Derived, RetTy > Struct Template Reference
clang::DefaultInitializedTypeVisitor< Derived, RetTy > Struct Template Reference
#include "clang/AST/NonTrivialTypeVisitor.h"
Public Member Functions
template<class... Ts>
RetTy visit (QualType FT, Ts &&... Args)
template<class... Ts>
RetTy visitWithKind (QualType::PrimitiveDefaultInitializeKind PDIK, QualType FT, Ts &&... Args)
Derived & asDerived ()
Detailed Description
template<class Derived, class RetTy = void>
struct clang::DefaultInitializedTypeVisitor< Derived, RetTy >
Definition at line 50 of file NonTrivialTypeVisitor.h.
Member Function Documentation
asDerived()
template<class Derived , class RetTy = void> Derived& clang::DefaultInitializedTypeVisitor< Derived, RetTy >::asDerived () inline
Definition at line 74 of file NonTrivialTypeVisitor.h.
Referenced by clang::DefaultInitializedTypeVisitor< Derived, RetTy >::visit(), and clang::DefaultInitializedTypeVisitor< Derived, RetTy >::visitWithKind().
visit()
template<class Derived , class RetTy = void> template<class... Ts> RetTy clang::DefaultInitializedTypeVisitor< Derived, RetTy >::visit (QualType FT, Ts &&... Args) inline
Definition at line 51 of file NonTrivialTypeVisitor.h.
References clang::DefaultInitializedTypeVisitor< Derived, RetTy >::asDerived(), and clang::QualType::isNonTrivialToPrimitiveDefaultInitialize().
Referenced by clang::Sema::checkNonTrivialCUnion().
visitWithKind()
template<class Derived , class RetTy = void> template<class... Ts> RetTy clang::DefaultInitializedTypeVisitor< Derived, RetTy >::visitWithKind (QualType::PrimitiveDefaultInitializeKind PDIK, QualType FT, Ts &&... Args) inline
Definition at line 58 of file NonTrivialTypeVisitor.h.
References clang::DefaultInitializedTypeVisitor< Derived, RetTy >::asDerived(), clang::QualType::PDIK_ARCStrong, clang::QualType::PDIK_ARCWeak, clang::QualType::PDIK_Struct, and clang::QualType::PDIK_Trivial.
The documentation for this struct was generated from the following file:
include/clang/AST/NonTrivialTypeVisitor.h