clang: clang::TemplateArgumentLocInfo Struct Reference
clang::TemplateArgumentLocInfo Struct Reference
Location information for a TemplateArgument.
#include "clang/AST/TemplateBase.h"
Public Member Functions
TemplateArgumentLocInfo ()
TemplateArgumentLocInfo (TypeSourceInfo *Declarator)
TemplateArgumentLocInfo (Expr *E)
TemplateArgumentLocInfo (ASTContext &Ctx, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateNameLoc, SourceLocation EllipsisLoc)
TypeSourceInfo * getAsTypeSourceInfo () const
Expr * getAsExpr () const
NestedNameSpecifierLoc getTemplateQualifierLoc () const
SourceLocation getTemplateNameLoc () const
SourceLocation getTemplateEllipsisLoc () const
Detailed Description
Location information for a TemplateArgument.
Definition at line 472 of file TemplateBase.h.
Constructor & Destructor Documentation
TemplateArgumentLocInfo() [1/4]
clang::TemplateArgumentLocInfo::TemplateArgumentLocInfo () inline
Definition at line 491 of file TemplateBase.h.
TemplateArgumentLocInfo() [2/4]
clang::TemplateArgumentLocInfo::TemplateArgumentLocInfo (TypeSourceInfo * Declarator) inline
Definition at line 492 of file TemplateBase.h.
TemplateArgumentLocInfo() [3/4]
clang::TemplateArgumentLocInfo::TemplateArgumentLocInfo (Expr * E) inline
Definition at line 494 of file TemplateBase.h.
TemplateArgumentLocInfo() [4/4]
clang::TemplateArgumentLocInfo::TemplateArgumentLocInfo (ASTContext & Ctx, NestedNameSpecifierLoc QualifierLoc, SourceLocation TemplateNameLoc, SourceLocation EllipsisLoc)
Definition at line 701 of file TemplateBase.cpp.
References clang::NestedNameSpecifierLoc::getNestedNameSpecifier(), and clang::NestedNameSpecifierLoc::getOpaqueData().
Member Function Documentation
getAsExpr()
Expr* clang::TemplateArgumentLocInfo::getAsExpr () const inline
Definition at line 505 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddTemplateArgumentLoc(), clang::ASTRecordWriter::AddTemplateArgumentLocInfo(), clang::TemplateArgumentLoc::getSourceDeclExpression(), clang::TemplateArgumentLoc::getSourceExpression(), clang::TemplateArgumentLoc::getSourceIntegralExpression(), clang::TemplateArgumentLoc::getSourceNullPtrExpression(), clang::TemplateArgumentLoc::getSourceStructuralValueExpression(), and clang::ASTNodeImporter::import().
getAsTypeSourceInfo()
TypeSourceInfo* clang::TemplateArgumentLocInfo::getAsTypeSourceInfo () const inline
Definition at line 501 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddTemplateArgumentLocInfo(), clang::TemplateArgumentLoc::getTypeSourceInfo(), and clang::ASTNodeImporter::import().
getTemplateEllipsisLoc()
SourceLocation clang::TemplateArgumentLocInfo::getTemplateEllipsisLoc () const inline
Definition at line 517 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddTemplateArgumentLocInfo(), clang::TemplateArgumentLoc::getTemplateEllipsisLoc(), and clang::ASTNodeImporter::import().
getTemplateNameLoc()
SourceLocation clang::TemplateArgumentLocInfo::getTemplateNameLoc () const inline
Definition at line 513 of file TemplateBase.h.
Referenced by clang::ASTRecordWriter::AddTemplateArgumentLocInfo(), clang::TemplateArgumentLoc::getTemplateNameLoc(), and clang::ASTNodeImporter::import().
getTemplateQualifierLoc()
NestedNameSpecifierLoc clang::TemplateArgumentLocInfo::getTemplateQualifierLoc () const inline
Definition at line 507 of file TemplateBase.h.
References clang::TemplateArgument::Template.
Referenced by clang::ASTRecordWriter::AddTemplateArgumentLocInfo(), clang::TemplateArgumentLoc::getTemplateQualifierLoc(), and clang::ASTNodeImporter::import().
The documentation for this struct was generated from the following files:
include/clang/AST/TemplateBase.h
lib/AST/TemplateBase.cpp