clang: llvm::GraphTraits< Inverse< ::clang::CFG * > > Struct Reference
llvm::GraphTraits< Inverse< ::clang::CFG * > > Struct Reference
#include "clang/Analysis/CFG.h"
Public Types
using nodes_iterator = ::clang::CFG::iterator
Public Types inherited from llvm::GraphTraits< Inverse< ::clang::CFGBlock * > >
using NodeRef = ::clang::CFGBlock *
using ChildIteratorType = ::clang::CFGBlock::const_pred_iterator
Static Public Member Functions
static NodeRef getEntryNode (::clang::CFG *F)
static nodes_iterator nodes_begin (::clang::CFG *F)
static nodes_iterator nodes_end (::clang::CFG *F)
Static Public Member Functions inherited from llvm::GraphTraits< Inverse< ::clang::CFGBlock * > >
static NodeRef getEntryNode (Inverse<::clang::CFGBlock * > G)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 1554 of file CFG.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< Inverse< ::clang::CFG * > >::nodes_iterator = ::clang::CFG::iterator
Definition at line 1556 of file CFG.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< Inverse< ::clang::CFG * > >::getEntryNode (::clang::CFG * F) inline static
Definition at line 1558 of file CFG.h.
References clang::CFG::getExit().
nodes_begin()
static nodes_iterator llvm::GraphTraits< Inverse< ::clang::CFG * > >::nodes_begin (::clang::CFG * F) inline static
Definition at line 1559 of file CFG.h.
References clang::CFG::nodes_begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< Inverse< ::clang::CFG * > >::nodes_end (::clang::CFG * F) inline static
Definition at line 1560 of file CFG.h.
References clang::CFG::nodes_end().
The documentation for this struct was generated from the following file:
include/clang/Analysis/CFG.h