clang: clang::FoldExpandedConstraint Struct Reference
clang::FoldExpandedConstraint Struct Reference
#include "clang/Sema/SemaConcept.h"
Public Types
enum class FoldOperatorKind { And , Or }
Public Member Functions
FoldExpandedConstraint (FoldOperatorKind K, NormalizedConstraint C, const Expr *Pattern)
template<typename AtomicSubsumptionEvaluator >
bool subsumes (const FoldExpandedConstraint &Other, const AtomicSubsumptionEvaluator &E) const
Static Public Member Functions
static bool AreCompatibleForSubsumption (const FoldExpandedConstraint &A, const FoldExpandedConstraint &B)
Public Attributes
enum clang::FoldExpandedConstraint::FoldOperatorKind Kind
NormalizedConstraint Constraint
const Expr * Pattern
Detailed Description
Definition at line 174 of file SemaConcept.h.
Member Enumeration Documentation
FoldOperatorKind
enum clang::FoldExpandedConstraint::FoldOperatorKind strong
Enumerator
And
Or
Definition at line 175 of file SemaConcept.h.
Constructor & Destructor Documentation
FoldExpandedConstraint()
clang::FoldExpandedConstraint::FoldExpandedConstraint (FoldOperatorKind K, NormalizedConstraint C, const Expr * Pattern) inline
Definition at line 179 of file SemaConcept.h.
Member Function Documentation
AreCompatibleForSubsumption()
bool FoldExpandedConstraint::AreCompatibleForSubsumption (const FoldExpandedConstraint & A, const FoldExpandedConstraint & B) static
Definition at line 1638 of file SemaConcept.cpp.
References clang::Sema::collectUnexpandedParameterPacks(), clang::getDepthAndIndex(), and Pattern.
subsumes()
template<typename AtomicSubsumptionEvaluator > bool clang::FoldExpandedConstraint::subsumes (const FoldExpandedConstraint & Other, const AtomicSubsumptionEvaluator & E) const
Definition at line 263 of file SemaConcept.h.
References E, Kind, clang::makeCNF(), clang::makeDNF(), clang::Other, and clang::subsumes().
Referenced by clang::subsumes().
Member Data Documentation
Constraint
NormalizedConstraint clang::FoldExpandedConstraint::Constraint
Definition at line 176 of file SemaConcept.h.
Kind
enum clang::FoldExpandedConstraint::FoldOperatorKind clang::FoldExpandedConstraint::Kind
Pattern
const Expr* clang::FoldExpandedConstraint::Pattern
Definition at line 177 of file SemaConcept.h.
Referenced by AreCompatibleForSubsumption().
The documentation for this struct was generated from the following files:
include/clang/Sema/SemaConcept.h
lib/Sema/SemaConcept.cpp