clang: clang::Parser::ConditionDeclarationOrInitStatementState Struct Reference
clang::Parser::ConditionDeclarationOrInitStatementState Struct Reference
Public Member Functions
ConditionDeclarationOrInitStatementState (Parser &P, bool CanBeInitStatement, bool CanBeForRangeDecl)
bool resolved ()
void markNotExpression ()
bool markNotCondition ()
bool markNotForRangeDecl ()
bool update (TPResult IsDecl)
ConditionOrInitStatement result () const
Public Attributes
Parser & P
bool CanBeExpression = true
bool CanBeCondition = true
bool CanBeInitStatement
bool CanBeForRangeDecl
Detailed Description
Definition at line 384 of file ParseTentative.cpp.
Constructor & Destructor Documentation
ConditionDeclarationOrInitStatementState()
clang::Parser::ConditionDeclarationOrInitStatementState::ConditionDeclarationOrInitStatementState (Parser & P, bool CanBeInitStatement, bool CanBeForRangeDecl) inline
Definition at line 391 of file ParseTentative.cpp.
Member Function Documentation
markNotCondition()
bool clang::Parser::ConditionDeclarationOrInitStatementState::markNotCondition () inline
Definition at line 443 of file ParseTentative.cpp.
References clang::Parser::ConditionDeclarationOrInitStatementState::CanBeCondition, and clang::Parser::ConditionDeclarationOrInitStatementState::resolved().
markNotExpression()
void clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression () inline
Definition at line 401 of file ParseTentative.cpp.
References clang::Parser::ConditionDeclarationOrInitStatementState::CanBeCondition, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeExpression, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeForRangeDecl, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeInitStatement, clang::Parser::ConsumeToken(), clang::Token::is(), clang::Token::isNot(), clang::Parser::ConditionDeclarationOrInitStatementState::P, clang::Parser::ConditionDeclarationOrInitStatementState::resolved(), clang::Parser::SkipUntil(), and clang::Parser::StopBeforeMatch.
Referenced by clang::Parser::ConditionDeclarationOrInitStatementState::update().
markNotForRangeDecl()
bool clang::Parser::ConditionDeclarationOrInitStatementState::markNotForRangeDecl () inline
Definition at line 448 of file ParseTentative.cpp.
References clang::Parser::ConditionDeclarationOrInitStatementState::CanBeForRangeDecl, and clang::Parser::ConditionDeclarationOrInitStatementState::resolved().
resolved()
bool clang::Parser::ConditionDeclarationOrInitStatementState::resolved () inline
Definition at line 396 of file ParseTentative.cpp.
References clang::Parser::ConditionDeclarationOrInitStatementState::CanBeCondition, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeExpression, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeForRangeDecl, and clang::Parser::ConditionDeclarationOrInitStatementState::CanBeInitStatement.
Referenced by clang::Parser::ConditionDeclarationOrInitStatementState::markNotCondition(), clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), clang::Parser::ConditionDeclarationOrInitStatementState::markNotForRangeDecl(), and clang::Parser::ConditionDeclarationOrInitStatementState::update().
result()
ConditionOrInitStatement clang::Parser::ConditionDeclarationOrInitStatementState::result () const inline
Definition at line 472 of file ParseTentative.cpp.
References clang::Parser::ConditionDeclarationOrInitStatementState::CanBeCondition, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeExpression, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeForRangeDecl, and clang::Parser::ConditionDeclarationOrInitStatementState::CanBeInitStatement.
update()
bool clang::Parser::ConditionDeclarationOrInitStatementState::update (TPResult IsDecl) inline
Definition at line 453 of file ParseTentative.cpp.
References clang::Parser::ConditionDeclarationOrInitStatementState::CanBeCondition, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeExpression, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeForRangeDecl, clang::Parser::ConditionDeclarationOrInitStatementState::CanBeInitStatement, clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), and clang::Parser::ConditionDeclarationOrInitStatementState::resolved().
Member Data Documentation
CanBeCondition
bool clang::Parser::ConditionDeclarationOrInitStatementState::CanBeCondition = true
Definition at line 387 of file ParseTentative.cpp.
Referenced by clang::Parser::ConditionDeclarationOrInitStatementState::markNotCondition(), clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), clang::Parser::ConditionDeclarationOrInitStatementState::resolved(), clang::Parser::ConditionDeclarationOrInitStatementState::result(), and clang::Parser::ConditionDeclarationOrInitStatementState::update().
CanBeExpression
bool clang::Parser::ConditionDeclarationOrInitStatementState::CanBeExpression = true
Definition at line 386 of file ParseTentative.cpp.
Referenced by clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), clang::Parser::ConditionDeclarationOrInitStatementState::resolved(), clang::Parser::ConditionDeclarationOrInitStatementState::result(), and clang::Parser::ConditionDeclarationOrInitStatementState::update().
CanBeForRangeDecl
bool clang::Parser::ConditionDeclarationOrInitStatementState::CanBeForRangeDecl
Definition at line 389 of file ParseTentative.cpp.
Referenced by clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), clang::Parser::ConditionDeclarationOrInitStatementState::markNotForRangeDecl(), clang::Parser::ConditionDeclarationOrInitStatementState::resolved(), clang::Parser::ConditionDeclarationOrInitStatementState::result(), and clang::Parser::ConditionDeclarationOrInitStatementState::update().
CanBeInitStatement
bool clang::Parser::ConditionDeclarationOrInitStatementState::CanBeInitStatement
Definition at line 388 of file ParseTentative.cpp.
Referenced by clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression(), clang::Parser::ConditionDeclarationOrInitStatementState::resolved(), clang::Parser::ConditionDeclarationOrInitStatementState::result(), and clang::Parser::ConditionDeclarationOrInitStatementState::update().
P
Parser& clang::Parser::ConditionDeclarationOrInitStatementState::P
Definition at line 385 of file ParseTentative.cpp.
Referenced by clang::Parser::ConditionDeclarationOrInitStatementState::markNotExpression().
The documentation for this struct was generated from the following file:
lib/Parse/ParseTentative.cpp