clang: clang::extractapi::APIIgnoresList Struct Reference
clang::extractapi::APIIgnoresList Struct Reference
A type that provides access to a new line separated list of symbol names to ignore when extracting API information.
#include "clang/ExtractAPI/APIIgnoresList.h"
Public Types
using FilePathList = std::vector< std::string >
Public Member Functions
APIIgnoresList ()=default
bool shouldIgnore (llvm::StringRef SymbolName) const
Check if SymbolName is specified in the APIIgnoresList and if it should therefore be ignored.
Static Public Member Functions
static llvm::Expected< APIIgnoresList > create (const FilePathList &IgnoresFilePathList, FileManager &FM)
The API to use for generating from the files at IgnoresFilePathList.
Detailed Description
A type that provides access to a new line separated list of symbol names to ignore when extracting API information.
Definition at line 46 of file APIIgnoresList.h.
Member Typedef Documentation
FilePathList
using clang::extractapi::APIIgnoresList::FilePathList = std::vector<std::string>
Definition at line 47 of file APIIgnoresList.h.
Constructor & Destructor Documentation
APIIgnoresList()
clang::extractapi::APIIgnoresList::APIIgnoresList () default
Member Function Documentation
create()
Expected< APIIgnoresList > APIIgnoresList::create (const FilePathList & IgnoresFilePathList, FileManager & FM) static
The API to use for generating from the files at IgnoresFilePathList.
Returns
an initialized APIIgnoresList or an Error.
Definition at line 35 of file APIIgnoresList.cpp.
References clang::FileManager::getBufferForFile().
Referenced by clang::ExtractAPIAction::CreateASTConsumer(), and clang::WrappingExtractAPIAction::CreateASTConsumer().
shouldIgnore()
bool APIIgnoresList::shouldIgnore (llvm::StringRef SymbolName) const
Check if SymbolName is specified in the APIIgnoresList and if it should therefore be ignored.
Definition at line 59 of file APIIgnoresList.cpp.
The documentation for this struct was generated from the following files:
include/clang/ExtractAPI/APIIgnoresList.h
lib/ExtractAPI/APIIgnoresList.cpp