clang: clang::installapi::InstallAPIContext Struct Reference
clang::installapi::InstallAPIContext Struct Reference
Struct used for generating validating InstallAPI.
#include "clang/InstallAPI/Context.h"
Public Member Functions
void addKnownHeader (const HeaderFile &H)
Populate entries of headers that should be included for TextAPI generation.
std::optional< HeaderType > findAndRecordFile (const FileEntry *FE, const Preprocessor &PP)
Record visited files during frontend actions to determine whether to include their declarations for TextAPI generation.
Public Attributes
BinaryAttrs BA
Library attributes that are typically passed as linker inputs.
LibAttrs Reexports
Install names of reexported libraries of a library.
HeaderSeq InputHeaders
All headers that represent a library.
Language LangMode = Language::ObjC
Active language mode to parse in.
HeaderType Type = HeaderType::Unknown
Active header access type.
std::shared_ptr< FrontendRecordsSlice > Slice
Active TargetSlice for symbol record collection.
FileManager * FM = nullptr
FileManager for all I/O operations.
DiagnosticsEngine * Diags = nullptr
DiagnosticsEngine for all error reporting.
std::unique_ptr< DylibVerifier > Verifier = nullptr
Verifier when binary dylib is passed as input.
llvm::StringRef OutputLoc {}
File Path of output location.
FileType FT = FileType::TBD_V5
What encoding to write output as.
Detailed Description
Struct used for generating validating InstallAPI.
The attributes captured represent all necessary information to generate TextAPI output.
Definition at line 26 of file Context.h.
Member Function Documentation
addKnownHeader()
void clang::installapi::InstallAPIContext::addKnownHeader (const HeaderFile & H)
Populate entries of headers that should be included for TextAPI generation.
Definition at line 109 of file Frontend.cpp.
References clang::installapi::HeaderFile::getIncludeName(), clang::installapi::HeaderFile::getPath(), clang::installapi::HeaderFile::getType(), and clang::installapi::HeaderFile::useIncludeName().
Referenced by clang::installapi::createInputBuffer().
findAndRecordFile()
std::optional< HeaderType > clang::installapi::InstallAPIContext::findAndRecordFile (const FileEntry * FE, const Preprocessor & PP)
Record visited files during frontend actions to determine whether to include their declarations for TextAPI generation.
Parameters
FE Header that is being parsed.
PP Preprocesser used for querying how header was imported.
Returns
Access level of header if it should be included for TextAPI generation.
Definition at line 78 of file Frontend.cpp.
References clang::Preprocessor::getHeaderSearchInfo(), clang::HeaderSearch::getIncludeNameForHeader(), and clang::prec::Unknown.
Member Data Documentation
BA
BinaryAttrs clang::installapi::InstallAPIContext::BA
Library attributes that are typically passed as linker inputs.
Definition at line 29 of file Context.h.
Diags
DiagnosticsEngine* clang::installapi::InstallAPIContext::Diags = nullptr
DiagnosticsEngine for all error reporting.
Definition at line 50 of file Context.h.
Referenced by clang::installapi::InstallAPIAction::CreateASTConsumer().
FM
FileManager* clang::installapi::InstallAPIContext::FM = nullptr
FileManager for all I/O operations.
Definition at line 47 of file Context.h.
FT
FileType clang::installapi::InstallAPIContext::FT = FileType::TBD_V5
What encoding to write output as.
Definition at line 59 of file Context.h.
InputHeaders
HeaderSeq clang::installapi::InstallAPIContext::InputHeaders
All headers that represent a library.
Definition at line 35 of file Context.h.
Referenced by clang::installapi::createInputBuffer().
LangMode
Language clang::installapi::InstallAPIContext::LangMode = Language::ObjC
Active language mode to parse in.
Definition at line 38 of file Context.h.
Referenced by clang::installapi::createInputBuffer().
OutputLoc
llvm::StringRef clang::installapi::InstallAPIContext::OutputLoc {}
File Path of output location.
Definition at line 56 of file Context.h.
Reexports
LibAttrs clang::installapi::InstallAPIContext::Reexports
Install names of reexported libraries of a library.
Definition at line 32 of file Context.h.
Slice
std::shared_ptr<FrontendRecordsSlice> clang::installapi::InstallAPIContext::Slice
Active TargetSlice for symbol record collection.
Definition at line 44 of file Context.h.
Referenced by clang::installapi::createInputBuffer().
Type
HeaderType clang::installapi::InstallAPIContext::Type = HeaderType::Unknown
Active header access type.
Definition at line 41 of file Context.h.
Referenced by clang::installapi::createInputBuffer().
Verifier
std::unique_ptr<DylibVerifier> clang::installapi::InstallAPIContext::Verifier = nullptr
Verifier when binary dylib is passed as input.
Definition at line 53 of file Context.h.
Referenced by clang::installapi::InstallAPIAction::CreateASTConsumer().
The documentation for this struct was generated from the following files:
include/clang/InstallAPI/Context.h
lib/InstallAPI/Frontend.cpp