clang: llvm::GraphTraits< clang::ento::ExplodedGraph * > Struct Reference
llvm::GraphTraits< clang::ento::ExplodedGraph * > Struct Reference
#include "clang/StaticAnalyzer/Core/PathSensitive/ExplodedGraph.h"
Public Types
using GraphTy = clang::ento::ExplodedGraph *
using NodeRef = clang::ento::ExplodedNode *
using ChildIteratorType = clang::ento::ExplodedNode::succ_iterator
using nodes_iterator = llvm::df_iterator< GraphTy >
Static Public Member Functions
static NodeRef getEntryNode (const GraphTy G)
static bool predecessorOfTrivial (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static nodes_iterator nodes_begin (const GraphTy G)
static nodes_iterator nodes_end (const GraphTy G)
Detailed Description
Definition at line 505 of file ExplodedGraph.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< clang::ento::ExplodedGraph * >::ChildIteratorType = clang::ento::ExplodedNode::succ_iterator
Definition at line 508 of file ExplodedGraph.h.
GraphTy
using llvm::GraphTraits< clang::ento::ExplodedGraph * >::GraphTy = clang::ento::ExplodedGraph *
Definition at line 506 of file ExplodedGraph.h.
NodeRef
using llvm::GraphTraits< clang::ento::ExplodedGraph * >::NodeRef = clang::ento::ExplodedNode *
Definition at line 507 of file ExplodedGraph.h.
nodes_iterator
using llvm::GraphTraits< clang::ento::ExplodedGraph * >::nodes_iterator = llvm::df_iterator<GraphTy>
Definition at line 509 of file ExplodedGraph.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< clang::ento::ExplodedGraph * >::child_begin (NodeRef N) inline static
Definition at line 519 of file ExplodedGraph.h.
References clang::ento::ExplodedNode::succ_begin().
child_end()
static ChildIteratorType llvm::GraphTraits< clang::ento::ExplodedGraph * >::child_end (NodeRef N) inline static
Definition at line 525 of file ExplodedGraph.h.
References clang::ento::ExplodedNode::getFirstSucc(), and clang::ento::ExplodedNode::succ_end().
getEntryNode()
static NodeRef llvm::GraphTraits< clang::ento::ExplodedGraph * >::getEntryNode (const GraphTy G) inline static
Definition at line 511 of file ExplodedGraph.h.
References clang::ento::ExplodedGraph::roots_begin().
nodes_begin()
static nodes_iterator llvm::GraphTraits< clang::ento::ExplodedGraph * >::nodes_begin (const GraphTy G) inline static
Definition at line 531 of file ExplodedGraph.h.
nodes_end()
static nodes_iterator llvm::GraphTraits< clang::ento::ExplodedGraph * >::nodes_end (const GraphTy G) inline static
Definition at line 535 of file ExplodedGraph.h.
predecessorOfTrivial()
static bool llvm::GraphTraits< clang::ento::ExplodedGraph * >::predecessorOfTrivial (NodeRef N) inline static
Definition at line 515 of file ExplodedGraph.h.
References clang::ento::ExplodedNode::getFirstSucc(), clang::ento::ExplodedNode::isTrivial(), and clang::ento::ExplodedNode::succ_size().
The documentation for this struct was generated from the following file:
include/clang/StaticAnalyzer/Core/PathSensitive/ExplodedGraph.h