clang: clang::Sema::InstantiatingTemplate Struct Reference
clang::Sema::InstantiatingTemplate Struct Reference
A stack object to be created when performing template instantiation.
#include "clang/Sema/Sema.h"
Classes
struct BuildingDeductionGuidesTag
struct ConstraintNormalization
struct ConstraintsCheck
struct ConstraintSubstitution
struct ExceptionSpecification
struct ParameterMappingSubstitution
Public Member Functions
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, Decl *Entity, SourceRange InstantiationRange=SourceRange())
Note that we are instantiating a class template, function template, variable template, alias template, or a member thereof.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, FunctionDecl *Entity, ExceptionSpecification, SourceRange InstantiationRange=SourceRange())
Note that we are instantiating an exception specification of a function template.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, TypeAliasTemplateDecl *Entity, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange=SourceRange())
Note that we are instantiating a type alias template declaration.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, TemplateParameter Param, TemplateDecl *Template, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange=SourceRange())
Note that we are instantiating a default argument in a template-id.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, FunctionTemplateDecl *FunctionTemplate, ArrayRef< TemplateArgument > TemplateArgs, CodeSynthesisContext::SynthesisKind Kind, sema::TemplateDeductionInfo &DeductionInfo, SourceRange InstantiationRange=SourceRange())
Note that we are substituting either explicitly-specified or deduced template arguments during function template argument deduction.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, TemplateDecl *Template, ArrayRef< TemplateArgument > TemplateArgs, sema::TemplateDeductionInfo &DeductionInfo, SourceRange InstantiationRange=SourceRange())
Note that we are instantiating as part of template argument deduction for a class template declaration.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, ClassTemplatePartialSpecializationDecl *PartialSpec, ArrayRef< TemplateArgument > TemplateArgs, sema::TemplateDeductionInfo &DeductionInfo, SourceRange InstantiationRange=SourceRange())
Note that we are instantiating as part of template argument deduction for a class template partial specialization.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, VarTemplatePartialSpecializationDecl *PartialSpec, ArrayRef< TemplateArgument > TemplateArgs, sema::TemplateDeductionInfo &DeductionInfo, SourceRange InstantiationRange=SourceRange())
Note that we are instantiating as part of template argument deduction for a variable template partial specialization.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, ParmVarDecl *Param, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange=SourceRange())
Note that we are instantiating a default argument for a function parameter.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, NamedDecl *Template, NonTypeTemplateParmDecl *Param, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange)
Note that we are substituting prior template arguments into a non-type parameter.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, NamedDecl *Template, TemplateTemplateParmDecl *Param, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange)
Note that we are substituting prior template arguments into a template template parameter.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, TemplateDecl *Template, NamedDecl *Param, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange)
Note that we are checking the default template argument against the template parameter for a given template-id.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, ConstraintsCheck, NamedDecl *Template, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange)
Note that we are checking the constraints associated with some constrained entity (a concept declaration or a template with associated constraints).
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, ConstraintSubstitution, NamedDecl *Template, sema::TemplateDeductionInfo &DeductionInfo, SourceRange InstantiationRange)
Note that we are checking a constraint expression associated with a template declaration or as part of the satisfaction check of a concept.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, ConstraintNormalization, NamedDecl *Template, SourceRange InstantiationRange)
Note that we are normalizing a constraint expression.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, ParameterMappingSubstitution, NamedDecl *Template, SourceRange InstantiationRange)
Note that we are subtituting into the parameter mapping of an atomic constraint during constraint normalization.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, concepts::Requirement *Req, sema::TemplateDeductionInfo &DeductionInfo, SourceRange InstantiationRange=SourceRange())
Note that we are substituting template arguments into a part of a requirement of a requires expression.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, concepts::NestedRequirement *Req, ConstraintsCheck, SourceRange InstantiationRange=SourceRange())
Note that we are checking the satisfaction of the constraint expression inside of a nested requirement.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, const RequiresExpr *E, sema::TemplateDeductionInfo &DeductionInfo, SourceRange InstantiationRange)
Note that we are checking a requires clause.
InstantiatingTemplate (Sema &SemaRef, SourceLocation PointOfInstantiation, TemplateDecl *Entity, BuildingDeductionGuidesTag, SourceRange InstantiationRange=SourceRange())
Note that we are building deduction guides.
void Clear ()
Note that we have finished instantiating this template.
~InstantiatingTemplate ()
bool isInvalid () const
Determines whether we have exceeded the maximum recursive template instantiations.
bool isAlreadyInstantiating () const
Determine whether we are already instantiating this specialization in some surrounding active instantiation.
Detailed Description
A stack object to be created when performing template instantiation.
Construction of an object of type InstantiatingTemplate pushes the current instantiation onto the stack of active instantiations. If the size of this stack exceeds the maximum number of recursive template instantiations, construction produces an error and evaluates true.
Destruction of this object will pop the named instantiation off the stack.
Definition at line 10182 of file Sema.h.
Constructor & Destructor Documentation
InstantiatingTemplate() [1/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, Decl * Entity, SourceRange InstantiationRange = SourceRange())
Note that we are instantiating a class template, function template, variable template, alias template, or a member thereof.
Definition at line 639 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [2/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, FunctionDecl * Entity, ExceptionSpecification , SourceRange InstantiationRange = SourceRange())
Note that we are instantiating an exception specification of a function template.
Definition at line 646 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [3/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, TypeAliasTemplateDecl * Entity, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange = SourceRange())
Note that we are instantiating a type alias template declaration.
Definition at line 739 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [4/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, TemplateParameter Param, TemplateDecl * Template, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange = SourceRange())
Note that we are instantiating a default argument in a template-id.
Definition at line 653 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [5/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, FunctionTemplateDecl * FunctionTemplate, ArrayRef< TemplateArgument > TemplateArgs, CodeSynthesisContext::SynthesisKind Kind, sema::TemplateDeductionInfo & DeductionInfo, SourceRange InstantiationRange = SourceRange())
Note that we are substituting either explicitly-specified or deduced template arguments during function template argument deduction.
Definition at line 663 of file SemaTemplateInstantiate.cpp.
References clang::Sema::CodeSynthesisContext::BuildingDeductionGuides, clang::Sema::CodeSynthesisContext::DeducedTemplateArgumentSubstitution, and clang::Sema::CodeSynthesisContext::ExplicitTemplateArgumentSubstitution.
InstantiatingTemplate() [6/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, TemplateDecl * Template, ArrayRef< TemplateArgument > TemplateArgs, sema::TemplateDeductionInfo & DeductionInfo, SourceRange InstantiationRange = SourceRange())
Note that we are instantiating as part of template argument deduction for a class template declaration.
Definition at line 677 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [7/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, ClassTemplatePartialSpecializationDecl * PartialSpec, ArrayRef< TemplateArgument > TemplateArgs, sema::TemplateDeductionInfo & DeductionInfo, SourceRange InstantiationRange = SourceRange())
Note that we are instantiating as part of template argument deduction for a class template partial specialization.
Definition at line 688 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [8/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, VarTemplatePartialSpecializationDecl * PartialSpec, ArrayRef< TemplateArgument > TemplateArgs, sema::TemplateDeductionInfo & DeductionInfo, SourceRange InstantiationRange = SourceRange())
Note that we are instantiating as part of template argument deduction for a variable template partial specialization.
Definition at line 699 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [9/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, ParmVarDecl * Param, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange = SourceRange())
Note that we are instantiating a default argument for a function parameter.
Definition at line 710 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [10/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, NamedDecl * Template, NonTypeTemplateParmDecl * Param, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange)
Note that we are substituting prior template arguments into a non-type parameter.
Definition at line 719 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [11/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, NamedDecl * Template, TemplateTemplateParmDecl * Param, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange)
Note that we are substituting prior template arguments into a template template parameter.
Definition at line 729 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [12/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, TemplateDecl * Template, NamedDecl * Param, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange)
Note that we are checking the default template argument against the template parameter for a given template-id.
Definition at line 748 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [13/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, ConstraintsCheck , NamedDecl * Template, ArrayRef< TemplateArgument > TemplateArgs, SourceRange InstantiationRange)
Note that we are checking the constraints associated with some constrained entity (a concept declaration or a template with associated constraints).
Definition at line 785 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [14/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, ConstraintSubstitution , NamedDecl * Template, sema::TemplateDeductionInfo & DeductionInfo, SourceRange InstantiationRange)
Note that we are checking a constraint expression associated with a template declaration or as part of the satisfaction check of a concept.
Definition at line 794 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [15/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, ConstraintNormalization , NamedDecl * Template, SourceRange InstantiationRange)
Note that we are normalizing a constraint expression.
Definition at line 803 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [16/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, ParameterMappingSubstitution , NamedDecl * Template, SourceRange InstantiationRange)
Note that we are subtituting into the parameter mapping of an atomic constraint during constraint normalization.
Definition at line 811 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [17/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, concepts::Requirement * Req, sema::TemplateDeductionInfo & DeductionInfo, SourceRange InstantiationRange = SourceRange())
Note that we are substituting template arguments into a part of a requirement of a requires expression.
Definition at line 757 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [18/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, concepts::NestedRequirement * Req, ConstraintsCheck , SourceRange InstantiationRange = SourceRange())
Note that we are checking the satisfaction of the constraint expression inside of a nested requirement.
Definition at line 767 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [19/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, const RequiresExpr * E, sema::TemplateDeductionInfo & DeductionInfo, SourceRange InstantiationRange)
Note that we are checking a requires clause.
Definition at line 776 of file SemaTemplateInstantiate.cpp.
InstantiatingTemplate() [20/20]
Sema::InstantiatingTemplate::InstantiatingTemplate (Sema & SemaRef, SourceLocation PointOfInstantiation, TemplateDecl * Entity, BuildingDeductionGuidesTag , SourceRange InstantiationRange = SourceRange())
Note that we are building deduction guides.
Definition at line 819 of file SemaTemplateInstantiate.cpp.
~InstantiatingTemplate()
clang::Sema::InstantiatingTemplate::~InstantiatingTemplate () inline
Definition at line 10332 of file Sema.h.
Member Function Documentation
Clear()
void Sema::InstantiatingTemplate::Clear ()
Note that we have finished instantiating this template.
Definition at line 871 of file SemaTemplateInstantiate.cpp.
References clang::atTemplateEnd(), clang::Sema::CodeSynthesisContexts, clang::Sema::InstantiatingSpecializations, clang::Sema::popCodeSynthesisContext(), clang::SemaBase::SemaRef, and clang::Sema::TemplateInstCallbacks.
isAlreadyInstantiating()
bool clang::Sema::InstantiatingTemplate::isAlreadyInstantiating () const inline
Determine whether we are already instantiating this specialization in some surrounding active instantiation.
Definition at line 10340 of file Sema.h.
Referenced by clang::Sema::InstantiateEnum(), clang::Sema::InstantiateExceptionSpec(), clang::Sema::InstantiateInClassInitializer(), clang::Sema::InstantiateVariableDefinition(), and clang::Sema::SubstDefaultArgument().
isInvalid()
bool clang::Sema::InstantiatingTemplate::isInvalid () const inline
Determines whether we have exceeded the maximum recursive template instantiations.
Definition at line 10336 of file Sema.h.
Referenced by clang::Sema::BuildVarTemplateInstantiation(), clang::Sema::CheckTemplateArgument(), clang::Sema::FinishTemplateArgumentDeduction(), clang::Sema::InstantiateEnum(), clang::Sema::InstantiateExceptionSpec(), clang::Sema::InstantiateFunctionDeclaration(), clang::Sema::InstantiateInClassInitializer(), clang::Sema::InstantiateVariableDefinition(), clang::Sema::SubstDefaultArgument(), SubstDefaultTemplateArgument(), and clang::Sema::SubstituteExplicitTemplateArguments().
The documentation for this struct was generated from the following files:
include/clang/Sema/Sema.h
lib/Sema/SemaTemplateInstantiate.cpp