clang: llvm::GraphTraits< clang::CallGraph * > Struct Reference
llvm::GraphTraits< clang::CallGraph * > Struct Reference
#include "clang/Analysis/CallGraph.h"
Public Types
using nodes_iterator = mapped_iterator< clang::CallGraph::iterator, decltype(&CGGetValue)>
Public Types inherited from llvm::GraphTraits< clang::CallGraphNode * >
using NodeType = clang::CallGraphNode
using NodeRef = clang::CallGraphNode *
using ChildIteratorType = NodeType::iterator
Static Public Member Functions
static NodeType * getEntryNode (clang::CallGraph *CGN)
static clang::CallGraphNode * CGGetValue (clang::CallGraph::const_iterator::value_type &P)
static nodes_iterator nodes_begin (clang::CallGraph *CG)
static nodes_iterator nodes_end (clang::CallGraph *CG)
static unsigned size (clang::CallGraph *CG)
Static Public Member Functions inherited from llvm::GraphTraits< clang::CallGraphNode * >
static NodeType * getEntryNode (clang::CallGraphNode *CGN)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
Detailed Description
Definition at line 279 of file CallGraph.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< clang::CallGraph * >::nodes_iterator = mapped_iterator<clang::CallGraph::iterator, decltype(&CGGetValue)>
Definition at line 291 of file CallGraph.h.
Member Function Documentation
CGGetValue()
static clang::CallGraphNode* llvm::GraphTraits< clang::CallGraph * >::CGGetValue (clang::CallGraph::const_iterator::value_type & P) inline static
Definition at line 286 of file CallGraph.h.
References P.
getEntryNode()
static NodeType* llvm::GraphTraits< clang::CallGraph * >::getEntryNode (clang::CallGraph * CGN) inline static
Definition at line 281 of file CallGraph.h.
References clang::CallGraph::getRoot().
nodes_begin()
static nodes_iterator llvm::GraphTraits< clang::CallGraph * >::nodes_begin (clang::CallGraph * CG) inline static
Definition at line 294 of file CallGraph.h.
References clang::CallGraph::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< clang::CallGraph * >::nodes_end (clang::CallGraph * CG) inline static
Definition at line 298 of file CallGraph.h.
References clang::CallGraph::end().
size()
static unsigned llvm::GraphTraits< clang::CallGraph * >::size (clang::CallGraph * CG) inline static
Definition at line 302 of file CallGraph.h.
References clang::CallGraph::size().
The documentation for this struct was generated from the following file:
include/clang/Analysis/CallGraph.h