clang: clang::ReturnAdjustment Struct Reference
clang::ReturnAdjustment Struct Reference
A return adjustment.
#include "clang/Basic/Thunk.h"
Classes
union VirtualAdjustment
Holds the ABI-specific information about the virtual return adjustment, if needed.
Public Member Functions
ReturnAdjustment ()
bool isEmpty () const
Public Attributes
int64_t NonVirtual
The non-virtual adjustment from the derived object to its nearest virtual base.
union clang::ReturnAdjustment::VirtualAdjustment Virtual
Friends
bool operator== (const ReturnAdjustment &LHS, const ReturnAdjustment &RHS)
bool operator!= (const ReturnAdjustment &LHS, const ReturnAdjustment &RHS)
bool operator< (const ReturnAdjustment &LHS, const ReturnAdjustment &RHS)
Detailed Description
A return adjustment.
Definition at line 26 of file Thunk.h.
Constructor & Destructor Documentation
ReturnAdjustment()
clang::ReturnAdjustment::ReturnAdjustment () inline
Definition at line 67 of file Thunk.h.
Member Function Documentation
isEmpty()
bool clang::ReturnAdjustment::isEmpty () const inline
Definition at line 69 of file Thunk.h.
References clang::ReturnAdjustment::VirtualAdjustment::isEmpty(), NonVirtual, and Virtual.
Referenced by dumpMicrosoftThunkAdjustment(), clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(), clang::CodeGen::CodeGenFunction::GenerateVarArgsThunk(), clang::ThunkInfo::isEmpty(), and setThunkProperties().
Friends And Related Function Documentation
operator!=
bool operator!= (const ReturnAdjustment & LHS, const ReturnAdjustment & RHS) friend
Definition at line 76 of file Thunk.h.
operator<
bool operator< (const ReturnAdjustment & LHS, const ReturnAdjustment & RHS) friend
Definition at line 81 of file Thunk.h.
operator==
bool operator== (const ReturnAdjustment & LHS, const ReturnAdjustment & RHS) friend
Definition at line 71 of file Thunk.h.
Member Data Documentation
NonVirtual
int64_t clang::ReturnAdjustment::NonVirtual
The non-virtual adjustment from the derived object to its nearest virtual base.
Definition at line 29 of file Thunk.h.
Referenced by dumpMicrosoftThunkAdjustment(), and isEmpty().
Virtual
union clang::ReturnAdjustment::VirtualAdjustment clang::ReturnAdjustment::Virtual
Referenced by dumpMicrosoftThunkAdjustment(), and isEmpty().
The documentation for this struct was generated from the following file:
include/clang/Basic/Thunk.h