clang: clang::CodeGen::CodeGenFunction::JumpDest Struct Reference
clang::CodeGen::CodeGenFunction::JumpDest Struct Reference
A jump destination is an abstract label, branching to which may require a jump out through normal cleanups.
#include "/home/runner/work/llvm/llvm/repo/clang/lib/CodeGen/CodeGenFunction.h"
Public Member Functions
JumpDest ()
JumpDest (llvm::BasicBlock *Block, EHScopeStack::stable_iterator Depth, unsigned Index)
bool isValid () const
llvm::BasicBlock * getBlock () const
EHScopeStack::stable_iterator getScopeDepth () const
unsigned getDestIndex () const
void setScopeDepth (EHScopeStack::stable_iterator depth)
Detailed Description
A jump destination is an abstract label, branching to which may require a jump out through normal cleanups.
Definition at line 239 of file CodeGenFunction.h.
Constructor & Destructor Documentation
JumpDest() [1/2]
clang::CodeGen::CodeGenFunction::JumpDest::JumpDest () inline
Definition at line 240 of file CodeGenFunction.h.
JumpDest() [2/2]
clang::CodeGen::CodeGenFunction::JumpDest::JumpDest (llvm::BasicBlock * Block, EHScopeStack::stable_iterator Depth, unsigned Index) inline
Definition at line 241 of file CodeGenFunction.h.
References clang::Block.
Member Function Documentation
getBlock()
llvm::BasicBlock* clang::CodeGen::CodeGenFunction::JumpDest::getBlock () const inline
Definition at line 246 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLabel(), clang::CodeGen::CodeGenFunction::EmitOMPLoopBody(), clang::CodeGen::CodeGenFunction::EmitReturnBlock(), clang::CodeGen::CodeGenFunction::EmitReturnValueCheck(), clang::CodeGen::CodeGenFunction::FinishFunction(), and clang::CodeGen::CodeGenFunction::GetAddrOfLabel().
getDestIndex()
unsigned clang::CodeGen::CodeGenFunction::JumpDest::getDestIndex () const inline
Definition at line 248 of file CodeGenFunction.h.
getScopeDepth()
EHScopeStack::stable_iterator clang::CodeGen::CodeGenFunction::JumpDest::getScopeDepth () const inline
Definition at line 247 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitBranchThroughCleanup(), clang::CodeGen::CodeGenFunction::EmitLabel(), clang::CodeGen::CodeGenFunction::isObviouslyBranchWithoutCleanups(), and clang::CodeGen::CodeGenFunction::LexicalScope::rescopeLabels().
isValid()
bool clang::CodeGen::CodeGenFunction::JumpDest::isValid () const inline
Definition at line 245 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLabel(), clang::CodeGen::CodeGenFunction::EmitReturnValueCheck(), clang::CodeGen::CodeGenFunction::FinishFunction(), and clang::CodeGen::CodeGenFunction::getJumpDestForLabel().
setScopeDepth()
void clang::CodeGen::CodeGenFunction::JumpDest::setScopeDepth (EHScopeStack::stable_iterator depth) inline
Definition at line 251 of file CodeGenFunction.h.
Referenced by clang::CodeGen::CodeGenFunction::EmitLabel(), and clang::CodeGen::CodeGenFunction::LexicalScope::rescopeLabels().
The documentation for this struct was generated from the following file:
lib/CodeGen/CodeGenFunction.h