clang: clang::extractapi::TypedefUnderlyingTypeResolver Struct Reference
clang::extractapi::TypedefUnderlyingTypeResolver Struct Reference
#include "clang/ExtractAPI/TypedefUnderlyingTypeResolver.h"
Public Member Functions
const NamedDecl * getUnderlyingTypeDecl (QualType Type) const
Gets the underlying type declaration.
SymbolReference getSymbolReferenceForType (QualType Type, APISet &API) const
Get a SymbolReference for the given type.
std::string getUSRForType (QualType Type) const
Get a USR for the given type.
TypedefUnderlyingTypeResolver (ASTContext &Context)
Detailed Description
Definition at line 28 of file TypedefUnderlyingTypeResolver.h.
Constructor & Destructor Documentation
TypedefUnderlyingTypeResolver()
clang::extractapi::TypedefUnderlyingTypeResolver::TypedefUnderlyingTypeResolver (ASTContext & Context) inline explicit
Definition at line 38 of file TypedefUnderlyingTypeResolver.h.
Member Function Documentation
getSymbolReferenceForType()
SymbolReference TypedefUnderlyingTypeResolver::getSymbolReferenceForType (QualType Type, APISet & API) const
Get a SymbolReference for the given type.
Definition at line 48 of file TypedefUnderlyingTypeResolver.cpp.
References clang::extractapi::APISet::createSymbolReference(), clang::index::generateUSRForDecl(), clang::index::generateUSRForType(), clang::Type::getAs(), clang::Decl::getImportedOwningModule(), clang::NamedDecl::getName(), getUnderlyingTypeDecl(), and clang::TypeName.
getUnderlyingTypeDecl()
const NamedDecl * TypedefUnderlyingTypeResolver::getUnderlyingTypeDecl (QualType Type) const
Gets the underlying type declaration.
Definition at line 22 of file TypedefUnderlyingTypeResolver.cpp.
References clang::Type::getAs(), clang::TypedefType::getDecl(), clang::TypedefNameDecl::getUnderlyingType(), and clang::Type::isTypedefNameType().
Referenced by getSymbolReferenceForType(), and getUSRForType().
getUSRForType()
std::string TypedefUnderlyingTypeResolver::getUSRForType (QualType Type) const
Get a USR for the given type.
Definition at line 70 of file TypedefUnderlyingTypeResolver.cpp.
References clang::index::generateUSRForDecl(), clang::index::generateUSRForType(), and getUnderlyingTypeDecl().
The documentation for this struct was generated from the following files:
include/clang/ExtractAPI/TypedefUnderlyingTypeResolver.h
lib/ExtractAPI/TypedefUnderlyingTypeResolver.cpp