clang: clang::OpenCLOptions::OpenCLOptionInfo Struct Reference
clang::OpenCLOptions::OpenCLOptionInfo Struct Reference
#include "clang/Basic/OpenCLOptions.h"
Public Member Functions
OpenCLOptionInfo ()=default
OpenCLOptionInfo (bool Pragma, unsigned AvailV, unsigned CoreV, unsigned OptV)
bool isCore () const
bool isOptionalCore () const
bool isAvailableIn (const LangOptions &LO) const
bool isCoreIn (const LangOptions &LO) const
bool isOptionalCoreIn (const LangOptions &LO) const
Public Attributes
bool WithPragma = false
unsigned Avail = 100U
unsigned Core = 0U
unsigned Opt = 0U
bool Supported = false
bool Enabled = false
Detailed Description
Definition at line 87 of file OpenCLOptions.h.
Constructor & Destructor Documentation
OpenCLOptionInfo() [1/2]
clang::OpenCLOptions::OpenCLOptionInfo::OpenCLOptionInfo () default
OpenCLOptionInfo() [2/2]
clang::OpenCLOptions::OpenCLOptionInfo::OpenCLOptionInfo (bool Pragma, unsigned AvailV, unsigned CoreV, unsigned OptV) inline
Definition at line 107 of file OpenCLOptions.h.
References clang::Pragma.
Member Function Documentation
isAvailableIn()
bool clang::OpenCLOptions::OpenCLOptionInfo::isAvailableIn (const LangOptions & LO) const inline
Definition at line 116 of file OpenCLOptions.h.
References Avail, and clang::LangOptions::getOpenCLCompatibleVersion().
Referenced by isCoreIn(), clang::OpenCLOptions::isOpenCLOptionAvailableIn(), and isOptionalCoreIn().
isCore()
bool clang::OpenCLOptions::OpenCLOptionInfo::isCore () const inline
Definition at line 111 of file OpenCLOptions.h.
References Core.
isCoreIn()
bool clang::OpenCLOptions::OpenCLOptionInfo::isCoreIn (const LangOptions & LO) const inline
Definition at line 122 of file OpenCLOptions.h.
References Core, and isAvailableIn().
Referenced by clang::OpenCLOptions::isOpenCLOptionCoreIn().
isOptionalCore()
bool clang::OpenCLOptions::OpenCLOptionInfo::isOptionalCore () const inline
Definition at line 113 of file OpenCLOptions.h.
References Opt.
isOptionalCoreIn()
bool clang::OpenCLOptions::OpenCLOptionInfo::isOptionalCoreIn (const LangOptions & LO) const inline
Definition at line 127 of file OpenCLOptions.h.
References isAvailableIn(), and Opt.
Member Data Documentation
Avail
unsigned clang::OpenCLOptions::OpenCLOptionInfo::Avail = 100U
Definition at line 92 of file OpenCLOptions.h.
Referenced by isAvailableIn().
Core
unsigned clang::OpenCLOptions::OpenCLOptionInfo::Core = 0U
Definition at line 95 of file OpenCLOptions.h.
Referenced by isCore(), and isCoreIn().
Enabled
bool clang::OpenCLOptions::OpenCLOptionInfo::Enabled = false
Definition at line 104 of file OpenCLOptions.h.
Opt
unsigned clang::OpenCLOptions::OpenCLOptionInfo::Opt = 0U
Definition at line 98 of file OpenCLOptions.h.
Referenced by isOptionalCore(), and isOptionalCoreIn().
Supported
bool clang::OpenCLOptions::OpenCLOptionInfo::Supported = false
Definition at line 101 of file OpenCLOptions.h.
WithPragma
bool clang::OpenCLOptions::OpenCLOptionInfo::WithPragma = false
Definition at line 89 of file OpenCLOptions.h.
The documentation for this struct was generated from the following file:
include/clang/Basic/OpenCLOptions.h