clang: lib/Driver/ToolChains/SYCL.cpp File Reference
SYCL.cpp File Reference
#include "SYCL.h"
#include "CommonArgs.h"
#include "clang/Driver/Action.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Options.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include <algorithm>
#include <sstream>
Functions
static void addFPGATimingDiagnostic (std::unique_ptr< Command > &Cmd, Compilation &C)
static bool selectBfloatLibs (const llvm::Triple &Triple, const Compilation &C, bool &UseNative)
static const char * makeExeName (Compilation &C, StringRef Name)
static std::vector< OptSpecifier > getUnsupportedOpts (void)
static void parseTargetOpts (StringRef ArgString, const llvm::opt::ArgList &Args, llvm::opt::ArgStringList &CmdArgs)
static void WarnForDeprecatedBackendOpts (const Driver &D, const llvm::Triple &Triple, StringRef Device, StringRef ArgString, const llvm::opt::Arg *A)
Variables
static llvm::SmallVector< StringRef, 16 > SYCLDeviceLibList
static llvm::StringMap< StringRef > GRFModeFlagMap
Function Documentation
addFPGATimingDiagnostic()
static void addFPGATimingDiagnostic (std::unique_ptr< Command > & Cmd, Compilation & C) static
Definition at line 54 of file SYCL.cpp.
References Cmd.
Referenced by clang::driver::tools::SYCL::fpga::BackendCompiler::ConstructJob(), and clang::driver::tools::SYCL::constructLLVMForeachCommand().
getUnsupportedOpts()
static std::vector<OptSpecifier> getUnsupportedOpts (void) static
Definition at line 1132 of file SYCL.cpp.
Referenced by clang::driver::toolchains::SYCLToolChain::SYCLToolChain(), and clang::driver::toolchains::SYCLToolChain::TranslateArgs().
makeExeName()
static const char* makeExeName (Compilation & C, StringRef Name) static
Definition at line 627 of file SYCL.cpp.
Referenced by clang::driver::tools::SYCL::fpga::BackendCompiler::ConstructJob(), clang::driver::tools::SYCL::gen::BackendCompiler::ConstructJob(), and clang::driver::tools::SYCL::x86_64::BackendCompiler::ConstructJob().
parseTargetOpts()
static void parseTargetOpts (StringRef ArgString, const llvm::opt::ArgList & Args, llvm::opt::ArgStringList & CmdArgs) static
Definition at line 1241 of file SYCL.cpp.
Referenced by clang::driver::toolchains::SYCLToolChain::TranslateBackendTargetArgs(), and clang::driver::toolchains::SYCLToolChain::TranslateTargetOpt().
selectBfloatLibs()
static bool selectBfloatLibs (const llvm::Triple & Triple, const Compilation & C, bool & UseNative) static
Definition at line 160 of file SYCL.cpp.
References clang::Device, clang::driver::Action::OFK_SYCL, and clang::driver::toolchains::SYCLToolChain::TranslateBackendTargetArgs().
Referenced by clang::driver::tools::SYCL::getDeviceLibraries().
WarnForDeprecatedBackendOpts()
static void WarnForDeprecatedBackendOpts (const Driver & D, const llvm::Triple & Triple, StringRef Device, StringRef ArgString, const llvm::opt::Arg * A) static
Definition at line 1271 of file SYCL.cpp.
References clang::Device, clang::driver::Driver::Diag(), and GRFModeFlagMap.
Referenced by clang::driver::toolchains::SYCLToolChain::TranslateBackendTargetArgs(), and clang::driver::toolchains::SYCLToolChain::TranslateTargetOpt().
Variable Documentation
GRFModeFlagMap
llvm::StringMap<StringRef> GRFModeFlagMap static
Initial value:
{
    {"auto", "-ze-intel-enable-auto-large-GRF-mode"},
    {"small", "-ze-intel-128-GRF-per-thread"},
    {"large", "-ze-opt-large-register-file"}}
Definition at line 852 of file SYCL.cpp.
Referenced by clang::driver::tools::SYCL::gen::getGenGRFFlag(), and WarnForDeprecatedBackendOpts().
SYCLDeviceLibList
llvm::SmallVector<StringRef, 16> SYCLDeviceLibList static
Initial value:
{
    "bfloat16",
    "crt",
    "cmath",
    "cmath-fp64",
    "complex",
    "complex-fp64",
    "sanitizer",
    "imf",
    "imf-fp64",
    "imf-bf16",
    "itt-compiler-wrappers",
    "itt-stubs",
    "itt-user-wrappers",
    "fallback-cassert",
    "fallback-cstring",
    "fallback-cmath",
    "fallback-cmath-fp64",
    "fallback-complex",
    "fallback-complex-fp64",
    "fallback-imf",
    "fallback-imf-fp64",
    "fallback-imf-bf16",
    "fallback-bfloat16",
    "native-bfloat16"}
Definition at line 372 of file SYCL.cpp.