clang: lib/AST/TextNodeDumper.cpp File Reference
TextNodeDumper.cpp File Reference
#include "clang/AST/TextNodeDumper.h"
#include "clang/AST/APValue.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/LocInfoType.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLocVisitor.h"
#include "clang/Basic/Module.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Basic/TypeTraits.h"
#include "llvm/ADT/StringExtras.h"
#include <algorithm>
#include <utility>
#include "clang/AST/DeclNodes.inc"
#include "clang/Basic/AttrList.inc"
#include "clang/Basic/FPOptions.def"
#include "clang/Basic/TransformTypeTraits.def"
Macros
#define DECL(DERIVED, BASE)
#define ABSTRACT_DECL(DECL)
#define ATTR(X)
#define OPTION(NAME, TYPE, WIDTH, PREVIOUS)
#define TRANSFORM_TYPE_TRAIT_DEF(Enum, Trait)
#define FLAG(fn, name)
Functions
static void dumpPreviousDeclImpl (raw_ostream &OS,...)
template<typename T >
static void dumpPreviousDeclImpl (raw_ostream &OS, const Mergeable< T > *D)
template<typename T >
static void dumpPreviousDeclImpl (raw_ostream &OS, const Redeclarable< T > *D)
static void dumpPreviousDecl (raw_ostream &OS, const Decl *D)
Dump the previous declaration in the redeclaration chain for a declaration, if any.
static double GetApproxValue (const llvm::APFloat &F)
static bool isSimpleAPValue (const APValue &Value)
True if the APValue Value can be folded onto the current line.
static void dumpBasePath (raw_ostream &OS, const CastExpr *Node)
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (DECL)
ATTR
#define ATTR (X)
Value:
  case attr::X:                                                                \
    OS << #X;                                                                  \
    break;
DECL
#define DECL (DERIVED, BASE)
Value:
  case Decl::DERIVED:                                                          \
    return dumpPreviousDeclImpl(OS, cast<DERIVED##Decl>(D));
FLAG
#define FLAG (fn, name)
Value:
  if (D->fn())                                                                 \
    OS << " " #name;
OPTION
#define OPTION (NAME, TYPE, WIDTH, PREVIOUS)
Value:
  if (FPO.has##NAME##Override())                                               \
    OS << " " #NAME "=" << FPO.get##NAME##Override();
TRANSFORM_TYPE_TRAIT_DEF
#define TRANSFORM_TYPE_TRAIT_DEF (Enum, Trait)
Value:
  case UnaryTransformType::Enum:                                               \
    OS << " " #Trait;                                                          \
    break;
Function Documentation
dumpBasePath()
static void dumpBasePath (raw_ostream & OS, const CastExpr * Node) static
Definition at line 1075 of file TextNodeDumper.cpp.
References clang::First, clang::RecordType::getDecl(), and Node.
Referenced by clang::TextNodeDumper::VisitCastExpr(), and clang::TextNodeDumper::VisitCXXNamedCastExpr().
dumpPreviousDecl()
static void dumpPreviousDecl (raw_ostream & OS, const Decl * D) static
Dump the previous declaration in the redeclaration chain for a declaration, if any.
Definition at line 51 of file TextNodeDumper.cpp.
References clang::Decl::getKind().
Referenced by clang::TextNodeDumper::Visit().
dumpPreviousDeclImpl() [1/3]
template<typename T > static void dumpPreviousDeclImpl (raw_ostream & OS, const Mergeable< T > * D) static
Definition at line 36 of file TextNodeDumper.cpp.
References clang::First, clang::Mergeable< decl_type >::getFirstDecl(), and clang::T.
dumpPreviousDeclImpl() [2/3]
template<typename T > static void dumpPreviousDeclImpl (raw_ostream & OS, const Redeclarable< T > * D) static
Definition at line 43 of file TextNodeDumper.cpp.
References clang::Redeclarable< decl_type >::getPreviousDecl(), and clang::T.
dumpPreviousDeclImpl() [3/3]
static void dumpPreviousDeclImpl (raw_ostream & OS, ...) static
Definition at line 33 of file TextNodeDumper.cpp.
GetApproxValue()
static double GetApproxValue (const llvm::APFloat & F) static
Definition at line 485 of file TextNodeDumper.cpp.
References V.
Referenced by clang::TextNodeDumper::Visit().
isSimpleAPValue()
static bool isSimpleAPValue (const APValue & Value) static
True if the APValue Value can be folded onto the current line.
Definition at line 494 of file TextNodeDumper.cpp.
References clang::APValue::AddrLabelDiff, clang::APValue::Array, clang::APValue::ComplexFloat, clang::APValue::ComplexInt, clang::APValue::FixedPoint, clang::APValue::Float, clang::Value::getKind(), clang::APValue::Indeterminate, clang::APValue::Int, clang::APValue::LValue, clang::APValue::MemberPointer, clang::APValue::None, clang::APValue::Struct, clang::APValue::Union, and clang::APValue::Vector.