clang: lib/Analysis/ThreadSafety.cpp File Reference
ThreadSafety.cpp File Reference
#include "clang/Analysis/Analyses/ThreadSafety.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclGroup.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/OperationKinds.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/AST/Type.h"
#include "clang/Analysis/Analyses/PostOrderCFGView.h"
#include "clang/Analysis/Analyses/ThreadSafetyCommon.h"
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
#include "clang/Analysis/Analyses/ThreadSafetyTraverse.h"
#include "clang/Analysis/Analyses/ThreadSafetyUtil.h"
#include "clang/Analysis/AnalysisDeclContext.h"
#include "clang/Analysis/CFG.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/OperatorKinds.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/Specifiers.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/ImmutableMap.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <functional>
#include <iterator>
#include <memory>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
Classes
class clang::threadSafety::BeforeSet
Namespaces
clang
clang::threadSafety
Functions
static void warnInvalidLock (ThreadSafetyHandler &Handler, const Expr *MutexExp, const NamedDecl *D, const Expr *DeclExp, StringRef Kind)
Issue a warning about an invalid lock expression.
static void findBlockLocations (CFG *CFGraph, const PostOrderCFGView *SortedGraph, std::vector< CFGBlockInfo > &BlockInfo)
Find the appropriate source locations to use when producing diagnostics for each block in the CFG.
static const ValueDecl * getValueDecl (const Expr *Exp)
Gets the value decl pointer from DeclRefExprs or MemberExprs.
static StringRef ClassifyDiagnostic (const CapabilityAttr *A)
static StringRef ClassifyDiagnostic (QualType VDT)
static StringRef ClassifyDiagnostic (const ValueDecl *VD)
template<typename AttrTy >
static std::enable_if_t<!has_arg_iterator_range< AttrTy >::value, StringRef > ClassifyDiagnostic (const AttrTy *A)
template<typename AttrTy >
static std::enable_if_t< has_arg_iterator_range< AttrTy >::value, StringRef > ClassifyDiagnostic (const AttrTy *A)
static bool getStaticBooleanValue (Expr *E, bool &TCond)
static CXXConstructorDecl * findConstructorForByValueReturn (const CXXRecordDecl *RD)
static Expr * buildFakeCtorCall (CXXConstructorDecl *CD, ArrayRef< Expr * > Args, SourceLocation Loc)
static bool neverReturns (const CFGBlock *B)
Function Documentation
buildFakeCtorCall()
static Expr* buildFakeCtorCall (CXXConstructorDecl * CD, ArrayRef< Expr * > Args, SourceLocation Loc) static
Definition at line 2137 of file ThreadSafety.cpp.
References clang::CXXConstructExpr::CK_Complete, clang::CXXConstructExpr::Create(), clang::Decl::getASTContext(), clang::CXXMethodDecl::getParent(), and clang::ASTContext::getRecordType().
ClassifyDiagnostic() [1/5]
template<typename AttrTy > static std::enable_if_t<!has_arg_iterator_range<AttrTy>::value, StringRef> ClassifyDiagnostic (const AttrTy * A) static
Definition at line 1253 of file ThreadSafety.cpp.
References ClassifyDiagnostic(), and getValueDecl().
ClassifyDiagnostic() [2/5]
template<typename AttrTy > static std::enable_if_t<has_arg_iterator_range<AttrTy>::value, StringRef> ClassifyDiagnostic (const AttrTy * A) static
Definition at line 1261 of file ThreadSafety.cpp.
References ClassifyDiagnostic(), and getValueDecl().
ClassifyDiagnostic() [3/5]
static StringRef ClassifyDiagnostic (const CapabilityAttr * A) static
Definition at line 1222 of file ThreadSafety.cpp.
Referenced by ClassifyDiagnostic().
ClassifyDiagnostic() [4/5]
static StringRef ClassifyDiagnostic (const ValueDecl * VD) static
Definition at line 1244 of file ThreadSafety.cpp.
References ClassifyDiagnostic(), and clang::ValueDecl::getType().
ClassifyDiagnostic() [5/5]
static StringRef ClassifyDiagnostic (QualType VDT) static
Definition at line 1226 of file ThreadSafety.cpp.
References ClassifyDiagnostic(), clang::Type::getAs(), clang::Type::getPointeeType(), clang::Type::isPointerType(), and clang::Type::isReferenceType().
findBlockLocations()
static void findBlockLocations (CFG * CFGraph, const PostOrderCFGView * SortedGraph, std::vector< CFGBlockInfo > & BlockInfo) static
Find the appropriate source locations to use when producing diagnostics for each block in the CFG.
Definition at line 810 of file ThreadSafety.cpp.
findConstructorForByValueReturn()
static CXXConstructorDecl* findConstructorForByValueReturn (const CXXRecordDecl * RD) static
Definition at line 2120 of file ThreadSafety.cpp.
References clang::CXXRecordDecl::ctors(), and clang::CXXConstructorDecl::isCopyConstructor().
getStaticBooleanValue()
static bool getStaticBooleanValue (Expr * E, bool & TCond) static
Definition at line 1423 of file ThreadSafety.cpp.
getValueDecl()
static const ValueDecl* getValueDecl (const Expr * Exp) static
Gets the value decl pointer from DeclRefExprs or MemberExprs.
Definition at line 1190 of file ThreadSafety.cpp.
Referenced by ClassifyDiagnostic().
neverReturns()
static bool neverReturns (const CFGBlock * B) static
Definition at line 2268 of file ThreadSafety.cpp.
References clang::CFGBlock::back(), clang::CFGBlock::empty(), clang::CFGBlock::hasNoReturnElement(), and clang::Last.
warnInvalidLock()
static void warnInvalidLock (ThreadSafetyHandler & Handler, const Expr * MutexExp, const NamedDecl * D, const Expr * DeclExp, StringRef Kind) static
Issue a warning about an invalid lock expression.
Definition at line 69 of file ThreadSafety.cpp.
References clang::Expr::getExprLoc(), clang::threadSafety::ThreadSafetyHandler::handleInvalidLockExp(), and clang::SourceLocation::isValid().