clang: lib/Analysis/ThreadSafetyCommon.cpp File Reference
ThreadSafetyCommon.cpp File Reference
#include "clang/Analysis/Analyses/ThreadSafetyCommon.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclGroup.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/OperationKinds.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/Type.h"
#include "clang/Analysis/Analyses/ThreadSafetyTIL.h"
#include "clang/Analysis/CFG.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/OperatorKinds.h"
#include "clang/Basic/Specifiers.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Casting.h"
#include <algorithm>
#include <cassert>
#include <string>
#include <utility>
Namespaces
clang
The JSON file list parser is used to communicate input to InstallAPI.
clang::threadSafety
Typedefs
using CallingContext = SExprBuilder::CallingContext
Functions
static bool isIncompletePhi (const til::SExpr *E)
static bool isCalleeArrow (const Expr *E)
static StringRef ClassifyDiagnostic (const CapabilityAttr *A)
static StringRef ClassifyDiagnostic (QualType VDT)
static const ValueDecl * getValueDeclFromSExpr (const til::SExpr *E)
static bool hasAnyPointerType (const til::SExpr *E)
static const CXXMethodDecl * getFirstVirtualDecl (const CXXMethodDecl *D)
static void maybeUpdateVD (til::SExpr *E, const ValueDecl *VD)
void clang::threadSafety::printSCFG (CFGWalker &Walker)
Typedef Documentation
CallingContext
using CallingContext = SExprBuilder::CallingContext
Definition at line 70 of file ThreadSafetyCommon.cpp.
Function Documentation
ClassifyDiagnostic() [1/2]
static StringRef ClassifyDiagnostic (const CapabilityAttr * A) static
Definition at line 84 of file ThreadSafetyCommon.cpp.
Referenced by ClassifyDiagnostic(), clang::threadSafety::SExprBuilder::createThisPlaceholder(), and clang::threadSafety::SExprBuilder::translateAttrExpr().
ClassifyDiagnostic() [2/2]
static StringRef ClassifyDiagnostic (QualType VDT) static
Definition at line 88 of file ThreadSafetyCommon.cpp.
References ClassifyDiagnostic(), clang::Type::getAs(), clang::Type::getPointeeType(), clang::Type::isPointerType(), and clang::Type::isReferenceType().
getFirstVirtualDecl()
static const CXXMethodDecl* getFirstVirtualDecl (const CXXMethodDecl * D) static
Definition at line 379 of file ThreadSafetyCommon.cpp.
References clang::CXXMethodDecl::getCanonicalDecl().
getValueDeclFromSExpr()
static const ValueDecl* getValueDeclFromSExpr (const til::SExpr * E) static
Definition at line 356 of file ThreadSafetyCommon.cpp.
References P, and V.
Referenced by hasAnyPointerType().
hasAnyPointerType()
static bool hasAnyPointerType (const til::SExpr * E) static
Definition at line 368 of file ThreadSafetyCommon.cpp.
References clang::threadSafety::til::CAST_objToPtr, and getValueDeclFromSExpr().
isCalleeArrow()
static bool isCalleeArrow (const Expr * E) static
Definition at line 79 of file ThreadSafetyCommon.cpp.
References clang::Expr::IgnoreParenCasts().
Referenced by clang::threadSafety::SExprBuilder::translateAttrExpr().
isIncompletePhi()
static bool isIncompletePhi (const til::SExpr * E) static
Definition at line 64 of file ThreadSafetyCommon.cpp.
References clang::threadSafety::til::Phi::PH_Incomplete.
maybeUpdateVD()
static void maybeUpdateVD (til::SExpr * E, const ValueDecl * VD) static
Definition at line 704 of file ThreadSafetyCommon.cpp.
References V.