clang: lib/Driver/ToolChain.cpp File Reference
ToolChain.cpp File Reference
#include "clang/Driver/ToolChain.h"
#include "ToolChains/Arch/AArch64.h"
#include "ToolChains/Arch/ARM.h"
#include "ToolChains/Clang.h"
#include "ToolChains/CommonArgs.h"
#include "ToolChains/Flang.h"
#include "ToolChains/InterfaceStubs.h"
#include "clang/Basic/ObjCRuntime.h"
#include "clang/Basic/Sanitizers.h"
#include "clang/Config/config.h"
#include "clang/Driver/Action.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/InputInfo.h"
#include "clang/Driver/Job.h"
#include "clang/Driver/Options.h"
#include "clang/Driver/SanitizerArgs.h"
#include "clang/Driver/XRayArgs.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/OptTable.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VersionTuple.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/TargetParser/AArch64TargetParser.h"
#include "llvm/TargetParser/TargetParser.h"
#include "llvm/TargetParser/Triple.h"
#include <cassert>
#include <cstddef>
#include <cstring>
#include <string>
#include "llvm/TargetParser/ARMTargetParser.def"
Macros
#define ARM_FPU(NAME, KIND, VERSION, NEON_SUPPORT, RESTRICTION)
Functions
static llvm::opt::Arg * GetRTTIArgument (const ArgList &Args)
static ToolChain::RTTIMode CalculateRTTIMode (const ArgList &Args, const llvm::Triple &Triple, const Arg *CachedRTTIArg)
static ToolChain::ExceptionsMode CalculateExceptionsMode (const ArgList &Args)
static void getAArch64MultilibFlags (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, Multilib::flags_list &Result)
static void getARMMultilibFlags (const Driver &D, const llvm::Triple &Triple, const llvm::opt::ArgList &Args, Multilib::flags_list &Result)
static const DriverSuffix * FindDriverSuffix (StringRef ProgName, size_t &Pos)
static std::string normalizeProgramName (llvm::StringRef Argv0)
Normalize the program name from argv[0] by stripping the file extension if present and lower-casing the string on Windows.
static const DriverSuffix * parseDriverSuffix (StringRef ProgName, size_t &Pos)
static StringRef getArchNameForCompilerRTLib (const ToolChain &TC, const ArgList &Args)
static VersionTuple separateMSVCFullVersion (unsigned Version)
Macro Definition Documentation
ARM_FPU
#define ARM_FPU (NAME, KIND, VERSION, NEON_SUPPORT, RESTRICTION)
Value:
  case llvm::ARM::KIND:                                                        \
    Result.push_back("-mfpu=" NAME);                                           \
    break;
Function Documentation
CalculateExceptionsMode()
static ToolChain::ExceptionsMode CalculateExceptionsMode (const ArgList & Args) static
Definition at line 81 of file ToolChain.cpp.
References clang::driver::ToolChain::EM_Disabled, and clang::driver::ToolChain::EM_Enabled.
CalculateRTTIMode()
static ToolChain::RTTIMode CalculateRTTIMode (const ArgList & Args, const llvm::Triple & Triple, const Arg * CachedRTTIArg) static
Definition at line 65 of file ToolChain.cpp.
References clang::driver::ToolChain::RM_Disabled, and clang::driver::ToolChain::RM_Enabled.
FindDriverSuffix()
static const DriverSuffix* FindDriverSuffix (StringRef ProgName, size_t & Pos) static
Definition at line 322 of file ToolChain.cpp.
Referenced by parseDriverSuffix().
getAArch64MultilibFlags()
static void getAArch64MultilibFlags (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, Multilib::flags_list & Result) static
Definition at line 188 of file ToolChain.cpp.
References clang::driver::tools::aarch64::getAArch64TargetFeatures(), and clang::driver::tools::unifyTargetFeatures().
Referenced by clang::driver::ToolChain::getMultilibFlags().
getArchNameForCompilerRTLib()
static StringRef getArchNameForCompilerRTLib (const ToolChain & TC, const ArgList & Args) static
Definition at line 652 of file ToolChain.cpp.
References clang::driver::ToolChain::getArch(), clang::driver::tools::arm::getARMFloatABI(), clang::driver::ToolChain::getTriple(), and clang::driver::ToolChain::isBareMetal().
Referenced by clang::driver::ToolChain::buildCompilerRTBasename().
getARMMultilibFlags()
static void getARMMultilibFlags (const Driver & D, const llvm::Triple & Triple, const llvm::opt::ArgList & Args, Multilib::flags_list & Result) static
Definition at line 213 of file ToolChain.cpp.
References clang::driver::tools::arm::getARMFloatABI(), clang::driver::tools::arm::getARMTargetFeatures(), and clang::driver::tools::unifyTargetFeatures().
Referenced by clang::driver::ToolChain::getMultilibFlags().
GetRTTIArgument()
static llvm::opt::Arg* GetRTTIArgument (const ArgList & Args) static
Definition at line 60 of file ToolChain.cpp.
normalizeProgramName()
static std::string normalizeProgramName (llvm::StringRef Argv0) static
Normalize the program name from argv[0] by stripping the file extension if present and lower-casing the string on Windows.
Definition at line 355 of file ToolChain.cpp.
Referenced by clang::driver::ToolChain::getTargetAndModeFromProgramName().
parseDriverSuffix()
static const DriverSuffix* parseDriverSuffix (StringRef ProgName, size_t & Pos) static
Definition at line 365 of file ToolChain.cpp.
References FindDriverSuffix().
Referenced by clang::driver::ToolChain::getTargetAndModeFromProgramName().
separateMSVCFullVersion()
static VersionTuple separateMSVCFullVersion (unsigned Version) static
Definition at line 1463 of file ToolChain.cpp.
Referenced by clang::driver::ToolChain::computeMSVCVersion().