clang: lib/Driver/Types.cpp File Reference
Types.cpp File Reference
#include "clang/Driver/Types.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Option/Arg.h"
#include <cassert>
#include <cstring>
#include "clang/Driver/Types.def"
Classes
struct TypeInfo
class TypeInfo::PhasesBitSet
Macros
#define TYPE(NAME, ID, PP_TYPE, TEMP_SUFFIX, ...) { NAME, TEMP_SUFFIX, TY_##PP_TYPE, { __VA_ARGS__ }, },
Functions
static const TypeInfo & getInfo (unsigned id)
static bool isPreprocessedModuleType (ID Id)
static bool isPreprocessedHeaderUnitType (ID Id)
Variables
static constexpr TypeInfo TypeInfos []
static const unsigned numTypes = std::size(TypeInfos)
Macro Definition Documentation
TYPE
#define TYPE (NAME, ID, PP_TYPE, TEMP_SUFFIX, ...) { NAME, TEMP_SUFFIX, TY_##PP_TYPE, { __VA_ARGS__ }, },
Function Documentation
getInfo()
static const TypeInfo& getInfo (unsigned id) static
Definition at line 47 of file Types.cpp.
References numTypes, and TypeInfos.
Referenced by clang::driver::types::getCompilationPhases(), clang::CodeGen::LoopInfoStack::getCurLoopID(), clang::CodeGen::LoopInfoStack::getCurLoopParallel(), clang::driver::types::getPreprocessedType(), clang::driver::types::getTypeName(), clang::driver::types::getTypeTempSuffix(), and clang::driver::types::onlyPrecompileType().
isPreprocessedHeaderUnitType()
static bool isPreprocessedHeaderUnitType (ID Id) static
Definition at line 68 of file Types.cpp.
References Id.
Referenced by clang::driver::types::getPrecompiledType().
isPreprocessedModuleType()
static bool isPreprocessedModuleType (ID Id) static
Definition at line 64 of file Types.cpp.
References Id.
Referenced by clang::driver::types::getPrecompiledType(), and clang::driver::types::onlyPrecompileType().
Variable Documentation
numTypes
const unsigned numTypes = std::size(TypeInfos) static
Definition at line 45 of file Types.cpp.
Referenced by getInfo().
TypeInfos
constexpr TypeInfo TypeInfos[] static constexpr
Initial value:
= {
#define TYPE(NAME, ID, PP_TYPE, TEMP_SUFFIX, ...)
}
Definition at line 39 of file Types.cpp.
Referenced by getInfo().