clang: clang::ReturnAdjustment::VirtualAdjustment Union Reference
clang::ReturnAdjustment::VirtualAdjustment Union Reference
Holds the ABI-specific information about the virtual return adjustment, if needed.
#include "clang/Basic/Thunk.h"
Public Member Functions
VirtualAdjustment ()
bool Equals (const VirtualAdjustment &Other) const
bool isEmpty () const
bool Less (const VirtualAdjustment &RHS) const
Public Attributes
struct {
int64_t VBaseOffsetOffset
The offset (in bytes), relative to the address point of the virtual base class offset.
} Itanium
struct {
uint32_t VBPtrOffset
The offset (in bytes) of the vbptr, relative to the beginning of the derived class.
uint32_t VBIndex
Index of the virtual base in the vbtable.
} Microsoft
Detailed Description
Holds the ABI-specific information about the virtual return adjustment, if needed.
Definition at line 33 of file Thunk.h.
Constructor & Destructor Documentation
VirtualAdjustment()
clang::ReturnAdjustment::VirtualAdjustment::VirtualAdjustment () inline
Definition at line 51 of file Thunk.h.
References memset().
Member Function Documentation
Equals()
bool clang::ReturnAdjustment::VirtualAdjustment::Equals (const VirtualAdjustment & Other) const inline
Definition at line 53 of file Thunk.h.
Referenced by isEmpty().
isEmpty()
bool clang::ReturnAdjustment::VirtualAdjustment::isEmpty () const inline
Definition at line 57 of file Thunk.h.
References Equals(), and clang::interp::Zero().
Referenced by clang::ReturnAdjustment::isEmpty().
Less()
bool clang::ReturnAdjustment::VirtualAdjustment::Less (const VirtualAdjustment & RHS) const inline
Definition at line 62 of file Thunk.h.
Member Data Documentation
Itanium
struct { ... } clang::ReturnAdjustment::VirtualAdjustment::Itanium
Microsoft
struct { ... } clang::ReturnAdjustment::VirtualAdjustment::Microsoft
Referenced by dumpMicrosoftThunkAdjustment().
VBaseOffsetOffset
int64_t clang::ReturnAdjustment::VirtualAdjustment::VBaseOffsetOffset
The offset (in bytes), relative to the address point of the virtual base class offset.
Definition at line 38 of file Thunk.h.
VBIndex
uint32_t clang::ReturnAdjustment::VirtualAdjustment::VBIndex
Index of the virtual base in the vbtable.
Definition at line 48 of file Thunk.h.
Referenced by dumpMicrosoftThunkAdjustment().
VBPtrOffset
uint32_t clang::ReturnAdjustment::VirtualAdjustment::VBPtrOffset
The offset (in bytes) of the vbptr, relative to the beginning of the derived class.
Definition at line 45 of file Thunk.h.
Referenced by dumpMicrosoftThunkAdjustment().
The documentation for this union was generated from the following file:
include/clang/Basic/Thunk.h