clang: clang::ThisAdjustment::VirtualAdjustment Union Reference
clang::ThisAdjustment::VirtualAdjustment Union Reference
Holds the ABI-specific information about the virtual this adjustment, if needed.
#include "clang/Basic/Thunk.h"
Public Member Functions
VirtualAdjustment ()
bool Equals (const VirtualAdjustment &Other) const
bool isEmpty () const
bool Less (const VirtualAdjustment &RHS) const
Public Attributes
struct {
int64_t VCallOffsetOffset
The offset (in bytes), relative to the address point, of the virtual call offset.
} Itanium
struct {
int32_t VtordispOffset
The offset of the vtordisp (in bytes), relative to the ECX.
int32_t VBPtrOffset
The offset of the vbptr of the derived class (in bytes), relative to the ECX after vtordisp adjustment.
int32_t VBOffsetOffset
The offset (in bytes) of the vbase offset in the vbtable.
} Microsoft
Detailed Description
Holds the ABI-specific information about the virtual this adjustment, if needed.
Definition at line 98 of file Thunk.h.
Constructor & Destructor Documentation
VirtualAdjustment()
clang::ThisAdjustment::VirtualAdjustment::VirtualAdjustment () inline
Definition at line 118 of file Thunk.h.
References memset().
Member Function Documentation
Equals()
bool clang::ThisAdjustment::VirtualAdjustment::Equals (const VirtualAdjustment & Other) const inline
Definition at line 120 of file Thunk.h.
Referenced by isEmpty().
isEmpty()
bool clang::ThisAdjustment::VirtualAdjustment::isEmpty () const inline
Definition at line 124 of file Thunk.h.
References Equals(), and clang::interp::Zero().
Referenced by dumpMicrosoftThunkAdjustment(), clang::ThisAdjustment::isEmpty(), and mangleThunkThisAdjustment().
Less()
bool clang::ThisAdjustment::VirtualAdjustment::Less (const VirtualAdjustment & RHS) const inline
Definition at line 129 of file Thunk.h.
Member Data Documentation
Itanium
struct { ... } clang::ThisAdjustment::VirtualAdjustment::Itanium
Microsoft
struct { ... } clang::ThisAdjustment::VirtualAdjustment::Microsoft
Referenced by dumpMicrosoftThunkAdjustment(), and mangleThunkThisAdjustment().
VBOffsetOffset
int32_t clang::ThisAdjustment::VirtualAdjustment::VBOffsetOffset
The offset (in bytes) of the vbase offset in the vbtable.
Definition at line 115 of file Thunk.h.
Referenced by dumpMicrosoftThunkAdjustment(), and mangleThunkThisAdjustment().
VBPtrOffset
int32_t clang::ThisAdjustment::VirtualAdjustment::VBPtrOffset
The offset of the vbptr of the derived class (in bytes), relative to the ECX after vtordisp adjustment.
Definition at line 112 of file Thunk.h.
Referenced by dumpMicrosoftThunkAdjustment(), and mangleThunkThisAdjustment().
VCallOffsetOffset
int64_t clang::ThisAdjustment::VirtualAdjustment::VCallOffsetOffset
The offset (in bytes), relative to the address point, of the virtual call offset.
Definition at line 103 of file Thunk.h.
VtordispOffset
int32_t clang::ThisAdjustment::VirtualAdjustment::VtordispOffset
The offset of the vtordisp (in bytes), relative to the ECX.
Definition at line 108 of file Thunk.h.
Referenced by dumpMicrosoftThunkAdjustment(), and mangleThunkThisAdjustment().
The documentation for this union was generated from the following file:
include/clang/Basic/Thunk.h