clang: lib/Analysis/UnsafeBufferUsage.cpp File Reference
UnsafeBufferUsage.cpp File Reference
#include "clang/Analysis/Analyses/UnsafeBufferUsage.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/AST/Expr.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/Stmt.h"
#include "clang/AST/StmtVisitor.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/ASTMatchers/ASTMatchers.h"
#include "clang/Basic/CharInfo.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Lex/Lexer.h"
#include "clang/Lex/Preprocessor.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Casting.h"
#include <memory>
#include <optional>
#include <queue>
#include <sstream>
#include "clang/Analysis/Analyses/UnsafeBufferUsageGadgets.def"
Classes
class clang::ast_matchers::MatchDescendantVisitor
class UPCPreIncrementGadget
class UUCAddAssignGadget
class DerefSimplePtrArithFixableGadget
struct CompareNode< NodeTy >
struct WarningGadgetSets
struct FixableGadgetSets
class VariableGroupsManagerImpl
Namespaces
clang
The JSON file list parser is used to communicate input to InstallAPI.
clang::ast_matchers
Macros
#define GADGET(x) x,
#define GADGET(x)
#define NEXT ++numFound
#define FIXABLE_GADGET(name)
#define WARNING_GADGET(name)
#define WARNING_GADGET(x)
#define WARNING_CONTAINER_GADGET(x)
#define FIXABLE_GADGET(x) x ## Gadget::matcher().bind(#x),
#define DEBUG_NOTE_DECL_FAIL(D, Msg)
Functions
static auto clang::ast_matchers::hasPointerType ()
static auto clang::ast_matchers::hasArrayType ()
clang::ast_matchers::AST_MATCHER_P (Stmt, forEachDescendantEvaluatedStmt, internal::Matcher< Stmt >, innerMatcher)
clang::ast_matchers::AST_MATCHER_P (Stmt, forEachDescendantStmt, internal::Matcher< Stmt >, innerMatcher)
clang::ast_matchers::AST_MATCHER_P (Stmt, notInSafeBufferOptOut, const UnsafeBufferUsageHandler *, Handler)
clang::ast_matchers::AST_MATCHER_P (Stmt, ignoreUnsafeBufferInContainer, const UnsafeBufferUsageHandler *, Handler)
clang::ast_matchers::AST_MATCHER_P (CastExpr, castSubExpr, internal::Matcher< Expr >, innerMatcher)
clang::ast_matchers::AST_MATCHER (UnaryOperator, isPreInc)
static auto clang::ast_matchers::isInUnspecifiedLvalueContext (internal::Matcher< Expr > innerMatcher)
static internal::Matcher< Stmt > clang::ast_matchers::isInUnspecifiedPointerContext (internal::Matcher< Stmt > InnerMatcher)
static internal::Matcher< Stmt > clang::ast_matchers::isInUnspecifiedUntypedContext (internal::Matcher< Stmt > InnerMatcher)
clang::ast_matchers::AST_MATCHER (CXXConstructExpr, isSafeSpanTwoParamConstruct)
clang::ast_matchers::AST_MATCHER (ArraySubscriptExpr, isSafeArraySubscript)
static std::tuple< FixableGadgetList, WarningGadgetList, DeclUseTracker > findGadgets (const Decl *D, const UnsafeBufferUsageHandler &Handler, bool EmitSuggestions)
Scan the function and return a list of gadgets found with provided kits.
static WarningGadgetSets groupWarningGadgetsByVar (const WarningGadgetList &AllUnsafeOperations)
static FixableGadgetSets groupFixablesByVar (FixableGadgetList &&AllFixableOperations)
static std::optional< FixItList > createDataFixit (const ASTContext &Ctx, const DeclRefExpr *DRE)
static bool isNonNegativeIntegerExpr (const Expr *Expr, const VarDecl *VD, const ASTContext &Ctx)
static std::optional< FixItList > fixUPCAddressofArraySubscriptWithSpan (const UnaryOperator *Node)
static StringRef getEndOfLine ()
std::string getUserFillPlaceHolder (StringRef HintTextToUser="placeholder")
template<typename NodeTy >
static std::optional< SourceLocation > getEndCharLoc (const NodeTy *Node, const SourceManager &SM, const LangOptions &LangOpts)
template<typename NodeTy >
static std::optional< SourceLocation > getPastLoc (const NodeTy *Node, const SourceManager &SM, const LangOptions &LangOpts)
static std::optional< StringRef > getExprText (const Expr *E, const SourceManager &SM, const LangOptions &LangOpts)
static std::optional< StringRef > getRangeText (SourceRange SR, const SourceManager &SM, const LangOptions &LangOpts)
static SourceLocation getVarDeclIdentifierLoc (const VarDecl *VD)
static std::optional< StringRef > getVarDeclIdentifierText (const VarDecl *VD, const SourceManager &SM, const LangOptions &LangOpts)
static bool hasUnsupportedSpecifiers (const VarDecl *VD, const SourceManager &SM)
static SourceRange getSourceRangeToTokenEnd (const Decl *D, const SourceManager &SM, const LangOptions &LangOpts)
static std::optional< std::string > getPointeeTypeText (const VarDecl *VD, const SourceManager &SM, const LangOptions &LangOpts, std::optional< Qualifiers > *QualifiersToAppend)
static std::optional< StringRef > getFunNameText (const FunctionDecl *FD, const SourceManager &SM, const LangOptions &LangOpts)
static std::string getSpanTypeText (StringRef EltTyText, std::optional< Qualifiers > Quals=std::nullopt)
static std::optional< FixItList > FixVarInitializerWithSpan (const Expr *Init, ASTContext &Ctx, const StringRef UserFillPlaceHolder)
static std::optional< std::string > createSpanTypeForVarDecl (const VarDecl *VD, const ASTContext &Ctx)
static FixItList fixLocalVarDeclWithSpan (const VarDecl *D, ASTContext &Ctx, const StringRef UserFillPlaceHolder, UnsafeBufferUsageHandler &Handler)
static bool hasConflictingOverload (const FunctionDecl *FD)
static std::optional< FixItList > createOverloadsForFixedParams (const FixitStrategy &S, const FunctionDecl *FD, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixParamWithSpan (const ParmVarDecl *PVD, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixVariableWithSpan (const VarDecl *VD, const DeclUseTracker &Tracker, ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixVarDeclWithArray (const VarDecl *D, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixVariableWithArray (const VarDecl *VD, const DeclUseTracker &Tracker, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixVariable (const VarDecl *VD, FixitStrategy::Kind K, const Decl *D, const DeclUseTracker &Tracker, ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static bool overlapWithMacro (const FixItList &FixIts)
static bool isParameterOf (const VarDecl *VD, const Decl *D)
static void eraseVarsForUnfixableGroupMates (std::map< const VarDecl *, FixItList > &FixItsForVariable, const VariableGroupsManager &VarGrpMgr)
static FixItList createFunctionOverloadsForParms (std::map< const VarDecl *, FixItList > &FixItsForVariable, const VariableGroupsManager &VarGrpMgr, const FunctionDecl *FD, const FixitStrategy &S, ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static std::map< const VarDecl *, FixItList > getFixIts (FixableGadgetSets &FixablesForAllVars, const FixitStrategy &S, ASTContext &Ctx, const Decl *D, const DeclUseTracker &Tracker, UnsafeBufferUsageHandler &Handler, const VariableGroupsManager &VarGrpMgr)
template<typename VarDeclIterTy >
static FixitStrategy getNaiveStrategy (llvm::iterator_range< VarDeclIterTy > UnsafeVars)
Macro Definition Documentation
DEBUG_NOTE_DECL_FAIL
#define DEBUG_NOTE_DECL_FAIL (D, Msg)
Value:
  Handler.addDebugNoteForVar((D), (D)->getBeginLoc(),                          \
                             "failed to produce fixit for declaration '" +     \
                                 (D)->getNameAsString() + "'" + (Msg))
Definition at line 2229 of file UnsafeBufferUsage.cpp.
FIXABLE_GADGET [1/2]
#define FIXABLE_GADGET (name)
Value:
  if (Result.Nodes.getNodeAs<Stmt>(#name)) {                                   \
    FixableGadgets.push_back(std::make_unique<name##Gadget>(Result));          \
    NEXT;                                                                      \
  }
FIXABLE_GADGET [2/2]
#define FIXABLE_GADGET (x) x ## Gadget::matcher().bind(#x),
GADGET [1/2]
#define GADGET (x) x,
Definition at line 469 of file UnsafeBufferUsage.cpp.
GADGET [2/2]
#define GADGET (x)
Value:
  case Kind::x:                                                                \
    return #x;
Definition at line 469 of file UnsafeBufferUsage.cpp.
NEXT
#define NEXT ++numFound
WARNING_CONTAINER_GADGET
#define WARNING_CONTAINER_GADGET (x)
Value:
          allOf(x ## Gadget::matcher().bind(#x),                               \
                notInSafeBufferOptOut(&Handler),                               \
                unless(ignoreUnsafeBufferInContainer(&Handler))),
WARNING_GADGET [1/2]
#define WARNING_GADGET (name)
Value:
  if (Result.Nodes.getNodeAs<Stmt>(#name)) {                                   \
    WarningGadgets.push_back(std::make_unique<name##Gadget>(Result));          \
    NEXT;                                                                      \
  }
WARNING_GADGET [2/2]
#define WARNING_GADGET (x)
Value:
          allOf(x ## Gadget::matcher().bind(#x),                               \
                notInSafeBufferOptOut(&Handler)),
Function Documentation
createDataFixit()
static std::optional< FixItList > createDataFixit (const ASTContext & Ctx, const DeclRefExpr * DRE) inline static
Returns
fixit that adds .data() call after \DRE.
Definition at line 1990 of file UnsafeBufferUsage.cpp.
References clang::ASTContext::getLangOpts(), getPastLoc(), clang::ASTContext::getSourceManager(), and SM.
createFunctionOverloadsForParms()
static FixItList createFunctionOverloadsForParms (std::map< const VarDecl *, FixItList > & FixItsForVariable, const VariableGroupsManager & VarGrpMgr, const FunctionDecl * FD, const FixitStrategy & S, ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2803 of file UnsafeBufferUsage.cpp.
createOverloadsForFixedParams()
static std::optional<FixItList> createOverloadsForFixedParams (const FixitStrategy & S, const FunctionDecl * FD, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2360 of file UnsafeBufferUsage.cpp.
createSpanTypeForVarDecl()
static std::optional<std::string> createSpanTypeForVarDecl (const VarDecl * VD, const ASTContext & Ctx) static
Definition at line 2241 of file UnsafeBufferUsage.cpp.
References clang::ASTContext::getLangOpts(), getPointeeTypeText(), clang::ASTContext::getSourceManager(), clang::ValueDecl::getType(), and clang::Type::isPointerType().
Referenced by fixLocalVarDeclWithSpan(), and fixParamWithSpan().
eraseVarsForUnfixableGroupMates()
static void eraseVarsForUnfixableGroupMates (std::map< const VarDecl *, FixItList > & FixItsForVariable, const VariableGroupsManager & VarGrpMgr) static
Definition at line 2774 of file UnsafeBufferUsage.cpp.
References clang::VariableGroupsManager::getGroupOfVar(), and clang::Member.
findGadgets()
static std::tuple<FixableGadgetList, WarningGadgetList, DeclUseTracker> findGadgets (const Decl * D, const UnsafeBufferUsageHandler & Handler, bool EmitSuggestions) static
Scan the function and return a list of gadgets found with provided kits.
Definition at line 1329 of file UnsafeBufferUsage.cpp.
References clang::ast_matchers::MatchFinder::addMatcher(), clang::ast_matchers::allOf, clang::ast_matchers::anyOf, clang::ast_matchers::bindingDecl, clang::ast_matchers::declRefExpr, clang::ast_matchers::declStmt, clang::ast_matchers::eachOf, FIXABLE_GADGET, clang::Decl::getASTContext(), clang::Decl::getBody(), clang::ast_matchers::hasArrayType(), clang::ast_matchers::hasPointerType(), clang::ast_matchers::MatchFinder::match(), NEXT, clang::transformer::run(), clang::ast_matchers::stmt, clang::ast_matchers::unless, clang::ast_matchers::varDecl, WARNING_CONTAINER_GADGET, and WARNING_GADGET.
Referenced by clang::checkUnsafeBufferUsage().
fixLocalVarDeclWithSpan()
static FixItList fixLocalVarDeclWithSpan (const VarDecl * D, ASTContext & Ctx, const StringRef UserFillPlaceHolder, UnsafeBufferUsageHandler & Handler) static
Definition at line 2277 of file UnsafeBufferUsage.cpp.
References createSpanTypeForVarDecl(), DEBUG_NOTE_DECL_FAIL, FixVarInitializerWithSpan(), clang::DeclaratorDecl::getBeginLoc(), clang::VarDecl::getInit(), clang::SourceLocation::getLocWithOffset(), clang::ASTContext::getSourceManager(), clang::DeclaratorDecl::getTypeSpecEndLoc(), getVarDeclIdentifierLoc(), hasUnsupportedSpecifiers(), and clang::SourceLocation::isValid().
Referenced by fixVariableWithSpan().
fixParamWithSpan()
static FixItList fixParamWithSpan (const ParmVarDecl * PVD, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2527 of file UnsafeBufferUsage.cpp.
References createSpanTypeForVarDecl(), DEBUG_NOTE_DECL_FAIL, clang::Qualifiers::getAsString(), clang::NamedDecl::getIdentifier(), clang::ASTContext::getLangOpts(), clang::IdentifierInfo::getName(), getPointeeTypeText(), clang::QualType::getQualifiers(), clang::ASTContext::getSourceManager(), clang::ParmVarDecl::getSourceRange(), getSpanTypeText(), clang::ValueDecl::getType(), clang::ParmVarDecl::hasDefaultArg(), clang::QualType::hasQualifiers(), and hasUnsupportedSpecifiers().
Referenced by fixVariable().
fixUPCAddressofArraySubscriptWithSpan()
static std::optional< FixItList > fixUPCAddressofArraySubscriptWithSpan (const UnaryOperator * Node) static
Definition at line 2028 of file UnsafeBufferUsage.cpp.
References clang::Decl::getASTContext(), clang::DeclRefExpr::getDecl(), clang::ASTContext::getSourceManager(), Node, and SM.
fixVarDeclWithArray()
static FixItList fixVarDeclWithArray (const VarDecl * D, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2596 of file UnsafeBufferUsage.cpp.
References DEBUG_NOTE_DECL_FAIL, clang::DeclaratorDecl::getBeginLoc(), clang::QualType::getCanonicalType(), clang::SourceRange::getEnd(), clang::ASTContext::getLangOpts(), clang::SourceLocation::getLocWithOffset(), getRangeText(), clang::ASTContext::getSourceManager(), clang::VarDecl::getSourceRange(), clang::ValueDecl::getType(), clang::DeclaratorDecl::getTypeSpecEndLoc(), getVarDeclIdentifierLoc(), getVarDeclIdentifierText(), and clang::QualType::isNull().
Referenced by fixVariableWithArray().
fixVariable()
static FixItList fixVariable (const VarDecl * VD, FixitStrategy::Kind K, const Decl * D, const DeclUseTracker & Tracker, ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2692 of file UnsafeBufferUsage.cpp.
References DEBUG_NOTE_DECL_FAIL, fixParamWithSpan(), fixVariableWithArray(), fixVariableWithSpan(), clang::QualType::getCanonicalType(), clang::ValueDecl::getType(), clang::VarDecl::isLocalVarDecl(), and clang::Type::isPointerType().
fixVariableWithArray()
static FixItList fixVariableWithArray (const VarDecl * VD, const DeclUseTracker & Tracker, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2670 of file UnsafeBufferUsage.cpp.
References fixVarDeclWithArray(), and clang::DeclStmt::isSingleDecl().
Referenced by fixVariable().
fixVariableWithSpan()
static FixItList fixVariableWithSpan (const VarDecl * VD, const DeclUseTracker & Tracker, ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 2572 of file UnsafeBufferUsage.cpp.
References DEBUG_NOTE_DECL_FAIL, fixLocalVarDeclWithSpan(), getUserFillPlaceHolder(), and clang::DeclStmt::isSingleDecl().
Referenced by fixVariable().
FixVarInitializerWithSpan()
static std::optional<FixItList> FixVarInitializerWithSpan (const Expr * Init, ASTContext & Ctx, const StringRef UserFillPlaceHolder) static
Definition at line 2151 of file UnsafeBufferUsage.cpp.
References clang::ASTContext::getSourceManager(), and SM.
Referenced by fixLocalVarDeclWithSpan().
getEndCharLoc()
template<typename NodeTy > static std::optional<SourceLocation> getEndCharLoc (const NodeTy * Node, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1678 of file UnsafeBufferUsage.cpp.
getEndOfLine()
static StringRef getEndOfLine () static
Definition at line 1662 of file UnsafeBufferUsage.cpp.
getExprText()
static std::optional<StringRef> getExprText (const Expr * E, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1702 of file UnsafeBufferUsage.cpp.
getFixIts()
static std::map<const VarDecl *, FixItList> getFixIts (FixableGadgetSets & FixablesForAllVars, const FixitStrategy & S, ASTContext & Ctx, const Decl * D, const DeclUseTracker & Tracker, UnsafeBufferUsageHandler & Handler, const VariableGroupsManager & VarGrpMgr) static
Definition at line 2827 of file UnsafeBufferUsage.cpp.
Referenced by clang::checkUnsafeBufferUsage().
getFunNameText()
static std::optional<StringRef> getFunNameText (const FunctionDecl * FD, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1866 of file UnsafeBufferUsage.cpp.
getNaiveStrategy()
template<typename VarDeclIterTy > static FixitStrategy getNaiveStrategy (llvm::iterator_range< VarDeclIterTy > UnsafeVars) static
Definition at line 2927 of file UnsafeBufferUsage.cpp.
Referenced by clang::checkUnsafeBufferUsage().
getPastLoc()
template<typename NodeTy > static std::optional<SourceLocation> getPastLoc (const NodeTy * Node, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1691 of file UnsafeBufferUsage.cpp.
Referenced by createDataFixit().
getPointeeTypeText()
static std::optional<std::string> getPointeeTypeText (const VarDecl * VD, const SourceManager & SM, const LangOptions & LangOpts, std::optional< Qualifiers > * QualifiersToAppend) static
Definition at line 1793 of file UnsafeBufferUsage.cpp.
Referenced by createSpanTypeForVarDecl(), and fixParamWithSpan().
getRangeText()
static std::optional<StringRef> getRangeText (SourceRange SR, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1716 of file UnsafeBufferUsage.cpp.
Referenced by fixVarDeclWithArray().
getSourceRangeToTokenEnd()
static SourceRange getSourceRangeToTokenEnd (const Decl * D, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1775 of file UnsafeBufferUsage.cpp.
getSpanTypeText()
static std::string getSpanTypeText (StringRef EltTyText, std::optional< Qualifiers > Quals = std::nullopt) static
Definition at line 1887 of file UnsafeBufferUsage.cpp.
Referenced by fixParamWithSpan().
getUserFillPlaceHolder()
std::string getUserFillPlaceHolder (StringRef HintTextToUser = "placeholder")
Definition at line 1668 of file UnsafeBufferUsage.cpp.
References s.
Referenced by fixVariableWithSpan().
getVarDeclIdentifierLoc()
static SourceLocation getVarDeclIdentifierLoc (const VarDecl * VD) static
Definition at line 1730 of file UnsafeBufferUsage.cpp.
References clang::Decl::getLocation().
Referenced by fixLocalVarDeclWithSpan(), and fixVarDeclWithArray().
getVarDeclIdentifierText()
static std::optional<StringRef> getVarDeclIdentifierText (const VarDecl * VD, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 1738 of file UnsafeBufferUsage.cpp.
Referenced by fixVarDeclWithArray().
groupFixablesByVar()
static FixableGadgetSets groupFixablesByVar (FixableGadgetList && AllFixableOperations) static
Definition at line 1481 of file UnsafeBufferUsage.cpp.
References FixableGadgetSets::byVar, and clang::DeclRefExpr::getDecl().
Referenced by clang::checkUnsafeBufferUsage().
groupWarningGadgetsByVar()
static WarningGadgetSets groupWarningGadgetsByVar (const WarningGadgetList & AllUnsafeOperations) static
Definition at line 1449 of file UnsafeBufferUsage.cpp.
References WarningGadgetSets::byVar, clang::DeclRefExpr::getDecl(), and WarningGadgetSets::noVar.
Referenced by clang::checkUnsafeBufferUsage().
hasConflictingOverload()
static bool hasConflictingOverload (const FunctionDecl * FD) static
Definition at line 2324 of file UnsafeBufferUsage.cpp.
References clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::DeclContextLookupResult::isSingleResult(), and clang::DeclContext::lookup().
hasUnsupportedSpecifiers()
static bool hasUnsupportedSpecifiers (const VarDecl * VD, const SourceManager & SM) static
Definition at line 1756 of file UnsafeBufferUsage.cpp.
References clang::Decl::attrs(), clang::VarDecl::hasConstantInitialization(), clang::VarDecl::hasLocalStorage(), clang::VarDecl::isConstexpr(), and clang::VarDecl::isInlineSpecified().
Referenced by fixLocalVarDeclWithSpan(), and fixParamWithSpan().
isNonNegativeIntegerExpr()
static bool isNonNegativeIntegerExpr (const Expr * Expr, const VarDecl * VD, const ASTContext & Ctx) static
Definition at line 1602 of file UnsafeBufferUsage.cpp.
References clang::Expr::getIntegerConstantExpr(), clang::Expr::getType(), and clang::Type::isUnsignedIntegerType().
isParameterOf()
static bool isParameterOf (const VarDecl * VD, const Decl * D) static
Definition at line 2766 of file UnsafeBufferUsage.cpp.
References clang::Decl::getDeclContext().
Referenced by clang::checkUnsafeBufferUsage().
overlapWithMacro()
static bool overlapWithMacro (const FixItList & FixIts) static
Definition at line 2753 of file UnsafeBufferUsage.cpp.
References clang::FixItHint::RemoveRange.