clang: lib/StaticAnalyzer/Checkers/VirtualCallChecker.cpp File Reference
VirtualCallChecker.cpp File Reference
#include "clang/AST/Attr.h"
#include "clang/AST/DeclCXX.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugReporter.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ProgramStateTrait.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/SValBuilder.h"
Classes
struct llvm::FoldingSetTrait< ObjectState >
Namespaces
llvm
Diagnostic wrappers for TextAPI types for error reporting.
Functions
static bool isVirtualCall (const CallExpr *CE)
Function Documentation
isVirtualCall()
static bool isVirtualCall (const CallExpr * CE) static
Definition at line 63 of file VirtualCallChecker.cpp.
References clang::CXXMethodDecl::getParent(), clang::Decl::hasAttr(), and clang::CXXMethodDecl::isVirtual().