clang: lib/Basic/Warnings.cpp File Reference
Warnings.cpp File Reference
#include "clang/Basic/AllDiagnostics.h"
#include "clang/Basic/Diagnostic.h"
#include "clang/Basic/DiagnosticOptions.h"
#include <algorithm>
#include <cstring>
#include <utility>
Functions
static void EmitUnknownDiagWarning (DiagnosticsEngine &Diags, diag::Flavor Flavor, StringRef Prefix, StringRef Opt)
Function Documentation
EmitUnknownDiagWarning()
static void EmitUnknownDiagWarning (DiagnosticsEngine & Diags, diag::Flavor Flavor, StringRef Prefix, StringRef Opt) static
Definition at line 34 of file Warnings.cpp.
References clang::DiagnosticIDs::getNearestOption(), clang::DiagnosticsEngine::Report(), string(), and clang::diag::WarningOrError.
Referenced by clang::ProcessWarningOptions().