var annotated_dup =
[
    [ "__spv", "namespace____spv.html", "namespace____spv" ],
    [ "cl", "namespacecl.html", "namespacecl" ],
    [ "settings", "namespacesettings.html", "namespacesettings" ],
    [ "std", "namespacestd.html", "namespacestd" ],
    [ "__abi_storage_kind", "struct____abi__storage__kind.html", null ],
    [ "__abi_storage_kind< __simd_abi< _K, _Np > >", "struct____abi__storage__kind_3_01____simd__abi_3_01__K_00_01__Np_01_4_01_4.html", "struct____abi__storage__kind_3_01____simd__abi_3_01__K_00_01__Np_01_4_01_4" ],
    [ "__copyAcc2Acc", "class____copyAcc2Acc.html", null ],
    [ "__copyAcc2Ptr", "class____copyAcc2Ptr.html", null ],
    [ "__copyPtr2Acc", "class____copyPtr2Acc.html", null ],
    [ "__fill", "class____fill.html", null ],
    [ "__mask_element", "struct____mask__element.html", "struct____mask__element" ],
    [ "__nodeduce", "struct____nodeduce.html", "struct____nodeduce" ],
    [ "__simd_abi", "struct____simd__abi.html", null ],
    [ "__simd_cast_traits", "struct____simd__cast__traits.html", "struct____simd__cast__traits" ],
    [ "__simd_cast_traits< simd< _Tp, _NewAbi > >", "struct____simd__cast__traits_3_01simd_3_01__Tp_00_01__NewAbi_01_4_01_4.html", "struct____simd__cast__traits_3_01simd_3_01__Tp_00_01__NewAbi_01_4_01_4" ],
    [ "__simd_mask_reference", "class____simd__mask__reference.html", "class____simd__mask__reference" ],
    [ "__simd_reference", "class____simd__reference.html", "class____simd__reference" ],
    [ "__simd_storage", "class____simd__storage.html", null ],
    [ "__simd_storage< _Tp, __simd_abi< _StorageKind::_Array, __num_element > >", "class____simd__storage_3_01__Tp_00_01____simd__abi_3_01__StorageKind_1_1__Array_00_01____num__element_01_4_01_4.html", "class____simd__storage_3_01__Tp_00_01____simd__abi_3_01__StorageKind_1_1__Array_00_01____num__element_01_4_01_4" ],
    [ "__simd_storage< _Tp, __simd_abi< _StorageKind::_Scalar, 1 > >", "class____simd__storage_3_01__Tp_00_01____simd__abi_3_01__StorageKind_1_1__Scalar_00_011_01_4_01_4.html", "class____simd__storage_3_01__Tp_00_01____simd__abi_3_01__StorageKind_1_1__Scalar_00_011_01_4_01_4" ],
    [ "__simd_storage< _Tp, __simd_abi< _StorageKind::_VecExt, __num_element > >", "class____simd__storage_3_01__Tp_00_01____simd__abi_3_01__StorageKind_1_1__VecExt_00_01____num__element_01_4_01_4.html", "class____simd__storage_3_01__Tp_00_01____simd__abi_3_01__StorageKind_1_1__VecExt_00_01____num__element_01_4_01_4" ],
    [ "__static_simd_cast_traits", "struct____static__simd__cast__traits.html", "struct____static__simd__cast__traits" ],
    [ "__static_simd_cast_traits< simd< _Tp, _NewAbi > >", "struct____static__simd__cast__traits_3_01simd_3_01__Tp_00_01__NewAbi_01_4_01_4.html", "struct____static__simd__cast__traits_3_01simd_3_01__Tp_00_01__NewAbi_01_4_01_4" ],
    [ "__usmfill", "class____usmfill.html", null ],
    [ "__vec_ext_traits", "struct____vec__ext__traits.html", null ],
    [ "_pi_buffer", "struct__pi__buffer.html", "struct__pi__buffer" ],
    [ "_pi_context", "struct__pi__context.html", "struct__pi__context" ],
    [ "_pi_device", "struct__pi__device.html", "struct__pi__device" ],
    [ "_pi_device_binary_property_set_struct", "struct__pi__device__binary__property__set__struct.html", "struct__pi__device__binary__property__set__struct" ],
    [ "_pi_device_binary_property_struct", "struct__pi__device__binary__property__struct.html", "struct__pi__device__binary__property__struct" ],
    [ "_pi_event", "struct__pi__event.html", "struct__pi__event" ],
    [ "_pi_image", "struct__pi__image.html", "struct__pi__image" ],
    [ "_pi_image_desc", "struct__pi__image__desc.html", "struct__pi__image__desc" ],
    [ "_pi_image_format", "struct__pi__image__format.html", "struct__pi__image__format" ],
    [ "_pi_kernel", "struct__pi__kernel.html", "struct__pi__kernel" ],
    [ "_pi_mem", "struct__pi__mem.html", "struct__pi__mem" ],
    [ "_pi_object", "struct__pi__object.html", "struct__pi__object" ],
    [ "_pi_offload_entry_struct", "struct__pi__offload__entry__struct.html", "struct__pi__offload__entry__struct" ],
    [ "_pi_platform", "struct__pi__platform.html", "struct__pi__platform" ],
    [ "_pi_plugin", "struct__pi__plugin.html", "struct__pi__plugin" ],
    [ "_pi_program", "struct__pi__program.html", "struct__pi__program" ],
    [ "_pi_queue", "struct__pi__queue.html", "struct__pi__queue" ],
    [ "_pi_sampler", "struct__pi__sampler.html", "struct__pi__sampler" ],
    [ "_pi_ze_event_list_t", "struct__pi__ze__event__list__t.html", "struct__pi__ze__event__list__t" ],
    [ "abi_for_size", "structabi__for__size.html", "structabi__for__size" ],
    [ "bool_constant", "classbool__constant.html", null ],
    [ "Bucket", "classBucket.html", "classBucket" ],
    [ "cm_buffer_ptr_slot", "structcm__buffer__ptr__slot.html", "structcm__buffer__ptr__slot" ],
    [ "cm_image_ptr_slot", "structcm__image__ptr__slot.html", "structcm__image__ptr__slot" ],
    [ "CommandListBatchConfig", "structCommandListBatchConfig.html", "structCommandListBatchConfig" ],
    [ "compile_program_error", "classcompile__program__error.html", null ],
    [ "const_where_expression", "classconst__where__expression.html", "classconst__where__expression" ],
    [ "element_aligned_tag", "structelement__aligned__tag.html", null ],
    [ "InvokeImpl", "structInvokeImpl.html", "structInvokeImpl" ],
    [ "is_abi_tag", "structis__abi__tag.html", null ],
    [ "is_abi_tag< __simd_abi< __kind, _Np > >", "structis__abi__tag_3_01____simd__abi_3_01____kind_00_01__Np_01_4_01_4.html", null ],
    [ "is_simd", "structis__simd.html", null ],
    [ "is_simd< simd< _Tp, _Abi > >", "structis__simd_3_01simd_3_01__Tp_00_01__Abi_01_4_01_4.html", null ],
    [ "is_simd_flag_type", "structis__simd__flag__type.html", null ],
    [ "is_simd_flag_type< element_aligned_tag >", "structis__simd__flag__type_3_01element__aligned__tag_01_4.html", null ],
    [ "is_simd_flag_type< overaligned_tag< _Align > >", "structis__simd__flag__type_3_01overaligned__tag_3_01__Align_01_4_01_4.html", null ],
    [ "is_simd_flag_type< vector_aligned_tag >", "structis__simd__flag__type_3_01vector__aligned__tag_01_4.html", null ],
    [ "is_simd_mask", "structis__simd__mask.html", null ],
    [ "is_simd_mask< simd_mask< _Tp, _Abi > >", "structis__simd__mask_3_01simd__mask_3_01__Tp_00_01__Abi_01_4_01_4.html", null ],
    [ "KernelInvocationContext", "structKernelInvocationContext.html", "structKernelInvocationContext" ],
    [ "libCMBatch", "classlibCMBatch.html", "classlibCMBatch" ],
    [ "MemAllocRecord", "structMemAllocRecord.html", "structMemAllocRecord" ],
    [ "memory_alignment", "structmemory__alignment.html", null ],
    [ "overaligned_tag", "structoveraligned__tag.html", null ],
    [ "pi_buff_rect_offset_struct", "structpi__buff__rect__offset__struct.html", "structpi__buff__rect__offset__struct" ],
    [ "pi_buff_rect_region_struct", "structpi__buff__rect__region__struct.html", "structpi__buff__rect__region__struct" ],
    [ "pi_buffer_region_struct", "structpi__buffer__region__struct.html", "structpi__buffer__region__struct" ],
    [ "pi_command_list_info_t", "structpi__command__list__info__t.html", "structpi__command__list__info__t" ],
    [ "pi_device_binaries_struct", "structpi__device__binaries__struct.html", "structpi__device__binaries__struct" ],
    [ "pi_device_binary_struct", "structpi__device__binary__struct.html", "structpi__device__binary__struct" ],
    [ "pi_image_offset_struct", "structpi__image__offset__struct.html", "structpi__image__offset__struct" ],
    [ "pi_image_region_struct", "structpi__image__region__struct.html", "structpi__image__region__struct" ],
    [ "pi_shared_mutex", "classpi__shared__mutex.html", "classpi__shared__mutex" ],
    [ "RangeBuilder", "structRangeBuilder.html", null ],
    [ "RangeBuilder< 1 >", "structRangeBuilder_3_011_01_4.html", "structRangeBuilder_3_011_01_4" ],
    [ "RangeBuilder< 2 >", "structRangeBuilder_3_012_01_4.html", "structRangeBuilder_3_012_01_4" ],
    [ "RangeBuilder< 3 >", "structRangeBuilder_3_013_01_4.html", "structRangeBuilder_3_013_01_4" ],
    [ "ReleaseGuard", "classReleaseGuard.html", "classReleaseGuard" ],
    [ "simd", "classsimd.html", "classsimd" ],
    [ "simd_mask", "classsimd__mask.html", "classsimd__mask" ],
    [ "simd_obj_impl", "classsimd__obj__impl.html", null ],
    [ "simd_size", "structsimd__size.html", null ],
    [ "simd_size< _Tp, __simd_abi< __kind, _Np > >", "structsimd__size_3_01__Tp_00_01____simd__abi_3_01____kind_00_01__Np_01_4_01_4.html", null ],
    [ "Slab", "classSlab.html", "classSlab" ],
    [ "SystemMemory", "classSystemMemory.html", "classSystemMemory" ],
    [ "T", "classT.html", null ],
    [ "type", "classstd_1_1conditional_1_1type.html", null ],
    [ "UsmAllocationException", "classUsmAllocationException.html", "classUsmAllocationException" ],
    [ "USMAllocContext", "classUSMAllocContext.html", "classUSMAllocContext" ],
    [ "USMDeviceMemoryAlloc", "classUSMDeviceMemoryAlloc.html", "classUSMDeviceMemoryAlloc" ],
    [ "USMHostMemoryAlloc", "classUSMHostMemoryAlloc.html", "classUSMHostMemoryAlloc" ],
    [ "USMMemoryAllocBase", "classUSMMemoryAllocBase.html", "classUSMMemoryAllocBase" ],
    [ "USMSharedMemoryAlloc", "classUSMSharedMemoryAlloc.html", "classUSMSharedMemoryAlloc" ],
    [ "USMSharedReadOnlyMemoryAlloc", "classUSMSharedReadOnlyMemoryAlloc.html", "classUSMSharedReadOnlyMemoryAlloc" ],
    [ "vector_aligned_tag", "structvector__aligned__tag.html", null ],
    [ "where_expression", "classwhere__expression.html", "classwhere__expression" ],
    [ "ZeCache", "structZeCache.html", "structZeCache" ],
    [ "ZesStruct", "structZesStruct.html", "structZesStruct" ],
    [ "ZeStruct", "structZeStruct.html", "structZeStruct" ],
    [ "ZeUSMImportExtension", "classZeUSMImportExtension.html", "classZeUSMImportExtension" ]
];