DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::image_mem Class Reference
sycl::_V1::ext::oneapi::experimental::image_mem Class Reference
A class that represents image memory.
#include <sycl/ext/oneapi/bindless_images_memory.hpp>
Public Member Functions
image_mem ()=default
image_mem (const image_mem &)=default
image_mem (image_mem &&rhs)=default
image_mem (const image_descriptor &desc, const device &syclDevice, const context &syclContext)
image_mem (const image_descriptor &desc, const queue &syclQueue)
~image_mem ()=default
image_mem & operator= (const image_mem &)=default
image_mem & operator= (image_mem &&)=default
bool operator== (const image_mem &rhs) const
bool operator!= (const image_mem &rhs) const
raw_handle_type get_handle () const
const image_descriptor & get_descriptor () const
sycl::device get_device () const
sycl::context get_context () const
sycl::range< 3 > get_range () const
sycl::image_channel_type get_channel_type () const
sycl::image_channel_order get_channel_order () const
unsigned int get_num_channels () const
image_type get_type () const
raw_handle_type get_mip_level_mem_handle (const unsigned int level) const
Protected Member Functions
template<class Obj >
decltype(Obj::impl) friend sycl::detail::getSyclObjImpl (const Obj &SyclObject)
Protected Attributes
std::shared_ptr< detail::image_mem_impl > impl
Detailed Description
A class that represents image memory.
Definition at line 57 of file bindless_images_memory.hpp.
Constructor & Destructor Documentation
image_mem() [1/5]
sycl::_V1::ext::oneapi::experimental::image_mem::image_mem () default
image_mem() [2/5]
sycl::_V1::ext::oneapi::experimental::image_mem::image_mem (const image_mem &) default
image_mem() [3/5]
sycl::_V1::ext::oneapi::experimental::image_mem::image_mem (image_mem && rhs) default
image_mem() [4/5]
sycl::_V1::ext::oneapi::experimental::image_mem::image_mem (const image_descriptor & desc, const device & syclDevice, const context & syclContext)
image_mem() [5/5]
sycl::_V1::ext::oneapi::experimental::image_mem::image_mem (const image_descriptor & desc, const queue & syclQueue)
~image_mem()
sycl::_V1::ext::oneapi::experimental::image_mem::~image_mem () default
Member Function Documentation
get_channel_order()
sycl::image_channel_order sycl::_V1::ext::oneapi::experimental::image_mem::get_channel_order () const
Definition at line 92 of file bindless_images.cpp.
get_channel_type()
sycl::image_channel_type sycl::_V1::ext::oneapi::experimental::image_mem::get_channel_type () const
Definition at line 88 of file bindless_images.cpp.
get_context()
sycl::context sycl::_V1::ext::oneapi::experimental::image_mem::get_context () const inline
Definition at line 81 of file bindless_images_memory.hpp.
get_descriptor()
const image_descriptor& sycl::_V1::ext::oneapi::experimental::image_mem::get_descriptor () const inline
Definition at line 77 of file bindless_images_memory.hpp.
get_device()
sycl::device sycl::_V1::ext::oneapi::experimental::image_mem::get_device () const inline
Definition at line 80 of file bindless_images_memory.hpp.
get_handle()
raw_handle_type sycl::_V1::ext::oneapi::experimental::image_mem::get_handle () const inline
Definition at line 76 of file bindless_images_memory.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::create_image().
get_mip_level_mem_handle()
image_mem_handle sycl::_V1::ext::oneapi::experimental::image_mem::get_mip_level_mem_handle (const unsigned int level) const
Definition at line 106 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::get_mip_level_mem_handle(), and sycl::_V1::ext::oneapi::experimental::level.
get_num_channels()
unsigned int sycl::_V1::ext::oneapi::experimental::image_mem::get_num_channels () const
Definition at line 96 of file bindless_images.cpp.
References sycl::_V1::detail::getImageNumberChannels().
get_range()
sycl::range< 3 > sycl::_V1::ext::oneapi::experimental::image_mem::get_range () const
Definition at line 83 of file bindless_images.cpp.
get_type()
image_type sycl::_V1::ext::oneapi::experimental::image_mem::get_type () const
Definition at line 101 of file bindless_images.cpp.
operator!=()
bool sycl::_V1::ext::oneapi::experimental::image_mem::operator!= (const image_mem & rhs) const inline
Definition at line 74 of file bindless_images_memory.hpp.
operator=() [1/2]
image_mem& sycl::_V1::ext::oneapi::experimental::image_mem::operator= (const image_mem &) default
operator=() [2/2]
image_mem& sycl::_V1::ext::oneapi::experimental::image_mem::operator= (image_mem &&) default
operator==()
bool sycl::_V1::ext::oneapi::experimental::image_mem::operator== (const image_mem & rhs) const inline
Definition at line 73 of file bindless_images_memory.hpp.
References impl.
sycl::detail::getSyclObjImpl()
template<class Obj > decltype(Obj::impl) friend sycl::_V1::ext::oneapi::experimental::image_mem::sycl::detail::getSyclObjImpl (const Obj & SyclObject) protected
Member Data Documentation
impl
std::shared_ptr<detail::image_mem_impl> sycl::_V1::ext::oneapi::experimental::image_mem::impl protected
Definition at line 92 of file bindless_images_memory.hpp.
Referenced by operator==().
The documentation for this class was generated from the following files:
include/sycl/ext/oneapi/bindless_images_memory.hpp
source/detail/bindless_images.cpp