DPC++ Runtime: sycl::_V1::nd_range< Dimensions > Class Template Reference
sycl::_V1::nd_range< Dimensions > Class Template Reference
DPC++ User API
Defines the iteration domain of both the work-groups and the overall dispatch.
#include <sycl/nd_range.hpp>
Public Member Functions
nd_range (range< Dimensions > globalSize, range< Dimensions > localSize, id< Dimensions > offset)
nd_range (range< Dimensions > globalSize, range< Dimensions > localSize)
range< Dimensions > get_global_range () const
range< Dimensions > get_local_range () const
range< Dimensions > get_group_range () const
id< Dimensions > get_offset () const
nd_range (const nd_range< Dimensions > &rhs)=default
nd_range (nd_range< Dimensions > &&rhs)=default
nd_range< Dimensions > & operator= (const nd_range< Dimensions > &rhs)=default
nd_range< Dimensions > & operator= (nd_range< Dimensions > &&rhs)=default
nd_range ()=default
bool operator== (const nd_range< Dimensions > &rhs) const
bool operator!= (const nd_range< Dimensions > &rhs) const
Static Public Attributes
static constexpr int dimensions = Dimensions
Detailed Description
template<int Dimensions = 1>
class sycl::_V1::nd_range< Dimensions >
Defines the iteration domain of both the work-groups and the overall dispatch.
Definition at line 22 of file nd_range.hpp.
Constructor & Destructor Documentation
nd_range() [1/5]
template<int Dimensions = 1> sycl::_V1::nd_range< Dimensions >::nd_range (range< Dimensions > globalSize, range< Dimensions > localSize, id< Dimensions > offset) inline
Definition at line 35 of file nd_range.hpp.
nd_range() [2/5]
template<int Dimensions = 1> sycl::_V1::nd_range< Dimensions >::nd_range (range< Dimensions > globalSize, range< Dimensions > localSize) inline
Definition at line 39 of file nd_range.hpp.
nd_range() [3/5]
template<int Dimensions = 1> sycl::_V1::nd_range< Dimensions >::nd_range (const nd_range< Dimensions > & rhs) default
nd_range() [4/5]
template<int Dimensions = 1> sycl::_V1::nd_range< Dimensions >::nd_range (nd_range< Dimensions > && rhs) default
nd_range() [5/5]
template<int Dimensions = 1> sycl::_V1::nd_range< Dimensions >::nd_range () default
Member Function Documentation
get_global_range()
template<int Dimensions = 1> range<Dimensions> sycl::_V1::nd_range< Dimensions >::get_global_range () const inline
Definition at line 43 of file nd_range.hpp.
Referenced by sycl::_V1::detail::NDRDescT::set(), syclcompat::detail::transform_nd_range(), and sycl::_V1::detail::writeNDRange().
get_group_range()
template<int Dimensions = 1> range<Dimensions> sycl::_V1::nd_range< Dimensions >::get_group_range () const inline
Definition at line 47 of file nd_range.hpp.
Referenced by sycl::_V1::detail::reduCGFuncMulti(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::range_basic >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run().
get_local_range()
template<int Dimensions = 1> range<Dimensions> sycl::_V1::nd_range< Dimensions >::get_local_range () const inline
Definition at line 45 of file nd_range.hpp.
Referenced by sycl::_V1::detail::reduCGFuncMulti(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::range_basic >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::local_mem_tree_and_atomic_cross_wg >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run(), sycl::_V1::detail::NDRDescT::set(), syclcompat::detail::transform_nd_range(), and sycl::_V1::detail::writeNDRange().
get_offset()
template<int Dimensions = 1> id<Dimensions> sycl::_V1::nd_range< Dimensions >::get_offset () const inline
Definition at line 50 of file nd_range.hpp.
Referenced by sycl::_V1::detail::NDRDescT::set(), and sycl::_V1::detail::writeNDRange().
operator!=()
template<int Dimensions = 1> bool sycl::_V1::nd_range< Dimensions >::operator!= (const nd_range< Dimensions > & rhs) const inline
Definition at line 65 of file nd_range.hpp.
operator=() [1/2]
template<int Dimensions = 1> nd_range<Dimensions>& sycl::_V1::nd_range< Dimensions >::operator= (const nd_range< Dimensions > & rhs) default
operator=() [2/2]
template<int Dimensions = 1> nd_range<Dimensions>& sycl::_V1::nd_range< Dimensions >::operator= (nd_range< Dimensions > && rhs) default
operator==()
template<int Dimensions = 1> bool sycl::_V1::nd_range< Dimensions >::operator== (const nd_range< Dimensions > & rhs) const inline
Definition at line 60 of file nd_range.hpp.
Member Data Documentation
dimensions
template<int Dimensions = 1> constexpr int sycl::_V1::nd_range< Dimensions >::dimensions = Dimensions static constexpr
Definition at line 24 of file nd_range.hpp.
The documentation for this class was generated from the following files:
include/sycl/ext/oneapi/experimental/uniform.hpp
include/sycl/nd_range.hpp