DPC++ Runtime: cl::sycl::kernel Class Reference
cl::sycl::kernel Class Reference
DPC++ User API
Provides an abstraction of a SYCL kernel.
#include <CL/sycl/kernel.hpp>
Public Member Functions
kernel (const kernel &RHS)=default
Constructs a SYCL kernel instance from an OpenCL cl_kernel.
kernel (kernel &&RHS)=default
kernel & operator= (const kernel &RHS)=default
kernel & operator= (kernel &&RHS)=default
bool operator== (const kernel &RHS) const
bool operator!= (const kernel &RHS) const
bool is_host () const
Get a valid OpenCL kernel handle.
context get_context () const
Get the context that this kernel is defined for.
backend get_backend () const noexcept
Returns the backend associated with this kernel.
kernel_bundle< bundle_state::executable > get_kernel_bundle () const
Get the kernel_bundle associated with this kernel.
template<info::kernel param>
info::param_traits< info::kernel, param >::return_type get_info () const
Get the program that this kernel is defined for.
template<info::kernel_device_specific param>
info::param_traits< info::kernel_device_specific, param >::return_type get_info (const device &Device) const
Query device-specific information from the kernel object using the info::kernel_device_specific descriptor.
template<info::kernel_device_specific param>
info::param_traits< info::kernel_device_specific, param >::return_type get_info (const device &Device, typename info::param_traits< info::kernel_device_specific, param >::input_type Value) const
Query device-specific information from a kernel using the info::kernel_device_specific descriptor for a specific device and value.
template<info::kernel_sub_group param>
__SYCL2020_DEPRECATED("get_work_group_info() is deprecated, use SYCL 2020 " "kernel_device_specific queries instead") typename info info::param_traits< info::kernel_sub_group, param >::return_type get_sub_group_info (const device &Device) const
Query work-group information from a kernel using the info::kernel_work_group descriptor for a specific device.
template<info::kernel_sub_group param>
info::param_traits< info::kernel_sub_group, param >::return_type get_sub_group_info (const device &Device, typename info::param_traits< info::kernel_sub_group, param >::input_type Value) const
Query sub-group information from a kernel using the info::kernel_sub_group descriptor for a specific device and value.
template<backend Backend>
backend_return_t< Backend, kernel > get_native () const
template<info::kernel_sub_group param>
info::param_traits< info::kernel_sub_group, param >::return_type get_sub_group_info (const device &dev) const
Friends
template<class T >
T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Detailed Description
Provides an abstraction of a SYCL kernel.
See also
sycl_api_exec
program
queue
Definition at line 67 of file kernel.hpp.
Constructor & Destructor Documentation
kernel() [1/2]
cl::sycl::kernel::kernel (const kernel & RHS) default
Constructs a SYCL kernel instance from an OpenCL cl_kernel.
The requirements for this constructor are described in section 4.3.1 of the SYCL specification.
Parameters
ClKernel is a valid OpenCL cl_kernel instance
SyclContext is a valid SYCL context
kernel() [2/2]
cl::sycl::kernel::kernel (kernel && RHS) default
Member Function Documentation
get_backend()
backend cl::sycl::kernel::get_backend () const noexcept
Returns the backend associated with this kernel.
Returns
the backend associated with this kernel.
Definition at line 33 of file kernel.cpp.
References cl::sycl::detail::getImplBackend().
get_context()
context cl::sycl::kernel::get_context () const
Get the context that this kernel is defined for.
The value returned must be equal to that returned by get_info<info::kernel::context>().
Returns
a valid SYCL context
Definition at line 29 of file kernel.cpp.
References cl::sycl::info::context.
get_info() [1/3]
template<info::kernel param> info::param_traits< info::kernel, param >::return_type cl::sycl::kernel::get_info
Get the program that this kernel is defined for.
The value returned must be equal to that returned by get_info<info::kernel::program>().
Returns
a valid SYCL program Query information from the kernel object using the info::kernel_info descriptor.
depends on information being queried.
Definition at line 47 of file kernel.cpp.
get_info() [2/3]
template<info::kernel_device_specific param> info::param_traits< info::kernel_device_specific, param >::return_type cl::sycl::kernel::get_info (const device & Device) const
Query device-specific information from the kernel object using the info::kernel_device_specific descriptor.
Parameters
Device is a valid SYCL device to query info for.
Returns
depends on information being queried.
Definition at line 61 of file kernel.cpp.
get_info() [3/3]
template<info::kernel_device_specific param> info::param_traits< info::kernel_device_specific, param >::return_type cl::sycl::kernel::get_info (const device & Device, typename info::param_traits< info::kernel_device_specific, param >::input_type Value) const
Query device-specific information from a kernel using the info::kernel_device_specific descriptor for a specific device and value.
Parameters
Device is a valid SYCL device.
Value depends on information being queried.
Returns
depends on information being queried.
Definition at line 67 of file kernel.cpp.
get_kernel_bundle()
kernel_bundle< sycl::bundle_state::executable > cl::sycl::kernel::get_kernel_bundle () const
Get the kernel_bundle associated with this kernel.
Returns
a valid kernel_bundle<bundle_state::executable>
Definition at line 36 of file kernel.cpp.
References cl::sycl::detail::createSyclObjFromImpl().
Referenced by cl::sycl::handler::parallel_for(), cl::sycl::handler::parallel_for_work_group(), and cl::sycl::handler::single_task().
get_native()
template<backend Backend> backend_return_t<Backend, kernel> cl::sycl::kernel::get_native () const inline
Definition at line 205 of file kernel.hpp.
get_sub_group_info() [1/3]
template<info::kernel_sub_group param> info::param_traits<info::kernel_sub_group, param>::return_type cl::sycl::kernel::get_sub_group_info (const device & dev) const
Definition at line 102 of file kernel.cpp.
get_sub_group_info() [2/3]
template<info::kernel_sub_group param> __SYCL2020_DEPRECATED ("get_work_group_info() is deprecated, use SYCL 2020 " "kernel_device_specific queries instead") typename info info::param_traits<info::kernel_sub_group, param>::return_type cl::sycl::kernel::get_sub_group_info (const device & Device) const
Query work-group information from a kernel using the info::kernel_work_group descriptor for a specific device.
Parameters
Device is a valid SYCL device.
Returns
depends on information being queried. Query sub-group information from a kernel using the info::kernel_sub_group descriptor for a specific device.
Parameters
Device is a valid SYCL device.
Returns
depends on information being queried.
get_sub_group_info() [3/3]
template<info::kernel_sub_group param> info::param_traits< info::kernel_sub_group, param >::return_type cl::sycl::kernel::get_sub_group_info (const device & Device, typename info::param_traits< info::kernel_sub_group, param >::input_type Value) const
Query sub-group information from a kernel using the info::kernel_sub_group descriptor for a specific device and value.
Parameters
Device is a valid SYCL device.
Value depends on information being queried.
Returns
depends on information being queried.
Definition at line 108 of file kernel.cpp.
is_host()
bool cl::sycl::kernel::is_host () const
Get a valid OpenCL kernel handle.
If this kernel encapsulates an instance of OpenCL kernel, a valid cl_kernel will be returned. If this kernel is a host kernel, an invalid_object_error exception will be thrown.
Returns
a valid cl_kernel instance Check if the associated SYCL context is a SYCL host context.
true if this SYCL kernel is a host kernel.
Definition at line 27 of file kernel.cpp.
operator!=()
bool cl::sycl::kernel::operator!= (const kernel & RHS) const inline
Definition at line 90 of file kernel.hpp.
References operator==().
operator=() [1/2]
kernel& cl::sycl::kernel::operator= (const kernel & RHS) default
operator=() [2/2]
kernel& cl::sycl::kernel::operator= (kernel && RHS) default
operator==()
bool cl::sycl::kernel::operator== (const kernel & RHS) const inline
Definition at line 88 of file kernel.hpp.
Friends And Related Function Documentation
detail::createSyclObjFromImpl
template<class T > T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
The documentation for this class was generated from the following files:
include/CL/sycl/kernel.hpp
source/kernel.cpp