DPC++ Runtime: sycl::_V1::detail::spec_constant_impl Class Reference
sycl::_V1::detail::spec_constant_impl Class Reference
#include <detail/spec_constant_impl.hpp>
Public Member Functions
spec_constant_impl ()=default
spec_constant_impl (size_t Size, const void *Val)
void set (size_t Size, const void *Val)
size_t getSize () const
const char * getValuePtr () const
bool isSet () const
Detailed Description
Definition at line 23 of file spec_constant_impl.hpp.
Constructor & Destructor Documentation
spec_constant_impl() [1/2]
sycl::_V1::detail::spec_constant_impl::spec_constant_impl () default
spec_constant_impl() [2/2]
sycl::_V1::detail::spec_constant_impl::spec_constant_impl (size_t Size, const void * Val) inline
Definition at line 27 of file spec_constant_impl.hpp.
References set().
Member Function Documentation
getSize()
size_t sycl::_V1::detail::spec_constant_impl::getSize () const inline
Definition at line 31 of file spec_constant_impl.hpp.
Referenced by sycl::_V1::detail::operator<<(), and sycl::_V1::detail::stableSerializeSpecConstRegistry().
getValuePtr()
const char* sycl::_V1::detail::spec_constant_impl::getValuePtr () const inline
Definition at line 32 of file spec_constant_impl.hpp.
Referenced by sycl::_V1::detail::program_impl::flush_spec_constants(), sycl::_V1::detail::operator<<(), and sycl::_V1::detail::stableSerializeSpecConstRegistry().
isSet()
bool sycl::_V1::detail::spec_constant_impl::isSet () const inline
Definition at line 33 of file spec_constant_impl.hpp.
Referenced by sycl::_V1::detail::program_impl::flush_spec_constants(), and sycl::_V1::detail::operator<<().
set()
void sycl::_V1::detail::spec_constant_impl::set (size_t Size, const void * Val)
Definition at line 23 of file spec_constant_impl.cpp.
Referenced by spec_constant_impl().
The documentation for this class was generated from the following files:
source/detail/spec_constant_impl.hpp
source/detail/spec_constant_impl.cpp