DPC++ Runtime: cl::sycl::detail::PersistentDeviceCodeCache Class Reference
cl::sycl::detail::PersistentDeviceCodeCache Class Reference
#include <detail/persistent_device_code_cache.hpp>
Static Public Member Functions
static std::string getCacheItemPath (const device &Device, const RTDeviceBinaryImage &Img, const SerializedObj &SpecConsts, const std::string &BuildOptionsString)
static std::vector< std::vector< char > > getItemFromDisc (const device &Device, const RTDeviceBinaryImage &Img, const SerializedObj &SpecConsts, const std::string &BuildOptionsString)
static void putItemToDisc (const device &Device, const RTDeviceBinaryImage &Img, const SerializedObj &SpecConsts, const std::string &BuildOptionsString, const RT::PiProgram &NativePrg)
static void trace (const std::string &msg)
Detailed Description
Definition at line 59 of file persistent_device_code_cache.hpp.
Member Function Documentation
getCacheItemPath()
std::string cl::sycl::detail::PersistentDeviceCodeCache::getCacheItemPath (const device & Device, const RTDeviceBinaryImage & Img, const SerializedObj & SpecConsts, const std::string & BuildOptionsString) static
Definition at line 318 of file persistent_device_code_cache.cpp.
References pi_device_binary_struct::BinaryStart, cl::sycl::detail::RTDeviceBinaryImage::getRawData(), cl::sycl::detail::pi::DeviceBinaryImage::getSize(), and trace().
Referenced by getItemFromDisc(), and putItemToDisc().
getItemFromDisc()
std::vector< std::vector< char > > cl::sycl::detail::PersistentDeviceCodeCache::getItemFromDisc (const device & Device, const RTDeviceBinaryImage & Img, const SerializedObj & SpecConsts, const std::string & BuildOptionsString) static
Definition at line 139 of file persistent_device_code_cache.cpp.
References getCacheItemPath(), cl::sycl::detail::LockCacheItem::isLocked(), cl::sycl::detail::OSUtil::isPathPresent(), and trace().
putItemToDisc()
void cl::sycl::detail::PersistentDeviceCodeCache::putItemToDisc (const device & Device, const RTDeviceBinaryImage & Img, const SerializedObj & SpecConsts, const std::string & BuildOptionsString, const RT::PiProgram & NativePrg) static
Definition at line 76 of file persistent_device_code_cache.cpp.
References getCacheItemPath(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::OSUtil::isPathPresent(), cl::sycl::detail::OSUtil::makeDir(), PI_PROGRAM_INFO_BINARIES, PI_PROGRAM_INFO_BINARY_SIZES, PI_PROGRAM_INFO_NUM_DEVICES, piProgramGetInfo(), and trace().
trace()
static void cl::sycl::detail::PersistentDeviceCodeCache::trace (const std::string & msg) inline static
Definition at line 188 of file persistent_device_code_cache.hpp.
References std::get().
Referenced by getCacheItemPath(), getItemFromDisc(), cl::sycl::detail::LockCacheItem::LockCacheItem(), cl::sycl::detail::parsePersistentCacheConfig(), putItemToDisc(), and cl::sycl::detail::LockCacheItem::~LockCacheItem().
The documentation for this class was generated from the following files:
source/detail/persistent_device_code_cache.hpp
source/detail/persistent_device_code_cache.cpp