DPC++ Runtime: cl::sycl::detail::OSUtil Class Reference
cl::sycl::detail::OSUtil Class Reference
Groups the OS-dependent services.
#include <CL/sycl/detail/os_util.hpp>
Static Public Member Functions
static OSModuleHandle getOSModuleHandle (const void *VirtAddr)
Returns a module enclosing given address or nullptr.
static std::string getCurrentDSODir ()
Returns an absolute path to a directory where the object was found.
static std::string getDirName (const char *Path)
Returns a directory component of a path.
static size_t getOSMemSize ()
Returns the amount of RAM available for the operating system.
static void * alignedAlloc (size_t Alignment, size_t NumBytes)
Allocates NumBytes bytes of uninitialized storage whose alignment is specified by Alignment.
static void alignedFree (void *Ptr)
Deallocates the memory referenced by Ptr.
static int makeDir (const char *Dir)
Make directory recursively and returns zero code on success.
static bool isPathPresent (const std::string &Path)
Checks if specified path is present.
Static Public Attributes
static constexpr OSModuleHandle ExeModuleHandle = -1
Module handle for the executable module - it is assumed there is always single one at most.
static constexpr OSModuleHandle DummyModuleHandle = -2
Dummy module handle to designate non-existing module for a device binary image loaded from file e.g.
static constexpr const char * DirSep = "/"
Detailed Description
Groups the OS-dependent services.
Definition at line 51 of file os_util.hpp.
Member Function Documentation
alignedAlloc()
void * cl::sycl::detail::OSUtil::alignedAlloc (size_t Alignment, size_t NumBytes) static
Allocates NumBytes bytes of uninitialized storage whose alignment is specified by Alignment.
Definition at line 255 of file os_util.cpp.
References cl::sycl::aligned_alloc().
alignedFree()
void cl::sycl::detail::OSUtil::alignedFree (void * Ptr) static
Deallocates the memory referenced by Ptr.
Definition at line 268 of file os_util.cpp.
References cl::sycl::detail::usm::free().
getCurrentDSODir()
static std::string cl::sycl::detail::OSUtil::getCurrentDSODir () static
Returns an absolute path to a directory where the object was found.
getDirName()
static std::string cl::sycl::detail::OSUtil::getDirName (const char * Path) static
Returns a directory component of a path.
getOSMemSize()
size_t cl::sycl::detail::OSUtil::getOSMemSize () static
Returns the amount of RAM available for the operating system.
Definition at line 238 of file os_util.cpp.
getOSModuleHandle()
static OSModuleHandle cl::sycl::detail::OSUtil::getOSModuleHandle (const void * VirtAddr) static
Returns a module enclosing given address or nullptr.
isPathPresent()
static bool cl::sycl::detail::OSUtil::isPathPresent (const std::string & Path) inline static
Checks if specified path is present.
Definition at line 90 of file os_util.hpp.
Referenced by cl::sycl::detail::PersistentDeviceCodeCache::getItemFromDisc(), and cl::sycl::detail::PersistentDeviceCodeCache::putItemToDisc().
makeDir()
int cl::sycl::detail::OSUtil::makeDir (const char * Dir) static
Make directory recursively and returns zero code on success.
Definition at line 280 of file os_util.cpp.
Referenced by cl::sycl::detail::PersistentDeviceCodeCache::putItemToDisc().
Member Data Documentation
DirSep
constexpr const char* cl::sycl::detail::OSUtil::DirSep = "/" static constexpr
Definition at line 73 of file os_util.hpp.
DummyModuleHandle
constexpr OSModuleHandle cl::sycl::detail::OSUtil::DummyModuleHandle = -2 static constexpr
Dummy module handle to designate non-existing module for a device binary image loaded from file e.g.
via SYCL_USE_KERNEL_SPV env var.
Definition at line 68 of file os_util.hpp.
ExeModuleHandle
constexpr OSModuleHandle cl::sycl::detail::OSUtil::ExeModuleHandle = -1 static constexpr
Module handle for the executable module - it is assumed there is always single one at most.
Definition at line 64 of file os_util.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/detail/os_util.hpp
source/detail/os_util.cpp