DPC++ Runtime: sycl::_V1::detail::ByteArray Class Reference
sycl::_V1::detail::ByteArray Class Reference
#include <detail/device_binary_image.hpp>
Public Types
using ConstIterator = const std::uint8_t *
Public Member Functions
ByteArray (const std::uint8_t *Ptr, std::size_t Size)
const std::uint8_t & operator[] (std::size_t Idx) const
std::size_t size () const
ConstIterator begin () const
ConstIterator end () const
template<typename... Ts>
auto consume ()
void dropBytes (std::size_t Bytes)
template<typename T >
void drop ()
bool empty () const
Detailed Description
Definition at line 23 of file device_binary_image.hpp.
Member Typedef Documentation
ConstIterator
using sycl::_V1::detail::ByteArray::ConstIterator = const std::uint8_t *
Definition at line 25 of file device_binary_image.hpp.
Constructor & Destructor Documentation
ByteArray()
sycl::_V1::detail::ByteArray::ByteArray (const std::uint8_t * Ptr, std::size_t Size) inline
Definition at line 27 of file device_binary_image.hpp.
Member Function Documentation
begin()
ConstIterator sycl::_V1::detail::ByteArray::begin () const inline
Definition at line 30 of file device_binary_image.hpp.
Referenced by sycl::_V1::detail::device_image_impl::get_specialization_constant_raw_value(), and sycl::_V1::detail::device_image_impl::set_specialization_constant_raw_value().
consume()
template<typename... Ts> auto sycl::_V1::detail::ByteArray::consume () inline
Definition at line 33 of file device_binary_image.hpp.
Referenced by sycl::_V1::detail::ProgramManager::addImages(), sycl::_V1::detail::checkDevSupportDeviceRequirements(), and sycl::_V1::detail::program_impl::flush_spec_constants().
drop()
template<typename T > void sycl::_V1::detail::ByteArray::drop () inline
Definition at line 46 of file device_binary_image.hpp.
References dropBytes().
dropBytes()
void sycl::_V1::detail::ByteArray::dropBytes (std::size_t Bytes) inline
Definition at line 40 of file device_binary_image.hpp.
Referenced by sycl::_V1::detail::ProgramManager::addImages(), sycl::_V1::detail::checkDevSupportDeviceRequirements(), drop(), and sycl::_V1::detail::program_impl::flush_spec_constants().
empty()
bool sycl::_V1::detail::ByteArray::empty () const inline
Definition at line 48 of file device_binary_image.hpp.
Referenced by sycl::_V1::detail::ProgramManager::addImages(), sycl::_V1::detail::checkDevSupportDeviceRequirements(), and sycl::_V1::detail::program_impl::flush_spec_constants().
end()
ConstIterator sycl::_V1::detail::ByteArray::end () const inline
Definition at line 31 of file device_binary_image.hpp.
operator[]()
const std::uint8_t& sycl::_V1::detail::ByteArray::operator[] (std::size_t Idx) const inline
Definition at line 28 of file device_binary_image.hpp.
size()
std::size_t sycl::_V1::detail::ByteArray::size () const inline
Definition at line 29 of file device_binary_image.hpp.
Referenced by sycl::_V1::detail::device_image_impl::get_specialization_constant_raw_value(), and sycl::_V1::detail::device_image_impl::set_specialization_constant_raw_value().
The documentation for this class was generated from the following file:
source/detail/device_binary_image.hpp