DPC++ Runtime: syclcompat::detail::host_buffer Class Reference
syclcompat::detail::host_buffer Class Reference
#include <syclcompat/memory.hpp>
Public Member Functions
host_buffer (size_t size, sycl::queue q, const std::vector< sycl::event > &deps)
void * get_ptr () const
size_t get_size () const
~host_buffer ()
Detailed Description
Definition at line 334 of file memory.hpp.
Constructor & Destructor Documentation
host_buffer()
syclcompat::detail::host_buffer::host_buffer (size_t size, sycl::queue q, const std::vector< sycl::event > & deps) inline
Definition at line 341 of file memory.hpp.
~host_buffer()
syclcompat::detail::host_buffer::~host_buffer () inline
Definition at line 345 of file memory.hpp.
References sycl::_V1::handler::depends_on(), syclcompat::free(), sycl::_V1::handler::host_task(), and sycl::_V1::queue::submit().
Member Function Documentation
get_ptr()
void* syclcompat::detail::host_buffer::get_ptr () const inline
Definition at line 343 of file memory.hpp.
Referenced by syclcompat::experimental::detail::memcpy().
get_size()
size_t syclcompat::detail::host_buffer::get_size () const inline
Definition at line 344 of file memory.hpp.
The documentation for this class was generated from the following file:
include/syclcompat/memory.hpp