DPC++ Runtime: sycl::_V1::handler Class Reference
sycl::_V1::handler Class Reference
DPC++ User API
Command group handler class.
#include <sycl/handler.hpp>
Classes
struct ShouldEnableSetArg
Public Types
template<typename T >
using remove_cv_ref_t = typename std::remove_cv_t< std::remove_reference_t< T > >
template<typename U , typename T >
using is_same_type = std::is_same< remove_cv_ref_t< U >, remove_cv_ref_t< T > >
Public Member Functions
handler (const handler &)=delete
handler (handler &&)=delete
handler & operator= (const handler &)=delete
handler & operator= (handler &&)=delete
template<auto & SpecName>
void set_specialization_constant (typename std::remove_reference_t< decltype(SpecName)>::value_type Value)
template<auto & SpecName>
std::remove_reference_t< decltype(SpecName)>::value_type get_specialization_constant () const
void use_kernel_bundle (const kernel_bundle< bundle_state::executable > &ExecBundle)
template<typename DataT , int Dims, access::mode AccMode, access::target AccTarget, access::placeholder isPlaceholder>
void require (accessor< DataT, Dims, AccMode, AccTarget, isPlaceholder > Acc)
Requires access to the memory object associated with the placeholder accessor.
template<typename DataT , int Dims, access::mode AccMode, access::target AccTarget, access::placeholder isPlaceholder>
void require (ext::oneapi::experimental::dynamic_parameter< accessor< DataT, Dims, AccMode, AccTarget, isPlaceholder >> dynamicParamAcc)
Requires access to the memory object associated with the placeholder accessor contained in a dynamic_parameter object.
void depends_on (event Event)
Registers event dependencies on this command group.
void depends_on (const std::vector< event > &Events)
Registers event dependencies on this command group.
template<typename T >
std::enable_if_t< ShouldEnableSetArg< T >::value, void > set_arg (int ArgIndex, T &&Arg)
Sets argument for OpenCL interoperability kernels.
template<typename DataT , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder>
void set_arg (int ArgIndex, accessor< DataT, Dims, AccessMode, AccessTarget, IsPlaceholder > Arg)
template<typename DataT , int Dims>
void set_arg (int ArgIndex, local_accessor< DataT, Dims > Arg)
template<typename T >
void set_arg (int argIndex, ext::oneapi::experimental::dynamic_parameter< T > &dynamicParam)
template<typename... Ts>
void set_args (Ts &&...Args)
Sets arguments for OpenCL interoperability kernels.
template<typename KernelName = detail::auto_name, typename KernelType >
void single_task (_KERNELFUNCPARAM(KernelFunc))
Defines and invokes a SYCL kernel function as a function object type.
template<typename KernelName = detail::auto_name, typename KernelType >
void parallel_for (range< 1 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc))
template<typename KernelName = detail::auto_name, typename KernelType >
void parallel_for (range< 2 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc))
template<typename KernelName = detail::auto_name, typename KernelType >
void parallel_for (range< 3 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc))
template<typename FuncT >
std::enable_if_t< detail::check_fn_signature< std::remove_reference_t< FuncT >, void()>::value||detail::check_fn_signature< std::remove_reference_t< FuncT >, void(interop_handle)>::value > host_task (FuncT &&Func)
Enqueues a command to the SYCL runtime to invoke Func once.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
void parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, _KERNELFUNCPARAM(KernelFunc))
Defines and invokes a SYCL kernel function for the specified range and offset.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
void parallel_for_work_group (range< Dims > NumWorkGroups, _KERNELFUNCPARAM(KernelFunc))
Hierarchical kernel invocation method of a kernel defined as a lambda encoding the body of each work-group to launch.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
void parallel_for_work_group (range< Dims > NumWorkGroups, range< Dims > WorkGroupSize, _KERNELFUNCPARAM(KernelFunc))
Hierarchical kernel invocation method of a kernel defined as a lambda encoding the body of each work-group to launch.
void single_task (kernel Kernel)
Invokes a SYCL kernel.
void parallel_for (range< 1 > NumWorkItems, kernel Kernel)
void parallel_for (range< 2 > NumWorkItems, kernel Kernel)
void parallel_for (range< 3 > NumWorkItems, kernel Kernel)
template<int Dims>
void parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, kernel Kernel)
Defines and invokes a SYCL kernel function for the specified range and offsets.
template<int Dims>
void parallel_for (nd_range< Dims > NDRange, kernel Kernel)
Defines and invokes a SYCL kernel function for the specified range and offsets.
template<typename KernelName = detail::auto_name, typename KernelType >
void single_task (kernel Kernel, _KERNELFUNCPARAM(KernelFunc))
Defines and invokes a SYCL kernel function.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
void parallel_for (kernel Kernel, range< Dims > NumWorkItems, _KERNELFUNCPARAM(KernelFunc))
Defines and invokes a SYCL kernel function for the specified range.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
void parallel_for (kernel Kernel, range< Dims > NumWorkItems, id< Dims > WorkItemOffset, _KERNELFUNCPARAM(KernelFunc))
Defines and invokes a SYCL kernel function for the specified range and offsets.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
void parallel_for (kernel Kernel, nd_range< Dims > NDRange, _KERNELFUNCPARAM(KernelFunc))
Defines and invokes a SYCL kernel function for the specified range and offsets.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
void parallel_for_work_group (kernel Kernel, range< Dims > NumWorkGroups, _KERNELFUNCPARAM(KernelFunc))
Hierarchical kernel invocation method of a kernel.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
void parallel_for_work_group (kernel Kernel, range< Dims > NumWorkGroups, range< Dims > WorkGroupSize, _KERNELFUNCPARAM(KernelFunc))
Hierarchical kernel invocation method of a kernel.
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT >
std::enable_if_t< ext::oneapi::experimental::is_property_list< PropertiesT >::value > single_task (PropertiesT Props, _KERNELFUNCPARAM(KernelFunc))
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT >
std::enable_if_t< ext::oneapi::experimental::is_property_list< PropertiesT >::value > parallel_for (range< 1 > NumWorkItems, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc))
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT >
std::enable_if_t< ext::oneapi::experimental::is_property_list< PropertiesT >::value > parallel_for (range< 2 > NumWorkItems, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc))
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT >
std::enable_if_t< ext::oneapi::experimental::is_property_list< PropertiesT >::value > parallel_for (range< 3 > NumWorkItems, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc))
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT , int Dims>
std::enable_if_t< ext::oneapi::experimental::is_property_list< PropertiesT >::value > parallel_for (nd_range< Dims > Range, PropertiesT Properties, _KERNELFUNCPARAM(KernelFunc))
class detail::queue_impl
template<typename DataT , int Dims, access::mode AccMode, access::target AccTarget, access::placeholder isPlaceholder, typename PropertyListT >
class accessor
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder>
class detail::image_accessor
class stream
class detail::stream_impl
template<typename T , class BinaryOperation , int Dims, size_t Extent, bool ExplicitIdentity, typename RedOutVar >
class detail::reduction_impl_algo
class ::MockHandler
template<class _name , class _dataT , int32_t _min_capacity, class _propertiesT , class >
class ext::intel::experimental::pipe
class ext::oneapi::experimental::detail::graph_impl
class ext::oneapi::experimental::detail::dynamic_parameter_impl
device detail::getDeviceFromHandler (handler &)
void detail::reduction::finalizeHandler (handler &CGH)
template<class FunctorTy >
void detail::reduction::withAuxHandler (handler &CGH, FunctorTy Func)
template<typename KernelName , detail::reduction::strategy Strategy, int Dims, typename PropertiesT , typename... RestT>
void detail::reduction_parallel_for (handler &CGH, range< Dims > NDRange, PropertiesT Properties, RestT... Rest)
template<typename KernelName , detail::reduction::strategy Strategy, int Dims, typename PropertiesT , typename... RestT>
void detail::reduction_parallel_for (handler &CGH, nd_range< Dims > NDRange, PropertiesT Properties, RestT... Rest)
void detail::associateWithHandler (handler &, detail::AccessorBaseHost *, access::target)
void detail::associateWithHandler (handler &, detail::UnsampledImageAccessorBaseHost *, image_target)
void detail::associateWithHandler (handler &, detail::SampledImageAccessorBaseHost *, image_target)
template<typename KernelName = detail::auto_name, typename PropertiesT , typename... RestT>
std::enable_if_t<(sizeof...(RestT) > 1) &&detail::AreAllButLastReductions< RestT... >::value &&ext::oneapi::experimental::is_property_list< PropertiesT >::value > parallel_for (range< 1 > Range, PropertiesT Properties, RestT &&...Rest)
Reductions.
template<typename KernelName = detail::auto_name, typename PropertiesT , typename... RestT>
std::enable_if_t<(sizeof...(RestT) > 1) &&detail::AreAllButLastReductions< RestT... >::value &&ext::oneapi::experimental::is_property_list< PropertiesT >::value > parallel_for (range< 2 > Range, PropertiesT Properties, RestT &&...Rest)
template<typename KernelName = detail::auto_name, typename PropertiesT , typename... RestT>
std::enable_if_t<(sizeof...(RestT) > 1) &&detail::AreAllButLastReductions< RestT... >::value &&ext::oneapi::experimental::is_property_list< PropertiesT >::value > parallel_for (range< 3 > Range, PropertiesT Properties, RestT &&...Rest)
template<typename KernelName = detail::auto_name, typename... RestT>
std::enable_if_t< detail::AreAllButLastReductions< RestT... >::value > parallel_for (range< 1 > Range, RestT &&...Rest)
template<typename KernelName = detail::auto_name, typename... RestT>
std::enable_if_t< detail::AreAllButLastReductions< RestT... >::value > parallel_for (range< 2 > Range, RestT &&...Rest)
template<typename KernelName = detail::auto_name, typename... RestT>
std::enable_if_t< detail::AreAllButLastReductions< RestT... >::value > parallel_for (range< 3 > Range, RestT &&...Rest)
template<typename KernelName = detail::auto_name, int Dims, typename PropertiesT , typename... RestT>
std::enable_if_t<(sizeof...(RestT) > 1) &&detail::AreAllButLastReductions< RestT... >::value &&ext::oneapi::experimental::is_property_list< PropertiesT >::value > parallel_for (nd_range< Dims > Range, PropertiesT Properties, RestT &&...Rest)
template<typename KernelName = detail::auto_name, int Dims, typename... RestT>
std::enable_if_t< detail::AreAllButLastReductions< RestT... >::value > parallel_for (nd_range< Dims > Range, RestT &&...Rest)
template<typename KernelName = detail::auto_name, typename KernelType , int Dims, typename PropertiesT >
void parallel_for_work_group (range< Dims > NumWorkGroups, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc))
}@
template<typename KernelName = detail::auto_name, typename KernelType , int Dims, typename PropertiesT >
void parallel_for_work_group (range< Dims > NumWorkGroups, range< Dims > WorkGroupSize, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc))
template<typename T_Src , typename T_Dst , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t>
void copy (accessor< T_Src, Dims, AccessMode, AccessTarget, IsPlaceholder > Src, std::shared_ptr< T_Dst > Dst)
Copies the content of memory object accessed by Src into the memory pointed by Dst.
template<typename T_Src , typename T_Dst , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t>
void copy (std::shared_ptr< T_Src > Src, accessor< T_Dst, Dims, AccessMode, AccessTarget, IsPlaceholder > Dst)
Copies the content of memory pointed by Src into the memory object accessed by Dst.
template<typename T_Src , typename T_Dst , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t>
void copy (accessor< T_Src, Dims, AccessMode, AccessTarget, IsPlaceholder > Src, T_Dst *Dst)
Copies the content of memory object accessed by Src into the memory pointed by Dst.
template<typename T_Src , typename T_Dst , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t>
void copy (const T_Src *Src, accessor< T_Dst, Dims, AccessMode, AccessTarget, IsPlaceholder > Dst)
Copies the content of memory pointed by Src into the memory object accessed by Dst.
template<typename T_Src , int Dims_Src, access::mode AccessMode_Src, access::target AccessTarget_Src, typename T_Dst , int Dims_Dst, access::mode AccessMode_Dst, access::target AccessTarget_Dst, access::placeholder IsPlaceholder_Src = access::placeholder::false_t, access::placeholder IsPlaceholder_Dst = access::placeholder::false_t>
void copy (accessor< T_Src, Dims_Src, AccessMode_Src, AccessTarget_Src, IsPlaceholder_Src > Src, accessor< T_Dst, Dims_Dst, AccessMode_Dst, AccessTarget_Dst, IsPlaceholder_Dst > Dst)
Copies the content of memory object accessed by Src to the memory object accessed by Dst.
template<typename T , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t>
void update_host (accessor< T, Dims, AccessMode, AccessTarget, IsPlaceholder > Acc)
Provides guarantees that the memory object accessed via Acc is updated on the host after command group object execution is complete.
template<typename T , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t, typename PropertyListT = property_list>
void fill (accessor< T, Dims, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > Dst, const T &Pattern)
Fills memory pointed by accessor with the pattern given.
template<typename T >
void fill (void *Ptr, const T &Pattern, size_t Count)
Fills the specified memory with the specified pattern.
void ext_oneapi_barrier ()
Prevents any commands submitted afterward to this queue from executing until all commands previously submitted to this queue have entered the complete state.
void ext_oneapi_barrier (const std::vector< event > &WaitList)
Prevents any commands submitted afterward to this queue from executing until all events in WaitList have entered the complete state.
void memcpy (void *Dest, const void *Src, size_t Count)
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on this handler's device.
template<typename T >
void copy (const T *Src, T *Dest, size_t Count)
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on this handler's device.
void memset (void *Dest, int Value, size_t Count)
Fills the memory pointed by a USM pointer with the value specified.
void prefetch (const void *Ptr, size_t Count)
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
void mem_advise (const void *Ptr, size_t Length, int Advice)
Provides additional information to the underlying runtime about how different allocations are used.
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>>
void ext_oneapi_memcpy2d (void *Dest, size_t DestPitch, const void *Src, size_t SrcPitch, size_t Width, size_t Height)
Copies data from one 2D memory region to another, both pointed by USM pointers.
template<typename T >
void ext_oneapi_copy2d (const T *Src, size_t SrcPitch, T *Dest, size_t DestPitch, size_t Width, size_t Height)
Copies data from one 2D memory region to another, both pointed by USM pointers.
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>>
void ext_oneapi_memset2d (void *Dest, size_t DestPitch, int Value, size_t Width, size_t Height)
Fills the memory pointed by a USM pointer with the value specified.
template<typename T >
void ext_oneapi_fill2d (void *Dest, size_t DestPitch, const T &Pattern, size_t Width, size_t Height)
Fills the memory pointed by a USM pointer with the value specified.
template<typename T , typename PropertyListT >
void memcpy (ext::oneapi::experimental::device_global< T, PropertyListT > &Dest, const void *Src, size_t NumBytes=sizeof(T), size_t DestOffset=0)
Copies data from a USM memory region to a device_global.
template<typename T , typename PropertyListT >
void memcpy (void *Dest, const ext::oneapi::experimental::device_global< T, PropertyListT > &Src, size_t NumBytes=sizeof(T), size_t SrcOffset=0)
Copies data from a device_global to USM memory.
template<typename T , typename PropertyListT >
void copy (const std::remove_all_extents_t< T > *Src, ext::oneapi::experimental::device_global< T, PropertyListT > &Dest, size_t Count=sizeof(T)/sizeof(std::remove_all_extents_t< T >), size_t StartIndex=0)
Copies elements of type std::remove_all_extents_t<T> from a USM memory region to a device_global.
template<typename T , typename PropertyListT >
void copy (const ext::oneapi::experimental::device_global< T, PropertyListT > &Src, std::remove_all_extents_t< T > *Dest, size_t Count=sizeof(T)/sizeof(std::remove_all_extents_t< T >), size_t StartIndex=0)
Copies elements of type std::remove_all_extents_t<T> from a device_global to a USM memory region.
void ext_oneapi_graph (ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::executable > Graph)
Executes a command_graph.
void ext_oneapi_copy (void *Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor &DestImgDesc)
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
void ext_oneapi_copy (void *Src, sycl::range< 3 > SrcOffset, sycl::range< 3 > SrcExtent, ext::oneapi::experimental::image_mem_handle Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor &DestImgDesc, sycl::range< 3 > CopyExtent)
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
void ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, void *Dest, const ext::oneapi::experimental::image_descriptor &SrcImgDesc)
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
void ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, sycl::range< 3 > SrcOffset, const ext::oneapi::experimental::image_descriptor &SrcImgDesc, void *Dest, sycl::range< 3 > DestOffset, sycl::range< 3 > DestExtent, sycl::range< 3 > CopyExtent)
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
void ext_oneapi_copy (void *Src, void *Dest, const ext::oneapi::experimental::image_descriptor &DeviceImgDesc, size_t DeviceRowPitch)
Copies data from one memory region to another, where Src and Dest are USM pointers.
void ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor &ImageDesc)
Copies data from device to device memory, where Src and Dest are opaque image memory handles.
void ext_oneapi_copy (void *Src, sycl::range< 3 > SrcOffset, void *Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor &DeviceImgDesc, size_t DeviceRowPitch, sycl::range< 3 > HostExtent, sycl::range< 3 > CopyExtent)
Copies data from one memory region to another, where Src and Dest are USM pointers.
void ext_oneapi_wait_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle)
Instruct the queue with a non-blocking wait on an external semaphore.
void ext_oneapi_signal_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle)
Instruct the queue to signal the external semaphore once all previous commands have completed execution.
Detailed Description
Command group handler class.
Objects of the handler class collect information about command group, such as kernel, requirements to the memory, arguments for the kernel.
sycl::queue::submit([](handler &CGH){
  CGH.require(Accessor1);   // Adds a requirement to the memory object.
  CGH.setArg(0, Accessor2); // Registers accessor given as an argument to
                            // the kernel + adds a requirement to the memory
                            // object.
  CGH.setArg(1, N);         // Registers value given as an argument to the
                            // kernel.
  // The following registers KernelFunctor to be a kernel that will be
  // executed in case of queue is bound to the host device, Kernel - for
  // an OpenCL device. This function clearly indicates that command group
  // represents kernel execution.
  CGH.parallel_for(KernelFunctor, Kernel);
 });
The command group can represent absolutely different operations. Depending on the operation we need to store different data. But, in most cases, it's impossible to say what kind of operation we need to perform until the very end. So, handler class contains all fields simultaneously, then during "finalization" it constructs CG object, that represents specific operation, passing fields that are required only.
See also
queue
program
kernel
Definition at line 461 of file handler.hpp.
Member Typedef Documentation
is_same_type
template<typename U , typename T > using sycl::_V1::handler::is_same_type = std::is_same<remove_cv_ref_t<U>, remove_cv_ref_t<T> >
Definition at line 1948 of file handler.hpp.
remove_cv_ref_t
template<typename T > using sycl::_V1::handler::remove_cv_ref_t = typename std::remove_cv_t<std::remove_reference_t<T> >
Definition at line 1945 of file handler.hpp.
Constructor & Destructor Documentation
handler() [1/2]
sycl::_V1::handler::handler (const handler &) delete
handler() [2/2]
sycl::_V1::handler::handler (handler &&) delete
Member Function Documentation
copy() [1/8]
template<typename T_Src , typename T_Dst , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t> void sycl::_V1::handler::copy (accessor< T_Src, Dims, AccessMode, AccessTarget, IsPlaceholder > Src, std::shared_ptr< T_Dst > Dst) inline
Copies the content of memory object accessed by Src into the memory pointed by Dst.
Source must have at least as many bytes as the range accessed by Dst.
Parameters
Src is a source SYCL accessor.
Dst is a smart pointer to destination memory.
Definition at line 2597 of file handler.hpp.
References sycl::_V1::AccessMode.
Referenced by sycl::_V1::queue::copy(), sycl::_V1::ext::oneapi::experimental::copy(), and sycl::_V1::detail::reduction_impl_algo< T, BinaryOperation, Dims, Extent, ExplicitIdentity, RedOutVar >::withInitializedMem().
copy() [2/8]
template<typename T_Src , typename T_Dst , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t> void sycl::_V1::handler::copy (accessor< T_Src, Dims, AccessMode, AccessTarget, IsPlaceholder > Src, T_Dst * Dst) inline
Copies the content of memory object accessed by Src into the memory pointed by Dst.
Source must have at least as many bytes as the range accessed by Dst.
Parameters
Src is a source SYCL accessor.
Dst is a pointer to destination memory.
Definition at line 2654 of file handler.hpp.
References sycl::_V1::AccessMode, sycl::_V1::detail::CG::CopyAccToPtr, and sycl::_V1::detail::getSyclObjImpl().
copy() [3/8]
template<typename T_Src , int Dims_Src, access::mode AccessMode_Src, access::target AccessTarget_Src, typename T_Dst , int Dims_Dst, access::mode AccessMode_Dst, access::target AccessTarget_Dst, access::placeholder IsPlaceholder_Src = access::placeholder::false_t, access::placeholder IsPlaceholder_Dst = access::placeholder::false_t> void sycl::_V1::handler::copy (accessor< T_Src, Dims_Src, AccessMode_Src, AccessTarget_Src, IsPlaceholder_Src > Src, accessor< T_Dst, Dims_Dst, AccessMode_Dst, AccessTarget_Dst, IsPlaceholder_Dst > Dst) inline
Copies the content of memory object accessed by Src to the memory object accessed by Dst.
Dst must have at least as many bytes as the range accessed by Src.
Parameters
Src is a source SYCL accessor.
Dst is a destination SYCL accessor.
Definition at line 2742 of file handler.hpp.
References sycl::_V1::detail::CG::CopyAccToAcc, and sycl::_V1::detail::getSyclObjImpl().
copy() [4/8]
template<typename T , typename PropertyListT > void sycl::_V1::handler::copy (const ext::oneapi::experimental::device_global< T, PropertyListT > & Src, std::remove_all_extents_t< T > * Dest, size_t Count = sizeof(T) / sizeof(std::remove_all_extents_t<T>), size_t StartIndex = 0) inline
Copies elements of type std::remove_all_extents_t<T> from a device_global to a USM memory region.
Throws an exception if the copy operation intends to write outside the memory range Src, as specified through Count and StartIndex.
Parameters
Src is the source device_global.
Dest is a USM pointer to copy to.
Count is a number of elements to copy.
StartIndex is the index of the first element in Src to copy from.
Definition at line 3117 of file handler.hpp.
copy() [5/8]
template<typename T , typename PropertyListT > void sycl::_V1::handler::copy (const std::remove_all_extents_t< T > * Src, ext::oneapi::experimental::device_global< T, PropertyListT > & Dest, size_t Count = sizeof(T) / sizeof(std::remove_all_extents_t<T>), size_t StartIndex = 0) inline
Copies elements of type std::remove_all_extents_t<T> from a USM memory region to a device_global.
Throws an exception if the copy operation intends to write outside the memory range Dest, as specified through Count and StartIndex.
Parameters
Src is a USM pointer to the source memory.
Dest is the destination device_glboal.
Count is a number of elements to copy.
StartIndex is the index of the first element in Dest to copy to.
Definition at line 3097 of file handler.hpp.
copy() [6/8]
template<typename T > void sycl::_V1::handler::copy (const T * Src, T * Dest, size_t Count) inline
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on this handler's device.
No operations is done if Count is zero. An exception is thrown if either Dest or Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Parameters
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
Count is a number of elements of type T to copy.
Definition at line 2916 of file handler.hpp.
copy() [7/8]
template<typename T_Src , typename T_Dst , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t> void sycl::_V1::handler::copy (const T_Src * Src, accessor< T_Dst, Dims, AccessMode, AccessTarget, IsPlaceholder > Dst) inline
Copies the content of memory pointed by Src into the memory object accessed by Dst.
Source must have at least as many bytes as the range accessed by Dst.
Parameters
Src is a pointer to source memory.
Dst is a destination SYCL accessor.
Definition at line 2696 of file handler.hpp.
References sycl::_V1::AccessMode, sycl::_V1::detail::CG::CopyPtrToAcc, and sycl::_V1::detail::getSyclObjImpl().
copy() [8/8]
template<typename T_Src , typename T_Dst , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t> void sycl::_V1::handler::copy (std::shared_ptr< T_Src > Src, accessor< T_Dst, Dims, AccessMode, AccessTarget, IsPlaceholder > Dst) inline
Copies the content of memory pointed by Src into the memory object accessed by Dst.
Source must have at least as many bytes as the range accessed by Dst.
Parameters
Src is a smart pointer to source memory.
Dst is a destination SYCL accessor.
Definition at line 2625 of file handler.hpp.
References sycl::_V1::AccessMode.
depends_on() [1/2]
void sycl::_V1::handler::depends_on (const std::vector< event > & Events)
Registers event dependencies on this command group.
Parameters
Events is a vector of valid SYCL events to wait on.
Definition at line 1461 of file handler.cpp.
References depends_on().
depends_on() [2/2]
void sycl::_V1::handler::depends_on (event Event)
Registers event dependencies on this command group.
Parameters
Event is a valid SYCL event to wait on.
Definition at line 1439 of file handler.cpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::invalid, and sycl::_V1::make_error_code().
Referenced by syclcompat::detail::combine_events(), depends_on(), sycl::_V1::queue::ext_oneapi_copy(), sycl::_V1::queue::ext_oneapi_copy2d(), sycl::_V1::queue::ext_oneapi_fill2d(), sycl::_V1::queue::ext_oneapi_graph(), sycl::_V1::queue::ext_oneapi_memcpy2d(), sycl::_V1::queue::ext_oneapi_memset2d(), sycl::_V1::queue::ext_oneapi_signal_external_semaphore(), sycl::_V1::queue::ext_oneapi_wait_external_semaphore(), sycl::_V1::queue::fill(), sycl::_V1::detail::reduction_impl_algo< T, BinaryOperation, Dims, Extent, ExplicitIdentity, RedOutVar >::getGroupsCounterAccDiscrete(), sycl::_V1::queue::memcpy(), sycl::_V1::queue::parallel_for(), sycl::_V1::queue::parallel_for_impl(), sycl::_V1::queue::prefetch(), sycl::_V1::queue::single_task(), sycl::_V1::detail::queue_impl::submitWithHandler(), and sycl::_V1::detail::reduction::withAuxHandler().
ext_oneapi_barrier() [1/2]
void sycl::_V1::handler::ext_oneapi_barrier () inline
Prevents any commands submitted afterward to this queue from executing until all commands previously submitted to this queue have entered the complete state.
Definition at line 2881 of file handler.hpp.
References sycl::_V1::detail::CG::Barrier.
Referenced by sycl::_V1::ext::oneapi::experimental::barrier(), sycl::_V1::queue::ext_oneapi_submit_barrier(), and sycl::_V1::ext::oneapi::experimental::partial_barrier().
ext_oneapi_barrier() [2/2]
void sycl::_V1::handler::ext_oneapi_barrier (const std::vector< event > & WaitList)
Prevents any commands submitted afterward to this queue from executing until all events in WaitList have entered the complete state.
If WaitList is empty, then the barrier has no effect.
Parameters
WaitList is a vector of valid SYCL events that need to complete before barrier command can be executed.
Definition at line 923 of file handler.cpp.
References sycl::_V1::detail::CG::BarrierWaitlist.
ext_oneapi_copy() [1/7]
void sycl::_V1::handler::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor & ImageDesc)
Copies data from device to device memory, where Src and Dest are opaque image memory handles.
An exception is thrown if either Src or Dest is incomplete
Parameters
Src is an opaque image memory handle to the source memory.
Dest is an opaque image memory handle to the destination memory.
ImageDesc is the source image descriptor
Definition at line 1182 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::array_size, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_order, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::convertChannelType(), sycl::_V1::detail::CG::CopyImage, sycl::_V1::ext::oneapi::experimental::image_descriptor::depth, sycl::_V1::ext::oneapi::experimental::image_descriptor::height, _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_type, _pi_image_desc::image_width, PI_IMAGE_COPY_DEVICE_TO_DEVICE, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, sycl::_V1::ext::oneapi::experimental::image_descriptor::type, sycl::_V1::ext::oneapi::experimental::image_descriptor::verify(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
ext_oneapi_copy() [2/7]
void sycl::_V1::handler::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, sycl::range< 3 > SrcOffset, const ext::oneapi::experimental::image_descriptor & SrcImgDesc, void * Dest, sycl::range< 3 > DestOffset, sycl::range< 3 > DestExtent, sycl::range< 3 > CopyExtent)
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
Allows for a sub-region copy, where SrcOffset , DestOffset , and Extent are used to determine the sub-region. Pixel size is determined by SrcImgDesc An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is an opaque image memory handle to the source memory.
SrcOffset is an offset from the origin of source measured in pixels (pixel size determined by SrcImgDesc)
SrcImgDesc is the source image descriptor
Dest is a USM pointer to the destination memory.
DestOffset is an offset from the destination origin where the x, y, and z components are measured in bytes, rows, and slices respectively
DestExtent is the extent of the dest memory to copy, measured in pixels (pixel size determined by DestImgDesc)
CopyExtent is the width, height, and depth of the region to copy measured in pixels (pixel size determined by SrcImgDesc)
Definition at line 1233 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::array_size, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_order, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::convertChannelType(), sycl::_V1::detail::CG::CopyImage, sycl::_V1::ext::oneapi::experimental::image_descriptor::depth, sycl::_V1::ext::oneapi::experimental::image_descriptor::height, _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_type, _pi_image_desc::image_width, PI_IMAGE_COPY_DEVICE_TO_HOST, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, sycl::_V1::ext::oneapi::experimental::image_descriptor::type, sycl::_V1::ext::oneapi::experimental::image_descriptor::verify(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
ext_oneapi_copy() [3/7]
void sycl::_V1::handler::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, void * Dest, const ext::oneapi::experimental::image_descriptor & SrcImgDesc)
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
An exception is thrown if either Src is incomplete or Dest is nullptr. The behavior is undefined if Desc is inconsistent with the allocated memory region.
Parameters
Src is an opaque image memory handle to the source memory.
Dest is a USM pointer to the destination memory.
SrcImgDesc is the source image descriptor
Definition at line 1131 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::array_size, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_order, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::convertChannelType(), sycl::_V1::detail::CG::CopyImage, sycl::_V1::ext::oneapi::experimental::image_descriptor::depth, sycl::_V1::ext::oneapi::experimental::image_descriptor::height, _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_type, _pi_image_desc::image_width, PI_IMAGE_COPY_DEVICE_TO_HOST, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, sycl::_V1::ext::oneapi::experimental::image_descriptor::type, sycl::_V1::ext::oneapi::experimental::image_descriptor::verify(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
ext_oneapi_copy() [4/7]
void sycl::_V1::handler::ext_oneapi_copy (void * Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor & DestImgDesc)
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
An exception is thrown if either Src is nullptr or Dest is incomplete. The behavior is undefined if Desc is inconsistent with the allocated memory region.
Parameters
Src is a USM pointer to the source memory.
Dest is an opaque image memory handle to the destination memory.
DestImgDesc is the image descriptor
Definition at line 1027 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::array_size, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_order, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::convertChannelType(), sycl::_V1::detail::CG::CopyImage, sycl::_V1::ext::oneapi::experimental::image_descriptor::depth, sycl::_V1::ext::oneapi::experimental::image_descriptor::height, _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_type, _pi_image_desc::image_width, PI_IMAGE_COPY_HOST_TO_DEVICE, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, sycl::_V1::ext::oneapi::experimental::image_descriptor::type, sycl::_V1::ext::oneapi::experimental::image_descriptor::verify(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
Referenced by sycl::_V1::queue::ext_oneapi_copy().
ext_oneapi_copy() [5/7]
void sycl::_V1::handler::ext_oneapi_copy (void * Src, sycl::range< 3 > SrcOffset, sycl::range< 3 > SrcExtent, ext::oneapi::experimental::image_mem_handle Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor & DestImgDesc, sycl::range< 3 > CopyExtent)
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
Allows for a sub-region copy, where SrcOffset , DestOffset , and CopyExtent are used to determine the sub-region. Pixel size is determined by DestImgDesc An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is a USM pointer to the source memory.
SrcOffset is an offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
SrcExtent is the extent of the source memory to copy, measured in pixels (pixel size determined by DestImgDesc)
Dest is an opaque image memory handle to the destination memory.
DestOffset is an offset from the destination origin measured in pixels (pixel size determined by DestImgDesc)
DestImgDesc is the destination image descriptor
CopyExtent is the width, height, and depth of the region to copy measured in pixels as determined by DestImgDesc
Definition at line 1078 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::array_size, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_order, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::convertChannelType(), sycl::_V1::detail::CG::CopyImage, sycl::_V1::ext::oneapi::experimental::image_descriptor::depth, sycl::_V1::ext::oneapi::experimental::image_descriptor::height, _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_type, _pi_image_desc::image_width, PI_IMAGE_COPY_HOST_TO_DEVICE, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, sycl::_V1::ext::oneapi::experimental::image_descriptor::type, sycl::_V1::ext::oneapi::experimental::image_descriptor::verify(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
ext_oneapi_copy() [6/7]
void sycl::_V1::handler::ext_oneapi_copy (void * Src, sycl::range< 3 > SrcOffset, void * Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor & DeviceImgDesc, size_t DeviceRowPitch, sycl::range< 3 > HostExtent, sycl::range< 3 > CopyExtent)
Copies data from one memory region to another, where Src and Dest are USM pointers.
Allows for a sub-region copy, where SrcOffset , DestOffset , and Extent are used to determine the sub-region. Pixel size is determined by DestImgDesc An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is a USM pointer to the source memory.
SrcOffset is an destination offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
Dest is a USM pointer to the destination memory.
DestOffset is an destination offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
DeviceImgDesc is the device image descriptor
DeviceRowPitch is the row pitch on the device
HostExtent is the extent of the dest memory to copy, measured in pixels (pixel size determined by DeviceImgDesc)
CopyExtent is the width, height, and depth of the region to copy measured in pixels (pixel size determined by DeviceImgDesc)
Definition at line 1339 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::array_size, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_order, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::convertChannelType(), sycl::_V1::detail::CG::CopyImage, sycl::_V1::ext::oneapi::experimental::image_descriptor::depth, sycl::_V1::get_pointer_type(), sycl::_V1::detail::getPiImageCopyFlags(), sycl::_V1::ext::oneapi::experimental::image_descriptor::height, _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_row_pitch, _pi_image_desc::image_type, _pi_image_desc::image_width, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, sycl::_V1::ext::oneapi::experimental::image_descriptor::type, sycl::_V1::ext::oneapi::experimental::image_descriptor::verify(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
ext_oneapi_copy() [7/7]
void sycl::_V1::handler::ext_oneapi_copy (void * Src, void * Dest, const ext::oneapi::experimental::image_descriptor & DeviceImgDesc, size_t DeviceRowPitch)
Copies data from one memory region to another, where Src and Dest are USM pointers.
An exception is thrown if either Src is nullptr, Dest is nullptr, or Pitch is inconsistent with hardware requirements. The behavior is undefined if Desc is inconsistent with the allocated memory region.
Parameters
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
DeviceImgDesc is the image descriptor (format, order, dimensions).
DeviceRowPitch is the pitch of the rows on the device.
Definition at line 1286 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::array_size, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_order, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::convertChannelType(), sycl::_V1::detail::CG::CopyImage, sycl::_V1::ext::oneapi::experimental::image_descriptor::depth, sycl::_V1::get_pointer_type(), sycl::_V1::detail::getPiImageCopyFlags(), sycl::_V1::ext::oneapi::experimental::image_descriptor::height, _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_row_pitch, _pi_image_desc::image_type, _pi_image_desc::image_width, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, sycl::_V1::ext::oneapi::experimental::image_descriptor::type, sycl::_V1::ext::oneapi::experimental::image_descriptor::verify(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
ext_oneapi_copy2d()
template<typename T > void sycl::_V1::handler::ext_oneapi_copy2d (const T * Src, size_t SrcPitch, T * Dest, size_t DestPitch, size_t Width, size_t Height)
Copies data from one 2D memory region to another, both pointed by USM pointers.
No operations is done if Width or Height is zero. An exception is thrown if either Dest or Src is nullptr or if Width is strictly greater than either DestPitch or SrcPitch. The behavior is undefined if any of the pointer parameters is invalid.
Parameters
Src is a USM pointer to the source memory.
SrcPitch is the pitch of the rows in Src.
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in Dest.
Width is the width in number of elements of the 2D region to copy.
Height is the height in number of rows of the 2D region to copy.
Definition at line 60 of file memcpy2d.hpp.
References sycl::_V1::get_pointer_type(), sycl::_V1::usm::host, sycl::_V1::invalid, and sycl::_V1::usm::unknown.
Referenced by sycl::_V1::queue::ext_oneapi_copy2d().
ext_oneapi_fill2d()
template<typename T > void sycl::_V1::handler::ext_oneapi_fill2d (void * Dest, size_t DestPitch, const T & Pattern, size_t Width, size_t Height)
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if Width or Height is zero. An exception is thrown if either Dest or Src is nullptr or if Width is strictly greater than DestPitch. The behavior is undefined if any of the pointer parameters is invalid.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in Dest.
Pattern is the pattern to fill into the memory. T should be device copyable.
Width is the width in number of elements of the 2D region to fill.
Height is the height in number of rows of the 2D region to fill.
Definition at line 121 of file memcpy2d.hpp.
References sycl::_V1::get_pointer_type(), sycl::_V1::usm::host, sycl::_V1::invalid, and sycl::_V1::usm::unknown.
Referenced by sycl::_V1::queue::ext_oneapi_fill2d().
ext_oneapi_graph()
void sycl::_V1::handler::ext_oneapi_graph (ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::executable > Graph)
Executes a command_graph.
Parameters
Graph Executable command_graph to run
Definition at line 1616 of file handler.cpp.
References sycl::_V1::detail::CG::ExecCommandBuffer, and sycl::_V1::detail::getSyclObjImpl().
Referenced by sycl::_V1::queue::ext_oneapi_graph().
ext_oneapi_memcpy2d()
template<typename T , typename > void sycl::_V1::handler::ext_oneapi_memcpy2d (void * Dest, size_t DestPitch, const void * Src, size_t SrcPitch, size_t Width, size_t Height)
Copies data from one 2D memory region to another, both pointed by USM pointers.
No operations is done if Width or Height is zero. An exception is thrown if either Dest or Src is nullptr or if Width is strictly greater than either DestPitch or SrcPitch. The behavior is undefined if any of the pointer parameters is invalid.
NOTE: Function is dependent to prevent the fallback kernels from materializing without the use of the function.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in Dest.
Src is a USM pointer to the source memory.
SrcPitch is the pitch of the rows in Src.
Width is the width in bytes of the 2D region to copy.
Height is the height in number of row of the 2D region to copy.
Definition at line 18 of file memcpy2d.hpp.
References sycl::_V1::get_pointer_type(), sycl::_V1::usm::host, sycl::_V1::invalid, and sycl::_V1::usm::unknown.
Referenced by sycl::_V1::queue::ext_oneapi_memcpy2d().
ext_oneapi_memset2d()
template<typename T , typename > void sycl::_V1::handler::ext_oneapi_memset2d (void * Dest, size_t DestPitch, int Value, size_t Width, size_t Height)
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if Width or Height is zero. An exception is thrown if either Dest or Src is nullptr or if Width is strictly greater than DestPitch. The behavior is undefined if any of the pointer parameters is invalid.
NOTE: Function is dependent to prevent the fallback kernels from materializing without the use of the function.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in Dest.
Value is the value to fill into the region in Dest. Value is cast as an unsigned char.
Width is the width in number of elements of the 2D region to fill.
Height is the height in number of rows of the 2D region to fill.
Definition at line 98 of file memcpy2d.hpp.
References sycl::_V1::get_pointer_type(), sycl::_V1::usm::host, sycl::_V1::invalid, and sycl::_V1::usm::unknown.
Referenced by sycl::_V1::queue::ext_oneapi_memset2d().
ext_oneapi_signal_external_semaphore()
void sycl::_V1::handler::ext_oneapi_signal_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle)
Instruct the queue to signal the external semaphore once all previous commands have completed execution.
An exception is thrown if SemaphoreHandle is incomplete.
Parameters
SemaphoreHandle is an opaque external interop semaphore handle
Definition at line 1405 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::interop_semaphore_handle::raw_handle, and sycl::_V1::detail::CG::SemaphoreSignal.
Referenced by sycl::_V1::queue::ext_oneapi_signal_external_semaphore().
ext_oneapi_wait_external_semaphore()
void sycl::_V1::handler::ext_oneapi_wait_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle)
Instruct the queue with a non-blocking wait on an external semaphore.
An exception is thrown if SemaphoreHandle is incomplete.
Parameters
SemaphoreHandle is an opaque external interop semaphore handle
Definition at line 1395 of file handler.cpp.
References sycl::_V1::ext::oneapi::experimental::interop_semaphore_handle::raw_handle, and sycl::_V1::detail::CG::SemaphoreWait.
Referenced by sycl::_V1::queue::ext_oneapi_wait_external_semaphore().
fill() [1/2]
template<typename T , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t, typename PropertyListT = property_list> void sycl::_V1::handler::fill (accessor< T, Dims, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > Dst, const T & Pattern) inline
Fills memory pointed by accessor with the pattern given.
If the operation is submitted to queue associated with OpenCL device and accessor points to one dimensional memory object then use special type for filling. Otherwise fill using regular kernel.
Parameters
Dst is a destination SYCL accessor.
Pattern is a value to be used to fill the memory.
Definition at line 2826 of file handler.hpp.
References sycl::_V1::detail::AccessorBaseHost::getAccessRange(), sycl::_V1::detail::AccessorBaseHost::getMemoryRange(), and sycl::_V1::ext::oneapi::experimental::memfill.
Referenced by sycl::_V1::ext::oneapi::experimental::fill(), and sycl::_V1::queue::fill().
fill() [2/2]
template<typename T > void sycl::_V1::handler::fill (void * Ptr, const T & Pattern, size_t Count) inline
Fills the specified memory with the specified pattern.
Parameters
Ptr is the pointer to the memory to fill
Pattern is the pattern to fill into the memory. T should be device copyable.
Count is the number of times to fill Pattern into Ptr.
Definition at line 2872 of file handler.hpp.
get_specialization_constant()
template<auto & SpecName> std::remove_reference_t<decltype(SpecName)>::value_type sycl::_V1::handler::get_specialization_constant () const inline
Definition at line 1880 of file handler.hpp.
References sycl::_V1::invalid, and sycl::_V1::make_error_code().
host_task()
template<typename FuncT > std::enable_if_t<detail::check_fn_signature<std::remove_reference_t<FuncT>, void()>::value || detail::check_fn_signature<std::remove_reference_t<FuncT>, void(interop_handle)>::value> sycl::_V1::handler::host_task (FuncT && Func) inline
Enqueues a command to the SYCL runtime to invoke Func once.
Definition at line 2043 of file handler.hpp.
Referenced by syclcompat::detail::combine_events().
mem_advise()
void sycl::_V1::handler::mem_advise (const void * Ptr, size_t Length, int Advice)
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
Definition at line 971 of file handler.cpp.
References sycl::_V1::detail::CG::AdviseUSM.
Referenced by sycl::_V1::detail::queue_impl::mem_advise(), and sycl::_V1::ext::oneapi::experimental::mem_advise().
memcpy() [1/3]
template<typename T , typename PropertyListT > void sycl::_V1::handler::memcpy (ext::oneapi::experimental::device_global< T, PropertyListT > & Dest, const void * Src, size_t NumBytes = sizeof(T), size_t DestOffset = 0) inline
Copies data from a USM memory region to a device_global.
Throws an exception if the copy operation intends to write outside the memory range Dest, as specified through NumBytes and DestOffset.
Parameters
Dest is the destination device_glboal.
Src is a USM pointer to the source memory.
NumBytes is a number of bytes to copy.
DestOffset is the offset into Dest to copy to.
Definition at line 3028 of file handler.hpp.
References sycl::_V1::ext::oneapi::experimental::has_property(), sycl::_V1::invalid, sycl::_V1::detail::isDeviceGlobalUsedInKernel(), and sycl::_V1::make_error_code().
memcpy() [2/3]
template<typename T , typename PropertyListT > void sycl::_V1::handler::memcpy (void * Dest, const ext::oneapi::experimental::device_global< T, PropertyListT > & Src, size_t NumBytes = sizeof(T), size_t SrcOffset = 0) inline
Copies data from a device_global to USM memory.
Throws an exception if the copy operation intends to read outside the memory range Src, as specified through NumBytes and SrcOffset.
Parameters
Dest is a USM pointer to copy to.
Src is the source device_global.
NumBytes is a number of bytes to copy.
SrcOffset is the offset into Src to copy from.
Definition at line 3062 of file handler.hpp.
References sycl::_V1::ext::oneapi::experimental::has_property(), sycl::_V1::invalid, sycl::_V1::detail::isDeviceGlobalUsedInKernel(), and sycl::_V1::make_error_code().
memcpy() [3/3]
void sycl::_V1::handler::memcpy (void * Dest, const void * Src, size_t Count)
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on this handler's device.
No operations is done if Count is zero. An exception is thrown if either Dest or Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Parameters
Dest is a USM pointer to the destination memory.
Src is a USM pointer to the source memory.
Count is a number of bytes to copy.
Definition at line 947 of file handler.cpp.
References sycl::_V1::detail::CG::CopyUSM.
Referenced by sycl::_V1::detail::queue_impl::memcpy(), sycl::_V1::queue::memcpy(), and sycl::_V1::ext::oneapi::experimental::memcpy().
memset()
void sycl::_V1::handler::memset (void * Dest, int Value, size_t Count)
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if Count is zero. An exception is thrown if Dest is nullptr. The behavior is undefined if Dest is invalid.
Parameters
Dest is a USM pointer to the memory to fill.
Value is a value to be set. Value is cast as an unsigned char.
Count is a number of bytes to fill.
Definition at line 955 of file handler.cpp.
References sycl::_V1::detail::CG::FillUSM, and sycl::_V1::ext::oneapi::experimental::memset.
Referenced by sycl::_V1::detail::queue_impl::memset(), and sycl::_V1::ext::oneapi::experimental::memset().
operator=() [1/2]
handler& sycl::_V1::handler::operator= (const handler &) delete
operator=() [2/2]
handler& sycl::_V1::handler::operator= (handler &&) delete
parallel_for() [1/24]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> void sycl::_V1::handler::parallel_for (kernel Kernel, nd_range< Dims > NDRange, _KERNELFUNCPARAM(KernelFunc)) inline
Defines and invokes a SYCL kernel function for the specified range and offsets.
Parameters
Kernel is a SYCL kernel that is executed on a SYCL device (except for the host device).
NDRange is a ND-range defining global and local sizes as well as offset.
KernelFunc is a lambda that is used if device, queue is bound to, is a host device.
Definition at line 2318 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::Kernel.
parallel_for() [2/24]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> void sycl::_V1::handler::parallel_for (kernel Kernel, range< Dims > NumWorkItems, _KERNELFUNCPARAM(KernelFunc)) inline
Defines and invokes a SYCL kernel function for the specified range.
Parameters
Kernel is a SYCL kernel that is executed on a SYCL device (except for the host device).
NumWorkItems is a range defining indexing space.
KernelFunc is a lambda that is used if device, queue is bound to, is a host device.
Definition at line 2240 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::Kernel.
parallel_for() [3/24]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> void sycl::_V1::handler::parallel_for (kernel Kernel, range< Dims > NumWorkItems, id< Dims > WorkItemOffset, _KERNELFUNCPARAM(KernelFunc)) inline
Defines and invokes a SYCL kernel function for the specified range and offsets.
Parameters
Kernel is a SYCL kernel that is executed on a SYCL device (except for the host device).
NumWorkItems is a range defining indexing space.
WorkItemOffset is an offset to be applied to each work item index.
KernelFunc is a lambda that is used if device, queue is bound to, is a host device.
Definition at line 2279 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::Kernel.
parallel_for() [4/24]
template<int Dims> void sycl::_V1::handler::parallel_for (nd_range< Dims > NDRange, kernel Kernel) inline
Defines and invokes a SYCL kernel function for the specified range and offsets.
The SYCL kernel function is defined as SYCL kernel object.
Parameters
NDRange is a ND-range defining global and local sizes as well as offset.
Kernel is a SYCL kernel function.
Definition at line 2188 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::Kernel.
parallel_for() [5/24]
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT , int Dims> std::enable_if_t< ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::parallel_for (nd_range< Dims > Range, PropertiesT Properties, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2469 of file handler.hpp.
parallel_for() [6/24]
template<typename KernelName = detail::auto_name, int Dims, typename PropertiesT , typename... RestT> std::enable_if_t< (sizeof...(RestT) > 1) && detail::AreAllButLastReductions<RestT...>::value && ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::parallel_for (nd_range< Dims > Range, PropertiesT Properties, RestT &&... Rest) inline
Definition at line 2545 of file handler.hpp.
parallel_for() [7/24]
template<typename KernelName = detail::auto_name, int Dims, typename... RestT> std::enable_if_t<detail::AreAllButLastReductions<RestT...>::value> sycl::_V1::handler::parallel_for (nd_range< Dims > Range, RestT &&... Rest) inline
Definition at line 2555 of file handler.hpp.
parallel_for() [8/24]
template<typename KernelName = detail::auto_name, typename KernelType > void sycl::_V1::handler::parallel_for (range< 1 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2017 of file handler.hpp.
Referenced by syclcompat::detail::launch(), sycl::_V1::ext::oneapi::experimental::nd_launch(), sycl::_V1::ext::oneapi::experimental::parallel_for(), sycl::_V1::detail::reduAuxCGFunc(), sycl::_V1::detail::reduCGFuncMulti(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::local_atomic_and_atomic_cross_wg >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::range_basic >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_atomic_cross_wg >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::local_mem_tree_and_atomic_cross_wg >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run().
parallel_for() [9/24]
void sycl::_V1::handler::parallel_for (range< 1 > NumWorkItems, kernel Kernel) inline
Definition at line 2146 of file handler.hpp.
parallel_for() [10/24]
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT > std::enable_if_t< ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::parallel_for (range< 1 > NumWorkItems, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2439 of file handler.hpp.
parallel_for() [11/24]
template<typename KernelName = detail::auto_name, typename PropertiesT , typename... RestT> std::enable_if_t< (sizeof...(RestT) > 1) && detail::AreAllButLastReductions<RestT...>::value && ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::parallel_for (range< 1 > Range, PropertiesT Properties, RestT &&... Rest) inline
Reductions.
Definition at line 2482 of file handler.hpp.
parallel_for() [12/24]
template<typename KernelName = detail::auto_name, typename... RestT> std::enable_if_t<detail::AreAllButLastReductions<RestT...>::value> sycl::_V1::handler::parallel_for (range< 1 > Range, RestT &&... Rest) inline
Definition at line 2517 of file handler.hpp.
parallel_for() [13/24]
template<typename KernelName = detail::auto_name, typename KernelType > void sycl::_V1::handler::parallel_for (range< 2 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2024 of file handler.hpp.
parallel_for() [14/24]
void sycl::_V1::handler::parallel_for (range< 2 > NumWorkItems, kernel Kernel) inline
Definition at line 2150 of file handler.hpp.
parallel_for() [15/24]
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT > std::enable_if_t< ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::parallel_for (range< 2 > NumWorkItems, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2449 of file handler.hpp.
parallel_for() [16/24]
template<typename KernelName = detail::auto_name, typename PropertiesT , typename... RestT> std::enable_if_t< (sizeof...(RestT) > 1) && detail::AreAllButLastReductions<RestT...>::value && ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::parallel_for (range< 2 > Range, PropertiesT Properties, RestT &&... Rest) inline
Definition at line 2495 of file handler.hpp.
parallel_for() [17/24]
template<typename KernelName = detail::auto_name, typename... RestT> std::enable_if_t<detail::AreAllButLastReductions<RestT...>::value> sycl::_V1::handler::parallel_for (range< 2 > Range, RestT &&... Rest) inline
Definition at line 2525 of file handler.hpp.
parallel_for() [18/24]
template<typename KernelName = detail::auto_name, typename KernelType > void sycl::_V1::handler::parallel_for (range< 3 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2031 of file handler.hpp.
parallel_for() [19/24]
void sycl::_V1::handler::parallel_for (range< 3 > NumWorkItems, kernel Kernel) inline
Definition at line 2154 of file handler.hpp.
parallel_for() [20/24]
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT > std::enable_if_t< ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::parallel_for (range< 3 > NumWorkItems, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2459 of file handler.hpp.
parallel_for() [21/24]
template<typename KernelName = detail::auto_name, typename PropertiesT , typename... RestT> std::enable_if_t< (sizeof...(RestT) > 1) && detail::AreAllButLastReductions<RestT...>::value && ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::parallel_for (range< 3 > Range, PropertiesT Properties, RestT &&... Rest) inline
Definition at line 2508 of file handler.hpp.
parallel_for() [22/24]
template<typename KernelName = detail::auto_name, typename... RestT> std::enable_if_t<detail::AreAllButLastReductions<RestT...>::value> sycl::_V1::handler::parallel_for (range< 3 > Range, RestT &&... Rest) inline
Definition at line 2533 of file handler.hpp.
parallel_for() [23/24]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> void sycl::_V1::handler::parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, _KERNELFUNCPARAM(KernelFunc)) inline
Defines and invokes a SYCL kernel function for the specified range and offset.
The SYCL kernel function is defined as a lambda function or a named function object type and given an id or item for indexing in the indexing space defined by range. If it is a named function object and the function object type is globally visible, there is no need for the developer to provide a kernel name for it.
Parameters
NumWorkItems is a range defining indexing space.
WorkItemOffset is an offset to be applied to each work item index.
KernelFunc is a SYCL kernel function.
Definition at line 2063 of file handler.hpp.
References sycl::_V1::detail::CG::Kernel.
parallel_for() [24/24]
template<int Dims> void sycl::_V1::handler::parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, kernel Kernel) inline
Defines and invokes a SYCL kernel function for the specified range and offsets.
The SYCL kernel function is defined as SYCL kernel object.
Parameters
NumWorkItems is a range defining indexing space.
WorkItemOffset is an offset to be applied to each work item index.
Kernel is a SYCL kernel function.
Definition at line 2168 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::Kernel.
parallel_for_work_group() [1/6]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> void sycl::_V1::handler::parallel_for_work_group (kernel Kernel, range< Dims > NumWorkGroups, _KERNELFUNCPARAM(KernelFunc)) inline
Hierarchical kernel invocation method of a kernel.
This version of parallel_for_work_group takes two parameters representing the same kernel. The first one - Kernel - is a compiled form of the second one - kernelFunc, which is the source form of the kernel. The same source kernel can be compiled multiple times yielding multiple kernel class objects accessible via the program class interface.
Parameters
Kernel is a compiled SYCL kernel.
NumWorkGroups is a range describing the number of work-groups in each dimension.
KernelFunc is a lambda representing kernel.
Definition at line 2361 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::Kernel.
parallel_for_work_group() [2/6]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> void sycl::_V1::handler::parallel_for_work_group (kernel Kernel, range< Dims > NumWorkGroups, range< Dims > WorkGroupSize, _KERNELFUNCPARAM(KernelFunc)) inline
Hierarchical kernel invocation method of a kernel.
This version of parallel_for_work_group takes two parameters representing the same kernel. The first one - Kernel - is a compiled form of the second one - kernelFunc, which is the source form of the kernel. The same source kernel can be compiled multiple times yielding multiple kernel class objects accessible via the program class interface.
Parameters
Kernel is a compiled SYCL kernel.
NumWorkGroups is a range describing the number of work-groups in each dimension.
WorkGroupSize is a range describing the size of work-groups in each dimension.
KernelFunc is a lambda representing kernel.
Definition at line 2400 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::detail::CG::Kernel, and sycl::_V1::ext::oneapi::experimental::detail::WorkGroupSize.
parallel_for_work_group() [3/6]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> void sycl::_V1::handler::parallel_for_work_group (range< Dims > NumWorkGroups, _KERNELFUNCPARAM(KernelFunc)) inline
Hierarchical kernel invocation method of a kernel defined as a lambda encoding the body of each work-group to launch.
Lambda may contain multiple calls to parallel_for_work_item(...) methods representing the execution on each work-item. Launches NumWorkGroups work-groups of runtime-defined size.
Parameters
NumWorkGroups is a range describing the number of work-groups in each dimension.
KernelFunc is a lambda representing kernel.
Definition at line 2098 of file handler.hpp.
parallel_for_work_group() [4/6]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims, typename PropertiesT > void sycl::_V1::handler::parallel_for_work_group (range< Dims > NumWorkGroups, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc)) inline
}@
Definition at line 2565 of file handler.hpp.
parallel_for_work_group() [5/6]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> void sycl::_V1::handler::parallel_for_work_group (range< Dims > NumWorkGroups, range< Dims > WorkGroupSize, _KERNELFUNCPARAM(KernelFunc)) inline
Hierarchical kernel invocation method of a kernel defined as a lambda encoding the body of each work-group to launch.
Lambda may contain multiple calls to parallel_for_work_item(...) methods representing the execution on each work-item. Launches NumWorkGroups work-groups of WorkGroupSize size.
Parameters
NumWorkGroups is a range describing the number of work-groups in each dimension.
WorkGroupSize is a range describing the size of work-groups in each dimension.
KernelFunc is a lambda representing kernel.
Definition at line 2119 of file handler.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::WorkGroupSize.
parallel_for_work_group() [6/6]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims, typename PropertiesT > void sycl::_V1::handler::parallel_for_work_group (range< Dims > NumWorkGroups, range< Dims > WorkGroupSize, PropertiesT Props, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2574 of file handler.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::WorkGroupSize.
prefetch()
void sycl::_V1::handler::prefetch (const void * Ptr, size_t Count)
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
Parameters
Ptr is a USM pointer to the memory to be prefetched to the device.
Count is a number of bytes to be prefetched.
Definition at line 964 of file handler.cpp.
References sycl::_V1::detail::CG::PrefetchUSM.
Referenced by sycl::_V1::queue::prefetch(), and sycl::_V1::ext::oneapi::experimental::prefetch().
require() [1/2]
template<typename DataT , int Dims, access::mode AccMode, access::target AccTarget, access::placeholder isPlaceholder> void sycl::_V1::handler::require (accessor< DataT, Dims, AccMode, AccTarget, isPlaceholder > Acc) inline
Requires access to the memory object associated with the placeholder accessor.
Calling this function with a non-placeholder accessor has no effect.
The command group has a requirement to gain access to the given memory object before executing.
Parameters
Acc is a SYCL accessor describing required memory region.
Definition at line 1908 of file handler.hpp.
References sycl::_V1::detail::associateWithHandler().
Referenced by sycl::_V1::queue::copy(), sycl::_V1::queue::fill(), and sycl::_V1::queue::update_host().
require() [2/2]
template<typename DataT , int Dims, access::mode AccMode, access::target AccTarget, access::placeholder isPlaceholder> void sycl::_V1::handler::require (ext::oneapi::experimental::dynamic_parameter< accessor< DataT, Dims, AccMode, AccTarget, isPlaceholder >> dynamicParamAcc) inline
Requires access to the memory object associated with the placeholder accessor contained in a dynamic_parameter object.
Calling this function with a non-placeholder accessor has no effect.
The command group has a requirement to gain access to the given memory object before executing.
Parameters
dynamicParamAcc is dynamic_parameter containing a SYCL accessor describing required memory region.
Definition at line 1924 of file handler.hpp.
References sycl::_V1::detail::associateWithHandler(), and sycl::_V1::detail::getValueFromDynamicParameter().
set_arg() [1/4]
template<typename DataT , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder> void sycl::_V1::handler::set_arg (int ArgIndex, accessor< DataT, Dims, AccessMode, AccessTarget, IsPlaceholder > Arg) inline
Definition at line 1977 of file handler.hpp.
set_arg() [2/4]
template<typename T > void sycl::_V1::handler::set_arg (int argIndex, ext::oneapi::experimental::dynamic_parameter< T > & dynamicParam) inline
Definition at line 1989 of file handler.hpp.
set_arg() [3/4]
template<typename DataT , int Dims> void sycl::_V1::handler::set_arg (int ArgIndex, local_accessor< DataT, Dims > Arg) inline
Definition at line 1983 of file handler.hpp.
set_arg() [4/4]
template<typename T > std::enable_if_t<ShouldEnableSetArg<T>::value, void> sycl::_V1::handler::set_arg (int ArgIndex, T && Arg) inline
Sets argument for OpenCL interoperability kernels.
Registers Arg passed as argument # ArgIndex.
Parameters
ArgIndex is a positional number of argument to be set.
Arg is an argument value to be set.
Definition at line 1970 of file handler.hpp.
set_args()
template<typename... Ts> void sycl::_V1::handler::set_args (Ts &&... Args) inline
Sets arguments for OpenCL interoperability kernels.
Registers pack of arguments(Args) with indexes starting from 0.
Parameters
Args are argument values to be set.
Definition at line 1999 of file handler.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::nd_launch(), sycl::_V1::ext::oneapi::experimental::parallel_for(), and sycl::_V1::ext::oneapi::experimental::single_task().
set_specialization_constant()
template<auto & SpecName> void sycl::_V1::handler::set_specialization_constant (typename std::remove_reference_t< decltype(SpecName)>::value_type Value) inline
Definition at line 1865 of file handler.hpp.
single_task() [1/4]
template<typename KernelName = detail::auto_name, typename KernelType > void sycl::_V1::handler::single_task (_KERNELFUNCPARAM(KernelFunc)) inline
Defines and invokes a SYCL kernel function as a function object type.
If it is a named function object and the function object type is globally visible, there is no need for the developer to provide a kernel name for it.
Parameters
KernelFunc is a SYCL kernel function.
Definition at line 2011 of file handler.hpp.
Referenced by sycl::_V1::detail::reduSaveFinalResultToUserMem(), sycl::_V1::ext::oneapi::experimental::single_task(), and sycl::_V1::detail::reduction_impl_algo< T, BinaryOperation, Dims, Extent, ExplicitIdentity, RedOutVar >::withInitializedMem().
single_task() [2/4]
void sycl::_V1::handler::single_task (kernel Kernel) inline
Invokes a SYCL kernel.
Executes exactly once. The kernel invocation method has no functors and cannot be called on host.
Parameters
Kernel is a SYCL kernel object.
Definition at line 2133 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::Kernel.
single_task() [3/4]
template<typename KernelName = detail::auto_name, typename KernelType > void sycl::_V1::handler::single_task (kernel Kernel, _KERNELFUNCPARAM(KernelFunc)) inline
Defines and invokes a SYCL kernel function.
Parameters
Kernel is a SYCL kernel that is executed on a SYCL device (except for the host device).
KernelFunc is a lambda that is used if device, queue is bound to, is a host device.
Definition at line 2206 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::Kernel.
single_task() [4/4]
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT > std::enable_if_t< ext::oneapi::experimental::is_property_list<PropertiesT>::value> sycl::_V1::handler::single_task (PropertiesT Props, _KERNELFUNCPARAM(KernelFunc)) inline
Definition at line 2430 of file handler.hpp.
update_host()
template<typename T , int Dims, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder = access::placeholder::false_t> void sycl::_V1::handler::update_host (accessor< T, Dims, AccessMode, AccessTarget, IsPlaceholder > Acc) inline
Provides guarantees that the memory object accessed via Acc is updated on the host after command group object execution is complete.
Parameters
Acc is a SYCL accessor that needs to be updated on host.
Definition at line 2795 of file handler.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::CG::UpdateHost.
Referenced by sycl::_V1::queue::update_host().
use_kernel_bundle()
void sycl::_V1::handler::use_kernel_bundle (const kernel_bundle< bundle_state::executable > & ExecBundle)
Definition at line 1415 of file handler.cpp.
References sycl::_V1::kernel_bundle< State >::get_context(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::invalid, and sycl::_V1::make_error_code().
Friends And Related Function Documentation
::MockHandler
friend class ::MockHandler friend
Definition at line 3390 of file handler.hpp.
accessor
template<typename DataT , int Dims, access::mode AccMode, access::target AccTarget, access::placeholder isPlaceholder, typename PropertyListT > friend class accessor friend
Definition at line 3349 of file handler.hpp.
detail::associateWithHandler [1/3]
void detail::associateWithHandler (handler & , detail::AccessorBaseHost * , access::target) friend
detail::associateWithHandler [2/3]
void detail::associateWithHandler (handler & , detail::SampledImageAccessorBaseHost * , image_target) friend
detail::associateWithHandler [3/3]
void detail::associateWithHandler (handler & , detail::UnsampledImageAccessorBaseHost * , image_target) friend
detail::getDeviceFromHandler
device detail::getDeviceFromHandler (handler &) friend
detail::image_accessor
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder> friend class detail::image_accessor friend
Definition at line 3354 of file handler.hpp.
detail::queue_impl
detail::queue_impl friend
Definition at line 3344 of file handler.hpp.
detail::reduction::finalizeHandler
void detail::reduction::finalizeHandler (handler & CGH) friend
detail::reduction::withAuxHandler
template<class FunctorTy > void detail::reduction::withAuxHandler (handler & CGH, FunctorTy Func) friend
detail::reduction_impl_algo
template<typename T , class BinaryOperation , int Dims, size_t Extent, bool ExplicitIdentity, typename RedOutVar > friend class detail::reduction_impl_algo friend
Definition at line 3362 of file handler.hpp.
detail::reduction_parallel_for [1/2]
template<typename KernelName , detail::reduction::strategy Strategy, int Dims, typename PropertiesT , typename... RestT> void detail::reduction_parallel_for (handler & CGH, nd_range< Dims > NDRange, PropertiesT Properties, RestT... Rest) friend
detail::reduction_parallel_for [2/2]
template<typename KernelName , detail::reduction::strategy Strategy, int Dims, typename PropertiesT , typename... RestT> void detail::reduction_parallel_for (handler & CGH, range< Dims > NDRange, PropertiesT Properties, RestT... Rest) friend
detail::stream_impl
friend class detail::stream_impl friend
Definition at line 3357 of file handler.hpp.
ext::intel::experimental::pipe
template<class _name , class _dataT , int32_t _min_capacity, class _propertiesT , class > friend class ext::intel::experimental::pipe friend
Definition at line 3397 of file handler.hpp.
ext::oneapi::experimental::detail::dynamic_parameter_impl
friend class ext::oneapi::experimental::detail::dynamic_parameter_impl friend
Definition at line 3425 of file handler.hpp.
ext::oneapi::experimental::detail::graph_impl
friend class ext::oneapi::experimental::detail::graph_impl friend
Definition at line 3424 of file handler.hpp.
stream
friend class stream friend
Definition at line 3356 of file handler.hpp.
The documentation for this class was generated from the following files:
include/sycl/handler.hpp
include/sycl/ext/oneapi/memcpy2d.hpp
source/handler.cpp