DPC++ Runtime: cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > > Class Template Reference
cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > > Class Template Reference
Specialization of the generic class 'reducer'.
#include <CL/sycl/intel/reduction.hpp>
Public Member Functions
reducer ()
reducer (const T &, BinaryOperation)
void combine (const T &Partial)
template<typename _T = T>
enable_if_t< std::is_same< _T, T >::value &&IsReduPlus< T, BinaryOperation >::value, reducer & > operator+= (const _T &Partial)
template<typename _T = T>
enable_if_t< std::is_same< _T, T >::value &&IsReduMultiplies< T, BinaryOperation >::value, reducer & > operator*= (const _T &Partial)
template<typename _T = T>
enable_if_t< std::is_same< _T, T >::value &&IsReduBitOR< T, BinaryOperation >::value, reducer & > operator|= (const _T &Partial)
template<typename _T = T>
enable_if_t< std::is_same< _T, T >::value &&IsReduBitXOR< T, BinaryOperation >::value, reducer & > operator^= (const _T &Partial)
template<typename _T = T>
enable_if_t< std::is_same< _T, T >::value &&IsReduBitAND< T, BinaryOperation >::value, reducer & > operator &= (const _T &Partial)
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&(is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&IsReduPlus< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic ADD operation: *ReduVarPtr += MValue;.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&(is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&IsReduBitOR< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic BITWISE OR operation: *ReduVarPtr |= MValue;.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&(is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&IsReduBitXOR< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic BITWISE XOR operation: *ReduVarPtr ^= MValue;.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&(is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&IsReduBitAND< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic BITWISE AND operation: *ReduVarPtr &= MValue;.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&(is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&IsReduMinimum< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic MIN operation: *ReduVarPtr = intel::minimum(*ReduVarPtr, MValue);.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&(is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&IsReduMaximum< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic MAX operation: *ReduVarPtr = intel::maximum(*ReduVarPtr, MValue);.
Static Public Member Functions
template<typename _T = T, class _BinaryOperation = BinaryOperation>
static enable_if_t< IsZeroIdentityOp< _T, _BinaryOperation >::value, _T > getIdentity ()
Returns zero as identity for ADD, OR, XOR operations.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
static enable_if_t< IsOneIdentityOp< _T, _BinaryOperation >::value, _T > getIdentity ()
Returns one as identify for MULTIPLY operations.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
static enable_if_t< IsOnesIdentityOp< _T, _BinaryOperation >::value, _T > getIdentity ()
Returns bit image consisting of all ones as identity for AND operations.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
static enable_if_t< IsMinimumIdentityOp< _T, _BinaryOperation >::value, _T > getIdentity ()
Returns maximal possible value as identity for MIN operations.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
static enable_if_t< IsMaximumIdentityOp< _T, _BinaryOperation >::value, _T > getIdentity ()
Returns minimal possible value as identity for MAX operations.
Public Attributes
T MValue
Detailed Description
template<typename T, class BinaryOperation>
class cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >
Specialization of the generic class 'reducer'.
It is used for reductions of those types and operations for which the identity value is known.
It allows to reduce the size of the 'reducer' object by not holding the identity field inside it and allows to add a default constructor.
Also, for many types with known identity the operation 'atomic_combine()' is implemented here, which allows to use more efficient version of kernels using those operations, which are based on functionality provided by sycl::atomic class.
For example, it is known that 0 is identity for intel::plus operations accepting native scalar types to which scalar 0 is convertible. Also, for int32/64 types the atomic_combine() is lowered to sycl::atomic::fetch_add().
Definition at line 181 of file reduction.hpp.
Constructor & Destructor Documentation
reducer() [1/2]
template<typename T , class BinaryOperation > cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::reducer () inline
Definition at line 184 of file reduction.hpp.
reducer() [2/2]
template<typename T , class BinaryOperation > cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::reducer (const T & , BinaryOperation) inline
Definition at line 185 of file reduction.hpp.
Member Function Documentation
atomic_combine() [1/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && (is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && IsReduPlus<T, _BinaryOperation>::value> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic ADD operation: *ReduVarPtr += MValue;.
Definition at line 281 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_add().
atomic_combine() [2/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && (is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && IsReduBitOR<T, _BinaryOperation>::value> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic BITWISE OR operation: *ReduVarPtr |= MValue;.
Definition at line 291 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_or().
atomic_combine() [3/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && (is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && IsReduBitXOR<T, _BinaryOperation>::value> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic BITWISE XOR operation: *ReduVarPtr ^= MValue;.
Definition at line 301 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_xor().
atomic_combine() [4/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && (is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && IsReduBitAND<T, _BinaryOperation>::value> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic BITWISE AND operation: *ReduVarPtr &= MValue;.
Definition at line 311 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_and().
atomic_combine() [5/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && (is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && IsReduMinimum<T, _BinaryOperation>::value> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic MIN operation: *ReduVarPtr = intel::minimum(*ReduVarPtr, MValue);.
Definition at line 321 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_min().
atomic_combine() [6/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && (is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && IsReduMaximum<T, _BinaryOperation>::value> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic MAX operation: *ReduVarPtr = intel::maximum(*ReduVarPtr, MValue);.
Definition at line 331 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_max().
combine()
template<typename T , class BinaryOperation > void cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::combine (const T & Partial) inline
Definition at line 187 of file reduction.hpp.
getIdentity() [1/5]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> static enable_if_t<IsZeroIdentityOp<_T, _BinaryOperation>::value, _T> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::getIdentity () inline static
Returns zero as identity for ADD, OR, XOR operations.
Definition at line 195 of file reduction.hpp.
getIdentity() [2/5]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> static enable_if_t<IsOneIdentityOp<_T, _BinaryOperation>::value, _T> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::getIdentity () inline static
Returns one as identify for MULTIPLY operations.
Definition at line 202 of file reduction.hpp.
getIdentity() [3/5]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> static enable_if_t<IsOnesIdentityOp<_T, _BinaryOperation>::value, _T> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::getIdentity () inline static
Returns bit image consisting of all ones as identity for AND operations.
Definition at line 209 of file reduction.hpp.
getIdentity() [4/5]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> static enable_if_t<IsMinimumIdentityOp<_T, _BinaryOperation>::value, _T> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::getIdentity () inline static
Returns maximal possible value as identity for MIN operations.
Definition at line 216 of file reduction.hpp.
getIdentity() [5/5]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> static enable_if_t<IsMaximumIdentityOp<_T, _BinaryOperation>::value, _T> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::getIdentity () inline static
Returns minimal possible value as identity for MAX operations.
Definition at line 225 of file reduction.hpp.
operator &=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<std::is_same<_T, T>::value && IsReduBitAND<T, BinaryOperation>::value, reducer &> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator&= (const _T & Partial) inline
Definition at line 271 of file reduction.hpp.
operator*=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<std::is_same<_T, T>::value && IsReduMultiplies<T, BinaryOperation>::value, reducer &> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator*= (const _T & Partial) inline
Definition at line 244 of file reduction.hpp.
operator+=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<std::is_same<_T, T>::value && IsReduPlus<T, BinaryOperation>::value, reducer &> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator+= (const _T & Partial) inline
Definition at line 235 of file reduction.hpp.
operator^=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<std::is_same<_T, T>::value && IsReduBitXOR<T, BinaryOperation>::value, reducer &> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator^= (const _T & Partial) inline
Definition at line 262 of file reduction.hpp.
operator|=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<std::is_same<_T, T>::value && IsReduBitOR<T, BinaryOperation>::value, reducer &> cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator|= (const _T & Partial) inline
Definition at line 253 of file reduction.hpp.
Member Data Documentation
MValue
template<typename T , class BinaryOperation > T cl::sycl::intel::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::MValue
Definition at line 336 of file reduction.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/intel/reduction.hpp