DPC++ Runtime: sycl::_V1::detail::half_impl::half Class Reference
sycl::_V1::detail::half_impl::half Class Reference
#include <sycl/half_type.hpp>
Public Member Functions
half ()=default
constexpr half (const half &)=default
constexpr half (half &&)=default
__SYCL_CONSTEXPR_HALF half (const float &rhs)
constexpr half & operator= (const half &rhs)=default
constexpr half (const detail::host_half_impl::half &rhs)
constexpr operator detail::host_half_impl::half () const
__SYCL_CONSTEXPR_HALF half & operator+= (const half &rhs)
__SYCL_CONSTEXPR_HALF half & operator-= (const half &rhs)
__SYCL_CONSTEXPR_HALF half & operator*= (const half &rhs)
__SYCL_CONSTEXPR_HALF half & operator/= (const half &rhs)
__SYCL_CONSTEXPR_HALF half & operator++ ()
__SYCL_CONSTEXPR_HALF half operator++ (int)
__SYCL_CONSTEXPR_HALF half & operator-- ()
__SYCL_CONSTEXPR_HALF half operator-- (int)
__SYCL_CONSTEXPR_HALF operator float () const
Friends
template<typename Key >
struct std::hash
class sycl::ext::intel::esimd::detail::WrapperElementTypeProxy
__SYCL_CONSTEXPR_HALF friend half operator- (const half other)
std::ostream & operator<< (std::ostream &O, sycl::half const &rhs)
std::istream & operator>> (std::istream &I, sycl::half &rhs)
Detailed Description
Definition at line 276 of file half_type.hpp.
Constructor & Destructor Documentation
half() [1/5]
sycl::_V1::detail::half_impl::half::half () default
half() [2/5]
constexpr sycl::_V1::detail::half_impl::half::half (const half &) constexpr default
half() [3/5]
constexpr sycl::_V1::detail::half_impl::half::half (half &&) constexpr default
half() [4/5]
__SYCL_CONSTEXPR_HALF sycl::_V1::detail::half_impl::half::half (const float & rhs) inline
Definition at line 285 of file half_type.hpp.
half() [5/5]
constexpr sycl::_V1::detail::half_impl::half::half (const detail::host_half_impl::half & rhs) inline constexpr
Definition at line 292 of file half_type.hpp.
Member Function Documentation
operator detail::host_half_impl::half()
constexpr sycl::_V1::detail::half_impl::half::operator detail::host_half_impl::half () const inline constexpr
Definition at line 293 of file half_type.hpp.
operator float()
__SYCL_CONSTEXPR_HALF sycl::_V1::detail::half_impl::half::operator float () const inline
Definition at line 534 of file half_type.hpp.
operator*=()
__SYCL_CONSTEXPR_HALF half& sycl::_V1::detail::half_impl::half::operator*= (const half & rhs) inline
Definition at line 307 of file half_type.hpp.
operator++() [1/2]
__SYCL_CONSTEXPR_HALF half& sycl::_V1::detail::half_impl::half::operator++ () inline
Definition at line 318 of file half_type.hpp.
Referenced by operator++().
operator++() [2/2]
__SYCL_CONSTEXPR_HALF half sycl::_V1::detail::half_impl::half::operator++ (int) inline
Definition at line 323 of file half_type.hpp.
References operator++().
operator+=()
__SYCL_CONSTEXPR_HALF half& sycl::_V1::detail::half_impl::half::operator+= (const half & rhs) inline
Definition at line 297 of file half_type.hpp.
operator--() [1/2]
__SYCL_CONSTEXPR_HALF half& sycl::_V1::detail::half_impl::half::operator-- () inline
Definition at line 329 of file half_type.hpp.
Referenced by operator--().
operator--() [2/2]
__SYCL_CONSTEXPR_HALF half sycl::_V1::detail::half_impl::half::operator-- (int) inline
Definition at line 334 of file half_type.hpp.
References operator--().
operator-=()
__SYCL_CONSTEXPR_HALF half& sycl::_V1::detail::half_impl::half::operator-= (const half & rhs) inline
Definition at line 302 of file half_type.hpp.
operator/=()
__SYCL_CONSTEXPR_HALF half& sycl::_V1::detail::half_impl::half::operator/= (const half & rhs) inline
Definition at line 312 of file half_type.hpp.
operator=()
constexpr half& sycl::_V1::detail::half_impl::half::operator= (const half & rhs) constexpr default
Friends And Related Function Documentation
operator-
__SYCL_CONSTEXPR_HALF friend half operator- (const half other) friend
Definition at line 339 of file half_type.hpp.
operator<<
std::ostream& operator<< (std::ostream & O, sycl::half const & rhs) friend
Definition at line 539 of file half_type.hpp.
operator>>
std::istream& operator>> (std::istream & I, sycl::half & rhs) friend
Definition at line 545 of file half_type.hpp.
std::hash
template<typename Key > friend struct std::hash friend
Definition at line 552 of file half_type.hpp.
sycl::ext::intel::esimd::detail::WrapperElementTypeProxy
friend class sycl::ext::intel::esimd::detail::WrapperElementTypeProxy friend
Definition at line 554 of file half_type.hpp.
The documentation for this class was generated from the following file:
include/sycl/half_type.hpp