DPC++ Runtime: Slab Class Reference
Slab Class Reference
Public Member Functions
Slab (Bucket &)
~Slab ()
void setIterator (ListIter It)
ListIter getIterator () const
size_t getNumAllocated () const
void * getChunk ()
void * getSlab ()
void * getPtr () const
void * getEnd () const
size_t getChunkSize () const
size_t getNumChunks () const
bool hasAvail ()
Bucket & getBucket ()
const Bucket & getBucket () const
void freeChunk (void *Ptr)
Detailed Description
Definition at line 338 of file usm_allocator.cpp.
Constructor & Destructor Documentation
Slab()
Slab::Slab (Bucket & Bkt)
Definition at line 550 of file usm_allocator.cpp.
~Slab()
Slab::~Slab ()
Definition at line 562 of file usm_allocator.cpp.
References SystemMemory::deallocate(), and Bucket::getMemHandle().
Member Function Documentation
freeChunk()
void Slab::freeChunk (void * Ptr)
Definition at line 648 of file usm_allocator.cpp.
References getChunkSize(), getEnd(), and getPtr().
Referenced by Bucket::freeChunk().
getBucket() [1/2]
const Bucket & Slab::getBucket ()
Definition at line 599 of file usm_allocator.cpp.
Referenced by USMAllocContext::USMAllocImpl::deallocate(), and operator<<().
getBucket() [2/2]
const Bucket& Slab::getBucket () const
getChunk()
void * Slab::getChunk ()
Definition at line 579 of file usm_allocator.cpp.
References getChunkSize(), and getPtr().
getChunkSize()
size_t Slab::getChunkSize () const
Definition at line 602 of file usm_allocator.cpp.
References Bucket::getSize().
Referenced by freeChunk(), and getChunk().
getEnd()
void * Slab::getEnd () const
Definition at line 670 of file usm_allocator.cpp.
References getPtr(), and Bucket::SlabMinSize().
Referenced by USMAllocContext::USMAllocImpl::deallocate(), freeChunk(), and operator<<().
getIterator()
ListIter Slab::getIterator () const inline
Definition at line 377 of file usm_allocator.cpp.
Referenced by Bucket::freeSlab().
getNumAllocated()
size_t Slab::getNumAllocated () const inline
Definition at line 379 of file usm_allocator.cpp.
getNumChunks()
size_t Slab::getNumChunks () const inline
Definition at line 391 of file usm_allocator.cpp.
Referenced by hasAvail().
getPtr()
void* Slab::getPtr () const inline
Definition at line 387 of file usm_allocator.cpp.
Referenced by USMAllocContext::USMAllocImpl::deallocate(), freeChunk(), getChunk(), getEnd(), getSlab(), operator<<(), and operator==().
getSlab()
void * Slab::getSlab ()
Definition at line 597 of file usm_allocator.cpp.
References getPtr().
hasAvail()
bool Slab::hasAvail ()
Definition at line 674 of file usm_allocator.cpp.
References getNumChunks().
setIterator()
void Slab::setIterator (ListIter It) inline
Definition at line 376 of file usm_allocator.cpp.
The documentation for this class was generated from the following file:
plugins/level_zero/usm_allocator.cpp