DPC++ Runtime: sycl::_V1::detail::DispatchHostTask Class Reference
sycl::_V1::detail::DispatchHostTask Class Reference
Public Member Functions
DispatchHostTask (ExecCGCommand *ThisCmd, std::vector< interop_handle::ReqToMem > ReqToMem)
void operator() () const
Detailed Description
Definition at line 320 of file commands.cpp.
Constructor & Destructor Documentation
DispatchHostTask()
sycl::_V1::detail::DispatchHostTask::DispatchHostTask (ExecCGCommand * ThisCmd, std::vector< interop_handle::ReqToMem > ReqToMem) inline
Definition at line 365 of file commands.cpp.
Member Function Documentation
operator()()
void sycl::_V1::detail::DispatchHostTask::operator() () const inline
Definition at line 369 of file commands.cpp.
References sycl::_V1::detail::ExecCGCommand::getCG(), sycl::_V1::detail::Scheduler::getInstance(), sycl::_V1::detail::CG::getType(), sycl::_V1::detail::GlobalHandler::instance(), sycl::_V1::detail::Command::MEvent, sycl::_V1::detail::Command::MSubmissionCodeLocation, sycl::_V1::detail::Scheduler::NotifyHostTaskCompletion(), and sycl::_V1::detail::GlobalHandler::TraceEventXPTI().
The documentation for this class was generated from the following file:
source/detail/scheduler/commands.cpp