DPC++ Runtime: cl::sycl::detail::LockCacheItem Class Reference
cl::sycl::detail::LockCacheItem Class Reference
#include <detail/persistent_device_code_cache.hpp>
Public Member Functions
LockCacheItem (const std::string &Path)
bool isOwned ()
~LockCacheItem ()
Static Public Member Functions
static bool isLocked (const std::string &Path)
Detailed Description
Definition at line 42 of file persistent_device_code_cache.hpp.
Constructor & Destructor Documentation
LockCacheItem()
cl::sycl::detail::LockCacheItem::LockCacheItem (const std::string & Path)
Definition at line 29 of file persistent_device_code_cache.cpp.
References cl::sycl::detail::PersistentDeviceCodeCache::trace().
~LockCacheItem()
cl::sycl::detail::LockCacheItem::~LockCacheItem ()
Definition at line 42 of file persistent_device_code_cache.cpp.
References cl::sycl::detail::PersistentDeviceCodeCache::trace().
Member Function Documentation
isLocked()
static bool cl::sycl::detail::LockCacheItem::isLocked (const std::string & Path) inline static
Definition at line 52 of file persistent_device_code_cache.hpp.
Referenced by cl::sycl::detail::PersistentDeviceCodeCache::getItemFromDisc().
isOwned()
bool cl::sycl::detail::LockCacheItem::isOwned () inline
Definition at line 51 of file persistent_device_code_cache.hpp.
The documentation for this class was generated from the following files:
source/detail/persistent_device_code_cache.hpp
source/detail/persistent_device_code_cache.cpp