DPC++ Runtime: cl::sycl::property::detail::PropertyHolder< T > Class Template Reference
cl::sycl::property::detail::PropertyHolder< T > Class Template Reference
#include <CL/sycl/property_list.hpp>
Public Member Functions
PropertyHolder ()=default
PropertyHolder (const PropertyHolder &P)
~PropertyHolder ()
PropertyHolder & operator= (const PropertyHolder &Other)
void setProp (const T &Rhs)
const T & getProp () const
bool isInitialized () const
Detailed Description
template<class T>
class cl::sycl::property::detail::PropertyHolder< T >
Definition at line 80 of file property_list.hpp.
Constructor & Destructor Documentation
PropertyHolder() [1/2]
template<class T > cl::sycl::property::detail::PropertyHolder< T >::PropertyHolder () default
PropertyHolder() [2/2]
template<class T > cl::sycl::property::detail::PropertyHolder< T >::PropertyHolder (const PropertyHolder< T > & P) inline
Definition at line 84 of file property_list.hpp.
References cl::sycl::property::detail::PropertyHolder< T >::getProp(), and cl::sycl::property::detail::PropertyHolder< T >::isInitialized().
~PropertyHolder()
template<class T > cl::sycl::property::detail::PropertyHolder< T >::~PropertyHolder () inline
Definition at line 91 of file property_list.hpp.
Member Function Documentation
getProp()
template<class T > const T& cl::sycl::property::detail::PropertyHolder< T >::getProp () const inline
Definition at line 119 of file property_list.hpp.
Referenced by cl::sycl::property::detail::PropertyHolder< T >::operator=(), and cl::sycl::property::detail::PropertyHolder< T >::PropertyHolder().
isInitialized()
template<class T > bool cl::sycl::property::detail::PropertyHolder< T >::isInitialized () const inline
Definition at line 124 of file property_list.hpp.
Referenced by cl::sycl::property::detail::PropertyHolder< T >::PropertyHolder().
operator=()
template<class T > PropertyHolder& cl::sycl::property::detail::PropertyHolder< T >::operator= (const PropertyHolder< T > & Other) inline
Definition at line 98 of file property_list.hpp.
References cl::sycl::property::detail::PropertyHolder< T >::getProp().
setProp()
template<class T > void cl::sycl::property::detail::PropertyHolder< T >::setProp (const T & Rhs) inline
Definition at line 114 of file property_list.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/property_list.hpp