DPC++ Runtime: cl::sycl::atomic< T, addressSpace > Class Template Reference
cl::sycl::atomic< T, addressSpace > Class Template Reference
#include <CL/sycl/atomic.hpp>
Public Member Functions
template<typename pointerT >
atomic (multi_ptr< pointerT, addressSpace > ptr)
void store (T Operand, memory_order Order=memory_order::relaxed)
T load (memory_order Order=memory_order::relaxed) const
T exchange (T Operand, memory_order Order=memory_order::relaxed)
bool compare_exchange_strong (T &Expected, T Desired, memory_order SuccessOrder=memory_order::relaxed, memory_order FailOrder=memory_order::relaxed)
T fetch_add (T Operand, memory_order Order=memory_order::relaxed)
T fetch_sub (T Operand, memory_order Order=memory_order::relaxed)
T fetch_and (T Operand, memory_order Order=memory_order::relaxed)
T fetch_or (T Operand, memory_order Order=memory_order::relaxed)
T fetch_xor (T Operand, memory_order Order=memory_order::relaxed)
T fetch_min (T Operand, memory_order Order=memory_order::relaxed)
T fetch_max (T Operand, memory_order Order=memory_order::relaxed)
Friends
class atomic< T, access::address_space::global_space >
Detailed Description
template<typename T, access::address_space addressSpace = access::address_space::global_space>
class cl::sycl::atomic< T, addressSpace >
Definition at line 175 of file atomic.hpp.
Constructor & Destructor Documentation
atomic()
template<typename T, access::address_space addressSpace = access::address_space::global_space> template<typename pointerT > cl::sycl::atomic< T, addressSpace >::atomic (multi_ptr< pointerT, addressSpace > ptr) inline
Definition at line 193 of file atomic.hpp.
Member Function Documentation
compare_exchange_strong()
template<typename T, access::address_space addressSpace = access::address_space::global_space> bool cl::sycl::atomic< T, addressSpace >::compare_exchange_strong (T & Expected, T Desired, memory_order SuccessOrder = memory_order::relaxed, memory_order FailOrder = memory_order::relaxed) inline
Definition at line 256 of file atomic.hpp.
References __SYCL_STATIC_ASSERT_NOT_FLOAT, cl::sycl::detail::getSPIRVMemorySemanticsMask(), and cl::sycl::detail::getStdMemoryOrder().
Referenced by cl::sycl::atomic_compare_exchange_strong().
exchange()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::exchange (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 250 of file atomic.hpp.
References __spirv_AtomicExchange(), and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::atomic_exchange().
fetch_add()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::fetch_add (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 277 of file atomic.hpp.
References __spirv_AtomicIAdd(), __SYCL_STATIC_ASSERT_NOT_FLOAT, and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine(), and cl::sycl::atomic_fetch_add().
fetch_and()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::fetch_and (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 289 of file atomic.hpp.
References __spirv_AtomicAnd(), __SYCL_STATIC_ASSERT_NOT_FLOAT, and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine(), and cl::sycl::atomic_fetch_and().
fetch_max()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::fetch_max (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 313 of file atomic.hpp.
References __spirv_AtomicMax(), __SYCL_STATIC_ASSERT_NOT_FLOAT, and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine(), and cl::sycl::atomic_fetch_max().
fetch_min()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::fetch_min (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 307 of file atomic.hpp.
References __spirv_AtomicMin(), __SYCL_STATIC_ASSERT_NOT_FLOAT, and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine(), and cl::sycl::atomic_fetch_min().
fetch_or()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::fetch_or (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 295 of file atomic.hpp.
References __spirv_AtomicOr(), __SYCL_STATIC_ASSERT_NOT_FLOAT, and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine(), and cl::sycl::atomic_fetch_or().
fetch_sub()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::fetch_sub (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 283 of file atomic.hpp.
References __spirv_AtomicISub(), __SYCL_STATIC_ASSERT_NOT_FLOAT, and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::atomic_fetch_sub().
fetch_xor()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::fetch_xor (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 301 of file atomic.hpp.
References __spirv_AtomicXor(), __SYCL_STATIC_ASSERT_NOT_FLOAT, and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine(), and cl::sycl::atomic_fetch_xor().
load()
template<typename T, access::address_space addressSpace = access::address_space::global_space> T cl::sycl::atomic< T, addressSpace >::load (memory_order Order = memory_order::relaxed) const inline
Definition at line 244 of file atomic.hpp.
References __spirv_AtomicLoad(), and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::atomic_load().
store()
template<typename T, access::address_space addressSpace = access::address_space::global_space> void cl::sycl::atomic< T, addressSpace >::store (T Operand, memory_order Order = memory_order::relaxed) inline
Definition at line 220 of file atomic.hpp.
References __spirv_AtomicLoad(), __spirv_AtomicStore(), cl::sycl::detail::bit_cast(), and cl::sycl::detail::getSPIRVMemorySemanticsMask().
Referenced by cl::sycl::atomic_store().
Friends And Related Function Documentation
atomic< T, access::address_space::global_space >
template<typename T, access::address_space addressSpace = access::address_space::global_space> friend class atomic< T, access::address_space::global_space > friend
Definition at line 176 of file atomic.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/atomic.hpp