DPC++ Runtime: sycl::_V1::detail::RTDeviceBinaryImage Class Reference
sycl::_V1::detail::RTDeviceBinaryImage Class Reference
#include <detail/device_binary_image.hpp>
Classes
class PropertyRange
Public Member Functions
RTDeviceBinaryImage ()
RTDeviceBinaryImage (sycl_device_binary Bin)
RTDeviceBinaryImage (const RTDeviceBinaryImage &)=delete
RTDeviceBinaryImage & operator= (const RTDeviceBinaryImage &)=delete
RTDeviceBinaryImage (RTDeviceBinaryImage &&)=default
RTDeviceBinaryImage & operator= (RTDeviceBinaryImage &&)=default
virtual ~RTDeviceBinaryImage ()
bool supportsSpecConstants () const
const sycl_device_binary_struct & getRawData () const
virtual void print () const
virtual void dump (std::ostream &Out) const
size_t getSize () const
const char * getCompileOptions () const
const char * getLinkOptions () const
ur::DeviceBinaryType getFormat () const
Returns the format of the binary image.
sycl_device_binary_property getProperty (const char *PropName) const
Returns a single property from SYCL_MISC_PROP category.
const PropertyRange & getSpecConstants () const
Gets the iterator range over specialization constants in this binary image.
const PropertyRange & getSpecConstantsDefaultValues () const
const PropertyRange & getDeviceLibReqMask () const
const PropertyRange & getKernelParamOptInfo () const
const PropertyRange & getAssertUsed () const
const PropertyRange & getProgramMetadata () const
const std::vector< ur_program_metadata_t > & getProgramMetadataUR () const
const PropertyRange & getExportedSymbols () const
const PropertyRange & getImportedSymbols () const
const PropertyRange & getDeviceGlobals () const
const PropertyRange & getDeviceRequirements () const
const PropertyRange & getHostPipes () const
const PropertyRange & getVirtualFunctions () const
std::uintptr_t getImageID () const
Protected Member Functions
void init (sycl_device_binary Bin)
sycl_device_binary get () const
Protected Attributes
sycl_device_binary Bin
ur::DeviceBinaryType Format = SYCL_DEVICE_BINARY_TYPE_NONE
RTDeviceBinaryImage::PropertyRange SpecConstIDMap
RTDeviceBinaryImage::PropertyRange SpecConstDefaultValuesMap
RTDeviceBinaryImage::PropertyRange DeviceLibReqMask
RTDeviceBinaryImage::PropertyRange KernelParamOptInfo
RTDeviceBinaryImage::PropertyRange AssertUsed
RTDeviceBinaryImage::PropertyRange ProgramMetadata
RTDeviceBinaryImage::PropertyRange ExportedSymbols
RTDeviceBinaryImage::PropertyRange ImportedSymbols
RTDeviceBinaryImage::PropertyRange DeviceGlobals
RTDeviceBinaryImage::PropertyRange DeviceRequirements
RTDeviceBinaryImage::PropertyRange HostPipes
RTDeviceBinaryImage::PropertyRange VirtualFunctions
std::vector< ur_program_metadata_t > ProgramMetadataUR
Detailed Description
Definition at line 87 of file device_binary_image.hpp.
Constructor & Destructor Documentation
RTDeviceBinaryImage() [1/4]
sycl::_V1::detail::RTDeviceBinaryImage::RTDeviceBinaryImage () inline
Definition at line 140 of file device_binary_image.hpp.
RTDeviceBinaryImage() [2/4]
sycl::_V1::detail::RTDeviceBinaryImage::RTDeviceBinaryImage (sycl_device_binary Bin) inline
Definition at line 141 of file device_binary_image.hpp.
References Bin, and init().
RTDeviceBinaryImage() [3/4]
sycl::_V1::detail::RTDeviceBinaryImage::RTDeviceBinaryImage (const RTDeviceBinaryImage &) delete
RTDeviceBinaryImage() [4/4]
sycl::_V1::detail::RTDeviceBinaryImage::RTDeviceBinaryImage (RTDeviceBinaryImage &&) default
~RTDeviceBinaryImage()
virtual sycl::_V1::detail::RTDeviceBinaryImage::~RTDeviceBinaryImage () inline virtual
Definition at line 150 of file device_binary_image.hpp.
Member Function Documentation
dump()
void sycl::_V1::detail::RTDeviceBinaryImage::dump (std::ostream & Out) const virtual
Definition at line 139 of file device_binary_image.cpp.
References Bin, sycl_device_binary_struct::BinaryStart, and getSize().
get()
sycl_device_binary sycl::_V1::detail::RTDeviceBinaryImage::get () const inline protected
Definition at line 238 of file device_binary_image.hpp.
References Bin.
Referenced by sycl::_V1::detail::ProgramManager::build(), getRawData(), and sycl::_V1::detail::SetKernelParamsAndLaunch().
getAssertUsed()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getAssertUsed () const inline
Definition at line 217 of file device_binary_image.hpp.
References AssertUsed.
getCompileOptions()
const char* sycl::_V1::detail::RTDeviceBinaryImage::getCompileOptions () const inline
Definition at line 166 of file device_binary_image.hpp.
References Bin, and sycl_device_binary_struct::CompileOptions.
Referenced by sycl::_V1::detail::appendCompileOptionsFromImage().
getDeviceGlobals()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getDeviceGlobals () const inline
Definition at line 224 of file device_binary_image.hpp.
References DeviceGlobals.
getDeviceLibReqMask()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getDeviceLibReqMask () const inline
Definition at line 213 of file device_binary_image.hpp.
References DeviceLibReqMask.
Referenced by sycl::_V1::detail::ProgramManager::getDeviceLibReqMask().
getDeviceRequirements()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getDeviceRequirements () const inline
Definition at line 225 of file device_binary_image.hpp.
References DeviceRequirements.
Referenced by sycl::_V1::detail::checkDevSupportDeviceRequirements().
getExportedSymbols()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getExportedSymbols () const inline
Definition at line 222 of file device_binary_image.hpp.
References ExportedSymbols.
getFormat()
ur::DeviceBinaryType sycl::_V1::detail::RTDeviceBinaryImage::getFormat () const inline
Returns the format of the binary image.
Definition at line 177 of file device_binary_image.hpp.
References Bin, and Format.
Referenced by sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::ProgramManager::createURProgram(), sycl::_V1::detail::ProgramManager::getBuiltURProgram(), and supportsSpecConstants().
getHostPipes()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getHostPipes () const inline
Definition at line 228 of file device_binary_image.hpp.
References HostPipes.
getImageID()
std::uintptr_t sycl::_V1::detail::RTDeviceBinaryImage::getImageID () const inline
Definition at line 231 of file device_binary_image.hpp.
References Bin.
Referenced by sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::ProgramManager::getBuiltURProgram(), and sycl::_V1::detail::context_impl::getProgramForHostPipe().
getImportedSymbols()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getImportedSymbols () const inline
Definition at line 223 of file device_binary_image.hpp.
References ImportedSymbols.
getKernelParamOptInfo()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getKernelParamOptInfo () const inline
Definition at line 214 of file device_binary_image.hpp.
References KernelParamOptInfo.
getLinkOptions()
const char* sycl::_V1::detail::RTDeviceBinaryImage::getLinkOptions () const inline
Definition at line 171 of file device_binary_image.hpp.
References Bin, and sycl_device_binary_struct::LinkOptions.
Referenced by sycl::_V1::detail::appendLinkOptionsFromImage().
getProgramMetadata()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getProgramMetadata () const inline
Definition at line 218 of file device_binary_image.hpp.
References ProgramMetadata.
getProgramMetadataUR()
const std::vector<ur_program_metadata_t>& sycl::_V1::detail::RTDeviceBinaryImage::getProgramMetadataUR () const inline
Definition at line 219 of file device_binary_image.hpp.
References ProgramMetadataUR.
Referenced by sycl::_V1::detail::ProgramManager::createURProgram().
getProperty()
sycl_device_binary_property sycl::_V1::detail::RTDeviceBinaryImage::getProperty (const char * PropName) const
Returns a single property from SYCL_MISC_PROP category.
Definition at line 145 of file device_binary_image.cpp.
References __SYCL_PROPERTY_SET_SYCL_MISC_PROP, sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::begin(), Bin, sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::end(), and sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::isAvailable().
Referenced by sycl::_V1::detail::appendCompileOptionsForGRFSizeProperties(), sycl::_V1::detail::getUint32PropAsBool(), sycl::_V1::detail::getUint32PropAsOptStr(), and sycl::_V1::detail::device_image_impl::specialization_constants_replaced_with_default().
getRawData()
const sycl_device_binary_struct& sycl::_V1::detail::RTDeviceBinaryImage::getRawData () const inline
Definition at line 156 of file device_binary_image.hpp.
References get().
Referenced by sycl::_V1::detail::device_image_impl::all_specialization_constant_native(), sycl::_V1::detail::CheckJITCompilationForImage(), sycl::_V1::detail::checkLinkingSupport(), sycl::_V1::detail::compatibleWithDevice(), sycl::_V1::detail::ProgramManager::createURProgram(), sycl::_V1::detail::getBinImageState(), and sycl::_V1::detail::ProgramManager::getDeviceImage().
getSize()
size_t sycl::_V1::detail::RTDeviceBinaryImage::getSize () const inline
Definition at line 161 of file device_binary_image.hpp.
References Bin, sycl_device_binary_struct::BinaryEnd, and sycl_device_binary_struct::BinaryStart.
Referenced by sycl::_V1::detail::ProgramManager::createURProgram(), dump(), and init().
getSpecConstants()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getSpecConstants () const inline
Gets the iterator range over specialization constants in this binary image.
For each property pointed to by an iterator within the range, the name of the property is the specialization constant symbolic ID and the value is a list of 3-element tuples of 32-bit unsigned integers, describing the specialization constant. This is done in order to unify representation of both scalar and composite specialization constants: composite specialization constant is represented by its leaf elements, so for scalars the list contains only a single tuple, while for composite there might be more of them. Each tuple consists of ID of scalar specialization constant, its location within a composite (offset in bytes from the beginning or 0 if it is not an element of a composite specialization constant) and its size. For example, for the following structure: struct A { int a; float b; }; struct POD { A a[2]; int b; }; List of tuples will look like: { ID0, 0, 4 }, // .a[0].a { ID1, 4, 4 }, // .a[0].b { ID2, 8, 4 }, // .a[1].a { ID3, 12, 4 }, // .a[1].b { ID4, 16, 4 }, // .b And for an interger specialization constant, the list of tuples will look like: { ID5, 0, 4 }
Definition at line 209 of file device_binary_image.hpp.
References SpecConstIDMap.
getSpecConstantsDefaultValues()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getSpecConstantsDefaultValues () const inline
Definition at line 210 of file device_binary_image.hpp.
References SpecConstDefaultValuesMap.
getVirtualFunctions()
const PropertyRange& sycl::_V1::detail::RTDeviceBinaryImage::getVirtualFunctions () const inline
Definition at line 229 of file device_binary_image.hpp.
References VirtualFunctions.
init()
void sycl::_V1::detail::RTDeviceBinaryImage::init (sycl_device_binary Bin) protected
Definition at line 160 of file device_binary_image.cpp.
References __SYCL_PROPERTY_SET_DEVICELIB_REQ_MASK, __SYCL_PROPERTY_SET_KERNEL_PARAM_OPT_INFO, __SYCL_PROPERTY_SET_PROGRAM_METADATA, __SYCL_PROPERTY_SET_SPEC_CONST_DEFAULT_VALUES_MAP, __SYCL_PROPERTY_SET_SPEC_CONST_MAP, __SYCL_PROPERTY_SET_SYCL_ASSERT_USED, __SYCL_PROPERTY_SET_SYCL_DEVICE_GLOBALS, __SYCL_PROPERTY_SET_SYCL_DEVICE_REQUIREMENTS, __SYCL_PROPERTY_SET_SYCL_EXPORTED_SYMBOLS, __SYCL_PROPERTY_SET_SYCL_HOST_PIPES, __SYCL_PROPERTY_SET_SYCL_IMPORTED_SYMBOLS, __SYCL_PROPERTY_SET_SYCL_VIRTUAL_FUNCTIONS, AssertUsed, Bin, sycl_device_binary_struct::BinaryStart, DeviceGlobals, DeviceLibReqMask, DeviceRequirements, ExportedSymbols, sycl_device_binary_struct::Format, Format, sycl::_V1::detail::ur::getBinaryImageFormat(), getSize(), HostPipes, ImportedSymbols, KernelParamOptInfo, sycl::_V1::detail::ur::mapDeviceBinaryPropertyToProgramMetadata(), ProgramMetadata, ProgramMetadataUR, SpecConstDefaultValuesMap, SpecConstIDMap, SYCL_DEVICE_BINARY_TYPE_NONE, and VirtualFunctions.
Referenced by sycl::_V1::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage(), and RTDeviceBinaryImage().
operator=() [1/2]
RTDeviceBinaryImage& sycl::_V1::detail::RTDeviceBinaryImage::operator= (const RTDeviceBinaryImage &) delete
operator=() [2/2]
RTDeviceBinaryImage& sycl::_V1::detail::RTDeviceBinaryImage::operator= (RTDeviceBinaryImage &&) default
print()
void sycl::_V1::detail::RTDeviceBinaryImage::print () const virtual
Reimplemented in sycl::_V1::detail::DynRTDeviceBinaryImage.
Definition at line 105 of file device_binary_image.cpp.
References Bin, sycl_device_binary_struct::BinaryEnd, sycl_device_binary_struct::BinaryStart, std::cerr, sycl_device_binary_struct::CompileOptions, sycl_device_binary_struct::DeviceTargetSpec, sycl_device_binary_struct::EntriesBegin, sycl_device_binary_struct::EntriesEnd, sycl_device_binary_struct::Format, sycl_device_binary_struct::Kind, sycl_device_binary_struct::LinkOptions, _sycl_device_binary_property_set_struct::Name, _sycl_device_binary_property_set_struct::PropertiesBegin, _sycl_device_binary_property_set_struct::PropertiesEnd, sycl_device_binary_struct::PropertySetsBegin, sycl_device_binary_struct::PropertySetsEnd, and sycl_device_binary_struct::Version.
Referenced by sycl::_V1::detail::ProgramManager::getDeviceImage(), and sycl::_V1::detail::DynRTDeviceBinaryImage::print().
supportsSpecConstants()
bool sycl::_V1::detail::RTDeviceBinaryImage::supportsSpecConstants () const inline
Definition at line 152 of file device_binary_image.hpp.
References getFormat(), and SYCL_DEVICE_BINARY_TYPE_SPIRV.
Referenced by sycl::_V1::detail::ProgramManager::getBuiltURProgram().
Member Data Documentation
AssertUsed
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::AssertUsed protected
Definition at line 247 of file device_binary_image.hpp.
Referenced by getAssertUsed(), and init().
Bin
sycl_device_binary sycl::_V1::detail::RTDeviceBinaryImage::Bin protected
Definition at line 240 of file device_binary_image.hpp.
Referenced by dump(), sycl::_V1::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage(), get(), getCompileOptions(), getFormat(), getImageID(), getLinkOptions(), getProperty(), getSize(), init(), print(), RTDeviceBinaryImage(), and sycl::_V1::detail::DynRTDeviceBinaryImage::~DynRTDeviceBinaryImage().
DeviceGlobals
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::DeviceGlobals protected
Definition at line 251 of file device_binary_image.hpp.
Referenced by getDeviceGlobals(), and init().
DeviceLibReqMask
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::DeviceLibReqMask protected
Definition at line 245 of file device_binary_image.hpp.
Referenced by getDeviceLibReqMask(), and init().
DeviceRequirements
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::DeviceRequirements protected
Definition at line 252 of file device_binary_image.hpp.
Referenced by getDeviceRequirements(), and init().
ExportedSymbols
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::ExportedSymbols protected
Definition at line 249 of file device_binary_image.hpp.
Referenced by getExportedSymbols(), and init().
Format
ur::DeviceBinaryType sycl::_V1::detail::RTDeviceBinaryImage::Format = SYCL_DEVICE_BINARY_TYPE_NONE protected
Definition at line 242 of file device_binary_image.hpp.
Referenced by getFormat(), and init().
HostPipes
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::HostPipes protected
Definition at line 253 of file device_binary_image.hpp.
Referenced by getHostPipes(), and init().
ImportedSymbols
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::ImportedSymbols protected
Definition at line 250 of file device_binary_image.hpp.
Referenced by getImportedSymbols(), and init().
KernelParamOptInfo
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::KernelParamOptInfo protected
Definition at line 246 of file device_binary_image.hpp.
Referenced by getKernelParamOptInfo(), and init().
ProgramMetadata
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::ProgramMetadata protected
Definition at line 248 of file device_binary_image.hpp.
Referenced by getProgramMetadata(), and init().
ProgramMetadataUR
std::vector<ur_program_metadata_t> sycl::_V1::detail::RTDeviceBinaryImage::ProgramMetadataUR protected
Definition at line 256 of file device_binary_image.hpp.
Referenced by getProgramMetadataUR(), and init().
SpecConstDefaultValuesMap
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::SpecConstDefaultValuesMap protected
Definition at line 244 of file device_binary_image.hpp.
Referenced by getSpecConstantsDefaultValues(), and init().
SpecConstIDMap
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::SpecConstIDMap protected
Definition at line 243 of file device_binary_image.hpp.
Referenced by getSpecConstants(), and init().
VirtualFunctions
RTDeviceBinaryImage::PropertyRange sycl::_V1::detail::RTDeviceBinaryImage::VirtualFunctions protected
Definition at line 254 of file device_binary_image.hpp.
Referenced by getVirtualFunctions(), and init().
The documentation for this class was generated from the following files:
source/detail/device_binary_image.hpp
source/detail/device_binary_image.cpp