DPC++ Runtime: cl::sycl::exception Class Reference
cl::sycl::exception Class Reference
DPC++ User API
#include <CL/sycl/exception.hpp>
Public Member Functions
__SYCL2020_DEPRECATED ("The version of an exception constructor which takes " "no arguments is deprecated.") exception()=default
exception (std::error_code, const char *Msg)
exception (std::error_code, const std::string &Msg)
exception (std::error_code)
exception (int, const std::error_category &, const std::string &)
exception (int, const std::error_category &, const char *)
exception (int, const std::error_category &)
exception (context, std::error_code, const std::string &)
exception (context, std::error_code, const char *)
exception (context, std::error_code)
exception (context, int, const std::error_category &, const std::string &)
exception (context, int, const std::error_category &, const char *)
exception (context, int, const std::error_category &)
const std::error_code & code () const noexcept
const std::error_category & category () const noexcept
const char * what () const noexcept final
bool has_context () const
context get_context () const
cl_int get_cl_code () const
Protected Member Functions
exception (const char *Msg, const cl_int CLErr, std::shared_ptr< context > Context=nullptr)
exception (const std::string &Msg, const cl_int CLErr, std::shared_ptr< context > Context=nullptr)
exception (std::error_code ec, const char *Msg, const cl_int CLErr, std::shared_ptr< context > Context=nullptr)
exception (std::error_code ec, const std::string &Msg, const cl_int CLErr, std::shared_ptr< context > Context=nullptr)
exception (const std::string &Msg)
exception (std::error_code ec, std::shared_ptr< context > SharedPtrCtx, const std::string &what_arg)
Detailed Description
Definition at line 63 of file exception.hpp.
Constructor & Destructor Documentation
exception() [1/18]
cl::sycl::exception::exception (std::error_code EC, const char * Msg)
Definition at line 24 of file exception.cpp.
exception() [2/18]
cl::sycl::exception::exception (std::error_code EC, const std::string & Msg)
Definition at line 27 of file exception.cpp.
exception() [3/18]
cl::sycl::exception::exception (std::error_code EC)
Definition at line 31 of file exception.cpp.
exception() [4/18]
cl::sycl::exception::exception (int EV, const std::error_category & ECat, const std::string & WhatArg)
Definition at line 33 of file exception.cpp.
exception() [5/18]
cl::sycl::exception::exception (int EV, const std::error_category & ECat, const char * WhatArg)
Definition at line 37 of file exception.cpp.
exception() [6/18]
cl::sycl::exception::exception (int EV, const std::error_category & ECat)
Definition at line 41 of file exception.cpp.
exception() [7/18]
cl::sycl::exception::exception (context Ctx, std::error_code EC, const std::string & WhatArg)
Definition at line 44 of file exception.cpp.
exception() [8/18]
cl::sycl::exception::exception (context Ctx, std::error_code EC, const char * WhatArg)
Definition at line 48 of file exception.cpp.
exception() [9/18]
cl::sycl::exception::exception (context Ctx, std::error_code EC)
Definition at line 51 of file exception.cpp.
exception() [10/18]
cl::sycl::exception::exception (context Ctx, int EV, const std::error_category & ECat, const std::string & WhatArg)
Definition at line 58 of file exception.cpp.
exception() [11/18]
cl::sycl::exception::exception (context Ctx, int EV, const std::error_category & ECat, const char * WhatArg)
Definition at line 54 of file exception.cpp.
exception() [12/18]
cl::sycl::exception::exception (context Ctx, int EV, const std::error_category & ECat)
Definition at line 62 of file exception.cpp.
exception() [13/18]
cl::sycl::exception::exception (const char * Msg, const cl_int CLErr, std::shared_ptr< context > Context = nullptr) inline protected
Definition at line 105 of file exception.hpp.
exception() [14/18]
cl::sycl::exception::exception (const std::string & Msg, const cl_int CLErr, std::shared_ptr< context > Context = nullptr) inline protected
Definition at line 108 of file exception.hpp.
exception() [15/18]
cl::sycl::exception::exception (std::error_code ec, const char * Msg, const cl_int CLErr, std::shared_ptr< context > Context = nullptr) inline protected
Definition at line 114 of file exception.hpp.
exception() [16/18]
cl::sycl::exception::exception (std::error_code ec, const std::string & Msg, const cl_int CLErr, std::shared_ptr< context > Context = nullptr) inline protected
Definition at line 118 of file exception.hpp.
exception() [17/18]
cl::sycl::exception::exception (const std::string & Msg) inline protected
Definition at line 124 of file exception.hpp.
exception() [18/18]
cl::sycl::exception::exception (std::error_code ec, std::shared_ptr< context > SharedPtrCtx, const std::string & what_arg) protected
Definition at line 66 of file exception.cpp.
References cl::sycl::detail::memcpy().
Member Function Documentation
__SYCL2020_DEPRECATED()
cl::sycl::exception::__SYCL2020_DEPRECATED ("The version of an exception constructor which takes " "no arguments is deprecated.") default
category()
const std::error_category & cl::sycl::exception::category () const noexcept
Definition at line 99 of file exception.cpp.
References code().
code()
const std::error_code & cl::sycl::exception::code () const noexcept
Definition at line 81 of file exception.cpp.
Referenced by category().
get_cl_code()
cl_int cl::sycl::exception::get_cl_code () const
Definition at line 114 of file exception.cpp.
Referenced by cl::sycl::detail::getOrBuild().
get_context()
context cl::sycl::exception::get_context () const
Definition at line 107 of file exception.cpp.
References has_context().
has_context()
bool cl::sycl::exception::has_context () const
Definition at line 105 of file exception.cpp.
Referenced by get_context().
what()
const char * cl::sycl::exception::what () const final noexcept
Definition at line 103 of file exception.cpp.
Referenced by cl::sycl::detail::getOrBuild().
The documentation for this class was generated from the following files:
include/CL/sycl/exception.hpp
source/exception.cpp