DPC++ Runtime: cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy > Class Template Reference
cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy > Class Template Reference
DPC++ Explicit SIMD API
The reference class.
#include <sycl/ext/intel/experimental/esimd/detail/region.hpp>
Public Types
using ShapeTy = typename shape_type< RegionTy >::type
using value_type = simd< typename ShapeTy::element_type, length >
The simd type if reading this simd_view object.
using vector_type = detail::vector_type_t< typename ShapeTy::element_type, length >
The underlying builtin value type.
using region_type = RegionTy
The region type of this class.
using element_type = typename ShapeTy::element_type
The element type of this class, which could be different from the element type of the base object type.
Public Member Functions
template<typename ToTy >
operator simd< ToTy, length > () const
Conversion to simd type.
value_type read () const
Read this simd_view object.
simd_view & write (const value_type &Val)
Write to this simd_view object.
template<typename EltTy >
auto bit_cast_view ()
View this object in a different element type.
template<typename EltTy >
auto format ()
template<typename EltTy , int Height, int Width>
auto bit_cast_view ()
View as a 2-dimensional simd_view.
template<typename EltTy , int Height, int Width>
auto format ()
template<int Size, int Stride, typename T = simd_view, typename = sycl::detail::enable_if_t<T::is1D()>>
auto select (uint16_t Offset=0)
1D region select, apply a region on top of this object.
template<int SizeY, int StrideY, int SizeX, int StrideX, typename T = simd_view, typename = sycl::detail::enable_if_t<T::is2D()>>
auto select (uint16_t OffsetY=0, uint16_t OffsetX=0)
2D region select, apply a region on top of this object.
simd_view & operator++ ()
value_type operator++ (int)
simd_view & operator-- ()
value_type operator-- (int)
template<typename T = simd_view, typename = sycl::detail::enable_if_t<T::is2D()>>
auto row (int i)
Reference a row from a 2D region.
template<typename T = simd_view, typename = sycl::detail::enable_if_t<T::is2D()>>
auto column (int i)
Reference a column from a 2D region.
template<typename T = simd_view, typename = sycl::detail::enable_if_t<T::is1D()>>
element_type operator[] (int i) const
Read a single element from a 1D region, by value only.
template<typename T1 = element_type, typename T2 = BaseTy, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>>
uint16_t any ()
Any operation.
template<typename T1 = element_type, typename T2 = BaseTy, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>>
uint16_t all ()
All operation.
simd_view & operator= (const simd_view &Other)
simd_view & operator= (const value_type &Val)
void merge (const value_type &Val, const mask_type_t< length > &Mask)
void merge (const value_type &Val1, value_type Val2, const mask_type_t< length > &Mask)
Replicate
Replicate simd instance given a simd_view
template<int Rep>
simd< element_type, Rep > replicate ()
template<int Rep, int W>
simd< element_type, Rep *W > replicate (uint16_t OffsetX)
template<int Rep, int W>
simd< element_type, Rep *W > replicate (uint16_t OffsetY, uint16_t OffsetX)
template<int Rep, int VS, int W>
simd< element_type, Rep *W > replicate (uint16_t OffsetX)
template<int Rep, int VS, int W>
simd< element_type, Rep *W > replicate (uint16_t OffsetY, uint16_t OffsetX)
template<int Rep, int VS, int W, int HS>
simd< element_type, Rep *W > replicate (uint16_t OffsetX)
template<int Rep, int VS, int W, int HS>
simd< element_type, Rep *W > replicate (uint16_t OffsetY, uint16_t OffsetX)
Static Public Attributes
static constexpr int length = ShapeTy::Size_x * ShapeTy::Size_y
Friends
template<typename , int >
class simd
template<typename , typename >
class simd_view
simd_view (const simd_view &Other)=delete
simd_view (simd_view &&Other)=delete
constexpr uint16_t getOffsetX () const
constexpr uint16_t getOffsetY () const
static constexpr bool is1D ()
static constexpr bool is2D ()
static constexpr int getSizeX ()
static constexpr int getStrideX ()
static constexpr int getSizeY ()
static constexpr int getStrideY ()
Detailed Description
template<typename BaseTy, typename RegionTy>
class cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >
The reference class.
This class represents a region applied to a base object, which must be a simd object.
Definition at line 60 of file region.hpp.
Member Typedef Documentation
element_type
template<typename BaseTy , typename RegionTy > using cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::element_type = typename ShapeTy::element_type
The element type of this class, which could be different from the element type of the base object type.
Definition at line 51 of file simd_view.hpp.
region_type
template<typename BaseTy , typename RegionTy > using cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::region_type = RegionTy
The region type of this class.
Definition at line 47 of file simd_view.hpp.
ShapeTy
template<typename BaseTy , typename RegionTy > using cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::ShapeTy = typename shape_type<RegionTy>::type
Definition at line 36 of file simd_view.hpp.
value_type
template<typename BaseTy , typename RegionTy > using cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::value_type = simd<typename ShapeTy::element_type, length>
The simd type if reading this simd_view object.
Definition at line 40 of file simd_view.hpp.
vector_type
template<typename BaseTy , typename RegionTy > using cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::vector_type = detail::vector_type_t<typename ShapeTy::element_type, length>
The underlying builtin value type.
Definition at line 44 of file simd_view.hpp.
Constructor & Destructor Documentation
simd_view() [1/2]
template<typename BaseTy , typename RegionTy > cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::simd_view (const simd_view< BaseTy, RegionTy > & Other) delete
simd_view() [2/2]
template<typename BaseTy , typename RegionTy > cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::simd_view (simd_view< BaseTy, RegionTy > && Other) delete
Member Function Documentation
all()
template<typename BaseTy , typename RegionTy > template<typename T1 = element_type, typename T2 = BaseTy, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>> uint16_t cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::all () inline
All operation.
Returns
1 if all elements are set, 0 otherwise.
Definition at line 446 of file simd_view.hpp.
any()
template<typename BaseTy , typename RegionTy > template<typename T1 = element_type, typename T2 = BaseTy, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>> uint16_t cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::any () inline
Any operation.
Returns
1 if any element is set, 0 otherwise.
Definition at line 436 of file simd_view.hpp.
bit_cast_view() [1/2]
template<typename BaseTy , typename RegionTy > template<typename EltTy > auto cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::bit_cast_view () inline
View this object in a different element type.
Definition at line 123 of file simd_view.hpp.
bit_cast_view() [2/2]
template<typename BaseTy , typename RegionTy > template<typename EltTy , int Height, int Width> auto cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::bit_cast_view () inline
View as a 2-dimensional simd_view.
Definition at line 138 of file simd_view.hpp.
column()
template<typename BaseTy , typename RegionTy > template<typename T = simd_view, typename = sycl::detail::enable_if_t<T::is2D()>> auto cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::column (int i) inline
Reference a column from a 2D region.
Returns
a 2D region.
Definition at line 343 of file simd_view.hpp.
format() [1/2]
template<typename BaseTy , typename RegionTy > template<typename EltTy > auto cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::format () inline
Definition at line 133 of file simd_view.hpp.
format() [2/2]
template<typename BaseTy , typename RegionTy > template<typename EltTy , int Height, int Width> auto cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::format () inline
Definition at line 149 of file simd_view.hpp.
getOffsetX()
template<typename BaseTy , typename RegionTy > constexpr uint16_t cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::getOffsetX () const inline constexpr
Definition at line 88 of file simd_view.hpp.
References cl::sycl::ext::intel::experimental::esimd::getTopRegion().
getOffsetY()
template<typename BaseTy , typename RegionTy > constexpr uint16_t cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::getOffsetY () const inline constexpr
Definition at line 91 of file simd_view.hpp.
References cl::sycl::ext::intel::experimental::esimd::getTopRegion().
getSizeX()
template<typename BaseTy , typename RegionTy > static constexpr int cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::getSizeX () inline static constexpr
Definition at line 84 of file simd_view.hpp.
getSizeY()
template<typename BaseTy , typename RegionTy > static constexpr int cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::getSizeY () inline static constexpr
Definition at line 86 of file simd_view.hpp.
getStrideX()
template<typename BaseTy , typename RegionTy > static constexpr int cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::getStrideX () inline static constexpr
Definition at line 85 of file simd_view.hpp.
getStrideY()
template<typename BaseTy , typename RegionTy > static constexpr int cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::getStrideY () inline static constexpr
Definition at line 87 of file simd_view.hpp.
is1D()
template<typename BaseTy , typename RegionTy > static constexpr bool cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::is1D () inline static constexpr
Region accessors.
Definition at line 82 of file simd_view.hpp.
is2D()
template<typename BaseTy , typename RegionTy > static constexpr bool cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::is2D () inline static constexpr
Definition at line 83 of file simd_view.hpp.
merge() [1/2]
template<typename BaseTy , typename RegionTy > void cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::merge (const value_type & Val, const mask_type_t< length > & Mask) inline
Whole region update with predicates.
Definition at line 111 of file simd_view.hpp.
merge() [2/2]
template<typename BaseTy , typename RegionTy > void cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::merge (const value_type & Val1, value_type Val2, const mask_type_t< length > & Mask) inline
Definition at line 115 of file simd_view.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::read(), and cl::sycl::detail::write().
operator simd< ToTy, length >()
template<typename BaseTy , typename RegionTy > template<typename ToTy > cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator simd< ToTy, length > () const inline
Conversion to simd type.
Definition at line 67 of file simd_view.hpp.
operator++() [1/2]
template<typename BaseTy , typename RegionTy > simd_view& cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator++ () inline
Definition at line 311 of file simd_view.hpp.
operator++() [2/2]
template<typename BaseTy , typename RegionTy > value_type cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator++ (int) inline
Definition at line 315 of file simd_view.hpp.
operator--() [1/2]
template<typename BaseTy , typename RegionTy > simd_view& cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator-- () inline
Definition at line 320 of file simd_view.hpp.
operator--() [2/2]
template<typename BaseTy , typename RegionTy > value_type cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator-- (int) inline
Definition at line 324 of file simd_view.hpp.
operator=() [1/2]
template<typename BaseTy , typename RegionTy > simd_view& cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator= (const simd_view< BaseTy, RegionTy > & Other) inline
Assignment operators.
Definition at line 76 of file simd_view.hpp.
References cl::sycl::detail::write().
operator=() [2/2]
template<typename BaseTy , typename RegionTy > simd_view& cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator= (const value_type & Val) inline
Definition at line 77 of file simd_view.hpp.
References cl::sycl::detail::write().
operator[]()
template<typename BaseTy , typename RegionTy > template<typename T = simd_view, typename = sycl::detail::enable_if_t<T::is1D()>> element_type cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator[] (int i) const inline
Read a single element from a 1D region, by value only.
Definition at line 350 of file simd_view.hpp.
read()
template<typename BaseTy , typename RegionTy > value_type cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::read () const inline
Read this simd_view object.
Definition at line 97 of file simd_view.hpp.
References cl::sycl::length().
replicate() [1/7]
template<typename BaseTy , typename RegionTy > template<int Rep> simd<element_type, Rep> cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::replicate () inline
Template Parameters
Rep is number of times region has to be replicated.
Definition at line 360 of file simd_view.hpp.
replicate() [2/7]
template<typename BaseTy , typename RegionTy > template<int Rep, int W> simd<element_type, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::replicate (uint16_t OffsetX) inline
Template Parameters
Rep is number of times region has to be replicated.
W is width of src region to replicate.
Parameters
OffsetX is column offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 369 of file simd_view.hpp.
replicate() [3/7]
template<typename BaseTy , typename RegionTy > template<int Rep, int VS, int W> simd<element_type, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::replicate (uint16_t OffsetX) inline
Template Parameters
Rep is number of times region has to be replicated.
VS is vertical stride of src region to replicate.
W is width of src region to replicate.
Parameters
OffsetX is column offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 389 of file simd_view.hpp.
replicate() [4/7]
template<typename BaseTy , typename RegionTy > template<int Rep, int VS, int W, int HS> simd<element_type, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::replicate (uint16_t OffsetX) inline
Template Parameters
Rep is number of times region has to be replicated.
VS is vertical stride of src region to replicate.
W is width of src region to replicate.
HS is horizontal stride of src region to replicate.
Parameters
OffsetX is column offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 411 of file simd_view.hpp.
replicate() [5/7]
template<typename BaseTy , typename RegionTy > template<int Rep, int W> simd<element_type, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::replicate (uint16_t OffsetY, uint16_t OffsetX) inline
Template Parameters
Rep is number of times region has to be replicated.
W is width of src region to replicate.
Parameters
OffsetX is column offset in number of elements in src region.
OffsetY is row offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 379 of file simd_view.hpp.
replicate() [6/7]
template<typename BaseTy , typename RegionTy > template<int Rep, int VS, int W> simd<element_type, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::replicate (uint16_t OffsetY, uint16_t OffsetX) inline
Template Parameters
Rep is number of times region has to be replicated.
VS is vertical stride of src region to replicate.
W is width of src region to replicate.
Parameters
OffsetX is column offset in number of elements in src region.
OffsetY is row offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 400 of file simd_view.hpp.
replicate() [7/7]
template<typename BaseTy , typename RegionTy > template<int Rep, int VS, int W, int HS> simd<element_type, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::replicate (uint16_t OffsetY, uint16_t OffsetX) inline
Template Parameters
Rep is number of times region has to be replicated.
VS is vertical stride of src region to replicate.
W is width of src region to replicate.
HS is horizontal stride of src region to replicate.
Parameters
OffsetX is column offset in number of elements in src region.
OffsetY is row offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 423 of file simd_view.hpp.
row()
template<typename BaseTy , typename RegionTy > template<typename T = simd_view, typename = sycl::detail::enable_if_t<T::is2D()>> auto cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::row (int i) inline
Reference a row from a 2D region.
Returns
a 1D region.
Definition at line 334 of file simd_view.hpp.
select() [1/2]
template<typename BaseTy , typename RegionTy > template<int Size, int Stride, typename T = simd_view, typename = sycl::detail::enable_if_t<T::is1D()>> auto cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::select (uint16_t Offset = 0) inline
1D region select, apply a region on top of this object.
Parameters
Size is the number of elements to be selected.
Template Parameters
Stride is the element distance between two consecutive elements.
Parameters
Offset is the starting element offset.
Returns
the representing region object.
Definition at line 161 of file simd_view.hpp.
select() [2/2]
template<typename BaseTy , typename RegionTy > template<int SizeY, int StrideY, int SizeX, int StrideX, typename T = simd_view, typename = sycl::detail::enable_if_t<T::is2D()>> auto cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::select (uint16_t OffsetY = 0, uint16_t OffsetX = 0) inline
2D region select, apply a region on top of this object.
Template Parameters
SizeX is the number of elements to be selected in X-dimension.
StrideX is the element distance between two consecutive elements in X-dimension.
SizeY is the number of elements to be selected in Y-dimension.
StrideY is the element distance between two consecutive elements Y-dimension.
Parameters
OffsetX is the starting element offset in X-dimension.
OffsetY is the starting element offset in Y-dimension.
Returns
the representing region object.
Definition at line 183 of file simd_view.hpp.
write()
template<typename BaseTy , typename RegionTy > simd_view& cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::write (const value_type & Val) inline
Write to this simd_view object.
Definition at line 104 of file simd_view.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
Friends And Related Function Documentation
simd
template<typename BaseTy , typename RegionTy > template<typename , int > friend class simd friend
Definition at line 30 of file simd_view.hpp.
simd_view
template<typename BaseTy , typename RegionTy > template<typename , typename > friend class simd_view friend
Definition at line 31 of file simd_view.hpp.
Member Data Documentation
length
template<typename BaseTy , typename RegionTy > constexpr int cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::length = ShapeTy::Size_x * ShapeTy::Size_y static constexpr
Definition at line 37 of file simd_view.hpp.
The documentation for this class was generated from the following files:
include/sycl/ext/intel/experimental/esimd/detail/region.hpp
include/sycl/ext/intel/experimental/esimd/simd_view.hpp