DPC++ Runtime: sycl::_V1::detail::aligned_allocator< T > Class Template Reference
sycl::_V1::detail::aligned_allocator< T > Class Template Reference
#include <sycl/detail/aligned_allocator.hpp>
Classes
struct rebind
Public Types
using value_type = T
using pointer = T *
using const_pointer = const T *
using reference = T &
using const_reference = const T &
Public Member Functions
aligned_allocator ()=default
~aligned_allocator ()=default
aligned_allocator (size_t Alignment)
void construct (pointer Ptr, const_reference Val)
void destroy (pointer Ptr)
pointer address (reference Val) const
const_pointer address (const_reference Val)
pointer allocate (size_t Size)
void deallocate (pointer Ptr, size_t)
bool operator== (const aligned_allocator &)
bool operator!= (const aligned_allocator &)
void setAlignment (size_t Alignment)
Detailed Description
template<typename T>
class sycl::_V1::detail::aligned_allocator< T >
Definition at line 22 of file aligned_allocator.hpp.
Member Typedef Documentation
const_pointer
template<typename T > using sycl::_V1::detail::aligned_allocator< T >::const_pointer = const T *
Definition at line 26 of file aligned_allocator.hpp.
const_reference
template<typename T > using sycl::_V1::detail::aligned_allocator< T >::const_reference = const T &
Definition at line 28 of file aligned_allocator.hpp.
pointer
template<typename T > using sycl::_V1::detail::aligned_allocator< T >::pointer = T *
Definition at line 25 of file aligned_allocator.hpp.
reference
template<typename T > using sycl::_V1::detail::aligned_allocator< T >::reference = T &
Definition at line 27 of file aligned_allocator.hpp.
value_type
template<typename T > using sycl::_V1::detail::aligned_allocator< T >::value_type = T
Definition at line 24 of file aligned_allocator.hpp.
Constructor & Destructor Documentation
aligned_allocator() [1/2]
template<typename T > sycl::_V1::detail::aligned_allocator< T >::aligned_allocator () default
~aligned_allocator()
template<typename T > sycl::_V1::detail::aligned_allocator< T >::~aligned_allocator () default
aligned_allocator() [2/2]
template<typename T > sycl::_V1::detail::aligned_allocator< T >::aligned_allocator (size_t Alignment) inline explicit
Definition at line 38 of file aligned_allocator.hpp.
Member Function Documentation
address() [1/2]
template<typename T > const_pointer sycl::_V1::detail::aligned_allocator< T >::address (const_reference Val) inline
Definition at line 49 of file aligned_allocator.hpp.
address() [2/2]
template<typename T > pointer sycl::_V1::detail::aligned_allocator< T >::address (reference Val) const inline
Definition at line 48 of file aligned_allocator.hpp.
allocate()
template<typename T > pointer sycl::_V1::detail::aligned_allocator< T >::allocate (size_t Size) inline
Definition at line 52 of file aligned_allocator.hpp.
References sycl::_V1::detail::OSUtil::alignedAlloc().
Referenced by sycl::_V1::detail::usm::alignedAllocHost(), and sycl::_V1::detail::usm::alignedAllocInternal().
construct()
template<typename T > void sycl::_V1::detail::aligned_allocator< T >::construct (pointer Ptr, const_reference Val) inline
Definition at line 41 of file aligned_allocator.hpp.
deallocate()
template<typename T > void sycl::_V1::detail::aligned_allocator< T >::deallocate (pointer Ptr, size_t) inline
Definition at line 66 of file aligned_allocator.hpp.
References sycl::_V1::detail::OSUtil::alignedFree().
destroy()
template<typename T > void sycl::_V1::detail::aligned_allocator< T >::destroy (pointer Ptr) inline
Definition at line 46 of file aligned_allocator.hpp.
operator!=()
template<typename T > bool sycl::_V1::detail::aligned_allocator< T >::operator!= (const aligned_allocator< T > &) inline
Definition at line 72 of file aligned_allocator.hpp.
operator==()
template<typename T > bool sycl::_V1::detail::aligned_allocator< T >::operator== (const aligned_allocator< T > &) inline
Definition at line 71 of file aligned_allocator.hpp.
setAlignment()
template<typename T > void sycl::_V1::detail::aligned_allocator< T >::setAlignment (size_t Alignment) inline
Definition at line 74 of file aligned_allocator.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment.
The documentation for this class was generated from the following file:
include/sycl/detail/aligned_allocator.hpp