DPC++ Runtime: ZeUSMImportExtension Class Reference
ZeUSMImportExtension Class Reference
Public Member Functions
ZeUSMImportExtension ()
void setZeUSMImport (pi_platform Platform)
void doZeUSMImport (ze_driver_handle_t driverHandle, void *HostPtr, size_t Size)
void doZeUSMRelease (ze_driver_handle_t driverHandle, void *HostPtr)
Public Attributes
bool Enabled
Detailed Description
Definition at line 1702 of file pi_level_zero.cpp.
Constructor & Destructor Documentation
ZeUSMImportExtension()
ZeUSMImportExtension::ZeUSMImportExtension () inline
Definition at line 1712 of file pi_level_zero.cpp.
Member Function Documentation
doZeUSMImport()
void ZeUSMImportExtension::doZeUSMImport (ze_driver_handle_t driverHandle, void * HostPtr, size_t Size) inline
Definition at line 1740 of file pi_level_zero.cpp.
References ZE_CALL_NOCHECK.
Referenced by piMemBufferCreate().
doZeUSMRelease()
void ZeUSMImportExtension::doZeUSMRelease (ze_driver_handle_t driverHandle, void * HostPtr) inline
Definition at line 1745 of file pi_level_zero.cpp.
References ZE_CALL_NOCHECK.
Referenced by piMemRelease().
setZeUSMImport()
void ZeUSMImportExtension::setZeUSMImport (pi_platform Platform) inline
Definition at line 1714 of file pi_level_zero.cpp.
References setEnvVar(), ZE_CALL_NOCHECK, and _pi_platform::ZeDriver.
Referenced by _pi_platform::initialize().
Member Data Documentation
Enabled
bool ZeUSMImportExtension::Enabled
Definition at line 1710 of file pi_level_zero.cpp.
Referenced by piMemBufferCreate().
The documentation for this class was generated from the following file:
plugins/level_zero/pi_level_zero.cpp