DPC++ Runtime: sycl::_V1::detail::DynRTDeviceBinaryImage Class Reference
sycl::_V1::detail::DynRTDeviceBinaryImage Class Reference
#include <detail/device_binary_image.hpp>
Public Member Functions
DynRTDeviceBinaryImage (std::unique_ptr< char[]> &&DataPtr, size_t DataSize)
~DynRTDeviceBinaryImage () override
void print () const override
Public Member Functions inherited from sycl::_V1::detail::RTDeviceBinaryImage
RTDeviceBinaryImage ()
RTDeviceBinaryImage (pi_device_binary Bin)
RTDeviceBinaryImage (const RTDeviceBinaryImage &)=delete
RTDeviceBinaryImage & operator= (const RTDeviceBinaryImage &)=delete
RTDeviceBinaryImage (RTDeviceBinaryImage &&)=default
RTDeviceBinaryImage & operator= (RTDeviceBinaryImage &&)=default
virtual ~RTDeviceBinaryImage ()
bool supportsSpecConstants () const
const pi_device_binary_struct & getRawData () const
virtual void dump (std::ostream &Out) const
size_t getSize () const
const char * getCompileOptions () const
const char * getLinkOptions () const
pi::PiDeviceBinaryType getFormat () const
Returns the format of the binary image.
pi_device_binary_property getProperty (const char *PropName) const
Returns a single property from SYCL_MISC_PROP category.
const PropertyRange & getSpecConstants () const
Gets the iterator range over specialization constants in this binary image.
const PropertyRange & getSpecConstantsDefaultValues () const
const PropertyRange & getDeviceLibReqMask () const
const PropertyRange & getKernelParamOptInfo () const
const PropertyRange & getAssertUsed () const
const PropertyRange & getProgramMetadata () const
const PropertyRange & getExportedSymbols () const
const PropertyRange & getDeviceGlobals () const
const PropertyRange & getDeviceRequirements () const
const PropertyRange & getHostPipes () const
std::uintptr_t getImageID () const
Protected Attributes
std::unique_ptr< char[]> Data
Protected Attributes inherited from sycl::_V1::detail::RTDeviceBinaryImage
pi_device_binary Bin
pi::PiDeviceBinaryType Format = PI_DEVICE_BINARY_TYPE_NONE
RTDeviceBinaryImage::PropertyRange SpecConstIDMap
RTDeviceBinaryImage::PropertyRange SpecConstDefaultValuesMap
RTDeviceBinaryImage::PropertyRange DeviceLibReqMask
RTDeviceBinaryImage::PropertyRange KernelParamOptInfo
RTDeviceBinaryImage::PropertyRange AssertUsed
RTDeviceBinaryImage::PropertyRange ProgramMetadata
RTDeviceBinaryImage::PropertyRange ExportedSymbols
RTDeviceBinaryImage::PropertyRange DeviceGlobals
RTDeviceBinaryImage::PropertyRange DeviceRequirements
RTDeviceBinaryImage::PropertyRange HostPipes
Additional Inherited Members
Protected Member Functions inherited from sycl::_V1::detail::RTDeviceBinaryImage
void init (pi_device_binary Bin)
pi_device_binary get () const
Detailed Description
Definition at line 251 of file device_binary_image.hpp.
Constructor & Destructor Documentation
DynRTDeviceBinaryImage()
sycl::_V1::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage (std::unique_ptr< char[]> && DataPtr, size_t DataSize)
Definition at line 186 of file device_binary_image.cpp.
References __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64, __SYCL_PI_DEVICE_BINARY_TARGET_UNKNOWN, sycl::_V1::detail::RTDeviceBinaryImage::Bin, pi_device_binary_struct::BinaryEnd, pi_device_binary_struct::BinaryStart, pi_device_binary_struct::CompileOptions, Data, pi_device_binary_struct::DeviceTargetSpec, pi_device_binary_struct::EntriesBegin, pi_device_binary_struct::EntriesEnd, pi_device_binary_struct::Format, sycl::_V1::detail::pi::getBinaryImageFormat(), sycl::_V1::detail::RTDeviceBinaryImage::init(), pi_device_binary_struct::Kind, pi_device_binary_struct::LinkOptions, pi_device_binary_struct::ManifestEnd, pi_device_binary_struct::ManifestStart, PI_DEVICE_BINARY_OFFLOAD_KIND_SYCL, PI_DEVICE_BINARY_TYPE_SPIRV, PI_DEVICE_BINARY_VERSION, and pi_device_binary_struct::Version.
~DynRTDeviceBinaryImage()
sycl::_V1::detail::DynRTDeviceBinaryImage::~DynRTDeviceBinaryImage () override
Definition at line 212 of file device_binary_image.cpp.
References sycl::_V1::detail::RTDeviceBinaryImage::Bin.
Member Function Documentation
print()
void sycl::_V1::detail::DynRTDeviceBinaryImage::print () const inline override virtual
Reimplemented from sycl::_V1::detail::RTDeviceBinaryImage.
Definition at line 256 of file device_binary_image.hpp.
References std::cerr, and sycl::_V1::detail::RTDeviceBinaryImage::print().
Member Data Documentation
Data
std::unique_ptr<char[]> sycl::_V1::detail::DynRTDeviceBinaryImage::Data protected
Definition at line 262 of file device_binary_image.hpp.
Referenced by DynRTDeviceBinaryImage().
The documentation for this class was generated from the following files:
source/detail/device_binary_image.hpp
source/detail/device_binary_image.cpp