DPC++ Runtime: ConvertHelper Class Reference
ConvertHelper Class Reference
#include <unified_runtime/pi2ur.hpp>
Public Member Functions
template<typename TypeUR , typename TypePI >
pi_result convert (std::function< TypePI(TypeUR)> Func)
template<typename TypeUR , typename TypePI >
pi_result convertArray (std::function< TypePI(TypeUR)> Func)
template<typename TypeUR , typename TypePI >
pi_result convertBitSet (std::function< TypePI(TypeUR)> Func)
Public Member Functions inherited from ReturnHelper
template<class T >
pi_result operator() (const T &t)
template<class T >
pi_result operator() (const T *t, size_t s)
template<class RetType , class T >
pi_result operator() (const T *t, size_t s)
Detailed Description
Definition at line 186 of file pi2ur.hpp.
Member Function Documentation
convert()
template<typename TypeUR , typename TypePI > pi_result ConvertHelper::convert (std::function< TypePI(TypeUR)> Func) inline
Definition at line 192 of file pi2ur.hpp.
References PI_ASSERT.
Referenced by convertBitSet(), ur2piDeviceInfoValue(), ur2piPlatformInfoValue(), ur2piProgramBuildInfoValue(), ur2piSamplerInfoValue(), and ur2piUSMAllocInfoValue().
convertArray()
template<typename TypeUR , typename TypePI > pi_result ConvertHelper::convertArray (std::function< TypePI(TypeUR)> Func) inline
Definition at line 211 of file pi2ur.hpp.
References sycl::_V1::detail::memcpy(), and PI_ASSERT.
Referenced by ur2piDeviceInfoValue().
convertBitSet()
template<typename TypeUR , typename TypePI > pi_result ConvertHelper::convertBitSet (std::function< TypePI(TypeUR)> Func) inline
Definition at line 245 of file pi2ur.hpp.
References convert(), and PI_ASSERT.
Referenced by ur2piDeviceInfoValue().
The documentation for this class was generated from the following file:
plugins/unified_runtime/pi2ur.hpp