DPC++ Runtime: cl::sycl::ext::intel::experimental::lsu< _mem_access_params > Class Template Reference
cl::sycl::ext::intel::experimental::lsu< _mem_access_params > Class Template Reference final
#include <sycl/ext/intel/experimental/fpga_lsu.hpp>
Public Member Functions
lsu ()=delete
Static Public Member Functions
template<class... _Params, typename _T , access::address_space _space>
static _T load (sycl::multi_ptr< _T, _space > Ptr)
template<class... _Params, typename _T , access::address_space _space>
static void store (sycl::multi_ptr< _T, _space > Ptr, _T Val)
Detailed Description
template<class... _mem_access_params>
class cl::sycl::ext::intel::experimental::lsu< _mem_access_params >
Definition at line 49 of file fpga_lsu.hpp.
Constructor & Destructor Documentation
lsu()
template<class... _mem_access_params> cl::sycl::ext::intel::experimental::lsu< _mem_access_params >::lsu () delete
Member Function Documentation
load()
template<class... _mem_access_params> template<class... _Params, typename _T , access::address_space _space> static _T cl::sycl::ext::intel::experimental::lsu< _mem_access_params >::load (sycl::multi_ptr< _T, _space > Ptr) inline static
Definition at line 54 of file fpga_lsu.hpp.
References max(), and min().
store()
template<class... _mem_access_params> template<class... _Params, typename _T , access::address_space _space> static void cl::sycl::ext::intel::experimental::lsu< _mem_access_params >::store (sycl::multi_ptr< _T, _space > Ptr, _T Val) inline static
Definition at line 84 of file fpga_lsu.hpp.
References max(), and min().
The documentation for this class was generated from the following file:
include/sycl/ext/intel/experimental/fpga_lsu.hpp