DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph Class Reference
sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph Class Reference
#include <sycl/ext/oneapi/experimental/graph.hpp>
Public Member Functions
executable_command_graph ()=delete
An executable command-graph is not user constructable.
void update (const command_graph< graph_state::modifiable > &Graph)
Update the inputs & output of the graph.
void update (const node &Node)
Updates a single node in this graph based on the contents of the provided node.
void update (const std::vector< node > &Nodes)
Updates a number of nodes in this graph based on the contents of the provided nodes.
Protected Member Functions
executable_command_graph (const std::shared_ptr< detail::graph_impl > &Graph, const sycl::context &Ctx, const property_list &PropList={})
Constructor used by internal runtime.
template<class Obj >
decltype(Obj::impl) friend sycl::detail::getSyclObjImpl (const Obj &SyclObject)
void finalizeImpl ()
Creates a backend representation of the graph in impl member variable.
Protected Attributes
std::shared_ptr< detail::exec_graph_impl > impl
Detailed Description
Definition at line 353 of file graph.hpp.
Constructor & Destructor Documentation
executable_command_graph() [1/2]
sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::executable_command_graph () delete
An executable command-graph is not user constructable.
executable_command_graph() [2/2]
sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::executable_command_graph (const std::shared_ptr< detail::graph_impl > & Graph, const sycl::context & Ctx, const property_list & PropList = {}) protected
Constructor used by internal runtime.
Parameters
Graph Detail implementation class to construct with.
Ctx Context to use for graph.
PropList Optional list of properties to pass.
Definition at line 1628 of file graph_impl.cpp.
References finalizeImpl().
Member Function Documentation
finalizeImpl()
void sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::finalizeImpl () protected
Creates a backend representation of the graph in impl member variable.
Definition at line 1635 of file graph_impl.cpp.
References impl.
Referenced by executable_command_graph().
sycl::detail::getSyclObjImpl()
template<class Obj > decltype(Obj::impl) friend sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::sycl::detail::getSyclObjImpl (const Obj & SyclObject) protected
update() [1/3]
void sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::update (const command_graph< graph_state::modifiable > & Graph)
Update the inputs & output of the graph.
Parameters
Graph Graph to use the inputs and outputs of.
Definition at line 1646 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and impl.
update() [2/3]
void sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::update (const node & Node)
Updates a single node in this graph based on the contents of the provided node.
Parameters
Node The node to use for updating the graph.
Definition at line 1651 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and impl.
update() [3/3]
void sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::update (const std::vector< node > & Nodes)
Updates a number of nodes in this graph based on the contents of the provided nodes.
Parameters
Nodes The nodes to use for updating the graph.
Definition at line 1655 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and impl.
Member Data Documentation
impl
std::shared_ptr<detail::exec_graph_impl> sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::impl protected
Definition at line 388 of file graph.hpp.
Referenced by finalizeImpl(), and update().
The documentation for this class was generated from the following files:
include/sycl/ext/oneapi/experimental/graph.hpp
source/detail/graph_impl.cpp