DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::default_sorters::group_key_value_sorter< KeyTy, ValueTy, CompareT, ElementsPerWorkItem > Class Template Reference
sycl::_V1::ext::oneapi::experimental::default_sorters::group_key_value_sorter< KeyTy, ValueTy, CompareT, ElementsPerWorkItem > Class Template Reference
#include <sycl/ext/oneapi/experimental/group_helpers_sorters.hpp>
Public Member Functions
template<std::size_t Extent>
group_key_value_sorter (sycl::span< std::byte, Extent > scratch_, CompareT comp_={})
template<typename Group >
std::tuple< KeyTy, ValueTy > operator() ([[maybe_unused]] Group g, KeyTy key, ValueTy value)
template<typename Group , typename Properties >
void operator() ([[maybe_unused]] Group g, [[maybe_unused]] sycl::span< KeyTy, ElementsPerWorkItem > keys, [[maybe_unused]] sycl::span< ValueTy, ElementsPerWorkItem > values, [[maybe_unused]] Properties property)
Static Public Member Functions
static std::size_t memory_required ([[maybe_unused]] sycl::memory_scope scope, std::size_t range_size)
Detailed Description
template<typename KeyTy, typename ValueTy, typename CompareT = std::less<>, std::size_t ElementsPerWorkItem = 1>
class sycl::_V1::ext::oneapi::experimental::default_sorters::group_key_value_sorter< KeyTy, ValueTy, CompareT, ElementsPerWorkItem >
Definition at line 204 of file group_helpers_sorters.hpp.
Constructor & Destructor Documentation
group_key_value_sorter()
template<typename KeyTy , typename ValueTy , typename CompareT = std::less<>, std::size_t ElementsPerWorkItem = 1> template<std::size_t Extent> sycl::_V1::ext::oneapi::experimental::default_sorters::group_key_value_sorter< KeyTy, ValueTy, CompareT, ElementsPerWorkItem >::group_key_value_sorter (sycl::span< std::byte, Extent > scratch_, CompareT comp_ = {}) inline
Definition at line 210 of file group_helpers_sorters.hpp.
Member Function Documentation
memory_required()
template<typename KeyTy , typename ValueTy , typename CompareT = std::less<>, std::size_t ElementsPerWorkItem = 1> static std::size_t sycl::_V1::ext::oneapi::experimental::default_sorters::group_key_value_sorter< KeyTy, ValueTy, CompareT, ElementsPerWorkItem >::memory_required ([[maybe_unused] ] sycl::memory_scope scope, std::size_t range_size) inline static
Definition at line 303 of file group_helpers_sorters.hpp.
operator()() [1/2]
template<typename KeyTy , typename ValueTy , typename CompareT = std::less<>, std::size_t ElementsPerWorkItem = 1> template<typename Group , typename Properties > void sycl::_V1::ext::oneapi::experimental::default_sorters::group_key_value_sorter< KeyTy, ValueTy, CompareT, ElementsPerWorkItem >::operator() ([[maybe_unused] ] Group g, [[maybe_unused] ] sycl::span< KeyTy, ElementsPerWorkItem > keys, [[maybe_unused] ] sycl::span< ValueTy, ElementsPerWorkItem > values, [[maybe_unused] ] Properties property) inline
Definition at line 246 of file group_helpers_sorters.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::isInputBlocked(), and sycl::_V1::ext::oneapi::experimental::detail::isOutputBlocked().
operator()() [2/2]
template<typename KeyTy , typename ValueTy , typename CompareT = std::less<>, std::size_t ElementsPerWorkItem = 1> template<typename Group > std::tuple<KeyTy, ValueTy> sycl::_V1::ext::oneapi::experimental::default_sorters::group_key_value_sorter< KeyTy, ValueTy, CompareT, ElementsPerWorkItem >::operator() ([[maybe_unused] ] Group g, KeyTy key, ValueTy value) inline
Definition at line 215 of file group_helpers_sorters.hpp.
References sycl::_V1::detail::make_tuple().
The documentation for this class was generated from the following file:
include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp