DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl Class Reference
sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl Class Reference
#include <sycl/ext/oneapi/bindless_images_memory.hpp>
Public Member Functions
image_mem_impl (const image_descriptor &desc, const device &syclDevice, const context &syclContext)
~image_mem_impl ()
raw_handle_type get_handle () const
const image_descriptor & get_descriptor () const
sycl::device get_device () const
sycl::context get_context () const
Detailed Description
Definition at line 33 of file bindless_images_memory.hpp.
Constructor & Destructor Documentation
image_mem_impl()
sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl::image_mem_impl (const image_descriptor & desc, const device & syclDevice, const context & syclContext)
Definition at line 59 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::alloc_image_mem().
~image_mem_impl()
sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl::~image_mem_impl ()
Definition at line 66 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::free_image_mem(), and syclcompat::get_device().
Member Function Documentation
get_context()
sycl::context sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl::get_context () const inline
Definition at line 45 of file bindless_images_memory.hpp.
get_descriptor()
const image_descriptor& sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl::get_descriptor () const inline
Definition at line 43 of file bindless_images_memory.hpp.
get_device()
sycl::device sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl::get_device () const inline
Definition at line 44 of file bindless_images_memory.hpp.
get_handle()
raw_handle_type sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl::get_handle () const inline
Definition at line 42 of file bindless_images_memory.hpp.
The documentation for this class was generated from the following files:
include/sycl/ext/oneapi/bindless_images_memory.hpp
source/detail/bindless_images.cpp