DPC++ Runtime: sycl::_V1::ext::oneapi::filter_selector Class Reference
sycl::_V1::ext::oneapi::filter_selector Class Reference
#include <sycl/ext/oneapi/filter_selector.hpp>
Public Member Functions
filter_selector (const std::string &filter)
int operator() (const device &dev) const override
void reset () const
device select_device () const override
Detailed Description
Definition at line 32 of file filter_selector.hpp.
Constructor & Destructor Documentation
filter_selector()
sycl::_V1::ext::oneapi::filter_selector::filter_selector (const std::string & filter)
Definition at line 305 of file device_selector.cpp.
Member Function Documentation
operator()()
int sycl::_V1::ext::oneapi::filter_selector::operator() (const device & dev) const override
Definition at line 308 of file device_selector.cpp.
reset()
void sycl::_V1::ext::oneapi::filter_selector::reset () const
Definition at line 312 of file device_selector.cpp.
Referenced by select_device().
select_device()
device sycl::_V1::ext::oneapi::filter_selector::select_device () const override
Definition at line 323 of file device_selector.cpp.
References reset(), and sycl::_V1::detail::select_device().
The documentation for this class was generated from the following files:
include/sycl/ext/oneapi/filter_selector.hpp
source/device_selector.cpp