DPC++ Runtime: cl::sycl::program Class Reference
cl::sycl::program Class Reference
DPC++ User API
Provides an abstraction of a SYCL program.
#include <CL/sycl/program.hpp>
Public Member Functions
program ()=delete
program (const context &Context, const property_list &PropList={})
Constructs an instance of SYCL program.
program (const context &Context, vector_class< device > DeviceList, const property_list &PropList={})
Constructs an instance of SYCL program for the provided DeviceList.
program (vector_class< program > ProgramList, const property_list &PropList={})
Constructs an instance of SYCL program by linking together each SYCL program instance in ProgramList.
program (vector_class< program > ProgramList, string_class LinkOptions, const property_list &PropList={})
Constructs an instance of SYCL program by linking together each SYCL program instance in ProgramList.
program (const context &Context, cl_program ClProgram)
Constructs a SYCL program instance from an OpenCL cl_program.
program (const program &rhs)=default
program (program &&rhs)=default
program & operator= (const program &rhs)=default
program & operator= (program &&rhs)=default
bool operator== (const program &rhs) const
bool operator!= (const program &rhs) const
template<typename propertyT >
bool has_property () const
Checks if this program has a property of type propertyT.
template<typename propertyT >
propertyT get_property () const
Gets the specified property of this program.
cl_program get () const
Returns a valid cl_program instance.
bool is_host () const
template<typename KernelT >
void compile_with_kernel_type (string_class CompileOptions="")
Compiles the SYCL kernel function into the encapsulated raw program.
void compile_with_source (string_class KernelSource, string_class CompileOptions="")
Compiles the OpenCL C kernel function defined by source string.
template<typename KernelT >
void build_with_kernel_type (string_class BuildOptions="")
Builds the SYCL kernel function into encapsulated raw program.
void build_with_source (string_class KernelSource, string_class BuildOptions="")
Builds the OpenCL C kernel function defined by source code.
void link (string_class LinkOptions="")
Links encapsulated raw program.
template<typename KernelT >
bool has_kernel () const
Checks if kernel is available for this program.
bool has_kernel (string_class KernelName) const
Checks if kernel is available for this program.
template<typename KernelT >
kernel get_kernel () const
Returns a SYCL kernel for the SYCL kernel function defined by KernelType.
kernel get_kernel (string_class KernelName) const
Returns a SYCL kernel for the SYCL kernel function defined by KernelName.
template<info::program param>
info::param_traits< info::program, param >::return_type get_info () const
Queries this SYCL program for information.
vector_class< vector_class< char > > get_binaries () const
Returns built program binaries.
context get_context () const
vector_class< device > get_devices () const
string_class get_compile_options () const
Returns compile options that were provided when the encapsulated program was explicitly compiled.
string_class get_link_options () const
Returns compile options that were provided to the most recent invocation of link member function.
string_class get_build_options () const
Returns the compile, link, or build options, from whichever of those operations was performed most recently on the encapsulated cl_program.
program_state get_state () const
template<typename ID , typename T >
ONEAPI::experimental::spec_constant< T, ID > set_spec_constant (T Cst)
Set the value of the specialization constant identified by the 'ID' type template parameter and return its instance.
backend get_backend () const noexcept
Returns the backend associated with this program.
template<backend BackendName>
auto get_native () const -> typename interop< BackendName, program >::type
Gets the native handle of the SYCL platform.
Friends
template<class T >
T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Detailed Description
Provides an abstraction of a SYCL program.
See also
kernel
queue
Definition at line 39 of file program.hpp.
Constructor & Destructor Documentation
program() [1/8]
cl::sycl::program::program () delete
program() [2/8]
cl::sycl::program::program (const context & Context, const property_list & PropList = {}) explicit
Constructs an instance of SYCL program.
The program will be created in the program_state::none state and associated with the provided context and the SYCL devices that are associated with the context.
Parameters
Context is an instance of SYCL context.
PropList is an instance of property_list.
Definition at line 20 of file program.cpp.
program() [3/8]
cl::sycl::program::program (const context & Context, vector_class< device > DeviceList, const property_list & PropList = {})
Constructs an instance of SYCL program for the provided DeviceList.
The program will be created in the program_state::none state and associated with the provided context and the SYCL devices in the provided DeviceList.
Parameters
Context is an instance of SYCL context.
DeviceList is a list of SYCL devices.
PropList is an instance of property_list.
Definition at line 24 of file program.cpp.
program() [4/8]
cl::sycl::program::program (vector_class< program > ProgramList, const property_list & PropList = {})
Constructs an instance of SYCL program by linking together each SYCL program instance in ProgramList.
Each SYCL program in ProgramList must be in the program_state::compiled state and must be associated with the same SYCL context. Otherwise an invalid_object_error SYCL exception will be thrown. A feature_not_supported exception will be thrown if any device that the program is to be linked for returns false for the device information query info::device::is_linker_available.
Parameters
ProgramList is a list of SYCL program instances.
PropList is an instance of property_list.
Definition at line 29 of file program.cpp.
program() [5/8]
cl::sycl::program::program (vector_class< program > ProgramList, string_class LinkOptions, const property_list & PropList = {})
Constructs an instance of SYCL program by linking together each SYCL program instance in ProgramList.
Each SYCL program in ProgramList must be in the program_state::compiled state and must be associated with the same SYCL context. Otherwise an invalid_object_error SYCL exception will be thrown. A feature_not_supported exception will be thrown if any device that the program is to be linked for returns false for the device information query info::device::is_linker_available.
Parameters
ProgramList is a list of SYCL program instances.
LinkOptions is a string containing valid OpenCL link options.
PropList is an instance of property_list.
Definition at line 33 of file program.cpp.
References cl::sycl::detail::getSyclObjImpl().
program() [6/8]
cl::sycl::program::program (const context & Context, cl_program ClProgram)
Constructs a SYCL program instance from an OpenCL cl_program.
The state of the constructed SYCL program can be either program_state::compiled or program_state::linked, depending on the state of the ClProgram. Otherwise an invalid_object_error SYCL exception is thrown.
The instance of OpenCL cl_program will be retained on construction.
Parameters
Context is an instance of SYCL Context.
ClProgram is an instance of OpenCL cl_program.
Definition at line 42 of file program.cpp.
program() [7/8]
cl::sycl::program::program (const program & rhs) default
program() [8/8]
cl::sycl::program::program (program && rhs) default
Member Function Documentation
build_with_kernel_type()
template<typename KernelT > void cl::sycl::program::build_with_kernel_type (string_class BuildOptions = "") inline
Builds the SYCL kernel function into encapsulated raw program.
The SYCL kernel function is defined by the type KernelT. This member function sets the state of this SYCL program to program_state::linked. If the program was not in the program_state::none state, an invalid_object_error SYCL exception is thrown. If the compilation fails, a compile_program_error SYCL exception is thrown. If any device that the program is being built for returns false for the device information queries info::device::is_compiler_available or info::device::is_linker_available, a feature_not_supported SYCL exception is thrown.
Parameters
BuildOptions is a string containing OpenCL compile options.
Definition at line 196 of file program.hpp.
build_with_source()
void cl::sycl::program::build_with_source (string_class KernelSource, string_class BuildOptions = "")
Builds the OpenCL C kernel function defined by source code.
This member function sets the state of this SYCL program to program_state::linked. If this program was not in program_state::none, an invalid_object_error SYCL exception is thrown. If the compilation fails, a compile_program_error SYCL exception is thrown. If any device that the program is being built for returns false for the device information queries info::device::is_compiler_available or info::device::is_linker_available, a feature_not_supported SYCL exception is thrown.
Parameters
KernelSource is a string containing OpenCL C kernel source code.
BuildOptions is a string containing OpenCL build options.
Definition at line 66 of file program.cpp.
compile_with_kernel_type()
template<typename KernelT > void cl::sycl::program::compile_with_kernel_type (string_class CompileOptions = "") inline
Compiles the SYCL kernel function into the encapsulated raw program.
The kernel function is defined by the type KernelT. This member function sets the state of this SYCL program to program_state::compiled. If this program was not in the program_state::none state, an invalid_object_error exception is thrown. If the compilation fails, a compile_program_error SYCL exception is thrown. If any device that the program is being compiled for returns false for the device information query info::device::is_compiler_available, a feature_not_supported exception is thrown.
Parameters
CompileOptions is a string of valid OpenCL compile options.
Definition at line 159 of file program.hpp.
compile_with_source()
void cl::sycl::program::compile_with_source (string_class KernelSource, string_class CompileOptions = "")
Compiles the OpenCL C kernel function defined by source string.
This member function sets the state of this SYCL program to program_state::compiled. If the program was not in the program_state::none state, an invalid_object_error SYCL exception is thrown. If the compilation fails, a compile_program_error SYCL exception is thrown. If any device that the program is being compiled for returns false for the device information query info::device::is_compiler_available, a feature_not_supported SYCL exception is thrown.
Parameters
KernelSource is a string containing OpenCL C kernel source code.
CompileOptions is a string containing OpenCL compile options.
Definition at line 61 of file program.cpp.
get()
cl_program cl::sycl::program::get () const
Returns a valid cl_program instance.
The instance of cl_program will be retained before returning. If the program is created for a SYCL host device, an invalid_object_error exception is thrown.
Returns
a valid OpenCL cl_program instance.
Definition at line 57 of file program.cpp.
Referenced by cl::sycl::ONEAPI::experimental::spec_constant< T, ID >::operator T().
get_backend()
backend cl::sycl::program::get_backend () const noexcept
Returns the backend associated with this program.
Returns
the backend associated with this program.
Definition at line 51 of file program.cpp.
References cl::sycl::detail::getImplBackend().
get_binaries()
vector_class< vector_class< char > > cl::sycl::program::get_binaries () const
Returns built program binaries.
If this program is not in the program_state::compiled or program_state::linked states, an invalid_object_error SYCL exception is thrown.
Returns
a vector of vectors representing the compiled binaries for each associated SYCL device.
Definition at line 134 of file program.cpp.
get_build_options()
string_class cl::sycl::program::get_build_options () const
Returns the compile, link, or build options, from whichever of those operations was performed most recently on the encapsulated cl_program.
If no compile, link, or build operations have been performed on this program, or if the program includes the host device in its device list, then an empty string is returned.
Returns
a string of valid OpenCL build options.
Definition at line 152 of file program.cpp.
get_compile_options()
string_class cl::sycl::program::get_compile_options () const
Returns compile options that were provided when the encapsulated program was explicitly compiled.
If the program was built instead of explicitly compiled, if the program has not yet been compiled, or if the program has been compiled for only the host device, then an empty string is return, unless the underlying cl_program was explicitly compiled, in which case the compile options used in the explicit compile are returned.
Returns
a string of valid OpenCL compile options.
Definition at line 144 of file program.cpp.
get_context()
context cl::sycl::program::get_context () const
Returns
the SYCL context that this program was constructed with.
Definition at line 138 of file program.cpp.
get_devices()
vector_class< device > cl::sycl::program::get_devices () const
Returns
a vector of devices that are associated with this program.
Definition at line 140 of file program.cpp.
get_info()
template<info::program param> info::param_traits< info::program, param >::return_type cl::sycl::program::get_info
Queries this SYCL program for information.
The return type depends on the information being queried.
Definition at line 105 of file program.cpp.
get_kernel() [1/2]
template<typename KernelT > kernel cl::sycl::program::get_kernel () const inline
Returns a SYCL kernel for the SYCL kernel function defined by KernelType.
If program is in the program_state::none state or if the SYCL kernel function is not available, an invalid_object_error exception is thrown.
Returns
a valid instance of SYCL kernel.
Definition at line 260 of file program.hpp.
Referenced by get_kernel().
get_kernel() [2/2]
kernel cl::sycl::program::get_kernel (string_class KernelName) const
Returns a SYCL kernel for the SYCL kernel function defined by KernelName.
An invalid_object_error SYCL exception is thrown if this program is a host program, if program is in the program_state::none state or if the SYCL kernel is not available.
Parameters
KernelName is a string containing SYCL kernel name.
Definition at line 94 of file program.cpp.
References get_kernel().
get_link_options()
string_class cl::sycl::program::get_link_options () const
Returns compile options that were provided to the most recent invocation of link member function.
If the program has not been explicitly linked using the aforementioned function, constructed with an explicitly linking constructor, or if the program has been linked for only the host device, then an empty string is returned. If the program was constructed from cl_program, then an empty string is returned unless the cl_program was explicitly linked, in which case the link options used in that explicit link are returned. If the program object was constructed using a constructor form that links a vector of programs, then the link options passed to this constructor are returned.
Returns
a string of valid OpenCL compile options.
Definition at line 148 of file program.cpp.
get_native()
template<backend BackendName> auto cl::sycl::program::get_native () const -> typename interop<BackendName, program>::type inline
Gets the native handle of the SYCL platform.
Returns
a native handle, the type of which defined by the backend.
Definition at line 368 of file program.hpp.
get_property()
template<typename propertyT > propertyT cl::sycl::program::get_property () const
Gets the specified property of this program.
Throws invalid_object_error if this program does not have a property of type propertyT.
Returns
a copy of the property of type propertyT.
get_state()
program_state cl::sycl::program::get_state () const
Returns
the current state of this SYCL program.
Definition at line 156 of file program.cpp.
has_kernel() [1/2]
template<typename KernelT > bool cl::sycl::program::has_kernel () const inline
Checks if kernel is available for this program.
The SYCL kernel is defined by type KernelT. If the program state is program_state::none an invalid_object_error SYCL exception is thrown.
Returns
true if the SYCL kernel is available.
Definition at line 238 of file program.hpp.
Referenced by has_kernel().
has_kernel() [2/2]
bool cl::sycl::program::has_kernel (string_class KernelName) const
Checks if kernel is available for this program.
The SYCL kernel is defined by its name. If the program is in the program_stateP::none state, an invalid_object_error SYCL exception is thrown.
Parameters
KernelName is a string containing kernel name.
Returns
true if the SYCL kernel is available and the program is not a SYCL host program.
Definition at line 85 of file program.cpp.
References has_kernel().
has_property()
template<typename propertyT > bool cl::sycl::program::has_property () const
Checks if this program has a property of type propertyT.
Returns
true if this context has a property of type propertyT.
is_host()
bool cl::sycl::program::is_host () const
Returns
true if this SYCL program is a host program.
Definition at line 59 of file program.cpp.
link()
void cl::sycl::program::link (string_class LinkOptions = "")
Links encapsulated raw program.
This member function sets the state of this SYCL program to program_state::linked. If the program was not in the program_state::compiled state, an invalid_object_error SYCL exception is thrown. If linking fails, a compile_program_error is thrown. If any device that the program is to be linked for returns false for the device information query info::device::is_linker_available, a feature_not_supported exception is thrown.
Parameters
LinkOptions is a string containing OpenCL link options.
Definition at line 83 of file program.cpp.
operator!=()
bool cl::sycl::program::operator!= (const program & rhs) const inline
Definition at line 119 of file program.hpp.
operator=() [1/2]
program& cl::sycl::program::operator= (const program & rhs) default
operator=() [2/2]
program& cl::sycl::program::operator= (program && rhs) default
operator==()
bool cl::sycl::program::operator== (const program & rhs) const inline
Definition at line 117 of file program.hpp.
set_spec_constant()
template<typename ID , typename T > ONEAPI::experimental::spec_constant<T, ID> cl::sycl::program::set_spec_constant (T Cst) inline
Set the value of the specialization constant identified by the 'ID' type template parameter and return its instance.
Parameters
cst the specialization constant value
Returns
a specialization constant instance corresponding to given type ID passed as a template parameter
Definition at line 344 of file program.hpp.
Friends And Related Function Documentation
detail::createSyclObjFromImpl
template<class T > T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
The documentation for this class was generated from the following files:
include/CL/sycl/program.hpp
source/program.cpp