DPC++ Runtime: cl::sycl::detail::DynRTDeviceBinaryImage Class Reference
cl::sycl::detail::DynRTDeviceBinaryImage Class Reference
#include <CL/sycl/detail/device_binary_image.hpp>
Public Member Functions
DynRTDeviceBinaryImage (std::unique_ptr< char[]> &&DataPtr, size_t DataSize, OSModuleHandle M)
~DynRTDeviceBinaryImage () override
void print () const override
Public Member Functions inherited from cl::sycl::detail::RTDeviceBinaryImage
RTDeviceBinaryImage (OSModuleHandle ModuleHandle)
RTDeviceBinaryImage (pi_device_binary Bin, OSModuleHandle ModuleHandle)
OSModuleHandle getOSModuleHandle () const
~RTDeviceBinaryImage () override
bool supportsSpecConstants () const
const pi_device_binary_struct & getRawData () const
Public Member Functions inherited from cl::sycl::detail::pi::DeviceBinaryImage
DeviceBinaryImage (pi_device_binary Bin)
DeviceBinaryImage ()
virtual void dump (std::ostream &Out) const
size_t getSize () const
const char * getCompileOptions () const
const char * getLinkOptions () const
pi::PiDeviceBinaryType getFormat () const
Returns the format of the binary image.
const PropertyRange & getSpecConstants () const
Gets the iterator range over specialization constants in this this binary image.
const PropertyRange & getDeviceLibReqMask () const
const PropertyRange & getKernelParamOptInfo () const
virtual ~DeviceBinaryImage ()
Protected Attributes
std::unique_ptr< char[]> Data
Protected Attributes inherited from cl::sycl::detail::RTDeviceBinaryImage
OSModuleHandle ModuleHandle
Protected Attributes inherited from cl::sycl::detail::pi::DeviceBinaryImage
pi_device_binary Bin
pi::PiDeviceBinaryType Format = PI_DEVICE_BINARY_TYPE_NONE
DeviceBinaryImage::PropertyRange SpecConstIDMap
DeviceBinaryImage::PropertyRange DeviceLibReqMask
DeviceBinaryImage::PropertyRange KernelParamOptInfo
Additional Inherited Members
Protected Member Functions inherited from cl::sycl::detail::pi::DeviceBinaryImage
void init (pi_device_binary Bin)
pi_device_binary get () const
Detailed Description
Definition at line 47 of file device_binary_image.hpp.
Constructor & Destructor Documentation
DynRTDeviceBinaryImage()
cl::sycl::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage (std::unique_ptr< char[]> && DataPtr, size_t DataSize, OSModuleHandle M)
Definition at line 19 of file device_binary_image.cpp.
References __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64, __SYCL_PI_DEVICE_BINARY_TARGET_UNKNOWN, cl::sycl::detail::pi::DeviceBinaryImage::Bin, pi_device_binary_struct::BinaryEnd, pi_device_binary_struct::BinaryStart, pi_device_binary_struct::CompileOptions, Data, pi_device_binary_struct::DeviceTargetSpec, pi_device_binary_struct::EntriesBegin, pi_device_binary_struct::EntriesEnd, pi_device_binary_struct::Format, cl::sycl::detail::pi::getBinaryImageFormat(), cl::sycl::detail::pi::DeviceBinaryImage::init(), pi_device_binary_struct::Kind, pi_device_binary_struct::LinkOptions, pi_device_binary_struct::ManifestEnd, pi_device_binary_struct::ManifestStart, PI_DEVICE_BINARY_OFFLOAD_KIND_SYCL, PI_DEVICE_BINARY_TYPE_SPIRV, PI_DEVICE_BINARY_VERSION, and pi_device_binary_struct::Version.
~DynRTDeviceBinaryImage()
cl::sycl::detail::DynRTDeviceBinaryImage::~DynRTDeviceBinaryImage () override
Definition at line 45 of file device_binary_image.cpp.
References cl::sycl::detail::pi::DeviceBinaryImage::Bin.
Member Function Documentation
print()
void cl::sycl::detail::DynRTDeviceBinaryImage::print () const inline override virtual
Reimplemented from cl::sycl::detail::RTDeviceBinaryImage.
Definition at line 53 of file device_binary_image.hpp.
References cl::sycl::detail::pi::print().
Member Data Documentation
Data
std::unique_ptr<char[]> cl::sycl::detail::DynRTDeviceBinaryImage::Data protected
Definition at line 59 of file device_binary_image.hpp.
Referenced by DynRTDeviceBinaryImage().
The documentation for this class was generated from the following files:
include/CL/sycl/detail/device_binary_image.hpp
source/detail/device_binary_image.cpp