DPC++ Runtime: sycl::_V1::detail::stream_impl Class Reference
sycl::_V1::detail::stream_impl Class Reference
#include <detail/stream_impl.hpp>
Public Member Functions
stream_impl (size_t BufferSize, size_t MaxStatementSize, handler &CGH)
stream_impl (size_t BufferSize, size_t MaxStatementSize, const property_list &PropList)
GlobalBufAccessorT accessGlobalBuf (handler &CGH)
GlobalBufAccessorT accessGlobalFlushBuf (handler &CGH)
GlobalOffsetAccessorT accessGlobalOffset (handler &CGH)
void initStreamHost (QueueImplPtr Queue)
void flush (const EventImplPtr &LeadEvent)
void flush ()
size_t size () const noexcept
size_t get_work_item_buffer_size () const
size_t get_size () const
size_t get_max_statement_size () const
template<typename propertyT >
bool has_property () const noexcept
template<typename propertyT >
propertyT get_property () const
Detailed Description
Definition at line 25 of file stream_impl.hpp.
Constructor & Destructor Documentation
stream_impl() [1/2]
sycl::_V1::detail::stream_impl::stream_impl (size_t BufferSize, size_t MaxStatementSize, handler & CGH)
Definition at line 21 of file stream_impl.cpp.
stream_impl() [2/2]
sycl::_V1::detail::stream_impl::stream_impl (size_t BufferSize, size_t MaxStatementSize, const property_list & PropList)
Definition at line 27 of file stream_impl.cpp.
References sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::set_write_back(), and sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::size().
Member Function Documentation
accessGlobalBuf()
GlobalBufAccessorT sycl::_V1::detail::stream_impl::accessGlobalBuf (handler & CGH)
Definition at line 49 of file stream_impl.cpp.
References sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::get_access().
accessGlobalFlushBuf()
GlobalBufAccessorT sycl::_V1::detail::stream_impl::accessGlobalFlushBuf (handler & CGH)
Definition at line 55 of file stream_impl.cpp.
References sycl::_V1::detail::FLUSH_BUF_OFFSET_SIZE, and sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::get_access().
accessGlobalOffset()
GlobalOffsetAccessorT sycl::_V1::detail::stream_impl::accessGlobalOffset (handler & CGH)
Definition at line 62 of file stream_impl.cpp.
flush() [1/2]
void sycl::_V1::detail::stream_impl::flush ()
Definition at line 141 of file stream_impl.cpp.
flush() [2/2]
void sycl::_V1::detail::stream_impl::flush (const EventImplPtr & LeadEvent)
Definition at line 96 of file stream_impl.cpp.
References sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::get_access(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::ext::oneapi::experimental::printf(), and sycl::_V1::access::read_write.
get_max_statement_size()
size_t sycl::_V1::detail::stream_impl::get_max_statement_size () const
Definition at line 77 of file stream_impl.cpp.
get_property()
template<typename propertyT > propertyT sycl::_V1::detail::stream_impl::get_property () const inline
Definition at line 70 of file stream_impl.hpp.
get_size()
size_t sycl::_V1::detail::stream_impl::get_size () const
Definition at line 75 of file stream_impl.cpp.
get_work_item_buffer_size()
size_t sycl::_V1::detail::stream_impl::get_work_item_buffer_size () const
Definition at line 71 of file stream_impl.cpp.
has_property()
template<typename propertyT > bool sycl::_V1::detail::stream_impl::has_property () const inline noexcept
Definition at line 66 of file stream_impl.hpp.
initStreamHost()
void sycl::_V1::detail::stream_impl::initStreamHost (QueueImplPtr Queue)
Definition at line 79 of file stream_impl.cpp.
References sycl::_V1::access::discard_write, sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::get_access(), and sycl::_V1::detail::getSyclObjImpl().
size()
size_t sycl::_V1::detail::stream_impl::size () const noexcept
Definition at line 69 of file stream_impl.cpp.
The documentation for this class was generated from the following files:
source/detail/stream_impl.hpp
source/detail/stream_impl.cpp