DPC++ Runtime: cl::sycl::detail::ProgramManager Class Reference
cl::sycl::detail::ProgramManager Class Reference
#include <detail/program_manager/program_manager.hpp>
Public Types
using KernelArgMask = std::vector< bool >
Public Member Functions
RTDeviceBinaryImage & getDeviceImage (OSModuleHandle M, const std::string &KernelName, const context &Context, const device &Device, bool JITCompilationIsRequired=false)
RT::PiProgram createPIProgram (const RTDeviceBinaryImage &Img, const context &Context, const device &Device)
std::pair< RT::PiProgram, bool > getOrCreatePIProgram (const RTDeviceBinaryImage &Img, const context &Context, const device &Device, const std::string &CompileAndLinkOptions, SerializedObj SpecConsts)
Creates a PI program using either a cached device code binary if present in the persistent cache or from the supplied device image otherwise.
RT::PiProgram getBuiltPIProgram (OSModuleHandle M, const ContextImplPtr &ContextImpl, const DeviceImplPtr &DeviceImpl, const std::string &KernelName, const program_impl *Prg=nullptr, bool JITCompilationIsRequired=false)
Builds or retrieves from cache a program defining the kernel with given name.
RT::PiProgram getBuiltPIProgram (OSModuleHandle M, const context &Context, const device &Device, const std::string &KernelName, const property_list &PropList, bool JITCompilationIsRequired=false)
std::tuple< RT::PiKernel, std::mutex *, RT::PiProgram > getOrCreateKernel (OSModuleHandle M, const ContextImplPtr &ContextImpl, const DeviceImplPtr &DeviceImpl, const std::string &KernelName, const program_impl *Prg)
RT::PiProgram getPiProgramFromPiKernel (RT::PiKernel Kernel, const ContextImplPtr Context)
void addImages (pi_device_binaries DeviceImages)
void debugPrintBinaryImages () const
void flushSpecConstants (const program_impl &Prg, pi::PiProgram NativePrg=nullptr, const RTDeviceBinaryImage *Img=nullptr)
Resolves given program to a device binary image and requests the program to flush constants the image depends on.
uint32_t getDeviceLibReqMask (const RTDeviceBinaryImage &Img)
KernelArgMask getEliminatedKernelArgMask (OSModuleHandle M, pi::PiProgram NativePrg, const std::string &KernelName)
Returns the mask for eliminated kernel arguments for the requested kernel within the native program.
kernel_id getSYCLKernelID (const std::string &KernelName)
std::vector< kernel_id > getAllSYCLKernelIDs ()
kernel_id getBuiltInKernelID (const std::string &KernelName)
void addOrInitDeviceGlobalEntry (const void *DeviceGlobalPtr, const char *UniqueId)
std::vector< device_image_plain > getSYCLDeviceImagesWithCompatibleState (const context &Ctx, const std::vector< device > &Devs, bundle_state TargetState, const std::vector< kernel_id > &KernelIDs={})
void bringSYCLDeviceImagesToState (std::vector< device_image_plain > &DeviceImages, bundle_state TargetState)
std::vector< device_image_plain > getSYCLDeviceImages (const context &Ctx, const std::vector< device > &Devs, bundle_state State)
std::vector< device_image_plain > getSYCLDeviceImages (const context &Ctx, const std::vector< device > &Devs, const DevImgSelectorImpl &Selector, bundle_state TargetState)
std::vector< device_image_plain > getSYCLDeviceImages (const context &Ctx, const std::vector< device > &Devs, const std::vector< kernel_id > &KernelIDs, bundle_state TargetState)
device_image_plain compile (const device_image_plain &DeviceImage, const std::vector< device > &Devs, const property_list &PropList)
std::vector< device_image_plain > link (const std::vector< device_image_plain > &DeviceImages, const std::vector< device > &Devs, const property_list &PropList)
device_image_plain build (const device_image_plain &DeviceImage, const std::vector< device > &Devs, const property_list &PropList)
std::pair< RT::PiKernel, std::mutex * > getOrCreateKernel (const context &Context, const std::string &KernelName, const property_list &PropList, RT::PiProgram Program)
ProgramManager ()
~ProgramManager ()=default
bool kernelUsesAssert (OSModuleHandle M, const std::string &KernelName) const
Static Public Member Functions
static ProgramManager & getInstance ()
static std::string getProgramBuildLog (const RT::PiProgram &Program, const ContextImplPtr Context)
Detailed Description
Definition at line 71 of file program_manager.hpp.
Member Typedef Documentation
KernelArgMask
using cl::sycl::detail::ProgramManager::KernelArgMask = std::vector<bool>
Definition at line 74 of file program_manager.hpp.
Constructor & Destructor Documentation
ProgramManager()
cl::sycl::detail::ProgramManager::ProgramManager ()
Definition at line 823 of file program_manager.cpp.
References cl::sycl::detail::DbgProgMgr, cl::sycl::detail::getFormatStr(), PI_INVALID_VALUE, cl::sycl::detail::SpvFileKSId, and cl::sycl::detail::UseSpvEnv().
~ProgramManager()
cl::sycl::detail::ProgramManager::~ProgramManager () default
Member Function Documentation
addImages()
void cl::sycl::detail::ProgramManager::addImages (pi_device_binaries DeviceImages)
Definition at line 1095 of file program_manager.cpp.
References cl::sycl::detail::pi::DeviceBinaryProperty::asByteArray(), cl::sycl::detail::createKernelArgMask(), pi_device_binaries_struct::DeviceBinaries, pi_device_binary_struct::EntriesBegin, pi_device_binary_struct::EntriesEnd, cl::sycl::detail::pi::DeviceBinaryImage::get(), cl::sycl::detail::pi::DeviceBinaryImage::getDeviceGlobals(), cl::sycl::detail::pi::DeviceBinaryImage::getExportedSymbols(), cl::sycl::detail::pi::DeviceBinaryImage::getKernelParamOptInfo(), cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::isAvailable(), _pi_offload_entry_struct::name, pi_device_binaries_struct::NumDeviceBinaries, and cl::sycl::detail::pi::ByteArray::size().
Referenced by __sycl_register_lib().
addOrInitDeviceGlobalEntry()
void cl::sycl::detail::ProgramManager::addOrInitDeviceGlobalEntry (const void * DeviceGlobalPtr, const char * UniqueId)
Definition at line 1485 of file program_manager.cpp.
bringSYCLDeviceImagesToState()
void cl::sycl::detail::ProgramManager::bringSYCLDeviceImagesToState (std::vector< device_image_plain > & DeviceImages, bundle_state TargetState)
Definition at line 1571 of file program_manager.cpp.
References cl::sycl::build(), cl::sycl::compile(), cl::sycl::detail::getSyclObjImpl(), and cl::sycl::link().
build()
device_image_plain cl::sycl::detail::ProgramManager::build (const device_image_plain & DeviceImage, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 1812 of file program_manager.cpp.
References cl::sycl::detail::KernelProgramCache::acquireCachedPrograms(), cl::sycl::detail::applyOptionsFromEnvironment(), cl::sycl::detail::applyOptionsFromImage(), cl::sycl::detail::device_image_impl::SpecConstDescT::BlobOffset, cl::sycl::build(), cl::sycl::detail::plugin::call(), cl::sycl::detail::emitBuiltProgramInfo(), cl::sycl::detail::enableITTAnnotationsIfNeeded(), cl::sycl::detail::plugin::getPiPlugin(), cl::sycl::detail::getRawSyclObjImpl(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::device_image_impl::SpecConstDescT::ID, cl::sycl::detail::device_image_impl::SpecConstDescT::IsSet, PI_DEVICE_BINARY_TYPE_SPIRV, PI_INVALID_OPERATION, piextProgramSetSpecializationConstant(), _pi_plugin::PiFunctionTable, piProgramRetain(), and cl::sycl::detail::device_image_impl::SpecConstDescT::Size.
compile()
device_image_plain cl::sycl::detail::ProgramManager::compile (const device_image_plain & DeviceImage, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 1678 of file program_manager.cpp.
References cl::sycl::detail::appendCompileOptionsFromImage(), cl::sycl::detail::applyCompileOptionsFromEnvironment(), cl::sycl::build(), cl::sycl::detail::plugin::call_nocheck(), cl::sycl::detail::enableITTAnnotationsIfNeeded(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::make_error_code(), PI_DEVICE_BINARY_TYPE_SPIRV, PI_INVALID_OPERATION, PI_SUCCESS, and piProgramCompile().
createPIProgram()
RT::PiProgram cl::sycl::detail::ProgramManager::createPIProgram (const RTDeviceBinaryImage & Img, const context & Context, const device & Device)
Definition at line 306 of file program_manager.cpp.
References cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::begin(), pi_device_binary_struct::BinaryEnd, pi_device_binary_struct::BinaryStart, cl::sycl::detail::createBinaryProgram(), cl::sycl::detail::createSpirvProgram(), cl::sycl::detail::DbgProgMgr, cl::sycl::feature_not_supported, cl::sycl::detail::pi::getBinaryImageFormat(), cl::sycl::detail::pi::DeviceBinaryImage::getFormat(), cl::sycl::detail::getFormatStr(), cl::sycl::detail::pi::DeviceBinaryImage::getProgramMetadata(), cl::sycl::detail::RTDeviceBinaryImage::getRawData(), cl::sycl::detail::getRawSyclObjImpl(), cl::sycl::detail::pi::DeviceBinaryImage::getSize(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::isDeviceBinaryTypeSupported(), PI_DEVICE_BINARY_TYPE_NONE, PI_DEVICE_BINARY_TYPE_SPIRV, PI_INVALID_OPERATION, and PI_INVALID_VALUE.
debugPrintBinaryImages()
void cl::sycl::detail::ProgramManager::debugPrintBinaryImages () const
Definition at line 1259 of file program_manager.cpp.
References cl::sycl::detail::pi::DeviceBinaryImage::get().
flushSpecConstants()
void cl::sycl::detail::ProgramManager::flushSpecConstants (const program_impl & Prg, pi::PiProgram NativePrg = nullptr, const RTDeviceBinaryImage * Img = nullptr)
Resolves given program to a device binary image and requests the program to flush constants the image depends on.
Parameters
Prg the program object to get spec constant settings from. Passing program_impl by raw reference is OK, since it is not captured anywhere once the function returns.
NativePrg the native program, target for spec constant setting; if not null then overrides the native program in Prg
Img A source of the information about which constants need setting and symboling->integer spec constant ID mapping. If not null, overrides native program->binary image binding maintained by the program manager.
Definition at line 1325 of file program_manager.cpp.
References cl::sycl::detail::DbgProgMgr, cl::sycl::detail::program_impl::flush_spec_constants(), cl::sycl::detail::program_impl::get(), cl::sycl::detail::program_impl::getHandleRef(), cl::sycl::detail::RTDeviceBinaryImage::getRawData(), cl::sycl::detail::program_impl::hasSetSpecConstants(), PI_INVALID_OPERATION, and cl::sycl::detail::RTDeviceBinaryImage::supportsSpecConstants().
getAllSYCLKernelIDs()
std::vector< kernel_id > cl::sycl::detail::ProgramManager::getAllSYCLKernelIDs ()
Definition at line 1461 of file program_manager.cpp.
getBuiltInKernelID()
kernel_id cl::sycl::detail::ProgramManager::getBuiltInKernelID (const std::string & KernelName)
Definition at line 1472 of file program_manager.cpp.
getBuiltPIProgram() [1/2]
RT::PiProgram cl::sycl::detail::ProgramManager::getBuiltPIProgram (OSModuleHandle M, const context & Context, const device & Device, const std::string & KernelName, const property_list & PropList, bool JITCompilationIsRequired = false)
getBuiltPIProgram() [2/2]
RT::PiProgram cl::sycl::detail::ProgramManager::getBuiltPIProgram (OSModuleHandle M, const ContextImplPtr & ContextImpl, const DeviceImplPtr & DeviceImpl, const std::string & KernelName, const program_impl * Prg = nullptr, bool JITCompilationIsRequired = false)
Builds or retrieves from cache a program defining the kernel with given name.
Parameters
M identifies the OS module the kernel comes from (multiple OS modules may have kernels with the same name)
Context the context to build the program with
Device the device for which the program is built
KernelName the kernel's name
Prg provides build context information, such as current specialization constants settings; can be nullptr. Passing as a raw pointer is OK, since it is not captured anywhere once the function returns.
JITCompilationIsRequired If JITCompilationIsRequired is true add a check that kernel is compiled, otherwise don't add the check.
Definition at line 481 of file program_manager.cpp.
References cl::sycl::detail::KernelProgramCache::acquireCachedPrograms(), cl::sycl::detail::applyOptionsFromEnvironment(), cl::sycl::detail::applyOptionsFromImage(), cl::sycl::build(), cl::sycl::detail::emitBuiltProgramInfo(), cl::sycl::detail::enableITTAnnotationsIfNeeded(), cl::sycl::detail::pi::DeviceBinaryImage::get(), cl::sycl::detail::program_impl::get_build_options(), cl::sycl::detail::pi::DeviceBinaryImage::getFormat(), cl::sycl::detail::plugin::getPiPlugin(), cl::sycl::detail::getRawSyclObjImpl(), cl::sycl::detail::getSyclObjImpl(), PI_DEVICE_BINARY_TYPE_SPIRV, PI_DEVICE_INFO_BUILD_ON_SUBDEVICE, PI_TRUE, piDeviceGetInfo(), _pi_plugin::PiFunctionTable, cl::sycl::detail::program_impl::stableSerializeSpecConstRegistry(), and cl::sycl::detail::RTDeviceBinaryImage::supportsSpecConstants().
Referenced by cl::sycl::detail::program_impl::build_with_kernel_name().
getDeviceImage()
RTDeviceBinaryImage & cl::sycl::detail::ProgramManager::getDeviceImage (OSModuleHandle M, const std::string & KernelName, const context & Context, const device & Device, bool JITCompilationIsRequired = false)
Definition at line 107 of file program_manager.cpp.
References cl::sycl::detail::DbgProgMgr, and cl::sycl::detail::getRawSyclObjImpl().
getDeviceLibReqMask()
uint32_t cl::sycl::detail::ProgramManager::getDeviceLibReqMask (const RTDeviceBinaryImage & Img)
Definition at line 1367 of file program_manager.cpp.
References cl::sycl::detail::pi::DeviceBinaryProperty::asUint32(), cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::begin(), cl::sycl::detail::pi::DeviceBinaryImage::getDeviceLibReqMask(), and cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::isAvailable().
getEliminatedKernelArgMask()
ProgramManager::KernelArgMask cl::sycl::detail::ProgramManager::getEliminatedKernelArgMask (OSModuleHandle M, pi::PiProgram NativePrg, const std::string & KernelName)
Returns the mask for eliminated kernel arguments for the requested kernel within the native program.
Parameters
M identifies the OS module the kernel comes from (multiple OS modules may have kernels with the same name).
NativePrg the PI program associated with the kernel.
KernelName the name of the kernel.
Definition at line 1378 of file program_manager.cpp.
Referenced by cl::sycl::detail::enqueueImpKernel().
getInstance()
ProgramManager & cl::sycl::detail::ProgramManager::getInstance () static
Definition at line 63 of file program_manager.cpp.
Referenced by __sycl_register_lib(), cl::sycl::detail::program_impl::build_with_kernel_name(), and cl::sycl::detail::enqueueImpKernel().
getOrCreateKernel() [1/2]
std::pair< RT::PiKernel, std::mutex * > cl::sycl::detail::ProgramManager::getOrCreateKernel (const context & Context, const std::string & KernelName, const property_list & PropList, RT::PiProgram Program)
Definition at line 1972 of file program_manager.cpp.
References cl::sycl::detail::KernelProgramCache::acquireKernelsPerProgramCache(), cl::sycl::detail::plugin::call(), cl::sycl::detail::getSyclObjImpl(), PI_TRUE, PI_USM_INDIRECT_ACCESS, piKernelCreate(), and piKernelSetExecInfo().
getOrCreateKernel() [2/2]
std::tuple< RT::PiKernel, std::mutex *, RT::PiProgram > cl::sycl::detail::ProgramManager::getOrCreateKernel (OSModuleHandle M, const ContextImplPtr & ContextImpl, const DeviceImplPtr & DeviceImpl, const std::string & KernelName, const program_impl * Prg)
Definition at line 600 of file program_manager.cpp.
References cl::sycl::detail::KernelProgramCache::acquireKernelsPerProgramCache(), cl::sycl::detail::applyOptionsFromEnvironment(), cl::sycl::detail::plugin::call(), cl::sycl::detail::DbgProgMgr, cl::sycl::detail::program_impl::get_build_options(), cl::sycl::detail::make_tuple(), PI_TRUE, PI_USM_INDIRECT_ACCESS, piKernelCreate(), piKernelSetExecInfo(), cl::sycl::detail::KernelProgramCache::saveKernel(), cl::sycl::detail::program_impl::stableSerializeSpecConstRegistry(), and cl::sycl::detail::KernelProgramCache::tryToGetKernelFast().
Referenced by cl::sycl::detail::enqueueImpKernel().
getOrCreatePIProgram()
std::pair< RT::PiProgram, bool > cl::sycl::detail::ProgramManager::getOrCreatePIProgram (const RTDeviceBinaryImage & Img, const context & Context, const device & Device, const std::string & CompileAndLinkOptions, SerializedObj SpecConsts)
Creates a PI program using either a cached device code binary if present in the persistent cache or from the supplied device image otherwise.
Parameters
Img The device image to find a cached device code binary for or create the PI program with.
Context The context to find or create the PI program with.
Device The device to find or create the PI program for.
CompileAndLinkOptions The compile and linking options to be used for building the PI program. These options must appear in the mentioned order. This parameter is used as a partial key in the cache and has no effect if no cached device code binary is found in the persistent cache.
SpecConsts Specialization constants associated with the device image. This parameter is used as a partial key in the cache and has no effect if no cached device code binary is found in the persistent cache.
Returns
A pair consisting of the PI program created with the corresponding device code binary and a boolean that is true if the device code binary was found in the persistent cache and false otherwise.
Definition at line 446 of file program_manager.cpp.
References cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::begin(), cl::sycl::detail::createBinaryProgram(), cl::sycl::detail::pi::DeviceBinaryImage::getProgramMetadata(), and cl::sycl::detail::getSyclObjImpl().
getPiProgramFromPiKernel()
RT::PiProgram cl::sycl::detail::ProgramManager::getPiProgramFromPiKernel (RT::PiKernel Kernel, const ContextImplPtr Context)
Definition at line 668 of file program_manager.cpp.
References cl::sycl::detail::plugin::call(), PI_KERNEL_INFO_PROGRAM, and piKernelGetInfo().
getProgramBuildLog()
std::string cl::sycl::detail::ProgramManager::getProgramBuildLog (const RT::PiProgram & Program, const ContextImplPtr Context) static
Definition at line 677 of file program_manager.cpp.
References cl::sycl::detail::plugin::call(), PI_DEVICE_INFO_NAME, PI_PROGRAM_INFO_DEVICES, piDeviceGetInfo(), piProgramGetBuildInfo(), and piProgramGetInfo().
getSYCLDeviceImages() [1/3]
std::vector< device_image_plain > cl::sycl::detail::ProgramManager::getSYCLDeviceImages (const context & Ctx, const std::vector< device > & Devs, bundle_state State)
Definition at line 1619 of file program_manager.cpp.
getSYCLDeviceImages() [2/3]
std::vector< device_image_plain > cl::sycl::detail::ProgramManager::getSYCLDeviceImages (const context & Ctx, const std::vector< device > & Devs, const DevImgSelectorImpl & Selector, bundle_state TargetState)
Definition at line 1630 of file program_manager.cpp.
getSYCLDeviceImages() [3/3]
std::vector< device_image_plain > cl::sycl::detail::ProgramManager::getSYCLDeviceImages (const context & Ctx, const std::vector< device > & Devs, const std::vector< kernel_id > & KernelIDs, bundle_state TargetState)
Definition at line 1649 of file program_manager.cpp.
References cl::sycl::make_error_code().
getSYCLDeviceImagesWithCompatibleState()
std::vector< device_image_plain > cl::sycl::detail::ProgramManager::getSYCLDeviceImagesWithCompatibleState (const context & Ctx, const std::vector< device > & Devs, bundle_state TargetState, const std::vector< kernel_id > & KernelIDs = {})
Definition at line 1505 of file program_manager.cpp.
References cl::sycl::detail::compatibleWithDevice(), and cl::sycl::detail::getBinImageState().
getSYCLKernelID()
kernel_id cl::sycl::detail::ProgramManager::getSYCLKernelID (const std::string & KernelName)
Definition at line 1450 of file program_manager.cpp.
References PI_INVALID_KERNEL_NAME.
Referenced by cl::sycl::detail::enqueueImpKernel().
kernelUsesAssert()
bool cl::sycl::detail::ProgramManager::kernelUsesAssert (OSModuleHandle M, const std::string & KernelName) const
Definition at line 1089 of file program_manager.cpp.
References cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::end().
link()
std::vector< device_image_plain > cl::sycl::detail::ProgramManager::link (const std::vector< device_image_plain > & DeviceImages, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 1743 of file program_manager.cpp.
References cl::sycl::detail::appendLinkOptionsFromImage(), cl::sycl::detail::applyLinkOptionsFromEnvironment(), cl::sycl::build(), cl::sycl::detail::plugin::call_nocheck(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::make_error_code(), PI_SUCCESS, piProgramLink(), and cl::sycl::detail::plugin::reportPiError().
The documentation for this class was generated from the following files:
source/detail/program_manager/program_manager.hpp
source/detail/program_manager/program_manager.cpp