DPC++ Runtime: cl::sycl::detail::SYCLMemObjI Class Reference
cl::sycl::detail::SYCLMemObjI Class Reference abstract
#include <CL/sycl/detail/sycl_mem_obj_i.hpp>
Public Types
enum MemObjType { Buffer = 0, Image = 1, Undefined = 2 }
Public Member Functions
virtual ~SYCLMemObjI ()=default
virtual MemObjType getType () const =0
virtual void * allocateMem (ContextImplPtr Context, bool InitFromUserData, void *HostPtr, RT::PiEvent &InteropEvent)=0
virtual void * allocateHostMem ()=0
virtual void releaseMem (ContextImplPtr Context, void *Ptr)=0
virtual void releaseHostMem (void *Ptr)=0
virtual size_t getSize () const =0
virtual ContextImplPtr getInteropContext () const =0
Protected Attributes
std::shared_ptr< MemObjRecord > MRecord
Friends
class Scheduler
class ExecCGCommand
Detailed Description
Definition at line 28 of file sycl_mem_obj_i.hpp.
Member Enumeration Documentation
MemObjType
enum cl::sycl::detail::SYCLMemObjI::MemObjType
Enumerator
Buffer
Image
Undefined
Definition at line 32 of file sycl_mem_obj_i.hpp.
Constructor & Destructor Documentation
~SYCLMemObjI()
virtual cl::sycl::detail::SYCLMemObjI::~SYCLMemObjI () virtual default
Member Function Documentation
allocateHostMem()
virtual void* cl::sycl::detail::SYCLMemObjI::allocateHostMem () pure virtual
Implemented in cl::sycl::detail::SYCLMemObjT.
Referenced by cl::sycl::detail::MemoryManager::allocateHostMemory().
allocateMem()
virtual void* cl::sycl::detail::SYCLMemObjI::allocateMem (ContextImplPtr Context, bool InitFromUserData, void * HostPtr, RT::PiEvent & InteropEvent) pure virtual
Implemented in cl::sycl::detail::image_impl< Dimensions >, cl::sycl::detail::buffer_impl, and cl::sycl::detail::SYCLMemObjT.
Referenced by cl::sycl::detail::MemoryManager::allocate().
getInteropContext()
virtual ContextImplPtr cl::sycl::detail::SYCLMemObjI::getInteropContext () const pure virtual
Implemented in cl::sycl::detail::SYCLMemObjT.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::getOrInsertMemObjRecord().
getSize()
virtual size_t cl::sycl::detail::SYCLMemObjI::getSize () const pure virtual
Implemented in cl::sycl::detail::SYCLMemObjT.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::findAllocaForReq().
getType()
virtual MemObjType cl::sycl::detail::SYCLMemObjI::getType () const pure virtual
Implemented in cl::sycl::detail::SYCLMemObjT, cl::sycl::detail::image_impl< Dimensions >, and cl::sycl::detail::buffer_impl.
Referenced by cl::sycl::detail::copyD2D(), cl::sycl::detail::copyD2H(), cl::sycl::detail::copyH2D(), cl::sycl::detail::MemoryManager::fill(), and cl::sycl::detail::UpdateHostRequirementCommand::printDot().
releaseHostMem()
virtual void cl::sycl::detail::SYCLMemObjI::releaseHostMem (void * Ptr) pure virtual
Implemented in cl::sycl::detail::SYCLMemObjT.
Referenced by cl::sycl::detail::MemoryManager::releaseMemObj().
releaseMem()
virtual void cl::sycl::detail::SYCLMemObjI::releaseMem (ContextImplPtr Context, void * Ptr) pure virtual
Implemented in cl::sycl::detail::SYCLMemObjT.
Referenced by cl::sycl::detail::MemoryManager::release().
Friends And Related Function Documentation
ExecCGCommand
friend class ExecCGCommand friend
Definition at line 76 of file sycl_mem_obj_i.hpp.
Scheduler
friend class Scheduler friend
Definition at line 75 of file sycl_mem_obj_i.hpp.
Member Data Documentation
MRecord
std::shared_ptr<MemObjRecord> cl::sycl::detail::SYCLMemObjI::MRecord protected
Definition at line 74 of file sycl_mem_obj_i.hpp.
Referenced by cl::sycl::detail::Scheduler::enqueueLeavesOfReqUnlocked(), cl::sycl::detail::Scheduler::getMemObjRecord(), cl::sycl::detail::Scheduler::GraphBuilder::getMemObjRecord(), cl::sycl::detail::Scheduler::GraphBuilder::getOrInsertMemObjRecord(), cl::sycl::detail::Scheduler::GraphBuilder::removeRecordForMemObj(), and cl::sycl::detail::SYCLMemObjT::updateHostMemory().
The documentation for this class was generated from the following file:
include/CL/sycl/detail/sycl_mem_obj_i.hpp