DPC++ Runtime: sycl::_V1::detail::OwnerLessBase< SyclObjT > Class Template Reference
sycl::_V1::detail::OwnerLessBase< SyclObjT > Class Template Reference
#include <sycl/detail/owner_less_base.hpp>
Public Member Functions
bool ext_oneapi_owner_before (const ext::oneapi::detail::weak_object_base< SyclObjT > &Other) const noexcept
Compares the object against a weak object using an owner-based implementation-defined ordering.
bool ext_oneapi_owner_before (const SyclObjT &Other) const noexcept
Compares the object against another object using an owner-based implementation-defined ordering.
Detailed Description
template<class SyclObjT>
class sycl::_V1::detail::OwnerLessBase< SyclObjT >
Definition at line 20 of file owner_less_base.hpp.
Member Function Documentation
ext_oneapi_owner_before() [1/2]
template<class SyclObjT > bool sycl::_V1::detail::OwnerLessBase< SyclObjT >::ext_oneapi_owner_before (const ext::oneapi::detail::weak_object_base< SyclObjT > & Other) const inline noexcept
Compares the object against a weak object using an owner-based implementation-defined ordering.
Parameters
Other is the weak object to compare ordering against.
Returns
true if this object precedes
Parameters
Other and false otherwise.
Definition at line 28 of file owner_less_base.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::ext::oneapi::detail::getSyclWeakObjImpl().
ext_oneapi_owner_before() [2/2]
template<class SyclObjT > bool sycl::_V1::detail::OwnerLessBase< SyclObjT >::ext_oneapi_owner_before (const SyclObjT & Other) const inline noexcept
Compares the object against another object using an owner-based implementation-defined ordering.
Parameters
Other is the object to compare ordering against.
Returns
true if this object precedes
Parameters
Other and false otherwise.
Definition at line 40 of file owner_less_base.hpp.
References sycl::_V1::detail::getSyclObjImpl().
The documentation for this class was generated from the following file:
include/sycl/detail/owner_less_base.hpp