DPC++ Runtime: sycl::_V1::ext::oneapi::detail::filter_selector_impl Class Reference
sycl::_V1::ext::oneapi::detail::filter_selector_impl Class Reference
#include <detail/filter_selector_impl.hpp>
Public Member Functions
filter_selector_impl (const std::string &filter)
int operator() (const device &dev) const
void reset () const
Detailed Description
Definition at line 28 of file filter_selector_impl.hpp.
Constructor & Destructor Documentation
filter_selector_impl()
sycl::_V1::ext::oneapi::detail::filter_selector_impl::filter_selector_impl (const std::string & filter)
Definition at line 90 of file filter_selector_impl.cpp.
References sycl::_V1::ext::oneapi::detail::create_filter(), sycl::_V1::device::get_devices(), and sycl::_V1::ext::oneapi::detail::tokenize().
Member Function Documentation
operator()()
int sycl::_V1::ext::oneapi::detail::filter_selector_impl::operator() (const device & dev) const
Definition at line 101 of file filter_selector_impl.cpp.
References sycl::_V1::all, sycl::_V1::default_selector_v(), sycl::_V1::device::get_info(), and sycl::_V1::detail::getSyclObjImpl().
reset()
void sycl::_V1::ext::oneapi::detail::filter_selector_impl::reset () const
Definition at line 155 of file filter_selector_impl.cpp.
The documentation for this class was generated from the following files:
source/detail/filter_selector_impl.hpp
source/detail/filter_selector_impl.cpp