DPC++ Runtime: event_callback Class Reference
event_callback Class Reference
#include <cuda/pi_cuda.hpp>
Public Member Functions
void trigger_callback (pi_event event, pi_int32 currentEventStatus) const
event_callback (pi_event_status status, pfn_notify callback, void *userData)
pi_event_status get_status () const noexcept
Detailed Description
Definition at line 306 of file pi_cuda.hpp.
Constructor & Destructor Documentation
event_callback()
event_callback::event_callback (pi_event_status status, pfn_notify callback, void * userData) inline
Definition at line 324 of file pi_cuda.hpp.
Member Function Documentation
get_status()
pi_event_status event_callback::get_status () const inline noexcept
Definition at line 328 of file pi_cuda.hpp.
Referenced by _pi_event::set_event_callback().
trigger_callback()
void event_callback::trigger_callback (pi_event event, pi_int32 currentEventStatus) const inline
Definition at line 308 of file pi_cuda.hpp.
Referenced by _pi_event::set_event_callback(), and _pi_event::trigger_callback().
The documentation for this class was generated from the following file:
plugins/cuda/pi_cuda.hpp