DPC++ Runtime: sycl::_V1::detail::CG Class Reference
sycl::_V1::detail::CG Class Reference
Base class for all types of command groups.
#include <sycl/detail/cg.hpp>
Classes
struct StorageInitHelper
Public Types
enum CGTYPE : unsigned int {
None = 0 , Kernel = 1 , CopyAccToPtr = 2 , CopyPtrToAcc = 3 ,
CopyAccToAcc = 4 , Barrier = 5 , BarrierWaitlist = 6 , Fill = 7 ,
UpdateHost = 8 , CopyUSM = 10 , FillUSM = 11 , PrefetchUSM = 12 ,
CodeplayHostTask = 14 , AdviseUSM = 15 , Copy2DUSM = 16 , Fill2DUSM = 17 ,
Memset2DUSM = 18 , CopyToDeviceGlobal = 19 , CopyFromDeviceGlobal = 20 , ReadWriteHostPipe = 21 ,
ExecCommandBuffer = 22 , CopyImage = 23 , SemaphoreWait = 24 , SemaphoreSignal = 25
}
Type of the command group.
Public Member Functions
CG (CGTYPE Type, StorageInitHelper D, detail::code_location loc={})
CG (CG &&CommandGroup)=default
CG (const CG &CommandGroup)=default
CGTYPE getType () const
std::vector< std::vector< char > > & getArgsStorage ()
std::vector< detail::AccessorImplPtr > & getAccStorage ()
std::vector< std::shared_ptr< const void > > & getSharedPtrStorage ()
std::vector< AccessorImplHost * > & getRequirements ()
std::vector< detail::EventImplPtr > & getEvents ()
virtual std::vector< std::shared_ptr< const void > > getAuxiliaryResources () const
virtual void clearAuxiliaryResources ()
virtual ~CG ()=default
Public Attributes
std::string MFunctionName
std::string MFileName
int32_t MLine
int32_t MColumn
Detailed Description
Base class for all types of command groups.
Definition at line 53 of file cg.hpp.
Member Enumeration Documentation
CGTYPE
enum sycl::_V1::detail::CG::CGTYPE : unsigned int
Type of the command group.
Enumerator
None
Kernel
CopyAccToPtr
CopyPtrToAcc
CopyAccToAcc
Barrier
BarrierWaitlist
Fill
UpdateHost
CopyUSM
FillUSM
PrefetchUSM
CodeplayHostTask
AdviseUSM
Copy2DUSM
Fill2DUSM
Memset2DUSM
CopyToDeviceGlobal
CopyFromDeviceGlobal
ReadWriteHostPipe
ExecCommandBuffer
CopyImage
SemaphoreWait
SemaphoreSignal
Definition at line 56 of file cg.hpp.
Constructor & Destructor Documentation
CG() [1/3]
sycl::_V1::detail::CG::CG (CGTYPE Type, StorageInitHelper D, detail::code_location loc = {}) inline
Definition at line 112 of file cg.hpp.
CG() [2/3]
sycl::_V1::detail::CG::CG (CG && CommandGroup) default
CG() [3/3]
sycl::_V1::detail::CG::CG (const CG & CommandGroup) default
~CG()
virtual sycl::_V1::detail::CG::~CG () virtual default
Member Function Documentation
clearAuxiliaryResources()
virtual void sycl::_V1::detail::CG::clearAuxiliaryResources () inline virtual
Reimplemented in sycl::_V1::detail::CGCopy, and sycl::_V1::detail::CGExecKernel.
Definition at line 149 of file cg.hpp.
getAccStorage()
std::vector<detail::AccessorImplPtr>& sycl::_V1::detail::CG::getAccStorage () inline
Definition at line 133 of file cg.hpp.
References sycl::_V1::detail::CG::StorageInitHelper::MAccStorage.
getArgsStorage()
std::vector<std::vector<char> >& sycl::_V1::detail::CG::getArgsStorage () inline
Definition at line 130 of file cg.hpp.
References sycl::_V1::detail::CG::StorageInitHelper::MArgsStorage.
getAuxiliaryResources()
virtual std::vector<std::shared_ptr<const void> > sycl::_V1::detail::CG::getAuxiliaryResources () const inline virtual
Reimplemented in sycl::_V1::detail::CGCopy, and sycl::_V1::detail::CGExecKernel.
Definition at line 146 of file cg.hpp.
getEvents()
std::vector<detail::EventImplPtr>& sycl::_V1::detail::CG::getEvents () inline
Definition at line 143 of file cg.hpp.
References sycl::_V1::detail::CG::StorageInitHelper::MEvents.
getRequirements()
std::vector<AccessorImplHost *>& sycl::_V1::detail::CG::getRequirements () inline
Definition at line 140 of file cg.hpp.
References sycl::_V1::detail::CG::StorageInitHelper::MRequirements.
getSharedPtrStorage()
std::vector<std::shared_ptr<const void> >& sycl::_V1::detail::CG::getSharedPtrStorage () inline
Definition at line 136 of file cg.hpp.
References sycl::_V1::detail::CG::StorageInitHelper::MSharedPtrStorage.
getType()
CGTYPE sycl::_V1::detail::CG::getType () const inline
Definition at line 128 of file cg.hpp.
Referenced by sycl::_V1::detail::Command::isFusable(), sycl::_V1::detail::isInteropHostTask(), and sycl::_V1::detail::DispatchHostTask::operator()().
Member Data Documentation
MColumn
int32_t sycl::_V1::detail::CG::MColumn
Definition at line 163 of file cg.hpp.
MFileName
std::string sycl::_V1::detail::CG::MFileName
Definition at line 161 of file cg.hpp.
MFunctionName
std::string sycl::_V1::detail::CG::MFunctionName
Definition at line 161 of file cg.hpp.
MLine
int32_t sycl::_V1::detail::CG::MLine
Definition at line 163 of file cg.hpp.
The documentation for this class was generated from the following file:
include/sycl/detail/cg.hpp