DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename > Class Template Reference
sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename > Class Template Reference
#include <sycl/ext/oneapi/device_global/device_global.hpp>
Public Member Functions
device_global_base ()=default
template<access::decorated IsDecorated>
multi_ptr< T, access::address_space::global_space, IsDecorated > get_multi_ptr () noexcept
template<access::decorated IsDecorated>
multi_ptr< const T, access::address_space::global_space, IsDecorated > get_multi_ptr () const noexcept
Protected Types
using pointer_t = typename decorated_global_ptr< T >::pointer
Protected Member Functions
pointer_t get_ptr () noexcept
pointer_t get_ptr () const noexcept
Protected Attributes
pointer_t usmptr {}
const T init_val {}
Detailed Description
template<typename T, typename PropertyListT, typename = void>
class sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >
Definition at line 54 of file device_global.hpp.
Member Typedef Documentation
pointer_t
template<typename T , typename PropertyListT , typename = void> using sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::pointer_t = typename decorated_global_ptr<T>::pointer protected
Definition at line 56 of file device_global.hpp.
Constructor & Destructor Documentation
device_global_base()
template<typename T , typename PropertyListT , typename = void> sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::device_global_base () default
Member Function Documentation
get_multi_ptr() [1/2]
template<typename T , typename PropertyListT , typename = void> template<access::decorated IsDecorated> multi_ptr<const T, access::address_space::global_space, IsDecorated> sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::get_multi_ptr () const inline noexcept
Definition at line 84 of file device_global.hpp.
References __SYCL_HOST_NOT_SUPPORTED, and sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::get_ptr().
get_multi_ptr() [2/2]
template<typename T , typename PropertyListT , typename = void> template<access::decorated IsDecorated> multi_ptr<T, access::address_space::global_space, IsDecorated> sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::get_multi_ptr () inline noexcept
Definition at line 76 of file device_global.hpp.
References __SYCL_HOST_NOT_SUPPORTED, and sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::get_ptr().
get_ptr() [1/2]
template<typename T , typename PropertyListT , typename = void> pointer_t sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::get_ptr () const inline protected noexcept
Definition at line 64 of file device_global.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::usmptr.
get_ptr() [2/2]
template<typename T , typename PropertyListT , typename = void> pointer_t sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::get_ptr () inline protected noexcept
Definition at line 63 of file device_global.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::usmptr.
Referenced by sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::get_multi_ptr(), and sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, properties_t< Props... >, std::enable_if_t< properties_t< Props... >::template has_property< device_image_scope_key >()> >::get_multi_ptr().
Member Data Documentation
init_val
template<typename T , typename PropertyListT , typename = void> const T sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::init_val {} protected
Definition at line 61 of file device_global.hpp.
usmptr
template<typename T , typename PropertyListT , typename = void> pointer_t sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::usmptr {} mutable protected
Definition at line 60 of file device_global.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::detail::device_global_base< T, PropertyListT, typename >::get_ptr().
The documentation for this class was generated from the following file:
include/sycl/ext/oneapi/device_global/device_global.hpp