DPC++ Runtime: sycl::_V1::property_list Class Reference
sycl::_V1::property_list Class Reference
DPC++ User API
Objects of the property_list class are containers for the SYCL properties.
#include <sycl/property_list.hpp>
Public Member Functions
template<typename... PropsT, typename = typename std::enable_if_t< AllProperties<PropsT...>::value>>
property_list (PropsT... Props)
template<typename PropT >
PropT get_property () const
template<typename PropT >
bool has_property () const noexcept
void add_or_replace_accessor_properties (const property_list &PropertyList)
void delete_accessor_property (const sycl::detail::PropWithDataKind &Kind)
template<typename... T>
operator ext::oneapi::accessor_property_list< T... > ()
Friends
template<typename... PropsT>
class ext::oneapi::accessor_property_list
Additional Inherited Members
Protected Member Functions inherited from sycl::_V1::detail::PropertyListBase
PropertyListBase (std::bitset< DataLessPropKind::DataLessPropKindSize > DataLessProps)
PropertyListBase (std::bitset< DataLessPropKind::DataLessPropKindSize > DataLessProps, std::vector< std::shared_ptr< PropertyWithDataBase >> PropsWithData)
void ctorHelper ()
template<typename... PropsT, class PropT >
std::enable_if_t< std::is_base_of_v< DataLessPropertyBase, PropT > > ctorHelper (PropT &, PropsT... Props)
template<typename... PropsT, class PropT >
std::enable_if_t< std::is_base_of_v< PropertyWithDataBase, PropT > > ctorHelper (PropT &Prop, PropsT... Props)
template<typename... PropsT, class PropT >
std::enable_if_t<!std::is_base_of_v< PropertyWithDataBase, PropT > &&!std::is_base_of_v< DataLessPropertyBase, PropT > > ctorHelper (PropT &, PropsT... Props)
template<typename PropT >
std::enable_if_t< std::is_base_of_v< DataLessPropertyBase, PropT >, bool > has_property_helper () const noexcept
template<typename PropT >
std::enable_if_t< std::is_base_of_v< PropertyWithDataBase, PropT >, bool > has_property_helper () const noexcept
template<typename PropT >
std::enable_if_t< std::is_base_of_v< DataLessPropertyBase, PropT >, PropT > get_property_helper () const
template<typename PropT >
std::enable_if_t< std::is_base_of_v< PropertyWithDataBase, PropT >, PropT > get_property_helper () const
void add_or_replace_accessor_properties_helper (const std::vector< std::shared_ptr< PropertyWithDataBase >> &PropsWithData)
void delete_accessor_property_helper (const PropWithDataKind &Kind)
Protected Attributes inherited from sycl::_V1::detail::PropertyListBase
std::bitset< DataLessPropKind::DataLessPropKindSize > MDataLessProps
std::vector< std::shared_ptr< PropertyWithDataBase > > MPropsWithData
Detailed Description
Objects of the property_list class are containers for the SYCL properties.
Definition at line 31 of file property_list.hpp.
Constructor & Destructor Documentation
property_list()
template<typename... PropsT, typename = typename std::enable_if_t< AllProperties<PropsT...>::value>> sycl::_V1::property_list::property_list (PropsT... Props) inline
Definition at line 43 of file property_list.hpp.
References sycl::_V1::detail::PropertyListBase::ctorHelper().
Member Function Documentation
add_or_replace_accessor_properties()
void sycl::_V1::property_list::add_or_replace_accessor_properties (const property_list & PropertyList) inline
Definition at line 59 of file property_list.hpp.
References sycl::_V1::detail::PropertyListBase::add_or_replace_accessor_properties_helper(), and sycl::_V1::detail::PropertyListBase::MPropsWithData.
delete_accessor_property()
void sycl::_V1::property_list::delete_accessor_property (const sycl::detail::PropWithDataKind & Kind) inline
Definition at line 62 of file property_list.hpp.
References sycl::_V1::detail::PropertyListBase::delete_accessor_property_helper().
get_property()
template<typename PropT > PropT sycl::_V1::property_list::get_property () const inline
Definition at line 47 of file property_list.hpp.
Referenced by sycl::_V1::detail::usm::alignedAllocHost(), sycl::_V1::detail::usm::alignedAllocInternal(), sycl::_V1::detail::MemoryManager::allocateBufferObject(), sycl::_V1::usm_allocator< T, AllocKind, Alignment >::get_property(), sycl::_V1::detail::context_impl::get_property(), sycl::_V1::detail::program_impl::get_property(), and sycl::_V1::detail::queue_impl::get_property().
has_property()
template<typename PropT > bool sycl::_V1::property_list::has_property () const inline noexcept
Definition at line 55 of file property_list.hpp.
Referenced by sycl::_V1::detail::usm::alignedAllocHost(), sycl::_V1::detail::usm::alignedAllocInternal(), sycl::_V1::detail::MemoryManager::allocateBufferObject(), sycl::_V1::detail::buffer_impl::buffer_impl(), sycl::_V1::detail::context_impl::context_impl(), sycl::_V1::detail::queue_impl::createPiQueueProperties(), sycl::_V1::detail::program_impl::has_property(), sycl::_V1::usm_allocator< T, AllocKind, Alignment >::has_property(), sycl::_V1::detail::context_impl::has_property(), sycl::_V1::detail::queue_impl::has_property(), and sycl::_V1::detail::make_queue().
operator ext::oneapi::accessor_property_list< T... >()
template<typename... T> sycl::_V1::property_list::operator ext::oneapi::accessor_property_list< T... > inline
Definition at line 21 of file property_list_conversion.hpp.
Friends And Related Function Documentation
ext::oneapi::accessor_property_list
template<typename... PropsT> friend class ext::oneapi::accessor_property_list friend
Definition at line 75 of file property_list.hpp.
The documentation for this class was generated from the following files:
include/sycl/property_list.hpp
include/sycl/property_list_conversion.hpp