DPC++ Runtime: sycl::_V1::ext::intel::experimental::esimd::tfloat32 Class Reference
sycl::_V1::ext::intel::experimental::esimd::tfloat32 Class Reference
#include <sycl/ext/intel/experimental/esimd/tfloat32.hpp>
Public Member Functions
tfloat32 ()=default
tfloat32 (const tfloat32 &)=default
~tfloat32 ()=default
tfloat32 (const float &a)
tfloat32 & operator= (const float &rhs)
operator float () const
storage_t raw () const
operator bool ()
Static Public Member Functions
static storage_t from_float (const float &a)
static float to_float (const storage_t &a)
Friends
tfloat32 operator- (tfloat32 &lhs)
Detailed Description
Definition at line 23 of file tfloat32.hpp.
Constructor & Destructor Documentation
tfloat32() [1/3]
sycl::_V1::ext::intel::experimental::esimd::tfloat32::tfloat32 () default
tfloat32() [2/3]
sycl::_V1::ext::intel::experimental::esimd::tfloat32::tfloat32 (const tfloat32 &) default
~tfloat32()
sycl::_V1::ext::intel::experimental::esimd::tfloat32::~tfloat32 () default
tfloat32() [3/3]
sycl::_V1::ext::intel::experimental::esimd::tfloat32::tfloat32 (const float & a) inline
Definition at line 43 of file tfloat32.hpp.
References from_float().
Member Function Documentation
from_float()
static storage_t sycl::_V1::ext::intel::experimental::esimd::tfloat32::from_float (const float & a) inline static
Definition at line 33 of file tfloat32.hpp.
Referenced by operator=(), and tfloat32().
operator bool()
sycl::_V1::ext::intel::experimental::esimd::tfloat32::operator bool () inline explicit
Definition at line 57 of file tfloat32.hpp.
References to_float().
operator float()
sycl::_V1::ext::intel::experimental::esimd::tfloat32::operator float () const inline
Definition at line 51 of file tfloat32.hpp.
References to_float().
operator=()
tfloat32& sycl::_V1::ext::intel::experimental::esimd::tfloat32::operator= (const float & rhs) inline
Definition at line 45 of file tfloat32.hpp.
References from_float().
raw()
storage_t sycl::_V1::ext::intel::experimental::esimd::tfloat32::raw () const inline
Definition at line 54 of file tfloat32.hpp.
to_float()
static float sycl::_V1::ext::intel::experimental::esimd::tfloat32::to_float (const storage_t & a) inline static
Definition at line 38 of file tfloat32.hpp.
Referenced by operator bool(), and operator float().
Friends And Related Function Documentation
operator-
tfloat32 operator- (tfloat32 & lhs) friend
Definition at line 60 of file tfloat32.hpp.
The documentation for this class was generated from the following file:
include/sycl/ext/intel/experimental/esimd/tfloat32.hpp