DPC++ Runtime: cl::sycl::detail::HostProfilingInfo Class Reference
cl::sycl::detail::HostProfilingInfo Class Reference
Profiling info for the host execution.
#include <CL/sycl/detail/host_profiling_info.hpp>
Public Member Functions
cl_ulong getStartTime () const
Returns event's start time.
cl_ulong getEndTime () const
Returns event's end time.
void start ()
Measures event's start time.
void end ()
Measures event's end time.
Detailed Description
Profiling info for the host execution.
Definition at line 19 of file host_profiling_info.hpp.
Member Function Documentation
end()
void cl::sycl::detail::HostProfilingInfo::end ()
Measures event's end time.
Definition at line 342 of file event_impl.cpp.
References cl::sycl::detail::getTimestamp().
Referenced by cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims >::call().
getEndTime()
cl_ulong cl::sycl::detail::HostProfilingInfo::getEndTime () const inline
Returns event's end time.
Returns
event's end time in nanoseconds.
Definition at line 31 of file host_profiling_info.hpp.
getStartTime()
cl_ulong cl::sycl::detail::HostProfilingInfo::getStartTime () const inline
Returns event's start time.
Returns
event's start time in nanoseconds.
Definition at line 27 of file host_profiling_info.hpp.
start()
void cl::sycl::detail::HostProfilingInfo::start ()
Measures event's start time.
Definition at line 340 of file event_impl.cpp.
References cl::sycl::detail::getTimestamp().
Referenced by cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims >::call().
The documentation for this class was generated from the following files:
include/CL/sycl/detail/host_profiling_info.hpp
source/detail/event_impl.cpp