DPC++ Runtime: cl::sycl::detail::spec_constant_impl Class Reference
cl::sycl::detail::spec_constant_impl Class Reference
#include <detail/spec_constant_impl.hpp>
Public Member Functions
spec_constant_impl ()=default
spec_constant_impl (size_t Size, const void *Val)
void set (size_t Size, const void *Val)
size_t getSize () const
const char * getValuePtr () const
bool isSet () const
Detailed Description
Definition at line 24 of file spec_constant_impl.hpp.
Constructor & Destructor Documentation
spec_constant_impl() [1/2]
cl::sycl::detail::spec_constant_impl::spec_constant_impl () default
spec_constant_impl() [2/2]
cl::sycl::detail::spec_constant_impl::spec_constant_impl (size_t Size, const void * Val) inline
Definition at line 28 of file spec_constant_impl.hpp.
Member Function Documentation
getSize()
size_t cl::sycl::detail::spec_constant_impl::getSize () const inline
Definition at line 32 of file spec_constant_impl.hpp.
Referenced by cl::sycl::detail::operator<<(), and cl::sycl::detail::stableSerializeSpecConstRegistry().
getValuePtr()
const char* cl::sycl::detail::spec_constant_impl::getValuePtr () const inline
Definition at line 33 of file spec_constant_impl.hpp.
Referenced by cl::sycl::detail::program_impl::flush_spec_constants(), cl::sycl::detail::operator<<(), and cl::sycl::detail::stableSerializeSpecConstRegistry().
isSet()
bool cl::sycl::detail::spec_constant_impl::isSet () const inline
Definition at line 34 of file spec_constant_impl.hpp.
Referenced by cl::sycl::detail::program_impl::flush_spec_constants(), and cl::sycl::detail::operator<<().
set()
void cl::sycl::detail::spec_constant_impl::set (size_t Size, const void * Val)
Definition at line 23 of file spec_constant_impl.cpp.
References PI_INVALID_VALUE.
Referenced by cl::sycl::detail::program_impl::set_spec_constant_impl().
The documentation for this class was generated from the following files:
source/detail/spec_constant_impl.hpp
source/detail/spec_constant_impl.cpp