DPC++ Runtime: cl::sycl::kernel_id Class Reference
cl::sycl::kernel_id Class Reference
DPC++ User API
Objects of the class identify kernel is some kernel_bundle related APIs.
#include <CL/sycl/kernel_bundle.hpp>
Public Member Functions
kernel_id ()=delete
const char * get_name () const noexcept
bool operator== (const kernel_id &RHS) const
bool operator!= (const kernel_id &RHS) const
Friends
template<class T >
T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Detailed Description
Objects of the class identify kernel is some kernel_bundle related APIs.
Definition at line 39 of file kernel_bundle.hpp.
Constructor & Destructor Documentation
kernel_id()
cl::sycl::kernel_id::kernel_id () delete
Member Function Documentation
get_name()
const char * cl::sycl::kernel_id::get_name () const noexcept
Returns
a null-terminated string which contains the kernel name
Definition at line 20 of file kernel_bundle.cpp.
Referenced by cl::sycl::detail::kernel_bundle_impl::get_kernel(), cl::sycl::detail::LessByNameComp::operator()(), and cl::sycl::detail::EqualByNameComp::operator()().
operator!=()
bool cl::sycl::kernel_id::operator!= (const kernel_id & RHS) const inline
Definition at line 48 of file kernel_bundle.hpp.
operator==()
bool cl::sycl::kernel_id::operator== (const kernel_id & RHS) const inline
Definition at line 46 of file kernel_bundle.hpp.
Friends And Related Function Documentation
detail::createSyclObjFromImpl
template<class T > T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
The documentation for this class was generated from the following files:
include/CL/sycl/kernel_bundle.hpp
source/kernel_bundle.cpp