DPC++ Runtime: _pi_event Struct Reference
_pi_event Struct Reference
PI Event mapping to CUevent.
#include <cuda/pi_cuda.hpp>
Public Types
using native_type = CUevent
Public Member Functions
pi_result record ()
pi_result wait ()
pi_result start ()
native_type get () const noexcept
pi_queue get_queue () const noexcept
pi_command_type get_command_type () const noexcept
pi_uint32 get_reference_count () const noexcept
bool is_recorded () const noexcept
bool is_started () const noexcept
bool is_completed () const noexcept
pi_int32 get_execution_status () const noexcept
pi_context get_context () const noexcept
pi_uint32 increment_reference_count ()
pi_uint32 decrement_reference_count ()
pi_uint32 get_event_id () const noexcept
pi_uint64 get_queued_time () const
pi_uint64 get_start_time () const
pi_uint64 get_end_time () const
pi_result release ()
~_pi_event ()
_pi_event (ze_event_handle_t ZeEvent, ze_event_pool_handle_t ZeEventPool, pi_context Context, pi_command_type CommandType)
Public Member Functions inherited from _pi_object
_pi_object ()
Static Public Member Functions
static pi_event make_native (pi_command_type type, pi_queue queue)
static ze_event_handle_t * createZeEventList (pi_uint32, const pi_event *)
static void deleteZeEventList (ze_event_handle_t *)
Public Attributes
ze_event_handle_t ZeEvent
ze_event_pool_handle_t ZeEventPool
ze_command_list_handle_t ZeCommandList
pi_queue Queue
pi_command_type CommandType
pi_context Context
void * CommandData
Public Attributes inherited from _pi_object
std::atomic< pi_uint32 > RefCount
Detailed Description
PI Event mapping to CUevent.
Definition at line 391 of file pi_cuda.hpp.
Member Typedef Documentation
native_type
using _pi_event::native_type = CUevent
Definition at line 393 of file pi_cuda.hpp.
Constructor & Destructor Documentation
~_pi_event()
_pi_event::~_pi_event ()
Definition at line 314 of file pi_cuda.cpp.
References cuda_piContextRelease(), and cuda_piQueueRelease().
_pi_event()
_pi_event::_pi_event (ze_event_handle_t ZeEvent, ze_event_pool_handle_t ZeEventPool, pi_context Context, pi_command_type CommandType) inline
Definition at line 450 of file pi_level_zero.hpp.
Member Function Documentation
createZeEventList()
ze_event_handle_t * _pi_event::createZeEventList (pi_uint32 EventListLength, const pi_event * EventList) static
Definition at line 614 of file pi_level_zero.cpp.
References ZeEvent.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and piextUSMEnqueuePrefetch().
decrement_reference_count()
pi_uint32 _pi_event::decrement_reference_count () inline
Definition at line 431 of file pi_cuda.hpp.
Referenced by cuda_piEventRelease().
deleteZeEventList()
void _pi_event::deleteZeEventList (ze_event_handle_t * ZeEventList) static
Definition at line 628 of file pi_level_zero.cpp.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and piextUSMEnqueuePrefetch().
get()
native_type _pi_event::get () const inline noexcept
Definition at line 401 of file pi_cuda.hpp.
Referenced by cl::sycl::detail::Command::waitForEvents().
get_command_type()
pi_command_type _pi_event::get_command_type () const inline noexcept
Definition at line 405 of file pi_cuda.hpp.
Referenced by cuda_piEventGetInfo().
get_context()
pi_context _pi_event::get_context () const inline noexcept
Definition at line 427 of file pi_cuda.hpp.
Referenced by cuda_piEventGetInfo(), cuda_piEventRelease(), and cuda_piEventsWait().
get_end_time()
pi_uint64 _pi_event::get_end_time () const
Definition at line 356 of file pi_cuda.cpp.
References _pi_context::evBase_, is_recorded(), and is_started().
get_event_id()
pi_uint32 _pi_event::get_event_id () const inline noexcept
Definition at line 433 of file pi_cuda.hpp.
get_execution_status()
pi_int32 _pi_event::get_execution_status () const inline noexcept
Definition at line 415 of file pi_cuda.hpp.
References PI_EVENT_COMPLETE, PI_EVENT_RUNNING, and PI_EVENT_SUBMITTED.
Referenced by cuda_piEventGetInfo().
get_queue()
pi_queue _pi_event::get_queue () const inline noexcept
Definition at line 403 of file pi_cuda.hpp.
Referenced by cuda_piEventGetInfo().
get_queued_time()
pi_uint64 _pi_event::get_queued_time () const
Definition at line 339 of file pi_cuda.cpp.
References _pi_context::evBase_, and is_started().
get_reference_count()
pi_uint32 _pi_event::get_reference_count () const inline noexcept
Definition at line 407 of file pi_cuda.hpp.
Referenced by cuda_piEventGetInfo(), and cuda_piEventRelease().
get_start_time()
pi_uint64 _pi_event::get_start_time () const
Definition at line 348 of file pi_cuda.cpp.
References _pi_context::evBase_, and is_started().
increment_reference_count()
pi_uint32 _pi_event::increment_reference_count () inline
Definition at line 429 of file pi_cuda.hpp.
is_completed()
bool _pi_event::is_completed () const inline noexcept
Definition at line 413 of file pi_cuda.hpp.
is_recorded()
bool _pi_event::is_recorded () const inline noexcept
Definition at line 409 of file pi_cuda.hpp.
Referenced by get_end_time(), and record().
is_started()
bool _pi_event::is_started () const inline noexcept
Definition at line 411 of file pi_cuda.hpp.
Referenced by get_end_time(), get_queued_time(), get_start_time(), record(), and start().
make_native()
static pi_event _pi_event::make_native (pi_command_type type, pi_queue queue) inline static
Definition at line 448 of file pi_cuda.hpp.
References _pi_queue::get_context().
Referenced by cuda_piEnqueueEventsWait(), cuda_piEnqueueKernelLaunch(), cuda_piEnqueueMemBufferCopy(), cuda_piEnqueueMemBufferCopyRect(), cuda_piEnqueueMemBufferFill(), cuda_piEnqueueMemBufferMap(), cuda_piEnqueueMemBufferRead(), cuda_piEnqueueMemBufferReadRect(), cuda_piEnqueueMemBufferWrite(), cuda_piEnqueueMemBufferWriteRect(), cuda_piEnqueueMemImageCopy(), cuda_piEnqueueMemImageRead(), cuda_piEnqueueMemImageWrite(), cuda_piEnqueueMemUnmap(), cuda_piextUSMEnqueueMemcpy(), cuda_piextUSMEnqueueMemset(), and cuda_piextUSMEnqueuePrefetch().
record()
pi_result _pi_event::record ()
Definition at line 364 of file pi_cuda.cpp.
References cl::sycl::detail::pi::die(), _pi_queue::get(), _pi_queue::get_next_event_id(), is_recorded(), is_started(), PI_INVALID_EVENT, PI_INVALID_OPERATION, PI_INVALID_QUEUE, and PI_SUCCESS.
release()
pi_result _pi_event::release ()
Definition at line 408 of file pi_cuda.cpp.
References PI_QUEUE_PROFILING_ENABLE, PI_SUCCESS, and _pi_queue::properties_.
start()
pi_result _pi_event::start ()
Definition at line 321 of file pi_cuda.cpp.
References _pi_queue::get(), is_started(), PI_QUEUE_PROFILING_ENABLE, and _pi_queue::properties_.
wait()
pi_result _pi_event::wait ()
Definition at line 396 of file pi_cuda.cpp.
Member Data Documentation
CommandData
void* _pi_event::CommandData
Definition at line 475 of file pi_level_zero.hpp.
Referenced by piEventRelease().
CommandType
pi_command_type _pi_event::CommandType
Definition at line 468 of file pi_level_zero.hpp.
Referenced by piEventGetInfo(), and piEventRelease().
Context
pi_context _pi_event::Context
Definition at line 472 of file pi_level_zero.hpp.
Referenced by piEventGetProfilingInfo(), and piEventRelease().
Queue
pi_queue _pi_event::Queue
Definition at line 467 of file pi_level_zero.hpp.
Referenced by piEventGetInfo(), piEventGetProfilingInfo(), piEventRelease(), piEventsWait(), and recycleEventCommandList().
ZeCommandList
ze_command_list_handle_t _pi_event::ZeCommandList
Definition at line 463 of file pi_level_zero.hpp.
Referenced by recycleEventCommandList().
ZeEvent
ze_event_handle_t _pi_event::ZeEvent
Definition at line 456 of file pi_level_zero.hpp.
Referenced by createZeEventList(), piEventGetInfo(), piEventGetProfilingInfo(), piEventRelease(), and piEventsWait().
ZeEventPool
ze_event_pool_handle_t _pi_event::ZeEventPool
Definition at line 458 of file pi_level_zero.hpp.
Referenced by piEventRelease().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/level_zero/pi_level_zero.hpp
plugins/cuda/pi_cuda.cpp
plugins/level_zero/pi_level_zero.cpp