DPC++ Runtime: cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > Class Template Reference
cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > Class Template Reference
DPC++ User API » Accessors
Buffer accessor.
#include <CL/sycl/accessor.hpp>
Public Types
using value_type = DataT
using reference = DataT &
using const_reference = const DataT &
Public Member Functions
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename detail::enable_if_t< detail::IsRunTimePropertyListT< PropertyListT >::value &&std::is_same< T, DataT >::value &&Dims==0 &&((!IsPlaceH &&IsHostBuf)||(IsPlaceH &&(IsGlobalBuf||IsConstantBuf)))> * = nullptr>
accessor (buffer< T, 1, AllocatorT > &BufferRef, const property_list &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename detail::enable_if_t< detail::IsCxPropertyList< PropertyListT >::value &&std::is_same< T, DataT >::value &&Dims==0 &&((!IsPlaceH &&IsHostBuf)||(IsPlaceH &&(IsGlobalBuf||IsConstantBuf)))> * = nullptr>
accessor (buffer< T, 1, AllocatorT > &BufferRef, const ext::oneapi::accessor_property_list< PropTypes... > &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = typename detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && std::is_same<T, DataT>::value && (Dims == 0) && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>>
accessor (buffer< T, 1, AllocatorT > &BufferRef, handler &CommandGroupHandler, const property_list &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = typename detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && std::is_same<T, DataT>::value && (Dims == 0) && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>>
accessor (buffer< T, 1, AllocatorT > &BufferRef, handler &CommandGroupHandler, const ext::oneapi::accessor_property_list< PropTypes... > &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, const property_list &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, const ext::oneapi::accessor_property_list< PropTypes... > &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, const property_list &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, const ext::oneapi::accessor_property_list< PropTypes... > &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, range< Dimensions > AccessRange, const property_list &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, range< Dimensions > AccessRange, const ext::oneapi::accessor_property_list< PropTypes... > &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, range< Dimensions > AccessRange, const property_list &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, range< Dimensions > AccessRange, const ext::oneapi::accessor_property_list< PropTypes... > &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const property_list &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const ext::oneapi::accessor_property_list< PropTypes... > &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const property_list &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>>
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const ext::oneapi::accessor_property_list< PropTypes... > &PropertyList={}, const detail::code_location CodeLoc=detail::code_location::current())
template<typename... NewPropsT>
accessor (const accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, ext::oneapi::accessor_property_list< NewPropsT... >> &Other, const detail::code_location CodeLoc=detail::code_location::current())
constexpr bool is_placeholder () const
size_t get_size () const
__SYCL2020_DEPRECATED ("get_count() is deprecated, please use size() instead") size_t get_count() const
size_t size () const noexcept
template<int Dims = Dimensions, typename = detail::enable_if_t<(Dims > 0)>>
range< Dimensions > get_range () const
template<int Dims = Dimensions, typename = detail::enable_if_t<(Dims > 0)>>
id< Dimensions > get_offset () const
template<int Dims = Dimensions, typename RefT = RefType, typename = detail::enable_if_t<Dims == 0 && IsAccessAnyWrite && !std::is_const<RefT>::value>>
operator RefType () const
template<int Dims = Dimensions, typename = detail::enable_if_t<Dims == 0 && IsAccessReadOnly>>
operator ConstRefType () const
template<int Dims = Dimensions, typename = detail::enable_if_t<(Dims > 0) && IsAccessAnyWrite>>
RefType operator[] (id< Dimensions > Index) const
template<int Dims = Dimensions>
detail::enable_if_t<(Dims > 0) &&IsAccessReadOnly, ConstRefType > operator[] (id< Dimensions > Index) const
template<int Dims = Dimensions>
operator typename detail::enable_if_t< Dims==0 &&AccessMode==access::mode::atomic, atomic< DataT, AS > > () const
template<int Dims = Dimensions>
detail::enable_if_t<(Dims > 0) &&AccessMode==access::mode::atomic, atomic< DataT, AS > > operator[] (id< Dimensions > Index) const
template<int Dims = Dimensions>
detail::enable_if_t< Dims==1 &&AccessMode==access::mode::atomic, atomic< DataT, AS > > operator[] (size_t Index) const
template<int Dims = Dimensions, typename = detail::enable_if_t<(Dims > 1)>>
AccessorCommonT::template AccessorSubscript< Dims - 1 > operator[] (size_t Index) const
template<access::target AccessTarget_ = AccessTarget, typename = detail::enable_if_t<AccessTarget_ == access::target::host_buffer>>
DataT * get_pointer () const
template<access::target AccessTarget_ = AccessTarget, typename = detail::enable_if_t<AccessTarget_ == access::target::device>>
global_ptr< DataT > get_pointer () const
template<access::target AccessTarget_ = AccessTarget, typename = detail::enable_if_t<AccessTarget_ == access::target::constant_buffer>>
constant_ptr< DataT > get_pointer () const
bool operator== (const accessor &Rhs) const
bool operator!= (const accessor &Rhs) const
Protected Types
using AccessorCommonT = detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >
template<int Dims>
using AccessorSubscript = typename AccessorCommonT::template AccessorSubscript< Dims >
using ConcreteASPtrType = typename detail::DecoratedType< DataT, AS >::type *
using RefType = detail::const_if_const_AS< AS, DataT > &
using ConstRefType = const DataT &
using PtrType = detail::const_if_const_AS< AS, DataT > *
Protected Member Functions
template<int Dims = Dimensions>
size_t getLinearIndex (id< Dims > Id) const
PtrType getQualifiedPtr () const
range< 3 > & getAccessRange ()
const range< 3 > & getAccessRange () const
range< 3 > & getMemoryRange ()
const range< 3 > & getMemoryRange () const
id< 3 > & getOffset ()
const id< 3 > & getOffset () const
Static Protected Member Functions
template<typename T , int Dims>
static constexpr bool IsSameAsBuffer ()
static access::mode getAdjustedMode (const PropertyListT &PropertyList)
Protected Attributes
char padding [sizeof(detail::AccessorImplDevice< AdjustedDim >)+sizeof(PtrType) - sizeof(detail::AccessorBaseHost)]
Static Protected Attributes
constexpr static int AdjustedDim = Dimensions == 0 ? 1 : Dimensions
constexpr static access::address_space AS
constexpr static bool IsAccessAnyWrite
constexpr static bool IsAccessReadOnly
constexpr static bool IsConstantBuf
constexpr static bool IsGlobalBuf
constexpr static bool IsHostBuf
constexpr static bool IsPlaceH
Friends
class sycl::stream
class sycl::ext::intel::esimd::detail::AccessorPrivateProxy
Detailed Description
template<typename DataT, int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT>
class cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >
Buffer accessor.
See also
buffer
Definition at line 223 of file accessor.hpp.
Member Typedef Documentation
AccessorCommonT
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::AccessorCommonT = detail::accessor_common<DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT> protected
Definition at line 811 of file accessor.hpp.
AccessorSubscript
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims> using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::AccessorSubscript = typename AccessorCommonT::template AccessorSubscript<Dims> protected
Definition at line 824 of file accessor.hpp.
ConcreteASPtrType
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::ConcreteASPtrType = typename detail::DecoratedType<DataT, AS>::type * protected
Definition at line 826 of file accessor.hpp.
const_reference
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::const_reference = const DataT &
Definition at line 976 of file accessor.hpp.
ConstRefType
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::ConstRefType = const DataT & protected
Definition at line 829 of file accessor.hpp.
PtrType
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::PtrType = detail::const_if_const_AS<AS, DataT> * protected
Definition at line 830 of file accessor.hpp.
reference
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::reference = DataT &
Definition at line 975 of file accessor.hpp.
RefType
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::RefType = detail::const_if_const_AS<AS, DataT> & protected
Definition at line 828 of file accessor.hpp.
value_type
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > using cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::value_type = DataT
Definition at line 974 of file accessor.hpp.
Constructor & Destructor Documentation
accessor() [1/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename detail::enable_if_t< detail::IsRunTimePropertyListT< PropertyListT >::value &&std::is_same< T, DataT >::value &&Dims==0 &&((!IsPlaceH &&IsHostBuf)||(IsPlaceH &&(IsGlobalBuf||IsConstantBuf)))> * = nullptr> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, 1, AllocatorT > & BufferRef, const property_list & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1008 of file accessor.hpp.
accessor() [2/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename detail::enable_if_t< detail::IsCxPropertyList< PropertyListT >::value &&std::is_same< T, DataT >::value &&Dims==0 &&((!IsPlaceH &&IsHostBuf)||(IsPlaceH &&(IsGlobalBuf||IsConstantBuf)))> * = nullptr> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, 1, AllocatorT > & BufferRef, const ext::oneapi::accessor_property_list< PropTypes... > & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1038 of file accessor.hpp.
accessor() [3/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = typename detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && std::is_same<T, DataT>::value && (Dims == 0) && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, 1, AllocatorT > & BufferRef, handler & CommandGroupHandler, const property_list & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1067 of file accessor.hpp.
accessor() [4/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = typename detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && std::is_same<T, DataT>::value && (Dims == 0) && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, 1, AllocatorT > & BufferRef, handler & CommandGroupHandler, const ext::oneapi::accessor_property_list< PropTypes... > & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1097 of file accessor.hpp.
accessor() [5/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, const property_list & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1128 of file accessor.hpp.
accessor() [6/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, const ext::oneapi::accessor_property_list< PropTypes... > & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1160 of file accessor.hpp.
accessor() [7/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, handler & CommandGroupHandler, const property_list & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1223 of file accessor.hpp.
accessor() [8/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, handler & CommandGroupHandler, const ext::oneapi::accessor_property_list< PropTypes... > & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1254 of file accessor.hpp.
accessor() [9/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, range< Dimensions > AccessRange, const property_list & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1320 of file accessor.hpp.
accessor() [10/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, range< Dimensions > AccessRange, const ext::oneapi::accessor_property_list< PropTypes... > & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1333 of file accessor.hpp.
accessor() [11/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, handler & CommandGroupHandler, range< Dimensions > AccessRange, const property_list & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1378 of file accessor.hpp.
accessor() [12/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, handler & CommandGroupHandler, range< Dimensions > AccessRange, const ext::oneapi::accessor_property_list< PropTypes... > & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1391 of file accessor.hpp.
accessor() [13/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const property_list & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1442 of file accessor.hpp.
accessor() [14/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && ((!IsPlaceH && IsHostBuf) || (IsPlaceH && (IsGlobalBuf || IsConstantBuf)))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const ext::oneapi::accessor_property_list< PropTypes... > & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1481 of file accessor.hpp.
accessor() [15/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename = detail::enable_if_t< detail::IsRunTimePropertyListT<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, handler & CommandGroupHandler, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const property_list & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1553 of file accessor.hpp.
accessor() [16/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T = DataT, int Dims = Dimensions, typename AllocatorT , typename... PropTypes, typename = detail::enable_if_t< detail::IsCxPropertyList<PropertyListT>::value && IsSameAsBuffer<T, Dims>() && (!IsPlaceH && (IsGlobalBuf || IsConstantBuf || IsHostBuf))>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (buffer< T, Dims, AllocatorT > & BufferRef, handler & CommandGroupHandler, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const ext::oneapi::accessor_property_list< PropTypes... > & PropertyList = {}, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1592 of file accessor.hpp.
accessor() [17/17]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename... NewPropsT> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::accessor (const accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, ext::oneapi::accessor_property_list< NewPropsT... >> & Other, const detail::code_location CodeLoc = detail::code_location::current()) inline
Definition at line 1663 of file accessor.hpp.
Member Function Documentation
__SYCL2020_DEPRECATED()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::__SYCL2020_DEPRECATED ("get_count() is deprecated, please use size() instead") const inline
Definition at line 1688 of file accessor.hpp.
get_offset()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions, typename = detail::enable_if_t<(Dims > 0)>> id<Dimensions> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::get_offset () const inline
Definition at line 1698 of file accessor.hpp.
get_pointer() [1/3]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<access::target AccessTarget_ = AccessTarget, typename = detail::enable_if_t<AccessTarget_ == access::target::host_buffer>> DataT* cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::get_pointer () const inline
Definition at line 1777 of file accessor.hpp.
Referenced by cl::sycl::ext::oneapi::detail::reduction_impl< T, BinaryOperation, Dims, IsUSM, IsPlaceholder >::getOutPointer().
get_pointer() [2/3]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<access::target AccessTarget_ = AccessTarget, typename = detail::enable_if_t<AccessTarget_ == access::target::device>> global_ptr<DataT> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::get_pointer () const inline
Definition at line 1784 of file accessor.hpp.
get_pointer() [3/3]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<access::target AccessTarget_ = AccessTarget, typename = detail::enable_if_t<AccessTarget_ == access::target::constant_buffer>> constant_ptr<DataT> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::get_pointer () const inline
Definition at line 1791 of file accessor.hpp.
get_range()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions, typename = detail::enable_if_t<(Dims > 0)>> range<Dimensions> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::get_range () const inline
Definition at line 1693 of file accessor.hpp.
Referenced by cl::sycl::handler::fill(), and cl::sycl::detail::updateOffset().
get_size()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > size_t cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::get_size () const inline
Definition at line 1686 of file accessor.hpp.
Referenced by cl::sycl::handler::copy().
getAccessRange() [1/2]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > range<3>& cl::sycl::detail::AccessorBaseHost::getAccessRange inline protected
Definition at line 145 of file accessor_impl.hpp.
getAccessRange() [2/2]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > const range<3>& cl::sycl::detail::AccessorBaseHost::getAccessRange inline protected
Definition at line 151 of file accessor_impl.hpp.
getAdjustedMode()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > static access::mode cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::getAdjustedMode (const PropertyListT & PropertyList) inline static protected
Definition at line 861 of file accessor.hpp.
getLinearIndex()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions> size_t cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::getLinearIndex (id< Dims > Id) const inline protected
Definition at line 832 of file accessor.hpp.
getMemoryRange() [1/2]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > range<3>& cl::sycl::detail::AccessorBaseHost::getMemoryRange inline protected
Definition at line 146 of file accessor_impl.hpp.
getMemoryRange() [2/2]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > const range<3>& cl::sycl::detail::AccessorBaseHost::getMemoryRange inline protected
Definition at line 152 of file accessor_impl.hpp.
getOffset() [1/2]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > id<3>& cl::sycl::detail::AccessorBaseHost::getOffset inline protected
Definition at line 144 of file accessor_impl.hpp.
getOffset() [2/2]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > const id<3>& cl::sycl::detail::AccessorBaseHost::getOffset inline protected
Definition at line 150 of file accessor_impl.hpp.
getQualifiedPtr()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > PtrType cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::getQualifiedPtr () const inline protected
Definition at line 963 of file accessor.hpp.
is_placeholder()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr bool cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::is_placeholder () const inline constexpr
Definition at line 1684 of file accessor.hpp.
IsSameAsBuffer()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<typename T , int Dims> static constexpr bool cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::IsSameAsBuffer () inline static constexpr protected
Definition at line 857 of file accessor.hpp.
operator ConstRefType()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions, typename = detail::enable_if_t<Dims == 0 && IsAccessReadOnly>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator ConstRefType () const inline
Definition at line 1718 of file accessor.hpp.
operator RefType()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions, typename RefT = RefType, typename = detail::enable_if_t<Dims == 0 && IsAccessAnyWrite && !std::is_const<RefT>::value>> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator RefType () const inline
Definition at line 1711 of file accessor.hpp.
operator typename detail::enable_if_t< Dims==0 &&AccessMode==access::mode::atomic, atomic< DataT, AS > >()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator typename detail::enable_if_t< Dims==0 &&AccessMode==access::mode::atomic, atomic< DataT, AS > > () const inline
Definition at line 1745 of file accessor.hpp.
operator!=()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > bool cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator!= (const accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > & Rhs) const inline
Definition at line 1796 of file accessor.hpp.
operator==()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > bool cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator== (const accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > & Rhs) const inline
Definition at line 1795 of file accessor.hpp.
operator[]() [1/5]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions, typename = detail::enable_if_t<(Dims > 0) && IsAccessAnyWrite>> RefType cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator[] (id< Dimensions > Index) const inline
Definition at line 1725 of file accessor.hpp.
operator[]() [2/5]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions> detail::enable_if_t<(Dims > 0) && IsAccessReadOnly, ConstRefType> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator[] (id< Dimensions > Index) const inline
Definition at line 1732 of file accessor.hpp.
operator[]() [3/5]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions> detail::enable_if_t<(Dims > 0) && AccessMode == access::mode::atomic, atomic<DataT, AS> > cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator[] (id< Dimensions > Index) const inline
Definition at line 1754 of file accessor.hpp.
operator[]() [4/5]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions> detail::enable_if_t<Dims == 1 && AccessMode == access::mode::atomic, atomic<DataT, AS> > cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator[] (size_t Index) const inline
Definition at line 1763 of file accessor.hpp.
operator[]() [5/5]
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > template<int Dims = Dimensions, typename = detail::enable_if_t<(Dims > 1)>> AccessorCommonT::template AccessorSubscript<Dims - 1> cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::operator[] (size_t Index) const inline
Definition at line 1770 of file accessor.hpp.
size()
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > size_t cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::size () const inline noexcept
Definition at line 1690 of file accessor.hpp.
Referenced by cl::sycl::ext::oneapi::detail::reduction_impl< T, BinaryOperation, Dims, IsUSM, IsPlaceholder >::reduction_impl(), and cl::sycl::detail::write().
Friends And Related Function Documentation
sycl::ext::intel::esimd::detail::AccessorPrivateProxy
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > friend class sycl::ext::intel::esimd::detail::AccessorPrivateProxy friend
Definition at line 971 of file accessor.hpp.
sycl::stream
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > friend class sycl::stream friend
Definition at line 970 of file accessor.hpp.
Member Data Documentation
AdjustedDim
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr static int cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::AdjustedDim = Dimensions == 0 ? 1 : Dimensions static constexpr protected
Definition at line 813 of file accessor.hpp.
AS
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr static access::address_space cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::AS static constexpr protected
Definition at line 272 of file accessor.hpp.
IsAccessAnyWrite
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr static bool cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::IsAccessAnyWrite static constexpr protected
Definition at line 285 of file accessor.hpp.
IsAccessReadOnly
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr static bool cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::IsAccessReadOnly static constexpr protected
Definition at line 291 of file accessor.hpp.
IsConstantBuf
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr static bool cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::IsConstantBuf static constexpr protected
Definition at line 282 of file accessor.hpp.
IsGlobalBuf
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr static bool cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::IsGlobalBuf static constexpr protected
Definition at line 279 of file accessor.hpp.
IsHostBuf
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr static bool cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::IsHostBuf static constexpr protected
Definition at line 274 of file accessor.hpp.
IsPlaceH
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > constexpr static bool cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::IsPlaceH static constexpr protected
Definition at line 271 of file accessor.hpp.
padding
template<typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder, typename PropertyListT > char cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::padding[sizeof(detail::AccessorImplDevice< AdjustedDim >)+ sizeof(PtrType) - sizeof(detail::AccessorBaseHost)] protected
Definition at line 961 of file accessor.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/accessor.hpp