DPC++ Runtime: sycl::_V1::queue Class Reference
sycl::_V1::queue Class Reference
DPC++ User API
Encapsulates a single SYCL queue which schedules kernels on a SYCL device.
#include <sycl/queue.hpp>
Public Member Functions
queue (const property_list &PropList={})
Constructs a SYCL queue instance using the device returned by an instance of default_selector.
queue (const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL queue instance with an async_handler using the device returned by an instance of default_selector.
template<typename DeviceSelector , typename = detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>>
queue (const DeviceSelector &deviceSelector, const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL queue instance using the device identified by the device selector provided.
template<typename DeviceSelector , typename = detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>>
queue (const DeviceSelector &deviceSelector, const property_list &PropList={})
Constructs a SYCL queue instance using the device identified by the device selector provided.
template<typename DeviceSelector , typename = detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>>
queue (const context &syclContext, const DeviceSelector &deviceSelector, const property_list &propList={})
Constructs a SYCL queue instance using the device identified by the device selector provided.
template<typename DeviceSelector , typename = detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>>
queue (const context &syclContext, const DeviceSelector &deviceSelector, const async_handler &AsyncHandler, const property_list &propList={})
Constructs a SYCL queue instance using the device identified by the device selector provided.
__SYCL2020_DEPRECATED ("SYCL 1.2.1 device selectors are deprecated. Please " "use SYCL 2020 device selectors instead.") queue(const device_selector &DeviceSelector
Constructs a SYCL queue instance using the device returned by the DeviceSelector provided.
__SYCL2020_DEPRECATED ("SYCL 1.2.1 device selectors are deprecated. Please " "use SYCL 2020 device selectors instead.") queue(const context &SyclContext
Constructs a SYCL queue instance that is associated with the context provided, using the device returned by the device selector.
__SYCL2020_DEPRECATED ("SYCL 1.2.1 device selectors are deprecated. Please " "use SYCL 2020 device selectors instead.") queue(const context &SyclContext
Constructs a SYCL queue instance with an async_handler that is associated with the context provided, using the device returned by the device selector.
queue (const context &SyclContext, const device &SyclDevice, const property_list &PropList={})
Constructs a SYCL queue associated with the given context, device and optional properties list.
queue (const context &SyclContext, const device &SyclDevice, const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL queue associated with the given context, device, asynchronous exception handler and optional properties list.
queue (const queue &RHS)=default
Constructs a SYCL queue with an optional async_handler from an OpenCL cl_command_queue.
queue (queue &&RHS)=default
queue & operator= (const queue &RHS)=default
queue & operator= (queue &&RHS)=default
bool operator== (const queue &RHS) const
bool operator!= (const queue &RHS) const
context get_context () const
device get_device () const
ext::oneapi::experimental::queue_state ext_oneapi_get_state () const
ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::modifiable > ext_oneapi_get_graph () const
__SYCL2020_DEPRECATED ("is_host() is deprecated as the host device is no longer supported.") bool is_host() const
template<typename Param >
detail::is_queue_info_desc< Param >::return_type get_info () const
Queries SYCL queue for information.
template<typename Param >
detail::is_backend_info_desc< Param >::return_type get_backend_info () const
Queries SYCL queue for SYCL backend-specific information.
template<typename T >
std::enable_if_t< std::is_invocable_r_v< void, T, handler & >, event > submit (T CGF, const detail::code_location &CodeLoc=detail::code_location::current())
Submits a command group function object to the queue, in order to be scheduled for execution on the device.
template<typename T >
std::enable_if_t< std::is_invocable_r_v< void, T, handler & >, event > submit (T CGF, queue &SecondaryQueue, const detail::code_location &CodeLoc=detail::code_location::current())
Submits a command group function object to the queue, in order to be scheduled for execution on the device.
event ext_oneapi_submit_barrier (const detail::code_location &CodeLoc=detail::code_location::current())
Prevents any commands submitted afterward to this queue from executing until all commands previously submitted to this queue have entered the complete state.
event ext_oneapi_submit_barrier (const std::vector< event > &WaitList, const detail::code_location &CodeLoc=detail::code_location::current())
Prevents any commands submitted afterward to this queue from executing until all events in WaitList have entered the complete state.
void wait (const detail::code_location &CodeLoc=detail::code_location::current())
Performs a blocking wait for the completion of all enqueued tasks in the queue.
void wait_and_throw (const detail::code_location &CodeLoc=detail::code_location::current())
Performs a blocking wait for the completion of all enqueued tasks in the queue.
void wait_proxy (const detail::code_location &CodeLoc)
Proxy method for wait to forward the code location information to the implementation.
void wait_and_throw_proxy (const detail::code_location &CodeLoc)
Proxy method for wait_and_throw to forward the code location information to the implementation.
void throw_asynchronous ()
Checks if any asynchronous errors have been produced by the queue and if so reports them to the async_handler passed on the queue construction.
template<typename PropertyT >
bool has_property () const noexcept
template<typename PropertyT >
PropertyT get_property () const
template<typename T >
event fill (void *Ptr, const T &Pattern, size_t Count, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the specified memory with the specified pattern.
template<typename T >
event fill (void *Ptr, const T &Pattern, size_t Count, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the specified memory with the specified pattern.
template<typename T >
event fill (void *Ptr, const T &Pattern, size_t Count, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the specified memory with the specified pattern.
event memset (void *Ptr, int Value, size_t Count, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
event memset (void *Ptr, int Value, size_t Count, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
event memset (void *Ptr, int Value, size_t Count, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
event memcpy (void *Dest, const void *Src, size_t Count, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
event memcpy (void *Dest, const void *Src, size_t Count, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
event memcpy (void *Dest, const void *Src, size_t Count, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
template<typename T >
event copy (const T *Src, T *Dest, size_t Count, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
template<typename T >
event copy (const T *Src, T *Dest, size_t Count, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
template<typename T >
event copy (const T *Src, T *Dest, size_t Count, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
event mem_advise (const void *Ptr, size_t Length, pi_mem_advice Advice, const detail::code_location &CodeLoc=detail::code_location::current())
Provides additional information to the underlying runtime about how different allocations are used.
event mem_advise (const void *Ptr, size_t Length, int Advice, const detail::code_location &CodeLoc=detail::code_location::current())
Provides additional information to the underlying runtime about how different allocations are used.
event mem_advise (const void *Ptr, size_t Length, int Advice, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Provides additional information to the underlying runtime about how different allocations are used.
event mem_advise (const void *Ptr, size_t Length, int Advice, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Provides additional information to the underlying runtime about how different allocations are used.
event prefetch (const void *Ptr, size_t Count, const detail::code_location &CodeLoc=detail::code_location::current())
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
event prefetch (const void *Ptr, size_t Count, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
event prefetch (const void *Ptr, size_t Count, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>>
event ext_oneapi_memcpy2d (void *Dest, size_t DestPitch, const void *Src, size_t SrcPitch, size_t Width, size_t Height, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>>
event ext_oneapi_memcpy2d (void *Dest, size_t DestPitch, const void *Src, size_t SrcPitch, size_t Width, size_t Height, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>>
event ext_oneapi_memcpy2d (void *Dest, size_t DestPitch, const void *Src, size_t SrcPitch, size_t Width, size_t Height, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
template<typename T >
event ext_oneapi_copy2d (const T *Src, size_t SrcPitch, T *Dest, size_t DestPitch, size_t Width, size_t Height, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
template<typename T >
event ext_oneapi_copy2d (const T *Src, size_t SrcPitch, T *Dest, size_t DestPitch, size_t Width, size_t Height, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
template<typename T >
event ext_oneapi_copy2d (const T *Src, size_t SrcPitch, T *Dest, size_t DestPitch, size_t Width, size_t Height, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>>
event ext_oneapi_memset2d (void *Dest, size_t DestPitch, int Value, size_t Width, size_t Height, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>>
event ext_oneapi_memset2d (void *Dest, size_t DestPitch, int Value, size_t Width, size_t Height, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>>
event ext_oneapi_memset2d (void *Dest, size_t DestPitch, int Value, size_t Width, size_t Height, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
template<typename T >
event ext_oneapi_fill2d (void *Dest, size_t DestPitch, const T &Pattern, size_t Width, size_t Height, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
template<typename T >
event ext_oneapi_fill2d (void *Dest, size_t DestPitch, const T &Pattern, size_t Width, size_t Height, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
template<typename T >
event ext_oneapi_fill2d (void *Dest, size_t DestPitch, const T &Pattern, size_t Width, size_t Height, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
template<typename T , typename PropertyListT >
event memcpy (ext::oneapi::experimental::device_global< T, PropertyListT > &Dest, const void *Src, size_t NumBytes, size_t Offset, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a USM memory region to a device_global.
template<typename T , typename PropertyListT >
event memcpy (ext::oneapi::experimental::device_global< T, PropertyListT > &Dest, const void *Src, size_t NumBytes, size_t Offset, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a USM memory region to a device_global.
template<typename T , typename PropertyListT >
event memcpy (ext::oneapi::experimental::device_global< T, PropertyListT > &Dest, const void *Src, size_t NumBytes=sizeof(T), size_t Offset=0, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a USM memory region to a device_global.
template<typename T , typename PropertyListT >
event memcpy (void *Dest, const ext::oneapi::experimental::device_global< T, PropertyListT > &Src, size_t NumBytes, size_t Offset, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a device_global to USM memory.
template<typename T , typename PropertyListT >
event memcpy (void *Dest, const ext::oneapi::experimental::device_global< T, PropertyListT > &Src, size_t NumBytes, size_t Offset, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a device_global to USM memory.
template<typename T , typename PropertyListT >
event memcpy (void *Dest, const ext::oneapi::experimental::device_global< T, PropertyListT > &Src, size_t NumBytes=sizeof(T), size_t Offset=0, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a device_global to USM memory.
template<typename T , typename PropertyListT >
event copy (const std::remove_all_extents_t< T > *Src, ext::oneapi::experimental::device_global< T, PropertyListT > &Dest, size_t Count, size_t StartIndex, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies elements of type std::remove_all_extents_t<T> from a USM memory region to a device_global.
template<typename T , typename PropertyListT >
event copy (const std::remove_all_extents_t< T > *Src, ext::oneapi::experimental::device_global< T, PropertyListT > &Dest, size_t Count, size_t StartIndex, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies elements of type std::remove_all_extents_t<T> from a USM memory region to a device_global.
template<typename T , typename PropertyListT >
event copy (const std::remove_all_extents_t< T > *Src, ext::oneapi::experimental::device_global< T, PropertyListT > &Dest, size_t Count=sizeof(T)/sizeof(std::remove_all_extents_t< T >), size_t StartIndex=0, const detail::code_location &CodeLoc=detail::code_location::current())
Copies elements of type std::remove_all_extents_t<T> from a USM memory region to a device_global.
template<typename T , typename PropertyListT >
event copy (const ext::oneapi::experimental::device_global< T, PropertyListT > &Src, std::remove_all_extents_t< T > *Dest, size_t Count, size_t StartIndex, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies elements of type std::remove_all_extents_t<T> from a device_global to a USM memory region.
template<typename T , typename PropertyListT >
event copy (const ext::oneapi::experimental::device_global< T, PropertyListT > &Src, std::remove_all_extents_t< T > *Dest, size_t Count, size_t StartIndex, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies elements of type std::remove_all_extents_t<T> from a device_global to a USM memory region.
template<typename T , typename PropertyListT >
event copy (const ext::oneapi::experimental::device_global< T, PropertyListT > &Src, std::remove_all_extents_t< T > *Dest, size_t Count=sizeof(T)/sizeof(std::remove_all_extents_t< T >), size_t StartIndex=0, const detail::code_location &CodeLoc=detail::code_location::current())
Copies elements of type std::remove_all_extents_t<T> from a device_global to a USM memory region.
event ext_oneapi_copy (void *Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor &DestImgDesc, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle wrapper.
event ext_oneapi_copy (void *Src, sycl::range< 3 > SrcOffset, sycl::range< 3 > SrcExtent, ext::oneapi::experimental::image_mem_handle Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor &DestImgDesc, sycl::range< 3 > CopyExtent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
event ext_oneapi_copy (void *Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor &DestImgDesc, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle wrapper.
event ext_oneapi_copy (void *Src, sycl::range< 3 > SrcOffset, sycl::range< 3 > SrcExtent, ext::oneapi::experimental::image_mem_handle Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor &DestImgDesc, sycl::range< 3 > CopyExtent, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
event ext_oneapi_copy (void *Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor &DestImgDesc, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle wrapper.
event ext_oneapi_copy (void *Src, sycl::range< 3 > SrcOffset, sycl::range< 3 > SrcExtent, ext::oneapi::experimental::image_mem_handle Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor &DestImgDesc, sycl::range< 3 > CopyExtent, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, void *Dest, const ext::oneapi::experimental::image_descriptor &SrcImgDesc, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, sycl::range< 3 > SrcOffset, const ext::oneapi::experimental::image_descriptor &SrcImgDesc, void *Dest, sycl::range< 3 > DestOffset, sycl::range< 3 > DestExtent, sycl::range< 3 > CopyExtent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, void *Dest, const ext::oneapi::experimental::image_descriptor &SrcImgDesc, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, sycl::range< 3 > SrcOffset, const ext::oneapi::experimental::image_descriptor &SrcImgDesc, void *Dest, sycl::range< 3 > DestOffset, sycl::range< 3 > DestExtent, sycl::range< 3 > CopyExtent, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, void *Dest, const ext::oneapi::experimental::image_descriptor &SrcImgDesc, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, sycl::range< 3 > SrcOffset, const ext::oneapi::experimental::image_descriptor &SrcImgDesc, void *Dest, sycl::range< 3 > DestOffset, sycl::range< 3 > DestExtent, sycl::range< 3 > CopyExtent, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
event ext_oneapi_copy (void *Src, void *Dest, const ext::oneapi::experimental::image_descriptor &DeviceImgDesc, size_t DeviceRowPitch, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src and Dest are USM pointers.
event ext_oneapi_copy (void *Src, sycl::range< 3 > SrcOffset, void *Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor &DeviceImgDesc, size_t DeviceRowPitch, sycl::range< 3 > HostExtent, sycl::range< 3 > CopyExtent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src and Dest are USM pointers.
event ext_oneapi_copy (void *Src, void *Dest, const ext::oneapi::experimental::image_descriptor &DeviceImgDesc, size_t DeviceRowPitch, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src and Dest are USM pointers.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor &ImageDesc, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from device to device memory, where Src and Dest are opaque image memory handles.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor &ImageDesc, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from device to device memory, where Src and Dest are opaque image memory handles.
event ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor &ImageDesc, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from device to device memory, where Src and Dest are opaque image memory handles.
event ext_oneapi_copy (void *Src, sycl::range< 3 > SrcOffset, void *Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor &DeviceImgDesc, size_t DeviceRowPitch, sycl::range< 3 > HostExtent, sycl::range< 3 > CopyExtent, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src and Dest are USM pointers.
event ext_oneapi_copy (void *Src, void *Dest, const ext::oneapi::experimental::image_descriptor &DeviceImgDesc, size_t DeviceRowPitch, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src and Dest are USM pointers.
event ext_oneapi_copy (void *Src, sycl::range< 3 > SrcOffset, void *Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor &DeviceImgDesc, size_t DeviceRowPitch, sycl::range< 3 > HostExtent, sycl::range< 3 > CopyExtent, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, where Src and Dest are USM pointers.
event ext_oneapi_wait_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, const detail::code_location &CodeLoc=detail::code_location::current())
Instruct the queue with a non-blocking wait on an external semaphore.
event ext_oneapi_wait_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Instruct the queue with a non-blocking wait on an external semaphore.
event ext_oneapi_wait_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Instruct the queue with a non-blocking wait on an external semaphore.
event ext_oneapi_signal_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, const detail::code_location &CodeLoc=detail::code_location::current())
Instruct the queue to signal the external semaphore once all previous commands have completed execution.
event ext_oneapi_signal_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Instruct the queue to signal the external semaphore once all previous commands have completed execution.
event ext_oneapi_signal_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Instruct the queue to signal the external semaphore once all previous commands have completed execution.
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT >
std::enable_if_t< ext::oneapi::experimental::is_property_list< PropertiesT >::value, event > single_task (PropertiesT Properties, _KERNELFUNCPARAM(KernelFunc), const detail::code_location &CodeLoc=detail::code_location::current())
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename KernelType >
event single_task (_KERNELFUNCPARAM(KernelFunc), const detail::code_location &CodeLoc=detail::code_location::current())
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT >
std::enable_if_t< ext::oneapi::experimental::is_property_list< PropertiesT >::value, event > single_task (event DepEvent, PropertiesT Properties, _KERNELFUNCPARAM(KernelFunc), const detail::code_location &CodeLoc=detail::code_location::current())
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename KernelType >
event single_task (event DepEvent, _KERNELFUNCPARAM(KernelFunc), const detail::code_location &CodeLoc=detail::code_location::current())
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT >
std::enable_if_t< ext::oneapi::experimental::is_property_list< PropertiesT >::value, event > single_task (const std::vector< event > &DepEvents, PropertiesT Properties, _KERNELFUNCPARAM(KernelFunc), const detail::code_location &CodeLoc=detail::code_location::current())
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename KernelType >
event single_task (const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc), const detail::code_location &CodeLoc=detail::code_location::current())
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 1 > Range, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 2 > Range, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 3 > Range, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 1 > Range, event DepEvent, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 2 > Range, event DepEvent, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 3 > Range, event DepEvent, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 1 > Range, const std::vector< event > &DepEvents, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 2 > Range, const std::vector< event > &DepEvents, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename... RestT>
event parallel_for (range< 3 > Range, const std::vector< event > &DepEvents, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType , int Dim>
event parallel_for (range< Dim > Range, id< Dim > WorkItemOffset, const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc))
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for_impl (range< Dims > Range, id< Dims > WorkItemOffset, _KERNELFUNCPARAM(KernelFunc))
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for_impl (range< Dims > Range, id< Dims > WorkItemOffset, event DepEvent, _KERNELFUNCPARAM(KernelFunc))
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for_impl (range< Dims > Range, id< Dims > WorkItemOffset, const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc))
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
template<typename KernelName = detail::auto_name, int Dims, typename PropertiesT , typename... RestT>
std::enable_if_t< detail::AreAllButLastReductions< RestT... >::value &&ext::oneapi::experimental::is_property_list< PropertiesT >::value, event > parallel_for (nd_range< Dims > Range, PropertiesT Properties, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
template<typename KernelName = detail::auto_name, int Dims, typename... RestT>
std::enable_if_t< detail::AreAllButLastReductions< RestT... >::value, event > parallel_for (nd_range< Dims > Range, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
template<typename KernelName = detail::auto_name, int Dims, typename... RestT>
event parallel_for (nd_range< Dims > Range, event DepEvent, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
template<typename KernelName = detail::auto_name, int Dims, typename... RestT>
event parallel_for (nd_range< Dims > Range, const std::vector< event > &DepEvents, RestT &&...Rest)
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
template<typename SrcT , int SrcDims, access_mode SrcMode, target SrcTgt, access::placeholder IsPlaceholder, typename DestT >
event copy (accessor< SrcT, SrcDims, SrcMode, SrcTgt, IsPlaceholder > Src, std::shared_ptr< DestT > Dest, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a memory region pointed to by a placeholder accessor to another memory region pointed to by a shared_ptr.
template<typename SrcT , typename DestT , int DestDims, access_mode DestMode, target DestTgt, access::placeholder IsPlaceholder>
event copy (std::shared_ptr< SrcT > Src, accessor< DestT, DestDims, DestMode, DestTgt, IsPlaceholder > Dest, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a memory region pointed to by a shared_ptr to another memory region pointed to by a placeholder accessor.
template<typename SrcT , int SrcDims, access_mode SrcMode, target SrcTgt, access::placeholder IsPlaceholder, typename DestT >
event copy (accessor< SrcT, SrcDims, SrcMode, SrcTgt, IsPlaceholder > Src, DestT *Dest, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a memory region pointed to by a placeholder accessor to another memory region pointed to by a raw pointer.
template<typename SrcT , typename DestT , int DestDims, access_mode DestMode, target DestTgt, access::placeholder IsPlaceholder>
event copy (const SrcT *Src, accessor< DestT, DestDims, DestMode, DestTgt, IsPlaceholder > Dest, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from a memory region pointed to by a raw pointer to another memory region pointed to by a placeholder accessor.
template<typename SrcT , int SrcDims, access_mode SrcMode, target SrcTgt, access::placeholder IsSrcPlaceholder, typename DestT , int DestDims, access_mode DestMode, target DestTgt, access::placeholder IsDestPlaceholder>
event copy (accessor< SrcT, SrcDims, SrcMode, SrcTgt, IsSrcPlaceholder > Src, accessor< DestT, DestDims, DestMode, DestTgt, IsDestPlaceholder > Dest, const detail::code_location &CodeLoc=detail::code_location::current())
Copies data from one memory region to another, both pointed by placeholder accessors.
template<typename T , int Dims, access_mode Mode, target Tgt, access::placeholder IsPlaceholder>
event update_host (accessor< T, Dims, Mode, Tgt, IsPlaceholder > Acc, const detail::code_location &CodeLoc=detail::code_location::current())
Provides guarantees that the memory object accessed via Acc is updated on the host after operation is complete.
template<typename T , int Dims, access_mode Mode, target Tgt, access::placeholder IsPlaceholder>
event fill (accessor< T, Dims, Mode, Tgt, IsPlaceholder > Dest, const T &Src, const detail::code_location &CodeLoc=detail::code_location::current())
Fills the specified memory with the specified data.
bool ext_codeplay_supports_fusion () const
Returns true if the queue was created with the ext::codeplay::experimental::property::queue::enable_fusion property.
event ext_oneapi_graph (ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::executable > Graph, const detail::code_location &CodeLoc=detail::code_location::current())
Shortcut for executing a graph of commands.
event ext_oneapi_graph (ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::executable > Graph, event DepEvent, const detail::code_location &CodeLoc=detail::code_location::current())
Shortcut for executing a graph of commands with a single dependency.
event ext_oneapi_graph (ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::executable > Graph, const std::vector< event > &DepEvents, const detail::code_location &CodeLoc=detail::code_location::current())
Shortcut for executing a graph of commands with multiple dependencies.
bool is_in_order () const
Returns whether the queue is in order or OoO.
backend get_backend () const noexcept
Returns the backend associated with this queue.
bool ext_oneapi_empty () const
Allows to check status of the queue (completed vs noncompleted).
pi_native_handle getNative (int32_t &NativeHandleDesc) const
event ext_oneapi_get_last_event () const
void ext_oneapi_set_external_event (const event &external_event)
Public Member Functions inherited from sycl::_V1::detail::OwnerLessBase< queue >
bool ext_oneapi_owner_before (const ext::oneapi::detail::weak_object_base< queue > &Other) const noexcept
Compares the object against a weak object using an owner-based implementation-defined ordering.
bool ext_oneapi_owner_before (const queue &Other) const noexcept
Compares the object against another object using an owner-based implementation-defined ordering.
Public Attributes
const property_list & PropList
const device_selector & DeviceSelector
const device_selector const property_list & PropList = {})
const device_selector const async_handler & AsyncHandler
const device_selector const async_handler const property_list & PropList = {})
Friends
template<class T >
T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
template<backend BackendName, class SyclObjectT >
auto get_native (const SyclObjectT &Obj) -> backend_return_t< BackendName, SyclObjectT >
Detailed Description
Encapsulates a single SYCL queue which schedules kernels on a SYCL device.
A SYCL queue can be used to submit command groups to be executed by the SYCL runtime.
See also
device
handler
event
kernel
Definition at line 105 of file queue.hpp.
Constructor & Destructor Documentation
queue() [1/10]
sycl::_V1::queue::queue (const property_list & PropList = {}) inline explicit
Constructs a SYCL queue instance using the device returned by an instance of default_selector.
Parameters
PropList is a list of properties for queue construction.
Definition at line 111 of file queue.hpp.
queue() [2/10]
sycl::_V1::queue::queue (const async_handler & AsyncHandler, const property_list & PropList = {}) inline
Constructs a SYCL queue instance with an async_handler using the device returned by an instance of default_selector.
Parameters
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 119 of file queue.hpp.
queue() [3/10]
template<typename DeviceSelector , typename = detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>> sycl::_V1::queue::queue (const DeviceSelector & deviceSelector, const async_handler & AsyncHandler, const property_list & PropList = {}) inline explicit
Constructs a SYCL queue instance using the device identified by the device selector provided.
Parameters
DeviceSelector is SYCL 2020 Device Selector, a simple callable that takes a device and returns an int
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 131 of file queue.hpp.
queue() [4/10]
template<typename DeviceSelector , typename = detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>> sycl::_V1::queue::queue (const DeviceSelector & deviceSelector, const property_list & PropList = {}) inline explicit
Constructs a SYCL queue instance using the device identified by the device selector provided.
Parameters
DeviceSelector is SYCL 2020 Device Selector, a simple callable that takes a device and returns an int
PropList is a list of properties for queue construction.
Definition at line 144 of file queue.hpp.
queue() [5/10]
template<typename DeviceSelector , typename = detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>> sycl::_V1::queue::queue (const context & syclContext, const DeviceSelector & deviceSelector, const property_list & propList = {}) inline explicit
Constructs a SYCL queue instance using the device identified by the device selector provided.
Parameters
SyclContext is an instance of SYCL context.
DeviceSelector is SYCL 2020 Device Selector, a simple callable that takes a device and returns an int
PropList is a list of properties for queue construction.
Definition at line 158 of file queue.hpp.
queue() [6/10]
template<typename DeviceSelector , typename = detail::EnableIfSYCL2020DeviceSelectorInvocable<DeviceSelector>> sycl::_V1::queue::queue (const context & syclContext, const DeviceSelector & deviceSelector, const async_handler & AsyncHandler, const property_list & propList = {}) inline explicit
Constructs a SYCL queue instance using the device identified by the device selector provided.
Parameters
SyclContext is an instance of SYCL context.
DeviceSelector is SYCL 2020 Device Selector, a simple callable that takes a device and returns an int
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 174 of file queue.hpp.
queue() [7/10]
sycl::_V1::queue::queue (const context & SyclContext, const device & SyclDevice, const property_list & PropList = {})
Constructs a SYCL queue associated with the given context, device and optional properties list.
Parameters
SyclContext is an instance of SYCL context.
SyclDevice is an instance of SYCL device.
PropList is a list of properties for queue construction.
Definition at line 58 of file queue.cpp.
queue() [8/10]
sycl::_V1::queue::queue (const context & SyclContext, const device & SyclDevice, const async_handler & AsyncHandler, const property_list & PropList = {})
Constructs a SYCL queue associated with the given context, device, asynchronous exception handler and optional properties list.
Parameters
SyclContext is an instance of SYCL context.
SyclDevice is an instance of SYCL device.
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 39 of file queue.cpp.
References AsyncHandler, sycl::_V1::detail::getSyclObjImpl(), and PropList.
queue() [9/10]
sycl::_V1::queue::queue (const queue & RHS) default
Constructs a SYCL queue with an optional async_handler from an OpenCL cl_command_queue.
The instance of cl_command_queue is retained on construction.
Parameters
ClQueue is a valid instance of OpenCL queue.
SyclContext is a valid SYCL context.
AsyncHandler is a SYCL asynchronous exception handler.
queue() [10/10]
sycl::_V1::queue::queue (queue && RHS) default
Member Function Documentation
__SYCL2020_DEPRECATED() [1/4]
sycl::_V1::queue::__SYCL2020_DEPRECATED ("is_host() is deprecated as the host device is no longer supported.") const
Returns
true if this queue is a SYCL host queue.
__SYCL2020_DEPRECATED() [2/4]
sycl::_V1::queue::__SYCL2020_DEPRECATED ("SYCL 1.2.1 device selectors are deprecated. Please " "use SYCL 2020 device selectors instead.") const &
Constructs a SYCL queue instance that is associated with the context provided, using the device returned by the device selector.
Parameters
SyclContext is an instance of SYCL context.
DeviceSelector is an instance of SYCL device selector.
PropList is a list of properties for queue construction.
__SYCL2020_DEPRECATED() [3/4]
sycl::_V1::queue::__SYCL2020_DEPRECATED ("SYCL 1.2.1 device selectors are deprecated. Please " "use SYCL 2020 device selectors instead.") const &
Constructs a SYCL queue instance with an async_handler that is associated with the context provided, using the device returned by the device selector.
Parameters
SyclContext is an instance of SYCL context.
DeviceSelector is an instance of SYCL device selector.
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
__SYCL2020_DEPRECATED() [4/4]
sycl::_V1::queue::__SYCL2020_DEPRECATED ("SYCL 1.2.1 device selectors are deprecated. Please " "use SYCL 2020 device selectors instead.") const &
Constructs a SYCL queue instance using the device returned by the DeviceSelector provided.
Parameters
DeviceSelector is an instance of a SYCL 1.2.1 device_selector.
PropList is a list of properties for queue construction.
copy() [1/14]
template<typename SrcT , int SrcDims, access_mode SrcMode, target SrcTgt, access::placeholder IsPlaceholder, typename DestT > event sycl::_V1::queue::copy (accessor< SrcT, SrcDims, SrcMode, SrcTgt, IsPlaceholder > Src, DestT * Dest, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a memory region pointed to by a placeholder accessor to another memory region pointed to by a raw pointer.
Parameters
Src is a placeholder accessor to the source memory.
Dest is a raw pointer to the destination memory.
Returns
an event representing copy operation.
Definition at line 2433 of file queue.hpp.
References sycl::_V1::handler::copy(), sycl::_V1::handler::require(), and sycl::_V1::ext::oneapi::experimental::submit().
copy() [2/14]
template<typename SrcT , int SrcDims, access_mode SrcMode, target SrcTgt, access::placeholder IsPlaceholder, typename DestT > event sycl::_V1::queue::copy (accessor< SrcT, SrcDims, SrcMode, SrcTgt, IsPlaceholder > Src, std::shared_ptr< DestT > Dest, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a memory region pointed to by a placeholder accessor to another memory region pointed to by a shared_ptr.
Parameters
Src is a placeholder accessor to the source memory.
Dest is a shared_ptr to the destination memory.
Returns
an event representing copy operation.
Definition at line 2393 of file queue.hpp.
References sycl::_V1::handler::copy(), sycl::_V1::handler::require(), and sycl::_V1::ext::oneapi::experimental::submit().
copy() [3/14]
template<typename SrcT , int SrcDims, access_mode SrcMode, target SrcTgt, access::placeholder IsSrcPlaceholder, typename DestT , int DestDims, access_mode DestMode, target DestTgt, access::placeholder IsDestPlaceholder> event sycl::_V1::queue::copy (accessor< SrcT, SrcDims, SrcMode, SrcTgt, IsSrcPlaceholder > Src, accessor< DestT, DestDims, DestMode, DestTgt, IsDestPlaceholder > Dest, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, both pointed by placeholder accessors.
Parameters
Src is a placeholder accessor to the source memory.
Dest is a placeholder accessor to the destination memory.
Returns
an event representing copy operation.
Definition at line 2474 of file queue.hpp.
References sycl::_V1::handler::copy(), sycl::_V1::handler::require(), and sycl::_V1::ext::oneapi::experimental::submit().
copy() [4/14]
template<typename T , typename PropertyListT > event sycl::_V1::queue::copy (const ext::oneapi::experimental::device_global< T, PropertyListT > & Src, std::remove_all_extents_t< T > * Dest, size_t Count, size_t StartIndex, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies elements of type std::remove_all_extents_t<T> from a device_global to a USM memory region.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Src,as specified through
Count and
StartIndex.
Src is the source device_global.
Dest is a USM pointer to copy to.
Count is a number of elements to copy.
StartIndex is the index of the first element in Src to copy from.
DepEvents is a vector of events that specifies the operation dependencies.
Returns
an event representing copy operation.
Definition at line 1320 of file queue.hpp.
copy() [5/14]
template<typename T , typename PropertyListT > event sycl::_V1::queue::copy (const ext::oneapi::experimental::device_global< T, PropertyListT > & Src, std::remove_all_extents_t< T > * Dest, size_t Count, size_t StartIndex, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies elements of type std::remove_all_extents_t<T> from a device_global to a USM memory region.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Src,as specified through
Count and
StartIndex.
Src is the source device_global.
Dest is a USM pointer to copy to.
Count is a number of elements to copy.
StartIndex is the index of the first element in Src to copy from.
DepEvent is a vector of event that specifies the operation dependency.
Returns
an event representing copy operation.
Definition at line 1345 of file queue.hpp.
copy() [6/14]
template<typename T , typename PropertyListT > event sycl::_V1::queue::copy (const ext::oneapi::experimental::device_global< T, PropertyListT > & Src, std::remove_all_extents_t< T > * Dest, size_t Count = sizeof(T) / sizeof(std::remove_all_extents_t<T>), size_t StartIndex = 0, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies elements of type std::remove_all_extents_t<T> from a device_global to a USM memory region.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Src,as specified through
Count and
StartIndex.
Src is the source device_global.
Dest is a USM pointer to copy to.
Count is a number of elements to copy.
StartIndex is the index of the first element in Src to copy from.
Returns
an event representing copy operation.
Definition at line 1368 of file queue.hpp.
copy() [7/14]
template<typename SrcT , typename DestT , int DestDims, access_mode DestMode, target DestTgt, access::placeholder IsPlaceholder> event sycl::_V1::queue::copy (const SrcT * Src, accessor< DestT, DestDims, DestMode, DestTgt, IsPlaceholder > Dest, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a memory region pointed to by a raw pointer to another memory region pointed to by a placeholder accessor.
Parameters
Src is a raw pointer to the source memory.
Dest is a placeholder accessor to the destination memory.
Returns
an event representing copy operation.
Definition at line 2452 of file queue.hpp.
References sycl::_V1::handler::copy(), sycl::_V1::handler::require(), and sycl::_V1::ext::oneapi::experimental::submit().
copy() [8/14]
template<typename T , typename PropertyListT > event sycl::_V1::queue::copy (const std::remove_all_extents_t< T > * Src, ext::oneapi::experimental::device_global< T, PropertyListT > & Dest, size_t Count, size_t StartIndex, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies elements of type std::remove_all_extents_t<T> from a USM memory region to a device_global.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Dest,as specified through
Count and
StartIndex.
Src is a USM pointer to the source memory.
Dest is the destination device_glboal.
Count is a number of elements to copy.
StartIndex is the index of the first element in Dest to copy to.
DepEvents is a vector of events that specifies the operation dependencies.
Returns
an event representing copy operation.
Definition at line 1247 of file queue.hpp.
copy() [9/14]
template<typename T , typename PropertyListT > event sycl::_V1::queue::copy (const std::remove_all_extents_t< T > * Src, ext::oneapi::experimental::device_global< T, PropertyListT > & Dest, size_t Count, size_t StartIndex, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies elements of type std::remove_all_extents_t<T> from a USM memory region to a device_global.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Dest,as specified through
Count and
StartIndex.
Src is a USM pointer to the source memory.
Dest is the destination device_glboal.
Count is a number of elements to copy.
StartIndex is the index of the first element in Dest to copy to.
DepEvent is a vector of event that specifies the operation dependency.
Returns
an event representing copy operation.
Definition at line 1272 of file queue.hpp.
copy() [10/14]
template<typename T , typename PropertyListT > event sycl::_V1::queue::copy (const std::remove_all_extents_t< T > * Src, ext::oneapi::experimental::device_global< T, PropertyListT > & Dest, size_t Count = sizeof(T) / sizeof(std::remove_all_extents_t<T>), size_t StartIndex = 0, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies elements of type std::remove_all_extents_t<T> from a USM memory region to a device_global.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Dest,as specified through
Count and
StartIndex.
Src is a USM pointer to the source memory.
Dest is the destination device_glboal.
Count is a number of elements to copy.
StartIndex is the index of the first element in Dest to copy to.
Returns
an event representing copy operation.
Definition at line 1295 of file queue.hpp.
copy() [11/14]
template<typename T > event sycl::_V1::queue::copy (const T * Src, T * Dest, size_t Count, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
Count is a number of elements of type T to copy.
CodeLoc contains the code location of user code
Returns
an event representing copy operation.
Definition at line 636 of file queue.hpp.
copy() [12/14]
template<typename T > event sycl::_V1::queue::copy (const T * Src, T * Dest, size_t Count, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
Count is a number of elements of type T to copy.
DepEvents is a vector of events that specifies the kernel
CodeLoc contains the code location of user code
Returns
an event representing copy operation.
Definition at line 678 of file queue.hpp.
copy() [13/14]
template<typename T > event sycl::_V1::queue::copy (const T * Src, T * Dest, size_t Count, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
Count is a number of elements of type T to copy.
DepEvent is an event that specifies the kernel dependencies.
CodeLoc contains the code location of user code
Returns
an event representing copy operation.
Definition at line 657 of file queue.hpp.
copy() [14/14]
template<typename SrcT , typename DestT , int DestDims, access_mode DestMode, target DestTgt, access::placeholder IsPlaceholder> event sycl::_V1::queue::copy (std::shared_ptr< SrcT > Src, accessor< DestT, DestDims, DestMode, DestTgt, IsPlaceholder > Dest, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a memory region pointed to by a shared_ptr to another memory region pointed to by a placeholder accessor.
Parameters
Src is a shared_ptr to the source memory.
Dest is a placeholder accessor to the destination memory.
Returns
an event representing copy operation.
Definition at line 2413 of file queue.hpp.
References sycl::_V1::handler::copy(), sycl::_V1::handler::require(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_codeplay_supports_fusion()
bool sycl::_V1::queue::ext_codeplay_supports_fusion () const
Returns true if the queue was created with the ext::codeplay::experimental::property::queue::enable_fusion property.
Equivalent to has_property<ext::codeplay::experimental::property::queue::enable_fusion>().
Definition at line 353 of file queue.cpp.
Referenced by sycl::_V1::ext::codeplay::experimental::fusion_wrapper::fusion_wrapper().
ext_oneapi_copy() [1/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor & ImageDesc, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from device to device memory, where Src and Dest are opaque image memory handles.
An exception is thrown if either Src or Dest is incomplete
Parameters
Src is an opaque image memory handle to the source memory.
Dest is an opaque image memory handle to the destination memory.
ImageDesc is the source image descriptor
Returns
an event representing the copy operation.
Definition at line 1612 of file bindless_images.hpp.
References sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [2/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor & ImageDesc, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from device to device memory, where Src and Dest are opaque image memory handles.
An exception is thrown if either Src or Dest is incomplete
Parameters
Src is an opaque image memory handle to the source memory.
Dest is an opaque image memory handle to the destination memory.
ImageDesc is the source image descriptor
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1598 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [3/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor & ImageDesc, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from device to device memory, where Src and Dest are opaque image memory handles.
An exception is thrown if either Src or Dest is incomplete
Parameters
Src is an opaque image memory handle to the source memory.
Dest is an opaque image memory handle to the destination memory.
ImageDesc is the source image descriptor
DepEvent is an events that specifies the kernel dependency.
Returns
an event representing the copy operation.
Definition at line 1584 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [4/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, sycl::range< 3 > SrcOffset, const ext::oneapi::experimental::image_descriptor & SrcImgDesc, void * Dest, sycl::range< 3 > DestOffset, sycl::range< 3 > DestExtent, sycl::range< 3 > CopyExtent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
Allows for a sub-region copy, where SrcOffset , DestOffset , and CopyExtent are used to determine the sub-region. Pixel size is determined by SrcImgDesc An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is an opaque image memory handle to the source memory.
SrcOffset is an offset from the origin of source measured in pixels (pixel size determined by SrcImgDesc)
SrcImgDesc is the source image descriptor
Dest is a USM pointer to the destination memory.
DestOffset is an offset from the destination origin where the x, y, and z components are measured in bytes, rows, and slices respectively
DestExtent is the extent of the dest memory to copy, measured in pixels (pixel size determined by DestImgDesc)
CopyExtent is the width, height, and depth of the region to copy measured in pixels (pixel size determined by SrcImgDesc)
Returns
an event representing the copy operation.
Definition at line 1472 of file bindless_images.hpp.
References sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [5/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, sycl::range< 3 > SrcOffset, const ext::oneapi::experimental::image_descriptor & SrcImgDesc, void * Dest, sycl::range< 3 > DestOffset, sycl::range< 3 > DestExtent, sycl::range< 3 > CopyExtent, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
Allows for a sub-region copy, where SrcOffset , DestOffset , and CopyExtent are used to determine the sub-region. Pixel size is determined by SrcImgDesc An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is an opaque image memory handle to the source memory.
SrcOffset is an offset from the origin of source measured in pixels (pixel size determined by SrcImgDesc)
SrcImgDesc is the source image descriptor
Dest is a USM pointer to the destination memory.
DestOffset is an offset from the destination origin where the x, y, and z components are measured in bytes, rows, and slices respectively
DestExtent is the extent of the dest memory to copy, measured in pixels (pixel size determined by DestImgDesc)
CopyExtent is the width, height, and depth of the region to copy measured in pixels (pixel size determined by SrcImgDesc)
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1528 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [6/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, sycl::range< 3 > SrcOffset, const ext::oneapi::experimental::image_descriptor & SrcImgDesc, void * Dest, sycl::range< 3 > DestOffset, sycl::range< 3 > DestExtent, sycl::range< 3 > CopyExtent, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
Allows for a sub-region copy, where SrcOffset , DestOffset , and CopyExtent are used to determine the sub-region. Pixel size is determined by SrcImgDesc An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is an opaque image memory handle to the source memory.
SrcOffset is an offset from the origin of source measured in pixels (pixel size determined by SrcImgDesc)
SrcImgDesc is the source image descriptor
Dest is a USM pointer to the destination memory.
DestOffset is an offset from the destination origin where the x, y, and z components are measured in bytes, rows, and slices respectively
DestExtent is the extent of the dest memory to copy, measured in pixels (pixel size determined by DestImgDesc)
CopyExtent is the width, height, and depth of the region to copy measured in pixels (pixel size determined by SrcImgDesc)
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1499 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [7/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, void * Dest, const ext::oneapi::experimental::image_descriptor & SrcImgDesc, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
An exception is thrown if either Src is incomplete or Dest is nullptr. The behavior is undefined if SrcImgDesc is inconsistent with the allocated memory region.
Parameters
Src is an opaque image memory handle to the source memory.
Dest is a USM pointer to the destination memory.
SrcImgDesc is the source image descriptor.
Returns
an event representing the copy operation.
Definition at line 1462 of file bindless_images.hpp.
References sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [8/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, void * Dest, const ext::oneapi::experimental::image_descriptor & SrcImgDesc, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
An exception is thrown if either Src is incomplete or Dest is nullptr. The behavior is undefined if SrcImgDesc is inconsistent with the allocated memory region.
Parameters
Src is an opaque image memory handle to the source memory.
Dest is a USM pointer to the destination memory.
SrcImgDesc is the image descriptor (format, order, dimensions).
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1515 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [9/21]
event sycl::_V1::queue::ext_oneapi_copy (ext::oneapi::experimental::image_mem_handle Src, void * Dest, const ext::oneapi::experimental::image_descriptor & SrcImgDesc, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is an opaque image memory handle and Dest is a USM pointer.
An exception is thrown if either Src is incomplete or Dest is nullptr. The behavior is undefined if SrcImgDesc is inconsistent with the allocated memory region.
Parameters
Src is an opaque image memory handle to the source memory.
Dest is a USM pointer to the destination memory.
SrcImgDesc is the image descriptor (format, order, dimensions).
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1486 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [10/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor & DestImgDesc, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle wrapper.
An exception is thrown if either Src is nullptr or Dest is incomplete. The behavior is undefined if DestImgDesc is inconsistent with the allocated memory region.
Parameters
Src is a USM pointer to the source memory.
Dest is a wrapper for an opaque image memory handle to the destination memory.
DestImgDesc is the image descriptor (format, order, dimensions).
Returns
an event representing the copy operation.
Definition at line 1380 of file bindless_images.hpp.
References sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [11/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor & DestImgDesc, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle wrapper.
An exception is thrown if either Src is nullptr or Dest is incomplete. The behavior is undefined if DestImgDesc is inconsistent with the allocated memory region.
Parameters
Src is a USM pointer to the source memory.
Dest is a wrapper for an opaque image memory handle to the destination memory.
DestImgDesc is the destination image descriptor
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1433 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [12/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, ext::oneapi::experimental::image_mem_handle Dest, const ext::oneapi::experimental::image_descriptor & DestImgDesc, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle wrapper.
An exception is thrown if either Src is nullptr or Dest is incomplete. The behavior is undefined if DestImgDesc is inconsistent with the allocated memory region.
Parameters
Src is a USM pointer to the source memory.
Dest is a wrapper for an opaque image memory handle to the destination memory.
DestImgDesc is the destination image descriptor
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1404 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [13/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, sycl::range< 3 > SrcOffset, sycl::range< 3 > SrcExtent, ext::oneapi::experimental::image_mem_handle Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor & DestImgDesc, sycl::range< 3 > CopyExtent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
Allows for a sub-region copy, where SrcOffset , DestOffset , and CopyExtent are used to determine the sub-region. An exception is thrown if either Src is nullptr or CopyExtent is incomplete.
Parameters
Src is a USM pointer to the source memory.
SrcOffset is an offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
SrcExtent is the extent of the source memory to copy, measured in pixels (pixel size determined by DestImgDesc)
Dest is an opaque image memory handle to the destination memory.
DestOffset is an offset from the destination origin measured in pixels (pixel size determined by DestImgDesc)
DestImgDesc is the destination image descriptor
CopyExtent is the width, height, and depth of the region to copy measured in pixels as determined by DestImgDesc
Returns
an event representing the copy operation.
Definition at line 1390 of file bindless_images.hpp.
References sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [14/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, sycl::range< 3 > SrcOffset, sycl::range< 3 > SrcExtent, ext::oneapi::experimental::image_mem_handle Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor & DestImgDesc, sycl::range< 3 > CopyExtent, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
Allows for a sub-region copy, where SrcOffset , DestOffset , and CopyExtent are used to determine the sub-region. An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is a USM pointer to the source memory.
SrcOffset is an offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
SrcExtent is the extent of the source memory to copy, measured in pixels (pixel size determined by DestImgDesc)
Dest is an opaque image memory handle to the destination memory.
DestOffset is an offset from the destination origin measured in pixels (pixel size determined by DestImgDesc)
DestImgDesc is the destination image descriptor
CopyExtent is the width, height, and depth of the region to copy measured in pixels as determined by DestImgDesc
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1446 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [15/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, sycl::range< 3 > SrcOffset, sycl::range< 3 > SrcExtent, ext::oneapi::experimental::image_mem_handle Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor & DestImgDesc, sycl::range< 3 > CopyExtent, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src is a USM pointer and Dest is an opaque image memory handle.
Allows for a sub-region copy, where SrcOffset , DestOffset , and CopyExtent are used to determine the sub-region. An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is a USM pointer to the source memory.
SrcOffset is an offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
SrcExtent is the extent of the source memory to copy, measured in pixels (pixel size determined by DestImgDesc)
Dest is an opaque image memory handle to the destination memory.
DestOffset is an offset from the destination origin measured in pixels (pixel size determined by DestImgDesc)
DestImgDesc is the destination image descriptor
CopyExtent is the width, height, and depth of the region to copy measured in pixels as determined by DestImgDesc
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1417 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [16/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, sycl::range< 3 > SrcOffset, void * Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor & DeviceImgDesc, size_t DeviceRowPitch, sycl::range< 3 > HostExtent, sycl::range< 3 > CopyExtent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src and Dest are USM pointers.
Allows for a sub-region copy, where SrcOffset , DestOffset , and Extent are used to determine the sub-region. An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is a USM pointer to the source memory.
SrcOffset is an destination offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
Dest is a USM pointer to the destination memory.
DestOffset is an destination offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
DeviceImgDesc is the device image descriptor
DeviceRowPitch is the row pitch on the device
HostExtent is the extent of the host memory to copy, measured in pixels (pixel size determined by DeviceImgDesc)
CopyExtent is the width, height, and depth of the region to copy measured in pixels (pixel size determined by DeviceImgDesc)
Returns
an event representing the copy operation.
Definition at line 1556 of file bindless_images.hpp.
References sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [17/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, sycl::range< 3 > SrcOffset, void * Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor & DeviceImgDesc, size_t DeviceRowPitch, sycl::range< 3 > HostExtent, sycl::range< 3 > CopyExtent, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src and Dest are USM pointers.
Allows for a sub-region copy, where SrcOffset , DestOffset , and Extent are used to determine the sub-region. An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is a USM pointer to the source memory.
SrcOffset is an destination offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
Dest is a USM pointer to the destination memory.
DestOffset is an destination offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
DeviceImgDesc is the destination image descriptor
DeviceRowPitch is the row pitch on the device
HostExtent is the extent of the host memory to copy, measured in pixels (pixel size determined by DeviceImgDesc)
CopyExtent is the width, height, and depth of the region to copy measured in pixels (pixel size determined by DeviceImgDesc)
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1652 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [18/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, sycl::range< 3 > SrcOffset, void * Dest, sycl::range< 3 > DestOffset, const ext::oneapi::experimental::image_descriptor & DeviceImgDesc, size_t DeviceRowPitch, sycl::range< 3 > HostExtent, sycl::range< 3 > CopyExtent, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src and Dest are USM pointers.
Allows for a sub-region copy, where SrcOffset , DestOffset , and Extent are used to determine the sub-region. An exception is thrown if either Src is nullptr or Dest is incomplete.
Parameters
Src is a USM pointer to the source memory.
SrcOffset is an destination offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
Dest is a USM pointer to the destination memory.
DestOffset is an destination offset from the origin where the x, y, and z components are measured in bytes, rows, and slices respectively
DeviceImgDesc is the destination image descriptor
DeviceRowPitch is the row pitch on the device
HostExtent is the extent of the host memory to copy, measured in pixels (pixel size determined by DeviceImgDesc)
CopyExtent is the width, height, and depth of the region to copy measured in pixels (pixel size determined by DeviceImgDesc)
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1623 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [19/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, void * Dest, const ext::oneapi::experimental::image_descriptor & DeviceImgDesc, size_t DeviceRowPitch, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src and Dest are USM pointers.
An exception is thrown if either Src is nullptr, Dest is nullptr, or Pitch is inconsistent with hardware requirements. The behavior is undefined if DeviceImgDesc is inconsistent with the allocated memory region.
Parameters
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
DeviceImgDesc is the image descriptor
DeviceRowPitch is the DeviceRowPitch of the rows on the device.
Returns
an event representing the copy operation.
Definition at line 1544 of file bindless_images.hpp.
References sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [20/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, void * Dest, const ext::oneapi::experimental::image_descriptor & DeviceImgDesc, size_t DeviceRowPitch, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src and Dest are USM pointers.
An exception is thrown if either Src is nullptr, Dest is nullptr, or Pitch is inconsistent with hardware requirements. The behavior is undefined if DeviceImgDesc is inconsistent with the allocated memory region.
Parameters
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
DeviceImgDesc is the image descriptor
DeviceRowPitch is the pitch of the rows on the device.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1638 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy() [21/21]
event sycl::_V1::queue::ext_oneapi_copy (void * Src, void * Dest, const ext::oneapi::experimental::image_descriptor & DeviceImgDesc, size_t DeviceRowPitch, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one memory region to another, where Src and Dest are USM pointers.
An exception is thrown if either Src is nullptr, Dest is nullptr, or Pitch is inconsistent with hardware requirements. The behavior is undefined if DeviceImgDesc is inconsistent with the allocated memory region.
Parameters
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
DeviceImgDesc is the image descriptor
DeviceRowPitch is the pitch of the rows on the device.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 1570 of file bindless_images.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy(), and submit().
ext_oneapi_copy2d() [1/3]
template<typename T > event sycl::_V1::queue::ext_oneapi_copy2d (const T * Src, size_t SrcPitch, T * Dest, size_t DestPitch, size_t Width, size_t Height, const detail::code_location & CodeLoc = detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than either
DestPitch or
SrcPitch. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
SrcPitch is the pitch of the rows in
Src.
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Width is the width in number of elements of the 2D region to copy.
Height is the height in number of rows of the 2D region to copy.
Returns
an event representing the copy operation.
Definition at line 173 of file memcpy2d.hpp.
References sycl::_V1::handler::ext_oneapi_copy2d(), and submit().
ext_oneapi_copy2d() [2/3]
template<typename T > event sycl::_V1::queue::ext_oneapi_copy2d (const T * Src, size_t SrcPitch, T * Dest, size_t DestPitch, size_t Width, size_t Height, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than either
DestPitch or
SrcPitch. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
SrcPitch is the pitch of the rows in
Src.
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Width is the width in number of elements of the 2D region to copy.
Height is the height in number of rows of the 2D region to copy.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 197 of file memcpy2d.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy2d(), and submit().
ext_oneapi_copy2d() [3/3]
template<typename T > event sycl::_V1::queue::ext_oneapi_copy2d (const T * Src, size_t SrcPitch, T * Dest, size_t DestPitch, size_t Width, size_t Height, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than either
DestPitch or
SrcPitch. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
SrcPitch is the pitch of the rows in
Src.
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Width is the width in number of elements of the 2D region to copy.
Height is the height in number of rows of the 2D region to copy.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 184 of file memcpy2d.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_copy2d(), and submit().
ext_oneapi_empty()
bool sycl::_V1::queue::ext_oneapi_empty () const
Allows to check status of the queue (completed vs noncompleted).
Returns
returns true if all enqueued commands in the queue have been completed, otherwise returns false.
Definition at line 324 of file queue.cpp.
ext_oneapi_fill2d() [1/3]
template<typename T > event sycl::_V1::queue::ext_oneapi_fill2d (void * Dest, size_t DestPitch, const T & Pattern, size_t Width, size_t Height, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than
DestPitch. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Width is the width in number of elements of the 2D region to fill.
Height is the height in number of rows of the 2D region to fill.
Returns
an event representing the fill operation.
Definition at line 246 of file memcpy2d.hpp.
References sycl::_V1::handler::ext_oneapi_fill2d(), and submit().
ext_oneapi_fill2d() [2/3]
template<typename T > event sycl::_V1::queue::ext_oneapi_fill2d (void * Dest, size_t DestPitch, const T & Pattern, size_t Width, size_t Height, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than
DestPitch. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Width is the width in number of elements of the 2D region to fill.
Height is the height in number of rows of the 2D region to fill.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the fill operation.
Definition at line 269 of file memcpy2d.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_fill2d(), and submit().
ext_oneapi_fill2d() [3/3]
template<typename T > event sycl::_V1::queue::ext_oneapi_fill2d (void * Dest, size_t DestPitch, const T & Pattern, size_t Width, size_t Height, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than
DestPitch. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Width is the width in number of elements of the 2D region to fill.
Height is the height in number of rows of the 2D region to fill.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the fill operation.
Definition at line 257 of file memcpy2d.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_fill2d(), and submit().
ext_oneapi_get_graph()
ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::modifiable > sycl::_V1::queue::ext_oneapi_get_graph () const
Returns
Graph when the queue is recording.
Definition at line 86 of file queue.cpp.
References sycl::_V1::detail::createSyclObjFromImpl(), sycl::_V1::invalid, sycl::_V1::make_error_code(), and sycl::_V1::ext::oneapi::experimental::modifiable.
ext_oneapi_get_last_event()
event sycl::_V1::queue::ext_oneapi_get_last_event () const
Definition at line 358 of file queue.cpp.
References sycl::_V1::invalid, is_in_order(), and sycl::_V1::make_error_code().
ext_oneapi_get_state()
ext::oneapi::experimental::queue_state sycl::_V1::queue::ext_oneapi_get_state () const
Returns
State the queue is currently in.
Definition at line 78 of file queue.cpp.
ext_oneapi_graph() [1/3]
event sycl::_V1::queue::ext_oneapi_graph (ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::executable > Graph, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Shortcut for executing a graph of commands.
Parameters
Graph the graph of commands to execute
Returns
an event representing graph execution operation.
Definition at line 2539 of file queue.hpp.
References sycl::_V1::handler::ext_oneapi_graph(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_graph() [2/3]
event sycl::_V1::queue::ext_oneapi_graph (ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::executable > Graph, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Shortcut for executing a graph of commands with multiple dependencies.
Parameters
Graph the graph of commands to execute
DepEvents is a vector of events that specifies the graph execution dependencies.
Returns
an event representing graph execution operation.
Definition at line 2573 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_graph(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_graph() [3/3]
event sycl::_V1::queue::ext_oneapi_graph (ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::executable > Graph, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Shortcut for executing a graph of commands with a single dependency.
Parameters
Graph the graph of commands to execute
DepEvent is an event that specifies the graph execution dependencies.
Returns
an event representing graph execution operation.
Definition at line 2553 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_graph(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_memcpy2d() [1/3]
template<typename T = unsigned char, typename = std::enable_if_t<std::is_same_v<T, unsigned char>>> event sycl::_V1::queue::ext_oneapi_memcpy2d (void * Dest, size_t DestPitch, const void * Src, size_t SrcPitch, size_t Width, size_t Height, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from one 2D memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than either
DestPitch or
SrcPitch. The behavior is undefined if any of the pointer parameters is invalid.
NOTE: Function is dependent to prevent the fallback kernels from materializing without the use of the function.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Src is a USM pointer to the source memory.
SrcPitch is the pitch of the rows in
Src.
Width is the width in bytes of the 2D region to copy.
Height is the height in number of rows of the 2D region to copy.
Returns
an event representing the copy operation.
Definition at line 809 of file queue.hpp.
References sycl::_V1::handler::ext_oneapi_memcpy2d(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_memcpy2d() [2/3]
template<typename T , typename > event sycl::_V1::queue::ext_oneapi_memcpy2d (void * Dest, size_t DestPitch, const void * Src, size_t SrcPitch, size_t Width, size_t Height, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than either
DestPitch or
SrcPitch. The behavior is undefined if any of the pointer parameters is invalid.
NOTE: Function is dependent to prevent the fallback kernels from materializing without the use of the function.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Src is a USM pointer to the source memory.
SrcPitch is the pitch of the rows in
Src.
Width is the width in bytes of the 2D region to copy.
Height is the height in number of rows of the 2D region to copy.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 159 of file memcpy2d.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_memcpy2d(), and submit().
ext_oneapi_memcpy2d() [3/3]
template<typename T , typename > event sycl::_V1::queue::ext_oneapi_memcpy2d (void * Dest, size_t DestPitch, const void * Src, size_t SrcPitch, size_t Width, size_t Height, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current())
Copies data from one 2D memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than either
DestPitch or
SrcPitch. The behavior is undefined if any of the pointer parameters is invalid.
NOTE: Function is dependent to prevent the fallback kernels from materializing without the use of the function.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Src is a USM pointer to the source memory.
SrcPitch is the pitch of the rows in
Src.
Width is the width in bytes of the 2D region to copy.
Height is the height in number of rows of the 2D region to copy.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the copy operation.
Definition at line 145 of file memcpy2d.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_memcpy2d(), and submit().
ext_oneapi_memset2d() [1/3]
template<typename T , typename > event sycl::_V1::queue::ext_oneapi_memset2d (void * Dest, size_t DestPitch, int Value, size_t Width, size_t Height, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than
DestPitch. The behavior is undefined if any of the pointer parameters is invalid.
NOTE: Function is dependent to prevent the fallback kernels from materializing without the use of the function.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Value is the value to fill into the region in
Dest. Value is cast as an unsigned char.
Width is the width in number of elements of the 2D region to fill.
Height is the height in number of rows of the 2D region to fill.
Returns
an event representing the fill operation.
Definition at line 210 of file memcpy2d.hpp.
References sycl::_V1::handler::ext_oneapi_memset2d(), and submit().
ext_oneapi_memset2d() [2/3]
template<typename T , typename > event sycl::_V1::queue::ext_oneapi_memset2d (void * Dest, size_t DestPitch, int Value, size_t Width, size_t Height, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than
DestPitch. The behavior is undefined if any of the pointer parameters is invalid.
NOTE: Function is dependent to prevent the fallback kernels from materializing without the use of the function.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Value is the value to fill into the region in
Dest. Value is cast as an unsigned char.
Width is the width in number of elements of the 2D region to fill.
Height is the height in number of rows of the 2D region to fill.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the fill operation.
Definition at line 233 of file memcpy2d.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_memset2d(), and submit().
ext_oneapi_memset2d() [3/3]
template<typename T , typename > event sycl::_V1::queue::ext_oneapi_memset2d (void * Dest, size_t DestPitch, int Value, size_t Width, size_t Height, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Width or
Height is zero. An exception is thrown if either
Dest or
Src is nullptr or if
Width is strictly greater than
DestPitch. The behavior is undefined if any of the pointer parameters is invalid.
NOTE: Function is dependent to prevent the fallback kernels from materializing without the use of the function.
Parameters
Dest is a USM pointer to the destination memory.
DestPitch is the pitch of the rows in
Dest.
Value is the value to fill into the region in
Dest. Value is cast as an unsigned char.
Width is the width in number of elements of the 2D region to fill.
Height is the height in number of rows of the 2D region to fill.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the fill operation.
Definition at line 221 of file memcpy2d.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_memset2d(), and submit().
ext_oneapi_set_external_event()
void sycl::_V1::queue::ext_oneapi_set_external_event (const event & external_event)
Definition at line 371 of file queue.cpp.
References sycl::_V1::invalid, is_in_order(), and sycl::_V1::make_error_code().
ext_oneapi_signal_external_semaphore() [1/3]
event sycl::_V1::queue::ext_oneapi_signal_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Instruct the queue to signal the external semaphore once all previous commands have completed execution.
An exception is thrown if SemaphoreHandle is incomplete.
Parameters
SemaphoreHandle is an opaque external interop semaphore handle
Returns
an event representing the signal operation.
Definition at line 1908 of file queue.hpp.
References sycl::_V1::handler::ext_oneapi_signal_external_semaphore(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_signal_external_semaphore() [2/3]
event sycl::_V1::queue::ext_oneapi_signal_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Instruct the queue to signal the external semaphore once all previous commands have completed execution.
An exception is thrown if SemaphoreHandle is incomplete.
Parameters
SemaphoreHandle is an opaque external interop semaphore handle
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the signal operation.
Definition at line 1947 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_signal_external_semaphore(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_signal_external_semaphore() [3/3]
event sycl::_V1::queue::ext_oneapi_signal_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Instruct the queue to signal the external semaphore once all previous commands have completed execution.
An exception is thrown if SemaphoreHandle is incomplete.
Parameters
SemaphoreHandle is an opaque external interop semaphore handle
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the signal operation.
Definition at line 1926 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_signal_external_semaphore(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_submit_barrier() [1/2]
event sycl::_V1::queue::ext_oneapi_submit_barrier (const detail::code_location & CodeLoc = detail::code_location::current())
Prevents any commands submitted afterward to this queue from executing until all commands previously submitted to this queue have entered the complete state.
Parameters
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object, which corresponds to the queue the command group is being enqueued on.
Definition at line 242 of file queue.cpp.
References sycl::_V1::handler::ext_oneapi_barrier(), sycl::_V1::getBarrierEventForInorderQueueHelper(), is_in_order(), and submit().
ext_oneapi_submit_barrier() [2/2]
event sycl::_V1::queue::ext_oneapi_submit_barrier (const std::vector< event > & WaitList, const detail::code_location & CodeLoc = detail::code_location::current())
Prevents any commands submitted afterward to this queue from executing until all events in WaitList have entered the complete state.
If WaitList is empty, then ext_oneapi_submit_barrier has no effect.
Parameters
WaitList is a vector of valid SYCL events that need to complete before barrier command can be executed.
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object, which corresponds to the queue the command group is being enqueued on.
Definition at line 258 of file queue.cpp.
References all_of(), sycl::_V1::handler::ext_oneapi_barrier(), sycl::_V1::getBarrierEventForInorderQueueHelper(), sycl::_V1::detail::getSyclObjImpl(), is_in_order(), and submit().
ext_oneapi_wait_external_semaphore() [1/3]
event sycl::_V1::queue::ext_oneapi_wait_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Instruct the queue with a non-blocking wait on an external semaphore.
An exception is thrown if SemaphoreHandle is incomplete.
Parameters
SemaphoreHandle is an opaque external interop semaphore handle
Returns
an event representing the wait operation.
Definition at line 1852 of file queue.hpp.
References sycl::_V1::handler::ext_oneapi_wait_external_semaphore(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_wait_external_semaphore() [2/3]
event sycl::_V1::queue::ext_oneapi_wait_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Instruct the queue with a non-blocking wait on an external semaphore.
An exception is thrown if SemaphoreHandle is incomplete.
Parameters
SemaphoreHandle is an opaque external interop semaphore handle
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing the wait operation.
Definition at line 1889 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_wait_external_semaphore(), and sycl::_V1::ext::oneapi::experimental::submit().
ext_oneapi_wait_external_semaphore() [3/3]
event sycl::_V1::queue::ext_oneapi_wait_external_semaphore (sycl::ext::oneapi::experimental::interop_semaphore_handle SemaphoreHandle, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Instruct the queue with a non-blocking wait on an external semaphore.
An exception is thrown if SemaphoreHandle is incomplete.
Parameters
SemaphoreHandle is an opaque external interop semaphore handle
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing the wait operation.
Definition at line 1869 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::ext_oneapi_wait_external_semaphore(), and sycl::_V1::ext::oneapi::experimental::submit().
fill() [1/4]
template<typename T , int Dims, access_mode Mode, target Tgt, access::placeholder IsPlaceholder> event sycl::_V1::queue::fill (accessor< T, Dims, Mode, Tgt, IsPlaceholder > Dest, const T & Src, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Fills the specified memory with the specified data.
Parameters
Dest is the placeholder accessor to the memory to fill.
Src is the data to fill the memory with. T should be trivially copyable.
Returns
an event representing fill operation.
Definition at line 2513 of file queue.hpp.
References sycl::_V1::handler::fill(), sycl::_V1::handler::require(), and sycl::_V1::ext::oneapi::experimental::submit().
fill() [2/4]
template<typename T > event sycl::_V1::queue::fill (void * Ptr, const T & Pattern, size_t Count, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Fills the specified memory with the specified pattern.
Parameters
Ptr is the pointer to the memory to fill.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Count is the number of times to fill Pattern into Ptr.
Returns
an event representing fill operation.
Definition at line 480 of file queue.hpp.
References sycl::_V1::handler::fill(), and sycl::_V1::ext::oneapi::experimental::submit().
Referenced by syclcompat::detail::fill().
fill() [3/4]
template<typename T > event sycl::_V1::queue::fill (void * Ptr, const T & Pattern, size_t Count, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Fills the specified memory with the specified pattern.
Parameters
Ptr is the pointer to the memory to fill.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Count is the number of times to fill Pattern into Ptr.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing fill operation.
Definition at line 519 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::fill(), and sycl::_V1::ext::oneapi::experimental::submit().
fill() [4/4]
template<typename T > event sycl::_V1::queue::fill (void * Ptr, const T & Pattern, size_t Count, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Fills the specified memory with the specified pattern.
Parameters
Ptr is the pointer to the memory to fill.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Count is the number of times to fill Pattern into Ptr.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing fill operation.
Definition at line 497 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::fill(), and sycl::_V1::ext::oneapi::experimental::submit().
get_backend()
backend sycl::_V1::queue::get_backend () const noexcept
Returns the backend associated with this queue.
Returns
the backend associated with this queue.
Definition at line 322 of file queue.cpp.
References sycl::_V1::detail::getImplBackend().
get_backend_info()
template<typename Param > detail::is_backend_info_desc< Param >::return_type sycl::_V1::queue::get_backend_info
Queries SYCL queue for SYCL backend-specific information.
The return type depends on information being queried.
Definition at line 287 of file queue.cpp.
get_context()
context sycl::_V1::queue::get_context () const
Returns
a valid instance of OpenCL queue, which is retained before being returned.
an associated SYCL context.
Definition at line 74 of file queue.cpp.
Referenced by sycl::_V1::ext::oneapi::experimental::alloc_image_mem(), sycl::_V1::ext::oneapi::experimental::create_image(), sycl::_V1::ext::oneapi::experimental::destroy_external_semaphore(), sycl::_V1::ext::oneapi::experimental::destroy_image_handle(), syclcompat::free(), sycl::_V1::ext::oneapi::experimental::free_image_mem(), sycl::_V1::ext::oneapi::experimental::get_image_channel_type(), sycl::_V1::ext::oneapi::experimental::get_image_num_channels(), sycl::_V1::ext::oneapi::experimental::get_image_range(), sycl::_V1::ext::oneapi::experimental::get_mip_level_mem_handle(), syclcompat::detail::get_pointer_attribute(), sycl::_V1::ext::oneapi::experimental::import_external_memory< resource_fd >(), sycl::_V1::ext::oneapi::experimental::import_external_semaphore(), syclcompat::pointer_attributes::init(), syclcompat::detail::malloc(), sycl::_V1::ext::oneapi::experimental::malloc_annotated(), sycl::_V1::ext::oneapi::experimental::map_external_image_memory(), sycl::_V1::ext::oneapi::experimental::pitched_alloc_device(), sycl::_V1::ext::oneapi::experimental::prepare_for_device_copy(), sycl::_V1::ext::oneapi::experimental::release_external_memory(), and sycl::_V1::ext::oneapi::experimental::release_from_device_copy().
get_device()
device sycl::_V1::queue::get_device () const
Returns
SYCL device this queue was constructed with.
Definition at line 76 of file queue.cpp.
Referenced by sycl::_V1::ext::oneapi::experimental::alloc_image_mem(), sycl::_V1::ext::oneapi::experimental::create_image(), sycl::_V1::ext::oneapi::experimental::destroy_external_semaphore(), sycl::_V1::ext::oneapi::experimental::destroy_image_handle(), sycl::_V1::ext::oneapi::experimental::free_image_mem(), sycl::_V1::ext::oneapi::experimental::get_image_channel_type(), sycl::_V1::ext::oneapi::experimental::get_image_num_channels(), sycl::_V1::ext::oneapi::experimental::get_image_range(), sycl::_V1::ext::oneapi::experimental::get_mip_level_mem_handle(), sycl::_V1::detail::reduction_impl_algo< T, BinaryOperation, Dims, Extent, ExplicitIdentity, RedOutVar >::getGroupsCounterAccDiscrete(), sycl::_V1::ext::oneapi::experimental::import_external_memory< resource_fd >(), sycl::_V1::ext::oneapi::experimental::import_external_semaphore(), syclcompat::detail::malloc(), sycl::_V1::ext::oneapi::experimental::malloc_annotated(), sycl::_V1::ext::oneapi::experimental::map_external_image_memory(), sycl::_V1::ext::oneapi::experimental::pitched_alloc_device(), sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read(), sycl::_V1::ext::oneapi::experimental::release_external_memory(), and sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write().
get_info()
template<typename Param > detail::is_queue_info_desc< Param >::return_type sycl::_V1::queue::get_info
Queries SYCL queue for information.
The return type depends on information being queried.
Definition at line 274 of file queue.cpp.
get_property()
template<typename PropertyT > PropertyT sycl::_V1::queue::get_property
Returns
a copy of the property of type PropertyT that the queue was constructed with. If the queue was not constructed with the PropertyT property, an invalid_object_error SYCL exception.
Definition at line 303 of file queue.cpp.
getNative()
pi_native_handle sycl::_V1::queue::getNative (int32_t & NativeHandleDesc) const
Definition at line 326 of file queue.cpp.
has_property()
template<typename PropertyT > bool sycl::_V1::queue::has_property noexcept
Returns
true if the queue was constructed with property specified by PropertyT.
Definition at line 299 of file queue.cpp.
is_in_order()
bool sycl::_V1::queue::is_in_order () const
Returns whether the queue is in order or OoO.
Equivalent to has_property<property::queue::in_order>()
Definition at line 318 of file queue.cpp.
Referenced by ext_oneapi_get_last_event(), ext_oneapi_set_external_event(), and ext_oneapi_submit_barrier().
mem_advise() [1/4]
event sycl::_V1::queue::mem_advise (const void * Ptr, size_t Length, int Advice, const detail::code_location & CodeLoc = detail::code_location::current())
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
Returns
an event representing advice operation.
Definition at line 150 of file queue.cpp.
mem_advise() [2/4]
event sycl::_V1::queue::mem_advise (const void * Ptr, size_t Length, int Advice, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current())
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing advice operation.
Definition at line 162 of file queue.cpp.
mem_advise() [3/4]
event sycl::_V1::queue::mem_advise (const void * Ptr, size_t Length, int Advice, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current())
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing advice operation.
Definition at line 156 of file queue.cpp.
mem_advise() [4/4]
event sycl::_V1::queue::mem_advise (const void * Ptr, size_t Length, pi_mem_advice Advice, const detail::code_location & CodeLoc = detail::code_location::current())
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
Returns
an event representing advice operation.
Definition at line 144 of file queue.cpp.
memcpy() [1/9]
template<typename T , typename PropertyListT > event sycl::_V1::queue::memcpy (ext::oneapi::experimental::device_global< T, PropertyListT > & Dest, const void * Src, size_t NumBytes, size_t Offset, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a USM memory region to a device_global.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Dest,as specified through
NumBytes and
Offset.
Dest is the destination device_glboal.
Src is a USM pointer to the source memory.
NumBytes is a number of bytes to copy.
Offset is the offset into
Dest to copy to.
DepEvents is a vector of events that specifies the operation dependencies.
Returns
an event representing copy operation.
Definition at line 1084 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::ext::oneapi::experimental::has_property(), sycl::_V1::invalid, sycl::_V1::detail::isDeviceGlobalUsedInKernel(), sycl::_V1::make_error_code(), sycl::_V1::handler::memcpy(), and sycl::_V1::ext::oneapi::experimental::submit().
memcpy() [2/9]
template<typename T , typename PropertyListT > event sycl::_V1::queue::memcpy (ext::oneapi::experimental::device_global< T, PropertyListT > & Dest, const void * Src, size_t NumBytes, size_t Offset, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a USM memory region to a device_global.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Dest,as specified through
NumBytes and
Offset.
Dest is the destination device_glboal.
Src is a USM pointer to the source memory.
NumBytes is a number of bytes to copy.
Offset is the offset into
Dest to copy to.
DepEvent is a vector of event that specifies the operation dependency.
Returns
an event representing copy operation.
Definition at line 1124 of file queue.hpp.
memcpy() [3/9]
template<typename T , typename PropertyListT > event sycl::_V1::queue::memcpy (ext::oneapi::experimental::device_global< T, PropertyListT > & Dest, const void * Src, size_t NumBytes = sizeof(T), size_t Offset = 0, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a USM memory region to a device_global.
Throws an exception if the copy operation intends to write outside the memory range
Parameters
Dest,as specified through
NumBytes and
Offset.
Dest is the destination device_glboal.
Src is a USM pointer to the source memory.
NumBytes is a number of bytes to copy.
Offset is the offset into
Dest to copy to.
Returns
an event representing copy operation.
Definition at line 1144 of file queue.hpp.
memcpy() [4/9]
template<typename T , typename PropertyListT > event sycl::_V1::queue::memcpy (void * Dest, const ext::oneapi::experimental::device_global< T, PropertyListT > & Src, size_t NumBytes, size_t Offset, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a device_global to USM memory.
Throws an exception if the copy operation intends to read outside the memory range
Parameters
Src,as specified through
NumBytes and
Offset.
Dest is a USM pointer to copy to.
Src is the source device_global.
NumBytes is a number of bytes to copy.
Offset is the offset into
Src to copy from.
DepEvents is a vector of events that specifies the operation dependencies.
Returns
an event representing copy operation.
Definition at line 1165 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::ext::oneapi::experimental::has_property(), sycl::_V1::invalid, sycl::_V1::detail::isDeviceGlobalUsedInKernel(), sycl::_V1::make_error_code(), sycl::_V1::handler::memcpy(), and sycl::_V1::ext::oneapi::experimental::submit().
memcpy() [5/9]
template<typename T , typename PropertyListT > event sycl::_V1::queue::memcpy (void * Dest, const ext::oneapi::experimental::device_global< T, PropertyListT > & Src, size_t NumBytes, size_t Offset, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a device_global to USM memory.
Throws an exception if the copy operation intends to read outside the memory range
Parameters
Src,as specified through
NumBytes and
Offset.
Dest is a USM pointer to copy to.
Src is the source device_global.
NumBytes is a number of bytes to copy.
Offset is the offset into
Src to copy from.
DepEvent is a vector of event that specifies the operation dependency.
Returns
an event representing copy operation.
Definition at line 1203 of file queue.hpp.
memcpy() [6/9]
template<typename T , typename PropertyListT > event sycl::_V1::queue::memcpy (void * Dest, const ext::oneapi::experimental::device_global< T, PropertyListT > & Src, size_t NumBytes = sizeof(T), size_t Offset = 0, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Copies data from a device_global to USM memory.
Throws an exception if the copy operation intends to read outside the memory range
Parameters
Src,as specified through
NumBytes and
Offset.
Dest is a USM pointer to copy to.
Src is the source device_global.
NumBytes is a number of bytes to copy.
Offset is the offset into
Src to copy from.
Returns
an event representing copy operation.
Definition at line 1224 of file queue.hpp.
memcpy() [7/9]
event sycl::_V1::queue::memcpy (void * Dest, const void * Src, size_t Count, const detail::code_location & CodeLoc = detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
Src is a USM pointer to the source memory.
Count is a number of bytes to copy.
Returns
an event representing copy operation.
Definition at line 125 of file queue.cpp.
memcpy() [8/9]
event sycl::_V1::queue::memcpy (void * Dest, const void * Src, size_t Count, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
Src is a USM pointer to the source memory.
Count is a number of bytes to copy.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing copy operation.
Definition at line 137 of file queue.cpp.
memcpy() [9/9]
event sycl::_V1::queue::memcpy (void * Dest, const void * Src, size_t Count, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current())
Copies data from one memory region to another, each is either a host pointer or a pointer within USM allocation accessible on the device associated with this queue.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
Src is a USM pointer to the source memory.
Count is a number of bytes to copy.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing copy operation.
Definition at line 131 of file queue.cpp.
memset() [1/3]
event sycl::_V1::queue::memset (void * Ptr, int Value, size_t Count, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Count is zero. An exception is thrown if
Ptr is nullptr. The behavior is undefined if
Ptr is invalid.
Ptr is a USM pointer to the memory to fill.
Value is a value to be set. Value is cast as an unsigned char.
Count is a number of bytes to fill.
Returns
an event representing fill operation.
Definition at line 106 of file queue.cpp.
Referenced by sycl::_V1::detail::reduction_impl_algo< T, BinaryOperation, Dims, Extent, ExplicitIdentity, RedOutVar >::getGroupsCounterAccDiscrete(), and syclcompat::detail::memset().
memset() [2/3]
event sycl::_V1::queue::memset (void * Ptr, int Value, size_t Count, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Count is zero. An exception is thrown if
Ptr is nullptr. The behavior is undefined if
Ptr is invalid.
Ptr is a USM pointer to the memory to fill.
Value is a value to be set. Value is cast as an unsigned char.
Count is a number of bytes to fill.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing fill operation.
Definition at line 118 of file queue.cpp.
memset() [3/3]
event sycl::_V1::queue::memset (void * Ptr, int Value, size_t Count, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current())
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Count is zero. An exception is thrown if
Ptr is nullptr. The behavior is undefined if
Ptr is invalid.
Ptr is a USM pointer to the memory to fill.
Value is a value to be set. Value is cast as an unsigned char.
Count is a number of bytes to fill.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing fill operation.
Definition at line 112 of file queue.cpp.
operator!=()
bool sycl::_V1::queue::operator!= (const queue & RHS) const inline
Definition at line 287 of file queue.hpp.
operator=() [1/2]
queue& sycl::_V1::queue::operator= (const queue & RHS) default
operator=() [2/2]
queue& sycl::_V1::queue::operator= (queue && RHS) default
operator==()
bool sycl::_V1::queue::operator== (const queue & RHS) const inline
Definition at line 285 of file queue.hpp.
parallel_for() [1/14]
template<typename KernelName = detail::auto_name, int Dims, typename... RestT> event sycl::_V1::queue::parallel_for (nd_range< Dims > Range, const std::vector< event > & DepEvents, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
Parameters
Range specifies the global and local work spaces of the kernel
DepEvents is a vector of events that specifies the kernel dependencies
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2370 of file queue.hpp.
References sycl::_V1::handler::depends_on(), and sycl::_V1::ext::oneapi::experimental::submit().
parallel_for() [2/14]
template<typename KernelName = detail::auto_name, int Dims, typename... RestT> event sycl::_V1::queue::parallel_for (nd_range< Dims > Range, event DepEvent, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
Parameters
Range specifies the global and local work spaces of the kernel
DepEvent is an event that specifies the kernel dependencies
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2346 of file queue.hpp.
References sycl::_V1::handler::depends_on(), and sycl::_V1::ext::oneapi::experimental::submit().
parallel_for() [3/14]
template<typename KernelName = detail::auto_name, int Dims, typename PropertiesT , typename... RestT> std::enable_if_t< detail::AreAllButLastReductions<RestT...>::value && ext::oneapi::experimental::is_property_list<PropertiesT>::value, event> sycl::_V1::queue::parallel_for (nd_range< Dims > Range, PropertiesT Properties, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
Parameters
Range specifies the global and local work spaces of the kernel
Properties is the kernel properties.
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2310 of file queue.hpp.
References sycl::_V1::ext::oneapi::experimental::submit().
parallel_for() [4/14]
template<typename KernelName = detail::auto_name, int Dims, typename... RestT> std::enable_if_t<detail::AreAllButLastReductions<RestT...>::value, event> sycl::_V1::queue::parallel_for (nd_range< Dims > Range, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
Parameters
Range specifies the global and local work spaces of the kernel
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2332 of file queue.hpp.
parallel_for() [5/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 1 > Range, const std::vector< event > & DepEvents, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
DepEvents is a vector of events that specifies the kernel dependencies
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2172 of file queue.hpp.
parallel_for() [6/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 1 > Range, event DepEvent, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
DepEvent is an event that specifies the kernel dependencies
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2135 of file queue.hpp.
parallel_for() [7/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 1 > Range, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2101 of file queue.hpp.
Referenced by syclcompat::detail::launch().
parallel_for() [8/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 2 > Range, const std::vector< event > & DepEvents, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
DepEvents is a vector of events that specifies the kernel dependencies
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2186 of file queue.hpp.
parallel_for() [9/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 2 > Range, event DepEvent, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
DepEvent is an event that specifies the kernel dependencies
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2147 of file queue.hpp.
parallel_for() [10/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 2 > Range, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2112 of file queue.hpp.
parallel_for() [11/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 3 > Range, const std::vector< event > & DepEvents, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
DepEvents is a vector of events that specifies the kernel dependencies
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2200 of file queue.hpp.
parallel_for() [12/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 3 > Range, event DepEvent, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
DepEvent is an event that specifies the kernel dependencies
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2159 of file queue.hpp.
parallel_for() [13/14]
template<typename KernelName = detail::auto_name, typename... RestT> event sycl::_V1::queue::parallel_for (range< 3 > Range, RestT &&... Rest) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
Range specifies the global work space of the kernel
Rest acts as-if: "ReductionTypes&&... Reductions, const KernelType &KernelFunc".
Definition at line 2123 of file queue.hpp.
parallel_for() [14/14]
template<typename KernelName = detail::auto_name, typename KernelType , int Dim> event sycl::_V1::queue::parallel_for (range< Dim > Range, id< Dim > WorkItemOffset, const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc)) inline
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
Parameters
Range specifies the global work space of the kernel
WorkItemOffset specifies the offset for each work item id
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 2217 of file queue.hpp.
parallel_for_impl() [1/3]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event sycl::_V1::queue::parallel_for_impl (range< Dims > Range, id< Dims > WorkItemOffset, _KERNELFUNCPARAM(KernelFunc)) inline
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
Parameters
Range specifies the global work space of the kernel
WorkItemOffset specifies the offset for each work item id
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 2235 of file queue.hpp.
References sycl::_V1::ext::oneapi::experimental::submit().
parallel_for_impl() [2/3]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event sycl::_V1::queue::parallel_for_impl (range< Dims > Range, id< Dims > WorkItemOffset, const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc)) inline
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
Parameters
Range specifies the global work space of the kernel
WorkItemOffset specifies the offset for each work item id
DepEvents is a vector of events that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 2283 of file queue.hpp.
References sycl::_V1::handler::depends_on(), and sycl::_V1::ext::oneapi::experimental::submit().
parallel_for_impl() [3/3]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event sycl::_V1::queue::parallel_for_impl (range< Dims > Range, id< Dims > WorkItemOffset, event DepEvent, _KERNELFUNCPARAM(KernelFunc)) inline
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
Parameters
Range specifies the global work space of the kernel
WorkItemOffset specifies the offset for each work item id
DepEvent is an event that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 2258 of file queue.hpp.
References sycl::_V1::handler::depends_on(), and sycl::_V1::ext::oneapi::experimental::submit().
prefetch() [1/3]
event sycl::_V1::queue::prefetch (const void * Ptr, size_t Count, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
Parameters
Ptr is a USM pointer to the memory to be prefetched to the device.
Count is a number of bytes to be prefetched.
Returns
an event representing prefetch operation.
Definition at line 741 of file queue.hpp.
References sycl::_V1::handler::prefetch(), and sycl::_V1::ext::oneapi::experimental::submit().
prefetch() [2/3]
event sycl::_V1::queue::prefetch (const void * Ptr, size_t Count, const std::vector< event > & DepEvents, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
Parameters
Ptr is a USM pointer to the memory to be prefetched to the device.
Count is a number of bytes to be prefetched.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing prefetch operation.
Definition at line 777 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::prefetch(), and sycl::_V1::ext::oneapi::experimental::submit().
prefetch() [3/3]
event sycl::_V1::queue::prefetch (const void * Ptr, size_t Count, event DepEvent, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
Parameters
Ptr is a USM pointer to the memory to be prefetched to the device.
Count is a number of bytes to be prefetched.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing prefetch operation.
Definition at line 756 of file queue.hpp.
References sycl::_V1::handler::depends_on(), sycl::_V1::handler::prefetch(), and sycl::_V1::ext::oneapi::experimental::submit().
single_task() [1/6]
template<typename KernelName = detail::auto_name, typename KernelType > event sycl::_V1::queue::single_task (_KERNELFUNCPARAM(KernelFunc) , const detail::code_location & CodeLoc = detail::code_location::current()) inline
single_task version with a kernel represented as a lambda.
Parameters
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 1994 of file queue.hpp.
single_task() [2/6]
template<typename KernelName = detail::auto_name, typename KernelType > event sycl::_V1::queue::single_task (const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc) , const detail::code_location & CodeLoc = detail::code_location::current()) inline
single_task version with a kernel represented as a lambda.
Parameters
DepEvents is a vector of events that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 2086 of file queue.hpp.
single_task() [3/6]
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT > std::enable_if_t< ext::oneapi::experimental::is_property_list<PropertiesT>::value, event> sycl::_V1::queue::single_task (const std::vector< event > & DepEvents, PropertiesT Properties, _KERNELFUNCPARAM(KernelFunc) , const detail::code_location & CodeLoc = detail::code_location::current()) inline
single_task version with a kernel represented as a lambda.
Parameters
DepEvents is a vector of events that specifies the kernel dependencies
Properties is the kernel properties.
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 2057 of file queue.hpp.
References sycl::_V1::handler::depends_on(), and sycl::_V1::ext::oneapi::experimental::submit().
single_task() [4/6]
template<typename KernelName = detail::auto_name, typename KernelType > event sycl::_V1::queue::single_task (event DepEvent, _KERNELFUNCPARAM(KernelFunc) , const detail::code_location & CodeLoc = detail::code_location::current()) inline
single_task version with a kernel represented as a lambda.
Parameters
DepEvent is an event that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 2038 of file queue.hpp.
single_task() [5/6]
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT > std::enable_if_t< ext::oneapi::experimental::is_property_list<PropertiesT>::value, event> sycl::_V1::queue::single_task (event DepEvent, PropertiesT Properties, _KERNELFUNCPARAM(KernelFunc) , const detail::code_location & CodeLoc = detail::code_location::current()) inline
single_task version with a kernel represented as a lambda.
Parameters
DepEvent is an event that specifies the kernel dependencies
Properties is the kernel properties.
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 2011 of file queue.hpp.
References sycl::_V1::handler::depends_on(), and sycl::_V1::ext::oneapi::experimental::submit().
single_task() [6/6]
template<typename KernelName = detail::auto_name, typename KernelType , typename PropertiesT > std::enable_if_t< ext::oneapi::experimental::is_property_list<PropertiesT>::value, event> sycl::_V1::queue::single_task (PropertiesT Properties, _KERNELFUNCPARAM(KernelFunc) , const detail::code_location & CodeLoc = detail::code_location::current()) inline
single_task version with a kernel represented as a lambda.
Parameters
Properties is the kernel properties.
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 1969 of file queue.hpp.
References sycl::_V1::ext::oneapi::experimental::submit().
submit() [1/2]
template<typename T > std::enable_if_t<std::is_invocable_r_v<void, T, handler &>, event> sycl::_V1::queue::submit (T CGF, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Submits a command group function object to the queue, in order to be scheduled for execution on the device.
Parameters
CGF is a function object containing command group.
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object for the submitted command group.
Definition at line 340 of file queue.hpp.
References sycl::_V1::ext::oneapi::experimental::device_has.
Referenced by syclcompat::detail::combine_events(), ext_oneapi_copy(), ext_oneapi_copy2d(), ext_oneapi_fill2d(), ext_oneapi_memcpy2d(), ext_oneapi_memset2d(), ext_oneapi_submit_barrier(), syclcompat::detail::launch(), sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read(), sycl::_V1::ext::oneapi::experimental::submit(), sycl::_V1::ext::oneapi::experimental::submit_with_event(), and sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write().
submit() [2/2]
template<typename T > std::enable_if_t<std::is_invocable_r_v<void, T, handler &>, event> sycl::_V1::queue::submit (T CGF, queue & SecondaryQueue, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Submits a command group function object to the queue, in order to be scheduled for execution on the device.
On a kernel error, this command group function object is then scheduled for execution on a secondary queue.
Parameters
CGF is a function object containing command group.
SecondaryQueue is a fallback SYCL queue.
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object, which corresponds to the queue the command group is being enqueued on.
Definition at line 375 of file queue.hpp.
References sycl::_V1::ext::oneapi::experimental::device_has.
throw_asynchronous()
void sycl::_V1::queue::throw_asynchronous ()
Checks if any asynchronous errors have been produced by the queue and if so reports them to the async_handler passed on the queue construction.
If no async_handler was provided then asynchronous exceptions will be lost.
Definition at line 104 of file queue.cpp.
update_host()
template<typename T , int Dims, access_mode Mode, target Tgt, access::placeholder IsPlaceholder> event sycl::_V1::queue::update_host (accessor< T, Dims, Mode, Tgt, IsPlaceholder > Acc, const detail::code_location & CodeLoc = detail::code_location::current()) inline
Provides guarantees that the memory object accessed via Acc is updated on the host after operation is complete.
Parameters
Acc is a SYCL accessor that needs to be updated on host.
Returns
an event representing update_host operation.
Definition at line 2494 of file queue.hpp.
References sycl::_V1::handler::require(), sycl::_V1::ext::oneapi::experimental::submit(), and sycl::_V1::handler::update_host().
wait()
void sycl::_V1::queue::wait (const detail::code_location & CodeLoc = detail::code_location::current()) inline
Performs a blocking wait for the completion of all enqueued tasks in the queue.
Synchronous errors will be reported through SYCL exceptions.
Parameters
CodeLoc is the code location of the submit call (default argument)
Definition at line 429 of file queue.hpp.
wait_and_throw()
void sycl::_V1::queue::wait_and_throw (const detail::code_location & CodeLoc = detail::code_location::current()) inline
Performs a blocking wait for the completion of all enqueued tasks in the queue.
Synchronous errors will be reported through SYCL exceptions. Asynchronous errors will be passed to the async_handler passed to the queue on construction. If no async_handler was provided then asynchronous exceptions will be lost.
Parameters
CodeLoc is the code location of the submit call (default argument)
Definition at line 443 of file queue.hpp.
wait_and_throw_proxy()
void sycl::_V1::queue::wait_and_throw_proxy (const detail::code_location & CodeLoc)
Proxy method for wait_and_throw to forward the code location information to the implementation.
Definition at line 204 of file queue.cpp.
wait_proxy()
void sycl::_V1::queue::wait_proxy (const detail::code_location & CodeLoc)
Proxy method for wait to forward the code location information to the implementation.
Definition at line 200 of file queue.cpp.
Friends And Related Function Documentation
detail::createSyclObjFromImpl
template<class T > T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
get_native
template<backend BackendName, class SyclObjectT > auto get_native (const SyclObjectT & Obj) -> backend_return_t< BackendName, SyclObjectT > friend
Definition at line 136 of file backend.hpp.
Member Data Documentation
AsyncHandler
const device_selector const async_handler& sycl::_V1::queue::AsyncHandler
Definition at line 243 of file queue.hpp.
Referenced by queue().
DeviceSelector
const device_selector & sycl::_V1::queue::DeviceSelector
Definition at line 229 of file queue.hpp.
PropList [1/3]
const property_list& sycl::_V1::queue::PropList
Initial value:
= {})
      : queue(DeviceSelector.select_device(), detail::defaultAsyncHandler,
              PropList) {}
  __SYCL2020_DEPRECATED("SYCL 1.2.1 device selectors are deprecated. Please "
                        "use SYCL 2020 device selectors instead.")
  queue(const device_selector &DeviceSelector,
        const async_handler &AsyncHandler, const property_list &PropList = {})
      : queue(DeviceSelector.select_device(), AsyncHandler, PropList) {}
  explicit queue(const device &SyclDevice, const property_list &PropList = {})
      : queue(SyclDevice, detail::defaultAsyncHandler, PropList) {}
  explicit queue(const device &SyclDevice, const async_handler &AsyncHandler,
                 const property_list &PropList = {})
Definition at line 189 of file queue.hpp.
Referenced by queue().
PropList [2/3]
const device_selector const property_list& sycl::_V1::queue::PropList = {})
Definition at line 230 of file queue.hpp.
PropList [3/3]
const device_selector const async_handler const property_list& sycl::_V1::queue::PropList = {})
Definition at line 243 of file queue.hpp.
The documentation for this class was generated from the following files:
include/sycl/queue.hpp
include/sycl/ext/oneapi/bindless_images.hpp
include/sycl/ext/oneapi/memcpy2d.hpp
source/queue.cpp
source/queue_v3.cpp