DPC++ Runtime: sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims > Class Template Reference
sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims > Class Template Reference
#include <sycl/detail/cg_types.hpp>
Public Member Functions
HostKernel (KernelType Kernel)
void call (const NDRDescT &NDRDesc, HostProfilingInfo *HPI) override
char * getPtr () override
template<class ArgT = KernelArgType>
std::enable_if_t< std::is_same_v< ArgT, void > > runOnHost (const NDRDescT &)
template<class ArgT = KernelArgType>
std::enable_if_t< std::is_same_v< ArgT, sycl::id< Dims > > > runOnHost (const NDRDescT &NDRDesc)
template<class ArgT = KernelArgType>
std::enable_if_t< std::is_same_v< ArgT, item< Dims, false > > > runOnHost (const NDRDescT &NDRDesc)
template<class ArgT = KernelArgType>
std::enable_if_t< std::is_same_v< ArgT, item< Dims, true > > > runOnHost (const NDRDescT &NDRDesc)
template<class ArgT = KernelArgType>
std::enable_if_t< std::is_same_v< ArgT, nd_item< Dims > > > runOnHost (const NDRDescT &NDRDesc)
template<typename ArgT = KernelArgType>
std::enable_if_t< std::is_same_v< ArgT, sycl::group< Dims > > > runOnHost (const NDRDescT &NDRDesc)
~HostKernel ()=default
Public Member Functions inherited from sycl::_V1::detail::HostKernelBase
virtual ~HostKernelBase ()=default
Friends
class sycl::handler
Detailed Description
template<class KernelType, class KernelArgType, int Dims>
class sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >
Definition at line 263 of file cg_types.hpp.
Constructor & Destructor Documentation
HostKernel()
template<class KernelType , class KernelArgType , int Dims> sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::HostKernel (KernelType Kernel) inline
Definition at line 271 of file cg_types.hpp.
~HostKernel()
template<class KernelType , class KernelArgType , int Dims> sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::~HostKernel () default
Member Function Documentation
call()
template<class KernelType , class KernelArgType , int Dims> void sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::call (const NDRDescT & NDRDesc, HostProfilingInfo * HPI) inline override virtual
Implements sycl::_V1::detail::HostKernelBase.
Definition at line 272 of file cg_types.hpp.
References sycl::_V1::detail::NDRDescT::Dims, sycl::_V1::detail::HostProfilingInfo::end(), sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::if(), sycl::_V1::detail::NDRDescT::LocalSize, sycl::_V1::detail::NDRDescT::NumWorkGroups, sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost(), sycl::_V1::detail::NDRDescT::set(), and sycl::_V1::detail::HostProfilingInfo::start().
getPtr()
template<class KernelType , class KernelArgType , int Dims> char* sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::getPtr () inline override virtual
Implements sycl::_V1::detail::HostKernelBase.
Definition at line 299 of file cg_types.hpp.
runOnHost() [1/6]
template<class KernelType , class KernelArgType , int Dims> template<class ArgT = KernelArgType> std::enable_if_t<std::is_same_v<ArgT, void> > sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost (const NDRDescT &) inline
Definition at line 303 of file cg_types.hpp.
References sycl::_V1::detail::runKernelWithoutArg().
Referenced by sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::call().
runOnHost() [2/6]
template<class KernelType , class KernelArgType , int Dims> template<class ArgT = KernelArgType> std::enable_if_t<std::is_same_v<ArgT, sycl::id<Dims> > > sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 309 of file cg_types.hpp.
References sycl::_V1::detail::NDRDescT::GlobalOffset, sycl::_V1::detail::NDRDescT::GlobalSize, and sycl::_V1::detail::NDLoop< NDims >::iterate().
runOnHost() [3/6]
template<class KernelType , class KernelArgType , int Dims> template<class ArgT = KernelArgType> std::enable_if_t<std::is_same_v<ArgT, item<Dims, false> > > sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 334 of file cg_types.hpp.
References sycl::_V1::detail::NDRDescT::GlobalSize.
runOnHost() [4/6]
template<class KernelType , class KernelArgType , int Dims> template<class ArgT = KernelArgType> std::enable_if_t<std::is_same_v<ArgT, item<Dims, true> > > sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 351 of file cg_types.hpp.
References sycl::_V1::detail::NDRDescT::GlobalOffset, sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::detail::NDLoop< NDims >::iterate(), and sycl::_V1::detail::runKernelWithArg().
runOnHost() [5/6]
template<class KernelType , class KernelArgType , int Dims> template<class ArgT = KernelArgType> std::enable_if_t<std::is_same_v<ArgT, nd_item<Dims> > > sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 376 of file cg_types.hpp.
References sycl::_V1::detail::NDRDescT::GlobalOffset, sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::detail::NDLoop< NDims >::iterate(), and sycl::_V1::detail::NDRDescT::LocalSize.
runOnHost() [6/6]
template<class KernelType , class KernelArgType , int Dims> template<typename ArgT = KernelArgType> std::enable_if_t<std::is_same_v<ArgT, sycl::group<Dims> > > sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 418 of file cg_types.hpp.
References sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::detail::NDLoop< NDims >::iterate(), and sycl::_V1::detail::NDRDescT::LocalSize.
Friends And Related Function Documentation
sycl::handler
template<class KernelType , class KernelArgType , int Dims> friend class sycl::handler friend
Definition at line 268 of file cg_types.hpp.
The documentation for this class was generated from the following file:
include/sycl/detail/cg_types.hpp