DPC++ Runtime: sycl::_V1::detail::CircularBuffer< T > Class Template Reference
sycl::_V1::detail::CircularBuffer< T > Class Template Reference
#include <detail/circular_buffer.hpp>
Public Types
using value_type = T
using pointer = T *
using const_pointer = const T *
using reference = T &
using const_reference = const T &
using iterator = typename std::deque< T >::iterator
using const_iterator = typename std::deque< T >::const_iterator
Public Member Functions
CircularBuffer (std::size_t Capacity)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
reference operator[] (std::size_t Idx)
const_reference operator[] (std::size_t Idx) const
std::size_t size () const
std::size_t capacity () const
bool empty () const
bool full () const
void push_back (T Val)
void push_front (T Val)
void pop_back ()
void pop_front ()
void erase (const_iterator Pos)
void erase (const_iterator First, const_iterator Last)
void clear ()
Detailed Description
template<typename T>
class sycl::_V1::detail::CircularBuffer< T >
Definition at line 23 of file circular_buffer.hpp.
Member Typedef Documentation
const_iterator
template<typename T > using sycl::_V1::detail::CircularBuffer< T >::const_iterator = typename std::deque<T>::const_iterator
Definition at line 34 of file circular_buffer.hpp.
const_pointer
template<typename T > using sycl::_V1::detail::CircularBuffer< T >::const_pointer = const T *
Definition at line 29 of file circular_buffer.hpp.
const_reference
template<typename T > using sycl::_V1::detail::CircularBuffer< T >::const_reference = const T &
Definition at line 31 of file circular_buffer.hpp.
iterator
template<typename T > using sycl::_V1::detail::CircularBuffer< T >::iterator = typename std::deque<T>::iterator
Definition at line 33 of file circular_buffer.hpp.
pointer
template<typename T > using sycl::_V1::detail::CircularBuffer< T >::pointer = T *
Definition at line 28 of file circular_buffer.hpp.
reference
template<typename T > using sycl::_V1::detail::CircularBuffer< T >::reference = T &
Definition at line 30 of file circular_buffer.hpp.
value_type
template<typename T > using sycl::_V1::detail::CircularBuffer< T >::value_type = T
Definition at line 27 of file circular_buffer.hpp.
Constructor & Destructor Documentation
CircularBuffer()
template<typename T > sycl::_V1::detail::CircularBuffer< T >::CircularBuffer (std::size_t Capacity) inline explicit
Definition at line 25 of file circular_buffer.hpp.
Member Function Documentation
back() [1/2]
template<typename T > reference sycl::_V1::detail::CircularBuffer< T >::back () inline
Definition at line 48 of file circular_buffer.hpp.
back() [2/2]
template<typename T > const_reference sycl::_V1::detail::CircularBuffer< T >::back () const inline
Definition at line 50 of file circular_buffer.hpp.
begin() [1/2]
template<typename T > iterator sycl::_V1::detail::CircularBuffer< T >::begin () inline
Definition at line 36 of file circular_buffer.hpp.
Referenced by sycl::_V1::detail::LeavesCollection::begin(), sycl::_V1::detail::LeavesCollection::cbegin(), sycl::_V1::detail::LeavesCollection::remove(), and sycl::_V1::detail::LeavesCollection::toVector().
begin() [2/2]
template<typename T > const_iterator sycl::_V1::detail::CircularBuffer< T >::begin () const inline
Definition at line 38 of file circular_buffer.hpp.
capacity()
template<typename T > std::size_t sycl::_V1::detail::CircularBuffer< T >::capacity () const inline
Definition at line 58 of file circular_buffer.hpp.
Referenced by sycl::_V1::detail::LeavesCollection::genericCommandsCapacity().
clear()
template<typename T > void sycl::_V1::detail::CircularBuffer< T >::clear () inline
Definition at line 86 of file circular_buffer.hpp.
empty()
template<typename T > bool sycl::_V1::detail::CircularBuffer< T >::empty () const inline
Definition at line 60 of file circular_buffer.hpp.
Referenced by sycl::_V1::detail::LeavesCollection::begin(), and sycl::_V1::detail::LeavesCollection::cbegin().
end() [1/2]
template<typename T > iterator sycl::_V1::detail::CircularBuffer< T >::end () inline
Definition at line 40 of file circular_buffer.hpp.
Referenced by sycl::_V1::detail::LeavesCollection::remove(), and sycl::_V1::detail::LeavesCollection::toVector().
end() [2/2]
template<typename T > const_iterator sycl::_V1::detail::CircularBuffer< T >::end () const inline
Definition at line 42 of file circular_buffer.hpp.
erase() [1/2]
template<typename T > void sycl::_V1::detail::CircularBuffer< T >::erase (const_iterator First, const_iterator Last) inline
Definition at line 82 of file circular_buffer.hpp.
erase() [2/2]
template<typename T > void sycl::_V1::detail::CircularBuffer< T >::erase (const_iterator Pos) inline
Definition at line 80 of file circular_buffer.hpp.
Referenced by sycl::_V1::detail::LeavesCollection::remove().
front() [1/2]
template<typename T > reference sycl::_V1::detail::CircularBuffer< T >::front () inline
Definition at line 44 of file circular_buffer.hpp.
front() [2/2]
template<typename T > const_reference sycl::_V1::detail::CircularBuffer< T >::front () const inline
Definition at line 46 of file circular_buffer.hpp.
full()
template<typename T > bool sycl::_V1::detail::CircularBuffer< T >::full () const inline
Definition at line 62 of file circular_buffer.hpp.
operator[]() [1/2]
template<typename T > reference sycl::_V1::detail::CircularBuffer< T >::operator[] (std::size_t Idx) inline
Definition at line 52 of file circular_buffer.hpp.
operator[]() [2/2]
template<typename T > const_reference sycl::_V1::detail::CircularBuffer< T >::operator[] (std::size_t Idx) const inline
Definition at line 54 of file circular_buffer.hpp.
pop_back()
template<typename T > void sycl::_V1::detail::CircularBuffer< T >::pop_back () inline
Definition at line 76 of file circular_buffer.hpp.
pop_front()
template<typename T > void sycl::_V1::detail::CircularBuffer< T >::pop_front () inline
Definition at line 78 of file circular_buffer.hpp.
push_back()
template<typename T > void sycl::_V1::detail::CircularBuffer< T >::push_back (T Val) inline
Definition at line 64 of file circular_buffer.hpp.
push_front()
template<typename T > void sycl::_V1::detail::CircularBuffer< T >::push_front (T Val) inline
Definition at line 70 of file circular_buffer.hpp.
size()
template<typename T > std::size_t sycl::_V1::detail::CircularBuffer< T >::size () const inline
Definition at line 56 of file circular_buffer.hpp.
Referenced by sycl::_V1::detail::LeavesCollection::toVector().
The documentation for this class was generated from the following file:
source/detail/circular_buffer.hpp