DPC++ Runtime: sycl::_V1::detail::Scheduler::GraphProcessor Class Reference
sycl::_V1::detail::Scheduler::GraphProcessor Class Reference
DPC++ Execution Graph
Graph Processor provides interfaces for enqueueing commands and their dependencies to the underlying runtime.
#include <detail/scheduler/scheduler.hpp>
Static Public Member Functions
static void waitForEvent (const EventImplPtr &Event, ReadLockT &GraphReadLock, std::vector< Command * > &ToCleanUp, bool LockTheLock=true, bool *Success=nullptr)
Waits for the command, associated with Event passed, is completed.
static bool enqueueCommand (Command *Cmd, ReadLockT &GraphReadLock, EnqueueResultT &EnqueueResult, std::vector< Command * > &ToCleanUp, Command *RootCommand, BlockingT Blocking=NON_BLOCKING)
Enqueues the command and all its dependencies.
static bool handleBlockingCmd (Command *Cmd, EnqueueResultT &EnqueueResult, Command *RootCommand, BlockingT Blocking)
Check if successfully enqueued command is expected to be blocking for the dependent commands before its completion.
Detailed Description
Graph Processor provides interfaces for enqueueing commands and their dependencies to the underlying runtime.
Member functions of this class do not modify the graph.
Command enqueueing
Commands are enqueued whenever they come to the Scheduler. Each command has enqueue method which takes vector of events that represents dependencies and returns event which represents the command. GraphProcessor performs topological sort to get the order in which commands have to be enqueued. Then it enqueues each command, passing a vector of events that this command needs to wait on. If an error happens during command enqueue, the whole process is stopped, the faulty command is propagated back to the Scheduler.
The command with dependencies that belong to a context different from its own can't be enqueued directly (limitation of OpenCL runtime). Instead, for each dependency, a proxy event is created in the target context and linked using OpenCL callback mechanism with original one. For example, the following SYCL code:
// The ContextA and ContextB are different OpenCL contexts
sycl::queue Q1(ContextA);
sycl::queue Q2(ContextB);
Q1.submit(Task1);
Q2.submit(Task2);
is translated to the following OCL API calls:
 void event_completion_callback(void *data) {
   // Change status of event to complete.
   clSetEventStatus((cl_event *)data, CL_COMPLETE); // Scope of Context2
 }
// Enqueue TASK1
EventTask1 = clEnqueueNDRangeKernel(Q1, TASK1, ..); // Scope of Context1
// Read memory to host
ReadMem = clEnqueueReadBuffer(A, .., /*Deps=*/EventTask1); // Scope of
// Context1
// Create user event with initial status "not completed".
UserEvent = clCreateUserEvent(Context2); // Scope of Context2
// Ask OpenCL to call callback with UserEvent as data when "read memory
// to host" operation is completed
clSetEventCallback(ReadMem, event_completion_callback,
                   /*data=*/UserEvent); // Scope of Context1
// Enqueue write memory from host, block it on user event
// It will be unblocked when we change UserEvent status to completed in
// callback.
WriteMem =
   clEnqueueWriteBuffer(A, .., /*Dep=*/UserEvent); // Scope of Context2
// Enqueue TASK2
EventTask2 =
   clEnqueueNDRangeKernel(TASK, .., /*Dep=*/WriteMem); // Scope of
   // Context2
The alternative approach that has been considered is to have separate dispatcher thread that would wait for all events from the Context other then target Context to complete and then enqueue command with dependencies from target Context only. Alternative approach makes code significantly more complex and can hurt performance on CPU device vs chosen approach with callbacks.
Definition at line 895 of file scheduler.hpp.
Member Function Documentation
enqueueCommand()
bool sycl::_V1::detail::Scheduler::GraphProcessor::enqueueCommand (Command * Cmd, ReadLockT & GraphReadLock, EnqueueResultT & EnqueueResult, std::vector< Command * > & ToCleanUp, Command * RootCommand, BlockingT Blocking = NON_BLOCKING) static
Enqueues the command and all its dependencies.
Parameters
EnqueueResult is set to specific status if enqueue failed.
ToCleanUp container for commands that can be cleaned up.
RootCommand top level command enqueueCommand is called for.
Returns
true if the command is successfully enqueued.
The function may unlock and lock GraphReadLock as needed. Upon return the lock is left in locked state.
Definition at line 72 of file graph_processor.cpp.
References sycl::_V1::detail::Scheduler::cancelFusion(), sycl::_V1::detail::Command::enqueue(), sycl::_V1::detail::Scheduler::getInstance(), sycl::_V1::detail::Command::getPreparedDepsEvents(), sycl::_V1::detail::Command::getPreparedHostDepsEvents(), sycl::_V1::detail::Command::isEnqueueBlocked(), sycl::_V1::detail::Command::isSuccessfullyEnqueued(), and sycl::_V1::detail::EnqueueResultT::SyclEnqueueBlocked.
Referenced by sycl::_V1::detail::Scheduler::addCommandGraphUpdate(), sycl::_V1::detail::Scheduler::addCopyBack(), sycl::_V1::detail::Scheduler::addHostAccessor(), sycl::_V1::detail::Scheduler::enqueueCommandForCG(), sycl::_V1::detail::Scheduler::enqueueLeavesOfReqUnlocked(), sycl::_V1::detail::Scheduler::enqueueUnblockedCommands(), waitForEvent(), and sycl::_V1::detail::Scheduler::waitForRecordToFinish().
handleBlockingCmd()
bool sycl::_V1::detail::Scheduler::GraphProcessor::handleBlockingCmd (Command * Cmd, EnqueueResultT & EnqueueResult, Command * RootCommand, BlockingT Blocking) static
Check if successfully enqueued command is expected to be blocking for the dependent commands before its completion.
Parameters
Cmd command that is currently enqueued.
EnqueueResult enqueue status to be updated if command is blocking.
RootCommand top level command enqueueCommand is called for. If Cmd == RootCommand we should not report command as blocking as no dependencies to be blocked yet.
Blocking mode for enqueue, we do not report command as blocking if it is true and allow to wait for command completion in enqueueImp.
Returns
true if we should continue enqueue process.
Definition at line 50 of file graph_processor.cpp.
References sycl::_V1::detail::Command::addBlockedUserUnique(), sycl::_V1::detail::Command::copySubmissionCodeLocation(), sycl::_V1::detail::Command::getEvent(), sycl::_V1::detail::Command::isBlocking(), sycl::_V1::detail::Command::MBlockedUsersMutex, and sycl::_V1::detail::EnqueueResultT::SyclEnqueueBlocked.
waitForEvent()
void sycl::_V1::detail::Scheduler::GraphProcessor::waitForEvent (const EventImplPtr & Event, ReadLockT & GraphReadLock, std::vector< Command * > & ToCleanUp, bool LockTheLock = true, bool * Success = nullptr) static
Waits for the command, associated with Event passed, is completed.
Parameters
GraphReadLock read-lock which is already acquired for reading
ToCleanUp container for commands that can be cleaned up.
LockTheLock selects if graph lock should be locked upon return
Success is an optional parameter that, when set to a non-null pointer, indicates that failure is a valid outcome for this wait (e.g., in case of a non-blocking read from a pipe), and the value it's pointing to is then set according to the outcome.
The function may unlock and lock GraphReadLock as needed. Upon return the lock is left in locked state if and only if LockTheLock is true.
Definition at line 24 of file graph_processor.cpp.
References sycl::_V1::detail::BLOCKING, enqueueCommand(), sycl::_V1::detail::getCommand(), sycl::_V1::detail::Command::getEvent(), sycl::_V1::detail::EnqueueResultT::MResult, and sycl::_V1::detail::EnqueueResultT::SyclEnqueueFailed.
Referenced by sycl::_V1::detail::Scheduler::waitForEvent(), and sycl::_V1::detail::Scheduler::waitForRecordToFinish().
The documentation for this class was generated from the following files:
source/detail/scheduler/scheduler.hpp
source/detail/scheduler/graph_processor.cpp