DPC++ Runtime: cl::sycl::range< dimensions > Class Template Reference
cl::sycl::range< dimensions > Class Template Reference
DPC++ User API
Defines the iteration domain of either a single work-group in a parallel dispatch, or the overall dimensions of the dispatch.
#include <CL/sycl/buffer.hpp>
Public Member Functions
template<int N = dimensions>
range (typename std::enable_if<(N==1), size_t >::type dim0)
template<int N = dimensions>
range (typename std::enable_if<(N==2), size_t >::type dim0, size_t dim1)
template<int N = dimensions>
range (typename std::enable_if<(N==3), size_t >::type dim0, size_t dim1, size_t dim2)
operator id< dimensions > () const
size_t size () const
range (const range< dimensions > &rhs)=default
range (range< dimensions > &&rhs)=default
range< dimensions > & operator= (const range< dimensions > &rhs)=default
range< dimensions > & operator= (range< dimensions > &&rhs)=default
range ()=delete
Public Member Functions inherited from cl::sycl::detail::array< dimensions >
template<int N = dimensions>
array (typename std::enable_if<(N==1), size_t >::type dim0=0)
template<int N = dimensions>
array (typename std::enable_if<(N==2), size_t >::type dim0, size_t dim1)
template<int N = dimensions, detail::enable_if_t<(N==2), size_t > = 0>
array ()
template<int N = dimensions>
array (typename std::enable_if<(N==3), size_t >::type dim0, size_t dim1, size_t dim2)
template<int N = dimensions, detail::enable_if_t<(N==3), size_t > = 0>
array ()
operator cl::sycl::id< dimensions > () const
operator cl::sycl::range< dimensions > () const
size_t get (int dimension) const
size_t & operator[] (int dimension)
size_t operator[] (int dimension) const
array (const array< dimensions > &rhs)=default
array (array< dimensions > &&rhs)=default
array< dimensions > & operator= (const array< dimensions > &rhs)=default
array< dimensions > & operator= (array< dimensions > &&rhs)=default
bool operator== (const array< dimensions > &rhs) const
bool operator!= (const array< dimensions > &rhs) const
Additional Inherited Members
Protected Member Functions inherited from cl::sycl::detail::array< dimensions >
ALWAYS_INLINE void check_dimension (int dimension) const
Protected Attributes inherited from cl::sycl::detail::array< dimensions >
size_t common_array [dimensions]
Detailed Description
template<int dimensions = 1>
class cl::sycl::range< dimensions >
Defines the iteration domain of either a single work-group in a parallel dispatch, or the overall dimensions of the dispatch.
Definition at line 21 of file buffer.hpp.
Constructor & Destructor Documentation
range() [1/6]
template<int dimensions = 1> template<int N = dimensions> cl::sycl::range< dimensions >::range (typename std::enable_if<(N==1), size_t >::type dim0) inline
Definition at line 34 of file range.hpp.
range() [2/6]
template<int dimensions = 1> template<int N = dimensions> cl::sycl::range< dimensions >::range (typename std::enable_if<(N==2), size_t >::type dim0, size_t dim1) inline
Definition at line 39 of file range.hpp.
range() [3/6]
template<int dimensions = 1> template<int N = dimensions> cl::sycl::range< dimensions >::range (typename std::enable_if<(N==3), size_t >::type dim0, size_t dim1, size_t dim2) inline
Definition at line 45 of file range.hpp.
range() [4/6]
template<int dimensions = 1> cl::sycl::range< dimensions >::range (const range< dimensions > & rhs) default
range() [5/6]
template<int dimensions = 1> cl::sycl::range< dimensions >::range (range< dimensions > && rhs) default
range() [6/6]
template<int dimensions = 1> cl::sycl::range< dimensions >::range () delete
Member Function Documentation
operator id< dimensions >()
template<int dimensions = 1> cl::sycl::range< dimensions >::operator id< dimensions > () const inline explicit
Definition at line 49 of file range.hpp.
operator=() [1/2]
template<int dimensions = 1> range<dimensions>& cl::sycl::range< dimensions >::operator= (const range< dimensions > & rhs) default
operator=() [2/2]
template<int dimensions = 1> range<dimensions>& cl::sycl::range< dimensions >::operator= (range< dimensions > && rhs) default
size()
template<int dimensions = 1> size_t cl::sycl::range< dimensions >::size () const inline
Definition at line 57 of file range.hpp.
Referenced by cl::sycl::detail::copyD2D(), cl::sycl::detail::doOverlap(), cl::sycl::detail::MemoryManager::fill(), cl::sycl::private_memory< T, Dimensions >::private_memory(), cl::sycl::buffer< char, 1 >::reinterpret(), cl::sycl::detail::ReverseRangeDimensionsForKernel(), and cl::sycl::detail::updateOffset().
The documentation for this class was generated from the following files:
include/CL/sycl/buffer.hpp
include/CL/sycl/range.hpp