DPC++ Runtime: sycl::_V1::detail::event_impl Class Reference
sycl::_V1::detail::event_impl Class Reference
#include <detail/event_impl.hpp>
Public Types
enum HostEventState : int { HES_NotComplete = 0 , HES_Complete , HES_Discarded }
Public Member Functions
event_impl (std::optional< HostEventState > State=HES_Complete)
Constructs a ready SYCL event.
event_impl (sycl::detail::pi::PiEvent Event, const context &SyclContext)
Constructs an event instance from a plug-in event handle.
event_impl (const QueueImplPtr &Queue)
bool is_host ()
Checks if this event is a SYCL host event.
void wait (std::shared_ptr< sycl::detail::event_impl > Self, bool *Success=nullptr)
Waits for the event.
void wait_and_throw (std::shared_ptr< sycl::detail::event_impl > Self)
Waits for the event.
template<typename Param >
Param::return_type get_profiling_info ()
Queries this event for profiling information.
template<typename Param >
Param::return_type get_info ()
Queries this SYCL event for information.
template<typename Param >
Param::return_type get_backend_info () const
Queries this SYCL event for SYCL backend-specific information.
~event_impl ()
void waitInternal (bool *Success=nullptr)
Waits for the event with respect to device type.
void setComplete ()
Marks this event as completed.
sycl::detail::pi::PiEvent & getHandleRef ()
Returns raw interoperability event handle.
const sycl::detail::pi::PiEvent & getHandleRef () const
Returns raw interoperability event handle.
const ContextImplPtr & getContextImpl ()
Returns context that is associated with this event.
const PluginPtr & getPlugin ()
void setContextImpl (const ContextImplPtr &Context)
Associate event with the context.
void setStateIncomplete ()
Clear the event state.
void * getCommand ()
Returns command that is associated with the event.
void setCommand (void *Command)
Associates this event with the command.
HostProfilingInfo * getHostProfilingInfo ()
Returns host profiling information.
pi_native_handle getNative ()
Gets the native handle of the SYCL event.
std::vector< std::shared_ptr< event_impl > > & getPreparedDepsEvents ()
Returns vector of event dependencies.
std::vector< std::shared_ptr< event_impl > > & getPreparedHostDepsEvents ()
Returns vector of host event dependencies.
std::vector< EventImplPtr > getWaitList ()
Returns vector of event_impl that this event_impl depends on.
void flushIfNeeded (const QueueImplPtr &UserQueue)
Performs a flush on the queue associated with this event if the user queue is different and the task associated with this event hasn't been submitted to the device yet.
void cleanupDependencyEvents ()
Cleans dependencies of this event_impl.
void cleanDepEventsThroughOneLevel ()
Cleans dependencies of this event's dependencies.
bool isDiscarded () const
Checks if this event is discarded by SYCL implementation.
QueueImplPtr getWorkerQueue ()
Returns worker queue for command.
void setWorkerQueue (const QueueImplPtr &WorkerQueue)
Sets worker queue for command.
void setSubmittedQueue (const QueueImplPtr &SubmittedQueue)
Sets original queue used for submission.
void associateWithQueue (const QueueImplPtr &Queue)
Associate event with provided queue.
bool isNOP ()
Indicates if this event is not associated with any command and doesn't have native handle.
void setSubmissionTime ()
Calling this function queries the current device timestamp and sets it as submission time for the command associated with this event.
void setHostEnqueueTime ()
Calling this function to capture the host timestamp to use profiling base time.
uint64_t getSubmissionTime ()
QueueImplPtr getSubmittedQueue () const
bool isInitialized () const noexcept
Checks if an event is in a fully intialized state.
bool isCompleted ()
Checks if this event is complete.
void attachEventToComplete (const EventImplPtr &Event)
bool isContextInitialized () const noexcept
ContextImplPtr getContextImplPtr ()
void setSyncPoint (sycl::detail::pi::PiExtSyncPoint SyncPoint)
sycl::detail::pi::PiExtSyncPoint getSyncPoint () const
void setCommandGraph (std::shared_ptr< ext::oneapi::experimental::detail::graph_impl > Graph)
std::shared_ptr< ext::oneapi::experimental::detail::graph_impl > getCommandGraph () const
void setEventFromSubmittedExecCommandBuffer (bool value)
bool isEventFromSubmittedExecCommandBuffer () const
void setProfilingEnabled (bool Value)
void setCommandBufferCommand (sycl::detail::pi::PiExtCommandBufferCommand Command)
sycl::detail::pi::PiExtCommandBufferCommand getCommandBufferCommand () const
const std::vector< EventImplPtr > & getPostCompleteEvents () const
Protected Member Functions
void * instrumentationProlog (std::string &Name, int32_t StreamID, uint64_t &instance_id) const
void instrumentationEpilog (void *TelementryEvent, const std::string &Name, int32_t StreamID, uint64_t IId) const
void checkProfilingPreconditions () const
void ensureContextInitialized ()
Protected Attributes
bool MIsInitialized = true
bool MIsContextInitialized = false
sycl::detail::pi::PiEvent MEvent = nullptr
uint64_t MSubmitTime = 0
uint64_t MHostBaseTime = 0
ContextImplPtr MContext
bool MHostEvent = true
std::unique_ptr< HostProfilingInfo > MHostProfilingInfo
void * MCommand = nullptr
std::weak_ptr< queue_impl > MQueue
bool MIsProfilingEnabled = false
bool MFallbackProfiling = false
std::weak_ptr< queue_impl > MWorkerQueue
std::weak_ptr< queue_impl > MSubmittedQueue
std::vector< EventImplPtr > MPreparedDepsEvents
Dependency events prepared for waiting by backend.
std::vector< EventImplPtr > MPreparedHostDepsEvents
std::vector< EventImplPtr > MPostCompleteEvents
std::atomic< bool > MIsFlushed = false
Indicates that the task associated with this event has been submitted by the queue to the device.
std::atomic< int > MState
std::mutex MMutex
std::condition_variable cv
std::weak_ptr< ext::oneapi::experimental::detail::graph_impl > MGraph
Store the command graph associated with this event, if any.
bool MEventFromSubmittedExecCommandBuffer = false
Indicates that the event results from a command graph submission.
sycl::detail::pi::PiExtSyncPoint MSyncPoint
sycl::detail::pi::PiExtCommandBufferCommand MCommandBufferCommand = nullptr
Friends
std::vector< sycl::detail::pi::PiEvent > getOrWaitEvents (std::vector< sycl::event > DepEvents, std::shared_ptr< sycl::detail::context_impl > Context)
Detailed Description
Definition at line 38 of file event_impl.hpp.
Member Enumeration Documentation
HostEventState
enum sycl::_V1::detail::event_impl::HostEventState : int
Enumerator
HES_NotComplete
HES_Complete
HES_Discarded
Definition at line 40 of file event_impl.hpp.
Constructor & Destructor Documentation
event_impl() [1/3]
sycl::_V1::detail::event_impl::event_impl (std::optional< HostEventState > State = HES_Complete) inline
Constructs a ready SYCL event.
If the constructed SYCL event is waited on it will complete immediately. Normally constructs a host event, use std::nullopt to instead instantiate a device event.
Definition at line 51 of file event_impl.hpp.
References sycl::_V1::detail::SYCLConfig< Config >::get().
event_impl() [2/3]
sycl::_V1::detail::event_impl::event_impl (sycl::detail::pi::PiEvent Event, const context & SyclContext)
Constructs an event instance from a plug-in event handle.
The SyclContext must match the plug-in context associated with the ClEvent.
Parameters
Event is a valid instance of plug-in event.
SyclContext is an instance of SYCL context.
Definition at line 145 of file event_impl.cpp.
References sycl::_V1::detail::codeToString(), getPlugin(), MContext, MEvent, PI_EVENT_INFO_CONTEXT, and piEventGetInfo().
event_impl() [3/3]
sycl::_V1::detail::event_impl::event_impl (const QueueImplPtr & Queue)
Definition at line 170 of file event_impl.cpp.
References associateWithQueue(), and setContextImpl().
~event_impl()
sycl::_V1::detail::event_impl::~event_impl ()
Definition at line 56 of file event_impl.cpp.
References getPlugin(), MEvent, and piEventRelease().
Member Function Documentation
associateWithQueue()
void sycl::_V1::detail::event_impl::associateWithQueue (const QueueImplPtr & Queue)
Associate event with provided queue.
Returns
Definition at line 175 of file event_impl.cpp.
References sycl::_V1::detail::codeToString(), HES_Complete, HES_NotComplete, MFallbackProfiling, MHostProfilingInfo, MIsProfilingEnabled, MQueue, and MState.
Referenced by event_impl().
attachEventToComplete()
void sycl::_V1::detail::event_impl::attachEventToComplete (const EventImplPtr & Event) inline
Definition at line 285 of file event_impl.hpp.
References MMutex, and MPostCompleteEvents.
checkProfilingPreconditions()
void sycl::_V1::detail::event_impl::checkProfilingPreconditions () const protected
Definition at line 285 of file event_impl.cpp.
References sycl::_V1::make_error_code(), MIsProfilingEnabled, and MQueue.
cleanDepEventsThroughOneLevel()
void sycl::_V1::detail::event_impl::cleanDepEventsThroughOneLevel ()
Cleans dependencies of this event's dependencies.
Definition at line 550 of file event_impl.cpp.
References MMutex, MPreparedDepsEvents, and MPreparedHostDepsEvents.
cleanupDependencyEvents()
void sycl::_V1::detail::event_impl::cleanupDependencyEvents ()
Cleans dependencies of this event_impl.
Definition at line 544 of file event_impl.cpp.
References MMutex, MPreparedDepsEvents, and MPreparedHostDepsEvents.
ensureContextInitialized()
void sycl::_V1::detail::event_impl::ensureContextInitialized () protected
Definition at line 36 of file event_impl.cpp.
References sycl::_V1::detail::Scheduler::getDefaultHostQueue(), sycl::_V1::detail::queue_impl::getDefaultOrNew(), sycl::_V1::detail::Scheduler::getInstance(), sycl::_V1::detail::getSyclObjImpl(), MHostEvent, MIsContextInitialized, and setContextImpl().
Referenced by getContextImpl(), getContextImplPtr(), getNative(), and getPlugin().
flushIfNeeded()
void sycl::_V1::detail::event_impl::flushIfNeeded (const QueueImplPtr & UserQueue)
Performs a flush on the queue associated with this event if the user queue is different and the task associated with this event hasn't been submitted to the device yet.
Definition at line 517 of file event_impl.cpp.
References getPlugin(), MEvent, MIsFlushed, MQueue, PI_EVENT_INFO_COMMAND_EXECUTION_STATUS, PI_EVENT_QUEUED, piEventGetInfo(), and piQueueFlush().
get_backend_info()
template<typename Param > Param::return_type sycl::_V1::detail::event_impl::get_backend_info () const
Queries this SYCL event for SYCL backend-specific information.
Returns
depends on information being queried.
get_info()
template<typename Param > Param::return_type sycl::_V1::detail::event_impl::get_info ()
Queries this SYCL event for information.
Returns
depends on the information being requested.
get_profiling_info()
template<typename Param > Param::return_type sycl::_V1::detail::event_impl::get_profiling_info ()
Queries this event for profiling information.
If the requested info is not available when this member function is called due to incompletion of command groups associated with the event, then the call to this member function will block until the requested info is available. If the queue which submitted the command group this event is associated with was not constructed with the property::queue::enable_profiling property, an invalid_object_error SYCL exception is thrown.
Returns
depends on template parameter.
getCommand()
void* sycl::_V1::detail::event_impl::getCommand () inline
Returns command that is associated with the event.
Scheduler mutex must be locked in read mode when this is called.
Returns
a generic pointer to Command object instance.
Definition at line 173 of file event_impl.hpp.
References MCommand.
getCommandBufferCommand()
sycl::detail::pi::PiExtCommandBufferCommand sycl::_V1::detail::event_impl::getCommandBufferCommand () const inline
Definition at line 333 of file event_impl.hpp.
References MCommandBufferCommand.
getCommandGraph()
std::shared_ptr<ext::oneapi::experimental::detail::graph_impl> sycl::_V1::detail::event_impl::getCommandGraph () const inline
Definition at line 312 of file event_impl.hpp.
References MGraph.
getContextImpl()
const ContextImplPtr & sycl::_V1::detail::event_impl::getContextImpl ()
Returns context that is associated with this event.
Returns
a shared pointer to a valid context_impl.
Definition at line 127 of file event_impl.cpp.
References ensureContextInitialized(), and MContext.
getContextImplPtr()
ContextImplPtr sycl::_V1::detail::event_impl::getContextImplPtr () inline
Definition at line 292 of file event_impl.hpp.
References ensureContextInitialized(), and MContext.
getHandleRef() [1/2]
sycl::detail::pi::PiEvent & sycl::_V1::detail::event_impl::getHandleRef ()
Returns raw interoperability event handle.
Returned reference will be] invalid if event_impl was destroyed.
Returns
a reference to an instance of plug-in event handle.
Definition at line 125 of file event_impl.cpp.
References MEvent.
Referenced by getNative(), and isNOP().
getHandleRef() [2/2]
const sycl::detail::pi::PiEvent & sycl::_V1::detail::event_impl::getHandleRef () const
Returns raw interoperability event handle.
Returned reference will be] invalid if event_impl was destroyed.
Returns
a const reference to an instance of plug-in event handle.
Definition at line 122 of file event_impl.cpp.
References MEvent.
getHostProfilingInfo()
HostProfilingInfo* sycl::_V1::detail::event_impl::getHostProfilingInfo () inline
Returns host profiling information.
Returns
a pointer to HostProfilingInfo instance.
Definition at line 185 of file event_impl.hpp.
References MHostProfilingInfo.
getNative()
pi_native_handle sycl::_V1::detail::event_impl::getNative ()
Gets the native handle of the SYCL event.
Returns
a native handle.
Definition at line 483 of file event_impl.cpp.
References ensureContextInitialized(), getHandleRef(), getPlugin(), MContext, MEvent, MIsInitialized, sycl::_V1::opencl, piEventCreate, piEventRetain(), and piextEventGetNativeHandle().
getPlugin()
const PluginPtr & sycl::_V1::detail::event_impl::getPlugin ()
Returns
the Plugin associated with the context of this event. Should be called when this is not a Host Event.
Definition at line 132 of file event_impl.cpp.
References ensureContextInitialized(), and MContext.
Referenced by event_impl(), flushIfNeeded(), getNative(), waitInternal(), and ~event_impl().
getPostCompleteEvents()
const std::vector<EventImplPtr>& sycl::_V1::detail::event_impl::getPostCompleteEvents () const inline
Definition at line 337 of file event_impl.hpp.
References MPostCompleteEvents.
getPreparedDepsEvents()
std::vector<std::shared_ptr<event_impl> >& sycl::_V1::detail::event_impl::getPreparedDepsEvents () inline
Returns vector of event dependencies.
Returns
a reference to MPreparedDepsEvents.
Definition at line 195 of file event_impl.hpp.
References MPreparedDepsEvents.
getPreparedHostDepsEvents()
std::vector<std::shared_ptr<event_impl> >& sycl::_V1::detail::event_impl::getPreparedHostDepsEvents () inline
Returns vector of host event dependencies.
Returns
a reference to MPreparedHostDepsEvents.
Definition at line 202 of file event_impl.hpp.
References MPreparedHostDepsEvents.
getSubmissionTime()
uint64_t sycl::_V1::detail::event_impl::getSubmissionTime ()
Returns
Submission time for command associated with this event
Definition at line 591 of file event_impl.cpp.
References MSubmitTime.
getSubmittedQueue()
QueueImplPtr sycl::_V1::detail::event_impl::getSubmittedQueue () const inline
Definition at line 269 of file event_impl.hpp.
References MSubmittedQueue.
getSyncPoint()
sycl::detail::pi::PiExtSyncPoint sycl::_V1::detail::event_impl::getSyncPoint () const inline
Definition at line 304 of file event_impl.hpp.
References MSyncPoint.
getWaitList()
std::vector< EventImplPtr > sycl::_V1::detail::event_impl::getWaitList ()
Returns vector of event_impl that this event_impl depends on.
Returns
a vector of "immediate" dependencies for this event_impl.
Definition at line 499 of file event_impl.cpp.
References HES_Discarded, sycl::_V1::invalid, sycl::_V1::make_error_code(), MMutex, MPreparedDepsEvents, MPreparedHostDepsEvents, and MState.
getWorkerQueue()
QueueImplPtr sycl::_V1::detail::event_impl::getWorkerQueue () inline
Returns worker queue for command.
Returns
shared_ptr to MWorkerQueue, please be aware it can be empty pointer
Definition at line 231 of file event_impl.hpp.
References MWorkerQueue.
instrumentationEpilog()
void sycl::_V1::detail::event_impl::instrumentationEpilog (void * TelementryEvent, const std::string & Name, int32_t StreamID, uint64_t IId) const protected
Definition at line 229 of file event_impl.cpp.
Referenced by wait().
instrumentationProlog()
void * sycl::_V1::detail::event_impl::instrumentationProlog (std::string & Name, int32_t StreamID, uint64_t & instance_id) const protected
Definition at line 193 of file event_impl.cpp.
References MCommand, MEvent, and sycl::_V1::detail::Command::MTraceEvent.
Referenced by wait().
is_host()
bool sycl::_V1::detail::event_impl::is_host ()
Checks if this event is a SYCL host event.
All devices that do not support OpenCL interoperability are treated as host device to avoid attempts to call method get on such events.
Returns
true if this event is a SYCL host event.
Definition at line 50 of file event_impl.cpp.
References MHostEvent.
isCompleted()
bool sycl::_V1::detail::event_impl::isCompleted ()
Checks if this event is complete.
Returns
true if this event is complete.
Definition at line 593 of file event_impl.cpp.
References sycl::_V1::info::complete.
isContextInitialized()
bool sycl::_V1::detail::event_impl::isContextInitialized () const inline noexcept
Definition at line 290 of file event_impl.hpp.
References MIsContextInitialized.
isDiscarded()
bool sycl::_V1::detail::event_impl::isDiscarded () const inline
Checks if this event is discarded by SYCL implementation.
Returns
true if this event is discarded.
Definition at line 225 of file event_impl.hpp.
References HES_Discarded, and MState.
isEventFromSubmittedExecCommandBuffer()
bool sycl::_V1::detail::event_impl::isEventFromSubmittedExecCommandBuffer () const inline
Definition at line 320 of file event_impl.hpp.
References MEventFromSubmittedExecCommandBuffer.
isInitialized()
bool sycl::_V1::detail::event_impl::isInitialized () const inline noexcept
Checks if an event is in a fully intialized state.
Default-constructed events will return true only after having initialized its native event, while other events will assume that they are fully initialized at construction, relying on external sources to supply member data.
Returns
true if the event is considered to be in a fully initialized state.
Definition at line 278 of file event_impl.hpp.
References MIsInitialized.
isNOP()
bool sycl::_V1::detail::event_impl::isNOP () inline
Indicates if this event is not associated with any command and doesn't have native handle.
Returns
true if no associated command and no event handle.
Definition at line 256 of file event_impl.hpp.
References getHandleRef(), and MCommand.
setCommand()
void sycl::_V1::detail::event_impl::setCommand (void * Command) inline
Associates this event with the command.
Scheduler mutex must be locked in write mode when this is called.
Parameters
Command is a generic pointer to Command object instance.
Definition at line 180 of file event_impl.hpp.
References MCommand.
setCommandBufferCommand()
void sycl::_V1::detail::event_impl::setCommandBufferCommand (sycl::detail::pi::PiExtCommandBufferCommand Command) inline
Definition at line 329 of file event_impl.hpp.
References MCommandBufferCommand.
setCommandGraph()
void sycl::_V1::detail::event_impl::setCommandGraph (std::shared_ptr< ext::oneapi::experimental::detail::graph_impl > Graph) inline
Definition at line 306 of file event_impl.hpp.
References MGraph.
setComplete()
void sycl::_V1::detail::event_impl::setComplete ()
Marks this event as completed.
Definition at line 94 of file event_impl.cpp.
References cv, HES_Complete, HES_NotComplete, MEvent, MHostEvent, MMutex, and MState.
setContextImpl()
void sycl::_V1::detail::event_impl::setContextImpl (const ContextImplPtr & Context)
Associate event with the context.
Provided PiContext inside ContextImplPtr must be associated with the PiEvent object stored in this class
Parameters
Context is a shared pointer to an instance of valid context_impl.
Definition at line 139 of file event_impl.cpp.
References MContext, MHostEvent, and MIsContextInitialized.
Referenced by ensureContextInitialized(), and event_impl().
setEventFromSubmittedExecCommandBuffer()
void sycl::_V1::detail::event_impl::setEventFromSubmittedExecCommandBuffer (bool value) inline
Definition at line 316 of file event_impl.hpp.
References MEventFromSubmittedExecCommandBuffer.
setHostEnqueueTime()
void sycl::_V1::detail::event_impl::setHostEnqueueTime ()
Calling this function to capture the host timestamp to use profiling base time.
See MFallbackProfiling
Definition at line 583 of file event_impl.cpp.
References sycl::_V1::detail::getTimestamp(), MFallbackProfiling, MHostBaseTime, and MIsProfilingEnabled.
setProfilingEnabled()
void sycl::_V1::detail::event_impl::setProfilingEnabled (bool Value) inline
Definition at line 324 of file event_impl.hpp.
References MIsProfilingEnabled.
setStateIncomplete()
void sycl::_V1::detail::event_impl::setStateIncomplete ()
Clear the event state.
Definition at line 137 of file event_impl.cpp.
References HES_NotComplete, and MState.
setSubmissionTime()
void sycl::_V1::detail::event_impl::setSubmissionTime ()
Calling this function queries the current device timestamp and sets it as submission time for the command associated with this event.
Definition at line 560 of file event_impl.cpp.
References sycl::_V1::exception::code(), sycl::_V1::detail::getTimestamp(), sycl::_V1::make_error_code(), MFallbackProfiling, MIsProfilingEnabled, MQueue, MSubmitTime, sycl::_V1::profiling, and sycl::_V1::exception::what().
setSubmittedQueue()
void sycl::_V1::detail::event_impl::setSubmittedQueue (const QueueImplPtr & SubmittedQueue) inline
Sets original queue used for submission.
Returns
Definition at line 243 of file event_impl.hpp.
References MSubmittedQueue.
setSyncPoint()
void sycl::_V1::detail::event_impl::setSyncPoint (sycl::detail::pi::PiExtSyncPoint SyncPoint) inline
Definition at line 299 of file event_impl.hpp.
References MSyncPoint.
setWorkerQueue()
void sycl::_V1::detail::event_impl::setWorkerQueue (const QueueImplPtr & WorkerQueue) inline
Sets worker queue for command.
Returns
Definition at line 236 of file event_impl.hpp.
References MWorkerQueue.
wait()
void sycl::_V1::detail::event_impl::wait (std::shared_ptr< sycl::detail::event_impl > Self, bool * Success = nullptr)
Waits for the event.
Self is needed in order to pass shared_ptr to Scheduler.
Parameters
Self is a pointer to this event.
Success is an optional parameter that, when set to a non-null pointer, indicates that failure is a valid outcome for this wait (e.g., in case of a non-blocking read from a pipe), and the value it's pointing to is then set according to the outcome.
Definition at line 245 of file event_impl.cpp.
References sycl::_V1::detail::Scheduler::getInstance(), HES_Discarded, instrumentationEpilog(), instrumentationProlog(), sycl::_V1::invalid, sycl::_V1::make_error_code(), MCommand, MEvent, MGraph, MState, sycl::_V1::detail::SYCL_STREAM_NAME, sycl::_V1::detail::Scheduler::waitForEvent(), and waitInternal().
Referenced by wait_and_throw().
wait_and_throw()
void sycl::_V1::detail::event_impl::wait_and_throw (std::shared_ptr< sycl::detail::event_impl > Self)
Waits for the event.
If any uncaught asynchronous errors occurred on the context that the event is waiting on executions from, then call that context's asynchronous error handler with those errors. Self is needed in order to pass shared_ptr to Scheduler.
Parameters
Self is a pointer to this event.
Definition at line 277 of file event_impl.cpp.
References MSubmittedQueue, and wait().
waitInternal()
void sycl::_V1::detail::event_impl::waitInternal (bool * Success = nullptr)
Waits for the event with respect to device type.
Parameters
Success is an optional parameter that, when set to a non-null pointer, indicates that failure is a valid outcome for this wait (e.g., in case of a non-blocking read from a pipe), and the value it's pointing to is then set according to the outcome.
Definition at line 61 of file event_impl.cpp.
References cv, getPlugin(), HES_Complete, HES_Discarded, sycl::_V1::invalid, sycl::_V1::make_error_code(), MEvent, MHostEvent, MMutex, MPostCompleteEvents, MState, and piEventsWait().
Referenced by wait().
Friends And Related Function Documentation
getOrWaitEvents
std::vector<sycl::detail::pi::PiEvent> getOrWaitEvents (std::vector< sycl::event > DepEvents, std::shared_ptr< sycl::detail::context_impl > Context) friend
Member Data Documentation
cv
std::condition_variable sycl::_V1::detail::event_impl::cv protected
Definition at line 386 of file event_impl.hpp.
Referenced by setComplete(), and waitInternal().
MCommand
void* sycl::_V1::detail::event_impl::MCommand = nullptr protected
Definition at line 362 of file event_impl.hpp.
Referenced by getCommand(), instrumentationProlog(), isNOP(), setCommand(), and wait().
MCommandBufferCommand
sycl::detail::pi::PiExtCommandBufferCommand sycl::_V1::detail::event_impl::MCommandBufferCommand = nullptr protected
Definition at line 402 of file event_impl.hpp.
Referenced by getCommandBufferCommand(), and setCommandBufferCommand().
MContext
ContextImplPtr sycl::_V1::detail::event_impl::MContext protected
Definition at line 359 of file event_impl.hpp.
Referenced by event_impl(), getContextImpl(), getContextImplPtr(), getNative(), getPlugin(), and setContextImpl().
MEvent
sycl::detail::pi::PiEvent sycl::_V1::detail::event_impl::MEvent = nullptr protected
Definition at line 355 of file event_impl.hpp.
Referenced by event_impl(), flushIfNeeded(), getHandleRef(), getNative(), instrumentationProlog(), setComplete(), wait(), waitInternal(), and ~event_impl().
MEventFromSubmittedExecCommandBuffer
bool sycl::_V1::detail::event_impl::MEventFromSubmittedExecCommandBuffer = false protected
Indicates that the event results from a command graph submission.
Definition at line 392 of file event_impl.hpp.
Referenced by isEventFromSubmittedExecCommandBuffer(), and setEventFromSubmittedExecCommandBuffer().
MFallbackProfiling
bool sycl::_V1::detail::event_impl::MFallbackProfiling = false protected
Definition at line 365 of file event_impl.hpp.
Referenced by associateWithQueue(), setHostEnqueueTime(), and setSubmissionTime().
MGraph
std::weak_ptr<ext::oneapi::experimental::detail::graph_impl> sycl::_V1::detail::event_impl::MGraph protected
Store the command graph associated with this event, if any.
This event is also be stored in the graph so a weak_ptr is used.
Definition at line 390 of file event_impl.hpp.
Referenced by getCommandGraph(), setCommandGraph(), and wait().
MHostBaseTime
uint64_t sycl::_V1::detail::event_impl::MHostBaseTime = 0 protected
Definition at line 358 of file event_impl.hpp.
Referenced by setHostEnqueueTime().
MHostEvent
bool sycl::_V1::detail::event_impl::MHostEvent = true protected
Definition at line 360 of file event_impl.hpp.
Referenced by ensureContextInitialized(), is_host(), setComplete(), setContextImpl(), and waitInternal().
MHostProfilingInfo
std::unique_ptr<HostProfilingInfo> sycl::_V1::detail::event_impl::MHostProfilingInfo protected
Definition at line 361 of file event_impl.hpp.
Referenced by associateWithQueue(), and getHostProfilingInfo().
MIsContextInitialized
bool sycl::_V1::detail::event_impl::MIsContextInitialized = false protected
Definition at line 354 of file event_impl.hpp.
Referenced by ensureContextInitialized(), isContextInitialized(), and setContextImpl().
MIsFlushed
std::atomic<bool> sycl::_V1::detail::event_impl::MIsFlushed = false protected
Indicates that the task associated with this event has been submitted by the queue to the device.
Definition at line 378 of file event_impl.hpp.
Referenced by flushIfNeeded().
MIsInitialized
bool sycl::_V1::detail::event_impl::MIsInitialized = true protected
Definition at line 353 of file event_impl.hpp.
Referenced by getNative(), and isInitialized().
MIsProfilingEnabled
bool sycl::_V1::detail::event_impl::MIsProfilingEnabled = false protected
Definition at line 364 of file event_impl.hpp.
Referenced by associateWithQueue(), checkProfilingPreconditions(), setHostEnqueueTime(), setProfilingEnabled(), and setSubmissionTime().
MMutex
std::mutex sycl::_V1::detail::event_impl::MMutex protected
Definition at line 385 of file event_impl.hpp.
Referenced by attachEventToComplete(), cleanDepEventsThroughOneLevel(), cleanupDependencyEvents(), getWaitList(), setComplete(), and waitInternal().
MPostCompleteEvents
std::vector<EventImplPtr> sycl::_V1::detail::event_impl::MPostCompleteEvents protected
Definition at line 374 of file event_impl.hpp.
Referenced by attachEventToComplete(), getPostCompleteEvents(), and waitInternal().
MPreparedDepsEvents
std::vector<EventImplPtr> sycl::_V1::detail::event_impl::MPreparedDepsEvents protected
Dependency events prepared for waiting by backend.
Definition at line 371 of file event_impl.hpp.
Referenced by cleanDepEventsThroughOneLevel(), cleanupDependencyEvents(), getPreparedDepsEvents(), and getWaitList().
MPreparedHostDepsEvents
std::vector<EventImplPtr> sycl::_V1::detail::event_impl::MPreparedHostDepsEvents protected
Definition at line 372 of file event_impl.hpp.
Referenced by cleanDepEventsThroughOneLevel(), cleanupDependencyEvents(), getPreparedHostDepsEvents(), and getWaitList().
MQueue
std::weak_ptr<queue_impl> sycl::_V1::detail::event_impl::MQueue protected
Definition at line 363 of file event_impl.hpp.
Referenced by associateWithQueue(), checkProfilingPreconditions(), flushIfNeeded(), and setSubmissionTime().
MState
std::atomic<int> sycl::_V1::detail::event_impl::MState protected
Definition at line 383 of file event_impl.hpp.
Referenced by associateWithQueue(), getWaitList(), isDiscarded(), setComplete(), setStateIncomplete(), wait(), and waitInternal().
MSubmittedQueue
std::weak_ptr<queue_impl> sycl::_V1::detail::event_impl::MSubmittedQueue protected
Definition at line 368 of file event_impl.hpp.
Referenced by getSubmittedQueue(), setSubmittedQueue(), and wait_and_throw().
MSubmitTime
uint64_t sycl::_V1::detail::event_impl::MSubmitTime = 0 protected
Definition at line 357 of file event_impl.hpp.
Referenced by getSubmissionTime(), and setSubmissionTime().
MSyncPoint
sycl::detail::pi::PiExtSyncPoint sycl::_V1::detail::event_impl::MSyncPoint protected
Definition at line 397 of file event_impl.hpp.
Referenced by getSyncPoint(), and setSyncPoint().
MWorkerQueue
std::weak_ptr<queue_impl> sycl::_V1::detail::event_impl::MWorkerQueue protected
Definition at line 367 of file event_impl.hpp.
Referenced by getWorkerQueue(), and setWorkerQueue().
The documentation for this class was generated from the following files:
source/detail/event_impl.hpp
source/detail/event_impl.cpp