DPC++ Runtime: cl::sycl::nd_range< dimensions > Class Template Reference
cl::sycl::nd_range< dimensions > Class Template Reference
DPC++ User API
Defines the iteration domain of both the work-groups and the overall dispatch.
#include <CL/sycl/nd_range.hpp>
Public Member Functions
nd_range (range< dimensions > globalSize, range< dimensions > localSize, id< dimensions > offset)
nd_range (range< dimensions > globalSize, range< dimensions > localSize)
range< dimensions > get_global_range () const
range< dimensions > get_local_range () const
range< dimensions > get_group_range () const
id< dimensions > get_offset () const
nd_range (const nd_range< dimensions > &rhs)=default
nd_range (nd_range< dimensions > &&rhs)=default
nd_range< dimensions > & operator= (const nd_range< dimensions > &rhs)=default
nd_range< dimensions > & operator= (nd_range< dimensions > &&rhs)=default
nd_range ()=default
bool operator== (const nd_range< dimensions > &rhs) const
bool operator!= (const nd_range< dimensions > &rhs) const
Detailed Description
template<int dimensions = 1>
class cl::sycl::nd_range< dimensions >
Defines the iteration domain of both the work-groups and the overall dispatch.
Definition at line 23 of file nd_range.hpp.
Constructor & Destructor Documentation
nd_range() [1/5]
template<int dimensions = 1> cl::sycl::nd_range< dimensions >::nd_range (range< dimensions > globalSize, range< dimensions > localSize, id< dimensions > offset) inline
Definition at line 32 of file nd_range.hpp.
nd_range() [2/5]
template<int dimensions = 1> cl::sycl::nd_range< dimensions >::nd_range (range< dimensions > globalSize, range< dimensions > localSize) inline
Definition at line 36 of file nd_range.hpp.
nd_range() [3/5]
template<int dimensions = 1> cl::sycl::nd_range< dimensions >::nd_range (const nd_range< dimensions > & rhs) default
nd_range() [4/5]
template<int dimensions = 1> cl::sycl::nd_range< dimensions >::nd_range (nd_range< dimensions > && rhs) default
nd_range() [5/5]
template<int dimensions = 1> cl::sycl::nd_range< dimensions >::nd_range () default
Member Function Documentation
get_global_range()
template<int dimensions = 1> range<dimensions> cl::sycl::nd_range< dimensions >::get_global_range () const inline
Definition at line 40 of file nd_range.hpp.
Referenced by cl::sycl::detail::NDRDescT::set(), and cl::sycl::detail::writeNDRange().
get_group_range()
template<int dimensions = 1> range<dimensions> cl::sycl::nd_range< dimensions >::get_group_range () const inline
Definition at line 44 of file nd_range.hpp.
Referenced by cl::sycl::handler::parallel_for(), cl::sycl::handler::parallel_for_Impl(), cl::sycl::ext::oneapi::detail::reduCGFunc(), and cl::sycl::ext::oneapi::detail::reduCGFuncImpl().
get_local_range()
template<int dimensions = 1> range<dimensions> cl::sycl::nd_range< dimensions >::get_local_range () const inline
Definition at line 42 of file nd_range.hpp.
Referenced by cl::sycl::handler::parallel_for(), cl::sycl::handler::parallel_for_Impl(), cl::sycl::ext::oneapi::detail::reduCGFunc(), cl::sycl::ext::oneapi::detail::reduCGFuncImpl(), cl::sycl::detail::NDRDescT::set(), and cl::sycl::detail::writeNDRange().
get_offset()
template<int dimensions = 1> id<dimensions> cl::sycl::nd_range< dimensions >::get_offset () const inline
Definition at line 47 of file nd_range.hpp.
Referenced by cl::sycl::detail::NDRDescT::set(), and cl::sycl::detail::writeNDRange().
operator!=()
template<int dimensions = 1> bool cl::sycl::nd_range< dimensions >::operator!= (const nd_range< dimensions > & rhs) const inline
Definition at line 62 of file nd_range.hpp.
operator=() [1/2]
template<int dimensions = 1> nd_range<dimensions>& cl::sycl::nd_range< dimensions >::operator= (const nd_range< dimensions > & rhs) default
operator=() [2/2]
template<int dimensions = 1> nd_range<dimensions>& cl::sycl::nd_range< dimensions >::operator= (nd_range< dimensions > && rhs) default
operator==()
template<int dimensions = 1> bool cl::sycl::nd_range< dimensions >::operator== (const nd_range< dimensions > & rhs) const inline
Definition at line 57 of file nd_range.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/nd_range.hpp