DPC++ Runtime: cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName > Class Template Reference
cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName > Class Template Reference
#include <CL/sycl/detail/cg_types.hpp>
Public Member Functions
HostKernel (KernelType Kernel)
void call (const NDRDescT &NDRDesc, HostProfilingInfo *HPI) override
char * getPtr () override
template<class ArgT = KernelArgType>
detail::enable_if_t< std::is_same< ArgT, void >::value > runOnHost (const NDRDescT &)
template<class ArgT = KernelArgType>
detail::enable_if_t< std::is_same< ArgT, sycl::id< Dims > >::value > runOnHost (const NDRDescT &NDRDesc)
template<class ArgT = KernelArgType>
detail::enable_if_t< std::is_same< ArgT, item< Dims, false > >::value > runOnHost (const NDRDescT &NDRDesc)
template<class ArgT = KernelArgType>
detail::enable_if_t< std::is_same< ArgT, item< Dims, true > >::value > runOnHost (const NDRDescT &NDRDesc)
template<class ArgT = KernelArgType>
detail::enable_if_t< std::is_same< ArgT, nd_item< Dims > >::value > runOnHost (const NDRDescT &NDRDesc)
template<typename ArgT = KernelArgType>
enable_if_t< std::is_same< ArgT, cl::sycl::group< Dims > >::value > runOnHost (const NDRDescT &NDRDesc)
~HostKernel ()=default
Public Member Functions inherited from cl::sycl::detail::HostKernelBase
virtual ~HostKernelBase ()=default
Detailed Description
template<class KernelType, class KernelArgType, int Dims, typename KernelName>
class cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >
Definition at line 254 of file cg_types.hpp.
Constructor & Destructor Documentation
HostKernel()
template<class KernelType , class KernelArgType , int Dims, typename KernelName > cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::HostKernel (KernelType Kernel) inline
Definition at line 259 of file cg_types.hpp.
~HostKernel()
template<class KernelType , class KernelArgType , int Dims, typename KernelName > cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::~HostKernel () default
Member Function Documentation
call()
template<class KernelType , class KernelArgType , int Dims, typename KernelName > void cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::call (const NDRDescT & NDRDesc, HostProfilingInfo * HPI) inline override virtual
Implements cl::sycl::detail::HostKernelBase.
Definition at line 260 of file cg_types.hpp.
References cl::sycl::detail::NDRDescT::Dims, cl::sycl::detail::HostProfilingInfo::end(), cl::sycl::detail::NDRDescT::GlobalSize, cl::sycl::detail::NDRDescT::LocalSize, cl::sycl::detail::NDRDescT::NumWorkGroups, cl::sycl::detail::NDRDescT::set(), and cl::sycl::detail::HostProfilingInfo::start().
getPtr()
template<class KernelType , class KernelArgType , int Dims, typename KernelName > char* cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::getPtr () inline override virtual
Implements cl::sycl::detail::HostKernelBase.
Definition at line 287 of file cg_types.hpp.
runOnHost() [1/6]
template<class KernelType , class KernelArgType , int Dims, typename KernelName > template<class ArgT = KernelArgType> detail::enable_if_t<std::is_same<ArgT, void>::value> cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::runOnHost (const NDRDescT &) inline
Definition at line 291 of file cg_types.hpp.
References cl::sycl::detail::runKernelWithoutArg().
runOnHost() [2/6]
template<class KernelType , class KernelArgType , int Dims, typename KernelName > template<class ArgT = KernelArgType> detail::enable_if_t<std::is_same<ArgT, sycl::id<Dims> >::value> cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 297 of file cg_types.hpp.
References cl::sycl::detail::NDRDescT::GlobalOffset, cl::sycl::detail::NDRDescT::GlobalSize, cl::sycl::detail::store_id(), and cl::sycl::detail::store_item().
runOnHost() [3/6]
template<class KernelType , class KernelArgType , int Dims, typename KernelName > template<class ArgT = KernelArgType> detail::enable_if_t< std::is_same<ArgT, item<Dims, false> >::value> cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 330 of file cg_types.hpp.
References cl::sycl::detail::NDRDescT::GlobalSize, and cl::sycl::detail::runKernelWithArg().
runOnHost() [4/6]
template<class KernelType , class KernelArgType , int Dims, typename KernelName > template<class ArgT = KernelArgType> detail::enable_if_t< std::is_same<ArgT, item<Dims, true> >::value> cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 355 of file cg_types.hpp.
References cl::sycl::detail::NDRDescT::GlobalOffset, cl::sycl::detail::NDRDescT::GlobalSize, cl::sycl::detail::runKernelWithArg(), cl::sycl::detail::store_id(), and cl::sycl::detail::store_item().
runOnHost() [5/6]
template<class KernelType , class KernelArgType , int Dims, typename KernelName > template<class ArgT = KernelArgType> detail::enable_if_t<std::is_same<ArgT, nd_item<Dims> >::value> cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 387 of file cg_types.hpp.
References cl::sycl::nd_item< dimensions >::get_group(), cl::sycl::detail::NDRDescT::GlobalOffset, cl::sycl::detail::NDRDescT::GlobalSize, cl::sycl::detail::NDRDescT::LocalSize, PI_INVALID_WORK_GROUP_SIZE, cl::sycl::detail::store_group(), cl::sycl::detail::store_id(), cl::sycl::detail::store_item(), and cl::sycl::detail::store_nd_item().
runOnHost() [6/6]
template<class KernelType , class KernelArgType , int Dims, typename KernelName > template<typename ArgT = KernelArgType> enable_if_t<std::is_same<ArgT, cl::sycl::group<Dims> >::value> cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims, KernelName >::runOnHost (const NDRDescT & NDRDesc) inline
Definition at line 438 of file cg_types.hpp.
References cl::sycl::detail::NDRDescT::GlobalSize, cl::sycl::detail::NDRDescT::LocalSize, and PI_INVALID_WORK_GROUP_SIZE.
The documentation for this class was generated from the following file:
include/CL/sycl/detail/cg_types.hpp