DPC++ Runtime: sycl::_V1::detail::RoundedRangeIDGenerator< Dims > Class Template Reference
sycl::_V1::detail::RoundedRangeIDGenerator< Dims > Class Template Reference
#include <sycl/handler.hpp>
Public Member Functions
RoundedRangeIDGenerator (const id< Dims > &Id, const range< Dims > &UserRange, const range< Dims > &RoundedRange)
operator bool ()
void updateId ()
id< Dims > getId ()
template<typename KernelType >
auto getItem ()
Detailed Description
template<int Dims>
class sycl::_V1::detail::RoundedRangeIDGenerator< Dims >
Definition at line 325 of file handler.hpp.
Constructor & Destructor Documentation
RoundedRangeIDGenerator()
template<int Dims> sycl::_V1::detail::RoundedRangeIDGenerator< Dims >::RoundedRangeIDGenerator (const id< Dims > & Id, const range< Dims > & UserRange, const range< Dims > & RoundedRange) inline
Definition at line 333 of file handler.hpp.
Member Function Documentation
getId()
template<int Dims> id<Dims> sycl::_V1::detail::RoundedRangeIDGenerator< Dims >::getId () inline
Definition at line 353 of file handler.hpp.
Referenced by sycl::_V1::detail::RoundedRangeIDGenerator< Dims >::getItem().
getItem()
template<int Dims> template<typename KernelType > auto sycl::_V1::detail::RoundedRangeIDGenerator< Dims >::getItem () inline
Definition at line 355 of file handler.hpp.
References sycl::_V1::detail::RoundedRangeIDGenerator< Dims >::getId().
operator bool()
template<int Dims> sycl::_V1::detail::RoundedRangeIDGenerator< Dims >::operator bool () inline explicit
Definition at line 341 of file handler.hpp.
updateId()
template<int Dims> void sycl::_V1::detail::RoundedRangeIDGenerator< Dims >::updateId () inline
Definition at line 343 of file handler.hpp.
Referenced by sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >::operator()(), and sycl::_V1::detail::RoundedRangeKernelWithKH< TransformedArgType, Dims, KernelType >::operator()().
The documentation for this class was generated from the following file:
include/sycl/handler.hpp