DPC++ Runtime: sycl::_V1::detail::Command Class Reference
sycl::_V1::detail::Command Class Reference abstract
DPC++ Execution Graph
The Command class represents some action that needs to be performed on one or more memory objects.
#include <detail/scheduler/commands.hpp>
Classes
struct Marks
Public Types
enum CommandType {
RUN_CG , COPY_MEMORY , ALLOCA , ALLOCA_SUB_BUF ,
RELEASE , MAP_MEM_OBJ , UNMAP_MEM_OBJ , UPDATE_REQUIREMENT ,
EMPTY_TASK , HOST_TASK , FUSION , EXEC_CMD_BUFFER ,
UPDATE_CMD_BUFFER
}
enum class BlockReason : int { HostAccessor = 0 , HostTask }
Public Member Functions
Command (CommandType Type, QueueImplPtr Queue, sycl::detail::pi::PiExtCommandBuffer CommandBuffer=nullptr, const std::vector< sycl::detail::pi::PiExtSyncPoint > &SyncPoints={})
It is safe to bind MPreparedDepsEvents and MPreparedHostDepsEvents references to event_impl class members because Command should not outlive the event connected to it.
Command * addDep (DepDesc NewDep, std::vector< Command * > &ToCleanUp)
Command * addDep (EventImplPtr Event, std::vector< Command * > &ToCleanUp)
void addUser (Command *NewUser)
CommandType getType () const
virtual bool enqueue (EnqueueResultT &EnqueueResult, BlockingT Blocking, std::vector< Command * > &ToCleanUp)
Checks if the command is enqueued, and calls enqueueImp.
bool isFinished ()
bool isSuccessfullyEnqueued () const
bool isEnqueueBlocked () const
bool isBlocking () const
void addBlockedUserUnique (const EventImplPtr &NewUser)
const QueueImplPtr & getQueue () const
const EventImplPtr & getEvent () const
void emitInstrumentationDataProxy ()
Proxy method which calls emitInstrumentationData.
virtual void emitInstrumentationData ()=0
Instrumentation method which emits telemetry data.
void resolveReleaseDependencies (std::set< Command * > &list)
Looks at all the dependencies for the release command and enables instrumentation to report these dependencies as edges.
void emitEdgeEventForCommandDependence (Command *Cmd, void *ObjAddr, bool IsCommand, std::optional< access::mode > AccMode=std::nullopt)
Creates an edge event when the dependency is a command.
void emitEdgeEventForEventDependence (Command *Cmd, sycl::detail::pi::PiEvent &EventAddr)
Creates an edge event when the dependency is an event.
void emitEnqueuedEventSignal (sycl::detail::pi::PiEvent &PiEventAddr)
Creates a signal event with the enqueued kernel event handle.
uint64_t makeTraceEventProlog (void *MAddress)
Create a trace event of node_create type; this must be guarded by a check for xptiTraceEnabled().
void makeTraceEventEpilog ()
If prolog has been run, run epilog; this must be guarded by a check for xptiTraceEnabled().
void emitInstrumentation (uint16_t Type, const char *Txt=nullptr)
Emits an event of Type.
virtual void printDot (std::ostream &Stream) const =0
virtual const Requirement * getRequirement () const
virtual ~Command ()
const char * getBlockReason () const
virtual const ContextImplPtr & getWorkerContext () const
Get the context of the queue this command will be submitted to.
const QueueImplPtr & getWorkerQueue () const
Get the queue this command will be submitted to.
virtual bool producesPiEvent () const
Returns true iff the command produces a PI event on non-host devices.
virtual bool supportsPostEnqueueCleanup () const
Returns true iff this command can be freed by post enqueue cleanup.
virtual bool readyForCleanup () const
Returns true iff this command is ready to be submitted for cleanup.
std::vector< sycl::detail::pi::PiEvent > getPiEvents (const std::vector< EventImplPtr > &EventImpls) const
Collect PI events from EventImpls and filter out some of them in case of in order queue.
std::vector< sycl::detail::pi::PiEvent > getPiEventsBlocking (const std::vector< EventImplPtr > &EventImpls) const
Collect PI events from EventImpls and filter out some of them in case of in order queue.
bool isHostTask () const
bool isFusable () const
const std::vector< EventImplPtr > & getPreparedHostDepsEvents () const
const std::vector< EventImplPtr > & getPreparedDepsEvents () const
void copySubmissionCodeLocation ()
void clearAllDependencies ()
Clear all dependency events This should only be used if a command is about to be deleted without being executed before that.
Public Attributes
std::vector< DepDesc > MDeps
Contains list of dependencies(edges)
std::unordered_set< Command * > MUsers
Contains list of commands that depend on the command.
bool MIsBlockable = false
Indicates whether the command can be blocked from enqueueing.
unsigned MLeafCounter = 0
Counts the number of memory objects this command is a leaf for.
Marks MMarks
Used for marking the node during graph traversal.
BlockReason MBlockReason
std::atomic< EnqueueResultT::ResultT > MEnqueueStatus
Describes the status of the command.
void * MTraceEvent = nullptr
The event for node_create and task_begin.
int32_t MStreamID = -1
The stream under which the traces are emitted.
void * MAddress = nullptr
Reserved for storing the object address such as SPIR-V or memory object address.
std::string MAddressString
Buffer to build the address string.
std::string MCommandNodeType
Buffer to build the command node type.
std::string MCommandName
Buffer to build the command end-user understandable name.
bool MTraceEventPrologComplete = false
Flag to indicate if makeTraceEventProlog() has been run.
bool MFirstInstance = false
Flag to indicate if this is the first time we are seeing this payload.
uint64_t MInstanceID = 0
Instance ID tracked for the command.
code_location MSubmissionCodeLocation
Represents code location of command submission to SYCL API, assigned with the valid value only if command execution is async (host task) or delayed (blocked by host task).
std::string MSubmissionFileName
Introduces string to handle memory management since code_location struct works with raw char arrays.
std::string MSubmissionFunctionName
bool MShouldCompleteEventIfPossible = true
bool MMarkedForCleanup = false
Indicates that the node will be freed by graph cleanup.
std::vector< EventImplPtr > MBlockedUsers
Contains list of commands that depends on the host command explicitly (by depends_on).
std::mutex MBlockedUsersMutex
Protected Member Functions
void waitForEvents (QueueImplPtr Queue, std::vector< EventImplPtr > &RawEvents, sycl::detail::pi::PiEvent &Event)
void waitForPreparedHostEvents () const
Command * processDepEvent (EventImplPtr DepEvent, const DepDesc &Dep, std::vector< Command * > &ToCleanUp)
Perform glueing of events from different contexts.
virtual pi_int32 enqueueImp ()=0
Private interface. Derived classes should implement this method.
sycl::detail::pi::PiExtCommandBuffer getCommandBuffer () const
Gets the command buffer (if any) associated with this command.
Protected Attributes
QueueImplPtr MQueue
EventImplPtr MEvent
QueueImplPtr MWorkerQueue
std::vector< EventImplPtr > & MPreparedDepsEvents
Dependency events prepared for waiting by backend.
std::vector< EventImplPtr > & MPreparedHostDepsEvents
CommandType MType
The type of the command.
std::mutex MEnqueueMtx
Mutex used to protect enqueueing from race conditions.
sycl::detail::pi::PiExtCommandBuffer MCommandBuffer
CommandBuffer which will be used to submit to instead of the queue, if set.
std::vector< sycl::detail::pi::PiExtSyncPoint > MSyncPointDeps
List of sync points for submissions to a command buffer.
Friends
class DispatchHostTask
Detailed Description
The Command class represents some action that needs to be performed on one or more memory objects.
The Command has a vector of DepDesc objects that represent dependencies of the command. It has a vector of pointers to commands that depend on the command. It has a pointer to a queue object and an event that is associated with the command.
Definition at line 107 of file commands.hpp.
Member Enumeration Documentation
BlockReason
enum sycl::_V1::detail::Command::BlockReason : int strong
Enumerator
HostAccessor
HostTask
Definition at line 337 of file commands.hpp.
CommandType
enum sycl::_V1::detail::Command::CommandType
Enumerator
RUN_CG
COPY_MEMORY
ALLOCA
ALLOCA_SUB_BUF
RELEASE
MAP_MEM_OBJ
UNMAP_MEM_OBJ
UPDATE_REQUIREMENT
EMPTY_TASK
HOST_TASK
FUSION
EXEC_CMD_BUFFER
UPDATE_CMD_BUFFER
Definition at line 109 of file commands.hpp.
Constructor & Destructor Documentation
Command()
sycl::_V1::detail::Command::Command (CommandType Type, QueueImplPtr Queue, sycl::detail::pi::PiExtCommandBuffer CommandBuffer = nullptr, const std::vector< sycl::detail::pi::PiExtSyncPoint > & SyncPoints = {})
It is safe to bind MPreparedDepsEvents and MPreparedHostDepsEvents references to event_impl class members because Command should not outlive the event connected to it.
Definition at line 511 of file commands.cpp.
References MEnqueueStatus, MEvent, MQueue, MStreamID, MWorkerQueue, sycl::_V1::detail::SYCL_STREAM_NAME, and sycl::_V1::detail::EnqueueResultT::SyclEnqueueReady.
~Command()
virtual sycl::_V1::detail::Command::~Command () inline virtual
Definition at line 220 of file commands.hpp.
References MEvent.
Member Function Documentation
addBlockedUserUnique()
void sycl::_V1::detail::Command::addBlockedUserUnique (const EventImplPtr & NewUser) inline
Definition at line 171 of file commands.hpp.
References MBlockedUsers.
Referenced by sycl::_V1::detail::Scheduler::GraphProcessor::handleBlockingCmd().
addDep() [1/2]
Command * sycl::_V1::detail::Command::addDep (DepDesc NewDep, std::vector< Command * > & ToCleanUp)
Parameters
NewDep dependency to be added
ToCleanUp container for commands that can be cleaned up.
Returns
an optional connection cmd to enqueue
Definition at line 759 of file commands.cpp.
References addUser(), emitEdgeEventForCommandDependence(), getEvent(), sycl::_V1::detail::AccessorImplHost::MAccessMode, sycl::_V1::detail::DepDesc::MDepCommand, sycl::_V1::detail::DepDesc::MDepRequirement, MDeps, sycl::_V1::detail::AccessorImplHost::MSYCLMemObj, and processDepEvent().
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::addCommandGraphUpdate(), sycl::_V1::detail::Scheduler::GraphBuilder::addCopyBack(), sycl::_V1::detail::EmptyCommand::addRequirement(), sycl::_V1::detail::AllocaCommand::AllocaCommand(), sycl::_V1::detail::AllocaSubBufCommand::AllocaSubBufCommand(), sycl::_V1::detail::Scheduler::GraphBuilder::connectDepEvent(), and sycl::_V1::detail::Scheduler::GraphBuilder::getOrInsertMemObjRecord().
addDep() [2/2]
Command * sycl::_V1::detail::Command::addDep (EventImplPtr Event, std::vector< Command * > & ToCleanUp)
Parameters
NewDep dependency to be added
ToCleanUp container for commands that can be cleaned up.
Returns
an optional connection cmd to enqueue
Definition at line 784 of file commands.cpp.
References emitEdgeEventForEventDependence(), and processDepEvent().
addUser()
void sycl::_V1::detail::Command::addUser (Command * NewUser) inline
Definition at line 141 of file commands.hpp.
References MUsers.
Referenced by addDep(), and sycl::_V1::detail::Scheduler::GraphBuilder::connectDepEvent().
clearAllDependencies()
void sycl::_V1::detail::Command::clearAllDependencies () inline
Clear all dependency events This should only be used if a command is about to be deleted without being executed before that.
As of now, the only valid use case for this function is in kernel fusion, where the fused kernel commands are replaced by the fused command without ever being executed.
Definition at line 313 of file commands.hpp.
References MDeps, MPreparedDepsEvents, and MPreparedHostDepsEvents.
copySubmissionCodeLocation()
void sycl::_V1::detail::Command::copySubmissionCodeLocation ()
Definition at line 963 of file commands.cpp.
References MSubmissionCodeLocation, MSubmissionFileName, MSubmissionFunctionName, and sycl::_V1::detail::tls_code_loc_t::query().
Referenced by sycl::_V1::detail::Scheduler::GraphProcessor::handleBlockingCmd().
emitEdgeEventForCommandDependence()
void sycl::_V1::detail::Command::emitEdgeEventForCommandDependence (Command * Cmd, void * ObjAddr, bool IsCommand, std::optional< access::mode > AccMode = std::nullopt)
Creates an edge event when the dependency is a command.
Method takes in void * for the address as adding a template function to the command group object maybe undesirable.
Parameters
Cmd The command object of the source of the edge
ObjAddr The address that defines the edge dependency; it is the event address when the edge is for an event and a memory object address if it is due to an accessor
Prefix Contains "event" if the dependency is an edge and contains the access mode to the buffer if it is due to an accessor
IsCommand True if the dependency has a command object as the source, false otherwise
Definition at line 552 of file commands.cpp.
References sycl::_V1::detail::accessModeToString(), MAddress, MStreamID, and MTraceEvent.
Referenced by addDep(), and emitEdgeEventForEventDependence().
emitEdgeEventForEventDependence()
void sycl::_V1::detail::Command::emitEdgeEventForEventDependence (Command * Cmd, sycl::detail::pi::PiEvent & PiEventAddr)
Creates an edge event when the dependency is an event.
Creates an edge when the dependency is due to an event.
Parameters
Cmd The command object of the source of the edge
PiEventAddr The address that defines the edge dependency, which in this case is an event
Definition at line 603 of file commands.cpp.
References emitEdgeEventForCommandDependence(), MAddress, MStreamID, and MTraceEvent.
Referenced by addDep().
emitEnqueuedEventSignal()
void sycl::_V1::detail::Command::emitEnqueuedEventSignal (sycl::detail::pi::PiEvent & PiEventAddr)
Creates a signal event with the enqueued kernel event handle.
Definition at line 799 of file commands.cpp.
References MInstanceID, MStreamID, and MTraceEvent.
Referenced by enqueue().
emitInstrumentation()
void sycl::_V1::detail::Command::emitInstrumentation (uint16_t Type, const char * Txt = nullptr)
Emits an event of Type.
Definition at line 808 of file commands.cpp.
References MInstanceID, MStreamID, and MTraceEvent.
Referenced by enqueue().
emitInstrumentationData()
virtual void sycl::_V1::detail::Command::emitInstrumentationData () pure virtual
Instrumentation method which emits telemetry data.
Implemented in sycl::_V1::detail::UnMapMemObject, sycl::_V1::detail::MapMemObject, sycl::_V1::detail::AllocaSubBufCommand, sycl::_V1::detail::AllocaCommand, sycl::_V1::detail::AllocaCommandBase, sycl::_V1::detail::ReleaseCommand, sycl::_V1::detail::EmptyCommand, sycl::_V1::detail::UpdateCommandBufferCommand, sycl::_V1::detail::KernelFusionCommand, sycl::_V1::detail::UpdateHostRequirementCommand, sycl::_V1::detail::ExecCGCommand, sycl::_V1::detail::MemCpyCommandHost, and sycl::_V1::detail::MemCpyCommand.
Referenced by emitInstrumentationDataProxy().
emitInstrumentationDataProxy()
void sycl::_V1::detail::Command::emitInstrumentationDataProxy ()
Proxy method which calls emitInstrumentationData.
Definition at line 536 of file commands.cpp.
References emitInstrumentationData().
Referenced by sycl::_V1::detail::AllocaCommand::AllocaCommand(), sycl::_V1::detail::AllocaCommandBase::AllocaCommandBase(), sycl::_V1::detail::AllocaSubBufCommand::AllocaSubBufCommand(), sycl::_V1::detail::EmptyCommand::EmptyCommand(), sycl::_V1::detail::ExecCGCommand::ExecCGCommand(), sycl::_V1::detail::KernelFusionCommand::KernelFusionCommand(), sycl::_V1::detail::MapMemObject::MapMemObject(), sycl::_V1::detail::MemCpyCommand::MemCpyCommand(), sycl::_V1::detail::MemCpyCommandHost::MemCpyCommandHost(), sycl::_V1::detail::ReleaseCommand::ReleaseCommand(), sycl::_V1::detail::UnMapMemObject::UnMapMemObject(), and sycl::_V1::detail::UpdateHostRequirementCommand::UpdateHostRequirementCommand().
enqueue()
bool sycl::_V1::detail::Command::enqueue (EnqueueResultT & EnqueueResult, BlockingT Blocking, std::vector< Command * > & ToCleanUp) virtual
Checks if the command is enqueued, and calls enqueueImp.
Parameters
EnqueueResult is set to the specific status if enqueue failed.
Blocking if this argument is true, function will wait for the command to be unblocked before calling enqueueImp.
ToCleanUp container for commands that can be cleaned up.
Returns
true if the command is enqueued.
Definition at line 819 of file commands.cpp.
References emitEnqueuedEventSignal(), emitInstrumentation(), enqueueImp(), getBlockReason(), MEnqueueMtx, MEnqueueStatus, MEvent, MIsBlockable, MLeafCounter, MMarkedForCleanup, MShouldCompleteEventIfPossible, MSubmissionCodeLocation, supportsPostEnqueueCleanup(), sycl::_V1::detail::EnqueueResultT::SyclEnqueueBlocked, sycl::_V1::detail::EnqueueResultT::SyclEnqueueFailed, and sycl::_V1::detail::EnqueueResultT::SyclEnqueueSuccess.
Referenced by sycl::_V1::detail::Scheduler::GraphProcessor::enqueueCommand().
enqueueImp()
virtual pi_int32 sycl::_V1::detail::Command::enqueueImp () protected pure virtual
Private interface. Derived classes should implement this method.
Referenced by enqueue().
getBlockReason()
const char * sycl::_V1::detail::Command::getBlockReason () const
Definition at line 952 of file commands.cpp.
References HostAccessor, HostTask, and MBlockReason.
Referenced by enqueue().
getCommandBuffer()
sycl::detail::pi::PiExtCommandBuffer sycl::_V1::detail::Command::getCommandBuffer () const inline protected
Gets the command buffer (if any) associated with this command.
Definition at line 403 of file commands.hpp.
References MCommandBuffer.
getEvent()
const EventImplPtr& sycl::_V1::detail::Command::getEvent () const inline
Definition at line 180 of file commands.hpp.
References MEvent.
Referenced by sycl::_V1::detail::Scheduler::addCG(), sycl::_V1::detail::Scheduler::addCommandGraphUpdate(), sycl::_V1::detail::Scheduler::addCopyBack(), addDep(), sycl::_V1::detail::Scheduler::addHostAccessor(), sycl::_V1::detail::Scheduler::checkLeavesCompletion(), sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommand(), sycl::_V1::detail::Scheduler::GraphBuilder::connectDepEvent(), sycl::_V1::detail::Scheduler::GraphProcessor::handleBlockingCmd(), sycl::_V1::detail::Scheduler::NotifyHostTaskCompletion(), sycl::_V1::detail::Scheduler::GraphProcessor::waitForEvent(), and sycl::_V1::detail::Scheduler::waitForRecordToFinish().
getPiEvents()
std::vector< sycl::detail::pi::PiEvent > sycl::_V1::detail::Command::getPiEvents (const std::vector< EventImplPtr > & EventImpls) const
Collect PI events from EventImpls and filter out some of them in case of in order queue.
Definition at line 233 of file commands.cpp.
References getWorkerQueue(), and isHostTask().
Referenced by waitForEvents().
getPiEventsBlocking()
std::vector< sycl::detail::pi::PiEvent > sycl::_V1::detail::Command::getPiEventsBlocking (const std::vector< EventImplPtr > & EventImpls) const
Collect PI events from EventImpls and filter out some of them in case of in order queue.
Does blocking enqueue if event is expected to produce pi event but has empty native handle.
Definition at line 260 of file commands.cpp.
References sycl::_V1::detail::BLOCKING, sycl::_V1::detail::Scheduler::enqueueCommandForCG(), sycl::_V1::detail::Scheduler::getInstance(), getWorkerQueue(), isHostTask(), and producesPiEvent().
getPreparedDepsEvents()
const std::vector<EventImplPtr>& sycl::_V1::detail::Command::getPreparedDepsEvents () const inline
Definition at line 300 of file commands.hpp.
References MPreparedDepsEvents.
Referenced by sycl::_V1::detail::checkForCircularDependency(), sycl::_V1::detail::Scheduler::GraphBuilder::completeFusion(), and sycl::_V1::detail::Scheduler::GraphProcessor::enqueueCommand().
getPreparedHostDepsEvents()
const std::vector<EventImplPtr>& sycl::_V1::detail::Command::getPreparedHostDepsEvents () const inline
Definition at line 296 of file commands.hpp.
References MPreparedHostDepsEvents.
Referenced by sycl::_V1::detail::checkForCircularDependency(), sycl::_V1::detail::Scheduler::GraphBuilder::completeFusion(), and sycl::_V1::detail::Scheduler::GraphProcessor::enqueueCommand().
getQueue()
const QueueImplPtr& sycl::_V1::detail::Command::getQueue () const inline
Definition at line 178 of file commands.hpp.
References MQueue.
Referenced by sycl::_V1::detail::Scheduler::addCopyBack(), sycl::_V1::detail::Scheduler::GraphBuilder::addCopyBack(), sycl::_V1::detail::Scheduler::GraphBuilder::addHostAccessor(), sycl::_V1::detail::Scheduler::GraphBuilder::findAllocaForReq(), and sycl::_V1::detail::insertMapUnmapForLinkedCmds().
getRequirement()
virtual const Requirement* sycl::_V1::detail::Command::getRequirement () const inline virtual
Reimplemented in sycl::_V1::detail::UpdateHostRequirementCommand, sycl::_V1::detail::MemCpyCommandHost, sycl::_V1::detail::MemCpyCommand, sycl::_V1::detail::UnMapMemObject, sycl::_V1::detail::MapMemObject, sycl::_V1::detail::AllocaCommandBase, and sycl::_V1::detail::EmptyCommand.
Definition at line 215 of file commands.hpp.
getType()
CommandType sycl::_V1::detail::Command::getType () const inline
Returns
type of the command, e.g. Allocate, MemoryCopy.
Definition at line 144 of file commands.hpp.
References MType.
Referenced by sycl::_V1::detail::Scheduler::checkLeavesCompletion(), sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommand(), sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), sycl::_V1::detail::Scheduler::GraphBuilder::completeFusion(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::Scheduler::GraphBuilder::findAllocaForReq(), sycl::_V1::detail::isHostAccessorCmd(), and sycl::_V1::detail::isPartOfFusion().
getWorkerContext()
const ContextImplPtr & sycl::_V1::detail::Command::getWorkerContext () const virtual
Get the context of the queue this command will be submitted to.
Could differ from the context of MQueue for memory copy commands.
Reimplemented in sycl::_V1::detail::MemCpyCommandHost, and sycl::_V1::detail::MemCpyCommand.
Definition at line 741 of file commands.cpp.
References MQueue.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::connectDepEvent().
getWorkerQueue()
const QueueImplPtr & sycl::_V1::detail::Command::getWorkerQueue () const
Get the queue this command will be submitted to.
Could differ from MQueue for memory copy commands.
Definition at line 745 of file commands.cpp.
References MWorkerQueue.
Referenced by getPiEvents(), getPiEventsBlocking(), sycl::_V1::detail::MemCpyCommand::getWorkerContext(), sycl::_V1::detail::MemCpyCommandHost::getWorkerContext(), processDepEvent(), and waitForEvents().
isBlocking()
bool sycl::_V1::detail::Command::isBlocking () const inline
Definition at line 169 of file commands.hpp.
References isHostTask(), and MEvent.
Referenced by sycl::_V1::detail::Scheduler::GraphProcessor::handleBlockingCmd().
isEnqueueBlocked()
bool sycl::_V1::detail::Command::isEnqueueBlocked () const inline
Definition at line 164 of file commands.hpp.
References MEnqueueStatus, MIsBlockable, and sycl::_V1::detail::EnqueueResultT::SyclEnqueueBlocked.
Referenced by sycl::_V1::detail::Scheduler::GraphProcessor::enqueueCommand().
isFinished()
bool sycl::_V1::detail::Command::isFinished ()
isFusable()
bool sycl::_V1::detail::Command::isFusable () const
Definition at line 304 of file commands.cpp.
References sycl::_V1::detail::CG::getType(), sycl::_V1::detail::CGExecKernel::MKernelIsCooperative, and MType.
isHostTask()
bool sycl::_V1::detail::Command::isHostTask () const
Definition at line 298 of file commands.cpp.
References MType.
Referenced by getPiEvents(), getPiEventsBlocking(), and isBlocking().
isSuccessfullyEnqueued()
bool sycl::_V1::detail::Command::isSuccessfullyEnqueued () const inline
Definition at line 158 of file commands.hpp.
References MEnqueueStatus, and sycl::_V1::detail::EnqueueResultT::SyclEnqueueSuccess.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommand(), and sycl::_V1::detail::Scheduler::GraphProcessor::enqueueCommand().
makeTraceEventEpilog()
void sycl::_V1::detail::Command::makeTraceEventEpilog ()
If prolog has been run, run epilog; this must be guarded by a check for xptiTraceEnabled().
Definition at line 693 of file commands.cpp.
References MCommandNodeType, MInstanceID, MStreamID, MTraceEvent, and MTraceEventPrologComplete.
Referenced by sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaSubBufCommand::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), and sycl::_V1::detail::UnMapMemObject::emitInstrumentationData().
makeTraceEventProlog()
uint64_t sycl::_V1::detail::Command::makeTraceEventProlog (void * MAddress)
Create a trace event of node_create type; this must be guarded by a check for xptiTraceEnabled().
Post Condition: MTraceEvent will be set to the event created.
Parameters
MAddress The address to use to create the payload.
Definition at line 661 of file commands.cpp.
References MAddress, MAddressString, MCommandName, MCommandNodeType, MFirstInstance, MInstanceID, MStreamID, MTraceEvent, MTraceEventPrologComplete, and MType.
Referenced by sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), and sycl::_V1::detail::UnMapMemObject::emitInstrumentationData().
printDot()
virtual void sycl::_V1::detail::Command::printDot (std::ostream & Stream) const pure virtual
Implemented in sycl::_V1::detail::UpdateCommandBufferCommand, sycl::_V1::detail::KernelFusionCommand, sycl::_V1::detail::UpdateHostRequirementCommand, sycl::_V1::detail::ExecCGCommand, sycl::_V1::detail::MemCpyCommandHost, sycl::_V1::detail::MemCpyCommand, sycl::_V1::detail::UnMapMemObject, sycl::_V1::detail::MapMemObject, sycl::_V1::detail::AllocaSubBufCommand, sycl::_V1::detail::AllocaCommand, sycl::_V1::detail::ReleaseCommand, and sycl::_V1::detail::EmptyCommand.
Referenced by sycl::_V1::detail::printDotRecursive().
processDepEvent()
Command * sycl::_V1::detail::Command::processDepEvent (EventImplPtr DepEvent, const DepDesc & Dep, std::vector< Command * > & ToCleanUp) protected
Perform glueing of events from different contexts.
Parameters
DepEvent event this commands should depend on
Dep optional DepDesc to perform connection of events properly
ToCleanUp container for commands that can be cleaned up.
Returns
returns an optional connection command to enqueue
Glueing (i.e. connecting) will be performed if and only if DepEvent is not from host context and its context doesn't match to context of this command. Context of this command is fetched via getWorkerContext().
Optionality of Dep is set by Dep.MDepCommand not equal to nullptr.
Definition at line 706 of file commands.cpp.
References sycl::_V1::detail::Scheduler::GraphBuilder::connectDepEvent(), sycl::_V1::detail::Scheduler::getInstance(), getWorkerQueue(), sycl::_V1::detail::Scheduler::MGraphBuilder, MPreparedDepsEvents, and MPreparedHostDepsEvents.
Referenced by addDep().
producesPiEvent()
bool sycl::_V1::detail::Command::producesPiEvent () const virtual
Returns true iff the command produces a PI event on non-host devices.
Reimplemented in sycl::_V1::detail::UpdateCommandBufferCommand, sycl::_V1::detail::KernelFusionCommand, sycl::_V1::detail::ExecCGCommand, sycl::_V1::detail::MemCpyCommand, sycl::_V1::detail::UnMapMemObject, sycl::_V1::detail::AllocaCommandBase, sycl::_V1::detail::ReleaseCommand, and sycl::_V1::detail::EmptyCommand.
Definition at line 750 of file commands.cpp.
Referenced by getPiEventsBlocking().
readyForCleanup()
bool sycl::_V1::detail::Command::readyForCleanup () const virtual
Returns true iff this command is ready to be submitted for cleanup.
Reimplemented in sycl::_V1::detail::ExecCGCommand, sycl::_V1::detail::AllocaCommandBase, and sycl::_V1::detail::ReleaseCommand.
Definition at line 754 of file commands.cpp.
References MEnqueueStatus, MLeafCounter, and sycl::_V1::detail::EnqueueResultT::SyclEnqueueSuccess.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::decrementLeafCountersForRecord(), and sycl::_V1::detail::ExecCGCommand::readyForCleanup().
resolveReleaseDependencies()
void sycl::_V1::detail::Command::resolveReleaseDependencies (std::set< Command * > & list)
Looks at all the dependencies for the release command and enables instrumentation to report these dependencies as edges.
Definition at line 910 of file commands.cpp.
References MAddress, MStreamID, MTraceEvent, and MType.
Referenced by sycl::_V1::detail::Scheduler::waitForRecordToFinish().
supportsPostEnqueueCleanup()
bool sycl::_V1::detail::Command::supportsPostEnqueueCleanup () const virtual
Returns true iff this command can be freed by post enqueue cleanup.
Reimplemented in sycl::_V1::detail::ExecCGCommand, sycl::_V1::detail::AllocaCommandBase, and sycl::_V1::detail::ReleaseCommand.
Definition at line 752 of file commands.cpp.
Referenced by enqueue(), and sycl::_V1::detail::ExecCGCommand::supportsPostEnqueueCleanup().
waitForEvents()
void sycl::_V1::detail::Command::waitForEvents (QueueImplPtr Queue, std::vector< EventImplPtr > & RawEvents, sycl::detail::pi::PiEvent & Event) protected
Definition at line 454 of file commands.cpp.
References sycl::_V1::detail::flushCrossQueueDeps(), getPiEvents(), getWorkerQueue(), MEvent, piEnqueueEventsWait(), and piEventsWait().
waitForPreparedHostEvents()
void sycl::_V1::detail::Command::waitForPreparedHostEvents () const protected
Definition at line 449 of file commands.cpp.
References MPreparedHostDepsEvents.
Friends And Related Function Documentation
DispatchHostTask
friend class DispatchHostTask friend
Definition at line 293 of file commands.hpp.
Member Data Documentation
MAddress
void* sycl::_V1::detail::Command::MAddress = nullptr
Reserved for storing the object address such as SPIR-V or memory object address.
Definition at line 358 of file commands.hpp.
Referenced by emitEdgeEventForCommandDependence(), emitEdgeEventForEventDependence(), sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::ExecCGCommand::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), sycl::_V1::detail::UnMapMemObject::emitInstrumentationData(), makeTraceEventProlog(), and resolveReleaseDependencies().
MAddressString
std::string sycl::_V1::detail::Command::MAddressString
Buffer to build the address string.
Definition at line 360 of file commands.hpp.
Referenced by makeTraceEventProlog().
MBlockedUsers
std::vector<EventImplPtr> sycl::_V1::detail::Command::MBlockedUsers
Contains list of commands that depends on the host command explicitly (by depends_on).
Not involved in the cleanup process since it is one-way link and does not hold resources. Using EventImplPtr since enqueueUnblockedCommands and event.wait may intersect with command enqueue.
Definition at line 398 of file commands.hpp.
Referenced by addBlockedUserUnique(), and sycl::_V1::detail::Scheduler::NotifyHostTaskCompletion().
MBlockedUsersMutex
std::mutex sycl::_V1::detail::Command::MBlockedUsersMutex
Definition at line 399 of file commands.hpp.
Referenced by sycl::_V1::detail::Scheduler::GraphProcessor::handleBlockingCmd(), and sycl::_V1::detail::Scheduler::NotifyHostTaskCompletion().
MBlockReason
BlockReason sycl::_V1::detail::Command::MBlockReason
Definition at line 340 of file commands.hpp.
Referenced by getBlockReason(), and sycl::_V1::detail::isHostAccessorCmd().
MCommandBuffer
sycl::detail::pi::PiExtCommandBuffer sycl::_V1::detail::Command::MCommandBuffer protected
CommandBuffer which will be used to submit to instead of the queue, if set.
Definition at line 409 of file commands.hpp.
Referenced by getCommandBuffer(), and sycl::_V1::detail::ExecCGCommand::producesPiEvent().
MCommandName
std::string sycl::_V1::detail::Command::MCommandName
Buffer to build the command end-user understandable name.
Definition at line 364 of file commands.hpp.
Referenced by sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), and makeTraceEventProlog().
MCommandNodeType
std::string sycl::_V1::detail::Command::MCommandNodeType
Buffer to build the command node type.
Definition at line 362 of file commands.hpp.
Referenced by sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), makeTraceEventEpilog(), and makeTraceEventProlog().
MDeps
std::vector<DepDesc> sycl::_V1::detail::Command::MDeps
Contains list of dependencies(edges)
Definition at line 320 of file commands.hpp.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::addCommandGraphUpdate(), addDep(), sycl::_V1::detail::checkForCircularDependency(), sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommand(), sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), clearAllDependencies(), sycl::_V1::detail::Scheduler::enqueueCommandForCG(), sycl::_V1::detail::Scheduler::GraphBuilder::findDepForRecord(), sycl::_V1::detail::Scheduler::NotifyHostTaskCompletion(), sycl::_V1::detail::EmptyCommand::printDot(), sycl::_V1::detail::ReleaseCommand::printDot(), sycl::_V1::detail::AllocaCommand::printDot(), sycl::_V1::detail::AllocaSubBufCommand::printDot(), sycl::_V1::detail::MapMemObject::printDot(), sycl::_V1::detail::UnMapMemObject::printDot(), sycl::_V1::detail::MemCpyCommand::printDot(), sycl::_V1::detail::MemCpyCommandHost::printDot(), sycl::_V1::detail::ExecCGCommand::printDot(), sycl::_V1::detail::UpdateHostRequirementCommand::printDot(), sycl::_V1::detail::KernelFusionCommand::printDot(), and sycl::_V1::detail::UpdateCommandBufferCommand::printDot().
MEnqueueMtx
std::mutex sycl::_V1::detail::Command::MEnqueueMtx protected
Mutex used to protect enqueueing from race conditions.
Definition at line 291 of file commands.hpp.
Referenced by enqueue().
MEnqueueStatus
std::atomic<EnqueueResultT::ResultT> sycl::_V1::detail::Command::MEnqueueStatus
Describes the status of the command.
Definition at line 343 of file commands.hpp.
Referenced by Command(), enqueue(), isEnqueueBlocked(), isSuccessfullyEnqueued(), readyForCleanup(), and sycl::_V1::detail::Scheduler::releaseHostAccessor().
MEvent
EventImplPtr sycl::_V1::detail::Command::MEvent protected
Definition at line 257 of file commands.hpp.
Referenced by Command(), enqueue(), sycl::_V1::detail::ExecCGCommand::ExecCGCommand(), getEvent(), isBlocking(), sycl::_V1::detail::MemCpyCommand::MemCpyCommand(), sycl::_V1::detail::MemCpyCommandHost::MemCpyCommandHost(), sycl::_V1::detail::DispatchHostTask::operator()(), sycl::_V1::detail::UnMapMemObject::producesPiEvent(), sycl::_V1::detail::MemCpyCommand::producesPiEvent(), sycl::_V1::detail::ExecCGCommand::readyForCleanup(), waitForEvents(), and ~Command().
MFirstInstance
bool sycl::_V1::detail::Command::MFirstInstance = false
Flag to indicate if this is the first time we are seeing this payload.
Definition at line 368 of file commands.hpp.
Referenced by sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData(), sycl::_V1::detail::AllocaCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaSubBufCommand::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), sycl::_V1::detail::UnMapMemObject::emitInstrumentationData(), and makeTraceEventProlog().
MInstanceID
uint64_t sycl::_V1::detail::Command::MInstanceID = 0
Instance ID tracked for the command.
Definition at line 370 of file commands.hpp.
Referenced by emitEnqueuedEventSignal(), emitInstrumentation(), sycl::_V1::detail::ExecCGCommand::emitInstrumentationData(), sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), makeTraceEventEpilog(), and makeTraceEventProlog().
MIsBlockable
bool sycl::_V1::detail::Command::MIsBlockable = false
Indicates whether the command can be blocked from enqueueing.
Definition at line 324 of file commands.hpp.
Referenced by enqueue(), and isEnqueueBlocked().
MLeafCounter
unsigned sycl::_V1::detail::Command::MLeafCounter = 0
Counts the number of memory objects this command is a leaf for.
Definition at line 326 of file commands.hpp.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::addNodeToLeaves(), sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommand(), sycl::_V1::detail::Scheduler::GraphBuilder::decrementLeafCountersForRecord(), enqueue(), sycl::_V1::detail::Scheduler::NotifyHostTaskCompletion(), readyForCleanup(), and sycl::_V1::detail::ExecCGCommand::readyForCleanup().
MMarkedForCleanup
bool sycl::_V1::detail::Command::MMarkedForCleanup = false
Indicates that the node will be freed by graph cleanup.
Such nodes should be ignored by other cleanup mechanisms (e.g. during memory object removal).
Definition at line 391 of file commands.hpp.
Referenced by enqueue(), and sycl::_V1::detail::Scheduler::NotifyHostTaskCompletion().
MMarks
Marks sycl::_V1::detail::Command::MMarks
Used for marking the node during graph traversal.
Definition at line 335 of file commands.hpp.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), and sycl::_V1::detail::markNodeAsVisited().
MPreparedDepsEvents
std::vector<EventImplPtr>& sycl::_V1::detail::Command::MPreparedDepsEvents protected
Dependency events prepared for waiting by backend.
See processDepEvent for details.
Definition at line 262 of file commands.hpp.
Referenced by clearAllDependencies(), getPreparedDepsEvents(), and processDepEvent().
MPreparedHostDepsEvents
std::vector<EventImplPtr>& sycl::_V1::detail::Command::MPreparedHostDepsEvents protected
Definition at line 263 of file commands.hpp.
Referenced by clearAllDependencies(), getPreparedHostDepsEvents(), processDepEvent(), and waitForPreparedHostEvents().
MQueue
QueueImplPtr sycl::_V1::detail::Command::MQueue protected
Definition at line 256 of file commands.hpp.
Referenced by Command(), sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::ExecCGCommand::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData(), sycl::_V1::detail::AllocaSubBufCommand::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), sycl::_V1::detail::UnMapMemObject::emitInstrumentationData(), sycl::_V1::detail::AllocaSubBufCommand::getMemAllocation(), getQueue(), getWorkerContext(), sycl::_V1::detail::MemCpyCommand::MemCpyCommand(), sycl::_V1::detail::MemCpyCommandHost::MemCpyCommandHost(), sycl::_V1::detail::ReleaseCommand::printDot(), sycl::_V1::detail::AllocaCommand::printDot(), sycl::_V1::detail::AllocaSubBufCommand::printDot(), sycl::_V1::detail::MapMemObject::printDot(), sycl::_V1::detail::UnMapMemObject::printDot(), sycl::_V1::detail::MemCpyCommand::printDot(), sycl::_V1::detail::MemCpyCommandHost::printDot(), sycl::_V1::detail::ExecCGCommand::printDot(), sycl::_V1::detail::UpdateHostRequirementCommand::printDot(), sycl::_V1::detail::KernelFusionCommand::printDot(), sycl::_V1::detail::UnMapMemObject::producesPiEvent(), sycl::_V1::detail::MemCpyCommand::producesPiEvent(), and sycl::_V1::detail::KernelFusionCommand::resetQueue().
MShouldCompleteEventIfPossible
bool sycl::_V1::detail::Command::MShouldCompleteEventIfPossible = true
Definition at line 386 of file commands.hpp.
Referenced by enqueue().
MStreamID
int32_t sycl::_V1::detail::Command::MStreamID = -1
The stream under which the traces are emitted.
Stream ids are positive integers and we set it to an invalid value.
Definition at line 355 of file commands.hpp.
Referenced by Command(), emitEdgeEventForCommandDependence(), emitEdgeEventForEventDependence(), emitEnqueuedEventSignal(), emitInstrumentation(), sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::ExecCGCommand::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData(), sycl::_V1::detail::AllocaCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaSubBufCommand::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), sycl::_V1::detail::UnMapMemObject::emitInstrumentationData(), makeTraceEventEpilog(), makeTraceEventProlog(), and resolveReleaseDependencies().
MSubmissionCodeLocation
code_location sycl::_V1::detail::Command::MSubmissionCodeLocation
Represents code location of command submission to SYCL API, assigned with the valid value only if command execution is async (host task) or delayed (blocked by host task).
Definition at line 374 of file commands.hpp.
Referenced by copySubmissionCodeLocation(), enqueue(), and sycl::_V1::detail::DispatchHostTask::operator()().
MSubmissionFileName
std::string sycl::_V1::detail::Command::MSubmissionFileName
Introduces string to handle memory management since code_location struct works with raw char arrays.
Definition at line 377 of file commands.hpp.
Referenced by copySubmissionCodeLocation().
MSubmissionFunctionName
std::string sycl::_V1::detail::Command::MSubmissionFunctionName
Definition at line 378 of file commands.hpp.
Referenced by copySubmissionCodeLocation().
MSyncPointDeps
std::vector<sycl::detail::pi::PiExtSyncPoint> sycl::_V1::detail::Command::MSyncPointDeps protected
List of sync points for submissions to a command buffer.
Definition at line 411 of file commands.hpp.
MTraceEvent
void* sycl::_V1::detail::Command::MTraceEvent = nullptr
The event for node_create and task_begin.
Definition at line 351 of file commands.hpp.
Referenced by emitEdgeEventForCommandDependence(), emitEdgeEventForEventDependence(), emitEnqueuedEventSignal(), emitInstrumentation(), sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::ExecCGCommand::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData(), sycl::_V1::detail::AllocaSubBufCommand::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), sycl::_V1::detail::UnMapMemObject::emitInstrumentationData(), sycl::_V1::detail::event_impl::instrumentationProlog(), makeTraceEventEpilog(), makeTraceEventProlog(), and resolveReleaseDependencies().
MTraceEventPrologComplete
bool sycl::_V1::detail::Command::MTraceEventPrologComplete = false
Flag to indicate if makeTraceEventProlog() has been run.
Definition at line 366 of file commands.hpp.
Referenced by makeTraceEventEpilog(), and makeTraceEventProlog().
MType
CommandType sycl::_V1::detail::Command::MType protected
The type of the command.
Definition at line 289 of file commands.hpp.
Referenced by sycl::_V1::detail::ExecCGCommand::emitInstrumentationData(), sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), getType(), isFusable(), isHostTask(), makeTraceEventProlog(), and resolveReleaseDependencies().
MUsers
std::unordered_set<Command *> sycl::_V1::detail::Command::MUsers
Contains list of commands that depend on the command.
Definition at line 322 of file commands.hpp.
Referenced by addUser(), sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommand(), sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), sycl::_V1::detail::Scheduler::enqueueCommandForCG(), and sycl::_V1::detail::printDotRecursive().
MWorkerQueue
QueueImplPtr sycl::_V1::detail::Command::MWorkerQueue protected
Definition at line 258 of file commands.hpp.
Referenced by Command(), getWorkerQueue(), sycl::_V1::detail::MemCpyCommand::MemCpyCommand(), sycl::_V1::detail::MemCpyCommandHost::MemCpyCommandHost(), and sycl::_V1::detail::KernelFusionCommand::resetQueue().
The documentation for this class was generated from the following files:
source/detail/scheduler/commands.hpp
source/detail/scheduler/commands.cpp