DPC++ Runtime: sycl::_V1::detail::device_image_impl Class Reference
sycl::_V1::detail::device_image_impl Class Reference
#include <detail/device_image_impl.hpp>
Classes
struct SpecConstDescT
Public Types
using SpecConstMapT = std::map< std::string, std::vector< SpecConstDescT > >
Public Member Functions
device_image_impl (const RTDeviceBinaryImage *BinImage, context Context, std::vector< device > Devices, bundle_state State, std::shared_ptr< std::vector< kernel_id >> KernelIDs, sycl::detail::pi::PiProgram Program)
device_image_impl (const RTDeviceBinaryImage *BinImage, context Context, std::vector< device > Devices, bundle_state State, std::shared_ptr< std::vector< kernel_id >> KernelIDs, sycl::detail::pi::PiProgram Program, const SpecConstMapT &SpecConstMap, const std::vector< unsigned char > &SpecConstsBlob)
bool has_kernel (const kernel_id &KernelIDCand) const noexcept
bool has_kernel (const kernel_id &KernelIDCand, const device &DeviceCand) const noexcept
const std::vector< kernel_id > & get_kernel_ids () const noexcept
bool has_specialization_constants () const noexcept
bool all_specialization_constant_native () const noexcept
bool has_specialization_constant (const char *SpecName) const noexcept
void set_specialization_constant_raw_value (const char *SpecName, const void *Value) noexcept
void get_specialization_constant_raw_value (const char *SpecName, void *ValueRet) const noexcept
bool is_specialization_constant_set (const char *SpecName) const noexcept
bool is_any_specialization_constant_set () const noexcept
bool specialization_constants_replaced_with_default () const noexcept
bundle_state get_state () const noexcept
void set_state (bundle_state NewState) noexcept
const std::vector< device > & get_devices () const noexcept
bool compatible_with_device (const device &Dev) const
const sycl::detail::pi::PiProgram & get_program_ref () const noexcept
const RTDeviceBinaryImage *& get_bin_image_ref () noexcept
const context & get_context () const noexcept
std::shared_ptr< std::vector< kernel_id > > & get_kernel_ids_ptr () noexcept
std::vector< unsigned char > & get_spec_const_blob_ref () noexcept
sycl::detail::pi::PiMem & get_spec_const_buffer_ref () noexcept
const SpecConstMapT & get_spec_const_data_ref () const noexcept
std::mutex & get_spec_const_data_lock () noexcept
pi_native_handle getNative () const
~device_image_impl ()
Detailed Description
Definition at line 44 of file device_image_impl.hpp.
Member Typedef Documentation
SpecConstMapT
using sycl::_V1::detail::device_image_impl::SpecConstMapT = std::map<std::string, std::vector<SpecConstDescT> >
Definition at line 58 of file device_image_impl.hpp.
Constructor & Destructor Documentation
device_image_impl() [1/2]
sycl::_V1::detail::device_image_impl::device_image_impl (const RTDeviceBinaryImage * BinImage, context Context, std::vector< device > Devices, bundle_state State, std::shared_ptr< std::vector< kernel_id >> KernelIDs, sycl::detail::pi::PiProgram Program) inline
Definition at line 60 of file device_image_impl.hpp.
device_image_impl() [2/2]
sycl::_V1::detail::device_image_impl::device_image_impl (const RTDeviceBinaryImage * BinImage, context Context, std::vector< device > Devices, bundle_state State, std::shared_ptr< std::vector< kernel_id >> KernelIDs, sycl::detail::pi::PiProgram Program, const SpecConstMapT & SpecConstMap, const std::vector< unsigned char > & SpecConstsBlob) inline
Definition at line 71 of file device_image_impl.hpp.
~device_image_impl()
sycl::_V1::detail::device_image_impl::~device_image_impl () inline
Definition at line 302 of file device_image_impl.hpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::detail::memReleaseHelper(), and piProgramRelease().
Member Function Documentation
all_specialization_constant_native()
bool sycl::_V1::detail::device_image_impl::all_specialization_constant_native () const inline noexcept
Definition at line 117 of file device_image_impl.hpp.
References __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV32, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64, pi_device_binary_struct::DeviceTargetSpec, sycl::_V1::ext_oneapi_level_zero, sycl::_V1::context::get_backend(), sycl::_V1::detail::RTDeviceBinaryImage::getRawData(), and sycl::_V1::opencl.
compatible_with_device()
bool sycl::_V1::detail::device_image_impl::compatible_with_device (const device & Dev) const inline
Definition at line 240 of file device_image_impl.hpp.
References any_of().
get_bin_image_ref()
const RTDeviceBinaryImage*& sycl::_V1::detail::device_image_impl::get_bin_image_ref () inline noexcept
Definition at line 250 of file device_image_impl.hpp.
get_context()
const context& sycl::_V1::detail::device_image_impl::get_context () const inline noexcept
Definition at line 252 of file device_image_impl.hpp.
get_devices()
const std::vector<device>& sycl::_V1::detail::device_image_impl::get_devices () const inline noexcept
Definition at line 238 of file device_image_impl.hpp.
get_kernel_ids()
const std::vector<kernel_id>& sycl::_V1::detail::device_image_impl::get_kernel_ids () const inline noexcept
Definition at line 105 of file device_image_impl.hpp.
get_kernel_ids_ptr()
std::shared_ptr<std::vector<kernel_id> >& sycl::_V1::detail::device_image_impl::get_kernel_ids_ptr () inline noexcept
Definition at line 254 of file device_image_impl.hpp.
get_program_ref()
const sycl::detail::pi::PiProgram& sycl::_V1::detail::device_image_impl::get_program_ref () const inline noexcept
Definition at line 246 of file device_image_impl.hpp.
get_spec_const_blob_ref()
std::vector<unsigned char>& sycl::_V1::detail::device_image_impl::get_spec_const_blob_ref () inline noexcept
Definition at line 258 of file device_image_impl.hpp.
get_spec_const_buffer_ref()
sycl::detail::pi::PiMem& sycl::_V1::detail::device_image_impl::get_spec_const_buffer_ref () inline noexcept
Definition at line 262 of file device_image_impl.hpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::detail::memBufferCreateHelper(), PI_MEM_FLAGS_ACCESS_RW, and PI_MEM_FLAGS_HOST_PTR_COPY.
get_spec_const_data_lock()
std::mutex& sycl::_V1::detail::device_image_impl::get_spec_const_data_lock () inline noexcept
Definition at line 284 of file device_image_impl.hpp.
get_spec_const_data_ref()
const SpecConstMapT& sycl::_V1::detail::device_image_impl::get_spec_const_data_ref () const inline noexcept
Definition at line 280 of file device_image_impl.hpp.
get_specialization_constant_raw_value()
void sycl::_V1::detail::device_image_impl::get_specialization_constant_raw_value (const char * SpecName, void * ValueRet) const inline noexcept
Definition at line 181 of file device_image_impl.hpp.
References sycl::_V1::detail::ByteArray::begin(), is_specialization_constant_set(), and sycl::_V1::detail::ByteArray::size().
get_state()
bundle_state sycl::_V1::detail::device_image_impl::get_state () const inline noexcept
Definition at line 234 of file device_image_impl.hpp.
getNative()
pi_native_handle sycl::_V1::detail::device_image_impl::getNative () const inline
Definition at line 288 of file device_image_impl.hpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::opencl, piextProgramGetNativeHandle(), and piProgramRetain().
has_kernel() [1/2]
bool sycl::_V1::detail::device_image_impl::has_kernel (const kernel_id & KernelIDCand) const inline noexcept
Definition at line 83 of file device_image_impl.hpp.
Referenced by has_kernel().
has_kernel() [2/2]
bool sycl::_V1::detail::device_image_impl::has_kernel (const kernel_id & KernelIDCand, const device & DeviceCand) const inline noexcept
Definition at line 88 of file device_image_impl.hpp.
References sycl::_V1::detail::getSyclObjImpl(), and has_kernel().
has_specialization_constant()
bool sycl::_V1::detail::device_image_impl::has_specialization_constant (const char * SpecName) const inline noexcept
Definition at line 138 of file device_image_impl.hpp.
has_specialization_constants()
bool sycl::_V1::detail::device_image_impl::has_specialization_constants () const inline noexcept
Definition at line 109 of file device_image_impl.hpp.
is_any_specialization_constant_set()
bool sycl::_V1::detail::device_image_impl::is_any_specialization_constant_set () const inline noexcept
Definition at line 213 of file device_image_impl.hpp.
is_specialization_constant_set()
bool sycl::_V1::detail::device_image_impl::is_specialization_constant_set (const char * SpecName) const inline noexcept
Definition at line 200 of file device_image_impl.hpp.
Referenced by get_specialization_constant_raw_value().
set_specialization_constant_raw_value()
void sycl::_V1::detail::device_image_impl::set_specialization_constant_raw_value (const char * SpecName, const void * Value) inline noexcept
Definition at line 146 of file device_image_impl.hpp.
References sycl::_V1::detail::ByteArray::begin(), and sycl::_V1::detail::ByteArray::size().
set_state()
void sycl::_V1::detail::device_image_impl::set_state (bundle_state NewState) inline noexcept
Definition at line 236 of file device_image_impl.hpp.
specialization_constants_replaced_with_default()
bool sycl::_V1::detail::device_image_impl::specialization_constants_replaced_with_default () const inline noexcept
Definition at line 228 of file device_image_impl.hpp.
References sycl::_V1::detail::DeviceBinaryProperty::asUint32(), and sycl::_V1::detail::RTDeviceBinaryImage::getProperty().
The documentation for this class was generated from the following file:
source/detail/device_image_impl.hpp