DPC++ Runtime: cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > > Class Template Reference
cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > > Class Template Reference
Specialization of the generic class 'reducer'.
#include <CL/sycl/ONEAPI/reduction.hpp>
Public Member Functions
reducer ()
reducer (const T &, BinaryOperation)
void combine (const T &Partial)
template<typename _T = T>
enable_if_t< sycl::detail::IsPlus< _T, BinaryOperation >::value &&sycl::detail::is_geninteger< _T >::value > operator++ ()
template<typename _T = T>
enable_if_t< sycl::detail::IsPlus< _T, BinaryOperation >::value &&sycl::detail::is_geninteger< _T >::value > operator++ (int)
template<typename _T = T>
enable_if_t< sycl::detail::IsPlus< _T, BinaryOperation >::value > operator+= (const _T &Partial)
template<typename _T = T>
enable_if_t< sycl::detail::IsMultiplies< _T, BinaryOperation >::value > operator*= (const _T &Partial)
template<typename _T = T>
enable_if_t< sycl::detail::IsBitOR< _T, BinaryOperation >::value > operator|= (const _T &Partial)
template<typename _T = T>
enable_if_t< sycl::detail::IsBitXOR< _T, BinaryOperation >::value > operator^= (const _T &Partial)
template<typename _T = T>
enable_if_t< sycl::detail::IsBitAND< _T, BinaryOperation >::value > operator&= (const _T &Partial)
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&IsReduOptForFastAtomicFetch< T, _BinaryOperation >::value &&sycl::detail::IsPlus< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic ADD operation: *ReduVarPtr += MValue;.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&IsReduOptForFastAtomicFetch< T, _BinaryOperation >::value &&sycl::detail::IsBitOR< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic BITWISE OR operation: *ReduVarPtr |= MValue;.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&IsReduOptForFastAtomicFetch< T, _BinaryOperation >::value &&sycl::detail::IsBitXOR< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic BITWISE XOR operation: *ReduVarPtr ^= MValue;.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&IsReduOptForFastAtomicFetch< T, _BinaryOperation >::value &&sycl::detail::IsBitAND< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic BITWISE AND operation: *ReduVarPtr &= MValue;.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&IsReduOptForFastAtomicFetch< T, _BinaryOperation >::value &&sycl::detail::IsMinimum< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic MIN operation: *ReduVarPtr = ONEAPI::minimum(*ReduVarPtr, MValue);.
template<typename _T = T, class _BinaryOperation = BinaryOperation>
enable_if_t< std::is_same< typename remove_AS< _T >::type, T >::value &&IsReduOptForFastAtomicFetch< T, _BinaryOperation >::value &&sycl::detail::IsMaximum< T, _BinaryOperation >::value > atomic_combine (_T *ReduVarPtr) const
Atomic MAX operation: *ReduVarPtr = ONEAPI::maximum(*ReduVarPtr, MValue);.
Static Public Member Functions
template<typename _T = T, class _BinaryOperation = BinaryOperation>
static enable_if_t< has_known_identity_impl< _BinaryOperation, _T >::value, _T > getIdentity ()
Public Attributes
T MValue
Detailed Description
template<typename T, class BinaryOperation>
class cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >
Specialization of the generic class 'reducer'.
It is used for reductions of those types and operations for which the identity value is known.
It allows to reduce the size of the 'reducer' object by not holding the identity field inside it and allows to add a default constructor.
Also, for many types with known identity the operation 'atomic_combine()' is implemented here, which allows to use more efficient version of kernels using those operations, which are based on functionality provided by sycl::atomic class.
For example, it is known that 0 is identity for ONEAPI::plus operations accepting native scalar types to which scalar 0 is convertible. Also, for int32/64 types the atomic_combine() is lowered to sycl::atomic::fetch_add().
Definition at line 170 of file reduction.hpp.
Constructor & Destructor Documentation
reducer() [1/2]
template<typename T , class BinaryOperation > cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::reducer () inline
Definition at line 173 of file reduction.hpp.
reducer() [2/2]
template<typename T , class BinaryOperation > cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::reducer (const T & , BinaryOperation) inline
Definition at line 174 of file reduction.hpp.
Member Function Documentation
atomic_combine() [1/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && IsReduOptForFastAtomicFetch<T, _BinaryOperation>::value && sycl::detail::IsPlus<T, _BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic ADD operation: *ReduVarPtr += MValue;.
Definition at line 236 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_add().
atomic_combine() [2/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && IsReduOptForFastAtomicFetch<T, _BinaryOperation>::value && sycl::detail::IsBitOR<T, _BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic BITWISE OR operation: *ReduVarPtr |= MValue;.
Definition at line 246 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_or().
atomic_combine() [3/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && IsReduOptForFastAtomicFetch<T, _BinaryOperation>::value && sycl::detail::IsBitXOR<T, _BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic BITWISE XOR operation: *ReduVarPtr ^= MValue;.
Definition at line 256 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_xor().
atomic_combine() [4/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && IsReduOptForFastAtomicFetch<T, _BinaryOperation>::value && sycl::detail::IsBitAND<T, _BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic BITWISE AND operation: *ReduVarPtr &= MValue;.
Definition at line 266 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_and().
atomic_combine() [5/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && IsReduOptForFastAtomicFetch<T, _BinaryOperation>::value && sycl::detail::IsMinimum<T, _BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic MIN operation: *ReduVarPtr = ONEAPI::minimum(*ReduVarPtr, MValue);.
Definition at line 276 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_min().
atomic_combine() [6/6]
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> enable_if_t<std::is_same<typename remove_AS<_T>::type, T>::value && IsReduOptForFastAtomicFetch<T, _BinaryOperation>::value && sycl::detail::IsMaximum<T, _BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::atomic_combine (_T * ReduVarPtr) const inline
Atomic MAX operation: *ReduVarPtr = ONEAPI::maximum(*ReduVarPtr, MValue);.
Definition at line 286 of file reduction.hpp.
References cl::sycl::atomic< T, addressSpace >::fetch_max().
combine()
template<typename T , class BinaryOperation > void cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::combine (const T & Partial) inline
Definition at line 176 of file reduction.hpp.
getIdentity()
template<typename T , class BinaryOperation > template<typename _T = T, class _BinaryOperation = BinaryOperation> static enable_if_t<has_known_identity_impl<_BinaryOperation, _T>::value, _T> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::getIdentity () inline static
Definition at line 183 of file reduction.hpp.
operator&=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<sycl::detail::IsBitAND<_T, BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator&= (const _T & Partial) inline
Definition at line 227 of file reduction.hpp.
operator*=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<sycl::detail::IsMultiplies<_T, BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator*= (const _T & Partial) inline
Definition at line 209 of file reduction.hpp.
operator++() [1/2]
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<sycl::detail::IsPlus<_T, BinaryOperation>::value && sycl::detail::is_geninteger<_T>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator++ () inline
Definition at line 190 of file reduction.hpp.
operator++() [2/2]
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<sycl::detail::IsPlus<_T, BinaryOperation>::value && sycl::detail::is_geninteger<_T>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator++ (int) inline
Definition at line 197 of file reduction.hpp.
operator+=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<sycl::detail::IsPlus<_T, BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator+= (const _T & Partial) inline
Definition at line 203 of file reduction.hpp.
operator^=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<sycl::detail::IsBitXOR<_T, BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator^= (const _T & Partial) inline
Definition at line 221 of file reduction.hpp.
operator|=()
template<typename T , class BinaryOperation > template<typename _T = T> enable_if_t<sycl::detail::IsBitOR<_T, BinaryOperation>::value> cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::operator|= (const _T & Partial) inline
Definition at line 215 of file reduction.hpp.
Member Data Documentation
MValue
template<typename T , class BinaryOperation > T cl::sycl::ONEAPI::detail::reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >::MValue
Definition at line 291 of file reduction.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/ONEAPI/reduction.hpp