DPC++ Runtime: cl::sycl::INTEL::gpu::simd< Ty, N > Class Template Reference
cl::sycl::INTEL::gpu::simd< Ty, N > Class Template Reference
DPC++ Explicit SIMD API
The simd vector class.
#include <CL/sycl/INTEL/esimd/detail/esimd_types.hpp>
Public Types
using vector_type = vector_type_t< Ty, N >
The underlying builtin data type.
using element_type = Ty
The element type of this simd object.
Public Member Functions
operator const vector_type & () const &
operator vector_type & () &
vector_type data () const
simd read () const
Whole region read.
simd & write (const simd &Val)
Whole region write.
void merge (const simd &Val, const mask_type_t< N > &Mask)
Whole region update with predicates.
void merge (const simd &Val1, simd Val2, const mask_type_t< N > &Mask)
constexpr simd & operator= (const simd &) &=default
{@ Assignment operators.
constexpr simd & operator= (simd &&) &=default
template<typename EltTy >
auto format () &
View this simd object in a different element type.
template<typename EltTy , int Height, int Width>
auto format () &
View as a 2-dimensional simd_view.
template<int Size, int Stride>
simd_view< simd, region1d_t< Ty, Size, Stride > > select (uint16_t Offset=0) &
1D region select, apply a region on top of this LValue object.
template<int Size, int Stride>
simd< Ty, Size > select (uint16_t Offset=0) &&
1D region select, apply a region on top of this RValue object.
Ty operator[] (int i) const
Read a single element, by value only.
simd & operator++ ()
simd operator++ (int)
simd & operator-- ()
simd operator-- (int)
template<typename T1 = element_type, typename T2 = Ty, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>>
uint16_t any ()
Any operation.
template<typename T1 = element_type, typename T2 = Ty, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>>
uint16_t all ()
All operation.
template<typename RTy >
ESIMD_INLINE void writeRegion (RTy Region, const vector_type_t< typename RTy::element_type, RTy::length > &Val)
Write a simd-vector into a basic region of a simd object.
template<typename TR , typename UR >
ESIMD_INLINE void writeRegion (std::pair< TR, UR > Region, const vector_type_t< typename TR::element_type, TR::length > &Val)
Write a simd-vector into a nested region of a simd object.
constexpr simd ()=default
constexpr simd (const simd &other)
constexpr simd (simd &&other)
constexpr simd (const vector_type &Val)
constexpr simd (std::initializer_list< Ty > Ilist) noexcept
constexpr simd (Ty Val, Ty Step=Ty()) noexcept
Initialize a simd with an initial value and step.
Replicate
Replicate simd instance given a region.
template<int Rep>
simd< Ty, Rep *N > replicate ()
template<int Rep, int W>
simd< Ty, Rep *W > replicate (uint16_t Offset)
template<int Rep, int VS, int W>
simd< Ty, Rep *W > replicate (uint16_t Offset)
template<int Rep, int VS, int W, int HS>
simd< Ty, Rep *W > replicate (uint16_t Offset)
Static Public Attributes
static constexpr int length = N
The number of elements in this simd object.
Detailed Description
template<typename Ty, int N>
class cl::sycl::INTEL::gpu::simd< Ty, N >
The simd vector class.
This is a wrapper class for llvm vector values. Additionally this class supports region operations that map to Intel GPU regions. The type of a region select or format operation is of simd_view type, which models read-update-write semantics.
Definition at line 82 of file esimd_types.hpp.
Member Typedef Documentation
element_type
template<typename Ty, int N> using cl::sycl::INTEL::gpu::simd< Ty, N >::element_type = Ty
The element type of this simd object.
Definition at line 35 of file esimd.hpp.
vector_type
template<typename Ty, int N> using cl::sycl::INTEL::gpu::simd< Ty, N >::vector_type = vector_type_t<Ty, N>
The underlying builtin data type.
Definition at line 32 of file esimd.hpp.
Constructor & Destructor Documentation
simd() [1/6]
template<typename Ty, int N> constexpr cl::sycl::INTEL::gpu::simd< Ty, N >::simd () default
Constructors.
simd() [2/6]
template<typename Ty, int N> constexpr cl::sycl::INTEL::gpu::simd< Ty, N >::simd (const simd< Ty, N > & other) inline
Definition at line 46 of file esimd.hpp.
simd() [3/6]
template<typename Ty, int N> constexpr cl::sycl::INTEL::gpu::simd< Ty, N >::simd (simd< Ty, N > && other) inline
Definition at line 47 of file esimd.hpp.
simd() [4/6]
template<typename Ty, int N> constexpr cl::sycl::INTEL::gpu::simd< Ty, N >::simd (const vector_type & Val) inline
Definition at line 48 of file esimd.hpp.
simd() [5/6]
template<typename Ty, int N> constexpr cl::sycl::INTEL::gpu::simd< Ty, N >::simd (std::initializer_list< Ty > Ilist) inline noexcept
Definition at line 69 of file esimd.hpp.
simd() [6/6]
template<typename Ty, int N> constexpr cl::sycl::INTEL::gpu::simd< Ty, N >::simd (Ty Val, Ty Step = Ty()) inline noexcept
Initialize a simd with an initial value and step.
Definition at line 77 of file esimd.hpp.
Member Function Documentation
all()
template<typename Ty, int N> template<typename T1 = element_type, typename T2 = Ty, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>> uint16_t cl::sycl::INTEL::gpu::simd< Ty, N >::all () inline
All operation.
Returns
1 if all elements are set, 0 otherwise.
Definition at line 365 of file esimd.hpp.
any()
template<typename Ty, int N> template<typename T1 = element_type, typename T2 = Ty, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>> uint16_t cl::sycl::INTEL::gpu::simd< Ty, N >::any () inline
Any operation.
Returns
1 if any element is set, 0 otherwise.
Definition at line 355 of file esimd.hpp.
data()
template<typename Ty, int N> vector_type cl::sycl::INTEL::gpu::simd< Ty, N >::data () const inline
Definition at line 93 of file esimd.hpp.
Referenced by cl::sycl::INTEL::gpu::detail::__esimd_abs_common_internal(), cl::sycl::INTEL::gpu::block_store(), cl::sycl::INTEL::gpu::esimd_cbit(), cl::sycl::INTEL::gpu::esimd_dp4a(), cl::sycl::INTEL::gpu::esimd_fbh(), cl::sycl::INTEL::gpu::esimd_fbl(), cl::sycl::INTEL::gpu::esimd_imul(), cl::sycl::INTEL::gpu::esimd_lsr(), cl::sycl::INTEL::gpu::esimd_max(), cl::sycl::INTEL::gpu::esimd_min(), cl::sycl::INTEL::gpu::esimd_pack_mask(), cl::sycl::INTEL::gpu::esimd_raw_send_load(), cl::sycl::INTEL::gpu::esimd_raw_send_store(), cl::sycl::INTEL::gpu::esimd_raw_sends_load(), cl::sycl::INTEL::gpu::esimd_raw_sends_store(), cl::sycl::INTEL::gpu::esimd_rol(), cl::sycl::INTEL::gpu::esimd_ror(), cl::sycl::INTEL::gpu::esimd_sat(), cl::sycl::INTEL::gpu::esimd_shl(), cl::sycl::INTEL::gpu::esimd_shr(), cl::sycl::INTEL::gpu::flat_atomic(), cl::sycl::INTEL::gpu::scatter(), cl::sycl::INTEL::gpu::scatter4(), cl::sycl::INTEL::gpu::slm_atomic(), cl::sycl::INTEL::gpu::slm_block_store(), cl::sycl::INTEL::gpu::slm_load(), cl::sycl::INTEL::gpu::slm_load4(), cl::sycl::INTEL::gpu::slm_store(), cl::sycl::INTEL::gpu::slm_store4(), and cl::sycl::INTEL::gpu::simd_view< BaseTy, RegionTy >::write().
format() [1/2]
template<typename Ty, int N> template<typename EltTy > auto cl::sycl::INTEL::gpu::simd< Ty, N >::format () & inline
View this simd object in a different element type.
Definition at line 127 of file esimd.hpp.
Referenced by cl::sycl::INTEL::gpu::esimd_imul().
format() [2/2]
template<typename Ty, int N> template<typename EltTy , int Height, int Width> auto cl::sycl::INTEL::gpu::simd< Ty, N >::format () & inline
View as a 2-dimensional simd_view.
Definition at line 137 of file esimd.hpp.
merge() [1/2]
template<typename Ty, int N> void cl::sycl::INTEL::gpu::simd< Ty, N >::merge (const simd< Ty, N > & Val, const mask_type_t< N > & Mask) inline
Whole region update with predicates.
Definition at line 111 of file esimd.hpp.
References __esimd_wrregion().
Referenced by cl::sycl::INTEL::gpu::esimd_acos(), cl::sycl::INTEL::gpu::esimd_asin(), cl::sycl::INTEL::gpu::esimd_atan(), cl::sycl::INTEL::gpu::esimd_atan2(), cl::sycl::INTEL::gpu::esimd_atan2_fast(), cl::sycl::INTEL::gpu::esimd_cos_emu(), cl::sycl::INTEL::gpu::esimd_sin_emu(), and cl::sycl::INTEL::gpu::simd_view< BaseTy, RegionTy >::merge().
merge() [2/2]
template<typename Ty, int N> void cl::sycl::INTEL::gpu::simd< Ty, N >::merge (const simd< Ty, N > & Val1, simd< Ty, N > Val2, const mask_type_t< N > & Mask) inline
Definition at line 115 of file esimd.hpp.
operator const vector_type &()
template<typename Ty, int N> cl::sycl::INTEL::gpu::simd< Ty, N >::operator const vector_type & () const & inline
Definition at line 90 of file esimd.hpp.
operator vector_type &()
template<typename Ty, int N> cl::sycl::INTEL::gpu::simd< Ty, N >::operator vector_type & () & inline
Definition at line 91 of file esimd.hpp.
operator++() [1/2]
template<typename Ty, int N> simd& cl::sycl::INTEL::gpu::simd< Ty, N >::operator++ () inline
Definition at line 263 of file esimd.hpp.
operator++() [2/2]
template<typename Ty, int N> simd cl::sycl::INTEL::gpu::simd< Ty, N >::operator++ (int) inline
Definition at line 267 of file esimd.hpp.
operator--() [1/2]
template<typename Ty, int N> simd& cl::sycl::INTEL::gpu::simd< Ty, N >::operator-- () inline
Definition at line 272 of file esimd.hpp.
operator--() [2/2]
template<typename Ty, int N> simd cl::sycl::INTEL::gpu::simd< Ty, N >::operator-- (int) inline
Definition at line 276 of file esimd.hpp.
operator=() [1/2]
template<typename Ty, int N> constexpr simd& cl::sycl::INTEL::gpu::simd< Ty, N >::operator= (const simd< Ty, N > &) & default
{@ Assignment operators.
operator=() [2/2]
template<typename Ty, int N> constexpr simd& cl::sycl::INTEL::gpu::simd< Ty, N >::operator= (simd< Ty, N > &&) & default
operator[]()
template<typename Ty, int N> Ty cl::sycl::INTEL::gpu::simd< Ty, N >::operator[] (int i) const inline
Read a single element, by value only.
Definition at line 178 of file esimd.hpp.
read()
template<typename Ty, int N> simd cl::sycl::INTEL::gpu::simd< Ty, N >::read () const inline
Whole region read.
Definition at line 102 of file esimd.hpp.
Referenced by cl::sycl::INTEL::gpu::esimd_pln(), and cl::sycl::INTEL::gpu::simd_view< BaseTy, RegionTy >::merge().
replicate() [1/4]
template<typename Ty, int N> template<int Rep> simd<Ty, Rep * N> cl::sycl::INTEL::gpu::simd< Ty, N >::replicate () inline
Template Parameters
Rep is number of times region has to be replicated.
Returns
replicated simd instance.
Definition at line 301 of file esimd.hpp.
replicate() [2/4]
template<typename Ty, int N> template<int Rep, int W> simd<Ty, Rep * W> cl::sycl::INTEL::gpu::simd< Ty, N >::replicate (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
W is width of src region to replicate.
Parameters
Offset is offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 309 of file esimd.hpp.
replicate() [3/4]
template<typename Ty, int N> template<int Rep, int VS, int W> simd<Ty, Rep * W> cl::sycl::INTEL::gpu::simd< Ty, N >::replicate (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
VS vertical stride of src region to replicate.
W is width of src region to replicate.
Parameters
Offset is offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 319 of file esimd.hpp.
replicate() [4/4]
template<typename Ty, int N> template<int Rep, int VS, int W, int HS> simd<Ty, Rep * W> cl::sycl::INTEL::gpu::simd< Ty, N >::replicate (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
VS vertical stride of src region to replicate.
W is width of src region to replicate.
HS horizontal stride of src region to replicate.
Parameters
Offset is offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 343 of file esimd.hpp.
select() [1/2]
template<typename Ty, int N> template<int Size, int Stride> simd_view<simd, region1d_t<Ty, Size, Stride> > cl::sycl::INTEL::gpu::simd< Ty, N >::select (uint16_t Offset = 0) & inline
1D region select, apply a region on top of this LValue object.
Template Parameters
Size is the number of elements to be selected.
Stride is the element distance between two consecutive elements.
Parameters
Offset is the starting element offset.
Returns
the representing region object.
Definition at line 151 of file esimd.hpp.
Referenced by cl::sycl::INTEL::gpu::esimd_dp2(), cl::sycl::INTEL::gpu::esimd_dp3(), cl::sycl::INTEL::gpu::esimd_dp4(), cl::sycl::INTEL::gpu::esimd_dph(), cl::sycl::INTEL::gpu::esimd_line(), and cl::sycl::INTEL::gpu::esimd_pln().
select() [2/2]
template<typename Ty, int N> template<int Size, int Stride> simd<Ty, Size> cl::sycl::INTEL::gpu::simd< Ty, N >::select (uint16_t Offset = 0) && inline
1D region select, apply a region on top of this RValue object.
Template Parameters
Size is the number of elements to be selected.
Stride is the element distance between two consecutive elements.
Parameters
Offset is the starting element offset.
Returns
the value this region object refers to.
Definition at line 163 of file esimd.hpp.
References __esimd_rdregion().
write()
template<typename Ty, int N> simd& cl::sycl::INTEL::gpu::simd< Ty, N >::write (const simd< Ty, N > & Val) inline
Whole region write.
Definition at line 105 of file esimd.hpp.
writeRegion() [1/2]
template<typename Ty, int N> template<typename RTy > ESIMD_INLINE void cl::sycl::INTEL::gpu::simd< Ty, N >::writeRegion (RTy Region, const vector_type_t< typename RTy::element_type, RTy::length > & Val) inline
Write a simd-vector into a basic region of a simd object.
Definition at line 371 of file esimd.hpp.
References __esimd_wrregion(), ESIMD_INLINE, and cl::sycl::length().
writeRegion() [2/2]
template<typename Ty, int N> template<typename TR , typename UR > ESIMD_INLINE void cl::sycl::INTEL::gpu::simd< Ty, N >::writeRegion (std::pair< TR, UR > Region, const vector_type_t< typename TR::element_type, TR::length > & Val) inline
Write a simd-vector into a nested region of a simd object.
Definition at line 399 of file esimd.hpp.
References __esimd_wrregion(), and cl::sycl::length().
Member Data Documentation
length
template<typename Ty, int N> constexpr int cl::sycl::INTEL::gpu::simd< Ty, N >::length = N static
The number of elements in this simd object.
Definition at line 38 of file esimd.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/INTEL/esimd/detail/esimd_types.hpp
include/CL/sycl/INTEL/esimd/esimd.hpp