DPC++ Runtime: ReleaseGuard< T > Class Template Reference
ReleaseGuard< T > Class Template Reference
RAII object that calls the reference count release function on the held PI object on destruction.
Public Member Functions
ReleaseGuard ()=delete
ReleaseGuard (T Obj)
Obj can be nullptr.
ReleaseGuard (ReleaseGuard &&Other) noexcept
ReleaseGuard (const ReleaseGuard &)=delete
~ReleaseGuard ()
Calls the related PI object release function if the object held is not nullptr or if dismiss has not been called.
ReleaseGuard & operator= (const ReleaseGuard &)=delete
ReleaseGuard & operator= (ReleaseGuard &&Other)
void dismiss ()
End the guard and do not release the reference count of the held PI object.
ReleaseGuard ()=delete
ReleaseGuard (T Obj)
Obj can be nullptr.
ReleaseGuard (ReleaseGuard &&Other) noexcept
ReleaseGuard (const ReleaseGuard &)=delete
~ReleaseGuard ()
Calls the related PI object release function if the object held is not nullptr or if dismiss has not been called.
ReleaseGuard & operator= (const ReleaseGuard &)=delete
ReleaseGuard & operator= (ReleaseGuard &&Other)
void dismiss ()
End the guard and do not release the reference count of the held PI object.
Detailed Description
template<typename T>
class ReleaseGuard< T >
RAII object that calls the reference count release function on the held PI object on destruction.
The dismiss function stops the release from happening on destruction.
Definition at line 588 of file pi_cuda.cpp.
Constructor & Destructor Documentation
ReleaseGuard() [1/8]
template<typename T > ReleaseGuard< T >::ReleaseGuard () delete
ReleaseGuard() [2/8]
template<typename T > ReleaseGuard< T >::ReleaseGuard (T Obj) inline explicit
Obj can be nullptr.
Definition at line 623 of file pi_cuda.cpp.
ReleaseGuard() [3/8]
template<typename T > ReleaseGuard< T >::ReleaseGuard (ReleaseGuard< T > && Other) inline noexcept
Definition at line 624 of file pi_cuda.cpp.
ReleaseGuard() [4/8]
template<typename T > ReleaseGuard< T >::ReleaseGuard (const ReleaseGuard< T > &) delete
~ReleaseGuard() [1/2]
template<typename T > ReleaseGuard< T >::~ReleaseGuard () inline
Calls the related PI object release function if the object held is not nullptr or if dismiss has not been called.
Definition at line 632 of file pi_cuda.cpp.
References cl::sycl::detail::pi::die(), and PI_SUCCESS.
ReleaseGuard() [5/8]
template<typename T > ReleaseGuard< T >::ReleaseGuard () delete
ReleaseGuard() [6/8]
template<typename T > ReleaseGuard< T >::ReleaseGuard (T Obj) inline explicit
Obj can be nullptr.
Definition at line 634 of file pi_hip.cpp.
ReleaseGuard() [7/8]
template<typename T > ReleaseGuard< T >::ReleaseGuard (ReleaseGuard< T > && Other) inline noexcept
Definition at line 635 of file pi_hip.cpp.
ReleaseGuard() [8/8]
template<typename T > ReleaseGuard< T >::ReleaseGuard (const ReleaseGuard< T > &) delete
~ReleaseGuard() [2/2]
template<typename T > ReleaseGuard< T >::~ReleaseGuard () inline
Calls the related PI object release function if the object held is not nullptr or if dismiss has not been called.
Definition at line 643 of file pi_hip.cpp.
References cl::sycl::detail::pi::die(), and PI_SUCCESS.
Member Function Documentation
dismiss() [1/2]
template<typename T > void ReleaseGuard< T >::dismiss () inline
End the guard and do not release the reference count of the held PI object.
Definition at line 656 of file pi_cuda.cpp.
Referenced by cuda_piMemBufferPartition(), and hip_piMemBufferPartition().
dismiss() [2/2]
template<typename T > void ReleaseGuard< T >::dismiss () inline
End the guard and do not release the reference count of the held PI object.
Definition at line 667 of file pi_hip.cpp.
operator=() [1/4]
template<typename T > ReleaseGuard& ReleaseGuard< T >::operator= (const ReleaseGuard< T > &) delete
operator=() [2/4]
template<typename T > ReleaseGuard& ReleaseGuard< T >::operator= (const ReleaseGuard< T > &) delete
operator=() [3/4]
template<typename T > ReleaseGuard& ReleaseGuard< T >::operator= (ReleaseGuard< T > && Other) inline
Definition at line 648 of file pi_cuda.cpp.
operator=() [4/4]
template<typename T > ReleaseGuard& ReleaseGuard< T >::operator= (ReleaseGuard< T > && Other) inline
Definition at line 659 of file pi_hip.cpp.
The documentation for this class was generated from the following files:
plugins/cuda/pi_cuda.cpp
plugins/hip/pi_hip.cpp