DPC++ Runtime: cl::sycl::detail::MemCpyCommandHost Class Reference
cl::sycl::detail::MemCpyCommandHost Class Reference
The mem copy host command enqueues memory copy between two instances of memory object.
#include <detail/scheduler/commands.hpp>
Public Member Functions
MemCpyCommandHost (Requirement SrcReq, AllocaCommandBase *SrcAllocaCmd, Requirement DstReq, void **DstPtr, QueueImplPtr SrcQueue, QueueImplPtr DstQueue)
void printDot (std::ostream &Stream) const final override
const Requirement * getRequirement () const final override
void emitInstrumentationData () final override
Instrumentation method which emits telemetry data.
ContextImplPtr getContext () const final override
Public Member Functions inherited from cl::sycl::detail::Command
Command (CommandType Type, QueueImplPtr Queue)
void addDep (DepDesc NewDep)
void addDep (EventImplPtr Event)
void addUser (Command *NewUser)
CommandType getType () const
virtual bool enqueue (EnqueueResultT &EnqueueResult, BlockingT Blocking)
Checks if the command is enqueued, and calls enqueueImp.
bool isFinished ()
bool isSuccessfullyEnqueued () const
bool isEnqueueBlocked () const
std::shared_ptr< queue_impl > getQueue () const
std::shared_ptr< event_impl > getEvent () const
void emitInstrumentationDataProxy ()
Proxy method which calls emitInstrumentationData.
void resolveReleaseDependencies (std::set< Command *> &list)
Looks at all the dependencies for the release command and enables instrumentation to report these dependencies as edges.
void emitEdgeEventForCommandDependence (Command *Cmd, void *ObjAddr, const string_class &Prefix, bool IsCommand)
Creates an edge event when the dependency is a command.
void emitEdgeEventForEventDependence (Command *Cmd, RT::PiEvent &EventAddr)
Creates an edge event when the dependency is an event.
void emitEnqueuedEventSignal (RT::PiEvent &PiEventAddr)
Creates a signal event with the enqueued kernel event handle.
uint64_t makeTraceEventProlog (void *MAddress)
Create a trace event of node_create type; this must be guarded by a check for xptiTraceEnabled().
void makeTraceEventEpilog ()
If prolog has been run, run epilog; this must be guarded by a check for xptiTraceEnabled().
void emitInstrumentation (uint16_t Type, const char *Txt=nullptr)
Emits an event of Type.
virtual ~Command ()=default
const char * getBlockReason () const
const std::vector< EventImplPtr > getPreparedHostDepsEvents () const
Additional Inherited Members
Public Types inherited from cl::sycl::detail::Command
enum CommandType {
RUN_CG, COPY_MEMORY, ALLOCA, ALLOCA_SUB_BUF,
RELEASE, MAP_MEM_OBJ, UNMAP_MEM_OBJ, UPDATE_REQUIREMENT,
EMPTY_TASK, HOST_TASK
}
enum BlockReason : int { BlockReason::HostAccessor = 0, BlockReason::HostTask }
Public Attributes inherited from cl::sycl::detail::Command
std::vector< DepDesc > MDeps
Contains list of dependencies(edges)
std::unordered_set< Command * > MUsers
Contains list of commands that depend on the command.
bool MIsBlockable = false
Indicates whether the command can be blocked from enqueueing.
unsigned MLeafCounter = 0
Counts the number of memory objects this command is a leaf for.
Marks MMarks
Used for marking the node during graph traversal.
BlockReason MBlockReason
std::atomic< EnqueueResultT::ResultT > MEnqueueStatus
Describes the status of the command.
void * MTraceEvent = nullptr
The event for node_create and task_begin.
int32_t MStreamID = -1
The stream under which the traces are emitted.
void * MAddress = nullptr
Reserved for storing the object address such as SPIR-V or memory object address.
string_class MAddressString
Buffer to build the address string.
string_class MCommandNodeType
Buffer to build the command node type.
string_class MCommandName
Buffer to build the command end-user understandable name.
bool MTraceEventPrologComplete = false
Flag to indicate if makeTraceEventProlog() has been run.
bool MFirstInstance = false
Flag to indicate if this is the first time we are seeing this payload.
uint64_t MInstanceID = 0
Instance ID tracked for the command.
bool MShouldCompleteEventIfPossible = true
Protected Member Functions inherited from cl::sycl::detail::Command
void waitForEvents (QueueImplPtr Queue, std::vector< EventImplPtr > &RawEvents, RT::PiEvent &Event)
void waitForPreparedHostEvents () const
void processDepEvent (EventImplPtr DepEvent, const DepDesc &Dep)
Perform glueing of events from different contexts.
Protected Attributes inherited from cl::sycl::detail::Command
EventImplPtr MEvent
QueueImplPtr MQueue
std::vector< EventImplPtr > MPreparedDepsEvents
Dependency events prepared for waiting by backend.
std::vector< EventImplPtr > MPreparedHostDepsEvents
CommandType MType
The type of the command.
std::mutex MEnqueueMtx
Mutex used to protect enqueueing from race conditions.
Detailed Description
The mem copy host command enqueues memory copy between two instances of memory object.
Definition at line 466 of file commands.hpp.
Constructor & Destructor Documentation
MemCpyCommandHost()
cl::sycl::detail::MemCpyCommandHost::MemCpyCommandHost (Requirement SrcReq, AllocaCommandBase * SrcAllocaCmd, Requirement DstReq, void ** DstPtr, QueueImplPtr SrcQueue, QueueImplPtr DstQueue)
Definition at line 1252 of file commands.cpp.
References cl::sycl::detail::Command::emitInstrumentationDataProxy(), cl::sycl::detail::getSyclObjImpl(), and cl::sycl::detail::Command::MEvent.
Member Function Documentation
emitInstrumentationData()
void cl::sycl::detail::MemCpyCommandHost::emitInstrumentationData () final override virtual
Instrumentation method which emits telemetry data.
Implements cl::sycl::detail::Command.
Definition at line 1266 of file commands.cpp.
References cl::sycl::detail::deviceToString(), cl::sycl::detail::AllocaCommandBase::getSYCLMemObj(), cl::sycl::detail::Command::MAddress, cl::sycl::detail::Command::MAddressString, cl::sycl::detail::Command::makeTraceEventEpilog(), cl::sycl::detail::Command::makeTraceEventProlog(), cl::sycl::detail::Command::MFirstInstance, cl::sycl::detail::Command::MQueue, and cl::sycl::detail::Command::MTraceEvent.
getContext()
ContextImplPtr cl::sycl::detail::MemCpyCommandHost::getContext () const final override virtual
Reimplemented from cl::sycl::detail::Command.
Definition at line 1289 of file commands.cpp.
References cl::sycl::detail::MemoryManager::copy(), cl::sycl::access::discard_read_write, cl::sycl::access::discard_write, cl::sycl::detail::AllocaCommandBase::getMemAllocation(), cl::sycl::detail::getPiEvents(), cl::sycl::detail::AllocaCommandBase::getSYCLMemObj(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::AccessorImplHost::MAccessMode, cl::sycl::detail::AccessorImplHost::MAccessRange, cl::sycl::detail::AccessorImplHost::MDims, cl::sycl::detail::AccessorImplHost::MElemSize, cl::sycl::detail::Command::MEvent, cl::sycl::detail::AccessorImplHost::MMemoryRange, cl::sycl::detail::AccessorImplHost::MOffset, cl::sycl::detail::Command::MPreparedDepsEvents, cl::sycl::detail::Command::MQueue, cl::sycl::detail::Command::waitForEvents(), and cl::sycl::detail::Command::waitForPreparedHostEvents().
getRequirement()
const Requirement* cl::sycl::detail::MemCpyCommandHost::getRequirement () const inline final override virtual
Reimplemented from cl::sycl::detail::Command.
Definition at line 473 of file commands.hpp.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::addCopyBack().
printDot()
void cl::sycl::detail::MemCpyCommandHost::printDot (std::ostream & Stream) const final override virtual
Implements cl::sycl::detail::Command.
Definition at line 1384 of file commands.cpp.
References cl::sycl::detail::accessModeToString(), cl::sycl::detail::deviceToString(), cl::sycl::endl, cl::sycl::detail::Command::MDeps, and cl::sycl::detail::Command::MQueue.
The documentation for this class was generated from the following files:
source/detail/scheduler/commands.hpp
source/detail/scheduler/commands.cpp