DPC++ Runtime: cl::sycl::context Class Reference
cl::sycl::context Class Reference
DPC++ User API
The context class represents a SYCL context on which kernel functions may be executed.
#include <CL/sycl/context.hpp>
Public Member Functions
context (const property_list &PropList={})
Constructs a SYCL context instance using an instance of default_selector.
context (const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL context instance using an instance of default_selector.
context (const device &Device, const property_list &PropList={})
Constructs a SYCL context instance using the provided device.
context (const device &Device, async_handler AsyncHandler, const property_list &PropList={})
Constructs a SYCL context instance using the provided device.
context (const platform &Platform, const property_list &PropList={})
Constructs a SYCL context instance using the provided platform.
context (const platform &Platform, async_handler AsyncHandler, const property_list &PropList={})
Constructs a SYCL context instance using the provided platform.
context (const std::vector< device > &DeviceList, const property_list &PropList={})
Constructs a SYCL context instance using list of devices.
context (const std::vector< device > &DeviceList, async_handler AsyncHandler, const property_list &PropList={})
Constructs a SYCL context instance using list of devices.
template<info::context param>
info::param_traits< info::context, param >::return_type get_info () const
Constructs a SYCL context instance from OpenCL cl_context.
context (const context &rhs)=default
context (context &&rhs)=default
context & operator= (const context &rhs)=default
context & operator= (context &&rhs)=default
bool operator== (const context &rhs) const
bool operator!= (const context &rhs) const
template<typename propertyT >
bool has_property () const
Checks if this context has a property of type propertyT.
template<typename propertyT >
propertyT get_property () const
Gets the specified property of this context.
bool is_host () const
Gets OpenCL interoperability context.
backend get_backend () const noexcept
Returns the backend associated with this context.
platform get_platform () const
Gets platform associated with this SYCL context.
std::vector< device > get_devices () const
Gets devices associated with this SYCL context.
template<backend Backend>
backend_return_t< Backend, context > get_native () const
Gets the native handle of the SYCL context.
Friends
template<class T >
detail::add_pointer_t< typename decltype(T::impl)::element_type > detail::getRawSyclObjImpl (const T &SyclObject)
template<class T >
T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Detailed Description
The context class represents a SYCL context on which kernel functions may be executed.
Definition at line 35 of file context.hpp.
Constructor & Destructor Documentation
context() [1/10]
cl::sycl::context::context (const property_list & PropList = {}) explicit
Constructs a SYCL context instance using an instance of default_selector.
The instance of default_selector is used to select the associated platform and device(s). SYCL properties are passed to the constructed SYCL context through PropList.
Parameters
PropList is an instance of property_list.
Definition at line 29 of file context.cpp.
context() [2/10]
cl::sycl::context::context (const async_handler & AsyncHandler, const property_list & PropList = {}) explicit
Constructs a SYCL context instance using an instance of default_selector.
The instance of default_selector is used to select the associated platform and device(s). The constructed SYCL context will use the AsyncHandler parameter to handle exceptions. SYCL properties are passed to the constructed SYCL context through PropList.
Parameters
AsyncHandler is an instance of async_handler.
PropList is an instance of property_list.
Definition at line 32 of file context.cpp.
context() [3/10]
cl::sycl::context::context (const device & Device, const property_list & PropList = {}) explicit
Constructs a SYCL context instance using the provided device.
Newly created context is associated with the Device and the SYCL platform that is associated with the Device. SYCL properties are passed to the constructed SYCL context through PropList.
Parameters
Device is an instance of SYCL device.
PropList is an instance of property_list.
Definition at line 36 of file context.cpp.
context() [4/10]
cl::sycl::context::context (const device & Device, async_handler AsyncHandler, const property_list & PropList = {}) explicit
Constructs a SYCL context instance using the provided device.
Newly created context is associated with the Device and the SYCL platform that is associated with the Device. The constructed SYCL context will use the AsyncHandler parameter to handle exceptions. SYCL properties are passed to the constructed SYCL context through PropList.
Parameters
Device is an instance of SYCL device.
AsyncHandler is an instance of async_handler.
PropList is an instance of property_list.
Definition at line 39 of file context.cpp.
context() [5/10]
cl::sycl::context::context (const platform & Platform, const property_list & PropList = {}) explicit
Constructs a SYCL context instance using the provided platform.
Newly created context is associated with the Platform and with each SYCL device that is associated with the Platform. SYCL properties are passed to the constructed SYCL context through PropList.
Parameters
Platform is an instance of SYCL platform.
PropList is an instance of property_list.
Definition at line 43 of file context.cpp.
context() [6/10]
cl::sycl::context::context (const platform & Platform, async_handler AsyncHandler, const property_list & PropList = {}) explicit
Constructs a SYCL context instance using the provided platform.
Newly created context is associated with the Platform and with each SYCL device that is associated with the Platform. The constructed SYCL context will use the AsyncHandler parameter to handle exceptions. SYCL properties are passed to the constructed SYCL context through PropList.
Parameters
Platform is an instance of SYCL platform.
AsyncHandler is an instance of async_handler.
PropList is an instance of property_list.
Definition at line 46 of file context.cpp.
context() [7/10]
cl::sycl::context::context (const std::vector< device > & DeviceList, const property_list & PropList = {}) explicit
Constructs a SYCL context instance using list of devices.
Newly created context will be associated with each SYCL device in the DeviceList. This requires that all SYCL devices in the list have the same associated SYCL platform. SYCL properties are passed to the constructed SYCL context through PropList.
Parameters
DeviceList is a list of SYCL device instances.
PropList is an instance of property_list.
Definition at line 50 of file context.cpp.
context() [8/10]
cl::sycl::context::context (const std::vector< device > & DeviceList, async_handler AsyncHandler, const property_list & PropList = {}) explicit
Constructs a SYCL context instance using list of devices.
Newly created context will be associated with each SYCL device in the DeviceList. This requires that all SYCL devices in the list have the same associated SYCL platform. The constructed SYCL context will use the AsyncHandler parameter to handle exceptions. SYCL properties are passed to the constructed SYCL context through PropList.
Parameters
DeviceList is a list of SYCL device instances.
AsyncHandler is an instance of async_handler.
PropList is an instance of property_list.
Definition at line 54 of file context.cpp.
References any_of(), cl::sycl::device::get_platform(), cl::sycl::detail::getSyclObjImpl(), PI_INVALID_DEVICE, and PI_INVALID_VALUE.
context() [9/10]
cl::sycl::context::context (const context & rhs) default
context() [10/10]
cl::sycl::context::context (context && rhs) default
Member Function Documentation
get_backend()
backend cl::sycl::context::get_backend () const noexcept
Returns the backend associated with this context.
Returns
the backend associated with this context.
Definition at line 121 of file context.cpp.
References cl::sycl::detail::getImplBackend().
get_devices()
std::vector< device > cl::sycl::context::get_devices () const
Gets devices associated with this SYCL context.
Returns
a vector of valid SYCL device instances.
Definition at line 127 of file context.cpp.
References cl::sycl::info::devices.
Referenced by cl::sycl::detail::checkAllDevicesAreInContext(), cl::sycl::detail::kernel_bundle_plain::get_devices(), cl::sycl::detail::get_empty_interop_kernel_bundle(), cl::sycl::get_kernel_bundle(), cl::sycl::get_pointer_device(), cl::sycl::has_kernel_bundle(), cl::sycl::detail::isDeviceBinaryTypeSupported(), and cl::sycl::queue::queue().
get_info()
template<info::context param> info::param_traits<info::context, param>::return_type cl::sycl::context::get_info () const
Constructs a SYCL context instance from OpenCL cl_context.
ClContext is retained on SYCL context instantiation. The constructed SYCL context will use the AsyncHandler parameter to handle exceptions.
Parameters
ClContext is an instance of OpenCL cl_context.
AsyncHandler is an instance of async_handler. Queries this SYCL context for information.
The return type depends on information being queried.
get_native()
template<backend Backend> backend_return_t<Backend, context> cl::sycl::context::get_native () const inline
Gets the native handle of the SYCL context.
Returns
a native handle, the type of which defined by the backend.
Definition at line 222 of file context.hpp.
get_platform()
platform cl::sycl::context::get_platform () const
Gets platform associated with this SYCL context.
Returns
a valid instance of SYCL platform.
Definition at line 123 of file context.cpp.
References cl::sycl::info::platform.
Referenced by cl::sycl::detail::isDeviceBinaryTypeSupported().
get_property()
template<typename propertyT > propertyT cl::sycl::context::get_property () const
Gets the specified property of this context.
Throws invalid_object_error if this context does not have a property of type propertyT.
Returns
a copy of the property of type propertyT.
has_property()
template<typename propertyT > bool cl::sycl::context::has_property () const
Checks if this context has a property of type propertyT.
Returns
true if this context has a property of type propertyT.
is_host()
bool cl::sycl::context::is_host () const
Gets OpenCL interoperability context.
The OpenCL cl_context handle is retained on return.
Returns
a valid instance of OpenCL cl_context. Checks if this context is a SYCL host context.
true if this context is a SYCL host context.
Definition at line 119 of file context.cpp.
Referenced by cl::sycl::detail::MemoryManager::advise_usm(), cl::sycl::detail::usm::alignedAllocHost(), cl::sycl::detail::MemoryManager::copy_usm(), cl::sycl::detail::MemoryManager::fill_usm(), cl::sycl::detail::usm::free(), cl::sycl::get_pointer_device(), cl::sycl::get_pointer_type(), and cl::sycl::detail::MemoryManager::prefetch_usm().
operator!=()
bool cl::sycl::context::operator!= (const context & rhs) const inline
Definition at line 173 of file context.hpp.
operator=() [1/2]
context& cl::sycl::context::operator= (const context & rhs) default
operator=() [2/2]
context& cl::sycl::context::operator= (context && rhs) default
operator==()
bool cl::sycl::context::operator== (const context & rhs) const inline
Definition at line 171 of file context.hpp.
Friends And Related Function Documentation
detail::createSyclObjFromImpl
template<class T > T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
detail::getRawSyclObjImpl
template<class T > detail::add_pointer_t<typename decltype(T::impl)::element_type> detail::getRawSyclObjImpl (const T & SyclObject) friend
The documentation for this class was generated from the following files:
include/CL/sycl/context.hpp
source/context.cpp