DPC++ Runtime: sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > > Class Template Reference
sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > > Class Template Reference
#include <sycl/ext/intel/experimental/task_sequence.hpp>
Public Member Functions
task_sequence (const task_sequence &)=delete
task_sequence & operator= (const task_sequence &)=delete
task_sequence (task_sequence &&)=delete
task_sequence & operator= (task_sequence &&)=delete
task_sequence ()
void async ([[maybe_unused]] ArgsT... Args)
ReturnT get ()
~task_sequence ()
Static Public Member Functions
template<typename propertyT >
static constexpr bool has_property ()
template<typename propertyT >
static constexpr auto get_property ()
Detailed Description
template<typename ReturnT, typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props>
class sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >
Definition at line 45 of file task_sequence.hpp.
Constructor & Destructor Documentation
task_sequence() [1/3]
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::task_sequence (const task_sequence< f, oneapi::experimental::detail::properties_t< Props... > > &) delete
task_sequence() [2/3]
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::task_sequence (task_sequence< f, oneapi::experimental::detail::properties_t< Props... > > &&) delete
task_sequence() [3/3]
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::task_sequence () inline
Definition at line 56 of file task_sequence.hpp.
References sycl::_V1::feature_not_supported, sycl::_V1::ext::intel::experimental::fpga_cluster, sycl::_V1::ext::intel::experimental::invocation_capacity, sycl::_V1::make_error_code(), sycl::_V1::ext::intel::experimental::pipelined, and sycl::_V1::ext::intel::experimental::response_capacity.
~task_sequence()
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::~task_sequence () inline
Definition at line 86 of file task_sequence.hpp.
References sycl::_V1::get().
Member Function Documentation
async()
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> void sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::async ([[maybe_unused] ] ArgsT... Args) inline
Definition at line 66 of file task_sequence.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
get()
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> ReturnT sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::get () inline
Definition at line 76 of file task_sequence.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
get_property()
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> template<typename propertyT > static constexpr auto sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::get_property () inline static constexpr
Definition at line 101 of file task_sequence.hpp.
has_property()
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> template<typename propertyT > static constexpr bool sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::has_property () inline static constexpr
Definition at line 97 of file task_sequence.hpp.
operator=() [1/2]
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> task_sequence& sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::operator= (const task_sequence< f, oneapi::experimental::detail::properties_t< Props... > > &) delete
operator=() [2/2]
template<typename ReturnT , typename... ArgsT, ReturnT(&)(ArgsT...) f, typename... Props> task_sequence& sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::operator= (task_sequence< f, oneapi::experimental::detail::properties_t< Props... > > &&) delete
The documentation for this class was generated from the following file:
include/sycl/ext/intel/experimental/task_sequence.hpp