DPC++ Runtime: sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType > Class Template Reference
sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType > Class Template Reference
#include <sycl/handler.hpp>
Public Member Functions
void operator() (item< Dims > It) const
Public Attributes
range< Dims > UserRange
KernelType KernelFunc
Detailed Description
template<typename TransformedArgType, int Dims, typename KernelType>
class sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >
Definition at line 376 of file handler.hpp.
Member Function Documentation
operator()()
template<typename TransformedArgType , int Dims, typename KernelType > void sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >::operator() (item< Dims > It) const inline
Definition at line 380 of file handler.hpp.
References sycl::_V1::item< Dimensions, with_offset >::get_id(), sycl::_V1::item< Dimensions, with_offset >::get_range(), sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >::KernelFunc, sycl::_V1::detail::RoundedRangeIDGenerator< Dims >::updateId(), and sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >::UserRange.
Member Data Documentation
KernelFunc
template<typename TransformedArgType , int Dims, typename KernelType > KernelType sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >::KernelFunc
Definition at line 379 of file handler.hpp.
Referenced by sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >::operator()().
UserRange
template<typename TransformedArgType , int Dims, typename KernelType > range<Dims> sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >::UserRange
Definition at line 378 of file handler.hpp.
Referenced by sycl::_V1::detail::RoundedRangeKernel< TransformedArgType, Dims, KernelType >::operator()().
The documentation for this class was generated from the following file:
include/sycl/handler.hpp