DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent > Class Template Reference
sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent > Class Template Reference
#include <sycl/ext/oneapi/experimental/group_helpers_sorters.hpp>
Public Member Functions
group_with_scratchpad (Group g_, sycl::span< std::byte, Extent > scratch_)
Group get_group () const
sycl::span< std::byte, Extent > get_memory () const
Detailed Description
template<typename Group, size_t Extent>
class sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >
Definition at line 40 of file group_helpers_sorters.hpp.
Constructor & Destructor Documentation
group_with_scratchpad()
template<typename Group , size_t Extent> sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::group_with_scratchpad (Group g_, sycl::span< std::byte, Extent > scratch_) inline
Definition at line 45 of file group_helpers_sorters.hpp.
Member Function Documentation
get_group()
template<typename Group , size_t Extent> Group sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_group () const inline
Definition at line 47 of file group_helpers_sorters.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::joint_sort(), and sycl::_V1::ext::oneapi::experimental::sort_over_group().
get_memory()
template<typename Group , size_t Extent> sycl::span<std::byte, Extent> sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_memory () const inline
Definition at line 48 of file group_helpers_sorters.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::joint_sort(), and sycl::_V1::ext::oneapi::experimental::sort_over_group().
The documentation for this class was generated from the following files:
include/sycl/detail/type_traits.hpp
include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp