DPC++ Runtime: sycl::_V1::detail::HostTask Class Reference
sycl::_V1::detail::HostTask Class Reference
#include <sycl/detail/cg_types.hpp>
Public Member Functions
HostTask ()
HostTask (std::function< void()> &&Func)
HostTask (std::function< void(interop_handle)> &&Func)
bool isInteropTask () const
void call (HostProfilingInfo *HPI)
void call (HostProfilingInfo *HPI, interop_handle handle)
Detailed Description
Definition at line 233 of file cg_types.hpp.
Constructor & Destructor Documentation
HostTask() [1/3]
sycl::_V1::detail::HostTask::HostTask () inline
Definition at line 238 of file cg_types.hpp.
HostTask() [2/3]
sycl::_V1::detail::HostTask::HostTask (std::function< void()> && Func) inline
Definition at line 239 of file cg_types.hpp.
HostTask() [3/3]
sycl::_V1::detail::HostTask::HostTask (std::function< void(interop_handle)> && Func) inline
Definition at line 240 of file cg_types.hpp.
Member Function Documentation
call() [1/2]
void sycl::_V1::detail::HostTask::call (HostProfilingInfo * HPI) inline
Definition at line 244 of file cg_types.hpp.
References sycl::_V1::detail::HostProfilingInfo::end(), and sycl::_V1::detail::HostProfilingInfo::start().
call() [2/2]
void sycl::_V1::detail::HostTask::call (HostProfilingInfo * HPI, interop_handle handle) inline
Definition at line 252 of file cg_types.hpp.
References sycl::_V1::detail::HostProfilingInfo::end(), and sycl::_V1::detail::HostProfilingInfo::start().
isInteropTask()
bool sycl::_V1::detail::HostTask::isInteropTask () const inline
Definition at line 242 of file cg_types.hpp.
The documentation for this class was generated from the following file:
include/sycl/detail/cg_types.hpp