DPC++ Runtime: sycl::_V1::detail::array< dimensions > Class Template Reference
sycl::_V1::detail::array< dimensions > Class Template Reference
#include <sycl/detail/array.hpp>
Public Member Functions
template<int N = dimensions>
array (typename std::enable_if_t<(N==1), size_t > dim0=0)
template<int N = dimensions>
array (typename std::enable_if_t<(N==2), size_t > dim0, size_t dim1)
template<int N = dimensions, std::enable_if_t<(N==2), size_t > = 0>
array ()
template<int N = dimensions>
array (typename std::enable_if_t<(N==3), size_t > dim0, size_t dim1, size_t dim2)
template<int N = dimensions, std::enable_if_t<(N==3), size_t > = 0>
array ()
operator sycl::id< dimensions > () const
size_t get (int dimension) const
size_t & operator[] (int dimension)
size_t operator[] (int dimension) const
array (const array< dimensions > &rhs)=default
array (array< dimensions > &&rhs)=default
array< dimensions > & operator= (const array< dimensions > &rhs)=default
array< dimensions > & operator= (array< dimensions > &&rhs)=default
bool operator== (const array< dimensions > &rhs) const
bool operator!= (const array< dimensions > &rhs) const
Protected Member Functions
__SYCL_ALWAYS_INLINE void check_dimension (int dimension) const
Protected Attributes
size_t common_array [dimensions]
Detailed Description
template<int dimensions = 1>
class sycl::_V1::detail::array< dimensions >
Definition at line 24 of file array.hpp.
Constructor & Destructor Documentation
array() [1/7]
template<int dimensions = 1> template<int N = dimensions> sycl::_V1::detail::array< dimensions >::array (typename std::enable_if_t<(N==1), size_t > dim0 = 0) inline
Definition at line 31 of file array.hpp.
array() [2/7]
template<int dimensions = 1> template<int N = dimensions> sycl::_V1::detail::array< dimensions >::array (typename std::enable_if_t<(N==2), size_t > dim0, size_t dim1) inline
Definition at line 37 of file array.hpp.
array() [3/7]
template<int dimensions = 1> template<int N = dimensions, std::enable_if_t<(N==2), size_t > = 0> sycl::_V1::detail::array< dimensions >::array () inline
Definition at line 41 of file array.hpp.
array() [4/7]
template<int dimensions = 1> template<int N = dimensions> sycl::_V1::detail::array< dimensions >::array (typename std::enable_if_t<(N==3), size_t > dim0, size_t dim1, size_t dim2) inline
Definition at line 46 of file array.hpp.
array() [5/7]
template<int dimensions = 1> template<int N = dimensions, std::enable_if_t<(N==3), size_t > = 0> sycl::_V1::detail::array< dimensions >::array () inline
Definition at line 51 of file array.hpp.
array() [6/7]
template<int dimensions = 1> sycl::_V1::detail::array< dimensions >::array (const array< dimensions > & rhs) default
array() [7/7]
template<int dimensions = 1> sycl::_V1::detail::array< dimensions >::array (array< dimensions > && rhs) default
Member Function Documentation
check_dimension()
template<int dimensions = 1> __SYCL_ALWAYS_INLINE void sycl::_V1::detail::array< dimensions >::check_dimension (int dimension) const inline protected
Definition at line 106 of file array.hpp.
Referenced by sycl::_V1::detail::array< dimensions >::get(), and sycl::_V1::detail::array< dimensions >::operator[]().
get()
template<int dimensions = 1> size_t sycl::_V1::detail::array< dimensions >::get (int dimension) const inline
Definition at line 62 of file array.hpp.
References sycl::_V1::detail::array< dimensions >::check_dimension(), and sycl::_V1::detail::array< dimensions >::common_array.
Referenced by syclcompat::detail::get_copy_range(), syclcompat::malloc(), and syclcompat::detail::memset().
operator sycl::id< dimensions >()
template<int dimensions = 1> sycl::_V1::detail::array< dimensions >::operator sycl::id< dimensions > () const inline
Definition at line 54 of file array.hpp.
References sycl::_V1::detail::array< dimensions >::common_array.
operator!=()
template<int dimensions = 1> bool sycl::_V1::detail::array< dimensions >::operator!= (const array< dimensions > & rhs) const inline
Definition at line 95 of file array.hpp.
References sycl::_V1::detail::array< dimensions >::common_array.
operator=() [1/2]
template<int dimensions = 1> array<dimensions>& sycl::_V1::detail::array< dimensions >::operator= (array< dimensions > && rhs) default
operator=() [2/2]
template<int dimensions = 1> array<dimensions>& sycl::_V1::detail::array< dimensions >::operator= (const array< dimensions > & rhs) default
operator==()
template<int dimensions = 1> bool sycl::_V1::detail::array< dimensions >::operator== (const array< dimensions > & rhs) const inline
Definition at line 84 of file array.hpp.
References sycl::_V1::detail::array< dimensions >::common_array.
Referenced by sycl::_V1::id< Dimensions >::operator==().
operator[]() [1/2]
template<int dimensions = 1> size_t& sycl::_V1::detail::array< dimensions >::operator[] (int dimension) inline
Definition at line 67 of file array.hpp.
References sycl::_V1::detail::array< dimensions >::check_dimension(), and sycl::_V1::detail::array< dimensions >::common_array.
operator[]() [2/2]
template<int dimensions = 1> size_t sycl::_V1::detail::array< dimensions >::operator[] (int dimension) const inline
Definition at line 72 of file array.hpp.
References sycl::_V1::detail::array< dimensions >::check_dimension(), and sycl::_V1::detail::array< dimensions >::common_array.
Member Data Documentation
common_array
template<int dimensions = 1> size_t sycl::_V1::detail::array< dimensions >::common_array[dimensions] protected
Definition at line 105 of file array.hpp.
Referenced by sycl::_V1::detail::array< dimensions >::get(), sycl::_V1::detail::array< dimensions >::operator sycl::id< dimensions >(), sycl::_V1::detail::array< dimensions >::operator!=(), sycl::_V1::detail::array< dimensions >::operator==(), and sycl::_V1::detail::array< dimensions >::operator[]().
The documentation for this class was generated from the following file:
include/sycl/detail/array.hpp