DPC++ Runtime: cl::sycl::detail::CG Class Reference
cl::sycl::detail::CG Class Reference
Base class for all types of command groups.
#include <CL/sycl/detail/cg.hpp>
Public Types
enum CG_VERSION : unsigned char { CG_VERSION::V0 = 0, CG_VERSION::V1 = 1 }
enum CGTYPE : unsigned int {
NONE = 0, KERNEL = 1, COPY_ACC_TO_PTR = 2, COPY_PTR_TO_ACC = 3,
COPY_ACC_TO_ACC = 4, BARRIER = 5, BARRIER_WAITLIST = 6, FILL = 7,
UPDATE_HOST = 8, RUN_ON_HOST_INTEL = 9, COPY_USM = 10, FILL_USM = 11,
PREFETCH_USM = 12, CODEPLAY_INTEROP_TASK = 13, CODEPLAY_HOST_TASK = 14, ADVISE_USM = 15
}
Type of the command group.
Public Member Functions
CG (CGTYPE Type, vector_class< vector_class< char >> ArgsStorage, vector_class< detail::AccessorImplPtr > AccStorage, vector_class< shared_ptr_class< const void >> SharedPtrStorage, vector_class< Requirement * > Requirements, vector_class< detail::EventImplPtr > Events, detail::code_location loc={})
CG (CG &&CommandGroup)=default
CGTYPE getType ()
CG_VERSION getVersion ()
std::shared_ptr< std::vector< ExtendedMemberT > > getExtendedMembers ()
virtual ~CG ()=default
Public Attributes
vector_class< Requirement * > MRequirements
List of requirements that specify which memory is needed for the command group to be executed.
vector_class< detail::EventImplPtr > MEvents
List of events that order the execution of this CG.
string_class MFunctionName
string_class MFileName
int32_t MLine
int32_t MColumn
Detailed Description
Base class for all types of command groups.
Definition at line 140 of file cg.hpp.
Member Enumeration Documentation
CG_VERSION
enum cl::sycl::detail::CG::CG_VERSION : unsigned char strong
Enumerator
V0
V1
Definition at line 146 of file cg.hpp.
CGTYPE
enum cl::sycl::detail::CG::CGTYPE : unsigned int
Type of the command group.
Enumerator
NONE
KERNEL
COPY_ACC_TO_PTR
COPY_PTR_TO_ACC
COPY_ACC_TO_ACC
BARRIER
BARRIER_WAITLIST
FILL
UPDATE_HOST
RUN_ON_HOST_INTEL
COPY_USM
FILL_USM
PREFETCH_USM
CODEPLAY_INTEROP_TASK
CODEPLAY_HOST_TASK
ADVISE_USM
Definition at line 152 of file cg.hpp.
Constructor & Destructor Documentation
CG() [1/2]
cl::sycl::detail::CG::CG (CGTYPE Type, vector_class< vector_class< char >> ArgsStorage, vector_class< detail::AccessorImplPtr > AccStorage, vector_class< shared_ptr_class< const void >> SharedPtrStorage, vector_class< Requirement * > Requirements, vector_class< detail::EventImplPtr > Events, detail::code_location loc = {}) inline
Definition at line 171 of file cg.hpp.
CG() [2/2]
cl::sycl::detail::CG::CG (CG && CommandGroup) default
~CG()
virtual cl::sycl::detail::CG::~CG () virtual default
Member Function Documentation
getExtendedMembers()
std::shared_ptr<std::vector<ExtendedMemberT> > cl::sycl::detail::CG::getExtendedMembers () inline
Definition at line 199 of file cg.hpp.
References cl::sycl::detail::convertToExtendedMembers(), and cl::sycl::detail::getCGTypeVersion().
getType()
CGTYPE cl::sycl::detail::CG::getType () inline
Definition at line 193 of file cg.hpp.
References cl::sycl::detail::getUnversionedCGType().
Referenced by cl::sycl::detail::DispatchHostTask::operator()().
getVersion()
CG_VERSION cl::sycl::detail::CG::getVersion () inline
Definition at line 195 of file cg.hpp.
References cl::sycl::detail::getCGTypeVersion().
Member Data Documentation
MColumn
int32_t cl::sycl::detail::CG::MColumn
Definition at line 233 of file cg.hpp.
MEvents
vector_class<detail::EventImplPtr> cl::sycl::detail::CG::MEvents
List of events that order the execution of this CG.
Definition at line 227 of file cg.hpp.
MFileName
string_class cl::sycl::detail::CG::MFileName
Definition at line 231 of file cg.hpp.
MFunctionName
string_class cl::sycl::detail::CG::MFunctionName
Definition at line 231 of file cg.hpp.
MLine
int32_t cl::sycl::detail::CG::MLine
Definition at line 233 of file cg.hpp.
MRequirements
vector_class<Requirement *> cl::sycl::detail::CG::MRequirements
List of requirements that specify which memory is needed for the command group to be executed.
Definition at line 225 of file cg.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/detail/cg.hpp