DPC++ Runtime: sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class > Class Template Reference
sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class > Class Template Reference
#include <sycl/ext/intel/experimental/pipes.hpp>
Classes
struct ConstantPipeStorageExp
Static Public Member Functions
static _dataT read (queue &Q, bool &Success, memory_order Order=memory_order::seq_cst)
static void write (queue &Q, const _dataT &Data, bool &Success, memory_order Order=memory_order::seq_cst)
template<typename _functionPropertiesT >
static _dataT read (bool &Success, _functionPropertiesT)
static _dataT read (bool &Success)
template<typename _functionPropertiesT >
static void write (const _dataT &Data, bool &Success, _functionPropertiesT)
static void write (const _dataT &Data, bool &Success)
static const void * get_host_ptr ()
static _dataT read (queue &Q, memory_order Order=memory_order::seq_cst)
static void write (queue &Q, const _dataT &Data, memory_order Order=memory_order::seq_cst)
template<typename _functionPropertiesT >
static _dataT read (_functionPropertiesT)
static _dataT read ()
template<typename _functionPropertiesT >
static void write (const _dataT &Data, _functionPropertiesT)
static void write (const _dataT &Data)
Static Public Attributes
static constexpr struct ConstantPipeStorageExp m_Storage
Additional Inherited Members
Protected Member Functions inherited from sycl::_V1::ext::intel::experimental::pipe_base
pipe_base ()
~pipe_base ()
Static Protected Member Functions inherited from sycl::_V1::ext::intel::experimental::pipe_base
static std::string get_pipe_name (const void *HostPipePtr)
static bool wait_non_blocking (const event &E)
Detailed Description
template<class _name, class _dataT, int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void>
class sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >
Definition at line 56 of file pipes.hpp.
Member Function Documentation
get_host_ptr()
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static const void* sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::get_host_ptr () inline static
Definition at line 232 of file pipes.hpp.
read() [1/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static _dataT sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read () inline static
Definition at line 324 of file pipes.hpp.
References sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read().
Referenced by sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read().
read() [2/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> template<typename _functionPropertiesT > static _dataT sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read (_functionPropertiesT) inline static
Definition at line 283 of file pipes.hpp.
References sycl::_V1::ext::intel::experimental::exact, sycl::_V1::ext::intel::experimental::max, and sycl::_V1::ext::intel::experimental::min.
read() [3/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static _dataT sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read (bool & Success) inline static
Definition at line 180 of file pipes.hpp.
read() [4/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> template<typename _functionPropertiesT > static _dataT sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read (bool & Success, _functionPropertiesT) inline static
Definition at line 138 of file pipes.hpp.
References sycl::_V1::ext::intel::experimental::exact, sycl::_V1::ext::intel::experimental::max, and sycl::_V1::ext::intel::experimental::min.
read() [5/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static _dataT sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read (queue & Q, bool & Success, memory_order Order = memory_order::seq_cst) inline static
Definition at line 79 of file pipes.hpp.
References sycl::_V1::queue::get_device(), sycl::_V1::event::get_info(), sycl::_V1::ext::intel::experimental::pipe_base::get_pipe_name(), sycl::_V1::device::has_extension(), and sycl::_V1::queue::submit().
read() [6/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static _dataT sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read (queue & Q, memory_order Order = memory_order::seq_cst) inline static
Definition at line 237 of file pipes.hpp.
References sycl::_V1::queue::get_device(), sycl::_V1::ext::intel::experimental::pipe_base::get_pipe_name(), sycl::_V1::device::has_extension(), and sycl::_V1::queue::submit().
write() [1/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static void sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write (const _dataT & Data) inline static
Definition at line 369 of file pipes.hpp.
write() [2/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> template<typename _functionPropertiesT > static void sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write (const _dataT & Data, _functionPropertiesT) inline static
Definition at line 329 of file pipes.hpp.
References sycl::_V1::ext::intel::experimental::exact, sycl::_V1::ext::intel::experimental::max, and sycl::_V1::ext::intel::experimental::min.
write() [3/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static void sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write (const _dataT & Data, bool & Success) inline static
Definition at line 228 of file pipes.hpp.
write() [4/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> template<typename _functionPropertiesT > static void sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write (const _dataT & Data, bool & Success, _functionPropertiesT) inline static
Definition at line 187 of file pipes.hpp.
References sycl::_V1::ext::intel::experimental::exact, sycl::_V1::ext::intel::experimental::max, and sycl::_V1::ext::intel::experimental::min.
write() [5/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static void sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write (queue & Q, const _dataT & Data, bool & Success, memory_order Order = memory_order::seq_cst) inline static
Definition at line 108 of file pipes.hpp.
References sycl::_V1::queue::get_device(), sycl::_V1::event::get_info(), sycl::_V1::ext::intel::experimental::pipe_base::get_pipe_name(), sycl::_V1::device::has_extension(), and sycl::_V1::queue::submit().
write() [6/6]
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> static void sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write (queue & Q, const _dataT & Data, memory_order Order = memory_order::seq_cst) inline static
Definition at line 259 of file pipes.hpp.
References sycl::_V1::queue::get_device(), sycl::_V1::ext::intel::experimental::pipe_base::get_pipe_name(), sycl::_V1::device::has_extension(), and sycl::_V1::queue::submit().
Member Data Documentation
m_Storage
template<class _name , class _dataT , int32_t _min_capacity = 0, class _propertiesT = decltype(oneapi::experimental::properties{}), class = void> constexpr struct ConstantPipeStorageExp sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::m_Storage static
Initial value:
= {
      m_ready_latency,
      m_bits_per_symbol,
      m_uses_valid,
      m_first_symbol_in_high_order_bits,
      m_protocol}
Definition at line 391 of file pipes.hpp.
The documentation for this class was generated from the following file:
include/sycl/ext/intel/experimental/pipes.hpp