DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph Class Reference
sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph Class Reference
#include <sycl/ext/oneapi/experimental/graph.hpp>
Public Member Functions
modifiable_command_graph (const context &SyclContext, const device &SyclDevice, const property_list &PropList={})
Constructor.
modifiable_command_graph (const queue &SyclQueue, const property_list &PropList={})
Constructor.
node add (const property_list &PropList={})
Add an empty node to the graph.
template<typename T >
node add (T CGF, const property_list &PropList={})
Add a command-group node to the graph.
void make_edge (node &Src, node &Dest)
Add a dependency between two nodes.
command_graph< graph_state::executable > finalize (const property_list &PropList={}) const
Finalize modifiable graph into an executable graph.
void begin_recording (queue &RecordingQueue, const property_list &PropList={})
Change the state of a queue to be recording and associate this graph with it.
void begin_recording (const std::vector< queue > &RecordingQueues, const property_list &PropList={})
Change the state of multiple queues to be recording and associate this graph with each of them.
void end_recording ()
Set all queues currently recording to this graph to the executing state.
void end_recording (queue &RecordingQueue)
Set a queue currently recording to this graph to the executing state.
void end_recording (const std::vector< queue > &RecordingQueues)
Set multiple queues currently recording to this graph to the executing state.
void print_graph (const std::string path, bool verbose=false) const
Synchronous operation that writes a DOT formatted description of the graph to the provided path.
std::vector< node > get_nodes () const
Get a list of all nodes contained in this graph.
std::vector< node > get_root_nodes () const
Get a list of all root nodes (nodes without dependencies) in this graph.
Protected Member Functions
modifiable_command_graph (const std::shared_ptr< detail::graph_impl > &Impl)
Constructor used internally by the runtime.
node addImpl (std::function< void(handler &)> CGF, const std::vector< node > &Dep)
Template-less implementation of add() for CGF nodes.
node addImpl (const std::vector< node > &Dep)
Template-less implementation of add() for empty nodes.
void addGraphLeafDependencies (node Node)
Adds all graph leaves as dependencies.
template<class Obj >
decltype(Obj::impl) friend sycl::detail::getSyclObjImpl (const Obj &SyclObject)
Protected Attributes
std::shared_ptr< detail::graph_impl > impl
Friends
template<class T >
T sycl::detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Detailed Description
Definition at line 213 of file graph.hpp.
Constructor & Destructor Documentation
modifiable_command_graph() [1/3]
sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::modifiable_command_graph (const context & SyclContext, const device & SyclDevice, const property_list & PropList = {})
Constructor.
Parameters
SyclContext Context to use for graph.
SyclDevice Device all nodes will be associated with.
PropList Optional list of properties to pass.
modifiable_command_graph() [2/3]
sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::modifiable_command_graph (const queue & SyclQueue, const property_list & PropList = {})
Constructor.
Parameters
SyclQueue Queue to use for the graph device and context.
PropList Optional list of properties to pass.
modifiable_command_graph() [3/3]
sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::modifiable_command_graph (const std::shared_ptr< detail::graph_impl > & Impl) inline protected
Constructor used internally by the runtime.
Parameters
Impl Detail implementation class to construct object with.
Definition at line 323 of file graph.hpp.
Member Function Documentation
add() [1/2]
node sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::add (const property_list & PropList = {}) inline
Add an empty node to the graph.
Parameters
PropList Property list used to pass [0..n] predecessor nodes.
Returns
Constructed empty node which has been added to the graph.
Definition at line 231 of file graph.hpp.
add() [2/2]
template<typename T > node sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::add (T CGF, const property_list & PropList = {}) inline
Add a command-group node to the graph.
Parameters
CGF Command-group function to create node with.
PropList Property list used to pass [0..n] predecessor nodes.
Returns
Constructed node which has been added to the graph.
Definition at line 251 of file graph.hpp.
addGraphLeafDependencies()
void sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::addGraphLeafDependencies (node Node) protected
Adds all graph leaves as dependencies.
Parameters
Node Destination node to which the leaves of the graph will be added as dependencies.
Definition at line 1493 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and impl.
addImpl() [1/2]
node sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::addImpl (const std::vector< node > & Dep) protected
Template-less implementation of add() for empty nodes.
Parameters
Dep List of predecessor nodes.
Returns
Node added to the graph.
Definition at line 1467 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and impl.
addImpl() [2/2]
node sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::addImpl (std::function< void(handler &)> CGF, const std::vector< node > & Dep) protected
Template-less implementation of add() for CGF nodes.
Parameters
CGF Command-group function to add.
Dep List of predecessor nodes.
Returns
Node added to the graph.
Definition at line 1479 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and impl.
begin_recording() [1/2]
void sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::begin_recording (const std::vector< queue > & RecordingQueues, const property_list & PropList = {})
Change the state of multiple queues to be recording and associate this graph with each of them.
Parameters
RecordingQueues The queues to change state on and associate this graph with.
PropList Property list used to pass properties for recording.
begin_recording() [2/2]
void sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::begin_recording (queue & RecordingQueue, const property_list & PropList = {})
Change the state of a queue to be recording and associate this graph with it.
Parameters
RecordingQueue The queue to change state on and associate this graph with.
PropList Property list used to pass properties for recording.
end_recording() [1/3]
void sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::end_recording ()
Set all queues currently recording to this graph to the executing state.
Definition at line 1579 of file graph_impl.cpp.
References impl.
Referenced by end_recording().
end_recording() [2/3]
void sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::end_recording (const std::vector< queue > & RecordingQueues)
Set multiple queues currently recording to this graph to the executing state.
Parameters
RecordingQueues The queues to change state on.
Definition at line 1598 of file graph_impl.cpp.
References end_recording().
end_recording() [3/3]
void sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::end_recording (queue & RecordingQueue)
Set a queue currently recording to this graph to the executing state.
Parameters
RecordingQueue The queue to change state on.
Definition at line 1584 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), impl, and sycl::_V1::invalid.
finalize()
command_graph< graph_state::executable > sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::finalize (const property_list & PropList = {}) const
Finalize modifiable graph into an executable graph.
Parameters
PropList Property list used to pass properties for finalization.
Returns
Executable graph object.
Definition at line 1517 of file graph_impl.cpp.
References impl.
get_nodes()
std::vector< node > sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::get_nodes () const
Get a list of all nodes contained in this graph.
Definition at line 1617 of file graph_impl.cpp.
References impl.
get_root_nodes()
std::vector< node > sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::get_root_nodes () const
Get a list of all root nodes (nodes without dependencies) in this graph.
Definition at line 1620 of file graph_impl.cpp.
References sycl::_V1::ext::oneapi::experimental::copy(), and impl.
make_edge()
void sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::make_edge (node & Src, node & Dest)
Add a dependency between two nodes.
Parameters
Src Node which will be a dependency of Dest.
Dest Node which will be dependent on Src.
Definition at line 1506 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and impl.
print_graph()
void sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::print_graph (const std::string path, bool verbose = false) const
Synchronous operation that writes a DOT formatted description of the graph to the provided path.
By default, this includes the graph topology, node types, node id and kernel names.
Parameters
path The path to write the DOT file to.
verbose If true, print additional information about the nodes such as kernel args or memory access where applicable.
Definition at line 1605 of file graph_impl.cpp.
References impl, and sycl::_V1::invalid.
sycl::detail::getSyclObjImpl()
template<class Obj > decltype(Obj::impl) friend sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::sycl::detail::getSyclObjImpl (const Obj & SyclObject) protected
Friends And Related Function Documentation
sycl::detail::createSyclObjFromImpl
template<class T > T sycl::detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
Member Data Documentation
impl
std::shared_ptr<detail::graph_impl> sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::impl protected
Definition at line 349 of file graph.hpp.
Referenced by addGraphLeafDependencies(), addImpl(), end_recording(), finalize(), get_nodes(), get_root_nodes(), make_edge(), and print_graph().
The documentation for this class was generated from the following files:
include/sycl/ext/oneapi/experimental/graph.hpp
source/detail/graph_impl.cpp