DPC++ Runtime: cl::sycl::detail::ExecCGCommand Class Reference
cl::sycl::detail::ExecCGCommand Class Reference
The exec CG command enqueues execution of kernel or explicit memory operation.
#include <detail/scheduler/commands.hpp>
Public Member Functions
ExecCGCommand (std::unique_ptr< detail::CG > CommandGroup, QueueImplPtr Queue)
std::vector< StreamImplPtr > getStreams () const
std::vector< std::shared_ptr< const void > > getAuxiliaryResources () const
void clearStreams ()
void clearAuxiliaryResources ()
void printDot (std::ostream &Stream) const final
void emitInstrumentationData () final
Instrumentation method which emits telemetry data.
detail::CG & getCG () const
bool producesPiEvent () const final
Returns true iff the command produces a PI event on non-host devices.
bool supportsPostEnqueueCleanup () const final
Returns true iff this command can be freed by post enqueue cleanup.
Public Member Functions inherited from cl::sycl::detail::Command
Command (CommandType Type, QueueImplPtr Queue)
It is safe to bind MPreparedDepsEvents and MPreparedHostDepsEvents references to event_impl class members because Command should not outlive the event connected to it.
Command * addDep (DepDesc NewDep, std::vector< Command * > &ToCleanUp)
Command * addDep (EventImplPtr Event, std::vector< Command * > &ToCleanUp)
void addUser (Command *NewUser)
CommandType getType () const
virtual bool enqueue (EnqueueResultT &EnqueueResult, BlockingT Blocking, std::vector< Command * > &ToCleanUp)
Checks if the command is enqueued, and calls enqueueImp.
bool isFinished ()
bool isSuccessfullyEnqueued () const
bool isEnqueueBlocked () const
const QueueImplPtr & getQueue () const
const QueueImplPtr & getSubmittedQueue () const
const EventImplPtr & getEvent () const
void emitInstrumentationDataProxy ()
Proxy method which calls emitInstrumentationData.
void resolveReleaseDependencies (std::set< Command * > &list)
Looks at all the dependencies for the release command and enables instrumentation to report these dependencies as edges.
void emitEdgeEventForCommandDependence (Command *Cmd, void *ObjAddr, bool IsCommand, std::optional< access::mode > AccMode=std::nullopt)
Creates an edge event when the dependency is a command.
void emitEdgeEventForEventDependence (Command *Cmd, RT::PiEvent &EventAddr)
Creates an edge event when the dependency is an event.
void emitEnqueuedEventSignal (RT::PiEvent &PiEventAddr)
Creates a signal event with the enqueued kernel event handle.
uint64_t makeTraceEventProlog (void *MAddress)
Create a trace event of node_create type; this must be guarded by a check for xptiTraceEnabled().
void makeTraceEventEpilog ()
If prolog has been run, run epilog; this must be guarded by a check for xptiTraceEnabled().
void emitInstrumentation (uint16_t Type, const char *Txt=nullptr)
Emits an event of Type.
virtual const Requirement * getRequirement () const
virtual ~Command ()
const char * getBlockReason () const
virtual const ContextImplPtr & getWorkerContext () const
Get the context of the queue this command will be submitted to.
virtual const QueueImplPtr & getWorkerQueue () const
Get the queue this command will be submitted to.
const std::vector< EventImplPtr > & getPreparedHostDepsEvents () const
Public Attributes
EmptyCommand * MEmptyCmd = nullptr
Public Attributes inherited from cl::sycl::detail::Command
std::vector< DepDesc > MDeps
Contains list of dependencies(edges)
std::unordered_set< Command * > MUsers
Contains list of commands that depend on the command.
bool MIsBlockable = false
Indicates whether the command can be blocked from enqueueing.
unsigned MLeafCounter = 0
Counts the number of memory objects this command is a leaf for.
Marks MMarks
Used for marking the node during graph traversal.
BlockReason MBlockReason
std::atomic< EnqueueResultT::ResultT > MEnqueueStatus
Describes the status of the command.
void * MTraceEvent = nullptr
The event for node_create and task_begin.
int32_t MStreamID = -1
The stream under which the traces are emitted.
void * MAddress = nullptr
Reserved for storing the object address such as SPIR-V or memory object address.
std::string MAddressString
Buffer to build the address string.
std::string MCommandNodeType
Buffer to build the command node type.
std::string MCommandName
Buffer to build the command end-user understandable name.
bool MTraceEventPrologComplete = false
Flag to indicate if makeTraceEventProlog() has been run.
bool MFirstInstance = false
Flag to indicate if this is the first time we are seeing this payload.
uint64_t MInstanceID = 0
Instance ID tracked for the command.
bool MShouldCompleteEventIfPossible = true
bool MPostEnqueueCleanup = false
Indicates that the node will be freed by cleanup after enqueue.
Friends
class Command
Additional Inherited Members
Public Types inherited from cl::sycl::detail::Command
enum CommandType {
RUN_CG, COPY_MEMORY, ALLOCA, ALLOCA_SUB_BUF,
RELEASE, MAP_MEM_OBJ, UNMAP_MEM_OBJ, UPDATE_REQUIREMENT,
EMPTY_TASK, HOST_TASK
}
enum BlockReason : int { BlockReason::HostAccessor = 0, BlockReason::HostTask }
Protected Member Functions inherited from cl::sycl::detail::Command
void waitForEvents (QueueImplPtr Queue, std::vector< EventImplPtr > &RawEvents, RT::PiEvent &Event)
void waitForPreparedHostEvents () const
Command * processDepEvent (EventImplPtr DepEvent, const DepDesc &Dep, std::vector< Command * > &ToCleanUp)
Perform glueing of events from different contexts.
Protected Attributes inherited from cl::sycl::detail::Command
QueueImplPtr MQueue
QueueImplPtr MSubmittedQueue
EventImplPtr MEvent
std::vector< EventImplPtr > & MPreparedDepsEvents
Dependency events prepared for waiting by backend.
std::vector< EventImplPtr > & MPreparedHostDepsEvents
CommandType MType
The type of the command.
std::mutex MEnqueueMtx
Mutex used to protect enqueueing from race conditions.
Detailed Description
The exec CG command enqueues execution of kernel or explicit memory operation.
Definition at line 539 of file commands.hpp.
Constructor & Destructor Documentation
ExecCGCommand()
cl::sycl::detail::ExecCGCommand::ExecCGCommand (std::unique_ptr< detail::CG > CommandGroup, QueueImplPtr Queue)
Definition at line 1679 of file commands.cpp.
References cl::sycl::detail::CG::CodeplayHostTask, cl::sycl::detail::Command::emitInstrumentationDataProxy(), cl::sycl::detail::Command::MEvent, cl::sycl::detail::Command::MQueue, and cl::sycl::detail::Command::MSubmittedQueue.
Member Function Documentation
clearAuxiliaryResources()
void cl::sycl::detail::ExecCGCommand::clearAuxiliaryResources ()
Definition at line 1393 of file commands.cpp.
References cl::sycl::detail::CG::Kernel.
clearStreams()
void cl::sycl::detail::ExecCGCommand::clearStreams ()
Definition at line 1388 of file commands.cpp.
References cl::sycl::detail::CG::Kernel.
emitInstrumentationData()
void cl::sycl::detail::ExecCGCommand::emitInstrumentationData () final virtual
Instrumentation method which emits telemetry data.
Implements cl::sycl::detail::Command.
Definition at line 1696 of file commands.cpp.
References cl::sycl::detail::cgTypeToString(), cl::sycl::detail::demangleKernelName(), cl::sycl::detail::deviceToString(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::CG::Kernel, cl::sycl::detail::Command::MAddress, cl::sycl::detail::Command::MInstanceID, cl::sycl::detail::Command::MQueue, cl::sycl::detail::Command::MStreamID, cl::sycl::detail::Command::MTraceEvent, and cl::sycl::detail::Command::MType.
getAuxiliaryResources()
std::vector< std::shared_ptr< const void > > cl::sycl::detail::ExecCGCommand::getAuxiliaryResources () const
Definition at line 1382 of file commands.cpp.
References cl::sycl::detail::CG::Kernel.
getCG()
detail::CG& cl::sycl::detail::ExecCGCommand::getCG () const inline
Definition at line 552 of file commands.hpp.
Referenced by cl::sycl::detail::DispatchHostTask::operator()().
getStreams()
std::vector< StreamImplPtr > cl::sycl::detail::ExecCGCommand::getStreams () const
Definition at line 1375 of file commands.cpp.
References cl::sycl::detail::CG::Kernel.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), and cl::sycl::detail::Scheduler::GraphBuilder::cleanupFinishedCommands().
printDot()
void cl::sycl::detail::ExecCGCommand::printDot (std::ostream & Stream) const final virtual
Implements cl::sycl::detail::Command.
Definition at line 1790 of file commands.cpp.
References cl::sycl::detail::accessModeToString(), cl::sycl::detail::cgTypeToString(), cl::sycl::detail::demangleKernelName(), cl::sycl::detail::deviceToString(), cl::sycl::detail::CG::Kernel, cl::sycl::detail::Command::MDeps, and cl::sycl::detail::Command::MQueue.
producesPiEvent()
bool cl::sycl::detail::ExecCGCommand::producesPiEvent () const final virtual
Returns true iff the command produces a PI event on non-host devices.
Reimplemented from cl::sycl::detail::Command.
Definition at line 2488 of file commands.cpp.
supportsPostEnqueueCleanup()
bool cl::sycl::detail::ExecCGCommand::supportsPostEnqueueCleanup () const final virtual
Returns true iff this command can be freed by post enqueue cleanup.
Reimplemented from cl::sycl::detail::Command.
Definition at line 2492 of file commands.cpp.
References cl::sycl::detail::Command::supportsPostEnqueueCleanup().
Friends And Related Function Documentation
Command
friend class Command friend
Definition at line 571 of file commands.hpp.
Member Data Documentation
MEmptyCmd
EmptyCommand* cl::sycl::detail::ExecCGCommand::MEmptyCmd = nullptr
Definition at line 558 of file commands.hpp.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::connectDepEvent(), and cl::sycl::detail::DispatchHostTask::operator()().
The documentation for this class was generated from the following files:
source/detail/scheduler/commands.hpp
source/detail/scheduler/commands.cpp