DPC++ Runtime: USMAllocContext Class Reference
USMAllocContext Class Reference
#include <level_zero/usm_allocator.hpp>
Classes
class USMAllocImpl
Public Member Functions
USMAllocContext (std::unique_ptr< SystemMemory > memHandle)
~USMAllocContext ()
void * allocate (size_t size)
void * allocate (size_t size, size_t alignment)
void deallocate (void *ptr)
Detailed Description
Definition at line 25 of file usm_allocator.hpp.
Constructor & Destructor Documentation
USMAllocContext()
USMAllocContext::USMAllocContext (std::unique_ptr< SystemMemory > memHandle)
Definition at line 980 of file usm_allocator.cpp.
~USMAllocContext()
USMAllocContext::~USMAllocContext ()
Definition at line 1026 of file usm_allocator.cpp.
References settings::SetLimits::CurPoolSize, SystemMemory::Device, SystemMemory::Host, settings::SetLimits::PoolTrace, and settings::USMSettings.
Member Function Documentation
allocate() [1/2]
void * USMAllocContext::allocate (size_t size)
Definition at line 983 of file usm_allocator.cpp.
References MemTypeNames, settings::SetLimits::PoolTrace, cl::sycl::setw(), and settings::USMSettings.
Referenced by USMAllocContext::USMAllocImpl::allocate().
allocate() [2/2]
void * USMAllocContext::allocate (size_t size, size_t alignment)
Definition at line 996 of file usm_allocator.cpp.
References MemTypeNames, settings::SetLimits::PoolTrace, cl::sycl::setw(), and settings::USMSettings.
deallocate()
void USMAllocContext::deallocate (void * ptr)
Definition at line 1009 of file usm_allocator.cpp.
References settings::SetLimits::CurPoolSize, settings::SetLimits::CurPoolSizes, SystemMemory::Device, SystemMemory::Host, MemTypeNames, settings::SetLimits::PoolTrace, SystemMemory::Shared, and settings::USMSettings.
The documentation for this class was generated from the following files:
plugins/level_zero/usm_allocator.hpp
plugins/level_zero/usm_allocator.cpp