DPC++ Runtime: sycl::_V1::detail::XPTIRegistry Class Reference
sycl::_V1::detail::XPTIRegistry Class Reference
#include <detail/xpti_registry.hpp>
Public Member Functions
void initializeFrameworkOnce ()
void initializeStream (const std::string &StreamName, uint32_t MajVer, uint32_t MinVer, const std::string &VerStr)
Notifies XPTI subscribers about new stream.
~XPTIRegistry ()
Static Public Member Functions
static void bufferConstructorNotification (const void *, const detail::code_location &, const void *, const void *, uint32_t, uint32_t, size_t[3])
static void bufferAssociateNotification (const void *, const void *)
static void bufferReleaseNotification (const void *, const void *)
static void bufferDestructorNotification (const void *)
static void bufferAccessorNotification (const void *, const void *, uint32_t, uint32_t, const detail::code_location &)
static void sampledImageConstructorNotification (const void *, const detail::code_location &, const void *, uint32_t, size_t[3], uint32_t, uint32_t, uint32_t, uint32_t)
static void sampledImageDestructorNotification (const void *)
static void unsampledImageConstructorNotification (const void *, const detail::code_location &, const void *, uint32_t, size_t[3], uint32_t)
static void unsampledImageDestructorNotification (const void *)
static void unsampledImageAccessorNotification (const void *, const void *, uint32_t, uint32_t, const void *, uint32_t, const detail::code_location &)
static void unsampledImageHostAccessorNotification (const void *, const void *, uint32_t, const void *, uint32_t, const detail::code_location &)
static void sampledImageAccessorNotification (const void *, const void *, uint32_t, const void *, uint32_t, const detail::code_location &)
static void sampledImageHostAccessorNotification (const void *, const void *, const void *, uint32_t, const detail::code_location &)
Detailed Description
Definition at line 66 of file xpti_registry.hpp.
Constructor & Destructor Documentation
~XPTIRegistry()
sycl::_V1::detail::XPTIRegistry::~XPTIRegistry () inline
Definition at line 105 of file xpti_registry.hpp.
Member Function Documentation
bufferAccessorNotification()
void sycl::_V1::detail::XPTIRegistry::bufferAccessorNotification (const void * UserObj, const void * AccessorObj, uint32_t Target, uint32_t Mode, const detail::code_location & CodeLoc) static
Definition at line 124 of file xpti_registry.cpp.
References sycl::_V1::Mode.
Referenced by sycl::_V1::detail::constructorNotification().
bufferAssociateNotification()
void sycl::_V1::detail::XPTIRegistry::bufferAssociateNotification (const void * UserObj, const void * MemObj) static
Definition at line 71 of file xpti_registry.cpp.
Referenced by sycl::_V1::detail::MemoryManager::allocateMemBuffer().
bufferConstructorNotification()
void sycl::_V1::detail::XPTIRegistry::bufferConstructorNotification (const void * UserObj, const detail::code_location & CodeLoc, const void * HostObj, const void * Type, uint32_t Dim, uint32_t ElemSize, size_t Range[3]) static
Definition at line 38 of file xpti_registry.cpp.
References sycl::_V1::detail::GlobalHandler::getXPTIRegistry(), initializeFrameworkOnce(), and sycl::_V1::detail::GlobalHandler::instance().
Referenced by sycl::_V1::detail::buffer_impl::constructorNotification().
bufferDestructorNotification()
void sycl::_V1::detail::XPTIRegistry::bufferDestructorNotification (const void * UserObj) static
Definition at line 109 of file xpti_registry.cpp.
Referenced by sycl::_V1::detail::buffer_impl::destructorNotification().
bufferReleaseNotification()
void sycl::_V1::detail::XPTIRegistry::bufferReleaseNotification (const void * UserObj, const void * MemObj) static
Definition at line 90 of file xpti_registry.cpp.
Referenced by sycl::_V1::detail::MemoryManager::release().
initializeFrameworkOnce()
void sycl::_V1::detail::XPTIRegistry::initializeFrameworkOnce () inline
Definition at line 68 of file xpti_registry.hpp.
References initializeStream(), sycl::_V1::detail::SYCL_BUFFER_STREAM_NAME, sycl::_V1::detail::SYCL_IMAGE_STREAM_NAME, and sycl::_V1::detail::SYCL_MEM_ALLOC_STREAM_NAME.
Referenced by bufferConstructorNotification(), sycl::_V1::detail::pi::initializePlugins(), sampledImageConstructorNotification(), and unsampledImageConstructorNotification().
initializeStream()
void sycl::_V1::detail::XPTIRegistry::initializeStream (const std::string & StreamName, uint32_t MajVer, uint32_t MinVer, const std::string & VerStr) inline
Notifies XPTI subscribers about new stream.
Parameters
StreamName is a name of newly initialized stream.
MajVer is a stream major version.
MinVer is a stream minor version.
VerStr is a string of "MajVer.MinVer" format.
Definition at line 97 of file xpti_registry.hpp.
Referenced by initializeFrameworkOnce(), sycl::_V1::detail::pi::initializePlugins(), and sycl::_V1::detail::GlobalHandler::InitXPTI().
sampledImageAccessorNotification()
void sycl::_V1::detail::XPTIRegistry::sampledImageAccessorNotification (const void * UserObj, const void * AccessorObj, uint32_t Target, const void * Type, uint32_t ElemSize, const detail::code_location & CodeLoc) static
Definition at line 312 of file xpti_registry.cpp.
Referenced by sycl::_V1::detail::sampledImageConstructorNotification().
sampledImageConstructorNotification()
void sycl::_V1::detail::XPTIRegistry::sampledImageConstructorNotification (const void * UserObj, const detail::code_location & CodeLoc, const void * HostObj, uint32_t Dim, size_t Range[3], uint32_t ImageFormat, uint32_t SamplerAddressingMode, uint32_t SamplerCoordinateNormalizationMode, uint32_t SamplerFilteringMode) static
Definition at line 148 of file xpti_registry.cpp.
References sycl::_V1::detail::GlobalHandler::getXPTIRegistry(), initializeFrameworkOnce(), and sycl::_V1::detail::GlobalHandler::instance().
Referenced by sycl::_V1::detail::image_impl::sampledImageConstructorNotification().
sampledImageDestructorNotification()
void sycl::_V1::detail::XPTIRegistry::sampledImageDestructorNotification (const void * UserObj) static
Definition at line 187 of file xpti_registry.cpp.
Referenced by sycl::_V1::detail::image_impl::sampledImageDestructorNotification().
sampledImageHostAccessorNotification()
void sycl::_V1::detail::XPTIRegistry::sampledImageHostAccessorNotification (const void * UserObj, const void * AccessorObj, const void * Type, uint32_t ElemSize, const detail::code_location & CodeLoc) static
Definition at line 339 of file xpti_registry.cpp.
Referenced by sycl::_V1::detail::sampledImageConstructorNotification().
unsampledImageAccessorNotification()
void sycl::_V1::detail::XPTIRegistry::unsampledImageAccessorNotification (const void * UserObj, const void * AccessorObj, uint32_t Target, uint32_t Mode, const void * Type, uint32_t ElemSize, const detail::code_location & CodeLoc) static
Definition at line 252 of file xpti_registry.cpp.
References sycl::_V1::Mode.
Referenced by sycl::_V1::detail::unsampledImageConstructorNotification().
unsampledImageConstructorNotification()
void sycl::_V1::detail::XPTIRegistry::unsampledImageConstructorNotification (const void * UserObj, const detail::code_location & CodeLoc, const void * HostObj, uint32_t Dim, size_t Range[3], uint32_t ImageFormat) static
Definition at line 202 of file xpti_registry.cpp.
References sycl::_V1::detail::GlobalHandler::getXPTIRegistry(), initializeFrameworkOnce(), and sycl::_V1::detail::GlobalHandler::instance().
Referenced by sycl::_V1::detail::image_impl::unsampledImageConstructorNotification().
unsampledImageDestructorNotification()
void sycl::_V1::detail::XPTIRegistry::unsampledImageDestructorNotification (const void * UserObj) static
Definition at line 237 of file xpti_registry.cpp.
Referenced by sycl::_V1::detail::image_impl::unsampledImageDestructorNotification().
unsampledImageHostAccessorNotification()
void sycl::_V1::detail::XPTIRegistry::unsampledImageHostAccessorNotification (const void * UserObj, const void * AccessorObj, uint32_t Mode, const void * Type, uint32_t ElemSize, const detail::code_location & CodeLoc) static
Definition at line 284 of file xpti_registry.cpp.
References sycl::_V1::Mode.
Referenced by sycl::_V1::detail::unsampledImageConstructorNotification().
The documentation for this class was generated from the following files:
source/detail/xpti_registry.hpp
source/detail/xpti_registry.cpp