DPC++ Runtime: syclcompat::detail::dev_mgr Class Reference
syclcompat::detail::dev_mgr Class Reference
device manager
#include <syclcompat/device.hpp>
Public Member Functions
device_ext & current_device ()
device_ext & cpu_device () const
device_ext & get_device (unsigned int id) const
unsigned int current_device_id () const
void select_device (unsigned int id)
Select device with a device ID.
unsigned int device_count ()
unsigned int get_device_id (const sycl::device &dev)
void list_devices () const
List all the devices with its id in dev_mgr.
void filter (const std::vector< std::string > &dev_subnames)
Filter out devices; only keep the device whose name contains one of the subname in dev_subnames.
template<class DeviceSelector >
std::enable_if_t< std::is_invocable_r_v< int, DeviceSelector, const sycl::device & > > select_device (const DeviceSelector &selector=sycl::gpu_selector_v)
Select device with a Device Selector.
dev_mgr (const dev_mgr &)=delete
dev_mgr & operator= (const dev_mgr &)=delete
dev_mgr (dev_mgr &&)=delete
dev_mgr & operator= (dev_mgr &&)=delete
Static Public Member Functions
static dev_mgr & instance ()
Returns the instance of device manager singleton.
Detailed Description
device manager
Definition at line 711 of file device.hpp.
Constructor & Destructor Documentation
dev_mgr() [1/2]
syclcompat::detail::dev_mgr::dev_mgr (const dev_mgr &) delete
dev_mgr() [2/2]
syclcompat::detail::dev_mgr::dev_mgr (dev_mgr &&) delete
Member Function Documentation
cpu_device()
device_ext& syclcompat::detail::dev_mgr::cpu_device () const inline
Definition at line 718 of file device.hpp.
Referenced by syclcompat::cpu_device().
current_device()
device_ext& syclcompat::detail::dev_mgr::current_device () inline
Definition at line 713 of file device.hpp.
References current_device_id().
Referenced by syclcompat::create_queue(), syclcompat::get_current_device(), syclcompat::get_default_queue(), syclcompat::get_kernel_function_info(), syclcompat::int_as_queue_ptr(), and syclcompat::set_default_queue().
current_device_id()
unsigned int syclcompat::detail::dev_mgr::current_device_id () const inline
Definition at line 731 of file device.hpp.
References syclcompat::detail::get_tid().
Referenced by current_device(), and syclcompat::get_current_device_id().
device_count()
unsigned int syclcompat::detail::dev_mgr::device_count () inline
Definition at line 747 of file device.hpp.
Referenced by syclcompat::device_count().
filter()
void syclcompat::detail::dev_mgr::filter (const std::vector< std::string > & dev_subnames) inline
Filter out devices; only keep the device whose name contains one of the subname in dev_subnames.
May break device id mapping and change current device. It's better to be called before other SYCLcompat/SYCL APIs.
Definition at line 780 of file device.hpp.
References list_devices().
Referenced by syclcompat::filter_device().
get_device()
device_ext& syclcompat::detail::dev_mgr::get_device (unsigned int id) const inline
Definition at line 726 of file device.hpp.
Referenced by syclcompat::get_device().
get_device_id()
unsigned int syclcompat::detail::dev_mgr::get_device_id (const sycl::device & dev) inline
Definition at line 749 of file device.hpp.
References sycl::_V1::device::get_info().
Referenced by syclcompat::get_device_id(), syclcompat::pointer_attributes::init(), and select_device().
instance()
static dev_mgr& syclcompat::detail::dev_mgr::instance () inline static
Returns the instance of device manager singleton.
Definition at line 823 of file device.hpp.
Referenced by syclcompat::cpu_device(), syclcompat::create_queue(), syclcompat::device_count(), syclcompat::device_memory< T, Memory, Dimension >::device_memory(), syclcompat::filter_device(), syclcompat::get_current_device(), syclcompat::get_current_device_id(), syclcompat::get_default_queue(), syclcompat::get_device(), syclcompat::get_device_id(), syclcompat::get_kernel_function_info(), syclcompat::pointer_attributes::init(), syclcompat::int_as_queue_ptr(), syclcompat::list_devices(), syclcompat::select_device(), and syclcompat::set_default_queue().
list_devices()
void syclcompat::detail::dev_mgr::list_devices () const inline
List all the devices with its id in dev_mgr.
Definition at line 769 of file device.hpp.
References std::cout.
Referenced by filter(), syclcompat::list_devices(), and operator=().
operator=() [1/2]
dev_mgr& syclcompat::detail::dev_mgr::operator= (const dev_mgr &) delete
operator=() [2/2]
dev_mgr& syclcompat::detail::dev_mgr::operator= (dev_mgr &&) delete
References sycl::_V1::device::is_cpu(), and list_devices().
select_device() [1/2]
template<class DeviceSelector > std::enable_if_t< std::is_invocable_r_v<int, DeviceSelector, const sycl::device &> > syclcompat::detail::dev_mgr::select_device (const DeviceSelector & selector = sycl::gpu_selector_v) inline
Select device with a Device Selector.
Parameters
selector device selector to get the device id from. Defaults to sycl::gpu_selector_v
Definition at line 816 of file device.hpp.
References get_device_id(), and select_device().
select_device() [2/2]
void syclcompat::detail::dev_mgr::select_device (unsigned int id) inline
Select device with a device ID.
Parameters
[in] id The id of the device which can be obtained through get_device_id(const sycl::device).
Definition at line 742 of file device.hpp.
References syclcompat::detail::get_tid().
Referenced by select_device(), and syclcompat::select_device().
The documentation for this class was generated from the following file:
include/syclcompat/device.hpp