DPC++ Runtime: sycl::_V1::detail::DeviceBinaryProperty Class Reference
sycl::_V1::detail::DeviceBinaryProperty Class Reference
#include <detail/device_binary_image.hpp>
Public Member Functions
DeviceBinaryProperty (const _pi_device_binary_property_struct *Prop)
pi_uint32 asUint32 () const
ByteArray asByteArray () const
const char * asCString () const
Protected Attributes
const _pi_device_binary_property_struct * Prop
Friends
std::ostream & operator<< (std::ostream &Out, const DeviceBinaryProperty &P)
Detailed Description
Definition at line 64 of file device_binary_image.hpp.
Constructor & Destructor Documentation
DeviceBinaryProperty()
sycl::_V1::detail::DeviceBinaryProperty::DeviceBinaryProperty (const _pi_device_binary_property_struct * Prop) inline
Definition at line 66 of file device_binary_image.hpp.
Member Function Documentation
asByteArray()
ByteArray sycl::_V1::detail::DeviceBinaryProperty::asByteArray () const
Definition at line 69 of file device_binary_image.cpp.
References PI_PROPERTY_TYPE_BYTE_ARRAY, Prop, _pi_device_binary_property_struct::Type, _pi_device_binary_property_struct::ValAddr, and _pi_device_binary_property_struct::ValSize.
Referenced by sycl::_V1::detail::ProgramManager::addImages(), sycl::_V1::detail::checkDevSupportDeviceRequirements(), and sycl::_V1::detail::program_impl::flush_spec_constants().
asCString()
const char * sycl::_V1::detail::DeviceBinaryProperty::asCString () const
Definition at line 76 of file device_binary_image.cpp.
References PI_PROPERTY_TYPE_STRING, Prop, _pi_device_binary_property_struct::Type, _pi_device_binary_property_struct::ValAddr, and _pi_device_binary_property_struct::ValSize.
asUint32()
pi_uint32 sycl::_V1::detail::DeviceBinaryProperty::asUint32 () const
Definition at line 61 of file device_binary_image.cpp.
References PI_PROPERTY_TYPE_UINT32, Prop, _pi_device_binary_property_struct::Type, _pi_device_binary_property_struct::ValAddr, and _pi_device_binary_property_struct::ValSize.
Referenced by sycl::_V1::detail::ProgramManager::addImages(), sycl::_V1::detail::appendCompileOptionsForGRFSizeProperties(), sycl::_V1::detail::checkDevSupportDeviceRequirements(), sycl::_V1::detail::ProgramManager::getDeviceLibReqMask(), sycl::_V1::detail::getUint32PropAsBool(), sycl::_V1::detail::getUint32PropAsOptStr(), and sycl::_V1::detail::device_image_impl::specialization_constants_replaced_with_default().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & Out, const DeviceBinaryProperty & P) friend
Definition at line 20 of file device_binary_image.cpp.
Member Data Documentation
Prop
const _pi_device_binary_property_struct* sycl::_V1::detail::DeviceBinaryProperty::Prop protected
Definition at line 76 of file device_binary_image.hpp.
Referenced by asByteArray(), asCString(), and asUint32().
The documentation for this class was generated from the following files:
source/detail/device_binary_image.hpp
source/detail/device_binary_image.cpp