DPC++ Runtime: sycl::_V1::detail::device_filter_list Class Reference
sycl::_V1::detail::device_filter_list Class Reference
#include <sycl/detail/device_filter.hpp>
Public Member Functions
device_filter_list ()
device_filter_list (const std::string &FilterString)
device_filter_list (device_filter &Filter)
void addFilter (device_filter &Filter)
std::vector< device_filter > & get ()
bool backendCompatible (backend Backend)
bool deviceTypeCompatible (info::device_type DeviceType)
bool deviceNumberCompatible (int DeviceNum)
Friends
std::ostream & operator<< (std::ostream &Out, const device_filter_list &List)
Detailed Description
Definition at line 88 of file device_filter.hpp.
Constructor & Destructor Documentation
device_filter_list() [1/3]
sycl::_V1::detail::device_filter_list::device_filter_list () inline
Definition at line 92 of file device_filter.hpp.
device_filter_list() [2/3]
sycl::_V1::detail::device_filter_list::device_filter_list (const std::string & FilterString)
Definition at line 382 of file device_filter.cpp.
device_filter_list() [3/3]
sycl::_V1::detail::device_filter_list::device_filter_list (device_filter & Filter)
Definition at line 402 of file device_filter.cpp.
Member Function Documentation
addFilter()
void sycl::_V1::detail::device_filter_list::addFilter (device_filter & Filter)
Definition at line 406 of file device_filter.cpp.
backendCompatible()
bool sycl::_V1::detail::device_filter_list::backendCompatible (backend Backend)
Definition at line 413 of file device_filter.cpp.
References any_of().
Referenced by sycl::_V1::device::get_devices().
deviceNumberCompatible()
bool sycl::_V1::detail::device_filter_list::deviceNumberCompatible (int DeviceNum)
Definition at line 431 of file device_filter.cpp.
References any_of().
deviceTypeCompatible()
bool sycl::_V1::detail::device_filter_list::deviceTypeCompatible (info::device_type DeviceType)
Definition at line 421 of file device_filter.cpp.
References any_of().
get()
std::vector<device_filter>& sycl::_V1::detail::device_filter_list::get () inline
Definition at line 96 of file device_filter.hpp.
Referenced by sycl::_V1::detail::pi::findPlugins().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & Out, const device_filter_list & List) friend
Definition at line 126 of file device_filter.hpp.
The documentation for this class was generated from the following files:
include/sycl/detail/device_filter.hpp
source/detail/device_filter.cpp