DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::opportunistic_group Class Reference
sycl::_V1::ext::oneapi::experimental::opportunistic_group Class Reference
#include <sycl/ext/oneapi/experimental/opportunistic_group.hpp>
Public Types
using id_type = id< 1 >
using range_type = range< 1 >
using linear_id_type = uint32_t
Public Member Functions
id_type get_group_id () const
id_type get_local_id () const
range_type get_group_range () const
range_type get_local_range () const
linear_id_type get_group_linear_id () const
linear_id_type get_local_linear_id () const
linear_id_type get_group_linear_range () const
linear_id_type get_local_linear_range () const
bool leader () const
Static Public Attributes
static constexpr int dimensions = 1
static constexpr sycl::memory_scope fence_scope
Protected Member Functions
opportunistic_group (sub_group_mask m)
Protected Attributes
sub_group_mask Mask
Friends
opportunistic_group this_kernel::get_opportunistic_group ()
sub_group_mask sycl::detail::GetMask (opportunistic_group Group)
Detailed Description
Definition at line 40 of file opportunistic_group.hpp.
Member Typedef Documentation
id_type
using sycl::_V1::ext::oneapi::experimental::opportunistic_group::id_type = id<1>
Definition at line 42 of file opportunistic_group.hpp.
linear_id_type
using sycl::_V1::ext::oneapi::experimental::opportunistic_group::linear_id_type = uint32_t
Definition at line 44 of file opportunistic_group.hpp.
range_type
using sycl::_V1::ext::oneapi::experimental::opportunistic_group::range_type = range<1>
Definition at line 43 of file opportunistic_group.hpp.
Constructor & Destructor Documentation
opportunistic_group()
sycl::_V1::ext::oneapi::experimental::opportunistic_group::opportunistic_group (sub_group_mask m) inline protected
Definition at line 134 of file opportunistic_group.hpp.
Member Function Documentation
get_group_id()
id_type sycl::_V1::ext::oneapi::experimental::opportunistic_group::get_group_id () const inline
Definition at line 49 of file opportunistic_group.hpp.
Referenced by get_group_linear_id().
get_group_linear_id()
linear_id_type sycl::_V1::ext::oneapi::experimental::opportunistic_group::get_group_linear_id () const inline
Definition at line 85 of file opportunistic_group.hpp.
References get_group_id().
get_group_linear_range()
linear_id_type sycl::_V1::ext::oneapi::experimental::opportunistic_group::get_group_linear_range () const inline
Definition at line 103 of file opportunistic_group.hpp.
References get_group_range().
get_group_range()
range_type sycl::_V1::ext::oneapi::experimental::opportunistic_group::get_group_range () const inline
Definition at line 67 of file opportunistic_group.hpp.
Referenced by get_group_linear_range().
get_local_id()
id_type sycl::_V1::ext::oneapi::experimental::opportunistic_group::get_local_id () const inline
Definition at line 58 of file opportunistic_group.hpp.
References Mask.
Referenced by get_local_linear_id().
get_local_linear_id()
linear_id_type sycl::_V1::ext::oneapi::experimental::opportunistic_group::get_local_linear_id () const inline
Definition at line 94 of file opportunistic_group.hpp.
References get_local_id().
get_local_linear_range()
linear_id_type sycl::_V1::ext::oneapi::experimental::opportunistic_group::get_local_linear_range () const inline
Definition at line 112 of file opportunistic_group.hpp.
References get_local_range().
get_local_range()
range_type sycl::_V1::ext::oneapi::experimental::opportunistic_group::get_local_range () const inline
Definition at line 76 of file opportunistic_group.hpp.
References sycl::_V1::ext::oneapi::sub_group_mask::count(), and Mask.
Referenced by get_local_linear_range().
leader()
bool sycl::_V1::ext::oneapi::experimental::opportunistic_group::leader () const inline
Definition at line 121 of file opportunistic_group.hpp.
References sycl::_V1::ext::oneapi::sub_group_mask::find_low(), and Mask.
Friends And Related Function Documentation
sycl::detail::GetMask
sub_group_mask sycl::detail::GetMask (opportunistic_group Group) friend
this_kernel::get_opportunistic_group
opportunistic_group this_kernel::get_opportunistic_group () friend
Member Data Documentation
dimensions
constexpr int sycl::_V1::ext::oneapi::experimental::opportunistic_group::dimensions = 1 static constexpr
Definition at line 45 of file opportunistic_group.hpp.
fence_scope
constexpr sycl::memory_scope sycl::_V1::ext::oneapi::experimental::opportunistic_group::fence_scope static constexpr
Initial value:
=
      sycl::memory_scope::sub_group
Definition at line 46 of file opportunistic_group.hpp.
Mask
sub_group_mask sycl::_V1::ext::oneapi::experimental::opportunistic_group::Mask protected
Definition at line 132 of file opportunistic_group.hpp.
Referenced by get_local_id(), get_local_range(), and leader().
The documentation for this class was generated from the following file:
include/sycl/ext/oneapi/experimental/opportunistic_group.hpp