DPC++ Runtime: sycl::_V1::detail::MemCpyCommand Class Reference
sycl::_V1::detail::MemCpyCommand Class Reference
The mem copy command enqueues memory copy between two instances of memory object.
#include <detail/scheduler/commands.hpp>
Public Member Functions
MemCpyCommand (Requirement SrcReq, AllocaCommandBase *SrcAllocaCmd, Requirement DstReq, AllocaCommandBase *DstAllocaCmd, QueueImplPtr SrcQueue, QueueImplPtr DstQueue)
void printDot (std::ostream &Stream) const final
const Requirement * getRequirement () const final
void emitInstrumentationData () final
Instrumentation method which emits telemetry data.
const ContextImplPtr & getWorkerContext () const final
Get the context of the queue this command will be submitted to.
bool producesPiEvent () const final
Returns true iff the command produces a PI event on non-host devices.
Public Member Functions inherited from sycl::_V1::detail::Command
Command (CommandType Type, QueueImplPtr Queue, sycl::detail::pi::PiExtCommandBuffer CommandBuffer=nullptr, const std::vector< sycl::detail::pi::PiExtSyncPoint > &SyncPoints={})
It is safe to bind MPreparedDepsEvents and MPreparedHostDepsEvents references to event_impl class members because Command should not outlive the event connected to it.
Command * addDep (DepDesc NewDep, std::vector< Command * > &ToCleanUp)
Command * addDep (EventImplPtr Event, std::vector< Command * > &ToCleanUp)
void addUser (Command *NewUser)
CommandType getType () const
virtual bool enqueue (EnqueueResultT &EnqueueResult, BlockingT Blocking, std::vector< Command * > &ToCleanUp)
Checks if the command is enqueued, and calls enqueueImp.
bool isFinished ()
bool isSuccessfullyEnqueued () const
bool isEnqueueBlocked () const
bool isBlocking () const
void addBlockedUserUnique (const EventImplPtr &NewUser)
const QueueImplPtr & getQueue () const
const EventImplPtr & getEvent () const
void emitInstrumentationDataProxy ()
Proxy method which calls emitInstrumentationData.
void resolveReleaseDependencies (std::set< Command * > &list)
Looks at all the dependencies for the release command and enables instrumentation to report these dependencies as edges.
void emitEdgeEventForCommandDependence (Command *Cmd, void *ObjAddr, bool IsCommand, std::optional< access::mode > AccMode=std::nullopt)
Creates an edge event when the dependency is a command.
void emitEdgeEventForEventDependence (Command *Cmd, sycl::detail::pi::PiEvent &EventAddr)
Creates an edge event when the dependency is an event.
void emitEnqueuedEventSignal (sycl::detail::pi::PiEvent &PiEventAddr)
Creates a signal event with the enqueued kernel event handle.
uint64_t makeTraceEventProlog (void *MAddress)
Create a trace event of node_create type; this must be guarded by a check for xptiTraceEnabled().
void makeTraceEventEpilog ()
If prolog has been run, run epilog; this must be guarded by a check for xptiTraceEnabled().
void emitInstrumentation (uint16_t Type, const char *Txt=nullptr)
Emits an event of Type.
virtual ~Command ()
const char * getBlockReason () const
const QueueImplPtr & getWorkerQueue () const
Get the queue this command will be submitted to.
virtual bool supportsPostEnqueueCleanup () const
Returns true iff this command can be freed by post enqueue cleanup.
virtual bool readyForCleanup () const
Returns true iff this command is ready to be submitted for cleanup.
std::vector< sycl::detail::pi::PiEvent > getPiEvents (const std::vector< EventImplPtr > &EventImpls) const
Collect PI events from EventImpls and filter out some of them in case of in order queue.
std::vector< sycl::detail::pi::PiEvent > getPiEventsBlocking (const std::vector< EventImplPtr > &EventImpls) const
Collect PI events from EventImpls and filter out some of them in case of in order queue.
bool isHostTask () const
bool isFusable () const
const std::vector< EventImplPtr > & getPreparedHostDepsEvents () const
const std::vector< EventImplPtr > & getPreparedDepsEvents () const
void copySubmissionCodeLocation ()
void clearAllDependencies ()
Clear all dependency events This should only be used if a command is about to be deleted without being executed before that.
Additional Inherited Members
Public Types inherited from sycl::_V1::detail::Command
enum CommandType {
RUN_CG , COPY_MEMORY , ALLOCA , ALLOCA_SUB_BUF ,
RELEASE , MAP_MEM_OBJ , UNMAP_MEM_OBJ , UPDATE_REQUIREMENT ,
EMPTY_TASK , HOST_TASK , FUSION , EXEC_CMD_BUFFER ,
UPDATE_CMD_BUFFER
}
enum class BlockReason : int { HostAccessor = 0 , HostTask }
Public Attributes inherited from sycl::_V1::detail::Command
std::vector< DepDesc > MDeps
Contains list of dependencies(edges)
std::unordered_set< Command * > MUsers
Contains list of commands that depend on the command.
bool MIsBlockable = false
Indicates whether the command can be blocked from enqueueing.
unsigned MLeafCounter = 0
Counts the number of memory objects this command is a leaf for.
Marks MMarks
Used for marking the node during graph traversal.
BlockReason MBlockReason
std::atomic< EnqueueResultT::ResultT > MEnqueueStatus
Describes the status of the command.
void * MTraceEvent = nullptr
The event for node_create and task_begin.
int32_t MStreamID = -1
The stream under which the traces are emitted.
void * MAddress = nullptr
Reserved for storing the object address such as SPIR-V or memory object address.
std::string MAddressString
Buffer to build the address string.
std::string MCommandNodeType
Buffer to build the command node type.
std::string MCommandName
Buffer to build the command end-user understandable name.
bool MTraceEventPrologComplete = false
Flag to indicate if makeTraceEventProlog() has been run.
bool MFirstInstance = false
Flag to indicate if this is the first time we are seeing this payload.
uint64_t MInstanceID = 0
Instance ID tracked for the command.
code_location MSubmissionCodeLocation
Represents code location of command submission to SYCL API, assigned with the valid value only if command execution is async (host task) or delayed (blocked by host task).
std::string MSubmissionFileName
Introduces string to handle memory management since code_location struct works with raw char arrays.
std::string MSubmissionFunctionName
bool MShouldCompleteEventIfPossible = true
bool MMarkedForCleanup = false
Indicates that the node will be freed by graph cleanup.
std::vector< EventImplPtr > MBlockedUsers
Contains list of commands that depends on the host command explicitly (by depends_on).
std::mutex MBlockedUsersMutex
Protected Member Functions inherited from sycl::_V1::detail::Command
void waitForEvents (QueueImplPtr Queue, std::vector< EventImplPtr > &RawEvents, sycl::detail::pi::PiEvent &Event)
void waitForPreparedHostEvents () const
Command * processDepEvent (EventImplPtr DepEvent, const DepDesc &Dep, std::vector< Command * > &ToCleanUp)
Perform glueing of events from different contexts.
sycl::detail::pi::PiExtCommandBuffer getCommandBuffer () const
Gets the command buffer (if any) associated with this command.
Protected Attributes inherited from sycl::_V1::detail::Command
QueueImplPtr MQueue
EventImplPtr MEvent
QueueImplPtr MWorkerQueue
std::vector< EventImplPtr > & MPreparedDepsEvents
Dependency events prepared for waiting by backend.
std::vector< EventImplPtr > & MPreparedHostDepsEvents
CommandType MType
The type of the command.
std::mutex MEnqueueMtx
Mutex used to protect enqueueing from race conditions.
sycl::detail::pi::PiExtCommandBuffer MCommandBuffer
CommandBuffer which will be used to submit to instead of the queue, if set.
std::vector< sycl::detail::pi::PiExtSyncPoint > MSyncPointDeps
List of sync points for submissions to a command buffer.
Detailed Description
The mem copy command enqueues memory copy between two instances of memory object.
Definition at line 581 of file commands.hpp.
Constructor & Destructor Documentation
MemCpyCommand()
sycl::_V1::detail::MemCpyCommand::MemCpyCommand (Requirement SrcReq, AllocaCommandBase * SrcAllocaCmd, Requirement DstReq, AllocaCommandBase * DstAllocaCmd, QueueImplPtr SrcQueue, QueueImplPtr DstQueue)
Definition at line 1459 of file commands.cpp.
References sycl::_V1::detail::Command::emitInstrumentationDataProxy(), sycl::_V1::detail::Command::MEvent, sycl::_V1::detail::Command::MQueue, and sycl::_V1::detail::Command::MWorkerQueue.
Member Function Documentation
emitInstrumentationData()
void sycl::_V1::detail::MemCpyCommand::emitInstrumentationData () final virtual
Instrumentation method which emits telemetry data.
Implements sycl::_V1::detail::Command.
Definition at line 1478 of file commands.cpp.
References sycl::_V1::detail::deviceToString(), sycl::_V1::detail::AllocaCommandBase::getSYCLMemObj(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::detail::Command::MAddress, sycl::_V1::detail::Command::makeTraceEventEpilog(), sycl::_V1::detail::Command::makeTraceEventProlog(), sycl::_V1::detail::Command::MFirstInstance, sycl::_V1::detail::Command::MQueue, sycl::_V1::detail::Command::MStreamID, and sycl::_V1::detail::Command::MTraceEvent.
getRequirement()
const Requirement* sycl::_V1::detail::MemCpyCommand::getRequirement () const inline final virtual
Reimplemented from sycl::_V1::detail::Command.
Definition at line 588 of file commands.hpp.
getWorkerContext()
const ContextImplPtr & sycl::_V1::detail::MemCpyCommand::getWorkerContext () const final virtual
Get the context of the queue this command will be submitted to.
Could differ from the context of MQueue for memory copy commands.
Reimplemented from sycl::_V1::detail::Command.
Definition at line 1512 of file commands.cpp.
References sycl::_V1::detail::Command::getWorkerQueue().
printDot()
void sycl::_V1::detail::MemCpyCommand::printDot (std::ostream & Stream) const final virtual
Implements sycl::_V1::detail::Command.
Definition at line 1557 of file commands.cpp.
References sycl::_V1::detail::accessModeToString(), sycl::_V1::detail::deviceToString(), sycl::_V1::detail::Command::MDeps, and sycl::_V1::detail::Command::MQueue.
producesPiEvent()
bool sycl::_V1::detail::MemCpyCommand::producesPiEvent () const final virtual
Returns true iff the command produces a PI event on non-host devices.
Reimplemented from sycl::_V1::detail::Command.
Definition at line 1516 of file commands.cpp.
References sycl::_V1::ext_oneapi_level_zero, sycl::_V1::detail::Command::MEvent, and sycl::_V1::detail::Command::MQueue.
The documentation for this class was generated from the following files:
source/detail/scheduler/commands.hpp
source/detail/scheduler/commands.cpp