DPC++ Runtime: sycl::_V1::range< Dimensions > Class Template Reference
sycl::_V1::range< Dimensions > Class Template Reference
DPC++ User API
Defines the iteration domain of either a single work-group in a parallel dispatch, or the overall Dimensions of the dispatch.
#include <sycl/range.hpp>
Public Member Functions
template<int N = Dimensions>
range (typename std::enable_if_t<(N==1), size_t > dim0)
template<int N = Dimensions>
range (typename std::enable_if_t<(N==2), size_t > dim0, size_t dim1)
template<int N = Dimensions>
range (typename std::enable_if_t<(N==3), size_t > dim0, size_t dim1, size_t dim2)
size_t size () const
range (const range< Dimensions > &rhs)=default
range (range< Dimensions > &&rhs)=default
range< Dimensions > & operator= (const range< Dimensions > &rhs)=default
range< Dimensions > & operator= (range< Dimensions > &&rhs)=default
range ()=default
Public Member Functions inherited from sycl::_V1::detail::array< 1 >
array (typename std::enable_if_t<(N==1), size_t > dim0=0)
array (typename std::enable_if_t<(N==2), size_t > dim0, size_t dim1)
array ()
array (typename std::enable_if_t<(N==3), size_t > dim0, size_t dim1, size_t dim2)
array ()
array (const array< dimensions > &rhs)=default
array (array< dimensions > &&rhs)=default
operator sycl::id< dimensions > () const
size_t get (int dimension) const
size_t & operator[] (int dimension)
size_t operator[] (int dimension) const
array< dimensions > & operator= (const array< dimensions > &rhs)=default
array< dimensions > & operator= (array< dimensions > &&rhs)=default
bool operator== (const array< dimensions > &rhs) const
bool operator!= (const array< dimensions > &rhs) const
Static Public Attributes
static constexpr int dimensions = Dimensions
Friends
class handler
class detail::Builder
Additional Inherited Members
Protected Member Functions inherited from sycl::_V1::detail::array< 1 >
__SYCL_ALWAYS_INLINE void check_dimension (int dimension) const
Protected Attributes inherited from sycl::_V1::detail::array< 1 >
size_t common_array [dimensions]
Detailed Description
template<int Dimensions = 1>
class sycl::_V1::range< Dimensions >
Defines the iteration domain of either a single work-group in a parallel dispatch, or the overall Dimensions of the dispatch.
Definition at line 26 of file range.hpp.
Constructor & Destructor Documentation
range() [1/6]
template<int Dimensions = 1> template<int N = Dimensions> sycl::_V1::range< Dimensions >::range (typename std::enable_if_t<(N==1), size_t > dim0) inline
Definition at line 41 of file range.hpp.
range() [2/6]
template<int Dimensions = 1> template<int N = Dimensions> sycl::_V1::range< Dimensions >::range (typename std::enable_if_t<(N==2), size_t > dim0, size_t dim1) inline
Definition at line 46 of file range.hpp.
range() [3/6]
template<int Dimensions = 1> template<int N = Dimensions> sycl::_V1::range< Dimensions >::range (typename std::enable_if_t<(N==3), size_t > dim0, size_t dim1, size_t dim2) inline
Definition at line 52 of file range.hpp.
range() [4/6]
template<int Dimensions = 1> sycl::_V1::range< Dimensions >::range (const range< Dimensions > & rhs) default
range() [5/6]
template<int Dimensions = 1> sycl::_V1::range< Dimensions >::range (range< Dimensions > && rhs) default
range() [6/6]
template<int Dimensions = 1> sycl::_V1::range< Dimensions >::range () default
Member Function Documentation
operator=() [1/2]
template<int Dimensions = 1> range<Dimensions>& sycl::_V1::range< Dimensions >::operator= (const range< Dimensions > & rhs) default
operator=() [2/2]
template<int Dimensions = 1> range<Dimensions>& sycl::_V1::range< Dimensions >::operator= (range< Dimensions > && rhs) default
size()
template<int Dimensions = 1> size_t sycl::_V1::range< Dimensions >::size () const inline
Definition at line 56 of file range.hpp.
References sycl::_V1::Dimensions, and sycl::_V1::detail::array< 1 >::get().
Referenced by syclcompat::compute_nd_range(), syclcompat::device_memory< T, Memory, Dimension >::device_memory(), sycl::_V1::detail::doOverlap(), sycl::_V1::detail::doTreeReduction(), sycl::_V1::detail::MemoryManager::fill(), sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_group_linear_range(), sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_linear_range(), sycl::_V1::ext::oneapi::experimental::radix_sorter< ValT, OrderT, BitsPerPass >::memory_required(), sycl::_V1::detail::reduAuxCGFunc(), sycl::_V1::detail::reduCGFuncImplArrayHelper(), sycl::_V1::detail::reduCGFuncImplScalar(), sycl::_V1::detail::reduCGFuncMulti(), sycl::_V1::detail::reduction_parallel_for(), sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::reinterpret(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::range_basic >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run().
Friends And Related Function Documentation
detail::Builder
template<int Dimensions = 1> friend class detail::Builder friend
Definition at line 220 of file range.hpp.
handler
template<int Dimensions = 1> friend class handler friend
Definition at line 219 of file range.hpp.
Member Data Documentation
dimensions
template<int Dimensions = 1> constexpr int sycl::_V1::range< Dimensions >::dimensions = Dimensions static constexpr
Definition at line 28 of file range.hpp.
The documentation for this class was generated from the following files:
include/sycl/buffer.hpp
include/sycl/range.hpp