DPC++ Runtime: cl::sycl::ext::oneapi::detail::filter_selector_impl Class Reference
cl::sycl::ext::oneapi::detail::filter_selector_impl Class Reference
#include <detail/filter_selector_impl.hpp>
Public Member Functions
filter_selector_impl (const std::string &filter)
int operator() (const device &dev) const
void reset () const
Detailed Description
Definition at line 28 of file filter_selector_impl.hpp.
Constructor & Destructor Documentation
filter_selector_impl()
cl::sycl::ext::oneapi::detail::filter_selector_impl::filter_selector_impl (const std::string & filter)
Definition at line 111 of file filter_selector_impl.cpp.
References cl::sycl::ext::oneapi::detail::create_filter(), cl::sycl::device::get_devices(), and cl::sycl::ext::oneapi::detail::tokenize().
Member Function Documentation
operator()()
int cl::sycl::ext::oneapi::detail::filter_selector_impl::operator() (const device & dev) const
Definition at line 122 of file filter_selector_impl.cpp.
References cl::sycl::all, cl::sycl::info::all, cl::sycl::info::device_type, cl::sycl::device::get_info(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::host, cl::sycl::device::is_host(), and PI_DEVICE_NOT_FOUND.
reset()
void cl::sycl::ext::oneapi::detail::filter_selector_impl::reset () const
Definition at line 178 of file filter_selector_impl.cpp.
The documentation for this class was generated from the following files:
source/detail/filter_selector_impl.hpp
source/detail/filter_selector_impl.cpp