DPC++ Runtime: cl::sycl::detail::DispatchHostTask Class Reference
cl::sycl::detail::DispatchHostTask Class Reference
Public Member Functions
DispatchHostTask (ExecCGCommand *ThisCmd, std::vector< interop_handle::ReqToMem > ReqToMem)
void operator() () const
Detailed Description
Definition at line 190 of file commands.cpp.
Constructor & Destructor Documentation
DispatchHostTask()
cl::sycl::detail::DispatchHostTask::DispatchHostTask (ExecCGCommand * ThisCmd, std::vector< interop_handle::ReqToMem > ReqToMem) inline
Definition at line 234 of file commands.cpp.
Member Function Documentation
operator()()
void cl::sycl::detail::DispatchHostTask::operator() () const inline
Definition at line 238 of file commands.cpp.
References cl::sycl::detail::Scheduler::cleanupCommands(), cl::sycl::detail::ExecCGCommand::getCG(), cl::sycl::detail::CG::getType(), cl::sycl::detail::Command::MDeps, cl::sycl::detail::ExecCGCommand::MEmptyCmd, cl::sycl::detail::Command::MEnqueueStatus, cl::sycl::detail::Command::MEvent, cl::sycl::detail::Scheduler::MGraphLock, PI_SUCCESS, and cl::sycl::detail::waitForEvents().
The documentation for this class was generated from the following file:
source/detail/scheduler/commands.cpp