DPC++ Runtime: syclcompat::pitched_data Class Reference
syclcompat::pitched_data Class Reference
Pitched 2D/3D memory data.
#include <syclcompat/memory.hpp>
Public Member Functions
pitched_data ()
pitched_data (void *data, size_t pitch, size_t x, size_t y)
void * get_data_ptr ()
void set_data_ptr (void *data)
size_t get_pitch ()
void set_pitch (size_t pitch)
size_t get_x ()
void set_x (size_t x)
size_t get_y ()
void set_y (size_t y)
Detailed Description
Pitched 2D/3D memory data.
Definition at line 100 of file memory.hpp.
Constructor & Destructor Documentation
pitched_data() [1/2]
syclcompat::pitched_data::pitched_data () inline
Definition at line 102 of file memory.hpp.
pitched_data() [2/2]
syclcompat::pitched_data::pitched_data (void * data, size_t pitch, size_t x, size_t y) inline
Definition at line 103 of file memory.hpp.
Member Function Documentation
get_data_ptr()
void* syclcompat::pitched_data::get_data_ptr () inline
Definition at line 106 of file memory.hpp.
Referenced by syclcompat::detail::memcpy(), and syclcompat::detail::memset().
get_pitch()
size_t syclcompat::pitched_data::get_pitch () inline
Definition at line 109 of file memory.hpp.
Referenced by syclcompat::detail::memcpy(), and syclcompat::detail::memset().
get_x()
size_t syclcompat::pitched_data::get_x () inline
Definition at line 112 of file memory.hpp.
get_y()
size_t syclcompat::pitched_data::get_y () inline
Definition at line 115 of file memory.hpp.
Referenced by syclcompat::detail::memcpy(), and syclcompat::detail::memset().
set_data_ptr()
void syclcompat::pitched_data::set_data_ptr (void * data) inline
Definition at line 107 of file memory.hpp.
Referenced by syclcompat::malloc().
set_pitch()
void syclcompat::pitched_data::set_pitch (size_t pitch) inline
Definition at line 110 of file memory.hpp.
Referenced by syclcompat::malloc().
set_x()
void syclcompat::pitched_data::set_x (size_t x) inline
Definition at line 113 of file memory.hpp.
set_y()
void syclcompat::pitched_data::set_y (size_t y) inline
Definition at line 116 of file memory.hpp.
The documentation for this class was generated from the following file:
include/syclcompat/memory.hpp