DPC++ Runtime: cl::sycl::detail::pi::DeviceBinaryProperty Class Reference
cl::sycl::detail::pi::DeviceBinaryProperty Class Reference
#include <CL/sycl/detail/pi.hpp>
Public Member Functions
DeviceBinaryProperty (const _pi_device_binary_property_struct *Prop)
pi_uint32 asUint32 () const
ByteArray asByteArray () const
const char * asCString () const
Protected Attributes
const _pi_device_binary_property_struct * Prop
Friends
std::ostream & operator<< (std::ostream &Out, const DeviceBinaryProperty &P)
Detailed Description
Definition at line 227 of file pi.hpp.
Constructor & Destructor Documentation
DeviceBinaryProperty()
cl::sycl::detail::pi::DeviceBinaryProperty::DeviceBinaryProperty (const _pi_device_binary_property_struct * Prop) inline
Definition at line 229 of file pi.hpp.
Member Function Documentation
asByteArray()
ByteArray cl::sycl::detail::pi::DeviceBinaryProperty::asByteArray () const
Definition at line 640 of file pi.cpp.
References PI_PROPERTY_TYPE_BYTE_ARRAY.
Referenced by cl::sycl::detail::ProgramManager::addImages(), cl::sycl::detail::program_impl::flush_spec_constants(), and cl::sycl::detail::pi::operator<<().
asCString()
const char * cl::sycl::detail::pi::DeviceBinaryProperty::asCString () const
Definition at line 647 of file pi.cpp.
References PI_PROPERTY_TYPE_STRING.
Referenced by cl::sycl::detail::pi::operator<<().
asUint32()
pi_uint32 cl::sycl::detail::pi::DeviceBinaryProperty::asUint32 () const
Definition at line 633 of file pi.cpp.
References cl::sycl::detail::pi::asUint32(), and PI_PROPERTY_TYPE_UINT32.
Referenced by cl::sycl::detail::ProgramManager::getDeviceLibReqMask(), and cl::sycl::detail::pi::operator<<().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & Out, const DeviceBinaryProperty & P) friend
Definition at line 547 of file pi.cpp.
Member Data Documentation
Prop
const _pi_device_binary_property_struct* cl::sycl::detail::pi::DeviceBinaryProperty::Prop protected
Definition at line 239 of file pi.hpp.
Referenced by cl::sycl::detail::pi::operator<<().
The documentation for this class was generated from the following files:
include/CL/sycl/detail/pi.hpp
source/detail/pi.cpp