DPC++ Runtime: sycl::_V1::detail::sampler_impl Class Reference
sycl::_V1::detail::sampler_impl Class Reference
#include <detail/sampler_impl.hpp>
Public Member Functions
sampler_impl (coordinate_normalization_mode normalizationMode, addressing_mode addressingMode, filtering_mode filteringMode, const property_list &propList)
sampler_impl (cl_sampler clSampler, const context &syclContext)
addressing_mode get_addressing_mode () const
filtering_mode get_filtering_mode () const
coordinate_normalization_mode get_coordinate_normalization_mode () const
sycl::detail::pi::PiSampler getOrCreateSampler (const context &Context)
template<typename propertyT >
bool has_property () const noexcept
Checks if this sampler_impl has a property of type propertyT.
template<typename propertyT >
propertyT get_property () const
Gets the specified property of this sampler_impl.
~sampler_impl ()
Detailed Description
Definition at line 28 of file sampler_impl.hpp.
Constructor & Destructor Documentation
sampler_impl() [1/2]
sycl::_V1::detail::sampler_impl::sampler_impl (coordinate_normalization_mode normalizationMode, addressing_mode addressingMode, filtering_mode filteringMode, const property_list & propList)
Definition at line 17 of file sampler_impl.cpp.
sampler_impl() [2/2]
sycl::_V1::detail::sampler_impl::sampler_impl (cl_sampler clSampler, const context & syclContext)
Definition at line 24 of file sampler_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), PI_SAMPLER_INFO_ADDRESSING_MODE, PI_SAMPLER_INFO_FILTER_MODE, PI_SAMPLER_INFO_NORMALIZED_COORDS, piSamplerGetInfo(), and piSamplerRetain().
~sampler_impl()
sycl::_V1::detail::sampler_impl::~sampler_impl ()
Definition at line 42 of file sampler_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and piSamplerRelease().
Member Function Documentation
get_addressing_mode()
addressing_mode sycl::_V1::detail::sampler_impl::get_addressing_mode () const
Definition at line 87 of file sampler_impl.cpp.
get_coordinate_normalization_mode()
coordinate_normalization_mode sycl::_V1::detail::sampler_impl::get_coordinate_normalization_mode () const
Definition at line 92 of file sampler_impl.cpp.
get_filtering_mode()
filtering_mode sycl::_V1::detail::sampler_impl::get_filtering_mode () const
Definition at line 89 of file sampler_impl.cpp.
get_property()
template<typename propertyT > propertyT sycl::_V1::detail::sampler_impl::get_property () const inline
Gets the specified property of this sampler_impl.
Throws invalid_object_error if this sampler_impl does not have a property of type propertyT.
Returns
a copy of the property of type propertyT.
Definition at line 57 of file sampler_impl.hpp.
getOrCreateSampler()
sycl::detail::pi::PiSampler sycl::_V1::detail::sampler_impl::getOrCreateSampler (const context & Context)
Definition at line 52 of file sampler_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), PI_SAMPLER_INFO_ADDRESSING_MODE, PI_SAMPLER_INFO_FILTER_MODE, PI_SAMPLER_INFO_NORMALIZED_COORDS, and piSamplerCreate().
has_property()
template<typename propertyT > bool sycl::_V1::detail::sampler_impl::has_property () const inline noexcept
Checks if this sampler_impl has a property of type propertyT.
Returns
true if this sampler_impl has a property of type propertyT.
Definition at line 47 of file sampler_impl.hpp.
The documentation for this class was generated from the following files:
source/detail/sampler_impl.hpp
source/detail/sampler_impl.cpp