DPC++ Runtime: cl::sycl::detail::KernelProgramCache Class Reference
cl::sycl::detail::KernelProgramCache Class Reference
#include <detail/kernel_program_cache.hpp>
Classes
struct BuildError
Denotes build error data.
struct BuildResult
Denotes pointer to some entity with its general state and build error.
Public Types
using PiProgramT = std::remove_pointer< RT::PiProgram >::type
using PiProgramPtrT = std::atomic< PiProgramT * >
using ProgramWithBuildStateT = BuildResult< PiProgramT >
using ProgramCacheKeyT = std::pair< std::pair< SerializedObj, KernelSetId >, std::pair< RT::PiDevice, std::string > >
using ProgramCacheT = std::map< ProgramCacheKeyT, ProgramWithBuildStateT >
using ContextPtr = context_impl *
using PiKernelT = std::remove_pointer< RT::PiKernel >::type
using PiKernelPtrT = std::atomic< PiKernelT * >
using KernelWithBuildStateT = BuildResult< PiKernelT >
using KernelByNameT = std::map< std::string, KernelWithBuildStateT >
using KernelCacheT = std::map< RT::PiProgram, KernelByNameT >
using KernelFastCacheKeyT = std::tuple< SerializedObj, OSModuleHandle, RT::PiDevice, std::string, std::string >
using KernelFastCacheValT = std::tuple< RT::PiKernel, std::mutex *, RT::PiProgram >
using KernelFastCacheT = std::map< KernelFastCacheKeyT, KernelFastCacheValT >
Public Member Functions
~KernelProgramCache ()
void setContextPtr (const ContextPtr &AContext)
Locked< ProgramCacheT > acquireCachedPrograms ()
Locked< KernelCacheT > acquireKernelsPerProgramCache ()
template<typename T , class Predicate >
void waitUntilBuilt (BuildResult< T > &BR, Predicate Pred) const
template<typename T >
void notifyAllBuild (BuildResult< T > &BR) const
template<typename KeyT >
KernelFastCacheValT tryToGetKernelFast (KeyT &&CacheKey)
template<typename KeyT , typename ValT >
void saveKernel (KeyT &&CacheKey, ValT &&CacheVal)
void reset ()
Clears cache state.
Friends
class ::MockKernelProgramCache
Detailed Description
Definition at line 31 of file kernel_program_cache.hpp.
Member Typedef Documentation
ContextPtr
using cl::sycl::detail::KernelProgramCache::ContextPtr = context_impl *
Definition at line 76 of file kernel_program_cache.hpp.
KernelByNameT
using cl::sycl::detail::KernelProgramCache::KernelByNameT = std::map<std::string, KernelWithBuildStateT>
Definition at line 82 of file kernel_program_cache.hpp.
KernelCacheT
using cl::sycl::detail::KernelProgramCache::KernelCacheT = std::map<RT::PiProgram, KernelByNameT>
Definition at line 83 of file kernel_program_cache.hpp.
KernelFastCacheKeyT
using cl::sycl::detail::KernelProgramCache::KernelFastCacheKeyT = std::tuple<SerializedObj, OSModuleHandle, RT::PiDevice, std::string, std::string>
Definition at line 87 of file kernel_program_cache.hpp.
KernelFastCacheT
using cl::sycl::detail::KernelProgramCache::KernelFastCacheT = std::map<KernelFastCacheKeyT, KernelFastCacheValT>
Definition at line 90 of file kernel_program_cache.hpp.
KernelFastCacheValT
using cl::sycl::detail::KernelProgramCache::KernelFastCacheValT = std::tuple<RT::PiKernel, std::mutex *, RT::PiProgram>
Definition at line 89 of file kernel_program_cache.hpp.
KernelWithBuildStateT
using cl::sycl::detail::KernelProgramCache::KernelWithBuildStateT = BuildResult<PiKernelT>
Definition at line 81 of file kernel_program_cache.hpp.
PiKernelPtrT
using cl::sycl::detail::KernelProgramCache::PiKernelPtrT = std::atomic<PiKernelT *>
Definition at line 80 of file kernel_program_cache.hpp.
PiKernelT
using cl::sycl::detail::KernelProgramCache::PiKernelT = std::remove_pointer<RT::PiKernel>::type
Definition at line 78 of file kernel_program_cache.hpp.
PiProgramPtrT
using cl::sycl::detail::KernelProgramCache::PiProgramPtrT = std::atomic<PiProgramT *>
Definition at line 71 of file kernel_program_cache.hpp.
PiProgramT
using cl::sycl::detail::KernelProgramCache::PiProgramT = std::remove_pointer<RT::PiProgram>::type
Definition at line 70 of file kernel_program_cache.hpp.
ProgramCacheKeyT
using cl::sycl::detail::KernelProgramCache::ProgramCacheKeyT = std::pair<std::pair<SerializedObj, KernelSetId>, std::pair<RT::PiDevice, std::string> >
Definition at line 74 of file kernel_program_cache.hpp.
ProgramCacheT
using cl::sycl::detail::KernelProgramCache::ProgramCacheT = std::map<ProgramCacheKeyT, ProgramWithBuildStateT>
Definition at line 75 of file kernel_program_cache.hpp.
ProgramWithBuildStateT
using cl::sycl::detail::KernelProgramCache::ProgramWithBuildStateT = BuildResult<PiProgramT>
Definition at line 72 of file kernel_program_cache.hpp.
Constructor & Destructor Documentation
~KernelProgramCache()
cl::sycl::detail::KernelProgramCache::~KernelProgramCache ()
Definition at line 16 of file kernel_program_cache.cpp.
References cl::sycl::detail::plugin::call(), piKernelRelease(), piProgramRelease(), and cl::sycl::detail::KernelProgramCache::BuildResult< T >::Ptr.
Member Function Documentation
acquireCachedPrograms()
Locked<ProgramCacheT> cl::sycl::detail::KernelProgramCache::acquireCachedPrograms () inline
Definition at line 96 of file kernel_program_cache.hpp.
Referenced by cl::sycl::detail::ProgramManager::build(), and cl::sycl::detail::ProgramManager::getBuiltPIProgram().
acquireKernelsPerProgramCache()
Locked<KernelCacheT> cl::sycl::detail::KernelProgramCache::acquireKernelsPerProgramCache () inline
Definition at line 100 of file kernel_program_cache.hpp.
Referenced by cl::sycl::detail::ProgramManager::getOrCreateKernel().
notifyAllBuild()
template<typename T > void cl::sycl::detail::KernelProgramCache::notifyAllBuild (BuildResult< T > & BR) const inline
Definition at line 111 of file kernel_program_cache.hpp.
Referenced by cl::sycl::detail::getOrBuild().
reset()
void cl::sycl::detail::KernelProgramCache::reset () inline
Clears cache state.
This member function should only be used in unit tests.
Definition at line 136 of file kernel_program_cache.hpp.
saveKernel()
template<typename KeyT , typename ValT > void cl::sycl::detail::KernelProgramCache::saveKernel (KeyT && CacheKey, ValT && CacheVal) inline
Definition at line 126 of file kernel_program_cache.hpp.
Referenced by cl::sycl::detail::ProgramManager::getOrCreateKernel().
setContextPtr()
void cl::sycl::detail::KernelProgramCache::setContextPtr (const ContextPtr & AContext) inline
Definition at line 94 of file kernel_program_cache.hpp.
Referenced by cl::sycl::detail::context_impl::context_impl().
tryToGetKernelFast()
template<typename KeyT > KernelFastCacheValT cl::sycl::detail::KernelProgramCache::tryToGetKernelFast (KeyT && CacheKey) inline
Definition at line 116 of file kernel_program_cache.hpp.
References cl::sycl::detail::make_tuple().
Referenced by cl::sycl::detail::ProgramManager::getOrCreateKernel().
waitUntilBuilt()
template<typename T , class Predicate > void cl::sycl::detail::KernelProgramCache::waitUntilBuilt (BuildResult< T > & BR, Predicate Pred) const inline
Definition at line 105 of file kernel_program_cache.hpp.
Referenced by cl::sycl::detail::waitUntilBuilt().
Friends And Related Function Documentation
::MockKernelProgramCache
friend class ::MockKernelProgramCache friend
Definition at line 152 of file kernel_program_cache.hpp.
The documentation for this class was generated from the following files:
source/detail/kernel_program_cache.hpp
source/detail/kernel_program_cache.cpp