DPC++ Runtime: cl::sycl::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, std::enable_if_t< std::is_same_v< _propertiesT, decltype(oneapi::experimental::properties{})> > > Class Template Reference
cl::sycl::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, std::enable_if_t< std::is_same_v< _propertiesT, decltype(oneapi::experimental::properties{})> > > Class Template Reference
#include <sycl/ext/intel/experimental/pipes.hpp>
Static Public Member Functions
template<class... _Params>
static _dataT read (bool &_Success)
template<class... _Params>
static void write (const _dataT &_Data, bool &_Success)
template<class... _Params>
static _dataT read ()
template<class... _Params>
static void write (const _dataT &_Data)
Detailed Description
template<class _name, class _dataT, int32_t _min_capacity, class _propertiesT>
class cl::sycl::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, std::enable_if_t< std::is_same_v< _propertiesT, decltype(oneapi::experimental::properties{})> > >
Definition at line 34 of file pipes.hpp.
Member Function Documentation
read() [1/2]
template<class _name , class _dataT , int32_t _min_capacity, class _propertiesT > template<class... _Params> static _dataT cl::sycl::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, std::enable_if_t< std::is_same_v< _propertiesT, decltype(oneapi::experimental::properties{})> > >::read () inline static
Definition at line 110 of file pipes.hpp.
References max(), and min().
read() [2/2]
template<class _name , class _dataT , int32_t _min_capacity, class _propertiesT > template<class... _Params> static _dataT cl::sycl::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, std::enable_if_t< std::is_same_v< _propertiesT, decltype(oneapi::experimental::properties{})> > >::read (bool & _Success) inline static
Definition at line 41 of file pipes.hpp.
References max(), and min().
write() [1/2]
template<class _name , class _dataT , int32_t _min_capacity, class _propertiesT > template<class... _Params> static void cl::sycl::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, std::enable_if_t< std::is_same_v< _propertiesT, decltype(oneapi::experimental::properties{})> > >::write (const _dataT & _Data) inline static
Definition at line 143 of file pipes.hpp.
References max(), and min().
write() [2/2]
template<class _name , class _dataT , int32_t _min_capacity, class _propertiesT > template<class... _Params> static void cl::sycl::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, std::enable_if_t< std::is_same_v< _propertiesT, decltype(oneapi::experimental::properties{})> > >::write (const _dataT & _Data, bool & _Success) inline static
Definition at line 76 of file pipes.hpp.
References max(), and min().
The documentation for this class was generated from the following file:
include/sycl/ext/intel/experimental/pipes.hpp