DPC++ Runtime: cl::sycl::detail::SYCLConfig< Config > Class Template Reference
cl::sycl::detail::SYCLConfig< Config > Class Template Reference
#include <detail/config.hpp>
Static Public Member Functions
static const char * get ()
static void reset ()
static const char * getName ()
Detailed Description
template<ConfigID Config>
class cl::sycl::detail::SYCLConfig< Config >
Definition at line 105 of file config.hpp.
Member Function Documentation
get()
template<ConfigID Config> static const char* cl::sycl::detail::SYCLConfig< Config >::get () inline static
Definition at line 109 of file config.hpp.
Referenced by cl::sycl::device::get_devices(), cl::sycl::detail::program_impl::link(), and cl::sycl::detail::parsePersistentCacheConfig().
getName()
template<ConfigID Config> static const char* cl::sycl::detail::SYCLConfig< Config >::getName () inline static
Definition at line 113 of file config.hpp.
Referenced by cl::sycl::detail::parsePersistentCacheConfig().
reset()
template<ConfigID Config> static void cl::sycl::detail::SYCLConfig< Config >::reset () inline static
Definition at line 111 of file config.hpp.
The documentation for this class was generated from the following file:
source/detail/config.hpp