DPC++ Runtime: cl::sycl::stream Class Reference
cl::sycl::stream Class Reference
DPC++ User API
A buffered output stream that allows outputting the values of built-in, vector and SYCL types to the console.
#include <CL/sycl/stream.hpp>
Public Member Functions
stream (size_t BufferSize, size_t MaxStatementSize, handler &CGH)
stream (size_t BufferSize, size_t MaxStatementSize, handler &CGH, const property_list &PropList)
size_t get_size () const
size_t get_max_statement_size () const
size_t get_precision () const
size_t get_width () const
stream_manipulator get_stream_mode () const
bool operator== (const stream &RHS) const
bool operator!= (const stream &LHS) const
template<typename propertyT >
bool has_property () const noexcept
template<typename propertyT >
propertyT get_property () const
Friends
class handler
const friend stream & operator<< (const stream &, const char)
const friend stream & operator<< (const stream &, const char *)
template<typename ValueType >
detail::enable_if_t< std::is_integral< ValueType >::value, const stream & > operator<< (const stream &, const ValueType &)
const friend stream & operator<< (const stream &, const float &)
const friend stream & operator<< (const stream &, const double &)
const friend stream & operator<< (const stream &, const half &)
const friend stream & operator<< (const stream &, const stream_manipulator)
const friend stream & operator<< (const stream &Out, const __precision_manipulator__ &RHS)
const friend stream & operator<< (const stream &Out, const __width_manipulator__ &RHS)
template<typename T , int Dimensions>
const friend stream & operator<< (const stream &Out, const vec< T, Dimensions > &RHS)
template<typename T >
const friend stream & operator<< (const stream &Out, const T *RHS)
template<int Dimensions>
const friend stream & operator<< (const stream &Out, const id< Dimensions > &RHS)
template<int Dimensions>
const friend stream & operator<< (const stream &Out, const range< Dimensions > &RHS)
template<int Dimensions>
const friend stream & operator<< (const stream &Out, const item< Dimensions > &RHS)
template<int Dimensions>
const friend stream & operator<< (const stream &Out, const nd_range< Dimensions > &RHS)
template<int Dimensions>
const friend stream & operator<< (const stream &Out, const nd_item< Dimensions > &RHS)
template<int Dimensions>
const friend stream & operator<< (const stream &Out, const group< Dimensions > &RHS)
template<int Dimensions>
const friend stream & operator<< (const stream &Out, const h_item< Dimensions > &RHS)
Detailed Description
A buffered output stream that allows outputting the values of built-in, vector and SYCL types to the console.
Definition at line 743 of file stream.hpp.
Constructor & Destructor Documentation
stream() [1/2]
cl::sycl::stream::stream (size_t BufferSize, size_t MaxStatementSize, handler & CGH)
Definition at line 35 of file stream.cpp.
stream() [2/2]
cl::sycl::stream::stream (size_t BufferSize, size_t MaxStatementSize, handler & CGH, const property_list & PropList)
Definition at line 38 of file stream.cpp.
References cl::sycl::detail::getSyclObjImpl().
Member Function Documentation
get_max_statement_size()
size_t cl::sycl::stream::get_max_statement_size () const
Definition at line 59 of file stream.cpp.
get_precision()
size_t cl::sycl::stream::get_precision () const inline
Definition at line 762 of file stream.hpp.
Referenced by cl::sycl::operator<<().
get_property()
template<typename propertyT > propertyT cl::sycl::stream::get_property () const
get_size()
size_t cl::sycl::stream::get_size () const
Definition at line 57 of file stream.cpp.
get_stream_mode()
stream_manipulator cl::sycl::stream::get_stream_mode () const inline
Definition at line 766 of file stream.hpp.
get_width()
size_t cl::sycl::stream::get_width () const inline
Definition at line 764 of file stream.hpp.
Referenced by cl::sycl::operator<<().
has_property()
template<typename propertyT > bool cl::sycl::stream::has_property () const noexcept
operator!=()
bool cl::sycl::stream::operator!= (const stream & LHS) const
Definition at line 65 of file stream.cpp.
operator==()
bool cl::sycl::stream::operator== (const stream & RHS) const
Definition at line 63 of file stream.cpp.
Friends And Related Function Documentation
handler
friend class handler friend
Definition at line 919 of file stream.hpp.
operator<< [1/18]
const friend stream& operator<< (const stream & Out, const char * Str) friend
Definition at line 988 of file stream.hpp.
operator<< [2/18]
const friend stream& operator<< (const stream & Out, const char C) friend
Definition at line 982 of file stream.hpp.
operator<< [3/18]
const friend stream& operator<< (const stream & Out, const double & RHS) friend
Definition at line 1023 of file stream.hpp.
operator<< [4/18]
const friend stream& operator<< (const stream & Out, const float & RHS) friend
Definition at line 1016 of file stream.hpp.
operator<< [5/18]
const friend stream& operator<< (const stream & Out, const half & RHS) friend
Definition at line 1030 of file stream.hpp.
operator<< [6/18]
const friend stream& operator<< (const stream & Out, const stream_manipulator RHS) friend
Definition at line 1070 of file stream.hpp.
operator<< [7/18]
template<typename ValueType > detail::enable_if_t<std::is_integral<ValueType>::value, const stream &> operator<< (const stream & Out, const ValueType & RHS) friend
Definition at line 1008 of file stream.hpp.
operator<< [8/18]
const friend stream& operator<< (const stream & Out, const __precision_manipulator__ & RHS) friend
Definition at line 1058 of file stream.hpp.
operator<< [9/18]
const friend stream& operator<< (const stream & Out, const __width_manipulator__ & RHS) friend
Definition at line 1064 of file stream.hpp.
operator<< [10/18]
template<int Dimensions> const friend stream& operator<< (const stream & Out, const group< Dimensions > & RHS) friend
Definition at line 1141 of file stream.hpp.
operator<< [11/18]
template<int Dimensions> const friend stream& operator<< (const stream & Out, const h_item< Dimensions > & RHS) friend
Definition at line 1149 of file stream.hpp.
operator<< [12/18]
template<int Dimensions> const friend stream& operator<< (const stream & Out, const id< Dimensions > & RHS) friend
Definition at line 1102 of file stream.hpp.
operator<< [13/18]
template<int Dimensions> const friend stream& operator<< (const stream & Out, const item< Dimensions > & RHS) friend
Definition at line 1117 of file stream.hpp.
operator<< [14/18]
template<int Dimensions> const friend stream& operator<< (const stream & Out, const nd_item< Dimensions > & RHS) friend
Definition at line 1133 of file stream.hpp.
operator<< [15/18]
template<int Dimensions> const friend stream& operator<< (const stream & Out, const nd_range< Dimensions > & RHS) friend
Definition at line 1125 of file stream.hpp.
operator<< [16/18]
template<int Dimensions> const friend stream& operator<< (const stream & Out, const range< Dimensions > & RHS) friend
Definition at line 1109 of file stream.hpp.
operator<< [17/18]
template<typename T > const friend stream& operator<< (const stream & Out, const T * RHS) friend
Definition at line 1047 of file stream.hpp.
operator<< [18/18]
template<typename T , int Dimensions> const friend stream& operator<< (const stream & Out, const vec< T, Dimensions > & RHS) friend
The documentation for this class was generated from the following files:
include/CL/sycl/stream.hpp
source/stream.cpp