DPC++ Runtime: USMAllocContext::USMAllocImpl Class Reference
USMAllocContext::USMAllocImpl Class Reference
Public Member Functions
USMAllocImpl (std::unique_ptr< SystemMemory > SystemMemHandle)
void * allocate (size_t Size, size_t Alignment, bool &FromPool)
void * allocate (size_t Size, bool &FromPool)
void deallocate (void *Ptr, bool &ToPool)
SystemMemory & getMemHandle ()
std::shared_timed_mutex & getKnownSlabsMapLock ()
std::unordered_multimap< void *, Slab & > & getKnownSlabs ()
size_t SlabMinSize ()
void printStats ()
Detailed Description
Definition at line 492 of file usm_allocator.cpp.
Constructor & Destructor Documentation
USMAllocImpl()
USMAllocContext::USMAllocImpl::USMAllocImpl (std::unique_ptr< SystemMemory > SystemMemHandle) inline
Definition at line 505 of file usm_allocator.cpp.
Member Function Documentation
allocate() [1/2]
void * USMAllocContext::USMAllocImpl::allocate (size_t Size, bool & FromPool)
Definition at line 867 of file usm_allocator.cpp.
References SystemMemory::allocate(), Bucket::ChunkCutOff(), Bucket::countAlloc(), Bucket::getChunk(), getMemHandle(), Bucket::getSlab(), settings::SetLimits::MaxPoolableSize, settings::SetLimits::PoolTrace, and settings::USMSettings.
allocate() [2/2]
void * USMAllocContext::USMAllocImpl::allocate (size_t Size, size_t Alignment, bool & FromPool)
Definition at line 891 of file usm_allocator.cpp.
References AlignPtrUp(), AlignUp(), USMAllocContext::allocate(), Bucket::ChunkCutOff(), Bucket::countAlloc(), Bucket::getChunk(), Bucket::getSlab(), settings::SetLimits::MaxPoolableSize, settings::SetLimits::PoolTrace, and settings::USMSettings.
deallocate()
void USMAllocContext::USMAllocImpl::deallocate (void * Ptr, bool & ToPool)
Definition at line 936 of file usm_allocator.cpp.
References AlignPtrDown(), Bucket::ChunkCutOff(), Bucket::countFree(), Bucket::freeChunk(), Bucket::freeSlab(), Slab::getBucket(), Slab::getEnd(), Slab::getPtr(), Bucket::getSize(), settings::SetLimits::PoolTrace, and settings::USMSettings.
getKnownSlabs()
std::unordered_multimap<void *, Slab &>& USMAllocContext::USMAllocImpl::getKnownSlabs () inline
Definition at line 526 of file usm_allocator.cpp.
getKnownSlabsMapLock()
std::shared_timed_mutex& USMAllocContext::USMAllocImpl::getKnownSlabsMapLock () inline
Definition at line 525 of file usm_allocator.cpp.
getMemHandle()
SystemMemory& USMAllocContext::USMAllocImpl::getMemHandle () inline
Definition at line 523 of file usm_allocator.cpp.
Referenced by allocate(), and Bucket::getMemHandle().
printStats()
void USMAllocContext::USMAllocImpl::printStats ()
Definition at line 1039 of file usm_allocator.cpp.
References cl::sycl::setw().
SlabMinSize()
size_t USMAllocContext::USMAllocImpl::SlabMinSize () inline
Definition at line 530 of file usm_allocator.cpp.
References settings::SetLimits::SlabMinSize, and settings::USMSettings.
The documentation for this class was generated from the following file:
plugins/level_zero/usm_allocator.cpp