DPC++ Runtime: cl::sycl::h_item< dimensions > Class Template Reference
cl::sycl::h_item< dimensions > Class Template Reference
DPC++ User API
Identifies an instance of a group::parallel_for_work_item function object executing at each point in a local range passed to a parallel_for_work_item call or to the corresponding parallel_for_work_group call.
#include <CL/sycl/detail/helpers.hpp>
Public Member Functions
h_item ()=delete
h_item (const h_item &hi)=default
h_item & operator= (const h_item &hi)=default
item< dimensions, false > get_global () const
item< dimensions, false > get_local () const
item< dimensions, false > get_logical_local () const
item< dimensions, false > get_physical_local () const
range< dimensions > get_global_range () const
size_t get_global_range (int dimension) const
id< dimensions > get_global_id () const
size_t get_global_id (int dimension) const
range< dimensions > get_local_range () const
size_t get_local_range (int dimension) const
id< dimensions > get_local_id () const
size_t get_local_id (int dimension) const
range< dimensions > get_logical_local_range () const
size_t get_logical_local_range (int dimension) const
id< dimensions > get_logical_local_id () const
size_t get_logical_local_id (int dimension) const
range< dimensions > get_physical_local_range () const
size_t get_physical_local_range (int dimension) const
id< dimensions > get_physical_local_id () const
size_t get_physical_local_id (int dimension) const
bool operator== (const h_item &rhs) const
bool operator!= (const h_item &rhs) const
Protected Member Functions
h_item (const item< dimensions, false > &GL, const item< dimensions, false > &L, const range< dimensions > &flexLocalRange)
h_item (const item< dimensions, false > &GL, const item< dimensions, false > &L)
void setLogicalLocalID (const id< dimensions > &ID)
Friends
class detail::Builder
class group< dimensions >
Detailed Description
template<int dimensions>
class cl::sycl::h_item< dimensions >
Identifies an instance of a group::parallel_for_work_item function object executing at each point in a local range passed to a parallel_for_work_item call or to the corresponding parallel_for_work_group call.
Definition at line 33 of file helpers.hpp.
Constructor & Destructor Documentation
h_item() [1/4]
template<int dimensions> cl::sycl::h_item< dimensions >::h_item () delete
h_item() [2/4]
template<int dimensions> cl::sycl::h_item< dimensions >::h_item (const h_item< dimensions > & hi) default
h_item() [3/4]
template<int dimensions> cl::sycl::h_item< dimensions >::h_item (const item< dimensions, false > & GL, const item< dimensions, false > & L, const range< dimensions > & flexLocalRange) inline protected
Definition at line 113 of file h_item.hpp.
h_item() [4/4]
template<int dimensions> cl::sycl::h_item< dimensions >::h_item (const item< dimensions, false > & GL, const item< dimensions, false > & L) inline protected
Definition at line 119 of file h_item.hpp.
Member Function Documentation
get_global()
template<int dimensions> item<dimensions, false> cl::sycl::h_item< dimensions >::get_global () const inline
Definition at line 37 of file h_item.hpp.
Referenced by cl::sycl::detail::writeHItem().
get_global_id() [1/2]
template<int dimensions> id<dimensions> cl::sycl::h_item< dimensions >::get_global_id () const inline
Definition at line 53 of file h_item.hpp.
get_global_id() [2/2]
template<int dimensions> size_t cl::sycl::h_item< dimensions >::get_global_id (int dimension) const inline
Definition at line 55 of file h_item.hpp.
get_global_range() [1/2]
template<int dimensions> range<dimensions> cl::sycl::h_item< dimensions >::get_global_range () const inline
Definition at line 45 of file h_item.hpp.
get_global_range() [2/2]
template<int dimensions> size_t cl::sycl::h_item< dimensions >::get_global_range (int dimension) const inline
Definition at line 49 of file h_item.hpp.
get_local()
template<int dimensions> item<dimensions, false> cl::sycl::h_item< dimensions >::get_local () const inline
Definition at line 39 of file h_item.hpp.
get_local_id() [1/2]
template<int dimensions> id<dimensions> cl::sycl::h_item< dimensions >::get_local_id () const inline
Definition at line 65 of file h_item.hpp.
get_local_id() [2/2]
template<int dimensions> size_t cl::sycl::h_item< dimensions >::get_local_id (int dimension) const inline
Definition at line 67 of file h_item.hpp.
get_local_range() [1/2]
template<int dimensions> range<dimensions> cl::sycl::h_item< dimensions >::get_local_range () const inline
Definition at line 59 of file h_item.hpp.
get_local_range() [2/2]
template<int dimensions> size_t cl::sycl::h_item< dimensions >::get_local_range (int dimension) const inline
Definition at line 61 of file h_item.hpp.
get_logical_local()
template<int dimensions> item<dimensions, false> cl::sycl::h_item< dimensions >::get_logical_local () const inline
Definition at line 41 of file h_item.hpp.
Referenced by cl::sycl::detail::writeHItem().
get_logical_local_id() [1/2]
template<int dimensions> id<dimensions> cl::sycl::h_item< dimensions >::get_logical_local_id () const inline
Definition at line 79 of file h_item.hpp.
get_logical_local_id() [2/2]
template<int dimensions> size_t cl::sycl::h_item< dimensions >::get_logical_local_id (int dimension) const inline
Definition at line 83 of file h_item.hpp.
get_logical_local_range() [1/2]
template<int dimensions> range<dimensions> cl::sycl::h_item< dimensions >::get_logical_local_range () const inline
Definition at line 71 of file h_item.hpp.
get_logical_local_range() [2/2]
template<int dimensions> size_t cl::sycl::h_item< dimensions >::get_logical_local_range (int dimension) const inline
Definition at line 75 of file h_item.hpp.
get_physical_local()
template<int dimensions> item<dimensions, false> cl::sycl::h_item< dimensions >::get_physical_local () const inline
Definition at line 43 of file h_item.hpp.
Referenced by cl::sycl::private_memory< T, Dimensions >::operator()(), and cl::sycl::detail::writeHItem().
get_physical_local_id() [1/2]
template<int dimensions> id<dimensions> cl::sycl::h_item< dimensions >::get_physical_local_id () const inline
Definition at line 95 of file h_item.hpp.
get_physical_local_id() [2/2]
template<int dimensions> size_t cl::sycl::h_item< dimensions >::get_physical_local_id (int dimension) const inline
Definition at line 99 of file h_item.hpp.
get_physical_local_range() [1/2]
template<int dimensions> range<dimensions> cl::sycl::h_item< dimensions >::get_physical_local_range () const inline
Definition at line 87 of file h_item.hpp.
get_physical_local_range() [2/2]
template<int dimensions> size_t cl::sycl::h_item< dimensions >::get_physical_local_range (int dimension) const inline
Definition at line 91 of file h_item.hpp.
operator!=()
template<int dimensions> bool cl::sycl::h_item< dimensions >::operator!= (const h_item< dimensions > & rhs) const inline
Definition at line 108 of file h_item.hpp.
operator=()
template<int dimensions> h_item& cl::sycl::h_item< dimensions >::operator= (const h_item< dimensions > & hi) default
operator==()
template<int dimensions> bool cl::sycl::h_item< dimensions >::operator== (const h_item< dimensions > & rhs) const inline
Definition at line 103 of file h_item.hpp.
setLogicalLocalID()
template<int dimensions> void cl::sycl::h_item< dimensions >::setLogicalLocalID (const id< dimensions > & ID) inline protected
Definition at line 124 of file h_item.hpp.
Referenced by cl::sycl::group< 1 >::parallel_for_work_item().
Friends And Related Function Documentation
detail::Builder
template<int dimensions> friend class detail::Builder friend
Definition at line 111 of file h_item.hpp.
group< dimensions >
template<int dimensions> friend class group< dimensions > friend
Definition at line 112 of file h_item.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/detail/helpers.hpp
include/CL/sycl/h_item.hpp