DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl Class Reference
sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl Class Reference
Class representing the implementation of command_graph<executable>.
#include <detail/graph_impl.hpp>
Public Types
using ReadLock = std::shared_lock< std::shared_mutex >
using WriteLock = std::unique_lock< std::shared_mutex >
Public Member Functions
exec_graph_impl (sycl::context Context, const std::shared_ptr< graph_impl > &GraphImpl, const property_list &PropList)
Constructor.
~exec_graph_impl ()
Destructor.
void makePartitions ()
Partition the graph nodes and put the partition in MPartitions.
sycl::event enqueue (const std::shared_ptr< sycl::detail::queue_impl > &Queue, sycl::detail::CG::StorageInitHelper CGData)
Called by handler::ext_oneapi_command_graph() to schedule graph for execution.
void createCommandBuffers (sycl::device Device, std::shared_ptr< partition > &Partition)
Turns the internal graph representation into UR command-buffers for a device.
sycl::device getDevice () const
Query for the device tied to this graph.
sycl::context getContext () const
Query for the context tied to this graph.
const std::list< std::shared_ptr< node_impl > > & getSchedule () const
Query the scheduling of node execution.
const std::shared_ptr< graph_impl > & getGraphImpl () const
Query the graph_impl.
const std::vector< std::shared_ptr< partition > > & getPartitions () const
Query the vector of the partitions composing the exec_graph.
bool previousSubmissionCompleted () const
Checks if the previous submissions of this graph have been completed This function checks the status of events associated to the previous graph submissions.
std::vector< sycl::detail::AccessorImplHost * > getRequirements () const
Returns a list of all the accessor requirements for this graph.
void update (std::shared_ptr< graph_impl > GraphImpl)
void update (std::shared_ptr< node_impl > Node)
void update (const std::vector< std::shared_ptr< node_impl >> Nodes)
void updateImpl (std::shared_ptr< node_impl > NodeImpl)
Public Attributes
std::shared_mutex MMutex
Protects all the fields that can be changed by class' methods.
Detailed Description
Class representing the implementation of command_graph<executable>.
Definition at line 1275 of file graph_impl.hpp.
Member Typedef Documentation
ReadLock
using sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::ReadLock = std::shared_lock<std::shared_mutex>
Definition at line 1277 of file graph_impl.hpp.
WriteLock
using sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::WriteLock = std::unique_lock<std::shared_mutex>
Definition at line 1278 of file graph_impl.hpp.
Constructor & Destructor Documentation
exec_graph_impl()
sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::exec_graph_impl (sycl::context Context, const std::shared_ptr< graph_impl > & GraphImpl, const property_list & PropList)
Constructor.
Nodes from GraphImpl will be copied when constructing this exec_graph_impl so that nodes may be modified (e.g. when merging subgraph nodes).
Parameters
Context Context to create graph with.
GraphImpl Modifiable graph implementation to create with.
PropList List of properties for constructing this object
Definition at line 760 of file graph_impl.cpp.
References sycl::_V1::feature_not_supported.
~exec_graph_impl()
sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::~exec_graph_impl ()
Destructor.
Releases any PI command-buffers the object has created.
Definition at line 784 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextCommandBufferRelease(), and piextCommandBufferReleaseCommand().
Member Function Documentation
createCommandBuffers()
void sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::createCommandBuffers (sycl::device Device, std::shared_ptr< partition > & Partition)
Turns the internal graph representation into UR command-buffers for a device.
Parameters
Device Device to create backend command-buffers for.
Partion Partition to which the created command-buffer should be attached.
Definition at line 697 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::invalid, PI_EXT_STRUCTURE_TYPE_COMMAND_BUFFER_DESC, piextCommandBufferCreate(), and piextCommandBufferFinalize().
enqueue()
sycl::event sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::enqueue (const std::shared_ptr< sycl::detail::queue_impl > & Queue, sycl::detail::CG::StorageInitHelper CGData)
Called by handler::ext_oneapi_command_graph() to schedule graph for execution.
Parameters
Queue Command-queue to schedule execution on.
CGData Command-group data provided by the sycl::handler
Returns
Event associated with the execution of the graph.
Definition at line 817 of file graph_impl.cpp.
References sycl::_V1::detail::enqueueImpKernel(), sycl::_V1::event, sycl::_V1::invalid, sycl::_V1::kernel, sycl::_V1::detail::CG::StorageInitHelper::MAccStorage, sycl::_V1::make_error_code(), sycl::_V1::detail::CG::StorageInitHelper::MEvents, MMutex, sycl::_V1::detail::CG::StorageInitHelper::MRequirements, PI_EXT_KERNEL_EXEC_INFO_CACHE_DEFAULT, and piextEnqueueCommandBuffer().
getContext()
sycl::context sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::getContext () const inline
Query for the context tied to this graph.
Returns
Context associated with graph.
Definition at line 1328 of file graph_impl.hpp.
getDevice()
sycl::device sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::getDevice () const inline
Query for the device tied to this graph.
Returns
Device associated with graph.
Definition at line 1324 of file graph_impl.hpp.
getGraphImpl()
const std::shared_ptr<graph_impl>& sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::getGraphImpl () const inline
Query the graph_impl.
Returns
pointer to the graph_impl MGraphImpl
Definition at line 1338 of file graph_impl.hpp.
getPartitions()
const std::vector<std::shared_ptr<partition> >& sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::getPartitions () const inline
Query the vector of the partitions composing the exec_graph.
Returns
Vector of partitions in execution order.
Definition at line 1342 of file graph_impl.hpp.
getRequirements()
std::vector<sycl::detail::AccessorImplHost *> sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::getRequirements () const inline
Returns a list of all the accessor requirements for this graph.
Definition at line 1361 of file graph_impl.hpp.
getSchedule()
const std::list<std::shared_ptr<node_impl> >& sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::getSchedule () const inline
Query the scheduling of node execution.
Returns
List of nodes in execution order.
Definition at line 1332 of file graph_impl.hpp.
makePartitions()
void sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::makePartitions ()
Partition the graph nodes and put the partition in MPartitions.
The partitioning splits the graph to allow synchronization between device events and events that do not run on the same device such as host_task.
Definition at line 183 of file graph_impl.cpp.
previousSubmissionCompleted()
bool sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::previousSubmissionCompleted () const inline
Checks if the previous submissions of this graph have been completed This function checks the status of events associated to the previous graph submissions.
Returns
true if all previous submissions have been completed, false otherwise.
Definition at line 1351 of file graph_impl.hpp.
update() [1/3]
void sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::update (const std::vector< std::shared_ptr< node_impl >> Nodes)
Definition at line 1215 of file graph_impl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::invalid, and updateImpl().
update() [2/3]
void sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::update (std::shared_ptr< graph_impl > GraphImpl)
Definition at line 1165 of file graph_impl.cpp.
References sycl::_V1::invalid.
Referenced by update().
update() [3/3]
void sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::update (std::shared_ptr< node_impl > Node)
Definition at line 1211 of file graph_impl.cpp.
References update().
updateImpl()
void sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::updateImpl (std::shared_ptr< node_impl > NodeImpl)
Definition at line 1290 of file graph_impl.cpp.
References sycl::_V1::detail::applyFuncOnFilteredArgs(), sycl::_V1::access::discard_write, sycl::_V1::detail::getSyclObjImpl(), pi_ext_command_buffer_update_kernel_launch_desc::global_work_offset, pi_ext_command_buffer_update_kernel_launch_desc::global_work_size, sycl::_V1::invalid, pi_ext_command_buffer_update_kernel_launch_desc::local_work_size, pi_ext_command_buffer_update_kernel_launch_desc::mem_obj_arg_list, pi_ext_command_buffer_update_kernel_launch_desc::num_mem_obj_args, pi_ext_command_buffer_update_kernel_launch_desc::num_ptr_args, pi_ext_command_buffer_update_kernel_launch_desc::num_value_args, pi_ext_command_buffer_update_kernel_launch_desc::num_work_dim, PI_ACCESS_READ_ONLY, PI_ACCESS_READ_WRITE, PI_ACCESS_WRITE_ONLY, PI_KERNEL_ARG_MEM_OBJ_ACCESS, PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE, piextCommandBufferUpdateKernelLaunch(), piKernelGetGroupInfo(), pi_ext_command_buffer_update_kernel_launch_desc::ptr_arg_list, sycl::_V1::access::read, sycl::_V1::detail::ReverseRangeDimensionsForKernel(), sycl::_V1::detail::tie(), pi_ext_command_buffer_update_kernel_launch_desc::value_arg_list, and sycl::_V1::access::write.
Referenced by update().
Member Data Documentation
MMutex
std::shared_mutex sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::MMutex mutable
Protects all the fields that can be changed by class' methods.
Definition at line 1281 of file graph_impl.hpp.
Referenced by enqueue().
The documentation for this class was generated from the following files:
source/detail/graph_impl.hpp
source/detail/graph_impl.cpp