DPC++ Runtime: cl::sycl::span< _Tp, _Extent > Class Template Reference
cl::sycl::span< _Tp, _Extent > Class Template Reference
#include <CL/sycl/sycl_span.hpp>
Public Types
using element_type = _Tp
using value_type = std::remove_cv_t< _Tp >
using size_type = size_t
using difference_type = ptrdiff_t
using pointer = _Tp *
using const_pointer = const _Tp *
using reference = _Tp &
using const_reference = const _Tp &
using iterator = pointer
using rev_iterator = std::reverse_iterator< pointer >
Public Member Functions
template<size_t _Sz = _Extent, std::enable_if_t< _Sz==0, std::nullptr_t > = nullptr>
constexpr _SYCL_SPAN_INLINE_VISIBILITY span () noexcept
constexpr span (const span &) noexcept=default
constexpr span & operator= (const span &) noexcept=default
constexpr _SYCL_SPAN_INLINE_VISIBILITY span (pointer __ptr, size_type __count)
constexpr _SYCL_SPAN_INLINE_VISIBILITY span (pointer __f, pointer __l)
template<class _OtherElementType , std::enable_if_t< std::is_convertible_v< _OtherElementType(*)[], element_type(*)[]>, std::nullptr_t > = nullptr>
constexpr _SYCL_SPAN_INLINE_VISIBILITY span (std::array< _OtherElementType, _Extent > &__arr) noexcept
template<class _OtherElementType , std::enable_if_t< std::is_convertible_v< const _OtherElementType(*)[], element_type(*)[]>, std::nullptr_t > = nullptr>
constexpr _SYCL_SPAN_INLINE_VISIBILITY span (const std::array< _OtherElementType, _Extent > &__arr) noexcept
template<class _Container >
constexpr _SYCL_SPAN_INLINE_VISIBILITY span (_Container &__c, std::enable_if_t< __is_span_compatible_container< _Container, _Tp >::value, std::nullptr_t >=nullptr)
template<class _Container >
constexpr _SYCL_SPAN_INLINE_VISIBILITY span (const _Container &__c, std::enable_if_t< __is_span_compatible_container< const _Container, _Tp >::value, std::nullptr_t >=nullptr)
template<class _OtherElementType >
constexpr _SYCL_SPAN_INLINE_VISIBILITY span (const span< _OtherElementType, _Extent > &__other, std::enable_if_t< std::is_convertible_v< _OtherElementType(*)[], element_type(*)[]>, std::nullptr_t >=nullptr)
template<size_t _Count>
constexpr _SYCL_SPAN_INLINE_VISIBILITY span< element_type, _Count > first () const noexcept
template<size_t _Count>
constexpr _SYCL_SPAN_INLINE_VISIBILITY span< element_type, _Count > last () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY span< element_type, dynamic_extent > first (size_type __count) const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY span< element_type, dynamic_extent > last (size_type __count) const noexcept
template<size_t _Offset, size_t _Count = dynamic_extent>
constexpr _SYCL_SPAN_INLINE_VISIBILITY auto subspan () const noexcept -> span< element_type,(_Count !=dynamic_extent ? _Count :_Extent - _Offset)>
constexpr _SYCL_SPAN_INLINE_VISIBILITY span< element_type, dynamic_extent > subspan (size_type __offset, size_type __count=dynamic_extent) const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY size_type size () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY size_type size_bytes () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY bool empty () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY reference operator[] (size_type __idx) const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY reference front () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY reference back () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY pointer data () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY iterator begin () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY iterator end () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY rev_iterator rbegin () const noexcept
constexpr _SYCL_SPAN_INLINE_VISIBILITY rev_iterator rend () const noexcept
_SYCL_SPAN_INLINE_VISIBILITY span< const byte, _Extent *sizeof(element_type)> __as_bytes () const noexcept
_SYCL_SPAN_INLINE_VISIBILITY span< byte, _Extent *sizeof(element_type)> __as_writable_bytes () const noexcept
Static Public Attributes
static constexpr size_type extent = _Extent
Detailed Description
template<typename _Tp, size_t _Extent>
class cl::sycl::span< _Tp, _Extent >
Definition at line 151 of file sycl_span.hpp.
Member Typedef Documentation
const_pointer
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::const_pointer = const _Tp *
Definition at line 202 of file sycl_span.hpp.
const_reference
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::const_reference = const _Tp &
Definition at line 204 of file sycl_span.hpp.
difference_type
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::difference_type = ptrdiff_t
Definition at line 200 of file sycl_span.hpp.
element_type
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::element_type = _Tp
Definition at line 197 of file sycl_span.hpp.
iterator
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::iterator = pointer
Definition at line 205 of file sycl_span.hpp.
pointer
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::pointer = _Tp *
Definition at line 201 of file sycl_span.hpp.
reference
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::reference = _Tp &
Definition at line 203 of file sycl_span.hpp.
rev_iterator
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::rev_iterator = std::reverse_iterator<pointer>
Definition at line 206 of file sycl_span.hpp.
size_type
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::size_type = size_t
Definition at line 199 of file sycl_span.hpp.
value_type
template<typename _Tp , size_t _Extent> using cl::sycl::span< _Tp, _Extent >::value_type = std::remove_cv_t<_Tp>
Definition at line 198 of file sycl_span.hpp.
Constructor & Destructor Documentation
span() [1/9]
template<typename _Tp , size_t _Extent> template<size_t _Sz = _Extent, std::enable_if_t< _Sz==0, std::nullptr_t > = nullptr> constexpr _SYCL_SPAN_INLINE_VISIBILITY cl::sycl::span< _Tp, _Extent >::span () inline constexpr noexcept
Definition at line 213 of file sycl_span.hpp.
span() [2/9]
template<typename _Tp , size_t _Extent> constexpr cl::sycl::span< _Tp, _Extent >::span (const span< _Tp, _Extent > &) constexpr default noexcept
span() [3/9]
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY cl::sycl::span< _Tp, _Extent >::span (pointer __ptr, size_type __count) inline explicit constexpr
Definition at line 218 of file sycl_span.hpp.
span() [4/9]
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY cl::sycl::span< _Tp, _Extent >::span (pointer __f, pointer __l) inline explicit constexpr
Definition at line 225 of file sycl_span.hpp.
span() [5/9]
template<typename _Tp , size_t _Extent> template<class _OtherElementType , std::enable_if_t< std::is_convertible_v< _OtherElementType(*)[], element_type(*)[]>, std::nullptr_t > = nullptr> constexpr _SYCL_SPAN_INLINE_VISIBILITY cl::sycl::span< _Tp, _Extent >::span (std::array< _OtherElementType, _Extent > & __arr) inline constexpr noexcept
Definition at line 236 of file sycl_span.hpp.
span() [6/9]
template<typename _Tp , size_t _Extent> template<class _OtherElementType , std::enable_if_t< std::is_convertible_v< const _OtherElementType(*)[], element_type(*)[]>, std::nullptr_t > = nullptr> constexpr _SYCL_SPAN_INLINE_VISIBILITY cl::sycl::span< _Tp, _Extent >::span (const std::array< _OtherElementType, _Extent > & __arr) inline constexpr noexcept
Definition at line 245 of file sycl_span.hpp.
span() [7/9]
template<typename _Tp , size_t _Extent> template<class _Container > constexpr _SYCL_SPAN_INLINE_VISIBILITY cl::sycl::span< _Tp, _Extent >::span (_Container & __c, std::enable_if_t< __is_span_compatible_container< _Container, _Tp >::value, std::nullptr_t > = nullptr) inline explicit constexpr
Definition at line 250 of file sycl_span.hpp.
span() [8/9]
template<typename _Tp , size_t _Extent> template<class _Container > constexpr _SYCL_SPAN_INLINE_VISIBILITY cl::sycl::span< _Tp, _Extent >::span (const _Container & __c, std::enable_if_t< __is_span_compatible_container< const _Container, _Tp >::value, std::nullptr_t > = nullptr) inline explicit constexpr
Definition at line 260 of file sycl_span.hpp.
span() [9/9]
template<typename _Tp , size_t _Extent> template<class _OtherElementType > constexpr _SYCL_SPAN_INLINE_VISIBILITY cl::sycl::span< _Tp, _Extent >::span (const span< _OtherElementType, _Extent > & __other, std::enable_if_t< std::is_convertible_v< _OtherElementType(*)[], element_type(*)[]>, std::nullptr_t > = nullptr) inline constexpr
Definition at line 271 of file sycl_span.hpp.
References cl::sycl::span< _Tp, _Extent >::data().
Member Function Documentation
__as_bytes()
template<typename _Tp , size_t _Extent> _SYCL_SPAN_INLINE_VISIBILITY span<const byte, _Extent * sizeof(element_type)> cl::sycl::span< _Tp, _Extent >::__as_bytes () const inline noexcept
Definition at line 386 of file sycl_span.hpp.
__as_writable_bytes()
template<typename _Tp , size_t _Extent> _SYCL_SPAN_INLINE_VISIBILITY span<byte, _Extent * sizeof(element_type)> cl::sycl::span< _Tp, _Extent >::__as_writable_bytes () const inline noexcept
Definition at line 392 of file sycl_span.hpp.
back()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY reference cl::sycl::span< _Tp, _Extent >::back () const inline constexpr noexcept
Definition at line 362 of file sycl_span.hpp.
References _SYCL_SPAN_ASSERT.
begin()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY iterator cl::sycl::span< _Tp, _Extent >::begin () const inline constexpr noexcept
Definition at line 372 of file sycl_span.hpp.
data()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY pointer cl::sycl::span< _Tp, _Extent >::data () const inline constexpr noexcept
Definition at line 367 of file sycl_span.hpp.
Referenced by cl::sycl::span< _Tp, _Extent >::span(), and cl::sycl::span< _Tp, dynamic_extent >::span().
empty()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY bool cl::sycl::span< _Tp, _Extent >::empty () const inline constexpr noexcept
Definition at line 347 of file sycl_span.hpp.
end()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY iterator cl::sycl::span< _Tp, _Extent >::end () const inline constexpr noexcept
Definition at line 375 of file sycl_span.hpp.
first() [1/2]
template<typename _Tp , size_t _Extent> template<size_t _Count> constexpr _SYCL_SPAN_INLINE_VISIBILITY span<element_type, _Count> cl::sycl::span< _Tp, _Extent >::first () const inline constexpr noexcept
Definition at line 282 of file sycl_span.hpp.
first() [2/2]
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY span<element_type, dynamic_extent> cl::sycl::span< _Tp, _Extent >::first (size_type __count) const inline constexpr noexcept
Definition at line 295 of file sycl_span.hpp.
References _SYCL_SPAN_ASSERT.
front()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY reference cl::sycl::span< _Tp, _Extent >::front () const inline constexpr noexcept
Definition at line 357 of file sycl_span.hpp.
References _SYCL_SPAN_ASSERT.
last() [1/2]
template<typename _Tp , size_t _Extent> template<size_t _Count> constexpr _SYCL_SPAN_INLINE_VISIBILITY span<element_type, _Count> cl::sycl::span< _Tp, _Extent >::last () const inline constexpr noexcept
Definition at line 288 of file sycl_span.hpp.
last() [2/2]
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY span<element_type, dynamic_extent> cl::sycl::span< _Tp, _Extent >::last (size_type __count) const inline constexpr noexcept
Definition at line 303 of file sycl_span.hpp.
References _SYCL_SPAN_ASSERT.
operator=()
template<typename _Tp , size_t _Extent> constexpr span& cl::sycl::span< _Tp, _Extent >::operator= (const span< _Tp, _Extent > &) constexpr default noexcept
operator[]()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY reference cl::sycl::span< _Tp, _Extent >::operator[] (size_type __idx) const inline constexpr noexcept
Definition at line 352 of file sycl_span.hpp.
References _SYCL_SPAN_ASSERT.
rbegin()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY rev_iterator cl::sycl::span< _Tp, _Extent >::rbegin () const inline constexpr noexcept
Definition at line 378 of file sycl_span.hpp.
rend()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY rev_iterator cl::sycl::span< _Tp, _Extent >::rend () const inline constexpr noexcept
Definition at line 381 of file sycl_span.hpp.
size()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY size_type cl::sycl::span< _Tp, _Extent >::size () const inline constexpr noexcept
Definition at line 341 of file sycl_span.hpp.
size_bytes()
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY size_type cl::sycl::span< _Tp, _Extent >::size_bytes () const inline constexpr noexcept
Definition at line 344 of file sycl_span.hpp.
subspan() [1/2]
template<typename _Tp , size_t _Extent> template<size_t _Offset, size_t _Count = dynamic_extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY auto cl::sycl::span< _Tp, _Extent >::subspan () const -> span<element_type, (_Count != dynamic_extent ? _Count : _Extent - _Offset)> inline constexpr noexcept
Definition at line 311 of file sycl_span.hpp.
References cl::sycl::dynamic_extent.
subspan() [2/2]
template<typename _Tp , size_t _Extent> constexpr _SYCL_SPAN_INLINE_VISIBILITY span<element_type, dynamic_extent> cl::sycl::span< _Tp, _Extent >::subspan (size_type __offset, size_type __count = dynamic_extent) const inline constexpr noexcept
Definition at line 327 of file sycl_span.hpp.
References _SYCL_SPAN_ASSERT, and cl::sycl::dynamic_extent.
Member Data Documentation
extent
template<typename _Tp , size_t _Extent> constexpr size_type cl::sycl::span< _Tp, _Extent >::extent = _Extent static constexpr
Definition at line 208 of file sycl_span.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/sycl_span.hpp