DPC++ Runtime: _pi_device Struct Reference
_pi_device Struct Reference
PI device mapping to a CUdevice.
#include <cuda/pi_cuda.hpp>
Public Member Functions
_pi_device (native_type cuDevice, pi_platform platform)
native_type get () const noexcept
pi_uint32 get_reference_count () const noexcept
pi_platform get_platform () const noexcept
_pi_device (ze_device_handle_t Device, pi_platform Plt, bool isSubDevice=false)
~_pi_device ()
pi_result initialize ()
pi_result getAvailableCommandList (pi_queue Queue, ze_command_list_handle_t *ZeCommandList, ze_fence_handle_t *ZeFence, bool AllowBatching=false)
Public Member Functions inherited from _pi_object
_pi_object ()
Public Attributes
uint32_t ZeComputeQueueGroupIndex
ze_device_handle_t ZeDevice
pi_platform Platform
std::mutex ZeCommandListCacheMutex
std::list< ze_command_list_handle_t > ZeCommandListCache
bool IsSubDevice
ze_device_properties_t ZeDeviceProperties
ze_device_compute_properties_t ZeDeviceComputeProperties
Public Attributes inherited from _pi_object
std::atomic< pi_uint32 > RefCount
Detailed Description
PI device mapping to a CUdevice.
Includes an observer pointer to the platform, and implements the reference counting semantics since CUDA objects are not refcounted.
Definition at line 67 of file pi_cuda.hpp.
Constructor & Destructor Documentation
_pi_device() [1/2]
_pi_device::_pi_device (native_type cuDevice, pi_platform platform) inline
Definition at line 75 of file pi_cuda.hpp.
_pi_device() [2/2]
_pi_device::_pi_device (ze_device_handle_t Device, pi_platform Plt, bool isSubDevice = false) inline
Definition at line 138 of file pi_level_zero.hpp.
~_pi_device()
_pi_device::~_pi_device ()
Definition at line 416 of file pi_level_zero.cpp.
Member Function Documentation
get()
native_type _pi_device::get () const inline noexcept
Definition at line 78 of file pi_cuda.hpp.
Referenced by cuda_piContextRelease(), cuda_piDeviceGetInfo(), cuda_piextDeviceGetNativeHandle(), cuda_piextUSMEnqueuePrefetch(), cuda_piKernelGetGroupInfo(), cuda_piKernelGetSubGroupInfo(), cuda_piProgramCreateWithBinary(), piDevicesGet(), and piextDeviceCreateWithNativeHandle().
get_platform()
pi_platform _pi_device::get_platform () const inline noexcept
Definition at line 82 of file pi_cuda.hpp.
Referenced by cuda_piDeviceGetInfo().
get_reference_count()
pi_uint32 _pi_device::get_reference_count () const inline noexcept
Definition at line 80 of file pi_cuda.hpp.
Referenced by cuda_piDeviceGetInfo().
getAvailableCommandList()
pi_result _pi_device::getAvailableCommandList (pi_queue Queue, ze_command_list_handle_t * ZeCommandList, ze_fence_handle_t * ZeFence, bool AllowBatching = false)
Definition at line 554 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_queue::Device, _pi_queue::executeOpenCommandList(), PI_OUT_OF_RESOURCES, PI_SUCCESS, _pi_queue::resetCommandListFenceEntry(), ZE_CALL, ZE_CALL_NOCHECK, ZeCommandListCache, ZeCommandListCacheMutex, _pi_queue::ZeCommandListFenceMap, _pi_queue::ZeCommandQueue, _pi_context::ZeContext, _pi_queue::ZeOpenCommandList, and _pi_queue::ZeOpenCommandListFence.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), piextUSMEnqueueMemAdvise(), and piextUSMEnqueuePrefetch().
initialize()
pi_result _pi_device::initialize ()
Definition at line 458 of file pi_level_zero.cpp.
References PI_ERROR_UNKNOWN, PI_SUCCESS, cl::sycl::info::uint32_t, and ZE_CALL.
Referenced by piDevicePartition().
Member Data Documentation
IsSubDevice
bool _pi_device::IsSubDevice
Definition at line 171 of file pi_level_zero.hpp.
Referenced by piDeviceGetInfo(), piDeviceRelease(), and piDeviceRetain().
Platform
pi_platform _pi_device::Platform
Definition at line 161 of file pi_level_zero.hpp.
Referenced by piDeviceGetInfo(), and piDevicePartition().
ZeCommandListCache
std::list<ze_command_list_handle_t> _pi_device::ZeCommandListCache
Definition at line 166 of file pi_level_zero.hpp.
Referenced by getAvailableCommandList().
ZeCommandListCacheMutex
std::mutex _pi_device::ZeCommandListCacheMutex
Definition at line 164 of file pi_level_zero.hpp.
Referenced by getAvailableCommandList().
ZeComputeQueueGroupIndex
uint32_t _pi_device::ZeComputeQueueGroupIndex
Definition at line 152 of file pi_level_zero.hpp.
Referenced by piQueueCreate().
ZeDevice
ze_device_handle_t _pi_device::ZeDevice
Definition at line 158 of file pi_level_zero.hpp.
Referenced by compileOrBuild(), piDeviceGetInfo(), piDevicePartition(), piextDeviceGetNativeHandle(), piextUSMEnqueueMemAdvise(), piKernelGetGroupInfo(), piMemImageCreate(), piProgramLink(), piQueueCreate(), piSamplerCreate(), USMDeviceAllocImpl(), and USMSharedAllocImpl().
ZeDeviceComputeProperties
ze_device_compute_properties_t _pi_device::ZeDeviceComputeProperties
Definition at line 192 of file pi_level_zero.hpp.
Referenced by piDeviceGetInfo().
ZeDeviceProperties
ze_device_properties_t _pi_device::ZeDeviceProperties
Definition at line 191 of file pi_level_zero.hpp.
Referenced by piDeviceGetInfo(), and piEventGetProfilingInfo().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/level_zero/pi_level_zero.hpp
plugins/level_zero/pi_level_zero.cpp