DPC++ Runtime: sycl::_V1::kernel_id Class Reference
sycl::_V1::kernel_id Class Reference
DPC++ User API
Objects of the class identify kernel is some kernel_bundle related APIs.
#include <sycl/kernel_bundle.hpp>
Public Member Functions
kernel_id ()=delete
const char * get_name () const noexcept
bool operator== (const kernel_id &RHS) const
bool operator!= (const kernel_id &RHS) const
Public Member Functions inherited from sycl::_V1::detail::OwnerLessBase< kernel_id >
bool ext_oneapi_owner_before (const ext::oneapi::detail::weak_object_base< kernel_id > &Other) const noexcept
Compares the object against a weak object using an owner-based implementation-defined ordering.
bool ext_oneapi_owner_before (const kernel_id &Other) const noexcept
Compares the object against another object using an owner-based implementation-defined ordering.
Friends
template<class T >
T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Detailed Description
Objects of the class identify kernel is some kernel_bundle related APIs.
Definition at line 58 of file kernel_bundle.hpp.
Constructor & Destructor Documentation
kernel_id()
sycl::_V1::kernel_id::kernel_id () delete
Member Function Documentation
get_name()
const char * sycl::_V1::kernel_id::get_name () const noexcept
Returns
a null-terminated string which contains the kernel name
Definition at line 25 of file kernel_bundle.cpp.
Referenced by sycl::_V1::detail::kernel_bundle_impl::get_kernel(), sycl::_V1::detail::LessByNameComp::operator()(), and sycl::_V1::detail::EqualByNameComp::operator()().
operator!=()
bool sycl::_V1::kernel_id::operator!= (const kernel_id & RHS) const inline
Definition at line 67 of file kernel_bundle.hpp.
operator==()
bool sycl::_V1::kernel_id::operator== (const kernel_id & RHS) const inline
Definition at line 65 of file kernel_bundle.hpp.
Friends And Related Function Documentation
detail::createSyclObjFromImpl
template<class T > T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
The documentation for this class was generated from the following files:
include/sycl/kernel_bundle.hpp
source/kernel_bundle.cpp