DPC++ Runtime: sycl::_V1::exception Class Reference
sycl::_V1::exception Class Reference
DPC++ User API
#include <sycl/exception.hpp>
Public Member Functions
__SYCL2020_DEPRECATED ("The version of an exception constructor which takes " "no arguments is deprecated.") exception()=default
virtual ~exception ()
exception (std::error_code, const char *Msg)
exception (std::error_code Ec, const std::string &Msg)
exception (std::error_code)
exception (int EV, const std::error_category &ECat, const std::string &WhatArg)
exception (int, const std::error_category &, const char *)
exception (int, const std::error_category &)
exception (context, std::error_code, const std::string &)
exception (context, std::error_code, const char *)
exception (context, std::error_code)
exception (context, int, const std::error_category &, const std::string &)
exception (context, int, const std::error_category &, const char *)
exception (context, int, const std::error_category &)
const std::error_code & code () const noexcept
const std::error_category & category () const noexcept
const char * what () const noexcept final
bool has_context () const noexcept
context get_context () const
cl_int get_cl_code () const
Protected Member Functions
exception (std::error_code Ec, const char *Msg, const pi_int32 PIErr, std::shared_ptr< context > Context=nullptr)
exception (std::error_code Ec, const std::string &Msg, const pi_int32 PIErr, std::shared_ptr< context > Context=nullptr)
exception (const std::string &Msg)
exception (std::error_code Ec, std::shared_ptr< context > SharedPtrCtx, const std::string &what_arg)
exception (std::error_code Ec, std::shared_ptr< context > SharedPtrCtx, const char *WhatArg)
Detailed Description
Definition at line 71 of file exception.hpp.
Constructor & Destructor Documentation
~exception()
sycl::_V1::exception::~exception () virtual
Definition at line 67 of file exception.cpp.
exception() [1/17]
sycl::_V1::exception::exception (std::error_code EC, const char * Msg)
Definition at line 19 of file exception.cpp.
exception() [2/17]
sycl::_V1::exception::exception (std::error_code Ec, const std::string & Msg) inline
Definition at line 80 of file exception.hpp.
exception() [3/17]
sycl::_V1::exception::exception (std::error_code EC)
Definition at line 23 of file exception.cpp.
exception() [4/17]
sycl::_V1::exception::exception (int EV, const std::error_category & ECat, const std::string & WhatArg) inline
Definition at line 85 of file exception.hpp.
exception() [5/17]
sycl::_V1::exception::exception (int EV, const std::error_category & ECat, const char * WhatArg)
Definition at line 25 of file exception.cpp.
exception() [6/17]
sycl::_V1::exception::exception (int EV, const std::error_category & ECat)
Definition at line 29 of file exception.cpp.
exception() [7/17]
sycl::_V1::exception::exception (context Ctx, std::error_code EC, const std::string & WhatArg)
Definition at line 33 of file exception.cpp.
exception() [8/17]
sycl::_V1::exception::exception (context Ctx, std::error_code EC, const char * WhatArg)
Definition at line 37 of file exception.cpp.
exception() [9/17]
sycl::_V1::exception::exception (context Ctx, std::error_code EC)
Definition at line 40 of file exception.cpp.
exception() [10/17]
sycl::_V1::exception::exception (context Ctx, int EV, const std::error_category & ECat, const std::string & WhatArg)
Definition at line 47 of file exception.cpp.
exception() [11/17]
sycl::_V1::exception::exception (context Ctx, int EV, const std::error_category & ECat, const char * WhatArg)
Definition at line 43 of file exception.cpp.
exception() [12/17]
sycl::_V1::exception::exception (context Ctx, int EV, const std::error_category & ECat)
Definition at line 51 of file exception.cpp.
exception() [13/17]
sycl::_V1::exception::exception (std::error_code Ec, const char * Msg, const pi_int32 PIErr, std::shared_ptr< context > Context = nullptr) inline protected
Definition at line 127 of file exception.hpp.
exception() [14/17]
sycl::_V1::exception::exception (std::error_code Ec, const std::string & Msg, const pi_int32 PIErr, std::shared_ptr< context > Context = nullptr) inline protected
Definition at line 131 of file exception.hpp.
exception() [15/17]
sycl::_V1::exception::exception (const std::string & Msg) inline protected
Definition at line 137 of file exception.hpp.
exception() [16/17]
sycl::_V1::exception::exception (std::error_code Ec, std::shared_ptr< context > SharedPtrCtx, const std::string & what_arg) inline protected
Definition at line 148 of file exception.hpp.
exception() [17/17]
sycl::_V1::exception::exception (std::error_code Ec, std::shared_ptr< context > SharedPtrCtx, const char * WhatArg) protected
Definition at line 56 of file exception.cpp.
References sycl::_V1::detail::GlobalHandler::instance(), and sycl::_V1::detail::GlobalHandler::TraceEventXPTI().
Member Function Documentation
__SYCL2020_DEPRECATED()
sycl::_V1::exception::__SYCL2020_DEPRECATED ("The version of an exception constructor which takes " "no arguments is deprecated.") default
category()
const std::error_category & sycl::_V1::exception::category () const noexcept
Definition at line 71 of file exception.cpp.
References code().
code()
const std::error_code & sycl::_V1::exception::code () const noexcept
Definition at line 69 of file exception.cpp.
Referenced by category(), sycl::_V1::detail::get_device_info_impl< std::vector< ext::oneapi::experimental::matrix::combination >, ext::oneapi::experimental::info::device::matrix_combinations >::get(), and sycl::_V1::detail::event_impl::setSubmissionTime().
get_cl_code()
cl_int sycl::_V1::exception::get_cl_code () const
Definition at line 86 of file exception.cpp.
Referenced by sycl::_V1::detail::KernelProgramCache::getOrBuild().
get_context()
context sycl::_V1::exception::get_context () const
Definition at line 79 of file exception.cpp.
References has_context().
has_context()
bool sycl::_V1::exception::has_context () const noexcept
Definition at line 77 of file exception.cpp.
Referenced by get_context().
what()
const char * sycl::_V1::exception::what () const final noexcept
Definition at line 75 of file exception.cpp.
Referenced by sycl::_V1::detail::KernelProgramCache::getOrBuild(), and sycl::_V1::detail::event_impl::setSubmissionTime().
The documentation for this class was generated from the following files:
include/sycl/exception.hpp
source/exception.cpp