DPC++ Runtime: sycl::_V1::detail::kernel_bundle_impl Class Reference
sycl::_V1::detail::kernel_bundle_impl Class Reference
The class is an impl counterpart of the sycl::kernel_bundle.
#include <detail/kernel_bundle_impl.hpp>
Public Member Functions
kernel_bundle_impl (context Ctx, std::vector< device > Devs, bundle_state State)
kernel_bundle_impl (context Ctx, std::vector< device > Devs)
kernel_bundle_impl (context Ctx, std::vector< device > Devs, device_image_plain &DevImage)
kernel_bundle_impl (const kernel_bundle< bundle_state::input > &InputBundle, std::vector< device > Devs, const property_list &PropList, bundle_state TargetState)
kernel_bundle_impl (const std::vector< kernel_bundle< bundle_state::object >> &ObjectBundles, std::vector< device > Devs, const property_list &PropList)
kernel_bundle_impl (context Ctx, std::vector< device > Devs, const std::vector< kernel_id > &KernelIDs, bundle_state State)
kernel_bundle_impl (context Ctx, std::vector< device > Devs, const DevImgSelectorImpl &Selector, bundle_state State)
kernel_bundle_impl (const std::vector< detail::KernelBundleImplPtr > &Bundles, bundle_state State)
kernel_bundle_impl (const context &Context, syclex::source_language Lang, const std::string &Src)
kernel_bundle_impl (const context &Context, syclex::source_language Lang, const std::vector< std::byte > &Bytes)
kernel_bundle_impl (context Ctx, std::vector< device > Devs, device_image_plain &DevImage, std::vector< std::string > KNames)
std::shared_ptr< kernel_bundle_impl > build_from_source (const std::vector< device > Devices, const std::vector< std::string > &BuildOptions, std::string *LogPtr)
bool ext_oneapi_has_kernel (const std::string &Name)
kernel ext_oneapi_get_kernel (const std::string &Name, const std::shared_ptr< kernel_bundle_impl > &Self)
bool empty () const noexcept
backend get_backend () const noexcept
context get_context () const noexcept
const std::vector< device > & get_devices () const noexcept
std::vector< kernel_id > get_kernel_ids () const
kernel get_kernel (const kernel_id &KernelID, const std::shared_ptr< detail::kernel_bundle_impl > &Self) const
bool has_kernel (const kernel_id &KernelID) const noexcept
bool has_kernel (const kernel_id &KernelID, const device &Dev) const noexcept
bool contains_specialization_constants () const noexcept
bool native_specialization_constant () const noexcept
bool has_specialization_constant (const char *SpecName) const noexcept
void set_specialization_constant_raw_value (const char *SpecName, const void *Value, size_t Size) noexcept
void get_specialization_constant_raw_value (const char *SpecName, void *ValueRet) const noexcept
bool is_specialization_constant_set (const char *SpecName) const noexcept
const device_image_plain * begin () const
const device_image_plain * end () const
size_t size () const noexcept
bundle_state get_bundle_state () const
const SpecConstMapT & get_spec_const_map_ref () const noexcept
bool isInterop () const
bool add_kernel (const kernel_id &KernelID, const device &Dev)
Detailed Description
The class is an impl counterpart of the sycl::kernel_bundle.
Definition at line 56 of file kernel_bundle_impl.hpp.
Constructor & Destructor Documentation
kernel_bundle_impl() [1/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, bundle_state State) inline
Definition at line 81 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::ProgramManager::getInstance(), and sycl::_V1::detail::ProgramManager::getSYCLDeviceImages().
kernel_bundle_impl() [2/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs) inline
Definition at line 91 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::checkAllDevicesAreInContext(), sycl::_V1::invalid, and sycl::_V1::make_error_code().
kernel_bundle_impl() [3/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, device_image_plain & DevImage) inline
Definition at line 102 of file kernel_bundle_impl.hpp.
kernel_bundle_impl() [4/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (const kernel_bundle< bundle_state::input > & InputBundle, std::vector< device > Devs, const property_list & PropList, bundle_state TargetState) inline
Definition at line 111 of file kernel_bundle_impl.hpp.
References all_of(), sycl::_V1::compile(), sycl::_V1::executable, sycl::_V1::ext_oneapi_source, sycl::_V1::detail::ProgramManager::getInstance(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::input, sycl::_V1::invalid, sycl::_V1::make_error_code(), none_of(), and sycl::_V1::object.
kernel_bundle_impl() [5/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (const std::vector< kernel_bundle< bundle_state::object >> & ObjectBundles, std::vector< device > Devs, const property_list & PropList) inline
Definition at line 163 of file kernel_bundle_impl.hpp.
References all_of(), get_context(), sycl::_V1::invalid, and sycl::_V1::make_error_code().
kernel_bundle_impl() [6/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, const std::vector< kernel_id > & KernelIDs, bundle_state State) inline
Definition at line 242 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::ProgramManager::getInstance(), and sycl::_V1::detail::ProgramManager::getSYCLDeviceImages().
kernel_bundle_impl() [7/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, const DevImgSelectorImpl & Selector, bundle_state State) inline
Definition at line 253 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::ProgramManager::getInstance(), and sycl::_V1::detail::ProgramManager::getSYCLDeviceImages().
kernel_bundle_impl() [8/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (const std::vector< detail::KernelBundleImplPtr > & Bundles, bundle_state State) inline
Definition at line 264 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::for_each(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::input, sycl::_V1::invalid, and sycl::_V1::make_error_code().
kernel_bundle_impl() [9/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (const context & Context, syclex::source_language Lang, const std::string & Src) inline
Definition at line 334 of file kernel_bundle_impl.hpp.
References sycl::_V1::ext_oneapi_source.
kernel_bundle_impl() [10/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (const context & Context, syclex::source_language Lang, const std::vector< std::byte > & Bytes) inline
Definition at line 341 of file kernel_bundle_impl.hpp.
References sycl::_V1::ext_oneapi_source.
kernel_bundle_impl() [11/11]
sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, device_image_plain & DevImage, std::vector< std::string > KNames) inline
Definition at line 349 of file kernel_bundle_impl.hpp.
References sycl::_V1::executable.
Member Function Documentation
add_kernel()
bool sycl::_V1::detail::kernel_bundle_impl::add_kernel (const kernel_id & KernelID, const device & Dev) inline
Definition at line 677 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::ProgramManager::getInstance(), sycl::_V1::detail::ProgramManager::getSYCLDeviceImages(), and sycl::_V1::detail::getSyclObjImpl().
begin()
const device_image_plain* sycl::_V1::detail::kernel_bundle_impl::begin () const inline
Definition at line 661 of file kernel_bundle_impl.hpp.
build_from_source()
std::shared_ptr<kernel_bundle_impl> sycl::_V1::detail::kernel_bundle_impl::build_from_source (const std::vector< device > Devices, const std::vector< std::string > & BuildOptions, std::string * LogPtr) inline
Definition at line 358 of file kernel_bundle_impl.hpp.
References sycl::_V1::build, sycl::_V1::ext::oneapi::experimental::detail::BuildOptions, sycl::_V1::executable, sycl::_V1::ext_oneapi_source, sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::invalid, sycl::_V1::make_error_code(), sycl::_V1::ext::oneapi::experimental::detail::OpenCLC_to_SPIRV(), PI_PROGRAM_INFO_KERNEL_NAMES, PI_PROGRAM_INFO_NUM_KERNELS, piProgramBuild(), piProgramCreate(), piProgramGetInfo(), and sycl::_V1::detail::split_string().
contains_specialization_constants()
bool sycl::_V1::detail::kernel_bundle_impl::contains_specialization_constants () const inline noexcept
Definition at line 589 of file kernel_bundle_impl.hpp.
References any_of().
empty()
bool sycl::_V1::detail::kernel_bundle_impl::empty () const inline noexcept
Definition at line 477 of file kernel_bundle_impl.hpp.
end()
const device_image_plain* sycl::_V1::detail::kernel_bundle_impl::end () const inline
Definition at line 663 of file kernel_bundle_impl.hpp.
ext_oneapi_get_kernel()
kernel sycl::_V1::detail::kernel_bundle_impl::ext_oneapi_get_kernel (const std::string & Name, const std::shared_ptr< kernel_bundle_impl > & Self) inline
Definition at line 449 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::invalid, sycl::_V1::make_error_code(), and piKernelCreate().
ext_oneapi_has_kernel()
bool sycl::_V1::detail::kernel_bundle_impl::ext_oneapi_has_kernel (const std::string & Name) inline
Definition at line 443 of file kernel_bundle_impl.hpp.
get_backend()
backend sycl::_V1::detail::kernel_bundle_impl::get_backend () const inline noexcept
Definition at line 479 of file kernel_bundle_impl.hpp.
get_bundle_state()
bundle_state sycl::_V1::detail::kernel_bundle_impl::get_bundle_state () const inline
Definition at line 669 of file kernel_bundle_impl.hpp.
get_context()
context sycl::_V1::detail::kernel_bundle_impl::get_context () const inline noexcept
Definition at line 483 of file kernel_bundle_impl.hpp.
Referenced by kernel_bundle_impl().
get_devices()
const std::vector<device>& sycl::_V1::detail::kernel_bundle_impl::get_devices () const inline noexcept
Definition at line 485 of file kernel_bundle_impl.hpp.
get_kernel()
kernel sycl::_V1::detail::kernel_bundle_impl::get_kernel (const kernel_id & KernelID, const std::shared_ptr< detail::kernel_bundle_impl > & Self) const inline
Definition at line 506 of file kernel_bundle_impl.hpp.
References sycl::_V1::kernel_id::get_name(), sycl::_V1::detail::ProgramManager::getInstance(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::invalid, and sycl::_V1::make_error_code().
get_kernel_ids()
std::vector<kernel_id> sycl::_V1::detail::kernel_bundle_impl::get_kernel_ids () const inline
Definition at line 487 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::getSyclObjImpl().
get_spec_const_map_ref()
const SpecConstMapT& sycl::_V1::detail::kernel_bundle_impl::get_spec_const_map_ref () const inline noexcept
Definition at line 671 of file kernel_bundle_impl.hpp.
get_specialization_constant_raw_value()
void sycl::_V1::detail::kernel_bundle_impl::get_specialization_constant_raw_value (const char * SpecName, void * ValueRet) const inline noexcept
Definition at line 628 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::getSyclObjImpl().
has_kernel() [1/2]
bool sycl::_V1::detail::kernel_bundle_impl::has_kernel (const kernel_id & KernelID) const inline noexcept
Definition at line 574 of file kernel_bundle_impl.hpp.
References any_of().
has_kernel() [2/2]
bool sycl::_V1::detail::kernel_bundle_impl::has_kernel (const kernel_id & KernelID, const device & Dev) const inline noexcept
Definition at line 581 of file kernel_bundle_impl.hpp.
References any_of().
has_specialization_constant()
bool sycl::_V1::detail::kernel_bundle_impl::has_specialization_constant (const char * SpecName) const inline noexcept
Definition at line 606 of file kernel_bundle_impl.hpp.
References any_of().
is_specialization_constant_set()
bool sycl::_V1::detail::kernel_bundle_impl::is_specialization_constant_set (const char * SpecName) const inline noexcept
Definition at line 651 of file kernel_bundle_impl.hpp.
References any_of().
isInterop()
bool sycl::_V1::detail::kernel_bundle_impl::isInterop () const inline
Definition at line 675 of file kernel_bundle_impl.hpp.
native_specialization_constant()
bool sycl::_V1::detail::kernel_bundle_impl::native_specialization_constant () const inline noexcept
Definition at line 597 of file kernel_bundle_impl.hpp.
References all_of().
set_specialization_constant_raw_value()
void sycl::_V1::detail::kernel_bundle_impl::set_specialization_constant_raw_value (const char * SpecName, const void * Value, size_t Size) inline noexcept
Definition at line 614 of file kernel_bundle_impl.hpp.
References sycl::_V1::detail::getSyclObjImpl().
size()
size_t sycl::_V1::detail::kernel_bundle_impl::size () const inline noexcept
Definition at line 667 of file kernel_bundle_impl.hpp.
The documentation for this class was generated from the following file:
source/detail/kernel_bundle_impl.hpp