DPC++ Runtime: cl::sycl::detail::device_image_impl Class Reference
cl::sycl::detail::device_image_impl Class Reference
#include <detail/device_image_impl.hpp>
Classes
struct SpecConstDescT
Public Types
using SpecConstMapT = std::map< std::string, std::vector< SpecConstDescT > >
Public Member Functions
device_image_impl (const RTDeviceBinaryImage *BinImage, context Context, std::vector< device > Devices, bundle_state State, std::shared_ptr< std::vector< kernel_id >> KernelIDs, RT::PiProgram Program)
device_image_impl (const RTDeviceBinaryImage *BinImage, context Context, std::vector< device > Devices, bundle_state State, std::shared_ptr< std::vector< kernel_id >> KernelIDs, RT::PiProgram Program, const SpecConstMapT &SpecConstMap, const std::vector< unsigned char > &SpecConstsBlob)
bool has_kernel (const kernel_id &KernelIDCand) const noexcept
bool has_kernel (const kernel_id &KernelIDCand, const device &DeviceCand) const noexcept
const std::vector< kernel_id > & get_kernel_ids () const noexcept
bool has_specialization_constants () const noexcept
bool all_specialization_constant_native () const noexcept
bool has_specialization_constant (const char *SpecName) const noexcept
void set_specialization_constant_raw_value (const char *SpecName, const void *Value) noexcept
void get_specialization_constant_raw_value (const char *SpecName, void *ValueRet) const noexcept
bool is_specialization_constant_set (const char *SpecName) const noexcept
bundle_state get_state () const noexcept
void set_state (bundle_state NewState) noexcept
const std::vector< device > & get_devices () const noexcept
bool compatible_with_device (const device &Dev) const
const RT::PiProgram & get_program_ref () const noexcept
const RTDeviceBinaryImage *& get_bin_image_ref () noexcept
const context & get_context () const noexcept
std::shared_ptr< std::vector< kernel_id > > & get_kernel_ids_ptr () noexcept
std::vector< unsigned char > & get_spec_const_blob_ref () noexcept
RT::PiMem & get_spec_const_buffer_ref () noexcept
const SpecConstMapT & get_spec_const_data_ref () const noexcept
std::mutex & get_spec_const_data_lock () noexcept
pi_native_handle getNative () const
~device_image_impl ()
Detailed Description
Definition at line 44 of file device_image_impl.hpp.
Member Typedef Documentation
SpecConstMapT
using cl::sycl::detail::device_image_impl::SpecConstMapT = std::map<std::string, std::vector<SpecConstDescT> >
Definition at line 56 of file device_image_impl.hpp.
Constructor & Destructor Documentation
device_image_impl() [1/2]
cl::sycl::detail::device_image_impl::device_image_impl (const RTDeviceBinaryImage * BinImage, context Context, std::vector< device > Devices, bundle_state State, std::shared_ptr< std::vector< kernel_id >> KernelIDs, RT::PiProgram Program) inline
Definition at line 58 of file device_image_impl.hpp.
device_image_impl() [2/2]
cl::sycl::detail::device_image_impl::device_image_impl (const RTDeviceBinaryImage * BinImage, context Context, std::vector< device > Devices, bundle_state State, std::shared_ptr< std::vector< kernel_id >> KernelIDs, RT::PiProgram Program, const SpecConstMapT & SpecConstMap, const std::vector< unsigned char > & SpecConstsBlob) inline
Definition at line 68 of file device_image_impl.hpp.
~device_image_impl()
cl::sycl::detail::device_image_impl::~device_image_impl () inline
Definition at line 232 of file device_image_impl.hpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::memReleaseHelper(), and piProgramRelease().
Member Function Documentation
all_specialization_constant_native()
bool cl::sycl::detail::device_image_impl::all_specialization_constant_native () const inline noexcept
Definition at line 104 of file device_image_impl.hpp.
compatible_with_device()
bool cl::sycl::detail::device_image_impl::compatible_with_device (const device & Dev) const inline
Definition at line 174 of file device_image_impl.hpp.
References any_of().
get_bin_image_ref()
const RTDeviceBinaryImage*& cl::sycl::detail::device_image_impl::get_bin_image_ref () inline noexcept
Definition at line 182 of file device_image_impl.hpp.
get_context()
const context& cl::sycl::detail::device_image_impl::get_context () const inline noexcept
Definition at line 184 of file device_image_impl.hpp.
get_devices()
const std::vector<device>& cl::sycl::detail::device_image_impl::get_devices () const inline noexcept
Definition at line 172 of file device_image_impl.hpp.
get_kernel_ids()
const std::vector<kernel_id>& cl::sycl::detail::device_image_impl::get_kernel_ids () const inline noexcept
Definition at line 92 of file device_image_impl.hpp.
get_kernel_ids_ptr()
std::shared_ptr<std::vector<kernel_id> >& cl::sycl::detail::device_image_impl::get_kernel_ids_ptr () inline noexcept
Definition at line 186 of file device_image_impl.hpp.
get_program_ref()
const RT::PiProgram& cl::sycl::detail::device_image_impl::get_program_ref () const inline noexcept
Definition at line 180 of file device_image_impl.hpp.
get_spec_const_blob_ref()
std::vector<unsigned char>& cl::sycl::detail::device_image_impl::get_spec_const_blob_ref () inline noexcept
Definition at line 190 of file device_image_impl.hpp.
get_spec_const_buffer_ref()
RT::PiMem& cl::sycl::detail::device_image_impl::get_spec_const_buffer_ref () inline noexcept
Definition at line 194 of file device_image_impl.hpp.
References cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::memBufferCreateHelper(), PI_MEM_FLAGS_ACCESS_RW, and PI_MEM_FLAGS_HOST_PTR_COPY.
get_spec_const_data_lock()
std::mutex& cl::sycl::detail::device_image_impl::get_spec_const_data_lock () inline noexcept
Definition at line 216 of file device_image_impl.hpp.
get_spec_const_data_ref()
const SpecConstMapT& cl::sycl::detail::device_image_impl::get_spec_const_data_ref () const inline noexcept
Definition at line 212 of file device_image_impl.hpp.
get_specialization_constant_raw_value()
void cl::sycl::detail::device_image_impl::get_specialization_constant_raw_value (const char * SpecName, void * ValueRet) const inline noexcept
Definition at line 137 of file device_image_impl.hpp.
References cl::sycl::detail::memcpy().
get_state()
bundle_state cl::sycl::detail::device_image_impl::get_state () const inline noexcept
Definition at line 168 of file device_image_impl.hpp.
getNative()
pi_native_handle cl::sycl::detail::device_image_impl::getNative () const inline
Definition at line 220 of file device_image_impl.hpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::getSyclObjImpl(), and piextProgramGetNativeHandle().
has_kernel() [1/2]
bool cl::sycl::detail::device_image_impl::has_kernel (const kernel_id & KernelIDCand) const inline noexcept
Definition at line 78 of file device_image_impl.hpp.
has_kernel() [2/2]
bool cl::sycl::detail::device_image_impl::has_kernel (const kernel_id & KernelIDCand, const device & DeviceCand) const inline noexcept
Definition at line 83 of file device_image_impl.hpp.
has_specialization_constant()
bool cl::sycl::detail::device_image_impl::has_specialization_constant (const char * SpecName) const inline noexcept
Definition at line 109 of file device_image_impl.hpp.
has_specialization_constants()
bool cl::sycl::detail::device_image_impl::has_specialization_constants () const inline noexcept
Definition at line 96 of file device_image_impl.hpp.
is_specialization_constant_set()
bool cl::sycl::detail::device_image_impl::is_specialization_constant_set (const char * SpecName) const inline noexcept
Definition at line 155 of file device_image_impl.hpp.
set_specialization_constant_raw_value()
void cl::sycl::detail::device_image_impl::set_specialization_constant_raw_value (const char * SpecName, const void * Value) inline noexcept
Definition at line 117 of file device_image_impl.hpp.
References cl::sycl::detail::memcpy().
set_state()
void cl::sycl::detail::device_image_impl::set_state (bundle_state NewState) inline noexcept
Definition at line 170 of file device_image_impl.hpp.
The documentation for this class was generated from the following file:
source/detail/device_image_impl.hpp