DPC++ Runtime: sycl::_V1::h_item< Dimensions > Class Template Reference
sycl::_V1::h_item< Dimensions > Class Template Reference
DPC++ User API
Identifies an instance of a group::parallel_for_work_item function object executing at each point in a local range passed to a parallel_for_work_item call or to the corresponding parallel_for_work_group call.
#include <sycl/h_item.hpp>
Public Member Functions
h_item ()=delete
h_item (const h_item &hi)=default
h_item & operator= (const h_item &hi)=default
item< Dimensions, false > get_global () const
item< Dimensions, false > get_local () const
item< Dimensions, false > get_logical_local () const
item< Dimensions, false > get_physical_local () const
range< Dimensions > get_global_range () const
size_t get_global_range (int Dimension) const
id< Dimensions > get_global_id () const
size_t get_global_id (int Dimension) const
range< Dimensions > get_local_range () const
size_t get_local_range (int Dimension) const
id< Dimensions > get_local_id () const
size_t get_local_id (int Dimension) const
range< Dimensions > get_logical_local_range () const
size_t get_logical_local_range (int Dimension) const
id< Dimensions > get_logical_local_id () const
size_t get_logical_local_id (int Dimension) const
range< Dimensions > get_physical_local_range () const
size_t get_physical_local_range (int Dimension) const
id< Dimensions > get_physical_local_id () const
size_t get_physical_local_id (int Dimension) const
bool operator== (const h_item &rhs) const
bool operator!= (const h_item &rhs) const
Static Public Attributes
static constexpr int dimensions = Dimensions
Protected Member Functions
h_item (const item< Dimensions, false > &GL, const item< Dimensions, false > &L, const range< Dimensions > &flexLocalRange)
h_item (const item< Dimensions, false > &GL, const item< Dimensions, false > &L)
void setLogicalLocalID (const id< Dimensions > &ID)
Friends
class detail::Builder
class group< Dimensions >
Detailed Description
template<int Dimensions>
class sycl::_V1::h_item< Dimensions >
Identifies an instance of a group::parallel_for_work_item function object executing at each point in a local range passed to a parallel_for_work_item call or to the corresponding parallel_for_work_group call.
Definition at line 31 of file h_item.hpp.
Constructor & Destructor Documentation
h_item() [1/4]
template<int Dimensions> sycl::_V1::h_item< Dimensions >::h_item () delete
h_item() [2/4]
template<int Dimensions> sycl::_V1::h_item< Dimensions >::h_item (const h_item< Dimensions > & hi) default
h_item() [3/4]
template<int Dimensions> sycl::_V1::h_item< Dimensions >::h_item (const item< Dimensions, false > & GL, const item< Dimensions, false > & L, const range< Dimensions > & flexLocalRange) inline protected
Definition at line 118 of file h_item.hpp.
h_item() [4/4]
template<int Dimensions> sycl::_V1::h_item< Dimensions >::h_item (const item< Dimensions, false > & GL, const item< Dimensions, false > & L) inline protected
Definition at line 124 of file h_item.hpp.
Member Function Documentation
get_global()
template<int Dimensions> item<Dimensions, false> sycl::_V1::h_item< Dimensions >::get_global () const inline
Definition at line 42 of file h_item.hpp.
Referenced by sycl::_V1::h_item< Dimensions >::get_global_id(), sycl::_V1::h_item< Dimensions >::get_global_range(), and sycl::_V1::detail::writeHItem().
get_global_id() [1/2]
template<int Dimensions> id<Dimensions> sycl::_V1::h_item< Dimensions >::get_global_id () const inline
Definition at line 58 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_global(), and sycl::_V1::item< Dimensions, with_offset >::get_id().
get_global_id() [2/2]
template<int Dimensions> size_t sycl::_V1::h_item< Dimensions >::get_global_id (int Dimension) const inline
Definition at line 60 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_global(), and sycl::_V1::item< Dimensions, with_offset >::get_id().
get_global_range() [1/2]
template<int Dimensions> range<Dimensions> sycl::_V1::h_item< Dimensions >::get_global_range () const inline
Definition at line 50 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_global(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
get_global_range() [2/2]
template<int Dimensions> size_t sycl::_V1::h_item< Dimensions >::get_global_range (int Dimension) const inline
Definition at line 54 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_global(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
get_local()
template<int Dimensions> item<Dimensions, false> sycl::_V1::h_item< Dimensions >::get_local () const inline
Definition at line 44 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_logical_local().
Referenced by sycl::_V1::h_item< Dimensions >::get_local_id(), and sycl::_V1::h_item< Dimensions >::get_local_range().
get_local_id() [1/2]
template<int Dimensions> id<Dimensions> sycl::_V1::h_item< Dimensions >::get_local_id () const inline
Definition at line 70 of file h_item.hpp.
References sycl::_V1::item< Dimensions, with_offset >::get_id(), and sycl::_V1::h_item< Dimensions >::get_local().
get_local_id() [2/2]
template<int Dimensions> size_t sycl::_V1::h_item< Dimensions >::get_local_id (int Dimension) const inline
Definition at line 72 of file h_item.hpp.
References sycl::_V1::item< Dimensions, with_offset >::get_id(), and sycl::_V1::h_item< Dimensions >::get_local().
get_local_range() [1/2]
template<int Dimensions> range<Dimensions> sycl::_V1::h_item< Dimensions >::get_local_range () const inline
Definition at line 64 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_local(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
get_local_range() [2/2]
template<int Dimensions> size_t sycl::_V1::h_item< Dimensions >::get_local_range (int Dimension) const inline
Definition at line 66 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_local(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
get_logical_local()
template<int Dimensions> item<Dimensions, false> sycl::_V1::h_item< Dimensions >::get_logical_local () const inline
Definition at line 46 of file h_item.hpp.
Referenced by sycl::_V1::h_item< Dimensions >::get_local(), sycl::_V1::h_item< Dimensions >::get_logical_local_id(), sycl::_V1::h_item< Dimensions >::get_logical_local_range(), and sycl::_V1::detail::writeHItem().
get_logical_local_id() [1/2]
template<int Dimensions> id<Dimensions> sycl::_V1::h_item< Dimensions >::get_logical_local_id () const inline
Definition at line 84 of file h_item.hpp.
References sycl::_V1::item< Dimensions, with_offset >::get_id(), and sycl::_V1::h_item< Dimensions >::get_logical_local().
get_logical_local_id() [2/2]
template<int Dimensions> size_t sycl::_V1::h_item< Dimensions >::get_logical_local_id (int Dimension) const inline
Definition at line 88 of file h_item.hpp.
References sycl::_V1::item< Dimensions, with_offset >::get_id(), and sycl::_V1::h_item< Dimensions >::get_logical_local().
get_logical_local_range() [1/2]
template<int Dimensions> range<Dimensions> sycl::_V1::h_item< Dimensions >::get_logical_local_range () const inline
Definition at line 76 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_logical_local(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
get_logical_local_range() [2/2]
template<int Dimensions> size_t sycl::_V1::h_item< Dimensions >::get_logical_local_range (int Dimension) const inline
Definition at line 80 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_logical_local(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
get_physical_local()
template<int Dimensions> item<Dimensions, false> sycl::_V1::h_item< Dimensions >::get_physical_local () const inline
Definition at line 48 of file h_item.hpp.
Referenced by sycl::_V1::h_item< Dimensions >::get_physical_local_id(), sycl::_V1::h_item< Dimensions >::get_physical_local_range(), and sycl::_V1::detail::writeHItem().
get_physical_local_id() [1/2]
template<int Dimensions> id<Dimensions> sycl::_V1::h_item< Dimensions >::get_physical_local_id () const inline
Definition at line 100 of file h_item.hpp.
References sycl::_V1::item< Dimensions, with_offset >::get_id(), and sycl::_V1::h_item< Dimensions >::get_physical_local().
get_physical_local_id() [2/2]
template<int Dimensions> size_t sycl::_V1::h_item< Dimensions >::get_physical_local_id (int Dimension) const inline
Definition at line 104 of file h_item.hpp.
References sycl::_V1::item< Dimensions, with_offset >::get_id(), and sycl::_V1::h_item< Dimensions >::get_physical_local().
get_physical_local_range() [1/2]
template<int Dimensions> range<Dimensions> sycl::_V1::h_item< Dimensions >::get_physical_local_range () const inline
Definition at line 92 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_physical_local(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
get_physical_local_range() [2/2]
template<int Dimensions> size_t sycl::_V1::h_item< Dimensions >::get_physical_local_range (int Dimension) const inline
Definition at line 96 of file h_item.hpp.
References sycl::_V1::h_item< Dimensions >::get_physical_local(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
operator!=()
template<int Dimensions> bool sycl::_V1::h_item< Dimensions >::operator!= (const h_item< Dimensions > & rhs) const inline
Definition at line 113 of file h_item.hpp.
operator=()
template<int Dimensions> h_item& sycl::_V1::h_item< Dimensions >::operator= (const h_item< Dimensions > & hi) default
operator==()
template<int Dimensions> bool sycl::_V1::h_item< Dimensions >::operator== (const h_item< Dimensions > & rhs) const inline
Definition at line 108 of file h_item.hpp.
setLogicalLocalID()
template<int Dimensions> void sycl::_V1::h_item< Dimensions >::setLogicalLocalID (const id< Dimensions > & ID) inline protected
Definition at line 129 of file h_item.hpp.
References sycl::_V1::detail::Builder::updateItemIndex().
Friends And Related Function Documentation
detail::Builder
template<int Dimensions> friend class detail::Builder friend
Definition at line 116 of file h_item.hpp.
group< Dimensions >
template<int Dimensions> friend class group< Dimensions > friend
Definition at line 116 of file h_item.hpp.
Member Data Documentation
dimensions
template<int Dimensions> constexpr int sycl::_V1::h_item< Dimensions >::dimensions = Dimensions static constexpr
Definition at line 33 of file h_item.hpp.
The documentation for this class was generated from the following files:
include/sycl/detail/helpers.hpp
include/sycl/h_item.hpp