DPC++ Runtime: cl::sycl::detail::stream_impl Class Reference
cl::sycl::detail::stream_impl Class Reference
#include <detail/stream_impl.hpp>
Public Member Functions
stream_impl (size_t BufferSize, size_t MaxStatementSize, handler &CGH)
stream_impl (size_t BufferSize, size_t MaxStatementSize, const property_list &PropList)
GlobalBufAccessorT accessGlobalBuf (handler &CGH)
GlobalBufAccessorT accessGlobalFlushBuf (handler &CGH)
GlobalOffsetAccessorT accessGlobalOffset (handler &CGH)
void flush ()
size_t get_size () const
size_t get_max_statement_size () const
template<typename propertyT >
bool has_property () const noexcept
template<typename propertyT >
propertyT get_property () const
Detailed Description
Definition at line 25 of file stream_impl.hpp.
Constructor & Destructor Documentation
stream_impl() [1/2]
cl::sycl::detail::stream_impl::stream_impl (size_t BufferSize, size_t MaxStatementSize, handler & CGH)
Definition at line 19 of file stream_impl.cpp.
stream_impl() [2/2]
cl::sycl::detail::stream_impl::stream_impl (size_t BufferSize, size_t MaxStatementSize, const property_list & PropList)
Definition at line 25 of file stream_impl.cpp.
References cl::sycl::detail::Scheduler::allocateStreamBuffers(), cl::sycl::detail::FLUSH_BUF_OFFSET_SIZE, and cl::sycl::detail::Scheduler::getInstance().
Member Function Documentation
accessGlobalBuf()
GlobalBufAccessorT cl::sycl::detail::stream_impl::accessGlobalBuf (handler & CGH)
Definition at line 41 of file stream_impl.cpp.
References cl::sycl::detail::Scheduler::getInstance(), cl::sycl::access::read_write, and cl::sycl::detail::Scheduler::StreamBuffersPool.
accessGlobalFlushBuf()
GlobalBufAccessorT cl::sycl::detail::stream_impl::accessGlobalFlushBuf (handler & CGH)
Definition at line 49 of file stream_impl.cpp.
References cl::sycl::detail::FLUSH_BUF_OFFSET_SIZE, cl::sycl::detail::Scheduler::getInstance(), cl::sycl::access::read_write, and cl::sycl::detail::Scheduler::StreamBuffersPool.
accessGlobalOffset()
GlobalOffsetAccessorT cl::sycl::detail::stream_impl::accessGlobalOffset (handler & CGH)
Definition at line 58 of file stream_impl.cpp.
References cl::sycl::access::atomic, and cl::sycl::detail::Scheduler::getInstance().
flush()
void cl::sycl::detail::stream_impl::flush ()
Definition at line 71 of file stream_impl.cpp.
References cl::sycl::detail::Scheduler::getInstance(), cl::sycl::access::host_buffer, cl::sycl::ext::oneapi::experimental::printf(), cl::sycl::access::read_write, and cl::sycl::detail::Scheduler::StreamBuffersPool.
get_max_statement_size()
size_t cl::sycl::detail::stream_impl::get_max_statement_size () const
Definition at line 69 of file stream_impl.cpp.
get_property()
template<typename propertyT > propertyT cl::sycl::detail::stream_impl::get_property () const inline
Definition at line 55 of file stream_impl.hpp.
get_size()
size_t cl::sycl::detail::stream_impl::get_size () const
Definition at line 67 of file stream_impl.cpp.
has_property()
template<typename propertyT > bool cl::sycl::detail::stream_impl::has_property () const inline noexcept
Definition at line 51 of file stream_impl.hpp.
The documentation for this class was generated from the following files:
source/detail/stream_impl.hpp
source/detail/stream_impl.cpp