DPC++ Runtime: cl::sycl::detail::RTDeviceBinaryImage Class Reference
cl::sycl::detail::RTDeviceBinaryImage Class Reference
#include <CL/sycl/detail/device_binary_image.hpp>
Public Member Functions
RTDeviceBinaryImage (OSModuleHandle ModuleHandle)
RTDeviceBinaryImage (pi_device_binary Bin, OSModuleHandle ModuleHandle)
RTDeviceBinaryImage (const RTDeviceBinaryImage &)=delete
RTDeviceBinaryImage & operator= (const RTDeviceBinaryImage &)=delete
RTDeviceBinaryImage (RTDeviceBinaryImage &&)=default
RTDeviceBinaryImage & operator= (RTDeviceBinaryImage &&)=default
OSModuleHandle getOSModuleHandle () const
~RTDeviceBinaryImage () override
bool supportsSpecConstants () const
const pi_device_binary_struct & getRawData () const
void print () const override
Public Member Functions inherited from cl::sycl::detail::pi::DeviceBinaryImage
DeviceBinaryImage (pi_device_binary Bin)
DeviceBinaryImage ()
virtual void dump (std::ostream &Out) const
size_t getSize () const
const char * getCompileOptions () const
const char * getLinkOptions () const
pi::PiDeviceBinaryType getFormat () const
Returns the format of the binary image.
pi_device_binary_property getProperty (const char *PropName) const
Returns a single property from SYCL_MISC_PROP category.
const PropertyRange & getSpecConstants () const
Gets the iterator range over specialization constants in this binary image.
const PropertyRange getSpecConstantsDefaultValues () const
const PropertyRange & getDeviceLibReqMask () const
const PropertyRange & getKernelParamOptInfo () const
const PropertyRange getAssertUsed () const
const PropertyRange & getProgramMetadata () const
const PropertyRange getExportedSymbols () const
const PropertyRange getDeviceGlobals () const
virtual ~DeviceBinaryImage ()
Protected Attributes
OSModuleHandle ModuleHandle
Protected Attributes inherited from cl::sycl::detail::pi::DeviceBinaryImage
pi_device_binary Bin
pi::PiDeviceBinaryType Format = PI_DEVICE_BINARY_TYPE_NONE
DeviceBinaryImage::PropertyRange SpecConstIDMap
DeviceBinaryImage::PropertyRange DeviceLibReqMask
DeviceBinaryImage::PropertyRange KernelParamOptInfo
DeviceBinaryImage::PropertyRange ProgramMetadata
Additional Inherited Members
Protected Member Functions inherited from cl::sycl::detail::pi::DeviceBinaryImage
void init (pi_device_binary Bin)
pi_device_binary get () const
Detailed Description
Definition at line 20 of file device_binary_image.hpp.
Constructor & Destructor Documentation
RTDeviceBinaryImage() [1/4]
cl::sycl::detail::RTDeviceBinaryImage::RTDeviceBinaryImage (OSModuleHandle ModuleHandle) inline
Definition at line 22 of file device_binary_image.hpp.
RTDeviceBinaryImage() [2/4]
cl::sycl::detail::RTDeviceBinaryImage::RTDeviceBinaryImage (pi_device_binary Bin, OSModuleHandle ModuleHandle) inline
Definition at line 24 of file device_binary_image.hpp.
RTDeviceBinaryImage() [3/4]
cl::sycl::detail::RTDeviceBinaryImage::RTDeviceBinaryImage (const RTDeviceBinaryImage &) delete
RTDeviceBinaryImage() [4/4]
cl::sycl::detail::RTDeviceBinaryImage::RTDeviceBinaryImage (RTDeviceBinaryImage &&) default
~RTDeviceBinaryImage()
cl::sycl::detail::RTDeviceBinaryImage::~RTDeviceBinaryImage () inline override
Definition at line 36 of file device_binary_image.hpp.
Member Function Documentation
getOSModuleHandle()
OSModuleHandle cl::sycl::detail::RTDeviceBinaryImage::getOSModuleHandle () const inline
Definition at line 34 of file device_binary_image.hpp.
getRawData()
const pi_device_binary_struct& cl::sycl::detail::RTDeviceBinaryImage::getRawData () const inline
Definition at line 42 of file device_binary_image.hpp.
References std::get().
Referenced by cl::sycl::detail::compatibleWithDevice(), cl::sycl::detail::ProgramManager::createPIProgram(), cl::sycl::detail::ProgramManager::flushSpecConstants(), cl::sycl::detail::getBinImageState(), and cl::sycl::detail::PersistentDeviceCodeCache::getCacheItemPath().
operator=() [1/2]
RTDeviceBinaryImage& cl::sycl::detail::RTDeviceBinaryImage::operator= (const RTDeviceBinaryImage &) delete
operator=() [2/2]
RTDeviceBinaryImage& cl::sycl::detail::RTDeviceBinaryImage::operator= (RTDeviceBinaryImage &&) default
print()
void cl::sycl::detail::RTDeviceBinaryImage::print () const inline override virtual
Reimplemented from cl::sycl::detail::pi::DeviceBinaryImage.
Reimplemented in cl::sycl::detail::DynRTDeviceBinaryImage.
Definition at line 44 of file device_binary_image.hpp.
References cl::sycl::detail::pi::print().
supportsSpecConstants()
bool cl::sycl::detail::RTDeviceBinaryImage::supportsSpecConstants () const inline
Definition at line 38 of file device_binary_image.hpp.
References PI_DEVICE_BINARY_TYPE_SPIRV.
Referenced by cl::sycl::detail::ProgramManager::flushSpecConstants(), and cl::sycl::detail::ProgramManager::getBuiltPIProgram().
Member Data Documentation
ModuleHandle
OSModuleHandle cl::sycl::detail::RTDeviceBinaryImage::ModuleHandle protected
Definition at line 50 of file device_binary_image.hpp.
The documentation for this class was generated from the following file:
include/CL/sycl/detail/device_binary_image.hpp