DPC++ Runtime: sycl::_V1::detail::string Class Reference
sycl::_V1::detail::string Class Reference
#include <sycl/detail/string.hpp>
Public Member Functions
string () noexcept=default
~string ()
string (std::string_view strn)
string (string &&other) noexcept
string (const string &other)
string & operator= (string &&other) noexcept
string & operator= (const string &other)
string & operator= (std::string_view strn)
const char * c_str () const noexcept
Friends
void swap (string &lhs, string &rhs) noexcept
bool operator== (const string &lhs, std::string_view rhs) noexcept
bool operator== (std::string_view lhs, const string &rhs) noexcept
Detailed Description
Definition at line 21 of file string.hpp.
Constructor & Destructor Documentation
string() [1/4]
sycl::_V1::detail::string::string () default noexcept
~string()
sycl::_V1::detail::string::~string () inline
Definition at line 26 of file string.hpp.
string() [2/4]
sycl::_V1::detail::string::string (std::string_view strn) inline
Definition at line 28 of file string.hpp.
string() [3/4]
sycl::_V1::detail::string::string (string && other) inline noexcept
Definition at line 39 of file string.hpp.
References swap.
string() [4/4]
sycl::_V1::detail::string::string (const string & other) inline
Definition at line 40 of file string.hpp.
Member Function Documentation
c_str()
const char* sycl::_V1::detail::string::c_str () const inline noexcept
Definition at line 60 of file string.hpp.
Referenced by sycl::_V1::detail::queue_impl::submit_impl().
operator=() [1/3]
string& sycl::_V1::detail::string::operator= (const string & other) inline
Definition at line 50 of file string.hpp.
operator=() [2/3]
string& sycl::_V1::detail::string::operator= (std::string_view strn) inline
Definition at line 55 of file string.hpp.
operator=() [3/3]
string& sycl::_V1::detail::string::operator= (string && other) inline noexcept
Definition at line 46 of file string.hpp.
References swap.
Friends And Related Function Documentation
operator== [1/2]
bool operator== (const string & lhs, std::string_view rhs) friend
Definition at line 62 of file string.hpp.
operator== [2/2]
bool operator== (std::string_view lhs, const string & rhs) friend
Definition at line 65 of file string.hpp.
swap
void swap (string & lhs, string & rhs) friend
Definition at line 35 of file string.hpp.
Referenced by operator=(), and string().
The documentation for this class was generated from the following file:
include/sycl/detail/string.hpp