DPC++ Runtime: sycl::_V1::detail::image_common< Dimensions, AllocatorT > Class Template Reference
sycl::_V1::detail::image_common< Dimensions, AllocatorT > Class Template Reference
#include <sycl/image.hpp>
Public Member Functions
template<typename propertyT >
bool has_property () const noexcept
template<typename propertyT >
propertyT get_property () const
range< Dimensions > get_range () const
template<bool IsMultiDim = (Dimensions > 1)>
std::enable_if_t< IsMultiDim, range< Dimensions - 1 > > get_pitch () const
size_t size () const noexcept
AllocatorT get_allocator () const
Protected Member Functions
image_plain (const std::shared_ptr< detail::image_impl > &Impl)
image_plain (image_channel_order Order, image_channel_type Type, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (image_channel_order Order, image_channel_type Type, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (void *HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const void *HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (void *HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const std::shared_ptr< const void > &HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList, bool IsConstPtr)
image_plain (const std::shared_ptr< const void > &HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList, bool IsConstPtr)
image_plain (const void *HostPointer, image_channel_order Order, image_channel_type Type, image_sampler Sampler, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const void *HostPointer, image_channel_order Order, image_channel_type Type, image_sampler Sampler, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const std::shared_ptr< const void > &HostPointer, image_channel_order Order, image_channel_type Type, image_sampler Sampler, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const std::shared_ptr< const void > &HostPointer, image_channel_order Order, image_channel_type Type, image_sampler Sampler, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (pi_native_handle MemObject, const context &SyclContext, event AvailableEvent, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, image_channel_order Order, image_channel_type Type, bool OwnNativeHandle, range< 3 > Range3WithOnes)
Protected Member Functions inherited from sycl::_V1::detail::image_plain
image_plain (const std::shared_ptr< detail::image_impl > &Impl)
image_plain (image_channel_order Order, image_channel_type Type, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (image_channel_order Order, image_channel_type Type, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (void *HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const void *HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (void *HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const std::shared_ptr< const void > &HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList, bool IsConstPtr)
image_plain (const std::shared_ptr< const void > &HostPointer, image_channel_order Order, image_channel_type Type, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList, bool IsConstPtr)
image_plain (const void *HostPointer, image_channel_order Order, image_channel_type Type, image_sampler Sampler, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const void *HostPointer, image_channel_order Order, image_channel_type Type, image_sampler Sampler, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const std::shared_ptr< const void > &HostPointer, image_channel_order Order, image_channel_type Type, image_sampler Sampler, const range< 3 > &Range, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (const std::shared_ptr< const void > &HostPointer, image_channel_order Order, image_channel_type Type, image_sampler Sampler, const range< 3 > &Range, const range< 2 > &Pitch, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, const property_list &PropList)
image_plain (pi_native_handle MemObject, const context &SyclContext, event AvailableEvent, std::unique_ptr< SYCLMemObjAllocator > Allocator, uint8_t Dimensions, image_channel_order Order, image_channel_type Type, bool OwnNativeHandle, range< 3 > Range3WithOnes)
template<typename propertyT >
bool has_property () const noexcept
template<typename propertyT >
propertyT get_property () const
range< 3 > get_range () const
range< 2 > get_pitch () const
size_t get_size () const noexcept
size_t get_count () const noexcept
void set_final_data_internal ()
void set_final_data_internal (const std::function< void(const std::function< void(void *const Ptr)> &)> &FinalDataFunc)
void set_write_back (bool flag)
const std::unique_ptr< SYCLMemObjAllocator > & get_allocator_internal () const
size_t getElementSize () const
size_t getRowPitch () const
size_t getSlicePitch () const
image_sampler getSampler () const noexcept
image_channel_order getChannelOrder () const
image_channel_type getChannelType () const
void sampledImageConstructorNotification (const detail::code_location &CodeLoc, void *UserObj, const void *HostObj, uint32_t Dim, size_t Range[3], image_format Format, const image_sampler &Sampler)
void sampledImageDestructorNotification (void *UserObj)
void unsampledImageConstructorNotification (const detail::code_location &CodeLoc, void *UserObj, const void *HostObj, uint32_t Dim, size_t Range[3], image_format Format)
void unsampledImageDestructorNotification (void *UserObj)
Additional Inherited Members
Protected Attributes inherited from sycl::_V1::detail::image_plain
std::shared_ptr< detail::image_impl > impl
Detailed Description
template<int Dimensions, typename AllocatorT>
class sycl::_V1::detail::image_common< Dimensions, AllocatorT >
Definition at line 308 of file image.hpp.
Member Function Documentation
get_allocator()
template<int Dimensions, typename AllocatorT > AllocatorT sycl::_V1::detail::image_common< Dimensions, AllocatorT >::get_allocator () const inline
Definition at line 338 of file image.hpp.
References sycl::_V1::detail::image_plain::get_allocator_internal().
get_pitch()
template<int Dimensions, typename AllocatorT > template<bool IsMultiDim = (Dimensions > 1)> std::enable_if_t<IsMultiDim, range<Dimensions - 1> > sycl::_V1::detail::image_common< Dimensions, AllocatorT >::get_pitch () const inline
Definition at line 330 of file image.hpp.
References sycl::_V1::detail::convertToArrayOfN(), sycl::_V1::Dimensions, and sycl::_V1::detail::image_plain::get_pitch().
get_property()
template<int Dimensions, typename AllocatorT > template<typename propertyT > propertyT sycl::_V1::detail::image_common< Dimensions, AllocatorT >::get_property () const inline
Definition at line 319 of file image.hpp.
get_range()
template<int Dimensions, typename AllocatorT > range<Dimensions> sycl::_V1::detail::image_common< Dimensions, AllocatorT >::get_range () const inline
Definition at line 323 of file image.hpp.
References sycl::_V1::detail::image_plain::get_range().
has_property()
template<int Dimensions, typename AllocatorT > template<typename propertyT > bool sycl::_V1::detail::image_common< Dimensions, AllocatorT >::has_property () const inline noexcept
Definition at line 315 of file image.hpp.
image_plain() [1/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 211 of file image.cpp.
image_plain() [2/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 204 of file image.cpp.
image_plain() [3/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 236 of file image.cpp.
image_plain() [4/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 230 of file image.cpp.
image_plain() [5/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain inline protected
Definition at line 176 of file image.hpp.
image_plain() [6/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 193 of file image.cpp.
image_plain() [7/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 224 of file image.cpp.
References sycl::_V1::detail::image_plain::impl.
image_plain() [8/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 218 of file image.cpp.
References sycl::_V1::detail::image_plain::impl.
image_plain() [9/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 183 of file image.cpp.
image_plain() [10/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 178 of file image.cpp.
References sycl::_V1::detail::image_plain::impl.
image_plain() [11/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 250 of file image.cpp.
image_plain() [12/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 198 of file image.cpp.
image_plain() [13/13]
template<int Dimensions, typename AllocatorT > sycl::_V1::detail::image_plain::image_plain protected
Definition at line 188 of file image.cpp.
size()
template<int Dimensions, typename AllocatorT > size_t sycl::_V1::detail::image_common< Dimensions, AllocatorT >::size () const inline noexcept
Definition at line 335 of file image.hpp.
References sycl::_V1::detail::image_plain::get_count().
The documentation for this class was generated from the following file:
include/sycl/image.hpp