DPC++ Runtime: sycl::_V1::detail::MemoryManager Class Reference
sycl::_V1::detail::MemoryManager Class Reference
#include <detail/memory_manager.hpp>
Static Public Member Functions
static void release (ContextImplPtr TargetContext, SYCLMemObjI *MemObj, void *MemAllocation, std::vector< EventImplPtr > DepEvents, sycl::detail::pi::PiEvent &OutEvent)
static void * allocate (ContextImplPtr TargetContext, SYCLMemObjI *MemObj, bool InitFromUserData, void *HostPtr, std::vector< EventImplPtr > DepEvents, sycl::detail::pi::PiEvent &OutEvent)
static void * allocateMemSubBuffer (ContextImplPtr TargetContext, void *ParentMemObj, size_t ElemSize, size_t Offset, range< 3 > Range, std::vector< EventImplPtr > DepEvents, sycl::detail::pi::PiEvent &OutEvent)
static void * allocateMemBuffer (ContextImplPtr TargetContext, SYCLMemObjI *MemObj, void *UserPtr, bool HostPtrReadOnly, size_t Size, const EventImplPtr &InteropEvent, const ContextImplPtr &InteropContext, const sycl::property_list &PropsList, sycl::detail::pi::PiEvent &OutEventToWait)
static void * allocateMemImage (ContextImplPtr TargetContext, SYCLMemObjI *MemObj, void *UserPtr, bool HostPtrReadOnly, size_t Size, const sycl::detail::pi::PiMemImageDesc &Desc, const sycl::detail::pi::PiMemImageFormat &Format, const EventImplPtr &InteropEvent, const ContextImplPtr &InteropContext, const sycl::property_list &PropsList, sycl::detail::pi::PiEvent &OutEventToWait)
static void releaseMemObj (ContextImplPtr TargetContext, SYCLMemObjI *MemObj, void *MemAllocation, void *UserPtr)
static void * allocateHostMemory (SYCLMemObjI *MemObj, void *UserPtr, bool HostPtrReadOnly, size_t Size, const sycl::property_list &PropsList)
static void * allocateInteropMemObject (ContextImplPtr TargetContext, void *UserPtr, const EventImplPtr &InteropEvent, const ContextImplPtr &InteropContext, const sycl::property_list &PropsList, sycl::detail::pi::PiEvent &OutEventToWait)
static void * allocateImageObject (ContextImplPtr TargetContext, void *UserPtr, bool HostPtrReadOnly, const sycl::detail::pi::PiMemImageDesc &Desc, const sycl::detail::pi::PiMemImageFormat &Format, const sycl::property_list &PropsList)
static void * allocateBufferObject (ContextImplPtr TargetContext, void *UserPtr, bool HostPtrReadOnly, const size_t Size, const sycl::property_list &PropsList)
static void copy (SYCLMemObjI *SYCLMemObj, void *SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, void *DstMem, QueueImplPtr TgtQueue, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent, const detail::EventImplPtr &OutEventImpl)
static void copy (SYCLMemObjI *SYCLMemObj, void *SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, void *DstMem, QueueImplPtr TgtQueue, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent)
static void fill (SYCLMemObjI *SYCLMemObj, void *Mem, QueueImplPtr Queue, size_t PatternSize, const char *Pattern, unsigned int Dim, sycl::range< 3 > Size, sycl::range< 3 > AccessRange, sycl::id< 3 > AccessOffset, unsigned int ElementSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent, const detail::EventImplPtr &OutEventImpl)
static void fill (SYCLMemObjI *SYCLMemObj, void *Mem, QueueImplPtr Queue, size_t PatternSize, const char *Pattern, unsigned int Dim, sycl::range< 3 > Size, sycl::range< 3 > AccessRange, sycl::id< 3 > AccessOffset, unsigned int ElementSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent)
static void * map (SYCLMemObjI *SYCLMemObj, void *Mem, QueueImplPtr Queue, access::mode AccessMode, unsigned int Dim, sycl::range< 3 > Size, sycl::range< 3 > AccessRange, sycl::id< 3 > AccessOffset, unsigned int ElementSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent)
static void unmap (SYCLMemObjI *SYCLMemObj, void *Mem, QueueImplPtr Queue, void *MappedPtr, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent)
static void copy_usm (const void *SrcMem, QueueImplPtr Queue, size_t Len, void *DstMem, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void copy_usm (const void *SrcMem, QueueImplPtr Queue, size_t Len, void *DstMem, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void fill_usm (void *DstMem, QueueImplPtr Queue, size_t Len, const std::vector< char > &Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void fill_usm (void *DstMem, QueueImplPtr Queue, size_t Len, int Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void fill_usm (void *DstMem, QueueImplPtr Queue, size_t Len, int Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void prefetch_usm (void *Ptr, QueueImplPtr Queue, size_t Len, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void prefetch_usm (void *Ptr, QueueImplPtr Queue, size_t Len, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void advise_usm (const void *Ptr, QueueImplPtr Queue, size_t Len, pi_mem_advice Advice, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void advise_usm (const void *Ptr, QueueImplPtr Queue, size_t Len, pi_mem_advice Advice, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void copy_2d_usm (const void *SrcMem, size_t SrcPitch, QueueImplPtr Queue, void *DstMem, size_t DstPitch, size_t Width, size_t Height, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void copy_2d_usm (const void *SrcMem, size_t SrcPitch, QueueImplPtr Queue, void *DstMem, size_t DstPitch, size_t Width, size_t Height, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void fill_2d_usm (void *DstMem, QueueImplPtr Queue, size_t Pitch, size_t Width, size_t Height, const std::vector< char > &Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void fill_2d_usm (void *DstMem, QueueImplPtr Queue, size_t Pitch, size_t Width, size_t Height, const std::vector< char > &Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void memset_2d_usm (void *DstMem, QueueImplPtr Queue, size_t Pitch, size_t Width, size_t Height, char Value, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void memset_2d_usm (void *DstMem, QueueImplPtr Queue, size_t Pitch, size_t Width, size_t Height, char Value, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void copy_to_device_global (const void *DeviceGlobalPtr, bool IsDeviceImageScoped, QueueImplPtr Queue, size_t NumBytes, size_t Offset, const void *SrcMem, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void copy_to_device_global (const void *DeviceGlobalPtr, bool IsDeviceImageScoped, QueueImplPtr Queue, size_t NumBytes, size_t Offset, const void *SrcMem, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void copy_from_device_global (const void *DeviceGlobalPtr, bool IsDeviceImageScoped, QueueImplPtr Queue, size_t NumBytes, size_t Offset, void *DstMem, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void copy_from_device_global (const void *DeviceGlobalPtr, bool IsDeviceImageScoped, QueueImplPtr Queue, size_t NumBytes, size_t Offset, void *DstMem, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void ext_oneapi_copyD2D_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, SYCLMemObjI *SYCLMemObj, void *SrcMem, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, void *DstMem, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint)
static void ext_oneapi_copyD2H_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, SYCLMemObjI *SYCLMemObj, void *SrcMem, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char *DstMem, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint)
static void ext_oneapi_copyH2D_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, SYCLMemObjI *SYCLMemObj, char *SrcMem, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, void *DstMem, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint)
static void ext_oneapi_copy_usm_cmd_buffer (ContextImplPtr Context, const void *SrcMem, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, size_t Len, void *DstMem, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint)
static void ext_oneapi_fill_usm_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, void *DstMem, size_t Len, const std::vector< char > &Pattern, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint)
static void ext_oneapi_fill_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, SYCLMemObjI *SYCLMemObj, void *Mem, size_t PatternSize, const char *Pattern, unsigned int Dim, sycl::range< 3 > Size, sycl::range< 3 > AccessRange, sycl::id< 3 > AccessOffset, unsigned int ElementSize, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint)
static void ext_oneapi_prefetch_usm_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, void *Mem, size_t Length, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint)
static void ext_oneapi_advise_usm_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, const void *Mem, size_t Length, pi_mem_advice Advice, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint)
static void copy_image_bindless (void *Src, QueueImplPtr Queue, void *Dst, const sycl::detail::pi::PiMemImageDesc &Desc, const sycl::detail::pi::PiMemImageFormat &Format, const sycl::detail::pi::PiImageCopyFlags Flags, sycl::detail::pi::PiImageOffset SrcOffset, sycl::detail::pi::PiImageOffset DstOffset, sycl::detail::pi::PiImageRegion CopyExtent, sycl::detail::pi::PiImageRegion HostExtent, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent)
Detailed Description
Definition at line 36 of file memory_manager.hpp.
Member Function Documentation
advise_usm() [1/2]
void sycl::_V1::detail::MemoryManager::advise_usm (const void * Ptr, QueueImplPtr Queue, size_t Len, pi_mem_advice Advice, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1077 of file memory_manager.cpp.
advise_usm() [2/2]
void sycl::_V1::detail::MemoryManager::advise_usm (const void * Ptr, QueueImplPtr Queue, size_t Len, pi_mem_advice Advice, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1061 of file memory_manager.cpp.
References piextUSMEnqueueMemAdvise().
Referenced by sycl::_V1::detail::queue_impl::mem_advise().
allocate()
void * sycl::_V1::detail::MemoryManager::allocate (ContextImplPtr TargetContext, SYCLMemObjI * MemObj, bool InitFromUserData, void * HostPtr, std::vector< EventImplPtr > DepEvents, sycl::detail::pi::PiEvent & OutEvent) static
Definition at line 278 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::allocateMem(), and sycl::_V1::detail::waitForEvents().
allocateBufferObject()
void * sycl::_V1::detail::MemoryManager::allocateBufferObject (ContextImplPtr TargetContext, void * UserPtr, bool HostPtrReadOnly, const size_t Size, const sycl::property_list & PropsList) static
Definition at line 350 of file memory_manager.cpp.
References sycl::_V1::property_list::get_property(), sycl::_V1::detail::getMemObjCreationFlags(), sycl::_V1::property_list::has_property(), sycl::_V1::detail::memBufferCreateHelper(), PI_MEM_FLAGS_HOST_PTR_ALLOC, PI_MEM_PROPERTIES_ALLOC_BUFFER_LOCATION, and PI_MEM_PROPERTIES_CHANNEL.
Referenced by allocateMemBuffer().
allocateHostMemory()
void * sycl::_V1::detail::MemoryManager::allocateHostMemory (SYCLMemObjI * MemObj, void * UserPtr, bool HostPtrReadOnly, size_t Size, const sycl::property_list & PropsList) static
Definition at line 291 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::allocateHostMem().
Referenced by allocateMemBuffer(), and allocateMemImage().
allocateImageObject()
void * sycl::_V1::detail::MemoryManager::allocateImageObject (ContextImplPtr TargetContext, void * UserPtr, bool HostPtrReadOnly, const sycl::detail::pi::PiMemImageDesc & Desc, const sycl::detail::pi::PiMemImageFormat & Format, const sycl::property_list & PropsList) static
Definition at line 333 of file memory_manager.cpp.
References sycl::_V1::detail::getMemObjCreationFlags(), and piMemImageCreate().
Referenced by allocateMemImage().
allocateInteropMemObject()
void * sycl::_V1::detail::MemoryManager::allocateInteropMemObject (ContextImplPtr TargetContext, void * UserPtr, const EventImplPtr & InteropEvent, const ContextImplPtr & InteropContext, const sycl::property_list & PropsList, sycl::detail::pi::PiEvent & OutEventToWait) static
Definition at line 305 of file memory_manager.cpp.
References piEventRetain().
Referenced by allocateMemBuffer(), and allocateMemImage().
allocateMemBuffer()
void * sycl::_V1::detail::MemoryManager::allocateMemBuffer (ContextImplPtr TargetContext, SYCLMemObjI * MemObj, void * UserPtr, bool HostPtrReadOnly, size_t Size, const EventImplPtr & InteropEvent, const ContextImplPtr & InteropContext, const sycl::property_list & PropsList, sycl::detail::pi::PiEvent & OutEventToWait) static
Definition at line 395 of file memory_manager.cpp.
References allocateBufferObject(), allocateHostMemory(), allocateInteropMemObject(), and sycl::_V1::detail::XPTIRegistry::bufferAssociateNotification().
Referenced by sycl::_V1::detail::buffer_impl::allocateMem().
allocateMemImage()
void * sycl::_V1::detail::MemoryManager::allocateMemImage (ContextImplPtr TargetContext, SYCLMemObjI * MemObj, void * UserPtr, bool HostPtrReadOnly, size_t Size, const sycl::detail::pi::PiMemImageDesc & Desc, const sycl::detail::pi::PiMemImageFormat & Format, const EventImplPtr & InteropEvent, const ContextImplPtr & InteropContext, const sycl::property_list & PropsList, sycl::detail::pi::PiEvent & OutEventToWait) static
Definition at line 415 of file memory_manager.cpp.
References allocateHostMemory(), allocateImageObject(), and allocateInteropMemObject().
Referenced by sycl::_V1::detail::image_impl::allocateMem().
allocateMemSubBuffer()
void * sycl::_V1::detail::MemoryManager::allocateMemSubBuffer (ContextImplPtr TargetContext, void * ParentMemObj, size_t ElemSize, size_t Offset, range< 3 > Range, std::vector< EventImplPtr > DepEvents, sycl::detail::pi::PiEvent & OutEvent) static
Definition at line 433 of file memory_manager.cpp.
References PI_BUFFER_CREATE_TYPE_REGION, PI_MEM_FLAGS_ACCESS_RW, piMemBufferPartition(), and sycl::_V1::detail::waitForEvents().
copy() [1/2]
void sycl::_V1::detail::MemoryManager::copy (SYCLMemObjI * SYCLMemObj, void * SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, void * DstMem, QueueImplPtr TgtQueue, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent) static
Definition at line 807 of file memory_manager.cpp.
References sycl::_V1::ext::oneapi::experimental::copy().
copy() [2/2]
void sycl::_V1::detail::MemoryManager::copy (SYCLMemObjI * SYCLMemObj, void * SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, void * DstMem, QueueImplPtr TgtQueue, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 766 of file memory_manager.cpp.
References sycl::_V1::detail::copyD2D(), sycl::_V1::detail::copyD2H(), sycl::_V1::detail::copyH2D(), and sycl::_V1::detail::copyH2H().
copy_2d_usm() [1/2]
void sycl::_V1::detail::MemoryManager::copy_2d_usm (const void * SrcMem, size_t SrcPitch, QueueImplPtr Queue, void * DstMem, size_t DstPitch, size_t Width, size_t Height, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1164 of file memory_manager.cpp.
copy_2d_usm() [2/2]
void sycl::_V1::detail::MemoryManager::copy_2d_usm (const void * SrcMem, size_t SrcPitch, QueueImplPtr Queue, void * DstMem, size_t DstPitch, size_t Width, size_t Height, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1085 of file memory_manager.cpp.
References PI_EXT_ONEAPI_CONTEXT_INFO_USM_MEMCPY2D_SUPPORT, PI_FALSE, piContextGetInfo(), piEnqueueEventsWait(), piextUSMEnqueueMemcpy(), and piextUSMEnqueueMemcpy2D().
copy_from_device_global() [1/2]
void sycl::_V1::detail::MemoryManager::copy_from_device_global (const void * DeviceGlobalPtr, bool IsDeviceImageScoped, QueueImplPtr Queue, size_t NumBytes, size_t Offset, void * DstMem, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1442 of file memory_manager.cpp.
copy_from_device_global() [2/2]
void sycl::_V1::detail::MemoryManager::copy_from_device_global (const void * DeviceGlobalPtr, bool IsDeviceImageScoped, QueueImplPtr Queue, size_t NumBytes, size_t Offset, void * DstMem, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1418 of file memory_manager.cpp.
References sycl::_V1::detail::DeviceGlobalMapEntry::MDeviceGlobalTSize, sycl::_V1::detail::memcpyFromDeviceGlobalDirect(), sycl::_V1::detail::memcpyFromDeviceGlobalUSM(), and sycl::_V1::detail::DeviceGlobalMapEntry::MIsDeviceImageScopeDecorated.
Referenced by sycl::_V1::detail::queue_impl::memcpyFromDeviceGlobal().
copy_image_bindless()
void sycl::_V1::detail::MemoryManager::copy_image_bindless (void * Src, QueueImplPtr Queue, void * Dst, const sycl::detail::pi::PiMemImageDesc & Desc, const sycl::detail::pi::PiMemImageFormat & Format, const sycl::detail::pi::PiImageCopyFlags Flags, sycl::detail::pi::PiImageOffset SrcOffset, sycl::detail::pi::PiImageOffset DstOffset, sycl::detail::pi::PiImageRegion CopyExtent, sycl::detail::pi::PiImageRegion HostExtent, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1778 of file memory_manager.cpp.
References sycl::_V1::ext::oneapi::experimental::DtoD, sycl::_V1::ext::oneapi::experimental::DtoH, sycl::_V1::ext::oneapi::experimental::HtoD, and piextMemImageCopy().
copy_to_device_global() [1/2]
void sycl::_V1::detail::MemoryManager::copy_to_device_global (const void * DeviceGlobalPtr, bool IsDeviceImageScoped, QueueImplPtr Queue, size_t NumBytes, size_t Offset, const void * SrcMem, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1409 of file memory_manager.cpp.
copy_to_device_global() [2/2]
void sycl::_V1::detail::MemoryManager::copy_to_device_global (const void * DeviceGlobalPtr, bool IsDeviceImageScoped, QueueImplPtr Queue, size_t NumBytes, size_t Offset, const void * SrcMem, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1385 of file memory_manager.cpp.
References sycl::_V1::detail::DeviceGlobalMapEntry::MDeviceGlobalTSize, sycl::_V1::detail::memcpyToDeviceGlobalDirect(), sycl::_V1::detail::memcpyToDeviceGlobalUSM(), and sycl::_V1::detail::DeviceGlobalMapEntry::MIsDeviceImageScopeDecorated.
Referenced by sycl::_V1::detail::queue_impl::memcpyToDeviceGlobal().
copy_usm() [1/2]
void sycl::_V1::detail::MemoryManager::copy_usm (const void * SrcMem, QueueImplPtr Queue, size_t Len, void * DstMem, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 977 of file memory_manager.cpp.
copy_usm() [2/2]
void sycl::_V1::detail::MemoryManager::copy_usm (const void * SrcMem, QueueImplPtr Queue, size_t Len, void * DstMem, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 944 of file memory_manager.cpp.
References PI_FALSE, piEnqueueEventsWait(), and piextUSMEnqueueMemcpy().
Referenced by sycl::_V1::detail::DeviceGlobalMapEntry::getOrAllocateDeviceGlobalUSM(), and sycl::_V1::detail::queue_impl::memcpy().
ext_oneapi_advise_usm_cmd_buffer()
void sycl::_V1::detail::MemoryManager::ext_oneapi_advise_usm_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, const void * Mem, size_t Length, pi_mem_advice Advice, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint) static
Definition at line 1764 of file memory_manager.cpp.
References piextCommandBufferAdviseUSM().
ext_oneapi_copy_usm_cmd_buffer()
void sycl::_V1::detail::MemoryManager::ext_oneapi_copy_usm_cmd_buffer (ContextImplPtr Context, const void * SrcMem, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, size_t Len, void * DstMem, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint) static
Definition at line 1673 of file memory_manager.cpp.
References piextCommandBufferMemcpyUSM().
ext_oneapi_copyD2D_cmd_buffer()
void sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2D_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, SYCLMemObjI * SYCLMemObj, void * SrcMem, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, void * DstMem, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint) static
Definition at line 1452 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::getType(), piextCommandBufferMemBufferCopy(), piextCommandBufferMemBufferCopyRect(), sycl::_V1::detail::prepTermPositions(), sycl::_V1::detail::TermPositions::XTerm, sycl::_V1::detail::TermPositions::YTerm, and sycl::_V1::detail::TermPositions::ZTerm.
ext_oneapi_copyD2H_cmd_buffer()
void sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2H_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, SYCLMemObjI * SYCLMemObj, void * SrcMem, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char * DstMem, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint) static
Definition at line 1518 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::getType(), piextCommandBufferMemBufferRead(), piextCommandBufferMemBufferReadRect(), sycl::_V1::detail::prepTermPositions(), sycl::_V1::detail::TermPositions::XTerm, sycl::_V1::detail::TermPositions::YTerm, and sycl::_V1::detail::TermPositions::ZTerm.
ext_oneapi_copyH2D_cmd_buffer()
void sycl::_V1::detail::MemoryManager::ext_oneapi_copyH2D_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, SYCLMemObjI * SYCLMemObj, char * SrcMem, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, void * DstMem, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint) static
Definition at line 1595 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::getType(), piextCommandBufferMemBufferWrite(), piextCommandBufferMemBufferWriteRect(), sycl::_V1::detail::prepTermPositions(), sycl::_V1::detail::TermPositions::XTerm, sycl::_V1::detail::TermPositions::YTerm, and sycl::_V1::detail::TermPositions::ZTerm.
ext_oneapi_fill_cmd_buffer()
void sycl::_V1::detail::MemoryManager::ext_oneapi_fill_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, SYCLMemObjI * SYCLMemObj, void * Mem, size_t PatternSize, const char * Pattern, unsigned int Dim, sycl::range< 3 > Size, sycl::range< 3 > AccessRange, sycl::id< 3 > AccessOffset, unsigned int ElementSize, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint) static
Definition at line 1714 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::getType(), and piextCommandBufferMemBufferFill().
ext_oneapi_fill_usm_cmd_buffer()
void sycl::_V1::detail::MemoryManager::ext_oneapi_fill_usm_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, void * DstMem, size_t Len, const std::vector< char > & Pattern, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint) static
Definition at line 1696 of file memory_manager.cpp.
References piextCommandBufferFillUSM().
ext_oneapi_prefetch_usm_cmd_buffer()
void sycl::_V1::detail::MemoryManager::ext_oneapi_prefetch_usm_cmd_buffer (sycl::detail::ContextImplPtr Context, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, void * Mem, size_t Length, std::vector< sycl::detail::pi::PiExtSyncPoint > Deps, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint) static
Definition at line 1751 of file memory_manager.cpp.
References piextCommandBufferPrefetchUSM().
fill() [1/2]
void sycl::_V1::detail::MemoryManager::fill (SYCLMemObjI * SYCLMemObj, void * Mem, QueueImplPtr Queue, size_t PatternSize, const char * Pattern, unsigned int Dim, sycl::range< 3 > Size, sycl::range< 3 > AccessRange, sycl::id< 3 > AccessOffset, unsigned int ElementSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent) static
Definition at line 872 of file memory_manager.cpp.
References sycl::_V1::ext::oneapi::experimental::fill().
fill() [2/2]
void sycl::_V1::detail::MemoryManager::fill (SYCLMemObjI * SYCLMemObj, void * Mem, QueueImplPtr Queue, size_t PatternSize, const char * Pattern, unsigned int Dim, sycl::range< 3 > Size, sycl::range< 3 > AccessRange, sycl::id< 3 > AccessOffset, unsigned int ElementSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 823 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::getType(), piEnqueueMemBufferFill(), piEnqueueMemImageFill(), and sycl::_V1::range< Dimensions >::size().
fill_2d_usm() [1/2]
void sycl::_V1::detail::MemoryManager::fill_2d_usm (void * DstMem, QueueImplPtr Queue, size_t Pitch, size_t Width, size_t Height, const std::vector< char > & Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1205 of file memory_manager.cpp.
fill_2d_usm() [2/2]
void sycl::_V1::detail::MemoryManager::fill_2d_usm (void * DstMem, QueueImplPtr Queue, size_t Pitch, size_t Width, size_t Height, const std::vector< char > & Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1173 of file memory_manager.cpp.
References piEnqueueEventsWait(), and piextUSMEnqueueFill2D().
fill_usm() [1/3]
void sycl::_V1::detail::MemoryManager::fill_usm (void * DstMem, QueueImplPtr Queue, size_t Len, const std::vector< char > & Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 985 of file memory_manager.cpp.
References piEnqueueEventsWait(), and piextUSMEnqueueFill().
Referenced by sycl::_V1::detail::queue_impl::memset().
fill_usm() [2/3]
void sycl::_V1::detail::MemoryManager::fill_usm (void * DstMem, QueueImplPtr Queue, size_t Len, int Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1027 of file memory_manager.cpp.
fill_usm() [3/3]
void sycl::_V1::detail::MemoryManager::fill_usm (void * DstMem, QueueImplPtr Queue, size_t Len, int Pattern, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1015 of file memory_manager.cpp.
map()
void * sycl::_V1::detail::MemoryManager::map (SYCLMemObjI * SYCLMemObj, void * Mem, QueueImplPtr Queue, access::mode AccessMode, unsigned int Dim, sycl::range< 3 > Size, sycl::range< 3 > AccessRange, sycl::id< 3 > AccessOffset, unsigned int ElementSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent) static
Definition at line 883 of file memory_manager.cpp.
References sycl::_V1::detail::memBufferMapHelper(), PI_FALSE, PI_MAP_READ, PI_MAP_WRITE, PI_MAP_WRITE_INVALIDATE_REGION, and sycl::_V1::detail::write().
memset_2d_usm() [1/2]
void sycl::_V1::detail::MemoryManager::memset_2d_usm (void * DstMem, QueueImplPtr Queue, size_t Pitch, size_t Width, size_t Height, char Value, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1246 of file memory_manager.cpp.
memset_2d_usm() [2/2]
void sycl::_V1::detail::MemoryManager::memset_2d_usm (void * DstMem, QueueImplPtr Queue, size_t Pitch, size_t Width, size_t Height, char Value, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1214 of file memory_manager.cpp.
References piEnqueueEventsWait(), and piextUSMEnqueueMemset2D().
prefetch_usm() [1/2]
void sycl::_V1::detail::MemoryManager::prefetch_usm (void * Ptr, QueueImplPtr Queue, size_t Len, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1054 of file memory_manager.cpp.
prefetch_usm() [2/2]
void sycl::_V1::detail::MemoryManager::prefetch_usm (void * Ptr, QueueImplPtr Queue, size_t Len, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1037 of file memory_manager.cpp.
References piextUSMEnqueuePrefetch().
release()
void sycl::_V1::detail::MemoryManager::release (ContextImplPtr TargetContext, SYCLMemObjI * MemObj, void * MemAllocation, std::vector< EventImplPtr > DepEvents, sycl::detail::pi::PiEvent & OutEvent) static
Definition at line 249 of file memory_manager.cpp.
References sycl::_V1::detail::XPTIRegistry::bufferReleaseNotification(), sycl::_V1::detail::SYCLMemObjI::releaseMem(), and sycl::_V1::detail::waitForEvents().
releaseMemObj()
void sycl::_V1::detail::MemoryManager::releaseMemObj (ContextImplPtr TargetContext, SYCLMemObjI * MemObj, void * MemAllocation, void * UserPtr) static
Definition at line 261 of file memory_manager.cpp.
References sycl::_V1::detail::memReleaseHelper(), and sycl::_V1::detail::SYCLMemObjI::releaseHostMem().
Referenced by sycl::_V1::detail::SYCLMemObjT::releaseMem().
unmap()
void sycl::_V1::detail::MemoryManager::unmap (SYCLMemObjI * SYCLMemObj, void * Mem, QueueImplPtr Queue, void * MappedPtr, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent) static
Definition at line 929 of file memory_manager.cpp.
References sycl::_V1::detail::memUnmapHelper().
The documentation for this class was generated from the following files:
source/detail/memory_manager.hpp
source/detail/memory_manager.cpp