DPC++ Runtime: cl::sycl::image< Dimensions, AllocatorT > Class Template Reference
cl::sycl::image< Dimensions, AllocatorT > Class Template Reference
DPC++ User API
Defines a shared image data.
#include <CL/sycl/detail/image_impl.hpp>
Public Member Functions
image (image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, const property_list &PropList={})
image (image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, AllocatorT Allocator, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image (image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, const typename std::enable_if< B, range< Dimensions - 1 >>::type &Pitch, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image (image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, const typename std::enable_if< B, range< Dimensions - 1 >>::type &Pitch, AllocatorT Allocator, const property_list &PropList={})
image (void *HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, const property_list &PropList={})
image (void *HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, AllocatorT Allocator, const property_list &PropList={})
image (const void *HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, const property_list &PropList={})
image (const void *HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, AllocatorT Allocator, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image (void *HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, typename std::enable_if< B, range< Dimensions - 1 >>::type &Pitch, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image (void *HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, typename std::enable_if< B, range< Dimensions - 1 >>::type &Pitch, AllocatorT Allocator, const property_list &PropList={})
image (shared_ptr_class< void > &HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, const property_list &PropList={})
image (shared_ptr_class< void > &HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, AllocatorT Allocator, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image (shared_ptr_class< void > &HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, const typename std::enable_if< B, range< Dimensions - 1 >>::type &Pitch, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image (shared_ptr_class< void > &HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > &Range, const typename std::enable_if< B, range< Dimensions - 1 >>::type &Pitch, AllocatorT Allocator, const property_list &PropList={})
image (cl_mem ClMemObject, const context &SyclContext, event AvailableEvent={})
image (const image &rhs)=default
image (image &&rhs)=default
image & operator= (const image &rhs)=default
image & operator= (image &&rhs)=default
~image ()=default
bool operator== (const image &rhs) const
bool operator!= (const image &rhs) const
template<typename propertyT >
bool has_property () const
template<typename propertyT >
propertyT get_property () const
range< Dimensions > get_range () const
template<bool B = (Dimensions > 1)>
std::enable_if< B, range< Dimensions - 1 > >::type get_pitch () const
size_t get_size () const
size_t get_count () const
AllocatorT get_allocator () const
template<typename DataT , access::mode AccessMode>
accessor< detail::EnableIfImgAccDataT< DataT >, Dimensions, AccessMode, access::target::image, access::placeholder::false_t > get_access (handler &commandGroupHandler)
template<typename DataT , access::mode AccessMode>
accessor< detail::EnableIfImgAccDataT< DataT >, Dimensions, AccessMode, access::target::host_image, access::placeholder::false_t > get_access ()
template<typename Destination = std::nullptr_t>
void set_final_data (Destination finalData=nullptr)
void set_write_back (bool flag=true)
Detailed Description
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator>
class cl::sycl::image< Dimensions, AllocatorT >
Defines a shared image data.
Images can be 1-, 2-, and 3-dimensional. They have to be accessed using the accessor class.
See also
Accessors
sampler
Definition at line 29 of file image_impl.hpp.
Constructor & Destructor Documentation
image() [1/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, const property_list & PropList = {}) inline
Definition at line 73 of file image.hpp.
image() [2/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, AllocatorT Allocator, const property_list & PropList = {}) inline
Definition at line 81 of file image.hpp.
image() [3/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<bool B = (Dimensions > 1)> cl::sycl::image< Dimensions, AllocatorT >::image (image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, const typename std::enable_if< B, range< Dimensions - 1 >>::type & Pitch, const property_list & PropList = {}) inline
Definition at line 93 of file image.hpp.
image() [4/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<bool B = (Dimensions > 1)> cl::sycl::image< Dimensions, AllocatorT >::image (image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, const typename std::enable_if< B, range< Dimensions - 1 >>::type & Pitch, AllocatorT Allocator, const property_list & PropList = {}) inline
Definition at line 105 of file image.hpp.
image() [5/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (void * HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, const property_list & PropList = {}) inline
Definition at line 116 of file image.hpp.
image() [6/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (void * HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, AllocatorT Allocator, const property_list & PropList = {}) inline
Definition at line 124 of file image.hpp.
image() [7/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (const void * HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, const property_list & PropList = {}) inline
Definition at line 134 of file image.hpp.
image() [8/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (const void * HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, AllocatorT Allocator, const property_list & PropList = {}) inline
Definition at line 143 of file image.hpp.
image() [9/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<bool B = (Dimensions > 1)> cl::sycl::image< Dimensions, AllocatorT >::image (void * HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, typename std::enable_if< B, range< Dimensions - 1 >>::type & Pitch, const property_list & PropList = {}) inline
Definition at line 155 of file image.hpp.
image() [10/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<bool B = (Dimensions > 1)> cl::sycl::image< Dimensions, AllocatorT >::image (void * HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, typename std::enable_if< B, range< Dimensions - 1 >>::type & Pitch, AllocatorT Allocator, const property_list & PropList = {}) inline
Definition at line 167 of file image.hpp.
image() [11/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (shared_ptr_class< void > & HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, const property_list & PropList = {}) inline
Definition at line 178 of file image.hpp.
image() [12/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (shared_ptr_class< void > & HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, AllocatorT Allocator, const property_list & PropList = {}) inline
Definition at line 187 of file image.hpp.
image() [13/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<bool B = (Dimensions > 1)> cl::sycl::image< Dimensions, AllocatorT >::image (shared_ptr_class< void > & HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, const typename std::enable_if< B, range< Dimensions - 1 >>::type & Pitch, const property_list & PropList = {}) inline
Definition at line 199 of file image.hpp.
image() [14/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<bool B = (Dimensions > 1)> cl::sycl::image< Dimensions, AllocatorT >::image (shared_ptr_class< void > & HostPointer, image_channel_order Order, image_channel_type Type, const range< Dimensions > & Range, const typename std::enable_if< B, range< Dimensions - 1 >>::type & Pitch, AllocatorT Allocator, const property_list & PropList = {}) inline
Definition at line 211 of file image.hpp.
image() [15/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (cl_mem ClMemObject, const context & SyclContext, event AvailableEvent = {}) inline
Definition at line 222 of file image.hpp.
image() [16/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (const image< Dimensions, AllocatorT > & rhs) default
image() [17/17]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::image (image< Dimensions, AllocatorT > && rhs) default
~image()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> cl::sycl::image< Dimensions, AllocatorT >::~image () default
Member Function Documentation
get_access() [1/2]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<typename DataT , access::mode AccessMode> accessor<detail::EnableIfImgAccDataT<DataT>, Dimensions, AccessMode, access::target::image, access::placeholder::false_t> cl::sycl::image< Dimensions, AllocatorT >::get_access (handler & commandGroupHandler) inline
Definition at line 276 of file image.hpp.
get_access() [2/2]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<typename DataT , access::mode AccessMode> accessor<detail::EnableIfImgAccDataT<DataT>, Dimensions, AccessMode, access::target::host_image, access::placeholder::false_t> cl::sycl::image< Dimensions, AllocatorT >::get_access () inline
Definition at line 284 of file image.hpp.
get_allocator()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> AllocatorT cl::sycl::image< Dimensions, AllocatorT >::get_allocator () const inline
Definition at line 269 of file image.hpp.
get_count()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> size_t cl::sycl::image< Dimensions, AllocatorT >::get_count () const inline
Definition at line 266 of file image.hpp.
Referenced by cl::sycl::detail::image_accessor< DataT, Dimensions, AccessMode, access::target::host_image, IsPlaceholder >::image_accessor().
get_pitch()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<bool B = (Dimensions > 1)> std::enable_if<B, range<Dimensions - 1> >::type cl::sycl::image< Dimensions, AllocatorT >::get_pitch () const inline
Definition at line 258 of file image.hpp.
get_property()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<typename propertyT > propertyT cl::sycl::image< Dimensions, AllocatorT >::get_property () const inline
Definition at line 250 of file image.hpp.
get_range()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> range<Dimensions> cl::sycl::image< Dimensions, AllocatorT >::get_range () const inline
Definition at line 254 of file image.hpp.
Referenced by cl::sycl::detail::image_accessor< DataT, Dimensions, AccessMode, access::target::host_image, IsPlaceholder >::image_accessor().
get_size()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> size_t cl::sycl::image< Dimensions, AllocatorT >::get_size () const inline
Definition at line 263 of file image.hpp.
has_property()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<typename propertyT > bool cl::sycl::image< Dimensions, AllocatorT >::has_property () const inline
Definition at line 246 of file image.hpp.
operator!=()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> bool cl::sycl::image< Dimensions, AllocatorT >::operator!= (const image< Dimensions, AllocatorT > & rhs) const inline
Definition at line 243 of file image.hpp.
operator=() [1/2]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> image& cl::sycl::image< Dimensions, AllocatorT >::operator= (const image< Dimensions, AllocatorT > & rhs) default
operator=() [2/2]
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> image& cl::sycl::image< Dimensions, AllocatorT >::operator= (image< Dimensions, AllocatorT > && rhs) default
operator==()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> bool cl::sycl::image< Dimensions, AllocatorT >::operator== (const image< Dimensions, AllocatorT > & rhs) const inline
Definition at line 241 of file image.hpp.
set_final_data()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> template<typename Destination = std::nullptr_t> void cl::sycl::image< Dimensions, AllocatorT >::set_final_data (Destination finalData = nullptr) inline
Definition at line 290 of file image.hpp.
set_write_back()
template<int Dimensions = 1, typename AllocatorT = cl::sycl::image_allocator> void cl::sycl::image< Dimensions, AllocatorT >::set_write_back (bool flag = true) inline
Definition at line 294 of file image.hpp.
References cl::sycl::detail::getSyclObjImpl().
The documentation for this class was generated from the following files:
include/CL/sycl/detail/image_impl.hpp
include/CL/sycl/image.hpp