DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup > Class Template Reference
sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup > Class Template Reference
#include <sycl/ext/oneapi/experimental/ballot_group.hpp>
Public Types
using id_type = id< 1 >
using range_type = range< 1 >
using linear_id_type = typename ParentGroup::linear_id_type
Public Member Functions
id_type get_group_id () const
id_type get_local_id () const
range_type get_group_range () const
range_type get_local_range () const
linear_id_type get_group_linear_id () const
linear_id_type get_local_linear_id () const
linear_id_type get_group_linear_range () const
linear_id_type get_local_linear_range () const
bool leader () const
Static Public Attributes
static constexpr int dimensions = 1
static constexpr sycl::memory_scope fence_scope = ParentGroup::fence_scope
Protected Member Functions
ballot_group (sub_group_mask m, bool p)
Protected Attributes
const sub_group_mask Mask
const bool Predicate
Friends
ballot_group< ParentGroup > get_ballot_group (ParentGroup g, bool predicate)
sub_group_mask sycl::detail::GetMask (ballot_group< ParentGroup > Group)
Detailed Description
template<typename ParentGroup>
class sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >
Definition at line 39 of file ballot_group.hpp.
Member Typedef Documentation
id_type
template<typename ParentGroup > using sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::id_type = id<1>
Definition at line 41 of file ballot_group.hpp.
linear_id_type
template<typename ParentGroup > using sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::linear_id_type = typename ParentGroup::linear_id_type
Definition at line 43 of file ballot_group.hpp.
range_type
template<typename ParentGroup > using sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::range_type = range<1>
Definition at line 42 of file ballot_group.hpp.
Constructor & Destructor Documentation
ballot_group()
template<typename ParentGroup > sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::ballot_group (sub_group_mask m, bool p) inline protected
Definition at line 133 of file ballot_group.hpp.
Member Function Documentation
get_group_id()
template<typename ParentGroup > id_type sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_id () const inline
Definition at line 47 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::Predicate.
Referenced by sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_linear_id().
get_group_linear_id()
template<typename ParentGroup > linear_id_type sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_linear_id () const inline
Definition at line 83 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_id().
get_group_linear_range()
template<typename ParentGroup > linear_id_type sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_linear_range () const inline
Definition at line 101 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_range().
get_group_range()
template<typename ParentGroup > range_type sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_range () const inline
Definition at line 65 of file ballot_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_linear_range().
get_local_id()
template<typename ParentGroup > id_type sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_id () const inline
Definition at line 56 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::Mask.
Referenced by sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_linear_id().
get_local_linear_id()
template<typename ParentGroup > linear_id_type sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_linear_id () const inline
Definition at line 92 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_id().
get_local_linear_range()
template<typename ParentGroup > linear_id_type sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_linear_range () const inline
Definition at line 110 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_range().
get_local_range()
template<typename ParentGroup > range_type sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_range () const inline
Definition at line 74 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::sub_group_mask::count(), and sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::Mask.
Referenced by sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_linear_range().
leader()
template<typename ParentGroup > bool sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::leader () const inline
Definition at line 119 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::sub_group_mask::find_low(), and sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::Mask.
Friends And Related Function Documentation
get_ballot_group
template<typename ParentGroup > ballot_group<ParentGroup> get_ballot_group (ParentGroup g, bool predicate) friend
sycl::detail::GetMask
template<typename ParentGroup > sub_group_mask sycl::detail::GetMask (ballot_group< ParentGroup > Group) friend
Member Data Documentation
dimensions
template<typename ParentGroup > constexpr int sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::dimensions = 1 static constexpr
Definition at line 44 of file ballot_group.hpp.
fence_scope
template<typename ParentGroup > constexpr sycl::memory_scope sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::fence_scope = ParentGroup::fence_scope static constexpr
Definition at line 45 of file ballot_group.hpp.
Mask
template<typename ParentGroup > const sub_group_mask sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::Mask protected
Definition at line 130 of file ballot_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_id(), sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_local_range(), and sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::leader().
Predicate
template<typename ParentGroup > const bool sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::Predicate protected
Definition at line 131 of file ballot_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::ballot_group< ParentGroup >::get_group_id().
The documentation for this class was generated from the following file:
include/sycl/ext/oneapi/experimental/ballot_group.hpp