DPC++ Runtime: sycl::_V1::detail::jit_compiler Class Reference
sycl::_V1::detail::jit_compiler Class Reference
#include <detail/jit_compiler.hpp>
Public Member Functions
std::unique_ptr< detail::CG > fuseKernels (QueueImplPtr Queue, std::vector< ExecCGCommand * > &InputKernels, const property_list &)
bool isAvailable ()
Static Public Member Functions
static jit_compiler & get_instance ()
Detailed Description
Definition at line 37 of file jit_compiler.hpp.
Member Function Documentation
fuseKernels()
std::unique_ptr<detail::CG> sycl::_V1::detail::jit_compiler::fuseKernels (QueueImplPtr Queue, std::vector< ExecCGCommand * > & InputKernels, const property_list &)
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::completeFusion().
get_instance()
static jit_compiler& sycl::_V1::detail::jit_compiler::get_instance () inline static
Definition at line 46 of file jit_compiler.hpp.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::completeFusion(), and sycl::_V1::detail::get_device_info_impl< bool, ext::codeplay::experimental::info::device::supports_fusion >::get().
isAvailable()
bool sycl::_V1::detail::jit_compiler::isAvailable () inline
Definition at line 44 of file jit_compiler.hpp.
The documentation for this class was generated from the following file:
source/detail/jit_compiler.hpp