DPC++ Runtime: sycl::_V1::detail::kernel_bundle_plain Class Reference
sycl::_V1::detail::kernel_bundle_plain Class Reference
#include <sycl/kernel_bundle.hpp>
Public Member Functions
kernel_bundle_plain (const detail::KernelBundleImplPtr &Impl)
bool operator== (const kernel_bundle_plain &RHS) const
bool operator!= (const kernel_bundle_plain &RHS) const
bool empty () const noexcept
backend get_backend () const noexcept
context get_context () const noexcept
std::vector< device > get_devices () const noexcept
bool has_kernel (const kernel_id &KernelID) const noexcept
bool has_kernel (const kernel_id &KernelID, const device &Dev) const noexcept
std::vector< kernel_id > get_kernel_ids () const
bool contains_specialization_constants () const noexcept
bool native_specialization_constant () const noexcept
bool ext_oneapi_has_kernel (const std::string &name)
kernel ext_oneapi_get_kernel (const std::string &name)
Protected Member Functions
kernel get_kernel (const kernel_id &KernelID) const
const device_image_plain * begin () const
const device_image_plain * end () const
bool has_specialization_constant_impl (const char *SpecName) const noexcept
void set_specialization_constant_impl (const char *SpecName, void *Value, size_t Size) noexcept
void get_specialization_constant_impl (const char *SpecName, void *Value) const noexcept
bool is_specialization_constant_set (const char *SpecName) const noexcept
Protected Attributes
detail::KernelBundleImplPtr impl
Detailed Description
Definition at line 155 of file kernel_bundle.hpp.
Constructor & Destructor Documentation
kernel_bundle_plain()
sycl::_V1::detail::kernel_bundle_plain::kernel_bundle_plain (const detail::KernelBundleImplPtr & Impl) inline
Definition at line 157 of file kernel_bundle.hpp.
Member Function Documentation
begin()
const device_image_plain * sycl::_V1::detail::kernel_bundle_plain::begin () const protected
Definition at line 80 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::begin().
contains_specialization_constants()
bool sycl::_V1::detail::kernel_bundle_plain::contains_specialization_constants () const noexcept
Definition at line 68 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::contains_specialization_constants().
empty()
bool sycl::_V1::detail::kernel_bundle_plain::empty () const noexcept
Definition at line 50 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::empty().
end()
const device_image_plain * sycl::_V1::detail::kernel_bundle_plain::end () const protected
Definition at line 84 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::end().
ext_oneapi_get_kernel()
kernel sycl::_V1::detail::kernel_bundle_plain::ext_oneapi_get_kernel (const std::string & name)
Definition at line 121 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::ext_oneapi_get_kernel().
ext_oneapi_has_kernel()
bool sycl::_V1::detail::kernel_bundle_plain::ext_oneapi_has_kernel (const std::string & name)
Definition at line 117 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::ext_oneapi_has_kernel().
get_backend()
backend sycl::_V1::detail::kernel_bundle_plain::get_backend () const noexcept
Definition at line 52 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::get_backend().
get_context()
context sycl::_V1::detail::kernel_bundle_plain::get_context () const noexcept
Definition at line 56 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::get_context().
get_devices()
std::vector< device > sycl::_V1::detail::kernel_bundle_plain::get_devices () const noexcept
Definition at line 60 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::get_devices().
get_kernel()
kernel sycl::_V1::detail::kernel_bundle_plain::get_kernel (const kernel_id & KernelID) const protected
Definition at line 76 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::get_kernel().
get_kernel_ids()
std::vector< kernel_id > sycl::_V1::detail::kernel_bundle_plain::get_kernel_ids () const
Definition at line 64 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::get_kernel_ids().
get_specialization_constant_impl()
void sycl::_V1::detail::kernel_bundle_plain::get_specialization_constant_impl (const char * SpecName, void * Value) const protected noexcept
Definition at line 107 of file kernel_bundle.cpp.
has_kernel() [1/2]
bool sycl::_V1::detail::kernel_bundle_plain::has_kernel (const kernel_id & KernelID) const noexcept
Definition at line 88 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::has_kernel().
has_kernel() [2/2]
bool sycl::_V1::detail::kernel_bundle_plain::has_kernel (const kernel_id & KernelID, const device & Dev) const noexcept
Definition at line 92 of file kernel_bundle.cpp.
has_specialization_constant_impl()
bool sycl::_V1::detail::kernel_bundle_plain::has_specialization_constant_impl (const char * SpecName) const protected noexcept
Definition at line 97 of file kernel_bundle.cpp.
is_specialization_constant_set()
bool sycl::_V1::detail::kernel_bundle_plain::is_specialization_constant_set (const char * SpecName) const protected noexcept
Definition at line 112 of file kernel_bundle.cpp.
native_specialization_constant()
bool sycl::_V1::detail::kernel_bundle_plain::native_specialization_constant () const noexcept
Definition at line 72 of file kernel_bundle.cpp.
Referenced by sycl::_V1::kernel_bundle< State >::native_specialization_constant().
operator!=()
bool sycl::_V1::detail::kernel_bundle_plain::operator!= (const kernel_bundle_plain & RHS) const inline
Definition at line 164 of file kernel_bundle.hpp.
operator==()
bool sycl::_V1::detail::kernel_bundle_plain::operator== (const kernel_bundle_plain & RHS) const inline
Definition at line 160 of file kernel_bundle.hpp.
References impl.
set_specialization_constant_impl()
void sycl::_V1::detail::kernel_bundle_plain::set_specialization_constant_impl (const char * SpecName, void * Value, size_t Size) protected noexcept
Definition at line 102 of file kernel_bundle.cpp.
Member Data Documentation
impl
detail::KernelBundleImplPtr sycl::_V1::detail::kernel_bundle_plain::impl protected
Definition at line 213 of file kernel_bundle.hpp.
Referenced by operator==().
The documentation for this class was generated from the following files:
include/sycl/kernel_bundle.hpp
source/kernel_bundle.cpp