DPC++ Runtime: cl::sycl::detail::image_impl< Dimensions > Class Template Reference
cl::sycl::detail::image_impl< Dimensions > Class Template Reference final
#include <CL/sycl/detail/image_impl.hpp>
Public Member Functions
image_impl (image_channel_order Order, image_channel_type Type, const range< Dimensions > &ImageRange, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image_impl (image_channel_order Order, image_channel_type Type, const range< Dimensions > &ImageRange, const EnableIfPitchT< B > &Pitch, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list &PropList={})
image_impl (void *HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > &ImageRange, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list &PropList={})
image_impl (const void *HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > &ImageRange, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image_impl (void *HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > &ImageRange, const EnableIfPitchT< B > &Pitch, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list &PropList={})
image_impl (shared_ptr_class< void > &HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > &ImageRange, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list &PropList={})
template<bool B = (Dimensions > 1)>
image_impl (shared_ptr_class< void > &HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > &ImageRange, const EnableIfPitchT< B > &Pitch, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list &PropList={})
image_impl (cl_mem MemObject, const context &SyclContext, event AvailableEvent, unique_ptr_class< SYCLMemObjAllocator > Allocator)
range< Dimensions > get_range () const
template<bool B = (Dimensions == 2)>
std::enable_if< B, range< 1 > >::type get_pitch () const
template<bool B = (Dimensions == 3)>
std::enable_if< B, range< 2 > >::type get_pitch () const
size_t get_count () const
void * allocateMem (ContextImplPtr Context, bool InitFromUserData, void *HostPtr, RT::PiEvent &OutEventToWait) override
MemObjType getType () const override
size_t getElementSize () const
image_channel_order getChannelOrder () const
image_channel_type getChannelType () const
size_t getRowPitch () const
size_t getSlicePitch () const
~image_impl ()
Public Member Functions inherited from cl::sycl::detail::SYCLMemObjT
SYCLMemObjT (const size_t SizeInBytes, const property_list &Props, unique_ptr_class< SYCLMemObjAllocator > Allocator)
SYCLMemObjT (const property_list &Props, unique_ptr_class< SYCLMemObjAllocator > Allocator)
SYCLMemObjT (cl_mem MemObject, const context &SyclContext, const size_t SizeInBytes, event AvailableEvent, unique_ptr_class< SYCLMemObjAllocator > Allocator)
SYCLMemObjT (cl_mem MemObject, const context &SyclContext, event AvailableEvent, unique_ptr_class< SYCLMemObjAllocator > Allocator)
virtual ~SYCLMemObjT ()=default
const plugin & getPlugin () const
DLL_LOCAL size_t getSize () const override
DLL_LOCAL size_t get_count () const
template<typename propertyT >
DLL_LOCAL bool has_property () const
template<typename propertyT >
DLL_LOCAL propertyT get_property () const
template<typename AllocatorT >
DLL_LOCAL AllocatorT get_allocator () const
DLL_LOCAL void * allocateHostMem () override
DLL_LOCAL void releaseHostMem (void *Ptr) override
void releaseMem (ContextImplPtr Context, void *MemAllocation) override
DLL_LOCAL void * getUserPtr () const
DLL_LOCAL void set_write_back (bool NeedWriteBack)
DLL_LOCAL void set_final_data (std::nullptr_t)
template<template< typename T > class PtrT, typename T >
DLL_LOCAL enable_if_t< std::is_convertible< PtrT< T >, weak_ptr_class< T > >::value > set_final_data (PtrT< T > FinalData)
template<typename T >
DLL_LOCAL void set_final_data (weak_ptr_class< T > FinalData)
DLL_LOCAL void set_final_data_from_storage ()
template<typename Destination >
DLL_LOCAL EnableIfOutputPointerT< Destination > set_final_data (Destination FinalData)
template<typename Destination >
DLL_LOCAL EnableIfOutputIteratorT< Destination > set_final_data (Destination FinalData)
void updateHostMemory (void *const Ptr)
void updateHostMemory ()
DLL_LOCAL bool useHostPtr ()
DLL_LOCAL bool canReuseHostPtr (void *HostPtr, const size_t RequiredAlign)
DLL_LOCAL void handleHostData (void *HostPtr, const size_t RequiredAlign)
DLL_LOCAL void handleHostData (const void *HostPtr, const size_t RequiredAlign)
template<typename T >
DLL_LOCAL void handleHostData (const shared_ptr_class< T > &HostPtr, const size_t RequiredAlign)
template<class InputIterator >
DLL_LOCAL void handleHostData (InputIterator First, InputIterator Last, const size_t RequiredAlign)
DLL_LOCAL void setAlign (size_t RequiredAlign)
DLL_LOCAL void * allocateMem (ContextImplPtr Context, bool InitFromUserData, void *HostPtr, RT::PiEvent &InteropEvent) override
DLL_LOCAL MemObjType getType () const override
Public Member Functions inherited from cl::sycl::detail::SYCLMemObjI
virtual ~SYCLMemObjI ()=default
Additional Inherited Members
Public Types inherited from cl::sycl::detail::SYCLMemObjI
enum MemObjType { BUFFER, IMAGE, UNDEFINED }
Static Public Member Functions inherited from cl::sycl::detail::SYCLMemObjT
static size_t getBufSizeForContext (const ContextImplPtr &Context, cl_mem MemObject)
Protected Attributes inherited from cl::sycl::detail::SYCLMemObjT
unique_ptr_class< SYCLMemObjAllocator > MAllocator
property_list MProps
EventImplPtr MInteropEvent
ContextImplPtr MInteropContext
cl_mem MInteropMemObject
bool MOpenCLInterop
bool MHostPtrReadOnly
bool MNeedWriteBack
size_t MSizeInBytes
void * MUserPtr
void * MShadowCopy
function_class< void(void)> MUploadDataFunctor
shared_ptr_class< const void > MSharedPtrStorage
Protected Attributes inherited from cl::sycl::detail::SYCLMemObjI
shared_ptr_class< MemObjRecord > MRecord
Detailed Description
template<int Dimensions>
class cl::sycl::detail::image_impl< Dimensions >
Definition at line 69 of file image_impl.hpp.
Constructor & Destructor Documentation
image_impl() [1/8]
template<int Dimensions> cl::sycl::detail::image_impl< Dimensions >::image_impl (image_channel_order Order, image_channel_type Type, const range< Dimensions > & ImageRange, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list & PropList = {}) inline
Definition at line 101 of file image_impl.hpp.
image_impl() [2/8]
template<int Dimensions> template<bool B = (Dimensions > 1)> cl::sycl::detail::image_impl< Dimensions >::image_impl (image_channel_order Order, image_channel_type Type, const range< Dimensions > & ImageRange, const EnableIfPitchT< B > & Pitch, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list & PropList = {}) inline
Definition at line 109 of file image_impl.hpp.
image_impl() [3/8]
template<int Dimensions> cl::sycl::detail::image_impl< Dimensions >::image_impl (void * HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > & ImageRange, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list & PropList = {}) inline
Definition at line 117 of file image_impl.hpp.
References cl::sycl::detail::getImageElementSize(), cl::sycl::detail::getImageNumberChannels(), and cl::sycl::detail::getNextPowerOfTwo().
image_impl() [4/8]
template<int Dimensions> cl::sycl::detail::image_impl< Dimensions >::image_impl (const void * HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > & ImageRange, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list & PropList = {}) inline
Definition at line 129 of file image_impl.hpp.
References cl::sycl::detail::getImageElementSize(), cl::sycl::detail::getImageNumberChannels(), and cl::sycl::detail::getNextPowerOfTwo().
image_impl() [5/8]
template<int Dimensions> template<bool B = (Dimensions > 1)> cl::sycl::detail::image_impl< Dimensions >::image_impl (void * HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > & ImageRange, const EnableIfPitchT< B > & Pitch, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list & PropList = {}) inline
Definition at line 142 of file image_impl.hpp.
References cl::sycl::detail::getImageElementSize(), cl::sycl::detail::getImageNumberChannels(), and cl::sycl::detail::getNextPowerOfTwo().
image_impl() [6/8]
template<int Dimensions> cl::sycl::detail::image_impl< Dimensions >::image_impl (shared_ptr_class< void > & HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > & ImageRange, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list & PropList = {}) inline
Definition at line 155 of file image_impl.hpp.
References cl::sycl::detail::getImageElementSize(), cl::sycl::detail::getImageNumberChannels(), and cl::sycl::detail::getNextPowerOfTwo().
image_impl() [7/8]
template<int Dimensions> template<bool B = (Dimensions > 1)> cl::sycl::detail::image_impl< Dimensions >::image_impl (shared_ptr_class< void > & HData, image_channel_order Order, image_channel_type Type, const range< Dimensions > & ImageRange, const EnableIfPitchT< B > & Pitch, unique_ptr_class< SYCLMemObjAllocator > Allocator, const property_list & PropList = {}) inline
Definition at line 169 of file image_impl.hpp.
References cl::sycl::detail::getImageElementSize(), cl::sycl::detail::getImageNumberChannels(), and cl::sycl::detail::getNextPowerOfTwo().
image_impl() [8/8]
template<int Dimensions> cl::sycl::detail::image_impl< Dimensions >::image_impl (cl_mem MemObject, const context & SyclContext, event AvailableEvent, unique_ptr_class< SYCLMemObjAllocator > Allocator)
Definition at line 270 of file image_impl.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::convertChannelOrder(), cl::sycl::detail::convertChannelType(), cl::sycl::detail::getImageElementSize(), cl::sycl::detail::getImageInfo(), cl::sycl::detail::getImageNumberChannels(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::SYCLMemObjT::MInteropMemObject, cl::sycl::detail::SYCLMemObjT::MSizeInBytes, PI_IMAGE_INFO_DEPTH, PI_IMAGE_INFO_ELEMENT_SIZE, PI_IMAGE_INFO_FORMAT, PI_IMAGE_INFO_HEIGHT, PI_IMAGE_INFO_ROW_PITCH, PI_IMAGE_INFO_SLICE_PITCH, PI_IMAGE_INFO_WIDTH, and piMemGetInfo().
~image_impl()
template<int Dimensions> cl::sycl::detail::image_impl< Dimensions >::~image_impl () inline
Definition at line 226 of file image_impl.hpp.
References _pi_image_desc::buffer, cl::sycl::detail::convertChannelOrder(), cl::sycl::detail::convertChannelType(), _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_row_pitch, _pi_image_desc::image_slice_pitch, _pi_image_desc::image_type, _pi_image_desc::image_width, _pi_image_desc::num_mip_levels, _pi_image_desc::num_samples, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, and PI_MEM_TYPE_IMAGE3D.
Member Function Documentation
allocateMem()
template<int Dimensions> void * cl::sycl::detail::image_impl< Dimensions >::allocateMem (ContextImplPtr Context, bool InitFromUserData, void * HostPtr, RT::PiEvent & OutEventToWait) override virtual
Implements cl::sycl::detail::SYCLMemObjI.
Definition at line 307 of file image_impl.cpp.
References cl::sycl::detail::MemoryManager::allocateMemImage(), _pi_image_desc::buffer, cl::sycl::detail::checkAny(), cl::sycl::info::devices, cl::sycl::detail::SYCLMemObjT::getSize(), cl::sycl::detail::SYCLMemObjT::getUserPtr(), _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_row_pitch, _pi_image_desc::image_slice_pitch, _pi_image_desc::image_type, _pi_image_desc::image_width, cl::sycl::detail::SYCLMemObjT::MHostPtrReadOnly, cl::sycl::detail::SYCLMemObjT::MInteropContext, cl::sycl::detail::SYCLMemObjT::MInteropEvent, _pi_image_desc::num_mip_levels, _pi_image_desc::num_samples, PI_IMAGE_CHANNEL_ORDER_ABGR, PI_IMAGE_CHANNEL_ORDER_ARGB, PI_IMAGE_CHANNEL_ORDER_BGRA, PI_IMAGE_CHANNEL_ORDER_INTENSITY, PI_IMAGE_CHANNEL_ORDER_LUMINANCE, PI_IMAGE_CHANNEL_ORDER_RGB, PI_IMAGE_CHANNEL_ORDER_RGBx, PI_IMAGE_CHANNEL_TYPE_FLOAT, PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8, PI_IMAGE_CHANNEL_TYPE_SNORM_INT16, PI_IMAGE_CHANNEL_TYPE_SNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT16, PI_IMAGE_CHANNEL_TYPE_UNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8, PI_INVALID_VALUE, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, and PI_MEM_TYPE_IMAGE3D.
get_count()
template<int Dimensions> size_t cl::sycl::detail::image_impl< Dimensions >::get_count () const inline
Definition at line 206 of file image_impl.hpp.
get_pitch() [1/2]
template<int Dimensions> template<bool B = (Dimensions == 2)> std::enable_if<B, range<1> >::type cl::sycl::detail::image_impl< Dimensions >::get_pitch () const inline
Definition at line 192 of file image_impl.hpp.
get_pitch() [2/2]
template<int Dimensions> template<bool B = (Dimensions == 3)> std::enable_if<B, range<2> >::type cl::sycl::detail::image_impl< Dimensions >::get_pitch () const inline
Definition at line 200 of file image_impl.hpp.
get_range()
template<int Dimensions> range<Dimensions> cl::sycl::detail::image_impl< Dimensions >::get_range () const inline
Definition at line 187 of file image_impl.hpp.
getChannelOrder()
template<int Dimensions> image_channel_order cl::sycl::detail::image_impl< Dimensions >::getChannelOrder () const inline
Definition at line 218 of file image_impl.hpp.
getChannelType()
template<int Dimensions> image_channel_type cl::sycl::detail::image_impl< Dimensions >::getChannelType () const inline
Definition at line 220 of file image_impl.hpp.
getElementSize()
template<int Dimensions> size_t cl::sycl::detail::image_impl< Dimensions >::getElementSize () const inline
Definition at line 216 of file image_impl.hpp.
getRowPitch()
template<int Dimensions> size_t cl::sycl::detail::image_impl< Dimensions >::getRowPitch () const inline
Definition at line 222 of file image_impl.hpp.
getSlicePitch()
template<int Dimensions> size_t cl::sycl::detail::image_impl< Dimensions >::getSlicePitch () const inline
Definition at line 224 of file image_impl.hpp.
getType()
template<int Dimensions> MemObjType cl::sycl::detail::image_impl< Dimensions >::getType () const inline override virtual
Implements cl::sycl::detail::SYCLMemObjI.
Definition at line 211 of file image_impl.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/detail/image_impl.hpp
source/detail/image_impl.cpp