DPC++ Runtime: cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange Class Reference
cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange Class Reference
#include <CL/sycl/detail/pi.hpp>
Classes
class ConstIterator
Public Types
using ValTy = std::remove_pointer< pi_device_binary_property >::type
Public Member Functions
ConstIterator begin () const
ConstIterator end () const
bool isAvailable () const
Friends
class DeviceBinaryImage
Detailed Description
Definition at line 249 of file pi.hpp.
Member Typedef Documentation
ValTy
using cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::ValTy = std::remove_pointer<pi_device_binary_property>::type
Definition at line 251 of file pi.hpp.
Member Function Documentation
begin()
ConstIterator cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::begin () const inline
Definition at line 277 of file pi.hpp.
Referenced by cl::sycl::detail::ProgramManager::createPIProgram(), cl::sycl::detail::ProgramManager::getDeviceLibReqMask(), cl::sycl::detail::ProgramManager::getOrCreatePIProgram(), and cl::sycl::detail::pi::DeviceBinaryImage::getProperty().
end()
ConstIterator cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::end () const inline
Definition at line 278 of file pi.hpp.
Referenced by cl::sycl::detail::pi::DeviceBinaryImage::getProperty(), and cl::sycl::detail::ProgramManager::kernelUsesAssert().
isAvailable()
bool cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::isAvailable () const inline
Definition at line 280 of file pi.hpp.
Referenced by cl::sycl::detail::ProgramManager::addImages(), cl::sycl::detail::ProgramManager::getDeviceLibReqMask(), and cl::sycl::detail::pi::DeviceBinaryImage::getProperty().
Friends And Related Function Documentation
DeviceBinaryImage
friend class DeviceBinaryImage friend
Definition at line 279 of file pi.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/detail/pi.hpp
source/detail/pi.cpp