DPC++ Runtime: cl::sycl::detail::sampler_impl Class Reference
cl::sycl::detail::sampler_impl Class Reference
#include <detail/sampler_impl.hpp>
Public Member Functions
sampler_impl (coordinate_normalization_mode normalizationMode, addressing_mode addressingMode, filtering_mode filteringMode, const property_list &propList)
sampler_impl (cl_sampler clSampler, const context &syclContext)
addressing_mode get_addressing_mode () const
filtering_mode get_filtering_mode () const
coordinate_normalization_mode get_coordinate_normalization_mode () const
RT::PiSampler getOrCreateSampler (const context &Context)
template<typename propertyT >
bool has_property () const
Checks if this sampler_impl has a property of type propertyT.
template<typename propertyT >
propertyT get_property () const
Gets the specified property of this sampler_impl.
~sampler_impl ()
Detailed Description
Definition at line 26 of file sampler_impl.hpp.
Constructor & Destructor Documentation
sampler_impl() [1/2]
cl::sycl::detail::sampler_impl::sampler_impl (coordinate_normalization_mode normalizationMode, addressing_mode addressingMode, filtering_mode filteringMode, const property_list & propList)
Definition at line 17 of file sampler_impl.cpp.
sampler_impl() [2/2]
cl::sycl::detail::sampler_impl::sampler_impl (cl_sampler clSampler, const context & syclContext)
Definition at line 24 of file sampler_impl.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::getSyclObjImpl(), PI_SAMPLER_INFO_ADDRESSING_MODE, PI_SAMPLER_INFO_FILTER_MODE, PI_SAMPLER_INFO_NORMALIZED_COORDS, piSamplerGetInfo(), and piSamplerRetain().
~sampler_impl()
cl::sycl::detail::sampler_impl::~sampler_impl ()
Definition at line 41 of file sampler_impl.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::getSyclObjImpl(), and piSamplerRelease().
Member Function Documentation
get_addressing_mode()
addressing_mode cl::sycl::detail::sampler_impl::get_addressing_mode () const
Definition at line 85 of file sampler_impl.cpp.
get_coordinate_normalization_mode()
coordinate_normalization_mode cl::sycl::detail::sampler_impl::get_coordinate_normalization_mode () const
Definition at line 90 of file sampler_impl.cpp.
get_filtering_mode()
filtering_mode cl::sycl::detail::sampler_impl::get_filtering_mode () const
Definition at line 87 of file sampler_impl.cpp.
get_property()
template<typename propertyT > propertyT cl::sycl::detail::sampler_impl::get_property () const inline
Gets the specified property of this sampler_impl.
Throws invalid_object_error if this sampler_impl does not have a property of type propertyT.
Returns
a copy of the property of type propertyT.
Definition at line 55 of file sampler_impl.hpp.
getOrCreateSampler()
RT::PiSampler cl::sycl::detail::sampler_impl::getOrCreateSampler (const context & Context)
Definition at line 50 of file sampler_impl.cpp.
References cl::sycl::detail::plugin::call_nocheck(), cl::sycl::detail::plugin::checkPiResult(), cl::sycl::feature_not_supported, cl::sycl::detail::getSyclObjImpl(), PI_INVALID_OPERATION, PI_SAMPLER_INFO_ADDRESSING_MODE, PI_SAMPLER_INFO_FILTER_MODE, PI_SAMPLER_INFO_NORMALIZED_COORDS, PI_SUCCESS, and piSamplerCreate().
has_property()
template<typename propertyT > bool cl::sycl::detail::sampler_impl::has_property () const inline
Checks if this sampler_impl has a property of type propertyT.
Returns
true if this sampler_impl has a property of type propertyT.
Definition at line 45 of file sampler_impl.hpp.
The documentation for this class was generated from the following files:
source/detail/sampler_impl.hpp
source/detail/sampler_impl.cpp