DPC++ Runtime: sycl::_V1::ext::intel::experimental::pipe_base Class Reference
sycl::_V1::ext::intel::experimental::pipe_base Class Reference
#include <sycl/ext/intel/experimental/pipes.hpp>
Protected Member Functions
pipe_base ()
~pipe_base ()
Static Protected Member Functions
static std::string get_pipe_name (const void *HostPipePtr)
static bool wait_non_blocking (const event &E)
Detailed Description
Definition at line 43 of file pipes.hpp.
Constructor & Destructor Documentation
pipe_base()
sycl::_V1::ext::intel::experimental::pipe_base::pipe_base () protected
~pipe_base()
sycl::_V1::ext::intel::experimental::pipe_base::~pipe_base () protected
Member Function Documentation
get_pipe_name()
std::string sycl::_V1::ext::intel::experimental::pipe_base::get_pipe_name (const void * HostPipePtr) static protected
Definition at line 20 of file pipes.cpp.
References sycl::_V1::detail::ProgramManager::getHostPipeEntry(), sycl::_V1::detail::ProgramManager::getInstance(), and sycl::_V1::detail::HostPipeMapEntry::MUniqueId.
Referenced by sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::read(), and sycl::_V1::ext::intel::experimental::pipe< _name, _dataT, _min_capacity, _propertiesT, class >::write().
wait_non_blocking()
bool sycl::_V1::ext::intel::experimental::pipe_base::wait_non_blocking (const event & E) static protected
Definition at line 26 of file pipes.cpp.
References sycl::_V1::detail::getSyclObjImpl().
The documentation for this class was generated from the following files:
include/sycl/ext/intel/experimental/pipes.hpp
source/detail/pipes.cpp