DPC++ Runtime: cl::sycl::detail::device_filter_list Class Reference
cl::sycl::detail::device_filter_list Class Reference
#include <CL/sycl/detail/device_filter.hpp>
Public Member Functions
device_filter_list ()
device_filter_list (const std::string &FilterString)
device_filter_list (device_filter &Filter)
void addFilter (device_filter &Filter)
std::vector< device_filter > & get ()
bool backendCompatible (backend Backend)
bool deviceTypeCompatible (info::device_type DeviceType)
bool deviceNumberCompatible (int DeviceNum)
bool containsHost ()
Friends
std::ostream & operator<< (std::ostream &Out, const device_filter_list &List)
Detailed Description
Definition at line 37 of file device_filter.hpp.
Constructor & Destructor Documentation
device_filter_list() [1/3]
cl::sycl::detail::device_filter_list::device_filter_list () inline
Definition at line 41 of file device_filter.hpp.
device_filter_list() [2/3]
cl::sycl::detail::device_filter_list::device_filter_list (const std::string & FilterString)
Definition at line 102 of file device_filter.cpp.
device_filter_list() [3/3]
cl::sycl::detail::device_filter_list::device_filter_list (device_filter & Filter)
Definition at line 122 of file device_filter.cpp.
Member Function Documentation
addFilter()
void cl::sycl::detail::device_filter_list::addFilter (device_filter & Filter)
Definition at line 126 of file device_filter.cpp.
backendCompatible()
bool cl::sycl::detail::device_filter_list::backendCompatible (backend Backend)
Definition at line 133 of file device_filter.cpp.
References cl::sycl::all().
Referenced by cl::sycl::device::get_devices(), and cl::sycl::detail::platform_impl::get_platforms().
containsHost()
bool cl::sycl::detail::device_filter_list::containsHost ()
Definition at line 160 of file device_filter.cpp.
References cl::sycl::all().
Referenced by cl::sycl::detail::platform_impl::get_devices(), and cl::sycl::device::get_devices().
deviceNumberCompatible()
bool cl::sycl::detail::device_filter_list::deviceNumberCompatible (int DeviceNum)
Definition at line 151 of file device_filter.cpp.
deviceTypeCompatible()
bool cl::sycl::detail::device_filter_list::deviceTypeCompatible (info::device_type DeviceType)
Definition at line 142 of file device_filter.cpp.
References cl::sycl::all().
get()
std::vector<device_filter>& cl::sycl::detail::device_filter_list::get () inline
Definition at line 45 of file device_filter.hpp.
Referenced by cl::sycl::detail::filterDeviceFilter(), and cl::sycl::detail::pi::findPlugins().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & Out, const device_filter_list & List) friend
Definition at line 76 of file device_filter.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/detail/device_filter.hpp
source/detail/device_filter.cpp