DPC++ Runtime: Bucket Class Reference
Bucket Class Reference
Public Member Functions
Bucket (size_t Sz, USMAllocContext::USMAllocImpl &AllocCtx)
void * getChunk (bool &FromAllocatedSlab)
void * getSlab (bool &FromPool)
size_t getSize () const
void freeChunk (void *Ptr, Slab &Slab, bool &ToPool)
void freeSlab (Slab &Slab, bool &ToPool)
SystemMemory & getMemHandle ()
SystemMemory::MemType getMemType ()
USMAllocContext::USMAllocImpl & getUsmAllocCtx ()
bool CanPool ()
size_t SlabMinSize ()
size_t ChunkCutOff ()
size_t Capacity ()
size_t MaxPoolableSize ()
void countAlloc (bool FromPool)
void countFree ()
void updateStats (int InUse, int InPool)
void printStats ()
Detailed Description
Definition at line 401 of file usm_allocator.cpp.
Constructor & Destructor Documentation
Bucket()
Bucket::Bucket (size_t Sz, USMAllocContext::USMAllocImpl & AllocCtx) inline
Definition at line 427 of file usm_allocator.cpp.
Member Function Documentation
CanPool()
bool Bucket::CanPool ()
Definition at line 811 of file usm_allocator.cpp.
References Capacity(), settings::SetLimits::CurPoolSize, settings::SetLimits::CurPoolSizes, getMemType(), settings::SetLimits::MaxPoolSize, settings::PoolLock, and settings::USMSettings.
Referenced by freeSlab().
Capacity()
size_t Bucket::Capacity ()
Definition at line 833 of file usm_allocator.cpp.
References settings::SetLimits::Capacity, getMemType(), and settings::USMSettings.
Referenced by CanPool().
ChunkCutOff()
size_t Bucket::ChunkCutOff ()
Definition at line 839 of file usm_allocator.cpp.
References SlabMinSize().
Referenced by USMAllocContext::USMAllocImpl::allocate(), and USMAllocContext::USMAllocImpl::deallocate().
countAlloc()
void Bucket::countAlloc (bool FromPool)
Definition at line 841 of file usm_allocator.cpp.
Referenced by USMAllocContext::USMAllocImpl::allocate().
countFree()
void Bucket::countFree ()
Definition at line 847 of file usm_allocator.cpp.
Referenced by USMAllocContext::USMAllocImpl::deallocate().
freeChunk()
void Bucket::freeChunk (void * Ptr, Slab & Slab, bool & ToPool)
Definition at line 770 of file usm_allocator.cpp.
References Slab::freeChunk().
Referenced by USMAllocContext::USMAllocImpl::deallocate().
freeSlab()
void Bucket::freeSlab (Slab & Slab, bool & ToPool)
Definition at line 712 of file usm_allocator.cpp.
References CanPool(), Slab::getIterator(), settings::SetLimits::PoolTrace, updateStats(), and settings::USMSettings.
Referenced by USMAllocContext::USMAllocImpl::deallocate().
getChunk()
void * Bucket::getChunk (bool & FromAllocatedSlab)
Definition at line 753 of file usm_allocator.cpp.
Referenced by USMAllocContext::USMAllocImpl::allocate().
getMemHandle()
SystemMemory & Bucket::getMemHandle ()
Definition at line 825 of file usm_allocator.cpp.
References USMAllocContext::USMAllocImpl::getMemHandle().
Referenced by getMemType(), and Slab::~Slab().
getMemType()
SystemMemory::MemType Bucket::getMemType ()
Definition at line 827 of file usm_allocator.cpp.
References getMemHandle(), and SystemMemory::getMemType().
Referenced by CanPool(), Capacity(), MaxPoolableSize(), and SlabMinSize().
getSize()
size_t Bucket::getSize () const inline
Definition at line 439 of file usm_allocator.cpp.
Referenced by USMAllocContext::USMAllocImpl::deallocate(), Slab::getChunkSize(), operator<<(), and printStats().
getSlab()
void * Bucket::getSlab (bool & FromPool)
Definition at line 700 of file usm_allocator.cpp.
Referenced by USMAllocContext::USMAllocImpl::allocate().
getUsmAllocCtx()
USMAllocContext::USMAllocImpl& Bucket::getUsmAllocCtx () inline
Definition at line 451 of file usm_allocator.cpp.
MaxPoolableSize()
size_t Bucket::MaxPoolableSize ()
Definition at line 835 of file usm_allocator.cpp.
References getMemType(), settings::SetLimits::MaxPoolableSize, and settings::USMSettings.
printStats()
void Bucket::printStats ()
Definition at line 856 of file usm_allocator.cpp.
References getSize(), and cl::sycl::setw().
SlabMinSize()
size_t Bucket::SlabMinSize ()
Definition at line 831 of file usm_allocator.cpp.
References getMemType(), settings::SetLimits::SlabMinSize, and settings::USMSettings.
Referenced by ChunkCutOff(), and Slab::getEnd().
updateStats()
void Bucket::updateStats (int InUse, int InPool)
Definition at line 849 of file usm_allocator.cpp.
Referenced by freeSlab().
The documentation for this class was generated from the following file:
plugins/level_zero/usm_allocator.cpp