DPC++ Runtime: sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT > Class Template Reference
sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT > Class Template Reference
#include <sycl/ext/oneapi/weak_object_base.hpp>
Public Types
using object_type = SYCLObjT
Public Member Functions
constexpr weak_object_base () noexcept
weak_object_base (const SYCLObjT &SYCLObj) noexcept
weak_object_base (const weak_object_base &Other) noexcept=default
weak_object_base (weak_object_base &&Other) noexcept=default
weak_object_base & operator= (const weak_object_base &Other) noexcept=default
weak_object_base & operator= (weak_object_base &&Other) noexcept=default
void reset () noexcept
void swap (weak_object_base &Other) noexcept
bool expired () const noexcept
bool owner_before (const SYCLObjT &Other) const noexcept
bool owner_before (const weak_object_base &Other) const noexcept
Protected Member Functions
template<class Obj >
decltype(weak_object_base< Obj >::MObjWeakPtr) friend detail::getSyclWeakObjImpl (const weak_object_base< Obj > &WeakObj)
Static Protected Member Functions
static decltype(MObjWeakPtr) GetWeakImpl (const SYCLObjT &SYCLObj)
Protected Attributes
decltype(sycl::detail::getSyclObjImpl(std::declval< SYCLObjT >())) ::weak_type MObjWeakPtr
Detailed Description
template<typename SYCLObjT>
class sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >
Definition at line 29 of file weak_object_base.hpp.
Member Typedef Documentation
object_type
template<typename SYCLObjT > using sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::object_type = SYCLObjT
Definition at line 31 of file weak_object_base.hpp.
Constructor & Destructor Documentation
weak_object_base() [1/4]
template<typename SYCLObjT > constexpr sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::weak_object_base () inline constexpr noexcept
Definition at line 33 of file weak_object_base.hpp.
weak_object_base() [2/4]
template<typename SYCLObjT > sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::weak_object_base (const SYCLObjT & SYCLObj) inline noexcept
Definition at line 34 of file weak_object_base.hpp.
weak_object_base() [3/4]
template<typename SYCLObjT > sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::weak_object_base (const weak_object_base< SYCLObjT > & Other) default noexcept
weak_object_base() [4/4]
template<typename SYCLObjT > sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::weak_object_base (weak_object_base< SYCLObjT > && Other) default noexcept
Member Function Documentation
detail::getSyclWeakObjImpl()
template<typename SYCLObjT > template<class Obj > decltype(weak_object_base<Obj>::MObjWeakPtr) friend sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::detail::getSyclWeakObjImpl (const weak_object_base< Obj > & WeakObj) protected
expired()
template<typename SYCLObjT > bool sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::expired () const inline noexcept
Definition at line 47 of file weak_object_base.hpp.
References sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::MObjWeakPtr.
GetWeakImpl()
template<typename SYCLObjT > static decltype(MObjWeakPtr) sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::GetWeakImpl (const SYCLObjT & SYCLObj) inline static protected
Definition at line 69 of file weak_object_base.hpp.
References sycl::_V1::detail::getSyclObjImpl().
Referenced by sycl::_V1::ext::oneapi::weak_object< buffer< T, Dimensions, AllocatorT > >::operator=(), sycl::_V1::ext::oneapi::weak_object< stream >::operator=(), sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::operator=(), and sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::owner_before().
operator=() [1/2]
template<typename SYCLObjT > weak_object_base& sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::operator= (const weak_object_base< SYCLObjT > & Other) default noexcept
operator=() [2/2]
template<typename SYCLObjT > weak_object_base& sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::operator= (weak_object_base< SYCLObjT > && Other) default noexcept
owner_before() [1/2]
template<typename SYCLObjT > bool sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::owner_before (const SYCLObjT & Other) const inline noexcept
Definition at line 50 of file weak_object_base.hpp.
References sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::GetWeakImpl(), and sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::MObjWeakPtr.
owner_before() [2/2]
template<typename SYCLObjT > bool sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::owner_before (const weak_object_base< SYCLObjT > & Other) const inline noexcept
Definition at line 53 of file weak_object_base.hpp.
References sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::MObjWeakPtr.
reset()
template<typename SYCLObjT > void sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::reset () inline noexcept
Definition at line 42 of file weak_object_base.hpp.
References sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::MObjWeakPtr.
swap()
template<typename SYCLObjT > void sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::swap (weak_object_base< SYCLObjT > & Other) inline noexcept
Definition at line 43 of file weak_object_base.hpp.
References sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::MObjWeakPtr.
Member Data Documentation
MObjWeakPtr
template<typename SYCLObjT > decltype(sycl::detail::getSyclObjImpl(std::declval<SYCLObjT>())) ::weak_type sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::MObjWeakPtr protected
Definition at line 67 of file weak_object_base.hpp.
Referenced by sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::expired(), sycl::_V1::ext::oneapi::weak_object< buffer< T, Dimensions, AllocatorT > >::operator=(), sycl::_V1::ext::oneapi::weak_object< stream >::operator=(), sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::operator=(), sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::owner_before(), sycl::_V1::ext::oneapi::weak_object< stream >::reset(), sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::reset(), sycl::_V1::ext::oneapi::weak_object< buffer< T, Dimensions, AllocatorT > >::swap(), sycl::_V1::ext::oneapi::weak_object< stream >::swap(), sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::swap(), sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::try_lock(), sycl::_V1::ext::oneapi::weak_object< buffer< T, Dimensions, AllocatorT > >::try_lock(), and sycl::_V1::ext::oneapi::weak_object< stream >::try_lock().
The documentation for this class was generated from the following file:
include/sycl/ext/oneapi/weak_object_base.hpp