DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::root_group< Dimensions > Class Template Reference
sycl::_V1::ext::oneapi::experimental::root_group< Dimensions > Class Template Reference
#include <sycl/ext/oneapi/experimental/root_group.hpp>
Public Types
using id_type = id< Dimensions >
using range_type = range< Dimensions >
using linear_id_type = size_t
Public Member Functions
id< Dimensions > get_group_id () const
id< Dimensions > get_local_id () const
range< Dimensions > get_group_range () const
range< Dimensions > get_local_range () const
range< Dimensions > get_max_local_range () const
size_t get_group_linear_id () const
size_t get_local_linear_id () const
size_t get_group_linear_range () const
size_t get_local_linear_range () const
bool leader () const
Static Public Attributes
static constexpr int dimensions = Dimensions
static constexpr memory_scope fence_scope = memory_scope::device
Friends
root_group< Dimensions > nd_item () const
Detailed Description
template<int Dimensions>
class sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >
Definition at line 37 of file root_group.hpp.
Member Typedef Documentation
id_type
template<int Dimensions> using sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::id_type = id<Dimensions>
Definition at line 39 of file root_group.hpp.
linear_id_type
template<int Dimensions> using sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::linear_id_type = size_t
Definition at line 41 of file root_group.hpp.
range_type
template<int Dimensions> using sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::range_type = range<Dimensions>
Definition at line 40 of file root_group.hpp.
Member Function Documentation
get_group_id()
template<int Dimensions> id<Dimensions> sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_group_id () const inline
Definition at line 45 of file root_group.hpp.
get_group_linear_id()
template<int Dimensions> size_t sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_group_linear_id () const inline
Definition at line 63 of file root_group.hpp.
get_group_linear_range()
template<int Dimensions> size_t sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_group_linear_range () const inline
Definition at line 67 of file root_group.hpp.
References sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_group_range(), and sycl::_V1::range< Dimensions >::size().
get_group_range()
template<int Dimensions> range<Dimensions> sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_group_range () const inline
Definition at line 49 of file root_group.hpp.
References sycl::_V1::Dimensions.
Referenced by sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_group_linear_range().
get_local_id()
template<int Dimensions> id<Dimensions> sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_id () const inline
Definition at line 47 of file root_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::leader().
get_local_linear_id()
template<int Dimensions> size_t sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_linear_id () const inline
Definition at line 65 of file root_group.hpp.
get_local_linear_range()
template<int Dimensions> size_t sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_linear_range () const inline
Definition at line 69 of file root_group.hpp.
References sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_range(), and sycl::_V1::range< Dimensions >::size().
get_local_range()
template<int Dimensions> range<Dimensions> sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_range () const inline
Definition at line 59 of file root_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_linear_range(), and sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_max_local_range().
get_max_local_range()
template<int Dimensions> range<Dimensions> sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_max_local_range () const inline
Definition at line 61 of file root_group.hpp.
References sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_range().
leader()
template<int Dimensions> bool sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::leader () const inline
Definition at line 71 of file root_group.hpp.
References sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_local_id().
Friends And Related Function Documentation
nd_item
template<int Dimensions> root_group<Dimensions> nd_item () const friend
Member Data Documentation
dimensions
template<int Dimensions> constexpr int sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::dimensions = Dimensions static constexpr
Definition at line 42 of file root_group.hpp.
fence_scope
template<int Dimensions> constexpr memory_scope sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::fence_scope = memory_scope::device static constexpr
Definition at line 43 of file root_group.hpp.
The documentation for this class was generated from the following files:
include/sycl/detail/type_traits.hpp
include/sycl/ext/oneapi/experimental/root_group.hpp