DPC++ Runtime: cl::sycl::device_selector Class Reference
cl::sycl::device_selector Class Reference abstract
DPC++ User API » Device selectors
The device_selector class provides ability to choose the best SYCL device based on heuristics specified by the user.
#include <CL/sycl/device_selector.hpp>
Public Member Functions
virtual ~device_selector ()=default
virtual device select_device () const
virtual int operator() (const device &device) const =0
Static Protected Attributes
static constexpr int REJECT_DEVICE_SCORE = -1
Detailed Description
The device_selector class provides ability to choose the best SYCL device based on heuristics specified by the user.
See also
device
Definition at line 28 of file device_selector.hpp.
Constructor & Destructor Documentation
~device_selector()
virtual cl::sycl::device_selector::~device_selector () virtual default
Member Function Documentation
operator()()
virtual int cl::sycl::device_selector::operator() (const device & device) const pure virtual
Implemented in cl::sycl::host_selector, cl::sycl::accelerator_selector, cl::sycl::cpu_selector, cl::sycl::gpu_selector, cl::sycl::default_selector, cl::sycl::ONEAPI::filter_selector, and cl::sycl::INTEL::platform_selector.
select_device()
device cl::sycl::device_selector::select_device () const virtual
Reimplemented in cl::sycl::ONEAPI::filter_selector.
Definition at line 65 of file device_selector.cpp.
References cl::sycl::device::get_info(), cl::sycl::isDeviceOfPreferredSyclBe(), cl::sycl::isForcedDevice(), PI_DEVICE_NOT_FOUND, cl::sycl::detail::pi::PI_TRACE_ALL, cl::sycl::detail::pi::PI_TRACE_BASIC, and cl::sycl::detail::pi::trace().
Referenced by cl::sycl::device::device(), cl::sycl::platform::platform(), cl::sycl::queue::queue(), and cl::sycl::ONEAPI::filter_selector::select_device().
Member Data Documentation
REJECT_DEVICE_SCORE
constexpr int cl::sycl::device_selector::REJECT_DEVICE_SCORE = -1 static protected
Definition at line 31 of file device_selector.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/device_selector.hpp
source/device_selector.cpp