DPC++ Runtime: sycl::_V1::detail::AllocaCommandBase Class Reference
sycl::_V1::detail::AllocaCommandBase Class Reference abstract
Base class for memory allocation commands.
#include <detail/scheduler/commands.hpp>
Public Member Functions
AllocaCommandBase (CommandType Type, QueueImplPtr Queue, Requirement Req, AllocaCommandBase *LinkedAllocaCmd, bool IsConst)
ReleaseCommand * getReleaseCmd ()
SYCLMemObjI * getSYCLMemObj () const
virtual void * getMemAllocation () const =0
const Requirement * getRequirement () const final
void emitInstrumentationData () override
Instrumentation method which emits telemetry data.
bool producesPiEvent () const final
Returns true iff the command produces a PI event on non-host devices.
bool supportsPostEnqueueCleanup () const final
Returns true iff this command can be freed by post enqueue cleanup.
bool readyForCleanup () const final
Returns true iff this command is ready to be submitted for cleanup.
Public Member Functions inherited from sycl::_V1::detail::Command
Command (CommandType Type, QueueImplPtr Queue, sycl::detail::pi::PiExtCommandBuffer CommandBuffer=nullptr, const std::vector< sycl::detail::pi::PiExtSyncPoint > &SyncPoints={})
It is safe to bind MPreparedDepsEvents and MPreparedHostDepsEvents references to event_impl class members because Command should not outlive the event connected to it.
Command * addDep (DepDesc NewDep, std::vector< Command * > &ToCleanUp)
Command * addDep (EventImplPtr Event, std::vector< Command * > &ToCleanUp)
void addUser (Command *NewUser)
CommandType getType () const
virtual bool enqueue (EnqueueResultT &EnqueueResult, BlockingT Blocking, std::vector< Command * > &ToCleanUp)
Checks if the command is enqueued, and calls enqueueImp.
bool isFinished ()
bool isSuccessfullyEnqueued () const
bool isEnqueueBlocked () const
bool isBlocking () const
void addBlockedUserUnique (const EventImplPtr &NewUser)
const QueueImplPtr & getQueue () const
const EventImplPtr & getEvent () const
void emitInstrumentationDataProxy ()
Proxy method which calls emitInstrumentationData.
void resolveReleaseDependencies (std::set< Command * > &list)
Looks at all the dependencies for the release command and enables instrumentation to report these dependencies as edges.
void emitEdgeEventForCommandDependence (Command *Cmd, void *ObjAddr, bool IsCommand, std::optional< access::mode > AccMode=std::nullopt)
Creates an edge event when the dependency is a command.
void emitEdgeEventForEventDependence (Command *Cmd, sycl::detail::pi::PiEvent &EventAddr)
Creates an edge event when the dependency is an event.
void emitEnqueuedEventSignal (sycl::detail::pi::PiEvent &PiEventAddr)
Creates a signal event with the enqueued kernel event handle.
uint64_t makeTraceEventProlog (void *MAddress)
Create a trace event of node_create type; this must be guarded by a check for xptiTraceEnabled().
void makeTraceEventEpilog ()
If prolog has been run, run epilog; this must be guarded by a check for xptiTraceEnabled().
void emitInstrumentation (uint16_t Type, const char *Txt=nullptr)
Emits an event of Type.
virtual void printDot (std::ostream &Stream) const =0
virtual ~Command ()
const char * getBlockReason () const
virtual const ContextImplPtr & getWorkerContext () const
Get the context of the queue this command will be submitted to.
const QueueImplPtr & getWorkerQueue () const
Get the queue this command will be submitted to.
std::vector< sycl::detail::pi::PiEvent > getPiEvents (const std::vector< EventImplPtr > &EventImpls) const
Collect PI events from EventImpls and filter out some of them in case of in order queue.
std::vector< sycl::detail::pi::PiEvent > getPiEventsBlocking (const std::vector< EventImplPtr > &EventImpls) const
Collect PI events from EventImpls and filter out some of them in case of in order queue.
bool isHostTask () const
bool isFusable () const
const std::vector< EventImplPtr > & getPreparedHostDepsEvents () const
const std::vector< EventImplPtr > & getPreparedDepsEvents () const
void copySubmissionCodeLocation ()
void clearAllDependencies ()
Clear all dependency events This should only be used if a command is about to be deleted without being executed before that.
Public Attributes
void * MMemAllocation = nullptr
AllocaCommandBase * MLinkedAllocaCmd = nullptr
Alloca command linked with current command.
bool MIsActive = true
Indicates that current alloca is active one.
bool MIsLeaderAlloca = true
Indicates that the command owns memory allocation in case of connected alloca command.
bool MIsConst = false
Public Attributes inherited from sycl::_V1::detail::Command
std::vector< DepDesc > MDeps
Contains list of dependencies(edges)
std::unordered_set< Command * > MUsers
Contains list of commands that depend on the command.
bool MIsBlockable = false
Indicates whether the command can be blocked from enqueueing.
unsigned MLeafCounter = 0
Counts the number of memory objects this command is a leaf for.
Marks MMarks
Used for marking the node during graph traversal.
BlockReason MBlockReason
std::atomic< EnqueueResultT::ResultT > MEnqueueStatus
Describes the status of the command.
void * MTraceEvent = nullptr
The event for node_create and task_begin.
int32_t MStreamID = -1
The stream under which the traces are emitted.
void * MAddress = nullptr
Reserved for storing the object address such as SPIR-V or memory object address.
std::string MAddressString
Buffer to build the address string.
std::string MCommandNodeType
Buffer to build the command node type.
std::string MCommandName
Buffer to build the command end-user understandable name.
bool MTraceEventPrologComplete = false
Flag to indicate if makeTraceEventProlog() has been run.
bool MFirstInstance = false
Flag to indicate if this is the first time we are seeing this payload.
uint64_t MInstanceID = 0
Instance ID tracked for the command.
code_location MSubmissionCodeLocation
Represents code location of command submission to SYCL API, assigned with the valid value only if command execution is async (host task) or delayed (blocked by host task).
std::string MSubmissionFileName
Introduces string to handle memory management since code_location struct works with raw char arrays.
std::string MSubmissionFunctionName
bool MShouldCompleteEventIfPossible = true
bool MMarkedForCleanup = false
Indicates that the node will be freed by graph cleanup.
std::vector< EventImplPtr > MBlockedUsers
Contains list of commands that depends on the host command explicitly (by depends_on).
std::mutex MBlockedUsersMutex
Protected Attributes
Requirement MRequirement
ReleaseCommand MReleaseCmd
Protected Attributes inherited from sycl::_V1::detail::Command
QueueImplPtr MQueue
EventImplPtr MEvent
QueueImplPtr MWorkerQueue
std::vector< EventImplPtr > & MPreparedDepsEvents
Dependency events prepared for waiting by backend.
std::vector< EventImplPtr > & MPreparedHostDepsEvents
CommandType MType
The type of the command.
std::mutex MEnqueueMtx
Mutex used to protect enqueueing from race conditions.
sycl::detail::pi::PiExtCommandBuffer MCommandBuffer
CommandBuffer which will be used to submit to instead of the queue, if set.
std::vector< sycl::detail::pi::PiExtSyncPoint > MSyncPointDeps
List of sync points for submissions to a command buffer.
Additional Inherited Members
Public Types inherited from sycl::_V1::detail::Command
enum CommandType {
RUN_CG , COPY_MEMORY , ALLOCA , ALLOCA_SUB_BUF ,
RELEASE , MAP_MEM_OBJ , UNMAP_MEM_OBJ , UPDATE_REQUIREMENT ,
EMPTY_TASK , HOST_TASK , FUSION , EXEC_CMD_BUFFER ,
UPDATE_CMD_BUFFER
}
enum class BlockReason : int { HostAccessor = 0 , HostTask }
Protected Member Functions inherited from sycl::_V1::detail::Command
void waitForEvents (QueueImplPtr Queue, std::vector< EventImplPtr > &RawEvents, sycl::detail::pi::PiEvent &Event)
void waitForPreparedHostEvents () const
Command * processDepEvent (EventImplPtr DepEvent, const DepDesc &Dep, std::vector< Command * > &ToCleanUp)
Perform glueing of events from different contexts.
virtual pi_int32 enqueueImp ()=0
Private interface. Derived classes should implement this method.
sycl::detail::pi::PiExtCommandBuffer getCommandBuffer () const
Gets the command buffer (if any) associated with this command.
Detailed Description
Base class for memory allocation commands.
Definition at line 458 of file commands.hpp.
Constructor & Destructor Documentation
AllocaCommandBase()
sycl::_V1::detail::AllocaCommandBase::AllocaCommandBase (CommandType Type, QueueImplPtr Queue, Requirement Req, AllocaCommandBase * LinkedAllocaCmd, bool IsConst)
Definition at line 981 of file commands.cpp.
References sycl::_V1::detail::Command::emitInstrumentationDataProxy(), sycl::_V1::detail::AccessorImplHost::MAccessMode, MRequirement, and sycl::_V1::access::read_write.
Member Function Documentation
emitInstrumentationData()
void sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData () override virtual
Instrumentation method which emits telemetry data.
Implements sycl::_V1::detail::Command.
Reimplemented in sycl::_V1::detail::AllocaSubBufCommand, and sycl::_V1::detail::AllocaCommand.
Definition at line 992 of file commands.cpp.
References sycl::_V1::detail::deviceToString(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::detail::Command::MAddress, sycl::_V1::detail::Command::makeTraceEventProlog(), sycl::_V1::detail::Command::MFirstInstance, sycl::_V1::detail::Command::MQueue, MRequirement, sycl::_V1::detail::Command::MStreamID, sycl::_V1::detail::AccessorImplHost::MSYCLMemObj, and sycl::_V1::detail::Command::MTraceEvent.
getMemAllocation()
virtual void* sycl::_V1::detail::AllocaCommandBase::getMemAllocation () const pure virtual
Implemented in sycl::_V1::detail::AllocaSubBufCommand, and sycl::_V1::detail::AllocaCommand.
Referenced by sycl::_V1::detail::AllocaSubBufCommand::getMemAllocation().
getReleaseCmd()
ReleaseCommand* sycl::_V1::detail::AllocaCommandBase::getReleaseCmd () inline
Definition at line 463 of file commands.hpp.
Referenced by sycl::_V1::detail::Scheduler::waitForRecordToFinish().
getRequirement()
const Requirement* sycl::_V1::detail::AllocaCommandBase::getRequirement () const inline final virtual
Reimplemented from sycl::_V1::detail::Command.
Definition at line 469 of file commands.hpp.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::addCopyBack(), sycl::_V1::detail::AllocaCommand::AllocaCommand(), sycl::_V1::detail::AllocaSubBufCommand::AllocaSubBufCommand(), sycl::_V1::detail::Scheduler::GraphBuilder::findAllocaForReq(), and sycl::_V1::detail::insertMapUnmapForLinkedCmds().
getSYCLMemObj()
SYCLMemObjI* sycl::_V1::detail::AllocaCommandBase::getSYCLMemObj () const inline
Definition at line 465 of file commands.hpp.
Referenced by sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), sycl::_V1::detail::UnMapMemObject::emitInstrumentationData(), and sycl::_V1::detail::ReleaseCommand::printDot().
producesPiEvent()
bool sycl::_V1::detail::AllocaCommandBase::producesPiEvent () const final virtual
Returns true iff the command produces a PI event on non-host devices.
Reimplemented from sycl::_V1::detail::Command.
Definition at line 1017 of file commands.cpp.
readyForCleanup()
bool sycl::_V1::detail::AllocaCommandBase::readyForCleanup () const final virtual
Returns true iff this command is ready to be submitted for cleanup.
Reimplemented from sycl::_V1::detail::Command.
Definition at line 1021 of file commands.cpp.
supportsPostEnqueueCleanup()
bool sycl::_V1::detail::AllocaCommandBase::supportsPostEnqueueCleanup () const final virtual
Returns true iff this command can be freed by post enqueue cleanup.
Reimplemented from sycl::_V1::detail::Command.
Definition at line 1019 of file commands.cpp.
Member Data Documentation
MIsActive
bool sycl::_V1::detail::AllocaCommandBase::MIsActive = true
Indicates that current alloca is active one.
Definition at line 488 of file commands.hpp.
Referenced by sycl::_V1::detail::insertMapUnmapForLinkedCmds().
MIsConst
bool sycl::_V1::detail::AllocaCommandBase::MIsConst = false
Definition at line 494 of file commands.hpp.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::findAllocaForReq().
MIsLeaderAlloca
bool sycl::_V1::detail::AllocaCommandBase::MIsLeaderAlloca = true
Indicates that the command owns memory allocation in case of connected alloca command.
Definition at line 492 of file commands.hpp.
MLinkedAllocaCmd
AllocaCommandBase* sycl::_V1::detail::AllocaCommandBase::MLinkedAllocaCmd = nullptr
Alloca command linked with current command.
Device and host alloca commands can be linked, so they may share the same memory. Only one allocation from a pair can be accessed at a time. Alloca commands associated with such allocation is "active". In order to switch "active" status between alloca commands map/unmap operations are used.
Definition at line 486 of file commands.hpp.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), sycl::_V1::detail::insertMapUnmapForLinkedCmds(), and sycl::_V1::detail::AllocaCommand::printDot().
MMemAllocation
void* sycl::_V1::detail::AllocaCommandBase::MMemAllocation = nullptr
Definition at line 479 of file commands.hpp.
Referenced by sycl::_V1::detail::AllocaSubBufCommand::getMemAllocation(), and sycl::_V1::detail::insertMapUnmapForLinkedCmds().
MReleaseCmd
ReleaseCommand sycl::_V1::detail::AllocaCommandBase::MReleaseCmd protected
Definition at line 498 of file commands.hpp.
MRequirement
Requirement sycl::_V1::detail::AllocaCommandBase::MRequirement protected
Definition at line 497 of file commands.hpp.
Referenced by AllocaCommandBase(), emitInstrumentationData(), sycl::_V1::detail::AllocaSubBufCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaSubBufCommand::getMemAllocation(), sycl::_V1::detail::AllocaCommand::printDot(), and sycl::_V1::detail::AllocaSubBufCommand::printDot().
The documentation for this class was generated from the following files:
source/detail/scheduler/commands.hpp
source/detail/scheduler/commands.cpp