DPC++ Runtime: cl::sycl::detail::Scheduler::GraphBuilder Class Reference
cl::sycl::detail::Scheduler::GraphBuilder Class Reference
DPC++ Execution Graph
Graph builder class.
#include <detail/scheduler/scheduler.hpp>
Public Member Functions
GraphBuilder ()
Command * addCG (std::unique_ptr< detail::CG > CommandGroup, QueueImplPtr Queue, std::vector< Command * > &ToEnqueue)
Registers command group and adds it to the dependency graph.
Command * addCGUpdateHost (std::unique_ptr< detail::CG > CommandGroup, QueueImplPtr HostQueue, std::vector< Command * > &ToEnqueue)
Registers a command group that updates host memory to the latest state.
Command * addCopyBack (Requirement *Req, std::vector< Command * > &ToEnqueue)
Enqueues a command to update memory to the latest state.
Command * addHostAccessor (Requirement *Req, std::vector< Command * > &ToEnqueue)
Enqueues a command to create a host accessor.
void optimize ()
[Provisional] Optimizes the whole graph.
void optimize (EventImplPtr Event)
[Provisional] Optimizes subgraph that consists of command associated with Event passed and its dependencies.
void cleanupCommand (Command *Cmd)
void cleanupFinishedCommands (Command *FinishedCmd, std::vector< std::shared_ptr< cl::sycl::detail::stream_impl >> &, std::vector< std::shared_ptr< const void >> &)
Removes finished non-leaf non-alloca commands from the subgraph (assuming that all its commands have been waited for).
void rescheduleCommand (Command *Cmd, QueueImplPtr Queue)
Reschedules the command passed using Queue provided.
MemObjRecord * getMemObjRecord (SYCLMemObjI *MemObject)
MemObjRecord * getOrInsertMemObjRecord (const QueueImplPtr &Queue, const Requirement *Req, std::vector< Command * > &ToEnqueue)
void decrementLeafCountersForRecord (MemObjRecord *Record)
Decrements leaf counters for all leaves of the record.
void cleanupCommandsForRecord (MemObjRecord *Record, std::vector< std::shared_ptr< cl::sycl::detail::stream_impl >> &, std::vector< std::shared_ptr< const void >> &)
Removes commands that use the given MemObjRecord from the graph.
void removeRecordForMemObj (SYCLMemObjI *MemObject)
Removes the MemObjRecord for the memory object passed.
void addNodeToLeaves (MemObjRecord *Record, Command *Cmd, access::mode AccessMode, std::vector< Command * > &ToEnqueue)
Adds new command to leaves if needed.
void updateLeaves (const std::set< Command * > &Cmds, MemObjRecord *Record, access::mode AccessMode, std::vector< Command * > &ToCleanUp)
Removes commands from leaves.
Command * connectDepEvent (Command *const Cmd, EventImplPtr DepEvent, const DepDesc &Dep, std::vector< Command * > &ToCleanUp)
Perform connection of events in multiple contexts.
Public Attributes
std::vector< SYCLMemObjI * > MMemObjs
Protected Member Functions
DepDesc findDepForRecord (Command *Cmd, MemObjRecord *Record)
Finds a command dependency corresponding to the record.
AllocaCommandBase * findAllocaForReq (MemObjRecord *Record, const Requirement *Req, const ContextImplPtr &Context)
Searches for suitable alloca in memory record.
Friends
class Command
class ::MockScheduler
Detailed Description
Graph builder class.
The graph builder provides means to change an existing graph (e.g. add or remove edges/nodes).
Definition at line 473 of file scheduler.hpp.
Constructor & Destructor Documentation
GraphBuilder()
cl::sycl::detail::Scheduler::GraphBuilder::GraphBuilder ()
Definition at line 89 of file graph_builder.cpp.
Member Function Documentation
addCG()
Command * cl::sycl::detail::Scheduler::GraphBuilder::addCG (std::unique_ptr< detail::CG > CommandGroup, QueueImplPtr Queue, std::vector< Command * > & ToEnqueue)
Registers command group and adds it to the dependency graph.
See also
queue::submit, Scheduler::addCG
Returns
a command that represents command group execution.
Definition at line 916 of file graph_builder.cpp.
References cl::sycl::detail::Command::addDep(), cl::sycl::detail::combineAccessModesOfReqs(), cl::sycl::detail::Command::getType(), cl::sycl::detail::isAccessModeAllowed(), cl::sycl::detail::isInteropHostTask(), cl::sycl::detail::AccessorImplHost::MAccessMode, cl::sycl::detail::MemObjRecord::MCurContext, cl::sycl::detail::Command::MDeps, cl::sycl::detail::MemObjRecord::MHostAccess, cl::sycl::detail::CGHostTask::MQueue, cl::sycl::detail::AccessorImplHost::MSYCLMemObj, PI_OUT_OF_HOST_MEMORY, and cl::sycl::detail::sameCtx().
addCGUpdateHost()
Command * cl::sycl::detail::Scheduler::GraphBuilder::addCGUpdateHost (std::unique_ptr< detail::CG > CommandGroup, QueueImplPtr HostQueue, std::vector< Command * > & ToEnqueue)
Registers a command group that updates host memory to the latest state.
Returns
a command that represents command group execution.
Definition at line 539 of file graph_builder.cpp.
addCopyBack()
Command * cl::sycl::detail::Scheduler::GraphBuilder::addCopyBack (Requirement * Req, std::vector< Command * > & ToEnqueue)
Enqueues a command to update memory to the latest state.
Parameters
Req is a requirement, that describes memory object.
Definition at line 457 of file graph_builder.cpp.
References cl::sycl::detail::Command::addDep(), cl::sycl::detail::Command::getQueue(), cl::sycl::detail::AllocaCommandBase::getRequirement(), cl::sycl::detail::MemCpyCommandHost::getRequirement(), cl::sycl::detail::AccessorImplHost::MAccessMode, cl::sycl::detail::MemObjRecord::MCurContext, cl::sycl::detail::AccessorImplHost::MData, cl::sycl::detail::MemObjRecord::MMemModified, cl::sycl::detail::AccessorImplHost::MSYCLMemObj, and PI_OUT_OF_HOST_MEMORY.
addHostAccessor()
Command * cl::sycl::detail::Scheduler::GraphBuilder::addHostAccessor (Requirement * Req, std::vector< Command * > & ToEnqueue)
Enqueues a command to create a host accessor.
Parameters
Req points to memory being accessed.
Definition at line 503 of file graph_builder.cpp.
References cl::sycl::detail::Command::getQueue(), cl::sycl::detail::isAccessModeAllowed(), cl::sycl::detail::AccessorImplHost::MAccessMode, cl::sycl::detail::AccessorImplHost::MBlockedCmd, cl::sycl::detail::MemObjRecord::MCurContext, cl::sycl::detail::MemObjRecord::MHostAccess, and cl::sycl::detail::sameCtx().
addNodeToLeaves()
void cl::sycl::detail::Scheduler::GraphBuilder::addNodeToLeaves (MemObjRecord * Record, Command * Cmd, access::mode AccessMode, std::vector< Command * > & ToEnqueue)
Adds new command to leaves if needed.
Definition at line 255 of file graph_builder.cpp.
References cl::sycl::detail::Command::MLeafCounter, cl::sycl::detail::MemObjRecord::MReadLeaves, and cl::sycl::detail::MemObjRecord::MWriteLeaves.
cleanupCommand()
void cl::sycl::detail::Scheduler::GraphBuilder::cleanupCommand (Command * Cmd)
Definition at line 1156 of file graph_builder.cpp.
References cl::sycl::detail::Command::getEvent(), cl::sycl::detail::Command::getType(), cl::sycl::detail::Command::isSuccessfullyEnqueued(), cl::sycl::detail::DepDesc::MAllocaCmd, cl::sycl::detail::DepDesc::MDepCommand, cl::sycl::detail::Command::MDeps, cl::sycl::detail::Command::MLeafCounter, and cl::sycl::detail::Command::MUsers.
cleanupCommandsForRecord()
void cl::sycl::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord (MemObjRecord * Record, std::vector< std::shared_ptr< cl::sycl::detail::stream_impl >> & , std::vector< std::shared_ptr< const void >> &)
Removes commands that use the given MemObjRecord from the graph.
Definition at line 1046 of file graph_builder.cpp.
References cl::sycl::detail::ExecCGCommand::getStreams(), cl::sycl::detail::Command::getType(), cl::sycl::detail::MemObjRecord::MAllocaCommands, cl::sycl::detail::markNodeAsVisited(), cl::sycl::detail::DepDesc::MDepCommand, cl::sycl::detail::Command::MDeps, cl::sycl::detail::AllocaCommandBase::MLinkedAllocaCmd, cl::sycl::detail::Command::MMarks, cl::sycl::detail::Command::MUsers, and cl::sycl::detail::Command::Marks::MVisited.
cleanupFinishedCommands()
void cl::sycl::detail::Scheduler::GraphBuilder::cleanupFinishedCommands (Command * FinishedCmd, std::vector< std::shared_ptr< cl::sycl::detail::stream_impl >> & , std::vector< std::shared_ptr< const void >> &)
Removes finished non-leaf non-alloca commands from the subgraph (assuming that all its commands have been waited for).
Definition at line 1203 of file graph_builder.cpp.
References cl::sycl::detail::ExecCGCommand::getStreams(), cl::sycl::detail::Command::getType(), cl::sycl::detail::handleVisitedNodes(), cl::sycl::detail::DepDesc::MAllocaCmd, cl::sycl::detail::markNodeAsVisited(), cl::sycl::detail::DepDesc::MDepCommand, cl::sycl::detail::Command::MDeps, cl::sycl::detail::Command::MLeafCounter, cl::sycl::detail::Command::MMarks, cl::sycl::detail::Command::MPostEnqueueCleanup, cl::sycl::detail::Command::Marks::MToBeDeleted, and cl::sycl::detail::Command::MUsers.
connectDepEvent()
Command * cl::sycl::detail::Scheduler::GraphBuilder::connectDepEvent (Command *const Cmd, EventImplPtr DepEvent, const DepDesc & Dep, std::vector< Command * > & ToCleanUp)
Perform connection of events in multiple contexts.
Parameters
Cmd dependant command
DepEvent event to depend on
Dep optional DepDesc to perform connection properly
ToCleanUp container for commands that can be cleaned up due to their removal from leaves
Returns
the connecting command which is to be enqueued
Optionality of Dep is set by Dep.MDepCommand equal to nullptr.
Definition at line 1299 of file graph_builder.cpp.
References cl::sycl::detail::Command::addDep(), cl::sycl::detail::Command::addUser(), cl::sycl::detail::Command::getEvent(), cl::sycl::detail::Command::getWorkerContext(), cl::sycl::detail::DepDesc::MDepCommand, cl::sycl::detail::DepDesc::MDepRequirement, cl::sycl::detail::ExecCGCommand::MEmptyCmd, and PI_OUT_OF_HOST_MEMORY.
Referenced by cl::sycl::detail::Command::processDepEvent().
decrementLeafCountersForRecord()
void cl::sycl::detail::Scheduler::GraphBuilder::decrementLeafCountersForRecord (MemObjRecord * Record)
Decrements leaf counters for all leaves of the record.
Definition at line 1030 of file graph_builder.cpp.
References cl::sycl::detail::Command::isSuccessfullyEnqueued(), cl::sycl::detail::Command::MLeafCounter, cl::sycl::detail::MemObjRecord::MReadLeaves, cl::sycl::detail::MemObjRecord::MWriteLeaves, and cl::sycl::detail::Command::supportsPostEnqueueCleanup().
findAllocaForReq()
AllocaCommandBase * cl::sycl::detail::Scheduler::GraphBuilder::findAllocaForReq (MemObjRecord * Record, const Requirement * Req, const ContextImplPtr & Context) protected
Searches for suitable alloca in memory record.
Definition at line 630 of file graph_builder.cpp.
References cl::sycl::detail::Command::getQueue(), cl::sycl::detail::AllocaCommandBase::getRequirement(), cl::sycl::detail::SYCLMemObjI::getSize(), cl::sycl::detail::Command::getType(), cl::sycl::detail::IsSuitableSubReq(), cl::sycl::detail::MemObjRecord::MAllocaCommands, cl::sycl::detail::AccessorImplHost::MOffsetInBytes, cl::sycl::detail::AccessorImplHost::MSYCLMemObj, and cl::sycl::detail::sameCtx().
findDepForRecord()
DepDesc cl::sycl::detail::Scheduler::GraphBuilder::findDepForRecord (Command * Cmd, MemObjRecord * Record) protected
Finds a command dependency corresponding to the record.
Definition at line 616 of file graph_builder.cpp.
References cl::sycl::detail::DepDesc::MDepRequirement, cl::sycl::detail::Command::MDeps, and cl::sycl::detail::AccessorImplHost::MSYCLMemObj.
getMemObjRecord()
MemObjRecord * cl::sycl::detail::Scheduler::GraphBuilder::getMemObjRecord (SYCLMemObjI * MemObject)
Returns
a pointer to the corresponding memory object record for the SYCL memory object provided, or nullptr if it does not exist.
Definition at line 171 of file graph_builder.cpp.
References cl::sycl::detail::SYCLMemObjI::MRecord.
getOrInsertMemObjRecord()
MemObjRecord * cl::sycl::detail::Scheduler::GraphBuilder::getOrInsertMemObjRecord (const QueueImplPtr & Queue, const Requirement * Req, std::vector< Command * > & ToEnqueue)
Returns
a pointer to MemObjRecord for pointer to memory object. If the record is not found, nullptr is returned.
Definition at line 175 of file graph_builder.cpp.
References cl::sycl::detail::Command::addDep(), cl::sycl::detail::SYCLMemObjI::getInteropContext(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::detail::DepDesc::MDepCommand, cl::sycl::detail::SYCLMemObjI::MRecord, and cl::sycl::detail::AccessorImplHost::MSYCLMemObj.
optimize() [1/2]
void cl::sycl::detail::Scheduler::GraphBuilder::optimize ()
[Provisional] Optimizes the whole graph.
optimize() [2/2]
void cl::sycl::detail::Scheduler::GraphBuilder::optimize (EventImplPtr Event)
[Provisional] Optimizes subgraph that consists of command associated with Event passed and its dependencies.
removeRecordForMemObj()
void cl::sycl::detail::Scheduler::GraphBuilder::removeRecordForMemObj (SYCLMemObjI * MemObject)
Removes the MemObjRecord for the memory object passed.
Definition at line 1277 of file graph_builder.cpp.
References cl::sycl::detail::SYCLMemObjI::MRecord.
rescheduleCommand()
void cl::sycl::detail::Scheduler::GraphBuilder::rescheduleCommand (Command * Cmd, QueueImplPtr Queue)
Reschedules the command passed using Queue provided.
This can lead to rescheduling of all dependent commands. This can be used when the user provides a "secondary" queue to the submit method which may be used when the command fails to enqueue/execute in the primary queue.
updateLeaves()
void cl::sycl::detail::Scheduler::GraphBuilder::updateLeaves (const std::set< Command * > & Cmds, MemObjRecord * Record, access::mode AccessMode, std::vector< Command * > & ToCleanUp)
Removes commands from leaves.
Definition at line 235 of file graph_builder.cpp.
References cl::sycl::detail::MemObjRecord::MReadLeaves, cl::sycl::detail::MemObjRecord::MWriteLeaves, and cl::sycl::detail::LeavesCollection::remove().
Friends And Related Function Documentation
::MockScheduler
friend class ::MockScheduler friend
Definition at line 626 of file scheduler.hpp.
Command
friend class Command friend
Definition at line 623 of file scheduler.hpp.
Member Data Documentation
MMemObjs
std::vector<SYCLMemObjI *> cl::sycl::detail::Scheduler::GraphBuilder::MMemObjs
Definition at line 573 of file scheduler.hpp.
The documentation for this class was generated from the following files:
source/detail/scheduler/scheduler.hpp
source/detail/scheduler/graph_builder.cpp