DPC++ Runtime: sycl::_V1::ext::oneapi::weak_object< SYCLObjT > Class Template Reference
sycl::_V1::ext::oneapi::weak_object< SYCLObjT > Class Template Reference
#include <sycl/ext/oneapi/weak_object.hpp>
Public Types
using object_type = typename detail::weak_object_base< SYCLObjT >::object_type
Public Types inherited from sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >
using object_type = SYCLObjT
Public Member Functions
constexpr weak_object () noexcept=default
weak_object (const SYCLObjT &SYCLObj) noexcept
weak_object (const weak_object &Other) noexcept=default
weak_object (weak_object &&Other) noexcept=default
weak_object & operator= (const SYCLObjT &SYCLObj) noexcept
weak_object & operator= (const weak_object &Other) noexcept=default
weak_object & operator= (weak_object &&Other) noexcept=default
std::optional< SYCLObjT > try_lock () const noexcept
SYCLObjT lock () const
Public Member Functions inherited from sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >
constexpr weak_object_base () noexcept
weak_object_base (const SYCLObjT &SYCLObj) noexcept
weak_object_base (const weak_object_base &Other) noexcept=default
weak_object_base (weak_object_base &&Other) noexcept=default
weak_object_base & operator= (const weak_object_base &Other) noexcept=default
weak_object_base & operator= (weak_object_base &&Other) noexcept=default
void reset () noexcept
void swap (weak_object_base &Other) noexcept
bool expired () const noexcept
bool owner_before (const SYCLObjT &Other) const noexcept
bool owner_before (const weak_object_base &Other) const noexcept
Additional Inherited Members
Protected Member Functions inherited from sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >
template<class Obj >
decltype(weak_object_base< Obj >::MObjWeakPtr) friend detail::getSyclWeakObjImpl (const weak_object_base< Obj > &WeakObj)
Static Protected Member Functions inherited from sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >
static decltype(MObjWeakPtr) GetWeakImpl (const SYCLObjT &SYCLObj)
Protected Attributes inherited from sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >
decltype(sycl::detail::getSyclObjImpl(std::declval< SYCLObjT >())) ::weak_type MObjWeakPtr
Detailed Description
template<typename SYCLObjT>
class sycl::_V1::ext::oneapi::weak_object< SYCLObjT >
Definition at line 53 of file weak_object.hpp.
Member Typedef Documentation
object_type
template<typename SYCLObjT > using sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::object_type = typename detail::weak_object_base<SYCLObjT>::object_type
Definition at line 55 of file weak_object.hpp.
Constructor & Destructor Documentation
weak_object() [1/4]
template<typename SYCLObjT > constexpr sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::weak_object () constexpr default noexcept
weak_object() [2/4]
template<typename SYCLObjT > sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::weak_object (const SYCLObjT & SYCLObj) inline noexcept
Definition at line 58 of file weak_object.hpp.
weak_object() [3/4]
template<typename SYCLObjT > sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::weak_object (const weak_object< SYCLObjT > & Other) default noexcept
weak_object() [4/4]
template<typename SYCLObjT > sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::weak_object (weak_object< SYCLObjT > && Other) default noexcept
Member Function Documentation
lock()
template<typename SYCLObjT > SYCLObjT sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::lock () const inline
Definition at line 79 of file weak_object.hpp.
References sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::try_lock().
operator=() [1/3]
template<typename SYCLObjT > weak_object& sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::operator= (const SYCLObjT & SYCLObj) inline noexcept
Definition at line 63 of file weak_object.hpp.
References sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::GetWeakImpl(), and sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::MObjWeakPtr.
operator=() [2/3]
template<typename SYCLObjT > weak_object& sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::operator= (const weak_object< SYCLObjT > & Other) default noexcept
operator=() [3/3]
template<typename SYCLObjT > weak_object& sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::operator= (weak_object< SYCLObjT > && Other) default noexcept
try_lock()
template<typename SYCLObjT > std::optional<SYCLObjT> sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::try_lock () const inline noexcept
Definition at line 73 of file weak_object.hpp.
References sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::MObjWeakPtr.
Referenced by sycl::_V1::ext::oneapi::weak_object< SYCLObjT >::lock(), sycl::_V1::ext::oneapi::weak_object< buffer< T, Dimensions, AllocatorT > >::lock(), and sycl::_V1::ext::oneapi::weak_object< stream >::lock().
The documentation for this class was generated from the following files:
include/sycl/buffer.hpp
include/sycl/ext/oneapi/weak_object.hpp