DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup > Class Template Reference
sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup > Class Template Reference
#include <sycl/ext/oneapi/experimental/fixed_size_group.hpp>
Public Types
using id_type = id< 1 >
using range_type = range< 1 >
using linear_id_type = typename ParentGroup::linear_id_type
Public Member Functions
id_type get_group_id () const
id_type get_local_id () const
range_type get_group_range () const
range_type get_local_range () const
linear_id_type get_group_linear_id () const
linear_id_type get_local_linear_id () const
linear_id_type get_group_linear_range () const
linear_id_type get_local_linear_range () const
bool leader () const
Static Public Attributes
static constexpr int dimensions = 1
static constexpr sycl::memory_scope fence_scope = ParentGroup::fence_scope
Protected Member Functions
fixed_size_group ()
Friends
fixed_size_group< PartitionSize, ParentGroup > get_fixed_size_group (ParentGroup g)
sub_group_mask sycl::detail::GetMask (fixed_size_group< PartitionSize, ParentGroup > Group)
Detailed Description
template<size_t PartitionSize, typename ParentGroup>
class sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >
Definition at line 40 of file fixed_size_group.hpp.
Member Typedef Documentation
id_type
template<size_t PartitionSize, typename ParentGroup > using sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::id_type = id<1>
Definition at line 42 of file fixed_size_group.hpp.
linear_id_type
template<size_t PartitionSize, typename ParentGroup > using sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::linear_id_type = typename ParentGroup::linear_id_type
Definition at line 44 of file fixed_size_group.hpp.
range_type
template<size_t PartitionSize, typename ParentGroup > using sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::range_type = range<1>
Definition at line 43 of file fixed_size_group.hpp.
Constructor & Destructor Documentation
fixed_size_group()
template<size_t PartitionSize, typename ParentGroup > sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::fixed_size_group () inline protected
Definition at line 137 of file fixed_size_group.hpp.
Member Function Documentation
get_group_id()
template<size_t PartitionSize, typename ParentGroup > id_type sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_group_id () const inline
Definition at line 48 of file fixed_size_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_group_linear_id().
get_group_linear_id()
template<size_t PartitionSize, typename ParentGroup > linear_id_type sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_group_linear_id () const inline
Definition at line 84 of file fixed_size_group.hpp.
References sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_group_id().
get_group_linear_range()
template<size_t PartitionSize, typename ParentGroup > linear_id_type sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_group_linear_range () const inline
Definition at line 102 of file fixed_size_group.hpp.
References sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_group_range().
get_group_range()
template<size_t PartitionSize, typename ParentGroup > range_type sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_group_range () const inline
Definition at line 66 of file fixed_size_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_group_linear_range().
get_local_id()
template<size_t PartitionSize, typename ParentGroup > id_type sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_id () const inline
Definition at line 57 of file fixed_size_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_linear_id().
get_local_linear_id()
template<size_t PartitionSize, typename ParentGroup > linear_id_type sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_linear_id () const inline
Definition at line 93 of file fixed_size_group.hpp.
References sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_id().
Referenced by sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::leader().
get_local_linear_range()
template<size_t PartitionSize, typename ParentGroup > linear_id_type sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_linear_range () const inline
Definition at line 111 of file fixed_size_group.hpp.
References sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_range().
get_local_range()
template<size_t PartitionSize, typename ParentGroup > range_type sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_range () const inline
Definition at line 75 of file fixed_size_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_linear_range().
leader()
template<size_t PartitionSize, typename ParentGroup > bool sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::leader () const inline
Definition at line 120 of file fixed_size_group.hpp.
References sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::get_local_linear_id().
Friends And Related Function Documentation
get_fixed_size_group
template<size_t PartitionSize, typename ParentGroup > fixed_size_group<PartitionSize, ParentGroup> get_fixed_size_group (ParentGroup g) friend
sycl::detail::GetMask
template<size_t PartitionSize, typename ParentGroup > sub_group_mask sycl::detail::GetMask (fixed_size_group< PartitionSize, ParentGroup > Group) friend
Member Data Documentation
dimensions
template<size_t PartitionSize, typename ParentGroup > constexpr int sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::dimensions = 1 static constexpr
Definition at line 45 of file fixed_size_group.hpp.
fence_scope
template<size_t PartitionSize, typename ParentGroup > constexpr sycl::memory_scope sycl::_V1::ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup >::fence_scope = ParentGroup::fence_scope static constexpr
Definition at line 46 of file fixed_size_group.hpp.
The documentation for this class was generated from the following file:
include/sycl/ext/oneapi/experimental/fixed_size_group.hpp