DPC++ Runtime: UsmAllocationException Class Reference
UsmAllocationException Class Reference
Public Member Functions
UsmAllocationException (pi_result Err)
pi_result getError () const
Detailed Description
Definition at line 6928 of file pi_level_zero.cpp.
Constructor & Destructor Documentation
UsmAllocationException()
UsmAllocationException::UsmAllocationException (pi_result Err) inline
Definition at line 6932 of file pi_level_zero.cpp.
Member Function Documentation
getError()
pi_result UsmAllocationException::getError () const inline
Definition at line 6933 of file pi_level_zero.cpp.
Referenced by piextUSMDeviceAlloc(), piextUSMHostAlloc(), piextUSMSharedAlloc(), and USMFreeHelper().
The documentation for this class was generated from the following file:
plugins/level_zero/pi_level_zero.cpp