DPC++ Runtime: cl::sycl::property_list Class Reference
cl::sycl::property_list Class Reference
DPC++ User API
Objects of the property_list class are containers for the SYCL properties.
#include <CL/sycl/property_list.hpp>
Public Member Functions
template<typename... PropsT, typename = typename detail::enable_if_t< AllProperties<PropsT...>::value>>
property_list (PropsT... Props)
template<typename PropT >
PropT get_property () const
template<typename PropT >
bool has_property () const
void add_or_replace_accessor_properties (const property_list &PropertyList)
void delete_accessor_property (const sycl::detail::PropWithDataKind &Kind)
template<typename... T>
operator ext::oneapi::accessor_property_list< T... > ()
Friends
template<typename... PropsT>
class ext::oneapi::accessor_property_list
Additional Inherited Members
Protected Member Functions inherited from cl::sycl::detail::PropertyListBase
PropertyListBase (std::bitset< DataLessPropKind::DataLessPropKindSize > DataLessProps)
PropertyListBase (std::bitset< DataLessPropKind::DataLessPropKindSize > DataLessProps, std::vector< std::shared_ptr< PropertyWithDataBase >> PropsWithData)
void ctorHelper ()
template<typename... PropsT, class PropT >
detail::enable_if_t< std::is_base_of< DataLessPropertyBase, PropT >::value > ctorHelper (PropT &, PropsT... Props)
template<typename... PropsT, class PropT >
detail::enable_if_t< std::is_base_of< PropertyWithDataBase, PropT >::value > ctorHelper (PropT &Prop, PropsT... Props)
template<typename... PropsT, class PropT >
detail::enable_if_t< !std::is_base_of< PropertyWithDataBase, PropT >::value &&!std::is_base_of< DataLessPropertyBase, PropT >::value > ctorHelper (PropT &, PropsT... Props)
template<typename PropT >
detail::enable_if_t< std::is_base_of< DataLessPropertyBase, PropT >::value, bool > has_property_helper () const
template<typename PropT >
detail::enable_if_t< std::is_base_of< PropertyWithDataBase, PropT >::value, bool > has_property_helper () const
template<typename PropT >
detail::enable_if_t< std::is_base_of< DataLessPropertyBase, PropT >::value, PropT > get_property_helper () const
template<typename PropT >
detail::enable_if_t< std::is_base_of< PropertyWithDataBase, PropT >::value, PropT > get_property_helper () const
void add_or_replace_accessor_properties_helper (const std::vector< std::shared_ptr< PropertyWithDataBase >> &PropsWithData)
void delete_accessor_property_helper (const PropWithDataKind &Kind)
Protected Attributes inherited from cl::sycl::detail::PropertyListBase
std::bitset< DataLessPropKind::DataLessPropKindSize > MDataLessProps
std::vector< std::shared_ptr< PropertyWithDataBase > > MPropsWithData
Detailed Description
Objects of the property_list class are containers for the SYCL properties.
Definition at line 26 of file property_list.hpp.
Constructor & Destructor Documentation
property_list()
template<typename... PropsT, typename = typename detail::enable_if_t< AllProperties<PropsT...>::value>> cl::sycl::property_list::property_list (PropsT... Props) inline
Definition at line 38 of file property_list.hpp.
Member Function Documentation
add_or_replace_accessor_properties()
void cl::sycl::property_list::add_or_replace_accessor_properties (const property_list & PropertyList) inline
Definition at line 54 of file property_list.hpp.
References cl::sycl::detail::PropertyListBase::MPropsWithData.
delete_accessor_property()
void cl::sycl::property_list::delete_accessor_property (const sycl::detail::PropWithDataKind & Kind) inline
Definition at line 57 of file property_list.hpp.
get_property()
template<typename PropT > PropT cl::sycl::property_list::get_property () const inline
Definition at line 42 of file property_list.hpp.
References PI_INVALID_VALUE.
Referenced by cl::sycl::detail::MemoryManager::allocateBufferObject().
has_property()
template<typename PropT > bool cl::sycl::property_list::has_property () const inline
Definition at line 50 of file property_list.hpp.
Referenced by cl::sycl::detail::MemoryManager::allocateBufferObject(), cl::sycl::detail::buffer_impl::buffer_impl(), and cl::sycl::detail::context_impl::context_impl().
operator ext::oneapi::accessor_property_list< T... >()
template<typename... T> cl::sycl::property_list::operator ext::oneapi::accessor_property_list< T... > inline
Definition at line 19 of file property_list_conversion.hpp.
Friends And Related Function Documentation
ext::oneapi::accessor_property_list
template<typename... PropsT> friend class ext::oneapi::accessor_property_list friend
Definition at line 65 of file property_list.hpp.
The documentation for this class was generated from the following files:
include/CL/sycl/property_list.hpp
include/CL/sycl/property_list_conversion.hpp