DPC++ Runtime: cl::sycl::detail::AllocaCommandBase Class Reference
cl::sycl::detail::AllocaCommandBase Class Reference abstract
Base class for memory allocation commands.
#include <detail/scheduler/commands.hpp>
Public Member Functions
AllocaCommandBase (CommandType Type, QueueImplPtr Queue, Requirement Req, AllocaCommandBase *LinkedAllocaCmd)
ReleaseCommand * getReleaseCmd ()
SYCLMemObjI * getSYCLMemObj () const
virtual void * getMemAllocation () const =0
const Requirement * getRequirement () const final override
void emitInstrumentationData () override
Instrumentation method which emits telemetry data.
Public Member Functions inherited from cl::sycl::detail::Command
Command (CommandType Type, QueueImplPtr Queue)
void addDep (DepDesc NewDep)
void addDep (EventImplPtr Event)
void addUser (Command *NewUser)
CommandType getType () const
bool enqueue (EnqueueResultT &EnqueueResult, BlockingT Blocking)
Checks if the command is enqueued, and calls enqueueImp.
bool isFinished ()
bool isSuccessfullyEnqueued () const
std::shared_ptr< queue_impl > getQueue () const
std::shared_ptr< event_impl > getEvent () const
void emitInstrumentationDataProxy ()
Proxy method which calls emitInstrumentationData.
void resolveReleaseDependencies (std::set< Command *> &list)
Looks at all the dependencies for the release command and enables instrumentation to report these dependencies as edges.
void emitEdgeEventForCommandDependence (Command *Cmd, void *ObjAddr, const string_class &Prefix, bool IsCommand)
Creates an edge event when the dependency is a command.
void emitEdgeEventForEventDependence (Command *Cmd, RT::PiEvent &EventAddr)
Creates an edge event when the dependency is an event.
void emitEnqueuedEventSignal (RT::PiEvent &PiEventAddr)
Creates a signal event with the enqueued kernel event handle.
uint64_t makeTraceEventProlog (void *MAddress)
Create a trace event of node_create type; this must be guarded by a check for xptiTraceEnabled().
void makeTraceEventEpilog ()
If prolog has been run, run epilog; this must be guarded by a check for xptiTraceEnabled().
void emitInstrumentation (uint16_t Type, const char *Txt=nullptr)
Emits an event of Type.
virtual void printDot (std::ostream &Stream) const =0
virtual ~Command ()=default
const char * getBlockReason () const
virtual ContextImplPtr getContext () const
Public Attributes
void * MMemAllocation = nullptr
struct {
void * MWrapperImage = nullptr
} ESIMDExt
AllocaCommandBase * MLinkedAllocaCmd = nullptr
Alloca command linked with current command.
bool MIsActive = true
Indicates that current alloca is active one.
bool MIsLeaderAlloca = true
Indicates that the command owns memory allocation in case of connected alloca command.
Public Attributes inherited from cl::sycl::detail::Command
std::vector< DepDesc > MDeps
Contains list of dependencies(edges)
std::unordered_set< Command * > MUsers
Contains list of commands that depend on the command.
bool MIsBlockable = false
Indicates whether the command can be blocked from enqueueing.
unsigned MLeafCounter = 0
Counts the number of memory objects this command is a leaf for.
Marks MMarks
Used for marking the node during graph traversal.
BlockReason MBlockReason
std::atomic< EnqueueResultT::ResultT > MEnqueueStatus
Describes the status of the command.
void * MTraceEvent = nullptr
The event for node_create and task_begin.
int32_t MStreamID = -1
The stream under which the traces are emitted.
void * MAddress = nullptr
Reserved for storing the object address such as SPIRV or memory object address.
string_class MAddressString
Buffer to build the address string.
string_class MCommandNodeType
Buffer to build the command node type.
string_class MCommandName
Buffer to build the command end-user understandable name.
bool MTraceEventPrologComplete = false
Flag to indicate if makeTraceEventProlog() has been run.
bool MFirstInstance = false
Flag to indicate if this is the first time we are seeing this payload.
uint64_t MInstanceID = 0
Instance ID tracked for the command.
bool MShouldCompleteEventIfPossible = true
Protected Attributes
Requirement MRequirement
ReleaseCommand MReleaseCmd
Protected Attributes inherited from cl::sycl::detail::Command
EventImplPtr MEvent
QueueImplPtr MQueue
std::vector< EventImplPtr > MPreparedDepsEvents
Dependency events prepared for waiting by backend.
std::vector< EventImplPtr > MPreparedHostDepsEvents
CommandType MType
The type of the command.
std::mutex MEnqueueMtx
Mutex used to protect enqueueing from race conditions.
Additional Inherited Members
Public Types inherited from cl::sycl::detail::Command
enum CommandType {
RUN_CG, COPY_MEMORY, ALLOCA, ALLOCA_SUB_BUF,
RELEASE, MAP_MEM_OBJ, UNMAP_MEM_OBJ, UPDATE_REQUIREMENT,
EMPTY_TASK, HOST_TASK
}
enum BlockReason : int { BlockReason::HostAccessor = 0, BlockReason::HostTask }
Protected Member Functions inherited from cl::sycl::detail::Command
void waitForEvents (QueueImplPtr Queue, std::vector< EventImplPtr > &RawEvents, RT::PiEvent &Event)
void waitForPreparedHostEvents () const
void processDepEvent (EventImplPtr DepEvent, const DepDesc &Dep)
Perform glueing of events from different contexts.
virtual cl_int enqueueImp ()=0
Private interface. Derived classes should implement this method.
Detailed Description
Base class for memory allocation commands.
Definition at line 315 of file commands.hpp.
Constructor & Destructor Documentation
AllocaCommandBase()
cl::sycl::detail::AllocaCommandBase::AllocaCommandBase (CommandType Type, QueueImplPtr Queue, Requirement Req, AllocaCommandBase * LinkedAllocaCmd)
Definition at line 687 of file commands.cpp.
References cl::sycl::detail::Command::emitInstrumentationDataProxy(), cl::sycl::detail::AccessorImplHost::MAccessMode, MRequirement, and cl::sycl::access::read_write.
Member Function Documentation
emitInstrumentationData()
void cl::sycl::detail::AllocaCommandBase::emitInstrumentationData () override virtual
Instrumentation method which emits telemetry data.
Implements cl::sycl::detail::Command.
Reimplemented in cl::sycl::detail::AllocaSubBufCommand, and cl::sycl::detail::AllocaCommand.
Definition at line 697 of file commands.cpp.
References cl::sycl::detail::deviceToString(), cl::sycl::detail::Command::MAddress, cl::sycl::detail::Command::MAddressString, cl::sycl::detail::Command::makeTraceEventProlog(), cl::sycl::detail::Command::MFirstInstance, cl::sycl::detail::Command::MQueue, MRequirement, cl::sycl::detail::AccessorImplHost::MSYCLMemObj, and cl::sycl::detail::Command::MTraceEvent.
getMemAllocation()
virtual void* cl::sycl::detail::AllocaCommandBase::getMemAllocation () const pure virtual
Implemented in cl::sycl::detail::AllocaSubBufCommand, and cl::sycl::detail::AllocaCommand.
Referenced by cl::sycl::detail::DispatchNativeKernel(), cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), cl::sycl::detail::AllocaCommand::emitInstrumentationData(), cl::sycl::detail::MapMemObject::emitInstrumentationData(), cl::sycl::detail::UnMapMemObject::emitInstrumentationData(), cl::sycl::detail::ExecCGCommand::flushStreams(), cl::sycl::detail::MemCpyCommand::getContext(), cl::sycl::detail::MemCpyCommandHost::getContext(), cl::sycl::detail::AllocaSubBufCommand::getMemAllocation(), and cl::sycl::detail::ReverseRangeDimensionsForKernel().
getReleaseCmd()
ReleaseCommand* cl::sycl::detail::AllocaCommandBase::getReleaseCmd () inline
Definition at line 320 of file commands.hpp.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::findAllocaForReq(), and cl::sycl::detail::Scheduler::waitForRecordToFinish().
getRequirement()
const Requirement* cl::sycl::detail::AllocaCommandBase::getRequirement () const inline final override virtual
Reimplemented from cl::sycl::detail::Command.
Definition at line 326 of file commands.hpp.
Referenced by cl::sycl::detail::AllocaCommand::AllocaCommand(), cl::sycl::detail::AllocaSubBufCommand::AllocaSubBufCommand(), cl::sycl::detail::AllocaCommand::emitInstrumentationData(), cl::sycl::detail::Scheduler::GraphBuilder::findAllocaForReq(), and cl::sycl::detail::insertMapUnmapForLinkedCmds().
getSYCLMemObj()
SYCLMemObjI* cl::sycl::detail::AllocaCommandBase::getSYCLMemObj () const inline
Definition at line 322 of file commands.hpp.
Referenced by cl::sycl::detail::DispatchNativeKernel(), cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), cl::sycl::detail::AllocaCommand::emitInstrumentationData(), cl::sycl::detail::MapMemObject::emitInstrumentationData(), cl::sycl::detail::UnMapMemObject::emitInstrumentationData(), cl::sycl::detail::MemCpyCommand::emitInstrumentationData(), cl::sycl::detail::MemCpyCommandHost::emitInstrumentationData(), cl::sycl::detail::UpdateHostRequirementCommand::emitInstrumentationData(), cl::sycl::detail::MemCpyCommand::getContext(), cl::sycl::detail::MemCpyCommandHost::getContext(), cl::sycl::detail::insertMapUnmapForLinkedCmds(), and cl::sycl::detail::ReleaseCommand::printDot().
Member Data Documentation
ESIMDExt
struct { ... } cl::sycl::detail::AllocaCommandBase::ESIMDExt
Referenced by cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), cl::sycl::detail::AllocaCommand::emitInstrumentationData(), and cl::sycl::detail::ReverseRangeDimensionsForKernel().
MIsActive
bool cl::sycl::detail::AllocaCommandBase::MIsActive = true
Indicates that current alloca is active one.
Definition at line 346 of file commands.hpp.
Referenced by cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), cl::sycl::detail::Scheduler::GraphBuilder::findAllocaForReq(), and cl::sycl::detail::insertMapUnmapForLinkedCmds().
MIsLeaderAlloca
bool cl::sycl::detail::AllocaCommandBase::MIsLeaderAlloca = true
Indicates that the command owns memory allocation in case of connected alloca command.
Definition at line 350 of file commands.hpp.
Referenced by cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), and cl::sycl::detail::AllocaCommand::emitInstrumentationData().
MLinkedAllocaCmd
AllocaCommandBase* cl::sycl::detail::AllocaCommandBase::MLinkedAllocaCmd = nullptr
Alloca command linked with current command.
Device and host alloca commands can be linked, so they may share the same memory. Only one allocation from a pair can be accessed at a time. Alloca commands associated with such allocation is "active". In order to switch "active" status between alloca commands map/unmap operations are used.
Definition at line 344 of file commands.hpp.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), cl::sycl::detail::AllocaCommand::emitInstrumentationData(), cl::sycl::detail::Scheduler::GraphBuilder::findAllocaForReq(), cl::sycl::detail::insertMapUnmapForLinkedCmds(), and cl::sycl::detail::AllocaCommand::printDot().
MMemAllocation
void* cl::sycl::detail::AllocaCommandBase::MMemAllocation = nullptr
Definition at line 330 of file commands.hpp.
Referenced by cl::sycl::detail::AllocaCommand::emitInstrumentationData(), cl::sycl::detail::AllocaSubBufCommand::getMemAllocation(), and cl::sycl::detail::insertMapUnmapForLinkedCmds().
MReleaseCmd
ReleaseCommand cl::sycl::detail::AllocaCommandBase::MReleaseCmd protected
Definition at line 354 of file commands.hpp.
MRequirement
Requirement cl::sycl::detail::AllocaCommandBase::MRequirement protected
Definition at line 353 of file commands.hpp.
Referenced by AllocaCommandBase(), emitInstrumentationData(), cl::sycl::detail::AllocaSubBufCommand::emitInstrumentationData(), cl::sycl::detail::AllocaSubBufCommand::getMemAllocation(), cl::sycl::detail::AllocaCommand::printDot(), and cl::sycl::detail::AllocaSubBufCommand::printDot().
MWrapperImage
void* cl::sycl::detail::AllocaCommandBase::MWrapperImage = nullptr
Definition at line 336 of file commands.hpp.
Referenced by cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), and cl::sycl::detail::ReverseRangeDimensionsForKernel().
The documentation for this class was generated from the following files:
source/detail/scheduler/commands.hpp
source/detail/scheduler/commands.cpp