DPC++ Runtime: sycl::_V1::detail::PersistentDeviceCodeCache Class Reference
sycl::_V1::detail::PersistentDeviceCodeCache Class Reference
#include <detail/persistent_device_code_cache.hpp>
Static Public Member Functions
static std::string getCacheItemPath (const device &Device, const RTDeviceBinaryImage &Img, const SerializedObj &SpecConsts, const std::string &BuildOptionsString)
static std::vector< std::vector< char > > getItemFromDisc (const device &Device, const RTDeviceBinaryImage &Img, const SerializedObj &SpecConsts, const std::string &BuildOptionsString)
static void putItemToDisc (const device &Device, const RTDeviceBinaryImage &Img, const SerializedObj &SpecConsts, const std::string &BuildOptionsString, const sycl::detail::pi::PiProgram &NativePrg)
static void trace (const std::string &msg)
Detailed Description
Definition at line 59 of file persistent_device_code_cache.hpp.
Member Function Documentation
getCacheItemPath()
std::string sycl::_V1::detail::PersistentDeviceCodeCache::getCacheItemPath (const device & Device, const RTDeviceBinaryImage & Img, const SerializedObj & SpecConsts, const std::string & BuildOptionsString) static
Definition at line 341 of file persistent_device_code_cache.cpp.
References pi_device_binary_struct::BinaryStart, sycl::_V1::detail::RTDeviceBinaryImage::getRawData(), sycl::_V1::detail::RTDeviceBinaryImage::getSize(), and trace().
Referenced by getItemFromDisc(), and putItemToDisc().
getItemFromDisc()
std::vector< std::vector< char > > sycl::_V1::detail::PersistentDeviceCodeCache::getItemFromDisc (const device & Device, const RTDeviceBinaryImage & Img, const SerializedObj & SpecConsts, const std::string & BuildOptionsString) static
Definition at line 162 of file persistent_device_code_cache.cpp.
References getCacheItemPath(), sycl::_V1::detail::LockCacheItem::isLocked(), sycl::_V1::detail::OSUtil::isPathPresent(), and trace().
Referenced by sycl::_V1::detail::ProgramManager::getOrCreatePIProgram().
putItemToDisc()
void sycl::_V1::detail::PersistentDeviceCodeCache::putItemToDisc (const device & Device, const RTDeviceBinaryImage & Img, const SerializedObj & SpecConsts, const std::string & BuildOptionsString, const sycl::detail::pi::PiProgram & NativePrg) static
Definition at line 91 of file persistent_device_code_cache.cpp.
References getCacheItemPath(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::detail::OSUtil::isPathPresent(), sycl::_V1::detail::OSUtil::makeDir(), PI_PROGRAM_INFO_BINARIES, PI_PROGRAM_INFO_BINARY_SIZES, PI_PROGRAM_INFO_NUM_DEVICES, piProgramGetInfo(), and trace().
Referenced by sycl::_V1::detail::ProgramManager::getBuiltPIProgram().
trace()
static void sycl::_V1::detail::PersistentDeviceCodeCache::trace (const std::string & msg) inline static
Definition at line 188 of file persistent_device_code_cache.hpp.
References std::cerr, and sycl::_V1::detail::SYCLConfig< Config >::get().
Referenced by getCacheItemPath(), getItemFromDisc(), sycl::_V1::detail::LockCacheItem::LockCacheItem(), putItemToDisc(), and sycl::_V1::detail::LockCacheItem::~LockCacheItem().
The documentation for this class was generated from the following files:
source/detail/persistent_device_code_cache.hpp
source/detail/persistent_device_code_cache.cpp