DPC++ Runtime: cl::sycl::detail::kernel_bundle_impl Class Reference
cl::sycl::detail::kernel_bundle_impl Class Reference
#include <detail/kernel_bundle_impl.hpp>
Public Member Functions
kernel_bundle_impl (context Ctx, std::vector< device > Devs, bundle_state State)
kernel_bundle_impl (context Ctx, std::vector< device > Devs)
kernel_bundle_impl (context Ctx, std::vector< device > Devs, device_image_plain &DevImage)
kernel_bundle_impl (const kernel_bundle< bundle_state::input > &InputBundle, std::vector< device > Devs, const property_list &PropList, bundle_state TargetState)
kernel_bundle_impl (const std::vector< kernel_bundle< bundle_state::object >> &ObjectBundles, std::vector< device > Devs, const property_list &PropList)
kernel_bundle_impl (context Ctx, std::vector< device > Devs, const std::vector< kernel_id > &KernelIDs, bundle_state State)
kernel_bundle_impl (context Ctx, std::vector< device > Devs, const DevImgSelectorImpl &Selector, bundle_state State)
kernel_bundle_impl (const std::vector< detail::KernelBundleImplPtr > &Bundles, bundle_state State)
bool empty () const noexcept
backend get_backend () const noexcept
context get_context () const noexcept
const std::vector< device > & get_devices () const noexcept
std::vector< kernel_id > get_kernel_ids () const
kernel get_kernel (const kernel_id &KernelID, const std::shared_ptr< detail::kernel_bundle_impl > &Self) const
bool has_kernel (const kernel_id &KernelID) const noexcept
bool has_kernel (const kernel_id &KernelID, const device &Dev) const noexcept
bool contains_specialization_constants () const noexcept
bool native_specialization_constant () const noexcept
bool has_specialization_constant (const char *SpecName) const noexcept
void set_specialization_constant_raw_value (const char *SpecName, const void *Value, size_t Size) noexcept
void get_specialization_constant_raw_value (const char *SpecName, void *ValueRet) const noexcept
bool is_specialization_constant_set (const char *SpecName) const noexcept
const device_image_plain * begin () const
const device_image_plain * end () const
size_t size () const noexcept
bundle_state get_bundle_state () const
const SpecConstMapT & get_spec_const_map_ref () const noexcept
bool isInterop () const
bool add_kernel (const kernel_id &KernelID, const device &Dev)
Detailed Description
Definition at line 50 of file kernel_bundle_impl.hpp.
Constructor & Destructor Documentation
kernel_bundle_impl() [1/8]
cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, bundle_state State) inline
Definition at line 75 of file kernel_bundle_impl.hpp.
kernel_bundle_impl() [2/8]
cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs) inline
Definition at line 85 of file kernel_bundle_impl.hpp.
References cl::sycl::detail::checkAllDevicesAreInContext(), cl::sycl::executable, and cl::sycl::make_error_code().
kernel_bundle_impl() [3/8]
cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, device_image_plain & DevImage) inline
Definition at line 96 of file kernel_bundle_impl.hpp.
kernel_bundle_impl() [4/8]
cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl (const kernel_bundle< bundle_state::input > & InputBundle, std::vector< device > Devs, const property_list & PropList, bundle_state TargetState) inline
Definition at line 105 of file kernel_bundle_impl.hpp.
References all_of(), cl::sycl::build(), cl::sycl::compile(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::make_error_code(), none_of(), and PI_INVALID_OPERATION.
kernel_bundle_impl() [5/8]
cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl (const std::vector< kernel_bundle< bundle_state::object >> & ObjectBundles, std::vector< device > Devs, const property_list & PropList) inline
Definition at line 156 of file kernel_bundle_impl.hpp.
References all_of(), cl::sycl::executable, and cl::sycl::make_error_code().
kernel_bundle_impl() [6/8]
cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, const std::vector< kernel_id > & KernelIDs, bundle_state State) inline
Definition at line 236 of file kernel_bundle_impl.hpp.
kernel_bundle_impl() [7/8]
cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl (context Ctx, std::vector< device > Devs, const DevImgSelectorImpl & Selector, bundle_state State) inline
Definition at line 249 of file kernel_bundle_impl.hpp.
kernel_bundle_impl() [8/8]
cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl (const std::vector< detail::KernelBundleImplPtr > & Bundles, bundle_state State) inline
Definition at line 260 of file kernel_bundle_impl.hpp.
References cl::sycl::detail::for_each(), cl::sycl::detail::getSyclObjImpl(), and cl::sycl::make_error_code().
Member Function Documentation
add_kernel()
bool cl::sycl::detail::kernel_bundle_impl::add_kernel (const kernel_id & KernelID, const device & Dev) inline
Definition at line 488 of file kernel_bundle_impl.hpp.
References cl::sycl::detail::getSyclObjImpl().
begin()
const device_image_plain* cl::sycl::detail::kernel_bundle_impl::begin () const inline
Definition at line 472 of file kernel_bundle_impl.hpp.
contains_specialization_constants()
bool cl::sycl::detail::kernel_bundle_impl::contains_specialization_constants () const inline noexcept
Definition at line 400 of file kernel_bundle_impl.hpp.
References any_of().
empty()
bool cl::sycl::detail::kernel_bundle_impl::empty () const inline noexcept
Definition at line 328 of file kernel_bundle_impl.hpp.
end()
const device_image_plain* cl::sycl::detail::kernel_bundle_impl::end () const inline
Definition at line 474 of file kernel_bundle_impl.hpp.
get_backend()
backend cl::sycl::detail::kernel_bundle_impl::get_backend () const inline noexcept
Definition at line 330 of file kernel_bundle_impl.hpp.
get_bundle_state()
bundle_state cl::sycl::detail::kernel_bundle_impl::get_bundle_state () const inline
Definition at line 480 of file kernel_bundle_impl.hpp.
get_context()
context cl::sycl::detail::kernel_bundle_impl::get_context () const inline noexcept
Definition at line 334 of file kernel_bundle_impl.hpp.
get_devices()
const std::vector<device>& cl::sycl::detail::kernel_bundle_impl::get_devices () const inline noexcept
Definition at line 336 of file kernel_bundle_impl.hpp.
get_kernel()
kernel cl::sycl::detail::kernel_bundle_impl::get_kernel (const kernel_id & KernelID, const std::shared_ptr< detail::kernel_bundle_impl > & Self) const inline
Definition at line 357 of file kernel_bundle_impl.hpp.
References cl::sycl::kernel_id::get_name(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::make_error_code(), and cl::sycl::detail::tie().
get_kernel_ids()
std::vector<kernel_id> cl::sycl::detail::kernel_bundle_impl::get_kernel_ids () const inline
Definition at line 338 of file kernel_bundle_impl.hpp.
References cl::sycl::detail::getSyclObjImpl().
get_spec_const_map_ref()
const SpecConstMapT& cl::sycl::detail::kernel_bundle_impl::get_spec_const_map_ref () const inline noexcept
Definition at line 482 of file kernel_bundle_impl.hpp.
get_specialization_constant_raw_value()
void cl::sycl::detail::kernel_bundle_impl::get_specialization_constant_raw_value (const char * SpecName, void * ValueRet) const inline noexcept
Definition at line 439 of file kernel_bundle_impl.hpp.
References cl::sycl::detail::getSyclObjImpl().
has_kernel() [1/2]
bool cl::sycl::detail::kernel_bundle_impl::has_kernel (const kernel_id & KernelID) const inline noexcept
Definition at line 385 of file kernel_bundle_impl.hpp.
References any_of().
has_kernel() [2/2]
bool cl::sycl::detail::kernel_bundle_impl::has_kernel (const kernel_id & KernelID, const device & Dev) const inline noexcept
Definition at line 392 of file kernel_bundle_impl.hpp.
References any_of().
has_specialization_constant()
bool cl::sycl::detail::kernel_bundle_impl::has_specialization_constant (const char * SpecName) const inline noexcept
Definition at line 416 of file kernel_bundle_impl.hpp.
References any_of().
is_specialization_constant_set()
bool cl::sycl::detail::kernel_bundle_impl::is_specialization_constant_set (const char * SpecName) const inline noexcept
Definition at line 462 of file kernel_bundle_impl.hpp.
References any_of().
isInterop()
bool cl::sycl::detail::kernel_bundle_impl::isInterop () const inline
Definition at line 486 of file kernel_bundle_impl.hpp.
native_specialization_constant()
bool cl::sycl::detail::kernel_bundle_impl::native_specialization_constant () const inline noexcept
Definition at line 408 of file kernel_bundle_impl.hpp.
References all_of().
set_specialization_constant_raw_value()
void cl::sycl::detail::kernel_bundle_impl::set_specialization_constant_raw_value (const char * SpecName, const void * Value, size_t Size) inline noexcept
Definition at line 424 of file kernel_bundle_impl.hpp.
References cl::sycl::detail::getSyclObjImpl().
size()
size_t cl::sycl::detail::kernel_bundle_impl::size () const inline noexcept
Definition at line 478 of file kernel_bundle_impl.hpp.
The documentation for this class was generated from the following file:
source/detail/kernel_bundle_impl.hpp