DPC++ Runtime: cl::sycl::queue Class Reference
cl::sycl::queue Class Reference
DPC++ User API
Encapsulates a single SYCL queue which schedules kernels on a SYCL device.
#include <CL/sycl/queue.hpp>
Public Member Functions
queue (const property_list &PropList={})
Constructs a SYCL queue instance using the device returned by an instance of default_selector.
queue (const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL queue instance with an async_handler using the device returned by an instance of default_selector.
queue (const device_selector &DeviceSelector, const property_list &PropList={})
Constructs a SYCL queue instance using the device returned by the DeviceSelector provided.
queue (const device_selector &DeviceSelector, const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL queue instance with an async_handler using the device returned by the DeviceSelector provided.
queue (const device &SyclDevice, const property_list &PropList={})
Constructs a SYCL queue instance using the device provided.
queue (const device &SyclDevice, const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL queue instance with an async_handler using the device provided.
queue (const context &SyclContext, const device_selector &DeviceSelector, const property_list &PropList={})
Constructs a SYCL queue instance that is associated with the context provided, using the device returned by the device selector.
queue (const context &SyclContext, const device_selector &DeviceSelector, const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL queue instance with an async_handler that is associated with the context provided, using the device returned by the device selector.
queue (const context &SyclContext, const device &SyclDevice, const property_list &PropList={})
Constructs a SYCL queue associated with the given context, device and optional properties list.
queue (const context &SyclContext, const device &SyclDevice, const async_handler &AsyncHandler, const property_list &PropList={})
Constructs a SYCL queue associated with the given context, device, asynchronous exception handler and optional properties list.
queue (const queue &RHS)=default
Constructs a SYCL queue with an optional async_handler from an OpenCL cl_command_queue.
queue (queue &&RHS)=default
queue & operator= (const queue &RHS)=default
queue & operator= (queue &&RHS)=default
bool operator== (const queue &RHS) const
bool operator!= (const queue &RHS) const
context get_context () const
device get_device () const
bool is_host () const
template<info::queue param>
info::param_traits< info::queue, param >::return_type get_info () const
Queries SYCL queue for information.
template<typename T >
event submit (T CGF _CODELOCPARAM(&CodeLoc))
Submits a command group function object to the queue, in order to be scheduled for execution on the device.
template<typename T >
event submit (T CGF, queue &SecondaryQueue _CODELOCPARAM(&CodeLoc))
Submits a command group function object to the queue, in order to be scheduled for execution on the device.
event ext_oneapi_submit_barrier (_CODELOCONLYPARAM(&CodeLoc))
Prevents any commands submitted afterward to this queue from executing until all commands previously submitted to this queue have entered the complete state.
event submit_barrier (_CODELOCONLYPARAM(&CodeLoc))
Prevents any commands submitted afterward to this queue from executing until all commands previously submitted to this queue have entered the complete state.
event ext_oneapi_submit_barrier (const std::vector< event > &WaitList _CODELOCPARAM(&CodeLoc))
Prevents any commands submitted afterward to this queue from executing until all events in WaitList have entered the complete state.
event submit_barrier (const std::vector< event > &WaitList _CODELOCPARAM(&CodeLoc))
Prevents any commands submitted afterward to this queue from executing until all events in WaitList have entered the complete state.
void wait (_CODELOCONLYPARAM(&CodeLoc))
Performs a blocking wait for the completion of all enqueued tasks in the queue.
void wait_and_throw (_CODELOCONLYPARAM(&CodeLoc))
Performs a blocking wait for the completion of all enqueued tasks in the queue.
void wait_proxy (const detail::code_location &CodeLoc)
Proxy method for wait to forward the code location information to the implementation.
void wait_and_throw_proxy (const detail::code_location &CodeLoc)
Proxy method for wait_and_throw to forward the code location information to the implementation.
void throw_asynchronous ()
Checks if any asynchronous errors have been produced by the queue and if so reports them to the async_handler passed on the queue construction.
template<typename PropertyT >
bool has_property () const
template<typename PropertyT >
PropertyT get_property () const
template<typename T >
event fill (void *Ptr, const T &Pattern, size_t Count)
Fills the specified memory with the specified pattern.
template<typename T >
event fill (void *Ptr, const T &Pattern, size_t Count, event DepEvent)
Fills the specified memory with the specified pattern.
template<typename T >
event fill (void *Ptr, const T &Pattern, size_t Count, const std::vector< event > &DepEvents)
Fills the specified memory with the specified pattern.
event memset (void *Ptr, int Value, size_t Count)
Fills the memory pointed by a USM pointer with the value specified.
event memset (void *Ptr, int Value, size_t Count, event DepEvent)
Fills the memory pointed by a USM pointer with the value specified.
event memset (void *Ptr, int Value, size_t Count, const std::vector< event > &DepEvents)
Fills the memory pointed by a USM pointer with the value specified.
event memcpy (void *Dest, const void *Src, size_t Count)
Copies data from one memory region to another, both pointed by USM pointers.
event memcpy (void *Dest, const void *Src, size_t Count, event DepEvent)
Copies data from one memory region to another, both pointed by USM pointers.
event memcpy (void *Dest, const void *Src, size_t Count, const std::vector< event > &DepEvents)
Copies data from one memory region to another, both pointed by USM pointers.
template<typename T >
event copy (const T *Src, T *Dest, size_t Count)
Copies data from one memory region to another, both pointed by USM pointers.
template<typename T >
event copy (const T *Src, T *Dest, size_t Count, event DepEvent)
Copies data from one memory region to another, both pointed by USM pointers.
template<typename T >
event copy (const T *Src, T *Dest, size_t Count, const std::vector< event > &DepEvents)
Copies data from one memory region to another, both pointed by USM pointers.
event mem_advise (const void *Ptr, size_t Length, pi_mem_advice Advice)
Provides additional information to the underlying runtime about how different allocations are used.
event mem_advise (const void *Ptr, size_t Length, int Advice)
Provides additional information to the underlying runtime about how different allocations are used.
event mem_advise (const void *Ptr, size_t Length, int Advice, event DepEvent)
Provides additional information to the underlying runtime about how different allocations are used.
event mem_advise (const void *Ptr, size_t Length, int Advice, const std::vector< event > &DepEvents)
Provides additional information to the underlying runtime about how different allocations are used.
event prefetch (const void *Ptr, size_t Count)
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
event prefetch (const void *Ptr, size_t Count, event DepEvent)
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
event prefetch (const void *Ptr, size_t Count, const std::vector< event > &DepEvents)
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
template<typename KernelName = detail::auto_name, typename KernelType >
event single_task (_KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename KernelType >
event single_task (event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename KernelType >
event single_task (const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
single_task version with a kernel represented as a lambda.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 1 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 2 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 3 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 1 > NumWorkItems, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 2 > NumWorkItems, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 3 > NumWorkItems, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 1 > NumWorkItems, const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 2 > NumWorkItems, const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType >
event parallel_for (range< 3 > NumWorkItems, const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for (nd_range< Dims > ExecutionRange, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for (nd_range< Dims > ExecutionRange, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims>
event parallel_for (nd_range< Dims > ExecutionRange, const std::vector< event > &DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
template<typename KernelName = detail::auto_name, typename KernelType , int Dims, typename Reduction >
event parallel_for (nd_range< Dims > ExecutionRange, Reduction Redu, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM(&CodeLoc))
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
bool is_in_order () const
Returns whether the queue is in order or OoO.
backend get_backend () const noexcept
Returns the backend associated with this queue.
template<backend Backend>
backend_return_t< Backend, queue > get_native () const
Gets the native handle of the SYCL queue.
Friends
template<class T >
T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Detailed Description
Encapsulates a single SYCL queue which schedules kernels on a SYCL device.
A SYCL queue can be used to submit command groups to be executed by the SYCL runtime.
See also
device
handler
event
kernel
Definition at line 103 of file queue.hpp.
Constructor & Destructor Documentation
queue() [1/12]
cl::sycl::queue::queue (const property_list & PropList = {}) inline explicit
Constructs a SYCL queue instance using the device returned by an instance of default_selector.
Parameters
PropList is a list of properties for queue construction.
Definition at line 109 of file queue.hpp.
queue() [2/12]
cl::sycl::queue::queue (const async_handler & AsyncHandler, const property_list & PropList = {}) inline
Constructs a SYCL queue instance with an async_handler using the device returned by an instance of default_selector.
Parameters
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 117 of file queue.hpp.
queue() [3/12]
cl::sycl::queue::queue (const device_selector & DeviceSelector, const property_list & PropList = {}) inline
Constructs a SYCL queue instance using the device returned by the DeviceSelector provided.
Parameters
DeviceSelector is an instance of SYCL device selector.
PropList is a list of properties for queue construction.
Definition at line 125 of file queue.hpp.
queue() [4/12]
cl::sycl::queue::queue (const device_selector & DeviceSelector, const async_handler & AsyncHandler, const property_list & PropList = {}) inline
Constructs a SYCL queue instance with an async_handler using the device returned by the DeviceSelector provided.
Parameters
DeviceSelector is an instance of SYCL device selector.
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 135 of file queue.hpp.
queue() [5/12]
cl::sycl::queue::queue (const device & SyclDevice, const property_list & PropList = {}) inline explicit
Constructs a SYCL queue instance using the device provided.
Parameters
SyclDevice is an instance of SYCL device.
PropList is a list of properties for queue construction.
Definition at line 143 of file queue.hpp.
queue() [6/12]
cl::sycl::queue::queue (const device & SyclDevice, const async_handler & AsyncHandler, const property_list & PropList = {}) explicit
Constructs a SYCL queue instance with an async_handler using the device provided.
Parameters
SyclDevice is an instance of SYCL device.
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 46 of file queue.cpp.
References cl::sycl::detail::getSyclObjImpl().
queue() [7/12]
cl::sycl::queue::queue (const context & SyclContext, const device_selector & DeviceSelector, const property_list & PropList = {})
Constructs a SYCL queue instance that is associated with the context provided, using the device returned by the device selector.
Parameters
SyclContext is an instance of SYCL context.
DeviceSelector is an instance of SYCL device selector.
PropList is a list of properties for queue construction.
Definition at line 59 of file queue.cpp.
queue() [8/12]
cl::sycl::queue::queue (const context & SyclContext, const device_selector & DeviceSelector, const async_handler & AsyncHandler, const property_list & PropList = {})
Constructs a SYCL queue instance with an async_handler that is associated with the context provided, using the device returned by the device selector.
Parameters
SyclContext is an instance of SYCL context.
DeviceSelector is an instance of SYCL device selector.
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 23 of file queue.cpp.
References cl::sycl::context::get_devices(), and cl::sycl::detail::getSyclObjImpl().
queue() [9/12]
cl::sycl::queue::queue (const context & SyclContext, const device & SyclDevice, const property_list & PropList = {})
Constructs a SYCL queue associated with the given context, device and optional properties list.
Parameters
SyclContext is an instance of SYCL context.
SyclDevice is an instance of SYCL device.
PropList is a list of properties for queue construction.
Definition at line 65 of file queue.cpp.
queue() [10/12]
cl::sycl::queue::queue (const context & SyclContext, const device & SyclDevice, const async_handler & AsyncHandler, const property_list & PropList = {})
Constructs a SYCL queue associated with the given context, device, asynchronous exception handler and optional properties list.
Parameters
SyclContext is an instance of SYCL context.
SyclDevice is an instance of SYCL device.
AsyncHandler is a SYCL asynchronous exception handler.
PropList is a list of properties for queue construction.
Definition at line 39 of file queue.cpp.
References cl::sycl::detail::getSyclObjImpl().
queue() [11/12]
cl::sycl::queue::queue (const queue & RHS) default
Constructs a SYCL queue with an optional async_handler from an OpenCL cl_command_queue.
The instance of cl_command_queue is retained on construction.
Parameters
ClQueue is a valid instance of OpenCL queue.
SyclContext is a valid SYCL context.
AsyncHandler is a SYCL asynchronous exception handler.
queue() [12/12]
cl::sycl::queue::queue (queue && RHS) default
Member Function Documentation
copy() [1/3]
template<typename T > event cl::sycl::queue::copy (const T * Src, T * Dest, size_t Count) inline
Copies data from one memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
Count is a number of elements of type T to copy.
Returns
an event representing copy operation.
Definition at line 563 of file queue.hpp.
References cl::sycl::detail::memcpy().
copy() [2/3]
template<typename T > event cl::sycl::queue::copy (const T * Src, T * Dest, size_t Count, const std::vector< event > & DepEvents) inline
Copies data from one memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
Count is a number of elements of type T to copy.
DepEvents is a vector of events that specifies the kernel
Returns
an event representing copy operation.
Definition at line 595 of file queue.hpp.
References cl::sycl::detail::memcpy().
copy() [3/3]
template<typename T > event cl::sycl::queue::copy (const T * Src, T * Dest, size_t Count, event DepEvent) inline
Copies data from one memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Src is a USM pointer to the source memory.
Dest is a USM pointer to the destination memory.
Count is a number of elements of type T to copy.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing copy operation.
Definition at line 579 of file queue.hpp.
References cl::sycl::detail::memcpy().
ext_oneapi_submit_barrier() [1/2]
event cl::sycl::queue::ext_oneapi_submit_barrier (_CODELOCONLYPARAM & CodeLoc) inline
Prevents any commands submitted afterward to this queue from executing until all commands previously submitted to this queue have entered the complete state.
Parameters
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object, which corresponds to the queue the command group is being enqueued on.
Definition at line 333 of file queue.hpp.
References _CODELOCFW, and cl::sycl::handler::ext_oneapi_barrier().
ext_oneapi_submit_barrier() [2/2]
event cl::sycl::queue::ext_oneapi_submit_barrier (const std::vector< event > &WaitList _CODELOCPARAM & CodeLoc) inline
Prevents any commands submitted afterward to this queue from executing until all events in WaitList have entered the complete state.
If WaitList is empty, then ext_oneapi_submit_barrier has no effect.
Parameters
WaitList is a vector of valid SYCL events that need to complete before barrier command can be executed.
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object, which corresponds to the queue the command group is being enqueued on.
Definition at line 360 of file queue.hpp.
References _CODELOCFW, and cl::sycl::handler::ext_oneapi_barrier().
fill() [1/3]
template<typename T > event cl::sycl::queue::fill (void * Ptr, const T & Pattern, size_t Count) inline
Fills the specified memory with the specified pattern.
Parameters
Ptr is the pointer to the memory to fill.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Count is the number of times to fill Pattern into Ptr.
Returns
an event representing fill operation.
Definition at line 438 of file queue.hpp.
References cl::sycl::handler::fill().
fill() [2/3]
template<typename T > event cl::sycl::queue::fill (void * Ptr, const T & Pattern, size_t Count, const std::vector< event > & DepEvents) inline
Fills the specified memory with the specified pattern.
Parameters
Ptr is the pointer to the memory to fill.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Count is the number of times to fill Pattern into Ptr.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing fill operation.
Definition at line 468 of file queue.hpp.
References cl::sycl::handler::depends_on(), and cl::sycl::handler::fill().
fill() [3/3]
template<typename T > event cl::sycl::queue::fill (void * Ptr, const T & Pattern, size_t Count, event DepEvent) inline
Fills the specified memory with the specified pattern.
Parameters
Ptr is the pointer to the memory to fill.
Pattern is the pattern to fill into the memory. T should be trivially copyable.
Count is the number of times to fill Pattern into Ptr.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing fill operation.
Definition at line 451 of file queue.hpp.
References cl::sycl::handler::depends_on(), and cl::sycl::handler::fill().
get_backend()
backend cl::sycl::queue::get_backend () const noexcept
Returns the backend associated with this queue.
Returns
the backend associated with this queue.
Definition at line 202 of file queue.cpp.
References cl::sycl::detail::getImplBackend().
get_context()
context cl::sycl::queue::get_context () const
Returns
a valid instance of OpenCL queue, which is retained before being returned.
an associated SYCL context.
Definition at line 73 of file queue.cpp.
Referenced by cl::sycl::aligned_alloc(), cl::sycl::aligned_alloc_device(), cl::sycl::aligned_alloc_host(), cl::sycl::aligned_alloc_shared(), cl::sycl::free(), cl::sycl::malloc(), cl::sycl::malloc_device(), cl::sycl::malloc_host(), and cl::sycl::malloc_shared().
get_device()
device cl::sycl::queue::get_device () const
Returns
SYCL device this queue was constructed with.
Definition at line 75 of file queue.cpp.
Referenced by cl::sycl::aligned_alloc(), cl::sycl::aligned_alloc_device(), cl::sycl::aligned_alloc_shared(), cl::sycl::malloc(), cl::sycl::malloc_device(), and cl::sycl::malloc_shared().
get_info()
template<info::queue Param> info::param_traits< info::queue, Param >::return_type cl::sycl::queue::get_info
Queries SYCL queue for information.
The return type depends on information being queried.
Definition at line 168 of file queue.cpp.
get_native()
template<backend Backend> backend_return_t<Backend, queue> cl::sycl::queue::get_native () const inline
Gets the native handle of the SYCL queue.
Returns
a native handle, the type of which defined by the backend.
Definition at line 1062 of file queue.hpp.
get_property()
template<typename PropertyT > PropertyT cl::sycl::queue::get_property
Returns
a copy of the property of type PropertyT that the queue was constructed with. If the queue was not constructed with the PropertyT property, an invalid_object_error SYCL exception.
Definition at line 184 of file queue.cpp.
has_property()
template<typename PropertyT > bool cl::sycl::queue::has_property
Returns
true if the queue was constructed with property specified by PropertyT.
Definition at line 180 of file queue.cpp.
is_host()
bool cl::sycl::queue::is_host () const
Returns
true if this queue is a SYCL host queue.
Definition at line 77 of file queue.cpp.
Referenced by submit().
is_in_order()
bool cl::sycl::queue::is_in_order () const
Returns whether the queue is in order or OoO.
Equivalent to has_property<property::queue::in_order>()
Definition at line 198 of file queue.cpp.
mem_advise() [1/4]
event cl::sycl::queue::mem_advise (const void * Ptr, size_t Length, int Advice)
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
Returns
an event representing advice operation.
Definition at line 112 of file queue.cpp.
mem_advise() [2/4]
event cl::sycl::queue::mem_advise (const void * Ptr, size_t Length, int Advice, const std::vector< event > & DepEvents)
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing advice operation.
Definition at line 121 of file queue.cpp.
mem_advise() [3/4]
event cl::sycl::queue::mem_advise (const void * Ptr, size_t Length, int Advice, event DepEvent)
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing advice operation.
Definition at line 116 of file queue.cpp.
mem_advise() [4/4]
event cl::sycl::queue::mem_advise (const void * Ptr, size_t Length, pi_mem_advice Advice)
Provides additional information to the underlying runtime about how different allocations are used.
Parameters
Ptr is a USM pointer to the allocation.
Length is a number of bytes in the allocation.
Advice is a device-defined advice for the specified allocation.
Returns
an event representing advice operation.
Definition at line 108 of file queue.cpp.
memcpy() [1/3]
event cl::sycl::queue::memcpy (void * Dest, const void * Src, size_t Count)
Copies data from one memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
Src is a USM pointer to the source memory.
Count is a number of bytes to copy.
Returns
an event representing copy operation.
Definition at line 95 of file queue.cpp.
memcpy() [2/3]
event cl::sycl::queue::memcpy (void * Dest, const void * Src, size_t Count, const std::vector< event > & DepEvents)
Copies data from one memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
Src is a USM pointer to the source memory.
Count is a number of bytes to copy.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing copy operation.
Definition at line 103 of file queue.cpp.
memcpy() [3/3]
event cl::sycl::queue::memcpy (void * Dest, const void * Src, size_t Count, event DepEvent)
Copies data from one memory region to another, both pointed by USM pointers.
No operations is done if
Parameters
Count is zero. An exception is thrown if either
Dest or
Src is nullptr. The behavior is undefined if any of the pointer parameters is invalid.
Dest is a USM pointer to the destination memory.
Src is a USM pointer to the source memory.
Count is a number of bytes to copy.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing copy operation.
Definition at line 99 of file queue.cpp.
memset() [1/3]
event cl::sycl::queue::memset (void * Ptr, int Value, size_t Count)
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Count is zero. An exception is thrown if
Ptr is nullptr. The behavior is undefined if
Ptr is invalid.
Ptr is a USM pointer to the memory to fill.
Value is a value to be set. Value is cast as an unsigned char.
Count is a number of bytes to fill.
Returns
an event representing fill operation.
Definition at line 82 of file queue.cpp.
memset() [2/3]
event cl::sycl::queue::memset (void * Ptr, int Value, size_t Count, const std::vector< event > & DepEvents)
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Count is zero. An exception is thrown if
Ptr is nullptr. The behavior is undefined if
Ptr is invalid.
Ptr is a USM pointer to the memory to fill.
Value is a value to be set. Value is cast as an unsigned char.
Count is a number of bytes to fill.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing fill operation.
Definition at line 90 of file queue.cpp.
memset() [3/3]
event cl::sycl::queue::memset (void * Ptr, int Value, size_t Count, event DepEvent)
Fills the memory pointed by a USM pointer with the value specified.
No operations is done if
Parameters
Count is zero. An exception is thrown if
Ptr is nullptr. The behavior is undefined if
Ptr is invalid.
Ptr is a USM pointer to the memory to fill.
Value is a value to be set. Value is cast as an unsigned char.
Count is a number of bytes to fill.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing fill operation.
Definition at line 86 of file queue.cpp.
operator!=()
bool cl::sycl::queue::operator!= (const queue & RHS) const inline
Definition at line 217 of file queue.hpp.
operator=() [1/2]
queue& cl::sycl::queue::operator= (const queue & RHS) default
operator=() [2/2]
queue& cl::sycl::queue::operator= (queue && RHS) default
operator==()
bool cl::sycl::queue::operator== (const queue & RHS) const inline
Definition at line 215 of file queue.hpp.
parallel_for() [1/16]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event cl::sycl::queue::parallel_for (nd_range< Dims > ExecutionRange, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
Parameters
ExecutionRange is a range that specifies the work space of the kernel
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 962 of file queue.hpp.
References _CODELOCARG.
parallel_for() [2/16]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event cl::sycl::queue::parallel_for (nd_range< Dims > ExecutionRange, const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
Parameters
ExecutionRange is a range that specifies the work space of the kernel
DepEvents is a vector of events that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 1006 of file queue.hpp.
References _CODELOCARG, and cl::sycl::handler::depends_on().
parallel_for() [3/16]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event cl::sycl::queue::parallel_for (nd_range< Dims > ExecutionRange, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
Parameters
ExecutionRange is a range that specifies the work space of the kernel
DepEvent is an event that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 983 of file queue.hpp.
References _CODELOCARG, and cl::sycl::handler::depends_on().
parallel_for() [4/16]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims, typename Reduction > event cl::sycl::queue::parallel_for (nd_range< Dims > ExecutionRange, Reduction Redu, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + nd_range that specifies global, local sizes and offset.
Parameters
ExecutionRange is a range that specifies the work space of the kernel
Redu is a reduction operation
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 1029 of file queue.hpp.
References _CODELOCARG.
parallel_for() [5/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 1 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 761 of file queue.hpp.
References _CODELOCARG.
parallel_for() [6/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 1 > NumWorkItems, const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
DepEvents is a vector of events that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 847 of file queue.hpp.
References _CODELOCARG.
parallel_for() [7/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 1 > NumWorkItems, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
DepEvent is an event that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 801 of file queue.hpp.
References _CODELOCARG.
parallel_for() [8/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 2 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 774 of file queue.hpp.
References _CODELOCARG.
parallel_for() [9/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 2 > NumWorkItems, const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
DepEvents is a vector of events that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 863 of file queue.hpp.
References _CODELOCARG.
parallel_for() [10/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 2 > NumWorkItems, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
DepEvent is an event that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 816 of file queue.hpp.
References _CODELOCARG.
parallel_for() [11/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 3 > NumWorkItems, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 787 of file queue.hpp.
References _CODELOCARG.
parallel_for() [12/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 3 > NumWorkItems, const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
DepEvents is a vector of events that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 879 of file queue.hpp.
References _CODELOCARG.
parallel_for() [13/16]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::parallel_for (range< 3 > NumWorkItems, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range that specifies global size only.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
DepEvent is an event that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 831 of file queue.hpp.
References _CODELOCARG.
parallel_for() [14/16]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event cl::sycl::queue::parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
WorkItemOffset specifies the offset for each work item id
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 895 of file queue.hpp.
References _CODELOCARG.
parallel_for() [15/16]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event cl::sycl::queue::parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
WorkItemOffset specifies the offset for each work item id
DepEvents is a vector of events that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 940 of file queue.hpp.
References _CODELOCARG, and cl::sycl::handler::depends_on().
parallel_for() [16/16]
template<typename KernelName = detail::auto_name, typename KernelType , int Dims> event cl::sycl::queue::parallel_for (range< Dims > NumWorkItems, id< Dims > WorkItemOffset, event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
parallel_for version with a kernel represented as a lambda + range and offset that specify global size and global offset correspondingly.
Parameters
NumWorkItems is a range that specifies the work space of the kernel
WorkItemOffset specifies the offset for each work item id
DepEvent is an event that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 916 of file queue.hpp.
References _CODELOCARG, and cl::sycl::handler::depends_on().
prefetch() [1/3]
event cl::sycl::queue::prefetch (const void * Ptr, size_t Count) inline
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
Parameters
Ptr is a USM pointer to the memory to be prefetched to the device.
Count is a number of bytes to be prefetched.
Returns
an event representing prefetch operation.
Definition at line 648 of file queue.hpp.
References cl::sycl::handler::prefetch().
prefetch() [2/3]
event cl::sycl::queue::prefetch (const void * Ptr, size_t Count, const std::vector< event > & DepEvents) inline
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
Parameters
Ptr is a USM pointer to the memory to be prefetched to the device.
Count is a number of bytes to be prefetched.
DepEvents is a vector of events that specifies the kernel dependencies.
Returns
an event representing prefetch operation.
Definition at line 676 of file queue.hpp.
References cl::sycl::handler::depends_on(), and cl::sycl::handler::prefetch().
prefetch() [3/3]
event cl::sycl::queue::prefetch (const void * Ptr, size_t Count, event DepEvent) inline
Provides hints to the runtime library that data should be made available on a device earlier than Unified Shared Memory would normally require it to be available.
Parameters
Ptr is a USM pointer to the memory to be prefetched to the device.
Count is a number of bytes to be prefetched.
DepEvent is an event that specifies the kernel dependencies.
Returns
an event representing prefetch operation.
Definition at line 660 of file queue.hpp.
References cl::sycl::handler::depends_on(), and cl::sycl::handler::prefetch().
single_task() [1/3]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::single_task (_KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
single_task version with a kernel represented as a lambda.
Parameters
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 689 of file queue.hpp.
References _CODELOCARG.
single_task() [2/3]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::single_task (const std::vector< event > & DepEvents, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
single_task version with a kernel represented as a lambda.
Parameters
DepEvents is a vector of events that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 736 of file queue.hpp.
References _CODELOCARG, and cl::sycl::handler::depends_on().
single_task() [3/3]
template<typename KernelName = detail::auto_name, typename KernelType > event cl::sycl::queue::single_task (event DepEvent, _KERNELFUNCPARAM(KernelFunc) _CODELOCPARAM & CodeLoc) inline
single_task version with a kernel represented as a lambda.
Parameters
DepEvent is an event that specifies the kernel dependencies
KernelFunc is the Kernel functor or lambda
CodeLoc contains the code location of user code
Definition at line 711 of file queue.hpp.
References _CODELOCARG, and cl::sycl::handler::depends_on().
submit() [1/2]
template<typename T > event cl::sycl::queue::submit (T CGF _CODELOCPARAM & CodeLoc) inline
Submits a command group function object to the queue, in order to be scheduled for execution on the device.
Parameters
CGF is a function object containing command group.
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object for the submitted command group.
Definition at line 252 of file queue.hpp.
References _CODELOCARG.
submit() [2/2]
template<typename T > event cl::sycl::queue::submit (T CGF, queue &SecondaryQueue _CODELOCPARAM & CodeLoc) inline
Submits a command group function object to the queue, in order to be scheduled for execution on the device.
On a kernel error, this command group function object is then scheduled for execution on a secondary queue.
Parameters
CGF is a function object containing command group.
SecondaryQueue is a fallback SYCL queue.
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object, which corresponds to the queue the command group is being enqueued on.
Definition at line 292 of file queue.hpp.
References _CODELOCARG, and is_host().
submit_barrier() [1/2]
event cl::sycl::queue::submit_barrier (_CODELOCONLYPARAM & CodeLoc) inline
Prevents any commands submitted afterward to this queue from executing until all commands previously submitted to this queue have entered the complete state.
Parameters
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object, which corresponds to the queue the command group is being enqueued on.
Definition at line 346 of file queue.hpp.
References _CODELOCARG.
submit_barrier() [2/2]
event cl::sycl::queue::submit_barrier (const std::vector< event > &WaitList _CODELOCPARAM & CodeLoc) inline
Prevents any commands submitted afterward to this queue from executing until all events in WaitList have entered the complete state.
If WaitList is empty, then submit_barrier has no effect.
Parameters
WaitList is a vector of valid SYCL events that need to complete before barrier command can be executed.
CodeLoc is the code location of the submit call (default argument)
Returns
a SYCL event object, which corresponds to the queue the command group is being enqueued on.
Definition at line 378 of file queue.hpp.
References _CODELOCARG.
throw_asynchronous()
void cl::sycl::queue::throw_asynchronous ()
Checks if any asynchronous errors have been produced by the queue and if so reports them to the async_handler passed on the queue construction.
If no async_handler was provided then asynchronous exceptions will be lost.
Definition at line 80 of file queue.cpp.
wait()
void cl::sycl::queue::wait (_CODELOCONLYPARAM & CodeLoc) inline
Performs a blocking wait for the completion of all enqueued tasks in the queue.
Synchronous errors will be reported through SYCL exceptions.
Parameters
CodeLoc is the code location of the submit call (default argument)
Definition at line 388 of file queue.hpp.
References _CODELOCARG.
wait_and_throw()
void cl::sycl::queue::wait_and_throw (_CODELOCONLYPARAM & CodeLoc) inline
Performs a blocking wait for the completion of all enqueued tasks in the queue.
Synchronous errors will be reported through SYCL exceptions. Asynchronous errors will be passed to the async_handler passed to the queue on construction. If no async_handler was provided then asynchronous exceptions will be lost.
Parameters
CodeLoc is the code location of the submit call (default argument)
Definition at line 402 of file queue.hpp.
References _CODELOCARG.
wait_and_throw_proxy()
void cl::sycl::queue::wait_and_throw_proxy (const detail::code_location & CodeLoc)
Proxy method for wait_and_throw to forward the code location information to the implementation.
Definition at line 162 of file queue.cpp.
wait_proxy()
void cl::sycl::queue::wait_proxy (const detail::code_location & CodeLoc)
Proxy method for wait to forward the code location information to the implementation.
Definition at line 158 of file queue.cpp.
Friends And Related Function Documentation
detail::createSyclObjFromImpl
template<class T > T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
The documentation for this class was generated from the following files:
include/CL/sycl/queue.hpp
source/queue.cpp