DPC++ Runtime: syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem > Class Template Reference
syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem > Class Template Reference
#include <syclcompat/launch_policy.hpp>
Public Types
using KPropsT = KProps
using LPropsT = LProps
using RangeT = Range
Public Member Functions
template<typename... Ts>
launch_policy (Range range, Ts... ts)
template<typename... Ts>
launch_policy (dim3 global_range, Ts... ts)
template<typename... Ts>
launch_policy (dim3 global_range, dim3 local_range, Ts... ts)
KProps get_kernel_properties ()
LProps get_launch_properties ()
size_t get_local_mem_size ()
Range get_range ()
Static Public Attributes
static constexpr bool HasLocalMem = LocalMem
Detailed Description
template<typename Range, typename KProps, typename LProps, bool LocalMem>
class syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >
Definition at line 96 of file launch_policy.hpp.
Member Typedef Documentation
KPropsT
template<typename Range , typename KProps , typename LProps , bool LocalMem> using syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::KPropsT = KProps
Definition at line 105 of file launch_policy.hpp.
LPropsT
template<typename Range , typename KProps , typename LProps , bool LocalMem> using syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::LPropsT = LProps
Definition at line 106 of file launch_policy.hpp.
RangeT
template<typename Range , typename KProps , typename LProps , bool LocalMem> using syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::RangeT = Range
Definition at line 107 of file launch_policy.hpp.
Constructor & Destructor Documentation
launch_policy() [1/3]
template<typename Range , typename KProps , typename LProps , bool LocalMem> template<typename... Ts> syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::launch_policy (Range range, Ts... ts) inline
Definition at line 139 of file launch_policy.hpp.
launch_policy() [2/3]
template<typename Range , typename KProps , typename LProps , bool LocalMem> template<typename... Ts> syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::launch_policy (dim3 global_range, Ts... ts) inline
Definition at line 145 of file launch_policy.hpp.
launch_policy() [3/3]
template<typename Range , typename KProps , typename LProps , bool LocalMem> template<typename... Ts> syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::launch_policy (dim3 global_range, dim3 local_range, Ts... ts) inline
Definition at line 151 of file launch_policy.hpp.
Member Function Documentation
get_kernel_properties()
template<typename Range , typename KProps , typename LProps , bool LocalMem> KProps syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::get_kernel_properties () inline
Definition at line 157 of file launch_policy.hpp.
References syclcompat::experimental::kernel_properties< Properties >::props.
Referenced by syclcompat::experimental::detail::build_kernel_functor().
get_launch_properties()
template<typename Range , typename KProps , typename LProps , bool LocalMem> LProps syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::get_launch_properties () inline
Definition at line 158 of file launch_policy.hpp.
References syclcompat::experimental::launch_properties< Properties >::props.
Referenced by syclcompat::experimental::detail::launch().
get_local_mem_size()
template<typename Range , typename KProps , typename LProps , bool LocalMem> size_t syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::get_local_mem_size () inline
Definition at line 159 of file launch_policy.hpp.
References syclcompat::experimental::local_mem_size::size.
Referenced by syclcompat::experimental::detail::build_kernel_functor().
get_range()
template<typename Range , typename KProps , typename LProps , bool LocalMem> Range syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::get_range () inline
Definition at line 160 of file launch_policy.hpp.
Referenced by syclcompat::experimental::detail::launch().
Member Data Documentation
HasLocalMem
template<typename Range , typename KProps , typename LProps , bool LocalMem> constexpr bool syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::HasLocalMem = LocalMem static constexpr
Definition at line 108 of file launch_policy.hpp.
The documentation for this class was generated from the following file:
include/syclcompat/launch_policy.hpp