DPC++ Runtime: cl::sycl::ONEAPI::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder > Class Template Reference
cl::sycl::ONEAPI::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder > Class Template Reference
#include <CL/sycl/ONEAPI/atomic_accessor.hpp>
Public Types
using value_type = DataT
using reference = atomic_ref< DataT, DefaultOrder, DefaultScope, AccessorT::AS >
Public Types inherited from cl::sycl::accessor< DataT, Dimensions, access::mode::read_write, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list<> >
using value_type = DataT
using reference = DataT &
using const_reference = const DataT &
Public Member Functions
template<int Dims = Dimensions>
operator typename detail::enable_if_t< Dims==0, reference > () const
template<int Dims = Dimensions>
detail::enable_if_t<(Dims > 0), reference > operator[] (id< Dimensions > Index) const
template<int Dims = Dimensions>
detail::enable_if_t< Dims==1, reference > operator[] (size_t Index) const
Public Member Functions inherited from cl::sycl::accessor< DataT, Dimensions, access::mode::read_write, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list<> >
accessor (buffer< T, 1, AllocatorT > &BufferRef, const property_list &PropertyList={})
accessor (buffer< T, 1, AllocatorT > &BufferRef, const ONEAPI::accessor_property_list< PropTypes... > &PropertyList={})
accessor (buffer< T, 1, AllocatorT > &BufferRef, handler &CommandGroupHandler, const property_list &PropertyList={})
accessor (buffer< T, 1, AllocatorT > &BufferRef, handler &CommandGroupHandler, const ONEAPI::accessor_property_list< PropTypes... > &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, const property_list &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, const ONEAPI::accessor_property_list< PropTypes... > &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, const property_list &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, const ONEAPI::accessor_property_list< PropTypes... > &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, range< Dimensions > AccessRange, const property_list &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, range< Dimensions > AccessRange, const ONEAPI::accessor_property_list< PropTypes... > &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, range< Dimensions > AccessRange, const property_list &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, range< Dimensions > AccessRange, const ONEAPI::accessor_property_list< PropTypes... > &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const property_list &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const ONEAPI::accessor_property_list< PropTypes... > &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const property_list &PropertyList={})
accessor (buffer< T, Dims, AllocatorT > &BufferRef, handler &CommandGroupHandler, range< Dimensions > AccessRange, id< Dimensions > AccessOffset, const ONEAPI::accessor_property_list< PropTypes... > &PropertyList={})
accessor (const accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list< NewPropsT... >> &Other)
constexpr bool is_placeholder () const
size_t get_size () const
size_t get_count () const
range< Dimensions > get_range () const
id< Dimensions > get_offset () const
operator RefType () const
operator ConstRefType () const
RefType operator[] (id< Dimensions > Index) const
detail::enable_if_t<(Dims > 0) &&IsAccessReadOnly, ConstRefType > operator[] (id< Dimensions > Index) const
detail::enable_if_t<(Dims > 0) &&AccessMode==access::mode::atomic, atomic< DataT, AS > > operator[] (id< Dimensions > Index) const
detail::enable_if_t< Dims==1 &&AccessMode==access::mode::atomic, atomic< DataT, AS > > operator[] (size_t Index) const
AccessorCommonT::template AccessorSubscript< Dims - 1 > operator[] (size_t Index) const
operator typename detail::enable_if_t< Dims==0 &&AccessMode==access::mode::atomic, atomic< DataT, AS >> () const
DataT * get_pointer () const
global_ptr< DataT > get_pointer () const
constant_ptr< DataT > get_pointer () const
bool operator== (const accessor &Rhs) const
bool operator!= (const accessor &Rhs) const
Public Member Functions inherited from cl::sycl::detail::AccessorBaseHost
AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, detail::SYCLMemObjI *SYCLMemObject, int Dims, int ElemSize, int OffsetInBytes=0, bool IsSubBuffer=false)
Additional Inherited Members
Protected Types inherited from cl::sycl::accessor< DataT, Dimensions, access::mode::read_write, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list<> >
using AccessorCommonT = detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list<> >
using AccessorSubscript = typename AccessorCommonT::template AccessorSubscript< Dims >
using ConcreteASPtrType = typename detail::DecoratedType< DataT, AS >::type *
using RefType = detail::const_if_const_AS< AS, DataT > &
using ConstRefType = const DataT &
using PtrType = detail::const_if_const_AS< AS, DataT > *
Protected Types inherited from cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >
using RefType = detail::const_if_const_AS< AS, DataT > &
using ConstRefType = const DataT &
using PtrType = detail::const_if_const_AS< AS, DataT > *
using AccType = accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >
Protected Member Functions inherited from cl::sycl::accessor< DataT, Dimensions, access::mode::read_write, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list<> >
size_t getLinearIndex (id< Dims > Id) const
PtrType getQualifiedPtr () const
Protected Member Functions inherited from cl::sycl::detail::AccessorBaseHost
id< 3 > & getOffset ()
range< 3 > & getAccessRange ()
range< 3 > & getMemoryRange ()
void * getPtr ()
unsigned int getElemSize () const
const id< 3 > & getOffset () const
const range< 3 > & getAccessRange () const
const range< 3 > & getMemoryRange () const
void * getPtr () const
template<class Obj >
decltype(Obj::impl) friend getSyclObjImpl (const Obj &SyclObject)
Static Protected Member Functions inherited from cl::sycl::accessor< DataT, Dimensions, access::mode::read_write, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list<> >
static constexpr bool IsSameAsBuffer ()
static access::mode getAdjustedMode (const ONEAPI::accessor_property_list<> &PropertyList)
Protected Attributes inherited from cl::sycl::accessor< DataT, Dimensions, access::mode::read_write, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list<> >
char padding [sizeof(detail::AccessorImplDevice< AdjustedDim >)+sizeof(PtrType) - sizeof(detail::AccessorBaseHost)]
Protected Attributes inherited from cl::sycl::detail::AccessorBaseHost
AccessorImplPtr impl
Static Protected Attributes inherited from cl::sycl::accessor< DataT, Dimensions, access::mode::read_write, AccessTarget, IsPlaceholder, ONEAPI::accessor_property_list<> >
static constexpr int AdjustedDim
Static Protected Attributes inherited from cl::sycl::detail::accessor_common< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >
static constexpr bool IsPlaceH = IsPlaceholder == access::placeholder::true_t
static constexpr access::address_space AS = TargetToAS<AccessTarget>::AS
static constexpr bool IsHostBuf = AccessTarget == access::target::host_buffer
static constexpr bool IsGlobalBuf
static constexpr bool IsConstantBuf
static constexpr bool IsAccessAnyWrite
static constexpr bool IsAccessReadOnly = AccessMode == access::mode::read
static constexpr bool IsAccessReadWrite
Detailed Description
template<typename DataT, int Dimensions, memory_order DefaultOrder, memory_scope DefaultScope, access::target AccessTarget = access::target::global_buffer, access::placeholder IsPlaceholder = access::placeholder::false_t>
class cl::sycl::ONEAPI::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder >
Definition at line 46 of file atomic_accessor.hpp.
Member Typedef Documentation
reference
template<typename DataT , int Dimensions, memory_order DefaultOrder, memory_scope DefaultScope, access::target AccessTarget = access::target::global_buffer, access::placeholder IsPlaceholder = access::placeholder::false_t> using cl::sycl::ONEAPI::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder >::reference = atomic_ref<DataT, DefaultOrder, DefaultScope, AccessorT::AS>
Definition at line 67 of file atomic_accessor.hpp.
value_type
template<typename DataT , int Dimensions, memory_order DefaultOrder, memory_scope DefaultScope, access::target AccessTarget = access::target::global_buffer, access::placeholder IsPlaceholder = access::placeholder::false_t> using cl::sycl::ONEAPI::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder >::value_type = DataT
Definition at line 65 of file atomic_accessor.hpp.
Member Function Documentation
operator typename detail::enable_if_t< Dims==0, reference >()
template<typename DataT , int Dimensions, memory_order DefaultOrder, memory_scope DefaultScope, access::target AccessTarget = access::target::global_buffer, access::placeholder IsPlaceholder = access::placeholder::false_t> template<int Dims = Dimensions> cl::sycl::ONEAPI::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder >::operator typename detail::enable_if_t< Dims==0, reference > () const inline
Definition at line 90 of file atomic_accessor.hpp.
References cl::sycl::detail::getLinearIndex().
operator[]() [1/2]
template<typename DataT , int Dimensions, memory_order DefaultOrder, memory_scope DefaultScope, access::target AccessTarget = access::target::global_buffer, access::placeholder IsPlaceholder = access::placeholder::false_t> template<int Dims = Dimensions> detail::enable_if_t<(Dims > 0), reference> cl::sycl::ONEAPI::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder >::operator[] (id< Dimensions > Index) const inline
Definition at line 97 of file atomic_accessor.hpp.
References cl::sycl::detail::getLinearIndex().
operator[]() [2/2]
template<typename DataT , int Dimensions, memory_order DefaultOrder, memory_scope DefaultScope, access::target AccessTarget = access::target::global_buffer, access::placeholder IsPlaceholder = access::placeholder::false_t> template<int Dims = Dimensions> detail::enable_if_t<Dims == 1, reference> cl::sycl::ONEAPI::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder >::operator[] (size_t Index) const inline
Definition at line 104 of file atomic_accessor.hpp.
References cl::sycl::detail::getLinearIndex().
The documentation for this class was generated from the following file:
include/CL/sycl/ONEAPI/atomic_accessor.hpp