DPC++ Runtime: cl::sycl::ext::oneapi::filter_selector Class Reference
cl::sycl::ext::oneapi::filter_selector Class Reference
#include <sycl/ext/oneapi/filter_selector.hpp>
Public Member Functions
filter_selector (const std::string &filter)
int operator() (const device &dev) const override
void reset () const
device select_device () const override
Public Member Functions inherited from cl::sycl::device_selector
virtual ~device_selector ()=default
Additional Inherited Members
Static Protected Attributes inherited from cl::sycl::device_selector
static constexpr int REJECT_DEVICE_SCORE = -1
Detailed Description
Definition at line 31 of file filter_selector.hpp.
Constructor & Destructor Documentation
filter_selector()
cl::sycl::ext::oneapi::filter_selector::filter_selector (const std::string & filter)
Definition at line 194 of file device_selector.cpp.
Member Function Documentation
operator()()
int cl::sycl::ext::oneapi::filter_selector::operator() (const device & dev) const override virtual
Implements cl::sycl::device_selector.
Definition at line 197 of file device_selector.cpp.
reset()
void cl::sycl::ext::oneapi::filter_selector::reset () const
Definition at line 201 of file device_selector.cpp.
Referenced by select_device().
select_device()
device cl::sycl::ext::oneapi::filter_selector::select_device () const override virtual
Reimplemented from cl::sycl::device_selector.
Definition at line 203 of file device_selector.cpp.
References cl::sycl::detail::GlobalHandler::instance(), reset(), and cl::sycl::device_selector::select_device().
The documentation for this class was generated from the following files:
include/sycl/ext/oneapi/filter_selector.hpp
source/device_selector.cpp