DPC++ Runtime: sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange Class Reference
sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange Class Reference
#include <detail/device_binary_image.hpp>
Classes
class ConstIterator
Public Types
using ValTy = std::remove_pointer< pi_device_binary_property >::type
Public Member Functions
ConstIterator begin () const
ConstIterator end () const
size_t size () const
bool isAvailable () const
Friends
class RTDeviceBinaryImage
Detailed Description
Definition at line 86 of file device_binary_image.hpp.
Member Typedef Documentation
ValTy
using sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::ValTy = std::remove_pointer<pi_device_binary_property>::type
Definition at line 88 of file device_binary_image.hpp.
Member Function Documentation
begin()
ConstIterator sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::begin () const inline
Definition at line 114 of file device_binary_image.hpp.
Referenced by sycl::_V1::detail::checkDevSupportDeviceRequirements(), sycl::_V1::detail::ProgramManager::createPIProgram(), sycl::_V1::detail::ProgramManager::getDeviceLibReqMask(), sycl::_V1::detail::ProgramManager::getOrCreatePIProgram(), sycl::_V1::detail::RTDeviceBinaryImage::getProperty(), and size().
end()
ConstIterator sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::end () const inline
Definition at line 115 of file device_binary_image.hpp.
Referenced by sycl::_V1::detail::checkDevSupportDeviceRequirements(), sycl::_V1::detail::RTDeviceBinaryImage::getProperty(), and size().
isAvailable()
bool sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::isAvailable () const inline
Definition at line 118 of file device_binary_image.hpp.
Referenced by sycl::_V1::detail::ProgramManager::addImages(), sycl::_V1::detail::ProgramManager::getDeviceLibReqMask(), and sycl::_V1::detail::RTDeviceBinaryImage::getProperty().
size()
size_t sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::size () const inline
Definition at line 116 of file device_binary_image.hpp.
References begin(), and end().
Friends And Related Function Documentation
RTDeviceBinaryImage
friend class RTDeviceBinaryImage friend
Definition at line 117 of file device_binary_image.hpp.
The documentation for this class was generated from the following files:
source/detail/device_binary_image.hpp
source/detail/device_binary_image.cpp