DPC++ Runtime: sycl::_V1::detail::fusion_wrapper_impl Class Reference
sycl::_V1::detail::fusion_wrapper_impl Class Reference
#include <detail/fusion/fusion_wrapper_impl.hpp>
Public Member Functions
fusion_wrapper_impl (std::shared_ptr< detail::queue_impl > Queue)
std::shared_ptr< detail::queue_impl > get_queue () const
bool is_in_fusion_mode () const
void start_fusion ()
void cancel_fusion ()
event complete_fusion (const property_list &propList={})
Detailed Description
Definition at line 16 of file fusion_wrapper_impl.hpp.
Constructor & Destructor Documentation
fusion_wrapper_impl()
sycl::_V1::detail::fusion_wrapper_impl::fusion_wrapper_impl (std::shared_ptr< detail::queue_impl > Queue) explicit
Definition at line 17 of file fusion_wrapper_impl.cpp.
Member Function Documentation
cancel_fusion()
void sycl::_V1::detail::fusion_wrapper_impl::cancel_fusion ()
Definition at line 38 of file fusion_wrapper_impl.cpp.
References sycl::_V1::detail::Scheduler::cancelFusion(), and sycl::_V1::detail::Scheduler::getInstance().
complete_fusion()
event sycl::_V1::detail::fusion_wrapper_impl::complete_fusion (const property_list & propList = {})
Definition at line 42 of file fusion_wrapper_impl.cpp.
References sycl::_V1::detail::Scheduler::completeFusion(), and sycl::_V1::detail::Scheduler::getInstance().
get_queue()
std::shared_ptr< detail::queue_impl > sycl::_V1::detail::fusion_wrapper_impl::get_queue () const
Definition at line 21 of file fusion_wrapper_impl.cpp.
is_in_fusion_mode()
bool sycl::_V1::detail::fusion_wrapper_impl::is_in_fusion_mode () const
Definition at line 25 of file fusion_wrapper_impl.cpp.
start_fusion()
void sycl::_V1::detail::fusion_wrapper_impl::start_fusion ()
Definition at line 29 of file fusion_wrapper_impl.cpp.
References sycl::_V1::detail::Scheduler::getInstance(), sycl::_V1::invalid, and sycl::_V1::detail::Scheduler::startFusion().
The documentation for this class was generated from the following files:
source/detail/fusion/fusion_wrapper_impl.hpp
source/detail/fusion/fusion_wrapper_impl.cpp