DPC++ Runtime: sycl::_V1::detail::AccessorBaseHost Class Reference
sycl::_V1::detail::AccessorBaseHost Class Reference
#include <sycl/accessor.hpp>
Public Member Functions
AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, void *SYCLMemObject, int Dims, int ElemSize, int OffsetInBytes=0, bool IsSubBuffer=false, const property_list &PropertyList={})
AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, void *SYCLMemObject, int Dims, int ElemSize, bool IsPlaceH, int OffsetInBytes=0, bool IsSubBuffer=false, const property_list &PropertyList={})
AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, void *SYCLMemObject, int Dims, int ElemSize, size_t OffsetInBytes=0, bool IsSubBuffer=false, const property_list &PropertyList={})
AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, void *SYCLMemObject, int Dims, int ElemSize, bool IsPlaceH, size_t OffsetInBytes=0, bool IsSubBuffer=false, const property_list &PropertyList={})
id< 3 > & getOffset ()
range< 3 > & getAccessRange ()
range< 3 > & getMemoryRange ()
void * getPtr () noexcept
unsigned int getElemSize () const
const id< 3 > & getOffset () const
const range< 3 > & getAccessRange () const
const range< 3 > & getMemoryRange () const
void * getPtr () const noexcept
bool isPlaceholder () const
bool isMemoryObjectUsedByGraph () const
detail::AccHostDataT & getAccData ()
const property_list & getPropList () const
void * getMemoryObject () const
template<class Obj >
decltype(Obj::impl) friend getSyclObjImpl (const Obj &SyclObject)
Public Attributes
AccessorImplPtr impl
Protected Member Functions
AccessorBaseHost (const AccessorImplPtr &Impl)
Friends
template<typename , int , access::mode , access::target , access::placeholder , typename >
class accessor
class sycl::ext::intel::esimd::detail::AccessorPrivateProxy
template<class T >
T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Detailed Description
Definition at line 518 of file accessor.hpp.
Constructor & Destructor Documentation
AccessorBaseHost() [1/5]
sycl::_V1::detail::AccessorBaseHost::AccessorBaseHost (const AccessorImplPtr & Impl) inline protected
Definition at line 520 of file accessor.hpp.
AccessorBaseHost() [2/5]
sycl::_V1::detail::AccessorBaseHost::AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, void * SYCLMemObject, int Dims, int ElemSize, int OffsetInBytes = 0, bool IsSubBuffer = false, const property_list & PropertyList = {})
Definition at line 27 of file accessor.cpp.
References sycl::_V1::AccessMode, and impl.
AccessorBaseHost() [3/5]
sycl::_V1::detail::AccessorBaseHost::AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, void * SYCLMemObject, int Dims, int ElemSize, bool IsPlaceH, int OffsetInBytes = 0, bool IsSubBuffer = false, const property_list & PropertyList = {})
Definition at line 40 of file accessor.cpp.
References sycl::_V1::AccessMode, and impl.
AccessorBaseHost() [4/5]
sycl::_V1::detail::AccessorBaseHost::AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, void * SYCLMemObject, int Dims, int ElemSize, size_t OffsetInBytes = 0, bool IsSubBuffer = false, const property_list & PropertyList = {})
Definition at line 52 of file accessor.cpp.
References sycl::_V1::AccessMode, and impl.
AccessorBaseHost() [5/5]
sycl::_V1::detail::AccessorBaseHost::AccessorBaseHost (id< 3 > Offset, range< 3 > AccessRange, range< 3 > MemoryRange, access::mode AccessMode, void * SYCLMemObject, int Dims, int ElemSize, bool IsPlaceH, size_t OffsetInBytes = 0, bool IsSubBuffer = false, const property_list & PropertyList = {})
Definition at line 64 of file accessor.cpp.
References sycl::_V1::AccessMode, and impl.
Member Function Documentation
getAccData()
detail::AccHostDataT & sycl::_V1::detail::AccessorBaseHost::getAccData ()
Definition at line 81 of file accessor.cpp.
References impl.
getAccessRange() [1/2]
range< 3 > & sycl::_V1::detail::AccessorBaseHost::getAccessRange ()
Definition at line 77 of file accessor.cpp.
References impl.
Referenced by sycl::_V1::handler::fill(), sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::get_range(), and sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::read().
getAccessRange() [2/2]
const range< 3 > & sycl::_V1::detail::AccessorBaseHost::getAccessRange () const
Definition at line 90 of file accessor.cpp.
References impl.
getElemSize()
unsigned int sycl::_V1::detail::AccessorBaseHost::getElemSize () const
Definition at line 87 of file accessor.cpp.
References impl.
Referenced by sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::read(), and sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::write().
getMemoryObject()
void * sycl::_V1::detail::AccessorBaseHost::getMemoryObject () const
Definition at line 100 of file accessor.cpp.
References impl.
getMemoryRange() [1/2]
range< 3 > & sycl::_V1::detail::AccessorBaseHost::getMemoryRange ()
Definition at line 78 of file accessor.cpp.
References impl.
Referenced by sycl::_V1::handler::fill().
getMemoryRange() [2/2]
const range< 3 > & sycl::_V1::detail::AccessorBaseHost::getMemoryRange () const
Definition at line 93 of file accessor.cpp.
References impl.
getOffset() [1/2]
id< 3 > & sycl::_V1::detail::AccessorBaseHost::getOffset ()
Definition at line 76 of file accessor.cpp.
References impl.
Referenced by sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::read(), and sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::write().
getOffset() [2/2]
const id< 3 > & sycl::_V1::detail::AccessorBaseHost::getOffset () const
Definition at line 89 of file accessor.cpp.
References impl.
getPropList()
const property_list & sycl::_V1::detail::AccessorBaseHost::getPropList () const
Definition at line 83 of file accessor.cpp.
References impl.
getPtr() [1/2]
void * sycl::_V1::detail::AccessorBaseHost::getPtr () const noexcept
Definition at line 96 of file accessor.cpp.
References impl.
getPtr() [2/2]
void * sycl::_V1::detail::AccessorBaseHost::getPtr () noexcept
Definition at line 79 of file accessor.cpp.
References impl.
Referenced by sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::read(), and sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::write().
getSyclObjImpl()
template<class Obj > decltype(Obj::impl) friend sycl::_V1::detail::AccessorBaseHost::getSyclObjImpl (const Obj & SyclObject)
isMemoryObjectUsedByGraph()
bool sycl::_V1::detail::AccessorBaseHost::isMemoryObjectUsedByGraph () const
Definition at line 104 of file accessor.cpp.
References impl.
isPlaceholder()
bool sycl::_V1::detail::AccessorBaseHost::isPlaceholder () const
Definition at line 102 of file accessor.cpp.
References impl.
Friends And Related Function Documentation
accessor
template<typename , int , access::mode , access::target , access::placeholder , typename > friend class accessor friend
Definition at line 576 of file accessor.hpp.
detail::createSyclObjFromImpl
template<class T > T detail::createSyclObjFromImpl (decltype(T::impl) ImplObj) friend
sycl::ext::intel::esimd::detail::AccessorPrivateProxy
friend class sycl::ext::intel::esimd::detail::AccessorPrivateProxy friend
Definition at line 581 of file accessor.hpp.
Member Data Documentation
impl
AccessorImplPtr sycl::_V1::detail::AccessorBaseHost::impl
Definition at line 578 of file accessor.hpp.
Referenced by AccessorBaseHost(), getAccData(), getAccessRange(), getElemSize(), getMemoryObject(), getMemoryRange(), getOffset(), getPropList(), getPtr(), isMemoryObjectUsedByGraph(), isPlaceholder(), and sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::operator==().
The documentation for this class was generated from the following files:
include/sycl/accessor.hpp
source/accessor.cpp