DPC++ Runtime: sycl::_V1::detail::SYCLMemObjI Class Reference
sycl::_V1::detail::SYCLMemObjI Class Reference abstract
#include <detail/sycl_mem_obj_i.hpp>
Public Types
enum MemObjType { Buffer = 0 , Image = 1 , Undefined = 2 }
Public Member Functions
virtual ~SYCLMemObjI ()=default
virtual MemObjType getType () const =0
virtual void * allocateMem (ContextImplPtr Context, bool InitFromUserData, void *HostPtr, sycl::detail::pi::PiEvent &InteropEvent)=0
virtual void * allocateHostMem ()=0
virtual void releaseMem (ContextImplPtr Context, void *Ptr)=0
virtual void releaseHostMem (void *Ptr)=0
virtual size_t getSizeInBytes () const noexcept=0
virtual bool isInterop () const =0
virtual bool hasUserDataPtr () const =0
virtual bool isHostPointerReadOnly () const =0
virtual bool usesPinnedHostMemory () const =0
virtual ContextImplPtr getInteropContext () const =0
Protected Attributes
std::shared_ptr< MemObjRecord > MRecord
Friends
class Scheduler
class ExecCGCommand
Detailed Description
Definition at line 27 of file sycl_mem_obj_i.hpp.
Member Enumeration Documentation
MemObjType
enum sycl::_V1::detail::SYCLMemObjI::MemObjType
Enumerator
Buffer
Image
Undefined
Definition at line 31 of file sycl_mem_obj_i.hpp.
Constructor & Destructor Documentation
~SYCLMemObjI()
virtual sycl::_V1::detail::SYCLMemObjI::~SYCLMemObjI () virtual default
Member Function Documentation
allocateHostMem()
virtual void* sycl::_V1::detail::SYCLMemObjI::allocateHostMem () pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT.
Referenced by sycl::_V1::detail::MemoryManager::allocateHostMemory().
allocateMem()
virtual void* sycl::_V1::detail::SYCLMemObjI::allocateMem (ContextImplPtr Context, bool InitFromUserData, void * HostPtr, sycl::detail::pi::PiEvent & InteropEvent) pure virtual
Implemented in sycl::_V1::detail::image_impl, sycl::_V1::detail::buffer_impl, and sycl::_V1::detail::SYCLMemObjT.
Referenced by sycl::_V1::detail::MemoryManager::allocate().
getInteropContext()
virtual ContextImplPtr sycl::_V1::detail::SYCLMemObjI::getInteropContext () const pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::getOrInsertMemObjRecord().
getSizeInBytes()
virtual size_t sycl::_V1::detail::SYCLMemObjI::getSizeInBytes () const pure virtual noexcept
Implemented in sycl::_V1::detail::SYCLMemObjT.
getType()
virtual MemObjType sycl::_V1::detail::SYCLMemObjI::getType () const pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT, sycl::_V1::detail::image_impl, and sycl::_V1::detail::buffer_impl.
Referenced by sycl::_V1::detail::copyD2D(), sycl::_V1::detail::copyD2H(), sycl::_V1::detail::copyH2D(), sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2D_cmd_buffer(), sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2H_cmd_buffer(), sycl::_V1::detail::MemoryManager::ext_oneapi_copyH2D_cmd_buffer(), sycl::_V1::detail::MemoryManager::ext_oneapi_fill_cmd_buffer(), sycl::_V1::detail::MemoryManager::fill(), and sycl::_V1::detail::UpdateHostRequirementCommand::printDot().
hasUserDataPtr()
virtual bool sycl::_V1::detail::SYCLMemObjI::hasUserDataPtr () const pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT.
isHostPointerReadOnly()
virtual bool sycl::_V1::detail::SYCLMemObjI::isHostPointerReadOnly () const pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT.
isInterop()
virtual bool sycl::_V1::detail::SYCLMemObjI::isInterop () const pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT.
releaseHostMem()
virtual void sycl::_V1::detail::SYCLMemObjI::releaseHostMem (void * Ptr) pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT.
Referenced by sycl::_V1::detail::MemoryManager::releaseMemObj().
releaseMem()
virtual void sycl::_V1::detail::SYCLMemObjI::releaseMem (ContextImplPtr Context, void * Ptr) pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT.
Referenced by sycl::_V1::detail::MemoryManager::release().
usesPinnedHostMemory()
virtual bool sycl::_V1::detail::SYCLMemObjI::usesPinnedHostMemory () const pure virtual
Implemented in sycl::_V1::detail::SYCLMemObjT.
Friends And Related Function Documentation
ExecCGCommand
friend class ExecCGCommand friend
Definition at line 84 of file sycl_mem_obj_i.hpp.
Scheduler
friend class Scheduler friend
Definition at line 83 of file sycl_mem_obj_i.hpp.
Member Data Documentation
MRecord
std::shared_ptr<MemObjRecord> sycl::_V1::detail::SYCLMemObjI::MRecord protected
Definition at line 82 of file sycl_mem_obj_i.hpp.
Referenced by sycl::_V1::detail::SYCLMemObjT::detachMemoryObject(), sycl::_V1::detail::Scheduler::enqueueLeavesOfReqUnlocked(), sycl::_V1::detail::Scheduler::getMemObjRecord(), sycl::_V1::detail::Scheduler::GraphBuilder::getMemObjRecord(), sycl::_V1::detail::buffer_impl::getNativeVector(), sycl::_V1::detail::Scheduler::GraphBuilder::getOrInsertMemObjRecord(), sycl::_V1::detail::SYCLMemObjT::handleWriteAccessorCreation(), sycl::_V1::detail::Scheduler::GraphBuilder::removeRecordForMemObj(), and sycl::_V1::detail::SYCLMemObjT::updateHostMemory().
The documentation for this class was generated from the following file:
source/detail/sycl_mem_obj_i.hpp