DPC++ Runtime: SystemMemory Class Reference
SystemMemory Class Reference abstract
#include <level_zero/usm_allocator.hpp>
Public Types
enum MemType {
Host, Device, Shared, SharedReadOnly,
All
}
Public Member Functions
virtual void * allocate (size_t size)=0
virtual void * allocate (size_t size, size_t aligned)=0
virtual void deallocate (void *ptr)=0
virtual MemType getMemType ()=0
virtual ~SystemMemory ()=default
Detailed Description
Definition at line 15 of file usm_allocator.hpp.
Member Enumeration Documentation
MemType
enum SystemMemory::MemType
Enumerator
Host
Device
Shared
SharedReadOnly
All
Definition at line 17 of file usm_allocator.hpp.
Constructor & Destructor Documentation
~SystemMemory()
virtual SystemMemory::~SystemMemory () virtual default
Member Function Documentation
allocate() [1/2]
virtual void* SystemMemory::allocate (size_t size) pure virtual
Implemented in USMMemoryAllocBase.
Referenced by USMAllocContext::USMAllocImpl::allocate().
allocate() [2/2]
virtual void* SystemMemory::allocate (size_t size, size_t aligned) pure virtual
Implemented in USMMemoryAllocBase.
deallocate()
virtual void SystemMemory::deallocate (void * ptr) pure virtual
Implemented in USMMemoryAllocBase.
Referenced by Slab::~Slab().
getMemType()
virtual MemType SystemMemory::getMemType () pure virtual
Implemented in USMMemoryAllocBase.
Referenced by Bucket::getMemType().
The documentation for this class was generated from the following file:
plugins/level_zero/usm_allocator.hpp