DPC++ Runtime: cl::sycl::ext::intel::experimental::esimd::simd< Ty, N > Class Template Reference
cl::sycl::ext::intel::experimental::esimd::simd< Ty, N > Class Template Reference
DPC++ Explicit SIMD API
The simd vector class.
#include <sycl/ext/intel/experimental/esimd/detail/types.hpp>
Public Types
using vector_type = detail::vector_type_t< Ty, N >
The underlying builtin data type.
using element_type = Ty
The element type of this simd object.
Public Member Functions
operator const vector_type & () const &
conversion operator
operator vector_type & () &
template<typename T = simd, typename = sycl::detail::enable_if_t<T::length == 1>>
operator element_type () const
Implicit conversion for simd<T, 1> into T.
vector_type data () const
simd read () const
Whole region read.
simd & write (const simd &Val)
Whole region write.
void merge (const simd &Val, const mask_type_t< N > &Mask)
Whole region update with predicates.
void merge (const simd &Val1, simd Val2, const mask_type_t< N > &Mask)
template<typename EltTy >
auto bit_cast_view () &
View this simd object in a different element type.
template<typename EltTy >
auto format () &
template<typename EltTy , int Height, int Width>
auto bit_cast_view () &
View as a 2-dimensional simd_view.
template<typename EltTy , int Height, int Width>
auto format () &
template<int Size, int Stride>
simd_view< simd, region1d_t< Ty, Size, Stride > > select (uint16_t Offset=0) &
1D region select, apply a region on top of this LValue object.
template<int Size, int Stride>
simd< Ty, Size > select (uint16_t Offset=0) &&
1D region select, apply a region on top of this RValue object.
Ty operator[] (int i) const
Read single element, return value only (not reference).
simd_view< simd, region1d_t< Ty, 1, 0 > > operator[] (int i)
Return writable view of a single element.
template<int Size>
simd< Ty, Size > iselect (const simd< uint16_t, Size > &Indices)
Read multiple elements by their indices in vector.
void iupdate (ushort Index, Ty V)
update single element
template<int Size>
void iupdate (const simd< uint16_t, Size > &Indices, const simd< Ty, Size > &Val, mask_type_t< Size > Mask)
update multiple elements by their indices in vector
simd & operator++ ()
simd operator++ (int)
simd & operator-- ()
simd operator-- (int)
template<typename T1 = element_type, typename T2 = Ty, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>>
uint16_t any ()
Any operation.
template<typename T1 = element_type, typename T2 = Ty, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>>
uint16_t all ()
All operation.
template<typename RTy >
ESIMD_INLINE void writeRegion (RTy Region, const detail::vector_type_t< typename RTy::element_type, RTy::length > &Val)
Write a simd-vector into a basic region of a simd object.
template<typename TR , typename UR >
ESIMD_INLINE void writeRegion (std::pair< TR, UR > Region, const detail::vector_type_t< typename TR::element_type, TR::length > &Val)
Write a simd-vector into a nested region of a simd object.
simd ()=default
simd (const simd &other)
template<typename SrcTy >
simd (const simd< SrcTy, N > &other)
template<typename SrcTy >
simd (simd< SrcTy, N > &&other)
simd (const vector_type &Val)
simd (std::initializer_list< Ty > Ilist) noexcept
simd (Ty Val, Ty Step=Ty()) noexcept
Initialize a simd with an initial value and step.
Replicate
Replicate simd instance given a region.
template<int Rep>
simd< Ty, Rep *N > replicate ()
template<int Rep, int W>
simd< Ty, Rep *W > replicate (uint16_t Offset)
template<int Rep, int W>
simd< Ty, Rep *W > replicate_w (uint16_t Offset)
template<int Rep, int VS, int W>
simd< Ty, Rep *W > replicate (uint16_t Offset)
template<int Rep, int VS, int W>
simd< Ty, Rep *W > replicate_vs_w (uint16_t Offset)
template<int Rep, int VS, int W, int HS>
simd< Ty, Rep *W > replicate (uint16_t Offset)
template<int Rep, int VS, int W, int HS>
simd< Ty, Rep *W > replicate_vs_w_hs (uint16_t Offset)
Memory operations
TODO NOTE: These APIs do not support cache hint specification yet, as this is WIP.
Later addition of hints is not expected to break code using these APIs.
ESIMD_INLINE void copy_from (const Ty *const addr) SYCL_ESIMD_FUNCTION
Copy a contiguous block of data from memory into this simd object.
template<typename AccessorT >
ESIMD_INLINE detail::EnableIfAccessor< AccessorT, detail::accessor_mode_cap::can_read, sycl::access::target::global_buffer, void > copy_from (AccessorT acc, uint32_t offset) SYCL_ESIMD_FUNCTION
Copy a contiguous block of data from memory into this simd object.
ESIMD_INLINE void copy_to (Ty *addr) SYCL_ESIMD_FUNCTION
Copy all vector elements of this object into a contiguous block in memory.
template<typename AccessorT >
ESIMD_INLINE detail::EnableIfAccessor< AccessorT, detail::accessor_mode_cap::can_write, sycl::access::target::global_buffer, void > copy_to (AccessorT acc, uint32_t offset) SYCL_ESIMD_FUNCTION
Copy all vector elements of this object into a contiguous block in memory.
Static Public Attributes
static constexpr int length = N
The number of elements in this simd object.
Friends
template<typename , typename >
class simd_view
Detailed Description
template<typename Ty, int N>
class cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >
The simd vector class.
This is a wrapper class for llvm vector values. Additionally this class supports region operations that map to Intel GPU regions. The type of a region select or format operation is of simd_view type, which models read-update-write semantics.
Definition at line 29 of file types.hpp.
Member Typedef Documentation
element_type
template<typename Ty , int N> using cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::element_type = Ty
The element type of this simd object.
Definition at line 43 of file simd.hpp.
vector_type
template<typename Ty , int N> using cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::vector_type = detail::vector_type_t<Ty, N>
The underlying builtin data type.
Definition at line 40 of file simd.hpp.
Constructor & Destructor Documentation
simd() [1/7]
template<typename Ty , int N> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::simd () default
Constructors.
simd() [2/7]
template<typename Ty , int N> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::simd (const simd< Ty, N > & other) inline
Definition at line 51 of file simd.hpp.
simd() [3/7]
template<typename Ty , int N> template<typename SrcTy > cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::simd (const simd< SrcTy, N > & other) inline
Definition at line 52 of file simd.hpp.
simd() [4/7]
template<typename Ty , int N> template<typename SrcTy > cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::simd (simd< SrcTy, N > && other) inline
Definition at line 55 of file simd.hpp.
simd() [5/7]
template<typename Ty , int N> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::simd (const vector_type & Val) inline
Definition at line 61 of file simd.hpp.
simd() [6/7]
template<typename Ty , int N> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::simd (std::initializer_list< Ty > Ilist) inline noexcept
Definition at line 82 of file simd.hpp.
simd() [7/7]
template<typename Ty , int N> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::simd (Ty Val, Ty Step = Ty()) inline noexcept
Initialize a simd with an initial value and step.
Definition at line 90 of file simd.hpp.
Member Function Documentation
all()
template<typename Ty , int N> template<typename T1 = element_type, typename T2 = Ty, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>> uint16_t cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::all () inline
All operation.
Returns
1 if all elements are set, 0 otherwise.
Definition at line 442 of file simd.hpp.
any()
template<typename Ty , int N> template<typename T1 = element_type, typename T2 = Ty, typename = sycl::detail::enable_if_t<std::is_integral<T1>::value, T2>> uint16_t cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::any () inline
Any operation.
Returns
1 if any element is set, 0 otherwise.
Definition at line 432 of file simd.hpp.
bit_cast_view() [1/2]
template<typename Ty , int N> template<typename EltTy > auto cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::bit_cast_view () & inline
View this simd object in a different element type.
Definition at line 142 of file simd.hpp.
References cl::sycl::ext::intel::experimental::esimd::R.
bit_cast_view() [2/2]
template<typename Ty , int N> template<typename EltTy , int Height, int Width> auto cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::bit_cast_view () & inline
View as a 2-dimensional simd_view.
Definition at line 156 of file simd.hpp.
References cl::sycl::ext::intel::experimental::esimd::R.
copy_from() [1/2]
template<typename T , int N> template<typename AccessorT > ESIMD_INLINE detail::EnableIfAccessor< AccessorT, detail::accessor_mode_cap::can_read, sycl::access::target::global_buffer, void > cl::sycl::ext::intel::experimental::esimd::simd< T, N >::copy_from (AccessorT acc, uint32_t offset)
Copy a contiguous block of data from memory into this simd object.
The amount of memory copied equals the total size of vector elements in this object. Source memory location is represented via a global accessor and offset.
Parameters
acc accessor to copy from.
offset offset to copy from.
Definition at line 613 of file simd.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2().
copy_from() [2/2]
template<typename Ty , int N> ESIMD_INLINE void cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::copy_from (const Ty *const addr)
Copy a contiguous block of data from memory into this simd object.
The amount of memory copied equals the total size of vector elements in this object.
Parameters
addr the memory address to copy from. Must be a pointer to the global address space, otherwise behavior is undefined.
Referenced by cl::sycl::ext::intel::experimental::esimd::block_load().
copy_to() [1/2]
template<typename T , int N> template<typename AccessorT > ESIMD_INLINE detail::EnableIfAccessor< AccessorT, detail::accessor_mode_cap::can_write, sycl::access::target::global_buffer, void > cl::sycl::ext::intel::experimental::esimd::simd< T, N >::copy_to (AccessorT acc, uint32_t offset)
Copy all vector elements of this object into a contiguous block in memory.
Destination memory location is represented via a global accessor and offset.
Parameters
acc accessor to copy from.
offset offset to copy from.
Definition at line 652 of file simd.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2().
copy_to() [2/2]
template<typename Ty , int N> ESIMD_INLINE void cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::copy_to (Ty * addr)
Copy all vector elements of this object into a contiguous block in memory.
Parameters
addr the memory address to copy to. Must be a pointer to the global address space, otherwise behavior is undefined.
data()
template<typename Ty , int N> vector_type cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data () const inline
Definition at line 114 of file simd.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::detail::__esimd_abs_common_internal(), cl::sycl::ext::intel::experimental::esimd::esimd_imul(), cl::sycl::ext::intel::experimental::esimd::esimd_lsr(), cl::sycl::ext::intel::experimental::esimd::esimd_max(), cl::sycl::ext::intel::experimental::esimd::esimd_min(), cl::sycl::ext::intel::experimental::esimd::esimd_pack_mask(), cl::sycl::ext::intel::experimental::esimd::esimd_raw_send_load(), cl::sycl::ext::intel::experimental::esimd::esimd_raw_send_store(), cl::sycl::ext::intel::experimental::esimd::esimd_raw_sends_load(), cl::sycl::ext::intel::experimental::esimd::esimd_raw_sends_store(), cl::sycl::ext::intel::experimental::esimd::esimd_rol(), cl::sycl::ext::intel::experimental::esimd::esimd_ror(), cl::sycl::ext::intel::experimental::esimd::esimd_sat(), cl::sycl::ext::intel::experimental::esimd::esimd_shl(), cl::sycl::ext::intel::experimental::esimd::esimd_shr(), cl::sycl::ext::intel::experimental::esimd::flat_atomic(), cl::sycl::ext::intel::experimental::esimd::gather(), cl::sycl::ext::intel::experimental::esimd::gather4(), cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::operator=(), cl::sycl::ext::intel::experimental::esimd::scatter(), cl::sycl::ext::intel::experimental::esimd::scatter4(), cl::sycl::ext::intel::experimental::esimd::slm_atomic(), cl::sycl::ext::intel::experimental::esimd::slm_block_store(), cl::sycl::ext::intel::experimental::esimd::slm_load(), cl::sycl::ext::intel::experimental::esimd::slm_load4(), cl::sycl::ext::intel::experimental::esimd::slm_store(), cl::sycl::ext::intel::experimental::esimd::slm_store4(), and cl::sycl::ext::intel::experimental::esimd::detail::simd_view_impl< BaseTy, region_base_1< Is2D, T, StrideY, StrideX > >::write().
format() [1/2]
template<typename Ty , int N> template<typename EltTy > auto cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::format () & inline
Definition at line 151 of file simd.hpp.
format() [2/2]
template<typename Ty , int N> template<typename EltTy , int Height, int Width> auto cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::format () & inline
Definition at line 166 of file simd.hpp.
iselect()
template<typename Ty , int N> template<int Size> simd<Ty, Size> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::iselect (const simd< uint16_t, Size > & Indices) inline
Read multiple elements by their indices in vector.
Definition at line 206 of file simd.hpp.
iupdate() [1/2]
template<typename Ty , int N> template<int Size> void cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::iupdate (const simd< uint16_t, Size > & Indices, const simd< Ty, Size > & Val, mask_type_t< Size > Mask) inline
update multiple elements by their indices in vector
Definition at line 220 of file simd.hpp.
iupdate() [2/2]
template<typename Ty , int N> void cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::iupdate (ushort Index, Ty V) inline
update single element
Definition at line 212 of file simd.hpp.
merge() [1/2]
template<typename Ty , int N> void cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge (const simd< Ty, N > & Val, const mask_type_t< N > & Mask) inline
Whole region update with predicates.
Definition at line 132 of file simd.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_acos(), cl::sycl::ext::intel::experimental::esimd::esimd_asin(), cl::sycl::ext::intel::experimental::esimd::esimd_atan(), and cl::sycl::ext::intel::experimental::esimd::detail::simd_view_impl< BaseTy, region_base_1< Is2D, T, StrideY, StrideX > >::merge().
merge() [2/2]
template<typename Ty , int N> void cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge (const simd< Ty, N > & Val1, simd< Ty, N > Val2, const mask_type_t< N > & Mask) inline
Definition at line 136 of file simd.hpp.
operator const vector_type &()
template<typename Ty , int N> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator const vector_type & () const & inline
conversion operator
Definition at line 104 of file simd.hpp.
operator element_type()
template<typename Ty , int N> template<typename T = simd, typename = sycl::detail::enable_if_t<T::length == 1>> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator element_type () const inline
Implicit conversion for simd<T, 1> into T.
Definition at line 110 of file simd.hpp.
operator vector_type &()
template<typename Ty , int N> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator vector_type & () & inline
Definition at line 105 of file simd.hpp.
operator++() [1/2]
template<typename Ty , int N> simd& cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator++ () inline
Definition at line 320 of file simd.hpp.
operator++() [2/2]
template<typename Ty , int N> simd cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator++ (int) inline
Definition at line 324 of file simd.hpp.
operator--() [1/2]
template<typename Ty , int N> simd& cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator-- () inline
Definition at line 329 of file simd.hpp.
operator--() [2/2]
template<typename Ty , int N> simd cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator-- (int) inline
Definition at line 333 of file simd.hpp.
operator[]() [1/2]
template<typename Ty , int N> simd_view<simd, region1d_t<Ty, 1, 0> > cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator[] (int i) inline
Return writable view of a single element.
Definition at line 199 of file simd.hpp.
operator[]() [2/2]
template<typename Ty , int N> Ty cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::operator[] (int i) const inline
Read single element, return value only (not reference).
Definition at line 196 of file simd.hpp.
read()
template<typename Ty , int N> simd cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::read () const inline
Whole region read.
Definition at line 123 of file simd.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_pln(), and cl::sycl::ext::intel::experimental::esimd::detail::simd_view_impl< BaseTy, region_base_1< Is2D, T, StrideY, StrideX > >::merge().
replicate() [1/4]
template<typename Ty , int N> template<int Rep> simd<Ty, Rep * N> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::replicate () inline
Template Parameters
Rep is number of times region has to be replicated.
Returns
replicated simd instance.
Definition at line 358 of file simd.hpp.
replicate() [2/4]
template<typename Ty , int N> template<int Rep, int W> simd<Ty, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::replicate (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
W is width of src region to replicate.
Parameters
Offset is offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 368 of file simd.hpp.
replicate() [3/4]
template<typename Ty , int N> template<int Rep, int VS, int W> simd<Ty, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::replicate (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
VS vertical stride of src region to replicate.
W is width of src region to replicate.
Parameters
Offset is offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 387 of file simd.hpp.
replicate() [4/4]
template<typename Ty , int N> template<int Rep, int VS, int W, int HS> simd<Ty, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::replicate (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
VS vertical stride of src region to replicate.
W is width of src region to replicate.
HS horizontal stride of src region to replicate.
Parameters
Offset is offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 409 of file simd.hpp.
replicate_vs_w()
template<typename Ty , int N> template<int Rep, int VS, int W> simd<Ty, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::replicate_vs_w (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
VS vertical stride of src region to replicate.
W width of src region to replicate.
Parameters
Offset offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 397 of file simd.hpp.
replicate_vs_w_hs()
template<typename Ty , int N> template<int Rep, int VS, int W, int HS> simd<Ty, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::replicate_vs_w_hs (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
VS vertical stride of src region to replicate.
W is width of src region to replicate.
HS horizontal stride of src region to replicate.
Parameters
Offset is offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 420 of file simd.hpp.
replicate_w()
template<typename Ty , int N> template<int Rep, int W> simd<Ty, Rep * W> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::replicate_w (uint16_t Offset) inline
Template Parameters
Rep is number of times region has to be replicated.
W is width of src region to replicate.
Parameters
Offset is offset in number of elements in src region.
Returns
replicated simd instance.
Definition at line 376 of file simd.hpp.
select() [1/2]
template<typename Ty , int N> template<int Size, int Stride> simd_view<simd, region1d_t<Ty, Size, Stride> > cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select (uint16_t Offset = 0) & inline
1D region select, apply a region on top of this LValue object.
Template Parameters
Size is the number of elements to be selected.
Stride is the element distance between two consecutive elements.
Parameters
Offset is the starting element offset.
Returns
the representing region object.
Definition at line 177 of file simd.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_dp2(), cl::sycl::ext::intel::experimental::esimd::esimd_dp3(), cl::sycl::ext::intel::experimental::esimd::esimd_dp4(), cl::sycl::ext::intel::experimental::esimd::esimd_dph(), cl::sycl::ext::intel::experimental::esimd::esimd_line(), and cl::sycl::ext::intel::experimental::esimd::esimd_pln().
select() [2/2]
template<typename Ty , int N> template<int Size, int Stride> simd<Ty, Size> cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select (uint16_t Offset = 0) && inline
1D region select, apply a region on top of this RValue object.
Template Parameters
Size is the number of elements to be selected.
Stride is the element distance between two consecutive elements.
Parameters
Offset is the starting element offset.
Returns
the value this region object refers to.
Definition at line 189 of file simd.hpp.
References __esimd_rdregion().
write()
template<typename Ty , int N> simd& cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::write (const simd< Ty, N > & Val) inline
Whole region write.
Definition at line 126 of file simd.hpp.
writeRegion() [1/2]
template<typename Ty , int N> template<typename RTy > ESIMD_INLINE void cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::writeRegion (RTy Region, const detail::vector_type_t< typename RTy::element_type, RTy::length > & Val) inline
Write a simd-vector into a basic region of a simd object.
Definition at line 449 of file simd.hpp.
References __esimd_wrregion(), and cl::sycl::length().
writeRegion() [2/2]
template<typename Ty , int N> template<typename TR , typename UR > ESIMD_INLINE void cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::writeRegion (std::pair< TR, UR > Region, const detail::vector_type_t< typename TR::element_type, TR::length > & Val) inline
Write a simd-vector into a nested region of a simd object.
Definition at line 476 of file simd.hpp.
References __esimd_wrregion(), and cl::sycl::length().
Friends And Related Function Documentation
simd_view
template<typename Ty , int N> template<typename , typename > friend class simd_view friend
Definition at line 36 of file simd.hpp.
Member Data Documentation
length
template<typename Ty , int N> constexpr int cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::length = N static constexpr
The number of elements in this simd object.
Definition at line 46 of file simd.hpp.
The documentation for this class was generated from the following files:
include/sycl/ext/intel/experimental/esimd/detail/types.hpp
include/sycl/ext/intel/experimental/esimd/simd.hpp