var dir_dd7d3bcc93139b1cbc3b663242fe4a67 =
[
    [ "access", "dir_890ae56b49654c9f921023f5ab965d24.html", "dir_890ae56b49654c9f921023f5ab965d24" ],
    [ "backend", "dir_c863f1cf1daa9fa160af971bc0a6225b.html", "dir_c863f1cf1daa9fa160af971bc0a6225b" ],
    [ "detail", "dir_399fbdfcd25b70941a9dab34251f0ee8.html", "dir_399fbdfcd25b70941a9dab34251f0ee8" ],
    [ "info", "dir_12b9ed12eb09663275c0ccaddd9adede.html", "dir_12b9ed12eb09663275c0ccaddd9adede" ],
    [ "properties", "dir_44c465508f81c3871cd3b8ecbdc75500.html", "dir_44c465508f81c3871cd3b8ecbdc75500" ],
    [ "usm", "dir_37f6d7b558fa13a28d407413718293f0.html", "dir_37f6d7b558fa13a28d407413718293f0" ],
    [ "accessor.hpp", "accessor_8hpp.html", "accessor_8hpp" ],
    [ "aliases.hpp", "aliases_8hpp.html", "aliases_8hpp" ],
    [ "aspects.hpp", "aspects_8hpp.html", "aspects_8hpp" ],
    [ "atomic.hpp", "CL_2sycl_2atomic_8hpp.html", "CL_2sycl_2atomic_8hpp" ],
    [ "atomic_fence.hpp", "CL_2sycl_2atomic__fence_8hpp.html", "CL_2sycl_2atomic__fence_8hpp" ],
    [ "atomic_ref.hpp", "CL_2sycl_2atomic__ref_8hpp.html", "CL_2sycl_2atomic__ref_8hpp" ],
    [ "backend.hpp", "backend_8hpp.html", "backend_8hpp" ],
    [ "backend_types.hpp", "backend__types_8hpp.html", "backend__types_8hpp" ],
    [ "bit_cast.hpp", "bit__cast_8hpp.html", "bit__cast_8hpp" ],
    [ "buffer.hpp", "buffer_8hpp.html", "buffer_8hpp" ],
    [ "builtins.hpp", "CL_2sycl_2builtins_8hpp.html", "CL_2sycl_2builtins_8hpp" ],
    [ "builtins_esimd.hpp", "builtins__esimd_8hpp.html", "builtins__esimd_8hpp" ],
    [ "context.hpp", "context_8hpp.html", [
      [ "hash< cl::sycl::context >", "structstd_1_1hash_3_01cl_1_1sycl_1_1context_01_4.html", "structstd_1_1hash_3_01cl_1_1sycl_1_1context_01_4" ]
    ] ],
    [ "define_vendors.hpp", "define__vendors_8hpp.html", "define__vendors_8hpp" ],
    [ "device.hpp", "device_8hpp.html", "device_8hpp" ],
    [ "device_event.hpp", "device__event_8hpp.html", null ],
    [ "device_selector.hpp", "device__selector_8hpp.html", null ],
    [ "event.hpp", "event_8hpp.html", [
      [ "hash< cl::sycl::event >", "structstd_1_1hash_3_01cl_1_1sycl_1_1event_01_4.html", "structstd_1_1hash_3_01cl_1_1sycl_1_1event_01_4" ]
    ] ],
    [ "exception.hpp", "exception_8hpp.html", "exception_8hpp" ],
    [ "exception_list.hpp", "exception__list_8hpp.html", "exception__list_8hpp" ],
    [ "feature_test.hpp", "feature__test_8hpp.html", "feature__test_8hpp" ],
    [ "functional.hpp", "CL_2sycl_2functional_8hpp.html", "CL_2sycl_2functional_8hpp" ],
    [ "group.hpp", "group_8hpp.html", "group_8hpp" ],
    [ "group_algorithm.hpp", "CL_2sycl_2group__algorithm_8hpp.html", "CL_2sycl_2group__algorithm_8hpp" ],
    [ "group_local_memory.hpp", "CL_2sycl_2group__local__memory_8hpp.html", "CL_2sycl_2group__local__memory_8hpp" ],
    [ "h_item.hpp", "h__item_8hpp.html", null ],
    [ "half_type.hpp", "half__type_8hpp.html", "half__type_8hpp" ],
    [ "handler.hpp", "handler_8hpp.html", "handler_8hpp" ],
    [ "id.hpp", "id_8hpp.html", "id_8hpp" ],
    [ "image.hpp", "image_8hpp.html", "image_8hpp" ],
    [ "interop_handle.hpp", "interop__handle_8hpp.html", [
      [ "interop_handle", "classcl_1_1sycl_1_1interop__handle.html", "classcl_1_1sycl_1_1interop__handle" ]
    ] ],
    [ "interop_handler.hpp", "interop__handler_8hpp.html", "interop__handler_8hpp" ],
    [ "item.hpp", "item_8hpp.html", "item_8hpp" ],
    [ "kernel.hpp", "kernel_8hpp.html", [
      [ "backend_traits", "classcl_1_1sycl_1_1backend__traits.html", "classcl_1_1sycl_1_1backend__traits" ],
      [ "auto_name", "classcl_1_1sycl_1_1detail_1_1auto__name.html", null ],
      [ "get_kernel_name_t", "structcl_1_1sycl_1_1detail_1_1get__kernel__name__t.html", "structcl_1_1sycl_1_1detail_1_1get__kernel__name__t" ],
      [ "hash< cl::sycl::kernel >", "structstd_1_1hash_3_01cl_1_1sycl_1_1kernel_01_4.html", "structstd_1_1hash_3_01cl_1_1sycl_1_1kernel_01_4" ]
    ] ],
    [ "kernel_bundle.hpp", "kernel__bundle_8hpp.html", "kernel__bundle_8hpp" ],
    [ "kernel_bundle_enums.hpp", "kernel__bundle__enums_8hpp.html", "kernel__bundle__enums_8hpp" ],
    [ "kernel_handler.hpp", "kernel__handler_8hpp.html", null ],
    [ "known_identity.hpp", "known__identity_8hpp.html", "known__identity_8hpp" ],
    [ "marray.hpp", "marray_8hpp.html", "marray_8hpp" ],
    [ "memory_enums.hpp", "memory__enums_8hpp.html", "memory__enums_8hpp" ],
    [ "multi_ptr.hpp", "multi__ptr_8hpp.html", "multi__ptr_8hpp" ],
    [ "nd_item.hpp", "nd__item_8hpp.html", "nd__item_8hpp" ],
    [ "nd_range.hpp", "nd__range_8hpp.html", null ],
    [ "pipes.hpp", "CL_2sycl_2pipes_8hpp.html", "CL_2sycl_2pipes_8hpp" ],
    [ "platform.hpp", "platform_8hpp.html", [
      [ "hash< cl::sycl::platform >", "structstd_1_1hash_3_01cl_1_1sycl_1_1platform_01_4.html", "structstd_1_1hash_3_01cl_1_1sycl_1_1platform_01_4" ]
    ] ],
    [ "pointers.hpp", "pointers_8hpp.html", "pointers_8hpp" ],
    [ "program.hpp", "program_8hpp.html", null ],
    [ "property_list.hpp", "property__list_8hpp.html", null ],
    [ "property_list_conversion.hpp", "property__list__conversion_8hpp.html", null ],
    [ "queue.hpp", "queue_8hpp.html", "queue_8hpp" ],
    [ "range.hpp", "range_8hpp.html", "range_8hpp" ],
    [ "reduction.hpp", "CL_2sycl_2reduction_8hpp.html", "CL_2sycl_2reduction_8hpp" ],
    [ "sampler.hpp", "sampler_8hpp.html", "sampler_8hpp" ],
    [ "specialization_id.hpp", "specialization__id_8hpp.html", null ],
    [ "stl.hpp", "stl_8hpp.html", "stl_8hpp" ],
    [ "stream.hpp", "stream_8hpp.html", "stream_8hpp" ],
    [ "sub_group.hpp", "CL_2sycl_2sub__group_8hpp.html", "CL_2sycl_2sub__group_8hpp" ],
    [ "sycl_span.hpp", "sycl__span_8hpp.html", null ],
    [ "types.hpp", "CL_2sycl_2types_8hpp.html", "CL_2sycl_2types_8hpp" ],
    [ "usm.hpp", "usm_8hpp.html", "usm_8hpp" ],
    [ "version.hpp", "version_8hpp.html", "version_8hpp" ]
];