DPC++ Runtime: include/CL/sycl/INTEL/esimd/detail/esimd_intrin.hpp File Reference
esimd_intrin.hpp File Reference
#include <CL/sycl/INTEL/esimd/detail/esimd_types.hpp>
#include <CL/sycl/INTEL/esimd/detail/esimd_util.hpp>
#include <CL/sycl/INTEL/esimd/esimd_enum.hpp>
#include <assert.h>
#include <cstdint>
Namespaces
cl
We provide new interfaces for matrix muliply in this patch:
cl::sycl
cl::sycl::INTEL
cl::sycl::INTEL::gpu
cl::sycl::INTEL::gpu::detail
Macros
#define __SIGD sycl::INTEL::gpu::detail
Functions
template<typename T , int N, int M, int VStride, int Width, int Stride, int ParentWidth = 0>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, M > __esimd_rdregion (__SIGD::vector_type_t< T, N > Input, uint16_t Offset)
template<typename T , int N, int M, int ParentWidth = 0>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, M > __esimd_rdindirect (__SIGD::vector_type_t< T, N > Input, __SIGD::vector_type_t< uint16_t, M > Offset)
template<typename T , int N, int M, int VStride, int Width, int Stride, int ParentWidth = 0>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, N > __esimd_wrregion (__SIGD::vector_type_t< T, N > OldVal, __SIGD::vector_type_t< T, M > NewVal, uint16_t Offset, sycl::INTEL::gpu::mask_type_t< M > Mask=1)
template<typename T , int N, int M, int ParentWidth = 0>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, N > __esimd_wrindirect (__SIGD::vector_type_t< T, N > OldVal, __SIGD::vector_type_t< T, M > NewVal, __SIGD::vector_type_t< uint16_t, M > Offset, sycl::INTEL::gpu::mask_type_t< M > Mask=1)
template<typename BT , int BN, typename RTy >
__SIGD::vector_type_t< typename RTy::element_type, RTy::length > ESIMD_INLINE cl::sycl::INTEL::gpu::detail::readRegion (const __SIGD::vector_type_t< BT, BN > &Base, RTy Region)
read from a basic region of a vector, return a vector
template<typename BT , int BN, typename T , typename U >
ESIMD_INLINE __SIGD::vector_type_t< typename T::element_type, T::length > cl::sycl::INTEL::gpu::detail::readRegion (const __SIGD::vector_type_t< BT, BN > &Base, std::pair< T, U > Region)
read from a nested region of a vector, return a vector
template<typename T , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, N > __esimd_vload (const __SIGD::vector_type_t< T, N > *ptr)
template<typename T , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_vstore (__SIGD::vector_type_t< T, N > *ptr, __SIGD::vector_type_t< T, N > vals)
template<typename T , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint16_t __esimd_any (__SIGD::vector_type_t< T, N > src)
template<typename T , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint16_t __esimd_all (__SIGD::vector_type_t< T, N > src)
Macro Definition Documentation
__SIGD
#define __SIGD sycl::INTEL::gpu::detail
Definition at line 21 of file esimd_intrin.hpp.
Function Documentation
__esimd_all()
template<typename T , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint16_t __esimd_all (__SIGD::vector_type_t< T, N > src)
__esimd_any()
template<typename T , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint16_t __esimd_any (__SIGD::vector_type_t< T, N > src)
__esimd_rdindirect()
template<typename T , int N, int M, int ParentWidth = 0> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, M > __esimd_rdindirect (__SIGD::vector_type_t< T, N > Input, __SIGD::vector_type_t< uint16_t, M > Offset)
Definition at line 265 of file esimd_intrin.hpp.
__esimd_rdregion()
template<typename T , int N, int M, int VStride, int Width, int Stride, int ParentWidth = 0> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, M > __esimd_rdregion (__SIGD::vector_type_t< T, N > Input, uint16_t Offset)
Definition at line 246 of file esimd_intrin.hpp.
Referenced by cl::sycl::INTEL::gpu::gather(), cl::sycl::INTEL::gpu::detail::readRegion(), and cl::sycl::INTEL::gpu::simd< Ty, N >::select().
__esimd_vload()
template<typename T , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, N> __esimd_vload (const __SIGD::vector_type_t< T, N > * ptr)
__esimd_vstore()
template<typename T , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_vstore (__SIGD::vector_type_t< T, N > * ptr, __SIGD::vector_type_t< T, N > vals)
__esimd_wrindirect()
template<typename T , int N, int M, int ParentWidth = 0> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, N > __esimd_wrindirect (__SIGD::vector_type_t< T, N > OldVal, __SIGD::vector_type_t< T, M > NewVal, __SIGD::vector_type_t< uint16_t, M > Offset, sycl::INTEL::gpu::mask_type_t< M > Mask = 1)
Definition at line 303 of file esimd_intrin.hpp.
__esimd_wrregion()
template<typename T , int N, int M, int VStride, int Width, int Stride, int ParentWidth = 0> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, N > __esimd_wrregion (__SIGD::vector_type_t< T, N > OldVal, __SIGD::vector_type_t< T, M > NewVal, uint16_t Offset, sycl::INTEL::gpu::mask_type_t< M > Mask = 1)
Definition at line 280 of file esimd_intrin.hpp.
Referenced by cl::sycl::INTEL::gpu::scatter(), and cl::sycl::INTEL::gpu::simd< Ty, N >::writeRegion().