DPC++ Runtime: include/CL/sycl/INTEL/esimd/detail/esimd_math_intrin.hpp File Reference
esimd_math_intrin.hpp File Reference
#include <CL/sycl/INTEL/esimd/detail/esimd_host_util.hpp>
#include <CL/sycl/INTEL/esimd/detail/esimd_types.hpp>
#include <CL/sycl/INTEL/esimd/esimd_enum.hpp>
#include <cstdint>
Macros
#define __SIGD sycl::INTEL::gpu::detail
#define __SIGED sycl::INTEL::gpu::emu::detail
Functions
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_satf (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_fptoui_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_fptosi_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_uutrunc_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_ustrunc_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_sutrunc_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_sstrunc_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_abs (__SIGD::vector_type_t< T, SZ > src0)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_ssshl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_sushl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_usshl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_uushl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_ssshl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_sushl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_usshl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_uushl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_rol (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_ror (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_umulh (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_smulh (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_frc (__SIGD::vector_type_t< float, SZ > src0)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_fmax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
3 kinds of max
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_umax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_smax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_lzd (__SIGD::vector_type_t< T, SZ > src0)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_fmin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
3 kinds of min
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_umin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T, SZ > __esimd_smin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_bfrev (__SIGD::vector_type_t< T1, SZ > src0)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< unsigned int, SZ > __esimd_cbit (__SIGD::vector_type_t< T, SZ > src0)
template<typename T0 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_bfins (__SIGD::vector_type_t< T0, SZ > src0, __SIGD::vector_type_t< T0, SZ > src1, __SIGD::vector_type_t< T0, SZ > src2, __SIGD::vector_type_t< T0, SZ > src3)
template<typename T0 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T0, SZ > __esimd_bfext (__SIGD::vector_type_t< T0, SZ > src0, __SIGD::vector_type_t< T0, SZ > src1, __SIGD::vector_type_t< T0, SZ > src2)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< uint32_t, SZ > __esimd_fbl (__SIGD::vector_type_t< uint32_t, SZ > src0)
template<typename T0 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< int, SZ > __esimd_sfbh (__SIGD::vector_type_t< T0, SZ > src0)
template<typename T0 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< uint32_t, SZ > __esimd_ufbh (__SIGD::vector_type_t< T0, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_inv (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_log (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_exp (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_sqrt (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_sqrt_ieee (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_rsqrt (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_sin (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_cos (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_pow (__SIGD::vector_type_t< float, SZ > src0, __SIGD::vector_type_t< float, SZ > src1)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_div_ieee (__SIGD::vector_type_t< float, SZ > src0, __SIGD::vector_type_t< float, SZ > src1)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_rndd (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_rndu (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_rnde (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< float, SZ > __esimd_rndz (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< double, SZ > __esimd_sqrt_ieee (__SIGD::vector_type_t< double, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< double, SZ > __esimd_div_ieee (__SIGD::vector_type_t< double, SZ > src0, __SIGD::vector_type_t< double, SZ > src1)
template<int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint32_t __esimd_pack_mask (__SIGD::vector_type_t< uint16_t, N > src0)
template<int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< uint16_t, N > __esimd_unpack_mask (uint32_t src0)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T1, N > __esimd_uudp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T1, N > __esimd_usdp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T1, N > __esimd_sudp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T1, N > __esimd_ssdp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T1, N > __esimd_uudp4a_sat (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T1, N > __esimd_usdp4a_sat (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T1, N > __esimd_sudp4a_sat (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< T1, N > __esimd_ssdp4a_sat (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< Ty, N > __esimd_reduced_fmax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< Ty, N > __esimd_reduced_umax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< Ty, N > __esimd_reduced_smax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< Ty, N > __esimd_reduced_fmin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< Ty, N > __esimd_reduced_umin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __esimd_reduced_smin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t< Ty, N > __esimd_dp4 (__SIGD::vector_type_t< Ty, N > v1, __SIGD::vector_type_t< Ty, N > v2)
template<typename T >
T extract (const uint32_t &width, const uint32_t &offset, uint32_t src, const uint32_t &sign_extend)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_satf (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_fptoui_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_fptosi_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_uutrunc_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_ustrunc_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_sutrunc_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_sstrunc_sat (__SIGD::vector_type_t< T1, SZ > src)
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_abs (__SIGD::vector_type_t< T, SZ > src0)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_ssshl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_sushl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_usshl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_uushl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_ssshl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_sushl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_usshl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_uushl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_rol (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_ror (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1)
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_umulh (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_smulh (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_frc (__SIGD::vector_type_t< float, SZ > src0)
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_fmax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
3 kinds of max
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_umax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_smax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_lzd (__SIGD::vector_type_t< T, SZ > src0)
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_fmin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
3 kinds of min
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_umin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
__SIGD::vector_type_t< T, SZ > __esimd_smin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_bfrev (__SIGD::vector_type_t< T1, SZ > src0)
template<typename T , int SZ>
__SIGD::vector_type_t< unsigned int, SZ > __esimd_cbit (__SIGD::vector_type_t< T, SZ > src0)
template<typename T0 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_bfins (__SIGD::vector_type_t< T0, SZ > width, __SIGD::vector_type_t< T0, SZ > offset, __SIGD::vector_type_t< T0, SZ > val, __SIGD::vector_type_t< T0, SZ > src)
template<typename T0 , int SZ>
__SIGD::vector_type_t< T0, SZ > __esimd_bfext (__SIGD::vector_type_t< T0, SZ > width, __SIGD::vector_type_t< T0, SZ > offset, __SIGD::vector_type_t< T0, SZ > src)
template<int SZ>
__SIGD::vector_type_t< uint32_t, SZ > __esimd_fbl (__SIGD::vector_type_t< uint32_t, SZ > src0)
template<typename T0 , int SZ>
__SIGD::vector_type_t< int, SZ > __esimd_sfbh (__SIGD::vector_type_t< T0, SZ > src0)
template<typename T0 , int SZ>
__SIGD::vector_type_t< uint32_t, SZ > __esimd_ufbh (__SIGD::vector_type_t< T0, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_inv (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_log (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_exp (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_sqrt (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_sqrt_ieee (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_rsqrt (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_sin (__SIGD::vector_type_t< float, SZ > src)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_cos (__SIGD::vector_type_t< float, SZ > src)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_pow (__SIGD::vector_type_t< float, SZ > src0, __SIGD::vector_type_t< float, SZ > src1)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_div_ieee (__SIGD::vector_type_t< float, SZ > src0, __SIGD::vector_type_t< float, SZ > src1)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_rndd (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_rndu (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_rnde (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< float, SZ > __esimd_rndz (__SIGD::vector_type_t< float, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< double, SZ > __esimd_sqrt_ieee (__SIGD::vector_type_t< double, SZ > src0)
template<int SZ>
__SIGD::vector_type_t< double, SZ > __esimd_div_ieee (__SIGD::vector_type_t< double, SZ > src0, __SIGD::vector_type_t< double, SZ > src1)
template<int N>
uint32_t __esimd_pack_mask (__SIGD::vector_type_t< uint16_t, N > src0)
template<int N>
__SIGD::vector_type_t< uint16_t, N > __esimd_unpack_mask (uint32_t src0)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
__SIGD::vector_type_t< T1, N > __esimd_dp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > __esimd_reduced_max (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > __esimd_reduced_fmax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > __esimd_reduced_umax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > __esimd_reduced_smax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > __esimd_reduced_min (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > __esimd_reduced_fmin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > __esimd_reduced_umin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SIGD::vector_type_t< Ty, N > __esimd_reduced_smin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2)
Macro Definition Documentation
__SIGD
#define __SIGD sycl::INTEL::gpu::detail
Definition at line 19 of file esimd_math_intrin.hpp.
__SIGED
#define __SIGED sycl::INTEL::gpu::emu::detail
Definition at line 334 of file esimd_math_intrin.hpp.
Function Documentation
__esimd_abs() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_abs (__SIGD::vector_type_t< T, SZ > src0) inline
Definition at line 415 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_abs() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_abs (__SIGD::vector_type_t< T, SZ > src0) inline
Definition at line 415 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfext() [1/2]
template<typename T0 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_bfext (__SIGD::vector_type_t< T0, SZ > src0, __SIGD::vector_type_t< T0, SZ > src1, __SIGD::vector_type_t< T0, SZ > src2) inline
Definition at line 815 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfext() [2/2]
template<typename T0 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_bfext (__SIGD::vector_type_t< T0, SZ > width, __SIGD::vector_type_t< T0, SZ > offset, __SIGD::vector_type_t< T0, SZ > src) inline
Definition at line 815 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfins() [1/2]
template<typename T0 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_bfins (__SIGD::vector_type_t< T0, SZ > src0, __SIGD::vector_type_t< T0, SZ > src1, __SIGD::vector_type_t< T0, SZ > src2, __SIGD::vector_type_t< T0, SZ > src3) inline
Definition at line 790 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfins() [2/2]
template<typename T0 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_bfins (__SIGD::vector_type_t< T0, SZ > width, __SIGD::vector_type_t< T0, SZ > offset, __SIGD::vector_type_t< T0, SZ > val, __SIGD::vector_type_t< T0, SZ > src) inline
Definition at line 790 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfrev() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_bfrev (__SIGD::vector_type_t< T1, SZ > src0) inline
Definition at line 743 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfrev() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_bfrev (__SIGD::vector_type_t< T1, SZ > src0) inline
Definition at line 743 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_cbit() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<unsigned int, SZ> __esimd_cbit (__SIGD::vector_type_t< T, SZ > src0) inline
Definition at line 768 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_cbit().
__esimd_cbit() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<unsigned int, SZ> __esimd_cbit (__SIGD::vector_type_t< T, SZ > src0) inline
Definition at line 768 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_cbit().
__esimd_cos() [1/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_cos (__SIGD::vector_type_t< float, SZ > src) inline
Definition at line 992 of file esimd_math_intrin.hpp.
References cl::sycl::cos(), and SIMDCF_ELEMENT_SKIP.
__esimd_cos() [2/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_cos (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 992 of file esimd_math_intrin.hpp.
References cl::sycl::cos(), and SIMDCF_ELEMENT_SKIP.
__esimd_div_ieee() [1/4]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<double, SZ> __esimd_div_ieee (__SIGD::vector_type_t< double, SZ > src0, __SIGD::vector_type_t< double, SZ > src1) inline
Handle Divide-by-zero
Definition at line 1120 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_div_ieee() [2/4]
template<int SZ> __SIGD::vector_type_t<double, SZ> __esimd_div_ieee (__SIGD::vector_type_t< double, SZ > src0, __SIGD::vector_type_t< double, SZ > src1) inline
Handle Divide-by-zero
Definition at line 1120 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_div_ieee() [3/4]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_div_ieee (__SIGD::vector_type_t< float, SZ > src0, __SIGD::vector_type_t< float, SZ > src1) inline
Handle Divide-by-zero
Definition at line 1015 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_div_ieee() [4/4]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_div_ieee (__SIGD::vector_type_t< float, SZ > src0, __SIGD::vector_type_t< float, SZ > src1) inline
Handle Divide-by-zero
Definition at line 1015 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_dp4()
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<Ty, N> __esimd_dp4 (__SIGD::vector_type_t< Ty, N > v1, __SIGD::vector_type_t< Ty, N > v2) inline
Definition at line 800 of file esimd_memory_intrin.hpp.
__esimd_dp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> __SIGD::vector_type_t<T1, N> __esimd_dp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2) inline
Definition at line 1167 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_exp() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_exp (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 938 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_exp() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_exp (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 938 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fbl() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<uint32_t, SZ> __esimd_fbl (__SIGD::vector_type_t< uint32_t, SZ > src0) inline
Definition at line 834 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_fbl().
__esimd_fbl() [2/2]
template<int SZ> __SIGD::vector_type_t<uint32_t, SZ> __esimd_fbl (__SIGD::vector_type_t< uint32_t, SZ > src0) inline
Definition at line 834 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_fbl().
__esimd_fmax() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_fmax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
3 kinds of max
Definition at line 609 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fmax() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_fmax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
3 kinds of max
Definition at line 609 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fmin() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_fmin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
3 kinds of min
Definition at line 686 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fmin() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_fmin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
3 kinds of min
Definition at line 686 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fptosi_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_fptosi_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 360 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fptosi_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_fptosi_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 360 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fptoui_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_fptoui_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 349 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fptoui_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_fptoui_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 349 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_frc() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_frc (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 597 of file esimd_math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_frc().
__esimd_frc() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_frc (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 597 of file esimd_math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_frc().
__esimd_inv() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_inv (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 915 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_inv() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_inv (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 915 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_log() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_log (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 927 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_log() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_log (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 927 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_lzd() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_lzd (__SIGD::vector_type_t< T, SZ > src0) inline
Definition at line 664 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_lzd() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_lzd (__SIGD::vector_type_t< T, SZ > src0) inline
Definition at line 664 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_pack_mask() [1/2]
template<int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint32_t __esimd_pack_mask (__SIGD::vector_type_t< uint16_t, N > src0) inline
Definition at line 1139 of file esimd_math_intrin.hpp.
__esimd_pack_mask() [2/2]
template<int N> uint32_t __esimd_pack_mask (__SIGD::vector_type_t< uint16_t, N > src0) inline
Definition at line 1139 of file esimd_math_intrin.hpp.
__esimd_pow() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_pow (__SIGD::vector_type_t< float, SZ > src0, __SIGD::vector_type_t< float, SZ > src1) inline
Definition at line 1002 of file esimd_math_intrin.hpp.
References cl::sycl::fabs(), and SIMDCF_ELEMENT_SKIP.
__esimd_pow() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_pow (__SIGD::vector_type_t< float, SZ > src0, __SIGD::vector_type_t< float, SZ > src1) inline
Definition at line 1002 of file esimd_math_intrin.hpp.
References cl::sycl::fabs(), and SIMDCF_ELEMENT_SKIP.
__esimd_reduced_fmax() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<Ty, N> __esimd_reduced_fmax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1219 of file esimd_math_intrin.hpp.
__esimd_reduced_fmax() [2/2]
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> __esimd_reduced_fmax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1219 of file esimd_math_intrin.hpp.
__esimd_reduced_fmin() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<Ty, N> __esimd_reduced_fmin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1255 of file esimd_math_intrin.hpp.
__esimd_reduced_fmin() [2/2]
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> __esimd_reduced_fmin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1255 of file esimd_math_intrin.hpp.
__esimd_reduced_max()
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> __esimd_reduced_max (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1204 of file esimd_math_intrin.hpp.
__esimd_reduced_min()
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> __esimd_reduced_min (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1240 of file esimd_math_intrin.hpp.
__esimd_reduced_smax() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<Ty, N> __esimd_reduced_smax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1233 of file esimd_math_intrin.hpp.
__esimd_reduced_smax() [2/2]
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> __esimd_reduced_smax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1233 of file esimd_math_intrin.hpp.
__esimd_reduced_smin() [1/2]
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __esimd_reduced_smin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1269 of file esimd_math_intrin.hpp.
__esimd_reduced_smin() [2/2]
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> __esimd_reduced_smin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1269 of file esimd_math_intrin.hpp.
__esimd_reduced_umax() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<Ty, N> __esimd_reduced_umax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1226 of file esimd_math_intrin.hpp.
__esimd_reduced_umax() [2/2]
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> __esimd_reduced_umax (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1226 of file esimd_math_intrin.hpp.
__esimd_reduced_umin() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<Ty, N> __esimd_reduced_umin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1262 of file esimd_math_intrin.hpp.
__esimd_reduced_umin() [2/2]
template<typename Ty , int N> __SIGD::vector_type_t<Ty, N> __esimd_reduced_umin (__SIGD::vector_type_t< Ty, N > src1, __SIGD::vector_type_t< Ty, N > src2) inline
Definition at line 1262 of file esimd_math_intrin.hpp.
__esimd_rndd() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_rndd (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 1035 of file esimd_math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndd() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_rndd (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 1035 of file esimd_math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rnde() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_rnde (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 1067 of file esimd_math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rnde() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_rnde (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 1067 of file esimd_math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndu() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_rndu (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 1047 of file esimd_math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndu() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_rndu (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 1047 of file esimd_math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndz() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_rndz (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 1089 of file esimd_math_intrin.hpp.
References cl::sycl::fabs(), cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndz() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_rndz (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 1089 of file esimd_math_intrin.hpp.
References cl::sycl::fabs(), cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rol() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_rol (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 555 of file esimd_math_intrin.hpp.
__esimd_rol() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_rol (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 555 of file esimd_math_intrin.hpp.
__esimd_ror() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_ror (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 560 of file esimd_math_intrin.hpp.
__esimd_ror() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_ror (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 560 of file esimd_math_intrin.hpp.
__esimd_rsqrt() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_rsqrt (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 971 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_rsqrt() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_rsqrt (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 971 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_satf() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_satf (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 338 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_satf() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_satf (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 338 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sfbh() [1/2]
template<typename T0 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<int, SZ> __esimd_sfbh (__SIGD::vector_type_t< T0, SZ > src0) inline
Definition at line 859 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_fbh().
__esimd_sfbh() [2/2]
template<typename T0 , int SZ> __SIGD::vector_type_t<int, SZ> __esimd_sfbh (__SIGD::vector_type_t< T0, SZ > src0) inline
Definition at line 859 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_fbh().
__esimd_sin() [1/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_sin (__SIGD::vector_type_t< float, SZ > src) inline
Definition at line 982 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sin().
__esimd_sin() [2/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_sin (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 982 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sin().
__esimd_smax() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_smax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 645 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_smax() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_smax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 645 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_smin() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_smin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 724 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_smin() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_smin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 724 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_smulh() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_smulh (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 581 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_imul().
__esimd_smulh() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_smulh (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 581 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_imul().
__esimd_sqrt() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_sqrt (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 949 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt() [2/2]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_sqrt (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 949 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt_ieee() [1/4]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<double, SZ> __esimd_sqrt_ieee (__SIGD::vector_type_t< double, SZ > src0) inline
Definition at line 1108 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt_ieee() [2/4]
template<int SZ> __SIGD::vector_type_t<double, SZ> __esimd_sqrt_ieee (__SIGD::vector_type_t< double, SZ > src0) inline
Definition at line 1108 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt_ieee() [3/4]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<float, SZ> __esimd_sqrt_ieee (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 960 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt_ieee() [4/4]
template<int SZ> __SIGD::vector_type_t<float, SZ> __esimd_sqrt_ieee (__SIGD::vector_type_t< float, SZ > src0) inline
Definition at line 960 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_ssdp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T1, N> __esimd_ssdp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
__esimd_ssdp4a_sat()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T1, N> __esimd_ssdp4a_sat (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
__esimd_ssshl() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_ssshl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 434 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ssshl() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_ssshl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 434 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ssshl_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_ssshl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 494 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ssshl_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_ssshl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 494 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sstrunc_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_sstrunc_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 404 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sstrunc_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_sstrunc_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 404 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sudp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T1, N> __esimd_sudp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
__esimd_sudp4a_sat()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T1, N> __esimd_sudp4a_sat (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
__esimd_sushl() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_sushl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 449 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sushl() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_sushl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 449 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sushl_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_sushl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 509 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sushl_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_sushl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 509 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sutrunc_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_sutrunc_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 393 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sutrunc_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_sutrunc_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 393 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ufbh() [1/2]
template<typename T0 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<uint32_t, SZ> __esimd_ufbh (__SIGD::vector_type_t< T0, SZ > src0) inline
Definition at line 891 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_fbh().
__esimd_ufbh() [2/2]
template<typename T0 , int SZ> __SIGD::vector_type_t<uint32_t, SZ> __esimd_ufbh (__SIGD::vector_type_t< T0, SZ > src0) inline
Definition at line 891 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_fbh().
__esimd_umax() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_umax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 627 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_umax() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_umax (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 627 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_umin() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_umin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 705 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_umin() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_umin (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 705 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_umulh() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T, SZ> __esimd_umulh (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 565 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_imul().
__esimd_umulh() [2/2]
template<typename T , int SZ> __SIGD::vector_type_t<T, SZ> __esimd_umulh (__SIGD::vector_type_t< T, SZ > src0, __SIGD::vector_type_t< T, SZ > src1) inline
Definition at line 565 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::INTEL::gpu::esimd_imul().
__esimd_unpack_mask() [1/2]
template<int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<uint16_t, N> __esimd_unpack_mask (uint32_t src0) inline
Definition at line 1153 of file esimd_math_intrin.hpp.
__esimd_unpack_mask() [2/2]
template<int N> __SIGD::vector_type_t<uint16_t, N> __esimd_unpack_mask (uint32_t src0) inline
Definition at line 1153 of file esimd_math_intrin.hpp.
__esimd_usdp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T1, N> __esimd_usdp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
__esimd_usdp4a_sat()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T1, N> __esimd_usdp4a_sat (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
__esimd_usshl() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_usshl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 464 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_usshl() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_usshl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 464 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_usshl_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_usshl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 524 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_usshl_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_usshl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 524 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ustrunc_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_ustrunc_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 382 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ustrunc_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_ustrunc_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 382 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uudp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T1, N> __esimd_uudp4a (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
__esimd_uudp4a_sat()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T1, N> __esimd_uudp4a_sat (__SIGD::vector_type_t< T2, N > src0, __SIGD::vector_type_t< T3, N > src1, __SIGD::vector_type_t< T4, N > src2)
__esimd_uushl() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_uushl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 479 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uushl() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_uushl (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 479 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uushl_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_uushl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 539 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uushl_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_uushl_sat (__SIGD::vector_type_t< T1, SZ > src0, __SIGD::vector_type_t< T1, SZ > src1) inline
Definition at line 539 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uutrunc_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SIGD::vector_type_t<T0, SZ> __esimd_uutrunc_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 371 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uutrunc_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SIGD::vector_type_t<T0, SZ> __esimd_uutrunc_sat (__SIGD::vector_type_t< T1, SZ > src) inline
Definition at line 371 of file esimd_math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
extract()
template<typename T > T extract (const uint32_t & width, const uint32_t & offset, uint32_t src, const uint32_t & sign_extend) inline
Definition at line 320 of file esimd_math_intrin.hpp.