DPC++ Runtime: include/CL/sycl/INTEL/esimd/detail/emu/esimd_emu_functions_v1.h File Reference
esimd_emu_functions_v1.h File Reference
Variables
void(* cm_barrier_ptr)(void)
void(* cm_sbarrier_ptr)(uint32_t)
void(* cm_fence_ptr)(void)
char *(* sycl_get_surface_base_addr_ptr)(int)
char *(* __cm_emu_get_slm_ptr)(void)
void(* cm_slm_init_ptr)(size_t)
Variable Documentation
__cm_emu_get_slm_ptr
char*(* __cm_emu_get_slm_ptr) (void)
Definition at line 45 of file esimd_emu_functions_v1.h.
Referenced by cl::sycl::detail::ESIMDDeviceInterface::ESIMDDeviceInterface().
cm_barrier_ptr
void(* cm_barrier_ptr) (void)
Definition at line 38 of file esimd_emu_functions_v1.h.
Referenced by cl::sycl::detail::ESIMDDeviceInterface::ESIMDDeviceInterface().
cm_fence_ptr
void(* cm_fence_ptr) (void)
Definition at line 40 of file esimd_emu_functions_v1.h.
Referenced by cl::sycl::detail::ESIMDDeviceInterface::ESIMDDeviceInterface().
cm_sbarrier_ptr
void(* cm_sbarrier_ptr) (uint32_t)
Definition at line 39 of file esimd_emu_functions_v1.h.
Referenced by cl::sycl::detail::ESIMDDeviceInterface::ESIMDDeviceInterface().
cm_slm_init_ptr
void(* cm_slm_init_ptr) (size_t)
Definition at line 46 of file esimd_emu_functions_v1.h.
Referenced by cl::sycl::detail::ESIMDDeviceInterface::ESIMDDeviceInterface().
sycl_get_surface_base_addr_ptr
char*(* sycl_get_surface_base_addr_ptr) (int)
Definition at line 44 of file esimd_emu_functions_v1.h.
Referenced by cl::sycl::detail::ESIMDDeviceInterface::ESIMDDeviceInterface().