DPC++ Runtime: include/CL/sycl/INTEL/esimd/detail/esimd_memory_intrin.hpp File Reference
esimd_memory_intrin.hpp File Reference
#include <CL/sycl/INTEL/esimd/detail/esimd_types.hpp>
#include <CL/sycl/INTEL/esimd/detail/esimd_util.hpp>
#include <CL/sycl/INTEL/esimd/esimd_enum.hpp>
#include <CL/sycl/types.hpp>
#include <cstdint>
Functions
template<typename Ty , int N, int NumBlk = 0, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N *sycl::INTEL::gpu::ElemsPerAddrDecoding(NumBlk)> __esimd_flat_read (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, int ElemsPerAddr=NumBlk, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, int NumBlk = 0, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL void __esimd_flat_write (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *sycl::INTEL::gpu::ElemsPerAddrDecoding(NumBlk)> vals, int ElemsPerAddr=NumBlk, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_flat_block_read_unaligned (uint64_t addr)
template<typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL void __esimd_flat_block_write (uint64_t addr, sycl::INTEL::gpu::vector_type_t< Ty, N > vals)
template<typename Ty , int N, typename SurfIndAliasTy >
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_block_read (SurfIndAliasTy surf_ind, uint32_t offset)
template<typename Ty , int N, typename SurfIndAliasTy >
SYCL_EXTERNAL void __esimd_block_write (SurfIndAliasTy surf_ind, uint32_t offset, sycl::INTEL::gpu::vector_type_t< Ty, N > vals)
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> SYCL_EXTERNAL __esimd_flat_read4 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL void __esimd_flat_write4 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, typename SurfIndAliasTy , int TySizeLog2, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_surf_read (int16_t scale, SurfIndAliasTy surf_ind, uint32_t global_offset, sycl::INTEL::gpu::vector_type_t< uint32_t, N > elem_offsets)
template<typename Ty , int N, typename SurfIndAliasTy , int TySizeLog2, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL void __esimd_surf_write (sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, int16_t scale, SurfIndAliasTy surf_ind, uint32_t global_offset, sycl::INTEL::gpu::vector_type_t< uint32_t, N > elem_offsets, sycl::INTEL::gpu::vector_type_t< Ty, N > vals)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_flat_atomic0 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_flat_atomic1 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_flat_atomic2 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< Ty, N > src1, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
SYCL_EXTERNAL void __esimd_barrier ()
TODO.
SYCL_EXTERNAL void __esimd_sbarrier (sycl::INTEL::gpu::EsimdSbarrierType flag)
SYCL_EXTERNAL void __esimd_slm_fence (uint8_t cntl)
template<typename Ty , int N>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_read (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N>
SYCL_EXTERNAL void __esimd_slm_write (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_block_read (uint32_t addr)
template<typename Ty , int N>
SYCL_EXTERNAL void __esimd_slm_block_write (uint32_t addr, sycl::INTEL::gpu::vector_type_t< Ty, N > vals)
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> __esimd_slm_read4 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask>
SYCL_EXTERNAL void __esimd_slm_write4 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred=1)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_atomic0 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_atomic1 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_atomic2 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< Ty, N > src1, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int M, int N, typename TACC >
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, M *N > __esimd_media_block_load (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y)
template<typename Ty , int M, int N, typename TACC >
SYCL_EXTERNAL void __esimd_media_block_store (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y, sycl::INTEL::gpu::vector_type_t< Ty, M *N > vals)
template<typename SurfIndAliasTy >
SYCL_EXTERNAL uint32_t __esimd_get_value (SurfIndAliasTy sid)
esimd_get_value
template<typename Ty1 , int N1, typename Ty2 , int N2, typename Ty3 , int N3, int N = 16>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty1, N1 > __esimd_raw_sends_load (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty3, N3 > msgSrc1, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgDst)
Raw sends load.
template<typename Ty1 , int N1, typename Ty2 , int N2, int N = 16>
SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty1, N1 > __esimd_raw_send_load (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgDst)
Raw send load.
template<typename Ty1 , int N1, typename Ty2 , int N2, int N = 16>
SYCL_EXTERNAL void __esimd_raw_sends_store (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc1)
Raw sends store.
template<typename Ty1 , int N1, int N = 16>
SYCL_EXTERNAL void __esimd_raw_send_store (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgSrc0)
Raw send store.
template<typename Ty , int N, int NumBlk, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
sycl::INTEL::gpu::vector_type_t< Ty, N *sycl::INTEL::gpu::ElemsPerAddrDecoding(NumBlk)> __esimd_flat_read (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, int ElemsPerAddr, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> __esimd_flat_read4 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, int NumBlk, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
void __esimd_flat_write (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *sycl::INTEL::gpu::ElemsPerAddrDecoding(NumBlk)> vals, int ElemsPerAddr, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
void __esimd_flat_write4 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_flat_block_read_unaligned (uint64_t addr)
template<typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
void __esimd_flat_block_write (uint64_t addr, sycl::INTEL::gpu::vector_type_t< Ty, N > vals)
template<typename Ty , int M, int N, typename TACC >
sycl::INTEL::gpu::vector_type_t< Ty, M *N > __esimd_media_block_load (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y)
template<typename Ty , int M, int N, typename TACC >
void __esimd_media_block_store (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y, sycl::INTEL::gpu::vector_type_t< Ty, M *N > vals)
template<typename Ty , int N>
uint16_t __esimd_any (sycl::INTEL::gpu::vector_type_t< Ty, N > src)
template<typename Ty , int N>
uint16_t __esimd_all (sycl::INTEL::gpu::vector_type_t< Ty, N > src)
template<typename Ty , int N>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_dp4 (sycl::INTEL::gpu::vector_type_t< Ty, N > v1, sycl::INTEL::gpu::vector_type_t< Ty, N > v2)
template<typename Ty , int N>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_read (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N>
void __esimd_slm_write (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_block_read (uint32_t addr)
template<typename Ty , int N>
void __esimd_slm_block_write (uint32_t addr, sycl::INTEL::gpu::vector_type_t< Ty, N > vals)
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask>
sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> __esimd_slm_read4 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask>
void __esimd_slm_write4 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_atomic0 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_atomic1 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_slm_atomic2 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< Ty, N > src1, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_flat_atomic0 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_flat_atomic1 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H>
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_flat_atomic2 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< Ty, N > src1, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, typename SurfIndAliasTy >
sycl::INTEL::gpu::vector_type_t< Ty, N > __esimd_block_read (SurfIndAliasTy surf_ind, uint32_t offset)
template<typename Ty , int N, typename SurfIndAliasTy >
void __esimd_block_write (SurfIndAliasTy surf_ind, uint32_t offset, sycl::INTEL::gpu::vector_type_t< Ty, N > vals)
template<typename AccessorTy >
uint32_t __esimd_get_value (AccessorTy acc)
esimd_get_value
template<typename Ty1 , int N1, typename Ty2 , int N2, typename Ty3 , int N3, int N>
sycl::INTEL::gpu::vector_type_t< Ty1, N1 > __esimd_raw_sends_load (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty3, N3 > msgSrc1, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgDst)
Raw sends load.
template<typename Ty1 , int N1, typename Ty2 , int N2, int N>
sycl::INTEL::gpu::vector_type_t< Ty1, N1 > __esimd_raw_send_load (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgDst)
Raw send load.
template<typename Ty1 , int N1, typename Ty2 , int N2, int N>
void __esimd_raw_sends_store (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc1)
Raw sends store.
template<typename Ty1 , int N1, int N>
void __esimd_raw_send_store (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgSrc0)
Raw send store.
Function Documentation
__esimd_all()
template<typename Ty , int N> uint16_t __esimd_all (sycl::INTEL::gpu::vector_type_t< Ty, N > src) inline
Definition at line 751 of file esimd_memory_intrin.hpp.
__esimd_any()
template<typename Ty , int N> uint16_t __esimd_any (sycl::INTEL::gpu::vector_type_t< Ty, N > src) inline
Definition at line 742 of file esimd_memory_intrin.hpp.
__esimd_barrier()
void __esimd_barrier () inline
TODO.
Definition at line 776 of file esimd_memory_intrin.hpp.
Referenced by cl::sycl::INTEL::gpu::esimd_barrier().
__esimd_block_read() [1/2]
template<typename Ty , int N, typename SurfIndAliasTy > SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_block_read (SurfIndAliasTy surf_ind, uint32_t offset) inline
Definition at line 887 of file esimd_memory_intrin.hpp.
__esimd_block_read() [2/2]
template<typename Ty , int N, typename SurfIndAliasTy > sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_block_read (SurfIndAliasTy surf_ind, uint32_t offset) inline
Definition at line 887 of file esimd_memory_intrin.hpp.
__esimd_block_write() [1/2]
template<typename Ty , int N, typename SurfIndAliasTy > SYCL_EXTERNAL void __esimd_block_write (SurfIndAliasTy surf_ind, uint32_t offset, sycl::INTEL::gpu::vector_type_t< Ty, N > vals) inline
Definition at line 893 of file esimd_memory_intrin.hpp.
__esimd_block_write() [2/2]
template<typename Ty , int N, typename SurfIndAliasTy > void __esimd_block_write (SurfIndAliasTy surf_ind, uint32_t offset, sycl::INTEL::gpu::vector_type_t< Ty, N > vals) inline
Definition at line 893 of file esimd_memory_intrin.hpp.
__esimd_dp4()
template<typename Ty , int N> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_dp4 (sycl::INTEL::gpu::vector_type_t< Ty, N > v1, sycl::INTEL::gpu::vector_type_t< Ty, N > v2) inline
Definition at line 761 of file esimd_memory_intrin.hpp.
__esimd_flat_atomic0() [1/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_flat_atomic0 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 858 of file esimd_memory_intrin.hpp.
__esimd_flat_atomic0() [2/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_flat_atomic0 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 858 of file esimd_memory_intrin.hpp.
__esimd_flat_atomic1() [1/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_flat_atomic1 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 867 of file esimd_memory_intrin.hpp.
__esimd_flat_atomic1() [2/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_flat_atomic1 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 867 of file esimd_memory_intrin.hpp.
__esimd_flat_atomic2() [1/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_flat_atomic2 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< Ty, N > src1, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 877 of file esimd_memory_intrin.hpp.
__esimd_flat_atomic2() [2/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_flat_atomic2 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< Ty, N > src1, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 877 of file esimd_memory_intrin.hpp.
__esimd_flat_block_read_unaligned() [1/2]
template<typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_flat_block_read_unaligned (uint64_t addr) inline
Definition at line 623 of file esimd_memory_intrin.hpp.
__esimd_flat_block_read_unaligned() [2/2]
template<typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_flat_block_read_unaligned (uint64_t addr) inline
Definition at line 623 of file esimd_memory_intrin.hpp.
__esimd_flat_block_write() [1/2]
template<typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL void __esimd_flat_block_write (uint64_t addr, sycl::INTEL::gpu::vector_type_t< Ty, N > vals) inline
Definition at line 636 of file esimd_memory_intrin.hpp.
__esimd_flat_block_write() [2/2]
template<typename Ty , int N, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> void __esimd_flat_block_write (uint64_t addr, sycl::INTEL::gpu::vector_type_t< Ty, N > vals) inline
Definition at line 636 of file esimd_memory_intrin.hpp.
__esimd_flat_read() [1/2]
template<typename Ty , int N, int NumBlk, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> sycl::INTEL::gpu::vector_type_t< Ty, N * sycl::INTEL::gpu::ElemsPerAddrDecoding(NumBlk)> __esimd_flat_read (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, int ElemsPerAddr, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 471 of file esimd_memory_intrin.hpp.
References cl::sycl::INTEL::gpu::ElemsPerAddrDecoding().
__esimd_flat_read() [2/2]
template<typename Ty , int N, int NumBlk = 0, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t< Ty, N * sycl::INTEL::gpu::ElemsPerAddrDecoding(NumBlk)> __esimd_flat_read (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, int ElemsPerAddr = NumBlk, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 471 of file esimd_memory_intrin.hpp.
References cl::sycl::INTEL::gpu::ElemsPerAddrDecoding().
__esimd_flat_read4() [1/2]
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> sycl::INTEL::gpu::vector_type_t<Ty, N * NumChannels(Mask)> __esimd_flat_read4 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 500 of file esimd_memory_intrin.hpp.
References HasA, HasB, HasG, HasR, and NumChannels.
__esimd_flat_read4() [2/2]
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> sycl::INTEL::gpu::vector_type_t<Ty, N * NumChannels(Mask)> SYCL_EXTERNAL __esimd_flat_read4 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 500 of file esimd_memory_intrin.hpp.
References HasA, HasB, HasG, HasR, and NumChannels.
__esimd_flat_write() [1/2]
template<typename Ty , int N, int NumBlk, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> void __esimd_flat_write (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *sycl::INTEL::gpu::ElemsPerAddrDecoding(NumBlk)> vals, int ElemsPerAddr, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 548 of file esimd_memory_intrin.hpp.
References cl::sycl::INTEL::gpu::ElemsPerAddrDecoding().
__esimd_flat_write() [2/2]
template<typename Ty , int N, int NumBlk = 0, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL void __esimd_flat_write (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *sycl::INTEL::gpu::ElemsPerAddrDecoding(NumBlk)> vals, int ElemsPerAddr = NumBlk, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 548 of file esimd_memory_intrin.hpp.
References cl::sycl::INTEL::gpu::ElemsPerAddrDecoding().
__esimd_flat_write4() [1/2]
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask, sycl::INTEL::gpu::CacheHint L1H, sycl::INTEL::gpu::CacheHint L3H> void __esimd_flat_write4 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 575 of file esimd_memory_intrin.hpp.
References HasA, HasB, HasG, HasR, and NumChannels.
__esimd_flat_write4() [2/2]
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL void __esimd_flat_write4 (sycl::INTEL::gpu::vector_type_t< uint64_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 575 of file esimd_memory_intrin.hpp.
References HasA, HasB, HasG, HasR, and NumChannels.
__esimd_get_value() [1/2]
template<typename AccessorTy > uint32_t __esimd_get_value (AccessorTy acc) inline
esimd_get_value
Parameters
acc the SYCL accessor.
Returns the binding table index value.
Definition at line 906 of file esimd_memory_intrin.hpp.
__esimd_get_value() [2/2]
template<typename SurfIndAliasTy > SYCL_EXTERNAL uint32_t __esimd_get_value (SurfIndAliasTy sid)
esimd_get_value
Parameters
sid the SYCL accessor.
Returns the binding table index value.
Referenced by cl::sycl::INTEL::gpu::esimd_get_value().
__esimd_media_block_load() [1/2]
template<typename Ty , int M, int N, typename TACC > SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, M * N> __esimd_media_block_load (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y) inline
Definition at line 646 of file esimd_memory_intrin.hpp.
__esimd_media_block_load() [2/2]
template<typename Ty , int M, int N, typename TACC > sycl::INTEL::gpu::vector_type_t<Ty, M * N> __esimd_media_block_load (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y) inline
Definition at line 646 of file esimd_memory_intrin.hpp.
__esimd_media_block_store() [1/2]
template<typename Ty , int M, int N, typename TACC > SYCL_EXTERNAL void __esimd_media_block_store (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y, sycl::INTEL::gpu::vector_type_t< Ty, M *N > vals) inline
Definition at line 697 of file esimd_memory_intrin.hpp.
__esimd_media_block_store() [2/2]
template<typename Ty , int M, int N, typename TACC > void __esimd_media_block_store (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y, sycl::INTEL::gpu::vector_type_t< Ty, M *N > vals) inline
Definition at line 697 of file esimd_memory_intrin.hpp.
__esimd_raw_send_load() [1/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, int N = 16> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty1, N1> __esimd_raw_send_load (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgDst) inline
Raw send load.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgDst the destination operand of send message.
Returns a simd vector of type Ty1 and size N1.
Definition at line 984 of file esimd_memory_intrin.hpp.
__esimd_raw_send_load() [2/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, int N> sycl::INTEL::gpu::vector_type_t<Ty1, N1> __esimd_raw_send_load (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgDst) inline
Raw send load.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgDst the destination operand of send message.
Returns a simd vector of type Ty1 and size N1.
Definition at line 984 of file esimd_memory_intrin.hpp.
__esimd_raw_send_store() [1/2]
template<typename Ty1 , int N1, int N = 16> SYCL_EXTERNAL void __esimd_raw_send_store (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgSrc0) inline
Raw send store.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
Definition at line 1050 of file esimd_memory_intrin.hpp.
__esimd_raw_send_store() [2/2]
template<typename Ty1 , int N1, int N> void __esimd_raw_send_store (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgSrc0) inline
Raw send store.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
Definition at line 1050 of file esimd_memory_intrin.hpp.
__esimd_raw_sends_load() [1/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, typename Ty3 , int N3, int N = 16> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty1, N1> __esimd_raw_sends_load (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty3, N3 > msgSrc1, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgDst) inline
Raw sends load.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
msgDst the destination operand of send message.
Returns a simd vector of type Ty1 and size N1.
Definition at line 945 of file esimd_memory_intrin.hpp.
__esimd_raw_sends_load() [2/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, typename Ty3 , int N3, int N> sycl::INTEL::gpu::vector_type_t<Ty1, N1> __esimd_raw_sends_load (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty3, N3 > msgSrc1, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgDst) inline
Raw sends load.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
msgDst the destination operand of send message.
Returns a simd vector of type Ty1 and size N1.
Definition at line 945 of file esimd_memory_intrin.hpp.
__esimd_raw_sends_store() [1/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, int N = 16> SYCL_EXTERNAL void __esimd_raw_sends_store (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc1) inline
Raw sends store.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
Definition at line 1020 of file esimd_memory_intrin.hpp.
__esimd_raw_sends_store() [2/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, int N> void __esimd_raw_sends_store (uint8_t modifier, uint8_t execSize, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, sycl::INTEL::gpu::vector_type_t< Ty1, N1 > msgSrc0, sycl::INTEL::gpu::vector_type_t< Ty2, N2 > msgSrc1) inline
Raw sends store.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
Definition at line 1020 of file esimd_memory_intrin.hpp.
__esimd_sbarrier()
void __esimd_sbarrier (sycl::INTEL::gpu::EsimdSbarrierType flag) inline
Definition at line 778 of file esimd_memory_intrin.hpp.
Referenced by cl::sycl::INTEL::gpu::esimd_sbarrier().
__esimd_slm_atomic0() [1/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_atomic0 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 830 of file esimd_memory_intrin.hpp.
__esimd_slm_atomic0() [2/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_atomic0 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 830 of file esimd_memory_intrin.hpp.
__esimd_slm_atomic1() [1/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_atomic1 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 838 of file esimd_memory_intrin.hpp.
__esimd_slm_atomic1() [2/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_atomic1 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 838 of file esimd_memory_intrin.hpp.
__esimd_slm_atomic2() [1/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_atomic2 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< Ty, N > src1, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 847 of file esimd_memory_intrin.hpp.
__esimd_slm_atomic2() [2/2]
template<sycl::INTEL::gpu::EsimdAtomicOpType Op, typename Ty , int N> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_atomic2 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > src0, sycl::INTEL::gpu::vector_type_t< Ty, N > src1, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 847 of file esimd_memory_intrin.hpp.
__esimd_slm_block_read() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_block_read (uint32_t addr) inline
Definition at line 800 of file esimd_memory_intrin.hpp.
__esimd_slm_block_read() [2/2]
template<typename Ty , int N> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_block_read (uint32_t addr) inline
Definition at line 800 of file esimd_memory_intrin.hpp.
__esimd_slm_block_write() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL void __esimd_slm_block_write (uint32_t addr, sycl::INTEL::gpu::vector_type_t< Ty, N > vals) inline
Definition at line 808 of file esimd_memory_intrin.hpp.
__esimd_slm_block_write() [2/2]
template<typename Ty , int N> void __esimd_slm_block_write (uint32_t addr, sycl::INTEL::gpu::vector_type_t< Ty, N > vals) inline
Definition at line 808 of file esimd_memory_intrin.hpp.
__esimd_slm_fence()
void __esimd_slm_fence (uint8_t cntl) inline
Definition at line 780 of file esimd_memory_intrin.hpp.
Referenced by cl::sycl::INTEL::gpu::esimd_barrier(), and cl::sycl::INTEL::gpu::esimd_fence().
__esimd_slm_read() [1/2]
template<typename Ty , int N> sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_read (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 784 of file esimd_memory_intrin.hpp.
__esimd_slm_read() [2/2]
template<typename Ty , int N> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_slm_read (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 784 of file esimd_memory_intrin.hpp.
__esimd_slm_read4() [1/2]
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask> sycl::INTEL::gpu::vector_type_t<Ty, N * NumChannels(Mask)> __esimd_slm_read4 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 814 of file esimd_memory_intrin.hpp.
References NumChannels.
__esimd_slm_read4() [2/2]
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N * NumChannels(Mask)> __esimd_slm_read4 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 814 of file esimd_memory_intrin.hpp.
References NumChannels.
__esimd_slm_write() [1/2]
template<typename Ty , int N> void __esimd_slm_write (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 793 of file esimd_memory_intrin.hpp.
__esimd_slm_write() [2/2]
template<typename Ty , int N> SYCL_EXTERNAL void __esimd_slm_write (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N > vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 793 of file esimd_memory_intrin.hpp.
__esimd_slm_write4() [1/2]
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask> void __esimd_slm_write4 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred) inline
Definition at line 822 of file esimd_memory_intrin.hpp.
__esimd_slm_write4() [2/2]
template<typename Ty , int N, sycl::INTEL::gpu::ChannelMaskType Mask> SYCL_EXTERNAL void __esimd_slm_write4 (sycl::INTEL::gpu::vector_type_t< uint32_t, N > addrs, sycl::INTEL::gpu::vector_type_t< Ty, N *NumChannels(Mask)> vals, sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 822 of file esimd_memory_intrin.hpp.
__esimd_surf_read()
template<typename Ty , int N, typename SurfIndAliasTy , int TySizeLog2, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL sycl::INTEL::gpu::vector_type_t<Ty, N> __esimd_surf_read (int16_t scale, SurfIndAliasTy surf_ind, uint32_t global_offset, sycl::INTEL::gpu::vector_type_t< uint32_t, N > elem_offsets)
Definition at line 110 of file esimd_memory_intrin.hpp.
Referenced by cl::sycl::INTEL::gpu::gather().
__esimd_surf_write()
template<typename Ty , int N, typename SurfIndAliasTy , int TySizeLog2, sycl::INTEL::gpu::CacheHint L1H = sycl::INTEL::gpu::CacheHint::None, sycl::INTEL::gpu::CacheHint L3H = sycl::INTEL::gpu::CacheHint::None> SYCL_EXTERNAL void __esimd_surf_write (sycl::INTEL::gpu::vector_type_t< uint16_t, N > pred, int16_t scale, SurfIndAliasTy surf_ind, uint32_t global_offset, sycl::INTEL::gpu::vector_type_t< uint32_t, N > elem_offsets, sycl::INTEL::gpu::vector_type_t< Ty, N > vals)
Definition at line 152 of file esimd_memory_intrin.hpp.