DPC++ Runtime: include/sycl/ext/intel/math.hpp File Reference
math.hpp File Reference
#include <cstdint>
#include <sycl/bit_cast.hpp>
#include <sycl/builtins.hpp>
#include <sycl/ext/intel/math/imf_fp_conversions.hpp>
#include <sycl/ext/intel/math/imf_half_trivial.hpp>
#include <sycl/ext/intel/math/imf_rounding_math.hpp>
#include <sycl/ext/intel/math/imf_simd.hpp>
#include <sycl/ext/oneapi/bfloat16.hpp>
#include <sycl/half_type.hpp>
#include <type_traits>
Namespaces
sycl
sycl::_V1
sycl::_V1::ext
sycl::_V1::ext::intel
sycl::_V1::ext::intel::math
Typedefs
using _iml_half_internal = uint16_t
Functions
float __imf_saturatef (float)
float __imf_copysignf (float, float)
double __imf_copysign (double, double)
_iml_half_internal __imf_copysignf16 (_iml_half_internal, _iml_half_internal)
float __imf_ceilf (float)
double __imf_ceil (double)
_iml_half_internal __imf_ceilf16 (_iml_half_internal)
float __imf_floorf (float)
double __imf_floor (double)
_iml_half_internal __imf_floorf16 (_iml_half_internal)
float __imf_rintf (float)
double __imf_rint (double)
_iml_half_internal __imf_invf16 (_iml_half_internal)
float __imf_invf (float)
double __imf_inv (double)
_iml_half_internal __imf_rintf16 (_iml_half_internal)
float __imf_sqrtf (float)
double __imf_sqrt (double)
_iml_half_internal __imf_sqrtf16 (_iml_half_internal)
float __imf_rsqrtf (float)
double __imf_rsqrt (double)
_iml_half_internal __imf_rsqrtf16 (_iml_half_internal)
float __imf_truncf (float)
double __imf_trunc (double)
_iml_half_internal __imf_truncf16 (_iml_half_internal)
double __imf_rcp64h (double)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::saturate (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::copysign (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::copysign (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sycl::_V1::ext::intel::math::copysign (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::ceil (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::ceil (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sycl::_V1::ext::intel::math::ceil (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > sycl::_V1::ext::intel::math::ceil (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::floor (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::floor (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sycl::_V1::ext::intel::math::floor (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > sycl::_V1::ext::intel::math::floor (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::inv (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::inv (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sycl::_V1::ext::intel::math::inv (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > sycl::_V1::ext::intel::math::inv (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::rint (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::rint (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sycl::_V1::ext::intel::math::rint (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > sycl::_V1::ext::intel::math::rint (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::sqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::sqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sycl::_V1::ext::intel::math::sqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > sycl::_V1::ext::intel::math::sqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::rsqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::rsqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sycl::_V1::ext::intel::math::rsqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > sycl::_V1::ext::intel::math::rsqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sycl::_V1::ext::intel::math::trunc (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::trunc (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sycl::_V1::ext::intel::math::trunc (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > sycl::_V1::ext::intel::math::trunc (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sycl::_V1::ext::intel::math::rcp64h (Tp x)
Typedef Documentation
_iml_half_internal
using _iml_half_internal = uint16_t
Definition at line 21 of file math.hpp.
Function Documentation
__imf_ceil()
double __imf_ceil (double)
Referenced by sycl::_V1::ext::intel::math::ceil().
__imf_ceilf()
float __imf_ceilf (float)
Referenced by sycl::_V1::ext::intel::math::ceil().
__imf_ceilf16()
_iml_half_internal __imf_ceilf16 (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::ceil().
__imf_copysign()
double __imf_copysign (double , double)
Referenced by sycl::_V1::ext::intel::math::copysign().
__imf_copysignf()
float __imf_copysignf (float , float)
Referenced by sycl::_V1::ext::intel::math::copysign().
__imf_copysignf16()
_iml_half_internal __imf_copysignf16 (_iml_half_internal , _iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::copysign().
__imf_floor()
double __imf_floor (double)
Referenced by sycl::_V1::ext::intel::math::floor().
__imf_floorf()
float __imf_floorf (float)
Referenced by sycl::_V1::ext::intel::math::floor().
__imf_floorf16()
_iml_half_internal __imf_floorf16 (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::floor().
__imf_inv()
double __imf_inv (double)
Referenced by sycl::_V1::ext::intel::math::inv().
__imf_invf()
float __imf_invf (float)
Referenced by sycl::_V1::ext::intel::math::inv().
__imf_invf16()
_iml_half_internal __imf_invf16 (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::inv().
__imf_rcp64h()
double __imf_rcp64h (double)
Referenced by sycl::_V1::ext::intel::math::rcp64h().
__imf_rint()
double __imf_rint (double)
Referenced by sycl::_V1::ext::intel::math::rint().
__imf_rintf()
float __imf_rintf (float)
Referenced by sycl::_V1::ext::intel::math::rint().
__imf_rintf16()
_iml_half_internal __imf_rintf16 (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::rint().
__imf_rsqrt()
double __imf_rsqrt (double)
Referenced by sycl::_V1::ext::intel::math::rsqrt().
__imf_rsqrtf()
float __imf_rsqrtf (float)
Referenced by sycl::_V1::ext::intel::math::rsqrt().
__imf_rsqrtf16()
_iml_half_internal __imf_rsqrtf16 (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::rsqrt().
__imf_saturatef()
float __imf_saturatef (float)
Referenced by sycl::_V1::ext::intel::math::saturate().
__imf_sqrt()
double __imf_sqrt (double)
Referenced by sycl::_V1::ext::intel::math::sqrt().
__imf_sqrtf()
float __imf_sqrtf (float)
Referenced by sycl::_V1::ext::intel::math::sqrt().
__imf_sqrtf16()
_iml_half_internal __imf_sqrtf16 (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::sqrt().
__imf_trunc()
double __imf_trunc (double)
Referenced by sycl::_V1::ext::intel::math::trunc().
__imf_truncf()
float __imf_truncf (float)
Referenced by sycl::_V1::ext::intel::math::trunc().
__imf_truncf16()
_iml_half_internal __imf_truncf16 (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::trunc().