DPC++ Runtime: Device selectors
Device selectors
DPC++ User API
Device selectors enable DPC++ runtime to choose the best devices based on heuristics specified by the user, or by one of the built-in selectors.
Classes
class sycl::_V1::accelerator_selector
The default selector chooses the first available SYCL device.
Functions
class sycl::_V1::__SYCL2020_DEPRECATED ("Use SYCL 2020 callable device selectors instead.") device_selector
The SYCL 1.2.1 device_selector class provides ability to choose the best SYCL device based on heuristics specified by the user.
class __SYCL2020_DEPRECATED("Host device is no longer supported.") host_selector int sycl::_V1::default_selector_v (const device &dev)
Selects SYCL host device.
Detailed Description
Device selectors enable DPC++ runtime to choose the best devices based on heuristics specified by the user, or by one of the built-in selectors.
Function Documentation
__SYCL2020_DEPRECATED()
class sycl::_V1::__SYCL2020_DEPRECATED ("Use SYCL 2020 callable device selectors instead.")
The SYCL 1.2.1 device_selector class provides ability to choose the best SYCL device based on heuristics specified by the user.
See also
device
Definition at line 1 of file device_selector.hpp.
default_selector_v()
int sycl::_V1::default_selector_v (const device & dev)
Selects SYCL host device.
See also
device
Definition at line 178 of file device_selector.cpp.
Referenced by sycl::_V1::detail::context_impl::get_backend_info< info::device::version >(), sycl::_V1::detail::kernel_impl::get_backend_info< info::device::version >(), sycl::_V1::ext::oneapi::detail::filter_selector_impl::operator()(), and sycl::_V1::detail::platform_impl::get_backend_info< info::device::version >().