DPC++ Runtime: DPC++ Explicit SIMD API
DPC++ Explicit SIMD API
Modules
SLM functions
Raw send APIs
APIs below are used to implement the send messages on Intel(R) processor graphics, as defined in the documentation at https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-icllp-vol02a-commandreference-instructions_2.pdf.
Classes
class cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >
The simd vector class.
class cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >
The reference class.
Functions
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<((n==8||n==16||n==32) &&(ElemsPerAddr==1||ElemsPerAddr==2||ElemsPerAddr==4)), simd< T, n *ElemsPerAddr > > cl::sycl::ext::intel::experimental::esimd::gather (T *p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
Flat-address gather.
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<((n==8||n==16||n==32) &&(ElemsPerAddr==1||ElemsPerAddr==2||ElemsPerAddr==4)), void > cl::sycl::ext::intel::experimental::esimd::scatter (T *p, simd< T, n *ElemsPerAddr > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
Flat-address scatter.
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > cl::sycl::ext::intel::experimental::esimd::block_load (const T *const addr)
Flat-address block-load.
template<typename T , int n, typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > cl::sycl::ext::intel::experimental::esimd::block_load (AccessorTy acc, uint32_t offset)
Accessor-based block-load.
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::block_store (T *p, simd< T, n > vals)
Flat-address block-store.
template<typename T , int n, typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::block_store (AccessorTy acc, uint32_t offset, simd< T, n > vals)
Accessor-based block-store.
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(sizeof(T)<=4) &&(N==1||N==8||N==16) &&!std::is_pointer< AccessorTy >::value, simd< T, N > > cl::sycl::ext::intel::experimental::esimd::gather (AccessorTy acc, simd< uint32_t, N > offsets, uint32_t glob_offset=0)
Accessor-based gather.
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(sizeof(T)<=4) &&(N==1||N==8||N==16) &&!std::is_pointer< AccessorTy >::value, void > cl::sycl::ext::intel::experimental::esimd::scatter (AccessorTy acc, simd< T, N > vals, simd< uint32_t, N > offsets, uint32_t glob_offset=0, simd< uint16_t, N > pred=1)
Accessor-based scatter.
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG T cl::sycl::ext::intel::experimental::esimd::scalar_load (AccessorTy acc, uint32_t offset)
Load a scalar value from an accessor.
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::scalar_store (AccessorTy acc, uint32_t offset, T val)
Store a scalar value into an accessor.
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==16||n==32) &&(sizeof(T)==4), simd< T, n *NumChannels(Mask)> > cl::sycl::ext::intel::experimental::esimd::gather4 (T *p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
Flat-address gather4.
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==16||n==32) &&(sizeof(T)==4), void > cl::sycl::ext::intel::experimental::esimd::scatter4 (T *p, simd< T, n *NumChannels(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
Flat-address scatter4.
template<EsimdAtomicOpType Op, typename T , int N, unsigned NumSrc>
constexpr bool cl::sycl::ext::intel::experimental::esimd::detail::check_atomic ()
Check the legality of an atomic call in terms of size and type.
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 0 >), simd< T, n > > cl::sycl::ext::intel::experimental::esimd::flat_atomic (T *p, simd< unsigned, n > offset, simd< ushort, n > pred)
Flat-address atomic, zero source operand: inc and dec.
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 1 >), simd< T, n > > cl::sycl::ext::intel::experimental::esimd::flat_atomic (T *p, simd< unsigned, n > offset, simd< T, n > src0, simd< ushort, n > pred)
Flat-address atomic, one source operand, add/sub/min/max etc.
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 2 >), simd< T, n > > cl::sycl::ext::intel::experimental::esimd::flat_atomic (T *p, simd< unsigned, n > offset, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
Flat-address atomic, two source operands.
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_fence (uint8_t cntl)
esimd_fence sets the memory read/write order.
ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_barrier ()
Generic work-group barrier.
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0>
ESIMD_INLINE ESIMD_NODEBUG simd< T, m *n > cl::sycl::ext::intel::experimental::esimd::media_block_load (AccessorTy acc, unsigned x, unsigned y)
Media block load.
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0>
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::media_block_store (AccessorTy acc, unsigned x, unsigned y, simd< T, m *n > vals)
Media block store.
template<typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG uint32_t cl::sycl::ext::intel::experimental::esimd::esimd_get_value (AccessorTy acc)
esimd_get_value
Detailed Description
Function Documentation
block_load() [1/2]
template<typename T , int n, typename AccessorTy > ESIMD_INLINE ESIMD_NODEBUG simd<T, n> cl::sycl::ext::intel::experimental::esimd::block_load (AccessorTy acc, uint32_t offset)
Accessor-based block-load.
Definition at line 191 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::copy_from().
block_load() [2/2]
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG simd<T, n> cl::sycl::ext::intel::experimental::esimd::block_load (const T *const addr)
Flat-address block-load.
Definition at line 172 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2().
block_store() [1/2]
template<typename T , int n, typename AccessorTy > ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::block_store (AccessorTy acc, uint32_t offset, simd< T, n > vals)
Accessor-based block-store.
Definition at line 224 of file esimd_memory.hpp.
block_store() [2/2]
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::block_store (T * p, simd< T, n > vals)
Flat-address block-store.
Definition at line 204 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2().
check_atomic()
template<EsimdAtomicOpType Op, typename T , int N, unsigned NumSrc> constexpr bool cl::sycl::ext::intel::experimental::esimd::detail::check_atomic () constexpr
Check the legality of an atomic call in terms of size and type.
Definition at line 415 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2().
esimd_barrier()
ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_barrier () inline
Generic work-group barrier.
Performs barrier synchronization for all threads within the same thread group. The barrier instruction causes the executing thread to wait until all threads in the same thread group have executed the barrier instruction. Memory ordering is also guaranteed by this instruction. The behavior is undefined if this instruction is executed in divergent control flow.
Definition at line 604 of file esimd_memory.hpp.
References __esimd_barrier(), __esimd_slm_fence(), cl::sycl::ext::intel::experimental::esimd::ESIMD_GLOBAL_COHERENT_FENCE, and cl::sycl::ext::intel::experimental::esimd::ESIMD_LOCAL_BARRIER.
esimd_fence()
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_fence (uint8_t cntl)
esimd_fence sets the memory read/write order.
Template Parameters
cntl is the bitmask composed from enum EsimdFenceMask
Definition at line 592 of file esimd_memory.hpp.
References __esimd_slm_fence().
esimd_get_value()
template<typename AccessorTy > ESIMD_INLINE ESIMD_NODEBUG uint32_t cl::sycl::ext::intel::experimental::esimd::esimd_get_value (AccessorTy acc)
esimd_get_value
Parameters
acc is the SYCL accessor.
Returns
the binding table index value.
Definition at line 827 of file esimd_memory.hpp.
References __esimd_get_value().
flat_atomic() [1/3]
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::check_atomic<Op, T, n, 2>), simd<T, n> > cl::sycl::ext::intel::experimental::esimd::flat_atomic (T * p, simd< unsigned, n > offset, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
Flat-address atomic, two source operands.
Definition at line 557 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
flat_atomic() [2/3]
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::check_atomic<Op, T, n, 1>), simd<T, n> > cl::sycl::ext::intel::experimental::esimd::flat_atomic (T * p, simd< unsigned, n > offset, simd< T, n > src0, simd< ushort, n > pred)
Flat-address atomic, one source operand, add/sub/min/max etc.
Definition at line 541 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
flat_atomic() [3/3]
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::check_atomic<Op, T, n, 0>), simd<T, n> > cl::sycl::ext::intel::experimental::esimd::flat_atomic (T * p, simd< unsigned, n > offset, simd< ushort, n > pred)
Flat-address atomic, zero source operand: inc and dec.
Definition at line 527 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
gather() [1/2]
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(sizeof(T) <= 4) && (N == 1 || N == 8 || N == 16) && !std::is_pointer<AccessorTy>::value, simd<T, N> > cl::sycl::ext::intel::experimental::esimd::gather (AccessorTy acc, simd< uint32_t, N > offsets, uint32_t glob_offset = 0)
Accessor-based gather.
Collects elements located at given offsets in an accessor and returns them as a single simd object. An element can be 1, 2 or 4-byte value.
Template Parameters
T is element type; can only be a 1,2,4-byte integer or float.
N is the number of elements.
AccessorTy is sycl::accessor type.
L1H is L1 cache hint.
L3H is L3 cache hint.
Parameters
acc is the accessor to gather from.
offsets is per-element offsets.
glob_offset is offset added to each individual element's offset to compute actual memory access offset for that element.
Definition at line 251 of file esimd_memory.hpp.
References __esimd_surf_read().
gather() [2/2]
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t< ((n == 8 || n == 16 || n == 32) && (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)), simd<T, n * ElemsPerAddr> > cl::sycl::ext::intel::experimental::esimd::gather (T * p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
Flat-address gather.
Definition at line 78 of file esimd_memory.hpp.
References __esimd_rdregion(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
gather4()
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n == 16 || n == 32) && (sizeof(T) == 4), simd<T, n * NumChannels(Mask)> > cl::sycl::ext::intel::experimental::esimd::gather4 (T * p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
Flat-address gather4.
Only allow simd-16 and simd-32.
Definition at line 387 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
media_block_load()
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0> ESIMD_INLINE ESIMD_NODEBUG simd<T, m * n> cl::sycl::ext::intel::experimental::esimd::media_block_load (AccessorTy acc, unsigned x, unsigned y)
Media block load.
Template Parameters
T is the element data type.
m is the height of the 2D block.
n is the width of the 2D block.
AccessorTy is type of the SYCL accessor.
plane is planar surface index.
Parameters
acc is the SYCL accessor.
x is X-coordinate of the left upper rectangle corner in BYTES.
y is Y-coordinate of the left upper rectangle corner in ROWS.
Returns
the linearized 2D block data read from surface.
Definition at line 742 of file esimd_memory.hpp.
media_block_store()
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::media_block_store (AccessorTy acc, unsigned x, unsigned y, simd< T, m *n > vals)
Media block store.
Template Parameters
T is the element data type.
m is the height of the 2D block.
n is the width of the 2D block.
is AccessorTy type of the SYCL accessor.
plane is planar surface index.
Parameters
acc is the SYCL accessor.
x is X-coordinate of the left upper rectangle corner in BYTES.
y is Y-coordinate of the left upper rectangle corner in ROWS.
vals is the linearized 2D block data to be written to surface.
Definition at line 784 of file esimd_memory.hpp.
scalar_load()
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG T cl::sycl::ext::intel::experimental::esimd::scalar_load (AccessorTy acc, uint32_t offset)
Load a scalar value from an accessor.
Definition at line 361 of file esimd_memory.hpp.
scalar_store()
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::scalar_store (AccessorTy acc, uint32_t offset, T val)
Store a scalar value into an accessor.
Definition at line 370 of file esimd_memory.hpp.
scatter() [1/2]
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(sizeof(T) <= 4) && (N == 1 || N == 8 || N == 16) && !std::is_pointer<AccessorTy>::value, void> cl::sycl::ext::intel::experimental::esimd::scatter (AccessorTy acc, simd< T, N > vals, simd< uint32_t, N > offsets, uint32_t glob_offset = 0, simd< uint16_t, N > pred = 1)
Accessor-based scatter.
Writes elements of a simd object into an accessor at given offsets. An element can be 1, 2 or 4-byte value.
Template Parameters
T is element type; can only be a 1,2,4-byte integer or float.
N is the number of elements.
AccessorTy is sycl::accessor type.
L1H is L1 cache hint.
L3H is L3 cache hint.
Parameters
acc is the accessor to scatter to.
vals is values to write.
offsets is per-element offsets.
glob_offset is offset added to each individual element's offset to compute actual memory access offset for that element.
pred is per-element predicates; elements with zero corresponding predicates are not written.
Definition at line 318 of file esimd_memory.hpp.
scatter() [2/2]
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t< ((n == 8 || n == 16 || n == 32) && (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)), void> cl::sycl::ext::intel::experimental::esimd::scatter (T * p, simd< T, n *ElemsPerAddr > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
Flat-address scatter.
Definition at line 127 of file esimd_memory.hpp.
References __esimd_wrregion(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
scatter4()
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n == 16 || n == 32) && (sizeof(T) == 4), void> cl::sycl::ext::intel::experimental::esimd::scatter4 (T * p, simd< T, n *NumChannels(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
Flat-address scatter4.
Definition at line 402 of file esimd_memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().