DPC++ Runtime: Raw send APIs.
Raw send APIs.
DPC++ Explicit SIMD API | DPC++ Explicit SIMD API » Memory access API.
Implements the send instruction to send messages to variaous components of the Intel(R) processor graphics, as defined in the documentation at https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/hardware-specs.html.
Functions
template<uint8_t exec_size, uint8_t sfid, uint8_t num_src0, uint8_t num_src1, uint8_t num_dst, raw_send_eot eot = raw_send_eot::not_eot, raw_send_sendc sendc = raw_send_sendc::not_sendc, typename T1 , int n1, typename T2 , int n2, typename T3 , int n3>
__ESIMD_API sycl::ext::intel::esimd::simd< T1, n1 > sycl::_V1::ext::intel::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msg_dst, sycl::ext::intel::esimd::simd< T2, n2 > msg_src0, sycl::ext::intel::esimd::simd< T3, n3 > msg_src1, uint32_t ex_desc, uint32_t msg_desc, sycl::ext::intel::esimd::simd_mask< exec_size > mask=1)
Raw sends.
template<uint8_t exec_size, uint8_t sfid, uint8_t num_src0, uint8_t num_dst, raw_send_eot eot = raw_send_eot::not_eot, raw_send_sendc sendc = raw_send_sendc::not_sendc, typename T1 , int n1, typename T2 , int n2>
__ESIMD_API sycl::ext::intel::esimd::simd< T1, n1 > sycl::_V1::ext::intel::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msg_dst, sycl::ext::intel::esimd::simd< T2, n2 > msg_src0, uint32_t ex_desc, uint32_t msg_desc, sycl::ext::intel::esimd::simd_mask< exec_size > mask=1)
Raw send.
template<uint8_t exec_size, uint8_t sfid, uint8_t num_src0, uint8_t num_src1, raw_send_eot eot = raw_send_eot::not_eot, raw_send_sendc sendc = raw_send_sendc::not_sendc, typename T1 , int n1, typename T2 , int n2>
__ESIMD_API void sycl::_V1::ext::intel::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msg_src0, sycl::ext::intel::esimd::simd< T2, n2 > msg_src1, uint32_t ex_desc, uint32_t msg_desc, sycl::ext::intel::esimd::simd_mask< exec_size > mask=1)
Raw sends.
template<uint8_t exec_size, uint8_t sfid, uint8_t num_src0, raw_send_eot eot = raw_send_eot::not_eot, raw_send_sendc sendc = raw_send_sendc::not_sendc, typename T1 , int n1>
__ESIMD_API void sycl::_V1::ext::intel::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msg_src0, uint32_t ex_desc, uint32_t msg_desc, sycl::ext::intel::esimd::simd_mask< exec_size > mask=1)
Raw send.
template<typename T1 , int n1, typename T2 , int n2, typename T3 , int n3, int N = 16>
__ESIMD_API sycl::ext::intel::esimd::simd< T1, n1 > sycl::_V1::ext::intel::experimental::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msgDst, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc0, sycl::ext::intel::esimd::simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT=0, uint8_t isSendc=0, sycl::ext::intel::esimd::simd_mask< N > mask=1)
Raw sends.
template<uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, typename T1 , int n1, typename T2 , int n2, typename T3 , int n3>
__ESIMD_API sycl::ext::intel::esimd::simd< T1, n1 > sycl::_V1::ext::intel::experimental::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msgDst, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc0, sycl::ext::intel::esimd::simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, sycl::ext::intel::esimd::simd_mask< execSize > mask=1)
Raw sends.
template<typename T1 , int n1, typename T2 , int n2, int N = 16>
__ESIMD_API sycl::ext::intel::esimd::simd< T1, n1 > sycl::_V1::ext::intel::experimental::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msgDst, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT=0, uint8_t isSendc=0, sycl::ext::intel::esimd::simd_mask< N > mask=1)
Raw send.
template<uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, typename T1 , int n1, typename T2 , int n2>
__ESIMD_API sycl::ext::intel::esimd::simd< T1, n1 > sycl::_V1::ext::intel::experimental::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msgDst, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, sycl::ext::intel::esimd::simd_mask< execSize > mask=1)
Raw send.
template<typename T1 , int n1, typename T2 , int n2, int N = 16>
__ESIMD_API void sycl::_V1::ext::intel::experimental::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msgSrc0, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT=0, uint8_t isSendc=0, sycl::ext::intel::esimd::simd_mask< N > mask=1)
Raw sends.
template<uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT = 0, uint8_t isSendc = 0, typename T1 , int n1, typename T2 , int n2>
__ESIMD_API void sycl::_V1::ext::intel::experimental::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msgSrc0, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, sycl::ext::intel::esimd::simd_mask< execSize > mask=1)
Raw sends.
template<typename T1 , int n1, int N = 16>
__ESIMD_API void sycl::_V1::ext::intel::experimental::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT=0, uint8_t isSendc=0, sycl::ext::intel::esimd::simd_mask< N > mask=1)
Raw send.
template<uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT = 0, uint8_t isSendc = 0, typename T1 , int n1>
__ESIMD_API void sycl::_V1::ext::intel::experimental::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, sycl::ext::intel::esimd::simd_mask< execSize > mask=1)
Raw send.
Detailed Description
Implements the send instruction to send messages to variaous components of the Intel(R) processor graphics, as defined in the documentation at https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/hardware-specs.html.
Function Documentation
raw_send() [1/6]
template<uint8_t exec_size, uint8_t sfid, uint8_t num_src0, uint8_t num_dst, raw_send_eot eot = raw_send_eot::not_eot, raw_send_sendc sendc = raw_send_sendc::not_sendc, typename T1 , int n1, typename T2 , int n2> __ESIMD_API sycl::ext::intel::esimd::simd<T1, n1> sycl::_V1::ext::intel::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msg_dst, sycl::ext::intel::esimd::simd< T2, n2 > msg_src0, uint32_t ex_desc, uint32_t msg_desc, sycl::ext::intel::esimd::simd_mask< exec_size > mask = 1)
Raw send.
This is a low-level API not recommended for general usage.
Template Parameters
exec_size is the execution size.
sfid is the shared function ID.
num_src0 is the number of GRFs for source-0.
num_dst is the number of GRFs for destination.
eot is the flag that indicates whether this is an EOT message (optional - default to off).
sendc is the flag that indicates whether sendc should be used (optional - default to off).
Parameters
msg_dst is the old value of the destination operand.
msg_src0 is the first source operand of send message.
ex_desc is the extended message descriptor.
msg_desc is the message descriptor.
mask is the predicate to specify enabled channels (optional - default to on).
Returns
the vector value read from memory
Definition at line 9682 of file memory.hpp.
References simd_mask< _Tp, _Abi >::data(), sycl::_V1::ext::intel::esimd::eot, and sycl::_V1::ext::intel::esimd::sendc.
raw_send() [2/6]
template<uint8_t exec_size, uint8_t sfid, uint8_t num_src0, raw_send_eot eot = raw_send_eot::not_eot, raw_send_sendc sendc = raw_send_sendc::not_sendc, typename T1 , int n1> __ESIMD_API void sycl::_V1::ext::intel::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msg_src0, uint32_t ex_desc, uint32_t msg_desc, sycl::ext::intel::esimd::simd_mask< exec_size > mask = 1)
Raw send.
Generates a send or sendc instruction for the message gateway. This is a low-level API not recommended for general usage.
Template Parameters
exec_size is the execution size.
sfid is the shared function ID.
num_src0 is the number of GRFs for source-0.
eot is the flag that indicates whether this is an EOT message (optional - default to off).
sendc is the flag that indicates whether sendc should be used (optional - default to off).
Parameters
msg_src0 is the first source operand of send message.
ex_desc is the extended message descriptor.
msg_desc is the message descriptor.
mask is the predicate to specify enabled channels (optional - default to on).
Definition at line 9758 of file memory.hpp.
References simd_mask< _Tp, _Abi >::data(), sycl::_V1::ext::intel::esimd::eot, and sycl::_V1::ext::intel::esimd::sendc.
raw_send() [3/6]
template<uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, typename T1 , int n1, typename T2 , int n2> __ESIMD_API sycl::ext::intel::esimd::simd<T1, n1> sycl::_V1::ext::intel::experimental::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msgDst, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, sycl::ext::intel::esimd::simd_mask< execSize > mask = 1)
Raw send.
Template Parameters
execSize is the execution size.
sfid is the shared function ID.
numSrc0 is the number of GRFs for source-0.
numDst is the number of GRFs for destination.
isEOT is the flag that indicates whether this is an EOT message (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used (optional - default to 0).
Parameters
msgDst is the old value of the destination operand.
msgSrc0 is the first source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
mask is the predicate to specify enabled channels (optional - default to on).
Returns
the vector value read from memory
Definition at line 199 of file memory.hpp.
raw_send() [4/6]
template<typename T1 , int n1, typename T2 , int n2, int N = 16> __ESIMD_API sycl::ext::intel::esimd::simd<T1, n1> sycl::_V1::ext::intel::experimental::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msgDst, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, sycl::ext::intel::esimd::simd_mask< N > mask = 1)
Raw send.
Parameters
msgDst is the old value of the destination operand.
msgSrc0 is the first source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
execSize is the execution size, which must be a compile time constant.
sfid is the shared function ID, which must be a compile time constant.
numSrc0 is the number of GRFs for source-0, which must be a compile time constant.
numDst is the number of GRFs for destination, which must be a compile time constant.
isEOT is the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask is the predicate to specify enabled channels (optional - default to on).
Returns
the vector value read from memory.
Definition at line 160 of file memory.hpp.
raw_send() [5/6]
template<uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT = 0, uint8_t isSendc = 0, typename T1 , int n1> __ESIMD_API void sycl::_V1::ext::intel::experimental::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, sycl::ext::intel::esimd::simd_mask< execSize > mask = 1)
Raw send.
Generates a send or sendc instruction for the message gateway.
Template Parameters
execSize is the execution size.
sfid is the shared function ID.
numSrc0 is the number of GRFs for source-0.
isEOT is the flag that indicates whether this is an EOT message (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used (optional - default to 0).
Parameters
msgSrc0 is the first source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
mask is the predicate to specify enabled channels (optional - default to on).
Definition at line 346 of file memory.hpp.
raw_send() [6/6]
template<typename T1 , int n1, int N = 16> __ESIMD_API void sycl::_V1::ext::intel::experimental::esimd::raw_send (sycl::ext::intel::esimd::simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT = 0, uint8_t isSendc = 0, sycl::ext::intel::esimd::simd_mask< N > mask = 1)
Raw send.
Generates a send or sendc instruction for the message gateway.
Parameters
msgSrc0 is the first source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
execSize is the execution size, which must be a compile time constant.
sfid is the shared function ID, which must be a compile time constant.
numSrc0 is the number of GRFs for source-0, which must be a compile time constant.
isEOT is the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask is the predicate to specify enabled channels (optional - default to on).
Definition at line 315 of file memory.hpp.
raw_sends() [1/6]
template<uint8_t exec_size, uint8_t sfid, uint8_t num_src0, uint8_t num_src1, uint8_t num_dst, raw_send_eot eot = raw_send_eot::not_eot, raw_send_sendc sendc = raw_send_sendc::not_sendc, typename T1 , int n1, typename T2 , int n2, typename T3 , int n3> __ESIMD_API sycl::ext::intel::esimd::simd<T1, n1> sycl::_V1::ext::intel::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msg_dst, sycl::ext::intel::esimd::simd< T2, n2 > msg_src0, sycl::ext::intel::esimd::simd< T3, n3 > msg_src1, uint32_t ex_desc, uint32_t msg_desc, sycl::ext::intel::esimd::simd_mask< exec_size > mask = 1)
Raw sends.
"s" suffix designates "split" variant - i.e. two sources. This is a low-level API not recommended for general usage.
Template Parameters
exec_size is the execution size.
sfid is the shared function ID.
num_src0 is the number of GRFs for source-0.
num_src1 is the number of GRFs for source-1.
num_dst is the number of GRFs for destination.
eot is the flag that indicates whether this is an EOT message (optional - default to off).
sendc is the flag that indicates whether sendc should be used (optional - default to off).
Parameters
msg_dst is the old value of the destination operand.
msg_src0 is the first source operand of send message.
msg_src1 is the second source operand of send message.
ex_desc is the extended message descriptor.
msg_desc is the message descriptor.
mask is the predicate to specify enabled channels (optional - default to on).
Returns
the vector value read from memory.
Definition at line 9638 of file memory.hpp.
References simd_mask< _Tp, _Abi >::data(), sycl::_V1::ext::intel::esimd::eot, and sycl::_V1::ext::intel::esimd::sendc.
raw_sends() [2/6]
template<uint8_t exec_size, uint8_t sfid, uint8_t num_src0, uint8_t num_src1, raw_send_eot eot = raw_send_eot::not_eot, raw_send_sendc sendc = raw_send_sendc::not_sendc, typename T1 , int n1, typename T2 , int n2> __ESIMD_API void sycl::_V1::ext::intel::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msg_src0, sycl::ext::intel::esimd::simd< T2, n2 > msg_src1, uint32_t ex_desc, uint32_t msg_desc, sycl::ext::intel::esimd::simd_mask< exec_size > mask = 1)
Raw sends.
"s" suffix designates "split" variant - i.e. two sources. This is a low-level API not recommended for general usage.
Template Parameters
exec_size is the execution size.
sfid is the shared function ID.
num_src0 is the number of GRFs for source-0.
num_src1 is the number of GRFs for source-1.
eot is the flag that indicates whether this is an EOT message (optional - default to off).
sendc is the flag that indicates whether sendc should be used (optional - default to off).
Parameters
msg_src0 is the first source operand of send message.
msg_src1 is the second source operand of send message.
ex_desc is the extended message descriptor.
msg_desc is the message descriptor.
mask is the predicate to specify enabled channels (optional - default to on).
Definition at line 9721 of file memory.hpp.
References simd_mask< _Tp, _Abi >::data(), sycl::_V1::ext::intel::esimd::eot, and sycl::_V1::ext::intel::esimd::sendc.
raw_sends() [3/6]
template<uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, typename T1 , int n1, typename T2 , int n2, typename T3 , int n3> __ESIMD_API sycl::ext::intel::esimd::simd<T1, n1> sycl::_V1::ext::intel::experimental::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msgDst, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc0, sycl::ext::intel::esimd::simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, sycl::ext::intel::esimd::simd_mask< execSize > mask = 1)
Raw sends.
"s" suffix designates "split" variant - i.e. two sources.
Template Parameters
execSize is the execution size.
sfid is the shared function ID.
numSrc0 is the number of GRFs for source-0.
numSrc1 is the number of GRFs for source-1.
numDst is the number of GRFs for destination.
isEOT is the flag that indicates whether this is an EOT message (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used (optional - default to 0).
Parameters
msgDst is the old value of the destination operand.
msgSrc0 is the first source operand of send message.
msgSrc1 is the second source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
mask is the predicate to specify enabled channels (optional - default to on).
Returns
the vector value read from memory.
Definition at line 115 of file memory.hpp.
raw_sends() [4/6]
template<typename T1 , int n1, typename T2 , int n2, typename T3 , int n3, int N = 16> __ESIMD_API sycl::ext::intel::esimd::simd<T1, n1> sycl::_V1::ext::intel::experimental::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msgDst, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc0, sycl::ext::intel::esimd::simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, sycl::ext::intel::esimd::simd_mask< N > mask = 1)
Raw sends.
"s" suffix designates "split" variant - i.e. two sources.
Parameters
msgDst is the old value of the destination operand.
msgSrc0 is the first source operand of send message.
msgSrc1 is the second source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
execSize is the execution size, which must be a compile time constant.
sfid is the shared function ID, which must be a compile time constant.
numSrc0 is the number of GRFs for source-0, which must be a compile time constant.
numSrc1 is the number of GRFs for source-1, which must be a compile constant.
numDst is the number of GRFs for destination, which must be a compile time constant.
isEOT is the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask is the predicate to specify enabled channels (optional - default to on).
Returns
the vector value read from memory.
Definition at line 70 of file memory.hpp.
raw_sends() [5/6]
template<uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT = 0, uint8_t isSendc = 0, typename T1 , int n1, typename T2 , int n2> __ESIMD_API void sycl::_V1::ext::intel::experimental::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msgSrc0, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, sycl::ext::intel::esimd::simd_mask< execSize > mask = 1)
Raw sends.
"s" suffix designates "split" variant - i.e. two sources.
Template Parameters
execSize is the execution size.
sfid is the shared function ID.
numSrc0 is the number of GRFs for source-0.
numSrc1 is the number of GRFs for source-1.
isEOT is the flag that indicates whether this is an EOT message (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used (optional - default to 0).
Parameters
msgSrc0 is the first source operand of send message.
msgSrc1 is the second source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
mask is the predicate to specify enabled channels (optional - default to on).
Definition at line 278 of file memory.hpp.
raw_sends() [6/6]
template<typename T1 , int n1, typename T2 , int n2, int N = 16> __ESIMD_API void sycl::_V1::ext::intel::experimental::esimd::raw_sends (sycl::ext::intel::esimd::simd< T1, n1 > msgSrc0, sycl::ext::intel::esimd::simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT = 0, uint8_t isSendc = 0, sycl::ext::intel::esimd::simd_mask< N > mask = 1)
Raw sends.
"s" suffix designates "split" variant - i.e. two sources.
Parameters
msgSrc0 is the first source operand of send message.
msgSrc1 is the second source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
execSize is the execution size, which must be a compile time constant.
sfid is the shared function ID, which must be a compile time constant.
numSrc0 is the number of GRFs for source-0, which must be a compile time constant.
numSrc1 is the number of GRFs for source-1, which must be a compile time constant.
isEOT is the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask is the predicate to specify enabled channels (optional - default to on).
Definition at line 239 of file memory.hpp.