DPC++ Runtime: LSC memory access APIs.
LSC memory access APIs.
DPC++ Explicit SIMD API » Memory access API.
Namespaces
cl::__ESIMD_ENS::detail
Functions
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, int N>
__ESIMD_API __ESIMD_NS::simd< T, N *NElts > cl::__ESIMD_ENS::lsc_slm_gather (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred=1)
SLM gather.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size>
__ESIMD_API __ESIMD_NS::simd< T, NElts > cl::__ESIMD_ENS::lsc_slm_block_load (uint32_t offset)
Transposed SLM gather with 1 channel.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value, __ESIMD_NS::simd< T, N *NElts > > cl::__ESIMD_ENS::lsc_gather (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred=1)
Accessor-based gather.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value, __ESIMD_NS::simd< T, NElts > > cl::__ESIMD_ENS::lsc_block_load (AccessorTy acc, uint32_t offset)
Accessor-based transposed gather with 1 channel.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N>
__ESIMD_API __ESIMD_NS::simd< T, N *NElts > cl::__ESIMD_ENS::lsc_gather (const T *p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred=1)
USM pointer gather.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none>
__ESIMD_API __ESIMD_NS::simd< T, NElts > cl::__ESIMD_ENS::lsc_block_load (const T *p)
USM pointer transposed gather with 1 channel.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value > cl::__ESIMD_ENS::lsc_prefetch (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred=1)
Accessor-based prefetch gather.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value > cl::__ESIMD_ENS::lsc_prefetch (AccessorTy acc, uint32_t offset)
Accessor-based transposed prefetch gather with 1 channel.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N>
__ESIMD_API void cl::__ESIMD_ENS::lsc_prefetch (const T *p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred=1)
USM pointer prefetch gather.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none>
__ESIMD_API void cl::__ESIMD_ENS::lsc_prefetch (const T *p)
USM pointer prefetch transposed gather with 1 channel.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, int N>
__ESIMD_API void cl::__ESIMD_ENS::lsc_slm_scatter (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N *NElts > vals, __ESIMD_NS::simd_mask< N > pred=1)
SLM scatter.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size>
__ESIMD_API void cl::__ESIMD_ENS::lsc_slm_block_store (uint32_t offset, __ESIMD_NS::simd< T, NElts > vals)
Transposed SLM scatter with 1 channel.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value > cl::__ESIMD_ENS::lsc_scatter (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N *NElts > vals, __ESIMD_NS::simd_mask< N > pred=1)
Accessor-based scatter.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value > cl::__ESIMD_ENS::lsc_block_store (AccessorTy acc, uint32_t offset, __ESIMD_NS::simd< T, NElts > vals)
Accessor-based transposed scatter with 1 channel.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N>
__ESIMD_API void cl::__ESIMD_ENS::lsc_scatter (T *p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N *NElts > vals, __ESIMD_NS::simd_mask< N > pred=1)
USM pointer scatter.
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none>
__ESIMD_API void cl::__ESIMD_ENS::lsc_block_store (T *p, __ESIMD_NS::simd< T, NElts > vals)
USM pointer transposed scatter with 1 channel.
template<typename T , int BlockWidth, int BlockHeight = 1, int NBlocks = 1, bool Transposed = false, bool Transformed = false, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N = detail::get_lsc_block_2d_data_size< T, NBlocks, BlockHeight, BlockWidth, Transposed, Transformed>()>
__ESIMD_API __ESIMD_NS::simd< T, N > cl::__ESIMD_ENS::lsc_load2d (const T *Ptr, unsigned SurfaceWidth, unsigned SurfaceHeight, unsigned SurfacePitch, int X, int Y)
2D USM pointer block load.
template<typename T , int BlockWidth, int BlockHeight = 1, int NBlocks = 1, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N = detail::get_lsc_block_2d_data_size< T, NBlocks, BlockHeight, BlockWidth, false, false>()>
__ESIMD_API void cl::__ESIMD_ENS::lsc_prefetch2d (const T *Ptr, unsigned SurfaceWidth, unsigned SurfaceHeight, unsigned SurfacePitch, int X, int Y)
2D USM pointer block prefetch.
template<typename T , int BlockWidth, int BlockHeight = 1, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N = detail::get_lsc_block_2d_data_size< T, 1u, BlockHeight, BlockWidth, false, false>()>
__ESIMD_API void cl::__ESIMD_ENS::lsc_store2d (T *Ptr, unsigned SurfaceWidth, unsigned SurfaceHeight, unsigned SurfacePitch, int X, int Y, __ESIMD_NS::simd< T, N > Vals)
2D USM pointer block store.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size>
__ESIMD_API __ESIMD_NS::simd< T, N > cl::__ESIMD_ENS::lsc_slm_atomic_update (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred)
SLM atomic.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size>
__ESIMD_API __ESIMD_NS::simd< T, N > cl::__ESIMD_ENS::lsc_slm_atomic_update (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd_mask< N > pred)
SLM atomic.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size>
__ESIMD_API __ESIMD_NS::simd< T, N > cl::__ESIMD_ENS::lsc_slm_atomic_update (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd< T, N > src1, __ESIMD_NS::simd_mask< N > pred)
SLM atomic.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value, __ESIMD_NS::simd< T, N > > cl::__ESIMD_ENS::lsc_atomic_update (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred)
Accessor-based atomic.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value, __ESIMD_NS::simd< T, N > > cl::__ESIMD_ENS::lsc_atomic_update (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd_mask< N > pred)
Accessor-based atomic.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy >
__ESIMD_API std::enable_if_t<!std::is_pointer< AccessorTy >::value, __ESIMD_NS::simd< T, N > > cl::__ESIMD_ENS::lsc_atomic_update (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd< T, N > src1, __ESIMD_NS::simd_mask< N > pred)
Accessor-based atomic.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none>
__ESIMD_API __ESIMD_NS::simd< T, N > cl::__ESIMD_ENS::lsc_atomic_update (T *p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred)
USM pointer atomic.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none>
__ESIMD_API __ESIMD_NS::simd< T, N > cl::__ESIMD_ENS::lsc_atomic_update (T *p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd_mask< N > pred)
USM pointer atomic.
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none>
__ESIMD_API __ESIMD_NS::simd< T, N > cl::__ESIMD_ENS::lsc_atomic_update (T *p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd< T, N > src1, __ESIMD_NS::simd_mask< N > pred)
USM pointer atomic.
template<lsc_memory_kind Kind = lsc_memory_kind::untyped_global, lsc_fence_op FenceOp = lsc_fence_op::none, lsc_scope Scope = lsc_scope::group, int N = 16>
__ESIMD_API void cl::__ESIMD_ENS::lsc_fence (__ESIMD_NS::simd_mask< N > pred=1)
Memory fence.
Detailed Description
Function Documentation
lsc_atomic_update() [1/6]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value, __ESIMD_NS::simd<T, N> > cl::__ESIMD_ENS::lsc_atomic_update (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd< T, N > src1, __ESIMD_NS::simd_mask< N > pred)
Accessor-based atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.ugm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offsets is the zero-based offsets.
src0 is the first atomic operand.
src1 is the second atomic operand.
pred is predicates.
Definition at line 1293 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE, and cl::__ESIMD_ENS::detail::expand_data_size().
lsc_atomic_update() [2/6]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value, __ESIMD_NS::simd<T, N> > cl::__ESIMD_ENS::lsc_atomic_update (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd_mask< N > pred)
Accessor-based atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.ugm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offsets is the zero-based offsets.
src0 is the first atomic operand.
pred is predicates.
Definition at line 1247 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE, and cl::__ESIMD_ENS::detail::expand_data_size().
lsc_atomic_update() [3/6]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value, __ESIMD_NS::simd<T, N> > cl::__ESIMD_ENS::lsc_atomic_update (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred)
Accessor-based atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.ugm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offsets is the zero-based offsets.
pred is predicates.
Definition at line 1202 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE, and cl::__ESIMD_ENS::detail::expand_data_size().
lsc_atomic_update() [4/6]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none> __ESIMD_API __ESIMD_NS::simd<T, N> cl::__ESIMD_ENS::lsc_atomic_update (T * p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd< T, N > src1, __ESIMD_NS::simd_mask< N > pred)
USM pointer atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.ugm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
Parameters
p is the base pointer.
offsets is the zero-based offsets.
src0 is the first atomic operand.
src1 is the second atomic operand.
pred is predicates.
Definition at line 1422 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_atomic_update() [5/6]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none> __ESIMD_API __ESIMD_NS::simd<T, N> cl::__ESIMD_ENS::lsc_atomic_update (T * p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd_mask< N > pred)
USM pointer atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.ugm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
Parameters
p is the base pointer.
offsets is the zero-based offsets.
src0 is the first atomic operand.
pred is predicates.
Definition at line 1378 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_atomic_update() [6/6]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none> __ESIMD_API __ESIMD_NS::simd<T, N> cl::__ESIMD_ENS::lsc_atomic_update (T * p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred)
USM pointer atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.ugm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
Parameters
p is the base pointer.
offsets is the zero-based offsets.
pred is predicates.
Definition at line 1335 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_block_load() [1/2]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value, __ESIMD_NS::simd<T, NElts> > cl::__ESIMD_ENS::lsc_block_load (AccessorTy acc, uint32_t offset)
Accessor-based transposed gather with 1 channel.
Supported platforms: DG2, PVC VISA instruction: lsc_load.ugm
Collects elements located at surface and returns them as a single simd object.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offset is the zero-based offset in bytes.
Returns
is a vector of type T and size NElts
Definition at line 412 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE.
lsc_block_load() [2/2]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none> __ESIMD_API __ESIMD_NS::simd<T, NElts> cl::__ESIMD_ENS::lsc_block_load (const T * p)
USM pointer transposed gather with 1 channel.
Supported platforms: DG2, PVC VISA instruction: lsc_load.ugm
Collects elements located at specified address and returns them as a single simd object.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
Parameters
p is the base pointer.
Returns
is a vector of type T and size NElts
Definition at line 495 of file memory.hpp.
lsc_block_store() [1/2]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value> cl::__ESIMD_ENS::lsc_block_store (AccessorTy acc, uint32_t offset, __ESIMD_NS::simd< T, NElts > vals)
Accessor-based transposed scatter with 1 channel.
Supported platforms: DG2, PVC VISA instruction: lsc_store.ugm
Scatters elements to surface.
Template Parameters
T is element type.
NElts is the number of elements to store per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offset is the zero-based offset in bytes.
vals is values to store.
Definition at line 809 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE.
lsc_block_store() [2/2]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none> __ESIMD_API void cl::__ESIMD_ENS::lsc_block_store (T * p, __ESIMD_NS::simd< T, NElts > vals)
USM pointer transposed scatter with 1 channel.
Supported platforms: DG2, PVC VISA instruction: lsc_store.ugm
Scatters elements to specific address.
Template Parameters
T is element type.
NElts is the number of elements to store per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
Parameters
p is the base pointer.
vals is values to store.
Definition at line 892 of file memory.hpp.
lsc_fence()
template<lsc_memory_kind Kind = lsc_memory_kind::untyped_global, lsc_fence_op FenceOp = lsc_fence_op::none, lsc_scope Scope = lsc_scope::group, int N = 16> __ESIMD_API void cl::__ESIMD_ENS::lsc_fence (__ESIMD_NS::simd_mask< N > pred = 1)
Memory fence.
Supported platforms: DG2, PVC
Template Parameters
Kind is the Sfid shaded function.
FenceOp is the fence operation.
Scope is the operation scope.
N is the number of channels (platform dependent).
Parameters
pred is predicates.
Definition at line 1458 of file memory.hpp.
lsc_gather() [1/2]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value, __ESIMD_NS::simd<T, N * NElts> > cl::__ESIMD_ENS::lsc_gather (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred = 1)
Accessor-based gather.
Supported platforms: DG2, PVC VISA instruction: lsc_load.ugm
Collects elements located at surface and returns them as a single simd object.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the number of channels (platform dependent).
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offsets is the zero-based offsets in bytes.
pred is predicates.
Returns
is a vector of type T and size N * NElts
Definition at line 369 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE, and cl::__ESIMD_ENS::detail::expand_data_size().
lsc_gather() [2/2]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N> __ESIMD_API __ESIMD_NS::simd<T, N * NElts> cl::__ESIMD_ENS::lsc_gather (const T * p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred = 1)
USM pointer gather.
Supported platforms: DG2, PVC VISA instruction: lsc_load.ugm
Collects elements located at specified address and returns them as a single simd object.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the number of channels (platform dependent).
Parameters
p is the base pointer.
offsets is the zero-based offsets in bytes.
pred is predicates.
Returns
is a vector of type T and size N * NElts
Definition at line 455 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_load2d()
template<typename T , int BlockWidth, int BlockHeight = 1, int NBlocks = 1, bool Transposed = false, bool Transformed = false, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N = detail::get_lsc_block_2d_data_size< T, NBlocks, BlockHeight, BlockWidth, Transposed, Transformed>()> __ESIMD_API __ESIMD_NS::simd<T, N> cl::__ESIMD_ENS::lsc_load2d (const T * Ptr, unsigned SurfaceWidth, unsigned SurfaceHeight, unsigned SurfacePitch, int X, int Y)
2D USM pointer block load.
Supported platforms: PVC VISA instruction: lsc_load_block2d.ugm
Collects elements located at specified address and returns them as a single simd object.
Template Parameters
T is element type.
BlockWidth is the block width in number of elements.
BlockHeight is the block height in number of elements.
NBlocks is the number of blocks.
Transposed is the transposed version or not.
Transformed is apply VNNI transform or not.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the data size
Parameters
Ptr is the surface base address for this operation.
SurfaceWidth is the surface width minus 1 in bytes
SurfaceHeight is the surface height minus 1 in rows
SurfacePitch is the surface pitch minus 1 in bytes
X is zero based X-coordinate of the left upper rectangle corner in number of elements.
Y is zero based Y-coordinate of the left upper rectangle corner in rows.
Returns
is a vector of type T and size N, where N is BlockWidth * BlockHeight * NBlocks, if transformed; otherwise, N = roundUpNextMultiple(BlockHeight, 4 / sizeof(T)) * getNextPowerOf2(BlockWidth) * NBlocks
Definition at line 948 of file memory.hpp.
lsc_prefetch() [1/4]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value> cl::__ESIMD_ENS::lsc_prefetch (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred = 1)
Accessor-based prefetch gather.
Supported platforms: DG2, PVC VISA instruction: lsc_load.ugm
Prefetches elements located at surface.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the number of channels (platform dependent).
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offsets is the zero-based offsets in bytes.
pred is predicates.
Definition at line 537 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE, and cl::__ESIMD_ENS::detail::expand_data_size().
lsc_prefetch() [2/4]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value> cl::__ESIMD_ENS::lsc_prefetch (AccessorTy acc, uint32_t offset)
Accessor-based transposed prefetch gather with 1 channel.
Supported platforms: DG2, PVC VISA instruction: lsc_load.ugm
Prefetches elements located at surface.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offset is the zero-based offset in bytes.
Definition at line 575 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE.
lsc_prefetch() [3/4]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none> __ESIMD_API void cl::__ESIMD_ENS::lsc_prefetch (const T * p)
USM pointer prefetch transposed gather with 1 channel.
Supported platforms: DG2, PVC VISA instruction: lsc_load.ugm
Prefetches elements located at specified address.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
Parameters
p is the base pointer.
Definition at line 652 of file memory.hpp.
lsc_prefetch() [4/4]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N> __ESIMD_API void cl::__ESIMD_ENS::lsc_prefetch (const T * p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred = 1)
USM pointer prefetch gather.
Supported platforms: DG2, PVC VISA instruction: lsc_load.ugm
Prefetches elements located at specified address.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the number of channels (platform dependent).
Parameters
p is the base pointer.
offsets is the zero-based offsets in bytes.
pred is predicates.
Definition at line 616 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_prefetch2d()
template<typename T , int BlockWidth, int BlockHeight = 1, int NBlocks = 1, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N = detail::get_lsc_block_2d_data_size< T, NBlocks, BlockHeight, BlockWidth, false, false>()> __ESIMD_API void cl::__ESIMD_ENS::lsc_prefetch2d (const T * Ptr, unsigned SurfaceWidth, unsigned SurfaceHeight, unsigned SurfacePitch, int X, int Y)
2D USM pointer block prefetch.
Supported platforms: PVC VISA instruction: lsc_load_block2d.ugm
Prefetches elements located at specified address.
Template Parameters
T is element type.
BlockWidth is the block width in number of elements.
BlockHeight is the block height in number of elements.
NBlocks is the number of blocks.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the data size
Parameters
Ptr is the surface base address for this operation.
SurfaceWidth is the surface width minus 1 in bytes
SurfaceHeight is the surface height minus 1 in rows
SurfacePitch is the surface pitch minus 1 in bytes
X is zero based X-coordinate of the left upper rectangle corner in number of elements.
Y is zero based Y-coordinate of the left upper rectangle corner in rows.
Definition at line 1010 of file memory.hpp.
lsc_scatter() [1/2]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N, typename AccessorTy > __ESIMD_API std::enable_if_t<!std::is_pointer<AccessorTy>::value> cl::__ESIMD_ENS::lsc_scatter (AccessorTy acc, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N *NElts > vals, __ESIMD_NS::simd_mask< N > pred = 1)
Accessor-based scatter.
Supported platforms: DG2, PVC VISA instruction: lsc_store.ugm
Scatters elements to surface.
Template Parameters
T is element type.
NElts is the number of elements to store per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the number of channels (platform dependent).
AccessorTy is the sycl::accessor type.
Parameters
acc is the SYCL accessor.
offsets is the zero-based offsets in bytes.
vals is values to store.
pred is predicates.
Definition at line 766 of file memory.hpp.
References __ESIMD_GET_SURF_HANDLE, and cl::__ESIMD_ENS::detail::expand_data_size().
lsc_scatter() [2/2]
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N> __ESIMD_API void cl::__ESIMD_ENS::lsc_scatter (T * p, __ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N *NElts > vals, __ESIMD_NS::simd_mask< N > pred = 1)
USM pointer scatter.
Supported platforms: DG2, PVC VISA instruction: lsc_store.ugm
Scatters elements to specific address.
Template Parameters
T is element type.
NElts is the number of elements to store per address.
DS is the data size.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the number of channels (platform dependent).
Parameters
p is the base pointer.
offsets is the zero-based offsets in bytes.
vals is values to store.
pred is predicates.
Definition at line 852 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_slm_atomic_update() [1/3]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size> __ESIMD_API __ESIMD_NS::simd<T, N> cl::__ESIMD_ENS::lsc_slm_atomic_update (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd< T, N > src1, __ESIMD_NS::simd_mask< N > pred)
SLM atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.slm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
Parameters
offsets is the zero-based offsets.
src0 is the first atomic operand.
src1 is the second atomic operand.
pred is predicates.
Definition at line 1158 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_slm_atomic_update() [2/3]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size> __ESIMD_API __ESIMD_NS::simd<T, N> cl::__ESIMD_ENS::lsc_slm_atomic_update (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N > src0, __ESIMD_NS::simd_mask< N > pred)
SLM atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.slm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
Parameters
offsets is the zero-based offsets.
src0 is the first atomic operand.
pred is predicates.
Definition at line 1119 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_slm_atomic_update() [3/3]
template<__ESIMD_NS::atomic_op Op, typename T , int N, lsc_data_size DS = lsc_data_size::default_size> __ESIMD_API __ESIMD_NS::simd<T, N> cl::__ESIMD_ENS::lsc_slm_atomic_update (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred)
SLM atomic.
Supported platforms: DG2, PVC VISA instruction: lsc_atomic_<OP>.slm
Template Parameters
Op is operation type.
T is element type.
N is the number of channels (platform dependent).
DS is the data size.
Parameters
offsets is the zero-based offsets.
pred is predicates.
Definition at line 1083 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_slm_block_load()
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size> __ESIMD_API __ESIMD_NS::simd<T, NElts> cl::__ESIMD_ENS::lsc_slm_block_load (uint32_t offset)
Transposed SLM gather with 1 channel.
Supported platforms: DG2, PVC VISA instruction: lsc_load.slm
Collects elements located at slm and returns them as a single simd object.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
Parameters
offset is the zero-based offset for SLM buffer in bytes.
Returns
is a vector of type T and size NElts
Definition at line 325 of file memory.hpp.
lsc_slm_block_store()
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size> __ESIMD_API void cl::__ESIMD_ENS::lsc_slm_block_store (uint32_t offset, __ESIMD_NS::simd< T, NElts > vals)
Transposed SLM scatter with 1 channel.
Supported platforms: DG2, PVC VISA instruction: lsc_store.slm
Scatters elements located to slm.
Template Parameters
T is element type.
NElts is the number of elements to store per address.
DS is the data size.
Parameters
offset is the zero-based offset for SLM buffer in bytes.
vals is values to store.
Definition at line 723 of file memory.hpp.
lsc_slm_gather()
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, int N> __ESIMD_API __ESIMD_NS::simd<T, N * NElts> cl::__ESIMD_ENS::lsc_slm_gather (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd_mask< N > pred = 1)
SLM gather.
Supported platforms: DG2, PVC VISA instruction: lsc_load.slm
Collects elements located at slm and returns them as a single simd object.
Template Parameters
T is element type.
NElts is the number of elements to load per address.
DS is the data size.
N is the number of channels (platform dependent).
Parameters
offsets is the zero-based offsets for SLM buffer in bytes.
pred is predicates.
Returns
is a vector of type T and size N * NElts
Definition at line 291 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_slm_scatter()
template<typename T , uint8_t NElts = 1, lsc_data_size DS = lsc_data_size::default_size, int N> __ESIMD_API void cl::__ESIMD_ENS::lsc_slm_scatter (__ESIMD_NS::simd< uint32_t, N > offsets, __ESIMD_NS::simd< T, N *NElts > vals, __ESIMD_NS::simd_mask< N > pred = 1)
SLM scatter.
Supported platforms: DG2, PVC VISA instruction: lsc_store.slm
Scatters elements located to slm.
Template Parameters
T is element type.
NElts is the number of elements to store per address.
DS is the data size.
N is the number of channels (platform dependent).
Parameters
offsets is the zero-based offsets for SLM buffer in bytes.
vals is values to store.
pred is predicates.
Definition at line 689 of file memory.hpp.
References cl::__ESIMD_ENS::detail::expand_data_size().
lsc_store2d()
template<typename T , int BlockWidth, int BlockHeight = 1, cache_hint L1H = cache_hint::none, cache_hint L3H = cache_hint::none, int N = detail::get_lsc_block_2d_data_size< T, 1u, BlockHeight, BlockWidth, false, false>()> __ESIMD_API void cl::__ESIMD_ENS::lsc_store2d (T * Ptr, unsigned SurfaceWidth, unsigned SurfaceHeight, unsigned SurfacePitch, int X, int Y, __ESIMD_NS::simd< T, N > Vals)
2D USM pointer block store.
Supported platforms: PVC VISA instruction: lsc_store_block2d.ugm
Stores elements at specified address.
Template Parameters
T is element type.
BlockWidth is the block width in number of elements.
BlockHeight is the block height in number of elements.
L1H is L1 cache hint.
L3H is L3 cache hint.
N is the data size
Parameters
Ptr is the surface base address for this operation.
SurfaceWidth is the surface width minus 1 in bytes
SurfaceHeight is the surface height minus 1 in rows
SurfacePitch is the surface pitch minus 1 in bytes
X is zero based X-coordinate of the left upper rectangle corner in number of elements.
Y is zero based Y-coordinate of the left upper rectangle corner in rows.
Vals is a vector to store of type T and size N, where N = roundUpNextMultiple(BlockHeight, 4 / sizeof(T)) * getNextPowerOf2(BlockWidth) * NBlocks
Definition at line 1053 of file memory.hpp.