DPC++ Runtime: Raw send APIs
Raw send APIs
DPC++ Explicit SIMD API
APIs below are used to implement the send messages on Intel(R) processor graphics, as defined in the documentation at https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-icllp-vol02a-commandreference-instructions_2.pdf.
Functions
template<typename T1 , int n1, typename T2 , int n2, typename T3 , int n3, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG simd< T1, n1 > cl::sycl::ext::intel::experimental::esimd::esimd_raw_sends_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw sends load.
template<typename T1 , int n1, typename T2 , int n2, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG simd< T1, n1 > cl::sycl::ext::intel::experimental::esimd::esimd_raw_send_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw send load.
template<typename T1 , int n1, typename T2 , int n2, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_raw_sends_store (simd< T1, n1 > msgSrc0, simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw sends store.
template<typename T1 , int n1, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_raw_send_store (simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw send store.
Detailed Description
APIs below are used to implement the send messages on Intel(R) processor graphics, as defined in the documentation at https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-icllp-vol02a-commandreference-instructions_2.pdf.
Function Documentation
esimd_raw_send_load()
template<typename T1 , int n1, typename T2 , int n2, int N = 16> ESIMD_INLINE ESIMD_NODEBUG simd<T1, n1> cl::sycl::ext::intel::experimental::esimd::esimd_raw_send_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, simd< uint16_t, N > mask = 1)
Raw send load.
Parameters
msgDst is the old value of the destination operand.
msgSrc0 is the first source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
execSize is the execution size, which must be a compile time constant.
sfid is the shared function ID, which must be a compile time constant.
numSrc0 is the number of GRFs for source-0, which must be a compile time constant.
numDst is the number of GRFs for destination, which must be a compile time constant.
isEOT is the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask is the predicate to specify enabled channels (optional - default to on).
Returns
the vector value read from memory.
Definition at line 902 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_raw_send_store()
template<typename T1 , int n1, int N = 16> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_raw_send_store (simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT = 0, uint8_t isSendc = 0, simd< uint16_t, N > mask = 1)
Raw send store.
Parameters
msgSrc0 is the first source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
execSize is the execution size, which must be a compile time constant.
sfid is the shared function ID, which must be a compile time constant.
numSrc0 is the number of GRFs for source-0, which must be a compile time constant.
isEOT is the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask is the predicate to specify enabled channels (optional - default to on).
Definition at line 974 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_raw_sends_load()
template<typename T1 , int n1, typename T2 , int n2, typename T3 , int n3, int N = 16> ESIMD_INLINE ESIMD_NODEBUG simd<T1, n1> cl::sycl::ext::intel::experimental::esimd::esimd_raw_sends_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, simd< uint16_t, N > mask = 1)
Raw sends load.
Parameters
msgDst is the old value of the destination operand.
msgSrc0 is the first source operand of send message.
msgSrc1 is the second source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
execSize is the execution size, which must be a compile time constant.
sfid is the shared function ID, which must be a compile time constant.
numSrc0 is the number of GRFs for source-0, which must be a compile time constant.
numSrc1 is the number of GRFs for source-1, which must be a compile constant.
numDst is the number of GRFs for destination, which must be a compile time constant.
isEOT is the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask is the predicate to specify enabled channels (optional - default to on).
Returns
the vector value read from memory.
Definition at line 861 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_raw_sends_store()
template<typename T1 , int n1, typename T2 , int n2, int N = 16> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_raw_sends_store (simd< T1, n1 > msgSrc0, simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT = 0, uint8_t isSendc = 0, simd< uint16_t, N > mask = 1)
Raw sends store.
Parameters
msgSrc0 is the first source operand of send message.
msgSrc1 is the second source operand of send message.
exDesc is the extended message descriptor.
msgDesc is the message descriptor.
execSize is the execution size, which must be a compile time constant.
sfid is the shared function ID, which must be a compile time constant.
numSrc0 is the number of GRFs for source-0, which must be a compile time constant.
numSrc1 is the number of GRFs for source-1, which must be a compile time constant.
isEOT is the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc is the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask is the predicate to specify enabled channels (optional - default to on).
Definition at line 939 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().