DPC++ Runtime: SLM functions
SLM functions
DPC++ Explicit SIMD API
Functions
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void cl::sycl::ext::intel::experimental::esimd::slm_init (uint32_t size)
Declare per-work-group slm size.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==16||n==32), simd< T, n > > cl::sycl::ext::intel::experimental::esimd::slm_load (simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM gather.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==16||n==32), void > cl::sycl::ext::intel::experimental::esimd::slm_store (simd< T, n > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM scatter.
template<typename T , int n, rgba_channel_mask Mask>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==8||n==16||n==32) &&(sizeof(T)==4), simd< T, n *get_num_channels_enabled(Mask)> > cl::sycl::ext::intel::experimental::esimd::slm_load4 (simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM gather4.
template<typename T , int n, rgba_channel_mask Mask>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==8||n==16||n==32) &&(sizeof(T)==4), void > cl::sycl::ext::intel::experimental::esimd::slm_store4 (simd< T, n *get_num_channels_enabled(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM scatter4.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > cl::sycl::ext::intel::experimental::esimd::slm_block_load (uint32_t offset)
SLM block-load.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::slm_block_store (uint32_t offset, simd< T, n > vals)
SLM block-store.
template<atomic_op Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 0 >), simd< T, n > > cl::sycl::ext::intel::experimental::esimd::slm_atomic (simd< uint32_t, n > offsets, simd< ushort, n > pred)
SLM atomic, zero source operand: inc and dec.
template<atomic_op Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 1 >), simd< T, n > > cl::sycl::ext::intel::experimental::esimd::slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< ushort, n > pred)
SLM atomic, one source operand, add/sub/min/max etc.
template<atomic_op Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 2 >), simd< T, n > > cl::sycl::ext::intel::experimental::esimd::slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
SLM atomic, two source operands.
Detailed Description
Function Documentation
slm_atomic() [1/3]
template<atomic_op Op, typename T , int n> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::check_atomic<Op, T, n, 2>), simd<T, n> > cl::sycl::ext::intel::experimental::esimd::slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
SLM atomic, two source operands.
Definition at line 710 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
slm_atomic() [2/3]
template<atomic_op Op, typename T , int n> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::check_atomic<Op, T, n, 1>), simd<T, n> > cl::sycl::ext::intel::experimental::esimd::slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< ushort, n > pred)
SLM atomic, one source operand, add/sub/min/max etc.
Definition at line 699 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
slm_atomic() [3/3]
template<atomic_op Op, typename T , int n> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::check_atomic<Op, T, n, 0>), simd<T, n> > cl::sycl::ext::intel::experimental::esimd::slm_atomic (simd< uint32_t, n > offsets, simd< ushort, n > pred)
SLM atomic, zero source operand: inc and dec.
Definition at line 690 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
slm_block_load()
template<typename T , int n> ESIMD_INLINE ESIMD_NODEBUG simd<T, n> cl::sycl::ext::intel::experimental::esimd::slm_block_load (uint32_t offset)
SLM block-load.
Definition at line 653 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2().
slm_block_store()
template<typename T , int n> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::slm_block_store (uint32_t offset, simd< T, n > vals)
SLM block-store.
Definition at line 669 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data(), and cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2().
slm_init()
void cl::sycl::ext::intel::experimental::esimd::slm_init (uint32_t size) inline
Declare per-work-group slm size.
Definition at line 806 of file memory.hpp.
slm_load()
template<typename T , int n> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n == 16 || n == 32), simd<T, n> > cl::sycl::ext::intel::experimental::esimd::slm_load (simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
SLM gather.
Only allow simd-16 and simd-32.
Definition at line 618 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
slm_load4()
template<typename T , int n, rgba_channel_mask Mask> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t< (n == 8 || n == 16 || n == 32) && (sizeof(T) == 4), simd<T, n * get_num_channels_enabled(Mask)> > cl::sycl::ext::intel::experimental::esimd::slm_load4 (simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
SLM gather4.
Only allow simd-8, simd-16 and simd-32.
Definition at line 638 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
slm_store()
template<typename T , int n> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n == 16 || n == 32), void> cl::sycl::ext::intel::experimental::esimd::slm_store (simd< T, n > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
SLM scatter.
Definition at line 626 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
slm_store4()
template<typename T , int n, rgba_channel_mask Mask> ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t< (n == 8 || n == 16 || n == 32) && (sizeof(T) == 4), void> cl::sycl::ext::intel::experimental::esimd::slm_store4 (simd< T, n *get_num_channels_enabled(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
SLM scatter4.
Definition at line 646 of file memory.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().