DPC++ Runtime: include/CL/sycl/half_type.hpp File Reference
half_type.hpp File Reference
#include <CL/sycl/detail/defines.hpp>
#include <CL/sycl/detail/export.hpp>
#include <CL/sycl/detail/type_traits.hpp>
#include <array>
#include <cmath>
#include <cstdint>
#include <functional>
#include <iostream>
#include <limits>
Classes
class cl::sycl::detail::host_half_impl::half
struct cl::sycl::detail::half_impl::half_vec< NumElements >
class cl::sycl::detail::half_impl::half
struct std::hash< half >
struct std::numeric_limits< half >
Namespaces
cl
---— Error handling, matching OpenCL plugin semantics.
cl::sycl
cl::sycl::detail
cl::sycl::detail::host_half_impl
cl::sycl::detail::half_impl
std
Macros
#define __SYCL_CONSTEXPR_ON_DEVICE
#define SYCL_HLF_MIN 6.103515625e-05F
#define SYCL_HLF_MAX 65504.0F
#define SYCL_HLF_MAX_10_EXP 4
#define SYCL_HLF_MAX_EXP 16
#define SYCL_HLF_MIN_10_EXP (-4)
#define SYCL_HLF_MIN_EXP (-13)
#define SYCL_HLF_MANT_DIG 11
#define SYCL_HLF_DIG 3
#define SYCL_HLF_DECIMAL_DIG 5
#define SYCL_HLF_EPSILON 9.765625e-04F
#define SYCL_HLF_RADIX 2
Typedefs
using cl::sycl::detail::half_impl::StorageT = detail::host_half_impl::half
using cl::sycl::detail::half_impl::BIsRepresentationT = half
using cl::sycl::detail::half_impl::Vec2StorageT = half_vec< 2 >
using cl::sycl::detail::half_impl::Vec3StorageT = half_vec< 3 >
using cl::sycl::detail::half_impl::Vec4StorageT = half_vec< 4 >
using cl::sycl::detail::half_impl::Vec8StorageT = half_vec< 8 >
using cl::sycl::detail::half_impl::Vec16StorageT = half_vec< 16 >
using half = cl::sycl::detail::half_impl::half
Functions
template<typename T >
T cl::sycl::detail::cast_if_host_half (T val)
float cl::sycl::detail::cast_if_host_half (half_impl::half val)
std::ostream & operator<< (std::ostream &O, half const &rhs)
std::istream & operator>> (std::istream &I, half &rhs)
Macro Definition Documentation
__SYCL_CONSTEXPR_ON_DEVICE
#define __SYCL_CONSTEXPR_ON_DEVICE
Definition at line 27 of file half_type.hpp.
SYCL_HLF_DECIMAL_DIG
#define SYCL_HLF_DECIMAL_DIG 5
Definition at line 257 of file half_type.hpp.
SYCL_HLF_DIG
#define SYCL_HLF_DIG 3
Definition at line 255 of file half_type.hpp.
SYCL_HLF_EPSILON
#define SYCL_HLF_EPSILON 9.765625e-04F
Definition at line 259 of file half_type.hpp.
Referenced by std::numeric_limits< half >::epsilon().
SYCL_HLF_MANT_DIG
#define SYCL_HLF_MANT_DIG 11
Definition at line 253 of file half_type.hpp.
SYCL_HLF_MAX
#define SYCL_HLF_MAX 65504.0F
Definition at line 243 of file half_type.hpp.
Referenced by std::numeric_limits< half >::lowest(), and std::numeric_limits< half >::max().
SYCL_HLF_MAX_10_EXP
#define SYCL_HLF_MAX_10_EXP 4
Definition at line 245 of file half_type.hpp.
SYCL_HLF_MAX_EXP
#define SYCL_HLF_MAX_EXP 16
Definition at line 247 of file half_type.hpp.
SYCL_HLF_MIN
#define SYCL_HLF_MIN 6.103515625e-05F
Definition at line 241 of file half_type.hpp.
Referenced by std::numeric_limits< half >::min().
SYCL_HLF_MIN_10_EXP
#define SYCL_HLF_MIN_10_EXP (-4)
Definition at line 249 of file half_type.hpp.
SYCL_HLF_MIN_EXP
#define SYCL_HLF_MIN_EXP (-13)
Definition at line 251 of file half_type.hpp.
SYCL_HLF_RADIX
#define SYCL_HLF_RADIX 2
Definition at line 261 of file half_type.hpp.
Typedef Documentation
half
using half = cl::sycl::detail::half_impl::half
Definition at line 223 of file half_type.hpp.
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & O, half const & rhs) inline
Definition at line 349 of file half_type.hpp.
Referenced by cl::sycl::detail::pi::DeviceBinaryProperty::DeviceBinaryProperty(), cl::sycl::stream::get_stream_mode(), cl::sycl::detail::spec_constant_impl::isSet(), cl::sycl::__precision_manipulator__::precision(), and cl::sycl::__width_manipulator__::width().
operator>>()
std::istream& operator>> (std::istream & I, half & rhs) inline
Definition at line 354 of file half_type.hpp.