DPC++ Runtime: include/sycl/ext/intel/math/imf_integer_utils.hpp File Reference
imf_integer_utils.hpp File Reference
Namespaces
sycl
sycl::_V1
sycl::_V1::ext
sycl::_V1::ext::intel
sycl::_V1::ext::intel::math
Functions
unsigned __imf_brev (unsigned)
unsigned long long __imf_brevll (unsigned long long)
unsigned __imf_byte_perm (unsigned, unsigned, unsigned)
long long __imf_llmax (long long x, long long y)
long long __imf_llmin (long long x, long long y)
int __imf_max (int x, int y)
int __imf_min (int x, int y)
unsigned long long __imf_ullmax (unsigned long long x, unsigned long long y)
unsigned long long __imf_ullmin (unsigned long long x, unsigned long long y)
unsigned __imf_umax (unsigned x, unsigned y)
unsigned __imf_umin (unsigned x, unsigned y)
int __imf_clz (int)
int __imf_clzll (long long)
int __imf_ffs (int)
int __imf_ffsll (long long)
int __imf_mul24 (int, int)
int __imf_mulhi (int, int)
long long __imf_mul64hi (long long, long long)
int __imf_popc (unsigned)
int __imf_popcll (unsigned long long)
int __imf_rhadd (int, int)
int __imf_hadd (int, int)
unsigned __imf_sad (int, int, unsigned)
unsigned __imf_uhadd (unsigned, unsigned)
unsigned __imf_umul24 (unsigned, unsigned)
unsigned __imf_umulhi (unsigned, unsigned)
unsigned long long __imf_umul64hi (unsigned long long, unsigned long long)
unsigned __imf_urhadd (unsigned, unsigned)
unsigned __imf_usad (unsigned, unsigned, unsigned)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::brev (Tp x)
template<typename Tp = unsigned long long>
unsigned long long sycl::_V1::ext::intel::math::brevll (Tp x)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::byte_perm (Tp x, Tp y, Tp z)
template<typename Tp = int>
int sycl::_V1::ext::intel::math::max (Tp x, Tp y)
template<typename Tp = int>
int sycl::_V1::ext::intel::math::min (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::umax (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::umin (Tp x, Tp y)
template<typename Tp = long long>
long long sycl::_V1::ext::intel::math::llmax (Tp x, Tp y)
template<typename Tp = long long>
long long sycl::_V1::ext::intel::math::llmin (Tp x, Tp y)
template<typename Tp = unsigned long long>
unsigned long long sycl::_V1::ext::intel::math::ullmax (Tp x, Tp y)
template<typename Tp = unsigned long long>
unsigned long long sycl::_V1::ext::intel::math::ullmin (Tp x, Tp y)
template<typename Tp = int>
int sycl::_V1::ext::intel::math::clz (Tp x)
template<typename Tp = long long>
int sycl::_V1::ext::intel::math::clzll (Tp x)
template<typename Tp = int>
int sycl::_V1::ext::intel::math::ffs (Tp x)
template<typename Tp = long long>
int sycl::_V1::ext::intel::math::ffsll (Tp x)
template<typename Tp = int>
int sycl::_V1::ext::intel::math::hadd (Tp x, Tp y)
template<typename Tp = int>
int sycl::_V1::ext::intel::math::rhadd (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::urhadd (Tp x, Tp y)
template<typename Tp = int>
int sycl::_V1::ext::intel::math::mul24 (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::umul24 (Tp x, Tp y)
template<typename Tp = int>
int sycl::_V1::ext::intel::math::mulhi (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::umulhi (Tp x, Tp y)
template<typename Tp = long long>
long long sycl::_V1::ext::intel::math::mul64hi (Tp x, Tp y)
template<typename Tp = unsigned long long>
unsigned long long sycl::_V1::ext::intel::math::umul64hi (Tp x, Tp y)
template<typename Tp = unsigned>
int sycl::_V1::ext::intel::math::popc (Tp x)
template<typename Tp = unsigned long long>
int sycl::_V1::ext::intel::math::popcll (Tp x)
template<typename Tp1 = int, typename Tp2 = unsigned>
unsigned sycl::_V1::ext::intel::math::sad (Tp1 x, Tp1 y, Tp2 z)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::usad (Tp x, Tp y, Tp z)
template<typename Tp = unsigned>
unsigned sycl::_V1::ext::intel::math::uhadd (Tp x, Tp y)
Function Documentation
__imf_brev()
unsigned __imf_brev (unsigned)
Referenced by sycl::_V1::ext::intel::math::brev().
__imf_brevll()
unsigned long long __imf_brevll (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::brevll().
__imf_byte_perm()
unsigned __imf_byte_perm (unsigned , unsigned , unsigned)
Referenced by sycl::_V1::ext::intel::math::byte_perm().
__imf_clz()
int __imf_clz (int)
Referenced by sycl::_V1::ext::intel::math::clz().
__imf_clzll()
int __imf_clzll (long long)
Referenced by sycl::_V1::ext::intel::math::clzll().
__imf_ffs()
int __imf_ffs (int)
Referenced by sycl::_V1::ext::intel::math::ffs().
__imf_ffsll()
int __imf_ffsll (long long)
Referenced by sycl::_V1::ext::intel::math::ffsll().
__imf_hadd()
int __imf_hadd (int , int)
Referenced by sycl::_V1::ext::intel::math::hadd().
__imf_llmax()
long long __imf_llmax (long long x, long long y)
Referenced by sycl::_V1::ext::intel::math::llmax().
__imf_llmin()
long long __imf_llmin (long long x, long long y)
Referenced by sycl::_V1::ext::intel::math::llmin().
__imf_max()
int __imf_max (int x, int y)
Referenced by sycl::_V1::ext::intel::math::max().
__imf_min()
int __imf_min (int x, int y)
Referenced by sycl::_V1::ext::intel::math::min().
__imf_mul24()
int __imf_mul24 (int , int)
Referenced by sycl::_V1::ext::intel::math::mul24().
__imf_mul64hi()
long long __imf_mul64hi (long long , long long)
Referenced by sycl::_V1::ext::intel::math::mul64hi().
__imf_mulhi()
int __imf_mulhi (int , int)
Referenced by sycl::_V1::ext::intel::math::mulhi().
__imf_popc()
int __imf_popc (unsigned)
Referenced by sycl::_V1::ext::intel::math::popc().
__imf_popcll()
int __imf_popcll (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::popcll().
__imf_rhadd()
int __imf_rhadd (int , int)
Referenced by sycl::_V1::ext::intel::math::rhadd().
__imf_sad()
unsigned __imf_sad (int , int , unsigned)
Referenced by sycl::_V1::ext::intel::math::sad().
__imf_uhadd()
unsigned __imf_uhadd (unsigned , unsigned)
Referenced by sycl::_V1::ext::intel::math::uhadd().
__imf_ullmax()
unsigned long long __imf_ullmax (unsigned long long x, unsigned long long y)
Referenced by sycl::_V1::ext::intel::math::ullmax().
__imf_ullmin()
unsigned long long __imf_ullmin (unsigned long long x, unsigned long long y)
Referenced by sycl::_V1::ext::intel::math::ullmin().
__imf_umax()
unsigned __imf_umax (unsigned x, unsigned y)
Referenced by sycl::_V1::ext::intel::math::umax().
__imf_umin()
unsigned __imf_umin (unsigned x, unsigned y)
Referenced by sycl::_V1::ext::intel::math::umin().
__imf_umul24()
unsigned __imf_umul24 (unsigned , unsigned)
Referenced by sycl::_V1::ext::intel::math::umul24().
__imf_umul64hi()
unsigned long long __imf_umul64hi (unsigned long long , unsigned long long)
Referenced by sycl::_V1::ext::intel::math::umul64hi().
__imf_umulhi()
unsigned __imf_umulhi (unsigned , unsigned)
Referenced by sycl::_V1::ext::intel::math::umulhi().
__imf_urhadd()
unsigned __imf_urhadd (unsigned , unsigned)
Referenced by sycl::_V1::ext::intel::math::urhadd().
__imf_usad()
unsigned __imf_usad (unsigned , unsigned , unsigned)
Referenced by sycl::_V1::ext::intel::math::usad().