DPC++ Runtime: include/sycl/ext/intel/math/imf_simd.hpp File Reference
imf_simd.hpp File Reference
#include <type_traits>
Namespaces
sycl
sycl::_V1
sycl::_V1::ext
sycl::_V1::ext::intel
sycl::_V1::ext::intel::math
Functions
unsigned int __imf_vabs2 (unsigned int)
unsigned int __imf_vabs4 (unsigned int)
unsigned int __imf_vneg2 (unsigned int)
unsigned int __imf_vneg4 (unsigned int)
unsigned int __imf_vnegss2 (unsigned int)
unsigned int __imf_vnegss4 (unsigned int)
unsigned int __imf_vabsdiffs2 (unsigned int, unsigned int)
unsigned int __imf_vabsdiffs4 (unsigned int, unsigned int)
unsigned int __imf_vabsdiffu2 (unsigned int, unsigned int)
unsigned int __imf_vabsdiffu4 (unsigned int, unsigned int)
unsigned int __imf_vabsss2 (unsigned int)
unsigned int __imf_vabsss4 (unsigned int)
unsigned int __imf_vadd2 (unsigned int, unsigned int)
unsigned int __imf_vadd4 (unsigned int, unsigned int)
unsigned int __imf_vaddss2 (unsigned int, unsigned int)
unsigned int __imf_vaddss4 (unsigned int, unsigned int)
unsigned int __imf_vaddus2 (unsigned int, unsigned int)
unsigned int __imf_vaddus4 (unsigned int, unsigned int)
unsigned int __imf_vsub2 (unsigned int, unsigned int)
unsigned int __imf_vsub4 (unsigned int, unsigned int)
unsigned int __imf_vsubss2 (unsigned int, unsigned int)
unsigned int __imf_vsubss4 (unsigned int, unsigned int)
unsigned int __imf_vsubus2 (unsigned int, unsigned int)
unsigned int __imf_vsubus4 (unsigned int, unsigned int)
unsigned int __imf_vhaddu2 (unsigned int, unsigned int)
unsigned int __imf_vhaddu4 (unsigned int, unsigned int)
unsigned int __imf_vavgs2 (unsigned int, unsigned int)
unsigned int __imf_vavgs4 (unsigned int, unsigned int)
unsigned int __imf_vavgu2 (unsigned int, unsigned int)
unsigned int __imf_vavgu4 (unsigned int, unsigned int)
unsigned int __imf_vcmpeq2 (unsigned int, unsigned int)
unsigned int __imf_vcmpeq4 (unsigned int, unsigned int)
unsigned int __imf_vcmpges2 (unsigned int, unsigned int)
unsigned int __imf_vcmpges4 (unsigned int, unsigned int)
unsigned int __imf_vcmpgeu2 (unsigned int, unsigned int)
unsigned int __imf_vcmpgeu4 (unsigned int, unsigned int)
unsigned int __imf_vcmpgts2 (unsigned int, unsigned int)
unsigned int __imf_vcmpgts4 (unsigned int, unsigned int)
unsigned int __imf_vcmpgtu2 (unsigned int, unsigned int)
unsigned int __imf_vcmpgtu4 (unsigned int, unsigned int)
unsigned int __imf_vcmples2 (unsigned int, unsigned int)
unsigned int __imf_vcmples4 (unsigned int, unsigned int)
unsigned int __imf_vcmpleu2 (unsigned int, unsigned int)
unsigned int __imf_vcmpleu4 (unsigned int, unsigned int)
unsigned int __imf_vcmplts2 (unsigned int, unsigned int)
unsigned int __imf_vcmplts4 (unsigned int, unsigned int)
unsigned int __imf_vcmpltu2 (unsigned int, unsigned int)
unsigned int __imf_vcmpltu4 (unsigned int, unsigned int)
unsigned int __imf_vcmpne2 (unsigned int, unsigned int)
unsigned int __imf_vcmpne4 (unsigned int, unsigned int)
unsigned int __imf_vmaxs2 (unsigned int, unsigned int)
unsigned int __imf_vmaxs4 (unsigned int, unsigned int)
unsigned int __imf_vmaxu2 (unsigned int, unsigned int)
unsigned int __imf_vmaxu4 (unsigned int, unsigned int)
unsigned int __imf_vmins2 (unsigned int, unsigned int)
unsigned int __imf_vmins4 (unsigned int, unsigned int)
unsigned int __imf_vminu2 (unsigned int, unsigned int)
unsigned int __imf_vminu4 (unsigned int, unsigned int)
unsigned int __imf_vseteq2 (unsigned int, unsigned int)
unsigned int __imf_vseteq4 (unsigned int, unsigned int)
unsigned int __imf_vsetne2 (unsigned int, unsigned int)
unsigned int __imf_vsetne4 (unsigned int, unsigned int)
unsigned int __imf_vsetges2 (unsigned int, unsigned int)
unsigned int __imf_vsetges4 (unsigned int, unsigned int)
unsigned int __imf_vsetgeu2 (unsigned int, unsigned int)
unsigned int __imf_vsetgeu4 (unsigned int, unsigned int)
unsigned int __imf_vsetgts2 (unsigned int, unsigned int)
unsigned int __imf_vsetgts4 (unsigned int, unsigned int)
unsigned int __imf_vsetgtu2 (unsigned int, unsigned int)
unsigned int __imf_vsetgtu4 (unsigned int, unsigned int)
unsigned int __imf_vsetles2 (unsigned int, unsigned int)
unsigned int __imf_vsetles4 (unsigned int, unsigned int)
unsigned int __imf_vsetleu2 (unsigned int, unsigned int)
unsigned int __imf_vsetleu4 (unsigned int, unsigned int)
unsigned int __imf_vsetlts2 (unsigned int, unsigned int)
unsigned int __imf_vsetlts4 (unsigned int, unsigned int)
unsigned int __imf_vsetltu2 (unsigned int, unsigned int)
unsigned int __imf_vsetltu4 (unsigned int, unsigned int)
unsigned int __imf_vsads2 (unsigned int, unsigned int)
unsigned int __imf_vsads4 (unsigned int, unsigned int)
unsigned int __imf_vsadu2 (unsigned int, unsigned int)
unsigned int __imf_vsadu4 (unsigned int, unsigned int)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vabs2 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vabs4 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vneg2 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vneg4 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vnegss2 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vnegss4 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vabsdiffs2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vabsdiffs4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vabsdiffu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vabsdiffu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vabsss2 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vabsss4 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vadd2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vadd4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vaddss2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vaddss4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vaddus2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vaddus4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsub2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsub4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsubss2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsubss4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsubus2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsubus4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vhaddu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vhaddu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vavgs2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vavgs4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vavgu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vavgu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpeq2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpeq4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpges2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpges4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpgeu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpgeu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpgts2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpgts4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpgtu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpgtu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmples2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmples4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpleu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpleu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmplts2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmplts4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpltu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpltu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpne2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vcmpne4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vmaxs2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vmaxs4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vmaxu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vmaxu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vmins2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vmins4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vminu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vminu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vseteq2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vseteq4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetne2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetne4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetges2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetges4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetgeu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetgeu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetgts2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetgts4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetgtu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetgtu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetles2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetles4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetleu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetleu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetlts2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetlts4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetltu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsetltu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsads2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsads4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsadu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > sycl::_V1::ext::intel::math::vsadu4 (Tp x, Tp y)
Function Documentation
__imf_vabs2()
unsigned int __imf_vabs2 (unsigned int)
Referenced by sycl::_V1::ext::intel::math::vabs2().
__imf_vabs4()
unsigned int __imf_vabs4 (unsigned int)
Referenced by sycl::_V1::ext::intel::math::vabs4().
__imf_vabsdiffs2()
unsigned int __imf_vabsdiffs2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vabsdiffs2().
__imf_vabsdiffs4()
unsigned int __imf_vabsdiffs4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vabsdiffs4().
__imf_vabsdiffu2()
unsigned int __imf_vabsdiffu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vabsdiffu2().
__imf_vabsdiffu4()
unsigned int __imf_vabsdiffu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vabsdiffu4().
__imf_vabsss2()
unsigned int __imf_vabsss2 (unsigned int)
Referenced by sycl::_V1::ext::intel::math::vabsss2().
__imf_vabsss4()
unsigned int __imf_vabsss4 (unsigned int)
Referenced by sycl::_V1::ext::intel::math::vabsss4().
__imf_vadd2()
unsigned int __imf_vadd2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vadd2().
__imf_vadd4()
unsigned int __imf_vadd4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vadd4().
__imf_vaddss2()
unsigned int __imf_vaddss2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vaddss2().
__imf_vaddss4()
unsigned int __imf_vaddss4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vaddss4().
__imf_vaddus2()
unsigned int __imf_vaddus2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vaddus2().
__imf_vaddus4()
unsigned int __imf_vaddus4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vaddus4().
__imf_vavgs2()
unsigned int __imf_vavgs2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vavgs2().
__imf_vavgs4()
unsigned int __imf_vavgs4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vavgs4().
__imf_vavgu2()
unsigned int __imf_vavgu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vavgu2().
__imf_vavgu4()
unsigned int __imf_vavgu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vavgu4().
__imf_vcmpeq2()
unsigned int __imf_vcmpeq2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpeq2().
__imf_vcmpeq4()
unsigned int __imf_vcmpeq4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpeq4().
__imf_vcmpges2()
unsigned int __imf_vcmpges2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpges2().
__imf_vcmpges4()
unsigned int __imf_vcmpges4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpges4().
__imf_vcmpgeu2()
unsigned int __imf_vcmpgeu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpgeu2().
__imf_vcmpgeu4()
unsigned int __imf_vcmpgeu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpgeu4().
__imf_vcmpgts2()
unsigned int __imf_vcmpgts2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpgts2().
__imf_vcmpgts4()
unsigned int __imf_vcmpgts4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpgts4().
__imf_vcmpgtu2()
unsigned int __imf_vcmpgtu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpgtu2().
__imf_vcmpgtu4()
unsigned int __imf_vcmpgtu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpgtu4().
__imf_vcmples2()
unsigned int __imf_vcmples2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmples2().
__imf_vcmples4()
unsigned int __imf_vcmples4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmples4().
__imf_vcmpleu2()
unsigned int __imf_vcmpleu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpleu2().
__imf_vcmpleu4()
unsigned int __imf_vcmpleu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpleu4().
__imf_vcmplts2()
unsigned int __imf_vcmplts2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmplts2().
__imf_vcmplts4()
unsigned int __imf_vcmplts4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmplts4().
__imf_vcmpltu2()
unsigned int __imf_vcmpltu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpltu2().
__imf_vcmpltu4()
unsigned int __imf_vcmpltu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpltu4().
__imf_vcmpne2()
unsigned int __imf_vcmpne2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpne2().
__imf_vcmpne4()
unsigned int __imf_vcmpne4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vcmpne4().
__imf_vhaddu2()
unsigned int __imf_vhaddu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vhaddu2().
__imf_vhaddu4()
unsigned int __imf_vhaddu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vhaddu4().
__imf_vmaxs2()
unsigned int __imf_vmaxs2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vmaxs2().
__imf_vmaxs4()
unsigned int __imf_vmaxs4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vmaxs4().
__imf_vmaxu2()
unsigned int __imf_vmaxu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vmaxu2().
__imf_vmaxu4()
unsigned int __imf_vmaxu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vmaxu4().
__imf_vmins2()
unsigned int __imf_vmins2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vmins2().
__imf_vmins4()
unsigned int __imf_vmins4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vmins4().
__imf_vminu2()
unsigned int __imf_vminu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vminu2().
__imf_vminu4()
unsigned int __imf_vminu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vminu4().
__imf_vneg2()
unsigned int __imf_vneg2 (unsigned int)
Referenced by sycl::_V1::ext::intel::math::vneg2().
__imf_vneg4()
unsigned int __imf_vneg4 (unsigned int)
Referenced by sycl::_V1::ext::intel::math::vneg4().
__imf_vnegss2()
unsigned int __imf_vnegss2 (unsigned int)
Referenced by sycl::_V1::ext::intel::math::vnegss2().
__imf_vnegss4()
unsigned int __imf_vnegss4 (unsigned int)
Referenced by sycl::_V1::ext::intel::math::vnegss4().
__imf_vsads2()
unsigned int __imf_vsads2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsads2().
__imf_vsads4()
unsigned int __imf_vsads4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsads4().
__imf_vsadu2()
unsigned int __imf_vsadu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsadu2().
__imf_vsadu4()
unsigned int __imf_vsadu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsadu4().
__imf_vseteq2()
unsigned int __imf_vseteq2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vseteq2().
__imf_vseteq4()
unsigned int __imf_vseteq4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vseteq4().
__imf_vsetges2()
unsigned int __imf_vsetges2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetges2().
__imf_vsetges4()
unsigned int __imf_vsetges4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetges4().
__imf_vsetgeu2()
unsigned int __imf_vsetgeu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetgeu2().
__imf_vsetgeu4()
unsigned int __imf_vsetgeu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetgeu4().
__imf_vsetgts2()
unsigned int __imf_vsetgts2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetgts2().
__imf_vsetgts4()
unsigned int __imf_vsetgts4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetgts4().
__imf_vsetgtu2()
unsigned int __imf_vsetgtu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetgtu2().
__imf_vsetgtu4()
unsigned int __imf_vsetgtu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetgtu4().
__imf_vsetles2()
unsigned int __imf_vsetles2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetles2().
__imf_vsetles4()
unsigned int __imf_vsetles4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetles4().
__imf_vsetleu2()
unsigned int __imf_vsetleu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetleu2().
__imf_vsetleu4()
unsigned int __imf_vsetleu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetleu4().
__imf_vsetlts2()
unsigned int __imf_vsetlts2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetlts2().
__imf_vsetlts4()
unsigned int __imf_vsetlts4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetlts4().
__imf_vsetltu2()
unsigned int __imf_vsetltu2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetltu2().
__imf_vsetltu4()
unsigned int __imf_vsetltu4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetltu4().
__imf_vsetne2()
unsigned int __imf_vsetne2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetne2().
__imf_vsetne4()
unsigned int __imf_vsetne4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsetne4().
__imf_vsub2()
unsigned int __imf_vsub2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsub2().
__imf_vsub4()
unsigned int __imf_vsub4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsub4().
__imf_vsubss2()
unsigned int __imf_vsubss2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsubss2().
__imf_vsubss4()
unsigned int __imf_vsubss4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsubss4().
__imf_vsubus2()
unsigned int __imf_vsubus2 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsubus2().
__imf_vsubus4()
unsigned int __imf_vsubus4 (unsigned int , unsigned int)
Referenced by sycl::_V1::ext::intel::math::vsubus4().