DPC++ Runtime: include/sycl/ext/intel/math/imf_rounding_math.hpp File Reference
imf_rounding_math.hpp File Reference
Namespaces
sycl
sycl::_V1
sycl::_V1::ext
sycl::_V1::ext::intel
sycl::_V1::ext::intel::math
Functions
float __imf_fadd_rz (float, float)
float __imf_fadd_rn (float, float)
float __imf_fadd_ru (float, float)
float __imf_fadd_rd (float, float)
float __imf_fsub_rz (float, float)
float __imf_fsub_rn (float, float)
float __imf_fsub_ru (float, float)
float __imf_fsub_rd (float, float)
float __imf_fmul_rz (float, float)
float __imf_fmul_rn (float, float)
float __imf_fmul_ru (float, float)
float __imf_fmul_rd (float, float)
float __imf_fdiv_rz (float, float)
float __imf_fdiv_rn (float, float)
float __imf_fdiv_ru (float, float)
float __imf_fdiv_rd (float, float)
float __imf_frcp_rz (float)
float __imf_frcp_rn (float)
float __imf_frcp_ru (float)
float __imf_frcp_rd (float)
float __imf_fmaf_rz (float, float, float)
float __imf_fmaf_rn (float, float, float)
float __imf_fmaf_ru (float, float, float)
float __imf_fmaf_rd (float, float, float)
float __imf_sqrtf_rz (float)
float __imf_sqrtf_rn (float)
float __imf_sqrtf_ru (float)
float __imf_sqrtf_rd (float)
double __imf_dadd_rz (double, double)
double __imf_dadd_rn (double, double)
double __imf_dadd_ru (double, double)
double __imf_dadd_rd (double, double)
double __imf_dsub_rz (double, double)
double __imf_dsub_rn (double, double)
double __imf_dsub_ru (double, double)
double __imf_dsub_rd (double, double)
double __imf_dmul_rz (double, double)
double __imf_dmul_rn (double, double)
double __imf_dmul_ru (double, double)
double __imf_dmul_rd (double, double)
double __imf_ddiv_rz (double, double)
double __imf_ddiv_rn (double, double)
double __imf_ddiv_ru (double, double)
double __imf_ddiv_rd (double, double)
double __imf_drcp_rz (double)
double __imf_drcp_rn (double)
double __imf_drcp_ru (double)
double __imf_drcp_rd (double)
double __imf_fma_rz (double, double, double)
double __imf_fma_rn (double, double, double)
double __imf_fma_ru (double, double, double)
double __imf_fma_rd (double, double, double)
double __imf_sqrt_rz (double)
double __imf_sqrt_rn (double)
double __imf_sqrt_ru (double)
double __imf_sqrt_rd (double)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fadd_rd (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fadd_rn (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fadd_ru (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fadd_rz (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fsub_rd (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fsub_rn (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fsub_ru (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fsub_rz (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fmul_rd (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fmul_rn (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fmul_ru (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fmul_rz (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fdiv_rd (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fdiv_rn (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fdiv_ru (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fdiv_rz (Tp x, Tp y)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::frcp_rd (Tp x)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::frcp_rn (Tp x)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::frcp_ru (Tp x)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::frcp_rz (Tp x)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fmaf_rd (Tp x, Tp y, Tp z)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fmaf_rn (Tp x, Tp y, Tp z)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fmaf_ru (Tp x, Tp y, Tp z)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fmaf_rz (Tp x, Tp y, Tp z)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fsqrt_rd (Tp x)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fsqrt_rn (Tp x)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fsqrt_ru (Tp x)
template<typename Tp = float>
Tp sycl::_V1::ext::intel::math::fsqrt_rz (Tp x)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dadd_rd (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dadd_rn (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dadd_ru (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dadd_rz (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dsub_rd (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dsub_rn (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dsub_ru (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dsub_rz (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dmul_rd (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dmul_rn (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dmul_ru (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dmul_rz (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::ddiv_rd (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::ddiv_rn (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::ddiv_ru (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::ddiv_rz (Tp x, Tp y)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::drcp_rd (Tp x)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::drcp_rn (Tp x)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::drcp_ru (Tp x)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::drcp_rz (Tp x)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::fma_rd (Tp x, Tp y, Tp z)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::fma_rn (Tp x, Tp y, Tp z)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::fma_ru (Tp x, Tp y, Tp z)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::fma_rz (Tp x, Tp y, Tp z)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dsqrt_rd (Tp x)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dsqrt_rn (Tp x)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dsqrt_ru (Tp x)
template<typename Tp = double>
Tp sycl::_V1::ext::intel::math::dsqrt_rz (Tp x)
Function Documentation
__imf_dadd_rd()
double __imf_dadd_rd (double , double)
Referenced by sycl::_V1::ext::intel::math::dadd_rd().
__imf_dadd_rn()
double __imf_dadd_rn (double , double)
Referenced by sycl::_V1::ext::intel::math::dadd_rn().
__imf_dadd_ru()
double __imf_dadd_ru (double , double)
Referenced by sycl::_V1::ext::intel::math::dadd_ru().
__imf_dadd_rz()
double __imf_dadd_rz (double , double)
Referenced by sycl::_V1::ext::intel::math::dadd_rz().
__imf_ddiv_rd()
double __imf_ddiv_rd (double , double)
Referenced by sycl::_V1::ext::intel::math::ddiv_rd().
__imf_ddiv_rn()
double __imf_ddiv_rn (double , double)
Referenced by sycl::_V1::ext::intel::math::ddiv_rn().
__imf_ddiv_ru()
double __imf_ddiv_ru (double , double)
Referenced by sycl::_V1::ext::intel::math::ddiv_ru().
__imf_ddiv_rz()
double __imf_ddiv_rz (double , double)
Referenced by sycl::_V1::ext::intel::math::ddiv_rz().
__imf_dmul_rd()
double __imf_dmul_rd (double , double)
Referenced by sycl::_V1::ext::intel::math::dmul_rd().
__imf_dmul_rn()
double __imf_dmul_rn (double , double)
Referenced by sycl::_V1::ext::intel::math::dmul_rn().
__imf_dmul_ru()
double __imf_dmul_ru (double , double)
Referenced by sycl::_V1::ext::intel::math::dmul_ru().
__imf_dmul_rz()
double __imf_dmul_rz (double , double)
Referenced by sycl::_V1::ext::intel::math::dmul_rz().
__imf_drcp_rd()
double __imf_drcp_rd (double)
Referenced by sycl::_V1::ext::intel::math::drcp_rd().
__imf_drcp_rn()
double __imf_drcp_rn (double)
Referenced by sycl::_V1::ext::intel::math::drcp_rn().
__imf_drcp_ru()
double __imf_drcp_ru (double)
Referenced by sycl::_V1::ext::intel::math::drcp_ru().
__imf_drcp_rz()
double __imf_drcp_rz (double)
Referenced by sycl::_V1::ext::intel::math::drcp_rz().
__imf_dsub_rd()
double __imf_dsub_rd (double , double)
Referenced by sycl::_V1::ext::intel::math::dsub_rd().
__imf_dsub_rn()
double __imf_dsub_rn (double , double)
Referenced by sycl::_V1::ext::intel::math::dsub_rn().
__imf_dsub_ru()
double __imf_dsub_ru (double , double)
Referenced by sycl::_V1::ext::intel::math::dsub_ru().
__imf_dsub_rz()
double __imf_dsub_rz (double , double)
Referenced by sycl::_V1::ext::intel::math::dsub_rz().
__imf_fadd_rd()
float __imf_fadd_rd (float , float)
Referenced by sycl::_V1::ext::intel::math::fadd_rd().
__imf_fadd_rn()
float __imf_fadd_rn (float , float)
Referenced by sycl::_V1::ext::intel::math::fadd_rn().
__imf_fadd_ru()
float __imf_fadd_ru (float , float)
Referenced by sycl::_V1::ext::intel::math::fadd_ru().
__imf_fadd_rz()
float __imf_fadd_rz (float , float)
Referenced by sycl::_V1::ext::intel::math::fadd_rz().
__imf_fdiv_rd()
float __imf_fdiv_rd (float , float)
Referenced by sycl::_V1::ext::intel::math::fdiv_rd().
__imf_fdiv_rn()
float __imf_fdiv_rn (float , float)
Referenced by sycl::_V1::ext::intel::math::fdiv_rn().
__imf_fdiv_ru()
float __imf_fdiv_ru (float , float)
Referenced by sycl::_V1::ext::intel::math::fdiv_ru().
__imf_fdiv_rz()
float __imf_fdiv_rz (float , float)
Referenced by sycl::_V1::ext::intel::math::fdiv_rz().
__imf_fma_rd()
double __imf_fma_rd (double , double , double)
Referenced by sycl::_V1::ext::intel::math::fma_rd().
__imf_fma_rn()
double __imf_fma_rn (double , double , double)
Referenced by sycl::_V1::ext::intel::math::fma_rn().
__imf_fma_ru()
double __imf_fma_ru (double , double , double)
Referenced by sycl::_V1::ext::intel::math::fma_ru().
__imf_fma_rz()
double __imf_fma_rz (double , double , double)
Referenced by sycl::_V1::ext::intel::math::fma_rz().
__imf_fmaf_rd()
float __imf_fmaf_rd (float , float , float)
Referenced by sycl::_V1::ext::intel::math::fmaf_rd().
__imf_fmaf_rn()
float __imf_fmaf_rn (float , float , float)
Referenced by sycl::_V1::ext::intel::math::fmaf_rn().
__imf_fmaf_ru()
float __imf_fmaf_ru (float , float , float)
Referenced by sycl::_V1::ext::intel::math::fmaf_ru().
__imf_fmaf_rz()
float __imf_fmaf_rz (float , float , float)
Referenced by sycl::_V1::ext::intel::math::fmaf_rz().
__imf_fmul_rd()
float __imf_fmul_rd (float , float)
Referenced by sycl::_V1::ext::intel::math::fmul_rd().
__imf_fmul_rn()
float __imf_fmul_rn (float , float)
Referenced by sycl::_V1::ext::intel::math::fmul_rn().
__imf_fmul_ru()
float __imf_fmul_ru (float , float)
Referenced by sycl::_V1::ext::intel::math::fmul_ru().
__imf_fmul_rz()
float __imf_fmul_rz (float , float)
Referenced by sycl::_V1::ext::intel::math::fmul_rz().
__imf_frcp_rd()
float __imf_frcp_rd (float)
Referenced by sycl::_V1::ext::intel::math::frcp_rd().
__imf_frcp_rn()
float __imf_frcp_rn (float)
Referenced by sycl::_V1::ext::intel::math::frcp_rn().
__imf_frcp_ru()
float __imf_frcp_ru (float)
Referenced by sycl::_V1::ext::intel::math::frcp_ru().
__imf_frcp_rz()
float __imf_frcp_rz (float)
Referenced by sycl::_V1::ext::intel::math::frcp_rz().
__imf_fsub_rd()
float __imf_fsub_rd (float , float)
Referenced by sycl::_V1::ext::intel::math::fsub_rd().
__imf_fsub_rn()
float __imf_fsub_rn (float , float)
Referenced by sycl::_V1::ext::intel::math::fsub_rn().
__imf_fsub_ru()
float __imf_fsub_ru (float , float)
Referenced by sycl::_V1::ext::intel::math::fsub_ru().
__imf_fsub_rz()
float __imf_fsub_rz (float , float)
Referenced by sycl::_V1::ext::intel::math::fsub_rz().
__imf_sqrt_rd()
double __imf_sqrt_rd (double)
Referenced by sycl::_V1::ext::intel::math::dsqrt_rd().
__imf_sqrt_rn()
double __imf_sqrt_rn (double)
Referenced by sycl::_V1::ext::intel::math::dsqrt_rn().
__imf_sqrt_ru()
double __imf_sqrt_ru (double)
Referenced by sycl::_V1::ext::intel::math::dsqrt_ru().
__imf_sqrt_rz()
double __imf_sqrt_rz (double)
Referenced by sycl::_V1::ext::intel::math::dsqrt_rz().
__imf_sqrtf_rd()
float __imf_sqrtf_rd (float)
Referenced by sycl::_V1::ext::intel::math::fsqrt_rd().
__imf_sqrtf_rn()
float __imf_sqrtf_rn (float)
Referenced by sycl::_V1::ext::intel::math::fsqrt_rn().
__imf_sqrtf_ru()
float __imf_sqrtf_ru (float)
Referenced by sycl::_V1::ext::intel::math::fsqrt_ru().
__imf_sqrtf_rz()
float __imf_sqrtf_rz (float)
Referenced by sycl::_V1::ext::intel::math::fsqrt_rz().