DPC++ Runtime: include/sycl/ext/intel/math/imf_fp_conversions.hpp File Reference
imf_fp_conversions.hpp File Reference
#include <sycl/bit_cast.hpp>
#include <sycl/ext/intel/math.hpp>
#include <sycl/ext/oneapi/bfloat16.hpp>
#include <sycl/half_type.hpp>
Namespaces
sycl
sycl::_V1
sycl::_V1::ext
sycl::_V1::ext::intel
sycl::_V1::ext::intel::math
Functions
int __imf_float2int_rd (float)
int __imf_float2int_rn (float)
int __imf_float2int_ru (float)
int __imf_float2int_rz (float)
unsigned int __imf_float2uint_rd (float)
unsigned int __imf_float2uint_rn (float)
unsigned int __imf_float2uint_ru (float)
unsigned int __imf_float2uint_rz (float)
long long int __imf_float2ll_rd (float)
long long int __imf_float2ll_rn (float)
long long int __imf_float2ll_ru (float)
long long int __imf_float2ll_rz (float)
unsigned long long int __imf_float2ull_rd (float)
unsigned long long int __imf_float2ull_rn (float)
unsigned long long int __imf_float2ull_ru (float)
unsigned long long int __imf_float2ull_rz (float)
int __imf_float_as_int (float)
unsigned int __imf_float_as_uint (float)
float __imf_int2float_rd (int)
float __imf_int2float_rn (int)
float __imf_int2float_ru (int)
float __imf_int2float_rz (int)
float __imf_int_as_float (int)
float __imf_ll2float_rd (long long int)
float __imf_ll2float_rn (long long int)
float __imf_ll2float_ru (long long int)
float __imf_ll2float_rz (long long int)
float __imf_uint2float_rd (unsigned int)
float __imf_uint2float_rn (unsigned int)
float __imf_uint2float_ru (unsigned int)
float __imf_uint2float_rz (unsigned int)
float __imf_uint_as_float (unsigned int)
float __imf_ull2float_rd (unsigned long long int)
float __imf_ull2float_rn (unsigned long long int)
float __imf_ull2float_ru (unsigned long long int)
float __imf_ull2float_rz (unsigned long long int)
float __imf_double2float_rd (double)
float __imf_double2float_rn (double)
float __imf_double2float_ru (double)
float __imf_double2float_rz (double)
int __imf_double2hiint (double)
int __imf_double2loint (double)
int __imf_double2int_rd (double)
int __imf_double2int_rn (double)
int __imf_double2int_ru (double)
int __imf_double2int_rz (double)
long long __imf_double2ll_rd (double)
long long __imf_double2ll_rn (double)
long long __imf_double2ll_ru (double)
long long __imf_double2ll_rz (double)
unsigned int __imf_double2uint_rd (double)
unsigned int __imf_double2uint_rn (double)
unsigned int __imf_double2uint_ru (double)
unsigned int __imf_double2uint_rz (double)
unsigned long long __imf_double2ull_rd (double)
unsigned long long __imf_double2ull_rn (double)
unsigned long long __imf_double2ull_ru (double)
unsigned long long __imf_double2ull_rz (double)
long long __imf_double_as_longlong (double)
double __imf_hiloint2double (int, int)
double __imf_int2double_rn (int)
double __imf_ll2double_rd (long long)
double __imf_ll2double_rn (long long)
double __imf_ll2double_ru (long long)
double __imf_ll2double_rz (long long)
double __imf_longlong_as_double (long long)
double __imf_uint2double_rn (unsigned)
double __imf_ull2double_rd (unsigned long long)
double __imf_ull2double_rn (unsigned long long)
double __imf_ull2double_ru (unsigned long long)
double __imf_ull2double_rz (unsigned long long)
float __imf_half2float (_iml_half_internal)
_iml_half_internal __imf_float2half_rd (float)
_iml_half_internal __imf_float2half_rn (float)
_iml_half_internal __imf_float2half_ru (float)
_iml_half_internal __imf_float2half_rz (float)
int __imf_half2int_rd (_iml_half_internal)
int __imf_half2int_rn (_iml_half_internal)
int __imf_half2int_ru (_iml_half_internal)
int __imf_half2int_rz (_iml_half_internal)
long long __imf_half2ll_rd (_iml_half_internal)
long long __imf_half2ll_rn (_iml_half_internal)
long long __imf_half2ll_ru (_iml_half_internal)
long long __imf_half2ll_rz (_iml_half_internal)
short __imf_half2short_rd (_iml_half_internal)
short __imf_half2short_rn (_iml_half_internal)
short __imf_half2short_ru (_iml_half_internal)
short __imf_half2short_rz (_iml_half_internal)
unsigned int __imf_half2uint_rd (_iml_half_internal)
unsigned int __imf_half2uint_rn (_iml_half_internal)
unsigned int __imf_half2uint_ru (_iml_half_internal)
unsigned int __imf_half2uint_rz (_iml_half_internal)
unsigned long long __imf_half2ull_rd (_iml_half_internal)
unsigned long long __imf_half2ull_rn (_iml_half_internal)
unsigned long long __imf_half2ull_ru (_iml_half_internal)
unsigned long long __imf_half2ull_rz (_iml_half_internal)
unsigned short __imf_half2ushort_rd (_iml_half_internal)
unsigned short __imf_half2ushort_rn (_iml_half_internal)
unsigned short __imf_half2ushort_ru (_iml_half_internal)
unsigned short __imf_half2ushort_rz (_iml_half_internal)
short __imf_half_as_short (_iml_half_internal)
unsigned short __imf_half_as_ushort (_iml_half_internal)
_iml_half_internal __imf_int2half_rd (int)
_iml_half_internal __imf_int2half_rn (int)
_iml_half_internal __imf_int2half_ru (int)
_iml_half_internal __imf_int2half_rz (int)
_iml_half_internal __imf_ll2half_rd (long long)
_iml_half_internal __imf_ll2half_rn (long long)
_iml_half_internal __imf_ll2half_ru (long long)
_iml_half_internal __imf_ll2half_rz (long long)
_iml_half_internal __imf_short2half_rd (short)
_iml_half_internal __imf_short2half_rn (short)
_iml_half_internal __imf_short2half_ru (short)
_iml_half_internal __imf_short2half_rz (short)
_iml_half_internal __imf_short_as_half (short)
_iml_half_internal __imf_uint2half_rd (unsigned int)
_iml_half_internal __imf_uint2half_rn (unsigned int)
_iml_half_internal __imf_uint2half_ru (unsigned int)
_iml_half_internal __imf_uint2half_rz (unsigned int)
_iml_half_internal __imf_ull2half_rd (unsigned long long)
_iml_half_internal __imf_ull2half_rn (unsigned long long)
_iml_half_internal __imf_ull2half_ru (unsigned long long)
_iml_half_internal __imf_ull2half_rz (unsigned long long)
_iml_half_internal __imf_ushort2half_rd (unsigned short)
_iml_half_internal __imf_ushort2half_rn (unsigned short)
_iml_half_internal __imf_ushort2half_ru (unsigned short)
_iml_half_internal __imf_ushort2half_rz (unsigned short)
_iml_half_internal __imf_ushort_as_half (unsigned short)
_iml_half_internal __imf_double2half (double)
unsigned short __imf_bfloat162ushort_rd (uint16_t)
unsigned short __imf_bfloat162ushort_rn (uint16_t)
unsigned short __imf_bfloat162ushort_ru (uint16_t)
unsigned short __imf_bfloat162ushort_rz (uint16_t)
short __imf_bfloat162short_rd (uint16_t)
short __imf_bfloat162short_rn (uint16_t)
short __imf_bfloat162short_ru (uint16_t)
short __imf_bfloat162short_rz (uint16_t)
unsigned int __imf_bfloat162uint_rd (uint16_t)
unsigned int __imf_bfloat162uint_rn (uint16_t)
unsigned int __imf_bfloat162uint_ru (uint16_t)
unsigned int __imf_bfloat162uint_rz (uint16_t)
int __imf_bfloat162int_rd (uint16_t)
int __imf_bfloat162int_rn (uint16_t)
int __imf_bfloat162int_ru (uint16_t)
int __imf_bfloat162int_rz (uint16_t)
unsigned long long __imf_bfloat162ull_rd (uint16_t)
unsigned long long __imf_bfloat162ull_rn (uint16_t)
unsigned long long __imf_bfloat162ull_ru (uint16_t)
unsigned long long __imf_bfloat162ull_rz (uint16_t)
long long __imf_bfloat162ll_rd (uint16_t)
long long __imf_bfloat162ll_rn (uint16_t)
long long __imf_bfloat162ll_ru (uint16_t)
long long __imf_bfloat162ll_rz (uint16_t)
float __imf_bfloat162float (uint16_t)
uint16_t __imf_float2bfloat16 (float)
uint16_t __imf_float2bfloat16_rd (float)
uint16_t __imf_float2bfloat16_rn (float)
uint16_t __imf_float2bfloat16_ru (float)
uint16_t __imf_float2bfloat16_rz (float)
uint16_t __imf_ushort2bfloat16_rd (unsigned short)
uint16_t __imf_ushort2bfloat16_rn (unsigned short)
uint16_t __imf_ushort2bfloat16_ru (unsigned short)
uint16_t __imf_ushort2bfloat16_rz (unsigned short)
uint16_t __imf_uint2bfloat16_rd (unsigned int)
uint16_t __imf_uint2bfloat16_rn (unsigned int)
uint16_t __imf_uint2bfloat16_ru (unsigned int)
uint16_t __imf_uint2bfloat16_rz (unsigned int)
uint16_t __imf_ull2bfloat16_rd (unsigned long long)
uint16_t __imf_ull2bfloat16_rn (unsigned long long)
uint16_t __imf_ull2bfloat16_ru (unsigned long long)
uint16_t __imf_ull2bfloat16_rz (unsigned long long)
uint16_t __imf_short2bfloat16_rd (short)
uint16_t __imf_short2bfloat16_rn (short)
uint16_t __imf_short2bfloat16_ru (short)
uint16_t __imf_short2bfloat16_rz (short)
uint16_t __imf_int2bfloat16_rd (int)
uint16_t __imf_int2bfloat16_rn (int)
uint16_t __imf_int2bfloat16_ru (int)
uint16_t __imf_int2bfloat16_rz (int)
uint16_t __imf_ll2bfloat16_rd (long long)
uint16_t __imf_ll2bfloat16_rn (long long)
uint16_t __imf_ll2bfloat16_ru (long long)
uint16_t __imf_ll2bfloat16_rz (long long)
uint16_t __imf_double2bfloat16 (double)
short __imf_bfloat16_as_short (uint16_t)
unsigned short __imf_bfloat16_as_ushort (uint16_t)
uint16_t __imf_short_as_bfloat16 (short)
uint16_t __imf_ushort_as_bfloat16 (unsigned short)
template<typename To = int, typename From = float>
To sycl::_V1::ext::intel::math::float2int_rd (From x)
template<typename To = int, typename From = float>
To sycl::_V1::ext::intel::math::float2int_rn (From x)
template<typename To = int, typename From = float>
To sycl::_V1::ext::intel::math::float2int_ru (From x)
template<typename To = int, typename From = float>
To sycl::_V1::ext::intel::math::float2int_rz (From x)
template<typename To = unsigned int, typename From = float>
To sycl::_V1::ext::intel::math::float2uint_rd (From x)
template<typename To = unsigned int, typename From = float>
To sycl::_V1::ext::intel::math::float2uint_rn (From x)
template<typename To = unsigned int, typename From = float>
To sycl::_V1::ext::intel::math::float2uint_ru (From x)
template<typename To = unsigned int, typename From = float>
To sycl::_V1::ext::intel::math::float2uint_rz (From x)
template<typename To = long long, typename From = float>
To sycl::_V1::ext::intel::math::float2ll_rd (From x)
template<typename To = long long, typename From = float>
To sycl::_V1::ext::intel::math::float2ll_rn (From x)
template<typename To = long long, typename From = float>
To sycl::_V1::ext::intel::math::float2ll_ru (From x)
template<typename To = long long, typename From = float>
To sycl::_V1::ext::intel::math::float2ll_rz (From x)
template<typename To = unsigned long long, typename From = float>
To sycl::_V1::ext::intel::math::float2ull_rd (From x)
template<typename To = unsigned long long, typename From = float>
To sycl::_V1::ext::intel::math::float2ull_rn (From x)
template<typename To = unsigned long long, typename From = float>
To sycl::_V1::ext::intel::math::float2ull_ru (From x)
template<typename To = unsigned long long, typename From = float>
To sycl::_V1::ext::intel::math::float2ull_rz (From x)
template<typename To = float, typename From = long long>
To sycl::_V1::ext::intel::math::ll2float_rd (From x)
template<typename To = float, typename From = long long>
To sycl::_V1::ext::intel::math::ll2float_rn (From x)
template<typename To = float, typename From = long long>
To sycl::_V1::ext::intel::math::ll2float_ru (From x)
template<typename To = float, typename From = long long>
To sycl::_V1::ext::intel::math::ll2float_rz (From x)
template<typename To = float, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2float_rd (From x)
template<typename To = float, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2float_rn (From x)
template<typename To = float, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2float_ru (From x)
template<typename To = float, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2float_rz (From x)
template<typename To = float, typename From = int>
To sycl::_V1::ext::intel::math::int2float_rd (From x)
template<typename To = float, typename From = int>
To sycl::_V1::ext::intel::math::int2float_rn (From x)
template<typename To = float, typename From = int>
To sycl::_V1::ext::intel::math::int2float_ru (From x)
template<typename To = float, typename From = int>
To sycl::_V1::ext::intel::math::int2float_rz (From x)
template<typename To = float, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2float_rd (From x)
template<typename To = float, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2float_rn (From x)
template<typename To = float, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2float_ru (From x)
template<typename To = float, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2float_rz (From x)
template<typename To = int, typename From = float>
To sycl::_V1::ext::intel::math::float_as_int (From x)
template<typename To = unsigned int, typename From = float>
To sycl::_V1::ext::intel::math::float_as_uint (From x)
template<typename To = float, typename From = int>
To sycl::_V1::ext::intel::math::int_as_float (From x)
template<typename To = float, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint_as_float (From x)
template<typename To = float, typename From = double>
To sycl::_V1::ext::intel::math::double2float_rd (From x)
template<typename To = float, typename From = double>
To sycl::_V1::ext::intel::math::double2float_rn (From x)
template<typename To = float, typename From = double>
To sycl::_V1::ext::intel::math::double2float_ru (From x)
template<typename To = float, typename From = double>
To sycl::_V1::ext::intel::math::double2float_rz (From x)
template<typename To = int, typename From = double>
To sycl::_V1::ext::intel::math::double2hiint (From x)
template<typename To = int, typename From = double>
To sycl::_V1::ext::intel::math::double2loint (From x)
template<typename To = int, typename From = double>
To sycl::_V1::ext::intel::math::double2int_rd (From x)
template<typename To = int, typename From = double>
To sycl::_V1::ext::intel::math::double2int_rn (From x)
template<typename To = int, typename From = double>
To sycl::_V1::ext::intel::math::double2int_ru (From x)
template<typename To = int, typename From = double>
To sycl::_V1::ext::intel::math::double2int_rz (From x)
template<typename To = long long, typename From = double>
To sycl::_V1::ext::intel::math::double2ll_rd (From x)
template<typename To = long long, typename From = double>
To sycl::_V1::ext::intel::math::double2ll_rn (From x)
template<typename To = long long, typename From = double>
To sycl::_V1::ext::intel::math::double2ll_ru (From x)
template<typename To = long long, typename From = double>
To sycl::_V1::ext::intel::math::double2ll_rz (From x)
template<typename To = unsigned int, typename From = double>
To sycl::_V1::ext::intel::math::double2uint_rd (From x)
template<typename To = unsigned int, typename From = double>
To sycl::_V1::ext::intel::math::double2uint_rn (From x)
template<typename To = unsigned int, typename From = double>
To sycl::_V1::ext::intel::math::double2uint_ru (From x)
template<typename To = unsigned int, typename From = double>
To sycl::_V1::ext::intel::math::double2uint_rz (From x)
template<typename To = unsigned long long, typename From = double>
To sycl::_V1::ext::intel::math::double2ull_rd (From x)
template<typename To = unsigned long long, typename From = double>
To sycl::_V1::ext::intel::math::double2ull_rn (From x)
template<typename To = unsigned long long, typename From = double>
To sycl::_V1::ext::intel::math::double2ull_ru (From x)
template<typename To = unsigned long long, typename From = double>
To sycl::_V1::ext::intel::math::double2ull_rz (From x)
template<typename To = long long, typename From = double>
To sycl::_V1::ext::intel::math::double_as_longlong (From x)
template<typename To = double, typename From = long long>
To sycl::_V1::ext::intel::math::longlong_as_double (From x)
template<typename To = double, typename From = int>
To sycl::_V1::ext::intel::math::hiloint2double (From x, From y)
template<typename To = double, typename From = int>
To sycl::_V1::ext::intel::math::int2double_rn (From x)
template<typename To = double, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2double_rn (From x)
template<typename To = double, typename From = long long>
To sycl::_V1::ext::intel::math::ll2double_rd (From x)
template<typename To = double, typename From = long long>
To sycl::_V1::ext::intel::math::ll2double_rn (From x)
template<typename To = double, typename From = long long>
To sycl::_V1::ext::intel::math::ll2double_ru (From x)
template<typename To = double, typename From = long long>
To sycl::_V1::ext::intel::math::ll2double_rz (From x)
template<typename To = double, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2double_rd (From x)
template<typename To = double, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2double_rn (From x)
template<typename To = double, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2double_ru (From x)
template<typename To = double, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2double_rz (From x)
template<typename To = float, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2float (From x)
template<typename To = sycl::half, typename From = float>
To sycl::_V1::ext::intel::math::float2half_rn (From x)
template<typename To = sycl::half, typename From = float>
To sycl::_V1::ext::intel::math::float2half_rd (From x)
template<typename To = sycl::half, typename From = float>
To sycl::_V1::ext::intel::math::float2half_ru (From x)
template<typename To = sycl::half, typename From = float>
To sycl::_V1::ext::intel::math::float2half_rz (From x)
template<typename To = sycl::half, typename From = double>
To sycl::_V1::ext::intel::math::double2half (From x)
template<typename To = int, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2int_rn (From x)
template<typename To = int, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2int_rd (From x)
template<typename To = int, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2int_ru (From x)
template<typename To = int, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2int_rz (From x)
template<typename To = long long, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ll_rn (From x)
template<typename To = long long, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ll_rd (From x)
template<typename To = long long, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ll_ru (From x)
template<typename To = long long, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ll_rz (From x)
template<typename To = short, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2short_rn (From x)
template<typename To = short, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2short_rd (From x)
template<typename To = short, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2short_ru (From x)
template<typename To = short, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2short_rz (From x)
template<typename To = unsigned short, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ushort_rn (From x)
template<typename To = unsigned short, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ushort_rd (From x)
template<typename To = unsigned short, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ushort_ru (From x)
template<typename To = unsigned short, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ushort_rz (From x)
template<typename To = unsigned int, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2uint_rn (From x)
template<typename To = unsigned int, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2uint_rd (From x)
template<typename To = unsigned int, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2uint_ru (From x)
template<typename To = unsigned int, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2uint_rz (From x)
template<typename To = unsigned long long, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ull_rn (From x)
template<typename To = unsigned long long, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ull_rd (From x)
template<typename To = unsigned long long, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ull_ru (From x)
template<typename To = unsigned long long, typename From = sycl::half>
To sycl::_V1::ext::intel::math::half2ull_rz (From x)
template<typename To = sycl::half, typename From = int>
To sycl::_V1::ext::intel::math::int2half_rn (From x)
template<typename To = sycl::half, typename From = int>
To sycl::_V1::ext::intel::math::int2half_rd (From x)
template<typename To = sycl::half, typename From = int>
To sycl::_V1::ext::intel::math::int2half_ru (From x)
template<typename To = sycl::half, typename From = int>
To sycl::_V1::ext::intel::math::int2half_rz (From x)
template<typename To = sycl::half, typename From = short>
To sycl::_V1::ext::intel::math::short2half_rn (From x)
template<typename To = sycl::half, typename From = short>
To sycl::_V1::ext::intel::math::short2half_rd (From x)
template<typename To = sycl::half, typename From = short>
To sycl::_V1::ext::intel::math::short2half_ru (From x)
template<typename To = sycl::half, typename From = short>
To sycl::_V1::ext::intel::math::short2half_rz (From x)
template<typename To = sycl::half, typename From = long long>
To sycl::_V1::ext::intel::math::ll2half_rn (From x)
template<typename To = sycl::half, typename From = long long>
To sycl::_V1::ext::intel::math::ll2half_rd (From x)
template<typename To = sycl::half, typename From = long long>
To sycl::_V1::ext::intel::math::ll2half_ru (From x)
template<typename To = sycl::half, typename From = long long>
To sycl::_V1::ext::intel::math::ll2half_rz (From x)
template<typename To = sycl::half, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort2half_rn (From x)
template<typename To = sycl::half, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort2half_rd (From x)
template<typename To = sycl::half, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort2half_ru (From x)
template<typename To = sycl::half, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort2half_rz (From x)
template<typename To = sycl::half, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2half_rn (From x)
template<typename To = sycl::half, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2half_rd (From x)
template<typename To = sycl::half, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2half_ru (From x)
template<typename To = sycl::half, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2half_rz (From x)
template<typename To = sycl::half, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2half_rn (From x)
template<typename To = sycl::half, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2half_rd (From x)
template<typename To = sycl::half, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2half_ru (From x)
template<typename To = sycl::half, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2half_rz (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat16_as_ushort (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat16_as_short (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort_as_bfloat16 (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To sycl::_V1::ext::intel::math::short_as_bfloat16 (From x)
template<typename To = float, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162float (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To sycl::_V1::ext::intel::math::float2bfloat16 (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To sycl::_V1::ext::intel::math::float2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To sycl::_V1::ext::intel::math::float2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To sycl::_V1::ext::intel::math::float2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To sycl::_V1::ext::intel::math::float2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To sycl::_V1::ext::intel::math::ushort2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int>
To sycl::_V1::ext::intel::math::uint2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long>
To sycl::_V1::ext::intel::math::ull2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To sycl::_V1::ext::intel::math::short2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To sycl::_V1::ext::intel::math::short2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To sycl::_V1::ext::intel::math::short2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To sycl::_V1::ext::intel::math::short2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int>
To sycl::_V1::ext::intel::math::int2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int>
To sycl::_V1::ext::intel::math::int2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int>
To sycl::_V1::ext::intel::math::int2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int>
To sycl::_V1::ext::intel::math::int2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long>
To sycl::_V1::ext::intel::math::ll2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long>
To sycl::_V1::ext::intel::math::ll2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long>
To sycl::_V1::ext::intel::math::ll2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long>
To sycl::_V1::ext::intel::math::ll2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = double>
To sycl::_V1::ext::intel::math::double2bfloat16 (From x)
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162uint_rd (From x)
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162uint_rn (From x)
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162uint_ru (From x)
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162uint_rz (From x)
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162int_rd (From x)
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162int_rn (From x)
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162int_ru (From x)
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162int_rz (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ushort_rd (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ushort_rn (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ushort_ru (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ushort_rz (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162short_rd (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162short_rn (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162short_ru (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162short_rz (From x)
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ll_rd (From x)
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ll_rn (From x)
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ll_ru (From x)
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ll_rz (From x)
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ull_rd (From x)
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ull_rn (From x)
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ull_ru (From x)
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16>
To sycl::_V1::ext::intel::math::bfloat162ull_rz (From x)
Function Documentation
__imf_bfloat162float()
float __imf_bfloat162float (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162float().
__imf_bfloat162int_rd()
int __imf_bfloat162int_rd (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162int_rd().
__imf_bfloat162int_rn()
int __imf_bfloat162int_rn (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162int_rn().
__imf_bfloat162int_ru()
int __imf_bfloat162int_ru (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162int_ru().
__imf_bfloat162int_rz()
int __imf_bfloat162int_rz (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162int_rz().
__imf_bfloat162ll_rd()
long long __imf_bfloat162ll_rd (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ll_rd().
__imf_bfloat162ll_rn()
long long __imf_bfloat162ll_rn (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ll_rn().
__imf_bfloat162ll_ru()
long long __imf_bfloat162ll_ru (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ll_ru().
__imf_bfloat162ll_rz()
long long __imf_bfloat162ll_rz (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ll_rz().
__imf_bfloat162short_rd()
short __imf_bfloat162short_rd (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162short_rd().
__imf_bfloat162short_rn()
short __imf_bfloat162short_rn (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162short_rn().
__imf_bfloat162short_ru()
short __imf_bfloat162short_ru (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162short_ru().
__imf_bfloat162short_rz()
short __imf_bfloat162short_rz (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162short_rz().
__imf_bfloat162uint_rd()
unsigned int __imf_bfloat162uint_rd (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162uint_rd().
__imf_bfloat162uint_rn()
unsigned int __imf_bfloat162uint_rn (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162uint_rn().
__imf_bfloat162uint_ru()
unsigned int __imf_bfloat162uint_ru (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162uint_ru().
__imf_bfloat162uint_rz()
unsigned int __imf_bfloat162uint_rz (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162uint_rz().
__imf_bfloat162ull_rd()
unsigned long long __imf_bfloat162ull_rd (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ull_rd().
__imf_bfloat162ull_rn()
unsigned long long __imf_bfloat162ull_rn (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ull_rn().
__imf_bfloat162ull_ru()
unsigned long long __imf_bfloat162ull_ru (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ull_ru().
__imf_bfloat162ull_rz()
unsigned long long __imf_bfloat162ull_rz (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ull_rz().
__imf_bfloat162ushort_rd()
unsigned short __imf_bfloat162ushort_rd (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ushort_rd().
__imf_bfloat162ushort_rn()
unsigned short __imf_bfloat162ushort_rn (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ushort_rn().
__imf_bfloat162ushort_ru()
unsigned short __imf_bfloat162ushort_ru (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ushort_ru().
__imf_bfloat162ushort_rz()
unsigned short __imf_bfloat162ushort_rz (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat162ushort_rz().
__imf_bfloat16_as_short()
short __imf_bfloat16_as_short (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat16_as_short().
__imf_bfloat16_as_ushort()
unsigned short __imf_bfloat16_as_ushort (uint16_t)
Referenced by sycl::_V1::ext::intel::math::bfloat16_as_ushort().
__imf_double2bfloat16()
uint16_t __imf_double2bfloat16 (double)
Referenced by sycl::_V1::ext::intel::math::double2bfloat16().
__imf_double2float_rd()
float __imf_double2float_rd (double)
Referenced by sycl::_V1::ext::intel::math::double2float_rd().
__imf_double2float_rn()
float __imf_double2float_rn (double)
Referenced by sycl::_V1::ext::intel::math::double2float_rn().
__imf_double2float_ru()
float __imf_double2float_ru (double)
Referenced by sycl::_V1::ext::intel::math::double2float_ru().
__imf_double2float_rz()
float __imf_double2float_rz (double)
Referenced by sycl::_V1::ext::intel::math::double2float_rz().
__imf_double2half()
_iml_half_internal __imf_double2half (double)
Referenced by sycl::_V1::ext::intel::math::double2half().
__imf_double2hiint()
int __imf_double2hiint (double)
Referenced by sycl::_V1::ext::intel::math::double2hiint().
__imf_double2int_rd()
int __imf_double2int_rd (double)
Referenced by sycl::_V1::ext::intel::math::double2int_rd().
__imf_double2int_rn()
int __imf_double2int_rn (double)
Referenced by sycl::_V1::ext::intel::math::double2int_rn().
__imf_double2int_ru()
int __imf_double2int_ru (double)
Referenced by sycl::_V1::ext::intel::math::double2int_ru().
__imf_double2int_rz()
int __imf_double2int_rz (double)
Referenced by sycl::_V1::ext::intel::math::double2int_rz().
__imf_double2ll_rd()
long long __imf_double2ll_rd (double)
Referenced by sycl::_V1::ext::intel::math::double2ll_rd().
__imf_double2ll_rn()
long long __imf_double2ll_rn (double)
Referenced by sycl::_V1::ext::intel::math::double2ll_rn().
__imf_double2ll_ru()
long long __imf_double2ll_ru (double)
Referenced by sycl::_V1::ext::intel::math::double2ll_ru().
__imf_double2ll_rz()
long long __imf_double2ll_rz (double)
Referenced by sycl::_V1::ext::intel::math::double2ll_rz().
__imf_double2loint()
int __imf_double2loint (double)
Referenced by sycl::_V1::ext::intel::math::double2loint().
__imf_double2uint_rd()
unsigned int __imf_double2uint_rd (double)
Referenced by sycl::_V1::ext::intel::math::double2uint_rd().
__imf_double2uint_rn()
unsigned int __imf_double2uint_rn (double)
Referenced by sycl::_V1::ext::intel::math::double2uint_rn().
__imf_double2uint_ru()
unsigned int __imf_double2uint_ru (double)
Referenced by sycl::_V1::ext::intel::math::double2uint_ru().
__imf_double2uint_rz()
unsigned int __imf_double2uint_rz (double)
Referenced by sycl::_V1::ext::intel::math::double2uint_rz().
__imf_double2ull_rd()
unsigned long long __imf_double2ull_rd (double)
Referenced by sycl::_V1::ext::intel::math::double2ull_rd().
__imf_double2ull_rn()
unsigned long long __imf_double2ull_rn (double)
Referenced by sycl::_V1::ext::intel::math::double2ull_rn().
__imf_double2ull_ru()
unsigned long long __imf_double2ull_ru (double)
Referenced by sycl::_V1::ext::intel::math::double2ull_ru().
__imf_double2ull_rz()
unsigned long long __imf_double2ull_rz (double)
Referenced by sycl::_V1::ext::intel::math::double2ull_rz().
__imf_double_as_longlong()
long long __imf_double_as_longlong (double)
Referenced by sycl::_V1::ext::intel::math::double_as_longlong().
__imf_float2bfloat16()
uint16_t __imf_float2bfloat16 (float)
__imf_float2bfloat16_rd()
uint16_t __imf_float2bfloat16_rd (float)
Referenced by sycl::_V1::ext::intel::math::float2bfloat16_rd().
__imf_float2bfloat16_rn()
uint16_t __imf_float2bfloat16_rn (float)
Referenced by sycl::_V1::ext::intel::math::float2bfloat16(), and sycl::_V1::ext::intel::math::float2bfloat16_rn().
__imf_float2bfloat16_ru()
uint16_t __imf_float2bfloat16_ru (float)
Referenced by sycl::_V1::ext::intel::math::float2bfloat16_ru().
__imf_float2bfloat16_rz()
uint16_t __imf_float2bfloat16_rz (float)
Referenced by sycl::_V1::ext::intel::math::float2bfloat16_rz().
__imf_float2half_rd()
_iml_half_internal __imf_float2half_rd (float)
Referenced by sycl::_V1::ext::intel::math::float2half_rd().
__imf_float2half_rn()
_iml_half_internal __imf_float2half_rn (float)
Referenced by sycl::_V1::ext::intel::math::float2half_rn().
__imf_float2half_ru()
_iml_half_internal __imf_float2half_ru (float)
Referenced by sycl::_V1::ext::intel::math::float2half_ru().
__imf_float2half_rz()
_iml_half_internal __imf_float2half_rz (float)
Referenced by sycl::_V1::ext::intel::math::float2half_rz().
__imf_float2int_rd()
int __imf_float2int_rd (float)
Referenced by sycl::_V1::ext::intel::math::float2int_rd().
__imf_float2int_rn()
int __imf_float2int_rn (float)
Referenced by sycl::_V1::ext::intel::math::float2int_rn().
__imf_float2int_ru()
int __imf_float2int_ru (float)
Referenced by sycl::_V1::ext::intel::math::float2int_ru().
__imf_float2int_rz()
int __imf_float2int_rz (float)
Referenced by sycl::_V1::ext::intel::math::float2int_rz().
__imf_float2ll_rd()
long long int __imf_float2ll_rd (float)
Referenced by sycl::_V1::ext::intel::math::float2ll_rd().
__imf_float2ll_rn()
long long int __imf_float2ll_rn (float)
Referenced by sycl::_V1::ext::intel::math::float2ll_rn().
__imf_float2ll_ru()
long long int __imf_float2ll_ru (float)
Referenced by sycl::_V1::ext::intel::math::float2ll_ru().
__imf_float2ll_rz()
long long int __imf_float2ll_rz (float)
Referenced by sycl::_V1::ext::intel::math::float2ll_rz().
__imf_float2uint_rd()
unsigned int __imf_float2uint_rd (float)
Referenced by sycl::_V1::ext::intel::math::float2uint_rd().
__imf_float2uint_rn()
unsigned int __imf_float2uint_rn (float)
Referenced by sycl::_V1::ext::intel::math::float2uint_rn().
__imf_float2uint_ru()
unsigned int __imf_float2uint_ru (float)
Referenced by sycl::_V1::ext::intel::math::float2uint_ru().
__imf_float2uint_rz()
unsigned int __imf_float2uint_rz (float)
Referenced by sycl::_V1::ext::intel::math::float2uint_rz().
__imf_float2ull_rd()
unsigned long long int __imf_float2ull_rd (float)
Referenced by sycl::_V1::ext::intel::math::float2ull_rd().
__imf_float2ull_rn()
unsigned long long int __imf_float2ull_rn (float)
Referenced by sycl::_V1::ext::intel::math::float2ull_rn().
__imf_float2ull_ru()
unsigned long long int __imf_float2ull_ru (float)
Referenced by sycl::_V1::ext::intel::math::float2ull_ru().
__imf_float2ull_rz()
unsigned long long int __imf_float2ull_rz (float)
Referenced by sycl::_V1::ext::intel::math::float2ull_rz().
__imf_float_as_int()
int __imf_float_as_int (float)
Referenced by sycl::_V1::ext::intel::math::float_as_int().
__imf_float_as_uint()
unsigned int __imf_float_as_uint (float)
Referenced by sycl::_V1::ext::intel::math::float_as_uint().
__imf_half2float()
float __imf_half2float (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2float().
__imf_half2int_rd()
int __imf_half2int_rd (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2int_rd().
__imf_half2int_rn()
int __imf_half2int_rn (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2int_rn().
__imf_half2int_ru()
int __imf_half2int_ru (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2int_ru().
__imf_half2int_rz()
int __imf_half2int_rz (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2int_rz().
__imf_half2ll_rd()
long long __imf_half2ll_rd (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ll_rd().
__imf_half2ll_rn()
long long __imf_half2ll_rn (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ll_rn().
__imf_half2ll_ru()
long long __imf_half2ll_ru (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ll_ru().
__imf_half2ll_rz()
long long __imf_half2ll_rz (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ll_rz().
__imf_half2short_rd()
short __imf_half2short_rd (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2short_rd().
__imf_half2short_rn()
short __imf_half2short_rn (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2short_rn().
__imf_half2short_ru()
short __imf_half2short_ru (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2short_ru().
__imf_half2short_rz()
short __imf_half2short_rz (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2short_rz().
__imf_half2uint_rd()
unsigned int __imf_half2uint_rd (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2uint_rd().
__imf_half2uint_rn()
unsigned int __imf_half2uint_rn (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2uint_rn().
__imf_half2uint_ru()
unsigned int __imf_half2uint_ru (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2uint_ru().
__imf_half2uint_rz()
unsigned int __imf_half2uint_rz (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2uint_rz().
__imf_half2ull_rd()
unsigned long long __imf_half2ull_rd (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ull_rd().
__imf_half2ull_rn()
unsigned long long __imf_half2ull_rn (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ull_rn().
__imf_half2ull_ru()
unsigned long long __imf_half2ull_ru (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ull_ru().
__imf_half2ull_rz()
unsigned long long __imf_half2ull_rz (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ull_rz().
__imf_half2ushort_rd()
unsigned short __imf_half2ushort_rd (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ushort_rd().
__imf_half2ushort_rn()
unsigned short __imf_half2ushort_rn (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ushort_rn().
__imf_half2ushort_ru()
unsigned short __imf_half2ushort_ru (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ushort_ru().
__imf_half2ushort_rz()
unsigned short __imf_half2ushort_rz (_iml_half_internal)
Referenced by sycl::_V1::ext::intel::math::half2ushort_rz().
__imf_half_as_short()
short __imf_half_as_short (_iml_half_internal)
__imf_half_as_ushort()
unsigned short __imf_half_as_ushort (_iml_half_internal)
__imf_hiloint2double()
double __imf_hiloint2double (int , int)
Referenced by sycl::_V1::ext::intel::math::hiloint2double().
__imf_int2bfloat16_rd()
uint16_t __imf_int2bfloat16_rd (int)
Referenced by sycl::_V1::ext::intel::math::int2bfloat16_rd().
__imf_int2bfloat16_rn()
uint16_t __imf_int2bfloat16_rn (int)
Referenced by sycl::_V1::ext::intel::math::int2bfloat16_rn().
__imf_int2bfloat16_ru()
uint16_t __imf_int2bfloat16_ru (int)
Referenced by sycl::_V1::ext::intel::math::int2bfloat16_ru().
__imf_int2bfloat16_rz()
uint16_t __imf_int2bfloat16_rz (int)
Referenced by sycl::_V1::ext::intel::math::int2bfloat16_rz().
__imf_int2double_rn()
double __imf_int2double_rn (int)
Referenced by sycl::_V1::ext::intel::math::int2double_rn().
__imf_int2float_rd()
float __imf_int2float_rd (int)
Referenced by sycl::_V1::ext::intel::math::int2float_rd().
__imf_int2float_rn()
float __imf_int2float_rn (int)
Referenced by sycl::_V1::ext::intel::math::int2float_rn().
__imf_int2float_ru()
float __imf_int2float_ru (int)
Referenced by sycl::_V1::ext::intel::math::int2float_ru().
__imf_int2float_rz()
float __imf_int2float_rz (int)
Referenced by sycl::_V1::ext::intel::math::int2float_rz().
__imf_int2half_rd()
_iml_half_internal __imf_int2half_rd (int)
Referenced by sycl::_V1::ext::intel::math::int2half_rd().
__imf_int2half_rn()
_iml_half_internal __imf_int2half_rn (int)
Referenced by sycl::_V1::ext::intel::math::int2half_rn().
__imf_int2half_ru()
_iml_half_internal __imf_int2half_ru (int)
Referenced by sycl::_V1::ext::intel::math::int2half_ru().
__imf_int2half_rz()
_iml_half_internal __imf_int2half_rz (int)
Referenced by sycl::_V1::ext::intel::math::int2half_rz().
__imf_int_as_float()
float __imf_int_as_float (int)
Referenced by sycl::_V1::ext::intel::math::int_as_float().
__imf_ll2bfloat16_rd()
uint16_t __imf_ll2bfloat16_rd (long long)
Referenced by sycl::_V1::ext::intel::math::ll2bfloat16_rd().
__imf_ll2bfloat16_rn()
uint16_t __imf_ll2bfloat16_rn (long long)
Referenced by sycl::_V1::ext::intel::math::ll2bfloat16_rn().
__imf_ll2bfloat16_ru()
uint16_t __imf_ll2bfloat16_ru (long long)
Referenced by sycl::_V1::ext::intel::math::ll2bfloat16_ru().
__imf_ll2bfloat16_rz()
uint16_t __imf_ll2bfloat16_rz (long long)
Referenced by sycl::_V1::ext::intel::math::ll2bfloat16_rz().
__imf_ll2double_rd()
double __imf_ll2double_rd (long long)
Referenced by sycl::_V1::ext::intel::math::ll2double_rd().
__imf_ll2double_rn()
double __imf_ll2double_rn (long long)
Referenced by sycl::_V1::ext::intel::math::ll2double_rn().
__imf_ll2double_ru()
double __imf_ll2double_ru (long long)
Referenced by sycl::_V1::ext::intel::math::ll2double_ru().
__imf_ll2double_rz()
double __imf_ll2double_rz (long long)
Referenced by sycl::_V1::ext::intel::math::ll2double_rz().
__imf_ll2float_rd()
float __imf_ll2float_rd (long long int)
Referenced by sycl::_V1::ext::intel::math::ll2float_rd().
__imf_ll2float_rn()
float __imf_ll2float_rn (long long int)
Referenced by sycl::_V1::ext::intel::math::ll2float_rn().
__imf_ll2float_ru()
float __imf_ll2float_ru (long long int)
Referenced by sycl::_V1::ext::intel::math::ll2float_ru().
__imf_ll2float_rz()
float __imf_ll2float_rz (long long int)
Referenced by sycl::_V1::ext::intel::math::ll2float_rz().
__imf_ll2half_rd()
_iml_half_internal __imf_ll2half_rd (long long)
Referenced by sycl::_V1::ext::intel::math::ll2half_rd().
__imf_ll2half_rn()
_iml_half_internal __imf_ll2half_rn (long long)
Referenced by sycl::_V1::ext::intel::math::ll2half_rn().
__imf_ll2half_ru()
_iml_half_internal __imf_ll2half_ru (long long)
Referenced by sycl::_V1::ext::intel::math::ll2half_ru().
__imf_ll2half_rz()
_iml_half_internal __imf_ll2half_rz (long long)
Referenced by sycl::_V1::ext::intel::math::ll2half_rz().
__imf_longlong_as_double()
double __imf_longlong_as_double (long long)
Referenced by sycl::_V1::ext::intel::math::longlong_as_double().
__imf_short2bfloat16_rd()
uint16_t __imf_short2bfloat16_rd (short)
Referenced by sycl::_V1::ext::intel::math::short2bfloat16_rd().
__imf_short2bfloat16_rn()
uint16_t __imf_short2bfloat16_rn (short)
Referenced by sycl::_V1::ext::intel::math::short2bfloat16_rn().
__imf_short2bfloat16_ru()
uint16_t __imf_short2bfloat16_ru (short)
Referenced by sycl::_V1::ext::intel::math::short2bfloat16_ru().
__imf_short2bfloat16_rz()
uint16_t __imf_short2bfloat16_rz (short)
Referenced by sycl::_V1::ext::intel::math::short2bfloat16_rz().
__imf_short2half_rd()
_iml_half_internal __imf_short2half_rd (short)
Referenced by sycl::_V1::ext::intel::math::short2half_rd().
__imf_short2half_rn()
_iml_half_internal __imf_short2half_rn (short)
Referenced by sycl::_V1::ext::intel::math::short2half_rn().
__imf_short2half_ru()
_iml_half_internal __imf_short2half_ru (short)
Referenced by sycl::_V1::ext::intel::math::short2half_ru().
__imf_short2half_rz()
_iml_half_internal __imf_short2half_rz (short)
Referenced by sycl::_V1::ext::intel::math::short2half_rz().
__imf_short_as_bfloat16()
uint16_t __imf_short_as_bfloat16 (short)
Referenced by sycl::_V1::ext::intel::math::short_as_bfloat16().
__imf_short_as_half()
_iml_half_internal __imf_short_as_half (short)
__imf_uint2bfloat16_rd()
uint16_t __imf_uint2bfloat16_rd (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2bfloat16_rd().
__imf_uint2bfloat16_rn()
uint16_t __imf_uint2bfloat16_rn (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2bfloat16_rn().
__imf_uint2bfloat16_ru()
uint16_t __imf_uint2bfloat16_ru (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2bfloat16_ru().
__imf_uint2bfloat16_rz()
uint16_t __imf_uint2bfloat16_rz (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2bfloat16_rz().
__imf_uint2double_rn()
double __imf_uint2double_rn (unsigned)
Referenced by sycl::_V1::ext::intel::math::uint2double_rn().
__imf_uint2float_rd()
float __imf_uint2float_rd (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2float_rd().
__imf_uint2float_rn()
float __imf_uint2float_rn (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2float_rn().
__imf_uint2float_ru()
float __imf_uint2float_ru (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2float_ru().
__imf_uint2float_rz()
float __imf_uint2float_rz (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2float_rz().
__imf_uint2half_rd()
_iml_half_internal __imf_uint2half_rd (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2half_rd().
__imf_uint2half_rn()
_iml_half_internal __imf_uint2half_rn (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2half_rn().
__imf_uint2half_ru()
_iml_half_internal __imf_uint2half_ru (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2half_ru().
__imf_uint2half_rz()
_iml_half_internal __imf_uint2half_rz (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint2half_rz().
__imf_uint_as_float()
float __imf_uint_as_float (unsigned int)
Referenced by sycl::_V1::ext::intel::math::uint_as_float().
__imf_ull2bfloat16_rd()
uint16_t __imf_ull2bfloat16_rd (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2bfloat16_rd().
__imf_ull2bfloat16_rn()
uint16_t __imf_ull2bfloat16_rn (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2bfloat16_rn().
__imf_ull2bfloat16_ru()
uint16_t __imf_ull2bfloat16_ru (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2bfloat16_ru().
__imf_ull2bfloat16_rz()
uint16_t __imf_ull2bfloat16_rz (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2bfloat16_rz().
__imf_ull2double_rd()
double __imf_ull2double_rd (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2double_rd().
__imf_ull2double_rn()
double __imf_ull2double_rn (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2double_rn().
__imf_ull2double_ru()
double __imf_ull2double_ru (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2double_ru().
__imf_ull2double_rz()
double __imf_ull2double_rz (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2double_rz().
__imf_ull2float_rd()
float __imf_ull2float_rd (unsigned long long int)
Referenced by sycl::_V1::ext::intel::math::ull2float_rd().
__imf_ull2float_rn()
float __imf_ull2float_rn (unsigned long long int)
Referenced by sycl::_V1::ext::intel::math::ull2float_rn().
__imf_ull2float_ru()
float __imf_ull2float_ru (unsigned long long int)
Referenced by sycl::_V1::ext::intel::math::ull2float_ru().
__imf_ull2float_rz()
float __imf_ull2float_rz (unsigned long long int)
Referenced by sycl::_V1::ext::intel::math::ull2float_rz().
__imf_ull2half_rd()
_iml_half_internal __imf_ull2half_rd (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2half_rd().
__imf_ull2half_rn()
_iml_half_internal __imf_ull2half_rn (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2half_rn().
__imf_ull2half_ru()
_iml_half_internal __imf_ull2half_ru (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2half_ru().
__imf_ull2half_rz()
_iml_half_internal __imf_ull2half_rz (unsigned long long)
Referenced by sycl::_V1::ext::intel::math::ull2half_rz().
__imf_ushort2bfloat16_rd()
uint16_t __imf_ushort2bfloat16_rd (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort2bfloat16_rd().
__imf_ushort2bfloat16_rn()
uint16_t __imf_ushort2bfloat16_rn (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort2bfloat16_rn().
__imf_ushort2bfloat16_ru()
uint16_t __imf_ushort2bfloat16_ru (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort2bfloat16_ru().
__imf_ushort2bfloat16_rz()
uint16_t __imf_ushort2bfloat16_rz (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort2bfloat16_rz().
__imf_ushort2half_rd()
_iml_half_internal __imf_ushort2half_rd (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort2half_rd().
__imf_ushort2half_rn()
_iml_half_internal __imf_ushort2half_rn (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort2half_rn().
__imf_ushort2half_ru()
_iml_half_internal __imf_ushort2half_ru (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort2half_ru().
__imf_ushort2half_rz()
_iml_half_internal __imf_ushort2half_rz (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort2half_rz().
__imf_ushort_as_bfloat16()
uint16_t __imf_ushort_as_bfloat16 (unsigned short)
Referenced by sycl::_V1::ext::intel::math::ushort_as_bfloat16().
__imf_ushort_as_half()
_iml_half_internal __imf_ushort_as_half (unsigned short)