DPC++ Runtime: include/sycl/ext/intel/experimental/esimd/detail/intrin.hpp File Reference
intrin.hpp File Reference
#include <sycl/ext/intel/experimental/esimd/common.hpp>
#include <sycl/ext/intel/experimental/esimd/detail/types.hpp>
#include <sycl/ext/intel/experimental/esimd/detail/util.hpp>
#include <assert.h>
#include <cstdint>
Namespaces
cl
We provide new interfaces for matrix muliply in this patch:
cl::sycl
cl::sycl::ext
cl::sycl::ext::intel
cl::sycl::ext::intel::experimental
cl::sycl::ext::intel::experimental::esimd
cl::sycl::ext::intel::experimental::esimd::detail
Macros
#define __SEIEED sycl::ext::intel::experimental::esimd::detail
#define __SEIEE sycl::ext::intel::experimental::esimd
Functions
template<typename T , int N, int M, int VStride, int Width, int Stride, int ParentWidth = 0>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, M > __esimd_rdregion (__SEIEED::vector_type_t< T, N > Input, uint16_t Offset)
template<typename T , int N, int M, int ParentWidth = 0>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, M > __esimd_rdindirect (__SEIEED::vector_type_t< T, N > Input, __SEIEED::vector_type_t< uint16_t, M > Offset)
template<typename T , int N, int M, int VStride, int Width, int Stride, int ParentWidth = 0>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, N > __esimd_wrregion (__SEIEED::vector_type_t< T, N > OldVal, __SEIEED::vector_type_t< T, M > NewVal, uint16_t Offset, __SEIEE::mask_type_t< M > Mask=1)
template<typename T , int N, int M, int ParentWidth = 0>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, N > __esimd_wrindirect (__SEIEED::vector_type_t< T, N > OldVal, __SEIEED::vector_type_t< T, M > NewVal, __SEIEED::vector_type_t< uint16_t, M > Offset, __SEIEE::mask_type_t< M > Mask=1)
template<typename BT , int BN, typename RTy >
__SEIEED::vector_type_t< typename RTy::element_type, RTy::length > ESIMD_INLINE cl::sycl::ext::intel::experimental::esimd::detail::readRegion (const __SEIEED::vector_type_t< BT, BN > &Base, RTy Region)
read from a basic region of a vector, return a vector
template<typename BT , int BN, typename T , typename U >
ESIMD_INLINE __SEIEED::vector_type_t< typename T::element_type, T::length > cl::sycl::ext::intel::experimental::esimd::detail::readRegion (const __SEIEED::vector_type_t< BT, BN > &Base, std::pair< T, U > Region)
read from a nested region of a vector, return a vector
template<typename T , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, N > __esimd_vload (const __SEIEED::vector_type_t< T, N > *ptr)
template<typename T , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_vstore (__SEIEED::vector_type_t< T, N > *ptr, __SEIEED::vector_type_t< T, N > vals)
template<typename T , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint16_t __esimd_any (__SEIEED::vector_type_t< T, N > src)
template<typename T , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint16_t __esimd_all (__SEIEED::vector_type_t< T, N > src)
Macro Definition Documentation
__SEIEE
#define __SEIEE sycl::ext::intel::experimental::esimd
Definition at line 22 of file intrin.hpp.
__SEIEED
#define __SEIEED sycl::ext::intel::experimental::esimd::detail
Definition at line 21 of file intrin.hpp.
Function Documentation
__esimd_all()
template<typename T , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint16_t __esimd_all (__SEIEED::vector_type_t< T, N > src)
__esimd_any()
template<typename T , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint16_t __esimd_any (__SEIEED::vector_type_t< T, N > src)
__esimd_rdindirect()
template<typename T , int N, int M, int ParentWidth = 0> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, M > __esimd_rdindirect (__SEIEED::vector_type_t< T, N > Input, __SEIEED::vector_type_t< uint16_t, M > Offset)
Definition at line 272 of file intrin.hpp.
__esimd_rdregion()
template<typename T , int N, int M, int VStride, int Width, int Stride, int ParentWidth = 0> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, M > __esimd_rdregion (__SEIEED::vector_type_t< T, N > Input, uint16_t Offset)
Definition at line 253 of file intrin.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::gather(), cl::sycl::ext::intel::experimental::esimd::detail::readRegion(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select().
__esimd_vload()
template<typename T , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, N> __esimd_vload (const __SEIEED::vector_type_t< T, N > * ptr)
__esimd_vstore()
template<typename T , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_vstore (__SEIEED::vector_type_t< T, N > * ptr, __SEIEED::vector_type_t< T, N > vals)
__esimd_wrindirect()
template<typename T , int N, int M, int ParentWidth = 0> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, N > __esimd_wrindirect (__SEIEED::vector_type_t< T, N > OldVal, __SEIEED::vector_type_t< T, M > NewVal, __SEIEED::vector_type_t< uint16_t, M > Offset, __SEIEE::mask_type_t< M > Mask = 1)
Definition at line 310 of file intrin.hpp.
__esimd_wrregion()
template<typename T , int N, int M, int VStride, int Width, int Stride, int ParentWidth = 0> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, N > __esimd_wrregion (__SEIEED::vector_type_t< T, N > OldVal, __SEIEED::vector_type_t< T, M > NewVal, uint16_t Offset, __SEIEE::mask_type_t< M > Mask = 1)
Definition at line 287 of file intrin.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::scatter(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::writeRegion().