DPC++ Runtime: include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp File Reference
math_intrin.hpp File Reference
#include <sycl/ext/intel/experimental/esimd/common.hpp>
#include <sycl/ext/intel/experimental/esimd/detail/host_util.hpp>
#include <sycl/ext/intel/experimental/esimd/detail/types.hpp>
#include <cstdint>
Macros
#define __SEIEED sycl::ext::intel::experimental::esimd::detail
#define __SEIEEED sycl::ext::intel::experimental::esimd::emu::detail
Functions
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_satf (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_fptoui_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_fptosi_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_uutrunc_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_ustrunc_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_sutrunc_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_sstrunc_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_abs (__SEIEED::vector_type_t< T, SZ > src0)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_ssshl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_sushl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_usshl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_uushl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_ssshl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_sushl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_usshl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_uushl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_rol (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_ror (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_umulh (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_smulh (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_frc (__SEIEED::vector_type_t< float, SZ > src0)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_fmax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
3 kinds of max
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_umax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_smax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_lzd (__SEIEED::vector_type_t< T, SZ > src0)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_fmin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
3 kinds of min
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_umin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T, SZ > __esimd_smin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T0 , typename T1 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_bfrev (__SEIEED::vector_type_t< T1, SZ > src0)
template<typename T , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< unsigned int, SZ > __esimd_cbit (__SEIEED::vector_type_t< T, SZ > src0)
template<typename T0 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_bfins (__SEIEED::vector_type_t< T0, SZ > src0, __SEIEED::vector_type_t< T0, SZ > src1, __SEIEED::vector_type_t< T0, SZ > src2, __SEIEED::vector_type_t< T0, SZ > src3)
template<typename T0 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T0, SZ > __esimd_bfext (__SEIEED::vector_type_t< T0, SZ > src0, __SEIEED::vector_type_t< T0, SZ > src1, __SEIEED::vector_type_t< T0, SZ > src2)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< uint32_t, SZ > __esimd_fbl (__SEIEED::vector_type_t< uint32_t, SZ > src0)
template<typename T0 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< int, SZ > __esimd_sfbh (__SEIEED::vector_type_t< T0, SZ > src0)
template<typename T0 , int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< uint32_t, SZ > __esimd_ufbh (__SEIEED::vector_type_t< T0, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_inv (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_log (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_exp (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_sqrt (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_sqrt_ieee (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_rsqrt (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_sin (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_cos (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_pow (__SEIEED::vector_type_t< float, SZ > src0, __SEIEED::vector_type_t< float, SZ > src1)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_div_ieee (__SEIEED::vector_type_t< float, SZ > src0, __SEIEED::vector_type_t< float, SZ > src1)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_rndd (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_rndu (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_rnde (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< float, SZ > __esimd_rndz (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< double, SZ > __esimd_sqrt_ieee (__SEIEED::vector_type_t< double, SZ > src0)
template<int SZ>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< double, SZ > __esimd_div_ieee (__SEIEED::vector_type_t< double, SZ > src0, __SEIEED::vector_type_t< double, SZ > src1)
template<int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint32_t __esimd_pack_mask (__SEIEED::vector_type_t< uint16_t, N > src0)
template<int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< uint16_t, N > __esimd_unpack_mask (uint32_t src0)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T1, N > __esimd_uudp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T1, N > __esimd_usdp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T1, N > __esimd_sudp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T1, N > __esimd_ssdp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T1, N > __esimd_uudp4a_sat (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T1, N > __esimd_usdp4a_sat (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T1, N > __esimd_sudp4a_sat (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< T1, N > __esimd_ssdp4a_sat (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_reduced_fmax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_reduced_umax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_reduced_smax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_reduced_fmin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_reduced_umin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __esimd_reduced_smin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_dp4 (__SEIEED::vector_type_t< Ty, N > v1, __SEIEED::vector_type_t< Ty, N > v2)
template<typename T >
T extract (const uint32_t &width, const uint32_t &offset, uint32_t src, const uint32_t &sign_extend)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_satf (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_fptoui_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_fptosi_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_uutrunc_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_ustrunc_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_sutrunc_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_sstrunc_sat (__SEIEED::vector_type_t< T1, SZ > src)
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_abs (__SEIEED::vector_type_t< T, SZ > src0)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_ssshl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_sushl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_usshl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_uushl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_ssshl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_sushl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_usshl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_uushl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_rol (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_ror (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1)
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_umulh (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_smulh (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_frc (__SEIEED::vector_type_t< float, SZ > src0)
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_fmax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
3 kinds of max
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_umax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_smax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_lzd (__SEIEED::vector_type_t< T, SZ > src0)
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_fmin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
3 kinds of min
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_umin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T , int SZ>
__SEIEED::vector_type_t< T, SZ > __esimd_smin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1)
template<typename T0 , typename T1 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_bfrev (__SEIEED::vector_type_t< T1, SZ > src0)
template<typename T , int SZ>
__SEIEED::vector_type_t< unsigned int, SZ > __esimd_cbit (__SEIEED::vector_type_t< T, SZ > src0)
template<typename T0 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_bfins (__SEIEED::vector_type_t< T0, SZ > width, __SEIEED::vector_type_t< T0, SZ > offset, __SEIEED::vector_type_t< T0, SZ > val, __SEIEED::vector_type_t< T0, SZ > src)
template<typename T0 , int SZ>
__SEIEED::vector_type_t< T0, SZ > __esimd_bfext (__SEIEED::vector_type_t< T0, SZ > width, __SEIEED::vector_type_t< T0, SZ > offset, __SEIEED::vector_type_t< T0, SZ > src)
template<int SZ>
__SEIEED::vector_type_t< uint32_t, SZ > __esimd_fbl (__SEIEED::vector_type_t< uint32_t, SZ > src0)
template<typename T0 , int SZ>
__SEIEED::vector_type_t< int, SZ > __esimd_sfbh (__SEIEED::vector_type_t< T0, SZ > src0)
template<typename T0 , int SZ>
__SEIEED::vector_type_t< uint32_t, SZ > __esimd_ufbh (__SEIEED::vector_type_t< T0, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_inv (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_log (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_exp (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_sqrt (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_sqrt_ieee (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_rsqrt (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_sin (__SEIEED::vector_type_t< float, SZ > src)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_cos (__SEIEED::vector_type_t< float, SZ > src)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_pow (__SEIEED::vector_type_t< float, SZ > src0, __SEIEED::vector_type_t< float, SZ > src1)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_div_ieee (__SEIEED::vector_type_t< float, SZ > src0, __SEIEED::vector_type_t< float, SZ > src1)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_rndd (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_rndu (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_rnde (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< float, SZ > __esimd_rndz (__SEIEED::vector_type_t< float, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< double, SZ > __esimd_sqrt_ieee (__SEIEED::vector_type_t< double, SZ > src0)
template<int SZ>
__SEIEED::vector_type_t< double, SZ > __esimd_div_ieee (__SEIEED::vector_type_t< double, SZ > src0, __SEIEED::vector_type_t< double, SZ > src1)
template<int N>
uint32_t __esimd_pack_mask (__SEIEED::vector_type_t< uint16_t, N > src0)
template<int N>
__SEIEED::vector_type_t< uint16_t, N > __esimd_unpack_mask (uint32_t src0)
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
__SEIEED::vector_type_t< T1, N > __esimd_dp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_reduced_max (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_reduced_fmax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_reduced_umax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_reduced_smax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_reduced_min (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_reduced_fmin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_reduced_umin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_reduced_smin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2)
Macro Definition Documentation
__SEIEED
#define __SEIEED sycl::ext::intel::experimental::esimd::detail
Definition at line 20 of file math_intrin.hpp.
__SEIEEED
#define __SEIEEED sycl::ext::intel::experimental::esimd::emu::detail
Definition at line 336 of file math_intrin.hpp.
Function Documentation
__esimd_abs() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_abs (__SEIEED::vector_type_t< T, SZ > src0) inline
Definition at line 417 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_abs() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_abs (__SEIEED::vector_type_t< T, SZ > src0) inline
Definition at line 417 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfext() [1/2]
template<typename T0 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_bfext (__SEIEED::vector_type_t< T0, SZ > src0, __SEIEED::vector_type_t< T0, SZ > src1, __SEIEED::vector_type_t< T0, SZ > src2) inline
Definition at line 819 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfext() [2/2]
template<typename T0 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_bfext (__SEIEED::vector_type_t< T0, SZ > width, __SEIEED::vector_type_t< T0, SZ > offset, __SEIEED::vector_type_t< T0, SZ > src) inline
Definition at line 819 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfins() [1/2]
template<typename T0 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_bfins (__SEIEED::vector_type_t< T0, SZ > src0, __SEIEED::vector_type_t< T0, SZ > src1, __SEIEED::vector_type_t< T0, SZ > src2, __SEIEED::vector_type_t< T0, SZ > src3) inline
Definition at line 793 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfins() [2/2]
template<typename T0 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_bfins (__SEIEED::vector_type_t< T0, SZ > width, __SEIEED::vector_type_t< T0, SZ > offset, __SEIEED::vector_type_t< T0, SZ > val, __SEIEED::vector_type_t< T0, SZ > src) inline
Definition at line 793 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfrev() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_bfrev (__SEIEED::vector_type_t< T1, SZ > src0) inline
Definition at line 745 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_bfrev() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_bfrev (__SEIEED::vector_type_t< T1, SZ > src0) inline
Definition at line 745 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_cbit() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<unsigned int, SZ> __esimd_cbit (__SEIEED::vector_type_t< T, SZ > src0) inline
Definition at line 770 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_cbit() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<unsigned int, SZ> __esimd_cbit (__SEIEED::vector_type_t< T, SZ > src0) inline
Definition at line 770 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_cos() [1/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_cos (__SEIEED::vector_type_t< float, SZ > src) inline
Definition at line 996 of file math_intrin.hpp.
References cl::sycl::cos(), and SIMDCF_ELEMENT_SKIP.
__esimd_cos() [2/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_cos (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 996 of file math_intrin.hpp.
References cl::sycl::cos(), and SIMDCF_ELEMENT_SKIP.
__esimd_div_ieee() [1/4]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<double, SZ> __esimd_div_ieee (__SEIEED::vector_type_t< double, SZ > src0, __SEIEED::vector_type_t< double, SZ > src1) inline
Handle Divide-by-zero
Definition at line 1124 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_div_ieee() [2/4]
template<int SZ> __SEIEED::vector_type_t<double, SZ> __esimd_div_ieee (__SEIEED::vector_type_t< double, SZ > src0, __SEIEED::vector_type_t< double, SZ > src1) inline
Handle Divide-by-zero
Definition at line 1124 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_div_ieee() [3/4]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_div_ieee (__SEIEED::vector_type_t< float, SZ > src0, __SEIEED::vector_type_t< float, SZ > src1) inline
Handle Divide-by-zero
Definition at line 1019 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_div_ieee() [4/4]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_div_ieee (__SEIEED::vector_type_t< float, SZ > src0, __SEIEED::vector_type_t< float, SZ > src1) inline
Handle Divide-by-zero
Definition at line 1019 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_dp4()
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_dp4 (__SEIEED::vector_type_t< Ty, N > v1, __SEIEED::vector_type_t< Ty, N > v2) inline
Definition at line 809 of file memory_intrin.hpp.
__esimd_dp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> __SEIEED::vector_type_t<T1, N> __esimd_dp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2) inline
Definition at line 1171 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_exp() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_exp (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 942 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_exp() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_exp (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 942 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fbl() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<uint32_t, SZ> __esimd_fbl (__SEIEED::vector_type_t< uint32_t, SZ > src0) inline
Definition at line 838 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_fbl().
__esimd_fbl() [2/2]
template<int SZ> __SEIEED::vector_type_t<uint32_t, SZ> __esimd_fbl (__SEIEED::vector_type_t< uint32_t, SZ > src0) inline
Definition at line 838 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_fbl().
__esimd_fmax() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_fmax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
3 kinds of max
Definition at line 611 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fmax() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_fmax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
3 kinds of max
Definition at line 611 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fmin() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_fmin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
3 kinds of min
Definition at line 688 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fmin() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_fmin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
3 kinds of min
Definition at line 688 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fptosi_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_fptosi_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 362 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fptosi_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_fptosi_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 362 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fptoui_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_fptoui_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 351 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_fptoui_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_fptoui_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 351 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_frc() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_frc (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 599 of file math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_frc().
__esimd_frc() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_frc (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 599 of file math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_frc().
__esimd_inv() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_inv (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 919 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_inv() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_inv (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 919 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_log() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_log (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 931 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_log() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_log (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 931 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_lzd() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_lzd (__SEIEED::vector_type_t< T, SZ > src0) inline
Definition at line 666 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_lzd() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_lzd (__SEIEED::vector_type_t< T, SZ > src0) inline
Definition at line 666 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_pack_mask() [1/2]
template<int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint32_t __esimd_pack_mask (__SEIEED::vector_type_t< uint16_t, N > src0) inline
Definition at line 1143 of file math_intrin.hpp.
__esimd_pack_mask() [2/2]
template<int N> uint32_t __esimd_pack_mask (__SEIEED::vector_type_t< uint16_t, N > src0) inline
Definition at line 1143 of file math_intrin.hpp.
__esimd_pow() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_pow (__SEIEED::vector_type_t< float, SZ > src0, __SEIEED::vector_type_t< float, SZ > src1) inline
Definition at line 1006 of file math_intrin.hpp.
References cl::sycl::fabs(), and SIMDCF_ELEMENT_SKIP.
__esimd_pow() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_pow (__SEIEED::vector_type_t< float, SZ > src0, __SEIEED::vector_type_t< float, SZ > src1) inline
Definition at line 1006 of file math_intrin.hpp.
References cl::sycl::fabs(), and SIMDCF_ELEMENT_SKIP.
__esimd_reduced_fmax() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_reduced_fmax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1223 of file math_intrin.hpp.
__esimd_reduced_fmax() [2/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_reduced_fmax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1223 of file math_intrin.hpp.
__esimd_reduced_fmin() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_reduced_fmin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1259 of file math_intrin.hpp.
__esimd_reduced_fmin() [2/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_reduced_fmin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1259 of file math_intrin.hpp.
__esimd_reduced_max()
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_reduced_max (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1208 of file math_intrin.hpp.
__esimd_reduced_min()
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_reduced_min (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1244 of file math_intrin.hpp.
__esimd_reduced_smax() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_reduced_smax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1237 of file math_intrin.hpp.
__esimd_reduced_smax() [2/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_reduced_smax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1237 of file math_intrin.hpp.
__esimd_reduced_smin() [1/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __esimd_reduced_smin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1273 of file math_intrin.hpp.
__esimd_reduced_smin() [2/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_reduced_smin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1273 of file math_intrin.hpp.
__esimd_reduced_umax() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_reduced_umax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1230 of file math_intrin.hpp.
__esimd_reduced_umax() [2/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_reduced_umax (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1230 of file math_intrin.hpp.
__esimd_reduced_umin() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_reduced_umin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1266 of file math_intrin.hpp.
__esimd_reduced_umin() [2/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_reduced_umin (__SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< Ty, N > src2) inline
Definition at line 1266 of file math_intrin.hpp.
__esimd_rndd() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_rndd (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 1039 of file math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndd() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_rndd (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 1039 of file math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rnde() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_rnde (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 1071 of file math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rnde() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_rnde (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 1071 of file math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndu() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_rndu (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 1051 of file math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndu() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_rndu (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 1051 of file math_intrin.hpp.
References cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndz() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_rndz (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 1093 of file math_intrin.hpp.
References cl::sycl::fabs(), cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rndz() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_rndz (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 1093 of file math_intrin.hpp.
References cl::sycl::fabs(), cl::sycl::floor(), and SIMDCF_ELEMENT_SKIP.
__esimd_rol() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_rol (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 557 of file math_intrin.hpp.
__esimd_rol() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_rol (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 557 of file math_intrin.hpp.
__esimd_ror() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_ror (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 562 of file math_intrin.hpp.
__esimd_ror() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_ror (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 562 of file math_intrin.hpp.
__esimd_rsqrt() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_rsqrt (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 975 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_rsqrt() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_rsqrt (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 975 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_satf() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_satf (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 340 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_satf() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_satf (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 340 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sfbh() [1/2]
template<typename T0 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<int, SZ> __esimd_sfbh (__SEIEED::vector_type_t< T0, SZ > src0) inline
Definition at line 863 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_fbh().
__esimd_sfbh() [2/2]
template<typename T0 , int SZ> __SEIEED::vector_type_t<int, SZ> __esimd_sfbh (__SEIEED::vector_type_t< T0, SZ > src0) inline
Definition at line 863 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_fbh().
__esimd_sin() [1/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_sin (__SEIEED::vector_type_t< float, SZ > src) inline
Definition at line 986 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sin().
__esimd_sin() [2/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_sin (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 986 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sin().
__esimd_smax() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_smax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 647 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_smax() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_smax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 647 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_smin() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_smin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 726 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_smin() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_smin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 726 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_smulh() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_smulh (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 583 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_imul().
__esimd_smulh() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_smulh (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 583 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_imul().
__esimd_sqrt() [1/2]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_sqrt (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 953 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt() [2/2]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_sqrt (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 953 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt_ieee() [1/4]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<double, SZ> __esimd_sqrt_ieee (__SEIEED::vector_type_t< double, SZ > src0) inline
Definition at line 1112 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt_ieee() [2/4]
template<int SZ> __SEIEED::vector_type_t<double, SZ> __esimd_sqrt_ieee (__SEIEED::vector_type_t< double, SZ > src0) inline
Definition at line 1112 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt_ieee() [3/4]
template<int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<float, SZ> __esimd_sqrt_ieee (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 964 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_sqrt_ieee() [4/4]
template<int SZ> __SEIEED::vector_type_t<float, SZ> __esimd_sqrt_ieee (__SEIEED::vector_type_t< float, SZ > src0) inline
Definition at line 964 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP, and cl::sycl::sqrt().
__esimd_ssdp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T1, N> __esimd_ssdp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
__esimd_ssdp4a_sat()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T1, N> __esimd_ssdp4a_sat (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
__esimd_ssshl() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_ssshl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 436 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ssshl() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_ssshl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 436 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ssshl_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_ssshl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 496 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ssshl_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_ssshl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 496 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sstrunc_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_sstrunc_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 406 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sstrunc_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_sstrunc_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 406 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sudp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T1, N> __esimd_sudp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
__esimd_sudp4a_sat()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T1, N> __esimd_sudp4a_sat (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
__esimd_sushl() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_sushl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 451 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sushl() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_sushl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 451 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sushl_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_sushl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 511 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sushl_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_sushl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 511 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sutrunc_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_sutrunc_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 395 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_sutrunc_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_sutrunc_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 395 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ufbh() [1/2]
template<typename T0 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<uint32_t, SZ> __esimd_ufbh (__SEIEED::vector_type_t< T0, SZ > src0) inline
Definition at line 895 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_fbh().
__esimd_ufbh() [2/2]
template<typename T0 , int SZ> __SEIEED::vector_type_t<uint32_t, SZ> __esimd_ufbh (__SEIEED::vector_type_t< T0, SZ > src0) inline
Definition at line 895 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_fbh().
__esimd_umax() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_umax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 629 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_umax() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_umax (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 629 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_umin() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_umin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 707 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_umin() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_umin (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 707 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_umulh() [1/2]
template<typename T , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T, SZ> __esimd_umulh (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 567 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_imul().
__esimd_umulh() [2/2]
template<typename T , int SZ> __SEIEED::vector_type_t<T, SZ> __esimd_umulh (__SEIEED::vector_type_t< T, SZ > src0, __SEIEED::vector_type_t< T, SZ > src1) inline
Definition at line 567 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_imul().
__esimd_unpack_mask() [1/2]
template<int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<uint16_t, N> __esimd_unpack_mask (uint32_t src0) inline
Definition at line 1157 of file math_intrin.hpp.
__esimd_unpack_mask() [2/2]
template<int N> __SEIEED::vector_type_t<uint16_t, N> __esimd_unpack_mask (uint32_t src0) inline
Definition at line 1157 of file math_intrin.hpp.
__esimd_usdp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T1, N> __esimd_usdp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
__esimd_usdp4a_sat()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T1, N> __esimd_usdp4a_sat (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
__esimd_usshl() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_usshl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 466 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_usshl() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_usshl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 466 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_usshl_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_usshl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 526 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_usshl_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_usshl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 526 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ustrunc_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_ustrunc_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 384 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_ustrunc_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_ustrunc_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 384 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uudp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T1, N> __esimd_uudp4a (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
__esimd_uudp4a_sat()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T1, N> __esimd_uudp4a_sat (__SEIEED::vector_type_t< T2, N > src0, __SEIEED::vector_type_t< T3, N > src1, __SEIEED::vector_type_t< T4, N > src2)
__esimd_uushl() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_uushl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 481 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uushl() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_uushl (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 481 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uushl_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_uushl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 541 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uushl_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_uushl_sat (__SEIEED::vector_type_t< T1, SZ > src0, __SEIEED::vector_type_t< T1, SZ > src1) inline
Definition at line 541 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uutrunc_sat() [1/2]
template<typename T0 , typename T1 , int SZ> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<T0, SZ> __esimd_uutrunc_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 373 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
__esimd_uutrunc_sat() [2/2]
template<typename T0 , typename T1 , int SZ> __SEIEED::vector_type_t<T0, SZ> __esimd_uutrunc_sat (__SEIEED::vector_type_t< T1, SZ > src) inline
Definition at line 373 of file math_intrin.hpp.
References SIMDCF_ELEMENT_SKIP.
extract()
template<typename T > T extract (const uint32_t & width, const uint32_t & offset, uint32_t src, const uint32_t & sign_extend) inline
Definition at line 322 of file math_intrin.hpp.