DPC++ Runtime: include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp File Reference
memory_intrin.hpp File Reference
#include <CL/sycl/detail/accessor_impl.hpp>
#include <CL/sycl/types.hpp>
#include <sycl/ext/intel/experimental/esimd/common.hpp>
#include <sycl/ext/intel/experimental/esimd/detail/types.hpp>
#include <sycl/ext/intel/experimental/esimd/detail/util.hpp>
#include <cstdint>
Classes
class cl::sycl::ext::intel::experimental::esimd::detail::AccessorPrivateProxy
Namespaces
cl
We provide new interfaces for matrix muliply in this patch:
cl::sycl
cl::sycl::ext
cl::sycl::ext::intel
cl::sycl::ext::intel::experimental
cl::sycl::ext::intel::experimental::esimd
cl::sycl::ext::intel::experimental::esimd::detail
Macros
#define __SEIEE sycl::ext::intel::experimental::esimd
#define __SEIEED sycl::ext::intel::experimental::esimd::detail
Functions
template<int ElemsPerAddr, typename = sycl::detail::enable_if_t< (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)>>
constexpr unsigned int cl::sycl::ext::intel::experimental::esimd::detail::ElemsPerAddrEncoding ()
constexpr unsigned int cl::sycl::ext::intel::experimental::esimd::detail::ElemsPerAddrDecoding (unsigned int ElemsPerAddrEncoded)
template<typename Ty , int N, int NumBlk = 0, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N *__SEIEED::ElemsPerAddrDecoding(NumBlk)> __esimd_flat_read (__SEIEED::vector_type_t< uint64_t, N > addrs, int ElemsPerAddr=NumBlk, __SEIEED::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, int NumBlk = 0, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_flat_write (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N *__SEIEED::ElemsPerAddrDecoding(NumBlk)> vals, int ElemsPerAddr=NumBlk, __SEIEED::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_flat_block_read_unaligned (uint64_t addr)
template<typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_flat_block_write (uint64_t addr, __SEIEED::vector_type_t< Ty, N > vals)
template<typename Ty , int N, typename SurfIndAliasTy >
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_block_read (SurfIndAliasTy surf_ind, uint32_t offset)
template<typename Ty , int N, typename SurfIndAliasTy >
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_block_write (SurfIndAliasTy surf_ind, uint32_t offset, __SEIEED::vector_type_t< Ty, N > vals)
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
__SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __esimd_flat_read4 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_flat_write4 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> vals, __SEIEED::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, typename SurfIndAliasTy , int TySizeLog2, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_surf_read (int16_t scale, SurfIndAliasTy surf_ind, uint32_t global_offset, __SEIEED::vector_type_t< uint32_t, N > elem_offsets)
template<typename Ty , int N, typename SurfIndAliasTy , int TySizeLog2, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_surf_write (__SEIEED::vector_type_t< uint16_t, N > pred, int16_t scale, SurfIndAliasTy surf_ind, uint32_t global_offset, __SEIEED::vector_type_t< uint32_t, N > elem_offsets, __SEIEED::vector_type_t< Ty, N > vals)
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_flat_atomic0 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_flat_atomic1 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_flat_atomic2 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< uint16_t, N > pred)
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_barrier ()
TODO.
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_sbarrier (__SEIEE::split_barrier_action flag)
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_slm_fence (uint8_t cntl)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_slm_read (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_slm_write (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > vals, __SEIEED::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_slm_block_read (uint32_t addr)
template<typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_slm_block_write (uint32_t addr, __SEIEED::vector_type_t< Ty, N > vals)
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> __esimd_slm_read4 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred=1)
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_slm_write4 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> vals, __SEIEED::vector_type_t< uint16_t, N > pred=1)
template<__SEIEE::atomic_op Op, typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_slm_atomic0 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_slm_atomic1 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, N > __esimd_slm_atomic2 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int M, int N, typename TACC >
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty, M *N > __esimd_media_block_load (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y)
template<typename Ty , int M, int N, typename TACC >
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_media_block_store (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y, __SEIEED::vector_type_t< Ty, M *N > vals)
template<typename SurfIndAliasTy >
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint32_t __esimd_get_value (SurfIndAliasTy sid)
esimd_get_value
template<typename Ty1 , int N1, typename Ty2 , int N2, typename Ty3 , int N3, int N = 16>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty1, N1 > __esimd_raw_sends_load (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty2, N2 > msgSrc0, __SEIEED::vector_type_t< Ty3, N3 > msgSrc1, __SEIEED::vector_type_t< Ty1, N1 > msgDst)
Raw sends load.
template<typename Ty1 , int N1, typename Ty2 , int N2, int N = 16>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t< Ty1, N1 > __esimd_raw_send_load (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty2, N2 > msgSrc0, __SEIEED::vector_type_t< Ty1, N1 > msgDst)
Raw send load.
template<typename Ty1 , int N1, typename Ty2 , int N2, int N = 16>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_raw_sends_store (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty1, N1 > msgSrc0, __SEIEED::vector_type_t< Ty2, N2 > msgSrc1)
Raw sends store.
template<typename Ty1 , int N1, int N = 16>
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_raw_send_store (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty1, N1 > msgSrc0)
Raw send store.
template<typename Ty , int N, int NumBlk, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
__SEIEED::vector_type_t< Ty, N *__SEIEED::ElemsPerAddrDecoding(NumBlk)> __esimd_flat_read (__SEIEED::vector_type_t< uint64_t, N > addrs, int ElemsPerAddr, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
__SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> __esimd_flat_read4 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, int NumBlk, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
void __esimd_flat_write (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N *__SEIEED::ElemsPerAddrDecoding(NumBlk)> vals, int ElemsPerAddr, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
void __esimd_flat_write4 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> vals, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
__SEIEED::vector_type_t< Ty, N > __esimd_flat_block_read_unaligned (uint64_t addr)
template<typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
void __esimd_flat_block_write (uint64_t addr, __SEIEED::vector_type_t< Ty, N > vals)
template<typename Ty , int M, int N, typename TACC >
__SEIEED::vector_type_t< Ty, M *N > __esimd_media_block_load (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y)
template<typename Ty , int M, int N, typename TACC >
void __esimd_media_block_store (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y, __SEIEED::vector_type_t< Ty, M *N > vals)
template<typename Ty , int N>
uint16_t __esimd_any (__SEIEED::vector_type_t< Ty, N > src)
template<typename Ty , int N>
uint16_t __esimd_all (__SEIEED::vector_type_t< Ty, N > src)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_dp4 (__SEIEED::vector_type_t< Ty, N > v1, __SEIEED::vector_type_t< Ty, N > v2)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_slm_read (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N>
void __esimd_slm_write (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > vals, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_slm_block_read (uint32_t addr)
template<typename Ty , int N>
void __esimd_slm_block_write (uint32_t addr, __SEIEED::vector_type_t< Ty, N > vals)
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask>
__SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> __esimd_slm_read4 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask>
void __esimd_slm_write4 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> vals, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_slm_atomic0 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_slm_atomic1 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N>
__SEIEED::vector_type_t< Ty, N > __esimd_slm_atomic2 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
__SEIEED::vector_type_t< Ty, N > __esimd_flat_atomic0 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
__SEIEED::vector_type_t< Ty, N > __esimd_flat_atomic1 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< uint16_t, N > pred)
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H>
__SEIEED::vector_type_t< Ty, N > __esimd_flat_atomic2 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< uint16_t, N > pred)
template<typename Ty , int N, typename SurfIndAliasTy >
__SEIEED::vector_type_t< Ty, N > __esimd_block_read (SurfIndAliasTy surf_ind, uint32_t offset)
template<typename Ty , int N, typename SurfIndAliasTy >
void __esimd_block_write (SurfIndAliasTy surf_ind, uint32_t offset, __SEIEED::vector_type_t< Ty, N > vals)
template<typename AccessorTy >
uint32_t __esimd_get_value (AccessorTy acc)
esimd_get_value
template<typename Ty1 , int N1, typename Ty2 , int N2, typename Ty3 , int N3, int N>
__SEIEED::vector_type_t< Ty1, N1 > __esimd_raw_sends_load (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty2, N2 > msgSrc0, __SEIEED::vector_type_t< Ty3, N3 > msgSrc1, __SEIEED::vector_type_t< Ty1, N1 > msgDst)
Raw sends load.
template<typename Ty1 , int N1, typename Ty2 , int N2, int N>
__SEIEED::vector_type_t< Ty1, N1 > __esimd_raw_send_load (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty2, N2 > msgSrc0, __SEIEED::vector_type_t< Ty1, N1 > msgDst)
Raw send load.
template<typename Ty1 , int N1, typename Ty2 , int N2, int N>
void __esimd_raw_sends_store (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty1, N1 > msgSrc0, __SEIEED::vector_type_t< Ty2, N2 > msgSrc1)
Raw sends store.
template<typename Ty1 , int N1, int N>
void __esimd_raw_send_store (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty1, N1 > msgSrc0)
Raw send store.
Macro Definition Documentation
__SEIEE
#define __SEIEE sycl::ext::intel::experimental::esimd
Definition at line 77 of file memory_intrin.hpp.
__SEIEED
#define __SEIEED sycl::ext::intel::experimental::esimd::detail
Definition at line 78 of file memory_intrin.hpp.
Function Documentation
__esimd_all()
template<typename Ty , int N> uint16_t __esimd_all (__SEIEED::vector_type_t< Ty, N > src) inline
Definition at line 799 of file memory_intrin.hpp.
__esimd_any()
template<typename Ty , int N> uint16_t __esimd_any (__SEIEED::vector_type_t< Ty, N > src) inline
Definition at line 790 of file memory_intrin.hpp.
__esimd_barrier()
void __esimd_barrier () inline
TODO.
Definition at line 824 of file memory_intrin.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_barrier().
__esimd_block_read() [1/2]
template<typename Ty , int N, typename SurfIndAliasTy > SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_block_read (SurfIndAliasTy surf_ind, uint32_t offset) inline
Definition at line 932 of file memory_intrin.hpp.
__esimd_block_read() [2/2]
template<typename Ty , int N, typename SurfIndAliasTy > __SEIEED::vector_type_t<Ty, N> __esimd_block_read (SurfIndAliasTy surf_ind, uint32_t offset) inline
Definition at line 932 of file memory_intrin.hpp.
__esimd_block_write() [1/2]
template<typename Ty , int N, typename SurfIndAliasTy > SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_block_write (SurfIndAliasTy surf_ind, uint32_t offset, __SEIEED::vector_type_t< Ty, N > vals) inline
Definition at line 938 of file memory_intrin.hpp.
__esimd_block_write() [2/2]
template<typename Ty , int N, typename SurfIndAliasTy > void __esimd_block_write (SurfIndAliasTy surf_ind, uint32_t offset, __SEIEED::vector_type_t< Ty, N > vals) inline
Definition at line 938 of file memory_intrin.hpp.
__esimd_dp4()
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_dp4 (__SEIEED::vector_type_t< Ty, N > v1, __SEIEED::vector_type_t< Ty, N > v2) inline
Definition at line 809 of file memory_intrin.hpp.
__esimd_flat_atomic0() [1/2]
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_flat_atomic0 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 903 of file memory_intrin.hpp.
__esimd_flat_atomic0() [2/2]
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> __SEIEED::vector_type_t<Ty, N> __esimd_flat_atomic0 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 903 of file memory_intrin.hpp.
__esimd_flat_atomic1() [1/2]
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_flat_atomic1 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 912 of file memory_intrin.hpp.
__esimd_flat_atomic1() [2/2]
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> __SEIEED::vector_type_t<Ty, N> __esimd_flat_atomic1 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 912 of file memory_intrin.hpp.
__esimd_flat_atomic2() [1/2]
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_flat_atomic2 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 922 of file memory_intrin.hpp.
__esimd_flat_atomic2() [2/2]
template<__SEIEE::atomic_op Op, typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> __SEIEED::vector_type_t<Ty, N> __esimd_flat_atomic2 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 922 of file memory_intrin.hpp.
__esimd_flat_block_read_unaligned() [1/2]
template<typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_flat_block_read_unaligned (uint64_t addr) inline
Definition at line 673 of file memory_intrin.hpp.
__esimd_flat_block_read_unaligned() [2/2]
template<typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> __SEIEED::vector_type_t<Ty, N> __esimd_flat_block_read_unaligned (uint64_t addr) inline
Definition at line 673 of file memory_intrin.hpp.
__esimd_flat_block_write() [1/2]
template<typename Ty , int N, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_flat_block_write (uint64_t addr, __SEIEED::vector_type_t< Ty, N > vals) inline
Definition at line 684 of file memory_intrin.hpp.
__esimd_flat_block_write() [2/2]
template<typename Ty , int N, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> void __esimd_flat_block_write (uint64_t addr, __SEIEED::vector_type_t< Ty, N > vals) inline
Definition at line 684 of file memory_intrin.hpp.
__esimd_flat_read() [1/2]
template<typename Ty , int N, int NumBlk, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> __SEIEED::vector_type_t<Ty, N * __SEIEED::ElemsPerAddrDecoding(NumBlk)> __esimd_flat_read (__SEIEED::vector_type_t< uint64_t, N > addrs, int ElemsPerAddr, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 527 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::ElemsPerAddrDecoding().
__esimd_flat_read() [2/2]
template<typename Ty , int N, int NumBlk = 0, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N * __SEIEED::ElemsPerAddrDecoding(NumBlk)> __esimd_flat_read (__SEIEED::vector_type_t< uint64_t, N > addrs, int ElemsPerAddr = NumBlk, __SEIEED::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 527 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::ElemsPerAddrDecoding().
__esimd_flat_read4() [1/2]
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> __SEIEED::vector_type_t<Ty, N * get_num_channels_enabled(Mask)> __esimd_flat_read4 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 553 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::get_num_channels_enabled(), and cl::sycl::ext::intel::experimental::esimd::is_channel_enabled().
__esimd_flat_read4() [2/2]
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> __SEIEED::vector_type_t<Ty, N * get_num_channels_enabled(Mask)> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __esimd_flat_read4 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 553 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::get_num_channels_enabled(), and cl::sycl::ext::intel::experimental::esimd::is_channel_enabled().
__esimd_flat_write() [1/2]
template<typename Ty , int N, int NumBlk, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> void __esimd_flat_write (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N *__SEIEED::ElemsPerAddrDecoding(NumBlk)> vals, int ElemsPerAddr, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 600 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::ElemsPerAddrDecoding().
__esimd_flat_write() [2/2]
template<typename Ty , int N, int NumBlk = 0, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_flat_write (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N *__SEIEED::ElemsPerAddrDecoding(NumBlk)> vals, int ElemsPerAddr = NumBlk, __SEIEED::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 600 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::ElemsPerAddrDecoding().
__esimd_flat_write4() [1/2]
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask, __SEIEE::CacheHint L1H, __SEIEE::CacheHint L3H> void __esimd_flat_write4 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> vals, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 626 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::get_num_channels_enabled(), and cl::sycl::ext::intel::experimental::esimd::is_channel_enabled().
__esimd_flat_write4() [2/2]
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_flat_write4 (__SEIEED::vector_type_t< uint64_t, N > addrs, __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> vals, __SEIEED::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 626 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::get_num_channels_enabled(), and cl::sycl::ext::intel::experimental::esimd::is_channel_enabled().
__esimd_get_value() [1/2]
template<typename AccessorTy > uint32_t __esimd_get_value (AccessorTy acc) inline
esimd_get_value
Parameters
acc the SYCL accessor.
Returns the binding table index value.
Definition at line 951 of file memory_intrin.hpp.
__esimd_get_value() [2/2]
template<typename SurfIndAliasTy > SYCL_EXTERNAL SYCL_ESIMD_FUNCTION uint32_t __esimd_get_value (SurfIndAliasTy sid)
esimd_get_value
Parameters
sid the SYCL accessor.
Returns the binding table index value.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_get_value().
__esimd_media_block_load() [1/2]
template<typename Ty , int M, int N, typename TACC > SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, M * N> __esimd_media_block_load (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y) inline
Definition at line 694 of file memory_intrin.hpp.
__esimd_media_block_load() [2/2]
template<typename Ty , int M, int N, typename TACC > __SEIEED::vector_type_t<Ty, M * N> __esimd_media_block_load (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y) inline
Definition at line 694 of file memory_intrin.hpp.
__esimd_media_block_store() [1/2]
template<typename Ty , int M, int N, typename TACC > SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_media_block_store (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y, __SEIEED::vector_type_t< Ty, M *N > vals) inline
Definition at line 744 of file memory_intrin.hpp.
__esimd_media_block_store() [2/2]
template<typename Ty , int M, int N, typename TACC > void __esimd_media_block_store (unsigned modififer, TACC handle, unsigned plane, unsigned width, unsigned x, unsigned y, __SEIEED::vector_type_t< Ty, M *N > vals) inline
Definition at line 744 of file memory_intrin.hpp.
__esimd_raw_send_load() [1/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, int N = 16> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty1, N1> __esimd_raw_send_load (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty2, N2 > msgSrc0, __SEIEED::vector_type_t< Ty1, N1 > msgDst) inline
Raw send load.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgDst the destination operand of send message.
Returns a simd vector of type Ty1 and size N1.
Definition at line 1029 of file memory_intrin.hpp.
__esimd_raw_send_load() [2/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, int N> __SEIEED::vector_type_t<Ty1, N1> __esimd_raw_send_load (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty2, N2 > msgSrc0, __SEIEED::vector_type_t< Ty1, N1 > msgDst) inline
Raw send load.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgDst the destination operand of send message.
Returns a simd vector of type Ty1 and size N1.
Definition at line 1029 of file memory_intrin.hpp.
__esimd_raw_send_store() [1/2]
template<typename Ty1 , int N1, int N = 16> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_raw_send_store (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty1, N1 > msgSrc0) inline
Raw send store.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
Definition at line 1094 of file memory_intrin.hpp.
__esimd_raw_send_store() [2/2]
template<typename Ty1 , int N1, int N> void __esimd_raw_send_store (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty1, N1 > msgSrc0) inline
Raw send store.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
Definition at line 1094 of file memory_intrin.hpp.
__esimd_raw_sends_load() [1/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, typename Ty3 , int N3, int N = 16> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty1, N1> __esimd_raw_sends_load (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty2, N2 > msgSrc0, __SEIEED::vector_type_t< Ty3, N3 > msgSrc1, __SEIEED::vector_type_t< Ty1, N1 > msgDst) inline
Raw sends load.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
msgDst the destination operand of send message.
Returns a simd vector of type Ty1 and size N1.
Definition at line 990 of file memory_intrin.hpp.
__esimd_raw_sends_load() [2/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, typename Ty3 , int N3, int N> __SEIEED::vector_type_t<Ty1, N1> __esimd_raw_sends_load (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty2, N2 > msgSrc0, __SEIEED::vector_type_t< Ty3, N3 > msgSrc1, __SEIEED::vector_type_t< Ty1, N1 > msgDst) inline
Raw sends load.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
msgDst the destination operand of send message.
Returns a simd vector of type Ty1 and size N1.
Definition at line 990 of file memory_intrin.hpp.
__esimd_raw_sends_store() [1/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, int N = 16> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_raw_sends_store (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty1, N1 > msgSrc0, __SEIEED::vector_type_t< Ty2, N2 > msgSrc1) inline
Raw sends store.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
Definition at line 1064 of file memory_intrin.hpp.
__esimd_raw_sends_store() [2/2]
template<typename Ty1 , int N1, typename Ty2 , int N2, int N> void __esimd_raw_sends_store (uint8_t modifier, uint8_t execSize, __SEIEED::vector_type_t< uint16_t, N > pred, uint8_t numSrc0, uint8_t numSrc1, uint8_t sfid, uint32_t exDesc, uint32_t msgDesc, __SEIEED::vector_type_t< Ty1, N1 > msgSrc0, __SEIEED::vector_type_t< Ty2, N2 > msgSrc1) inline
Raw sends store.
Parameters
modifier the send message flags (Bit-0: isSendc, Bit-1: isEOT).
execSize the execution size, which must be a compile time constant.
pred the predicate to specify enabled channels.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
exDesc the extended message descriptor.
msgDesc the message descriptor.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
Definition at line 1064 of file memory_intrin.hpp.
__esimd_sbarrier()
void __esimd_sbarrier (__SEIEE::split_barrier_action flag) inline
Definition at line 826 of file memory_intrin.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_sbarrier().
__esimd_slm_atomic0() [1/2]
template<__SEIEE::atomic_op Op, typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_slm_atomic0 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 875 of file memory_intrin.hpp.
__esimd_slm_atomic0() [2/2]
template<__SEIEE::atomic_op Op, typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_slm_atomic0 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 875 of file memory_intrin.hpp.
__esimd_slm_atomic1() [1/2]
template<__SEIEE::atomic_op Op, typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_slm_atomic1 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 883 of file memory_intrin.hpp.
__esimd_slm_atomic1() [2/2]
template<__SEIEE::atomic_op Op, typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_slm_atomic1 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 883 of file memory_intrin.hpp.
__esimd_slm_atomic2() [1/2]
template<__SEIEE::atomic_op Op, typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_slm_atomic2 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 892 of file memory_intrin.hpp.
__esimd_slm_atomic2() [2/2]
template<__SEIEE::atomic_op Op, typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_slm_atomic2 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > src0, __SEIEED::vector_type_t< Ty, N > src1, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 892 of file memory_intrin.hpp.
__esimd_slm_block_read() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_slm_block_read (uint32_t addr) inline
Definition at line 846 of file memory_intrin.hpp.
__esimd_slm_block_read() [2/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_slm_block_read (uint32_t addr) inline
Definition at line 846 of file memory_intrin.hpp.
__esimd_slm_block_write() [1/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_slm_block_write (uint32_t addr, __SEIEED::vector_type_t< Ty, N > vals) inline
Definition at line 853 of file memory_intrin.hpp.
__esimd_slm_block_write() [2/2]
template<typename Ty , int N> void __esimd_slm_block_write (uint32_t addr, __SEIEED::vector_type_t< Ty, N > vals) inline
Definition at line 853 of file memory_intrin.hpp.
__esimd_slm_fence()
void __esimd_slm_fence (uint8_t cntl) inline
Definition at line 828 of file memory_intrin.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::esimd_barrier(), and cl::sycl::ext::intel::experimental::esimd::esimd_fence().
__esimd_slm_read() [1/2]
template<typename Ty , int N> __SEIEED::vector_type_t<Ty, N> __esimd_slm_read (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 832 of file memory_intrin.hpp.
__esimd_slm_read() [2/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_slm_read (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 832 of file memory_intrin.hpp.
__esimd_slm_read4() [1/2]
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask> __SEIEED::vector_type_t<Ty, N * get_num_channels_enabled(Mask)> __esimd_slm_read4 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 859 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::get_num_channels_enabled().
__esimd_slm_read4() [2/2]
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N * get_num_channels_enabled(Mask)> __esimd_slm_read4 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 859 of file memory_intrin.hpp.
References cl::sycl::ext::intel::experimental::esimd::get_num_channels_enabled().
__esimd_slm_write() [1/2]
template<typename Ty , int N> void __esimd_slm_write (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > vals, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 840 of file memory_intrin.hpp.
__esimd_slm_write() [2/2]
template<typename Ty , int N> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_slm_write (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N > vals, __SEIEED::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 840 of file memory_intrin.hpp.
__esimd_slm_write4() [1/2]
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask> void __esimd_slm_write4 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> vals, __SEIEED::vector_type_t< uint16_t, N > pred) inline
Definition at line 867 of file memory_intrin.hpp.
__esimd_slm_write4() [2/2]
template<typename Ty , int N, __SEIEE::rgba_channel_mask Mask> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_slm_write4 (__SEIEED::vector_type_t< uint32_t, N > addrs, __SEIEED::vector_type_t< Ty, N *get_num_channels_enabled(Mask)> vals, __SEIEED::vector_type_t< uint16_t, N > pred = 1) inline
Definition at line 867 of file memory_intrin.hpp.
__esimd_surf_read()
template<typename Ty , int N, typename SurfIndAliasTy , int TySizeLog2, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION __SEIEED::vector_type_t<Ty, N> __esimd_surf_read (int16_t scale, SurfIndAliasTy surf_ind, uint32_t global_offset, __SEIEED::vector_type_t< uint32_t, N > elem_offsets)
Definition at line 166 of file memory_intrin.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::gather().
__esimd_surf_write()
template<typename Ty , int N, typename SurfIndAliasTy , int TySizeLog2, __SEIEE::CacheHint L1H = __SEIEE::CacheHint::None, __SEIEE::CacheHint L3H = __SEIEE::CacheHint::None> SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void __esimd_surf_write (__SEIEED::vector_type_t< uint16_t, N > pred, int16_t scale, SurfIndAliasTy surf_ind, uint32_t global_offset, __SEIEED::vector_type_t< uint32_t, N > elem_offsets, __SEIEED::vector_type_t< Ty, N > vals)
Definition at line 208 of file memory_intrin.hpp.