DPC++ Runtime: sycl::_V1::detail::enqueue_kernel_launch Namespace Reference
sycl::_V1::detail::enqueue_kernel_launch Namespace Reference
Functions
void handleOutOfResources (const device_impl &DeviceImpl, ur_kernel_handle_t Kernel, const NDRDescT &NDRDesc)
void handleInvalidWorkGroupSize (const device_impl &DeviceImpl, ur_kernel_handle_t Kernel, const NDRDescT &NDRDesc)
void handleInvalidWorkItemSize (const device_impl &DeviceImpl, const NDRDescT &NDRDesc)
void handleInvalidValue (const device_impl &DeviceImpl, const NDRDescT &NDRDesc)
void handleErrorOrWarning (ur_result_t, const device_impl &, ur_kernel_handle_t, const NDRDescT &)
Analyzes error code and arguments of urEnqueueKernelLaunch to emit user-friendly exception describing the problem.
Function Documentation
handleErrorOrWarning()
void sycl::_V1::detail::enqueue_kernel_launch::handleErrorOrWarning (ur_result_t , const device_impl & , ur_kernel_handle_t , const NDRDescT &)
Analyzes error code and arguments of urEnqueueKernelLaunch to emit user-friendly exception describing the problem.
This function is expected to be called only for non-success error codes, i.e. the first argument must not be equal to UR_RESULT_SUCCESS.
This function actually never returns and always throws an exception with error description.
Definition at line 346 of file error_handling.cpp.
References sycl::_V1::feature_not_supported, sycl::_V1::detail::device_impl::getPlugin(), handleInvalidValue(), handleInvalidWorkGroupSize(), handleInvalidWorkItemSize(), handleOutOfResources(), sycl::_V1::invalid, sycl::_V1::detail::Kernel, sycl::_V1::kernel_argument, sycl::_V1::make_error_code(), sycl::_V1::memory_allocation, sycl::_V1::runtime, and sycl::_V1::detail::set_ur_error().
Referenced by sycl::_V1::detail::enqueueImpCommandBufferKernel(), and sycl::_V1::detail::enqueueImpKernel().
handleInvalidValue()
void sycl::_V1::detail::enqueue_kernel_launch::handleInvalidValue (const device_impl & DeviceImpl, const NDRDescT & NDRDesc)
Definition at line 324 of file error_handling.cpp.
References sycl::_V1::detail::NDRDescT::Dims, sycl::_V1::detail::device_impl::getHandleRef(), sycl::_V1::detail::device_impl::getPlugin(), sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::detail::NDRDescT::LocalSize, sycl::_V1::make_error_code(), and sycl::_V1::nd_range.
Referenced by handleErrorOrWarning().
handleInvalidWorkGroupSize()
void sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize (const device_impl & DeviceImpl, ur_kernel_handle_t Kernel, const NDRDescT & NDRDesc)
Definition at line 75 of file error_handling.cpp.
References sycl::_V1::platform::get_backend(), sycl::_V1::detail::device_impl::get_info(), sycl::_V1::detail::device_impl::get_platform(), sycl::_V1::detail::device_impl::getHandleRef(), sycl::_V1::detail::device_impl::getPlugin(), sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::detail::Kernel, sycl::_V1::kernel_not_supported, sycl::_V1::detail::NDRDescT::LocalSize, sycl::_V1::make_error_code(), and sycl::_V1::nd_range.
Referenced by handleErrorOrWarning().
handleInvalidWorkItemSize()
void sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkItemSize (const device_impl & DeviceImpl, const NDRDescT & NDRDesc)
Definition at line 304 of file error_handling.cpp.
References sycl::_V1::detail::NDRDescT::Dims, sycl::_V1::detail::device_impl::getHandleRef(), sycl::_V1::detail::device_impl::getPlugin(), sycl::_V1::detail::NDRDescT::LocalSize, sycl::_V1::make_error_code(), and sycl::_V1::nd_range.
Referenced by handleErrorOrWarning().
handleOutOfResources()
void sycl::_V1::detail::enqueue_kernel_launch::handleOutOfResources (const device_impl & DeviceImpl, ur_kernel_handle_t Kernel, const NDRDescT & NDRDesc)
Definition at line 23 of file error_handling.cpp.
References sycl::_V1::detail::codeToString(), sycl::_V1::platform::get_backend(), sycl::_V1::detail::device_impl::get_info(), sycl::_V1::detail::device_impl::get_platform(), sycl::_V1::detail::device_impl::getPlugin(), sycl::_V1::detail::Kernel, sycl::_V1::detail::NDRDescT::LocalSize, and sycl::_V1::nd_range.
Referenced by handleErrorOrWarning().