DPC++ Runtime: pi2ur Namespace Reference
pi2ur Namespace Reference
Functions
pi_result piTearDown (void *PluginParameter)
pi_result PiGetAdapter (ur_adapter_handle_t &adapter)
pi_result piPlatformsGet (pi_uint32 NumEntries, pi_platform *Platforms, pi_uint32 *NumPlatforms)
pi_result piextPlatformGetNativeHandle (pi_platform Platform, pi_native_handle *NativeHandle)
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform *Platform)
pi_result piPlatformGetInfo (pi_platform Platform, pi_platform_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextPluginGetOpaqueData (void *opaque_data_param, void **opaque_data_return)
pi_result piPluginGetBackendOption (pi_platform Platform, const char *FrontendOption, const char **PlatformOption)
pi_result piDevicesGet (pi_platform Platform, pi_device_type DeviceType, pi_uint32 NumEntries, pi_device *Devices, pi_uint32 *NumDevices)
pi_result piDeviceRetain (pi_device Device)
pi_result piDeviceRelease (pi_device Device)
pi_result piPluginGetLastError (char **Message)
pi_result piDeviceGetInfo (pi_device Device, pi_device_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextDeviceGetNativeHandle (pi_device Device, pi_native_handle *NativeHandle)
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform Platform, pi_device *Device)
pi_result piDevicePartition (pi_device Device, const pi_device_partition_property *Properties, pi_uint32 NumEntries, pi_device *SubDevices, pi_uint32 *NumSubDevices)
pi_result piGetDeviceAndHostTimer (pi_device Device, uint64_t *DeviceTime, uint64_t *HostTime)
pi_result piextDeviceSelectBinary (pi_device Device, pi_device_binary *Binaries, pi_uint32 NumBinaries, pi_uint32 *SelectedBinaryInd)
pi_result piContextCreate (const pi_context_properties *Properties, pi_uint32 NumDevices, const pi_device *Devices, void(*PFnNotify)(const char *ErrInfo, const void *PrivateInfo, size_t CB, void *UserData), void *UserData, pi_context *RetContext)
pi_result piextContextSetExtendedDeleter (pi_context Context, pi_context_extended_deleter Function, void *UserData)
pi_result piextContextGetNativeHandle (pi_context Context, pi_native_handle *NativeHandle)
pi_result piextContextCreateWithNativeHandle (pi_native_handle NativeHandle, pi_uint32 NumDevices, const pi_device *Devices, bool OwnNativeHandle, pi_context *RetContext)
pi_result piContextGetInfo (pi_context Context, pi_context_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piContextRetain (pi_context Context)
pi_result piContextRelease (pi_context Context)
pi_result piextQueueCreate (pi_context Context, pi_device Device, pi_queue_properties *Properties, pi_queue *Queue)
pi_result piQueueCreate (pi_context Context, pi_device Device, pi_queue_properties Flags, pi_queue *Queue)
pi_result piextQueueCreateWithNativeHandle (pi_native_handle NativeHandle, int32_t NativeHandleDesc, pi_context Context, pi_device Device, bool OwnNativeHandle, pi_queue_properties *Properties, pi_queue *Queue)
pi_result piextQueueGetNativeHandle (pi_queue Queue, pi_native_handle *NativeHandle, int32_t *NativeHandleDesc)
pi_result piQueueRelease (pi_queue Queue)
pi_result piQueueFinish (pi_queue Queue)
pi_result piQueueGetInfo (pi_queue Queue, pi_queue_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piQueueRetain (pi_queue Queue)
pi_result piQueueFlush (pi_queue Queue)
pi_result piProgramCreate (pi_context Context, const void *ILBytes, size_t Length, pi_program *Program)
pi_result piProgramCreateWithBinary (pi_context Context, pi_uint32 NumDevices, const pi_device *DeviceList, const size_t *Lengths, const unsigned char **Binaries, size_t NumMetadataEntries, const pi_device_binary_property *Metadata, pi_int32 *BinaryStatus, pi_program *Program)
pi_result piProgramGetInfo (pi_program Program, pi_program_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piProgramLink (pi_context Context, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, pi_uint32 NumInputPrograms, const pi_program *InputPrograms, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData, pi_program *RetProgram)
pi_result piProgramCompile (pi_program Program, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, pi_uint32 NumInputHeaders, const pi_program *InputHeaders, const char **HeaderIncludeNames, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData)
pi_result piProgramBuild (pi_program Program, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData)
pi_result piextProgramSetSpecializationConstant (pi_program Program, pi_uint32 SpecID, size_t Size, const void *SpecValue)
pi_result piKernelCreate (pi_program Program, const char *KernelName, pi_kernel *RetKernel)
pi_result piEnqueueMemImageFill (pi_queue Queue, pi_mem Image, const void *FillColor, const size_t *Origin, const size_t *Region, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *Event)
pi_result piextGetDeviceFunctionPointer (pi_device Device, pi_program Program, const char *FunctionName, pi_uint64 *FunctionPointerRet)
pi_result piextGetGlobalVariablePointer (pi_device Device, pi_program Program, const char *GlobalVariableName, size_t *GlobalVariableSize, void **GlobalVariablePointerRet)
pi_result piextKernelSetArgMemObj (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_mem_obj_property *ArgProperties, const pi_mem *ArgValue)
pi_result piKernelSetArg (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void *ArgValue)
pi_result piKernelSetArgPointer (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void *ArgValue)
pi_result piextKernelCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, pi_program Program, bool OwnNativeHandle, pi_kernel *Kernel)
pi_result piProgramRetain (pi_program Program)
pi_result piKernelSetExecInfo (pi_kernel Kernel, pi_kernel_exec_info ParamName, size_t ParamValueSize, const void *ParamValue)
pi_result piextProgramGetNativeHandle (pi_program Program, pi_native_handle *NativeHandle)
pi_result piextProgramCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_program *Program)
pi_result piKernelGetInfo (pi_kernel Kernel, pi_kernel_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piKernelGetGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_group_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piKernelRetain (pi_kernel Kernel)
pi_result piKernelRelease (pi_kernel Kernel)
pi_result piProgramRelease (pi_program Program)
pi_result piextKernelSetArgPointer (pi_kernel Kernel, pi_uint32 ArgIndex, size_t, const void *ArgValue)
pi_result piKernelGetSubGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_sub_group_info ParamName, size_t InputValueSize, const void *InputValue, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piProgramGetBuildInfo (pi_program Program, pi_device Device, pi_program_build_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextKernelGetNativeHandle (pi_kernel Kernel, pi_native_handle *NativeHandle)
pi_result piextKernelSuggestMaxCooperativeGroupCount (pi_kernel Kernel, size_t LocalWorkSize, size_t DynamicSharedMemorySize, pi_uint32 *GroupCountRet)
pi_result piextEnqueueDeviceGlobalVariableWrite (pi_queue Queue, pi_program Program, const char *Name, pi_bool BlockingWrite, size_t Count, size_t Offset, const void *Src, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
API for writing data from host to a device global variable.
pi_result piextEnqueueDeviceGlobalVariableRead (pi_queue Queue, pi_program Program, const char *Name, pi_bool BlockingRead, size_t Count, size_t Offset, void *Dst, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
API reading data from a device global variable to host.
pi_result piMemBufferCreate (pi_context Context, pi_mem_flags Flags, size_t Size, void *HostPtr, pi_mem *RetMem, const pi_mem_properties *properties)
pi_result piextUSMHostAlloc (void **ResultPtr, pi_context Context, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
pi_result piMemGetInfo (pi_mem Mem, pi_mem_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
static void pi2urImageDesc (const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, ur_image_format_t *UrFormat, ur_image_desc_t *UrDesc)
static void ur2piImageFormat (const ur_image_format_t *UrFormat, pi_image_format *PiFormat)
pi_result piMemImageCreate (pi_context Context, pi_mem_flags Flags, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, void *HostPtr, pi_mem *RetImage)
pi_result piextMemImageCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, pi_mem *RetImage)
pi_result piMemBufferPartition (pi_mem Buffer, pi_mem_flags Flags, pi_buffer_create_type BufferCreateType, void *BufferCreateInfo, pi_mem *RetMem)
pi_result piextMemGetNativeHandle (pi_mem Mem, pi_device Dev, pi_native_handle *NativeHandle)
pi_result piEnqueueMemImageCopy (pi_queue Queue, pi_mem SrcImage, pi_mem DstImage, pi_image_offset SrcOrigin, pi_image_offset DstOrigin, pi_image_region Region, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piextMemCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_mem *Mem)
pi_result piextUSMDeviceAlloc (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
pi_result piextUSMPitchedAlloc (void **ResultPtr, size_t *ResultPitch, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t WidthInBytes, size_t Height, unsigned int ElementSizeBytes)
pi_result piextUSMSharedAlloc (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
pi_result piextUSMFree (pi_context Context, void *Ptr)
pi_result piMemRetain (pi_mem Mem)
pi_result piMemRelease (pi_mem Mem)
pi_result piextUSMEnqueuePrefetch (pi_queue Queue, const void *Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
Hint to migrate memory to the device.
pi_result piextUSMEnqueueMemAdvise (pi_queue Queue, const void *Ptr, size_t Length, pi_mem_advice Advice, pi_event *OutEvent)
USM memadvise API to govern behavior of automatic migration mechanisms.
pi_result piextUSMEnqueueFill2D (pi_queue Queue, void *Ptr, size_t Pitch, size_t PatternSize, const void *Pattern, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event *EventsWaitList, pi_event *Event)
USM 2D Fill API.
pi_result piextUSMEnqueueMemset2D (pi_queue Queue, void *Ptr, size_t Pitch, int Value, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event *EventsWaitList, pi_event *Event)
pi_result piextUSMGetMemAllocInfo (pi_context Context, const void *Ptr, pi_mem_alloc_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextUSMImport (const void *HostPtr, size_t Size, pi_context Context)
pi_result piextUSMRelease (const void *HostPtr, pi_context Context)
pi_result piMemImageGetInfo (pi_mem Image, pi_image_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextUSMEnqueueMemcpy2D (pi_queue Queue, pi_bool Blocking, void *DstPtr, size_t DstPitch, const void *SrcPtr, size_t SrcPitch, size_t Width, size_t Height, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
USM 2D Memcpy API.
pi_result piEnqueueKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t *GlobalWorkOffset, const size_t *GlobalWorkSize, const size_t *LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piextEnqueueCooperativeKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t *GlobalWorkOffset, const size_t *GlobalWorkSize, const size_t *LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemImageWrite (pi_queue Queue, pi_mem Image, pi_bool BlockingWrite, pi_image_offset Origin, pi_image_region Region, size_t InputRowPitch, size_t InputSlicePitch, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemImageRead (pi_queue Queue, pi_mem Image, pi_bool BlockingRead, pi_image_offset Origin, pi_image_region Region, size_t RowPitch, size_t SlicePitch, void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferMap (pi_queue Queue, pi_mem Mem, pi_bool BlockingMap, pi_map_flags MapFlags, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent, void **RetMap)
pi_result piEnqueueMemUnmap (pi_queue Queue, pi_mem Mem, void *MappedPtr, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferFill (pi_queue Queue, pi_mem Buffer, const void *Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piextUSMEnqueueMemset (pi_queue Queue, void *Ptr, pi_int32 Value, size_t Count, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferCopyRect (pi_queue Queue, pi_mem SrcMem, pi_mem DstMem, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferCopy (pi_queue Queue, pi_mem SrcMem, pi_mem DstMem, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piextUSMEnqueueMemcpy (pi_queue Queue, pi_bool Blocking, void *DstPtr, const void *SrcPtr, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferWriteRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferWrite (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, size_t Offset, size_t Size, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferReadRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingRead, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferRead (pi_queue Queue, pi_mem Src, pi_bool BlockingRead, size_t Offset, size_t Size, void *Dst, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueEventsWaitWithBarrier (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piEnqueueEventsWait (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *OutEvent)
pi_result piextEnqueueReadHostPipe (pi_queue queue, pi_program program, const char *pipe_symbol, pi_bool blocking, void *ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
pi_result piextEnqueueWriteHostPipe (pi_queue queue, pi_program program, const char *pipe_symbol, pi_bool blocking, void *ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
pi_result piEventsWait (pi_uint32 NumEvents, const pi_event *EventsWaitList)
pi_result piEventGetInfo (pi_event Event, pi_event_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextEventGetNativeHandle (pi_event Event, pi_native_handle *NativeHandle)
pi_result piEventGetProfilingInfo (pi_event Event, pi_profiling_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piEventCreate (pi_context Context, pi_event *RetEvent)
pi_result piextEventCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_event *Event)
pi_result piEventSetCallback (pi_event Event, pi_int32 CommandExecCallbackType, void(*PFnNotify)(pi_event Event, pi_int32 EventCommandStatus, void *UserData), void *UserData)
pi_result piEventSetStatus (pi_event Event, pi_int32 ExecutionStatus)
pi_result piEventRetain (pi_event Event)
pi_result piEventRelease (pi_event Event)
pi_result piEnqueueTimestampRecordingExp (pi_queue Queue, pi_bool Blocking, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piSamplerCreate (pi_context Context, const pi_sampler_properties *SamplerProperties, pi_sampler *RetSampler)
pi_result piSamplerGetInfo (pi_sampler Sampler, pi_sampler_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextKernelSetArgSampler (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_sampler *ArgValue)
pi_result piSamplerRetain (pi_sampler Sampler)
pi_result piSamplerRelease (pi_sampler Sampler)
pi_result piextCommandBufferCreate (pi_context Context, pi_device Device, const pi_ext_command_buffer_desc *Desc, pi_ext_command_buffer *RetCommandBuffer)
pi_result piextCommandBufferRetain (pi_ext_command_buffer CommandBuffer)
pi_result piextCommandBufferRelease (pi_ext_command_buffer CommandBuffer)
pi_result piextCommandBufferFinalize (pi_ext_command_buffer CommandBuffer)
pi_result piextCommandBufferNDRangeKernel (pi_ext_command_buffer CommandBuffer, pi_kernel Kernel, pi_uint32 WorkDim, const size_t *GlobalWorkOffset, const size_t *GlobalWorkSize, const size_t *LocalWorkSize, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint, pi_ext_command_buffer_command *Command)
pi_result piextCommandBufferMemcpyUSM (pi_ext_command_buffer CommandBuffer, void *DstPtr, const void *SrcPtr, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferMemBufferCopy (pi_ext_command_buffer CommandBuffer, pi_mem SrcMem, pi_mem DstMem, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferMemBufferCopyRect (pi_ext_command_buffer CommandBuffer, pi_mem SrcMem, pi_mem DstMem, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferMemBufferReadRect (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void *Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferMemBufferRead (pi_ext_command_buffer CommandBuffer, pi_mem Src, size_t Offset, size_t Size, void *Dst, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferMemBufferWriteRect (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void *Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferMemBufferWrite (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, size_t Offset, size_t Size, const void *Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferMemBufferFill (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, const void *Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferFillUSM (pi_ext_command_buffer CommandBuffer, void *Ptr, const void *Pattern, size_t PatternSize, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferPrefetchUSM (pi_ext_command_buffer CommandBuffer, const void *Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextCommandBufferAdviseUSM (pi_ext_command_buffer CommandBuffer, const void *Ptr, size_t Length, pi_mem_advice Advice, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
pi_result piextEnqueueCommandBuffer (pi_ext_command_buffer CommandBuffer, pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piextCommandBufferUpdateKernelLaunch (pi_ext_command_buffer_command command, pi_ext_command_buffer_update_kernel_launch_desc *desc)
pi_result piextCommandBufferRetainCommand (pi_ext_command_buffer_command command)
pi_result piextCommandBufferReleaseCommand (pi_ext_command_buffer_command command)
pi_result piextEnablePeerAccess (pi_device command_device, pi_device peer_device)
pi_result piextDisablePeerAccess (pi_device command_device, pi_device peer_device)
pi_result piextPeerAccessGetInfo (pi_device command_device, pi_device peer_device, pi_peer_attr attr, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piextMemImageAllocate (pi_context Context, pi_device Device, pi_image_format *ImageFormat, pi_image_desc *ImageDesc, pi_image_mem_handle *RetMem)
pi_result piextMemUnsampledImageCreate (pi_context Context, pi_device Device, pi_image_mem_handle ImgMem, pi_image_format *ImageFormat, pi_image_desc *ImageDesc, pi_image_handle *RetHandle)
pi_result piextMemSampledImageCreate (pi_context Context, pi_device Device, pi_image_mem_handle ImgMem, pi_image_format *ImageFormat, pi_image_desc *ImageDesc, pi_sampler Sampler, pi_image_handle *RetHandle)
pi_result piextBindlessImageSamplerCreate (pi_context Context, const pi_sampler_properties *SamplerProperties, float MinMipmapLevelClamp, float MaxMipmapLevelClamp, float MaxAnisotropy, pi_sampler *RetSampler)
pi_result piextMemMipmapGetLevel (pi_context Context, pi_device Device, pi_image_mem_handle MipMem, unsigned int Level, pi_image_mem_handle *RetMem)
pi_result piextMemImageFree (pi_context Context, pi_device Device, pi_image_mem_handle MemoryHandle)
pi_result piextMemMipmapFree (pi_context Context, pi_device Device, pi_image_mem_handle MemoryHandle)
static void pi2urImageCopyFlags (const pi_image_copy_flags PiFlags, ur_exp_image_copy_flags_t *UrFlags)
pi_result piextMemImageCopy (pi_queue Queue, void *DstPtr, void *SrcPtr, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, const pi_image_copy_flags Flags, pi_image_offset SrcOffset, pi_image_offset DstOffset, pi_image_region CopyExtent, pi_image_region HostExtent, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piextMemUnsampledImageHandleDestroy (pi_context Context, pi_device Device, pi_image_handle Handle)
pi_result piextMemSampledImageHandleDestroy (pi_context Context, pi_device Device, pi_image_handle Handle)
static void pi2urImageInfoFlags (const pi_image_info PiFlags, ur_image_info_t *UrFlags)
pi_result piextMemImageGetInfo (pi_image_mem_handle MemHandle, pi_image_info ParamName, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextMemImportOpaqueFD (pi_context Context, pi_device Device, size_t Size, int FileDescriptor, pi_interop_mem_handle *RetHandle)
pi_result piextImportExternalMemory (pi_context Context, pi_device Device, pi_external_mem_descriptor *MemDescriptor, pi_interop_mem_handle *RetHandle)
pi_result piextMemMapExternalArray (pi_context Context, pi_device Device, pi_image_format *ImageFormat, pi_image_desc *ImageDesc, pi_interop_mem_handle MemHandle, pi_image_mem_handle *RetMem)
pi_result piextMemReleaseInterop (pi_context Context, pi_device Device, pi_interop_mem_handle ExtMem)
pi_result piextImportExternalSemaphoreOpaqueFD (pi_context Context, pi_device Device, int FileDescriptor, pi_interop_semaphore_handle *RetHandle)
pi_result piextImportExternalSemaphore (pi_context Context, pi_device Device, pi_external_semaphore_descriptor *SemDescriptor, pi_interop_semaphore_handle *RetHandle)
pi_result piextDestroyExternalSemaphore (pi_context Context, pi_device Device, pi_interop_semaphore_handle SemHandle)
pi_result piextWaitExternalSemaphore (pi_queue Queue, pi_interop_semaphore_handle SemHandle, bool HasWaitValue, pi_uint64 WaitValue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piextSignalExternalSemaphore (pi_queue Queue, pi_interop_semaphore_handle SemHandle, bool HasSignalValue, pi_uint64 SignalValue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piextVirtualMemGranularityGetInfo (pi_context Context, pi_device Device, pi_virtual_mem_granularity_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextPhysicalMemCreate (pi_context Context, pi_device Device, size_t MemSize, pi_physical_mem *RetPhyscialMem)
pi_result piextPhysicalMemRetain (pi_physical_mem PhysicalMem)
pi_result piextPhysicalMemRelease (pi_physical_mem PhysicalMem)
pi_result piextVirtualMemReserve (pi_context Context, const void *Start, size_t RangeSize, void **RetPtr)
pi_result piextVirtualMemFree (pi_context Context, const void *Ptr, size_t RangeSize)
pi_result piextVirtualMemSetAccess (pi_context Context, const void *Ptr, size_t RangeSize, pi_virtual_access_flags Flags)
pi_result piextVirtualMemMap (pi_context Context, const void *Ptr, size_t RangeSize, pi_physical_mem PhysicalMem, size_t Offset, pi_virtual_access_flags Flags)
pi_result piextVirtualMemUnmap (pi_context Context, const void *Ptr, size_t RangeSize)
pi_result piextVirtualMemGetInfo (pi_context Context, const void *Ptr, size_t RangeSize, pi_virtual_mem_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextEnqueueNativeCommand (pi_queue Queue, pi_enqueue_native_command_function Fn, void *Data, pi_uint32 NumMems, const pi_mem *MemList, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
Function Documentation
pi2urImageCopyFlags()
static void pi2ur::pi2urImageCopyFlags (const pi_image_copy_flags PiFlags, ur_exp_image_copy_flags_t * UrFlags) static
Definition at line 5269 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), PI_IMAGE_COPY_DEVICE_TO_DEVICE, PI_IMAGE_COPY_DEVICE_TO_HOST, and PI_IMAGE_COPY_HOST_TO_DEVICE.
Referenced by piextMemImageCopy().
pi2urImageDesc()
static void pi2ur::pi2urImageDesc (const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, ur_image_format_t * UrFormat, ur_image_desc_t * UrDesc) static
Definition at line 2903 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_row_pitch, _pi_image_desc::image_slice_pitch, _pi_image_desc::image_type, _pi_image_desc::image_width, _pi_image_desc::num_mip_levels, _pi_image_desc::num_samples, PI_IMAGE_CHANNEL_ORDER_A, PI_IMAGE_CHANNEL_ORDER_ABGR, PI_IMAGE_CHANNEL_ORDER_ARGB, PI_IMAGE_CHANNEL_ORDER_BGRA, PI_IMAGE_CHANNEL_ORDER_INTENSITY, PI_IMAGE_CHANNEL_ORDER_LUMINANCE, PI_IMAGE_CHANNEL_ORDER_R, PI_IMAGE_CHANNEL_ORDER_RA, PI_IMAGE_CHANNEL_ORDER_RG, PI_IMAGE_CHANNEL_ORDER_RGB, PI_IMAGE_CHANNEL_ORDER_RGBA, PI_IMAGE_CHANNEL_ORDER_RGBx, PI_IMAGE_CHANNEL_ORDER_RGx, PI_IMAGE_CHANNEL_ORDER_Rx, PI_IMAGE_CHANNEL_ORDER_sRGBA, PI_IMAGE_CHANNEL_TYPE_FLOAT, PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8, PI_IMAGE_CHANNEL_TYPE_SNORM_INT16, PI_IMAGE_CHANNEL_TYPE_SNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT16, PI_IMAGE_CHANNEL_TYPE_UNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, PI_TO_UR_MAP_IMAGE_CHANNEL_ORDER, PI_TO_UR_MAP_IMAGE_CHANNEL_TYPE, and PI_TO_UR_MAP_IMAGE_TYPE.
Referenced by piextMemImageAllocate(), piextMemImageCopy(), piextMemImageCreateWithNativeHandle(), piextMemMapExternalArray(), piextMemSampledImageCreate(), piextMemUnsampledImageCreate(), and piMemImageCreate().
pi2urImageInfoFlags()
static void pi2ur::pi2urImageInfoFlags (const pi_image_info PiFlags, ur_image_info_t * UrFlags) static
Definition at line 5360 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), PI_IMAGE_INFO_DEPTH, PI_IMAGE_INFO_ELEMENT_SIZE, PI_IMAGE_INFO_FORMAT, PI_IMAGE_INFO_HEIGHT, PI_IMAGE_INFO_ROW_PITCH, PI_IMAGE_INFO_SLICE_PITCH, PI_IMAGE_INFO_WIDTH, and PI_TO_UR_IMAGE_INFO.
Referenced by piextMemImageGetInfo().
piContextCreate()
pi_result pi2ur::piContextCreate (const pi_context_properties * Properties, pi_uint32 NumDevices, const pi_device * Devices, void(*)(const char *ErrInfo, const void *PrivateInfo, size_t CB, void *UserData) PFnNotify, void * UserData, pi_context * RetContext) inline
Definition at line 1548 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piContextCreate().
piContextGetInfo()
pi_result pi2ur::piContextGetInfo (pi_context Context, pi_context_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 1616 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), fixupInfoValueTypes(), HANDLE_ERRORS, PI_ASSERT, PI_CONTEXT_INFO_DEVICES, PI_CONTEXT_INFO_NUM_DEVICES, PI_CONTEXT_INFO_REFERENCE_COUNT, PI_EXT_CONTEXT_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES, PI_EXT_CONTEXT_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES, PI_EXT_CONTEXT_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES, PI_EXT_CONTEXT_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES, PI_EXT_ONEAPI_CONTEXT_INFO_USM_FILL2D_SUPPORT, PI_EXT_ONEAPI_CONTEXT_INFO_USM_MEMCPY2D_SUPPORT, and PI_EXT_ONEAPI_CONTEXT_INFO_USM_MEMSET2D_SUPPORT.
Referenced by piContextGetInfo().
piContextRelease()
pi_result pi2ur::piContextRelease (pi_context Context) inline
Definition at line 1679 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piContextRelease().
piContextRetain()
pi_result pi2ur::piContextRetain (pi_context Context) inline
Definition at line 1671 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piContextRetain().
piDeviceGetInfo()
pi_result pi2ur::piDeviceGetInfo (pi_device Device, pi_device_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 1040 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_DEVICE_INFO_ADDRESS_BITS, PI_DEVICE_INFO_ATOMIC_64, PI_DEVICE_INFO_AVAILABLE, PI_DEVICE_INFO_BACKEND_VERSION, PI_DEVICE_INFO_BUILD_ON_SUBDEVICE, PI_DEVICE_INFO_BUILT_IN_KERNELS, PI_DEVICE_INFO_COMPILER_AVAILABLE, PI_DEVICE_INFO_DEVICE_ID, PI_DEVICE_INFO_DOUBLE_FP_CONFIG, PI_DEVICE_INFO_DRIVER_VERSION, PI_DEVICE_INFO_ENDIAN_LITTLE, PI_DEVICE_INFO_ERROR_CORRECTION_SUPPORT, PI_DEVICE_INFO_EXECUTION_CAPABILITIES, PI_DEVICE_INFO_EXTENSIONS, PI_DEVICE_INFO_GLOBAL_MEM_CACHE_SIZE, PI_DEVICE_INFO_GLOBAL_MEM_CACHE_TYPE, PI_DEVICE_INFO_GLOBAL_MEM_CACHELINE_SIZE, PI_DEVICE_INFO_GLOBAL_MEM_SIZE, PI_DEVICE_INFO_GPU_EU_COUNT, PI_DEVICE_INFO_GPU_EU_COUNT_PER_SUBSLICE, PI_DEVICE_INFO_GPU_EU_SIMD_WIDTH, PI_DEVICE_INFO_GPU_HW_THREADS_PER_EU, PI_DEVICE_INFO_GPU_SLICES, PI_DEVICE_INFO_GPU_SUBSLICES_PER_SLICE, PI_DEVICE_INFO_HALF_FP_CONFIG, PI_DEVICE_INFO_HOST_UNIFIED_MEMORY, PI_DEVICE_INFO_IL_VERSION, PI_DEVICE_INFO_IMAGE2D_MAX_HEIGHT, PI_DEVICE_INFO_IMAGE2D_MAX_WIDTH, PI_DEVICE_INFO_IMAGE3D_MAX_DEPTH, PI_DEVICE_INFO_IMAGE3D_MAX_HEIGHT, PI_DEVICE_INFO_IMAGE3D_MAX_WIDTH, PI_DEVICE_INFO_IMAGE_MAX_ARRAY_SIZE, PI_DEVICE_INFO_IMAGE_MAX_BUFFER_SIZE, PI_DEVICE_INFO_IMAGE_SRGB, PI_DEVICE_INFO_IMAGE_SUPPORT, PI_DEVICE_INFO_LINKER_AVAILABLE, PI_DEVICE_INFO_LOCAL_MEM_SIZE, PI_DEVICE_INFO_LOCAL_MEM_TYPE, PI_DEVICE_INFO_MAX_CLOCK_FREQUENCY, PI_DEVICE_INFO_MAX_COMPUTE_UNITS, PI_DEVICE_INFO_MAX_CONSTANT_ARGS, PI_DEVICE_INFO_MAX_CONSTANT_BUFFER_SIZE, PI_DEVICE_INFO_MAX_MEM_ALLOC_SIZE, PI_DEVICE_INFO_MAX_MEM_BANDWIDTH, PI_DEVICE_INFO_MAX_NUM_SUB_GROUPS, PI_DEVICE_INFO_MAX_PARAMETER_SIZE, PI_DEVICE_INFO_MAX_READ_IMAGE_ARGS, PI_DEVICE_INFO_MAX_SAMPLERS, PI_DEVICE_INFO_MAX_WORK_GROUP_SIZE, PI_DEVICE_INFO_MAX_WORK_ITEM_DIMENSIONS, PI_DEVICE_INFO_MAX_WORK_ITEM_SIZES, PI_DEVICE_INFO_MAX_WRITE_IMAGE_ARGS, PI_DEVICE_INFO_MEM_BASE_ADDR_ALIGN, PI_DEVICE_INFO_NAME, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_CHAR, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_DOUBLE, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_FLOAT, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_HALF, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_INT, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_LONG, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_SHORT, PI_DEVICE_INFO_OPENCL_C_VERSION, PI_DEVICE_INFO_PARENT_DEVICE, PI_DEVICE_INFO_PARTITION_AFFINITY_DOMAIN, PI_DEVICE_INFO_PARTITION_MAX_SUB_DEVICES, PI_DEVICE_INFO_PARTITION_PROPERTIES, PI_DEVICE_INFO_PARTITION_TYPE, PI_DEVICE_INFO_PCI_ADDRESS, PI_DEVICE_INFO_PLATFORM, PI_DEVICE_INFO_PREFERRED_INTEROP_USER_SYNC, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_CHAR, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_DOUBLE, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_FLOAT, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_HALF, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_INT, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_LONG, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_SHORT, PI_DEVICE_INFO_PRINTF_BUFFER_SIZE, PI_DEVICE_INFO_PROFILE, PI_DEVICE_INFO_PROFILING_TIMER_RESOLUTION, PI_DEVICE_INFO_QUEUE_PROPERTIES, PI_DEVICE_INFO_REFERENCE_COUNT, PI_DEVICE_INFO_SINGLE_FP_CONFIG, PI_DEVICE_INFO_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS, PI_DEVICE_INFO_SUB_GROUP_SIZES_INTEL, PI_DEVICE_INFO_TYPE, PI_DEVICE_INFO_USM_CROSS_SHARED_SUPPORT, PI_DEVICE_INFO_USM_DEVICE_SUPPORT, PI_DEVICE_INFO_USM_HOST_SUPPORT, PI_DEVICE_INFO_USM_SINGLE_SHARED_SUPPORT, PI_DEVICE_INFO_USM_SYSTEM_SHARED_SUPPORT, PI_DEVICE_INFO_UUID, PI_DEVICE_INFO_VENDOR, PI_DEVICE_INFO_VENDOR_ID, PI_DEVICE_INFO_VERSION, PI_EXT_CODEPLAY_DEVICE_INFO_MAX_REGISTERS_PER_WORK_GROUP, PI_EXT_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES, PI_EXT_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES, PI_EXT_DEVICE_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES, PI_EXT_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES, PI_EXT_INTEL_DEVICE_INFO_ESIMD_SUPPORT, PI_EXT_INTEL_DEVICE_INFO_FREE_MEMORY, PI_EXT_INTEL_DEVICE_INFO_MAX_COMPUTE_QUEUE_INDICES, PI_EXT_INTEL_DEVICE_INFO_MEM_CHANNEL_SUPPORT, PI_EXT_INTEL_DEVICE_INFO_MEMORY_BUS_WIDTH, PI_EXT_INTEL_DEVICE_INFO_MEMORY_CLOCK_RATE, PI_EXT_ONEAPI_DEVICE_INFO_BFLOAT16_MATH_FUNCTIONS, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_1D_USM_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_2D_USM_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_SHARED_USM_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D_USM, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D_USM, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D, PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D_USM, PI_EXT_ONEAPI_DEVICE_INFO_COMMAND_BUFFER_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_COMMAND_BUFFER_UPDATE_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_COMPONENT_DEVICES, PI_EXT_ONEAPI_DEVICE_INFO_COMPOSITE_DEVICE, PI_EXT_ONEAPI_DEVICE_INFO_CUBEMAP_SEAMLESS_FILTERING_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_CUBEMAP_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_ENQUEUE_NATIVE_COMMAND_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_IMAGE_PITCH_ALIGN, PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_MEMORY_EXPORT_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_MEMORY_IMPORT_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_SEMAPHORE_EXPORT_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_SEMAPHORE_IMPORT_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_IP_VERSION, PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_HEIGHT, PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_PITCH, PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_WIDTH, PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_3D, PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_ANISOTROPY_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_LEVEL_REFERENCE_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_MAX_ANISOTROPY, PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_SUPPORT, PI_EXT_ONEAPI_DEVICE_INFO_SUPPORTS_VIRTUAL_MEM, PI_EXT_ONEAPI_DEVICE_INFO_TIMESTAMP_RECORDING_SUPPORT, PI_TO_UR_MAP_DEVICE_INFO, and ur2piDeviceInfoValue().
Referenced by piDeviceGetInfo().
piDevicePartition()
pi_result pi2ur::piDevicePartition (pi_device Device, const pi_device_partition_property * Properties, pi_uint32 NumEntries, pi_device * SubDevices, pi_uint32 * NumSubDevices) inline
Definition at line 1405 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), HANDLE_ERRORS, PI_ASSERT, PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN, PI_DEVICE_PARTITION_BY_COUNTS, PI_DEVICE_PARTITION_EQUALLY, and PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE.
Referenced by piDevicePartition().
piDeviceRelease()
pi_result pi2ur::piDeviceRelease (pi_device Device) inline
Definition at line 1015 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piDeviceRelease().
piDeviceRetain()
pi_result pi2ur::piDeviceRetain (pi_device Device) inline
Definition at line 1008 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piDeviceRetain().
piDevicesGet()
pi_result pi2ur::piDevicesGet (pi_platform Platform, pi_device_type DeviceType, pi_uint32 NumEntries, pi_device * Devices, pi_uint32 * NumDevices) inline
Definition at line 977 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_DEVICE_TYPE_ACC, PI_DEVICE_TYPE_ALL, PI_DEVICE_TYPE_CPU, and PI_DEVICE_TYPE_GPU.
Referenced by piDevicesGet().
piEnqueueEventsWait()
pi_result pi2ur::piEnqueueEventsWait (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 4164 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEnqueueEventsWait().
piEnqueueEventsWaitWithBarrier()
pi_result pi2ur::piEnqueueEventsWaitWithBarrier (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 4145 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEnqueueEventsWaitWithBarrier().
piEnqueueKernelLaunch()
pi_result pi2ur::piEnqueueKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t * GlobalWorkOffset, const size_t * GlobalWorkSize, const size_t * LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3745 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEnqueueKernelLaunch().
piEnqueueMemBufferCopy()
pi_result pi2ur::piEnqueueMemBufferCopy (pi_queue Queue, pi_mem SrcMem, pi_mem DstMem, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3984 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEnqueueMemBufferCopy().
piEnqueueMemBufferCopyRect()
pi_result pi2ur::piEnqueueMemBufferCopyRect (pi_queue Queue, pi_mem SrcMem, pi_mem DstMem, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3950 of file pi2ur.hpp.
References pi_buff_rect_region_struct::depth_scalar, HANDLE_ERRORS, pi_buff_rect_region_struct::height_scalar, PI_ASSERT, pi_buff_rect_region_struct::width_bytes, pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, and pi_buff_rect_offset_struct::z_scalar.
Referenced by piEnqueueMemBufferCopyRect().
piEnqueueMemBufferFill()
pi_result pi2ur::piEnqueueMemBufferFill (pi_queue Queue, pi_mem Buffer, const void * Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3904 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEnqueueMemBufferFill().
piEnqueueMemBufferMap()
pi_result pi2ur::piEnqueueMemBufferMap (pi_queue Queue, pi_mem Mem, pi_bool BlockingMap, pi_map_flags MapFlags, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent, void ** RetMap) inline
Definition at line 3849 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_MAP_READ, PI_MAP_WRITE, and PI_MAP_WRITE_INVALIDATE_REGION.
Referenced by piEnqueueMemBufferMap().
piEnqueueMemBufferRead()
pi_result pi2ur::piEnqueueMemBufferRead (pi_queue Queue, pi_mem Src, pi_bool BlockingRead, size_t Offset, size_t Size, void * Dst, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 4122 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEnqueueMemBufferRead().
piEnqueueMemBufferReadRect()
pi_result pi2ur::piEnqueueMemBufferReadRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingRead, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 4087 of file pi2ur.hpp.
References pi_buff_rect_region_struct::depth_scalar, HANDLE_ERRORS, pi_buff_rect_region_struct::height_scalar, PI_ASSERT, pi_buff_rect_region_struct::width_bytes, pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, and pi_buff_rect_offset_struct::z_scalar.
Referenced by piEnqueueMemBufferReadRect().
piEnqueueMemBufferWrite()
pi_result pi2ur::piEnqueueMemBufferWrite (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, size_t Offset, size_t Size, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 4063 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEnqueueMemBufferWrite().
piEnqueueMemBufferWriteRect()
pi_result pi2ur::piEnqueueMemBufferWriteRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 4029 of file pi2ur.hpp.
References pi_buff_rect_region_struct::depth_scalar, HANDLE_ERRORS, pi_buff_rect_region_struct::height_scalar, PI_ASSERT, pi_buff_rect_region_struct::width_bytes, pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, and pi_buff_rect_offset_struct::z_scalar.
Referenced by piEnqueueMemBufferWriteRect().
piEnqueueMemImageCopy()
pi_result pi2ur::piEnqueueMemImageCopy (pi_queue Queue, pi_mem SrcImage, pi_mem DstImage, pi_image_offset SrcOrigin, pi_image_offset DstOrigin, pi_image_region Region, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3244 of file pi2ur.hpp.
References pi_image_region_struct::depth, HANDLE_ERRORS, pi_image_region_struct::height, PI_ASSERT, pi_image_region_struct::width, pi_image_offset_struct::x, pi_image_offset_struct::y, and pi_image_offset_struct::z.
Referenced by piEnqueueMemImageCopy().
piEnqueueMemImageFill()
pi_result pi2ur::piEnqueueMemImageFill (pi_queue Queue, pi_mem Image, const void * FillColor, const size_t * Origin, const size_t * Region, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event) inline
Definition at line 2190 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), and PI_ASSERT.
Referenced by piEnqueueMemImageFill().
piEnqueueMemImageRead()
pi_result pi2ur::piEnqueueMemImageRead (pi_queue Queue, pi_mem Image, pi_bool BlockingRead, pi_image_offset Origin, pi_image_region Region, size_t RowPitch, size_t SlicePitch, void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3823 of file pi2ur.hpp.
References pi_image_region_struct::depth, HANDLE_ERRORS, pi_image_region_struct::height, PI_ASSERT, pi_image_region_struct::width, pi_image_offset_struct::x, pi_image_offset_struct::y, and pi_image_offset_struct::z.
Referenced by piEnqueueMemImageRead().
piEnqueueMemImageWrite()
pi_result pi2ur::piEnqueueMemImageWrite (pi_queue Queue, pi_mem Image, pi_bool BlockingWrite, pi_image_offset Origin, pi_image_region Region, size_t InputRowPitch, size_t InputSlicePitch, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3794 of file pi2ur.hpp.
References pi_image_region_struct::depth, HANDLE_ERRORS, pi_image_region_struct::height, PI_ASSERT, pi_image_region_struct::width, pi_image_offset_struct::x, pi_image_offset_struct::y, and pi_image_offset_struct::z.
Referenced by piEnqueueMemImageWrite().
piEnqueueMemUnmap()
pi_result pi2ur::piEnqueueMemUnmap (pi_queue Queue, pi_mem Mem, void * MappedPtr, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3882 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEnqueueMemUnmap().
piEnqueueTimestampRecordingExp()
pi_result pi2ur::piEnqueueTimestampRecordingExp (pi_queue Queue, pi_bool Blocking, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) inline
Definition at line 4399 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piEnqueueTimestampRecordingExp().
piEventCreate()
pi_result pi2ur::piEventCreate (pi_context Context, pi_event * RetEvent) inline
Definition at line 4322 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piEventCreate().
piEventGetInfo()
pi_result pi2ur::piEventGetInfo (pi_event Event, pi_event_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 4240 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_EVENT_INFO_COMMAND_EXECUTION_STATUS, PI_EVENT_INFO_COMMAND_QUEUE, PI_EVENT_INFO_COMMAND_TYPE, PI_EVENT_INFO_CONTEXT, and PI_EVENT_INFO_REFERENCE_COUNT.
Referenced by piEventGetInfo().
piEventGetProfilingInfo()
pi_result pi2ur::piEventGetProfilingInfo (pi_event Event, pi_profiling_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 4284 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_PROFILING_INFO_COMMAND_END, PI_PROFILING_INFO_COMMAND_QUEUED, PI_PROFILING_INFO_COMMAND_START, and PI_PROFILING_INFO_COMMAND_SUBMIT.
Referenced by piEventGetProfilingInfo().
piEventRelease()
pi_result pi2ur::piEventRelease (pi_event Event) inline
Definition at line 4390 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEventRelease().
piEventRetain()
pi_result pi2ur::piEventRetain (pi_event Event) inline
Definition at line 4381 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piEventRetain().
piEventSetCallback()
pi_result pi2ur::piEventSetCallback (pi_event Event, pi_int32 CommandExecCallbackType, void(*)(pi_event Event, pi_int32 EventCommandStatus, void *UserData) PFnNotify, void * UserData) inline
Definition at line 4361 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die().
Referenced by piEventSetCallback().
piEventSetStatus()
pi_result pi2ur::piEventSetStatus (pi_event Event, pi_int32 ExecutionStatus) inline
Definition at line 4374 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die().
Referenced by piEventSetStatus().
piEventsWait()
pi_result pi2ur::piEventsWait (pi_uint32 NumEvents, const pi_event * EventsWaitList) inline
Definition at line 4226 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piEventsWait().
piextBindlessImageSamplerCreate()
pi_result pi2ur::piextBindlessImageSamplerCreate (pi_context Context, const pi_sampler_properties * SamplerProperties, float MinMipmapLevelClamp, float MaxMipmapLevelClamp, float MaxAnisotropy, pi_sampler * RetSampler) inline
Definition at line 5111 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_SAMPLER_ADDRESSING_MODE_CLAMP, PI_SAMPLER_ADDRESSING_MODE_CLAMP_TO_EDGE, PI_SAMPLER_ADDRESSING_MODE_MIRRORED_REPEAT, PI_SAMPLER_ADDRESSING_MODE_NONE, PI_SAMPLER_ADDRESSING_MODE_REPEAT, PI_SAMPLER_CUBEMAP_FILTER_MODE_DISJOINTED, PI_SAMPLER_CUBEMAP_FILTER_MODE_SEAMLESS, PI_SAMPLER_FILTER_MODE_LINEAR, PI_SAMPLER_FILTER_MODE_NEAREST, PI_SAMPLER_PROPERTIES_ADDRESSING_MODE, PI_SAMPLER_PROPERTIES_CUBEMAP_FILTER_MODE, PI_SAMPLER_PROPERTIES_FILTER_MODE, PI_SAMPLER_PROPERTIES_MIP_FILTER_MODE, and PI_SAMPLER_PROPERTIES_NORMALIZED_COORDS.
Referenced by piextBindlessImageSamplerCreate().
piextCommandBufferAdviseUSM()
pi_result pi2ur::piextCommandBufferAdviseUSM (pi_ext_command_buffer CommandBuffer, const void * Ptr, size_t Length, pi_mem_advice Advice, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4838 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY, PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY_HOST, PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION, PI_MEM_ADVICE_CUDA_SET_READ_MOSTLY, PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY, PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY_HOST, PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION, PI_MEM_ADVICE_CUDA_UNSET_READ_MOSTLY, and PI_MEM_ADVICE_RESET.
Referenced by piextCommandBufferAdviseUSM().
piextCommandBufferCreate()
pi_result pi2ur::piextCommandBufferCreate (pi_context Context, pi_device Device, const pi_ext_command_buffer_desc * Desc, pi_ext_command_buffer * RetCommandBuffer) inline
Definition at line 4560 of file pi2ur.hpp.
References pi_ext_command_buffer_desc::enable_profiling, HANDLE_ERRORS, pi_ext_command_buffer_desc::is_in_order, and pi_ext_command_buffer_desc::is_updatable.
Referenced by piextCommandBufferCreate().
piextCommandBufferFillUSM()
pi_result pi2ur::piextCommandBufferFillUSM (pi_ext_command_buffer CommandBuffer, void * Ptr, const void * Pattern, size_t PatternSize, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4803 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferFillUSM().
piextCommandBufferFinalize()
pi_result pi2ur::piextCommandBufferFinalize (pi_ext_command_buffer CommandBuffer) inline
Definition at line 4600 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferFinalize().
piextCommandBufferMemBufferCopy()
pi_result pi2ur::piextCommandBufferMemBufferCopy (pi_ext_command_buffer CommandBuffer, pi_mem SrcMem, pi_mem DstMem, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4643 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferMemBufferCopy().
piextCommandBufferMemBufferCopyRect()
pi_result pi2ur::piextCommandBufferMemBufferCopyRect (pi_ext_command_buffer CommandBuffer, pi_mem SrcMem, pi_mem DstMem, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4661 of file pi2ur.hpp.
References pi_buff_rect_region_struct::depth_scalar, HANDLE_ERRORS, pi_buff_rect_region_struct::height_scalar, pi_buff_rect_region_struct::width_bytes, pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, and pi_buff_rect_offset_struct::z_scalar.
Referenced by piextCommandBufferMemBufferCopyRect().
piextCommandBufferMemBufferFill()
pi_result pi2ur::piextCommandBufferMemBufferFill (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, const void * Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4786 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextCommandBufferMemBufferFill().
piextCommandBufferMemBufferRead()
pi_result pi2ur::piextCommandBufferMemBufferRead (pi_ext_command_buffer CommandBuffer, pi_mem Src, size_t Offset, size_t Size, void * Dst, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4720 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextCommandBufferMemBufferRead().
piextCommandBufferMemBufferReadRect()
pi_result pi2ur::piextCommandBufferMemBufferReadRect (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void * Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4690 of file pi2ur.hpp.
References pi_buff_rect_region_struct::depth_scalar, HANDLE_ERRORS, pi_buff_rect_region_struct::height_scalar, PI_ASSERT, pi_buff_rect_region_struct::width_bytes, pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, and pi_buff_rect_offset_struct::z_scalar.
Referenced by piextCommandBufferMemBufferReadRect().
piextCommandBufferMemBufferWrite()
pi_result pi2ur::piextCommandBufferMemBufferWrite (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, size_t Offset, size_t Size, const void * Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4768 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextCommandBufferMemBufferWrite().
piextCommandBufferMemBufferWriteRect()
pi_result pi2ur::piextCommandBufferMemBufferWriteRect (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void * Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4737 of file pi2ur.hpp.
References pi_buff_rect_region_struct::depth_scalar, HANDLE_ERRORS, pi_buff_rect_region_struct::height_scalar, PI_ASSERT, pi_buff_rect_region_struct::width_bytes, pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, and pi_buff_rect_offset_struct::z_scalar.
Referenced by piextCommandBufferMemBufferWriteRect().
piextCommandBufferMemcpyUSM()
pi_result pi2ur::piextCommandBufferMemcpyUSM (pi_ext_command_buffer CommandBuffer, void * DstPtr, const void * SrcPtr, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4629 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferMemcpyUSM().
piextCommandBufferNDRangeKernel()
pi_result pi2ur::piextCommandBufferNDRangeKernel (pi_ext_command_buffer CommandBuffer, pi_kernel Kernel, pi_uint32 WorkDim, const size_t * GlobalWorkOffset, const size_t * GlobalWorkSize, const size_t * LocalWorkSize, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint, pi_ext_command_buffer_command * Command) inline
Definition at line 4609 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferNDRangeKernel().
piextCommandBufferPrefetchUSM()
pi_result pi2ur::piextCommandBufferPrefetchUSM (pi_ext_command_buffer CommandBuffer, const void * Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point * SyncPointWaitList, pi_ext_sync_point * SyncPoint) inline
Definition at line 4817 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextCommandBufferPrefetchUSM().
piextCommandBufferRelease()
pi_result pi2ur::piextCommandBufferRelease (pi_ext_command_buffer CommandBuffer) inline
Definition at line 4590 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferRelease().
piextCommandBufferReleaseCommand()
pi_result pi2ur::piextCommandBufferReleaseCommand (pi_ext_command_buffer_command command) inline
Definition at line 4967 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferReleaseCommand().
piextCommandBufferRetain()
pi_result pi2ur::piextCommandBufferRetain (pi_ext_command_buffer CommandBuffer) inline
Definition at line 4580 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferRetain().
piextCommandBufferRetainCommand()
pi_result pi2ur::piextCommandBufferRetainCommand (pi_ext_command_buffer_command command) inline
Definition at line 4959 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextCommandBufferRetainCommand().
piextCommandBufferUpdateKernelLaunch()
pi_result pi2ur::piextCommandBufferUpdateKernelLaunch (pi_ext_command_buffer_command command, pi_ext_command_buffer_update_kernel_launch_desc * desc) inline
Definition at line 4901 of file pi2ur.hpp.
References pi_ext_command_buffer_update_kernel_launch_desc::global_work_offset, pi_ext_command_buffer_update_kernel_launch_desc::global_work_size, HANDLE_ERRORS, pi_ext_command_buffer_update_kernel_launch_desc::local_work_size, pi_ext_command_buffer_update_kernel_launch_desc::mem_obj_arg_list, pi_ext_command_buffer_update_kernel_launch_desc::num_mem_obj_args, pi_ext_command_buffer_update_kernel_launch_desc::num_ptr_args, pi_ext_command_buffer_update_kernel_launch_desc::num_value_args, pi_ext_command_buffer_update_kernel_launch_desc::num_work_dim, pi_ext_command_buffer_update_kernel_launch_desc::ptr_arg_list, and pi_ext_command_buffer_update_kernel_launch_desc::value_arg_list.
Referenced by piextCommandBufferUpdateKernelLaunch().
piextContextCreateWithNativeHandle()
pi_result pi2ur::piextContextCreateWithNativeHandle (pi_native_handle NativeHandle, pi_uint32 NumDevices, const pi_device * Devices, bool OwnNativeHandle, pi_context * RetContext) inline
Definition at line 1588 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, and PiGetAdapter().
Referenced by piextContextCreateWithNativeHandle().
piextContextGetNativeHandle()
pi_result pi2ur::piextContextGetNativeHandle (pi_context Context, pi_native_handle * NativeHandle) inline
Definition at line 1577 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextContextGetNativeHandle().
piextContextSetExtendedDeleter()
pi_result pi2ur::piextContextSetExtendedDeleter (pi_context Context, pi_context_extended_deleter Function, void * UserData) inline
Definition at line 1568 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextContextSetExtendedDeleter().
piextDestroyExternalSemaphore()
pi_result pi2ur::piextDestroyExternalSemaphore (pi_context Context, pi_device Device, pi_interop_semaphore_handle SemHandle) inline
Definition at line 5639 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextDestroyExternalSemaphore().
piextDeviceCreateWithNativeHandle()
pi_result pi2ur::piextDeviceCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform Platform, pi_device * Device) inline
Definition at line 1381 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, and PiGetAdapter().
Referenced by piextDeviceCreateWithNativeHandle().
piextDeviceGetNativeHandle()
pi_result pi2ur::piextDeviceGetNativeHandle (pi_device Device, pi_native_handle * NativeHandle) inline
Definition at line 1367 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextDeviceGetNativeHandle().
piextDeviceSelectBinary()
pi_result pi2ur::piextDeviceSelectBinary (pi_device Device, pi_device_binary * Binaries, pi_uint32 NumBinaries, pi_uint32 * SelectedBinaryInd) inline
Definition at line 1489 of file pi2ur.hpp.
References __SYCL_PI_DEVICE_BINARY_TARGET_AMDGCN, __SYCL_PI_DEVICE_BINARY_TARGET_NATIVE_CPU, __SYCL_PI_DEVICE_BINARY_TARGET_NVPTX64, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV32, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_FPGA, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_X86_64, __SYCL_PI_DEVICE_BINARY_TARGET_UNKNOWN, and HANDLE_ERRORS.
Referenced by piextDeviceSelectBinary().
piextDisablePeerAccess()
pi_result pi2ur::piextDisablePeerAccess (pi_device command_device, pi_device peer_device) inline
Definition at line 4990 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextDisablePeerAccess().
piextEnablePeerAccess()
pi_result pi2ur::piextEnablePeerAccess (pi_device command_device, pi_device peer_device) inline
Definition at line 4980 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextEnablePeerAccess().
piextEnqueueCommandBuffer()
pi_result pi2ur::piextEnqueueCommandBuffer (pi_ext_command_buffer CommandBuffer, pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) inline
Definition at line 4881 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextEnqueueCommandBuffer().
piextEnqueueCooperativeKernelLaunch()
pi_result pi2ur::piextEnqueueCooperativeKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t * GlobalWorkOffset, const size_t * GlobalWorkSize, const size_t * LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3769 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextEnqueueCooperativeKernelLaunch().
piextEnqueueDeviceGlobalVariableRead()
pi_result pi2ur::piextEnqueueDeviceGlobalVariableRead (pi_queue Queue, pi_program Program, const char * Name, pi_bool BlockingRead, size_t Count, size_t Offset, void * Dst, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
API reading data from a device global variable to host.
Parameters
Queue is the queue
Program is the program containing the device global variable
Name is the unique identifier for the device global variable
BlockingRead is true if the read should block
Count is the number of bytes to copy
Offset is the byte offset into the device global variable to start copying
Dst is a pointer to where the data must be copied to
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 2745 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextEnqueueDeviceGlobalVariableRead().
piextEnqueueDeviceGlobalVariableWrite()
pi_result pi2ur::piextEnqueueDeviceGlobalVariableWrite (pi_queue Queue, pi_program Program, const char * Name, pi_bool BlockingWrite, size_t Count, size_t Offset, const void * Src, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
API for writing data from host to a device global variable.
Parameters
Queue is the queue
Program is the program containing the device global variable
Name is the unique identifier for the device global variable
BlockingWrite is true if the write should block
Count is the number of bytes to copy
Offset is the byte offset into the device global variable to start copying
Src is a pointer to where the data must be copied from
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 2713 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextEnqueueDeviceGlobalVariableWrite().
piextEnqueueNativeCommand()
pi_result pi2ur::piextEnqueueNativeCommand (pi_queue Queue, pi_enqueue_native_command_function Fn, void * Data, pi_uint32 NumMems, const pi_mem * MemList, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) inline
Definition at line 5890 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextEnqueueNativeCommand().
piextEnqueueReadHostPipe()
pi_result pi2ur::piextEnqueueReadHostPipe (pi_queue queue, pi_program program, const char * pipe_symbol, pi_bool blocking, void * ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event * events_waitlist, pi_event * event) inline
Definition at line 4187 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextEnqueueReadHostPipe().
piextEnqueueWriteHostPipe()
pi_result pi2ur::piextEnqueueWriteHostPipe (pi_queue queue, pi_program program, const char * pipe_symbol, pi_bool blocking, void * ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event * events_waitlist, pi_event * event) inline
Definition at line 4205 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextEnqueueWriteHostPipe().
piextEventCreateWithNativeHandle()
pi_result pi2ur::piextEventCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_event * Event) inline
Definition at line 4337 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextEventCreateWithNativeHandle().
piextEventGetNativeHandle()
pi_result pi2ur::piextEventGetNativeHandle (pi_event Event, pi_native_handle * NativeHandle) inline
Definition at line 4269 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextEventGetNativeHandle().
piextGetDeviceFunctionPointer()
pi_result pi2ur::piextGetDeviceFunctionPointer (pi_device Device, pi_program Program, const char * FunctionName, pi_uint64 * FunctionPointerRet) inline
Definition at line 2209 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextGetDeviceFunctionPointer().
piextGetGlobalVariablePointer()
pi_result pi2ur::piextGetGlobalVariablePointer (pi_device Device, pi_program Program, const char * GlobalVariableName, size_t * GlobalVariableSize, void ** GlobalVariablePointerRet) inline
Definition at line 2228 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextGetGlobalVariablePointer().
piextImportExternalMemory()
pi_result pi2ur::piextImportExternalMemory (pi_context Context, pi_device Device, pi_external_mem_descriptor * MemDescriptor, pi_interop_mem_handle * RetHandle) inline
Definition at line 5437 of file pi2ur.hpp.
References pi_external_handle::file_descriptor, pi_external_mem_descriptor::handle, HANDLE_ERRORS, pi_external_mem_descriptor::handleType, pi_external_mem_descriptor::memorySizeBytes, opaque_fd, PI_ASSERT, pi_external_handle::win32_handle, win32_nt_dx12_resource, and win32_nt_handle.
Referenced by piextImportExternalMemory().
piextImportExternalSemaphore()
pi_result pi2ur::piextImportExternalSemaphore (pi_context Context, pi_device Device, pi_external_semaphore_descriptor * SemDescriptor, pi_interop_semaphore_handle * RetHandle) inline
Definition at line 5572 of file pi2ur.hpp.
References pi_external_handle::file_descriptor, pi_external_semaphore_descriptor::handle, HANDLE_ERRORS, pi_external_semaphore_descriptor::handleType, opaque_fd, PI_ASSERT, pi_external_handle::win32_handle, win32_nt_dx12_fence, and win32_nt_handle.
Referenced by piextImportExternalSemaphore().
piextImportExternalSemaphoreOpaqueFD()
pi_result pi2ur::piextImportExternalSemaphoreOpaqueFD (pi_context Context, pi_device Device, int FileDescriptor, pi_interop_semaphore_handle * RetHandle) inline
Definition at line 5545 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextImportExternalSemaphoreOpaqueFD().
piextKernelCreateWithNativeHandle()
pi_result pi2ur::piextKernelCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, pi_program Program, bool OwnNativeHandle, pi_kernel * Kernel) inline
Definition at line 2330 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextKernelCreateWithNativeHandle().
piextKernelGetNativeHandle()
pi_result pi2ur::piextKernelGetNativeHandle (pi_kernel Kernel, pi_native_handle * NativeHandle) inline
Definition at line 2673 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextKernelGetNativeHandle().
piextKernelSetArgMemObj()
pi_result pi2ur::piextKernelSetArgMemObj (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_mem_obj_property * ArgProperties, const pi_mem * ArgValue) inline
Definition at line 2246 of file pi2ur.hpp.
References HANDLE_ERRORS, _pi_mem_obj_property::mem_access, PI_ACCESS_READ_ONLY, PI_ACCESS_READ_WRITE, PI_ACCESS_WRITE_ONLY, PI_ASSERT, PI_KERNEL_ARG_MEM_OBJ_ACCESS, _pi_mem_obj_property::pNext, and _pi_mem_obj_property::type.
Referenced by piextKernelSetArgMemObj().
piextKernelSetArgPointer()
pi_result pi2ur::piextKernelSetArgPointer (pi_kernel Kernel, pi_uint32 ArgIndex, size_t , const void * ArgValue) inline
Definition at line 2585 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextKernelSetArgPointer().
piextKernelSetArgSampler()
pi_result pi2ur::piextKernelSetArgSampler (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_sampler * ArgValue) inline
Definition at line 4520 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextKernelSetArgSampler().
piextKernelSuggestMaxCooperativeGroupCount()
pi_result pi2ur::piextKernelSuggestMaxCooperativeGroupCount (pi_kernel Kernel, size_t LocalWorkSize, size_t DynamicSharedMemorySize, pi_uint32 * GroupCountRet) inline
Definition at line 2687 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextKernelSuggestMaxCooperativeGroupCount().
piextMemCreateWithNativeHandle()
pi_result pi2ur::piextMemCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_mem * Mem) inline
Definition at line 3275 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemCreateWithNativeHandle().
piextMemGetNativeHandle()
pi_result pi2ur::piextMemGetNativeHandle (pi_mem Mem, pi_device Dev, pi_native_handle * NativeHandle) inline
Definition at line 3229 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemGetNativeHandle().
piextMemImageAllocate()
pi_result pi2ur::piextMemImageAllocate (pi_context Context, pi_device Device, pi_image_format * ImageFormat, pi_image_desc * ImageDesc, pi_image_mem_handle * RetMem) inline
Definition at line 5035 of file pi2ur.hpp.
References HANDLE_ERRORS, pi2urImageDesc(), and PI_ASSERT.
Referenced by piextMemImageAllocate().
piextMemImageCopy()
pi_result pi2ur::piextMemImageCopy (pi_queue Queue, void * DstPtr, void * SrcPtr, const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, const pi_image_copy_flags Flags, pi_image_offset SrcOffset, pi_image_offset DstOffset, pi_image_region CopyExtent, pi_image_region HostExtent, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) inline
Definition at line 5287 of file pi2ur.hpp.
References pi_image_region_struct::depth, HANDLE_ERRORS, pi_image_region_struct::height, pi2urImageCopyFlags(), pi2urImageDesc(), PI_ASSERT, pi_image_region_struct::width, pi_image_offset_struct::x, pi_image_offset_struct::y, and pi_image_offset_struct::z.
Referenced by piextMemImageCopy().
piextMemImageCreateWithNativeHandle()
pi_result pi2ur::piextMemImageCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, pi_mem * RetImage) inline
Definition at line 3153 of file pi2ur.hpp.
References HANDLE_ERRORS, pi2urImageDesc(), and PI_ASSERT.
Referenced by piextMemImageCreateWithNativeHandle().
piextMemImageFree()
pi_result pi2ur::piextMemImageFree (pi_context Context, pi_device Device, pi_image_mem_handle MemoryHandle) inline
Definition at line 5237 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemImageFree().
piextMemImageGetInfo()
pi_result pi2ur::piextMemImageGetInfo (pi_image_mem_handle MemHandle, pi_image_info ParamName, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 5381 of file pi2ur.hpp.
References HANDLE_ERRORS, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, pi2urImageInfoFlags(), PI_IMAGE_INFO_FORMAT, and ur2piImageFormat().
Referenced by piextMemImageGetInfo().
piextMemImportOpaqueFD()
pi_result pi2ur::piextMemImportOpaqueFD (pi_context Context, pi_device Device, size_t Size, int FileDescriptor, pi_interop_mem_handle * RetHandle) inline
Definition at line 5410 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemImportOpaqueFD().
piextMemMapExternalArray()
pi_result pi2ur::piextMemMapExternalArray (pi_context Context, pi_device Device, pi_image_format * ImageFormat, pi_image_desc * ImageDesc, pi_interop_mem_handle MemHandle, pi_image_mem_handle * RetMem) inline
Definition at line 5502 of file pi2ur.hpp.
References HANDLE_ERRORS, pi2urImageDesc(), and PI_ASSERT.
Referenced by piextMemMapExternalArray().
piextMemMipmapFree()
pi_result pi2ur::piextMemMipmapFree (pi_context Context, pi_device Device, pi_image_mem_handle MemoryHandle) inline
Definition at line 5253 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemMipmapFree().
piextMemMipmapGetLevel()
pi_result pi2ur::piextMemMipmapGetLevel (pi_context Context, pi_device Device, pi_image_mem_handle MipMem, unsigned int Level, pi_image_mem_handle * RetMem) inline
Definition at line 5218 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemMipmapGetLevel().
piextMemReleaseInterop()
pi_result pi2ur::piextMemReleaseInterop (pi_context Context, pi_device Device, pi_interop_mem_handle ExtMem) inline
Definition at line 5527 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemReleaseInterop().
piextMemSampledImageCreate()
pi_result pi2ur::piextMemSampledImageCreate (pi_context Context, pi_device Device, pi_image_mem_handle ImgMem, pi_image_format * ImageFormat, pi_image_desc * ImageDesc, pi_sampler Sampler, pi_image_handle * RetHandle) inline
Definition at line 5084 of file pi2ur.hpp.
References HANDLE_ERRORS, pi2urImageDesc(), and PI_ASSERT.
Referenced by piextMemSampledImageCreate().
piextMemSampledImageHandleDestroy()
pi_result pi2ur::piextMemSampledImageHandleDestroy (pi_context Context, pi_device Device, pi_image_handle Handle) inline
Definition at line 5344 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemSampledImageHandleDestroy().
piextMemUnsampledImageCreate()
pi_result pi2ur::piextMemUnsampledImageCreate (pi_context Context, pi_device Device, pi_image_mem_handle ImgMem, pi_image_format * ImageFormat, pi_image_desc * ImageDesc, pi_image_handle * RetHandle) inline
Definition at line 5058 of file pi2ur.hpp.
References HANDLE_ERRORS, pi2urImageDesc(), and PI_ASSERT.
Referenced by piextMemUnsampledImageCreate().
piextMemUnsampledImageHandleDestroy()
pi_result pi2ur::piextMemUnsampledImageHandleDestroy (pi_context Context, pi_device Device, pi_image_handle Handle) inline
Definition at line 5328 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextMemUnsampledImageHandleDestroy().
piextPeerAccessGetInfo()
pi_result pi2ur::piextPeerAccessGetInfo (pi_device command_device, pi_device peer_device, pi_peer_attr attr, size_t param_value_size, void * param_value, size_t * param_value_size_ret) inline
Definition at line 5001 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_PEER_ACCESS_SUPPORTED, and PI_PEER_ATOMICS_SUPPORTED.
Referenced by piextPeerAccessGetInfo().
piextPhysicalMemCreate()
pi_result pi2ur::piextPhysicalMemCreate (pi_context Context, pi_device Device, size_t MemSize, pi_physical_mem * RetPhyscialMem) inline
Definition at line 5731 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextPhysicalMemCreate().
piextPhysicalMemRelease()
pi_result pi2ur::piextPhysicalMemRelease (pi_physical_mem PhysicalMem) inline
Definition at line 5761 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextPhysicalMemRelease().
piextPhysicalMemRetain()
pi_result pi2ur::piextPhysicalMemRetain (pi_physical_mem PhysicalMem) inline
Definition at line 5750 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextPhysicalMemRetain().
piextPlatformCreateWithNativeHandle()
pi_result pi2ur::piextPlatformCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform * Platform) inline
Definition at line 878 of file pi2ur.hpp.
References PI_ASSERT, and PiGetAdapter().
Referenced by piextPlatformCreateWithNativeHandle().
piextPlatformGetNativeHandle()
pi_result pi2ur::piextPlatformGetNativeHandle (pi_platform Platform, pi_native_handle * NativeHandle) inline
Definition at line 861 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextPlatformGetNativeHandle().
piextPluginGetOpaqueData()
pi_result pi2ur::piextPluginGetOpaqueData (void * opaque_data_param, void ** opaque_data_return) inline
Definition at line 954 of file pi2ur.hpp.
Referenced by piextPluginGetOpaqueData().
piextProgramCreateWithNativeHandle()
pi_result pi2ur::piextProgramCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_program * Program) inline
Definition at line 2423 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextProgramCreateWithNativeHandle().
piextProgramGetNativeHandle()
pi_result pi2ur::piextProgramGetNativeHandle (pi_program Program, pi_native_handle * NativeHandle) inline
Definition at line 2407 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextProgramGetNativeHandle().
piextProgramSetSpecializationConstant()
pi_result pi2ur::piextProgramSetSpecializationConstant (pi_program Program, pi_uint32 SpecID, size_t Size, const void * SpecValue) inline
Definition at line 2156 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextProgramSetSpecializationConstant().
piextQueueCreate()
pi_result pi2ur::piextQueueCreate (pi_context Context, pi_device Device, pi_queue_properties * Properties, pi_queue * Queue) inline
Definition at line 1690 of file pi2ur.hpp.
References __SYCL_PI_CUDA_SYNC_WITH_DEFAULT, __SYCL_PI_CUDA_USE_DEFAULT_STREAM, HANDLE_ERRORS, PI_ASSERT, PI_EXT_ONEAPI_QUEUE_FLAG_DISCARD_EVENTS, PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_HIGH, PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_LOW, PI_EXT_QUEUE_FLAG_SUBMISSION_IMMEDIATE, PI_EXT_QUEUE_FLAG_SUBMISSION_NO_IMMEDIATE, PI_QUEUE_COMPUTE_INDEX, PI_QUEUE_FLAG_ON_DEVICE, PI_QUEUE_FLAG_ON_DEVICE_DEFAULT, PI_QUEUE_FLAG_OUT_OF_ORDER_EXEC_MODE_ENABLE, PI_QUEUE_FLAG_PROFILING_ENABLE, and PI_QUEUE_FLAGS.
Referenced by piextQueueCreate(), and piQueueCreate().
piextQueueCreateWithNativeHandle()
pi_result pi2ur::piextQueueCreateWithNativeHandle (pi_native_handle NativeHandle, int32_t NativeHandleDesc, pi_context Context, pi_device Device, bool OwnNativeHandle, pi_queue_properties * Properties, pi_queue * Queue) inline
Definition at line 1767 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_EXT_ONEAPI_QUEUE_FLAG_DISCARD_EVENTS, PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_HIGH, PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_LOW, PI_QUEUE_FLAG_ON_DEVICE, PI_QUEUE_FLAG_ON_DEVICE_DEFAULT, PI_QUEUE_FLAG_OUT_OF_ORDER_EXEC_MODE_ENABLE, and PI_QUEUE_FLAG_PROFILING_ENABLE.
Referenced by piextQueueCreateWithNativeHandle().
piextQueueGetNativeHandle()
pi_result pi2ur::piextQueueGetNativeHandle (pi_queue Queue, pi_native_handle * NativeHandle, int32_t * NativeHandleDesc) inline
Definition at line 1813 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextQueueGetNativeHandle().
piextSignalExternalSemaphore()
pi_result pi2ur::piextSignalExternalSemaphore (pi_queue Queue, pi_interop_semaphore_handle SemHandle, bool HasSignalValue, pi_uint64 SignalValue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) inline
Definition at line 5675 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextSignalExternalSemaphore().
piextUSMDeviceAlloc()
pi_result pi2ur::piextUSMDeviceAlloc (void ** ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties * Properties, size_t Size, pi_uint32 Alignment) inline
Definition at line 3296 of file pi2ur.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, HANDLE_ERRORS, and PI_MEM_USM_ALLOC_BUFFER_LOCATION.
Referenced by piextUSMDeviceAlloc().
piextUSMEnqueueFill2D()
pi_result pi2ur::piextUSMEnqueueFill2D (pi_queue Queue, void * Ptr, size_t Pitch, size_t PatternSize, const void * Pattern, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event * EventsWaitList, pi_event * Event) inline
USM 2D Fill API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
pattern is a pointer with the bytes of the pattern to set
pattern_size is the size in bytes of the pattern
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 3550 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextUSMEnqueueFill2D().
piextUSMEnqueueMemAdvise()
pi_result pi2ur::piextUSMEnqueueMemAdvise (pi_queue Queue, const void * Ptr, size_t Length, pi_mem_advice Advice, pi_event * OutEvent) inline
USM memadvise API to govern behavior of automatic migration mechanisms.
Parameters
Queue is the queue to submit to
Ptr is the data to be advised
Length is the size in bytes of the meory to advise
Advice is device specific advice
Event is the event that represents this operation
Definition at line 3488 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY, PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY_HOST, PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION, PI_MEM_ADVICE_CUDA_SET_READ_MOSTLY, PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY, PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY_HOST, PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION, PI_MEM_ADVICE_CUDA_UNSET_READ_MOSTLY, PI_MEM_ADVICE_HIP_SET_COARSE_GRAINED, PI_MEM_ADVICE_HIP_UNSET_COARSE_GRAINED, and PI_MEM_ADVICE_RESET.
Referenced by piextUSMEnqueueMemAdvise().
piextUSMEnqueueMemcpy()
pi_result pi2ur::piextUSMEnqueueMemcpy (pi_queue Queue, pi_bool Blocking, void * DstPtr, const void * SrcPtr, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 4009 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextUSMEnqueueMemcpy().
piextUSMEnqueueMemcpy2D()
pi_result pi2ur::piextUSMEnqueueMemcpy2D (pi_queue Queue, pi_bool Blocking, void * DstPtr, size_t DstPitch, const void * SrcPtr, size_t SrcPitch, size_t Width, size_t Height, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
USM 2D Memcpy API.
Parameters
queue is the queue to submit to
blocking is whether this operation should block the host
dst_ptr is the location the data will be copied
dst_pitch is the total width of the destination memory including padding
src_ptr is the data to be copied
dst_pitch is the total width of the source memory including padding
width is width in bytes of each row to be copied
height is height the columns to be copied
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 3712 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextUSMEnqueueMemcpy2D().
piextUSMEnqueueMemset()
pi_result pi2ur::piextUSMEnqueueMemset (pi_queue Queue, void * Ptr, pi_int32 Value, size_t Count, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Definition at line 3926 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextUSMEnqueueMemset().
piextUSMEnqueueMemset2D()
pi_result pi2ur::piextUSMEnqueueMemset2D (pi_queue Queue, void * Ptr, size_t Pitch, int Value, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event * EventsWaitList, pi_event * Event) inline
Definition at line 3569 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die().
Referenced by piextUSMEnqueueMemset2D().
piextUSMEnqueuePrefetch()
pi_result pi2ur::piextUSMEnqueuePrefetch (pi_queue Queue, const void * Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * OutEvent) inline
Hint to migrate memory to the device.
Parameters
Queue is the queue to submit to
Ptr points to the memory to migrate
Size is the number of bytes to migrate
Flags is a bitfield used to specify memory migration options
NumEventsInWaitList is the number of events to wait on
EventsWaitList is an array of events to wait on
Event is the event that represents this operation
Definition at line 3451 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextUSMEnqueuePrefetch().
piextUSMFree()
pi_result pi2ur::piextUSMFree (pi_context Context, void * Ptr) inline
Definition at line 3415 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextUSMFree().
piextUSMGetMemAllocInfo()
pi_result pi2ur::piextUSMGetMemAllocInfo (pi_context Context, const void * Ptr, pi_mem_alloc_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 3588 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), HANDLE_ERRORS, PI_ASSERT, PI_MEM_ALLOC_BASE_PTR, PI_MEM_ALLOC_DEVICE, PI_MEM_ALLOC_SIZE, PI_MEM_ALLOC_TYPE, and ur2piUSMAllocInfoValue().
Referenced by piextUSMGetMemAllocInfo().
piextUSMHostAlloc()
pi_result pi2ur::piextUSMHostAlloc (void ** ResultPtr, pi_context Context, pi_usm_mem_properties * Properties, size_t Size, pi_uint32 Alignment) inline
Definition at line 2847 of file pi2ur.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, HANDLE_ERRORS, and PI_MEM_USM_ALLOC_BUFFER_LOCATION.
Referenced by piextUSMHostAlloc().
piextUSMImport()
pi_result pi2ur::piextUSMImport (const void * HostPtr, size_t Size, pi_context Context) inline
Definition at line 3630 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextUSMImport().
piextUSMPitchedAlloc()
pi_result pi2ur::piextUSMPitchedAlloc (void ** ResultPtr, size_t * ResultPitch, pi_context Context, pi_device Device, pi_usm_mem_properties * Properties, size_t WidthInBytes, size_t Height, unsigned int ElementSizeBytes) inline
Definition at line 3330 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextUSMPitchedAlloc().
piextUSMRelease()
pi_result pi2ur::piextUSMRelease (const void * HostPtr, pi_context Context) inline
Definition at line 3642 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextUSMRelease().
piextUSMSharedAlloc()
pi_result pi2ur::piextUSMSharedAlloc (void ** ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties * Properties, size_t Size, pi_uint32 Alignment) inline
Definition at line 3351 of file pi2ur.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, HANDLE_ERRORS, PI_MEM_ALLOC_DEVICE_READ_ONLY, PI_MEM_ALLOC_FLAGS, PI_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE, PI_MEM_ALLOC_INITIAL_PLACEMENT_HOST, PI_MEM_ALLOC_WRTITE_COMBINED, and PI_MEM_USM_ALLOC_BUFFER_LOCATION.
Referenced by piextUSMSharedAlloc().
piextVirtualMemFree()
pi_result pi2ur::piextVirtualMemFree (pi_context Context, const void * Ptr, size_t RangeSize) inline
Definition at line 5784 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextVirtualMemFree().
piextVirtualMemGetInfo()
pi_result pi2ur::piextVirtualMemGetInfo (pi_context Context, const void * Ptr, size_t RangeSize, pi_virtual_mem_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 5855 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_EXT_ONEAPI_VIRTUAL_MEM_INFO_ACCESS_MODE, and ur2piVirtualMemInfoValue().
Referenced by piextVirtualMemGetInfo().
piextVirtualMemGranularityGetInfo()
pi_result pi2ur::piextVirtualMemGranularityGetInfo (pi_context Context, pi_device Device, pi_virtual_mem_granularity_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 5702 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_EXT_ONEAPI_VIRTUAL_MEM_GRANULARITY_INFO_MINIMUM, and PI_EXT_ONEAPI_VIRTUAL_MEM_GRANULARITY_INFO_RECOMMENDED.
Referenced by piextVirtualMemGranularityGetInfo().
piextVirtualMemMap()
pi_result pi2ur::piextVirtualMemMap (pi_context Context, const void * Ptr, size_t RangeSize, pi_physical_mem PhysicalMem, size_t Offset, pi_virtual_access_flags Flags) inline
Definition at line 5817 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_VIRTUAL_ACCESS_FLAG_READ_ONLY, and PI_VIRTUAL_ACCESS_FLAG_RW.
Referenced by piextVirtualMemMap().
piextVirtualMemReserve()
pi_result pi2ur::piextVirtualMemReserve (pi_context Context, const void * Start, size_t RangeSize, void ** RetPtr) inline
Definition at line 5771 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextVirtualMemReserve().
piextVirtualMemSetAccess()
pi_result pi2ur::piextVirtualMemSetAccess (pi_context Context, const void * Ptr, size_t RangeSize, pi_virtual_access_flags Flags) inline
Definition at line 5797 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_VIRTUAL_ACCESS_FLAG_READ_ONLY, and PI_VIRTUAL_ACCESS_FLAG_RW.
Referenced by piextVirtualMemSetAccess().
piextVirtualMemUnmap()
pi_result pi2ur::piextVirtualMemUnmap (pi_context Context, const void * Ptr, size_t RangeSize) inline
Definition at line 5842 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextVirtualMemUnmap().
piextWaitExternalSemaphore()
pi_result pi2ur::piextWaitExternalSemaphore (pi_queue Queue, pi_interop_semaphore_handle SemHandle, bool HasWaitValue, pi_uint64 WaitValue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) inline
Definition at line 5655 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piextWaitExternalSemaphore().
PiGetAdapter()
pi_result pi2ur::PiGetAdapter (ur_adapter_handle_t & adapter) inline
Definition at line 830 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piextContextCreateWithNativeHandle(), piextDeviceCreateWithNativeHandle(), piextPlatformCreateWithNativeHandle(), and piPlatformsGet().
piGetDeviceAndHostTimer()
pi_result pi2ur::piGetDeviceAndHostTimer (pi_device Device, uint64_t * DeviceTime, uint64_t * HostTime) inline
Definition at line 1481 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piGetDeviceAndHostTimer().
piKernelCreate()
pi_result pi2ur::piKernelCreate (pi_program Program, const char * KernelName, pi_kernel * RetKernel) inline
Definition at line 2173 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piKernelCreate().
piKernelGetGroupInfo()
pi_result pi2ur::piKernelGetGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_group_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 2495 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), HANDLE_ERRORS, PI_ASSERT, PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE, PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE, PI_KERNEL_GROUP_INFO_LOCAL_MEM_SIZE, PI_KERNEL_GROUP_INFO_NUM_REGS, PI_KERNEL_GROUP_INFO_PREFERRED_WORK_GROUP_SIZE_MULTIPLE, PI_KERNEL_GROUP_INFO_PRIVATE_MEM_SIZE, and PI_KERNEL_GROUP_INFO_WORK_GROUP_SIZE.
Referenced by piKernelGetGroupInfo().
piKernelGetInfo()
pi_result pi2ur::piKernelGetInfo (pi_kernel Kernel, pi_kernel_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 2443 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_KERNEL_INFO_ATTRIBUTES, PI_KERNEL_INFO_CONTEXT, PI_KERNEL_INFO_FUNCTION_NAME, PI_KERNEL_INFO_NUM_ARGS, PI_KERNEL_INFO_PROGRAM, and PI_KERNEL_INFO_REFERENCE_COUNT.
Referenced by piKernelGetInfo().
piKernelGetSubGroupInfo()
pi_result pi2ur::piKernelGetSubGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_sub_group_info ParamName, size_t InputValueSize, const void * InputValue, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 2596 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_KERNEL_COMPILE_NUM_SUB_GROUPS, PI_KERNEL_COMPILE_SUB_GROUP_SIZE_INTEL, PI_KERNEL_MAX_NUM_SUB_GROUPS, and PI_KERNEL_MAX_SUB_GROUP_SIZE.
Referenced by piKernelGetSubGroupInfo().
piKernelRelease()
pi_result pi2ur::piKernelRelease (pi_kernel Kernel) inline
Definition at line 2562 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piKernelRelease().
piKernelRetain()
pi_result pi2ur::piKernelRetain (pi_kernel Kernel) inline
Definition at line 2551 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piKernelRetain().
piKernelSetArg()
pi_result pi2ur::piKernelSetArg (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void * ArgValue) inline
Definition at line 2301 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piKernelSetArg().
piKernelSetArgPointer()
pi_result pi2ur::piKernelSetArgPointer (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void * ArgValue) inline
Definition at line 2317 of file pi2ur.hpp.
References HANDLE_ERRORS.
piKernelSetExecInfo()
pi_result pi2ur::piKernelSetExecInfo (pi_kernel Kernel, pi_kernel_exec_info ParamName, size_t ParamValueSize, const void * ParamValue) inline
Definition at line 2362 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), HANDLE_ERRORS, PI_ASSERT, PI_EXT_KERNEL_EXEC_INFO_CACHE_CONFIG, PI_EXT_KERNEL_EXEC_INFO_CACHE_DEFAULT, PI_EXT_KERNEL_EXEC_INFO_CACHE_LARGE_DATA, PI_EXT_KERNEL_EXEC_INFO_CACHE_LARGE_SLM, PI_USM_INDIRECT_ACCESS, and PI_USM_PTRS.
Referenced by piKernelSetExecInfo().
piMemBufferCreate()
pi_result pi2ur::piMemBufferCreate (pi_context Context, pi_mem_flags Flags, size_t Size, void * HostPtr, pi_mem * RetMem, const pi_mem_properties * properties) inline
Definition at line 2772 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_MEM_ACCESS_READ_ONLY, PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_ALLOC, PI_MEM_FLAGS_HOST_PTR_COPY, PI_MEM_FLAGS_HOST_PTR_USE, PI_MEM_PROPERTIES_ALLOC_BUFFER_LOCATION, and PI_MEM_PROPERTIES_CHANNEL.
Referenced by piMemBufferCreate().
piMemBufferPartition()
pi_result pi2ur::piMemBufferPartition (pi_mem Buffer, pi_mem_flags Flags, pi_buffer_create_type BufferCreateType, void * BufferCreateInfo, pi_mem * RetMem) inline
Definition at line 3182 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_BUFFER_CREATE_TYPE_REGION, PI_MEM_ACCESS_READ_ONLY, PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_ALLOC, PI_MEM_FLAGS_HOST_PTR_COPY, and PI_MEM_FLAGS_HOST_PTR_USE.
Referenced by piMemBufferPartition().
piMemGetInfo()
pi_result pi2ur::piMemGetInfo (pi_mem Mem, pi_mem_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 2877 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), HANDLE_ERRORS, PI_ASSERT, PI_MEM_CONTEXT, and PI_MEM_SIZE.
Referenced by piMemGetInfo().
piMemImageCreate()
pi_result pi2ur::piMemImageCreate (pi_context Context, pi_mem_flags Flags, const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, void * HostPtr, pi_mem * RetImage) inline
Definition at line 3111 of file pi2ur.hpp.
References HANDLE_ERRORS, pi2urImageDesc(), PI_ASSERT, PI_MEM_ACCESS_READ_ONLY, PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_ALLOC, PI_MEM_FLAGS_HOST_PTR_COPY, and PI_MEM_FLAGS_HOST_PTR_USE.
Referenced by piMemImageCreate().
piMemImageGetInfo()
pi_result pi2ur::piMemImageGetInfo (pi_mem Image, pi_image_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 3653 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_IMAGE_INFO_DEPTH, PI_IMAGE_INFO_ELEMENT_SIZE, PI_IMAGE_INFO_FORMAT, PI_IMAGE_INFO_HEIGHT, PI_IMAGE_INFO_ROW_PITCH, PI_IMAGE_INFO_SLICE_PITCH, and PI_IMAGE_INFO_WIDTH.
Referenced by piMemImageGetInfo().
piMemRelease()
pi_result pi2ur::piMemRelease (pi_mem Mem) inline
Definition at line 3432 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piMemRelease().
piMemRetain()
pi_result pi2ur::piMemRetain (pi_mem Mem) inline
Definition at line 3422 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piMemRetain().
piPlatformGetInfo()
pi_result pi2ur::piPlatformGetInfo (pi_platform Platform, pi_platform_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 901 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), fixupInfoValueTypes(), HANDLE_ERRORS, PI_ASSERT, PI_EXT_PLATFORM_INFO_BACKEND, PI_PLATFORM_INFO_EXTENSIONS, PI_PLATFORM_INFO_NAME, PI_PLATFORM_INFO_PROFILE, PI_PLATFORM_INFO_VENDOR, PI_PLATFORM_INFO_VERSION, and ur2piPlatformInfoValue().
Referenced by piPlatformGetInfo().
piPlatformsGet()
pi_result pi2ur::piPlatformsGet (pi_uint32 NumEntries, pi_platform * Platforms, pi_uint32 * NumPlatforms) inline
Definition at line 848 of file pi2ur.hpp.
References HANDLE_ERRORS, and PiGetAdapter().
Referenced by piPlatformsGet().
piPluginGetBackendOption()
pi_result pi2ur::piPluginGetBackendOption (pi_platform Platform, const char * FrontendOption, const char ** PlatformOption) inline
Definition at line 961 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piPluginGetBackendOption().
piPluginGetLastError()
pi_result pi2ur::piPluginGetLastError (char ** Message) inline
Definition at line 1023 of file pi2ur.hpp.
References ur2piResult().
Referenced by piPluginGetLastError().
piProgramBuild()
pi_result pi2ur::piProgramBuild (pi_program Program, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData) inline
Definition at line 2127 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, and ur2piResult().
Referenced by piProgramBuild().
piProgramCompile()
pi_result pi2ur::piProgramCompile (pi_program Program, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, pi_uint32 NumInputHeaders, const pi_program * InputHeaders, const char ** HeaderIncludeNames, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData) inline
Definition at line 2089 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, and ur2piResult().
Referenced by piProgramCompile().
piProgramCreate()
pi_result pi2ur::piProgramCreate (pi_context Context, const void * ILBytes, size_t Length, pi_program * Program) inline
Definition at line 1932 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piProgramCreate().
piProgramCreateWithBinary()
pi_result pi2ur::piProgramCreateWithBinary (pi_context Context, pi_uint32 NumDevices, const pi_device * DeviceList, const size_t * Lengths, const unsigned char ** Binaries, size_t NumMetadataEntries, const pi_device_binary_property * Metadata, pi_int32 * BinaryStatus, pi_program * Program) inline
Definition at line 1951 of file pi2ur.hpp.
References HANDLE_ERRORS, mapPIMetadataToUR(), and PI_ASSERT.
Referenced by piProgramCreateWithBinary().
piProgramGetBuildInfo()
pi_result pi2ur::piProgramGetBuildInfo (pi_program Program, pi_device Device, pi_program_build_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 2633 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), HANDLE_ERRORS, PI_PROGRAM_BUILD_INFO_BINARY_TYPE, PI_PROGRAM_BUILD_INFO_LOG, PI_PROGRAM_BUILD_INFO_OPTIONS, PI_PROGRAM_BUILD_INFO_STATUS, and ur2piProgramBuildInfoValue().
Referenced by piProgramGetBuildInfo().
piProgramGetInfo()
pi_result pi2ur::piProgramGetInfo (pi_program Program, pi_program_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 1997 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), HANDLE_ERRORS, PI_ASSERT, PI_PROGRAM_INFO_BINARIES, PI_PROGRAM_INFO_BINARY_SIZES, PI_PROGRAM_INFO_CONTEXT, PI_PROGRAM_INFO_DEVICES, PI_PROGRAM_INFO_KERNEL_NAMES, PI_PROGRAM_INFO_NUM_DEVICES, PI_PROGRAM_INFO_NUM_KERNELS, PI_PROGRAM_INFO_REFERENCE_COUNT, and PI_PROGRAM_INFO_SOURCE.
Referenced by piProgramGetInfo().
piProgramLink()
pi_result pi2ur::piProgramLink (pi_context Context, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, pi_uint32 NumInputPrograms, const pi_program * InputPrograms, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData, pi_program * RetProgram) inline
Definition at line 2057 of file pi2ur.hpp.
References PI_ASSERT, and ur2piResult().
Referenced by piProgramLink().
piProgramRelease()
pi_result pi2ur::piProgramRelease (pi_program Program) inline
Definition at line 2573 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piProgramRelease().
piProgramRetain()
pi_result pi2ur::piProgramRetain (pi_program Program) inline
Definition at line 2351 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piProgramRetain().
piQueueCreate()
pi_result pi2ur::piQueueCreate (pi_context Context, pi_device Device, pi_queue_properties Flags, pi_queue * Queue) inline
Definition at line 1761 of file pi2ur.hpp.
References PI_QUEUE_FLAGS, and piextQueueCreate().
Referenced by piQueueCreate().
piQueueFinish()
pi_result pi2ur::piQueueFinish (pi_queue Queue) inline
Definition at line 1843 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piQueueFinish().
piQueueFlush()
pi_result pi2ur::piQueueFlush (pi_queue Queue) inline
Definition at line 1915 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piQueueFlush().
piQueueGetInfo()
pi_result pi2ur::piQueueGetInfo (pi_queue Queue, pi_queue_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 1854 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), HANDLE_ERRORS, PI_ASSERT, PI_EXT_ONEAPI_QUEUE_INFO_EMPTY, PI_QUEUE_INFO_CONTEXT, PI_QUEUE_INFO_DEVICE, PI_QUEUE_INFO_DEVICE_DEFAULT, PI_QUEUE_INFO_PROPERTIES, PI_QUEUE_INFO_REFERENCE_COUNT, and PI_QUEUE_INFO_SIZE.
Referenced by piQueueGetInfo().
piQueueRelease()
pi_result pi2ur::piQueueRelease (pi_queue Queue) inline
Definition at line 1833 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piQueueRelease().
piQueueRetain()
pi_result pi2ur::piQueueRetain (pi_queue Queue) inline
Definition at line 1904 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piQueueRetain().
piSamplerCreate()
pi_result pi2ur::piSamplerCreate (pi_context Context, const pi_sampler_properties * SamplerProperties, pi_sampler * RetSampler) inline
Definition at line 4421 of file pi2ur.hpp.
References HANDLE_ERRORS, PI_ASSERT, PI_SAMPLER_ADDRESSING_MODE_CLAMP, PI_SAMPLER_ADDRESSING_MODE_CLAMP_TO_EDGE, PI_SAMPLER_ADDRESSING_MODE_MIRRORED_REPEAT, PI_SAMPLER_ADDRESSING_MODE_NONE, PI_SAMPLER_ADDRESSING_MODE_REPEAT, PI_SAMPLER_FILTER_MODE_LINEAR, PI_SAMPLER_FILTER_MODE_NEAREST, PI_SAMPLER_PROPERTIES_ADDRESSING_MODE, PI_SAMPLER_PROPERTIES_FILTER_MODE, and PI_SAMPLER_PROPERTIES_NORMALIZED_COORDS.
Referenced by piSamplerCreate().
piSamplerGetInfo()
pi_result pi2ur::piSamplerGetInfo (pi_sampler Sampler, pi_sampler_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet) inline
Definition at line 4482 of file pi2ur.hpp.
References fixupInfoValueTypes(), HANDLE_ERRORS, PI_SAMPLER_INFO_ADDRESSING_MODE, PI_SAMPLER_INFO_CONTEXT, PI_SAMPLER_INFO_FILTER_MODE, PI_SAMPLER_INFO_NORMALIZED_COORDS, PI_SAMPLER_INFO_REFERENCE_COUNT, and ur2piSamplerInfoValue().
Referenced by piSamplerGetInfo().
piSamplerRelease()
pi_result pi2ur::piSamplerRelease (pi_sampler Sampler) inline
Definition at line 4542 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piSamplerRelease().
piSamplerRetain()
pi_result pi2ur::piSamplerRetain (pi_sampler Sampler) inline
Definition at line 4531 of file pi2ur.hpp.
References HANDLE_ERRORS, and PI_ASSERT.
Referenced by piSamplerRetain().
piTearDown()
pi_result pi2ur::piTearDown (void * PluginParameter) inline
Definition at line 808 of file pi2ur.hpp.
References HANDLE_ERRORS.
Referenced by piTearDown().
ur2piImageFormat()
static void pi2ur::ur2piImageFormat (const ur_image_format_t * UrFormat, pi_image_format * PiFormat) static
Definition at line 3024 of file pi2ur.hpp.
References sycl::_V1::detail::pi::die(), PI_IMAGE_CHANNEL_ORDER_A, PI_IMAGE_CHANNEL_ORDER_ABGR, PI_IMAGE_CHANNEL_ORDER_ARGB, PI_IMAGE_CHANNEL_ORDER_BGRA, PI_IMAGE_CHANNEL_ORDER_INTENSITY, PI_IMAGE_CHANNEL_ORDER_LUMINANCE, PI_IMAGE_CHANNEL_ORDER_R, PI_IMAGE_CHANNEL_ORDER_RA, PI_IMAGE_CHANNEL_ORDER_RG, PI_IMAGE_CHANNEL_ORDER_RGB, PI_IMAGE_CHANNEL_ORDER_RGBA, PI_IMAGE_CHANNEL_ORDER_RGBx, PI_IMAGE_CHANNEL_ORDER_RGx, PI_IMAGE_CHANNEL_ORDER_Rx, PI_IMAGE_CHANNEL_ORDER_sRGBA, PI_IMAGE_CHANNEL_TYPE_FLOAT, PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8, PI_IMAGE_CHANNEL_TYPE_SNORM_INT16, PI_IMAGE_CHANNEL_TYPE_SNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT16, PI_IMAGE_CHANNEL_TYPE_UNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8, UR_TO_PI_MAP_IMAGE_CHANNEL_ORDER, and UR_TO_PI_MAP_IMAGE_CHANNEL_TYPE.
Referenced by piextMemImageGetInfo().