DPC++ Runtime: cl::sycl::opencl Namespace Reference
cl::sycl::opencl Namespace Reference
Functions
platform make_platform (pi_native_handle NativeHandle)
device make_device (pi_native_handle NativeHandle)
context make_context (pi_native_handle NativeHandle)
queue make_queue (const context &Context, pi_native_handle InteropHandle)
template<typename T , typename detail::enable_if_t< std::is_same< T, platform >::value > * = nullptr>
T make (typename detail::interop< backend::opencl, T >::type Interop)
template<typename T , typename detail::enable_if_t< std::is_same< T, queue >::value > * = nullptr>
T make (const context &Context, typename detail::interop< backend::opencl, T >::type Interop)
program make_program (const context &Context, pi_native_handle NativeHandle)
Function Documentation
make() [1/2]
template<typename T , typename detail::enable_if_t< std::is_same< T, queue >::value > * = nullptr> T cl::sycl::opencl::make (const context & Context, typename detail::interop< backend::opencl, T >::type Interop)
Definition at line 71 of file opencl.hpp.
References make_queue().
make() [2/2]
template<typename T , typename detail::enable_if_t< std::is_same< T, platform >::value > * = nullptr> T cl::sycl::opencl::make (typename detail::interop< backend::opencl, T >::type Interop)
Definition at line 36 of file opencl.hpp.
References make_platform().
make_context()
context cl::sycl::opencl::make_context (pi_native_handle NativeHandle)
Definition at line 35 of file opencl.cpp.
make_device()
device cl::sycl::opencl::make_device (pi_native_handle NativeHandle)
Definition at line 29 of file opencl.cpp.
make_platform()
platform cl::sycl::opencl::make_platform (pi_native_handle NativeHandle)
Definition at line 23 of file opencl.cpp.
Referenced by make(), and cl::sycl::ext::oneapi::level_zero::make_platform().
make_program()
program cl::sycl::opencl::make_program (const context & Context, pi_native_handle NativeHandle)
Definition at line 41 of file opencl.cpp.
References cl::sycl::detail::getSyclObjImpl().
make_queue()
queue cl::sycl::opencl::make_queue (const context & Context, pi_native_handle InteropHandle)
Definition at line 52 of file opencl.cpp.
References cl::sycl::detail::getSyclObjImpl().
Referenced by make(), and cl::sycl::detail::make_queue().