DPC++ Runtime: cl::sycl::ext::intel::experimental::esimd::detail Namespace Reference
cl::sycl::ext::intel::experimental::esimd::detail Namespace Reference
Classes
struct accessor_mode_cap
class AccessorPrivateProxy
struct bitcast_helper
struct byte_type
struct byte_type< int >
struct byte_type< short >
struct byte_type< uint >
struct byte_type< ushort >
struct common_type
struct computation_type
Get the computation type.
struct compute_format_type
struct compute_format_type< detail::simd_view_impl< BaseTy, RegionTy >, EltTy >
struct compute_format_type< simd< Ty, N >, EltTy >
struct compute_format_type_2d
struct compute_format_type_2d< detail::simd_view_impl< BaseTy, RegionTy >, EltTy, Height, Width >
struct compute_format_type_2d< simd< Ty, N >, EltTy, Height, Width >
struct dword_type
struct dword_type< char >
struct dword_type< short >
struct dword_type< uchar >
struct dword_type< ushort >
struct element_type
struct element_type< detail::simd_view_impl< BaseTy, RegionTy > >
struct element_type< simd< Ty, N > >
struct is_esimd_arithmetic_type
struct is_esimd_arithmetic_type< Ty, __esimd_void_t< decltype(std::declval< Ty >()+std::declval< Ty >()), decltype(std::declval< Ty >() - std::declval< Ty >()), decltype(std::declval< Ty >() *std::declval< Ty >()), decltype(std::declval< Ty >()/std::declval< Ty >())> >
struct is_esimd_vector
type traits
struct is_esimd_vector< simd< T, N > >
struct is_simd_type
struct is_simd_type< detail::simd_view_impl< BaseTy, RegionTy > >
struct is_simd_type< simd< Ty, N > >
struct is_simd_v
struct is_simd_view_type
struct is_simd_view_type< detail::simd_view_impl< BaseTy, RegionTy > >
struct is_simd_view_v
struct is_sycl_accessor
struct is_sycl_accessor< sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > >
struct is_sycl_accessor_with
struct is_vectorizable
struct is_vectorizable< bool >
struct is_vectorizable_v
struct Log2
Compute binary logarithm of a constexpr with guaranteed compile-time evaluation.
struct Log2< N, false >
struct Log2< N, true >
struct make_esimd_void
struct NextPowerOf2
Compute next power of 2 of a constexpr with guaranteed compile-time evaluation.
struct NextPowerOf2< N, K, false >
struct NextPowerOf2< N, K, true >
struct OperandSize
ESIMD intrinsic operand size in bytes.
struct simd_type
Convert types into vector types.
struct simd_type< const T >
struct simd_type< T & >
struct simd_type< T && >
struct simd_type< vector_type< T, N > >
class simd_view_impl
The simd_view base class.
struct vector_type
struct word_type
struct word_type< char >
struct word_type< int >
struct word_type< uchar >
struct word_type< uint >
Typedefs
using accessor_mode_cap_val_t = bool
template<typename T , accessor_mode_cap_val_t Capability, sycl::access::target AccessTarget, typename RetT >
using EnableIfAccessor = sycl::detail::enable_if_t< detail::is_sycl_accessor_with< T, Capability, AccessTarget >::value, RetT >
using half = cl::sycl::detail::half_impl::StorageT
template<typename T >
using remove_cvref_t = csd::remove_cv_t< csd::remove_reference_t< T > >
template<class... Tys>
using __esimd_void_t = typename make_esimd_void< Tys... >::type
template<typename Ty , int N>
using vector_type_t = typename vector_type< Ty, N >::type
template<typename Ty , typename EltTy >
using compute_format_type_t = typename compute_format_type< Ty, EltTy >::type
template<typename Ty , typename EltTy , int Height, int Width>
using compute_format_type_2d_t = typename compute_format_type_2d< Ty, EltTy, Height, Width >::type
template<typename T1 , typename T2 = T1>
using compute_type_t = typename common_type< remove_cvref_t< T1 >, remove_cvref_t< T2 > >::type
template<typename T >
using is_esimd_scalar = typename std::bool_constant< cl::sycl::detail::is_arithmetic< T >::value >
template<typename T , int N>
using is_hw_int_type = typename std::bool_constant< std::is_integral_v< T > &&(sizeof(T)==N)>
template<typename T >
using is_qword_type = is_hw_int_type< T, 8 >
template<typename T >
using is_dword_type = is_hw_int_type< T, 4 >
template<typename T >
using is_word_type = is_hw_int_type< T, 2 >
template<typename T >
using is_byte_type = is_hw_int_type< T, 1 >
template<typename T , int N>
using is_hw_fp_type = typename std::bool_constant< std::is_floating_point_v< T > &&(sizeof(T)==N)>
template<typename T >
using is_fp_type = is_hw_fp_type< T, 4 >
template<typename T >
using is_df_type = is_hw_fp_type< T, 8 >
template<typename T >
using is_fp_or_dword_type = typename std::bool_constant< is_fp_type< T >::value||is_dword_type< T >::value >
Functions
template<typename BT , int BN, typename RTy >
__SEIEED::vector_type_t< typename RTy::element_type, RTy::length > ESIMD_INLINE readRegion (const __SEIEED::vector_type_t< BT, BN > &Base, RTy Region)
read from a basic region of a vector, return a vector
template<typename BT , int BN, typename T , typename U >
ESIMD_INLINE __SEIEED::vector_type_t< typename T::element_type, T::length > readRegion (const __SEIEED::vector_type_t< BT, BN > &Base, std::pair< T, U > Region)
read from a nested region of a vector, return a vector
template<int ElemsPerAddr, typename = sycl::detail::enable_if_t< (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)>>
constexpr unsigned int ElemsPerAddrEncoding ()
constexpr unsigned int ElemsPerAddrDecoding (unsigned int ElemsPerAddrEncoded)
template<sycl::access::mode Mode, accessor_mode_cap_val_t Cap>
constexpr bool accessor_mode_has_capability ()
template<typename To , typename From >
To convert (From Val)
template<typename U >
constexpr bool is_type ()
Base case for checking if a type U is one of the types.
template<typename U , typename T , typename... Ts>
constexpr bool is_type ()
template<typename ToEltTy , typename FromEltTy , int FromN, typename = csd::enable_if_t<is_vectorizable<ToEltTy>::value>>
ESIMD_INLINE csd::conditional_t< std::is_same< FromEltTy, ToEltTy >::value, vector_type_t< FromEltTy, FromN >, vector_type_t< ToEltTy, bitcast_helper< ToEltTy, FromEltTy, FromN >::nToElems()> > bitcast (vector_type_t< FromEltTy, FromN > Val)
std::ostream & operator<< (std::ostream &O, half const &rhs)
std::istream & operator>> (std::istream &I, half &rhs)
template<unsigned int N>
constexpr unsigned int getNextPowerOf2 ()
template<>
constexpr unsigned int getNextPowerOf2< 0 > ()
template<unsigned int N>
constexpr unsigned int log2 ()
static constexpr ESIMD_INLINE bool isPowerOf2 (unsigned int n)
Check if a given 32 bit positive integer is a power of 2 at compile time.
static constexpr ESIMD_INLINE bool isPowerOf2 (unsigned int n, unsigned int limit)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T0, SZ > __esimd_abs_common_internal (simd< T1, SZ > src0, int flag=saturation_off)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value, typename sycl::detail::remove_const_t< T0 > > __esimd_abs_common_internal (T1 src0, int flag=saturation_off)
template<atomic_op Op, typename T , int N, unsigned NumSrc>
constexpr bool check_atomic ()
Check the legality of an atomic call in terms of size and type.
Variables
template<rgba_channel Ch>
static constexpr uint8_t ch = 1 << static_cast<int>(Ch)
static constexpr uint8_t chR = ch<rgba_channel::R>
static constexpr uint8_t chG = ch<rgba_channel::G>
static constexpr uint8_t chB = ch<rgba_channel::B>
static constexpr uint8_t chA = ch<rgba_channel::A>
Typedef Documentation
__esimd_void_t
template<class... Tys> using cl::sycl::ext::intel::experimental::esimd::detail::__esimd_void_t = typedef typename make_esimd_void<Tys...>::type
Definition at line 46 of file types.hpp.
accessor_mode_cap_val_t
using cl::sycl::ext::intel::experimental::esimd::detail::accessor_mode_cap_val_t = typedef bool
Definition at line 45 of file sycl_util.hpp.
compute_format_type_2d_t
template<typename Ty , typename EltTy , int Height, int Width> using cl::sycl::ext::intel::experimental::esimd::detail::compute_format_type_2d_t = typedef typename compute_format_type_2d<Ty, EltTy, Height, Width>::type
Definition at line 136 of file types.hpp.
compute_format_type_t
template<typename Ty , typename EltTy > using cl::sycl::ext::intel::experimental::esimd::detail::compute_format_type_t = typedef typename compute_format_type<Ty, EltTy>::type
Definition at line 101 of file types.hpp.
compute_type_t
template<typename T1 , typename T2 = T1> using cl::sycl::ext::intel::experimental::esimd::detail::compute_type_t = typedef typename common_type<remove_cvref_t<T1>, remove_cvref_t<T2> >::type
Definition at line 193 of file types.hpp.
EnableIfAccessor
template<typename T , accessor_mode_cap_val_t Capability, sycl::access::target AccessTarget, typename RetT > using cl::sycl::ext::intel::experimental::esimd::detail::EnableIfAccessor = typedef sycl::detail::enable_if_t< detail::is_sycl_accessor_with<T, Capability, AccessTarget>::value, RetT>
Definition at line 82 of file sycl_util.hpp.
half
using cl::sycl::ext::intel::experimental::esimd::detail::half = typedef cl::sycl::detail::half_impl::StorageT
Definition at line 38 of file types.hpp.
is_byte_type
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::is_byte_type = typedef is_hw_int_type<T, 1>
Definition at line 96 of file util.hpp.
is_df_type
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::is_df_type = typedef is_hw_fp_type<T, 8>
Definition at line 103 of file util.hpp.
is_dword_type
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::is_dword_type = typedef is_hw_int_type<T, 4>
Definition at line 94 of file util.hpp.
is_esimd_scalar
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::is_esimd_scalar = typedef typename std::bool_constant<cl::sycl::detail::is_arithmetic<T>::value>
Definition at line 87 of file util.hpp.
is_fp_or_dword_type
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::is_fp_or_dword_type = typedef typename std::bool_constant<is_fp_type<T>::value || is_dword_type<T>::value>
Definition at line 108 of file util.hpp.
is_fp_type
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::is_fp_type = typedef is_hw_fp_type<T, 4>
Definition at line 102 of file util.hpp.
is_hw_fp_type
template<typename T , int N> using cl::sycl::ext::intel::experimental::esimd::detail::is_hw_fp_type = typedef typename std::bool_constant<std::is_floating_point_v<T> && (sizeof(T) == N)>
Definition at line 100 of file util.hpp.
is_hw_int_type
template<typename T , int N> using cl::sycl::ext::intel::experimental::esimd::detail::is_hw_int_type = typedef typename std::bool_constant<std::is_integral_v<T> && (sizeof(T) == N)>
Definition at line 91 of file util.hpp.
is_qword_type
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::is_qword_type = typedef is_hw_int_type<T, 8>
Definition at line 93 of file util.hpp.
is_word_type
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::is_word_type = typedef is_hw_int_type<T, 2>
Definition at line 95 of file util.hpp.
remove_cvref_t
template<typename T > using cl::sycl::ext::intel::experimental::esimd::detail::remove_cvref_t = typedef csd::remove_cv_t<csd::remove_reference_t<T> >
Definition at line 41 of file types.hpp.
vector_type_t
template<typename Ty , int N> using cl::sycl::ext::intel::experimental::esimd::detail::vector_type_t = typedef typename vector_type<Ty, N>::type
Definition at line 80 of file types.hpp.
Function Documentation
__esimd_abs_common_internal() [1/2]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T0, SZ> cl::sycl::ext::intel::experimental::esimd::detail::__esimd_abs_common_internal (simd< T1, SZ > src0, int flag = saturation_off)
Definition at line 56 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data(), and cl::sycl::ext::intel::experimental::esimd::saturation_on.
__esimd_abs_common_internal() [2/2]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::detail::__esimd_abs_common_internal (T1 src0, int flag = saturation_off)
Definition at line 68 of file math.hpp.
accessor_mode_has_capability()
template<sycl::access::mode Mode, accessor_mode_cap_val_t Cap> constexpr bool cl::sycl::ext::intel::experimental::esimd::detail::accessor_mode_has_capability () constexpr
Definition at line 54 of file sycl_util.hpp.
bitcast()
template<typename ToEltTy , typename FromEltTy , int FromN, typename = csd::enable_if_t<is_vectorizable<ToEltTy>::value>> ESIMD_INLINE csd::conditional_t< std::is_same<FromEltTy, ToEltTy>::value, vector_type_t<FromEltTy, FromN>, vector_type_t<ToEltTy, bitcast_helper<ToEltTy, FromEltTy, FromN>::nToElems()> > cl::sycl::ext::intel::experimental::esimd::detail::bitcast (vector_type_t< FromEltTy, FromN > Val)
Definition at line 233 of file types.hpp.
convert()
template<typename To , typename From > To cl::sycl::ext::intel::experimental::esimd::detail::convert (From Val)
Definition at line 195 of file types.hpp.
ElemsPerAddrDecoding()
constexpr unsigned int cl::sycl::ext::intel::experimental::esimd::detail::ElemsPerAddrDecoding (unsigned int ElemsPerAddrEncoded) constexpr
Definition at line 63 of file memory_intrin.hpp.
Referenced by __esimd_flat_read(), and __esimd_flat_write().
ElemsPerAddrEncoding()
template<int ElemsPerAddr, typename = sycl::detail::enable_if_t< (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)>> constexpr unsigned int cl::sycl::ext::intel::experimental::esimd::detail::ElemsPerAddrEncoding () constexpr
Definition at line 51 of file memory_intrin.hpp.
getNextPowerOf2()
template<unsigned int N> constexpr unsigned int cl::sycl::ext::intel::experimental::esimd::detail::getNextPowerOf2 () constexpr
Definition at line 45 of file util.hpp.
References std::get().
getNextPowerOf2< 0 >()
template<> constexpr unsigned int cl::sycl::ext::intel::experimental::esimd::detail::getNextPowerOf2< 0 > () constexpr
Definition at line 49 of file util.hpp.
is_type() [1/2]
template<typename U > constexpr bool cl::sycl::ext::intel::experimental::esimd::detail::is_type () constexpr
Base case for checking if a type U is one of the types.
Definition at line 206 of file types.hpp.
is_type() [2/2]
template<typename U , typename T , typename... Ts> constexpr bool cl::sycl::ext::intel::experimental::esimd::detail::is_type () constexpr
Definition at line 208 of file types.hpp.
isPowerOf2() [1/2]
static constexpr ESIMD_INLINE bool cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2 (unsigned int n) static constexpr
Check if a given 32 bit positive integer is a power of 2 at compile time.
Definition at line 70 of file util.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::block_load(), cl::sycl::ext::intel::experimental::esimd::block_store(), check_atomic(), cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::copy_from(), cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::copy_to(), cl::sycl::ext::intel::experimental::esimd::slm_block_load(), and cl::sycl::ext::intel::experimental::esimd::slm_block_store().
isPowerOf2() [2/2]
static constexpr ESIMD_INLINE bool cl::sycl::ext::intel::experimental::esimd::detail::isPowerOf2 (unsigned int n, unsigned int limit) static constexpr
Definition at line 74 of file util.hpp.
log2()
template<unsigned int N> constexpr unsigned int cl::sycl::ext::intel::experimental::esimd::detail::log2 () constexpr
Definition at line 65 of file util.hpp.
References std::get().
operator<<()
std::ostream& cl::sycl::ext::intel::experimental::esimd::detail::operator<< (std::ostream & O, half const & rhs) inline
Definition at line 244 of file types.hpp.
operator>>()
std::istream& cl::sycl::ext::intel::experimental::esimd::detail::operator>> (std::istream & I, half & rhs) inline
Definition at line 249 of file types.hpp.
readRegion() [1/2]
template<typename BT , int BN, typename RTy > __SEIEED::vector_type_t<typename RTy::element_type, RTy::length> ESIMD_INLINE cl::sycl::ext::intel::experimental::esimd::detail::readRegion (const __SEIEED::vector_type_t< BT, BN > & Base, RTy Region)
read from a basic region of a vector, return a vector
Definition at line 148 of file intrin.hpp.
References __esimd_rdregion().
readRegion() [2/2]
template<typename BT , int BN, typename T , typename U > ESIMD_INLINE __SEIEED::vector_type_t<typename T::element_type, T::length> cl::sycl::ext::intel::experimental::esimd::detail::readRegion (const __SEIEED::vector_type_t< BT, BN > & Base, std::pair< T, U > Region)
read from a nested region of a vector, return a vector
Definition at line 170 of file intrin.hpp.
References cl::sycl::length(), and cl::sycl::ext::intel::experimental::esimd::R.
Variable Documentation
ch
template<rgba_channel Ch> constexpr uint8_t cl::sycl::ext::intel::experimental::esimd::detail::ch = 1 << static_cast<int>(Ch) inline static constexpr
Definition at line 94 of file common.hpp.
chA
constexpr uint8_t cl::sycl::ext::intel::experimental::esimd::detail::chA = ch<rgba_channel::A> inline static constexpr
Definition at line 98 of file common.hpp.
chB
constexpr uint8_t cl::sycl::ext::intel::experimental::esimd::detail::chB = ch<rgba_channel::B> inline static constexpr
Definition at line 97 of file common.hpp.
chG
constexpr uint8_t cl::sycl::ext::intel::experimental::esimd::detail::chG = ch<rgba_channel::G> inline static constexpr
Definition at line 96 of file common.hpp.
chR
constexpr uint8_t cl::sycl::ext::intel::experimental::esimd::detail::chR = ch<rgba_channel::R> inline static constexpr
Definition at line 95 of file common.hpp.