DPC++ Runtime: __host_std Namespace Reference
__host_std Namespace Reference
Namespaces
detail
Typedefs
using rel_res_t = d::ConvertToOpenCLType_t< bool >
Functions
__SYCL_MAKE_CALL_ARG2_SAME (Dot, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME_RESULT(FMul
__FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (FOrdEqual, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(FUnordNotEqual
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (FOrdGreaterThan, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(FOrdGreaterThanEqual
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (FOrdLessThan, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(FOrdLessThanEqual
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (FOrdNotEqual, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(LessOrGreater
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG1 (IsFinite, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG1(IsInf
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG1 (IsNan, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG1(IsNormal
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (Ordered, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(Unordered
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG1 (SignBitSet, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG1(Any
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG1 (All, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG3(select
s::cl_float sycl_host_fclamp (s::cl_float x, s::cl_float minval, s::cl_float maxval) __NOEXC
s::cl_double sycl_host_fclamp (s::cl_double x, s::cl_double minval, s::cl_double maxval) __NOEXC
s::cl_half sycl_host_fclamp (s::cl_half x, s::cl_half minval, s::cl_half maxval) __NOEXC
MAKE_1V_2V_3V (sycl_host_fclamp, s::cl_float, s::cl_float, s::cl_float, s::cl_float) MAKE_1V_2V_3V(sycl_host_fclamp
s::cl_double s::cl_float sycl_host_degrees (s::cl_float radians) __NOEXC
s::cl_double sycl_host_degrees (s::cl_double radians) __NOEXC
s::cl_half sycl_host_degrees (s::cl_half radians) __NOEXC
s::cl_float sycl_host_fmin_common (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double sycl_host_fmin_common (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half sycl_host_fmin_common (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float sycl_host_fmax_common (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double sycl_host_fmax_common (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half sycl_host_fmax_common (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float sycl_host_mix (s::cl_float x, s::cl_float y, s::cl_float a) __NOEXC
s::cl_double sycl_host_mix (s::cl_double x, s::cl_double y, s::cl_double a) __NOEXC
s::cl_half sycl_host_mix (s::cl_half x, s::cl_half y, s::cl_half a) __NOEXC
cl::cl_float sycl_host_Dot (s::vec< float, 1 >, s::vec< float, 1 >)
cl::cl_float sycl_host_Dot (s::vec< cl::cl_float, 2 >, s::vec< cl::cl_float, 2 >)
cl::cl_float sycl_host_Dot (s::vec< cl::cl_float, 3 >, s::vec< cl::cl_float, 3 >)
cl::cl_float sycl_host_Dot (s::vec< cl::cl_float, 4 >, s::vec< cl::cl_float, 4 >)
cl::cl_double sycl_host_Dot (s::vec< double, 1 >, s::vec< double, 1 >)
cl::cl_double sycl_host_Dot (s::vec< cl::cl_double, 2 >, s::vec< cl::cl_double, 2 >)
cl::cl_double sycl_host_Dot (s::vec< cl::cl_double, 3 >, s::vec< cl::cl_double, 3 >)
cl::cl_double sycl_host_Dot (s::vec< cl::cl_double, 4 >, s::vec< cl::cl_double, 4 >)
cl::cl_half sycl_host_Dot (s::vec< s::half, 1 >, s::vec< s::half, 1 >)
cl::cl_half sycl_host_Dot (s::vec< cl::cl_half, 2 >, s::vec< cl::cl_half, 2 >)
cl::cl_half sycl_host_Dot (s::vec< cl::cl_half, 3 >, s::vec< cl::cl_half, 3 >)
cl::cl_half sycl_host_Dot (s::vec< cl::cl_half, 4 >, s::vec< cl::cl_half, 4 >)
cl::cl_int sycl_host_All (s::vec< int, 1 >)
cl::cl_int sycl_host_All (s::vec< cl::cl_int, 2 >)
cl::cl_int sycl_host_All (s::vec< cl::cl_int, 3 >)
cl::cl_int sycl_host_All (s::vec< cl::cl_int, 4 >)
s::vec< cl::cl_float, 3 > sycl_host_cross (s::vec< cl::cl_float, 3 > p0, s::vec< cl::cl_float, 3 > p1) __NOEXC
s::vec< cl::cl_float, 4 > sycl_host_cross (s::vec< cl::cl_float, 4 > p0, s::vec< cl::cl_float, 4 > p1) __NOEXC
s::vec< cl::cl_double, 3 > sycl_host_cross (s::vec< cl::cl_double, 3 > p0, s::vec< cl::cl_double, 3 > p1) __NOEXC
s::vec< cl::cl_double, 4 > sycl_host_cross (s::vec< cl::cl_double, 4 > p0, s::vec< cl::cl_double, 4 > p1) __NOEXC
s::vec< cl::cl_half, 3 > sycl_host_cross (s::vec< cl::cl_half, 3 > p0, s::vec< cl::cl_half, 3 > p1) __NOEXC
s::vec< cl::cl_half, 4 > sycl_host_cross (s::vec< cl::cl_half, 4 > p0, s::vec< cl::cl_half, 4 > p1) __NOEXC
cl::cl_float sycl_host_FMul (cl::cl_float p0, cl::cl_float p1)
cl::cl_double sycl_host_FMul (cl::cl_double p0, cl::cl_double p1)
cl::cl_float sycl_host_FMul (cl::cl_half p0, cl::cl_half p1)
MAKE_GEO_1V_2V_RS (sycl_host_Dot, __FMul_impl, s::cl_float, s::cl_float, s::cl_float) MAKE_GEO_1V_2V_RS(sycl_host_Dot
s::cl_double MAKE_GEO_1V_2V_RS (sycl_host_Dot, __FMul_impl, s::cl_half, s::cl_half, s::cl_half) 1 cl
cl::cl_double sycl_host_length (cl::cl_double p)
cl::cl_half sycl_host_length (cl::cl_half p)
cl::cl_float sycl_host_length (s::vec< float, 1 > p)
cl::cl_float sycl_host_length (s::vec< cl::cl_float, 2 > p)
cl::cl_float sycl_host_length (s::vec< cl::cl_float, 3 > p)
cl::cl_float sycl_host_length (s::vec< cl::cl_float, 4 > p)
cl::cl_double sycl_host_length (s::vec< double, 1 > p)
cl::cl_double sycl_host_length (s::vec< cl::cl_double, 2 > p)
cl::cl_double sycl_host_length (s::vec< cl::cl_double, 3 > p)
cl::cl_double sycl_host_length (s::vec< cl::cl_double, 4 > p)
cl::cl_half sycl_host_length (s::vec< s::half, 1 > p)
cl::cl_half sycl_host_length (s::vec< cl::cl_half, 2 > p)
cl::cl_half sycl_host_length (s::vec< cl::cl_half, 3 > p)
cl::cl_half sycl_host_length (s::vec< cl::cl_half, 4 > p)
cl::cl_float sycl_host_distance (cl::cl_float p0, cl::cl_float p1)
cl::cl_float sycl_host_distance (s::vec< float, 1 > p0, s::vec< float, 1 > p1)
cl::cl_float sycl_host_distance (s::vec< cl::cl_float, 2 > p0, s::vec< cl::cl_float, 2 > p1)
cl::cl_float sycl_host_distance (s::vec< cl::cl_float, 3 > p0, s::vec< cl::cl_float, 3 > p1)
cl::cl_float sycl_host_distance (s::vec< cl::cl_float, 4 > p0, s::vec< cl::cl_float, 4 > p1)
cl::cl_double sycl_host_distance (cl::cl_double p0, cl::cl_double p1)
cl::cl_float sycl_host_distance (s::vec< double, 1 > p0, s::vec< double, 1 > p1)
cl::cl_double sycl_host_distance (s::vec< cl::cl_double, 2 > p0, s::vec< cl::cl_double, 2 > p1)
cl::cl_double sycl_host_distance (s::vec< cl::cl_double, 3 > p0, s::vec< cl::cl_double, 3 > p1)
cl::cl_double sycl_host_distance (s::vec< cl::cl_double, 4 > p0, s::vec< cl::cl_double, 4 > p1)
cl::cl_half sycl_host_distance (cl::cl_half p0, cl::cl_half p1)
cl::cl_float sycl_host_distance (s::vec< s::half, 1 > p0, s::vec< s::half, 1 > p1)
cl::cl_half sycl_host_distance (s::vec< cl::cl_half, 2 > p0, s::vec< cl::cl_half, 2 > p1)
cl::cl_half sycl_host_distance (s::vec< cl::cl_half, 3 > p0, s::vec< cl::cl_half, 3 > p1)
cl::cl_half sycl_host_distance (s::vec< cl::cl_half, 4 > p0, s::vec< cl::cl_half, 4 > p1)
cl::cl_float sycl_host_normalize (cl::cl_float p)
cl::cl_float sycl_host_normalize (s::vec< float, 1 > p)
s::vec< cl::cl_float, 2 > sycl_host_normalize (s::vec< cl::cl_float, 2 > p)
s::vec< cl::cl_float, 3 > sycl_host_normalize (s::vec< cl::cl_float, 3 > p)
s::vec< cl::cl_float, 4 > sycl_host_normalize (s::vec< cl::cl_float, 4 > p)
cl::cl_double sycl_host_normalize (cl::cl_double p)
cl::cl_double sycl_host_normalize (s::vec< double, 1 > p)
s::vec< cl::cl_double, 2 > sycl_host_normalize (s::vec< cl::cl_double, 2 > p)
s::vec< cl::cl_double, 3 > sycl_host_normalize (s::vec< cl::cl_double, 3 > p)
s::vec< cl::cl_double, 4 > sycl_host_normalize (s::vec< cl::cl_double, 4 > p)
cl::cl_half sycl_host_normalize (cl::cl_half p)
s::vec< cl::cl_half, 2 > sycl_host_normalize (s::vec< cl::cl_half, 2 > p)
s::vec< cl::cl_half, 3 > sycl_host_normalize (s::vec< cl::cl_half, 3 > p)
s::vec< cl::cl_half, 4 > sycl_host_normalize (s::vec< cl::cl_half, 4 > p)
cl::cl_float sycl_host_fast_length (cl::cl_float p)
cl::cl_float sycl_host_fast_length (s::vec< float, 1 > p)
cl::cl_float sycl_host_fast_length (s::vec< cl::cl_float, 2 > p)
cl::cl_float sycl_host_fast_length (s::vec< cl::cl_float, 3 > p)
cl::cl_float sycl_host_fast_length (s::vec< cl::cl_float, 4 > p)
cl::cl_float sycl_host_fast_normalize (cl::cl_float p)
cl::cl_float sycl_host_fast_normalize (s::vec< float, 1 > p)
s::vec< cl::cl_float, 2 > sycl_host_fast_normalize (s::vec< cl::cl_float, 2 > p)
s::vec< cl::cl_float, 3 > sycl_host_fast_normalize (s::vec< cl::cl_float, 3 > p)
s::vec< cl::cl_float, 4 > sycl_host_fast_normalize (s::vec< cl::cl_float, 4 > p)
cl::cl_float sycl_host_fast_distance (cl::cl_float p0, cl::cl_float p1)
cl::cl_float sycl_host_fast_distance (s::vec< float, 1 > p0, s::vec< float, 1 > p1)
cl::cl_float sycl_host_fast_distance (s::vec< cl::cl_float, 2 > p0, s::vec< cl::cl_float, 2 > p1)
cl::cl_float sycl_host_fast_distance (s::vec< cl::cl_float, 3 > p0, s::vec< cl::cl_float, 3 > p1)
cl::cl_float sycl_host_fast_distance (s::vec< cl::cl_float, 4 > p0, s::vec< cl::cl_float, 4 > p1)
s::cl_uchar sycl_host_u_abs (s::cl_uchar x) __NOEXC
s::cl_ushort sycl_host_u_abs (s::cl_ushort x) __NOEXC
s::cl_uint sycl_host_u_abs (s::cl_uint x) __NOEXC
s::cl_ulong sycl_host_u_abs (s::cl_ulong x) __NOEXC
s::cl_uchar sycl_host_s_abs (s::cl_char x) __NOEXC
s::cl_ushort sycl_host_s_abs (s::cl_short x) __NOEXC
s::cl_uint sycl_host_s_abs (s::cl_int x) __NOEXC
s::cl_ulong sycl_host_s_abs (s::cl_long x) __NOEXC
s::cl_uchar sycl_host_u_abs_diff (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort sycl_host_u_abs_diff (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint sycl_host_u_abs_diff (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong sycl_host_u_abs_diff (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_uchar sycl_host_s_abs_diff (s::cl_char x, s::cl_char y) __NOEXC
s::cl_ushort sycl_host_s_abs_diff (s::cl_short x, s::cl_short y) __NOEXC
s::cl_uint sycl_host_s_abs_diff (s::cl_int x, s::cl_int y) __NOEXC
s::cl_ulong sycl_host_s_abs_diff (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar sycl_host_u_add_sat (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort sycl_host_u_add_sat (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint sycl_host_u_add_sat (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong sycl_host_u_add_sat (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char sycl_host_s_add_sat (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short sycl_host_s_add_sat (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int sycl_host_s_add_sat (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long sycl_host_s_add_sat (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar sycl_host_u_hadd (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort sycl_host_u_hadd (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint sycl_host_u_hadd (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong sycl_host_u_hadd (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char sycl_host_s_hadd (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short sycl_host_s_hadd (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int sycl_host_s_hadd (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long sycl_host_s_hadd (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar sycl_host_u_rhadd (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort sycl_host_u_rhadd (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint sycl_host_u_rhadd (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong sycl_host_u_rhadd (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char sycl_host_s_rhadd (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short sycl_host_s_rhadd (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int sycl_host_s_rhadd (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long sycl_host_s_rhadd (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar sycl_host_u_clamp (s::cl_uchar x, s::cl_uchar minval, s::cl_uchar maxval) __NOEXC
s::cl_ushort sycl_host_u_clamp (s::cl_ushort x, s::cl_ushort minval, s::cl_ushort maxval) __NOEXC
s::cl_uint sycl_host_u_clamp (s::cl_uint x, s::cl_uint minval, s::cl_uint maxval) __NOEXC
s::cl_ulong sycl_host_u_clamp (s::cl_ulong x, s::cl_ulong minval, s::cl_ulong maxval) __NOEXC
MAKE_1V_2V_3V (sycl_host_u_clamp, s::cl_uchar, s::cl_uchar, s::cl_uchar, s::cl_uchar) MAKE_1V_2V_3V(sycl_host_u_clamp
s::cl_ushort MAKE_1V_2V_3V (sycl_host_u_clamp, s::cl_ulong, s::cl_ulong, s::cl_ulong, s::cl_ulong) MAKE_1V_2S_3S(sycl_host_u_clamp
s::cl_ushort s::cl_uchar MAKE_1V_2S_3S (sycl_host_u_clamp, s::cl_ushort, s::cl_ushort, s::cl_ushort, s::cl_ushort) MAKE_1V_2S_3S(sycl_host_u_clamp
s::cl_ushort s::cl_uchar s::cl_ulong s::cl_char sycl_host_s_clamp (s::cl_char x, s::cl_char minval, s::cl_char maxval) __NOEXC
s::cl_short sycl_host_s_clamp (s::cl_short x, s::cl_short minval, s::cl_short maxval) __NOEXC
s::cl_int sycl_host_s_clamp (s::cl_int x, s::cl_int minval, s::cl_int maxval) __NOEXC
s::cl_long sycl_host_s_clamp (s::cl_long x, s::cl_long minval, s::cl_long maxval) __NOEXC
MAKE_1V_2V_3V (sycl_host_s_clamp, s::cl_short, s::cl_short, s::cl_short, s::cl_short) MAKE_1V_2S_3S(sycl_host_s_clamp
s::cl_short s::cl_uchar sycl_host_clz (s::cl_uchar x) __NOEXC
s::cl_char sycl_host_clz (s::cl_char x) __NOEXC
s::cl_ushort sycl_host_clz (s::cl_ushort x) __NOEXC
s::cl_short sycl_host_clz (s::cl_short x) __NOEXC
s::cl_uint sycl_host_clz (s::cl_uint x) __NOEXC
s::cl_int sycl_host_clz (s::cl_int x) __NOEXC
s::cl_ulong sycl_host_clz (s::cl_ulong x) __NOEXC
s::cl_long sycl_host_clz (s::cl_long x) __NOEXC
s::cl_uchar sycl_host_ctz (s::cl_uchar x) __NOEXC
s::cl_char sycl_host_ctz (s::cl_char x) __NOEXC
s::cl_ushort sycl_host_ctz (s::cl_ushort x) __NOEXC
s::cl_short sycl_host_ctz (s::cl_short x) __NOEXC
s::cl_uint sycl_host_ctz (s::cl_uint x) __NOEXC
s::cl_int sycl_host_ctz (s::cl_int x) __NOEXC
s::cl_ulong sycl_host_ctz (s::cl_ulong x) __NOEXC
s::cl_long sycl_host_ctz (s::cl_long x) __NOEXC
s::cl_char sycl_host_s_mul_hi (s::cl_char a, s::cl_char b)
s::cl_short sycl_host_s_mul_hi (s::cl_short a, s::cl_short b)
s::cl_int sycl_host_s_mul_hi (s::cl_int a, s::cl_int b)
s::cl_long sycl_host_s_mul_hi (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar sycl_host_u_mul_hi (s::cl_uchar a, s::cl_uchar b)
s::cl_ushort sycl_host_u_mul_hi (s::cl_ushort a, s::cl_ushort b)
s::cl_uint sycl_host_u_mul_hi (s::cl_uint a, s::cl_uint b)
s::cl_ulong sycl_host_u_mul_hi (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char sycl_host_s_mad_hi (s::cl_char x, s::cl_char minval, s::cl_char maxval) __NOEXC
s::cl_short sycl_host_s_mad_hi (s::cl_short x, s::cl_short minval, s::cl_short maxval) __NOEXC
s::cl_int sycl_host_s_mad_hi (s::cl_int x, s::cl_int minval, s::cl_int maxval) __NOEXC
s::cl_long sycl_host_s_mad_hi (s::cl_long x, s::cl_long minval, s::cl_long maxval) __NOEXC
MAKE_1V_2V_3V (sycl_host_s_mad_hi, s::cl_char, s::cl_char, s::cl_char, s::cl_char) MAKE_1V_2V_3V(sycl_host_s_mad_hi
s::cl_float sycl_host_acos (s::cl_float x) __NOEXC
s::cl_double sycl_host_acos (s::cl_double x) __NOEXC
s::cl_half sycl_host_acos (s::cl_half x) __NOEXC
s::cl_float sycl_host_acosh (s::cl_float x) __NOEXC
s::cl_double sycl_host_acosh (s::cl_double x) __NOEXC
s::cl_half sycl_host_acosh (s::cl_half x) __NOEXC
s::cl_float sycl_host_acospi (s::cl_float x) __NOEXC
s::cl_double sycl_host_acospi (s::cl_double x) __NOEXC
s::cl_half sycl_host_acospi (s::cl_half x) __NOEXC
s::cl_float sycl_host_asin (s::cl_float x) __NOEXC
s::cl_double sycl_host_asin (s::cl_double x) __NOEXC
s::cl_half sycl_host_asin (s::cl_half x) __NOEXC
s::cl_float sycl_host_asinh (s::cl_float x) __NOEXC
s::cl_double sycl_host_asinh (s::cl_double x) __NOEXC
s::cl_half sycl_host_asinh (s::cl_half x) __NOEXC
s::cl_float sycl_host_asinpi (s::cl_float x) __NOEXC
s::cl_double sycl_host_asinpi (s::cl_double x) __NOEXC
s::cl_half sycl_host_asinpi (s::cl_half x) __NOEXC
s::cl_float sycl_host_atan (s::cl_float x) __NOEXC
s::cl_double sycl_host_atan (s::cl_double x) __NOEXC
s::cl_half sycl_host_atan (s::cl_half x) __NOEXC
s::cl_float sycl_host_atan2 (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double sycl_host_atan2 (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half sycl_host_atan2 (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float sycl_host_atanh (s::cl_float x) __NOEXC
s::cl_double sycl_host_atanh (s::cl_double x) __NOEXC
s::cl_half sycl_host_atanh (s::cl_half x) __NOEXC
s::cl_float sycl_host_atanpi (s::cl_float x) __NOEXC
s::cl_double sycl_host_atanpi (s::cl_double x) __NOEXC
s::cl_half sycl_host_atanpi (s::cl_half x) __NOEXC
s::cl_float sycl_host_atan2pi (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double sycl_host_atan2pi (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half sycl_host_atan2pi (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float sycl_host_cbrt (s::cl_float x) __NOEXC
s::cl_double sycl_host_cbrt (s::cl_double x) __NOEXC
s::cl_half sycl_host_cbrt (s::cl_half x) __NOEXC
s::cl_float sycl_host_ceil (s::cl_float x) __NOEXC
s::cl_double sycl_host_ceil (s::cl_double x) __NOEXC
s::cl_half sycl_host_ceil (s::cl_half x) __NOEXC
s::cl_float sycl_host_copysign (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double sycl_host_copysign (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half sycl_host_copysign (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float sycl_host_cos (s::cl_float x) __NOEXC
s::cl_double sycl_host_cos (s::cl_double x) __NOEXC
s::cl_half sycl_host_cos (s::cl_half x) __NOEXC
s::cl_float sycl_host_cosh (s::cl_float x) __NOEXC
s::cl_double sycl_host_cosh (s::cl_double x) __NOEXC
s::cl_half sycl_host_cosh (s::cl_half x) __NOEXC
s::cl_float sycl_host_cospi (s::cl_float x) __NOEXC
s::cl_double sycl_host_cospi (s::cl_double x) __NOEXC
s::cl_half sycl_host_cospi (s::cl_half x) __NOEXC
s::cl_float sycl_host_erfc (s::cl_float x) __NOEXC
s::cl_double sycl_host_erfc (s::cl_double x) __NOEXC
s::cl_half sycl_host_erfc (s::cl_half x) __NOEXC
s::cl_float sycl_host_erf (s::cl_float x) __NOEXC
s::cl_double sycl_host_erf (s::cl_double x) __NOEXC
s::cl_half sycl_host_erf (s::cl_half x) __NOEXC
s::cl_float sycl_host_exp (s::cl_float x) __NOEXC
s::cl_double sycl_host_exp (s::cl_double x) __NOEXC
s::cl_half sycl_host_exp (s::cl_half x) __NOEXC
s::cl_float sycl_host_exp2 (s::cl_float x) __NOEXC
s::cl_double sycl_host_exp2 (s::cl_double x) __NOEXC
s::cl_half sycl_host_exp2 (s::cl_half x) __NOEXC
s::cl_float sycl_host_exp10 (s::cl_float x) __NOEXC
s::cl_double sycl_host_exp10 (s::cl_double x) __NOEXC
s::cl_half sycl_host_exp10 (s::cl_half x) __NOEXC
s::cl_float sycl_host_expm1 (s::cl_float x) __NOEXC
s::cl_double sycl_host_expm1 (s::cl_double x) __NOEXC
s::cl_half sycl_host_expm1 (s::cl_half x) __NOEXC
s::cl_float sycl_host_fabs (s::cl_float x) __NOEXC
s::cl_double sycl_host_fabs (s::cl_double x) __NOEXC
s::cl_half sycl_host_fabs (s::cl_half x) __NOEXC
s::cl_float sycl_host_fdim (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double sycl_host_fdim (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half sycl_host_fdim (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float sycl_host_floor (s::cl_float x) __NOEXC
s::cl_double sycl_host_floor (s::cl_double x) __NOEXC
s::cl_half sycl_host_floor (s::cl_half x) __NOEXC
s::cl_float sycl_host_fma (s::cl_float a, s::cl_float b, s::cl_float c) __NOEXC
s::cl_double sycl_host_fma (s::cl_double a, s::cl_double b, s::cl_double c) __NOEXC
s::cl_half sycl_host_fma (s::cl_half a, s::cl_half b, s::cl_half c) __NOEXC
rel_res_t sycl_host_FOrdEqual (s::cl_float x, s::cl_float y) __NOEXC
rel_res_t sycl_host_FOrdEqual (s::cl_double x, s::cl_double y) __NOEXC
rel_res_t sycl_host_FOrdEqual (s::cl_half x, s::cl_half y) __NOEXC
MAKE_1V_2V_FUNC (sycl_host_FOrdEqual, __vFOrdEqual, s::cl_int, s::cl_float, s::cl_float) MAKE_1V_2V_FUNC(sycl_host_FOrdEqual
Variables
__FMul_impl
__vFOrdEqual
Typedef Documentation
rel_res_t
using __host_std::rel_res_t = typedef d::ConvertToOpenCLType_t<bool>
Definition at line 150 of file builtins_relational.cpp.
Function Documentation
__SYCL_MAKE_CALL_ARG1() [1/4]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG1 (All , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG1() [2/4]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG1 (IsFinite , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG1() [3/4]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG1 (IsNan , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG1() [4/4]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG1 (SignBitSet , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [1/6]
__host_std::__SYCL_MAKE_CALL_ARG2_SAME (Dot , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [2/6]
__FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG2_SAME (FOrdEqual , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [3/6]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG2_SAME (FOrdGreaterThan , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [4/6]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG2_SAME (FOrdLessThan , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [5/6]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG2_SAME (FOrdNotEqual , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [6/6]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __host_std::__SYCL_MAKE_CALL_ARG2_SAME (Ordered , __FUNC_PREFIX_CORE)
MAKE_1V_2S_3S()
s::cl_ushort s::cl_uchar __host_std::MAKE_1V_2S_3S (sycl_host_u_clamp , s::cl_ushort , s::cl_ushort , s::cl_ushort , s::cl_ushort)
MAKE_1V_2V_3V() [1/5]
__host_std::MAKE_1V_2V_3V (sycl_host_fclamp , s::cl_float , s::cl_float , s::cl_float , s::cl_float)
MAKE_1V_2V_3V() [2/5]
__host_std::MAKE_1V_2V_3V (sycl_host_s_clamp , s::cl_short , s::cl_short , s::cl_short , s::cl_short)
MAKE_1V_2V_3V() [3/5]
__host_std::MAKE_1V_2V_3V (sycl_host_s_mad_hi , s::cl_char , s::cl_char , s::cl_char , s::cl_char)
MAKE_1V_2V_3V() [4/5]
__host_std::MAKE_1V_2V_3V (sycl_host_u_clamp , s::cl_uchar , s::cl_uchar , s::cl_uchar , s::cl_uchar)
MAKE_1V_2V_3V() [5/5]
s::cl_ushort __host_std::MAKE_1V_2V_3V (sycl_host_u_clamp , s::cl_ulong , s::cl_ulong , s::cl_ulong , s::cl_ulong)
MAKE_1V_2V_FUNC()
__host_std::MAKE_1V_2V_FUNC (sycl_host_FOrdEqual , __vFOrdEqual , s::cl_int , s::cl_float , s::cl_float)
MAKE_GEO_1V_2V_RS() [1/2]
__host_std::MAKE_GEO_1V_2V_RS (sycl_host_Dot , __FMul_impl , s::cl_float , s::cl_float , s::cl_float)
MAKE_GEO_1V_2V_RS() [2/2]
s::cl_double __host_std::MAKE_GEO_1V_2V_RS (sycl_host_Dot , __FMul_impl , s::cl_half , s::cl_half , s::cl_half)
Definition at line 161 of file builtins_geometric.cpp.
sycl_host_acos() [1/3]
s::cl_double __host_std::sycl_host_acos (s::cl_double x)
Definition at line 104 of file builtins_math.cpp.
sycl_host_acos() [2/3]
s::cl_float __host_std::sycl_host_acos (s::cl_float x)
Definition at line 101 of file builtins_math.cpp.
sycl_host_acos() [3/3]
s::cl_half __host_std::sycl_host_acos (s::cl_half x)
Definition at line 107 of file builtins_math.cpp.
sycl_host_acosh() [1/3]
s::cl_double __host_std::sycl_host_acosh (s::cl_double x)
Definition at line 118 of file builtins_math.cpp.
sycl_host_acosh() [2/3]
s::cl_float __host_std::sycl_host_acosh (s::cl_float x)
Definition at line 115 of file builtins_math.cpp.
sycl_host_acosh() [3/3]
s::cl_half __host_std::sycl_host_acosh (s::cl_half x)
Definition at line 121 of file builtins_math.cpp.
sycl_host_acospi() [1/3]
s::cl_double __host_std::sycl_host_acospi (s::cl_double x)
Definition at line 132 of file builtins_math.cpp.
sycl_host_acospi() [2/3]
s::cl_float __host_std::sycl_host_acospi (s::cl_float x)
Definition at line 129 of file builtins_math.cpp.
sycl_host_acospi() [3/3]
s::cl_half __host_std::sycl_host_acospi (s::cl_half x)
Definition at line 135 of file builtins_math.cpp.
sycl_host_All() [1/4]
cl::cl_int __host_std::sycl_host_All (s::vec< cl::cl_int, 2 >)
sycl_host_All() [2/4]
cl::cl_int __host_std::sycl_host_All (s::vec< cl::cl_int, 3 >)
sycl_host_All() [3/4]
cl::cl_int __host_std::sycl_host_All (s::vec< cl::cl_int, 4 >)
sycl_host_All() [4/4]
cl::cl_int __host_std::sycl_host_All (s::vec< int, 1 >)
sycl_host_asin() [1/3]
s::cl_double __host_std::sycl_host_asin (s::cl_double x)
Definition at line 146 of file builtins_math.cpp.
sycl_host_asin() [2/3]
s::cl_float __host_std::sycl_host_asin (s::cl_float x)
Definition at line 143 of file builtins_math.cpp.
sycl_host_asin() [3/3]
s::cl_half __host_std::sycl_host_asin (s::cl_half x)
Definition at line 149 of file builtins_math.cpp.
sycl_host_asinh() [1/3]
s::cl_double __host_std::sycl_host_asinh (s::cl_double x)
Definition at line 160 of file builtins_math.cpp.
sycl_host_asinh() [2/3]
s::cl_float __host_std::sycl_host_asinh (s::cl_float x)
Definition at line 157 of file builtins_math.cpp.
sycl_host_asinh() [3/3]
s::cl_half __host_std::sycl_host_asinh (s::cl_half x)
Definition at line 163 of file builtins_math.cpp.
sycl_host_asinpi() [1/3]
s::cl_double __host_std::sycl_host_asinpi (s::cl_double x)
Definition at line 174 of file builtins_math.cpp.
sycl_host_asinpi() [2/3]
s::cl_float __host_std::sycl_host_asinpi (s::cl_float x)
Definition at line 171 of file builtins_math.cpp.
sycl_host_asinpi() [3/3]
s::cl_half __host_std::sycl_host_asinpi (s::cl_half x)
Definition at line 177 of file builtins_math.cpp.
sycl_host_atan() [1/3]
s::cl_double __host_std::sycl_host_atan (s::cl_double x)
Definition at line 188 of file builtins_math.cpp.
sycl_host_atan() [2/3]
s::cl_float __host_std::sycl_host_atan (s::cl_float x)
Definition at line 185 of file builtins_math.cpp.
sycl_host_atan() [3/3]
s::cl_half __host_std::sycl_host_atan (s::cl_half x)
Definition at line 191 of file builtins_math.cpp.
sycl_host_atan2() [1/3]
s::cl_double __host_std::sycl_host_atan2 (s::cl_double x, s::cl_double y)
Definition at line 203 of file builtins_math.cpp.
sycl_host_atan2() [2/3]
s::cl_float __host_std::sycl_host_atan2 (s::cl_float x, s::cl_float y)
Definition at line 199 of file builtins_math.cpp.
sycl_host_atan2() [3/3]
s::cl_half __host_std::sycl_host_atan2 (s::cl_half x, s::cl_half y)
Definition at line 207 of file builtins_math.cpp.
sycl_host_atan2pi() [1/3]
s::cl_double __host_std::sycl_host_atan2pi (s::cl_double x, s::cl_double y)
Definition at line 247 of file builtins_math.cpp.
sycl_host_atan2pi() [2/3]
s::cl_float __host_std::sycl_host_atan2pi (s::cl_float x, s::cl_float y)
Definition at line 243 of file builtins_math.cpp.
sycl_host_atan2pi() [3/3]
s::cl_half __host_std::sycl_host_atan2pi (s::cl_half x, s::cl_half y)
Definition at line 251 of file builtins_math.cpp.
sycl_host_atanh() [1/3]
s::cl_double __host_std::sycl_host_atanh (s::cl_double x)
Definition at line 218 of file builtins_math.cpp.
sycl_host_atanh() [2/3]
s::cl_float __host_std::sycl_host_atanh (s::cl_float x)
Definition at line 215 of file builtins_math.cpp.
sycl_host_atanh() [3/3]
s::cl_half __host_std::sycl_host_atanh (s::cl_half x)
Definition at line 221 of file builtins_math.cpp.
sycl_host_atanpi() [1/3]
s::cl_double __host_std::sycl_host_atanpi (s::cl_double x)
Definition at line 232 of file builtins_math.cpp.
sycl_host_atanpi() [2/3]
s::cl_float __host_std::sycl_host_atanpi (s::cl_float x)
Definition at line 229 of file builtins_math.cpp.
sycl_host_atanpi() [3/3]
s::cl_half __host_std::sycl_host_atanpi (s::cl_half x)
Definition at line 235 of file builtins_math.cpp.
sycl_host_cbrt() [1/3]
s::cl_double __host_std::sycl_host_cbrt (s::cl_double x)
Definition at line 262 of file builtins_math.cpp.
sycl_host_cbrt() [2/3]
s::cl_float __host_std::sycl_host_cbrt (s::cl_float x)
Definition at line 259 of file builtins_math.cpp.
sycl_host_cbrt() [3/3]
s::cl_half __host_std::sycl_host_cbrt (s::cl_half x)
Definition at line 265 of file builtins_math.cpp.
sycl_host_ceil() [1/3]
s::cl_double __host_std::sycl_host_ceil (s::cl_double x)
Definition at line 276 of file builtins_math.cpp.
sycl_host_ceil() [2/3]
s::cl_float __host_std::sycl_host_ceil (s::cl_float x)
Definition at line 273 of file builtins_math.cpp.
sycl_host_ceil() [3/3]
s::cl_half __host_std::sycl_host_ceil (s::cl_half x)
Definition at line 279 of file builtins_math.cpp.
sycl_host_clz() [1/8]
s::cl_char __host_std::sycl_host_clz (s::cl_char x)
Definition at line 510 of file builtins_integer.cpp.
sycl_host_clz() [2/8]
s::cl_int __host_std::sycl_host_clz (s::cl_int x)
Definition at line 522 of file builtins_integer.cpp.
sycl_host_clz() [3/8]
s::cl_long __host_std::sycl_host_clz (s::cl_long x)
Definition at line 526 of file builtins_integer.cpp.
sycl_host_clz() [4/8]
s::cl_short __host_std::sycl_host_clz (s::cl_short x)
Definition at line 516 of file builtins_integer.cpp.
sycl_host_clz() [5/8]
s::cl_short s::cl_uchar __host_std::sycl_host_clz (s::cl_uchar x)
Definition at line 507 of file builtins_integer.cpp.
sycl_host_clz() [6/8]
s::cl_uint __host_std::sycl_host_clz (s::cl_uint x)
Definition at line 519 of file builtins_integer.cpp.
sycl_host_clz() [7/8]
s::cl_ulong __host_std::sycl_host_clz (s::cl_ulong x)
Definition at line 523 of file builtins_integer.cpp.
sycl_host_clz() [8/8]
s::cl_ushort __host_std::sycl_host_clz (s::cl_ushort x)
Definition at line 513 of file builtins_integer.cpp.
sycl_host_copysign() [1/3]
s::cl_double __host_std::sycl_host_copysign (s::cl_double x, s::cl_double y)
Definition at line 291 of file builtins_math.cpp.
sycl_host_copysign() [2/3]
s::cl_float __host_std::sycl_host_copysign (s::cl_float x, s::cl_float y)
Definition at line 287 of file builtins_math.cpp.
sycl_host_copysign() [3/3]
s::cl_half __host_std::sycl_host_copysign (s::cl_half x, s::cl_half y)
Definition at line 295 of file builtins_math.cpp.
sycl_host_cos() [1/3]
s::cl_double __host_std::sycl_host_cos (s::cl_double x)
Definition at line 307 of file builtins_math.cpp.
sycl_host_cos() [2/3]
s::cl_float __host_std::sycl_host_cos (s::cl_float x)
Definition at line 304 of file builtins_math.cpp.
sycl_host_cos() [3/3]
s::cl_half __host_std::sycl_host_cos (s::cl_half x)
Definition at line 310 of file builtins_math.cpp.
sycl_host_cosh() [1/3]
s::cl_double __host_std::sycl_host_cosh (s::cl_double x)
Definition at line 321 of file builtins_math.cpp.
sycl_host_cosh() [2/3]
s::cl_float __host_std::sycl_host_cosh (s::cl_float x)
Definition at line 318 of file builtins_math.cpp.
sycl_host_cosh() [3/3]
s::cl_half __host_std::sycl_host_cosh (s::cl_half x)
Definition at line 324 of file builtins_math.cpp.
sycl_host_cospi() [1/3]
s::cl_double __host_std::sycl_host_cospi (s::cl_double x)
Definition at line 335 of file builtins_math.cpp.
sycl_host_cospi() [2/3]
s::cl_float __host_std::sycl_host_cospi (s::cl_float x)
Definition at line 332 of file builtins_math.cpp.
sycl_host_cospi() [3/3]
s::cl_half __host_std::sycl_host_cospi (s::cl_half x)
Definition at line 338 of file builtins_math.cpp.
sycl_host_cross() [1/6]
s::vec<cl::cl_double, 3> __host_std::sycl_host_cross (s::vec< cl::cl_double, 3 > p0, s::vec< cl::cl_double, 3 > p1)
Definition at line 127 of file builtins_geometric.cpp.
sycl_host_cross() [2/6]
s::vec<cl::cl_double, 4> __host_std::sycl_host_cross (s::vec< cl::cl_double, 4 > p0, s::vec< cl::cl_double, 4 > p1)
Definition at line 132 of file builtins_geometric.cpp.
sycl_host_cross() [3/6]
s::vec<cl::cl_float, 3> __host_std::sycl_host_cross (s::vec< cl::cl_float, 3 > p0, s::vec< cl::cl_float, 3 > p1)
Definition at line 117 of file builtins_geometric.cpp.
sycl_host_cross() [4/6]
s::vec<cl::cl_float, 4> __host_std::sycl_host_cross (s::vec< cl::cl_float, 4 > p0, s::vec< cl::cl_float, 4 > p1)
Definition at line 122 of file builtins_geometric.cpp.
sycl_host_cross() [5/6]
s::vec<cl::cl_half, 3> __host_std::sycl_host_cross (s::vec< cl::cl_half, 3 > p0, s::vec< cl::cl_half, 3 > p1)
Definition at line 137 of file builtins_geometric.cpp.
sycl_host_cross() [6/6]
s::vec<cl::cl_half, 4> __host_std::sycl_host_cross (s::vec< cl::cl_half, 4 > p0, s::vec< cl::cl_half, 4 > p1)
Definition at line 141 of file builtins_geometric.cpp.
sycl_host_ctz() [1/8]
s::cl_char __host_std::sycl_host_ctz (s::cl_char x)
Definition at line 542 of file builtins_integer.cpp.
sycl_host_ctz() [2/8]
s::cl_int __host_std::sycl_host_ctz (s::cl_int x)
Definition at line 554 of file builtins_integer.cpp.
sycl_host_ctz() [3/8]
s::cl_long __host_std::sycl_host_ctz (s::cl_long x)
Definition at line 558 of file builtins_integer.cpp.
sycl_host_ctz() [4/8]
s::cl_short __host_std::sycl_host_ctz (s::cl_short x)
Definition at line 548 of file builtins_integer.cpp.
sycl_host_ctz() [5/8]
s::cl_uchar __host_std::sycl_host_ctz (s::cl_uchar x)
Definition at line 539 of file builtins_integer.cpp.
sycl_host_ctz() [6/8]
s::cl_uint __host_std::sycl_host_ctz (s::cl_uint x)
Definition at line 551 of file builtins_integer.cpp.
sycl_host_ctz() [7/8]
s::cl_ulong __host_std::sycl_host_ctz (s::cl_ulong x)
Definition at line 555 of file builtins_integer.cpp.
sycl_host_ctz() [8/8]
s::cl_ushort __host_std::sycl_host_ctz (s::cl_ushort x)
Definition at line 545 of file builtins_integer.cpp.
sycl_host_degrees() [1/3]
s::cl_double __host_std::sycl_host_degrees (s::cl_double radians)
Definition at line 90 of file builtins_common.cpp.
sycl_host_degrees() [2/3]
s::cl_double s::cl_float __host_std::sycl_host_degrees (s::cl_float radians)
Definition at line 87 of file builtins_common.cpp.
sycl_host_degrees() [3/3]
s::cl_half __host_std::sycl_host_degrees (s::cl_half radians)
Definition at line 93 of file builtins_common.cpp.
sycl_host_distance() [1/15]
cl::cl_double __host_std::sycl_host_distance (cl::cl_double p0, cl::cl_double p1)
Definition at line 232 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [2/15]
cl::cl_float __host_std::sycl_host_distance (cl::cl_float p0, cl::cl_float p1)
Definition at line 212 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [3/15]
cl::cl_half __host_std::sycl_host_distance (cl::cl_half p0, cl::cl_half p1)
Definition at line 252 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [4/15]
cl::cl_double __host_std::sycl_host_distance (s::vec< cl::cl_double, 2 > p0, s::vec< cl::cl_double, 2 > p1)
Definition at line 240 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [5/15]
cl::cl_double __host_std::sycl_host_distance (s::vec< cl::cl_double, 3 > p0, s::vec< cl::cl_double, 3 > p1)
Definition at line 244 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [6/15]
cl::cl_double __host_std::sycl_host_distance (s::vec< cl::cl_double, 4 > p0, s::vec< cl::cl_double, 4 > p1)
Definition at line 248 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [7/15]
cl::cl_float __host_std::sycl_host_distance (s::vec< cl::cl_float, 2 > p0, s::vec< cl::cl_float, 2 > p1)
Definition at line 220 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [8/15]
cl::cl_float __host_std::sycl_host_distance (s::vec< cl::cl_float, 3 > p0, s::vec< cl::cl_float, 3 > p1)
Definition at line 224 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [9/15]
cl::cl_float __host_std::sycl_host_distance (s::vec< cl::cl_float, 4 > p0, s::vec< cl::cl_float, 4 > p1)
Definition at line 228 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [10/15]
cl::cl_half __host_std::sycl_host_distance (s::vec< cl::cl_half, 2 > p0, s::vec< cl::cl_half, 2 > p1)
Definition at line 259 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [11/15]
cl::cl_half __host_std::sycl_host_distance (s::vec< cl::cl_half, 3 > p0, s::vec< cl::cl_half, 3 > p1)
Definition at line 263 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [12/15]
cl::cl_half __host_std::sycl_host_distance (s::vec< cl::cl_half, 4 > p0, s::vec< cl::cl_half, 4 > p1)
Definition at line 267 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [13/15]
cl::cl_float __host_std::sycl_host_distance (s::vec< double, 1 > p0, s::vec< double, 1 > p1)
Definition at line 236 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [14/15]
cl::cl_float __host_std::sycl_host_distance (s::vec< float, 1 > p0, s::vec< float, 1 > p1)
Definition at line 216 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_distance() [15/15]
cl::cl_float __host_std::sycl_host_distance (s::vec< s::half, 1 > p0, s::vec< s::half, 1 > p1)
Definition at line 255 of file builtins_geometric.cpp.
References sycl_host_length().
sycl_host_Dot() [1/12]
cl::cl_double __host_std::sycl_host_Dot (s::vec< cl::cl_double, 2 > , s::vec< cl::cl_double, 2 >)
sycl_host_Dot() [2/12]
cl::cl_double __host_std::sycl_host_Dot (s::vec< cl::cl_double, 3 > , s::vec< cl::cl_double, 3 >)
sycl_host_Dot() [3/12]
cl::cl_double __host_std::sycl_host_Dot (s::vec< cl::cl_double, 4 > , s::vec< cl::cl_double, 4 >)
sycl_host_Dot() [4/12]
cl::cl_float __host_std::sycl_host_Dot (s::vec< cl::cl_float, 2 > , s::vec< cl::cl_float, 2 >)
sycl_host_Dot() [5/12]
cl::cl_float __host_std::sycl_host_Dot (s::vec< cl::cl_float, 3 > , s::vec< cl::cl_float, 3 >)
sycl_host_Dot() [6/12]
cl::cl_float __host_std::sycl_host_Dot (s::vec< cl::cl_float, 4 > , s::vec< cl::cl_float, 4 >)
sycl_host_Dot() [7/12]
cl::cl_half __host_std::sycl_host_Dot (s::vec< cl::cl_half, 2 > , s::vec< cl::cl_half, 2 >)
sycl_host_Dot() [8/12]
cl::cl_half __host_std::sycl_host_Dot (s::vec< cl::cl_half, 3 > , s::vec< cl::cl_half, 3 >)
sycl_host_Dot() [9/12]
cl::cl_half __host_std::sycl_host_Dot (s::vec< cl::cl_half, 4 > , s::vec< cl::cl_half, 4 >)
sycl_host_Dot() [10/12]
cl::cl_double __host_std::sycl_host_Dot (s::vec< double, 1 > , s::vec< double, 1 >)
sycl_host_Dot() [11/12]
cl::cl_float __host_std::sycl_host_Dot (s::vec< float, 1 > , s::vec< float, 1 >)
sycl_host_Dot() [12/12]
cl::cl_half __host_std::sycl_host_Dot (s::vec< s::half, 1 > , s::vec< s::half, 1 >)
sycl_host_erf() [1/3]
s::cl_double __host_std::sycl_host_erf (s::cl_double x)
Definition at line 363 of file builtins_math.cpp.
sycl_host_erf() [2/3]
s::cl_float __host_std::sycl_host_erf (s::cl_float x)
Definition at line 360 of file builtins_math.cpp.
sycl_host_erf() [3/3]
s::cl_half __host_std::sycl_host_erf (s::cl_half x)
Definition at line 366 of file builtins_math.cpp.
sycl_host_erfc() [1/3]
s::cl_double __host_std::sycl_host_erfc (s::cl_double x)
Definition at line 349 of file builtins_math.cpp.
sycl_host_erfc() [2/3]
s::cl_float __host_std::sycl_host_erfc (s::cl_float x)
Definition at line 346 of file builtins_math.cpp.
sycl_host_erfc() [3/3]
s::cl_half __host_std::sycl_host_erfc (s::cl_half x)
Definition at line 352 of file builtins_math.cpp.
sycl_host_exp() [1/3]
s::cl_double __host_std::sycl_host_exp (s::cl_double x)
Definition at line 377 of file builtins_math.cpp.
sycl_host_exp() [2/3]
s::cl_float __host_std::sycl_host_exp (s::cl_float x)
Definition at line 374 of file builtins_math.cpp.
sycl_host_exp() [3/3]
s::cl_half __host_std::sycl_host_exp (s::cl_half x)
Definition at line 380 of file builtins_math.cpp.
sycl_host_exp10() [1/3]
s::cl_double __host_std::sycl_host_exp10 (s::cl_double x)
Definition at line 405 of file builtins_math.cpp.
sycl_host_exp10() [2/3]
s::cl_float __host_std::sycl_host_exp10 (s::cl_float x)
Definition at line 402 of file builtins_math.cpp.
sycl_host_exp10() [3/3]
s::cl_half __host_std::sycl_host_exp10 (s::cl_half x)
Definition at line 408 of file builtins_math.cpp.
sycl_host_exp2() [1/3]
s::cl_double __host_std::sycl_host_exp2 (s::cl_double x)
Definition at line 391 of file builtins_math.cpp.
sycl_host_exp2() [2/3]
s::cl_float __host_std::sycl_host_exp2 (s::cl_float x)
Definition at line 388 of file builtins_math.cpp.
sycl_host_exp2() [3/3]
s::cl_half __host_std::sycl_host_exp2 (s::cl_half x)
Definition at line 394 of file builtins_math.cpp.
sycl_host_expm1() [1/3]
s::cl_double __host_std::sycl_host_expm1 (s::cl_double x)
Definition at line 419 of file builtins_math.cpp.
sycl_host_expm1() [2/3]
s::cl_float __host_std::sycl_host_expm1 (s::cl_float x)
Definition at line 416 of file builtins_math.cpp.
sycl_host_expm1() [3/3]
s::cl_half __host_std::sycl_host_expm1 (s::cl_half x)
Definition at line 422 of file builtins_math.cpp.
sycl_host_fabs() [1/3]
s::cl_double __host_std::sycl_host_fabs (s::cl_double x)
Definition at line 433 of file builtins_math.cpp.
sycl_host_fabs() [2/3]
s::cl_float __host_std::sycl_host_fabs (s::cl_float x)
Definition at line 430 of file builtins_math.cpp.
sycl_host_fabs() [3/3]
s::cl_half __host_std::sycl_host_fabs (s::cl_half x)
Definition at line 436 of file builtins_math.cpp.
sycl_host_fast_distance() [1/5]
cl::cl_float __host_std::sycl_host_fast_distance (cl::cl_float p0, cl::cl_float p1)
Definition at line 366 of file builtins_geometric.cpp.
References sycl_host_fast_length().
sycl_host_fast_distance() [2/5]
cl::cl_float __host_std::sycl_host_fast_distance (s::vec< cl::cl_float, 2 > p0, s::vec< cl::cl_float, 2 > p1)
Definition at line 374 of file builtins_geometric.cpp.
References sycl_host_fast_length().
sycl_host_fast_distance() [3/5]
cl::cl_float __host_std::sycl_host_fast_distance (s::vec< cl::cl_float, 3 > p0, s::vec< cl::cl_float, 3 > p1)
Definition at line 378 of file builtins_geometric.cpp.
References sycl_host_fast_length().
sycl_host_fast_distance() [4/5]
cl::cl_float __host_std::sycl_host_fast_distance (s::vec< cl::cl_float, 4 > p0, s::vec< cl::cl_float, 4 > p1)
Definition at line 382 of file builtins_geometric.cpp.
References sycl_host_fast_length().
sycl_host_fast_distance() [5/5]
cl::cl_float __host_std::sycl_host_fast_distance (s::vec< float, 1 > p0, s::vec< float, 1 > p1)
Definition at line 370 of file builtins_geometric.cpp.
References sycl_host_fast_length().
sycl_host_fast_length() [1/5]
cl::cl_float __host_std::sycl_host_fast_length (cl::cl_float p)
Definition at line 326 of file builtins_geometric.cpp.
Referenced by sycl_host_fast_distance().
sycl_host_fast_length() [2/5]
cl::cl_float __host_std::sycl_host_fast_length (s::vec< cl::cl_float, 2 > p)
Definition at line 332 of file builtins_geometric.cpp.
sycl_host_fast_length() [3/5]
cl::cl_float __host_std::sycl_host_fast_length (s::vec< cl::cl_float, 3 > p)
Definition at line 335 of file builtins_geometric.cpp.
sycl_host_fast_length() [4/5]
cl::cl_float __host_std::sycl_host_fast_length (s::vec< cl::cl_float, 4 > p)
Definition at line 338 of file builtins_geometric.cpp.
sycl_host_fast_length() [5/5]
cl::cl_float __host_std::sycl_host_fast_length (s::vec< float, 1 > p)
Definition at line 329 of file builtins_geometric.cpp.
sycl_host_fast_normalize() [1/5]
cl::cl_float __host_std::sycl_host_fast_normalize (cl::cl_float p)
Definition at line 343 of file builtins_geometric.cpp.
References sycl_host_FMul().
sycl_host_fast_normalize() [2/5]
s::vec<cl::cl_float, 2> __host_std::sycl_host_fast_normalize (s::vec< cl::cl_float, 2 > p)
Definition at line 353 of file builtins_geometric.cpp.
sycl_host_fast_normalize() [3/5]
s::vec<cl::cl_float, 3> __host_std::sycl_host_fast_normalize (s::vec< cl::cl_float, 3 > p)
Definition at line 357 of file builtins_geometric.cpp.
sycl_host_fast_normalize() [4/5]
s::vec<cl::cl_float, 4> __host_std::sycl_host_fast_normalize (s::vec< cl::cl_float, 4 > p)
Definition at line 361 of file builtins_geometric.cpp.
sycl_host_fast_normalize() [5/5]
cl::cl_float __host_std::sycl_host_fast_normalize (s::vec< float, 1 > p)
Definition at line 349 of file builtins_geometric.cpp.
sycl_host_fclamp() [1/3]
s::cl_double __host_std::sycl_host_fclamp (s::cl_double x, s::cl_double minval, s::cl_double maxval)
Definition at line 72 of file builtins_common.cpp.
sycl_host_fclamp() [2/3]
s::cl_float __host_std::sycl_host_fclamp (s::cl_float x, s::cl_float minval, s::cl_float maxval)
Definition at line 68 of file builtins_common.cpp.
sycl_host_fclamp() [3/3]
s::cl_half __host_std::sycl_host_fclamp (s::cl_half x, s::cl_half minval, s::cl_half maxval)
Definition at line 76 of file builtins_common.cpp.
sycl_host_fdim() [1/3]
s::cl_double __host_std::sycl_host_fdim (s::cl_double x, s::cl_double y)
Definition at line 447 of file builtins_math.cpp.
sycl_host_fdim() [2/3]
s::cl_float __host_std::sycl_host_fdim (s::cl_float x, s::cl_float y)
Definition at line 444 of file builtins_math.cpp.
sycl_host_fdim() [3/3]
s::cl_half __host_std::sycl_host_fdim (s::cl_half x, s::cl_half y)
Definition at line 451 of file builtins_math.cpp.
sycl_host_floor() [1/3]
s::cl_double __host_std::sycl_host_floor (s::cl_double x)
Definition at line 462 of file builtins_math.cpp.
sycl_host_floor() [2/3]
s::cl_float __host_std::sycl_host_floor (s::cl_float x)
Definition at line 459 of file builtins_math.cpp.
sycl_host_floor() [3/3]
s::cl_half __host_std::sycl_host_floor (s::cl_half x)
Definition at line 465 of file builtins_math.cpp.
sycl_host_fma() [1/3]
s::cl_double __host_std::sycl_host_fma (s::cl_double a, s::cl_double b, s::cl_double c)
Definition at line 477 of file builtins_math.cpp.
sycl_host_fma() [2/3]
s::cl_float __host_std::sycl_host_fma (s::cl_float a, s::cl_float b, s::cl_float c)
Definition at line 473 of file builtins_math.cpp.
sycl_host_fma() [3/3]
s::cl_half __host_std::sycl_host_fma (s::cl_half a, s::cl_half b, s::cl_half c)
Definition at line 481 of file builtins_math.cpp.
sycl_host_fmax_common() [1/3]
s::cl_double __host_std::sycl_host_fmax_common (s::cl_double x, s::cl_double y)
Definition at line 122 of file builtins_common.cpp.
sycl_host_fmax_common() [2/3]
s::cl_float __host_std::sycl_host_fmax_common (s::cl_float x, s::cl_float y)
Definition at line 118 of file builtins_common.cpp.
sycl_host_fmax_common() [3/3]
s::cl_half __host_std::sycl_host_fmax_common (s::cl_half x, s::cl_half y)
Definition at line 126 of file builtins_common.cpp.
sycl_host_fmin_common() [1/3]
s::cl_double __host_std::sycl_host_fmin_common (s::cl_double x, s::cl_double y)
Definition at line 105 of file builtins_common.cpp.
sycl_host_fmin_common() [2/3]
s::cl_float __host_std::sycl_host_fmin_common (s::cl_float x, s::cl_float y)
Definition at line 101 of file builtins_common.cpp.
sycl_host_fmin_common() [3/3]
s::cl_half __host_std::sycl_host_fmin_common (s::cl_half x, s::cl_half y)
Definition at line 109 of file builtins_common.cpp.
sycl_host_FMul() [1/3]
cl::cl_double __host_std::sycl_host_FMul (cl::cl_double p0, cl::cl_double p1)
Definition at line 149 of file builtins_geometric.cpp.
sycl_host_FMul() [2/3]
cl::cl_float __host_std::sycl_host_FMul (cl::cl_float p0, cl::cl_float p1)
Definition at line 146 of file builtins_geometric.cpp.
Referenced by sycl_host_fast_normalize().
sycl_host_FMul() [3/3]
cl::cl_float __host_std::sycl_host_FMul (cl::cl_half p0, cl::cl_half p1)
Definition at line 152 of file builtins_geometric.cpp.
sycl_host_FOrdEqual() [1/3]
rel_res_t __host_std::sycl_host_FOrdEqual (s::cl_double x, s::cl_double y)
Definition at line 157 of file builtins_relational.cpp.
sycl_host_FOrdEqual() [2/3]
rel_res_t __host_std::sycl_host_FOrdEqual (s::cl_float x, s::cl_float y)
Definition at line 153 of file builtins_relational.cpp.
sycl_host_FOrdEqual() [3/3]
rel_res_t __host_std::sycl_host_FOrdEqual (s::cl_half x, s::cl_half y)
Definition at line 161 of file builtins_relational.cpp.
sycl_host_length() [1/14]
cl::cl_double __host_std::sycl_host_length (cl::cl_double p)
Definition at line 168 of file builtins_geometric.cpp.
Referenced by sycl_host_distance().
sycl_host_length() [2/14]
cl::cl_half __host_std::sycl_host_length (cl::cl_half p)
Definition at line 171 of file builtins_geometric.cpp.
sycl_host_length() [3/14]
cl::cl_double __host_std::sycl_host_length (s::vec< cl::cl_double, 2 > p)
Definition at line 189 of file builtins_geometric.cpp.
sycl_host_length() [4/14]
cl::cl_double __host_std::sycl_host_length (s::vec< cl::cl_double, 3 > p)
Definition at line 192 of file builtins_geometric.cpp.
sycl_host_length() [5/14]
cl::cl_double __host_std::sycl_host_length (s::vec< cl::cl_double, 4 > p)
Definition at line 195 of file builtins_geometric.cpp.
sycl_host_length() [6/14]
cl::cl_float __host_std::sycl_host_length (s::vec< cl::cl_float, 2 > p)
Definition at line 177 of file builtins_geometric.cpp.
sycl_host_length() [7/14]
cl::cl_float __host_std::sycl_host_length (s::vec< cl::cl_float, 3 > p)
Definition at line 180 of file builtins_geometric.cpp.
sycl_host_length() [8/14]
cl::cl_float __host_std::sycl_host_length (s::vec< cl::cl_float, 4 > p)
Definition at line 183 of file builtins_geometric.cpp.
sycl_host_length() [9/14]
cl::cl_half __host_std::sycl_host_length (s::vec< cl::cl_half, 2 > p)
Definition at line 201 of file builtins_geometric.cpp.
sycl_host_length() [10/14]
cl::cl_half __host_std::sycl_host_length (s::vec< cl::cl_half, 3 > p)
Definition at line 204 of file builtins_geometric.cpp.
sycl_host_length() [11/14]
cl::cl_half __host_std::sycl_host_length (s::vec< cl::cl_half, 4 > p)
Definition at line 207 of file builtins_geometric.cpp.
sycl_host_length() [12/14]
cl::cl_double __host_std::sycl_host_length (s::vec< double, 1 > p)
Definition at line 186 of file builtins_geometric.cpp.
sycl_host_length() [13/14]
cl::cl_float __host_std::sycl_host_length (s::vec< float, 1 > p)
Definition at line 174 of file builtins_geometric.cpp.
sycl_host_length() [14/14]
cl::cl_half __host_std::sycl_host_length (s::vec< s::half, 1 > p)
Definition at line 198 of file builtins_geometric.cpp.
sycl_host_mix() [1/3]
s::cl_double __host_std::sycl_host_mix (s::cl_double x, s::cl_double y, s::cl_double a)
Definition at line 139 of file builtins_common.cpp.
sycl_host_mix() [2/3]
s::cl_float __host_std::sycl_host_mix (s::cl_float x, s::cl_float y, s::cl_float a)
Definition at line 135 of file builtins_common.cpp.
sycl_host_mix() [3/3]
s::cl_half __host_std::sycl_host_mix (s::cl_half x, s::cl_half y, s::cl_half a)
Definition at line 143 of file builtins_common.cpp.
sycl_host_normalize() [1/14]
cl::cl_double __host_std::sycl_host_normalize (cl::cl_double p)
Definition at line 291 of file builtins_geometric.cpp.
sycl_host_normalize() [2/14]
cl::cl_float __host_std::sycl_host_normalize (cl::cl_float p)
Definition at line 273 of file builtins_geometric.cpp.
sycl_host_normalize() [3/14]
cl::cl_half __host_std::sycl_host_normalize (cl::cl_half p)
Definition at line 309 of file builtins_geometric.cpp.
sycl_host_normalize() [4/14]
s::vec<cl::cl_double, 2> __host_std::sycl_host_normalize (s::vec< cl::cl_double, 2 > p)
Definition at line 298 of file builtins_geometric.cpp.
sycl_host_normalize() [5/14]
s::vec<cl::cl_double, 3> __host_std::sycl_host_normalize (s::vec< cl::cl_double, 3 > p)
Definition at line 302 of file builtins_geometric.cpp.
sycl_host_normalize() [6/14]
s::vec<cl::cl_double, 4> __host_std::sycl_host_normalize (s::vec< cl::cl_double, 4 > p)
Definition at line 306 of file builtins_geometric.cpp.
sycl_host_normalize() [7/14]
s::vec<cl::cl_float, 2> __host_std::sycl_host_normalize (s::vec< cl::cl_float, 2 > p)
Definition at line 280 of file builtins_geometric.cpp.
sycl_host_normalize() [8/14]
s::vec<cl::cl_float, 3> __host_std::sycl_host_normalize (s::vec< cl::cl_float, 3 > p)
Definition at line 284 of file builtins_geometric.cpp.
sycl_host_normalize() [9/14]
s::vec<cl::cl_float, 4> __host_std::sycl_host_normalize (s::vec< cl::cl_float, 4 > p)
Definition at line 288 of file builtins_geometric.cpp.
sycl_host_normalize() [10/14]
s::vec<cl::cl_half, 2> __host_std::sycl_host_normalize (s::vec< cl::cl_half, 2 > p)
Definition at line 313 of file builtins_geometric.cpp.
sycl_host_normalize() [11/14]
s::vec<cl::cl_half, 3> __host_std::sycl_host_normalize (s::vec< cl::cl_half, 3 > p)
Definition at line 317 of file builtins_geometric.cpp.
sycl_host_normalize() [12/14]
s::vec<cl::cl_half, 4> __host_std::sycl_host_normalize (s::vec< cl::cl_half, 4 > p)
Definition at line 321 of file builtins_geometric.cpp.
sycl_host_normalize() [13/14]
cl::cl_double __host_std::sycl_host_normalize (s::vec< double, 1 > p)
Definition at line 294 of file builtins_geometric.cpp.
sycl_host_normalize() [14/14]
cl::cl_float __host_std::sycl_host_normalize (s::vec< float, 1 > p)
Definition at line 276 of file builtins_geometric.cpp.
sycl_host_s_abs() [1/4]
s::cl_uchar __host_std::sycl_host_s_abs (s::cl_char x)
Definition at line 260 of file builtins_integer.cpp.
sycl_host_s_abs() [2/4]
s::cl_uint __host_std::sycl_host_s_abs (s::cl_int x)
Definition at line 266 of file builtins_integer.cpp.
sycl_host_s_abs() [3/4]
s::cl_ulong __host_std::sycl_host_s_abs (s::cl_long x)
Definition at line 269 of file builtins_integer.cpp.
sycl_host_s_abs() [4/4]
s::cl_ushort __host_std::sycl_host_s_abs (s::cl_short x)
Definition at line 263 of file builtins_integer.cpp.
sycl_host_s_abs_diff() [1/4]
s::cl_uchar __host_std::sycl_host_s_abs_diff (s::cl_char x, s::cl_char y)
Definition at line 301 of file builtins_integer.cpp.
sycl_host_s_abs_diff() [2/4]
s::cl_uint __host_std::sycl_host_s_abs_diff (s::cl_int x, s::cl_int y)
Definition at line 309 of file builtins_integer.cpp.
sycl_host_s_abs_diff() [3/4]
s::cl_ulong __host_std::sycl_host_s_abs_diff (s::cl_long x, s::cl_long y)
Definition at line 313 of file builtins_integer.cpp.
sycl_host_s_abs_diff() [4/4]
s::cl_ushort __host_std::sycl_host_s_abs_diff (s::cl_short x, s::cl_short y)
Definition at line 305 of file builtins_integer.cpp.
sycl_host_s_add_sat() [1/4]
s::cl_char __host_std::sycl_host_s_add_sat (s::cl_char x, s::cl_char y)
Definition at line 345 of file builtins_integer.cpp.
sycl_host_s_add_sat() [2/4]
s::cl_int __host_std::sycl_host_s_add_sat (s::cl_int x, s::cl_int y)
Definition at line 353 of file builtins_integer.cpp.
sycl_host_s_add_sat() [3/4]
s::cl_long __host_std::sycl_host_s_add_sat (s::cl_long x, s::cl_long y)
Definition at line 356 of file builtins_integer.cpp.
sycl_host_s_add_sat() [4/4]
s::cl_short __host_std::sycl_host_s_add_sat (s::cl_short x, s::cl_short y)
Definition at line 349 of file builtins_integer.cpp.
sycl_host_s_clamp() [1/4]
s::cl_ushort s::cl_uchar s::cl_ulong s::cl_char __host_std::sycl_host_s_clamp (s::cl_char x, s::cl_char minval, s::cl_char maxval)
Definition at line 479 of file builtins_integer.cpp.
sycl_host_s_clamp() [2/4]
s::cl_int __host_std::sycl_host_s_clamp (s::cl_int x, s::cl_int minval, s::cl_int maxval)
Definition at line 487 of file builtins_integer.cpp.
sycl_host_s_clamp() [3/4]
s::cl_long __host_std::sycl_host_s_clamp (s::cl_long x, s::cl_long minval, s::cl_long maxval)
Definition at line 491 of file builtins_integer.cpp.
sycl_host_s_clamp() [4/4]
s::cl_short __host_std::sycl_host_s_clamp (s::cl_short x, s::cl_short minval, s::cl_short maxval)
Definition at line 483 of file builtins_integer.cpp.
sycl_host_s_hadd() [1/4]
s::cl_char __host_std::sycl_host_s_hadd (s::cl_char x, s::cl_char y)
Definition at line 387 of file builtins_integer.cpp.
sycl_host_s_hadd() [2/4]
s::cl_int __host_std::sycl_host_s_hadd (s::cl_int x, s::cl_int y)
Definition at line 394 of file builtins_integer.cpp.
sycl_host_s_hadd() [3/4]
s::cl_long __host_std::sycl_host_s_hadd (s::cl_long x, s::cl_long y)
Definition at line 397 of file builtins_integer.cpp.
sycl_host_s_hadd() [4/4]
s::cl_short __host_std::sycl_host_s_hadd (s::cl_short x, s::cl_short y)
Definition at line 390 of file builtins_integer.cpp.
sycl_host_s_mad_hi() [1/4]
s::cl_char __host_std::sycl_host_s_mad_hi (s::cl_char x, s::cl_char minval, s::cl_char maxval)
Definition at line 609 of file builtins_integer.cpp.
sycl_host_s_mad_hi() [2/4]
s::cl_int __host_std::sycl_host_s_mad_hi (s::cl_int x, s::cl_int minval, s::cl_int maxval)
Definition at line 617 of file builtins_integer.cpp.
sycl_host_s_mad_hi() [3/4]
s::cl_long __host_std::sycl_host_s_mad_hi (s::cl_long x, s::cl_long minval, s::cl_long maxval)
Definition at line 621 of file builtins_integer.cpp.
sycl_host_s_mad_hi() [4/4]
s::cl_short __host_std::sycl_host_s_mad_hi (s::cl_short x, s::cl_short minval, s::cl_short maxval)
Definition at line 613 of file builtins_integer.cpp.
sycl_host_s_mul_hi() [1/4]
s::cl_char __host_std::sycl_host_s_mul_hi (s::cl_char a, s::cl_char b)
Definition at line 571 of file builtins_integer.cpp.
sycl_host_s_mul_hi() [2/4]
s::cl_int __host_std::sycl_host_s_mul_hi (s::cl_int a, s::cl_int b)
Definition at line 577 of file builtins_integer.cpp.
sycl_host_s_mul_hi() [3/4]
s::cl_long __host_std::sycl_host_s_mul_hi (s::cl_long x, s::cl_long y)
Definition at line 580 of file builtins_integer.cpp.
sycl_host_s_mul_hi() [4/4]
s::cl_short __host_std::sycl_host_s_mul_hi (s::cl_short a, s::cl_short b)
Definition at line 574 of file builtins_integer.cpp.
sycl_host_s_rhadd() [1/4]
s::cl_char __host_std::sycl_host_s_rhadd (s::cl_char x, s::cl_char y)
Definition at line 427 of file builtins_integer.cpp.
sycl_host_s_rhadd() [2/4]
s::cl_int __host_std::sycl_host_s_rhadd (s::cl_int x, s::cl_int y)
Definition at line 434 of file builtins_integer.cpp.
sycl_host_s_rhadd() [3/4]
s::cl_long __host_std::sycl_host_s_rhadd (s::cl_long x, s::cl_long y)
Definition at line 437 of file builtins_integer.cpp.
sycl_host_s_rhadd() [4/4]
s::cl_short __host_std::sycl_host_s_rhadd (s::cl_short x, s::cl_short y)
Definition at line 430 of file builtins_integer.cpp.
sycl_host_u_abs() [1/4]
s::cl_uchar __host_std::sycl_host_u_abs (s::cl_uchar x)
Definition at line 250 of file builtins_integer.cpp.
sycl_host_u_abs() [2/4]
s::cl_uint __host_std::sycl_host_u_abs (s::cl_uint x)
Definition at line 252 of file builtins_integer.cpp.
sycl_host_u_abs() [3/4]
s::cl_ulong __host_std::sycl_host_u_abs (s::cl_ulong x)
Definition at line 253 of file builtins_integer.cpp.
sycl_host_u_abs() [4/4]
s::cl_ushort __host_std::sycl_host_u_abs (s::cl_ushort x)
Definition at line 251 of file builtins_integer.cpp.
sycl_host_u_abs_diff() [1/4]
s::cl_uchar __host_std::sycl_host_u_abs_diff (s::cl_uchar x, s::cl_uchar y)
Definition at line 278 of file builtins_integer.cpp.
sycl_host_u_abs_diff() [2/4]
s::cl_uint __host_std::sycl_host_u_abs_diff (s::cl_uint x, s::cl_uint y)
Definition at line 286 of file builtins_integer.cpp.
sycl_host_u_abs_diff() [3/4]
s::cl_ulong __host_std::sycl_host_u_abs_diff (s::cl_ulong x, s::cl_ulong y)
Definition at line 290 of file builtins_integer.cpp.
sycl_host_u_abs_diff() [4/4]
s::cl_ushort __host_std::sycl_host_u_abs_diff (s::cl_ushort x, s::cl_ushort y)
Definition at line 282 of file builtins_integer.cpp.
sycl_host_u_add_sat() [1/4]
s::cl_uchar __host_std::sycl_host_u_add_sat (s::cl_uchar x, s::cl_uchar y)
Definition at line 323 of file builtins_integer.cpp.
sycl_host_u_add_sat() [2/4]
s::cl_uint __host_std::sycl_host_u_add_sat (s::cl_uint x, s::cl_uint y)
Definition at line 331 of file builtins_integer.cpp.
sycl_host_u_add_sat() [3/4]
s::cl_ulong __host_std::sycl_host_u_add_sat (s::cl_ulong x, s::cl_ulong y)
Definition at line 335 of file builtins_integer.cpp.
sycl_host_u_add_sat() [4/4]
s::cl_ushort __host_std::sycl_host_u_add_sat (s::cl_ushort x, s::cl_ushort y)
Definition at line 327 of file builtins_integer.cpp.
sycl_host_u_clamp() [1/4]
s::cl_uchar __host_std::sycl_host_u_clamp (s::cl_uchar x, s::cl_uchar minval, s::cl_uchar maxval)
Definition at line 446 of file builtins_integer.cpp.
sycl_host_u_clamp() [2/4]
s::cl_uint __host_std::sycl_host_u_clamp (s::cl_uint x, s::cl_uint minval, s::cl_uint maxval)
Definition at line 455 of file builtins_integer.cpp.
sycl_host_u_clamp() [3/4]
s::cl_ulong __host_std::sycl_host_u_clamp (s::cl_ulong x, s::cl_ulong minval, s::cl_ulong maxval)
Definition at line 459 of file builtins_integer.cpp.
sycl_host_u_clamp() [4/4]
s::cl_ushort __host_std::sycl_host_u_clamp (s::cl_ushort x, s::cl_ushort minval, s::cl_ushort maxval)
Definition at line 450 of file builtins_integer.cpp.
sycl_host_u_hadd() [1/4]
s::cl_uchar __host_std::sycl_host_u_hadd (s::cl_uchar x, s::cl_uchar y)
Definition at line 366 of file builtins_integer.cpp.
sycl_host_u_hadd() [2/4]
s::cl_uint __host_std::sycl_host_u_hadd (s::cl_uint x, s::cl_uint y)
Definition at line 374 of file builtins_integer.cpp.
sycl_host_u_hadd() [3/4]
s::cl_ulong __host_std::sycl_host_u_hadd (s::cl_ulong x, s::cl_ulong y)
Definition at line 377 of file builtins_integer.cpp.
sycl_host_u_hadd() [4/4]
s::cl_ushort __host_std::sycl_host_u_hadd (s::cl_ushort x, s::cl_ushort y)
Definition at line 370 of file builtins_integer.cpp.
sycl_host_u_mul_hi() [1/4]
s::cl_uchar __host_std::sycl_host_u_mul_hi (s::cl_uchar a, s::cl_uchar b)
Definition at line 590 of file builtins_integer.cpp.
sycl_host_u_mul_hi() [2/4]
s::cl_uint __host_std::sycl_host_u_mul_hi (s::cl_uint a, s::cl_uint b)
Definition at line 596 of file builtins_integer.cpp.
sycl_host_u_mul_hi() [3/4]
s::cl_ulong __host_std::sycl_host_u_mul_hi (s::cl_ulong x, s::cl_ulong y)
Definition at line 599 of file builtins_integer.cpp.
sycl_host_u_mul_hi() [4/4]
s::cl_ushort __host_std::sycl_host_u_mul_hi (s::cl_ushort a, s::cl_ushort b)
Definition at line 593 of file builtins_integer.cpp.
sycl_host_u_rhadd() [1/4]
s::cl_uchar __host_std::sycl_host_u_rhadd (s::cl_uchar x, s::cl_uchar y)
Definition at line 406 of file builtins_integer.cpp.
sycl_host_u_rhadd() [2/4]
s::cl_uint __host_std::sycl_host_u_rhadd (s::cl_uint x, s::cl_uint y)
Definition at line 414 of file builtins_integer.cpp.
sycl_host_u_rhadd() [3/4]
s::cl_ulong __host_std::sycl_host_u_rhadd (s::cl_ulong x, s::cl_ulong y)
Definition at line 417 of file builtins_integer.cpp.
sycl_host_u_rhadd() [4/4]
s::cl_ushort __host_std::sycl_host_u_rhadd (s::cl_ushort x, s::cl_ushort y)
Definition at line 410 of file builtins_integer.cpp.
Variable Documentation
__FMul_impl
__host_std::__FMul_impl
Definition at line 159 of file builtins_geometric.cpp.
__vFOrdEqual
__host_std::__vFOrdEqual
Definition at line 167 of file builtins_relational.cpp.