DPC++ Runtime: sycl::_V1::detail::ur Namespace Reference
sycl::_V1::detail::ur Namespace Reference
Classes
struct IsStdVector
struct IsStdVector< std::vector< T > >
Typedefs
using DeviceBinaryType = ::sycl_device_binary_type
Functions
template<class To >
To cast (std::vector< cl_event > value)
template<>
ur_program_handle_t cast (cl_program)=delete
template<>
ur_device_handle_t cast (cl_device_id)=delete
void * loadOsLibrary (const std::string &Library)
int unloadOsLibrary (void *Library)
void * getOsLibraryFuncAddress (void *Library, const std::string &FunctionName)
std::vector< PluginPtr > & initializeUr (ur_loader_config_handle_t LoaderConfig=nullptr)
template<backend BE>
const PluginPtr & getPlugin ()
bool trace ()
template<class To , class From >
To cast (From value)
template<class To , class FromE >
To cast (std::vector< FromE > Values)
ur_program_metadata_t mapDeviceBinaryPropertyToProgramMetadata (const sycl_device_binary_property &DeviceBinaryProperty)
static void initializePlugins (std::vector< PluginPtr > &Plugins, ur_loader_config_handle_t LoaderConfig)
template const PluginPtr & getPlugin< backend::opencl > ()
template const PluginPtr & getPlugin< backend::ext_oneapi_level_zero > ()
template const PluginPtr & getPlugin< backend::ext_oneapi_cuda > ()
template const PluginPtr & getPlugin< backend::ext_oneapi_hip > ()
template<typename ResT >
static ResT readELFValue (const unsigned char *Data, size_t NumBytes, bool IsBigEndian)
static bool checkELFSectionPresent (const std::string &ExpectedSectionName, const unsigned char *ImgData, size_t ImgSize)
static uint16_t getELFHeaderType (const unsigned char *ImgData, size_t ImgSize)
sycl_device_binary_type getBinaryImageFormat (const unsigned char *ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
static std::filesystem::path getCurrentDSODirPath ()
Variables
bool XPTIInitDone = false
Typedef Documentation
DeviceBinaryType
using sycl::_V1::detail::ur::DeviceBinaryType = typedef ::sycl_device_binary_type
Definition at line 72 of file ur_utils.hpp.
Function Documentation
cast() [1/5]
template<> ur_device_handle_t sycl::_V1::detail::ur::cast (cl_device_id) inline delete
cast() [2/5]
template<> ur_program_handle_t sycl::_V1::detail::ur::cast (cl_program) inline delete
cast() [3/5]
template<class To , class From > To sycl::_V1::detail::ur::cast (From value) inline
Definition at line 94 of file ur.hpp.
cast() [4/5]
template<class To > To sycl::_V1::detail::ur::cast (std::vector< cl_event > value) inline
Definition at line 145 of file backend_traits_opencl.hpp.
Referenced by sycl::_V1::detail::BufferInterop< backend::opencl, DataT, Dimensions, AllocatorT >::GetNativeObjs().
cast() [5/5]
template<class To , class FromE > To sycl::_V1::detail::ur::cast (std::vector< FromE > Values)
Definition at line 106 of file ur.hpp.
checkELFSectionPresent()
static bool sycl::_V1::detail::ur::checkELFSectionPresent (const std::string & ExpectedSectionName, const unsigned char * ImgData, size_t ImgSize) static
Definition at line 263 of file ur.cpp.
Referenced by getBinaryImageFormat().
getBinaryImageFormat()
DeviceBinaryType sycl::_V1::detail::ur::getBinaryImageFormat (const unsigned char * ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
Returns SYCL_DEVICE_BINARY_TYPE_NONE if unsuccessful.
Definition at line 335 of file ur.cpp.
References checkELFSectionPresent(), getELFHeaderType(), SYCL_DEVICE_BINARY_TYPE_LLVMIR_BITCODE, SYCL_DEVICE_BINARY_TYPE_NATIVE, SYCL_DEVICE_BINARY_TYPE_NONE, and SYCL_DEVICE_BINARY_TYPE_SPIRV.
Referenced by sycl::_V1::detail::ProgramManager::createURProgram(), sycl::_V1::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage(), and sycl::_V1::detail::RTDeviceBinaryImage::init().
getCurrentDSODirPath()
static std::filesystem::path sycl::_V1::detail::ur::getCurrentDSODirPath () static
Definition at line 55 of file windows_ur.cpp.
References ExeModuleHandle, and getOSModuleHandle().
getELFHeaderType()
static uint16_t sycl::_V1::detail::ur::getELFHeaderType (const unsigned char * ImgData, size_t ImgSize) static
Definition at line 327 of file ur.cpp.
Referenced by getBinaryImageFormat().
getOsLibraryFuncAddress()
void * sycl::_V1::detail::ur::getOsLibraryFuncAddress (void * Library, const std::string & FunctionName)
Definition at line 34 of file posix_ur.cpp.
Referenced by sycl::_V1::ext::__SYCL2020_DEPRECATED(), sycl::_V1::ext::oneapi::experimental::detail::checkOclocLibrary(), and sycl::_V1::ext::oneapi::experimental::detail::SetupLibrary().
getPlugin()
template<backend BE> const PluginPtr & sycl::_V1::detail::ur::getPlugin ()
Definition at line 226 of file ur.cpp.
References initializeUr(), and sycl::_V1::runtime.
getPlugin< backend::ext_oneapi_cuda >()
template const PluginPtr& sycl::_V1::detail::ur::getPlugin< backend::ext_oneapi_cuda > ()
getPlugin< backend::ext_oneapi_hip >()
template const PluginPtr& sycl::_V1::detail::ur::getPlugin< backend::ext_oneapi_hip > ()
getPlugin< backend::ext_oneapi_level_zero >()
template const PluginPtr& sycl::_V1::detail::ur::getPlugin< backend::ext_oneapi_level_zero > ()
getPlugin< backend::opencl >()
template const PluginPtr& sycl::_V1::detail::ur::getPlugin< backend::opencl > ()
initializePlugins()
static void sycl::_V1::detail::ur::initializePlugins (std::vector< PluginPtr > & Plugins, ur_loader_config_handle_t LoaderConfig) static
Definition at line 96 of file ur.cpp.
References sycl::_V1::all, std::cerr, CHECK_UR_SUCCESS, sycl::_V1::detail::codeLocationCallback(), sycl::_V1::ext_oneapi_cuda, sycl::_V1::ext_oneapi_hip, sycl::_V1::ext_oneapi_level_zero, sycl::_V1::ext_oneapi_native_cpu, sycl::_V1::detail::SYCLConfig< Config >::get(), sycl::_V1::detail::ProgramManager::getInstance(), sycl::_V1::detail::GlobalHandler::getXPTIRegistry(), sycl::_V1::detail::XPTIRegistry::initializeFrameworkOnce(), sycl::_V1::detail::XPTIRegistry::initializeStream(), sycl::_V1::detail::GlobalHandler::instance(), sycl::_V1::opencl, sycl::_V1::detail::SYCL_STREAM_NAME, and XPTIInitDone.
Referenced by initializeUr().
initializeUr()
std::vector< PluginPtr > & sycl::_V1::detail::ur::initializeUr (ur_loader_config_handle_t LoaderConfig = nullptr)
Definition at line 86 of file ur.cpp.
References sycl::_V1::detail::GlobalHandler::getPlugins(), initializePlugins(), and sycl::_V1::detail::GlobalHandler::instance().
Referenced by sycl::_V1::detail::platform_impl::get_devices(), sycl::_V1::detail::platform_impl::get_platforms(), and getPlugin().
loadOsLibrary()
void * sycl::_V1::detail::ur::loadOsLibrary (const std::string & Library)
Definition at line 20 of file posix_ur.cpp.
References std::cerr, and trace().
Referenced by sycl::_V1::ext::__SYCL2020_DEPRECATED(), and sycl::_V1::ext::oneapi::experimental::detail::loadOclocLibrary().
mapDeviceBinaryPropertyToProgramMetadata()
ur_program_metadata_t sycl::_V1::detail::ur::mapDeviceBinaryPropertyToProgramMetadata (const sycl_device_binary_property & DeviceBinaryProperty)
Definition at line 382 of file ur.cpp.
References SYCL_PROPERTY_TYPE_BYTE_ARRAY, SYCL_PROPERTY_TYPE_STRING, and SYCL_PROPERTY_TYPE_UINT32.
Referenced by sycl::_V1::detail::RTDeviceBinaryImage::init().
readELFValue()
template<typename ResT > static ResT sycl::_V1::detail::ur::readELFValue (const unsigned char * Data, size_t NumBytes, bool IsBigEndian) static
Definition at line 248 of file ur.cpp.
References sycl::_V1::ext::oneapi::experimental::copy().
trace()
bool sycl::_V1::detail::ur::trace ()
Definition at line 78 of file ur.cpp.
References sycl::_V1::detail::SYCLConfig< Config >::get().
Referenced by sycl::_V1::detail::IsBannedPlatform(), loadOsLibrary(), and sycl::_V1::detail::traceDeviceSelection().
unloadOsLibrary()
int sycl::_V1::detail::ur::unloadOsLibrary (void * Library)
Definition at line 32 of file posix_ur.cpp.
Variable Documentation
XPTIInitDone
bool sycl::_V1::detail::ur::XPTIInitDone = false
Definition at line 83 of file ur.cpp.
Referenced by initializePlugins().