DPC++ Runtime: sycl::_V1::detail Namespace Reference
sycl::_V1::detail Namespace Reference
Namespaces
acc_properties
builtins
device_global_map
enqueue_kernel_launch
gtl
gvl
half_impl
host_half_impl
host_pipe_map
kernel_get_group_info
pi
reduction
spirv
sub_group
usm
Classes
struct NegateDecorated
struct NegateDecorated< access::decorated::yes >
struct NegateDecorated< access::decorated::no >
struct TargetToAS
struct TargetToAS< access::target::local >
struct TargetToAS< access::target::constant_buffer >
struct DecoratedType
struct DecoratedType< ElementType, access::address_space::private_space >
struct DecoratedType< ElementType, access::address_space::generic_space >
struct DecoratedType< ElementType, access::address_space::global_space >
struct DecoratedType< ElementType, access::address_space::ext_intel_global_device_space >
struct DecoratedType< ElementType, access::address_space::ext_intel_global_host_space >
struct DecoratedType< ElementType, access::address_space::constant_space >
struct DecoratedType< ElementType, access::address_space::local_space >
struct remove_decoration_impl
struct AccHostDataT
struct IsCxPropertyList
struct IsCxPropertyList< ext::oneapi::accessor_property_list< Props... > >
struct IsCxPropertyList< ext::oneapi::accessor_property_list<> >
class accessor_common
class LocalAccessorBaseDevice
class AccessorImplDevice
class AccessorBaseHost
class LocalAccessorBaseHost
struct IsValidCoordDataT
struct IsValidCoordDataT< 1, T >
struct IsValidCoordDataT< 2, T >
struct IsValidCoordDataT< 3, T >
struct IsValidUnsampledCoord2020DataT
struct IsValidUnsampledCoord2020DataT< 1, T >
struct IsValidUnsampledCoord2020DataT< 2, T >
struct IsValidUnsampledCoord2020DataT< 3, T >
struct IsValidSampledCoord2020DataT
struct IsValidSampledCoord2020DataT< 1, T >
struct IsValidSampledCoord2020DataT< 2, T >
struct IsValidSampledCoord2020DataT< 3, T >
class UnsampledImageAccessorBaseHost
class SampledImageAccessorBaseHost
class __image_array_slice__
class image_accessor
struct IsValidAtomicType
struct IsValidAtomicAddressSpace
struct GetSpirvMemoryScope
struct GetSpirvMemoryScope< access::address_space::global_space >
struct GetSpirvMemoryScope< access::address_space::ext_intel_global_device_space >
struct GetSpirvMemoryScope< access::address_space::local_space >
struct IsValidAtomicRefType
struct IsValidAtomicRefAddressSpace
struct memory_order_traits
struct memory_order_traits< memory_order::relaxed >
struct memory_order_traits< memory_order::acq_rel >
struct memory_order_traits< memory_order::seq_cst >
struct bit_equal
struct bit_equal< T, typename std::enable_if_t< std::is_integral_v< T > > >
struct bit_equal< float >
struct bit_equal< double >
class atomic_ref_base
class atomic_ref_impl
class atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >
class atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_floating_point_v< T > > >
class atomic_ref_impl< T, true, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >
class atomic_ref_impl< T, true, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_floating_point_v< T > > >
class atomic_ref_impl< T *, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace >
struct BufferInterop
struct BufferInterop< backend::opencl, DataT, Dimensions, AllocatorT >
class buffer_plain
struct use_fast_math
struct is_same_op
struct get_signed_int_by_size
struct same_size_signed_int
struct get_unsigned_int_by_size
struct same_size_unsigned_int
struct get_fixed_sized_int
struct simplify_if_swizzle
struct is_valid_elem_type
struct get_multi_ptr_decoration
struct get_multi_ptr_decoration< multi_ptr< ElementType, Space, DecorateAddress > >
struct has_writeable_addr_space
struct has_writeable_addr_space< multi_ptr< ElementType, Space, DecorateAddress > >
struct is_swizzle
struct is_swizzle< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct is_valid_elem_type< marray< T, N >, Ts... >
struct is_valid_elem_type< vec< T, N >, Ts... >
struct is_valid_elem_type< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... >, Ts... >
struct is_valid_elem_type< multi_ptr< ElementType, Space, DecorateAddress >, Ts... >
struct num_elements
struct num_elements< marray< T, N > >
struct num_elements< vec< T, N > >
struct num_elements< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct is_valid_size
struct simplify_if_swizzle< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct is_same_op< T1, T2, std::enable_if_t< is_vec_or_swizzle_v< T1 > &&is_vec_or_swizzle_v< T2 > > >
struct same_size_signed_int< marray< T, N > >
struct same_size_signed_int< vec< T, N > >
struct same_size_signed_int< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct same_size_unsigned_int< marray< T, N > >
struct same_size_unsigned_int< vec< T, N > >
struct same_size_unsigned_int< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct change_elements
struct change_elements< NewElemT, marray< T, N > >
struct change_elements< NewElemT, vec< T, N > >
struct change_elements< NewElemT, SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
class accessor_iterator
class aligned_allocator
class array
struct AssertHappened
struct interop
struct BackendInput
struct BackendReturn
struct InteropFeatureSupportMap
struct interop< backend::ext_oneapi_cuda, context >
struct interop< backend::ext_oneapi_cuda, device >
struct interop< backend::ext_oneapi_cuda, event >
struct interop< backend::ext_oneapi_cuda, queue >
struct BackendInput< backend::ext_oneapi_cuda, buffer< DataT, Dimensions, AllocatorT > >
struct BackendReturn< backend::ext_oneapi_cuda, buffer< DataT, Dimensions, AllocatorT > >
struct BackendInput< backend::ext_oneapi_cuda, context >
struct BackendReturn< backend::ext_oneapi_cuda, context >
struct BackendInput< backend::ext_oneapi_cuda, device >
struct BackendReturn< backend::ext_oneapi_cuda, device >
struct BackendInput< backend::ext_oneapi_cuda, event >
struct BackendReturn< backend::ext_oneapi_cuda, event >
struct BackendInput< backend::ext_oneapi_cuda, queue >
struct BackendReturn< backend::ext_oneapi_cuda, queue >
struct interop< backend::ext_oneapi_hip, context >
struct interop< backend::ext_oneapi_hip, device >
struct interop< backend::ext_oneapi_hip, event >
struct interop< backend::ext_oneapi_hip, queue >
struct BackendInput< backend::ext_oneapi_hip, buffer< DataT, Dimensions, AllocatorT > >
struct BackendReturn< backend::ext_oneapi_hip, buffer< DataT, Dimensions, AllocatorT > >
struct BackendInput< backend::ext_oneapi_hip, context >
struct BackendReturn< backend::ext_oneapi_hip, context >
struct BackendInput< backend::ext_oneapi_hip, device >
struct BackendReturn< backend::ext_oneapi_hip, device >
struct BackendInput< backend::ext_oneapi_hip, event >
struct BackendReturn< backend::ext_oneapi_hip, event >
struct BackendInput< backend::ext_oneapi_hip, queue >
struct BackendReturn< backend::ext_oneapi_hip, queue >
struct InteropFeatureSupportMap< backend::ext_oneapi_hip >
struct interop< backend::ext_oneapi_level_zero, context >
struct interop< backend::ext_oneapi_level_zero, device >
struct interop< backend::ext_oneapi_level_zero, event >
struct interop< backend::ext_oneapi_level_zero, queue >
struct interop< backend::ext_oneapi_level_zero, platform >
struct interop< backend::ext_oneapi_level_zero, kernel >
struct BackendInput< backend::ext_oneapi_level_zero, context >
struct BackendReturn< backend::ext_oneapi_level_zero, context >
struct BackendInput< backend::ext_oneapi_level_zero, device >
struct BackendReturn< backend::ext_oneapi_level_zero, device >
struct BackendInput< backend::ext_oneapi_level_zero, event >
struct BackendReturn< backend::ext_oneapi_level_zero, event >
struct BackendInput< backend::ext_oneapi_level_zero, queue >
struct BackendInput< backend::ext_oneapi_level_zero, buffer< DataT, Dimensions, AllocatorT > >
struct BackendReturn< backend::ext_oneapi_level_zero, buffer< DataT, Dimensions, AllocatorT > >
struct BackendInput< backend::ext_oneapi_level_zero, image< Dimensions, AllocatorT > >
struct BackendReturn< backend::ext_oneapi_level_zero, image< Dimensions, AllocatorT > >
struct BackendReturn< backend::ext_oneapi_level_zero, queue >
struct BackendInput< backend::ext_oneapi_level_zero, platform >
struct BackendReturn< backend::ext_oneapi_level_zero, platform >
struct BackendInput< backend::ext_oneapi_level_zero, kernel_bundle< State > >
struct BackendReturn< backend::ext_oneapi_level_zero, kernel_bundle< State > >
struct BackendInput< backend::ext_oneapi_level_zero, kernel >
struct BackendReturn< backend::ext_oneapi_level_zero, kernel >
struct InteropFeatureSupportMap< backend::ext_oneapi_level_zero >
struct interop< backend::opencl, context >
struct interop< backend::opencl, device >
struct interop< backend::opencl, queue >
struct interop< backend::opencl, platform >
struct BackendInput< backend::opencl, buffer< DataT, Dimensions, AllocatorT > >
struct BackendReturn< backend::opencl, buffer< DataT, Dimensions, AllocatorT > >
struct BackendInput< backend::opencl, context >
struct BackendReturn< backend::opencl, context >
struct BackendInput< backend::opencl, device >
struct BackendReturn< backend::opencl, device >
struct interop< backend::opencl, event >
struct BackendInput< backend::opencl, event >
struct BackendReturn< backend::opencl, event >
struct BackendInput< backend::opencl, queue >
struct BackendReturn< backend::opencl, queue >
struct BackendInput< backend::opencl, platform >
struct BackendReturn< backend::opencl, platform >
struct BackendInput< backend::opencl, kernel_bundle< State > >
struct BackendReturn< backend::opencl, kernel_bundle< State > >
struct BackendInput< backend::opencl, kernel >
struct BackendReturn< backend::opencl, kernel >
struct InteropFeatureSupportMap< backend::opencl >
struct Assigner
struct Assigner< 0 >
struct Boolean
struct fp_elem_type
struct float_elem_type
struct same_basic_shape
struct same_elem_type
struct any_shape
struct scalar_only
struct non_scalar_only
struct default_ret_type
struct scalar_ret_type
struct builtin_enable
class CG
Base class for all types of command groups.
class CGExecKernel
"Execute kernel" command group class.
class CGCopy
"Copy memory" command group class.
class CGFill
"Fill memory" command group class.
class CGUpdateHost
"Update host" command group class.
class CGCopyUSM
"Copy USM" command group class.
class CGFillUSM
"Fill USM" command group class.
class CGPrefetchUSM
"Prefetch USM" command group class.
class CGAdviseUSM
"Advise USM" command group class.
class CGHostTask
class CGBarrier
class CGCopy2DUSM
"Copy 2D USM" command group class.
class CGFill2DUSM
"Fill 2D USM" command group class.
class CGMemset2DUSM
"Memset 2D USM" command group class.
class CGReadWriteHostPipe
"ReadWriteHostPipe" command group class.
class CGCopyToDeviceGlobal
"Copy to device_global" command group class.
class CGCopyFromDeviceGlobal
"Copy to device_global" command group class.
class CGCopyImage
"Copy Image" command group class.
class CGSemaphoreWait
"Semaphore Wait" command group class.
class CGSemaphoreSignal
"Semaphore Signal" command group class.
class CGExecCommandBuffer
"Execute command-buffer" command group class.
class ArgDesc
class NDRDescT
struct check_fn_signature
struct check_fn_signature< F, RetT(Args...)>
struct KernelLambdaHasKernelHandlerArgT
class HostKernelBase
class HostTask
class HostKernel
struct code_location
class tls_code_loc_t
Data type that manages the code_location information in TLS.
struct InitializedVal
struct InitializedVal< 1, T >
struct InitializedVal< 2, T >
struct InitializedVal< 3, T >
struct NDLoopIterateImpl
Helper class for the NDLoop.
struct NDLoopIterateImpl< NDims, 0, LoopBoundTy, FuncTy, LoopIndexTy >
struct NDLoop
Generates an NDims-dimensional perfect loop nest.
struct InlineVariableHelper
struct ArrayCreator
struct ArrayCreator< DataT, FlattenF, ArgT, ArgTN... >
struct ArrayCreator< DataT, FlattenF >
struct ods_target
class ods_target_list
struct select_cl_scalar_complex_or_T
struct GetNumElements
struct GetNumElements< typename sycl::vec< Type, NumElements > >
struct GetNumElements< typename sycl::detail::Boolean< N > >
class TryToGetElementType
class Builder
class HostProfilingInfo
Profiling info for the host execution.
struct PiInfoCode
struct is_platform_info_desc
struct is_context_info_desc
struct is_device_info_desc
struct is_queue_info_desc
struct is_kernel_info_desc
struct is_kernel_device_specific_info_desc
struct is_event_info_desc
struct is_event_profiling_info_desc
struct is_backend_info_desc
struct IsSubGroupInfo
struct IsSubGroupInfo< info::kernel_device_specific::max_num_sub_groups >
struct IsSubGroupInfo< info::kernel_device_specific::compile_num_sub_groups >
struct IsSubGroupInfo< info::kernel_device_specific::max_sub_group_size >
struct IsSubGroupInfo< info::kernel_device_specific::compile_sub_group_size >
struct is_device_copyable_impl
struct is_device_copyable_impl< T, std::enable_if_t<!std::is_same_v< T, std::remove_cv_t< T > > > >
struct ItemBase
struct ItemBase< Dims, true >
struct ItemBase< Dims, false >
struct conditional
struct conditional< false, TrueT, FalseT >
struct kernel_param_desc_t
struct SpecConstantInfo
struct KernelInfo
struct register_alloc_mode_key
class Locked
Represents a reference to value with appropriate lock acquired.
class OSUtil
Groups the OS-dependent services.
class OwnerLessBase
class DataLessPropertyBase
class DataLessProperty
class PropertyWithDataBase
class PropertyWithData
class PropertyListBase
class reduction_impl_algo
class reduction_impl_base
Base non-template class which is a base class for all reduction implementation classes.
struct IsReduction
Predicate returning true if a type is a reduction.
struct AreAllButLastReductions
Predicate returning true if all template type parameters except the last one are reductions.
struct AreAllButLastReductions< T >
Helper specialization of AreAllButLastReductions for one element only.
class SpinLock
SpinLock is a synchronization primitive, that uses atomic variable and causes thread trying acquire lock wait in loop while repeatedly check if the lock is available.
struct is_output_iterator
struct is_output_iterator< T, output_iterator_requirements< T > >
class string
class string_view
class SYCLMemObjAllocator
class SYCLMemObjAllocatorHolder
struct tuple
struct tuple_element
struct tuple_element< N, tuple< T, Rest... > >
struct tuple_element< 0, tuple< T, Rest... > >
struct get
struct get< 0 >
struct TupleValueHolder
struct TupleCopyAssignableValueHolder
struct TupleCopyAssignableValueHolder< T, false >
struct tuple< T, Ts... >
struct tuple<>
struct value_list
struct value_list< T, Head, Tail... >
struct value_list< T >
struct is_contained_value
struct is_contained_value< T, Value, value_list< T > >
struct is_type_size_equal
struct is_type_size_double_of
struct find_type
struct is_fixed_size_group
class SwizzleOp
struct is_group
struct is_group< group< Dimensions > >
struct is_sub_group
struct is_sub_group< ext::oneapi::sub_group >
struct is_sub_group< sycl::sub_group >
struct is_generic_group
struct copy_cv_qualifiers
struct vector_size_impl
struct vector_size_impl< vec< T, N > >
struct vector_size
struct vector_element_impl
struct vector_element_impl< vec< T, N > >
struct vector_element
struct get_elem_type
struct get_elem_type< marray< T, N > >
struct get_elem_type< vec< T, N > >
struct get_elem_type< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct get_elem_type< multi_ptr< ElementType, Space, DecorateAddress > >
struct is_ext_vector
struct is_ext_vector< T, std::void_t< decltype(__builtin_reduce_max(std::declval< T >()))> >
struct get_elem_type< T, std::enable_if_t< is_ext_vector_v< T > > >
struct change_base_type
struct change_base_type< vec< T, N >, B >
struct copy_cv_qualifiers_impl
struct copy_cv_qualifiers_impl< const T, R >
struct copy_cv_qualifiers_impl< volatile T, R >
struct copy_cv_qualifiers_impl< const volatile T, R >
struct make_signed
struct make_signed< const T >
struct make_signed< vec< T, N > >
struct make_signed< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct make_signed< marray< T, N > >
struct make_unsigned
struct make_unsigned< const T >
struct make_unsigned< vec< T, N > >
struct make_unsigned< SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct make_unsigned< marray< T, N > >
struct is_vec
struct is_vec< sycl::vec< T, N > >
struct get_vec_size
struct get_vec_size< sycl::vec< T, N > >
struct is_marray
struct is_marray< sycl::marray< T, N > >
struct is_integral
struct is_floating_point_impl
struct is_floating_point_impl< half >
struct is_floating_point
struct is_arithmetic
struct is_scalar_arithmetic
struct is_vector_arithmetic
struct is_scalar_bool
struct is_vector_bool
struct is_bool
struct is_boolean
struct is_boolean< Boolean< N > >
struct is_pointer_impl
struct is_pointer_impl< T * >
struct is_pointer_impl< multi_ptr< T, Space, DecorateAddress > >
struct is_pointer
struct is_multi_ptr
struct is_multi_ptr< multi_ptr< ElementType, Space, IsDecorated > >
struct is_non_legacy_multi_ptr
struct is_non_legacy_multi_ptr< multi_ptr< ElementType, Space, access::decorated::yes > >
struct is_non_legacy_multi_ptr< multi_ptr< ElementType, Space, access::decorated::no > >
struct is_legacy_multi_ptr
struct is_legacy_multi_ptr< multi_ptr< ElementType, Space, access::decorated::legacy > >
struct remove_pointer_impl
struct remove_pointer_impl< T * >
struct remove_pointer_impl< multi_ptr< T, Space, DecorateAddress > >
struct remove_pointer
struct is_address_space_compliant_impl
struct is_address_space_compliant_impl< T *, SpaceList >
struct is_address_space_compliant_impl< multi_ptr< T, Space, DecorateAddress >, SpaceList >
struct is_address_space_compliant
struct make_type_impl
struct make_type_impl< vec< T, N >, TL >
struct make_larger_impl
struct make_larger_impl< T, std::enable_if_t< is_contained< T, gtl::scalar_floating_list >::value, T > >
struct make_larger_impl< T, std::enable_if_t< is_contained< T, gtl::scalar_signed_integer_list >::value, T > >
struct make_larger_impl< T, std::enable_if_t< is_contained< T, gtl::scalar_unsigned_integer_list >::value, T > >
struct make_larger_impl< vec< T, N >, vec< T, N > >
struct make_larger_impl< marray< T, N >, marray< T, N > >
struct make_larger
struct function_traits
struct function_traits< Ret(Args...)>
struct first_type
struct map_type
struct map_type< T, From, To, Rest... >
class Sync
Groups and provides access to all the locks used the SYCL runtime.
struct TempAssignGuard
struct HashCStr
struct CmpCStr
struct ABINeutralT
struct ABINeutralT< std::string >
struct ABINeutralT< std::vector< std::string > >
struct vector_alignment_impl
struct vector_alignment
class SYCLCategory
struct IsCompileTimePropertyInstance
struct interop< backend::ext_oneapi_cuda, platform >
struct BackendInput< backend::ext_oneapi_cuda, platform >
struct BackendReturn< backend::ext_oneapi_cuda, platform >
struct InteropFeatureSupportMap< backend::ext_oneapi_cuda >
class if_architecture_helper
struct is_fixed_size_group< ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup > >
struct is_native_op
struct is_complex
struct is_vector_arithmetic_or_complex
struct get_scalar_binary_op
struct get_scalar_binary_op< F< sycl::vec< T, n > > >
struct get_scalar_binary_op< F< void > >
struct is_max_or_min
struct is_max_or_min< sycl::maximum< T > >
struct is_max_or_min< sycl::minimum< T > >
class __pf_kernel_wrapper
struct get_kernel_wrapper_name_t
struct GetMergedKernelProperties
struct GetMergedKernelProperties< KernelType, PropertiesT, std::enable_if_t< ext::oneapi::experimental::detail::HasKernelPropertiesGetMethod< KernelType >::value > >
class RoundedRangeIDGenerator
class RoundedRangeKernel
class RoundedRangeKernelWithKH
class image_plain
class image_common
class unsampled_image_common
class auto_name
This class is the default KernelName template parameter type for kernel invocation APIs such as single_task.
struct get_kernel_name_t
Helper struct to get a kernel name type based on given Name and Type types: if Name is undefined (is a auto_name) then Type becomes the Name.
class device_image_plain
class kernel_bundle_plain
struct isComplex
struct has_known_identity_impl
struct known_identity_impl
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsZeroIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns zero as identity for ADD, OR, XOR operations.
struct known_identity_impl< BinaryOperation, vec< std::byte, NumElements >, std::enable_if_t< IsZeroIdentityOp< vec< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, marray< std::byte, NumElements >, std::enable_if_t< IsZeroIdentityOp< marray< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, vec< sycl::half, NumElements >, std::enable_if_t< IsZeroIdentityOp< vec< sycl::half, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, half, std::enable_if_t< IsZeroIdentityOp< half, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsOneIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns one as identify for MULTIPLY operations.
struct known_identity_impl< BinaryOperation, vec< std::byte, NumElements >, std::enable_if_t< IsOneIdentityOp< vec< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, marray< std::byte, NumElements >, std::enable_if_t< IsOneIdentityOp< marray< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, half, std::enable_if_t< IsOneIdentityOp< half, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsOnesIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns bit image consisting of all ones as identity for AND operations.
struct known_identity_impl< BinaryOperation, vec< std::byte, NumElements >, std::enable_if_t< IsOnesIdentityOp< vec< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, marray< std::byte, NumElements >, std::enable_if_t< IsOnesIdentityOp< marray< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsMinimumIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns maximal possible value as identity for MIN operations.
struct known_identity_impl< BinaryOperation, vec< std::byte, NumElements >, std::enable_if_t< IsMinimumIdentityOp< vec< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, marray< std::byte, NumElements >, std::enable_if_t< IsMinimumIdentityOp< marray< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsMaximumIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns minimal possible value as identity for MAX operations.
struct known_identity_impl< BinaryOperation, vec< std::byte, NumElements >, std::enable_if_t< IsMaximumIdentityOp< vec< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, marray< std::byte, NumElements >, std::enable_if_t< IsMaximumIdentityOp< marray< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsFalseIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns false as identity for LOGICAL OR operations.
struct known_identity_impl< BinaryOperation, vec< std::byte, NumElements >, std::enable_if_t< IsFalseIdentityOp< vec< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, marray< std::byte, NumElements >, std::enable_if_t< IsFalseIdentityOp< marray< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsTrueIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns true as identity for LOGICAL AND operations.
struct known_identity_impl< BinaryOperation, vec< std::byte, NumElements >, std::enable_if_t< IsTrueIdentityOp< vec< std::byte, NumElements >, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, marray< std::byte, NumElements >, std::enable_if_t< IsTrueIdentityOp< marray< std::byte, NumElements >, BinaryOperation >::value > >
struct GetMArrayArgsSize
struct GetMArrayArgsSize<>
struct GetMArrayArgsSize< marray< T, N >, Ts... >
struct GetMArrayArgsSize< T, Ts... >
struct LegacyPointerTypes
struct LegacyPointerTypes< ElementType, access::address_space::constant_space >
struct LegacyReferenceTypes
struct LegacyReferenceTypes< ElementType, access::address_space::constant_space >
struct IsCompileTimePropertyInstance< ext::intel::property::buffer_location::instance< I > >
struct IsCompileTimePropertyInstance< ext::oneapi::property::no_alias::instance<> >
struct IsCompileTimePropertyInstance< ext::oneapi::property::no_offset::instance<> >
class ReducerElement
struct ReducerTraits
Helper class for accessing reducer-defined types in CRTP May prove to be useful for other things later.
struct ReducerTraits< reducer< T, BinaryOperation, Dims, Extent, IdentityContainerT, View, Subst > >
class ReducerAccess
Helper class for accessing internal reducer member functions.
class combiner
Use CRTP to avoid redefining shorthand operators in terms of combine.
class ReductionIdentityContainer
Templated class for common functionality of all reduction implementation classes.
class ReductionIdentityContainer< T, BinaryOperation, ExplicitIdentity, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >
class ReductionIdentityContainer< T, BinaryOperation, true, enable_if_t<!IsKnownIdentityOp< T, BinaryOperation >::value > >
class ReductionIdentityContainer< T, BinaryOperation, false, std::enable_if_t<!IsKnownIdentityOp< T, BinaryOperation >::value > >
class reducer_common
struct ReducerToken
struct data_dim_t
struct data_dim_t< accessor< T, AccessorDims, Mode, access::target::device, IsPH, PropList > >
struct get_red_t
struct get_red_t< T * >
struct get_red_t< buffer< T, Dims, AllocatorT > >
class reduction_impl
This class encapsulates the reduction variable/accessor, the reduction operator and an optional operator identity.
struct KernelOneWGTag
struct KernelMultipleWGTag
struct NDRangeReduction
struct NDRangeReduction< reduction::strategy::local_atomic_and_atomic_cross_wg >
struct NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >
struct NDRangeReduction< reduction::strategy::range_basic >
struct NDRangeReduction< reduction::strategy::group_reduce_and_atomic_cross_wg >
struct NDRangeReduction< reduction::strategy::local_mem_tree_and_atomic_cross_wg >
struct NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >
struct NDRangeReduction< reduction::strategy::basic >
struct IsNonUsmReductionPredicate
struct EmptyReductionPredicate
struct FilterElement
struct IsScalarReduction
struct IsArrayReduction
struct NDRangeReduction< reduction::strategy::multi >
struct NDRangeReduction< reduction::strategy::auto_select >
struct IsSwizzleOp
struct IsSwizzleOp< sycl::detail::SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct IsDeprecatedDeviceCopyable
struct vec_helper
struct vec_helper< bool >
struct vec_helper< sycl::ext::oneapi::bfloat16 >
struct vec_helper< std::byte >
struct VecStorage
class GetOp
struct VecStorageImpl
struct VecStorage< bool, 1, void >
struct VecStorage< bool, N, typename std::enable_if_t< isValidVectorSize(N)> >
struct VecStorage< std::byte, 1, void >
struct VecStorage< T, 1, typename std::enable_if_t< is_sigeninteger_v< T > > >
struct VecStorage< T, 1, typename std::enable_if_t< is_sugeninteger_v< T > > >
struct VecStorage< T, 1, typename std::enable_if_t<!is_half_or_bf16_v< T > &&is_sgenfloat_v< T > > >
struct VecStorage< T, N, typename std::enable_if_t< isValidVectorSize(N) &&(is_sgeninteger_v< T >||(is_sgenfloat_v< T > &&!is_half_or_bf16_v< T >))> >
struct VecStorage< half, 1, void >
struct VecStorage< sycl::ext::oneapi::bfloat16, 1, void >
class GetScalarOp
struct EqualTo
struct NotEqualTo
struct GreaterEqualTo
struct LessEqualTo
struct GreaterThan
struct LessThan
struct LogicalAnd
struct LogicalOr
struct RShift
struct LShift
class AccessorImplHost
class LocalAccessorImplHost
class UnsampledImageAccessorImplHost
class SampledImageAccessorImplHost
class buffer_impl
class CircularBuffer
class SYCLConfigBase
class SYCLConfig
class SYCLConfig< SYCL_PI_TRACE >
class SYCLConfig< SYCL_RT_WARNING_LEVEL >
class SYCLConfig< SYCL_PARALLEL_FOR_RANGE_ROUNDING_TRACE >
class SYCLConfig< SYCL_DISABLE_PARALLEL_FOR_RANGE_ROUNDING >
class SYCLConfig< SYCL_PARALLEL_FOR_RANGE_ROUNDING_PARAMS >
class SYCLConfig< ONEAPI_DEVICE_SELECTOR >
class SYCLConfig< SYCL_ENABLE_DEFAULT_CONTEXTS >
class SYCLConfig< SYCL_QUEUE_THREAD_POOL_SIZE >
class SYCLConfig< SYCL_CACHE_PERSISTENT >
class SYCLConfig< SYCL_CACHE_DIR >
class SYCLConfig< SYCL_REDUCTION_PREFERRED_WORKGROUP_SIZE >
class SYCLConfig< SYCL_ENABLE_FUSION_CACHING >
class SYCLConfig< SYCL_CACHE_IN_MEM >
class context_impl
class ByteArray
class DeviceBinaryProperty
class RTDeviceBinaryImage
class DynRTDeviceBinaryImage
struct DeviceGlobalUSMMem
struct DeviceGlobalMapEntry
struct LessByHash
class device_image_impl
class device_impl
struct sycl_to_pi
struct sycl_to_pi< bool >
struct sycl_to_pi< device >
struct sycl_to_pi< platform >
struct check_fp_support
struct check_fp_support< info::device::half_fp_config >
struct check_fp_support< info::device::double_fp_config >
struct get_device_info_impl
struct get_device_info_impl< platform, Param >
struct get_device_info_impl< std::string, Param >
struct get_device_info_impl< ReturnT, info::device::parent_device >
struct get_device_info_impl< std::vector< info::fp_config >, Param >
struct get_device_info_impl< std::string, info::device::version >
struct get_device_info_impl< std::vector< info::fp_config >, info::device::single_fp_config >
struct get_device_info_impl< bool, info::device::queue_profiling >
struct get_device_info_impl< std::vector< memory_order >, info::device::atomic_memory_order_capabilities >
struct get_device_info_impl< std::vector< memory_order >, info::device::atomic_fence_order_capabilities >
struct get_device_info_impl< std::vector< memory_scope >, info::device::atomic_memory_scope_capabilities >
struct get_device_info_impl< std::vector< memory_scope >, info::device::atomic_fence_scope_capabilities >
struct get_device_info_impl< bool, info::device::ext_oneapi_bfloat16_math_functions >
struct get_device_info_impl< std::vector< info::execution_capability >, info::device::execution_capabilities >
struct get_device_info_impl< std::vector< kernel_id >, info::device::built_in_kernel_ids >
struct get_device_info_impl< std::vector< std::string >, info::device::built_in_kernels >
struct get_device_info_impl< std::vector< std::string >, info::device::extensions >
struct get_device_info_impl< std::vector< info::partition_property >, info::device::partition_properties >
struct get_device_info_impl< std::vector< info::partition_affinity_domain >, info::device::partition_affinity_domains >
struct get_device_info_impl< info::partition_affinity_domain, info::device::partition_type_affinity_domain >
struct get_device_info_impl< info::partition_property, info::device::partition_type_property >
struct get_device_info_impl< std::vector< size_t >, info::device::sub_group_sizes >
struct get_device_info_impl< bool, info::device::kernel_kernel_pipe_support >
struct get_device_info_impl< range< Dimensions >, info::device::max_work_item_sizes< Dimensions > >
struct get_device_info_impl< ext::oneapi::experimental::architecture, ext::oneapi::experimental::info::device::architecture >
struct get_device_info_impl< std::vector< ext::oneapi::experimental::matrix::combination >, ext::oneapi::experimental::info::device::matrix_combinations >
struct get_device_info_impl< size_t, ext::oneapi::experimental::info::device::max_global_work_groups >
struct get_device_info_impl< id< 1 >, ext::oneapi::experimental::info::device::max_work_groups< 1 > >
struct get_device_info_impl< id< 2 >, ext::oneapi::experimental::info::device::max_work_groups< 2 > >
struct get_device_info_impl< id< 3 >, ext::oneapi::experimental::info::device::max_work_groups< 3 > >
struct get_device_info_impl< size_t, info::device::ext_oneapi_max_global_work_groups >
struct get_device_info_impl< id< 1 >, info::device::ext_oneapi_max_work_groups_1d >
struct get_device_info_impl< id< 2 >, info::device::ext_oneapi_max_work_groups_2d >
struct get_device_info_impl< id< 3 >, info::device::ext_oneapi_max_work_groups_3d >
struct get_device_info_impl< device, info::device::parent_device >
struct get_device_info_impl< bool, info::device::image_support >
struct get_device_info_impl< bool, info::device::usm_device_allocations >
struct get_device_info_impl< bool, info::device::usm_host_allocations >
struct get_device_info_impl< bool, info::device::usm_shared_allocations >
struct get_device_info_impl< bool, info::device::usm_restricted_shared_allocations >
struct get_device_info_impl< bool, info::device::usm_system_allocations >
struct get_device_info_impl< bool, ext::codeplay::experimental::info::device::supports_fusion >
struct get_device_info_impl< uint32_t, ext::codeplay::experimental::info::device::max_registers_per_work_group >
struct get_device_info_impl< std::vector< sycl::device >, ext::oneapi::experimental::info::device::component_devices >
struct get_device_info_impl< sycl::device, ext::oneapi::experimental::info::device::composite_device >
class event_impl
class fusion_wrapper_impl
class ObjectUsageCounter
struct DefaultContextReleaseHandler
class GlobalHandler
Wrapper class for global data structures with non-trivial destructors.
class handler_impl
struct HostPipeMapEntry
class image_impl
class jit_compiler
class OffloadEntryContainer
Representation of _pi_offload_entry for creation of JIT device binaries at runtime.
class PropertyContainer
Representation of _pi_device_binary_property_struct for creation of JIT device binaries at runtime.
class PropertySetContainer
Representation of _pi_device_binary_property_set_struct for creation of JIT device binaries at runtime.
class DeviceBinaryContainer
Representation of pi_device_binary_struct for creation of JIT device binaries at runtime.
class DeviceBinariesCollection
Representation of pi_device_binaries_struct for creation of JIT device binaries at runtime.
class kernel_bundle_impl
The class is an impl counterpart of the sycl::kernel_bundle.
struct LessByNameComp
struct EqualByNameComp
class kernel_id_impl
class kernel_impl
class KernelProgramCache
struct TermPositions
class MemoryManager
class LockCacheItem
class PersistentDeviceCodeCache
struct OwnedPiEvent
class platform_impl
struct PlatformUtil
struct array_fill_helper
struct PiApiArgTuple
struct array_fill_helper< Kind, Idx, T >
struct array_fill_helper< Kind, Idx, T, Args... >
class plugin
The plugin class provides a unified interface to the underlying low-level runtimes for the device-agnostic SYCL runtime.
class program_impl
class ProgramManager
class queue_impl
class sampler_impl
class DispatchHostTask
struct EnqueueResultT
Result of command enqueueing.
struct DepDesc
Dependency between two commands.
class Command
The Command class represents some action that needs to be performed on one or more memory objects.
class EmptyCommand
The empty command does nothing during enqueue.
class ReleaseCommand
The release command enqueues release of a memory object instance allocated on Host or underlying framework.
class AllocaCommandBase
Base class for memory allocation commands.
class AllocaCommand
The alloca command enqueues allocation of instance of memory object on Host or underlying framework.
class AllocaSubBufCommand
The AllocaSubBuf command enqueues creation of sub-buffer of memory object.
class MapMemObject
The map command enqueues mapping of device memory onto host memory.
class UnMapMemObject
The unmap command removes mapping of host memory onto device memory.
class MemCpyCommand
The mem copy command enqueues memory copy between two instances of memory object.
class MemCpyCommandHost
The mem copy host command enqueues memory copy between two instances of memory object.
class ExecCGCommand
The exec CG command enqueues execution of kernel or explicit memory operation.
class UpdateHostRequirementCommand
class KernelFusionCommand
The KernelFusionCommand is placed in the execution graph together with the individual kernels of the fusion list to control kernel fusion.
class UpdateCommandBufferCommand
class LeavesCollection
A wrapper for CircularBuffer class along with collection for host accessor's EmptyCommands.
struct MemObjRecord
Memory Object Record.
class Scheduler
DPC++ graph scheduler class.
class spec_constant_impl
class stream_impl
class SYCLMemObjI
class SYCLMemObjT
class ThreadPool
class XPTIRegistry
struct ESIMDDeviceInterface
Typedefs
template<typename T >
using IsPropertyListT = typename std::is_base_of< PropertyListBase, T >
template<typename T >
using IsRunTimePropertyListT = typename std::is_same< ext::oneapi::accessor_property_list<>, T >
using AccessorImplPtr = std::shared_ptr< AccessorImplHost >
using LocalAccessorImplPtr = std::shared_ptr< LocalAccessorImplHost >
using UnsampledImageAccessorImplPtr = std::shared_ptr< UnsampledImageAccessorImplHost >
using SampledImageAccessorImplPtr = std::shared_ptr< SampledImageAccessorImplHost >
using memory_order = sycl::memory_order
using memory_scope = sycl::memory_scope
template<memory_order Order>
using IsValidDefaultOrder = std::bool_constant< Order==memory_order::relaxed||Order==memory_order::acq_rel||Order==memory_order::seq_cst >
template<size_t Size, typename T8 , typename T16 , typename T32 , typename T64 >
using select_scalar_by_size_t = std::conditional_t< Size==1, T8, std::conditional_t< Size==2, T16, std::conditional_t< Size==4, T32, std::conditional_t< Size==8, T64, void > >> >
template<typename T >
using same_size_signed_int_t = typename same_size_signed_int< T >::type
template<typename T >
using same_size_unsigned_int_t = typename same_size_unsigned_int< T >::type
template<typename T >
using get_fixed_sized_int_t = typename get_fixed_sized_int< T >::type
template<typename T >
using simplify_if_swizzle_t = typename simplify_if_swizzle< T >::type
template<typename NewElemT , typename T >
using change_elements_t = typename change_elements< NewElemT, T >::type
using EventImplPtr = std::shared_ptr< event_impl >
template<typename DataT >
using EnableIfOutputPointerT = std::enable_if_t< std::is_pointer_v< DataT > >
template<typename DataT >
using EnableIfOutputIteratorT = std::enable_if_t< !std::is_pointer_v< DataT > >
template<typename T >
using is_geninteger = std::bool_constant< is_geninteger_v< T > >
template<typename T >
using is_igeninteger = std::bool_constant< is_igeninteger_v< T > >
template<typename T >
using is_ugeninteger = std::bool_constant< is_ugeninteger_v< T > >
template<typename T >
using make_floating_point_t = make_type_t< T, gtl::scalar_floating_list >
template<typename T >
using make_singed_integer_t = make_type_t< T, gtl::scalar_signed_integer_list >
template<typename T >
using make_unsinged_integer_t = make_type_t< T, gtl::scalar_unsigned_integer_list >
template<typename T , typename T8 , typename T16 , typename T32 , typename T64 >
using select_apply_cl_scalar_t = std::conditional_t< sizeof(T)==1, T8, std::conditional_t< sizeof(T)==2, T16, std::conditional_t< sizeof(T)==4, T32, T64 > >>
template<typename T >
using select_cl_scalar_integral_signed_t = select_apply_cl_scalar_t< T, sycl::opencl::cl_char, sycl::opencl::cl_short, sycl::opencl::cl_int, sycl::opencl::cl_long >
template<typename T >
using select_cl_scalar_integral_unsigned_t = select_apply_cl_scalar_t< T, sycl::opencl::cl_uchar, sycl::opencl::cl_ushort, sycl::opencl::cl_uint, sycl::opencl::cl_ulong >
template<typename T >
using select_cl_scalar_complex_or_T_t = typename select_cl_scalar_complex_or_T< T >::type
template<typename T >
using ConvertToOpenCLType_t = decltype(convertToOpenCLType(std::declval< T >()))
template<typename T >
using IsValidCoordType = typename is_contained< T, boost::mp11::mp_unique< type_list< opencl::cl_int, opencl::cl_float, std::int32_t, float > >>::type
using int64_t = conditional< sizeof(long)==8, long, long long >::type
using PluginPtr = std::shared_ptr< plugin >
template<typename T >
using iterator_category_t = typename std::iterator_traits< T >::iterator_category
template<typename T >
using iterator_value_type_t = typename std::iterator_traits< T >::value_type
template<typename T >
using iterator_pointer_t = typename std::iterator_traits< T >::pointer
template<typename T >
using iterator_to_const_type_t = std::is_const< std::remove_pointer_t< iterator_pointer_t< T > >>
template<typename T >
using output_iterator_requirements = std::void_t< iterator_category_t< T >, decltype(*std::declval< T >()=std::declval< iterator_value_type_t< T > >())>
template<typename DataT >
using sycl_memory_object_allocator = aligned_allocator< DataT >
template<std::size_t I, class T >
using tuple_element_t = typename tuple_element< I, T >::type
template<class... T>
using type_list = boost::mp11::mp_list< T... >
using empty_type_list = type_list<>
template<typename T >
using is_empty_type_list = std::is_same< T, empty_type_list >
template<typename T , typename TypeList >
using is_contained = boost::mp11::mp_set_contains< TypeList, std::remove_cv_t< T > >
template<class... L>
using tl_append = boost::mp11::mp_append< L... >
template<typename T >
using tail_t = typename T::tail
template<access::address_space... Values>
using address_space_list = value_list< access::address_space, Values... >
template<access::address_space AddressSpace, typename ValueList >
using is_one_of_spaces = is_contained_value< access::address_space, AddressSpace, ValueList >
template<typename TypeList , template< typename, typename > class Comp, typename T >
using find_type_t = typename find_type< TypeList, Comp, T >::type
template<typename TypeList , typename T >
using find_same_size_type_t = find_type_t< TypeList, is_type_size_equal, T >
template<typename TypeList , typename T >
using find_twice_as_large_type_t = find_type_t< TypeList, is_type_size_double_of, T >
using uuid_type = std::array< unsigned char, 16 >
template<typename T , typename R >
using copy_cv_qualifiers_t = typename copy_cv_qualifiers< T, R >::type
template<int V>
using int_constant = std::integral_constant< int, V >
template<typename T >
using vector_element_impl_t = typename vector_element_impl< T >::type
template<class T >
using vector_element_t = typename vector_element< T >::type
template<class T >
using marray_element_t = typename T::value_type
template<typename T >
using get_elem_type_t = typename get_elem_type< T >::type
template<typename T , typename B >
using change_base_type_t = typename change_base_type< T, B >::type
template<typename T >
using make_signed_t = typename make_signed< T >::type
template<typename T >
using make_unsigned_t = typename make_unsigned< T >::type
template<typename T >
using remove_pointer_t = typename remove_pointer< T >::type
template<typename T , typename TL >
using make_type_t = typename make_type_impl< T, TL >::type
template<typename T >
using make_larger_t = typename make_larger< T >::type
template<access::address_space AS, class DataT >
using const_if_const_AS = DataT
using SerializedObj = std::vector< unsigned char >
template<typename T >
using ABINeutralT_t = typename ABINeutralT< T >::type
template<typename T , typename R >
using is_sint_to_sint = std::bool_constant< is_sigeninteger_v< T > &&is_sigeninteger_v< R > >
template<typename T , typename R >
using is_uint_to_uint = std::bool_constant< is_sugeninteger_v< T > &&is_sugeninteger_v< R > >
template<typename T , typename R >
using is_sint_to_from_uint = std::bool_constant<(detail::is_sigeninteger_v< T > &&detail::is_sugeninteger_v< R >)||(detail::is_sugeninteger_v< T > &&detail::is_sigeninteger_v< R >)>
template<typename T , typename R >
using is_sint_to_float = std::bool_constant< std::is_integral_v< T > &&!std::is_unsigned_v< T > &&detail::is_floating_point< R >::value >
template<typename T , typename R >
using is_uint_to_float = std::bool_constant< std::is_unsigned_v< T > &&detail::is_floating_point< R >::value >
template<typename T , typename R >
using is_int_to_float = std::bool_constant< std::is_integral_v< T > &&detail::is_floating_point< R >::value >
template<typename T , typename R >
using is_float_to_uint = std::bool_constant< detail::is_floating_point< T >::value &&std::is_unsigned_v< R > >
template<typename T , typename R >
using is_float_to_sint = std::bool_constant< detail::is_floating_point< T >::value &&std::is_integral_v< R > &&!std::is_unsigned_v< R > >
template<typename T , typename R >
using is_float_to_float = std::bool_constant< detail::is_floating_point< T >::value &&detail::is_floating_point< R >::value >
using DSelectorInvocableType = std::function< int(const sycl::device &)>
template<typename DeviceSelector >
using EnableIfSYCL2020DeviceSelectorInvocable = std::enable_if_t< std::is_invocable_r_v< int, DeviceSelector &, const device & > &&!std::is_base_of_v< ext::oneapi::filter_selector, DeviceSelector > &&!std::is_base_of_v< device_selector, DeviceSelector > >
using UseToUseStringPair = std::pair< ext::oneapi::experimental::matrix::use, const char * >
template<typename T >
using native_op_list = type_list< sycl::plus< T >, sycl::bit_or< T >, sycl::bit_xor< T >, sycl::bit_and< T >, sycl::maximum< T >, sycl::minimum< T >, sycl::multiplies< T >, sycl::logical_or< T >, sycl::logical_and< T > >
template<typename T , typename BinaryOperation >
using is_plus = std::integral_constant< bool, std::is_same_v< BinaryOperation, sycl::plus< std::remove_const_t< T > >>||std::is_same_v< BinaryOperation, sycl::plus< std::add_const_t< T > >>||std::is_same_v< BinaryOperation, sycl::plus< void > >>
template<typename T , typename BinaryOperation >
using is_multiplies = std::integral_constant< bool, std::is_same_v< BinaryOperation, sycl::multiplies< std::remove_const_t< T > >>||std::is_same_v< BinaryOperation, sycl::multiplies< std::add_const_t< T > >>||std::is_same_v< BinaryOperation, sycl::multiplies< void > >>
template<typename T >
using is_arithmetic_or_complex = std::integral_constant< bool, sycl::detail::is_complex< T >::value||sycl::detail::is_arithmetic< T >::value >
template<typename T , typename BinaryOperation >
using is_plus_or_multiplies_if_complex = std::integral_constant< bool,(is_complex< T >::value ?(is_plus< T, BinaryOperation >::value||is_multiplies< T, BinaryOperation >::value) :std::true_type::value)>
template<typename F , typename SuggestedArgType >
using lambda_arg_type = decltype(argument_helper< F, SuggestedArgType >(0))
template<typename T >
using is_validImageDataT = typename detail::is_contained< T, type_list< vec< opencl::cl_int, 4 >, vec< opencl::cl_uint, 4 >, vec< opencl::cl_float, 4 >, vec< opencl::cl_half, 4 > >>::type
template<typename DataT >
using EnableIfImgAccDataT = typename std::enable_if_t< is_validImageDataT< DataT >::value, DataT >
using DeviceImageImplPtr = std::shared_ptr< device_image_impl >
using KernelBundleImplPtr = std::shared_ptr< detail::kernel_bundle_impl >
using DevImgSelectorImpl = std::function< bool(const detail::DeviceImageImplPtr &DevImgImpl)>
template<typename T , class BinaryOperation >
using IsPlus = std::bool_constant< std::is_same_v< BinaryOperation, sycl::plus< T > >||std::is_same_v< BinaryOperation, sycl::plus< void > >>
template<typename T , class BinaryOperation >
using IsMultiplies = std::bool_constant< std::is_same_v< BinaryOperation, sycl::multiplies< T > >||std::is_same_v< BinaryOperation, sycl::multiplies< void > >>
template<typename T , class BinaryOperation >
using IsMinimum = std::bool_constant< std::is_same_v< BinaryOperation, sycl::minimum< T > >||std::is_same_v< BinaryOperation, sycl::minimum< void > >>
template<typename T , class BinaryOperation >
using IsMaximum = std::bool_constant< std::is_same_v< BinaryOperation, sycl::maximum< T > >||std::is_same_v< BinaryOperation, sycl::maximum< void > >>
template<typename T , class BinaryOperation >
using IsBitAND = std::bool_constant< std::is_same_v< BinaryOperation, sycl::bit_and< T > >||std::is_same_v< BinaryOperation, sycl::bit_and< void > >>
template<typename T , class BinaryOperation >
using IsBitOR = std::bool_constant< std::is_same_v< BinaryOperation, sycl::bit_or< T > >||std::is_same_v< BinaryOperation, sycl::bit_or< void > >>
template<typename T , class BinaryOperation >
using IsBitXOR = std::bool_constant< std::is_same_v< BinaryOperation, sycl::bit_xor< T > >||std::is_same_v< BinaryOperation, sycl::bit_xor< void > >>
template<typename T , class BinaryOperation >
using IsLogicalAND = std::bool_constant< std::is_same_v< BinaryOperation, std::logical_and< T > >||std::is_same_v< BinaryOperation, std::logical_and< void > >||std::is_same_v< BinaryOperation, sycl::logical_and< T > >||std::is_same_v< BinaryOperation, sycl::logical_and< void > >>
template<typename T , class BinaryOperation >
using IsLogicalOR = std::bool_constant< std::is_same_v< BinaryOperation, std::logical_or< T > >||std::is_same_v< BinaryOperation, std::logical_or< void > >||std::is_same_v< BinaryOperation, sycl::logical_or< T > >||std::is_same_v< BinaryOperation, sycl::logical_or< void > >>
template<typename T , class BinaryOperation >
using IsZeroIdentityOp = std::bool_constant<((is_genbool_v< T >||is_geninteger_v< T >)&&(IsPlus< T, BinaryOperation >::value||IsBitOR< T, BinaryOperation >::value||IsBitXOR< T, BinaryOperation >::value))||(is_genfloat_v< T > &&IsPlus< T, BinaryOperation >::value)||(isComplex< T >::value &&IsPlus< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsOneIdentityOp = std::bool_constant<(is_genbool_v< T >||is_geninteger_v< T >||is_genfloat_v< T >)&&IsMultiplies< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsOnesIdentityOp = std::bool_constant<(is_genbool_v< T >||is_geninteger_v< T >)&&IsBitAND< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsMinimumIdentityOp = std::bool_constant<(is_genbool_v< T >||is_geninteger_v< T >||is_genfloat_v< T >)&&IsMinimum< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsMaximumIdentityOp = std::bool_constant<(is_genbool_v< T >||is_geninteger_v< T >||is_genfloat_v< T >)&&IsMaximum< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsFalseIdentityOp = std::bool_constant< IsLogicalOR< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsTrueIdentityOp = std::bool_constant< IsLogicalAND< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsKnownIdentityOp = std::bool_constant< IsZeroIdentityOp< T, BinaryOperation >::value||IsOneIdentityOp< T, BinaryOperation >::value||IsOnesIdentityOp< T, BinaryOperation >::value||IsMinimumIdentityOp< T, BinaryOperation >::value||IsMaximumIdentityOp< T, BinaryOperation >::value||IsFalseIdentityOp< T, BinaryOperation >::value||IsTrueIdentityOp< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsReduOptForFastAtomicFetch = std::bool_constant<((is_sgenfloat_v< T > &&sizeof(T)==4)||is_sgeninteger_v< T >)&&IsValidAtomicType< T >::value &&(IsPlus< T, BinaryOperation >::value||IsMinimum< T, BinaryOperation >::value||IsMaximum< T, BinaryOperation >::value||IsBitOR< T, BinaryOperation >::value||IsBitXOR< T, BinaryOperation >::value||IsBitAND< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsReduOptForAtomic64Op = std::bool_constant<(IsPlus< T, BinaryOperation >::value||IsMinimum< T, BinaryOperation >::value||IsMaximum< T, BinaryOperation >::value) &&is_sgenfloat_v< T > &&sizeof(T)==8 >
template<typename T , class BinaryOperation >
using IsReduOptForFastReduce = std::bool_constant<((is_sgeninteger_v< T > &&(sizeof(T)==4||sizeof(T)==8))||is_sgenfloat_v< T >)&&(IsPlus< T, BinaryOperation >::value||IsMinimum< T, BinaryOperation >::value||IsMaximum< T, BinaryOperation >::value)>
template<typename... Ts>
using ReduTupleT = sycl::detail::tuple< Ts... >
template<class KernelName >
using __sycl_init_mem_for = std::conditional_t< std::is_same_v< KernelName, auto_name >, auto_name, reduction::InitMemKrn< KernelName > >
A helper to pass undefined (sycl::detail::auto_name) names unmodified.
template<template< typename, reduction::strategy, typename... > class MainOrAux, class KernelName , reduction::strategy Strategy, class... Ts>
using __sycl_reduction_kernel = std::conditional_t< std::is_same_v< KernelName, auto_name >, auto_name, MainOrAux< KernelName, Strategy, Ts... > >
A helper to pass undefined (sycl::detail::auto_name) names unmodified.
using FmtFlags = unsigned int
template<class F , class T = void>
using EnableIfFP = typename std::enable_if_t< detail::check_type_in_v< F, float, double, half, ext::oneapi::bfloat16 >, T >
using GlobalBufAccessorT = accessor< char, 1, sycl::access::mode::read_write, sycl::access::target::device >
using GlobalBufPtrType = typename detail::DecoratedType< char, GlobalBufAS >::type *
using GlobalOffsetAccessorT = accessor< unsigned, 1, sycl::access::mode::atomic, sycl::access::target::device >
using GlobalOffsetPtrType = typename detail::DecoratedType< unsigned, GlobalBufAS >::type *
template<typename T >
using EnableIfSwizzleVec = typename std::enable_if_t< IsSwizzleOp< T >::value, typename IsSwizzleOp< T >::Type >
template<typename _IN , typename T8 , typename T16 , typename T32 , typename T64 >
using select_apply_cl_t = std::conditional_t< sizeof(_IN)==1, T8, std::conditional_t< sizeof(_IN)==2, T16, std::conditional_t< sizeof(_IN)==4, T32, T64 > >>
template<typename DataT >
using rel_t = typename std::conditional_t< sizeof(DataT)==sizeof(opencl::cl_char), opencl::cl_char, typename std::conditional_t< sizeof(DataT)==sizeof(opencl::cl_short), opencl::cl_short, typename std::conditional_t< sizeof(DataT)==sizeof(opencl::cl_int), opencl::cl_int, typename std::conditional_t< sizeof(DataT)==sizeof(opencl::cl_long), opencl::cl_long, bool > >> >
using Requirement = AccessorImplHost
using DeviceDescT = std::map< std::string, std::string >
using AllowListParsedT = std::vector< DeviceDescT >
using PlatformImplPtr = std::shared_ptr< detail::platform_impl >
using oneapi_exp_arch = sycl::ext::oneapi::experimental::architecture
using ContextImplPtr = std::shared_ptr< sycl::detail::context_impl >
using QueueImplPtr = std::shared_ptr< sycl::detail::queue_impl >
using LockGuard = std::lock_guard< SpinLock >
using image_allocator = aligned_allocator< byte >
using KernelArgMask = std::vector< bool >
using ProgramImplPtr = std::shared_ptr< program_impl >
using DeviceImplPtr = std::shared_ptr< device_impl >
using StreamImplPtr = std::shared_ptr< detail::stream_impl >
using QueueIdT = std::hash< std::shared_ptr< detail::queue_impl > >::result_type
using CommandPtr = std::unique_ptr< Command >
using FusionList = std::unique_ptr< KernelFusionCommand >
using FusionMap = std::unordered_map< QueueIdT, FusionList >
using SpecConstRegistryT = std::map< std::string, spec_constant_impl >
Enumerations
enum class backend_errc : unsigned int
enum class kernel_param_kind_t {
kind_accessor = 0 , kind_std_layout = 1 , kind_sampler = 2 , kind_pointer = 3 ,
kind_specialization_constants_buffer = 4 , kind_stream = 5 , kind_invalid = 0xf
}
enum class register_alloc_mode_enum : uint32_t { automatic = 0 , large = 2 }
enum class PiApiKind { _PI_API }
enum DataLessPropKind {
BufferUseHostPtr = 0 , ImageUseHostPtr = 1 , QueueEnableProfiling = 2 , InOrder = 3 ,
NoInit = 4 , BufferUsePinnedHostMemory = 5 , UsePrimaryContext = 6 , InitializeToIdentity = 7 ,
UseDefaultStream = 8 , DiscardEvents = 9 , DeviceReadOnly = 10 , FusionPromotePrivate = 11 ,
FusionPromoteLocal = 12 , FusionNoBarrier = 13 , FusionEnable = 14 , FusionForce = 15 ,
QueuePriorityNormal = 16 , QueuePriorityLow = 17 , QueuePriorityHigh = 18 , GraphNoCycleCheck = 19 ,
QueueSubmissionBatched = 20 , QueueSubmissionImmediate = 21 , GraphAssumeDataOutlivesBuffer = 22 , GraphAssumeBufferOutlivesGraph = 23 ,
GraphDependOnAllLeaves = 24 , GraphUpdatable = 25 , GraphEnableProfiling = 26 , LastKnownDataLessPropKind = 26 ,
DataLessPropKindSize = 32
}
enum PropWithDataKind {
BufferUseMutex = 0 , BufferContextBound = 1 , ImageUseMutex = 2 , ImageContextBound = 3 ,
BufferMemChannel = 4 , AccPropBufferLocation = 5 , QueueComputeIndex = 6 , GraphNodeDependencies = 7 ,
PropWithDataKindSize = 8
}
enum class WorkSizeGuarantees { None , Equal , LessOrEqual }
enum ConfigID { START = 0 , END }
enum class HandlerSubmissionState : std::uint8_t { NO_STATE = 0 , EXPLICIT_KERNEL_BUNDLE_STATE , SPEC_CONST_SET_STATE }
enum class program_state { none = 0 , compiled = 1 , linked = 2 }
enum class DeviceLibExt : std::uint32_t {
cl_intel_devicelib_assert , cl_intel_devicelib_math , cl_intel_devicelib_math_fp64 , cl_intel_devicelib_complex ,
cl_intel_devicelib_complex_fp64 , cl_intel_devicelib_cstring , cl_intel_devicelib_imf , cl_intel_devicelib_imf_fp64 ,
cl_intel_devicelib_imf_bf16 , cl_intel_devicelib_bfloat16
}
enum class CUDAContextT : char { primary , custom }
Possible CUDA context types supported by PI CUDA backend TODO: Implement this as a property once there is an extension document.
enum QueueOrder { Ordered , OOO }
enum BlockingT { NON_BLOCKING = 0 , BLOCKING }
Functions
constexpr bool isTargetHostAccess (access::target T)
constexpr bool modeNeedsOldData (access::mode m)
constexpr bool modeWritesNewData (access::mode m)
template<typename ToT , typename FromT >
ToT cast_AS (FromT from)
void constructorNotification (void *BufferObj, void *AccessorObj, access::target Target, access::mode Mode, const code_location &CodeLoc)
template<typename BufferT >
sycl::range< 1 > GetZeroDimAccessRange (BufferT Buffer)
device getDeviceFromHandler (handler &CommandGroupHandlerRef)
template<typename DataT >
constexpr access::mode accessModeFromConstness ()
template<typename MayBeTag1 , typename MayBeTag2 >
constexpr access::mode deduceAccessMode ()
template<typename MayBeTag1 , typename MayBeTag2 >
constexpr access::target deduceAccessTarget (access::target defaultTarget)
void addHostAccessorAndWait (AccessorImplHost *Req)
void unsampledImageConstructorNotification (void *ImageObj, void *AccessorObj, const std::optional< image_target > &Target, access::mode Mode, const void *Type, uint32_t ElemSize, const code_location &CodeLoc)
void sampledImageConstructorNotification (void *ImageObj, void *AccessorObj, const std::optional< image_target > &Target, const void *Type, uint32_t ElemSize, const code_location &CodeLoc)
void addHostUnsampledImageAccessorAndWait (UnsampledImageAccessorImplHost *Req)
void addHostSampledImageAccessorAndWait (SampledImageAccessorImplHost *Req)
std::memory_order getStdMemoryOrder (__spv::MemorySemanticsMask::Flag)
constexpr memory_order getLoadOrder (memory_order order)
backend convertBackend (pi_platform_backend PiBackend)
platform make_platform (pi_native_handle NativeHandle, backend Backend)
device make_device (pi_native_handle NativeHandle, backend Backend)
context make_context (pi_native_handle NativeHandle, const async_handler &Handler, backend Backend)
queue make_queue (pi_native_handle NativeHandle, int32_t nativeHandleDesc, const context &TargetContext, const device *TargetDevice, bool KeepOwnership, const property_list &PropList, const async_handler &Handler, backend Backend)
event make_event (pi_native_handle NativeHandle, const context &TargetContext, backend Backend)
event make_event (pi_native_handle NativeHandle, const context &TargetContext, bool KeepOwnership, backend Backend)
kernel make_kernel (pi_native_handle NativeHandle, const context &TargetContext, backend Backend)
kernel make_kernel (const context &TargetContext, const kernel_bundle< bundle_state::executable > &KernelBundle, pi_native_handle NativeKernelHandle, bool KeepOwnership, backend Backend)
std::shared_ptr< detail::kernel_bundle_impl > make_kernel_bundle (pi_native_handle NativeHandle, const context &TargetContext, bundle_state State, backend Backend)
std::shared_ptr< detail::kernel_bundle_impl > make_kernel_bundle (pi_native_handle NativeHandle, const context &TargetContext, bool KeepOwnership, bundle_state State, backend Backend)
std::string_view get_backend_name_no_vendor (backend Backend)
template<typename T , int Dimensions, typename AllocatorT >
buffer< T, Dimensions, AllocatorT, void > make_buffer_helper (pi_native_handle Handle, const context &Ctx, event Evt={}, bool OwnNativeHandle=true)
template<backend BackendName, typename DataT , int Dimensions, typename Allocator >
auto get_native_buffer (const buffer< DataT, Dimensions, Allocator, void > &Obj) -> backend_return_t< BackendName, buffer< DataT, Dimensions, Allocator, void >>
template<size_t N, size_t... Ns>
constexpr bool CheckSizeIn ()
template<typename T , typename... Ts>
constexpr bool CheckAllSameOpType ()
template<class T , size_t N>
vec< T, 2 > to_vec2 (marray< T, N > X, size_t Start)
template<class T , size_t N>
vec< T, N > to_vec (marray< T, N > X)
template<class T , int N>
marray< T, N > to_marray (vec< T, N > X)
template<typename FuncTy , typename... Ts>
auto builtin_marray_impl (FuncTy F, const Ts &...x)
template<typename FuncTy , typename... Ts>
auto builtin_default_host_impl (FuncTy F, const Ts &...x)
template<typename FuncTy , typename... Ts>
auto builtin_delegate_to_scalar (FuncTy F, const Ts &...x)
template<typename F , typename... Args>
static constexpr bool check_kernel_lambda_takes_args ()
template<typename KernelType , typename LambdaArgType , typename std::enable_if_t< std::is_same_v< LambdaArgType, void >> * = nullptr>
constexpr bool isKernelLambdaCallableWithKernelHandlerImpl ()
template<typename KernelType >
std::enable_if_t< KernelLambdaHasKernelHandlerArgT< KernelType >::value > runKernelWithoutArg (KernelType KernelName)
template<typename KernelType >
std::enable_if_t<!KernelLambdaHasKernelHandlerArgT< KernelType >::value > runKernelWithoutArg (KernelType KernelName)
template<typename ArgType , typename KernelType >
std::enable_if_t< KernelLambdaHasKernelHandlerArgT< KernelType, ArgType >::value > runKernelWithArg (KernelType KernelName, ArgType Arg)
template<typename ArgType , typename KernelType >
std::enable_if_t< !KernelLambdaHasKernelHandlerArgT< KernelType, ArgType >::value > runKernelWithArg (KernelType KernelName, ArgType Arg)
const char * stringifyErrorCode (pi_int32 error)
std::string codeToString (pi_int32 code)
constexpr size_t getNextPowerOfTwoHelper (size_t Var, size_t Offset)
constexpr size_t getNextPowerOfTwo (size_t Var)
template<int Dims, template< int > class T, template< int > class U>
size_t getLinearIndex (const T< Dims > &Index, const U< Dims > &Range)
template<int NewDim, int DefaultValue, template< int > class T, int OldDim>
static T< NewDim > convertToArrayOfN (T< OldDim > OldObj)
template<typename T , std::size_t... Is1, std::size_t... Is2>
constexpr std::array< T, sizeof...(Is1)+sizeof...(Is2)> ConcatArrays (const std::array< T, sizeof...(Is1)> &A1, const std::array< T, sizeof...(Is2)> &A2, std::index_sequence< Is1... >, std::index_sequence< Is2... >)
template<typename T , std::size_t N1, std::size_t N2>
constexpr std::array< T, N1+N2 > ConcatArrays (const std::array< T, N1 > &A1, const std::array< T, N2 > &A2)
template<typename T , size_t... Is>
static constexpr std::array< T, sizeof...(Is)> RepeatValueHelper (const T &Arg, std::index_sequence< Is... >)
template<size_t N, typename T >
static constexpr std::array< T, N > RepeatValue (const T &Arg)
template<typename T >
std::ostream & operator<< (std::ostream &os, std::optional< T > const &opt)
std::ostream & operator<< (std::ostream &Out, const ods_target &Target)
std::vector< ods_target > Parse_ONEAPI_DEVICE_SELECTOR (const std::string &envStr)
template<typename T >
auto convertToOpenCLType (T &&x)
template<typename To , typename From >
auto convertFromOpenCLTypeFor (From &&x)
template<typename T >
constexpr T msbMask (T)
template<typename T >
constexpr bool msbIsSet (const T x)
template<typename T >
static constexpr T max_v ()
template<typename T >
static constexpr T min_v ()
void associateWithHandler (handler &, AccessorBaseHost *, access::target)
void associateWithHandler (handler &, UnsampledImageAccessorBaseHost *, image_target)
void associateWithHandler (handler &, SampledImageAccessorBaseHost *, image_target)
std::vector< sycl::detail::pi::PiEvent > getOrWaitEvents (std::vector< sycl::event > DepEvents, std::shared_ptr< sycl::detail::context_impl > Context)
void waitEvents (std::vector< sycl::event > DepEvents)
void markBufferAsInternal (const std::shared_ptr< buffer_impl > &BufImpl)
template<typename T >
T * declptr ()
template<typename T >
T get_or_store (const T *obj)
constexpr __spv::MemorySemanticsMask::Flag getSPIRVMemorySemanticsMask (memory_order)
constexpr uint32_t getSPIRVMemorySemanticsMask (const access::fence_space AccessSpace, const __spv::MemorySemanticsMask LocalScopeMask=__spv::MemorySemanticsMask::WorkgroupMemory)
template<size_t... Inds, class F >
void loop_impl (std::integer_sequence< size_t, Inds... >, F &&f)
template<size_t count, class F >
void loop (F &&f)
template<typename T >
std::enable_if_t< IsValidCoordType< T >::value, T > UnnormalizeCoordinates (const T &Coords, const range< 3 > &Range)
template<typename T >
std::enable_if_t< IsValidCoordType< T >::value, vec< T, 2 > > UnnormalizeCoordinates (const vec< T, 2 > &Coords, const range< 3 > &Range)
template<typename T >
std::enable_if_t< IsValidCoordType< T >::value, vec< T, 4 > > UnnormalizeCoordinates (const vec< T, 4 > &Coords, const range< 3 > &Range)
template<typename T >
std::enable_if_t< IsValidCoordType< T >::value, float4 > convertToFloat4 (T Coords)
template<typename T >
std::enable_if_t< IsValidCoordType< T >::value, float4 > convertToFloat4 (vec< T, 2 > Coords)
template<typename T >
std::enable_if_t< IsValidCoordType< T >::value, float4 > convertToFloat4 (vec< T, 4 > Coords)
template<typename T >
std::enable_if_t< std::is_integral_v< T >, size_t > getImageOffset (const T &Coords, const id< 3 >, const uint8_t ElementSize)
template<typename T >
std::enable_if_t< std::is_integral_v< T >, size_t > getImageOffset (const vec< T, 2 > &Coords, const id< 3 > ImgPitch, const uint8_t ElementSize)
template<typename T >
std::enable_if_t< std::is_integral_v< T >, size_t > getImageOffset (const vec< T, 4 > &Coords, const id< 3 > ImgPitch, const uint8_t ElementSize)
int4 getPixelCoordNearestFiltMode (float4, const addressing_mode, const range< 3 >)
int8 getPixelCoordLinearFiltMode (float4, const addressing_mode, const range< 3 >, float4 &)
bool isOutOfRange (const int4 PixelCoord, const addressing_mode SmplAddrMode, const range< 3 > ImgRange)
float4 getBorderColor (const image_channel_order ImgChannelOrder)
template<typename T >
vec< T, 4 > readPixel (T *Ptr, const image_channel_order ChannelOrder, const image_channel_type ChannelType)
template<typename T >
void writePixel (const vec< T, 4 > Pixel, T *Ptr, const image_channel_order ChannelOrder, const image_channel_type ChannelType)
template<typename ChannelType >
void convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, uint4 &RetData)
template<typename ChannelType >
void convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, int4 &RetData)
template<typename ChannelType >
void convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, float4 &RetData)
template<typename ChannelType >
void convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, half4 &RetData)
template<typename ChannelType >
vec< ChannelType, 4 > convertWriteData (const uint4 WriteData, const image_channel_type ImageChannelType)
template<typename ChannelType >
vec< ChannelType, 4 > convertWriteData (const int4 WriteData, const image_channel_type ImageChannelType)
template<typename ChannelType >
vec< ChannelType, 4 > processFloatDataToPixel (float4 WriteData, float MulFactor)
template<typename ChannelType >
vec< ChannelType, 4 > convertWriteData (const float4 WriteData, const image_channel_type ImageChannelType)
template<typename ChannelType >
vec< ChannelType, 4 > convertWriteData (const half4 WriteData, const image_channel_type ImageChannelType)
template<typename CoordT , typename WriteDataT >
void imageWriteHostImpl (const CoordT &Coords, const WriteDataT &Color, id< 3 > ImgPitch, uint8_t ElementSize, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void *BasePtr)
template<typename DataT >
DataT ReadPixelData (const int4 PixelCoord, const id< 3 > ImgPitch, const image_channel_type ImageChannelType, const image_channel_order ImageChannelOrder, void *BasePtr, const uint8_t ElementSize)
template<typename DataT >
DataT getColor (const int4 PixelCoord, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, const id< 3 > ImgPitch, const image_channel_type ImgChannelType, const image_channel_order ImgChannelOrder, void *BasePtr, const uint8_t ElementSize)
template<typename DataT >
DataT ReadPixelDataLinearFiltMode (const int8 CoordValues, const float4 abc, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, id< 3 > ImgPitch, const image_channel_type ImgChannelType, const image_channel_order ImgChannelOrder, void *BasePtr, const uint8_t ElementSize)
template<typename CoordT , typename DataT >
DataT imageReadSamplerHostImpl (const CoordT &Coords, coordinate_normalization_mode SmplNormMode, addressing_mode SmplAddrMode, filtering_mode SmplFiltMode, range< 3 > ImgRange, id< 3 > ImgPitch, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void *BasePtr, uint8_t ElementSize)
template<typename CoordT , typename DataT >
DataT imageReadSamplerHostImpl (const CoordT &Coords, const sampler &Smpl, range< 3 > ImgRange, id< 3 > ImgPitch, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void *BasePtr, uint8_t ElementSize)
template<typename CoordT , typename DataT >
DataT imageReadSamplerHostImpl (const CoordT &Coords, const image_sampler &Smpl, range< 3 > ImgRange, id< 3 > ImgPitch, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void *BasePtr, uint8_t ElementSize)
template<class Obj >
decltype(Obj::impl) getSyclObjImpl (const Obj &SyclObject)
template<class T >
std::add_pointer_t< typename decltype(T::impl)::element_type > getRawSyclObjImpl (const T &SyclObject)
template<class T >
T createSyclObjFromImpl (decltype(T::impl) ImplObj)
template<auto & SpecName>
const char * get_spec_constant_symbolic_ID_impl ()
template<auto & SpecName>
const char * get_spec_constant_symbolic_ID ()
template<register_alloc_mode_enum Mode>
constexpr register_alloc_mode_key::value_t< Mode > register_alloc_mode __SYCL_DEPRECATED ("register_alloc_mode is deprecated, " "use sycl::ext::intel::experimental::grf_size or " "sycl::ext::intel::experimental::grf_size_automatic")
void memcpy (void *Dst, const void *Src, size_t Size)
template<sycl::backend BE>
void * getPluginOpaqueData (void *opaquedata_arg)
template<typename KernelName , reduction::strategy Strategy = reduction::strategy::auto_select, int Dims, typename PropertiesT , typename... RestT>
void reduction_parallel_for (handler &CGH, range< Dims > NDRange, PropertiesT Properties, RestT... Rest)
template<typename KernelName , reduction::strategy Strategy = reduction::strategy::auto_select, int Dims, typename PropertiesT , typename... RestT>
void reduction_parallel_for (handler &CGH, nd_range< Dims > NDRange, PropertiesT Properties, RestT... Rest)
template<typename T , typename... Ts, std::size_t... Is>
std::tuple< Ts... > get_tuple_tail_impl (const std::tuple< T, Ts... > &Tuple, const std::index_sequence< Is... > &)
template<typename T , typename... Ts>
std::tuple< Ts... > get_tuple_tail (const std::tuple< T, Ts... > &Tuple)
template<typename... Ts>
constexpr tuple< Ts... > make_tuple (Ts... Args)
template<typename... Ts>
auto tie (Ts &...Args)
template<typename T , typename... Ts>
constexpr bool CheckTypeIn ()
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>>
To SConvert (From Value)
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>>
To UConvert (From Value)
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>>
To ConvertSToF (From Value)
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>>
To ConvertUToF (From Value)
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>, sycl::rounding_mode RM>
To FConvert (From Value)
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>, sycl::rounding_mode roundingMode>
To ConvertFToS (From Value)
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>, sycl::rounding_mode roundingMode>
To ConvertFToU (From Value)
template<typename FromT , typename ToT , sycl::rounding_mode RoundingMode, int VecSize, typename NativeFromT , typename NativeToT >
NativeToT convertImpl (NativeFromT Value)
Entry point helper for all kinds of converts between scalars and vectors, it dispatches to a right function depending on source and destination types.
auto getDeviceComparisonLambda ()
template<typename LastT >
void fill_aspect_vector (std::vector< aspect > &V, LastT L)
template<typename FirstT , typename... OtherTs>
void fill_aspect_vector (std::vector< aspect > &V, FirstT F, OtherTs... O)
device select_device (const DSelectorInvocableType &DeviceSelectorInvocable)
device select_device (const DSelectorInvocableType &DeviceSelectorInvocable, const context &SyclContext)
void defaultAsyncHandler (exception_list Exceptions)
constexpr static std::optional< ext::oneapi::experimental::architecture > get_current_architecture_aot ()
constexpr static bool is_aot_for_architecture (ext::oneapi::experimental::architecture arch)
template<ext::oneapi::experimental::architecture... Archs>
constexpr static bool allowable_aot_mode ()
template<ext::oneapi::experimental::architecture... Archs>
constexpr static bool device_architecture_is ()
static constexpr std::optional< ext::oneapi::experimental::architecture > get_category_min_architecture (ext::oneapi::experimental::arch_category Category)
static constexpr std::optional< ext::oneapi::experimental::architecture > get_category_max_architecture (ext::oneapi::experimental::arch_category Category)
template<ext::oneapi::experimental::arch_category Category>
constexpr static bool device_architecture_is_in_category_aot ()
template<ext::oneapi::experimental::arch_category... Categories>
constexpr static bool device_architecture_is_in_categories ()
constexpr static std::optional< ext::oneapi::experimental::arch_category > get_device_architecture_category (ext::oneapi::experimental::architecture arch)
template<ext::oneapi::experimental::architecture Arch, typename Compare >
constexpr static bool device_architecture_comparison_aot (Compare comp)
sycl::vec< unsigned, 4 > ExtractMask (ext::oneapi::sub_group_mask Mask)
template<typename NonUniformGroup >
ext::oneapi::sub_group_mask GetMask (NonUniformGroup Group)
template<typename NonUniformGroup >
uint32_t IdToMaskPosition (NonUniformGroup Group, uint32_t Id)
constexpr const char * convertMatrixUseEnumToString (ext::oneapi::experimental::matrix::use Use)
constexpr std::optional< ext::oneapi::experimental::matrix::use > convertMatrixUseStringToEnum (const char *UseString)
__SYCL_ALWAYS_INLINE __spv::MatrixLayout joint_matrix_layout_to_spv (sycl::ext::oneapi::experimental::matrix::layout Layout)
template<typename T >
constexpr const char * convertTypeToMatrixTypeString ()
template<>
constexpr const char * convertTypeToMatrixTypeString< sycl::ext::oneapi::bfloat16 > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< sycl::half > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< sycl::ext::oneapi::experimental::matrix::precision::tf32 > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< float > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< double > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< int8_t > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< int16_t > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< int32_t > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< int64_t > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< uint8_t > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< uint16_t > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< uint32_t > ()
template<>
constexpr const char * convertTypeToMatrixTypeString< uint64_t > ()
template<typename DecorT , typename T , access::address_space Space, access::decorated IsDecorated>
DecorT * getDecorated (multi_ptr< T, Space, IsDecorated > ptr)
void workGroupBarrier ()
template<int Dimensions>
id< Dimensions > linear_id_to_id (range< Dimensions >, size_t linear_id)
template<>
id< 1 > linear_id_to_id (range< 1 >, size_t linear_id)
template<>
id< 2 > linear_id_to_id (range< 2 > r, size_t linear_id)
template<>
id< 3 > linear_id_to_id (range< 3 > r, size_t linear_id)
template<typename Group >
auto get_local_linear_range (Group g)
template<typename Group >
auto get_local_linear_id (Group g)
template<typename T , class BinaryOperation >
constexpr std::enable_if_t<(is_complex< T >::value &&is_plus< T, BinaryOperation >::value), T > identity_for_ga_op ()
template<typename T , class BinaryOperation >
constexpr std::enable_if_t<(is_complex< T >::value &&is_multiplies< T, BinaryOperation >::value), T > identity_for_ga_op ()
template<typename T , class BinaryOperation >
constexpr std::enable_if_t<!is_complex< T >::value, T > identity_for_ga_op ()
template<typename Group , typename Ptr , class Function >
Function for_each (Group g, Ptr first, Ptr last, Function f)
__SYCL_CONSTEXPR_HALF uint16_t float2Half (const float &Val)
__SYCL_CONSTEXPR_HALF float half2Float (const uint16_t &Val)
template<typename T >
T cast_if_host_half (T val)
float cast_if_host_half (half_impl::half val)
template<typename RetType , typename Func , typename Arg >
static Arg member_ptr_helper (RetType(Func::*)(Arg) const)
template<typename RetType , typename Func , typename Arg1 , typename Arg2 >
static Arg1 member_ptr_helper (RetType(Func::*)(Arg1, Arg2) const)
template<typename F , typename SuggestedArgType >
SuggestedArgType argument_helper (...)
bool isDeviceGlobalUsedInKernel (const void *DeviceGlobalPtr)
void * getValueFromDynamicParameter (ext::oneapi::experimental::detail::dynamic_parameter_base &DynamicParamBase)
template<int Dims, typename T >
std::enable_if_t< std::is_same_v< T, range< Dims > >||std::is_same_v< T, id< Dims > > > checkValueRange (const T &V)
template<int Dims>
void checkValueRange (const range< Dims > &R, const id< Dims > &O)
template<int Dims, typename T >
std::enable_if_t< std::is_same_v< T, nd_range< Dims > > > checkValueRange (const T &V)
template<typename T >
static std::enable_if_t< std::is_unsigned_v< T >, bool > multiply_with_overflow_check (T &dst, T x, T y)
template<int Dims>
bool range_size_fits_in_size_t (const range< Dims > &r)
template<int Dimensions>
size_t getOffsetForId (range< Dimensions > Range, id< Dimensions > Id, id< Dimensions > Offset)
id< 1 > getDelinearizedId (const range< 1 > &, size_t Index)
id< 2 > getDelinearizedId (const range< 2 > &Range, size_t Index)
id< 3 > getDelinearizedId (const range< 3 > &Range, size_t Index)
image_channel_type FormatChannelType (image_format Format)
image_channel_order FormatChannelOrder (image_format Format)
kernel_id get_kernel_id_impl (string_view KernelName)
detail::KernelBundleImplPtr get_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, bundle_state State)
const std::vector< device > removeDuplicateDevices (const std::vector< device > &Devs)
detail::KernelBundleImplPtr get_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, const std::vector< kernel_id > &KernelIDs, bundle_state State)
detail::KernelBundleImplPtr get_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, bundle_state State, const DevImgSelectorImpl &Selector)
detail::KernelBundleImplPtr get_empty_interop_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs)
template<bundle_state State>
kernel_bundle< State > get_empty_interop_kernel_bundle (const context &Ctx)
make_kernel may need an empty interop kernel bundle.
bool has_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, bundle_state State)
bool has_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, const std::vector< kernel_id > &kernelIds, bundle_state State)
std::shared_ptr< detail::kernel_bundle_impl > join_impl (const std::vector< detail::KernelBundleImplPtr > &Bundles, bundle_state State)
std::shared_ptr< detail::kernel_bundle_impl > compile_impl (const kernel_bundle< bundle_state::input > &InputBundle, const std::vector< device > &Devs, const property_list &PropList)
std::vector< sycl::device > find_device_intersection (const std::vector< kernel_bundle< bundle_state::object >> &ObjectBundles)
std::shared_ptr< detail::kernel_bundle_impl > link_impl (const std::vector< kernel_bundle< bundle_state::object >> &ObjectBundles, const std::vector< device > &Devs, const property_list &PropList)
std::shared_ptr< detail::kernel_bundle_impl > build_impl (const kernel_bundle< bundle_state::input > &InputBundle, const std::vector< device > &Devs, const property_list &PropList)
std::vector< memory_order > readMemoryOrderBitfield (pi_memory_order_capabilities bits)
std::vector< memory_scope > readMemoryScopeBitfield (pi_memory_scope_capabilities bits)
static constexpr std::memory_order getStdMemoryOrder (sycl::memory_order order)
void enable_ext_oneapi_default_context (bool Val)
Allows to enable/disable "Default Context" extension.
template<typename ParamT >
auto convert_to_abi_neutral (ParamT &&Info)
template<typename ParamT >
auto convert_from_abi_neutral (ParamT &&Info)
std::array< size_t, 3 > rangeToArray (const range< 3 > &r)
std::array< size_t, 3 > rangeToArray (const range< 2 > &r)
std::array< size_t, 3 > rangeToArray (const range< 1 > &r)
template<typename... Ts>
ReduTupleT< Ts... > makeReduTupleT (Ts... Elements)
size_t reduGetMaxWGSize (std::shared_ptr< queue_impl > Queue, size_t LocalMemBytesPerWorkItem)
size_t reduComputeWGSize (size_t NWorkItems, size_t MaxWGSize, size_t &NWorkGroups)
size_t reduGetPreferredWGSize (std::shared_ptr< queue_impl > &Queue, size_t LocalMemBytesPerWorkItem)
template<typename ReducerT >
auto getReducerAccess (ReducerT &Reducer)
template<class BinaryOp , int Dims, size_t Extent, bool ExplicitIdentity, typename RedOutVar , typename... RestTy>
auto make_reduction (RedOutVar RedVar, RestTy &&...Rest)
template<typename KernelName , class Reduction >
void reduSaveFinalResultToUserMem (handler &CGH, Reduction &Redu)
Copies the final reduction result kept in read-write accessor to user's USM memory.
size_t GreatestPowerOfTwo (size_t N)
Computes the greatest power-of-two less than or equal to N.
template<typename FuncTy >
void doTreeReductionHelper (size_t WorkSize, size_t LID, FuncTy Func)
template<WorkSizeGuarantees WSGuarantee, int Dim, typename LocalRedsTy , typename BinOpTy , typename AccessFuncTy >
void doTreeReduction (size_t WorkSize, nd_item< Dim > NDIt, LocalRedsTy &LocalReds, BinOpTy &BOp, AccessFuncTy AccessFunc)
template<typename... LocalAccT, typename... BOPsT, size_t... Is>
void doTreeReductionOnTuple (size_t WorkSize, size_t LID, ReduTupleT< LocalAccT... > &LocalAccs, ReduTupleT< BOPsT... > &BOPs, std::index_sequence< Is... >)
template<bool IsOneWG, typename... Reductions, size_t... Is>
auto createReduOutAccs (size_t NWorkGroups, handler &CGH, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
For the given 'Reductions' types pack and indices enumerating them this function either creates new temporary accessors for partial sums (if IsOneWG is false) or returns user's accessor/USM-pointer if (IsOneWG is true).
template<typename OutAccT , typename LocalAccT , typename BOPT , typename IdentityContainerT >
auto getLastCombine (OutAccT OutAcc, LocalAccT LocalAcc, BOPT BOP, IdentityContainerT IdentityContainer, bool IsInitializeToIdentity)
template<bool IsOneWG, typename... Reductions, typename... OutAccT, typename... LocalAccT, typename... BOPsT, typename... Ts, size_t... Is>
void writeReduSumsToOutAccs (size_t OutAccIndex, ReduTupleT< OutAccT... > OutAccs, ReduTupleT< LocalAccT... > LocalAccs, ReduTupleT< BOPsT... > BOPs, ReduTupleT< Ts... > IdentityVals, std::array< bool, sizeof...(Reductions)> IsInitializeToIdentity, std::index_sequence< Is... >)
constexpr std::index_sequence concat_sequences (std::index_sequence<>)
template<size_t I>
constexpr std::index_sequence< I > concat_sequences (std::index_sequence< I >)
template<size_t... Is, size_t... Js>
constexpr std::index_sequence< Is..., Js... > concat_sequences (std::index_sequence< Is... >, std::index_sequence< Js... >)
template<size_t... Is, size_t... Js, class... Rs>
constexpr auto concat_sequences (std::index_sequence< Is... >, std::index_sequence< Js... >, Rs...)
template<typename... T, typename FunctorT , size_t... Is, std::enable_if_t<(sizeof...(Is) > 0), int > Z = 0>
constexpr auto filterSequenceHelper (FunctorT, std::index_sequence< Is... >)
For each index 'I' from the given indices pack 'Is' this function initially creates a number of short index_sequences, where each of such short index sequences is either empty (if the given Functor returns false for the type T[I]) or 1 element 'I' (otherwise).
template<typename... T, typename FunctorT , size_t... Is>
constexpr auto filterSequence (FunctorT F, std::index_sequence< Is... > Indices)
For each index 'I' from the given indices pack 'Is' this function returns an index sequence consisting of only those 'I's for which the 'FunctorT' applied to 'T[I]' returns true.
template<typename ElementType , typename BOPT >
constexpr auto makeAdjustedBOP (BOPT &BOP)
template<typename... Reductions, typename... BOPsT, size_t... Is>
constexpr auto makeAdjustedBOPs (ReduTupleT< BOPsT... > &BOPsTuple, std::index_sequence< Is... >)
template<typename... Reductions, typename... BOPsT>
constexpr auto makeAdjustedBOPs (ReduTupleT< BOPsT... > &BOPsTuple)
template<bool IsOneWG, typename... Reductions, int Dims, typename... LocalAccT, typename... OutAccT, typename... ReducerT, typename... Ts, typename... BOPsT, size_t... Is>
void reduCGFuncImplScalar (nd_item< Dims > NDIt, ReduTupleT< LocalAccT... > LocalAccsTuple, ReduTupleT< OutAccT... > OutAccsTuple, std::tuple< ReducerT... > &ReducersTuple, ReduTupleT< Ts... > IdentitiesTuple, ReduTupleT< BOPsT... > BOPsTuple, std::array< bool, sizeof...(Reductions)> InitToIdentityProps, std::index_sequence< Is... > ReduIndices)
All scalar reductions are processed together; there is one loop of log2(N) steps, and each reduction uses its own storage.
template<bool IsOneWG, typename Reduction , int Dims, typename LocalAccT , typename OutAccT , typename ReducerT , typename BOPT >
void reduCGFuncImplArrayHelper (nd_item< Dims > NDIt, LocalAccT LocalReds, OutAccT Out, ReducerT &Reducer, BOPT BOp, bool IsInitializeToIdentity)
Each array reduction is processed separately.
template<bool IsOneWG, typename... Reductions, int Dims, typename... LocalAccT, typename... OutAccT, typename... ReducerT, typename... BOPsT, size_t... Is>
void reduCGFuncImplArray (nd_item< Dims > NDIt, ReduTupleT< LocalAccT... > LocalAccsTuple, ReduTupleT< OutAccT... > OutAccsTuple, std::tuple< ReducerT... > &ReducersTuple, ReduTupleT< BOPsT... > BOPsTuple, std::array< bool, sizeof...(Reductions)> InitToIdentityProps, std::index_sequence< Is... >)
template<typename KernelName , typename KernelType , int Dims, typename PropertiesT , typename... Reductions, size_t... Is>
void reduCGFuncMulti (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, PropertiesT Properties, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... > ReduIndices)
template<typename... Reductions, size_t... Is>
void associateReduAccsWithHandler (handler &CGH, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
template<bool IsOneWG, typename... Reductions, int Dims, typename... LocalAccT, typename... InAccT, typename... OutAccT, typename... Ts, typename... BOPsT, size_t... Is>
void reduAuxCGFuncImplScalar (nd_item< Dims > NDIt, size_t LID, size_t GID, size_t RemainingWorkSize, ReduTupleT< LocalAccT... > LocalAccsTuple, ReduTupleT< InAccT... > InAccsTuple, ReduTupleT< OutAccT... > OutAccsTuple, ReduTupleT< Ts... > IdentitiesTuple, ReduTupleT< BOPsT... > BOPsTuple, std::array< bool, sizeof...(Reductions)> InitToIdentityProps, std::index_sequence< Is... > ReduIndices)
All scalar reductions are processed together; there is one loop of log2(N) steps, and each reduction uses its own storage.
template<bool IsOneWG, typename Reduction , int Dims, typename LocalAccT , typename InAccT , typename OutAccT , typename T , typename BOPT >
void reduAuxCGFuncImplArrayHelper (nd_item< Dims > NDIt, size_t LID, size_t GID, size_t RemainingWorkSize, LocalAccT LocalReds, InAccT In, OutAccT Out, T IdentityContainer, BOPT BOp, bool IsInitializeToIdentity)
template<bool IsOneWG, typename... Reductions, int Dims, typename... LocalAccT, typename... InAccT, typename... OutAccT, typename... Ts, typename... BOPsT, size_t... Is>
void reduAuxCGFuncImplArray (nd_item< Dims > NDIt, size_t LID, size_t GID, size_t RemainingWorkSize, ReduTupleT< LocalAccT... > LocalAccsTuple, ReduTupleT< InAccT... > InAccsTuple, ReduTupleT< OutAccT... > OutAccsTuple, ReduTupleT< Ts... > IdentitiesTuple, ReduTupleT< BOPsT... > BOPsTuple, std::array< bool, sizeof...(Reductions)> InitToIdentityProps, std::index_sequence< Is... >)
template<typename KernelName , typename KernelType , typename... Reductions, size_t... Is>
size_t reduAuxCGFunc (handler &CGH, size_t NWorkItems, size_t MaxWGSize, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... > ReduIndices)
template<typename Reduction >
size_t reduGetMemPerWorkItemHelper (Reduction &)
template<typename Reduction , typename... RestT>
size_t reduGetMemPerWorkItemHelper (Reduction &, RestT... Rest)
template<typename... ReductionT, size_t... Is>
size_t reduGetMemPerWorkItem (std::tuple< ReductionT... > &ReduTuple, std::index_sequence< Is... >)
template<typename TupleT , std::size_t... Is>
std::tuple< std::tuple_element_t< Is, TupleT >... > tuple_select_elements (TupleT Tuple, std::index_sequence< Is... >)
Utility function: for the given tuple.
uint32_t reduGetMaxNumConcurrentWorkGroups (std::shared_ptr< queue_impl > Queue)
unsigned GetFlushBufOffset (const GlobalBufAccessorT &GlobalFlushBuf, unsigned WIOffset)
void SetFlushBufOffset (GlobalBufAccessorT &GlobalFlushBuf, unsigned WIOffset, unsigned Offset)
void write (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const char *Str, unsigned Len, unsigned Padding=0)
void reverseBuf (char *Buf, unsigned Len)
template<typename T >
std::make_unsigned_t< T > getAbsVal (const T Val, const int Base)
char digitToChar (const int Digit)
template<typename T >
std::enable_if_t< std::is_integral_v< T >, unsigned > integralToBase (T Val, int Base, char *Digits)
template<typename T >
std::enable_if_t< std::is_integral_v< T >, unsigned > ScalarToStr (const T &Val, char *Buf, unsigned Flags, int, int Precision=-1)
unsigned append (char *Dst, const char *Src)
unsigned F2I32 (float Val)
unsigned long long D2I64 (double Val)
template<typename T >
detail::enable_if_t< std::is_same< T, float >::value||std::is_same< T, double >::value, bool > isFastMathInf (T Val)
template<typename T >
detail::enable_if_t< std::is_same< T, float >::value||std::is_same< T, double >::value, bool > isFastMathNan (T Val)
template<typename T >
detail::enable_if_t< std::is_same< T, float >::value||std::is_same< T, double >::value, bool > isFastMathSignBit (T Val)
template<typename T >
detail::enable_if_t< std::is_same< T, float >::value||std::is_same< T, double >::value, unsigned > checkForInfNan (char *Buf, T Val)
template<typename T >
std::enable_if_t< std::is_same_v< T, half >, unsigned > checkForInfNan (char *Buf, T Val)
template<typename T >
std::enable_if_t< std::is_same_v< T, ext::oneapi::bfloat16 >, unsigned > checkForInfNan (char *Buf, T Val)
template<typename T >
EnableIfFP< T, unsigned > floatingPointToDecStr (T AbsVal, char *Digits, int Precision, bool IsSci)
template<typename T >
EnableIfFP< T, unsigned > ScalarToStr (const T &Val, char *Buf, unsigned Flags, int, int Precision=-1)
template<typename T >
std::enable_if_t< std::is_integral_v< T > > writeIntegral (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, const T &Val)
template<typename T >
EnableIfFP< T > writeFloatingPoint (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, int Precision, const T &Val)
bool updateOffset (GlobalOffsetAccessorT &GlobalOffset, GlobalBufAccessorT &GlobalBuf, unsigned Size, unsigned &Cur)
void flushBuffer (GlobalOffsetAccessorT &GlobalOffset, GlobalBufAccessorT &GlobalBuf, GlobalBufAccessorT &GlobalFlushBuf, unsigned WIOffset)
template<typename T , int VecLength>
std::enable_if_t<(VecLength==1), unsigned > VecToStr (const vec< T, VecLength > &Vec, char *VecStr, unsigned Flags, int Width, int Precision)
template<typename T , int VecLength>
std::enable_if_t<(VecLength==2||VecLength==4||VecLength==8||VecLength==16), unsigned > VecToStr (const vec< T, VecLength > &Vec, char *VecStr, unsigned Flags, int Width, int Precision)
template<typename T , int VecLength>
std::enable_if_t<(VecLength==3), unsigned > VecToStr (const vec< T, VecLength > &Vec, char *VecStr, unsigned Flags, int Width, int Precision)
template<typename T , int VecLength>
void writeVec (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, int Precision, const vec< T, VecLength > &Vec)
template<int ArrayLength>
unsigned ArrayToStr (char *Buf, const array< ArrayLength > &Arr)
template<int ArrayLength>
void writeArray (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const array< ArrayLength > &Arr)
template<int Dimensions>
void writeItem (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const item< Dimensions > &Item)
template<int Dimensions>
void writeNDRange (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const nd_range< Dimensions > &ND_Range)
template<int Dimensions>
void writeNDItem (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const nd_item< Dimensions > &ND_Item)
template<int Dimensions>
void writeGroup (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const group< Dimensions > &Group)
template<int Dimensions>
unsigned ItemToStr (char *Buf, const item< Dimensions, false > &Item)
template<int Dimensions>
void writeHItem (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const h_item< Dimensions > &HItem)
template<typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>>
multi_ptr< T, Space, IsDecorated > GetUnqualMultiPtr (const multi_ptr< CVT, Space, IsDecorated > &Mptr)
template<typename T >
struct __SYCL2020_DEPRECATED ("This type isn't device copyable in SYCL 2020") IsDeprecatedDeviceCopyable< T
constexpr bool isValidVectorSize (int N)
static const PluginPtr & getPlugin (backend Backend)
void constructorNotification (void *BufferObj, void *AccessorObj, sycl::access::target Target, sycl::access::mode Mode, const detail::code_location &CodeLoc)
AllowListParsedT parseAllowList (const std::string &AllowListRaw)
bool deviceIsAllowed (const DeviceDescT &DeviceDesc, const AllowListParsedT &AllowListParsed)
void applyAllowList (std::vector< sycl::detail::pi::PiDevice > &PiDevices, sycl::detail::pi::PiPlatform PiPlatform, const PluginPtr &Plugin)
template<class T >
backend getImplBackend (const T &Impl)
static void initValue (const char *Key, const char *Value)
void readConfig (bool ForceInitialization)
void dumpConfig ()
const std::array< std::pair< std::string, backend >, 8 > & getSyclBeMap ()
constexpr const char * getStrOrNullptr (const char *Str)
template<bool supportAcc = false>
const std::array< std::pair< std::string, info::device_type >, 6 > & getSyclDeviceTypeMap ()
template<>
uint32_t context_impl::get_info< info::context::reference_count > () const
template<>
platform context_impl::get_info< info::context::platform > () const
template<>
std::vector< sycl::device > context_impl::get_info< info::context::devices > () const
template<>
std::vector< sycl::memory_order > context_impl::get_info< info::context::atomic_memory_order_capabilities > () const
template<>
std::vector< sycl::memory_scope > context_impl::get_info< info::context::atomic_memory_scope_capabilities > () const
template<>
std::vector< sycl::memory_order > context_impl::get_info< info::context::atomic_fence_order_capabilities > () const
template<>
std::vector< sycl::memory_scope > context_impl::get_info< info::context::atomic_fence_scope_capabilities > () const
template<>
info::platform::version::return_type context_impl::get_backend_info< info::platform::version > () const
device select_device (DSelectorInvocableType DeviceSelectorInvocable, std::vector< device > &Devices)
template<>
info::device::version::return_type context_impl::get_backend_info< info::device::version > () const
template<>
info::device::backend_version::return_type context_impl::get_backend_info< info::device::backend_version > () const
template<typename T , typename Capabilities >
void GetCapabilitiesIntersectionSet (const std::vector< sycl::device > &Devices, std::vector< T > &CapabilityList)
template<typename Param >
Param::return_type get_context_info (sycl::detail::pi::PiContext Ctx, const PluginPtr &Plugin)
std::ostream & operator<< (std::ostream &Out, const DeviceBinaryProperty &P)
std::vector< std::string_view > tokenize (const std::string_view &Filter, const std::string &Delim, bool ProhibitEmptyTokens=false)
static backend Parse_ODS_Backend (const std::string_view &BackendStr, const std::string_view &FullEntry)
static void Parse_ODS_Device (ods_target &Target, const std::string_view &DeviceStr)
template<>
info::platform::version::return_type device_impl::get_backend_info< info::platform::version > () const
template<>
info::device::version::return_type device_impl::get_backend_info< info::device::version > () const
template<>
info::device::backend_version::return_type device_impl::get_backend_info< info::device::backend_version > () const
std::vector< info::fp_config > read_fp_bitfield (pi_device_fp_config bits)
std::vector< info::partition_affinity_domain > read_domain_bitfield (pi_device_affinity_domain bits)
std::vector< info::execution_capability > read_execution_bitfield (pi_device_exec_capabilities bits)
std::string affinityDomainToString (info::partition_affinity_domain AffinityDomain)
static bool is_sycl_partition_property (info::partition_property PP)
template<int Dimensions>
range< Dimensions > construct_range (size_t *values)=delete
template<>
range< 1 > construct_range< 1 > (size_t *values)
template<>
range< 2 > construct_range< 2 > (size_t *values)
template<>
range< 3 > construct_range< 3 > (size_t *values)
template<typename Param >
Param::return_type get_device_info (const DeviceImplPtr &Dev)
template<typename Param >
Param::return_type get_device_info_host ()=delete
template<>
std::vector< sycl::aspect > get_device_info_host< info::device::aspects > ()
template<>
ext::oneapi::experimental::architecture get_device_info_host< ext::oneapi::experimental::info::device::architecture > ()
template<>
info::device_type get_device_info_host< info::device::device_type > ()
template<>
uint32_t get_device_info_host< info::device::vendor_id > ()
template<>
uint32_t get_device_info_host< info::device::max_compute_units > ()
template<>
uint32_t get_device_info_host< info::device::max_work_item_dimensions > ()
template<>
range< 1 > get_device_info_host< info::device::max_work_item_sizes< 1 > > ()
template<>
range< 2 > get_device_info_host< info::device::max_work_item_sizes< 2 > > ()
template<>
range< 3 > get_device_info_host< info::device::max_work_item_sizes< 3 > > ()
template<>
constexpr size_t get_device_info_host< ext::oneapi::experimental::info::device::max_global_work_groups > ()
template<>
id< 1 > get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 1 > > ()
template<>
id< 2 > get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 2 > > ()
template<>
id< 3 > get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 3 > > ()
template<>
constexpr size_t get_device_info_host< info::device::ext_oneapi_max_global_work_groups > ()
template<>
id< 1 > get_device_info_host< info::device::ext_oneapi_max_work_groups_1d > ()
template<>
id< 2 > get_device_info_host< info::device::ext_oneapi_max_work_groups_2d > ()
template<>
id< 3 > get_device_info_host< info::device::ext_oneapi_max_work_groups_3d > ()
template<>
size_t get_device_info_host< info::device::max_work_group_size > ()
template<>
uint32_t get_device_info_host< info::device::preferred_vector_width_char > ()
template<>
uint32_t get_device_info_host< info::device::preferred_vector_width_short > ()
template<>
uint32_t get_device_info_host< info::device::preferred_vector_width_int > ()
template<>
uint32_t get_device_info_host< info::device::preferred_vector_width_long > ()
template<>
uint32_t get_device_info_host< info::device::preferred_vector_width_float > ()
template<>
uint32_t get_device_info_host< info::device::preferred_vector_width_double > ()
template<>
uint32_t get_device_info_host< info::device::preferred_vector_width_half > ()
template<>
uint32_t get_device_info_host< info::device::native_vector_width_char > ()
template<>
uint32_t get_device_info_host< info::device::native_vector_width_short > ()
template<>
uint32_t get_device_info_host< info::device::native_vector_width_int > ()
template<>
uint32_t get_device_info_host< info::device::native_vector_width_long > ()
template<>
uint32_t get_device_info_host< info::device::native_vector_width_float > ()
template<>
uint32_t get_device_info_host< info::device::native_vector_width_double > ()
template<>
uint32_t get_device_info_host< info::device::native_vector_width_half > ()
template<>
uint32_t get_device_info_host< info::device::max_clock_frequency > ()
template<>
uint32_t get_device_info_host< info::device::address_bits > ()
template<>
uint64_t get_device_info_host< info::device::global_mem_size > ()
template<>
uint64_t get_device_info_host< info::device::max_mem_alloc_size > ()
template<>
bool get_device_info_host< info::device::image_support > ()
template<>
bool get_device_info_host< info::device::atomic64 > ()
template<>
std::vector< memory_order > get_device_info_host< info::device::atomic_memory_order_capabilities > ()
template<>
std::vector< memory_order > get_device_info_host< info::device::atomic_fence_order_capabilities > ()
template<>
std::vector< memory_scope > get_device_info_host< info::device::atomic_memory_scope_capabilities > ()
template<>
std::vector< memory_scope > get_device_info_host< info::device::atomic_fence_scope_capabilities > ()
template<>
bool get_device_info_host< info::device::ext_oneapi_bfloat16_math_functions > ()
template<>
uint32_t get_device_info_host< info::device::max_read_image_args > ()
template<>
uint32_t get_device_info_host< info::device::max_write_image_args > ()
template<>
size_t get_device_info_host< info::device::image2d_max_width > ()
template<>
size_t get_device_info_host< info::device::image2d_max_height > ()
template<>
size_t get_device_info_host< info::device::image3d_max_width > ()
template<>
size_t get_device_info_host< info::device::image3d_max_height > ()
template<>
size_t get_device_info_host< info::device::image3d_max_depth > ()
template<>
size_t get_device_info_host< info::device::image_max_buffer_size > ()
template<>
size_t get_device_info_host< info::device::image_max_array_size > ()
template<>
uint32_t get_device_info_host< info::device::max_samplers > ()
template<>
size_t get_device_info_host< info::device::max_parameter_size > ()
template<>
uint32_t get_device_info_host< info::device::mem_base_addr_align > ()
template<>
std::vector< info::fp_config > get_device_info_host< info::device::half_fp_config > ()
template<>
std::vector< info::fp_config > get_device_info_host< info::device::single_fp_config > ()
template<>
std::vector< info::fp_config > get_device_info_host< info::device::double_fp_config > ()
template<>
info::global_mem_cache_type get_device_info_host< info::device::global_mem_cache_type > ()
template<>
uint32_t get_device_info_host< info::device::global_mem_cache_line_size > ()
template<>
uint64_t get_device_info_host< info::device::global_mem_cache_size > ()
template<>
uint64_t get_device_info_host< info::device::max_constant_buffer_size > ()
template<>
uint32_t get_device_info_host< info::device::max_constant_args > ()
template<>
info::local_mem_type get_device_info_host< info::device::local_mem_type > ()
template<>
uint64_t get_device_info_host< info::device::local_mem_size > ()
template<>
bool get_device_info_host< info::device::error_correction_support > ()
template<>
bool get_device_info_host< info::device::host_unified_memory > ()
template<>
size_t get_device_info_host< info::device::profiling_timer_resolution > ()
template<>
bool get_device_info_host< info::device::is_endian_little > ()
template<>
bool get_device_info_host< info::device::is_available > ()
template<>
bool get_device_info_host< info::device::is_compiler_available > ()
template<>
bool get_device_info_host< info::device::is_linker_available > ()
template<>
std::vector< info::execution_capability > get_device_info_host< info::device::execution_capabilities > ()
template<>
bool get_device_info_host< info::device::queue_profiling > ()
template<>
std::vector< kernel_id > get_device_info_host< info::device::built_in_kernel_ids > ()
template<>
std::vector< std::string > get_device_info_host< info::device::built_in_kernels > ()
template<>
platform get_device_info_host< info::device::platform > ()
template<>
std::string get_device_info_host< info::device::name > ()
template<>
std::string get_device_info_host< info::device::vendor > ()
template<>
std::string get_device_info_host< info::device::driver_version > ()
template<>
std::string get_device_info_host< info::device::profile > ()
template<>
std::string get_device_info_host< info::device::version > ()
template<>
std::string get_device_info_host< info::device::opencl_c_version > ()
template<>
std::vector< std::string > get_device_info_host< info::device::extensions > ()
template<>
size_t get_device_info_host< info::device::printf_buffer_size > ()
template<>
bool get_device_info_host< info::device::preferred_interop_user_sync > ()
template<>
device get_device_info_host< info::device::parent_device > ()
template<>
uint32_t get_device_info_host< info::device::partition_max_sub_devices > ()
template<>
std::vector< info::partition_property > get_device_info_host< info::device::partition_properties > ()
template<>
std::vector< info::partition_affinity_domain > get_device_info_host< info::device::partition_affinity_domains > ()
template<>
info::partition_property get_device_info_host< info::device::partition_type_property > ()
template<>
info::partition_affinity_domain get_device_info_host< info::device::partition_type_affinity_domain > ()
template<>
uint32_t get_device_info_host< info::device::reference_count > ()
template<>
uint32_t get_device_info_host< info::device::max_num_sub_groups > ()
template<>
std::vector< size_t > get_device_info_host< info::device::sub_group_sizes > ()
template<>
bool get_device_info_host< info::device::sub_group_independent_forward_progress > ()
template<>
bool get_device_info_host< info::device::kernel_kernel_pipe_support > ()
template<>
std::string get_device_info_host< info::device::backend_version > ()
template<>
bool get_device_info_host< info::device::usm_device_allocations > ()
template<>
bool get_device_info_host< info::device::usm_host_allocations > ()
template<>
bool get_device_info_host< info::device::usm_shared_allocations > ()
template<>
bool get_device_info_host< info::device::usm_restricted_shared_allocations > ()
template<>
bool get_device_info_host< info::device::usm_system_allocations > ()
template<>
bool get_device_info_host< info::device::ext_intel_mem_channel > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::device_id > ()
template<>
std::string get_device_info_host< ext::intel::info::device::pci_address > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::gpu_eu_count > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::gpu_eu_simd_width > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::gpu_slices > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::gpu_subslices_per_slice > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::gpu_eu_count_per_subslice > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::gpu_hw_threads_per_eu > ()
template<>
uint64_t get_device_info_host< ext::intel::info::device::max_mem_bandwidth > ()
template<>
detail::uuid_type get_device_info_host< ext::intel::info::device::uuid > ()
template<>
std::string get_device_info_host< info::device::ext_intel_pci_address > ()
template<>
uint32_t get_device_info_host< info::device::ext_intel_gpu_eu_count > ()
template<>
uint32_t get_device_info_host< info::device::ext_intel_gpu_eu_simd_width > ()
template<>
uint32_t get_device_info_host< info::device::ext_intel_gpu_slices > ()
template<>
uint32_t get_device_info_host< info::device::ext_intel_gpu_subslices_per_slice > ()
template<>
uint32_t get_device_info_host< info::device::ext_intel_gpu_eu_count_per_subslice > ()
template<>
uint32_t get_device_info_host< info::device::ext_intel_gpu_hw_threads_per_eu > ()
template<>
uint64_t get_device_info_host< info::device::ext_intel_max_mem_bandwidth > ()
template<>
bool get_device_info_host< info::device::ext_oneapi_srgb > ()
template<>
detail::uuid_type get_device_info_host< info::device::ext_intel_device_info_uuid > ()
template<>
uint64_t get_device_info_host< ext::intel::info::device::free_memory > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::memory_clock_rate > ()
template<>
uint32_t get_device_info_host< ext::intel::info::device::memory_bus_width > ()
template<>
int32_t get_device_info_host< ext::intel::info::device::max_compute_queue_indices > ()
template<>
bool get_device_info_host< ext::codeplay::experimental::info::device::supports_fusion > ()
template<>
uint32_t get_device_info_host< ext::codeplay::experimental::info::device::max_registers_per_work_group > ()
template<>
uint32_t get_device_info_host< ext::oneapi::experimental::info::device::image_row_pitch_align > ()
template<>
uint32_t get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_row_pitch > ()
template<>
std::vector< ext::oneapi::experimental::matrix::combination > get_device_info_host< ext::oneapi::experimental::info::device::matrix_combinations > ()
template<>
uint32_t get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_width > ()
template<>
uint32_t get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_height > ()
template<>
float get_device_info_host< ext::oneapi::experimental::info::device::mipmap_max_anisotropy > ()
template<>
std::vector< sycl::device > get_device_info_host< ext::oneapi::experimental::info::device::component_devices > ()
template<>
sycl::device get_device_info_host< ext::oneapi::experimental::info::device::composite_device > ()
static uint64_t getTimestamp ()
template<>
uint64_t event_impl::get_profiling_info< info::event_profiling::command_submit > ()
template<>
uint64_t event_impl::get_profiling_info< info::event_profiling::command_start > ()
template<>
uint64_t event_impl::get_profiling_info< info::event_profiling::command_end > ()
template<>
uint32_t event_impl::get_info< info::event::reference_count > ()
template<>
info::event_command_status event_impl::get_info< info::event::command_execution_status > ()
template<>
info::platform::version::return_type event_impl::get_backend_info< info::platform::version > () const
template<>
info::device::version::return_type event_impl::get_backend_info< info::device::version > () const
template<>
info::device::backend_version::return_type event_impl::get_backend_info< info::device::backend_version > () const
template<typename Param >
Param::return_type get_event_profiling_info (sycl::detail::pi::PiEvent Event, const PluginPtr &Plugin)
template<typename Param >
Param::return_type get_event_info (sycl::detail::pi::PiEvent Event, const PluginPtr &Plugin)
static void enableOnCrashStackPrinting ()
void shutdown ()
__attribute__ ((destructor(110))) static void syclUnload()
std::vector< sycl::detail::pi::PiEvent > getOrWaitEvents (std::vector< sycl::event > DepEvents, ContextImplPtr Context)
template<typename Param >
static bool checkImageValueRange (const std::vector< device > &Devices, const size_t Value)
template<typename T , typename... Args>
static bool checkAnyImpl (T)
template<typename ValT , typename VarT , typename... Args>
static bool checkAnyImpl (ValT Value, VarT Variant, Args... Arguments)
template<typename T , typename... Args>
static bool checkAny (const T Value, Args... Arguments)
uint8_t getImageNumberChannels (image_channel_order Order)
uint8_t getImageElementSize (uint8_t NumChannels, image_channel_type Type)
sycl::detail::pi::PiMemImageChannelOrder convertChannelOrder (image_channel_order Order)
image_channel_order convertChannelOrder (sycl::detail::pi::PiMemImageChannelOrder Order)
sycl::detail::pi::PiMemImageChannelType convertChannelType (image_channel_type Type)
image_channel_type convertChannelType (sycl::detail::pi::PiMemImageChannelType Type)
template<typename T >
static void getImageInfo (const ContextImplPtr Context, sycl::detail::pi::PiMemImageInfo Info, T &Dest, sycl::detail::pi::PiMem InteropMemObject)
KernelArgMask createKernelArgMask (const ByteArray &Bytes)
static bool checkAllDevicesAreInContext (const std::vector< device > &Devices, const context &Context)
static bool checkAllDevicesHaveAspect (const std::vector< device > &Devices, aspect Aspect)
template<>
info::platform::version::return_type kernel_impl::get_backend_info< info::platform::version > () const
template<>
info::device::version::return_type kernel_impl::get_backend_info< info::device::version > () const
template<>
info::device::backend_version::return_type kernel_impl::get_backend_info< info::device::backend_version > () const
template<>
context kernel_impl::get_info< info::kernel::context > () const
template<>
ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync::return_type kernel_impl::ext_oneapi_get_info< ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync > (const queue &Queue) const
template<typename Param >
std::enable_if< std::is_same< typename Param::return_type, std::string >::value, std::string >::type get_kernel_info (sycl::detail::pi::PiKernel Kernel, const PluginPtr &Plugin)
template<typename Param >
std::enable_if< std::is_same< typename Param::return_type, uint32_t >::value, uint32_t >::type get_kernel_info (sycl::detail::pi::PiKernel Kernel, const PluginPtr &Plugin)
template<typename Param >
std::enable_if< IsSubGroupInfo< Param >::value >::type get_kernel_device_specific_info_helper (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, const PluginPtr &Plugin, void *Result, size_t Size)
template<typename Param >
std::enable_if<!IsSubGroupInfo< Param >::value >::type get_kernel_device_specific_info_helper (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, const PluginPtr &Plugin, void *Result, size_t Size)
template<typename Param >
std::enable_if< !std::is_same< typename Param::return_type, sycl::range< 3 > >::value, typename Param::return_type >::type get_kernel_device_specific_info (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, const PluginPtr &Plugin)
template<typename Param >
std::enable_if< std::is_same< typename Param::return_type, sycl::range< 3 > >::value, sycl::range< 3 > >::type get_kernel_device_specific_info (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, const PluginPtr &Plugin)
template<typename Param >
uint32_t get_kernel_device_specific_info_with_input (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, sycl::range< 3 > In, const PluginPtr &Plugin)
template<typename Param >
Param::return_type get_kernel_device_specific_info_host (const sycl::device &Device)=delete
template<>
sycl::range< 3 > get_kernel_device_specific_info_host< info::kernel_device_specific::global_work_size > (const sycl::device &)
template<>
size_t get_kernel_device_specific_info_host< info::kernel_device_specific::work_group_size > (const sycl::device &Dev)
template<>
sycl::range< 3 > get_kernel_device_specific_info_host< info::kernel_device_specific::compile_work_group_size > (const sycl::device &)
template<>
size_t get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple > (const sycl::device &Dev)
template<>
size_t get_kernel_device_specific_info_host< info::kernel_device_specific::private_mem_size > (const sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::ext_codeplay_num_regs > (const sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::max_num_sub_groups > (const sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::max_sub_group_size > (const sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::compile_num_sub_groups > (const sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::compile_sub_group_size > (const sycl::device &)
void memBufferCreateHelper (const PluginPtr &Plugin, pi_context Ctx, pi_mem_flags Flags, size_t Size, void *HostPtr, pi_mem *RetMem, const pi_mem_properties *Props=nullptr)
void memReleaseHelper (const PluginPtr &Plugin, pi_mem Mem)
void memBufferMapHelper (const PluginPtr &Plugin, pi_queue command_queue, pi_mem buffer, pi_bool blocking_map, pi_map_flags map_flags, size_t offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event, void **ret_map)
void memUnmapHelper (const PluginPtr &Plugin, pi_queue command_queue, pi_mem memobj, void *mapped_ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
uint64_t emitMemAllocBeginTrace (uintptr_t ObjHandle, size_t AllocSize, size_t GuardZone)
void emitMemAllocEndTrace (uintptr_t ObjHandle, uintptr_t AllocPtr, size_t AllocSize, size_t GuardZone, uint64_t CorrelationID)
uint64_t emitMemReleaseBeginTrace (uintptr_t ObjHandle, uintptr_t AllocPtr)
void emitMemReleaseEndTrace (uintptr_t ObjHandle, uintptr_t AllocPtr, uint64_t CorrelationID)
static void waitForEvents (const std::vector< EventImplPtr > &Events)
static sycl::detail::pi::PiMemFlags getMemObjCreationFlags (void *UserPtr, bool HostPtrReadOnly)
void prepTermPositions (TermPositions &pos, int Dimensions, detail::SYCLMemObjI::MemObjType Type)
void copyH2D (SYCLMemObjI *SYCLMemObj, char *SrcMem, QueueImplPtr, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, sycl::detail::pi::PiMem DstMem, QueueImplPtr TgtQueue, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent, const detail::EventImplPtr &OutEventImpl)
void copyD2H (SYCLMemObjI *SYCLMemObj, sycl::detail::pi::PiMem SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char *DstMem, QueueImplPtr, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent, const detail::EventImplPtr &OutEventImpl)
void copyD2D (SYCLMemObjI *SYCLMemObj, sycl::detail::pi::PiMem SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, sycl::detail::pi::PiMem DstMem, QueueImplPtr, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 >, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent &OutEvent, const detail::EventImplPtr &OutEventImpl)
static void copyH2H (SYCLMemObjI *, char *SrcMem, QueueImplPtr, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char *DstMem, QueueImplPtr, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent >, sycl::detail::pi::PiEvent &, const detail::EventImplPtr &)
static void memcpyToDeviceGlobalUSM (QueueImplPtr Queue, DeviceGlobalMapEntry *DeviceGlobalEntry, size_t NumBytes, size_t Offset, const void *Src, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static void memcpyFromDeviceGlobalUSM (QueueImplPtr Queue, DeviceGlobalMapEntry *DeviceGlobalEntry, size_t NumBytes, size_t Offset, void *Dest, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent, const detail::EventImplPtr &OutEventImpl)
static sycl::detail::pi::PiProgram getOrBuildProgramForDeviceGlobal (QueueImplPtr Queue, DeviceGlobalMapEntry *DeviceGlobalEntry)
static void memcpyToDeviceGlobalDirect (QueueImplPtr Queue, DeviceGlobalMapEntry *DeviceGlobalEntry, size_t NumBytes, size_t Offset, const void *Src, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static void memcpyFromDeviceGlobalDirect (QueueImplPtr Queue, DeviceGlobalMapEntry *DeviceGlobalEntry, size_t NumBytes, size_t Offset, void *Dest, const std::vector< sycl::detail::pi::PiEvent > &DepEvents, sycl::detail::pi::PiEvent *OutEvent)
static bool IsSupportedImageFormat (sycl::detail::pi::PiDeviceBinaryType Format)
std::string getDirName (const char *Path)
template void * getPluginOpaqueData< sycl::backend::ext_intel_esimd_emulator > (void *)
static bool IsBannedPlatform (platform Platform)
static bool supportsAffinityDomain (const device &dev, info::partition_property partitionProp, info::partition_affinity_domain domain)
static bool supportsPartitionProperty (const device &dev, info::partition_property partitionProp)
static std::vector< device > amendDeviceAndSubDevices (backend PlatformBackend, std::vector< device > &DeviceList, ods_target_list *OdsTargetList, const std::vector< int > &original_indices, PlatformImplPtr PlatformImpl)
template<>
info::platform::version::return_type platform_impl::get_backend_info< info::platform::version > () const
template<>
info::device::version::return_type platform_impl::get_backend_info< info::device::version > () const
template<>
info::device::backend_version::return_type platform_impl::get_backend_info< info::device::backend_version > () const
std::string get_platform_info_string_impl (sycl::detail::pi::PiPlatform Plt, const PluginPtr &Plugin, pi_platform_info PiCode)
template<typename Param >
std::enable_if< std::is_same< typename Param::return_type, std::string >::value, std::string >::type get_platform_info (sycl::detail::pi::PiPlatform Plt, const PluginPtr &Plugin)
template<typename Param >
std::enable_if< std::is_same< Param, info::platform::extensions >::value, std::vector< std::string > >::type get_platform_info (sycl::detail::pi::PiPlatform Plt, const PluginPtr &Plugin)
template<typename Param >
Param::return_type get_platform_info_host ()=delete
template<>
std::string get_platform_info_host< info::platform::profile > ()
template<>
std::string get_platform_info_host< info::platform::version > ()
template<>
std::string get_platform_info_host< info::platform::name > ()
template<>
std::string get_platform_info_host< info::platform::vendor > ()
template<>
std::vector< std::string > get_platform_info_host< info::platform::extensions > ()
template<typename... Ts>
constexpr size_t totalSize (const std::tuple< Ts... > &)
template<PiApiKind Kind, typename... ArgsT>
auto packCallArguments (ArgsT &&...Args)
static constexpr char UseSpvEnv ("SYCL_USE_KERNEL_SPV")
static void enableITTAnnotationsIfNeeded (const sycl::detail::pi::PiProgram &Prog, const PluginPtr &Plugin)
This function enables ITT annotations in SPIR-V module by setting a specialization constant if INTEL_LIBITTNOTIFY64 env variable is set.
static sycl::detail::pi::PiProgram createBinaryProgram (const ContextImplPtr Context, const device &Device, const unsigned char *Data, size_t DataLen, const std::vector< pi_device_binary_property > Metadata)
static sycl::detail::pi::PiProgram createSpirvProgram (const ContextImplPtr Context, const unsigned char *Data, size_t DataLen)
static bool isDeviceBinaryTypeSupported (const context &C, sycl::detail::pi::PiDeviceBinaryType Format)
static const char * getFormatStr (sycl::detail::pi::PiDeviceBinaryType Format)
static void appendLinkOptionsFromImage (std::string &LinkOpts, const RTDeviceBinaryImage &Img)
static bool getUint32PropAsBool (const RTDeviceBinaryImage &Img, const char *PropName)
static std::string getUint32PropAsOptStr (const RTDeviceBinaryImage &Img, const char *PropName)
static void appendCompileOptionsForGRFSizeProperties (std::string &CompileOpts, const RTDeviceBinaryImage &Img, bool IsEsimdImage)
static void appendCompileOptionsFromImage (std::string &CompileOpts, const RTDeviceBinaryImage &Img, const std::vector< device > &Devs, const PluginPtr &)
static void appendCompileEnvironmentVariablesThatAppend (std::string &CompileOpts)
static void appendLinkEnvironmentVariablesThatAppend (std::string &LinkOpts)
static void applyOptionsFromImage (std::string &CompileOpts, std::string &LinkOpts, const RTDeviceBinaryImage &Img, const std::vector< device > &Devices, const PluginPtr &Plugin)
static void applyCompileOptionsFromEnvironment (std::string &CompileOpts)
static void applyLinkOptionsFromEnvironment (std::string &LinkOpts)
static void applyOptionsFromEnvironment (std::string &CompileOpts, std::string &LinkOpts)
static void emitBuiltProgramInfo (const pi_program &Prog, const ContextImplPtr &Context)
Emits information about built programs if the appropriate contitions are met, namely when SYCL_RT_WARNING_LEVEL is greater than or equal to 2.
static bool loadDeviceLib (const ContextImplPtr Context, const char *Name, sycl::detail::pi::PiProgram &Prog)
static const char * getDeviceLibFilename (DeviceLibExt Extension, bool Native)
static const char * getDeviceLibExtensionStr (DeviceLibExt Extension)
static sycl::detail::pi::PiProgram loadDeviceLibFallback (const ContextImplPtr Context, DeviceLibExt Extension, const sycl::detail::pi::PiDevice &Device, bool UseNativeLib)
void CheckJITCompilationForImage (const RTDeviceBinaryImage *const &Image, bool JITCompilationIsRequired)
template<typename StorageKey >
RTDeviceBinaryImage * getBinImageFromMultiMap (const std::unordered_multimap< StorageKey, RTDeviceBinaryImage * > &ImagesSet, const StorageKey &Key, const context &Context, const device &Device)
static bool isDeviceLibRequired (DeviceLibExt Ext, uint32_t DeviceLibReqMask)
static std::vector< sycl::detail::pi::PiProgram > getDeviceLibPrograms (const ContextImplPtr Context, const sycl::detail::pi::PiDevice &Device, uint32_t DeviceLibReqMask)
static bundle_state getBinImageState (const RTDeviceBinaryImage *BinImage)
static bool compatibleWithDevice (RTDeviceBinaryImage *BinImage, const device &Dev)
static void setSpecializationConstants (const std::shared_ptr< device_image_impl > &InputImpl, sycl::detail::pi::PiProgram Prog, const PluginPtr &Plugin)
bool doesDevSupportDeviceRequirements (const device &Dev, const RTDeviceBinaryImage &Img)
static std::string getAspectNameStr (sycl::aspect AspectNum)
template<typename T >
static std::enable_if_t< std::is_unsigned_v< T >, std::optional< T > > multiply_with_overflow_check (T x, T y)
std::optional< matrix_ext::matrix_type > convertMatrixTypeStringMatrixTypeEnumValue (const std::string &MatrixTypeString)
bool isMatrixSupportedByHW (const std::string &MatrixTypeStrUser, size_t RowsUser, size_t ColsUser, matrix_ext::matrix_type MatrixTypeRuntime, size_t MaxRowsRuntime, size_t MaxColsRuntime, size_t RowsRuntime, size_t ColsRuntime)
std::optional< sycl::exception > checkDevSupportJointMatrix (const std::string &JointMatrixProStr, const std::vector< ext::oneapi::experimental::matrix::combination > &SupportedMatrixCombinations)
std::optional< sycl::exception > checkDevSupportJointMatrixMad (const std::string &JointMatrixProStr, const std::vector< ext::oneapi::experimental::matrix::combination > &SupportedMatrixCombinations)
std::optional< sycl::exception > checkDevSupportDeviceRequirements (const device &Dev, const RTDeviceBinaryImage &Img, const NDRDescT &NDRDesc)
static std::vector< sycl::detail::pi::PiEvent > getPIEvents (const std::vector< sycl::event > &DepEvents)
template<>
uint32_t queue_impl::get_info< info::queue::reference_count > () const
template<>
context queue_impl::get_info< info::queue::context > () const
template<>
device queue_impl::get_info< info::queue::device > () const
template<>
info::platform::version::return_type queue_impl::get_backend_info< info::platform::version > () const
template<>
info::device::version::return_type queue_impl::get_backend_info< info::device::version > () const
template<>
info::device::backend_version::return_type queue_impl::get_backend_info< info::device::backend_version > () const
static event prepareSYCLEventAssociatedWithQueue (const std::shared_ptr< detail::queue_impl > &QueueImpl)
static event createDiscardedEvent ()
void report (const code_location &CodeLoc)
uint32_t reduGetMaxNumConcurrentWorkGroups (std::shared_ptr< sycl::detail::queue_impl > Queue)
size_t reduGetMaxWGSize (std::shared_ptr< sycl::detail::queue_impl > Queue, size_t LocalMemBytesPerWorkItem)
static std::string demangleKernelName (std::string Name)
static std::string deviceToString (device Device)
void applyFuncOnFilteredArgs (const KernelArgMask *EliminatedArgMask, std::vector< ArgDesc > &Args, std::function< void(detail::ArgDesc &Arg, int NextTrueIndex)> Func)
static std::string accessModeToString (access::mode Mode)
static void flushCrossQueueDeps (const std::vector< EventImplPtr > &EventImpls, const QueueImplPtr &Queue)
static std::string_view cgTypeToString (detail::CG::CGTYPE Type)
static void adjustNDRangePerKernel (NDRDescT &NDR, sycl::detail::pi::PiKernel Kernel, const device_impl &DeviceImpl)
void ReverseRangeDimensionsForKernel (NDRDescT &NDR)
pi_mem_obj_access AccessModeToPi (access::mode AccessorMode)
void SetArgBasedOnType (const PluginPtr &Plugin, sycl::detail::pi::PiKernel Kernel, const std::shared_ptr< device_image_impl > &DeviceImageImpl, const std::function< void *(Requirement *Req)> &getMemAllocationFunc, const sycl::context &Context, bool IsHost, detail::ArgDesc &Arg, size_t NextTrueIndex)
static pi_result SetKernelParamsAndLaunch (const QueueImplPtr &Queue, std::vector< ArgDesc > &Args, const std::shared_ptr< device_image_impl > &DeviceImageImpl, sycl::detail::pi::PiKernel Kernel, NDRDescT &NDRDesc, std::vector< sycl::detail::pi::PiEvent > &RawEvents, const detail::EventImplPtr &OutEventImpl, const KernelArgMask *EliminatedArgMask, const std::function< void *(Requirement *Req)> &getMemAllocationFunc, bool IsCooperative)
void DispatchNativeKernel (void *Blob)
pi_int32 enqueueImpCommandBufferKernel (context Ctx, DeviceImplPtr DeviceImpl, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, const CGExecKernel &CommandGroup, std::vector< sycl::detail::pi::PiExtSyncPoint > &SyncPoints, sycl::detail::pi::PiExtSyncPoint *OutSyncPoint, sycl::detail::pi::PiExtCommandBufferCommand *OutCommand, const std::function< void *(Requirement *Req)> &getMemAllocationFunc)
pi_int32 enqueueImpKernel (const QueueImplPtr &Queue, NDRDescT &NDRDesc, std::vector< ArgDesc > &Args, const std::shared_ptr< detail::kernel_bundle_impl > &KernelBundleImplPtr, const std::shared_ptr< detail::kernel_impl > &MSyclKernel, const std::string &KernelName, std::vector< sycl::detail::pi::PiEvent > &RawEvents, const detail::EventImplPtr &OutEventImpl, const std::function< void *(Requirement *Req)> &getMemAllocationFunc, sycl::detail::pi::PiKernelCacheConfig KernelCacheConfig, const bool KernelIsCooperative)
pi_int32 enqueueReadWriteHostPipe (const QueueImplPtr &Queue, const std::string &PipeName, bool blocking, void *ptr, size_t size, std::vector< sycl::detail::pi::PiEvent > &RawEvents, const detail::EventImplPtr &OutEventImpl, bool read)
void SetArgBasedOnType (const detail::plugin &Plugin, sycl::detail::pi::PiKernel Kernel, const std::shared_ptr< device_image_impl > &DeviceImageImpl, const std::function< void *(Requirement *Req)> &getMemAllocationFunc, const sycl::context &Context, bool IsHost, detail::ArgDesc &Arg, size_t NextTrueIndex)
static bool doOverlap (const Requirement *LHS, const Requirement *RHS)
Checks whether two requirements overlap or not.
static bool sameCtx (const ContextImplPtr &LHS, const ContextImplPtr &RHS)
static bool IsSuitableSubReq (const Requirement *Req)
Checks if current requirement is requirement for sub buffer.
static bool isAccessModeAllowed (access::mode Required, access::mode Current)
Checks if the required access mode is allowed under the current one.
static access::mode combineAccessModes (access::mode A, access::mode B)
Combines two access modes into a single one that allows both.
static bool markNodeAsVisited (Command *Cmd, std::vector< Command * > &Visited)
static void unmarkVisitedNodes (std::vector< Command * > &Visited)
static void handleVisitedNodes (std::vector< Command * > &Visited)
static void printDotRecursive (std::fstream &Stream, std::vector< Command * > &Visited, Command *Cmd)
static Command * insertMapUnmapForLinkedCmds (AllocaCommandBase *AllocaCmdSrc, AllocaCommandBase *AllocaCmdDst, access::mode MapMode)
static bool checkHostUnifiedMemory (const ContextImplPtr &Ctx)
static bool isInteropHostTask (ExecCGCommand *Cmd)
static void combineAccessModesOfReqs (std::vector< Requirement * > &Reqs)
static bool isPartOfFusion (Command *Cmd, KernelFusionCommand *Fusion)
static bool checkForCircularDependency (Command *, bool, KernelFusionCommand *)
static bool createsCircularDependency (Command *Cmd, bool PredPartOfFusion, KernelFusionCommand *Fusion)
static Command * getCommand (const EventImplPtr &Event)
static bool doOverlap (const Requirement *LHS, const Requirement *RHS)
static bool isHostAccessorCmd (Command *Cmd)
static void registerAuxiliaryResourcesNoLock (std::unordered_map< EventImplPtr, std::vector< std::shared_ptr< const void >>> &AuxiliaryResources, const EventImplPtr &Event, std::vector< std::shared_ptr< const void >> &&Resources)
bool CheckEventReadiness (const ContextImplPtr &Context, const EventImplPtr &SyclEventImplPtr)
void stableSerializeSpecConstRegistry (const SpecConstRegistryT &Reg, SerializedObj &Dst)
std::ostream & operator<< (std::ostream &Out, const spec_constant_impl &V)
std::vector< std::string > split_string (std::string_view str, char delimeter)
sycl::detail::pi::PiMemObjectType getImageType (int Dimensions)
void force_type (info::device_type &t, const info::device_type &ft)
static int getDevicePreference (const device &Device)
static void traceDeviceSelection (const device &Device, int Score, bool Chosen)
ESIMDDeviceInterface * getESIMDDeviceInterface ()
sycl::detail::pi::PiImageCopyFlags getPiImageCopyFlags (sycl::usm::alloc SrcPtrType, sycl::usm::alloc DstPtrType)
Variables
template<typename T >
constexpr bool use_fast_math_v = use_fast_math<T>::value
template<typename T1 , typename T2 >
constexpr bool is_same_op_v = is_same_op<T1, T2>::value
template<typename... Ts>
constexpr bool check_all_same_op_type_v = CheckAllSameOpType<Ts...>()
template<size_t... Ns>
constexpr bool check_size_in_v = CheckSizeIn<Ns...>()
template<typename T , typename... Ts>
constexpr bool is_valid_elem_type_v = is_valid_elem_type<T, Ts...>::value
template<typename T >
constexpr access::decorated get_multi_ptr_decoration_v
template<typename T >
constexpr bool has_writeable_addr_space_v = has_writeable_addr_space<T>::value
template<typename T >
constexpr bool is_swizzle_v = is_swizzle<T>::value
template<typename T >
constexpr bool is_vec_or_swizzle_v = is_vec_v<T> || is_swizzle_v<T>
template<typename T , int... Ns>
constexpr bool is_valid_size_v = is_valid_size<T, Ns...>::value
template<typename... Ts>
constexpr bool builtin_same_shape_v
template<typename... Ts>
constexpr bool builtin_same_or_swizzle_v
template<typename T >
constexpr bool is_svgenfloatf_v
template<typename T >
constexpr bool is_svgenfloatd_v
template<typename T >
constexpr bool is_half_v = is_contained_v<T, gtl::scalar_half_list>
template<typename T >
constexpr bool is_bfloat16_v
template<typename T >
constexpr bool is_half_or_bf16_v
template<typename T >
constexpr bool is_svgenfloath_v
template<typename T >
constexpr bool is_genfloat_v = is_contained_v<T, gtl::floating_list>
template<typename T >
constexpr bool is_sgenfloat_v
template<typename T >
constexpr bool is_vgenfloat_v
template<typename T >
constexpr bool is_svgenfloat_v
template<typename T >
constexpr bool is_mgenfloat_v
template<typename T >
constexpr bool is_gengeofloat_v = is_contained_v<T, gtl::geo_float_list>
template<typename T >
constexpr bool is_gengeodouble_v
template<typename T >
constexpr bool is_gengeomarrayfloat_v
template<typename T >
constexpr bool is_gengeomarray_v
template<typename T >
constexpr bool is_gengeohalf_v = is_contained_v<T, gtl::geo_half_list>
template<typename T >
constexpr bool is_vgengeofloat_v
template<typename T >
constexpr bool is_vgengeodouble_v
template<typename T >
constexpr bool is_vgengeohalf_v
template<typename T >
constexpr bool is_sgengeo_v = is_contained_v<T, gtl::scalar_geo_list>
template<typename T >
constexpr bool is_vgengeo_v = is_contained_v<T, gtl::vector_geo_list>
template<typename T >
constexpr bool is_gencrossfloat_v
template<typename T >
constexpr bool is_gencrossdouble_v
template<typename T >
constexpr bool is_gencrosshalf_v
template<typename T >
constexpr bool is_gencross_v
template<typename T >
constexpr bool is_gencrossmarray_v
template<typename T >
constexpr bool is_ugenint_v = is_contained_v<T, gtl::unsigned_int_list>
template<typename T >
constexpr bool is_intn_v
template<typename T >
constexpr bool is_genint_v = is_contained_v<T, gtl::signed_int_list>
template<typename T >
constexpr bool is_geninteger_v = is_contained_v<T, gtl::integer_list>
template<typename T >
constexpr bool is_igeninteger_v
template<typename T >
constexpr bool is_ugeninteger_v
template<typename T >
constexpr bool is_sgeninteger_v
template<typename T >
constexpr bool is_vgeninteger_v
template<typename T >
constexpr bool is_sigeninteger_v
template<typename T >
constexpr bool is_sugeninteger_v
template<typename T >
constexpr bool is_vigeninteger_v
template<typename T >
constexpr bool is_vugeninteger_v
template<typename T >
constexpr bool is_genbool_v = is_contained_v<T, gtl::bool_list>
template<typename T >
constexpr bool is_gentype_v = is_contained_v<T, gtl::basic_list>
template<typename T >
constexpr bool is_vgentype_v = is_contained_v<T, gtl::vector_basic_list>
template<typename T >
constexpr bool is_sgentype_v = is_contained_v<T, gtl::scalar_basic_list>
template<typename T >
constexpr bool is_igeninteger8bit_v
template<typename T >
constexpr bool is_igeninteger16bit_v
template<typename T >
constexpr bool is_igeninteger32bit_v
template<typename T >
constexpr bool is_igeninteger64bit_v
template<typename T >
constexpr bool is_ugeninteger8bit_v
template<typename T >
constexpr bool is_ugeninteger16bit_v
template<typename T >
constexpr bool is_ugeninteger32bit_v
template<typename T >
constexpr bool is_ugeninteger64bit_v
template<typename T >
constexpr bool is_genintptr_v
template<typename T , access::address_space AddressSpace, access::decorated IsDecorated>
constexpr bool is_genintptr_marray_v
template<typename T >
constexpr bool is_genfloatptr_v
template<typename T , access::address_space AddressSpace, access::decorated IsDecorated>
constexpr bool is_genfloatptr_marray_v
template<typename T , typename TypeList >
constexpr bool is_contained_v = is_contained<T, TypeList>::value
template<class T >
constexpr bool is_fixed_size_group_v = is_fixed_size_group<T>::value
template<typename T >
constexpr bool is_generic_group_v = is_generic_group<T>::value
template<typename T >
constexpr bool is_ext_vector_v = is_ext_vector<T>::value
template<typename T , int N, template< typename > class S>
constexpr bool is_gen_based_on_type_sizeof_v
template<typename T >
constexpr bool is_vec_v = is_vec<T>::value
template<typename T >
constexpr bool is_marray_v = is_marray<T>::value
template<typename T >
constexpr bool is_scalar_arithmetic_v = is_scalar_arithmetic<T>::value
template<typename T >
constexpr bool is_boolean_v = is_boolean<T>::value
template<typename T >
constexpr bool is_pointer_v = is_pointer<T>::value
template<class T >
constexpr bool is_multi_ptr_v = is_multi_ptr<T>::value
template<class T >
constexpr bool is_non_legacy_multi_ptr_v
template<class T >
constexpr bool is_legacy_multi_ptr_v = is_legacy_multi_ptr<T>::value
template<typename T , typename SpaceList >
constexpr bool is_address_space_compliant_v
template<typename T0 , typename... Ts>
constexpr bool all_same_v = (... && std::is_same_v<T0, Ts>)
template<typename... Ts>
constexpr bool check_type_in_v = CheckTypeIn<Ts...>()
constexpr size_t MaxVecAlignment = 64
static constexpr int REJECT_DEVICE_SCORE = -1
static constexpr ext::oneapi::experimental::architecture min_intel_gpu_architecture
static constexpr ext::oneapi::experimental::architecture max_intel_gpu_architecture
static constexpr ext::oneapi::experimental::architecture min_nvidia_gpu_architecture
static constexpr ext::oneapi::experimental::architecture max_nvidia_gpu_architecture
static constexpr ext::oneapi::experimental::architecture min_amd_gpu_architecture
static constexpr ext::oneapi::experimental::architecture max_amd_gpu_architecture
static constexpr bool is_allowable_aot_mode
constexpr auto device_arch_compare_op_lt
constexpr auto device_arch_compare_op_le
constexpr auto device_arch_compare_op_gt
constexpr auto device_arch_compare_op_ge
constexpr UseToUseStringPair UseToUseStringMap []
template<typename F , typename SuggestedArgType >
decltype(member_ptr_helper(&F::operator())) argument_helper (int)
static constexpr FmtFlags Dec = 0x0001
static constexpr FmtFlags Hex = 0x0002
static constexpr FmtFlags Oct = 0x0004
static constexpr FmtFlags ShowBase = 0x0008
static constexpr FmtFlags ShowPos = 0x0010
static constexpr FmtFlags Fixed = 0x0020
static constexpr FmtFlags Scientific = 0x0040
static constexpr FmtFlags BaseField = Dec | Hex | Oct
static constexpr FmtFlags FloatField = Scientific | Fixed
constexpr size_t MAX_FLOATING_POINT_DIGITS = 24
constexpr size_t MAX_INTEGRAL_DIGITS = 23
constexpr const char * VEC_ELEMENT_DELIMITER = ", "
constexpr char VEC_OPEN_BRACE = '{'
constexpr char VEC_CLOSE_BRACE = '}'
constexpr size_t MAX_DIMENSIONS = 3
constexpr size_t MAX_ARRAY_SIZE
constexpr unsigned FLUSH_BUF_OFFSET_SIZE = 2
constexpr static access::address_space GlobalBufAS
constexpr static int GlobalBufDim = 1
constexpr static access::address_space GlobalOffsetAS
constexpr static int GlobalOffsetDim = 1
constexpr size_t MAX_ITEM_SIZE = 2 * MAX_ARRAY_SIZE + 20
constexpr char BackendNameKeyName [] = "BackendName"
constexpr char DeviceTypeKeyName [] = "DeviceType"
constexpr char DeviceVendorIdKeyName [] = "DeviceVendorId"
constexpr char DriverVersionKeyName [] = "DriverVersion"
constexpr char PlatformVersionKeyName [] = "PlatformVersion"
constexpr char DeviceNameKeyName [] = "DeviceName"
constexpr char PlatformNameKeyName [] = "PlatformName"
constexpr std::array< const char *, 7 > SupportedAllowListKeyNames
static thread_local detail::code_location GCodeLocTLS = {}
CodeLocation information slot in thread local storage.
constexpr bool ConfigFromEnvEnabled = true
constexpr bool ConfigFromFileEnabled = true
constexpr bool ConfigFromCompileDefEnabled = true
constexpr int MAX_CONFIG_NAME = 256
constexpr int MAX_CONFIG_VALUE = 1024
constexpr std::pair< const char *, oneapi_exp_arch > NvidiaAmdGPUArchitectures []
constexpr std::pair< const int, oneapi_exp_arch > IntelGPUArchitectures []
constexpr std::pair< const int, oneapi_exp_arch > IntelCPUArchitectures []
static constexpr int DbgProgMgr = 0
static const std::map< DeviceLibExt, std::pair< const char *, const char * > > DeviceLibNames
static const std::map< DeviceLibExt, const char * > DeviceLibExtensionStrs
static constexpr uint32_t ITTSpecConstId = 0xFF747469
static constexpr size_t MaxNumQueues = 256
Sets max number of queues supported by FPGA RT.
constexpr CUDAContextT DefaultContextType = CUDAContextT::custom
Default context type created for CUDA backend.
constexpr const char * SYCL_STREAM_NAME = "sycl"
constexpr const char * SYCL_PICALL_STREAM_NAME = "sycl.pi"
constexpr const char * SYCL_PIDEBUGCALL_STREAM_NAME = "sycl.pi.debug"
constexpr auto SYCL_MEM_ALLOC_STREAM_NAME
constexpr const char * SYCL_BUFFER_STREAM_NAME
constexpr const char * SYCL_IMAGE_STREAM_NAME = "sycl.experimental.image"
Typedef Documentation
__sycl_init_mem_for
template<class KernelName > using sycl::_V1::detail::__sycl_init_mem_for = typedef std::conditional_t<std::is_same_v<KernelName, auto_name>, auto_name, reduction::InitMemKrn<KernelName> >
A helper to pass undefined (sycl::detail::auto_name) names unmodified.
We must do that to avoid name collisions.
Definition at line 826 of file reduction.hpp.
__sycl_reduction_kernel
template<template< typename, reduction::strategy, typename... > class MainOrAux, class KernelName , reduction::strategy Strategy, class... Ts> using sycl::_V1::detail::__sycl_reduction_kernel = typedef std::conditional_t<std::is_same_v<KernelName, auto_name>, auto_name, MainOrAux<KernelName, Strategy, Ts...> >
A helper to pass undefined (sycl::detail::auto_name) names unmodified.
We must do that to avoid name collisions.
Definition at line 1216 of file reduction.hpp.
ABINeutralT_t
template<typename T > using sycl::_V1::detail::ABINeutralT_t = typedef typename ABINeutralT<T>::type
Definition at line 85 of file util.hpp.
AccessorImplPtr
typedef std::shared_ptr< AccessorImplHost > sycl::_V1::detail::AccessorImplPtr
Definition at line 516 of file accessor.hpp.
address_space_list
template<access::address_space... Values> using sycl::_V1::detail::address_space_list = typedef value_list<access::address_space, Values...>
Definition at line 62 of file type_list.hpp.
AllowListParsedT
using sycl::_V1::detail::AllowListParsedT = typedef std::vector<DeviceDescT>
Definition at line 23 of file allowlist.hpp.
change_base_type_t
template<typename T , typename B > using sycl::_V1::detail::change_base_type_t = typedef typename change_base_type<T, B>::type
Definition at line 209 of file type_traits.hpp.
change_elements_t
template<typename NewElemT , typename T > using sycl::_V1::detail::change_elements_t = typedef typename change_elements<NewElemT, T>::type
Definition at line 144 of file builtins_utils_vec.hpp.
CommandPtr
using sycl::_V1::detail::CommandPtr = typedef std::unique_ptr<Command>
Definition at line 192 of file scheduler.hpp.
const_if_const_AS
template<access::address_space AS, class DataT > using sycl::_V1::detail::const_if_const_AS = typedef DataT
Definition at line 510 of file type_traits.hpp.
ContextImplPtr
typedef std::shared_ptr< context_impl > sycl::_V1::detail::ContextImplPtr
Definition at line 32 of file event_impl.hpp.
ConvertToOpenCLType_t
template<typename T > using sycl::_V1::detail::ConvertToOpenCLType_t = typedef decltype(convertToOpenCLType(std::declval<T>()))
Definition at line 382 of file generic_type_traits.hpp.
copy_cv_qualifiers_t
template<typename T , typename R > using sycl::_V1::detail::copy_cv_qualifiers_t = typedef typename copy_cv_qualifiers<T, R>::type
Definition at line 126 of file type_traits.hpp.
DeviceDescT
using sycl::_V1::detail::DeviceDescT = typedef std::map<std::string, std::string>
Definition at line 22 of file allowlist.hpp.
DeviceImageImplPtr
using sycl::_V1::detail::DeviceImageImplPtr = typedef std::shared_ptr<device_image_impl>
Definition at line 86 of file kernel_bundle.hpp.
DeviceImplPtr
typedef std::shared_ptr< detail::device_impl > sycl::_V1::detail::DeviceImplPtr
Definition at line 66 of file program_manager.hpp.
DevImgSelectorImpl
using sycl::_V1::detail::DevImgSelectorImpl = typedef std::function<bool(const detail::DeviceImageImplPtr &DevImgImpl)>
Definition at line 554 of file kernel_bundle.hpp.
DSelectorInvocableType
using sycl::_V1::detail::DSelectorInvocableType = typedef std::function<int(const sycl::device &)>
Definition at line 122 of file device_selector.hpp.
empty_type_list
using sycl::_V1::detail::empty_type_list = typedef type_list<>
Definition at line 24 of file type_list.hpp.
EnableIfFP
template<class F , class T = void> using sycl::_V1::detail::EnableIfFP = typedef typename std::enable_if_t< detail::check_type_in_v<F, float, double, half, ext::oneapi::bfloat16>, T>
Definition at line 87 of file stream.hpp.
EnableIfImgAccDataT
template<typename DataT > using sycl::_V1::detail::EnableIfImgAccDataT = typedef typename std::enable_if_t<is_validImageDataT<DataT>::value, DataT>
Definition at line 122 of file image.hpp.
EnableIfOutputIteratorT
template<typename DataT > using sycl::_V1::detail::EnableIfOutputIteratorT = typedef std::enable_if_t< !std::is_pointer_v<DataT> >
Definition at line 37 of file common.hpp.
EnableIfOutputPointerT
template<typename DataT > using sycl::_V1::detail::EnableIfOutputPointerT = typedef std::enable_if_t< std::is_pointer_v<DataT> >
Definition at line 33 of file common.hpp.
EnableIfSwizzleVec
template<typename T > using sycl::_V1::detail::EnableIfSwizzleVec = typedef typename std::enable_if_t<IsSwizzleOp<T>::value, typename IsSwizzleOp<T>::Type>
Definition at line 762 of file stream.hpp.
EnableIfSYCL2020DeviceSelectorInvocable
template<typename DeviceSelector > using sycl::_V1::detail::EnableIfSYCL2020DeviceSelectorInvocable = typedef std::enable_if_t< std::is_invocable_r_v<int, DeviceSelector &, const device &> && !std::is_base_of_v<ext::oneapi::filter_selector, DeviceSelector> && !std::is_base_of_v<device_selector, DeviceSelector> >
Definition at line 140 of file device_selector.hpp.
EventImplPtr
typedef std::shared_ptr< event_impl > sycl::_V1::detail::EventImplPtr
Definition at line 43 of file cg.hpp.
find_same_size_type_t
template<typename TypeList , typename T > using sycl::_V1::detail::find_same_size_type_t = typedef find_type_t<TypeList, is_type_size_equal, T>
Definition at line 91 of file type_list.hpp.
find_twice_as_large_type_t
template<typename TypeList , typename T > using sycl::_V1::detail::find_twice_as_large_type_t = typedef find_type_t<TypeList, is_type_size_double_of, T>
Definition at line 94 of file type_list.hpp.
find_type_t
template<typename TypeList , template< typename, typename > class Comp, typename T > using sycl::_V1::detail::find_type_t = typedef typename find_type<TypeList, Comp, T>::type
Definition at line 88 of file type_list.hpp.
FmtFlags
using sycl::_V1::detail::FmtFlags = typedef unsigned int
Definition at line 47 of file stream.hpp.
FusionList
using sycl::_V1::detail::FusionList = typedef std::unique_ptr<KernelFusionCommand>
Definition at line 193 of file scheduler.hpp.
FusionMap
using sycl::_V1::detail::FusionMap = typedef std::unordered_map<QueueIdT, FusionList>
Definition at line 194 of file scheduler.hpp.
get_elem_type_t
template<typename T > using sycl::_V1::detail::get_elem_type_t = typedef typename get_elem_type<T>::type
Definition at line 197 of file type_traits.hpp.
get_fixed_sized_int_t
template<typename T > using sycl::_V1::detail::get_fixed_sized_int_t = typedef typename get_fixed_sized_int<T>::type
Definition at line 114 of file builtins_utils_scalar.hpp.
GlobalBufAccessorT
using sycl::_V1::detail::GlobalBufAccessorT = typedef accessor<char, 1, sycl::access::mode::read_write, sycl::access::target::device>
Definition at line 90 of file stream.hpp.
GlobalBufPtrType
using sycl::_V1::detail::GlobalBufPtrType = typedef typename detail::DecoratedType<char, GlobalBufAS>::type *
Definition at line 95 of file stream.hpp.
GlobalOffsetAccessorT
using sycl::_V1::detail::GlobalOffsetAccessorT = typedef accessor<unsigned, 1, sycl::access::mode::atomic, sycl::access::target::device>
Definition at line 99 of file stream.hpp.
GlobalOffsetPtrType
using sycl::_V1::detail::GlobalOffsetPtrType = typedef typename detail::DecoratedType<unsigned, GlobalBufAS>::type *
Definition at line 104 of file stream.hpp.
image_allocator
using sycl::_V1::detail::image_allocator = typedef aligned_allocator<byte>
Definition at line 40 of file image_impl.hpp.
int64_t
using sycl::_V1::detail::int64_t = typedef conditional<sizeof(long) == 8, long, long long>::type
Definition at line 35 of file kernel_desc.hpp.
int_constant
template<int V> using sycl::_V1::detail::int_constant = typedef std::integral_constant<int, V>
Definition at line 128 of file type_traits.hpp.
is_arithmetic_or_complex
template<typename T > using sycl::_V1::detail::is_arithmetic_or_complex = typedef std::integral_constant<bool, sycl::detail::is_complex<T>::value || sycl::detail::is_arithmetic<T>::value>
Definition at line 125 of file group_algorithm.hpp.
is_contained
template<typename T , typename TypeList > using sycl::_V1::detail::is_contained = typedef boost::mp11::mp_set_contains<TypeList, std::remove_cv_t<T> >
Definition at line 31 of file type_list.hpp.
is_empty_type_list
template<typename T > using sycl::_V1::detail::is_empty_type_list = typedef std::is_same<T, empty_type_list>
Definition at line 27 of file type_list.hpp.
is_float_to_float
template<typename T , typename R > using sycl::_V1::detail::is_float_to_float = typedef std::bool_constant<detail::is_floating_point<T>::value && detail::is_floating_point<R>::value>
Definition at line 122 of file vector_convert.hpp.
is_float_to_sint
template<typename T , typename R > using sycl::_V1::detail::is_float_to_sint = typedef std::bool_constant<detail::is_floating_point<T>::value && std::is_integral_v<R> && !std::is_unsigned_v<R> >
Definition at line 117 of file vector_convert.hpp.
is_float_to_uint
template<typename T , typename R > using sycl::_V1::detail::is_float_to_uint = typedef std::bool_constant<detail::is_floating_point<T>::value && std::is_unsigned_v<R> >
Definition at line 112 of file vector_convert.hpp.
is_geninteger
template<typename T > using sycl::_V1::detail::is_geninteger = typedef std::bool_constant<is_geninteger_v<T> >
Definition at line 142 of file generic_type_traits.hpp.
is_igeninteger
template<typename T > using sycl::_V1::detail::is_igeninteger = typedef std::bool_constant<is_igeninteger_v<T> >
Definition at line 149 of file generic_type_traits.hpp.
is_int_to_float
template<typename T , typename R > using sycl::_V1::detail::is_int_to_float = typedef std::bool_constant<std::is_integral_v<T> && detail::is_floating_point<R>::value>
Definition at line 108 of file vector_convert.hpp.
is_multiplies
template<typename T , typename BinaryOperation > using sycl::_V1::detail::is_multiplies = typedef std::integral_constant< bool, std::is_same_v<BinaryOperation, sycl::multiplies<std::remove_const_t<T> >> || std::is_same_v<BinaryOperation, sycl::multiplies<std::add_const_t<T> >> || std::is_same_v<BinaryOperation, sycl::multiplies<void> >>
Definition at line 109 of file group_algorithm.hpp.
is_one_of_spaces
template<access::address_space AddressSpace, typename ValueList > using sycl::_V1::detail::is_one_of_spaces = typedef is_contained_value<access::address_space, AddressSpace, ValueList>
Definition at line 65 of file type_list.hpp.
is_plus
template<typename T , typename BinaryOperation > using sycl::_V1::detail::is_plus = typedef std::integral_constant< bool, std::is_same_v<BinaryOperation, sycl::plus<std::remove_const_t<T> >> || std::is_same_v<BinaryOperation, sycl::plus<std::add_const_t<T> >> || std::is_same_v<BinaryOperation, sycl::plus<void> >>
Definition at line 101 of file group_algorithm.hpp.
is_plus_or_multiplies_if_complex
template<typename T , typename BinaryOperation > using sycl::_V1::detail::is_plus_or_multiplies_if_complex = typedef std::integral_constant< bool, (is_complex<T>::value ? (is_plus<T, BinaryOperation>::value || is_multiplies<T, BinaryOperation>::value) : std::true_type::value)>
Definition at line 137 of file group_algorithm.hpp.
is_sint_to_float
template<typename T , typename R > using sycl::_V1::detail::is_sint_to_float = typedef std::bool_constant<std::is_integral_v<T> && !std::is_unsigned_v<T> && detail::is_floating_point<R>::value>
Definition at line 98 of file vector_convert.hpp.
is_sint_to_from_uint
template<typename T , typename R > using sycl::_V1::detail::is_sint_to_from_uint = typedef std::bool_constant< (detail::is_sigeninteger_v<T> && detail::is_sugeninteger_v<R>) || (detail::is_sugeninteger_v<T> && detail::is_sigeninteger_v<R>)>
Definition at line 93 of file vector_convert.hpp.
is_sint_to_sint
template<typename T , typename R > using sycl::_V1::detail::is_sint_to_sint = typedef std::bool_constant<is_sigeninteger_v<T> && is_sigeninteger_v<R> >
Definition at line 85 of file vector_convert.hpp.
is_ugeninteger
template<typename T > using sycl::_V1::detail::is_ugeninteger = typedef std::bool_constant<is_ugeninteger_v<T> >
Definition at line 156 of file generic_type_traits.hpp.
is_uint_to_float
template<typename T , typename R > using sycl::_V1::detail::is_uint_to_float = typedef std::bool_constant<std::is_unsigned_v<T> && detail::is_floating_point<R>::value>
Definition at line 103 of file vector_convert.hpp.
is_uint_to_uint
template<typename T , typename R > using sycl::_V1::detail::is_uint_to_uint = typedef std::bool_constant<is_sugeninteger_v<T> && is_sugeninteger_v<R> >
Definition at line 89 of file vector_convert.hpp.
is_validImageDataT
template<typename T > using sycl::_V1::detail::is_validImageDataT = typedef typename detail::is_contained< T, type_list<vec<opencl::cl_int, 4>, vec<opencl::cl_uint, 4>, vec<opencl::cl_float, 4>, vec<opencl::cl_half, 4> >>::type
Definition at line 117 of file image.hpp.
IsBitAND
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsBitAND = typedef std::bool_constant<std::is_same_v<BinaryOperation, sycl::bit_and<T> > || std::is_same_v<BinaryOperation, sycl::bit_and<void> >>
Definition at line 49 of file known_identity.hpp.
IsBitOR
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsBitOR = typedef std::bool_constant<std::is_same_v<BinaryOperation, sycl::bit_or<T> > || std::is_same_v<BinaryOperation, sycl::bit_or<void> >>
Definition at line 54 of file known_identity.hpp.
IsBitXOR
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsBitXOR = typedef std::bool_constant<std::is_same_v<BinaryOperation, sycl::bit_xor<T> > || std::is_same_v<BinaryOperation, sycl::bit_xor<void> >>
Definition at line 59 of file known_identity.hpp.
IsFalseIdentityOp
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsFalseIdentityOp = typedef std::bool_constant<IsLogicalOR<T, BinaryOperation>::value>
Definition at line 119 of file known_identity.hpp.
IsKnownIdentityOp
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsKnownIdentityOp = typedef std::bool_constant<IsZeroIdentityOp<T, BinaryOperation>::value || IsOneIdentityOp<T, BinaryOperation>::value || IsOnesIdentityOp<T, BinaryOperation>::value || IsMinimumIdentityOp<T, BinaryOperation>::value || IsMaximumIdentityOp<T, BinaryOperation>::value || IsFalseIdentityOp<T, BinaryOperation>::value || IsTrueIdentityOp<T, BinaryOperation>::value>
Definition at line 128 of file known_identity.hpp.
IsLogicalAND
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsLogicalAND = typedef std::bool_constant< std::is_same_v<BinaryOperation, std::logical_and<T> > || std::is_same_v<BinaryOperation, std::logical_and<void> > || std::is_same_v<BinaryOperation, sycl::logical_and<T> > || std::is_same_v<BinaryOperation, sycl::logical_and<void> >>
Definition at line 64 of file known_identity.hpp.
IsLogicalOR
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsLogicalOR = typedef std::bool_constant<std::is_same_v<BinaryOperation, std::logical_or<T> > || std::is_same_v<BinaryOperation, std::logical_or<void> > || std::is_same_v<BinaryOperation, sycl::logical_or<T> > || std::is_same_v<BinaryOperation, sycl::logical_or<void> >>
Definition at line 71 of file known_identity.hpp.
IsMaximum
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsMaximum = typedef std::bool_constant<std::is_same_v<BinaryOperation, sycl::maximum<T> > || std::is_same_v<BinaryOperation, sycl::maximum<void> >>
Definition at line 44 of file known_identity.hpp.
IsMaximumIdentityOp
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsMaximumIdentityOp = typedef std::bool_constant<(is_genbool_v<T> || is_geninteger_v<T> || is_genfloat_v<T>)&&IsMaximum<T, BinaryOperation>::value>
Definition at line 113 of file known_identity.hpp.
IsMinimum
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsMinimum = typedef std::bool_constant<std::is_same_v<BinaryOperation, sycl::minimum<T> > || std::is_same_v<BinaryOperation, sycl::minimum<void> >>
Definition at line 39 of file known_identity.hpp.
IsMinimumIdentityOp
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsMinimumIdentityOp = typedef std::bool_constant<(is_genbool_v<T> || is_geninteger_v<T> || is_genfloat_v<T>)&&IsMinimum<T, BinaryOperation>::value>
Definition at line 107 of file known_identity.hpp.
IsMultiplies
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsMultiplies = typedef std::bool_constant<std::is_same_v<BinaryOperation, sycl::multiplies<T> > || std::is_same_v<BinaryOperation, sycl::multiplies<void> >>
Definition at line 34 of file known_identity.hpp.
IsOneIdentityOp
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsOneIdentityOp = typedef std::bool_constant<(is_genbool_v<T> || is_geninteger_v<T> || is_genfloat_v<T>)&&IsMultiplies<T, BinaryOperation>::value>
Definition at line 95 of file known_identity.hpp.
IsOnesIdentityOp
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsOnesIdentityOp = typedef std::bool_constant<(is_genbool_v<T> || is_geninteger_v<T>)&&IsBitAND<T, BinaryOperation>::value>
Definition at line 101 of file known_identity.hpp.
IsPlus
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsPlus = typedef std::bool_constant<std::is_same_v<BinaryOperation, sycl::plus<T> > || std::is_same_v<BinaryOperation, sycl::plus<void> >>
Definition at line 29 of file known_identity.hpp.
IsPropertyListT
template<typename T > using sycl::_V1::detail::IsPropertyListT = typedef typename std::is_base_of<PropertyListBase, T>
Definition at line 265 of file accessor.hpp.
IsReduOptForAtomic64Op
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsReduOptForAtomic64Op = typedef std::bool_constant<(IsPlus<T, BinaryOperation>::value || IsMinimum<T, BinaryOperation>::value || IsMaximum<T, BinaryOperation>::value) && is_sgenfloat_v<T> && sizeof(T) == 8>
Definition at line 113 of file reduction.hpp.
IsReduOptForFastAtomicFetch
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsReduOptForFastAtomicFetch = typedef std::bool_constant<((is_sgenfloat_v<T> && sizeof(T) == 4) || is_sgeninteger_v<T>)&&IsValidAtomicType<T>::value && (IsPlus<T, BinaryOperation>::value || IsMinimum<T, BinaryOperation>::value || IsMaximum<T, BinaryOperation>::value || IsBitOR<T, BinaryOperation>::value || IsBitXOR<T, BinaryOperation>::value || IsBitAND<T, BinaryOperation>::value)>
Definition at line 90 of file reduction.hpp.
IsReduOptForFastReduce
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsReduOptForFastReduce = typedef std::bool_constant<((is_sgeninteger_v<T> && (sizeof(T) == 4 || sizeof(T) == 8)) || is_sgenfloat_v<T>)&&(IsPlus<T, BinaryOperation>::value || IsMinimum<T, BinaryOperation>::value || IsMaximum<T, BinaryOperation>::value)>
Definition at line 129 of file reduction.hpp.
IsRunTimePropertyListT
template<typename T > using sycl::_V1::detail::IsRunTimePropertyListT = typedef typename std::is_same<ext::oneapi::accessor_property_list<>, T>
Definition at line 268 of file accessor.hpp.
IsTrueIdentityOp
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsTrueIdentityOp = typedef std::bool_constant<IsLogicalAND<T, BinaryOperation>::value>
Definition at line 124 of file known_identity.hpp.
IsValidCoordType
template<typename T > using sycl::_V1::detail::IsValidCoordType = typedef typename is_contained< T, boost::mp11::mp_unique<type_list<opencl::cl_int, opencl::cl_float, std::int32_t, float> >>::type
Definition at line 39 of file image_accessor_util.hpp.
IsValidDefaultOrder
template<memory_order Order> using sycl::_V1::detail::IsValidDefaultOrder = typedef std::bool_constant<Order == memory_order::relaxed || Order == memory_order::acq_rel || Order == memory_order::seq_cst>
Definition at line 52 of file atomic_ref.hpp.
IsZeroIdentityOp
template<typename T , class BinaryOperation > using sycl::_V1::detail::IsZeroIdentityOp = typedef std::bool_constant< ((is_genbool_v<T> || is_geninteger_v<T>)&&(IsPlus<T, BinaryOperation>::value || IsBitOR<T, BinaryOperation>::value || IsBitXOR<T, BinaryOperation>::value)) || (is_genfloat_v<T> && IsPlus<T, BinaryOperation>::value) || (isComplex<T>::value && IsPlus<T, BinaryOperation>::value)>
Definition at line 85 of file known_identity.hpp.
iterator_category_t
template<typename T > using sycl::_V1::detail::iterator_category_t = typedef typename std::iterator_traits<T>::iterator_category
Definition at line 23 of file stl_type_traits.hpp.
iterator_pointer_t
template<typename T > using sycl::_V1::detail::iterator_pointer_t = typedef typename std::iterator_traits<T>::pointer
Definition at line 29 of file stl_type_traits.hpp.
iterator_to_const_type_t
template<typename T > using sycl::_V1::detail::iterator_to_const_type_t = typedef std::is_const<std::remove_pointer_t<iterator_pointer_t<T> >>
Definition at line 32 of file stl_type_traits.hpp.
iterator_value_type_t
template<typename T > using sycl::_V1::detail::iterator_value_type_t = typedef typename std::iterator_traits<T>::value_type
Definition at line 26 of file stl_type_traits.hpp.
KernelArgMask
using sycl::_V1::detail::KernelArgMask = typedef std::vector<bool>
Definition at line 16 of file kernel_arg_mask.hpp.
KernelBundleImplPtr
typedef std::shared_ptr< kernel_bundle_impl > sycl::_V1::detail::KernelBundleImplPtr
Definition at line 152 of file kernel_bundle.hpp.
lambda_arg_type
template<typename F , typename SuggestedArgType > using sycl::_V1::detail::lambda_arg_type = typedef decltype(argument_helper<F, SuggestedArgType>(0))
Definition at line 204 of file handler.hpp.
LocalAccessorImplPtr
typedef std::shared_ptr< LocalAccessorImplHost > sycl::_V1::detail::LocalAccessorImplPtr
Definition at line 585 of file accessor.hpp.
LockGuard
using sycl::_V1::detail::LockGuard = typedef std::lock_guard<SpinLock>
Definition at line 36 of file global_handler.cpp.
make_floating_point_t
template<typename T > using sycl::_V1::detail::make_floating_point_t = typedef make_type_t<T, gtl::scalar_floating_list>
Definition at line 256 of file generic_type_traits.hpp.
make_larger_t
template<typename T > using sycl::_V1::detail::make_larger_t = typedef typename make_larger<T>::type
Definition at line 501 of file type_traits.hpp.
make_signed_t
template<typename T > using sycl::_V1::detail::make_signed_t = typedef typename make_signed<T>::type
Definition at line 238 of file type_traits.hpp.
make_singed_integer_t
template<typename T > using sycl::_V1::detail::make_singed_integer_t = typedef make_type_t<T, gtl::scalar_signed_integer_list>
Definition at line 259 of file generic_type_traits.hpp.
make_type_t
template<typename T , typename TL > using sycl::_V1::detail::make_type_t = typedef typename make_type_impl<T, TL>::type
Definition at line 456 of file type_traits.hpp.
make_unsigned_t
template<typename T > using sycl::_V1::detail::make_unsigned_t = typedef typename make_unsigned<T>::type
Definition at line 259 of file type_traits.hpp.
make_unsinged_integer_t
template<typename T > using sycl::_V1::detail::make_unsinged_integer_t = typedef make_type_t<T, gtl::scalar_unsigned_integer_list>
Definition at line 262 of file generic_type_traits.hpp.
marray_element_t
template<class T > using sycl::_V1::detail::marray_element_t = typedef typename T::value_type
Definition at line 154 of file type_traits.hpp.
memory_order
typedef sycl::memory_order sycl::_V1::detail::memory_order
Definition at line 38 of file atomic.hpp.
memory_scope
using sycl::_V1::detail::memory_scope = typedef sycl::memory_scope
Definition at line 31 of file atomic_ref.hpp.
native_op_list
template<typename T > using sycl::_V1::detail::native_op_list = typedef type_list<sycl::plus<T>, sycl::bit_or<T>, sycl::bit_xor<T>, sycl::bit_and<T>, sycl::maximum<T>, sycl::minimum<T>, sycl::multiplies<T>, sycl::logical_or<T>, sycl::logical_and<T> >
Definition at line 85 of file group_algorithm.hpp.
oneapi_exp_arch
using sycl::_V1::detail::oneapi_exp_arch = typedef sycl::ext::oneapi::experimental::architecture
Definition at line 562 of file device_info.hpp.
output_iterator_requirements
template<typename T > using sycl::_V1::detail::output_iterator_requirements = typedef std::void_t<iterator_category_t<T>, decltype(*std::declval<T>() = std::declval<iterator_value_type_t<T> >())>
Definition at line 38 of file stl_type_traits.hpp.
PlatformImplPtr
typedef std::shared_ptr< platform_impl > sycl::_V1::detail::PlatformImplPtr
Definition at line 31 of file context_impl.hpp.
PluginPtr
typedef std::shared_ptr< plugin > sycl::_V1::detail::PluginPtr
Definition at line 48 of file pi.hpp.
ProgramImplPtr
using sycl::_V1::detail::ProgramImplPtr = typedef std::shared_ptr<program_impl>
Definition at line 33 of file kernel_impl.hpp.
QueueIdT
using sycl::_V1::detail::QueueIdT = typedef std::hash<std::shared_ptr<detail::queue_impl> >::result_type
Definition at line 191 of file scheduler.hpp.
QueueImplPtr
typedef std::shared_ptr< detail::queue_impl > sycl::_V1::detail::QueueImplPtr
Definition at line 34 of file event_impl.hpp.
ReduTupleT
template<typename... Ts> using sycl::_V1::detail::ReduTupleT = typedef sycl::detail::tuple<Ts...>
Definition at line 144 of file reduction.hpp.
rel_t
template<typename DataT > using sycl::_V1::detail::rel_t = typedef typename std::conditional_t< sizeof(DataT) == sizeof(opencl::cl_char), opencl::cl_char, typename std::conditional_t< sizeof(DataT) == sizeof(opencl::cl_short), opencl::cl_short, typename std::conditional_t< sizeof(DataT) == sizeof(opencl::cl_int), opencl::cl_int, typename std::conditional_t<sizeof(DataT) == sizeof(opencl::cl_long), opencl::cl_long, bool> >> >
Definition at line 166 of file vector.hpp.
remove_pointer_t
template<typename T > using sycl::_V1::detail::remove_pointer_t = typedef typename remove_pointer<T>::type
Definition at line 422 of file type_traits.hpp.
Requirement
using sycl::_V1::detail::Requirement = typedef AccessorImplHost
Definition at line 210 of file accessor_impl.hpp.
same_size_signed_int_t
template<typename T > using sycl::_V1::detail::same_size_signed_int_t = typedef typename same_size_signed_int<T>::type
Definition at line 94 of file builtins_utils_scalar.hpp.
same_size_unsigned_int_t
template<typename T > using sycl::_V1::detail::same_size_unsigned_int_t = typedef typename same_size_unsigned_int<T>::type
Definition at line 105 of file builtins_utils_scalar.hpp.
SampledImageAccessorImplPtr
typedef std::shared_ptr< SampledImageAccessorImplHost > sycl::_V1::detail::SampledImageAccessorImplPtr
Definition at line 28 of file accessor_image.hpp.
select_apply_cl_scalar_t
template<typename T , typename T8 , typename T16 , typename T32 , typename T64 > using sycl::_V1::detail::select_apply_cl_scalar_t = typedef std::conditional_t< sizeof(T) == 1, T8, std::conditional_t<sizeof(T) == 2, T16, std::conditional_t<sizeof(T) == 4, T32, T64> >>
Definition at line 268 of file generic_type_traits.hpp.
select_apply_cl_t
template<typename _IN , typename T8 , typename T16 , typename T32 , typename T64 > using sycl::_V1::detail::select_apply_cl_t = typedef std::conditional_t< sizeof(_IN) == 1, T8, std::conditional_t<sizeof(_IN) == 2, T16, std::conditional_t<sizeof(_IN) == 4, T32, T64> >>
Definition at line 92 of file vector.hpp.
select_cl_scalar_complex_or_T_t
template<typename T > using sycl::_V1::detail::select_cl_scalar_complex_or_T_t = typedef typename select_cl_scalar_complex_or_T<T>::type
Definition at line 294 of file generic_type_traits.hpp.
select_cl_scalar_integral_signed_t
template<typename T > using sycl::_V1::detail::select_cl_scalar_integral_signed_t = typedef select_apply_cl_scalar_t<T, sycl::opencl::cl_char, sycl::opencl::cl_short, sycl::opencl::cl_int, sycl::opencl::cl_long>
Definition at line 275 of file generic_type_traits.hpp.
select_cl_scalar_integral_unsigned_t
template<typename T > using sycl::_V1::detail::select_cl_scalar_integral_unsigned_t = typedef select_apply_cl_scalar_t<T, sycl::opencl::cl_uchar, sycl::opencl::cl_ushort, sycl::opencl::cl_uint, sycl::opencl::cl_ulong>
Definition at line 280 of file generic_type_traits.hpp.
select_scalar_by_size_t
template<size_t Size, typename T8 , typename T16 , typename T32 , typename T64 > using sycl::_V1::detail::select_scalar_by_size_t = typedef std::conditional_t< Size == 1, T8, std::conditional_t< Size == 2, T16, std::conditional_t<Size == 4, T32, std::conditional_t<Size == 8, T64, void> >> >
Definition at line 39 of file builtins_utils_scalar.hpp.
SerializedObj
using sycl::_V1::detail::SerializedObj = typedef std::vector<unsigned char>
Definition at line 69 of file util.hpp.
simplify_if_swizzle_t
template<typename T > using sycl::_V1::detail::simplify_if_swizzle_t = typedef typename simplify_if_swizzle<T>::type
Definition at line 123 of file builtins_utils_scalar.hpp.
SpecConstRegistryT
using sycl::_V1::detail::SpecConstRegistryT = typedef std::map<std::string, spec_constant_impl>
Definition at line 43 of file spec_constant_impl.hpp.
StreamImplPtr
typedef std::shared_ptr< detail::stream_impl > sycl::_V1::detail::StreamImplPtr
Definition at line 50 of file commands.hpp.
sycl_memory_object_allocator
template<typename DataT > using sycl::_V1::detail::sycl_memory_object_allocator = typedef aligned_allocator<DataT>
Definition at line 22 of file sycl_mem_obj_allocator.hpp.
tail_t
template<typename T > using sycl::_V1::detail::tail_t = typedef typename T::tail
Definition at line 49 of file type_list.hpp.
tl_append
template<class... L> using sycl::_V1::detail::tl_append = typedef boost::mp11::mp_append<L...>
Definition at line 37 of file type_list.hpp.
tuple_element_t
template<std::size_t I, class T > using sycl::_V1::detail::tuple_element_t = typedef typename tuple_element<I, T>::type
Definition at line 55 of file tuple.hpp.
type_list
template<class... T> using sycl::_V1::detail::type_list = typedef boost::mp11::mp_list<T...>
Definition at line 22 of file type_list.hpp.
UnsampledImageAccessorImplPtr
typedef std::shared_ptr< UnsampledImageAccessorImplHost > sycl::_V1::detail::UnsampledImageAccessorImplPtr
Definition at line 26 of file accessor_image.hpp.
UseToUseStringPair
using sycl::_V1::detail::UseToUseStringPair = typedef std::pair<ext::oneapi::experimental::matrix::use, const char *>
Definition at line 44 of file matrix-unified-utils.hpp.
uuid_type
using sycl::_V1::detail::uuid_type = typedef std::array<unsigned char, 16>
Definition at line 121 of file type_traits.hpp.
vector_element_impl_t
template<typename T > using sycl::_V1::detail::vector_element_impl_t = typedef typename vector_element_impl<T>::type
Definition at line 141 of file type_traits.hpp.
vector_element_t
template<class T > using sycl::_V1::detail::vector_element_t = typedef typename vector_element<T>::type
Definition at line 152 of file type_traits.hpp.
Enumeration Type Documentation
backend_errc
enum sycl::_V1::detail::backend_errc : unsigned int strong
Definition at line 64 of file backend.hpp.
BlockingT
enum sycl::_V1::detail::BlockingT
Enumerator
NON_BLOCKING
BLOCKING
Definition at line 59 of file commands.hpp.
ConfigID
enum sycl::_V1::detail::ConfigID
Enumerator
START
END
Definition at line 52 of file config.hpp.
CUDAContextT
enum sycl::_V1::detail::CUDAContextT : char strong
Possible CUDA context types supported by PI CUDA backend TODO: Implement this as a property once there is an extension document.
Enumerator
primary
custom
Definition at line 63 of file queue_impl.hpp.
DataLessPropKind
enum sycl::_V1::detail::DataLessPropKind
Enumerator
BufferUseHostPtr
ImageUseHostPtr
QueueEnableProfiling
InOrder
NoInit
BufferUsePinnedHostMemory
UsePrimaryContext
InitializeToIdentity
UseDefaultStream
DiscardEvents
DeviceReadOnly
FusionPromotePrivate
FusionPromoteLocal
FusionNoBarrier
FusionEnable
FusionForce
QueuePriorityNormal
QueuePriorityLow
QueuePriorityHigh
GraphNoCycleCheck
QueueSubmissionBatched
QueueSubmissionImmediate
GraphAssumeDataOutlivesBuffer
GraphAssumeBufferOutlivesGraph
GraphDependOnAllLeaves
GraphUpdatable
GraphEnableProfiling
LastKnownDataLessPropKind
DataLessPropKindSize
Definition at line 24 of file property_helper.hpp.
DeviceLibExt
enum sycl::_V1::detail::DeviceLibExt : std::uint32_t strong
Enumerator
cl_intel_devicelib_assert
cl_intel_devicelib_math
cl_intel_devicelib_math_fp64
cl_intel_devicelib_complex
cl_intel_devicelib_complex_fp64
cl_intel_devicelib_cstring
cl_intel_devicelib_imf
cl_intel_devicelib_imf_fp64
cl_intel_devicelib_imf_bf16
cl_intel_devicelib_bfloat16
Definition at line 73 of file program_manager.hpp.
HandlerSubmissionState
enum sycl::_V1::detail::HandlerSubmissionState : std::uint8_t strong
Enumerator
NO_STATE
EXPLICIT_KERNEL_BUNDLE_STATE
SPEC_CONST_SET_STATE
Definition at line 25 of file handler_impl.hpp.
kernel_param_kind_t
enum sycl::_V1::detail::kernel_param_kind_t strong
Enumerator
kind_accessor
kind_std_layout
kind_sampler
kind_pointer
kind_specialization_constants_buffer
kind_stream
kind_invalid
Definition at line 38 of file kernel_desc.hpp.
PiApiKind
enum sycl::_V1::detail::PiApiKind strong
Enumerator
_PI_API
Definition at line 43 of file pi.hpp.
program_state
enum sycl::_V1::detail::program_state strong
Enumerator
none
compiled
linked
Definition at line 34 of file program_impl.hpp.
PropWithDataKind
enum sycl::_V1::detail::PropWithDataKind
Enumerator
BufferUseMutex
BufferContextBound
ImageUseMutex
ImageContextBound
BufferMemChannel
AccPropBufferLocation
QueueComputeIndex
GraphNodeDependencies
PropWithDataKindSize
Definition at line 59 of file property_helper.hpp.
QueueOrder
enum sycl::_V1::detail::QueueOrder
Enumerator
Ordered
OOO
Definition at line 68 of file queue_impl.hpp.
register_alloc_mode_enum
enum sycl::_V1::detail::register_alloc_mode_enum : uint32_t strong
Enumerator
automatic
large
Definition at line 20 of file kernel_properties.hpp.
WorkSizeGuarantees
enum sycl::_V1::detail::WorkSizeGuarantees strong
Enumerator
None
Equal
LessOrEqual
Definition at line 1424 of file reduction.hpp.
Function Documentation
__attribute__()
sycl::_V1::detail::__attribute__ ((destructor(110)))
Definition at line 366 of file global_handler.cpp.
References shutdown().
__SYCL2020_DEPRECATED()
template<typename T > struct sycl::_V1::detail::__SYCL2020_DEPRECATED ("This type isn't device copyable in SYCL 2020")
__SYCL_DEPRECATED()
template<register_alloc_mode_enum Mode> constexpr register_alloc_mode_key::value_t<Mode> register_alloc_mode sycl::_V1::detail::__SYCL_DEPRECATED ("register_alloc_mode is deprecated, " "use sycl::ext::intel::experimental::grf_size or " "sycl::ext::intel::experimental::grf_size_automatic") inline constexpr
accessModeFromConstness()
template<typename DataT > constexpr access::mode sycl::_V1::detail::accessModeFromConstness () constexpr
Definition at line 386 of file accessor.hpp.
References sycl::_V1::access::read, and sycl::_V1::access::read_write.
AccessModeToPi()
pi_mem_obj_access sycl::_V1::detail::AccessModeToPi (access::mode AccessorMode)
Definition at line 2270 of file commands.cpp.
References sycl::_V1::access::discard_write, PI_ACCESS_READ_ONLY, PI_ACCESS_READ_WRITE, PI_ACCESS_WRITE_ONLY, sycl::_V1::access::read, and sycl::_V1::access::write.
Referenced by SetArgBasedOnType().
accessModeToString()
static std::string sycl::_V1::detail::accessModeToString (access::mode Mode) static
Definition at line 154 of file commands.cpp.
References sycl::_V1::access::discard_read_write, sycl::_V1::access::discard_write, sycl::_V1::Mode, sycl::_V1::access::read, sycl::_V1::access::read_write, and sycl::_V1::access::write.
Referenced by sycl::_V1::detail::Command::emitEdgeEventForCommandDependence(), sycl::_V1::detail::EmptyCommand::printDot(), sycl::_V1::detail::ReleaseCommand::printDot(), sycl::_V1::detail::AllocaCommand::printDot(), sycl::_V1::detail::AllocaSubBufCommand::printDot(), sycl::_V1::detail::MapMemObject::printDot(), sycl::_V1::detail::UnMapMemObject::printDot(), sycl::_V1::detail::MemCpyCommand::printDot(), sycl::_V1::detail::MemCpyCommandHost::printDot(), sycl::_V1::detail::ExecCGCommand::printDot(), sycl::_V1::detail::UpdateHostRequirementCommand::printDot(), sycl::_V1::detail::KernelFusionCommand::printDot(), and sycl::_V1::detail::UpdateCommandBufferCommand::printDot().
addHostAccessorAndWait()
void sycl::_V1::detail::addHostAccessorAndWait (AccessorImplHost * Req)
Definition at line 36 of file accessor_impl.cpp.
References sycl::_V1::detail::Scheduler::addHostAccessor(), and sycl::_V1::detail::Scheduler::getInstance().
Referenced by addHostSampledImageAccessorAndWait(), and addHostUnsampledImageAccessorAndWait().
addHostSampledImageAccessorAndWait()
void sycl::_V1::detail::addHostSampledImageAccessorAndWait (SampledImageAccessorImplHost * Req)
Definition at line 46 of file accessor_impl.cpp.
References addHostAccessorAndWait().
addHostUnsampledImageAccessorAndWait()
void sycl::_V1::detail::addHostUnsampledImageAccessorAndWait (UnsampledImageAccessorImplHost * Req)
Definition at line 42 of file accessor_impl.cpp.
References addHostAccessorAndWait().
adjustNDRangePerKernel()
static void sycl::_V1::detail::adjustNDRangePerKernel (NDRDescT & NDR, sycl::detail::pi::PiKernel Kernel, const device_impl & DeviceImpl) static
Definition at line 2234 of file commands.cpp.
References sycl::_V1::detail::NDRDescT::Dims, get_kernel_device_specific_info(), sycl::_V1::detail::device_impl::getHandleRef(), sycl::_V1::detail::device_impl::getPlugin(), sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::detail::NDRDescT::LocalSize, sycl::_V1::detail::NDRDescT::NumWorkGroups, and sycl::_V1::detail::NDRDescT::set().
Referenced by SetKernelParamsAndLaunch().
affinityDomainToString()
std::string sycl::_V1::detail::affinityDomainToString (info::partition_affinity_domain AffinityDomain) inline
Definition at line 86 of file device_info.hpp.
References __SYCL_AFFINITY_DOMAIN_STRING_CASE.
Referenced by sycl::_V1::detail::device_impl::create_sub_devices().
allowable_aot_mode()
template<ext::oneapi::experimental::architecture... Archs> constexpr static bool sycl::_V1::detail::allowable_aot_mode () static constexpr
Definition at line 831 of file device_architecture.hpp.
References is_allowable_aot_mode.
amendDeviceAndSubDevices()
static std::vector<device> sycl::_V1::detail::amendDeviceAndSubDevices (backend PlatformBackend, std::vector< device > & DeviceList, ods_target_list * OdsTargetList, const std::vector< int > & original_indices, PlatformImplPtr PlatformImpl) static
Definition at line 350 of file platform_impl.cpp.
References sycl::_V1::all, sycl::_V1::info::all, std::cout, sycl::_V1::device::create_sub_devices(), sycl::_V1::detail::ods_target_list::get(), sycl::_V1::device::get_info(), sycl::_V1::info::next_partitionable, sycl::_V1::info::partition_by_affinity_domain, supportsAffinityDomain(), and supportsPartitionProperty().
Referenced by sycl::_V1::detail::platform_impl::get_devices().
append()
unsigned sycl::_V1::detail::append (char * Dst, const char * Src) inline
Definition at line 239 of file stream.hpp.
Referenced by ArrayToStr(), checkForInfNan(), ItemToStr(), VecToStr(), writeGroup(), writeHItem(), writeItem(), writeNDItem(), and writeNDRange().
appendCompileEnvironmentVariablesThatAppend()
static void sycl::_V1::detail::appendCompileEnvironmentVariablesThatAppend (std::string & CompileOpts) static
Definition at line 430 of file program_manager.cpp.
References sycl::_V1::detail::SYCLConfig< Config >::get().
Referenced by sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::ProgramManager::compile(), sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), and sycl::_V1::detail::ProgramManager::getOrCreateKernel().
appendCompileOptionsForGRFSizeProperties()
static void sycl::_V1::detail::appendCompileOptionsForGRFSizeProperties (std::string & CompileOpts, const RTDeviceBinaryImage & Img, bool IsEsimdImage) static
Definition at line 273 of file program_manager.cpp.
References sycl::_V1::detail::DeviceBinaryProperty::asUint32(), automatic, sycl::_V1::detail::RTDeviceBinaryImage::getProperty(), and large.
Referenced by appendCompileOptionsFromImage().
appendCompileOptionsFromImage()
static void sycl::_V1::detail::appendCompileOptionsFromImage (std::string & CompileOpts, const RTDeviceBinaryImage & Img, const std::vector< device > & Devs, const PluginPtr &) static
Definition at line 316 of file program_manager.cpp.
References all_of(), appendCompileOptionsForGRFSizeProperties(), sycl::_V1::ext_oneapi_level_zero, sycl::_V1::detail::SYCLConfig< Config >::get(), sycl::_V1::detail::RTDeviceBinaryImage::getCompileOptions(), getSyclObjImpl(), getUint32PropAsBool(), getUint32PropAsOptStr(), and sycl::_V1::opencl.
Referenced by applyOptionsFromImage(), and sycl::_V1::detail::ProgramManager::compile().
appendLinkEnvironmentVariablesThatAppend()
static void sycl::_V1::detail::appendLinkEnvironmentVariablesThatAppend (std::string & LinkOpts) static
Definition at line 439 of file program_manager.cpp.
References sycl::_V1::detail::SYCLConfig< Config >::get().
Referenced by sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), and sycl::_V1::detail::ProgramManager::link().
appendLinkOptionsFromImage()
static void sycl::_V1::detail::appendLinkOptionsFromImage (std::string & LinkOpts, const RTDeviceBinaryImage & Img) static
Definition at line 238 of file program_manager.cpp.
References sycl::_V1::detail::SYCLConfig< Config >::get(), and sycl::_V1::detail::RTDeviceBinaryImage::getLinkOptions().
Referenced by applyOptionsFromImage(), and sycl::_V1::detail::ProgramManager::link().
applyAllowList()
void sycl::_V1::detail::applyAllowList (std::vector< sycl::detail::pi::PiDevice > & PiDevices, sycl::detail::pi::PiPlatform PiPlatform, const PluginPtr & Plugin)
Definition at line 346 of file allowlist.cpp.
References BackendNameKeyName, deviceIsAllowed(), DeviceNameKeyName, DeviceTypeKeyName, DeviceVendorIdKeyName, DriverVersionKeyName, sycl::_V1::detail::platform_impl::getOrMakePlatformImpl(), getSyclBeMap(), parseAllowList(), PI_DEVICE_INFO_TYPE, piDeviceGetInfo(), PlatformNameKeyName, and PlatformVersionKeyName.
Referenced by sycl::_V1::detail::platform_impl::get_devices().
applyCompileOptionsFromEnvironment()
static void sycl::_V1::detail::applyCompileOptionsFromEnvironment (std::string & CompileOpts) static
Definition at line 458 of file program_manager.cpp.
References sycl::_V1::detail::SYCLConfig< Config >::get().
Referenced by applyOptionsFromEnvironment(), and sycl::_V1::detail::ProgramManager::compile().
applyFuncOnFilteredArgs()
void sycl::_V1::detail::applyFuncOnFilteredArgs (const KernelArgMask * EliminatedArgMask, std::vector< ArgDesc > & Args, std::function< void(detail::ArgDesc &Arg, int NextTrueIndex)> Func)
Definition at line 111 of file commands.cpp.
References sycl::_V1::detail::ArgDesc::MIndex.
Referenced by enqueueImpCommandBufferKernel(), SetKernelParamsAndLaunch(), and sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::updateImpl().
applyLinkOptionsFromEnvironment()
static void sycl::_V1::detail::applyLinkOptionsFromEnvironment (std::string & LinkOpts) static
Definition at line 468 of file program_manager.cpp.
References sycl::_V1::detail::SYCLConfig< Config >::get().
Referenced by applyOptionsFromEnvironment(), and sycl::_V1::detail::ProgramManager::link().
applyOptionsFromEnvironment()
static void sycl::_V1::detail::applyOptionsFromEnvironment (std::string & CompileOpts, std::string & LinkOpts) static
Definition at line 477 of file program_manager.cpp.
References applyCompileOptionsFromEnvironment(), and applyLinkOptionsFromEnvironment().
Referenced by sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), and sycl::_V1::detail::ProgramManager::getOrCreateKernel().
applyOptionsFromImage()
static void sycl::_V1::detail::applyOptionsFromImage (std::string & CompileOpts, std::string & LinkOpts, const RTDeviceBinaryImage & Img, const std::vector< device > & Devices, const PluginPtr & Plugin) static
Definition at line 449 of file program_manager.cpp.
References appendCompileOptionsFromImage(), and appendLinkOptionsFromImage().
Referenced by sycl::_V1::detail::ProgramManager::build(), and sycl::_V1::detail::ProgramManager::getBuiltPIProgram().
argument_helper()
template<typename F , typename SuggestedArgType > SuggestedArgType sycl::_V1::detail::argument_helper (...)
ArrayToStr()
template<int ArrayLength> unsigned sycl::_V1::detail::ArrayToStr (char * Buf, const array< ArrayLength > & Arr) inline
Definition at line 613 of file stream.hpp.
References append(), ScalarToStr(), VEC_CLOSE_BRACE, VEC_ELEMENT_DELIMITER, and VEC_OPEN_BRACE.
Referenced by ItemToStr(), writeArray(), writeGroup(), writeItem(), writeNDItem(), and writeNDRange().
associateReduAccsWithHandler()
template<typename... Reductions, size_t... Is> void sycl::_V1::detail::associateReduAccsWithHandler (handler & CGH, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... >)
Definition at line 2383 of file reduction.hpp.
Referenced by reduAuxCGFunc().
associateWithHandler() [1/3]
void sycl::_V1::detail::associateWithHandler (handler & CGH, AccessorBaseHost * Acc, access::target Target)
Definition at line 17 of file handler_proxy.cpp.
Referenced by sycl::_V1::handler::require().
associateWithHandler() [2/3]
void sycl::_V1::detail::associateWithHandler (handler & CGH, SampledImageAccessorBaseHost * Acc, image_target Target)
Definition at line 27 of file handler_proxy.cpp.
associateWithHandler() [3/3]
void sycl::_V1::detail::associateWithHandler (handler & CGH, UnsampledImageAccessorBaseHost * Acc, image_target Target)
Definition at line 22 of file handler_proxy.cpp.
build_impl()
std::shared_ptr< detail::kernel_bundle_impl > sycl::_V1::detail::build_impl (const kernel_bundle< bundle_state::input > & InputBundle, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 267 of file kernel_bundle.cpp.
builtin_default_host_impl()
template<typename FuncTy , typename... Ts> auto sycl::_V1::detail::builtin_default_host_impl (FuncTy F, const Ts &... x)
Definition at line 141 of file builtins.hpp.
References builtin_marray_impl().
builtin_delegate_to_scalar()
template<typename FuncTy , typename... Ts> auto sycl::_V1::detail::builtin_delegate_to_scalar (FuncTy F, const Ts &... x)
Definition at line 156 of file builtins.hpp.
References sycl::_V1::r.
builtin_marray_impl()
template<typename FuncTy , typename... Ts> auto sycl::_V1::detail::builtin_marray_impl (FuncTy F, const Ts &... x)
Definition at line 119 of file builtins.hpp.
References to_vec2().
Referenced by builtin_default_host_impl().
cast_AS()
template<typename ToT , typename FromT > ToT sycl::_V1::detail::cast_AS (FromT from) inline
Definition at line 330 of file access.hpp.
References sycl::_V1::access::ext_intel_global_device_space, sycl::_V1::access::ext_intel_global_host_space, sycl::_V1::access::generic_space, sycl::_V1::access::global_space, sycl::_V1::access::local_space, and sycl::_V1::access::private_space.
Referenced by sycl::_V1::nd_item< Dimensions >::async_work_group_copy().
cast_if_host_half() [1/2]
float sycl::_V1::detail::cast_if_host_half (half_impl::half val) inline
Definition at line 569 of file half_type.hpp.
cast_if_host_half() [2/2]
template<typename T > T sycl::_V1::detail::cast_if_host_half (T val) inline
Definition at line 567 of file half_type.hpp.
cgTypeToString()
static std::string_view sycl::_V1::detail::cgTypeToString (detail::CG::CGTYPE Type) static
Definition at line 1857 of file commands.cpp.
References sycl::_V1::detail::CG::AdviseUSM, sycl::_V1::detail::CG::Barrier, sycl::_V1::detail::CG::BarrierWaitlist, sycl::_V1::detail::CG::CodeplayHostTask, sycl::_V1::detail::CG::Copy2DUSM, sycl::_V1::detail::CG::CopyAccToAcc, sycl::_V1::detail::CG::CopyAccToPtr, sycl::_V1::detail::CG::CopyFromDeviceGlobal, sycl::_V1::detail::CG::CopyImage, sycl::_V1::detail::CG::CopyPtrToAcc, sycl::_V1::detail::CG::CopyToDeviceGlobal, sycl::_V1::detail::CG::CopyUSM, sycl::_V1::detail::CG::ExecCommandBuffer, sycl::_V1::detail::CG::Fill, sycl::_V1::detail::CG::Fill2DUSM, sycl::_V1::detail::CG::FillUSM, sycl::_V1::detail::CG::Kernel, sycl::_V1::detail::CG::Memset2DUSM, sycl::_V1::detail::CG::PrefetchUSM, sycl::_V1::detail::CG::ReadWriteHostPipe, sycl::_V1::detail::CG::SemaphoreSignal, sycl::_V1::detail::CG::SemaphoreWait, and sycl::_V1::detail::CG::UpdateHost.
Referenced by sycl::_V1::detail::ExecCGCommand::getTypeString().
check_kernel_lambda_takes_args()
template<typename F , typename... Args> static constexpr bool sycl::_V1::detail::check_kernel_lambda_takes_args () static constexpr
Definition at line 161 of file cg_types.hpp.
checkAllDevicesAreInContext()
static bool sycl::_V1::detail::checkAllDevicesAreInContext (const std::vector< device > & Devices, const context & Context) static
Definition at line 35 of file kernel_bundle_impl.hpp.
References all_of().
Referenced by has_kernel_bundle_impl(), and sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl().
checkAllDevicesHaveAspect()
static bool sycl::_V1::detail::checkAllDevicesHaveAspect (const std::vector< device > & Devices, aspect Aspect) static
Definition at line 43 of file kernel_bundle_impl.hpp.
References all_of().
Referenced by has_kernel_bundle_impl().
CheckAllSameOpType()
template<typename T , typename... Ts> constexpr bool sycl::_V1::detail::CheckAllSameOpType () constexpr
Definition at line 67 of file builtins_utils_scalar.hpp.
checkAny()
template<typename T , typename... Args> static bool sycl::_V1::detail::checkAny (const T Value, Args... Arguments) static
Definition at line 43 of file image_impl.cpp.
References checkAnyImpl().
checkAnyImpl() [1/2]
template<typename T , typename... Args> static bool sycl::_V1::detail::checkAnyImpl (T) static
Definition at line 33 of file image_impl.cpp.
Referenced by checkAny(), and checkAnyImpl().
checkAnyImpl() [2/2]
template<typename ValT , typename VarT , typename... Args> static bool sycl::_V1::detail::checkAnyImpl (ValT Value, VarT Variant, Args... Arguments) static
Definition at line 38 of file image_impl.cpp.
References checkAnyImpl().
checkDevSupportDeviceRequirements()
std::optional< sycl::exception > sycl::_V1::detail::checkDevSupportDeviceRequirements (const device & Dev, const RTDeviceBinaryImage & Img, const NDRDescT & NDRDesc)
TODO: Before intel/llvm#10620, the reqd_work_group_size attribute
Definition at line 2680 of file program_manager.cpp.
References sycl::_V1::detail::DeviceBinaryProperty::asByteArray(), sycl::_V1::detail::DeviceBinaryProperty::asUint32(), sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::begin(), checkDevSupportJointMatrix(), checkDevSupportJointMatrixMad(), sycl::_V1::detail::ByteArray::consume(), sycl::_V1::detail::NDRDescT::Dims, sycl::_V1::detail::ByteArray::dropBytes(), sycl::_V1::detail::ByteArray::empty(), sycl::_V1::detail::RTDeviceBinaryImage::PropertyRange::end(), std::get(), sycl::_V1::device::get_info(), getAspectNameStr(), sycl::_V1::detail::RTDeviceBinaryImage::getDeviceRequirements(), getUint32PropAsBool(), sycl::_V1::device::has(), sycl::_V1::kernel_not_supported, sycl::_V1::make_error_code(), multiply_with_overflow_check(), sycl::_V1::nd_range, and none_of().
Referenced by doesDevSupportDeviceRequirements(), and sycl::_V1::detail::ProgramManager::getBuiltPIProgram().
checkDevSupportJointMatrix()
std::optional<sycl::exception> sycl::_V1::detail::checkDevSupportJointMatrix (const std::string & JointMatrixProStr, const std::vector< ext::oneapi::experimental::matrix::combination > & SupportedMatrixCombinations)
Definition at line 2504 of file program_manager.cpp.
References convertMatrixUseStringToEnum(), isMatrixSupportedByHW(), sycl::_V1::kernel_not_supported, and sycl::_V1::make_error_code().
Referenced by checkDevSupportDeviceRequirements().
checkDevSupportJointMatrixMad()
std::optional<sycl::exception> sycl::_V1::detail::checkDevSupportJointMatrixMad (const std::string & JointMatrixProStr, const std::vector< ext::oneapi::experimental::matrix::combination > & SupportedMatrixCombinations)
Definition at line 2585 of file program_manager.cpp.
References convertMatrixTypeStringMatrixTypeEnumValue(), sycl::_V1::kernel_not_supported, and sycl::_V1::make_error_code().
Referenced by checkDevSupportDeviceRequirements().
CheckEventReadiness()
bool sycl::_V1::detail::CheckEventReadiness (const ContextImplPtr & Context, const EventImplPtr & SyclEventImplPtr)
Definition at line 719 of file scheduler.cpp.
checkForCircularDependency()
static bool sycl::_V1::detail::checkForCircularDependency (Command * Cmd, bool IsPartOfFusion, KernelFusionCommand * Fusion) static
Definition at line 1498 of file graph_builder.cpp.
References createsCircularDependency(), sycl::_V1::detail::Command::getPreparedDepsEvents(), sycl::_V1::detail::Command::getPreparedHostDepsEvents(), and sycl::_V1::detail::Command::MDeps.
Referenced by createsCircularDependency().
checkForInfNan() [1/3]
template<typename T > detail::enable_if_t< std::is_same<T, float>::value || std::is_same<T, double>::value, unsigned> sycl::_V1::detail::checkForInfNan (char * Buf, T Val)
Definition at line 309 of file stream.hpp.
References append(), isFastMathInf(), isFastMathNan(), isFastMathSignBit(), and sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by ScalarToStr().
checkForInfNan() [2/3]
template<typename T > std::enable_if_t<std::is_same_v<T, half>, unsigned> sycl::_V1::detail::checkForInfNan (char * Buf, T Val) inline
Definition at line 331 of file stream.hpp.
References append().
checkForInfNan() [3/3]
template<typename T > std::enable_if_t<std::is_same_v<T, ext::oneapi::bfloat16>, unsigned> sycl::_V1::detail::checkForInfNan (char * Buf, T Val) inline
Definition at line 351 of file stream.hpp.
References append().
checkHostUnifiedMemory()
static bool sycl::_V1::detail::checkHostUnifiedMemory (const ContextImplPtr & Ctx) static
Definition at line 680 of file graph_builder.cpp.
checkImageValueRange()
template<typename Param > static bool sycl::_V1::detail::checkImageValueRange (const std::vector< device > & Devices, const size_t Value) static
Definition at line 25 of file image_impl.cpp.
References all_of().
CheckJITCompilationForImage()
void sycl::_V1::detail::CheckJITCompilationForImage (const RTDeviceBinaryImage *const & Image, bool JITCompilationIsRequired)
Definition at line 959 of file program_manager.cpp.
References __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_FPGA, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_X86_64, pi_device_binary_struct::DeviceTargetSpec, and sycl::_V1::detail::RTDeviceBinaryImage::getRawData().
Referenced by sycl::_V1::detail::ProgramManager::getDeviceImage().
CheckSizeIn()
template<size_t N, size_t... Ns> constexpr bool sycl::_V1::detail::CheckSizeIn () constexpr
Definition at line 46 of file builtins_utils_scalar.hpp.
CheckTypeIn()
template<typename T , typename... Ts> constexpr bool sycl::_V1::detail::CheckTypeIn () constexpr
Definition at line 542 of file type_traits.hpp.
checkValueRange() [1/3]
template<int Dims> void sycl::_V1::detail::checkValueRange (const range< Dims > & R, const id< Dims > & O)
Definition at line 295 of file handler.hpp.
checkValueRange() [2/3]
template<int Dims, typename T > std::enable_if_t<std::is_same_v<T, range<Dims> > || std::is_same_v<T, id<Dims> > > sycl::_V1::detail::checkValueRange (const T & V)
Definition at line 276 of file handler.hpp.
checkValueRange() [3/3]
template<int Dims, typename T > std::enable_if_t<std::is_same_v<T, nd_range<Dims> > > sycl::_V1::detail::checkValueRange (const T & V)
Definition at line 313 of file handler.hpp.
codeToString()
std::string sycl::_V1::detail::codeToString (pi_int32 code) inline
Definition at line 153 of file common.hpp.
References stringifyErrorCode().
Referenced by sycl::_V1::detail::event_impl::associateWithQueue(), sycl::_V1::detail::event_impl::event_impl(), event_impl::get_profiling_info< info::event_profiling::command_end >(), event_impl::get_profiling_info< info::event_profiling::command_start >(), getPlugin(), sycl::_V1::detail::enqueue_kernel_launch::handleErrorOrWarning(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidValue(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), make_kernel(), make_kernel_bundle(), parseAllowList(), sycl::_V1::detail::plugin::reportPiError(), and SetArgBasedOnType().
combineAccessModes()
static access::mode sycl::_V1::detail::combineAccessModes (access::mode A, access::mode B) static
Combines two access modes into a single one that allows both.
Definition at line 82 of file graph_builder.cpp.
References sycl::_V1::access::discard_read_write, sycl::_V1::access::discard_write, sycl::_V1::access::read_write, and sycl::_V1::access::write.
Referenced by combineAccessModesOfReqs().
combineAccessModesOfReqs()
static void sycl::_V1::detail::combineAccessModesOfReqs (std::vector< Requirement * > & Reqs) static
Definition at line 920 of file graph_builder.cpp.
References combineAccessModes().
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::addCommandGraphUpdate().
compatibleWithDevice()
static bool sycl::_V1::detail::compatibleWithDevice (RTDeviceBinaryImage * BinImage, const device & Dev) static
Definition at line 1551 of file program_manager.cpp.
References sycl::_V1::detail::RTDeviceBinaryImage::getRawData(), getSyclObjImpl(), and piextDeviceSelectBinary().
Referenced by sycl::_V1::detail::ProgramManager::getDeviceImageFromBinaryImage().
compile_impl()
std::shared_ptr< detail::kernel_bundle_impl > sycl::_V1::detail::compile_impl (const kernel_bundle< bundle_state::input > & InputBundle, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 253 of file kernel_bundle.cpp.
concat_sequences() [1/4]
template<size_t I> constexpr std::index_sequence<I> sycl::_V1::detail::concat_sequences (std::index_sequence< I >) constexpr
Definition at line 2094 of file reduction.hpp.
concat_sequences() [2/4]
template<size_t... Is, size_t... Js> constexpr std::index_sequence<Is..., Js...> sycl::_V1::detail::concat_sequences (std::index_sequence< Is... > , std::index_sequence< Js... >) constexpr
Definition at line 2101 of file reduction.hpp.
concat_sequences() [3/4]
template<size_t... Is, size_t... Js, class... Rs> constexpr auto sycl::_V1::detail::concat_sequences (std::index_sequence< Is... > , std::index_sequence< Js... > , Rs...) constexpr
Definition at line 2107 of file reduction.hpp.
References concat_sequences().
concat_sequences() [4/4]
constexpr std::index_sequence sycl::_V1::detail::concat_sequences (std::index_sequence<>) constexpr
Definition at line 2088 of file reduction.hpp.
Referenced by concat_sequences(), and filterSequenceHelper().
ConcatArrays() [1/2]
template<typename T , std::size_t N1, std::size_t N2> constexpr std::array<T, N1 + N2> sycl::_V1::detail::ConcatArrays (const std::array< T, N1 > & A1, const std::array< T, N2 > & A2) constexpr
Definition at line 403 of file common.hpp.
References ConcatArrays().
ConcatArrays() [2/2]
template<typename T , std::size_t... Is1, std::size_t... Is2> constexpr std::array<T, sizeof...(Is1) + sizeof...(Is2)> sycl::_V1::detail::ConcatArrays (const std::array< T, sizeof...(Is1)> & A1, const std::array< T, sizeof...(Is2)> & A2, std::index_sequence< Is1... > , std::index_sequence< Is2... >) constexpr
Definition at line 397 of file common.hpp.
Referenced by ConcatArrays(), and sycl::_V1::detail::ArrayCreator< DataT, FlattenF, ArgT, ArgTN... >::Create().
construct_range()
template<int Dimensions> range<Dimensions> sycl::_V1::detail::construct_range (size_t * values) delete
construct_range< 1 >()
template<> range<1> sycl::_V1::detail::construct_range< 1 > (size_t * values) inline
Definition at line 535 of file device_info.hpp.
construct_range< 2 >()
template<> range<2> sycl::_V1::detail::construct_range< 2 > (size_t * values) inline
Definition at line 535 of file device_info.hpp.
construct_range< 3 >()
template<> range<3> sycl::_V1::detail::construct_range< 3 > (size_t * values) inline
Definition at line 535 of file device_info.hpp.
constructorNotification() [1/2]
void sycl::_V1::detail::constructorNotification (void * BufferObj, void * AccessorObj, access::target Target, access::mode Mode, const code_location & CodeLoc)
constructorNotification() [2/2]
void sycl::_V1::detail::constructorNotification (void * BufferObj, void * AccessorObj, sycl::access::target Target, sycl::access::mode Mode, const detail::code_location & CodeLoc)
Definition at line 50 of file accessor_impl.cpp.
References sycl::_V1::detail::XPTIRegistry::bufferAccessorNotification(), and sycl::_V1::Mode.
context_impl::get_backend_info< info::device::backend_version >()
template<> info::device::backend_version::return_type sycl::_V1::detail::context_impl::get_backend_info< info::device::backend_version > () const
Definition at line 289 of file context_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::ext_oneapi_level_zero.
context_impl::get_backend_info< info::device::version >()
template<> info::device::version::return_type sycl::_V1::detail::context_impl::get_backend_info< info::device::version > () const
Definition at line 272 of file context_impl.cpp.
References sycl::_V1::backend_mismatch, sycl::_V1::default_selector_v(), sycl::_V1::device::get_info(), sycl::_V1::opencl, and select_device().
context_impl::get_backend_info< info::platform::version >()
template<> info::platform::version::return_type sycl::_V1::detail::context_impl::get_backend_info< info::platform::version > () const
Definition at line 258 of file context_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::opencl.
context_impl::get_info< info::context::atomic_fence_order_capabilities >()
template<> std::vector<sycl::memory_order> sycl::_V1::detail::context_impl::get_info< info::context::atomic_fence_order_capabilities > () const
Definition at line 179 of file context_impl.cpp.
References sycl::_V1::detail::platform_impl::getHostPlatformImpl().
context_impl::get_info< info::context::atomic_fence_scope_capabilities >()
template<> std::vector<sycl::memory_scope> sycl::_V1::detail::context_impl::get_info< info::context::atomic_fence_scope_capabilities > () const
Definition at line 179 of file context_impl.cpp.
context_impl::get_info< info::context::atomic_memory_order_capabilities >()
template<> std::vector<sycl::memory_order> sycl::_V1::detail::context_impl::get_info< info::context::atomic_memory_order_capabilities > () const
Definition at line 179 of file context_impl.cpp.
context_impl::get_info< info::context::atomic_memory_scope_capabilities >()
template<> std::vector<sycl::memory_scope> sycl::_V1::detail::context_impl::get_info< info::context::atomic_memory_scope_capabilities > () const
Definition at line 179 of file context_impl.cpp.
context_impl::get_info< info::context::devices >()
template<> std::vector<sycl::device> sycl::_V1::detail::context_impl::get_info< info::context::devices > () const
Definition at line 179 of file context_impl.cpp.
context_impl::get_info< info::context::platform >()
template<> platform sycl::_V1::detail::context_impl::get_info< info::context::platform > () const
Definition at line 179 of file context_impl.cpp.
context_impl::get_info< info::context::reference_count >()
template<> uint32_t sycl::_V1::detail::context_impl::get_info< info::context::reference_count > () const
Definition at line 173 of file context_impl.cpp.
References getPlugin().
convert_from_abi_neutral()
template<typename ParamT > auto sycl::_V1::detail::convert_from_abi_neutral (ParamT && Info)
Definition at line 74 of file platform.hpp.
Referenced by sycl::_V1::device::get_info(), sycl::_V1::kernel::get_info(), and sycl::_V1::platform::get_info().
convert_to_abi_neutral()
template<typename ParamT > auto sycl::_V1::detail::convert_to_abi_neutral (ParamT && Info)
Definition at line 58 of file platform.hpp.
convertBackend()
backend sycl::_V1::detail::convertBackend (pi_platform_backend PiBackend)
Definition at line 49 of file backend.cpp.
References sycl::_V1::all, sycl::_V1::ext_oneapi_cuda, sycl::_V1::ext_oneapi_hip, sycl::_V1::ext_oneapi_level_zero, sycl::_V1::ext_oneapi_native_cpu, sycl::_V1::opencl, PI_EXT_PLATFORM_BACKEND_CUDA, PI_EXT_PLATFORM_BACKEND_ESIMD, PI_EXT_PLATFORM_BACKEND_HIP, PI_EXT_PLATFORM_BACKEND_LEVEL_ZERO, PI_EXT_PLATFORM_BACKEND_NATIVE_CPU, PI_EXT_PLATFORM_BACKEND_OPENCL, and PI_EXT_PLATFORM_BACKEND_UNKNOWN.
Referenced by sycl::_V1::detail::platform_impl::platform_impl().
convertChannelOrder() [1/2]
sycl::detail::pi::PiMemImageChannelOrder sycl::_V1::detail::convertChannelOrder (image_channel_order Order)
Definition at line 111 of file image_impl.cpp.
References sycl::_V1::a, sycl::_V1::abgr, sycl::_V1::argb, sycl::_V1::bgra, sycl::_V1::ext_oneapi_srgba, sycl::_V1::intensity, sycl::_V1::luminance, PI_IMAGE_CHANNEL_ORDER_A, PI_IMAGE_CHANNEL_ORDER_ABGR, PI_IMAGE_CHANNEL_ORDER_ARGB, PI_IMAGE_CHANNEL_ORDER_BGRA, PI_IMAGE_CHANNEL_ORDER_INTENSITY, PI_IMAGE_CHANNEL_ORDER_LUMINANCE, PI_IMAGE_CHANNEL_ORDER_R, PI_IMAGE_CHANNEL_ORDER_RA, PI_IMAGE_CHANNEL_ORDER_RG, PI_IMAGE_CHANNEL_ORDER_RGB, PI_IMAGE_CHANNEL_ORDER_RGBA, PI_IMAGE_CHANNEL_ORDER_RGBx, PI_IMAGE_CHANNEL_ORDER_RGx, PI_IMAGE_CHANNEL_ORDER_Rx, PI_IMAGE_CHANNEL_ORDER_sRGBA, sycl::_V1::r, sycl::_V1::ra, sycl::_V1::rg, sycl::_V1::rgb, sycl::_V1::rgba, sycl::_V1::rgbx, sycl::_V1::rgx, and sycl::_V1::rx.
Referenced by sycl::_V1::handler::ext_oneapi_copy(), sycl::_V1::ext::oneapi::experimental::get_image_num_channels(), and sycl::_V1::ext::oneapi::experimental::populate_pi_structs().
convertChannelOrder() [2/2]
image_channel_order sycl::_V1::detail::convertChannelOrder (sycl::detail::pi::PiMemImageChannelOrder Order)
Definition at line 149 of file image_impl.cpp.
References sycl::_V1::a, sycl::_V1::abgr, sycl::_V1::argb, sycl::_V1::bgra, sycl::_V1::ext_oneapi_srgba, sycl::_V1::intensity, sycl::_V1::luminance, PI_IMAGE_CHANNEL_ORDER_A, PI_IMAGE_CHANNEL_ORDER_ABGR, PI_IMAGE_CHANNEL_ORDER_ARGB, PI_IMAGE_CHANNEL_ORDER_BGRA, PI_IMAGE_CHANNEL_ORDER_INTENSITY, PI_IMAGE_CHANNEL_ORDER_LUMINANCE, PI_IMAGE_CHANNEL_ORDER_R, PI_IMAGE_CHANNEL_ORDER_RA, PI_IMAGE_CHANNEL_ORDER_RG, PI_IMAGE_CHANNEL_ORDER_RGB, PI_IMAGE_CHANNEL_ORDER_RGBA, PI_IMAGE_CHANNEL_ORDER_RGBx, PI_IMAGE_CHANNEL_ORDER_RGx, PI_IMAGE_CHANNEL_ORDER_Rx, PI_IMAGE_CHANNEL_ORDER_sRGBA, sycl::_V1::r, sycl::_V1::ra, sycl::_V1::rg, sycl::_V1::rgb, sycl::_V1::rgba, sycl::_V1::rgbx, sycl::_V1::rgx, and sycl::_V1::rx.
convertChannelType() [1/2]
sycl::detail::pi::PiMemImageChannelType sycl::_V1::detail::convertChannelType (image_channel_type Type)
Definition at line 187 of file image_impl.cpp.
References sycl::_V1::fp16, sycl::_V1::fp32, PI_IMAGE_CHANNEL_TYPE_FLOAT, PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8, PI_IMAGE_CHANNEL_TYPE_SNORM_INT16, PI_IMAGE_CHANNEL_TYPE_SNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT16, PI_IMAGE_CHANNEL_TYPE_UNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8, sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
Referenced by sycl::_V1::handler::ext_oneapi_copy(), sycl::_V1::ext::oneapi::experimental::get_image_channel_type(), and sycl::_V1::ext::oneapi::experimental::populate_pi_structs().
convertChannelType() [2/2]
image_channel_type sycl::_V1::detail::convertChannelType (sycl::detail::pi::PiMemImageChannelType Type)
Definition at line 225 of file image_impl.cpp.
References sycl::_V1::fp16, sycl::_V1::fp32, PI_IMAGE_CHANNEL_TYPE_FLOAT, PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8, PI_IMAGE_CHANNEL_TYPE_SNORM_INT16, PI_IMAGE_CHANNEL_TYPE_SNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT16, PI_IMAGE_CHANNEL_TYPE_UNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8, sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
convertFromOpenCLTypeFor()
template<typename To , typename From > auto sycl::_V1::detail::convertFromOpenCLTypeFor (From && x)
Definition at line 384 of file generic_type_traits.hpp.
References convertToOpenCLType().
ConvertFToS()
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>, sycl::rounding_mode roundingMode> To sycl::_V1::detail::ConvertFToS (From Value)
Definition at line 161 of file vector_convert.hpp.
References sycl::automatic, sycl::_V1::make_error_code(), sycl::rte, sycl::rtn, sycl::rtp, sycl::rtz, and sycl::_V1::runtime.
ConvertFToU()
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>, sycl::rounding_mode roundingMode> To sycl::_V1::detail::ConvertFToU (From Value)
Definition at line 196 of file vector_convert.hpp.
convertImpl()
template<typename FromT , typename ToT , sycl::rounding_mode RoundingMode, int VecSize, typename NativeFromT , typename NativeToT > NativeToT sycl::_V1::detail::convertImpl (NativeFromT Value)
Entry point helper for all kinds of converts between scalars and vectors, it dispatches to a right function depending on source and destination types.
Template Parameters
FromT scalar user-visible type to convert from, used to detect conversion kind. It is expected to be DataT template argument of a vector we are trying to convert from
ToT scalar user-visible type to convert to, used to detect conversion kind. It is expected to be DataT template argument of a vector we are trying to convert to
NativeFromT scalar or vector internal type corresponding to FromT, which is used to hold vector data. It is expected to be vec<FromT, VecSize>::vector_t of a vector we are trying to convert from if VecSize > 1, or result of detail::ConvertToOpenCLType_t<FromT>
NativeToT scalar or vector internal type corresponding to ToT, which is used to hold vector data. It is expected to be vec<ToT, VecSize>::vector_t of a vector we are trying to convert from if VecSize > 1, or result of detail::ConvertToOpenCLType_t<ToT>
Note
Each pair of types FromT, ToT and NativeFromT, NativeToT can't contain the same type, because there are no no-op convert instructions in SPIR-V.
Definition at line 525 of file vector_convert.hpp.
convertMatrixTypeStringMatrixTypeEnumValue()
std::optional<matrix_ext::matrix_type> sycl::_V1::detail::convertMatrixTypeStringMatrixTypeEnumValue (const std::string & MatrixTypeString)
Definition at line 2448 of file program_manager.cpp.
Referenced by checkDevSupportJointMatrixMad(), and isMatrixSupportedByHW().
convertMatrixUseEnumToString()
constexpr const char* sycl::_V1::detail::convertMatrixUseEnumToString (ext::oneapi::experimental::matrix::use Use) constexpr
Definition at line 54 of file matrix-unified-utils.hpp.
References UseToUseStringMap.
convertMatrixUseStringToEnum()
constexpr std::optional<ext::oneapi::experimental::matrix::use> sycl::_V1::detail::convertMatrixUseStringToEnum (const char * UseString) constexpr
Definition at line 63 of file matrix-unified-utils.hpp.
References UseToUseStringMap.
Referenced by checkDevSupportJointMatrix().
convertReadData() [1/4]
template<typename ChannelType > void sycl::_V1::detail::convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, float4 & RetData)
Definition at line 334 of file image_accessor_util.hpp.
References sycl::_V1::fp16, sycl::_V1::fp32, sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
convertReadData() [2/4]
template<typename ChannelType > void sycl::_V1::detail::convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, half4 & RetData)
Definition at line 423 of file image_accessor_util.hpp.
References sycl::_V1::fp16, sycl::_V1::fp32, sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
convertReadData() [3/4]
template<typename ChannelType > void sycl::_V1::detail::convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, int4 & RetData)
Definition at line 312 of file image_accessor_util.hpp.
References sycl::_V1::signed_int16, sycl::_V1::signed_int32, and sycl::_V1::signed_int8.
convertReadData() [4/4]
template<typename ChannelType > void sycl::_V1::detail::convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, uint4 & RetData)
Definition at line 290 of file image_accessor_util.hpp.
References sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
ConvertSToF()
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>> To sycl::_V1::detail::ConvertSToF (From Value)
Definition at line 141 of file vector_convert.hpp.
convertToArrayOfN()
template<int NewDim, int DefaultValue, template< int > class T, int OldDim> static T<NewDim> sycl::_V1::detail::convertToArrayOfN (T< OldDim > OldObj) static
Definition at line 384 of file common.hpp.
Referenced by sycl::_V1::detail::image_common< Dimensions, AllocatorT >::get_pitch(), and sycl::_V1::image< Dimensions, AllocatorT >::get_pitch().
convertToFloat4() [1/3]
template<typename T > std::enable_if_t<IsValidCoordType<T>::value, float4> sycl::_V1::detail::convertToFloat4 (T Coords)
Definition at line 69 of file image_accessor_util.hpp.
Referenced by imageReadSamplerHostImpl().
convertToFloat4() [2/3]
template<typename T > std::enable_if_t<IsValidCoordType<T>::value, float4> sycl::_V1::detail::convertToFloat4 (vec< T, 2 > Coords)
Definition at line 75 of file image_accessor_util.hpp.
convertToFloat4() [3/3]
template<typename T > std::enable_if_t<IsValidCoordType<T>::value, float4> sycl::_V1::detail::convertToFloat4 (vec< T, 4 > Coords)
Definition at line 82 of file image_accessor_util.hpp.
convertToOpenCLType()
template<typename T > auto sycl::_V1::detail::convertToOpenCLType (T && x)
Definition at line 297 of file generic_type_traits.hpp.
Referenced by convertFromOpenCLTypeFor(), sycl::_V1::detail::sub_group::convertToBlockPtr(), sycl::_V1::ext::oneapi::sub_group_mask::count(), sycl::_V1::ext::oneapi::experimental::native::exp2(), and sycl::_V1::ext::oneapi::experimental::native::tanh().
convertTypeToMatrixTypeString()
template<typename T > constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString () constexpr
Definition at line 51 of file query-types.hpp.
convertTypeToMatrixTypeString< double >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< double > () constexpr
Definition at line 70 of file query-types.hpp.
convertTypeToMatrixTypeString< float >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< float > () constexpr
Definition at line 67 of file query-types.hpp.
convertTypeToMatrixTypeString< int16_t >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< int16_t > () constexpr
Definition at line 76 of file query-types.hpp.
convertTypeToMatrixTypeString< int32_t >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< int32_t > () constexpr
Definition at line 79 of file query-types.hpp.
convertTypeToMatrixTypeString< int64_t >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< int64_t > () constexpr
Definition at line 82 of file query-types.hpp.
convertTypeToMatrixTypeString< int8_t >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< int8_t > () constexpr
Definition at line 73 of file query-types.hpp.
convertTypeToMatrixTypeString< sycl::ext::oneapi::bfloat16 >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< sycl::ext::oneapi::bfloat16 > () constexpr
Definition at line 55 of file query-types.hpp.
convertTypeToMatrixTypeString< sycl::ext::oneapi::experimental::matrix::precision::tf32 >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< sycl::ext::oneapi::experimental::matrix::precision::tf32 > () constexpr
Definition at line 63 of file query-types.hpp.
convertTypeToMatrixTypeString< sycl::half >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< sycl::half > () constexpr
Definition at line 59 of file query-types.hpp.
convertTypeToMatrixTypeString< uint16_t >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< uint16_t > () constexpr
Definition at line 88 of file query-types.hpp.
convertTypeToMatrixTypeString< uint32_t >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< uint32_t > () constexpr
Definition at line 91 of file query-types.hpp.
convertTypeToMatrixTypeString< uint64_t >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< uint64_t > () constexpr
Definition at line 94 of file query-types.hpp.
convertTypeToMatrixTypeString< uint8_t >()
template<> constexpr const char* sycl::_V1::detail::convertTypeToMatrixTypeString< uint8_t > () constexpr
Definition at line 85 of file query-types.hpp.
ConvertUToF()
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>> To sycl::_V1::detail::ConvertUToF (From Value)
Definition at line 147 of file vector_convert.hpp.
convertWriteData() [1/4]
template<typename ChannelType > vec<ChannelType, 4> sycl::_V1::detail::convertWriteData (const float4 WriteData, const image_channel_type ImageChannelType)
Definition at line 562 of file image_accessor_util.hpp.
References sycl::_V1::fp16, sycl::_V1::fp32, sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
convertWriteData() [2/4]
template<typename ChannelType > vec<ChannelType, 4> sycl::_V1::detail::convertWriteData (const half4 WriteData, const image_channel_type ImageChannelType)
Definition at line 640 of file image_accessor_util.hpp.
References sycl::_V1::fp16, sycl::_V1::fp32, sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
convertWriteData() [3/4]
template<typename ChannelType > vec<ChannelType, 4> sycl::_V1::detail::convertWriteData (const int4 WriteData, const image_channel_type ImageChannelType)
Definition at line 520 of file image_accessor_util.hpp.
References sycl::_V1::signed_int16, sycl::_V1::signed_int32, and sycl::_V1::signed_int8.
convertWriteData() [4/4]
template<typename ChannelType > vec<ChannelType, 4> sycl::_V1::detail::convertWriteData (const uint4 WriteData, const image_channel_type ImageChannelType)
Definition at line 487 of file image_accessor_util.hpp.
References sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
copyD2D()
void sycl::_V1::detail::copyD2D (SYCLMemObjI * SYCLMemObj, sycl::detail::pi::PiMem SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, sycl::detail::pi::PiMem DstMem, QueueImplPtr , unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > , sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent, const detail::EventImplPtr & OutEventImpl)
Definition at line 659 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::getType(), piEnqueueMemBufferCopy(), piEnqueueMemBufferCopyRect(), piEnqueueMemImageCopy(), prepTermPositions(), sycl::_V1::detail::TermPositions::XTerm, sycl::_V1::detail::TermPositions::YTerm, and sycl::_V1::detail::TermPositions::ZTerm.
Referenced by sycl::_V1::detail::MemoryManager::copy().
copyD2H()
void sycl::_V1::detail::copyD2H (SYCLMemObjI * SYCLMemObj, sycl::detail::pi::PiMem SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char * DstMem, QueueImplPtr , unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent, const detail::EventImplPtr & OutEventImpl)
Definition at line 576 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::getType(), PI_FALSE, piEnqueueMemBufferRead(), piEnqueueMemBufferReadRect(), prepTermPositions(), sycl::_V1::detail::TermPositions::XTerm, sycl::_V1::detail::TermPositions::YTerm, and sycl::_V1::detail::TermPositions::ZTerm.
Referenced by sycl::_V1::detail::MemoryManager::copy().
copyH2D()
void sycl::_V1::detail::copyH2D (SYCLMemObjI * SYCLMemObj, char * SrcMem, QueueImplPtr , unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, sycl::detail::pi::PiMem DstMem, QueueImplPtr TgtQueue, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > DepEvents, sycl::detail::pi::PiEvent & OutEvent, const detail::EventImplPtr & OutEventImpl)
Definition at line 498 of file memory_manager.cpp.
References sycl::_V1::detail::SYCLMemObjI::getType(), PI_FALSE, piEnqueueMemBufferWrite(), piEnqueueMemBufferWriteRect(), prepTermPositions(), sycl::_V1::detail::TermPositions::XTerm, sycl::_V1::detail::TermPositions::YTerm, and sycl::_V1::detail::TermPositions::ZTerm.
Referenced by sycl::_V1::detail::MemoryManager::copy().
copyH2H()
static void sycl::_V1::detail::copyH2H (SYCLMemObjI * , char * SrcMem, QueueImplPtr , unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char * DstMem, QueueImplPtr , unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< sycl::detail::pi::PiEvent > , sycl::detail::pi::PiEvent & , const detail::EventImplPtr &) static
Definition at line 737 of file memory_manager.cpp.
Referenced by sycl::_V1::detail::MemoryManager::copy().
createBinaryProgram()
static sycl::detail::pi::PiProgram sycl::_V1::detail::createBinaryProgram (const ContextImplPtr Context, const device & Device, const unsigned char * Data, size_t DataLen, const std::vector< pi_device_binary_property > Metadata) static
Definition at line 73 of file program_manager.cpp.
References getSyclObjImpl(), PI_CONTEXT_INFO_NUM_DEVICES, piContextGetInfo(), and piProgramCreateWithBinary().
Referenced by sycl::_V1::detail::ProgramManager::createPIProgram(), and sycl::_V1::detail::ProgramManager::getOrCreatePIProgram().
createDiscardedEvent()
static event sycl::_V1::detail::createDiscardedEvent () static
Definition at line 104 of file queue_impl.cpp.
References sycl::_V1::detail::event_impl::HES_Discarded.
Referenced by sycl::_V1::detail::queue_impl::discard_or_return(), sycl::_V1::detail::queue_impl::getLastEvent(), and sycl::_V1::detail::queue_impl::submitMemOpHelper().
createKernelArgMask()
KernelArgMask sycl::_V1::detail::createKernelArgMask (const ByteArray & Bytes) inline
Definition at line 17 of file kernel_arg_mask.hpp.
Referenced by sycl::_V1::detail::ProgramManager::addImages().
createReduOutAccs()
template<bool IsOneWG, typename... Reductions, size_t... Is> auto sycl::_V1::detail::createReduOutAccs (size_t NWorkGroups, handler & CGH, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... >)
For the given 'Reductions' types pack and indices enumerating them this function either creates new temporary accessors for partial sums (if IsOneWG is false) or returns user's accessor/USM-pointer if (IsOneWG is true).
Definition at line 2039 of file reduction.hpp.
References makeReduTupleT().
createsCircularDependency()
static bool sycl::_V1::detail::createsCircularDependency (Command * Cmd, bool PredPartOfFusion, KernelFusionCommand * Fusion) static
Definition at line 1483 of file graph_builder.cpp.
References checkForCircularDependency(), and isPartOfFusion().
Referenced by checkForCircularDependency().
createSpirvProgram()
static sycl::detail::pi::PiProgram sycl::_V1::detail::createSpirvProgram (const ContextImplPtr Context, const unsigned char * Data, size_t DataLen) static
Definition at line 103 of file program_manager.cpp.
References piProgramCreate().
Referenced by sycl::_V1::detail::ProgramManager::createPIProgram(), and loadDeviceLib().
createSyclObjFromImpl()
template<class T > T sycl::_V1::detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Definition at line 48 of file impl_utils.hpp.
Referenced by sycl::_V1::queue::ext_oneapi_get_graph(), and sycl::_V1::kernel::get_kernel_bundle().
D2I64()
unsigned long long sycl::_V1::detail::D2I64 (double Val) inline
Definition at line 258 of file stream.hpp.
Referenced by isFastMathInf(), isFastMathNan(), and isFastMathSignBit().
declptr()
template<typename T > T* sycl::_V1::detail::declptr ()
Definition at line 56 of file helpers.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED(), and sycl::_V1::ext::oneapi::this_work_item::get_nd_item().
deduceAccessMode()
template<typename MayBeTag1 , typename MayBeTag2 > constexpr access::mode sycl::_V1::detail::deduceAccessMode () constexpr
Definition at line 394 of file accessor.hpp.
References sycl::_V1::access::host_task, sycl::_V1::access::read, sycl::_V1::access::read_write, and sycl::_V1::access::write.
deduceAccessTarget()
template<typename MayBeTag1 , typename MayBeTag2 > constexpr access::target sycl::_V1::detail::deduceAccessTarget (access::target defaultTarget) constexpr
Definition at line 441 of file accessor.hpp.
References sycl::_V1::access::host_task, sycl::_V1::access::read, sycl::_V1::access::read_write, and sycl::_V1::access::write.
defaultAsyncHandler()
void sycl::_V1::detail::defaultAsyncHandler (exception_list Exceptions) inline
Definition at line 58 of file exception_list.hpp.
References std::cerr.
Referenced by sycl::_V1::ext::oneapi::level_zero::make_context(), and sycl::_V1::opencl::make_context().
demangleKernelName()
static std::string sycl::_V1::detail::demangleKernelName (std::string Name) static
Definition at line 95 of file commands.cpp.
Referenced by sycl::_V1::detail::ExecCGCommand::printDot(), and sycl::_V1::detail::KernelFusionCommand::printDot().
device_architecture_comparison_aot()
template<ext::oneapi::experimental::architecture Arch, typename Compare > constexpr static bool sycl::_V1::detail::device_architecture_comparison_aot (Compare comp) static constexpr
Definition at line 915 of file device_architecture.hpp.
References get_current_architecture_aot(), and get_device_architecture_category().
device_architecture_is()
template<ext::oneapi::experimental::architecture... Archs> constexpr static bool sycl::_V1::detail::device_architecture_is () static constexpr
Definition at line 838 of file device_architecture.hpp.
References is_aot_for_architecture().
device_architecture_is_in_categories()
template<ext::oneapi::experimental::arch_category... Categories> constexpr static bool sycl::_V1::detail::device_architecture_is_in_categories () static constexpr
Definition at line 887 of file device_architecture.hpp.
device_architecture_is_in_category_aot()
template<ext::oneapi::experimental::arch_category Category> constexpr static bool sycl::_V1::detail::device_architecture_is_in_category_aot () static constexpr
Definition at line 869 of file device_architecture.hpp.
References get_category_max_architecture(), get_category_min_architecture(), and get_current_architecture_aot().
device_impl::get_backend_info< info::device::backend_version >()
template<> info::device::backend_version::return_type sycl::_V1::detail::device_impl::get_backend_info< info::device::backend_version > () const
Definition at line 169 of file device_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::ext_oneapi_level_zero.
device_impl::get_backend_info< info::device::version >()
template<> info::device::version::return_type sycl::_V1::detail::device_impl::get_backend_info< info::device::version > () const
Definition at line 158 of file device_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::opencl.
device_impl::get_backend_info< info::platform::version >()
template<> info::platform::version::return_type sycl::_V1::detail::device_impl::get_backend_info< info::platform::version > () const
Definition at line 147 of file device_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::opencl.
deviceIsAllowed()
bool sycl::_V1::detail::deviceIsAllowed (const DeviceDescT & DeviceDesc, const AllowListParsedT & AllowListParsed)
Definition at line 292 of file allowlist.cpp.
References all_of(), BackendNameKeyName, DeviceNameKeyName, DeviceTypeKeyName, DeviceVendorIdKeyName, DriverVersionKeyName, PlatformNameKeyName, PlatformVersionKeyName, and SupportedAllowListKeyNames.
Referenced by applyAllowList().
deviceToString()
static std::string sycl::_V1::detail::deviceToString (device Device) static
Definition at line 98 of file commands.cpp.
References getSyclObjImpl(), sycl::_V1::device::is_accelerator(), sycl::_V1::device::is_cpu(), and sycl::_V1::device::is_gpu().
Referenced by sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), sycl::_V1::detail::UnMapMemObject::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::printDot(), sycl::_V1::detail::AllocaCommand::printDot(), sycl::_V1::detail::AllocaSubBufCommand::printDot(), sycl::_V1::detail::MapMemObject::printDot(), sycl::_V1::detail::UnMapMemObject::printDot(), sycl::_V1::detail::MemCpyCommand::printDot(), sycl::_V1::detail::MemCpyCommandHost::printDot(), sycl::_V1::detail::ExecCGCommand::printDot(), sycl::_V1::detail::UpdateHostRequirementCommand::printDot(), and sycl::_V1::detail::KernelFusionCommand::printDot().
digitToChar()
char sycl::_V1::detail::digitToChar (const int Digit) inline
Definition at line 169 of file stream.hpp.
Referenced by floatingPointToDecStr(), and integralToBase().
DispatchNativeKernel()
void sycl::_V1::detail::DispatchNativeKernel (void * Blob)
Definition at line 2431 of file commands.cpp.
References sycl::_V1::detail::AccessorImplHost::MData.
doesDevSupportDeviceRequirements()
bool sycl::_V1::detail::doesDevSupportDeviceRequirements (const device & Dev, const RTDeviceBinaryImage & Img)
Definition at line 2405 of file program_manager.cpp.
References checkDevSupportDeviceRequirements().
doOverlap() [1/2]
static bool sycl::_V1::detail::doOverlap (const Requirement * LHS, const Requirement * RHS) static
Checks whether two requirements overlap or not.
This information can be used to prove that executing two kernels that work on different parts of the memory object in parallel is legal.
Definition at line 45 of file graph_builder.cpp.
References sycl::_V1::detail::AccessorImplHost::MAccessRange, sycl::_V1::detail::AccessorImplHost::MElemSize, sycl::_V1::detail::AccessorImplHost::MOffsetInBytes, and sycl::_V1::range< Dimensions >::size().
doOverlap() [2/2]
static bool sycl::_V1::detail::doOverlap (const Requirement * LHS, const Requirement * RHS) inline static
Definition at line 19 of file leaves_collection.cpp.
References sycl::_V1::detail::AccessorImplHost::MAccessRange, sycl::_V1::detail::AccessorImplHost::MElemSize, sycl::_V1::detail::AccessorImplHost::MOffsetInBytes, and sycl::_V1::range< Dimensions >::size().
doTreeReduction()
template<WorkSizeGuarantees WSGuarantee, int Dim, typename LocalRedsTy , typename BinOpTy , typename AccessFuncTy > void sycl::_V1::detail::doTreeReduction (size_t WorkSize, nd_item< Dim > NDIt, LocalRedsTy & LocalReds, BinOpTy & BOp, AccessFuncTy AccessFunc)
Definition at line 1428 of file reduction.hpp.
References doTreeReductionHelper(), Equal, sycl::_V1::nd_item< Dimensions >::get_local_linear_id(), sycl::_V1::nd_item< Dimensions >::get_local_range(), LessOrEqual, and sycl::_V1::range< Dimensions >::size().
doTreeReductionHelper()
template<typename FuncTy > void sycl::_V1::detail::doTreeReductionHelper (size_t WorkSize, size_t LID, FuncTy Func)
Definition at line 1394 of file reduction.hpp.
References GreatestPowerOfTwo(), and workGroupBarrier().
Referenced by doTreeReduction(), and doTreeReductionOnTuple().
doTreeReductionOnTuple()
template<typename... LocalAccT, typename... BOPsT, size_t... Is> void sycl::_V1::detail::doTreeReductionOnTuple (size_t WorkSize, size_t LID, ReduTupleT< LocalAccT... > & LocalAccs, ReduTupleT< BOPsT... > & BOPs, std::index_sequence< Is... >)
Definition at line 1463 of file reduction.hpp.
References doTreeReductionHelper().
Referenced by reduAuxCGFuncImplScalar(), and reduCGFuncImplScalar().
dumpConfig()
void sycl::_V1::detail::dumpConfig ()
Definition at line 153 of file config.cpp.
emitBuiltProgramInfo()
static void sycl::_V1::detail::emitBuiltProgramInfo (const pi_program & Prog, const ContextImplPtr & Context) static
Emits information about built programs if the appropriate contitions are met, namely when SYCL_RT_WARNING_LEVEL is greater than or equal to 2.
Definition at line 512 of file program_manager.cpp.
References std::clog, and sycl::_V1::detail::ProgramManager::getProgramBuildLog().
Referenced by sycl::_V1::detail::ProgramManager::build(), and sycl::_V1::detail::ProgramManager::getBuiltPIProgram().
emitMemAllocBeginTrace()
uint64_t sycl::_V1::detail::emitMemAllocBeginTrace (uintptr_t ObjHandle, size_t AllocSize, size_t GuardZone)
Definition at line 42 of file memory_manager.cpp.
Referenced by memBufferCreateHelper(), and memBufferMapHelper().
emitMemAllocEndTrace()
void sycl::_V1::detail::emitMemAllocEndTrace (uintptr_t ObjHandle, uintptr_t AllocPtr, size_t AllocSize, size_t GuardZone, uint64_t CorrelationID)
Definition at line 63 of file memory_manager.cpp.
Referenced by memBufferCreateHelper(), and memBufferMapHelper().
emitMemReleaseBeginTrace()
uint64_t sycl::_V1::detail::emitMemReleaseBeginTrace (uintptr_t ObjHandle, uintptr_t AllocPtr)
Definition at line 83 of file memory_manager.cpp.
Referenced by memReleaseHelper(), and memUnmapHelper().
emitMemReleaseEndTrace()
void sycl::_V1::detail::emitMemReleaseEndTrace (uintptr_t ObjHandle, uintptr_t AllocPtr, uint64_t CorrelationID)
Definition at line 102 of file memory_manager.cpp.
Referenced by memReleaseHelper(), and memUnmapHelper().
enable_ext_oneapi_default_context()
void sycl::_V1::detail::enable_ext_oneapi_default_context (bool Val)
Allows to enable/disable "Default Context" extension.
This API is in detail:: namespace because it's never supposed to be called by end-user. It's necessary for internal use of oneAPI components
Parameters
Val Indicates if extension should be enabled/disabled
Definition at line 150 of file platform.cpp.
enableITTAnnotationsIfNeeded()
static void sycl::_V1::detail::enableITTAnnotationsIfNeeded (const sycl::detail::pi::PiProgram & Prog, const PluginPtr & Plugin) static
This function enables ITT annotations in SPIR-V module by setting a specialization constant if INTEL_LIBITTNOTIFY64 env variable is set.
Definition at line 59 of file program_manager.cpp.
References ITTSpecConstId, and piextProgramSetSpecializationConstant().
Referenced by sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), and setSpecializationConstants().
enableOnCrashStackPrinting()
static void sycl::_V1::detail::enableOnCrashStackPrinting () static
Definition at line 147 of file global_handler.cpp.
Referenced by sycl::_V1::detail::GlobalHandler::getPlugins(), and sycl::_V1::detail::GlobalHandler::getScheduler().
enqueueImpCommandBufferKernel()
pi_int32 sycl::_V1::detail::enqueueImpCommandBufferKernel (context Ctx, DeviceImplPtr DeviceImpl, sycl::detail::pi::PiExtCommandBuffer CommandBuffer, const CGExecKernel & CommandGroup, std::vector< sycl::detail::pi::PiExtSyncPoint > & SyncPoints, sycl::detail::pi::PiExtSyncPoint * OutSyncPoint, sycl::detail::pi::PiExtCommandBufferCommand * OutCommand, const std::function< void *(Requirement *Req)> & getMemAllocationFunc)
Definition at line 2455 of file commands.cpp.
References applyFuncOnFilteredArgs(), sycl::_V1::detail::NDRDescT::Dims, sycl::_V1::detail::ProgramManager::getInstance(), sycl::_V1::detail::ProgramManager::getSYCLKernelID(), getSyclObjImpl(), sycl::_V1::detail::NDRDescT::GlobalOffset, sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::detail::enqueue_kernel_launch::handleErrorOrWarning(), sycl::_V1::detail::NDRDescT::LocalSize, sycl::_V1::detail::CGExecKernel::MArgs, sycl::_V1::detail::CGExecKernel::MKernelBundle, sycl::_V1::detail::CGExecKernel::MKernelName, sycl::_V1::detail::CGExecKernel::MNDRDesc, sycl::_V1::detail::CGExecKernel::MSyclKernel, PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE, piextCommandBufferNDRangeKernel(), piKernelGetGroupInfo(), piKernelRelease(), piProgramRelease(), ReverseRangeDimensionsForKernel(), SetArgBasedOnType(), and tie().
enqueueImpKernel()
pi_int32 sycl::_V1::detail::enqueueImpKernel (const QueueImplPtr & Queue, NDRDescT & NDRDesc, std::vector< ArgDesc > & Args, const std::shared_ptr< detail::kernel_bundle_impl > & KernelBundleImplPtr, const std::shared_ptr< detail::kernel_impl > & MSyclKernel, const std::string & KernelName, std::vector< sycl::detail::pi::PiEvent > & RawEvents, const detail::EventImplPtr & OutEventImpl, const std::function< void *(Requirement *Req)> & getMemAllocationFunc, sycl::detail::pi::PiKernelCacheConfig KernelCacheConfig, const bool KernelIsCooperative)
Definition at line 2559 of file commands.cpp.
References sycl::_V1::detail::ProgramManager::getInstance(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), sycl::_V1::detail::ProgramManager::getSYCLKernelID(), getSyclObjImpl(), sycl::_V1::detail::enqueue_kernel_launch::handleErrorOrWarning(), PI_EXT_KERNEL_EXEC_INFO_CACHE_CONFIG, PI_EXT_KERNEL_EXEC_INFO_CACHE_LARGE_DATA, PI_EXT_KERNEL_EXEC_INFO_CACHE_LARGE_SLM, piKernelRelease(), piKernelSetExecInfo(), piProgramRelease(), SetKernelParamsAndLaunch(), and tie().
Referenced by sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::enqueue().
enqueueReadWriteHostPipe()
pi_int32 sycl::_V1::detail::enqueueReadWriteHostPipe (const QueueImplPtr & Queue, const std::string & PipeName, bool blocking, void * ptr, size_t size, std::vector< sycl::detail::pi::PiEvent > & RawEvents, const detail::EventImplPtr & OutEventImpl, bool read)
Definition at line 2680 of file commands.cpp.
References sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::HostPipeMapEntry::getDevBinImage(), sycl::_V1::detail::ProgramManager::getDeviceImageFromBinaryImage(), sycl::_V1::detail::ProgramManager::getHostPipeEntry(), sycl::_V1::detail::ProgramManager::getInstance(), getSyclObjImpl(), piextEnqueueReadHostPipe(), and piextEnqueueWriteHostPipe().
event_impl::get_backend_info< info::device::backend_version >()
template<> info::device::backend_version::return_type sycl::_V1::detail::event_impl::get_backend_info< info::device::backend_version > () const
Definition at line 463 of file event_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::ext_oneapi_level_zero.
event_impl::get_backend_info< info::device::version >()
template<> info::device::version::return_type sycl::_V1::detail::event_impl::get_backend_info< info::device::version > () const
Definition at line 445 of file event_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::opencl.
event_impl::get_backend_info< info::platform::version >()
template<> info::platform::version::return_type sycl::_V1::detail::event_impl::get_backend_info< info::platform::version > () const
Definition at line 425 of file event_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::opencl.
event_impl::get_info< info::event::command_execution_status >()
template<> info::event_command_status sycl::_V1::detail::event_impl::get_info< info::event::command_execution_status > ()
Definition at line 404 of file event_impl.cpp.
References sycl::_V1::info::complete, sycl::_V1::info::ext_oneapi_unknown, and getPlugin().
event_impl::get_info< info::event::reference_count >()
template<> uint32_t sycl::_V1::detail::event_impl::get_info< info::event::reference_count > ()
Definition at line 395 of file event_impl.cpp.
References getPlugin().
event_impl::get_profiling_info< info::event_profiling::command_end >()
template<> uint64_t sycl::_V1::detail::event_impl::get_profiling_info< info::event_profiling::command_end > ()
Definition at line 364 of file event_impl.cpp.
References codeToString(), and getPlugin().
event_impl::get_profiling_info< info::event_profiling::command_start >()
template<> uint64_t sycl::_V1::detail::event_impl::get_profiling_info< info::event_profiling::command_start > ()
Definition at line 331 of file event_impl.cpp.
References codeToString(), and getPlugin().
event_impl::get_profiling_info< info::event_profiling::command_submit >()
template<> uint64_t sycl::_V1::detail::event_impl::get_profiling_info< info::event_profiling::command_submit > ()
Definition at line 302 of file event_impl.cpp.
References getPlugin().
ExtractMask()
sycl::vec<unsigned, 4> sycl::_V1::detail::ExtractMask (ext::oneapi::sub_group_mask Mask) inline
Definition at line 23 of file non_uniform_groups.hpp.
References sycl::_V1::ext::oneapi::sub_group_mask::extract_bits().
Referenced by IdToMaskPosition().
F2I32()
unsigned sycl::_V1::detail::F2I32 (float Val) inline
Definition at line 249 of file stream.hpp.
Referenced by isFastMathInf(), isFastMathNan(), and isFastMathSignBit().
FConvert()
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>, sycl::rounding_mode RM> To sycl::_V1::detail::FConvert (From Value)
Definition at line 154 of file vector_convert.hpp.
fill_aspect_vector() [1/2]
template<typename FirstT , typename... OtherTs> void sycl::_V1::detail::fill_aspect_vector (std::vector< aspect > & V, FirstT F, OtherTs... O)
Definition at line 130 of file device_selector.hpp.
References fill_aspect_vector().
fill_aspect_vector() [2/2]
template<typename LastT > void sycl::_V1::detail::fill_aspect_vector (std::vector< aspect > & V, LastT L)
Definition at line 125 of file device_selector.hpp.
Referenced by fill_aspect_vector().
filterSequence()
template<typename... T, typename FunctorT , size_t... Is> constexpr auto sycl::_V1::detail::filterSequence (FunctorT F, std::index_sequence< Is... > Indices) constexpr
For each index 'I' from the given indices pack 'Is' this function returns an index sequence consisting of only those 'I's for which the 'FunctorT' applied to 'T[I]' returns true.
Definition at line 2152 of file reduction.hpp.
References filterSequenceHelper().
Referenced by reduAuxCGFunc(), and reduCGFuncMulti().
filterSequenceHelper()
template<typename... T, typename FunctorT , size_t... Is, std::enable_if_t<(sizeof...(Is) > 0), int > Z = 0> constexpr auto sycl::_V1::detail::filterSequenceHelper (FunctorT , std::index_sequence< Is... >) constexpr
For each index 'I' from the given indices pack 'Is' this function initially creates a number of short index_sequences, where each of such short index sequences is either empty (if the given Functor returns false for the type T[I]) or 1 element 'I' (otherwise).
After that this function concatenates those short sequences into one and returns the result sequence.
Definition at line 2136 of file reduction.hpp.
References concat_sequences().
Referenced by filterSequence().
find_device_intersection()
std::vector< sycl::device > sycl::_V1::detail::find_device_intersection (const std::vector< kernel_bundle< bundle_state::object >> & ObjectBundles)
Definition at line 275 of file kernel_bundle.cpp.
References sycl::_V1::device::get_devices().
float2Half()
__SYCL_CONSTEXPR_HALF uint16_t sycl::_V1::detail::float2Half (const float & Val) inline
Definition at line 55 of file half_type.hpp.
References __builtin_expect.
floatingPointToDecStr()
template<typename T > EnableIfFP<T, unsigned> sycl::_V1::detail::floatingPointToDecStr (T AbsVal, char * Digits, int Precision, bool IsSci)
Definition at line 369 of file stream.hpp.
References digitToChar(), and MAX_FLOATING_POINT_DIGITS.
Referenced by ScalarToStr().
flushBuffer()
void sycl::_V1::detail::flushBuffer (GlobalOffsetAccessorT & GlobalOffset, GlobalBufAccessorT & GlobalBuf, GlobalBufAccessorT & GlobalFlushBuf, unsigned WIOffset) inline
Definition at line 549 of file stream.hpp.
References FLUSH_BUF_OFFSET_SIZE, GetFlushBufOffset(), SetFlushBufOffset(), and updateOffset().
flushCrossQueueDeps()
static void sycl::_V1::detail::flushCrossQueueDeps (const std::vector< EventImplPtr > & EventImpls, const QueueImplPtr & Queue) static
Definition at line 313 of file commands.cpp.
Referenced by sycl::_V1::detail::Command::waitForEvents().
for_each()
template<typename Group , typename Ptr , class Function > Function sycl::_V1::detail::for_each (Group g, Ptr first, Ptr last, Function f)
Definition at line 188 of file group_algorithm.hpp.
References sycl::_V1::feature_not_supported, get_local_linear_id(), get_local_linear_range(), and sycl::_V1::make_error_code().
Referenced by sycl::_V1::detail::device_impl::create_sub_devices(), sycl::_V1::ext::oneapi::experimental::joint_reduce(), and sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl().
force_type()
void sycl::_V1::detail::force_type (info::device_type & t, const info::device_type & ft)
Definition at line 22 of file device.cpp.
References sycl::_V1::info::all, and sycl::_V1::t.
FormatChannelOrder()
image_channel_order sycl::_V1::detail::FormatChannelOrder (image_format Format) inline
Definition at line 153 of file image.hpp.
References sycl::_V1::b8g8r8a8_unorm, sycl::_V1::bgra, sycl::_V1::r16b16g16a16_sfloat, sycl::_V1::r16g16b16a16_sint, sycl::_V1::r16g16b16a16_uint, sycl::_V1::r16g16b16a16_unorm, sycl::_V1::r32b32g32a32_sint, sycl::_V1::r32b32g32a32_uint, sycl::_V1::r32g32b32a32_sfloat, sycl::_V1::r8g8b8a8_sint, sycl::_V1::r8g8b8a8_uint, sycl::_V1::r8g8b8a8_unorm, and sycl::_V1::rgba.
FormatChannelType()
image_channel_type sycl::_V1::detail::FormatChannelType (image_format Format) inline
Definition at line 125 of file image.hpp.
References sycl::_V1::b8g8r8a8_unorm, sycl::_V1::fp16, sycl::_V1::fp32, sycl::_V1::r16b16g16a16_sfloat, sycl::_V1::r16g16b16a16_sint, sycl::_V1::r16g16b16a16_uint, sycl::_V1::r16g16b16a16_unorm, sycl::_V1::r32b32g32a32_sint, sycl::_V1::r32b32g32a32_uint, sycl::_V1::r32g32b32a32_sfloat, sycl::_V1::r8g8b8a8_sint, sycl::_V1::r8g8b8a8_uint, sycl::_V1::r8g8b8a8_unorm, sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
get_backend_name_no_vendor()
std::string_view sycl::_V1::detail::get_backend_name_no_vendor (backend Backend) inline
Definition at line 69 of file backend_types.hpp.
References sycl::_V1::all, sycl::_V1::ext_oneapi_cuda, sycl::_V1::ext_oneapi_hip, sycl::_V1::ext_oneapi_level_zero, sycl::_V1::ext_oneapi_native_cpu, and sycl::_V1::opencl.
get_category_max_architecture()
static constexpr std::optional<ext::oneapi::experimental::architecture> sycl::_V1::detail::get_category_max_architecture (ext::oneapi::experimental::arch_category Category) static constexpr
Definition at line 856 of file device_architecture.hpp.
References sycl::_V1::ext::oneapi::experimental::amd_gpu, sycl::_V1::ext::oneapi::experimental::intel_gpu, max_amd_gpu_architecture, max_intel_gpu_architecture, max_nvidia_gpu_architecture, and sycl::_V1::ext::oneapi::experimental::nvidia_gpu.
Referenced by device_architecture_is_in_category_aot(), and sycl::_V1::detail::device_impl::extOneapiArchitectureIs().
get_category_min_architecture()
static constexpr std::optional<ext::oneapi::experimental::architecture> sycl::_V1::detail::get_category_min_architecture (ext::oneapi::experimental::arch_category Category) static constexpr
Definition at line 843 of file device_architecture.hpp.
References sycl::_V1::ext::oneapi::experimental::amd_gpu, sycl::_V1::ext::oneapi::experimental::intel_gpu, min_amd_gpu_architecture, min_intel_gpu_architecture, min_nvidia_gpu_architecture, and sycl::_V1::ext::oneapi::experimental::nvidia_gpu.
Referenced by device_architecture_is_in_category_aot(), and sycl::_V1::detail::device_impl::extOneapiArchitectureIs().
get_context_info()
template<typename Param > Param::return_type sycl::_V1::detail::get_context_info (sycl::detail::pi::PiContext Ctx, const PluginPtr & Plugin)
Definition at line 21 of file context_info.hpp.
References piContextGetInfo().
get_current_architecture_aot()
constexpr static std::optional<ext::oneapi::experimental::architecture> sycl::_V1::detail::get_current_architecture_aot () static constexpr
Definition at line 572 of file device_architecture.hpp.
References sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1010, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1011, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1012, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1030, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1031, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1032, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1033, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1034, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1035, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1036, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1100, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1101, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1102, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1103, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1150, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1151, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1200, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx1201, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx700, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx701, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx702, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx801, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx802, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx803, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx805, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx810, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx900, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx902, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx904, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx906, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx908, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx909, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx90a, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx90c, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx940, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx941, sycl::_V1::ext::oneapi::experimental::amd_gpu_gfx942, sycl::_V1::ext::oneapi::experimental::intel_gpu_acm_g10, sycl::_V1::ext::oneapi::experimental::intel_gpu_acm_g11, sycl::_V1::ext::oneapi::experimental::intel_gpu_acm_g12, sycl::_V1::ext::oneapi::experimental::intel_gpu_adl_n, sycl::_V1::ext::oneapi::experimental::intel_gpu_adl_p, sycl::_V1::ext::oneapi::experimental::intel_gpu_adl_s, sycl::_V1::ext::oneapi::experimental::intel_gpu_aml, sycl::_V1::ext::oneapi::experimental::intel_gpu_apl, sycl::_V1::ext::oneapi::experimental::intel_gpu_arl_h, sycl::_V1::ext::oneapi::experimental::intel_gpu_bdw, sycl::_V1::ext::oneapi::experimental::intel_gpu_bmg_g21, sycl::_V1::ext::oneapi::experimental::intel_gpu_cfl, sycl::_V1::ext::oneapi::experimental::intel_gpu_cml, sycl::_V1::ext::oneapi::experimental::intel_gpu_dg1, sycl::_V1::ext::oneapi::experimental::intel_gpu_ehl, sycl::_V1::ext::oneapi::experimental::intel_gpu_glk, sycl::_V1::ext::oneapi::experimental::intel_gpu_icllp, sycl::_V1::ext::oneapi::experimental::intel_gpu_kbl, sycl::_V1::ext::oneapi::experimental::intel_gpu_lnl_m, sycl::_V1::ext::oneapi::experimental::intel_gpu_mtl_h, sycl::_V1::ext::oneapi::experimental::intel_gpu_mtl_u, sycl::_V1::ext::oneapi::experimental::intel_gpu_pvc, sycl::_V1::ext::oneapi::experimental::intel_gpu_pvc_vg, sycl::_V1::ext::oneapi::experimental::intel_gpu_rkl, sycl::_V1::ext::oneapi::experimental::intel_gpu_skl, sycl::_V1::ext::oneapi::experimental::intel_gpu_tgllp, sycl::_V1::ext::oneapi::experimental::intel_gpu_whl, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_50, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_52, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_53, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_60, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_61, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_62, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_70, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_72, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_75, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_80, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_86, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_87, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_89, sycl::_V1::ext::oneapi::experimental::nvidia_gpu_sm_90, and sycl::_V1::ext::oneapi::experimental::x86_64.
Referenced by device_architecture_comparison_aot(), device_architecture_is_in_category_aot(), and is_aot_for_architecture().
get_device_architecture_category()
constexpr static std::optional<ext::oneapi::experimental::arch_category> sycl::_V1::detail::get_device_architecture_category (ext::oneapi::experimental::architecture arch) static constexpr
Definition at line 892 of file device_architecture.hpp.
References sycl::_V1::ext::oneapi::experimental::amd_gpu, sycl::_V1::ext::oneapi::experimental::intel_gpu, max_amd_gpu_architecture, max_intel_gpu_architecture, max_nvidia_gpu_architecture, min_amd_gpu_architecture, min_intel_gpu_architecture, min_nvidia_gpu_architecture, and sycl::_V1::ext::oneapi::experimental::nvidia_gpu.
Referenced by device_architecture_comparison_aot().
get_device_info()
template<typename Param > Param::return_type sycl::_V1::detail::get_device_info (const DeviceImplPtr & Dev)
Definition at line 1264 of file device_info.hpp.
References sycl::_V1::detail::get_device_info_impl< ReturnT, Param >::get().
get_device_info_host()
template<typename Param > Param::return_type sycl::_V1::detail::get_device_info_host () inline delete
Referenced by get_device_info_host< info::device::ext_oneapi_max_global_work_groups >().
get_device_info_host< ext::codeplay::experimental::info::device::max_registers_per_work_group >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::codeplay::experimental::info::device::max_registers_per_work_group > () inline
Definition at line 2157 of file device_info.hpp.
get_device_info_host< ext::codeplay::experimental::info::device::supports_fusion >()
template<> bool sycl::_V1::detail::get_device_info_host< ext::codeplay::experimental::info::device::supports_fusion > () inline
Definition at line 2150 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::device_id >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::device_id > () inline
Definition at line 1970 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::free_memory >()
template<> uint64_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::free_memory > () inline
Definition at line 2119 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::gpu_eu_count >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::gpu_eu_count > () inline
Definition at line 1982 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::gpu_eu_count_per_subslice >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::gpu_eu_count_per_subslice > () inline
Definition at line 2007 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::gpu_eu_simd_width >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::gpu_eu_simd_width > () inline
Definition at line 1987 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::gpu_hw_threads_per_eu >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::gpu_hw_threads_per_eu > () inline
Definition at line 2014 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::gpu_slices >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::gpu_slices > () inline
Definition at line 1994 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::gpu_subslices_per_slice >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::gpu_subslices_per_slice > () inline
Definition at line 2000 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::max_compute_queue_indices >()
template<> int32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::max_compute_queue_indices > () inline
Definition at line 2142 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::max_mem_bandwidth >()
template<> uint64_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::max_mem_bandwidth > () inline
Definition at line 2021 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::memory_bus_width >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::memory_bus_width > () inline
Definition at line 2134 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::memory_clock_rate >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::intel::info::device::memory_clock_rate > () inline
Definition at line 2126 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::pci_address >()
template<> std::string sycl::_V1::detail::get_device_info_host< ext::intel::info::device::pci_address > () inline
Definition at line 1975 of file device_info.hpp.
get_device_info_host< ext::intel::info::device::uuid >()
template<> detail::uuid_type sycl::_V1::detail::get_device_info_host< ext::intel::info::device::uuid > () inline
Definition at line 2028 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::architecture >()
template<> ext::oneapi::experimental::architecture sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::architecture > () inline
Definition at line 1290 of file device_info.hpp.
References sycl::_V1::ext::oneapi::experimental::x86_64.
get_device_info_host< ext::oneapi::experimental::info::device::component_devices >()
template<> std::vector<sycl::device> sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::component_devices > () inline
Definition at line 2206 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::composite_device >()
template<> sycl::device sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::composite_device > () inline
Definition at line 2220 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::image_row_pitch_align >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::image_row_pitch_align > () inline
Definition at line 2165 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::matrix_combinations >()
template<> std::vector<ext::oneapi::experimental::matrix::combination> sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::matrix_combinations > () inline
Definition at line 2173 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::max_global_work_groups >()
template<> constexpr size_t sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::max_global_work_groups > () inline constexpr
Definition at line 1333 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_height >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_height > () inline
Definition at line 2198 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_row_pitch >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_row_pitch > () inline
Definition at line 2173 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_width >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::max_image_linear_width > () inline
Definition at line 2190 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 1 > >()
template<> id<1> sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 1 > > () inline
Definition at line 1333 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 2 > >()
template<> id<2> sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 2 > > () inline
Definition at line 1333 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 3 > >()
template<> id<3> sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::max_work_groups< 3 > > () inline
Definition at line 1333 of file device_info.hpp.
get_device_info_host< ext::oneapi::experimental::info::device::mipmap_max_anisotropy >()
template<> float sycl::_V1::detail::get_device_info_host< ext::oneapi::experimental::info::device::mipmap_max_anisotropy > () inline
Definition at line 2206 of file device_info.hpp.
get_device_info_host< info::device::address_bits >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::address_bits > () inline
Definition at line 1501 of file device_info.hpp.
get_device_info_host< info::device::aspects >()
template<> std::vector<sycl::aspect> sycl::_V1::detail::get_device_info_host< info::device::aspects > () inline
Definition at line 1282 of file device_info.hpp.
get_device_info_host< info::device::atomic64 >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::atomic64 > () inline
Definition at line 1522 of file device_info.hpp.
get_device_info_host< info::device::atomic_fence_order_capabilities >()
template<> std::vector<memory_order> sycl::_V1::detail::get_device_info_host< info::device::atomic_fence_order_capabilities > () inline
Definition at line 1522 of file device_info.hpp.
get_device_info_host< info::device::atomic_fence_scope_capabilities >()
template<> std::vector<memory_scope> sycl::_V1::detail::get_device_info_host< info::device::atomic_fence_scope_capabilities > () inline
Definition at line 1522 of file device_info.hpp.
get_device_info_host< info::device::atomic_memory_order_capabilities >()
template<> std::vector<memory_order> sycl::_V1::detail::get_device_info_host< info::device::atomic_memory_order_capabilities > () inline
Definition at line 1522 of file device_info.hpp.
get_device_info_host< info::device::atomic_memory_scope_capabilities >()
template<> std::vector<memory_scope> sycl::_V1::detail::get_device_info_host< info::device::atomic_memory_scope_capabilities > () inline
Definition at line 1522 of file device_info.hpp.
get_device_info_host< info::device::backend_version >()
template<> std::string sycl::_V1::detail::get_device_info_host< info::device::backend_version > () inline
Definition at line 1930 of file device_info.hpp.
get_device_info_host< info::device::built_in_kernel_ids >()
template<> std::vector<kernel_id> sycl::_V1::detail::get_device_info_host< info::device::built_in_kernel_ids > () inline
Definition at line 1791 of file device_info.hpp.
get_device_info_host< info::device::built_in_kernels >()
template<> std::vector<std::string> sycl::_V1::detail::get_device_info_host< info::device::built_in_kernels > () inline
Definition at line 1791 of file device_info.hpp.
get_device_info_host< info::device::device_type >()
template<> info::device_type sycl::_V1::detail::get_device_info_host< info::device::device_type > () inline
Definition at line 1296 of file device_info.hpp.
References sycl::_V1::info::host.
get_device_info_host< info::device::double_fp_config >()
template<> std::vector<info::fp_config> sycl::_V1::detail::get_device_info_host< info::device::double_fp_config > () inline
Definition at line 1676 of file device_info.hpp.
get_device_info_host< info::device::driver_version >()
template<> std::string sycl::_V1::detail::get_device_info_host< info::device::driver_version > () inline
Definition at line 1820 of file device_info.hpp.
get_device_info_host< info::device::error_correction_support >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::error_correction_support > () inline
Definition at line 1745 of file device_info.hpp.
get_device_info_host< info::device::execution_capabilities >()
template<> std::vector<info::execution_capability> sycl::_V1::detail::get_device_info_host< info::device::execution_capabilities > () inline
Definition at line 1781 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_device_info_uuid >()
template<> detail::uuid_type sycl::_V1::detail::get_device_info_host< info::device::ext_intel_device_info_uuid > () inline
Definition at line 2111 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_gpu_eu_count >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::ext_intel_gpu_eu_count > () inline
Definition at line 2046 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_gpu_eu_count_per_subslice >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::ext_intel_gpu_eu_count_per_subslice > () inline
Definition at line 2079 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_gpu_eu_simd_width >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::ext_intel_gpu_eu_simd_width > () inline
Definition at line 2053 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_gpu_hw_threads_per_eu >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::ext_intel_gpu_hw_threads_per_eu > () inline
Definition at line 2088 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_gpu_slices >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::ext_intel_gpu_slices > () inline
Definition at line 2062 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_gpu_subslices_per_slice >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::ext_intel_gpu_subslices_per_slice > () inline
Definition at line 2070 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_max_mem_bandwidth >()
template<> uint64_t sycl::_V1::detail::get_device_info_host< info::device::ext_intel_max_mem_bandwidth > () inline
Definition at line 2097 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_mem_channel >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::ext_intel_mem_channel > () inline
Definition at line 1963 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_pci_address >()
template<> std::string sycl::_V1::detail::get_device_info_host< info::device::ext_intel_pci_address > () inline
Definition at line 2038 of file device_info.hpp.
get_device_info_host< info::device::ext_oneapi_bfloat16_math_functions >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::ext_oneapi_bfloat16_math_functions > () inline
Definition at line 1555 of file device_info.hpp.
get_device_info_host< info::device::ext_oneapi_max_global_work_groups >()
template<> constexpr size_t sycl::_V1::detail::get_device_info_host< info::device::ext_oneapi_max_global_work_groups > () inline constexpr
Definition at line 1369 of file device_info.hpp.
References get_device_info_host().
get_device_info_host< info::device::ext_oneapi_max_work_groups_1d >()
template<> id<1> sycl::_V1::detail::get_device_info_host< info::device::ext_oneapi_max_work_groups_1d > () inline
Definition at line 1369 of file device_info.hpp.
get_device_info_host< info::device::ext_oneapi_max_work_groups_2d >()
template<> id<2> sycl::_V1::detail::get_device_info_host< info::device::ext_oneapi_max_work_groups_2d > () inline
Definition at line 1369 of file device_info.hpp.
get_device_info_host< info::device::ext_oneapi_max_work_groups_3d >()
template<> id<3> sycl::_V1::detail::get_device_info_host< info::device::ext_oneapi_max_work_groups_3d > () inline
Definition at line 1369 of file device_info.hpp.
get_device_info_host< info::device::ext_oneapi_srgb >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::ext_oneapi_srgb > () inline
Definition at line 2104 of file device_info.hpp.
get_device_info_host< info::device::extensions >()
template<> std::vector<std::string> sycl::_V1::detail::get_device_info_host< info::device::extensions > () inline
Definition at line 1833 of file device_info.hpp.
get_device_info_host< info::device::global_mem_cache_line_size >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::global_mem_cache_line_size > () inline
Definition at line 1710 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::getMemCacheLineSize().
get_device_info_host< info::device::global_mem_cache_size >()
template<> uint64_t sycl::_V1::detail::get_device_info_host< info::device::global_mem_cache_size > () inline
Definition at line 1716 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::getMemCacheSize().
get_device_info_host< info::device::global_mem_cache_type >()
template<> info::global_mem_cache_type sycl::_V1::detail::get_device_info_host< info::device::global_mem_cache_type > () inline
Definition at line 1704 of file device_info.hpp.
References sycl::_V1::info::read_write.
get_device_info_host< info::device::global_mem_size >()
template<> uint64_t sycl::_V1::detail::get_device_info_host< info::device::global_mem_size > () inline
Definition at line 1506 of file device_info.hpp.
References sycl::_V1::detail::OSUtil::getOSMemSize().
get_device_info_host< info::device::half_fp_config >()
template<> std::vector<info::fp_config> sycl::_V1::detail::get_device_info_host< info::device::half_fp_config > () inline
Definition at line 1676 of file device_info.hpp.
get_device_info_host< info::device::host_unified_memory >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::host_unified_memory > () inline
Definition at line 1750 of file device_info.hpp.
get_device_info_host< info::device::image2d_max_height >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::image2d_max_height > () inline
Definition at line 1589 of file device_info.hpp.
get_device_info_host< info::device::image2d_max_width >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::image2d_max_width > () inline
Definition at line 1573 of file device_info.hpp.
get_device_info_host< info::device::image3d_max_depth >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::image3d_max_depth > () inline
Definition at line 1637 of file device_info.hpp.
get_device_info_host< info::device::image3d_max_height >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::image3d_max_height > () inline
Definition at line 1621 of file device_info.hpp.
get_device_info_host< info::device::image3d_max_width >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::image3d_max_width > () inline
Definition at line 1605 of file device_info.hpp.
get_device_info_host< info::device::image_max_array_size >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::image_max_array_size > () inline
Definition at line 1659 of file device_info.hpp.
get_device_info_host< info::device::image_max_buffer_size >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::image_max_buffer_size > () inline
Definition at line 1653 of file device_info.hpp.
get_device_info_host< info::device::image_support >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::image_support > () inline
Definition at line 1518 of file device_info.hpp.
get_device_info_host< info::device::is_available >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::is_available > () inline
Definition at line 1771 of file device_info.hpp.
get_device_info_host< info::device::is_compiler_available >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::is_compiler_available > () inline
Definition at line 1776 of file device_info.hpp.
get_device_info_host< info::device::is_endian_little >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::is_endian_little > () inline
Definition at line 1762 of file device_info.hpp.
get_device_info_host< info::device::is_linker_available >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::is_linker_available > () inline
Definition at line 1781 of file device_info.hpp.
get_device_info_host< info::device::kernel_kernel_pipe_support >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::kernel_kernel_pipe_support > () inline
Definition at line 1925 of file device_info.hpp.
get_device_info_host< info::device::local_mem_size >()
template<> uint64_t sycl::_V1::detail::get_device_info_host< info::device::local_mem_size > () inline
Definition at line 1739 of file device_info.hpp.
get_device_info_host< info::device::local_mem_type >()
template<> info::local_mem_type sycl::_V1::detail::get_device_info_host< info::device::local_mem_type > () inline
Definition at line 1733 of file device_info.hpp.
References sycl::_V1::info::global.
get_device_info_host< info::device::max_clock_frequency >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::max_clock_frequency > () inline
Definition at line 1497 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::getMaxClockFrequency().
get_device_info_host< info::device::max_compute_units >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::max_compute_units > () inline
Definition at line 1305 of file device_info.hpp.
get_device_info_host< info::device::max_constant_args >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::max_constant_args > () inline
Definition at line 1727 of file device_info.hpp.
get_device_info_host< info::device::max_constant_buffer_size >()
template<> uint64_t sycl::_V1::detail::get_device_info_host< info::device::max_constant_buffer_size > () inline
Definition at line 1721 of file device_info.hpp.
get_device_info_host< info::device::max_mem_alloc_size >()
template<> uint64_t sycl::_V1::detail::get_device_info_host< info::device::max_mem_alloc_size > () inline
Definition at line 1511 of file device_info.hpp.
get_device_info_host< info::device::max_num_sub_groups >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::max_num_sub_groups > () inline
Definition at line 1902 of file device_info.hpp.
get_device_info_host< info::device::max_parameter_size >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::max_parameter_size > () inline
Definition at line 1670 of file device_info.hpp.
get_device_info_host< info::device::max_read_image_args >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::max_read_image_args > () inline
Definition at line 1561 of file device_info.hpp.
get_device_info_host< info::device::max_samplers >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::max_samplers > () inline
Definition at line 1664 of file device_info.hpp.
get_device_info_host< info::device::max_work_group_size >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::max_work_group_size > () inline
Definition at line 1404 of file device_info.hpp.
get_device_info_host< info::device::max_work_item_dimensions >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::max_work_item_dimensions > () inline
Definition at line 1310 of file device_info.hpp.
get_device_info_host< info::device::max_work_item_sizes< 1 > >()
template<> range<1> sycl::_V1::detail::get_device_info_host< info::device::max_work_item_sizes< 1 > > () inline
Definition at line 1310 of file device_info.hpp.
get_device_info_host< info::device::max_work_item_sizes< 2 > >()
template<> range<2> sycl::_V1::detail::get_device_info_host< info::device::max_work_item_sizes< 2 > > () inline
Definition at line 1310 of file device_info.hpp.
get_device_info_host< info::device::max_work_item_sizes< 3 > >()
template<> range<3> sycl::_V1::detail::get_device_info_host< info::device::max_work_item_sizes< 3 > > () inline
Definition at line 1310 of file device_info.hpp.
get_device_info_host< info::device::max_write_image_args >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::max_write_image_args > () inline
Definition at line 1567 of file device_info.hpp.
get_device_info_host< info::device::mem_base_addr_align >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::mem_base_addr_align > () inline
Definition at line 1676 of file device_info.hpp.
get_device_info_host< info::device::name >()
template<> std::string sycl::_V1::detail::get_device_info_host< info::device::name > () inline
Definition at line 1811 of file device_info.hpp.
get_device_info_host< info::device::native_vector_width_char >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::native_vector_width_char > () inline
Definition at line 1459 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::Char, and sycl::_V1::detail::PlatformUtil::getNativeVectorWidth().
get_device_info_host< info::device::native_vector_width_double >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::native_vector_width_double > () inline
Definition at line 1486 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::Double, and sycl::_V1::detail::PlatformUtil::getNativeVectorWidth().
get_device_info_host< info::device::native_vector_width_float >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::native_vector_width_float > () inline
Definition at line 1480 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::Float, and sycl::_V1::detail::PlatformUtil::getNativeVectorWidth().
get_device_info_host< info::device::native_vector_width_half >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::native_vector_width_half > () inline
Definition at line 1492 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::getNativeVectorWidth(), and sycl::_V1::detail::PlatformUtil::Half.
get_device_info_host< info::device::native_vector_width_int >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::native_vector_width_int > () inline
Definition at line 1470 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::getNativeVectorWidth(), and sycl::_V1::detail::PlatformUtil::Int.
get_device_info_host< info::device::native_vector_width_long >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::native_vector_width_long > () inline
Definition at line 1475 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::getNativeVectorWidth(), and sycl::_V1::detail::PlatformUtil::Long.
get_device_info_host< info::device::native_vector_width_short >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::native_vector_width_short > () inline
Definition at line 1464 of file device_info.hpp.
References sycl::_V1::detail::PlatformUtil::getNativeVectorWidth(), and sycl::_V1::detail::PlatformUtil::Short.
get_device_info_host< info::device::opencl_c_version >()
template<> std::string sycl::_V1::detail::get_device_info_host< info::device::opencl_c_version > () inline
Definition at line 1833 of file device_info.hpp.
get_device_info_host< info::device::parent_device >()
template<> device sycl::_V1::detail::get_device_info_host< info::device::parent_device > () inline
Definition at line 1855 of file device_info.hpp.
get_device_info_host< info::device::partition_affinity_domains >()
template<> std::vector<info::partition_affinity_domain> sycl::_V1::detail::get_device_info_host< info::device::partition_affinity_domains > () inline
Definition at line 1862 of file device_info.hpp.
get_device_info_host< info::device::partition_max_sub_devices >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::partition_max_sub_devices > () inline
Definition at line 1862 of file device_info.hpp.
get_device_info_host< info::device::partition_properties >()
template<> std::vector<info::partition_property> sycl::_V1::detail::get_device_info_host< info::device::partition_properties > () inline
Definition at line 1862 of file device_info.hpp.
get_device_info_host< info::device::partition_type_affinity_domain >()
template<> info::partition_affinity_domain sycl::_V1::detail::get_device_info_host< info::device::partition_type_affinity_domain > () inline
Definition at line 1889 of file device_info.hpp.
References sycl::_V1::info::not_applicable.
get_device_info_host< info::device::partition_type_property >()
template<> info::partition_property sycl::_V1::detail::get_device_info_host< info::device::partition_type_property > () inline
Definition at line 1883 of file device_info.hpp.
References sycl::_V1::info::no_partition.
get_device_info_host< info::device::platform >()
template<> platform sycl::_V1::detail::get_device_info_host< info::device::platform > () inline
Definition at line 1807 of file device_info.hpp.
References sycl::_V1::detail::platform_impl::getHostPlatformImpl().
get_device_info_host< info::device::preferred_interop_user_sync >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::preferred_interop_user_sync > () inline
Definition at line 1851 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_char >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::preferred_vector_width_char > () inline
Definition at line 1410 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_double >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::preferred_vector_width_double > () inline
Definition at line 1445 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_float >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::preferred_vector_width_float > () inline
Definition at line 1438 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_half >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::preferred_vector_width_half > () inline
Definition at line 1452 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_int >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::preferred_vector_width_int > () inline
Definition at line 1424 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_long >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::preferred_vector_width_long > () inline
Definition at line 1431 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_short >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::preferred_vector_width_short > () inline
Definition at line 1417 of file device_info.hpp.
get_device_info_host< info::device::printf_buffer_size >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::printf_buffer_size > () inline
Definition at line 1845 of file device_info.hpp.
get_device_info_host< info::device::profile >()
template<> std::string sycl::_V1::detail::get_device_info_host< info::device::profile > () inline
Definition at line 1824 of file device_info.hpp.
get_device_info_host< info::device::profiling_timer_resolution >()
template<> size_t sycl::_V1::detail::get_device_info_host< info::device::profiling_timer_resolution > () inline
Definition at line 1755 of file device_info.hpp.
get_device_info_host< info::device::queue_profiling >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::queue_profiling > () inline
Definition at line 1791 of file device_info.hpp.
get_device_info_host< info::device::reference_count >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::reference_count > () inline
Definition at line 1896 of file device_info.hpp.
get_device_info_host< info::device::single_fp_config >()
template<> std::vector<info::fp_config> sycl::_V1::detail::get_device_info_host< info::device::single_fp_config > () inline
Definition at line 1676 of file device_info.hpp.
get_device_info_host< info::device::sub_group_independent_forward_progress >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::sub_group_independent_forward_progress > () inline
Definition at line 1917 of file device_info.hpp.
get_device_info_host< info::device::sub_group_sizes >()
template<> std::vector<size_t> sycl::_V1::detail::get_device_info_host< info::device::sub_group_sizes > () inline
Definition at line 1902 of file device_info.hpp.
get_device_info_host< info::device::usm_device_allocations >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::usm_device_allocations > () inline
Definition at line 1937 of file device_info.hpp.
get_device_info_host< info::device::usm_host_allocations >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::usm_host_allocations > () inline
Definition at line 1942 of file device_info.hpp.
get_device_info_host< info::device::usm_restricted_shared_allocations >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::usm_restricted_shared_allocations > () inline
Definition at line 1952 of file device_info.hpp.
get_device_info_host< info::device::usm_shared_allocations >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::usm_shared_allocations > () inline
Definition at line 1947 of file device_info.hpp.
get_device_info_host< info::device::usm_system_allocations >()
template<> bool sycl::_V1::detail::get_device_info_host< info::device::usm_system_allocations > () inline
Definition at line 1958 of file device_info.hpp.
get_device_info_host< info::device::vendor >()
template<> std::string sycl::_V1::detail::get_device_info_host< info::device::vendor > () inline
Definition at line 1815 of file device_info.hpp.
get_device_info_host< info::device::vendor_id >()
template<> uint32_t sycl::_V1::detail::get_device_info_host< info::device::vendor_id > () inline
Definition at line 1300 of file device_info.hpp.
get_device_info_host< info::device::version >()
template<> std::string sycl::_V1::detail::get_device_info_host< info::device::version > () inline
Definition at line 1828 of file device_info.hpp.
get_empty_interop_kernel_bundle()
template<bundle_state State> kernel_bundle<State> sycl::_V1::detail::get_empty_interop_kernel_bundle (const context & Ctx)
make_kernel may need an empty interop kernel bundle.
This function supplies this.
Definition at line 572 of file kernel_bundle.hpp.
References sycl::_V1::context::get_devices(), and get_empty_interop_kernel_bundle_impl().
get_empty_interop_kernel_bundle_impl()
detail::KernelBundleImplPtr sycl::_V1::detail::get_empty_interop_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs)
Definition at line 169 of file kernel_bundle.cpp.
Referenced by get_empty_interop_kernel_bundle().
get_event_info()
template<typename Param > Param::return_type sycl::_V1::detail::get_event_info (sycl::detail::pi::PiEvent Event, const PluginPtr & Plugin)
Definition at line 35 of file event_info.hpp.
References PI_EVENT_QUEUED, and piEventGetInfo().
get_event_profiling_info()
template<typename Param > Param::return_type sycl::_V1::detail::get_event_profiling_info (sycl::detail::pi::PiEvent Event, const PluginPtr & Plugin)
Definition at line 23 of file event_info.hpp.
References piEventGetProfilingInfo().
get_kernel_bundle_impl() [1/3]
detail::KernelBundleImplPtr sycl::_V1::detail::get_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, bundle_state State)
Definition at line 148 of file kernel_bundle.cpp.
get_kernel_bundle_impl() [2/3]
detail::KernelBundleImplPtr sycl::_V1::detail::get_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, bundle_state State, const DevImgSelectorImpl & Selector)
Definition at line 162 of file kernel_bundle.cpp.
get_kernel_bundle_impl() [3/3]
detail::KernelBundleImplPtr sycl::_V1::detail::get_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, const std::vector< kernel_id > & KernelIDs, bundle_state State)
Definition at line 154 of file kernel_bundle.cpp.
get_kernel_device_specific_info() [1/2]
template<typename Param > std::enable_if< !std::is_same<typename Param::return_type, sycl::range<3> >::value, typename Param::return_type>::type sycl::_V1::detail::get_kernel_device_specific_info (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, const PluginPtr & Plugin)
Definition at line 88 of file kernel_info.hpp.
Referenced by adjustNDRangePerKernel().
get_kernel_device_specific_info() [2/2]
template<typename Param > std::enable_if< std::is_same<typename Param::return_type, sycl::range<3> >::value, sycl::range<3> >::type sycl::_V1::detail::get_kernel_device_specific_info (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, const PluginPtr & Plugin)
Definition at line 104 of file kernel_info.hpp.
get_kernel_device_specific_info_helper() [1/2]
template<typename Param > std::enable_if<IsSubGroupInfo<Param>::value>::type sycl::_V1::detail::get_kernel_device_specific_info_helper (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, const PluginPtr & Plugin, void * Result, size_t Size)
Definition at line 61 of file kernel_info.hpp.
References piKernelGetSubGroupInfo().
get_kernel_device_specific_info_helper() [2/2]
template<typename Param > std::enable_if<!IsSubGroupInfo<Param>::value>::type sycl::_V1::detail::get_kernel_device_specific_info_helper (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, const PluginPtr & Plugin, void * Result, size_t Size)
Definition at line 72 of file kernel_info.hpp.
References sycl::_V1::detail::kernel_get_group_info::handleErrorOrWarning(), and piKernelGetGroupInfo().
get_kernel_device_specific_info_host()
template<typename Param > Param::return_type sycl::_V1::detail::get_kernel_device_specific_info_host (const sycl::device & Device) inline delete
Referenced by get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple >().
get_kernel_device_specific_info_host< info::kernel_device_specific::compile_num_sub_groups >()
template<> uint32_t sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::compile_num_sub_groups > (const sycl::device &) inline
Definition at line 199 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::compile_sub_group_size >()
template<> uint32_t sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::compile_sub_group_size > (const sycl::device &) inline
Definition at line 207 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::compile_work_group_size >()
template<> sycl::range<3> sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::compile_work_group_size > (const sycl::device &) inline
Definition at line 152 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::ext_codeplay_num_regs >()
template<> uint32_t sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::ext_codeplay_num_regs > (const sycl::device &) inline
Definition at line 179 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::global_work_size >()
template<> sycl::range<3> sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::global_work_size > (const sycl::device &) inline
Definition at line 142 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::max_num_sub_groups >()
template<> uint32_t sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::max_num_sub_groups > (const sycl::device &) inline
Definition at line 185 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::max_sub_group_size >()
template<> uint32_t sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::max_sub_group_size > (const sycl::device &) inline
Definition at line 192 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple >()
template<> size_t sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple > (const sycl::device & Dev) inline
Definition at line 165 of file kernel_info.hpp.
References get_kernel_device_specific_info_host(), and sycl::_V1::ext::oneapi::experimental::work_group_size.
get_kernel_device_specific_info_host< info::kernel_device_specific::private_mem_size >()
template<> size_t sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::private_mem_size > (const sycl::device &) inline
Definition at line 173 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::work_group_size >()
template<> size_t sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::work_group_size > (const sycl::device & Dev) inline
Definition at line 152 of file kernel_info.hpp.
get_kernel_device_specific_info_with_input()
template<typename Param > uint32_t sycl::_V1::detail::get_kernel_device_specific_info_with_input (sycl::detail::pi::PiKernel Kernel, sycl::detail::pi::PiDevice Device, sycl::range< 3 > In, const PluginPtr & Plugin)
Definition at line 120 of file kernel_info.hpp.
References piKernelGetSubGroupInfo().
get_kernel_id_impl()
kernel_id sycl::_V1::detail::get_kernel_id_impl (string_view KernelName)
Definition at line 142 of file kernel_bundle.cpp.
References sycl::_V1::detail::string_view::data().
get_kernel_info() [1/2]
template<typename Param > std::enable_if< std::is_same<typename Param::return_type, std::string>::value, std::string>::type sycl::_V1::detail::get_kernel_info (sycl::detail::pi::PiKernel Kernel, const PluginPtr & Plugin)
Definition at line 28 of file kernel_info.hpp.
References piKernelGetInfo().
get_kernel_info() [2/2]
template<typename Param > std::enable_if< std::is_same<typename Param::return_type, uint32_t>::value, uint32_t>::type sycl::_V1::detail::get_kernel_info (sycl::detail::pi::PiKernel Kernel, const PluginPtr & Plugin)
Definition at line 49 of file kernel_info.hpp.
References piKernelGetInfo().
get_local_linear_id()
template<typename Group > auto sycl::_V1::detail::get_local_linear_id (Group g) inline
Definition at line 71 of file group_algorithm.hpp.
Referenced by for_each().
get_local_linear_range()
template<typename Group > auto sycl::_V1::detail::get_local_linear_range (Group g) inline
Definition at line 62 of file group_algorithm.hpp.
Referenced by for_each().
get_native_buffer()
template<backend BackendName, typename DataT , int Dimensions, typename Allocator > auto sycl::_V1::detail::get_native_buffer (const buffer< DataT, Dimensions, Allocator, void > & Obj) -> backend_return_t< BackendName, buffer< DataT, Dimensions, Allocator, void >>
get_or_store()
template<typename T > T sycl::_V1::detail::get_or_store (const T * obj)
Definition at line 60 of file helpers.hpp.
References sycl::_V1::ext::oneapi::experimental::obj.
get_platform_info() [1/2]
template<typename Param > std::enable_if< std::is_same<typename Param::return_type, std::string>::value, std::string>::type sycl::_V1::detail::get_platform_info (sycl::detail::pi::PiPlatform Plt, const PluginPtr & Plugin)
Definition at line 44 of file platform_info.hpp.
References get_platform_info_string_impl().
get_platform_info() [2/2]
template<typename Param > std::enable_if<std::is_same<Param, info::platform::extensions>::value, std::vector<std::string> >::type sycl::_V1::detail::get_platform_info (sycl::detail::pi::PiPlatform Plt, const PluginPtr & Plugin)
Definition at line 54 of file platform_info.hpp.
References get_platform_info_string_impl(), and split_string().
get_platform_info_host()
template<typename Param > Param::return_type sycl::_V1::detail::get_platform_info_host () inline delete
get_platform_info_host< info::platform::extensions >()
template<> std::vector<std::string> sycl::_V1::detail::get_platform_info_host< info::platform::extensions > () inline
Definition at line 81 of file platform_info.hpp.
get_platform_info_host< info::platform::name >()
template<> std::string sycl::_V1::detail::get_platform_info_host< info::platform::name > () inline
Definition at line 76 of file platform_info.hpp.
get_platform_info_host< info::platform::profile >()
template<> std::string sycl::_V1::detail::get_platform_info_host< info::platform::profile > () inline
Definition at line 67 of file platform_info.hpp.
get_platform_info_host< info::platform::vendor >()
template<> std::string sycl::_V1::detail::get_platform_info_host< info::platform::vendor > () inline
Definition at line 81 of file platform_info.hpp.
get_platform_info_host< info::platform::version >()
template<> std::string sycl::_V1::detail::get_platform_info_host< info::platform::version > () inline
Definition at line 72 of file platform_info.hpp.
get_platform_info_string_impl()
std::string sycl::_V1::detail::get_platform_info_string_impl (sycl::detail::pi::PiPlatform Plt, const PluginPtr & Plugin, pi_platform_info PiCode) inline
Definition at line 23 of file platform_info.hpp.
References piPlatformGetInfo().
Referenced by get_platform_info(), and sycl::_V1::detail::platform_impl::has_extension().
get_spec_constant_symbolic_ID()
template<auto & SpecName> const char * sycl::_V1::detail::get_spec_constant_symbolic_ID ()
Definition at line 19 of file spec_const_integration.hpp.
get_spec_constant_symbolic_ID_impl()
template<auto & SpecName> const char* sycl::_V1::detail::get_spec_constant_symbolic_ID_impl ()
get_tuple_tail()
template<typename T , typename... Ts> std::tuple<Ts...> sycl::_V1::detail::get_tuple_tail (const std::tuple< T, Ts... > & Tuple)
Definition at line 30 of file tuple.hpp.
References get_tuple_tail_impl().
Referenced by sycl::_V1::detail::tuple< T, Ts... >::operator=().
get_tuple_tail_impl()
template<typename T , typename... Ts, std::size_t... Is> std::tuple<Ts...> sycl::_V1::detail::get_tuple_tail_impl (const std::tuple< T, Ts... > & Tuple, const std::index_sequence< Is... > &)
Definition at line 24 of file tuple.hpp.
Referenced by get_tuple_tail().
getAbsVal()
template<typename T > std::make_unsigned_t<T> sycl::_V1::detail::getAbsVal (const T Val, const int Base) inline
Definition at line 165 of file stream.hpp.
Referenced by ScalarToStr().
getAspectNameStr()
static std::string sycl::_V1::detail::getAspectNameStr (sycl::aspect AspectNum) static
Definition at line 2410 of file program_manager.cpp.
References sycl::_V1::kernel_not_supported.
Referenced by checkDevSupportDeviceRequirements(), and syclcompat::device_ext::has_capability_or_fail().
getBinImageFromMultiMap()
template<typename StorageKey > RTDeviceBinaryImage* sycl::_V1::detail::getBinImageFromMultiMap (const std::unordered_multimap< StorageKey, RTDeviceBinaryImage * > & ImagesSet, const StorageKey & Key, const context & Context, const device & Device)
Definition at line 977 of file program_manager.cpp.
References getSyclObjImpl(), and piextDeviceSelectBinary().
Referenced by sycl::_V1::detail::ProgramManager::getDeviceImage().
getBinImageState()
static bundle_state sycl::_V1::detail::getBinImageState (const RTDeviceBinaryImage * BinImage) static
Definition at line 1535 of file program_manager.cpp.
References __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_FPGA, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_X86_64, pi_device_binary_struct::DeviceTargetSpec, and sycl::_V1::detail::RTDeviceBinaryImage::getRawData().
Referenced by sycl::_V1::detail::ProgramManager::getDeviceImageFromBinaryImage().
getBorderColor()
float4 sycl::_V1::detail::getBorderColor (const image_channel_order ImgChannelOrder)
Definition at line 171 of file image_accessor_util.cpp.
References sycl::_V1::luminance, sycl::_V1::r, sycl::_V1::rg, and sycl::_V1::rgb.
Referenced by getColor().
GetCapabilitiesIntersectionSet()
template<typename T , typename Capabilities > void sycl::_V1::detail::GetCapabilitiesIntersectionSet (const std::vector< sycl::device > & Devices, std::vector< T > & CapabilityList)
Definition at line 333 of file context_impl.hpp.
References sycl::_V1::device::get_info().
getColor()
template<typename DataT > DataT sycl::_V1::detail::getColor (const int4 PixelCoord, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, const id< 3 > ImgPitch, const image_channel_type ImgChannelType, const image_channel_order ImgChannelOrder, void * BasePtr, const uint8_t ElementSize)
Definition at line 908 of file image_accessor_util.hpp.
References getBorderColor(), and isOutOfRange().
getCommand()
static Command* sycl::_V1::detail::getCommand (const EventImplPtr & Event) static
Definition at line 20 of file graph_processor.cpp.
Referenced by sycl::_V1::detail::Scheduler::GraphProcessor::waitForEvent().
getDecorated()
template<typename DecorT , typename T , access::address_space Space, access::decorated IsDecorated> DecorT* sycl::_V1::detail::getDecorated (multi_ptr< T, Space, IsDecorated > ptr)
Definition at line 24 of file utils.hpp.
getDelinearizedId() [1/3]
id<1> sycl::_V1::detail::getDelinearizedId (const range< 1 > & , size_t Index) inline
Definition at line 313 of file id.hpp.
Referenced by reduction_parallel_for().
getDelinearizedId() [2/3]
id<2> sycl::_V1::detail::getDelinearizedId (const range< 2 > & Range, size_t Index) inline
Definition at line 317 of file id.hpp.
getDelinearizedId() [3/3]
id<3> sycl::_V1::detail::getDelinearizedId (const range< 3 > & Range, size_t Index) inline
Definition at line 323 of file id.hpp.
getDeviceComparisonLambda()
auto sycl::_V1::detail::getDeviceComparisonLambda ()
getDeviceFromHandler()
device sycl::_V1::detail::getDeviceFromHandler (handler & CommandGroupHandlerRef)
Definition at line 17 of file accessor.cpp.
Referenced by sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::auto_select >::run().
getDeviceLibExtensionStr()
static const char* sycl::_V1::detail::getDeviceLibExtensionStr (DeviceLibExt Extension) static
Definition at line 869 of file program_manager.cpp.
References DeviceLibExtensionStrs.
Referenced by getDeviceLibPrograms().
getDeviceLibFilename()
static const char* sycl::_V1::detail::getDeviceLibFilename (DeviceLibExt Extension, bool Native) static
Definition at line 840 of file program_manager.cpp.
References DeviceLibNames.
Referenced by loadDeviceLibFallback().
getDeviceLibPrograms()
static std::vector<sycl::detail::pi::PiProgram> sycl::_V1::detail::getDeviceLibPrograms (const ContextImplPtr Context, const sycl::detail::pi::PiDevice & Device, uint32_t DeviceLibReqMask) static
Definition at line 1099 of file program_manager.cpp.
References cl_intel_devicelib_assert, cl_intel_devicelib_bfloat16, cl_intel_devicelib_complex, cl_intel_devicelib_complex_fp64, cl_intel_devicelib_cstring, cl_intel_devicelib_imf, cl_intel_devicelib_imf_bf16, cl_intel_devicelib_imf_fp64, cl_intel_devicelib_math, cl_intel_devicelib_math_fp64, getDeviceLibExtensionStr(), isDeviceLibRequired(), and loadDeviceLibFallback().
getDevicePreference()
static int sycl::_V1::detail::getDevicePreference (const device & Device) static
Definition at line 34 of file device_selector.cpp.
References sycl::_V1::ext_oneapi_level_zero, and getSyclObjImpl().
Referenced by select_device().
getDirName()
std::string sycl::_V1::detail::getDirName (const char * Path)
getESIMDDeviceInterface()
ESIMDDeviceInterface* sycl::_V1::detail::getESIMDDeviceInterface ()
Definition at line 32 of file esimd_emulator_device_interface.cpp.
GetFlushBufOffset()
unsigned sycl::_V1::detail::GetFlushBufOffset (const GlobalBufAccessorT & GlobalFlushBuf, unsigned WIOffset) inline
Definition at line 112 of file stream.hpp.
Referenced by flushBuffer(), and write().
getFormatStr()
static const char* sycl::_V1::detail::getFormatStr (sycl::detail::pi::PiDeviceBinaryType Format) static
Definition at line 157 of file program_manager.cpp.
References PI_DEVICE_BINARY_TYPE_LLVMIR_BITCODE, PI_DEVICE_BINARY_TYPE_NATIVE, PI_DEVICE_BINARY_TYPE_NONE, and PI_DEVICE_BINARY_TYPE_SPIRV.
Referenced by sycl::_V1::detail::ProgramManager::createPIProgram(), and sycl::_V1::detail::ProgramManager::ProgramManager().
getImageElementSize()
uint8_t sycl::_V1::detail::getImageElementSize (uint8_t NumChannels, image_channel_type Type)
Definition at line 74 of file image_impl.cpp.
References sycl::_V1::fp16, sycl::_V1::fp32, sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
Referenced by sycl::_V1::detail::image_impl::image_impl(), and sycl::_V1::ext::oneapi::experimental::pitched_alloc_device().
getImageInfo()
template<typename T > static void sycl::_V1::detail::getImageInfo (const ContextImplPtr Context, sycl::detail::pi::PiMemImageInfo Info, T & Dest, sycl::detail::pi::PiMem InteropMemObject) static
Definition at line 263 of file image_impl.cpp.
References piMemImageGetInfo().
getImageNumberChannels()
uint8_t sycl::_V1::detail::getImageNumberChannels (image_channel_order Order)
Definition at line 47 of file image_impl.cpp.
References sycl::_V1::a, sycl::_V1::abgr, sycl::_V1::argb, sycl::_V1::bgra, sycl::_V1::ext_oneapi_srgba, sycl::_V1::intensity, sycl::_V1::luminance, sycl::_V1::r, sycl::_V1::ra, sycl::_V1::rg, sycl::_V1::rgb, sycl::_V1::rgba, sycl::_V1::rgbx, sycl::_V1::rgx, and sycl::_V1::rx.
Referenced by sycl::_V1::ext::oneapi::experimental::get_image_num_channels(), sycl::_V1::ext::oneapi::experimental::image_mem::get_num_channels(), sycl::_V1::detail::image_impl::image_impl(), and sycl::_V1::ext::oneapi::experimental::pitched_alloc_device().
getImageOffset() [1/3]
template<typename T > std::enable_if_t<std::is_integral_v<T>, size_t> sycl::_V1::detail::getImageOffset (const T & Coords, const id< 3 > , const uint8_t ElementSize)
Definition at line 92 of file image_accessor_util.hpp.
Referenced by imageWriteHostImpl(), and ReadPixelData().
getImageOffset() [2/3]
template<typename T > std::enable_if_t<std::is_integral_v<T>, size_t> sycl::_V1::detail::getImageOffset (const vec< T, 2 > & Coords, const id< 3 > ImgPitch, const uint8_t ElementSize)
Definition at line 98 of file image_accessor_util.hpp.
getImageOffset() [3/3]
template<typename T > std::enable_if_t<std::is_integral_v<T>, size_t> sycl::_V1::detail::getImageOffset (const vec< T, 4 > & Coords, const id< 3 > ImgPitch, const uint8_t ElementSize)
Definition at line 105 of file image_accessor_util.hpp.
getImageType()
sycl::detail::pi::PiMemObjectType sycl::_V1::detail::getImageType (int Dimensions)
Definition at line 65 of file sycl_mem_obj_t.cpp.
References sycl::_V1::Dimensions, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE2D, and PI_MEM_TYPE_IMAGE3D.
Referenced by sycl::_V1::detail::SYCLMemObjT::SYCLMemObjT().
getImplBackend()
template<class T > backend sycl::_V1::detail::getImplBackend (const T & Impl)
Definition at line 17 of file backend_impl.hpp.
Referenced by sycl::_V1::event::get_backend(), sycl::_V1::interop_handle::get_backend(), sycl::_V1::kernel::get_backend(), and sycl::_V1::queue::get_backend().
getLastCombine()
template<typename OutAccT , typename LocalAccT , typename BOPT , typename IdentityContainerT > auto sycl::_V1::detail::getLastCombine (OutAccT OutAcc, LocalAccT LocalAcc, BOPT BOP, IdentityContainerT IdentityContainer, bool IsInitializeToIdentity)
Definition at line 2051 of file reduction.hpp.
Referenced by writeReduSumsToOutAccs().
getLinearIndex()
template<int Dims, template< int > class T, template< int > class U> size_t sycl::_V1::detail::getLinearIndex (const T< Dims > & Index, const U< Dims > & Range)
Definition at line 367 of file common.hpp.
Referenced by sycl::_V1::local_accessor_base< DataT, Dimensions, AccessMode, IsPlaceholder >::operator[]().
getLoadOrder()
constexpr memory_order sycl::_V1::detail::getLoadOrder (memory_order order) inline constexpr
Definition at line 73 of file atomic_ref.hpp.
References sycl::_V1::__consume_unsupported, sycl::_V1::acq_rel, sycl::_V1::acquire, sycl::_V1::relaxed, sycl::_V1::release, and sycl::_V1::seq_cst.
Referenced by sycl::_V1::detail::atomic_ref_impl< T *, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace >::fetch_add(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_floating_point_v< T > > >::fetch_add(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >::fetch_max(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_floating_point_v< T > > >::fetch_max(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >::fetch_min(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_floating_point_v< T > > >::fetch_min(), sycl::_V1::detail::atomic_ref_impl< T *, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace >::fetch_sub(), and sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_floating_point_v< T > > >::fetch_sub().
GetMask()
template<typename NonUniformGroup > ext::oneapi::sub_group_mask sycl::_V1::detail::GetMask (NonUniformGroup Group) inline
Definition at line 44 of file non_uniform_groups.hpp.
Referenced by IdToMaskPosition().
getMemObjCreationFlags()
static sycl::detail::pi::PiMemFlags sycl::_V1::detail::getMemObjCreationFlags (void * UserPtr, bool HostPtrReadOnly) static
Definition at line 324 of file memory_manager.cpp.
References PI_MEM_ACCESS_READ_ONLY, PI_MEM_FLAGS_ACCESS_RW, and PI_MEM_FLAGS_HOST_PTR_USE.
Referenced by sycl::_V1::detail::MemoryManager::allocateBufferObject(), and sycl::_V1::detail::MemoryManager::allocateImageObject().
getNextPowerOfTwo()
constexpr size_t sycl::_V1::detail::getNextPowerOfTwo (size_t Var) constexpr
Definition at line 361 of file common.hpp.
References getNextPowerOfTwoHelper().
Referenced by sycl::_V1::detail::image_impl::image_impl().
getNextPowerOfTwoHelper()
constexpr size_t sycl::_V1::detail::getNextPowerOfTwoHelper (size_t Var, size_t Offset) constexpr
Definition at line 354 of file common.hpp.
Referenced by getNextPowerOfTwo().
getOffsetForId()
template<int Dimensions> size_t sycl::_V1::detail::getOffsetForId (range< Dimensions > Range, id< Dimensions > Id, id< Dimensions > Offset)
Definition at line 305 of file id.hpp.
References sycl::_V1::Dimensions.
getOrBuildProgramForDeviceGlobal()
static sycl::detail::pi::PiProgram sycl::_V1::detail::getOrBuildProgramForDeviceGlobal (QueueImplPtr Queue, DeviceGlobalMapEntry * DeviceGlobalEntry) static
Definition at line 1323 of file memory_manager.cpp.
References sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::ProgramManager::getDeviceImage(), sycl::_V1::detail::ProgramManager::getDeviceImageFromBinaryImage(), getSyclObjImpl(), sycl::_V1::detail::DeviceGlobalMapEntry::MImageIdentifiers, sycl::_V1::detail::DeviceGlobalMapEntry::MImages, and sycl::_V1::detail::DeviceGlobalMapEntry::MIsDeviceImageScopeDecorated.
Referenced by memcpyFromDeviceGlobalDirect(), and memcpyToDeviceGlobalDirect().
getOrWaitEvents() [1/2]
std::vector<sycl::detail::pi::PiEvent> sycl::_V1::detail::getOrWaitEvents (std::vector< sycl::event > DepEvents, ContextImplPtr Context)
Definition at line 27 of file helpers.cpp.
References BLOCKING, sycl::_V1::detail::Scheduler::enqueueCommandForCG(), sycl::_V1::detail::Scheduler::getInstance(), and getSyclObjImpl().
getOrWaitEvents() [2/2]
std::vector<sycl::detail::pi::PiEvent> sycl::_V1::detail::getOrWaitEvents (std::vector< sycl::event > DepEvents, std::shared_ptr< sycl::detail::context_impl > Context)
getPIEvents()
static std::vector<sycl::detail::pi::PiEvent> sycl::_V1::detail::getPIEvents (const std::vector< sycl::event > & DepEvents) static
Definition at line 32 of file queue_impl.cpp.
References getSyclObjImpl().
Referenced by sycl::_V1::detail::queue_impl::submitMemOpHelper().
getPiImageCopyFlags()
sycl::detail::pi::PiImageCopyFlags sycl::_V1::detail::getPiImageCopyFlags (sycl::usm::alloc SrcPtrType, sycl::usm::alloc DstPtrType)
Definition at line 48 of file handler.cpp.
References sycl::_V1::invalid, sycl::_V1::make_error_code(), PI_IMAGE_COPY_DEVICE_TO_DEVICE, PI_IMAGE_COPY_DEVICE_TO_HOST, and PI_IMAGE_COPY_HOST_TO_DEVICE.
Referenced by sycl::_V1::handler::ext_oneapi_copy().
getPixelCoordLinearFiltMode()
int8 sycl::_V1::detail::getPixelCoordLinearFiltMode (float4 Coorduvw, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, float4 & Retabc)
Definition at line 92 of file image_accessor_util.cpp.
References sycl::_V1::clamp, sycl::_V1::clamp_to_edge, sycl::_V1::ext::oneapi::fabs(), sycl::_V1::mirrored_repeat, sycl::_V1::none, and sycl::_V1::repeat.
Referenced by imageReadSamplerHostImpl().
getPixelCoordNearestFiltMode()
int4 sycl::_V1::detail::getPixelCoordNearestFiltMode (float4 Coorduvw, const addressing_mode SmplAddrMode, const range< 3 > ImgRange)
Definition at line 19 of file image_accessor_util.cpp.
References sycl::_V1::clamp, sycl::_V1::clamp_to_edge, sycl::_V1::ext::oneapi::fabs(), sycl::_V1::mirrored_repeat, sycl::_V1::none, and sycl::_V1::repeat.
Referenced by imageReadSamplerHostImpl().
getPlugin()
static const PluginPtr& sycl::_V1::detail::getPlugin (backend Backend) static
Definition at line 32 of file backend.cpp.
References codeToString(), sycl::_V1::ext_oneapi_cuda, sycl::_V1::ext_oneapi_hip, sycl::_V1::ext_oneapi_level_zero, and sycl::_V1::opencl.
Referenced by context_impl::get_info< info::context::reference_count >(), event_impl::get_info< info::event::command_execution_status >(), event_impl::get_info< info::event::reference_count >(), event_impl::get_profiling_info< info::event_profiling::command_end >(), event_impl::get_profiling_info< info::event_profiling::command_start >(), event_impl::get_profiling_info< info::event_profiling::command_submit >(), kernel_impl::ext_oneapi_get_info< ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync >(), make_context(), make_device(), make_event(), make_kernel(), make_kernel_bundle(), make_platform(), make_queue(), and queue_impl::get_info< info::queue::reference_count >().
getPluginOpaqueData()
template<sycl::backend BE> void * sycl::_V1::detail::getPluginOpaqueData (void * opaquedata_arg)
Definition at line 61 of file pi.cpp.
References piextPluginGetOpaqueData().
getPluginOpaqueData< sycl::backend::ext_intel_esimd_emulator >()
template void* sycl::_V1::detail::getPluginOpaqueData< sycl::backend::ext_intel_esimd_emulator > (void *)
getRawSyclObjImpl()
template<class T > std::add_pointer_t<typename decltype(T::impl)::element_type> sycl::_V1::detail::getRawSyclObjImpl (const T & SyclObject)
Definition at line 40 of file impl_utils.hpp.
Referenced by sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::ProgramManager::createPIProgram(), sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), and sycl::_V1::detail::ProgramManager::getDeviceImage().
getReducerAccess()
template<typename ReducerT > auto sycl::_V1::detail::getReducerAccess (ReducerT & Reducer)
Definition at line 208 of file reduction.hpp.
Referenced by reduCGFuncImplArrayHelper(), reduCGFuncImplScalar(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::local_atomic_and_atomic_cross_wg >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::range_basic >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_atomic_cross_wg >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::local_mem_tree_and_atomic_cross_wg >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run().
getSPIRVMemorySemanticsMask() [1/2]
constexpr uint32_t sycl::_V1::detail::getSPIRVMemorySemanticsMask (const access::fence_space AccessSpace, const __spv::MemorySemanticsMask LocalScopeMask = __spv::MemorySemanticsMask::WorkgroupMemory) inline constexpr
Definition at line 203 of file helpers.hpp.
References __spv::MemorySemanticsMask::CrossWorkgroupMemory, sycl::_V1::access::global_space, sycl::_V1::access::local_space, and __spv::MemorySemanticsMask::SequentiallyConsistent.
getSPIRVMemorySemanticsMask() [2/2]
constexpr __spv::MemorySemanticsMask::Flag sycl::_V1::detail::getSPIRVMemorySemanticsMask (memory_order) inline constexpr
Definition at line 198 of file helpers.hpp.
References __spv::MemorySemanticsMask::None.
Referenced by sycl::_V1::sub_group::__SYCL_DEPRECATED(), sycl::_V1::nd_item< Dimensions >::barrier(), and sycl::_V1::nd_item< Dimensions >::mem_fence().
getStdMemoryOrder() [1/2]
std::memory_order sycl::_V1::detail::getStdMemoryOrder (__spv::MemorySemanticsMask::Flag) inline
Definition at line 82 of file atomic.hpp.
Referenced by __spirv_AtomicAnd(), __spirv_AtomicExchange(), __spirv_AtomicIAdd(), __spirv_AtomicISub(), __spirv_AtomicLoad(), __spirv_AtomicMax(), __spirv_AtomicMin(), __spirv_AtomicOr(), __spirv_AtomicStore(), __spirv_AtomicXor(), sycl::_V1::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::compare_exchange_strong(), sycl::_V1::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::compare_exchange_weak(), sycl::_V1::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::exchange(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >::fetch_add(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >::fetch_and(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >::fetch_or(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >::fetch_sub(), sycl::_V1::detail::atomic_ref_impl< T, IsAspectAtomic64AttrUsed, DefaultOrder, DefaultScope, AddressSpace, typename std::enable_if_t< std::is_integral_v< T > > >::fetch_xor(), sycl::_V1::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::load(), and sycl::_V1::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::store().
getStdMemoryOrder() [2/2]
static constexpr std::memory_order sycl::_V1::detail::getStdMemoryOrder (sycl::memory_order order) static constexpr
Definition at line 84 of file memory_enums.hpp.
References sycl::_V1::__consume_unsupported, sycl::_V1::acq_rel, sycl::_V1::acquire, sycl::_V1::memory_order_acq_rel, sycl::_V1::memory_order_acquire, sycl::_V1::memory_order_relaxed, sycl::_V1::memory_order_release, sycl::_V1::memory_order_seq_cst, sycl::_V1::relaxed, sycl::_V1::release, and sycl::_V1::seq_cst.
getStrOrNullptr()
constexpr const char* sycl::_V1::detail::getStrOrNullptr (const char * Str) constexpr
Definition at line 61 of file config.hpp.
getSyclBeMap()
const std::array< std::pair< std::string, backend >, 8 > & sycl::_V1::detail::getSyclBeMap ()
Definition at line 169 of file config.cpp.
References sycl::_V1::all, sycl::_V1::ext_oneapi_cuda, sycl::_V1::ext_oneapi_hip, sycl::_V1::ext_oneapi_level_zero, sycl::_V1::ext_oneapi_native_cpu, and sycl::_V1::opencl.
Referenced by applyAllowList(), Parse_ODS_Backend(), and parseAllowList().
getSyclDeviceTypeMap()
template<bool supportAcc = false> const std::array<std::pair<std::string, info::device_type>, 6>& sycl::_V1::detail::getSyclDeviceTypeMap ()
Definition at line 239 of file config.hpp.
References sycl::_V1::info::accelerator, sycl::_V1::info::all, sycl::_V1::info::cpu, sycl::_V1::info::gpu, and sycl::_V1::info::host.
Referenced by Parse_ODS_Device().
getSyclObjImpl()
template<class Obj > decltype(Obj::impl) sycl::_V1::detail::getSyclObjImpl (const Obj & SyclObject)
Definition at line 30 of file impl_utils.hpp.
Referenced by sycl::_V1::detail::kernel_bundle_impl::add_kernel(), sycl::_V1::detail::context_impl::addDeviceGlobalInitializer(), sycl::_V1::detail::queue_impl::addEvent(), sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::addGraphLeafDependencies(), sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::addImpl(), sycl::_V1::detail::usm::alignedAlloc(), sycl::_V1::detail::usm::alignedAllocHost(), sycl::_V1::ext::oneapi::experimental::alloc_image_mem(), sycl::_V1::ext::oneapi::experimental::alloc_mipmap_mem(), appendCompileOptionsFromImage(), sycl::_V1::detail::ProgramManager::bringSYCLDeviceImagesToState(), sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::kernel_bundle_impl::build_from_source(), sycl::_V1::ext::oneapi::experimental::detail::build_from_source(), compatibleWithDevice(), sycl::_V1::detail::ProgramManager::compile(), sycl::_V1::context::context(), sycl::_V1::detail::context_impl::context_impl(), sycl::_V1::detail::pi::contextSetExtendedDeleter(), sycl::_V1::handler::copy(), sycl::_V1::ext::oneapi::experimental::create_image(), createBinaryProgram(), sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::createCommandBuffers(), sycl::_V1::detail::ProgramManager::createPIProgram(), sycl::_V1::handler::depends_on(), sycl::_V1::ext::oneapi::experimental::destroy_external_semaphore(), sycl::_V1::ext::oneapi::experimental::destroy_image_handle(), deviceToString(), sycl::_V1::detail::MemCpyCommand::emitInstrumentationData(), sycl::_V1::detail::MemCpyCommandHost::emitInstrumentationData(), sycl::_V1::detail::UpdateHostRequirementCommand::emitInstrumentationData(), sycl::_V1::detail::KernelFusionCommand::emitInstrumentationData(), sycl::_V1::detail::EmptyCommand::emitInstrumentationData(), sycl::_V1::detail::ReleaseCommand::emitInstrumentationData(), sycl::_V1::detail::AllocaCommandBase::emitInstrumentationData(), sycl::_V1::detail::MapMemObject::emitInstrumentationData(), sycl::_V1::detail::UnMapMemObject::emitInstrumentationData(), sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::end_recording(), enqueueImpCommandBufferKernel(), enqueueImpKernel(), enqueueReadWriteHostPipe(), sycl::_V1::detail::event_impl::ensureContextInitialized(), sycl::_V1::platform::ext_oneapi_get_default_context(), sycl::_V1::detail::kernel_bundle_impl::ext_oneapi_get_kernel(), sycl::_V1::handler::ext_oneapi_graph(), sycl::_V1::detail::OwnerLessBase< SyclObjT >::ext_oneapi_owner_before(), sycl::_V1::queue::ext_oneapi_submit_barrier(), sycl::_V1::detail::queue_impl::finalizeHandler(), sycl::_V1::detail::context_impl::findMatchingDeviceImpl(), sycl::_V1::detail::stream_impl::flush(), sycl::_V1::detail::program_impl::flush_spec_constants(), sycl::_V1::detail::usm::free(), sycl::_V1::ext::oneapi::experimental::free_image_mem(), sycl::_V1::ext::oneapi::experimental::free_mipmap_mem(), sycl::_V1::ext::codeplay::experimental::fusion_wrapper::fusion_wrapper(), sycl::_V1::ext::oneapi::experimental::get_image_channel_type(), sycl::_V1::ext::oneapi::experimental::get_image_num_channels(), sycl::_V1::ext::oneapi::experimental::get_image_range(), sycl::_V1::detail::kernel_impl::get_info(), sycl::_V1::detail::kernel_bundle_impl::get_kernel(), sycl::_V1::detail::kernel_bundle_impl::get_kernel_ids(), sycl::_V1::ext::oneapi::experimental::get_mip_level_mem_handle(), sycl::_V1::interop_handle::get_native_mem(), sycl::_V1::ext::oneapi::experimental::node::get_node_from_event(), sycl::_V1::detail::platform_impl::get_platforms(), sycl::_V1::detail::device_image_impl::get_spec_const_buffer_ref(), sycl::_V1::detail::kernel_bundle_impl::get_specialization_constant_raw_value(), getBinImageFromMultiMap(), sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), sycl::_V1::detail::queue_impl::getDefaultOrNew(), sycl::_V1::detail::ProgramManager::getDeviceImage(), getDevicePreference(), sycl::_V1::detail::device_image_impl::getNative(), getOrBuildProgramForDeviceGlobal(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), sycl::_V1::detail::ProgramManager::getOrCreatePIProgram(), sycl::_V1::detail::sampler_impl::getOrCreateSampler(), sycl::_V1::detail::Scheduler::GraphBuilder::getOrInsertMemObjRecord(), getOrWaitEvents(), getPIEvents(), sycl::_V1::detail::context_impl::getProgramForDevImgs(), getValueFromDynamicParameter(), sycl::_V1::ext::oneapi::detail::weak_object_base< SYCLObjT >::GetWeakImpl(), sycl::_V1::opencl::has_extension(), sycl::_V1::detail::device_image_impl::has_kernel(), has_kernel_bundle_impl(), sycl::_V1::detail::context_impl::hasDevice(), sycl::_V1::ext::oneapi::experimental::import_external_memory< resource_fd >(), sycl::_V1::ext::oneapi::experimental::import_external_semaphore(), sycl::_V1::detail::stream_impl::initStreamHost(), sycl::_V1::detail::queue_impl::instrumentationProlog(), IsBannedPlatform(), isDeviceBinaryTypeSupported(), sycl::_V1::detail::context_impl::isDeviceValid(), sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl(), sycl::_V1::detail::ProgramManager::link(), sycl::_V1::ext::oneapi::level_zero::make_context(), sycl::_V1::ext::oneapi::level_zero::make_device(), sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::make_edge(), make_event(), make_kernel(), make_kernel_bundle(), sycl::_V1::ext::oneapi::level_zero::make_queue(), sycl::_V1::opencl::make_queue(), make_queue(), sycl::_V1::ext::oneapi::experimental::map_external_image_memory(), std::hash< sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder > >::operator()(), std::hash< sycl::host_accessor< DataT, Dimensions, AccessMode > >::operator()(), std::hash< sycl::local_accessor< DataT, Dimensions > >::operator()(), std::hash< sycl::unsampled_image_accessor< DataT, Dimensions, AccessMode, AccessTarget > >::operator()(), std::hash< sycl::host_unsampled_image_accessor< DataT, Dimensions, AccessMode > >::operator()(), std::hash< sycl::sampled_image_accessor< DataT, Dimensions, AccessTarget > >::operator()(), std::hash< sycl::host_sampled_image_accessor< DataT, Dimensions > >::operator()(), sycl::_V1::ext::oneapi::detail::filter_selector_impl::operator()(), std::hash< sycl::buffer< T, dimensions, AllocatorT > >::operator()(), std::hash< sycl::context >::operator()(), std::hash< sycl::device >::operator()(), std::hash< sycl::device_image< State > >::operator()(), std::hash< sycl::event >::operator()(), std::hash< sycl::ext::oneapi::experimental::image_mem >::operator()(), std::hash< sycl::image< Dimensions, AllocatorT > >::operator()(), std::hash< sycl::kernel >::operator()(), std::hash< sycl::kernel_bundle< State > >::operator()(), std::hash< sycl::kernel_id >::operator()(), std::hash< sycl::platform >::operator()(), std::hash< sycl::queue >::operator()(), std::hash< sycl::sampled_image< Dimensions, AllocatorT > >::operator()(), std::hash< sycl::sampler >::operator()(), std::hash< sycl::stream >::operator()(), std::hash< sycl::unsampled_image< Dimensions, AllocatorT > >::operator()(), sycl::_V1::detail::LessByHash< T >::operator()(), sycl::_V1::handler::parallel_for(), sycl::_V1::handler::parallel_for_work_group(), sycl::_V1::ext::oneapi::experimental::pitched_alloc_device(), prepareSYCLEventAssociatedWithQueue(), sycl::_V1::detail::PersistentDeviceCodeCache::putItemToDisc(), sycl::_V1::queue::queue(), sycl::_V1::ext::oneapi::experimental::release_external_memory(), sycl::_V1::detail::DeviceGlobalMapEntry::removeAssociatedResources(), sycl::_V1::detail::sampler_impl::sampler_impl(), sycl::_V1::detail::Scheduler::Scheduler(), sycl::_V1::detail::kernel_bundle_impl::set_specialization_constant_raw_value(), SetArgBasedOnType(), sycl::_V1::handler::single_task(), sycl::_V1::detail::queue_impl::submitMemOpHelper(), sycl::_V1::ext::oneapi::experimental::detail::executable_command_graph::update(), sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::update(), sycl::_V1::handler::update_host(), sycl::_V1::ext::oneapi::experimental::detail::node_impl::updateAccessor(), sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::updateImpl(), sycl::_V1::handler::use_kernel_bundle(), sycl::_V1::ext::intel::experimental::pipe_base::wait_non_blocking(), waitEvents(), sycl::_V1::detail::device_image_impl::~device_image_impl(), sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::~exec_graph_impl(), and sycl::_V1::detail::sampler_impl::~sampler_impl().
getTimestamp()
static uint64_t sycl::_V1::detail::getTimestamp () inline static
Definition at line 116 of file event_impl.cpp.
Referenced by sycl::_V1::detail::HostProfilingInfo::end(), sycl::_V1::detail::event_impl::setHostEnqueueTime(), sycl::_V1::detail::event_impl::setSubmissionTime(), and sycl::_V1::detail::HostProfilingInfo::start().
getUint32PropAsBool()
static bool sycl::_V1::detail::getUint32PropAsBool (const RTDeviceBinaryImage & Img, const char * PropName) static
Definition at line 252 of file program_manager.cpp.
References sycl::_V1::detail::DeviceBinaryProperty::asUint32(), and sycl::_V1::detail::RTDeviceBinaryImage::getProperty().
Referenced by appendCompileOptionsFromImage(), and checkDevSupportDeviceRequirements().
getUint32PropAsOptStr()
static std::string sycl::_V1::detail::getUint32PropAsOptStr (const RTDeviceBinaryImage & Img, const char * PropName) static
Definition at line 258 of file program_manager.cpp.
References sycl::_V1::detail::DeviceBinaryProperty::asUint32(), and sycl::_V1::detail::RTDeviceBinaryImage::getProperty().
Referenced by appendCompileOptionsFromImage().
GetUnqualMultiPtr()
template<typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>> multi_ptr<T, Space, IsDecorated> sycl::_V1::detail::GetUnqualMultiPtr (const multi_ptr< CVT, Space, IsDecorated > & Mptr) inline
Definition at line 120 of file sub_group.hpp.
Referenced by sycl::_V1::sub_group::load().
getValueFromDynamicParameter()
void * sycl::_V1::detail::getValueFromDynamicParameter (ext::oneapi::experimental::detail::dynamic_parameter_base & DynamicParamBase)
Definition at line 75 of file handler.cpp.
References getSyclObjImpl().
Referenced by sycl::_V1::handler::require().
GetZeroDimAccessRange()
template<typename BufferT > sycl::range<1> sycl::_V1::detail::GetZeroDimAccessRange (BufferT Buffer)
Definition at line 287 of file accessor.hpp.
GreatestPowerOfTwo()
size_t sycl::_V1::detail::GreatestPowerOfTwo (size_t N) inline
Computes the greatest power-of-two less than or equal to N.
Definition at line 1383 of file reduction.hpp.
Referenced by doTreeReductionHelper().
half2Float()
__SYCL_CONSTEXPR_HALF float sycl::_V1::detail::half2Float (const uint16_t & Val) inline
Definition at line 107 of file half_type.hpp.
References __builtin_expect.
Referenced by sycl::_V1::detail::host_half_impl::half::operator float().
handleVisitedNodes()
static void sycl::_V1::detail::handleVisitedNodes (std::vector< Command * > & Visited) static
Definition at line 142 of file graph_builder.cpp.
References sycl::_V1::detail::Command::FUSION, and sycl::_V1::detail::KernelFusionCommand::readyForDeletion().
has_kernel_bundle_impl() [1/2]
bool sycl::_V1::detail::has_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, bundle_state State)
Definition at line 180 of file kernel_bundle.cpp.
References checkAllDevicesAreInContext(), and checkAllDevicesHaveAspect().
has_kernel_bundle_impl() [2/2]
bool sycl::_V1::detail::has_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, const std::vector< kernel_id > & kernelIds, bundle_state State)
Definition at line 203 of file kernel_bundle.cpp.
References all_of(), checkAllDevicesAreInContext(), and getSyclObjImpl().
identity_for_ga_op() [1/3]
template<typename T , class BinaryOperation > constexpr std::enable_if_t< (is_complex<T>::value && is_plus<T, BinaryOperation>::value), T> sycl::_V1::detail::identity_for_ga_op () constexpr
Definition at line 170 of file group_algorithm.hpp.
identity_for_ga_op() [2/3]
template<typename T , class BinaryOperation > constexpr std::enable_if_t< (is_complex<T>::value && is_multiplies<T, BinaryOperation>::value), T> sycl::_V1::detail::identity_for_ga_op () constexpr
Definition at line 177 of file group_algorithm.hpp.
identity_for_ga_op() [3/3]
template<typename T , class BinaryOperation > constexpr std::enable_if_t<!is_complex<T>::value, T> sycl::_V1::detail::identity_for_ga_op () constexpr
Definition at line 182 of file group_algorithm.hpp.
IdToMaskPosition()
template<typename NonUniformGroup > uint32_t sycl::_V1::detail::IdToMaskPosition (NonUniformGroup Group, uint32_t Id) inline
Definition at line 49 of file non_uniform_groups.hpp.
References ExtractMask(), and GetMask().
imageReadSamplerHostImpl() [1/3]
template<typename CoordT , typename DataT > DataT sycl::_V1::detail::imageReadSamplerHostImpl (const CoordT & Coords, const image_sampler & Smpl, range< 3 > ImgRange, id< 3 > ImgPitch, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void * BasePtr, uint8_t ElementSize)
Definition at line 1147 of file image_accessor_util.hpp.
References sycl::_V1::image_sampler::addressing, sycl::_V1::image_sampler::coordinate, and sycl::_V1::image_sampler::filtering.
imageReadSamplerHostImpl() [2/3]
template<typename CoordT , typename DataT > DataT sycl::_V1::detail::imageReadSamplerHostImpl (const CoordT & Coords, const sampler & Smpl, range< 3 > ImgRange, id< 3 > ImgPitch, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void * BasePtr, uint8_t ElementSize)
Definition at line 1128 of file image_accessor_util.hpp.
imageReadSamplerHostImpl() [3/3]
template<typename CoordT , typename DataT > DataT sycl::_V1::detail::imageReadSamplerHostImpl (const CoordT & Coords, coordinate_normalization_mode SmplNormMode, addressing_mode SmplAddrMode, filtering_mode SmplFiltMode, range< 3 > ImgRange, id< 3 > ImgPitch, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void * BasePtr, uint8_t ElementSize)
Definition at line 1029 of file image_accessor_util.hpp.
References sycl::_V1::clamp, sycl::_V1::clamp_to_edge, convertToFloat4(), getPixelCoordLinearFiltMode(), getPixelCoordNearestFiltMode(), sycl::_V1::linear, sycl::_V1::mirrored_repeat, sycl::_V1::nearest, sycl::_V1::none, sycl::_V1::normalized, sycl::_V1::repeat, UnnormalizeCoordinates(), and sycl::_V1::unnormalized.
imageWriteHostImpl()
template<typename CoordT , typename WriteDataT > void sycl::_V1::detail::imageWriteHostImpl (const CoordT & Coords, const WriteDataT & Color, id< 3 > ImgPitch, uint8_t ElementSize, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void * BasePtr)
Definition at line 702 of file image_accessor_util.hpp.
References sycl::_V1::fp16, sycl::_V1::fp32, getImageOffset(), sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, sycl::_V1::unsigned_int8, and writePixel().
Referenced by sycl::_V1::detail::UnsampledImageAccessorBaseHost::write(), and sycl::_V1::detail::image_accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >::write().
initValue()
static void sycl::_V1::detail::initValue (const char * Key, const char * Value) static
Definition at line 41 of file config.cpp.
Referenced by readConfig().
insertMapUnmapForLinkedCmds()
static Command* sycl::_V1::detail::insertMapUnmapForLinkedCmds (AllocaCommandBase * AllocaCmdSrc, AllocaCommandBase * AllocaCmdDst, access::mode MapMode) static
Definition at line 314 of file graph_builder.cpp.
References sycl::_V1::detail::Command::getQueue(), sycl::_V1::detail::AllocaCommandBase::getRequirement(), sycl::_V1::detail::AllocaCommandBase::MIsActive, sycl::_V1::detail::AllocaCommandBase::MLinkedAllocaCmd, and sycl::_V1::detail::AllocaCommandBase::MMemAllocation.
integralToBase()
template<typename T > std::enable_if_t<std::is_integral_v<T>, unsigned> sycl::_V1::detail::integralToBase (T Val, int Base, char * Digits) inline
Definition at line 179 of file stream.hpp.
References digitToChar().
Referenced by ScalarToStr().
is_aot_for_architecture()
constexpr static bool sycl::_V1::detail::is_aot_for_architecture (ext::oneapi::experimental::architecture arch) static constexpr
Definition at line 820 of file device_architecture.hpp.
References get_current_architecture_aot().
Referenced by device_architecture_is().
is_sycl_partition_property()
static bool sycl::_V1::detail::is_sycl_partition_property (info::partition_property PP) static
Definition at line 376 of file device_info.hpp.
References sycl::_V1::info::ext_intel_partition_by_cslice, sycl::_V1::info::no_partition, sycl::_V1::info::partition_by_affinity_domain, sycl::_V1::info::partition_by_counts, and sycl::_V1::info::partition_equally.
Referenced by sycl::_V1::detail::get_device_info_impl< std::vector< info::partition_property >, info::device::partition_properties >::get().
isAccessModeAllowed()
static bool sycl::_V1::detail::isAccessModeAllowed (access::mode Required, access::mode Current) static
Checks if the required access mode is allowed under the current one.
Definition at line 64 of file graph_builder.cpp.
References sycl::_V1::access::atomic, sycl::_V1::access::discard_read_write, sycl::_V1::access::discard_write, sycl::_V1::access::read, sycl::_V1::access::read_write, and sycl::_V1::access::write.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::addHostAccessor().
IsBannedPlatform()
static bool sycl::_V1::detail::IsBannedPlatform (platform Platform) static
Definition at line 75 of file platform_impl.cpp.
References std::cout, sycl::_V1::platform::get_info(), getSyclObjImpl(), sycl::_V1::opencl, sycl::_V1::detail::pi::PI_TRACE_ALL, and sycl::_V1::detail::pi::trace().
Referenced by sycl::_V1::detail::platform_impl::get_platforms().
isDeviceBinaryTypeSupported()
static bool sycl::_V1::detail::isDeviceBinaryTypeSupported (const context & C, sycl::detail::pi::PiDeviceBinaryType Format) static
Definition at line 114 of file program_manager.cpp.
References sycl::_V1::ext_oneapi_cuda, sycl::_V1::context::get_devices(), sycl::_V1::platform::get_info(), sycl::_V1::context::get_platform(), getSyclObjImpl(), sycl::_V1::opencl, and PI_DEVICE_BINARY_TYPE_SPIRV.
Referenced by sycl::_V1::detail::ProgramManager::createPIProgram().
isDeviceGlobalUsedInKernel()
bool sycl::_V1::detail::isDeviceGlobalUsedInKernel (const void * DeviceGlobalPtr)
Definition at line 40 of file handler.cpp.
References sycl::_V1::detail::ProgramManager::getDeviceGlobalEntry(), sycl::_V1::detail::ProgramManager::getInstance(), and sycl::_V1::detail::DeviceGlobalMapEntry::MImageIdentifiers.
Referenced by sycl::_V1::queue::memcpy(), and sycl::_V1::handler::memcpy().
isDeviceLibRequired()
static bool sycl::_V1::detail::isDeviceLibRequired (DeviceLibExt Ext, uint32_t DeviceLibReqMask) static
Definition at line 1091 of file program_manager.cpp.
References cl_intel_devicelib_assert.
Referenced by getDeviceLibPrograms().
isFastMathInf()
template<typename T > detail::enable_if_t< std::is_same<T, float>::value || std::is_same<T, double>::value, bool> sycl::_V1::detail::isFastMathInf (T Val) inline
Definition at line 270 of file stream.hpp.
References D2I64(), and F2I32().
Referenced by checkForInfNan().
isFastMathNan()
template<typename T > detail::enable_if_t< std::is_same<T, float>::value || std::is_same<T, double>::value, bool> sycl::_V1::detail::isFastMathNan (T Val) inline
Definition at line 283 of file stream.hpp.
References D2I64(), and F2I32().
Referenced by checkForInfNan().
isFastMathSignBit()
template<typename T > detail::enable_if_t< std::is_same<T, float>::value || std::is_same<T, double>::value, bool> sycl::_V1::detail::isFastMathSignBit (T Val) inline
Definition at line 296 of file stream.hpp.
References D2I64(), and F2I32().
Referenced by checkForInfNan().
isHostAccessorCmd()
static bool sycl::_V1::detail::isHostAccessorCmd (Command * Cmd) inline static
Definition at line 33 of file leaves_collection.cpp.
References sycl::_V1::detail::Command::EMPTY_TASK, sycl::_V1::detail::Command::getType(), sycl::_V1::detail::Command::HostAccessor, and sycl::_V1::detail::Command::MBlockReason.
Referenced by sycl::_V1::detail::LeavesCollection::push_back(), and sycl::_V1::detail::LeavesCollection::remove().
isInteropHostTask()
static bool sycl::_V1::detail::isInteropHostTask (ExecCGCommand * Cmd) static
Definition at line 910 of file graph_builder.cpp.
References sycl::_V1::detail::ExecCGCommand::getCG(), sycl::_V1::detail::CG::getType(), and sycl::_V1::detail::CGHostTask::MHostTask.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::addCG().
isKernelLambdaCallableWithKernelHandlerImpl()
template<typename KernelType , typename LambdaArgType , typename std::enable_if_t< std::is_same_v< LambdaArgType, void >> * = nullptr> constexpr bool sycl::_V1::detail::isKernelLambdaCallableWithKernelHandlerImpl () constexpr
Definition at line 173 of file cg_types.hpp.
isMatrixSupportedByHW()
bool sycl::_V1::detail::isMatrixSupportedByHW (const std::string & MatrixTypeStrUser, size_t RowsUser, size_t ColsUser, matrix_ext::matrix_type MatrixTypeRuntime, size_t MaxRowsRuntime, size_t MaxColsRuntime, size_t RowsRuntime, size_t ColsRuntime)
Definition at line 2487 of file program_manager.cpp.
References convertMatrixTypeStringMatrixTypeEnumValue().
Referenced by checkDevSupportJointMatrix().
isOutOfRange()
bool sycl::_V1::detail::isOutOfRange (const int4 PixelCoord, const addressing_mode SmplAddrMode, const range< 3 > ImgRange)
Definition at line 153 of file image_accessor_util.cpp.
References sycl::_V1::clamp, and sycl::_V1::none.
Referenced by getColor().
isPartOfFusion()
static bool sycl::_V1::detail::isPartOfFusion (Command * Cmd, KernelFusionCommand * Fusion) static
Definition at line 1474 of file graph_builder.cpp.
References sycl::_V1::detail::Command::getType(), and sycl::_V1::detail::Command::RUN_CG.
Referenced by createsCircularDependency().
IsSuitableSubReq()
static bool sycl::_V1::detail::IsSuitableSubReq (const Requirement * Req) static
Checks if current requirement is requirement for sub buffer.
Definition at line 59 of file graph_builder.cpp.
References sycl::_V1::detail::AccessorImplHost::MIsSubBuffer.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::findAllocaForReq().
IsSupportedImageFormat()
static bool sycl::_V1::detail::IsSupportedImageFormat (sycl::detail::pi::PiDeviceBinaryType Format) static
Definition at line 57 of file persistent_device_code_cache.cpp.
References PI_DEVICE_BINARY_TYPE_NATIVE, and PI_DEVICE_BINARY_TYPE_SPIRV.
isTargetHostAccess()
constexpr bool sycl::_V1::detail::isTargetHostAccess (access::target T) constexpr
Definition at line 98 of file access.hpp.
References sycl::_V1::access::host_image.
isValidVectorSize()
constexpr bool sycl::_V1::detail::isValidVectorSize (int N) constexpr
Definition at line 193 of file vector.hpp.
ItemToStr()
template<int Dimensions> unsigned sycl::_V1::detail::ItemToStr (char * Buf, const item< Dimensions, false > & Item) inline
Definition at line 718 of file stream.hpp.
References append(), ArrayToStr(), sycl::_V1::item< Dimensions, with_offset >::get_id(), and sycl::_V1::item< Dimensions, with_offset >::get_range().
Referenced by writeHItem().
join_impl()
std::shared_ptr< detail::kernel_bundle_impl > sycl::_V1::detail::join_impl (const std::vector< detail::KernelBundleImplPtr > & Bundles, bundle_state State)
Definition at line 175 of file kernel_bundle.cpp.
joint_matrix_layout_to_spv()
__SYCL_ALWAYS_INLINE __spv::MatrixLayout sycl::_V1::detail::joint_matrix_layout_to_spv (sycl::ext::oneapi::experimental::matrix::layout Layout) inline
Definition at line 71 of file matrix-unified-utils.hpp.
References __spv::ColumnMajor, __spv::Dynamic, __spv::Packed, and __spv::RowMajor.
Referenced by sycl::_V1::ext::oneapi::experimental::matrix::joint_matrix_load(), sycl::_V1::ext::intel::experimental::matrix::joint_matrix_load_checked(), sycl::_V1::ext::oneapi::experimental::matrix::joint_matrix_store(), and sycl::_V1::ext::intel::experimental::matrix::joint_matrix_store_checked().
kernel_impl::ext_oneapi_get_info< ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync >()
template<> ext::oneapi::experimental::info::kernel_queue_specific:: max_num_work_group_sync::return_type sycl::_V1::detail::kernel_impl::ext_oneapi_get_info< ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync > (const queue & Queue) const inline
Definition at line 273 of file kernel_impl.hpp.
References getPlugin(), and piextKernelSuggestMaxCooperativeGroupCount().
kernel_impl::get_backend_info< info::device::backend_version >()
template<> info::device::backend_version::return_type sycl::_V1::detail::kernel_impl::get_backend_info< info::device::backend_version > () const
Definition at line 158 of file kernel_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::ext_oneapi_level_zero.
kernel_impl::get_backend_info< info::device::version >()
template<> info::device::version::return_type sycl::_V1::detail::kernel_impl::get_backend_info< info::device::version > () const
Definition at line 141 of file kernel_impl.cpp.
References sycl::_V1::backend_mismatch, sycl::_V1::default_selector_v(), sycl::_V1::device::get_info(), sycl::_V1::opencl, and select_device().
kernel_impl::get_backend_info< info::platform::version >()
template<> info::platform::version::return_type sycl::_V1::detail::kernel_impl::get_backend_info< info::platform::version > () const
Definition at line 126 of file kernel_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::opencl.
kernel_impl::get_info< info::kernel::context >()
template<> context sycl::_V1::detail::kernel_impl::get_info< info::kernel::context > () const inline
Definition at line 232 of file kernel_impl.hpp.
linear_id_to_id() [1/4]
template<> id<1> sycl::_V1::detail::linear_id_to_id (range< 1 > , size_t linear_id) inline
Definition at line 44 of file group_algorithm.hpp.
linear_id_to_id() [2/4]
template<> id<2> sycl::_V1::detail::linear_id_to_id (range< 2 > r, size_t linear_id) inline
Definition at line 47 of file group_algorithm.hpp.
References sycl::_V1::r.
linear_id_to_id() [3/4]
template<> id<3> sycl::_V1::detail::linear_id_to_id (range< 3 > r, size_t linear_id) inline
Definition at line 53 of file group_algorithm.hpp.
References sycl::_V1::r.
linear_id_to_id() [4/4]
template<int Dimensions> id<Dimensions> sycl::_V1::detail::linear_id_to_id (range< Dimensions > , size_t linear_id)
link_impl()
std::shared_ptr< detail::kernel_bundle_impl > sycl::_V1::detail::link_impl (const std::vector< kernel_bundle< bundle_state::object >> & ObjectBundles, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 260 of file kernel_bundle.cpp.
loadDeviceLib()
static bool sycl::_V1::detail::loadDeviceLib (const ContextImplPtr Context, const char * Name, sycl::detail::pi::PiProgram & Prog) static
Definition at line 794 of file program_manager.cpp.
References createSpirvProgram(), sycl::_V1::detail::OSUtil::DirSep, and sycl::_V1::detail::OSUtil::getCurrentDSODir().
Referenced by loadDeviceLibFallback().
loadDeviceLibFallback()
static sycl::detail::pi::PiProgram sycl::_V1::detail::loadDeviceLibFallback (const ContextImplPtr Context, DeviceLibExt Extension, const sycl::detail::pi::PiDevice & Device, bool UseNativeLib) static
Definition at line 878 of file program_manager.cpp.
References getDeviceLibFilename(), sycl::_V1::detail::ProgramManager::getProgramBuildLog(), loadDeviceLib(), and piProgramCompile().
Referenced by getDeviceLibPrograms().
loop()
template<size_t count, class F > void sycl::_V1::detail::loop (F && f)
Definition at line 253 of file helpers.hpp.
References loop_impl().
loop_impl()
template<size_t... Inds, class F > void sycl::_V1::detail::loop_impl (std::integer_sequence< size_t, Inds... > , F && f)
Definition at line 249 of file helpers.hpp.
Referenced by loop().
make_buffer_helper()
template<typename T , int Dimensions, typename AllocatorT > buffer<T, Dimensions, AllocatorT, void> sycl::_V1::detail::make_buffer_helper (pi_native_handle Handle, const context & Ctx, event Evt = {}, bool OwnNativeHandle = true)
Definition at line 71 of file buffer.hpp.
make_context()
context sycl::_V1::detail::make_context (pi_native_handle NativeHandle, const async_handler & Handler, backend Backend)
Definition at line 94 of file backend.cpp.
References getPlugin(), and piextContextCreateWithNativeHandle().
Referenced by sycl::_V1::opencl::make_context().
make_device()
device sycl::_V1::detail::make_device (pi_native_handle NativeHandle, backend Backend)
Definition at line 82 of file backend.cpp.
References getPlugin(), and piextDeviceCreateWithNativeHandle().
Referenced by sycl::_V1::opencl::make_device().
make_event() [1/2]
event sycl::_V1::detail::make_event (pi_native_handle NativeHandle, const context & TargetContext, backend Backend)
Definition at line 141 of file backend.cpp.
Referenced by sycl::_V1::ext::oneapi::level_zero::make_event().
make_event() [2/2]
event sycl::_V1::detail::make_event (pi_native_handle NativeHandle, const context & TargetContext, bool KeepOwnership, backend Backend)
Definition at line 146 of file backend.cpp.
References getPlugin(), getSyclObjImpl(), sycl::_V1::opencl, piEventRetain(), and piextEventCreateWithNativeHandle().
make_kernel() [1/2]
kernel sycl::_V1::detail::make_kernel (const context & TargetContext, const kernel_bundle< bundle_state::executable > & KernelBundle, pi_native_handle NativeKernelHandle, bool KeepOwnership, backend Backend)
Definition at line 252 of file backend.cpp.
References sycl::_V1::kernel_bundle< State >::begin(), codeToString(), sycl::_V1::ext_oneapi_level_zero, getPlugin(), getSyclObjImpl(), sycl::_V1::opencl, piextKernelCreateWithNativeHandle(), and piKernelRetain().
make_kernel() [2/2]
kernel sycl::_V1::detail::make_kernel (pi_native_handle NativeHandle, const context & TargetContext, backend Backend)
Definition at line 295 of file backend.cpp.
make_kernel_bundle() [1/2]
std::shared_ptr< detail::kernel_bundle_impl > sycl::_V1::detail::make_kernel_bundle (pi_native_handle NativeHandle, const context & TargetContext, bool KeepOwnership, bundle_state State, backend Backend)
Definition at line 165 of file backend.cpp.
References sycl::_V1::build, codeToString(), sycl::_V1::executable, getPlugin(), getSyclObjImpl(), sycl::_V1::input, sycl::_V1::object, sycl::_V1::opencl, PI_PROGRAM_BINARY_TYPE_COMPILED_OBJECT, PI_PROGRAM_BINARY_TYPE_EXECUTABLE, PI_PROGRAM_BINARY_TYPE_LIBRARY, PI_PROGRAM_BINARY_TYPE_NONE, PI_PROGRAM_BUILD_INFO_BINARY_TYPE, PI_PROGRAM_INFO_DEVICES, PI_PROGRAM_INFO_NUM_DEVICES, piextProgramCreateWithNativeHandle(), piProgramBuild(), piProgramCompile(), piProgramGetBuildInfo(), piProgramGetInfo(), piProgramLink(), and piProgramRetain().
make_kernel_bundle() [2/2]
std::shared_ptr< detail::kernel_bundle_impl > sycl::_V1::detail::make_kernel_bundle (pi_native_handle NativeHandle, const context & TargetContext, bundle_state State, backend Backend)
Definition at line 247 of file backend.cpp.
make_platform()
platform sycl::_V1::detail::make_platform (pi_native_handle NativeHandle, backend Backend)
Definition at line 70 of file backend.cpp.
References sycl::_V1::detail::platform_impl::getOrMakePlatformImpl(), getPlugin(), and piextPlatformCreateWithNativeHandle().
Referenced by sycl::_V1::ext::oneapi::level_zero::make_platform(), and sycl::_V1::opencl::make_platform().
make_queue()
queue sycl::_V1::detail::make_queue (pi_native_handle NativeHandle, int32_t nativeHandleDesc, const context & TargetContext, const device * TargetDevice, bool KeepOwnership, const property_list & PropList, const async_handler & Handler, backend Backend)
Definition at line 107 of file backend.cpp.
References sycl::_V1::detail::queue_impl::createPiQueueProperties(), getPlugin(), getSyclObjImpl(), sycl::_V1::property_list::has_property(), sycl::_V1::invalid, sycl::_V1::make_error_code(), OOO, Ordered, PI_QUEUE_FLAGS, and piextQueueCreateWithNativeHandle().
Referenced by sycl::_V1::ext::oneapi::level_zero::make_queue(), and sycl::_V1::opencl::make_queue().
make_reduction()
template<class BinaryOp , int Dims, size_t Extent, bool ExplicitIdentity, typename RedOutVar , typename... RestTy> auto sycl::_V1::detail::make_reduction (RedOutVar RedVar, RestTy &&... Rest)
Definition at line 1158 of file reduction.hpp.
make_tuple()
template<typename... Ts> constexpr tuple<Ts...> sycl::_V1::detail::make_tuple (Ts... Args) constexpr
Definition at line 35 of file tuple.hpp.
Referenced by sycl::_V1::ext::oneapi::detail::wi_element< T, NumRows, NumCols, Use, Layout, Group >::get_coord(), sycl::_V1::ext::oneapi::detail::wi_element< sycl::ext::oneapi::bfloat16, NumRows, NumCols, Use, Layout, Group >::get_coord(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), sycl::_V1::detail::pi::loadPlugins(), makeReduTupleT(), and sycl::_V1::detail::KernelProgramCache::tryToGetKernelFast().
makeAdjustedBOP()
template<typename ElementType , typename BOPT > constexpr auto sycl::_V1::detail::makeAdjustedBOP (BOPT & BOP) constexpr
Definition at line 2171 of file reduction.hpp.
Referenced by makeAdjustedBOPs().
makeAdjustedBOPs() [1/2]
template<typename... Reductions, typename... BOPsT> constexpr auto sycl::_V1::detail::makeAdjustedBOPs (ReduTupleT< BOPsT... > & BOPsTuple) constexpr
Definition at line 2187 of file reduction.hpp.
References makeAdjustedBOPs().
makeAdjustedBOPs() [2/2]
template<typename... Reductions, typename... BOPsT, size_t... Is> constexpr auto sycl::_V1::detail::makeAdjustedBOPs (ReduTupleT< BOPsT... > & BOPsTuple, std::index_sequence< Is... >) constexpr
Definition at line 2178 of file reduction.hpp.
References makeAdjustedBOP(), and makeReduTupleT().
Referenced by makeAdjustedBOPs(), reduAuxCGFuncImplScalar(), and reduCGFuncImplScalar().
makeReduTupleT()
template<typename... Ts> ReduTupleT<Ts...> sycl::_V1::detail::makeReduTupleT (Ts... Elements)
Definition at line 145 of file reduction.hpp.
References make_tuple().
Referenced by createReduOutAccs(), makeAdjustedBOPs(), reduAuxCGFunc(), and reduCGFuncMulti().
markBufferAsInternal()
void sycl::_V1::detail::markBufferAsInternal (const std::shared_ptr< buffer_impl > & BufImpl)
Definition at line 70 of file helpers.cpp.
markNodeAsVisited()
static bool sycl::_V1::detail::markNodeAsVisited (Command * Cmd, std::vector< Command * > & Visited) static
Definition at line 128 of file graph_builder.cpp.
References sycl::_V1::detail::Command::MMarks, and sycl::_V1::detail::Command::Marks::MVisited.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), and printDotRecursive().
max_v()
template<typename T > static constexpr T sycl::_V1::detail::max_v () static constexpr
Definition at line 440 of file generic_type_traits.hpp.
member_ptr_helper() [1/2]
template<typename RetType , typename Func , typename Arg > static Arg sycl::_V1::detail::member_ptr_helper (RetType(Func::*)(Arg) const) static
member_ptr_helper() [2/2]
template<typename RetType , typename Func , typename Arg1 , typename Arg2 > static Arg1 sycl::_V1::detail::member_ptr_helper (RetType(Func::*)(Arg1, Arg2) const) static
memBufferCreateHelper()
void sycl::_V1::detail::memBufferCreateHelper (const PluginPtr & Plugin, pi_context Ctx, pi_mem_flags Flags, size_t Size, void * HostPtr, pi_mem * RetMem, const pi_mem_properties * Props = nullptr)
Definition at line 134 of file memory_manager.cpp.
References emitMemAllocBeginTrace(), emitMemAllocEndTrace(), piextMemGetNativeHandle(), and piMemBufferCreate().
Referenced by sycl::_V1::detail::MemoryManager::allocateBufferObject(), and sycl::_V1::detail::device_image_impl::get_spec_const_buffer_ref().
memBufferMapHelper()
void sycl::_V1::detail::memBufferMapHelper (const PluginPtr & Plugin, pi_queue command_queue, pi_mem buffer, pi_bool blocking_map, pi_map_flags map_flags, size_t offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event, void ** ret_map)
Definition at line 198 of file memory_manager.cpp.
References emitMemAllocBeginTrace(), emitMemAllocEndTrace(), and piEnqueueMemBufferMap().
Referenced by sycl::_V1::detail::MemoryManager::map().
memcpy()
void sycl::_V1::detail::memcpy (void * Dst, const void * Src, size_t Size) inline
Definition at line 16 of file memcpy.hpp.
Referenced by ConvertHelper::convertArray().
memcpyFromDeviceGlobalDirect()
static void sycl::_V1::detail::memcpyFromDeviceGlobalDirect (QueueImplPtr Queue, DeviceGlobalMapEntry * DeviceGlobalEntry, size_t NumBytes, size_t Offset, void * Dest, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1371 of file memory_manager.cpp.
References getOrBuildProgramForDeviceGlobal(), sycl::_V1::detail::DeviceGlobalMapEntry::MUniqueId, and piextEnqueueDeviceGlobalVariableRead().
Referenced by sycl::_V1::detail::MemoryManager::copy_from_device_global().
memcpyFromDeviceGlobalUSM()
static void sycl::_V1::detail::memcpyFromDeviceGlobalUSM (QueueImplPtr Queue, DeviceGlobalMapEntry * DeviceGlobalEntry, size_t NumBytes, size_t Offset, void * Dest, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1288 of file memory_manager.cpp.
References sycl::_V1::detail::OwnedPiEvent::GetEvent(), sycl::_V1::detail::DeviceGlobalUSMMem::getInitEvent(), sycl::_V1::detail::DeviceGlobalMapEntry::getOrAllocateDeviceGlobalUSM(), and sycl::_V1::detail::DeviceGlobalUSMMem::getPtr().
Referenced by sycl::_V1::detail::MemoryManager::copy_from_device_global().
memcpyToDeviceGlobalDirect()
static void sycl::_V1::detail::memcpyToDeviceGlobalDirect (QueueImplPtr Queue, DeviceGlobalMapEntry * DeviceGlobalEntry, size_t NumBytes, size_t Offset, const void * Src, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent) static
Definition at line 1357 of file memory_manager.cpp.
References getOrBuildProgramForDeviceGlobal(), sycl::_V1::detail::DeviceGlobalMapEntry::MUniqueId, and piextEnqueueDeviceGlobalVariableWrite().
Referenced by sycl::_V1::detail::MemoryManager::copy_to_device_global().
memcpyToDeviceGlobalUSM()
static void sycl::_V1::detail::memcpyToDeviceGlobalUSM (QueueImplPtr Queue, DeviceGlobalMapEntry * DeviceGlobalEntry, size_t NumBytes, size_t Offset, const void * Src, const std::vector< sycl::detail::pi::PiEvent > & DepEvents, sycl::detail::pi::PiEvent * OutEvent, const detail::EventImplPtr & OutEventImpl) static
Definition at line 1255 of file memory_manager.cpp.
References sycl::_V1::detail::OwnedPiEvent::GetEvent(), sycl::_V1::detail::DeviceGlobalUSMMem::getInitEvent(), sycl::_V1::detail::DeviceGlobalMapEntry::getOrAllocateDeviceGlobalUSM(), and sycl::_V1::detail::DeviceGlobalUSMMem::getPtr().
Referenced by sycl::_V1::detail::MemoryManager::copy_to_device_global().
memReleaseHelper()
void sycl::_V1::detail::memReleaseHelper (const PluginPtr & Plugin, pi_mem Mem)
Definition at line 167 of file memory_manager.cpp.
References emitMemReleaseBeginTrace(), emitMemReleaseEndTrace(), piextMemGetNativeHandle(), and piMemRelease().
Referenced by sycl::_V1::detail::MemoryManager::releaseMemObj(), and sycl::_V1::detail::device_image_impl::~device_image_impl().
memUnmapHelper()
void sycl::_V1::detail::memUnmapHelper (const PluginPtr & Plugin, pi_queue command_queue, pi_mem memobj, void * mapped_ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 221 of file memory_manager.cpp.
References emitMemReleaseBeginTrace(), emitMemReleaseEndTrace(), piEnqueueMemUnmap(), and piEventsWait().
Referenced by sycl::_V1::detail::MemoryManager::unmap().
min_v()
template<typename T > static constexpr T sycl::_V1::detail::min_v () static constexpr
Definition at line 444 of file generic_type_traits.hpp.
modeNeedsOldData()
constexpr bool sycl::_V1::detail::modeNeedsOldData (access::mode m) constexpr
Definition at line 102 of file access.hpp.
References sycl::_V1::access::atomic, sycl::_V1::access::read, sycl::_V1::access::read_write, and sycl::_V1::access::write.
modeWritesNewData()
constexpr bool sycl::_V1::detail::modeWritesNewData (access::mode m) constexpr
Definition at line 107 of file access.hpp.
References sycl::_V1::access::read.
msbIsSet()
template<typename T > constexpr bool sycl::_V1::detail::msbIsSet (const T x) inline constexpr
Definition at line 410 of file generic_type_traits.hpp.
References msbMask().
Referenced by sycl::_V1::detail::Assigner< Num >::init(), and sycl::_V1::detail::Assigner< 0 >::init().
msbMask()
template<typename T > constexpr T sycl::_V1::detail::msbMask (T) inline constexpr
Definition at line 405 of file generic_type_traits.hpp.
Referenced by msbIsSet().
multiply_with_overflow_check() [1/2]
template<typename T > static std::enable_if_t<std::is_unsigned_v<T>, bool> sycl::_V1::detail::multiply_with_overflow_check (T & dst, T x, T y) static
Definition at line 412 of file handler.hpp.
Referenced by range_size_fits_in_size_t().
multiply_with_overflow_check() [2/2]
template<typename T > static std::enable_if_t<std::is_unsigned_v<T>, std::optional<T> > sycl::_V1::detail::multiply_with_overflow_check (T x, T y) static
Definition at line 2433 of file program_manager.cpp.
References sycl::_V1::x, and sycl::_V1::y.
Referenced by checkDevSupportDeviceRequirements().
operator<<() [1/4]
template<typename T > std::ostream& sycl::_V1::detail::operator<< (std::ostream & os, std::optional< T > const & opt)
Definition at line 27 of file device_filter.hpp.
operator<<() [2/4]
std::ostream & sycl::_V1::detail::operator<< (std::ostream & Out, const DeviceBinaryProperty & P)
Definition at line 20 of file device_binary_image.cpp.
operator<<() [3/4]
std::ostream & sycl::_V1::detail::operator<< (std::ostream & Out, const ods_target & Target)
Definition at line 261 of file device_filter.cpp.
operator<<() [4/4]
std::ostream & sycl::_V1::detail::operator<< (std::ostream & Out, const spec_constant_impl & V)
Definition at line 40 of file spec_constant_impl.cpp.
References sycl::_V1::detail::spec_constant_impl::getSize(), sycl::_V1::detail::spec_constant_impl::getValuePtr(), and sycl::_V1::detail::spec_constant_impl::isSet().
packCallArguments()
template<PiApiKind Kind, typename... ArgsT> auto sycl::_V1::detail::packCallArguments (ArgsT &&... Args)
Definition at line 75 of file plugin.hpp.
References sycl::_V1::ext::oneapi::experimental::fill(), and totalSize().
Parse_ODS_Backend()
static backend sycl::_V1::detail::Parse_ODS_Backend (const std::string_view & BackendStr, const std::string_view & FullEntry) static
Definition at line 61 of file device_filter.cpp.
References getSyclBeMap(), and sycl::_V1::invalid.
Referenced by Parse_ONEAPI_DEVICE_SELECTOR().
Parse_ODS_Device()
static void sycl::_V1::detail::Parse_ODS_Device (ods_target & Target, const std::string_view & DeviceStr) static
Definition at line 83 of file device_filter.cpp.
References sycl::_V1::detail::ods_target::DeviceNum, sycl::_V1::detail::ods_target::DeviceType, getSyclDeviceTypeMap(), sycl::_V1::detail::ods_target::HasDeviceWildCard, sycl::_V1::detail::ods_target::HasSubDeviceWildCard, sycl::_V1::detail::ods_target::HasSubSubDeviceWildCard, sycl::_V1::invalid, sycl::_V1::detail::ods_target::SubDeviceNum, sycl::_V1::detail::ods_target::SubSubDeviceNum, and tokenize().
Referenced by Parse_ONEAPI_DEVICE_SELECTOR().
Parse_ONEAPI_DEVICE_SELECTOR()
std::vector< ods_target > sycl::_V1::detail::Parse_ONEAPI_DEVICE_SELECTOR (const std::string & envStr)
Definition at line 184 of file device_filter.cpp.
References sycl::_V1::all, sycl::_V1::info::all, sycl::_V1::invalid, sycl::_V1::detail::ods_target::IsNegativeTarget, Parse_ODS_Backend(), Parse_ODS_Device(), and tokenize().
Referenced by sycl::_V1::detail::ods_target_list::ods_target_list().
parseAllowList()
AllowListParsedT sycl::_V1::detail::parseAllowList (const std::string & AllowListRaw)
Definition at line 54 of file allowlist.cpp.
References BackendNameKeyName, codeToString(), std::cout, DeviceNameKeyName, DeviceTypeKeyName, DeviceVendorIdKeyName, DriverVersionKeyName, getSyclBeMap(), PlatformNameKeyName, PlatformVersionKeyName, and SupportedAllowListKeyNames.
Referenced by applyAllowList().
platform_impl::get_backend_info< info::device::backend_version >()
template<> info::device::backend_version::return_type sycl::_V1::detail::platform_impl::get_backend_info< info::device::backend_version > () const
Definition at line 627 of file platform_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::ext_oneapi_level_zero.
platform_impl::get_backend_info< info::device::version >()
template<> info::device::version::return_type sycl::_V1::detail::platform_impl::get_backend_info< info::device::version > () const
Definition at line 610 of file platform_impl.cpp.
References sycl::_V1::backend_mismatch, sycl::_V1::default_selector_v(), sycl::_V1::device::get_info(), sycl::_V1::opencl, and select_device().
platform_impl::get_backend_info< info::platform::version >()
template<> info::platform::version::return_type sycl::_V1::detail::platform_impl::get_backend_info< info::platform::version > () const
Definition at line 596 of file platform_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::opencl.
prepareSYCLEventAssociatedWithQueue()
static event sycl::_V1::detail::prepareSYCLEventAssociatedWithQueue (const std::shared_ptr< detail::queue_impl > & QueueImpl) static
Definition at line 96 of file queue_impl.cpp.
References getSyclObjImpl().
Referenced by sycl::_V1::detail::queue_impl::submitMemOpHelper().
prepTermPositions()
void sycl::_V1::detail::prepTermPositions (TermPositions & pos, int Dimensions, detail::SYCLMemObjI::MemObjType Type)
Definition at line 473 of file memory_manager.cpp.
References sycl::_V1::Dimensions, sycl::_V1::detail::TermPositions::XTerm, sycl::_V1::detail::TermPositions::YTerm, and sycl::_V1::detail::TermPositions::ZTerm.
Referenced by copyD2D(), copyD2H(), copyH2D(), sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2D_cmd_buffer(), sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2H_cmd_buffer(), and sycl::_V1::detail::MemoryManager::ext_oneapi_copyH2D_cmd_buffer().
printDotRecursive()
static void sycl::_V1::detail::printDotRecursive (std::fstream & Stream, std::vector< Command * > & Visited, Command * Cmd) static
Definition at line 160 of file graph_builder.cpp.
References markNodeAsVisited(), sycl::_V1::detail::Command::MUsers, and sycl::_V1::detail::Command::printDot().
processFloatDataToPixel()
template<typename ChannelType > vec<ChannelType, 4> sycl::_V1::detail::processFloatDataToPixel (float4 WriteData, float MulFactor)
Definition at line 552 of file image_accessor_util.hpp.
References sycl::rte.
queue_impl::get_backend_info< info::device::backend_version >()
template<> info::device::backend_version::return_type sycl::_V1::detail::queue_impl::get_backend_info< info::device::backend_version > () const
Definition at line 83 of file queue_impl.cpp.
References sycl::_V1::backend_mismatch, and sycl::_V1::ext_oneapi_level_zero.
queue_impl::get_backend_info< info::device::version >()
template<> info::device::version::return_type sycl::_V1::detail::queue_impl::get_backend_info< info::device::version > () const
Definition at line 72 of file queue_impl.cpp.
References sycl::_V1::backend_mismatch, syclcompat::get_device(), and sycl::_V1::opencl.
queue_impl::get_backend_info< info::platform::version >()
template<> info::platform::version::return_type sycl::_V1::detail::queue_impl::get_backend_info< info::platform::version > () const
Definition at line 61 of file queue_impl.cpp.
References sycl::_V1::backend_mismatch, syclcompat::get_device(), and sycl::_V1::opencl.
queue_impl::get_info< info::queue::context >()
template<> context sycl::_V1::detail::queue_impl::get_info< info::queue::context > () const
Definition at line 52 of file queue_impl.cpp.
queue_impl::get_info< info::queue::device >()
template<> device sycl::_V1::detail::queue_impl::get_info< info::queue::device > () const
Definition at line 56 of file queue_impl.cpp.
References syclcompat::get_device().
queue_impl::get_info< info::queue::reference_count >()
template<> uint32_t sycl::_V1::detail::queue_impl::get_info< info::queue::reference_count > () const
Definition at line 43 of file queue_impl.cpp.
References getPlugin(), PI_QUEUE_INFO_REFERENCE_COUNT, and piQueueGetInfo().
range_size_fits_in_size_t()
template<int Dims> bool sycl::_V1::detail::range_size_fits_in_size_t (const range< Dims > & r)
Definition at line 417 of file handler.hpp.
References multiply_with_overflow_check(), and sycl::_V1::r.
rangeToArray() [1/3]
std::array<size_t, 3> sycl::_V1::detail::rangeToArray (const range< 1 > & r) inline
Definition at line 240 of file range.hpp.
References sycl::_V1::r.
rangeToArray() [2/3]
std::array<size_t, 3> sycl::_V1::detail::rangeToArray (const range< 2 > & r) inline
Definition at line 237 of file range.hpp.
References sycl::_V1::r.
rangeToArray() [3/3]
std::array<size_t, 3> sycl::_V1::detail::rangeToArray (const range< 3 > & r) inline
Definition at line 234 of file range.hpp.
References sycl::_V1::r.
Referenced by sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::buffer().
read_domain_bitfield()
std::vector<info::partition_affinity_domain> sycl::_V1::detail::read_domain_bitfield (pi_device_affinity_domain bits) inline
Definition at line 58 of file device_info.hpp.
References sycl::_V1::info::L1_cache, sycl::_V1::info::L2_cache, sycl::_V1::info::L3_cache, sycl::_V1::info::L4_cache, sycl::_V1::info::next_partitionable, sycl::_V1::info::numa, PI_DEVICE_AFFINITY_DOMAIN_L1_CACHE, PI_DEVICE_AFFINITY_DOMAIN_L2_CACHE, PI_DEVICE_AFFINITY_DOMAIN_L3_CACHE, PI_DEVICE_AFFINITY_DOMAIN_L4_CACHE, PI_DEVICE_AFFINITY_DOMAIN_NEXT_PARTITIONABLE, and PI_DEVICE_AFFINITY_DOMAIN_NUMA.
Referenced by sycl::_V1::detail::get_device_info_impl< std::vector< info::partition_affinity_domain >, info::device::partition_affinity_domains >::get().
read_execution_bitfield()
std::vector<info::execution_capability> sycl::_V1::detail::read_execution_bitfield (pi_device_exec_capabilities bits) inline
Definition at line 76 of file device_info.hpp.
References sycl::_V1::info::exec_kernel, sycl::_V1::info::exec_native_kernel, PI_EXEC_KERNEL, and PI_EXEC_NATIVE_KERNEL.
Referenced by sycl::_V1::detail::get_device_info_impl< std::vector< info::execution_capability >, info::device::execution_capabilities >::get().
read_fp_bitfield()
std::vector<info::fp_config> sycl::_V1::detail::read_fp_bitfield (pi_device_fp_config bits) inline
Definition at line 36 of file device_info.hpp.
References sycl::_V1::info::correctly_rounded_divide_sqrt, sycl::_V1::info::denorm, sycl::_V1::info::fma, sycl::_V1::info::inf_nan, PI_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT, PI_FP_DENORM, PI_FP_FMA, PI_FP_INF_NAN, PI_FP_ROUND_TO_INF, PI_FP_ROUND_TO_NEAREST, PI_FP_ROUND_TO_ZERO, PI_FP_SOFT_FLOAT, sycl::_V1::info::round_to_inf, sycl::_V1::info::round_to_nearest, sycl::_V1::info::round_to_zero, and sycl::_V1::info::soft_float.
Referenced by sycl::_V1::detail::get_device_info_impl< std::vector< info::fp_config >, Param >::get(), and sycl::_V1::detail::get_device_info_impl< std::vector< info::fp_config >, info::device::single_fp_config >::get().
readConfig()
void sycl::_V1::detail::readConfig (bool ForceInitialization)
Definition at line 53 of file config.cpp.
References initValue(), sycl::_V1::make_error_code(), MAX_CONFIG_NAME, MAX_CONFIG_VALUE, sycl::_V1::runtime, and SYCL_CONFIG_FILE_NAME.
readMemoryOrderBitfield()
std::vector<memory_order> sycl::_V1::detail::readMemoryOrderBitfield (pi_memory_order_capabilities bits) inline
Definition at line 52 of file memory_enums.hpp.
References sycl::_V1::acq_rel, sycl::_V1::acquire, PI_MEMORY_ORDER_ACQ_REL, PI_MEMORY_ORDER_ACQUIRE, PI_MEMORY_ORDER_RELAXED, PI_MEMORY_ORDER_RELEASE, PI_MEMORY_ORDER_SEQ_CST, sycl::_V1::relaxed, sycl::_V1::release, and sycl::_V1::seq_cst.
Referenced by sycl::_V1::detail::get_device_info_impl< std::vector< memory_order >, info::device::atomic_memory_order_capabilities >::get(), and sycl::_V1::detail::get_device_info_impl< std::vector< memory_order >, info::device::atomic_fence_order_capabilities >::get().
readMemoryScopeBitfield()
std::vector<memory_scope> sycl::_V1::detail::readMemoryScopeBitfield (pi_memory_scope_capabilities bits) inline
Definition at line 68 of file memory_enums.hpp.
References sycl::_V1::device, PI_MEMORY_SCOPE_DEVICE, PI_MEMORY_SCOPE_SUB_GROUP, PI_MEMORY_SCOPE_SYSTEM, PI_MEMORY_SCOPE_WORK_GROUP, PI_MEMORY_SCOPE_WORK_ITEM, sycl::_V1::sub_group, sycl::_V1::system, sycl::_V1::work_group, and sycl::_V1::work_item.
Referenced by sycl::_V1::detail::get_device_info_impl< std::vector< memory_scope >, info::device::atomic_memory_scope_capabilities >::get(), and sycl::_V1::detail::get_device_info_impl< std::vector< memory_scope >, info::device::atomic_fence_scope_capabilities >::get().
readPixel()
template<typename T > vec<T, 4> sycl::_V1::detail::readPixel (T * Ptr, const image_channel_order ChannelOrder, const image_channel_type ChannelType)
Definition at line 135 of file image_accessor_util.hpp.
References sycl::_V1::a, sycl::_V1::abgr, sycl::_V1::argb, sycl::_V1::bgra, sycl::_V1::ext_oneapi_srgba, sycl::_V1::intensity, sycl::_V1::luminance, sycl::_V1::r, sycl::_V1::ra, sycl::_V1::rg, sycl::_V1::rgb, sycl::_V1::rgba, sycl::_V1::rgbx, sycl::_V1::rgx, sycl::_V1::rx, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, and sycl::_V1::unorm_short_565.
Referenced by ReadPixelData().
ReadPixelData()
template<typename DataT > DataT sycl::_V1::detail::ReadPixelData (const int4 PixelCoord, const id< 3 > ImgPitch, const image_channel_type ImageChannelType, const image_channel_order ImageChannelOrder, void * BasePtr, const uint8_t ElementSize)
Definition at line 801 of file image_accessor_util.hpp.
References sycl::_V1::fp16, sycl::_V1::fp32, getImageOffset(), readPixel(), sycl::_V1::signed_int16, sycl::_V1::signed_int32, sycl::_V1::signed_int8, sycl::_V1::snorm_int16, sycl::_V1::snorm_int8, sycl::_V1::unorm_int16, sycl::_V1::unorm_int8, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, sycl::_V1::unorm_short_565, sycl::_V1::unsigned_int16, sycl::_V1::unsigned_int32, and sycl::_V1::unsigned_int8.
ReadPixelDataLinearFiltMode()
template<typename DataT > DataT sycl::_V1::detail::ReadPixelDataLinearFiltMode (const int8 CoordValues, const float4 abc, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, id< 3 > ImgPitch, const image_channel_type ImgChannelType, const image_channel_order ImgChannelOrder, void * BasePtr, const uint8_t ElementSize)
Definition at line 930 of file image_accessor_util.hpp.
reduAuxCGFunc()
template<typename KernelName , typename KernelType , typename... Reductions, size_t... Is> size_t sycl::_V1::detail::reduAuxCGFunc (handler & CGH, size_t NWorkItems, size_t MaxWGSize, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... > ReduIndices)
Definition at line 2498 of file reduction.hpp.
References associateReduAccsWithHandler(), filterSequence(), sycl::_V1::nd_item< Dimensions >::get_global_linear_id(), sycl::_V1::nd_item< Dimensions >::get_group_linear_id(), sycl::_V1::nd_item< Dimensions >::get_local_linear_id(), sycl::_V1::nd_item< Dimensions >::get_local_range(), makeReduTupleT(), sycl::_V1::detail::reduction::multi, sycl::_V1::handler::parallel_for(), reduAuxCGFuncImplArray(), reduAuxCGFuncImplScalar(), reduComputeWGSize(), and sycl::_V1::range< Dimensions >::size().
reduAuxCGFuncImplArray()
template<bool IsOneWG, typename... Reductions, int Dims, typename... LocalAccT, typename... InAccT, typename... OutAccT, typename... Ts, typename... BOPsT, size_t... Is> void sycl::_V1::detail::reduAuxCGFuncImplArray (nd_item< Dims > NDIt, size_t LID, size_t GID, size_t RemainingWorkSize, ReduTupleT< LocalAccT... > LocalAccsTuple, ReduTupleT< InAccT... > InAccsTuple, ReduTupleT< OutAccT... > OutAccsTuple, ReduTupleT< Ts... > IdentitiesTuple, ReduTupleT< BOPsT... > BOPsTuple, std::array< bool, sizeof...(Reductions)> InitToIdentityProps, std::index_sequence< Is... >)
Definition at line 2476 of file reduction.hpp.
References reduAuxCGFuncImplArrayHelper().
Referenced by reduAuxCGFunc().
reduAuxCGFuncImplArrayHelper()
template<bool IsOneWG, typename Reduction , int Dims, typename LocalAccT , typename InAccT , typename OutAccT , typename T , typename BOPT > void sycl::_V1::detail::reduAuxCGFuncImplArrayHelper (nd_item< Dims > NDIt, size_t LID, size_t GID, size_t RemainingWorkSize, LocalAccT LocalReds, InAccT In, OutAccT Out, T IdentityContainer, BOPT BOp, bool IsInitializeToIdentity)
Definition at line 2428 of file reduction.hpp.
References sycl::_V1::nd_item< Dimensions >::barrier(), and sycl::_V1::nd_item< Dimensions >::get_group_linear_id().
Referenced by reduAuxCGFuncImplArray().
reduAuxCGFuncImplScalar()
template<bool IsOneWG, typename... Reductions, int Dims, typename... LocalAccT, typename... InAccT, typename... OutAccT, typename... Ts, typename... BOPsT, size_t... Is> void sycl::_V1::detail::reduAuxCGFuncImplScalar (nd_item< Dims > NDIt, size_t LID, size_t GID, size_t RemainingWorkSize, ReduTupleT< LocalAccT... > LocalAccsTuple, ReduTupleT< InAccT... > InAccsTuple, ReduTupleT< OutAccT... > OutAccsTuple, ReduTupleT< Ts... > IdentitiesTuple, ReduTupleT< BOPsT... > BOPsTuple, std::array< bool, sizeof...(Reductions)> InitToIdentityProps, std::index_sequence< Is... > ReduIndices)
All scalar reductions are processed together; there is one loop of log2(N) steps, and each reduction uses its own storage.
Definition at line 2398 of file reduction.hpp.
References doTreeReductionOnTuple(), sycl::_V1::nd_item< Dimensions >::get_group_linear_id(), makeAdjustedBOPs(), and writeReduSumsToOutAccs().
Referenced by reduAuxCGFunc().
reduCGFuncImplArray()
template<bool IsOneWG, typename... Reductions, int Dims, typename... LocalAccT, typename... OutAccT, typename... ReducerT, typename... BOPsT, size_t... Is> void sycl::_V1::detail::reduCGFuncImplArray (nd_item< Dims > NDIt, ReduTupleT< LocalAccT... > LocalAccsTuple, ReduTupleT< OutAccT... > OutAccsTuple, std::tuple< ReducerT... > & ReducersTuple, ReduTupleT< BOPsT... > BOPsTuple, std::array< bool, sizeof...(Reductions)> InitToIdentityProps, std::index_sequence< Is... >)
Definition at line 2279 of file reduction.hpp.
Referenced by reduCGFuncMulti().
reduCGFuncImplArrayHelper()
template<bool IsOneWG, typename Reduction , int Dims, typename LocalAccT , typename OutAccT , typename ReducerT , typename BOPT > void sycl::_V1::detail::reduCGFuncImplArrayHelper (nd_item< Dims > NDIt, LocalAccT LocalReds, OutAccT Out, ReducerT & Reducer, BOPT BOp, bool IsInitializeToIdentity)
Each array reduction is processed separately.
Definition at line 2229 of file reduction.hpp.
References sycl::_V1::nd_item< Dimensions >::barrier(), sycl::_V1::nd_item< Dimensions >::get_group_linear_id(), sycl::_V1::nd_item< Dimensions >::get_local_linear_id(), sycl::_V1::nd_item< Dimensions >::get_local_range(), getReducerAccess(), and sycl::_V1::range< Dimensions >::size().
reduCGFuncImplScalar()
template<bool IsOneWG, typename... Reductions, int Dims, typename... LocalAccT, typename... OutAccT, typename... ReducerT, typename... Ts, typename... BOPsT, size_t... Is> void sycl::_V1::detail::reduCGFuncImplScalar (nd_item< Dims > NDIt, ReduTupleT< LocalAccT... > LocalAccsTuple, ReduTupleT< OutAccT... > OutAccsTuple, std::tuple< ReducerT... > & ReducersTuple, ReduTupleT< Ts... > IdentitiesTuple, ReduTupleT< BOPsT... > BOPsTuple, std::array< bool, sizeof...(Reductions)> InitToIdentityProps, std::index_sequence< Is... > ReduIndices)
All scalar reductions are processed together; there is one loop of log2(N) steps, and each reduction uses its own storage.
Definition at line 2197 of file reduction.hpp.
References doTreeReductionOnTuple(), sycl::_V1::nd_item< Dimensions >::get_group_linear_id(), sycl::_V1::nd_item< Dimensions >::get_local_linear_id(), sycl::_V1::nd_item< Dimensions >::get_local_range(), getReducerAccess(), makeAdjustedBOPs(), sycl::_V1::range< Dimensions >::size(), and writeReduSumsToOutAccs().
Referenced by reduCGFuncMulti().
reduCGFuncMulti()
template<typename KernelName , typename KernelType , int Dims, typename PropertiesT , typename... Reductions, size_t... Is> void sycl::_V1::detail::reduCGFuncMulti (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, PropertiesT Properties, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... > ReduIndices)
Definition at line 2298 of file reduction.hpp.
References filterSequence(), sycl::_V1::nd_range< Dimensions >::get_group_range(), sycl::_V1::nd_range< Dimensions >::get_local_range(), makeReduTupleT(), sycl::_V1::detail::reduction::multi, sycl::_V1::handler::parallel_for(), reduCGFuncImplArray(), reduCGFuncImplScalar(), and sycl::_V1::range< Dimensions >::size().
reduComputeWGSize()
size_t sycl::_V1::detail::reduComputeWGSize (size_t NWorkItems, size_t MaxWGSize, size_t & NWorkGroups)
Definition at line 19 of file reduction.cpp.
Referenced by reduAuxCGFunc(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run().
reduction_parallel_for() [1/2]
template<typename KernelName , reduction::strategy Strategy = reduction::strategy::auto_select, int Dims, typename PropertiesT , typename... RestT> void sycl::_V1::detail::reduction_parallel_for (handler & CGH, nd_range< Dims > NDRange, PropertiesT Properties, RestT... Rest)
Definition at line 2700 of file reduction.hpp.
reduction_parallel_for() [2/2]
template<typename KernelName , reduction::strategy Strategy = reduction::strategy::auto_select, int Dims, typename PropertiesT , typename... RestT> void sycl::_V1::detail::reduction_parallel_for (handler & CGH, range< Dims > NDRange, PropertiesT Properties, RestT... Rest)
Definition at line 2711 of file reduction.hpp.
References sycl::_V1::detail::reduction::auto_select, std::get(), getDelinearizedId(), sycl::_V1::detail::reduction::getDelinearizedItem(), sycl::_V1::detail::reduction::group_reduce_and_last_wg_detection, sycl::_V1::detail::reduction::local_atomic_and_atomic_cross_wg, sycl::_V1::detail::reduction::range_basic, reduGetMaxNumConcurrentWorkGroups(), reduGetMemPerWorkItem(), reduGetPreferredWGSize(), sycl::_V1::range< Dimensions >::size(), and tuple_select_elements().
reduGetMaxNumConcurrentWorkGroups() [1/2]
uint32_t sycl::_V1::detail::reduGetMaxNumConcurrentWorkGroups (std::shared_ptr< queue_impl > Queue)
Referenced by reduction_parallel_for().
reduGetMaxNumConcurrentWorkGroups() [2/2]
uint32_t sycl::_V1::detail::reduGetMaxNumConcurrentWorkGroups (std::shared_ptr< sycl::detail::queue_impl > Queue)
Definition at line 53 of file reduction.cpp.
References sycl::_V1::device::get_info(), and sycl::_V1::device::is_gpu().
reduGetMaxWGSize() [1/2]
size_t sycl::_V1::detail::reduGetMaxWGSize (std::shared_ptr< queue_impl > Queue, size_t LocalMemBytesPerWorkItem)
Referenced by reduGetPreferredWGSize(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run().
reduGetMaxWGSize() [2/2]
size_t sycl::_V1::detail::reduGetMaxWGSize (std::shared_ptr< sycl::detail::queue_impl > Queue, size_t LocalMemBytesPerWorkItem)
Definition at line 75 of file reduction.cpp.
References sycl::_V1::device::get_info().
reduGetMemPerWorkItem()
template<typename... ReductionT, size_t... Is> size_t sycl::_V1::detail::reduGetMemPerWorkItem (std::tuple< ReductionT... > & ReduTuple, std::index_sequence< Is... >)
Definition at line 2583 of file reduction.hpp.
References reduGetMemPerWorkItemHelper().
Referenced by reduction_parallel_for(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run().
reduGetMemPerWorkItemHelper() [1/2]
template<typename Reduction > size_t sycl::_V1::detail::reduGetMemPerWorkItemHelper (Reduction &)
Definition at line 2572 of file reduction.hpp.
Referenced by reduGetMemPerWorkItem(), and reduGetMemPerWorkItemHelper().
reduGetMemPerWorkItemHelper() [2/2]
template<typename Reduction , typename... RestT> size_t sycl::_V1::detail::reduGetMemPerWorkItemHelper (Reduction & , RestT... Rest)
Definition at line 2577 of file reduction.hpp.
References reduGetMemPerWorkItemHelper().
reduGetPreferredWGSize()
size_t sycl::_V1::detail::reduGetPreferredWGSize (std::shared_ptr< queue_impl > & Queue, size_t LocalMemBytesPerWorkItem)
Definition at line 115 of file reduction.cpp.
References std::get(), sycl::_V1::device::get_info(), sycl::_V1::device::is_accelerator(), sycl::_V1::device::is_cpu(), sycl::_V1::device::is_gpu(), and reduGetMaxWGSize().
Referenced by reduction_parallel_for().
reduSaveFinalResultToUserMem()
template<typename KernelName , class Reduction > void sycl::_V1::detail::reduSaveFinalResultToUserMem (handler & CGH, Reduction & Redu)
Copies the final reduction result kept in read-write accessor to user's USM memory.
Definition at line 1183 of file reduction.hpp.
References sycl::_V1::handler::single_task().
registerAuxiliaryResourcesNoLock()
static void sycl::_V1::detail::registerAuxiliaryResourcesNoLock (std::unordered_map< EventImplPtr, std::vector< std::shared_ptr< const void >>> & AuxiliaryResources, const EventImplPtr & Event, std::vector< std::shared_ptr< const void >> && Resources) static
Definition at line 562 of file scheduler.cpp.
Referenced by sycl::_V1::detail::Scheduler::registerAuxiliaryResources(), and sycl::_V1::detail::Scheduler::takeAuxiliaryResources().
removeDuplicateDevices()
const std::vector< device > sycl::_V1::detail::removeDuplicateDevices (const std::vector< device > & Devs)
Definition at line 130 of file kernel_bundle.cpp.
Referenced by sycl::_V1::ext::oneapi::experimental::detail::build_from_source().
RepeatValue()
template<size_t N, typename T > static constexpr std::array<T, N> sycl::_V1::detail::RepeatValue (const T & Arg) static constexpr
Definition at line 442 of file common.hpp.
References RepeatValueHelper().
RepeatValueHelper()
template<typename T , size_t... Is> static constexpr std::array<T, sizeof...(Is)> sycl::_V1::detail::RepeatValueHelper (const T & Arg, std::index_sequence< Is... >) static constexpr
Definition at line 437 of file common.hpp.
Referenced by RepeatValue().
report()
void sycl::_V1::detail::report (const code_location & CodeLoc)
Definition at line 167 of file queue_impl.cpp.
References sycl::_V1::detail::code_location::columnNumber(), std::cout, sycl::_V1::detail::code_location::fileName(), sycl::_V1::detail::code_location::functionName(), and sycl::_V1::detail::code_location::lineNumber().
Referenced by sycl::_V1::detail::queue_impl::memcpy().
reverseBuf()
void sycl::_V1::detail::reverseBuf (char * Buf, unsigned Len) inline
Definition at line 152 of file stream.hpp.
Referenced by ScalarToStr().
ReverseRangeDimensionsForKernel()
void sycl::_V1::detail::ReverseRangeDimensionsForKernel (NDRDescT & NDR)
Definition at line 2262 of file commands.cpp.
References sycl::_V1::detail::NDRDescT::Dims, sycl::_V1::detail::NDRDescT::GlobalOffset, sycl::_V1::detail::NDRDescT::GlobalSize, and sycl::_V1::detail::NDRDescT::LocalSize.
Referenced by enqueueImpCommandBufferKernel(), SetKernelParamsAndLaunch(), and sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::updateImpl().
runKernelWithArg() [1/2]
template<typename ArgType , typename KernelType > std::enable_if_t< KernelLambdaHasKernelHandlerArgT<KernelType, ArgType>::value> sycl::_V1::detail::runKernelWithArg (KernelType KernelName, ArgType Arg)
Definition at line 210 of file cg_types.hpp.
Referenced by sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost().
runKernelWithArg() [2/2]
template<typename ArgType , typename KernelType > std::enable_if_t< !KernelLambdaHasKernelHandlerArgT<KernelType, ArgType>::value> sycl::_V1::detail::runKernelWithArg (KernelType KernelName, ArgType Arg)
Definition at line 218 of file cg_types.hpp.
runKernelWithoutArg() [1/2]
template<typename KernelType > std::enable_if_t<KernelLambdaHasKernelHandlerArgT<KernelType>::value> sycl::_V1::detail::runKernelWithoutArg (KernelType KernelName)
Definition at line 196 of file cg_types.hpp.
Referenced by sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost().
runKernelWithoutArg() [2/2]
template<typename KernelType > std::enable_if_t<!KernelLambdaHasKernelHandlerArgT<KernelType>::value> sycl::_V1::detail::runKernelWithoutArg (KernelType KernelName)
Definition at line 203 of file cg_types.hpp.
sameCtx()
static bool sycl::_V1::detail::sameCtx (const ContextImplPtr & LHS, const ContextImplPtr & RHS) static
Definition at line 52 of file graph_builder.cpp.
Referenced by sycl::_V1::detail::Scheduler::GraphBuilder::addCommandGraphUpdate(), sycl::_V1::detail::Scheduler::GraphBuilder::addHostAccessor(), and sycl::_V1::detail::Scheduler::GraphBuilder::findAllocaForReq().
sampledImageConstructorNotification()
void sycl::_V1::detail::sampledImageConstructorNotification (void * ImageObj, void * AccessorObj, const std::optional< image_target > & Target, const void * Type, uint32_t ElemSize, const code_location & CodeLoc)
Definition at line 71 of file accessor_impl.cpp.
References sycl::_V1::detail::XPTIRegistry::sampledImageAccessorNotification(), and sycl::_V1::detail::XPTIRegistry::sampledImageHostAccessorNotification().
ScalarToStr() [1/2]
template<typename T > std::enable_if_t<std::is_integral_v<T>, unsigned> sycl::_V1::detail::ScalarToStr (const T & Val, char * Buf, unsigned Flags, int , int Precision = -1) inline
Definition at line 193 of file stream.hpp.
References BaseField, Dec, getAbsVal(), Hex, integralToBase(), Oct, reverseBuf(), ShowBase, and ShowPos.
Referenced by ArrayToStr(), VecToStr(), writeFloatingPoint(), and writeIntegral().
ScalarToStr() [2/2]
template<typename T > EnableIfFP<T, unsigned> sycl::_V1::detail::ScalarToStr (const T & Val, char * Buf, unsigned Flags, int , int Precision = -1) inline
Definition at line 483 of file stream.hpp.
References checkForInfNan(), floatingPointToDecStr(), Scientific, and ShowPos.
SConvert()
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>> To sycl::_V1::detail::SConvert (From Value)
Definition at line 129 of file vector_convert.hpp.
select_device() [1/3]
device sycl::_V1::detail::select_device (const DSelectorInvocableType & DeviceSelectorInvocable)
Definition at line 136 of file device_selector.cpp.
References sycl::_V1::device::get_devices().
Referenced by context_impl::get_backend_info< info::device::version >(), kernel_impl::get_backend_info< info::device::version >(), platform_impl::get_backend_info< info::device::version >(), sycl::_V1::ext::oneapi::filter_selector::select_device(), and select_device().
select_device() [2/3]
device sycl::_V1::detail::select_device (const DSelectorInvocableType & DeviceSelectorInvocable, const context & SyclContext)
Definition at line 144 of file device_selector.cpp.
References sycl::_V1::context::get_devices(), sycl::_V1::invalid, and select_device().
select_device() [3/3]
device sycl::_V1::detail::select_device (DSelectorInvocableType DeviceSelectorInvocable, std::vector< device > & Devices)
Definition at line 73 of file device_selector.cpp.
References sycl::_V1::accelerator_selector_v(), sycl::_V1::cpu_selector_v(), getDevicePreference(), sycl::_V1::gpu_selector_v(), REJECT_DEVICE_SCORE, and traceDeviceSelection().
SetArgBasedOnType() [1/2]
void sycl::_V1::detail::SetArgBasedOnType (const detail::plugin & Plugin, sycl::detail::pi::PiKernel Kernel, const std::shared_ptr< device_image_impl > & DeviceImageImpl, const std::function< void *(Requirement *Req)> & getMemAllocationFunc, const sycl::context & Context, bool IsHost, detail::ArgDesc & Arg, size_t NextTrueIndex)
SetArgBasedOnType() [2/2]
void sycl::_V1::detail::SetArgBasedOnType (const PluginPtr & Plugin, sycl::detail::pi::PiKernel Kernel, const std::shared_ptr< device_image_impl > & DeviceImageImpl, const std::function< void *(Requirement *Req)> & getMemAllocationFunc, const sycl::context & Context, bool IsHost, detail::ArgDesc & Arg, size_t NextTrueIndex)
Definition at line 2282 of file commands.cpp.
References AccessModeToPi(), codeToString(), sycl::_V1::context::get_backend(), getSyclObjImpl(), kind_accessor, kind_invalid, kind_pointer, kind_sampler, kind_specialization_constants_buffer, kind_std_layout, kind_stream, sycl::_V1::detail::AccessorImplHost::MAccessMode, _pi_mem_obj_property::mem_access, sycl::_V1::detail::ArgDesc::MPtr, sycl::_V1::detail::ArgDesc::MSize, sycl::_V1::detail::ArgDesc::MType, sycl::_V1::opencl, PI_ACCESS_READ_ONLY, PI_KERNEL_ARG_MEM_OBJ_ACCESS, piextKernelSetArgMemObj(), piextKernelSetArgPointer(), piextKernelSetArgSampler(), and piKernelSetArg().
Referenced by enqueueImpCommandBufferKernel(), and SetKernelParamsAndLaunch().
SetFlushBufOffset()
void sycl::_V1::detail::SetFlushBufOffset (GlobalBufAccessorT & GlobalFlushBuf, unsigned WIOffset, unsigned Offset) inline
Definition at line 124 of file stream.hpp.
Referenced by flushBuffer(), and write().
SetKernelParamsAndLaunch()
static pi_result sycl::_V1::detail::SetKernelParamsAndLaunch (const QueueImplPtr & Queue, std::vector< ArgDesc > & Args, const std::shared_ptr< device_image_impl > & DeviceImageImpl, sycl::detail::pi::PiKernel Kernel, NDRDescT & NDRDesc, std::vector< sycl::detail::pi::PiEvent > & RawEvents, const detail::EventImplPtr & OutEventImpl, const KernelArgMask * EliminatedArgMask, const std::function< void *(Requirement *Req)> & getMemAllocationFunc, bool IsCooperative) static
Definition at line 2369 of file commands.cpp.
References adjustNDRangePerKernel(), applyFuncOnFilteredArgs(), sycl::_V1::detail::NDRDescT::Dims, sycl::_V1::detail::NDRDescT::GlobalOffset, sycl::_V1::detail::NDRDescT::GlobalSize, sycl::_V1::detail::NDRDescT::LocalSize, PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE, piEnqueueKernelLaunch(), piextEnqueueCooperativeKernelLaunch(), piKernelGetGroupInfo(), ReverseRangeDimensionsForKernel(), and SetArgBasedOnType().
Referenced by enqueueImpKernel().
setSpecializationConstants()
static void sycl::_V1::detail::setSpecializationConstants (const std::shared_ptr< device_image_impl > & InputImpl, sycl::detail::pi::PiProgram Prog, const PluginPtr & Plugin) static
Definition at line 1993 of file program_manager.cpp.
References enableITTAnnotationsIfNeeded(), and piextProgramSetSpecializationConstant().
Referenced by sycl::_V1::detail::ProgramManager::build(), and sycl::_V1::detail::ProgramManager::compile().
shutdown()
void sycl::_V1::detail::shutdown ()
Definition at line 287 of file global_handler.cpp.
Referenced by __attribute__().
split_string()
std::vector<std::string> sycl::_V1::detail::split_string (std::string_view str, char delimeter) inline
Definition at line 18 of file split_string.hpp.
Referenced by sycl::_V1::detail::kernel_bundle_impl::build_from_source(), sycl::_V1::detail::get_device_info_impl< std::vector< kernel_id >, info::device::built_in_kernel_ids >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< std::string >, info::device::built_in_kernels >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< std::string >, info::device::extensions >::get(), get_platform_info(), and sycl::_V1::ext::oneapi::experimental::detail::OpenCLC_Supports_Extension().
stableSerializeSpecConstRegistry()
void sycl::_V1::detail::stableSerializeSpecConstRegistry (const SpecConstRegistryT & Reg, SerializedObj & Dst)
Definition at line 31 of file spec_constant_impl.cpp.
References sycl::_V1::detail::spec_constant_impl::getSize(), and sycl::_V1::detail::spec_constant_impl::getValuePtr().
Referenced by sycl::_V1::detail::program_impl::stableSerializeSpecConstRegistry().
stringifyErrorCode()
const char * sycl::_V1::detail::stringifyErrorCode (pi_int32 error)
Definition at line 56 of file common.cpp.
Referenced by codeToString().
supportsAffinityDomain()
static bool sycl::_V1::detail::supportsAffinityDomain (const device & dev, info::partition_property partitionProp, info::partition_affinity_domain domain) static
Definition at line 331 of file platform_impl.cpp.
References sycl::_V1::device::get_info(), and sycl::_V1::info::partition_by_affinity_domain.
Referenced by amendDeviceAndSubDevices().
supportsPartitionProperty()
static bool sycl::_V1::detail::supportsPartitionProperty (const device & dev, info::partition_property partitionProp) static
Definition at line 342 of file platform_impl.cpp.
References sycl::_V1::device::get_info().
Referenced by amendDeviceAndSubDevices().
tie()
template<typename... Ts> auto sycl::_V1::detail::tie (Ts &... Args)
Definition at line 39 of file tuple.hpp.
Referenced by enqueueImpCommandBufferKernel(), enqueueImpKernel(), sycl::_V1::platform::ext_oneapi_get_default_context(), and sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::updateImpl().
to_marray()
template<class T , int N> marray<T, N> sycl::_V1::detail::to_marray (vec< T, N > X)
Definition at line 156 of file builtins_utils_vec.hpp.
to_vec()
template<class T , size_t N> vec<T, N> sycl::_V1::detail::to_vec (marray< T, N > X)
Definition at line 150 of file builtins_utils_vec.hpp.
to_vec2()
template<class T , size_t N> vec<T, 2> sycl::_V1::detail::to_vec2 (marray< T, N > X, size_t Start)
Definition at line 147 of file builtins_utils_vec.hpp.
Referenced by builtin_marray_impl(), sycl::_V1::ext::oneapi::experimental::native::exp2(), and sycl::_V1::ext::oneapi::experimental::native::tanh().
tokenize()
std::vector<std::string_view> sycl::_V1::detail::tokenize (const std::string_view & Filter, const std::string & Delim, bool ProhibitEmptyTokens = false)
Definition at line 22 of file device_filter.cpp.
References sycl::_V1::invalid.
Referenced by Parse_ODS_Device(), and Parse_ONEAPI_DEVICE_SELECTOR().
totalSize()
template<typename... Ts> constexpr size_t sycl::_V1::detail::totalSize (const std::tuple< Ts... > &) constexpr
Definition at line 70 of file plugin.hpp.
Referenced by packCallArguments().
traceDeviceSelection()
static void sycl::_V1::detail::traceDeviceSelection (const device & Device, int Score, bool Chosen) static
Definition at line 50 of file device_selector.cpp.
References std::cout, sycl::_V1::device::get_info(), sycl::_V1::detail::pi::PI_TRACE_ALL, sycl::_V1::detail::pi::PI_TRACE_BASIC, and sycl::_V1::detail::pi::trace().
Referenced by select_device().
tuple_select_elements()
template<typename TupleT , std::size_t... Is> std::tuple<std::tuple_element_t<Is, TupleT>...> sycl::_V1::detail::tuple_select_elements (TupleT Tuple, std::index_sequence< Is... >)
Utility function: for the given tuple.
Parameters
Tuple the function returns a new tuple consisting of only elements indexed by the index sequence.
Definition at line 2592 of file reduction.hpp.
Referenced by reduction_parallel_for(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run().
UConvert()
template<typename From , typename To , int VecSize, typename Enable = std::enable_if_t<VecSize == 1>> To sycl::_V1::detail::UConvert (From Value)
Definition at line 135 of file vector_convert.hpp.
unmarkVisitedNodes()
static void sycl::_V1::detail::unmarkVisitedNodes (std::vector< Command * > & Visited) static
Definition at line 137 of file graph_builder.cpp.
UnnormalizeCoordinates() [1/3]
template<typename T > std::enable_if_t<IsValidCoordType<T>::value, T> sycl::_V1::detail::UnnormalizeCoordinates (const T & Coords, const range< 3 > & Range)
Definition at line 47 of file image_accessor_util.hpp.
Referenced by imageReadSamplerHostImpl().
UnnormalizeCoordinates() [2/3]
template<typename T > std::enable_if_t<IsValidCoordType<T>::value, vec<T, 2> > sycl::_V1::detail::UnnormalizeCoordinates (const vec< T, 2 > & Coords, const range< 3 > & Range)
Definition at line 53 of file image_accessor_util.hpp.
UnnormalizeCoordinates() [3/3]
template<typename T > std::enable_if_t<IsValidCoordType<T>::value, vec<T, 4> > sycl::_V1::detail::UnnormalizeCoordinates (const vec< T, 4 > & Coords, const range< 3 > & Range)
Definition at line 59 of file image_accessor_util.hpp.
unsampledImageConstructorNotification()
void sycl::_V1::detail::unsampledImageConstructorNotification (void * ImageObj, void * AccessorObj, const std::optional< image_target > & Target, access::mode Mode, const void * Type, uint32_t ElemSize, const code_location & CodeLoc)
Definition at line 58 of file accessor_impl.cpp.
References sycl::_V1::Mode, sycl::_V1::detail::XPTIRegistry::unsampledImageAccessorNotification(), and sycl::_V1::detail::XPTIRegistry::unsampledImageHostAccessorNotification().
updateOffset()
bool sycl::_V1::detail::updateOffset (GlobalOffsetAccessorT & GlobalOffset, GlobalBufAccessorT & GlobalBuf, unsigned Size, unsigned & Cur) inline
Definition at line 535 of file stream.hpp.
Referenced by flushBuffer().
UseSpvEnv()
static constexpr char sycl::_V1::detail::UseSpvEnv ("SYCL_USE_KERNEL_SPV") static constexpr
Referenced by sycl::_V1::detail::ProgramManager::ProgramManager().
VecToStr() [1/3]
template<typename T , int VecLength> std::enable_if_t<(VecLength == 1), unsigned> sycl::_V1::detail::VecToStr (const vec< T, VecLength > & Vec, char * VecStr, unsigned Flags, int Width, int Precision)
Definition at line 570 of file stream.hpp.
References ScalarToStr().
Referenced by VecToStr().
VecToStr() [2/3]
template<typename T , int VecLength> std::enable_if_t<(VecLength == 2 || VecLength == 4 || VecLength == 8 || VecLength == 16), unsigned> sycl::_V1::detail::VecToStr (const vec< T, VecLength > & Vec, char * VecStr, unsigned Flags, int Width, int Precision)
Definition at line 579 of file stream.hpp.
References append(), VEC_ELEMENT_DELIMITER, and VecToStr().
VecToStr() [3/3]
template<typename T , int VecLength> std::enable_if_t<(VecLength == 3), unsigned> sycl::_V1::detail::VecToStr (const vec< T, VecLength > & Vec, char * VecStr, unsigned Flags, int Width, int Precision)
Definition at line 591 of file stream.hpp.
References append(), and VEC_ELEMENT_DELIMITER.
waitEvents()
void sycl::_V1::detail::waitEvents (std::vector< sycl::event > DepEvents)
Definition at line 64 of file helpers.cpp.
References getSyclObjImpl().
waitForEvents()
static void sycl::_V1::detail::waitForEvents (const std::vector< EventImplPtr > & Events) static
Definition at line 120 of file memory_manager.cpp.
References piEventsWait().
Referenced by sycl::_V1::detail::MemoryManager::allocate(), sycl::_V1::detail::MemoryManager::allocateMemSubBuffer(), and sycl::_V1::detail::MemoryManager::release().
workGroupBarrier()
void sycl::_V1::detail::workGroupBarrier () inline
Definition at line 42 of file group.hpp.
References __spirv_ControlBarrier(), __spv::MemorySemanticsMask::SequentiallyConsistent, __spv::Scope::Workgroup, and __spv::MemorySemanticsMask::WorkgroupMemory.
Referenced by doTreeReductionHelper(), sycl::_V1::ext::oneapi::group_local_memory(), sycl::_V1::ext::oneapi::group_local_memory_for_overwrite(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::local_atomic_and_atomic_cross_wg >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::range_basic >::run().
write()
void sycl::_V1::detail::write (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const char * Str, unsigned Len, unsigned Padding = 0) inline
Definition at line 130 of file stream.hpp.
References FLUSH_BUF_OFFSET_SIZE, GetFlushBufOffset(), and SetFlushBufOffset().
Referenced by sycl::_V1::detail::MemoryManager::map(), writeArray(), writeFloatingPoint(), writeGroup(), writeHItem(), writeIntegral(), writeItem(), writeNDItem(), writeNDRange(), and writeVec().
writeArray()
template<int ArrayLength> void sycl::_V1::detail::writeArray (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const array< ArrayLength > & Arr) inline
Definition at line 629 of file stream.hpp.
References ArrayToStr(), MAX_ARRAY_SIZE, and write().
writeFloatingPoint()
template<typename T > EnableIfFP<T> sycl::_V1::detail::writeFloatingPoint (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, int Precision, const T & Val) inline
Definition at line 521 of file stream.hpp.
References MAX_FLOATING_POINT_DIGITS, ScalarToStr(), and write().
writeGroup()
template<int Dimensions> void sycl::_V1::detail::writeGroup (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const group< Dimensions > & Group) inline
Definition at line 693 of file stream.hpp.
References append(), ArrayToStr(), MAX_ARRAY_SIZE, and write().
writeHItem()
template<int Dimensions> void sycl::_V1::detail::writeHItem (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const h_item< Dimensions > & HItem) inline
Definition at line 730 of file stream.hpp.
References append(), sycl::_V1::h_item< Dimensions >::get_global(), sycl::_V1::h_item< Dimensions >::get_logical_local(), sycl::_V1::h_item< Dimensions >::get_physical_local(), ItemToStr(), MAX_ITEM_SIZE, and write().
writeIntegral()
template<typename T > std::enable_if_t<std::is_integral_v<T> > sycl::_V1::detail::writeIntegral (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, const T & Val) inline
Definition at line 509 of file stream.hpp.
References MAX_INTEGRAL_DIGITS, ScalarToStr(), and write().
writeItem()
template<int Dimensions> void sycl::_V1::detail::writeItem (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const item< Dimensions > & Item) inline
Definition at line 638 of file stream.hpp.
References append(), ArrayToStr(), sycl::_V1::item< Dimensions, with_offset >::get_id(), sycl::_V1::item< Dimensions, with_offset >::get_offset(), sycl::_V1::item< Dimensions, with_offset >::get_range(), MAX_ARRAY_SIZE, and write().
writeNDItem()
template<int Dimensions> void sycl::_V1::detail::writeNDItem (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const nd_item< Dimensions > & ND_Item) inline
Definition at line 676 of file stream.hpp.
References append(), ArrayToStr(), sycl::_V1::nd_item< Dimensions >::get_global_id(), sycl::_V1::nd_item< Dimensions >::get_local_id(), MAX_ARRAY_SIZE, and write().
writeNDRange()
template<int Dimensions> void sycl::_V1::detail::writeNDRange (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const nd_range< Dimensions > & ND_Range) inline
Definition at line 657 of file stream.hpp.
References append(), ArrayToStr(), sycl::_V1::nd_range< Dimensions >::get_global_range(), sycl::_V1::nd_range< Dimensions >::get_local_range(), sycl::_V1::nd_range< Dimensions >::get_offset(), MAX_ARRAY_SIZE, and write().
writePixel()
template<typename T > void sycl::_V1::detail::writePixel (const vec< T, 4 > Pixel, T * Ptr, const image_channel_order ChannelOrder, const image_channel_type ChannelType)
Definition at line 218 of file image_accessor_util.hpp.
References sycl::_V1::a, sycl::_V1::abgr, sycl::_V1::argb, sycl::_V1::bgra, sycl::_V1::ext_oneapi_srgba, sycl::_V1::intensity, sycl::_V1::luminance, sycl::_V1::r, sycl::_V1::ra, sycl::_V1::rg, sycl::_V1::rgb, sycl::_V1::rgba, sycl::_V1::rgbx, sycl::_V1::rgx, sycl::_V1::rx, sycl::_V1::unorm_int_101010, sycl::_V1::unorm_short_555, and sycl::_V1::unorm_short_565.
Referenced by imageWriteHostImpl().
writeReduSumsToOutAccs()
template<bool IsOneWG, typename... Reductions, typename... OutAccT, typename... LocalAccT, typename... BOPsT, typename... Ts, size_t... Is> void sycl::_V1::detail::writeReduSumsToOutAccs (size_t OutAccIndex, ReduTupleT< OutAccT... > OutAccs, ReduTupleT< LocalAccT... > LocalAccs, ReduTupleT< BOPsT... > BOPs, ReduTupleT< Ts... > IdentityVals, std::array< bool, sizeof...(Reductions)> IsInitializeToIdentity, std::index_sequence< Is... >)
Definition at line 2066 of file reduction.hpp.
References getLastCombine().
Referenced by reduAuxCGFuncImplScalar(), and reduCGFuncImplScalar().
writeVec()
template<typename T , int VecLength> void sycl::_V1::detail::writeVec (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, int Precision, const vec< T, VecLength > & Vec) inline
Definition at line 600 of file stream.hpp.
References MAX_FLOATING_POINT_DIGITS, and write().
Variable Documentation
all_same_v
template<typename T0 , typename... Ts> constexpr bool sycl::_V1::detail::all_same_v = (... && std::is_same_v<T0, Ts>) inline constexpr
Definition at line 527 of file type_traits.hpp.
argument_helper
template<typename F , typename SuggestedArgType > decltype(member_ptr_helper(&F::operator())) sycl::_V1::detail::argument_helper(int) (int)
Definition at line 198 of file handler.hpp.
BackendNameKeyName
constexpr char sycl::_V1::detail::BackendNameKeyName[] = "BackendName" constexpr
Definition at line 22 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
BaseField
constexpr FmtFlags sycl::_V1::detail::BaseField = Dec | Hex | Oct static constexpr
Definition at line 62 of file stream.hpp.
Referenced by ScalarToStr().
builtin_same_or_swizzle_v
template<typename... Ts> constexpr bool sycl::_V1::detail::builtin_same_or_swizzle_v inline constexpr
Initial value:
=
    builtin_same_shape_v<Ts...> && all_same_v<simplify_if_swizzle_t<Ts>...>
Definition at line 79 of file builtins.hpp.
builtin_same_shape_v
template<typename... Ts> constexpr bool sycl::_V1::detail::builtin_same_shape_v inline constexpr
Initial value:
=
    ((... && is_scalar_arithmetic_v<Ts>) || (... && is_marray_v<Ts>) ||
     (... && is_vec_or_swizzle_v<Ts>)) &&
    (... && (num_elements<Ts>::value ==
             num_elements<typename first_type<Ts...>::type>::value))
Definition at line 72 of file builtins.hpp.
check_all_same_op_type_v
template<typename... Ts> constexpr bool sycl::_V1::detail::check_all_same_op_type_v = CheckAllSameOpType<Ts...>() constexpr
Definition at line 80 of file builtins_utils_scalar.hpp.
check_size_in_v
template<size_t... Ns> constexpr bool sycl::_V1::detail::check_size_in_v = CheckSizeIn<Ns...>() constexpr
Definition at line 83 of file builtins_utils_scalar.hpp.
check_type_in_v
template<typename... Ts> constexpr bool sycl::_V1::detail::check_type_in_v = CheckTypeIn<Ts...>() constexpr
Definition at line 554 of file type_traits.hpp.
ConfigFromCompileDefEnabled
constexpr bool sycl::_V1::detail::ConfigFromCompileDefEnabled = true constexpr
Definition at line 45 of file config.hpp.
ConfigFromEnvEnabled
constexpr bool sycl::_V1::detail::ConfigFromEnvEnabled = true constexpr
Definition at line 33 of file config.hpp.
ConfigFromFileEnabled
constexpr bool sycl::_V1::detail::ConfigFromFileEnabled = true constexpr
Definition at line 39 of file config.hpp.
DbgProgMgr
constexpr int sycl::_V1::detail::DbgProgMgr = 0 static constexpr
Definition at line 52 of file program_manager.cpp.
Referenced by sycl::_V1::detail::ProgramManager::createPIProgram(), sycl::_V1::detail::ProgramManager::flushSpecConstants(), sycl::_V1::detail::ProgramManager::getDeviceImage(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), and sycl::_V1::detail::ProgramManager::ProgramManager().
Dec
constexpr FmtFlags sycl::_V1::detail::Dec = 0x0001 static constexpr
Definition at line 51 of file stream.hpp.
Referenced by ScalarToStr().
DefaultContextType
constexpr CUDAContextT sycl::_V1::detail::DefaultContextType = CUDAContextT::custom constexpr
Default context type created for CUDA backend.
Definition at line 66 of file queue_impl.hpp.
device_arch_compare_op_ge
constexpr auto sycl::_V1::detail::device_arch_compare_op_ge constexpr
Initial value:
=
    [](ext::oneapi::experimental::architecture a,
       ext::oneapi::experimental::architecture b) constexpr { return a >= b; }
Definition at line 940 of file device_architecture.hpp.
Referenced by sycl::_V1::detail::if_architecture_helper< MakeCall >::else_if_architecture_is_between(), sycl::_V1::detail::if_architecture_helper< MakeCall >::else_if_architecture_is_ge(), sycl::_V1::ext::oneapi::experimental::if_architecture_is_between(), and sycl::_V1::ext::oneapi::experimental::if_architecture_is_ge().
device_arch_compare_op_gt
constexpr auto sycl::_V1::detail::device_arch_compare_op_gt constexpr
Initial value:
=
    [](ext::oneapi::experimental::architecture a,
       ext::oneapi::experimental::architecture b) constexpr { return a > b; }
Definition at line 937 of file device_architecture.hpp.
Referenced by sycl::_V1::detail::if_architecture_helper< MakeCall >::else_if_architecture_is_gt(), and sycl::_V1::ext::oneapi::experimental::if_architecture_is_gt().
device_arch_compare_op_le
constexpr auto sycl::_V1::detail::device_arch_compare_op_le constexpr
Initial value:
=
    [](ext::oneapi::experimental::architecture a,
       ext::oneapi::experimental::architecture b) constexpr { return a <= b; }
Definition at line 934 of file device_architecture.hpp.
Referenced by sycl::_V1::detail::if_architecture_helper< MakeCall >::else_if_architecture_is_between(), sycl::_V1::detail::if_architecture_helper< MakeCall >::else_if_architecture_is_le(), sycl::_V1::ext::oneapi::experimental::if_architecture_is_between(), and sycl::_V1::ext::oneapi::experimental::if_architecture_is_le().
device_arch_compare_op_lt
constexpr auto sycl::_V1::detail::device_arch_compare_op_lt constexpr
Initial value:
=
    [](ext::oneapi::experimental::architecture a,
       ext::oneapi::experimental::architecture b) constexpr { return a < b; }
Definition at line 931 of file device_architecture.hpp.
Referenced by sycl::_V1::detail::if_architecture_helper< MakeCall >::else_if_architecture_is_lt(), and sycl::_V1::ext::oneapi::experimental::if_architecture_is_lt().
DeviceLibExtensionStrs
const std::map<DeviceLibExt, const char *> sycl::_V1::detail::DeviceLibExtensionStrs static
Initial value:
= {
    {DeviceLibExt::cl_intel_devicelib_assert, "cl_intel_devicelib_assert"},
    {DeviceLibExt::cl_intel_devicelib_math, "cl_intel_devicelib_math"},
    {DeviceLibExt::cl_intel_devicelib_math_fp64,
     "cl_intel_devicelib_math_fp64"},
    {DeviceLibExt::cl_intel_devicelib_complex, "cl_intel_devicelib_complex"},
    {DeviceLibExt::cl_intel_devicelib_complex_fp64,
     "cl_intel_devicelib_complex_fp64"},
    {DeviceLibExt::cl_intel_devicelib_cstring, "cl_intel_devicelib_cstring"},
    {DeviceLibExt::cl_intel_devicelib_imf, "cl_intel_devicelib_imf"},
    {DeviceLibExt::cl_intel_devicelib_imf_fp64, "cl_intel_devicelib_imf_fp64"},
    {DeviceLibExt::cl_intel_devicelib_imf_bf16, "cl_intel_devicelib_imf_bf16"},
    {DeviceLibExt::cl_intel_devicelib_bfloat16,
     "cl_intel_bfloat16_conversions"}}
Definition at line 854 of file program_manager.cpp.
Referenced by getDeviceLibExtensionStr().
DeviceLibNames
const std::map<DeviceLibExt, std::pair<const char *, const char *> > sycl::_V1::detail::DeviceLibNames static
Initial value:
= {
        {DeviceLibExt::cl_intel_devicelib_assert,
         {nullptr, "libsycl-fallback-cassert.spv"}},
        {DeviceLibExt::cl_intel_devicelib_math,
         {nullptr, "libsycl-fallback-cmath.spv"}},
        {DeviceLibExt::cl_intel_devicelib_math_fp64,
         {nullptr, "libsycl-fallback-cmath-fp64.spv"}},
        {DeviceLibExt::cl_intel_devicelib_complex,
         {nullptr, "libsycl-fallback-complex.spv"}},
        {DeviceLibExt::cl_intel_devicelib_complex_fp64,
         {nullptr, "libsycl-fallback-complex-fp64.spv"}},
        {DeviceLibExt::cl_intel_devicelib_cstring,
         {nullptr, "libsycl-fallback-cstring.spv"}},
        {DeviceLibExt::cl_intel_devicelib_imf,
         {nullptr, "libsycl-fallback-imf.spv"}},
        {DeviceLibExt::cl_intel_devicelib_imf_fp64,
         {nullptr, "libsycl-fallback-imf-fp64.spv"}},
        {DeviceLibExt::cl_intel_devicelib_imf_bf16,
         {nullptr, "libsycl-fallback-imf-bf16.spv"}},
        {DeviceLibExt::cl_intel_devicelib_bfloat16,
         {"libsycl-native-bfloat16.spv", "libsycl-fallback-bfloat16.spv"}}}
Definition at line 818 of file program_manager.cpp.
Referenced by getDeviceLibFilename().
DeviceNameKeyName
constexpr char sycl::_V1::detail::DeviceNameKeyName[] = "DeviceName" constexpr
Definition at line 27 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
DeviceTypeKeyName
constexpr char sycl::_V1::detail::DeviceTypeKeyName[] = "DeviceType" constexpr
Definition at line 23 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
DeviceVendorIdKeyName
constexpr char sycl::_V1::detail::DeviceVendorIdKeyName[] = "DeviceVendorId" constexpr
Definition at line 24 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
DriverVersionKeyName
constexpr char sycl::_V1::detail::DriverVersionKeyName[] = "DriverVersion" constexpr
Definition at line 25 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
Fixed
constexpr FmtFlags sycl::_V1::detail::Fixed = 0x0020 static constexpr
Definition at line 56 of file stream.hpp.
FloatField
constexpr FmtFlags sycl::_V1::detail::FloatField = Scientific | Fixed static constexpr
Definition at line 67 of file stream.hpp.
FLUSH_BUF_OFFSET_SIZE
constexpr unsigned sycl::_V1::detail::FLUSH_BUF_OFFSET_SIZE = 2 constexpr
Definition at line 84 of file stream.hpp.
Referenced by sycl::_V1::detail::stream_impl::accessGlobalFlushBuf(), flushBuffer(), and write().
GCodeLocTLS
thread_local detail::code_location sycl::_V1::detail::GCodeLocTLS = {} static
CodeLocation information slot in thread local storage.
This structure is maintained by the SYCL runtime to manage the propagation of the code_location data down the stack without breaking ABI compatibility. This is used by the tls_code_loc_t class that is the prescribed way to propagate the code location information
Definition at line 19 of file common.cpp.
Referenced by sycl::_V1::detail::tls_code_loc_t::query(), sycl::_V1::detail::tls_code_loc_t::tls_code_loc_t(), and sycl::_V1::detail::tls_code_loc_t::~tls_code_loc_t().
get_multi_ptr_decoration_v
template<typename T > constexpr access::decorated sycl::_V1::detail::get_multi_ptr_decoration_v constexpr
Initial value:
=
    get_multi_ptr_decoration<T>::value
Definition at line 142 of file builtins_utils_scalar.hpp.
GlobalBufAS
constexpr static access::address_space sycl::_V1::detail::GlobalBufAS static constexpr
Initial value:
=
    TargetToAS<sycl::access::target::device>::AS
Definition at line 93 of file stream.hpp.
GlobalBufDim
constexpr static int sycl::_V1::detail::GlobalBufDim = 1 static constexpr
Definition at line 97 of file stream.hpp.
GlobalOffsetAS
constexpr static access::address_space sycl::_V1::detail::GlobalOffsetAS static constexpr
Initial value:
=
    TargetToAS<sycl::access::target::device>::AS
Definition at line 102 of file stream.hpp.
GlobalOffsetDim
constexpr static int sycl::_V1::detail::GlobalOffsetDim = 1 static constexpr
Definition at line 106 of file stream.hpp.
has_writeable_addr_space_v
template<typename T > constexpr bool sycl::_V1::detail::has_writeable_addr_space_v = has_writeable_addr_space<T>::value constexpr
Definition at line 157 of file builtins_utils_scalar.hpp.
Hex
constexpr FmtFlags sycl::_V1::detail::Hex = 0x0002 static constexpr
Definition at line 52 of file stream.hpp.
Referenced by ScalarToStr().
IntelCPUArchitectures
constexpr std::pair<const int, oneapi_exp_arch> sycl::_V1::detail::IntelCPUArchitectures[] constexpr
Initial value:
= {
    {8, oneapi_exp_arch::intel_cpu_spr},
    {9, oneapi_exp_arch::intel_cpu_gnr},
}
Definition at line 652 of file device_info.hpp.
Referenced by sycl::_V1::detail::get_device_info_impl< ext::oneapi::experimental::architecture, ext::oneapi::experimental::info::device::architecture >::get().
IntelGPUArchitectures
constexpr std::pair<const int, oneapi_exp_arch> sycl::_V1::detail::IntelGPUArchitectures[] constexpr
Initial value:
= {
    {0x02000000, oneapi_exp_arch::intel_gpu_bdw},
    {0x02400009, oneapi_exp_arch::intel_gpu_skl},
    {0x02404009, oneapi_exp_arch::intel_gpu_kbl},
    {0x02408009, oneapi_exp_arch::intel_gpu_cfl},
    {0x0240c000, oneapi_exp_arch::intel_gpu_apl},
    {0x02410000, oneapi_exp_arch::intel_gpu_glk},
    {0x02414000, oneapi_exp_arch::intel_gpu_whl},
    {0x02418000, oneapi_exp_arch::intel_gpu_aml},
    {0x0241c000, oneapi_exp_arch::intel_gpu_cml},
    {0x02c00000, oneapi_exp_arch::intel_gpu_icllp},
    {0x02c08000, oneapi_exp_arch::intel_gpu_ehl},
    {0x03000000, oneapi_exp_arch::intel_gpu_tgllp},
    {0x03004000, oneapi_exp_arch::intel_gpu_rkl},
    {0x03008000, oneapi_exp_arch::intel_gpu_adl_s},
    {0x0300c000, oneapi_exp_arch::intel_gpu_adl_p},
    {0x03010000, oneapi_exp_arch::intel_gpu_adl_n},
    {0x03028000, oneapi_exp_arch::intel_gpu_dg1},
    {0x030dc008, oneapi_exp_arch::intel_gpu_acm_g10},
    {0x030e0005, oneapi_exp_arch::intel_gpu_acm_g11},
    {0x030e4000, oneapi_exp_arch::intel_gpu_acm_g12},
    {0x030f0007, oneapi_exp_arch::intel_gpu_pvc},
    {0x030f4007, oneapi_exp_arch::intel_gpu_pvc_vg},
    {0x03118004, oneapi_exp_arch::intel_gpu_mtl_u},
    {0x0311c004, oneapi_exp_arch::intel_gpu_mtl_h},
    {0x03128004, oneapi_exp_arch::intel_gpu_arl_h},
    {0x05004004, oneapi_exp_arch::intel_gpu_bmg_g21},
    {0x05010004, oneapi_exp_arch::intel_gpu_lnl_m},
}
Definition at line 621 of file device_info.hpp.
Referenced by sycl::_V1::detail::get_device_info_impl< ext::oneapi::experimental::architecture, ext::oneapi::experimental::info::device::architecture >::get().
is_address_space_compliant_v
template<typename T , typename SpaceList > constexpr bool sycl::_V1::detail::is_address_space_compliant_v inline constexpr
Initial value:
=
    is_address_space_compliant<T, SpaceList>::value
Definition at line 442 of file type_traits.hpp.
is_allowable_aot_mode
constexpr bool sycl::_V1::detail::is_allowable_aot_mode static constexpr
Definition at line 489 of file device_architecture.hpp.
Referenced by allowable_aot_mode().
is_bfloat16_v
template<typename T > constexpr bool sycl::_V1::detail::is_bfloat16_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_bfloat16_list>
Definition at line 42 of file generic_type_traits.hpp.
is_boolean_v
template<typename T > constexpr bool sycl::_V1::detail::is_boolean_v = is_boolean<T>::value inline constexpr
Definition at line 350 of file type_traits.hpp.
is_contained_v
template<typename T , typename TypeList > constexpr bool sycl::_V1::detail::is_contained_v = is_contained<T, TypeList>::value inline constexpr
Definition at line 34 of file type_list.hpp.
is_ext_vector_v
template<typename T > constexpr bool sycl::_V1::detail::is_ext_vector_v = is_ext_vector<T>::value inline constexpr
Definition at line 190 of file type_traits.hpp.
is_fixed_size_group_v
template<class T > constexpr bool sycl::_V1::detail::is_fixed_size_group_v = is_fixed_size_group<T>::value inline constexpr
Definition at line 26 of file type_traits.hpp.
is_gen_based_on_type_sizeof_v
template<typename T , int N, template< typename > class S> constexpr bool sycl::_V1::detail::is_gen_based_on_type_sizeof_v inline constexpr
Initial value:
=
    S<T>::value && (sizeof(vector_element_t<T>) == N)
Definition at line 278 of file type_traits.hpp.
is_genbool_v
template<typename T > constexpr bool sycl::_V1::detail::is_genbool_v = is_contained_v<T, gtl::bool_list> inline constexpr
Definition at line 183 of file generic_type_traits.hpp.
is_gencross_v
template<typename T > constexpr bool sycl::_V1::detail::is_gencross_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::cross_floating_list>
Definition at line 121 of file generic_type_traits.hpp.
is_gencrossdouble_v
template<typename T > constexpr bool sycl::_V1::detail::is_gencrossdouble_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::cross_double_list>
Definition at line 113 of file generic_type_traits.hpp.
is_gencrossfloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_gencrossfloat_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::cross_float_list>
Definition at line 109 of file generic_type_traits.hpp.
is_gencrosshalf_v
template<typename T > constexpr bool sycl::_V1::detail::is_gencrosshalf_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::cross_half_list>
Definition at line 117 of file generic_type_traits.hpp.
is_gencrossmarray_v
template<typename T > constexpr bool sycl::_V1::detail::is_gencrossmarray_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::cross_marray_list>
Definition at line 125 of file generic_type_traits.hpp.
is_generic_group_v
template<typename T > constexpr bool sycl::_V1::detail::is_generic_group_v = is_generic_group<T>::value inline constexpr
Definition at line 92 of file type_traits.hpp.
is_genfloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_genfloat_v = is_contained_v<T, gtl::floating_list> inline constexpr
Definition at line 54 of file generic_type_traits.hpp.
is_genfloatptr_marray_v
template<typename T , access::address_space AddressSpace, access::decorated IsDecorated> constexpr bool sycl::_V1::detail::is_genfloatptr_marray_v inline constexpr
Initial value:
=
    is_mgenfloat_v<T> &&
    is_address_space_compliant_v<multi_ptr<T, AddressSpace, IsDecorated>,
                                 gvl::nonconst_address_space_list> &&
    (IsDecorated == access::decorated::yes ||
     IsDecorated == access::decorated::no)
Definition at line 248 of file generic_type_traits.hpp.
is_genfloatptr_v
template<typename T > constexpr bool sycl::_V1::detail::is_genfloatptr_v inline constexpr
Initial value:
=
    is_pointer_v<T> && is_genfloat_v<remove_pointer_t<T>> &&
    is_address_space_compliant_v<T, gvl::nonconst_address_space_list>
Definition at line 242 of file generic_type_traits.hpp.
is_gengeodouble_v
template<typename T > constexpr bool sycl::_V1::detail::is_gengeodouble_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::geo_double_list>
Definition at line 76 of file generic_type_traits.hpp.
is_gengeofloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_gengeofloat_v = is_contained_v<T, gtl::geo_float_list> inline constexpr
Definition at line 73 of file generic_type_traits.hpp.
is_gengeohalf_v
template<typename T > constexpr bool sycl::_V1::detail::is_gengeohalf_v = is_contained_v<T, gtl::geo_half_list> inline constexpr
Definition at line 88 of file generic_type_traits.hpp.
is_gengeomarray_v
template<typename T > constexpr bool sycl::_V1::detail::is_gengeomarray_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::marray_geo_list>
Definition at line 84 of file generic_type_traits.hpp.
is_gengeomarrayfloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_gengeomarrayfloat_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::marray_geo_float_list>
Definition at line 80 of file generic_type_traits.hpp.
is_genint_v
template<typename T > constexpr bool sycl::_V1::detail::is_genint_v = is_contained_v<T, gtl::signed_int_list> inline constexpr
Definition at line 136 of file generic_type_traits.hpp.
is_geninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_geninteger_v = is_contained_v<T, gtl::integer_list> inline constexpr
Definition at line 139 of file generic_type_traits.hpp.
is_genintptr_marray_v
template<typename T , access::address_space AddressSpace, access::decorated IsDecorated> constexpr bool sycl::_V1::detail::is_genintptr_marray_v inline constexpr
Initial value:
=
    std::is_same_v<T, sycl::marray<marray_element_t<T>, T::size()>> &&
    is_genint_v<marray_element_t<remove_pointer_t<T>>> &&
    is_address_space_compliant_v<multi_ptr<T, AddressSpace, IsDecorated>,
                                 gvl::nonconst_address_space_list> &&
    (IsDecorated == access::decorated::yes ||
     IsDecorated == access::decorated::no)
Definition at line 233 of file generic_type_traits.hpp.
is_genintptr_v
template<typename T > constexpr bool sycl::_V1::detail::is_genintptr_v inline constexpr
Initial value:
=
    is_pointer_v<T> && is_genint_v<remove_pointer_t<T>> &&
    is_address_space_compliant_v<T, gvl::nonconst_address_space_list>
Definition at line 227 of file generic_type_traits.hpp.
is_gentype_v
template<typename T > constexpr bool sycl::_V1::detail::is_gentype_v = is_contained_v<T, gtl::basic_list> inline constexpr
Definition at line 186 of file generic_type_traits.hpp.
is_half_or_bf16_v
template<typename T > constexpr bool sycl::_V1::detail::is_half_or_bf16_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::half_bfloat16_list>
Definition at line 46 of file generic_type_traits.hpp.
is_half_v
template<typename T > constexpr bool sycl::_V1::detail::is_half_v = is_contained_v<T, gtl::scalar_half_list> inline constexpr
Definition at line 39 of file generic_type_traits.hpp.
is_igeninteger16bit_v
template<typename T > constexpr bool sycl::_V1::detail::is_igeninteger16bit_v inline constexpr
Initial value:
=
    is_gen_based_on_type_sizeof_v<T, 2, is_igeninteger>
Definition at line 199 of file generic_type_traits.hpp.
is_igeninteger32bit_v
template<typename T > constexpr bool sycl::_V1::detail::is_igeninteger32bit_v inline constexpr
Initial value:
=
    is_gen_based_on_type_sizeof_v<T, 4, is_igeninteger>
Definition at line 203 of file generic_type_traits.hpp.
is_igeninteger64bit_v
template<typename T > constexpr bool sycl::_V1::detail::is_igeninteger64bit_v inline constexpr
Initial value:
=
    is_gen_based_on_type_sizeof_v<T, 8, is_igeninteger>
Definition at line 207 of file generic_type_traits.hpp.
is_igeninteger8bit_v
template<typename T > constexpr bool sycl::_V1::detail::is_igeninteger8bit_v inline constexpr
Initial value:
=
    is_gen_based_on_type_sizeof_v<T, 1, is_igeninteger>
Definition at line 195 of file generic_type_traits.hpp.
is_igeninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_igeninteger_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::signed_integer_list>
Definition at line 145 of file generic_type_traits.hpp.
is_intn_v
template<typename T > constexpr bool sycl::_V1::detail::is_intn_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::vector_signed_int_list>
Definition at line 132 of file generic_type_traits.hpp.
is_legacy_multi_ptr_v
template<class T > constexpr bool sycl::_V1::detail::is_legacy_multi_ptr_v = is_legacy_multi_ptr<T>::value inline constexpr
Definition at line 402 of file type_traits.hpp.
is_marray_v
template<typename T > constexpr bool sycl::_V1::detail::is_marray_v = is_marray<T>::value constexpr
Definition at line 299 of file type_traits.hpp.
is_mgenfloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_mgenfloat_v inline constexpr
Initial value:
=
    is_marray_v<T> && is_svgenfloat_v<get_elem_type_t<T>>
Definition at line 69 of file generic_type_traits.hpp.
is_multi_ptr_v
template<class T > constexpr bool sycl::_V1::detail::is_multi_ptr_v = is_multi_ptr<T>::value inline constexpr
Definition at line 376 of file type_traits.hpp.
is_non_legacy_multi_ptr_v
template<class T > constexpr bool sycl::_V1::detail::is_non_legacy_multi_ptr_v inline constexpr
Initial value:
=
    is_non_legacy_multi_ptr<T>::value
Definition at line 390 of file type_traits.hpp.
is_pointer_v
template<typename T > constexpr bool sycl::_V1::detail::is_pointer_v = is_pointer<T>::value inline constexpr
Definition at line 365 of file type_traits.hpp.
is_same_op_v
template<typename T1 , typename T2 > constexpr bool sycl::_V1::detail::is_same_op_v = is_same_op<T1, T2>::value constexpr
Definition at line 62 of file builtins_utils_scalar.hpp.
is_scalar_arithmetic_v
template<typename T > constexpr bool sycl::_V1::detail::is_scalar_arithmetic_v = is_scalar_arithmetic<T>::value inline constexpr
Definition at line 326 of file type_traits.hpp.
is_sgenfloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_sgenfloat_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_floating_list>
Definition at line 57 of file generic_type_traits.hpp.
is_sgengeo_v
template<typename T > constexpr bool sycl::_V1::detail::is_sgengeo_v = is_contained_v<T, gtl::scalar_geo_list> inline constexpr
Definition at line 103 of file generic_type_traits.hpp.
is_sgeninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_sgeninteger_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_integer_list>
Definition at line 159 of file generic_type_traits.hpp.
is_sgentype_v
template<typename T > constexpr bool sycl::_V1::detail::is_sgentype_v = is_contained_v<T, gtl::scalar_basic_list> inline constexpr
Definition at line 192 of file generic_type_traits.hpp.
is_sigeninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_sigeninteger_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_signed_integer_list>
Definition at line 167 of file generic_type_traits.hpp.
is_sugeninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_sugeninteger_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_unsigned_integer_list>
Definition at line 171 of file generic_type_traits.hpp.
is_svgenfloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_svgenfloat_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_vector_floating_list>
Definition at line 65 of file generic_type_traits.hpp.
is_svgenfloatd_v
template<typename T > constexpr bool sycl::_V1::detail::is_svgenfloatd_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_vector_double_list>
Definition at line 35 of file generic_type_traits.hpp.
is_svgenfloatf_v
template<typename T > constexpr bool sycl::_V1::detail::is_svgenfloatf_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_vector_float_list>
Definition at line 31 of file generic_type_traits.hpp.
is_svgenfloath_v
template<typename T > constexpr bool sycl::_V1::detail::is_svgenfloath_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::scalar_vector_half_list>
Definition at line 50 of file generic_type_traits.hpp.
is_swizzle_v
template<typename T > constexpr bool sycl::_V1::detail::is_swizzle_v = is_swizzle<T>::value constexpr
Definition at line 25 of file builtins_utils_vec.hpp.
is_ugenint_v
template<typename T > constexpr bool sycl::_V1::detail::is_ugenint_v = is_contained_v<T, gtl::unsigned_int_list> inline constexpr
Definition at line 129 of file generic_type_traits.hpp.
is_ugeninteger16bit_v
template<typename T > constexpr bool sycl::_V1::detail::is_ugeninteger16bit_v inline constexpr
Initial value:
=
    is_gen_based_on_type_sizeof_v<T, 2, is_ugeninteger>
Definition at line 215 of file generic_type_traits.hpp.
is_ugeninteger32bit_v
template<typename T > constexpr bool sycl::_V1::detail::is_ugeninteger32bit_v inline constexpr
Initial value:
=
    is_gen_based_on_type_sizeof_v<T, 4, is_ugeninteger>
Definition at line 219 of file generic_type_traits.hpp.
is_ugeninteger64bit_v
template<typename T > constexpr bool sycl::_V1::detail::is_ugeninteger64bit_v inline constexpr
Initial value:
=
    is_gen_based_on_type_sizeof_v<T, 8, is_ugeninteger>
Definition at line 223 of file generic_type_traits.hpp.
is_ugeninteger8bit_v
template<typename T > constexpr bool sycl::_V1::detail::is_ugeninteger8bit_v inline constexpr
Initial value:
=
    is_gen_based_on_type_sizeof_v<T, 1, is_ugeninteger>
Definition at line 211 of file generic_type_traits.hpp.
is_ugeninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_ugeninteger_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::unsigned_integer_list>
Definition at line 152 of file generic_type_traits.hpp.
is_valid_elem_type_v
template<typename T , typename... Ts> constexpr bool sycl::_V1::detail::is_valid_elem_type_v = is_valid_elem_type<T, Ts...>::value constexpr
Definition at line 130 of file builtins_utils_scalar.hpp.
is_valid_size_v
template<typename T , int... Ns> constexpr bool sycl::_V1::detail::is_valid_size_v = is_valid_size<T, Ns...>::value constexpr
Definition at line 69 of file builtins_utils_vec.hpp.
is_vec_or_swizzle_v
template<typename T > constexpr bool sycl::_V1::detail::is_vec_or_swizzle_v = is_vec_v<T> || is_swizzle_v<T> constexpr
Definition at line 28 of file builtins_utils_vec.hpp.
is_vec_v
template<typename T > constexpr bool sycl::_V1::detail::is_vec_v = is_vec<T>::value constexpr
Definition at line 284 of file type_traits.hpp.
is_vgenfloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_vgenfloat_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::vector_floating_list>
Definition at line 61 of file generic_type_traits.hpp.
is_vgengeo_v
template<typename T > constexpr bool sycl::_V1::detail::is_vgengeo_v = is_contained_v<T, gtl::vector_geo_list> inline constexpr
Definition at line 106 of file generic_type_traits.hpp.
is_vgengeodouble_v
template<typename T > constexpr bool sycl::_V1::detail::is_vgengeodouble_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::vector_geo_double_list>
Definition at line 95 of file generic_type_traits.hpp.
is_vgengeofloat_v
template<typename T > constexpr bool sycl::_V1::detail::is_vgengeofloat_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::vector_geo_float_list>
Definition at line 91 of file generic_type_traits.hpp.
is_vgengeohalf_v
template<typename T > constexpr bool sycl::_V1::detail::is_vgengeohalf_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::vector_geo_half_list>
Definition at line 99 of file generic_type_traits.hpp.
is_vgeninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_vgeninteger_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::vector_integer_list>
Definition at line 163 of file generic_type_traits.hpp.
is_vgentype_v
template<typename T > constexpr bool sycl::_V1::detail::is_vgentype_v = is_contained_v<T, gtl::vector_basic_list> inline constexpr
Definition at line 189 of file generic_type_traits.hpp.
is_vigeninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_vigeninteger_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::vector_signed_integer_list>
Definition at line 175 of file generic_type_traits.hpp.
is_vugeninteger_v
template<typename T > constexpr bool sycl::_V1::detail::is_vugeninteger_v inline constexpr
Initial value:
=
    is_contained_v<T, gtl::vector_unsigned_integer_list>
Definition at line 179 of file generic_type_traits.hpp.
ITTSpecConstId
constexpr uint32_t sycl::_V1::detail::ITTSpecConstId = 0xFF747469 inline static constexpr
Definition at line 61 of file program_manager.hpp.
Referenced by enableITTAnnotationsIfNeeded().
max_amd_gpu_architecture
constexpr ext::oneapi::experimental::architecture sycl::_V1::detail::max_amd_gpu_architecture static constexpr
Initial value:
=
        ext::oneapi::experimental::architecture::amd_gpu_gfx1201
Definition at line 240 of file device_architecture.hpp.
Referenced by get_category_max_architecture(), and get_device_architecture_category().
MAX_ARRAY_SIZE
constexpr size_t sycl::_V1::detail::MAX_ARRAY_SIZE constexpr
Initial value:
=
    MAX_INTEGRAL_DIGITS * MAX_DIMENSIONS + 2 * (MAX_DIMENSIONS - 1) + 2
Definition at line 79 of file stream.hpp.
Referenced by writeArray(), writeGroup(), writeItem(), writeNDItem(), and writeNDRange().
MAX_CONFIG_NAME
constexpr int sycl::_V1::detail::MAX_CONFIG_NAME = 256 constexpr
Definition at line 48 of file config.hpp.
Referenced by readConfig().
MAX_CONFIG_VALUE
constexpr int sycl::_V1::detail::MAX_CONFIG_VALUE = 1024 constexpr
Definition at line 49 of file config.hpp.
Referenced by readConfig().
MAX_DIMENSIONS
constexpr size_t sycl::_V1::detail::MAX_DIMENSIONS = 3 constexpr
Definition at line 75 of file stream.hpp.
MAX_FLOATING_POINT_DIGITS
constexpr size_t sycl::_V1::detail::MAX_FLOATING_POINT_DIGITS = 24 constexpr
Definition at line 69 of file stream.hpp.
Referenced by floatingPointToDecStr(), writeFloatingPoint(), and writeVec().
MAX_INTEGRAL_DIGITS
constexpr size_t sycl::_V1::detail::MAX_INTEGRAL_DIGITS = 23 constexpr
Definition at line 70 of file stream.hpp.
Referenced by writeIntegral().
max_intel_gpu_architecture
constexpr ext::oneapi::experimental::architecture sycl::_V1::detail::max_intel_gpu_architecture static constexpr
Initial value:
=
        ext::oneapi::experimental::architecture::intel_gpu_lnl_m
Definition at line 226 of file device_architecture.hpp.
Referenced by get_category_max_architecture(), and get_device_architecture_category().
MAX_ITEM_SIZE
constexpr size_t sycl::_V1::detail::MAX_ITEM_SIZE = 2 * MAX_ARRAY_SIZE + 20 constexpr
Definition at line 715 of file stream.hpp.
Referenced by writeHItem().
max_nvidia_gpu_architecture
constexpr ext::oneapi::experimental::architecture sycl::_V1::detail::max_nvidia_gpu_architecture static constexpr
Initial value:
=
        ext::oneapi::experimental::architecture::nvidia_gpu_sm_90
Definition at line 233 of file device_architecture.hpp.
Referenced by get_category_max_architecture(), and get_device_architecture_category().
MaxNumQueues
constexpr size_t sycl::_V1::detail::MaxNumQueues = 256 static constexpr
Sets max number of queues supported by FPGA RT.
Definition at line 59 of file queue_impl.hpp.
Referenced by sycl::_V1::detail::queue_impl::getExclusiveQueueHandleRef().
MaxVecAlignment
constexpr size_t sycl::_V1::detail::MaxVecAlignment = 64 constexpr
Definition at line 21 of file vector_traits.hpp.
min_amd_gpu_architecture
constexpr ext::oneapi::experimental::architecture sycl::_V1::detail::min_amd_gpu_architecture static constexpr
Initial value:
=
        ext::oneapi::experimental::architecture::amd_gpu_gfx700
Definition at line 237 of file device_architecture.hpp.
Referenced by get_category_min_architecture(), and get_device_architecture_category().
min_intel_gpu_architecture
constexpr ext::oneapi::experimental::architecture sycl::_V1::detail::min_intel_gpu_architecture static constexpr
Initial value:
=
        ext::oneapi::experimental::architecture::intel_gpu_bdw
Definition at line 223 of file device_architecture.hpp.
Referenced by get_category_min_architecture(), and get_device_architecture_category().
min_nvidia_gpu_architecture
constexpr ext::oneapi::experimental::architecture sycl::_V1::detail::min_nvidia_gpu_architecture static constexpr
Initial value:
=
        ext::oneapi::experimental::architecture::nvidia_gpu_sm_50
Definition at line 230 of file device_architecture.hpp.
Referenced by get_category_min_architecture(), and get_device_architecture_category().
NvidiaAmdGPUArchitectures
constexpr std::pair<const char *, oneapi_exp_arch> sycl::_V1::detail::NvidiaAmdGPUArchitectures[] constexpr
Definition at line 565 of file device_info.hpp.
Referenced by sycl::_V1::detail::get_device_info_impl< ext::oneapi::experimental::architecture, ext::oneapi::experimental::info::device::architecture >::get().
Oct
constexpr FmtFlags sycl::_V1::detail::Oct = 0x0004 static constexpr
Definition at line 53 of file stream.hpp.
Referenced by ScalarToStr().
PlatformNameKeyName
constexpr char sycl::_V1::detail::PlatformNameKeyName[] = "PlatformName" constexpr
Definition at line 28 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
PlatformVersionKeyName
constexpr char sycl::_V1::detail::PlatformVersionKeyName[] = "PlatformVersion" constexpr
Definition at line 26 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
REJECT_DEVICE_SCORE
constexpr int sycl::_V1::detail::REJECT_DEVICE_SCORE = -1 static constexpr
Definition at line 120 of file device_selector.hpp.
Referenced by select_device().
Scientific
constexpr FmtFlags sycl::_V1::detail::Scientific = 0x0040 static constexpr
Definition at line 57 of file stream.hpp.
Referenced by ScalarToStr().
ShowBase
constexpr FmtFlags sycl::_V1::detail::ShowBase = 0x0008 static constexpr
Definition at line 54 of file stream.hpp.
Referenced by ScalarToStr().
ShowPos
constexpr FmtFlags sycl::_V1::detail::ShowPos = 0x0010 static constexpr
Definition at line 55 of file stream.hpp.
Referenced by ScalarToStr().
SupportedAllowListKeyNames
constexpr std::array<const char *, 7> sycl::_V1::detail::SupportedAllowListKeyNames constexpr
Initial value:
{
    BackendNameKeyName,   DeviceTypeKeyName,      DeviceVendorIdKeyName,
    DriverVersionKeyName, PlatformVersionKeyName, DeviceNameKeyName,
    PlatformNameKeyName}
Definition at line 30 of file allowlist.cpp.
Referenced by deviceIsAllowed(), and parseAllowList().
SYCL_BUFFER_STREAM_NAME
constexpr const char* sycl::_V1::detail::SYCL_BUFFER_STREAM_NAME inline constexpr
Initial value:
=
    "sycl.experimental.buffer"
Definition at line 60 of file xpti_registry.hpp.
Referenced by sycl::_V1::detail::XPTIRegistry::initializeFrameworkOnce().
SYCL_IMAGE_STREAM_NAME
constexpr const char* sycl::_V1::detail::SYCL_IMAGE_STREAM_NAME = "sycl.experimental.image" inline constexpr
Definition at line 64 of file xpti_registry.hpp.
Referenced by sycl::_V1::detail::XPTIRegistry::initializeFrameworkOnce().
SYCL_MEM_ALLOC_STREAM_NAME
constexpr auto sycl::_V1::detail::SYCL_MEM_ALLOC_STREAM_NAME inline constexpr
Initial value:
=
    "sycl.experimental.mem_alloc"
Definition at line 35 of file xpti_registry.hpp.
Referenced by sycl::_V1::detail::usm::alignedAlloc(), sycl::_V1::detail::usm::alignedAllocHost(), sycl::_V1::detail::usm::free(), and sycl::_V1::detail::XPTIRegistry::initializeFrameworkOnce().
SYCL_PICALL_STREAM_NAME
constexpr const char* sycl::_V1::detail::SYCL_PICALL_STREAM_NAME = "sycl.pi" inline constexpr
Definition at line 31 of file xpti_registry.hpp.
Referenced by sycl::_V1::detail::pi::initializePlugins().
SYCL_PIDEBUGCALL_STREAM_NAME
constexpr const char* sycl::_V1::detail::SYCL_PIDEBUGCALL_STREAM_NAME = "sycl.pi.debug" inline constexpr
Definition at line 34 of file xpti_registry.hpp.
Referenced by sycl::_V1::detail::pi::initializePlugins().
SYCL_STREAM_NAME
constexpr const char* sycl::_V1::detail::SYCL_STREAM_NAME = "sycl" inline constexpr
Definition at line 29 of file xpti_registry.hpp.
Referenced by sycl::_V1::detail::Command::Command(), sycl::_V1::detail::pi::initializePlugins(), sycl::_V1::detail::GlobalHandler::InitXPTI(), sycl::_V1::detail::queue_impl::memcpy(), sycl::_V1::detail::queue_impl::memset(), sycl::_V1::detail::queue_impl::queue_impl(), sycl::_V1::detail::GlobalHandler::TraceEventXPTI(), sycl::_V1::detail::queue_impl::wait(), and sycl::_V1::detail::event_impl::wait().
use_fast_math_v
template<typename T > constexpr bool sycl::_V1::detail::use_fast_math_v = use_fast_math<T>::value constexpr
Definition at line 35 of file builtins_utils_scalar.hpp.
UseToUseStringMap
constexpr UseToUseStringPair sycl::_V1::detail::UseToUseStringMap[] constexpr
Initial value:
= {
    {ext::oneapi::experimental::matrix::use::a, "use::a"},
    {ext::oneapi::experimental::matrix::use::b, "use::b"},
    {ext::oneapi::experimental::matrix::use::accumulator, "use::accumulator"},
}
Definition at line 47 of file matrix-unified-utils.hpp.
Referenced by convertMatrixUseEnumToString(), and convertMatrixUseStringToEnum().
VEC_CLOSE_BRACE
constexpr char sycl::_V1::detail::VEC_CLOSE_BRACE = '}' constexpr
Definition at line 73 of file stream.hpp.
Referenced by ArrayToStr().
VEC_ELEMENT_DELIMITER
constexpr const char* sycl::_V1::detail::VEC_ELEMENT_DELIMITER = ", " constexpr
Definition at line 71 of file stream.hpp.
Referenced by ArrayToStr(), and VecToStr().
VEC_OPEN_BRACE
constexpr char sycl::_V1::detail::VEC_OPEN_BRACE = '{' constexpr
Definition at line 72 of file stream.hpp.
Referenced by ArrayToStr().