DPC++ Runtime: __esimd Namespace Reference
__esimd Namespace Reference
Classes
struct Log2
Compute binary logarithm of a constexpr with guaranteed compile-time evaluation.
struct Log2< N, false >
struct Log2< N, true >
struct NextPowerOf2
Compute next power of 2 of a constexpr with guaranteed compile-time evaluation.
struct NextPowerOf2< N, K, false >
struct NextPowerOf2< N, K, true >
Enumerations
enum {
BYTE = 1, WORD = 2, DWORD = 4, QWORD = 8,
OWORD = 16, GRF = 32
}
Constant in number of bytes.
Functions
template<unsigned int N>
constexpr unsigned int getNextPowerOf2 ()
template<>
constexpr unsigned int getNextPowerOf2< 0 > ()
template<unsigned int N>
constexpr unsigned int log2 ()
static ESIMD_INLINE constexpr bool isPowerOf2 (unsigned int n)
Check if a given 32 bit positive integer is a power of 2 at compile time.
static ESIMD_INLINE constexpr bool isPowerOf2 (unsigned int n, unsigned int limit)
Enumeration Type Documentation
anonymous enum
anonymous enum
Constant in number of bytes.
Enumerator
BYTE
WORD
DWORD
QWORD
OWORD
GRF
Definition at line 18 of file esimd_util.hpp.
Function Documentation
getNextPowerOf2()
template<unsigned int N> constexpr unsigned int __esimd::getNextPowerOf2 ()
Definition at line 34 of file esimd_util.hpp.
getNextPowerOf2< 0 >()
template<> constexpr unsigned int __esimd::getNextPowerOf2< 0 > ()
Definition at line 38 of file esimd_util.hpp.
isPowerOf2() [1/2]
static ESIMD_INLINE constexpr bool __esimd::isPowerOf2 (unsigned int n) static
Check if a given 32 bit positive integer is a power of 2 at compile time.
Definition at line 59 of file esimd_util.hpp.
Referenced by cl::sycl::INTEL::gpu::block_load(), cl::sycl::INTEL::gpu::block_store(), cl::sycl::INTEL::gpu::check_atomic(), cl::sycl::INTEL::gpu::detail::esimd_reduce(), cl::sycl::INTEL::gpu::detail::esimd_reduce_pair(), cl::sycl::INTEL::gpu::detail::esimd_reduce_single(), cl::sycl::INTEL::gpu::slm_block_load(), and cl::sycl::INTEL::gpu::slm_block_store().
isPowerOf2() [2/2]
static ESIMD_INLINE constexpr bool __esimd::isPowerOf2 (unsigned int n, unsigned int limit) static
Definition at line 63 of file esimd_util.hpp.
References __SYCL_INLINE_NAMESPACE.
log2()
template<unsigned int N> constexpr unsigned int __esimd::log2 ()
Definition at line 54 of file esimd_util.hpp.