DPC++ Runtime: syclcompat::experimental::detail Namespace Reference
syclcompat::experimental::detail Namespace Reference
Classes
struct KernelFunctor
struct tuple_template_index_helper
struct tuple_template_index_helper< PropertyContainer, std::tuple<> >
struct tuple_template_index_helper< PropertyContainer, std::tuple< PropertyContainer< T >, Rest... > >
struct tuple_template_index_helper< PropertyContainer, std::tuple< First, Rest... > >
struct tuple_template_index
Functions
template<auto F, typename LaunchPolicy , typename... Args>
sycl::event launch (LaunchPolicy launch_policy, sycl::queue q, Args... args)
template<auto F, typename LaunchPolicy , typename... Args>
auto build_kernel_functor (sycl::handler &cgh, LaunchPolicy launch_policy, Args... args) -> KernelFunctor< F, typename LaunchPolicy::RangeT, typename LaunchPolicy::KPropsT, LaunchPolicy::HasLocalMem, Args... >
static pitched_data to_pitched_data (image_matrix *image)
static std::vector< sycl::event > memcpy (sycl::queue q, const experimental::memcpy_parameter &param)
Function Documentation
build_kernel_functor()
template<auto F, typename LaunchPolicy , typename... Args> auto syclcompat::experimental::detail::build_kernel_functor (sycl::handler & cgh, LaunchPolicy launch_policy, Args... args) -> KernelFunctor<F, typename LaunchPolicy::RangeT, typename LaunchPolicy::KPropsT, LaunchPolicy::HasLocalMem, Args...>
Definition at line 232 of file launch_policy.hpp.
References syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::get_kernel_properties(), and syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::get_local_mem_size().
launch()
template<auto F, typename LaunchPolicy , typename... Args> sycl::event syclcompat::experimental::detail::launch (LaunchPolicy launch_policy, sycl::queue q, Args... args)
Definition at line 128 of file launch.hpp.
References syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::get_launch_properties(), syclcompat::experimental::launch_policy< Range, KProps, LProps, LocalMem >::get_range(), syclcompat::detail::is_range_v, sycl::_V1::ext::oneapi::experimental::nd_launch(), sycl::_V1::ext::oneapi::experimental::parallel_for(), and sycl::_V1::ext::oneapi::experimental::submit_with_event().
memcpy()
static std::vector<sycl::event> syclcompat::experimental::detail::memcpy (sycl::queue q, const experimental::memcpy_parameter & param) inline static
Definition at line 486 of file memory.hpp.
References syclcompat::experimental::memcpy_parameter::from, syclcompat::detail::host_buffer::get_ptr(), syclcompat::experimental::memcpy_parameter::data_wrapper::image, syclcompat::detail::memcpy(), syclcompat::experimental::memcpy_parameter::data_wrapper::pitched, syclcompat::experimental::memcpy_parameter::data_wrapper::pos, syclcompat::experimental::memcpy_parameter::size, syclcompat::experimental::memcpy_parameter::to, and to_pitched_data().
Referenced by syclcompat::experimental::memcpy(), and syclcompat::experimental::memcpy_async().
to_pitched_data()
static pitched_data syclcompat::experimental::detail::to_pitched_data (image_matrix * image) static
Referenced by memcpy().