DPC++ Runtime: sycl::_V1::ext::intel::detail Namespace Reference
sycl::_V1::ext::intel::detail Namespace Reference
Functions
int selectDeviceByPlatform (std::string_view required_platform_name, const device &device)
void enableFPGASimulator ()
Function Documentation
enableFPGASimulator()
void sycl::_V1::ext::intel::detail::enableFPGASimulator () inline
Definition at line 36 of file fpga_device_selector.hpp.
Referenced by sycl::_V1::ext::intel::fpga_simulator_selector_v().
selectDeviceByPlatform()
int sycl::_V1::ext::intel::detail::selectDeviceByPlatform (std::string_view required_platform_name, const device & device) inline
Definition at line 27 of file fpga_device_selector.hpp.
References sycl::_V1::platform::get_info(), and sycl::_V1::device::get_platform().
Referenced by sycl::_V1::ext::intel::fpga_emulator_selector_v(), sycl::_V1::ext::intel::fpga_selector_v(), and sycl::_V1::ext::intel::platform_selector::operator()().