DPC++ Runtime: sycl::_V1::detail::usm Namespace Reference
sycl::_V1::detail::usm Namespace Reference
Functions
void * alignedAlloc (size_t Alignment, size_t Bytes, const context &Ctxt, const device &Dev, sycl::usm::alloc Kind, const code_location &CL)
void * alignedAllocHost (size_t Alignment, size_t Bytes, const context &Ctxt, sycl::usm::alloc Kind, const code_location &CL)
void free (void *Ptr, const context &Ctxt, const code_location &CL)
void * alignedAllocHost (size_t Alignment, size_t Size, const context &Ctxt, alloc Kind, const property_list &PropList, const detail::code_location &CodeLoc)
void * alignedAllocInternal (size_t Alignment, size_t Size, const context_impl *CtxImpl, const device_impl *DevImpl, alloc Kind, const property_list &PropList)
void * alignedAlloc (size_t Alignment, size_t Size, const context &Ctxt, const device &Dev, alloc Kind, const property_list &PropList, const detail::code_location &CodeLoc)
void freeInternal (void *Ptr, const context_impl *CtxImpl)
Function Documentation
alignedAlloc() [1/2]
void* sycl::_V1::detail::usm::alignedAlloc (size_t Alignment, size_t Bytes, const context & Ctxt, const device & Dev, sycl::usm::alloc Kind, const code_location & CL)
Referenced by alignedAlloc().
alignedAlloc() [2/2]
void* sycl::_V1::detail::usm::alignedAlloc (size_t Alignment, size_t Size, const context & Ctxt, const device & Dev, alloc Kind, const property_list & PropList, const detail::code_location & CodeLoc)
Definition at line 252 of file usm_impl.cpp.
References alignedAlloc(), alignedAllocInternal(), sycl::_V1::ext::oneapi::experimental::detail::Alignment, sycl::_V1::get(), sycl::_V1::device::get_info(), sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::SYCL_MEM_ALLOC_STREAM_NAME.
alignedAllocHost() [1/2]
void* sycl::_V1::detail::usm::alignedAllocHost (size_t Alignment, size_t Bytes, const context & Ctxt, sycl::usm::alloc Kind, const code_location & CL)
Referenced by alignedAllocHost().
alignedAllocHost() [2/2]
void* sycl::_V1::detail::usm::alignedAllocHost (size_t Alignment, size_t Size, const context & Ctxt, alloc Kind, const property_list & PropList, const detail::code_location & CodeLoc)
Definition at line 43 of file usm_impl.cpp.
References alignedAllocHost(), sycl::_V1::ext::oneapi::experimental::detail::Alignment, sycl::_V1::detail::aligned_allocator< T >::allocate(), any_of(), sycl::_V1::ext::intel::experimental::buffer_location, sycl::_V1::context::get_devices(), sycl::_V1::context::get_platform(), sycl::_V1::property_list::get_property(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::property_list::has_property(), PI_MEM_USM_ALLOC_BUFFER_LOCATION, piextUSMHostAlloc(), and sycl::_V1::detail::SYCL_MEM_ALLOC_STREAM_NAME.
alignedAllocInternal()
void * sycl::_V1::detail::usm::alignedAllocInternal (size_t Alignment, size_t Size, const context_impl * CtxImpl, const device_impl * DevImpl, alloc Kind, const property_list & PropList)
Definition at line 139 of file usm_impl.cpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, sycl::_V1::detail::aligned_allocator< T >::allocate(), sycl::_V1::ext::intel::experimental::buffer_location, sycl::_V1::property_list::get_property(), sycl::_V1::detail::context_impl::getHandleRef(), sycl::_V1::detail::device_impl::getHandleRef(), sycl::_V1::detail::context_impl::getPlugin(), sycl::_V1::detail::device_impl::has(), sycl::_V1::detail::device_impl::has_extension(), sycl::_V1::property_list::has_property(), sycl::_V1::detail::context_impl::is_host(), PI_MEM_ALLOC_DEVICE_READ_ONLY, PI_MEM_ALLOC_FLAGS, PI_MEM_USM_ALLOC_BUFFER_LOCATION, piextUSMDeviceAlloc(), and piextUSMSharedAlloc().
Referenced by alignedAlloc(), and sycl::_V1::detail::DeviceGlobalMapEntry::getOrAllocateDeviceGlobalUSM().
free()
void sycl::_V1::detail::usm::free (void * Ptr, const context & Ctxt, const code_location & CL)
Definition at line 297 of file usm_impl.cpp.
References freeInternal(), sycl::_V1::get(), sycl::_V1::detail::getSyclObjImpl(), and sycl::_V1::detail::SYCL_MEM_ALLOC_STREAM_NAME.
freeInternal()
void sycl::_V1::detail::usm::freeInternal (void * Ptr, const context_impl * CtxImpl)
Definition at line 284 of file usm_impl.cpp.
References sycl::_V1::detail::OSUtil::alignedFree(), sycl::_V1::detail::context_impl::getHandleRef(), sycl::_V1::detail::context_impl::getPlugin(), sycl::_V1::detail::context_impl::is_host(), and piextUSMFree().
Referenced by free(), and sycl::_V1::detail::DeviceGlobalMapEntry::removeAssociatedResources().