DPC++ Runtime: cl::__host_std Namespace Reference
cl::__host_std Namespace Reference
Namespaces
detail
Functions
__SYCL_MAKE_CALL_ARG2_SAME (Dot, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME_RESULT(FMul
__FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (FOrdEqual, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(FUnordNotEqual
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (FOrdGreaterThan, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(FOrdGreaterThanEqual
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (FOrdLessThan, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(FOrdLessThanEqual
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (FOrdNotEqual, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(LessOrGreater
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG1 (IsFinite, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG1(IsInf
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG1 (IsNan, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG1(IsNormal
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG2_SAME (Ordered, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG2_SAME(Unordered
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG1 (SignBitSet, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG1(Any
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __SYCL_MAKE_CALL_ARG1 (All, __FUNC_PREFIX_CORE) __SYCL_MAKE_CALL_ARG3(select
s::cl_float fclamp (s::cl_float x, s::cl_float minval, s::cl_float maxval) __NOEXC
s::cl_double fclamp (s::cl_double x, s::cl_double minval, s::cl_double maxval) __NOEXC
s::cl_half fclamp (s::cl_half x, s::cl_half minval, s::cl_half maxval) __NOEXC
s::cl_float degrees (s::cl_float radians) __NOEXC
s::cl_double degrees (s::cl_double radians) __NOEXC
s::cl_half degrees (s::cl_half radians) __NOEXC
s::cl_float fmin_common (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double fmin_common (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half fmin_common (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float fmax_common (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double fmax_common (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half fmax_common (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float mix (s::cl_float x, s::cl_float y, s::cl_float a) __NOEXC
s::cl_double mix (s::cl_double x, s::cl_double y, s::cl_double a) __NOEXC
s::cl_half mix (s::cl_half x, s::cl_half y, s::cl_half a) __NOEXC
s::cl_float radians (s::cl_float degrees) __NOEXC
s::cl_double radians (s::cl_double degrees) __NOEXC
s::cl_half radians (s::cl_half degrees) __NOEXC
s::cl_float step (s::cl_float edge, s::cl_float x) __NOEXC
s::cl_double step (s::cl_double edge, s::cl_double x) __NOEXC
s::cl_half step (s::cl_half edge, s::cl_half x) __NOEXC
s::cl_float smoothstep (s::cl_float edge0, s::cl_float edge1, s::cl_float x) __NOEXC
s::cl_double smoothstep (s::cl_double edge0, s::cl_double edge1, s::cl_double x) __NOEXC
s::cl_half smoothstep (s::cl_half edge0, s::cl_half edge1, s::cl_half x) __NOEXC
s::cl_float Dot (s::vec< float, 1 >, s::vec< float, 1 >)
s::cl_float Dot (s::cl_float2, s::cl_float2)
s::cl_float Dot (s::cl_float3, s::cl_float3)
s::cl_float Dot (s::cl_float4, s::cl_float4)
s::cl_double Dot (s::vec< double, 1 >, s::vec< double, 1 >)
s::cl_double Dot (s::cl_double2, s::cl_double2)
s::cl_double Dot (s::cl_double3, s::cl_double3)
s::cl_double Dot (s::cl_double4, s::cl_double4)
s::cl_half Dot (s::cl_half2, s::cl_half2)
s::cl_half Dot (s::cl_half3, s::cl_half3)
s::cl_half Dot (s::cl_half4, s::cl_half4)
s::cl_int All (s::vec< int, 1 >)
s::cl_int All (s::cl_int2)
s::cl_int All (s::cl_int3)
s::cl_int All (s::cl_int4)
s::cl_float3 cross (s::cl_float3 p0, s::cl_float3 p1) __NOEXC
s::cl_float4 cross (s::cl_float4 p0, s::cl_float4 p1) __NOEXC
s::cl_double3 cross (s::cl_double3 p0, s::cl_double3 p1) __NOEXC
s::cl_double4 cross (s::cl_double4 p0, s::cl_double4 p1) __NOEXC
s::cl_half3 cross (s::cl_half3 p0, s::cl_half3 p1) __NOEXC
s::cl_half4 cross (s::cl_half4 p0, s::cl_half4 p1) __NOEXC
s::cl_float FMul (s::cl_float p0, s::cl_float p1)
s::cl_double FMul (s::cl_double p0, s::cl_double p1)
s::cl_float FMul (s::cl_half p0, s::cl_half p1)
s::cl_float length (s::cl_float p)
s::cl_double length (s::cl_double p)
s::cl_half length (s::cl_half p)
s::cl_float length (s::vec< float, 1 > p)
s::cl_float length (s::cl_float2 p)
s::cl_float length (s::cl_float3 p)
s::cl_float length (s::cl_float4 p)
s::cl_double length (s::vec< double, 1 > p)
s::cl_double length (s::cl_double2 p)
s::cl_double length (s::cl_double3 p)
s::cl_double length (s::cl_double4 p)
s::cl_half length (s::vec< s::half, 1 > p)
s::cl_half length (s::cl_half2 p)
s::cl_half length (s::cl_half3 p)
s::cl_half length (s::cl_half4 p)
s::cl_float distance (s::cl_float p0, s::cl_float p1)
s::cl_float distance (s::vec< float, 1 > p0, s::vec< float, 1 > p1)
s::cl_float distance (s::cl_float2 p0, s::cl_float2 p1)
s::cl_float distance (s::cl_float3 p0, s::cl_float3 p1)
s::cl_float distance (s::cl_float4 p0, s::cl_float4 p1)
s::cl_double distance (s::cl_double p0, s::cl_double p1)
s::cl_float distance (s::vec< double, 1 > p0, s::vec< double, 1 > p1)
s::cl_double distance (s::cl_double2 p0, s::cl_double2 p1)
s::cl_double distance (s::cl_double3 p0, s::cl_double3 p1)
s::cl_double distance (s::cl_double4 p0, s::cl_double4 p1)
s::cl_half distance (s::cl_half p0, s::cl_half p1)
s::cl_float distance (s::vec< s::half, 1 > p0, s::vec< s::half, 1 > p1)
s::cl_half distance (s::cl_half2 p0, s::cl_half2 p1)
s::cl_half distance (s::cl_half3 p0, s::cl_half3 p1)
s::cl_half distance (s::cl_half4 p0, s::cl_half4 p1)
s::cl_float normalize (s::cl_float p)
s::cl_float normalize (s::vec< float, 1 > p)
s::cl_float2 normalize (s::cl_float2 p)
s::cl_float3 normalize (s::cl_float3 p)
s::cl_float4 normalize (s::cl_float4 p)
s::cl_double normalize (s::cl_double p)
s::cl_double normalize (s::vec< double, 1 > p)
s::cl_double2 normalize (s::cl_double2 p)
s::cl_double3 normalize (s::cl_double3 p)
s::cl_double4 normalize (s::cl_double4 p)
s::cl_half normalize (s::cl_half p)
s::cl_half2 normalize (s::cl_half2 p)
s::cl_half3 normalize (s::cl_half3 p)
s::cl_half4 normalize (s::cl_half4 p)
s::cl_float fast_length (s::cl_float p)
s::cl_float fast_length (s::vec< float, 1 > p)
s::cl_float fast_length (s::cl_float2 p)
s::cl_float fast_length (s::cl_float3 p)
s::cl_float fast_length (s::cl_float4 p)
s::cl_float fast_normalize (s::cl_float p)
s::cl_float fast_normalize (s::vec< float, 1 > p)
s::cl_float2 fast_normalize (s::cl_float2 p)
s::cl_float3 fast_normalize (s::cl_float3 p)
s::cl_float4 fast_normalize (s::cl_float4 p)
s::cl_float fast_distance (s::cl_float p0, s::cl_float p1)
s::cl_float fast_distance (s::vec< float, 1 > p0, s::vec< float, 1 > p1)
s::cl_float fast_distance (s::cl_float2 p0, s::cl_float2 p1)
s::cl_float fast_distance (s::cl_float3 p0, s::cl_float3 p1)
s::cl_float fast_distance (s::cl_float4 p0, s::cl_float4 p1)
s::cl_uchar u_abs (s::cl_uchar x) __NOEXC
s::cl_ushort u_abs (s::cl_ushort x) __NOEXC
s::cl_uint u_abs (s::cl_uint x) __NOEXC
s::cl_ulong u_abs (s::cl_ulong x) __NOEXC
s::cl_uchar s_abs (s::cl_char x) __NOEXC
s::cl_ushort s_abs (s::cl_short x) __NOEXC
s::cl_uint s_abs (s::cl_int x) __NOEXC
s::cl_ulong s_abs (s::cl_long x) __NOEXC
s::cl_uchar u_abs_diff (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort u_abs_diff (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint u_abs_diff (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong u_abs_diff (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_uchar s_abs_diff (s::cl_char x, s::cl_char y) __NOEXC
s::cl_ushort s_abs_diff (s::cl_short x, s::cl_short y) __NOEXC
s::cl_uint s_abs_diff (s::cl_int x, s::cl_int y) __NOEXC
s::cl_ulong s_abs_diff (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar u_add_sat (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort u_add_sat (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint u_add_sat (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong u_add_sat (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char s_add_sat (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short s_add_sat (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int s_add_sat (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long s_add_sat (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar u_hadd (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort u_hadd (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint u_hadd (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong u_hadd (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char s_hadd (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short s_hadd (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int s_hadd (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long s_hadd (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar u_rhadd (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort u_rhadd (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint u_rhadd (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong u_rhadd (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char s_rhadd (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short s_rhadd (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int s_rhadd (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long s_rhadd (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar u_clamp (s::cl_uchar x, s::cl_uchar minval, s::cl_uchar maxval) __NOEXC
s::cl_ushort u_clamp (s::cl_ushort x, s::cl_ushort minval, s::cl_ushort maxval) __NOEXC
s::cl_uint u_clamp (s::cl_uint x, s::cl_uint minval, s::cl_uint maxval) __NOEXC
s::cl_ulong u_clamp (s::cl_ulong x, s::cl_ulong minval, s::cl_ulong maxval) __NOEXC
s::cl_char s_clamp (s::cl_char x, s::cl_char minval, s::cl_char maxval) __NOEXC
s::cl_short s_clamp (s::cl_short x, s::cl_short minval, s::cl_short maxval) __NOEXC
s::cl_int s_clamp (s::cl_int x, s::cl_int minval, s::cl_int maxval) __NOEXC
s::cl_long s_clamp (s::cl_long x, s::cl_long minval, s::cl_long maxval) __NOEXC
s::cl_uchar clz (s::cl_uchar x) __NOEXC
s::cl_char clz (s::cl_char x) __NOEXC
s::cl_ushort clz (s::cl_ushort x) __NOEXC
s::cl_short clz (s::cl_short x) __NOEXC
s::cl_uint clz (s::cl_uint x) __NOEXC
s::cl_int clz (s::cl_int x) __NOEXC
s::cl_ulong clz (s::cl_ulong x) __NOEXC
s::cl_long clz (s::cl_long x) __NOEXC
s::cl_uchar ctz (s::cl_uchar x) __NOEXC
s::cl_char ctz (s::cl_char x) __NOEXC
s::cl_ushort ctz (s::cl_ushort x) __NOEXC
s::cl_short ctz (s::cl_short x) __NOEXC
s::cl_uint ctz (s::cl_uint x) __NOEXC
s::cl_int ctz (s::cl_int x) __NOEXC
s::cl_ulong ctz (s::cl_ulong x) __NOEXC
s::cl_long ctz (s::cl_long x) __NOEXC
s::cl_char s_mul_hi (s::cl_char a, s::cl_char b)
s::cl_short s_mul_hi (s::cl_short a, s::cl_short b)
s::cl_int s_mul_hi (s::cl_int a, s::cl_int b)
s::cl_long s_mul_hi (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar u_mul_hi (s::cl_uchar a, s::cl_uchar b)
s::cl_ushort u_mul_hi (s::cl_ushort a, s::cl_ushort b)
s::cl_uint u_mul_hi (s::cl_uint a, s::cl_uint b)
s::cl_ulong u_mul_hi (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char s_mad_hi (s::cl_char x, s::cl_char minval, s::cl_char maxval) __NOEXC
s::cl_short s_mad_hi (s::cl_short x, s::cl_short minval, s::cl_short maxval) __NOEXC
s::cl_int s_mad_hi (s::cl_int x, s::cl_int minval, s::cl_int maxval) __NOEXC
s::cl_long s_mad_hi (s::cl_long x, s::cl_long minval, s::cl_long maxval) __NOEXC
s::cl_uchar u_mad_hi (s::cl_uchar x, s::cl_uchar minval, s::cl_uchar maxval) __NOEXC
s::cl_ushort u_mad_hi (s::cl_ushort x, s::cl_ushort minval, s::cl_ushort maxval) __NOEXC
s::cl_uint u_mad_hi (s::cl_uint x, s::cl_uint minval, s::cl_uint maxval) __NOEXC
s::cl_ulong u_mad_hi (s::cl_ulong x, s::cl_ulong minval, s::cl_ulong maxval) __NOEXC
s::cl_char s_mad_sat (s::cl_char a, s::cl_char b, s::cl_char c) __NOEXC
s::cl_short s_mad_sat (s::cl_short a, s::cl_short b, s::cl_short c) __NOEXC
s::cl_int s_mad_sat (s::cl_int a, s::cl_int b, s::cl_int c) __NOEXC
s::cl_long s_mad_sat (s::cl_long a, s::cl_long b, s::cl_long c) __NOEXC
s::cl_uchar u_mad_sat (s::cl_uchar a, s::cl_uchar b, s::cl_uchar c) __NOEXC
s::cl_ushort u_mad_sat (s::cl_ushort a, s::cl_ushort b, s::cl_ushort c) __NOEXC
s::cl_uint u_mad_sat (s::cl_uint a, s::cl_uint b, s::cl_uint c) __NOEXC
s::cl_ulong u_mad_sat (s::cl_ulong a, s::cl_ulong b, s::cl_ulong c) __NOEXC
s::cl_char s_max (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short s_max (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int s_max (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long s_max (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar u_max (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort u_max (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint u_max (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong u_max (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char s_min (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short s_min (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int s_min (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long s_min (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar u_min (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort u_min (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint u_min (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong u_min (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_uchar rotate (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort rotate (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint rotate (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong rotate (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char rotate (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short rotate (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int rotate (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long rotate (s::cl_long x, s::cl_long y) __NOEXC
s::cl_uchar u_sub_sat (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_ushort u_sub_sat (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_uint u_sub_sat (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_ulong u_sub_sat (s::cl_ulong x, s::cl_ulong y) __NOEXC
s::cl_char s_sub_sat (s::cl_char x, s::cl_char y) __NOEXC
s::cl_short s_sub_sat (s::cl_short x, s::cl_short y) __NOEXC
s::cl_int s_sub_sat (s::cl_int x, s::cl_int y) __NOEXC
s::cl_long s_sub_sat (s::cl_long x, s::cl_long y) __NOEXC
s::cl_ushort u_upsample (s::cl_uchar x, s::cl_uchar y) __NOEXC
s::cl_uint u_upsample (s::cl_ushort x, s::cl_ushort y) __NOEXC
s::cl_ulong u_upsample (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_short s_upsample (s::cl_char x, s::cl_uchar y) __NOEXC
s::cl_int s_upsample (s::cl_short x, s::cl_ushort y) __NOEXC
s::cl_long s_upsample (s::cl_int x, s::cl_uint y) __NOEXC
s::cl_uchar popcount (s::cl_uchar x) __NOEXC
s::cl_ushort popcount (s::cl_ushort x) __NOEXC
s::cl_uint popcount (s::cl_uint x) __NOEXC
s::cl_ulong popcount (s::cl_ulong x) __NOEXC
s::cl_char popcount (s::cl_char x) __NOEXC
s::cl_short popcount (s::cl_short x) __NOEXC
s::cl_int popcount (s::cl_int x) __NOEXC
s::cl_long popcount (s::cl_long x) __NOEXC
s::cl_uint u_mad24 (s::cl_uint x, s::cl_uint y, s::cl_uint z) __NOEXC
s::cl_int s_mad24 (s::cl_int x, s::cl_int y, s::cl_int z) __NOEXC
s::cl_uint u_mul24 (s::cl_uint x, s::cl_uint y) __NOEXC
s::cl_int s_mul24 (s::cl_int x, s::cl_int y) __NOEXC
s::cl_float acos (s::cl_float x) __NOEXC
s::cl_double acos (s::cl_double x) __NOEXC
s::cl_half acos (s::cl_half x) __NOEXC
s::cl_float acosh (s::cl_float x) __NOEXC
s::cl_double acosh (s::cl_double x) __NOEXC
s::cl_half acosh (s::cl_half x) __NOEXC
s::cl_float acospi (s::cl_float x) __NOEXC
s::cl_double acospi (s::cl_double x) __NOEXC
s::cl_half acospi (s::cl_half x) __NOEXC
s::cl_float asin (s::cl_float x) __NOEXC
s::cl_double asin (s::cl_double x) __NOEXC
s::cl_half asin (s::cl_half x) __NOEXC
s::cl_float asinh (s::cl_float x) __NOEXC
s::cl_double asinh (s::cl_double x) __NOEXC
s::cl_half asinh (s::cl_half x) __NOEXC
s::cl_float asinpi (s::cl_float x) __NOEXC
s::cl_double asinpi (s::cl_double x) __NOEXC
s::cl_half asinpi (s::cl_half x) __NOEXC
s::cl_float atan (s::cl_float x) __NOEXC
s::cl_double atan (s::cl_double x) __NOEXC
s::cl_half atan (s::cl_half x) __NOEXC
s::cl_float atan2 (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double atan2 (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half atan2 (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float atanh (s::cl_float x) __NOEXC
s::cl_double atanh (s::cl_double x) __NOEXC
s::cl_half atanh (s::cl_half x) __NOEXC
s::cl_float atanpi (s::cl_float x) __NOEXC
s::cl_double atanpi (s::cl_double x) __NOEXC
s::cl_half atanpi (s::cl_half x) __NOEXC
s::cl_float atan2pi (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double atan2pi (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half atan2pi (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float cbrt (s::cl_float x) __NOEXC
s::cl_double cbrt (s::cl_double x) __NOEXC
s::cl_half cbrt (s::cl_half x) __NOEXC
s::cl_float ceil (s::cl_float x) __NOEXC
s::cl_double ceil (s::cl_double x) __NOEXC
s::cl_half ceil (s::cl_half x) __NOEXC
s::cl_float copysign (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double copysign (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half copysign (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float cos (s::cl_float x) __NOEXC
s::cl_double cos (s::cl_double x) __NOEXC
s::cl_half cos (s::cl_half x) __NOEXC
s::cl_float cosh (s::cl_float x) __NOEXC
s::cl_double cosh (s::cl_double x) __NOEXC
s::cl_half cosh (s::cl_half x) __NOEXC
s::cl_float cospi (s::cl_float x) __NOEXC
s::cl_double cospi (s::cl_double x) __NOEXC
s::cl_half cospi (s::cl_half x) __NOEXC
s::cl_float erfc (s::cl_float x) __NOEXC
s::cl_double erfc (s::cl_double x) __NOEXC
s::cl_half erfc (s::cl_half x) __NOEXC
s::cl_float erf (s::cl_float x) __NOEXC
s::cl_double erf (s::cl_double x) __NOEXC
s::cl_half erf (s::cl_half x) __NOEXC
s::cl_float exp (s::cl_float x) __NOEXC
s::cl_double exp (s::cl_double x) __NOEXC
s::cl_half exp (s::cl_half x) __NOEXC
s::cl_float exp2 (s::cl_float x) __NOEXC
s::cl_double exp2 (s::cl_double x) __NOEXC
s::cl_half exp2 (s::cl_half x) __NOEXC
s::cl_float exp10 (s::cl_float x) __NOEXC
s::cl_double exp10 (s::cl_double x) __NOEXC
s::cl_half exp10 (s::cl_half x) __NOEXC
s::cl_float expm1 (s::cl_float x) __NOEXC
s::cl_double expm1 (s::cl_double x) __NOEXC
s::cl_half expm1 (s::cl_half x) __NOEXC
s::cl_float fabs (s::cl_float x) __NOEXC
s::cl_double fabs (s::cl_double x) __NOEXC
s::cl_half fabs (s::cl_half x) __NOEXC
s::cl_float fdim (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double fdim (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half fdim (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float floor (s::cl_float x) __NOEXC
s::cl_double floor (s::cl_double x) __NOEXC
s::cl_half floor (s::cl_half x) __NOEXC
s::cl_float fma (s::cl_float a, s::cl_float b, s::cl_float c) __NOEXC
s::cl_double fma (s::cl_double a, s::cl_double b, s::cl_double c) __NOEXC
s::cl_half fma (s::cl_half a, s::cl_half b, s::cl_half c) __NOEXC
s::cl_float fmax (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double fmax (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half fmax (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float fmin (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double fmin (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half fmin (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float fmod (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double fmod (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half fmod (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float nextafter (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double nextafter (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half nextafter (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float fract (s::cl_float x, s::cl_float *iptr) __NOEXC
s::cl_double fract (s::cl_double x, s::cl_double *iptr) __NOEXC
s::cl_half fract (s::cl_half x, s::cl_half *iptr) __NOEXC
s::cl_float frexp (s::cl_float x, s::cl_int *exp) __NOEXC
s::cl_double frexp (s::cl_double x, s::cl_int *exp) __NOEXC
s::cl_half frexp (s::cl_half x, s::cl_int *exp) __NOEXC
s::cl_float hypot (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double hypot (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half hypot (s::cl_half x, s::cl_half y) __NOEXC
s::cl_int ilogb (s::cl_float x) __NOEXC
s::cl_int ilogb (s::cl_double x) __NOEXC
s::cl_int ilogb (s::cl_half x) __NOEXC
s::cl_float ldexp (s::cl_float x, s::cl_int k) __NOEXC
s::cl_double ldexp (s::cl_double x, s::cl_int k) __NOEXC
s::cl_half ldexp (s::cl_half x, s::cl_int k) __NOEXC
s::cl_float lgamma (s::cl_float x) __NOEXC
s::cl_double lgamma (s::cl_double x) __NOEXC
s::cl_half lgamma (s::cl_half x) __NOEXC
s::cl_float lgamma_r (s::cl_float x, s::cl_int *signp) __NOEXC
s::cl_double lgamma_r (s::cl_double x, s::cl_int *signp) __NOEXC
s::cl_half lgamma_r (s::cl_half x, s::cl_int *signp) __NOEXC
s::cl_float log (s::cl_float x) __NOEXC
s::cl_double log (s::cl_double x) __NOEXC
s::cl_half log (s::cl_half x) __NOEXC
s::cl_float log2 (s::cl_float x) __NOEXC
s::cl_double log2 (s::cl_double x) __NOEXC
s::cl_half log2 (s::cl_half x) __NOEXC
s::cl_float log10 (s::cl_float x) __NOEXC
s::cl_double log10 (s::cl_double x) __NOEXC
s::cl_half log10 (s::cl_half x) __NOEXC
s::cl_float log1p (s::cl_float x) __NOEXC
s::cl_double log1p (s::cl_double x) __NOEXC
s::cl_half log1p (s::cl_half x) __NOEXC
s::cl_float logb (s::cl_float x) __NOEXC
s::cl_double logb (s::cl_double x) __NOEXC
s::cl_half logb (s::cl_half x) __NOEXC
s::cl_float mad (s::cl_float a, s::cl_float b, s::cl_float c) __NOEXC
s::cl_double mad (s::cl_double a, s::cl_double b, s::cl_double c) __NOEXC
s::cl_half mad (s::cl_half a, s::cl_half b, s::cl_half c) __NOEXC
s::cl_float maxmag (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double maxmag (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half maxmag (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float minmag (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double minmag (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half minmag (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float modf (s::cl_float x, s::cl_float *iptr) __NOEXC
s::cl_double modf (s::cl_double x, s::cl_double *iptr) __NOEXC
s::cl_half modf (s::cl_half x, s::cl_half *iptr) __NOEXC
s::cl_float nan (s::cl_uint nancode) __NOEXC
s::cl_double nan (s::cl_ulong nancode) __NOEXC
s::cl_half nan (s::cl_ushort nancode) __NOEXC
s::cl_float pow (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double pow (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half pow (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float pown (s::cl_float x, s::cl_int y) __NOEXC
s::cl_double pown (s::cl_double x, s::cl_int y) __NOEXC
s::cl_half pown (s::cl_half x, s::cl_int y) __NOEXC
s::cl_float powr (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double powr (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half powr (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float remainder (s::cl_float x, s::cl_float y) __NOEXC
s::cl_double remainder (s::cl_double x, s::cl_double y) __NOEXC
s::cl_half remainder (s::cl_half x, s::cl_half y) __NOEXC
s::cl_float remquo (s::cl_float x, s::cl_float y, s::cl_int *quo) __NOEXC
s::cl_double remquo (s::cl_double x, s::cl_double y, s::cl_int *quo) __NOEXC
s::cl_half remquo (s::cl_half x, s::cl_half y, s::cl_int *quo) __NOEXC
s::cl_float rint (s::cl_float x) __NOEXC
s::cl_double rint (s::cl_double x) __NOEXC
s::cl_half rint (s::cl_half x) __NOEXC
s::cl_float rootn (s::cl_float x, s::cl_int y) __NOEXC
s::cl_double rootn (s::cl_double x, s::cl_int y) __NOEXC
s::cl_half rootn (s::cl_half x, s::cl_int y) __NOEXC
s::cl_float round (s::cl_float x) __NOEXC
s::cl_double round (s::cl_double x) __NOEXC
s::cl_half round (s::cl_half x) __NOEXC
s::cl_float rsqrt (s::cl_float x) __NOEXC
s::cl_double rsqrt (s::cl_double x) __NOEXC
s::cl_half rsqrt (s::cl_half x) __NOEXC
s::cl_float sin (s::cl_float x) __NOEXC
s::cl_double sin (s::cl_double x) __NOEXC
s::cl_half sin (s::cl_half x) __NOEXC
s::cl_float sincos (s::cl_float x, s::cl_float *cosval) __NOEXC
s::cl_double sincos (s::cl_double x, s::cl_double *cosval) __NOEXC
s::cl_half sincos (s::cl_half x, s::cl_half *cosval) __NOEXC
s::cl_float sinh (s::cl_float x) __NOEXC
s::cl_double sinh (s::cl_double x) __NOEXC
s::cl_half sinh (s::cl_half x) __NOEXC
s::cl_float sinpi (s::cl_float x) __NOEXC
s::cl_double sinpi (s::cl_double x) __NOEXC
s::cl_half sinpi (s::cl_half x) __NOEXC
s::cl_float sqrt (s::cl_float x) __NOEXC
s::cl_double sqrt (s::cl_double x) __NOEXC
s::cl_half sqrt (s::cl_half x) __NOEXC
s::cl_float tan (s::cl_float x) __NOEXC
s::cl_double tan (s::cl_double x) __NOEXC
s::cl_half tan (s::cl_half x) __NOEXC
s::cl_float tanh (s::cl_float x) __NOEXC
s::cl_double tanh (s::cl_double x) __NOEXC
s::cl_half tanh (s::cl_half x) __NOEXC
s::cl_float tanpi (s::cl_float x) __NOEXC
s::cl_double tanpi (s::cl_double x) __NOEXC
s::cl_half tanpi (s::cl_half x) __NOEXC
s::cl_float tgamma (s::cl_float x) __NOEXC
s::cl_double tgamma (s::cl_double x) __NOEXC
s::cl_half tgamma (s::cl_half x) __NOEXC
s::cl_float trunc (s::cl_float x) __NOEXC
s::cl_double trunc (s::cl_double x) __NOEXC
s::cl_half trunc (s::cl_half x) __NOEXC
s::cl_float native_cos (s::cl_float x) __NOEXC
s::cl_float native_divide (s::cl_float x, s::cl_float y) __NOEXC
s::cl_float native_exp (s::cl_float x) __NOEXC
s::cl_float native_exp2 (s::cl_float x) __NOEXC
s::cl_float native_exp10 (s::cl_float x) __NOEXC
s::cl_float native_log (s::cl_float x) __NOEXC
s::cl_float native_log2 (s::cl_float x) __NOEXC
s::cl_float native_log10 (s::cl_float x) __NOEXC
s::cl_float native_powr (s::cl_float x, s::cl_float y) __NOEXC
s::cl_float native_recip (s::cl_float x) __NOEXC
s::cl_float native_rsqrt (s::cl_float x) __NOEXC
s::cl_float native_sin (s::cl_float x) __NOEXC
s::cl_float native_sqrt (s::cl_float x) __NOEXC
s::cl_float native_tan (s::cl_float x) __NOEXC
s::cl_float half_cos (s::cl_float x) __NOEXC
s::cl_float half_divide (s::cl_float x, s::cl_float y) __NOEXC
s::cl_float half_exp (s::cl_float x) __NOEXC
s::cl_float half_exp2 (s::cl_float x) __NOEXC
s::cl_float half_exp10 (s::cl_float x) __NOEXC
s::cl_float half_log (s::cl_float x) __NOEXC
s::cl_float half_log2 (s::cl_float x) __NOEXC
s::cl_float half_log10 (s::cl_float x) __NOEXC
s::cl_float half_powr (s::cl_float x, s::cl_float y) __NOEXC
s::cl_float half_recip (s::cl_float x) __NOEXC
s::cl_float half_rsqrt (s::cl_float x) __NOEXC
s::cl_float half_sin (s::cl_float x) __NOEXC
s::cl_float half_sqrt (s::cl_float x) __NOEXC
s::cl_float half_tan (s::cl_float x) __NOEXC
s::cl_int FOrdEqual (s::cl_float x, s::cl_float y) __NOEXC
s::cl_int FOrdEqual (s::cl_double x, s::cl_double y) __NOEXC
s::cl_int FOrdEqual (s::cl_half x, s::cl_half y) __NOEXC
s::cl_int FUnordNotEqual (s::cl_float x, s::cl_float y) __NOEXC
s::cl_int FUnordNotEqual (s::cl_double x, s::cl_double y) __NOEXC
s::cl_int FUnordNotEqual (s::cl_half x, s::cl_half y) __NOEXC
MAKE_1V_2V_FUNC (FUnordNotEqual, __vFUnordNotEqual, s::cl_int, s::cl_float, s::cl_float) MAKE_1V_2V_FUNC(FUnordNotEqual
Variables
s::cl_half Dot (s::vec< s::half, 1 >, s::vec< s::half, 1 >)
__vFUnordNotEqual
Function Documentation
__SYCL_MAKE_CALL_ARG1() [1/4]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG1 (All , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG1() [2/4]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG1 (IsFinite , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG1() [3/4]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG1 (IsNan , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG1() [4/4]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG1 (SignBitSet , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [1/6]
cl::__host_std::__SYCL_MAKE_CALL_ARG2_SAME (Dot , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [2/6]
__FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG2_SAME (FOrdEqual , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [3/6]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG2_SAME (FOrdGreaterThan , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [4/6]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG2_SAME (FOrdLessThan , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [5/6]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG2_SAME (FOrdNotEqual , __FUNC_PREFIX_CORE)
__SYCL_MAKE_CALL_ARG2_SAME() [6/6]
__FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE __FUNC_PREFIX_CORE cl::__host_std::__SYCL_MAKE_CALL_ARG2_SAME (Ordered , __FUNC_PREFIX_CORE)
acos() [1/3]
s::cl_double cl::__host_std::acos (s::cl_double x)
Definition at line 96 of file builtins_math.cpp.
References acos().
acos() [2/3]
s::cl_float cl::__host_std::acos (s::cl_float x)
Definition at line 95 of file builtins_math.cpp.
References acos().
acos() [3/3]
s::cl_half cl::__host_std::acos (s::cl_half x)
Definition at line 97 of file builtins_math.cpp.
Referenced by acos().
acosh() [1/3]
s::cl_double cl::__host_std::acosh (s::cl_double x)
Definition at line 104 of file builtins_math.cpp.
References acosh().
acosh() [2/3]
s::cl_float cl::__host_std::acosh (s::cl_float x)
Definition at line 103 of file builtins_math.cpp.
References acosh().
acosh() [3/3]
s::cl_half cl::__host_std::acosh (s::cl_half x)
Definition at line 107 of file builtins_math.cpp.
Referenced by acosh().
acospi() [1/3]
s::cl_double cl::__host_std::acospi (s::cl_double x)
Definition at line 114 of file builtins_math.cpp.
acospi() [2/3]
s::cl_float cl::__host_std::acospi (s::cl_float x)
Definition at line 113 of file builtins_math.cpp.
acospi() [3/3]
s::cl_half cl::__host_std::acospi (s::cl_half x)
Definition at line 117 of file builtins_math.cpp.
All() [1/4]
s::cl_int cl::__host_std::All (s::cl_int2)
All() [2/4]
s::cl_int cl::__host_std::All (s::cl_int3)
All() [3/4]
s::cl_int cl::__host_std::All (s::cl_int4)
All() [4/4]
s::cl_int cl::__host_std::All (s::vec< int, 1 >)
asin() [1/3]
s::cl_double cl::__host_std::asin (s::cl_double x)
Definition at line 124 of file builtins_math.cpp.
References asin().
asin() [2/3]
s::cl_float cl::__host_std::asin (s::cl_float x)
Definition at line 123 of file builtins_math.cpp.
References asin().
asin() [3/3]
s::cl_half cl::__host_std::asin (s::cl_half x)
Definition at line 125 of file builtins_math.cpp.
Referenced by asin().
asinh() [1/3]
s::cl_double cl::__host_std::asinh (s::cl_double x)
Definition at line 132 of file builtins_math.cpp.
References asinh().
asinh() [2/3]
s::cl_float cl::__host_std::asinh (s::cl_float x)
Definition at line 131 of file builtins_math.cpp.
References asinh().
asinh() [3/3]
s::cl_half cl::__host_std::asinh (s::cl_half x)
Definition at line 135 of file builtins_math.cpp.
Referenced by asinh().
asinpi() [1/3]
s::cl_double cl::__host_std::asinpi (s::cl_double x)
Definition at line 142 of file builtins_math.cpp.
asinpi() [2/3]
s::cl_float cl::__host_std::asinpi (s::cl_float x)
Definition at line 141 of file builtins_math.cpp.
asinpi() [3/3]
s::cl_half cl::__host_std::asinpi (s::cl_half x)
Definition at line 145 of file builtins_math.cpp.
atan() [1/3]
s::cl_double cl::__host_std::atan (s::cl_double x)
Definition at line 152 of file builtins_math.cpp.
References atan().
atan() [2/3]
s::cl_float cl::__host_std::atan (s::cl_float x)
Definition at line 151 of file builtins_math.cpp.
References atan().
atan() [3/3]
s::cl_half cl::__host_std::atan (s::cl_half x)
Definition at line 153 of file builtins_math.cpp.
Referenced by atan().
atan2() [1/3]
s::cl_double cl::__host_std::atan2 (s::cl_double x, s::cl_double y)
Definition at line 162 of file builtins_math.cpp.
References atan2().
atan2() [2/3]
s::cl_float cl::__host_std::atan2 (s::cl_float x, s::cl_float y)
Definition at line 159 of file builtins_math.cpp.
References atan2().
atan2() [3/3]
s::cl_half cl::__host_std::atan2 (s::cl_half x, s::cl_half y)
Definition at line 165 of file builtins_math.cpp.
Referenced by atan2().
atan2pi() [1/3]
s::cl_double cl::__host_std::atan2pi (s::cl_double x, s::cl_double y)
Definition at line 196 of file builtins_math.cpp.
atan2pi() [2/3]
s::cl_float cl::__host_std::atan2pi (s::cl_float x, s::cl_float y)
Definition at line 193 of file builtins_math.cpp.
atan2pi() [3/3]
s::cl_half cl::__host_std::atan2pi (s::cl_half x, s::cl_half y)
Definition at line 199 of file builtins_math.cpp.
atanh() [1/3]
s::cl_double cl::__host_std::atanh (s::cl_double x)
Definition at line 174 of file builtins_math.cpp.
References atanh().
atanh() [2/3]
s::cl_float cl::__host_std::atanh (s::cl_float x)
Definition at line 173 of file builtins_math.cpp.
References atanh().
atanh() [3/3]
s::cl_half cl::__host_std::atanh (s::cl_half x)
Definition at line 177 of file builtins_math.cpp.
Referenced by atanh().
atanpi() [1/3]
s::cl_double cl::__host_std::atanpi (s::cl_double x)
Definition at line 184 of file builtins_math.cpp.
atanpi() [2/3]
s::cl_float cl::__host_std::atanpi (s::cl_float x)
Definition at line 183 of file builtins_math.cpp.
atanpi() [3/3]
s::cl_half cl::__host_std::atanpi (s::cl_half x)
Definition at line 187 of file builtins_math.cpp.
cbrt() [1/3]
s::cl_double cl::__host_std::cbrt (s::cl_double x)
Definition at line 208 of file builtins_math.cpp.
References cbrt().
cbrt() [2/3]
s::cl_float cl::__host_std::cbrt (s::cl_float x)
Definition at line 207 of file builtins_math.cpp.
References cbrt().
cbrt() [3/3]
s::cl_half cl::__host_std::cbrt (s::cl_half x)
Definition at line 209 of file builtins_math.cpp.
Referenced by cbrt().
ceil() [1/3]
s::cl_double cl::__host_std::ceil (s::cl_double x)
Definition at line 216 of file builtins_math.cpp.
References ceil().
ceil() [2/3]
s::cl_float cl::__host_std::ceil (s::cl_float x)
Definition at line 215 of file builtins_math.cpp.
References ceil().
ceil() [3/3]
s::cl_half cl::__host_std::ceil (s::cl_half x)
Definition at line 217 of file builtins_math.cpp.
Referenced by ceil().
clz() [1/8]
s::cl_char cl::__host_std::clz (s::cl_char x)
Definition at line 459 of file builtins_integer.cpp.
clz() [2/8]
s::cl_int cl::__host_std::clz (s::cl_int x)
Definition at line 463 of file builtins_integer.cpp.
clz() [3/8]
s::cl_long cl::__host_std::clz (s::cl_long x)
Definition at line 465 of file builtins_integer.cpp.
clz() [4/8]
s::cl_short cl::__host_std::clz (s::cl_short x)
Definition at line 461 of file builtins_integer.cpp.
clz() [5/8]
s::cl_uchar cl::__host_std::clz (s::cl_uchar x)
Definition at line 458 of file builtins_integer.cpp.
clz() [6/8]
s::cl_uint cl::__host_std::clz (s::cl_uint x)
Definition at line 462 of file builtins_integer.cpp.
clz() [7/8]
s::cl_ulong cl::__host_std::clz (s::cl_ulong x)
Definition at line 464 of file builtins_integer.cpp.
clz() [8/8]
s::cl_ushort cl::__host_std::clz (s::cl_ushort x)
Definition at line 460 of file builtins_integer.cpp.
copysign() [1/3]
s::cl_double cl::__host_std::copysign (s::cl_double x, s::cl_double y)
Definition at line 226 of file builtins_math.cpp.
References copysign().
copysign() [2/3]
s::cl_float cl::__host_std::copysign (s::cl_float x, s::cl_float y)
Definition at line 223 of file builtins_math.cpp.
References copysign().
copysign() [3/3]
s::cl_half cl::__host_std::copysign (s::cl_half x, s::cl_half y)
Definition at line 229 of file builtins_math.cpp.
Referenced by copysign().
cos() [1/3]
s::cl_double cl::__host_std::cos (s::cl_double x)
Definition at line 238 of file builtins_math.cpp.
References cos().
cos() [2/3]
s::cl_float cl::__host_std::cos (s::cl_float x)
Definition at line 237 of file builtins_math.cpp.
References cos().
cos() [3/3]
s::cl_half cl::__host_std::cos (s::cl_half x)
Definition at line 239 of file builtins_math.cpp.
Referenced by cos(), half_cos(), and native_cos().
cosh() [1/3]
s::cl_double cl::__host_std::cosh (s::cl_double x)
Definition at line 246 of file builtins_math.cpp.
References cosh().
cosh() [2/3]
s::cl_float cl::__host_std::cosh (s::cl_float x)
Definition at line 245 of file builtins_math.cpp.
References cosh().
cosh() [3/3]
s::cl_half cl::__host_std::cosh (s::cl_half x)
Definition at line 247 of file builtins_math.cpp.
Referenced by cosh().
cospi() [1/3]
s::cl_double cl::__host_std::cospi (s::cl_double x)
Definition at line 254 of file builtins_math.cpp.
cospi() [2/3]
s::cl_float cl::__host_std::cospi (s::cl_float x)
Definition at line 253 of file builtins_math.cpp.
cospi() [3/3]
s::cl_half cl::__host_std::cospi (s::cl_half x)
Definition at line 255 of file builtins_math.cpp.
cross() [1/6]
s::cl_double3 cl::__host_std::cross (s::cl_double3 p0, s::cl_double3 p1)
Definition at line 120 of file builtins_geometric.cpp.
cross() [2/6]
s::cl_double4 cl::__host_std::cross (s::cl_double4 p0, s::cl_double4 p1)
Definition at line 123 of file builtins_geometric.cpp.
cross() [3/6]
s::cl_float3 cl::__host_std::cross (s::cl_float3 p0, s::cl_float3 p1)
Definition at line 114 of file builtins_geometric.cpp.
cross() [4/6]
s::cl_float4 cl::__host_std::cross (s::cl_float4 p0, s::cl_float4 p1)
Definition at line 117 of file builtins_geometric.cpp.
cross() [5/6]
s::cl_half3 cl::__host_std::cross (s::cl_half3 p0, s::cl_half3 p1)
Definition at line 126 of file builtins_geometric.cpp.
cross() [6/6]
s::cl_half4 cl::__host_std::cross (s::cl_half4 p0, s::cl_half4 p1)
Definition at line 129 of file builtins_geometric.cpp.
ctz() [1/8]
s::cl_char cl::__host_std::ctz (s::cl_char x)
Definition at line 477 of file builtins_integer.cpp.
ctz() [2/8]
s::cl_int cl::__host_std::ctz (s::cl_int x)
Definition at line 481 of file builtins_integer.cpp.
ctz() [3/8]
s::cl_long cl::__host_std::ctz (s::cl_long x)
Definition at line 483 of file builtins_integer.cpp.
ctz() [4/8]
s::cl_short cl::__host_std::ctz (s::cl_short x)
Definition at line 479 of file builtins_integer.cpp.
ctz() [5/8]
s::cl_uchar cl::__host_std::ctz (s::cl_uchar x)
Definition at line 476 of file builtins_integer.cpp.
ctz() [6/8]
s::cl_uint cl::__host_std::ctz (s::cl_uint x)
Definition at line 480 of file builtins_integer.cpp.
ctz() [7/8]
s::cl_ulong cl::__host_std::ctz (s::cl_ulong x)
Definition at line 482 of file builtins_integer.cpp.
ctz() [8/8]
s::cl_ushort cl::__host_std::ctz (s::cl_ushort x)
Definition at line 478 of file builtins_integer.cpp.
degrees() [1/3]
s::cl_double cl::__host_std::degrees (s::cl_double radians)
Definition at line 89 of file builtins_common.cpp.
References radians().
degrees() [2/3]
s::cl_float cl::__host_std::degrees (s::cl_float radians)
Definition at line 86 of file builtins_common.cpp.
References radians().
degrees() [3/3]
s::cl_half cl::__host_std::degrees (s::cl_half radians)
Definition at line 92 of file builtins_common.cpp.
References radians().
Referenced by radians().
distance() [1/15]
s::cl_double cl::__host_std::distance (s::cl_double p0, s::cl_double p1)
Definition at line 182 of file builtins_geometric.cpp.
References length().
distance() [2/15]
s::cl_double cl::__host_std::distance (s::cl_double2 p0, s::cl_double2 p1)
Definition at line 188 of file builtins_geometric.cpp.
References length().
distance() [3/15]
s::cl_double cl::__host_std::distance (s::cl_double3 p0, s::cl_double3 p1)
Definition at line 191 of file builtins_geometric.cpp.
References length().
distance() [4/15]
s::cl_double cl::__host_std::distance (s::cl_double4 p0, s::cl_double4 p1)
Definition at line 194 of file builtins_geometric.cpp.
References length().
distance() [5/15]
s::cl_float cl::__host_std::distance (s::cl_float p0, s::cl_float p1)
Definition at line 167 of file builtins_geometric.cpp.
References length().
distance() [6/15]
s::cl_float cl::__host_std::distance (s::cl_float2 p0, s::cl_float2 p1)
Definition at line 173 of file builtins_geometric.cpp.
References length().
distance() [7/15]
s::cl_float cl::__host_std::distance (s::cl_float3 p0, s::cl_float3 p1)
Definition at line 176 of file builtins_geometric.cpp.
References length().
distance() [8/15]
s::cl_float cl::__host_std::distance (s::cl_float4 p0, s::cl_float4 p1)
Definition at line 179 of file builtins_geometric.cpp.
References length().
distance() [9/15]
s::cl_half cl::__host_std::distance (s::cl_half p0, s::cl_half p1)
Definition at line 197 of file builtins_geometric.cpp.
References length().
distance() [10/15]
s::cl_half cl::__host_std::distance (s::cl_half2 p0, s::cl_half2 p1)
Definition at line 204 of file builtins_geometric.cpp.
References length().
distance() [11/15]
s::cl_half cl::__host_std::distance (s::cl_half3 p0, s::cl_half3 p1)
Definition at line 207 of file builtins_geometric.cpp.
References length().
distance() [12/15]
s::cl_half cl::__host_std::distance (s::cl_half4 p0, s::cl_half4 p1)
Definition at line 210 of file builtins_geometric.cpp.
References length().
distance() [13/15]
s::cl_float cl::__host_std::distance (s::vec< double, 1 > p0, s::vec< double, 1 > p1)
Definition at line 185 of file builtins_geometric.cpp.
References length().
distance() [14/15]
s::cl_float cl::__host_std::distance (s::vec< float, 1 > p0, s::vec< float, 1 > p1)
Definition at line 170 of file builtins_geometric.cpp.
References length().
distance() [15/15]
s::cl_float cl::__host_std::distance (s::vec< s::half, 1 > p0, s::vec< s::half, 1 > p1)
Definition at line 200 of file builtins_geometric.cpp.
References length().
Dot() [1/11]
s::cl_double cl::__host_std::Dot (s::cl_double2 , s::cl_double2)
Dot() [2/11]
s::cl_double cl::__host_std::Dot (s::cl_double3 , s::cl_double3)
Dot() [3/11]
s::cl_double cl::__host_std::Dot (s::cl_double4 , s::cl_double4)
Dot() [4/11]
s::cl_float cl::__host_std::Dot (s::cl_float2 , s::cl_float2)
Dot() [5/11]
s::cl_float cl::__host_std::Dot (s::cl_float3 , s::cl_float3)
Dot() [6/11]
s::cl_float cl::__host_std::Dot (s::cl_float4 , s::cl_float4)
Dot() [7/11]
s::cl_half cl::__host_std::Dot (s::cl_half2 , s::cl_half2)
Dot() [8/11]
s::cl_half cl::__host_std::Dot (s::cl_half3 , s::cl_half3)
Dot() [9/11]
s::cl_half cl::__host_std::Dot (s::cl_half4 , s::cl_half4)
Dot() [10/11]
s::cl_double cl::__host_std::Dot (s::vec< double, 1 > , s::vec< double, 1 >)
Dot() [11/11]
s::cl_float cl::__host_std::Dot (s::vec< float, 1 > , s::vec< float, 1 >)
erf() [1/3]
s::cl_double cl::__host_std::erf (s::cl_double x)
Definition at line 270 of file builtins_math.cpp.
References erf().
erf() [2/3]
s::cl_float cl::__host_std::erf (s::cl_float x)
Definition at line 269 of file builtins_math.cpp.
References erf().
erf() [3/3]
s::cl_half cl::__host_std::erf (s::cl_half x)
Definition at line 271 of file builtins_math.cpp.
Referenced by erf().
erfc() [1/3]
s::cl_double cl::__host_std::erfc (s::cl_double x)
Definition at line 262 of file builtins_math.cpp.
References erfc().
erfc() [2/3]
s::cl_float cl::__host_std::erfc (s::cl_float x)
Definition at line 261 of file builtins_math.cpp.
References erfc().
erfc() [3/3]
s::cl_half cl::__host_std::erfc (s::cl_half x)
Definition at line 263 of file builtins_math.cpp.
Referenced by erfc().
exp() [1/3]
s::cl_double cl::__host_std::exp (s::cl_double x)
Definition at line 278 of file builtins_math.cpp.
References exp().
exp() [2/3]
s::cl_float cl::__host_std::exp (s::cl_float x)
Definition at line 277 of file builtins_math.cpp.
References exp().
exp() [3/3]
s::cl_half cl::__host_std::exp (s::cl_half x)
Definition at line 279 of file builtins_math.cpp.
Referenced by exp(), frexp(), half_exp(), and native_exp().
exp10() [1/3]
s::cl_double cl::__host_std::exp10 (s::cl_double x)
Definition at line 296 of file builtins_math.cpp.
References pow().
exp10() [2/3]
s::cl_float cl::__host_std::exp10 (s::cl_float x)
Definition at line 293 of file builtins_math.cpp.
References pow().
exp10() [3/3]
s::cl_half cl::__host_std::exp10 (s::cl_half x)
Definition at line 299 of file builtins_math.cpp.
References pow().
exp2() [1/3]
s::cl_double cl::__host_std::exp2 (s::cl_double x)
Definition at line 286 of file builtins_math.cpp.
References exp2().
exp2() [2/3]
s::cl_float cl::__host_std::exp2 (s::cl_float x)
Definition at line 285 of file builtins_math.cpp.
References exp2().
exp2() [3/3]
s::cl_half cl::__host_std::exp2 (s::cl_half x)
Definition at line 287 of file builtins_math.cpp.
Referenced by exp2(), half_exp2(), and native_exp2().
expm1() [1/3]
s::cl_double cl::__host_std::expm1 (s::cl_double x)
Definition at line 306 of file builtins_math.cpp.
References expm1().
expm1() [2/3]
s::cl_float cl::__host_std::expm1 (s::cl_float x)
Definition at line 305 of file builtins_math.cpp.
References expm1().
expm1() [3/3]
s::cl_half cl::__host_std::expm1 (s::cl_half x)
Definition at line 309 of file builtins_math.cpp.
Referenced by expm1().
fabs() [1/3]
s::cl_double cl::__host_std::fabs (s::cl_double x)
Definition at line 316 of file builtins_math.cpp.
References fabs().
fabs() [2/3]
s::cl_float cl::__host_std::fabs (s::cl_float x)
Definition at line 315 of file builtins_math.cpp.
References fabs().
fabs() [3/3]
s::cl_half cl::__host_std::fabs (s::cl_half x)
Definition at line 317 of file builtins_math.cpp.
Referenced by fabs().
fast_distance() [1/5]
s::cl_float cl::__host_std::fast_distance (s::cl_float p0, s::cl_float p1)
Definition at line 278 of file builtins_geometric.cpp.
References fast_length().
fast_distance() [2/5]
s::cl_float cl::__host_std::fast_distance (s::cl_float2 p0, s::cl_float2 p1)
Definition at line 285 of file builtins_geometric.cpp.
References fast_length().
fast_distance() [3/5]
s::cl_float cl::__host_std::fast_distance (s::cl_float3 p0, s::cl_float3 p1)
Definition at line 288 of file builtins_geometric.cpp.
References fast_length().
fast_distance() [4/5]
s::cl_float cl::__host_std::fast_distance (s::cl_float4 p0, s::cl_float4 p1)
Definition at line 291 of file builtins_geometric.cpp.
References fast_length().
fast_distance() [5/5]
s::cl_float cl::__host_std::fast_distance (s::vec< float, 1 > p0, s::vec< float, 1 > p1)
Definition at line 281 of file builtins_geometric.cpp.
References fast_length().
fast_length() [1/5]
s::cl_float cl::__host_std::fast_length (s::cl_float p)
Definition at line 241 of file builtins_geometric.cpp.
fast_length() [2/5]
s::cl_float cl::__host_std::fast_length (s::cl_float2 p)
Definition at line 247 of file builtins_geometric.cpp.
fast_length() [3/5]
s::cl_float cl::__host_std::fast_length (s::cl_float3 p)
Definition at line 250 of file builtins_geometric.cpp.
fast_length() [4/5]
s::cl_float cl::__host_std::fast_length (s::cl_float4 p)
Definition at line 253 of file builtins_geometric.cpp.
Referenced by fast_distance().
fast_length() [5/5]
s::cl_float cl::__host_std::fast_length (s::vec< float, 1 > p)
Definition at line 244 of file builtins_geometric.cpp.
fast_normalize() [1/5]
s::cl_float cl::__host_std::fast_normalize (s::cl_float p)
Definition at line 258 of file builtins_geometric.cpp.
References FMul(), and cl::sycl::sqrt().
fast_normalize() [2/5]
s::cl_float2 cl::__host_std::fast_normalize (s::cl_float2 p)
Definition at line 267 of file builtins_geometric.cpp.
fast_normalize() [3/5]
s::cl_float3 cl::__host_std::fast_normalize (s::cl_float3 p)
Definition at line 270 of file builtins_geometric.cpp.
fast_normalize() [4/5]
s::cl_float4 cl::__host_std::fast_normalize (s::cl_float4 p)
Definition at line 273 of file builtins_geometric.cpp.
fast_normalize() [5/5]
s::cl_float cl::__host_std::fast_normalize (s::vec< float, 1 > p)
Definition at line 264 of file builtins_geometric.cpp.
fclamp() [1/3]
s::cl_double cl::__host_std::fclamp (s::cl_double x, s::cl_double minval, s::cl_double maxval)
Definition at line 73 of file builtins_common.cpp.
fclamp() [2/3]
s::cl_float cl::__host_std::fclamp (s::cl_float x, s::cl_float minval, s::cl_float maxval)
Definition at line 69 of file builtins_common.cpp.
fclamp() [3/3]
s::cl_half cl::__host_std::fclamp (s::cl_half x, s::cl_half minval, s::cl_half maxval)
Definition at line 77 of file builtins_common.cpp.
fdim() [1/3]
s::cl_double cl::__host_std::fdim (s::cl_double x, s::cl_double y)
Definition at line 326 of file builtins_math.cpp.
References fdim().
fdim() [2/3]
s::cl_float cl::__host_std::fdim (s::cl_float x, s::cl_float y)
Definition at line 323 of file builtins_math.cpp.
References fdim().
fdim() [3/3]
s::cl_half cl::__host_std::fdim (s::cl_half x, s::cl_half y)
Definition at line 329 of file builtins_math.cpp.
Referenced by fdim().
floor() [1/3]
s::cl_double cl::__host_std::floor (s::cl_double x)
Definition at line 338 of file builtins_math.cpp.
References floor().
floor() [2/3]
s::cl_float cl::__host_std::floor (s::cl_float x)
Definition at line 337 of file builtins_math.cpp.
References floor().
floor() [3/3]
s::cl_half cl::__host_std::floor (s::cl_half x)
Definition at line 341 of file builtins_math.cpp.
Referenced by floor().
fma() [1/3]
s::cl_double cl::__host_std::fma (s::cl_double a, s::cl_double b, s::cl_double c)
Definition at line 351 of file builtins_math.cpp.
fma() [2/3]
s::cl_float cl::__host_std::fma (s::cl_float a, s::cl_float b, s::cl_float c)
Definition at line 347 of file builtins_math.cpp.
fma() [3/3]
s::cl_half cl::__host_std::fma (s::cl_half a, s::cl_half b, s::cl_half c)
Definition at line 355 of file builtins_math.cpp.
fmax() [1/3]
s::cl_double cl::__host_std::fmax (s::cl_double x, s::cl_double y)
Definition at line 366 of file builtins_math.cpp.
fmax() [2/3]
s::cl_float cl::__host_std::fmax (s::cl_float x, s::cl_float y)
Definition at line 363 of file builtins_math.cpp.
fmax() [3/3]
s::cl_half cl::__host_std::fmax (s::cl_half x, s::cl_half y)
Definition at line 369 of file builtins_math.cpp.
fmax_common() [1/3]
s::cl_double cl::__host_std::fmax_common (s::cl_double x, s::cl_double y)
Definition at line 117 of file builtins_common.cpp.
fmax_common() [2/3]
s::cl_float cl::__host_std::fmax_common (s::cl_float x, s::cl_float y)
Definition at line 114 of file builtins_common.cpp.
fmax_common() [3/3]
s::cl_half cl::__host_std::fmax_common (s::cl_half x, s::cl_half y)
Definition at line 120 of file builtins_common.cpp.
fmin() [1/3]
s::cl_double cl::__host_std::fmin (s::cl_double x, s::cl_double y)
Definition at line 380 of file builtins_math.cpp.
fmin() [2/3]
s::cl_float cl::__host_std::fmin (s::cl_float x, s::cl_float y)
Definition at line 377 of file builtins_math.cpp.
fmin() [3/3]
s::cl_half cl::__host_std::fmin (s::cl_half x, s::cl_half y)
Definition at line 383 of file builtins_math.cpp.
fmin_common() [1/3]
s::cl_double cl::__host_std::fmin_common (s::cl_double x, s::cl_double y)
Definition at line 103 of file builtins_common.cpp.
fmin_common() [2/3]
s::cl_float cl::__host_std::fmin_common (s::cl_float x, s::cl_float y)
Definition at line 100 of file builtins_common.cpp.
fmin_common() [3/3]
s::cl_half cl::__host_std::fmin_common (s::cl_half x, s::cl_half y)
Definition at line 106 of file builtins_common.cpp.
fmod() [1/3]
s::cl_double cl::__host_std::fmod (s::cl_double x, s::cl_double y)
Definition at line 394 of file builtins_math.cpp.
References fmod().
fmod() [2/3]
s::cl_float cl::__host_std::fmod (s::cl_float x, s::cl_float y)
Definition at line 391 of file builtins_math.cpp.
References fmod().
fmod() [3/3]
s::cl_half cl::__host_std::fmod (s::cl_half x, s::cl_half y)
Definition at line 397 of file builtins_math.cpp.
Referenced by fmod().
FMul() [1/3]
s::cl_double cl::__host_std::FMul (s::cl_double p0, s::cl_double p1)
Definition at line 137 of file builtins_geometric.cpp.
FMul() [2/3]
s::cl_float cl::__host_std::FMul (s::cl_float p0, s::cl_float p1)
Definition at line 134 of file builtins_geometric.cpp.
FMul() [3/3]
s::cl_float cl::__host_std::FMul (s::cl_half p0, s::cl_half p1)
Definition at line 140 of file builtins_geometric.cpp.
Referenced by fast_normalize().
FOrdEqual() [1/3]
s::cl_int cl::__host_std::FOrdEqual (s::cl_double x, s::cl_double y)
Definition at line 147 of file builtins_relational.cpp.
FOrdEqual() [2/3]
s::cl_int cl::__host_std::FOrdEqual (s::cl_float x, s::cl_float y)
Definition at line 144 of file builtins_relational.cpp.
FOrdEqual() [3/3]
s::cl_int cl::__host_std::FOrdEqual (s::cl_half x, s::cl_half y)
Definition at line 150 of file builtins_relational.cpp.
fract() [1/3]
s::cl_double cl::__host_std::fract (s::cl_double x, s::cl_double * iptr)
Definition at line 422 of file builtins_math.cpp.
fract() [2/3]
s::cl_float cl::__host_std::fract (s::cl_float x, s::cl_float * iptr)
Definition at line 419 of file builtins_math.cpp.
fract() [3/3]
s::cl_half cl::__host_std::fract (s::cl_half x, s::cl_half * iptr)
Definition at line 425 of file builtins_math.cpp.
frexp() [1/3]
s::cl_double cl::__host_std::frexp (s::cl_double x, s::cl_int * exp)
Definition at line 436 of file builtins_math.cpp.
References exp(), and frexp().
frexp() [2/3]
s::cl_float cl::__host_std::frexp (s::cl_float x, s::cl_int * exp)
Definition at line 433 of file builtins_math.cpp.
References exp(), and frexp().
frexp() [3/3]
s::cl_half cl::__host_std::frexp (s::cl_half x, s::cl_int * exp)
Definition at line 439 of file builtins_math.cpp.
References exp().
Referenced by frexp().
FUnordNotEqual() [1/3]
s::cl_int cl::__host_std::FUnordNotEqual (s::cl_double x, s::cl_double y)
Definition at line 161 of file builtins_relational.cpp.
FUnordNotEqual() [2/3]
s::cl_int cl::__host_std::FUnordNotEqual (s::cl_float x, s::cl_float y)
Definition at line 158 of file builtins_relational.cpp.
FUnordNotEqual() [3/3]
s::cl_int cl::__host_std::FUnordNotEqual (s::cl_half x, s::cl_half y)
Definition at line 164 of file builtins_relational.cpp.
half_cos()
s::cl_float cl::__host_std::half_cos (s::cl_float x)
Definition at line 920 of file builtins_math.cpp.
References cos().
half_divide()
s::cl_float cl::__host_std::half_divide (s::cl_float x, s::cl_float y)
Definition at line 926 of file builtins_math.cpp.
half_exp()
s::cl_float cl::__host_std::half_exp (s::cl_float x)
Definition at line 932 of file builtins_math.cpp.
References exp().
half_exp10()
s::cl_float cl::__host_std::half_exp10 (s::cl_float x)
Definition at line 943 of file builtins_math.cpp.
References pow().
half_exp2()
s::cl_float cl::__host_std::half_exp2 (s::cl_float x)
Definition at line 937 of file builtins_math.cpp.
References exp2().
half_log()
s::cl_float cl::__host_std::half_log (s::cl_float x)
Definition at line 948 of file builtins_math.cpp.
References log().
half_log10()
s::cl_float cl::__host_std::half_log10 (s::cl_float x)
Definition at line 960 of file builtins_math.cpp.
References log10().
half_log2()
s::cl_float cl::__host_std::half_log2 (s::cl_float x)
Definition at line 954 of file builtins_math.cpp.
References log2().
half_powr()
s::cl_float cl::__host_std::half_powr (s::cl_float x, s::cl_float y)
Definition at line 966 of file builtins_math.cpp.
References pow().
half_recip()
s::cl_float cl::__host_std::half_recip (s::cl_float x)
Definition at line 972 of file builtins_math.cpp.
half_rsqrt()
s::cl_float cl::__host_std::half_rsqrt (s::cl_float x)
Definition at line 976 of file builtins_math.cpp.
References sqrt().
half_sin()
s::cl_float cl::__host_std::half_sin (s::cl_float x)
Definition at line 982 of file builtins_math.cpp.
References sin().
half_sqrt()
s::cl_float cl::__host_std::half_sqrt (s::cl_float x)
Definition at line 988 of file builtins_math.cpp.
References sqrt().
half_tan()
s::cl_float cl::__host_std::half_tan (s::cl_float x)
Definition at line 994 of file builtins_math.cpp.
References tan().
hypot() [1/3]
s::cl_double cl::__host_std::hypot (s::cl_double x, s::cl_double y)
Definition at line 450 of file builtins_math.cpp.
References hypot().
hypot() [2/3]
s::cl_float cl::__host_std::hypot (s::cl_float x, s::cl_float y)
Definition at line 447 of file builtins_math.cpp.
References hypot().
hypot() [3/3]
s::cl_half cl::__host_std::hypot (s::cl_half x, s::cl_half y)
Definition at line 453 of file builtins_math.cpp.
Referenced by hypot().
ilogb() [1/3]
s::cl_int cl::__host_std::ilogb (s::cl_double x)
Definition at line 462 of file builtins_math.cpp.
References ilogb().
ilogb() [2/3]
s::cl_int cl::__host_std::ilogb (s::cl_float x)
Definition at line 461 of file builtins_math.cpp.
References ilogb().
ilogb() [3/3]
s::cl_int cl::__host_std::ilogb (s::cl_half x)
Definition at line 463 of file builtins_math.cpp.
Referenced by ilogb().
ldexp() [1/3]
s::cl_double cl::__host_std::ldexp (s::cl_double x, s::cl_int k)
Definition at line 472 of file builtins_math.cpp.
References ldexp().
ldexp() [2/3]
s::cl_float cl::__host_std::ldexp (s::cl_float x, s::cl_int k)
Definition at line 469 of file builtins_math.cpp.
References ldexp().
ldexp() [3/3]
s::cl_half cl::__host_std::ldexp (s::cl_half x, s::cl_int k)
Definition at line 475 of file builtins_math.cpp.
Referenced by ldexp().
length() [1/15]
s::cl_double cl::__host_std::length (s::cl_double p)
Definition at line 151 of file builtins_geometric.cpp.
length() [2/15]
s::cl_double cl::__host_std::length (s::cl_double2 p)
Definition at line 158 of file builtins_geometric.cpp.
length() [3/15]
s::cl_double cl::__host_std::length (s::cl_double3 p)
Definition at line 159 of file builtins_geometric.cpp.
length() [4/15]
s::cl_double cl::__host_std::length (s::cl_double4 p)
Definition at line 160 of file builtins_geometric.cpp.
length() [5/15]
s::cl_float cl::__host_std::length (s::cl_float p)
Definition at line 150 of file builtins_geometric.cpp.
length() [6/15]
s::cl_float cl::__host_std::length (s::cl_float2 p)
Definition at line 154 of file builtins_geometric.cpp.
length() [7/15]
s::cl_float cl::__host_std::length (s::cl_float3 p)
Definition at line 155 of file builtins_geometric.cpp.
length() [8/15]
s::cl_float cl::__host_std::length (s::cl_float4 p)
Definition at line 156 of file builtins_geometric.cpp.
length() [9/15]
s::cl_half cl::__host_std::length (s::cl_half p)
Definition at line 152 of file builtins_geometric.cpp.
length() [10/15]
s::cl_half cl::__host_std::length (s::cl_half2 p)
Definition at line 162 of file builtins_geometric.cpp.
length() [11/15]
s::cl_half cl::__host_std::length (s::cl_half3 p)
Definition at line 163 of file builtins_geometric.cpp.
length() [12/15]
s::cl_half cl::__host_std::length (s::cl_half4 p)
Definition at line 164 of file builtins_geometric.cpp.
Referenced by distance().
length() [13/15]
s::cl_double cl::__host_std::length (s::vec< double, 1 > p)
Definition at line 157 of file builtins_geometric.cpp.
length() [14/15]
s::cl_float cl::__host_std::length (s::vec< float, 1 > p)
Definition at line 153 of file builtins_geometric.cpp.
length() [15/15]
s::cl_half cl::__host_std::length (s::vec< s::half, 1 > p)
Definition at line 161 of file builtins_geometric.cpp.
lgamma() [1/3]
s::cl_double cl::__host_std::lgamma (s::cl_double x)
Definition at line 486 of file builtins_math.cpp.
References lgamma().
lgamma() [2/3]
s::cl_float cl::__host_std::lgamma (s::cl_float x)
Definition at line 483 of file builtins_math.cpp.
References lgamma().
lgamma() [3/3]
s::cl_half cl::__host_std::lgamma (s::cl_half x)
Definition at line 489 of file builtins_math.cpp.
Referenced by lgamma().
lgamma_r() [1/3]
s::cl_double cl::__host_std::lgamma_r (s::cl_double x, s::cl_int * signp)
Definition at line 498 of file builtins_math.cpp.
lgamma_r() [2/3]
s::cl_float cl::__host_std::lgamma_r (s::cl_float x, s::cl_int * signp)
Definition at line 495 of file builtins_math.cpp.
lgamma_r() [3/3]
s::cl_half cl::__host_std::lgamma_r (s::cl_half x, s::cl_int * signp)
Definition at line 501 of file builtins_math.cpp.
log() [1/3]
s::cl_double cl::__host_std::log (s::cl_double x)
Definition at line 510 of file builtins_math.cpp.
References log().
log() [2/3]
s::cl_float cl::__host_std::log (s::cl_float x)
Definition at line 509 of file builtins_math.cpp.
References log().
log() [3/3]
s::cl_half cl::__host_std::log (s::cl_half x)
Definition at line 511 of file builtins_math.cpp.
Referenced by half_log(), log(), and native_log().
log10() [1/3]
s::cl_double cl::__host_std::log10 (s::cl_double x)
Definition at line 526 of file builtins_math.cpp.
References log10().
log10() [2/3]
s::cl_float cl::__host_std::log10 (s::cl_float x)
Definition at line 525 of file builtins_math.cpp.
References log10().
log10() [3/3]
s::cl_half cl::__host_std::log10 (s::cl_half x)
Definition at line 529 of file builtins_math.cpp.
Referenced by half_log10(), log10(), and native_log10().
log1p() [1/3]
s::cl_double cl::__host_std::log1p (s::cl_double x)
Definition at line 536 of file builtins_math.cpp.
References log1p().
log1p() [2/3]
s::cl_float cl::__host_std::log1p (s::cl_float x)
Definition at line 535 of file builtins_math.cpp.
References log1p().
log1p() [3/3]
s::cl_half cl::__host_std::log1p (s::cl_half x)
Definition at line 539 of file builtins_math.cpp.
Referenced by log1p().
log2() [1/3]
s::cl_double cl::__host_std::log2 (s::cl_double x)
Definition at line 518 of file builtins_math.cpp.
References log2().
log2() [2/3]
s::cl_float cl::__host_std::log2 (s::cl_float x)
Definition at line 517 of file builtins_math.cpp.
References log2().
log2() [3/3]
s::cl_half cl::__host_std::log2 (s::cl_half x)
Definition at line 519 of file builtins_math.cpp.
Referenced by half_log2(), log2(), and native_log2().
logb() [1/3]
s::cl_double cl::__host_std::logb (s::cl_double x)
Definition at line 546 of file builtins_math.cpp.
References logb().
logb() [2/3]
s::cl_float cl::__host_std::logb (s::cl_float x)
Definition at line 545 of file builtins_math.cpp.
References logb().
logb() [3/3]
s::cl_half cl::__host_std::logb (s::cl_half x)
Definition at line 547 of file builtins_math.cpp.
Referenced by logb().
mad() [1/3]
s::cl_double cl::__host_std::mad (s::cl_double a, s::cl_double b, s::cl_double c)
Definition at line 557 of file builtins_math.cpp.
mad() [2/3]
s::cl_float cl::__host_std::mad (s::cl_float a, s::cl_float b, s::cl_float c)
Definition at line 553 of file builtins_math.cpp.
mad() [3/3]
s::cl_half cl::__host_std::mad (s::cl_half a, s::cl_half b, s::cl_half c)
Definition at line 561 of file builtins_math.cpp.
MAKE_1V_2V_FUNC()
cl::__host_std::MAKE_1V_2V_FUNC (FUnordNotEqual , __vFUnordNotEqual , s::cl_int , s::cl_float , s::cl_float)
maxmag() [1/3]
s::cl_double cl::__host_std::maxmag (s::cl_double x, s::cl_double y)
Definition at line 572 of file builtins_math.cpp.
maxmag() [2/3]
s::cl_float cl::__host_std::maxmag (s::cl_float x, s::cl_float y)
Definition at line 569 of file builtins_math.cpp.
maxmag() [3/3]
s::cl_half cl::__host_std::maxmag (s::cl_half x, s::cl_half y)
Definition at line 575 of file builtins_math.cpp.
minmag() [1/3]
s::cl_double cl::__host_std::minmag (s::cl_double x, s::cl_double y)
Definition at line 586 of file builtins_math.cpp.
minmag() [2/3]
s::cl_float cl::__host_std::minmag (s::cl_float x, s::cl_float y)
Definition at line 583 of file builtins_math.cpp.
minmag() [3/3]
s::cl_half cl::__host_std::minmag (s::cl_half x, s::cl_half y)
Definition at line 589 of file builtins_math.cpp.
mix() [1/3]
s::cl_double cl::__host_std::mix (s::cl_double x, s::cl_double y, s::cl_double a)
Definition at line 132 of file builtins_common.cpp.
mix() [2/3]
s::cl_float cl::__host_std::mix (s::cl_float x, s::cl_float y, s::cl_float a)
Definition at line 128 of file builtins_common.cpp.
mix() [3/3]
s::cl_half cl::__host_std::mix (s::cl_half x, s::cl_half y, s::cl_half a)
Definition at line 136 of file builtins_common.cpp.
modf() [1/3]
s::cl_double cl::__host_std::modf (s::cl_double x, s::cl_double * iptr)
Definition at line 600 of file builtins_math.cpp.
References modf().
modf() [2/3]
s::cl_float cl::__host_std::modf (s::cl_float x, s::cl_float * iptr)
Definition at line 597 of file builtins_math.cpp.
References modf().
modf() [3/3]
s::cl_half cl::__host_std::modf (s::cl_half x, s::cl_half * iptr)
Definition at line 603 of file builtins_math.cpp.
Referenced by modf().
nan() [1/3]
s::cl_float cl::__host_std::nan (s::cl_uint nancode)
Definition at line 611 of file builtins_math.cpp.
nan() [2/3]
s::cl_double cl::__host_std::nan (s::cl_ulong nancode)
Definition at line 615 of file builtins_math.cpp.
nan() [3/3]
s::cl_half cl::__host_std::nan (s::cl_ushort nancode)
Definition at line 619 of file builtins_math.cpp.
native_cos()
s::cl_float cl::__host_std::native_cos (s::cl_float x)
Definition at line 835 of file builtins_math.cpp.
References cos().
native_divide()
s::cl_float cl::__host_std::native_divide (s::cl_float x, s::cl_float y)
Definition at line 841 of file builtins_math.cpp.
native_exp()
s::cl_float cl::__host_std::native_exp (s::cl_float x)
Definition at line 847 of file builtins_math.cpp.
References exp().
native_exp10()
s::cl_float cl::__host_std::native_exp10 (s::cl_float x)
Definition at line 859 of file builtins_math.cpp.
References pow().
native_exp2()
s::cl_float cl::__host_std::native_exp2 (s::cl_float x)
Definition at line 853 of file builtins_math.cpp.
References exp2().
native_log()
s::cl_float cl::__host_std::native_log (s::cl_float x)
Definition at line 865 of file builtins_math.cpp.
References log().
native_log10()
s::cl_float cl::__host_std::native_log10 (s::cl_float x)
Definition at line 877 of file builtins_math.cpp.
References log10().
native_log2()
s::cl_float cl::__host_std::native_log2 (s::cl_float x)
Definition at line 871 of file builtins_math.cpp.
References log2().
native_powr()
s::cl_float cl::__host_std::native_powr (s::cl_float x, s::cl_float y)
Definition at line 883 of file builtins_math.cpp.
References pow().
native_recip()
s::cl_float cl::__host_std::native_recip (s::cl_float x)
Definition at line 889 of file builtins_math.cpp.
native_rsqrt()
s::cl_float cl::__host_std::native_rsqrt (s::cl_float x)
Definition at line 895 of file builtins_math.cpp.
References sqrt().
native_sin()
s::cl_float cl::__host_std::native_sin (s::cl_float x)
Definition at line 901 of file builtins_math.cpp.
References sin().
native_sqrt()
s::cl_float cl::__host_std::native_sqrt (s::cl_float x)
Definition at line 907 of file builtins_math.cpp.
References sqrt().
native_tan()
s::cl_float cl::__host_std::native_tan (s::cl_float x)
Definition at line 913 of file builtins_math.cpp.
References tan().
nextafter() [1/3]
s::cl_double cl::__host_std::nextafter (s::cl_double x, s::cl_double y)
Definition at line 408 of file builtins_math.cpp.
References nextafter().
nextafter() [2/3]
s::cl_float cl::__host_std::nextafter (s::cl_float x, s::cl_float y)
Definition at line 405 of file builtins_math.cpp.
References nextafter().
nextafter() [3/3]
s::cl_half cl::__host_std::nextafter (s::cl_half x, s::cl_half y)
Definition at line 411 of file builtins_math.cpp.
Referenced by nextafter().
normalize() [1/14]
s::cl_double cl::__host_std::normalize (s::cl_double p)
Definition at line 222 of file builtins_geometric.cpp.
normalize() [2/14]
s::cl_double2 cl::__host_std::normalize (s::cl_double2 p)
Definition at line 226 of file builtins_geometric.cpp.
normalize() [3/14]
s::cl_double3 cl::__host_std::normalize (s::cl_double3 p)
Definition at line 229 of file builtins_geometric.cpp.
normalize() [4/14]
s::cl_double4 cl::__host_std::normalize (s::cl_double4 p)
Definition at line 232 of file builtins_geometric.cpp.
normalize() [5/14]
s::cl_float cl::__host_std::normalize (s::cl_float p)
Definition at line 215 of file builtins_geometric.cpp.
normalize() [6/14]
s::cl_float2 cl::__host_std::normalize (s::cl_float2 p)
Definition at line 219 of file builtins_geometric.cpp.
normalize() [7/14]
s::cl_float3 cl::__host_std::normalize (s::cl_float3 p)
Definition at line 220 of file builtins_geometric.cpp.
normalize() [8/14]
s::cl_float4 cl::__host_std::normalize (s::cl_float4 p)
Definition at line 221 of file builtins_geometric.cpp.
normalize() [9/14]
s::cl_half cl::__host_std::normalize (s::cl_half p)
Definition at line 235 of file builtins_geometric.cpp.
normalize() [10/14]
s::cl_half2 cl::__host_std::normalize (s::cl_half2 p)
Definition at line 236 of file builtins_geometric.cpp.
normalize() [11/14]
s::cl_half3 cl::__host_std::normalize (s::cl_half3 p)
Definition at line 237 of file builtins_geometric.cpp.
normalize() [12/14]
s::cl_half4 cl::__host_std::normalize (s::cl_half4 p)
Definition at line 238 of file builtins_geometric.cpp.
normalize() [13/14]
s::cl_double cl::__host_std::normalize (s::vec< double, 1 > p)
Definition at line 223 of file builtins_geometric.cpp.
normalize() [14/14]
s::cl_float cl::__host_std::normalize (s::vec< float, 1 > p)
Definition at line 216 of file builtins_geometric.cpp.
popcount() [1/8]
s::cl_char cl::__host_std::popcount (s::cl_char x)
Definition at line 820 of file builtins_integer.cpp.
popcount() [2/8]
s::cl_int cl::__host_std::popcount (s::cl_int x)
Definition at line 826 of file builtins_integer.cpp.
popcount() [3/8]
s::cl_long cl::__host_std::popcount (s::cl_long x)
Definition at line 827 of file builtins_integer.cpp.
popcount() [4/8]
s::cl_short cl::__host_std::popcount (s::cl_short x)
Definition at line 823 of file builtins_integer.cpp.
popcount() [5/8]
s::cl_uchar cl::__host_std::popcount (s::cl_uchar x)
Definition at line 803 of file builtins_integer.cpp.
popcount() [6/8]
s::cl_uint cl::__host_std::popcount (s::cl_uint x)
Definition at line 809 of file builtins_integer.cpp.
popcount() [7/8]
s::cl_ulong cl::__host_std::popcount (s::cl_ulong x)
Definition at line 812 of file builtins_integer.cpp.
popcount() [8/8]
s::cl_ushort cl::__host_std::popcount (s::cl_ushort x)
Definition at line 806 of file builtins_integer.cpp.
pow() [1/3]
s::cl_double cl::__host_std::pow (s::cl_double x, s::cl_double y)
Definition at line 631 of file builtins_math.cpp.
References pow().
pow() [2/3]
s::cl_float cl::__host_std::pow (s::cl_float x, s::cl_float y)
Definition at line 628 of file builtins_math.cpp.
References pow().
pow() [3/3]
s::cl_half cl::__host_std::pow (s::cl_half x, s::cl_half y)
Definition at line 634 of file builtins_math.cpp.
Referenced by exp10(), half_exp10(), half_powr(), native_exp10(), native_powr(), pow(), and pown().
pown() [1/3]
s::cl_double cl::__host_std::pown (s::cl_double x, s::cl_int y)
Definition at line 645 of file builtins_math.cpp.
References pow().
pown() [2/3]
s::cl_float cl::__host_std::pown (s::cl_float x, s::cl_int y)
Definition at line 642 of file builtins_math.cpp.
References pow().
pown() [3/3]
s::cl_half cl::__host_std::pown (s::cl_half x, s::cl_int y)
Definition at line 648 of file builtins_math.cpp.
References pow().
powr() [1/3]
s::cl_double cl::__host_std::powr (s::cl_double x, s::cl_double y)
Definition at line 659 of file builtins_math.cpp.
powr() [2/3]
s::cl_float cl::__host_std::powr (s::cl_float x, s::cl_float y)
Definition at line 656 of file builtins_math.cpp.
powr() [3/3]
s::cl_half cl::__host_std::powr (s::cl_half x, s::cl_half y)
Definition at line 662 of file builtins_math.cpp.
radians() [1/3]
s::cl_double cl::__host_std::radians (s::cl_double degrees)
Definition at line 147 of file builtins_common.cpp.
References degrees().
radians() [2/3]
s::cl_float cl::__host_std::radians (s::cl_float degrees)
Definition at line 144 of file builtins_common.cpp.
References degrees().
radians() [3/3]
s::cl_half cl::__host_std::radians (s::cl_half degrees)
Definition at line 150 of file builtins_common.cpp.
References degrees().
Referenced by degrees().
remainder() [1/3]
s::cl_double cl::__host_std::remainder (s::cl_double x, s::cl_double y)
Definition at line 673 of file builtins_math.cpp.
References remainder().
remainder() [2/3]
s::cl_float cl::__host_std::remainder (s::cl_float x, s::cl_float y)
Definition at line 670 of file builtins_math.cpp.
References remainder().
remainder() [3/3]
s::cl_half cl::__host_std::remainder (s::cl_half x, s::cl_half y)
Definition at line 676 of file builtins_math.cpp.
Referenced by remainder().
remquo() [1/3]
s::cl_double cl::__host_std::remquo (s::cl_double x, s::cl_double y, s::cl_int * quo)
Definition at line 688 of file builtins_math.cpp.
References remquo().
remquo() [2/3]
s::cl_float cl::__host_std::remquo (s::cl_float x, s::cl_float y, s::cl_int * quo)
Definition at line 684 of file builtins_math.cpp.
References remquo().
remquo() [3/3]
s::cl_half cl::__host_std::remquo (s::cl_half x, s::cl_half y, s::cl_int * quo)
Definition at line 692 of file builtins_math.cpp.
Referenced by remquo().
rint() [1/3]
s::cl_double cl::__host_std::rint (s::cl_double x)
Definition at line 702 of file builtins_math.cpp.
References rint().
rint() [2/3]
s::cl_float cl::__host_std::rint (s::cl_float x)
Definition at line 701 of file builtins_math.cpp.
References rint().
rint() [3/3]
s::cl_half cl::__host_std::rint (s::cl_half x)
Definition at line 703 of file builtins_math.cpp.
Referenced by rint().
rootn() [1/3]
s::cl_double cl::__host_std::rootn (s::cl_double x, s::cl_int y)
Definition at line 712 of file builtins_math.cpp.
rootn() [2/3]
s::cl_float cl::__host_std::rootn (s::cl_float x, s::cl_int y)
Definition at line 709 of file builtins_math.cpp.
rootn() [3/3]
s::cl_half cl::__host_std::rootn (s::cl_half x, s::cl_int y)
Definition at line 715 of file builtins_math.cpp.
rotate() [1/8]
s::cl_char cl::__host_std::rotate (s::cl_char x, s::cl_char y)
Definition at line 718 of file builtins_integer.cpp.
rotate() [2/8]
s::cl_int cl::__host_std::rotate (s::cl_int x, s::cl_int y)
Definition at line 724 of file builtins_integer.cpp.
rotate() [3/8]
s::cl_long cl::__host_std::rotate (s::cl_long x, s::cl_long y)
Definition at line 727 of file builtins_integer.cpp.
rotate() [4/8]
s::cl_short cl::__host_std::rotate (s::cl_short x, s::cl_short y)
Definition at line 721 of file builtins_integer.cpp.
rotate() [5/8]
s::cl_uchar cl::__host_std::rotate (s::cl_uchar x, s::cl_uchar y)
Definition at line 706 of file builtins_integer.cpp.
rotate() [6/8]
s::cl_uint cl::__host_std::rotate (s::cl_uint x, s::cl_uint y)
Definition at line 712 of file builtins_integer.cpp.
rotate() [7/8]
s::cl_ulong cl::__host_std::rotate (s::cl_ulong x, s::cl_ulong y)
Definition at line 715 of file builtins_integer.cpp.
rotate() [8/8]
s::cl_ushort cl::__host_std::rotate (s::cl_ushort x, s::cl_ushort y)
Definition at line 709 of file builtins_integer.cpp.
round() [1/3]
s::cl_double cl::__host_std::round (s::cl_double x)
Definition at line 724 of file builtins_math.cpp.
References round().
round() [2/3]
s::cl_float cl::__host_std::round (s::cl_float x)
Definition at line 723 of file builtins_math.cpp.
References round().
round() [3/3]
s::cl_half cl::__host_std::round (s::cl_half x)
Definition at line 727 of file builtins_math.cpp.
Referenced by round().
rsqrt() [1/3]
s::cl_double cl::__host_std::rsqrt (s::cl_double x)
Definition at line 734 of file builtins_math.cpp.
rsqrt() [2/3]
s::cl_float cl::__host_std::rsqrt (s::cl_float x)
Definition at line 733 of file builtins_math.cpp.
rsqrt() [3/3]
s::cl_half cl::__host_std::rsqrt (s::cl_half x)
Definition at line 735 of file builtins_math.cpp.
s_abs() [1/4]
s::cl_uchar cl::__host_std::s_abs (s::cl_char x)
Definition at line 251 of file builtins_integer.cpp.
References cl::sycl::abs().
s_abs() [2/4]
s::cl_uint cl::__host_std::s_abs (s::cl_int x)
Definition at line 253 of file builtins_integer.cpp.
References cl::sycl::abs().
s_abs() [3/4]
s::cl_ulong cl::__host_std::s_abs (s::cl_long x)
Definition at line 254 of file builtins_integer.cpp.
References cl::sycl::abs().
s_abs() [4/4]
s::cl_ushort cl::__host_std::s_abs (s::cl_short x)
Definition at line 252 of file builtins_integer.cpp.
References cl::sycl::abs().
s_abs_diff() [1/4]
s::cl_uchar cl::__host_std::s_abs_diff (s::cl_char x, s::cl_char y)
Definition at line 280 of file builtins_integer.cpp.
s_abs_diff() [2/4]
s::cl_uint cl::__host_std::s_abs_diff (s::cl_int x, s::cl_int y)
Definition at line 286 of file builtins_integer.cpp.
s_abs_diff() [3/4]
s::cl_ulong cl::__host_std::s_abs_diff (s::cl_long x, s::cl_long y)
Definition at line 289 of file builtins_integer.cpp.
s_abs_diff() [4/4]
s::cl_ushort cl::__host_std::s_abs_diff (s::cl_short x, s::cl_short y)
Definition at line 283 of file builtins_integer.cpp.
s_add_sat() [1/4]
s::cl_char cl::__host_std::s_add_sat (s::cl_char x, s::cl_char y)
Definition at line 316 of file builtins_integer.cpp.
s_add_sat() [2/4]
s::cl_int cl::__host_std::s_add_sat (s::cl_int x, s::cl_int y)
Definition at line 322 of file builtins_integer.cpp.
s_add_sat() [3/4]
s::cl_long cl::__host_std::s_add_sat (s::cl_long x, s::cl_long y)
Definition at line 325 of file builtins_integer.cpp.
s_add_sat() [4/4]
s::cl_short cl::__host_std::s_add_sat (s::cl_short x, s::cl_short y)
Definition at line 319 of file builtins_integer.cpp.
s_clamp() [1/4]
s::cl_char cl::__host_std::s_clamp (s::cl_char x, s::cl_char minval, s::cl_char maxval)
Definition at line 432 of file builtins_integer.cpp.
s_clamp() [2/4]
s::cl_int cl::__host_std::s_clamp (s::cl_int x, s::cl_int minval, s::cl_int maxval)
Definition at line 440 of file builtins_integer.cpp.
s_clamp() [3/4]
s::cl_long cl::__host_std::s_clamp (s::cl_long x, s::cl_long minval, s::cl_long maxval)
Definition at line 444 of file builtins_integer.cpp.
s_clamp() [4/4]
s::cl_short cl::__host_std::s_clamp (s::cl_short x, s::cl_short minval, s::cl_short maxval)
Definition at line 436 of file builtins_integer.cpp.
s_hadd() [1/4]
s::cl_char cl::__host_std::s_hadd (s::cl_char x, s::cl_char y)
Definition at line 352 of file builtins_integer.cpp.
s_hadd() [2/4]
s::cl_int cl::__host_std::s_hadd (s::cl_int x, s::cl_int y)
Definition at line 358 of file builtins_integer.cpp.
s_hadd() [3/4]
s::cl_long cl::__host_std::s_hadd (s::cl_long x, s::cl_long y)
Definition at line 361 of file builtins_integer.cpp.
s_hadd() [4/4]
s::cl_short cl::__host_std::s_hadd (s::cl_short x, s::cl_short y)
Definition at line 355 of file builtins_integer.cpp.
s_mad24()
s::cl_int cl::__host_std::s_mad24 (s::cl_int x, s::cl_int y, s::cl_int z)
Definition at line 843 of file builtins_integer.cpp.
s_mad_hi() [1/4]
s::cl_char cl::__host_std::s_mad_hi (s::cl_char x, s::cl_char minval, s::cl_char maxval)
Definition at line 530 of file builtins_integer.cpp.
s_mad_hi() [2/4]
s::cl_int cl::__host_std::s_mad_hi (s::cl_int x, s::cl_int minval, s::cl_int maxval)
Definition at line 538 of file builtins_integer.cpp.
s_mad_hi() [3/4]
s::cl_long cl::__host_std::s_mad_hi (s::cl_long x, s::cl_long minval, s::cl_long maxval)
Definition at line 542 of file builtins_integer.cpp.
s_mad_hi() [4/4]
s::cl_short cl::__host_std::s_mad_hi (s::cl_short x, s::cl_short minval, s::cl_short maxval)
Definition at line 534 of file builtins_integer.cpp.
s_mad_sat() [1/4]
s::cl_char cl::__host_std::s_mad_sat (s::cl_char a, s::cl_char b, s::cl_char c)
Definition at line 574 of file builtins_integer.cpp.
s_mad_sat() [2/4]
s::cl_int cl::__host_std::s_mad_sat (s::cl_int a, s::cl_int b, s::cl_int c)
Definition at line 582 of file builtins_integer.cpp.
s_mad_sat() [3/4]
s::cl_long cl::__host_std::s_mad_sat (s::cl_long a, s::cl_long b, s::cl_long c)
Definition at line 586 of file builtins_integer.cpp.
s_mad_sat() [4/4]
s::cl_short cl::__host_std::s_mad_sat (s::cl_short a, s::cl_short b, s::cl_short c)
Definition at line 578 of file builtins_integer.cpp.
s_max() [1/4]
s::cl_char cl::__host_std::s_max (s::cl_char x, s::cl_char y)
Definition at line 618 of file builtins_integer.cpp.
s_max() [2/4]
s::cl_int cl::__host_std::s_max (s::cl_int x, s::cl_int y)
Definition at line 624 of file builtins_integer.cpp.
s_max() [3/4]
s::cl_long cl::__host_std::s_max (s::cl_long x, s::cl_long y)
Definition at line 627 of file builtins_integer.cpp.
s_max() [4/4]
s::cl_short cl::__host_std::s_max (s::cl_short x, s::cl_short y)
Definition at line 621 of file builtins_integer.cpp.
s_min() [1/4]
s::cl_char cl::__host_std::s_min (s::cl_char x, s::cl_char y)
Definition at line 662 of file builtins_integer.cpp.
s_min() [2/4]
s::cl_int cl::__host_std::s_min (s::cl_int x, s::cl_int y)
Definition at line 668 of file builtins_integer.cpp.
s_min() [3/4]
s::cl_long cl::__host_std::s_min (s::cl_long x, s::cl_long y)
Definition at line 671 of file builtins_integer.cpp.
s_min() [4/4]
s::cl_short cl::__host_std::s_min (s::cl_short x, s::cl_short y)
Definition at line 665 of file builtins_integer.cpp.
s_mul24()
s::cl_int cl::__host_std::s_mul24 (s::cl_int x, s::cl_int y)
Definition at line 855 of file builtins_integer.cpp.
s_mul_hi() [1/4]
s::cl_char cl::__host_std::s_mul_hi (s::cl_char a, s::cl_char b)
Definition at line 494 of file builtins_integer.cpp.
s_mul_hi() [2/4]
s::cl_int cl::__host_std::s_mul_hi (s::cl_int a, s::cl_int b)
Definition at line 500 of file builtins_integer.cpp.
s_mul_hi() [3/4]
s::cl_long cl::__host_std::s_mul_hi (s::cl_long x, s::cl_long y)
Definition at line 503 of file builtins_integer.cpp.
s_mul_hi() [4/4]
s::cl_short cl::__host_std::s_mul_hi (s::cl_short a, s::cl_short b)
Definition at line 497 of file builtins_integer.cpp.
s_rhadd() [1/4]
s::cl_char cl::__host_std::s_rhadd (s::cl_char x, s::cl_char y)
Definition at line 388 of file builtins_integer.cpp.
s_rhadd() [2/4]
s::cl_int cl::__host_std::s_rhadd (s::cl_int x, s::cl_int y)
Definition at line 394 of file builtins_integer.cpp.
s_rhadd() [3/4]
s::cl_long cl::__host_std::s_rhadd (s::cl_long x, s::cl_long y)
Definition at line 397 of file builtins_integer.cpp.
s_rhadd() [4/4]
s::cl_short cl::__host_std::s_rhadd (s::cl_short x, s::cl_short y)
Definition at line 391 of file builtins_integer.cpp.
s_sub_sat() [1/4]
s::cl_char cl::__host_std::s_sub_sat (s::cl_char x, s::cl_char y)
Definition at line 758 of file builtins_integer.cpp.
s_sub_sat() [2/4]
s::cl_int cl::__host_std::s_sub_sat (s::cl_int x, s::cl_int y)
Definition at line 764 of file builtins_integer.cpp.
s_sub_sat() [3/4]
s::cl_long cl::__host_std::s_sub_sat (s::cl_long x, s::cl_long y)
Definition at line 767 of file builtins_integer.cpp.
s_sub_sat() [4/4]
s::cl_short cl::__host_std::s_sub_sat (s::cl_short x, s::cl_short y)
Definition at line 761 of file builtins_integer.cpp.
s_upsample() [1/3]
s::cl_short cl::__host_std::s_upsample (s::cl_char x, s::cl_uchar y)
Definition at line 789 of file builtins_integer.cpp.
s_upsample() [2/3]
s::cl_long cl::__host_std::s_upsample (s::cl_int x, s::cl_uint y)
Definition at line 795 of file builtins_integer.cpp.
s_upsample() [3/3]
s::cl_int cl::__host_std::s_upsample (s::cl_short x, s::cl_ushort y)
Definition at line 792 of file builtins_integer.cpp.
sin() [1/3]
s::cl_double cl::__host_std::sin (s::cl_double x)
Definition at line 742 of file builtins_math.cpp.
References sin().
sin() [2/3]
s::cl_float cl::__host_std::sin (s::cl_float x)
Definition at line 741 of file builtins_math.cpp.
References sin().
sin() [3/3]
s::cl_half cl::__host_std::sin (s::cl_half x)
Definition at line 743 of file builtins_math.cpp.
Referenced by half_sin(), native_sin(), and sin().
sincos() [1/3]
s::cl_double cl::__host_std::sincos (s::cl_double x, s::cl_double * cosval)
Definition at line 752 of file builtins_math.cpp.
sincos() [2/3]
s::cl_float cl::__host_std::sincos (s::cl_float x, s::cl_float * cosval)
Definition at line 749 of file builtins_math.cpp.
sincos() [3/3]
s::cl_half cl::__host_std::sincos (s::cl_half x, s::cl_half * cosval)
Definition at line 756 of file builtins_math.cpp.
sinh() [1/3]
s::cl_double cl::__host_std::sinh (s::cl_double x)
Definition at line 765 of file builtins_math.cpp.
References sinh().
sinh() [2/3]
s::cl_float cl::__host_std::sinh (s::cl_float x)
Definition at line 764 of file builtins_math.cpp.
References sinh().
sinh() [3/3]
s::cl_half cl::__host_std::sinh (s::cl_half x)
Definition at line 766 of file builtins_math.cpp.
Referenced by sinh().
sinpi() [1/3]
s::cl_double cl::__host_std::sinpi (s::cl_double x)
Definition at line 773 of file builtins_math.cpp.
sinpi() [2/3]
s::cl_float cl::__host_std::sinpi (s::cl_float x)
Definition at line 772 of file builtins_math.cpp.
sinpi() [3/3]
s::cl_half cl::__host_std::sinpi (s::cl_half x)
Definition at line 774 of file builtins_math.cpp.
smoothstep() [1/3]
s::cl_double cl::__host_std::smoothstep (s::cl_double edge0, s::cl_double edge1, s::cl_double x)
Definition at line 176 of file builtins_common.cpp.
smoothstep() [2/3]
s::cl_float cl::__host_std::smoothstep (s::cl_float edge0, s::cl_float edge1, s::cl_float x)
Definition at line 172 of file builtins_common.cpp.
smoothstep() [3/3]
s::cl_half cl::__host_std::smoothstep (s::cl_half edge0, s::cl_half edge1, s::cl_half x)
Definition at line 180 of file builtins_common.cpp.
sqrt() [1/3]
s::cl_double cl::__host_std::sqrt (s::cl_double x)
Definition at line 781 of file builtins_math.cpp.
References sqrt().
sqrt() [2/3]
s::cl_float cl::__host_std::sqrt (s::cl_float x)
Definition at line 780 of file builtins_math.cpp.
References sqrt().
sqrt() [3/3]
s::cl_half cl::__host_std::sqrt (s::cl_half x)
Definition at line 782 of file builtins_math.cpp.
Referenced by half_rsqrt(), half_sqrt(), native_rsqrt(), native_sqrt(), and sqrt().
step() [1/3]
s::cl_double cl::__host_std::step (s::cl_double edge, s::cl_double x)
Definition at line 161 of file builtins_common.cpp.
step() [2/3]
s::cl_float cl::__host_std::step (s::cl_float edge, s::cl_float x)
Definition at line 158 of file builtins_common.cpp.
step() [3/3]
s::cl_half cl::__host_std::step (s::cl_half edge, s::cl_half x)
Definition at line 164 of file builtins_common.cpp.
tan() [1/3]
s::cl_double cl::__host_std::tan (s::cl_double x)
Definition at line 789 of file builtins_math.cpp.
References tan().
tan() [2/3]
s::cl_float cl::__host_std::tan (s::cl_float x)
Definition at line 788 of file builtins_math.cpp.
References tan().
tan() [3/3]
s::cl_half cl::__host_std::tan (s::cl_half x)
Definition at line 790 of file builtins_math.cpp.
Referenced by half_tan(), native_tan(), and tan().
tanh() [1/3]
s::cl_double cl::__host_std::tanh (s::cl_double x)
Definition at line 797 of file builtins_math.cpp.
References tanh().
tanh() [2/3]
s::cl_float cl::__host_std::tanh (s::cl_float x)
Definition at line 796 of file builtins_math.cpp.
References tanh().
tanh() [3/3]
s::cl_half cl::__host_std::tanh (s::cl_half x)
Definition at line 798 of file builtins_math.cpp.
Referenced by tanh().
tanpi() [1/3]
s::cl_double cl::__host_std::tanpi (s::cl_double x)
Definition at line 805 of file builtins_math.cpp.
tanpi() [2/3]
s::cl_float cl::__host_std::tanpi (s::cl_float x)
Definition at line 804 of file builtins_math.cpp.
tanpi() [3/3]
s::cl_half cl::__host_std::tanpi (s::cl_half x)
Definition at line 806 of file builtins_math.cpp.
tgamma() [1/3]
s::cl_double cl::__host_std::tgamma (s::cl_double x)
Definition at line 815 of file builtins_math.cpp.
References tgamma().
tgamma() [2/3]
s::cl_float cl::__host_std::tgamma (s::cl_float x)
Definition at line 812 of file builtins_math.cpp.
References tgamma().
tgamma() [3/3]
s::cl_half cl::__host_std::tgamma (s::cl_half x)
Definition at line 818 of file builtins_math.cpp.
Referenced by tgamma().
trunc() [1/3]
s::cl_double cl::__host_std::trunc (s::cl_double x)
Definition at line 825 of file builtins_math.cpp.
References trunc().
trunc() [2/3]
s::cl_float cl::__host_std::trunc (s::cl_float x)
Definition at line 824 of file builtins_math.cpp.
References trunc().
trunc() [3/3]
s::cl_half cl::__host_std::trunc (s::cl_half x)
Definition at line 828 of file builtins_math.cpp.
Referenced by trunc().
u_abs() [1/4]
s::cl_uchar cl::__host_std::u_abs (s::cl_uchar x)
Definition at line 241 of file builtins_integer.cpp.
u_abs() [2/4]
s::cl_uint cl::__host_std::u_abs (s::cl_uint x)
Definition at line 243 of file builtins_integer.cpp.
u_abs() [3/4]
s::cl_ulong cl::__host_std::u_abs (s::cl_ulong x)
Definition at line 244 of file builtins_integer.cpp.
u_abs() [4/4]
s::cl_ushort cl::__host_std::u_abs (s::cl_ushort x)
Definition at line 242 of file builtins_integer.cpp.
u_abs_diff() [1/4]
s::cl_uchar cl::__host_std::u_abs_diff (s::cl_uchar x, s::cl_uchar y)
Definition at line 261 of file builtins_integer.cpp.
u_abs_diff() [2/4]
s::cl_uint cl::__host_std::u_abs_diff (s::cl_uint x, s::cl_uint y)
Definition at line 267 of file builtins_integer.cpp.
u_abs_diff() [3/4]
s::cl_ulong cl::__host_std::u_abs_diff (s::cl_ulong x, s::cl_ulong y)
Definition at line 270 of file builtins_integer.cpp.
u_abs_diff() [4/4]
s::cl_ushort cl::__host_std::u_abs_diff (s::cl_ushort x, s::cl_ushort y)
Definition at line 264 of file builtins_integer.cpp.
u_add_sat() [1/4]
s::cl_uchar cl::__host_std::u_add_sat (s::cl_uchar x, s::cl_uchar y)
Definition at line 298 of file builtins_integer.cpp.
u_add_sat() [2/4]
s::cl_uint cl::__host_std::u_add_sat (s::cl_uint x, s::cl_uint y)
Definition at line 304 of file builtins_integer.cpp.
u_add_sat() [3/4]
s::cl_ulong cl::__host_std::u_add_sat (s::cl_ulong x, s::cl_ulong y)
Definition at line 307 of file builtins_integer.cpp.
u_add_sat() [4/4]
s::cl_ushort cl::__host_std::u_add_sat (s::cl_ushort x, s::cl_ushort y)
Definition at line 301 of file builtins_integer.cpp.
u_clamp() [1/4]
s::cl_uchar cl::__host_std::u_clamp (s::cl_uchar x, s::cl_uchar minval, s::cl_uchar maxval)
Definition at line 406 of file builtins_integer.cpp.
u_clamp() [2/4]
s::cl_uint cl::__host_std::u_clamp (s::cl_uint x, s::cl_uint minval, s::cl_uint maxval)
Definition at line 414 of file builtins_integer.cpp.
u_clamp() [3/4]
s::cl_ulong cl::__host_std::u_clamp (s::cl_ulong x, s::cl_ulong minval, s::cl_ulong maxval)
Definition at line 418 of file builtins_integer.cpp.
u_clamp() [4/4]
s::cl_ushort cl::__host_std::u_clamp (s::cl_ushort x, s::cl_ushort minval, s::cl_ushort maxval)
Definition at line 410 of file builtins_integer.cpp.
u_hadd() [1/4]
s::cl_uchar cl::__host_std::u_hadd (s::cl_uchar x, s::cl_uchar y)
Definition at line 334 of file builtins_integer.cpp.
u_hadd() [2/4]
s::cl_uint cl::__host_std::u_hadd (s::cl_uint x, s::cl_uint y)
Definition at line 340 of file builtins_integer.cpp.
u_hadd() [3/4]
s::cl_ulong cl::__host_std::u_hadd (s::cl_ulong x, s::cl_ulong y)
Definition at line 343 of file builtins_integer.cpp.
u_hadd() [4/4]
s::cl_ushort cl::__host_std::u_hadd (s::cl_ushort x, s::cl_ushort y)
Definition at line 337 of file builtins_integer.cpp.
u_mad24()
s::cl_uint cl::__host_std::u_mad24 (s::cl_uint x, s::cl_uint y, s::cl_uint z)
Definition at line 836 of file builtins_integer.cpp.
u_mad_hi() [1/4]
s::cl_uchar cl::__host_std::u_mad_hi (s::cl_uchar x, s::cl_uchar minval, s::cl_uchar maxval)
Definition at line 552 of file builtins_integer.cpp.
u_mad_hi() [2/4]
s::cl_uint cl::__host_std::u_mad_hi (s::cl_uint x, s::cl_uint minval, s::cl_uint maxval)
Definition at line 560 of file builtins_integer.cpp.
u_mad_hi() [3/4]
s::cl_ulong cl::__host_std::u_mad_hi (s::cl_ulong x, s::cl_ulong minval, s::cl_ulong maxval)
Definition at line 564 of file builtins_integer.cpp.
u_mad_hi() [4/4]
s::cl_ushort cl::__host_std::u_mad_hi (s::cl_ushort x, s::cl_ushort minval, s::cl_ushort maxval)
Definition at line 556 of file builtins_integer.cpp.
u_mad_sat() [1/4]
s::cl_uchar cl::__host_std::u_mad_sat (s::cl_uchar a, s::cl_uchar b, s::cl_uchar c)
Definition at line 596 of file builtins_integer.cpp.
u_mad_sat() [2/4]
s::cl_uint cl::__host_std::u_mad_sat (s::cl_uint a, s::cl_uint b, s::cl_uint c)
Definition at line 604 of file builtins_integer.cpp.
u_mad_sat() [3/4]
s::cl_ulong cl::__host_std::u_mad_sat (s::cl_ulong a, s::cl_ulong b, s::cl_ulong c)
Definition at line 608 of file builtins_integer.cpp.
u_mad_sat() [4/4]
s::cl_ushort cl::__host_std::u_mad_sat (s::cl_ushort a, s::cl_ushort b, s::cl_ushort c)
Definition at line 600 of file builtins_integer.cpp.
u_max() [1/4]
s::cl_uchar cl::__host_std::u_max (s::cl_uchar x, s::cl_uchar y)
Definition at line 640 of file builtins_integer.cpp.
u_max() [2/4]
s::cl_uint cl::__host_std::u_max (s::cl_uint x, s::cl_uint y)
Definition at line 646 of file builtins_integer.cpp.
u_max() [3/4]
s::cl_ulong cl::__host_std::u_max (s::cl_ulong x, s::cl_ulong y)
Definition at line 649 of file builtins_integer.cpp.
u_max() [4/4]
s::cl_ushort cl::__host_std::u_max (s::cl_ushort x, s::cl_ushort y)
Definition at line 643 of file builtins_integer.cpp.
u_min() [1/4]
s::cl_uchar cl::__host_std::u_min (s::cl_uchar x, s::cl_uchar y)
Definition at line 684 of file builtins_integer.cpp.
u_min() [2/4]
s::cl_uint cl::__host_std::u_min (s::cl_uint x, s::cl_uint y)
Definition at line 690 of file builtins_integer.cpp.
u_min() [3/4]
s::cl_ulong cl::__host_std::u_min (s::cl_ulong x, s::cl_ulong y)
Definition at line 693 of file builtins_integer.cpp.
u_min() [4/4]
s::cl_ushort cl::__host_std::u_min (s::cl_ushort x, s::cl_ushort y)
Definition at line 687 of file builtins_integer.cpp.
u_mul24()
s::cl_uint cl::__host_std::u_mul24 (s::cl_uint x, s::cl_uint y)
Definition at line 849 of file builtins_integer.cpp.
u_mul_hi() [1/4]
s::cl_uchar cl::__host_std::u_mul_hi (s::cl_uchar a, s::cl_uchar b)
Definition at line 512 of file builtins_integer.cpp.
u_mul_hi() [2/4]
s::cl_uint cl::__host_std::u_mul_hi (s::cl_uint a, s::cl_uint b)
Definition at line 518 of file builtins_integer.cpp.
u_mul_hi() [3/4]
s::cl_ulong cl::__host_std::u_mul_hi (s::cl_ulong x, s::cl_ulong y)
Definition at line 521 of file builtins_integer.cpp.
u_mul_hi() [4/4]
s::cl_ushort cl::__host_std::u_mul_hi (s::cl_ushort a, s::cl_ushort b)
Definition at line 515 of file builtins_integer.cpp.
u_rhadd() [1/4]
s::cl_uchar cl::__host_std::u_rhadd (s::cl_uchar x, s::cl_uchar y)
Definition at line 370 of file builtins_integer.cpp.
u_rhadd() [2/4]
s::cl_uint cl::__host_std::u_rhadd (s::cl_uint x, s::cl_uint y)
Definition at line 376 of file builtins_integer.cpp.
u_rhadd() [3/4]
s::cl_ulong cl::__host_std::u_rhadd (s::cl_ulong x, s::cl_ulong y)
Definition at line 379 of file builtins_integer.cpp.
u_rhadd() [4/4]
s::cl_ushort cl::__host_std::u_rhadd (s::cl_ushort x, s::cl_ushort y)
Definition at line 373 of file builtins_integer.cpp.
u_sub_sat() [1/4]
s::cl_uchar cl::__host_std::u_sub_sat (s::cl_uchar x, s::cl_uchar y)
Definition at line 740 of file builtins_integer.cpp.
u_sub_sat() [2/4]
s::cl_uint cl::__host_std::u_sub_sat (s::cl_uint x, s::cl_uint y)
Definition at line 746 of file builtins_integer.cpp.
u_sub_sat() [3/4]
s::cl_ulong cl::__host_std::u_sub_sat (s::cl_ulong x, s::cl_ulong y)
Definition at line 749 of file builtins_integer.cpp.
u_sub_sat() [4/4]
s::cl_ushort cl::__host_std::u_sub_sat (s::cl_ushort x, s::cl_ushort y)
Definition at line 743 of file builtins_integer.cpp.
u_upsample() [1/3]
s::cl_ushort cl::__host_std::u_upsample (s::cl_uchar x, s::cl_uchar y)
Definition at line 776 of file builtins_integer.cpp.
u_upsample() [2/3]
s::cl_ulong cl::__host_std::u_upsample (s::cl_uint x, s::cl_uint y)
Definition at line 782 of file builtins_integer.cpp.
u_upsample() [3/3]
s::cl_uint cl::__host_std::u_upsample (s::cl_ushort x, s::cl_ushort y)
Definition at line 779 of file builtins_integer.cpp.
Variable Documentation
__vFUnordNotEqual
cl::__host_std::__vFUnordNotEqual
Definition at line 169 of file builtins_relational.cpp.
Dot
s::cl_half cl::__host_std::Dot(s::cl_half4, s::cl_half4) (s::vec< s::half, 1 > , s::vec< s::half, 1 >)