DPC++ Runtime: cl::sycl::INTEL::gpu::detail Namespace Reference
cl::sycl::INTEL::gpu::detail Namespace Reference
Classes
struct accessor_mode_cap
class AccessorPrivateProxy
struct bitcast_helper
struct byte_type
struct byte_type< int >
struct byte_type< short >
struct byte_type< uint >
struct byte_type< ushort >
struct common_type
struct computation_type
Get the computation type.
struct compute_format_type
struct compute_format_type< simd< Ty, N >, EltTy >
struct compute_format_type< simd_view< BaseTy, RegionTy >, EltTy >
struct compute_format_type_2d
struct compute_format_type_2d< simd< Ty, N >, EltTy, Height, Width >
struct compute_format_type_2d< simd_view< BaseTy, RegionTy >, EltTy, Height, Width >
struct dword_type
struct dword_type< char >
struct dword_type< short >
struct dword_type< uchar >
struct dword_type< ushort >
struct element_type
struct element_type< simd< Ty, N > >
struct element_type< simd_view< BaseTy, RegionTy > >
struct esimd_apply_prod
struct esimd_apply_reduced_max
struct esimd_apply_reduced_min
struct esimd_apply_sum
struct is_byte_type
struct is_byte_type< sycl::INTEL::gpu::detail::vector_type< T, N > >
struct is_byte_type< sycl::INTEL::gpu::simd< T, N > >
struct is_df_type
struct is_dword_type
struct is_dword_type< sycl::INTEL::gpu::detail::vector_type< T, N > >
struct is_dword_type< sycl::INTEL::gpu::simd< T, N > >
struct is_esimd_arithmetic_type
struct is_esimd_arithmetic_type< Ty, __esimd_void_t< decltype(std::declval< Ty >()+std::declval< Ty >()), decltype(std::declval< Ty >() - std::declval< Ty >()), decltype(std::declval< Ty >() *std::declval< Ty >()), decltype(std::declval< Ty >()/std::declval< Ty >())> >
struct is_esimd_scalar
struct is_esimd_vector
type traits
struct is_esimd_vector< sycl::INTEL::gpu::detail::vector_type< T, N > >
struct is_esimd_vector< sycl::INTEL::gpu::simd< T, N > >
struct is_fp_or_dword_type
struct is_fp_or_dword_type< sycl::INTEL::gpu::detail::vector_type< T, N > >
struct is_fp_or_dword_type< sycl::INTEL::gpu::simd< T, N > >
struct is_fp_type
struct is_qword_type
struct is_qword_type< sycl::INTEL::gpu::detail::vector_type< T, N > >
struct is_qword_type< sycl::INTEL::gpu::simd< T, N > >
struct is_simd_type
struct is_simd_type< simd< Ty, N > >
struct is_simd_type< simd_view< BaseTy, RegionTy > >
struct is_simd_v
struct is_simd_view_type
struct is_simd_view_type< simd_view< BaseTy, RegionTy > >
struct is_simd_view_v
struct is_sycl_accessor
struct is_sycl_accessor< sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > >
struct is_sycl_accessor_with
struct is_vectorizable
struct is_vectorizable< bool >
struct is_vectorizable_v
struct is_word_type
struct is_word_type< sycl::INTEL::gpu::detail::vector_type< T, N > >
struct is_word_type< sycl::INTEL::gpu::simd< T, N > >
struct Log2
Compute binary logarithm of a constexpr with guaranteed compile-time evaluation.
struct Log2< N, false >
struct Log2< N, true >
struct make_esimd_void
struct NextPowerOf2
Compute next power of 2 of a constexpr with guaranteed compile-time evaluation.
struct NextPowerOf2< N, K, false >
struct NextPowerOf2< N, K, true >
struct OperandSize
ESIMD intrinsic operand size in bytes.
struct simd_type
Convert types into vector types.
struct simd_type< const T >
struct simd_type< sycl::INTEL::gpu::detail::vector_type< T, N > >
struct simd_type< T & >
struct simd_type< T && >
struct vector_type
struct word_type
struct word_type< char >
struct word_type< int >
struct word_type< uchar >
struct word_type< uint >
Typedefs
using accessor_mode_cap_val_t = bool
template<typename T , accessor_mode_cap_val_t Capability, sycl::access::target AccessTarget, typename RetT >
using EnableIfAccessor = sycl::detail::enable_if_t< detail::is_sycl_accessor_with< T, Capability, AccessTarget >::value, RetT >
using half = cl::sycl::detail::half_impl::StorageT
template<typename T >
using remove_cvref_t = csd::remove_cv_t< csd::remove_reference_t< T > >
template<class... Tys>
using __esimd_void_t = typename make_esimd_void< Tys... >::type
template<typename Ty , int N>
using vector_type_t = typename vector_type< Ty, N >::type
template<typename Ty , typename EltTy >
using compute_format_type_t = typename compute_format_type< Ty, EltTy >::type
template<typename Ty , typename EltTy , int Height, int Width>
using compute_format_type_2d_t = typename compute_format_type_2d< Ty, EltTy, Height, Width >::type
template<typename T1 , typename T2 = T1>
using compute_type_t = typename common_type< remove_cvref_t< T1 >, remove_cvref_t< T2 > >::type
Functions
template<typename BT , int BN, typename RTy >
__SIGD::vector_type_t< typename RTy::element_type, RTy::length > ESIMD_INLINE readRegion (const __SIGD::vector_type_t< BT, BN > &Base, RTy Region)
read from a basic region of a vector, return a vector
template<typename BT , int BN, typename T , typename U >
ESIMD_INLINE __SIGD::vector_type_t< typename T::element_type, T::length > readRegion (const __SIGD::vector_type_t< BT, BN > &Base, std::pair< T, U > Region)
read from a nested region of a vector, return a vector
template<int ElemsPerAddr, typename = sycl::detail::enable_if_t< (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)>>
constexpr unsigned int ElemsPerAddrEncoding ()
constexpr unsigned int ElemsPerAddrDecoding (unsigned int ElemsPerAddrEncoded)
template<sycl::access::mode Mode, accessor_mode_cap_val_t Cap>
constexpr bool accessor_mode_has_capability ()
template<typename To , typename From >
To convert (From Val)
template<typename U >
constexpr bool is_type ()
Base case for checking if a type U is one of the types.
template<typename U , typename T , typename... Ts>
constexpr bool is_type ()
template<typename ToEltTy , typename FromEltTy , int FromN, typename = csd::enable_if_t<is_vectorizable<ToEltTy>::value>>
ESIMD_INLINE csd::conditional_t< std::is_same< FromEltTy, ToEltTy >::value, vector_type_t< FromEltTy, FromN >, vector_type_t< ToEltTy, bitcast_helper< ToEltTy, FromEltTy, FromN >::nToElems()> > bitcast (vector_type_t< FromEltTy, FromN > Val)
std::ostream & operator<< (std::ostream &O, half const &rhs)
std::istream & operator>> (std::istream &I, half &rhs)
template<unsigned int N>
constexpr unsigned int getNextPowerOf2 ()
template<>
constexpr unsigned int getNextPowerOf2< 0 > ()
template<unsigned int N>
constexpr unsigned int log2 ()
static constexpr ESIMD_INLINE bool isPowerOf2 (unsigned int n)
Check if a given 32 bit positive integer is a power of 2 at compile time.
static constexpr ESIMD_INLINE bool isPowerOf2 (unsigned int n, unsigned int limit)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T0, SZ > __esimd_abs_common_internal (simd< T1, SZ > src0, int flag=GENX_NOSAT)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value, typename sycl::detail::remove_const_t< T0 > > __esimd_abs_common_internal (T1 src0, int flag=GENX_NOSAT)
template<int N>
ESIMD_INLINE simd< float, N > esimd_tanh_cody_waite_impl (simd< float, N > x)
template<int N>
ESIMD_INLINE simd< float, N > esimd_tanh_impl (simd< float, N > x)
template<typename T0 , typename T1 , int SZ, template< typename RT, typename T, int N > class OpType>
T0 esimd_reduce_single (simd< T1, SZ > v)
template<typename T0 , typename T1 , int N1, int N2, template< typename RT, typename T, int N > class OpType>
T0 esimd_reduce_pair (simd< T1, N1 > v1, simd< T1, N2 > v2)
template<typename T0 , typename T1 , int SZ, template< typename RT, typename T, int N > class OpType>
T0 esimd_reduce (simd< T1, SZ > v)
template<typename T0 , typename T1 , int SZ>
ESIMD_INLINE ESIMD_NODEBUG T0 esimd_sum (simd< T1, SZ > v)
template<typename T0 , typename T1 , int SZ>
ESIMD_INLINE ESIMD_NODEBUG T0 esimd_prod (simd< T1, SZ > v)
template<EsimdAtomicOpType Op, typename T , int N, unsigned NumSrc>
constexpr bool check_atomic ()
Check the legality of an atomic call in terms of size and type.
Typedef Documentation
__esimd_void_t
template<class... Tys> using cl::sycl::INTEL::gpu::detail::__esimd_void_t = typedef typename make_esimd_void<Tys...>::type
Definition at line 42 of file esimd_types.hpp.
accessor_mode_cap_val_t
using cl::sycl::INTEL::gpu::detail::accessor_mode_cap_val_t = typedef bool
Definition at line 43 of file esimd_sycl_util.hpp.
compute_format_type_2d_t
template<typename Ty , typename EltTy , int Height, int Width> using cl::sycl::INTEL::gpu::detail::compute_format_type_2d_t = typedef typename compute_format_type_2d<Ty, EltTy, Height, Width>::type
Definition at line 132 of file esimd_types.hpp.
compute_format_type_t
template<typename Ty , typename EltTy > using cl::sycl::INTEL::gpu::detail::compute_format_type_t = typedef typename compute_format_type<Ty, EltTy>::type
Definition at line 97 of file esimd_types.hpp.
compute_type_t
template<typename T1 , typename T2 = T1> using cl::sycl::INTEL::gpu::detail::compute_type_t = typedef typename common_type<remove_cvref_t<T1>, remove_cvref_t<T2> >::type
Definition at line 187 of file esimd_types.hpp.
EnableIfAccessor
template<typename T , accessor_mode_cap_val_t Capability, sycl::access::target AccessTarget, typename RetT > using cl::sycl::INTEL::gpu::detail::EnableIfAccessor = typedef sycl::detail::enable_if_t< detail::is_sycl_accessor_with<T, Capability, AccessTarget>::value, RetT>
Definition at line 80 of file esimd_sycl_util.hpp.
half
using cl::sycl::INTEL::gpu::detail::half = typedef cl::sycl::detail::half_impl::StorageT
Definition at line 33 of file esimd_types.hpp.
remove_cvref_t
template<typename T > using cl::sycl::INTEL::gpu::detail::remove_cvref_t = typedef csd::remove_cv_t<csd::remove_reference_t<T> >
Definition at line 37 of file esimd_types.hpp.
vector_type_t
template<typename Ty , int N> using cl::sycl::INTEL::gpu::detail::vector_type_t = typedef typename vector_type<Ty, N>::type
Definition at line 76 of file esimd_types.hpp.
Function Documentation
__esimd_abs_common_internal() [1/2]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T0, SZ> cl::sycl::INTEL::gpu::detail::__esimd_abs_common_internal (simd< T1, SZ > src0, int flag = GENX_NOSAT)
Definition at line 52 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), and cl::sycl::INTEL::gpu::GENX_SAT.
__esimd_abs_common_internal() [2/2]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::INTEL::gpu::detail::__esimd_abs_common_internal (T1 src0, int flag = GENX_NOSAT)
Definition at line 64 of file esimd_math.hpp.
accessor_mode_has_capability()
template<sycl::access::mode Mode, accessor_mode_cap_val_t Cap> constexpr bool cl::sycl::INTEL::gpu::detail::accessor_mode_has_capability () constexpr
Definition at line 52 of file esimd_sycl_util.hpp.
bitcast()
template<typename ToEltTy , typename FromEltTy , int FromN, typename = csd::enable_if_t<is_vectorizable<ToEltTy>::value>> ESIMD_INLINE csd::conditional_t< std::is_same<FromEltTy, ToEltTy>::value, vector_type_t<FromEltTy, FromN>, vector_type_t<ToEltTy, bitcast_helper<ToEltTy, FromEltTy, FromN>::nToElems()> > cl::sycl::INTEL::gpu::detail::bitcast (vector_type_t< FromEltTy, FromN > Val)
Definition at line 227 of file esimd_types.hpp.
convert()
template<typename To , typename From > To cl::sycl::INTEL::gpu::detail::convert (From Val)
Definition at line 189 of file esimd_types.hpp.
ElemsPerAddrDecoding()
constexpr unsigned int cl::sycl::INTEL::gpu::detail::ElemsPerAddrDecoding (unsigned int ElemsPerAddrEncoded) constexpr
Definition at line 60 of file esimd_memory_intrin.hpp.
Referenced by __esimd_flat_read(), and __esimd_flat_write().
ElemsPerAddrEncoding()
template<int ElemsPerAddr, typename = sycl::detail::enable_if_t< (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)>> constexpr unsigned int cl::sycl::INTEL::gpu::detail::ElemsPerAddrEncoding () constexpr
Definition at line 48 of file esimd_memory_intrin.hpp.
esimd_prod()
template<typename T0 , typename T1 , int SZ> ESIMD_INLINE ESIMD_NODEBUG T0 cl::sycl::INTEL::gpu::detail::esimd_prod (simd< T1, SZ > v)
Definition at line 1947 of file esimd_math.hpp.
esimd_reduce()
template<typename T0 , typename T1 , int SZ, template< typename RT, typename T, int N > class OpType> T0 cl::sycl::INTEL::gpu::detail::esimd_reduce (simd< T1, SZ > v)
Definition at line 1924 of file esimd_math.hpp.
References isPowerOf2().
esimd_reduce_pair()
template<typename T0 , typename T1 , int N1, int N2, template< typename RT, typename T, int N > class OpType> T0 cl::sycl::INTEL::gpu::detail::esimd_reduce_pair (simd< T1, N1 > v1, simd< T1, N2 > v2)
Definition at line 1899 of file esimd_math.hpp.
References isPowerOf2(), and cl::sycl::INTEL::gpu::simd< Ty, N >::read().
esimd_reduce_single()
template<typename T0 , typename T1 , int SZ, template< typename RT, typename T, int N > class OpType> T0 cl::sycl::INTEL::gpu::detail::esimd_reduce_single (simd< T1, SZ > v)
Definition at line 1883 of file esimd_math.hpp.
References isPowerOf2().
esimd_sum()
template<typename T0 , typename T1 , int SZ> ESIMD_INLINE ESIMD_NODEBUG T0 cl::sycl::INTEL::gpu::detail::esimd_sum (simd< T1, SZ > v)
Definition at line 1939 of file esimd_math.hpp.
esimd_tanh_cody_waite_impl()
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::detail::esimd_tanh_cody_waite_impl (simd< float, N > x)
Definition at line 1741 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::esimd_abs(), and cl::sycl::sign().
Referenced by cl::sycl::INTEL::gpu::esimd_tanh_cody_waite().
esimd_tanh_impl()
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::detail::esimd_tanh_impl (simd< float, N > x)
Definition at line 1784 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::esimd_abs(), cl::sycl::exp(), and cl::sycl::sign().
Referenced by cl::sycl::INTEL::gpu::esimd_tanh().
getNextPowerOf2()
template<unsigned int N> constexpr unsigned int cl::sycl::INTEL::gpu::detail::getNextPowerOf2 () constexpr
Definition at line 41 of file esimd_util.hpp.
References std::get().
getNextPowerOf2< 0 >()
template<> constexpr unsigned int cl::sycl::INTEL::gpu::detail::getNextPowerOf2< 0 > () constexpr
Definition at line 45 of file esimd_util.hpp.
is_type() [1/2]
template<typename U > constexpr bool cl::sycl::INTEL::gpu::detail::is_type () constexpr
Base case for checking if a type U is one of the types.
Definition at line 200 of file esimd_types.hpp.
is_type() [2/2]
template<typename U , typename T , typename... Ts> constexpr bool cl::sycl::INTEL::gpu::detail::is_type () constexpr
Definition at line 202 of file esimd_types.hpp.
isPowerOf2() [1/2]
static constexpr ESIMD_INLINE bool cl::sycl::INTEL::gpu::detail::isPowerOf2 (unsigned int n) static constexpr
Check if a given 32 bit positive integer is a power of 2 at compile time.
Definition at line 66 of file esimd_util.hpp.
Referenced by cl::sycl::INTEL::gpu::block_load(), cl::sycl::INTEL::gpu::block_store(), check_atomic(), cl::sycl::INTEL::gpu::simd< Ty, N >::copy_from(), cl::sycl::INTEL::gpu::simd< Ty, N >::copy_to(), esimd_reduce(), esimd_reduce_pair(), esimd_reduce_single(), cl::sycl::INTEL::gpu::slm_block_load(), and cl::sycl::INTEL::gpu::slm_block_store().
isPowerOf2() [2/2]
static constexpr ESIMD_INLINE bool cl::sycl::INTEL::gpu::detail::isPowerOf2 (unsigned int n, unsigned int limit) static constexpr
Definition at line 70 of file esimd_util.hpp.
log2()
template<unsigned int N> constexpr unsigned int cl::sycl::INTEL::gpu::detail::log2 () constexpr
Definition at line 61 of file esimd_util.hpp.
References std::get().
operator<<()
std::ostream& cl::sycl::INTEL::gpu::detail::operator<< (std::ostream & O, half const & rhs) inline
Definition at line 238 of file esimd_types.hpp.
operator>>()
std::istream& cl::sycl::INTEL::gpu::detail::operator>> (std::istream & I, half & rhs) inline
Definition at line 243 of file esimd_types.hpp.
readRegion() [1/2]
template<typename BT , int BN, typename RTy > __SIGD::vector_type_t<typename RTy::element_type, RTy::length> ESIMD_INLINE cl::sycl::INTEL::gpu::detail::readRegion (const __SIGD::vector_type_t< BT, BN > & Base, RTy Region)
read from a basic region of a vector, return a vector
Definition at line 145 of file esimd_intrin.hpp.
References __esimd_rdregion().
readRegion() [2/2]
template<typename BT , int BN, typename T , typename U > ESIMD_INLINE __SIGD::vector_type_t<typename T::element_type, T::length> cl::sycl::INTEL::gpu::detail::readRegion (const __SIGD::vector_type_t< BT, BN > & Base, std::pair< T, U > Region)
read from a nested region of a vector, return a vector
Definition at line 167 of file esimd_intrin.hpp.
References cl::sycl::length().