DPC++ Runtime: cl::sycl::ext::intel Namespace Reference
cl::sycl::ext::intel Namespace Reference
Namespaces
detail
esimd
experimental
property
Classes
struct _GetValue
struct _GetValue< _Type, _T1, _T... >
struct _MatchType
struct burst_coalesce_impl
struct cache
class fpga_emulator_selector
class fpga_selector
class kernel_readable_io_pipe
class kernel_writeable_io_pipe
class lsu
class pipe
class platform_selector
struct prefetch_impl
struct statically_coalesce_impl
Typedefs
template<bool _B>
using burst_coalesce = burst_coalesce_impl< _B >
template<bool _B>
using prefetch = prefetch_impl< _B >
template<bool _B>
using statically_coalesce = statically_coalesce_impl< _B >
Enumerations
enum Preference { Preference::DSP, Preference::Softlogic, Preference::Compiler_default }
enum Propagate { Propagate::On, Propagate::Off }
Functions
template<typename Function >
void math_prefer_dsp_propagate (Function f)
template<typename Function >
void math_prefer_dsp_no_propagate (Function f)
template<typename Function >
void math_prefer_softlogic_propagate (Function f)
template<typename Function >
void math_prefer_softlogic_no_propagate (Function f)
template<Preference my_preference = Preference::DSP, Propagate my_propagate = Propagate::On, typename Function >
void math_dsp_control (Function f)
Preference: Control the hardware implementation of math operations in the lambda expression.
template<int _N = 1, typename _F >
void fpga_loop_fuse (_F f)
template<int _N = 1, typename _F >
void fpga_loop_fuse_independent (_F f)
template<typename _T >
std::enable_if< std::is_trivially_copyable< _T >::value, _T >::type fpga_reg (_T t)
template<typename _T >
std::enable_if< std::is_trivially_copyable< _T >::value==false, _T >::type fpga_reg (_T t)
Variables
static constexpr auto EMULATION_PLATFORM_NAME
static constexpr auto HARDWARE_PLATFORM_NAME
constexpr uint8_t BURST_COALESCE = 0x1
constexpr uint8_t CACHE = 0x2
constexpr uint8_t STATICALLY_COALESCE = 0x4
constexpr uint8_t PREFETCH = 0x8
Typedef Documentation
burst_coalesce
template<bool _B> using cl::sycl::ext::intel::burst_coalesce = typedef burst_coalesce_impl<_B>
Definition at line 43 of file fpga_lsu.hpp.
prefetch
template<bool _B> using cl::sycl::ext::intel::prefetch = typedef prefetch_impl<_B>
Definition at line 44 of file fpga_lsu.hpp.
statically_coalesce
template<bool _B> using cl::sycl::ext::intel::statically_coalesce = typedef statically_coalesce_impl<_B>
Definition at line 45 of file fpga_lsu.hpp.
Enumeration Type Documentation
Preference
enum cl::sycl::ext::intel::Preference strong
Enumerator
DSP
Softlogic
Compiler_default
Definition at line 15 of file fpga_dsp_control.hpp.
Propagate
enum cl::sycl::ext::intel::Propagate strong
Enumerator
On
Off
Definition at line 16 of file fpga_dsp_control.hpp.
Function Documentation
fpga_loop_fuse()
template<int _N = 1, typename _F > void cl::sycl::ext::intel::fpga_loop_fuse (_F f)
Definition at line 16 of file fpga_loop_fuse.hpp.
fpga_loop_fuse_independent()
template<int _N = 1, typename _F > void cl::sycl::ext::intel::fpga_loop_fuse_independent (_F f)
Definition at line 21 of file fpga_loop_fuse.hpp.
fpga_reg() [1/2]
template<typename _T > std::enable_if<std::is_trivially_copyable<_T>::value, _T>::type cl::sycl::ext::intel::fpga_reg (_T t)
Definition at line 24 of file fpga_reg.hpp.
Referenced by intelfpga::fpga_reg().
fpga_reg() [2/2]
template<typename _T > std::enable_if<std::is_trivially_copyable<_T>::value == false, _T>::type cl::sycl::ext::intel::fpga_reg (_T t)
Definition at line 38 of file fpga_reg.hpp.
math_dsp_control()
template<Preference my_preference = Preference::DSP, Propagate my_propagate = Propagate::On, typename Function > void cl::sycl::ext::intel::math_dsp_control (Function f)
Preference: Control the hardware implementation of math operations in the lambda expression.
– DSP: Prefer math operations to be implemented in DSPs. – Softlogic: Prefer math operations to be implemented in soft-logic. – Compiler_default: Compiler determines the implementation based on the data type and math operation.
Propagate: Determine the propagation of 'Preference' to function calls in the lambda expression. – On: 'Preference' recursively applies to math operations in all function calls in the lambda expression. – Off: 'Preference' applies only to math operations directly inside the lambda expression. Math operations in function calls inside the lambda expression are not affected by 'Preference'.
Definition at line 72 of file fpga_dsp_control.hpp.
References math_prefer_dsp_no_propagate(), math_prefer_dsp_propagate(), math_prefer_softlogic_no_propagate(), and math_prefer_softlogic_propagate().
math_prefer_dsp_no_propagate()
template<typename Function > void cl::sycl::ext::intel::math_prefer_dsp_no_propagate (Function f)
Definition at line 32 of file fpga_dsp_control.hpp.
Referenced by math_dsp_control().
math_prefer_dsp_propagate()
template<typename Function > void cl::sycl::ext::intel::math_prefer_dsp_propagate (Function f)
Definition at line 23 of file fpga_dsp_control.hpp.
Referenced by math_dsp_control().
math_prefer_softlogic_no_propagate()
template<typename Function > void cl::sycl::ext::intel::math_prefer_softlogic_no_propagate (Function f)
Definition at line 51 of file fpga_dsp_control.hpp.
Referenced by math_dsp_control().
math_prefer_softlogic_propagate()
template<typename Function > void cl::sycl::ext::intel::math_prefer_softlogic_propagate (Function f)
Definition at line 42 of file fpga_dsp_control.hpp.
Referenced by math_dsp_control().
Variable Documentation
BURST_COALESCE
constexpr uint8_t cl::sycl::ext::intel::BURST_COALESCE = 0x1 constexpr
Definition at line 18 of file fpga_lsu.hpp.
CACHE
constexpr uint8_t cl::sycl::ext::intel::CACHE = 0x2 constexpr
Definition at line 19 of file fpga_lsu.hpp.
EMULATION_PLATFORM_NAME
constexpr auto cl::sycl::ext::intel::EMULATION_PLATFORM_NAME static constexpr
Initial value:
=
    "Intel(R) FPGA Emulation Platform for OpenCL(TM)"
Definition at line 43 of file fpga_device_selector.hpp.
HARDWARE_PLATFORM_NAME
constexpr auto cl::sycl::ext::intel::HARDWARE_PLATFORM_NAME static constexpr
Initial value:
=
    "Intel(R) FPGA SDK for OpenCL(TM)"
Definition at line 45 of file fpga_device_selector.hpp.
PREFETCH
constexpr uint8_t cl::sycl::ext::intel::PREFETCH = 0x8 constexpr
Definition at line 21 of file fpga_lsu.hpp.
STATICALLY_COALESCE
constexpr uint8_t cl::sycl::ext::intel::STATICALLY_COALESCE = 0x4 constexpr
Definition at line 20 of file fpga_lsu.hpp.