DPC++ Runtime: cl::sycl::level_zero Namespace Reference
cl::sycl::level_zero Namespace Reference
Enumerations
enum ownership { ownership::transfer, ownership::keep }
Functions
platform make_platform (pi_native_handle NativeHandle)
device make_device (const platform &Platform, pi_native_handle NativeHandle)
context make_context (const vector_class< device > &DeviceList, pi_native_handle NativeHandle, bool keep_ownership=false)
program make_program (const context &Context, pi_native_handle NativeHandle)
queue make_queue (const context &Context, pi_native_handle InteropHandle)
template<typename T , typename detail::enable_if_t< std::is_same< T, platform >::value > * = nullptr>
T make (typename interop< backend::level_zero, T >::type Interop)
template<typename T , typename detail::enable_if_t< std::is_same< T, device >::value > * = nullptr>
T make (const platform &Platform, typename interop< backend::level_zero, T >::type Interop)
template<typename T , typename std::enable_if< std::is_same< T, context >::value >::type * = nullptr>
T make (const vector_class< device > &DeviceList, typename interop< backend::level_zero, T >::type Interop, ownership Ownership=ownership::transfer)
Construction of SYCL context.
template<typename T , typename detail::enable_if_t< std::is_same< T, program >::value > * = nullptr>
T make (const context &Context, typename interop< backend::level_zero, T >::type Interop)
context make_context (const vector_class< device > &DeviceList, pi_native_handle NativeHandle)
Enumeration Type Documentation
ownership
enum cl::sycl::level_zero::ownership strong
Enumerator
transfer
keep
Definition at line 70 of file level_zero.hpp.
Function Documentation
make() [1/4]
template<typename T , typename detail::enable_if_t< std::is_same< T, program >::value > * = nullptr> T cl::sycl::level_zero::make (const context & Context, typename interop< backend::level_zero, T >::type Interop)
Definition at line 121 of file level_zero.hpp.
References make_program().
make() [2/4]
template<typename T , typename detail::enable_if_t< std::is_same< T, device >::value > * = nullptr> T cl::sycl::level_zero::make (const platform & Platform, typename interop< backend::level_zero, T >::type Interop)
Definition at line 95 of file level_zero.hpp.
References make_device().
make() [3/4]
template<typename T , typename std::enable_if< std::is_same< T, context >::value >::type * = nullptr> T cl::sycl::level_zero::make (const vector_class< device > & DeviceList, typename interop< backend::level_zero, T >::type Interop, ownership Ownership = ownership::transfer)
Construction of SYCL context.
Parameters
DeviceList is a vector of devices which must be encapsulated by created SYCL context. Provided devices and native context handle must be associated with the same platform.
Interop is a Level Zero native context handle.
Ownership (optional) specifies who will assume ownership of the native context handle. Default is that SYCL RT does, so it destroys the native handle when the created SYCL object goes out of life.
Definition at line 111 of file level_zero.hpp.
References make_context().
make() [4/4]
template<typename T , typename detail::enable_if_t< std::is_same< T, platform >::value > * = nullptr> T cl::sycl::level_zero::make (typename interop< backend::level_zero, T >::type Interop)
Definition at line 88 of file level_zero.hpp.
References make_platform().
make_context() [1/2]
context cl::sycl::level_zero::make_context (const vector_class< device > & DeviceList, pi_native_handle NativeHandle)
Definition at line 63 of file level_zero.cpp.
make_context() [2/2]
context cl::sycl::level_zero::make_context (const vector_class< device > & DeviceList, pi_native_handle NativeHandle, bool keep_ownership = false)
Definition at line 44 of file level_zero.cpp.
References cl::sycl::detail::getSyclObjImpl(), and piextContextCreateWithNativeHandle().
Referenced by make(), and cl::sycl::opencl::make_context().
make_device()
device cl::sycl::level_zero::make_device (const platform & Platform, pi_native_handle NativeHandle)
Definition at line 29 of file level_zero.cpp.
References cl::sycl::detail::getSyclObjImpl(), and piextDeviceCreateWithNativeHandle().
Referenced by make(), and cl::sycl::opencl::make_device().
make_platform()
platform cl::sycl::level_zero::make_platform (pi_native_handle NativeHandle)
Definition at line 23 of file level_zero.cpp.
Referenced by make(), and cl::sycl::opencl::make_platform().
make_program()
program cl::sycl::level_zero::make_program (const context & Context, pi_native_handle NativeHandle)
Definition at line 70 of file level_zero.cpp.
References cl::sycl::detail::getSyclObjImpl().
Referenced by make().
make_queue()
queue cl::sycl::level_zero::make_queue (const context & Context, pi_native_handle InteropHandle)
Definition at line 81 of file level_zero.cpp.
References cl::sycl::detail::getSyclObjImpl().
Referenced by cl::sycl::opencl::make_queue().