DPC++ Runtime: sycl::_V1::ext::intel::experimental::detail Namespace Reference
sycl::_V1::ext::intel::experimental::detail Namespace Reference
Classes
struct _MatchType
struct _GetValue
struct _GetValue< _Type, _T1, _T... >
struct GetOrDefaultValT
Typedefs
using defaultLatencyAnchorIdProperty = latency_anchor_id_key::value_t<-1 >
using defaultLatencyConstraintProperty = latency_constraint_key::value_t< 0, latency_control_type::none, 0 >
Functions
template<int count>
static constexpr void checkLevel1 ()
template<int count>
static constexpr void checkLevel2 ()
template<int count>
static constexpr void checkLevel3 ()
template<int count>
static constexpr void checkLevel4 ()
constexpr fp_mode operator& (const fp_mode &a, const fp_mode &b)
constexpr fp_mode operator^ (const fp_mode &a, const fp_mode &b)
constexpr bool isSet (const fp_mode &mode, const fp_mode &flag)
constexpr bool checkMutuallyExclusive (const fp_mode &mode)
constexpr fp_mode setDefaultValuesIfNeeded (fp_mode mode)
static std::vector< const char * > prepareOclocArgs (sycl::info::device_type DeviceType, device_arch DeviceArch, bool Is64Bit, const std::string &DeviceStepping, const std::string &UserArgs)
static std::vector< byte > compileToSPIRV (const std::string &Source, sycl::info::device_type DeviceType, device_arch DeviceArch, bool Is64Bit, const std::string &DeviceStepping, void *&CompileToSPIRVHandle, void *&FreeSPIRVOutputsHandle, const std::vector< std::string > &UserArgs)
Compiles the given source Source to SPIR-V IL and returns IL as a vector of bytes.
Typedef Documentation
defaultLatencyAnchorIdProperty
using sycl::_V1::ext::intel::experimental::detail::defaultLatencyAnchorIdProperty = typedef latency_anchor_id_key::value_t<-1>
Definition at line 51 of file fpga_utils.hpp.
defaultLatencyConstraintProperty
using sycl::_V1::ext::intel::experimental::detail::defaultLatencyConstraintProperty = typedef latency_constraint_key::value_t<0, latency_control_type::none, 0>
Definition at line 54 of file fpga_utils.hpp.
Function Documentation
checkLevel1()
template<int count> static constexpr void sycl::_V1::ext::intel::experimental::detail::checkLevel1 () static constexpr
Definition at line 40 of file cache_control_properties.hpp.
checkLevel2()
template<int count> static constexpr void sycl::_V1::ext::intel::experimental::detail::checkLevel2 () static constexpr
Definition at line 43 of file cache_control_properties.hpp.
checkLevel3()
template<int count> static constexpr void sycl::_V1::ext::intel::experimental::detail::checkLevel3 () static constexpr
Definition at line 46 of file cache_control_properties.hpp.
checkLevel4()
template<int count> static constexpr void sycl::_V1::ext::intel::experimental::detail::checkLevel4 () static constexpr
Definition at line 49 of file cache_control_properties.hpp.
checkMutuallyExclusive()
constexpr bool sycl::_V1::ext::intel::experimental::detail::checkMutuallyExclusive (const fp_mode & mode) constexpr
Definition at line 56 of file fp_control_kernel_properties.hpp.
References sycl::_V1::ext::intel::experimental::denorm_d_allow, sycl::_V1::ext::intel::experimental::denorm_f_allow, sycl::_V1::ext::intel::experimental::denorm_ftz, sycl::_V1::ext::intel::experimental::denorm_hf_allow, isSet(), sycl::_V1::ext::intel::experimental::round_downward, sycl::_V1::ext::intel::experimental::round_to_nearest, sycl::_V1::ext::intel::experimental::round_toward_zero, and sycl::_V1::ext::intel::experimental::round_upward.
compileToSPIRV()
static std::vector<byte> sycl::_V1::ext::intel::experimental::detail::compileToSPIRV (const std::string & Source, sycl::info::device_type DeviceType, device_arch DeviceArch, bool Is64Bit, const std::string & DeviceStepping, void *& CompileToSPIRVHandle, void *& FreeSPIRVOutputsHandle, const std::vector< std::string > & UserArgs) static
Compiles the given source Source to SPIR-V IL and returns IL as a vector of bytes.
Parameters
Source - Either OpenCL or CM source code.
DeviceType - SYCL device type, e.g. cpu, gpu, accelerator, etc.
DeviceArch - More detailed info on the target device architecture.
Is64Bit - If set to true, specifies the 64-bit architecture. Otherwise, 32-bit is assumed.
DeviceStepping - implementation specific target device stepping.
CompileToSPIRVHandle - Output parameter. It is set to the address of the library function doing the compilation.
FreeSPIRVOutputsHandle - Output parameter. It is set to the address of the library function freeing memory allocated during the compilation.
UserArgs - User's options to ocloc compiler.
Definition at line 85 of file online_compiler.cpp.
isSet()
constexpr bool sycl::_V1::ext::intel::experimental::detail::isSet (const fp_mode & mode, const fp_mode & flag) constexpr
Definition at line 53 of file fp_control_kernel_properties.hpp.
Referenced by checkMutuallyExclusive().
operator&()
constexpr fp_mode sycl::_V1::ext::intel::experimental::detail::operator& (const fp_mode & a, const fp_mode & b) constexpr
Definition at line 45 of file fp_control_kernel_properties.hpp.
operator^()
constexpr fp_mode sycl::_V1::ext::intel::experimental::detail::operator^ (const fp_mode & a, const fp_mode & b) constexpr
Definition at line 49 of file fp_control_kernel_properties.hpp.
prepareOclocArgs()
static std::vector<const char *> sycl::_V1::ext::intel::experimental::detail::prepareOclocArgs (sycl::info::device_type DeviceType, device_arch DeviceArch, bool Is64Bit, const std::string & DeviceStepping, const std::string & UserArgs) static
Definition at line 23 of file online_compiler.cpp.
References sycl::_V1::ext::intel::experimental::device_arch::gpu_gen11, sycl::_V1::ext::intel::experimental::device_arch::gpu_gen12, sycl::_V1::ext::intel::experimental::device_arch::gpu_gen9, and sycl::_V1::ext::intel::experimental::device_arch::gpu_gen9_5.
Referenced by sycl::_V1::ext::__SYCL2020_DEPRECATED().
setDefaultValuesIfNeeded()
constexpr fp_mode sycl::_V1::ext::intel::experimental::detail::setDefaultValuesIfNeeded (fp_mode mode) constexpr
Definition at line 73 of file fp_control_kernel_properties.hpp.
References sycl::_V1::ext::intel::experimental::denorm_d_allow, sycl::_V1::ext::intel::experimental::denorm_f_allow, sycl::_V1::ext::intel::experimental::denorm_ftz, sycl::_V1::ext::intel::experimental::denorm_hf_allow, sycl::_V1::ext::intel::experimental::round_downward, sycl::_V1::ext::intel::experimental::round_to_nearest, sycl::_V1::ext::intel::experimental::round_toward_zero, and sycl::_V1::ext::intel::experimental::round_upward.