DPC++ Runtime: sycl::_V1::detail::reduction Namespace Reference
sycl::_V1::detail::reduction Namespace Reference
Namespaces
aux_krn
main_krn
Classes
struct InitMemKrn
struct MainKrn
struct AuxKrn
Enumerations
enum class strategy : int {
auto_select , group_reduce_and_last_wg_detection , local_atomic_and_atomic_cross_wg , range_basic ,
group_reduce_and_atomic_cross_wg , local_mem_tree_and_atomic_cross_wg , group_reduce_and_multiple_kernels , basic ,
multi
}
Functions
void finalizeHandler (handler &CGH)
template<class FunctorTy >
void withAuxHandler (handler &CGH, FunctorTy Func)
template<int Dims>
item< Dims, false > getDelinearizedItem (range< Dims > Range, id< Dims > Id)
Enumeration Type Documentation
strategy
enum sycl::_V1::detail::reduction::strategy : int strong
Enumerator
auto_select
group_reduce_and_last_wg_detection
local_atomic_and_atomic_cross_wg
range_basic
group_reduce_and_atomic_cross_wg
local_mem_tree_and_atomic_cross_wg
group_reduce_and_multiple_kernels
basic
multi
Definition at line 33 of file reduction_forward.hpp.
Function Documentation
finalizeHandler()
void sycl::_V1::detail::reduction::finalizeHandler (handler & CGH) inline
Definition at line 1165 of file reduction.hpp.
Referenced by sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run().
getDelinearizedItem()
template<int Dims> item<Dims, false> sycl::_V1::detail::reduction::getDelinearizedItem (range< Dims > Range, id< Dims > Id)
Definition at line 55 of file reduction_forward.hpp.
Referenced by sycl::_V1::detail::reduction_parallel_for().
withAuxHandler()
template<class FunctorTy > void sycl::_V1::detail::reduction::withAuxHandler (handler & CGH, FunctorTy Func)
Definition at line 1166 of file reduction.hpp.
References sycl::_V1::handler::depends_on().
Referenced by sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run(), and sycl::_V1::detail::reduction_impl_algo< T, BinaryOperation, Dims, Extent, ExplicitIdentity, RedOutVar >::withInitializedMem().