DPC++ Runtime: cl::sycl::ONEAPI::detail Namespace Reference
cl::sycl::ONEAPI::detail Namespace Reference
Classes
class __sycl_reduction_aux_kernel
class __sycl_reduction_main_kernel
These are the forward declaration for the classes that help to create names for additional kernels.
struct AreAllButLastReductions
Predicate returning true if all template type parameters except the last one are reductions.
struct AreAllButLastReductions< T >
Helper specialization of AreAllButLastReductions for one element only.
class atomic_ref_base
class atomic_ref_impl
class atomic_ref_impl< T *, DefaultOrder, DefaultScope, AddressSpace >
class atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >
class atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >
struct bit_equal
struct bit_equal< double >
struct bit_equal< float >
struct bit_equal< T, typename detail::enable_if_t< std::is_integral< T >::value > >
struct EmptyReductionPredicate
class filter_selector_impl
struct FilterElement
struct get_reduction_aux_kernel_name_t
struct get_reduction_main_kernel_name_t
Helper structs to get additional kernel name types based on given Name and additional template parameters helping to distinguish kernels.
struct has_known_identity_impl
struct IsNonUsmReductionPredicate
struct known_identity_impl
struct known_identity_impl< BinaryOperation, AccumulatorT, typename std::enable_if< IsMaximumIdentityOp< AccumulatorT, BinaryOperation >::value >::type >
Returns minimal possible value as identity for MAX operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, typename std::enable_if< IsMinimumIdentityOp< AccumulatorT, BinaryOperation >::value >::type >
Returns maximal possible value as identity for MIN operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, typename std::enable_if< IsOneIdentityOp< AccumulatorT, BinaryOperation >::value >::type >
Returns one as identify for MULTIPLY operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, typename std::enable_if< IsOnesIdentityOp< AccumulatorT, BinaryOperation >::value >::type >
Returns bit image consisting of all ones as identity for AND operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, typename std::enable_if< IsZeroIdentityOp< AccumulatorT, BinaryOperation >::value >::type >
Returns zero as identity for ADD, OR, XOR operations.
struct known_identity_impl< BinaryOperation, half, typename std::enable_if< IsOneIdentityOp< half, BinaryOperation >::value >::type >
struct known_identity_impl< BinaryOperation, half, typename std::enable_if< IsZeroIdentityOp< half, BinaryOperation >::value >::type >
struct memory_order_traits
struct memory_order_traits< memory_order::acq_rel >
struct memory_order_traits< memory_order::relaxed >
struct memory_order_traits< memory_order::seq_cst >
class reducer
Class that is used to represent objects that are passed to user's lambda functions and representing users' reduction variable.
class reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >
Specialization of the generic class 'reducer'.
class reduction_impl
This class encapsulates the reduction variable/accessor, the reduction operator and an optional operator identity.
class reduction_impl_base
Base non-template class which is a base class for all reduction implementation classes.
Typedefs
using memory_order = cl::sycl::ONEAPI::memory_order
using memory_scope = cl::sycl::ONEAPI::memory_scope
template<typename T >
using IsValidAtomicType = bool_constant< std::is_arithmetic< T >::value||std::is_pointer< T >::value >
template<cl::sycl::access::address_space AS>
using IsValidAtomicAddressSpace = bool_constant< AS==access::address_space::global_space||AS==access::address_space::local_space||AS==access::address_space::global_device_space >
template<memory_order Order>
using IsValidDefaultOrder = bool_constant< Order==memory_order::relaxed||Order==memory_order::acq_rel||Order==memory_order::seq_cst >
template<typename T , class BinaryOperation >
using IsReduPlus = bool_constant< std::is_same< BinaryOperation, ONEAPI::plus< T > >::value||std::is_same< BinaryOperation, ONEAPI::plus< void > >::value >
template<typename T , class BinaryOperation >
using IsReduMultiplies = bool_constant< std::is_same< BinaryOperation, std::multiplies< T > >::value||std::is_same< BinaryOperation, std::multiplies< void > >::value >
template<typename T , class BinaryOperation >
using IsReduMinimum = bool_constant< std::is_same< BinaryOperation, ONEAPI::minimum< T > >::value||std::is_same< BinaryOperation, ONEAPI::minimum< void > >::value >
template<typename T , class BinaryOperation >
using IsReduMaximum = bool_constant< std::is_same< BinaryOperation, ONEAPI::maximum< T > >::value||std::is_same< BinaryOperation, ONEAPI::maximum< void > >::value >
template<typename T , class BinaryOperation >
using IsReduBitOR = bool_constant< std::is_same< BinaryOperation, ONEAPI::bit_or< T > >::value||std::is_same< BinaryOperation, ONEAPI::bit_or< void > >::value >
template<typename T , class BinaryOperation >
using IsReduBitXOR = bool_constant< std::is_same< BinaryOperation, ONEAPI::bit_xor< T > >::value||std::is_same< BinaryOperation, ONEAPI::bit_xor< void > >::value >
template<typename T , class BinaryOperation >
using IsReduBitAND = bool_constant< std::is_same< BinaryOperation, ONEAPI::bit_and< T > >::value||std::is_same< BinaryOperation, ONEAPI::bit_and< void > >::value >
template<typename T , class BinaryOperation >
using IsReduOptForFastAtomicFetch = bool_constant< is_sgeninteger< T >::value &&sycl::detail::IsValidAtomicType< T >::value &&(IsReduPlus< T, BinaryOperation >::value||IsReduMinimum< T, BinaryOperation >::value||IsReduMaximum< T, BinaryOperation >::value||IsReduBitOR< T, BinaryOperation >::value||IsReduBitXOR< T, BinaryOperation >::value||IsReduBitAND< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsReduOptForFastReduce = bool_constant<((is_sgeninteger< T >::value &&(sizeof(T)==32||sizeof(T)==64))||is_sgenfloat< T >::value) &&(IsReduPlus< T, BinaryOperation >::value||IsReduMinimum< T, BinaryOperation >::value||IsReduMaximum< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsZeroIdentityOp = bool_constant<(is_sgeninteger< T >::value &&(IsReduPlus< T, BinaryOperation >::value||IsReduBitOR< T, BinaryOperation >::value||IsReduBitXOR< T, BinaryOperation >::value))||(is_sgenfloat< T >::value &&IsReduPlus< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsOneIdentityOp = bool_constant<(is_sgeninteger< T >::value||is_sgenfloat< T >::value) &&IsReduMultiplies< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsOnesIdentityOp = bool_constant< is_sgeninteger< T >::value &&IsReduBitAND< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsMinimumIdentityOp = bool_constant<(is_sgeninteger< T >::value||is_sgenfloat< T >::value) &&IsReduMinimum< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsMaximumIdentityOp = bool_constant<(is_sgeninteger< T >::value||is_sgenfloat< T >::value) &&IsReduMaximum< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsKnownIdentityOp = bool_constant< IsZeroIdentityOp< T, BinaryOperation >::value||IsOneIdentityOp< T, BinaryOperation >::value||IsOnesIdentityOp< T, BinaryOperation >::value||IsMinimumIdentityOp< T, BinaryOperation >::value||IsMaximumIdentityOp< T, BinaryOperation >::value >
typedef struct sycl::detail::device_filter filter
Functions
template<typename KernelName , typename KernelType , int Dims, class Reduction >
enable_if_t< Reduction::has_fast_atomics > reduCGFunc (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &Redu)
template<typename KernelName , typename KernelType , int Dims, class Reduction >
enable_if_t<!Reduction::has_fast_atomics > reduCGFunc (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &Redu)
template<typename KernelName , typename KernelType , class Reduction >
enable_if_t<!Reduction::has_fast_atomics, size_t > reduAuxCGFunc (handler &CGH, size_t NWorkItems, size_t MaxWGSize, Reduction &Redu)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
template<typename KernelName , typename KernelType , int Dims, typename... Reductions, size_t... Is>
void reduCGFunc (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
template<typename KernelName , typename KernelType , typename... Reductions, size_t... Is>
size_t reduAuxCGFunc (handler &CGH, size_t NWorkItems, size_t MaxWGSize, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
template<typename KernelName , class Reduction >
std::enable_if_t<!Reduction::is_usm > reduSaveFinalResultToUserMem (handler &CGH, Reduction &Redu)
Copies the final reduction result kept in read-write accessor to user's accessor.
template<typename KernelName , class Reduction >
std::enable_if_t< Reduction::is_usm > reduSaveFinalResultToUserMem (handler &CGH, Reduction &Redu)
Copies the final reduction result kept in read-write accessor to user's USM memory.
template<typename... Reduction, size_t... Is>
shared_ptr_class< event > reduSaveFinalResultToUserMem (shared_ptr_class< detail::queue_impl > Queue, bool IsHost, std::tuple< Reduction... > &ReduTuple, std::index_sequence< Is... >)
Creates additional kernels that copy the accumulated/final results from reductions accessors to either user's accessor or user's USM memory.
template<typename Reduction , typename... RestT>
std::enable_if_t<!Reduction::is_usm > reduSaveFinalResultToUserMemHelper (std::vector< event > &Events, shared_ptr_class< detail::queue_impl > Queue, bool IsHost, Reduction &Redu, RestT... Rest)
size_t reduGetMaxWGSize (shared_ptr_class< queue_impl > Queue, size_t LocalMemBytesPerWorkItem)
template<typename... ReductionT, size_t... Is>
size_t reduGetMemPerWorkItem (std::tuple< ReductionT... > &ReduTuple, std::index_sequence< Is... >)
template<typename TupleT , std::size_t... Is>
std::tuple< std::tuple_element_t< Is, TupleT >... > tuple_select_elements (TupleT Tuple, std::index_sequence< Is... >)
Utility function: for the given tuple.
static constexpr std::memory_order getStdMemoryOrder (::cl::sycl::ONEAPI::memory_order order)
constexpr memory_order getLoadOrder (memory_order order)
size_t reduComputeWGSize (size_t NWorkItems, size_t MaxWGSize, size_t &NWorkGroups)
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool IsPow2WG>
enable_if_t< Reduction::has_fast_reduce &&Reduction::has_fast_atomics > reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &, typename Reduction::rw_accessor_type Out)
Implements a command group function that enqueues a kernel that calls user's lambda function KernelFunc and also does one iteration of reduction of elements computed in user's lambda function.
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool IsPow2WG>
enable_if_t<!Reduction::has_fast_reduce &&Reduction::has_fast_atomics > reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &, typename Reduction::rw_accessor_type Out)
Implements a command group function that enqueues a kernel that calls user's lambda function KernelFunc and also does one iteration of reduction of elements computed in user's lambda function.
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool IsPow2WG>
enable_if_t< Reduction::has_fast_reduce &&!Reduction::has_fast_atomics > reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &Redu, typename Reduction::rw_accessor_type Out)
Implements a command group function that enqueues a kernel that calls user's lambda function and does one iteration of reduction of elements in each of work-groups.
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool IsPow2WG>
enable_if_t<!Reduction::has_fast_reduce &&!Reduction::has_fast_atomics > reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &Redu, typename Reduction::rw_accessor_type Out)
Implements a command group function that enqueues a kernel that calls user's lambda function.
template<typename KernelName , typename KernelType , bool UniformWG, class Reduction , typename InputT , typename OutputT >
enable_if_t< Reduction::has_fast_reduce &&!Reduction::has_fast_atomics > reduAuxCGFuncImpl (handler &CGH, size_t NWorkItems, size_t NWorkGroups, size_t WGSize, Reduction &Redu, InputT In, OutputT Out)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
template<typename KernelName , typename KernelType , bool UniformPow2WG, class Reduction , typename InputT , typename OutputT >
enable_if_t<!Reduction::has_fast_reduce &&!Reduction::has_fast_atomics > reduAuxCGFuncImpl (handler &CGH, size_t NWorkItems, size_t NWorkGroups, size_t WGSize, Reduction &Redu, InputT In, OutputT Out)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
template<typename... Reductions, size_t... Is>
auto createReduLocalAccs (size_t Size, handler &CGH, std::index_sequence< Is... >)
For the given 'Reductions' types pack and indices enumerating only the reductions for which a local accessors are needed, this function creates those local accessors and returns a tuple consisting of them.
template<bool IsOneWG, typename... Reductions, size_t... Is>
auto createReduOutAccs (size_t NWorkGroups, handler &CGH, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
For the given 'Reductions' types pack and indices enumerating them this function either creates new temporary accessors for partial sums (if IsOneWG is false) or returns user's accessor/USM-pointer if (IsOneWG is true).
template<typename... Reductions, size_t... Is>
auto getReadAccsToPreviousPartialReds (handler &CGH, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
For the given 'Reductions' types pack and indices enumerating them this function returns accessors to buffers holding partial sums generated in the previous kernel invocation.
template<typename... Reductions, size_t... Is>
std::tuple< typename Reductions::result_type... > getReduIdentities (std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
template<typename... Reductions, size_t... Is>
std::tuple< typename Reductions::binary_operation... > getReduBOPs (std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
template<typename... Reductions, size_t... Is>
std::array< bool, sizeof...(Reductions)> getInitToIdentityProperties (std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
template<typename... Reductions, size_t... Is>
std::tuple< typename Reductions::reducer_type... > createReducers (std::tuple< typename Reductions::result_type... > Identities, std::tuple< typename Reductions::binary_operation... > BOPsTuple, std::index_sequence< Is... >)
template<typename KernelType , int Dims, typename... ReducerT, size_t... Is>
void callReduUserKernelFunc (KernelType KernelFunc, nd_item< Dims > NDIt, std::tuple< ReducerT... > &Reducers, std::index_sequence< Is... >)
template<bool Pow2WG, typename... LocalAccT, typename... ReducerT, typename... ResultT, size_t... Is>
void initReduLocalAccs (size_t LID, size_t WGSize, std::tuple< LocalAccT... > LocalAccs, const std::tuple< ReducerT... > &Reducers, const std::tuple< ResultT... > Identities, std::index_sequence< Is... >)
template<bool UniformPow2WG, typename... LocalAccT, typename... InputAccT, typename... ResultT, size_t... Is>
void initReduLocalAccs (size_t LID, size_t GID, size_t NWorkItems, size_t WGSize, std::tuple< InputAccT... > LocalAccs, std::tuple< LocalAccT... > InputAccs, const std::tuple< ResultT... > Identities, std::index_sequence< Is... >)
template<typename... LocalAccT, typename... BOPsT, size_t... Is>
void reduceReduLocalAccs (size_t IndexA, size_t IndexB, std::tuple< LocalAccT... > LocalAccs, std::tuple< BOPsT... > BOPs, std::index_sequence< Is... >)
template<bool Pow2WG, bool IsOneWG, typename... Reductions, typename... OutAccT, typename... LocalAccT, typename... BOPsT, typename... Ts, size_t... Is>
void writeReduSumsToOutAccs (size_t OutAccIndex, size_t WGSize, std::tuple< Reductions... > *, std::tuple< OutAccT... > OutAccs, std::tuple< LocalAccT... > LocalAccs, std::tuple< BOPsT... > BOPs, std::tuple< Ts... > IdentityVals, std::array< bool, sizeof...(Reductions)> IsInitializeToIdentity, std::index_sequence< Is... >)
constexpr std::index_sequence concat_sequences (std::index_sequence<>)
template<size_t I>
constexpr std::index_sequence< I > concat_sequences (std::index_sequence< I >)
template<size_t... Is, size_t... Js>
constexpr std::index_sequence< Is..., Js... > concat_sequences (std::index_sequence< Is... >, std::index_sequence< Js... >)
template<size_t... Is, size_t... Js, class... Rs>
constexpr auto concat_sequences (std::index_sequence< Is... >, std::index_sequence< Js... >, Rs...)
template<typename... T, typename FunctorT , size_t... Is, std::enable_if_t<(sizeof...(Is) > 0), int > Z = 0>
constexpr auto filterSequenceHelper (FunctorT, std::index_sequence< Is... >)
For each index 'I' from the given indices pack 'Is' this function initially creates a number of short index_sequences, where each of such short index sequences is either empty (if the given Functor returns false for the type T[I]) or 1 element 'I' (otherwise).
template<typename... T, typename FunctorT , size_t... Is>
constexpr auto filterSequence (FunctorT F, std::index_sequence< Is... > Indices)
For each index 'I' from the given indices pack 'Is' this function returns an index sequence consisting of only those 'I's for which the 'FunctorT' applied to 'T[I]' returns true.
template<typename KernelName , bool Pow2WG, bool IsOneWG, typename KernelType , int Dims, typename... Reductions, size_t... Is>
void reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... > ReduIndices)
void associateReduAccsWithHandlerHelper (handler &)
template<typename ReductionT >
void associateReduAccsWithHandlerHelper (handler &CGH, ReductionT &Redu)
template<typename ReductionT , typename... RestT, enable_if_t<(sizeof...(RestT) > 0), int > Z = 0>
void associateReduAccsWithHandlerHelper (handler &CGH, ReductionT &Redu, RestT &... Rest)
template<typename... Reductions, size_t... Is>
void associateReduAccsWithHandler (handler &CGH, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... >)
template<typename KernelName , typename KernelType , bool UniformPow2WG, bool IsOneWG, typename... Reductions, size_t... Is>
void reduAuxCGFuncImpl (handler &CGH, size_t NWorkItems, size_t NWorkGroups, size_t WGSize, std::tuple< Reductions... > &ReduTuple, std::index_sequence< Is... > ReduIndices)
void reduSaveFinalResultToUserMemHelper (std::vector< event > &, shared_ptr_class< detail::queue_impl >, bool)
template<typename Reduction , typename... RestT>
std::enable_if_t< Reduction::is_usm > reduSaveFinalResultToUserMemHelper (std::vector< event > &Events, shared_ptr_class< detail::queue_impl > Queue, bool IsHost, Reduction &, RestT... Rest)
template<typename Reduction >
size_t reduGetMemPerWorkItemHelper (Reduction &)
template<typename Reduction , typename... RestT>
size_t reduGetMemPerWorkItemHelper (Reduction &, RestT... Rest)
std::vector< std::string > tokenize (const std::string &Filter, const std::string &Delim)
filter create_filter (const std::string &Input)
size_t reduGetMaxWGSize (shared_ptr_class< sycl::detail::queue_impl > Queue, size_t LocalMemBytesPerWorkItem)
Typedef Documentation
filter
typedef struct sycl::detail::device_filter cl::sycl::ONEAPI::detail::filter
Definition at line 25 of file filter_selector_impl.hpp.
IsKnownIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsKnownIdentityOp = typedef bool_constant<IsZeroIdentityOp<T, BinaryOperation>::value || IsOneIdentityOp<T, BinaryOperation>::value || IsOnesIdentityOp<T, BinaryOperation>::value || IsMinimumIdentityOp<T, BinaryOperation>::value || IsMaximumIdentityOp<T, BinaryOperation>::value>
Definition at line 130 of file reduction.hpp.
IsMaximumIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsMaximumIdentityOp = typedef bool_constant<(is_sgeninteger<T>::value || is_sgenfloat<T>::value) && IsReduMaximum<T, BinaryOperation>::value>
Definition at line 122 of file reduction.hpp.
IsMinimumIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsMinimumIdentityOp = typedef bool_constant<(is_sgeninteger<T>::value || is_sgenfloat<T>::value) && IsReduMinimum<T, BinaryOperation>::value>
Definition at line 116 of file reduction.hpp.
IsOneIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsOneIdentityOp = typedef bool_constant<(is_sgeninteger<T>::value || is_sgenfloat<T>::value) && IsReduMultiplies<T, BinaryOperation>::value>
Definition at line 105 of file reduction.hpp.
IsOnesIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsOnesIdentityOp = typedef bool_constant<is_sgeninteger<T>::value && IsReduBitAND<T, BinaryOperation>::value>
Definition at line 110 of file reduction.hpp.
IsReduBitAND
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduBitAND = typedef bool_constant<std::is_same<BinaryOperation, ONEAPI::bit_and<T> >::value || std::is_same<BinaryOperation, ONEAPI::bit_and<void> >::value>
Definition at line 71 of file reduction.hpp.
IsReduBitOR
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduBitOR = typedef bool_constant<std::is_same<BinaryOperation, ONEAPI::bit_or<T> >::value || std::is_same<BinaryOperation, ONEAPI::bit_or<void> >::value>
Definition at line 61 of file reduction.hpp.
IsReduBitXOR
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduBitXOR = typedef bool_constant<std::is_same<BinaryOperation, ONEAPI::bit_xor<T> >::value || std::is_same<BinaryOperation, ONEAPI::bit_xor<void> >::value>
Definition at line 66 of file reduction.hpp.
IsReduMaximum
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduMaximum = typedef bool_constant<std::is_same<BinaryOperation, ONEAPI::maximum<T> >::value || std::is_same<BinaryOperation, ONEAPI::maximum<void> >::value>
Definition at line 56 of file reduction.hpp.
IsReduMinimum
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduMinimum = typedef bool_constant<std::is_same<BinaryOperation, ONEAPI::minimum<T> >::value || std::is_same<BinaryOperation, ONEAPI::minimum<void> >::value>
Definition at line 51 of file reduction.hpp.
IsReduMultiplies
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduMultiplies = typedef bool_constant<std::is_same<BinaryOperation, std::multiplies<T> >::value || std::is_same<BinaryOperation, std::multiplies<void> >::value>
Definition at line 46 of file reduction.hpp.
IsReduOptForFastAtomicFetch
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduOptForFastAtomicFetch = typedef bool_constant<is_sgeninteger<T>::value && sycl::detail::IsValidAtomicType<T>::value && (IsReduPlus<T, BinaryOperation>::value || IsReduMinimum<T, BinaryOperation>::value || IsReduMaximum<T, BinaryOperation>::value || IsReduBitOR<T, BinaryOperation>::value || IsReduBitXOR<T, BinaryOperation>::value || IsReduBitAND<T, BinaryOperation>::value)>
Definition at line 82 of file reduction.hpp.
IsReduOptForFastReduce
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduOptForFastReduce = typedef bool_constant<((is_sgeninteger<T>::value && (sizeof(T) == 32 || sizeof(T) == 64)) || is_sgenfloat<T>::value) && (IsReduPlus<T, BinaryOperation>::value || IsReduMinimum<T, BinaryOperation>::value || IsReduMaximum<T, BinaryOperation>::value)>
Definition at line 91 of file reduction.hpp.
IsReduPlus
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsReduPlus = typedef bool_constant<std::is_same<BinaryOperation, ONEAPI::plus<T> >::value || std::is_same<BinaryOperation, ONEAPI::plus<void> >::value>
Definition at line 41 of file reduction.hpp.
IsValidAtomicAddressSpace
template<cl::sycl::access::address_space AS> using cl::sycl::ONEAPI::detail::IsValidAtomicAddressSpace = typedef bool_constant<AS == access::address_space::global_space || AS == access::address_space::local_space || AS == access::address_space::global_device_space>
Definition at line 47 of file atomic_ref.hpp.
IsValidAtomicType
template<typename T > using cl::sycl::ONEAPI::detail::IsValidAtomicType = typedef bool_constant<std::is_arithmetic<T>::value || std::is_pointer<T>::value>
Definition at line 41 of file atomic_ref.hpp.
IsValidDefaultOrder
template<memory_order Order> using cl::sycl::ONEAPI::detail::IsValidDefaultOrder = typedef bool_constant<Order == memory_order::relaxed || Order == memory_order::acq_rel || Order == memory_order::seq_cst>
Definition at line 53 of file atomic_ref.hpp.
IsZeroIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::ONEAPI::detail::IsZeroIdentityOp = typedef bool_constant< (is_sgeninteger<T>::value && (IsReduPlus<T, BinaryOperation>::value || IsReduBitOR<T, BinaryOperation>::value || IsReduBitXOR<T, BinaryOperation>::value)) || (is_sgenfloat<T>::value && IsReduPlus<T, BinaryOperation>::value)>
Definition at line 99 of file reduction.hpp.
memory_order
using cl::sycl::ONEAPI::detail::memory_order = typedef cl::sycl::ONEAPI::memory_order
Definition at line 36 of file atomic_ref.hpp.
memory_scope
using cl::sycl::ONEAPI::detail::memory_scope = typedef cl::sycl::ONEAPI::memory_scope
Definition at line 37 of file atomic_ref.hpp.
Function Documentation
associateReduAccsWithHandler()
template<typename... Reductions, size_t... Is> void cl::sycl::ONEAPI::detail::associateReduAccsWithHandler (handler & CGH, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... >)
Definition at line 1623 of file reduction.hpp.
References associateReduAccsWithHandlerHelper().
Referenced by reduAuxCGFuncImpl().
associateReduAccsWithHandlerHelper() [1/3]
void cl::sycl::ONEAPI::detail::associateReduAccsWithHandlerHelper (handler &) inline
Definition at line 1607 of file reduction.hpp.
associateReduAccsWithHandlerHelper() [2/3]
template<typename ReductionT > void cl::sycl::ONEAPI::detail::associateReduAccsWithHandlerHelper (handler & CGH, ReductionT & Redu)
Definition at line 1610 of file reduction.hpp.
associateReduAccsWithHandlerHelper() [3/3]
template<typename ReductionT , typename... RestT, enable_if_t<(sizeof...(RestT) > 0), int > Z = 0> void cl::sycl::ONEAPI::detail::associateReduAccsWithHandlerHelper (handler & CGH, ReductionT & Redu, RestT &... Rest)
Definition at line 1616 of file reduction.hpp.
Referenced by associateReduAccsWithHandler().
callReduUserKernelFunc()
template<typename KernelType , int Dims, typename... ReducerT, size_t... Is> void cl::sycl::ONEAPI::detail::callReduUserKernelFunc (KernelType KernelFunc, nd_item< Dims > NDIt, std::tuple< ReducerT... > & Reducers, std::index_sequence< Is... >)
Definition at line 1351 of file reduction.hpp.
Referenced by reduCGFuncImpl().
concat_sequences() [1/4]
template<size_t I> constexpr std::index_sequence<I> cl::sycl::ONEAPI::detail::concat_sequences (std::index_sequence< I >) constexpr
Definition at line 1455 of file reduction.hpp.
concat_sequences() [2/4]
template<size_t... Is, size_t... Js> constexpr std::index_sequence<Is..., Js...> cl::sycl::ONEAPI::detail::concat_sequences (std::index_sequence< Is... > , std::index_sequence< Js... >) constexpr
Definition at line 1462 of file reduction.hpp.
concat_sequences() [3/4]
template<size_t... Is, size_t... Js, class... Rs> constexpr auto cl::sycl::ONEAPI::detail::concat_sequences (std::index_sequence< Is... > , std::index_sequence< Js... > , Rs...) constexpr
Definition at line 1468 of file reduction.hpp.
Referenced by filterSequenceHelper().
concat_sequences() [4/4]
constexpr std::index_sequence cl::sycl::ONEAPI::detail::concat_sequences (std::index_sequence<>) constexpr
Definition at line 1449 of file reduction.hpp.
create_filter()
filter cl::sycl::ONEAPI::detail::create_filter (const std::string & Input)
Definition at line 50 of file filter_selector_impl.cpp.
References cl::sycl::detail::device_filter::Backend, cl::sycl::detail::device_filter::DeviceNum, cl::sycl::detail::device_filter::DeviceType, cl::sycl::detail::device_filter::HasBackend, cl::sycl::detail::device_filter::HasDeviceNum, cl::sycl::detail::device_filter::HasDeviceType, PI_INVALID_VALUE, and tokenize().
Referenced by cl::sycl::ONEAPI::detail::filter_selector_impl::filter_selector_impl().
createReducers()
template<typename... Reductions, size_t... Is> std::tuple<typename Reductions::reducer_type...> cl::sycl::ONEAPI::detail::createReducers (std::tuple< typename Reductions::result_type... > Identities, std::tuple< typename Reductions::binary_operation... > BOPsTuple, std::index_sequence< Is... >)
Definition at line 1343 of file reduction.hpp.
Referenced by reduCGFuncImpl().
createReduLocalAccs()
template<typename... Reductions, size_t... Is> auto cl::sycl::ONEAPI::detail::createReduLocalAccs (size_t Size, handler & CGH, std::index_sequence< Is... >)
For the given 'Reductions' types pack and indices enumerating only the reductions for which a local accessors are needed, this function creates those local accessors and returns a tuple consisting of them.
Definition at line 1291 of file reduction.hpp.
Referenced by reduAuxCGFuncImpl(), and reduCGFuncImpl().
createReduOutAccs()
template<bool IsOneWG, typename... Reductions, size_t... Is> auto cl::sycl::ONEAPI::detail::createReduOutAccs (size_t NWorkGroups, handler & CGH, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... >)
For the given 'Reductions' types pack and indices enumerating them this function either creates new temporary accessors for partial sums (if IsOneWG is false) or returns user's accessor/USM-pointer if (IsOneWG is true).
Definition at line 1302 of file reduction.hpp.
filterSequence()
template<typename... T, typename FunctorT , size_t... Is> constexpr auto cl::sycl::ONEAPI::detail::filterSequence (FunctorT F, std::index_sequence< Is... > Indices) constexpr
For each index 'I' from the given indices pack 'Is' this function returns an index sequence consisting of only those 'I's for which the 'FunctorT' applied to 'T[I]' returns true.
Definition at line 1511 of file reduction.hpp.
References filterSequenceHelper().
Referenced by reduAuxCGFuncImpl().
filterSequenceHelper()
template<typename... T, typename FunctorT , size_t... Is, std::enable_if_t<(sizeof...(Is) > 0), int > Z = 0> constexpr auto cl::sycl::ONEAPI::detail::filterSequenceHelper (FunctorT , std::index_sequence< Is... >) constexpr
For each index 'I' from the given indices pack 'Is' this function initially creates a number of short index_sequences, where each of such short index sequences is either empty (if the given Functor returns false for the type T[I]) or 1 element 'I' (otherwise).
After that this function concatenates those short sequences into one and returns the result sequence.
Definition at line 1495 of file reduction.hpp.
References concat_sequences().
Referenced by filterSequence().
getInitToIdentityProperties()
template<typename... Reductions, size_t... Is> std::array<bool, sizeof...(Reductions)> cl::sycl::ONEAPI::detail::getInitToIdentityProperties (std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... >)
Definition at line 1336 of file reduction.hpp.
Referenced by reduAuxCGFuncImpl(), and reduCGFuncImpl().
getLoadOrder()
constexpr memory_order cl::sycl::ONEAPI::detail::getLoadOrder (memory_order order) inline constexpr
Definition at line 72 of file atomic_ref.hpp.
References cl::sycl::ONEAPI::memory_order_acq_rel, cl::sycl::ONEAPI::memory_order_acquire, cl::sycl::ONEAPI::memory_order_relaxed, cl::sycl::ONEAPI::memory_order_release, and cl::sycl::ONEAPI::memory_order_seq_cst.
Referenced by cl::sycl::ONEAPI::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >::fetch_add(), cl::sycl::ONEAPI::detail::atomic_ref_impl< T *, DefaultOrder, DefaultScope, AddressSpace >::fetch_add(), cl::sycl::ONEAPI::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_max(), cl::sycl::ONEAPI::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >::fetch_max(), cl::sycl::ONEAPI::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_min(), cl::sycl::ONEAPI::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >::fetch_min(), cl::sycl::ONEAPI::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >::fetch_sub(), and cl::sycl::ONEAPI::detail::atomic_ref_impl< T *, DefaultOrder, DefaultScope, AddressSpace >::fetch_sub().
getReadAccsToPreviousPartialReds()
template<typename... Reductions, size_t... Is> auto cl::sycl::ONEAPI::detail::getReadAccsToPreviousPartialReds (handler & CGH, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... >)
For the given 'Reductions' types pack and indices enumerating them this function returns accessors to buffers holding partial sums generated in the previous kernel invocation.
Definition at line 1314 of file reduction.hpp.
Referenced by reduAuxCGFuncImpl().
getReduBOPs()
template<typename... Reductions, size_t... Is> std::tuple<typename Reductions::binary_operation...> cl::sycl::ONEAPI::detail::getReduBOPs (std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... >)
Definition at line 1330 of file reduction.hpp.
Referenced by reduAuxCGFuncImpl(), and reduCGFuncImpl().
getReduIdentities()
template<typename... Reductions, size_t... Is> std::tuple<typename Reductions::result_type...> cl::sycl::ONEAPI::detail::getReduIdentities (std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... >)
Definition at line 1323 of file reduction.hpp.
Referenced by reduAuxCGFuncImpl(), and reduCGFuncImpl().
getStdMemoryOrder()
static constexpr std::memory_order cl::sycl::ONEAPI::detail::getStdMemoryOrder (::cl::sycl::ONEAPI::memory_order order) inline static constexpr
Definition at line 65 of file atomic_enums.hpp.
References cl::sycl::ONEAPI::memory_order_acq_rel, cl::sycl::ONEAPI::memory_order_acquire, cl::sycl::ONEAPI::memory_order_relaxed, cl::sycl::ONEAPI::memory_order_release, and cl::sycl::ONEAPI::memory_order_seq_cst.
initReduLocalAccs() [1/2]
template<bool UniformPow2WG, typename... LocalAccT, typename... InputAccT, typename... ResultT, size_t... Is> void cl::sycl::ONEAPI::detail::initReduLocalAccs (size_t LID, size_t GID, size_t NWorkItems, size_t WGSize, std::tuple< InputAccT... > LocalAccs, std::tuple< LocalAccT... > InputAccs, const std::tuple< ResultT... > Identities, std::index_sequence< Is... >)
Definition at line 1377 of file reduction.hpp.
initReduLocalAccs() [2/2]
template<bool Pow2WG, typename... LocalAccT, typename... ReducerT, typename... ResultT, size_t... Is> void cl::sycl::ONEAPI::detail::initReduLocalAccs (size_t LID, size_t WGSize, std::tuple< LocalAccT... > LocalAccs, const std::tuple< ReducerT... > & Reducers, const std::tuple< ResultT... > Identities, std::index_sequence< Is... >)
Definition at line 1359 of file reduction.hpp.
reduAuxCGFunc() [1/2]
template<typename KernelName , typename KernelType , class Reduction > enable_if_t<!Reduction::has_fast_atomics, size_t > cl::sycl::ONEAPI::detail::reduAuxCGFunc (handler & CGH, size_t NWorkItems, size_t MaxWGSize, Reduction & Redu)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
At the end of each work-group the partial sum is written to a global buffer. The function returns the number of the newly generated partial sums.
Definition at line 1224 of file reduction.hpp.
References reduComputeWGSize().
reduAuxCGFunc() [2/2]
template<typename KernelName , typename KernelType , typename... Reductions, size_t... Is> size_t cl::sycl::ONEAPI::detail::reduAuxCGFunc (handler & CGH, size_t NWorkItems, size_t MaxWGSize, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... > ReduIndices)
Definition at line 1698 of file reduction.hpp.
References reduComputeWGSize().
reduAuxCGFuncImpl() [1/3]
template<typename KernelName , typename KernelType , bool UniformWG, class Reduction , typename InputT , typename OutputT > enable_if_t<Reduction::has_fast_reduce && !Reduction::has_fast_atomics> cl::sycl::ONEAPI::detail::reduAuxCGFuncImpl (handler & CGH, size_t NWorkItems, size_t NWorkGroups, size_t WGSize, Reduction & Redu, InputT In, OutputT Out)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
This version uses ONEAPI::reduce() algorithm to reduce elements in each of work-groups. At the end of each work-groups the partial sum is written to a global buffer.
Briefly: aux kernel, ONEAPI:reduce(), reproducible results, FP + ADD/MIN/MAX
Definition at line 1128 of file reduction.hpp.
References cl::sycl::handler::parallel_for(), and cl::sycl::INTEL::gpu::reduce().
reduAuxCGFuncImpl() [2/3]
template<typename KernelName , typename KernelType , bool UniformPow2WG, class Reduction , typename InputT , typename OutputT > enable_if_t<!Reduction::has_fast_reduce && !Reduction::has_fast_atomics> cl::sycl::ONEAPI::detail::reduAuxCGFuncImpl (handler & CGH, size_t NWorkItems, size_t NWorkGroups, size_t WGSize, Reduction & Redu, InputT In, OutputT Out)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
This version uses tree-reduction algorithm to reduce elements in each of work-groups. At the end of each work-group the partial sum is written to a global buffer.
Briefly: aux kernel, tree-reduction, CUSTOM types/ops.
Definition at line 1163 of file reduction.hpp.
References cl::sycl::handler::parallel_for().
reduAuxCGFuncImpl() [3/3]
template<typename KernelName , typename KernelType , bool UniformPow2WG, bool IsOneWG, typename... Reductions, size_t... Is> void cl::sycl::ONEAPI::detail::reduAuxCGFuncImpl (handler & CGH, size_t NWorkItems, size_t NWorkGroups, size_t WGSize, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... > ReduIndices)
Definition at line 1631 of file reduction.hpp.
References associateReduAccsWithHandler(), createReduLocalAccs(), filterSequence(), getInitToIdentityProperties(), getReadAccsToPreviousPartialReds(), getReduBOPs(), getReduIdentities(), and reduceReduLocalAccs().
reduceReduLocalAccs()
template<typename... LocalAccT, typename... BOPsT, size_t... Is> void cl::sycl::ONEAPI::detail::reduceReduLocalAccs (size_t IndexA, size_t IndexB, std::tuple< LocalAccT... > LocalAccs, std::tuple< BOPsT... > BOPs, std::index_sequence< Is... >)
Definition at line 1404 of file reduction.hpp.
Referenced by reduAuxCGFuncImpl(), and reduCGFuncImpl().
reduCGFunc() [1/3]
template<typename KernelName , typename KernelType , int Dims, class Reduction > enable_if_t< Reduction::has_fast_atomics > cl::sycl::ONEAPI::detail::reduCGFunc (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & Redu)
Definition at line 963 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_local_range().
reduCGFunc() [2/3]
template<typename KernelName , typename KernelType , int Dims, class Reduction > enable_if_t<!Reduction::has_fast_atomics > cl::sycl::ONEAPI::detail::reduCGFunc (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & Redu)
Definition at line 1098 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_group_range(), and cl::sycl::nd_range< dimensions >::get_local_range().
reduCGFunc() [3/3]
template<typename KernelName , typename KernelType , int Dims, typename... Reductions, size_t... Is> void cl::sycl::ONEAPI::detail::reduCGFunc (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... > ReduIndices)
Definition at line 1579 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_group_range(), and cl::sycl::nd_range< dimensions >::get_local_range().
reduCGFuncImpl() [1/5]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool IsPow2WG> enable_if_t<Reduction::has_fast_reduce && Reduction::has_fast_atomics> cl::sycl::ONEAPI::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & , typename Reduction::rw_accessor_type Out)
Implements a command group function that enqueues a kernel that calls user's lambda function KernelFunc and also does one iteration of reduction of elements computed in user's lambda function.
This version uses ONEAPI::reduce() algorithm to reduce elements in each of work-groups, then it calls fast SYCL atomic operations to update the given reduction variable Out.
Briefly: calls user's lambda, ONEAPI::reduce() + atomic, INT + ADD/MIN/MAX.
Definition at line 885 of file reduction.hpp.
References cl::sycl::handler::parallel_for(), and cl::sycl::INTEL::gpu::reduce().
reduCGFuncImpl() [2/5]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool IsPow2WG> enable_if_t<!Reduction::has_fast_reduce && Reduction::has_fast_atomics> cl::sycl::ONEAPI::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & , typename Reduction::rw_accessor_type Out)
Implements a command group function that enqueues a kernel that calls user's lambda function KernelFunc and also does one iteration of reduction of elements computed in user's lambda function.
This version uses tree-reduction algorithm to reduce elements in each of work-groups, then it calls fast SYCL atomic operations to update user's reduction variable.
Briefly: calls user's lambda, tree-reduction + atomic, INT + AND/OR/XOR.
Definition at line 912 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_local_range(), and cl::sycl::handler::parallel_for().
reduCGFuncImpl() [3/5]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool IsPow2WG> enable_if_t<Reduction::has_fast_reduce && !Reduction::has_fast_atomics> cl::sycl::ONEAPI::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & Redu, typename Reduction::rw_accessor_type Out)
Implements a command group function that enqueues a kernel that calls user's lambda function and does one iteration of reduction of elements in each of work-groups.
This version uses ONEAPI::reduce() algorithm to reduce elements in each of work-groups. At the end of each work-groups the partial sum is written to a global buffer.
Briefly: user's lambda, ONEAPI:reduce(), FP + ADD/MIN/MAX.
Definition at line 1002 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_group_range(), cl::sycl::handler::parallel_for(), and cl::sycl::INTEL::gpu::reduce().
reduCGFuncImpl() [4/5]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool IsPow2WG> enable_if_t<!Reduction::has_fast_reduce && !Reduction::has_fast_atomics> cl::sycl::ONEAPI::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & Redu, typename Reduction::rw_accessor_type Out)
Implements a command group function that enqueues a kernel that calls user's lambda function.
Parameters
KernelFunc and does one iteration of reduction of elements in each of work-groups. This version uses tree-reduction algorithm to reduce elements in each of work-groups. At the end of each work-group the partial sum is written to a global buffer.
Briefly: user's lambda, tree-reduction, CUSTOM types/ops.
Definition at line 1040 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_group_range(), cl::sycl::nd_range< dimensions >::get_local_range(), and cl::sycl::handler::parallel_for().
reduCGFuncImpl() [5/5]
template<typename KernelName , bool Pow2WG, bool IsOneWG, typename KernelType , int Dims, typename... Reductions, size_t... Is> void cl::sycl::ONEAPI::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, std::tuple< Reductions... > & ReduTuple, std::index_sequence< Is... > ReduIndices)
Definition at line 1517 of file reduction.hpp.
References callReduUserKernelFunc(), createReducers(), createReduLocalAccs(), cl::sycl::nd_range< dimensions >::get_group_range(), cl::sycl::nd_range< dimensions >::get_local_range(), getInitToIdentityProperties(), getReduBOPs(), getReduIdentities(), and reduceReduLocalAccs().
reduComputeWGSize()
size_t cl::sycl::ONEAPI::detail::reduComputeWGSize (size_t NWorkItems, size_t MaxWGSize, size_t & NWorkGroups)
Definition at line 19 of file reduction.cpp.
Referenced by reduAuxCGFunc().
reduGetMaxWGSize() [1/2]
size_t cl::sycl::ONEAPI::detail::reduGetMaxWGSize (shared_ptr_class< queue_impl > Queue, size_t LocalMemBytesPerWorkItem)
Referenced by cl::sycl::handler::parallel_for().
reduGetMaxWGSize() [2/2]
size_t cl::sycl::ONEAPI::detail::reduGetMaxWGSize (shared_ptr_class< sycl::detail::queue_impl > Queue, size_t LocalMemBytesPerWorkItem)
Definition at line 52 of file reduction.cpp.
References cl::sycl::device::get_info().
reduGetMemPerWorkItem()
template<typename... ReductionT, size_t... Is> size_t cl::sycl::ONEAPI::detail::reduGetMemPerWorkItem (std::tuple< ReductionT... > & ReduTuple, std::index_sequence< Is... >)
Definition at line 1783 of file reduction.hpp.
References reduGetMemPerWorkItemHelper().
Referenced by cl::sycl::handler::parallel_for().
reduGetMemPerWorkItemHelper() [1/2]
template<typename Reduction > size_t cl::sycl::ONEAPI::detail::reduGetMemPerWorkItemHelper (Reduction &)
Definition at line 1772 of file reduction.hpp.
reduGetMemPerWorkItemHelper() [2/2]
template<typename Reduction , typename... RestT> size_t cl::sycl::ONEAPI::detail::reduGetMemPerWorkItemHelper (Reduction & , RestT... Rest)
Definition at line 1777 of file reduction.hpp.
Referenced by reduGetMemPerWorkItem().
reduSaveFinalResultToUserMem() [1/3]
template<typename KernelName , class Reduction > std::enable_if_t<!Reduction::is_usm > cl::sycl::ONEAPI::detail::reduSaveFinalResultToUserMem (handler & CGH, Reduction & Redu)
Copies the final reduction result kept in read-write accessor to user's accessor.
This method is not called for user's read-write accessors requiring update-write to it.
Definition at line 1258 of file reduction.hpp.
References cl::sycl::handler::copy().
reduSaveFinalResultToUserMem() [2/3]
template<typename KernelName , class Reduction > std::enable_if_t< Reduction::is_usm > cl::sycl::ONEAPI::detail::reduSaveFinalResultToUserMem (handler & CGH, Reduction & Redu)
Copies the final reduction result kept in read-write accessor to user's USM memory.
Definition at line 1274 of file reduction.hpp.
References cl::sycl::handler::single_task().
reduSaveFinalResultToUserMem() [3/3]
template<typename... Reduction, size_t... Is> shared_ptr_class< event > cl::sycl::ONEAPI::detail::reduSaveFinalResultToUserMem (shared_ptr_class< detail::queue_impl > Queue, bool IsHost, std::tuple< Reduction... > & ReduTuple, std::index_sequence< Is... >)
Creates additional kernels that copy the accumulated/final results from reductions accessors to either user's accessor or user's USM memory.
Returns the event to the last kernel copying data or nullptr if no additional kernels created.
Definition at line 1761 of file reduction.hpp.
References reduSaveFinalResultToUserMemHelper().
Referenced by cl::sycl::handler::parallel_for().
reduSaveFinalResultToUserMemHelper() [1/3]
void cl::sycl::ONEAPI::detail::reduSaveFinalResultToUserMemHelper (std::vector< event > & , shared_ptr_class< detail::queue_impl > , bool) inline
Definition at line 1724 of file reduction.hpp.
reduSaveFinalResultToUserMemHelper() [2/3]
template<typename Reduction , typename... RestT> std::enable_if_t<Reduction::is_usm> cl::sycl::ONEAPI::detail::reduSaveFinalResultToUserMemHelper (std::vector< event > & Events, shared_ptr_class< detail::queue_impl > Queue, bool IsHost, Reduction & , RestT... Rest)
Definition at line 1729 of file reduction.hpp.
Referenced by reduSaveFinalResultToUserMem(), and reduSaveFinalResultToUserMemHelper().
reduSaveFinalResultToUserMemHelper() [3/3]
template<typename Reduction , typename... RestT> std::enable_if_t<!Reduction::is_usm > cl::sycl::ONEAPI::detail::reduSaveFinalResultToUserMemHelper (std::vector< event > & Events, shared_ptr_class< detail::queue_impl > Queue, bool IsHost, Reduction & Redu, RestT... Rest)
Definition at line 1738 of file reduction.hpp.
References cl::sycl::handler::copy(), cl::sycl::handler::depends_on(), and reduSaveFinalResultToUserMemHelper().
tokenize()
std::vector<std::string> cl::sycl::ONEAPI::detail::tokenize (const std::string & Filter, const std::string & Delim)
Definition at line 27 of file filter_selector_impl.cpp.
Referenced by create_filter(), and cl::sycl::ONEAPI::detail::filter_selector_impl::filter_selector_impl().
tuple_select_elements()
template<typename TupleT , std::size_t... Is> std::tuple< std::tuple_element_t< Is, TupleT >... > cl::sycl::ONEAPI::detail::tuple_select_elements (TupleT Tuple, std::index_sequence< Is... >)
Utility function: for the given tuple.
Parameters
Tuple the function returns a new tuple consisting of only elements indexed by the index sequence.
Definition at line 1792 of file reduction.hpp.
Referenced by cl::sycl::handler::parallel_for().
writeReduSumsToOutAccs()
template<bool Pow2WG, bool IsOneWG, typename... Reductions, typename... OutAccT, typename... LocalAccT, typename... BOPsT, typename... Ts, size_t... Is> void cl::sycl::ONEAPI::detail::writeReduSumsToOutAccs (size_t OutAccIndex, size_t WGSize, std::tuple< Reductions... > * , std::tuple< OutAccT... > OutAccs, std::tuple< LocalAccT... > LocalAccs, std::tuple< BOPsT... > BOPs, std::tuple< Ts... > IdentityVals, std::array< bool, sizeof...(Reductions)> IsInitializeToIdentity, std::index_sequence< Is... >)
Definition at line 1416 of file reduction.hpp.