DPC++ Runtime: cl::sycl::detail::usm Namespace Reference
cl::sycl::detail::usm Namespace Reference
Functions
void * alignedAlloc (size_t Alignment, size_t Bytes, const context &Ctxt, const device &Dev, cl::sycl::usm::alloc Kind, const code_location &CL)
void * alignedAllocHost (size_t Alignment, size_t Bytes, const context &Ctxt, cl::sycl::usm::alloc Kind, const code_location &CL)
void free (void *Ptr, const context &Ctxt, const code_location &CL)
void * alignedAlloc (size_t Alignment, size_t Size, const context &Ctxt, const device &Dev, alloc Kind, const detail::code_location &CL, const property_list &PropList={})
void * alignedAllocHost (size_t Alignment, size_t Size, const context &Ctxt, alloc Kind)
void free (void *Ptr, const context &Ctxt)
void * alignedAlloc (size_t Alignment, size_t Size, const context &Ctxt, const device &Dev, alloc Kind)
Function Documentation
alignedAlloc() [1/3]
void* cl::sycl::detail::usm::alignedAlloc (size_t Alignment, size_t Bytes, const context & Ctxt, const device & Dev, cl::sycl::usm::alloc Kind, const code_location & CL)
Referenced by cl::sycl::detail::aligned_allocator< T >::allocate().
alignedAlloc() [2/3]
void* cl::sycl::detail::usm::alignedAlloc (size_t Alignment, size_t Size, const context & Ctxt, const device & Dev, alloc Kind)
Definition at line 207 of file usm_impl.cpp.
Referenced by cl::sycl::aligned_alloc(), cl::sycl::aligned_alloc_device(), cl::sycl::aligned_alloc_shared(), cl::sycl::malloc(), cl::sycl::malloc_device(), and cl::sycl::malloc_shared().
alignedAlloc() [3/3]
void* cl::sycl::detail::usm::alignedAlloc (size_t Alignment, size_t Size, const context & Ctxt, const device & Dev, alloc Kind, const detail::code_location & CL, const property_list & PropList = {})
Definition at line 94 of file usm_impl.cpp.
alignedAllocHost() [1/2]
void * cl::sycl::detail::usm::alignedAllocHost (size_t Alignment, size_t Bytes, const context & Ctxt, cl::sycl::usm::alloc Kind, const code_location & CL)
Definition at line 46 of file usm_impl.cpp.
References cl::sycl::detail::aligned_allocator< T >::allocate(), cl::sycl::detail::plugin::call_nocheck(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::context::is_host(), PI_INVALID_VALUE, PI_SUCCESS, piextUSMHostAlloc(), and XPTI_CREATE_TRACEPOINT.
alignedAllocHost() [2/2]
void* cl::sycl::detail::usm::alignedAllocHost (size_t Alignment, size_t Size, const context & Ctxt, alloc Kind)
Definition at line 198 of file usm_impl.cpp.
Referenced by cl::sycl::aligned_alloc(), cl::sycl::aligned_alloc_host(), cl::sycl::malloc(), and cl::sycl::malloc_host().
free() [1/2]
void cl::sycl::detail::usm::free (void * Ptr, const context & Ctxt)
Definition at line 203 of file usm_impl.cpp.
References cl::sycl::free().
free() [2/2]
void cl::sycl::detail::usm::free (void * Ptr, const context & Ctxt, const code_location & CL)
Definition at line 181 of file usm_impl.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::getSyclObjImpl(), cl::sycl::context::is_host(), piextUSMFree(), and XPTI_CREATE_TRACEPOINT.
Referenced by cl::sycl::detail::OSUtil::alignedFree(), and _pi_mem::mem_::buffer_mem_::unmap().