DPC++ Runtime: ze_api_generator Namespace Reference
ze_api_generator Namespace Reference
Functions
def camel_to_snake (src)
def snake_to_camel (src)
def extract_ze_apis (header)
Variables
header = f.read()
Function Documentation
camel_to_snake()
def ze_api_generator.camel_to_snake (src)
Definition at line 5 of file ze_api_generator.py.
Referenced by extract_ze_apis().
extract_ze_apis()
def ze_api_generator.extract_ze_apis (header)
Emit file with contents of
_ZE_API(api_name, api_domain, cb, param_type)
Definition at line 14 of file ze_api_generator.py.
References camel_to_snake(), and snake_to_camel().
snake_to_camel()
def ze_api_generator.snake_to_camel (src)
Definition at line 9 of file ze_api_generator.py.
Referenced by extract_ze_apis().
Variable Documentation
header
ze_api_generator.header = f.read()
Definition at line 47 of file ze_api_generator.py.