DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::cplx::detail Namespace Reference
sycl::_V1::ext::oneapi::experimental::cplx::detail Namespace Reference
TRAITS.
Classes
struct __numeric_type
struct __numeric_type< void >
class __promote_imp
class __promote_imp< _A1, _A2, _A3, true >
class __promote_imp< _A1, _A2, void, true >
class __promote_imp< _A1, void, void, true >
class __promote
struct __libcpp_complex_overload_traits
struct __libcpp_complex_overload_traits< _Tp, true, false >
struct __libcpp_complex_overload_traits< _Tp, false, true >
Typedefs
template<bool _Val>
using _BoolConstant = std::integral_constant< bool, _Val >
template<class _Tp , class _Up >
using _IsNotSame = _BoolConstant<!__is_same(_Tp, _Up)>
Functions
template<class _Tp >
_SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > __sqr (const complex< _Tp > &__x)
Detailed Description
TRAITS.
Typedef Documentation
_BoolConstant
template<bool _Val> using sycl::_V1::ext::oneapi::experimental::cplx::detail::_BoolConstant = typedef std::integral_constant<bool, _Val>
Definition at line 30 of file complex_math.hpp.
_IsNotSame
template<class _Tp , class _Up > using sycl::_V1::ext::oneapi::experimental::cplx::detail::_IsNotSame = typedef _BoolConstant<!__is_same(_Tp, _Up)>
Definition at line 33 of file complex_math.hpp.
Function Documentation
__sqr()
template<class _Tp > _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::cplx::detail::__sqr (const complex< _Tp > & __x)
Definition at line 349 of file complex_math.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::acos(), sycl::_V1::ext::oneapi::experimental::acosh(), and sycl::_V1::ext::oneapi::experimental::asinh().