DPC++ Runtime: cl::sycl::detail Namespace Reference
cl::sycl::detail Namespace Reference
Namespaces
__sycl_service_kernel__
device_global_map
enqueue_kernel_launch
gtl
gvl
half_impl
host_half_impl
pi
sub_group
usm
Classes
class __image_array_slice__
class __pf_kernel_wrapper
class accessor_common
class AccessorBaseHost
class AccessorImplDevice
class AccessorImplHost
class aligned_allocator
class AllocaCommand
The alloca command enqueues allocation of instance of memory object on Host or underlying framework.
class AllocaCommandBase
Base class for memory allocation commands.
class AllocaSubBufCommand
The AllocaSubBuf command enqueues creation of sub-buffer of memory object.
class ArgDesc
class array
struct array_fill_helper
struct array_fill_helper< Kind, Idx, T >
struct array_fill_helper< Kind, Idx, T, Args... >
struct AssertHappened
struct Assigner
struct Assigner< 0 >
class atomic_ref_base
class atomic_ref_impl
class atomic_ref_impl< T *, DefaultOrder, DefaultScope, AddressSpace >
class atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >
class atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >
class auto_name
This class is the default KernelName template parameter type for kernel invocation APIs such as single_task.
struct BackendInput
struct BackendInput< backend::ext_oneapi_cuda, buffer< DataT, Dimensions, AllocatorT > >
struct BackendInput< backend::ext_oneapi_cuda, context >
struct BackendInput< backend::ext_oneapi_cuda, device >
struct BackendInput< backend::ext_oneapi_cuda, event >
struct BackendInput< backend::ext_oneapi_cuda, queue >
struct BackendInput< backend::ext_oneapi_level_zero, context >
struct BackendInput< backend::ext_oneapi_level_zero, device >
struct BackendInput< backend::ext_oneapi_level_zero, event >
struct BackendInput< backend::ext_oneapi_level_zero, kernel >
struct BackendInput< backend::ext_oneapi_level_zero, kernel_bundle< State > >
struct BackendInput< backend::ext_oneapi_level_zero, platform >
struct BackendInput< backend::ext_oneapi_level_zero, queue >
struct BackendInput< backend::opencl, buffer< DataT, Dimensions, AllocatorT > >
struct BackendInput< backend::opencl, context >
struct BackendInput< backend::opencl, device >
struct BackendInput< backend::opencl, event >
struct BackendInput< backend::opencl, kernel >
struct BackendInput< backend::opencl, kernel_bundle< State > >
struct BackendInput< backend::opencl, platform >
struct BackendInput< backend::opencl, queue >
struct BackendReturn
struct BackendReturn< backend::ext_oneapi_cuda, buffer< DataT, Dimensions, AllocatorT > >
struct BackendReturn< backend::ext_oneapi_cuda, context >
struct BackendReturn< backend::ext_oneapi_cuda, device >
struct BackendReturn< backend::ext_oneapi_cuda, event >
struct BackendReturn< backend::ext_oneapi_cuda, queue >
struct BackendReturn< backend::ext_oneapi_level_zero, context >
struct BackendReturn< backend::ext_oneapi_level_zero, device >
struct BackendReturn< backend::ext_oneapi_level_zero, event >
struct BackendReturn< backend::ext_oneapi_level_zero, kernel >
struct BackendReturn< backend::ext_oneapi_level_zero, kernel_bundle< State > >
struct BackendReturn< backend::ext_oneapi_level_zero, platform >
struct BackendReturn< backend::ext_oneapi_level_zero, queue >
struct BackendReturn< backend::opencl, buffer< DataT, Dimensions, AllocatorT > >
struct BackendReturn< backend::opencl, context >
struct BackendReturn< backend::opencl, device >
struct BackendReturn< backend::opencl, event >
struct BackendReturn< backend::opencl, kernel >
struct BackendReturn< backend::opencl, kernel_bundle< State > >
struct BackendReturn< backend::opencl, platform >
struct BackendReturn< backend::opencl, queue >
class BaseCLTypeConverter
struct bit_equal
struct bit_equal< double >
struct bit_equal< float >
struct bit_equal< T, typename detail::enable_if_t< std::is_integral< T >::value > >
struct Boolean
struct Boolean< 1 >
class buffer_impl
class Builder
class CG
Base class for all types of command groups.
class CGAdviseUSM
"Advise USM" command group class.
class CGBarrier
class CGCopy
"Copy memory" command group class.
class CGCopyUSM
"Copy USM" command group class.
class CGExecKernel
"Execute kernel" command group class.
class CGFill
"Fill memory" command group class.
class CGFillUSM
"Fill USM" command group class.
class CGHostTask
class CGInteropTask
class CGPrefetchUSM
"Prefetch USM" command group class.
class CGUpdateHost
"Update host" command group class.
struct change_base_type
struct change_base_type< vec< T, N >, B >
struct check_fn_signature
struct check_fn_signature< F, RetT(Args...)>
struct check_fp_support
struct check_fp_support< info::device::double_fp_config >
struct check_fp_support< info::device::half_fp_config >
class CircularBuffer
struct CmpCStr
struct code_location
class Command
The Command class represents some action that needs to be performed on one or more memory objects.
class context_impl
struct convert_data_type_impl
struct convert_data_type_impl< T, B, enable_if_t< is_sgentype< T >::value, T > >
struct convert_data_type_impl< T, B, enable_if_t< is_vgentype< T >::value, T > >
struct copy_cv_qualifiers
struct copy_cv_qualifiers_impl
struct copy_cv_qualifiers_impl< const T, R >
struct copy_cv_qualifiers_impl< const volatile T, R >
struct copy_cv_qualifiers_impl< volatile T, R >
class DataLessProperty
class DataLessPropertyBase
struct DecoratedType
struct DecoratedType< ElementType, access::address_space::constant_space >
struct DecoratedType< ElementType, access::address_space::generic_space >
struct DecoratedType< ElementType, access::address_space::global_device_space >
struct DecoratedType< ElementType, access::address_space::global_host_space >
struct DecoratedType< ElementType, access::address_space::global_space >
struct DecoratedType< ElementType, access::address_space::local_space >
struct DecoratedType< ElementType, access::address_space::private_space >
struct DefaultContextReleaseHandler
struct DepDesc
Dependency between two commands.
struct device_filter
class device_filter_list
class device_image_impl
class device_image_plain
class device_impl
struct DeviceGlobalMapEntry
class DispatchHostTask
class DynRTDeviceBinaryImage
class EmptyCommand
The empty command does nothing during enqueue.
struct EnqueueResultT
Result of command enqueueing.
struct EqualByNameComp
struct EqualTo
class event_impl
class ExecCGCommand
The exec CG command enqueues execution of kernel or explicit memory operation.
struct ExtendedMemberT
struct find_type
struct find_type< empty_type_list, C, T >
struct function_traits
struct function_traits< Ret(Args...)>
struct get
struct get< 0 >
struct get_context_info
struct get_context_info< info::context::atomic_memory_order_capabilities >
struct get_device_info
struct get_device_info< bool, info::device::ext_intel_mem_channel >
struct get_device_info< bool, info::device::kernel_kernel_pipe_support >
struct get_device_info< bool, info::device::queue_profiling >
struct get_device_info< bool, info::device::usm_device_allocations >
struct get_device_info< bool, info::device::usm_host_allocations >
struct get_device_info< bool, info::device::usm_restricted_shared_allocations >
struct get_device_info< bool, info::device::usm_shared_allocations >
struct get_device_info< bool, info::device::usm_system_allocations >
struct get_device_info< device, info::device::parent_device >
struct get_device_info< id< 1 >, info::device::ext_oneapi_max_work_groups_1d >
struct get_device_info< id< 2 >, info::device::ext_oneapi_max_work_groups_2d >
struct get_device_info< id< 3 >, info::device::ext_oneapi_max_work_groups_3d >
struct get_device_info< id< 3 >, info::device::max_work_item_sizes >
struct get_device_info< id< 3 >, param >
struct get_device_info< info::partition_affinity_domain, info::device::partition_type_affinity_domain >
struct get_device_info< info::partition_property, info::device::partition_type_property >
struct get_device_info< platform, param >
struct get_device_info< size_t, info::device::ext_oneapi_max_global_work_groups >
struct get_device_info< std::string, info::device::version >
struct get_device_info< std::string, param >
struct get_device_info< std::vector< info::execution_capability >, info::device::execution_capabilities >
struct get_device_info< std::vector< info::fp_config >, info::device::single_fp_config >
struct get_device_info< std::vector< info::fp_config >, param >
struct get_device_info< std::vector< info::partition_affinity_domain >, info::device::partition_affinity_domains >
struct get_device_info< std::vector< info::partition_property >, info::device::partition_properties >
struct get_device_info< std::vector< kernel_id >, info::device::built_in_kernel_ids >
struct get_device_info< std::vector< memory_order >, info::device::atomic_memory_order_capabilities >
struct get_device_info< std::vector< memory_scope >, info::device::atomic_memory_scope_capabilities >
struct get_device_info< std::vector< size_t >, info::device::sub_group_sizes >
struct get_device_info< std::vector< std::string >, info::device::built_in_kernels >
struct get_device_info< std::vector< std::string >, info::device::extensions >
struct get_device_info< T, info::device::parent_device >
struct get_device_info_string
struct get_event_info
struct get_event_profiling_info
struct get_kernel_device_specific_info
struct get_kernel_device_specific_info< cl::sycl::range< 3 >, Param >
struct get_kernel_device_specific_info_with_input
struct get_kernel_info
struct get_kernel_info< cl_uint, Param >
struct get_kernel_info< std::string, Param >
struct get_kernel_name_t
Helper struct to get a kernel name type based on given Name and Type types: if Name is undefined (is a auto_name) then Type becomes the Name.
struct get_kernel_wrapper_name_t
struct get_platform_info
struct get_platform_info< std::string, param >
struct get_platform_info< std::vector< std::string >, info::platform::extensions >
class GetOp
class GetScalarOp
struct GetSpirvMemoryScope
struct GetSpirvMemoryScope< access::address_space::global_device_space >
struct GetSpirvMemoryScope< access::address_space::global_space >
struct GetSpirvMemoryScope< access::address_space::local_space >
class GlobalHandler
Wrapper class for global data structures with non-trivial destructors.
struct GreaterEqualTo
struct GreaterThan
struct group_barrier_scope
struct group_barrier_scope< sycl::group< D > >
struct group_barrier_scope< sycl::sub_group >
class handler_impl
struct has_known_identity_impl
struct HashCStr
class HostKernel
class HostKernelBase
class HostProfilingInfo
Profiling info for the host execution.
class HostTask
class image_accessor
class image_impl
struct InitializedVal
struct InitializedVal< 1, T >
struct InitializedVal< 2, T >
struct InitializedVal< 3, T >
struct InlineVariableHelper
struct interop
struct interop< backend::ext_oneapi_cuda, accessor< DataT, Dimensions, AccessMode, access::target::constant_buffer, access::placeholder::false_t > >
struct interop< backend::ext_oneapi_cuda, accessor< DataT, Dimensions, AccessMode, access::target::device, access::placeholder::false_t > >
struct interop< backend::ext_oneapi_cuda, context >
struct interop< backend::ext_oneapi_cuda, device >
struct interop< backend::ext_oneapi_cuda, event >
struct interop< backend::ext_oneapi_cuda, queue >
struct interop< backend::ext_oneapi_level_zero, accessor< DataT, Dimensions, AccessMode, access::target::constant_buffer, access::placeholder::false_t > >
struct interop< backend::ext_oneapi_level_zero, accessor< DataT, Dimensions, AccessMode, access::target::device, access::placeholder::false_t > >
struct interop< backend::ext_oneapi_level_zero, accessor< DataT, Dimensions, AccessMode, access::target::image, access::placeholder::false_t > >
struct interop< backend::ext_oneapi_level_zero, context >
struct interop< backend::ext_oneapi_level_zero, device >
struct interop< backend::ext_oneapi_level_zero, event >
struct interop< backend::ext_oneapi_level_zero, kernel >
struct interop< backend::ext_oneapi_level_zero, platform >
struct interop< backend::ext_oneapi_level_zero, queue >
struct interop< backend::opencl, accessor< DataT, Dimensions, AccessMode, access::target::constant_buffer, access::placeholder::false_t > >
struct interop< backend::opencl, accessor< DataT, Dimensions, AccessMode, access::target::device, access::placeholder::false_t > >
struct interop< backend::opencl, accessor< DataT, Dimensions, AccessMode, access::target::image, access::placeholder::false_t > >
struct interop< backend::opencl, context >
struct interop< backend::opencl, device >
struct interop< backend::opencl, event >
struct interop< backend::opencl, platform >
struct interop< backend::opencl, queue >
struct InteropFeatureSupportMap
struct InteropFeatureSupportMap< backend::ext_oneapi_level_zero >
struct InteropFeatureSupportMap< backend::opencl >
class InteropTask
struct is_address_space_compliant
struct is_address_space_compliant_impl
struct is_address_space_compliant_impl< multi_ptr< T, Space >, SpaceList >
struct is_address_space_compliant_impl< T *, SpaceList >
struct is_arithmetic
struct is_bool
struct is_complex
struct is_contained
struct is_contained< T, empty_type_list >
struct is_contained_value
struct is_contained_value< T, V, value_list< T > >
struct is_empty_type_list
struct is_floating_point
struct is_floating_point_impl
struct is_floating_point_impl< half >
struct is_generic_group
struct is_group
struct is_group< group< Dimensions > >
struct is_integral
struct is_native_op
struct is_output_iterator
struct is_output_iterator< T, output_iterator_requirements< T > >
struct is_pointer
struct is_pointer_impl
struct is_pointer_impl< multi_ptr< T, Space > >
struct is_pointer_impl< T * >
class is_same_vector_size
class is_same_vector_size_impl
class is_same_vector_size_impl< FirstSize >
class is_same_vector_size_impl< FirstSize, T, Args... >
struct is_scalar_arithmetic
struct is_scalar_bool
struct is_sub_group
struct is_sub_group< ext::oneapi::sub_group >
struct is_type_size_double_of
struct is_type_size_equal
struct is_type_size_greater
struct is_type_size_half_of
struct is_type_size_less
struct is_vec
struct is_vec< cl::sycl::vec< T, N > >
struct is_vector_arithmetic
struct is_vector_bool
struct IsCompileTimePropertyInstance
struct IsCompileTimePropertyInstance< ext::intel::property::buffer_location::instance< I > >
struct IsCompileTimePropertyInstance< ext::oneapi::property::no_alias::instance<> >
struct IsCompileTimePropertyInstance< ext::oneapi::property::no_offset::instance<> >
struct IsCxPropertyList
struct IsCxPropertyList< ext::oneapi::accessor_property_list< Props... > >
struct IsCxPropertyList< ext::oneapi::accessor_property_list<> >
struct IsDeprecatedDeviceCopyable
struct IsSwizzleOp
struct IsSwizzleOp< cl::sycl::detail::SwizzleOp< VecT, OperationLeftT, OperationRightT, OperationCurrentT, Indexes... > >
struct IsValidAtomicAddressSpace
struct IsValidAtomicRefAddressSpace
struct IsValidAtomicRefType
struct IsValidAtomicType
struct IsValidCoordDataT
struct IsValidCoordDataT< 1, T >
struct IsValidCoordDataT< 2, T >
struct IsValidCoordDataT< 3, T >
struct IsWorkGroupInfo
struct IsWorkGroupInfo< info::kernel_device_specific::compile_work_group_size >
struct IsWorkGroupInfo< info::kernel_device_specific::ext_codeplay_num_regs >
struct IsWorkGroupInfo< info::kernel_device_specific::global_work_size >
struct IsWorkGroupInfo< info::kernel_device_specific::preferred_work_group_size_multiple >
struct IsWorkGroupInfo< info::kernel_device_specific::private_mem_size >
struct IsWorkGroupInfo< info::kernel_device_specific::work_group_size >
struct ItemBase
struct ItemBase< Dims, false >
struct ItemBase< Dims, true >
class kernel_bundle_impl
class kernel_bundle_plain
class kernel_id_impl
class kernel_impl
struct kernel_param_desc_t
struct KernelInfo
struct KernelLambdaHasKernelHandlerArgT
class KernelProgramCache
struct known_identity_impl
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsFalseIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns false as identity for LOGICAL OR operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsMaximumIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns minimal possible value as identity for MAX operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsMinimumIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns maximal possible value as identity for MIN operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsOneIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns one as identify for MULTIPLY operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsOnesIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns bit image consisting of all ones as identity for AND operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsTrueIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns true as identity for LOGICAL AND operations.
struct known_identity_impl< BinaryOperation, AccumulatorT, std::enable_if_t< IsZeroIdentityOp< AccumulatorT, BinaryOperation >::value > >
Returns zero as identity for ADD, OR, XOR operations.
struct known_identity_impl< BinaryOperation, half, std::enable_if_t< IsOneIdentityOp< half, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, half, std::enable_if_t< IsZeroIdentityOp< half, BinaryOperation >::value > >
struct known_identity_impl< BinaryOperation, vec< sycl::half, NumElements >, std::enable_if_t< IsZeroIdentityOp< vec< sycl::half, NumElements >, BinaryOperation >::value > >
class LeavesCollection
A wrapper for CircularBuffer class along with collection for host accessor's EmptyCommands.
struct LessByHash
struct LessByNameComp
struct LessEqualTo
struct LessThan
class LocalAccessorBaseDevice
class LocalAccessorBaseHost
class LocalAccessorImplHost
class LockCacheItem
class Locked
Represents a reference to value with appropriate lock acquired.
struct LogicalAnd
struct LogicalOr
struct LShift
struct make_larger
struct make_larger_impl
struct make_larger_impl< T, enable_if_t< is_contained< T, gtl::scalar_floating_list >::value, T > >
struct make_larger_impl< T, enable_if_t< is_contained< T, gtl::scalar_signed_integer_list >::value, T > >
struct make_larger_impl< T, enable_if_t< is_contained< T, gtl::scalar_unsigned_integer_list >::value, T > >
struct make_larger_impl< vec< T, N >, vec< T, N > >
struct make_signed
struct make_signed_impl
struct make_signed_impl< T, enable_if_t< is_contained< T, gtl::scalar_integer_list >::value, T > >
struct make_signed_impl< T, enable_if_t< is_contained< T, gtl::vector_integer_list >::value, T > >
struct make_signed_impl< T, enable_if_t<!is_contained< T, gtl::integer_list >::value, T > >
struct make_type_impl
struct make_type_impl< vec< T, N >, TL >
struct make_unsigned
struct make_unsigned_impl
struct make_unsigned_impl< T, enable_if_t< is_contained< T, gtl::scalar_integer_list >::value, T > >
struct make_unsigned_impl< T, enable_if_t< is_contained< T, gtl::vector_integer_list >::value, T > >
struct make_unsigned_impl< T, enable_if_t<!is_contained< T, gtl::integer_list >::value, T > >
class MapMemObject
The map command enqueues mapping of device memory onto host memory.
class MemCpyCommand
The mem copy command enqueues memory copy between two instances of memory object.
class MemCpyCommandHost
The mem copy host command enqueues memory copy between two instances of memory object.
struct MemObjRecord
Memory Object Record.
struct memory_order_traits
struct memory_order_traits< memory_order::acq_rel >
struct memory_order_traits< memory_order::relaxed >
struct memory_order_traits< memory_order::seq_cst >
class MemoryManager
struct nan_types
struct nan_types< T, enable_if_t< is_contained< T, gtl::unsigned_int_list >::value, T > >
struct nan_types< T, enable_if_t< is_contained< T, gtl::unsigned_long_integer_list >::value, T > >
struct nan_types< T, enable_if_t< is_contained< T, gtl::unsigned_short_list >::value, T > >
struct NDLoop
Generates an NDIMS-dimensional perfect loop nest.
struct NDLoopIterateImpl
Helper class for the NDLoop.
struct NDLoopIterateImpl< NDIMS, 0, LoopBoundTy, FuncTy, LoopIndexTy >
class NDRDescT
struct NotEqualTo
class OSUtil
Groups the OS-dependent services.
class PersistentDeviceCodeCache
struct PiApiArgTuple
class platform_impl
struct PlatformUtil
class plugin
The plugin class provides a unified interface to the underlying low-level runtimes for the device-agnostic SYCL runtime.
class program_impl
class ProgramManager
class PropertyListBase
class PropertyWithData
class PropertyWithDataBase
class queue_impl
struct RelationalReturnType
struct RelationalTestForSignBitType
struct RelConverter
struct RelConverter< T, typename detail::enable_if_t< TryToGetElementType< T >::value > >
struct RelConverter< T, typename detail::enable_if_t<!TryToGetElementType< T >::value > >
class ReleaseCommand
The release command enqueues release of a memory object instance allocated on Host or underlying framework.
struct remove_AS
struct remove_pointer
struct remove_pointer_impl
struct remove_pointer_impl< multi_ptr< T, Space > >
struct remove_pointer_impl< T * >
class RoundedRangeKernel
class RoundedRangeKernelWithKH
struct RShift
class RTDeviceBinaryImage
class sampler_impl
class Scheduler
DPC++ graph scheduler class.
struct select_cl_mptr_or_vector_or_scalar
struct select_cl_mptr_or_vector_or_scalar< T, typename detail::enable_if_t< is_genptr< T >::value &&!std::is_pointer< T >::value > >
struct select_cl_mptr_or_vector_or_scalar< T, typename detail::enable_if_t<!is_genptr< T >::value||std::is_pointer< T >::value > >
struct select_cl_vector_or_scalar
struct select_cl_vector_or_scalar< T, typename detail::enable_if_t< is_vgentype< T >::value > >
struct select_cl_vector_or_scalar< T, typename detail::enable_if_t<!is_vgentype< T >::value > >
class spec_constant_impl
struct SpecConstantInfo
class SpinLock
SpinLock is a synchronization primitive, that uses atomic variable and causes thread trying acquire lock wait in loop while repeatedly check if the lock is available.
class stream_impl
class SwizzleOp
struct sycl_to_pi
struct sycl_to_pi< bool >
struct sycl_to_pi< device >
struct sycl_to_pi< platform >
class SYCLCategory
class SYCLConfig
class SYCLConfig< SYCL_BE >
class SYCLConfig< SYCL_DEVICE_FILTER >
class SYCLConfig< SYCL_DISABLE_PARALLEL_FOR_RANGE_ROUNDING >
class SYCLConfig< SYCL_ENABLE_DEFAULT_CONTEXTS >
class SYCLConfig< SYCL_PARALLEL_FOR_RANGE_ROUNDING_PARAMS >
class SYCLConfig< SYCL_PARALLEL_FOR_RANGE_ROUNDING_TRACE >
class SYCLConfig< SYCL_PI_TRACE >
class SYCLConfig< SYCL_QUEUE_THREAD_POOL_SIZE >
class SYCLConfig< SYCL_RT_WARNING_LEVEL >
class SYCLConfigBase
class SYCLMemObjAllocator
class SYCLMemObjAllocatorHolder
class SYCLMemObjI
class SYCLMemObjT
class Sync
Groups and provides access to all the locks used the SYCL runtime.
struct TargetToAS
struct TargetToAS< access::target::constant_buffer >
struct TargetToAS< access::target::local >
struct TermPositions
class ThreadPool
class TryToGetElementType
struct TryToGetNumElements
struct TryToGetNumElements< T, typename detail::enable_if_t< TryToGetVectorT< T >::value > >
struct TryToGetNumElements< T, typename detail::enable_if_t<!TryToGetVectorT< T >::value > >
class TryToGetPointerT
class TryToGetPointerVecT
class TryToGetVectorT
struct tuple
struct tuple< T, Ts... >
struct tuple<>
struct tuple_element
struct tuple_element< 0, tuple< T, Rest... > >
struct tuple_element< N, tuple< T, Rest... > >
struct TupleCopyAssignableValueHolder
struct TupleCopyAssignableValueHolder< T, false >
struct TupleValueHolder
struct type_list
struct type_list< H, T... >
struct type_list< type_list< H, T... >, T2... >
struct type_list<>
struct TypeHelper
class UnMapMemObject
The unmap command removes mapping of host memory onto device memory.
class UpdateHostRequirementCommand
struct value_list
struct value_list< T >
struct value_list< T, H, V... >
struct vec_helper
struct vector_alignment
struct vector_alignment_impl
struct vector_element
struct vector_element_impl
struct vector_element_impl< vec< T, N > >
struct vector_size
struct vector_size_impl
struct vector_size_impl< vec< T, N > >
class XPTIRegistry
Typedefs
template<typename T >
using IsPropertyListT = typename std::is_base_of< PropertyListBase, T >
template<typename T >
using IsRunTimePropertyListT = typename std::is_same< ext::oneapi::accessor_property_list<>, T >
using memory_order = cl::sycl::memory_order
using memory_scope = cl::sycl::memory_scope
template<memory_order Order>
using IsValidDefaultOrder = bool_constant< Order==memory_order::relaxed||Order==memory_order::acq_rel||Order==memory_order::seq_cst >
using AccessorImplPtr = std::shared_ptr< AccessorImplHost >
using LocalAccessorImplPtr = std::shared_ptr< LocalAccessorImplHost >
using Requirement = AccessorImplHost
using KernelSetId = size_t
template<typename T >
using is_floatn = is_contained< T, gtl::vector_float_list >
template<typename T >
using is_genfloatf = is_contained< T, gtl::float_list >
template<typename T >
using is_doublen = is_contained< T, gtl::vector_double_list >
template<typename T >
using is_genfloatd = is_contained< T, gtl::double_list >
template<typename T >
using is_halfn = is_contained< T, gtl::vector_half_list >
template<typename T >
using is_genfloath = is_contained< T, gtl::half_list >
template<typename T >
using is_genfloat = is_contained< T, gtl::floating_list >
template<typename T >
using is_sgenfloat = is_contained< T, gtl::scalar_floating_list >
template<typename T >
using is_vgenfloat = is_contained< T, gtl::vector_floating_list >
template<typename T >
using is_gengeofloat = is_contained< T, gtl::geo_float_list >
template<typename T >
using is_gengeodouble = is_contained< T, gtl::geo_double_list >
template<typename T >
using is_gengeohalf = is_contained< T, gtl::geo_half_list >
template<typename T >
using is_vgengeofloat = is_contained< T, gtl::vector_geo_float_list >
template<typename T >
using is_vgengeodouble = is_contained< T, gtl::vector_geo_double_list >
template<typename T >
using is_vgengeohalf = is_contained< T, gtl::vector_geo_half_list >
template<typename T >
using is_sgengeo = is_contained< T, gtl::scalar_geo_list >
template<typename T >
using is_vgengeo = is_contained< T, gtl::vector_geo_list >
template<typename T >
using is_gencrossfloat = is_contained< T, gtl::cross_float_list >
template<typename T >
using is_gencrossdouble = is_contained< T, gtl::cross_double_list >
template<typename T >
using is_gencrosshalf = is_contained< T, gtl::cross_half_list >
template<typename T >
using is_gencross = is_contained< T, gtl::cross_floating_list >
template<typename T >
using is_charn = is_contained< T, gtl::vector_default_char_list >
template<typename T >
using is_scharn = is_contained< T, gtl::vector_signed_char_list >
template<typename T >
using is_ucharn = is_contained< T, gtl::vector_unsigned_char_list >
template<typename T >
using is_igenchar = is_contained< T, gtl::signed_char_list >
template<typename T >
using is_ugenchar = is_contained< T, gtl::unsigned_char_list >
template<typename T >
using is_genchar = is_contained< T, gtl::char_list >
template<typename T >
using is_shortn = is_contained< T, gtl::vector_signed_short_list >
template<typename T >
using is_genshort = is_contained< T, gtl::signed_short_list >
template<typename T >
using is_ushortn = is_contained< T, gtl::vector_unsigned_short_list >
template<typename T >
using is_ugenshort = is_contained< T, gtl::unsigned_short_list >
template<typename T >
using is_uintn = is_contained< T, gtl::vector_unsigned_int_list >
template<typename T >
using is_ugenint = is_contained< T, gtl::unsigned_int_list >
template<typename T >
using is_intn = is_contained< T, gtl::vector_signed_int_list >
template<typename T >
using is_genint = is_contained< T, gtl::signed_int_list >
template<typename T >
using is_ulongn = is_contained< T, gtl::vector_unsigned_long_list >
template<typename T >
using is_ugenlong = is_contained< T, gtl::unsigned_long_list >
template<typename T >
using is_longn = is_contained< T, gtl::vector_signed_long_list >
template<typename T >
using is_genlong = is_contained< T, gtl::signed_long_list >
template<typename T >
using is_ulonglongn = is_contained< T, gtl::vector_unsigned_longlong_list >
template<typename T >
using is_ugenlonglong = is_contained< T, gtl::unsigned_longlong_list >
template<typename T >
using is_longlongn = is_contained< T, gtl::vector_signed_longlong_list >
template<typename T >
using is_genlonglong = is_contained< T, gtl::signed_longlong_list >
template<typename T >
using is_igenlonginteger = is_contained< T, gtl::signed_long_integer_list >
template<typename T >
using is_ugenlonginteger = is_contained< T, gtl::unsigned_long_integer_list >
template<typename T >
using is_geninteger = is_contained< T, gtl::integer_list >
template<typename T >
using is_igeninteger = is_contained< T, gtl::signed_integer_list >
template<typename T >
using is_ugeninteger = is_contained< T, gtl::unsigned_integer_list >
template<typename T >
using is_sgeninteger = is_contained< T, gtl::scalar_integer_list >
template<typename T >
using is_vgeninteger = is_contained< T, gtl::vector_integer_list >
template<typename T >
using is_sigeninteger = is_contained< T, gtl::scalar_signed_integer_list >
template<typename T >
using is_sugeninteger = is_contained< T, gtl::scalar_unsigned_integer_list >
template<typename T >
using is_vigeninteger = is_contained< T, gtl::vector_signed_integer_list >
template<typename T >
using is_vugeninteger = is_contained< T, gtl::vector_unsigned_integer_list >
template<typename T >
using is_gentype = is_contained< T, gtl::basic_list >
template<typename T >
using is_vgentype = is_contained< T, gtl::vector_basic_list >
template<typename T >
using is_sgentype = is_contained< T, gtl::scalar_basic_list >
template<typename T >
using is_igeninteger8bit = is_gen_based_on_type_sizeof< T, 1, is_igeninteger >
template<typename T >
using is_igeninteger16bit = is_gen_based_on_type_sizeof< T, 2, is_igeninteger >
template<typename T >
using is_igeninteger32bit = is_gen_based_on_type_sizeof< T, 4, is_igeninteger >
template<typename T >
using is_igeninteger64bit = is_gen_based_on_type_sizeof< T, 8, is_igeninteger >
template<typename T >
using is_ugeninteger8bit = is_gen_based_on_type_sizeof< T, 1, is_ugeninteger >
template<typename T >
using is_ugeninteger16bit = is_gen_based_on_type_sizeof< T, 2, is_ugeninteger >
template<typename T >
using is_ugeninteger32bit = is_gen_based_on_type_sizeof< T, 4, is_ugeninteger >
template<typename T >
using is_ugeninteger64bit = is_gen_based_on_type_sizeof< T, 8, is_ugeninteger >
template<typename T >
using is_geninteger8bit = is_gen_based_on_type_sizeof< T, 1, is_geninteger >
template<typename T >
using is_geninteger16bit = is_gen_based_on_type_sizeof< T, 2, is_geninteger >
template<typename T >
using is_geninteger32bit = is_gen_based_on_type_sizeof< T, 4, is_geninteger >
template<typename T >
using is_geninteger64bit = is_gen_based_on_type_sizeof< T, 8, is_geninteger >
template<typename T >
using is_genintptr = bool_constant< is_pointer< T >::value &&is_genint< remove_pointer_t< T > >::value &&is_address_space_compliant< T, gvl::nonconst_address_space_list >::value >
template<typename T >
using is_genfloatptr = bool_constant< is_pointer< T >::value &&is_genfloat< remove_pointer_t< T > >::value &&is_address_space_compliant< T, gvl::nonconst_address_space_list >::value >
template<typename T >
using is_genptr = bool_constant< is_pointer< T >::value &&is_gentype< remove_pointer_t< T > >::value &&is_address_space_compliant< T, gvl::nonconst_address_space_list >::value >
template<typename T >
using is_nan_type = is_contained< T, gtl::nan_list >
template<typename T >
using nan_return_t = typename nan_types< T, T >::ret_type
template<typename T >
using nan_argument_base_t = typename nan_types< T, T >::arg_type
template<typename T >
using make_floating_point_t = make_type_t< T, gtl::scalar_floating_list >
template<typename T >
using make_singed_integer_t = make_type_t< T, gtl::scalar_signed_integer_list >
template<typename T >
using make_unsinged_integer_t = make_type_t< T, gtl::scalar_unsigned_integer_list >
template<typename T , typename B >
using convert_data_type = convert_data_type_impl< T, B, T >
template<typename T , typename T8 , typename T16 , typename T32 , typename T64 >
using select_apply_cl_scalar_t = conditional_t< sizeof(T)==1, T8, conditional_t< sizeof(T)==2, T16, conditional_t< sizeof(T)==4, T32, T64 > >>
template<typename T >
using select_cl_scalar_integral_signed_t = select_apply_cl_scalar_t< T, sycl::cl_char, sycl::cl_short, sycl::cl_int, sycl::cl_long >
template<typename T >
using select_cl_scalar_integral_unsigned_t = select_apply_cl_scalar_t< T, sycl::cl_uchar, sycl::cl_ushort, sycl::cl_uint, sycl::cl_ulong >
template<typename T >
using select_cl_scalar_float_t = select_apply_cl_scalar_t< T, std::false_type, sycl::cl_half, sycl::cl_float, sycl::cl_double >
template<typename T >
using select_cl_scalar_integral_t = conditional_t< std::is_signed< T >::value, select_cl_scalar_integral_signed_t< T >, select_cl_scalar_integral_unsigned_t< T > >
template<typename T >
using select_cl_scalar_t = conditional_t< std::is_integral< T >::value, select_cl_scalar_integral_t< T >, conditional_t< std::is_floating_point< T >::value, select_cl_scalar_float_t< T >, conditional_t< std::is_same< T, half >::value, cl::sycl::detail::half_impl::BIsRepresentationT, T > >>
template<typename T >
using type_helper = typename TypeHelper< T >::RetType
template<typename T >
using SelectMatchingOpenCLType_t = typename select_cl_mptr_or_vector_or_scalar< T >::type
template<typename T >
using ConvertToOpenCLType_t = conditional_t< TryToGetVectorT< SelectMatchingOpenCLType_t< T > >::value, typename TryToGetVectorT< SelectMatchingOpenCLType_t< T > >::type, conditional_t< TryToGetPointerT< SelectMatchingOpenCLType_t< T > >::value, typename TryToGetPointerVecT< SelectMatchingOpenCLType_t< T > >::type, SelectMatchingOpenCLType_t< T > >>
template<typename T >
using common_rel_ret_t = conditional_t< is_vgentype< T >::value, make_singed_integer_t< T >, int >
template<typename T >
using rel_ret_t = typename RelationalReturnType< T >::type
template<typename T >
using rel_sign_bit_test_ret_t = typename RelationalTestForSignBitType< T >::return_type
template<typename T >
using rel_sign_bit_test_arg_t = typename RelationalTestForSignBitType< T >::argument_type
template<typename T >
using IsValidCoordType = typename is_contained< T, type_list< cl_int, cl_float > >::type
using image_allocator = aligned_allocator< byte >
template<typename T >
using is_validImageDataT = typename detail::is_contained< T, type_list< cl_int4, cl_uint4, cl_float4, cl_half4 > >::type
template<typename DataT >
using EnableIfImgAccDataT = typename detail::enable_if_t< is_validImageDataT< DataT >::value, DataT >
using QueueImplPtr = std::shared_ptr< detail::queue_impl >
using EventImplPtr = std::shared_ptr< detail::event_impl >
using ContextImplPtr = std::shared_ptr< detail::context_impl >
using OSModuleHandle = intptr_t
Uniquely identifies an operating system module (executable or a dynamic library)
template<bool B, class T = void>
using enable_if_t = typename std::enable_if< B, T >::type
template<bool B, class T , class F >
using conditional_t = typename std::conditional< B, T, F >::type
template<typename T >
using remove_const_t = typename std::remove_const< T >::type
template<typename T >
using remove_cv_t = typename std::remove_cv< T >::type
template<typename T >
using remove_reference_t = typename std::remove_reference< T >::type
template<typename T >
using add_pointer_t = typename std::add_pointer< T >::type
template<bool V>
using bool_constant = std::integral_constant< bool, V >
template<class... >
using void_t = void
template<typename T >
using allocator_value_type_t = typename std::allocator_traits< T >::value_type
template<typename T >
using allocator_pointer_t = typename std::allocator_traits< T >::pointer
template<typename T >
using iterator_category_t = typename std::iterator_traits< T >::iterator_category
template<typename T >
using iterator_value_type_t = typename std::iterator_traits< T >::value_type
template<typename T >
using iterator_pointer_t = typename std::iterator_traits< T >::pointer
template<typename T >
using iterator_to_const_type_t = std::is_const< typename std::remove_pointer< iterator_pointer_t< T > >::type >
template<typename T >
using output_iterator_requirements = void_t< iterator_category_t< T >, decltype(*std::declval< T >()=std::declval< iterator_value_type_t< T > >())>
using sycl_memory_object_allocator = aligned_allocator< char >
template<std::size_t I, class T >
using tuple_element_t = typename tuple_element< I, T >::type
template<typename T >
using head_t = typename T::head
template<typename T >
using tail_t = typename T::tail
using empty_type_list = type_list<>
template<access::address_space... V>
using address_space_list = value_list< access::address_space, V... >
template<access::address_space AS, typename VL >
using is_one_of_spaces = is_contained_value< access::address_space, AS, VL >
template<typename TL , template< typename, typename > class C, typename T >
using find_type_t = typename find_type< TL, C, T >::type
template<typename TL , typename T >
using find_same_size_type_t = find_type_t< TL, is_type_size_equal, T >
template<typename TL , typename T >
using find_smaller_type_t = find_type_t< TL, is_type_size_less, T >
template<typename TL , typename T >
using find_larger_type_t = find_type_t< TL, is_type_size_greater, T >
template<typename TL , typename T >
using find_twice_as_small_type_t = find_type_t< TL, is_type_size_half_of, T >
template<typename TL , typename T >
using find_twice_as_large_type_t = find_type_t< TL, is_type_size_double_of, T >
using uuid_type = std::array< unsigned char, 16 >
template<typename T , typename R >
using copy_cv_qualifiers_t = typename copy_cv_qualifiers< T, R >::type
template<int V>
using int_constant = std::integral_constant< int, V >
template<typename T >
using vector_element_impl_t = typename vector_element_impl< T >::type
template<class T >
using vector_element_t = typename vector_element< T >::type
template<typename T , typename B >
using change_base_type_t = typename change_base_type< T, B >::type
template<typename T >
using make_signed_impl_t = typename make_signed_impl< T, T >::type
template<typename T >
using make_signed_t = typename make_signed< T >::type
template<typename T >
using make_unsigned_impl_t = typename make_unsigned_impl< T, T >::type
template<typename T >
using make_unsigned_t = typename make_unsigned< T >::type
template<typename T , int N, template< typename > class S>
using is_gen_based_on_type_sizeof = bool_constant< S< T >::value &&(sizeof(vector_element_t< T >)==N)>
template<typename T >
using remove_pointer_t = typename remove_pointer< T >::type
template<typename T , typename TL >
using make_type_t = typename make_type_impl< T, TL >::type
template<typename T >
using make_larger_t = typename make_larger< T >::type
template<access::address_space AS, class DataT >
using const_if_const_AS = DataT
using SerializedObj = std::vector< unsigned char >
template<typename T >
using native_op_list = type_list< sycl::plus< T >, sycl::bit_or< T >, sycl::bit_xor< T >, sycl::bit_and< T >, sycl::maximum< T >, sycl::minimum< T >, sycl::multiplies< T > >
template<typename T , typename BinaryOperation >
using is_plus = std::integral_constant< bool, std::is_same< BinaryOperation, sycl::plus< T > >::value||std::is_same< BinaryOperation, sycl::plus< void > >::value >
template<typename T >
using is_arithmetic_or_complex = std::integral_constant< bool, sycl::detail::is_complex< T >::value||sycl::detail::is_arithmetic< T >::value >
template<typename T , typename BinaryOperation >
using is_plus_if_complex = std::integral_constant< bool,(is_complex< T >::value ? is_plus< T, BinaryOperation >::value :std::true_type::value)>
template<typename F , typename SuggestedArgType >
using lambda_arg_type = decltype(argument_helper< F, SuggestedArgType >(0))
using DeviceImageImplPtr = std::shared_ptr< device_image_impl >
using KernelBundleImplPtr = std::shared_ptr< detail::kernel_bundle_impl >
using DevImgSelectorImpl = std::function< bool(const detail::DeviceImageImplPtr &DevImgImpl)>
template<typename T , class BinaryOperation >
using IsPlus = bool_constant< std::is_same< BinaryOperation, sycl::plus< T > >::value||std::is_same< BinaryOperation, sycl::plus< void > >::value >
template<typename T , class BinaryOperation >
using IsMultiplies = bool_constant< std::is_same< BinaryOperation, sycl::multiplies< T > >::value||std::is_same< BinaryOperation, sycl::multiplies< void > >::value >
template<typename T , class BinaryOperation >
using IsMinimum = bool_constant< std::is_same< BinaryOperation, sycl::minimum< T > >::value||std::is_same< BinaryOperation, sycl::minimum< void > >::value >
template<typename T , class BinaryOperation >
using IsMaximum = bool_constant< std::is_same< BinaryOperation, sycl::maximum< T > >::value||std::is_same< BinaryOperation, sycl::maximum< void > >::value >
template<typename T , class BinaryOperation >
using IsBitAND = bool_constant< std::is_same< BinaryOperation, sycl::bit_and< T > >::value||std::is_same< BinaryOperation, sycl::bit_and< void > >::value >
template<typename T , class BinaryOperation >
using IsBitOR = bool_constant< std::is_same< BinaryOperation, sycl::bit_or< T > >::value||std::is_same< BinaryOperation, sycl::bit_or< void > >::value >
template<typename T , class BinaryOperation >
using IsBitXOR = bool_constant< std::is_same< BinaryOperation, sycl::bit_xor< T > >::value||std::is_same< BinaryOperation, sycl::bit_xor< void > >::value >
template<typename T , class BinaryOperation >
using IsLogicalAND = bool_constant< std::is_same< BinaryOperation, sycl::logical_and< T > >::value||std::is_same< BinaryOperation, sycl::logical_and< void > >::value >
template<typename T , class BinaryOperation >
using IsLogicalOR = bool_constant< std::is_same< BinaryOperation, sycl::logical_or< T > >::value||std::is_same< BinaryOperation, sycl::logical_or< void > >::value >
template<typename T , class BinaryOperation >
using IsZeroIdentityOp = bool_constant<(is_geninteger< T >::value &&(IsPlus< T, BinaryOperation >::value||IsBitOR< T, BinaryOperation >::value||IsBitXOR< T, BinaryOperation >::value))||(is_genfloat< T >::value &&IsPlus< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsOneIdentityOp = bool_constant<(is_geninteger< T >::value||is_genfloat< T >::value) &&IsMultiplies< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsOnesIdentityOp = bool_constant< is_geninteger< T >::value &&IsBitAND< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsMinimumIdentityOp = bool_constant<(is_geninteger< T >::value||is_genfloat< T >::value) &&IsMinimum< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsMaximumIdentityOp = bool_constant<(is_geninteger< T >::value||is_genfloat< T >::value) &&IsMaximum< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsFalseIdentityOp = bool_constant< IsLogicalOR< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsTrueIdentityOp = bool_constant< IsLogicalAND< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsKnownIdentityOp = bool_constant< IsZeroIdentityOp< T, BinaryOperation >::value||IsOneIdentityOp< T, BinaryOperation >::value||IsOnesIdentityOp< T, BinaryOperation >::value||IsMinimumIdentityOp< T, BinaryOperation >::value||IsMaximumIdentityOp< T, BinaryOperation >::value||IsFalseIdentityOp< T, BinaryOperation >::value||IsTrueIdentityOp< T, BinaryOperation >::value >
using FmtFlags = unsigned int
template<class F , class T = void>
using EnableIfFP = typename detail::enable_if_t< std::is_same< F, float >::value||std::is_same< F, double >::value||std::is_same< F, half >::value, T >
using GlobalBufAccessorT = accessor< char, 1, cl::sycl::access::mode::read_write, cl::sycl::access::target::global_buffer, cl::sycl::access::placeholder::false_t >
using GlobalBufPtrType = typename detail::DecoratedType< char, GlobalBufAS >::type *
using GlobalOffsetAccessorT = accessor< unsigned, 1, cl::sycl::access::mode::atomic, cl::sycl::access::target::global_buffer, cl::sycl::access::placeholder::false_t >
using GlobalOffsetPtrType = typename detail::DecoratedType< unsigned, GlobalBufAS >::type *
template<typename T >
using EnableIfSwizzleVec = typename detail::enable_if_t< IsSwizzleOp< T >::value, typename IsSwizzleOp< T >::Type >
template<typename DataT >
using rel_t = typename detail::conditional_t< sizeof(DataT)==sizeof(cl_char), cl_char, typename detail::conditional_t< sizeof(DataT)==sizeof(cl_short), cl_short, typename detail::conditional_t< sizeof(DataT)==sizeof(cl_int), cl_int, typename detail::conditional_t< sizeof(DataT)==sizeof(cl_long), cl_long, bool > >> >
template<typename T , typename R >
using is_int_to_int = std::integral_constant< bool, std::is_integral< T >::value &&std::is_integral< R >::value >
template<typename T , typename R >
using is_sint_to_sint = std::integral_constant< bool, is_sigeninteger< T >::value &&is_sigeninteger< R >::value >
template<typename T , typename R >
using is_uint_to_uint = std::integral_constant< bool, is_sugeninteger< T >::value &&is_sugeninteger< R >::value >
template<typename T , typename R >
using is_sint_to_from_uint = std::integral_constant< bool,(is_sugeninteger< T >::value &&is_sigeninteger< R >::value)||(is_sigeninteger< T >::value &&is_sugeninteger< R >::value)>
template<typename T , typename R >
using is_sint_to_float = std::integral_constant< bool, std::is_integral< T >::value &&!(std::is_unsigned< T >::value) &&detail::is_floating_point< R >::value >
template<typename T , typename R >
using is_uint_to_float = std::integral_constant< bool, std::is_unsigned< T >::value &&detail::is_floating_point< R >::value >
template<typename T , typename R >
using is_int_to_float = std::integral_constant< bool, std::is_integral< T >::value &&detail::is_floating_point< R >::value >
template<typename T , typename R >
using is_float_to_int = std::integral_constant< bool, detail::is_floating_point< T >::value &&std::is_integral< R >::value >
template<typename T , typename R >
using is_float_to_float = std::integral_constant< bool, detail::is_floating_point< T >::value &&detail::is_floating_point< R >::value >
template<typename T >
using is_standard_type = std::integral_constant< bool, detail::is_sgentype< T >::value >
template<typename T , typename T8 , typename T16 , typename T32 , typename T64 >
using select_apply_cl_t = conditional_t< sizeof(T)==1, T8, conditional_t< sizeof(T)==2, T16, conditional_t< sizeof(T)==4, T32, T64 > >>
using DeviceDescT = std::map< std::string, std::string >
using AllowListParsedT = std::vector< DeviceDescT >
using PlatformImplPtr = std::shared_ptr< detail::platform_impl >
using LockGuard = std::lock_guard< SpinLock >
using ProgramImplPtr = std::shared_ptr< program_impl >
using DeviceImplPtr = std::shared_ptr< device_impl >
using StreamImplPtr = std::shared_ptr< detail::stream_impl >
using SpecConstRegistryT = std::map< std::string, spec_constant_impl >
Enumerations
enum backend_errc : unsigned int
enum ExtendedMembersType : unsigned int { ExtendedMembersType::HANDLER_KERNEL_BUNDLE = 0, ExtendedMembersType::HANDLER_MEM_ADVICE, ExtendedMembersType::HANDLER_IMPL }
enum kernel_param_kind_t {
kernel_param_kind_t::kind_accessor = 0, kernel_param_kind_t::kind_std_layout = 1, kernel_param_kind_t::kind_sampler = 2, kernel_param_kind_t::kind_pointer = 3,
kernel_param_kind_t::kind_specialization_constants_buffer = 4, kernel_param_kind_t::kind_stream = 5, kernel_param_kind_t::kind_invalid = 0xf
}
enum PiApiKind { PiApiKind::_PI_API }
enum DataLessPropKind {
BufferUseHostPtr = 0, ImageUseHostPtr = 1, QueueEnableProfiling = 2, InOrder = 3,
NoInit = 4, BufferUsePinnedHostMemory = 5, UsePrimaryContext = 6, InitializeToIdentity = 7,
UseDefaultStream = 8, DiscardEvents = 9, DeviceReadOnly = 10, LastKnownDataLessPropKind = 10,
DataLessPropKindSize = 32
}
enum PropWithDataKind {
BufferUseMutex = 0, BufferContextBound = 1, ImageUseMutex = 2, ImageContextBound = 3,
BufferMemChannel = 4, AccPropBufferLocation = 5, PropWithDataKindSize = 6
}
enum ConfigID { START = 0, END }
enum HandlerSubmissionState : std::uint8_t { HandlerSubmissionState::NO_STATE = 0, HandlerSubmissionState::EXPLICIT_KERNEL_BUNDLE_STATE, HandlerSubmissionState::SPEC_CONST_SET_STATE }
enum BuildState { BS_InProgress, BS_Done, BS_Failed }
enum DeviceLibExt : std::uint32_t {
DeviceLibExt::cl_intel_devicelib_assert, DeviceLibExt::cl_intel_devicelib_math, DeviceLibExt::cl_intel_devicelib_math_fp64, DeviceLibExt::cl_intel_devicelib_complex,
DeviceLibExt::cl_intel_devicelib_complex_fp64, DeviceLibExt::cl_intel_devicelib_cstring
}
enum CUDAContextT : char { CUDAContextT::primary, CUDAContextT::custom }
Possible CUDA context types supported by PI CUDA backend TODO: Implement this as a property once there is an extension document.
enum QueueOrder { Ordered, OOO }
enum BlockingT { NON_BLOCKING = 0, BLOCKING }
Functions
constexpr bool isTargetHostAccess (access::target T)
constexpr bool modeNeedsOldData (access::mode m)
constexpr bool modeWritesNewData (access::mode m)
void constructorNotification (void *BufferObj, void *AccessorObj, access::target Target, access::mode Mode, const code_location &CodeLoc)
template<int NewDim, int DefaultValue, template< int > class T, int OldDim>
static T< NewDim > convertToArrayOfN (T< OldDim > OldObj)
device getDeviceFromHandler (handler &CommandGroupHandlerRef)
static std::memory_order getStdMemoryOrder (__spv::MemorySemanticsMask::Flag)
constexpr memory_order getLoadOrder (memory_order order)
platform make_platform (pi_native_handle NativeHandle, backend Backend)
device make_device (pi_native_handle NativeHandle, backend Backend)
context make_context (pi_native_handle NativeHandle, const async_handler &Handler, backend Backend)
queue make_queue (pi_native_handle NativeHandle, const context &TargetContext, bool KeepOwnership, const async_handler &Handler, backend Backend)
queue make_queue (pi_native_handle NativeHandle, const context &TargetContext, const async_handler &Handler, backend Backend)
event make_event (pi_native_handle NativeHandle, const context &TargetContext, backend Backend)
event make_event (pi_native_handle NativeHandle, const context &TargetContext, bool KeepOwnership, backend Backend)
kernel make_kernel (pi_native_handle NativeHandle, const context &TargetContext, backend Backend)
kernel make_kernel (const context &TargetContext, const kernel_bundle< bundle_state::executable > &KernelBundle, pi_native_handle NativeKernelHandle, bool KeepOwnership, backend Backend)
std::shared_ptr< detail::kernel_bundle_impl > make_kernel_bundle (pi_native_handle NativeHandle, const context &TargetContext, bundle_state State, backend Backend)
std::shared_ptr< detail::kernel_bundle_impl > make_kernel_bundle (pi_native_handle NativeHandle, const context &TargetContext, bool KeepOwnership, bundle_state State, backend Backend)
void memcpy (void *Dst, const void *Src, std::size_t Size)
template<typename To , typename From >
To bit_cast (const From &from) noexcept
template<typename T , int Dimensions, typename AllocatorT >
buffer< T, Dimensions, AllocatorT, void > make_buffer_helper (pi_native_handle Handle, const context &Ctx, event Evt)
void addHostAccessorAndWait (Requirement *Req)
static std::shared_ptr< std::vector< ExtendedMemberT > > convertToExtendedMembers (const std::shared_ptr< const void > &SPtr)
constexpr unsigned int getVersionedCGType (unsigned int Type, unsigned char Version)
constexpr unsigned char getUnversionedCGType (unsigned int Type)
constexpr unsigned char getCGTypeVersion (unsigned int Type)
template<typename F , typename... Args>
static constexpr bool check_kernel_lambda_takes_args ()
template<typename KernelType , typename LambdaArgType , typename std::enable_if_t< std::is_same< LambdaArgType, void >::value > * = nullptr>
constexpr bool isKernelLambdaCallableWithKernelHandlerImpl ()
template<typename KernelType >
std::enable_if_t< KernelLambdaHasKernelHandlerArgT< KernelType >::value > runKernelWithoutArg (KernelType KernelName)
template<typename KernelType >
std::enable_if_t<!KernelLambdaHasKernelHandlerArgT< KernelType >::value > runKernelWithoutArg (KernelType KernelName)
template<typename ArgType , typename KernelType >
std::enable_if_t< KernelLambdaHasKernelHandlerArgT< KernelType, ArgType >::value > runKernelWithArg (KernelType KernelName, ArgType Arg)
template<typename ArgType , typename KernelType >
std::enable_if_t< !KernelLambdaHasKernelHandlerArgT< KernelType, ArgType >::value > runKernelWithArg (KernelType KernelName, ArgType Arg)
const char * stringifyErrorCode (cl_int error)
static std::string codeToString (cl_int code)
template<class Obj >
decltype(Obj::impl) getSyclObjImpl (const Obj &SyclObject)
template<class T >
detail::add_pointer_t< typename decltype(T::impl)::element_type > getRawSyclObjImpl (const T &SyclObject)
template<class T >
T createSyclObjFromImpl (decltype(T::impl) ImplObj)
constexpr size_t getNextPowerOfTwoHelper (size_t Var, size_t Offset)
constexpr size_t getNextPowerOfTwo (size_t Var)
template<int Dims, template< int > class T, template< int > class U>
size_t getLinearIndex (const T< Dims > &Index, const U< Dims > &Range)
std::vector< std::string > split_string (const std::string &str, char delimeter)
std::ostream & operator<< (std::ostream &Out, const device_filter &Filter)
std::ostream & operator<< (std::ostream &Out, const device_filter_list &List)
template<typename T , typename = typename detail::enable_if_t< TryToGetPointerT<T>::value, std::true_type>>
TryToGetPointerVecT< T >::type TryToGetPointer (T &t)
template<typename T >
TryToGetPointerVecT< T * >::type TryToGetPointer (T *t)
template<typename T , typename = typename detail::enable_if_t< !TryToGetPointerT<T>::value, std::false_type>>
T TryToGetPointer (T &t)
template<typename FROM , typename TO >
detail::enable_if_t< is_vgentype< FROM >::value &&is_vgentype< TO >::value &&sizeof(TO)==sizeof(FROM), TO > convertDataToType (FROM t)
template<typename FROM , typename TO >
detail::enable_if_t<!(is_vgentype< FROM >::value &&is_vgentype< TO >::value) &&sizeof(TO)==sizeof(FROM), TO > convertDataToType (FROM t)
template<typename T >
constexpr T msbMask (T)
template<typename T >
constexpr bool msbIsSet (const T x)
template<typename T >
static constexpr T max_v ()
template<typename T >
static constexpr T min_v ()
template<typename T >
static constexpr T quiet_NaN ()
template<typename... Args>
void check_vector_size ()
void associateWithHandler (handler &, AccessorBaseHost *, access::target)
void memcpy (void *Dst, const void *Src, size_t Size)
std::vector< RT::PiEvent > getOrWaitEvents (std::vector< cl::sycl::event > DepEvents, std::shared_ptr< cl::sycl::detail::context_impl > Context)
void waitEvents (std::vector< cl::sycl::event > DepEvents)
template<typename T >
T * declptr ()
template<typename T >
T get_or_store (const T *obj)
constexpr __spv::MemorySemanticsMask::Flag getSPIRVMemorySemanticsMask (memory_order)
constexpr uint32_t getSPIRVMemorySemanticsMask (const access::fence_space AccessSpace, const __spv::MemorySemanticsMask LocalScopeMask=__spv::MemorySemanticsMask::WorkgroupMemory)
template<typename T >
detail::enable_if_t< IsValidCoordType< T >::value, T > UnnormalizeCoordinates (const T &Coords, const range< 3 > &Range)
template<typename T >
detail::enable_if_t< IsValidCoordType< T >::value, vec< T, 2 > > UnnormalizeCoordinates (const vec< T, 2 > &Coords, const range< 3 > &Range)
template<typename T >
detail::enable_if_t< IsValidCoordType< T >::value, vec< T, 4 > > UnnormalizeCoordinates (const vec< T, 4 > &Coords, const range< 3 > &Range)
template<typename T >
detail::enable_if_t< IsValidCoordType< T >::value, cl_float4 > convertToFloat4 (T Coords)
template<typename T >
detail::enable_if_t< IsValidCoordType< T >::value, cl_float4 > convertToFloat4 (vec< T, 2 > Coords)
template<typename T >
detail::enable_if_t< IsValidCoordType< T >::value, cl_float4 > convertToFloat4 (vec< T, 4 > Coords)
template<typename T >
detail::enable_if_t< std::is_integral< T >::value, size_t > getImageOffset (const T &Coords, const id< 3 >, const uint8_t ElementSize)
template<typename T >
detail::enable_if_t< std::is_integral< T >::value, size_t > getImageOffset (const vec< T, 2 > &Coords, const id< 3 > ImgPitch, const uint8_t ElementSize)
template<typename T >
detail::enable_if_t< std::is_integral< T >::value, size_t > getImageOffset (const vec< T, 4 > &Coords, const id< 3 > ImgPitch, const uint8_t ElementSize)
cl_int4 getPixelCoordNearestFiltMode (cl_float4, const addressing_mode, const range< 3 >)
cl_int8 getPixelCoordLinearFiltMode (cl_float4, const addressing_mode, const range< 3 >, cl_float4 &)
bool isOutOfRange (const cl_int4 PixelCoord, const addressing_mode SmplAddrMode, const range< 3 > ImgRange)
cl_float4 getBorderColor (const image_channel_order ImgChannelOrder)
template<typename T >
vec< T, 4 > readPixel (T *Ptr, const image_channel_order ChannelOrder, const image_channel_type ChannelType)
template<typename T >
void writePixel (const vec< T, 4 > Pixel, T *Ptr, const image_channel_order ChannelOrder, const image_channel_type ChannelType)
template<typename ChannelType >
void convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, vec< cl_uint, 4 > &RetData)
template<typename ChannelType >
void convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, vec< cl_int, 4 > &RetData)
template<typename ChannelType >
void convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, vec< cl_float, 4 > &RetData)
template<typename ChannelType >
void convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, vec< cl_half, 4 > &RetData)
template<typename ChannelType >
vec< ChannelType, 4 > convertWriteData (const vec< cl_uint, 4 > WriteData, const image_channel_type ImageChannelType)
template<typename ChannelType >
vec< ChannelType, 4 > convertWriteData (const vec< cl_int, 4 > WriteData, const image_channel_type ImageChannelType)
template<typename ChannelType >
vec< ChannelType, 4 > processFloatDataToPixel (vec< cl_float, 4 > WriteData, float MulFactor)
template<typename ChannelType >
vec< ChannelType, 4 > convertWriteData (const vec< cl_float, 4 > WriteData, const image_channel_type ImageChannelType)
template<typename ChannelType >
vec< ChannelType, 4 > convertWriteData (const vec< cl_half, 4 > WriteData, const image_channel_type ImageChannelType)
template<typename CoordT , typename WriteDataT >
void imageWriteHostImpl (const CoordT &Coords, const WriteDataT &Color, id< 3 > ImgPitch, uint8_t ElementSize, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void *BasePtr)
template<typename DataT >
DataT ReadPixelData (const cl_int4 PixelCoord, const id< 3 > ImgPitch, const image_channel_type ImageChannelType, const image_channel_order ImageChannelOrder, void *BasePtr, const uint8_t ElementSize)
template<typename DataT >
DataT getColor (const cl_int4 PixelCoord, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, const id< 3 > ImgPitch, const image_channel_type ImgChannelType, const image_channel_order ImgChannelOrder, void *BasePtr, const uint8_t ElementSize)
template<typename DataT >
DataT ReadPixelDataLinearFiltMode (const cl_int8 CoordValues, const cl_float4 abc, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, id< 3 > ImgPitch, const image_channel_type ImgChannelType, const image_channel_order ImgChannelOrder, void *BasePtr, const uint8_t ElementSize)
template<typename CoordT , typename DataT >
DataT imageReadSamplerHostImpl (const CoordT &Coords, const sampler &Smpl, range< 3 > ImgRange, id< 3 > ImgPitch, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void *BasePtr, uint8_t ElementSize)
uint8_t getImageNumberChannels (image_channel_order Order)
uint8_t getImageElementSize (uint8_t NumChannels, image_channel_type Type)
RT::PiMemImageChannelOrder convertChannelOrder (image_channel_order Order)
image_channel_order convertChannelOrder (RT::PiMemImageChannelOrder Order)
RT::PiMemImageChannelType convertChannelType (image_channel_type Type)
image_channel_type convertChannelType (RT::PiMemImageChannelType Type)
template<cl::sycl::backend BE>
void * getPluginOpaqueData (void *opaquedata_arg)
template<typename T , typename... Ts, std::size_t... Is>
std::tuple< Ts... > get_tuple_tail_impl (const std::tuple< T, Ts... > &Tuple, const std::index_sequence< Is... > &)
template<typename T , typename... Ts>
std::tuple< Ts... > get_tuple_tail (const std::tuple< T, Ts... > &Tuple)
template<typename... Ts>
constexpr tuple< Ts... > make_tuple (Ts... Args)
template<typename... Ts>
auto tie (Ts &... Args)
auto getDeviceComparisonLambda ()
static void workGroupBarrier ()
template<int Dimensions>
id< Dimensions > linear_id_to_id (range< Dimensions >, size_t linear_id)
template<>
id< 1 > linear_id_to_id (range< 1 >, size_t linear_id)
template<>
id< 2 > linear_id_to_id (range< 2 > r, size_t linear_id)
template<>
id< 3 > linear_id_to_id (range< 3 > r, size_t linear_id)
template<typename Group >
size_t get_local_linear_range (Group g)
template<>
size_t get_local_linear_range< group< 1 > > (group< 1 > g)
template<>
size_t get_local_linear_range< group< 2 > > (group< 2 > g)
template<>
size_t get_local_linear_range< group< 3 > > (group< 3 > g)
template<>
size_t get_local_linear_range< ext::oneapi::sub_group > (ext::oneapi::sub_group g)
template<typename Group >
Group::linear_id_type get_local_linear_id (Group g)
template<>
ext::oneapi::sub_group::linear_id_type get_local_linear_id< ext::oneapi::sub_group > (ext::oneapi::sub_group g)
template<typename T , class BinaryOperation >
constexpr detail::enable_if_t<(is_complex< T >::value &&is_plus< T, BinaryOperation >::value), T > identity_for_ga_op ()
template<typename T , class BinaryOperation >
constexpr detail::enable_if_t<!is_complex< T >::value, T > identity_for_ga_op ()
template<typename Group , typename Ptr , class Function >
Function for_each (Group g, Ptr first, Ptr last, Function f)
__SYCL_CONSTEXPR_HALF uint16_t float2Half (const float &Val)
__SYCL_CONSTEXPR_HALF float half2Float (const uint16_t &Val)
template<typename T >
T cast_if_host_half (T val)
float cast_if_host_half (half_impl::half val)
template<typename RetType , typename Func , typename Arg >
static Arg member_ptr_helper (RetType(Func::*)(Arg) const)
template<typename F , typename SuggestedArgType >
SuggestedArgType argument_helper (...)
template<int Dims, typename T >
detail::enable_if_t< std::is_same< T, range< Dims > >::value||std::is_same< T, id< Dims > >::value > checkValueRange (const T &V)
template<int Dims>
void checkValueRange (const range< Dims > &R, const id< Dims > &O)
template<int Dims, typename T >
detail::enable_if_t< std::is_same< T, nd_range< Dims > >::value > checkValueRange (const T &V)
template<int dimensions>
size_t getOffsetForId (range< dimensions > Range, id< dimensions > Id, id< dimensions > Offset)
id< 1 > getDelinearizedId (const range< 1 > &, size_t Index)
id< 2 > getDelinearizedId (const range< 2 > &Range, size_t Index)
id< 3 > getDelinearizedId (const range< 3 > &Range, size_t Index)
kernel_id get_kernel_id_impl (std::string KernelName)
detail::KernelBundleImplPtr get_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, bundle_state State)
const std::vector< device > removeDuplicateDevices (const std::vector< device > &Devs)
detail::KernelBundleImplPtr get_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, const std::vector< kernel_id > &KernelIDs, bundle_state State)
detail::KernelBundleImplPtr get_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, bundle_state State, const DevImgSelectorImpl &Selector)
detail::KernelBundleImplPtr get_empty_interop_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs)
template<bundle_state State>
kernel_bundle< State > get_empty_interop_kernel_bundle (const context &Ctx)
make_kernel may need an empty interop kernel bundle.
bool has_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, bundle_state State)
bool has_kernel_bundle_impl (const context &Ctx, const std::vector< device > &Devs, const std::vector< kernel_id > &kernelIds, bundle_state State)
std::shared_ptr< detail::kernel_bundle_impl > join_impl (const std::vector< detail::KernelBundleImplPtr > &Bundles)
std::shared_ptr< detail::kernel_bundle_impl > join_impl (const std::vector< detail::KernelBundleImplPtr > &Bundles, bundle_state State)
std::shared_ptr< detail::kernel_bundle_impl > compile_impl (const kernel_bundle< bundle_state::input > &InputBundle, const std::vector< device > &Devs, const property_list &PropList)
std::vector< sycl::device > find_device_intersection (const std::vector< kernel_bundle< bundle_state::object >> &ObjectBundles)
std::shared_ptr< detail::kernel_bundle_impl > link_impl (const std::vector< kernel_bundle< bundle_state::object >> &ObjectBundles, const std::vector< device > &Devs, const property_list &PropList)
std::shared_ptr< detail::kernel_bundle_impl > build_impl (const kernel_bundle< bundle_state::input > &InputBundle, const std::vector< device > &Devs, const property_list &PropList)
std::vector< memory_order > readMemoryOrderBitfield (pi_memory_order_capabilities bits)
std::vector< memory_scope > readMemoryScopeBitfield (pi_memory_scope_capabilities bits)
static constexpr std::memory_order getStdMemoryOrder (sycl::memory_order order)
unsigned GetFlushBufOffset (const GlobalBufAccessorT &GlobalFlushBuf, unsigned WIOffset)
void SetFlushBufOffset (GlobalBufAccessorT &GlobalFlushBuf, unsigned WIOffset, unsigned Offset)
void write (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const char *Str, unsigned Len, unsigned Padding=0)
void reverseBuf (char *Buf, unsigned Len)
template<typename T >
std::make_unsigned< T >::type getAbsVal (const T Val, const int Base)
char digitToChar (const int Digit)
template<typename T >
detail::enable_if_t< std::is_integral< T >::value, unsigned > integralToBase (T Val, int Base, char *Digits)
template<typename T >
detail::enable_if_t< std::is_integral< T >::value, unsigned > ScalarToStr (const T &Val, char *Buf, unsigned Flags, int, int Precision=-1)
unsigned append (char *Dst, const char *Src)
template<typename T >
detail::enable_if_t< std::is_same< T, float >::value||std::is_same< T, double >::value, unsigned > checkForInfNan (char *Buf, T Val)
template<typename T >
detail::enable_if_t< std::is_same< T, half >::value, unsigned > checkForInfNan (char *Buf, T Val)
template<typename T >
EnableIfFP< T, unsigned > floatingPointToDecStr (T AbsVal, char *Digits, int Precision, bool IsSci)
template<typename T >
EnableIfFP< T, unsigned > ScalarToStr (const T &Val, char *Buf, unsigned Flags, int, int Precision=-1)
template<typename T >
detail::enable_if_t< std::is_integral< T >::value > writeIntegral (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, const T &Val)
template<typename T >
EnableIfFP< T > writeFloatingPoint (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, int Precision, const T &Val)
bool updateOffset (GlobalOffsetAccessorT &GlobalOffset, GlobalBufAccessorT &GlobalBuf, unsigned Size, unsigned &Cur)
void flushBuffer (GlobalOffsetAccessorT &GlobalOffset, GlobalBufAccessorT &GlobalBuf, GlobalBufAccessorT &GlobalFlushBuf, unsigned WIOffset)
template<typename T , int VecLength>
detail::enable_if_t<(VecLength==1), unsigned > VecToStr (const vec< T, VecLength > &Vec, char *VecStr, unsigned Flags, int Width, int Precision)
template<typename T , int VecLength>
detail::enable_if_t<(VecLength==2||VecLength==4||VecLength==8||VecLength==16), unsigned > VecToStr (const vec< T, VecLength > &Vec, char *VecStr, unsigned Flags, int Width, int Precision)
template<typename T , int VecLength>
detail::enable_if_t<(VecLength==3), unsigned > VecToStr (const vec< T, VecLength > &Vec, char *VecStr, unsigned Flags, int Width, int Precision)
template<typename T , int VecLength>
void writeVec (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, int Precision, const vec< T, VecLength > &Vec)
template<int ArrayLength>
unsigned ArrayToStr (char *Buf, const array< ArrayLength > &Arr)
template<int ArrayLength>
void writeArray (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const array< ArrayLength > &Arr)
template<int Dimensions>
void writeItem (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const item< Dimensions > &Item)
template<int Dimensions>
void writeNDRange (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const nd_range< Dimensions > &ND_Range)
template<int Dimensions>
void writeNDItem (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const nd_item< Dimensions > &ND_Item)
template<int Dimensions>
void writeGroup (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const group< Dimensions > &Group)
template<int Dimensions>
unsigned ItemToStr (char *Buf, const item< Dimensions, false > &Item)
template<int Dimensions>
void writeHItem (GlobalBufAccessorT &GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const h_item< Dimensions > &HItem)
template<typename T , typename R , rounding_mode roundingMode, typename OpenCLT , typename OpenCLR >
detail::enable_if_t< std::is_same< T, R >::value, R > convertImpl (T Value)
template<typename T , typename R , rounding_mode roundingMode, typename OpenCLT , typename OpenCLR >
detail::enable_if_t<!std::is_same< T, R >::value &&(is_int_to_int< T, R >::value||is_int_to_float< T, R >::value||is_float_to_float< T, R >::value), R > convertImpl (T Value)
template<typename T , typename R , rounding_mode roundingMode, typename OpenCLT , typename OpenCLR >
detail::enable_if_t< is_float_to_int< T, R >::value, R > convertImpl (T Value)
template<typename T >
struct __SYCL2020_DEPRECATED ("This type isn't device copyable in SYCL 2020") IsDeprecatedDeviceCopyable< T
static const plugin & getPlugin (backend Backend)
AllowListParsedT parseAllowList (const std::string &AllowListRaw)
bool deviceIsAllowed (const DeviceDescT &DeviceDesc, const AllowListParsedT &AllowListParsed)
void applyAllowList (std::vector< RT::PiDevice > &PiDevices, RT::PiPlatform PiPlatform, const plugin &Plugin)
template<class T >
backend getImplBackend (const T &Impl)
static void initValue (const char *Key, const char *Value)
void readConfig (bool ForceInitialization)
void dumpConfig ()
const std::array< std::pair< std::string, info::device_type >, 5 > & getSyclDeviceTypeMap ()
const std::array< std::pair< std::string, backend >, 7 > & getSyclBeMap ()
constexpr const char * getStrOrNullptr (const char *Str)
template<>
cl_uint context_impl::get_info< info::context::reference_count > () const
template<>
platform context_impl::get_info< info::context::platform > () const
template<>
std::vector< cl::sycl::device > context_impl::get_info< info::context::devices > () const
template<>
std::vector< cl::sycl::memory_order > context_impl::get_info< info::context::atomic_memory_order_capabilities > () const
template<>
std::vector< cl::sycl::memory_scope > context_impl::get_info< info::context::atomic_memory_scope_capabilities > () const
std::vector< std::string_view > tokenize (const std::string &Filter, const std::string &Delim)
std::vector< info::fp_config > read_fp_bitfield (cl_device_fp_config bits)
std::vector< info::partition_affinity_domain > read_domain_bitfield (cl_device_affinity_domain bits)
std::vector< info::execution_capability > read_execution_bitfield (cl_device_exec_capabilities bits)
static bool is_sycl_partition_property (info::partition_property PP)
template<info::device param>
info::param_traits< info::device, param >::return_type get_device_info_host ()=delete
template<>
info::device_type get_device_info_host< info::device::device_type > ()
template<>
cl_uint get_device_info_host< info::device::vendor_id > ()
template<>
cl_uint get_device_info_host< info::device::max_compute_units > ()
template<>
cl_uint get_device_info_host< info::device::max_work_item_dimensions > ()
template<>
id< 3 > get_device_info_host< info::device::max_work_item_sizes > ()
template<>
constexpr size_t get_device_info_host< info::device::ext_oneapi_max_global_work_groups > ()
template<>
id< 1 > get_device_info_host< info::device::ext_oneapi_max_work_groups_1d > ()
template<>
id< 2 > get_device_info_host< info::device::ext_oneapi_max_work_groups_2d > ()
template<>
id< 3 > get_device_info_host< info::device::ext_oneapi_max_work_groups_3d > ()
template<>
size_t get_device_info_host< info::device::max_work_group_size > ()
template<>
cl_uint get_device_info_host< info::device::preferred_vector_width_char > ()
template<>
cl_uint get_device_info_host< info::device::preferred_vector_width_short > ()
template<>
cl_uint get_device_info_host< info::device::preferred_vector_width_int > ()
template<>
cl_uint get_device_info_host< info::device::preferred_vector_width_long > ()
template<>
cl_uint get_device_info_host< info::device::preferred_vector_width_float > ()
template<>
cl_uint get_device_info_host< info::device::preferred_vector_width_double > ()
template<>
cl_uint get_device_info_host< info::device::preferred_vector_width_half > ()
template<>
cl_uint get_device_info_host< info::device::native_vector_width_char > ()
template<>
cl_uint get_device_info_host< info::device::native_vector_width_short > ()
template<>
cl_uint get_device_info_host< info::device::native_vector_width_int > ()
template<>
cl_uint get_device_info_host< info::device::native_vector_width_long > ()
template<>
cl_uint get_device_info_host< info::device::native_vector_width_float > ()
template<>
cl_uint get_device_info_host< info::device::native_vector_width_double > ()
template<>
cl_uint get_device_info_host< info::device::native_vector_width_half > ()
template<>
cl_uint get_device_info_host< info::device::max_clock_frequency > ()
template<>
cl_uint get_device_info_host< info::device::address_bits > ()
template<>
cl_ulong get_device_info_host< info::device::global_mem_size > ()
template<>
cl_ulong get_device_info_host< info::device::max_mem_alloc_size > ()
template<>
bool get_device_info_host< info::device::image_support > ()
template<>
bool get_device_info_host< info::device::atomic64 > ()
template<>
std::vector< memory_order > get_device_info_host< info::device::atomic_memory_order_capabilities > ()
template<>
std::vector< memory_scope > get_device_info_host< info::device::atomic_memory_scope_capabilities > ()
template<>
cl_uint get_device_info_host< info::device::max_read_image_args > ()
template<>
cl_uint get_device_info_host< info::device::max_write_image_args > ()
template<>
size_t get_device_info_host< info::device::image2d_max_width > ()
template<>
size_t get_device_info_host< info::device::image2d_max_height > ()
template<>
size_t get_device_info_host< info::device::image3d_max_width > ()
template<>
size_t get_device_info_host< info::device::image3d_max_height > ()
template<>
size_t get_device_info_host< info::device::image3d_max_depth > ()
template<>
size_t get_device_info_host< info::device::image_max_buffer_size > ()
template<>
size_t get_device_info_host< info::device::image_max_array_size > ()
template<>
cl_uint get_device_info_host< info::device::max_samplers > ()
template<>
size_t get_device_info_host< info::device::max_parameter_size > ()
template<>
cl_uint get_device_info_host< info::device::mem_base_addr_align > ()
template<>
std::vector< info::fp_config > get_device_info_host< info::device::half_fp_config > ()
template<>
std::vector< info::fp_config > get_device_info_host< info::device::single_fp_config > ()
template<>
std::vector< info::fp_config > get_device_info_host< info::device::double_fp_config > ()
template<>
info::global_mem_cache_type get_device_info_host< info::device::global_mem_cache_type > ()
template<>
cl_uint get_device_info_host< info::device::global_mem_cache_line_size > ()
template<>
cl_ulong get_device_info_host< info::device::global_mem_cache_size > ()
template<>
cl_ulong get_device_info_host< info::device::max_constant_buffer_size > ()
template<>
cl_uint get_device_info_host< info::device::max_constant_args > ()
template<>
info::local_mem_type get_device_info_host< info::device::local_mem_type > ()
template<>
cl_ulong get_device_info_host< info::device::local_mem_size > ()
template<>
bool get_device_info_host< info::device::error_correction_support > ()
template<>
bool get_device_info_host< info::device::host_unified_memory > ()
template<>
size_t get_device_info_host< info::device::profiling_timer_resolution > ()
template<>
bool get_device_info_host< info::device::is_endian_little > ()
template<>
bool get_device_info_host< info::device::is_available > ()
template<>
bool get_device_info_host< info::device::is_compiler_available > ()
template<>
bool get_device_info_host< info::device::is_linker_available > ()
template<>
std::vector< info::execution_capability > get_device_info_host< info::device::execution_capabilities > ()
template<>
bool get_device_info_host< info::device::queue_profiling > ()
template<>
std::vector< kernel_id > get_device_info_host< info::device::built_in_kernel_ids > ()
template<>
std::vector< std::string > get_device_info_host< info::device::built_in_kernels > ()
template<>
platform get_device_info_host< info::device::platform > ()
template<>
std::string get_device_info_host< info::device::name > ()
template<>
std::string get_device_info_host< info::device::vendor > ()
template<>
std::string get_device_info_host< info::device::driver_version > ()
template<>
std::string get_device_info_host< info::device::profile > ()
template<>
std::string get_device_info_host< info::device::version > ()
template<>
std::string get_device_info_host< info::device::opencl_c_version > ()
template<>
std::vector< std::string > get_device_info_host< info::device::extensions > ()
template<>
size_t get_device_info_host< info::device::printf_buffer_size > ()
template<>
bool get_device_info_host< info::device::preferred_interop_user_sync > ()
template<>
device get_device_info_host< info::device::parent_device > ()
template<>
cl_uint get_device_info_host< info::device::partition_max_sub_devices > ()
template<>
std::vector< info::partition_property > get_device_info_host< info::device::partition_properties > ()
template<>
std::vector< info::partition_affinity_domain > get_device_info_host< info::device::partition_affinity_domains > ()
template<>
info::partition_property get_device_info_host< info::device::partition_type_property > ()
template<>
info::partition_affinity_domain get_device_info_host< info::device::partition_type_affinity_domain > ()
template<>
cl_uint get_device_info_host< info::device::reference_count > ()
template<>
cl_uint get_device_info_host< info::device::max_num_sub_groups > ()
template<>
std::vector< size_t > get_device_info_host< info::device::sub_group_sizes > ()
template<>
bool get_device_info_host< info::device::sub_group_independent_forward_progress > ()
template<>
bool get_device_info_host< info::device::kernel_kernel_pipe_support > ()
template<>
std::string get_device_info_host< info::device::backend_version > ()
template<>
bool get_device_info_host< info::device::usm_device_allocations > ()
template<>
bool get_device_info_host< info::device::usm_host_allocations > ()
template<>
bool get_device_info_host< info::device::usm_shared_allocations > ()
template<>
bool get_device_info_host< info::device::usm_restricted_shared_allocations > ()
template<>
bool get_device_info_host< info::device::usm_system_allocations > ()
template<>
bool get_device_info_host< info::device::ext_intel_mem_channel > ()
cl_uint get_native_vector_width (size_t idx)
template<>
std::string get_device_info_host< info::device::ext_intel_pci_address > ()
template<>
cl_uint get_device_info_host< info::device::ext_intel_gpu_eu_count > ()
template<>
cl_uint get_device_info_host< info::device::ext_intel_gpu_eu_simd_width > ()
template<>
cl_uint get_device_info_host< info::device::ext_intel_gpu_slices > ()
template<>
cl_uint get_device_info_host< info::device::ext_intel_gpu_subslices_per_slice > ()
template<>
cl_uint get_device_info_host< info::device::ext_intel_gpu_eu_count_per_subslice > ()
template<>
cl_uint get_device_info_host< info::device::ext_intel_gpu_hw_threads_per_eu > ()
template<>
cl_ulong get_device_info_host< info::device::ext_intel_max_mem_bandwidth > ()
template<>
bool get_device_info_host< info::device::ext_oneapi_srgb > ()
template<>
detail::uuid_type get_device_info_host< info::device::ext_intel_device_info_uuid > ()
template<>
cl_ulong event_impl::get_profiling_info< info::event_profiling::command_submit > () const
template<>
cl_ulong event_impl::get_profiling_info< info::event_profiling::command_start > () const
template<>
cl_ulong event_impl::get_profiling_info< info::event_profiling::command_end > () const
template<>
cl_uint event_impl::get_info< info::event::reference_count > () const
template<>
info::event_command_status event_impl::get_info< info::event::command_execution_status > () const
static uint64_t getTimestamp ()
bool match_types (const info::device_type &l, const info::device_type &r)
info::device_type get_forced_type ()
void releaseDefaultContexts ()
void shutdown ()
__attribute__ ((destructor(110))) static void syclUnload()
std::vector< RT::PiEvent > getOrWaitEvents (std::vector< cl::sycl::event > DepEvents, ContextImplPtr Context)
template<info::device Param>
static bool checkImageValueRange (const std::vector< device > &Devices, const size_t Value)
template<typename T , typename... Args>
static bool checkAnyImpl (T)
template<typename ValT , typename VarT , typename... Args>
static bool checkAnyImpl (ValT Value, VarT Variant, Args... Arguments)
template<typename T , typename... Args>
static bool checkAny (const T Value, Args... Arguments)
template<typename T >
static void getImageInfo (const ContextImplPtr Context, RT::PiMemImageInfo Info, T &Dest, RT::PiMem InteropMemObject)
static bool checkAllDevicesAreInContext (const std::vector< device > &Devices, const context &Context)
static bool checkAllDevicesHaveAspect (const std::vector< device > &Devices, aspect Aspect)
template<>
context kernel_impl::get_info< info::kernel::context > () const
template<info::kernel_device_specific Param>
info::param_traits< info::kernel_device_specific, Param >::return_type get_kernel_device_specific_info_host (const cl::sycl::device &Device)
template<>
cl::sycl::range< 3 > get_kernel_device_specific_info_host< info::kernel_device_specific::global_work_size > (const cl::sycl::device &)
template<>
size_t get_kernel_device_specific_info_host< info::kernel_device_specific::work_group_size > (const cl::sycl::device &Dev)
template<>
cl::sycl::range< 3 > get_kernel_device_specific_info_host< info::kernel_device_specific::compile_work_group_size > (const cl::sycl::device &)
template<>
size_t get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple > (const cl::sycl::device &Dev)
template<>
cl_ulong get_kernel_device_specific_info_host< info::kernel_device_specific::private_mem_size > (const cl::sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::ext_codeplay_num_regs > (const cl::sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::max_num_sub_groups > (const cl::sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::compile_num_sub_groups > (const cl::sycl::device &)
template<>
uint32_t get_kernel_device_specific_info_host< info::kernel_device_specific::compile_sub_group_size > (const cl::sycl::device &)
void memBufferCreateHelper (const plugin &Plugin, pi_context Ctx, pi_mem_flags Flags, size_t Size, void *HostPtr, pi_mem *RetMem, const pi_mem_properties *Props=nullptr)
void memReleaseHelper (const plugin &Plugin, pi_mem Mem)
void memBufferMapHelper (const plugin &Plugin, pi_queue command_queue, pi_mem buffer, pi_bool blocking_map, pi_map_flags map_flags, size_t offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event, void **ret_map)
void memUnmapHelper (const plugin &Plugin, pi_queue command_queue, pi_mem memobj, void *mapped_ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
uint64_t emitMemAllocBeginTrace (uintptr_t ObjHandle, size_t AllocSize, size_t GuardZone)
void emitMemAllocEndTrace (uintptr_t ObjHandle, uintptr_t AllocPtr, size_t AllocSize, size_t GuardZone, uint64_t CorrelationID)
uint64_t emitMemReleaseBeginTrace (uintptr_t ObjHandle, uintptr_t AllocPtr)
void emitMemReleaseEndTrace (uintptr_t ObjHandle, uintptr_t AllocPtr, uint64_t CorrelationID)
static void waitForEvents (const std::vector< EventImplPtr > &Events)
static RT::PiMemFlags getMemObjCreationFlags (void *UserPtr, bool HostPtrReadOnly)
void prepTermPositions (TermPositions &pos, int Dimensions, detail::SYCLMemObjI::MemObjType Type)
void copyH2D (SYCLMemObjI *SYCLMemObj, char *SrcMem, QueueImplPtr, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, RT::PiMem DstMem, QueueImplPtr TgtQueue, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< RT::PiEvent > DepEvents, RT::PiEvent &OutEvent)
void copyD2H (SYCLMemObjI *SYCLMemObj, RT::PiMem SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char *DstMem, QueueImplPtr, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< RT::PiEvent > DepEvents, RT::PiEvent &OutEvent)
void copyD2D (SYCLMemObjI *SYCLMemObj, RT::PiMem SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, RT::PiMem DstMem, QueueImplPtr, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 >, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< RT::PiEvent > DepEvents, RT::PiEvent &OutEvent)
static void copyH2H (SYCLMemObjI *, char *SrcMem, QueueImplPtr, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char *DstMem, QueueImplPtr, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< RT::PiEvent >, RT::PiEvent &)
static bool parsePersistentCacheConfig ()
std::string getDirName (const char *Path)
template void * getPluginOpaqueData< cl::sycl::backend::ext_intel_esimd_emulator > (void *)
static bool IsBannedPlatform (platform Platform)
static void filterDeviceFilter (std::vector< RT::PiDevice > &PiDevices, RT::PiPlatform Platform)
template<info::platform param>
info::param_traits< info::platform, param >::return_type get_platform_info_host ()=delete
template<>
std::string get_platform_info_host< info::platform::profile > ()
template<>
std::string get_platform_info_host< info::platform::version > ()
template<>
std::string get_platform_info_host< info::platform::name > ()
template<>
std::string get_platform_info_host< info::platform::vendor > ()
template<>
std::vector< std::string > get_platform_info_host< info::platform::extensions > ()
template<typename... Ts>
constexpr size_t totalSize (const std::tuple< Ts... > &)
template<PiApiKind Kind, typename... ArgsT>
auto packCallArguments (ArgsT &&... Args)
template<>
cl_uint program_impl::get_info< info::program::reference_count > () const
template<>
context program_impl::get_info< info::program::context > () const
template<>
std::vector< device > program_impl::get_info< info::program::devices > () const
static constexpr char UseSpvEnv ("SYCL_USE_KERNEL_SPV")
static void enableITTAnnotationsIfNeeded (const RT::PiProgram &Prog, const plugin &Plugin)
This function enables ITT annotations in SPIR-V module by setting a specialization constant if INTEL_LIBITTNOTIFY64 env variable is set.
static RT::PiProgram createBinaryProgram (const ContextImplPtr Context, const device &Device, const unsigned char *Data, size_t DataLen, const std::vector< pi_device_binary_property > Metadata)
static RT::PiProgram createSpirvProgram (const ContextImplPtr Context, const unsigned char *Data, size_t DataLen)
template<typename ExceptionT , typename RetT >
RetT * waitUntilBuilt (KernelProgramCache &Cache, KernelProgramCache::BuildResult< RetT > *BuildResult)
template<typename RetT , typename ExceptionT , typename KeyT , typename AcquireFT , typename GetCacheFT , typename BuildFT >
KernelProgramCache::BuildResult< RetT > * getOrBuild (KernelProgramCache &KPCache, KeyT &&CacheKey, AcquireFT &&Acquire, GetCacheFT &&GetCache, BuildFT &&Build)
Try to fetch entity (kernel or program) from cache.
static bool isDeviceBinaryTypeSupported (const context &C, RT::PiDeviceBinaryType Format)
static const char * getFormatStr (RT::PiDeviceBinaryType Format)
static void appendLinkOptionsFromImage (std::string &LinkOpts, const RTDeviceBinaryImage &Img)
static void appendCompileOptionsFromImage (std::string &CompileOpts, const RTDeviceBinaryImage &Img)
static void applyOptionsFromImage (std::string &CompileOpts, std::string &LinkOpts, const RTDeviceBinaryImage &Img)
static void applyCompileOptionsFromEnvironment (std::string &CompileOpts)
static void applyLinkOptionsFromEnvironment (std::string &LinkOpts)
static void applyOptionsFromEnvironment (std::string &CompileOpts, std::string &LinkOpts)
static void emitBuiltProgramInfo (const pi_program &Prog, const ContextImplPtr &Context)
Emits information about built programs if the appropriate contitions are met, namely when SYCL_RT_WARNING_LEVEL is greater than or equal to 2.
static bool loadDeviceLib (const ContextImplPtr Context, const char *Name, RT::PiProgram &Prog)
static const char * getDeviceLibFilename (DeviceLibExt Extension)
static const char * getDeviceLibExtensionStr (DeviceLibExt Extension)
static RT::PiProgram loadDeviceLibFallback (const ContextImplPtr Context, DeviceLibExt Extension, const RT::PiDevice &Device, std::map< std::pair< DeviceLibExt, RT::PiDevice >, RT::PiProgram > &CachedLibPrograms)
static bool isDeviceLibRequired (DeviceLibExt Ext, uint32_t DeviceLibReqMask)
static std::vector< RT::PiProgram > getDeviceLibPrograms (const ContextImplPtr Context, const RT::PiDevice &Device, std::map< std::pair< DeviceLibExt, RT::PiDevice >, RT::PiProgram > &CachedLibPrograms, uint32_t DeviceLibReqMask)
static ProgramManager::KernelArgMask createKernelArgMask (const pi::ByteArray &Bytes)
static bundle_state getBinImageState (const RTDeviceBinaryImage *BinImage)
static bool compatibleWithDevice (RTDeviceBinaryImage *BinImage, const device &Dev)
template<>
cl_uint queue_impl::get_info< info::queue::reference_count > () const
template<>
context queue_impl::get_info< info::queue::context > () const
template<>
device queue_impl::get_info< info::queue::device > () const
static event prepareUSMEvent (const std::shared_ptr< detail::queue_impl > &QueueImpl, RT::PiEvent NativeEvent)
static event createDiscardedEvent ()
static std::string demangleKernelName (std::string Name)
static std::string deviceToString (device Device)
static std::string accessModeToString (access::mode Mode)
static std::vector< RT::PiEvent > getPiEvents (const std::vector< EventImplPtr > &EventImpls)
static void flushCrossQueueDeps (const std::vector< EventImplPtr > &EventImpls, const QueueImplPtr &Queue)
static std::string cgTypeToString (detail::CG::CGTYPE Type)
static void adjustNDRangePerKernel (NDRDescT &NDR, RT::PiKernel Kernel, const device_impl &DeviceImpl)
static void ReverseRangeDimensionsForKernel (NDRDescT &NDR)
static pi_result SetKernelParamsAndLaunch (const QueueImplPtr &Queue, std::vector< ArgDesc > &Args, const std::shared_ptr< device_image_impl > &DeviceImageImpl, RT::PiKernel Kernel, NDRDescT &NDRDesc, std::vector< RT::PiEvent > &RawEvents, RT::PiEvent *OutEvent, const ProgramManager::KernelArgMask &EliminatedArgMask, const std::function< void *(Requirement *Req)> &getMemAllocationFunc)
void DispatchNativeKernel (void *Blob)
cl_int enqueueImpKernel (const QueueImplPtr &Queue, NDRDescT &NDRDesc, std::vector< ArgDesc > &Args, const std::shared_ptr< detail::kernel_bundle_impl > &KernelBundleImplPtr, const std::shared_ptr< detail::kernel_impl > &MSyclKernel, const std::string &KernelName, const detail::OSModuleHandle &OSModuleHandle, std::vector< RT::PiEvent > &RawEvents, RT::PiEvent *OutEvent, const std::function< void *(Requirement *Req)> &getMemAllocationFunc)
static bool doOverlap (const Requirement *LHS, const Requirement *RHS)
Checks whether two requirements overlap or not.
static bool sameCtx (const ContextImplPtr &LHS, const ContextImplPtr &RHS)
static bool IsSuitableSubReq (const Requirement *Req)
Checks if current requirement is requirement for sub buffer.
static bool isAccessModeAllowed (access::mode Required, access::mode Current)
Checks if the required access mode is allowed under the current one.
static access::mode combineAccessModes (access::mode A, access::mode B)
Combines two access modes into a single one that allows both.
static bool markNodeAsVisited (Command *Cmd, std::vector< Command * > &Visited)
static void unmarkVisitedNodes (std::vector< Command * > &Visited)
static void handleVisitedNodes (std::vector< Command * > &Visited)
static void printDotRecursive (std::fstream &Stream, std::vector< Command * > &Visited, Command *Cmd)
static Command * insertMapUnmapForLinkedCmds (AllocaCommandBase *AllocaCmdSrc, AllocaCommandBase *AllocaCmdDst, access::mode MapMode)
static bool checkHostUnifiedMemory (const ContextImplPtr &Ctx)
static bool isInteropHostTask (const std::unique_ptr< ExecCGCommand > &Cmd)
static void combineAccessModesOfReqs (std::vector< Requirement * > &Reqs)
static Command * getCommand (const EventImplPtr &Event)
static bool doOverlap (const Requirement *LHS, const Requirement *RHS)
static bool isHostAccessorCmd (Command *Cmd)
static void deallocateStreams (std::vector< std::shared_ptr< stream_impl >> &StreamsToDeallocate)
void initStream (StreamImplPtr Stream, QueueImplPtr Queue)
void stableSerializeSpecConstRegistry (const SpecConstRegistryT &Reg, SerializedObj &Dst)
std::ostream & operator<< (std::ostream &Out, const spec_constant_impl &V)
void force_type (info::device_type &t, const info::device_type &ft)
ESIMDDeviceInterface * getESIMDDeviceInterface ()
ext::oneapi::device_func_ptr_holder_t getDeviceFunctionPointerImpl (device &D, program &P, const char *FuncName)
Variables
constexpr unsigned int ShiftBitsForVersion = 24
constexpr KernelSetId SpvFileKSId = 0
constexpr KernelSetId LastKSId = SpvFileKSId
template<typename T , typename U >
constexpr bool is_same_v = std::is_same<T, U>::value
template<typename T , typename U >
constexpr bool is_convertible_v = std::is_convertible<T, U>::value
template<typename F , typename SuggestedArgType >
decltype(member_ptr_helper(&F::operator())) argument_helper (int)
static constexpr FmtFlags Dec = 0x0001
static constexpr FmtFlags Hex = 0x0002
static constexpr FmtFlags Oct = 0x0004
static constexpr FmtFlags ShowBase = 0x0008
static constexpr FmtFlags ShowPos = 0x0010
static constexpr FmtFlags Fixed = 0x0020
static constexpr FmtFlags Scientific = 0x0040
static constexpr FmtFlags BaseField = Dec | Hex | Oct
static constexpr FmtFlags FloatField = Scientific | Fixed
constexpr size_t MAX_FLOATING_POINT_DIGITS = 24
constexpr size_t MAX_INTEGRAL_DIGITS = 23
constexpr const char * VEC_ELEMENT_DELIMITER = ", "
constexpr char VEC_OPEN_BRACE = '{'
constexpr char VEC_CLOSE_BRACE = '}'
constexpr size_t MAX_DIMENSIONS = 3
constexpr size_t MAX_ARRAY_SIZE
constexpr unsigned FLUSH_BUF_OFFSET_SIZE = 2
constexpr static access::address_space GlobalBufAS
constexpr static int GlobalBufDim = 1
constexpr static access::address_space GlobalOffsetAS
constexpr static int GlobalOffsetDim = 1
constexpr size_t MAX_ITEM_SIZE = 2 * MAX_ARRAY_SIZE + 20
constexpr char BackendNameKeyName [] = "BackendName"
constexpr char DeviceTypeKeyName [] = "DeviceType"
constexpr char DeviceVendorIdKeyName [] = "DeviceVendorId"
constexpr char DriverVersionKeyName [] = "DriverVersion"
constexpr char PlatformVersionKeyName [] = "PlatformVersion"
constexpr char DeviceNameKeyName [] = "DeviceName"
constexpr char PlatformNameKeyName [] = "PlatformName"
constexpr std::array< const char *, 7 > SupportedAllowListKeyNames
constexpr bool ConfigFromEnvEnabled = true
constexpr bool ConfigFromFileEnabled = true
constexpr bool ConfigFromCompileDefEnabled = true
constexpr int MAX_CONFIG_NAME = 256
constexpr int MAX_CONFIG_VALUE = 1024
static constexpr int DbgProgMgr = 0
static constexpr uint32_t ITTSpecConstId = 0xFF747469
static constexpr size_t MaxNumQueues = 256
Sets max number of queues supported by FPGA RT.
constexpr CUDAContextT DefaultContextType = CUDAContextT::custom
Default context type created for CUDA backend.
constexpr const char * SYCL_STREAM_NAME = "sycl"
constexpr const char * SYCL_PICALL_STREAM_NAME = "sycl.pi"
constexpr const char * SYCL_PIDEBUGCALL_STREAM_NAME = "sycl.pi.debug"
constexpr auto SYCL_MEM_ALLOC_STREAM_NAME
constexpr const char * SYCL_BUFFER_STREAM_NAME
Typedef Documentation
AccessorImplPtr
using cl::sycl::detail::AccessorImplPtr = typedef std::shared_ptr<AccessorImplHost>
Definition at line 130 of file accessor_impl.hpp.
add_pointer_t
template<typename T > using cl::sycl::detail::add_pointer_t = typedef typename std::add_pointer<T>::type
Definition at line 37 of file stl_type_traits.hpp.
address_space_list
template<access::address_space... V> using cl::sycl::detail::address_space_list = typedef value_list<access::address_space, V...>
Definition at line 82 of file type_list.hpp.
allocator_pointer_t
template<typename T > using cl::sycl::detail::allocator_pointer_t = typedef typename std::allocator_traits<T>::pointer
Definition at line 49 of file stl_type_traits.hpp.
allocator_value_type_t
template<typename T > using cl::sycl::detail::allocator_value_type_t = typedef typename std::allocator_traits<T>::value_type
Definition at line 46 of file stl_type_traits.hpp.
AllowListParsedT
using cl::sycl::detail::AllowListParsedT = typedef std::vector<DeviceDescT>
Definition at line 23 of file allowlist.hpp.
bool_constant
template<bool V> using cl::sycl::detail::bool_constant = typedef std::integral_constant<bool, V>
Definition at line 40 of file stl_type_traits.hpp.
change_base_type_t
template<typename T , typename B > using cl::sycl::detail::change_base_type_t = typedef typename change_base_type<T, B>::type
Definition at line 110 of file type_traits.hpp.
common_rel_ret_t
template<typename T > using cl::sycl::detail::common_rel_ret_t = typedef conditional_t<is_vgentype<T>::value, make_singed_integer_t<T>, int>
Definition at line 506 of file generic_type_traits.hpp.
conditional_t
template<bool B, class T , class F > using cl::sycl::detail::conditional_t = typedef typename std::conditional<B, T, F>::type
Definition at line 27 of file stl_type_traits.hpp.
const_if_const_AS
template<access::address_space AS, class DataT > using cl::sycl::detail::const_if_const_AS = typedef DataT
Definition at line 348 of file type_traits.hpp.
ContextImplPtr
typedef std::shared_ptr< detail::context_impl > cl::sycl::detail::ContextImplPtr
Definition at line 32 of file memory_manager.hpp.
convert_data_type
template<typename T , typename B > using cl::sycl::detail::convert_data_type = typedef convert_data_type_impl<T, B, T>
Definition at line 289 of file generic_type_traits.hpp.
ConvertToOpenCLType_t
template<typename T > using cl::sycl::detail::ConvertToOpenCLType_t = typedef conditional_t< TryToGetVectorT<SelectMatchingOpenCLType_t<T> >::value, typename TryToGetVectorT<SelectMatchingOpenCLType_t<T> >::type, conditional_t< TryToGetPointerT<SelectMatchingOpenCLType_t<T> >::value, typename TryToGetPointerVecT<SelectMatchingOpenCLType_t<T> >::type, SelectMatchingOpenCLType_t<T> >>
Definition at line 472 of file generic_type_traits.hpp.
copy_cv_qualifiers_t
template<typename T , typename R > using cl::sycl::detail::copy_cv_qualifiers_t = typedef typename copy_cv_qualifiers<T, R>::type
Definition at line 67 of file type_traits.hpp.
DeviceDescT
using cl::sycl::detail::DeviceDescT = typedef std::map<std::string, std::string>
Definition at line 22 of file allowlist.hpp.
DeviceImageImplPtr
using cl::sycl::detail::DeviceImageImplPtr = typedef std::shared_ptr<device_image_impl>
Definition at line 67 of file kernel_bundle.hpp.
DeviceImplPtr
typedef std::shared_ptr< detail::device_impl > cl::sycl::detail::DeviceImplPtr
Definition at line 55 of file program_manager.hpp.
DevImgSelectorImpl
using cl::sycl::detail::DevImgSelectorImpl = typedef std::function<bool(const detail::DeviceImageImplPtr &DevImgImpl)>
Definition at line 467 of file kernel_bundle.hpp.
empty_type_list
using cl::sycl::detail::empty_type_list = typedef type_list<>
Definition at line 25 of file type_list.hpp.
enable_if_t
template<bool B, class T = void> using cl::sycl::detail::enable_if_t = typedef typename std::enable_if<B, T>::type
Definition at line 24 of file stl_type_traits.hpp.
EnableIfFP
template<class F , class T = void> using cl::sycl::detail::EnableIfFP = typedef typename detail::enable_if_t<std::is_same<F, float>::value || std::is_same<F, double>::value || std::is_same<F, half>::value, T>
Definition at line 65 of file stream.hpp.
EnableIfImgAccDataT
template<typename DataT > using cl::sycl::detail::EnableIfImgAccDataT = typedef typename detail::enable_if_t<is_validImageDataT<DataT>::value, DataT>
Definition at line 67 of file image_impl.hpp.
EnableIfSwizzleVec
template<typename T > using cl::sycl::detail::EnableIfSwizzleVec = typedef typename detail::enable_if_t<IsSwizzleOp<T>::value, typename IsSwizzleOp<T>::Type>
Definition at line 659 of file stream.hpp.
EventImplPtr
typedef std::shared_ptr< detail::event_impl > cl::sycl::detail::EventImplPtr
Definition at line 31 of file memory_manager.hpp.
find_larger_type_t
template<typename TL , typename T > using cl::sycl::detail::find_larger_type_t = typedef find_type_t<TL, is_type_size_greater, T>
Definition at line 128 of file type_list.hpp.
find_same_size_type_t
template<typename TL , typename T > using cl::sycl::detail::find_same_size_type_t = typedef find_type_t<TL, is_type_size_equal, T>
Definition at line 122 of file type_list.hpp.
find_smaller_type_t
template<typename TL , typename T > using cl::sycl::detail::find_smaller_type_t = typedef find_type_t<TL, is_type_size_less, T>
Definition at line 125 of file type_list.hpp.
find_twice_as_large_type_t
template<typename TL , typename T > using cl::sycl::detail::find_twice_as_large_type_t = typedef find_type_t<TL, is_type_size_double_of, T>
Definition at line 134 of file type_list.hpp.
find_twice_as_small_type_t
template<typename TL , typename T > using cl::sycl::detail::find_twice_as_small_type_t = typedef find_type_t<TL, is_type_size_half_of, T>
Definition at line 131 of file type_list.hpp.
find_type_t
template<typename TL , template< typename, typename > class C, typename T > using cl::sycl::detail::find_type_t = typedef typename find_type<TL, C, T>::type
Definition at line 119 of file type_list.hpp.
FmtFlags
using cl::sycl::detail::FmtFlags = typedef unsigned int
Definition at line 21 of file stream.hpp.
GlobalBufAccessorT
using cl::sycl::detail::GlobalBufAccessorT = typedef accessor<char, 1, cl::sycl::access::mode::read_write, cl::sycl::access::target::global_buffer, cl::sycl::access::placeholder::false_t>
Definition at line 69 of file stream.hpp.
GlobalBufPtrType
using cl::sycl::detail::GlobalBufPtrType = typedef typename detail::DecoratedType<char, GlobalBufAS>::type *
Definition at line 74 of file stream.hpp.
GlobalOffsetAccessorT
using cl::sycl::detail::GlobalOffsetAccessorT = typedef accessor<unsigned, 1, cl::sycl::access::mode::atomic, cl::sycl::access::target::global_buffer, cl::sycl::access::placeholder::false_t>
Definition at line 80 of file stream.hpp.
GlobalOffsetPtrType
using cl::sycl::detail::GlobalOffsetPtrType = typedef typename detail::DecoratedType<unsigned, GlobalBufAS>::type *
Definition at line 85 of file stream.hpp.
head_t
template<typename T > using cl::sycl::detail::head_t = typedef typename T::head
Definition at line 18 of file type_list.hpp.
image_allocator
using cl::sycl::detail::image_allocator = typedef aligned_allocator<byte>
Definition at line 39 of file image_impl.hpp.
int_constant
template<int V> using cl::sycl::detail::int_constant = typedef std::integral_constant<int, V>
Definition at line 69 of file type_traits.hpp.
is_arithmetic_or_complex
template<typename T > using cl::sycl::detail::is_arithmetic_or_complex = typedef std::integral_constant<bool, sycl::detail::is_complex<T>::value || sycl::detail::is_arithmetic<T>::value>
Definition at line 121 of file group_algorithm.hpp.
is_charn
template<typename T > using cl::sycl::detail::is_charn = typedef is_contained<T, gtl::vector_default_char_list>
Definition at line 79 of file generic_type_traits.hpp.
is_doublen
template<typename T > using cl::sycl::detail::is_doublen = typedef is_contained<T, gtl::vector_double_list>
Definition at line 29 of file generic_type_traits.hpp.
is_float_to_float
template<typename T , typename R > using cl::sycl::detail::is_float_to_float = typedef std::integral_constant<bool, detail::is_floating_point<T>::value && detail::is_floating_point<R>::value>
Definition at line 259 of file types.hpp.
is_float_to_int
template<typename T , typename R > using cl::sycl::detail::is_float_to_int = typedef std::integral_constant<bool, detail::is_floating_point<T>::value && std::is_integral<R>::value>
Definition at line 254 of file types.hpp.
is_floatn
template<typename T > using cl::sycl::detail::is_floatn = typedef is_contained<T, gtl::vector_float_list>
Definition at line 24 of file generic_type_traits.hpp.
is_gen_based_on_type_sizeof
template<typename T , int N, template< typename > class S> using cl::sycl::detail::is_gen_based_on_type_sizeof = typedef bool_constant<S<T>::value && (sizeof(vector_element_t<T>) == N)>
Definition at line 206 of file type_traits.hpp.
is_genchar
template<typename T > using cl::sycl::detail::is_genchar = typedef is_contained<T, gtl::char_list>
Definition at line 93 of file generic_type_traits.hpp.
is_gencross
template<typename T > using cl::sycl::detail::is_gencross = typedef is_contained<T, gtl::cross_floating_list>
Definition at line 76 of file generic_type_traits.hpp.
is_gencrossdouble
template<typename T > using cl::sycl::detail::is_gencrossdouble = typedef is_contained<T, gtl::cross_double_list>
Definition at line 70 of file generic_type_traits.hpp.
is_gencrossfloat
template<typename T > using cl::sycl::detail::is_gencrossfloat = typedef is_contained<T, gtl::cross_float_list>
Definition at line 67 of file generic_type_traits.hpp.
is_gencrosshalf
template<typename T > using cl::sycl::detail::is_gencrosshalf = typedef is_contained<T, gtl::cross_half_list>
Definition at line 73 of file generic_type_traits.hpp.
is_genfloat
template<typename T > using cl::sycl::detail::is_genfloat = typedef is_contained<T, gtl::floating_list>
Definition at line 37 of file generic_type_traits.hpp.
is_genfloatd
template<typename T > using cl::sycl::detail::is_genfloatd = typedef is_contained<T, gtl::double_list>
Definition at line 31 of file generic_type_traits.hpp.
is_genfloatf
template<typename T > using cl::sycl::detail::is_genfloatf = typedef is_contained<T, gtl::float_list>
Definition at line 26 of file generic_type_traits.hpp.
is_genfloath
template<typename T > using cl::sycl::detail::is_genfloath = typedef is_contained<T, gtl::half_list>
Definition at line 35 of file generic_type_traits.hpp.
is_genfloatptr
template<typename T > using cl::sycl::detail::is_genfloatptr = typedef bool_constant< is_pointer<T>::value && is_genfloat<remove_pointer_t<T> >::value && is_address_space_compliant<T, gvl::nonconst_address_space_list>::value>
Definition at line 225 of file generic_type_traits.hpp.
is_gengeodouble
template<typename T > using cl::sycl::detail::is_gengeodouble = typedef is_contained<T, gtl::geo_double_list>
Definition at line 49 of file generic_type_traits.hpp.
is_gengeofloat
template<typename T > using cl::sycl::detail::is_gengeofloat = typedef is_contained<T, gtl::geo_float_list>
Definition at line 46 of file generic_type_traits.hpp.
is_gengeohalf
template<typename T > using cl::sycl::detail::is_gengeohalf = typedef is_contained<T, gtl::geo_half_list>
Definition at line 51 of file generic_type_traits.hpp.
is_genint
template<typename T > using cl::sycl::detail::is_genint = typedef is_contained<T, gtl::signed_int_list>
Definition at line 116 of file generic_type_traits.hpp.
is_geninteger
template<typename T > using cl::sycl::detail::is_geninteger = typedef is_contained<T, gtl::integer_list>
Definition at line 147 of file generic_type_traits.hpp.
is_geninteger16bit
template<typename T > using cl::sycl::detail::is_geninteger16bit = typedef is_gen_based_on_type_sizeof<T, 2, is_geninteger>
Definition at line 209 of file generic_type_traits.hpp.
is_geninteger32bit
template<typename T > using cl::sycl::detail::is_geninteger32bit = typedef is_gen_based_on_type_sizeof<T, 4, is_geninteger>
Definition at line 212 of file generic_type_traits.hpp.
is_geninteger64bit
template<typename T > using cl::sycl::detail::is_geninteger64bit = typedef is_gen_based_on_type_sizeof<T, 8, is_geninteger>
Definition at line 215 of file generic_type_traits.hpp.
is_geninteger8bit
template<typename T > using cl::sycl::detail::is_geninteger8bit = typedef is_gen_based_on_type_sizeof<T, 1, is_geninteger>
Definition at line 206 of file generic_type_traits.hpp.
is_genintptr
template<typename T > using cl::sycl::detail::is_genintptr = typedef bool_constant< is_pointer<T>::value && is_genint<remove_pointer_t<T> >::value && is_address_space_compliant<T, gvl::nonconst_address_space_list>::value>
Definition at line 220 of file generic_type_traits.hpp.
is_genlong
template<typename T > using cl::sycl::detail::is_genlong = typedef is_contained<T, gtl::signed_long_list>
Definition at line 127 of file generic_type_traits.hpp.
is_genlonglong
template<typename T > using cl::sycl::detail::is_genlonglong = typedef is_contained<T, gtl::signed_longlong_list>
Definition at line 139 of file generic_type_traits.hpp.
is_genptr
template<typename T > using cl::sycl::detail::is_genptr = typedef bool_constant< is_pointer<T>::value && is_gentype<remove_pointer_t<T> >::value && is_address_space_compliant<T, gvl::nonconst_address_space_list>::value>
Definition at line 230 of file generic_type_traits.hpp.
is_genshort
template<typename T > using cl::sycl::detail::is_genshort = typedef is_contained<T, gtl::signed_short_list>
Definition at line 99 of file generic_type_traits.hpp.
is_gentype
template<typename T > using cl::sycl::detail::is_gentype = typedef is_contained<T, gtl::basic_list>
Definition at line 173 of file generic_type_traits.hpp.
is_halfn
template<typename T > using cl::sycl::detail::is_halfn = typedef is_contained<T, gtl::vector_half_list>
Definition at line 33 of file generic_type_traits.hpp.
is_igenchar
template<typename T > using cl::sycl::detail::is_igenchar = typedef is_contained<T, gtl::signed_char_list>
Definition at line 88 of file generic_type_traits.hpp.
is_igeninteger
template<typename T > using cl::sycl::detail::is_igeninteger = typedef is_contained<T, gtl::signed_integer_list>
Definition at line 150 of file generic_type_traits.hpp.
is_igeninteger16bit
template<typename T > using cl::sycl::detail::is_igeninteger16bit = typedef is_gen_based_on_type_sizeof<T, 2, is_igeninteger>
Definition at line 185 of file generic_type_traits.hpp.
is_igeninteger32bit
template<typename T > using cl::sycl::detail::is_igeninteger32bit = typedef is_gen_based_on_type_sizeof<T, 4, is_igeninteger>
Definition at line 188 of file generic_type_traits.hpp.
is_igeninteger64bit
template<typename T > using cl::sycl::detail::is_igeninteger64bit = typedef is_gen_based_on_type_sizeof<T, 8, is_igeninteger>
Definition at line 191 of file generic_type_traits.hpp.
is_igeninteger8bit
template<typename T > using cl::sycl::detail::is_igeninteger8bit = typedef is_gen_based_on_type_sizeof<T, 1, is_igeninteger>
Definition at line 182 of file generic_type_traits.hpp.
is_igenlonginteger
template<typename T > using cl::sycl::detail::is_igenlonginteger = typedef is_contained<T, gtl::signed_long_integer_list>
Definition at line 142 of file generic_type_traits.hpp.
is_int_to_float
template<typename T , typename R > using cl::sycl::detail::is_int_to_float = typedef std::integral_constant<bool, std::is_integral<T>::value && detail::is_floating_point<R>::value>
Definition at line 249 of file types.hpp.
is_int_to_int
template<typename T , typename R > using cl::sycl::detail::is_int_to_int = typedef std::integral_constant<bool, std::is_integral<T>::value && std::is_integral<R>::value>
Definition at line 218 of file types.hpp.
is_intn
template<typename T > using cl::sycl::detail::is_intn = typedef is_contained<T, gtl::vector_signed_int_list>
Definition at line 114 of file generic_type_traits.hpp.
is_longlongn
template<typename T > using cl::sycl::detail::is_longlongn = typedef is_contained<T, gtl::vector_signed_longlong_list>
Definition at line 136 of file generic_type_traits.hpp.
is_longn
template<typename T > using cl::sycl::detail::is_longn = typedef is_contained<T, gtl::vector_signed_long_list>
Definition at line 125 of file generic_type_traits.hpp.
is_nan_type
template<typename T > using cl::sycl::detail::is_nan_type = typedef is_contained<T, gtl::nan_list>
Definition at line 232 of file generic_type_traits.hpp.
is_one_of_spaces
template<access::address_space AS, typename VL > using cl::sycl::detail::is_one_of_spaces = typedef is_contained_value<access::address_space, AS, VL>
Definition at line 85 of file type_list.hpp.
is_plus
template<typename T , typename BinaryOperation > using cl::sycl::detail::is_plus = typedef std::integral_constant< bool, std::is_same<BinaryOperation, sycl::plus<T> >::value || std::is_same<BinaryOperation, sycl::plus<void> >::value>
Definition at line 106 of file group_algorithm.hpp.
is_plus_if_complex
template<typename T , typename BinaryOperation > using cl::sycl::detail::is_plus_if_complex = typedef std::integral_constant<bool, (is_complex<T>::value ? is_plus<T, BinaryOperation>::value : std::true_type::value)>
Definition at line 127 of file group_algorithm.hpp.
is_scharn
template<typename T > using cl::sycl::detail::is_scharn = typedef is_contained<T, gtl::vector_signed_char_list>
Definition at line 82 of file generic_type_traits.hpp.
is_sgenfloat
template<typename T > using cl::sycl::detail::is_sgenfloat = typedef is_contained<T, gtl::scalar_floating_list>
Definition at line 40 of file generic_type_traits.hpp.
is_sgengeo
template<typename T > using cl::sycl::detail::is_sgengeo = typedef is_contained<T, gtl::scalar_geo_list>
Definition at line 62 of file generic_type_traits.hpp.
is_sgeninteger
template<typename T > using cl::sycl::detail::is_sgeninteger = typedef is_contained<T, gtl::scalar_integer_list>
Definition at line 156 of file generic_type_traits.hpp.
is_sgentype
template<typename T > using cl::sycl::detail::is_sgentype = typedef is_contained<T, gtl::scalar_basic_list>
Definition at line 179 of file generic_type_traits.hpp.
is_shortn
template<typename T > using cl::sycl::detail::is_shortn = typedef is_contained<T, gtl::vector_signed_short_list>
Definition at line 96 of file generic_type_traits.hpp.
is_sigeninteger
template<typename T > using cl::sycl::detail::is_sigeninteger = typedef is_contained<T, gtl::scalar_signed_integer_list>
Definition at line 162 of file generic_type_traits.hpp.
is_sint_to_float
template<typename T , typename R > using cl::sycl::detail::is_sint_to_float = typedef std::integral_constant<bool, std::is_integral<T>::value && !(std::is_unsigned<T>::value) && detail::is_floating_point<R>::value>
Definition at line 239 of file types.hpp.
is_sint_to_from_uint
template<typename T , typename R > using cl::sycl::detail::is_sint_to_from_uint = typedef std::integral_constant< bool, (is_sugeninteger<T>::value && is_sigeninteger<R>::value) || (is_sigeninteger<T>::value && is_sugeninteger<R>::value)>
Definition at line 233 of file types.hpp.
is_sint_to_sint
template<typename T , typename R > using cl::sycl::detail::is_sint_to_sint = typedef std::integral_constant<bool, is_sigeninteger<T>::value && is_sigeninteger<R>::value>
Definition at line 223 of file types.hpp.
is_standard_type
template<typename T > using cl::sycl::detail::is_standard_type = typedef std::integral_constant<bool, detail::is_sgentype<T>::value>
Definition at line 262 of file types.hpp.
is_sugeninteger
template<typename T > using cl::sycl::detail::is_sugeninteger = typedef is_contained<T, gtl::scalar_unsigned_integer_list>
Definition at line 165 of file generic_type_traits.hpp.
is_ucharn
template<typename T > using cl::sycl::detail::is_ucharn = typedef is_contained<T, gtl::vector_unsigned_char_list>
Definition at line 85 of file generic_type_traits.hpp.
is_ugenchar
template<typename T > using cl::sycl::detail::is_ugenchar = typedef is_contained<T, gtl::unsigned_char_list>
Definition at line 91 of file generic_type_traits.hpp.
is_ugenint
template<typename T > using cl::sycl::detail::is_ugenint = typedef is_contained<T, gtl::unsigned_int_list>
Definition at line 111 of file generic_type_traits.hpp.
is_ugeninteger
template<typename T > using cl::sycl::detail::is_ugeninteger = typedef is_contained<T, gtl::unsigned_integer_list>
Definition at line 153 of file generic_type_traits.hpp.
is_ugeninteger16bit
template<typename T > using cl::sycl::detail::is_ugeninteger16bit = typedef is_gen_based_on_type_sizeof<T, 2, is_ugeninteger>
Definition at line 197 of file generic_type_traits.hpp.
is_ugeninteger32bit
template<typename T > using cl::sycl::detail::is_ugeninteger32bit = typedef is_gen_based_on_type_sizeof<T, 4, is_ugeninteger>
Definition at line 200 of file generic_type_traits.hpp.
is_ugeninteger64bit
template<typename T > using cl::sycl::detail::is_ugeninteger64bit = typedef is_gen_based_on_type_sizeof<T, 8, is_ugeninteger>
Definition at line 203 of file generic_type_traits.hpp.
is_ugeninteger8bit
template<typename T > using cl::sycl::detail::is_ugeninteger8bit = typedef is_gen_based_on_type_sizeof<T, 1, is_ugeninteger>
Definition at line 194 of file generic_type_traits.hpp.
is_ugenlong
template<typename T > using cl::sycl::detail::is_ugenlong = typedef is_contained<T, gtl::unsigned_long_list>
Definition at line 122 of file generic_type_traits.hpp.
is_ugenlonginteger
template<typename T > using cl::sycl::detail::is_ugenlonginteger = typedef is_contained<T, gtl::unsigned_long_integer_list>
Definition at line 145 of file generic_type_traits.hpp.
is_ugenlonglong
template<typename T > using cl::sycl::detail::is_ugenlonglong = typedef is_contained<T, gtl::unsigned_longlong_list>
Definition at line 133 of file generic_type_traits.hpp.
is_ugenshort
template<typename T > using cl::sycl::detail::is_ugenshort = typedef is_contained<T, gtl::unsigned_short_list>
Definition at line 105 of file generic_type_traits.hpp.
is_uint_to_float
template<typename T , typename R > using cl::sycl::detail::is_uint_to_float = typedef std::integral_constant<bool, std::is_unsigned<T>::value && detail::is_floating_point<R>::value>
Definition at line 244 of file types.hpp.
is_uint_to_uint
template<typename T , typename R > using cl::sycl::detail::is_uint_to_uint = typedef std::integral_constant<bool, is_sugeninteger<T>::value && is_sugeninteger<R>::value>
Definition at line 228 of file types.hpp.
is_uintn
template<typename T > using cl::sycl::detail::is_uintn = typedef is_contained<T, gtl::vector_unsigned_int_list>
Definition at line 108 of file generic_type_traits.hpp.
is_ulonglongn
template<typename T > using cl::sycl::detail::is_ulonglongn = typedef is_contained<T, gtl::vector_unsigned_longlong_list>
Definition at line 130 of file generic_type_traits.hpp.
is_ulongn
template<typename T > using cl::sycl::detail::is_ulongn = typedef is_contained<T, gtl::vector_unsigned_long_list>
Definition at line 119 of file generic_type_traits.hpp.
is_ushortn
template<typename T > using cl::sycl::detail::is_ushortn = typedef is_contained<T, gtl::vector_unsigned_short_list>
Definition at line 102 of file generic_type_traits.hpp.
is_validImageDataT
template<typename T > using cl::sycl::detail::is_validImageDataT = typedef typename detail::is_contained< T, type_list<cl_int4, cl_uint4, cl_float4, cl_half4> >::type
Definition at line 63 of file image_impl.hpp.
is_vgenfloat
template<typename T > using cl::sycl::detail::is_vgenfloat = typedef is_contained<T, gtl::vector_floating_list>
Definition at line 43 of file generic_type_traits.hpp.
is_vgengeo
template<typename T > using cl::sycl::detail::is_vgengeo = typedef is_contained<T, gtl::vector_geo_list>
Definition at line 64 of file generic_type_traits.hpp.
is_vgengeodouble
template<typename T > using cl::sycl::detail::is_vgengeodouble = typedef is_contained<T, gtl::vector_geo_double_list>
Definition at line 57 of file generic_type_traits.hpp.
is_vgengeofloat
template<typename T > using cl::sycl::detail::is_vgengeofloat = typedef is_contained<T, gtl::vector_geo_float_list>
Definition at line 54 of file generic_type_traits.hpp.
is_vgengeohalf
template<typename T > using cl::sycl::detail::is_vgengeohalf = typedef is_contained<T, gtl::vector_geo_half_list>
Definition at line 60 of file generic_type_traits.hpp.
is_vgeninteger
template<typename T > using cl::sycl::detail::is_vgeninteger = typedef is_contained<T, gtl::vector_integer_list>
Definition at line 159 of file generic_type_traits.hpp.
is_vgentype
template<typename T > using cl::sycl::detail::is_vgentype = typedef is_contained<T, gtl::vector_basic_list>
Definition at line 176 of file generic_type_traits.hpp.
is_vigeninteger
template<typename T > using cl::sycl::detail::is_vigeninteger = typedef is_contained<T, gtl::vector_signed_integer_list>
Definition at line 168 of file generic_type_traits.hpp.
is_vugeninteger
template<typename T > using cl::sycl::detail::is_vugeninteger = typedef is_contained<T, gtl::vector_unsigned_integer_list>
Definition at line 171 of file generic_type_traits.hpp.
IsBitAND
template<typename T , class BinaryOperation > using cl::sycl::detail::IsBitAND = typedef bool_constant<std::is_same<BinaryOperation, sycl::bit_and<T> >::value || std::is_same<BinaryOperation, sycl::bit_and<void> >::value>
Definition at line 44 of file known_identity.hpp.
IsBitOR
template<typename T , class BinaryOperation > using cl::sycl::detail::IsBitOR = typedef bool_constant<std::is_same<BinaryOperation, sycl::bit_or<T> >::value || std::is_same<BinaryOperation, sycl::bit_or<void> >::value>
Definition at line 49 of file known_identity.hpp.
IsBitXOR
template<typename T , class BinaryOperation > using cl::sycl::detail::IsBitXOR = typedef bool_constant<std::is_same<BinaryOperation, sycl::bit_xor<T> >::value || std::is_same<BinaryOperation, sycl::bit_xor<void> >::value>
Definition at line 54 of file known_identity.hpp.
IsFalseIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::detail::IsFalseIdentityOp = typedef bool_constant<IsLogicalOR<T, BinaryOperation>::value>
Definition at line 100 of file known_identity.hpp.
IsKnownIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::detail::IsKnownIdentityOp = typedef bool_constant<IsZeroIdentityOp<T, BinaryOperation>::value || IsOneIdentityOp<T, BinaryOperation>::value || IsOnesIdentityOp<T, BinaryOperation>::value || IsMinimumIdentityOp<T, BinaryOperation>::value || IsMaximumIdentityOp<T, BinaryOperation>::value || IsFalseIdentityOp<T, BinaryOperation>::value || IsTrueIdentityOp<T, BinaryOperation>::value>
Definition at line 114 of file known_identity.hpp.
IsLogicalAND
template<typename T , class BinaryOperation > using cl::sycl::detail::IsLogicalAND = typedef bool_constant< std::is_same<BinaryOperation, sycl::logical_and<T> >::value || std::is_same<BinaryOperation, sycl::logical_and<void> >::value>
Definition at line 59 of file known_identity.hpp.
IsLogicalOR
template<typename T , class BinaryOperation > using cl::sycl::detail::IsLogicalOR = typedef bool_constant<std::is_same<BinaryOperation, sycl::logical_or<T> >::value || std::is_same<BinaryOperation, sycl::logical_or<void> >::value>
Definition at line 64 of file known_identity.hpp.
IsMaximum
template<typename T , class BinaryOperation > using cl::sycl::detail::IsMaximum = typedef bool_constant<std::is_same<BinaryOperation, sycl::maximum<T> >::value || std::is_same<BinaryOperation, sycl::maximum<void> >::value>
Definition at line 39 of file known_identity.hpp.
IsMaximumIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::detail::IsMaximumIdentityOp = typedef bool_constant<(is_geninteger<T>::value || is_genfloat<T>::value) && IsMaximum<T, BinaryOperation>::value>
Definition at line 96 of file known_identity.hpp.
IsMinimum
template<typename T , class BinaryOperation > using cl::sycl::detail::IsMinimum = typedef bool_constant<std::is_same<BinaryOperation, sycl::minimum<T> >::value || std::is_same<BinaryOperation, sycl::minimum<void> >::value>
Definition at line 34 of file known_identity.hpp.
IsMinimumIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::detail::IsMinimumIdentityOp = typedef bool_constant<(is_geninteger<T>::value || is_genfloat<T>::value) && IsMinimum<T, BinaryOperation>::value>
Definition at line 90 of file known_identity.hpp.
IsMultiplies
template<typename T , class BinaryOperation > using cl::sycl::detail::IsMultiplies = typedef bool_constant<std::is_same<BinaryOperation, sycl::multiplies<T> >::value || std::is_same<BinaryOperation, sycl::multiplies<void> >::value>
Definition at line 29 of file known_identity.hpp.
IsOneIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::detail::IsOneIdentityOp = typedef bool_constant<(is_geninteger<T>::value || is_genfloat<T>::value) && IsMultiplies<T, BinaryOperation>::value>
Definition at line 79 of file known_identity.hpp.
IsOnesIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::detail::IsOnesIdentityOp = typedef bool_constant<is_geninteger<T>::value && IsBitAND<T, BinaryOperation>::value>
Definition at line 84 of file known_identity.hpp.
IsPlus
template<typename T , class BinaryOperation > using cl::sycl::detail::IsPlus = typedef bool_constant<std::is_same<BinaryOperation, sycl::plus<T> >::value || std::is_same<BinaryOperation, sycl::plus<void> >::value>
Definition at line 24 of file known_identity.hpp.
IsPropertyListT
template<typename T > using cl::sycl::detail::IsPropertyListT = typedef typename std::is_base_of<PropertyListBase, T>
Definition at line 231 of file accessor.hpp.
IsRunTimePropertyListT
template<typename T > using cl::sycl::detail::IsRunTimePropertyListT = typedef typename std::is_same<ext::oneapi::accessor_property_list<>, T>
Definition at line 235 of file accessor.hpp.
IsTrueIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::detail::IsTrueIdentityOp = typedef bool_constant<IsLogicalAND<T, BinaryOperation>::value>
Definition at line 104 of file known_identity.hpp.
IsValidCoordType
template<typename T > using cl::sycl::detail::IsValidCoordType = typedef typename is_contained<T, type_list<cl_int, cl_float> >::type
Definition at line 31 of file image_accessor_util.hpp.
IsValidDefaultOrder
template<memory_order Order> using cl::sycl::detail::IsValidDefaultOrder = typedef bool_constant<Order == memory_order::relaxed || Order == memory_order::acq_rel || Order == memory_order::seq_cst>
Definition at line 55 of file atomic_ref.hpp.
IsZeroIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::detail::IsZeroIdentityOp = typedef bool_constant<(is_geninteger<T>::value && (IsPlus<T, BinaryOperation>::value || IsBitOR<T, BinaryOperation>::value || IsBitXOR<T, BinaryOperation>::value)) || (is_genfloat<T>::value && IsPlus<T, BinaryOperation>::value)>
Definition at line 73 of file known_identity.hpp.
iterator_category_t
template<typename T > using cl::sycl::detail::iterator_category_t = typedef typename std::iterator_traits<T>::iterator_category
Definition at line 52 of file stl_type_traits.hpp.
iterator_pointer_t
template<typename T > using cl::sycl::detail::iterator_pointer_t = typedef typename std::iterator_traits<T>::pointer
Definition at line 58 of file stl_type_traits.hpp.
iterator_to_const_type_t
template<typename T > using cl::sycl::detail::iterator_to_const_type_t = typedef std::is_const<typename std::remove_pointer<iterator_pointer_t<T> >::type>
Definition at line 62 of file stl_type_traits.hpp.
iterator_value_type_t
template<typename T > using cl::sycl::detail::iterator_value_type_t = typedef typename std::iterator_traits<T>::value_type
Definition at line 55 of file stl_type_traits.hpp.
KernelBundleImplPtr
typedef std::shared_ptr< kernel_bundle_impl > cl::sycl::detail::KernelBundleImplPtr
Definition at line 132 of file kernel_bundle.hpp.
KernelSetId
using cl::sycl::detail::KernelSetId = typedef size_t
Definition at line 340 of file common.hpp.
lambda_arg_type
template<typename F , typename SuggestedArgType > using cl::sycl::detail::lambda_arg_type = typedef decltype(argument_helper<F, SuggestedArgType>(0))
Definition at line 111 of file handler.hpp.
LocalAccessorImplPtr
using cl::sycl::detail::LocalAccessorImplPtr = typedef std::shared_ptr<LocalAccessorImplHost>
Definition at line 182 of file accessor_impl.hpp.
LockGuard
using cl::sycl::detail::LockGuard = typedef std::lock_guard<SpinLock>
Definition at line 30 of file global_handler.cpp.
make_floating_point_t
template<typename T > using cl::sycl::detail::make_floating_point_t = typedef make_type_t<T, gtl::scalar_floating_list>
Definition at line 266 of file generic_type_traits.hpp.
make_larger_t
template<typename T > using cl::sycl::detail::make_larger_t = typedef typename make_larger<T>::type
Definition at line 339 of file type_traits.hpp.
make_signed_impl_t
template<typename T > using cl::sycl::detail::make_signed_impl_t = typedef typename make_signed_impl<T, T>::type
Definition at line 139 of file type_traits.hpp.
make_signed_t
template<typename T > using cl::sycl::detail::make_signed_t = typedef typename make_signed<T>::type
Definition at line 167 of file type_traits.hpp.
make_singed_integer_t
template<typename T > using cl::sycl::detail::make_singed_integer_t = typedef make_type_t<T, gtl::scalar_signed_integer_list>
Definition at line 269 of file generic_type_traits.hpp.
make_type_t
template<typename T , typename TL > using cl::sycl::detail::make_type_t = typedef typename make_type_impl<T, TL>::type
Definition at line 303 of file type_traits.hpp.
make_unsigned_impl_t
template<typename T > using cl::sycl::detail::make_unsigned_impl_t = typedef typename make_unsigned_impl<T, T>::type
Definition at line 173 of file type_traits.hpp.
make_unsigned_t
template<typename T > using cl::sycl::detail::make_unsigned_t = typedef typename make_unsigned<T>::type
Definition at line 201 of file type_traits.hpp.
make_unsinged_integer_t
template<typename T > using cl::sycl::detail::make_unsinged_integer_t = typedef make_type_t<T, gtl::scalar_unsigned_integer_list>
Definition at line 273 of file generic_type_traits.hpp.
memory_order
typedef cl::sycl::memory_order cl::sycl::detail::memory_order
Definition at line 36 of file atomic.hpp.
memory_scope
using cl::sycl::detail::memory_scope = typedef cl::sycl::memory_scope
Definition at line 30 of file atomic_ref.hpp.
nan_argument_base_t
template<typename T > using cl::sycl::detail::nan_argument_base_t = typedef typename nan_types<T, T>::arg_type
Definition at line 263 of file generic_type_traits.hpp.
nan_return_t
template<typename T > using cl::sycl::detail::nan_return_t = typedef typename nan_types<T, T>::ret_type
Definition at line 260 of file generic_type_traits.hpp.
native_op_list
template<typename T > using cl::sycl::detail::native_op_list = typedef type_list<sycl::plus<T>, sycl::bit_or<T>, sycl::bit_xor<T>, sycl::bit_and<T>, sycl::maximum<T>, sycl::minimum<T>, sycl::multiplies<T> >
Definition at line 94 of file group_algorithm.hpp.
OSModuleHandle
using cl::sycl::detail::OSModuleHandle = typedef intptr_t
Uniquely identifies an operating system module (executable or a dynamic library)
Definition at line 48 of file os_util.hpp.
output_iterator_requirements
template<typename T > using cl::sycl::detail::output_iterator_requirements = typedef void_t<iterator_category_t<T>, decltype(*std::declval<T>() = std::declval<iterator_value_type_t<T> >())>
Definition at line 70 of file stl_type_traits.hpp.
PlatformImplPtr
typedef std::shared_ptr< platform_impl > cl::sycl::detail::PlatformImplPtr
Definition at line 30 of file context_impl.hpp.
ProgramImplPtr
using cl::sycl::detail::ProgramImplPtr = typedef std::shared_ptr<program_impl>
Definition at line 32 of file kernel_impl.hpp.
QueueImplPtr
typedef std::shared_ptr< detail::queue_impl > cl::sycl::detail::QueueImplPtr
Definition at line 30 of file memory_manager.hpp.
rel_ret_t
template<typename T > using cl::sycl::detail::rel_ret_t = typedef typename RelationalReturnType<T>::type
Definition at line 534 of file generic_type_traits.hpp.
rel_sign_bit_test_arg_t
template<typename T > using cl::sycl::detail::rel_sign_bit_test_arg_t = typedef typename RelationalTestForSignBitType<T>::argument_type
Definition at line 553 of file generic_type_traits.hpp.
rel_sign_bit_test_ret_t
template<typename T > using cl::sycl::detail::rel_sign_bit_test_ret_t = typedef typename RelationalTestForSignBitType<T>::return_type
Definition at line 549 of file generic_type_traits.hpp.
rel_t
template<typename DataT > using cl::sycl::detail::rel_t = typedef typename detail::conditional_t< sizeof(DataT) == sizeof(cl_char), cl_char, typename detail::conditional_t< sizeof(DataT) == sizeof(cl_short), cl_short, typename detail::conditional_t< sizeof(DataT) == sizeof(cl_int), cl_int, typename detail::conditional_t<sizeof(DataT) == sizeof(cl_long), cl_long, bool> >> >
Definition at line 131 of file types.hpp.
remove_const_t
template<typename T > using cl::sycl::detail::remove_const_t = typedef typename std::remove_const<T>::type
Definition at line 30 of file stl_type_traits.hpp.
remove_cv_t
template<typename T > using cl::sycl::detail::remove_cv_t = typedef typename std::remove_cv<T>::type
Definition at line 32 of file stl_type_traits.hpp.
remove_pointer_t
template<typename T > using cl::sycl::detail::remove_pointer_t = typedef typename remove_pointer<T>::type
Definition at line 275 of file type_traits.hpp.
remove_reference_t
template<typename T > using cl::sycl::detail::remove_reference_t = typedef typename std::remove_reference<T>::type
Definition at line 35 of file stl_type_traits.hpp.
Requirement
using cl::sycl::detail::Requirement = typedef AccessorImplHost
Definition at line 218 of file accessor_impl.hpp.
select_apply_cl_scalar_t
template<typename T , typename T8 , typename T16 , typename T32 , typename T64 > using cl::sycl::detail::select_apply_cl_scalar_t = typedef conditional_t<sizeof(T) == 1, T8, conditional_t<sizeof(T) == 2, T16, conditional_t<sizeof(T) == 4, T32, T64> >>
Definition at line 365 of file generic_type_traits.hpp.
select_apply_cl_t
template<typename T , typename T8 , typename T16 , typename T32 , typename T64 > using cl::sycl::detail::select_apply_cl_t = typedef conditional_t<sizeof(T) == 1, T8, conditional_t<sizeof(T) == 2, T16, conditional_t<sizeof(T) == 4, T32, T64> >>
Definition at line 2157 of file types.hpp.
select_cl_scalar_float_t
template<typename T > using cl::sycl::detail::select_cl_scalar_float_t = typedef select_apply_cl_scalar_t<T, std::false_type, sycl::cl_half, sycl::cl_float, sycl::cl_double>
Definition at line 381 of file generic_type_traits.hpp.
select_cl_scalar_integral_signed_t
template<typename T > using cl::sycl::detail::select_cl_scalar_integral_signed_t = typedef select_apply_cl_scalar_t<T, sycl::cl_char, sycl::cl_short, sycl::cl_int, sycl::cl_long>
Definition at line 371 of file generic_type_traits.hpp.
select_cl_scalar_integral_t
template<typename T > using cl::sycl::detail::select_cl_scalar_integral_t = typedef conditional_t<std::is_signed<T>::value, select_cl_scalar_integral_signed_t<T>, select_cl_scalar_integral_unsigned_t<T> >
Definition at line 387 of file generic_type_traits.hpp.
select_cl_scalar_integral_unsigned_t
template<typename T > using cl::sycl::detail::select_cl_scalar_integral_unsigned_t = typedef select_apply_cl_scalar_t<T, sycl::cl_uchar, sycl::cl_ushort, sycl::cl_uint, sycl::cl_ulong>
Definition at line 376 of file generic_type_traits.hpp.
select_cl_scalar_t
template<typename T > using cl::sycl::detail::select_cl_scalar_t = typedef conditional_t< std::is_integral<T>::value, select_cl_scalar_integral_t<T>, conditional_t< std::is_floating_point<T>::value, select_cl_scalar_float_t<T>, conditional_t<std::is_same<T, half>::value, cl::sycl::detail::half_impl::BIsRepresentationT, T> >>
Definition at line 399 of file generic_type_traits.hpp.
SelectMatchingOpenCLType_t
template<typename T > using cl::sycl::detail::SelectMatchingOpenCLType_t = typedef typename select_cl_mptr_or_vector_or_scalar<T>::type
Definition at line 461 of file generic_type_traits.hpp.
SerializedObj
using cl::sycl::detail::SerializedObj = typedef std::vector<unsigned char>
Definition at line 56 of file util.hpp.
SpecConstRegistryT
using cl::sycl::detail::SpecConstRegistryT = typedef std::map<std::string, spec_constant_impl>
Definition at line 44 of file spec_constant_impl.hpp.
StreamImplPtr
typedef std::shared_ptr< detail::stream_impl > cl::sycl::detail::StreamImplPtr
Definition at line 38 of file commands.hpp.
sycl_memory_object_allocator
using cl::sycl::detail::sycl_memory_object_allocator = typedef aligned_allocator<char>
Definition at line 40 of file sycl_mem_obj_t.hpp.
tail_t
template<typename T > using cl::sycl::detail::tail_t = typedef typename T::tail
Definition at line 20 of file type_list.hpp.
tuple_element_t
template<std::size_t I, class T > using cl::sycl::detail::tuple_element_t = typedef typename tuple_element<I, T>::type
Definition at line 56 of file tuple.hpp.
type_helper
template<typename T > using cl::sycl::detail::type_helper = typedef typename TypeHelper<T>::RetType
Definition at line 440 of file generic_type_traits.hpp.
uuid_type
using cl::sycl::detail::uuid_type = typedef std::array<unsigned char, 16>
Definition at line 62 of file type_traits.hpp.
vector_element_impl_t
template<typename T > using cl::sycl::detail::vector_element_impl_t = typedef typename vector_element_impl<T>::type
Definition at line 92 of file type_traits.hpp.
vector_element_t
template<class T > using cl::sycl::detail::vector_element_t = typedef typename vector_element<T>::type
Definition at line 100 of file type_traits.hpp.
void_t
template<class... > using cl::sycl::detail::void_t = typedef void
Definition at line 42 of file stl_type_traits.hpp.
Enumeration Type Documentation
backend_errc
enum cl::sycl::detail::backend_errc : unsigned int strong
Definition at line 45 of file backend.hpp.
BlockingT
enum cl::sycl::detail::BlockingT
Enumerator
NON_BLOCKING
BLOCKING
Definition at line 47 of file commands.hpp.
BuildState
enum cl::sycl::detail::BuildState
Enumerator
BS_InProgress
BS_Done
BS_Failed
Definition at line 48 of file program_manager.cpp.
ConfigID
enum cl::sycl::detail::ConfigID
Enumerator
START
END
Definition at line 51 of file config.hpp.
CUDAContextT
enum cl::sycl::detail::CUDAContextT : char strong
Possible CUDA context types supported by PI CUDA backend TODO: Implement this as a property once there is an extension document.
Enumerator
primary
custom
Definition at line 47 of file queue_impl.hpp.
DataLessPropKind
enum cl::sycl::detail::DataLessPropKind
Enumerator
BufferUseHostPtr
ImageUseHostPtr
QueueEnableProfiling
InOrder
NoInit
BufferUsePinnedHostMemory
UsePrimaryContext
InitializeToIdentity
UseDefaultStream
DiscardEvents
DeviceReadOnly
LastKnownDataLessPropKind
DataLessPropKindSize
Definition at line 26 of file property_helper.hpp.
DeviceLibExt
enum cl::sycl::detail::DeviceLibExt : std::uint32_t strong
Enumerator
cl_intel_devicelib_assert
cl_intel_devicelib_math
cl_intel_devicelib_math_fp64
cl_intel_devicelib_complex
cl_intel_devicelib_complex_fp64
cl_intel_devicelib_cstring
Definition at line 60 of file program_manager.hpp.
ExtendedMembersType
enum cl::sycl::detail::ExtendedMembersType : unsigned int strong
Enumerator
HANDLER_KERNEL_BUNDLE
HANDLER_MEM_ADVICE
HANDLER_IMPL
Definition at line 94 of file cg.hpp.
HandlerSubmissionState
enum cl::sycl::detail::HandlerSubmissionState : std::uint8_t strong
Enumerator
NO_STATE
EXPLICIT_KERNEL_BUNDLE_STATE
SPEC_CONST_SET_STATE
Definition at line 19 of file handler_impl.hpp.
kernel_param_kind_t
enum cl::sycl::detail::kernel_param_kind_t strong
Enumerator
kind_accessor
kind_std_layout
kind_sampler
kind_pointer
kind_specialization_constants_buffer
kind_stream
kind_invalid
Definition at line 25 of file kernel_desc.hpp.
PiApiKind
enum cl::sycl::detail::PiApiKind strong
Enumerator
_PI_API
Definition at line 42 of file pi.hpp.
PropWithDataKind
enum cl::sycl::detail::PropWithDataKind
Enumerator
BufferUseMutex
BufferContextBound
ImageUseMutex
ImageContextBound
BufferMemChannel
AccPropBufferLocation
PropWithDataKindSize
Definition at line 45 of file property_helper.hpp.
QueueOrder
enum cl::sycl::detail::QueueOrder
Enumerator
Ordered
OOO
Definition at line 52 of file queue_impl.hpp.
Function Documentation
__attribute__()
cl::sycl::detail::__attribute__ ((destructor(110)))
Definition at line 182 of file global_handler.cpp.
References shutdown().
Referenced by cl::sycl::ext::oneapi::group_local_memory(), and cl::sycl::ext::oneapi::group_local_memory_for_overwrite().
__SYCL2020_DEPRECATED()
template<typename T > struct cl::sycl::detail::__SYCL2020_DEPRECATED ("This type isn't device copyable in SYCL 2020")
accessModeToString()
static std::string cl::sycl::detail::accessModeToString (access::mode Mode) static
Definition at line 98 of file commands.cpp.
References write().
Referenced by cl::sycl::detail::Command::emitEdgeEventForCommandDependence(), cl::sycl::detail::EmptyCommand::printDot(), cl::sycl::detail::ReleaseCommand::printDot(), cl::sycl::detail::AllocaCommand::printDot(), cl::sycl::detail::AllocaSubBufCommand::printDot(), cl::sycl::detail::MapMemObject::printDot(), cl::sycl::detail::UnMapMemObject::printDot(), cl::sycl::detail::MemCpyCommand::printDot(), cl::sycl::detail::MemCpyCommandHost::printDot(), cl::sycl::detail::ExecCGCommand::printDot(), and cl::sycl::detail::UpdateHostRequirementCommand::printDot().
addHostAccessorAndWait()
void cl::sycl::detail::addHostAccessorAndWait (Requirement * Req)
Definition at line 36 of file accessor_impl.cpp.
adjustNDRangePerKernel()
static void cl::sycl::detail::adjustNDRangePerKernel (NDRDescT & NDR, RT::PiKernel Kernel, const device_impl & DeviceImpl) static
Definition at line 1835 of file commands.cpp.
References cl::sycl::info::compile_work_group_size, cl::sycl::detail::NDRDescT::Dims, std::get(), cl::sycl::detail::device_impl::getHandleRef(), cl::sycl::detail::device_impl::getPlugin(), cl::sycl::detail::NDRDescT::GlobalSize, cl::sycl::detail::NDRDescT::LocalSize, cl::sycl::detail::NDRDescT::NumWorkGroups, and cl::sycl::detail::NDRDescT::set().
Referenced by SetKernelParamsAndLaunch().
append()
unsigned cl::sycl::detail::append (char * Dst, const char * Src) inline
Definition at line 220 of file stream.hpp.
Referenced by ArrayToStr(), checkForInfNan(), ItemToStr(), VecToStr(), writeGroup(), writeHItem(), writeItem(), writeNDItem(), and writeNDRange().
appendCompileOptionsFromImage()
static void cl::sycl::detail::appendCompileOptionsFromImage (std::string & CompileOpts, const RTDeviceBinaryImage & Img) static
Definition at line 383 of file program_manager.cpp.
References cl::sycl::detail::pi::asUint32(), std::get(), cl::sycl::detail::pi::DeviceBinaryImage::getCompileOptions(), and cl::sycl::detail::pi::DeviceBinaryImage::getProperty().
Referenced by applyOptionsFromImage(), and cl::sycl::detail::ProgramManager::compile().
appendLinkOptionsFromImage()
static void cl::sycl::detail::appendLinkOptionsFromImage (std::string & LinkOpts, const RTDeviceBinaryImage & Img) static
Definition at line 369 of file program_manager.cpp.
References std::get(), and cl::sycl::detail::pi::DeviceBinaryImage::getLinkOptions().
Referenced by applyOptionsFromImage(), and cl::sycl::detail::ProgramManager::link().
applyAllowList()
void cl::sycl::detail::applyAllowList (std::vector< RT::PiDevice > & PiDevices, RT::PiPlatform PiPlatform, const plugin & Plugin)
Definition at line 336 of file allowlist.cpp.
References BackendNameKeyName, cl::sycl::detail::plugin::call(), deviceIsAllowed(), DeviceNameKeyName, DeviceTypeKeyName, DeviceVendorIdKeyName, DriverVersionKeyName, std::get(), cl::sycl::detail::plugin::getBackend(), getSyclBeMap(), getSyclDeviceTypeMap(), parseAllowList(), PI_DEVICE_INFO_TYPE, piDeviceGetInfo(), PlatformNameKeyName, and PlatformVersionKeyName.
Referenced by cl::sycl::detail::platform_impl::get_devices().
applyCompileOptionsFromEnvironment()
static void cl::sycl::detail::applyCompileOptionsFromEnvironment (std::string & CompileOpts) static
Definition at line 420 of file program_manager.cpp.
References std::get().
Referenced by applyOptionsFromEnvironment(), and cl::sycl::detail::ProgramManager::compile().
applyLinkOptionsFromEnvironment()
static void cl::sycl::detail::applyLinkOptionsFromEnvironment (std::string & LinkOpts) static
Definition at line 430 of file program_manager.cpp.
References std::get().
Referenced by applyOptionsFromEnvironment(), and cl::sycl::detail::ProgramManager::link().
applyOptionsFromEnvironment()
static void cl::sycl::detail::applyOptionsFromEnvironment (std::string & CompileOpts, std::string & LinkOpts) static
Definition at line 439 of file program_manager.cpp.
References applyCompileOptionsFromEnvironment(), and applyLinkOptionsFromEnvironment().
Referenced by cl::sycl::detail::ProgramManager::build(), cl::sycl::detail::ProgramManager::getBuiltPIProgram(), and cl::sycl::detail::ProgramManager::getOrCreateKernel().
applyOptionsFromImage()
static void cl::sycl::detail::applyOptionsFromImage (std::string & CompileOpts, std::string & LinkOpts, const RTDeviceBinaryImage & Img) static
Definition at line 413 of file program_manager.cpp.
References appendCompileOptionsFromImage(), and appendLinkOptionsFromImage().
Referenced by cl::sycl::detail::ProgramManager::build(), and cl::sycl::detail::ProgramManager::getBuiltPIProgram().
argument_helper()
template<typename F , typename SuggestedArgType > SuggestedArgType cl::sycl::detail::argument_helper (...)
ArrayToStr()
template<int ArrayLength> unsigned cl::sycl::detail::ArrayToStr (char * Buf, const array< ArrayLength > & Arr) inline
Definition at line 508 of file stream.hpp.
References append(), ScalarToStr(), VEC_CLOSE_BRACE, VEC_ELEMENT_DELIMITER, and VEC_OPEN_BRACE.
Referenced by ItemToStr(), writeArray(), writeGroup(), writeItem(), writeNDItem(), and writeNDRange().
associateWithHandler()
void cl::sycl::detail::associateWithHandler (handler & CGH, AccessorBaseHost * Acc, access::target Target)
Definition at line 17 of file handler_proxy.cpp.
Referenced by cl::sycl::accessor< DataT, Dimensions, AccessMode, access::target::image, IsPlaceholder >::accessor(), cl::sycl::accessor< DataT, Dimensions, AccessMode, access::target::image_array, IsPlaceholder >::accessor(), cl::sycl::ext::oneapi::detail::reduction_impl< T, BinaryOperation, Dims, IsUSM, IsPlaceholder >::getWriteAccForPartialReds(), cl::sycl::ext::oneapi::detail::reduction_impl< T, BinaryOperation, Dims, IsUSM, IsPlaceholder >::reduction_impl(), and cl::sycl::handler::require().
bit_cast()
template<typename To , typename From > To cl::sycl::detail::bit_cast (const From & from) noexcept
Definition at line 60 of file bit_cast.hpp.
build_impl()
std::shared_ptr< detail::kernel_bundle_impl > cl::sycl::detail::build_impl (const kernel_bundle< bundle_state::input > & InputBundle, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 252 of file kernel_bundle.cpp.
cast_if_host_half() [1/2]
float cl::sycl::detail::cast_if_host_half (half_impl::half val) inline
Definition at line 419 of file half_type.hpp.
cast_if_host_half() [2/2]
template<typename T > T cl::sycl::detail::cast_if_host_half (T val) inline
Definition at line 417 of file half_type.hpp.
cgTypeToString()
static std::string cl::sycl::detail::cgTypeToString (detail::CG::CGTYPE Type) static
Definition at line 1641 of file commands.cpp.
References cl::sycl::detail::CG::CodeplayHostTask, cl::sycl::detail::CG::CopyAccToAcc, cl::sycl::detail::CG::CopyAccToPtr, cl::sycl::detail::CG::CopyPtrToAcc, cl::sycl::detail::CG::CopyUSM, cl::sycl::detail::CG::Fill, cl::sycl::detail::CG::FillUSM, cl::sycl::detail::CG::Kernel, cl::sycl::detail::CG::PrefetchUSM, and cl::sycl::detail::CG::UpdateHost.
Referenced by cl::sycl::detail::ExecCGCommand::emitInstrumentationData(), and cl::sycl::detail::ExecCGCommand::printDot().
check_kernel_lambda_takes_args()
template<typename F , typename... Args> static constexpr bool cl::sycl::detail::check_kernel_lambda_takes_args () static constexpr
Definition at line 148 of file cg_types.hpp.
check_vector_size()
template<typename... Args> void cl::sycl::detail::check_vector_size () inline
Definition at line 633 of file generic_type_traits.hpp.
checkAllDevicesAreInContext()
static bool cl::sycl::detail::checkAllDevicesAreInContext (const std::vector< device > & Devices, const context & Context) static
Definition at line 31 of file kernel_bundle_impl.hpp.
References all_of(), and cl::sycl::context::get_devices().
Referenced by has_kernel_bundle_impl(), and cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl().
checkAllDevicesHaveAspect()
static bool cl::sycl::detail::checkAllDevicesHaveAspect (const std::vector< device > & Devices, aspect Aspect) static
Definition at line 41 of file kernel_bundle_impl.hpp.
References all_of().
Referenced by has_kernel_bundle_impl().
checkAny()
template<typename T , typename... Args> static bool cl::sycl::detail::checkAny (const T Value, Args... Arguments) static
Definition at line 40 of file image_impl.cpp.
References checkAnyImpl().
checkAnyImpl() [1/2]
template<typename T , typename... Args> static bool cl::sycl::detail::checkAnyImpl (T) static
Definition at line 30 of file image_impl.cpp.
checkAnyImpl() [2/2]
template<typename ValT , typename VarT , typename... Args> static bool cl::sycl::detail::checkAnyImpl (ValT Value, VarT Variant, Args... Arguments) static
Definition at line 35 of file image_impl.cpp.
Referenced by checkAny().
checkForInfNan() [1/2]
template<typename T > detail::enable_if_t< std::is_same<T, float>::value || std::is_same<T, double>::value, unsigned> cl::sycl::detail::checkForInfNan (char * Buf, T Val) inline
Definition at line 233 of file stream.hpp.
References append(), cl::sycl::isinf(), cl::sycl::isnan(), and cl::sycl::signbit().
checkForInfNan() [2/2]
template<typename T > detail::enable_if_t<std::is_same<T, half>::value, unsigned> cl::sycl::detail::checkForInfNan (char * Buf, T Val) inline
Definition at line 246 of file stream.hpp.
References append().
Referenced by ScalarToStr().
checkHostUnifiedMemory()
static bool cl::sycl::detail::checkHostUnifiedMemory (const ContextImplPtr & Ctx) static
Definition at line 648 of file graph_builder.cpp.
checkImageValueRange()
template<info::device Param> static bool cl::sycl::detail::checkImageValueRange (const std::vector< device > & Devices, const size_t Value) static
Definition at line 22 of file image_impl.cpp.
References all_of().
checkValueRange() [1/3]
template<int Dims> void cl::sycl::detail::checkValueRange (const range< Dims > & R, const id< Dims > & O)
Definition at line 172 of file handler.hpp.
checkValueRange() [2/3]
template<int Dims, typename T > detail::enable_if_t<std::is_same<T, range<Dims> >::value || std::is_same<T, id<Dims> >::value> cl::sycl::detail::checkValueRange (const T & V)
Definition at line 153 of file handler.hpp.
checkValueRange() [3/3]
template<int Dims, typename T > detail::enable_if_t<std::is_same<T, nd_range<Dims> >::value> cl::sycl::detail::checkValueRange (const T & V)
Definition at line 190 of file handler.hpp.
codeToString()
static std::string cl::sycl::detail::codeToString (cl_int code) inline static
Definition at line 96 of file common.hpp.
References stringifyErrorCode().
Referenced by cl::sycl::detail::enqueue_kernel_launch::handleError(), cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), and cl::sycl::detail::plugin::reportPiError().
combineAccessModes()
static access::mode cl::sycl::detail::combineAccessModes (access::mode A, access::mode B) static
Combines two access modes into a single one that allows both.
Definition at line 74 of file graph_builder.cpp.
References write().
Referenced by combineAccessModesOfReqs().
combineAccessModesOfReqs()
static void cl::sycl::detail::combineAccessModesOfReqs (std::vector< Requirement * > & Reqs) static
Definition at line 895 of file graph_builder.cpp.
References combineAccessModes().
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::addCG().
compatibleWithDevice()
static bool cl::sycl::detail::compatibleWithDevice (RTDeviceBinaryImage * BinImage, const device & Dev) static
Definition at line 1427 of file program_manager.cpp.
References cl::sycl::detail::RTDeviceBinaryImage::getRawData(), getSyclObjImpl(), max(), PI_INVALID_BINARY, PI_INVALID_VALUE, PI_SUCCESS, and piextDeviceSelectBinary().
Referenced by cl::sycl::detail::ProgramManager::getSYCLDeviceImagesWithCompatibleState().
compile_impl()
std::shared_ptr< detail::kernel_bundle_impl > cl::sycl::detail::compile_impl (const kernel_bundle< bundle_state::input > & InputBundle, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 238 of file kernel_bundle.cpp.
constructorNotification()
void cl::sycl::detail::constructorNotification (void * BufferObj, void * AccessorObj, access::target Target, access::mode Mode, const code_location & CodeLoc)
Definition at line 42 of file accessor_impl.cpp.
Referenced by cl::sycl::accessor< DataT, 1, access_mode::read_write, target::host_buffer, access::placeholder::false_t >::accessor(), and cl::sycl::detail::buffer_impl::constructorNotification().
context_impl::get_info< info::context::atomic_memory_order_capabilities >()
template<> std::vector<cl::sycl::memory_order> cl::sycl::detail::context_impl::get_info< info::context::atomic_memory_order_capabilities > () const
Definition at line 153 of file context_impl.cpp.
References cl::sycl::acq_rel, cl::sycl::acquire, cl::sycl::info::atomic_memory_order_capabilities, cl::sycl::detail::plugin::call(), getPlugin(), piContextGetInfo(), readMemoryOrderBitfield(), cl::sycl::relaxed, cl::sycl::release, and cl::sycl::seq_cst.
context_impl::get_info< info::context::atomic_memory_scope_capabilities >()
template<> std::vector<cl::sycl::memory_scope> cl::sycl::detail::context_impl::get_info< info::context::atomic_memory_scope_capabilities > () const
Definition at line 170 of file context_impl.cpp.
References cl::sycl::info::atomic_memory_scope_capabilities, cl::sycl::detail::plugin::call(), cl::sycl::device, getPlugin(), piContextGetInfo(), readMemoryScopeBitfield(), cl::sycl::sub_group, cl::sycl::system, cl::sycl::work_group, and cl::sycl::work_item.
context_impl::get_info< info::context::devices >()
template<> std::vector<cl::sycl::device> cl::sycl::detail::context_impl::get_info< info::context::devices > () const
Definition at line 148 of file context_impl.cpp.
context_impl::get_info< info::context::platform >()
template<> platform cl::sycl::detail::context_impl::get_info< info::context::platform > () const
Definition at line 141 of file context_impl.cpp.
context_impl::get_info< info::context::reference_count >()
template<> cl_uint cl::sycl::detail::context_impl::get_info< info::context::reference_count > () const
Definition at line 135 of file context_impl.cpp.
References cl::sycl::detail::get_context_info< param >::get(), and getPlugin().
convertChannelOrder() [1/2]
RT::PiMemImageChannelOrder cl::sycl::detail::convertChannelOrder (image_channel_order Order)
Definition at line 107 of file image_impl.cpp.
References PI_IMAGE_CHANNEL_ORDER_A, PI_IMAGE_CHANNEL_ORDER_ABGR, PI_IMAGE_CHANNEL_ORDER_ARGB, PI_IMAGE_CHANNEL_ORDER_BGRA, PI_IMAGE_CHANNEL_ORDER_INTENSITY, PI_IMAGE_CHANNEL_ORDER_LUMINANCE, PI_IMAGE_CHANNEL_ORDER_R, PI_IMAGE_CHANNEL_ORDER_RA, PI_IMAGE_CHANNEL_ORDER_RG, PI_IMAGE_CHANNEL_ORDER_RGB, PI_IMAGE_CHANNEL_ORDER_RGBA, PI_IMAGE_CHANNEL_ORDER_RGBx, PI_IMAGE_CHANNEL_ORDER_RGx, PI_IMAGE_CHANNEL_ORDER_Rx, and PI_IMAGE_CHANNEL_ORDER_sRGBA.
Referenced by cl::sycl::detail::image_impl< Dimensions >::image_impl().
convertChannelOrder() [2/2]
image_channel_order cl::sycl::detail::convertChannelOrder (RT::PiMemImageChannelOrder Order)
Definition at line 144 of file image_impl.cpp.
References PI_IMAGE_CHANNEL_ORDER_A, PI_IMAGE_CHANNEL_ORDER_ABGR, PI_IMAGE_CHANNEL_ORDER_ARGB, PI_IMAGE_CHANNEL_ORDER_BGRA, PI_IMAGE_CHANNEL_ORDER_INTENSITY, PI_IMAGE_CHANNEL_ORDER_LUMINANCE, PI_IMAGE_CHANNEL_ORDER_R, PI_IMAGE_CHANNEL_ORDER_RA, PI_IMAGE_CHANNEL_ORDER_RG, PI_IMAGE_CHANNEL_ORDER_RGB, PI_IMAGE_CHANNEL_ORDER_RGBA, PI_IMAGE_CHANNEL_ORDER_RGBx, PI_IMAGE_CHANNEL_ORDER_RGx, PI_IMAGE_CHANNEL_ORDER_Rx, and PI_IMAGE_CHANNEL_ORDER_sRGBA.
convertChannelType() [1/2]
RT::PiMemImageChannelType cl::sycl::detail::convertChannelType (image_channel_type Type)
Definition at line 181 of file image_impl.cpp.
References PI_IMAGE_CHANNEL_TYPE_FLOAT, PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8, PI_IMAGE_CHANNEL_TYPE_SNORM_INT16, PI_IMAGE_CHANNEL_TYPE_SNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT16, PI_IMAGE_CHANNEL_TYPE_UNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT32, and PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8.
Referenced by cl::sycl::detail::image_impl< Dimensions >::image_impl().
convertChannelType() [2/2]
image_channel_type cl::sycl::detail::convertChannelType (RT::PiMemImageChannelType Type)
Definition at line 218 of file image_impl.cpp.
References PI_IMAGE_CHANNEL_TYPE_FLOAT, PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT32, PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8, PI_IMAGE_CHANNEL_TYPE_SNORM_INT16, PI_IMAGE_CHANNEL_TYPE_SNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT16, PI_IMAGE_CHANNEL_TYPE_UNORM_INT8, PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555, PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT16, PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT32, and PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8.
convertDataToType() [1/2]
template<typename FROM , typename TO > detail::enable_if_t<is_vgentype<FROM>::value && is_vgentype<TO>::value && sizeof(TO) == sizeof(FROM), TO> cl::sycl::detail::convertDataToType (FROM t)
Definition at line 481 of file generic_type_traits.hpp.
convertDataToType() [2/2]
template<typename FROM , typename TO > detail::enable_if_t<!(is_vgentype<FROM>::value && is_vgentype<TO>::value) && sizeof(TO) == sizeof(FROM), TO> cl::sycl::detail::convertDataToType (FROM t)
Definition at line 490 of file generic_type_traits.hpp.
References TryToGetPointer().
convertImpl() [1/3]
template<typename T , typename R , rounding_mode roundingMode, typename OpenCLT , typename OpenCLR > detail::enable_if_t<std::is_same<T, R>::value, R> cl::sycl::detail::convertImpl (T Value)
Definition at line 266 of file types.hpp.
convertImpl() [2/3]
template<typename T , typename R , rounding_mode roundingMode, typename OpenCLT , typename OpenCLR > detail::enable_if_t<!std::is_same<T, R>::value && (is_int_to_int<T, R>::value || is_int_to_float<T, R>::value || is_float_to_float<T, R>::value), R> cl::sycl::detail::convertImpl (T Value)
Definition at line 281 of file types.hpp.
convertImpl() [3/3]
template<typename T , typename R , rounding_mode roundingMode, typename OpenCLT , typename OpenCLR > detail::enable_if_t<is_float_to_int<T, R>::value, R> cl::sycl::detail::convertImpl (T Value)
Definition at line 288 of file types.hpp.
References cl::sycl::ceil(), cl::sycl::floor(), PI_ERROR_UNKNOWN, cl::sycl::rint(), and cl::sycl::trunc().
convertReadData() [1/4]
template<typename ChannelType > void cl::sycl::detail::convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, vec< cl_float, 4 > & RetData)
Definition at line 328 of file image_accessor_util.hpp.
References cl::sycl::fmax(), and PI_INVALID_VALUE.
convertReadData() [2/4]
template<typename ChannelType > void cl::sycl::detail::convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, vec< cl_half, 4 > & RetData)
Definition at line 418 of file image_accessor_util.hpp.
References cl::sycl::fmax(), PI_INVALID_OPERATION, and PI_INVALID_VALUE.
convertReadData() [3/4]
template<typename ChannelType > void cl::sycl::detail::convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, vec< cl_int, 4 > & RetData)
Definition at line 306 of file image_accessor_util.hpp.
References PI_INVALID_VALUE.
convertReadData() [4/4]
template<typename ChannelType > void cl::sycl::detail::convertReadData (const vec< ChannelType, 4 > PixelData, const image_channel_type ImageChannelType, vec< cl_uint, 4 > & RetData)
Definition at line 284 of file image_accessor_util.hpp.
References PI_INVALID_VALUE.
convertToArrayOfN()
template<int NewDim, int DefaultValue, template< int > class T, int OldDim> static T<NewDim> cl::sycl::detail::convertToArrayOfN (T< OldDim > OldObj) static
Definition at line 254 of file accessor.hpp.
convertToExtendedMembers()
static std::shared_ptr<std::vector<ExtendedMemberT> > cl::sycl::detail::convertToExtendedMembers (const std::shared_ptr< const void > & SPtr) static
Definition at line 113 of file cg.hpp.
Referenced by cl::sycl::detail::CG::getExtendedMembers(), cl::sycl::getHandlerImplMember(), and cl::sycl::handler::mem_advise().
convertToFloat4() [1/3]
template<typename T > detail::enable_if_t<IsValidCoordType<T>::value, cl_float4> cl::sycl::detail::convertToFloat4 (T Coords)
Definition at line 60 of file image_accessor_util.hpp.
convertToFloat4() [2/3]
template<typename T > detail::enable_if_t<IsValidCoordType<T>::value, cl_float4> cl::sycl::detail::convertToFloat4 (vec< T, 2 > Coords)
Definition at line 66 of file image_accessor_util.hpp.
convertToFloat4() [3/3]
template<typename T > detail::enable_if_t<IsValidCoordType<T>::value, cl_float4> cl::sycl::detail::convertToFloat4 (vec< T, 4 > Coords)
Definition at line 73 of file image_accessor_util.hpp.
Referenced by imageReadSamplerHostImpl().
convertWriteData() [1/4]
template<typename ChannelType > vec<ChannelType, 4> cl::sycl::detail::convertWriteData (const vec< cl_float, 4 > WriteData, const image_channel_type ImageChannelType)
Definition at line 558 of file image_accessor_util.hpp.
References PI_INVALID_OPERATION, and PI_INVALID_VALUE.
convertWriteData() [2/4]
template<typename ChannelType > vec<ChannelType, 4> cl::sycl::detail::convertWriteData (const vec< cl_half, 4 > WriteData, const image_channel_type ImageChannelType)
Definition at line 636 of file image_accessor_util.hpp.
References PI_INVALID_OPERATION, and PI_INVALID_VALUE.
convertWriteData() [3/4]
template<typename ChannelType > vec<ChannelType, 4> cl::sycl::detail::convertWriteData (const vec< cl_int, 4 > WriteData, const image_channel_type ImageChannelType)
Definition at line 515 of file image_accessor_util.hpp.
References cl::sycl::clamp(), and PI_INVALID_VALUE.
convertWriteData() [4/4]
template<typename ChannelType > vec<ChannelType, 4> cl::sycl::detail::convertWriteData (const vec< cl_uint, 4 > WriteData, const image_channel_type ImageChannelType)
Definition at line 482 of file image_accessor_util.hpp.
References cl::sycl::clamp(), and PI_INVALID_VALUE.
copyD2D()
void cl::sycl::detail::copyD2D (SYCLMemObjI * SYCLMemObj, RT::PiMem SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, RT::PiMem DstMem, QueueImplPtr , unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > , sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< RT::PiEvent > DepEvents, RT::PiEvent & OutEvent)
Definition at line 634 of file memory_manager.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::SYCLMemObjI::getType(), piEnqueueMemBufferCopy(), piEnqueueMemBufferCopyRect(), piEnqueueMemImageCopy(), prepTermPositions(), cl::sycl::detail::TermPositions::XTerm, cl::sycl::detail::TermPositions::YTerm, and cl::sycl::detail::TermPositions::ZTerm.
Referenced by cl::sycl::detail::MemoryManager::copy().
copyD2H()
void cl::sycl::detail::copyD2H (SYCLMemObjI * SYCLMemObj, RT::PiMem SrcMem, QueueImplPtr SrcQueue, unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char * DstMem, QueueImplPtr , unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< RT::PiEvent > DepEvents, RT::PiEvent & OutEvent)
Definition at line 557 of file memory_manager.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::SYCLMemObjI::getType(), piEnqueueMemBufferRead(), piEnqueueMemBufferReadRect(), prepTermPositions(), cl::sycl::detail::TermPositions::XTerm, cl::sycl::detail::TermPositions::YTerm, and cl::sycl::detail::TermPositions::ZTerm.
Referenced by cl::sycl::detail::MemoryManager::copy().
copyH2D()
void cl::sycl::detail::copyH2D (SYCLMemObjI * SYCLMemObj, char * SrcMem, QueueImplPtr , unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, RT::PiMem DstMem, QueueImplPtr TgtQueue, unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< RT::PiEvent > DepEvents, RT::PiEvent & OutEvent)
Definition at line 485 of file memory_manager.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::SYCLMemObjI::getType(), piEnqueueMemBufferWrite(), piEnqueueMemBufferWriteRect(), prepTermPositions(), cl::sycl::detail::TermPositions::XTerm, cl::sycl::detail::TermPositions::YTerm, and cl::sycl::detail::TermPositions::ZTerm.
Referenced by cl::sycl::detail::MemoryManager::copy().
copyH2H()
static void cl::sycl::detail::copyH2H (SYCLMemObjI * , char * SrcMem, QueueImplPtr , unsigned int DimSrc, sycl::range< 3 > SrcSize, sycl::range< 3 > SrcAccessRange, sycl::id< 3 > SrcOffset, unsigned int SrcElemSize, char * DstMem, QueueImplPtr , unsigned int DimDst, sycl::range< 3 > DstSize, sycl::range< 3 > DstAccessRange, sycl::id< 3 > DstOffset, unsigned int DstElemSize, std::vector< RT::PiEvent > , RT::PiEvent &) static
Definition at line 706 of file memory_manager.cpp.
References memcpy(), and PI_INVALID_OPERATION.
Referenced by cl::sycl::detail::MemoryManager::copy().
createBinaryProgram()
static RT::PiProgram cl::sycl::detail::createBinaryProgram (const ContextImplPtr Context, const device & Device, const unsigned char * Data, size_t DataLen, const std::vector< pi_device_binary_property > Metadata) static
Definition at line 68 of file program_manager.cpp.
References cl::sycl::detail::plugin::call(), getSyclObjImpl(), PI_CONTEXT_INFO_NUM_DEVICES, piContextGetInfo(), and piProgramCreateWithBinary().
Referenced by cl::sycl::detail::ProgramManager::createPIProgram(), and cl::sycl::detail::ProgramManager::getOrCreatePIProgram().
createDiscardedEvent()
static event cl::sycl::detail::createDiscardedEvent () static
Definition at line 54 of file queue_impl.cpp.
Referenced by cl::sycl::detail::queue_impl::mem_advise(), cl::sycl::detail::queue_impl::memcpy(), and cl::sycl::detail::queue_impl::memset().
createKernelArgMask()
static ProgramManager::KernelArgMask cl::sycl::detail::createKernelArgMask (const pi::ByteArray & Bytes) static
Definition at line 1062 of file program_manager.cpp.
Referenced by cl::sycl::detail::ProgramManager::addImages().
createSpirvProgram()
static RT::PiProgram cl::sycl::detail::createSpirvProgram (const ContextImplPtr Context, const unsigned char * Data, size_t DataLen) static
Definition at line 96 of file program_manager.cpp.
References cl::sycl::detail::plugin::call(), and piProgramCreate().
Referenced by cl::sycl::detail::ProgramManager::createPIProgram(), and loadDeviceLib().
createSyclObjFromImpl()
template<class T > T cl::sycl::detail::createSyclObjFromImpl (decltype(T::impl) ImplObj)
Definition at line 215 of file common.hpp.
Referenced by cl::sycl::kernel::get_kernel_bundle(), and cl::sycl::get_kernel_bundle().
deallocateStreams()
static void cl::sycl::detail::deallocateStreams (std::vector< std::shared_ptr< stream_impl >> & StreamsToDeallocate) static
Definition at line 223 of file scheduler.cpp.
Referenced by cl::sycl::detail::Scheduler::cleanupFinishedCommands(), and cl::sycl::detail::Scheduler::removeMemoryObject().
declptr()
template<typename T > T* cl::sycl::detail::declptr ()
Definition at line 56 of file helpers.hpp.
Referenced by cl::sycl::this_group(), cl::sycl::ext::oneapi::experimental::this_group(), cl::sycl::this_id(), cl::sycl::ext::oneapi::experimental::this_id(), cl::sycl::this_item(), cl::sycl::ext::oneapi::experimental::this_item(), cl::sycl::this_nd_item(), and cl::sycl::ext::oneapi::experimental::this_nd_item().
demangleKernelName()
static std::string cl::sycl::detail::demangleKernelName (std::string Name) static
Definition at line 73 of file commands.cpp.
Referenced by cl::sycl::detail::ExecCGCommand::emitInstrumentationData(), and cl::sycl::detail::ExecCGCommand::printDot().
deviceIsAllowed()
bool cl::sycl::detail::deviceIsAllowed (const DeviceDescT & DeviceDesc, const AllowListParsedT & AllowListParsed)
Definition at line 282 of file allowlist.cpp.
References all_of(), BackendNameKeyName, DeviceNameKeyName, DeviceTypeKeyName, DeviceVendorIdKeyName, DriverVersionKeyName, PlatformNameKeyName, PlatformVersionKeyName, and SupportedAllowListKeyNames.
Referenced by applyAllowList().
deviceToString()
static std::string cl::sycl::detail::deviceToString (device Device) static
Definition at line 76 of file commands.cpp.
References cl::sycl::device::is_accelerator(), cl::sycl::device::is_cpu(), cl::sycl::device::is_gpu(), and cl::sycl::device::is_host().
Referenced by cl::sycl::detail::EmptyCommand::emitInstrumentationData(), cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), cl::sycl::detail::AllocaCommandBase::emitInstrumentationData(), cl::sycl::detail::MapMemObject::emitInstrumentationData(), cl::sycl::detail::UnMapMemObject::emitInstrumentationData(), cl::sycl::detail::MemCpyCommand::emitInstrumentationData(), cl::sycl::detail::MemCpyCommandHost::emitInstrumentationData(), cl::sycl::detail::ExecCGCommand::emitInstrumentationData(), cl::sycl::detail::UpdateHostRequirementCommand::emitInstrumentationData(), cl::sycl::detail::ReleaseCommand::printDot(), cl::sycl::detail::AllocaCommand::printDot(), cl::sycl::detail::AllocaSubBufCommand::printDot(), cl::sycl::detail::MapMemObject::printDot(), cl::sycl::detail::UnMapMemObject::printDot(), cl::sycl::detail::MemCpyCommand::printDot(), cl::sycl::detail::MemCpyCommandHost::printDot(), cl::sycl::detail::ExecCGCommand::printDot(), and cl::sycl::detail::UpdateHostRequirementCommand::printDot().
digitToChar()
char cl::sycl::detail::digitToChar (const int Digit) inline
Definition at line 150 of file stream.hpp.
Referenced by floatingPointToDecStr(), and integralToBase().
DispatchNativeKernel()
void cl::sycl::detail::DispatchNativeKernel (void * Blob)
Definition at line 2005 of file commands.cpp.
References cl::sycl::detail::AccessorImplHost::MData.
doOverlap() [1/2]
static bool cl::sycl::detail::doOverlap (const Requirement * LHS, const Requirement * RHS) inline static
Definition at line 19 of file leaves_collection.cpp.
References cl::sycl::detail::AccessorImplHost::MAccessRange, cl::sycl::detail::AccessorImplHost::MElemSize, cl::sycl::detail::AccessorImplHost::MOffsetInBytes, and cl::sycl::range< dimensions >::size().
doOverlap() [2/2]
static bool cl::sycl::detail::doOverlap (const Requirement * LHS, const Requirement * RHS) static
Checks whether two requirements overlap or not.
This information can be used to prove that executing two kernels that work on different parts of the memory object in parallel is legal.
Definition at line 37 of file graph_builder.cpp.
References cl::sycl::detail::AccessorImplHost::MAccessRange, cl::sycl::detail::AccessorImplHost::MElemSize, cl::sycl::detail::AccessorImplHost::MOffsetInBytes, and cl::sycl::range< dimensions >::size().
dumpConfig()
void cl::sycl::detail::dumpConfig ()
Definition at line 148 of file config.cpp.
emitBuiltProgramInfo()
static void cl::sycl::detail::emitBuiltProgramInfo (const pi_program & Prog, const ContextImplPtr & Context) static
Emits information about built programs if the appropriate contitions are met, namely when SYCL_RT_WARNING_LEVEL is greater than or equal to 2.
Definition at line 472 of file program_manager.cpp.
Referenced by cl::sycl::detail::ProgramManager::build(), and cl::sycl::detail::ProgramManager::getBuiltPIProgram().
emitMemAllocBeginTrace()
uint64_t cl::sycl::detail::emitMemAllocBeginTrace (uintptr_t ObjHandle, size_t AllocSize, size_t GuardZone)
Definition at line 35 of file memory_manager.cpp.
Referenced by memBufferCreateHelper(), and memBufferMapHelper().
emitMemAllocEndTrace()
void cl::sycl::detail::emitMemAllocEndTrace (uintptr_t ObjHandle, uintptr_t AllocPtr, size_t AllocSize, size_t GuardZone, uint64_t CorrelationID)
Definition at line 56 of file memory_manager.cpp.
Referenced by memBufferCreateHelper(), and memBufferMapHelper().
emitMemReleaseBeginTrace()
uint64_t cl::sycl::detail::emitMemReleaseBeginTrace (uintptr_t ObjHandle, uintptr_t AllocPtr)
Definition at line 76 of file memory_manager.cpp.
Referenced by memReleaseHelper(), and memUnmapHelper().
emitMemReleaseEndTrace()
void cl::sycl::detail::emitMemReleaseEndTrace (uintptr_t ObjHandle, uintptr_t AllocPtr, uint64_t CorrelationID)
Definition at line 95 of file memory_manager.cpp.
Referenced by memReleaseHelper(), and memUnmapHelper().
enableITTAnnotationsIfNeeded()
static void cl::sycl::detail::enableITTAnnotationsIfNeeded (const RT::PiProgram & Prog, const plugin & Plugin) static
This function enables ITT annotations in SPIR-V module by setting a specialization constant if INTEL_LIBITTNOTIFY64 env variable is set.
Definition at line 54 of file program_manager.cpp.
References cl::sycl::detail::plugin::call(), ITTSpecConstId, and piextProgramSetSpecializationConstant().
Referenced by cl::sycl::detail::ProgramManager::build(), cl::sycl::detail::ProgramManager::compile(), and cl::sycl::detail::ProgramManager::getBuiltPIProgram().
enqueueImpKernel()
cl_int cl::sycl::detail::enqueueImpKernel (const QueueImplPtr & Queue, NDRDescT & NDRDesc, std::vector< ArgDesc > & Args, const std::shared_ptr< detail::kernel_bundle_impl > & KernelBundleImplPtr, const std::shared_ptr< detail::kernel_impl > & MSyclKernel, const std::string & KernelName, const detail::OSModuleHandle & OSModuleHandle, std::vector< RT::PiEvent > & RawEvents, RT::PiEvent * OutEvent, const std::function< void *(Requirement *Req)> & getMemAllocationFunc)
Definition at line 2029 of file commands.cpp.
References cl::sycl::info::context, cl::sycl::detail::ProgramManager::getEliminatedKernelArgMask(), cl::sycl::detail::ProgramManager::getInstance(), cl::sycl::detail::ProgramManager::getOrCreateKernel(), cl::sycl::detail::ProgramManager::getSYCLKernelID(), getSyclObjImpl(), cl::sycl::detail::enqueue_kernel_launch::handleError(), PI_SUCCESS, SetKernelParamsAndLaunch(), and tie().
event_impl::get_info< info::event::command_execution_status >()
template<> info::event_command_status cl::sycl::detail::event_impl::get_info< info::event::command_execution_status > () const
Definition at line 321 of file event_impl.cpp.
References cl::sycl::info::complete, cl::sycl::info::ext_oneapi_unknown, cl::sycl::detail::get_event_info< Param >::get(), getPlugin(), and cl::sycl::info::submitted.
event_impl::get_info< info::event::reference_count >()
template<> cl_uint cl::sycl::detail::event_impl::get_info< info::event::reference_count > () const
Definition at line 311 of file event_impl.cpp.
References cl::sycl::detail::get_event_info< Param >::get(), and getPlugin().
event_impl::get_profiling_info< info::event_profiling::command_end >()
template<> cl_ulong cl::sycl::detail::event_impl::get_profiling_info< info::event_profiling::command_end > () const
Definition at line 297 of file event_impl.cpp.
References cl::sycl::detail::get_event_profiling_info< Param >::get(), getPlugin(), and PI_PROFILING_INFO_NOT_AVAILABLE.
event_impl::get_profiling_info< info::event_profiling::command_start >()
template<> cl_ulong cl::sycl::detail::event_impl::get_profiling_info< info::event_profiling::command_start > () const
Definition at line 280 of file event_impl.cpp.
References cl::sycl::info::command_start, std::get(), getPlugin(), and PI_PROFILING_INFO_NOT_AVAILABLE.
event_impl::get_profiling_info< info::event_profiling::command_submit >()
template<> cl_ulong cl::sycl::detail::event_impl::get_profiling_info< info::event_profiling::command_submit > () const
Definition at line 263 of file event_impl.cpp.
References cl::sycl::info::command_submit, std::get(), getPlugin(), and PI_PROFILING_INFO_NOT_AVAILABLE.
filterDeviceFilter()
static void cl::sycl::detail::filterDeviceFilter (std::vector< RT::PiDevice > & PiDevices, RT::PiPlatform Platform) static
Definition at line 156 of file platform_impl.cpp.
References cl::sycl::all(), cl::sycl::detail::plugin::call(), cl::sycl::detail::device_filter_list::get(), std::get(), cl::sycl::detail::plugin::getBackend(), cl::sycl::detail::plugin::getPluginMutex(), cl::sycl::detail::plugin::getStartingDeviceId(), cl::sycl::detail::pi::initialize(), PI_DEVICE_INFO_TYPE, piDeviceGetInfo(), and cl::sycl::detail::plugin::setLastDeviceId().
Referenced by cl::sycl::detail::platform_impl::get_devices().
find_device_intersection()
std::vector< sycl::device > cl::sycl::detail::find_device_intersection (const std::vector< kernel_bundle< bundle_state::object >> & ObjectBundles)
Definition at line 260 of file kernel_bundle.cpp.
References cl::sycl::device::get_devices().
float2Half()
__SYCL_CONSTEXPR_HALF uint16_t cl::sycl::detail::float2Half (const float & Val) inline
Definition at line 48 of file half_type.hpp.
References __builtin_expect.
floatingPointToDecStr()
template<typename T > EnableIfFP<T, unsigned> cl::sycl::detail::floatingPointToDecStr (T AbsVal, char * Digits, int Precision, bool IsSci)
Definition at line 264 of file stream.hpp.
References digitToChar(), and MAX_FLOATING_POINT_DIGITS.
Referenced by ScalarToStr().
flushBuffer()
void cl::sycl::detail::flushBuffer (GlobalOffsetAccessorT & GlobalOffset, GlobalBufAccessorT & GlobalBuf, GlobalBufAccessorT & GlobalFlushBuf, unsigned WIOffset) inline
Definition at line 444 of file stream.hpp.
References FLUSH_BUF_OFFSET_SIZE, GetFlushBufOffset(), SetFlushBufOffset(), and updateOffset().
Referenced by cl::sycl::operator<<().
flushCrossQueueDeps()
static void cl::sycl::detail::flushCrossQueueDeps (const std::vector< EventImplPtr > & EventImpls, const QueueImplPtr & Queue) static
Definition at line 183 of file commands.cpp.
Referenced by cl::sycl::detail::Command::waitForEvents().
for_each()
template<typename Group , typename Ptr , class Function > Function cl::sycl::detail::for_each (Group g, Ptr first, Ptr last, Function f)
Definition at line 148 of file group_algorithm.hpp.
References get_local_linear_id(), get_local_linear_range(), and PI_INVALID_DEVICE.
Referenced by cl::sycl::detail::device_impl::create_sub_devices(), _pi_context::getFreeSlotInExistingOrNewPool(), cl::sycl::joint_all_of(), cl::sycl::joint_any_of(), cl::sycl::joint_reduce(), and cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl().
force_type()
void cl::sycl::detail::force_type (info::device_type & t, const info::device_type & ft)
Definition at line 22 of file device.cpp.
References cl::sycl::all(), and PI_INVALID_OPERATION.
Referenced by cl::sycl::device::get_devices().
get_device_info_host()
template<info::device param> info::param_traits<info::device, param>::return_type cl::sycl::detail::get_device_info_host () inline delete
get_device_info_host< info::device::address_bits >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::address_bits > () inline
Definition at line 733 of file device_info.hpp.
get_device_info_host< info::device::atomic64 >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::atomic64 > () inline
Definition at line 754 of file device_info.hpp.
get_device_info_host< info::device::atomic_memory_order_capabilities >()
template<> std::vector<memory_order> cl::sycl::detail::get_device_info_host< info::device::atomic_memory_order_capabilities > () inline
Definition at line 760 of file device_info.hpp.
get_device_info_host< info::device::atomic_memory_scope_capabilities >()
template<> std::vector<memory_scope> cl::sycl::detail::get_device_info_host< info::device::atomic_memory_scope_capabilities > () inline
Definition at line 767 of file device_info.hpp.
get_device_info_host< info::device::backend_version >()
template<> std::string cl::sycl::detail::get_device_info_host< info::device::backend_version > () inline
Definition at line 1142 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::built_in_kernel_ids >()
template<> std::vector<kernel_id> cl::sycl::detail::get_device_info_host< info::device::built_in_kernel_ids > () inline
Definition at line 1009 of file device_info.hpp.
get_device_info_host< info::device::built_in_kernels >()
template<> std::vector<std::string> cl::sycl::detail::get_device_info_host< info::device::built_in_kernels > () inline
Definition at line 1015 of file device_info.hpp.
get_device_info_host< info::device::device_type >()
template<> info::device_type cl::sycl::detail::get_device_info_host< info::device::device_type > () inline
Definition at line 579 of file device_info.hpp.
get_device_info_host< info::device::double_fp_config >()
template<> std::vector<info::fp_config> cl::sycl::detail::get_device_info_host< info::device::double_fp_config > () inline
Definition at line 908 of file device_info.hpp.
References cl::sycl::fma().
get_device_info_host< info::device::driver_version >()
template<> std::string cl::sycl::detail::get_device_info_host< info::device::driver_version > () inline
Definition at line 1032 of file device_info.hpp.
get_device_info_host< info::device::error_correction_support >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::error_correction_support > () inline
Definition at line 957 of file device_info.hpp.
get_device_info_host< info::device::execution_capabilities >()
template<> std::vector<info::execution_capability> cl::sycl::detail::get_device_info_host< info::device::execution_capabilities > () inline
Definition at line 999 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_device_info_uuid >()
template<> detail::uuid_type cl::sycl::detail::get_device_info_host< info::device::ext_intel_device_info_uuid > () inline
Definition at line 1317 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_intel_gpu_eu_count >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::ext_intel_gpu_eu_count > () inline
Definition at line 1266 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_intel_gpu_eu_count_per_subslice >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::ext_intel_gpu_eu_count_per_subslice > () inline
Definition at line 1292 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_intel_gpu_eu_simd_width >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::ext_intel_gpu_eu_simd_width > () inline
Definition at line 1272 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_intel_gpu_hw_threads_per_eu >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::ext_intel_gpu_hw_threads_per_eu > () inline
Definition at line 1299 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_intel_gpu_slices >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::ext_intel_gpu_slices > () inline
Definition at line 1278 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_intel_gpu_subslices_per_slice >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::ext_intel_gpu_subslices_per_slice > () inline
Definition at line 1285 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_intel_max_mem_bandwidth >()
template<> cl_ulong cl::sycl::detail::get_device_info_host< info::device::ext_intel_max_mem_bandwidth > () inline
Definition at line 1306 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_intel_mem_channel >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::ext_intel_mem_channel > () inline
Definition at line 1175 of file device_info.hpp.
get_device_info_host< info::device::ext_intel_pci_address >()
template<> std::string cl::sycl::detail::get_device_info_host< info::device::ext_intel_pci_address > () inline
Definition at line 1260 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::ext_oneapi_max_global_work_groups >()
template<> constexpr size_t cl::sycl::detail::get_device_info_host< info::device::ext_oneapi_max_global_work_groups > () inline constexpr
Definition at line 605 of file device_info.hpp.
References max().
get_device_info_host< info::device::ext_oneapi_max_work_groups_1d >()
template<> id<1> cl::sycl::detail::get_device_info_host< info::device::ext_oneapi_max_work_groups_1d > () inline
Definition at line 612 of file device_info.hpp.
get_device_info_host< info::device::ext_oneapi_max_work_groups_2d >()
template<> id<2> cl::sycl::detail::get_device_info_host< info::device::ext_oneapi_max_work_groups_2d > () inline
Definition at line 621 of file device_info.hpp.
get_device_info_host< info::device::ext_oneapi_max_work_groups_3d >()
template<> id<3> cl::sycl::detail::get_device_info_host< info::device::ext_oneapi_max_work_groups_3d > () inline
Definition at line 630 of file device_info.hpp.
get_device_info_host< info::device::ext_oneapi_srgb >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::ext_oneapi_srgb > () inline
Definition at line 1311 of file device_info.hpp.
get_device_info_host< info::device::extensions >()
template<> std::vector<std::string> cl::sycl::detail::get_device_info_host< info::device::extensions > () inline
Definition at line 1051 of file device_info.hpp.
get_device_info_host< info::device::global_mem_cache_line_size >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::global_mem_cache_line_size > () inline
Definition at line 923 of file device_info.hpp.
get_device_info_host< info::device::global_mem_cache_size >()
template<> cl_ulong cl::sycl::detail::get_device_info_host< info::device::global_mem_cache_size > () inline
Definition at line 928 of file device_info.hpp.
get_device_info_host< info::device::global_mem_cache_type >()
template<> info::global_mem_cache_type cl::sycl::detail::get_device_info_host< info::device::global_mem_cache_type > () inline
Definition at line 917 of file device_info.hpp.
get_device_info_host< info::device::global_mem_size >()
template<> cl_ulong cl::sycl::detail::get_device_info_host< info::device::global_mem_size > () inline
Definition at line 738 of file device_info.hpp.
get_device_info_host< info::device::half_fp_config >()
template<> std::vector<info::fp_config> cl::sycl::detail::get_device_info_host< info::device::half_fp_config > () inline
Definition at line 894 of file device_info.hpp.
get_device_info_host< info::device::host_unified_memory >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::host_unified_memory > () inline
Definition at line 962 of file device_info.hpp.
get_device_info_host< info::device::image2d_max_height >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::image2d_max_height > () inline
Definition at line 801 of file device_info.hpp.
References max().
get_device_info_host< info::device::image2d_max_width >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::image2d_max_width > () inline
Definition at line 785 of file device_info.hpp.
References max().
get_device_info_host< info::device::image3d_max_depth >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::image3d_max_depth > () inline
Definition at line 849 of file device_info.hpp.
References max().
get_device_info_host< info::device::image3d_max_height >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::image3d_max_height > () inline
Definition at line 833 of file device_info.hpp.
References max().
get_device_info_host< info::device::image3d_max_width >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::image3d_max_width > () inline
Definition at line 817 of file device_info.hpp.
References max().
get_device_info_host< info::device::image_max_array_size >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::image_max_array_size > () inline
Definition at line 871 of file device_info.hpp.
get_device_info_host< info::device::image_max_buffer_size >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::image_max_buffer_size > () inline
Definition at line 865 of file device_info.hpp.
get_device_info_host< info::device::image_support >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::image_support > () inline
Definition at line 750 of file device_info.hpp.
get_device_info_host< info::device::is_available >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::is_available > () inline
Definition at line 983 of file device_info.hpp.
get_device_info_host< info::device::is_compiler_available >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::is_compiler_available > () inline
Definition at line 988 of file device_info.hpp.
get_device_info_host< info::device::is_endian_little >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::is_endian_little > () inline
Definition at line 974 of file device_info.hpp.
References cl::sycl::a.
get_device_info_host< info::device::is_linker_available >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::is_linker_available > () inline
Definition at line 993 of file device_info.hpp.
get_device_info_host< info::device::kernel_kernel_pipe_support >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::kernel_kernel_pipe_support > () inline
Definition at line 1137 of file device_info.hpp.
get_device_info_host< info::device::local_mem_size >()
template<> cl_ulong cl::sycl::detail::get_device_info_host< info::device::local_mem_size > () inline
Definition at line 951 of file device_info.hpp.
get_device_info_host< info::device::local_mem_type >()
template<> info::local_mem_type cl::sycl::detail::get_device_info_host< info::device::local_mem_type > () inline
Definition at line 946 of file device_info.hpp.
get_device_info_host< info::device::max_clock_frequency >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::max_clock_frequency > () inline
Definition at line 729 of file device_info.hpp.
get_device_info_host< info::device::max_compute_units >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::max_compute_units > () inline
Definition at line 588 of file device_info.hpp.
get_device_info_host< info::device::max_constant_args >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::max_constant_args > () inline
Definition at line 939 of file device_info.hpp.
get_device_info_host< info::device::max_constant_buffer_size >()
template<> cl_ulong cl::sycl::detail::get_device_info_host< info::device::max_constant_buffer_size > () inline
Definition at line 933 of file device_info.hpp.
get_device_info_host< info::device::max_mem_alloc_size >()
template<> cl_ulong cl::sycl::detail::get_device_info_host< info::device::max_mem_alloc_size > () inline
Definition at line 743 of file device_info.hpp.
References cl::sycl::a.
get_device_info_host< info::device::max_num_sub_groups >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::max_num_sub_groups > () inline
Definition at line 1114 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::max_parameter_size >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::max_parameter_size > () inline
Definition at line 882 of file device_info.hpp.
get_device_info_host< info::device::max_read_image_args >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::max_read_image_args > () inline
Definition at line 773 of file device_info.hpp.
get_device_info_host< info::device::max_samplers >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::max_samplers > () inline
Definition at line 876 of file device_info.hpp.
get_device_info_host< info::device::max_work_group_size >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::max_work_group_size > () inline
Definition at line 638 of file device_info.hpp.
get_device_info_host< info::device::max_work_item_dimensions >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::max_work_item_dimensions > () inline
Definition at line 593 of file device_info.hpp.
get_device_info_host< info::device::max_work_item_sizes >()
template<> id<3> cl::sycl::detail::get_device_info_host< info::device::max_work_item_sizes > () inline
Definition at line 598 of file device_info.hpp.
get_device_info_host< info::device::max_write_image_args >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::max_write_image_args > () inline
Definition at line 779 of file device_info.hpp.
get_device_info_host< info::device::mem_base_addr_align >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::mem_base_addr_align > () inline
Definition at line 888 of file device_info.hpp.
get_device_info_host< info::device::name >()
template<> std::string cl::sycl::detail::get_device_info_host< info::device::name > () inline
Definition at line 1023 of file device_info.hpp.
get_device_info_host< info::device::native_vector_width_char >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::native_vector_width_char > () inline
Definition at line 693 of file device_info.hpp.
get_device_info_host< info::device::native_vector_width_double >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::native_vector_width_double > () inline
Definition at line 719 of file device_info.hpp.
get_device_info_host< info::device::native_vector_width_float >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::native_vector_width_float > () inline
Definition at line 713 of file device_info.hpp.
get_device_info_host< info::device::native_vector_width_half >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::native_vector_width_half > () inline
Definition at line 724 of file device_info.hpp.
get_device_info_host< info::device::native_vector_width_int >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::native_vector_width_int > () inline
Definition at line 703 of file device_info.hpp.
get_device_info_host< info::device::native_vector_width_long >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::native_vector_width_long > () inline
Definition at line 708 of file device_info.hpp.
get_device_info_host< info::device::native_vector_width_short >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::native_vector_width_short > () inline
Definition at line 698 of file device_info.hpp.
get_device_info_host< info::device::opencl_c_version >()
template<> std::string cl::sycl::detail::get_device_info_host< info::device::opencl_c_version > () inline
Definition at line 1045 of file device_info.hpp.
get_device_info_host< info::device::parent_device >()
template<> device cl::sycl::detail::get_device_info_host< info::device::parent_device > () inline
Definition at line 1067 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::partition_affinity_domains >()
template<> std::vector<info::partition_affinity_domain> cl::sycl::detail::get_device_info_host< info::device::partition_affinity_domains > () inline
Definition at line 1089 of file device_info.hpp.
get_device_info_host< info::device::partition_max_sub_devices >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::partition_max_sub_devices > () inline
Definition at line 1075 of file device_info.hpp.
get_device_info_host< info::device::partition_properties >()
template<> std::vector<info::partition_property> cl::sycl::detail::get_device_info_host< info::device::partition_properties > () inline
Definition at line 1082 of file device_info.hpp.
get_device_info_host< info::device::partition_type_affinity_domain >()
template<> info::partition_affinity_domain cl::sycl::detail::get_device_info_host< info::device::partition_type_affinity_domain > () inline
Definition at line 1102 of file device_info.hpp.
get_device_info_host< info::device::partition_type_property >()
template<> info::partition_property cl::sycl::detail::get_device_info_host< info::device::partition_type_property > () inline
Definition at line 1096 of file device_info.hpp.
get_device_info_host< info::device::platform >()
template<> platform cl::sycl::detail::get_device_info_host< info::device::platform > () inline
Definition at line 1019 of file device_info.hpp.
get_device_info_host< info::device::preferred_interop_user_sync >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::preferred_interop_user_sync > () inline
Definition at line 1063 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_char >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::preferred_vector_width_char > () inline
Definition at line 645 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_double >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::preferred_vector_width_double > () inline
Definition at line 680 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_float >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::preferred_vector_width_float > () inline
Definition at line 673 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_half >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::preferred_vector_width_half > () inline
Definition at line 687 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_int >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::preferred_vector_width_int > () inline
Definition at line 659 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_long >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::preferred_vector_width_long > () inline
Definition at line 666 of file device_info.hpp.
get_device_info_host< info::device::preferred_vector_width_short >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::preferred_vector_width_short > () inline
Definition at line 652 of file device_info.hpp.
get_device_info_host< info::device::printf_buffer_size >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::printf_buffer_size > () inline
Definition at line 1057 of file device_info.hpp.
get_device_info_host< info::device::profile >()
template<> std::string cl::sycl::detail::get_device_info_host< info::device::profile > () inline
Definition at line 1036 of file device_info.hpp.
get_device_info_host< info::device::profiling_timer_resolution >()
template<> size_t cl::sycl::detail::get_device_info_host< info::device::profiling_timer_resolution > () inline
Definition at line 967 of file device_info.hpp.
get_device_info_host< info::device::queue_profiling >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::queue_profiling > () inline
Definition at line 1003 of file device_info.hpp.
get_device_info_host< info::device::reference_count >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::reference_count > () inline
Definition at line 1108 of file device_info.hpp.
get_device_info_host< info::device::single_fp_config >()
template<> std::vector<info::fp_config> cl::sycl::detail::get_device_info_host< info::device::single_fp_config > () inline
Definition at line 901 of file device_info.hpp.
get_device_info_host< info::device::sub_group_independent_forward_progress >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::sub_group_independent_forward_progress > () inline
Definition at line 1130 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::sub_group_sizes >()
template<> std::vector<size_t> cl::sycl::detail::get_device_info_host< info::device::sub_group_sizes > () inline
Definition at line 1122 of file device_info.hpp.
References PI_INVALID_DEVICE.
get_device_info_host< info::device::usm_device_allocations >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::usm_device_allocations > () inline
Definition at line 1149 of file device_info.hpp.
get_device_info_host< info::device::usm_host_allocations >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::usm_host_allocations > () inline
Definition at line 1154 of file device_info.hpp.
get_device_info_host< info::device::usm_restricted_shared_allocations >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::usm_restricted_shared_allocations > () inline
Definition at line 1165 of file device_info.hpp.
get_device_info_host< info::device::usm_shared_allocations >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::usm_shared_allocations > () inline
Definition at line 1159 of file device_info.hpp.
get_device_info_host< info::device::usm_system_allocations >()
template<> bool cl::sycl::detail::get_device_info_host< info::device::usm_system_allocations > () inline
Definition at line 1170 of file device_info.hpp.
get_device_info_host< info::device::vendor >()
template<> std::string cl::sycl::detail::get_device_info_host< info::device::vendor > () inline
Definition at line 1027 of file device_info.hpp.
get_device_info_host< info::device::vendor_id >()
template<> cl_uint cl::sycl::detail::get_device_info_host< info::device::vendor_id > () inline
Definition at line 583 of file device_info.hpp.
get_device_info_host< info::device::version >()
template<> std::string cl::sycl::detail::get_device_info_host< info::device::version > () inline
Definition at line 1040 of file device_info.hpp.
get_empty_interop_kernel_bundle()
template<bundle_state State> kernel_bundle<State> cl::sycl::detail::get_empty_interop_kernel_bundle (const context & Ctx)
make_kernel may need an empty interop kernel bundle.
This function supplies this.
Definition at line 484 of file kernel_bundle.hpp.
References cl::sycl::context::get_devices(), and get_empty_interop_kernel_bundle_impl().
get_empty_interop_kernel_bundle_impl()
detail::KernelBundleImplPtr cl::sycl::detail::get_empty_interop_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs)
Definition at line 142 of file kernel_bundle.cpp.
Referenced by get_empty_interop_kernel_bundle().
get_forced_type()
info::device_type cl::sycl::detail::get_forced_type ()
Definition at line 24 of file force_device.cpp.
References cl::sycl::all(), and PI_INVALID_VALUE.
Referenced by cl::sycl::device::get_devices(), cl::sycl::detail::platform_impl::get_platforms(), and cl::sycl::default_selector::operator()().
get_kernel_bundle_impl() [1/3]
detail::KernelBundleImplPtr cl::sycl::detail::get_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, bundle_state State)
Definition at line 121 of file kernel_bundle.cpp.
get_kernel_bundle_impl() [2/3]
detail::KernelBundleImplPtr cl::sycl::detail::get_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, bundle_state State, const DevImgSelectorImpl & Selector)
Definition at line 135 of file kernel_bundle.cpp.
Referenced by cl::sycl::get_kernel_bundle().
get_kernel_bundle_impl() [3/3]
detail::KernelBundleImplPtr cl::sycl::detail::get_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, const std::vector< kernel_id > & KernelIDs, bundle_state State)
Definition at line 127 of file kernel_bundle.cpp.
get_kernel_device_specific_info_host()
template<info::kernel_device_specific Param> info::param_traits<info::kernel_device_specific, Param>::return_type cl::sycl::detail::get_kernel_device_specific_info_host (const cl::sycl::device & Device) inline
Referenced by get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple >().
get_kernel_device_specific_info_host< info::kernel_device_specific::compile_num_sub_groups >()
template<> uint32_t cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::compile_num_sub_groups > (const cl::sycl::device &) inline
Definition at line 166 of file kernel_info.hpp.
References PI_INVALID_KERNEL.
get_kernel_device_specific_info_host< info::kernel_device_specific::compile_sub_group_size >()
template<> uint32_t cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::compile_sub_group_size > (const cl::sycl::device &) inline
Definition at line 174 of file kernel_info.hpp.
References PI_INVALID_KERNEL.
get_kernel_device_specific_info_host< info::kernel_device_specific::compile_work_group_size >()
template<> cl::sycl::range<3> cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::compile_work_group_size > (const cl::sycl::device &) inline
Definition at line 130 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::ext_codeplay_num_regs >()
template<> uint32_t cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::ext_codeplay_num_regs > (const cl::sycl::device &) inline
Definition at line 151 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::global_work_size >()
template<> cl::sycl::range<3> cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::global_work_size > (const cl::sycl::device &) inline
Definition at line 116 of file kernel_info.hpp.
References PI_INVALID_KERNEL.
get_kernel_device_specific_info_host< info::kernel_device_specific::max_num_sub_groups >()
template<> uint32_t cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::max_num_sub_groups > (const cl::sycl::device &) inline
Definition at line 158 of file kernel_info.hpp.
References PI_INVALID_KERNEL.
get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple >()
template<> size_t cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple > (const cl::sycl::device & Dev) inline
Definition at line 137 of file kernel_info.hpp.
References get_kernel_device_specific_info_host().
get_kernel_device_specific_info_host< info::kernel_device_specific::private_mem_size >()
template<> cl_ulong cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::private_mem_size > (const cl::sycl::device &) inline
Definition at line 145 of file kernel_info.hpp.
get_kernel_device_specific_info_host< info::kernel_device_specific::work_group_size >()
template<> size_t cl::sycl::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::work_group_size > (const cl::sycl::device & Dev) inline
Definition at line 123 of file kernel_info.hpp.
get_kernel_id_impl()
kernel_id cl::sycl::detail::get_kernel_id_impl (std::string KernelName)
Definition at line 116 of file kernel_bundle.cpp.
Referenced by cl::sycl::get_kernel_id().
get_local_linear_id()
template<typename Group > Group::linear_id_type cl::sycl::detail::get_local_linear_id (Group g)
Referenced by cl::sycl::exclusive_scan_over_group(), for_each(), cl::sycl::inclusive_scan_over_group(), cl::sycl::joint_exclusive_scan(), cl::sycl::joint_inclusive_scan(), cl::sycl::group< 1 >::leader(), and cl::sycl::ext::oneapi::leader().
get_local_linear_id< ext::oneapi::sub_group >()
template<> ext::oneapi::sub_group::linear_id_type cl::sycl::detail::get_local_linear_id< ext::oneapi::sub_group > (ext::oneapi::sub_group g) inline
Definition at line 85 of file group_algorithm.hpp.
References cl::sycl::ext::oneapi::sub_group::get_local_id().
get_local_linear_range()
template<typename Group > size_t cl::sycl::detail::get_local_linear_range (Group g)
Referenced by for_each(), cl::sycl::joint_exclusive_scan(), and cl::sycl::joint_inclusive_scan().
get_local_linear_range< ext::oneapi::sub_group >()
template<> size_t cl::sycl::detail::get_local_linear_range< ext::oneapi::sub_group > (ext::oneapi::sub_group g) inline
Definition at line 62 of file group_algorithm.hpp.
References cl::sycl::ext::oneapi::sub_group::get_local_range().
get_local_linear_range< group< 1 > >()
template<> size_t cl::sycl::detail::get_local_linear_range< group< 1 > > (group< 1 > g) inline
Definition at line 51 of file group_algorithm.hpp.
get_local_linear_range< group< 2 > >()
template<> size_t cl::sycl::detail::get_local_linear_range< group< 2 > > (group< 2 > g) inline
Definition at line 54 of file group_algorithm.hpp.
get_local_linear_range< group< 3 > >()
template<> size_t cl::sycl::detail::get_local_linear_range< group< 3 > > (group< 3 > g) inline
Definition at line 57 of file group_algorithm.hpp.
get_native_vector_width()
cl_uint cl::sycl::detail::get_native_vector_width (size_t idx)
get_or_store()
template<typename T > T cl::sycl::detail::get_or_store (const T * obj)
Definition at line 60 of file helpers.hpp.
get_platform_info_host()
template<info::platform param> info::param_traits<info::platform, param>::return_type cl::sycl::detail::get_platform_info_host () inline delete
get_platform_info_host< info::platform::extensions >()
template<> std::vector<std::string> cl::sycl::detail::get_platform_info_host< info::platform::extensions > () inline
Definition at line 78 of file platform_info.hpp.
get_platform_info_host< info::platform::name >()
template<> std::string cl::sycl::detail::get_platform_info_host< info::platform::name > () inline
Definition at line 67 of file platform_info.hpp.
get_platform_info_host< info::platform::profile >()
template<> std::string cl::sycl::detail::get_platform_info_host< info::platform::profile > () inline
Definition at line 58 of file platform_info.hpp.
get_platform_info_host< info::platform::vendor >()
template<> std::string cl::sycl::detail::get_platform_info_host< info::platform::vendor > () inline
Definition at line 72 of file platform_info.hpp.
get_platform_info_host< info::platform::version >()
template<> std::string cl::sycl::detail::get_platform_info_host< info::platform::version > () inline
Definition at line 63 of file platform_info.hpp.
get_tuple_tail()
template<typename T , typename... Ts> std::tuple<Ts...> cl::sycl::detail::get_tuple_tail (const std::tuple< T, Ts... > & Tuple)
Definition at line 31 of file tuple.hpp.
References get_tuple_tail_impl().
Referenced by cl::sycl::detail::tuple< T, Ts... >::operator=().
get_tuple_tail_impl()
template<typename T , typename... Ts, std::size_t... Is> std::tuple<Ts...> cl::sycl::detail::get_tuple_tail_impl (const std::tuple< T, Ts... > & Tuple, const std::index_sequence< Is... > &)
Definition at line 25 of file tuple.hpp.
Referenced by get_tuple_tail().
getAbsVal()
template<typename T > std::make_unsigned<T>::type cl::sycl::detail::getAbsVal (const T Val, const int Base) inline
Definition at line 145 of file stream.hpp.
Referenced by ScalarToStr().
getBinImageState()
static bundle_state cl::sycl::detail::getBinImageState (const RTDeviceBinaryImage * BinImage) static
Definition at line 1411 of file program_manager.cpp.
References __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_FPGA, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_X86_64, pi_device_binary_struct::DeviceTargetSpec, and cl::sycl::detail::RTDeviceBinaryImage::getRawData().
Referenced by cl::sycl::detail::ProgramManager::getSYCLDeviceImagesWithCompatibleState().
getBorderColor()
cl_float4 cl::sycl::detail::getBorderColor (const image_channel_order ImgChannelOrder)
Definition at line 174 of file image_accessor_util.cpp.
Referenced by getColor().
getCGTypeVersion()
constexpr unsigned char cl::sycl::detail::getCGTypeVersion (unsigned int Type) constexpr
Definition at line 139 of file cg.hpp.
References ShiftBitsForVersion.
Referenced by cl::sycl::detail::CG::getExtendedMembers(), and cl::sycl::detail::CG::getVersion().
getColor()
template<typename DataT > DataT cl::sycl::detail::getColor (const cl_int4 PixelCoord, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, const id< 3 > ImgPitch, const image_channel_type ImgChannelType, const image_channel_order ImgChannelOrder, void * BasePtr, const uint8_t ElementSize)
Definition at line 896 of file image_accessor_util.hpp.
References getBorderColor(), and isOutOfRange().
getCommand()
static Command* cl::sycl::detail::getCommand (const EventImplPtr & Event) static
Definition at line 20 of file graph_processor.cpp.
Referenced by cl::sycl::detail::Scheduler::GraphProcessor::waitForEvent().
getDelinearizedId() [1/3]
id<1> cl::sycl::detail::getDelinearizedId (const range< 1 > & , size_t Index) inline
Definition at line 318 of file id.hpp.
Referenced by cl::sycl::ext::oneapi::detail::reductionLoop().
getDelinearizedId() [2/3]
id<2> cl::sycl::detail::getDelinearizedId (const range< 2 > & Range, size_t Index) inline
Definition at line 322 of file id.hpp.
getDelinearizedId() [3/3]
id<3> cl::sycl::detail::getDelinearizedId (const range< 3 > & Range, size_t Index) inline
Definition at line 328 of file id.hpp.
getDeviceComparisonLambda()
auto cl::sycl::detail::getDeviceComparisonLambda () inline
Definition at line 380 of file kernel_bundle.hpp.
References cl::sycl::a.
Referenced by removeDuplicateDevices().
getDeviceFromHandler()
device cl::sycl::detail::getDeviceFromHandler (handler & CommandGroupHandlerRef)
Definition at line 15 of file accessor.cpp.
Referenced by cl::sycl::handler::parallel_for().
getDeviceFunctionPointerImpl()
ext::oneapi::device_func_ptr_holder_t cl::sycl::detail::getDeviceFunctionPointerImpl (device & D, program & P, const char * FuncName)
Definition at line 17 of file function_pointer.cpp.
References cl::sycl::detail::plugin::call_nocheck(), getSyclObjImpl(), PI_FUNCTION_ADDRESS_IS_NOT_AVAILABLE, PI_INVALID_KERNEL_NAME, PI_SUCCESS, and piextGetDeviceFunctionPointer().
getDeviceLibExtensionStr()
static const char* cl::sycl::detail::getDeviceLibExtensionStr (DeviceLibExt Extension) static
Definition at line 763 of file program_manager.cpp.
References PI_INVALID_OPERATION.
Referenced by getDeviceLibPrograms().
getDeviceLibFilename()
static const char* cl::sycl::detail::getDeviceLibFilename (DeviceLibExt Extension) static
Definition at line 744 of file program_manager.cpp.
References PI_INVALID_OPERATION.
Referenced by loadDeviceLibFallback().
getDeviceLibPrograms()
static std::vector<RT::PiProgram> cl::sycl::detail::getDeviceLibPrograms (const ContextImplPtr Context, const RT::PiDevice & Device, std::map< std::pair< DeviceLibExt, RT::PiDevice >, RT::PiProgram > & CachedLibPrograms, uint32_t DeviceLibReqMask) static
Definition at line 929 of file program_manager.cpp.
References std::get(), getDeviceLibExtensionStr(), isDeviceLibRequired(), and loadDeviceLibFallback().
getDirName()
std::string cl::sycl::detail::getDirName (const char * Path)
getESIMDDeviceInterface()
ESIMDDeviceInterface* cl::sycl::detail::getESIMDDeviceInterface ()
Definition at line 25 of file esimd_emulator_device_interface.cpp.
References cl::sycl::feature_not_supported.
GetFlushBufOffset()
unsigned cl::sycl::detail::GetFlushBufOffset (const GlobalBufAccessorT & GlobalFlushBuf, unsigned WIOffset) inline
Definition at line 92 of file stream.hpp.
Referenced by flushBuffer(), and write().
getFormatStr()
static const char* cl::sycl::detail::getFormatStr (RT::PiDeviceBinaryType Format) static
Definition at line 291 of file program_manager.cpp.
References PI_DEVICE_BINARY_TYPE_LLVMIR_BITCODE, PI_DEVICE_BINARY_TYPE_NATIVE, PI_DEVICE_BINARY_TYPE_NONE, and PI_DEVICE_BINARY_TYPE_SPIRV.
Referenced by cl::sycl::detail::ProgramManager::createPIProgram(), and cl::sycl::detail::ProgramManager::ProgramManager().
getImageElementSize()
uint8_t cl::sycl::detail::getImageElementSize (uint8_t NumChannels, image_channel_type Type)
Definition at line 71 of file image_impl.cpp.
Referenced by cl::sycl::detail::image_impl< Dimensions >::image_impl().
getImageInfo()
template<typename T > static void cl::sycl::detail::getImageInfo (const ContextImplPtr Context, RT::PiMemImageInfo Info, T & Dest, RT::PiMem InteropMemObject) static
Definition at line 256 of file image_impl.cpp.
References cl::sycl::detail::plugin::call(), and piMemImageGetInfo().
Referenced by cl::sycl::detail::image_impl< Dimensions >::image_impl().
getImageNumberChannels()
uint8_t cl::sycl::detail::getImageNumberChannels (image_channel_order Order)
Definition at line 44 of file image_impl.cpp.
Referenced by cl::sycl::detail::image_impl< Dimensions >::image_impl().
getImageOffset() [1/3]
template<typename T > detail::enable_if_t<std::is_integral<T>::value, size_t> cl::sycl::detail::getImageOffset (const T & Coords, const id< 3 > , const uint8_t ElementSize)
Definition at line 83 of file image_accessor_util.hpp.
getImageOffset() [2/3]
template<typename T > detail::enable_if_t<std::is_integral<T>::value, size_t> cl::sycl::detail::getImageOffset (const vec< T, 2 > & Coords, const id< 3 > ImgPitch, const uint8_t ElementSize)
Definition at line 89 of file image_accessor_util.hpp.
getImageOffset() [3/3]
template<typename T > detail::enable_if_t<std::is_integral<T>::value, size_t> cl::sycl::detail::getImageOffset (const vec< T, 4 > & Coords, const id< 3 > ImgPitch, const uint8_t ElementSize)
Definition at line 96 of file image_accessor_util.hpp.
Referenced by imageWriteHostImpl(), and ReadPixelData().
getImplBackend()
template<class T > backend cl::sycl::detail::getImplBackend (const T & Impl)
Definition at line 16 of file backend_impl.hpp.
Referenced by cl::sycl::interop_handle::get_backend(), cl::sycl::platform::get_backend(), cl::sycl::kernel::get_backend(), cl::sycl::event::get_backend(), cl::sycl::device::get_backend(), cl::sycl::context::get_backend(), and cl::sycl::queue::get_backend().
getLinearIndex()
template<int Dims, template< int > class T, template< int > class U> size_t cl::sycl::detail::getLinearIndex (const T< Dims > & Index, const U< Dims > & Range)
Definition at line 330 of file common.hpp.
Referenced by cl::sycl::accessor< DataT, 1, access_mode::read_write, target::host_buffer, access::placeholder::false_t >::operator ConstRefType(), cl::sycl::accessor< DataT, 1, access_mode::read_write, target::host_buffer, access::placeholder::false_t >::operator RefType(), cl::sycl::accessor< unsigned, 1, cl::sycl::access::mode::atomic, cl::sycl::access::target::global_buffer, cl::sycl::access::placeholder::false_t >::operator typename detail::enable_if_t< Dims==0 &&AccessMode==access::mode::atomic, atomic< unsigned, AS > >(), cl::sycl::ext::oneapi::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder >::operator typename detail::enable_if_t< Dims==0, reference >(), cl::sycl::ext::oneapi::atomic_accessor< DataT, Dimensions, DefaultOrder, DefaultScope, AccessTarget, IsPlaceholder >::operator[](), cl::sycl::accessor< DataT, 1, access_mode::read_write, target::host_buffer, access::placeholder::false_t >::operator[](), and cl::sycl::accessor< DataT, Dimensions, AccessMode, access::target::local, IsPlaceholder >::operator[]().
getLoadOrder()
constexpr memory_order cl::sycl::detail::getLoadOrder (memory_order order) inline constexpr
Definition at line 74 of file atomic_ref.hpp.
getMemObjCreationFlags()
static RT::PiMemFlags cl::sycl::detail::getMemObjCreationFlags (void * UserPtr, bool HostPtrReadOnly) static
Definition at line 326 of file memory_manager.cpp.
References PI_MEM_ACCESS_READ_ONLY, PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_COPY, and PI_MEM_FLAGS_HOST_PTR_USE.
Referenced by cl::sycl::detail::MemoryManager::allocateBufferObject(), and cl::sycl::detail::MemoryManager::allocateImageObject().
getNextPowerOfTwo()
constexpr size_t cl::sycl::detail::getNextPowerOfTwo (size_t Var) constexpr
Definition at line 324 of file common.hpp.
References getNextPowerOfTwoHelper().
Referenced by piextUSMSharedAlloc().
getNextPowerOfTwoHelper()
constexpr size_t cl::sycl::detail::getNextPowerOfTwoHelper (size_t Var, size_t Offset) constexpr
Definition at line 317 of file common.hpp.
Referenced by getNextPowerOfTwo().
getOffsetForId()
template<int dimensions> size_t cl::sycl::detail::getOffsetForId (range< dimensions > Range, id< dimensions > Id, id< dimensions > Offset)
Definition at line 310 of file id.hpp.
getOrBuild()
template<typename RetT , typename ExceptionT , typename KeyT , typename AcquireFT , typename GetCacheFT , typename BuildFT > KernelProgramCache::BuildResult<RetT>* cl::sycl::detail::getOrBuild (KernelProgramCache & KPCache, KeyT && CacheKey, AcquireFT && Acquire, GetCacheFT && GetCache, BuildFT && Build)
Try to fetch entity (kernel or program) from cache.
If there is no such entity try to build it. Throw any exception build process may throw. This method eliminates unwanted builds by employing atomic variable with build state and waiting until the entity is built in another thread. If the building thread has failed the awaiting thread will fail either. Exception thrown by build procedure are rethrown.
Template Parameters
RetT type of entity to get
ExceptionT type of exception to throw on awaiting thread if the building thread fails build step.
KeyT key (in cache) to fetch built entity with
AcquireFT type of function which will acquire the locked version of the cache. Accept reference to KernelProgramCache.
GetCacheFT type of function which will fetch proper cache from locked version. Accepts reference to locked version of cache.
BuildFT type of function which will build the entity if it is not in cache. Accepts nothing. Return pointer to built entity.
Returns
a pointer to cached build result, return value must not be nullptr.
Definition at line 163 of file program_manager.cpp.
References BS_Done, BS_Failed, BS_InProgress, cl::sycl::detail::KernelProgramCache::BuildResult< T >::Error, cl::sycl::exception::get_cl_code(), cl::sycl::detail::KernelProgramCache::BuildResult< T >::MBuildResultMutex, cl::sycl::detail::KernelProgramCache::notifyAllBuild(), cl::sycl::detail::KernelProgramCache::BuildResult< T >::Ptr, cl::sycl::detail::KernelProgramCache::BuildResult< T >::State, and cl::sycl::exception::what().
getOrWaitEvents() [1/2]
std::vector<RT::PiEvent> cl::sycl::detail::getOrWaitEvents (std::vector< cl::sycl::event > DepEvents, ContextImplPtr Context)
Definition at line 21 of file helpers.cpp.
References getSyclObjImpl().
getOrWaitEvents() [2/2]
std::vector<RT::PiEvent> cl::sycl::detail::getOrWaitEvents (std::vector< cl::sycl::event > DepEvents, std::shared_ptr< cl::sycl::detail::context_impl > Context)
Referenced by cl::sycl::detail::queue_impl::mem_advise(), cl::sycl::detail::queue_impl::memcpy(), and cl::sycl::detail::queue_impl::memset().
getPiEvents()
static std::vector<RT::PiEvent> cl::sycl::detail::getPiEvents (const std::vector< EventImplPtr > & EventImpls) static
Definition at line 173 of file commands.cpp.
Referenced by cl::sycl::detail::Command::waitForEvents().
getPixelCoordLinearFiltMode()
cl_int8 cl::sycl::detail::getPixelCoordLinearFiltMode (cl_float4 Coorduvw, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, cl_float4 & Retabc)
Definition at line 93 of file image_accessor_util.cpp.
References cl::sycl::clamp(), clamp(), cl::sycl::fabs(), cl::sycl::floor(), cl::sycl::rint(), and cl::sycl::select().
Referenced by imageReadSamplerHostImpl().
getPixelCoordNearestFiltMode()
cl_int4 cl::sycl::detail::getPixelCoordNearestFiltMode (cl_float4 Coorduvw, const addressing_mode SmplAddrMode, const range< 3 > ImgRange)
Definition at line 18 of file image_accessor_util.cpp.
References cl::sycl::clamp(), clamp(), cl::sycl::fabs(), cl::sycl::floor(), cl::sycl::rint(), and cl::sycl::select().
Referenced by imageReadSamplerHostImpl().
getPlugin()
static const plugin& cl::sycl::detail::getPlugin (backend Backend) static
Definition at line 32 of file backend.cpp.
References PI_INVALID_OPERATION.
Referenced by context_impl::get_info< info::context::atomic_memory_order_capabilities >(), context_impl::get_info< info::context::atomic_memory_scope_capabilities >(), context_impl::get_info< info::context::reference_count >(), event_impl::get_info< info::event::command_execution_status >(), event_impl::get_info< info::event::reference_count >(), event_impl::get_profiling_info< info::event_profiling::command_end >(), event_impl::get_profiling_info< info::event_profiling::command_start >(), event_impl::get_profiling_info< info::event_profiling::command_submit >(), make_context(), make_device(), make_event(), make_kernel(), make_kernel_bundle(), make_platform(), make_queue(), and program_impl::get_info< info::program::reference_count >().
getPluginOpaqueData()
template<cl::sycl::backend BE> void * cl::sycl::detail::getPluginOpaqueData (void * opaquedata_arg)
Definition at line 65 of file pi.cpp.
References cl::sycl::detail::plugin::call(), and piextPluginGetOpaqueData().
getPluginOpaqueData< cl::sycl::backend::ext_intel_esimd_emulator >()
template void* cl::sycl::detail::getPluginOpaqueData< cl::sycl::backend::ext_intel_esimd_emulator > (void *)
getRawSyclObjImpl()
template<class T > detail::add_pointer_t<typename decltype(T::impl)::element_type> cl::sycl::detail::getRawSyclObjImpl (const T & SyclObject)
Definition at line 207 of file common.hpp.
Referenced by cl::sycl::detail::ProgramManager::build(), cl::sycl::detail::ProgramManager::createPIProgram(), cl::sycl::detail::ProgramManager::getBuiltPIProgram(), and cl::sycl::detail::ProgramManager::getDeviceImage().
getSPIRVMemorySemanticsMask() [1/2]
constexpr uint32_t cl::sycl::detail::getSPIRVMemorySemanticsMask (const access::fence_space AccessSpace, const __spv::MemorySemanticsMask LocalScopeMask = __spv::MemorySemanticsMask::WorkgroupMemory) inline constexpr
Definition at line 205 of file helpers.hpp.
References __spv::MemorySemanticsMask::CrossWorkgroupMemory, and __spv::MemorySemanticsMask::SequentiallyConsistent.
getSPIRVMemorySemanticsMask() [2/2]
constexpr __spv::MemorySemanticsMask::Flag cl::sycl::detail::getSPIRVMemorySemanticsMask (memory_order) inline constexpr
Definition at line 200 of file helpers.hpp.
References __spv::MemorySemanticsMask::None.
Referenced by cl::sycl::__SYCL2020_DEPRECATED(), cl::sycl::nd_item< dimensions >::barrier(), and cl::sycl::group< 1 >::mem_fence().
getStdMemoryOrder() [1/2]
static std::memory_order cl::sycl::detail::getStdMemoryOrder (__spv::MemorySemanticsMask::Flag) inline static
Definition at line 81 of file atomic.hpp.
Referenced by __spirv_AtomicAnd(), __spirv_AtomicExchange(), __spirv_AtomicIAdd(), __spirv_AtomicISub(), __spirv_AtomicLoad(), __spirv_AtomicMax(), __spirv_AtomicMin(), __spirv_AtomicOr(), __spirv_AtomicStore(), __spirv_AtomicXor(), cl::sycl::__SYCL2020_DEPRECATED(), cl::sycl::atomic_fence(), cl::sycl::ext::oneapi::atomic_fence(), cl::sycl::detail::atomic_ref_base< uintptr_t, DefaultOrder, DefaultScope, AddressSpace >::compare_exchange_strong(), cl::sycl::ext::oneapi::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::compare_exchange_strong(), cl::sycl::detail::atomic_ref_base< uintptr_t, DefaultOrder, DefaultScope, AddressSpace >::compare_exchange_weak(), cl::sycl::ext::oneapi::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::compare_exchange_weak(), cl::sycl::ext::oneapi::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::exchange(), cl::sycl::detail::atomic_ref_base< uintptr_t, DefaultOrder, DefaultScope, AddressSpace >::exchange(), cl::sycl::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_add(), cl::sycl::ext::oneapi::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_add(), cl::sycl::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_and(), cl::sycl::ext::oneapi::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_and(), cl::sycl::ext::oneapi::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_or(), cl::sycl::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_or(), cl::sycl::ext::oneapi::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_sub(), cl::sycl::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_sub(), cl::sycl::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_xor(), cl::sycl::ext::oneapi::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_xor(), cl::sycl::detail::atomic_ref_base< uintptr_t, DefaultOrder, DefaultScope, AddressSpace >::load(), cl::sycl::ext::oneapi::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::load(), cl::sycl::ext::oneapi::detail::atomic_ref_base< T, DefaultOrder, DefaultScope, AddressSpace >::store(), and cl::sycl::detail::atomic_ref_base< uintptr_t, DefaultOrder, DefaultScope, AddressSpace >::store().
getStdMemoryOrder() [2/2]
static constexpr std::memory_order cl::sycl::detail::getStdMemoryOrder (sycl::memory_order order) static constexpr
Definition at line 83 of file memory_enums.hpp.
getStrOrNullptr()
constexpr const char* cl::sycl::detail::getStrOrNullptr (const char * Str) constexpr
Definition at line 60 of file config.hpp.
getSyclBeMap()
const std::array< std::pair< std::string, backend >, 7 > & cl::sycl::detail::getSyclBeMap ()
Definition at line 172 of file config.cpp.
References cl::sycl::all().
Referenced by applyAllowList(), cl::sycl::detail::device_filter::device_filter(), and parseAllowList().
getSyclDeviceTypeMap()
const std::array< std::pair< std::string, info::device_type >, 5 > & cl::sycl::detail::getSyclDeviceTypeMap ()
Definition at line 161 of file config.cpp.
References cl::sycl::all().
Referenced by applyAllowList(), cl::sycl::detail::device_filter::device_filter(), and parseAllowList().
getSyclObjImpl()
template<class Obj > decltype(Obj::impl) cl::sycl::detail::getSyclObjImpl (const Obj & SyclObject)
Definition at line 198 of file common.hpp.
Referenced by cl::sycl::__SYCL_DEPRECATED(), cl::sycl::detail::kernel_bundle_impl::add_kernel(), cl::sycl::detail::usm::alignedAllocHost(), cl::sycl::detail::ProgramManager::bringSYCLDeviceImagesToState(), cl::sycl::detail::ProgramManager::build(), cl::sycl::detail::program_impl::build_with_kernel_name(), compatibleWithDevice(), cl::sycl::detail::ProgramManager::compile(), cl::sycl::context::context(), cl::sycl::detail::context_impl::context_impl(), cl::sycl::detail::pi::contextSetExtendedDeleter(), cl::sycl::handler::copy(), createBinaryProgram(), cl::sycl::detail::ProgramManager::createPIProgram(), cl::sycl::handler::depends_on(), cl::sycl::detail::EmptyCommand::emitInstrumentationData(), cl::sycl::detail::ReleaseCommand::emitInstrumentationData(), cl::sycl::detail::AllocaCommandBase::emitInstrumentationData(), cl::sycl::detail::MapMemObject::emitInstrumentationData(), cl::sycl::detail::UnMapMemObject::emitInstrumentationData(), cl::sycl::detail::MemCpyCommand::emitInstrumentationData(), cl::sycl::detail::MemCpyCommandHost::emitInstrumentationData(), cl::sycl::detail::ExecCGCommand::emitInstrumentationData(), cl::sycl::detail::UpdateHostRequirementCommand::emitInstrumentationData(), enqueueImpKernel(), cl::sycl::platform::ext_oneapi_get_default_context(), cl::sycl::handler::fill(), cl::sycl::detail::program_impl::flush_spec_constants(), cl::sycl::detail::usm::free(), cl::sycl::detail::kernel_impl::get_info(), cl::sycl::detail::kernel_bundle_impl::get_kernel(), cl::sycl::detail::kernel_bundle_impl::get_kernel_ids(), cl::sycl::interop_handle::get_native_mem(), cl::sycl::get_pointer_device(), cl::sycl::get_pointer_type(), cl::sycl::detail::device_image_impl::get_spec_const_buffer_ref(), cl::sycl::detail::kernel_bundle_impl::get_specialization_constant_raw_value(), cl::sycl::detail::ProgramManager::getBuiltPIProgram(), cl::sycl::detail::queue_impl::getDefaultOrNew(), getDeviceFunctionPointerImpl(), cl::sycl::detail::event_impl::getNative(), cl::sycl::detail::device_image_impl::getNative(), cl::sycl::detail::ProgramManager::getOrCreateKernel(), cl::sycl::detail::ProgramManager::getOrCreatePIProgram(), cl::sycl::detail::sampler_impl::getOrCreateSampler(), cl::sycl::detail::Scheduler::GraphBuilder::getOrInsertMemObjRecord(), getOrWaitEvents(), has_kernel_bundle_impl(), cl::sycl::detail::context_impl::hasDevice(), cl::sycl::detail::image_impl< Dimensions >::image_impl(), initStream(), IsBannedPlatform(), isDeviceBinaryTypeSupported(), cl::sycl::isDeviceOfPreferredSyclBe(), cl::sycl::join(), cl::sycl::detail::kernel_bundle_impl::kernel_bundle_impl(), cl::sycl::detail::ProgramManager::link(), cl::sycl::ext::oneapi::level_zero::make_context(), cl::sycl::ext::oneapi::level_zero::make_device(), make_event(), make_kernel(), make_kernel_bundle(), cl::sycl::opencl::make_program(), cl::sycl::ext::oneapi::level_zero::make_program(), cl::sycl::opencl::make_queue(), cl::sycl::ext::oneapi::level_zero::make_queue(), make_queue(), cl::sycl::ext::oneapi::detail::filter_selector_impl::operator()(), cl::sycl::detail::LessByHash< T >::operator()(), std::hash< cl::sycl::sampler >::operator()(), std::hash< cl::sycl::platform >::operator()(), std::hash< cl::sycl::event >::operator()(), std::hash< cl::sycl::kernel >::operator()(), std::hash< cl::sycl::device >::operator()(), std::hash< cl::sycl::context >::operator()(), std::hash< cl::sycl::image< Dimensions, AllocatorT > >::operator()(), std::hash< cl::sycl::buffer< T, dimensions, AllocatorT > >::operator()(), std::hash< cl::sycl::kernel_id >::operator()(), std::hash< cl::sycl::device_image< State > >::operator()(), std::hash< cl::sycl::kernel_bundle< State > >::operator()(), std::hash< cl::sycl::stream >::operator()(), std::hash< cl::sycl::queue >::operator()(), std::hash< cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder > >::operator()(), cl::sycl::handler::parallel_for(), cl::sycl::handler::parallel_for_work_group(), prepareUSMEvent(), cl::sycl::detail::PersistentDeviceCodeCache::putItemToDisc(), cl::sycl::queue::queue(), cl::sycl::detail::sampler_impl::sampler_impl(), cl::sycl::detail::Scheduler::Scheduler(), cl::sycl::detail::kernel_bundle_impl::set_specialization_constant_raw_value(), SetKernelParamsAndLaunch(), cl::sycl::handler::single_task(), cl::sycl::stream::stream(), cl::sycl::handler::update_host(), cl::sycl::handler::use_kernel_bundle(), waitEvents(), cl::sycl::detail::device_image_impl::~device_image_impl(), and cl::sycl::detail::sampler_impl::~sampler_impl().
getTimestamp()
static uint64_t cl::sycl::detail::getTimestamp () static
Definition at line 334 of file event_impl.cpp.
Referenced by cl::sycl::detail::HostProfilingInfo::end(), and cl::sycl::detail::HostProfilingInfo::start().
getUnversionedCGType()
constexpr unsigned char cl::sycl::detail::getUnversionedCGType (unsigned int Type) constexpr
Definition at line 132 of file cg.hpp.
References ShiftBitsForVersion.
Referenced by cl::sycl::detail::CG::getType().
getVersionedCGType()
constexpr unsigned int cl::sycl::detail::getVersionedCGType (unsigned int Type, unsigned char Version) constexpr
Definition at line 126 of file cg.hpp.
References ShiftBitsForVersion.
half2Float()
__SYCL_CONSTEXPR_HALF float cl::sycl::detail::half2Float (const uint16_t & Val) inline
Definition at line 94 of file half_type.hpp.
References __builtin_expect.
Referenced by cl::sycl::detail::host_half_impl::half::operator float(), and cl::sycl::detail::host_half_impl::half_v2::operator float().
handleVisitedNodes()
static void cl::sycl::detail::handleVisitedNodes (std::vector< Command * > & Visited) static
Definition at line 128 of file graph_builder.cpp.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::cleanupFinishedCommands().
has_kernel_bundle_impl() [1/2]
bool cl::sycl::detail::has_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, bundle_state State)
Definition at line 159 of file kernel_bundle.cpp.
References checkAllDevicesAreInContext(), checkAllDevicesHaveAspect(), and cl::sycl::make_error_code().
has_kernel_bundle_impl() [2/2]
bool cl::sycl::detail::has_kernel_bundle_impl (const context & Ctx, const std::vector< device > & Devs, const std::vector< kernel_id > & kernelIds, bundle_state State)
Definition at line 185 of file kernel_bundle.cpp.
References all_of(), checkAllDevicesAreInContext(), getSyclObjImpl(), and cl::sycl::make_error_code().
Referenced by cl::sycl::has_kernel_bundle().
identity_for_ga_op() [1/2]
template<typename T , class BinaryOperation > constexpr detail::enable_if_t< (is_complex<T>::value && is_plus<T, BinaryOperation>::value), T> cl::sycl::detail::identity_for_ga_op () constexpr
Definition at line 137 of file group_algorithm.hpp.
identity_for_ga_op() [2/2]
template<typename T , class BinaryOperation > constexpr detail::enable_if_t<!is_complex<T>::value, T> cl::sycl::detail::identity_for_ga_op () constexpr
Definition at line 142 of file group_algorithm.hpp.
imageReadSamplerHostImpl()
template<typename CoordT , typename DataT > DataT cl::sycl::detail::imageReadSamplerHostImpl (const CoordT & Coords, const sampler & Smpl, range< 3 > ImgRange, id< 3 > ImgPitch, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void * BasePtr, uint8_t ElementSize)
Definition at line 1018 of file image_accessor_util.hpp.
References clamp(), convertToFloat4(), cl::sycl::sampler::get_addressing_mode(), cl::sycl::sampler::get_coordinate_normalization_mode(), cl::sycl::sampler::get_filtering_mode(), getPixelCoordLinearFiltMode(), getPixelCoordNearestFiltMode(), PI_INVALID_OPERATION, and UnnormalizeCoordinates().
imageWriteHostImpl()
template<typename CoordT , typename WriteDataT > void cl::sycl::detail::imageWriteHostImpl (const CoordT & Coords, const WriteDataT & Color, id< 3 > ImgPitch, uint8_t ElementSize, image_channel_type ImgChannelType, image_channel_order ImgChannelOrder, void * BasePtr)
Definition at line 698 of file image_accessor_util.hpp.
References getImageOffset(), and writePixel().
Referenced by cl::sycl::detail::image_accessor< DataT, Dimensions, AccessMode, access::target::host_image, IsPlaceholder >::write().
initStream()
void cl::sycl::detail::initStream (StreamImplPtr Stream, QueueImplPtr Queue)
Definition at line 19 of file scheduler_helpers.cpp.
References getSyclObjImpl().
Referenced by cl::sycl::detail::Scheduler::addCG().
initValue()
static void cl::sycl::detail::initValue (const char * Key, const char * Value) static
Definition at line 36 of file config.cpp.
Referenced by readConfig().
insertMapUnmapForLinkedCmds()
static Command* cl::sycl::detail::insertMapUnmapForLinkedCmds (AllocaCommandBase * AllocaCmdSrc, AllocaCommandBase * AllocaCmdDst, access::mode MapMode) static
Definition at line 295 of file graph_builder.cpp.
References cl::sycl::detail::Command::getQueue(), cl::sycl::detail::AllocaCommandBase::getRequirement(), cl::sycl::detail::AllocaCommandBase::MIsActive, cl::sycl::detail::AllocaCommandBase::MLinkedAllocaCmd, and cl::sycl::detail::AllocaCommandBase::MMemAllocation.
integralToBase()
template<typename T > detail::enable_if_t<std::is_integral<T>::value, unsigned> cl::sycl::detail::integralToBase (T Val, int Base, char * Digits) inline
Definition at line 160 of file stream.hpp.
References digitToChar().
Referenced by ScalarToStr().
is_sycl_partition_property()
static bool cl::sycl::detail::is_sycl_partition_property (info::partition_property PP) static
Definition at line 323 of file device_info.hpp.
Referenced by cl::sycl::detail::get_device_info< std::vector< info::partition_property >, info::device::partition_properties >::get().
isAccessModeAllowed()
static bool cl::sycl::detail::isAccessModeAllowed (access::mode Required, access::mode Current) static
Checks if the required access mode is allowed under the current one.
Definition at line 56 of file graph_builder.cpp.
References write().
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::addCG(), and cl::sycl::detail::Scheduler::GraphBuilder::addHostAccessor().
IsBannedPlatform()
static bool cl::sycl::detail::IsBannedPlatform (platform Platform) static
Definition at line 69 of file platform_impl.cpp.
References cl::sycl::platform::get_info(), getSyclObjImpl(), cl::sycl::detail::pi::PI_TRACE_ALL, and cl::sycl::detail::pi::trace().
Referenced by cl::sycl::detail::platform_impl::get_platforms().
isDeviceBinaryTypeSupported()
static bool cl::sycl::detail::isDeviceBinaryTypeSupported (const context & C, RT::PiDeviceBinaryType Format) static
Definition at line 247 of file program_manager.cpp.
References cl::sycl::context::get_devices(), cl::sycl::platform::get_info(), cl::sycl::context::get_platform(), getSyclObjImpl(), and PI_DEVICE_BINARY_TYPE_SPIRV.
Referenced by cl::sycl::detail::ProgramManager::createPIProgram().
isDeviceLibRequired()
static bool cl::sycl::detail::isDeviceLibRequired (DeviceLibExt Ext, uint32_t DeviceLibReqMask) static
Definition at line 922 of file program_manager.cpp.
Referenced by getDeviceLibPrograms().
isHostAccessorCmd()
static bool cl::sycl::detail::isHostAccessorCmd (Command * Cmd) inline static
Definition at line 33 of file leaves_collection.cpp.
References cl::sycl::detail::Command::getType(), and cl::sycl::detail::Command::MBlockReason.
Referenced by cl::sycl::detail::LeavesCollection::push_back(), and cl::sycl::detail::LeavesCollection::remove().
isInteropHostTask()
static bool cl::sycl::detail::isInteropHostTask (const std::unique_ptr< ExecCGCommand > & Cmd) static
Definition at line 885 of file graph_builder.cpp.
References cl::sycl::detail::CGHostTask::MHostTask.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::addCG().
isKernelLambdaCallableWithKernelHandlerImpl()
template<typename KernelType , typename LambdaArgType , typename std::enable_if_t< std::is_same< LambdaArgType, void >::value > * = nullptr> constexpr bool cl::sycl::detail::isKernelLambdaCallableWithKernelHandlerImpl () constexpr
Definition at line 160 of file cg_types.hpp.
isOutOfRange()
bool cl::sycl::detail::isOutOfRange (const cl_int4 PixelCoord, const addressing_mode SmplAddrMode, const range< 3 > ImgRange)
Definition at line 156 of file image_accessor_util.cpp.
References clamp().
Referenced by getColor().
IsSuitableSubReq()
static bool cl::sycl::detail::IsSuitableSubReq (const Requirement * Req) static
Checks if current requirement is requirement for sub buffer.
Definition at line 51 of file graph_builder.cpp.
References cl::sycl::detail::AccessorImplHost::MIsSubBuffer.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::findAllocaForReq().
isTargetHostAccess()
constexpr bool cl::sycl::detail::isTargetHostAccess (access::target T) constexpr
Definition at line 102 of file access.hpp.
ItemToStr()
template<int Dimensions> unsigned cl::sycl::detail::ItemToStr (char * Buf, const item< Dimensions, false > & Item) inline
Definition at line 613 of file stream.hpp.
References append(), ArrayToStr(), cl::sycl::item< dimensions, with_offset >::get_id(), and cl::sycl::item< dimensions, with_offset >::get_range().
Referenced by writeHItem().
join_impl() [1/2]
std::shared_ptr< detail::kernel_bundle_impl > cl::sycl::detail::join_impl (const std::vector< detail::KernelBundleImplPtr > & Bundles)
Definition at line 148 of file kernel_bundle.cpp.
join_impl() [2/2]
std::shared_ptr< detail::kernel_bundle_impl > cl::sycl::detail::join_impl (const std::vector< detail::KernelBundleImplPtr > & Bundles, bundle_state State)
Definition at line 154 of file kernel_bundle.cpp.
Referenced by cl::sycl::join().
kernel_impl::get_info< info::kernel::context >()
template<> context cl::sycl::detail::kernel_impl::get_info< info::kernel::context > () const inline
Definition at line 232 of file kernel_impl.hpp.
linear_id_to_id() [1/4]
template<> id<1> cl::sycl::detail::linear_id_to_id (range< 1 > , size_t linear_id) inline
Definition at line 32 of file group_algorithm.hpp.
linear_id_to_id() [2/4]
template<> id<2> cl::sycl::detail::linear_id_to_id (range< 2 > r, size_t linear_id) inline
Definition at line 35 of file group_algorithm.hpp.
References cl::sycl::r.
linear_id_to_id() [3/4]
template<> id<3> cl::sycl::detail::linear_id_to_id (range< 3 > r, size_t linear_id) inline
Definition at line 41 of file group_algorithm.hpp.
References cl::sycl::r.
Referenced by cl::sycl::group_broadcast().
linear_id_to_id() [4/4]
template<int Dimensions> id<Dimensions> cl::sycl::detail::linear_id_to_id (range< Dimensions > , size_t linear_id)
link_impl()
std::shared_ptr< detail::kernel_bundle_impl > cl::sycl::detail::link_impl (const std::vector< kernel_bundle< bundle_state::object >> & ObjectBundles, const std::vector< device > & Devs, const property_list & PropList)
Definition at line 245 of file kernel_bundle.cpp.
loadDeviceLib()
static bool cl::sycl::detail::loadDeviceLib (const ContextImplPtr Context, const char * Name, RT::PiProgram & Prog) static
Definition at line 723 of file program_manager.cpp.
References createSpirvProgram().
Referenced by loadDeviceLibFallback().
loadDeviceLibFallback()
static RT::PiProgram cl::sycl::detail::loadDeviceLibFallback (const ContextImplPtr Context, DeviceLibExt Extension, const RT::PiDevice & Device, std::map< std::pair< DeviceLibExt, RT::PiDevice >, RT::PiProgram > & CachedLibPrograms) static
Definition at line 782 of file program_manager.cpp.
References cl::sycl::detail::plugin::call_nocheck(), getDeviceLibFilename(), loadDeviceLib(), PI_INVALID_VALUE, PI_SUCCESS, and piProgramCompile().
Referenced by getDeviceLibPrograms().
make_buffer_helper()
template<typename T , int Dimensions, typename AllocatorT > buffer<T, Dimensions, AllocatorT, void> cl::sycl::detail::make_buffer_helper (pi_native_handle Handle, const context & Ctx, event Evt)
Definition at line 29 of file buffer.hpp.
make_context()
context cl::sycl::detail::make_context (pi_native_handle NativeHandle, const async_handler & Handler, backend Backend)
Definition at line 67 of file backend.cpp.
References getPlugin(), and piextContextCreateWithNativeHandle().
make_device()
device cl::sycl::detail::make_device (pi_native_handle NativeHandle, backend Backend)
Definition at line 55 of file backend.cpp.
References getPlugin(), and piextDeviceCreateWithNativeHandle().
make_event() [1/2]
event cl::sycl::detail::make_event (pi_native_handle NativeHandle, const context & TargetContext, backend Backend)
Definition at line 100 of file backend.cpp.
Referenced by cl::sycl::ext::oneapi::level_zero::make_event().
make_event() [2/2]
event cl::sycl::detail::make_event (pi_native_handle NativeHandle, const context & TargetContext, bool KeepOwnership, backend Backend)
Definition at line 105 of file backend.cpp.
References getPlugin(), getSyclObjImpl(), and piextEventCreateWithNativeHandle().
make_kernel() [1/2]
kernel cl::sycl::detail::make_kernel (const context & TargetContext, const kernel_bundle< bundle_state::executable > & KernelBundle, pi_native_handle NativeKernelHandle, bool KeepOwnership, backend Backend)
Definition at line 207 of file backend.cpp.
References cl::sycl::kernel_bundle< State >::begin(), getPlugin(), getSyclObjImpl(), PI_INVALID_PROGRAM, piextKernelCreateWithNativeHandle(), and piKernelRetain().
make_kernel() [2/2]
kernel cl::sycl::detail::make_kernel (pi_native_handle NativeHandle, const context & TargetContext, backend Backend)
Definition at line 249 of file backend.cpp.
Referenced by cl::sycl::make_kernel< backend::ext_oneapi_level_zero >().
make_kernel_bundle() [1/2]
std::shared_ptr< detail::kernel_bundle_impl > cl::sycl::detail::make_kernel_bundle (pi_native_handle NativeHandle, const context & TargetContext, bool KeepOwnership, bundle_state State, backend Backend)
Definition at line 120 of file backend.cpp.
References cl::sycl::build(), getPlugin(), getSyclObjImpl(), PI_INVALID_VALUE, PI_PROGRAM_BINARY_TYPE_COMPILED_OBJECT, PI_PROGRAM_BINARY_TYPE_EXECUTABLE, PI_PROGRAM_BINARY_TYPE_LIBRARY, PI_PROGRAM_BINARY_TYPE_NONE, PI_PROGRAM_BUILD_INFO_BINARY_TYPE, PI_PROGRAM_INFO_DEVICES, PI_PROGRAM_INFO_NUM_DEVICES, piextProgramCreateWithNativeHandle(), piProgramBuild(), piProgramCompile(), piProgramGetBuildInfo(), piProgramGetInfo(), and piProgramLink().
make_kernel_bundle() [2/2]
std::shared_ptr< detail::kernel_bundle_impl > cl::sycl::detail::make_kernel_bundle (pi_native_handle NativeHandle, const context & TargetContext, bundle_state State, backend Backend)
Definition at line 202 of file backend.cpp.
Referenced by cl::sycl::make_kernel_bundle< backend::ext_oneapi_level_zero, bundle_state::executable >().
make_platform()
platform cl::sycl::detail::make_platform (pi_native_handle NativeHandle, backend Backend)
Definition at line 43 of file backend.cpp.
References getPlugin(), and piextPlatformCreateWithNativeHandle().
make_queue() [1/2]
queue cl::sycl::detail::make_queue (pi_native_handle NativeHandle, const context & TargetContext, bool KeepOwnership, const async_handler & Handler, backend Backend)
Definition at line 86 of file backend.cpp.
References getPlugin(), getSyclObjImpl(), and piextQueueCreateWithNativeHandle().
make_queue() [2/2]
queue cl::sycl::detail::make_queue (pi_native_handle NativeHandle, const context & TargetContext, const async_handler & Handler, backend Backend)
Definition at line 80 of file backend.cpp.
References cl::sycl::opencl::make_queue().
make_tuple()
template<typename... Ts> constexpr tuple<Ts...> cl::sycl::detail::make_tuple (Ts... Args) constexpr
Definition at line 36 of file tuple.hpp.
Referenced by cl::sycl::detail::ProgramManager::getOrCreateKernel(), cl::sycl::ext::oneapi::detail::initReduLocalAccs(), cl::sycl::ext::oneapi::detail::makeReduTupleT(), cl::sycl::ext::oneapi::detail::reduceReduLocalAccs(), _pi_program::set_metadata(), cl::sycl::detail::KernelProgramCache::tryToGetKernelFast(), and cl::sycl::ext::oneapi::detail::writeReduSumsToOutAccs().
markNodeAsVisited()
static bool cl::sycl::detail::markNodeAsVisited (Command * Cmd, std::vector< Command * > & Visited) static
Definition at line 114 of file graph_builder.cpp.
References cl::sycl::detail::Command::MMarks, and cl::sycl::detail::Command::Marks::MVisited.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::cleanupCommandsForRecord(), cl::sycl::detail::Scheduler::GraphBuilder::cleanupFinishedCommands(), and printDotRecursive().
match_types()
bool cl::sycl::detail::match_types (const info::device_type & l, const info::device_type & r)
Definition at line 20 of file force_device.cpp.
References cl::sycl::all(), and cl::sycl::r.
Referenced by cl::sycl::device::get_devices().
max_v()
template<typename T > static constexpr T cl::sycl::detail::max_v () static constexpr
Definition at line 595 of file generic_type_traits.hpp.
References max().
member_ptr_helper()
template<typename RetType , typename Func , typename Arg > static Arg cl::sycl::detail::member_ptr_helper (RetType(Func::*)(Arg) const) static
memBufferCreateHelper()
void cl::sycl::detail::memBufferCreateHelper (const plugin & Plugin, pi_context Ctx, pi_mem_flags Flags, size_t Size, void * HostPtr, pi_mem * RetMem, const pi_mem_properties * Props = nullptr)
Definition at line 127 of file memory_manager.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::plugin::call_nocheck(), emitMemAllocBeginTrace(), emitMemAllocEndTrace(), piextMemGetNativeHandle(), and piMemBufferCreate().
Referenced by cl::sycl::detail::MemoryManager::allocateBufferObject(), and cl::sycl::detail::device_image_impl::get_spec_const_buffer_ref().
memBufferMapHelper()
void cl::sycl::detail::memBufferMapHelper (const plugin & Plugin, pi_queue command_queue, pi_mem buffer, pi_bool blocking_map, pi_map_flags map_flags, size_t offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event, void ** ret_map)
Definition at line 182 of file memory_manager.cpp.
References cl::sycl::detail::plugin::call(), emitMemAllocBeginTrace(), emitMemAllocEndTrace(), and piEnqueueMemBufferMap().
Referenced by cl::sycl::detail::MemoryManager::map().
memcpy() [1/2]
void cl::sycl::detail::memcpy (void * Dst, const void * Src, size_t Size) inline
Definition at line 38 of file helpers.hpp.
memcpy() [2/2]
void cl::sycl::detail::memcpy (void * Dst, const void * Src, std::size_t Size) inline
Referenced by _pi_kernel::arguments::add_arg(), cl::sycl::detail::MemoryManager::allocateHostMemory(), cl::sycl::bit_cast(), cl::sycl::queue::copy(), cl::sycl::handler::copy(), cl::sycl::detail::MemoryManager::copy_usm(), copyH2H(), cl::sycl::exception::exception(), _pi_device::get_max_work_item_sizes(), cl::sycl::detail::device_image_impl::get_specialization_constant_raw_value(), cl::sycl::detail::SYCLMemObjT::handleHostData(), piDeviceGetInfo(), piEnqueueMemBufferMap(), piEnqueueMemBufferRead(), piEnqueueMemImageRead(), piEnqueueMemUnmap(), piMemBufferCreate(), piProgramGetInfo(), _pi_device::save_max_work_item_sizes(), _pi_kernel::arguments::set_implicit_offset(), and cl::sycl::detail::device_image_impl::set_specialization_constant_raw_value().
memReleaseHelper()
void cl::sycl::detail::memReleaseHelper (const plugin & Plugin, pi_mem Mem)
Definition at line 155 of file memory_manager.cpp.
References cl::sycl::detail::plugin::call(), emitMemReleaseBeginTrace(), emitMemReleaseEndTrace(), piextMemGetNativeHandle(), and piMemRelease().
Referenced by cl::sycl::detail::MemoryManager::releaseMemObj(), and cl::sycl::detail::device_image_impl::~device_image_impl().
memUnmapHelper()
void cl::sycl::detail::memUnmapHelper (const plugin & Plugin, pi_queue command_queue, pi_mem memobj, void * mapped_ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 206 of file memory_manager.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::plugin::call_nocheck(), emitMemReleaseBeginTrace(), emitMemReleaseEndTrace(), piEnqueueMemUnmap(), and piEventsWait().
Referenced by cl::sycl::detail::MemoryManager::unmap().
min_v()
template<typename T > static constexpr T cl::sycl::detail::min_v () static constexpr
Definition at line 599 of file generic_type_traits.hpp.
References min().
modeNeedsOldData()
constexpr bool cl::sycl::detail::modeNeedsOldData (access::mode m) constexpr
Definition at line 106 of file access.hpp.
References write().
modeWritesNewData()
constexpr bool cl::sycl::detail::modeWritesNewData (access::mode m) constexpr
Definition at line 111 of file access.hpp.
msbIsSet()
template<typename T > constexpr bool cl::sycl::detail::msbIsSet (const T x) inline constexpr
Definition at line 500 of file generic_type_traits.hpp.
References msbMask().
Referenced by cl::sycl::all(), cl::sycl::any(), cl::sycl::detail::Assigner< Num >::init(), and cl::sycl::detail::Assigner< 0 >::init().
msbMask()
template<typename T > constexpr T cl::sycl::detail::msbMask (T) inline constexpr
Definition at line 495 of file generic_type_traits.hpp.
Referenced by msbIsSet().
operator<<() [1/3]
std::ostream& cl::sycl::detail::operator<< (std::ostream & Out, const device_filter & Filter) inline
Definition at line 54 of file device_filter.hpp.
References cl::sycl::all(), cl::sycl::detail::device_filter::Backend, cl::sycl::detail::device_filter::DeviceNum, cl::sycl::detail::device_filter::DeviceType, and cl::sycl::detail::device_filter::HasDeviceNum.
operator<<() [2/3]
std::ostream& cl::sycl::detail::operator<< (std::ostream & Out, const device_filter_list & List) inline
Definition at line 76 of file device_filter.hpp.
operator<<() [3/3]
std::ostream & cl::sycl::detail::operator<< (std::ostream & Out, const spec_constant_impl & V)
Definition at line 39 of file spec_constant_impl.cpp.
References cl::sycl::detail::spec_constant_impl::getSize(), cl::sycl::detail::spec_constant_impl::getValuePtr(), and cl::sycl::detail::spec_constant_impl::isSet().
packCallArguments()
template<PiApiKind Kind, typename... ArgsT> auto cl::sycl::detail::packCallArguments (ArgsT &&... Args)
Definition at line 73 of file plugin.hpp.
References totalSize().
parseAllowList()
AllowListParsedT cl::sycl::detail::parseAllowList (const std::string & AllowListRaw)
Definition at line 53 of file allowlist.cpp.
References BackendNameKeyName, DeviceNameKeyName, DeviceTypeKeyName, DeviceVendorIdKeyName, DriverVersionKeyName, getSyclBeMap(), getSyclDeviceTypeMap(), PI_INVALID_VALUE, PlatformNameKeyName, PlatformVersionKeyName, and SupportedAllowListKeyNames.
Referenced by applyAllowList().
parsePersistentCacheConfig()
static bool cl::sycl::detail::parsePersistentCacheConfig () static
Definition at line 349 of file persistent_device_code_cache.cpp.
References cl::sycl::detail::SYCLConfig< Config >::get(), cl::sycl::detail::SYCLConfig< Config >::getName(), PI_INVALID_OPERATION, and cl::sycl::detail::PersistentDeviceCodeCache::trace().
prepareUSMEvent()
static event cl::sycl::detail::prepareUSMEvent (const std::shared_ptr< detail::queue_impl > & QueueImpl, RT::PiEvent NativeEvent) static
Definition at line 46 of file queue_impl.cpp.
References getSyclObjImpl().
Referenced by cl::sycl::detail::queue_impl::mem_advise(), cl::sycl::detail::queue_impl::memcpy(), and cl::sycl::detail::queue_impl::memset().
prepTermPositions()
void cl::sycl::detail::prepTermPositions (TermPositions & pos, int Dimensions, detail::SYCLMemObjI::MemObjType Type)
Definition at line 460 of file memory_manager.cpp.
References cl::sycl::detail::TermPositions::XTerm, cl::sycl::detail::TermPositions::YTerm, and cl::sycl::detail::TermPositions::ZTerm.
Referenced by copyD2D(), copyD2H(), and copyH2D().
printDotRecursive()
static void cl::sycl::detail::printDotRecursive (std::fstream & Stream, std::vector< Command * > & Visited, Command * Cmd) static
Definition at line 138 of file graph_builder.cpp.
References markNodeAsVisited(), cl::sycl::detail::Command::MUsers, and cl::sycl::detail::Command::printDot().
processFloatDataToPixel()
template<typename ChannelType > vec<ChannelType, 4> cl::sycl::detail::processFloatDataToPixel (vec< cl_float, 4 > WriteData, float MulFactor)
Definition at line 547 of file image_accessor_util.hpp.
References cl::sycl::clamp().
program_impl::get_info< info::program::context >()
template<> context cl::sycl::detail::program_impl::get_info< info::program::context > () const
Definition at line 518 of file program_impl.cpp.
program_impl::get_info< info::program::devices >()
template<> std::vector<device> cl::sycl::detail::program_impl::get_info< info::program::devices > () const
Definition at line 523 of file program_impl.cpp.
program_impl::get_info< info::program::reference_count >()
template<> cl_uint cl::sycl::detail::program_impl::get_info< info::program::reference_count > () const
Definition at line 505 of file program_impl.cpp.
References cl::sycl::detail::plugin::call(), getPlugin(), PI_INVALID_PROGRAM, PI_PROGRAM_INFO_REFERENCE_COUNT, and piProgramGetInfo().
queue_impl::get_info< info::queue::context >()
template<> context cl::sycl::detail::queue_impl::get_info< info::queue::context > () const
Definition at line 37 of file queue_impl.cpp.
queue_impl::get_info< info::queue::device >()
template<> device cl::sycl::detail::queue_impl::get_info< info::queue::device > () const
Definition at line 41 of file queue_impl.cpp.
queue_impl::get_info< info::queue::reference_count >()
template<> cl_uint cl::sycl::detail::queue_impl::get_info< info::queue::reference_count > () const
Definition at line 28 of file queue_impl.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::pi::getPlugin(), PI_QUEUE_INFO_REFERENCE_COUNT, PI_SUCCESS, and piQueueGetInfo().
quiet_NaN()
template<typename T > static constexpr T cl::sycl::detail::quiet_NaN () static constexpr
Definition at line 603 of file generic_type_traits.hpp.
read_domain_bitfield()
std::vector<info::partition_affinity_domain> cl::sycl::detail::read_domain_bitfield (cl_device_affinity_domain bits) inline
Definition at line 53 of file device_info.hpp.
Referenced by cl::sycl::detail::get_device_info< std::vector< info::partition_affinity_domain >, info::device::partition_affinity_domains >::get().
read_execution_bitfield()
std::vector<info::execution_capability> cl::sycl::detail::read_execution_bitfield (cl_device_exec_capabilities bits) inline
Definition at line 71 of file device_info.hpp.
Referenced by cl::sycl::detail::get_device_info< std::vector< info::execution_capability >, info::device::execution_capabilities >::get().
read_fp_bitfield()
std::vector<info::fp_config> cl::sycl::detail::read_fp_bitfield (cl_device_fp_config bits) inline
Definition at line 31 of file device_info.hpp.
References cl::sycl::fma().
Referenced by cl::sycl::detail::get_device_info< std::vector< info::fp_config >, param >::get(), and cl::sycl::detail::get_device_info< std::vector< info::fp_config >, info::device::single_fp_config >::get().
readConfig()
void cl::sycl::detail::readConfig (bool ForceInitialization)
Definition at line 48 of file config.cpp.
References initValue(), cl::sycl::make_error_code(), max(), MAX_CONFIG_NAME, MAX_CONFIG_VALUE, and SYCL_CONFIG_FILE_NAME.
readMemoryOrderBitfield()
std::vector<memory_order> cl::sycl::detail::readMemoryOrderBitfield (pi_memory_order_capabilities bits) inline
Definition at line 51 of file memory_enums.hpp.
References PI_MEMORY_ORDER_ACQ_REL, PI_MEMORY_ORDER_ACQUIRE, PI_MEMORY_ORDER_RELAXED, PI_MEMORY_ORDER_RELEASE, and PI_MEMORY_ORDER_SEQ_CST.
Referenced by context_impl::get_info< info::context::atomic_memory_order_capabilities >(), cl::sycl::detail::get_context_info< info::context::atomic_memory_order_capabilities >::get(), and cl::sycl::detail::get_device_info< std::vector< memory_order >, info::device::atomic_memory_order_capabilities >::get().
readMemoryScopeBitfield()
std::vector<memory_scope> cl::sycl::detail::readMemoryScopeBitfield (pi_memory_scope_capabilities bits) inline
Definition at line 67 of file memory_enums.hpp.
References PI_MEMORY_SCOPE_DEVICE, PI_MEMORY_SCOPE_SUB_GROUP, PI_MEMORY_SCOPE_SYSTEM, PI_MEMORY_SCOPE_WORK_GROUP, and PI_MEMORY_SCOPE_WORK_ITEM.
Referenced by context_impl::get_info< info::context::atomic_memory_scope_capabilities >(), and cl::sycl::detail::get_device_info< std::vector< memory_scope >, info::device::atomic_memory_scope_capabilities >::get().
readPixel()
template<typename T > vec<T, 4> cl::sycl::detail::readPixel (T * Ptr, const image_channel_order ChannelOrder, const image_channel_type ChannelType)
Definition at line 129 of file image_accessor_util.hpp.
Referenced by ReadPixelData().
ReadPixelData()
template<typename DataT > DataT cl::sycl::detail::ReadPixelData (const cl_int4 PixelCoord, const id< 3 > ImgPitch, const image_channel_type ImageChannelType, const image_channel_order ImageChannelOrder, void * BasePtr, const uint8_t ElementSize)
Definition at line 800 of file image_accessor_util.hpp.
References getImageOffset(), and readPixel().
ReadPixelDataLinearFiltMode()
template<typename DataT > DataT cl::sycl::detail::ReadPixelDataLinearFiltMode (const cl_int8 CoordValues, const cl_float4 abc, const addressing_mode SmplAddrMode, const range< 3 > ImgRange, id< 3 > ImgPitch, const image_channel_type ImgChannelType, const image_channel_order ImgChannelOrder, void * BasePtr, const uint8_t ElementSize)
Definition at line 918 of file image_accessor_util.hpp.
References cl::sycl::a.
releaseDefaultContexts()
void cl::sycl::detail::releaseDefaultContexts ()
Definition at line 101 of file global_handler.cpp.
Referenced by shutdown(), and cl::sycl::detail::DefaultContextReleaseHandler::~DefaultContextReleaseHandler().
removeDuplicateDevices()
const std::vector<device> cl::sycl::detail::removeDuplicateDevices (const std::vector< device > & Devs) inline
Definition at line 385 of file kernel_bundle.hpp.
References getDeviceComparisonLambda().
Referenced by cl::sycl::get_kernel_bundle().
reverseBuf()
void cl::sycl::detail::reverseBuf (char * Buf, unsigned Len) inline
Definition at line 132 of file stream.hpp.
Referenced by ScalarToStr().
ReverseRangeDimensionsForKernel()
static void cl::sycl::detail::ReverseRangeDimensionsForKernel (NDRDescT & NDR) static
Definition at line 1863 of file commands.cpp.
References cl::sycl::detail::NDRDescT::Dims, cl::sycl::detail::NDRDescT::GlobalOffset, cl::sycl::detail::NDRDescT::GlobalSize, and cl::sycl::detail::NDRDescT::LocalSize.
Referenced by SetKernelParamsAndLaunch().
runKernelWithArg() [1/2]
template<typename ArgType , typename KernelType > std::enable_if_t< KernelLambdaHasKernelHandlerArgT<KernelType, ArgType>::value> cl::sycl::detail::runKernelWithArg (KernelType KernelName, ArgType Arg)
Definition at line 197 of file cg_types.hpp.
runKernelWithArg() [2/2]
template<typename ArgType , typename KernelType > std::enable_if_t< !KernelLambdaHasKernelHandlerArgT<KernelType, ArgType>::value> cl::sycl::detail::runKernelWithArg (KernelType KernelName, ArgType Arg)
Definition at line 205 of file cg_types.hpp.
Referenced by cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost().
runKernelWithoutArg() [1/2]
template<typename KernelType > std::enable_if_t<KernelLambdaHasKernelHandlerArgT<KernelType>::value> cl::sycl::detail::runKernelWithoutArg (KernelType KernelName)
Definition at line 183 of file cg_types.hpp.
runKernelWithoutArg() [2/2]
template<typename KernelType > std::enable_if_t<!KernelLambdaHasKernelHandlerArgT<KernelType>::value> cl::sycl::detail::runKernelWithoutArg (KernelType KernelName)
Definition at line 190 of file cg_types.hpp.
Referenced by cl::sycl::detail::HostKernel< KernelType, KernelArgType, Dims >::runOnHost().
sameCtx()
static bool cl::sycl::detail::sameCtx (const ContextImplPtr & LHS, const ContextImplPtr & RHS) static
Definition at line 44 of file graph_builder.cpp.
Referenced by cl::sycl::detail::Scheduler::GraphBuilder::addCG(), cl::sycl::detail::Scheduler::GraphBuilder::addHostAccessor(), and cl::sycl::detail::Scheduler::GraphBuilder::findAllocaForReq().
ScalarToStr() [1/2]
template<typename T > detail::enable_if_t<std::is_integral<T>::value, unsigned> cl::sycl::detail::ScalarToStr (const T & Val, char * Buf, unsigned Flags, int , int Precision = -1) inline
Definition at line 174 of file stream.hpp.
References BaseField, Dec, getAbsVal(), Hex, integralToBase(), Oct, reverseBuf(), ShowBase, and ShowPos.
ScalarToStr() [2/2]
template<typename T > EnableIfFP<T, unsigned> cl::sycl::detail::ScalarToStr (const T & Val, char * Buf, unsigned Flags, int , int Precision = -1) inline
Definition at line 378 of file stream.hpp.
References checkForInfNan(), floatingPointToDecStr(), Scientific, and ShowPos.
Referenced by ArrayToStr(), VecToStr(), writeFloatingPoint(), and writeIntegral().
SetFlushBufOffset()
void cl::sycl::detail::SetFlushBufOffset (GlobalBufAccessorT & GlobalFlushBuf, unsigned WIOffset, unsigned Offset) inline
Definition at line 104 of file stream.hpp.
Referenced by flushBuffer(), and write().
SetKernelParamsAndLaunch()
static pi_result cl::sycl::detail::SetKernelParamsAndLaunch (const QueueImplPtr & Queue, std::vector< ArgDesc > & Args, const std::shared_ptr< device_image_impl > & DeviceImageImpl, RT::PiKernel Kernel, NDRDescT & NDRDesc, std::vector< RT::PiEvent > & RawEvents, RT::PiEvent * OutEvent, const ProgramManager::KernelArgMask & EliminatedArgMask, const std::function< void *(Requirement *Req)> & getMemAllocationFunc) static
Definition at line 1871 of file commands.cpp.
References adjustNDRangePerKernel(), cl::sycl::detail::plugin::call(), cl::sycl::detail::plugin::call_nocheck(), cl::sycl::detail::NDRDescT::Dims, cl::sycl::detail::plugin::getBackend(), getSyclObjImpl(), cl::sycl::detail::NDRDescT::GlobalOffset, cl::sycl::detail::NDRDescT::GlobalSize, kind_accessor, kind_invalid, kind_pointer, kind_sampler, kind_specialization_constants_buffer, kind_std_layout, kind_stream, cl::sycl::detail::NDRDescT::LocalSize, cl::sycl::opencl, PI_INVALID_OPERATION, PI_INVALID_VALUE, PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE, piEnqueueKernelLaunch(), piextKernelSetArgMemObj(), piextKernelSetArgPointer(), piextKernelSetArgSampler(), piKernelGetGroupInfo(), piKernelSetArg(), ReverseRangeDimensionsForKernel(), and cl::sycl::range< dimensions >::size().
Referenced by enqueueImpKernel().
shutdown()
void cl::sycl::detail::shutdown ()
Definition at line 123 of file global_handler.cpp.
References piTearDown(), and releaseDefaultContexts().
Referenced by __attribute__().
split_string()
std::vector< std::string > cl::sycl::detail::split_string (const std::string & str, char delimeter)
Definition at line 228 of file common.cpp.
References cl::sycl::length().
Referenced by cl::sycl::detail::get_platform_info< std::vector< std::string >, info::platform::extensions >::get(), cl::sycl::detail::get_device_info< std::vector< kernel_id >, info::device::built_in_kernel_ids >::get(), cl::sycl::detail::get_device_info< std::vector< std::string >, info::device::built_in_kernels >::get(), and cl::sycl::detail::get_device_info< std::vector< std::string >, info::device::extensions >::get().
stableSerializeSpecConstRegistry()
void cl::sycl::detail::stableSerializeSpecConstRegistry (const SpecConstRegistryT & Reg, SerializedObj & Dst)
Definition at line 30 of file spec_constant_impl.cpp.
References cl::sycl::detail::spec_constant_impl::getSize(), and cl::sycl::detail::spec_constant_impl::getValuePtr().
Referenced by cl::sycl::detail::program_impl::stableSerializeSpecConstRegistry().
stringifyErrorCode()
const char * cl::sycl::detail::stringifyErrorCode (cl_int error)
Definition at line 16 of file common.cpp.
References PI_COMMAND_EXECUTION_FAILURE, and PI_FUNCTION_ADDRESS_IS_NOT_AVAILABLE.
Referenced by codeToString().
tie()
template<typename... Ts> auto cl::sycl::detail::tie (Ts &... Args)
Definition at line 40 of file tuple.hpp.
Referenced by enqueueImpKernel(), cl::sycl::platform::ext_oneapi_get_default_context(), cl::sycl::detail::kernel_bundle_impl::get_kernel(), _pi_context::getAvailableCommandList(), cl::sycl::ext::oneapi::detail::initReduLocalAccs(), cl::sycl::ext::oneapi::detail::reduceReduLocalAccs(), and cl::sycl::ext::oneapi::detail::writeReduSumsToOutAccs().
tokenize()
std::vector<std::string_view> cl::sycl::detail::tokenize (const std::string & Filter, const std::string & Delim)
Definition at line 21 of file device_filter.cpp.
Referenced by cl::sycl::detail::device_filter::device_filter().
totalSize()
template<typename... Ts> constexpr size_t cl::sycl::detail::totalSize (const std::tuple< Ts... > &) constexpr
Definition at line 68 of file plugin.hpp.
Referenced by packCallArguments(), and piDeviceGetInfo().
TryToGetPointer() [1/3]
template<typename T , typename = typename detail::enable_if_t< TryToGetPointerT<T>::value, std::true_type>> TryToGetPointerVecT<T>::type cl::sycl::detail::TryToGetPointer (T & t)
Definition at line 340 of file generic_type_traits.hpp.
TryToGetPointer() [2/3]
template<typename T , typename = typename detail::enable_if_t< !TryToGetPointerT<T>::value, std::false_type>> T cl::sycl::detail::TryToGetPointer (T & t)
Definition at line 355 of file generic_type_traits.hpp.
Referenced by convertDataToType().
TryToGetPointer() [3/3]
template<typename T > TryToGetPointerVecT<T *>::type cl::sycl::detail::TryToGetPointer (T * t)
Definition at line 347 of file generic_type_traits.hpp.
unmarkVisitedNodes()
static void cl::sycl::detail::unmarkVisitedNodes (std::vector< Command * > & Visited) static
Definition at line 123 of file graph_builder.cpp.
UnnormalizeCoordinates() [1/3]
template<typename T > detail::enable_if_t<IsValidCoordType<T>::value, T> cl::sycl::detail::UnnormalizeCoordinates (const T & Coords, const range< 3 > & Range)
Definition at line 37 of file image_accessor_util.hpp.
UnnormalizeCoordinates() [2/3]
template<typename T > detail::enable_if_t<IsValidCoordType<T>::value, vec<T, 2> > cl::sycl::detail::UnnormalizeCoordinates (const vec< T, 2 > & Coords, const range< 3 > & Range)
Definition at line 43 of file image_accessor_util.hpp.
UnnormalizeCoordinates() [3/3]
template<typename T > detail::enable_if_t<IsValidCoordType<T>::value, vec<T, 4> > cl::sycl::detail::UnnormalizeCoordinates (const vec< T, 4 > & Coords, const range< 3 > & Range)
Definition at line 49 of file image_accessor_util.hpp.
Referenced by imageReadSamplerHostImpl().
updateOffset()
bool cl::sycl::detail::updateOffset (GlobalOffsetAccessorT & GlobalOffset, GlobalBufAccessorT & GlobalBuf, unsigned Size, unsigned & Cur) inline
Definition at line 430 of file stream.hpp.
References cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::get_range(), and cl::sycl::range< dimensions >::size().
Referenced by flushBuffer().
UseSpvEnv()
static constexpr char cl::sycl::detail::UseSpvEnv ("SYCL_USE_KERNEL_SPV") static constexpr
Referenced by cl::sycl::detail::ProgramManager::ProgramManager().
VecToStr() [1/3]
template<typename T , int VecLength> detail::enable_if_t<(VecLength == 1), unsigned> cl::sycl::detail::VecToStr (const vec< T, VecLength > & Vec, char * VecStr, unsigned Flags, int Width, int Precision)
Definition at line 465 of file stream.hpp.
References ScalarToStr().
VecToStr() [2/3]
template<typename T , int VecLength> detail::enable_if_t<(VecLength == 2 || VecLength == 4 || VecLength == 8 || VecLength == 16), unsigned> cl::sycl::detail::VecToStr (const vec< T, VecLength > & Vec, char * VecStr, unsigned Flags, int Width, int Precision)
Definition at line 474 of file stream.hpp.
References append(), VEC_ELEMENT_DELIMITER, and VecToStr().
VecToStr() [3/3]
template<typename T , int VecLength> detail::enable_if_t<(VecLength == 3), unsigned> cl::sycl::detail::VecToStr (const vec< T, VecLength > & Vec, char * VecStr, unsigned Flags, int Width, int Precision)
Definition at line 486 of file stream.hpp.
References append(), and VEC_ELEMENT_DELIMITER.
Referenced by VecToStr().
waitEvents()
void cl::sycl::detail::waitEvents (std::vector< cl::sycl::event > DepEvents)
Definition at line 36 of file helpers.cpp.
References getSyclObjImpl().
waitForEvents()
static void cl::sycl::detail::waitForEvents (const std::vector< EventImplPtr > & Events) static
Definition at line 113 of file memory_manager.cpp.
References cl::sycl::detail::plugin::call(), and piEventsWait().
Referenced by cl::sycl::detail::MemoryManager::allocate(), cl::sycl::detail::MemoryManager::allocateMemSubBuffer(), cl::sycl::detail::DispatchHostTask::operator()(), and cl::sycl::detail::MemoryManager::release().
waitUntilBuilt()
template<typename ExceptionT , typename RetT > RetT* cl::sycl::detail::waitUntilBuilt (KernelProgramCache & Cache, KernelProgramCache::BuildResult< RetT > * BuildResult)
Definition at line 121 of file program_manager.cpp.
References BS_Done, BS_Failed, cl::sycl::detail::KernelProgramCache::BuildError::Code, cl::sycl::detail::KernelProgramCache::BuildResult< T >::Error, cl::sycl::detail::KernelProgramCache::BuildError::Msg, cl::sycl::detail::KernelProgramCache::BuildResult< T >::Ptr, cl::sycl::detail::KernelProgramCache::BuildResult< T >::State, and cl::sycl::detail::KernelProgramCache::waitUntilBuilt().
workGroupBarrier()
static void cl::sycl::detail::workGroupBarrier () inline static
Definition at line 33 of file group.hpp.
References __spirv_ControlBarrier(), __spv::MemorySemanticsMask::SequentiallyConsistent, __spv::Scope::Workgroup, and __spv::MemorySemanticsMask::WorkgroupMemory.
Referenced by cl::sycl::ext::oneapi::group_local_memory(), cl::sycl::group< 1 >::parallel_for_work_item(), and cl::sycl::ext::oneapi::detail::reduCGFuncImpl().
write()
void cl::sycl::detail::write (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const char * Str, unsigned Len, unsigned Padding = 0) inline
Definition at line 110 of file stream.hpp.
References FLUSH_BUF_OFFSET_SIZE, GetFlushBufOffset(), SetFlushBufOffset(), and cl::sycl::accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT >::size().
Referenced by accessModeToString(), combineAccessModes(), cl::sycl::accessor< DataT, 1, access_mode::read_write, target::host_buffer, access::placeholder::false_t >::getAdjustedMode(), isAccessModeAllowed(), cl::sycl::detail::MemoryManager::map(), cl::__ESIMD_DNS::simd_view_impl< BaseTy, RegionTy >::merge(), modeNeedsOldData(), cl::sycl::operator<<(), cl::__ESIMD_DNS::simd_view_impl< BaseTy, RegionTy >::operator=(), writeArray(), writeFloatingPoint(), writeGroup(), writeHItem(), writeIntegral(), writeItem(), writeNDItem(), writeNDRange(), and writeVec().
writeArray()
template<int ArrayLength> void cl::sycl::detail::writeArray (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const array< ArrayLength > & Arr) inline
Definition at line 524 of file stream.hpp.
References ArrayToStr(), MAX_ARRAY_SIZE, and write().
writeFloatingPoint()
template<typename T > EnableIfFP<T> cl::sycl::detail::writeFloatingPoint (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, int Precision, const T & Val) inline
Definition at line 416 of file stream.hpp.
References MAX_FLOATING_POINT_DIGITS, ScalarToStr(), and write().
writeGroup()
template<int Dimensions> void cl::sycl::detail::writeGroup (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const group< Dimensions > & Group) inline
Definition at line 588 of file stream.hpp.
References append(), ArrayToStr(), cl::sycl::group< Dimensions >::get_global_range(), cl::sycl::group< Dimensions >::get_group_range(), cl::sycl::group< Dimensions >::get_id(), cl::sycl::group< Dimensions >::get_local_range(), MAX_ARRAY_SIZE, and write().
writeHItem()
template<int Dimensions> void cl::sycl::detail::writeHItem (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const h_item< Dimensions > & HItem) inline
Definition at line 625 of file stream.hpp.
References append(), cl::sycl::h_item< dimensions >::get_global(), cl::sycl::h_item< dimensions >::get_logical_local(), cl::sycl::h_item< dimensions >::get_physical_local(), ItemToStr(), MAX_ITEM_SIZE, and write().
writeIntegral()
template<typename T > detail::enable_if_t<std::is_integral<T>::value> cl::sycl::detail::writeIntegral (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, const T & Val) inline
Definition at line 404 of file stream.hpp.
References MAX_INTEGRAL_DIGITS, ScalarToStr(), and write().
Referenced by cl::sycl::operator<<().
writeItem()
template<int Dimensions> void cl::sycl::detail::writeItem (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const item< Dimensions > & Item) inline
Definition at line 533 of file stream.hpp.
References append(), ArrayToStr(), cl::sycl::item< dimensions, with_offset >::get_id(), cl::sycl::item< dimensions, with_offset >::get_offset(), cl::sycl::item< dimensions, with_offset >::get_range(), MAX_ARRAY_SIZE, and write().
writeNDItem()
template<int Dimensions> void cl::sycl::detail::writeNDItem (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const nd_item< Dimensions > & ND_Item) inline
Definition at line 571 of file stream.hpp.
References append(), ArrayToStr(), cl::sycl::nd_item< dimensions >::get_global_id(), cl::sycl::nd_item< dimensions >::get_local_id(), MAX_ARRAY_SIZE, and write().
writeNDRange()
template<int Dimensions> void cl::sycl::detail::writeNDRange (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, const nd_range< Dimensions > & ND_Range) inline
Definition at line 552 of file stream.hpp.
References append(), ArrayToStr(), cl::sycl::nd_range< dimensions >::get_global_range(), cl::sycl::nd_range< dimensions >::get_local_range(), cl::sycl::nd_range< dimensions >::get_offset(), MAX_ARRAY_SIZE, and write().
writePixel()
template<typename T > void cl::sycl::detail::writePixel (const vec< T, 4 > Pixel, T * Ptr, const image_channel_order ChannelOrder, const image_channel_type ChannelType)
Definition at line 212 of file image_accessor_util.hpp.
Referenced by imageWriteHostImpl().
writeVec()
template<typename T , int VecLength> void cl::sycl::detail::writeVec (GlobalBufAccessorT & GlobalFlushBuf, size_t FlushBufferSize, unsigned WIOffset, unsigned Flags, int Width, int Precision, const vec< T, VecLength > & Vec) inline
Definition at line 495 of file stream.hpp.
References MAX_FLOATING_POINT_DIGITS, and write().
Variable Documentation
argument_helper
template<typename F , typename SuggestedArgType > decltype(member_ptr_helper(&F::operator())) cl::sycl::detail::argument_helper(int)
Definition at line 105 of file handler.hpp.
BackendNameKeyName
constexpr char cl::sycl::detail::BackendNameKeyName[] = "BackendName" constexpr
Definition at line 21 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
BaseField
constexpr FmtFlags cl::sycl::detail::BaseField = Dec | Hex | Oct static constexpr
Definition at line 36 of file stream.hpp.
Referenced by cl::sycl::operator<<(), and ScalarToStr().
ConfigFromCompileDefEnabled
constexpr bool cl::sycl::detail::ConfigFromCompileDefEnabled = true constexpr
Definition at line 44 of file config.hpp.
ConfigFromEnvEnabled
constexpr bool cl::sycl::detail::ConfigFromEnvEnabled = true constexpr
Definition at line 32 of file config.hpp.
ConfigFromFileEnabled
constexpr bool cl::sycl::detail::ConfigFromFileEnabled = true constexpr
Definition at line 38 of file config.hpp.
DbgProgMgr
constexpr int cl::sycl::detail::DbgProgMgr = 0 static constexpr
Definition at line 46 of file program_manager.cpp.
Referenced by cl::sycl::detail::ProgramManager::createPIProgram(), cl::sycl::detail::ProgramManager::flushSpecConstants(), cl::sycl::detail::ProgramManager::getDeviceImage(), cl::sycl::detail::ProgramManager::getOrCreateKernel(), and cl::sycl::detail::ProgramManager::ProgramManager().
Dec
constexpr FmtFlags cl::sycl::detail::Dec = 0x0001 static constexpr
Definition at line 25 of file stream.hpp.
Referenced by ScalarToStr().
DefaultContextType
constexpr CUDAContextT cl::sycl::detail::DefaultContextType = CUDAContextT::custom constexpr
Default context type created for CUDA backend.
Definition at line 50 of file queue_impl.hpp.
DeviceNameKeyName
constexpr char cl::sycl::detail::DeviceNameKeyName[] = "DeviceName" constexpr
Definition at line 26 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
DeviceTypeKeyName
constexpr char cl::sycl::detail::DeviceTypeKeyName[] = "DeviceType" constexpr
Definition at line 22 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
DeviceVendorIdKeyName
constexpr char cl::sycl::detail::DeviceVendorIdKeyName[] = "DeviceVendorId" constexpr
Definition at line 23 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
DriverVersionKeyName
constexpr char cl::sycl::detail::DriverVersionKeyName[] = "DriverVersion" constexpr
Definition at line 24 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
Fixed
constexpr FmtFlags cl::sycl::detail::Fixed = 0x0020 static constexpr
Definition at line 30 of file stream.hpp.
FloatField
constexpr FmtFlags cl::sycl::detail::FloatField = Scientific | Fixed static constexpr
Definition at line 41 of file stream.hpp.
FLUSH_BUF_OFFSET_SIZE
constexpr unsigned cl::sycl::detail::FLUSH_BUF_OFFSET_SIZE = 2 constexpr
Definition at line 58 of file stream.hpp.
Referenced by cl::sycl::detail::stream_impl::accessGlobalFlushBuf(), flushBuffer(), cl::sycl::detail::stream_impl::stream_impl(), and write().
GlobalBufAS
constexpr static access::address_space cl::sycl::detail::GlobalBufAS static constexpr
Initial value:
=
    TargetToAS<cl::sycl::access::target::global_buffer>::AS
Definition at line 71 of file stream.hpp.
GlobalBufDim
constexpr static int cl::sycl::detail::GlobalBufDim = 1 static constexpr
Definition at line 75 of file stream.hpp.
GlobalOffsetAS
constexpr static access::address_space cl::sycl::detail::GlobalOffsetAS static constexpr
Initial value:
=
    TargetToAS<cl::sycl::access::target::global_buffer>::AS
Definition at line 82 of file stream.hpp.
GlobalOffsetDim
constexpr static int cl::sycl::detail::GlobalOffsetDim = 1 static constexpr
Definition at line 86 of file stream.hpp.
Hex
constexpr FmtFlags cl::sycl::detail::Hex = 0x0002 static constexpr
Definition at line 26 of file stream.hpp.
Referenced by cl::sycl::operator<<(), and ScalarToStr().
is_convertible_v
template<typename T , typename U > constexpr bool cl::sycl::detail::is_convertible_v = std::is_convertible<T, U>::value inline constexpr
Definition at line 85 of file stl_type_traits.hpp.
is_same_v
template<typename T , typename U > constexpr bool cl::sycl::detail::is_same_v = std::is_same<T, U>::value inline constexpr
Definition at line 82 of file stl_type_traits.hpp.
ITTSpecConstId
constexpr uint32_t cl::sycl::detail::ITTSpecConstId = 0xFF747469 inline static constexpr
Definition at line 50 of file program_manager.hpp.
Referenced by enableITTAnnotationsIfNeeded().
LastKSId
constexpr KernelSetId cl::sycl::detail::LastKSId = SpvFileKSId constexpr
Definition at line 344 of file common.hpp.
MAX_ARRAY_SIZE
constexpr size_t cl::sycl::detail::MAX_ARRAY_SIZE constexpr
Initial value:
=
    MAX_INTEGRAL_DIGITS * MAX_DIMENSIONS + 2 * (MAX_DIMENSIONS - 1) + 2
Definition at line 53 of file stream.hpp.
Referenced by writeArray(), writeGroup(), writeItem(), writeNDItem(), and writeNDRange().
MAX_CONFIG_NAME
constexpr int cl::sycl::detail::MAX_CONFIG_NAME = 256 constexpr
Definition at line 47 of file config.hpp.
Referenced by readConfig().
MAX_CONFIG_VALUE
constexpr int cl::sycl::detail::MAX_CONFIG_VALUE = 1024 constexpr
Definition at line 48 of file config.hpp.
Referenced by readConfig().
MAX_DIMENSIONS
constexpr size_t cl::sycl::detail::MAX_DIMENSIONS = 3 constexpr
Definition at line 49 of file stream.hpp.
MAX_FLOATING_POINT_DIGITS
constexpr size_t cl::sycl::detail::MAX_FLOATING_POINT_DIGITS = 24 constexpr
Definition at line 43 of file stream.hpp.
Referenced by floatingPointToDecStr(), writeFloatingPoint(), and writeVec().
MAX_INTEGRAL_DIGITS
constexpr size_t cl::sycl::detail::MAX_INTEGRAL_DIGITS = 23 constexpr
Definition at line 44 of file stream.hpp.
Referenced by writeIntegral().
MAX_ITEM_SIZE
constexpr size_t cl::sycl::detail::MAX_ITEM_SIZE = 2 * MAX_ARRAY_SIZE + 20 constexpr
Definition at line 610 of file stream.hpp.
Referenced by writeHItem().
MaxNumQueues
constexpr size_t cl::sycl::detail::MaxNumQueues = 256 static constexpr
Sets max number of queues supported by FPGA RT.
Definition at line 43 of file queue_impl.hpp.
Referenced by cl::sycl::detail::queue_impl::getExclusiveQueueHandleRef().
Oct
constexpr FmtFlags cl::sycl::detail::Oct = 0x0004 static constexpr
Definition at line 27 of file stream.hpp.
Referenced by ScalarToStr().
PlatformNameKeyName
constexpr char cl::sycl::detail::PlatformNameKeyName[] = "PlatformName" constexpr
Definition at line 27 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
PlatformVersionKeyName
constexpr char cl::sycl::detail::PlatformVersionKeyName[] = "PlatformVersion" constexpr
Definition at line 25 of file allowlist.cpp.
Referenced by applyAllowList(), deviceIsAllowed(), and parseAllowList().
Scientific
constexpr FmtFlags cl::sycl::detail::Scientific = 0x0040 static constexpr
Definition at line 31 of file stream.hpp.
Referenced by ScalarToStr().
ShiftBitsForVersion
constexpr unsigned int cl::sycl::detail::ShiftBitsForVersion = 24 constexpr
Definition at line 123 of file cg.hpp.
Referenced by getCGTypeVersion(), getUnversionedCGType(), and getVersionedCGType().
ShowBase
constexpr FmtFlags cl::sycl::detail::ShowBase = 0x0008 static constexpr
Definition at line 28 of file stream.hpp.
Referenced by cl::sycl::operator<<(), and ScalarToStr().
ShowPos
constexpr FmtFlags cl::sycl::detail::ShowPos = 0x0010 static constexpr
Definition at line 29 of file stream.hpp.
Referenced by ScalarToStr().
SpvFileKSId
constexpr KernelSetId cl::sycl::detail::SpvFileKSId = 0 constexpr
Definition at line 343 of file common.hpp.
Referenced by cl::sycl::detail::ProgramManager::ProgramManager().
SupportedAllowListKeyNames
constexpr std::array<const char *, 7> cl::sycl::detail::SupportedAllowListKeyNames constexpr
Initial value:
{
    BackendNameKeyName,   DeviceTypeKeyName,      DeviceVendorIdKeyName,
    DriverVersionKeyName, PlatformVersionKeyName, DeviceNameKeyName,
    PlatformNameKeyName}
Definition at line 29 of file allowlist.cpp.
Referenced by deviceIsAllowed(), and parseAllowList().
SYCL_BUFFER_STREAM_NAME
constexpr const char* cl::sycl::detail::SYCL_BUFFER_STREAM_NAME inline constexpr
Initial value:
=
    "sycl.experimental.buffer"
Definition at line 44 of file xpti_registry.hpp.
Referenced by cl::sycl::detail::XPTIRegistry::initializeFrameworkOnce().
SYCL_MEM_ALLOC_STREAM_NAME
constexpr auto cl::sycl::detail::SYCL_MEM_ALLOC_STREAM_NAME inline constexpr
Initial value:
=
    "sycl.experimental.mem_alloc"
Definition at line 34 of file xpti_registry.hpp.
Referenced by cl::sycl::detail::XPTIRegistry::initializeFrameworkOnce().
SYCL_PICALL_STREAM_NAME
constexpr const char* cl::sycl::detail::SYCL_PICALL_STREAM_NAME = "sycl.pi" inline constexpr
Definition at line 30 of file xpti_registry.hpp.
Referenced by cl::sycl::detail::pi::emitFunctionBeginTrace(), cl::sycl::detail::pi::emitFunctionEndTrace(), and cl::sycl::detail::pi::initializePlugins().
SYCL_PIDEBUGCALL_STREAM_NAME
constexpr const char* cl::sycl::detail::SYCL_PIDEBUGCALL_STREAM_NAME = "sycl.pi.debug" inline constexpr
Definition at line 33 of file xpti_registry.hpp.
Referenced by cl::sycl::detail::pi::emitFunctionWithArgsBeginTrace(), cl::sycl::detail::pi::emitFunctionWithArgsEndTrace(), and cl::sycl::detail::pi::initializePlugins().
SYCL_STREAM_NAME
constexpr const char* cl::sycl::detail::SYCL_STREAM_NAME = "sycl" inline constexpr
Definition at line 28 of file xpti_registry.hpp.
Referenced by cl::sycl::detail::Command::Command(), cl::sycl::detail::pi::initializePlugins(), cl::sycl::detail::event_impl::wait(), and cl::sycl::detail::queue_impl::wait().
VEC_CLOSE_BRACE
constexpr char cl::sycl::detail::VEC_CLOSE_BRACE = '}' constexpr
Definition at line 47 of file stream.hpp.
Referenced by ArrayToStr().
VEC_ELEMENT_DELIMITER
constexpr const char* cl::sycl::detail::VEC_ELEMENT_DELIMITER = ", " constexpr
Definition at line 45 of file stream.hpp.
Referenced by ArrayToStr(), and VecToStr().
VEC_OPEN_BRACE
constexpr char cl::sycl::detail::VEC_OPEN_BRACE = '{' constexpr
Definition at line 46 of file stream.hpp.
Referenced by ArrayToStr().