DPC++ Runtime: sycl::_V1::ext::oneapi::experimental Namespace Reference
sycl::_V1::ext::oneapi::experimental Namespace Reference
Namespaces
cplx
cuda
default_sorters
detail
info
matrix
native
property
radix_sorters
simd_abi
this_kernel
this_work_item
Classes
class group_with_scratchpad
struct is_fixed_topology_group
class root_group
struct is_fixed_topology_group< root_group< Dimensions > >
struct is_fixed_topology_group< sycl::group< Dimensions > >
struct is_fixed_topology_group< sycl::ext::oneapi::sub_group >
struct is_fixed_topology_group< sycl::sub_group >
struct is_user_constructed_group
struct property_value< sycl::ext::intel::esimd::cache_hint_L1_key, std::integral_constant< sycl::ext::intel::esimd::cache_hint, Hint > >
struct property_value< sycl::ext::intel::esimd::cache_hint_L2_key, std::integral_constant< sycl::ext::intel::esimd::cache_hint, Hint > >
struct property_value< sycl::ext::intel::esimd::cache_hint_L3_key, std::integral_constant< sycl::ext::intel::esimd::cache_hint, Hint > >
struct is_property_list< sycl::ext::intel::esimd::properties< std::tuple< PropertyValueTs... > > >
class annotated_ptr
struct is_property_key_of< intel::experimental::read_hint_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< intel::experimental::read_assertion_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< intel::experimental::write_hint_key, annotated_ptr< T, PropertyListT > >
struct propagateToPtrAnnotation< intel::experimental::read_hint_key >
struct propagateToPtrAnnotation< intel::experimental::read_assertion_key >
struct propagateToPtrAnnotation< intel::experimental::write_hint_key >
struct is_valid_property< T, intel::experimental::read_hint_key::value_t< Cs... > >
struct is_valid_property< T, intel::experimental::read_assertion_key::value_t< Cs... > >
struct is_valid_property< T, intel::experimental::write_hint_key::value_t< Cs... > >
struct is_property_key_of< intel::experimental::fp_control_key, intel::experimental::kernel_attribute< T, PropertyListT > >
class annotated_arg
struct is_property_key_of< register_map_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< conduit_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< stable_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< buffer_location_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< awidth_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< dwidth_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< latency_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< read_write_mode_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< maxburst_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< wait_request_key, annotated_arg< T, PropertyListT > >
struct is_property_key_of< register_map_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< conduit_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< stable_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< buffer_location_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< awidth_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< dwidth_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< latency_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< read_write_mode_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< maxburst_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< wait_request_key, annotated_ptr< T, PropertyListT > >
struct is_valid_property< T, buffer_location_key::value_t< N > >
struct is_valid_property< T, awidth_key::value_t< W > >
struct is_valid_property< T, dwidth_key::value_t< W > >
struct is_valid_property< T, latency_key::value_t< N > >
struct is_valid_property< T, read_write_mode_key::value_t< Mode > >
struct is_valid_property< T, maxburst_key::value_t< N > >
struct is_valid_property< T, wait_request_key::value_t< Enable > >
struct is_valid_property< T, register_map_key::value_t >
struct is_valid_property< T, conduit_key::value_t >
struct is_valid_property< T, stable_key::value_t >
struct propagateToPtrAnnotation< buffer_location_key >
struct is_property_key_of< intel::experimental::streaming_interface_key, intel::experimental::fpga_kernel_attribute< T, PropertyListT > >
struct is_property_key_of< intel::experimental::register_map_interface_key, intel::experimental::fpga_kernel_attribute< T, PropertyListT > >
struct is_property_key_of< intel::experimental::pipelined_key, intel::experimental::fpga_kernel_attribute< T, PropertyListT > >
struct is_property_key_of< intel::experimental::fpga_cluster_key, intel::experimental::fpga_kernel_attribute< T, PropertyListT > >
struct is_property_key_of< intel::experimental::pipelined_key, intel::experimental::task_sequence< f, PropertyListT > >
struct is_property_key_of< intel::experimental::fpga_cluster_key, intel::experimental::task_sequence< f, PropertyListT > >
struct is_property_key_of< intel::experimental::resource_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::num_banks_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::stride_size_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::word_size_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::bi_directional_ports_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::clock_2x_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::ram_stitching_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::max_private_copies_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::num_replicates_key, intel::experimental::fpga_mem< T, PropertyListT > >
struct is_property_key_of< intel::experimental::cache_config_key, intel::experimental::gpu_kernel_attribute< T, PropertyListT > >
struct is_property_key_of< intel::experimental::balanced_key, intel::experimental::task_sequence< f, PropertyListT > >
struct is_property_key_of< intel::experimental::invocation_capacity_key, intel::experimental::task_sequence< f, PropertyListT > >
struct is_property_key_of< intel::experimental::response_capacity_key, intel::experimental::task_sequence< f, PropertyListT > >
struct unsampled_image_handle
Opaque unsampled image handle type.
struct sampled_image_handle
Opaque sampled image handle type.
struct image_descriptor
A struct to describe the properties of an image.
struct interop_mem_handle
Opaque interop memory handle type.
struct interop_semaphore_handle
Opaque interop semaphore handle type.
struct resource_fd
struct resource_win32_handle
struct resource_win32_name
struct external_mem_descriptor
Opaque external memory descriptor type.
struct external_semaphore_descriptor
struct external_mem_fd
EVERYTHING BELOW IS DEPRECATED.
struct external_mem_win32
Windows external memory type.
struct external_semaphore_fd
External semaphore file descriptor type.
struct image_mem_handle
Opaque image memory handle type.
class image_mem
A class that represents image memory.
struct bindless_image_sampler
class device_global
class device_global< T, detail::properties_t< Props... > >
struct device_image_scope_key
struct host_access_key
struct init_mode_key
struct implement_in_csr_key
struct is_property_key_of< device_image_scope_key, device_global< T, PropertyListT > >
struct is_property_key_of< host_access_key, device_global< T, PropertyListT > >
struct is_property_key_of< init_mode_key, device_global< T, PropertyListT > >
struct is_property_key_of< implement_in_csr_key, device_global< T, PropertyListT > >
class annotated_ref
struct annotationHelper
struct annotationHelper< I, detail::properties_t< P... > >
class annotated_ref< T, detail::properties_t< Props... > >
struct usm_kind_key
struct is_valid_property< T, usm_kind_key::value_t< Kind > >
struct is_property_key_of< usm_kind_key, annotated_ptr< T, PropertyListT > >
class ballot_group
struct is_user_constructed_group< ballot_group< ParentGroup > >
struct is_valid_property
struct check_property_list
struct check_property_list< T, Prop, Props... >
struct propagateToPtrAnnotation
struct propagateToPtrAnnotation< property_value< PropKeyT, PropValuesTs... > >
struct alignment_key
struct is_valid_property< T, alignment_key::value_t< W > >
struct is_property_key_of< alignment_key, annotated_ptr< T, PropertyListT > >
struct is_property_key_of< alignment_key, annotated_arg< T, PropertyListT > >
struct propagateToPtrAnnotation< alignment_key >
struct is_genfloat
FORWARD DECLARATIONS.
class complex
struct is_gencomplex
class complex< _Tp, typename std::enable_if_t< is_genfloat< _Tp >::value > >
class launch_config
class fixed_size_group
struct is_user_constructed_group< fixed_size_group< PartitionSize, ParentGroup > >
class command_graph
Graph in the modifiable state.
class node
Class representing a node in the graph, returned by command_graph::add().
class command_graph< graph_state::executable >
class dynamic_parameter
struct input_data_placement_key
struct output_data_placement_key
class default_sorter
class radix_sorter
struct data_placement_key
struct contiguous_memory_key
struct full_group_key
class tangle_group
class opportunistic_group
struct is_user_constructed_group< opportunistic_group >
struct prefetch_hint_key
struct is_user_constructed_group< tangle_group< ParentGroup > >
class uniform
struct use_root_sync_key
struct indirectly_callable_key
struct calls_indirectly_key
struct is_property_key< indirectly_callable_key >
struct is_property_key< calls_indirectly_key >
struct properties_tag
struct work_group_size_key
struct work_group_size_hint_key
struct sub_group_size_key
struct device_has_key
struct nd_range_kernel_key
struct single_task_kernel_key
struct property_value< work_group_size_key, std::integral_constant< size_t, Dim0 >, std::integral_constant< size_t, Dims >... >
struct property_value< work_group_size_hint_key, std::integral_constant< size_t, Dim0 >, std::integral_constant< size_t, Dims >... >
struct property_value< sub_group_size_key, std::integral_constant< uint32_t, Size > >
struct property_value< device_has_key, std::integral_constant< aspect, Aspects >... >
struct property_value< nd_range_kernel_key, std::integral_constant< int, Dims > >
struct property_value< single_task_kernel_key >
struct work_group_progress_key
struct sub_group_progress_key
struct work_item_progress_key
struct property_value< work_group_progress_key, std::integral_constant< forward_progress_guarantee, Guarantee >, std::integral_constant< execution_scope, CoordinationScope > >
struct property_value< sub_group_progress_key, std::integral_constant< forward_progress_guarantee, Guarantee >, std::integral_constant< execution_scope, CoordinationScope > >
struct property_value< work_item_progress_key, std::integral_constant< forward_progress_guarantee, Guarantee >, std::integral_constant< execution_scope, CoordinationScope > >
struct is_property_key< work_group_progress_key >
struct is_property_key< sub_group_progress_key >
struct is_property_key< work_item_progress_key >
struct property_value< intel::experimental::latency_constraint_key, std::integral_constant< int, Target >, std::integral_constant< intel::experimental::latency_control_type, Type >, std::integral_constant< int, Cycle > >
class properties
struct is_property_list
struct is_property_list< properties< std::tuple< PropertyValueTs... > > >
struct is_property_key
struct is_property_key_of
struct property_value
struct is_property_value
struct is_property_value_of
struct is_property_value< V, std::void_t< typename V::key_t > >
struct is_property_value_of< V, O, std::void_t< typename V::key_t > >
class physical_mem
struct build_options
struct is_property_key_of< build_options_key, sycl::kernel_bundle< bundle_state::ext_oneapi_source > >
struct save_log
struct is_property_key_of< save_log_key, sycl::kernel_bundle< bundle_state::ext_oneapi_source > >
struct cl_version
Typedefs
using register_map_key = intel::experimental::register_map_key
using conduit_key = intel::experimental::conduit_key
using stable_key = intel::experimental::stable_key
using buffer_location_key = intel::experimental::buffer_location_key
using awidth_key = intel::experimental::awidth_key
using dwidth_key = intel::experimental::dwidth_key
using latency_key = intel::experimental::latency_key
using read_write_mode_key = intel::experimental::read_write_mode_key
using maxburst_key = intel::experimental::maxburst_key
using wait_request_key = intel::experimental::wait_request_key
using read_write_mode_enum = intel::experimental::read_write_mode_enum
using global_pointer_t = typename decorated_global_ptr< T >::pointer
using UnderlyingT = T
using property_list_t = detail::properties_t< Props... >
using reference = sycl::ext::oneapi::experimental::annotated_ref< T, property_list_t >
template<typename T , typename ListA , typename ListB >
using CheckDevicePtrTAndPropLists = typename detail::CheckTAndPropListsWithUsmKind< sycl::usm::alloc::device, T, ListA, ListB >
template<typename PropertyListT >
using GetAnnotatedDevicePtrProperties = detail::GetAnnotatedPtrPropertiesWithUsmKind< sycl::usm::alloc::device, PropertyListT >
template<typename T , typename ListA , typename ListB >
using CheckHostPtrTAndPropLists = typename detail::CheckTAndPropListsWithUsmKind< sycl::usm::alloc::host, T, ListA, ListB >
template<typename PropertyListT >
using GetAnnotatedHostPtrProperties = detail::GetAnnotatedPtrPropertiesWithUsmKind< sycl::usm::alloc::host, PropertyListT >
template<typename T , typename ListA , typename ListB >
using CheckSharedPtrTAndPropLists = typename detail::CheckTAndPropListsWithUsmKind< sycl::usm::alloc::shared, T, ListA, ListB >
template<typename PropertyListT >
using GetAnnotatedSharedPtrProperties = detail::GetAnnotatedPtrPropertiesWithUsmKind< sycl::usm::alloc::shared, PropertyListT >
template<class T , int N>
using simd = std::experimental::simd< T, simd_abi::native_fixed_size< T, N > >
template<class T , int N>
using simd_mask = std::experimental::simd_mask< T, simd_abi::native_fixed_size< T, N > >
using empty_properties_t = properties< std::tuple<> >
using build_options_key = build_options
using save_log_key = save_log
using source_kb = kernel_bundle< sycl::bundle_state::ext_oneapi_source >
using exe_kb = kernel_bundle< bundle_state::executable >
using kernel_bundle_impl = sycl::detail::kernel_bundle_impl
Enumerations
enum class image_type : unsigned int { standard = 0 , mipmap = 1 , array = 2 , cubemap = 3 }
image type enum
enum class external_mem_handle_type { opaque_fd = 0 , win32_nt_handle = 1 , win32_nt_dx12_resource = 2 }
enum class external_semaphore_handle_type { opaque_fd = 0 , win32_nt_handle = 1 , win32_nt_dx12_fence = 2 }
enum image_copy_flags : unsigned int { HtoD = 0 , DtoH = 1 , DtoD = 2 }
Direction to copy data from bindless image handle (Host -> Device) (Device -> Host) etc.
enum class cubemap_filtering_mode : unsigned int { disjointed = PI_SAMPLER_CUBEMAP_FILTER_MODE_DISJOINTED , seamless = PI_SAMPLER_CUBEMAP_FILTER_MODE_SEAMLESS }
cubemap filtering mode enum
enum class host_access_enum : std::uint16_t { read , write , read_write , none }
enum class init_mode_enum : std::uint16_t { reprogram , reset }
enum class architecture : uint64_t { __SYCL_ARCHITECTURE , __SYCL_ARCHITECTURE_ALIAS }
enum class arch_category { intel_gpu = 0 , nvidia_gpu = 1 , amd_gpu = 2 }
enum class forward_progress_guarantee { concurrent , parallel , weakly_parallel }
enum class execution_scope { work_item , sub_group , work_group , root_group }
enum class graph_state { modifiable , executable }
State to template the command_graph class on.
enum class node_type {
empty = 0 , subgraph = 1 , kernel = 2 , memcpy = 3 ,
memset = 4 , memfill = 5 , prefetch = 6 , memadvise = 7 ,
ext_oneapi_barrier = 8 , host_task = 9
}
enum class group_algorithm_data_placement { blocked , striped }
enum class sorting_order { ascending , descending }
enum class data_placement_enum { blocked , striped }
enum class cache_level { L1 = 0 , L2 = 1 , L3 = 2 , L4 = 3 }
enum class address_access_mode : char { none = 0 , read = 1 , read_write = 2 }
enum class granularity_mode : char { minimum = 0 , recommended = 1 }
enum class source_language : int { opencl = 0 , spirv = 1 }
Functions
image_mem_handle alloc_image_mem (const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
Allocate image memory based on image_descriptor.
image_mem_handle alloc_image_mem (const image_descriptor &desc, const sycl::queue &syclQueue)
Allocate image memory based on image_descriptor.
void free_image_mem (image_mem_handle handle, const sycl::device &syclDevice, const sycl::context &syclContext)
[Deprecated] Free image memory
void free_image_mem (image_mem_handle handle, const sycl::queue &syclQueue)
[Deprecated] Free image memory
void free_image_mem (image_mem_handle handle, image_type imageType, const sycl::device &syclDevice, const sycl::context &syclContext)
Free image memory.
void free_image_mem (image_mem_handle handle, image_type imageType, const sycl::queue &syclQueue)
Free image memory.
image_mem_handle alloc_mipmap_mem (const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
[Deprecated] Allocate mipmap memory based on image_descriptor
image_mem_handle alloc_mipmap_mem (const image_descriptor &desc, const sycl::device &syclQueue)
[Deprecated] Allocate mipmap memory based on image_descriptor
void free_mipmap_mem (image_mem_handle handle, const sycl::device &syclDevice, const sycl::context &syclContext)
[Deprecated] Free mipmap memory
void free_mipmap_mem (image_mem_handle handle, const sycl::queue &syclQueue)
[Deprecated] Free mipmap memory
image_mem_handle get_mip_level_mem_handle (const image_mem_handle mipMem, unsigned int level, const sycl::device &syclDevice, const sycl::context &syclContext)
Retrieve the memory handle to an individual mipmap image.
image_mem_handle get_mip_level_mem_handle (const image_mem_handle mipMem, unsigned int level, const sycl::queue &syclQueue)
Retrieve the memory handle to an individual mipmap image.
template<typename ExternalMemHandleType >
interop_mem_handle import_external_memory (external_mem_descriptor< ExternalMemHandleType > externalMem, const sycl::device &syclDevice, const sycl::context &syclContext)
Import external memory taking an external memory handle (the type of which is dependent on the OS & external API) and return an interop memory handle.
template<typename ExternalMemHandleType >
interop_mem_handle import_external_memory (external_mem_descriptor< ExternalMemHandleType > externalMem, const sycl::queue &syclQueue)
Import external memory taking an external memory handle (the type of which is dependent on the OS & external API) and return an interop memory handle.
image_mem_handle map_external_memory_array (interop_mem_handle memHandle, const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
[Deprecated] Maps an interop memory handle to an image memory handle (which may have a device optimized memory layout)
image_mem_handle map_external_memory_array (interop_mem_handle memHandle, const image_descriptor &desc, const sycl::queue &syclQueue)
[Deprecated] Maps an interop memory handle to an image memory handle (which may have a device optimized memory layout)
image_mem_handle map_external_image_memory (interop_mem_handle memHandle, const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
Maps an interop memory handle to an image memory handle (which may have a device optimized memory layout)
image_mem_handle map_external_image_memory (interop_mem_handle memHandle, const image_descriptor &desc, const sycl::queue &syclQueue)
Maps an interop memory handle to an image memory handle (which may have a device optimized memory layout)
template<typename ExternalSemaphoreHandleType >
interop_semaphore_handle import_external_semaphore (external_semaphore_descriptor< ExternalSemaphoreHandleType > externalSemaphoreDesc, const sycl::device &syclDevice, const sycl::context &syclContext)
Import external semaphore taking an external semaphore handle (the type of which is dependent on the OS & external API)
template<typename ExternalSemaphoreHandleType >
interop_semaphore_handle import_external_semaphore (external_semaphore_descriptor< ExternalSemaphoreHandleType > externalSemaphoreDesc, const sycl::queue &syclQueue)
Import external semaphore taking an external semaphore handle (the type of which is dependent on the OS & external API)
void destroy_external_semaphore (interop_semaphore_handle semaphoreHandle, const sycl::device &syclDevice, const sycl::context &syclContext)
Destroy the external semaphore handle.
void destroy_external_semaphore (interop_semaphore_handle semaphoreHandle, const sycl::queue &syclQueue)
Destroy the external semaphore handle.
void release_external_memory (interop_mem_handle interopHandle, const sycl::device &syclDevice, const sycl::context &syclContext)
Release external memory.
void release_external_memory (interop_mem_handle interopHandle, const sycl::queue &syclQueue)
Release external memory.
unsampled_image_handle create_image (image_mem &memHandle, const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
Create an image and return the device image handle.
unsampled_image_handle create_image (image_mem &memHandle, const image_descriptor &desc, const sycl::queue &syclQueue)
Create an image and return the device image handle.
unsampled_image_handle create_image (image_mem_handle memHandle, const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
Create an image and return the device image handle.
unsampled_image_handle create_image (image_mem_handle memHandle, const image_descriptor &desc, const sycl::queue &syclQueue)
Create an image and return the device image handle.
sampled_image_handle create_image (void *imgMem, size_t pitch, const bindless_image_sampler &sampler, const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
Create a sampled image and return the device image handle.
sampled_image_handle create_image (void *imgMem, size_t pitch, const bindless_image_sampler &sampler, const image_descriptor &desc, const sycl::queue &syclQueue)
Create a sampled image and return the device image handle.
sampled_image_handle create_image (image_mem &memHandle, const bindless_image_sampler &sampler, const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
Create a sampled image and return the device image handle.
sampled_image_handle create_image (image_mem &memHandle, const bindless_image_sampler &sampler, const image_descriptor &desc, const sycl::queue &syclQueue)
Create a sampled image and return the device image handle.
sampled_image_handle create_image (image_mem_handle memHandle, const bindless_image_sampler &sampler, const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
Create a sampled image and return the device image handle.
sampled_image_handle create_image (image_mem_handle memHandle, const bindless_image_sampler &sampler, const image_descriptor &desc, const sycl::queue &syclQueue)
Create a sampled image and return the device image handle.
void destroy_image_handle (unsampled_image_handle &imageHandle, const sycl::device &syclDevice, const sycl::context &syclContext)
Destroy an unsampled image handle.
void destroy_image_handle (unsampled_image_handle &imageHandle, const sycl::queue &syclQueue)
Destroy an unsampled image handle.
void destroy_image_handle (sampled_image_handle &imageHandle, const sycl::device &syclDevice, const sycl::context &syclContext)
Destroy a sampled image handle.
void destroy_image_handle (sampled_image_handle &imageHandle, const sycl::queue &syclQueue)
Destroy a sampled image handle.
void * pitched_alloc_device (size_t *resultPitch, size_t widthInBytes, size_t height, unsigned int elementSizeBytes, const sycl::queue &syclQueue)
Allocate pitched USM image memory.
void * pitched_alloc_device (size_t *resultPitch, size_t widthInBytes, size_t height, unsigned int elementSizeBytes, const sycl::device &syclDevice, const sycl::context &syclContext)
Allocate pitched USM image memory.
void * pitched_alloc_device (size_t *resultPitch, const image_descriptor &desc, const sycl::queue &syclQueue)
Allocate pitched USM image memory.
void * pitched_alloc_device (size_t *resultPitch, const image_descriptor &desc, const sycl::device &syclDevice, const sycl::context &syclContext)
Allocate pitched USM image memory.
sycl::range< 3 > get_image_range (const image_mem_handle memHandle, const sycl::device &syclDevice, const sycl::context &syclContext)
Get the range that describes the image's dimensions.
sycl::range< 3 > get_image_range (const image_mem_handle memHandle, const sycl::queue &syclQueue)
Get the range that describes the image's dimensions.
sycl::image_channel_type get_image_channel_type (const image_mem_handle memHandle, const sycl::device &syclDevice, const sycl::context &syclContext)
Get the channel type that describes the image memory.
sycl::image_channel_type get_image_channel_type (const image_mem_handle memHandle, const sycl::queue &syclQueue)
Get the channel type that describes the image memory.
unsigned int get_image_num_channels (const image_mem_handle memHandle, const sycl::device &syclDevice, const sycl::context &syclContext)
Get the number of channels that describes the image memory.
unsigned int get_image_num_channels (const image_mem_handle memHandle, const sycl::queue &syclQueue)
Get the number of channels that describes the image memory.
template<typename DataT , typename HintT = DataT, typename CoordT >
DataT fetch_image (const unsampled_image_handle &imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]])
Fetch data from an unsampled image using its handle.
template<typename DataT , typename HintT = DataT, typename CoordT >
__SYCL_DEPRECATED ("read_image for standard unsampled images is deprecated. " "Instead use fetch_image.") DataT read_image(const unsampled_image_handle &imageHandle
[Deprecated] Read an unsampled image using its handle
template<typename DataT , typename HintT = DataT, typename CoordT >
DataT fetch_image (const sampled_image_handle &imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]])
Fetch data from a sampled image using its handle.
template<typename DataT , typename HintT = DataT, typename CoordT >
DataT sample_image (const sampled_image_handle &imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]])
Sample data from a sampled image using its handle.
template<typename DataT , typename HintT = DataT, typename CoordT >
__SYCL_DEPRECATED ("read_image for standard sampled images is deprecated. " "Instead use sample_image with floating point coordinates or " "fetch_image with integer coordinates.") DataT read_image(const sampled_image_handle &imageHandle
[Deprecated] Read a sampled image using its handle
constexpr if (detail::are_floating_coords< CoordT >())
else constexpr if (detail::are_integer_coords< CoordT >())
template<typename DataT , typename HintT = DataT, typename CoordT >
DataT sample_mipmap (const sampled_image_handle &imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]], const float level[[maybe_unused]])
Sample a mipmap image using its handle with LOD filtering.
template<typename DataT , typename HintT = DataT, typename CoordT >
DataT sample_mipmap (const sampled_image_handle &imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]], const CoordT &dX[[maybe_unused]], const CoordT &dY[[maybe_unused]])
Sample a mipmap image using its handle with anisotropic filtering.
template<typename DataT , typename HintT = DataT, typename CoordT >
__SYCL_DEPRECATED ("read_mipmap has been deprecated. " "Instead use sample_mipmap.") DataT read_mipmap(const sampled_image_handle &imageHandle
[Deprecated] Read a mipmap image using its handle with LOD filtering
template<typename DataT , typename HintT = DataT, typename CoordT >
__SYCL_DEPRECATED ("read_image for mipmaps is deprecated. " "Instead use sample_mipmap.") DataT read_image(const sampled_image_handle &imageHandle
[Deprecated] Read a mipmap image using its handle with LOD filtering
template<typename DataT , typename HintT = DataT, typename CoordT >
DataT fetch_image_array (const unsampled_image_handle &imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]], unsigned int arrayLayer[[maybe_unused]])
Fetch data from an unsampled image array using its handle.
template<typename DataT , typename HintT = DataT>
DataT fetch_cubemap (const unsampled_image_handle &imageHandle, const int2 &coords, unsigned int face)
Fetch data from an unsampled cubemap image using its handle.
template<typename DataT , typename HintT = DataT>
DataT sample_cubemap (const sampled_image_handle &imageHandle[[maybe_unused]], const sycl::float3 &dirVec[[maybe_unused]])
Sample a cubemap image using its handle.
template<typename DataT , typename HintT = DataT, typename CoordT >
DataT fetch_image_array (const sampled_image_handle &imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]], unsigned int arrayLayer[[maybe_unused]])
Fetch data from a sampled image array using its handle.
template<typename DataT , typename HintT = DataT, typename CoordT >
DataT sample_image_array (const sampled_image_handle &imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]], unsigned int arrayLayer[[maybe_unused]])
Sample data from a sampled image array using its handle.
template<typename DataT , typename CoordT >
void write_image (unsampled_image_handle imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]], const DataT &color[[maybe_unused]])
Write to an unsampled image using its handle.
template<typename DataT , typename CoordT >
void write_image_array (unsampled_image_handle imageHandle[[maybe_unused]], const CoordT &coords[[maybe_unused]], unsigned int arrayLayer[[maybe_unused]], const DataT &color[[maybe_unused]])
Write to an unsampled image array using its handle.
template<typename DataT >
void write_cubemap (unsampled_image_handle imageHandle, const sycl::int2 &coords, int face, const DataT &color)
Write to an unsampled cubemap using its handle.
template<access::address_space Space, access::decorated DecorateAddress, typename ElementType >
multi_ptr< ElementType, Space, DecorateAddress > static_address_cast (ElementType *Ptr)
template<access::address_space Space, access::decorated DecorateAddress, typename ElementType >
multi_ptr< ElementType, Space, DecorateAddress > dynamic_address_cast (ElementType *Ptr)
template<typename ElementType , auto & SizeSpecName, access::decorated DecorateAddress>
private_ptr< ElementType, DecorateAddress > private_alloca (kernel_handler &kh)
template<typename ElementType , std::size_t Alignment, auto & SizeSpecName, access::decorated DecorateAddress>
private_ptr< ElementType, DecorateAddress > aligned_private_alloca (kernel_handler &kh)
template<typename T , typename... Args>
annotated_arg (T, Args...) -> annotated_arg< T, typename detail::DeducedProperties< Args... >::type >
template<typename T , typename old , typename... ArgT>
annotated_arg (annotated_arg< T, old >, properties< std::tuple< ArgT... >>) -> annotated_arg< T, detail::merged_properties_t< old, detail::properties_t< ArgT... >>>
template<typename T , typename... Props>
class __SYCL_SPECIAL_CLASS __SYCL_TYPE (annotated_arg) annotated_arg< T *
annotated_arg (const annotated_arg &)=default
annotated_arg & operator= (annotated_arg &)=default
annotated_arg (T *_ptr, const property_list_t &PropList=property_list_t{}) noexcept
template<typename... PropertyValueTs>
annotated_arg (T *_ptr, const PropertyValueTs &...props) noexcept
template<typename T2 , typename PropertyList2 >
annotated_arg (const annotated_arg< T2, PropertyList2 > &other) noexcept
template<typename T2 , typename PropertyListU , typename PropertyListV >
annotated_arg (const annotated_arg< T2, PropertyListU > &other, const PropertyListV &proplist) noexcept
operator T* () noexcept
T & operator[] (std::ptrdiff_t idx) const noexcept
T * operator-> () const noexcept
template<typename PropertyT >
static constexpr bool has_property ()
template<typename PropertyT >
static constexpr auto get_property ()
annotated_arg (const T &_obj, const property_list_t &PropList=property_list_t{}) noexcept
template<typename... PropertyValueTs>
annotated_arg (const T &_obj, PropertyValueTs... props) noexcept
operator T () noexcept
template<typename T , typename... Props>
class __SYCL_SPECIAL_CLASS __SYCL_TYPE (annotated_ptr) annotated_ptr< T
annotated_ptr (const annotated_ptr &)=default
annotated_ptr & operator= (const annotated_ptr &)=default
annotated_ptr (T *Ptr, const property_list_t &=property_list_t{}) noexcept
template<typename... PropertyValueTs>
annotated_ptr (T *Ptr, const PropertyValueTs &...props) noexcept
template<typename T2 , typename PropertyList2 >
annotated_ptr (const annotated_ptr< T2, PropertyList2 > &other) noexcept
template<typename T2 , typename PropertyListU , typename PropertyListV >
annotated_ptr (const annotated_ptr< T2, PropertyListU > &other, const PropertyListV &) noexcept
reference operator* () const noexcept
std::ptrdiff_t operator- (annotated_ptr other) const noexcept
operator bool () const noexcept
T * get () const noexcept
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>>
annotated_ptr operator+ (size_t offset) const noexcept
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>>
auto operator+ (size_t offset) const noexcept -> decltype("operator+ is not available when alignment is specified!")=delete
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>>
annotated_ptr & operator++ () noexcept
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>>
auto operator++ () noexcept -> decltype("operator++ is not available when alignment is specified!")=delete
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>>
annotated_ptr operator++ (int) noexcept
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>>
auto operator++ (int) noexcept -> decltype("operator++ is not available when alignment is specified!")=delete
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>>
annotated_ptr & operator-- () noexcept
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>>
auto operator-- () noexcept -> decltype("operator-- is not available when alignment is specified!")=delete
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>>
annotated_ptr operator-- (int) noexcept
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>>
auto operator-- (int) noexcept -> decltype("operator-- is not available when alignment is specified!")=delete
template<typename PropertyT >
static constexpr bool has_property ()
template<typename PropertyT >
static constexpr auto get_property ()
template<typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > aligned_alloc_annotated (size_t alignment, size_t numBytes, const device &syclDevice, const context &syclContext, sycl::usm::alloc kind, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > aligned_alloc_annotated (size_t alignment, size_t count, const device &syclDevice, const context &syclContext, sycl::usm::alloc kind, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > aligned_alloc_annotated (size_t alignment, size_t numBytes, const queue &syclQueue, sycl::usm::alloc kind, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > aligned_alloc_annotated (size_t alignment, size_t count, const queue &syclQueue, sycl::usm::alloc kind, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_annotated (size_t numBytes, const device &syclDevice, const context &syclContext, sycl::usm::alloc kind, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_annotated (size_t count, const device &syclDevice, const context &syclContext, sycl::usm::alloc kind, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_annotated (size_t numBytes, const queue &syclQueue, sycl::usm::alloc kind, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_annotated (size_t count, const queue &syclQueue, sycl::usm::alloc kind, const propertyListA &propList=propertyListA{})
template<typename propertyListA , typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_annotated (size_t numBytes, const device &syclDevice, const context &syclContext, const propertyListA &propList)
template<typename T , typename propertyListA , typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_annotated (size_t count, const device &syclDevice, const context &syclContext, const propertyListA &propList)
template<typename propertyListA , typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_annotated (size_t numBytes, const queue &syclQueue, const propertyListA &propList)
template<typename T , typename propertyListA , typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type>
std::enable_if_t< detail::CheckTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_annotated (size_t count, const queue &syclQueue, const propertyListA &propList)
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type>
std::enable_if_t< CheckDevicePtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > aligned_alloc_device_annotated (size_t alignment, size_t numBytes, const device &syclDevice, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type>
std::enable_if_t< CheckDevicePtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > aligned_alloc_device_annotated (size_t alignment, size_t count, const device &syclDevice, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type>
std::enable_if_t< CheckDevicePtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > aligned_alloc_device_annotated (size_t alignment, size_t numBytes, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type>
std::enable_if_t< CheckDevicePtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > aligned_alloc_device_annotated (size_t alignment, size_t count, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type>
std::enable_if_t< CheckDevicePtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_device_annotated (size_t numBytes, const device &syclDevice, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type>
std::enable_if_t< CheckDevicePtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_device_annotated (size_t count, const device &syclDevice, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type>
std::enable_if_t< CheckDevicePtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_device_annotated (size_t numBytes, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type>
std::enable_if_t< CheckDevicePtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_device_annotated (size_t count, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type>
std::enable_if_t< CheckHostPtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > aligned_alloc_host_annotated (size_t alignment, size_t numBytes, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type>
std::enable_if_t< CheckHostPtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > aligned_alloc_host_annotated (size_t alignment, size_t count, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type>
std::enable_if_t< CheckHostPtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > aligned_alloc_host_annotated (size_t alignment, size_t numBytes, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type>
std::enable_if_t< CheckHostPtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > aligned_alloc_host_annotated (size_t alignment, size_t count, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type>
std::enable_if_t< CheckHostPtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_host_annotated (size_t numBytes, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type>
std::enable_if_t< CheckHostPtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_host_annotated (size_t count, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type>
std::enable_if_t< CheckHostPtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_host_annotated (size_t numBytes, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type>
std::enable_if_t< CheckHostPtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_host_annotated (size_t count, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type>
std::enable_if_t< CheckSharedPtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > aligned_alloc_shared_annotated (size_t alignment, size_t numBytes, const device &syclDevice, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type>
std::enable_if_t< CheckSharedPtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > aligned_alloc_shared_annotated (size_t alignment, size_t count, const device &syclDevice, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type>
std::enable_if_t< CheckSharedPtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > aligned_alloc_shared_annotated (size_t alignment, size_t numBytes, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type>
std::enable_if_t< CheckSharedPtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > aligned_alloc_shared_annotated (size_t alignment, size_t count, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type>
std::enable_if_t< CheckSharedPtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_shared_annotated (size_t numBytes, const device &syclDevice, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type>
std::enable_if_t< CheckSharedPtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_shared_annotated (size_t count, const device &syclDevice, const context &syclContext, const propertyListA &propList=propertyListA{})
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type>
std::enable_if_t< CheckSharedPtrTAndPropLists< void, propertyListA, propertyListB >::value, annotated_ptr< void, propertyListB > > malloc_shared_annotated (size_t numBytes, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type>
std::enable_if_t< CheckSharedPtrTAndPropLists< T, propertyListA, propertyListB >::value, annotated_ptr< T, propertyListB > > malloc_shared_annotated (size_t count, const queue &syclQueue, const propertyListA &propList=propertyListA{})
template<typename PropertyListT >
property_list get_usm_property_list ()
size_t combine_align (size_t alignA, size_t alignB)
template<typename T , typename propList >
void free (annotated_ptr< T, propList > &ptr, const context &syclContext)
template<typename T , typename propList >
void free (annotated_ptr< T, propList > &ptr, const queue &syclQueue)
template<int Dimensions>
static range< Dimensions > auto_range ()
template<typename Group >
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&std::is_same_v< Group, sycl::sub_group >, ballot_group< Group > > get_ballot_group (Group group, bool predicate)
template<typename T >
std::enable_if_t< std::is_same_v< T, bfloat16 >, bool > isnan (T x)
template<size_t N>
sycl::marray< bool, N > isnan (sycl::marray< bfloat16, N > x)
template<typename T , int N = num_elements_v<T>>
std::enable_if_t< is_vec_or_swizzle_bf16_v< T >, sycl::vec< int16_t, N > > isnan (T x)
template<typename T >
std::enable_if_t< std::is_same_v< T, bfloat16 >, T > fabs (T x)
template<size_t N>
sycl::marray< bfloat16, N > fabs (sycl::marray< bfloat16, N > x)
template<typename T , int N = num_elements_v<T>>
std::enable_if_t< is_vec_or_swizzle_bf16_v< T >, sycl::vec< bfloat16, N > > fabs (T x)
template<typename T >
std::enable_if_t< std::is_same_v< T, bfloat16 >, T > fmin (T x, T y)
template<size_t N>
sycl::marray< bfloat16, N > fmin (sycl::marray< bfloat16, N > x, sycl::marray< bfloat16, N > y)
template<typename T1 , typename T2 , int N1 = num_elements_v<T1>, int N2 = num_elements_v<T2>>
std::enable_if_t< is_vec_or_swizzle_bf16_v< T1 > &&is_vec_or_swizzle_bf16_v< T2 > &&N1==N2, sycl::vec< bfloat16, N1 > > fmin (T1 x, T2 y)
template<typename T >
std::enable_if_t< std::is_same_v< T, bfloat16 >, T > fmax (T x, T y)
template<size_t N>
sycl::marray< bfloat16, N > fmax (sycl::marray< bfloat16, N > x, sycl::marray< bfloat16, N > y)
template<typename T1 , typename T2 , int N1 = num_elements_v<T1>, int N2 = num_elements_v<T2>>
std::enable_if_t< is_vec_or_swizzle_bf16_v< T1 > &&is_vec_or_swizzle_bf16_v< T2 > &&N1==N2, sycl::vec< bfloat16, N1 > > fmax (T1 x, T2 y)
template<typename T >
std::enable_if_t< std::is_same_v< T, bfloat16 >, T > fma (T x, T y, T z)
template<size_t N>
sycl::marray< bfloat16, N > fma (sycl::marray< bfloat16, N > x, sycl::marray< bfloat16, N > y, sycl::marray< bfloat16, N > z)
template<typename T1 , typename T2 , typename T3 , int N1 = num_elements_v<T1>, int N2 = num_elements_v<T2>, int N3 = num_elements_v<T3>>
std::enable_if_t< is_vec_or_swizzle_bf16_v< T1 > &&is_vec_or_swizzle_bf16_v< T2 > &&is_vec_or_swizzle_bf16_v< T3 > &&N1==N2 &&N2==N3, sycl::vec< bfloat16, N1 > > fma (T1 x, T2 y, T3 z)
template<typename FormatT , typename... Args>
int printf (const FormatT *__format, Args... args)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, _Tp > abs (const complex< _Tp > &__c)
FUNCTIONS.
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, _Tp > arg (const complex< _Tp > &__c)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits< _Tp >::_ValueType arg (_Tp __re)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, _Tp > norm (const complex< _Tp > &__c)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits< _Tp >::_ValueType norm (_Tp __re)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > conj (const complex< _Tp > &__c)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits< _Tp >::_ComplexType conj (_Tp __re)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > proj (const complex< _Tp > &__c)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits< _Tp >::_ComplexType proj (_Tp __re)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > polar (const _Tp &__rho, const _Tp &__theta=_Tp())
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > log (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > log10 (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > sqrt (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > exp (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > pow (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<class _Tp , class _Up >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< typename cplx::detail::__promote< _Tp, _Up >::type > > pow (const complex< _Tp > &__x, const complex< _Up > &__y)
template<class _Tp , class _Up >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value &&is_genfloat< _Up >::value, complex< typename cplx::detail::__promote< _Tp, _Up >::type > > pow (const complex< _Tp > &__x, const _Up &__y)
template<class _Tp , class _Up >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value &&is_genfloat< _Up >::value, complex< typename cplx::detail::__promote< _Tp, _Up >::type > > pow (const _Tp &__x, const complex< _Up > &__y)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > asinh (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > acosh (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > atanh (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > sinh (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > cosh (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > tanh (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > asin (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > acos (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > atan (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > sin (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > cos (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, complex< _Tp > > tan (const complex< _Tp > &__x)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL constexpr _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, _Tp > real (const complex< _Tp > &__c)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL constexpr _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits< _Tp >::_ValueType real (_Tp __re)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL constexpr _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat< _Tp >::value, _Tp > imag (const complex< _Tp > &__c)
template<class _Tp >
__DPCPP_SYCL_EXTERNAL constexpr _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits< _Tp >::_ValueType imag (_Tp)
std::vector< device > get_composite_devices ()
template<architecture... Archs, typename T >
constexpr static auto if_architecture_is (T fn)
The condition is true only if the device which executes the if_architecture_is function has any one of the architectures listed in the.
template<architecture Arch, typename T >
constexpr static auto if_architecture_is_lt (T fn)
The condition is true only if the device which executes the if_architecture_is_lt function has an architecture that is in the same family as.
template<architecture Arch, typename T >
constexpr static auto if_architecture_is_le (T fn)
The condition is true only if the device which executes the if_architecture_is_le function has an architecture that is in the same family as.
template<architecture Arch, typename T >
constexpr static auto if_architecture_is_gt (T fn)
The condition is true only if the device which executes the if_architecture_is_gt function has an architecture that is in the same family as.
template<architecture Arch, typename T >
constexpr static auto if_architecture_is_ge (T fn)
The condition is true only if the device which executes the if_architecture_is_ge function has an architecture that is in the same family as.
template<architecture Arch1, architecture Arch2, typename T >
constexpr static auto if_architecture_is_between (T fn)
The condition is true only if the device which executes the if_architecture_is_between function has an architecture that is in the same family as.
template<typename CommandGroupFunc >
void submit (queue Q, CommandGroupFunc &&CGF, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
template<typename CommandGroupFunc >
event submit_with_event (queue Q, CommandGroupFunc &&CGF, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
template<typename KernelName = sycl::detail::auto_name, typename KernelType >
void single_task (handler &CGH, const KernelType &KernelObj)
template<typename KernelName = sycl::detail::auto_name, typename KernelType >
void single_task (queue Q, const KernelType &KernelObj, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
template<typename... ArgsT>
void single_task (handler &CGH, const kernel &KernelObj, ArgsT &&...Args)
template<typename... ArgsT>
void single_task (queue Q, const kernel &KernelObj, ArgsT &&...Args)
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename KernelType , typename... ReductionsT>
void parallel_for (handler &CGH, range< Dimensions > Range, const KernelType &KernelObj, ReductionsT &&...Reductions)
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename KernelType , typename... ReductionsT>
void parallel_for (queue Q, range< Dimensions > Range, const KernelType &KernelObj, ReductionsT &&...Reductions)
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename Properties , typename KernelType , typename... ReductionsT>
void parallel_for (handler &CGH, launch_config< range< Dimensions >, Properties > Config, const KernelType &KernelObj, ReductionsT &&...Reductions)
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename Properties , typename KernelType , typename... ReductionsT>
void parallel_for (queue Q, launch_config< range< Dimensions >, Properties > Config, const KernelType &KernelObj, ReductionsT &&...Reductions)
template<int Dimensions, typename... ArgsT>
void parallel_for (handler &CGH, range< Dimensions > Range, const kernel &KernelObj, ArgsT &&...Args)
template<int Dimensions, typename... ArgsT>
void parallel_for (queue Q, range< Dimensions > Range, const kernel &KernelObj, ArgsT &&...Args)
template<int Dimensions, typename Properties , typename... ArgsT>
void parallel_for (handler &CGH, launch_config< range< Dimensions >, Properties > Config, const kernel &KernelObj, ArgsT &&...Args)
template<int Dimensions, typename Properties , typename... ArgsT>
void parallel_for (queue Q, launch_config< range< Dimensions >, Properties > Config, const kernel &KernelObj, ArgsT &&...Args)
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename KernelType , typename... ReductionsT>
void nd_launch (handler &CGH, nd_range< Dimensions > Range, const KernelType &KernelObj, ReductionsT &&...Reductions)
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename KernelType , typename... ReductionsT>
void nd_launch (queue Q, nd_range< Dimensions > Range, const KernelType &KernelObj, ReductionsT &&...Reductions)
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename Properties , typename KernelType , typename... ReductionsT>
void nd_launch (handler &CGH, launch_config< nd_range< Dimensions >, Properties > Config, const KernelType &KernelObj, ReductionsT &&...Reductions)
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename Properties , typename KernelType , typename... ReductionsT>
void nd_launch (queue Q, launch_config< nd_range< Dimensions >, Properties > Config, const KernelType &KernelObj, ReductionsT &&...Reductions)
template<int Dimensions, typename... ArgsT>
void nd_launch (handler &CGH, nd_range< Dimensions > Range, const kernel &KernelObj, ArgsT &&...Args)
template<int Dimensions, typename... ArgsT>
void nd_launch (queue Q, nd_range< Dimensions > Range, const kernel &KernelObj, ArgsT &&...Args)
template<int Dimensions, typename Properties , typename... ArgsT>
void nd_launch (handler &CGH, launch_config< nd_range< Dimensions >, Properties > Config, const kernel &KernelObj, ArgsT &&...Args)
template<int Dimensions, typename Properties , typename... ArgsT>
void nd_launch (queue Q, launch_config< nd_range< Dimensions >, Properties > Config, const kernel &KernelObj, ArgsT &&...Args)
void memcpy (handler &CGH, void *Dest, const void *Src, size_t NumBytes)
void memcpy (queue Q, void *Dest, const void *Src, size_t NumBytes, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
template<typename T >
void copy (handler &CGH, const T *Src, T *Dest, size_t Count)
template<typename T >
void copy (queue Q, const T *Src, T *Dest, size_t Count, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
void memset (handler &CGH, void *Ptr, int Value, size_t NumBytes)
void memset (queue Q, void *Ptr, int Value, size_t NumBytes, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
template<typename T >
void fill (sycl::handler &CGH, T *Ptr, const T &Pattern, size_t Count)
template<typename T >
void fill (sycl::queue Q, T *Ptr, const T &Pattern, size_t Count, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
void prefetch (handler &CGH, void *Ptr, size_t NumBytes)
void prefetch (queue Q, void *Ptr, size_t NumBytes, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
void mem_advise (handler &CGH, void *Ptr, size_t NumBytes, int Advice)
void mem_advise (queue Q, void *Ptr, size_t NumBytes, int Advice, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
void barrier (handler &CGH)
void barrier (queue Q, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
void partial_barrier (handler &CGH, const std::vector< event > &Events)
void partial_barrier (queue Q, const std::vector< event > &Events, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
template<size_t PartitionSize, typename Group >
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&std::is_same_v< Group, sycl::sub_group >, fixed_size_group< PartitionSize, Group > > get_fixed_size_group (Group group)
template<typename ValueT >
dynamic_parameter (experimental::command_graph< graph_state::modifiable > Graph, const ValueT &Param) -> dynamic_parameter< ValueT >
Additional CTAD deduction guides.
template<graph_state State = graph_state::modifiable>
command_graph (const context &SyclContext, const device &SyclDevice, const property_list &PropList) -> command_graph< State >
template<typename... Args>
void group_load (Args...)
template<typename... Args>
void group_store (Args...)
template<typename Group , typename T , typename Sorter >
std::enable_if_t< detail::is_sorter< Sorter, Group, T >::value, T > sort_over_group ([[maybe_unused]] Group group, [[maybe_unused]] T value, [[maybe_unused]] Sorter sorter)
template<typename Group , typename T , typename Compare , size_t Extent>
std::enable_if_t<!detail::is_sorter< Compare, Group, T >::value, T > sort_over_group (experimental::group_with_scratchpad< Group, Extent > exec, T value, Compare comp)
template<typename Group , typename T , size_t Extent>
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > >, T > sort_over_group (experimental::group_with_scratchpad< Group, Extent > exec, T value)
template<typename Group , typename T , std::size_t ElementsPerWorkItem, typename Sorter , typename Properties = ext::oneapi::experimental::empty_properties_t>
std::enable_if_t< sycl::ext::oneapi::experimental::is_property_list_v< std::decay_t< Properties > >, void > sort_over_group ([[maybe_unused]] Group g, [[maybe_unused]] sycl::span< T, ElementsPerWorkItem > values, [[maybe_unused]] Sorter sorter, [[maybe_unused]] Properties properties={})
template<typename Group , typename T , std::size_t Extent, std::size_t ElementsPerWorkItem, typename Properties = ext::oneapi::experimental::empty_properties_t>
std::enable_if_t< sycl::ext::oneapi::experimental::is_property_list_v< std::decay_t< Properties > >, void > sort_over_group (experimental::group_with_scratchpad< Group, Extent > exec, sycl::span< T, ElementsPerWorkItem > values, Properties properties={})
template<typename Group , typename T , std::size_t Extent, std::size_t ElementsPerWorkItem, typename Compare , typename Properties = ext::oneapi::experimental::empty_properties_t>
std::enable_if_t<!sycl::ext::oneapi::experimental::is_property_list_v< std::decay_t< Compare > > &&sycl::ext::oneapi::experimental::is_property_list_v< std::decay_t< Properties > >, void > sort_over_group (experimental::group_with_scratchpad< Group, Extent > exec, sycl::span< T, ElementsPerWorkItem > values, Compare comp, Properties properties={})
template<typename Group , typename Iter , typename Sorter >
std::enable_if_t< detail::is_sorter< Sorter, Group, Iter >::value, void > joint_sort ([[maybe_unused]] Group group, [[maybe_unused]] Iter first, [[maybe_unused]] Iter last, [[maybe_unused]] Sorter sorter)
template<typename Group , typename Iter , typename Compare , size_t Extent>
std::enable_if_t<!detail::is_sorter< Compare, Group, Iter >::value, void > joint_sort (experimental::group_with_scratchpad< Group, Extent > exec, Iter first, Iter last, Compare comp)
template<typename Group , typename Iter , size_t Extent>
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > >, void > joint_sort (experimental::group_with_scratchpad< Group, Extent > exec, Iter first, Iter last)
template<typename Group , typename KeyTy , typename ValueTy , typename Sorter >
std::enable_if_t< detail::is_key_value_sorter< Sorter, Group, KeyTy, ValueTy >::value, std::tuple< KeyTy, ValueTy > > sort_key_value_over_group ([[maybe_unused]] Group g, [[maybe_unused]] KeyTy key, [[maybe_unused]] ValueTy value, [[maybe_unused]] Sorter sorter)
template<typename Group , typename KeyTy , typename ValueTy , typename Compare , std::size_t Extent>
std::enable_if_t< !detail::is_key_value_sorter< Compare, Group, KeyTy, ValueTy >::value, std::tuple< KeyTy, ValueTy > > sort_key_value_over_group (experimental::group_with_scratchpad< Group, Extent > exec, KeyTy key, ValueTy value, Compare comp)
template<typename KeyTy , typename ValueTy , typename Group , std::size_t Extent>
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > >, std::tuple< KeyTy, ValueTy > > sort_key_value_over_group (experimental::group_with_scratchpad< Group, Extent > exec, KeyTy key, ValueTy value)
template<class Callable , class... T>
__attribute__ ((always_inline)) auto invoke_simd(sycl
The invoke_simd free function invokes a SIMD function using all work-items in a sub_group.
template<typename Properties = empty_properties_t>
std::enable_if_t< is_property_list_v< std::decay_t< Properties > > > prefetch (void *ptr, Properties properties={})
template<typename Properties = empty_properties_t>
std::enable_if_t< is_property_list_v< std::decay_t< Properties > > > prefetch (void *ptr, size_t bytes, Properties properties={})
template<typename T , typename Properties = empty_properties_t>
std::enable_if_t< is_property_list_v< std::decay_t< Properties > > > prefetch (T *ptr, Properties properties={})
template<typename T , typename Properties = empty_properties_t>
std::enable_if_t< is_property_list_v< std::decay_t< Properties > > > prefetch (T *ptr, size_t count, Properties properties={})
template<access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_AS< AddressSpace > &&is_property_list_v< std::decay_t< Properties > > > prefetch (multi_ptr< void, AddressSpace, IsDecorated > ptr, Properties properties={})
template<access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_AS< AddressSpace > &&is_property_list_v< std::decay_t< Properties > > > prefetch (multi_ptr< void, AddressSpace, IsDecorated > ptr, size_t bytes, Properties properties={})
template<typename T , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_AS< AddressSpace > &&is_property_list_v< std::decay_t< Properties > > > prefetch (multi_ptr< T, AddressSpace, IsDecorated > ptr, Properties properties={})
template<typename T , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_AS< AddressSpace > &&is_property_list_v< std::decay_t< Properties > > > prefetch (multi_ptr< T, AddressSpace, IsDecorated > ptr, size_t count, Properties properties={})
template<typename DataT , int Dimensions, access_mode AccessMode, access::placeholder IsPlaceholder, typename Properties = empty_properties_t, typename AccessorProperties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_acc_mode< AccessMode > &&(Dimensions > 0) &&is_property_list_v< std::decay_t< Properties > > > prefetch (accessor< DataT, Dimensions, AccessMode, target::device, IsPlaceholder, AccessorProperties > acc, id< Dimensions > offset, Properties properties={})
template<typename DataT , int Dimensions, access_mode AccessMode, access::placeholder IsPlaceholder, typename Properties = empty_properties_t, typename AccessorProperties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_acc_mode< AccessMode > &&(Dimensions > 0) &&is_property_list_v< std::decay_t< Properties > > > prefetch (accessor< DataT, Dimensions, AccessMode, target::device, IsPlaceholder, AccessorProperties > acc, size_t offset, size_t count, Properties properties={})
template<typename Group , typename Properties = empty_properties_t>
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, void *ptr, Properties properties={})
template<typename Group , typename Properties = empty_properties_t>
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, void *ptr, size_t bytes, Properties properties={})
template<typename Group , typename T , typename Properties = empty_properties_t>
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, T *ptr, Properties properties={})
template<typename Group , typename T , typename Properties = empty_properties_t>
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, T *ptr, size_t count, Properties properties={})
template<typename Group , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_AS< AddressSpace > &&sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, multi_ptr< void, AddressSpace, IsDecorated > ptr, Properties properties={})
template<typename Group , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_AS< AddressSpace > &&sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, multi_ptr< void, AddressSpace, IsDecorated > ptr, size_t bytes, Properties properties={})
template<typename Group , typename T , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_AS< AddressSpace > &&sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, multi_ptr< T, AddressSpace, IsDecorated > ptr, Properties properties={})
template<typename Group , typename T , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_AS< AddressSpace > &&sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, multi_ptr< T, AddressSpace, IsDecorated > ptr, size_t count, Properties properties={})
template<typename Group , typename DataT , int Dimensions, access_mode AccessMode, access::placeholder IsPlaceholder, typename Properties = empty_properties_t, typename AccessorProperties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_acc_mode< AccessMode > &&(Dimensions > 0) &&sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, accessor< DataT, Dimensions, AccessMode, target::device, IsPlaceholder, AccessorProperties > acc, size_t offset, Properties properties={})
template<typename Group , typename DataT , int Dimensions, access_mode AccessMode, access::placeholder IsPlaceholder, typename Properties = empty_properties_t, typename AccessorProperties = empty_properties_t>
std::enable_if_t< detail::check_prefetch_acc_mode< AccessMode > &&(Dimensions > 0) &&sycl::is_group_v< std::decay_t< Group > > &&is_property_list_v< std::decay_t< Properties > > > joint_prefetch (Group g, accessor< DataT, Dimensions, AccessMode, target::device, IsPlaceholder, AccessorProperties > acc, size_t offset, size_t count, Properties properties={})
event submit_profiling_tag (queue &Queue, const sycl::detail::code_location &CodeLoc=sycl::detail::code_location::current())
template<typename Group >
std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&std::is_same_v< Group, sycl::sub_group >, tangle_group< Group > > get_tangle_group (Group group)
template<typename GroupHelper , typename T , typename BinaryOperation >
std::enable_if_t<(is_group_helper_v< GroupHelper >), T > reduce_over_group (GroupHelper group_helper, T x, BinaryOperation binary_op)
template<typename GroupHelper , typename V , typename T , typename BinaryOperation >
std::enable_if_t<(is_group_helper_v< GroupHelper >), T > reduce_over_group (GroupHelper group_helper, V x, T init, BinaryOperation binary_op)
template<typename GroupHelper , typename Ptr , typename BinaryOperation >
std::enable_if_t<(is_group_helper_v< GroupHelper > &&sycl::detail::is_pointer_v< Ptr >), typename std::iterator_traits< Ptr >::value_type > joint_reduce (GroupHelper group_helper, Ptr first, Ptr last, BinaryOperation binary_op)
template<typename GroupHelper , typename Ptr , typename T , typename BinaryOperation >
std::enable_if_t<(is_group_helper_v< GroupHelper > &&sycl::detail::is_pointer_v< Ptr >), T > joint_reduce (GroupHelper group_helper, Ptr first, Ptr last, T init, BinaryOperation binary_op)
template<int Dims>
__SYCL_DEPRECATED ("use sycl::ext::oneapi::this_work_item::get_nd_item() instead") nd_item< Dims > this_nd_item()
template<int Dims>
__SYCL_DEPRECATED ("use sycl::ext::oneapi::this_work_item::get_work_group() instead") group< Dims > this_group()
__SYCL_DEPRECATED ("use sycl::ext::oneapi::this_work_item::get_sub_group() instead") inline sycl
template<int Dims>
__SYCL_DEPRECATED ("use nd_range kernel and " "sycl::ext::oneapi::this_work_item::get_nd_item() instead") item< Dims > this_item()
template<typename PropertyT , typename... A, typename... B>
constexpr std::enable_if_t< detail::IsCompileTimeProperty< PropertyT >::value, bool > operator== (const property_value< PropertyT, A... > &, const property_value< PropertyT, B... > &)
template<typename PropertyT , typename... A, typename... B>
constexpr std::enable_if_t< detail::IsCompileTimeProperty< PropertyT >::value, bool > operator!= (const property_value< PropertyT, A... > &, const property_value< PropertyT, B... > &)
size_t get_mem_granularity (const device &SyclDevice, const context &SyclContext, granularity_mode Mode=granularity_mode::recommended)
size_t get_mem_granularity (const context &SyclContext, granularity_mode Mode=granularity_mode::recommended)
uintptr_t reserve_virtual_mem (uintptr_t Start, size_t NumBytes, const context &SyclContext)
uintptr_t reserve_virtual_mem (size_t NumBytes, const context &SyclContext)
void free_virtual_mem (uintptr_t Ptr, size_t NumBytes, const context &SyclContext)
void set_access_mode (const void *Ptr, size_t NumBytes, address_access_mode Mode, const context &SyclContext)
address_access_mode get_access_mode (const void *Ptr, size_t NumBytes, const context &SyclContext)
void unmap (const void *Ptr, size_t NumBytes, const context &SyclContext)
bool is_source_kernel_bundle_supported (backend BE, source_language Language)
kernel_bundle< bundle_state::ext_oneapi_source > create_kernel_bundle_from_source (const context &SyclContext, source_language Language, const std::string &Source)
kernel_bundle< bundle_state::ext_oneapi_source > create_kernel_bundle_from_source (const context &SyclContext, source_language Language, const std::vector< std::byte > &Bytes)
template<typename PropertyListT = empty_properties_t, typename = std::enable_if_t< is_property_list_v<PropertyListT> && detail::all_props_are_keys_of< kernel_bundle<bundle_state::ext_oneapi_source>, PropertyListT>::value>>
kernel_bundle< bundle_state::executable > build (kernel_bundle< bundle_state::ext_oneapi_source > &SourceKB, const std::vector< device > &Devices, PropertyListT props={})
template<typename PropertyListT = empty_properties_t, typename = std::enable_if_t< is_property_list_v<PropertyListT> && detail::all_props_are_keys_of< kernel_bundle<bundle_state::ext_oneapi_source>, PropertyListT>::value>>
kernel_bundle< bundle_state::executable > build (kernel_bundle< bundle_state::ext_oneapi_source > &SourceKB, PropertyListT props={})
void prepare_for_device_copy (const void *Ptr, size_t Size, const context &Context)
void prepare_for_device_copy (const void *Ptr, size_t Size, const queue &Queue)
void release_from_device_copy (const void *Ptr, const context &Context)
void release_from_device_copy (const void *Ptr, const queue &Queue)
void populate_pi_structs (const image_descriptor &desc, pi_image_desc &piDesc, pi_image_format &piFormat, size_t pitch=0)
image_mem_handle alloc_mipmap_mem (const image_descriptor &desc, const sycl::queue &syclQueue)
template<>
interop_mem_handle import_external_memory< resource_fd > (external_mem_descriptor< resource_fd > externalMem, const sycl::device &syclDevice, const sycl::context &syclContext)
template<>
interop_mem_handle import_external_memory< resource_fd > (external_mem_descriptor< resource_fd > externalMem, const sycl::queue &syclQueue)
template<>
interop_mem_handle import_external_memory< resource_win32_handle > (external_mem_descriptor< resource_win32_handle > externalMem, const sycl::device &syclDevice, const sycl::context &syclContext)
template<>
interop_mem_handle import_external_memory< external_mem_fd > (external_mem_descriptor< external_mem_fd > externalMem, const sycl::device &syclDevice, const sycl::context &syclContext)
template<>
interop_mem_handle import_external_memory< external_mem_fd > (external_mem_descriptor< external_mem_fd > externalMem, const sycl::queue &syclQueue)
template<>
interop_mem_handle import_external_memory< resource_win32_handle > (external_mem_descriptor< resource_win32_handle > externalMem, const sycl::queue &syclQueue)
template<>
interop_semaphore_handle import_external_semaphore (external_semaphore_descriptor< resource_fd > externalSemaphoreDesc, const sycl::device &syclDevice, const sycl::context &syclContext)
template<>
interop_semaphore_handle import_external_semaphore (external_semaphore_descriptor< resource_fd > externalSemaphoreDesc, const sycl::queue &syclQueue)
template<>
interop_semaphore_handle import_external_semaphore (external_semaphore_descriptor< resource_win32_handle > externalSemaphoreDesc, const sycl::device &syclDevice, const sycl::context &syclContext)
template<>
interop_semaphore_handle import_external_semaphore (external_semaphore_descriptor< resource_win32_handle > externalSemaphoreDesc, const sycl::queue &syclQueue)
template<>
interop_semaphore_handle import_external_semaphore (external_semaphore_descriptor< external_semaphore_fd > externalSemaphoreDesc, const sycl::device &syclDevice, const sycl::context &syclContext)
template<>
interop_semaphore_handle import_external_semaphore (external_semaphore_descriptor< external_semaphore_fd > externalSemaphoreDesc, const sycl::queue &syclQueue)
Variables
template<class T >
constexpr bool is_fixed_topology_group_v
template<class T >
constexpr bool is_user_constructed_group_v
template<class T >
constexpr bool is_group_helper_v
const CoordT & coords
const CoordT const float level
const CoordT const CoordT & dX
const CoordT const CoordT const CoordT & dY
constexpr device_image_scope_key::value_t device_image_scope
template<host_access_enum Access>
constexpr host_access_key::value_t< Access > host_access
constexpr host_access_key::value_t< host_access_enum::read > host_access_read
constexpr host_access_key::value_t< host_access_enum::write > host_access_write
constexpr host_access_key::value_t< host_access_enum::read_write > host_access_read_write
constexpr host_access_key::value_t< host_access_enum::none > host_access_none
template<init_mode_enum Trigger>
constexpr init_mode_key::value_t< Trigger > init_mode
constexpr init_mode_key::value_t< init_mode_enum::reprogram > init_mode_reprogram
constexpr init_mode_key::value_t< init_mode_enum::reset > init_mode_reset
template<bool Enable>
constexpr implement_in_csr_key::value_t< Enable > implement_in_csr
constexpr implement_in_csr_key::value_t< true > implement_in_csr_on
constexpr implement_in_csr_key::value_t< false > implement_in_csr_off
T * obj
static constexpr bool is_valid_property_list
static constexpr bool contains_valid_properties
static constexpr bool hasValidFPGAProperties
static constexpr bool hasConduitAndRegisterMapProperties
static constexpr bool is_device_copyable = is_device_copyable_v<T>
static constexpr bool has_buffer_location
static constexpr bool has_awidth = has_property<awidth_key>()
static constexpr bool has_dwidth = has_property<dwidth_key>()
static constexpr bool has_latency = has_property<latency_key>()
static constexpr bool has_read_write_mode
static constexpr bool has_maxburst = has_property<maxburst_key>()
static constexpr bool has_wait_request = has_property<wait_request_key>()
static constexpr bool has_alignment = has_property<alignment_key>()
static constexpr bool has_usm_kind = has_property<usm_kind_key>()
T * m_Ptr
static constexpr bool is_valid_property_list
static constexpr bool contains_valid_properties
static constexpr bool hasValidFPGAProperties
static constexpr bool hasConduitAndRegisterMapProperties
template<sycl::usm::alloc Kind>
constexpr usm_kind_key::value_t< Kind > usm_kind
constexpr usm_kind_key::value_t< sycl::usm::alloc::device > usm_kind_device
constexpr usm_kind_key::value_t< sycl::usm::alloc::host > usm_kind_host
constexpr usm_kind_key::value_t< sycl::usm::alloc::shared > usm_kind_shared
template<typename T >
constexpr bool is_vec_or_swizzle_bf16_v
template<typename T >
constexpr int num_elements_v = sycl::detail::num_elements<T>::value
template<int K>
constexpr alignment_key::value_t< K > alignment
template<group_algorithm_data_placement Placement>
constexpr input_data_placement_key::value_t< Placement > input_data_placement
template<group_algorithm_data_placement Placement>
constexpr output_data_placement_key::value_t< Placement > output_data_placement
template<data_placement_enum Placement>
constexpr data_placement_key::value_t< Placement > data_placement
constexpr data_placement_key::value_t< data_placement_enum::blocked > data_placement_blocked
constexpr data_placement_key::value_t< data_placement_enum::striped > data_placement_striped
constexpr contiguous_memory_key::value_t contiguous_memory
constexpr full_group_key::value_t full_group
template<cache_level Level, typename Hint >
constexpr prefetch_hint_key::value_t< Level, Hint > prefetch_hint
constexpr prefetch_hint_key::value_t< cache_level::L1, void > prefetch_hint_L1
constexpr prefetch_hint_key::value_t< cache_level::L2, void > prefetch_hint_L2
constexpr prefetch_hint_key::value_t< cache_level::L3, void > prefetch_hint_L3
constexpr prefetch_hint_key::value_t< cache_level::L4, void > prefetch_hint_L4
constexpr prefetch_hint_key::value_t< cache_level::L1, nontemporal > prefetch_hint_L1_nt
constexpr prefetch_hint_key::value_t< cache_level::L2, nontemporal > prefetch_hint_L2_nt
constexpr prefetch_hint_key::value_t< cache_level::L3, nontemporal > prefetch_hint_L3_nt
constexpr prefetch_hint_key::value_t< cache_level::L4, nontemporal > prefetch_hint_L4_nt
constexpr use_root_sync_key::value_t use_root_sync
template<typename Set = void>
constexpr indirectly_callable_key::value_t< Set > indirectly_callable
template<typename First = void, typename... Rest>
constexpr calls_indirectly_key::value_t< First, Rest... > calls_indirectly
template<size_t Dim0, size_t... Dims>
constexpr work_group_size_key::value_t< Dim0, Dims... > work_group_size
template<size_t Dim0, size_t... Dims>
constexpr work_group_size_hint_key::value_t< Dim0, Dims... > work_group_size_hint
template<uint32_t Size>
constexpr sub_group_size_key::value_t< Size > sub_group_size
template<aspect... Aspects>
constexpr device_has_key::value_t< Aspects... > device_has
template<int Dims>
constexpr nd_range_kernel_key::value_t< Dims > nd_range_kernel
constexpr single_task_kernel_key::value_t single_task_kernel
template<forward_progress_guarantee Guarantee, execution_scope CoordinationScope>
constexpr work_group_progress_key::value_t< Guarantee, CoordinationScope > work_group_progress
template<forward_progress_guarantee Guarantee, execution_scope CoordinationScope>
constexpr sub_group_progress_key::value_t< Guarantee, CoordinationScope > sub_group_progress
template<forward_progress_guarantee Guarantee, execution_scope CoordinationScope>
constexpr work_item_progress_key::value_t< Guarantee, CoordinationScope > work_item_progress
constexpr cl_version opencl_c_1_0 = {1, 0, 0}
constexpr cl_version opencl_c_1_1 = {1, 1, 0}
constexpr cl_version opencl_c_1_2 = {1, 2, 0}
constexpr cl_version opencl_c_2_0 = {2, 0, 0}
constexpr cl_version opencl_c_3_0 = {3, 0, 0}
Typedef Documentation
awidth_key
using sycl::_V1::ext::oneapi::experimental::awidth_key = typedef intel::experimental::awidth_key
Definition at line 140 of file fpga_annotated_properties.hpp.
buffer_location_key
using sycl::_V1::ext::oneapi::experimental::buffer_location_key = typedef intel::experimental::buffer_location_key
Definition at line 139 of file fpga_annotated_properties.hpp.
build_options_key
using sycl::_V1::ext::oneapi::experimental::build_options_key = typedef build_options
Definition at line 826 of file kernel_bundle.hpp.
CheckDevicePtrTAndPropLists
template<typename T , typename ListA , typename ListB > using sycl::_V1::ext::oneapi::experimental::CheckDevicePtrTAndPropLists = typedef typename detail::CheckTAndPropListsWithUsmKind<sycl::usm::alloc::device, T, ListA, ListB>
Definition at line 20 of file alloc_device.hpp.
CheckHostPtrTAndPropLists
template<typename T , typename ListA , typename ListB > using sycl::_V1::ext::oneapi::experimental::CheckHostPtrTAndPropLists = typedef typename detail::CheckTAndPropListsWithUsmKind<sycl::usm::alloc::host, T, ListA, ListB>
Definition at line 20 of file alloc_host.hpp.
CheckSharedPtrTAndPropLists
template<typename T , typename ListA , typename ListB > using sycl::_V1::ext::oneapi::experimental::CheckSharedPtrTAndPropLists = typedef typename detail::CheckTAndPropListsWithUsmKind<sycl::usm::alloc::shared, T, ListA, ListB>
Definition at line 20 of file alloc_shared.hpp.
conduit_key
using sycl::_V1::ext::oneapi::experimental::conduit_key = typedef intel::experimental::conduit_key
Definition at line 137 of file fpga_annotated_properties.hpp.
dwidth_key
using sycl::_V1::ext::oneapi::experimental::dwidth_key = typedef intel::experimental::dwidth_key
Definition at line 141 of file fpga_annotated_properties.hpp.
empty_properties_t
using sycl::_V1::ext::oneapi::experimental::empty_properties_t = typedef properties<std::tuple<> >
Definition at line 234 of file properties.hpp.
exe_kb
using sycl::_V1::ext::oneapi::experimental::exe_kb = typedef kernel_bundle<bundle_state::executable>
Definition at line 362 of file kernel_bundle.cpp.
GetAnnotatedDevicePtrProperties
template<typename PropertyListT > using sycl::_V1::ext::oneapi::experimental::GetAnnotatedDevicePtrProperties = typedef detail::GetAnnotatedPtrPropertiesWithUsmKind<sycl::usm::alloc::device, PropertyListT>
Definition at line 25 of file alloc_device.hpp.
GetAnnotatedHostPtrProperties
template<typename PropertyListT > using sycl::_V1::ext::oneapi::experimental::GetAnnotatedHostPtrProperties = typedef detail::GetAnnotatedPtrPropertiesWithUsmKind<sycl::usm::alloc::host, PropertyListT>
Definition at line 25 of file alloc_host.hpp.
GetAnnotatedSharedPtrProperties
template<typename PropertyListT > using sycl::_V1::ext::oneapi::experimental::GetAnnotatedSharedPtrProperties = typedef detail::GetAnnotatedPtrPropertiesWithUsmKind<sycl::usm::alloc::shared, PropertyListT>
Definition at line 25 of file alloc_shared.hpp.
global_pointer_t
typedef typename decorated_global_ptr< T >::pointer sycl::_V1::ext::oneapi::experimental::global_pointer_t
Definition at line 100 of file annotated_arg.hpp.
kernel_bundle_impl
using sycl::_V1::ext::oneapi::experimental::kernel_bundle_impl = typedef sycl::detail::kernel_bundle_impl
Definition at line 363 of file kernel_bundle.cpp.
latency_key
using sycl::_V1::ext::oneapi::experimental::latency_key = typedef intel::experimental::latency_key
Definition at line 142 of file fpga_annotated_properties.hpp.
maxburst_key
using sycl::_V1::ext::oneapi::experimental::maxburst_key = typedef intel::experimental::maxburst_key
Definition at line 144 of file fpga_annotated_properties.hpp.
property_list_t
using sycl::_V1::ext::oneapi::experimental::property_list_t = typedef detail::properties_t<Props...>
Definition at line 270 of file annotated_ptr.hpp.
read_write_mode_enum
using sycl::_V1::ext::oneapi::experimental::read_write_mode_enum = typedef intel::experimental::read_write_mode_enum
Definition at line 146 of file fpga_annotated_properties.hpp.
read_write_mode_key
using sycl::_V1::ext::oneapi::experimental::read_write_mode_key = typedef intel::experimental::read_write_mode_key
Definition at line 143 of file fpga_annotated_properties.hpp.
reference
using sycl::_V1::ext::oneapi::experimental::reference = typedef sycl::ext::oneapi::experimental::annotated_ref<T, property_list_t>
Definition at line 273 of file annotated_ptr.hpp.
register_map_key
using sycl::_V1::ext::oneapi::experimental::register_map_key = typedef intel::experimental::register_map_key
Definition at line 136 of file fpga_annotated_properties.hpp.
save_log_key
using sycl::_V1::ext::oneapi::experimental::save_log_key = typedef save_log
Definition at line 840 of file kernel_bundle.hpp.
simd
template<class T , int N> using sycl::_V1::ext::oneapi::experimental::simd = typedef std::experimental::simd<T, simd_abi::native_fixed_size<T, N> >
Definition at line 38 of file invoke_simd_types.hpp.
simd_mask
template<class T , int N> using sycl::_V1::ext::oneapi::experimental::simd_mask = typedef std::experimental::simd_mask<T, simd_abi::native_fixed_size<T, N> >
This is basically an alias of the detail::simd_mask_impl class.
Definition at line 42 of file invoke_simd_types.hpp.
source_kb
using sycl::_V1::ext::oneapi::experimental::source_kb = typedef kernel_bundle<sycl::bundle_state::ext_oneapi_source>
Definition at line 361 of file kernel_bundle.cpp.
stable_key
using sycl::_V1::ext::oneapi::experimental::stable_key = typedef intel::experimental::stable_key
Definition at line 138 of file fpga_annotated_properties.hpp.
UnderlyingT
using sycl::_V1::ext::oneapi::experimental::UnderlyingT = typedef T
Definition at line 233 of file annotated_arg.hpp.
wait_request_key
using sycl::_V1::ext::oneapi::experimental::wait_request_key = typedef intel::experimental::wait_request_key
Definition at line 145 of file fpga_annotated_properties.hpp.
Enumeration Type Documentation
address_access_mode
enum sycl::_V1::ext::oneapi::experimental::address_access_mode : char strong
Enumerator
none
read
read_write
Definition at line 27 of file physical_mem.hpp.
arch_category
enum sycl::_V1::ext::oneapi::experimental::arch_category strong
Enumerator
intel_gpu
nvidia_gpu
amd_gpu
Definition at line 27 of file device_architecture.hpp.
architecture
enum sycl::_V1::ext::oneapi::experimental::architecture : uint64_t strong
Enumerator
__SYCL_ARCHITECTURE
__SYCL_ARCHITECTURE_ALIAS
Definition at line 19 of file device_architecture.hpp.
cache_level
enum sycl::_V1::ext::oneapi::experimental::cache_level strong
Enumerator
L1
L2
L3
L4
Definition at line 19 of file prefetch.hpp.
cubemap_filtering_mode
enum sycl::_V1::ext::oneapi::experimental::cubemap_filtering_mode : unsigned int strong
cubemap filtering mode enum
Enumerator
disjointed
seamless
Definition at line 18 of file bindless_images_sampler.hpp.
data_placement_enum
enum sycl::_V1::ext::oneapi::experimental::data_placement_enum strong
Enumerator
blocked
striped
Definition at line 23 of file group_load_store.hpp.
execution_scope
enum sycl::_V1::ext::oneapi::experimental::execution_scope strong
Enumerator
work_item
sub_group
work_group
root_group
Definition at line 19 of file forward_progress.hpp.
external_mem_handle_type
enum sycl::_V1::ext::oneapi::experimental::external_mem_handle_type strong
Enumerator
opaque_fd
win32_nt_handle
win32_nt_dx12_resource
Definition at line 20 of file bindless_images_interop.hpp.
external_semaphore_handle_type
enum sycl::_V1::ext::oneapi::experimental::external_semaphore_handle_type strong
Enumerator
opaque_fd
win32_nt_handle
win32_nt_dx12_fence
Definition at line 27 of file bindless_images_interop.hpp.
forward_progress_guarantee
enum sycl::_V1::ext::oneapi::experimental::forward_progress_guarantee strong
Enumerator
concurrent
parallel
weakly_parallel
Definition at line 17 of file forward_progress.hpp.
granularity_mode
enum sycl::_V1::ext::oneapi::experimental::granularity_mode : char strong
Enumerator
minimum
recommended
Definition at line 24 of file virtual_mem.hpp.
graph_state
enum sycl::_V1::ext::oneapi::experimental::graph_state strong
State to template the command_graph class on.
Enumerator
modifiable
In modifiable state, commands can be added to graph.
executable
In executable state, the graph is ready to execute.
Definition at line 37 of file graph.hpp.
group_algorithm_data_placement
enum sycl::_V1::ext::oneapi::experimental::group_algorithm_data_placement strong
Enumerator
blocked
striped
Definition at line 40 of file group_helpers_sorters.hpp.
host_access_enum
enum sycl::_V1::ext::oneapi::experimental::host_access_enum : std::uint16_t strong
Enumerator
read
write
read_write
none
Definition at line 29 of file properties.hpp.
image_copy_flags
enum sycl::_V1::ext::oneapi::experimental::image_copy_flags : unsigned int
Direction to copy data from bindless image handle (Host -> Device) (Device -> Host) etc.
Enumerator
HtoD
DtoH
DtoD
Definition at line 101 of file bindless_images_memory.hpp.
image_type
enum sycl::_V1::ext::oneapi::experimental::image_type : unsigned int strong
image type enum
Enumerator
standard
mipmap
array
cubemap
Definition at line 44 of file bindless_images_descriptor.hpp.
init_mode_enum
enum sycl::_V1::ext::oneapi::experimental::init_mode_enum : std::uint16_t strong
Enumerator
reprogram
reset
Definition at line 39 of file properties.hpp.
node_type
enum sycl::_V1::ext::oneapi::experimental::node_type strong
Enumerator
empty
subgraph
kernel
memcpy
memset
memfill
prefetch
memadvise
ext_oneapi_barrier
host_task
Definition at line 91 of file graph.hpp.
sorting_order
enum sycl::_V1::ext::oneapi::experimental::sorting_order strong
Enumerator
ascending
descending
Definition at line 158 of file group_helpers_sorters.hpp.
source_language
enum sycl::_V1::ext::oneapi::experimental::source_language : int strong
Enumerator
opencl
spirv
Definition at line 23 of file kernel_bundle_enums.hpp.
Function Documentation
__attribute__()
template<class Callable , class... T> sycl::_V1::ext::oneapi::experimental::__attribute__ ((always_inline))
The invoke_simd free function invokes a SIMD function using all work-items in a sub_group.
The invoke_simd interface marshals data between the SPMD context of the calling kernel and the SIMD context of the callee, converting arguments and return values between scalar and SIMD types as appropriate.
Parameters
sg the subgroup simd function is invoked from
f represents the invoked simd function. Must be a C++ callable that can be invoked with the same number of arguments specified in the args parameter pack. Callable may be a function object, a lambda, or a function pointer (if the device supports SPV_INTEL_function_pointers). Callable must be an immutable callable with the same type and state for all work-items in the sub-group, otherwise behavior is undefined.
args SPMD parameters to the invoked function, which undergo transformation before actual passing to the simd function, as described in the specification.
Definition at line 464 of file invoke_simd.hpp.
References __builtin_invoke_simd(), sycl::_V1::ext::oneapi::experimental::detail::get_sg_size(), sycl::_V1::ext::oneapi::experimental::detail::unwrap_uniform< T >::impl(), sycl::_V1::ext::oneapi::experimental::detail::simd_func_call_helper(), sycl::_V1::ext::oneapi::experimental::detail::simd_obj_call_helper(), sycl::_V1::ext::oneapi::experimental::detail::verify_return_type_matches_sg_size(), and sycl::_V1::ext::oneapi::experimental::detail::verify_valid_args_and_ret().
Referenced by sycl::_V1::ext::oneapi::group_local_memory(), sycl::_V1::ext::oneapi::group_local_memory_for_overwrite(), and sycl::_V1::ext::oneapi::experimental::detail::prefetch_impl().
__SYCL_DEPRECATED() [1/8]
template<typename DataT , typename HintT = DataT, typename CoordT > sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED ("read_image for mipmaps is deprecated. " "Instead use sample_mipmap.") const &
[Deprecated] Read a mipmap image using its handle with LOD filtering
[Deprecated] Read a mipmap image using its handle with anisotropic filtering
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. float, float2, or float3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The mipmap image handle
coords The coordinates at which to sample mipmap image data
level The mipmap level at which to sample
Returns
Mipmap image data with LOD filtering
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. float, float2, or float3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The mipmap image handle
coords The coordinates at which to fetch mipmap image data
dX Screen space gradient in the x dimension
dY Screen space gradient in the y dimension
Returns
Mipmap image data with anisotropic filtering
References coords, and level.
__SYCL_DEPRECATED() [2/8]
template<typename DataT , typename HintT = DataT, typename CoordT > sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED ("read_image for standard sampled images is deprecated. " "Instead use sample_image with floating point coordinates or " "fetch_image with integer coordinates.") const &
[Deprecated] Read a sampled image using its handle
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. float, float2, or float3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The image handle
coords The coordinates at which to sample image data
Returns
Sampled image data
NVPTX: Name mangling info Cuda surfaces require integer coords (by bytes) Cuda textures require float coords (by element or normalized) for sampling, and integer coords (by bytes) for fetching The name mangling should therefore not interfere with one another
__SYCL_DEPRECATED() [3/8]
template<typename DataT , typename HintT = DataT, typename CoordT > sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED ("read_image for standard unsampled images is deprecated. " "Instead use fetch_image.") const &
[Deprecated] Read an unsampled image using its handle
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. int, int2, or int3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The image handle
coords The coordinates at which to fetch image data
Returns
Image data
NVPTX: Name mangling info Cuda surfaces require integer coords (by bytes) Cuda textures require float coords (by element or normalized) for sampling, and integer coords (by bytes) for fetching The name mangling should therefore not interfere with one another
__SYCL_DEPRECATED() [4/8]
template<typename DataT , typename HintT = DataT, typename CoordT > sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED ("read_mipmap has been deprecated. " "Instead use sample_mipmap.") const &
[Deprecated] Read a mipmap image using its handle with LOD filtering
[Deprecated] Read a mipmap image using its handle with anisotropic filtering
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. float, float2, or float3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The mipmap image handle
coords The coordinates at which to sample mipmap image data
level The mipmap level at which to sample
Returns
Mipmap image data with LOD filtering
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. float, float2, or float3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The mipmap image handle
coords The coordinates at which to sample mipmap image data
dX Screen space gradient in the x dimension
dY Screen space gradient in the y dimension
Returns
Mipmap image data with anisotropic filtering
__SYCL_DEPRECATED() [5/8]
template<int Dims> sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED ("use nd_range kernel and " "sycl::ext::oneapi::this_work_item::get_nd_item() instead")
Definition at line 70 of file free_function_queries.hpp.
References sycl::_V1::detail::declptr().
__SYCL_DEPRECATED() [6/8]
template<int Dims> sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED ("use sycl::ext::oneapi::this_work_item::get_nd_item() instead")
Definition at line 50 of file free_function_queries.hpp.
__SYCL_DEPRECATED() [7/8]
sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED ("use sycl::ext::oneapi::this_work_item::get_sub_group() instead")
Definition at line 63 of file free_function_queries.hpp.
References sycl::_V1::ext::oneapi::this_work_item::get_sub_group().
__SYCL_DEPRECATED() [8/8]
template<int Dims> sycl::_V1::ext::oneapi::experimental::__SYCL_DEPRECATED ("use sycl::ext::oneapi::this_work_item::get_work_group() instead")
Definition at line 57 of file free_function_queries.hpp.
__SYCL_TYPE() [1/2]
template<typename T , typename... Props> class __SYCL_SPECIAL_CLASS sycl::_V1::ext::oneapi::experimental::__SYCL_TYPE (annotated_arg)
__SYCL_TYPE() [2/2]
template<typename T , typename... Props> class __SYCL_SPECIAL_CLASS sycl::_V1::ext::oneapi::experimental::__SYCL_TYPE (annotated_ptr)
abs()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, _Tp> sycl::_V1::ext::oneapi::experimental::abs (const complex< _Tp > & __c)
FUNCTIONS.
Definition at line 122 of file complex_math.hpp.
Referenced by log(), and sqrt().
acos()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::acos (const complex< _Tp > & __x)
Definition at line 525 of file complex_math.hpp.
References sycl::_V1::ext::oneapi::experimental::cplx::detail::__sqr(), sycl::_V1::ext::oneapi::fabs(), isnan(), log(), and sqrt().
acosh()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::acosh (const complex< _Tp > & __x)
Definition at line 390 of file complex_math.hpp.
References sycl::_V1::ext::oneapi::experimental::cplx::detail::__sqr(), sycl::_V1::ext::intel::math::copysign(), sycl::_V1::ext::oneapi::fabs(), isnan(), log(), and sqrt().
aligned_alloc_annotated() [1/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_annotated (size_t alignment, size_t count, const device & syclDevice, const context & syclContext, sycl::usm::alloc kind, const propertyListA & propList = propertyListA{})
Definition at line 86 of file alloc_base.hpp.
aligned_alloc_annotated() [2/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_annotated (size_t alignment, size_t count, const queue & syclQueue, sycl::usm::alloc kind, const propertyListA & propList = propertyListA{})
Definition at line 141 of file alloc_base.hpp.
aligned_alloc_annotated() [3/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_annotated (size_t alignment, size_t numBytes, const device & syclDevice, const context & syclContext, sycl::usm::alloc kind, const propertyListA & propList = propertyListA{})
Definition at line 44 of file alloc_base.hpp.
aligned_alloc_annotated() [4/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_annotated (size_t alignment, size_t numBytes, const queue & syclQueue, sycl::usm::alloc kind, const propertyListA & propList = propertyListA{})
Definition at line 128 of file alloc_base.hpp.
aligned_alloc_device_annotated() [1/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type> std::enable_if_t< CheckDevicePtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_device_annotated (size_t alignment, size_t count, const device & syclDevice, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 62 of file alloc_device.hpp.
aligned_alloc_device_annotated() [2/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type> std::enable_if_t< CheckDevicePtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_device_annotated (size_t alignment, size_t count, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 92 of file alloc_device.hpp.
aligned_alloc_device_annotated() [3/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type> std::enable_if_t< CheckDevicePtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_device_annotated (size_t alignment, size_t numBytes, const device & syclDevice, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 46 of file alloc_device.hpp.
aligned_alloc_device_annotated() [4/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type> std::enable_if_t< CheckDevicePtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_device_annotated (size_t alignment, size_t numBytes, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 78 of file alloc_device.hpp.
aligned_alloc_host_annotated() [1/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type> std::enable_if_t< CheckHostPtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_host_annotated (size_t alignment, size_t count, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 61 of file alloc_host.hpp.
aligned_alloc_host_annotated() [2/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type> std::enable_if_t< CheckHostPtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_host_annotated (size_t alignment, size_t count, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 88 of file alloc_host.hpp.
aligned_alloc_host_annotated() [3/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type> std::enable_if_t< CheckHostPtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_host_annotated (size_t alignment, size_t numBytes, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 47 of file alloc_host.hpp.
aligned_alloc_host_annotated() [4/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type> std::enable_if_t< CheckHostPtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_host_annotated (size_t alignment, size_t numBytes, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 75 of file alloc_host.hpp.
aligned_alloc_shared_annotated() [1/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type> std::enable_if_t< CheckSharedPtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_shared_annotated (size_t alignment, size_t count, const device & syclDevice, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 62 of file alloc_shared.hpp.
aligned_alloc_shared_annotated() [2/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type> std::enable_if_t< CheckSharedPtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_shared_annotated (size_t alignment, size_t count, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 92 of file alloc_shared.hpp.
aligned_alloc_shared_annotated() [3/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type> std::enable_if_t< CheckSharedPtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_shared_annotated (size_t alignment, size_t numBytes, const device & syclDevice, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 46 of file alloc_shared.hpp.
aligned_alloc_shared_annotated() [4/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type> std::enable_if_t< CheckSharedPtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::aligned_alloc_shared_annotated (size_t alignment, size_t numBytes, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 78 of file alloc_shared.hpp.
aligned_private_alloca()
template<typename ElementType , std::size_t Alignment, auto & SizeSpecName, access::decorated DecorateAddress> private_ptr<ElementType, DecorateAddress> sycl::_V1::ext::oneapi::experimental::aligned_private_alloca (kernel_handler & kh)
Definition at line 72 of file alloca.hpp.
alloc_image_mem() [1/2]
image_mem_handle sycl::_V1::ext::oneapi::experimental::alloc_image_mem (const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
Allocate image memory based on image_descriptor.
Parameters
desc The image descriptor
syclDevice The device in which we create our memory handle
syclContext The context in which we create our memory handle
Returns
Memory handle to allocated memory on the device
Definition at line 161 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextMemImageAllocate(), populate_pi_structs(), sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, and sycl::_V1::ext::oneapi::experimental::image_descriptor::verify().
Referenced by alloc_image_mem(), and sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl::image_mem_impl().
alloc_image_mem() [2/2]
image_mem_handle sycl::_V1::ext::oneapi::experimental::alloc_image_mem (const image_descriptor & desc, const sycl::queue & syclQueue)
Allocate image memory based on image_descriptor.
Parameters
desc The image descriptor
syclQueue The queue in which we create our memory handle
Returns
Memory handle to allocated memory on the device
Definition at line 187 of file bindless_images.cpp.
References alloc_image_mem(), sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
alloc_mipmap_mem() [1/3]
image_mem_handle sycl::_V1::ext::oneapi::experimental::alloc_mipmap_mem (const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
[Deprecated] Allocate mipmap memory based on image_descriptor
Parameters
desc The image descriptor
syclDevice The device in which we create our memory handle
syclContext The context in which we create our memory handle
Returns
Memory handle to allocated memory on the device
Definition at line 194 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextMemImageAllocate(), populate_pi_structs(), and sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle.
Referenced by alloc_mipmap_mem().
alloc_mipmap_mem() [2/3]
image_mem_handle sycl::_V1::ext::oneapi::experimental::alloc_mipmap_mem (const image_descriptor & desc, const sycl::device & syclQueue)
[Deprecated] Allocate mipmap memory based on image_descriptor
Parameters
desc The image descriptor
syclQueue The queue in which we create our memory handle
Returns
Memory handle to allocated memory on the device
alloc_mipmap_mem() [3/3]
image_mem_handle sycl::_V1::ext::oneapi::experimental::alloc_mipmap_mem (const image_descriptor & desc, const sycl::queue & syclQueue)
Definition at line 222 of file bindless_images.cpp.
References alloc_mipmap_mem().
annotated_arg() [1/9]
template<typename T , typename old , typename... ArgT> sycl::_V1::ext::oneapi::experimental::annotated_arg (annotated_arg< T, old > , properties< std::tuple< ArgT... >>) -> annotated_arg< T, detail::merged_properties_t< old, detail::properties_t< ArgT... >>>
annotated_arg() [2/9]
sycl::_V1::ext::oneapi::experimental::annotated_arg (const annotated_arg &) default
annotated_arg() [3/9]
template<typename T2 , typename PropertyList2 > sycl::_V1::ext::oneapi::experimental::annotated_arg (const annotated_arg< T2, PropertyList2 > & other) explicit noexcept
Definition at line 143 of file annotated_arg.hpp.
annotated_arg() [4/9]
template<typename T2 , typename PropertyListU , typename PropertyListV > sycl::_V1::ext::oneapi::experimental::annotated_arg (const annotated_arg< T2, PropertyListU > & other, const PropertyListV & proplist) explicit noexcept
Definition at line 165 of file annotated_arg.hpp.
annotated_arg() [5/9]
sycl::_V1::ext::oneapi::experimental::annotated_arg (const T & _obj, const property_list_t & PropList = property_list_t{}) noexcept
Definition at line 252 of file annotated_arg.hpp.
annotated_arg() [6/9]
template<typename... PropertyValueTs> sycl::_V1::ext::oneapi::experimental::annotated_arg (const T & _obj, PropertyValueTs... props) noexcept
Definition at line 263 of file annotated_arg.hpp.
annotated_arg() [7/9]
sycl::_V1::ext::oneapi::experimental::annotated_arg (T * _ptr, const property_list_t & PropList = property_list_t{}) noexcept
Definition at line 116 of file annotated_arg.hpp.
annotated_arg() [8/9]
template<typename... PropertyValueTs> sycl::_V1::ext::oneapi::experimental::annotated_arg (T * _ptr, const PropertyValueTs &... props) noexcept
Definition at line 127 of file annotated_arg.hpp.
annotated_arg() [9/9]
template<typename T , typename... Args> sycl::_V1::ext::oneapi::experimental::annotated_arg (T , Args...) -> annotated_arg< T, typename detail::DeducedProperties< Args... >::type >
annotated_ptr() [1/5]
sycl::_V1::ext::oneapi::experimental::annotated_ptr (const annotated_ptr &) default
annotated_ptr() [2/5]
template<typename T2 , typename PropertyList2 > sycl::_V1::ext::oneapi::experimental::annotated_ptr (const annotated_ptr< T2, PropertyList2 > & other) explicit noexcept
Definition at line 332 of file annotated_ptr.hpp.
annotated_ptr() [3/5]
template<typename T2 , typename PropertyListU , typename PropertyListV > sycl::_V1::ext::oneapi::experimental::annotated_ptr (const annotated_ptr< T2, PropertyListU > & other, const PropertyListV &) explicit noexcept
Definition at line 355 of file annotated_ptr.hpp.
annotated_ptr() [4/5]
sycl::_V1::ext::oneapi::experimental::annotated_ptr (T * Ptr, const property_list_t & = property_list_t{}) explicit noexcept
Definition at line 305 of file annotated_ptr.hpp.
annotated_ptr() [5/5]
template<typename... PropertyValueTs> sycl::_V1::ext::oneapi::experimental::annotated_ptr (T * Ptr, const PropertyValueTs &... props) explicit noexcept
Definition at line 314 of file annotated_ptr.hpp.
arg() [1/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits<_Tp>::_ValueType sycl::_V1::ext::oneapi::experimental::arg (_Tp __re)
Definition at line 138 of file complex_math.hpp.
arg() [2/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, _Tp> sycl::_V1::ext::oneapi::experimental::arg (const complex< _Tp > & __c)
Definition at line 131 of file complex_math.hpp.
Referenced by log(), and sqrt().
asin()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::asin (const complex< _Tp > & __x)
Definition at line 515 of file complex_math.hpp.
References asinh().
asinh()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::asinh (const complex< _Tp > & __x)
Definition at line 360 of file complex_math.hpp.
References sycl::_V1::ext::oneapi::experimental::cplx::detail::__sqr(), sycl::_V1::ext::intel::math::copysign(), isnan(), log(), and sqrt().
Referenced by asin().
atan()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::atan (const complex< _Tp > & __x)
Definition at line 561 of file complex_math.hpp.
References atanh().
atanh()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::atanh (const complex< _Tp > & __x)
Definition at line 425 of file complex_math.hpp.
References sycl::_V1::ext::intel::math::copysign(), sycl::_V1::ext::oneapi::fabs(), isnan(), and log().
Referenced by atan().
auto_range()
template<int Dimensions> static range<Dimensions> sycl::_V1::ext::oneapi::experimental::auto_range () inline static
Definition at line 17 of file auto_local_range.hpp.
References sycl::_V1::Dimensions.
barrier() [1/2]
void sycl::_V1::ext::oneapi::experimental::barrier (handler & CGH) inline
Definition at line 335 of file enqueue_functions.hpp.
References sycl::_V1::handler::ext_oneapi_barrier().
Referenced by barrier().
barrier() [2/2]
void sycl::_V1::ext::oneapi::experimental::barrier (queue Q, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current()) inline
Definition at line 337 of file enqueue_functions.hpp.
References barrier(), and submit().
build() [1/2]
template<typename PropertyListT = empty_properties_t, typename = std::enable_if_t< is_property_list_v<PropertyListT> && detail::all_props_are_keys_of< kernel_bundle<bundle_state::ext_oneapi_source>, PropertyListT>::value>> kernel_bundle<bundle_state::executable> sycl::_V1::ext::oneapi::experimental::build (kernel_bundle< bundle_state::ext_oneapi_source > & SourceKB, const std::vector< device > & Devices, PropertyListT props = {})
Definition at line 890 of file kernel_bundle.hpp.
build() [2/2]
template<typename PropertyListT = empty_properties_t, typename = std::enable_if_t< is_property_list_v<PropertyListT> && detail::all_props_are_keys_of< kernel_bundle<bundle_state::ext_oneapi_source>, PropertyListT>::value>> kernel_bundle<bundle_state::executable> sycl::_V1::ext::oneapi::experimental::build (kernel_bundle< bundle_state::ext_oneapi_source > & SourceKB, PropertyListT props = {})
Definition at line 910 of file kernel_bundle.hpp.
combine_align()
size_t sycl::_V1::ext::oneapi::experimental::combine_align (size_t alignA, size_t alignB) inline
Definition at line 238 of file alloc_util.hpp.
command_graph()
template<graph_state State = graph_state::modifiable> sycl::_V1::ext::oneapi::experimental::command_graph (const context & SyclContext, const device & SyclDevice, const property_list & PropList) -> command_graph< State >
conj() [1/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits<_Tp>::_ComplexType sycl::_V1::ext::oneapi::experimental::conj (_Tp __re)
Definition at line 180 of file complex_math.hpp.
conj() [2/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::conj (const complex< _Tp > & __c)
Definition at line 173 of file complex_math.hpp.
copy() [1/2]
template<typename T > void sycl::_V1::ext::oneapi::experimental::copy (handler & CGH, const T * Src, T * Dest, size_t Count)
Definition at line 286 of file enqueue_functions.hpp.
References sycl::_V1::handler::copy().
Referenced by sycl::_V1::ext::oneapi::experimental::detail::modifiable_command_graph::get_root_nodes(), sycl::_V1::detail::pi::readELFValue(), and sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::set_final_data_internal().
copy() [2/2]
template<typename T > void sycl::_V1::ext::oneapi::experimental::copy (queue Q, const T * Src, T * Dest, size_t Count, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current())
Definition at line 291 of file enqueue_functions.hpp.
References submit().
cos()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::cos (const complex< _Tp > & __x)
Definition at line 581 of file complex_math.hpp.
References cosh().
cosh()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::cosh (const complex< _Tp > & __x)
Definition at line 473 of file complex_math.hpp.
References sycl::_V1::ext::oneapi::fabs(), and sinh().
Referenced by cos(), sinh(), and tanh().
create_image() [1/10]
sampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (image_mem & memHandle, const bindless_image_sampler & sampler, const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
Create a sampled image and return the device image handle.
Parameters
memHandle Device memory handle wrapper for allocated image memory
sampler bindless image sampler used to sample the image
desc The image descriptor
syclDevice The device in which we create our image handle
syclContext The context in which we create our image handle
Returns
Image handle to created image object on the device
Definition at line 397 of file bindless_images.cpp.
References create_image(), sycl::_V1::ext::oneapi::experimental::image_mem::get_handle(), and sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle.
create_image() [2/10]
sampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (image_mem & memHandle, const bindless_image_sampler & sampler, const image_descriptor & desc, const sycl::queue & syclQueue)
Create a sampled image and return the device image handle.
Parameters
memHandle Device memory handle wrapper for allocated image memory
sampler bindless image sampler used to sample the image
desc The image descriptor
syclQueue The queue in which we create our image handle
Returns
Image handle to created image object on the device
Definition at line 405 of file bindless_images.cpp.
References create_image(), sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), sycl::_V1::ext::oneapi::experimental::image_mem::get_handle(), and sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle.
create_image() [3/10]
unsampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (image_mem & memHandle, const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
Create an image and return the device image handle.
Parameters
memHandle Device memory handle wrapper for allocated image memory
desc The image descriptor
syclDevice The device in which we created our image handle
syclContext The context in which we create our image handle
Returns
Image handle to created image object on the device
Definition at line 336 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::image_mem::get_handle().
Referenced by create_image().
create_image() [4/10]
unsampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (image_mem & memHandle, const image_descriptor & desc, const sycl::queue & syclQueue)
Create an image and return the device image handle.
Parameters
memHandle Device memory handle wrapper for allocated image memory
desc The image descriptor
syclqueue The queue in which we created our image handle
Returns
Image handle to created image object on the device
Definition at line 342 of file bindless_images.cpp.
References create_image(), sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and sycl::_V1::ext::oneapi::experimental::image_mem::get_handle().
create_image() [5/10]
sampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (image_mem_handle memHandle, const bindless_image_sampler & sampler, const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
Create a sampled image and return the device image handle.
Parameters
memHandle Device memory handle for allocated image memory
sampler bindless image sampler used to sample the image
desc The image descriptor
syclDevice The device in which we create our image handle
syclContext The context in which we create our image handle
Returns
Image handle to created image object on the device
Definition at line 382 of file bindless_images.cpp.
References create_image(), and sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle.
create_image() [6/10]
sampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (image_mem_handle memHandle, const bindless_image_sampler & sampler, const image_descriptor & desc, const sycl::queue & syclQueue)
Create a sampled image and return the device image handle.
Parameters
memHandle Device memory handle for allocated image memory
sampler bindless image sampler used to sample the image
desc The image descriptor
syclQueue The queue in which we create our image handle
Returns
Image handle to created image object on the device
Definition at line 390 of file bindless_images.cpp.
References create_image(), sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
create_image() [7/10]
unsampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (image_mem_handle memHandle, const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
Create an image and return the device image handle.
Parameters
memHandle Device memory handle for allocated image memory
desc The image descriptor
syclDevice The device in which we created our image handle
syclContext The context in which we create our image handle
Returns
Image handle to created image object on the device
Definition at line 349 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextMemUnsampledImageCreate(), populate_pi_structs(), sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, and sycl::_V1::ext::oneapi::experimental::image_descriptor::verify().
create_image() [8/10]
unsampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (image_mem_handle memHandle, const image_descriptor & desc, const sycl::queue & syclQueue)
Create an image and return the device image handle.
Parameters
memHandle Device memory handle for allocated image memory
desc The image descriptor
syclQueue The queue in which we created our image handle
Returns
Image handle to created image object on the device
Definition at line 375 of file bindless_images.cpp.
References create_image(), sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
create_image() [9/10]
sampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (void * imgMem, size_t pitch, const bindless_image_sampler & sampler, const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
Create a sampled image and return the device image handle.
Parameters
imgMem Device memory pointer to allocated image memory
pitch The allocation pitch value
sampler bindless image sampler to sample the image
desc The image descriptor
syclDevice The device in which we create our image handle
syclContext The context in which we create our image handle
Returns
Image handle to created image object on the device
Definition at line 412 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::bindless_image_sampler::addressing, sycl::_V1::ext::oneapi::experimental::bindless_image_sampler::coordinate, sycl::_V1::ext::oneapi::experimental::bindless_image_sampler::cubemap_filtering, sycl::_V1::ext::oneapi::experimental::bindless_image_sampler::filtering, sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::ext::oneapi::experimental::bindless_image_sampler::max_anisotropy, sycl::_V1::ext::oneapi::experimental::bindless_image_sampler::max_mipmap_level_clamp, sycl::_V1::ext::oneapi::experimental::bindless_image_sampler::min_mipmap_level_clamp, sycl::_V1::ext::oneapi::experimental::bindless_image_sampler::mipmap_filtering, PI_SAMPLER_PROPERTIES_ADDRESSING_MODE, PI_SAMPLER_PROPERTIES_CUBEMAP_FILTER_MODE, PI_SAMPLER_PROPERTIES_FILTER_MODE, PI_SAMPLER_PROPERTIES_MIP_FILTER_MODE, PI_SAMPLER_PROPERTIES_NORMALIZED_COORDS, piextBindlessImageSamplerCreate(), piextMemSampledImageCreate(), populate_pi_structs(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::verify().
create_image() [10/10]
sampled_image_handle sycl::_V1::ext::oneapi::experimental::create_image (void * imgMem, size_t pitch, const bindless_image_sampler & sampler, const image_descriptor & desc, const sycl::queue & syclQueue)
Create a sampled image and return the device image handle.
Parameters
imgMem Device memory pointer to allocated image memory
pitch The allocation pitch value
sampler bindless image sampler used to sample the image
desc The image descriptor
syclQueue The queue in which we create our image handle
Returns
Image handle to created image object on the device
Definition at line 462 of file bindless_images.cpp.
References create_image(), sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
create_kernel_bundle_from_source() [1/2]
source_kb sycl::_V1::ext::oneapi::experimental::create_kernel_bundle_from_source (const context & SyclContext, source_language Language, const std::string & Source)
Definition at line 389 of file kernel_bundle.cpp.
References sycl::_V1::context::get_backend(), and is_source_kernel_bundle_supported().
create_kernel_bundle_from_source() [2/2]
source_kb sycl::_V1::ext::oneapi::experimental::create_kernel_bundle_from_source (const context & SyclContext, source_language Language, const std::vector< std::byte > & Bytes)
Definition at line 406 of file kernel_bundle.cpp.
References sycl::_V1::context::get_backend(), and is_source_kernel_bundle_supported().
destroy_external_semaphore() [1/2]
void sycl::_V1::ext::oneapi::experimental::destroy_external_semaphore (interop_semaphore_handle semaphoreHandle, const sycl::device & syclDevice, const sycl::context & syclContext)
Destroy the external semaphore handle.
Parameters
semaphoreHandle The interop semaphore handle to destroy
syclDevice The device in which the interop semaphore handle was created
syclContext The context in which the interop semaphore handle was created
Definition at line 770 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextDestroyExternalSemaphore(), and sycl::_V1::ext::oneapi::experimental::interop_semaphore_handle::raw_handle.
Referenced by destroy_external_semaphore().
destroy_external_semaphore() [2/2]
void sycl::_V1::ext::oneapi::experimental::destroy_external_semaphore (interop_semaphore_handle semaphoreHandle, const sycl::queue & syclQueue)
Destroy the external semaphore handle.
Parameters
semaphoreHandle The interop semaphore handle to destroy
syclQueue The queue in which the interop semaphore handle was created
Definition at line 787 of file bindless_images.cpp.
References destroy_external_semaphore(), sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
destroy_image_handle() [1/4]
void sycl::_V1::ext::oneapi::experimental::destroy_image_handle (sampled_image_handle & imageHandle, const sycl::device & syclDevice, const sycl::context & syclContext)
Destroy a sampled image handle.
Does not free memory backing the handle
Parameters
imageHandle The sampled image handle to destroy
syclDevice The device in which we created our image handle
syclContext The context in which we created our image handle
Definition at line 137 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextMemSampledImageHandleDestroy(), and sycl::_V1::ext::oneapi::experimental::sampled_image_handle::raw_handle.
destroy_image_handle() [2/4]
void sycl::_V1::ext::oneapi::experimental::destroy_image_handle (sampled_image_handle & imageHandle, const sycl::queue & syclQueue)
Destroy a sampled image handle.
Does not free memory backing the handle
Parameters
imageHandle The sampled image handle to destroy
syclQueue The queue in which we created our image handle
Definition at line 154 of file bindless_images.cpp.
References destroy_image_handle(), sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
destroy_image_handle() [3/4]
void sycl::_V1::ext::oneapi::experimental::destroy_image_handle (unsampled_image_handle & imageHandle, const sycl::device & syclDevice, const sycl::context & syclContext)
Destroy an unsampled image handle.
Does not free memory backing the handle
Parameters
imageHandle The unsampled image handle to destroy
syclDevice The device in which we created our image handle
syclContext The context in which we created our image handle
Definition at line 114 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextMemUnsampledImageHandleDestroy(), and sycl::_V1::ext::oneapi::experimental::unsampled_image_handle::raw_handle.
Referenced by destroy_image_handle().
destroy_image_handle() [4/4]
void sycl::_V1::ext::oneapi::experimental::destroy_image_handle (unsampled_image_handle & imageHandle, const sycl::queue & syclQueue)
Destroy an unsampled image handle.
Does not free memory backing the handle
Parameters
imageHandle The unsampled image handle to destroy
syclQueue The queue in which we created our image handle
Definition at line 131 of file bindless_images.cpp.
References destroy_image_handle(), sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
dynamic_address_cast()
template<access::address_space Space, access::decorated DecorateAddress, typename ElementType > multi_ptr<ElementType, Space, DecorateAddress> sycl::_V1::ext::oneapi::experimental::dynamic_address_cast (ElementType * Ptr)
Definition at line 35 of file address_cast.hpp.
dynamic_parameter()
template<typename ValueT > sycl::_V1::ext::oneapi::experimental::dynamic_parameter (experimental::command_graph< graph_state::modifiable > Graph, const ValueT & Param) -> dynamic_parameter< ValueT >
Additional CTAD deduction guides.
exp()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::exp (const complex< _Tp > & __x)
Definition at line 284 of file complex_math.hpp.
References sycl::_V1::ext::intel::math::copysign().
Referenced by pow().
fabs() [1/3]
template<size_t N> sycl::marray<bfloat16, N> sycl::_V1::ext::oneapi::experimental::fabs (sycl::marray< bfloat16, N > x)
Definition at line 109 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits(), sycl::_V1::ext::oneapi::detail::bitsToBfloat16(), fabs(), and sycl::_V1::ext::oneapi::experimental::detail::to_uint32_t().
fabs() [2/3]
template<typename T > std::enable_if_t<std::is_same_v<T, bfloat16>, T> sycl::_V1::ext::oneapi::experimental::fabs (T x)
Definition at line 90 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits(), sycl::_V1::ext::oneapi::detail::bitsToBfloat16(), and isnan().
Referenced by fabs().
fabs() [3/3]
template<typename T , int N = num_elements_v<T>> std::enable_if_t<is_vec_or_swizzle_bf16_v<T>, sycl::vec<bfloat16, N> > sycl::_V1::ext::oneapi::experimental::fabs (T x)
Definition at line 135 of file bfloat16_math.hpp.
References fabs().
fetch_cubemap()
template<typename DataT , typename HintT = DataT> DataT sycl::_V1::ext::oneapi::experimental::fetch_cubemap (const unsampled_image_handle & imageHandle, const int2 & coords, unsigned int face)
Fetch data from an unsampled cubemap image using its handle.
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
Parameters
imageHandle The image handle
coords The coordinates at which to fetch image data (int2 only)
face The cubemap face at which to fetch
Returns
Image data
Definition at line 1343 of file bindless_images.hpp.
References coords.
fetch_image() [1/2]
template<typename DataT , typename HintT = DataT, typename CoordT > DataT sycl::_V1::ext::oneapi::experimental::fetch_image (const sampled_image_handle &imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused])
Fetch data from a sampled image using its handle.
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. int, int2, or int3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The image handle
coords The coordinates at which to fetch image data
Returns
Fetched image data
NVPTX: Name mangling info Cuda surfaces require integer coords (by bytes) Cuda textures require float coords (by element or normalized) for sampling, and integer coords (by bytes) for fetching The name mangling should therefore not interfere with one another
Definition at line 966 of file bindless_images.hpp.
References coords.
fetch_image() [2/2]
template<typename DataT , typename HintT = DataT, typename CoordT > DataT sycl::_V1::ext::oneapi::experimental::fetch_image (const unsampled_image_handle &imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused])
Fetch data from an unsampled image using its handle.
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. int, int2, or int3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The image handle
coords The coordinates at which to fetch image data
Returns
Image data
NVPTX: Name mangling info Cuda surfaces require integer coords (by bytes) Cuda textures require float coords (by element or normalized) for sampling, and integer coords (by bytes) for fetching The name mangling should therefore not interfere with one another
Definition at line 882 of file bindless_images.hpp.
References coords.
fetch_image_array() [1/2]
template<typename DataT , typename HintT = DataT, typename CoordT > DataT sycl::_V1::ext::oneapi::experimental::fetch_image_array (const sampled_image_handle &imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused], unsigned int arrayLayer] [[maybe_unused])
Fetch data from a sampled image array using its handle.
Template Parameters
DataT The return type.
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. int or int2 for 1D or 2D, respectively.
Parameters
imageHandle The image handle.
coords The coordinates at which to fetch image data.
arrayLayer The image array layer at which to fetch.
Returns
Image data.
Definition at line 1402 of file bindless_images.hpp.
References coords.
fetch_image_array() [2/2]
template<typename DataT , typename HintT = DataT, typename CoordT > DataT sycl::_V1::ext::oneapi::experimental::fetch_image_array (const unsampled_image_handle &imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused], unsigned int arrayLayer] [[maybe_unused])
Fetch data from an unsampled image array using its handle.
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. int or int2 for 1D or 2D, respectively
Parameters
imageHandle The image handle
coords The coordinates at which to fetch image data
arrayLayer The image array layer at which to fetch
Returns
Image data
Definition at line 1293 of file bindless_images.hpp.
References coords.
fill() [1/2]
template<typename T > void sycl::_V1::ext::oneapi::experimental::fill (sycl::handler & CGH, T * Ptr, const T & Pattern, size_t Count)
Definition at line 306 of file enqueue_functions.hpp.
References sycl::_V1::handler::fill().
Referenced by sycl::_V1::detail::array_fill_helper< Kind, Idx, T, Args... >::fill(), sycl::_V1::detail::context_impl::memcpyFromHostOnlyDeviceGlobal(), and sycl::_V1::detail::packCallArguments().
fill() [2/2]
template<typename T > void sycl::_V1::ext::oneapi::experimental::fill (sycl::queue Q, T * Ptr, const T & Pattern, size_t Count, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current())
Definition at line 311 of file enqueue_functions.hpp.
References submit().
fma() [1/3]
template<size_t N> sycl::marray<bfloat16, N> sycl::_V1::ext::oneapi::experimental::fma (sycl::marray< bfloat16, N > x, sycl::marray< bfloat16, N > y, sycl::marray< bfloat16, N > z)
Definition at line 333 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits(), sycl::_V1::ext::oneapi::detail::bitsToBfloat16(), fma(), and sycl::_V1::ext::oneapi::experimental::detail::to_uint32_t().
fma() [2/3]
template<typename T > std::enable_if_t<std::is_same_v<T, bfloat16>, T> sycl::_V1::ext::oneapi::experimental::fma (T x, T y, T z)
Definition at line 319 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits(), and sycl::_V1::ext::oneapi::detail::bitsToBfloat16().
Referenced by fma().
fma() [3/3]
template<typename T1 , typename T2 , typename T3 , int N1 = num_elements_v<T1>, int N2 = num_elements_v<T2>, int N3 = num_elements_v<T3>> std::enable_if_t<is_vec_or_swizzle_bf16_v<T1> && is_vec_or_swizzle_bf16_v<T2> && is_vec_or_swizzle_bf16_v<T3> && N1 == N2 && N2 == N3, sycl::vec<bfloat16, N1> > sycl::_V1::ext::oneapi::experimental::fma (T1 x, T2 y, T3 z)
Definition at line 370 of file bfloat16_math.hpp.
References fma().
fmax() [1/3]
template<size_t N> sycl::marray<bfloat16, N> sycl::_V1::ext::oneapi::experimental::fmax (sycl::marray< bfloat16, N > x, sycl::marray< bfloat16, N > y)
Definition at line 265 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits(), sycl::_V1::ext::oneapi::detail::bitsToBfloat16(), fmax(), and sycl::_V1::ext::oneapi::experimental::detail::to_uint32_t().
fmax() [2/3]
template<typename T > std::enable_if_t<std::is_same_v<T, bfloat16>, T> sycl::_V1::ext::oneapi::experimental::fmax (T x, T y)
Definition at line 237 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits(), sycl::_V1::ext::oneapi::detail::bitsToBfloat16(), and isnan().
Referenced by fmax().
fmax() [3/3]
template<typename T1 , typename T2 , int N1 = num_elements_v<T1>, int N2 = num_elements_v<T2>> std::enable_if_t<is_vec_or_swizzle_bf16_v<T1> && is_vec_or_swizzle_bf16_v<T2> && N1 == N2, sycl::vec<bfloat16, N1> > sycl::_V1::ext::oneapi::experimental::fmax (T1 x, T2 y)
Definition at line 298 of file bfloat16_math.hpp.
References fmax().
fmin() [1/3]
template<size_t N> sycl::marray<bfloat16, N> sycl::_V1::ext::oneapi::experimental::fmin (sycl::marray< bfloat16, N > x, sycl::marray< bfloat16, N > y)
Definition at line 183 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits(), sycl::_V1::ext::oneapi::detail::bitsToBfloat16(), fmin(), and sycl::_V1::ext::oneapi::experimental::detail::to_uint32_t().
fmin() [2/3]
template<typename T > std::enable_if_t<std::is_same_v<T, bfloat16>, T> sycl::_V1::ext::oneapi::experimental::fmin (T x, T y)
Definition at line 154 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits(), sycl::_V1::ext::oneapi::detail::bitsToBfloat16(), and isnan().
Referenced by fmin().
fmin() [3/3]
template<typename T1 , typename T2 , int N1 = num_elements_v<T1>, int N2 = num_elements_v<T2>> std::enable_if_t<is_vec_or_swizzle_bf16_v<T1> && is_vec_or_swizzle_bf16_v<T2> && N1 == N2, sycl::vec<bfloat16, N1> > sycl::_V1::ext::oneapi::experimental::fmin (T1 x, T2 y)
Definition at line 216 of file bfloat16_math.hpp.
References fmin().
free() [1/2]
template<typename T , typename propList > void sycl::_V1::ext::oneapi::experimental::free (annotated_ptr< T, propList > & ptr, const context & syclContext)
Definition at line 24 of file dealloc.hpp.
free() [2/2]
template<typename T , typename propList > void sycl::_V1::ext::oneapi::experimental::free (annotated_ptr< T, propList > & ptr, const queue & syclQueue)
Definition at line 29 of file dealloc.hpp.
free_image_mem() [1/4]
void sycl::_V1::ext::oneapi::experimental::free_image_mem (image_mem_handle handle, const sycl::device & syclDevice, const sycl::context & syclContext)
[Deprecated] Free image memory
Parameters
handle Memory handle to allocated memory on the device
syclDevice The device in which we create our memory handle
syclContext The context in which we created our memory handle
Definition at line 295 of file bindless_images.cpp.
References standard.
Referenced by free_image_mem(), and sycl::_V1::ext::oneapi::experimental::detail::image_mem_impl::~image_mem_impl().
free_image_mem() [2/4]
void sycl::_V1::ext::oneapi::experimental::free_image_mem (image_mem_handle handle, const sycl::queue & syclQueue)
[Deprecated] Free image memory
Parameters
handle Memory handle to allocated memory on the device
syclQueue The queue in which we create our memory handle
Definition at line 303 of file bindless_images.cpp.
References free_image_mem().
free_image_mem() [3/4]
void sycl::_V1::ext::oneapi::experimental::free_image_mem (image_mem_handle handle, image_type imageType, const sycl::device & syclDevice, const sycl::context & syclContext)
Free image memory.
Parameters
handle Memory handle to allocated memory on the device
imageType Type of image memory to be freed
syclDevice The device in which we create our memory handle
syclContext The context in which we created our memory handle
Definition at line 256 of file bindless_images.cpp.
References array, cubemap, sycl::_V1::detail::getSyclObjImpl(), mipmap, piextMemImageFree(), piextMemMipmapFree(), sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, and standard.
free_image_mem() [4/4]
void sycl::_V1::ext::oneapi::experimental::free_image_mem (image_mem_handle handle, image_type imageType, const sycl::queue & syclQueue)
Free image memory.
Parameters
handle Memory handle to allocated memory on the device
imageType Type of image memory to be freed
syclQueue The queue in which we create our memory handle
Definition at line 286 of file bindless_images.cpp.
References free_image_mem(), sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
free_mipmap_mem() [1/2]
void sycl::_V1::ext::oneapi::experimental::free_mipmap_mem (image_mem_handle handle, const sycl::device & syclDevice, const sycl::context & syclContext)
[Deprecated] Free mipmap memory
Parameters
handle The mipmap memory handle
syclDevice The device in which we created our memory handle
syclContext The context in which we created our memory handle
Definition at line 310 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and piextMemMipmapFree().
Referenced by free_mipmap_mem().
free_mipmap_mem() [2/2]
void sycl::_V1::ext::oneapi::experimental::free_mipmap_mem (image_mem_handle handle, const sycl::queue & syclQueue)
[Deprecated] Free mipmap memory
Parameters
handle The mipmap memory handle
syclQueue The queue in which we created our memory handle
Definition at line 329 of file bindless_images.cpp.
References free_mipmap_mem().
free_virtual_mem()
void sycl::_V1::ext::oneapi::experimental::free_virtual_mem (uintptr_t Ptr, size_t NumBytes, const context & SyclContext)
Definition at line 124 of file virtual_mem.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and piextVirtualMemFree().
get()
T* sycl::_V1::ext::oneapi::experimental::get () const noexcept
Definition at line 384 of file annotated_ptr.hpp.
References m_Ptr.
Referenced by sycl::_V1::ext::oneapi::experimental::device_global< T, detail::properties_t< Props... > >::operator const T &(), and sycl::_V1::ext::oneapi::experimental::device_global< T, detail::properties_t< Props... > >::operator T&().
get_access_mode()
address_access_mode sycl::_V1::ext::oneapi::experimental::get_access_mode (const void * Ptr, size_t NumBytes, const context & SyclContext)
Definition at line 145 of file virtual_mem.cpp.
References sycl::_V1::detail::getSyclObjImpl(), none, PI_EXT_ONEAPI_VIRTUAL_MEM_INFO_ACCESS_MODE, PI_VIRTUAL_ACCESS_FLAG_READ_ONLY, PI_VIRTUAL_ACCESS_FLAG_RW, piextVirtualMemGetInfo(), read, and read_write.
get_ballot_group()
template<typename Group > std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&std::is_same_v< Group, sycl::sub_group >, ballot_group< Group > > sycl::_V1::ext::oneapi::experimental::get_ballot_group (Group group, bool predicate) inline
Definition at line 146 of file ballot_group.hpp.
References sycl::_V1::ext::oneapi::group_ballot(), and sycl::_V1::ext::oneapi::sub_group_mask::max_bits.
get_composite_devices()
std::vector< device > sycl::_V1::ext::oneapi::experimental::get_composite_devices ()
Definition at line 17 of file composite_device.cpp.
get_fixed_size_group()
template<size_t PartitionSize, typename Group > std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&std::is_same_v< Group, sycl::sub_group >, fixed_size_group< PartitionSize, Group > > sycl::_V1::ext::oneapi::experimental::get_fixed_size_group (Group group) inline
Definition at line 152 of file fixed_size_group.hpp.
get_image_channel_type() [1/2]
sycl::image_channel_type sycl::_V1::ext::oneapi::experimental::get_image_channel_type (const image_mem_handle memHandle, const sycl::device & syclDevice, const sycl::context & syclContext)
Get the channel type that describes the image memory.
Parameters
memHandle Memory handle to allocated memory on the device
syclDevice The device in which we created our image memory handle
syclContext The context in which we created our image memory handle
Returns
sycl image channel type that describes the image
Definition at line 825 of file bindless_images.cpp.
References sycl::_V1::detail::convertChannelType(), sycl::_V1::detail::getSyclObjImpl(), _pi_image_format::image_channel_data_type, PI_IMAGE_INFO_FORMAT, piextMemImageGetInfo(), and sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle.
Referenced by get_image_channel_type().
get_image_channel_type() [2/2]
sycl::image_channel_type sycl::_V1::ext::oneapi::experimental::get_image_channel_type (const image_mem_handle memHandle, const sycl::queue & syclQueue)
Get the channel type that describes the image memory.
Parameters
memHandle Memory handle to allocated memory on the device
syclQueue The queue in which we created our image memory handle
Returns
sycl image channel type that describes the image
Definition at line 846 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and get_image_channel_type().
get_image_num_channels() [1/2]
unsigned int sycl::_V1::ext::oneapi::experimental::get_image_num_channels (const image_mem_handle memHandle, const sycl::device & syclDevice, const sycl::context & syclContext)
Get the number of channels that describes the image memory.
Parameters
memHandle Memory handle to allocated memory on the device
syclDevice The device in which we created our image memory handle
syclContext The context in which we created our image memory handle
Returns
The number of channels describing the image
Definition at line 915 of file bindless_images.cpp.
References sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::getImageNumberChannels(), sycl::_V1::detail::getSyclObjImpl(), _pi_image_format::image_channel_order, PI_IMAGE_INFO_FORMAT, piextMemImageGetInfo(), and sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle.
Referenced by get_image_num_channels().
get_image_num_channels() [2/2]
unsigned int sycl::_V1::ext::oneapi::experimental::get_image_num_channels (const image_mem_handle memHandle, const sycl::queue & syclQueue)
Get the number of channels that describes the image memory.
Parameters
memHandle Memory handle to allocated memory on the device
syclQueue The queue in which we created our image memory handle
Returns
The number of channels describing the image
Definition at line 936 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and get_image_num_channels().
get_image_range() [1/2]
sycl::range< 3 > sycl::_V1::ext::oneapi::experimental::get_image_range (const image_mem_handle memHandle, const sycl::device & syclDevice, const sycl::context & syclContext)
Get the range that describes the image's dimensions.
Parameters
memHandle Memory handle to allocated memory on the device
syclDevice The device in which we created our image memory handle
syclContext The context in which we created our image memory handle
Returns
sycl range describing image's dimensions
Definition at line 793 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), PI_IMAGE_INFO_DEPTH, PI_IMAGE_INFO_HEIGHT, PI_IMAGE_INFO_WIDTH, piextMemImageGetInfo(), and sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle.
Referenced by get_image_range().
get_image_range() [2/2]
sycl::range< 3 > sycl::_V1::ext::oneapi::experimental::get_image_range (const image_mem_handle memHandle, const sycl::queue & syclQueue)
Get the range that describes the image's dimensions.
Parameters
memHandle Memory handle to allocated memory on the device
syclQueue The queue in which we created our image memory handle
Returns
sycl range describing image's dimensions
Definition at line 818 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and get_image_range().
get_mem_granularity() [1/2]
size_t sycl::_V1::ext::oneapi::experimental::get_mem_granularity (const context & SyclContext, granularity_mode Mode = granularity_mode::recommended)
Definition at line 64 of file virtual_mem.cpp.
References all_of(), sycl::_V1::ext_oneapi_cuda, sycl::_V1::context::get_backend(), sycl::_V1::context::get_devices(), get_mem_granularity(), and sycl::_V1::Mode.
get_mem_granularity() [2/2]
size_t sycl::_V1::ext::oneapi::experimental::get_mem_granularity (const device & SyclDevice, const context & SyclContext, granularity_mode Mode = granularity_mode::recommended)
Definition at line 25 of file virtual_mem.cpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::device::has(), minimum, sycl::_V1::Mode, PI_EXT_ONEAPI_VIRTUAL_MEM_GRANULARITY_INFO_MINIMUM, PI_EXT_ONEAPI_VIRTUAL_MEM_GRANULARITY_INFO_RECOMMENDED, piextVirtualMemGranularityGetInfo(), and recommended.
Referenced by get_mem_granularity().
get_mip_level_mem_handle() [1/2]
image_mem_handle sycl::_V1::ext::oneapi::experimental::get_mip_level_mem_handle (const image_mem_handle mipMem, unsigned int level, const sycl::device & syclDevice, const sycl::context & syclContext)
Retrieve the memory handle to an individual mipmap image.
Parameters
mipMem The memory handle to the mipmapped array
level The requested level of the mipmap
syclDevice The device in which we created our memory handle
syclContext The context in which we created our memory handle
Returns
Memory handle to the individual mipmap image
Definition at line 228 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), level, piextMemMipmapGetLevel(), and sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle.
Referenced by get_mip_level_mem_handle(), and sycl::_V1::ext::oneapi::experimental::image_mem::get_mip_level_mem_handle().
get_mip_level_mem_handle() [2/2]
image_mem_handle sycl::_V1::ext::oneapi::experimental::get_mip_level_mem_handle (const image_mem_handle mipMem, unsigned int level, const sycl::queue & syclQueue)
Retrieve the memory handle to an individual mipmap image.
Parameters
mipMem The memory handle to the mipmapped array
level The requested level of the mipmap
syclQueue The queue in which we created our memory handle
Returns
Memory handle to the individual mipmap image
Definition at line 250 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), get_mip_level_mem_handle(), and level.
get_property() [1/2]
template<typename PropertyT > static constexpr auto sycl::_V1::ext::oneapi::experimental::get_property () static constexpr
Definition at line 195 of file annotated_arg.hpp.
get_property() [2/2]
template<typename PropertyT > static constexpr auto sycl::_V1::ext::oneapi::experimental::get_property () static constexpr
Definition at line 471 of file annotated_ptr.hpp.
get_tangle_group()
template<typename Group > std::enable_if_t< sycl::is_group_v< std::decay_t< Group > > &&std::is_same_v< Group, sycl::sub_group >, tangle_group< Group > > sycl::_V1::ext::oneapi::experimental::get_tangle_group (Group group) inline
Definition at line 143 of file tangle_group.hpp.
References sycl::_V1::ext::oneapi::group_ballot().
get_usm_property_list()
template<typename PropertyListT > property_list sycl::_V1::ext::oneapi::experimental::get_usm_property_list () inline
Definition at line 226 of file alloc_util.hpp.
References sycl::_V1::ext::intel::experimental::buffer_location.
group_load()
template<typename... Args> void sycl::_V1::ext::oneapi::experimental::group_load (Args...)
Definition at line 393 of file group_load_store.hpp.
group_store()
template<typename... Args> void sycl::_V1::ext::oneapi::experimental::group_store (Args...)
Definition at line 398 of file group_load_store.hpp.
has_property() [1/2]
template<typename PropertyT > static constexpr bool sycl::_V1::ext::oneapi::experimental::has_property () static constexpr
Definition at line 191 of file annotated_arg.hpp.
Referenced by sycl::_V1::queue::memcpy(), and sycl::_V1::handler::memcpy().
has_property() [2/2]
template<typename PropertyT > static constexpr bool sycl::_V1::ext::oneapi::experimental::has_property () static constexpr
Definition at line 467 of file annotated_ptr.hpp.
if() [1/2]
constexpr sycl::_V1::ext::oneapi::experimental::if (detail::are_floating_coords< CoordT > ()) constexpr
Definition at line 1074 of file bindless_images.hpp.
References coords.
if() [2/2]
else constexpr sycl::_V1::ext::oneapi::experimental::if (detail::are_integer_coords< CoordT > ()) constexpr
Definition at line 1076 of file bindless_images.hpp.
if_architecture_is()
template<architecture... Archs, typename T > constexpr static auto sycl::_V1::ext::oneapi::experimental::if_architecture_is (T fn) static constexpr
The condition is true only if the device which executes the if_architecture_is function has any one of the architectures listed in the.
The condition is true only if the device which executes the if_architecture_is function has an architecture that is in any one of the categories listed in the.
Template Parameters
Archs pack.
Categories pack.
Definition at line 1073 of file device_architecture.hpp.
if_architecture_is_between()
template<architecture Arch1, architecture Arch2, typename T > constexpr static auto sycl::_V1::ext::oneapi::experimental::if_architecture_is_between (T fn) static constexpr
The condition is true only if the device which executes the if_architecture_is_between function has an architecture that is in the same family as.
Template Parameters
Arch1 and is greater than or equal to
Arch1 and is less than or equal to
Arch2.
Definition at line 1168 of file device_architecture.hpp.
References sycl::_V1::detail::device_arch_compare_op_ge, and sycl::_V1::detail::device_arch_compare_op_le.
if_architecture_is_ge()
template<architecture Arch, typename T > constexpr static auto sycl::_V1::ext::oneapi::experimental::if_architecture_is_ge (T fn) static constexpr
The condition is true only if the device which executes the if_architecture_is_ge function has an architecture that is in the same family as.
Template Parameters
Arch and compares greater than or equal to
Arch.
Definition at line 1152 of file device_architecture.hpp.
References sycl::_V1::detail::device_arch_compare_op_ge.
if_architecture_is_gt()
template<architecture Arch, typename T > constexpr static auto sycl::_V1::ext::oneapi::experimental::if_architecture_is_gt (T fn) static constexpr
The condition is true only if the device which executes the if_architecture_is_gt function has an architecture that is in the same family as.
Template Parameters
Arch and compares greater than
Arch.
Definition at line 1137 of file device_architecture.hpp.
References sycl::_V1::detail::device_arch_compare_op_gt.
if_architecture_is_le()
template<architecture Arch, typename T > constexpr static auto sycl::_V1::ext::oneapi::experimental::if_architecture_is_le (T fn) static constexpr
The condition is true only if the device which executes the if_architecture_is_le function has an architecture that is in the same family as.
Template Parameters
Arch and compares less than or equal to
Arch.
Definition at line 1122 of file device_architecture.hpp.
References sycl::_V1::detail::device_arch_compare_op_le.
if_architecture_is_lt()
template<architecture Arch, typename T > constexpr static auto sycl::_V1::ext::oneapi::experimental::if_architecture_is_lt (T fn) static constexpr
The condition is true only if the device which executes the if_architecture_is_lt function has an architecture that is in the same family as.
Template Parameters
Arch and compares less than
Arch.
Definition at line 1107 of file device_architecture.hpp.
References sycl::_V1::detail::device_arch_compare_op_lt.
imag() [1/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL constexpr _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits<_Tp>::_ValueType sycl::_V1::ext::oneapi::experimental::imag (_Tp) constexpr
Definition at line 623 of file complex_math.hpp.
imag() [2/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL constexpr _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, _Tp> sycl::_V1::ext::oneapi::experimental::imag (const complex< _Tp > & __c) constexpr
Definition at line 616 of file complex_math.hpp.
import_external_memory() [1/2]
template<typename ExternalMemHandleType > interop_mem_handle sycl::_V1::ext::oneapi::experimental::import_external_memory (external_mem_descriptor< ExternalMemHandleType > externalMem, const sycl::device & syclDevice, const sycl::context & syclContext)
Import external memory taking an external memory handle (the type of which is dependent on the OS & external API) and return an interop memory handle.
Template Parameters
ExternalMemHandleType Handle type describing external memory handle
Parameters
externalMem External memory descriptor
syclDevice The device in which we create our interop memory
syclContext The context in which we create our interop memory handle
Returns
Interop memory handle to the external memory
import_external_memory() [2/2]
template<typename ExternalMemHandleType > interop_mem_handle sycl::_V1::ext::oneapi::experimental::import_external_memory (external_mem_descriptor< ExternalMemHandleType > externalMem, const sycl::queue & syclQueue)
Import external memory taking an external memory handle (the type of which is dependent on the OS & external API) and return an interop memory handle.
Template Parameters
ExternalMemHandleType Handle type describing external memory handle
Parameters
externalMem External memory descriptor
syclQueue The queue in which we create our interop memory handle
Returns
Interop memory handle to the external memory
import_external_memory< external_mem_fd >() [1/2]
template<> interop_mem_handle sycl::_V1::ext::oneapi::experimental::import_external_memory< external_mem_fd > (external_mem_descriptor< external_mem_fd > externalMem, const sycl::device & syclDevice, const sycl::context & syclContext)
Definition at line 551 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::external_mem_descriptor< ResourceType >::external_resource, import_external_memory< resource_fd >(), and sycl::_V1::ext::oneapi::experimental::external_mem_descriptor< ResourceType >::size_in_bytes.
Referenced by import_external_memory< external_mem_fd >().
import_external_memory< external_mem_fd >() [2/2]
template<> interop_mem_handle sycl::_V1::ext::oneapi::experimental::import_external_memory< external_mem_fd > (external_mem_descriptor< external_mem_fd > externalMem, const sycl::queue & syclQueue)
Definition at line 566 of file bindless_images.cpp.
References import_external_memory< external_mem_fd >().
import_external_memory< resource_fd >() [1/2]
template<> interop_mem_handle sycl::_V1::ext::oneapi::experimental::import_external_memory< resource_fd > (external_mem_descriptor< resource_fd > externalMem, const sycl::device & syclDevice, const sycl::context & syclContext)
Definition at line 469 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::external_mem_descriptor< ResourceType >::external_resource, pi_external_handle::file_descriptor, sycl::_V1::detail::getSyclObjImpl(), pi_external_mem_descriptor::handle, pi_external_mem_descriptor::handleType, pi_external_mem_descriptor::memorySizeBytes, opaque_fd, piextImportExternalMemory(), and sycl::_V1::ext::oneapi::experimental::external_mem_descriptor< ResourceType >::size_in_bytes.
Referenced by import_external_memory< external_mem_fd >(), and import_external_memory< resource_fd >().
import_external_memory< resource_fd >() [2/2]
template<> interop_mem_handle sycl::_V1::ext::oneapi::experimental::import_external_memory< resource_fd > (external_mem_descriptor< resource_fd > externalMem, const sycl::queue & syclQueue)
Definition at line 499 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and import_external_memory< resource_fd >().
import_external_memory< resource_win32_handle >() [1/2]
template<> interop_mem_handle sycl::_V1::ext::oneapi::experimental::import_external_memory< resource_win32_handle > (external_mem_descriptor< resource_win32_handle > externalMem, const sycl::device & syclDevice, const sycl::context & syclContext)
Definition at line 507 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::external_mem_descriptor< ResourceType >::external_resource, sycl::_V1::detail::getSyclObjImpl(), pi_external_mem_descriptor::handle, sycl::_V1::ext::oneapi::experimental::external_mem_descriptor< ResourceType >::handle_type, pi_external_mem_descriptor::handleType, pi_external_mem_descriptor::memorySizeBytes, piextImportExternalMemory(), sycl::_V1::ext::oneapi::experimental::external_mem_descriptor< ResourceType >::size_in_bytes, pi_external_handle::win32_handle, win32_nt_dx12_resource, win32_nt_dx12_resource, win32_nt_handle, and win32_nt_handle.
Referenced by import_external_memory< resource_win32_handle >().
import_external_memory< resource_win32_handle >() [2/2]
template<> interop_mem_handle sycl::_V1::ext::oneapi::experimental::import_external_memory< resource_win32_handle > (external_mem_descriptor< resource_win32_handle > externalMem, const sycl::queue & syclQueue)
Definition at line 574 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and import_external_memory< resource_win32_handle >().
import_external_semaphore() [1/8]
template<> interop_semaphore_handle sycl::_V1::ext::oneapi::experimental::import_external_semaphore (external_semaphore_descriptor< external_semaphore_fd > externalSemaphoreDesc, const sycl::device & syclDevice, const sycl::context & syclContext)
Definition at line 748 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::external_semaphore_descriptor< ResourceType >::external_resource.
import_external_semaphore() [2/8]
template<> interop_semaphore_handle sycl::_V1::ext::oneapi::experimental::import_external_semaphore (external_semaphore_descriptor< external_semaphore_fd > externalSemaphoreDesc, const sycl::queue & syclQueue)
Definition at line 762 of file bindless_images.cpp.
References import_external_semaphore().
import_external_semaphore() [3/8]
template<typename ExternalSemaphoreHandleType > interop_semaphore_handle sycl::_V1::ext::oneapi::experimental::import_external_semaphore (external_semaphore_descriptor< ExternalSemaphoreHandleType > externalSemaphoreDesc, const sycl::device & syclDevice, const sycl::context & syclContext)
Import external semaphore taking an external semaphore handle (the type of which is dependent on the OS & external API)
Template Parameters
ExternalSemaphoreHandleType Handle type describing external semaphore handle
Parameters
externalSemaphoreDesc External semaphore descriptor
syclDevice The device in which we create our interop semaphore handle
syclContext The context in which we create our interop semaphore handle
Returns
Interop semaphore handle to the external semaphore
Referenced by import_external_semaphore().
import_external_semaphore() [4/8]
template<typename ExternalSemaphoreHandleType > interop_semaphore_handle sycl::_V1::ext::oneapi::experimental::import_external_semaphore (external_semaphore_descriptor< ExternalSemaphoreHandleType > externalSemaphoreDesc, const sycl::queue & syclQueue)
Import external semaphore taking an external semaphore handle (the type of which is dependent on the OS & external API)
Template Parameters
ExternalSemaphoreHandleType Handle type describing external semaphore handle
Parameters
externalSemaphoreDesc External semaphore descriptor
syclQueue The queue in which we create our interop semaphore handle
Returns
Interop semaphore handle to the external semaphore
import_external_semaphore() [5/8]
template<> interop_semaphore_handle sycl::_V1::ext::oneapi::experimental::import_external_semaphore (external_semaphore_descriptor< resource_fd > externalSemaphoreDesc, const sycl::device & syclDevice, const sycl::context & syclContext)
Definition at line 659 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::external_semaphore_descriptor< ResourceType >::external_resource, pi_external_handle::file_descriptor, sycl::_V1::detail::getSyclObjImpl(), pi_external_semaphore_descriptor::handle, pi_external_semaphore_descriptor::handleType, opaque_fd, opaque_fd, and piextImportExternalSemaphore().
import_external_semaphore() [6/8]
template<> interop_semaphore_handle sycl::_V1::ext::oneapi::experimental::import_external_semaphore (external_semaphore_descriptor< resource_fd > externalSemaphoreDesc, const sycl::queue & syclQueue)
Definition at line 688 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and import_external_semaphore().
import_external_semaphore() [7/8]
template<> interop_semaphore_handle sycl::_V1::ext::oneapi::experimental::import_external_semaphore (external_semaphore_descriptor< resource_win32_handle > externalSemaphoreDesc, const sycl::device & syclDevice, const sycl::context & syclContext)
Definition at line 696 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::external_semaphore_descriptor< ResourceType >::external_resource, sycl::_V1::detail::getSyclObjImpl(), pi_external_semaphore_descriptor::handle, sycl::_V1::ext::oneapi::experimental::external_semaphore_descriptor< ResourceType >::handle_type, pi_external_semaphore_descriptor::handleType, piextImportExternalSemaphore(), pi_external_handle::win32_handle, win32_nt_dx12_fence, win32_nt_dx12_fence, win32_nt_handle, and win32_nt_handle.
import_external_semaphore() [8/8]
template<> interop_semaphore_handle sycl::_V1::ext::oneapi::experimental::import_external_semaphore (external_semaphore_descriptor< resource_win32_handle > externalSemaphoreDesc, const sycl::queue & syclQueue)
Definition at line 737 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and import_external_semaphore().
is_source_kernel_bundle_supported()
bool sycl::_V1::ext::oneapi::experimental::is_source_kernel_bundle_supported (backend BE, source_language Language)
Definition at line 368 of file kernel_bundle.cpp.
References sycl::_V1::ext::oneapi::experimental::detail::OpenCLC_Compilation_Available().
Referenced by create_kernel_bundle_from_source(), and sycl::_V1::detail::device_impl::extOneapiCanCompile().
isnan() [1/3]
template<size_t N> sycl::marray<bool, N> sycl::_V1::ext::oneapi::experimental::isnan (sycl::marray< bfloat16, N > x)
Definition at line 53 of file bfloat16_math.hpp.
References isnan().
isnan() [2/3]
template<typename T > std::enable_if_t<std::is_same_v<T, bfloat16>, bool> sycl::_V1::ext::oneapi::experimental::isnan (T x)
Definition at line 48 of file bfloat16_math.hpp.
References sycl::_V1::ext::oneapi::detail::bfloat16ToBits().
Referenced by acos(), acosh(), asinh(), atanh(), sycl::_V1::detail::checkForInfNan(), fabs(), fmax(), fmin(), sycl::_V1::ext::intel::math::hequ(), sycl::_V1::ext::intel::math::hgeu(), sycl::_V1::ext::intel::math::hgtu(), sycl::_V1::ext::intel::math::hisnan(), sycl::_V1::ext::intel::math::hleu(), sycl::_V1::ext::intel::math::hltu(), sycl::_V1::ext::intel::math::hne(), sycl::_V1::ext::intel::math::hneu(), isnan(), polar(), sqrt(), and tanh().
isnan() [3/3]
template<typename T , int N = num_elements_v<T>> std::enable_if_t<is_vec_or_swizzle_bf16_v<T>, sycl::vec<int16_t, N> > sycl::_V1::ext::oneapi::experimental::isnan (T x)
Definition at line 64 of file bfloat16_math.hpp.
References isnan().
joint_prefetch() [1/10]
template<typename Group , typename DataT , int Dimensions, access_mode AccessMode, access::placeholder IsPlaceholder, typename Properties = empty_properties_t, typename AccessorProperties = empty_properties_t> std::enable_if_t<detail::check_prefetch_acc_mode<AccessMode> && (Dimensions > 0) && sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, accessor< DataT, Dimensions, AccessMode, target::device, IsPlaceholder, AccessorProperties > acc, size_t offset, Properties properties = {})
Definition at line 272 of file prefetch.hpp.
joint_prefetch() [2/10]
template<typename Group , typename DataT , int Dimensions, access_mode AccessMode, access::placeholder IsPlaceholder, typename Properties = empty_properties_t, typename AccessorProperties = empty_properties_t> std::enable_if_t<detail::check_prefetch_acc_mode<AccessMode> && (Dimensions > 0) && sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, accessor< DataT, Dimensions, AccessMode, target::device, IsPlaceholder, AccessorProperties > acc, size_t offset, size_t count, Properties properties = {})
Definition at line 287 of file prefetch.hpp.
joint_prefetch() [3/10]
template<typename Group , typename T , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t> std::enable_if_t<detail::check_prefetch_AS<AddressSpace> && sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, multi_ptr< T, AddressSpace, IsDecorated > ptr, Properties properties = {})
Definition at line 249 of file prefetch.hpp.
joint_prefetch() [4/10]
template<typename Group , typename T , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t> std::enable_if_t<detail::check_prefetch_AS<AddressSpace> && sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, multi_ptr< T, AddressSpace, IsDecorated > ptr, size_t count, Properties properties = {})
Definition at line 260 of file prefetch.hpp.
joint_prefetch() [5/10]
template<typename Group , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t> std::enable_if_t<detail::check_prefetch_AS<AddressSpace> && sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, multi_ptr< void, AddressSpace, IsDecorated > ptr, Properties properties = {})
Definition at line 227 of file prefetch.hpp.
joint_prefetch() [6/10]
template<typename Group , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t> std::enable_if_t<detail::check_prefetch_AS<AddressSpace> && sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, multi_ptr< void, AddressSpace, IsDecorated > ptr, size_t bytes, Properties properties = {})
Definition at line 238 of file prefetch.hpp.
joint_prefetch() [7/10]
template<typename Group , typename T , typename Properties = empty_properties_t> std::enable_if_t<sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, T * ptr, Properties properties = {})
Definition at line 210 of file prefetch.hpp.
joint_prefetch() [8/10]
template<typename Group , typename T , typename Properties = empty_properties_t> std::enable_if_t<sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, T * ptr, size_t count, Properties properties = {})
Definition at line 217 of file prefetch.hpp.
joint_prefetch() [9/10]
template<typename Group , typename Properties = empty_properties_t> std::enable_if_t<sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, void * ptr, Properties properties = {})
Definition at line 196 of file prefetch.hpp.
joint_prefetch() [10/10]
template<typename Group , typename Properties = empty_properties_t> std::enable_if_t<sycl::is_group_v<std::decay_t<Group> > && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::joint_prefetch (Group g, void * ptr, size_t bytes, Properties properties = {})
Definition at line 203 of file prefetch.hpp.
joint_reduce() [1/2]
template<typename GroupHelper , typename Ptr , typename BinaryOperation > std::enable_if_t<(is_group_helper_v<GroupHelper> && sycl::detail::is_pointer_v<Ptr>), typename std::iterator_traits<Ptr>::value_type> sycl::_V1::ext::oneapi::experimental::joint_reduce (GroupHelper group_helper, Ptr first, Ptr last, BinaryOperation binary_op)
Definition at line 87 of file user_defined_reductions.hpp.
References sycl::_V1::detail::for_each(), sycl::_V1::group_barrier(), and sycl::_V1::ext::oneapi::experimental::detail::reduce_over_group_impl().
Referenced by joint_reduce().
joint_reduce() [2/2]
template<typename GroupHelper , typename Ptr , typename T , typename BinaryOperation > std::enable_if_t< (is_group_helper_v<GroupHelper> && sycl::detail::is_pointer_v<Ptr>), T> sycl::_V1::ext::oneapi::experimental::joint_reduce (GroupHelper group_helper, Ptr first, Ptr last, T init, BinaryOperation binary_op)
Definition at line 123 of file user_defined_reductions.hpp.
References joint_reduce().
joint_sort() [1/3]
template<typename Group , typename Iter , typename Sorter > std::enable_if_t<detail::is_sorter<Sorter, Group, Iter>::value, void> sycl::_V1::ext::oneapi::experimental::joint_sort ([[maybe_unused] ] Group group, [[maybe_unused] ] Iter first, [[maybe_unused] ] Iter last, [[maybe_unused] ] Sorter sorter)
Definition at line 173 of file group_sort.hpp.
Referenced by joint_sort().
joint_sort() [2/3]
template<typename Group , typename Iter , size_t Extent> std::enable_if_t<sycl::is_group_v<std::decay_t<Group> >, void> sycl::_V1::ext::oneapi::experimental::joint_sort (experimental::group_with_scratchpad< Group, Extent > exec, Iter first, Iter last)
Definition at line 194 of file group_sort.hpp.
References sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_group(), sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_memory(), and joint_sort().
joint_sort() [3/3]
template<typename Group , typename Iter , typename Compare , size_t Extent> std::enable_if_t<!detail::is_sorter<Compare, Group, Iter>::value, void> sycl::_V1::ext::oneapi::experimental::joint_sort (experimental::group_with_scratchpad< Group, Extent > exec, Iter first, Iter last, Compare comp)
Definition at line 186 of file group_sort.hpp.
References sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_group(), sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_memory(), and joint_sort().
log()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::log (const complex< _Tp > & __x)
Definition at line 247 of file complex_math.hpp.
References abs(), and arg().
Referenced by acos(), acosh(), asinh(), atanh(), log10(), and pow().
log10()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::log10 (const complex< _Tp > & __x)
Definition at line 256 of file complex_math.hpp.
References log().
malloc_annotated() [1/8]
template<typename T , typename propertyListA , typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_annotated (size_t count, const device & syclDevice, const context & syclContext, const propertyListA & propList)
Definition at line 228 of file alloc_base.hpp.
malloc_annotated() [2/8]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_annotated (size_t count, const device & syclDevice, const context & syclContext, sycl::usm::alloc kind, const propertyListA & propList = propertyListA{})
Definition at line 167 of file alloc_base.hpp.
malloc_annotated() [3/8]
template<typename T , typename propertyListA , typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_annotated (size_t count, const queue & syclQueue, const propertyListA & propList)
Definition at line 256 of file alloc_base.hpp.
References sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
malloc_annotated() [4/8]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_annotated (size_t count, const queue & syclQueue, sycl::usm::alloc kind, const propertyListA & propList = propertyListA{})
Definition at line 192 of file alloc_base.hpp.
malloc_annotated() [5/8]
template<typename propertyListA , typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_annotated (size_t numBytes, const device & syclDevice, const context & syclContext, const propertyListA & propList)
Definition at line 212 of file alloc_base.hpp.
References malloc_annotated().
malloc_annotated() [6/8]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_annotated (size_t numBytes, const device & syclDevice, const context & syclContext, sycl::usm::alloc kind, const propertyListA & propList = propertyListA{})
Definition at line 154 of file alloc_base.hpp.
Referenced by malloc_annotated().
malloc_annotated() [7/8]
template<typename propertyListA , typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_annotated (size_t numBytes, const queue & syclQueue, const propertyListA & propList)
Definition at line 244 of file alloc_base.hpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and malloc_annotated().
malloc_annotated() [8/8]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename detail::GetCompileTimeProperties<propertyListA>::type> std::enable_if_t< detail::CheckTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_annotated (size_t numBytes, const queue & syclQueue, sycl::usm::alloc kind, const propertyListA & propList = propertyListA{})
Definition at line 180 of file alloc_base.hpp.
malloc_device_annotated() [1/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type> std::enable_if_t< CheckDevicePtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_device_annotated (size_t count, const device & syclDevice, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 126 of file alloc_device.hpp.
malloc_device_annotated() [2/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type> std::enable_if_t< CheckDevicePtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_device_annotated (size_t count, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 151 of file alloc_device.hpp.
malloc_device_annotated() [3/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type> std::enable_if_t< CheckDevicePtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_device_annotated (size_t numBytes, const device & syclDevice, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 113 of file alloc_device.hpp.
malloc_device_annotated() [4/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedDevicePtrProperties<propertyListA>::type> std::enable_if_t< CheckDevicePtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_device_annotated (size_t numBytes, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 139 of file alloc_device.hpp.
malloc_host_annotated() [1/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type> std::enable_if_t< CheckHostPtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_host_annotated (size_t count, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 119 of file alloc_host.hpp.
malloc_host_annotated() [2/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type> std::enable_if_t< CheckHostPtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_host_annotated (size_t count, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 141 of file alloc_host.hpp.
malloc_host_annotated() [3/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type> std::enable_if_t< CheckHostPtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_host_annotated (size_t numBytes, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 108 of file alloc_host.hpp.
malloc_host_annotated() [4/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedHostPtrProperties<propertyListA>::type> std::enable_if_t< CheckHostPtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_host_annotated (size_t numBytes, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 130 of file alloc_host.hpp.
malloc_shared_annotated() [1/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type> std::enable_if_t< CheckSharedPtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_shared_annotated (size_t count, const device & syclDevice, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 126 of file alloc_shared.hpp.
malloc_shared_annotated() [2/4]
template<typename T , typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type> std::enable_if_t< CheckSharedPtrTAndPropLists<T, propertyListA, propertyListB>::value, annotated_ptr<T, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_shared_annotated (size_t count, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 151 of file alloc_shared.hpp.
malloc_shared_annotated() [3/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type> std::enable_if_t< CheckSharedPtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_shared_annotated (size_t numBytes, const device & syclDevice, const context & syclContext, const propertyListA & propList = propertyListA{})
Definition at line 113 of file alloc_shared.hpp.
malloc_shared_annotated() [4/4]
template<typename propertyListA = empty_properties_t, typename propertyListB = typename GetAnnotatedSharedPtrProperties<propertyListA>::type> std::enable_if_t< CheckSharedPtrTAndPropLists<void, propertyListA, propertyListB>::value, annotated_ptr<void, propertyListB> > sycl::_V1::ext::oneapi::experimental::malloc_shared_annotated (size_t numBytes, const queue & syclQueue, const propertyListA & propList = propertyListA{})
Definition at line 139 of file alloc_shared.hpp.
map_external_image_memory() [1/2]
image_mem_handle sycl::_V1::ext::oneapi::experimental::map_external_image_memory (interop_mem_handle memHandle, const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
Maps an interop memory handle to an image memory handle (which may have a device optimized memory layout)
Parameters
memHandle Interop memory handle
desc The image descriptor
syclDevice The device in which we create our image memory handle
syclContext The conext in which we create our image memory handle
Returns
Memory handle to externally allocated memory on the device
Definition at line 582 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextMemMapExternalArray(), populate_pi_structs(), sycl::_V1::ext::oneapi::experimental::interop_mem_handle::raw_handle, sycl::_V1::ext::oneapi::experimental::image_mem_handle::raw_handle, and sycl::_V1::ext::oneapi::experimental::image_descriptor::verify().
Referenced by map_external_image_memory(), and map_external_memory_array().
map_external_image_memory() [2/2]
image_mem_handle sycl::_V1::ext::oneapi::experimental::map_external_image_memory (interop_mem_handle memHandle, const image_descriptor & desc, const sycl::queue & syclQueue)
Maps an interop memory handle to an image memory handle (which may have a device optimized memory layout)
Parameters
memHandle Interop memory handle
desc The image descriptor
syclQueue The queue in which we create our image memory handle
Returns
Memory handle to externally allocated memory on the device
Definition at line 611 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and map_external_image_memory().
map_external_memory_array() [1/2]
image_mem_handle sycl::_V1::ext::oneapi::experimental::map_external_memory_array (interop_mem_handle memHandle, const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
[Deprecated] Maps an interop memory handle to an image memory handle (which may have a device optimized memory layout)
Parameters
memHandle Interop memory handle
desc The image descriptor
syclDevice The device in which we create our image memory handle
syclContext The conext in which we create our image memory handle
Returns
Memory handle to externally allocated memory on the device
Definition at line 620 of file bindless_images.cpp.
References map_external_image_memory().
Referenced by map_external_memory_array().
map_external_memory_array() [2/2]
image_mem_handle sycl::_V1::ext::oneapi::experimental::map_external_memory_array (interop_mem_handle memHandle, const image_descriptor & desc, const sycl::queue & syclQueue)
[Deprecated] Maps an interop memory handle to an image memory handle (which may have a device optimized memory layout)
Parameters
memHandle Interop memory handle
desc The image descriptor
syclQueue The queue in which we create our image memory handle
Returns
Memory handle to externally allocated memory on the device
Definition at line 629 of file bindless_images.cpp.
References map_external_memory_array().
mem_advise() [1/2]
void sycl::_V1::ext::oneapi::experimental::mem_advise (handler & CGH, void * Ptr, size_t NumBytes, int Advice) inline
Definition at line 327 of file enqueue_functions.hpp.
References sycl::_V1::handler::mem_advise().
mem_advise() [2/2]
void sycl::_V1::ext::oneapi::experimental::mem_advise (queue Q, void * Ptr, size_t NumBytes, int Advice, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current())
Definition at line 32 of file enqueue_functions.cpp.
References sycl::_V1::detail::getSyclObjImpl().
memcpy() [1/2]
void sycl::_V1::ext::oneapi::experimental::memcpy (handler & CGH, void * Dest, const void * Src, size_t NumBytes) inline
Definition at line 277 of file enqueue_functions.hpp.
References sycl::_V1::handler::memcpy().
memcpy() [2/2]
void sycl::_V1::ext::oneapi::experimental::memcpy (queue Q, void * Dest, const void * Src, size_t NumBytes, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current())
Definition at line 16 of file enqueue_functions.cpp.
References sycl::_V1::detail::getSyclObjImpl().
memset() [1/2]
void sycl::_V1::ext::oneapi::experimental::memset (handler & CGH, void * Ptr, int Value, size_t NumBytes) inline
Definition at line 297 of file enqueue_functions.hpp.
References sycl::_V1::handler::memset().
memset() [2/2]
void sycl::_V1::ext::oneapi::experimental::memset (queue Q, void * Ptr, int Value, size_t NumBytes, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current())
Definition at line 24 of file enqueue_functions.cpp.
References sycl::_V1::detail::getSyclObjImpl().
nd_launch() [1/8]
template<int Dimensions, typename Properties , typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::nd_launch (handler & CGH, launch_config< nd_range< Dimensions >, Properties > Config, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 259 of file enqueue_functions.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::LaunchConfigAccess< LCRangeT, LCPropertiesT >::getRange(), sycl::_V1::handler::parallel_for(), and sycl::_V1::handler::set_args().
nd_launch() [2/8]
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename Properties , typename KernelType , typename... ReductionsT> void sycl::_V1::ext::oneapi::experimental::nd_launch (handler & CGH, launch_config< nd_range< Dimensions >, Properties > Config, const KernelType & KernelObj, ReductionsT &&... Reductions)
Definition at line 221 of file enqueue_functions.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::LaunchConfigAccess< LCRangeT, LCPropertiesT >::getRange(), and sycl::_V1::handler::parallel_for().
nd_launch() [3/8]
template<int Dimensions, typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::nd_launch (handler & CGH, nd_range< Dimensions > Range, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 244 of file enqueue_functions.hpp.
References sycl::_V1::handler::parallel_for(), and sycl::_V1::handler::set_args().
nd_launch() [4/8]
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename KernelType , typename... ReductionsT> void sycl::_V1::ext::oneapi::experimental::nd_launch (handler & CGH, nd_range< Dimensions > Range, const KernelType & KernelObj, ReductionsT &&... Reductions)
Definition at line 203 of file enqueue_functions.hpp.
References sycl::_V1::handler::parallel_for().
Referenced by nd_launch().
nd_launch() [5/8]
template<int Dimensions, typename Properties , typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::nd_launch (queue Q, launch_config< nd_range< Dimensions >, Properties > Config, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 270 of file enqueue_functions.hpp.
References nd_launch(), and submit().
nd_launch() [6/8]
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename Properties , typename KernelType , typename... ReductionsT> void sycl::_V1::ext::oneapi::experimental::nd_launch (queue Q, launch_config< nd_range< Dimensions >, Properties > Config, const KernelType & KernelObj, ReductionsT &&... Reductions)
Definition at line 235 of file enqueue_functions.hpp.
References submit().
nd_launch() [7/8]
template<int Dimensions, typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::nd_launch (queue Q, nd_range< Dimensions > Range, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 251 of file enqueue_functions.hpp.
References nd_launch(), and submit().
nd_launch() [8/8]
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename KernelType , typename... ReductionsT> void sycl::_V1::ext::oneapi::experimental::nd_launch (queue Q, nd_range< Dimensions > Range, const KernelType & KernelObj, ReductionsT &&... Reductions)
Definition at line 211 of file enqueue_functions.hpp.
References submit().
norm() [1/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits<_Tp>::_ValueType sycl::_V1::ext::oneapi::experimental::norm (_Tp __re)
Definition at line 161 of file complex_math.hpp.
norm() [2/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, _Tp> sycl::_V1::ext::oneapi::experimental::norm (const complex< _Tp > & __c)
Definition at line 150 of file complex_math.hpp.
References sycl::_V1::ext::oneapi::fabs().
operator bool()
sycl::_V1::ext::oneapi::experimental::operator bool () const explicit noexcept
Definition at line 380 of file annotated_ptr.hpp.
References m_Ptr.
operator T()
sycl::_V1::ext::oneapi::experimental::operator T () noexcept
Definition at line 320 of file annotated_arg.hpp.
References obj.
operator T*()
sycl::_V1::ext::oneapi::experimental::operator T* () delete noexcept
Definition at line 184 of file annotated_arg.hpp.
References obj.
operator!=()
template<typename PropertyT , typename... A, typename... B> constexpr std::enable_if_t<detail::IsCompileTimeProperty<PropertyT>::value, bool> sycl::_V1::ext::oneapi::experimental::operator!= (const property_value< PropertyT, A... > & , const property_value< PropertyT, B... > &) constexpr
Definition at line 55 of file property_value.hpp.
operator*()
reference sycl::_V1::ext::oneapi::experimental::operator* () const noexcept
Definition at line 374 of file annotated_ptr.hpp.
References m_Ptr.
operator+() [1/2]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>> annotated_ptr sycl::_V1::ext::oneapi::experimental::operator+ (size_t offset) const delete noexcept
Definition at line 411 of file annotated_ptr.hpp.
References annotated_ptr, and m_Ptr.
operator+() [2/2]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>> auto sycl::_V1::ext::oneapi::experimental::operator+ (size_t offset) const -> decltype("operator+ is not available when alignment is specified!")=delete delete noexcept
Definition at line 411 of file annotated_ptr.hpp.
References annotated_ptr, and m_Ptr.
operator++() [1/4]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>> annotated_ptr& sycl::_V1::ext::oneapi::experimental::operator++ () delete noexcept
Definition at line 421 of file annotated_ptr.hpp.
References m_Ptr.
operator++() [2/4]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>> auto sycl::_V1::ext::oneapi::experimental::operator++ () -> decltype("operator++ is not available when alignment is specified!")=delete delete noexcept
Definition at line 421 of file annotated_ptr.hpp.
References m_Ptr.
operator++() [3/4]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>> annotated_ptr sycl::_V1::ext::oneapi::experimental::operator++ (int) delete noexcept
Definition at line 432 of file annotated_ptr.hpp.
References m_Ptr.
operator++() [4/4]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>> auto sycl::_V1::ext::oneapi::experimental::operator++ (int) -> decltype("operator++ is not available when alignment is specified!")=delete delete noexcept
Definition at line 432 of file annotated_ptr.hpp.
References m_Ptr.
operator-()
std::ptrdiff_t sycl::_V1::ext::oneapi::experimental::operator- (annotated_ptr other) const noexcept
Definition at line 376 of file annotated_ptr.hpp.
References m_Ptr.
operator--() [1/4]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>> annotated_ptr& sycl::_V1::ext::oneapi::experimental::operator-- () delete noexcept
Definition at line 444 of file annotated_ptr.hpp.
References m_Ptr.
operator--() [2/4]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>> auto sycl::_V1::ext::oneapi::experimental::operator-- () -> decltype("operator-- is not available when alignment is specified!")=delete delete noexcept
Definition at line 444 of file annotated_ptr.hpp.
References m_Ptr.
operator--() [3/4]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<!has_alignment>> annotated_ptr sycl::_V1::ext::oneapi::experimental::operator-- (int) delete noexcept
Definition at line 455 of file annotated_ptr.hpp.
References m_Ptr.
operator--() [4/4]
template<bool has_alignment = detail::contains_alignment<Props...>::value, class = std::enable_if_t<has_alignment>> auto sycl::_V1::ext::oneapi::experimental::operator-- (int) -> decltype("operator-- is not available when alignment is specified!")=delete delete noexcept
Definition at line 455 of file annotated_ptr.hpp.
References m_Ptr.
operator->()
T* sycl::_V1::ext::oneapi::experimental::operator-> () const noexcept
Definition at line 189 of file annotated_arg.hpp.
References obj.
operator=() [1/2]
annotated_arg & sycl::_V1::ext::oneapi::experimental::operator= (annotated_arg &) default
Referenced by sycl::_V1::ext::intel::esimd::detail::simd_mask_impl< T, N >::operator=(), and sycl::_V1::ext::intel::esimd::simd_view< BaseTy, RegionTy >::operator=().
operator=() [2/2]
annotated_ptr& sycl::_V1::ext::oneapi::experimental::operator= (const annotated_ptr &) default
operator==()
template<typename PropertyT , typename... A, typename... B> constexpr std::enable_if_t<detail::IsCompileTimeProperty<PropertyT>::value, bool> sycl::_V1::ext::oneapi::experimental::operator== (const property_value< PropertyT, A... > & , const property_value< PropertyT, B... > &) constexpr
Definition at line 47 of file property_value.hpp.
operator[]()
T& sycl::_V1::ext::oneapi::experimental::operator[] (std::ptrdiff_t idx) const noexcept
Definition at line 187 of file annotated_arg.hpp.
References obj.
parallel_for() [1/8]
template<int Dimensions, typename Properties , typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::parallel_for (handler & CGH, launch_config< range< Dimensions >, Properties > Config, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 183 of file enqueue_functions.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::LaunchConfigAccess< LCRangeT, LCPropertiesT >::getRange(), sycl::_V1::handler::parallel_for(), and sycl::_V1::handler::set_args().
parallel_for() [2/8]
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename Properties , typename KernelType , typename... ReductionsT> void sycl::_V1::ext::oneapi::experimental::parallel_for (handler & CGH, launch_config< range< Dimensions >, Properties > Config, const KernelType & KernelObj, ReductionsT &&... Reductions)
Definition at line 146 of file enqueue_functions.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::LaunchConfigAccess< LCRangeT, LCPropertiesT >::getRange(), and sycl::_V1::handler::parallel_for().
parallel_for() [3/8]
template<int Dimensions, typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::parallel_for (handler & CGH, range< Dimensions > Range, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 168 of file enqueue_functions.hpp.
References sycl::_V1::handler::parallel_for(), and sycl::_V1::handler::set_args().
parallel_for() [4/8]
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename KernelType , typename... ReductionsT> void sycl::_V1::ext::oneapi::experimental::parallel_for (handler & CGH, range< Dimensions > Range, const KernelType & KernelObj, ReductionsT &&... Reductions)
Definition at line 128 of file enqueue_functions.hpp.
References sycl::_V1::handler::parallel_for().
Referenced by parallel_for().
parallel_for() [5/8]
template<int Dimensions, typename Properties , typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::parallel_for (queue Q, launch_config< range< Dimensions >, Properties > Config, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 194 of file enqueue_functions.hpp.
References parallel_for(), and submit().
parallel_for() [6/8]
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename Properties , typename KernelType , typename... ReductionsT> void sycl::_V1::ext::oneapi::experimental::parallel_for (queue Q, launch_config< range< Dimensions >, Properties > Config, const KernelType & KernelObj, ReductionsT &&... Reductions)
Definition at line 159 of file enqueue_functions.hpp.
References submit().
parallel_for() [7/8]
template<int Dimensions, typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::parallel_for (queue Q, range< Dimensions > Range, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 175 of file enqueue_functions.hpp.
References parallel_for(), and submit().
parallel_for() [8/8]
template<typename KernelName = sycl::detail::auto_name, int Dimensions, typename KernelType , typename... ReductionsT> void sycl::_V1::ext::oneapi::experimental::parallel_for (queue Q, range< Dimensions > Range, const KernelType & KernelObj, ReductionsT &&... Reductions)
Definition at line 136 of file enqueue_functions.hpp.
References submit().
partial_barrier() [1/2]
void sycl::_V1::ext::oneapi::experimental::partial_barrier (handler & CGH, const std::vector< event > & Events) inline
Definition at line 342 of file enqueue_functions.hpp.
References sycl::_V1::handler::ext_oneapi_barrier().
Referenced by partial_barrier().
partial_barrier() [2/2]
void sycl::_V1::ext::oneapi::experimental::partial_barrier (queue Q, const std::vector< event > & Events, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current()) inline
Definition at line 346 of file enqueue_functions.hpp.
References partial_barrier(), and submit().
pitched_alloc_device() [1/4]
void * sycl::_V1::ext::oneapi::experimental::pitched_alloc_device (size_t * resultPitch, const image_descriptor & desc, const sycl::device & syclDevice, const sycl::context & syclContext)
Allocate pitched USM image memory.
Parameters
resultPitch The allocation pitch value
desc The image descriptor
syclDevice The device
syclContext The context
Returns
Generic pointer to allocated USM image memory
Definition at line 900 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::getImageElementSize(), sycl::_V1::ext::oneapi::experimental::image_descriptor::height, sycl::_V1::ext::oneapi::experimental::image_descriptor::num_channels, pitched_alloc_device(), and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
pitched_alloc_device() [2/4]
void * sycl::_V1::ext::oneapi::experimental::pitched_alloc_device (size_t * resultPitch, const image_descriptor & desc, const sycl::queue & syclQueue)
Allocate pitched USM image memory.
Parameters
resultPitch The allocation pitch value
desc The image descriptor
syclQueue The queue
Returns
Generic pointer to allocated USM image memory
Definition at line 893 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and pitched_alloc_device().
pitched_alloc_device() [3/4]
void * sycl::_V1::ext::oneapi::experimental::pitched_alloc_device (size_t * resultPitch, size_t widthInBytes, size_t height, unsigned int elementSizeBytes, const sycl::device & syclDevice, const sycl::context & syclContext)
Allocate pitched USM image memory.
Parameters
resultPitch The allocation pitch value
widthInBytes The width of the image in bytes
height The height of the image in elements
elementSizeBytes Number of bytes of a singular image element
syclDevice The device
syclContext The context
Returns
Generic pointer to allocated USM image memory
Definition at line 852 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and piextUSMPitchedAlloc().
pitched_alloc_device() [4/4]
void * sycl::_V1::ext::oneapi::experimental::pitched_alloc_device (size_t * resultPitch, size_t widthInBytes, size_t height, unsigned int elementSizeBytes, const sycl::queue & syclQueue)
Allocate pitched USM image memory.
Parameters
resultPitch The allocation pitch value
widthInBytes The width of the image in bytes
height The height of the image in elements
elementSizeBytes Number of bytes of a singular image element
syclQueue The queue
Returns
Generic pointer to allocated USM image memory
Definition at line 884 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), and sycl::_V1::queue::get_device().
Referenced by pitched_alloc_device().
polar()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::polar (const _Tp & __rho, const _Tp & __theta = _Tp())
Definition at line 220 of file complex_math.hpp.
References isnan().
Referenced by sqrt().
populate_pi_structs()
void sycl::_V1::ext::oneapi::experimental::populate_pi_structs (const image_descriptor & desc, pi_image_desc & piDesc, pi_image_format & piFormat, size_t pitch = 0)
Definition at line 25 of file bindless_images.cpp.
References sycl::_V1::ext::oneapi::experimental::image_descriptor::array_size, _pi_image_desc::buffer, sycl::_V1::ext::oneapi::experimental::image_descriptor::channel_type, sycl::_V1::detail::convertChannelOrder(), sycl::_V1::detail::convertChannelType(), cubemap, sycl::_V1::ext::oneapi::experimental::image_descriptor::depth, sycl::_V1::ext::oneapi::experimental::detail::get_image_default_channel_order(), sycl::_V1::ext::oneapi::experimental::image_descriptor::height, _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_row_pitch, _pi_image_desc::image_slice_pitch, _pi_image_desc::image_type, _pi_image_desc::image_width, sycl::_V1::ext::oneapi::experimental::image_descriptor::num_channels, sycl::_V1::ext::oneapi::experimental::image_descriptor::num_levels, _pi_image_desc::num_mip_levels, _pi_image_desc::num_samples, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_MEM_TYPE_IMAGE_CUBEMAP, sycl::_V1::ext::oneapi::experimental::image_descriptor::type, and sycl::_V1::ext::oneapi::experimental::image_descriptor::width.
Referenced by alloc_image_mem(), alloc_mipmap_mem(), create_image(), and map_external_image_memory().
pow() [1/4]
template<class _Tp , class _Up > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat<_Tp>::value && is_genfloat<_Up>::value, complex<typename cplx::detail::__promote<_Tp, _Up>::type> > sycl::_V1::ext::oneapi::experimental::pow (const _Tp & __x, const complex< _Up > & __y)
Definition at line 338 of file complex_math.hpp.
References pow().
pow() [2/4]
template<class _Tp , class _Up > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat<_Tp>::value && is_genfloat<_Up>::value, complex<typename cplx::detail::__promote<_Tp, _Up>::type> > sycl::_V1::ext::oneapi::experimental::pow (const complex< _Tp > & __x, const _Up & __y)
Definition at line 328 of file complex_math.hpp.
References pow().
pow() [3/4]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::pow (const complex< _Tp > & __x, const complex< _Tp > & __y)
Definition at line 309 of file complex_math.hpp.
References exp(), and log().
Referenced by pow().
pow() [4/4]
template<class _Tp , class _Up > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t< is_genfloat<_Tp>::value, complex<typename cplx::detail::__promote<_Tp, _Up>::type> > sycl::_V1::ext::oneapi::experimental::pow (const complex< _Tp > & __x, const complex< _Up > & __y)
Definition at line 318 of file complex_math.hpp.
References pow().
prefetch() [1/12]
template<typename DataT , int Dimensions, access_mode AccessMode, access::placeholder IsPlaceholder, typename Properties = empty_properties_t, typename AccessorProperties = empty_properties_t> std::enable_if_t<detail::check_prefetch_acc_mode<AccessMode> && (Dimensions > 0) && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (accessor< DataT, Dimensions, AccessMode, target::device, IsPlaceholder, AccessorProperties > acc, id< Dimensions > offset, Properties properties = {})
Definition at line 172 of file prefetch.hpp.
prefetch() [2/12]
template<typename DataT , int Dimensions, access_mode AccessMode, access::placeholder IsPlaceholder, typename Properties = empty_properties_t, typename AccessorProperties = empty_properties_t> std::enable_if_t<detail::check_prefetch_acc_mode<AccessMode> && (Dimensions > 0) && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (accessor< DataT, Dimensions, AccessMode, target::device, IsPlaceholder, AccessorProperties > acc, size_t offset, size_t count, Properties properties = {})
Definition at line 186 of file prefetch.hpp.
prefetch() [3/12]
void sycl::_V1::ext::oneapi::experimental::prefetch (handler & CGH, void * Ptr, size_t NumBytes) inline
Definition at line 317 of file enqueue_functions.hpp.
References sycl::_V1::handler::prefetch().
Referenced by prefetch().
prefetch() [4/12]
template<typename T , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t> std::enable_if_t<detail::check_prefetch_AS<AddressSpace> && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (multi_ptr< T, AddressSpace, IsDecorated > ptr, Properties properties = {})
Definition at line 150 of file prefetch.hpp.
prefetch() [5/12]
template<typename T , access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t> std::enable_if_t<detail::check_prefetch_AS<AddressSpace> && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (multi_ptr< T, AddressSpace, IsDecorated > ptr, size_t count, Properties properties = {})
Definition at line 160 of file prefetch.hpp.
prefetch() [6/12]
template<access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t> std::enable_if_t<detail::check_prefetch_AS<AddressSpace> && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (multi_ptr< void, AddressSpace, IsDecorated > ptr, Properties properties = {})
Definition at line 131 of file prefetch.hpp.
prefetch() [7/12]
template<access::address_space AddressSpace, access::decorated IsDecorated, typename Properties = empty_properties_t> std::enable_if_t<detail::check_prefetch_AS<AddressSpace> && is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (multi_ptr< void, AddressSpace, IsDecorated > ptr, size_t bytes, Properties properties = {})
Definition at line 140 of file prefetch.hpp.
prefetch() [8/12]
void sycl::_V1::ext::oneapi::experimental::prefetch (queue Q, void * Ptr, size_t NumBytes, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current()) inline
Definition at line 321 of file enqueue_functions.hpp.
References prefetch(), and submit().
prefetch() [9/12]
template<typename T , typename Properties = empty_properties_t> std::enable_if_t<is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (T * ptr, Properties properties = {})
Definition at line 117 of file prefetch.hpp.
prefetch() [10/12]
template<typename T , typename Properties = empty_properties_t> std::enable_if_t<is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (T * ptr, size_t count, Properties properties = {})
Definition at line 123 of file prefetch.hpp.
prefetch() [11/12]
template<typename Properties = empty_properties_t> std::enable_if_t<is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (void * ptr, Properties properties = {})
Definition at line 105 of file prefetch.hpp.
prefetch() [12/12]
template<typename Properties = empty_properties_t> std::enable_if_t<is_property_list_v<std::decay_t<Properties> > > sycl::_V1::ext::oneapi::experimental::prefetch (void * ptr, size_t bytes, Properties properties = {})
Definition at line 111 of file prefetch.hpp.
prepare_for_device_copy() [1/2]
void sycl::_V1::ext::oneapi::experimental::prepare_for_device_copy (const void * Ptr, size_t Size, const context & Context)
Definition at line 688 of file usm_impl.cpp.
References sycl::_V1::prepare_for_usm_device_copy().
prepare_for_device_copy() [2/2]
void sycl::_V1::ext::oneapi::experimental::prepare_for_device_copy (const void * Ptr, size_t Size, const queue & Queue)
Definition at line 693 of file usm_impl.cpp.
References sycl::_V1::queue::get_context(), and sycl::_V1::prepare_for_usm_device_copy().
printf()
template<typename FormatT , typename... Args> int sycl::_V1::ext::oneapi::experimental::printf (const FormatT * __format, Args... args)
Definition at line 79 of file builtins.hpp.
Referenced by sycl::_V1::detail::stream_impl::flush().
private_alloca()
template<typename ElementType , auto & SizeSpecName, access::decorated DecorateAddress> private_ptr<ElementType, DecorateAddress> sycl::_V1::ext::oneapi::experimental::private_alloca (kernel_handler & kh)
Definition at line 63 of file alloca.hpp.
proj() [1/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits<_Tp>::_ComplexType sycl::_V1::ext::oneapi::experimental::proj (_Tp __re)
Definition at line 202 of file complex_math.hpp.
References sycl::_V1::ext::oneapi::fabs().
proj() [2/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::proj (const complex< _Tp > & __c)
Definition at line 192 of file complex_math.hpp.
References sycl::_V1::ext::intel::math::copysign().
real() [1/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL constexpr _SYCL_EXT_CPLX_INLINE_VISIBILITY cplx::detail::__libcpp_complex_overload_traits<_Tp>::_ValueType sycl::_V1::ext::oneapi::experimental::real (_Tp __re) constexpr
Definition at line 607 of file complex_math.hpp.
real() [2/2]
template<class _Tp > __DPCPP_SYCL_EXTERNAL constexpr _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, _Tp> sycl::_V1::ext::oneapi::experimental::real (const complex< _Tp > & __c) constexpr
Definition at line 600 of file complex_math.hpp.
reduce_over_group() [1/2]
template<typename GroupHelper , typename T , typename BinaryOperation > std::enable_if_t<(is_group_helper_v<GroupHelper>), T> sycl::_V1::ext::oneapi::experimental::reduce_over_group (GroupHelper group_helper, T x, BinaryOperation binary_op)
Definition at line 49 of file user_defined_reductions.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::reduce_over_group_impl().
Referenced by reduce_over_group().
reduce_over_group() [2/2]
template<typename GroupHelper , typename V , typename T , typename BinaryOperation > std::enable_if_t<(is_group_helper_v<GroupHelper>), T> sycl::_V1::ext::oneapi::experimental::reduce_over_group (GroupHelper group_helper, V x, T init, BinaryOperation binary_op)
Definition at line 66 of file user_defined_reductions.hpp.
References reduce_over_group().
release_external_memory() [1/2]
void sycl::_V1::ext::oneapi::experimental::release_external_memory (interop_mem_handle interopHandle, const sycl::device & syclDevice, const sycl::context & syclContext)
Release external memory.
Parameters
interopHandle The interop memory handle to release
syclDevice The device in which the interop memory handle was created
syclContext The context in which the interop memory handle was created
Definition at line 636 of file bindless_images.cpp.
References sycl::_V1::detail::getSyclObjImpl(), piextMemReleaseInterop(), and sycl::_V1::ext::oneapi::experimental::interop_mem_handle::raw_handle.
Referenced by release_external_memory().
release_external_memory() [2/2]
void sycl::_V1::ext::oneapi::experimental::release_external_memory (interop_mem_handle interopHandle, const sycl::queue & syclQueue)
Release external memory.
Parameters
interopHandle The interop memory handle to release
syclQueue The queue in which the interop memory handle was created
Definition at line 652 of file bindless_images.cpp.
References sycl::_V1::queue::get_context(), sycl::_V1::queue::get_device(), and release_external_memory().
release_from_device_copy() [1/2]
void sycl::_V1::ext::oneapi::experimental::release_from_device_copy (const void * Ptr, const context & Context)
Definition at line 697 of file usm_impl.cpp.
References sycl::_V1::release_from_usm_device_copy().
release_from_device_copy() [2/2]
void sycl::_V1::ext::oneapi::experimental::release_from_device_copy (const void * Ptr, const queue & Queue)
Definition at line 701 of file usm_impl.cpp.
References sycl::_V1::queue::get_context(), and sycl::_V1::release_from_usm_device_copy().
reserve_virtual_mem() [1/2]
uintptr_t sycl::_V1::ext::oneapi::experimental::reserve_virtual_mem (size_t NumBytes, const context & SyclContext) inline
Definition at line 40 of file virtual_mem.hpp.
References reserve_virtual_mem().
reserve_virtual_mem() [2/2]
uintptr_t sycl::_V1::ext::oneapi::experimental::reserve_virtual_mem (uintptr_t Start, size_t NumBytes, const context & SyclContext)
Definition at line 103 of file virtual_mem.cpp.
References any_of(), sycl::_V1::context::get_devices(), sycl::_V1::detail::getSyclObjImpl(), and piextVirtualMemReserve().
Referenced by reserve_virtual_mem().
sample_cubemap()
template<typename DataT , typename HintT = DataT> DataT sycl::_V1::ext::oneapi::experimental::sample_cubemap (const sampled_image_handle &imageHandle] [[maybe_unused], const sycl::float3 &dirVec] [[maybe_unused])
Sample a cubemap image using its handle.
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
Parameters
imageHandle The image handle
dirVec The direction vector at which to sample image data (float3 only)
Returns
Image data
Definition at line 1363 of file bindless_images.hpp.
sample_image()
template<typename DataT , typename HintT = DataT, typename CoordT > DataT sycl::_V1::ext::oneapi::experimental::sample_image (const sampled_image_handle &imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused])
Sample data from a sampled image using its handle.
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. float, float2, or float3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The image handle
coords The coordinates at which to sample image data
Returns
Sampled image data
NVPTX: Name mangling info Cuda surfaces require integer coords (by bytes) Cuda textures require float coords (by element or normalized) for sampling, and integer coords (by bytes) for fetching The name mangling should therefore not interfere with one another
Definition at line 1018 of file bindless_images.hpp.
References coords.
sample_image_array()
template<typename DataT , typename HintT = DataT, typename CoordT > DataT sycl::_V1::ext::oneapi::experimental::sample_image_array (const sampled_image_handle &imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused], unsigned int arrayLayer] [[maybe_unused])
Sample data from a sampled image array using its handle.
Template Parameters
DataT The return type.
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. int or int2 for 1D or 2D, respectively.
Parameters
imageHandle The image handle.
coords The coordinates at which to fetch image data.
arrayLayer The image array layer at which to fetch.
Returns
Image data.
Definition at line 1446 of file bindless_images.hpp.
References coords.
sample_mipmap() [1/2]
template<typename DataT , typename HintT = DataT, typename CoordT > DataT sycl::_V1::ext::oneapi::experimental::sample_mipmap (const sampled_image_handle &imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused], const CoordT &dX] [[maybe_unused], const CoordT &dY] [[maybe_unused])
Sample a mipmap image using its handle with anisotropic filtering.
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. float, float2, or float3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The mipmap image handle
coords The coordinates at which to sample mipmap image data
dX Screen space gradient in the x dimension
dY Screen space gradient in the y dimension
Returns
Mipmap image data with anisotropic filtering
Definition at line 1143 of file bindless_images.hpp.
References coords, dX, and dY.
sample_mipmap() [2/2]
template<typename DataT , typename HintT = DataT, typename CoordT > DataT sycl::_V1::ext::oneapi::experimental::sample_mipmap (const sampled_image_handle &imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused], const float level] [[maybe_unused])
Sample a mipmap image using its handle with LOD filtering.
Template Parameters
DataT The return type
HintT A hint type that can be used to select for a specialized backend intrinsic when a user-defined type is passed as DataT. HintT should be a sycl::vec type, sycl::half type, or POD type. HintT must also have the same size as DataT.
CoordT The input coordinate type. e.g. float, float2, or float3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The mipmap image handle
coords The coordinates at which to sample mipmap image data
level The mipmap level at which to sample
Returns
Mipmap image data with LOD filtering
Definition at line 1097 of file bindless_images.hpp.
References coords, and level.
set_access_mode()
void sycl::_V1::ext::oneapi::experimental::set_access_mode (const void * Ptr, size_t NumBytes, address_access_mode Mode, const context & SyclContext)
Definition at line 133 of file virtual_mem.cpp.
References sycl::_V1::detail::AccessModeToVirtualAccessFlags(), sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::Mode, and piextVirtualMemSetAccess().
sin()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::sin (const complex< _Tp > & __x)
Definition at line 571 of file complex_math.hpp.
References sinh().
single_task() [1/4]
template<typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::single_task (handler & CGH, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 113 of file enqueue_functions.hpp.
References sycl::_V1::handler::set_args(), and sycl::_V1::handler::single_task().
single_task() [2/4]
template<typename KernelName = sycl::detail::auto_name, typename KernelType > void sycl::_V1::ext::oneapi::experimental::single_task (handler & CGH, const KernelType & KernelObj)
Definition at line 99 of file enqueue_functions.hpp.
References sycl::_V1::handler::single_task().
Referenced by single_task().
single_task() [3/4]
template<typename... ArgsT> void sycl::_V1::ext::oneapi::experimental::single_task (queue Q, const kernel & KernelObj, ArgsT &&... Args)
Definition at line 119 of file enqueue_functions.hpp.
References single_task(), and submit().
single_task() [4/4]
template<typename KernelName = sycl::detail::auto_name, typename KernelType > void sycl::_V1::ext::oneapi::experimental::single_task (queue Q, const KernelType & KernelObj, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current())
Definition at line 104 of file enqueue_functions.hpp.
References submit().
sinh()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::sinh (const complex< _Tp > & __x)
Definition at line 457 of file complex_math.hpp.
References cosh().
Referenced by cosh(), sin(), and tanh().
sort_key_value_over_group() [1/3]
template<typename Group , typename KeyTy , typename ValueTy , typename Sorter > std::enable_if_t< detail::is_key_value_sorter<Sorter, Group, KeyTy, ValueTy>::value, std::tuple<KeyTy, ValueTy> > sycl::_V1::ext::oneapi::experimental::sort_key_value_over_group ([[maybe_unused] ] Group g, [[maybe_unused] ] KeyTy key, [[maybe_unused] ] ValueTy value, [[maybe_unused] ] Sorter sorter)
Definition at line 204 of file group_sort.hpp.
Referenced by sort_key_value_over_group().
sort_key_value_over_group() [2/3]
template<typename KeyTy , typename ValueTy , typename Group , std::size_t Extent> std::enable_if_t<sycl::is_group_v<std::decay_t<Group> >, std::tuple<KeyTy, ValueTy> > sycl::_V1::ext::oneapi::experimental::sort_key_value_over_group (experimental::group_with_scratchpad< Group, Extent > exec, KeyTy key, ValueTy value)
Definition at line 233 of file group_sort.hpp.
References sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_group(), sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_memory(), and sort_key_value_over_group().
sort_key_value_over_group() [3/3]
template<typename Group , typename KeyTy , typename ValueTy , typename Compare , std::size_t Extent> std::enable_if_t< !detail::is_key_value_sorter<Compare, Group, KeyTy, ValueTy>::value, std::tuple<KeyTy, ValueTy> > sycl::_V1::ext::oneapi::experimental::sort_key_value_over_group (experimental::group_with_scratchpad< Group, Extent > exec, KeyTy key, ValueTy value, Compare comp)
Definition at line 221 of file group_sort.hpp.
References sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_group(), sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_memory(), and sort_key_value_over_group().
sort_over_group() [1/6]
template<typename Group , typename T , std::size_t ElementsPerWorkItem, typename Sorter , typename Properties = ext::oneapi::experimental::empty_properties_t> std::enable_if_t<sycl::ext::oneapi::experimental::is_property_list_v< std::decay_t<Properties> >, void> sycl::_V1::ext::oneapi::experimental::sort_over_group ([[maybe_unused] ] Group g, [[maybe_unused] ] sycl::span< T, ElementsPerWorkItem > values, [[maybe_unused] ] Sorter sorter, [[maybe_unused] ] Properties properties = {})
Definition at line 123 of file group_sort.hpp.
sort_over_group() [2/6]
template<typename Group , typename T , typename Sorter > std::enable_if_t<detail::is_sorter<Sorter, Group, T>::value, T> sycl::_V1::ext::oneapi::experimental::sort_over_group ([[maybe_unused] ] Group group, [[maybe_unused] ] T value, [[maybe_unused] ] Sorter sorter)
Definition at line 89 of file group_sort.hpp.
Referenced by sort_over_group().
sort_over_group() [3/6]
template<typename Group , typename T , std::size_t Extent, std::size_t ElementsPerWorkItem, typename Compare , typename Properties = ext::oneapi::experimental::empty_properties_t> std::enable_if_t<!sycl::ext::oneapi::experimental::is_property_list_v< std::decay_t<Compare> > && sycl::ext::oneapi::experimental::is_property_list_v< std::decay_t<Properties> >, void> sycl::_V1::ext::oneapi::experimental::sort_over_group (experimental::group_with_scratchpad< Group, Extent > exec, sycl::span< T, ElementsPerWorkItem > values, Compare comp, Properties properties = {})
Definition at line 160 of file group_sort.hpp.
sort_over_group() [4/6]
template<typename Group , typename T , std::size_t Extent, std::size_t ElementsPerWorkItem, typename Properties = ext::oneapi::experimental::empty_properties_t> std::enable_if_t<sycl::ext::oneapi::experimental::is_property_list_v< std::decay_t<Properties> >, void> sycl::_V1::ext::oneapi::experimental::sort_over_group (experimental::group_with_scratchpad< Group, Extent > exec, sycl::span< T, ElementsPerWorkItem > values, Properties properties = {})
Definition at line 142 of file group_sort.hpp.
sort_over_group() [5/6]
template<typename Group , typename T , size_t Extent> std::enable_if_t<sycl::is_group_v<std::decay_t<Group> >, T> sycl::_V1::ext::oneapi::experimental::sort_over_group (experimental::group_with_scratchpad< Group, Extent > exec, T value)
Definition at line 111 of file group_sort.hpp.
References sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_group(), sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_memory(), and sort_over_group().
sort_over_group() [6/6]
template<typename Group , typename T , typename Compare , size_t Extent> std::enable_if_t<!detail::is_sorter<Compare, Group, T>::value, T> sycl::_V1::ext::oneapi::experimental::sort_over_group (experimental::group_with_scratchpad< Group, Extent > exec, T value, Compare comp)
Definition at line 102 of file group_sort.hpp.
References sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_group(), sycl::_V1::ext::oneapi::experimental::group_with_scratchpad< Group, Extent >::get_memory(), and sort_over_group().
sqrt()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::sqrt (const complex< _Tp > & __x)
Definition at line 265 of file complex_math.hpp.
References abs(), arg(), sycl::_V1::ext::intel::math::copysign(), isnan(), and polar().
Referenced by acos(), acosh(), and asinh().
static_address_cast()
template<access::address_space Space, access::decorated DecorateAddress, typename ElementType > multi_ptr<ElementType, Space, DecorateAddress> sycl::_V1::ext::oneapi::experimental::static_address_cast (ElementType * Ptr)
Definition at line 23 of file address_cast.hpp.
submit()
template<typename CommandGroupFunc > void sycl::_V1::ext::oneapi::experimental::submit (queue Q, CommandGroupFunc && CGF, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current())
Definition at line 84 of file enqueue_functions.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::submit_impl().
Referenced by barrier(), sycl::_V1::queue::copy(), copy(), sycl::_V1::queue::ext_oneapi_graph(), sycl::_V1::queue::ext_oneapi_memcpy2d(), sycl::_V1::queue::ext_oneapi_wait_external_semaphore(), fill(), sycl::_V1::queue::fill(), sycl::_V1::queue::memcpy(), nd_launch(), sycl::_V1::queue::parallel_for(), parallel_for(), sycl::_V1::queue::parallel_for_impl(), partial_barrier(), sycl::_V1::queue::prefetch(), prefetch(), sycl::_V1::queue::single_task(), single_task(), and sycl::_V1::queue::update_host().
submit_profiling_tag()
event sycl::_V1::ext::oneapi::experimental::submit_profiling_tag (queue & Queue, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current()) inline
Definition at line 21 of file profiling_tag.hpp.
References sycl::_V1::queue::ext_oneapi_submit_barrier(), sycl::_V1::queue::get_device(), sycl::_V1::device::has(), sycl::_V1::queue::has_property(), sycl::_V1::invalid, sycl::_V1::make_error_code(), and sycl::_V1::queue::submit().
submit_with_event()
template<typename CommandGroupFunc > event sycl::_V1::ext::oneapi::experimental::submit_with_event (queue Q, CommandGroupFunc && CGF, const sycl::detail::code_location & CodeLoc = sycl::detail::code_location::current())
Definition at line 92 of file enqueue_functions.hpp.
References sycl::_V1::queue::submit().
tan()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::tan (const complex< _Tp > & __x)
Definition at line 590 of file complex_math.hpp.
References tanh().
tanh()
template<class _Tp > __DPCPP_SYCL_EXTERNAL _SYCL_EXT_CPLX_INLINE_VISIBILITY std::enable_if_t<is_genfloat<_Tp>::value, complex<_Tp> > sycl::_V1::ext::oneapi::experimental::tanh (const complex< _Tp > & __x)
Definition at line 491 of file complex_math.hpp.
References sycl::_V1::ext::intel::math::copysign(), cosh(), isnan(), and sinh().
Referenced by tan().
unmap()
void sycl::_V1::ext::oneapi::experimental::unmap (const void * Ptr, size_t NumBytes, const context & SyclContext)
Definition at line 172 of file virtual_mem.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and piextVirtualMemUnmap().
write_cubemap()
template<typename DataT > void sycl::_V1::ext::oneapi::experimental::write_cubemap (unsampled_image_handle imageHandle, const sycl::int2 & coords, int face, const DataT & color)
Write to an unsampled cubemap using its handle.
Template Parameters
DataT The data type to write
Parameters
imageHandle The image handle
coords The coordinates at which to write image data (int2 only)
face The cubemap face at which to write
color The data to write
Definition at line 1566 of file bindless_images.hpp.
References coords, and write_image_array().
write_image()
template<typename DataT , typename CoordT > void sycl::_V1::ext::oneapi::experimental::write_image (unsampled_image_handle imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused], const DataT &color] [[maybe_unused])
Write to an unsampled image using its handle.
Template Parameters
DataT The data type to write
CoordT The input coordinate type. e.g. int, int2, or int3 for 1D, 2D, and 3D, respectively
Parameters
imageHandle The image handle
coords The coordinates at which to write image data
color The data to write
Definition at line 1485 of file bindless_images.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::convert_color(), and coords.
write_image_array()
template<typename DataT , typename CoordT > void sycl::_V1::ext::oneapi::experimental::write_image_array (unsampled_image_handle imageHandle] [[maybe_unused], const CoordT &coords] [[maybe_unused], unsigned int arrayLayer] [[maybe_unused], const DataT &color] [[maybe_unused])
Write to an unsampled image array using its handle.
Template Parameters
DataT The data type to write
CoordT The input coordinate type. e.g. int or int2 for 1D or 2D, respectively
Parameters
imageHandle The image handle
coords The coordinates at which to write image data
arrayLayer The image array layer at which to write
color The data to write
Definition at line 1525 of file bindless_images.hpp.
References sycl::_V1::ext::oneapi::experimental::detail::convert_color(), and coords.
Referenced by write_cubemap().
Variable Documentation
alignment
template<int K> constexpr alignment_key::value_t<K> sycl::_V1::ext::oneapi::experimental::alignment inline constexpr
Definition at line 75 of file properties.hpp.
calls_indirectly
template<typename First = void, typename... Rest> constexpr calls_indirectly_key::value_t<First, Rest...> sycl::_V1::ext::oneapi::experimental::calls_indirectly inline constexpr
Definition at line 27 of file virtual_functions.hpp.
contains_valid_properties [1/2]
static constexpr bool sycl::_V1::ext::oneapi::experimental::contains_valid_properties static constexpr
Initial value:
=
      check_property_list<T *, Props...>::value
Definition at line 210 of file annotated_arg.hpp.
contains_valid_properties [2/2]
constexpr bool sycl::_V1::ext::oneapi::experimental::contains_valid_properties static constexpr
Initial value:
=
      check_property_list<T *, Props...>::value
Definition at line 486 of file annotated_ptr.hpp.
contiguous_memory
constexpr contiguous_memory_key::value_t sycl::_V1::ext::oneapi::experimental::contiguous_memory inline constexpr
Definition at line 47 of file group_load_store.hpp.
coords
const CoordT & sycl::_V1::ext::oneapi::experimental::coords
Initial value:
{
  return fetch_image<DataT>(imageHandle, coords)
Definition at line 940 of file bindless_images.hpp.
Referenced by __SYCL_DEPRECATED(), fetch_cubemap(), fetch_image(), fetch_image_array(), if(), sample_image(), sample_image_array(), sample_mipmap(), write_cubemap(), write_image(), and write_image_array().
data_placement
template<data_placement_enum Placement> constexpr data_placement_key::value_t<Placement> sycl::_V1::ext::oneapi::experimental::data_placement inline constexpr
Definition at line 35 of file group_load_store.hpp.
data_placement_blocked
constexpr data_placement_key::value_t<data_placement_enum::blocked> sycl::_V1::ext::oneapi::experimental::data_placement_blocked inline constexpr
Definition at line 38 of file group_load_store.hpp.
data_placement_striped
constexpr data_placement_key::value_t<data_placement_enum::striped> sycl::_V1::ext::oneapi::experimental::data_placement_striped inline constexpr
Definition at line 40 of file group_load_store.hpp.
device_has
template<aspect... Aspects> constexpr device_has_key::value_t<Aspects...> sycl::_V1::ext::oneapi::experimental::device_has inline constexpr
Definition at line 152 of file properties.hpp.
Referenced by sycl::_V1::queue::submit().
device_image_scope
constexpr device_image_scope_key::value_t sycl::_V1::ext::oneapi::experimental::device_image_scope inline constexpr
Definition at line 56 of file properties.hpp.
dX
const CoordT const CoordT & sycl::_V1::ext::oneapi::experimental::dX
Definition at line 1220 of file bindless_images.hpp.
Referenced by sample_mipmap().
dY
const CoordT const CoordT const CoordT & sycl::_V1::ext::oneapi::experimental::dY
Initial value:
{
  return sample_mipmap<DataT>(imageHandle, coords, dX, dY)
Definition at line 1221 of file bindless_images.hpp.
Referenced by sample_mipmap().
full_group
constexpr full_group_key::value_t sycl::_V1::ext::oneapi::experimental::full_group inline constexpr
Definition at line 54 of file group_load_store.hpp.
has_alignment
constexpr bool sycl::_V1::ext::oneapi::experimental::has_alignment = has_property<alignment_key>() static constexpr
Definition at line 430 of file annotated_arg.hpp.
has_awidth
constexpr bool sycl::_V1::ext::oneapi::experimental::has_awidth = has_property<awidth_key>() static constexpr
Definition at line 402 of file annotated_arg.hpp.
has_buffer_location
constexpr bool sycl::_V1::ext::oneapi::experimental::has_buffer_location static constexpr
Initial value:
=
      has_property<buffer_location_key>()
Definition at line 396 of file annotated_arg.hpp.
has_dwidth
constexpr bool sycl::_V1::ext::oneapi::experimental::has_dwidth = has_property<dwidth_key>() static constexpr
Definition at line 406 of file annotated_arg.hpp.
has_latency
constexpr bool sycl::_V1::ext::oneapi::experimental::has_latency = has_property<latency_key>() static constexpr
Definition at line 410 of file annotated_arg.hpp.
has_maxburst
constexpr bool sycl::_V1::ext::oneapi::experimental::has_maxburst = has_property<maxburst_key>() static constexpr
Definition at line 420 of file annotated_arg.hpp.
has_read_write_mode
constexpr bool sycl::_V1::ext::oneapi::experimental::has_read_write_mode static constexpr
Initial value:
=
      has_property<read_write_mode_key>()
Definition at line 414 of file annotated_arg.hpp.
has_usm_kind
constexpr bool sycl::_V1::ext::oneapi::experimental::has_usm_kind = has_property<usm_kind_key>() static constexpr
Definition at line 435 of file annotated_arg.hpp.
has_wait_request
constexpr bool sycl::_V1::ext::oneapi::experimental::has_wait_request = has_property<wait_request_key>() static constexpr
Definition at line 425 of file annotated_arg.hpp.
hasConduitAndRegisterMapProperties [1/2]
static constexpr bool sycl::_V1::ext::oneapi::experimental::hasConduitAndRegisterMapProperties static constexpr
Initial value:
=
      detail::checkHasConduitAndRegisterMap<Props...>::value
Definition at line 221 of file annotated_arg.hpp.
hasConduitAndRegisterMapProperties [2/2]
constexpr bool sycl::_V1::ext::oneapi::experimental::hasConduitAndRegisterMapProperties static constexpr
Initial value:
=
      detail::checkHasConduitAndRegisterMap<Props...>::value
Definition at line 497 of file annotated_ptr.hpp.
hasValidFPGAProperties [1/2]
static constexpr bool sycl::_V1::ext::oneapi::experimental::hasValidFPGAProperties static constexpr
Initial value:
=
      detail::checkValidFPGAPropertySet<Props...>::value
Definition at line 215 of file annotated_arg.hpp.
hasValidFPGAProperties [2/2]
constexpr bool sycl::_V1::ext::oneapi::experimental::hasValidFPGAProperties static constexpr
Initial value:
=
      detail::checkValidFPGAPropertySet<Props...>::value
Definition at line 491 of file annotated_ptr.hpp.
host_access
template<host_access_enum Access> constexpr host_access_key::value_t<Access> sycl::_V1::ext::oneapi::experimental::host_access inline constexpr
Definition at line 59 of file properties.hpp.
host_access_none
constexpr host_access_key::value_t<host_access_enum::none> sycl::_V1::ext::oneapi::experimental::host_access_none inline constexpr
Definition at line 67 of file properties.hpp.
host_access_read
constexpr host_access_key::value_t<host_access_enum::read> sycl::_V1::ext::oneapi::experimental::host_access_read inline constexpr
Definition at line 61 of file properties.hpp.
host_access_read_write
constexpr host_access_key::value_t<host_access_enum::read_write> sycl::_V1::ext::oneapi::experimental::host_access_read_write inline constexpr
Definition at line 65 of file properties.hpp.
host_access_write
constexpr host_access_key::value_t<host_access_enum::write> sycl::_V1::ext::oneapi::experimental::host_access_write inline constexpr
Definition at line 63 of file properties.hpp.
implement_in_csr
template<bool Enable> constexpr implement_in_csr_key::value_t<Enable> sycl::_V1::ext::oneapi::experimental::implement_in_csr inline constexpr
Definition at line 76 of file properties.hpp.
implement_in_csr_off
constexpr implement_in_csr_key::value_t<false> sycl::_V1::ext::oneapi::experimental::implement_in_csr_off inline constexpr
Definition at line 78 of file properties.hpp.
implement_in_csr_on
constexpr implement_in_csr_key::value_t<true> sycl::_V1::ext::oneapi::experimental::implement_in_csr_on inline constexpr
Definition at line 77 of file properties.hpp.
indirectly_callable
template<typename Set = void> constexpr indirectly_callable_key::value_t<Set> sycl::_V1::ext::oneapi::experimental::indirectly_callable inline constexpr
Definition at line 17 of file virtual_functions.hpp.
init_mode
template<init_mode_enum Trigger> constexpr init_mode_key::value_t<Trigger> sycl::_V1::ext::oneapi::experimental::init_mode inline constexpr
Definition at line 70 of file properties.hpp.
init_mode_reprogram
constexpr init_mode_key::value_t<init_mode_enum::reprogram> sycl::_V1::ext::oneapi::experimental::init_mode_reprogram inline constexpr
Definition at line 72 of file properties.hpp.
init_mode_reset
constexpr init_mode_key::value_t<init_mode_enum::reset> sycl::_V1::ext::oneapi::experimental::init_mode_reset inline constexpr
Definition at line 73 of file properties.hpp.
input_data_placement
template<group_algorithm_data_placement Placement> constexpr input_data_placement_key::value_t<Placement> sycl::_V1::ext::oneapi::experimental::input_data_placement inline constexpr
Definition at line 60 of file group_helpers_sorters.hpp.
is_device_copyable
constexpr bool sycl::_V1::ext::oneapi::experimental::is_device_copyable = is_device_copyable_v<T> static constexpr
Definition at line 392 of file annotated_arg.hpp.
is_fixed_topology_group_v
template<class T > constexpr bool sycl::_V1::ext::oneapi::experimental::is_fixed_topology_group_v inline constexpr
Initial value:
=
    is_fixed_topology_group<T>::value
Definition at line 44 of file type_traits.hpp.
is_group_helper_v
template<class T > constexpr bool sycl::_V1::ext::oneapi::experimental::is_group_helper_v inline constexpr
Initial value:
=
    detail::is_group_helper<std::decay_t<T>>::value
Definition at line 113 of file type_traits.hpp.
is_user_constructed_group_v
template<class T > constexpr bool sycl::_V1::ext::oneapi::experimental::is_user_constructed_group_v inline constexpr
Initial value:
=
    is_user_constructed_group<T>::value
Definition at line 62 of file type_traits.hpp.
is_valid_property_list [1/2]
static constexpr bool sycl::_V1::ext::oneapi::experimental::is_valid_property_list static constexpr
Initial value:
=
      is_property_list<property_list_t>::value
Definition at line 207 of file annotated_arg.hpp.
is_valid_property_list [2/2]
constexpr bool sycl::_V1::ext::oneapi::experimental::is_valid_property_list static constexpr
Initial value:
=
      is_property_list<property_list_t>::value
Definition at line 483 of file annotated_ptr.hpp.
is_vec_or_swizzle_bf16_v
template<typename T > constexpr bool sycl::_V1::ext::oneapi::experimental::is_vec_or_swizzle_bf16_v constexpr
Initial value:
=
    sycl::detail::is_vec_or_swizzle_v<T> &&
    sycl::detail::is_valid_elem_type_v<T, bfloat16>
Definition at line 36 of file bfloat16_math.hpp.
level
const CoordT const float sycl::_V1::ext::oneapi::experimental::level
Initial value:
{
  return sample_mipmap<DataT>(imageHandle, coords, level)
Definition at line 1194 of file bindless_images.hpp.
Referenced by __SYCL_DEPRECATED(), sycl::_V1::ext::oneapi::experimental::image_descriptor::get_mip_level_desc(), get_mip_level_mem_handle(), sycl::_V1::ext::oneapi::experimental::image_mem::get_mip_level_mem_handle(), and sample_mipmap().
m_Ptr
T* sycl::_V1::ext::oneapi::experimental::m_Ptr
Definition at line 288 of file annotated_ptr.hpp.
Referenced by get(), operator bool(), sycl::_V1::ext::oneapi::experimental::annotated_ref< T, detail::properties_t< Props... > >::operator T(), operator*(), operator+(), operator++(), operator-(), operator--(), and sycl::_V1::ext::oneapi::experimental::annotated_ref< T, detail::properties_t< Props... > >::operator=().
nd_range_kernel
template<int Dims> constexpr nd_range_kernel_key::value_t<Dims> sycl::_V1::ext::oneapi::experimental::nd_range_kernel inline constexpr
Definition at line 155 of file properties.hpp.
num_elements_v
template<typename T > constexpr int sycl::_V1::ext::oneapi::experimental::num_elements_v = sycl::detail::num_elements<T>::value constexpr
Definition at line 41 of file bfloat16_math.hpp.
obj
T sycl::_V1::ext::oneapi::experimental::obj
Definition at line 87 of file annotated_arg.hpp.
Referenced by sycl::_V1::detail::get_or_store(), operator T(), operator T*(), operator->(), operator[](), and sycl::_V1::ext::oneapi::experimental::detail::verify_callable().
opencl_c_1_0
constexpr cl_version sycl::_V1::ext::oneapi::experimental::opencl_c_1_0 = {1, 0, 0} inline constexpr
Definition at line 32 of file kernel_bundle_enums.hpp.
opencl_c_1_1
constexpr cl_version sycl::_V1::ext::oneapi::experimental::opencl_c_1_1 = {1, 1, 0} inline constexpr
Definition at line 33 of file kernel_bundle_enums.hpp.
opencl_c_1_2
constexpr cl_version sycl::_V1::ext::oneapi::experimental::opencl_c_1_2 = {1, 2, 0} inline constexpr
Definition at line 34 of file kernel_bundle_enums.hpp.
opencl_c_2_0
constexpr cl_version sycl::_V1::ext::oneapi::experimental::opencl_c_2_0 = {2, 0, 0} inline constexpr
Definition at line 35 of file kernel_bundle_enums.hpp.
opencl_c_3_0
constexpr cl_version sycl::_V1::ext::oneapi::experimental::opencl_c_3_0 = {3, 0, 0} inline constexpr
Definition at line 36 of file kernel_bundle_enums.hpp.
output_data_placement
template<group_algorithm_data_placement Placement> constexpr output_data_placement_key::value_t<Placement> sycl::_V1::ext::oneapi::experimental::output_data_placement inline constexpr
Definition at line 64 of file group_helpers_sorters.hpp.
prefetch_hint
template<cache_level Level, typename Hint > constexpr prefetch_hint_key::value_t<Level, Hint> sycl::_V1::ext::oneapi::experimental::prefetch_hint inline constexpr
Definition at line 31 of file prefetch.hpp.
prefetch_hint_L1
constexpr prefetch_hint_key::value_t<cache_level::L1, void> sycl::_V1::ext::oneapi::experimental::prefetch_hint_L1 inline constexpr
Definition at line 34 of file prefetch.hpp.
prefetch_hint_L1_nt
constexpr prefetch_hint_key::value_t<cache_level::L1, nontemporal> sycl::_V1::ext::oneapi::experimental::prefetch_hint_L1_nt inline constexpr
Definition at line 43 of file prefetch.hpp.
prefetch_hint_L2
constexpr prefetch_hint_key::value_t<cache_level::L2, void> sycl::_V1::ext::oneapi::experimental::prefetch_hint_L2 inline constexpr
Definition at line 36 of file prefetch.hpp.
prefetch_hint_L2_nt
constexpr prefetch_hint_key::value_t<cache_level::L2, nontemporal> sycl::_V1::ext::oneapi::experimental::prefetch_hint_L2_nt inline constexpr
Definition at line 45 of file prefetch.hpp.
prefetch_hint_L3
constexpr prefetch_hint_key::value_t<cache_level::L3, void> sycl::_V1::ext::oneapi::experimental::prefetch_hint_L3 inline constexpr
Definition at line 38 of file prefetch.hpp.
prefetch_hint_L3_nt
constexpr prefetch_hint_key::value_t<cache_level::L3, nontemporal> sycl::_V1::ext::oneapi::experimental::prefetch_hint_L3_nt inline constexpr
Definition at line 47 of file prefetch.hpp.
prefetch_hint_L4
constexpr prefetch_hint_key::value_t<cache_level::L4, void> sycl::_V1::ext::oneapi::experimental::prefetch_hint_L4 inline constexpr
Definition at line 40 of file prefetch.hpp.
prefetch_hint_L4_nt
constexpr prefetch_hint_key::value_t<cache_level::L4, nontemporal> sycl::_V1::ext::oneapi::experimental::prefetch_hint_L4_nt inline constexpr
Definition at line 49 of file prefetch.hpp.
single_task_kernel
constexpr single_task_kernel_key::value_t sycl::_V1::ext::oneapi::experimental::single_task_kernel inline constexpr
Definition at line 157 of file properties.hpp.
sub_group_progress
template<forward_progress_guarantee Guarantee, execution_scope CoordinationScope> constexpr sub_group_progress_key::value_t<Guarantee, CoordinationScope> sycl::_V1::ext::oneapi::experimental::sub_group_progress inline constexpr
Definition at line 230 of file properties.hpp.
sub_group_size
template<uint32_t Size> constexpr sub_group_size_key::value_t<Size> sycl::_V1::ext::oneapi::experimental::sub_group_size inline constexpr
Definition at line 149 of file properties.hpp.
Referenced by syclcompat::device_ext::get_device_info().
use_root_sync
constexpr use_root_sync_key::value_t sycl::_V1::ext::oneapi::experimental::use_root_sync inline constexpr
Definition at line 25 of file use_root_sync_prop.hpp.
usm_kind
template<sycl::usm::alloc Kind> constexpr usm_kind_key::value_t<Kind> sycl::_V1::ext::oneapi::experimental::usm_kind inline constexpr
Definition at line 36 of file annotated_ptr_properties.hpp.
usm_kind_device
constexpr usm_kind_key::value_t<sycl::usm::alloc::device> sycl::_V1::ext::oneapi::experimental::usm_kind_device inline constexpr
Definition at line 38 of file annotated_ptr_properties.hpp.
usm_kind_host
constexpr usm_kind_key::value_t<sycl::usm::alloc::host> sycl::_V1::ext::oneapi::experimental::usm_kind_host inline constexpr
Definition at line 39 of file annotated_ptr_properties.hpp.
usm_kind_shared
constexpr usm_kind_key::value_t<sycl::usm::alloc::shared> sycl::_V1::ext::oneapi::experimental::usm_kind_shared inline constexpr
Definition at line 41 of file annotated_ptr_properties.hpp.
work_group_progress
template<forward_progress_guarantee Guarantee, execution_scope CoordinationScope> constexpr work_group_progress_key::value_t<Guarantee, CoordinationScope> sycl::_V1::ext::oneapi::experimental::work_group_progress inline constexpr
Definition at line 225 of file properties.hpp.
work_group_size
template<size_t Dim0, size_t... Dims> constexpr work_group_size_key::value_t<Dim0, Dims...> sycl::_V1::ext::oneapi::experimental::work_group_size inline constexpr
Definition at line 142 of file properties.hpp.
Referenced by syclcompat::compute_nd_range(), and sycl::_V1::detail::get_kernel_device_specific_info_host< info::kernel_device_specific::preferred_work_group_size_multiple >().
work_group_size_hint
template<size_t Dim0, size_t... Dims> constexpr work_group_size_hint_key::value_t<Dim0, Dims...> sycl::_V1::ext::oneapi::experimental::work_group_size_hint inline constexpr
Definition at line 146 of file properties.hpp.
work_item_progress
template<forward_progress_guarantee Guarantee, execution_scope CoordinationScope> constexpr work_item_progress_key::value_t<Guarantee, CoordinationScope> sycl::_V1::ext::oneapi::experimental::work_item_progress inline constexpr
Definition at line 235 of file properties.hpp.