DPC++ Runtime: cl::sycl::ext::oneapi Namespace Reference
cl::sycl::ext::oneapi Namespace Reference
Namespaces
cuda
detail
experimental
level_zero
property
Classes
class accessor_property_list
Objects of the accessor_property_list class are containers for the SYCL properties.
class atomic_accessor
class filter_selector
struct has_known_identity
struct is_compile_time_property
struct is_compile_time_property< ext::oneapi::property::no_alias >
struct is_compile_time_property< ext::oneapi::property::no_offset >
struct is_compile_time_property< sycl::ext::intel::property::buffer_location >
struct known_identity
struct sub_group
struct sub_group_mask
union Us
union Uu
Typedefs
using instead = cl::sycl::memory_order
template<typename T = void>
using plus = std::plus< T >
template<typename T = void>
using multiplies = std::multiplies< T >
template<typename T = void>
using bit_or = std::bit_or< T >
template<typename T = void>
using bit_xor = std::bit_xor< T >
template<typename T = void>
using bit_and = std::bit_and< T >
template<typename T = void>
using maximum = sycl::maximum< T >
template<typename T = void>
using minimum = sycl::minimum< T >
template<typename T >
using EnableIfIsScalarArithmetic = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_scalar_arithmetic< T >::value, T >
template<typename T >
using EnableIfIsVectorArithmetic = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_vector_arithmetic< T >::value, T >
template<typename Ptr , typename T >
using EnableIfIsPointer = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_pointer< Ptr >::value, T >
template<typename T >
using EnableIfIsTriviallyCopyable = cl::sycl::detail::enable_if_t< std::is_trivially_copyable< T >::value &&!cl::sycl::detail::is_vector_arithmetic< T >::value, T >
template<typename T , typename BinaryOperation >
using EnableIfIsScalarArithmeticNativeOp = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_scalar_arithmetic< T >::value &&cl::sycl::detail::is_native_op< T, BinaryOperation >::value, T >
template<typename T , typename BinaryOperation >
using EnableIfIsVectorArithmeticNativeOp = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_vector_arithmetic< T >::value &&cl::sycl::detail::is_native_op< T, BinaryOperation >::value, T >
template<typename T , typename BinaryOperation >
using EnableIfIsNonNativeOp = cl::sycl::detail::enable_if_t<(!cl::sycl::detail::is_scalar_arithmetic< T >::value &&!cl::sycl::detail::is_vector_arithmetic< T >::value &&std::is_trivially_copyable< T >::value)||!cl::sycl::detail::is_native_op< T, BinaryOperation >::value, T >
Functions
__SYCL_INLINE_CONSTEXPR memory_order memory_order_relaxed __SYCL2020_DEPRECATED ("use 'sycl::memory_order_relaxed' instead")
__SYCL_INLINE_CONSTEXPR memory_order memory_order_acquire __SYCL2020_DEPRECATED ("use 'sycl::memory_order_acquire' instead")
__SYCL_INLINE_CONSTEXPR memory_order memory_order_release __SYCL2020_DEPRECATED ("use 'sycl::memory_order_release' instead")
__SYCL_INLINE_CONSTEXPR memory_order memory_order_acq_rel __SYCL2020_DEPRECATED ("use 'sycl::memory_order_acq_rel' instead")
__SYCL_INLINE_CONSTEXPR memory_order memory_order_seq_cst __SYCL2020_DEPRECATED ("use 'sycl::memory_order_seq_cst' instead")
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_work_item __SYCL2020_DEPRECATED ("use 'sycl::memory_scope_work_item' instead")
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_sub_group __SYCL2020_DEPRECATED ("use 'sycl::memory_scope_sub_group' instead")
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_work_group __SYCL2020_DEPRECATED ("use 'sycl::memory_scope_work_group' instead")
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_device __SYCL2020_DEPRECATED ("use 'sycl::memory_scope_device' instead")
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_system __SYCL2020_DEPRECATED ("use 'sycl::memory_scope_system' instead")
static void atomic_fence (memory_order order, memory_scope scope)
template<typename T >
std::enable_if_t< detail::is_bf16_storage_type< T >::value, T > fabs (T x)
template<typename T >
std::enable_if_t< detail::is_bf16_storage_type< T >::value, T > fmin (T x, T y)
template<typename T >
std::enable_if_t< detail::is_bf16_storage_type< T >::value, T > fmax (T x, T y)
template<typename T >
std::enable_if_t< detail::is_bf16_storage_type< T >::value, T > fma (T x, T y, T z)
int32_t dot_acc (int32_t pa, int32_t pb, int32_t c)
int32_t dot_acc (uint32_t pa, uint32_t pb, int32_t c)
int32_t dot_acc (int32_t pa, uint32_t pb, int32_t c)
int32_t dot_acc (uint32_t pa, int32_t pb, int32_t c)
int32_t dot_acc (vec< int8_t, 4 > a, vec< int8_t, 4 > b, int32_t c)
int32_t dot_acc (vec< uint8_t, 4 > a, vec< uint8_t, 4 > b, int32_t c)
int32_t dot_acc (vec< uint8_t, 4 > a, vec< int8_t, 4 > b, int32_t c)
int32_t dot_acc (vec< int8_t, 4 > a, vec< uint8_t, 4 > b, int32_t c)
template<typename Group >
__SYCL2020_DEPRECATED ("ext::oneapi::all_of is deprecated. Use all_of_group instead.") detail
template<typename Group , typename T , class Predicate >
__SYCL2020_DEPRECATED ("ext::oneapi::all_of is deprecated. Use all_of_group instead.") detail
template<typename Group , typename Ptr , class Predicate >
__SYCL2020_DEPRECATED ("ext::oneapi::all_of is deprecated. Use joint_all_of instead.") detail
template<typename Group >
__SYCL2020_DEPRECATED ("ext::oneapi::any_of is deprecated. Use any_of_group instead.") detail
template<typename Group , typename T , class Predicate >
__SYCL2020_DEPRECATED ("ext::oneapi::any_of is deprecated. Use any_of_group instead.") detail
template<typename Group , typename Ptr , class Predicate >
__SYCL2020_DEPRECATED ("ext::oneapi::any_of is deprecated. Use joint_any_of instead.") detail
template<typename Group >
__SYCL2020_DEPRECATED ("ext::oneapi::none_of is deprecated. Use none_of_group instead.") detail
template<typename Group , typename T , class Predicate >
__SYCL2020_DEPRECATED ("ext::oneapi::none_of is deprecated. Use none_of_group instead.") detail
template<typename Group , typename Ptr , class Predicate >
__SYCL2020_DEPRECATED ("ext::oneapi::none_of is deprecated. Use joint_none_of instead.") detail
template<typename Group , typename T >
__SYCL2020_DEPRECATED ("ext::oneapi::broadcast is deprecated. Use group_broadcast instead.") detail
template<typename Group , typename T , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::reduce is deprecated. Use reduce_over_group instead.") detail
template<typename Group , typename V , typename T , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::reduce is deprecated. Use reduce_over_group instead.") detail
template<typename Group , typename Ptr , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::reduce is deprecated. Use joint_reduce instead.") detail
template<typename Group , typename Ptr , typename T , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::reduce is deprecated. Use joint_reduce instead.") detail
template<typename Group , typename T , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::exclusive_scan is deprecated. Use " "exclusive_scan_over_group instead.") detail
template<typename Group , typename V , typename T , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::exclusive_scan is deprecated. Use " "exclusive_scan_over_group instead.") detail
template<typename Group , typename InPtr , typename OutPtr , typename T , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::exclusive_scan is deprecated. Use " "joint_exclusive_scan instead.") detail
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::exclusive_scan is deprecated. Use " "joint_exclusive_scan instead.") detail
template<typename Group , typename T , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::inclusive_scan is deprecated. Use " "inclusive_scan_over_group instead.") detail
template<typename Group , typename V , class BinaryOperation , typename T >
__SYCL2020_DEPRECATED ("ext::oneapi::inclusive_scan is deprecated. Use " "inclusive_scan_over_group instead.") detail
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation , typename T >
__SYCL2020_DEPRECATED ("ext::oneapi::inclusive_scan is deprecated. Use " "joint_inclusive_scan instead.") detail
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation >
__SYCL2020_DEPRECATED ("ext::oneapi::inclusive_scan is deprecated. Use " "joint_inclusive_scan instead.") detail
template<typename Group >
detail::enable_if_t< detail::is_generic_group< Group >::value, bool > leader (Group g)
template<typename T , typename Group >
std::enable_if_t< std::is_trivially_destructible< T >::value &&sycl::detail::is_group< Group >::value, multi_ptr< T, access::address_space::local_space > > __SYCL_ALWAYS_INLINE group_local_memory_for_overwrite (Group g)
template<typename T , typename Group , typename... Args>
std::enable_if_t< std::is_trivially_destructible< T >::value &&sycl::detail::is_group< Group >::value, multi_ptr< T, access::address_space::local_space > > __SYCL_ALWAYS_INLINE group_local_memory (Group g, Args &&... args)
template<typename T , class BinaryOperation , int Dims, access::mode AccMode, access::placeholder IsPH>
detail::reduction_impl< T, BinaryOperation, Dims, false, IsPH > reduction (accessor< T, Dims, AccMode, access::target::device, IsPH > &Acc, const T &Identity, BinaryOperation BOp)
Creates and returns an object implementing the reduction functionality.
template<typename T , class BinaryOperation , int Dims, access::mode AccMode, access::placeholder IsPH>
std::enable_if_t< detail::IsKnownIdentityOp< T, BinaryOperation >::value, detail::reduction_impl< T, BinaryOperation, Dims, false, IsPH > > reduction (accessor< T, Dims, AccMode, access::target::device, IsPH > &Acc, BinaryOperation)
Creates and returns an object implementing the reduction functionality.
template<typename T , class BinaryOperation >
detail::reduction_impl< T, BinaryOperation, 1, true > reduction (T *VarPtr, const T &Identity, BinaryOperation BOp)
Creates and returns an object implementing the reduction functionality.
template<typename T , class BinaryOperation >
std::enable_if_t< detail::IsKnownIdentityOp< T, BinaryOperation >::value, detail::reduction_impl< T, BinaryOperation, 1, true > > reduction (T *VarPtr, BinaryOperation)
Creates and returns an object implementing the reduction functionality.
__SYCL_DEPRECATED ("use sycl::ext::oneapi::experimental::this_sub_group() instead") inline sub_group this_sub_group()
template<typename Group >
detail::enable_if_t< std::is_same< std::decay_t< Group >, sub_group >::value, sub_group_mask > group_ballot (Group g, bool predicate)
Variables
template<typename BinaryOperation , typename AccumulatorT >
__SYCL_INLINE_CONSTEXPR bool has_known_identity_v
template<typename BinaryOperation , typename AccumulatorT >
__SYCL_INLINE_CONSTEXPR AccumulatorT known_identity_v
Typedef Documentation
bit_and
template<typename T = void> using cl::sycl::ext::oneapi::bit_and = typedef std::bit_and<T>
Definition at line 23 of file functional.hpp.
bit_or
template<typename T = void> using cl::sycl::ext::oneapi::bit_or = typedef std::bit_or<T>
Definition at line 21 of file functional.hpp.
bit_xor
template<typename T = void> using cl::sycl::ext::oneapi::bit_xor = typedef std::bit_xor<T>
Definition at line 22 of file functional.hpp.
EnableIfIsNonNativeOp
template<typename T , typename BinaryOperation > using cl::sycl::ext::oneapi::EnableIfIsNonNativeOp = typedef cl::sycl::detail::enable_if_t< (!cl::sycl::detail::is_scalar_arithmetic<T>::value && !cl::sycl::detail::is_vector_arithmetic<T>::value && std::is_trivially_copyable<T>::value) || !cl::sycl::detail::is_native_op<T, BinaryOperation>::value, T>
Definition at line 66 of file group_algorithm.hpp.
EnableIfIsPointer
template<typename Ptr , typename T > using cl::sycl::ext::oneapi::EnableIfIsPointer = typedef cl::sycl::detail::enable_if_t<cl::sycl::detail::is_pointer<Ptr>::value, T>
Definition at line 38 of file group_algorithm.hpp.
EnableIfIsScalarArithmetic
template<typename T > using cl::sycl::ext::oneapi::EnableIfIsScalarArithmetic = typedef cl::sycl::detail::enable_if_t< cl::sycl::detail::is_scalar_arithmetic<T>::value, T>
Definition at line 30 of file group_algorithm.hpp.
EnableIfIsScalarArithmeticNativeOp
template<typename T , typename BinaryOperation > using cl::sycl::ext::oneapi::EnableIfIsScalarArithmeticNativeOp = typedef cl::sycl::detail::enable_if_t< cl::sycl::detail::is_scalar_arithmetic<T>::value && cl::sycl::detail::is_native_op<T, BinaryOperation>::value, T>
Definition at line 51 of file group_algorithm.hpp.
EnableIfIsTriviallyCopyable
template<typename T > using cl::sycl::ext::oneapi::EnableIfIsTriviallyCopyable = typedef cl::sycl::detail::enable_if_t< std::is_trivially_copyable<T>::value && !cl::sycl::detail::is_vector_arithmetic<T>::value, T>
Definition at line 44 of file group_algorithm.hpp.
EnableIfIsVectorArithmetic
template<typename T > using cl::sycl::ext::oneapi::EnableIfIsVectorArithmetic = typedef cl::sycl::detail::enable_if_t< cl::sycl::detail::is_vector_arithmetic<T>::value, T>
Definition at line 34 of file group_algorithm.hpp.
EnableIfIsVectorArithmeticNativeOp
template<typename T , typename BinaryOperation > using cl::sycl::ext::oneapi::EnableIfIsVectorArithmeticNativeOp = typedef cl::sycl::detail::enable_if_t< cl::sycl::detail::is_vector_arithmetic<T>::value && cl::sycl::detail::is_native_op<T, BinaryOperation>::value, T>
Definition at line 57 of file group_algorithm.hpp.
instead
typedef cl::sycl::memory_scope cl::sycl::ext::oneapi::instead
Definition at line 28 of file atomic_enums.hpp.
maximum
template<typename T = void> using cl::sycl::ext::oneapi::maximum = typedef sycl::maximum<T>
Definition at line 24 of file functional.hpp.
minimum
template<typename T = void> using cl::sycl::ext::oneapi::minimum = typedef sycl::minimum<T>
Definition at line 25 of file functional.hpp.
multiplies
template<typename T = void> using cl::sycl::ext::oneapi::multiplies = typedef std::multiplies<T>
Definition at line 20 of file functional.hpp.
plus
template<typename T = void> using cl::sycl::ext::oneapi::plus = typedef std::plus<T>
Definition at line 19 of file functional.hpp.
Function Documentation
__SYCL2020_DEPRECATED() [1/32]
template<typename Group > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::all_of is deprecated. Use all_of_group instead.")
Definition at line 69 of file group_algorithm.hpp.
References cl::sycl::all_of_group().
__SYCL2020_DEPRECATED() [2/32]
template<typename Group , typename T , class Predicate > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::all_of is deprecated. Use all_of_group instead.")
Definition at line 77 of file group_algorithm.hpp.
References cl::sycl::all_of_group().
__SYCL2020_DEPRECATED() [3/32]
template<typename Group , typename Ptr , class Predicate > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::all_of is deprecated. Use joint_all_of instead.")
Definition at line 85 of file group_algorithm.hpp.
References cl::sycl::joint_all_of().
__SYCL2020_DEPRECATED() [4/32]
template<typename Group > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::any_of is deprecated. Use any_of_group instead.")
Definition at line 94 of file group_algorithm.hpp.
References cl::sycl::any_of_group().
__SYCL2020_DEPRECATED() [5/32]
template<typename Group , typename T , class Predicate > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::any_of is deprecated. Use any_of_group instead.")
Definition at line 102 of file group_algorithm.hpp.
References cl::sycl::any_of_group().
__SYCL2020_DEPRECATED() [6/32]
template<typename Group , typename Ptr , class Predicate > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::any_of is deprecated. Use joint_any_of instead.")
Definition at line 110 of file group_algorithm.hpp.
References cl::sycl::joint_any_of().
__SYCL2020_DEPRECATED() [7/32]
template<typename Group , typename T > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::broadcast is deprecated. Use group_broadcast instead.")
Definition at line 145 of file group_algorithm.hpp.
References PI_INVALID_DEVICE.
__SYCL2020_DEPRECATED() [8/32]
template<typename Group , typename T , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::exclusive_scan is deprecated. Use " "exclusive_scan_over_group instead.")
Definition at line 375 of file group_algorithm.hpp.
References cl::sycl::exclusive_scan_over_group().
__SYCL2020_DEPRECATED() [9/32]
template<typename Group , typename V , typename T , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::exclusive_scan is deprecated. Use " "exclusive_scan_over_group instead.")
Definition at line 395 of file group_algorithm.hpp.
References cl::sycl::exclusive_scan_over_group().
__SYCL2020_DEPRECATED() [10/32]
template<typename Group , typename InPtr , typename OutPtr , typename T , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::exclusive_scan is deprecated. Use " "joint_exclusive_scan instead.")
Definition at line 422 of file group_algorithm.hpp.
References cl::sycl::joint_exclusive_scan().
__SYCL2020_DEPRECATED() [11/32]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::exclusive_scan is deprecated. Use " "joint_exclusive_scan instead.")
Definition at line 440 of file group_algorithm.hpp.
References cl::sycl::joint_exclusive_scan().
__SYCL2020_DEPRECATED() [12/32]
template<typename Group , typename T , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::inclusive_scan is deprecated. Use " "inclusive_scan_over_group instead.")
Definition at line 455 of file group_algorithm.hpp.
References cl::sycl::inclusive_scan_over_group().
__SYCL2020_DEPRECATED() [13/32]
template<typename Group , typename V , class BinaryOperation , typename T > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::inclusive_scan is deprecated. Use " "inclusive_scan_over_group instead.")
Definition at line 475 of file group_algorithm.hpp.
References cl::sycl::inclusive_scan_over_group().
__SYCL2020_DEPRECATED() [14/32]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation , typename T > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::inclusive_scan is deprecated. Use " "joint_inclusive_scan instead.")
Definition at line 502 of file group_algorithm.hpp.
References cl::sycl::joint_inclusive_scan().
__SYCL2020_DEPRECATED() [15/32]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::inclusive_scan is deprecated. Use " "joint_inclusive_scan instead.")
Definition at line 520 of file group_algorithm.hpp.
References cl::sycl::joint_inclusive_scan().
__SYCL2020_DEPRECATED() [16/32]
template<typename Group , typename Ptr , class Predicate > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::none_of is deprecated. Use joint_none_of instead.")
Definition at line 135 of file group_algorithm.hpp.
References cl::sycl::joint_none_of().
__SYCL2020_DEPRECATED() [17/32]
template<typename Group > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::none_of is deprecated. Use none_of_group instead.")
Definition at line 119 of file group_algorithm.hpp.
References cl::sycl::none_of_group().
__SYCL2020_DEPRECATED() [18/32]
template<typename Group , typename T , class Predicate > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::none_of is deprecated. Use none_of_group instead.")
Definition at line 127 of file group_algorithm.hpp.
References cl::sycl::none_of_group().
__SYCL2020_DEPRECATED() [19/32]
template<typename Group , typename Ptr , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::reduce is deprecated. Use joint_reduce instead.")
Definition at line 348 of file group_algorithm.hpp.
References cl::sycl::joint_reduce().
__SYCL2020_DEPRECATED() [20/32]
template<typename Group , typename Ptr , typename T , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::reduce is deprecated. Use joint_reduce instead.")
Definition at line 361 of file group_algorithm.hpp.
References cl::sycl::joint_reduce().
__SYCL2020_DEPRECATED() [21/32]
template<typename Group , typename T , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::reduce is deprecated. Use reduce_over_group instead.")
Definition at line 266 of file group_algorithm.hpp.
References cl::sycl::reduce_over_group().
__SYCL2020_DEPRECATED() [22/32]
template<typename Group , typename V , typename T , class BinaryOperation > cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("ext::oneapi::reduce is deprecated. Use reduce_over_group instead.")
Definition at line 304 of file group_algorithm.hpp.
References cl::sycl::reduce_over_group().
__SYCL2020_DEPRECATED() [23/32]
__SYCL_INLINE_CONSTEXPR memory_order memory_order_acq_rel cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_order_acq_rel' instead")
__SYCL2020_DEPRECATED() [24/32]
__SYCL_INLINE_CONSTEXPR memory_order memory_order_acquire cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_order_acquire' instead")
__SYCL2020_DEPRECATED() [25/32]
__SYCL_INLINE_CONSTEXPR memory_order memory_order_relaxed cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_order_relaxed' instead")
__SYCL2020_DEPRECATED() [26/32]
__SYCL_INLINE_CONSTEXPR memory_order memory_order_release cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_order_release' instead")
__SYCL2020_DEPRECATED() [27/32]
__SYCL_INLINE_CONSTEXPR memory_order memory_order_seq_cst cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_order_seq_cst' instead")
__SYCL2020_DEPRECATED() [28/32]
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_device cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_scope_device' instead")
__SYCL2020_DEPRECATED() [29/32]
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_sub_group cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_scope_sub_group' instead")
__SYCL2020_DEPRECATED() [30/32]
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_system cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_scope_system' instead")
__SYCL2020_DEPRECATED() [31/32]
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_work_group cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_scope_work_group' instead")
__SYCL2020_DEPRECATED() [32/32]
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_work_item cl::sycl::ext::oneapi::__SYCL2020_DEPRECATED ("use 'sycl::memory_scope_work_item' instead")
__SYCL_DEPRECATED()
cl::sycl::ext::oneapi::__SYCL_DEPRECATED ("use sycl::ext::oneapi::experimental::this_sub_group() instead")
Definition at line 745 of file sub_group.hpp.
References PI_INVALID_DEVICE.
atomic_fence()
static void cl::sycl::ext::oneapi::atomic_fence (memory_order order, memory_scope scope) inline static
Definition at line 28 of file atomic_fence.hpp.
References __spirv_MemoryBarrier(), and cl::sycl::detail::getStdMemoryOrder().
dot_acc() [1/8]
int32_t cl::sycl::ext::oneapi::dot_acc (int32_t pa, int32_t pb, int32_t c)
Definition at line 27 of file dot_product.hpp.
References cl::sycl::a.
dot_acc() [2/8]
int32_t cl::sycl::ext::oneapi::dot_acc (int32_t pa, uint32_t pb, int32_t c)
Definition at line 41 of file dot_product.hpp.
References cl::sycl::a.
dot_acc() [3/8]
int32_t cl::sycl::ext::oneapi::dot_acc (uint32_t pa, int32_t pb, int32_t c)
Definition at line 48 of file dot_product.hpp.
References cl::sycl::a.
dot_acc() [4/8]
int32_t cl::sycl::ext::oneapi::dot_acc (uint32_t pa, uint32_t pb, int32_t c)
Definition at line 34 of file dot_product.hpp.
References cl::sycl::a.
dot_acc() [5/8]
int32_t cl::sycl::ext::oneapi::dot_acc (vec< int8_t, 4 > a, vec< int8_t, 4 > b, int32_t c)
Definition at line 55 of file dot_product.hpp.
References cl::sycl::a.
dot_acc() [6/8]
int32_t cl::sycl::ext::oneapi::dot_acc (vec< int8_t, 4 > a, vec< uint8_t, 4 > b, int32_t c)
Definition at line 70 of file dot_product.hpp.
References cl::sycl::a.
dot_acc() [7/8]
int32_t cl::sycl::ext::oneapi::dot_acc (vec< uint8_t, 4 > a, vec< int8_t, 4 > b, int32_t c)
Definition at line 65 of file dot_product.hpp.
References cl::sycl::a.
dot_acc() [8/8]
int32_t cl::sycl::ext::oneapi::dot_acc (vec< uint8_t, 4 > a, vec< uint8_t, 4 > b, int32_t c)
Definition at line 60 of file dot_product.hpp.
References cl::sycl::a.
fabs()
template<typename T > std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> cl::sycl::ext::oneapi::fabs (T x)
Definition at line 40 of file bf16_storage_builtins.hpp.
References PI_INVALID_DEVICE.
fma()
template<typename T > std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> cl::sycl::ext::oneapi::fma (T x, T y, T z)
Definition at line 72 of file bf16_storage_builtins.hpp.
References PI_INVALID_DEVICE.
fmax()
template<typename T > std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> cl::sycl::ext::oneapi::fmax (T x, T y)
Definition at line 61 of file bf16_storage_builtins.hpp.
References PI_INVALID_DEVICE.
fmin()
template<typename T > std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> cl::sycl::ext::oneapi::fmin (T x, T y)
Definition at line 50 of file bf16_storage_builtins.hpp.
References PI_INVALID_DEVICE.
group_ballot()
template<typename Group > detail::enable_if_t<std::is_same<std::decay_t<Group>, sub_group>::value, sub_group_mask> cl::sycl::ext::oneapi::group_ballot (Group g, bool predicate)
Definition at line 257 of file sub_group_mask.hpp.
group_local_memory()
template<typename T , typename Group , typename... Args> std::enable_if_t<std::is_trivially_destructible<T>::value && sycl::detail::is_group<Group>::value, multi_ptr<T, access::address_space::local_space> > __SYCL_ALWAYS_INLINE cl::sycl::ext::oneapi::group_local_memory (Group g, Args &&... args)
Definition at line 47 of file group_local_memory.hpp.
References cl::sycl::detail::__attribute__(), cl::sycl::feature_not_supported, PI_INVALID_OPERATION, and cl::sycl::detail::workGroupBarrier().
Referenced by cl::sycl::group_local_memory().
group_local_memory_for_overwrite()
template<typename T , typename Group > std::enable_if_t<std::is_trivially_destructible<T>::value && sycl::detail::is_group<Group>::value, multi_ptr<T, access::address_space::local_space> > __SYCL_ALWAYS_INLINE cl::sycl::ext::oneapi::group_local_memory_for_overwrite (Group g)
Definition at line 30 of file group_local_memory.hpp.
References cl::sycl::detail::__attribute__(), cl::sycl::feature_not_supported, and PI_INVALID_OPERATION.
leader()
template<typename Group > detail::enable_if_t<detail::is_generic_group<Group>::value, bool> cl::sycl::ext::oneapi::leader (Group g)
Definition at line 536 of file group_algorithm.hpp.
References cl::sycl::detail::get_local_linear_id(), and PI_INVALID_DEVICE.
reduction() [1/4]
template<typename T , class BinaryOperation , int Dims, access::mode AccMode, access::placeholder IsPH> std::enable_if_t<detail::IsKnownIdentityOp<T, BinaryOperation>::value, detail::reduction_impl<T, BinaryOperation, Dims, false, IsPH> > cl::sycl::ext::oneapi::reduction (accessor< T, Dims, AccMode, access::target::device, IsPH > & Acc, BinaryOperation)
Creates and returns an object implementing the reduction functionality.
Accepts 2 arguments: the accessor to buffer to where the computed reduction must be stored
Parameters
Acc and the binary operation used in the reduction. The identity value is not passed to this version as it is statically known.
Definition at line 2035 of file reduction.hpp.
reduction() [2/4]
template<typename T , class BinaryOperation , int Dims, access::mode AccMode, access::placeholder IsPH> detail::reduction_impl<T, BinaryOperation, Dims, false, IsPH> cl::sycl::ext::oneapi::reduction (accessor< T, Dims, AccMode, access::target::device, IsPH > & Acc, const T & Identity, BinaryOperation BOp)
Creates and returns an object implementing the reduction functionality.
Accepts 3 arguments: the accessor to buffer to where the computed reduction must be stored
Parameters
Acc,identity value
Identity,and the binary operation used in the reduction.
Definition at line 2022 of file reduction.hpp.
reduction() [3/4]
template<typename T , class BinaryOperation > std::enable_if_t<detail::IsKnownIdentityOp<T, BinaryOperation>::value, detail::reduction_impl<T, BinaryOperation, 1, true> > cl::sycl::ext::oneapi::reduction (T * VarPtr, BinaryOperation)
Creates and returns an object implementing the reduction functionality.
Accepts 2 arguments: the reference to the reduction variable, to where the computed reduction must be stored
Parameters
VarPtr,and the binary operation used in the reduction. The identity value is not passed to this version as it is statically known.
Definition at line 2058 of file reduction.hpp.
reduction() [4/4]
template<typename T , class BinaryOperation > detail::reduction_impl<T, BinaryOperation, 1, true> cl::sycl::ext::oneapi::reduction (T * VarPtr, const T & Identity, BinaryOperation BOp)
Creates and returns an object implementing the reduction functionality.
Accepts 3 arguments: the reference to the reduction variable to where the computed reduction must be stored
Parameters
VarPtr,identity value
Identity,and the binary operation used in the reduction.
Definition at line 2046 of file reduction.hpp.
Variable Documentation
has_known_identity_v
template<typename BinaryOperation , typename AccumulatorT > __SYCL_INLINE_CONSTEXPR bool cl::sycl::ext::oneapi::has_known_identity_v
Initial value:
=
    has_known_identity<BinaryOperation, AccumulatorT>::value
Definition at line 2068 of file reduction.hpp.
known_identity_v
template<typename BinaryOperation , typename AccumulatorT > __SYCL_INLINE_CONSTEXPR AccumulatorT cl::sycl::ext::oneapi::known_identity_v
Initial value:
=
    known_identity<BinaryOperation, AccumulatorT>::value
Definition at line 2076 of file reduction.hpp.