DPC++ Runtime: cl::sycl::ext::intel::experimental::esimd Namespace Reference
cl::sycl::ext::intel::experimental::esimd Namespace Reference
Namespaces
detail
emu
Classes
struct region_base
struct shape_type
struct shape_type< region1d_t< Ty, Size, Stride > >
struct shape_type< region2d_t< Ty, SizeY, StrideY, SizeX, StrideX > >
struct shape_type< simd_view< BaseTy, RegionTy > >
struct shape_type< std::pair< TopRegionTy, BaseRegionTy > >
class simd
The simd vector class.
class simd_view
The reference class.
Typedefs
using uchar = unsigned char
using ushort = unsigned short
using uint = unsigned int
template<typename T , int Size, int Stride>
using region1d_t = region_base< false, T, 1, 0, Size, Stride >
template<typename T , int SizeY, int StrideY, int SizeX, int StrideX>
using region2d_t = region_base< true, T, SizeY, StrideY, SizeX, StrideX >
template<int N>
using mask_type_t = typename detail::vector_type< uint16_t, N >::type
Enumerations
enum { GENX_NOSAT = 0, GENX_SAT }
enum ChannelMaskType {
ESIMD_R_ENABLE = 1, ESIMD_G_ENABLE = 2, ESIMD_GR_ENABLE = 3, ESIMD_B_ENABLE = 4,
ESIMD_BR_ENABLE = 5, ESIMD_BG_ENABLE = 6, ESIMD_BGR_ENABLE = 7, ESIMD_A_ENABLE = 8,
ESIMD_AR_ENABLE = 9, ESIMD_AG_ENABLE = 10, ESIMD_AGR_ENABLE = 11, ESIMD_AB_ENABLE = 12,
ESIMD_ABR_ENABLE = 13, ESIMD_ABG_ENABLE = 14, ESIMD_ABGR_ENABLE = 15
}
enum EsimdAtomicOpType : uint16_t {
EsimdAtomicOpType::ATOMIC_ADD = 0x0, EsimdAtomicOpType::ATOMIC_SUB = 0x1, EsimdAtomicOpType::ATOMIC_INC = 0x2, EsimdAtomicOpType::ATOMIC_DEC = 0x3,
EsimdAtomicOpType::ATOMIC_MIN = 0x4, EsimdAtomicOpType::ATOMIC_MAX = 0x5, EsimdAtomicOpType::ATOMIC_XCHG = 0x6, EsimdAtomicOpType::ATOMIC_CMPXCHG = 0x7,
EsimdAtomicOpType::ATOMIC_AND = 0x8, EsimdAtomicOpType::ATOMIC_OR = 0x9, EsimdAtomicOpType::ATOMIC_XOR = 0xa, EsimdAtomicOpType::ATOMIC_MINSINT = 0xb,
EsimdAtomicOpType::ATOMIC_MAXSINT = 0xc, EsimdAtomicOpType::ATOMIC_FMAX = 0x10, EsimdAtomicOpType::ATOMIC_FMIN = 0x11, EsimdAtomicOpType::ATOMIC_FCMPWR = 0x12,
EsimdAtomicOpType::ATOMIC_PREDEC = 0xff
}
enum CacheHint : uint8_t {
CacheHint::None = 0, CacheHint::Uncached = 1, CacheHint::WriteBack = 2, CacheHint::WriteThrough = 3,
CacheHint::Streaming = 4, CacheHint::ReadInvalidate = 5
}
enum EsimdSbarrierType : uint8_t { EsimdSbarrierType::WAIT = 0, EsimdSbarrierType::SIGNAL = 1 }
enum EsimdFenceMask {
ESIMD_GLOBAL_COHERENT_FENCE = 0x1, ESIMD_L3_FLUSH_INSTRUCTIONS = 0x2, ESIMD_L3_FLUSH_TEXTURE_DATA = 0x4, ESIMD_L3_FLUSH_CONSTANT_DATA = 0x8,
ESIMD_L3_FLUSH_RW_DATA = 0x10, ESIMD_LOCAL_BARRIER = 0x20, ESIMD_L1_FLUASH_RO_DATA = 0x40, ESIMD_SW_BARRIER = 0x80
}
Bits used to form the bitmask that controls the behavior of esimd_fence Bit 0: the “commit enable” bit.
Functions
template<typename T >
T getTopRegion (T Reg)
template<typename T , typename U >
T getTopRegion (std::pair< T, U > Reg)
template<typename T >
T getBaseRegion (T Reg)
template<typename T , typename U >
T getBaseRegion (std::pair< T, U > Reg)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T0, SZ > esimd_sat (simd< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< !std::is_same< typename sycl::detail::remove_const_t< T0 >, typename sycl::detail::remove_const_t< T1 > >::value, simd< T0, SZ > > esimd_abs (simd< T1, SZ > src0, int flag=GENX_NOSAT)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< !std::is_same< typename sycl::detail::remove_const_t< T0 >, typename sycl::detail::remove_const_t< T1 > >::value &&detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_abs (T1 src0, int flag=GENX_NOSAT)
template<typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T1, SZ > esimd_abs (simd< T1, SZ > src0, int flag=GENX_NOSAT)
template<typename T1 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T1 >::value, typename sycl::detail::remove_const_t< T1 > > esimd_abs (T1 src0, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > > esimd_shl (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_shl (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > > esimd_shr (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_shr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T0 >::value &&std::is_integral< T1 >::value, simd< T0, SZ > > esimd_rol (simd< T1, SZ > src0, simd< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > > esimd_rol (simd< T1, SZ > src0, U src1)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_rol (T1 src0, T2 src1)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T0 >::value &&std::is_integral< T1 >::value, simd< T0, SZ > > esimd_ror (simd< T1, SZ > src0, simd< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > > esimd_ror (simd< T1, SZ > src0, U src1)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_ror (T1 src0, T2 src1)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > > esimd_lsr (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_lsr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_vector< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, decltype(esimd_lsr< T0 >T2(), T1()))> esimd_lsr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > > esimd_asr (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_asr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_vector< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, decltype(esimd_asr< T0 >T2(), T1()))> esimd_asr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename U , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_dword_type< T0 >::value &&detail::is_dword_type< T1 >::value &&detail::is_dword_type< U >::value, simd< T0, SZ > > esimd_imul (simd< T0, SZ > &rmd, simd< T1, SZ > src0, U src1)
template<typename T0 , typename T1 , typename U , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< U >::value, simd< T0, SZ > > esimd_imul (simd< T0, SZ > &rmd, U src0, simd< T1, SZ > src1)
template<typename T0 , typename T , typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T >::value &&detail::is_esimd_scalar< U >::value &&detail::is_esimd_scalar< T0 >::value, T0 > esimd_imul (simd< T0, 1 > &rmd, T src0, U src1)
template<typename T , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T >::value &&std::is_integral< U >::value, simd< T, SZ > > esimd_quot (simd< T, SZ > src0, U src1)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_quot (T0 src0, T1 src1)
template<typename T , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T >::value &&std::is_integral< U >::value, simd< T, SZ > > esimd_mod (simd< T, SZ > src0, U src1)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_mod (T0 src0, T1 src1)
template<typename T , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T >::value &&std::is_integral< U >::value, simd< T, SZ > > esimd_div (simd< T, SZ > &remainder, simd< T, SZ > src0, U src1)
template<typename T , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T >::value &&std::is_integral< U >::value &&detail::is_esimd_scalar< U >::value, simd< T, SZ > > esimd_div (simd< T, SZ > &remainder, U src0, simd< T, SZ > src1)
template<typename RT , typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< RT >::value &&detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value, typename sycl::detail::remove_const_t< RT > > esimd_div (simd< typename std::remove_const< RT >, 1 > &remainder, T0 src0, T1 src1)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T, SZ > esimd_max (simd< T, SZ > src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T >::value, simd< T, SZ > > esimd_max (simd< T, SZ > src0, T src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T >::value, simd< T, SZ > > esimd_max (T src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T >::value, T > esimd_max (T src0, T src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T, SZ > esimd_min (simd< T, SZ > src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T >::value, simd< T, SZ > > esimd_min (simd< T, SZ > src0, T src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T >::value, simd< T, SZ > > esimd_min (T src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T >::value, T > esimd_min (T src0, T src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type< T1 >::value &&std::is_floating_point< T1 >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T0, SZ > > esimd_dp2 (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type< T1 >::value &&std::is_floating_point< T1 >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T0, SZ > > esimd_dp3 (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type< T1 >::value &&std::is_floating_point< T1 >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T0, SZ > > esimd_dp4 (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T , typename U , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type< T >::value &&std::is_floating_point< T >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T, SZ > > esimd_dph (simd< T, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type< T >::value &&std::is_floating_point< T >::value, simd< T, SZ > > esimd_line (simd< T, 4 > src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type< T >::value &&std::is_floating_point< T >::value, simd< T, SZ > > esimd_line (float P, float Q, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T, SZ > esimd_frc (simd< T, SZ > src0)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE T esimd_frc (T src0)
template<typename RT , typename T0 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< RT, SZ > esimd_lzd (simd< T0, SZ > src0, int flag=GENX_NOSAT)
template<typename RT , typename T0 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< RT >::value &&detail::is_esimd_scalar< T0 >::value, typename sycl::detail::remove_const_t< RT > > esimd_lzd (T0 src0, int flag=GENX_NOSAT)
template<typename T , int SZ, typename U , typename V >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type< T >::value &&std::is_floating_point< T >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T, SZ > > esimd_lrp (simd< T, SZ > src0, U src1, V src2, int flag=GENX_NOSAT)
template<int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< float, SZ > esimd_pln (simd< float, 4 > src0, simd< float, SZ > src1, simd< float, SZ > src2, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T0, SZ > esimd_bf_reverse (simd< T1, SZ > src0)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_bf_reverse (T1 src0)
template<typename T0 , typename T1 , int SZ, typename U , typename V , typename W >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T1 >::value, simd< T0, SZ > > esimd_bf_insert (U src0, V src1, W src2, simd< T1, SZ > src3)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T4 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_bf_insert (T1 src0, T2 src1, T3 src2, T4 src3)
template<typename T0 , typename T1 , int SZ, typename U , typename V >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T1 >::value, simd< T0, SZ > > esimd_bf_extract (U src0, V src1, simd< T1, SZ > src2)
template<typename T0 , typename T1 , typename T2 , typename T3 >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T3 >::value, typename sycl::detail::remove_const_t< T0 > > esimd_bf_extract (T1 src0, T2 src1, T3 src2)
template<int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE simd< float, SZ > esimd_sincos (simd< float, SZ > &dstcos, U src0, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_floating_point< T >::value, simd< T, SZ > > esimd_atan (simd< T, SZ > src0, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_floating_point< T >::value, T > esimd_atan (T src0, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_floating_point< T >::value, simd< T, SZ > > esimd_acos (simd< T, SZ > src0, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_floating_point< T >::value, T > esimd_acos (T src0, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_floating_point< T >::value, simd< T, SZ > > esimd_asin (simd< T, SZ > src0, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_floating_point< T >::value, T > esimd_asin (T src0, int flag=GENX_NOSAT)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<(N==8||N==16||N==32), uint > esimd_pack_mask (simd< ushort, N > src0)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<(N==8||N==16||N==32), simd< ushort, N > > esimd_unpack_mask (uint src0)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<(N !=8 &&N !=16 &&N< 32), uint > esimd_pack_mask (simd< ushort, N > src0)
template<typename T , int N>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T >::value, simd< uint, N > > esimd_cbit (simd< T, N > src0)
Count component-wise the total bits set in source operand.
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral< T >::value &&detail::is_esimd_scalar< T >::value, uint > esimd_cbit (T src)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE simd< unsigned, N > esimd_fbl (simd< unsigned, N > src)
Find component-wise the first bit from LSB side.
template<typename T = void>
ESIMD_NODEBUG ESIMD_INLINE unsigned esimd_fbl (unsigned src)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE simd< int, N > esimd_fbh (simd< int, N > src)
Find component-wise the first bit from MSB side.
template<int N>
ESIMD_NODEBUG ESIMD_INLINE simd< unsigned int, N > esimd_fbh (simd< unsigned int, N > src)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_dword_type< T >::value &&detail::is_esimd_scalar< T >::value, T > esimd_fbh (T src)
template<typename T = void>
simd< uint, 4 > esimd_rdtsc ()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_dword_type< T1 >::value &&detail::is_dword_type< T2 >::value &&detail::is_dword_type< T3 >::value &&detail::is_dword_type< T4 >::value, simd< T1, N > > esimd_dp4a (simd< T2, N > src0, simd< T3, N > src1, simd< T4, N > src2, int flag=GENX_NOSAT)
DP4A.
template<typename RT , int SZ>
ESIMD_INLINE simd< RT, SZ > esimd_floor (const simd< float, SZ > src0, const uint flags=0)
template<typename RT >
ESIMD_INLINE RT esimd_floor (const float &src0, const uint flags=0)
template<typename RT , int SZ>
ESIMD_INLINE simd< RT, SZ > esimd_ceil (const simd< float, SZ > src0, const uint flags=0)
template<typename RT >
ESIMD_INLINE RT esimd_ceil (const float &src0, const uint flags=0)
template<int N>
simd< float, N > esimd_atan2_fast (simd< float, N > y, simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_atan2_fast (T y, T x, const uint flags=0)
template<int N>
simd< float, N > esimd_atan2 (simd< float, N > y, simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_atan2 (T y, T x, const uint flags=0)
template<int N>
simd< float, N > esimd_fmod (simd< float, N > y, simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_fmod (T y, T x, const uint flags=0)
template<int N>
simd< float, N > esimd_sin_emu (simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_sin_emu (T x, const uint flags=0)
template<int N>
simd< float, N > esimd_cos_emu (simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_cos_emu (T x, const uint flags=0)
float esimd_tanh_cody_waite (float x)
template<int N>
simd< float, N > esimd_tanh_cody_waite (simd< float, N > x)
float esimd_tanh (float x)
template<int N>
simd< float, N > esimd_tanh (simd< float, N > x)
template<int N>
ESIMD_INLINE simd< float, N > esimd_atan2_fast (simd< float, N > y, simd< float, N > x, const uint flags)
template<>
ESIMD_INLINE float esimd_atan2_fast (float y, float x, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_atan2 (simd< float, N > y, simd< float, N > x, const uint flags)
template<>
ESIMD_INLINE float esimd_atan2 (float y, float x, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_fmod (simd< float, N > y, simd< float, N > x, const uint flags)
template<>
ESIMD_INLINE float esimd_fmod (float y, float x, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_sin_emu (simd< float, N > x, const uint flags)
template<typename T >
ESIMD_INLINE float esimd_sin_emu (T x0, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_cos_emu (simd< float, N > x, const uint flags)
template<typename T >
ESIMD_INLINE float esimd_cos_emu (T x0, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_tanh_cody_waite (simd< float, N > x)
template<int N>
ESIMD_INLINE simd< float, N > esimd_tanh (simd< float, N > x)
template<typename T0 , typename T1 , int SZ>
ESIMD_INLINE ESIMD_NODEBUG T0 hmax (simd< T1, SZ > v)
template<typename T0 , typename T1 , int SZ>
ESIMD_INLINE ESIMD_NODEBUG T0 hmin (simd< T1, SZ > v)
template<typename T0 , typename T1 , int SZ, typename BinaryOperation >
ESIMD_INLINE ESIMD_NODEBUG T0 reduce (simd< T1, SZ > v, BinaryOperation op)
template<typename T , int N>
simd< T, N > esimd_dp4 (simd< T, N > v1, simd< T, N > v2)
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<((n==8||n==16||n==32) &&(ElemsPerAddr==1||ElemsPerAddr==2||ElemsPerAddr==4)), simd< T, n *ElemsPerAddr > > gather (T *p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
Flat-address gather.
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<((n==8||n==16||n==32) &&(ElemsPerAddr==1||ElemsPerAddr==2||ElemsPerAddr==4)), void > scatter (T *p, simd< T, n *ElemsPerAddr > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
Flat-address scatter.
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > block_load (const T *const addr)
Flat-address block-load.
template<typename T , int n, typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > block_load (AccessorTy acc, uint32_t offset)
Accessor-based block-load.
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG void block_store (T *p, simd< T, n > vals)
Flat-address block-store.
template<typename T , int n, typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG void block_store (AccessorTy acc, uint32_t offset, simd< T, n > vals)
Accessor-based block-store.
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(sizeof(T)<=4) &&(N==1||N==8||N==16) &&!std::is_pointer< AccessorTy >::value, simd< T, N > > gather (AccessorTy acc, simd< uint32_t, N > offsets, uint32_t glob_offset=0)
Accessor-based gather.
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(sizeof(T)<=4) &&(N==1||N==8||N==16) &&!std::is_pointer< AccessorTy >::value, void > scatter (AccessorTy acc, simd< T, N > vals, simd< uint32_t, N > offsets, uint32_t glob_offset=0, simd< uint16_t, N > pred=1)
Accessor-based scatter.
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG T scalar_load (AccessorTy acc, uint32_t offset)
Load a scalar value from an accessor.
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG void scalar_store (AccessorTy acc, uint32_t offset, T val)
Store a scalar value into an accessor.
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==16||n==32) &&(sizeof(T)==4), simd< T, n *NumChannels(Mask)> > gather4 (T *p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
Flat-address gather4.
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==16||n==32) &&(sizeof(T)==4), void > scatter4 (T *p, simd< T, n *NumChannels(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
Flat-address scatter4.
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 0 >), simd< T, n > > flat_atomic (T *p, simd< unsigned, n > offset, simd< ushort, n > pred)
Flat-address atomic, zero source operand: inc and dec.
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 1 >), simd< T, n > > flat_atomic (T *p, simd< unsigned, n > offset, simd< T, n > src0, simd< ushort, n > pred)
Flat-address atomic, one source operand, add/sub/min/max etc.
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 2 >), simd< T, n > > flat_atomic (T *p, simd< unsigned, n > offset, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
Flat-address atomic, two source operands.
ESIMD_INLINE ESIMD_NODEBUG void esimd_fence (uint8_t cntl)
esimd_fence sets the memory read/write order.
ESIMD_NODEBUG void esimd_barrier ()
Generic work-group barrier.
ESIMD_NODEBUG void esimd_sbarrier (EsimdSbarrierType flag)
Generic work-group split barrier.
SYCL_EXTERNAL SYCL_ESIMD_FUNCTION void slm_init (uint32_t size)
Declare per-work-group slm size.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==16||n==32), simd< T, n > > slm_load (simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM gather.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==16||n==32), void > slm_store (simd< T, n > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM scatter.
template<typename T , int n, ChannelMaskType Mask>
ESIMD_INLINE ESIMD_NODEBUG sycl::detail::enable_if_t<(n==8||n==16||n==32) &&(sizeof(T)==4), simd< T, n *NumChannels(Mask)> > slm_load4 (simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM gather4.
template<typename T , int n, ChannelMaskType Mask>
sycl::detail::enable_if_t<(n==8||n==16||n==32) &&(sizeof(T)==4), void > slm_store4 (simd< T, n *NumChannels(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM scatter4.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > slm_block_load (uint32_t offset)
SLM block-load.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG void slm_block_store (uint32_t offset, simd< T, n > vals)
SLM block-store.
template<EsimdAtomicOpType Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 0 >), simd< T, n > > slm_atomic (simd< uint32_t, n > offsets, simd< ushort, n > pred)
SLM atomic, zero source operand: inc and dec.
template<EsimdAtomicOpType Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 1 >), simd< T, n > > slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< ushort, n > pred)
SLM atomic, one source operand, add/sub/min/max etc.
template<EsimdAtomicOpType Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::check_atomic< Op, T, n, 2 >), simd< T, n > > slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
SLM atomic, two source operands.
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0>
ESIMD_INLINE ESIMD_NODEBUG simd< T, m *n > media_block_load (AccessorTy acc, unsigned x, unsigned y)
Media block load.
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0>
ESIMD_INLINE ESIMD_NODEBUG void media_block_store (AccessorTy acc, unsigned x, unsigned y, simd< T, m *n > vals)
Media block store.
template<typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG uint32_t esimd_get_value (AccessorTy acc)
esimd_get_value
template<typename T1 , int n1, typename T2 , int n2, typename T3 , int n3, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG simd< T1, n1 > esimd_raw_sends_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw sends load.
template<typename T1 , int n1, typename T2 , int n2, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG simd< T1, n1 > esimd_raw_send_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw send load.
template<typename T1 , int n1, typename T2 , int n2, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG void esimd_raw_sends_store (simd< T1, n1 > msgSrc0, simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw sends store.
template<typename T1 , int n1, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG void esimd_raw_send_store (simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw send store.
template<typename U , typename T , int n>
ESIMD_INLINE simd< U, n > convert (simd< T, n > val)
Variables
static constexpr auto ESIMD_CONST_E = 2.71828f
static constexpr auto ESIMD_CONST_PI = 3.14159f
static constexpr auto ESIMD_CONST_2PI = 6.28318f
static constexpr auto ESIMD_DBL_EPSILON = 0.00001f
static constexpr auto CMPI = 3.14159265f
Typedef Documentation
mask_type_t
template<int N> using cl::sycl::ext::intel::experimental::esimd::mask_type_t = typedef typename detail::vector_type<uint16_t, N>::type
Definition at line 262 of file types.hpp.
region1d_t
template<typename T , int Size, int Stride> using cl::sycl::ext::intel::experimental::esimd::region1d_t = typedef region_base<false, T, 1, 0, Size, Stride>
Definition at line 53 of file region.hpp.
region2d_t
template<typename T , int SizeY, int StrideY, int SizeX, int StrideX> using cl::sycl::ext::intel::experimental::esimd::region2d_t = typedef region_base<true, T, SizeY, StrideY, SizeX, StrideX>
Definition at line 57 of file region.hpp.
uchar
using cl::sycl::ext::intel::experimental::esimd::uchar = typedef unsigned char
Definition at line 24 of file common.hpp.
uint
using cl::sycl::ext::intel::experimental::esimd::uint = typedef unsigned int
Definition at line 26 of file common.hpp.
ushort
using cl::sycl::ext::intel::experimental::esimd::ushort = typedef unsigned short
Definition at line 25 of file common.hpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GENX_NOSAT
GENX_SAT
Definition at line 56 of file common.hpp.
CacheHint
enum cl::sycl::ext::intel::experimental::esimd::CacheHint : uint8_t strong
Enumerator
None
Uncached
WriteBack
WriteThrough
Streaming
ReadInvalidate
Definition at line 105 of file common.hpp.
ChannelMaskType
enum cl::sycl::ext::intel::experimental::esimd::ChannelMaskType
Enumerator
ESIMD_R_ENABLE
ESIMD_G_ENABLE
ESIMD_GR_ENABLE
ESIMD_B_ENABLE
ESIMD_BR_ENABLE
ESIMD_BG_ENABLE
ESIMD_BGR_ENABLE
ESIMD_A_ENABLE
ESIMD_AR_ENABLE
ESIMD_AG_ENABLE
ESIMD_AGR_ENABLE
ESIMD_AB_ENABLE
ESIMD_ABR_ENABLE
ESIMD_ABG_ENABLE
ESIMD_ABGR_ENABLE
Definition at line 58 of file common.hpp.
EsimdAtomicOpType
enum cl::sycl::ext::intel::experimental::esimd::EsimdAtomicOpType : uint16_t strong
Enumerator
ATOMIC_ADD
ATOMIC_SUB
ATOMIC_INC
ATOMIC_DEC
ATOMIC_MIN
ATOMIC_MAX
ATOMIC_XCHG
ATOMIC_CMPXCHG
ATOMIC_AND
ATOMIC_OR
ATOMIC_XOR
ATOMIC_MINSINT
ATOMIC_MAXSINT
ATOMIC_FMAX
ATOMIC_FMIN
ATOMIC_FCMPWR
ATOMIC_PREDEC
Definition at line 84 of file common.hpp.
EsimdFenceMask
enum cl::sycl::ext::intel::experimental::esimd::EsimdFenceMask
Bits used to form the bitmask that controls the behavior of esimd_fence Bit 0: the “commit enable” bit.
If set, the fence is guaranteed to be globally observable Bit 1: flush instruction cache if set. Bit 2: flush sampler cache if set Bit 3: flush constant cache if set Bit 4: flush read-write cache if set Bit 5: 0 means the fence is applied to global memory 1 means the fence applies to shared local memory only Bit 6: flush L1 read-only data cache if set Bit 7: indicates this is a scheduling barrier but will not generate an actual fence instruction
Enumerator
ESIMD_GLOBAL_COHERENT_FENCE
ESIMD_L3_FLUSH_INSTRUCTIONS
ESIMD_L3_FLUSH_TEXTURE_DATA
ESIMD_L3_FLUSH_CONSTANT_DATA
ESIMD_L3_FLUSH_RW_DATA
ESIMD_LOCAL_BARRIER
ESIMD_L1_FLUASH_RO_DATA
ESIMD_SW_BARRIER
Definition at line 579 of file memory.hpp.
EsimdSbarrierType
enum cl::sycl::ext::intel::experimental::esimd::EsimdSbarrierType : uint8_t strong
Enumerator
WAIT
SIGNAL
Definition at line 114 of file common.hpp.
Function Documentation
convert()
template<typename U , typename T , int n> ESIMD_INLINE simd<U, n> cl::sycl::ext::intel::experimental::esimd::convert (simd< T, n > val)
Definition at line 544 of file simd.hpp.
esimd_abs() [1/4]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< !std::is_same<typename sycl::detail::remove_const_t<T0>, typename sycl::detail::remove_const_t<T1> >::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_abs (simd< T1, SZ > src0, int flag = GENX_NOSAT)
Definition at line 82 of file math.hpp.
esimd_abs() [2/4]
template<typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T1, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_abs (simd< T1, SZ > src0, int flag = GENX_NOSAT)
Definition at line 98 of file math.hpp.
esimd_abs() [3/4]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< !std::is_same<typename sycl::detail::remove_const_t<T0>, typename sycl::detail::remove_const_t<T1> >::value && detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_abs (T1 src0, int flag = GENX_NOSAT)
Definition at line 93 of file math.hpp.
esimd_abs() [4/4]
template<typename T1 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T1>::value, typename sycl::detail::remove_const_t<T1> > cl::sycl::ext::intel::experimental::esimd::esimd_abs (T1 src0, int flag = GENX_NOSAT)
Definition at line 107 of file math.hpp.
Referenced by esimd_acos(), esimd_asin(), esimd_atan(), cl::sycl::ext::intel::experimental::esimd::detail::esimd_tanh_cody_waite_impl(), and cl::sycl::ext::intel::experimental::esimd::detail::esimd_tanh_impl().
esimd_acos() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_floating_point<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_acos (simd< T, SZ > src0, int flag = GENX_NOSAT)
Definition at line 1151 of file math.hpp.
References esimd_abs(), ESIMD_HDR_CONST_PI, GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge().
esimd_acos() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_floating_point<T>::value, T> cl::sycl::ext::intel::experimental::esimd::esimd_acos (T src0, int flag = GENX_NOSAT)
Definition at line 1184 of file math.hpp.
Referenced by esimd_asin().
esimd_asin() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_floating_point<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_asin (simd< T, SZ > src0, int flag = GENX_NOSAT)
Definition at line 1196 of file math.hpp.
References esimd_abs(), esimd_acos(), ESIMD_HDR_CONST_PI, GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge().
esimd_asin() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_floating_point<T>::value, T> cl::sycl::ext::intel::experimental::esimd::esimd_asin (T src0, int flag = GENX_NOSAT)
Definition at line 1213 of file math.hpp.
esimd_asr() [1/3]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_asr (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 322 of file math.hpp.
References GENX_SAT.
esimd_asr() [2/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_asr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 340 of file math.hpp.
esimd_asr() [3/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T1>::value && detail::is_esimd_vector<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, decltype(esimd_asr<T0>T2(), T1()))> cl::sycl::ext::intel::experimental::esimd::esimd_asr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 354 of file math.hpp.
esimd_atan() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_floating_point<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_atan (simd< T, SZ > src0, int flag = GENX_NOSAT)
Definition at line 1108 of file math.hpp.
References esimd_abs(), ESIMD_HDR_CONST_PI, GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge().
esimd_atan() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_floating_point<T>::value, T> cl::sycl::ext::intel::experimental::esimd::esimd_atan (T src0, int flag = GENX_NOSAT)
Definition at line 1139 of file math.hpp.
Referenced by esimd_atan2().
esimd_atan2() [1/4]
template<> ESIMD_INLINE float cl::sycl::ext::intel::experimental::esimd::esimd_atan2 (float y, float x, const uint flags)
Definition at line 1540 of file math.hpp.
References cl::sycl::atan2(), esimd_atan(), ESIMD_CONST_PI, and GENX_SAT.
esimd_atan2() [2/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_atan2 (simd< float, N > y, simd< float, N > x, const uint flags)
Definition at line 1521 of file math.hpp.
References cl::sycl::atan2(), esimd_atan(), ESIMD_CONST_PI, GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge().
esimd_atan2() [3/4]
template<int N> simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_atan2 (simd< float, N > y, simd< float, N > x, const uint flags = 0)
Definition at line 1521 of file math.hpp.
References cl::sycl::atan2(), esimd_atan(), ESIMD_CONST_PI, GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge().
esimd_atan2() [4/4]
template<typename T > float cl::sycl::ext::intel::experimental::esimd::esimd_atan2 (T y, T x, const uint flags = 0)
esimd_atan2_fast() [1/4]
template<> ESIMD_INLINE float cl::sycl::ext::intel::experimental::esimd::esimd_atan2_fast (float y, float x, const uint flags)
Definition at line 1511 of file math.hpp.
References cl::sycl::atan2().
esimd_atan2_fast() [2/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_atan2_fast (simd< float, N > y, simd< float, N > x, const uint flags)
Definition at line 1484 of file math.hpp.
References cl::sycl::atan2(), ESIMD_CONST_PI, ESIMD_DBL_EPSILON, GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge().
esimd_atan2_fast() [3/4]
template<int N> simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_atan2_fast (simd< float, N > y, simd< float, N > x, const uint flags = 0)
Definition at line 1484 of file math.hpp.
References cl::sycl::atan2(), ESIMD_CONST_PI, ESIMD_DBL_EPSILON, GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge().
esimd_atan2_fast() [4/4]
template<typename T > float cl::sycl::ext::intel::experimental::esimd::esimd_atan2_fast (T y, T x, const uint flags = 0)
esimd_bf_extract() [1/2]
template<typename T0 , typename T1 , typename T2 , typename T3 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T3>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_bf_extract (T1 src0, T2 src1, T3 src2)
Definition at line 988 of file math.hpp.
esimd_bf_extract() [2/2]
template<typename T0 , typename T1 , int SZ, typename U , typename V > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T1>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_bf_extract (U src0, V src1, simd< T1, SZ > src2)
Definition at line 973 of file math.hpp.
esimd_bf_insert() [1/2]
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T4>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_bf_insert (T1 src0, T2 src1, T3 src2, T4 src3)
Definition at line 962 of file math.hpp.
esimd_bf_insert() [2/2]
template<typename T0 , typename T1 , int SZ, typename U , typename V , typename W > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T1>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_bf_insert (U src0, V src1, W src2, simd< T1, SZ > src3)
Definition at line 946 of file math.hpp.
esimd_bf_reverse() [1/2]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T0, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_bf_reverse (simd< T1, SZ > src0)
Definition at line 926 of file math.hpp.
esimd_bf_reverse() [2/2]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_bf_reverse (T1 src0)
Definition at line 935 of file math.hpp.
esimd_cbit() [1/2]
template<typename T , int N> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T>::value, simd<uint, N> > cl::sycl::ext::intel::experimental::esimd::esimd_cbit (simd< T, N > src0)
Count component-wise the total bits set in source operand.
Definition at line 1276 of file math.hpp.
References __esimd_cbit(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_cbit() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral<T>::value && detail::is_esimd_scalar<T>::value, uint> cl::sycl::ext::intel::experimental::esimd::esimd_cbit (T src)
Definition at line 1283 of file math.hpp.
esimd_ceil() [1/2]
template<typename RT > ESIMD_INLINE RT cl::sycl::ext::intel::experimental::esimd::esimd_ceil (const float & src0, const uint flags = 0)
Definition at line 1425 of file math.hpp.
esimd_ceil() [2/2]
template<typename RT , int SZ> ESIMD_INLINE simd<RT, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_ceil (const simd< float, SZ > src0, const uint flags = 0)
Definition at line 1419 of file math.hpp.
esimd_cos_emu() [1/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_cos_emu (simd< float, N > x, const uint flags)
Definition at line 1668 of file math.hpp.
References CMPI, esimd_fmod(), GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_cos_emu() [2/4]
template<int N> simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_cos_emu (simd< float, N > x, const uint flags = 0)
Definition at line 1668 of file math.hpp.
References CMPI, esimd_fmod(), GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_cos_emu() [3/4]
template<typename T > float cl::sycl::ext::intel::experimental::esimd::esimd_cos_emu (T x, const uint flags = 0)
Definition at line 1705 of file math.hpp.
References CMPI, esimd_fmod(), GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_cos_emu() [4/4]
template<typename T > ESIMD_INLINE float cl::sycl::ext::intel::experimental::esimd::esimd_cos_emu (T x0, const uint flags)
Definition at line 1705 of file math.hpp.
References CMPI, esimd_fmod(), GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_div() [1/3]
template<typename T , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral<T>::value && std::is_integral<U>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_div (simd< T, SZ > & remainder, simd< T, SZ > src0, U src1)
Definition at line 473 of file math.hpp.
References cl::sycl::remainder().
esimd_div() [2/3]
template<typename T , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T>::value && std::is_integral<U>::value && detail::is_esimd_scalar<U>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_div (simd< T, SZ > & remainder, U src0, simd< T, SZ > src1)
Definition at line 484 of file math.hpp.
References cl::sycl::remainder().
esimd_div() [3/3]
template<typename RT , typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<RT>::value && detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value, typename sycl::detail::remove_const_t<RT> > cl::sycl::ext::intel::experimental::esimd::esimd_div (simd< typename std::remove_const< RT >, 1 > & remainder, T0 src0, T1 src1)
Definition at line 494 of file math.hpp.
References cl::sycl::remainder().
esimd_dp2()
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type<T1>::value && std::is_floating_point<T1>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_dp2 (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 698 of file math.hpp.
References GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select().
esimd_dp3()
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type<T1>::value && std::is_floating_point<T1>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_dp3 (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 720 of file math.hpp.
References GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select().
esimd_dp4() [1/2]
template<typename T , int N> simd<T, N> cl::sycl::ext::intel::experimental::esimd::esimd_dp4 (simd< T, N > v1, simd< T, N > v2)
Definition at line 1987 of file math.hpp.
esimd_dp4() [2/2]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type<T1>::value && std::is_floating_point<T1>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_dp4 (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 743 of file math.hpp.
References GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select().
esimd_dp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_dword_type<T1>::value && detail::is_dword_type<T2>::value && detail::is_dword_type<T3>::value && detail::is_dword_type<T4>::value, simd<T1, N> > cl::sycl::ext::intel::experimental::esimd::esimd_dp4a (simd< T2, N > src0, simd< T3, N > src1, simd< T4, N > src2, int flag = GENX_NOSAT)
DP4A.
Parameters
src0 the first source operand of dp4a operation.
src1 the second source operand of dp4a operation.
src2 the third source operand of dp4a operation.
flag saturation flag, which has default value of GENX_NOSAT.
Returns simd vector of the dp4a operation result.
Definition at line 1342 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data(), GENX_NOSAT, and GENX_SAT.
esimd_dph()
template<typename T , typename U , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type<T>::value && std::is_floating_point<T>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_dph (simd< T, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 766 of file math.hpp.
References GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select().
esimd_fbh() [1/3]
template<int N> ESIMD_NODEBUG ESIMD_INLINE simd<int, N> cl::sycl::ext::intel::experimental::esimd::esimd_fbh (simd< int, N > src)
Find component-wise the first bit from MSB side.
Definition at line 1304 of file math.hpp.
References __esimd_sfbh(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_fbh() [2/3]
template<int N> ESIMD_NODEBUG ESIMD_INLINE simd<unsigned int, N> cl::sycl::ext::intel::experimental::esimd::esimd_fbh (simd< unsigned int, N > src)
Definition at line 1310 of file math.hpp.
References __esimd_ufbh(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_fbh() [3/3]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_dword_type<T>::value && detail::is_esimd_scalar<T>::value, T> cl::sycl::ext::intel::experimental::esimd::esimd_fbh (T src)
Definition at line 1317 of file math.hpp.
esimd_fbl() [1/2]
template<int N> ESIMD_NODEBUG ESIMD_INLINE simd<unsigned, N> cl::sycl::ext::intel::experimental::esimd::esimd_fbl (simd< unsigned, N > src)
Find component-wise the first bit from LSB side.
Definition at line 1291 of file math.hpp.
References __esimd_fbl(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_fbl() [2/2]
template<typename T = void> ESIMD_NODEBUG ESIMD_INLINE unsigned cl::sycl::ext::intel::experimental::esimd::esimd_fbl (unsigned src)
Definition at line 1296 of file math.hpp.
esimd_floor() [1/2]
template<typename RT > ESIMD_INLINE RT cl::sycl::ext::intel::experimental::esimd::esimd_floor (const float & src0, const uint flags = 0)
Definition at line 1414 of file math.hpp.
esimd_floor() [2/2]
template<typename RT , int SZ> ESIMD_INLINE simd<RT, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_floor (const simd< float, SZ > src0, const uint flags = 0)
Definition at line 1408 of file math.hpp.
esimd_fmod() [1/4]
template<> ESIMD_INLINE float cl::sycl::ext::intel::experimental::esimd::esimd_fmod (float y, float x, const uint flags)
Definition at line 1574 of file math.hpp.
References cl::sycl::fmod(), and GENX_SAT.
Referenced by esimd_cos_emu(), and esimd_sin_emu().
esimd_fmod() [2/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_fmod (simd< float, N > y, simd< float, N > x, const uint flags)
Definition at line 1560 of file math.hpp.
References cl::sycl::fmod(), and GENX_SAT.
esimd_fmod() [3/4]
template<int N> simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_fmod (simd< float, N > y, simd< float, N > x, const uint flags = 0)
Definition at line 1560 of file math.hpp.
References cl::sycl::fmod(), and GENX_SAT.
esimd_fmod() [4/4]
template<typename T > float cl::sycl::ext::intel::experimental::esimd::esimd_fmod (T y, T x, const uint flags = 0)
esimd_frc() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_frc (simd< T, SZ > src0)
Definition at line 817 of file math.hpp.
References __esimd_frc().
esimd_frc() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE T cl::sycl::ext::intel::experimental::esimd::esimd_frc (T src0)
Definition at line 822 of file math.hpp.
esimd_imul() [1/3]
template<typename T0 , typename T , typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_esimd_scalar<T>::value && detail::is_esimd_scalar<U>::value && detail::is_esimd_scalar<T0>::value, T0> cl::sycl::ext::intel::experimental::esimd::esimd_imul (simd< T0, 1 > & rmd, T src0, U src1)
Definition at line 428 of file math.hpp.
Referenced by esimd_imul().
esimd_imul() [2/3]
template<typename T0 , typename T1 , typename U , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_dword_type<T0>::value && detail::is_dword_type<T1>::value && detail::is_dword_type<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_imul (simd< T0, SZ > & rmd, simd< T1, SZ > src0, U src1)
Definition at line 367 of file math.hpp.
References __esimd_smulh(), __esimd_umulh(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_imul() [3/3]
template<typename T0 , typename T1 , typename U , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_esimd_scalar<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_imul (simd< T0, SZ > & rmd, U src0, simd< T1, SZ > src1)
Definition at line 418 of file math.hpp.
References esimd_imul().
esimd_line() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_fp_or_dword_type<T>::value && std::is_floating_point<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_line (float P, float Q, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 808 of file math.hpp.
References P.
esimd_line() [2/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_fp_or_dword_type<T>::value && std::is_floating_point<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_line (simd< T, 4 > src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 787 of file math.hpp.
References GENX_SAT, and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select().
esimd_lrp()
template<typename T , int SZ, typename U , typename V > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_fp_or_dword_type<T>::value && std::is_floating_point<T>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_lrp (simd< T, SZ > src0, U src1, V src2, int flag = GENX_NOSAT)
Definition at line 883 of file math.hpp.
References GENX_SAT.
esimd_lsr() [1/3]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_lsr (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 279 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data(), and GENX_SAT.
esimd_lsr() [2/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_lsr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 297 of file math.hpp.
esimd_lsr() [3/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T1>::value && detail::is_esimd_vector<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, decltype(esimd_lsr<T0>T2(), T1()))> cl::sycl::ext::intel::experimental::esimd::esimd_lsr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 311 of file math.hpp.
esimd_lzd() [1/2]
template<typename RT , typename T0 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<RT, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_lzd (simd< T0, SZ > src0, int flag = GENX_NOSAT)
Definition at line 830 of file math.hpp.
esimd_lzd() [2/2]
template<typename RT , typename T0 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<RT>::value && detail::is_esimd_scalar<T0>::value, typename sycl::detail::remove_const_t<RT> > cl::sycl::ext::intel::experimental::esimd::esimd_lzd (T0 src0, int flag = GENX_NOSAT)
Definition at line 841 of file math.hpp.
esimd_max() [1/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_max (simd< T, SZ > src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 508 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data(), and GENX_NOSAT.
esimd_max() [2/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_esimd_scalar<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_max (simd< T, SZ > src0, T src1, int flag = GENX_NOSAT)
Definition at line 527 of file math.hpp.
esimd_max() [3/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_esimd_scalar<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_max (T src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 537 of file math.hpp.
esimd_max() [4/4]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_esimd_scalar<T>::value, T> cl::sycl::ext::intel::experimental::esimd::esimd_max (T src0, T src1, int flag = GENX_NOSAT)
Definition at line 546 of file math.hpp.
esimd_min() [1/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_min (simd< T, SZ > src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 555 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data(), and GENX_NOSAT.
esimd_min() [2/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_esimd_scalar<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_min (simd< T, SZ > src0, T src1, int flag = GENX_NOSAT)
Definition at line 574 of file math.hpp.
esimd_min() [3/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_esimd_scalar<T>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_min (T src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 584 of file math.hpp.
esimd_min() [4/4]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<detail::is_esimd_scalar<T>::value, T> cl::sycl::ext::intel::experimental::esimd::esimd_min (T src0, T src1, int flag = GENX_NOSAT)
Definition at line 592 of file math.hpp.
esimd_mod() [1/2]
template<typename T , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral<T>::value && std::is_integral<U>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_mod (simd< T, SZ > src0, U src1)
Definition at line 456 of file math.hpp.
esimd_mod() [2/2]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && std::is_integral<T0>::value && std::is_integral<T1>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_mod (T0 src0, T1 src1)
Definition at line 465 of file math.hpp.
esimd_pack_mask() [1/2]
template<int N> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<(N == 8 || N == 16 || N == 32), uint> cl::sycl::ext::intel::experimental::esimd::esimd_pack_mask (simd< ushort, N > src0)
Definition at line 1250 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_pack_mask() [2/2]
template<int N> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<(N != 8 && N != 16 && N < 32), uint> cl::sycl::ext::intel::experimental::esimd::esimd_pack_mask (simd< ushort, N > src0)
Definition at line 1265 of file math.hpp.
esimd_pln()
template<int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<float, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_pln (simd< float, 4 > src0, simd< float, SZ > src1, simd< float, SZ > src2, int flag = GENX_NOSAT)
Definition at line 898 of file math.hpp.
References GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::read(), and cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::select().
esimd_quot() [1/2]
template<typename T , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral<T>::value && std::is_integral<U>::value, simd<T, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_quot (simd< T, SZ > src0, U src1)
Definition at line 439 of file math.hpp.
esimd_quot() [2/2]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && std::is_integral<T0>::value && std::is_integral<T1>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_quot (T0 src0, T1 src1)
Definition at line 448 of file math.hpp.
esimd_rdtsc()
template<typename T = void> simd<uint, 4> cl::sycl::ext::intel::experimental::esimd::esimd_rdtsc ()
esimd_rol() [1/3]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral<T0>::value && std::is_integral<T1>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_rol (simd< T1, SZ > src0, simd< T1, SZ > src1)
Definition at line 204 of file math.hpp.
esimd_rol() [2/3]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_rol (simd< T1, SZ > src0, U src1)
Definition at line 214 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_rol() [3/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_rol (T1 src0, T2 src1)
Definition at line 228 of file math.hpp.
esimd_ror() [1/3]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< std::is_integral<T0>::value && std::is_integral<T1>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_ror (simd< T1, SZ > src0, simd< T1, SZ > src1)
Definition at line 240 of file math.hpp.
esimd_ror() [2/3]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_ror (simd< T1, SZ > src0, U src1)
Definition at line 250 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_ror() [3/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_ror (T1 src0, T2 src1)
Definition at line 264 of file math.hpp.
esimd_sat()
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T0, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_sat (simd< T1, SZ > src)
Definition at line 29 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data().
esimd_sbarrier()
ESIMD_NODEBUG void cl::sycl::ext::intel::experimental::esimd::esimd_sbarrier (EsimdSbarrierType flag) inline
Generic work-group split barrier.
Definition at line 611 of file memory.hpp.
References __esimd_sbarrier().
esimd_shl() [1/2]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_shl (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 118 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data(), and GENX_SAT.
esimd_shl() [2/2]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_shl (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 157 of file math.hpp.
esimd_shr() [1/2]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> > cl::sycl::ext::intel::experimental::esimd::esimd_shr (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 172 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::data(), and GENX_SAT.
esimd_shr() [2/2]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename sycl::detail::remove_const_t<T0> > cl::sycl::ext::intel::experimental::esimd::esimd_shr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 192 of file math.hpp.
esimd_sin_emu() [1/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_sin_emu (simd< float, N > x, const uint flags)
Definition at line 1591 of file math.hpp.
References CMPI, esimd_fmod(), GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_sin_emu() [2/4]
template<int N> simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_sin_emu (simd< float, N > x, const uint flags = 0)
Definition at line 1591 of file math.hpp.
References CMPI, esimd_fmod(), GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_sin_emu() [3/4]
template<typename T > float cl::sycl::ext::intel::experimental::esimd::esimd_sin_emu (T x, const uint flags = 0)
Definition at line 1628 of file math.hpp.
References CMPI, esimd_fmod(), GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_sin_emu() [4/4]
template<typename T > ESIMD_INLINE float cl::sycl::ext::intel::experimental::esimd::esimd_sin_emu (T x0, const uint flags)
Definition at line 1628 of file math.hpp.
References CMPI, esimd_fmod(), GENX_SAT, cl::sycl::ext::intel::experimental::esimd::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_sincos()
template<int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE simd<float, SZ> cl::sycl::ext::intel::experimental::esimd::esimd_sincos (simd< float, SZ > & dstcos, U src0, int flag = GENX_NOSAT)
Definition at line 1095 of file math.hpp.
esimd_tanh() [1/3]
ESIMD_INLINE float cl::sycl::ext::intel::experimental::esimd::esimd_tanh (float x)
Definition at line 1833 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::esimd_tanh_impl().
esimd_tanh() [2/3]
template<int N> simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_tanh (simd< float, N > x)
Definition at line 1837 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::esimd_tanh_impl().
esimd_tanh() [3/3]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_tanh (simd< float, N > x)
Definition at line 1837 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::esimd_tanh_impl().
esimd_tanh_cody_waite() [1/3]
ESIMD_INLINE float cl::sycl::ext::intel::experimental::esimd::esimd_tanh_cody_waite (float x)
Definition at line 1822 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::esimd_tanh_cody_waite_impl().
esimd_tanh_cody_waite() [2/3]
template<int N> simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_tanh_cody_waite (simd< float, N > x)
Definition at line 1827 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::esimd_tanh_cody_waite_impl().
esimd_tanh_cody_waite() [3/3]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::ext::intel::experimental::esimd::esimd_tanh_cody_waite (simd< float, N > x)
Definition at line 1827 of file math.hpp.
References cl::sycl::ext::intel::experimental::esimd::detail::esimd_tanh_cody_waite_impl().
esimd_unpack_mask()
template<int N> ESIMD_NODEBUG ESIMD_INLINE sycl::detail::enable_if_t<(N == 8 || N == 16 || N == 32), simd<ushort, N> > cl::sycl::ext::intel::experimental::esimd::esimd_unpack_mask (uint src0)
Definition at line 1258 of file math.hpp.
getBaseRegion() [1/2]
template<typename T , typename U > T cl::sycl::ext::intel::experimental::esimd::getBaseRegion (std::pair< T, U > Reg)
Definition at line 114 of file region.hpp.
getBaseRegion() [2/2]
template<typename T > T cl::sycl::ext::intel::experimental::esimd::getBaseRegion (T Reg)
Definition at line 113 of file region.hpp.
getTopRegion() [1/2]
template<typename T , typename U > T cl::sycl::ext::intel::experimental::esimd::getTopRegion (std::pair< T, U > Reg)
Definition at line 109 of file region.hpp.
getTopRegion() [2/2]
template<typename T > T cl::sycl::ext::intel::experimental::esimd::getTopRegion (T Reg)
Definition at line 108 of file region.hpp.
Referenced by cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::getOffsetX(), and cl::sycl::ext::intel::experimental::esimd::simd_view< BaseTy, RegionTy >::getOffsetY().
hmax()
template<typename T0 , typename T1 , int SZ> ESIMD_INLINE ESIMD_NODEBUG T0 cl::sycl::ext::intel::experimental::esimd::hmax (simd< T1, SZ > v)
Definition at line 1960 of file math.hpp.
hmin()
template<typename T0 , typename T1 , int SZ> ESIMD_INLINE ESIMD_NODEBUG T0 cl::sycl::ext::intel::experimental::esimd::hmin (simd< T1, SZ > v)
Definition at line 1967 of file math.hpp.
reduce()
template<typename T0 , typename T1 , int SZ, typename BinaryOperation > ESIMD_INLINE ESIMD_NODEBUG T0 cl::sycl::ext::intel::experimental::esimd::reduce (simd< T1, SZ > v, BinaryOperation op)
Definition at line 1974 of file math.hpp.
Variable Documentation
CMPI
constexpr auto cl::sycl::ext::intel::experimental::esimd::CMPI = 3.14159265f static constexpr
Definition at line 1586 of file math.hpp.
Referenced by esimd_cos_emu(), and esimd_sin_emu().
ESIMD_CONST_2PI
constexpr auto cl::sycl::ext::intel::experimental::esimd::ESIMD_CONST_2PI = 6.28318f static constexpr
Definition at line 1402 of file math.hpp.
ESIMD_CONST_E
constexpr auto cl::sycl::ext::intel::experimental::esimd::ESIMD_CONST_E = 2.71828f static constexpr
Definition at line 1400 of file math.hpp.
ESIMD_CONST_PI
constexpr auto cl::sycl::ext::intel::experimental::esimd::ESIMD_CONST_PI = 3.14159f static constexpr
Definition at line 1401 of file math.hpp.
Referenced by esimd_atan2(), and esimd_atan2_fast().
ESIMD_DBL_EPSILON
constexpr auto cl::sycl::ext::intel::experimental::esimd::ESIMD_DBL_EPSILON = 0.00001f static constexpr
Definition at line 1405 of file math.hpp.
Referenced by esimd_atan2_fast().