DPC++ Runtime: cl::sycl::intel::detail Namespace Reference
cl::sycl::intel::detail Namespace Reference
Classes
class __sycl_reduction_aux_kernel
class __sycl_reduction_main_kernel
These are the forward declaration for the classes that help to create names for additional kernels.
class atomic_ref_base
class atomic_ref_impl
class atomic_ref_impl< T *, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_pointer< T >::value > >
class atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >
class atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >
struct bit_equal
struct bit_equal< double >
struct bit_equal< float >
struct bit_equal< T, typename detail::enable_if_t< std::is_integral< T >::value > >
struct get_reduction_aux_kernel_name_t
struct get_reduction_main_kernel_name_t
Helper structs to get additional kernel name types based on given Name and Type types: if Name is undefined (is a auto_name) then Type becomes the Name.
struct memory_order_traits
struct memory_order_traits< memory_order::acq_rel >
struct memory_order_traits< memory_order::relaxed >
struct memory_order_traits< memory_order::seq_cst >
class reducer
Class that is used to represent objects that are passed to user's lambda functions and representing users' reduction variable.
class reducer< T, BinaryOperation, enable_if_t< IsKnownIdentityOp< T, BinaryOperation >::value > >
Specialization of the generic class 'reducer'.
class reduction_impl
This class encapsulates the reduction variable/accessor, the reduction operator and an optional operator identity.
Typedefs
using memory_order = cl::sycl::intel::memory_order
using memory_scope = cl::sycl::intel::memory_scope
template<typename T >
using IsValidAtomicType = bool_constant< std::is_arithmetic< T >::value||std::is_pointer< T >::value >
template<cl::sycl::access::address_space AS>
using IsValidAtomicAddressSpace = bool_constant< AS==access::address_space::global_space||AS==access::address_space::local_space||AS==access::address_space::global_device_space >
template<memory_order Order>
using IsValidDefaultOrder = bool_constant< Order==memory_order::relaxed||Order==memory_order::acq_rel||Order==memory_order::seq_cst >
template<typename T , class BinaryOperation >
using IsReduPlus = detail::bool_constant< std::is_same< BinaryOperation, intel::plus< T > >::value||std::is_same< BinaryOperation, intel::plus< void > >::value >
template<typename T , class BinaryOperation >
using IsReduMultiplies = detail::bool_constant< std::is_same< BinaryOperation, std::multiplies< T > >::value||std::is_same< BinaryOperation, std::multiplies< void > >::value >
template<typename T , class BinaryOperation >
using IsReduMinimum = detail::bool_constant< std::is_same< BinaryOperation, intel::minimum< T > >::value||std::is_same< BinaryOperation, intel::minimum< void > >::value >
template<typename T , class BinaryOperation >
using IsReduMaximum = detail::bool_constant< std::is_same< BinaryOperation, intel::maximum< T > >::value||std::is_same< BinaryOperation, intel::maximum< void > >::value >
template<typename T , class BinaryOperation >
using IsReduBitOR = detail::bool_constant< std::is_same< BinaryOperation, intel::bit_or< T > >::value||std::is_same< BinaryOperation, intel::bit_or< void > >::value >
template<typename T , class BinaryOperation >
using IsReduBitXOR = detail::bool_constant< std::is_same< BinaryOperation, intel::bit_xor< T > >::value||std::is_same< BinaryOperation, intel::bit_xor< void > >::value >
template<typename T , class BinaryOperation >
using IsReduBitAND = detail::bool_constant< std::is_same< BinaryOperation, intel::bit_and< T > >::value||std::is_same< BinaryOperation, intel::bit_and< void > >::value >
template<typename T , class BinaryOperation >
using IsReduOptForFastAtomicFetch = detail::bool_constant<(is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&(IsReduPlus< T, BinaryOperation >::value||IsReduMinimum< T, BinaryOperation >::value||IsReduMaximum< T, BinaryOperation >::value||IsReduBitOR< T, BinaryOperation >::value||IsReduBitXOR< T, BinaryOperation >::value||IsReduBitAND< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsReduOptForFastReduce = detail::bool_constant<(is_geninteger32bit< T >::value||is_geninteger64bit< T >::value||std::is_same< T, half >::value||std::is_same< T, float >::value||std::is_same< T, double >::value) &&(IsReduPlus< T, BinaryOperation >::value||IsReduMinimum< T, BinaryOperation >::value||IsReduMaximum< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsZeroIdentityOp = bool_constant<((is_geninteger8bit< T >::value||is_geninteger16bit< T >::value||is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&(IsReduPlus< T, BinaryOperation >::value||IsReduBitOR< T, BinaryOperation >::value||IsReduBitXOR< T, BinaryOperation >::value))||((std::is_same< T, half >::value||std::is_same< T, float >::value||std::is_same< T, double >::value) &&IsReduPlus< T, BinaryOperation >::value)>
template<typename T , class BinaryOperation >
using IsOneIdentityOp = bool_constant<(is_geninteger8bit< T >::value||is_geninteger16bit< T >::value||is_geninteger32bit< T >::value||is_geninteger64bit< T >::value||std::is_same< T, half >::value||std::is_same< T, float >::value||std::is_same< T, double >::value) &&IsReduMultiplies< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsOnesIdentityOp = bool_constant<(is_geninteger8bit< T >::value||is_geninteger16bit< T >::value||is_geninteger32bit< T >::value||is_geninteger64bit< T >::value) &&IsReduBitAND< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsMinimumIdentityOp = bool_constant<(is_geninteger8bit< T >::value||is_geninteger16bit< T >::value||is_geninteger32bit< T >::value||is_geninteger64bit< T >::value||std::is_same< T, half >::value||std::is_same< T, float >::value||std::is_same< T, double >::value) &&IsReduMinimum< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsMaximumIdentityOp = bool_constant<(is_geninteger8bit< T >::value||is_geninteger16bit< T >::value||is_geninteger32bit< T >::value||is_geninteger64bit< T >::value||std::is_same< T, half >::value||std::is_same< T, float >::value||std::is_same< T, double >::value) &&IsReduMaximum< T, BinaryOperation >::value >
template<typename T , class BinaryOperation >
using IsKnownIdentityOp = bool_constant< IsZeroIdentityOp< T, BinaryOperation >::value||IsOneIdentityOp< T, BinaryOperation >::value||IsOnesIdentityOp< T, BinaryOperation >::value||IsMinimumIdentityOp< T, BinaryOperation >::value||IsMaximumIdentityOp< T, BinaryOperation >::value >
Functions
template<typename KernelName , typename KernelType , int Dims, class Reduction , typename OutputT >
enable_if_t< Reduction::has_fast_atomics > reduCGFunc (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &Redu, OutputT Out)
template<typename KernelName , typename KernelType , int Dims, class Reduction >
enable_if_t<!Reduction::has_fast_atomics > reduCGFunc (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &Redu)
template<typename KernelName , typename KernelType , int Dims, class Reduction >
enable_if_t<!Reduction::has_fast_atomics > reduAuxCGFunc (handler &CGH, const nd_range< Dims > &Range, size_t NWorkItems, Reduction &Redu)
static constexpr std::memory_order getStdMemoryOrder (::cl::sycl::intel::memory_order order)
constexpr memory_order getLoadOrder (memory_order order)
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformWG, typename OutputT >
enable_if_t< Reduction::has_fast_reduce &&Reduction::has_fast_atomics > reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &, OutputT Out)
Implements a command group function that enqueues a kernel that calls user's lambda function KernelFunc and also does one iteration of reduction of elements computed in user's lambda function.
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformPow2WG, typename OutputT >
enable_if_t<!Reduction::has_fast_reduce &&Reduction::has_fast_atomics > reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &Redu, OutputT Out)
Implements a command group function that enqueues a kernel that calls user's lambda function KernelFunc and also does one iteration of reduction of elements computed in user's lambda function.
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformWG, typename OutputT >
enable_if_t< Reduction::has_fast_reduce &&!Reduction::has_fast_atomics > reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &, OutputT Out)
Implements a command group function that enqueues a kernel that calls user's lambda function and does one iteration of reduction of elements in each of work-groups.
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformPow2WG, typename OutputT >
enable_if_t<!Reduction::has_fast_reduce &&!Reduction::has_fast_atomics > reduCGFuncImpl (handler &CGH, KernelType KernelFunc, const nd_range< Dims > &Range, Reduction &Redu, OutputT Out)
Implements a command group function that enqueues a kernel that calls user's lambda function.
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformWG, typename InputT , typename OutputT >
enable_if_t< Reduction::has_fast_reduce &&!Reduction::has_fast_atomics > reduAuxCGFuncImpl (handler &CGH, const nd_range< Dims > &Range, size_t NWorkItems, Reduction &, InputT In, OutputT Out)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformPow2WG, typename InputT , typename OutputT >
enable_if_t<!Reduction::has_fast_reduce &&!Reduction::has_fast_atomics > reduAuxCGFuncImpl (handler &CGH, const nd_range< Dims > &Range, size_t NWorkItems, Reduction &Redu, InputT In, OutputT Out)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
Typedef Documentation
IsKnownIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsKnownIdentityOp = typedef bool_constant<IsZeroIdentityOp<T, BinaryOperation>::value || IsOneIdentityOp<T, BinaryOperation>::value || IsOnesIdentityOp<T, BinaryOperation>::value || IsMinimumIdentityOp<T, BinaryOperation>::value || IsMaximumIdentityOp<T, BinaryOperation>::value>
Definition at line 135 of file reduction.hpp.
IsMaximumIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsMaximumIdentityOp = typedef bool_constant< (is_geninteger8bit<T>::value || is_geninteger16bit<T>::value || is_geninteger32bit<T>::value || is_geninteger64bit<T>::value || std::is_same<T, half>::value || std::is_same<T, float>::value || std::is_same<T, double>::value) && IsReduMaximum<T, BinaryOperation>::value>
Definition at line 127 of file reduction.hpp.
IsMinimumIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsMinimumIdentityOp = typedef bool_constant< (is_geninteger8bit<T>::value || is_geninteger16bit<T>::value || is_geninteger32bit<T>::value || is_geninteger64bit<T>::value || std::is_same<T, half>::value || std::is_same<T, float>::value || std::is_same<T, double>::value) && IsReduMinimum<T, BinaryOperation>::value>
Definition at line 118 of file reduction.hpp.
IsOneIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsOneIdentityOp = typedef bool_constant< (is_geninteger8bit<T>::value || is_geninteger16bit<T>::value || is_geninteger32bit<T>::value || is_geninteger64bit<T>::value || std::is_same<T, half>::value || std::is_same<T, float>::value || std::is_same<T, double>::value) && IsReduMultiplies<T, BinaryOperation>::value>
Definition at line 102 of file reduction.hpp.
IsOnesIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsOnesIdentityOp = typedef bool_constant< (is_geninteger8bit<T>::value || is_geninteger16bit<T>::value || is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && IsReduBitAND<T, BinaryOperation>::value>
Definition at line 109 of file reduction.hpp.
IsReduBitAND
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduBitAND = typedef detail::bool_constant< std::is_same<BinaryOperation, intel::bit_and<T> >::value || std::is_same<BinaryOperation, intel::bit_and<void> >::value>
Definition at line 61 of file reduction.hpp.
IsReduBitOR
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduBitOR = typedef detail::bool_constant< std::is_same<BinaryOperation, intel::bit_or<T> >::value || std::is_same<BinaryOperation, intel::bit_or<void> >::value>
Definition at line 51 of file reduction.hpp.
IsReduBitXOR
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduBitXOR = typedef detail::bool_constant< std::is_same<BinaryOperation, intel::bit_xor<T> >::value || std::is_same<BinaryOperation, intel::bit_xor<void> >::value>
Definition at line 56 of file reduction.hpp.
IsReduMaximum
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduMaximum = typedef detail::bool_constant< std::is_same<BinaryOperation, intel::maximum<T> >::value || std::is_same<BinaryOperation, intel::maximum<void> >::value>
Definition at line 46 of file reduction.hpp.
IsReduMinimum
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduMinimum = typedef detail::bool_constant< std::is_same<BinaryOperation, intel::minimum<T> >::value || std::is_same<BinaryOperation, intel::minimum<void> >::value>
Definition at line 41 of file reduction.hpp.
IsReduMultiplies
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduMultiplies = typedef detail::bool_constant< std::is_same<BinaryOperation, std::multiplies<T> >::value || std::is_same<BinaryOperation, std::multiplies<void> >::value>
Definition at line 36 of file reduction.hpp.
IsReduOptForFastAtomicFetch
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduOptForFastAtomicFetch = typedef detail::bool_constant<(is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && (IsReduPlus<T, BinaryOperation>::value || IsReduMinimum<T, BinaryOperation>::value || IsReduMaximum<T, BinaryOperation>::value || IsReduBitOR<T, BinaryOperation>::value || IsReduBitXOR<T, BinaryOperation>::value || IsReduBitAND<T, BinaryOperation>::value)>
Definition at line 72 of file reduction.hpp.
IsReduOptForFastReduce
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduOptForFastReduce = typedef detail::bool_constant< (is_geninteger32bit<T>::value || is_geninteger64bit<T>::value || std::is_same<T, half>::value || std::is_same<T, float>::value || std::is_same<T, double>::value) && (IsReduPlus<T, BinaryOperation>::value || IsReduMinimum<T, BinaryOperation>::value || IsReduMaximum<T, BinaryOperation>::value)>
Definition at line 81 of file reduction.hpp.
IsReduPlus
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsReduPlus = typedef detail::bool_constant< std::is_same<BinaryOperation, intel::plus<T> >::value || std::is_same<BinaryOperation, intel::plus<void> >::value>
Definition at line 31 of file reduction.hpp.
IsValidAtomicAddressSpace
template<cl::sycl::access::address_space AS> using cl::sycl::intel::detail::IsValidAtomicAddressSpace = typedef bool_constant<AS == access::address_space::global_space || AS == access::address_space::local_space || AS == access::address_space::global_device_space>
Definition at line 47 of file atomic_ref.hpp.
IsValidAtomicType
template<typename T > using cl::sycl::intel::detail::IsValidAtomicType = typedef bool_constant<std::is_arithmetic<T>::value || std::is_pointer<T>::value>
Definition at line 41 of file atomic_ref.hpp.
IsValidDefaultOrder
template<memory_order Order> using cl::sycl::intel::detail::IsValidDefaultOrder = typedef bool_constant<Order == memory_order::relaxed || Order == memory_order::acq_rel || Order == memory_order::seq_cst>
Definition at line 53 of file atomic_ref.hpp.
IsZeroIdentityOp
template<typename T , class BinaryOperation > using cl::sycl::intel::detail::IsZeroIdentityOp = typedef bool_constant< ((is_geninteger8bit<T>::value || is_geninteger16bit<T>::value || is_geninteger32bit<T>::value || is_geninteger64bit<T>::value) && (IsReduPlus<T, BinaryOperation>::value || IsReduBitOR<T, BinaryOperation>::value || IsReduBitXOR<T, BinaryOperation>::value)) || ((std::is_same<T, half>::value || std::is_same<T, float>::value || std::is_same<T, double>::value) && IsReduPlus<T, BinaryOperation>::value)>
Definition at line 93 of file reduction.hpp.
memory_order
using cl::sycl::intel::detail::memory_order = typedef cl::sycl::intel::memory_order
Definition at line 36 of file atomic_ref.hpp.
memory_scope
using cl::sycl::intel::detail::memory_scope = typedef cl::sycl::intel::memory_scope
Definition at line 37 of file atomic_ref.hpp.
Function Documentation
getLoadOrder()
constexpr memory_order cl::sycl::intel::detail::getLoadOrder (memory_order order) inline
Definition at line 91 of file atomic_ref.hpp.
References cl::sycl::intel::memory_order_acquire, cl::sycl::intel::memory_order_relaxed, and cl::sycl::intel::memory_order_seq_cst.
Referenced by cl::sycl::intel::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >::fetch_add(), cl::sycl::intel::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_max(), cl::sycl::intel::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >::fetch_max(), cl::sycl::intel::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_integral< T >::value > >::fetch_min(), cl::sycl::intel::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >::fetch_min(), and cl::sycl::intel::detail::atomic_ref_impl< T, DefaultOrder, DefaultScope, AddressSpace, typename detail::enable_if_t< std::is_floating_point< T >::value > >::fetch_sub().
getStdMemoryOrder()
static constexpr std::memory_order cl::sycl::intel::detail::getStdMemoryOrder (::cl::sycl::intel::memory_order order) inline static
Definition at line 84 of file atomic_enums.hpp.
References cl::sycl::intel::memory_order_acq_rel, cl::sycl::intel::memory_order_acquire, cl::sycl::intel::memory_order_relaxed, cl::sycl::intel::memory_order_release, and cl::sycl::intel::memory_order_seq_cst.
reduAuxCGFunc()
template<typename KernelName , typename KernelType , int Dims, class Reduction > enable_if_t<!Reduction::has_fast_atomics > cl::sycl::intel::detail::reduAuxCGFunc (handler & CGH, const nd_range< Dims > & Range, size_t NWorkItems, Reduction & Redu)
Definition at line 967 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_group_range(), and cl::sycl::nd_range< dimensions >::get_local_range().
reduAuxCGFuncImpl() [1/2]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformWG, typename InputT , typename OutputT > enable_if_t<Reduction::has_fast_reduce && !Reduction::has_fast_atomics> cl::sycl::intel::detail::reduAuxCGFuncImpl (handler & CGH, const nd_range< Dims > & Range, size_t NWorkItems, Reduction & , InputT In, OutputT Out)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
This version uses intel::reduce() algorithm to reduce elements in each of work-groups. At the end of each work-groups the partial sum is written to a global buffer.
Briefly: aux kernel, intel:reduce(), reproducible results,FP + ADD/MIN/MAX
Definition at line 874 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_group_range(), cl::sycl::handler::parallel_for(), and cl::sycl::intel::gpu::reduce().
reduAuxCGFuncImpl() [2/2]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformPow2WG, typename InputT , typename OutputT > enable_if_t<!Reduction::has_fast_reduce && !Reduction::has_fast_atomics> cl::sycl::intel::detail::reduAuxCGFuncImpl (handler & CGH, const nd_range< Dims > & Range, size_t NWorkItems, Reduction & Redu, InputT In, OutputT Out)
Implements a command group function that enqueues a kernel that does one iteration of reduction of elements in each of work-groups.
This version uses tree-reduction algorithm to reduce elements in each of work-groups. At the end of each work-group the partial sum is written to a global buffer.
Briefly: aux kernel, tree-reduction, CUSTOM types/ops.
Definition at line 909 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_group_range(), cl::sycl::nd_range< dimensions >::get_local_range(), and cl::sycl::handler::parallel_for().
reduCGFunc() [1/2]
template<typename KernelName , typename KernelType , int Dims, class Reduction , typename OutputT > enable_if_t< Reduction::has_fast_atomics > cl::sycl::intel::detail::reduCGFunc (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & Redu, OutputT Out)
Definition at line 698 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_global_range(), cl::sycl::nd_range< dimensions >::get_group_range(), and cl::sycl::nd_range< dimensions >::get_local_range().
reduCGFunc() [2/2]
template<typename KernelName , typename KernelType , int Dims, class Reduction > enable_if_t<!Reduction::has_fast_atomics > cl::sycl::intel::detail::reduCGFunc (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & Redu)
Definition at line 833 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_global_range(), cl::sycl::nd_range< dimensions >::get_group_range(), and cl::sycl::nd_range< dimensions >::get_local_range().
reduCGFuncImpl() [1/4]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformWG, typename OutputT > enable_if_t<Reduction::has_fast_reduce && Reduction::has_fast_atomics> cl::sycl::intel::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & , OutputT Out)
Implements a command group function that enqueues a kernel that calls user's lambda function KernelFunc and also does one iteration of reduction of elements computed in user's lambda function.
This version uses intel::reduce() algorithm to reduce elements in each of work-groups, then it calls fast sycl atomic operations to update user's reduction variable.
Briefly: calls user's lambda, intel::reduce() + atomic, INT + ADD/MIN/MAX.
Definition at line 610 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_global_range(), cl::sycl::handler::parallel_for(), and cl::sycl::intel::gpu::reduce().
reduCGFuncImpl() [2/4]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformPow2WG, typename OutputT > enable_if_t<!Reduction::has_fast_reduce && Reduction::has_fast_atomics> cl::sycl::intel::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & Redu, OutputT Out)
Implements a command group function that enqueues a kernel that calls user's lambda function KernelFunc and also does one iteration of reduction of elements computed in user's lambda function.
This version uses tree-reduction algorithm to reduce elements in each of work-groups, then it calls fast sycl atomic operations to update user's reduction variable.
Briefly: calls user's lambda, tree-reduction + atomic, INT + AND/OR/XOR.
Definition at line 642 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_global_range(), cl::sycl::nd_range< dimensions >::get_local_range(), and cl::sycl::handler::parallel_for().
reduCGFuncImpl() [3/4]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformWG, typename OutputT > enable_if_t<Reduction::has_fast_reduce && !Reduction::has_fast_atomics> cl::sycl::intel::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & , OutputT Out)
Implements a command group function that enqueues a kernel that calls user's lambda function and does one iteration of reduction of elements in each of work-groups.
This version uses intel::reduce() algorithm to reduce elements in each of work-groups. At the end of each work-groups the partial sum is written to a global buffer.
Briefly: user's lambda, intel:reduce(), FP + ADD/MIN/MAX.
Definition at line 727 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_global_range(), cl::sycl::nd_range< dimensions >::get_group_range(), cl::sycl::handler::parallel_for(), and cl::sycl::intel::gpu::reduce().
reduCGFuncImpl() [4/4]
template<typename KernelName , typename KernelType , int Dims, class Reduction , bool UniformPow2WG, typename OutputT > enable_if_t<!Reduction::has_fast_reduce && !Reduction::has_fast_atomics> cl::sycl::intel::detail::reduCGFuncImpl (handler & CGH, KernelType KernelFunc, const nd_range< Dims > & Range, Reduction & Redu, OutputT Out)
Implements a command group function that enqueues a kernel that calls user's lambda function.
Parameters
KernelFunc and does one iteration of reduction of elements in each of work-groups. This version uses tree-reduction algorithm to reduce elements in each of work-groups. At the end of each work-group the partial sum is written to a global buffer.
Briefly: user's lambda, tree-reduction, CUSTOM types/ops.
Definition at line 773 of file reduction.hpp.
References cl::sycl::nd_range< dimensions >::get_global_range(), cl::sycl::nd_range< dimensions >::get_group_range(), cl::sycl::nd_range< dimensions >::get_local_range(), and cl::sycl::handler::parallel_for().