DPC++ Runtime: sycl::_V1::ext::oneapi::experimental::native Namespace Reference
sycl::_V1::ext::oneapi::experimental::native Namespace Reference
Functions
template<typename T >
__SYCL_ALWAYS_INLINE std::enable_if_t< sycl::detail::is_svgenfloatf_v< T >||sycl::detail::is_svgenfloath_v< T >, T > tanh (T x) __NOEXC
template<typename T , size_t N>
__SYCL_ALWAYS_INLINE std::enable_if_t< std::is_same_v< T, half >||std::is_same_v< T, float >, sycl::marray< T, N > > tanh (sycl::marray< T, N > x) __NOEXC
template<typename T >
__SYCL_ALWAYS_INLINE std::enable_if_t< sycl::detail::is_svgenfloath_v< T >, T > exp2 (T x) __NOEXC
template<size_t N>
__SYCL_ALWAYS_INLINE sycl::marray< half, N > exp2 (sycl::marray< half, N > x) __NOEXC
Function Documentation
exp2() [1/2]
template<size_t N> __SYCL_ALWAYS_INLINE sycl::marray<half, N> sycl::_V1::ext::oneapi::experimental::native::exp2 (sycl::marray< half, N > x) inline
Definition at line 157 of file builtins.hpp.
References exp2(), and sycl::_V1::detail::to_vec2().
Referenced by exp2().
exp2() [2/2]
template<typename T > __SYCL_ALWAYS_INLINE std::enable_if_t<sycl::detail::is_svgenfloath_v<T>, T> sycl::_V1::ext::oneapi::experimental::native::exp2 (T x) inline
Definition at line 144 of file builtins.hpp.
References sycl::_V1::detail::convertToOpenCLType(), and exp2().
Referenced by exp2().
tanh() [1/2]
template<typename T , size_t N> __SYCL_ALWAYS_INLINE std::enable_if_t<std::is_same_v<T, half> || std::is_same_v<T, float>, sycl::marray<T, N> > sycl::_V1::ext::oneapi::experimental::native::tanh (sycl::marray< T, N > x) inline
Definition at line 116 of file builtins.hpp.
References tanh(), and sycl::_V1::detail::to_vec2().
Referenced by tanh().
tanh() [2/2]
template<typename T > __SYCL_ALWAYS_INLINE std::enable_if_t< sycl::detail::is_svgenfloatf_v<T> || sycl::detail::is_svgenfloath_v<T>, T> sycl::_V1::ext::oneapi::experimental::native::tanh (T x) inline
Definition at line 96 of file builtins.hpp.
References sycl::_V1::detail::convertToOpenCLType(), and tanh().
Referenced by tanh().