DPC++ Runtime: cl::sycl::ext::oneapi::experimental Namespace Reference
cl::sycl::ext::oneapi::experimental Namespace Reference
Namespaces
detail
matrix
native
Classes
struct device_image_scope_key
struct host_access_key
struct implement_in_csr_key
struct init_mode_key
struct is_property_key
struct is_property_key< device_image_scope_key >
struct is_property_key< host_access_key >
struct is_property_key< implement_in_csr_key >
struct is_property_key< init_mode_key >
struct is_property_key_of
struct is_property_list
struct is_property_list< properties< std::tuple< PropertyValueTs... > > >
struct is_property_value
struct is_property_value< V, sycl::detail::void_t< typename V::key_t > >
struct is_property_value_of
struct is_property_value_of< V, O, sycl::detail::void_t< typename V::key_t > >
class properties
struct property_value
class spec_const_error
Enumerations
enum host_access_enum : std::uint16_t { host_access_enum::read, host_access_enum::write, host_access_enum::read_write, host_access_enum::none }
enum init_mode_enum : std::uint16_t { init_mode_enum::reprogram, init_mode_enum::reset }
Functions
template<int Dims>
group< Dims > this_group ()
template<int Dims>
id< Dims > this_id ()
template<int Dims>
item< Dims > this_item ()
template<int Dims>
nd_item< Dims > this_nd_item ()
sub_group this_sub_group ()
template<typename FormatT , typename... Args>
int printf (const FormatT *__format, Args... args)
template<typename T , typename ID = T>
class __SYCL2020_DEPRECATED ("Specialization constats extension is deprecated, use SYCL 2020" " specialization constants instead") spec_constant
template<typename PropertyT , typename... A, typename... B>
constexpr std::enable_if_t< detail::IsCompileTimeProperty< PropertyT >::value, bool > operator== (const property_value< PropertyT, A... > &, const property_value< PropertyT, B... > &)
template<typename PropertyT , typename... A, typename... B>
constexpr std::enable_if_t< detail::IsCompileTimeProperty< PropertyT >::value, bool > operator!= (const property_value< PropertyT, A... > &, const property_value< PropertyT, B... > &)
Variables
constexpr device_image_scope_key::value_t device_image_scope
template<host_access_enum Access>
constexpr host_access_key::value_t< Access > host_access
constexpr host_access_key::value_t< host_access_enum::read > host_access_read
constexpr host_access_key::value_t< host_access_enum::write > host_access_write
constexpr host_access_key::value_t< host_access_enum::read_write > host_access_read_write
constexpr host_access_key::value_t< host_access_enum::none > host_access_none
template<init_mode_enum Trigger>
constexpr init_mode_key::value_t< Trigger > init_mode
constexpr init_mode_key::value_t< init_mode_enum::reprogram > init_mode_reprogram
constexpr init_mode_key::value_t< init_mode_enum::reset > init_mode_reset
template<bool Enable>
constexpr implement_in_csr_key::value_t< Enable > implement_in_csr
constexpr implement_in_csr_key::value_t< true > implement_in_csr_on
constexpr implement_in_csr_key::value_t< false > implement_in_csr_off
Enumeration Type Documentation
host_access_enum
enum cl::sycl::ext::oneapi::experimental::host_access_enum : std::uint16_t strong
Enumerator
read
write
read_write
none
Definition at line 24 of file properties.hpp.
init_mode_enum
enum cl::sycl::ext::oneapi::experimental::init_mode_enum : std::uint16_t strong
Enumerator
reprogram
reset
Definition at line 33 of file properties.hpp.
Function Documentation
__SYCL2020_DEPRECATED()
template<typename T , typename ID = T> class cl::sycl::ext::oneapi::experimental::__SYCL2020_DEPRECATED ("Specialization constats extension is deprecated, use SYCL 2020" " specialization constants instead")
Definition at line 35 of file spec_constant.hpp.
References std::get().
operator!=()
template<typename PropertyT , typename... A, typename... B> constexpr std::enable_if_t<detail::IsCompileTimeProperty<PropertyT>::value, bool> cl::sycl::ext::oneapi::experimental::operator!= (const property_value< PropertyT, A... > & , const property_value< PropertyT, B... > &) constexpr
Definition at line 62 of file property_value.hpp.
operator==()
template<typename PropertyT , typename... A, typename... B> constexpr std::enable_if_t<detail::IsCompileTimeProperty<PropertyT>::value, bool> cl::sycl::ext::oneapi::experimental::operator== (const property_value< PropertyT, A... > & , const property_value< PropertyT, B... > &) constexpr
Definition at line 54 of file property_value.hpp.
printf()
template<typename FormatT , typename... Args> int cl::sycl::ext::oneapi::experimental::printf (const FormatT * __format, Args... args)
Definition at line 76 of file builtins.hpp.
Referenced by cl::sycl::detail::stream_impl::flush().
this_group()
template<int Dims> group<Dims> cl::sycl::ext::oneapi::experimental::this_group ()
Definition at line 547 of file group.hpp.
References cl::sycl::detail::declptr(), and cl::sycl::make_error_code().
this_id()
template<int Dims> id<Dims> cl::sycl::ext::oneapi::experimental::this_id ()
Definition at line 361 of file id.hpp.
References cl::sycl::detail::declptr(), and cl::sycl::make_error_code().
this_item()
template<int Dims> item<Dims> cl::sycl::ext::oneapi::experimental::this_item ()
Definition at line 151 of file item.hpp.
References cl::sycl::detail::declptr(), and cl::sycl::make_error_code().
this_nd_item()
template<int Dims> nd_item<Dims> cl::sycl::ext::oneapi::experimental::this_nd_item ()
Definition at line 208 of file nd_item.hpp.
References cl::sycl::detail::declptr(), and cl::sycl::make_error_code().
this_sub_group()
sub_group cl::sycl::ext::oneapi::experimental::this_sub_group () inline
Definition at line 23 of file sub_group.hpp.
References PI_INVALID_DEVICE.
Variable Documentation
device_image_scope
constexpr device_image_scope_key::value_t cl::sycl::ext::oneapi::experimental::device_image_scope inline constexpr
Definition at line 48 of file properties.hpp.
host_access
template<host_access_enum Access> constexpr host_access_key::value_t<Access> cl::sycl::ext::oneapi::experimental::host_access inline constexpr
Definition at line 51 of file properties.hpp.
host_access_none
constexpr host_access_key::value_t<host_access_enum::none> cl::sycl::ext::oneapi::experimental::host_access_none inline constexpr
Definition at line 59 of file properties.hpp.
host_access_read
constexpr host_access_key::value_t<host_access_enum::read> cl::sycl::ext::oneapi::experimental::host_access_read inline constexpr
Definition at line 53 of file properties.hpp.
host_access_read_write
constexpr host_access_key::value_t<host_access_enum::read_write> cl::sycl::ext::oneapi::experimental::host_access_read_write inline constexpr
Definition at line 57 of file properties.hpp.
host_access_write
constexpr host_access_key::value_t<host_access_enum::write> cl::sycl::ext::oneapi::experimental::host_access_write inline constexpr
Definition at line 55 of file properties.hpp.
implement_in_csr
template<bool Enable> constexpr implement_in_csr_key::value_t<Enable> cl::sycl::ext::oneapi::experimental::implement_in_csr inline constexpr
Definition at line 68 of file properties.hpp.
implement_in_csr_off
constexpr implement_in_csr_key::value_t<false> cl::sycl::ext::oneapi::experimental::implement_in_csr_off inline constexpr
Definition at line 70 of file properties.hpp.
implement_in_csr_on
constexpr implement_in_csr_key::value_t<true> cl::sycl::ext::oneapi::experimental::implement_in_csr_on inline constexpr
Definition at line 69 of file properties.hpp.
init_mode
template<init_mode_enum Trigger> constexpr init_mode_key::value_t<Trigger> cl::sycl::ext::oneapi::experimental::init_mode inline constexpr
Definition at line 62 of file properties.hpp.
init_mode_reprogram
constexpr init_mode_key::value_t<init_mode_enum::reprogram> cl::sycl::ext::oneapi::experimental::init_mode_reprogram inline constexpr
Definition at line 64 of file properties.hpp.
init_mode_reset
constexpr init_mode_key::value_t<init_mode_enum::reset> cl::sycl::ext::oneapi::experimental::init_mode_reset inline constexpr
Definition at line 65 of file properties.hpp.